### ISSUE TITLE
kvanttifysiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10005]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kvanttifysiikka](http://www.yso.fi/onto/yso/p5564)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käsitteet kvanttifysiikka, kvanttimekaniikka ja kvanttiteoria tulisi yhdistää. Sama yhdistäminen tulisi tehdä englannin ja ruotsin vastaaville termeille.

**Perustelut ehdotukselle**

Termit vastaavat toisiaan täysin näissä kolmessa kielessä, joten riittää tarkastella englanninkielisten sanojen merkitystä. Library of congress (https://id.loc.gov/authorities/subjects/sh85109469.html) luokittelee termit toistensa varianteiksi.  Merriam-Websterin (yksi) määritelmä termille "Quantum theory" on "Quantum mechanics" (https://www.merriam-webster.com/dictionary/quantum%20theory).

**Ehdottajan organisaatio**

Jyväskylän yliopisto, Fysiikan laitos

**Comment by ristoja** [comment]
Kvanttimekaniikka on yleisimmin käytetty termi, joten ehdotan että muut käsitteet ohjataan siihen. _Mekaniikka_ tulee poistaa  kvanttimekaniikan yläkäsitteistä, sillä mekaniikka viittaa _klassiseen mekaniikkaan_.

**Comment by mariaforsen** [comment]
SAOssa ja Natiionalencyklopedinissä on kaksi eri käsitettä: 
-kvantteori (ohjaustermi kvantmekanik) Ks. myös https://svenska.se/tre/?sok=kvantteori&pz=1
-kvantfysik = "gren av fysiken som började utvecklas omkring sekelskiftet 1900 och som beskriver atomära och subatomära system – även kallade mikrokosmos" /NE Myös lisäselityksenä: "Kvantfysiken utgör basen för Bohrs revolutionerande atommodell liksom för den mer sofistikerade modell för atomära system som kvantmekaniken utgör." Ja kvantmekanik=kvantteori: "teorin för det system av naturlagar som har upptäckts vid studiet av mikroskopiska system som molekyler, atomer, atomkärnor och elementarpartiklar."

**Comment by ristoja** [comment]
Melindassa kvanttimekaniikan perustason oppikirjoja ja jopa saman oppikirjan eri painoksia on luokiteltu vaihtelevasti kaikkien kolmen käsitteen alle: [1](https://melinda.kansalliskirjasto.fi/byid/017469869), [2](https://melinda.kansalliskirjasto.fi/byid/001411769), [3](https://melinda.kansalliskirjasto.fi/byid/014229341)

**Comment by mirmaid** [comment]
Muistan joskus pohtineeni (samalla kun otettiin kvanttikenttäteoria), pitäisikö kvanttiteorian olla monikossa, tarkoittaen kvanttifysiikan alan teorioita yleensä.

GND:ssä tilanne on sama kuin meillä - kaikki kolme ovat sanastossa.

Quantentheorie: Bevorzugt verwendet für die alte Quantentheorie vor Heisenberg und für eher philosophische, weltanschauliche oder populärwissenschaftliche Schriften.

Quantenphysik: Benutzt als übergeordneter Begriff zu Quantenmechanik, Quantenfeldtheorie, Quantenchromodynamik usw. 

Quantenmechanik: Durch Quantisierung der klass. Mechanik entstandene nichtrelativistische Quantentheorie

**Comment by mirmaid** [comment]
Yksi varovainen muutos voisi olla kvanttiteorian muuttaminen monikkoon ja ohjaustermi kvanttiteoria (kvanttimekaniikka) KÄ kvanttimekaniikka (ja ehkä pitäisi myös lisätä kvanttiteoria (kvanttikenttäteoria) KÄ kvanttikenttäteoria). 

Toki varmaan mahdollista myös yhdistää kvanttiteoria ja kvanttimekaniikka, jolloin jättäisin kvanttiteoria (kvanttimekaniikka) KÄ kvanttimekaniikka, ja varhaisempi historia olisi sitten kuvattavissa kvanttifysiikka-kattotermillä (sikäli kuin on tarpeen erottaa, ettei kyse ole kvanttimekaniikasta).

**Comment by YSO-kokous** [comment]
**Päätös**

Yhdistetään _kvanttiteoria_ ja _kvanttimekaniikka_. _Kvanttimekaniikka_ päätermiksi. _Kvanttifysiikka_ jää ennalleen.

**Comment by mariaforsen** [comment]
Sv. kvantmekanik HT kvantteori, kvantummekanik, kvantumteori
NE
https://svenska.se/tre/?sok=kvantmekanik&pz=1
https://termipankki.fi/tepa/fi/haku/kvantmekanik
https://sv.wikipedia.org/wiki/Kvantmekanik
https://www.rikstermbanken.se/search?q=kvantmekanik&s=termer
jfr https://id.kb.se/find?q=kvantmekanik
