### ISSUE TITLE
suhteellisuusteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10008]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[suhteellisuusteoria](http://www.yso.fi/onto/yso/p9145)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Suhteellisuusteoria fysiikan alakäsitteeksi. Library of Congress subject headings on väärä, pitäisi olla vain Relativity, ei General Relativity.

**Perustelut ehdotukselle**

Suhteellisuusteoria on fysiikan osa-alue. 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ehdotettu muutos ei ole YSOn hierarkiaperiaatteen mukainan (suhteellisuusteoria ei ole tietynlainen fysiikka). LCSH-linkitys korjattu.
