### ISSUE TITLE
säätsunamit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10001]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

säätsunamit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

meteotsunamit

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.ilmatieteenlaitos.fi/saatsunamit

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/315759

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [säätsunamit](http://finto.fi/yse/fi/page/Y510001)

**Comment by ilona-x** [comment]
jos tämä otetaan, pitäisikö tehdä jotain tsunameille, joka on nyt ohjaustermi hyökyaalloille? http://www.yso.fi/onto/yso/p1176

Kielitoimiston sanakirja:

**hyökyaalto**
hyökyvä aalto, hyöky.
Myrsky nosti mahtavan hyökyaallon.

**tsunami**
maanjäristyksen tms. aiheuttama, merenpohjan voimakkaasta liikkeestä johtuva sarjallinen hyökyaalto. 

https://fi.wikipedia.org/wiki/Hy%C3%B6kyaalto
https://fi.wikipedia.org/wiki/Tsunami

**Comment by mariaforsen** [comment]
Sv. sjösprång HT meteorologiska tsunamier, meteotsunamier

**Comment by YSO-kokous** [comment]
### Päätös
otetaan sanastoon  
säätsunamit 
tsunamit 
Selvitetään hyökyaallot ja tsunamit -käsitteiden suhdetta. Onko kuvailussa muita hyökyaaltoja kuin tsunamit.
