### ISSUE TITLE
terveyden lukutaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1000]
#### Ehdotettu termi suomeksi

terveyden lukutaito
#### Ehdotetut ohjaustermit

terveydenlukutaito, terveyslukutaito
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)
#### Lähde

Lähde: Kunnon kirja
#### Käsitteen määritelmä

Terveyden lukutaidolla tarkoitetaan kuluttajien kykyä valita sellaisia hyvinvointiteollisuuden tuotteita, jotka ovat heille hyödyllisiä ja joista ei koidu haitallisia sivuvaikutuksia (Ritva S. lähetti tällaisen määritelmän)

**Luontipäivämäärä:** 23.10.2003

**Muokkauspäivämäärä:** 15.4.2004, 15.4.2004, 15.4.2004, 10.6.2004, 23.10.2003, 16.12.2008, 18.10.2012, 18.10.2012, 18.10.2012, 18.10.2012

**Voyager-id:** 127776

**Termiehdotus Fintossa:** [terveyden lukutaito](http://finto.fi/yse/fi/page/Y327776)

**Comment by mariaforsen** [comment]
Hyväksytty jo ohjaustermiksi.
