### ISSUE TITLE
banjolele [SEKO]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10003]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

banjolele [SEKO]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

banjo ukulele

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

 [ukulele](http://www.yso.fi/onto/yso/p37988)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 banjouke [ENG, FIN], banjoukulele, banjo uke [ENG], banjolele [ENG], banjulele [ENG], ukulele banjo [ENG]

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCMPT](http://id.loc.gov/authorities/performanceMediums/mp2013015054), [Wikidata](https://www.wikidata.org/wiki/Q1889346)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/017425179 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [banjolele [SEKO]](http://finto.fi/yse/fi/page/Y510003)

**Comment by jtuohini** [comment]
LT:ksi myös [**banjo**](http://urn.fi/urn:nbn:fi:au:seko:00096).

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
