### ISSUE TITLE
lämpöoppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10004]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lämpöoppi](http://www.yso.fi/onto/yso/p5008)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Termodynamiikka ja lämpöoppi ovat synonyymeja. Thermology on virheellinen käännös, molemmat termit kääntyvät englanniksi nimellä thermodynamics. Myös ruotsin värmelära ja termodynamik vastaavat toisiaan.

**Perustelut ehdotukselle**

Asia lienee selvä esim. googlettamalla "lämpöoppi eli termodynamiikka" tai kysymällä asiantuntijalta. Varoituksena sanon että vastaava virhe näyttää levinneen laajalle, esim. Kielitoimiston sanakirjassa termodynamiikka esitetään lämpöopin osana eikä synonyyminä. Englanninkielistä sanaa "thermology" ei löydy MOT Oxford dictionary:stä eikä myöskään Merriam-Websteristä.

**Ehdottajan organisaatio**

Jyväskylän yliopisto, fysiikan laitos

**Comment by ristoja** [comment]
Ehdotukset olivat siis: 
- Termodynamiikka Fysiikan alakäsitteeksi.
- Lämpöoppi ohjaamaan termodynamiikkaan. 
- Vastaavat muutokset ruotsiksi.
"Thermology" poistunee järjestelmästä näillä muutoksilla?

**Comment by mariaforsen** [comment]
svenska.se: 
Termodynamik: vetenskapen om sam­bandet mellan värme och andra energi­former
Värmelära: läran om värme­energi

**Comment by mariaforsen** [comment]
https://svenska.se/tre/?sok=termodynamik&pz=1 eli "vetenskapen om sam­bandet mellan värme och andra energi­former"
https://svenska.se/tre/?sok=v%C3%A4rmel%C3%A4ra&pz=1 eli "läran om värmeenergi"
Mutta Nationalencyklopedinissä sama määritelmä molemmilla ja SAOssa on vain termodynamik. Ruotsin kannalta ehdotus on hyvä.

**Comment by mirmaid** [comment]
_Lämpöoppi_ on ollut sanastossa vuodesta 1985 ja _termodynamiikka_ 1996. Kyllä näillä varmasti on yritetty kuvata eri asioita, toisella tieteenalaa ja toisella ilmiötä, jota se tutkii. Mutta jos mitään mielekästä eroa ei pysty ilmaisemaan, niin voidaan omasta puolestani yhdistää.

**Comment by ilona-x** [comment]
DNB:
Sachbegriff 	**Thermodynamik**

Synonyme 	
Wärmelehre
Wärmetheorie
Technische Thermodynamik
Technische Wärmelehre

**Comment by mirmaid** [comment]
Vrt. kuitenkin esim. ehdotus _sähkömagnetismi_ - olisi hyvä, jos tämäntyyppiset voitaisiin käsitellä johdonmukaisesti (eli kun kyseessä on tieteenala ja sen tutkima ilmiö).

**Comment by mirmaid** [comment]
Melindassa 
lämpöoppi 570
termodynamiikka 927
molemmat 191

**Comment by mirmaid** [comment]
Lämpöopin ohjausterminä on termofysiikka, tällainen löytyy: https://en.wikipedia.org/wiki/Thermal_physics, ei ruotsiksi tai suomeksi, mutta https://da.wikipedia.org/wiki/Termisk_fysik

**Comment by YSO-kokous** [comment]
**Päätös**

Ei yhdistetä, mutta tarkistetaan kielivastineet. Englannin termiksi vaihtoehto esim. _thermal physics_.
