### ISSUE TITLE
sähkömagnetismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10006]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähkömagnetismi](http://www.yso.fi/onto/yso/p9447)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan sähkömagneettisten käsitteiden perusteellista mylläystä. Sähkömagnetismi olisi fysiikan alakäsite, ja sähköoppi ohjaisi siihen. Sähkömagnetismin englanninkielinen vastine on electromagnetism. Sähkömagnetismin alakäsitteitä olisivat sähködynamiikka ja sähköstatiikka. Sähkömagnetismin assosiatiivinen käsite olisi luonnollisesti sähkömagneettiset ilmiöt, jonka alakäsitteitä ovat sähkö, magnetismi, ja sähköstaattinen induktio. Sähkömagnetismin yläkäsitteeksi voisi lisätä myös perusvuorovaikutukset, jos systeemi siihen taipuu.

**Perustelut ehdotukselle**

Huomautuksena sanottakoon että sähkömagnetismilla on kaksi merkitystä: 1. sähköiset ja magneettiset ilmiöt yhdistävä fysiikan ala, 2. sähkövirran aikaansaama magnetismi. Ehdotuksessani käytettäisiin sähkömagnetismin ensimmäistä merkitystä. Toisen merkityksen kattaa käsite sähkömagneetti.

**Ehdottajan organisaatio**

**Comment by ristoja** [comment]
Sähkömagnetismia tässä tarkoitetussa merkityksessä käytetään esimerkiksi [lukion opetussuunnitelmassa](https://eperusteet.opintopolku.fi/beta/#/fi/lukiokoulutus/6828810/oppiaine/6832792/moduuli/6833234)
Tuo toinen merkitys on käsittääkseni harvinaisempi, koska sähkön tuottamaan magnetismiin on luontevampaa viitata termillä "sähkömagneetti".

**Comment by ristoja** [comment]
Pikaisen silmäyksen perusteella valtaosa Melindasta hakusanalla "sähkömagnetismi" löytyvästä aineistosta käsittelee sähkömagnetismia nimenomaan fysiikan alana sekä sähkön ja magnetismin yläkäsitteenä.

**Comment by ristoja** [comment]
Sähkömagnetismin valitseminen käytettäväksi käsitteeksi vanhakantaisemman sähköopin sijasta helpottaisi kääntämistä ruotsiin ja englantiin. Nyt YSO:ssa oleva käännöstä _elektricitetslära_ ei löydy Svevnsk ordbokista, mutta _elektromagnetism_ löytyy tarkoitetussa merkityksessä: https://svenska.se/so/?sok=elektromagnetism

Vastaavasti englannin käsite _theory of electricity_ on jouduttu tässä rakentamalla rakentamaan, mutta sähkömagnetismi kääntyisi suoraan: _electromagnetism_ (https://www.merriam-webster.com/dictionary/electromagnetism)

**Comment by mariaforsen** [comment]
Elektricitetslära löytyy esim. SAOLista, https://svenska.se/tre/?sok=elektricitetsl%C3%A4ra&pz=1 On siis aivan ok. Ja synonymi ellära löytyy myös esim. Nationalencyklopedinistä. 

Sen lisäksi myös SAOssa on molemmat termit:  
https://id.kb.se/find?q=ell%C3%A4ra
https://id.kb.se/find?q=elektromagnetism

**Comment by ristoja** [comment]
Mahdollisesti hyödyllinen esimerkki siitä miten käsitettä käytetään nykyisen YSO-luokituksen vastaisesti: https://melinda.kansalliskirjasto.fi/byid/017465330
Tässä sähkömagnetismi rinnastetaan mekaniikkaan, akustiikkaan, optiikkaan ja termodynamiikkaan, eli se ymmärretään fysiikan alana, ei magnetismin lajina.

**Comment by ilona-x** [comment]
Saksan kansalliskirjastossa molemmat termit:

Elektrizitätslehre https://d-nb.info/gnd/4113415-1
Elektromagnetismus  https://d-nb.info/gnd/4014306-5

**Comment by mirmaid** [comment]
^^ Mainitussa esimerkkiteoksessa on ylipäätään ehkä vähän niukasti asiasanoja - voisin kuvitella, että sekä sähköoppi, että sähkömagnetismi olisivat ok, samoin moni muu nyt puuttuva tarkempi termi. 

Luokitusjärjestelmässä, kuten YKL, sähköoppi ja sähkömagnetismi olisivat päällekkäisiä - ja ne on näin käsiteltykin: http://urn.fi/URN:NBN:fi:au:ykl:53.7. 

YSOssa sähkömagnetismin toisena yläkäsitteenä voisi hyvin olla perusvuorovaikutukset. YSOn hierarkiassa sähkömagnetismi on fysikaalinen ilmiö (samoin perusvuorovaikutukset), sähköoppi puolestaan tieteenala.

**Comment by mirmaid** [comment]
Ehdotan, että näitä ei yhdistetä, mutta voidaan tarkentaa hierarkiaa/suhteita.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei yhdistetä. Tarkistetaan suhteet.
