### ISSUE TITLE
kvanttilaskenta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10012]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kvanttilaskenta](http://www.yso.fi/onto/yso/p39209)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kvanttimekaniikka toiseksi yläkäsitteeksi

**Perustelut ehdotukselle**

Kvanttilaskenta on kvanttimekaniikan sovellusalue

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ehdotettu muutos ei ole YSOn hierarkiaperiaatteen mukainan (kvanttilaskenta ei ole tietynlainen kvanttimekaniikka). Lisättiin näille RT-suhde.
