### ISSUE TITLE
Heikko vuorovaikutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10014]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Heikko vuorovaikutus

**Ehdotettu termi ruotsiksi**

svag växelverkan

**Ehdotettu termi englanniksi**

weak interaction

**Tarkoitusta täsmentävä selite**

Luonnon perusvuorovaikutus

**Perustelut ehdotukselle**

Neljä perusvuorovaikutusta ovat gravitaatio, sähkömagnetismi, sekä heikko ja vahva vuorovaikutus.

**Ehdotettu yläkäsite YSOssa (LT)**

 [perusvuorovaikutukset](http://www.yso.fi/onto/yso/p29742)

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565)

**Vaihtoehtoiset termit**

 heikko voima, heikko ydinvoima

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Heikko_vuorovaikutus)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/F/KJICSBUM3FQAUY2B8AVNS81Q5N9U8ADG2T8UAMQ8V2IJ2NQMNG-01593?func=full-set-set&set_number=000090&set_entry=000032&format=999

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Heikko vuorovaikutus](http://finto.fi/yse/fi/page/Y510014)

**Comment by ilona-x** [comment]
LCSH: **Weak interactions (Nuclear physics)** http://id.loc.gov/authorities/subjects/sh85145822

**Comment by mariaforsen** [comment]
SAO https://id.kb.se/find?q=Weak%20interactions%20%28Nuclear%20physics%29
