### ISSUE TITLE
hienomekaniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10010]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hienomekaniikka](http://www.yso.fi/onto/yso/p17208)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mekaniikan poisto yläkäsitteistä

**Perustelut ehdotukselle**

Hienomekaniikan yläkäsite ei ole mekaniikka (fysiikan ala/teoria), vaan konetekniikka, sähkötekniikka tai joku muu tekniikan ala.

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/10195

**Comment by mirmaid** [comment]
YK teknologia
