### ISSUE TITLE
CPAP-hoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10016]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

CPAP-hoito

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 ylipainehoito

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/150318

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [CPAP-hoito](http://finto.fi/yse/fi/page/Y510016)

**Comment by mirmaid** [comment]
Myös https://www.utupub.fi/handle/10024/150637

**Comment by ilona-x** [comment]
FinMeSH:
**CPAP** http://www.yso.fi/onto/mesh/D045422
Ohjaustermit
    C-PAP
    CPAP-hengitys
    CPAP-hoito
    jatkuva ylipainehengitys
    positiivinen painehengitys

**Comment by mirmaid** [comment]
Melindassa CPAP, CPAP-hoito, CPAP-laite, ylipainehoito. Kaikkia käytetty 8-17 kertaa.

**Comment by mariaforsen** [comment]
Sv. CPAP-behandling HT övertrycksbehandling, kontinuerligt positivt luftvägstryck /https://finto.fi/mesh/fi/page/D045422?clang=sv
https://www.kaypahoito.fi/sv/imk01107

**Comment by LeKorsu** [comment]
Kannatan ehdottomasti että otetaan ysoon, mutta CPAP (Finmesh) vai CPAP-hoito, ei selvää kantaa. Tyydyn siihen mitä päätätte.
Assosiaatiokäsitteeksi uniapnea-oireyhtymä

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termeissä

https://www.terveysportti.fi/apps/sanakirjat/0/cpap

CPAP näyttää olevan suomennettu **jatkuva positiivinen hengitystiepaine**. Kaipaisin jotain sellaista termiä, mistä ilmenee, että kyseessä on hoito(menetelmä).
