### ISSUE TITLE
tiedontuotanto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1001]
#### Ehdotettu termi suomeksi

tiedontuotanto
#### Ehdotetut ohjaustermit

tiedon tuotanto, tietotuotanto
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[56 Tiede. Tutkimus](http://www.yso.fi/onto/ysa/ryhma_56)
#### Lähde

Lähde: Tiedon tuotannon käytännöt ja ympäristöpoliittinen toimijuus

**Luontipäivämäärä:** 23.10.2003

**Muokkauspäivämäärä:** 12.6.2006, 12.6.2006, 12.6.2006, 27.9.2005, 8.6.2006, 26.5.2004, 23.10.2003, 16.12.2008, 15.6.2009, 04.07.2012

**Voyager-id:** 127777

**Termiehdotus Fintossa:** [tiedontuotanto](http://finto.fi/yse/fi/page/Y327777)

**Comment by henriyli** [comment]
YSAan 24.5.2016: http://www.yso.fi/onto/ysa/Y208801
