### ISSUE TITLE
esidiabetes

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10019]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

esidiabetes

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/150801

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [esidiabetes](http://finto.fi/yse/fi/page/Y510019)

**Comment by ilona-x** [comment]
Verensokeri koholla (esidiabetes) https://www.terveyskirjasto.fi/dlk01134

FinMeSHissä ei ole esidiabetesta
ja kohonnut verensokeri ohjaa käyttämään **hyperglykemia** http://www.yso.fi/onto/mesh/D006943
Ja hyperglykemia on myös YSOssa http://www.yso.fi/onto/yso/p21830

esidiabetes ei Melindassa

**Comment by mirmaid** [comment]
Tämän väitöstiedotteen perusteella esidiabetes ei olisi vain kohonnut verensokeri: https://www.utu.fi/fi/ajankohtaista/vaitos/perintotekijat-vaikuttavat-suomalaislasten-kohonneeseen-diabetesriskiin. Mutta voi jäädä seurattaviin.

**Comment by mariaforsen** [comment]
Sv. prediabetes HT fördiabetes
https://www.terveyskyla.fi/diabetestalo/sv/information/konstaterande-av-diabetes/normalt-blodsocker-f%C3%B6rdiabetes-och-diabetes

**Comment by FinMeSHienPaimentaja** [comment]
MeSHinä on Prediabetic State

https://meshb.nlm.nih.gov/record/ui?ui=D011236

FinMeSHeinä on vaikka mitä ml. prediabetes ja prediabeettinen tila, ei kuitenkaan toistaiseksi ole mielestäni selkeää   esidiabetes. Ensisijaisena FinMeSHinä on nyt latentti diabetes, täytyy miettiä päivittämistä...

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään esidiabetes
ohjaustermejä voidaan MeSHissä.
