### ISSUE TITLE
ajoavustinjärjestelmät (tms.)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10025]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ajoavustinjärjestelmät (tms.)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/130293

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ajoavustinjärjestelmät (tms.)](http://finto.fi/yse/fi/page/Y510025)

**Comment by ilona-x** [comment]
LCSH: Driver assistance systems http://id.loc.gov/authorities/subjects/sh2002000554

**Comment by mariaforsen** [comment]
Sv. förarassistanssystem HT förarstödsystem
http://www.tsk.fi/tsk/fi/hakemistot-267.html?page=get_id&id=ID5&vocabulary_code=TSKTT
https://termipankki.fi/tepa/fi/haku/ajoavustinj%C3%A4rjestelm%C3%A4
