### ISSUE TITLE
koe-eläinmallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10020]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koe-eläinmallit](http://www.yso.fi/onto/yso/p28104)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT eläinmallit

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
aiempi ehdotus samasta: https://github.com/Finto-ehdotus/YSE/issues/9843
