### ISSUE TITLE
hoitoetiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10023]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hoitoetiikka](http://www.yso.fi/onto/yso/p24237)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT hoitotyön etiikka (?)

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. HT vårdarbetets etik, omvårdnadsetik

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään ehdotuksen mukaan
