### ISSUE TITLE
sukukirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10029]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukukirjat](http://www.yso.fi/onto/yso/p27349)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: sukuselvitykset

**Perustelut ehdotukselle**

käytetään myös

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**sukuselvitys** https://www.kielitoimistonsanakirja.fi/#/sukuselvitys?searchMode=all
väestöluettelon perusteella laadittu selvitys jkn sukulaisuussuhteista.
 -- Sukuselvitys perukirjaa varten.

--

https://www.suomi.fi/palvelut/sukuselvitys-digi-ja-vaestotietovirasto/5a0914b8-fd0e-425e-8521-a210303ee35b

https://evl.fi/tietoa-kirkosta/kirkko-ja-yhteiskunta/sukuselvitys

**Comment by mariaforsen** [comment]
Ruotsiksi ohjausterminä on "släktutredningar (släktböcker)"

**Comment by fantsby-m** [comment]
Esim. perunkirjoitusta varten tarvittava sukuselvitys ei ole sukukirja (ks. esim. https://dvv.fi/sukuselvitys). 
Jos uusi ohjaustermi otettaisiin pitäisi suomeksikin olla ainakin tarkenne, esim _sukuselvitykset (sukukirjat)_.

**Comment by YSO-kokous** [comment]
### Päätös
ei oteta ohjaustermiksi
