### ISSUE TITLE
sotilashenkilöstö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10026]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sotilashenkilöstö](http://www.yso.fi/onto/yso/p788)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: puolustushenkilöstö

**Perustelut ehdotukselle**

synonymi

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Ei juurikaan löydy asiallisia lähteitä joissa tuota olisi käytetty.

**Comment by ilona-x** [comment]
FinMeSHissä voisi olla parempia ehdokkaita ohjaustermeiksi.
 
sotilashenkilökunta http://www.yso.fi/onto/mesh/D008889
KT    armeijan henkilöstö
KT    puolustusvoimien henkilöstö
KT    sotilashenkilöstö

Tosiaan puolustushenkilöstö näyttää olevan todella vähän käytetty. Liekö suora käännös ruotsinkielestä försvarspersonal -termistä, jolle sanakirja antaa käännökseksi sotilashenkilöstö.

**Comment by YSO-kokous** [comment]
### Päätös
ei hyväksytä ehdotettua termiä, mutta lisätään Ilonan ehdotuksesta MeSH termit
sotilashenkilöstö KT sotilashenkilökunta, armeijan henkilöstö, puolustusvoimien henkilöstö
