### ISSUE TITLE
informaatiotulva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10024]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

informaatiotulva

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

information overload

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

On niin peruskäsite, että täytyyhän tälle olla jokin ilmaus YSO:ssa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 informaatioähky

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [informaatio](http://www.yso.fi/onto/yso/p14428)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Johann Hari: Stolen focus : why you can't pay attention.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [informaatiotulva](http://finto.fi/yse/fi/page/Y510024)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Informaatio%C3%A4hky

Melinda:
informaatioähky x 3
informaatiotulva x 4
tietotulva x 4

**Comment by mariaforsen** [comment]
Sv. informationsöverflöd HT information overload, informationsöverbelastning
https://it-ord.idg.se/ord/informationsoverbelastning/

**Comment by YSO-kokous** [comment]
### Päätös
informaatiotulva OT tietotulva

**Comment by mariaforsen** [comment]
Varmaan suomeksi myös OT informaatioähky?
