### ISSUE TITLE
siirtohinnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10021]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[siirtohinnat](http://www.yso.fi/onto/yso/p9691)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan

**Perustelut ehdotukselle**

Epäselvää mihin viittaa. Termi on ruotsiksi ollut internpriser, eli aivan eri asia kuin esim. sähkön siirtohinta, mistä se on nyt myös käytetty Melindassa. Samoin eng. on ollut transfer prices, mutta jos sähkön siirtohinnasta yms. niin transmission prices, ainakin tämän mukaan: https://termipankki.fi/tepa/fi/haku/siirtohinta

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Sanastossa tosin on jo myös siirtohinnoittelu, joten olisiko mahdollista rajata tämä sähköön yms. ja muuttaa muunkieliset vastineet sen mukaisiksi? 
https://en.wikipedia.org/wiki/Transfer_pricing
https://fi.wikipedia.org/wiki/Siirtohinnoittelu

**Comment by mirmaid** [comment]
_Siirtohinnat_ (1997) ja _siirtohinnoittelu_ (2008) vaikuttavat kyllä päällekkäisiltä, tuo sähkön siirtohinta -merkitys on tullut mukaan vasta myöhemmin.

**Comment by mirmaid** [comment]
_Sähkönsiirto & hinnat_ myös käytetty.

**Comment by ilona-x** [comment]
> _Siirtohinnat_ (1997) ja _siirtohinnoittelu_ (2008) vaikuttavat kyllä päällekkäisiltä, tuo sähkön siirtohinta -merkitys on tullut mukaan vasta myöhemmin.

**siirtohinnoittelu**-termiä käytetään ainakin yritysverotuksen yhteydessä:
https://fi.wikipedia.org/wiki/Siirtohinnoittelu
https://termipankki.fi/tepa/fi/haku/siirtohinnoittelu

**Comment by ilona-x** [comment]
[siirtohinnat](http://www.yso.fi/onto/yso/p9691) 
[siirtohinnoittelu](http://www.yso.fi/onto/yso/p23477) 
Nämä molemmat YSO-termit on näköjään linkattu LCSH-termiin
**Transfer pricing** http://id.loc.gov/authorities/subjects/sh85136909
Variants
    Cost transfer pricing
    Intercompany pricing
    Interdivisional transfer pricing
    Internal transfer pricing

Eli varmaan yksi termi riittäisi tälle liiketalous/yritysverotus -merkitykselle ja tämän lisäksi tarvittaisiin erikseen sähkön siirtohinnat / sähkön siirtohinnoittelu.

**Comment by mirmaid** [comment]
^ Ellei sitten riitä vaan _sähkönsiirto & hinnat/hinnoittelu_ -yhdistelmä. Tosin kun myös _siirtohinnoittelussa_ on se riski, että käytetään sähköön liittyen, helpottaisi ehkä oikeaa käyttöä jos se olisi omana käsitteenään. En ainakaan keksi poissulkevaa tarkennetta.

**Comment by mariaforsen** [comment]
Voisiko olla:
-siirtohinnoittelu (yhtiöiden välinen?) = internprissättning
https://www.vero.fi/yritykset-ja-yhteisot/yritystoiminta/siirtohinnoittelu/ "Siirtohinnoittelulla tarkoitetaan samaan konserniin kuuluvien yhtiöiden välisten liiketoimien (etuyhteysliiketoimien) hinnoittelua"
https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/79688/J1714_Team%20Finland%20Siirtohinnoitteluopas_net.pdf
-siirtohinnat (sähkönsiirto) / sähkön siirtohinnat = elöverföringspriser

**Comment by ilona-x** [comment]
Alan kallistua sille kannalle, että pitäisi keksiä tarkenne tuohon konserniyhtiöiden väliseen siirtohinnoitteluun, siirtohinnoittelu (konserniyhtiöt?) Ja sähköön liittyvät voisi kuvailla Mirjan ehdotuksen mukaisesti yhdistelmällä sähkönsiirto + hinnat/hinnoittelu, kun ei varmaan kuitenkaan haluta muita eri asioiden hintoja YSOon. Esimerkiksi eihän nyt ole erikseen sähköenergian hinnoille omaa termiä. 🤔 

Tätä tutkiessa huomasin, että YSOsta löytyy termi [sähkötariffit ](http://www.yso.fi/onto/yso/p14947), mitä näyttäisi olevan käytetty sähkönhintoja käsittelevissä aineistoissa. Voisiko sähkötariffeille (otettu sanastoon v. 1985) lisätä ohjaustermejä, kun tuo tariffit kuulostaa ainakin omaan korvaan vähän vieraalta?

Kielitoimiton sanakirja:
sähkötariffi
sähköenergian myynnissä noudatettava tariffi. 
https://www.kielitoimistonsanakirja.fi/#/s%C3%A4hk%C3%B6tariffi?searchMode=all

"Sähkötariffit eli sähköyhtiön perimät sähkötuotteen hinnat vaihtelevat toimittajittain. "
https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Electricity_price_statistics/fi&oldid=365840

Tässä vielä vähän vanhempi esimerkkitietue Melindasta:
Jakeluverkon siirtotariffien rakenteet https://melinda.kansalliskirjasto.fi/byid/000343961

**Comment by mirmaid** [comment]
^ Voisiko siis olla ihan sähkön hinnat, sähkön siirtohinnat KÄ sähkötariffit? 

Ja siirtohinnoittelu (konserniyhtiöt)?

**Comment by mariaforsen** [comment]
Itse sähkön hinta on kuitenkin aika eri asia kuin sähkön siirron hinta, hinnoittelu eri ja eri laskut ja laskuttaja, paitsi jos asuu sellaisella alueella missä siirtäjä ja tuottaja on sama - ja asiakas on valinnut sama yhtiö molempiin.

**Comment by mirmaid** [comment]
^ Käsitin tuolta linkin takaa, että molemmista kuitenkin käytettäisiin tuota _sähkötariffit_, joka jo on sanastossa. 

Korjaus, olikin täältä: https://www.kilpailuttaja.fi/palvelut/tuki_ja_ohjeet/Sahkon_hinta_ja_kilpailuttaminen_kilpailuttajafi_palvelussa/sahkotuotteet_eli_tariffit/

**Comment by LeKorsu** [comment]
Mirjan linkistä kopsattua: "Sekä sähköenergian että siirtopalvelun hinnat eli tariffit muodostuvat tavallisesti kahdesta osatekijästä:..."
Tämä siis puoltaisi tuota Mirjan ehdotusta, että molemmista voisi käyttää tuota sähkötariffeja. Toisaalta olen tietävinäni, että uutisartikkelien asiasanoituksessa kaivataan asiasanaa, joka on mahdollisimman lähellä uutiskieltä, eli sähkön siirtohinnat omana olisi varmaan mieluisampi siellä. 

Mutta koska tämä ratkaisu voi taas avata Pandoran lippaan muiden erityisten hintojen lisäämisehdotuksille, peukkua kuitenkin sähkötariffeille. Myös tuo siirtohinnoittelu (konserniyhtiöt) ok minulle.

**Comment by mariaforsen** [comment]
Ok, eli siirtohinnat (sähkö) KÄYTÄ sähkötariffit? Silloin ei tosin ole mahdollista hakea erikseen tietoa nimenomaan sähkön siirtohinnoista.

**Comment by mirmaid** [comment]
^ Paitsi yhdistämällä sähkönsiirto + sähkötariffit/hinnat.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään sulkutarkenne _siirtohinnat (konserniyhtiöt)_, _siirtohinnat (sähkö)_ ohjaustermiksi käsitteelle _sähkötariffit_.
