### ISSUE TITLE
teleoperaattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10048]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[teleoperaattorit](http://www.yso.fi/onto/yso/p11827)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi ohjaustermi: matkapuhelinoperaattorit

**Perustelut ehdotukselle**

synonymi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. jo HT mobiloperatörer, lisätään myös mobiltelefonoperatörer
