### ISSUE TITLE
raviratsastus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10059]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

raviratsastus

**Ehdotettu termi ruotsiksi**

monté

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Monté eli raviratsastus on ravikilpailumuoto, jossa ohjastaja istuu kärryjen sijaan satulassa hevosen selässä.

**Perustelut ehdotukselle**

Käsitteet ratsastus ja raviurheilu eivät riitä kuvailemaan Ravataan - yhdessä -teosta, koska kyseessä on juuri noiden kahden lajin "sekoitus", joten käsite raviratsastus tai monté tarvittaisiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [hevosurheilu](http://www.yso.fi/onto/yso/p6963)

**Ehdotetut temaattiset ryhmät**

 [97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)

**Vaihtoehtoiset termit**

 monté

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ratsastus](http://www.yso.fi/onto/yso/p1653), [raviurheilu](http://www.yso.fi/onto/yso/p503)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ravataan - yhdessä / Paula Keränen. 
https://www.monteteam.fi/monteakatemia/

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [raviratsastus](http://finto.fi/yse/fi/page/Y510059)

**Comment by mirmaid** [comment]
https://www.hippos.fi/raviurheilu/raviurheilu-lajina/monte/
https://www.ratsastus.fi/lajit/muut-lajit/monte/
https://fi.wikipedia.org/wiki/Mont%C3%A9

**Comment by mariaforsen** [comment]
Sv. monté HT travridning 
https://svenska.se/tre/?sok=monte&pz=1
https://svenska.se/so/?id=186301&ref=lnr923154 
https://sv.wikipedia.org/wiki/Mont%C3%A9

**Comment by mirmaid** [comment]
Itselleni tutumpi muoto on _monté_ ja se taitaa olla myös enemmän käytössä, mutta _raviratsastus_ toki terminä selkeämpi.
