### ISSUE TITLE
Helsingin vanha kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10058]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Helsingin vanha kirkko](http://www.yso.fi/onto/yso/p37915)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Nimi tulisi olla muotoa: Helsingin Vanhakirkko

**Perustelut ehdotukselle**

Nimi perustuu kirkon ominaisuuteen
Osa kirkon nimistä perustuu johonkin kirkon ominaisuuteen. Kun kyseessä ei ole tilapäinen luonnehdinta vaan yksilöivä erisnimi, nimenosat kirjoitetaan yhteen:

Vanhakirkko ~ Helsingin Vanhakirkko

Kun ilmaukseen sisältyy kohdetta kuvaava ominaisuudennimitys (kuten vanha, uusi), joka ei ole ilmauksen jälkiosan tilapäinen luonnehdinta vaan kiinteä osa yksilöivää erisnimeä, nimenosat kirjoitetaan yhteen. Tällainen kiteytynyt nimi on esimerkiksi Vanhakirkko (yhteen kirjoitetaan myös mm. Ristinkirkko ja Sovituksenkirkko). Nimen alussa oleva adjektiivi vanha taipuu, kun nimeä taivutetaan, esim. Vanhankirkon, Vanhassakirkossa ja Vanhaakirkkoa.

Tiettyä kirkkoa voidaan luonnehtia vanhaksi myös erotukseksi uudemmasta kirkosta ilman, että sana vanha tai uusi kuuluisi pysyvästi kirkon nimeen, esim. Espoon vanha kirkko eli Espoon tuomiokirkko. Jos kirkon nimi sen sijaan on vakiintunut muotoon Vanhakirkko tai Uusikirkko, nimi säilyy samassa muodossa myös paikannimimääritteen jäljessä (X:n Vanhakirkko, X:n Uusikirkko).

Pääkaupungin Vanhakirkko sijaitsee Vanhassa kirkkopuistossa, jota kutsutaan epävirallisesti myös Ruttopuistoksi, koska alueelle haudattiin paljon ruttoepidemian uhreja vuonna 1710. Puiston virallinen nimi Vanha kirkkopuisto (ruotsiksi Gamla kyrkoparken) on vuodelta 1956. Se kirjoitetaan kaavanimien oikeinkirjoitusohjeiden mukaan sanaliitoksi, sillä perusosa kirkkopuisto on yhdyssana, vrt. Käpylän urheilupuisto ja Toukolan rantapuisto.

**Ehdottajan organisaatio**

Kotus

**Comment by mirmaid** [comment]
Kirjoitusasu vaihtelee eri lähteissä ja esim. Helsingin seurakuntien sivustolla on samalla sivullakin käytetty sekä yhteen- että erikseen kirjoitettuja muotoja: https://www.helsinginseurakunnat.fi/vanhakirkko.html.stx

https://www.myhelsinki.fi/fi/n%C3%A4e-ja-koe/n%C3%A4ht%C3%A4vyydet/vanhakirkko
https://fi.wikipedia.org/wiki/Vanha_kirkko_(Helsinki)
https://fi-fi.facebook.com/vanhakirkko/
https://www.stadissa.fi/paikat/178/vanha-kirkko

Erikseen kirjoitettu muoto on luultavasti valittu Helsingin seurakuntien sivulla eniten käytetyn perusteella (yleensä on valittu kirkoille seurakunnan käyttämä nimimuoto), myös muualla erikseen kirjoitettu muoto on yleisempi. Voidaan toki silti vaihtaa.

**Comment by YSO-kokous** [comment]
### Päätös
Tehdään KOTUS ohjeen mukaan: pääterm Helsingin Vanhakirkko OT Helsingin vanha kirkko
