### ISSUE TITLE
Koukkusaari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10087]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Koukkusaari](http://www.yso.fi/onto/yso/p144444)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Monessa paikassa Suomessa.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
_Saariston savuja_: Koukkusaaret: http://paikkatiedot.fi/so/1000772/10878141 ja http://paikkatiedot.fi/so/1000772/10877923 sekä http://paikkatiedot.fi/so/1000772/10877918. 

_Hanko toisessa maailmansodassa_: http://paikkatiedot.fi/so/1000772/10312614 (osa saaresta nimeltään Lilla Krokön).

**Comment by mirmaid** [comment]
Auktorisoidaan erikseen.
