### ISSUE TITLE
ADD

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10089]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hermoston taudit](http://www.yso.fi/onto/yso/p295)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisäys rinnakkaistermiksi: ADD.

**Perustelut ehdotukselle**

On täsmätermi. "ADD (Attention Deficit Disorder) pitkälti kuin ADHD mutta ilman ylivilkkautta. Ongelmia keskittymisen ja tarkkaavuuden säätelyssä: toiminnanohjauksessa, tekemisen aloittamisessa tai loppuun saattamisessa. Oireet voivat vaihdella ikääntyessä: usein ylivilkkaus vähenee ja muuttuu sisäiseksi levottomuudeksi." (https://www.google.com/search?q=add+oireet+aikuisella&oq=add+oire&aqs=chrome.1.0i433i512j0i512j69i57j0i512l7.8269j0j7&sourceid=chrome&ie=UTF-8)  Teos: 978-91-7775-191-5 

**Ehdottajan organisaatio**

Kirjastopalvelu/ OH

**Comment by mirmaid** [comment]
Eli tämä on oikeastaan uusi termiehdotus lisättäväksi sanastoon: ADD. Yllättäen tätä ei ole MeSHissä eikä TEROssa edes ohjausterminä.

https://www.terveyskirjasto.fi/ltt03858

**Comment by ilona-x** [comment]
Riittäisikö, jos lisätään ADD KÄYTÄ ADHD. kun nyt on jo tarkkaavuushäiriö KÄYTÄ ADHD?

LCSH:
**Attention-deficit hyperactivity disorder** http://id.loc.gov/authorities/subjects/sh85063661
Variants
    ADD (Child behavior disorder)
    ADHD (Child behavior disorder)
    Attention deficit disorder with hyperactivity
    Attention deficit disorders
    Hyperactive child syndrome
    Hyperkinesia in children
    Hyperkinetic syndrome

**Comment by mirmaid** [comment]
Veikkaan että ennen pitkää pitää tehdä muutakin, kun nykyään nähdään, että ADD ilman H:ta eli tarkkaavuuden häiriö ilman ylivilkkautta on suunnilleen yhtä yleinen kuin tuo ADHD.

**Comment by mariaforsen** [comment]
Sv. ADD HT uppmärksamhetsstörning
https://www.psykologiguiden.se/psykologilexikon/?Lookup=add
SAOssa on ADD KÄYTÄ ADHD https://id.kb.se/term/sao/Adhd

**Comment by fantsby-m** [comment]
Näiden mukaan ADD on yksi ADHD:n ilmenemismuodoista:
https://www.aivoliitto.fi/verraton/artikkelit/add-ja-adhd/#534e9940
https://adhdtutuksi.fi/add-tarkkaavuushairio-nuorella/

Kannatan myös lisäämistä ohjaustermiksi.

**Comment by mirmaid** [comment]
Kirjoissa tarkkuustaso varmasti riittää, mutta aika paljon artikkeleja on siitä, miten nimenomaan ADD eroaa ADHD:stä, miksi diagnoosin saaminen viivästyy jne. Toki ADD on silloin usein jo nimekkeessä mainittu. Ohjaus on kuitenkin hiukan ongelmallinen, kun ADD tarkoittaa nimenomaan tarkkaavuushäiriötä _ilman_ yliaktiivisuutta.

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään ADD 
lisätään ohjaustermi  tarkkaavuushäiriö
