### ISSUE TITLE
matkaviestinpalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10083]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[matkaviestinpalvelut](http://www.yso.fi/onto/yso/p15079)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT mobiilipalvelut (vai ohjaustermi?)

**Perustelut ehdotukselle**

Ainakin joidenkin lähteiden mukaan sama asia: https://termipankki.fi/tepa/fi/haku/matkaviestinpalvelu

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
_Matkaviestinpalvelut_ otettu v. 2000, _mobiilipalvelut_ 2009. TEPA suosittelee ensin mainittua, mutta mobiilipalvelut on toki paljon käytetympi.

**Comment by ilona-x** [comment]
näillä kahdella taitaa kuitenkin olla merkitysero, kun ovat molemmat Matkaviestinsanastossa/matkaviestinsanaston täydennysosassa. 🤔 

--

fi        matkaviestinpalvelu; matkaviestintäpalvelu; matkapuhelinpalvelu
mieluummin kuin: mobiilipalvelu
sv       mobiltjänst; mobilteletjänst; mobilkommunikationstjänst; mobiltelefontjänst
en      mobile service; mobile communication service; mobile phone service; > cellular service

määritelmä
radioliikenteeseen perustuva tietoliikennepalvelu, jonka avulla matkaviestimet voivat olla yhteydessä toisiinsa ja muihin päätelaitteisiin 

Lähde: Matkaviestinsanasto (TSK 29, 2001)
https://termipankki.fi/tepa/fi/haku/matkaviestinpalvelu

--

fi        mobiilipalvelu
sv       mobiltjänst
en      mobile service

määritelmä
mobiililaitteella käytettäväksi suunniteltu palvelu

huomautus
Mobiilipalveluja ovat esimerkiksi tekstiviestillä tilattavat palvelut, mobiililaitteen kautta internetistä käytettävät palvelut, mobiilisovellukset ja mobiili-VoIP eli mobiililaitteella käytettävät internetpuhelupalvelut. Myös matkaviestinpalvelut sisältyvät mobiilipalveluihin.
Internetistä käytettävissä mobiilipalveluissa verkkosivujen tulisi mukautua mobiililaitteelle sopivaksi.

Lähde: Mobiilisanasto – Matkaviestinsanaston (TSK 29) täydennysosa (TSK 48, 2015)
https://termipankki.fi/tepa/fi/haku/mobiilipalvelu

**Comment by mariaforsen** [comment]
Sv. mobilkommunikationstjänster ja mobiltjänster eli sama asia. Ruotsin kannalta yhdistäminen olisi oikein.

**Comment by fantsby-m** [comment]
Tuo yllä oleva määritelmä termille _matkaviestinpalvelu_ on vuodelta 2001, olisiko vanhentunut?

**Comment by ilona-x** [comment]
En tiedä, miksi itse kuulen noiden välillä jonkinlaisen eron. Ajattelisin, että matkaviestinpalvelut ovat sitä "peruspalvelua", mitä matkapuhelinoperaattorit tarjoavat. Ja mobiilipalveluita eli siis mobiililaitteella käytettävää palvelua voi tarjota mikä tahansa taho esim. pankki. Matkaviestinpalvelut olisi mielestäni telepalveluiden alakäsite. 

--

https://www.stat.fi/meta/kas/televiestintapa.html

--

fi        matkaviestinoperaattori; matkapuhelinoperaattori
mieluummin kuin: mobiilioperaattori
sv       mobiloperatör

määritelmä
**matkaviestinpalveluja tarjoava teleyritys**

definition
teleföretag som tillhandahåller mobiltjänster

Lähde: Matkaviestinsanasto (TSK 29, 2001)
https://termipankki.fi/tepa/fi/haku/matkaviestinoperaattori

**Comment by mirmaid** [comment]
^ Jos halutaan säilyttää ero kuvailuissa, matkaviestinpalvelut vaatisi tarkenteen ja ehkä hierarkian korjauksen. Ehkä myös jonkun ohjauksen pois mobiilipalveluista.

**Comment by mariaforsen** [comment]
Ruotsiksi pitäisi varmaan keksiä jokin ihan uusi termi? Pysyisin Matkaviestinsanaston antamassa ratkaisussa, en tiedä miten tämä olisi ratkaistavissa, jos todella pidetään molemmat termit erillisinä?

**Comment by ilona-x** [comment]
Käsitekaavio Matkaviestinpalvelu
![kuva](https://user-images.githubusercontent.com/21304210/167639342-7d92b761-56d9-4623-ae10-23182b52e66e.png)
Lähde:Matkaviestinsanasto (TSK 29, 2001) https://termipankki.fi/tepa/mot/mot.exe?base=2&att=TSK29\MVPALV.gif

Käsitekaavio Mobiilipalvelu
![kuva](https://user-images.githubusercontent.com/21304210/167640440-1a5e04e3-42e7-49ce-8cbb-1e16574934fd.png)
Lähde: Mobiilisanasto – Matkaviestinsanaston (TSK 29) täydennysosa (TSK 48, 2015) https://termipankki.fi/tepa/mot/mot.exe?base=2&att=TSK48\mobiilipalvelut.gif

Käsitekaavio Tietoliikennepalvelu: 
![kuva](https://user-images.githubusercontent.com/21304210/167640678-b53e6a61-66ae-497e-a8ed-8596cd359dea.png)
Lähde: Matkaviestinsanasto (TSK 29, 2001)
https://termipankki.fi/tepa/mot/mot.exe?base=2&att=TSK29\PALVELU.gif

**Comment by mirmaid** [comment]
Olisiko ero selkeä, jos olisi _matkaviestinpalvelut (tietoliikennepalvelut)_? Voisi myös tutkia, onko mobiilipalvelut käytetty oikein, vai tarvitseeko jotain mobiilipalvelut (tietoliikennepalvelut) KÄ matkaviestinpalvelut (tietoliikennepalvelut) tms. 

Pikavilkaisulla ehkä tarvitaan, esim.
https://melinda.kansalliskirjasto.fi/byid/013712304
https://melinda.kansalliskirjasto.fi/byid/017445864

**Comment by ilona-x** [comment]
**matkaviestinpalvelut (tietoliikennepalvelut)** kuulostaa kelvolliselta ratkaisulta.

Pitääkö tässä huomioida jotenkin, että YSOssa on tietoliikennepalvelut KÄYTÄ telepalvelut?
Eli olisiko **matkaviestinpalvelut (telepalvelut)**, sitä tuskin ainakaan tulisi kovin herkästi käytettyä mobiilipankkien tmv. mobiilipalveluiden yhteydessä, kun käytössä on myös termi mobiilipalvelut.

**Comment by mirmaid** [comment]
^ Tulisiko vielä mobiilipalvelut (telepalvelut) KÄ matkaviestinpalvelut (telepalvelut)?

**Comment by ilona-x** [comment]
> ^ Tulisiko vielä mobiilipalvelut (telepalvelut) KÄ matkaviestinpalvelut (telepalvelut)?

Vähän epäilyttää, onko tuosta enemmän hyötyä kuin haittaa, mutta ehkä se on kuitenkin tarpeellinen ohjaus.
Hiukan myös arveluttaa se, että voiko mobiilipalvelut olla ilman tarkennetta, mutta siihen on määritelmän pohjalta vaikea keksiä mitään kovin ytimekästä sulkutarkennetta. Mutta ehkä ainakin määritelmät voisi lisätä näille molemmille termeille.

**mobiilipalvelut**
määritelmä
mobiililaitteella käytettäväksi suunniteltu palvelu Lähde: 
Lähde: Mobiilisanasto – Matkaviestinsanaston (TSK 29) täydennysosa (TSK 48, 2015)
https://termipankki.fi/tepa/fi/haku/mobiilipalvelu

**matkaviestinpalvelut (telepalvelut)**
KT matkaviestintäpalvelut (telepalvelut)
KT matkapuhelinpalvelut (telepalvelut)
KT mobiilipalvelut (telepalvelut)
määritelmä
radioliikenteeseen perustuva tietoliikennepalvelu, jonka avulla matkaviestimet voivat olla yhteydessä toisiinsa ja muihin päätelaitteisiin 
Lähde: Matkaviestinsanasto (TSK 29, 2001)
https://termipankki.fi/tepa/fi/haku/matkaviestinpalvelu

**Comment by FinMeSHienPaimentaja** [comment]
_matkaviestinpalvelut (tietoliikennepalvelut) kuulostaa kelvolliselta ratkaisulta_ OK

Entä erikseen myös mobiilipalvelut (tietoliikennepalvelut) - telepalvelut kuulostaa vanhahtavalta ja ennen kaikkea yllä käsitekaaviossa tietoliikennepalvelut on laajempi.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään tarkenne _matkaviestinpalvelut (telepalvelut)_. Ohjaustermeiksi _mobiilipalvelut (telepalvelut)_ ja _matkaviestinpalvelut (tietoliikennepalvelut)_. Lisätään matkaviestinsanaston määritelmät.

**Comment by mariaforsen** [comment]
Sv.
-mobiltjänster HT mobila tjänster
-mobilkommunikationstjänster (teletjänster) HT mobilteletjänster, mobiltjänster (teletjänster), mobiltelefontjänster 

https://termipankki.fi/tepa/fi/haku/matkapuhelinpalvelu
https://www.rikstermbanken.se/search?q=mobilkommunikationstj%C3%A4nst&s=termer
https://termipankki.fi/tepa/fi/haku/mobiilipalvelu
https://www.sanakirja.fi/custom/fi-en-sv/mobiilipalvelu

Onko matkaviestinpalveluiden yläkäsite (verkkopalvelut) nyt väärä, jos se on "verkkosivuston kautta tarjottava palvelu, nettipalvelu."?
