### ISSUE TITLE
paikannimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10088]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[paikannimet](http://www.yso.fi/onto/yso/p10410)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: toponyymit

**Perustelut ehdotukselle**

Synonymi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/toponyymi
