### ISSUE TITLE
Pohjalampi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10084]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pohjalampi](http://www.yso.fi/onto/yso/p137292)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne ja/tai muitakin Pohjalampia.

**Perustelut ehdotukselle**

Monessa eri paikassa Suomessa.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kolme samannimistä Liperissä...

**Comment by mirmaid** [comment]
Poistetaan ja siirretään tietueissa > 653.
