### ISSUE TITLE
ritarikunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10095]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ritarikunnat](http://www.yso.fi/onto/yso/p5956)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "ansioritarikunnat" tai luodaan siitä kokonaan uusi asiasanansa, jolloin nykyinen tarkoittaisi todellisia historiallisia ritarikuntia ja jälkimmäinen julkisen arvonannon osoituksia jakavia järjestöjä, sekä virallisia t.s. itsenäisen valtion ylläpitämiä (esim. "Vapaudenristin ritarikunta") että puolivirallisia (esim. "Pyhän Karitsan ritarikunta") ansioritarikuntia, samoin kuin näitä imitoivia yksityisluontoisia toimijoita (ks. https://en.wikipedia.org/wiki/Self-styled_order)

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. hist. järjestöjä joiden jäsenet sitoutuivat noudattamaan ritari-ihanteiden mukaisia sääntöjä, ritaristo. _Hengelliset ritarikunnat. Saksalainen ritarikunta._
2. ritarimerkin saaneiden henkilöiden ryhmä. _Suomen Leijonan ritarikunta._

**Comment by mirmaid** [comment]
https://www.presidentti.fi/ahtisaari/fin/instituutio/ritarikuntahistoria.html

Käytetty molemmista.

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Ansioritarikunta = https://en.wikipedia.org/wiki/Order_of_Merit
En kannata.

**Comment by fantsby-m** [comment]
^on muitakin ansioritarikuntia kuin tuo

**Comment by YSO-kokous** [comment]
### Päätös
Selvitetään vielä ovatko ruotsinkieliset vastineet eri tyyppisille ritarikunnille erillisiä. 
hisotiralliset ritarikunnat vs. ansioritarikunnat

**Comment by mariaforsen** [comment]
Sv.
-riddarordnar eli orders of knighthood/ritarikunnat?
-förtjänstordnar eli orders of merit/ansioritarikunnat?
https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_f%C3%B6rtj%C3%A4nstordnar

**Comment by YSO-kokous** [comment]
**Päätös**

Uutena terminä _ansioritarikunnat_, muutetaan _ritarikunnat_ muotoon _ritarikunnat (historia)_.

**Comment by mariaforsen** [comment]
Sv. riddarordnar > riddarordnar (historia)
-förtjänstordnar /ne https://id.kb.se/term/sao/F%C3%B6rtj%C3%A4nstordnar  Decoration of honor • lcsh

**Comment by mirmaid** [comment]
Korjausta tehdessä kävi ilmi, että myös ansioritarikunnat voivat olla hyvin vanhoja (esim. sukkanauharitarikunta) ja suuri osa historiallisista ritarikunnista on hengellisiä ritarikuntia (myös sanastossa).

**Comment by AuHo22** [comment]
ritarikunnat (aateli) / ritarikunnat (ritarilaitos)? maalliset ritarikunnat?
Jotain päällekkäisyyttä ehkä pakostakin

**Comment by mirmaid** [comment]
Näyttäisi siltä että hengelliset ritarikunnat ja ansioritarikunnat riittää, muihin ehkä ritarilaitos tai jokin ihan muu termi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään Mirjan yllä oleva ehdotus.
