### ISSUE TITLE
nuottijulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10098]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nuottijulkaisut](http://www.yso.fi/onto/yso/p2966)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "sävelmäjulkaisut" sekä SLM:ään että YSO:on

**Perustelut ehdotukselle**

Nimitystä on käytetty mm. painetussa kansallisbibliorafiassamme, esim. "Suomen kirjallisuus. 1944–1948. VI, Sävelmäjulkaisut : kartat : aiheenmukainen osasto ..." ([Helsinki]: Helsingin yliopiston kirjasto, 1966)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
