### ISSUE TITLE
Lamminniemen hovi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10097]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Lamminniemen hovi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Liperissä sijaitseva Lamminniemen hovi on vanha
hallinnollinen keskuspaikka. .. . Hallinnollisen keskuksen
ohella Lamminniemi oli suurmaatila, jonka mailla asui
ja työskenteli lukuisia torppareita.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kartanot](http://www.yso.fi/onto/yso/p832)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lamminniemenhovi :rakennushistoriaselvitys : Liperi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Lamminniemen hovi](http://finto.fi/yse/fi/page/Y510097)

**Comment by mariaforsen** [comment]
Sv. Lamminniemen hovi
