### ISSUE TITLE
luokituskaavat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10092]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luokituskaavat](http://www.yso.fi/onto/yso/p12632)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-termiksi

**Perustelut ehdotukselle**

Tarvitaan luokituskaavojen kuvailussa, esim. "Dewey Decimal Classification & Relative Index", joka ei käsittele luokituskaavoja vaan on itse sellainen

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Hyväksytään SLM-termiksi /SLM-kokous 19.4.2022

**Comment by mariaforsen** [comment]
Sv. klassifikationscheman
