### ISSUE TITLE
äärivasemmistolaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10105]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

äärivasemmistolaisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSO:ssa myös äärioikeistolaisuus

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston julkaisut, verkkosivut ja asiakirjat

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [äärivasemmistolaisuus](http://finto.fi/yse/fi/page/Y510105)

**Comment by mirmaid** [comment]
Pari kertaa Melindassa yksikössä ja monikossa. Hiukan enemmän muodossa _vasemmistoradikalismi_.

https://en.wikipedia.org/wiki/Far-left_politics

**Comment by mariaforsen** [comment]
Sv. vänsterextremism HT revolutionär vänster, ultravänster, radikal vänster, vänsterradikalism, yttervänster

**Comment by jarmosaarikko** [comment]
YK vasemmistolaisuus  | left-wing ideology | vänsterorientering | http://www.yso.fi/onto/yso/p448 
RT [ääriliikkeet](http://www.yso.fi/onto/yso/p19)  (vastaavasti on jo [äärioikeistolaisuus](http://www.yso.fi/onto/yso/p29340))

**Comment by YSO-kokous** [comment]
#### Päätös
Hyväksytään äärivasemmistolaisuus  

Perehdytään vielä miten ohjaustermejä käytetään. 
Ehdotuksia: vasemmistoradikalismi, ultravasemmisto. ultravasemmistolaisuus 
äärioikeistolaisuus OT oikeistoradikalismi
