### ISSUE TITLE
rakenteellinen syrjintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10102]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rakenteellinen syrjintä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ajankohtainen käsite.

**Ehdotettu yläkäsite YSOssa (LT)**

 [syrjintä](http://www.yso.fi/onto/yso/p6303)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston asiakirjojen julkaisujen ja verkkosivujen kuvailussa

**Ehdottajan organisaatio**

JUHO-ylläpito /VNK
**Termiehdotus Fintossa:** [rakenteellinen syrjintä](http://finto.fi/yse/fi/page/Y510102)

**Comment by jtuohini** [comment]
LT-suhteiksi myös [**sosioekonomiset tekijät**](http://www.yso.fi/onto/yso/p2134), [**yhteiskunnalliset ilmiöt**](http://www.yso.fi/onto/yso/p2241) ja [**yhteiskunnalliset järjestelmät**](http://www.yso.fi/onto/yso/p250) ja RT-suhteiksi [**sosiaalinen rakenne**](http://www.yso.fi/onto/yso/p4495), [**yhteiskuntarakenne**](http://www.yso.fi/onto/yso/p6314) yms.?

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. strukturell diskriminering HT indirekt diskriminering, inbyggd diskriminering
Ks. Kotoutumisen sanasto: 1. laitos (TEM 2021:54) https://termipankki.fi/tepa/fi/haku/strukturell%20diskriminering

https://sv.wikipedia.org/wiki/Strukturell_diskriminering
https://en.wikipedia.org/wiki/Structural_discrimination

**Comment by jarmosaarikko** [comment]
löytyy  yle.fi sisällöstä ainakin 2017 alkaen kymmeniä osumia. esim. https://yle.fi/aihe/artikkeli/2017/03/10/atlas-saarikoski-kirjallisuus-harvojen-kasissa, https://haku.yle.fi/?query=rakenteellinen%20syrjint%C3%A4&type=article

fi-wikipediassa kuvattu Syrjintä-sivulla: https://fi.wikipedia.org/wiki/Syrjint%C3%A4#Rakenteellinen_syrjint%C3%A4
