### ISSUE TITLE
hyvinvointialueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10101]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hyvinvointialueet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ajankohtainen käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston aineistoissa esim. Valton julkaisut,  asiakirjat , verkkosivut

**Ehdottajan organisaatio**

JUHO-ylläpito/ VNK 
**Termiehdotus Fintossa:** [hyvinvointialueet](http://finto.fi/yse/fi/page/Y510101)

**Comment by jtuohini** [comment]
LT-suhteeksi varmastikin [**hallintoalueet**](http://www.yso.fi/onto/yso/p6818) ja RT-suhteeksi kenties [**sosiaali- ja terveysalueet**](http://www.yso.fi/onto/yso/p27746).

**Comment by ilona-x** [comment]
Pitäisiköhän tuon YSOsta löytyvän sosiaali-ja terveysalueet -termin kanssa toimia samoin kuin maakuntavaalien kanssa toimittiin, eli sosiaali- ja terveysalueet KÄYTÄ hyvinvointialueet? Kun nuo sosiaali-ja terveysalueet eivät ole tainneet olla olemassa, vaan liittyivät sote-uudistukseen 🤔 Ja sanastosta löytyy kuitenkin myös sote-uudistus & maakuntauudistus.

Esimerkiksi YLEllä sosiaali- ja terveysalueet käytetty suomeksi 2 kertaa ja ruotsiksi 4 kertaa, ja osa artikkeleista käsittelee hyvinvointialueita https://yle.fi/aihe/t/18-237227

**Comment by jarmosaarikko** [comment]
RT aluevaalit (Suomi)

**Comment by YSO-kokous** [comment]
### Päätös
päätermin muutos sosiaali- ja terveysalueet KÄYTÄ hyvinvointialueet

**Comment by mariaforsen** [comment]
Sv. välfärdsområden /finlex, https://termipankki.fi/tepa/fi/haku/v%C3%A4lf%C3%A4rdsomr%C3%A5de
