### ISSUE TITLE
jihadismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10104]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jihadismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Selite:Jihad [jihad t. džihad] (arab. جهاد‎, jihād) tarkoittaa Pyhää sotaa, jota käydään ei-muslimeita vastaan. Islamilaisen selityksen mukaan sana on johdettu termistä mujahada, joka merkitsee sodankäyntiä uskonnon puolesta. (LG)

**Perustelut ehdotukselle**

Käytetään sisäministeriössä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ääriliikkeet](http://www.yso.fi/onto/yso/p19)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston julkaisut, verkkosivut ja asiakirjat

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [jihadismi](http://finto.fi/yse/fi/page/Y510104)

**Comment by mirmaid** [comment]
Sanastossa nyt jihad KÄ pyhä sota.

https://fi.wikipedia.org/wiki/Jihadismi

6 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Kannatan erikseen pyhä sota/uskonnollinen sota ja ST jihadismi. Pyhä sota on laajempi käsite joka koskee myös muita uskontoja kuin islam. Ks. esim. https://fi.wikipedia.org/wiki/Uskonnollinen_sota 
SAOssa: https://id.kb.se/find?q=jihadism

**Comment by YSO-kokous** [comment]
#### Päätös
Hyväksytään jihadismi

**Comment by mariaforsen** [comment]
Sanastossa on siis jo jihad KÄYTÄ pyhä sota, mutta tarkoitus oli kai pitää nämä erillisinä, niin että pyhä sota käytetään myös muista uskonnoista kuin pelkästään islamista, ja jihadismi nimenomaan islamista?

**Comment by mariaforsen** [comment]
Sv. jihadism
