### ISSUE TITLE
Afrikan unioni tai AU-maat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10103]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Afrikan unioni tai AU-maat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Afrikan unioni on 55 Afrikan valtion muodostama kansainvälinen järjestö. Unioni perustettiin 9. heinäkuuta 2002 Etelä-Afrikassa, ja se on Afrikan yhtenäisyysjärjestön (OAU) sekä Afrikan talousyhteisön (AEC) seuraaja. Rakenteeltaan unioni muistuttaa Euroopan unionia ja Amerikan valtioiden järjestöä.

**Perustelut ehdotukselle**

Tarvitaan UM:n aineistoissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [valtioliitot](http://www.yso.fi/onto/yso/p4450)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston asiakirjat, verkkosivut ja julkaisut

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [Afrikan unioni tai AU-maat](http://finto.fi/yse/fi/page/Y510103)

**Comment by jtuohini** [comment]
Jos tarve viitata yhteisönä, ei kuulu YSO:on, vaan Kantoon, josta jo löytyykin: [**Afrikan unioni**](http://urn.fi/URN:NBN:fi:au:finaf:000029299).

Jos taas tarve viitata Afrikan unionin maihin alueena, ei siinäkään tapauksessa kuulu YSO:on, vaan YSO-paikkoihin. Vanhastaan ei siellä ole esimerkiksi EU-maita, Nato-maita eikä Varsovan liiton maita. Myöskään muita talous- tai puolustusliittoja ei näytä huomioidun alueellisessa mielessä. Olisi iso linjaus ottaa sellaiset maantieteelisinä käsitteinä, mutta mielestäni kannatettava, jos aineisto selvästi viittaa alueeseen, joka määrittyy yhteisön jäsenyyden kautta eikä ole helposti kuvailtavaissa luonnonmaantieteellisillä tai vastaavilla asiasanoilla.

LCSH:ssa on tätä tyyppiä (osin) edustavina vanhastaan ainakin [**Arab countries**](http://id.loc.gov/authorities/subjects/sh85006278), [**Developed countries**](http://id.loc.gov/authorities/subjects/sh2001000124), [**European Union countries**](http://id.loc.gov/authorities/subjects/sh94003571), [**Islamic countries**](http://id.loc.gov/authorities/subjects/sh85068436) ja [**Western countries**](http://id.loc.gov/authorities/subjects/sh2003008962), mutta ei Nato-maille eikä Varsovan liiton maille.

**Comment by mirmaid** [comment]
YSOssa on kyllä vastaavia (EU-maat, IVY-maat jne.). Näiden on varmaan ajateltu olevan jonkinlaisia toimijakollektiiveja enemmän kuin varsinaisesti kuvaavan maantieteellistä aluetta (EU-maat yhdessä ja erikseen, "EU-maiden talous" ei ole sama asia kuin "EU:n talous").

**Comment by mariaforsen** [comment]
Sv. AU-länder HT Afrikanska unionens länder, Afrikanska unionen
