### ISSUE TITLE
pirtu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10109]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pirtu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ehdotettu KAUNOon, entä YSO?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pirtu](http://finto.fi/yse/fi/page/Y510109)

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. ? Suhde väkiviinaan?
https://fi.wikipedia.org/wiki/Pirtu = https://sv.wikipedia.org/wiki/L%C3%A4karsprit

**Comment by jarmosaarikko** [comment]
MeSH ja Tero  pirtu KÄYTÄ etanoli

Voisiko lisätä  samalla tavalla ohjaustermiksi  pirtu, sprii  KÄYTÄ **etanoli** http://www.yso.fi/onto/yso/p10108
Muuten voi tulla ongelmia KOKOn kanssa.

**Comment by mirmaid** [comment]
Etanolin yläkäsite on alkoholit (yhdisteet), joten pirtu ei kyllä ole oikein sopiva ohjaustermi sille. Ei tämä toki ole välttämätön lisäys, mutta hyväksyttiin KAUNOonkin, eikä kuitenkaan ole mitenkään erityisesti fiktiivinen asia 🙂.

**Comment by YSO-kokous** [comment]
#### Päätös
Otetaan muodossa pirtu KÄYTÄ väkiviina  LT alkoholijuomat

**Comment by mariaforsen** [comment]
Sv. sprit+parentes, starksprit, läkarsprit, finsprit? 
https://www.finlex.fi/sv/laki/ajantasa/kumotut/1994/19941143
