### ISSUE TITLE
merkkihenkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10108]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[merkkihenkilöt](http://www.yso.fi/onto/yso/p20057)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KAUNO-kokouksessa pohdittiin ohjaustermien poistoa (ainakin "kansalliset suurmiehet"), sekä mahd. tilalle korkea-arvoiset henkilöt (tarpeen mukaan jotain muutakin?).

**Perustelut ehdotukselle**

Nykyiset ohjaustermit antavat kuvan "todella merkittävistä henkilöistä", ohjaako käyttöä väärin?

**Ehdottajan organisaatio**

KAUNO-ryhmä

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään ohjaustermi:  korkea-arvoiset henkilöt
Poistetaan ohjaustermit: kansalliset suurmiehet, suurmiehet
