### ISSUE TITLE
ilmastonmuutoksen torjunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10127]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ilmastonmuutoksen torjunta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Uusi käsite, joka esiintyy VN:n aineistoissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [torjunta](http://www.yso.fi/onto/yso/p792)

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valltioneuvoston verkkosivut, julkaisut, asiakirjat

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [ilmastonmuutoksen torjunta](http://finto.fi/yse/fi/page/Y510127)

**Comment by mirmaid** [comment]
Sanastossa nyt _ilmastonsuojelu_: tarkoittaa toimia ilmastonmuutoksen hillitsemiseksi ja torjumiseksi. Ohjaustermi?

**Comment by mariaforsen** [comment]
Kannatan ohjausterminä.
Sv. HT klimatåtgärder, bekämpning av klimatförändringen

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään ohjausterminä ilmastonmuutoksen torjunta KÄYTÄ ilmastonsuojelu
