### ISSUE TITLE
positiivinen luottorekisteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10124]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

positiivinen luottorekisteri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Positiivinen luottorekisteri on tietokanta, josta luoton myöntäjä näkee reaaliaikaisesti hakijan lainamäärät ja tulotiedot. 

**Perustelut ehdotukselle**

Ajankohtainen aihe. Aihetta käsitelty VN:n julkaisuissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [rekisterit](http://www.yso.fi/onto/yso/p82)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston asiakirjat, julkaisut ja vetrkkosivut.

**Ehdottajan organisaatio**

JIUHO-ylläpito VNK
**Termiehdotus Fintossa:** [positiivinen luottorekisteri](http://finto.fi/yse/fi/page/Y510124)

**Comment by jtuohini** [comment]
Sama ehdotus kuin https://github.com/Finto-ehdotus/YSE/issues/10123
