### ISSUE TITLE
päästökompensaatio tai päästökompensointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10126]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

päästökompensaatio tai päästökompensointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

rahallista hyvitystä, jolla pyritään kumoamaan aiheutettujen kasvihuonekaasupäästöjen vaikutukset rahoittamalla päästöjen vähentämiseen tähtääviä toimia toisaalla. (lähde Wikipedia)

**Perustelut ehdotukselle**

Ajakohtainen käsite, jota on käytetty VN:n aineistoissa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston asiakirjat, verkkosivut ja julkaisut.

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [päästökompensaatio tai päästökompensointi](http://finto.fi/yse/fi/page/Y510126)

**Comment by ilona-x** [comment]
IATE3
fi        hiilikompensaatio ★★★☆;
päästökompensaatio ★★★☆;
päästöjen kompensointi ★★★☆
en      carbon offsetting ★★★☆
	  
Lähde: IATE 02.02.2022, Euroopan unioni (3533364)
https://termipankki.fi/tepa/fi/haku/p%C3%A4%C3%A4st%C3%B6kompensaatio

IATE4
fi        päästökompensaatio ★★★☆;
päästöhyvitys ★★★☆;
hiilidioksidin neutralointi ★★★☆
sv       utsläppskompensation ★★★☆;
utsläppskredit ★★★☆
en      carbon offset credit ★★★☆;
carbon offset ★★★☆

	  
Lähde: IATE 02.02.2022, Euroopan unioni (1194773)
https://termipankki.fi/tepa/fi/haku/p%C3%A4%C3%A4st%C3%B6kompensaatio

**Comment by mirmaid** [comment]
_Päästöt + kompensointi_ -yhdistelmää käytetty 11 kertaa Melindassa.

**Comment by mirmaid** [comment]
Wikipedialinkki: https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4st%C3%B6kompensaatio

**Comment by mariaforsen** [comment]
Ruotsiksi eniten "klimatkompensation" (ilmastokompensaatio). Vähemmän "utsläppskompensation".

**Comment by jarmosaarikko** [comment]
YSOssa on jo "[ekologinen kompensaatio](http://www.yso.fi/onto/yso/p38324)", mutta se lienee eri käsite.

Yläkäsite voisi olla näille yhteinen, se on muodossa [kompensointi](http://www.yso.fi/onto/yso/p22614)  KT kompensaatio
(huom eri taivutusmuoto alakäsitteen termissä).

Mikäli käsite halutaan sanastoon, niin **päästöhyvitys** kuulostaisi enemmän suomenkieliseltä kuin päästökompensointi, vaikkei ole käytetty varmaankaan yhtä paljon.

**Comment by mirmaid** [comment]
_Ekologinen kompensaatio_ -issue: https://github.com/Finto-ehdotus/YSE/issues/6863.

_Päästöhyvitys_ on kyllä hyvin vähän käytetty verrattuna _päästökompensaatio_-muotoon.

**Comment by YSO-kokous** [comment]
#### Päätökset
hyväksytään päästökompensaatio OT ilmastokompensaatio, hiilikompensaatio, päästöhyvitys
_OT = ohjaustermi_

**Comment by mariaforsen** [comment]
Sv. klimatkompensation HT utsläppskompensation, koldioxidkompensation, utsläppskompensering, klimatkompensering
https://www.naturochmiljo.fi/lar-dig-mer/perspektiv/klimatkompensering-ett-satt-att-kopa-gott-samvete/
https://www.sitra.fi/sv/ordbok/utslappskompensation/
