### ISSUE TITLE
positiivinen luottorekisteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10123]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

positiivinen luottorekisteri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Positiivinen luottorekisteri on tietokanta, josta luoton myöntäjä näkee reaaliaikaisesti hakijan lainamäärät ja tulotiedot. 

**Perustelut ehdotukselle**

Ajankohtainen aihe. Aihetta käsitelty VN:n julkaisuissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [rekisterit](http://www.yso.fi/onto/yso/p82)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston asiakirjat, julkaisut ja vetrkkosivut.

**Ehdottajan organisaatio**

JIUHO-ylläpito VNK
**Termiehdotus Fintossa:** [positiivinen luottorekisteri](http://finto.fi/yse/fi/page/Y510123)

**Comment by mirmaid** [comment]
Sanastossa on _luottotiedot_.

**Comment by mariaforsen** [comment]
Sv. positivt kreditregister?

**Comment by fantsby-m** [comment]
_Positiivinen luottotietorekisteri_ on valmisteilla, joten ehkä se päätermiksi?
https://www.vero.fi/positiivinenluottotietorekisteri/tietoa-positiivisesta-luottotietorekisterista/

**Comment by fantsby-m** [comment]
_Det positiva kreditupplysningsregistret_:
https://www.vero.fi/sv/positivakreditupplysningsregistret/det-positiva-kreditupplysningsregistret/

**Comment by mirmaid** [comment]
Entä laajempi termi, joka kattaisi erilaiset luottorekisterit, myös eri maissa? Vähän mietityttää yksittäisen rekisterin auktorisoiminen YSO-käsitteeksi.

**Comment by ilona-x** [comment]
Melindasta näyttää löytyvän jo nykyisin olemassa olevia "negatiivisia luotto(tieto)rekistereitä" käsitteleviä aineistoja, joiden kuvailussa on käytetty rekisterit, henkilörekisterit & luottotiedot -termejä

**Comment by YSO-kokous** [comment]
#### Päätökset
Otetaan käsite positiiviset luottorekisterit TAI positiiviset luottotietorekisterit. 
toinen muoto ohjaustermiksi.

**Comment by mariaforsen** [comment]
Sv. positiva kreditregister HT positiva kreditupplysningsregister
