### ISSUE TITLE
kaupunkisaamelaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10125]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaupunkisaamelaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Uusi ksäite, jota on käytetty VN:n julkaisuissa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston julkaisut, asiakirjat ja verkkosivustot.

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [kaupunkisaamelaiset](http://finto.fi/yse/fi/page/Y510125)

**Comment by jtuohini** [comment]
Ja tällä tarkoitetaan mitä? "Kaupunkisavolaiset", "kaupunkihämäläiset", "kaupunkisuomenruotsalaiset"?

Eikö kuvailussa riittäisi asiasanayhdistelmä **saamelaiset** + täsmällinen paikannimi (esim. **Helsinki** tai **Rovaniemi**) tai – jos yleisellä tasolla halutaan kuvailla – jokin sopiva toinen asiasana (esim. **kaupunkikulttuuri** tai **kaupunkiväestö**, jonka KT-muoto on _kaupunkilaiset_)?

**Comment by mariaforsen** [comment]
Sv. stadssamer HT urbana samer, samer i städer

**Comment by jarmosaarikko** [comment]
Voisiko lisätä ohjaustermiksi  kaupunkisaamelaiset  KÄYTÄ saamelaiset

**Comment by leen989** [comment]
Kaupunkisaamelaiset on tietääkseni saamelaisyhteisön käyttämä nimitys kaupungissa asuvista saamelaisista.

**Comment by fantsby-m** [comment]
https://fi.wikipedia.org/wiki/Kaupunkisaamelainen
https://annikoivisto.fi/2019/09/21/kaupunkisaamelaiset-ovat-tarkea-osa-saamelaisyhteisoa/

**Comment by annamarj** [comment]
YSOssa on tunturisaamelaiset ja metsäsaamelaiset. Asia näyttää liittyvän laajempaan määrittelyyn saamelaisryhmistä elinkeinon ja asuinpaikan mukaan: on olemassa mm. Metsä-, kalastaja- ja tunturisaamelaiset ry. Tulisiko harkita sekä kalastajasaamelaiset- että kaupunkisaamelaiset-lisäyksiä? Yhteen aikaan puhuttiin julkisuudessa citysaamelaisista. Olisiko sekin ohjausterminä siinä tapauksessa?

**Comment by mirmaid** [comment]
Tätä ei ole Lapponica-sanastossa (muut mainitut löytyvät) 🤔.

**Comment by annamarj** [comment]
Heissan!

Mielenkiintoinen tapaus….kun meillä on saame-asioita tunteva Niko talossa, niin voisi/n vaikka kysyä häneltäkin kommenttia – mutta onko tällainen pieni konsultointi ok, ettei ”turhaa vaivaamista”? En usko että hän pahastuisi kysymästä, jos ei halua ottaa kantaa niin ei pakko toki 😊

ovatkohan nuo muut ST siellä Lapponicassa, olikohan metsäsaamelaiset ja tunturi-…en katsonut.

Koetin kommentoida minkä osasin, ja
Seuraavaan kokoukseen sitten;
kuulemisiin!

Anna
