### ISSUE TITLE
alkuperäisrodut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10136]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[alkuperäisrodut](http://www.yso.fi/onto/yso/p28980)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yhdistetään käsitteeseen maatiaisrodut

**Perustelut ehdotukselle**

Termejä käytetään täysin ristiin.  Esim. https://www.maatiainen.fi/elaimet.htm , https://www.luke.fi/blogi/alkuperaisrodut-ovat-kulttuuriperintoamme/

Käsitteet ovat useimmissa kansainvälisissä sanastoissa yhdessä.
https://www.wikidata.org/wiki/Q174030 ,  
http://aims.fao.org/aos/agrovoc/c_4177 ,
https://termipankki.fi/tepa/fi/haku/maatiaisrotu  (IATE) 

Kts. myös https://www.ruokavirasto.fi/globalassets/tietoa-meista/asiointi/oppaat-ja-lomakkeet/viljelijat/tuet-ja-rahoitus/oppaat-ja-esitteet/alkuperaisrodut_esite.pdf -- 
https://www.luke.fi/tietoa-luonnonvaroista/geenivarat/elaingeenivarat/ -- Eläingeenivarohjelma käsittelee alkuperäisrotuja, jotka ovat kuitenkin maatiasirotuja. 

Kielitoimiston sanakirja: 
alkuperäisrotu
tietyllä alueella vanhastaan kasvatetusta eläinkannasta periytyvä, alueen oloihin sopeutunut kotieläinrotu.
KÄYTTÖESIMERKIT:  Suomenhevonen, pohjoissuomenkarja ym. alkuperäisrodut.

maatiais­rotu
1. jalostamaton t. vain vähän jalostettu kotieläinrotu.
2. alkuperäisrotu.

**Ehdottajan organisaatio**

FInto

**Comment by jarmosaarikko** [comment]
Melindassa:
alkuperäisrodut (yso/fin) 26 kpl (agrifors) 7 kpl  -- useat näistä viitteistä käsittelevät maatiaisrotuja
maatiaisrodut  (yso/fin) 410 kpl (agrifors) 52 kpl

**Comment by mirmaid** [comment]
Ei niin montaa vuotta sitten oli tärkeää, että nämä ovat sanastossa erikseen ja määritelmin varustettuna.

**Comment by mirmaid** [comment]
Nämä löytyvät myös AFOsta afo-käsitteinä, ja YSOn määritelmät on otettu AFOsta. Muistan kun tätä käsiteltiin (nyt siitä on toki jo reilut 10 vuotta), ja silloin siis pidettiin tärkeänä, että myös YSOssa on molemmat erikseen ja määritelmin varustettuna. Varmasti ovat hyvin päällekkäisiä ja esiintyvät usein yhdessä, mutta onko siitä varsinaista haittaa? Eri näkökulma kuitenkin asiaan.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
