### ISSUE TITLE
terveysturvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10130]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

terveysturvallisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Terveysturvallisuus on tartuntatautien ja biouhkien ehkäisemistä, havaitsemista ja torjuntaa (Lähde STM)

**Perustelut ehdotukselle**

Ajakohtainen käsite, esiintyy mm valtioneuvoston julkaisuissa  ja verkkosivuilla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [turvallisuus](http://www.yso.fi/onto/yso/p7349)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston verkkosivut, julkaisut ja asiakirjat.

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [terveysturvallisuus](http://finto.fi/yse/fi/page/Y510130)

**Comment by ilona-x** [comment]
Melinda x 2

https://en.wikipedia.org/wiki/Health_security

**Comment by ilona-x** [comment]
IATE3
fi        terveysturvallisuus ★★★☆
sv       hälsosäkerhet ★★★☆;
folkhälsosäkerhet ★★★☆
en      public health security ★★★☆;
health security ★★★☆

Lähde:IATE 02.02.2022, Euroopan unioni (928615)
https://termipankki.fi/tepa/fi/haku/terveysturvallisuus

**Comment by mirmaid** [comment]
Sanastossa on _bioturvallisuus_. Entä meneekö sekaisin _potilasturvallisuuden_ tai _lääkitysturvallisuuden_ kanssa?

https://thl.fi/fi/web/infektiotaudit-ja-rokotukset/taudit-ja-torjunta/bioturva/bioturvan-peruskasitteet

**Comment by mariaforsen** [comment]
Sv. hälsosäkerhet 
https://thl.fi/sv/web/thlfi-sv/thl/organisationsstruktur/avdelningar-och-enheter/halsosakerhet

**Comment by fantsby-m** [comment]
https://stm.fi/globaali-terveysturvallisuus
https://www.soste.fi/hyvinvointi-ja-terveys/terveysturvallisuus-osana-yhteiskunnan-kokonaisturvallisuutta/

**Comment by mirmaid** [comment]
THL:n sivua lukuunottamatta _bioturvallisuus_ näyttää Googlen viitteissä yleensä olevan käytössä maatalouden yhteydessä. Melindassa kuitenkin laajemmin. 

https://en.wikipedia.org/wiki/Biosecurity - tämä sitten kenties olisi alakäsite, käyttö ei ehkä kauhean johdonmukaisena pysy.

**Comment by ilona-x** [comment]
> Mikä ihmeen terveysturvallisuus?
> • Terveysturvallisuus (health security) on käsitteenä suomalaisessa keskustelussa melko uusi
> • Otettiin käyttöön pääosin 2000-luvun alussa
> • Aiemmin (ja yhä) käytössä olevia käsitteitä jotka sukua terveysturvallisuudelle ovat mm.
>  -Terveydensuojelu
>  -Kansanterveystyö
> -Ympäristöterveys
> -Tartuntatautien torjunta ja ennaltaehkäisy
> -Bioturvallisuus
> • Eivät kuitenkaan täysin kata terveysturvallisuuden käsitettä

Lähde: Koronapandemian opit tuleville polville / Professori Mika Salminen 
https://ennakointi.kymenlaakso.fi/files/33/Tulevaisuusseminaarin-materiaalit/41/Mika-Salminen-Koronapandemian-opit.pdf
