### ISSUE TITLE
lyömäsoittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10139]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lyömäsoittimet](http://www.yso.fi/onto/yso/p441)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "lyöntisoittimet"

**Perustelut ehdotukselle**

Käytetty mm. Gerhard Schepelernin kirjassa Orkesterin soittimet

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
