### ISSUE TITLE
monialainen yhteistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10132]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

monialainen yhteistyö

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Monialainen yhteistyö ymmärretään eri hallinnon- ja tieteenalat yhteen kokoavana ja niiden rajat ylittävänä toimintana. Monialainen työyhteisö voi koostua esimerkiksi eri koulutusalojen ja ammattiryhmien edustajista, opiskelijoista, asiakkaista ja yhteistyökumppaneista.

**Perustelut ehdotukselle**

Käytetty valtioneuvoston julkaisuissa

**Ehdotettu yläkäsite YSOssa (LT)**

 [yhteistyö](http://www.yso.fi/onto/yso/p6334)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston julkaisut, asiakirjat ja verkkosivut

**Ehdottajan organisaatio**

JUHO-ylläpito VNK
**Termiehdotus Fintossa:** [monialainen yhteistyö](http://finto.fi/yse/fi/page/Y510132)

**Comment by jtuohini** [comment]
Sama ehdotus kuin https://github.com/Finto-ehdotus/YSE/issues/10131

**Comment by mirmaid** [comment]
Sanastossa on _monialaisuus_ ja _poikkitieteisyys_.

**Comment by mariaforsen** [comment]
Sv. branschöverskridande samarbete HT multiprofessionellt samarbete, sektorsövergripande samarbete 
https://finlex.fi/sv/laki/ajantasa/2014/20141301
https://termipankki.fi/tepa/fi/haku/monialainen

**Comment by mirmaid** [comment]
Ei Melindassa fraasina, _monialaisuus + yhteistyö_ 118 kertaa samoissa viitteissä.

**Comment by YSO-kokous** [comment]
### Päätös
Äänestyksen jälkeen tetaan sanastoon monialainen yhteistyö KT  monialaisuus (yhteistyö)
Selvitetään miten monialaisuus -käsitettä on käytetty ja miten paljon menee päällekkäin tämän kanssa.  Esim. monialainen koulutus, monialayritykset.
