### ISSUE TITLE
terveyshyödyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10138]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[terveyshyödyt](http://www.yso.fi/onto/yso/p25168)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tähän lisätä ruotsiksi ohjaustermin hälsonyttor?

**Perustelut ehdotukselle**

https://www.abo.fi/nyheter/doktorsavhandling-om-delaktighet-som-halsobringande-nytta/

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Lisätty.
