### ISSUE TITLE
Dynamiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10145]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Dynamiitti

**Ehdotettu termi ruotsiksi**

Dynamit

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan aineiston kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-91-7987-354-7 Fakta om dynamit

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Dynamiitti](http://finto.fi/yse/fi/page/Y510145)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.
https://fi.wikipedia.org/wiki/Dynamiitti

**Comment by ilona-x** [comment]
LCSH: Dynamite http://id.loc.gov/authorities/subjects/sh85040322
SAO: dynamit https://id.kb.se/term/sao/Dynamit
