### ISSUE TITLE
jaksollinen kasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10148]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jaksollinen kasvatus

**Ehdotettu termi ruotsiksi**

trakthyggesbruk

**Ehdotettu termi englanniksi**

even-aged forest management

**Tarkoitusta täsmentävä selite**

Jaksollisessa kasvatuksessa metsän kehityksessä on erotettavissa kasvatusvaihe ja uudistamisvaihe. Kasvatusvaiheessa metsänhoidon pääpaino on kasvavan puuston hoitamisessa taimikonhoidolla ja harvennushakkuin ja lopuksi tehdään pääte- eli uudistushakkuu. Lähde: Metsäkeskus https://www.metsakeskus.fi/fi/metsan-kaytto-ja-omistus/metsanhoito-ja-hakkuut/metsankasvatus-ja-kasvatushakkuut

**Perustelut ehdotukselle**

Koska jatkuva kasvatus metsänkäsittelymuotona on yleistynyt, on tarvetta erottaa omakseen sen vastakohta.

**Ehdotettu yläkäsite YSOssa (LT)**

 [metsänkasvatus](http://www.yso.fi/onto/yso/p24915)

**Ehdotetut temaattiset ryhmät**

 [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

 tasaikäiskasvatus, beståndsvård trädskiktsvis

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [avohakkuut](http://www.yso.fi/onto/yso/p8845)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Even-aged_timber_management)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. tämän tyyppisen julkaisun kuvailu: https://finna.fi/Record/arto.012895680. Tekeillä on mm. opinnäytteitä, joissa vertaillaan näitä kahta menetelmää.

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [jaksollinen kasvatus](http://finto.fi/yse/fi/page/Y510148)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. trakthyggesbruk HT beståndsvård trädskiktsvis 
https://sv.wikipedia.org/wiki/Trakthyggesbruk
https://www.metsakeskus.fi/sv/aga-och-anvanda-skog/skogsvard-och-avverkningar/skogsvard-och-gallring
