### ISSUE TITLE
uusiseelantilainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10147]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

uusiseelantilainen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

386-kenttään kansallisuudeksi

**Ehdotettu yläkäsite YSOssa (LT)**

 [väestöryhmään liittyvä rooli](http://www.yso.fi/onto/yso/p487)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [polynesialaiset](http://www.yso.fi/onto/yso/p25137)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Meg Mason: Murhe ja autuus https://melinda.kansalliskirjasto.fi/F/BDXM8B74C3UCCXLBPYEMU4YCCR62KP1H5GN5MXQAJRYFIPG6FM-00522?func=full-set-set&set_number=013070&set_entry=000003&format=999

kirjailija on uusiseelantilainen 

**Ehdottajan organisaatio**

Tampereen Kaupunginkirjasto
**Termiehdotus Fintossa:** [uusiseelantilainen](http://finto.fi/yse/fi/page/Y510147)

**Comment by petraunk** [comment]
Oikea muoto uusiseelantilaiset

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. nyzeeländare HT nya zeeländare
