### ISSUE TITLE
primaarinen hyperaldosteronismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10144]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

primaarinen hyperaldosteronismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/125091

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [primaarinen hyperaldosteronismi](http://finto.fi/yse/fi/page/Y510144)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D006929

Lääketieteen termit: primaarinen aldosteronismi: aldosteronismi jolle ei voida osoittaa lisämunuaiskuoren ulkopuolista syytä
aldosteronismi: hyperaldosteronismi | aldosteronin liikaerityksestä aiheutunut oireyhtymä, jolle ovat ominaisia mm. lihasheikkous, kohonnut verenpaine, hypokaleeminen alkaloosi sekä runsas juominen ja virtsaaminen

https://fi.wikipedia.org/wiki/Primaarinen_hyperaldosteronismi
https://www.terveyskirjasto.fi/dlk00993

**Comment by mariaforsen** [comment]
Sv. primär hyperaldosteronism, hyperaldosteronism, Conns sjukdom

**Comment by mirmaid** [comment]
(hyper)aldosteronismi voi siis olla primaarinen tai sekundaarinen. Eli joko primaarinen hyperaldosteronismi / primaarinen aldosteronismi tai hyperaldosteronismi / aldosteronismi.

**Comment by mariaforsen** [comment]
Sv. hyperaldosteronism HT Conns sjukdom, Conns syndrom, aldosteronism, primär hyperaldosteronism
