### ISSUE TITLE
linkitetty data

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10143]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

linkitetty data

**Ehdotettu termi ruotsiksi**

länkade data

**Ehdotettu termi englanniksi**

linked data

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sanastossa on jo "yhdistetty avoin tieto", "linked open data", mutta linkitetty data ei ole aina "avointa dataa".    "Linked data may also be open data, in which case it is usually described as linked open data (LOD)" 
Lnkitetty data ei ole aina avointa. 
Huom. LCSH:ssa nämä ovat samassa käsitteessä, Wikidatassa eri käsitteinä. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [data](http://www.yso.fi/onto/yso/p27250)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [yhdistetty avoin tieto](http://www.yso.fi/onto/yso/p26001)

**Vastaava käsite muussa sanastossa**

 [Wikidata: linkitetty data](http://www.wikidata.org/entity/Q515701), [LCSH: Linked data](http://id.loc.gov/authorities/subjects/sh2013002090), [sv.wikipedia: Länkade data](https://sv.wikipedia.org/wiki/L%C3%A4nkade_data), [en.wikipedia: Linked data](https://en.wikipedia.org/wiki/Linked_data)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston verkkosivut ja julkaisut

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto
**Termiehdotus Fintossa:** [linkitetty data](http://finto.fi/yse/fi/page/Y510143)

**Comment by mariaforsen** [comment]
Sv. länkade data HT länkad data
https://id.kb.se/find?q=l%C3%A4nkade%20data
https://finto.fi/tt/sv/page/t84
