### ISSUE TITLE
vesikkelit tai kalvorakkulat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10146]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vesikkelit tai kalvorakkulat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/130697

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [vesikkelit tai kalvorakkulat](http://finto.fi/yse/fi/page/Y510146)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kalvorakkula
https://tieteentermipankki.fi/wiki/Nimitys:kalvorakkula

**Comment by mirmaid** [comment]
_Kalvorakkulat_ varmaankin yksiselitteisempi termi.

**Comment by mariaforsen** [comment]
Sv. vesiklar

**Comment by mirmaid** [comment]
Sanastossa on nyt _solunulkoiset vesikkelit_, mutta se ei käy jos on kyse soluelimestä.

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään käsite vesikkelit KT kalvorakkulat
solunulkoiset vesikkelit LT vesikkelit
