### ISSUE TITLE
piktorialismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10140]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

piktorialismi

**Ehdotettu termi ruotsiksi**

piktorialism

**Ehdotettu termi englanniksi**

pictorialism

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Taiteentutkimuksessa vakiintunut käsite. Asiaa mahdoton täsmällistä ilmaista muuten.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Piktorialismi : valokuvataiteen synty 

**Ehdottajan organisaatio**

Kirjastopalvelu/OH
**Termiehdotus Fintossa:** [piktorialismi](http://finto.fi/yse/fi/page/Y510140)

**Comment by jtuohini** [comment]
LCSH-siltaus: [**Pictorialism (Photography movement)**](http://id.loc.gov/authorities/subjects/sh94000092). Ja Wikidata-siltaus: https://www.wikidata.org/wiki/Q851869. Temaattiseksi ryhmäksi varmaan mieluummin 96 kuin 92.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Piktorialismi

4 viitettä Melindassa.

**Comment by ilona-x** [comment]
VALO: **piktorialismi** http://www.yso.fi/onto/valo/p1489

**Comment by mariaforsen** [comment]
https://id.kb.se/find?q=piktorialism
