### ISSUE TITLE
Naapurinvaara (Sotkamo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10153]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Naapurinvaara (Sotkamo)](http://www.yso.fi/onto/yso/p124928)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäiskö tämä jakaa? Tai ainakin korjata huomautus: Naapurinvaara on sekä kylä että vaara Sotkamossa, mutta pnr-linkki vain kylään

**Perustelut ehdotukselle**

Vaaroista kaunein : Naapurinvaaran maisemanhoitoja käyttösuunnitelma
https://urn.fi/URN:ISBN:978-952-314-804-8

kohouma Paikkatietoalustalla: http://paikkatiedot.fi/so/1000772/10270198

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Nämäkin ovat käytännössä ihan samassa paikassa. Vastaa varmaan tilannetta, jossa kylä on saaressa. Onkohan näissä tilanteissa hyödyllisempää huomioida tilanne huomautuksessa jotenkin? Linkitys molempiin?

**Comment by mirmaid** [comment]
Poistetaan huomautus.
