### ISSUE TITLE
käännösstrategiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10158]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

käännösstrategiat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tämä on peruskäsite kääntämiseen littyyvissä tutkimuksessa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kaikessa aineistossa, missä käsitellään kääntämistä lähtökielestä kohdekieleen.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [käännösstrategiat](http://finto.fi/yse/fi/page/Y510158)

**Comment by jtuohini** [comment]
Jos ehdotettua asiasanaa on tarkoitus käyttää "[k]aikessa aineistossa, missä käsitellään kääntämistä lähtökielestä kohdekieleen", niin kysehän olisi suunnilleen samasta kuin mihin nyt käytetään [**kääntäminen**](http://www.yso.fi/onto/yso/p9586)-asiasanaa. Kai tällä nyt ehdotetulla on jokin merkitysero aiempaan ja se myös käyttötarkoitukseltaan olisi aidosti erilainen?

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/K%C3%A4%C3%A4nn%C3%B6stiede:k%C3%A4%C3%A4nn%C3%B6sstrategia

**Comment by mirmaid** [comment]
N. 30 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. översättningsstrategier

**Comment by fantsby-m** [comment]
Tässä on harvinaisen perusteellinen Wikipedia-artikkeli, joka avaa mm. käännöstrategian merkitystä:
https://fi.wikipedia.org/wiki/Kotouttaminen_ja_vieraannuttaminen_(k%C3%A4%C3%A4nn%C3%B6stiede)

**Comment by mirmaid** [comment]
Sanastossa on muuten _kotouttaminen (käännöstiede)_, _vieraannuttaminen_ sen sijaan on ilman tarkennetta ja sitä on käytetty sekä kääntämisen yhteydessä, että muissa konteksteissa. Ehkä siinä ei kuitenkaan ole samanlaista ilmeistä ongelmaa kuin kotouttamisen osalta.
