### ISSUE TITLE
Hiljaiset kirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10155]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Hiljaiset kirjat

**Ehdotettu termi ruotsiksi**

Tysta böcker

**Ehdotettu termi englanniksi**

Silent books

**Tarkoitusta täsmentävä selite**

SLM-termiehdotus

**Perustelut ehdotukselle**

Etenkin opettajat kyselevät näitä. Hiljaiset tai sanattomat kirjat ovat teoksia, joissa ei ole perinteistä tekstiä, mutta ne ovat erityisen rikkaita visuaalisuudestaan. Perinteisissä kuvakirjoissa on sekä kuvia että tekstiä ja yhdessä ne muodostavat tarinan. Hiljaisissa kirjoissa kuvat kertovat kaiken, jolloin kirjat jättävät paljon tilaa mielikuvitukselle. Hiljaiset kirjat sopivat kaikille lapsille, nuorille ja aikuisille ja ne ovat terapeuttista luettavaa myös pakolaistaustaisille lapsille. 
https://www.stadsbiblioteket.nu/silent-books/
https://sites.utu.fi/iki-taru/taidelahtoiset-menetelmat/hiljaiset-kirjat/

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Netti, Eveliina. Pinnalla pinnan alla
Palin, Merja. Taikapuikot

**Ehdottajan organisaatio**

Porvoon kaupunginkirjasto
**Termiehdotus Fintossa:** [Hiljaiset kirjat](http://finto.fi/yse/fi/page/Y510155)

**Comment by AuHo22** [comment]
https://peda.net/kouvola/perusopetus/hankkeet/lukeva-kouvola/kirjavinkkausta/hiljaiset-kirjat
https://kuvittajat.fi/kuvittaja-posts/sanattomat-kuvat

**Comment by ilona-x** [comment]
tekstittömät kirjat https://github.com/Finto-ehdotus/YSE/issues/2798

**Comment by mirmaid** [comment]
Suhde termeihin _tekstittömät kirjat, kuvakirjat_?

**Comment by jtuohini** [comment]
Vrt. "hiljainen kirja" -Google-haun kolmas osuma: https://www.ncc.fi/myncc/tyoturvallisuus-ja-terveys/hiljainen-kirja/ > https://www.ncc.fi/contentassets/bb0bb6445817415ba14cf0b2c40e2024/silent_book_a6_2016_vers5.pdf: "Kuvat kertovat enemmän kuin tuhat sanaa. NCC Hiljainen kirja on vähentänyt työtapaturmia NCC:n omilla työmailla. Siinä rohkaistaan puuttumaan epävarmoihin tilanteisiin ja riskialttiiseen käyttäytymiseen."

**Comment by mirmaid** [comment]
Palataan seuraavissa kokouksessa, Kauno-ryhmä käsittelee vielä.

**Comment by AuHo22** [comment]
https://www.helmet.fi/fi-FI/Lapset/Juttuja_kirjastoista/Kirjoja_lapsille_ilman_tekstia(226599)

Toimisiko ohjaustermilisäyksillä tekstittömät kirjat KT hiljaiset kirjat KT sanattomat kirjat

**Comment by mirmaid** [comment]
KAUNO-kokous: kannatetaan SLM-ryhmän keskustelussa esitettyä ratkaisua:
hiljaiset kirjat KÄ tekstittömät kirjat, sanattomat kirjat KÄ tekstittömät kirjat

**Comment by mirmaid** [comment]
hiljaiset kirjat KÄ tekstittömät kirjat
sanattomat kirjat KÄ tekstittömät kirjat
