### ISSUE TITLE
resistenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10159]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[resistenssi](http://www.yso.fi/onto/yso/p16107)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö laajentaa biologian puolelle pelkän lääketieteen lisäksi. 

**Perustelut ehdotukselle**

AFOssa esim. https://finto.fi/afo/fi/page/p1068 
Tarve olisi käyttää tähän julkaisuun: http://urn.fi/URN:ISBN:978-952-326-200-3

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
Halutaan siis lisätään YSO-ryhmät 15 Biologia, 16. Kasvitiede ja 17 eläintiede?  
Eng-termissä tarvitaan tarkenne erottamaan vastarintaliikkeistä ja lukuisista muista käyttötapauksista:
- https://en.wikipedia.org/wiki/Resistance 
- joten mieluummin uusi käsite esim.  resistessi (biologia)

Ehdotuksen julkasuun liittyen tässä voisi ehdottaa saman tien alakäsitteen lisäämistä AFO:sta: 
- **torjunta-aineresistenssi**  [pesticide resistance](https://en.wikipedia.org/wiki/Pesticide_resistance)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7160

**Comment by mirmaid** [comment]
_Taudinkestävyys (kasvit)_ kaipaisi myös varmaan resistenssi-ohjaustermin.

**Comment by mariaforsen** [comment]
Termi on ruotsiksi resistens ja se sopiikin myös kasveista yms. Eli jos tämä on tarkoitus viitata vain lääketieteeseen, niin ruotsiksi pitäisi oikeastaan olla tarkenne.

**Comment by mirmaid** [comment]
En kyllä oikein hahmota mitä erottelua siinä lääketiede vs. biologia -tarkenteilla sitten tehtäisiin. Nythän YK on biologiset ominaisuudet. Ryhmien lisääminen on omasta puolestani ok. 

Yllä viitatussa issuessa onkin mainittu, että ruotsiksi on ollut tarkenne, joka on poistettu.

Sitä myös tässä kyselen, tarvitaanko _taudinkestävyys (kasvit)_ ja _tuholaiskestävyys_ -käsitteille myös resistenssi-alkuisia ohjaustermejä, jotta ne löytyisivät paremmin? Resistenssi (tuholaiskestävyys) ja resistenssi (kasvin taudinkestävyys) tms. Ja olisiko niille ok paikka hierarkiassa resistenssin alakäsitteinä?

**Comment by mirmaid** [comment]
Ehdotus: resistenssi (tuholaiskestävyys) ja resistenssi (kasvin taudinkestävyys) ohjaustermeiksi mainituille päätermeille.
Ryhmien lisäys.
