### ISSUE TITLE
kirsikkatomaatti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10154]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kirsikkatomaatti

**Ehdotettu termi ruotsiksi**

körsbärstomat

**Ehdotettu termi englanniksi**

cherry tomato

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirsikkatomaatti (Solanum lycopersicum var. cerasiforme) on tomaatin muunnos, jonka nimi johtuu sen pienestä koosta.
https://fi.wikipedia.org/wiki/Kirsikkatomaatti

**Ehdotettu yläkäsite YSOssa (LT)**

 [tomaatti](http://www.yso.fi/onto/yso/p20111)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533), [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [AFO](http://www.yso.fi/onto/afo/p1436), [AFO](http://www.yso.fi/onto/afo/p5851)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-326-870-8

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kirsikkatomaatti](http://finto.fi/yse/fi/page/Y510154)

**Comment by mariaforsen** [comment]
Sv. körsbärstomat HT cocktailtomat, cherrytomat

**Comment by mirmaid** [comment]
Onko muuten miniluumutomaatti KT?
