### ISSUE TITLE
jousikvartetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10152]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jousikvartetit

**Ehdotettu termi ruotsiksi**

stråkkvartetter (musikgrupper)

**Ehdotettu termi englanniksi**

string quartets (ensembles (groups))

**Tarkoitusta täsmentävä selite**

Jousikvartettoja (esityskokoonpano: 2 viulua, 1 alttoviulu ja 1 sello) esittävä yhtye.

**Perustelut ehdotukselle**

Tarvitaan jousikvartetteja käsittelevän aineiston kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://lccn.loc.gov/sh99011235)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/000569568

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [jousikvartetit](http://finto.fi/yse/fi/page/Y510152)

**Comment by jtuohini** [comment]
Ja LT-suhteiksi arvattavasti sekä [**kvartetit**](http://www.yso.fi/onto/yso/p30113) että [**soitinyhtyeet**](http://www.yso.fi/onto/yso/p27211).

**Comment by mariaforsen** [comment]
Sv. stråkkvartetter (ensembler)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LCSH-vastine http://id.loc.gov/authorities/subjects/sh99011235
