### ISSUE TITLE
Merimaskun kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10151]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Merimaskun kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Merimaskun kirkon kunnostustyöt

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Merimaskun kirkko](http://finto.fi/yse/fi/page/Y510151)

**Comment by mariaforsen** [comment]
Sv. Merimasku kyrka
