### ISSUE TITLE
tyrosiinikinaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10161]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tyrosiinikinaasit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/131430

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tyrosiinikinaasit](http://finto.fi/yse/fi/page/Y510161)

**Comment by jarmosaarikko** [comment]
LIeneekö sama kuin 
- FinMesh: [proteiinityrosiinikinaasit](http://www.yso.fi/onto/mesh/D011505)
- WIkidata:  [protein tyrosin kinase](http://www.wikidata.org/entity/Q87099740)
- en-wikipedia: [tyrosin kinase](https://en.wikipedia.org/wiki/Tyrosine_kinase)

**Comment by mariaforsen** [comment]
Sv. tyrosinkinaser HT protein-tyrosinkinaser

**Comment by mirmaid** [comment]
On sama, tyrosiinikinaasit KT proteiinityrosiinikinaasit?

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/330040
