### ISSUE TITLE
mielikuvitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10162]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mielikuvitus](http://www.yso.fi/onto/yso/p8511)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT fantasia (psykologia) ja mahdollisesti myös kuvittelukyky?

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/mielikuvitus?searchMode=all

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
ALLFO: inbillningsförmåga HT fantasi (psykologi)

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Filosofia:imaginaatio

**Comment by YSO-kokous** [comment]
### Päätös
Ei oteta ehdotettuja termejä ohjaustermeiksi.
Ruotsinkielinen päätermi menee vielä Aasi-ryhmän käsittelyyn. 
Mielikuvitus on suomeksi täysin yksiselitteinen. Fantasia viittaa ensisijaisesti mielikuvituksen tuotteisiin eli kuvitelmiin.
