### ISSUE TITLE
akuutti lymfaattinen leukemia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10160]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[akuutti lymfaattinen leukemia](http://www.yso.fi/onto/yso/p24089)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT akuutti lymfoblastileukemia

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. HT akut lymfoblastisk leukemi, akut lymfoblastleukemi

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termeissä (Duodecim, Terveysportti) - vaikkakin  sama lyhenne ALL - näyttää olevan erikseen:

**akuutti lymfaattinen leukemia** leuchaemia lymphatica acuta la, acute lymphocytic leukemia, acute lymphatic leukemia e, akut lymfatisk leukemi r (lyh. ALL) äkillinen imusoluleukemia | aikuisten akuuttien leukemioiden toinen päälaji, jossa poikkeavat solut ovat erilaistumattomia imusolujen esiasteita ja jossa maksan, pernan ja imusolmukkeiden suureneminen on tavallista; alalajeja B-solulinjan ja T-solulinjan akuutti lymfaattinen leukemia; vrt. akuutti lymfoblastileukemia

**akuutti lymfoblastileukemia** leuchaemia lymphoblastica acuta la, acute lymphoblastic leukemia, acute lymphocytic leukemia e, akut lymfoblastisk leukemi, akut lymfoblastleukemi r (lyh. ALL) lasten tavallisin, nopeasti kehittyvä leukemia, jonka kaikissa alalajeissa luuydin on epäkypsien imusolujen (lymfoblastien) täyttämä

**Comment by mirmaid** [comment]
^ Samoin Lääketieteen termit. Jaottelu aikuiset/lapset ei kuitenkaan ole näin selkeä näiden lähteiden ulkopuolella, vaatisi varmaan tarkenteet jos rajataan. 

https://www.terveydentukena.fi/sairaudet-ja-hoito/syopa/syopataudit/verisyovat/akuutti-lymfaattinen-leukemia
https://fi.wikipedia.org/wiki/Akuutti_lymfaattinen_leukemia
https://www.potilaanlaakarilehti.fi/artikkelit/leukemia-voi-olla-akuutti-tai-krooninen/
https://www.theseus.fi/bitstream/handle/10024/353203/ALL-OPAS%2023.11.2020.pdf?sequence=3&isAllowed=y
https://www.cancer.org/cancer/acute-lymphocytic-leukemia/about/what-is-all.html
https://medlineplus.gov/acutelymphocyticleukemia.html

**Comment by YSO-kokous** [comment]
Termejä käyteään paljon ristiin ja vaihtuneetkin vuosien varrella.
### Päätös
lisätään ohjaustermeiksi
akuutti lymfaattinen leukemiai KT akuutti lymfoblastileukemia, akuutti lymfoblastinen leukemia
