### ISSUE TITLE
tietokonelingvistiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10168]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tietokonelingvistiikka](http://www.yso.fi/onto/yso/p6069)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT laskennallinen kielitiede, laskennallinen lingvistiikka

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Liittyi tähän väitöskirjaan: https://www.tuni.fi/fi/ajankohtaista/kaj-syrjanen-laskennallinen-evoluutiotutkimus-tuo-tehokasta-uutta-metodologiaa. Ehdotettuja ohjaustermejä ei ole juuri käytetty, itselläni vaan kesti hetken keksiä _tietokonelingvistiikka_-termi, kun sitäkään ei käytetty ko. väitöskirjassa.

**Comment by YSO-kokous** [comment]
### Päätös
tietokonelingvistiikka KT laskennallinen kielitiede, laskennallinen lingvistiikka
