### ISSUE TITLE
pikkukeskoset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10173]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pikkukeskoset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 pienet keskoset

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/150416

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pikkukeskoset](http://finto.fi/yse/fi/page/Y510173)

**Comment by mirmaid** [comment]
https://www.terveyskyla.fi/lastentalo/tietoa-lasten-sairauksista/keskosena-kotiin/keskosuuden-m%C3%A4%C3%A4ritelm%C3%A4

https://www.tays.fi/fi-fi/palvelut/lastentaudit/vastasyntyneiden_ongelmat/pikkukeskosen_hoito

**Comment by mirmaid** [comment]
Lääketieteen termit: _very low birth weight premature (infant) e, mycket lågviktig prematur r (lyh. VLBW) keskonen jonka syntymäpaino on alle 1 500 g mutta yli 1 000 g tai joka on syntynyt raskausviikoilla 22–32_

**Comment by mariaforsen** [comment]
Sv. små prematurer

https://thl.fi/sv/web/thlfi-sv/-/hur-mar-sma-prematurer-som-vuxna-thl-s-uppfoljningsstudie-forsoker-minska-de-sma-prematurernas-halsorisker-i-vuxen-alde

Erilaiset määrittelyt.. https://www.terveyskyla.fi/lastentalo/sv/information-om-barns-sjukdomar/hem-med-en-prematur/definition-av-prematuritet :
"Prematurerna kan indelas i kategorier enligt vilken graviditetsvecka de föds i:
Lindrigt prematurt barn föds i graviditetsvecka 34+0–36+6.
Måttligt prematurt barn föds i graviditetsvecka 28+0–33+6.
Extremt ;prematurt barn föds före graviditetsvecka 28+0.
Också följande klassificering kan användas:
Prematur: födelsevikt under 2 500 g
Liten prematur: född ≤ graviditetsvecka 32+0 eller födelsevikt under 1500g
Mycket liten prematur: födelsevikt under 1000g."

**Comment by mirmaid** [comment]
^ Kuulostaa oikealta.

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään. Käsite kattaa kaikki pienemmät keskoset.
Lisätään huomautus, että on alle 1500g painoinen keskonen

**Comment by mariaforsen** [comment]
Sv. små prematurer
