### ISSUE TITLE
sähköautojen latausasemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10171]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sähköautojen latausasemat

**Ehdotettu termi ruotsiksi**

laddningsstationer för elbilar

**Ehdotettu termi englanniksi**

Battery charging stations (Electric vehicles)

**Tarkoitusta täsmentävä selite**

YLEllä aihe latausasema: https://yle.fi/uutiset/18-140396

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [ihmisen määrittämät paikat](http://www.yso.fi/onto/yso/p347)

**Ehdotetut temaattiset ryhmät**

 [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

 latausasemat (sähköautot), latauspisteet (sähköautot), sähköautojen latauspisteet, electric car charging points, laddningsställen för elbilar

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [huoltoasemat](http://www.yso.fi/onto/yso/p20442), [latauslaitteet](http://www.yso.fi/onto/yso/p7494)

**Vastaava käsite muussa sanastossa**

 [LCSH: Battery charging stations (Electric vehicles)](http://id.loc.gov/authorities/subjects/sh2012003590), [JUPO: sähköautojen latauspisteet](http://www.yso.fi/onto/jupo/p3010)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sähköautojen latausasemaverkosto Lapissa :suunnitelma verkoston toteuttamiseksi vuoteen 2030 mennessä https://urn.fi/URN:ISBN:978-952-316-386-7

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [sähköautojen latausasemat](http://finto.fi/yse/fi/page/Y510171)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mirmaid** [comment]
Myös https://www.verkkokauppa.com/fi/catalog/10472d/Sahkoautojen-latausasemat

**Comment by MarkoLatvanen** [comment]
JUPO:ssa on jo "sähköautojen latauspisteet"

**Comment by mirmaid** [comment]
^ Molempia käytetään sekä laitteesta, että "huoltoasemasta". Onko ongelma?

**Comment by ilona-x** [comment]
YSOssa on latauslaitteet http://www.yso.fi/onto/yso/p7494, olisiko mahdollista ohjata jotain käyttötapauksia siihen, esim. latauspisteet (latauslaitteet) & latausasemat (latauslaitteet) KÄYTÄ latauslaitteet 🤔 

Tuota latauslaitteet-termiä oli siis käytetty Melindassa sähköautojen latausta käsittelevissä aineistoissa, mutta tuossa minulla käsillä olleessa julkaisussa se ei ollut oikein mahdollinen, kun käsiteltiin sähköautojen latausasemaverkostoa.

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään käsite muodossa sähköautojen latauspisteet  KT  sähköautojen latausasemat
Hyväksytään ohjaustermit latauspisteet (latauslaitteet) & latausasemat (latauslaitteet) KÄYTÄ latauslaitteet

**Comment by mariaforsen** [comment]
Sv. laddningsställen för elbilar /JUPO HT laddstationer för elbilar, laddningsstationer för elbilar, laddpunkter för elbilar, laddningspunkter för elbilar, laddningsstationer för elfordon, laddningsställen för elfordon, laddningspunkter för elfordon
https://finlex.fi/fi/laki/ajantasa/2020/20200733
https://finto.fi/jupo/sv/page/p3010
