### ISSUE TITLE
monitoimityökalut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10178]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

monitoimityökalut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Monitoimikoneet ja monitoimilaitteet -käsitteille lisättiin tarkenne, käytetty melko paljon erilaisten monitoimityökalujen kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Artikkeliaineisto Melindassa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [monitoimityökalut](http://finto.fi/yse/fi/page/Y510178)

**Comment by mariaforsen** [comment]
Sv. universalverktyg, multiverktyg? Motin sanakirjoissa viitataan myös yleistyökaluihin.

**Comment by mirmaid** [comment]
^ Voisi varmaan olla ohjaustermi, monitoimityökalu kuitenkin käytetympi.

**Comment by YSO-kokous** [comment]
### Päätös
monitoimityökalut KT yleistyökalut

**Comment by mariaforsen** [comment]
Sv. multiverktyg HT universalverktyg https://svenska.se/tre/?sok=multiverktyg&pz=1 https://svenska.se/tre/?sok=universalverktyg&pz=1
