### ISSUE TITLE
tavarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10175]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tavarat](http://www.yso.fi/onto/yso/p2156)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko mahdollista jakaa tai rajata myytäviin tavaroihin?

**Perustelut ehdotukselle**

Ruotsiksi on pääasiassa kaksi vaihtoehtoa, joko saker (föremål) tai nykyinen vastine varor (esineet tms. kaupan kohteena). Sanastossa on myös esineet = föremål. Nyt on ruotsiksi väärä termi eli varor, sellaisissa tietueissa missä ei ole kyseessä kaupan kohteena olevista tavaroista, eli esim. Paikka kaikelle : mistä tavaratulva syntyy ja kuinka se padotaan / Ilana Aalto ; Hejdå saker : konsten att bli lyckligare genom minimalism / Fumio Sasaki ; översättning av Linda Skugge ; The minimalist home : a room-by-room guide to a decluttered, refocused life / Joshua Becker with Eric Stanford jne.  Ks. esim. https://www.kielitoimistonsanakirja.fi/#/tavara?searchMode=all 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
_Tavarat_ on kyllä laajempi kuin _esineet_, _saker_ olisi hyvä vastine, jos löytyisi jokin sallivampi tarkenne. Tavaroita voivat varsinaisten esineiden lisäksi olla vaatteet, ruoka- ja pesuainepakkaukset, toimistotarvikkeet, harrastusvälineet jnejne. Usein varmasti kuvailussa vähän turha sana, mutta käytetty kuitenkin lähes 900 kertaa Melindassa. Noissa aineistoissa, joissa hallitaan "tavaratulvaa", kohteena varmaan enemmän muu roina kuin se, mikä miellettäisiin "esineiksi".

**Comment by mariaforsen** [comment]
Sv. varor > saker (föremål)

**Comment by mariaforsen** [comment]
Olisi varmaan syytä muuttaa myös eng. goods > things tms. joka ei viittaa kauppatavaraan, kuten nyt ruotsiksikin muutettiin, tämän päätöksen mukaisesti.

**Comment by mirmaid** [comment]
^ Nämä muutokset onkin jo tehty, joten tilanne lienee kunnossa.
