### ISSUE TITLE
afrosuomalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10172]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

afrosuomalaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Afrosuomalaiset ovat suomalaisia, joilla on sukujuuria Saharan eteläpuolisessa Afrikassa (wikipedia).

**Perustelut ehdotukselle**

Termin käyttö yleistyy kyseisen väestönosan keskuudessa. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [suomalaiset](http://www.yso.fi/onto/yso/p3180)

**Ehdotetut temaattiset ryhmät**

 [61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [vähemmistöt](http://www.yso.fi/onto/yso/p5740), [suomalaisuus](http://www.yso.fi/onto/yso/p4880), [uussuomalaiset](http://www.yso.fi/onto/yso/p26754)

**Vastaava käsite muussa sanastossa**

 [WIkipedia](https://fi.wikipedia.org/wiki/Afrosuomalaiset)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Afrosuomalaisia esittävän valokuvasarjan

**Ehdottajan organisaatio**

Suomen valokuvataiteen museo
**Termiehdotus Fintossa:** [afrosuomalaiset](http://finto.fi/yse/fi/page/Y510172)

**Comment by mirmaid** [comment]
Melindassa kerran _afrosuomalaisuus_. Googlella n. 1400 (74 kun selaa viitteet loppuun). Ei ehkä kovin vakiintunut vielä.

**Comment by mariaforsen** [comment]
https://www.kielitoimistonsanakirja.fi/#/afro?searchMode=all
Merkityskenttä epäselvä, tarkaalleen mistä täytyy olla kotoisin jotta kuuluisi afrosuomalaisiin, ja onko tällainen ihmisten jaottelu hyvä?

**Comment by jarmosaarikko** [comment]
Sanastossa on jo samantyyppinen  **afroamerikkalaiset** http://www.yso.fi/onto/yso/p12789

Toisaalta, meillä ei liene olemassa samanlaista yhtenäistä afrikkalaisperäistä kulttuuria tai ihmisryhmää, jotka voisi nähdä tällaisen yhden termin alle muodostuvana kansanryhmänä tai kulttuurina. Tällöin käsite on tarpeeton eikä tällaista ihmisten jaottelua ehkä haluta ollenkaan kuten edellä Maria toteaa.

**Comment by YSO-kokous** [comment]
### Päätös
jää odottamaan laajempaa käyttöä.
