### ISSUE TITLE
profetismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10179]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[profetismi](http://www.yso.fi/onto/yso/p28944)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: profeetallisuus

**Perustelut ehdotukselle**

Käytetään runsaasti kristillisessa kirjallisuudessa, nyt kuvailijat ei näytä löytävän termiä, sen takia olisi tärkeä ohjausterminä. Esim. Lähemmäksi Jeesusta : matkalla profeetallisuuteen / Miisu Piipari.

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
### Päätös
profeetallisuus (profetismi) KÄYTÄ profetismi
