### ISSUE TITLE
mikroroskat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10186]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mikroroskat](http://www.yso.fi/onto/yso/p27844)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö päätermin kuitenkin olla mikromuovit.

**Perustelut ehdotukselle**

Mikromuoveista yleensä puhutaan.

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
"Mikromuovit" on mielestäni parempi kuin "mikroroskat" ("roska" on intuitiivisesti isokokoisempi eikä mikro-etuliitekään sitä oikein luontevasti pienennä).

**Comment by ilona-x** [comment]
IATE3
fi        mikroroska
sv       mikroskräp
en      microlitter;
micro-litter
	  
Lähde: IATE 02.02.2022, Euroopan unioni (3579064)
	  
IATE4
fi        mikromuoviroska ★★☆☆;
mikromuovi ★★★☆;
muovinen mikrohiukkanen ★★☆☆;
mikroroska ★★★☆
sv       mikroplastavfall ★★★☆
en      microplastic litter ★★★☆

Lähde: IATE 02.02.2022, Euroopan unioni (3550573)
https://termipankki.fi/tepa/fi/haku/mikroroska

**Comment by mariaforsen** [comment]
Mikromuovi voisi olla alakäsite, mikroroskia on muistakin materiaaleista kuin muovista.

**Comment by AuHo22** [comment]
https://www.ymparisto.fi/fi-FI/Meri/Itameren_tilan_seuranta/Roskaantumisen_ja_vedenalaisen_melun_seuranta/Mikroroska__haaste_jatevedenpuhdistamoil(46726)
Tässä viitataan myös mikroskooppisen pieniin tekstiilikuituihin. LT mikroroskat ST mikromuovit

**Comment by mirmaid** [comment]
Otetaanko mikromuovi(t) erikseen?

**Comment by mirmaid** [comment]
Mikromuovi: https://helda.helsinki.fi/handle/10138/333153

**Comment by mirmaid** [comment]
Mikromuovi KT mikromuovit

**Comment by mariaforsen** [comment]
Sv. mikroplast HT mikroplaster, plastpartiklar
https://id.kb.se/find?q=mikroplaster
https://svenska.se/tre/?sok=mikroplast&pz=1
