### ISSUE TITLE
saarnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10184]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[saarnat](http://www.yso.fi/onto/yso/p4897)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään SLM:ssä LT-suhteeksi "puheet"

**Perustelut ehdotukselle**

Saarnat ovat yhdenlaisia puheita, ja YSO:n puolella kyseinen suhde jo onkin.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
YSOssa jo LT/ST-suhde KT postillat / saarnakokoelmat

**Comment by mirmaid** [comment]
Lisätään ehdotetut KT-muodot ja yläkäsite.
