### ISSUE TITLE
koukuttavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10185]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

koukuttavuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käsite riippuvuus ei oikein sovi siihen tarkoitukseen, kun ei puhuta varsinaisesta diagnostisesta yksilön ongelmakäytöstä, vaan esimerkiksi siitä, että sosiaalisen median sovellukset on suunniteltu koukuttaviksi ja pitämään ihmiset käyttämässä palvelua. Eli ne koukuttavat kaikkia ihmisiä, riippumatta siitä, koetaanko käytön olevan ongelmakäyttöä vai ns. normaalia käyttöä. 

Tarvitsisimme siis käsitteen ei yksilön riippuuvuusongelmalle, vaan laitteen, sosiaalisen median, pelin tai muun ominaisuudelle, joka pyrkii koukuttamaan tai koukuttaa käyttäjiä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Aino-Mari Tuuri: Aikakone : ihmissuhteet digimaailmassa.
Johann Hari: Stolen focus.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [koukuttavuus](http://finto.fi/yse/fi/page/Y510185)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. beroendeframkallande (riippuvuutta aiheuttava) ?

**Comment by ilona-x** [comment]
IATE3
fi        riippuvuutta aiheuttava vaikutus;
riippuvuutta aiheuttava ominaisuus;
riippuvuuden aiheuttaminen
sv       beroendeframkallande egenskaper
en      addictiveness
	  
Lähde: IATE 02.02.2022, Euroopan unioni (3547851)
https://termipankki.fi/tepa/fi/haku/riippuvuutta%20aiheuttava%20ominaisuus

**Comment by YSO-kokous** [comment]
### Päätös
Äänestyksen jälkeen otetaan sanastoon muodossa addiktiivisuus  KT koukuttavuus

**Comment by mariaforsen** [comment]
Sv. beroendeframkallande HT beroendeframkallande egenskap
