### ISSUE TITLE
oppaat (teokset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10180]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oppaat (teokset)](http://www.yso.fi/onto/yso/p4641)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä kysymys koskee SLM-sanastoa: Onko tarkenne (teokset) harhaanjohtava, nyt kun RDA:ssa on myös ekspressio jne. SLM-sanastossa/genrekentässä (655) ei ole myöskään sekaannuksen vaaraa ammatin kanssa, kuten YSOssa. 

**Perustelut ehdotukselle**

Onko tarkenne tarpeen?

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ei muutosta.
