### ISSUE TITLE
maakauppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10181]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maakauppa](http://www.yso.fi/onto/yso/p18185)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan RT maanhankinta

**Perustelut ehdotukselle**

Poistetaan, Jos käsite liittyy esim. Maakauppalakiin, joka kielsi kaupankäynnin maaseudulla, eikä niinkään maanhankintaan.   https://fi.wikipedia.org/wiki/Maakauppa

Olisiko tässä merkityksessä termi ruotsiksi ilmeisesti landsköp?

maakauppa tai landsköp termiä ei löydy Finlexistä.  
Finlexissa markköp on samassa pykälässä suomeksi maanosto, joka voisi olla ohjausterminä käsitteessä maanhankinta.

**Ehdottajan organisaatio**

Finto-palvelu

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. maa-alueen kauppa. _Kunnan maakaupat._
2. hist. maaseudulla harjoitettu kauppa. _Vuoden 1734 laki kielsi pysyvän maakaupan._

**Comment by mirmaid** [comment]
Käytetty lähes yksinomaan 1. merkityksessä, mutta jos pitää rajata täysin siihen, vaatii tarkenteen (ja ehkä toisen termin historialliselle merkitykselle, tosin kauppa & maaseutu voisi myös riittää).

**Comment by jtuohini** [comment]
Eikö riitäävän toimiva lopputulos olisi erilliset asiasanat

- 1-merkitykselle: **maanhankinta**, KT _maakauppa (maanhankinta)_
- 2-merkitykselle: **maakauppa (vähittäiskauppa [tai jokin parempi tarkenne])**, KT _kaupankäynti maaseudulla_, _maaseutukauppa_ (jotka kummatkin KT-muodot löytyvät kirjallisuustakuun puitteissa).

**Comment by mirmaid** [comment]
^ Maakauppa on maanhankintaa ostajan näkökulmasta, voisiko olla maakauppa (maa-alueet) tms.?

**Comment by jtuohini** [comment]
RT-suhteeksi varmaan myös [**kiinteistökauppa**](http://www.yso.fi/onto/yso/p13798)? Maa-alueet (tilat ja tontit) ovat osa kiinteistöjä (https://www.kielitoimistonsanakirja.fi/kiinteistö).

**Comment by mariaforsen** [comment]
Aikaisemmin mainittu historiallinen merkitys (landsköp) ei siis ole ollut ALLFOssa ollenkaan, ja sille merkitykselle pitää olla erillinen ja selkeästi rajattu termi, jos halutaan mukaan.
Nykyinen maakauppa merkityksessä "kauppa jostain maa-alueesta" voisi ruotsiksi mahdollisesti olla tarkemmin markhandel/markaffär (nyt markköp), jos termi voi viitata sekä ostoon että myyntiin? Olisiko muuten OT maanosto ok?

**Comment by ilona-x** [comment]
> varsinkin jos termi voi viitata sekä ostoon että myyntiin? Olisiko muuten OT maanosto ok?

YSOssa on erikseen maanhankinta ([markförvärv](https://finto.fi/yso/fi/page/p7440?clang=sv). Pitäisikö maanosto ohjata näihin molempiin vai vain toiseen?  

Ja nyt jäin miettimään Jaakon ylempänä olevaa ehdotusta. Eli tarvitaanko sanastossa sekä maanhankinta että maakauppa (maa-alueet)?

https://termipankki.fi/tepa/fi/haku/maanhankinta

--

Melinda:
maakauppa x 300
maakauppa & maanhankinta x 74

--

Melindassa paljon esim. venäläisten maakauppoja koskevia aineistoja, mutta eivätkö yksityishenkilöiden kaupat ole melkein aina kiinteistökauppaa? 🤔 
https://termipankki.fi/tepa/fi/haku/kiinteist%C3%B6kauppa
https://termipankki.fi/tepa/fi/haku/kiinteist%C3%B6

**Comment by mariaforsen** [comment]
Jos maakauppa voi olla myös myyntiä, niin ei maanhankinta varmaan korvaa sitä.

**Comment by ilona-x** [comment]
**maakauppa**-termin käyttöä YLEllä https://yle.fi/aihe/t/18-215388

**Comment by mirmaid** [comment]
En ihan ehkä saa kiinni, mikä olisi toivottu lopputulos, mutta ehdotan edelleen _maakauppa (maa-alueet)_ ja ehkä myös maakauppa (kiinteistöt) KÄ kiinteistökauppa.

**Comment by ilona-x** [comment]
Ja varmaan vielä oma termi tuolle historialliselle maakaupalle? Melindassa vanhimissa maakauppa-termillä kuvailluissa aineistoissa näyttää olevan paljon tätä maaseudun maakauppaa.

**Comment by annamarj** [comment]
On ollut tärkeä asia historiassa.

**Comment by mariaforsen** [comment]
Eli uutena terminä:
landsköp = maakauppa  (historia)?

"Äldre benämning på mer eller mindre yrkesmässigt bedriven handel på landsbygden som var förbjuden i lag. Som straff konfiskerades varorna av kronan."
"Vanha nimitys enemmän tai vähemmän ammattimaisesti harjoitetulle ja laissa kielletylle kaupankäynnille maaseudulla. Rangaistuksena oli tavaroiden takavarikointi kruunulle."
/ https://fho.sls.fi/uppslagsord/2349/landskop/

**Comment by ilona-x** [comment]
'historiallisen' maakaupan tarkenteen keksiminen onkin hankalaa, riittääkö tuo pelkkä historia vai voiko sen ajatella tarkoittavan minkä tahansa maakaupan historiaa. Voisiko mahdollisesti olla **maakauppa (kaupankäynti maaseudulla)**?

**Comment by mariaforsen** [comment]
Jos vielä lisäisi huomautuksenkin, koska sehän pitää kuitenkin rajautua historialliseen merkitykseen, ei saa kattaa kaupankäyntiä maaseudulla nykyään..

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _maakauppa (kaupankäynti maaseudulla)_, ohjaustermiksi _maakauppa (historia)_. Lisätään määritelmä.

Lisätään _maakauppa (maa-alueet)_ sekä _maakauppa (kiinteistöt)_ KÄ _kiinteistökauppa_.
