### ISSUE TITLE
Laajalahti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10189]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Laajalahti](http://www.yso.fi/onto/yso/p145980)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa myös Laajalahti (Espoo)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tarkenteet?

**Comment by mariaforsen** [comment]
Lahti ja kaupunginosa?

**Comment by mirmaid** [comment]
Laajalahti (Espoo : kaupunginosa)
Laajalahti (Espoo : lahti) KT Laajalahti (Helsinki : lahti)
