### ISSUE TITLE
puolustusvoimat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10197]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[puolustusvoimat](http://www.yso.fi/onto/yso/p7457)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan KT-muoto "puolustuslaitos" monikkoon ja lisätään KT-muoto "itsepuolustusvoimat"

**Perustelut ehdotukselle**

YSO:ssa on vastaavalla tavalla laskettavissa olevasta ilmiöstä asisana "sotalaitokset", ei "sotalaitos", ja Japanin armeijasta käytetään nimitystä itsepuolustusvoimat.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Itsepuolustusvoimat tuntuu kyllä viittaavaan yksinomaan Japaniin.

**Comment by YSO-kokous** [comment]
### Päätökset
voidaan lisätä monikkomuoto ohjaustermiksi
säilytetään yksikkömuotokin ohjausterminä.

puolustuslaitokset  KÄYTÄ puolustusvoimat
