### ISSUE TITLE
mekaniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10195]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mekaniikka](http://www.yso.fi/onto/yso/p3753)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodoksi "klassinen mekaniikka" tai muutetaan koko asiasana kyseiseksi.

**Perustelut ehdotukselle**

Tällä hetkellä "mekaniikka"-asiasanaa näyttää käytetyn virheellisesesti esimerkiksi museoien kuva-aineistojen kuvailussa (https://www.finna.fi/Record/forssanmuseo.pju-13060 ja lähes sata muuta), joten jotakin pitäisi tehdä asiasanan selkiyttämiseksi ja sen virheellisen käytön vähentämiseksi.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ristoja** [comment]
katso myös: https://github.com/Finto-ehdotus/YSE/issues/10005#issuecomment-1024987908

**Comment by mirmaid** [comment]
Ohjaustermi ainakin ok.

**Comment by YSO-kokous** [comment]
### Päätökset
klassinen mekaniikka KÄYTÄ mekaniikka
