### ISSUE TITLE
jännityskirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10199]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[jännityskirjallisuus](http://www.yso.fi/onto/yso/p5087)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä ehdotus koskee SLM-termiä: psykologinen jännityskirjallisuus: uusi ohjaustermi: psykologiset trillerit

**Perustelut ehdotukselle**

Synonymi.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
psykologiset trillerit KÄ psykologinen jännityskirjallisuus
