### ISSUE TITLE
koiruoho

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10190]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

koiruoho

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

laji, kuvailuun

**Ehdotettu yläkäsite YSOssa (LT)**

 [marunat](http://www.yso.fi/onto/yso/p10502)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533)

**Vaihtoehtoiset termit**

 mali

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikipedia](https://fi.wikipedia.org/wiki/Koiruoho), [laji.fi](https://laji.fi/taxon/MX.39838)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://askelterveyteen.com/koiruohon-yllattavat-terveyshyodyt/

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [koiruoho](http://finto.fi/yse/fi/page/Y510190)

**Comment by mariaforsen** [comment]
Sv. malört (art) HT äkta malört
