### ISSUE TITLE
toffee

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10193]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

toffee

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

toffee

**Tarkoitusta täsmentävä selite**

"Toffee on makeinen, joka valmistetaan sokerista ja voista." (https://fi.wikipedia.org/wiki/Toffee) / "Toffee is a confection made by caramelizing sugar or molasses (creating inverted sugar) along with butter, and occasionally flour." (https://en.wikipedia.org/wiki/Toffee)

**Perustelut ehdotukselle**

Erittäin keskeinen osa myös suomalaista makeiskulttuuria; aihetta käsittelevää aineistoa mahdoton kuvata tarkoin muilla asiasanoilla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [makeiset](http://www.yso.fi/onto/yso/p6769)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

 voitoffee [fin], Russian fudge [eng], smörkola [swe], tjinuski [swe]

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013687013 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [toffee](http://finto.fi/yse/fi/page/Y510193)

**Comment by mariaforsen** [comment]
Sv. toffe HT kola (godis), toffee, gräddkola, gräddkaramell 
https://kaino.kotus.fi/fsob/?p=searchresults

**Comment by mirmaid** [comment]
^ Toffee taitaa aina olla jossain määrin pehmeä karkki, olenko väärässä vai voiko kola olla myös kova kermakaramelli?
