### ISSUE TITLE
intimiteetti/intiimiys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10191]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

intimiteetti/intiimiys

**Ehdotettu termi ruotsiksi**

[intimitet]

**Ehdotettu termi englanniksi**

intimacy 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ruotsiksi on jo sanastossa intimitet=yksityisyys, mutta se täytyy muuttaa (tehdään sen jälkeen kun on päätetty miten suomeksi suhtaudutaan vastaavaan termiin intimiteetti/intiimiys). Tämä käsite on myös LCSH:ssa ja SAOssa, toivotaan myös YSOon. Käytetty Melindassa ruotsin kannalta oikein esim. tähän: Lust & olust : om sex, närhet och anknytning / Malin Drevstam mutta väärin suurimpaan osaan (integritet, privatliv..) 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85067603.html), [SAO ](https://id.kb.se/find?q=intimitet)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Everyday friendships : intimacy and freedom in a complex world / Harry Blatterer, Macquarie University, Australia. ; Living, loving, and loss : the interplay of intimacy, sexuality, and grief / edited by Brad DeFord and Richard B. Gilbert. ; Emotional intimacy : a comprehensive guide for connecting with the power of your emotions / Robert Augustus Masters, PhD. ; Intimacy, transcendence, and psychology : closeness and openness in everyday life / Steen Halling.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [intimiteetti/intiimiys](http://finto.fi/yse/fi/page/Y510191)

**Comment by mirmaid** [comment]
Suomeksi varmaan tässä merkityksessä usein _läheisyys_, joka on sanastossa, ja jolla on englanniksi ohjausterminä intimacy.

**Comment by mariaforsen** [comment]
Mielestäni olisi tärkeä pitää nämä erillisinä.

**Comment by ilona-x** [comment]
SAOssa vain intimitet, jolla ohjausterminä närhet

--

Kielitoimiston sanakirja:

**intimiteetti**
= intiimiys. 

**intiimiys**
vrt. intiimi.

**intiimi**
läheinen, likeinen, tuttavallinen; (arkaluonteisen) henkilökohtainen, yksityinen.
https://www.kielitoimistonsanakirja.fi/#/intiimi

**Comment by annamarj** [comment]
> Mielestäni olisi tärkeä pitää nämä erillisinä.

Kielitoimiston sanakirjassa on merkityksenä läheisyyden lisäksi tuo "henkilökohtainen, yksityinen", joka ymmärtääkseni on myös paljon käytetty intimiteetin merkityksenä. Läheisyys ei minusta ole tarpeeksi selkeä eikä tarkka vastine.

**Comment by mirmaid** [comment]
Sanastossa on siis nyt yksityisyys ja läheisyys. Jos niiden lisäksi olisi intiimiys, miten se oikein rajautuisi?

**Comment by annamarj** [comment]
Kiinnostava kysymys!  Yhden mahdollisen tulkinnan mukaan intimiteetti voisi olla ohjausterminä yksityisyydelle, mutta ei läheisyydelle, mutta muitakin tulkintoja tästä löytynee?

**Comment by mariaforsen** [comment]
Aiemmin mainituissa tapauksissa EI ainakaan voi korvata yksityisyydellä. Lähin olisi varmaan läheisyys.

**Comment by YSO-kokous** [comment]
### Päätös
Ei hyväksytä uutta käsitetä. Tarkennetaan kielivastineita
intiimiys KÄYTÄ läheisyys
intimitet ANVÄND närhet

yksityisyys | sv:intimitet  ruotsinkielinen termi vaihtunee muotoon: integritet HT privathet
läheisyys | en:intimacy --- englanninkielinen termi?
