### ISSUE TITLE
kinuski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10192]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kinuski

**Ehdotettu termi ruotsiksi**

kola / tjinusk / ?

**Ehdotettu termi englanniksi**

Russian candy ?

**Tarkoitusta täsmentävä selite**

"Kinuski on maidosta tai kermasta ja sokerista keittämällä valmistettu toffeen kaltainen makea massa, joka tarjoillaan useimmiten jälkiruokien kastikkeena." (https://fi.wikipedia.org/wiki/Kinuski)

**Perustelut ehdotukselle**

Keskeinen osa suomalaista keittiötä; aihe ei kuvailtavissa tarkoin muilla asiasanoilla. Käytetty Melindassa 29 kertaa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013580704 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kinuski](http://finto.fi/yse/fi/page/Y510192)

**Comment by mirmaid** [comment]
29 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. kinuskisås /se ne HT kolasås, tjinuskisås
https://svenska.se/tre/?sok=kinuski&pz=`
Ruotsiksi tärkeä pitää kastikkeena, eli erikseen toffeesta.

**Comment by mirmaid** [comment]
Ehkä tämä voisi olla ihan kinuskikastike? Jos pitää olla ihan varma, ettei käytetä sellaisista makeisista, joissa on valmistusaineena kinuski (toffeet, nekut).

**Comment by YSO-kokous** [comment]
### Päätös
**kinuskikastike** KT kinuski
