### ISSUE TITLE
Memelin alue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10196]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Memelin alue

**Ehdotettu termi ruotsiksi**

Memelområdet

**Ehdotettu termi englanniksi**

Memel Territory

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kyseistä aluetta ei mahdollista kuvailla YSO:n nykyisillä paikkaa kuvaavilla asiasanoilla

**Ehdotettu yläkäsite YSOssa (LT)**

 [Itä-Preussi](http://www.yso.fi/onto/yso/p192068)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Memelin mandaattihallintoalue, Memel (mandaattihallintoalue), Memelland

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/names/no2004067726), [Wikidata](https://www.wikidata.org/wiki/Q161334)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/001960976 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [Memelin alue](http://finto.fi/yse/fi/page/Y510196)

**Comment by mirmaid** [comment]
Olisiko tämä ennemmin ilman yläkäsitettä? https://en.wikipedia.org/wiki/Klaip%C4%97da_Region

**Comment by mirmaid** [comment]
Memelin alue, KT Memelin mandaattihallintoalue, RT Liettua, Itä-Preussi
Memel (kaupunki) KÄ Klaipeda

**Comment by mariaforsen** [comment]
Sv. Memelområdet /ne HT Klaipėdaområdet, Memelterritoriet
Memel (stad) ANV Klaipėda
