### ISSUE TITLE
Mommila (Lammi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10202]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mommila (Lammi)](http://www.yso.fi/onto/yso/p124922)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tarkenteen vaihto Mommila (Lammi) -> Mommila (Hausjärvi)

**Perustelut ehdotukselle**

yläkäsite on Hausjärvi.  Lammi liitettiin Hämeenlinnaan, mutta Lammin eteläosan Mommila Hausjärveen.

**Ehdottajan organisaatio**

Finto

**Comment by ilona-x** [comment]
Aiempi ehdotus samasta: https://github.com/Finto-ehdotus/YSE/issues/9392

> Ehdotettu muutos
> 
> Muutetaanko muotoon Hietoinen (Hausjärvi) tai Mommila-Hietonen (Hausjärvi)?
> Kylä siirtynyt kuntaliitosten myötä Lammilta Hämeenlinnan kautta Hausjärvelle. Hausjärvellä myös toinen Mommila-nimellä tunnettu kylä.

**Comment by mirmaid** [comment]
Sotkuinen tapaus: https://fi.wikipedia.org/wiki/Hietoinen

Paikkatietoalustalla
Hietoinen http://paikkatiedot.fi/so/1000772/10114751 
Mommila http://paikkatiedot.fi/so/1000772/10114488

**Comment by mirmaid** [comment]
Päätermiksi Hietoinen (Hausjärvi), KT Mommila (Lammi), Mommila-Hietoinen

**Comment by ilona-x** [comment]
Asutusnimihakemisto:

Mommila-Hietonen

Kylä (vir.); vrt. Hietonen

Sijaintikunta: 	Hausjärvi
Maakunta: 	Kanta-Häme

Aiempi sijainti: 	Lammi (Kanta-Häme)
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=tietue&id=10484
