### ISSUE TITLE
opiskelijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10209]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[opiskelijat](http://www.yso.fi/onto/yso/p16486)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisäys: korkeakouluopiskelijat (ehkä myös ammattikorkeakouluopiskelijat, yliopisto-opiskelijat)

**Perustelut ehdotukselle**

Tarvitaan mm. 'kohderyhmä'-kentässä.

**Ehdottajan organisaatio**

Kirjastopalvelu /OH

**Comment by mirmaid** [comment]
En ole varma onko tässä ehdotettu ohjaustermejä vai (mitä epäilen) uusi alakäsitteitä. 

https://github.com/Finto-ehdotus/YSE/issues/6522
https://github.com/Finto-ehdotus/YSE/issues/3733

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/opiskelija
https://termipankki.fi/tepa/fi/haku/oppilas

**Comment by YSO-kokous** [comment]
Keskusteltiin pitäisikö kohderyhmät kuvailla mieluummin Metatietosanaston avulla eli pitäisikö käsitteet olla ennemmin siellä. Voidaan tarkistaa esim. sisällönkuvailun asiantuntijaryhmän tai Kumean  kantaa. 

opsikelijat käsitettä käytetty Melindassa yli 14.000 kertaa, joten sisällöllisiä muutoksia tai jakoja siihen ei mielellään tehdä.

### Päätökset
Ei lisätä  ohjaustermejä tässä vaiheessa.   

Selvietätään löytyykö vakiintuneet määritelmät käsitteille oppillaat ja  opiskelijat (esimerkiksi toisen asteen koulutukseen osallistuvista.)   Kts. myös opetus- ja koulutussanasto

**Comment by ilona-x** [comment]
Tässä mainitun Opetus- ja koulutussanaston määritelmät tänne näkyviin.

----

**fi        opiskelija**
sv       studerande n; > student (1) (korkeakouluopiskelija)
en      student

**määritelmä
oppija, joka opiskelee muun kuin esi- tai perusopetuksen piirissä**

huomautus
Opiskelijoita ovat esimerkiksi lukiossa (1), toisen asteen ammatillisessa koulutuksessa, korkeakoulussa (1) ja vapaan sivistystyön piirissä opiskelevat henkilöt.
Myös perusopetuksen piirissä opiskelevia aikuisia kutsutaan opiskelijoiksi.
student: Ruotsin sana student viittaa korkeakouluopiskelijaan, mutta sitä käytetään myös muista opiskelijoista yhdyssanoissa.

Lähde: Opetus- ja koulutussanasto, 2. laitos (OKM, 2021:10) – PDF https://termipankki.fi/tepa/fi/haku/opiskelija


---

**fi        oppilas; ~ koululainen**

**määritelmä
esi- tai perusopetuksessa opiskeleva oppija**

huomautus
Oppilaaksi kutsutaan tyypillisesti esi- tai perusopetuksen piirissä opiskelevaa lasta tai nuorta, mutta oppilas voi olla myös muussa oppilaitoksessa (esimerkiksi musiikkikoulu) tai esimerkiksi yksityisopettajalta opetusta (2) saava henkilö.
Sana koululainen on yleiskielessä oppilaan lähisynonyymi; sillä viitataan peruskoulua (1) tai muuta koulua käyvään oppilaaseen.

Lähde: Opetus- ja koulutussanasto, 2. laitos (OKM, 2021:10) – PDF https://termipankki.fi/tepa/fi/haku/oppilas

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**opiskelija** https://www.kielitoimistonsanakirja.fi/#/opiskelija?searchMode=all

korkeakoulussa, lukiossa, ammattioppilaitoksessa t. opistossa opiskeleva henkilö. 

----
**oppilas**  https://www.kielitoimistonsanakirja.fi/#/oppilas?searchMode=all
1. jssak oppilaitoksessa t. jklta opettajalta opetusta saava henkilö; harjoittelija, ammattioppilas.

2. jklta merkittävältä tiedemieheltä, taiteilijalta tms. oppia t. vaikutteita saanut henkilö.

**Comment by mirmaid** [comment]
Melinda:
oppilaat + lukio 545 kertaa
opiskelijat + lukio 355 kertaa

opiskelijat + ammattikoulut 513 kertaa
oppilaat + ammattikoulut 117 kertaa

opiskelijat + ammatilliset oppilaitokset 509 kertaa
oppilaat + ammatilliset oppilaitokset 109 kertaa

**Comment by mariaforsen** [comment]
Ruotsiksi käytössä:
-elev (person som får undervisning, särsk. om barn el. yngre person /Nationalencyklopedin, yleensä peruskoulussa) =fi. oppilas
-studerande (person som studerar, särsk. efter gymnasieutbildning) =fi. opiskelija
-student (1. person som av­slutat gymnasieutbildning 2. person som studerar vid universitet eller hög­skola) =fi. opiskelija/oppilas/ylioppilas ..Eli ALLFOn studenter tarvitsee ehkä tarkennetta..

**Comment by mirmaid** [comment]
Suomeksi siis opiskelijat-sanaa käytetään korkeakoulujen ja yleensä myös ammattioppilaitosten yhteydessä. Peruskoulua käyvät ovat oppilaita, lukiolaisista käytetään molempia sanoja. 

Kohderyhmän ilmaisemiseen on Metatietosanastossa opiskelutasoa kuvaavat termit. 

Jos nyt otettaisiin YSOon _korkeakouluopiskelijat_, sitä käytettäisiin joko opiskelijat-käsitteen lisäksi tai sen sijasta aineistoissa, joissa käsitellään yliopistojen ja ammattikorkeakoulujen opiskelijoita. _Opiskelijat_-käsitettä käytettäisiin ammattioppilaitosten ja osittain lukion opiskelijoista, ja todennäköisesti melko usein myös korkeakouluopiskelijoista, joko ko. tarkemman termin lisäksi tai sen sijasta (se on enemmän normaalin kielenkäytön sana, "Helsingin yliopistossa on noin 30000 opiskelijaa" ei "noin 30000 korkeakouluopiskelijaa"). Paranisiko tilanne jos se otettaisiin?

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Ylläpitoryhmä ei nähnyt, että korkeakouluopiskelijat-termit ynnä vastaavien tarkempien termien lisääminen hyödyttäisi tiedonhakijaa, koska niitä tuskin käytettäisiin kuvailussa johdonmukaisesti. Opiskelijat-termi on erittäin vakiintunut puhuttaessa myös korkeamman asteen opiskelijoista. Ylioppilaat-termiä ei nähdä suomen kielessä synonyymisena korkeakouluopiskelijalle.
