### ISSUE TITLE
Faron sopimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10203]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Faron sopimus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Faro Convention

**Tarkoitusta täsmentävä selite**

kulttuuriperinnön yhteiskunnallista merkitystä koskeva yleissopimus vuodelta 2005
https://www.museovirasto.fi/fi/tietoa-meista/kansainvalinen-toiminta/euroopan-neuvosto-ja-kulttuuriperinto

**Perustelut ehdotukselle**

Tarvitaan kirjastoaineiston kuvailussa. esiintyy Melindassa 5 tietueessa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kansainväliset sopimukset](http://www.yso.fi/onto/yso/p322)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

 Faron yleissopimus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Euroopan neuvosto](https://www.coe.int/en/web/culture-and-heritage/faro-convention)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/q5v72t/alma9934207978906253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [Faron sopimus](http://finto.fi/yse/fi/page/Y510203)

**Comment by vthuhtal** [comment]
Sopimukset ovat teoksia ja kuuluvat siten bib-kuvailussa 130/630/730 kenttiin. Tätä voisi ehdottaa teosauktoriteettiprojektille esimerkkitapaukseksi?

**Comment by mirmaid** [comment]
YSOssa on toki ennestään runsaasti sopimuksia, mutta joka tapauksessa rajanveto teosauktoriteetteihin pitää ratkaista ennen pitkää.

**Comment by mariaforsen** [comment]
Sv. Farokonventionen

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään uusi käsite johdonmukaisuuden vuoksi.
Päätös mahdollisesta sopimusten siirtämisestä teosauktoriteettisanastoon tehdään kerralla, kun kyseinen sanaston on olemassa.
