### ISSUE TITLE
märkähiilto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10207]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

märkähiilto

**Ehdotettu termi ruotsiksi**

våtkolning

**Ehdotettu termi englanniksi**

wet carbonization

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Julkaisussa erilaisia lämpökemiallisia käsittelyjä, joista torrefiointi on jo sanastossa. Pitäisikö lämpökemiallinen käsittely ottaa näille yläkäsitteeksi?
"-hankkeessa selvitettiin lämpökemiallisten käsittelyjen, torrefioinnin ja märkähiillon (HTC), vaikutusta
lietefosforin välittömään käyttökelpoisuuteen kasvatuskokeilla"

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 HTC-teknologia

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tepa termipankki](https://termipankki.fi/tepa/fi/haku/m%C3%A4rk%C3%A4hiilto)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-326-698-8

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [märkähiilto](http://finto.fi/yse/fi/page/Y510207)

**Comment by ilona-x** [comment]
LCSH: 
**Hydrothermal carbonization** http://id.loc.gov/authorities/subjects/sh2013001120
KT HTC (Hydrothermal carbonization)

Wikipedia:
https://en.wikipedia.org/wiki/Hydrothermal_carbonization
