### ISSUE TITLE
Lahden kartano (Somero)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10201]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Lahden kartano (Somero)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kartanot](http://www.yso.fi/onto/yso/p832)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-7319-05-5

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Lahden kartano (Somero)](http://finto.fi/yse/fi/page/Y510201)

**Comment by mariaforsen** [comment]
Sama kuin Fellmanin kartano? https://fi.wikipedia.org/wiki/Fellmanin_kartano
Siinä tapauksessa on jo sanastossa https://finto.fi/yso/en/page/p38093?clang=sv
Sv. Lahtis gård

**Comment by fantsby-m** [comment]
Ei ole sama kuin YSOssa oleva Fellmanin kartano, joka on Lahdessa. Tämä on Somerolla.

**Comment by ilona-x** [comment]
Tässä vielä linkki ehdotuksessa mainittun teoksen tietoihin:
http://amanita.fi/amanita/tuote/leeni-tiirakari-lahden-kartano/

**Comment by mariaforsen** [comment]
Sv. Lahtis gård (Somero)
Lahtis gård > Lahtis gård (Lahtis)
