### ISSUE TITLE
anonyymi rekrytointi

### ISSUE THREAD

**Issue by vayrynenleena** [Finto-ehdotus/YSE#10219]
Ehdotus **rekrytointi** -asiasanan alakäsitteeksi (http://www.yso.fi/onto/yso/p478)

Anonyymi rekrytointi -termiä on käsitelty mm. Monimuotoisuusbarometri 2020 : Fokuksessa rekrytointikäytännöt ja monikulttuurisuus -julkaisussa (https://urn.fi/URN:ISBN:9789522619471) luvussa 6.2 (s. 65-67) ja Kuntarekryn sivulla: https://www.kuntarekry.fi/fi/anonyymi-tyonhaku/.

**Comment by mariaforsen** [comment]
Sv. anonym rekrytering
https://www.kela.fi/web/sv/anonym-rekrytering
