### ISSUE TITLE
zarzuelat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10218]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[zarzuelat](http://www.yso.fi/onto/yso/p29802)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tarvitaan myös SLM termi

**Perustelut ehdotukselle**

on nuotteja, äänitteitä ja konserttivideoita, joiden kuvailussa genre-terminä tarvittaisiin  zarzuelat.

**Ehdottajan organisaatio**

Jyväskylän kaupunginkirjasto

**Comment by jarmosaarikko** [comment]
kts. myös #10329

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT oopperat
