### ISSUE TITLE
katsaukset [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10217]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

katsaukset [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

"Katsaus [- -] (lyhyehkö) yleisesitys jstak."  (https://www.kielitoimistonsanakirja.fi/katsaus)

**Perustelut ehdotukselle**

Tarvitaan katsausten kuvailuun

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Deutsches und europäisches Bank- und Kapitalmarkrecht

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
LT-suhteeksi _**ei-fiktiivinen aineisto**_ ja RT-suhteisiksi sopivia, ks. https://github.com/Finto-ehdotus/YSE/issues/8737.

**Comment by ilona-x** [comment]
Siirretään käsiteltäväksi samassa yhteysessä kuin issuen https://github.com/Finto-ehdotus/YSE/issues/8737 termit

**Comment by AuHo22** [comment]
Tämän löysin Melindasta 9783662528044 
xxxviii, 3027 sivua -> onko kuitenkaan katsaus vai jotain muuta? Markkinoinnissa Das ideale Handwerkszeug für den Praktiker 
Auf die Bedürfnisse der Praxis ausgerichtet, erläutert das Werk unter Aufarbeitung der neuesten Rechtsentwicklungen systematisch das gesamte Bankrecht in Deutschland.

**Comment by mariaforsen** [comment]
Sv. översikter 
https://termipankki.fi/tepa/fi/haku/katsaus
https://www.sanakirja.fi/custom/en-sv-fi/katsaus

**Comment by mirmaid** [comment]
Ehdotettu KÄ raportit.

**Comment by mirmaid** [comment]
Toivottiin lisää esimerkkejä aineistoista, joissa tarvittaisiin _katsaukset_-genreä.

**Comment by mirmaid** [comment]
Jos näitä esimerkkejä ei tähän hätään tule enempää, jätetäänkö termiehdotukseksi ja palataan jos jatkossa tarvetta ilmenee?

**Comment by mirmaid** [comment]
Jaakko varmistaa vielä, tuleeko esimerkkejä.

**Comment by jtuohini** [comment]
https://melinda.kansalliskirjasto.fi/byid/018686271, https://melinda.kansalliskirjasto.fi/byid/018284204, https://melinda.kansalliskirjasto.fi/byid/016796445 jne. Ja aiemmin tässä ketjussa mainittu yli 3 000-sivuinen oikeustieteellinen kirja koostuu lyhyistä maakohtaisista katsauksista. Useilla tutkimuslaitoksilla on "Katsauksia"-tyyppisiä julkaisusarjoja, joihin pelkkä **ei-fiktiiviset aineistot** olisi turhan yleinen ja jotka eivät kuitenkaan ole esimerkiksi raportteja tai tilastoja.

**Comment by mirmaid** [comment]
Hyväksytään katsaukset KT vuosikatsaukset, tilannekatsaukset, tieteelliset katsaukset /SLM.
RT raportit
