### ISSUE TITLE
triangulaatio (tutkimus)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10212]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[triangulaatio (tutkimus)](http://www.yso.fi/onto/yso/p23071)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

monimenetelmäisyys tai monimenetelmällisyys

**Perustelut ehdotukselle**

triangulaatio ei ole enää terminä käytössä. se on myös ikävän vierasperäinen ja keinotekoinen sana 

**Ehdottajan organisaatio**

Kela

**Comment by mariaforsen** [comment]
On eri asia. Käsitelty jo aiemmin: https://github.com/Finto-ehdotus/YSE/issues/8424 ja https://github.com/Finto-ehdotus/YSE/issues/5850 Olisi kuitenkin varmaan mahdollista hyväksyä monimenetelmällisyys tms. erillisenä käsitteenä.

**Comment by mirmaid** [comment]
Tämä on todella hankala, koska monimenetelmätutkimus (tai monimenetelmäisyys) määritellään eri tavalla kuin triangulaatio (johon kuuluu myös menetelmätriangulaatio), mutta selvästi sitä käytetään osittain (ehkä alasta tai organisaatiosta riippuen) myös päällekkäin. Kun molemmissa on kyse tutkimuksesta, erottelu tarkentein on vaikeaa ja määritelmä ei välttämättä ohjaa käyttöä riittävästi. 

Jos tämä otetaan erikseen, vaatisi varmasti ainakin määritelmän ja ohjauksen monimenetelmäisyys/monimenetelmätutkimus (triangulaatio/menetelmätriangulaatio) KÄ triangulaatio. Vähän kyllä epäilen, että käyttö olisi silti osin epäjohdonmukaista, jos esim. ehdottajan organisaatiossa katsotaan, että nämä tarkoittavat samaa.

**Comment by AuHo22** [comment]
Tässä vielä löydettyä (ei ihan uutta)  jaottelua viittauksineen: https://www.mv.helsinki.fi/home/jmykkane/tutkielma/Tutkimusmenetelmat.html
_Edelleen validiutta voidaan parantaa hyödyntämällä tutkimuskohteeseen mahdollisuuksien mukaan useampaa näkökulmaa, mitä kutsutaan yleisesti triangulaatioksi. Denzin (1970, lainattu Hirsjärvi ym. 2003, 215)) jakaa triangulaation neljään eri tyyppiin:
-tutkijatriangulaatio, jolloin samaan tutkimukseen osallistuuu useita tutkijoita sen eri vaiheissa
-teoreettinen triangulaatio, jolloin tutkimuksen kohteena olevaa ilmiötä tarkastellaan eri teorioiden näkökulmasta
-aineistotriangulaatio, jossa samaa ongelmaa yritetään ratkaista erilaisia tutkimusaineistoja analysoimalla
-metodologinen (tai metodinen) triangulaatio, jolloin samaan aineistoon käytetään useita tutkimusmenetelmiä. Erityisesti tässä merkityksessä triangulaatio tulee lähelle tutkimusmenetelmällistä "mixing methods" -otetta._

Itse voisin katsoa triangulaatio (tutkimus) sekä ehdotettua monimenetelmäisyys -termien suhdetta LT/ST suhteena, triangulaatio sisältää muitakin tarkastelukulmia kuin vain metodologisen triangulaation. Seuraavassa aika paljon erilaista triangulaatio-käsitteeseen liittyvää analyysia myös, jossa otettiin metodologisen triangulaation, so. monimenetelmäisyyden, lisäksi muitakin triangulaation muotoja huomioon, mm. moninäkökulmaisuus (laajojen lähestymistapojen/teorioiden näkökulmat eli teoreettinen triangulaatio) tai kahden tutkijan käyttö tutkimuksessa (tutkijatriangulaatio). S. 30-> 

https://www.theseus.fi/bitstream/handle/10024/125189/Ikaheimo_Henriikka%20Karikumpu_Henna.pdf..pdf;jsessionid=A55263369EB354D9492B402C19017A8E?sequence=1

**Comment by mirmaid** [comment]
^ Helpottaisi kyllä asiaa, jos voidaan ajatella että monimenetelmäisyys/monimenetelmätutkimus = menetelmätriangulaatio. Usein tunnutaan mixed methods research kääntävän monimenetelmätutkimukseksi, jolloin määritelmä on (ehkä?) suppeampi. Mutta kyllä näitä myös selvästi käytetään ristiin.

**Comment by AuHo22** [comment]
LT/ST-suhteen lisäksi ohjaus menetelmätriangulaatio KÄYTÄ monimenetelmäisyys/monimenetelmätutkimus

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään uusi termi _monimenetelmätutkimus_, tälle sekä käsitteelle _triangulaatio_ ohjaustermiksi _menetelmätriangulaatio_. Tutkitaan vielä ruotsin osalta.

**Comment by mariaforsen** [comment]
Tuleeko mixed method -tutkimus ohjaustermiksi? Ja eng. linkki tähän: https://id.loc.gov/authorities/subjects/sh2010001158.html ?

Ks. esim. https://peda.net/jyu/okl/ryhmat/multilete-2018/multilete/ktkp-opinnot/ktkp040/sj2md:file/download/850bb93a3a0a486ebdc23c76828ea2a892c88702/Salminen_mixed_methods_2014.pdf

https://www.utu.fi/fi/yliopisto/turun-kauppakorkeakoulu/markkinointi/tutkimus

Sv. flermetodsforskning HT flermetodforskning, mixed method(s)-forskning
https://termipankki.fi/tepa/fi/haku/mixed%20methods
https://www.vr.se/download/18.2412c5311624176023d25adb/1556010447479/Forskningsbasering-laerarutbildningen-SKOLFORSK_VR_2015.pdf
https://www.skolfi.se/wp-content/uploads/2020/11/Hur-ska-man-veta-vad-forskningen-s%C3%A4ger.pdf
https://www.adlibris.com/fi/kirja/foretagsekonomiska-forskningsmetoder-9789147112074
https://www.diva-portal.org/smash/get/diva2:1309720/FULLTEXT01.pdf
https://bibkat.hkr.se/cgi-bin/koha/opac-detail.pl?biblionumber=3950
