### ISSUE TITLE
tanssiteokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10213]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tanssiteokset](http://www.yso.fi/onto/yso/p10217)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "koreografiat", "koreografiset teokset" ja "tanssikompositiot"

**Perustelut ehdotukselle**

Ks. esim. https://fi.wikipedia.org/wiki/Koreografia, https://www.kielitoimistonsanakirja.fi/koreografia (jälkimmäisessä merkityksessä) ja https://www.teatteritanssi.fi/2013/03/mita-on-koreografia-mika-on-tanssia/

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT koreografiska verk, danskompositioner?

**Comment by AuHo22** [comment]
Itse en laittaisi välttämättä yhtäläisyysmerkkiä koreografian ja tanssiteoksen välille, koskapa jälkimmäinen voi toteutua tanssiesityksenä mm. näyttämöllisessä tilassa, koreografia puolestaan voi olla lähellä ns. tanssinotaatiota erilaisissa muodoissaan kuten myös viitatussa Wikipedian artikkelissa sanotaan. Sama voi sitten koskea muitakin ohjaustermejä. 

Vrt. myös baletit (teokset) määritelmä YSOssa: "Tanssitaiteeseen kuuluva taideteos kokonaisuutena (musiikki, tanssi, koreografia)."

https://termipankki.fi/tepa/fi/haku/koreografia

**Comment by mirmaid** [comment]
_Koreografia_ on sanastossa myös.

**Comment by YSO-kokous** [comment]
### Päätös
Tarkistetaan vvielä yhtäläisyyttä. Siirretään seuraavaan kokoukseen.

**Comment by mirmaid** [comment]
Itse en ainakaan oikein pääse tässä eteenpäin, olisiko kenelläkään ehdottaa tahoa, jolta voisi suoraan kysyä?

**Comment by ilona-x** [comment]
Voisiko nämä ohjaustermit vain jättää lisäämättä tai mahdollisesti lisätä tarkenteellisina esimerkiksi koreografiat (tanssiteokset) KÄYTÄ tanssiteokset? 🤔

**Comment by YSO-kokous** [comment]
**Päätös**

Ei lisätä ohjaustermejä.
