### ISSUE TITLE
terveysvaikutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10210]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[terveysvaikutukset](http://www.yso.fi/onto/yso/p15449)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan ohjaustermi terveysvaarat

**Perustelut ehdotukselle**

Terveysvaikutukset voivat olla positiivisia ja terveysriskit on sanastossa erikseen (ohjausterminä terveysvaarat)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Poisto ok.
