### ISSUE TITLE
perhevapaakorvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10223]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

perhevapaakorvaus

**Ehdotettu termi ruotsiksi**

familjeledighetsersättning

**Ehdotettu termi englanniksi**

employer compensation for family leave costs

**Tarkoitusta täsmentävä selite**

Kelan terminologinen sanasto, 6. laitos
  	
suomi:
  	
perhevapaakorvaus
  
  	
Määritelmä:
  	
naispuolisen työtekijän työnantajalle maksettava kertakorvaus vanhemmuudesta aiheutuvista perhevapaakustannuksista

**Perustelut ehdotukselle**

Kyse on Kelan etuudesta ja se on virallinen osa sosiaaliturvaa 

**Ehdotettu yläkäsite YSOssa (LT)**

 [perhevapaat](http://www.yso.fi/onto/yso/p2449)

**Ehdotetut temaattiset ryhmät**

 [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/2257/discover?rpp=20&sort_by=score&order=DESC&query=perhevapaakorvaus&context=%2Fhandle%2F10138%2F2257%2Fdiscover 

**Ehdottajan organisaatio**

Kela
**Termiehdotus Fintossa:** [perhevapaakorvaus](http://finto.fi/yse/fi/page/Y510223)

**Comment by mirmaid** [comment]
Tupla.
