### ISSUE TITLE
Ukrainan kriisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10225]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ukrainan kriisi](http://www.yso.fi/onto/yso/p38096)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Venäjän-Ukrainan sota

**Perustelut ehdotukselle**

Nykyinen ei ole ajantasainen. Termin tulisi tuoda näkyväksi Venäjän valtion osuus. Nykyistä ei oikein voi käyttää nykydokumentoinnin ainestojen luetteloinnissa.

**Ehdottajan organisaatio**

HAnnu Häkkinen / Museovirasto

**Comment by jarmosaarikko** [comment]
Voisi mieluummin olla erillinen käsite  "**Venäjän-Ukrainan sota**"   "rysk-ukrainska kriget"  "Russo-Ukrainian War"
OT "Ukrainan sota (2022)"  "ukrainska kriget (2022)",  "Ukrainian war (2022)"
LT "sodat"    
RT "Ukrainan kriisi"

vrt.  YSO käsitteet:
- [Venäjän-Japanin sota](https://finto.fi/yso/fi/page/p16987), [rysk-japanska kriget](https://finto.fi/yso/fi/page/p16987?clang=sv), [Russo-Japanese War](https://finto.fi/yso/fi/page/p16987?clang=en)
- [Russo-Swedish War 1495–97](https://finto.fi/yso/fi/page/p26974?clang=en)
- [Russo-Swedish War (1570-1595)](https://finto.fi/yso/fi/page/p11530?clang=en)
- [Russo-Swedish War (1741-1743)](https://finto.fi/yso/fi/page/p17768?clang=en)
- [Russo-Swedish War (1788-1790)](https://finto.fi/yso/fi/page/p5375?clang=en)
- [Russo-Turkish War (1877-1878)](https://finto.fi/yso/fi/page/p17685?clang=en)
- [Soviet–Afghan War (1979-1989)](https://finto.fi/yso/fi/page/p16274?clang=en)
- etc.

**Comment by vthuhtal** [comment]
Jotenkin pitäisi myös huomioida Krimin valtaus 2014 ja Itä-Ukrainan "kansantasavallat"

**Comment by mirmaid** [comment]
Ainakin eng. wikipedia Russo-Ukrainian war alkaa v. 2014. Erikseen 2022 Russian invasion of Ukraine, suom. Venäjän hyökkäys Ukrainaan 2022. Mediassa usein "Venäjän hyökkäyssota Ukrainassa".

https://um.fi/venajan-hyokkays-ukrainaan

YSOssa ei ennestään ole yksittäisiä sotia tai sotatoimia hyökkäys(sota)-termillä. SAOssa näyttää kuitenkin olevan 
Ryska invasionen av Ukraina 2022
Konflikten i östra Ukraina 2014-

Tältä pohjalta voisi kenties ottaa muodossa _Venäjän hyökkäys Ukrainaan 2022_ ja _Ukrainan kriisi_ voisi jäädä muuttamatta, tosin en tiedä olisiko tuo vuositarkenne hyvä lisätä? Ukrainan sota voisi ohjata molempiin?

**Comment by LeKorsu** [comment]
Olen samaa mieltä ehdottajan kanssa, että Ukrainan kriisi ei sovi nykyhetkeen eikä myöskään tulevaisuutta ajatellen. Sodalla sitä tullaan tulevaisuudessa hakemaan ja siksi kannatan selkeää sota-termiä tuon Venäjän hyökkäys Ukrainaan 2022 sijasta. Onko se sitten "Venäjän-Ukrainan sota (2022-?)" vai "Ukrainan sota (2022-?)", vrt. Afganistanin sota (jossa Neuvostoliittoa ei ole mainittu asiasanassa osapuolena), siitä minulla ei ole vielä vahvaa kantaa vaan käyn mielelläni keskustelua asiasta.

Voidaanko Ukrainan kriisi tarkentaa vuosiin 2014-2021, jolloin Krimin valtaus ja Itä-Ukrainan "kansantasavallat" saataisiin mukaan tähän

**Comment by YSO-kokous** [comment]
### Päätökset
vaihdetaan päätermi 
**Ukrainan kriisi 2014-**   
LT jäätyneet konfliktit
KT Ukrainan sota
KT Venäjän-Ukrainan sota
KT Krimin miehitys

Lisätään käsite 
**Venäjän hyökkäys Ukrainaan 2022**
LT sodat
KT Ukrainan sota
KT Venäjän-Ukrainan sota

**Comment by mariaforsen** [comment]
Sv. 
-Ukrainakrisen > konflikten i östra Ukraina 2014- HT Ukrainakrisen 2014-, konflikten i Ukraina 2014-, kriget i Östra Ukraina 2014-, proryska upproret i Ukraina 2014-, rysk-ukrainska konflikten 2014-, ukrainsk-ryska konflikten 2014-
-ryska invasionen av Ukraina 2022 HT kriget i Ukraina 2022, Rysslands invasion av Ukraina 2022

se https://id.kb.se/find?q=kriget%20i%20%C3%B6str%2a
