### ISSUE TITLE
lastenkirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10222]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lastenkirjallisuus](http://www.yso.fi/onto/yso/p4742)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM: Uusi ohjaustermi lastenromaanit?

**Perustelut ehdotukselle**

Vastaava ohjaus on jo: nuorisoromaanit KÄYTÄ nuortenkirjallisuus
Ks. Melinda, esim. Nyt ratsaille, Niklas / Merja Jalo ; kuvittanut Milla Koivunen. Onko todella romaani?

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Hyväksytty/YSO.

**Comment by mirmaid** [comment]
Lastenromaanit, lisäksi nuortenromaanit SLM.

**Comment by mariaforsen** [comment]
Sv. -barnromaner HT romaner för barn 
-ungdomsromaner HT romaner för ungdomar
