### ISSUE TITLE
k-pop

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10221]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

k-pop

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

k-pop

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

K-pop on tunnettu ja spesifi ilmiö, josta on kirjoitettu jo vuosia ja julkaistu monta teosta. Populaarimusiikki-asiasana on hyvin geneerinen käsite, joka ei havainnollista tätä ilmiötä. Voisi harkita myös SLM:ään.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/K-pop), [LCSH](http://id.loc.gov/authorities/subjects/sh2020006575)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sanni Ylimartimo: Pimeässä hohtavat tähdet.

**Ehdottajan organisaatio**

Kirjastopalvelu / PA

**Comment by ilona-x** [comment]
aiempi ehdotus https://github.com/Finto-ehdotus/YSE/issues/9770
