### ISSUE TITLE
inkerinsuomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10229]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

inkerinsuomi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kuvausta mm.: https://jyx.jyu.fi/bitstream/handle/123456789/41516/miten-suomea-puhutaan-inkerinmaalla.pdf?sequence=1&isAllowed=y

**Perustelut ehdotukselle**

Ks.  YKL 88.25 Hakusanat

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Olisi ollut tarvetta esim. Šulkkuni sanaine : kirjoituksia karjalasta ja vähemmistökielistä

**Ehdottajan organisaatio**

Suomen kirjastopalvelu
**Termiehdotus Fintossa:** [inkerinsuomi](http://finto.fi/yse/fi/page/Y510229)

**Comment by mirmaid** [comment]
Eli tulisiko tämä YSOssa kaakkoismurteiden alle?

**Comment by mariaforsen** [comment]
Mikä tämän kielikoodi on?

**Comment by AuHo22** [comment]
ingermanlandsfinska? kielikoodi fin

https://sv.wikipedia.org/wiki/Ingermanlandsfinska

**Comment by nikopartanen** [comment]
Kaakkoismurteiden alla on varmasti hyvä sijainti. Tuleeko jokin suhde käsitteeseen inkeriläiset?

https://finto.fi/yso/fi/page/p9532

**Comment by mariaforsen** [comment]
Sv. ingermanlandsfinska HT ingermanländsk finska
