### ISSUE TITLE
URN-tunnus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10235]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

URN-tunnus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Uniform Resource Name

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [URN-tunnus](http://finto.fi/yse/fi/page/Y510235)

**Comment by mirmaid** [comment]
YK pysyvät tunnisteet

**Comment by mariaforsen** [comment]
Sv. URN (identifikator) HT URN, URN-identifikator, URN-nummer, uniform resource name 
https://www.digime.fi/sv/interoperabilitet/identifierare/
https://www.kiwi.fi/display/URN/Anvisningar+till+URN-kunder
https://www.rikstermbanken.se/termposter/1943/URN
https://www.umu.se/bibliotek/publicera/vetenskaplig-publicering/publikationer-pid/
https://id.kb.se/vocab/URN
