### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10233]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[DOI](http://www.yso.fi/onto/yso/p27420)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermi muotoon DOI-tunnus

**Perustelut ehdotukselle**

yhteismitallisuus ISO 5127:n kanssa

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. DOI-nummer?
