### ISSUE TITLE
Handle-tunnus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10236]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Handle-tunnus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Handle

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Handle-tunnus](http://finto.fi/yse/fi/page/Y510236)

**Comment by mirmaid** [comment]
YK pysyvät tunnisteet

**Comment by mariaforsen** [comment]
Sv. Handle (identifikator) HT Handle
https://docplayer.se/33716893-Nationellt-format-for-publiceringsdatabaser-lokala-register-over-akademisk-publicering.html
https://termipankki.fi/tepa/fi/haku/tunnus
https://termipankki.fi/tepa/en/search/identifikator
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_db68be0448b4b3d6b70ee121a58b8f6e&list_id=1&keyword=tunnus&word=tunnus
https://www.sanakirja.fi/custom/en-sv-fi/%20tunnus
https://www.digime.fi/sv/interoperabilitet/identifierare/
https://id.kb.se/vocab/Hdl
