### ISSUE TITLE
säilöönotto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10232]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[säilöönotto](http://www.yso.fi/onto/yso/p10752)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan

**Perustelut ehdotukselle**

Turvapaikanhakijan säilöönotto ja päihtyneen säilöönotto -merkityksiä on vaikea kääntää yksiselitteisesti yhdellä termillä, eikä tunnu muutenkaan kovin perustellulta käsitellä niitä yhtenä käsitteenä.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi nykyinen tilanne ok (finlex, https://migri.fi/sv/forvarstagande)

**Comment by mirmaid** [comment]
Ongelma siis ennen kaikkea englanniksi, koska mahdolliset käännösvastineet sekoittuvat myös pidättämiseen ja jälki-istuntoon. Tai sitten pitäisi rakentaa jokin "detention of asylum seekers or intoxicated persons" -käännösvastine...

**Comment by ilona-x** [comment]
YSOssa säilöönotto englanniksi nyt: 
[taking into police custody](https://finto.fi/yso/fi/page/p10752?clang=en)

ja ohjaustermeinä:
    detention (asylum seekers)
    detention (intoxicated persons)
    detention (police custody)
    taking into custody (police custody)

**Comment by mirmaid** [comment]
Tuo _taking into police custody_ on merkitykseltään aika epäselvä.

**Comment by ilona-x** [comment]
Eli haluttaisiinko englanniksi 
detention (asylum seekers)
detention (intoxicated persons) 
vai pitääkö näitä tarkentaa vielä jotenkin muuten?

Jakamisen vaatimien mahdollisten tarkenteiden keksiminen tuntuu hankalalta. Ja mitkä kaikki merkitykset pitäisi ottaa erikseen:
säilöönotto (turvapaikanhakijat?, ulkomaalaiset?, pakolaiset?)
säilöönotto (päihtyneet?, mielenosoittajat?)

Lisäksi näköjään myös eri maiden välillä luovutettavia rikoksentekijöitä voidaan ottaa säilöön:
Laki rikoksen johdosta tapahtuvasta luovuttamisesta Suomen ja muiden Pohjoismaiden välillä
https://www.finlex.fi/fi/laki/ajantasa/2007/20071383?search%5Btype%5D=pika&search%5Bpika%5D=s%C3%A4il%C3%B6%C3%B6n%20ottaminen

OIKOssa näkyy olevan vain yksi säilöönotto-termi:
säilöönotto http://www.yso.fi/onto/oiko/p216

Kielitoimiston sanakirja:
säilöönotto https://www.kielitoimistonsanakirja.fi/#/s%C3%A4il%C3%B6%C3%B6notto?searchMode=all
oik. määräsyistä tapahtuva henkilön väliaikainen otto poliisin huostaan.
Päihtyneen säilöönotto.
Ulkomaalaislakiin perustuvat säilöönotot.

Voisiko tarkenteena olla laki, johon säilöönotto perustuu? 🤔 
säilöönotto (poliisilain perusteella)
säilöönotto (ulkomaalaislain perusteella)

Toki sitten tuo rikoksentekijöiden säilöönottoa koskeva laki onkin sitten hankalampi. Ja pitäisi varmistua, voidaanko tehdä säilöönottoja myös joidenkin muiden lakien perusteella. Näköjään ainakin järjestyksenvalvojilla on joissain tilanteissa säilöönotto-oikeus https://poliisi.fi/sailoonottoilmoitus, joka perustuu Lakiin yksityisistä turvallisuuspalveluista. Eli ei taida laki-tarkenteetkaan olla kovin toimiva vaihtoehto.

Helpointa olisi, jos jatkossakin riittäisi vain yksi säilöönotto.

**Comment by mirmaid** [comment]
^ Varmaan näin voidaan jatkaa, vaikka englanninkielinen termimuoto sitten jää epäselväksi. Nykyistä parempi ehkä olisi kuitenkin _detention_ jollain tarkenteella. Tai non-criminal detention 🤔

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutoksia suomeksi.
