### ISSUE TITLE
ARK-tunnus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10234]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ARK-tunnus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

  Archival Resource Key

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ARK-tunnus](http://finto.fi/yse/fi/page/Y510234)

**Comment by mirmaid** [comment]
YK pysyvät tunnisteet

**Comment by mariaforsen** [comment]
Sv. ARK (identifikator) HT archival resource key, ARK
https://www.ifla.org/references/best-practice-for-national-bibliographic-agencies-in-a-digital-age/resource-description-and-standards/identifiers/persistent-identifiers/archival-resource-key-ark/
https://termipankki.fi/tepa/fi/haku/tunnus
https://termipankki.fi/tepa/en/search/identifikator
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_db68be0448b4b3d6b70ee121a58b8f6e&list_id=1&keyword=tunnus&word=tunnus
https://www.sanakirja.fi/custom/en-sv-fi/%20tunnus
https://www.digime.fi/sv/interoperabilitet/identifierare/
