### ISSUE TITLE
ROR-tunnus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10237]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ROR-tunnus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

 [tunnukset](http://www.yso.fi/onto/yso/p2014)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ROR-tunnus](http://finto.fi/yse/fi/page/Y510237)

**Comment by mirmaid** [comment]
https://ror.org/

**Comment by mariaforsen** [comment]
Sv. ROR (identifikator) HT ROR, research organization registry
https://termipankki.fi/tepa/fi/haku/tunnus
https://termipankki.fi/tepa/en/search/identifikator
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_db68be0448b4b3d6b70ee121a58b8f6e&list_id=1&keyword=tunnus&word=tunnus
https://www.sanakirja.fi/custom/en-sv-fi/%20tunnus
https://www.digime.fi/sv/interoperabilitet/identifierare/
