### ISSUE TITLE
assemblaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10231]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[assemblaasit](http://www.yso.fi/onto/yso/p779)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "esinekoosteet" (tarpeen tullen kera sulkutarkenteen)

**Perustelut ehdotukselle**

"Assemblaasi [- -] eli esinekooste on taiteessa kollaasin kolmiulotteinen vastine, useista esineistä koottu taideteos." (https://fi.wikipedia.org/wiki/Assemblaasi)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja toiseksi KT-muodoksi _esinesommitelmat_, jota sanaa on assemblaaseista käytetty mm. _Pinx.: maalaustaide Suomessa_ -teoksessa.

**Comment by AuHo22** [comment]
Kannatan sulkutarkenteen kanssa

**Comment by mirmaid** [comment]
Onko tarkenne tarpeen? Mitä muuta esinekooste voi olla (tai rajautuuko assemblaasi jotenkin tarkemmin)?

**Comment by AuHo22** [comment]
Käytetään näköjään pääsääntöisesti taidemaailman terminä, mutta esim. muitakin esinekoosteita: https://evl.fi/kasvuakatsomuksesta/tutustu-ja-toteuta/yhdessa-maailmassa/viisi-maailmanuskontoa

**Comment by YSO-kokous** [comment]
### Päätös
assemblaasit
KT esinekoosteet (taideteokset)
KT esinesommitelmat (taideteokset)
