### ISSUE TITLE
maanpeitekasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10245]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maanpeitekasvit](http://www.yso.fi/onto/yso/p17175)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi peitekasvit ellei peitekasveista tehdä omaa käsitettä.

**Perustelut ehdotukselle**

Julkaisussa http://urn.fi/URN:ISBN:978-952-326-324-6 puhutaan peitekasveista rikkakasvien hallinnan yhteydessä. Maanpeitekasvien käyttötarkoitus laajempi, mutta samassa wikipedian artikelissa viitataan myös samaan tarkoitukseen: "Aikaisin keväällä maan verhoavat peitekasvit estävät rikkakasvien siemeniä itämästä paljaaseen multaan."

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ohjaustermiksi?
