### ISSUE TITLE
tiedustelumenetelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10240]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tiedustelumenetelmät

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tiedustelumenetelmä-asiasana auttaisi hahmottamaan, että tiedustelua tarkastellaan nimenomaan menetelmien näkökulmasta. Alun perin mietin käsitettä tietoliikennetiedustelu, joka on yksi tiedustelumenetelmistä. Toisaalta se voi olla liian spesifi, kun muitakaan tiedustelumenetelmiä ei ole YSO:ssa. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541), [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575), [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. tämä tuli tänään, mutta olen aiemminkin ajatellut käsitteen tarpeellisuutta: https://ojs.ub.gu.se/index.php/sjpa/article/view/4969

**Ehdottajan organisaatio**

Poliisiammattikorkeakoulu
**Termiehdotus Fintossa:** [tiedustelumenetelmät](http://finto.fi/yse/fi/page/Y510240)

**Comment by mariaforsen** [comment]
Tiedustelu on monimerkityksinen termi, tarvitaan tarkennusta. Onko kyseessä sama merkitys kuin tässä: https://www.finlex.fi/fi/laki/ajantasa/2019/20190590 vai muutakin?

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Verkkovalvonta ->
tiedustelu + varkkovalvonta
TAI
tietoliikennetiedustelu
https://supo.fi/tiedonhankinta 
Supon sivuilla mainittuja tiedustelumenetelmiä kyllä löytyy jo muitakin YSOsta.

**Comment by mirmaid** [comment]
^ On ja niiden kanssa on jo nyt selvitelty, kun on vaikea tietää mitä eroa on eri menetelmillä. 

Tietoliikennetiedutelu (siviilitiedustelu) lakitekstissä: Suomen rajan viestintäverkossa ylittävään tietoliikenteeseen kohdistuvaa, tietoliikenteen automatisoituun erotteluun perustuvaa teknistä tiedonhankintaa sekä hankitun tiedon käsittelyä

Telekuuntelu: Telekuuntelulla tarkoitetaan sähköisen viestinnän palveluista annetun lain [(917/2014) 3 §:n](https://www.finlex.fi/fi/laki/ajantasa/2014/20140917#P3) 43 kohdassa tarkoitetun yleisen viestintäverkon tai siihen liitetyn viestintäverkon kautta teleosoitteeseen tai telepäätelaitteeseen vastaanotettavan taikka siitä lähetetyn viestin kuuntelua, tallentamista ja muuta käsittelyä viestin sisällön ja siihen liittyvien tämän luvun 8 §:ssä tarkoitettujen tunnistamistietojen selvittämiseksi.

Televalvonta: Televalvonnalla tarkoitetaan tunnistamistietojen hankkimista viestistä, joka on lähetetty 5 §:ssä tarkoitettuun viestintäverkkoon kytketystä teleosoitteesta tai telepäätelaitteesta taikka vastaanotettu tällaiseen osoitteeseen tai laitteeseen, sekä teleosoitteen tai telepäätelaitteen sijaintitiedon hankkimista taikka osoitteen tai laitteen käytön tilapäistä estämistä.

**Comment by mirmaid** [comment]
Tietoliikennetiedustelu ei Melindassa, tiedustelumenetelmät käytetty 2 kertaa. _Tiedustelu & menetelmät_ yhdistelmää joitakia kertoja.

**Comment by ilona-x** [comment]
YLEllä tietoliikennetiedustelu
https://yle.fi/aihe/t/18-250105

**Comment by YSO-kokous** [comment]
### Päätös
Ei lisätä: tiedustelumenetelmät
Lisätään uusi käsite:  **tietoliikennetiedustelu**
Käsite kattaa suomeksi sekä siviili- että sotilastietoliikennetiedustelun.
Tarkistetaan vielä lainsäädännöstä rajaukset.

**Comment by fantsby-m** [comment]
Ks:
[Laki sotilastisedustelusta](https://www.finlex.fi/fi/laki/ajantasa/2019/20190590)
[Laki tietoliikennetiedustelusta siviilitiedustelussa ](https://www.finlex.fi/fi/laki/alkup/2019/20190582)
Molemmissa sama määritelmä tietoliikennetiedustelulle.

**Comment by mariaforsen** [comment]
Sv. underrättelseinhämtning avseende datatrafik HT underrättelseinhämtning som avser datatrafik
/finlex
https://www.sanakirja.fi/custom/en-sv-fi/underr%C3%A4ttelseinh%C3%A4mtning%20avseende%20datatrafik
