### ISSUE TITLE
fulltextdatabaser

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10246]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[fulltextdatabaser](http://www.yso.fi/onto/yso/p19426)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jag föreslår att termen "fulltextdatabaser" också tas med i FGF.

**Perustelut ehdotukselle**

1. Jag vill använda fulltextdatabaser för att genre-klassa databaser som innehåller fulltexter (helt eller delvis) i 655-fältet. T.ex. Ebscos Academic Search Complete https://abo.finna.fi/Record/abo_electronic_aa.9912910273405972

2. Jag uppfattar termen fulltextdatabaser som ett slags begreppsligt motsatspar till termen referensdatabaser, som redan finns i FGF, vilket bidrar till att termen fulltextdatabaser också kan anses höra hemma i FGF.  På mitt universitet är det vanligt att dela upp databaser i antingen a) referensdatabaser eller b) fulltextdatabaser. Förvisso är många databaser både och, men då vore min mening att upprepa 655-fältet men bägge termer.

**Ehdottajan organisaatio**

Åbo Akademis bibliotek

**Comment by mariaforsen** [comment]
Mysö SAOgf-sanastossa: https://id.kb.se/term/saogf/Fulltextdatabaser

Tieteen termipankissa kokotekstitietokanta : https://tieteentermipankki.fi/wiki/Nimitys:kokotekstitietokanta

YSOssa vastine tekstitietokannat: https://finto.fi/yso/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp19426&anylang=on&clang=fi

https://www.kirjastot.fi/kysy/mitka-ovat-tekstitietokantojen-paatyypit?language_content_entity=fi

**Comment by mirmaid** [comment]
Kokotekstitietokannat/SLM

**Comment by mirmaid** [comment]
YSO: onko tekstitietokannat selkeä, otetaanko kokotekstitietokannat erikseen vai muutetaanko?

**Comment by AuHo22** [comment]
https://blogs.helsinki.fi/opiskelijan-digitaidot/3-tiedonhankinta/3-1-tiedonhankinnan-suunnittelu/tiedonlahteet/

**Comment by mirmaid** [comment]
Täällä _tekstitietokannat_ siis laajemmin: https://www.kirjastot.fi/kysy/mitka-ovat-tekstitietokantojen-paatyypit?language_content_entity=fi. YSOssa kuitenkaan _viitetietokannat_ ei ole sen alla. Jos taas nykyinen hierarkia on ok, Aulin linkin kautta saisi sen käsityksen, että tekstitietokannat on suppea (mutta mitä oikeastaan). Se on kuitenkin YSAn perua, joten ei ole alun perin viitannut siihen, että tekstitietokannat olisivat ainoastaan faktatietokantoja (YSAssa toisena yläkäsitteena tietokannat).

**Comment by mariaforsen** [comment]
Käyttäjän ja tiedonhakijan kannalta tässä on kuitenkin tärkeintä varmaan se että sanastossa (ainakin SLM:ssä, kuten ehdotuksessa pyydettiin) olisi käsite joka viittaa nimenomaan kokotekstitietokantoihin. koska se on hakijan kannalta ratkaisevaa, että onko kyseessä vain viitetietokanta tai jokin muu "teksti"tietokanta (vrt. vaikka kuvatietokantaan), vai sellainen tietokanta mistä oikeasti pääsee lukemaan artikkelit yms. tekstit kokonaisuudessaan).

**Comment by mirmaid** [comment]
Tietohuollon sanastossa (1993) tekstitietokanta on sv. fulltextdatabas, textdatabank; en. full text database, textual database; de. Volltextdatenbasis, Textdatenbank; fr. base de donnees textuelles. Ks. tietokanta

Tietokanta (ei tietopankki): kokoelma tiettyä kohdetta kuvaavia tietoja, joita yksi tai useampi tietojärjestelmä käyttää ja päivittää. _Tietokannat voidaan jakaa viitetietokantoihin ja faktatietokantoihin ja nämä edelleen tekstitietokantoihin, numeerisiin tietokantoihin ja tekstinumeerisiin tietokantoihin._

**Comment by mirmaid** [comment]
Ja YSOssa on siis myös numeeriset tietokannat, mutta sitä on käytetty hyvin vähän. Tämäntyyppinen jaottelu on ehkä jäänyt historiaan, mutta vaikuttaa siltä että tekstitietokanta ei ole alun perin tarkoittanut ihan pelkästään kokotekstitietokantaa suomeksi, kielivastineet kuitenkin viittaavat siihen. Tulee mieleen sellainenkin, onko tuossa voinut olla väärinkäsitys full text database -termin merkityksestä (että se tarkoittaisi "pelkkää tekstiä" vs. numeerinen).

**Comment by mariaforsen** [comment]
On mahdollista että ruotsiksi on valittu fulltextdatabaser myös sen takia että se on ollut, ja on hyvin tärkeä termi (tällaisia ratkaisuja on voitu vuosien varrella tehdä, silloin kun ei vielä ollut samanlaista tarkkuutta siinä että erikieliset termit todella vastaavat toisiaan (YSA ja Allärs - erilliset asiasanastot). SAOssa ja SAOgenressä vain "fulltextdatabaser" https://id.kb.se/find?q=fulltextdatabaser

Genrepuolella termi (kokotekstitietokannat) on tietty äärimmäisen tärkeä (tiedonhakijat haluavat tietää saako ko. tietokannasta kokotekstejä vai pelkästään viitteitä tms.) mutta YSOn puolella ei välttämättä samalla tavalla keskeinen? Itse (informaatiotutkimustaustaisena) kannatan kyllä erottelua, mutta tässä taitaa olla kielierokin.

**Comment by ilona-x** [comment]
> On alettu tuottaa tietokantoja, joista käyttäjä saa viitteiden sijasta suoraan tarvitsemansa tiedot käytettäväkseen. Näitä tietokantoja on monentyyppisiä. Tekstitietokannat (full-text databases) sisältävät tekstimuotoisia dokumentteja, kuten esim. lakiasioita (ennakkotapauksia, lakitekstiä) ja muita hallinnollisia päätöksiä koskevia dokumentteja, uutisaineistoa, aikakauslehtiä,
> hakuteoksia jne. [Lern-83] [Teno-84]. Tavallisesti nämä ovat, ainakin toistaiseksi saatavissa myös paperijulkaisuina. Numeeriset tietokannat (numerical databases) sisältävät pääosin tai pelkästään numeromuotoista tietoa esim. luonnontieteen ja tekniikan (kemiallisten yhdisteiden omaisuudet), yritystoiminnan ja kaupan (osakkeiden kurssit, tuotteiden valmistajat) sekä julkisen vallan ja yhteiskuntatieteiden aloilta (tilastoaineistot) [ChHe-84] [Fost-84] [Heim-82] [RuHa-84]. Muut faktatietokannat (other fact databases) sisältävät einumeerista mutta kuitenkin yleensä strukturoitua tietoa samoista aihepiireistä [Cuad-82] [Cuad-84].

Lähde: Järvelin, Kalervo, Numeeriset tietokannat ja niiden käyttökustannukset: uusia ongelmia informatiikalle ja informaatiopalvelulle. Kirjastotiede ja informatiikka 5 (2): 33—55, 1986.
https://journal.fi/inf/article/view/1283/1130

--

Termi tekstitietokannat on otettu YSAan 1987, joten voisi ajatella, että YSAn jaottelu on ollut samankaltainen kuin tuossa v. 1986 julkaistussa artikkelissa.

**Comment by mariaforsen** [comment]
Totta, ja silloin 1986 ei varmaan ollut samanlaista tarvetta vielä juuri käsitellä "kokotekstitietokantoja". Nykyään se taitaa olla esim. opiskelijoille ja tutkijoille aivan "välttämätöntä".

**Comment by YSO-kokous** [comment]
**Päätös**

Vaihdetaan päätermiksi _kokotekstitietokannat_.
