### ISSUE TITLE
gammakuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10248]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[gammakuvaus](http://www.yso.fi/onto/yso/p10180)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi tai uusi termi: skintigrafia 

**Perustelut ehdotukselle**

onko synonymi, vrt mesh eng.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Gammakuvaus linkattu näihin: https://sv.wikipedia.org/wiki/Skintigrafi ja https://en.wikipedia.org/wiki/Scintigraphy

**Comment by mirmaid** [comment]
^ Kuulostaisi siltä, että ohjaustermi ok. Myös Lääketieteen termit: skintigrafia ks. gammakuvaus.
