### ISSUE TITLE
ruumis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10244]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ruumis](http://www.yso.fi/onto/yso/p4005)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Keho

**Perustelut ehdotukselle**

Nykykielenkäytössä ruumis tarkoittaa kuollutta ruumista. Keho-sanaa käytetään yleisesti puhuttaessa elävästä kehosta. Esim. kehollisuus ja ruumiillisuus ovat käsitteinä hiukan erilaisia sävyltään, näistäkin kehollisuus on paitsi neutraalimpi myös ehdottomasti käytetympi nykyään. Kun kuvataan kehollisuutta esim. taiteessa, ei sanaa voi korvata ruumiillisuudella, sillä merkitys on eri. Esimerkki:
https://tulva.fi/lue/ninja-thyberg-ohjasi-elokuvan-pornoteollisuudesta-ja-turhautui-feministiseen-diskurssiin-pornon-naiset-tietavat-mita-tekevat/
"Mieskatse on niin sisäistettyä, että pelkkä kehon näkeminen saa ajattelemaan, että miestä vartenhan tuo näytetään.” Lause saa aivan eri merkityksen jos keho korvataan sanalla ruumis. Näyttäisi siltä, että ruumis-sanan käyttö yleiskäsitteenä elävälle ja kuolleelle keholle on jäänne, joka ei vastyaan nykykielenkäyttöä.  
https://www.kotus.fi/nyt/kolumnit_artikkelit_ja_esitelmat/kieli-ikkuna_%281996_2010%29/ruumis_kalmo_ja_keho

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
"Ruumis" tosiaan viitannee enemmän kuolleeseen ruumiiseen/kehoon, mutta mielestäni ei kuitenkaan aina ja ehdottomasti. Joten mielestäni tähän olisi hyvä jättää väljyyttä merkitysten kannalta.

**Comment by mariaforsen** [comment]
Ruotsiksi vastine on kroppen ja se viittaa elävään ruumiseen/kehoon. Jos se olisi "kropp" se voisi viitata mahdollisesti myös kuolleeseen, mutta sille on oma terminsä: lik. Jos haluttaisiinkin jakaa, se olisi ok ruotsiksi: ruumis (kuollut)=lik, keho=kropp(en)

**Comment by mirmaid** [comment]
Tämä keskustelu on käyty aika monta kertaa.

Kielitoimiston sanakirja: ruumis: ihmisen t. eläimen koko elimistö.
1. elävänä: keho. _Kissan notkea ruumis. Nojasi oveen koko ruumiillaan. Äiti suojeli lasta omalla ruumiillaan. Karaista, harjoittaa ruumistaan. Rääkätä ruumistaan kovilla ponnistuksilla. Olla täysissä sielun ja ruumiin voimissa. Terve sielu terveessä ruumiissa_ SP. _Prostituoitu myy ruumistaan._

**Comment by mirmaid** [comment]
Ehdotukseen linkatussa Kotuksen artikkelissa: _Edelleenkin ruumiilla tarkoitetaan sekä elävää että kuollutta. Jos olisi päätetty rajata vuosisatoja käytetty ruumis-sana vain kuolleen merkitykseen, mitä silloin olisi tehty tunnetuille elävän ruumiin sanonnoille, kuten ”terve sielu terveessä ruumiissa”, ”olla hyvissä sielun ja ruumiin voimissa”, ”rääkätä ruumistaan”, ”ruumiinvoimat”, ”ruumiinrakenne” tai ”joutua ruumiintarkastukseen”?_

**Comment by mariaforsen** [comment]
Eli onko tilanne nyt se että suomeksi on tarkoitus käyttää YSO-termiä ruumis myös kuolleista ruumiista? Jos on, niin ruotsiksi pitäisi ainakin muuttaa kroppen > kropp, koska tuo määrätty muoto on nimenomaan elävään ruumiiseen viittaava.

**Comment by mirmaid** [comment]
^ Kannattaa selata Melindan ruumis-viitteitä jos tuntuu, että ruotsinkielinen muoto kannattaa tarkistaa. En tiedä millaisessa aineistossa olisi kyse nimenomaan kuolleesta ruumiista, vaikka esim. anatomian kirjoissa ruumis ei välttämättä ole myöskään elävä.

**Comment by mariaforsen** [comment]
Melindassa suurin osa elävästä kehosta, mutta poikkeuksia on esim. [The corpse in the Middle Ages : embalming, cremating, and the cultural construction of the dead body / Romedio Schmitz-Esser ; translated by Albrecht Classen and Carolin Radtke.] Tilanne ihan ok nyt ruotsin osalta.

**Comment by mirmaid** [comment]
^ Hyvä esimerkki löytyikin. Ajattelin, että yleensä noissa keskeisempää on kuolema jne. kuin silkka ruumis. Mutta suomeksi siis käy niin kuolleesta kuin elävästä yhtä lailla, joten jos tuokaan kirja ei ole ruotsin kannalta ongelma, niin ei sitten varmaan mikään 👍

**Comment by mirmaid** [comment]
Ehdotus: ei muutosta.

**Comment by mariaforsen** [comment]
Sv. kroppen > kropp, kropp (organismer)?
https://svenska.se/tre/?sok=kropp&pz=1 
https://www.kielitoimistonsanakirja.fi/#/ruumis?searchMode=all
