### ISSUE TITLE
ampujat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10249]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ampujat](http://www.yso.fi/onto/yso/p10264)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: ampumaurheilijat

**Perustelut ehdotukselle**

Tärkeä synonymi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Muutaman kerran käytetty muissakin yhteyksissa, halutaanko tätä rajata ihan tarkenteella?

**Comment by YSO-kokous** [comment]
### Päätös
vaihdetaan päätermiksi
ampumaurheilijat KT ampujat
