### ISSUE TITLE
Penni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10241]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Penni](http://www.yso.fi/onto/yso/p16824)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan käsite

**Perustelut ehdotukselle**

Käytetty kirjasto- ym. aineistojen kuvailussa vain muutaman kerran ja lähes kaikki väärin. Kyseessä siis tietokoneohjelma (Penni - kodin talousohjelma vuodelta 1991) - ei rahayksikkö eikä Penniteatteri eikä fiktiivinen hahmo.

**Ehdottajan organisaatio**

Finto

**Comment by mirmaid** [comment]
Poisto ok.
