### ISSUE TITLE
libanonilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10243]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

libanonilaiset

**Ehdotettu termi ruotsiksi**

libanesiska

**Ehdotettu termi englanniksi**

lebanese

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

386-kenttään merkintä kansalaisuudeksi

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://fi.wikipedia.org/wiki/Libanonin_v%C3%A4est%C3%B6](http://Libanonin väestö), [https://en.wikipedia.org/wiki/Lebanese_people](http://Lebanese people)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ruznamati al-mumayyazat 978-614-03-2062-8

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [libanonilaiset](http://finto.fi/yse/fi/page/Y510243)

**Comment by mariaforsen** [comment]
Sv. libaneser
