### ISSUE TITLE
synagogamusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10242]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

synagogamusiikki

**Ehdotettu termi ruotsiksi**

synagogmusik

**Ehdotettu termi englanniksi**

synagogue music 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

SLM ja YSO. Tarvitaan synagogamusiikin ja synagogamusiikkia käsittelevien teosten kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 juutalainen uskonnollinen musiikki, juutalainen liturginen musiikki

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh85131565), [LCGFT](https://lccn.loc.gov/gf2017026116)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://uniarts.finna.fi/Record/uniarts.992231504206249

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [synagogamusiikki](http://finto.fi/yse/fi/page/Y510242)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT uskonnollinen musiikki

**Comment by mariaforsen** [comment]
Sv. synagogmusik HT synagogsmusik, synagogemusik, synagogamusik, judisk liturgisk musik  
https://id.kb.se/find?q=Synagogue%20music

**Comment by YSO-kokous** [comment]
### Päätös
synagogamusiikki KT  juutalainen liturginen musiikki

**Comment by mirmaid** [comment]
Hyväksytty /SLM.
