### ISSUE TITLE
laki asianajajista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10259]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laki asianajajista

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Advokaträtt

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [laki asianajajista](http://finto.fi/yse/fi/page/Y510259)

**Comment by mariaforsen** [comment]
Sv. lag om advokater
