### ISSUE TITLE
Paraolympialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10250]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Paraolympialaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Paralympialaiset ovat kansainväliset vammaisurheilukilpailut, jotka järjestetään kahden vuoden välein vuorotellen kesäisin ja talvisin. Paralympialaisten järjestämistä hallinnoi Kansainvälinen Paralympiakomitea (IPC)

**Perustelut ehdotukselle**

Olympialaiset on, paraolympialaisia ei, vaikka ne joka kerta järjestetään

**Ehdotettu yläkäsite YSOssa (LT)**

 [olympialaiset](http://www.yso.fi/onto/yso/p7930)

**Ehdotetut temaattiset ryhmät**

 [97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [vammaisurheilu](http://www.yso.fi/onto/yso/p25148)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Verkkoarkiston teemakeräyksen kuvailu "Pekingin talviolympialaiset 2022"

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [Paraolympialaiset](http://finto.fi/yse/fi/page/Y510250)

**Comment by ilona-x** [comment]
YSOssa on jo **paralympialaiset** http://www.yso.fi/onto/yso/p3094

**Comment by mirmaid** [comment]
Lisätään ohjaustermiksi.

**Comment by LeKorsu** [comment]
Tästä tuleekin mieleeni, että minun on jo pidemmän aikaa pitänyt tehdä käsite-ehdotus paraurheilusta (vammaisurheilu <> paraurheilu), vrt. urheilu <> huippu-urheilu. Voidaanko se hyväksyä ilman erillistä ehdotusta tässä samalla?

**Comment by ilona-x** [comment]
https://www.paralympia.fi/paralympiakomitea/medialle/terminologiaa

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään ohjaustermit
paraolympialaiset  KÄYTÄ paralympialaiset
paraurheilu KÄYTÄ vammaisurheilu
