### ISSUE TITLE
palkokasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10256]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[palkokasvit](http://www.yso.fi/onto/yso/p10330)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi valkuaiskasvit

**Perustelut ehdotukselle**

Käytetään mm. palkokasveista esim. http://ravinnejaenergia.fi/fi/valkuaisomavaraisuus/

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Kaikki valkuaiskasvit eivät liene palkokasveja. Esim [täällä ](https://www.smts.fi/fi/Manni_2016)mainitaan "mm. apilat, sinimailanen, virnat, herne, härkäpapu, lupiinit sekä rypsi ja rapsi". - Ja samat itse asiassa tuossa ehdotuksessa olevassa linkissäkin.

**Comment by ilona-x** [comment]
AFOssa erikseen **valkuaiskasvit** http://www.yso.fi/onto/afo/p3552

**Comment by mirmaid** [comment]
Aina oppii uutta, muut paitsi rypsi ja rapsi ovat tosiaan hernekasveja ja jopa apilassa on ilmeisesti palko, vaikka se ei hahmotukaan sellaiseksi ihan tavalliselle tallaajalle. :four_leaf_clover: Rypsissä ja rapsissakin on palko, mutta ne eivät ole hernekasveja vaan kaaleja.

**Comment by YSO-kokous** [comment]
### Päätös
Ei hyväksytä ohjaustermiä.
