### ISSUE TITLE
ilmastotunteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10257]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ilmastotunteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

climate emotions

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ilmastotunteita ja ympäristötunteita käsittelevää kirjallisuutta ilmestyy yhä enenevässä määrin. Spesifi käsite, jolla asiakkaat voivat helpommin hakea tietoa, kuin erilaisilla yhdistelmillä sanoista ilmasto (ilmasto, ilmastokriisi, ilmastonmuutokset jne.) tai ympäristö ja tunteet.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tunteet](http://www.yso.fi/onto/yso/p3485)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 ympäristötunteet, ilmastoahdistus, ilmastosuru

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kestävää tekoa: Nuorisobarometri 2021. https://tietoanuorista.fi/wp-content/uploads/2022/03/nuorisobarometri-2021-web.pdf 

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [ilmastotunteet](http://finto.fi/yse/fi/page/Y510257)

**Comment by FinMeSHienPaimentaja** [comment]
Mielestäni ei ole ainakaan vielä tarpeen - jos tälle tielle lähdettäisiin, niin tulisi valtava määrä myös muita termejä, joihin pitäisi ympätä "tunteet".

**Comment by mirmaid** [comment]
Melindassa kerran _ilmastoahdistus_.

**Comment by AuHo22** [comment]
Myöskään termiä luontorakkaus ei hyväksytty YSOon - tunteista kun puhutaan

**Comment by mirmaid** [comment]
Palaute: _Ilmastoahdistus-sana alkaa olla vakiintunut käsite. Sitä ei ole YSOssa, mutta onko sen kaltainen sana jota ei edes ajatella YSOon? Ahdistus-sana perinteisessä mielessä on enempi lääketieteellinen termi. Sanaa ei oikein arvaa korvata muullakaan._

**Comment by FinMeSHienPaimentaja** [comment]
Vertailun vuoksi mitä MeSH:eihin tulee, MeSH:eissä on varsinaisen (lääketieteellisiin diagnooseihin liittyvän) Anxiety Disorders -termin lisäksi pelkkä Anxiety ja Psychological Distress (ja myös aspektitermi psychology on olemassa).


Olisin edelleen ottamatta "ilmastoahdistusta", perusteluina edelleen, että samantapaisia yhdistelmätermejä (luontorakkaus ym.) tulisi sitten valtavan paljon ja pärjätään käyttämällä "ahdistus" + jokin ilmastotermi.

**Comment by AuHo22** [comment]
LC ja DNB näyttäisivät käyttävän vielä kombinatorisia asiasanoja asian kuvailemiseksi, esim: Klimawandel und Angst. Auswirkungen des Klimawandels auf Emotionen von Schülern ->
Klimaänderung* ; Anthropogene Klimaänderung* ; Zukunftsangst* ; Angst* ; Angststörung* ; Klimaschutz*

Rameausta sitten jo löytyy **Éco-anxiété** samoin kuin sitten näköjään LC:stä vastaava termillä Solastalgia, suomeksi ympäristöahdistus https://fi.wikipedia.org/wiki/Ymp%C3%A4rist%C3%B6ahdistus

Itse voisin kannattaa jompaa kumpaa termiä ottaen huomioon viime aikaisen keskustelun myös luontokadosta, jonka taustalla on tietenkin sitten ilmastonmuutos - lieneekö niin, että tällä hetkellä ilmastoahdistus-termi on valtaamassa alaa ehkä enemmän aiemmin käytetyltä ympäristöahdistus-termiltä. Vaikutusvaltaisilla foorumeilla kuitenkin näkee paljon termien käyttöä, esim.
https://www.duodecimlehti.fi/xmedia/duo/duo17696.pdf
https://www.ymparistoahdistus.fi/tag/ilmastoahdistus/

**Comment by mariaforsen** [comment]
Voisi olla myös ympäristöahdistus=miljöångest sanastossa.
https://www.ymparistoahdistus.fi/
https://www.sanakirja.fi/custom/en-sv-fi/ilmastoahdistus
https://www.sanakirja.fi/custom/en-sv-fi/ymp%C3%A4rist%C3%B6ahdistus
https://www.psykologiguiden.se/psykologilexikon/?Lookup=klimat%C3%A5ngest

**Comment by mirmaid** [comment]
Ehkä ympäristöahdistus, kaikki huolta aiheuttavat ympäristönmuutokset eivät johdu pelkästään ilmastonmuutoksesta (vaikka hyönteiskato).

**Comment by YSO-kokous** [comment]
Ympäristöahdistus KT ilmastoahdistus.

**Comment by mariaforsen** [comment]
Sv. miljöångest HT klimatångest

https://mieli.fi/wp-content/uploads/2021/09/ympa%CC%88risto%CC%88ahdistus_taitto_RUOTSI_PAINO.pdf
https://lund.se/personalingangen/for-dig-som-arbetar-inom-forskola-och-skola/naturskolan/pedagogiska-aktiviteter/ekokanslor-hos-barn-och-unga
https://vihrealippu.fi/sv/lilla-miljoangestguiden/
https://www.hbl.fi/artikel/79b7613e-e4c7-419b-8657-74230cf259d9
https://www.nyyti.fi/sv/projekt/projektet-miljon-framtiden-och-valbefinnandet/
https://finlandsnatur.fi/hallbar-livsstil/klimatangest-intressant-nytt-forskningsomrade/
