### ISSUE TITLE
ensyklikat [YSO + SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10252]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ensyklikat [YSO + SLM]

**Ehdotettu termi ruotsiksi**

encyclicals

**Ehdotettu termi englanniksi**

encyklikor

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan ensyklikoiden ja niitä käsittelevän aineiston kuvailussa. Sanasto ei nykyisellään sisällä sopivia asiasanoja ("kiertokirjeet" ei sovi laisinkaan).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q221409)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/004748569 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [ensyklikat [YSO + SLM]](http://finto.fi/yse/fi/page/Y510252)

**Comment by jtuohini** [comment]
Korjaus: LT-suhteeksi [**kiertokirjeet**](http://www.yso.fi/onto/yso/p8645) käykin hyvin, kun onkin YSO:ssa määritelty hallinnonalaan kuuluviksi.

**Comment by jtuohini** [comment]
KT-muodoksi lisäksi ainakin _apostoliset kehotuskirjeet_ ja _apostoliset kiertokirjeet_.

**Comment by AuHo22** [comment]
Vaikea nähdä oikeastaan eroa kiertokirje-käyttöön, esim. muut nimekkeet tietueessa Fratelli tutti 978-952-7153-55-0
tai
https://www.vaticannews.va/sv/suomi/news/2020-10/fratelli-tutti-paavi-franciscuksen-kolmas-kiertokirje.html

Tietenkin kun ketjuja emme voi käyttää, niin paavin kiertokirjeet olisi sitten selkein ratkaisu, mutta vertaa keskustelu bibliografioista, niissäkin on samanlainen ehdotus eli vain kombinoimalla voidaan löytää tietyntyyppisiä bibliografioita, esim. aihebibliografiat + 600-kenttä jne. (vs. henkilöbibliografiat)

**Comment by mirmaid** [comment]
paavin kiertokirjeet KT ensyklikat, apostoliset kiertokirjeet, apostoliset kehotuskirjeet

**Comment by AuHo22** [comment]
https://katolinen.fi/asiakirjoja/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. påvliga encyklikor HT påvliga rundskrivelser, encyklikor
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_f7200d45fee8c61f5cfc9018fc21765d&list_id=1&keyword=kiertokirje&word=kiertokirje
https://svenska.se/tre/?sok=encyklika&pz=1
https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_viktigare_p%C3%A5vliga_encyklikor
