### ISSUE TITLE
ampuma-aseet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10253]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ampuma-aseet](http://www.yso.fi/onto/yso/p11352)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ot: tuliaseet

**Perustelut ehdotukselle**

synonymi, ks. mesh, wikipedia jne.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
SAO: eldvapen ANV skjutvapen

**Comment by mirmaid** [comment]
Varmaan ok, vaikka jousikin on ampuma-ase.
