### ISSUE TITLE
Perä-Posio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10269]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Perä-Posio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kylän nimi Posion kunnassa.

**Perustelut ehdotukselle**

Maantieteellinen paikannimi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Posio](http://www.yso.fi/onto/yso/p105232)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paikallishistorialliset, maantieteelliset yms.

**Ehdottajan organisaatio**

Rovaniemen kaupunginkirjasto / maakuntakokoelma
**Termiehdotus Fintossa:** [Perä-Posio](http://finto.fi/yse/fi/page/Y510269)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10183061
