### ISSUE TITLE
Vuolenkoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10266]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vuolenkoski](http://www.yso.fi/onto/yso/p185106)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko linkitys ok?

**Perustelut ehdotukselle**

Paikkatietoalustalla tämä on "järvi tai lampi", aik. ilmeisesti "vakaveden osa", auktorisoitu koskena. 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
http://www.yso.fi/onto/yso/p185106
http://paikkatiedot.fi/so/1000772/10537429

**Comment by ilona-x** [comment]
Melindassa 1 viite:
Vuolenkosken koski kuvina
https://melinda.kansalliskirjasto.fi/byid/005991010

**Comment by mirmaid** [comment]
Vuolenkoski (Iitti : kylä)
Vuolenkoski (Iitti : vesialue)
