### ISSUE TITLE
osakeyhtiölaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10264]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[osakeyhtiölaki](http://www.yso.fi/onto/yso/p11605)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaanko/jaetaanko?

**Perustelut ehdotukselle**

Kaksi eri lakia: https://finlex.fi/fi/laki/alkup/1978/19780734 ja https://www.finlex.fi/fi/laki/alkup/2006/20060624 Erinimisiä ruotsiksi (Allfossa nyt vanhempi laki näistä)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
_Yhdenvertaisuuslaki_ jaettiin vuositarkenteilla, aina ei varmaan ole näin tehty (tai edes huomattu).

**Comment by AuHo22** [comment]
Eli pitäisikö olla myös esim. laki yhteistoiminnasta yrityksissä (2007) ja yhteistoimintalaki (2021)

**Comment by mirmaid** [comment]
^ Siinä ei tarvita vuositarkenteita, koska lait ovat erinimisiä.

**Comment by AuHo22** [comment]
Huomaako käytännön kuvailija kiireessä asian?

**Comment by mirmaid** [comment]
Miten halutaan tehdä? Lait eivät varmaan kuulu YSOon enää sitten, jos teossanasto joskus saadaan, mutta lisätäänko toistaiseksi vuositarkenteita, jos kahteen lakiin on viitattu samalla nimellä, vaikka niillä virallisesti olisikin eri nimet?

**Comment by mariaforsen** [comment]
Eli nyt olisi:
osakeyhtiölaki (1978) = lag om aktiebolag + tarkenne?
osakeyhtiölaki (2006) = aktiebolagslag + tarkenne?

**Comment by YSO-kokous** [comment]
**Päätös**

Lakien identtisiin muotoihin kirjataan vuositarkenne.
