### ISSUE TITLE
temperamentti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10261]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[temperamentti](http://www.yso.fi/onto/yso/p7077)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tällekin KT luonne?

**Perustelut ehdotukselle**

vrt. luonteenpiirteet, persoonallisuus

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Nyt ohjausterminä _luonteenpiirteet_ ja _persoonallisuus_ -käsitteille.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: temperamentti: luonteenlaatu; temperamenttisuus, luonteen tulisuus.

**Comment by YSO-kokous** [comment]
### Päätös
lisätään ohjautermi
luonne KÄYTÄ temperamentti
