### ISSUE TITLE
propionibakteerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10260]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

propionibakteerit

**Ehdotettu termi ruotsiksi**

propionibakterier

**Ehdotettu termi englanniksi**

propionibacterium

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [bakteerit](http://www.yso.fi/onto/yso/p1749)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Propionibakteerit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://aaltodoc.aalto.fi/handle/123456789/45648

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [propionibakteerit](http://finto.fi/yse/fi/page/Y510260)

**Comment by jarmosaarikko** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh88023303 Propionibacterium
Wikidata: http://www.wikidata.org/entity/Q1309614
MeSH http://www.yso.fi/onto/mesh/D011424  Propionibacterium

**Comment by mariaforsen** [comment]
Sv. propionibakterier HT propionibacterium
