### ISSUE TITLE
glukoosirasituskoe

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10263]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

glukoosirasituskoe

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 sokerirasituskoe

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://www.yso.fi/onto/mesh/D005951)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/330187

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [glukoosirasituskoe](http://finto.fi/yse/fi/page/Y510263)

**Comment by FinMeSHienPaimentaja** [comment]
Tätä tulee lääketieteen puolella aika paljon vastaan, joten kannatan Ysoon ottamista.

**Comment by mirmaid** [comment]
Lääketieteen termit: _sokerirasituskoe, glukoosikoe | lähinnä sokeriaineenvaihdunnan tutkimiseen käytettävä testi, jossa seurataan veren glukoosipitoisuutta suun kautta annetun glukoosiannoksen jälkeen_

FinMeSH: http://www.yso.fi/onto/mesh/D005951

**Comment by mariaforsen** [comment]
Sv. glukosbelastningstest /mesh HT glukostoleranstest, sockerbelastningstest
