### ISSUE TITLE
Ristilä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10267]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Ristilä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kylän nimi Posion kunnan pohjoisosassa.

**Perustelut ehdotukselle**

Maantieteellinen paikannimi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Posio](http://www.yso.fi/onto/yso/p105232)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paikallishistorialliset, luonnontieteelliset yms. 

**Ehdottajan organisaatio**

Rovaniemen kaupunginkirjasto / maakuntakokoelma.
**Termiehdotus Fintossa:** [Ristilä](http://finto.fi/yse/fi/page/Y510267)

**Comment by ilona-x** [comment]
http://paikkatiedot.fi/so/1000772/10183366
