### ISSUE TITLE
Karjalaisenniemi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10272]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Karjalaisenniemi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kylän nimi Posion kunnassa.

**Perustelut ehdotukselle**

Maantieteellinen paikannimi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Posio](http://www.yso.fi/onto/yso/p105232)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paikallishistoriallinen, maantieteellinen.

**Ehdottajan organisaatio**

Rovaniemen kaupunginkirjasto / maakuntakokoelma.
**Termiehdotus Fintossa:** [Karjalaisenniemi](http://finto.fi/yse/fi/page/Y510272)

**Comment by ilona-x** [comment]
http://paikkatiedot.fi/so/1000772/10184140
