### ISSUE TITLE
perhevapaakorvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10273]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

perhevapaakorvaus

**Ehdotettu termi ruotsiksi**

familjeledighetsersättning

**Ehdotettu termi englanniksi**

employer compensation for family leave costs 

**Tarkoitusta täsmentävä selite**

 	
suomi:
  	
perhevapaakorvaus
  
  	
Määritelmä:
  	
naispuolisen työtekijän työnantajalle maksettava kertakorvaus vanhemmuudesta aiheutuvista perhevapaakustannuksista
  
  	
ruotsi:
  	
familjeledighetsersättning
  
  	
Määritelmä:
  	
engångsersättning till en kvinnlig anställds arbetsgivare som betalas för kostnaderna för familjeledighet som orsakas av föräldraskap
  
  	
Lisätietoa:
  	
Kelan terminologinen sanasto, Etuuksiin liittyvät käsitteet, 6. laitos

**Perustelut ehdotukselle**

Kelan etuus. Osa sosiaaliturvaa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:NBN:fi-fe2022031123032

**Ehdottajan organisaatio**

Kela
**Termiehdotus Fintossa:** [perhevapaakorvaus](http://finto.fi/yse/fi/page/Y510273)

**Comment by mirmaid** [comment]
https://www.kela.fi/tyonantajat-perhevapaakorvaus

Ei Melindassa.

**Comment by LeKorsu** [comment]
Monikossa vai yksikössä? Suurin osa erilaisista korvauksista on monikossa (esim. lääkekorvaukset, työttömyyskorvaukset), mutta vahingonkorvaus on yksikössä.

**Comment by ilona-x** [comment]
Pitäisikö jo termistä näkyä, että kyseessä on nimenomaan työnantajalle maksettava korvaus, ettei tätä aleta käyttää vahingossa vanhempainrahasta, äitiysrahasta ja isyysrahasta?

**Comment by mirmaid** [comment]
^ Totta, mikähän se voisi olla? Nämä etuudet ovat yksikössä silloin, kun on vain yksi tietty etuus, johon termi viittaa.

**Comment by ilona-x** [comment]
Voisiko olla "työnantajan perhevapaakorvaus"?

**Comment by YSO-kokous** [comment]
### Päätös
perhevapaakorvaus työnantajalle KT työnantajan perhevapaakorvaus

**Comment by pappila** [comment]
Miksei voi olla ehdotetussa muodossa perhevapaakorvaus? Se on kuitenkin etuuden virallinen nimi. Sisältöä voi tarkentaa huomautuskentässä

**Comment by mariaforsen** [comment]
Jos virallinen termimuoto on parempi päätermi voisi olla myös "perhevapaakorvaus (työnantajalle)"? Silloin kuvailija kuitenkin näkee heti mistä on kysymys, mutta päätermi on silti virallisen muodon mukainen. 

Sv. familjeledighetsersättning (till arbetsgivare) HT familjeledighetsersättning till arbetsgivare
https://www.kela.fi/web/sv/arbetsgivare-familjeledighetsersattning

**Comment by pappila** [comment]
Vaikuttaa hyvältä ehdotukselta
