### ISSUE TITLE
bullat [YSO + SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10274]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

bullat [YSO + SLM]

**Ehdotettu termi ruotsiksi**

bullarier

**Ehdotettu termi englanniksi**

Papal bulls

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa, eikä sanastossa ole ennestään sopivaa asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [asiakirjat](http://www.yso.fi/onto/yso/p2325)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 paavin bullat, påvliga bullarier

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85017972), [Wikidata](https://www.wikidata.org/wiki/Q189867)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/000230106

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [bullat [YSO + SLM]](http://finto.fi/yse/fi/page/Y510274)

**Comment by mirmaid** [comment]
Kerran Melindassa.

Tällainen merkityskin näyttää olevan: https://fi.wikipedia.org/wiki/Bulla

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Paavin_bulla
Sv. påvliga bullor OT bullor (av påven)
Bullarier vähän eri asia (NE: bullaʹrium (latin), utgåva av främst bullor men även andra påvliga skrivelser)

**Comment by nikopartanen** [comment]
Tieteen termipankissa on myös:

https://tieteentermipankki.fi/wiki/Historia:bulla

**Comment by YSO-kokous** [comment]
### Päätös
paavin bullat KT bullat, paavilliset bullat LT asiakirjat
