### ISSUE TITLE
Englannin sisällissota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10283]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Englannin sisällissota

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/329830

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Englannin sisällissota](http://finto.fi/yse/fi/page/Y510283)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Englannin_sis%C3%A4llissota

http://id.loc.gov/authorities/subjects/sh85056792

**Comment by mariaforsen** [comment]
Sv. engelska inbördeskriget (1642-1649) HT engelska inbördeskriget, engelska inbördeskriget 1642-1649

**Comment by AuHo22** [comment]
Selkeyden takia olisi kuitenkin hyvä laittaa vuosiluvut sulkeisiin? Esim.
 https://en.wikipedia.org/wiki/List_of_English_civil_wars

Myös merkitty vuosille 1642-1651?

**Comment by LeKorsu** [comment]
Encyclopedia Britannica  käyttää monikollista termiä "English civil wars" tarkoittaen ajanjaksoa 1642-1651, 
https://www.britannica.com/event/English-Civil-Wars, mutta LCSH:ssa yksikössä  samat vuosiluvut mukana. Wikipedia-artikkelin kaltaiseen jaotteluun tuskin kannattaa mennä (1. sisällissota, 2. sisällissota, 3. sisällissota), kun ysossa ei ole edes ruusujen sotaa.

**Comment by mirmaid** [comment]
En ehdottanut vuositarkenteita, kun niitä on meillä tähän asti ainakin suomenkielisissä termimuodoissa käytetty vain silloin, kun termillä viitataan useampaan samannimiseen asiaan tai on muuten hyvin epäselvä kattavuus.

**Comment by YSO-kokous** [comment]
### Päätökset
Hyväksytään. 
Käyteään yksikkömuotoa ja lisätään vuositarkenne
