### ISSUE TITLE
seurustelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10288]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seurustelu](http://www.yso.fi/onto/yso/p11722)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi deittailu, tai uutena terminä.

**Perustelut ehdotukselle**

On Melindassa. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Kannatan erillisenä terminä.

**Comment by mirmaid** [comment]
Englanniksi dating nyt ohjaustermi.

**Comment by mirmaid** [comment]
Sanastossa on _treffit_. KAUNOssa on erikseen _deittailu_, mutta tarvitaankohan kuitenkaan tietoaineistossa?

**Comment by AuHo22** [comment]
Mielestäni deittailu sopisi paremmin ohjaustermiksi treffit-termille.

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään, mutta eri käsitteeseen
deittailu KÄYTÄ **treffit**
