### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10285]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[C++](http://www.yso.fi/onto/yso/p269)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään sulkutarkenne "(ohjelmointikieli)" ja englanniksi "(computer program language)"

**Perustelut ehdotukselle**

Alman auktoriteettivalvonta vertailee bibin ja auktoriteetin merkkijonoja ilman erikoimerkkejä. Siksi ohjelmistokielissä ’C++’ -> ’C’ ja ’C#’ -> ’C’ – eli molemmissa vertailu tehdään ’C’ normalisoituna, minkä takia authority control task list paukkuu.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
### Päätös
C++ (ohjelmointikieli) KT C++
