### ISSUE TITLE
oboistit [YSO]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10281]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

oboistit [YSO]

**Ehdotettu termi ruotsiksi**

oboister

**Ehdotettu termi englanniksi**

oboists

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSO:ssa ei tällä hetkellä tarkkaa asiasanaa oboisteja käsittelevän aineiston kuvailemiseen (tällä hetkellä asiaa kierretty laittamalla soitin kuvailuun, mutta eihän soittaja itse ole sama asia kuin soittamansa soitin).

**Ehdotettu yläkäsite YSOssa (LT)**

 [soittajat](http://www.yso.fi/onto/yso/p37965)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 oboensoittajat [fin], oboespelare [swe], oboe players [eng]

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85093721), [Wikidata](https://www.wikidata.org/wiki/Q16003954)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/017547775 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [oboistit [YSO]](http://finto.fi/yse/fi/page/Y510281)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
