### ISSUE TITLE
C-kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10287]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[C-kieli](http://www.yso.fi/onto/yso/p18909)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan muotoon "C (ohjelmointikieli)", "C (computer program language)"

**Perustelut ehdotukselle**

Alman auktoriteettivalvonta vertailee bibin ja auktoriteetin merkkijonoja ilman erikoimerkkejä. Siksi ohjelmistokielissä ’C++’ -> ’C’ ja ’C#’ -> ’C’ – eli molemmissa vertailu tehdään ’C’ normalisoituna, minkä takia authority control task list paukkuu. Ja jos halutaan kieliin sana logiikka, pitäisi tässäkin olla "[ohjelmointikielen nimi] (ohjelmointikieli)"

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Eli ongelmaa ei ole tässä käsitteessä, vaan kahdessa muussa mainitussa.

**Comment by YSO-kokous** [comment]
### Päätös
C (ohjelmointikieli) KT C-kieli
