### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10286]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[C#](http://www.yso.fi/onto/yso/p13591)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään sulkutarkenne suomeksi "(ohjelmointikieli)" ja englanniksi "(computer program language)"

**Perustelut ehdotukselle**

Alman auktoriteettivalvonta vertailee bibin ja auktoriteetin merkkijonoja ilman erikoimerkkejä. Siksi ohjelmistokielissä ’C++’ -> ’C’ ja ’C#’ -> ’C’ – eli molemmissa vertailu tehdään ’C’ normalisoituna, minkä takia authority control task list paukkuu.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
En ihan hahmota, mitä tässä siis tapahtuu. Jos task listin paukkuminen viittaa siihen, että Alma ei tunnista bib-tietueiden termejä samaksi kuin auktoriteetissa, auttaako tarkenteen lisääminen, eikö edelleen sitten näytä, että C# ja C++ ovat identtisiä?

Sanastossa on myös muita ohjelmointikieliä, joissa + -merkkejä.

**Comment by jtuohini** [comment]
Alma kaiketikin tiputtaa kaikki kirjainten jälkeiset merkit (pisteet, pilkut, plussat ym) auktorisoinnin piiristä, mutta jos niiden jälkeen on varsinaista tekstiä, huomioi ne. Näin ymmärsin Villen kommenteista.

**Comment by mirmaid** [comment]
^ ok

**Comment by YSO-kokous** [comment]
### Päätös
C# (ohjelmointikieli) KT C#
