### ISSUE TITLE
Cambridge (Massachusetts)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10280]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Cambridge (Massachusetts)

**Ehdotettu termi ruotsiksi**

Cambridge (Massachusetts)

**Ehdotettu termi englanniksi**

Cambridge (Massachusetts)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa käytetty julkaisupaikkana Cambridge 36943 kertaa ja aiheena 129 kertaa, muttei pysty sanomaan kumpi on kysessä: USA vai Englanti.  (julkaisumaa tietysti sen paljastaa, mutta paikkana pelkkä "Cambridge" ei ole yksiselitteinen, kun molemmat ovat tärkeitä yliopistokaupunkeja, Harvard, MIT, University of Cambridge, jne. ja näitä on muissakin osavaltioissa ja maissa.
RT käsitteelle tulee tässä tapauksessa myös tarkenne: "Cambridge (Englanti)"

**Ehdotettu yläkäsite YSOssa (LT)**

 [Massachusetts](http://www.yso.fi/onto/yso/p199609)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Cambridge (USA)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [Cambridge](http://www.yso.fi/onto/yso/p234553)

**Vastaava käsite muussa sanastossa**

 [LCNAF: Cambridge (Mass.)](http://id.loc.gov/authorities/names/n79061258), [Wikidata: Cambridge](http://www.wikidata.org/entity/Q49111), [Wikipedia: Cambridge (Massachusetts)](https://fi.wikipedia.org/wiki/Cambridge_(Massachusetts))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melinda

**Ehdottajan organisaatio**

Finto
**Termiehdotus Fintossa:** [Cambridge (Massachusetts)](http://finto.fi/yse/fi/page/Y510280)

**Comment by jarmosaarikko** [comment]
Eri kuin: http://www.yso.fi/onto/yso/p234553 Cambridge
LCNAF http://id.loc.gov/authorities/names/n79018410 
**Cambridge (England)**
KT Cambridge (Cambridgeshire)
