### ISSUE TITLE
direktiivit (kielitiede)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10284]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

direktiivit (kielitiede)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/330291

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [direktiivit (kielitiede)](http://finto.fi/yse/fi/page/Y510284)

**Comment by mirmaid** [comment]
Melindassa 8 viitettä, joissa direktiivit käytetty kielitieteen aineistoissa.

https://tieteentermipankki.fi/wiki/Kielitiede:direktiivi

**Comment by mariaforsen** [comment]
Löytyykö muista lähteistä kuin Tieteen termipankista?

**Comment by AuHo22** [comment]
https://termipankki.fi/tepa/en/search/direktiivi
Tepa-termipankissa lähikäsitteet imperatiivi ja jussiivi yksikössä YSOssa, voisi erottaa helpommin muista direktiiveistä -> direktiivi (kielitiede)

**Comment by nikopartanen** [comment]
Termi näyttää hyvin vakiintuneelta suomenkielisessä tätä aihetta käsittelevässä tutkimuksessa.

**Comment by YSO-kokous** [comment]
### Päätökset
otetaan yksikkömuodossa
**direktiivi (kielitiede)**

**Comment by mariaforsen** [comment]
Sv. direktiv (språkvetenskap)
