### ISSUE TITLE
tuohihuilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10282]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tuohihuilu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kyseistä soitinta käsittelevän aineiston kuvailemiseen ei ole YSO:ssa tarkkaa asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [huilusoittimet](http://www.yso.fi/onto/yso/p10307), [kansansoittimet](http://www.yso.fi/onto/yso/p7134)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571), [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Seko](http://urn.fi/urn:nbn:fi:au:seko:01141)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/museovirasto.456BD8207A337FCFB9A5DB1BE8DCBB85 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [tuohihuilu](http://finto.fi/yse/fi/page/Y510282)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Sv. näverflöjt
