### ISSUE TITLE
munasarjojen monirakkulatauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10299]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[munasarjojen monirakkulatauti](http://www.yso.fi/onto/yso/p1408)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tälle voisi lisätä ohjaustermejä esim. monirakkulainen munasarjaoireyhtymä

**Perustelut ehdotukselle**

lisää ohjaustermiehdokkaita FinMeSHissä:
http://www.yso.fi/onto/mesh/D011085

**Ehdottajan organisaatio**

kk/il

**Comment by FinMeSHienPaimentaja** [comment]
Tässä vielä, mitä Lääketieteen termit sanoo: 

munasarjojen monirakkulatauti
morbus polycysticus ovariorum, syndroma Stein-Leventhal la, polycystic ovary syndrome, polycystic ovary disease, Stein-Leventhal syndrome e, polycystiskt ovariesyndrom, Stein-Leventhals syndrom r (lyh. PCOS) Stein–Leventhalin oireyhtymä, polykystinen munasarjaoireyhtymä | mieshormonien liikaeritykseen liittyvä naisen oireyhtymä, jolle ovat ominaisia insuliiniresistenssi, molempien munasarjojen puhkeamattomat rakkulat, ovulaatioiden ja kuukautisten epäsäännöllisyys sekä usein hirsutismi ja hedelmättömyys

**Comment by mirmaid** [comment]
FinMeSHin lisäksi vielä ainakin _monirakkulaiset munasarjat_. (Kaikki FinMeSHin muodot eivät kovin käytettyjä.)
