### ISSUE TITLE
vågor

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10293]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vågor](http://www.yso.fi/onto/yso/p1191)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitääkö tarkentaa/jakaa? Esim. aallot (vesi)

**Perustelut ehdotukselle**

On ryhmässä 13, mutta on monimerkityksinen termi ja käytetty myös esim. valoon ja ääneen liittyvistä aalloista, ks. Melinda. https://www.kielitoimistonsanakirja.fi/#/aalto?searchMode=all

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
SAOssa mm. https://id.kb.se/term/sao/Vattenv%C3%A5gor ja https://id.kb.se/term/sao/V%C3%A5gor%20%28fysik%29

**Comment by mirmaid** [comment]
No suomeksi ei kyllä rajaudu vesiaaltoihin, mutta ryhmä on nyt vain sen mukaan. Tarvitaan varmasti kuitenkin laajemmin.

**Comment by ilona-x** [comment]
LCSHssa waves näyttää kattavan monenlaisia aaltoja http://id.loc.gov/authorities/subjects/sh85145789

--

muita YSOssa olevia aaltoja:
gravitaatioaallot
mikroaallot
millimetriaallot
radioaallot
yliaallot
https://finto.fi/yso/fi/search?clang=fi&q=*aallot

**Comment by YSO-kokous** [comment]
### Päätökset
Ei jaeta käsitettä.  Lisätään Fysiikan ryhmä.  Tarkistetaan hierarkia.
