### ISSUE TITLE
eroottiset sarjakuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10298]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

eroottiset sarjakuvat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

- 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9781634422536 The history of hentai manga : an expressionist examination of eromanga

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [eroottiset sarjakuvat](http://finto.fi/yse/fi/page/Y510298)

**Comment by mirmaid** [comment]
On SLM-sanastossa, joten varmaankin puoltaa paikkaansa myös YSOssa.
