### ISSUE TITLE
hepatoblastooma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10291]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hepatoblastooma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/330121

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [hepatoblastooma](http://finto.fi/yse/fi/page/Y510291)

**Comment by mariaforsen** [comment]
Sv. hepatoblastom https://finto.fi/mesh/fi/page/D018197?clang=sv
