### ISSUE TITLE
lämpövoimakoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10294]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lämpövoimakoneet](http://www.yso.fi/onto/yso/p743)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lämpövoimakoneen englanninkielinen vastine on "heat engine".

**Perustelut ehdotukselle**

"Thermal power device" ei tuota vastakaikua edes googlesta.

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
LCSH-linkin voisi myös lisätä tähän:
Heat-engines http://id.loc.gov/authorities/subjects/sh85059780
