### ISSUE TITLE
voimakoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10296]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[voimakoneet](http://www.yso.fi/onto/yso/p744)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistettävä Moottorit-käsitteeseen. Turbiinit Moottorit-käsitteen alakäsitteeksi.

**Perustelut ehdotukselle**

Voimakone on vanhanaikainen nimitys moottorille. Moottori tuottaa mekaanista energiaa eri lähteistä: lämpövoimakone ja turbiini sopivat tähän määritelmään 

(voimakoneella moottori-merkityksen lisäksi myös teknisempi merkitys vastaparissa voimakone vs. työkone=kuormakone, ruotsiksi kraftmaskin=primärmotor vs. arbetsmaskin, ks. SAOB, mutta tämä merkitys ei ole olennainen tässä)

Ilmeisesti voimakone voi tarkoittaa myös höyrykonetta, sekään ei ole tavoiteltu merkitys tässä luokittelussa.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Kraftmaskin ei kovin yleinen termi ruotsiksi.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: voimakone: kone joka muuttaa sähkö-, lämpö- tms. energian mekaaniseksi, tav. pyörimisliikkeeksi. _Sähkö- ja polttomoottori, vesiturbiini ym. voimakoneet._

**Comment by mirmaid** [comment]
Käytetty 83 kertaa Melindassa. Yleensä moottoreista, mutta ei kai ihan aina niin, että kyse olisi pelkästä moottorista tai moottoriksi kutsuttavasta laitteesta. Vähän käytetty kyllä myös suomeksi.

**Comment by ilona-x** [comment]
LCSHssa näköjään sekä engines että sen alakäsitteenä mm. motors:
[Engines](https://id.loc.gov/authorities/subjects/sh85043258)
[Motors](http://id.loc.gov/authorities/subjects/sh85087697)

LCSH:n engines-termillä näyttäisi olevan samantyyppisiä alakäsitteitä kuin YSOn voimakoneilla.

**Comment by ilona-x** [comment]
Huom. YSOssa myös lämpövoimakoneet, jonka eng. termin muutosehdotus käsittelyssä YSO-kokouksessa 2/2022 https://github.com/Finto-ehdotus/YSE/issues/10294

**Comment by YSO-kokous** [comment]
### Päätökset
Selvitetään vielä kuvailukäytön perusteella käsitteen voimakoneet poistamista.
Mikäli poistetaan, niin muutetaan ohjaustermiksi  voimakoneet KÄYTÄ moottorit
Ei muuteta turbiinit hierarkiaa tässä vaiheessa.

**Comment by annamarj** [comment]
Tutkailin vielä asiaa, ja nimenomaan höyrykoneet ja turbiinit mietityttävät. Ainakin ne jäisivät ilman sopivaa termiä, jos tehdään muutos voimakoneet KÄYTÄ moottorit. Vaihtoehtona myös, jos kuvailukäytön huomioiden on ok,  jo Ilonan tuossa mainitsemaan tarkempaan termiin liittyvä EHDOTUS poistaa "voimakoneet", mutta jättää "lämpövoimakoneet". Sen alakäsitteinä näyttää olevan kattavasti niitä voimakoneita, jotka eivät lukeudu moottoreihin. https://github.com/Finto-ehdotus/YSE/issues/10294 (kannatettava ehdotus)

**Comment by ilona-x** [comment]
voimakone löytyy näköjäään myös Wikidatasta/Wikipediasta (linkkaus ei näy jostain syystä näy YSO:ssa):
https://www.wikidata.org/wiki/Q18762500
https://fi.wikipedia.org/wiki/Voimakone

**Comment by ilona-x** [comment]
GND:

Sachbegriff 	**Kraftmaschine**
Synonyme 	
Antriebsmaschine
Kraftmaschinen 
https://d-nb.info/gnd/4032715-2


Sachbegriff 	**Motor**
Synonyme 	Motoren 
https://d-nb.info/gnd/4128006-4

**Comment by mirmaid** [comment]
Voisiko vaan jättää? Aiheutuuko nykytilanteesta joku ongelma?

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
