### ISSUE TITLE
polttokennot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10295]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[polttokennot](http://www.yso.fi/onto/yso/p20139)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Polttokenno ei ole lämpövoimakone, joten yläkäsite tulisi vaihtaa. En tiedä mihin, mutta LCSH antaa joitain vaihtoehtoja.

**Perustelut ehdotukselle**

Polttokenno muuttaa kemiallista energiaa sähköksi, ei lämpöä sähköksi, kuten lämpövoimakone.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/polttokenno
https://fi.wikipedia.org/wiki/Polttokenno
Eli näiden mukaan YK laitteet?
