### ISSUE TITLE
karisma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10290]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[karisma](http://www.yso.fi/onto/yso/p13445)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko rajattavissa psykologiaan/persoonallisuuteen, esim. karismaattisuus (psykologia), tai päätermiksi karisma? 

**Perustelut ehdotukselle**

Ruotsiksi termi on karisma, eikä se voi viitata karismaattiseen kristinuskoon, eli suomenkielisen termin ykkösmerkitykseen: https://www.kielitoimistonsanakirja.fi/#/karismaattinen?searchMode=all  Sanastossa on erikseen karismaattiset liikkeet, voisiko ohjata karismaattisuus (uskonto) käytä karismaattiset liikkeet? Melindassa on nyt käytetty molemmista merkityksistä, uskontomerkityksessä virheellisesti ruotsin osalta. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
^ Varmaan ok? Eli termin muutos > karisma ja ohjaustermi.
