### ISSUE TITLE
teho

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10300]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[teho](http://www.yso.fi/onto/yso/p10712)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa tms. ratkaisu joka toimii kaikilla kielillä?

**Perustelut ehdotukselle**

ALLFO: effekt=teho, effekter=vaikutukset, eli tarkenne on lisättävä ruotsiksi. Eng. power (physics) ja ryhmäkin on 07, mutta Melindassa käytetty myös paljosta muusta, joissakin tapauksissa vaikutuksen merkityksessä. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/teho
https://svenska.se/tre/?sok=effekt&pz=1
Olisiko yksi vaihtoehto lisätä tarkenne (fysik/fysiikka) myös ruotsiksi ja suomeksi, tai mahdollisesti (energia) tms.? Ainakin ruotsiksi voisi sen lisäksi olla myös ohjauksena effekt (verkan) ANVÄND effekter. 

Vai onko jako tarpeen? On kyllä tosi paljon käytetty muusta kuin fysiikasta. Melindassa esim: [Säännöllinen liikunta tehostaa todennäköisesti koronarokotteen vaikutusta.](javascript:open_window("/F/K5I9DDY2NJ4DA8BA8VUU73GYHUBF8HYH6VMQ36S6PJ16K6BNNP-01999?func=service&doc_number=018237367&line_number=0009&service_type=TAG%22);) ; [Efficacy, safety and clinical outcomes of biologic drugs in the treatment of rheumatoid arthritis / Kalle Aaltonen.](javascript:open_window("/F/9YXQ8EQ1F22UYSEVI5XCXDNHGH7IY4E3BLC68LRD91CB7KFRR9-04213?func=service&doc_number=007043997&line_number=0014&service_type=TAG%22);) ; [Sulfonyyliurearesistentin pihatähtimön torjunta ja sen vaikutus ohran satoon ja laatuun / Tuomas Uusitalo.](javascript:open_window("/F/9YXQ8EQ1F22UYSEVI5XCXDNHGH7IY4E3BLC68LRD91CB7KFRR9-02342?func=service&doc_number=006395256&line_number=0011&service_type=TAG%22);) ; [Finn Spring Oy:n Härkänevan tehtaan tuotannon tehostaminen / Aleksi Ali-Haapala ja Teppo Ylikulju.](javascript:open_window("/F/9YXQ8EQ1F22UYSEVI5XCXDNHGH7IY4E3BLC68LRD91CB7KFRR9-01948?func=service&doc_number=006072692&line_number=0011&service_type=TAG%22);) ; [Työsuojelun valvontalain vaikutus työsuojelun viranomaisvalvontaan / Riikka Ruotsala ... [ja muita]](https://melinda.kansalliskirjasto.fi/F/9YXQ8EQ1F22UYSEVI5XCXDNHGH7IY4E3BLC68LRD91CB7KFRR9-01004?func=full-set-set&set_number=006556&set_entry=000180&format=999)
Myös tämäntyyppisiä: Kapitalstruktur och företagets prestanda : en studie på den finska och svenska aktiemarknaden / Alexander Fagerholm.
Yllä olevat kirjoja, artikkeleissa on vielä enemmän käytetty "vaikutuksen" merkityksessä...

**Comment by mirmaid** [comment]
Käytetty 755 kertaa Melindassa. Näyttää olevan joitakin kertoja aika erikoista käyttöä ilmeisesti ruotsinkielen kautta, esim. https://melinda.kansalliskirjasto.fi/byid/014724150, https://melinda.kansalliskirjasto.fi/byid/009587893.

Tuo "vaikutus"-merkitys olisi siis suomeksi teho(kkuus), _vaikutukset_ liittyy enemmän jonkin (erilaisiin) seurauksiin. _Teho (fysiikka)_ ja _tehokkuus_ menisivät varmasti sekaisin.

**Comment by YSO-kokous** [comment]
**Päätös**

Päätermiin _teho_ lisätään tarkenne _teho (fysiikka)_

_Tehokkuus (fysiikka)_ KÄ _teho (fysiikka)_

Teho (vaikuttavuus) KÄ _tehokkuus_ ja _vaikuttavuus_
