### ISSUE TITLE
harjoitusaineistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10307]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[harjoitusaineistot](http://www.yso.fi/onto/yso/p29883)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM-ehdotus: vaihdetaan yläkäsite

**Perustelut ehdotukselle**

Yläkäsite on genresanastossa musiikki, se on liian suppea ja on kuvailijalle hämmentävä (saako käyttää vai eikö, kun on kyse muista harjoituaineistoista kuin musiikki). Asia on käsitelty aikaisemmassa issuessa https://github.com/Finto-ehdotus/YSE/issues/5547 jossa päädyttiin siihen ettei rajata musiikkiaineistoihin. 

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Muusa-kokouksen käsittelyyn. Tarvitaanko mahdollisesti erillinen termi **musiikin harjoitusaineistot**?

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta. LCGFT-linkin tyyppi pitää samalla vaihtaa narrower matchiksi.

Ei tarvita erillistä termiä _musiikin harjoitusaineistot_.

Samalla ehdotetaan muutettavaksi käsitteen _vokaliisit (harjoitteet)_ yläkäsitteeksi _musiikki_.

**Comment by mirmaid** [comment]
SLM-työryhmä kannattaa termin rajaamista musiikkiin, muuten sekoittuu oppimateriaali ja harjoituskirjat -termeihin käytössä.

musiikin harjoitusaineistot / harjoitusaineistot (musiikki)

**Comment by MUUSA-kokous** [comment]
Kannatetaan termin muuttamista muotoon _musiikin harjoitusaineistot_.

**Comment by mirmaid** [comment]
Muutetaan SLM:ssä (linkki exact matchiksi).

YSO-kokoukseen.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan SLM:n mukaisesti.

**Comment by mariaforsen** [comment]
Sv. övningsmaterial för musik
Jfr https://finto.fi/slm/fi/page/s1304
