### ISSUE TITLE
kansallisdiskografiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10308]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kansallisdiskografiat](http://www.yso.fi/onto/yso/p23314)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-sanastoon.

**Perustelut ehdotukselle**

Tarve kansallisdiskografioiden kuvailussa.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

LT diskografiat

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
