### ISSUE TITLE
hydrauliikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10302]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hydrauliikka](http://www.yso.fi/onto/yso/p10545)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermi virtausoppi ohjataan hydrodynamiikkaan

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/virtausoppi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. strömningslära ANV hydrodynamik
