### ISSUE TITLE
ympäristökriisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10309]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ympäristökriisi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

environmental crisis / ecological crisis

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan käsite kuvaamaan laajempaa kokonaiskriisiä, jonka osia ovat esimerkiksi ilmastokriisi, luontokato, sukupuuttoaalto, ekokatastrofit sekä jäte- ja saasteongelmat. Ympäristökriisiä / ekologista kriisiä käsittelevää aineistoa tulee jatkuvasti, mutta sopivaa käsitettä ei ole. Tällä hetkellä käsite ekokriisi ohjautuu käsitteeseen ekokatastrofit, joka taas tarkoittaa aivan eri asiaa: yksittäisiä tulvia, metsäpaloja tai muita paikallisia katastrofeja. Kun taas käsite ympäristökriisi tai ekologinen kriisi viittaa globaaliin, jatkuvaan ja merkittävästi laajempaan kriisiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kriisit](http://www.yso.fi/onto/yso/p6173)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 ekologinen kriisi

**Alakäsitteet (RT)**

 [ilmastokriisi](http://www.yso.fi/onto/yso/p39413)

**Assosiatiiviset (RT)**

 [ilmastokriisi](http://www.yso.fi/onto/yso/p39413), [ekokatastrofit](http://www.yso.fi/onto/yso/p7750)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Ecological_crisis)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Planeetan kokoinen arki: askelia kestävämpään politiikkaan (toim. Senja Laakso & Riikka Aro, Gaudeamus 2022). Ja monessa muussa. 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [ympäristökriisi](http://finto.fi/yse/fi/page/Y510309)

**Comment by vthuhtal** [comment]
-krrisien lisäksäksi YSOssa on jo erilaisia -katoja, -vahinkoja, -tuhoja, -riskejä jne.

Ympäristökriisi voi olla ihan hyvä termi, varsinkin jos sille löydetään jonkinlainen tieteellinen määritelmä termin kattavuuden rajaamiseksi. Samalla pitäisi kuitenkin miettiä uuden termin suhdetta jo olemassa oleviin termeihin, jottei sisällönkuvailusa tarvitsisi käyttää kaikkea mahdollista YSOsta löytyvää.

**Comment by mirmaid** [comment]
Tämän aihepiirin termistöä on tosiaan jo runsaasti, ja tämä sama ehdotus käsiteltiin viimeksi viime vuoden lopulla, https://github.com/Finto-ehdotus/YSE/issues/9722. Issuessa perusteluja ratkaisulle.

**Comment by mariaforsen** [comment]
Ekologinen kriisi ei ole välttämättä sama asia kuin ympäristökriisi.

**Comment by YSO-kokous** [comment]
### Päätökset
Lisätään ohjausterminä
ympäristökriisit KÄYTÄ ekokatastrofit
