### ISSUE TITLE
melodraamat (draama)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10304]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[melodraamat (draama)](http://www.yso.fi/onto/yso/p37992)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan asiasana kahtia tai vaihdetaan LT-suhteeksi paremmin sopiva

**Perustelut ehdotukselle**

On nyt kaksoishierarkia: onko kyse elokuvista vai teatterista? Jos draamasta yleensä, pitäisi LT-suhteen heijastella suoraan sitä.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
YSOssa kuuluu ryhmiin: 87 Kirjallisuus  95 Teatteri. Tanssi  96 Valokuvaus. Elokuva

SLM-sanastossa tehty tietoisesti viittaus molemmista -> 

    melodraamat (elokuvat) KÄ melodraamat (draama) 
    melodraamat (näytelmät) KÄ melodraamat (draama) 

Hyvin sama pätee moniin muihinkin teatterin/elokuvan lajityyppeihin: tapakomediat, tilannekomediat jne. eli voivat kuulua moniin kategorioihin.

**Comment by jtuohini** [comment]
Mutta ei voi olla tuplahierarkiaa, jos termi on joko–tai-tyyppiä: jos sillä tarkoitetaan teatterimelodraamaa, on hierarkiasuhde elokuvaan virheellinen ja toisinpäin. Nyt sanasto antaa ymmärtää, että asiasana tarkoittaa sellaista melodraamaa, joka on yhtäaikaisesti elokuva ja näytelmä, koska jokainen YSO-asiasana perii kaikki LT-suhteisten asiasanojensa ominaisuudet. SLM:ssä ei ole LT–ST-suhdetta ja siksi sillä voidaan kuvailla vapaammin eri taiteenlajien sisälle asettuvia melodraamoja.
