### ISSUE TITLE
ruoko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10301]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ruoko](http://www.yso.fi/onto/yso/p27607)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Rajautuuko vain materiaaliin, ja olisiko siinä tapauksessa päätermi mahdollisesti ruoko (materiaali)?

**Perustelut ehdotukselle**

Ruotsiksi sanastossa on vass, vassar ja bladvass, ja nämä pitää tarkentaa. Lisätään vass > vass (material) jos tämä suomeksikin rajautuu selkeästi materiaaliin? Ks. https://www.kielitoimistonsanakirja.fi/#/ruoko?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Käytetty rakentamiseen ja askarteluun liittyen, lisäksi usein bioenergian ym. raaka-aineena ja jonkun kerran jätevedenpuhdistuksen yhteydessä. Ruokoa voi käyttää myös lannoitteena. Näissä tapauksissa ei varmaan yleensä puhutan materiaaleista vaan raaka-aineista, toisaalta kyseessä on _järviruoko_, joka on myös YSOssa. Ruoko pelkästään ei ole välttämättä tarpeellinen ollenkaan.

**Comment by YSO-kokous** [comment]
### Päätökset
poistetaan käsite "ruoko"
lisätään ohjaustermi 
ruoko KÄYTÄ järviruoko
