### ISSUE TITLE
merikirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10306]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[merikirjallisuus](http://www.yso.fi/onto/yso/p17807)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Asiasanan suomen- ja ruotsinkielinen muoto pitäisi harmonisoida

**Perustelut ehdotukselle**

Suomenkielinen viittaa kirjallisuuteen yleensä, ruotsinkielinen romaaneihin. Liittyy myös LT–ST- ja RT-suhteisiin, niin YSO:ssa kuin SLM:ssä.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
[Kollegalta sähköpostitse tullut vastaaviin muihin liittyvä kommentti:]

Miksi ei ole ’sotaromaanit’-asiasanaa? Sehän on käytetty käsite, käytetympi kuin ’sotakirjallisuus’, joka on kattavampi.

Miksi on kuitenkin ’rakkausromaanit’ eikä ’rakkauskirjallisuus’, joka kylläkin sanana on kauhea. Sillä on yksi alakäsite eli ’historialliset rr:t’. Onhan Suomessa suosittu kirjallisuuden alalaji ns. kaukopartioromaanit, joita minäkin olen tukkukaupalla lukenut. Se voisi hyvin olla ’sotaromaanien’ alalaji.

**Comment by AuHo22** [comment]
Sotakirjallisuus tietenkin kattaa myös sotanovellit ja muut vastaavat kertomukset. Käytetty myös näytelmien yhteydessä.

**Comment by ilona-x** [comment]
Fiktioaineistotyöryhmän & KAUNO-ryhmän käsittelyyn.

Muitakin vastaavia tapauksia, esim. sotaromaanit > sotakirjallisuus.

**Comment by mariaforsen** [comment]
Sanastossa myös: 
poliisikirjallisuus OT poliisiromaanit = polisromaner (voisi olla polislitteratur tai polisfiktion?)
saaristolaiskirjallisuus OT saaristolaisromaanit = skärgårdsromaner
vakoilukirjallisuus OT vakoiluromaanit = spionromaner

Eli nämäkin suomen- ja ruotsinkieliset erot pitäisi varmaan "harmonisoida".

**Comment by AuHo22** [comment]
Joillakin termeillä voi olla pitkä perinne (jo Kitosta lähtien) samoin kuin yleisten kirjastojen kuvailussa. Merikirjallisuus-termiä voidaan kuvailla myös merikertomuksia, kuten 978-952-7211-34-2 tai 978-952-7270-92-9
Olisin sitä mieltä, että muutosten täytyisi olla hyvin perusteltuja, jos niihin lähdetään. Libris ei myöskään ole kovin johdonmukainen asiassa: SAO -> sjöromaner (Sea stories • lcsh, close match) , SAOGF sjöberättelser (variant sjöromaner).

Myös runojakin ehkä: https://nysalor.com/2020/03/10/kuollut-laiva/
Tosiasia on tietenkin, että merikirjallisuus-termiä esim. kirjakaupat näyttävät käyttävän tietokirjallisuudesta. 
Myös wikipedia kiinnittää huomionsa merikirjallisuus-kaunogenren moninaisuuteen https://en.wikipedia.org/wiki/Nautical_fiction

Hyvin vakiintunutta "rakkauskirjallisuutta" puolestaan ovat rakkausrunot erotuksena rakkausromaaneista jne., eli jokainen tapaus täytyisi tarkastella yksitellen, eikä vain "harmonisoinnin" näkökulmasta.

Itse en kuitenkaan vastustaisi esimerkiksi kaukopartioromaanit-termin sanastoon ottamista, joskin yleensä on sitten saatu kuvattua termien kaukopartiot + sissit avulla, jne.

https://yle.fi/aihe/t/18-213299 
https://yle.fi/aihe/t/18-211735
Näissä ainakin yle käyttää samoja käännöksiä kuin slm, enkä koe ongelmalliseksi

**Comment by mariaforsen** [comment]
Eli mistä kaikesta on tarkoitus käyttää merikirjallisuus SLM-terminä? Jos muustakin kuin romaaneista, niin ruotsiksi täytyy tehdä muutoksia.
Melindassa yli 800 kertaa, näyttää olevan lähinnä romaaneja.

**Comment by AuHo22** [comment]
Voisiko tässä ajatella termin merikertomukset-termin käyttöä suomeksi, sv. sjöberättelser? Merikertomukset sointuu suomenkielisen korvaan paremmin kuin meriromaanit ja on myös laajempi käyttöalueeltaan. Muita vastaavia SLM-termejä, joita käytetään kuvaamaan myös romaaneja (vastaavaa -romaanit muotoa ei siis ole olemassa): eläinkertomukset, joulukertomukset, eräkertomukset, Ja tällöin tuskin syntyy sekaannusta tietokirjallisuuteenkaan.

**Comment by mirmaid** [comment]
^ Matkakertomukset on nyt tarkenteella (tietokirjallisuus). Eräkertomusten osalta on ehkä nyt vähän sekavaa, että YSOssa on sekä eräkirjallisuus että eräkertomukset, SLM:ssä eräkirjallisuus on ohjaustermi. 

Jos kaunon ja muistelmatyyppisen aineiston yhdistäminen samaan ei haittaa, merikertomukset on kyllä sikäli hyvä, että ei kata mitä tahansa tietoaineistoa.

**Comment by ghost** [comment]
Kauno-ryhmä kannattaa muutosehdotusta muodossa: merikirjallisuus (kaunokirjallisuus) / sjölitteratur (skönlitteratur)

**Comment by mariaforsen** [comment]
Sjölitteratur ei ole kovin suosittu muoto ruotsiksi, mutta ehkä menettelee paremman puutteessa. https://oula.finna.fi/Record/oy.991847353906252

**Comment by mirmaid** [comment]
Hyväksytään merikirjallisuus (kaunokirjallisuus).

**Comment by mirmaid** [comment]
YSO?

**Comment by YSO-kokous** [comment]
Hyväksytään _merikirjallisuus (kaunokirjallisuus)_.

**Comment by mariaforsen** [comment]
Samanlainen ongelma: saaristolaiskirjallisuus (ei ole YSOssa, joten erillistä ehdotusta ei voi tehdä). Miten ratkaistaan?
