### ISSUE TITLE
tolvstegsprogram [huvudterm]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10313]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kahdentoista askeleen hoito

**Ehdotettu termi ruotsiksi**

tolvstegsprogram [huvudterm]

**Ehdotettu termi englanniksi**

Twelve-step programs

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Behövs vid katalogisering

**Ehdotettu yläkäsite YSOssa (LT)**

 [behandlingsmetoder](http://www.yso.fi/onto/yso/p392)

**Ehdotetut temaattiset ryhmät**

 [55 Psykologi](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [Minnesotamodellen](http://www.yso.fi/onto/yso/p16815)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Twelve-step_program), [LCSH ](https://id.loc.gov/authorities/subjects/sh90000761.html), [SAO](https://id.kb.se/term/sao/Tolvstegsprogram)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Beroendeboken : om olika beroenden och hur man tillfrisknar / Helena Bengtsson.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tolvstegsprogram [huvudterm]](http://finto.fi/yse/fi/page/Y510313)

**Comment by mirmaid** [comment]
Hyvin vähän suomeksi.

**Comment by fantsby-m** [comment]
Suomeksi löytyy 12 askelta, 12 askeleen ohjelma jne. Google-hauilla, esim. AA-konteksteissa.
Myös esim. Duodecimin Käypähoito-sivuilla:
https://www.kaypahoito.fi/nak04632

**Comment by annamarj** [comment]
> Suomeksi löytyy 12 askelta, 12 askeleen ohjelma jne. Google-hauilla, esim. AA-konteksteissa. Myös esim. Duodecimin Käypähoito-sivuilla: https://www.kaypahoito.fi/nak04632

Käsittääkseni "ohjelma" onkin yleisesti käytetty juuri AA-kontekstissa (jossa on pikemminkin oppi/aineisto/ohjenuora kuin hoito).

**Comment by mirmaid** [comment]
AA-kontekstissa vaan taitaa olla vahvasti päällekkäinen _myllyhoidon_ kanssa?

**Comment by YSO-kokous** [comment]
### Päätökset
fi 12 askeleen ohjelma KT kahdentoista askeleen ohjelma   RT myllyhoito
sv tolvstegsprogram
