### ISSUE TITLE
moyamoya-tauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10315]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

moyamoya-tauti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/329710

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [moyamoya-tauti](http://finto.fi/yse/fi/page/Y510315)

**Comment by mariaforsen** [comment]
Sv. moyamoyasjukdom https://mesh.kib.ki.se/term/D009072/moyamoya-disease HT moya-moya /ne

**Comment by ilona-x** [comment]
FinMeSH 
moyamoya-tauti http://www.yso.fi/onto/mesh/D009072

Wikipedia
https://en.wikipedia.org/wiki/Moyamoya_disease

LCSH
Moyamoya disease  http://id.loc.gov/authorities/subjects/sh85088178
