### ISSUE TITLE
keskijohto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10318]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[keskijohto](http://www.yso.fi/onto/yso/p20745)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko oikea yläkäsite johtajat? Viittaako keskijohtajiin, eli olisiko ainakin OT keskijohtajat, vai viittaako jonkinlaiseen toimintaan?

**Perustelut ehdotukselle**

Ruotsiksi mellanchefer, mutta voisi mahdollisesti oikeammin olla "ledning på mellannivå", kuten se on myös esim. JUPOssa: https://finto.fi/jupo/fi/page/p4602 Tämä riippuu tosin siitä että viittaako tämä henkilöihin vai jonkinlaiseen toimintaan. Vrt. yläkäsite johto Jupossa. Eng. nyt middle management. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: Yrityksen keskijohto ylemmän ja alemman johtajiston välinen johto. 
Wikipedia: https://fi.wikipedia.org/wiki/Johtaminen#Johtamisen_ty%C3%B6njako

**Comment by YSO-kokous** [comment]
### Päätökset
keskijohtajat KÄYTÄ keskijohto
