### ISSUE TITLE
Tarvaspää

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10311]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Tarvaspää](http://www.yso.fi/onto/yso/p11080)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi Gallen-Kallelan Museo

**Perustelut ehdotukselle**

"Taiteilija Akseli Gallen-Kallelan (1865–1931) suunnittelema ja rakentama Tarvaspään ateljeelinna avattiin yleisölle vuonna 1961 Gallen-Kallelan Museona." / https://www.gallen-kallela.fi/

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
KANTOssa: https://finto.fi/finaf/fi/page/000037193

**Comment by mirmaid** [comment]
YSAssa huomautus: _Akseli Gallen-Kallelan omien piirustustensa mukaan rakennuttama ateljeetalo Espoossa. Tarvaspäässä on toiminut vuodesta 1961 lähtien Akseli Gallen-Kallela museo_

Tarvaspää on siis otettu YSAan rakennuksena (sillä ei ole yläkäsitettä).

**Comment by YSO-kokous** [comment]
### Päätös
Ei lisätä ohjaustermiä. Museo on yhteisö ja kuuluu Kantoon.
