### ISSUE TITLE
proteaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10319]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

proteaasit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/325428

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [proteaasit](http://finto.fi/yse/fi/page/Y510319)

**Comment by mirmaid** [comment]
AFOssa muodossa _peptidaasit_.

**Comment by mirmaid** [comment]
Melindassa 10 x proteaasit, 3 x peptidaasit.

Lääketieteen termit: _proteiineja hajottavien entsyymien yleisnimi_. 
https://fi.wikipedia.org/wiki/Proteaasi

**Comment by mariaforsen** [comment]
Sv. proteaser, peptidaser /ne
