### ISSUE TITLE
pilkkumäntypistiäinen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10310]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pilkkumäntypistiäinen

**Ehdotettu termi ruotsiksi**

vanlig tallstekel

**Ehdotettu termi englanniksi**

Diprion pini

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melinda x 5

**Ehdotettu yläkäsite YSOssa (LT)**

 [mäntypistiäiset](http://www.yso.fi/onto/yso/p5459)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [AFO](http://www.yso.fi/onto/afo/p3734), [Wikipedia](https://fi.wikipedia.org/wiki/Pilkkum%C3%A4ntypisti%C3%A4inen), [LCSH: Diprion pini](http://id.loc.gov/authorities/subjects/sh87020305)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Insect and storm disturbance in boreal forests : predisposing site factors and impacts on ecosystem carbon 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [pilkkumäntypistiäinen](http://finto.fi/yse/fi/page/Y510310)

**Comment by mariaforsen** [comment]
https://namnochslaktskap.artfakta.se/taxa/261408/details
