### ISSUE TITLE
pussiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10317]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pussiitti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/329279

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pussiitti](http://finto.fi/yse/fi/page/Y510317)

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

säiliöileiitti
pouch ileitis, ”pouchitis” e, reservoarileit ‑en, ”pouchit ‑en” r ark. pussiitti | ileoanaalisen →pussin tulehdus

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Pouchitis

**Comment by mirmaid** [comment]
Ottaisin päätermiksi kuitenkin _pussiitti_, paljon käytetympi kuin Lääketieteen termien muoto.

**Comment by ilona-x** [comment]
FinMeSHistä löytyi tällainen ilmeisesti tätä ehdotettua pussiittia vastaava termi? 

**tyhjäsuolen pussin tulehdus**  http://www.yso.fi/onto/mesh/D019449
Ohjaustermit
    pouchiitti
    pouchitis

englanti    
Pouchitis
Ileitis, Pouch
Pouch Ileitis

ruotsi   
Pouchit

**Comment by mariaforsen** [comment]
Sv. pouchit
