### ISSUE TITLE
juhlajulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10327]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[juhlajulkaisut](http://www.yso.fi/onto/yso/p18076)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään määritelmä, varsinkin SLM-sanastoon.

**Perustelut ehdotukselle**

Todettu Siskun kokouksessa, että termi käytetään nykyään myös laajemmin, ja tarvitaan sen takia selventävä määritelmä. Käsitelty myös Kumeassa, ks. https://www.kiwi.fi/display/kumea/2015-03-26

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Lisätään käyttöhuomautukseksi: "Kun juhlajulkaisun kohteena on yhteisö, genretermi merkitään vain jos julkaisussa on tabula gratulatoria. Muussa tapauksessa käytä esimerkiksi historiikit, järjestöhistoriikit, yrityshistoriikit tai kouluhistoriikit"
SLM-kokous 19.4.2022

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Mielestäni olisi tärkeä saada määritelmä myös YSOon, mutta vähän toisessa muodossa? Jos tarkoitus on sulkea pois sellaiset kuin "80 vuotta voimistelua ja urheilua : Himangan Roima" ; "Veljet Viipurista : Teollisuuden- ja liikkeenharjoittajain Seura Pamaus ry 125 vuotta" jne. Näin on ainakin ruotsiksi, ks. https://svenska.se/tre/?sok=festskrift&pz= https://en.wikipedia.org/wiki/Festschrift

**Comment by mirmaid** [comment]
Tämä on toisaalta varmaan aika harvinainen aiheena - ja vielä vähemmän niin, että käytettäisiin silloin jotenkin villisti (kirja, jonka aiheena olisivat yhteisöjen juhlajulkaisut...)

**Comment by mirmaid** [comment]
Vaatisi aika paljon uudelleenmuotoilua YSOon - "juhlajulkaisulla tarkoitetaan vain henkilöiden juhlajulkaisuja, ja sellaisia yhteisöjen juhlajulkaisuja, joissa on tabula gratulatoria" tai "käytetään vain kuvailtaessa aineistoa, jonka aiheena ovat henkilöiden juhlajulkaisut tai sellaiset yhteisöjen juhlajulkaisut, joissa on tabula gratulatoria" - ei kuulosta suoraan sanoa oikein järkevältä jaottelulta silloin, kun kyse on aiheesta. Voisiko jättää pois kuitenkin YSOn puolella? Toinen vaihtoehto on unohtaa YSOssa tuo tabula gratulatoria ja puhua vain henkilöiden juhlajulkaisuista, mutta tosiaan epäilen, että aineistoja, joissa olisi aiheena yhteisöjen juhlajulkaisut, ei kyllä kovin montaa ole.

**Comment by mariaforsen** [comment]
Ongelma on tosiaan sekin että ruotsiksi festskrifter on "bok vars inne­håll till­ägnas en jubilar i all­mänhet inne­hållande upp­satser skrivna av veder­börandes vänner" /svenska.se

**Comment by mirmaid** [comment]
^ Mikä siinä on siis ongelma? Niin se suomeksikin yleensä on.

Veikkaan että yleensäkin juhlajulkaisut on äärimmäisen harvoin aiheena (tutkimuksen kohteena).

**Comment by mariaforsen** [comment]
Tarkoitan vain että määritelmä olisi ehkä tarpeen YSOssakin, koska nyt näkyy aina välillä että termi on käytetty myös laajemmassa merkityksessä, Melindassa esim.
Veljet Viipurista : Teollisuuden- ja liikkeenharjoittajain Seura Pamaus ry 125 vuotta / Seppo Tamminen 
Matkailututkimuksen juhlakirja : 20 vuotta matkailun opetusta Lapin yliopistossa / toim. Heli Ilola ja Maria Hakkarainen.
Merisotakoulu 52 : RU-kurssi 1965-2015 / Toimituskunta: Kai Masalin, Tapani Somersalo ja Hannu Uski.
Suurin osa nykyisistä YSO-termeistä Melindassa olisivat toki SLM-termeinä 655-kentässä, jos saataisiin korjattua..

**Comment by mirmaid** [comment]
SLM:ssä onkin käyttöhuomautus, ja kun YSO-käsitettä ei enää ole tarkoitus käyttää genre-kentässä, niin tarvitaanko siihen huomautusta - kun huomautus pitäisi kuitenkin muotoilla niin, että se koskee käyttöä aiheena? (tyyliin "Käsitettä käytetään, kun kuvailtavan aineiston aiheena ovat henkilöiden juhlajulkaisut." (Tai, luoja paratkoon, "sellaiset yhteisöjen juhlajulkaisut, joissa on tabula gratulatoria".)

**Comment by YSO-kokous** [comment]
**Päätös**

Ei määritelmää YSOssa.
