### ISSUE TITLE
abolitionismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10324]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

abolitionismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

 abolition

**Tarkoitusta täsmentävä selite**

Abolitionismi (< engl. abolition, 'lakkauttaminen') oli alun perin orjakaupan ja orjuuden lakkauttamista vaatinut protestiliike Isossa-Britanniassa ja Yhdysvalloissa 1700-luvun lopussa ja 1800-luvulla. Liike yhdisti eri uskonlahkoja ja filantrooppisia liikkeitä.
Myöhemmin sanan merkitys on laajentunut muihinkin vapauspyrkimyksiin. ( https://fi.wikipedia.org/wiki/Abolitionismi )

**Perustelut ehdotukselle**

Ilmiötä muuten vaikea ilmaista täsmällisesti. Termi käy kaikkiin vapauspyrkimyksiin. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Abolition. feminism. now 

**Ehdottajan organisaatio**

Kirjastopalvelu/OH
**Termiehdotus Fintossa:** [abolitionismi](http://finto.fi/yse/fi/page/Y510324)

**Comment by mirmaid** [comment]
6 viitettä Melindassa. 
LCSH: Antislavery movements

**Comment by mariaforsen** [comment]
Sv. abolitionism (slaveri) HT antislaverirörelser
SAOssa https://id.kb.se/term/sao/Antislaverir%C3%B6relser

**Comment by YSO-kokous** [comment]
### Päätös
Hyvksytään, mutta lisätään tarkenne, jolla tarkennetaan rajaus vain orjuuteen liittyväksi.
**abolitionismi (orjuus)**
