### ISSUE TITLE
taajuuskorjaimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10321]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taajuuskorjaimet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

equalizers

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 9

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536)

**Vaihtoehtoiset termit**

 ekvalisaattorit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH: Equalizers (Electronics)](http://id.loc.gov/authorities/subjects/sh85044509), [Wikipedia](https://fi.wikipedia.org/wiki/Taajuuskorjain)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Equalizer design for sound reproduction 
http://urn.fi/URN:ISBN:978-952-64-0040-2

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [taajuuskorjaimet](http://finto.fi/yse/fi/page/Y510321)

**Comment by mariaforsen** [comment]
Sv. equalizers HT frekvensmodulatorer
https://sv.wikipedia.org/wiki/Equalizer
https://www.rikstermbanken.se/simpleSearch.html
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_04be4d0485ba8da8fe140a89f25d9356&list_id=1&keyword=taajuuskorjain&word=taajuuskorjain
