### ISSUE TITLE
zarzuelat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10329]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[zarzuelat](http://www.yso.fi/onto/yso/p29802)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Myös SLM-termiksi.

**Perustelut ehdotukselle**

Tarvitaan zarzuelojen kuvailussa. Vastaava termi: https://lccn.loc.gov/gf2016026059

**Ehdottajan organisaatio**

Taideyliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT oopperat

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
