### ISSUE TITLE
varhaisnuoret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10328]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[varhaisnuoret](http://www.yso.fi/onto/yso/p13493)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaihdetaan LT-suhde --> "lapset (ikäryhmät)"

**Perustelut ehdotukselle**

Jos "varhaisnuoret"-asiasana viittaa esiteini-ikäisiin, kuten ruotsin- ja englanninkieliset tuntuvat viittaavan, niin kyse on lapsista.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja lisätään KT-muodot _esiteini-ikäiset_ ja _esiteinit_.

**Comment by mirmaid** [comment]
Nuoret voivat kyllä myös olla lapsia, olisiko sitten tuplahierarkia?

**Comment by jtuohini** [comment]
Mirjan kommenttiin liittyen: riippuu siitä, mitä asiasanalla _nuoret_ tarkoitetaan t.s. kattaako se alaikäisten (eli lasten) lisäksi myös täysi-iän jo saavuttaneita (eli aikuisia).

**Comment by mirmaid** [comment]
^ Täällä jotain: https://fi.wikipedia.org/wiki/Nuoruus

**Comment by mirmaid** [comment]
Ehdotus: lisätään ohjaustermit ja tuplahierarkia.
