### ISSUE TITLE
prosessilouhinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10322]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

prosessilouhinta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

process mining

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [tiedonlouhinta](http://www.yso.fi/onto/yso/p5520), [operaatioanalyysi](http://www.yso.fi/onto/yso/p13475)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553), [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2019102868), [Wikipedia](https://en.wikipedia.org/wiki/Process_mining)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Process Mining Based Influence Analysis for Analyzing and Improving Business Processes http://urn.fi/URN:ISBN:978-952-64-0138-6

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [prosessilouhinta](http://finto.fi/yse/fi/page/Y510322)

**Comment by mariaforsen** [comment]
Sv. processutvinning HT process mining
http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A946487&dswid=-8179
https://www.sitra.fi/sv/nyheter/ny-utredning-i-finland-stiftas-lagarna-bit-for-bit-forsvarar-medborgarnas-mojligheter-att-paverka/
