### ISSUE TITLE
estimointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10339]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[estimointi](http://www.yso.fi/onto/yso/p11349)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT: arviointi (estimointi)

**Perustelut ehdotukselle**

Olisi ehkä hyvä ohjata näin, ettei vahingossa käytetä termiä arviointi=evaluation=utvärdering tähän merkitykseen. 
Ks. https://www.kielitoimistonsanakirja.fi/#/estimoida?searchMode=all 

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Tai arviointi (tilastomenetelmät) KÄ estimointi?

**Comment by mirmaid** [comment]
Ehkä kuitenkin arviointi (estimointi), ettei vahingossa tule muutakin tilastoihin liittyvää ohjatuksi tänne?

**Comment by YSO-kokous** [comment]
### Päätös
arviointi (estimointi) KÄYTÄ estimointi
