### ISSUE TITLE
antirasismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10337]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[antirasismi](http://www.yso.fi/onto/yso/p8643)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

antirasismi ja rasisminvastaisuus eri käsitteiksi

**Perustelut ehdotukselle**

Antirasismi ja rasisminvastaisuus ovat kaksi eri asiaa. Antirasismiin kuuluu esimerkiksi kriittinen rotuteoria mikä taas ei kuulu kaikkeen rasisminvastaisuuteen. 

**Ehdottajan organisaatio**

**Comment by annamarj** [comment]
Ei ole tässä kerrottu perustelua, miten olisivat kaksi eri asiaa, eikä etenkään tuolle "antirasismiin kuuluu kriittinen rotuteoria". Väite ei myöskään oikein mitenkään pidä paikkaansa.

**Comment by YSO-kokous** [comment]
### Päätös
Ei muutosta
