### ISSUE TITLE
Lallinmäki (Akaa)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10338]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Lallinmäki (Akaa)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve aineiston kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [Akaa (kaupunki)](http://www.yso.fi/onto/yso/p215781)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Lallinmäki (Viiala)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [PNR](http://paikkatiedot.fi/so/1000772/10614275)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Muistikuvia Lallinmäestä 1950- ja 1960-luvuilta 

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Kesken!
