### ISSUE TITLE
sikuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10331]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sikuri

**Ehdotettu termi ruotsiksi**

cikoria

**Ehdotettu termi englanniksi**

chicory

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Laji. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533)

**Vaihtoehtoiset termit**

 hyötysikuri

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Laji.fi](https://laji.fi/taxon/MX.39912), [Wikipedia ](https://fi.wikipedia.org/wiki/Sikuri)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Jakobstads cikoria = Pietarsaaren sikuria / [compiled by Lena Serenius] ; [translated by Alasdais Pollock]. Tämänkaltaiset eivät varsinaisesti käsittele sikurikasveja, vaan nimenomaan sikuria. 

**Ehdottajan organisaatio**

ALLFO
**Termiehdotus Fintossa:** [sikuri](http://finto.fi/yse/fi/page/Y510331)

**Comment by mariaforsen** [comment]
Sv. cikoria HT vanlig cikoria, vägvårda
