### ISSUE TITLE
kansalaismedia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10336]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kansalaismedia](http://www.yso.fi/onto/yso/p22028)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarpeen erillisenä? 

**Perustelut ehdotukselle**

Päällekkäisyys käsitteiden "kansalaisjournalismi" ja "sosiaalinen media" kanssa.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. medborgarmedier, joten ok ruotsin osalta jos halutaan poistaa, mutta ei ole mitenkään välttämätöntä (medborgarmedier viittaa itse mediaan, medborgarjournalistik laajempaan ilmiöön)

**Comment by mirmaid** [comment]
Käytetty Melindassa 68 kertaa. 40 samoissa viitteissä sosiaalisen median kanssa ja 14 kertaa kansalaisjournalismin kanssa, mikä ei sinänsä välttämättä tarkoita selkeää päällekkäisyyttä. Toisaalta nyt kun kansalaisjournalismia ei haluttu rajata osallistavaan ammattijournalismiin, on ehkä vähän vaikea hahmottaa, mitä eroa näillä kahdella tavoitellaan. Ainakaan suomeksi ero ei ole kovin selkeä, mutta media on vähän laajempi (journalismi assosioituu kirjoitettuun mediaan) (?).

https://melinda.kansalliskirjasto.fi/byid/011327804 (tässä molemmat termit, kyseessä radio/tv)

**Comment by mirmaid** [comment]
Ehdotus: joko KÄ kansalaisjournalismi, tai jos tarvitaan erikseen tv:tä/radiota varten, pidetään molemmat.

**Comment by nikopartanen** [comment]
Tuo englannin käännös _community media_ ja taas _citizen journalism_ ovat ehkä jotenkin selkeämpiä erottaa toisistaan kuin _kansalaismedia_ ja _kansalaisjournalismi_. Eli onko kansalaismedia esim. paikallisjärjestön tuottamaa mediaa kansalaisjournalismi sitten taas kansalaisten harjoittamaa journalistista toimintaa?

**Comment by LeKorsu** [comment]
Minulle käy tuo KÄ kansalaisjournalismi

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _kansalaismedia_, laitetaan se ohjaustermiksi _kansalaisjournalismille_.

**Comment by AuHo22** [comment]
Vertaismedia ohjaustermi? Esim.

https://www.oamk.fi/opinto-opas/opintojen-sisalto/opetussuunnitelmat?koulutus=vie2019s-jou&lk=s2019&alasivu=opintojakso&oj=M300CB81_fi
