### ISSUE TITLE
itsesäätely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10332]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[itsesäätely](http://www.yso.fi/onto/yso/p14462)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa, esim. itsesäätely (psykologia)? Ja lisättävä ryhmä 55, sekä uusi RT itsehallinta?

**Perustelut ehdotukselle**

Ruotsiksi pitänee vaihtaa päätermiksi självreglering (psykologi) tms. https://www.psykologiguiden.se/psykologilexikon/?Lookup=sj%C3%A4lvreglering Nykyinen självjustering viittaa "laitteiden itsesäätelyyn".  Melindassa itsesäätely on käytetty lähinnä psykologian merkityksessä, eli Kielitoimiston toiseen merkitykseen: https://www.kielitoimistonsanakirja.fi/#/itses%C3%A4%C3%A4tely?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**itsesäätely**
1. vars. biol. eliöiden, populaatioiden ja ekosysteemien kyky sopeutua muutoksiin niin, että niiden olemassaolo voi jatkua.
2. oman toiminnan säätely.

**Comment by ilona-x** [comment]
> uusi RT itsehallinta?
> 

Kannatan RT-suhdetta itsehallinta-termiin, sillä tätä näyttää käytetyn sellaisissa viitteissä, joissa englanniksi self-control.

Litäksi RT-suhde termiin itsesääntely kannattaisi ehkä poistaa, kun nyt on jonkin verran viitteitä, joihin on laitettu molemmat termit. Ja jos ja kun nämä molemmat rajataan tarkenteiden avulla, ei assosiatiivinen suhde näiden välillä oikein enää päde.

**Comment by ilona-x** [comment]
> Onko tarkennettavissa, esim. itsesäätely (psykologia)? 

Melindan viitteet käyty läpi. Viitteitä 392, joista suurin osa psykologian merkityksessä. 

Käytetty kuitenkin myös itsesääntely-merkityksessä:

- Kaikkeen toimintaan tarvitaan kontrollia.
- Économie politique des capitalismes : théorie de la régulation et des crises 
- JNS tukee sananvapautta.
- Tourism impacts, planning and management 
- Mediat itse estävät journalismikritiikin nyky-Virossa.
- Journalistin sananvapaus
- Kriisijournalismia ennen ja nyt.
- Kohti parempia mediaesityksiä :median itsesääntely ja mediakasvatus sananvapauden tukena 
- Oikeutta vai etiikkaa? : viestintäoikeuden vuosikirja 2008.
- Median maku.
- Säätiöiden varojen väärinkäyttö voi johtaa vahingonkorvauksiin.
- Itsesääntely autoteollisuudesssa
- Picturing the public : advertising self-regulation in Sweden and the UK 
- Informaatio tehokkuudesta osana itsesäätelyä yliopistojen laitoksilla /
- The great transformation : the political and economic origins of our time 
- Lex Mercatoria and harmonization of contract law in the EU 
- Julkisesti kriittinen lukija : New York Timesin lukija-asiamies Daniel Okrent.
- Mainonnassa itsesääntely korvaamassa uudet lait
- Hyvän liiketavan mukainen mainonta 
- Julkisen sektorin antimuodikkaat tulosvapaat holistit
- Sananvapaus, joukkoviestintä ja sääntely 
- YK ja poikkikansalliset yritykset : kansainvälisen sääntelyn yrityksistä yritysten yhteiskuntavastuuseen
- Yksityinen ja julkinen sääntely kauppaoikeudessa 
- Mediamuffinssi
- Tapaoikeus oikeuslähdeopissa
- Näkökulmia tietoverkkojen itsesääntelyyn.
- Pelastaako itsesääntely internetin?.
- Yhteissääntely ja itsesääntely 
- Twilight on self-regulation :a sovio-legal evaluation of conservation and sustainable use of agrobiodiversity by industry self-regulation 
- Luottamus uusien sääntelykeinojen edellytyksenä.
- Making global self-regulation effective in developing countries 
- Journalistin sananvapaus 
- Keitetään päätä ja muuta kivaa :mainonnan eettiset arvot, niiden määrittely, ilmeneminen ja ongelmat 

Ja lisäksi vielä sellaisia joissa sekä itsesääntely että itsesäätely, joista jälkimmäinen virheellisesti:
itsesäätely väärin:

- Making global self-regulation effective in developing countries
- Trauma and expressive arts therapy :brain, body, and imagination in the healing process 
- Journalistin lainsäädäntö 
- Suuri murros : aikakautemme poliittiset ja taloudelliset juuret 
- Mikä osa yleisöllä? : viestintäoikeuden vuosikirja 2007
- Den stora omdaningen : marknadsekonomins uppgång och fall

**Comment by ilona-x** [comment]
Seuraavissa Melinda-viitteissä jäi epäselväksi, millaisesta itsesäätelystä on kyse, ja sopisiko niihin itsesäätely (psykologia) tai itsesääntely (tälle myös joku tarkenne):

- Muistitikun tappajat : pilvipalvelut.
- Kybernetiikan kehät : itseohjaavuuden ajatus ja sosiaalisen alue.
- Gaia-hypoteesi kumoutui : Uusin tieto ilmastosta ei tue ajatusta, että planeettaa ohjaisi biologinen "termostaatti"
- Att köpa eller inte köpa : rapport från ett köpstopp
- Incest aversion : the evolutionary roots of individual regulation
- Everybody : a book about freedom

**Comment by ilona-x** [comment]
Ehdotus: rajataan käyttöä tarkenteella **itsesäätely (psykologia)**

**Comment by mirmaid** [comment]
Ei ilmeisesti käytetty Kielitoimiston sanakirjan 1. merkityksessä?

**Comment by ilona-x** [comment]
> Ei ilmeisesti käytetty Kielitoimiston sanakirjan 1. merkityksessä?

Ehkä mahdollisesti tässä yhdessä tapauksessa 🤔 :

Gaia-hypoteesi kumoutui : Uusin tieto ilmastosta ei tue ajatusta, että planeettaa ohjaisi biologinen "termostaatti". 
https://melinda.kansalliskirjasto.fi/byid/013853731

**Comment by YSO-kokous** [comment]
### Päätös
itsesäätely (psykologia)

**Comment by mariaforsen** [comment]
Sv. självreglering (psykologi)
