### ISSUE TITLE
itsesääntely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10333]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[itsesääntely](http://www.yso.fi/onto/yso/p22188)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa, ainakin lisäämällä ryhmiä (ja poistamalla 00), esim. 69, 71, 75? 

**Perustelut ehdotukselle**

Ruotsiksi tarkenne lisättävä, sanastossa on myös itsesäätely. Rajautuuko suomeksi selkeästi tähän: https://www.kielitoimistonsanakirja.fi/#/itses%C3%A4%C3%A4ntely?searchMode=all myös ilman tarkennetta? Melindassa näköjään käytetty vähän muustakin. YSAssa on kyllä ollut huomautus: 
"Itsesääntelyllä tarkoitetaan esim. yritysten toiminnalleen vapaaehtoisesti sopimuksilla asettamia vaatimuksia"

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**itsesääntely**
eril. yhteisöjen ja toimialojen sisäinen, muu kuin julkisen hallinnon määräämä sääntely.
Vähittäiskaupan itsesääntely.
Lehdistön itsesääntely.

**Comment by ilona-x** [comment]
Käytetty Melindassa 111 kertaa, joista n. 16 kertaa virheellisesti. 

Näissä tietueissa sekä itsesääntely että itsesäätely, joista itsesääntely käytetty virheellisesti:

- Kindergarten, sloyd and classroom teacher trainees' self-directed learning, metacognitive regulation and web-based support 
- Itsesäätelyvalmiudet musiikin opiskelussa 
- Is a majority enough? : psychological well-being and its relation to academic and prosocial motivation, self-regulation and achievement at school 
- Nuoren aikuisen psykodynaaminen psykoterapia
- Exploring project-based learning in higher education
- Business coaching itsesäätelyn kehitysinterventiona 
- Korkeakouluopintojen kuormittavuus opiskelijan itsesäätelytaitojen ja opiskeluympäristön suhteena 
- Social kontroll : övervakning, disciplinering och självreglering 
- Tunne nälkä! : syö intuitiivisesti, saavuta tuloksia 
- Känslofällan : ta makten över dina tankar, känslor och ditt beteende 
- Self-preservation in simultaneous interpreting : surviving the role 

Seuraavissa termi itsesääntely, jota käytetty virheellisesti 

- Thermal modelling of water-based floor heating systems : supply temperature optimisation and self-regulating effects 
- Social kontroll och självreglering : hur kontrolleras drickandet? : kamratgrupper i fokus 
- Hurdan inverkan har en aktivitet som kräver självreglering på konsumentens beteende? 

Näissä käytetty itsesääntely, mutta tietueen perusteella ei ihan varmaan, onko käyttö oikein vai väärin:

- Permaculture : principles & pathways beyond sustainability 
- Itseohjautuvuus Venäjän rakennusalalla : liittymisprosessin kuvaus laadullisella menetelmällä

**Comment by ilona-x** [comment]
Myös tälle pitäisi varmaan keksiä tarkenne? Tätä on käytetty yritysten itsesääntelystä ja median itsesääntelystä. Ensimmäisenä tuli mieleen itsesääntely (talous), mutta eihän tuo oikein toimi median/lehdistön osalta. 

Toisaalta tätä käytetty virheellisesti todella vähän, joten riittäisikö, jos tarkenne tulisi vain itsesäätelylle eli itsesäätely (psykologia)?

**Comment by mirmaid** [comment]
^ Ja ohjaus itsesääntely (psykologia) KÄ itsesäätely (psykologia)?

**Comment by ilona-x** [comment]
Ai niin, ruotsiksi itsesäätely & itsesääntely taisi olla täysin sama termi **självreglering**, joten jokin tarkenne pitänee sittenkin tälle keksiä.

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään määritelmä:  
_Eril. yhteisöjen ja toimialojen sisäinen, muu kuin julkisen hallinnon määräämä sääntely.
Vähittäiskaupan itsesääntely.
Lehdistön itsesääntely. Lähde: Kielitoimiston sanakirja._

Ei lisätä tarkennetta: itsesääntely
Ruotsinkieliseen termiin tarvitaan tarkenne.
Poisteaan RT suhde itsesäätelyyn.

**Comment by mariaforsen** [comment]
Sv. självreglering (institutioner)
Anm. Olika institutioners och branschers inre reglering, som inte är styrd av den offentliga förvaltningen.
