### ISSUE TITLE
Vähätkylät (Kruunupyy)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10345]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vähätkylät (Kruunupyy)](http://www.yso.fi/onto/yso/p119314)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vähätkylä - engalnniksi käytettävä ruotsinkielinen nimi Småbönders

**Perustelut ehdotukselle**

Ruotsinkieliset nimet käytetään kansainvälisesti kun kunta on ruotsienemmistöinen

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
