### ISSUE TITLE
havainnekuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10340]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[havainnekuvat](http://www.yso.fi/onto/yso/p8907)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko jotenkin rajattavissa kaavoitukseen/arkktehtuuriin? Tai muuten tarkennettavissa.

**Perustelut ehdotukselle**

Ruotsiksi ja englanniksi 3D-kuvia, mutta ne eivät rajaudu huomautuksen mukaisesti, lisätään mahdollisesti tarkenteita? Ks. Melinda (26 osumaa)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ei varmaan kyllä rajaudu kaavoitukseen/arkkitehtuuriin.

**Comment by mariaforsen** [comment]
Huomautuksena on siis nyt: Kolmiulotteinen kuva, jota käytetään esim. kaavoituksen ja arkkitehtuurin havainnollistamiseen
Joissakin sivuissa käytetty visualiseringsbilder?

**Comment by mirmaid** [comment]
^ Käytetty kuitenkin myös muissa yhteyksissä, ja tuossa huomautuksessa nämä ovat vain esimerkkejä (suurin osa käytöstä on tätä kyllä).

**Comment by mirmaid** [comment]
Eivät välttämättä varmaan kolmiulotteisia:
https://melinda.kansalliskirjasto.fi/byid/007334106
https://melinda.kansalliskirjasto.fi/byid/003584073
https://melinda.kansalliskirjasto.fi/byid/013934993

**Comment by YSO-kokous** [comment]
### Päätös
Tarkistetaan huomautus sekä ruotsin- ja englanninkieliset termit, sillä ei rajaudu 3D kuviin.

**Comment by mariaforsen** [comment]
Englanniksi ei ole näköjään vielä muutettu, on edelleen 3D illustrations.

**Comment by jarmosaarikko** [comment]
Ilmeiesti tämä?
- Wikidatassa:  havainnekuva on "[architectural rendering](http://www.wikidata.org/entity/Q635281)" 
-- wikipedia :  _"Architectural rendering, architectural illustration, or architectural visualization is the art of creating three-dimensional images or animations showing the attributes of a proposed architectural design."_
- https://www.kielitoimistonsanakirja.fi/#/havainnekuva 
Muualla tällaisia "huonoja" vaihtoehtoja
- MOT English tarjoaa "virtual photo"
- Tie- ja liikennesanasto (1985)  havainnepiirros -- "illustration"
