### ISSUE TITLE
pysäköintitilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10341]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pysäköintitilat](http://www.yso.fi/onto/yso/p25074)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko poistettavissa tai tarkennettavissa?

**Perustelut ehdotukselle**

Ruotsiksi parkeringar (områden), eng. parking spaces, mutta sanastossa on myös pysäköintialueet=parkeringsområden, eli yksi niistä pitää ruotsin kannalta poistaa tai tämän päätermi muuttaa (>parkeringshallar? nyt ohjausterminä). Ks. myös pysäköintiluolat, pysäköintipaikat, pysäköintitalot. Pysäköintitilat käytetty Melindassa 26 kertaa. Ks. https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intitila?searchMode=all 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Jos halutaan pitää sanastossa merkityksessä "mikä tahansa rakennettu pysäköintitila" voidaan ruotsiksi laittaa "parkeringslokaler" tai mahdollisesti "parkeringsutrymmen".

**Comment by mirmaid** [comment]
Voi olla että tälle on kyllä tarvetta, koska on myös rakennettuja pysäköintipaikkoja, jotka eivät ole pysäköintitaloja tai -luolia (esim. vain osana rakennusta).

**Comment by mariaforsen** [comment]
Voiko silloin käyttää pysäköintipaikat?

**Comment by mirmaid** [comment]
Voi, mutta se ei ota kantaa siihen, onko kyse rakennuksesta vai ulkoalueesta. Se myös viittaa ihan parkkiruutuihinkin (vaikka kadunvarressa).

**Comment by YSO-kokous** [comment]
### Päätös
Tarkistetaan vieliä käsitteiden yhdistämistä käytön  perusteella.
pysäköintitalot vs. pysäköintihalliit vs. pysäköintiluolat vs. pysäköintitilat
Tarvitaanko määritelmät?

**Comment by ilona-x** [comment]
Esim. JUPOssa näin 

**pysäköintilaitokset** http://www.yso.fi/onto/jupo/p418
ST **pysäköintitalot ja -tilat** http://www.yso.fi/onto/jupo/p417
--ST **pysäköintihallit**  http://www.yso.fi/onto/jupo/p839
----ST **toriparkit** http://www.yso.fi/onto/jupo/p838

**pysäköintipaikat** http://www.yso.fi/onto/jupo/p629

**Comment by ilona-x** [comment]
YSOssa nyt:
[pysäköintialueet](https://finto.fi/yso/fi/page/p13828) Melinda x 302
[pysäköintiluolat](https://finto.fi/yso/fi/page/p27869) Melinda x 6
[pysäköintipaikat](https://finto.fi/yso/fi/page/p13830) Melinda x 181
[pysäköintitalot](https://finto.fi/yso/fi/page/p13829) Melinda x 101
[pysäköintitilat](https://finto.fi/yso/fi/page/p25074) Melinda x 26

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**pysäköintialue** https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intialue
moottoriajoneuvojen pysäköimiseen tarkoitettu alue, paikoitusalue. 

**pysäköintiluola** https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intiluola
luola paikoitustilana. 

**pysäköintipaikka** https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intipaikka
paikoitustila, ”parkkipaikka”. 

**paikoitustalo** https://www.kielitoimistonsanakirja.fi/#/paikoitustalo
lähinnä autojen paikoitustiloja sisältävä monikerroksinen talo, pysäköintitalo, ”parkkitalo”. 

**pysäköintitila** https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intitila
Kadulla ei ollut pysäköintitilaa.

**pysäköintihalli** https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intihalli
moottoriajoneuvojen pysäköimiseen tarkoitettu halli, paikoitushalli.
Tavaratalon pysäköintihalli.

**Comment by mariaforsen** [comment]
Pysäköintitilat on mielestäni eniten päällekkäinen näistä. Ja ruotsiksi nyt aivan päällekkäinen. Olisiko se ainakin mahdollista poistaa (Melindassa vain 27) ? Voisi olla myös ohjaus pysäköintitilat KÄYTÄ pysäköintipaikat ja ehkä pysäköintialueet?

**Comment by mirmaid** [comment]
Myös JUPOn _pysäköintitalot ja -tilat_ tuntuisi aika käyttökelpoiselta, KT pysäköintihallit. Tai sitten pysäköintitilat KÄ _pysäköintitalot, pysäköintihallit_.

**Comment by mariaforsen** [comment]
Eikö pysäköintitilat olisi osittain päällekkäinen erityyppisten pysäköintitilojen, esim. pysäköintiluolat, -paikat jne. kanssa? Kannatan mieluummin pysäköintitilojen ohjaamista tarkempiin termeihin. 
https://www.kielitoimistonsanakirja.fi/#/pys%C3%A4k%C3%B6intitila?searchMode=all

**Comment by mirmaid** [comment]
^ Varmasti, ja pysäköintipaikat on joka tapauksessa päällekkäinen kaikkien muiden kanssa.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _pysäköintitilat_ ja lisätään _pysäköintihallit_.

**Comment by mariaforsen** [comment]
Sv. parkeringshallar HT p-hallar
