### ISSUE TITLE
Friitala (Ulvila)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10348]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Friitala (Ulvila)](http://www.yso.fi/onto/yso/p154135)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vanha ruotsinkielinen nimi Friby

**Perustelut ehdotukselle**

voisi viedä historiallisena tietona

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Lisätty ohjasutermeinä Friby ja Fridaby.
https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=friitala
https://bebyggelsenamn.sls.fi/bebyggelsenamn/2716/friby-ulvsby/
https://kaino.kotus.fi/www/verkkojulkaisut/julk63b/SuomalainenPaikannimikirja_e-kirja_kuvaton.pdf
