### ISSUE TITLE
Isojärvi (Kruunupyy)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10343]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Isojärvi (Kruunupyy)](http://www.yso.fi/onto/yso/p212567)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Enklanniksi Storträsket

**Perustelut ehdotukselle**

Kruunupyyssä on ruotsinkielinen enemmistö miksi kansainvälisesti ruotsinkieliset nimet ovat käytössä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
