### ISSUE TITLE
Kruunupyyn joki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10344]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kruunupyyn joki](http://www.yso.fi/onto/yso/p105140)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kruunupyyn joki - engalnniksi Kronoby å

**Perustelut ehdotukselle**

Ruotsinkieliset nimet käytetään kansainvälisesti kun kunta on ruotsienemmistöinen

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
vrt. https://github.com/Finto-ehdotus/YSE/issues/10352

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
