### ISSUE TITLE
Ansku (Raasepori)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10349]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ansku (Raasepori)](http://www.yso.fi/onto/yso/p508290)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Antskog engalnniksi

**Perustelut ehdotukselle**

Kunnassa on enemmistökieli ruotsi miksi ruotsinkielinen nimi käytetään kansanainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
