### ISSUE TITLE
Aittaluoto (Pori)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10346]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Aittaluoto (Pori)](http://www.yso.fi/onto/yso/p153842)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Bodskär ruotsiksi

**Perustelut ehdotukselle**

Tämän paikan nimi on kyllä ollur Bodskär ruotsiksi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ei löydy tästä https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=aittaluoto mutta joidenkin lähteiden perusteella voisi kyllä laittaa ruotsinkielinen nimi päätermiksi, ks. https://bebyggelsenamn.sls.fi/bebyggelsenamn/2645/bodskar-bjorneborg/
