### ISSUE TITLE
Ruosniemi (Pori)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10347]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ruosniemi (Pori)](http://www.yso.fi/onto/yso/p154144)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Rosnäs

**Perustelut ehdotukselle**

Kotuksen nimilistan mukaan: https://kaino.kotus.fi/svenskaortnamn/?a=abc&b=R

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Korjattu.
