### ISSUE TITLE
Pietarsaaren maalaiskunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10342]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pietarsaaren maalaiskunta](http://www.yso.fi/onto/yso/p94336)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Det svenska namnet Jakobstads landskommun - borde vara Pedersöre 

**Perustelut ehdotukselle**

Jakobstads landskommun har bara funnits i den finska versionen Pietarsaaren mlk för att skilja mellan staden och landsbygden. Däremot har den svenska formen varit Pedersöre för landsbygden och Jakobstad för staden

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Pedersöre är en skild term i ALLFO-orter: https://finto.fi/yso-paikat/sv/page/p105289 och därför kan inte motsvarigheten till Pietarsaaren maalaiskunta vara Pedersöre. Två likadana huvudtermer kan finnas endast om de förses med parenteser som skiljer dem åt. Problemet behandlas på nästa YSO-paikat-möte.

**Comment by mariaforsen** [comment]
Kysymys YSO-paikat -kokoukseen:

Suomalainen paikannimikirja: "Pedersören kunta kunta Pohjanmaalla, ruotsiksi Pedersöre. – Pietarsaaren maalaiskunta, Purmo ja Ähtävä yhdistyivät 1977 ja uusi kunta sai suomenkielisen nimen Pietarsaaren maalaiskunta, ruotsiksi Pedersöre. Kunnan uudeksi suomenkieliseksi nimeksi vahvistettiin 23.2.1989 Pedersören kunta, joka perustuu maalaiskunnan perinteiseen ruotsinkieliseen nimeen Pedersöre. Nimestä ja nimenvaihdosta ks. → Pietarsaari. – PS" /https://kaino.kotus.fi/www/verkkojulkaisut/julk63b/SuomalainenPaikannimikirja_e-kirja_kuvaton.pdf

Kun tämä nimenmuutos on tapahtunut vain suomeksi, niin olisiko mahdollista että tämä ratkaistaisiin yhdistämällä suomeksi kaksi eri nimenmuotoa yhdeksi (seuraaja+edeltäjä)? Vai muuttuiko todella paikka nimenmuutoksen yhteydessä (ja vaatii siten kaksi eri termiä?) Jos kaksi eri termiä todella vaaditaan, niin ruotsiksi voisi yksi ratkaisutapa myös olla tarkenteiden lisäys, mutta asia on hankala siinä mielessä, että Pedersöre on ollut olemassa jo vuosisatoja, eli siinä tapauksessa pitää olla tarkkaan määritelty mihin aikakausiin suomenkieliset termit viittaavat.. Entä suomenkielinen muoto "Pedersören kunta", joka viittaa nimenomaan vuoden 1989 -jälkeiseen Pedersöreen?

**Comment by mirmaid** [comment]
Pedersöre (kommun) ja Pedersöre (landskommun).
