### ISSUE TITLE
Parainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10355]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Parainen](http://www.yso.fi/onto/yso/p94327)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pargas englanniksi

**Perustelut ehdotukselle**

Kunnan enemmistökieli on ruotsi miksi ruotsinkielinen nimi käytetään kansainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Wikidatassa eng. Parainen, wikipedia Pargas.

**Comment by jarmosaarikko** [comment]
Tärkeintä lienee, että kunta itse käyttää englanninkielisillä sivuillaan termiä **Pargas**
Wikidata  http://www.wikidata.org/entity/Q1010550   enLabel **Parainen** --> "Pargas"  tämä on vaihdettu
WIkipedia  https://en.wikipedia.org/wiki/Pargas  **Pargas**
GND https://d-nb.info/gnd/3045722-1  **Pargas**
