### ISSUE TITLE
Pohjanmaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10351]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pohjanmaa](http://www.yso.fi/onto/yso/p94344)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ostrobothnia - engalnniksi

**Perustelut ehdotukselle**

Tätä nimeä käytetään usein kirjallisissa teksteissä, Esim: http://www.kotiinpohjanmaalle.fi/frontpage/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Pohjanmaalla ei nyt wikidata-linkkiä, mutta jos halutaan rajata maakuntaan, sellaista ei taida ollakaan.

**Comment by nikopartanen** [comment]
Tällainen linkki löytyy:

https://www.wikidata.org/wiki/Q5702
