### ISSUE TITLE
Riippi (Teuva)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10354]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Riippi (Teuva)](http://www.yso.fi/onto/yso/p145058)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Rip ruotsiksi

**Perustelut ehdotukselle**

Kotimaisten kielten tutkimuskeskusken listan mukaan

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Korjattu. 
https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=riippi
