### ISSUE TITLE
Malmi (Parainen)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10357]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Malmi (Parainen)](http://www.yso.fi/onto/yso/p108683)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Malmen englanniksi

**Perustelut ehdotukselle**

Kunnan enemmistökieli on ruotsi miksi ruotsinkielinen nimi käytetään kansainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Englanninkieliset nimet tulevat wikidatasta, tätä paikkaa ei ole wikidatassa.
