### ISSUE TITLE
Karkkimala (Mustasaari)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10359]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Karkkimala (Mustasaari)](http://www.yso.fi/onto/yso/p149722)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Karkmo englanniksi

**Perustelut ehdotukselle**

Kunnan enemmistökieli on ruotsi miksi ruotsinkielinen nimi käytetään kansainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Lisätty wikidata-linkitys.
