### ISSUE TITLE
Purokylä (Pedersöre)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10353]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Purokylä (Pedersöre)](http://www.yso.fi/onto/yso/p165175)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Bäckby englanniksi

**Perustelut ehdotukselle**

Kunnan enemmistökieli ruotsi siksi ruotsinkielinen nimi käytetään kansainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://www.wikidata.org/wiki/Q50172907, enkkulabel puuttuu

**Comment by jarmosaarikko** [comment]
wikidata tiedot täydennetty

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa, tässä tapauksessa tiedot korjattu Wikidataan.
