### ISSUE TITLE
Puistomäki (Turku)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10358]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Puistomäki (Turku)](http://www.yso.fi/onto/yso/p508539)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Parkbacken ruotsiksi

**Perustelut ehdotukselle**

Turun karttapalvelujen mukaan

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
^ On ruotsiksi noin.
