### ISSUE TITLE
Pohja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10350]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pohja](http://www.yso.fi/onto/yso/p94342)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pojo englanniksi

**Perustelut ehdotukselle**

Kunnassa on enemmistökieli ruotsi miksi ruotsinkielinen nimi käytetään kansanainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa, tässä tapauksessa tiedot korjattu Wikidataan.
