### ISSUE TITLE
Purmonjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10352]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Purmonjoki](http://www.yso.fi/onto/yso/p112152)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Purmo river englanniksi

**Perustelut ehdotukselle**

Englanniksi voisi kyllä johdonmukaisesti käyttää enlganninkielinen nimi vert. Esse river

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
^ Englanninkieliset nimet tulevat suoraan wikidatasta, niiden muoto ei siis ole YSO-ylläpidon päättämä.

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
