### ISSUE TITLE
sfingolipidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10364]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sfingolipidit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/325855

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [sfingolipidit](http://finto.fi/yse/fi/page/Y510364)

**Comment by mariaforsen** [comment]
Sv. sfingolipider /mesh
