### ISSUE TITLE
Tuovila (Mustasaari)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10360]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Tuovila (Mustasaari)](http://www.yso.fi/onto/yso/p218700)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Toby englanniksi

**Perustelut ehdotukselle**

Kunnan enemmistökieli on ruotsi miksi ruotsinkielinen nimi käytetään kansainvälisesti

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Englanninkieliset nimet näkyvät automaattisesti wikidata-linkkien kautta. Tähän lisätty linkitys, eng. muoto onkin siellä Toby.
