### ISSUE TITLE
parvorokko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10367]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

parvorokko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/324787

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [parvorokko](http://finto.fi/yse/fi/page/Y510367)

**Comment by mirmaid** [comment]
TEROssa ja FinMeSHissä pääterminä _pikkurokko_. Duodecim ja wikipedia _parvorokko_. Googlella parvorokko n. 6700, pikkurokko n. 1600.

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

parvorokko
erythema infectiosum la e r, femte sjukdomen r pikkurokko, viides rokko, viides lastentauti | parvoviruksiin kuuluvan parvorokkoviruksen aiheuttama, etenkin lapsilla esiintyvä lievä infektiotauti, jolle ovat ominaisia mm. suuret punoittavat läiskät etenkin poskissa ja monimuotoinen ihottuma vartalon vatsapuolella ja raajoissa

Ehkä voisi olla "parvorokko" ensisjaisesti (-> FinMeSH-päivitys).

**Comment by mariaforsen** [comment]
SV. erythema infectiosum /ne, mesh HT femte barnsjukdomen, femte sjukan 
https://finto.fi/mesh/fi/page/D016731?clang=sv
