### ISSUE TITLE
varhaisuusenglanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10369]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

varhaisuusenglanti

**Ehdotettu termi ruotsiksi**

tidig nyengelska

**Ehdotettu termi englanniksi**

Early Modern English

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/324666

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [varhaisuusenglanti](http://finto.fi/yse/fi/page/Y510369)

**Comment by mirmaid** [comment]
Sanastossa on keskienglanti ja muinaisenglanti. 

4 viitettä Melindassa.

https://en.wikipedia.org/wiki/Early_Modern_English

**Comment by mariaforsen** [comment]
Sv. tidigmodern engelska, tidig nyengelska..?

**Comment by AuHo22** [comment]
varhaisuusyläsaksa myös YSOssa
