### ISSUE TITLE
yhteistoimintalaki (päätermi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10361]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yhteistoimintalaki (päätermi)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://finlex.fi/fi/laki/alkup/2021/20211333#Lidm45237815778736

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-246-726-3

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [yhteistoimintalaki (päätermi)](http://finto.fi/yse/fi/page/Y510361)

**Comment by mirmaid** [comment]
Eli tämä uutena ja ohjaustermi pois edeltäjältä (tai tarkenteen lisäys siihen).

**Comment by mariaforsen** [comment]
Sv. samarbetslag (2021)
