### ISSUE TITLE
nukleaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10362]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nukleaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/326794

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [nukleaatio](http://finto.fi/yse/fi/page/Y510362)

**Comment by mirmaid** [comment]
GEO-ontologiassa.

8 viitettä Melindassa.

https://fi.wikipedia.org/wiki/Nukleaatio

**Comment by mariaforsen** [comment]
Sv. nukleation HT kärnbildning (kemi och fysik), nukleering

**Comment by ilona-x** [comment]
Ehdotuksessa mainittu väitös näyttää olevan ilmakehätieteiden alalta. Tarvitseeko rajata vai riittääkö yksi nukleaatio?

--

LCSHssa:
[Nucleation](https://id.loc.gov/authorities/subjects/sh85093142)
[Atmospheric nucleation](https://id.loc.gov/authorities/subjects/sh85009286)

--

Tieteen termipankissa:

**fi      nukleoituminen**
en      nucleation

määritelmä
uusien kidealkioiden muodostuminen

huomautus
Käsitesivun ovat kirjoittaneet yhteistyössä FT Aku Heinonen ja FT Elina Lehtonen.

Luokitus: geologia, mineralogia,petrologia
	  
Lähde: Tieteen termipankki 02.02.2022, Geologia:nukleoituminen


**fi      hiukkastuminen**
sv      nukleation
en      nucleation

Luokitus: ilmatiede
	  
Lähde: Tieteen termipankki 02.02.2022, Ilmatiede:hiukkastuminen


--

Tepa antaa monta vastinetta englannin termille nucleation:
mm. ytimen muodostus, kidealkion muodostuminen, pisara-alkion muodostuminen, kiteytyminen, ydintyminen 
https://termipankki.fi/tepa/fi/haku/nucleation

**Comment by mirmaid** [comment]
Ja tärkeimpänä https://fi.wikipedia.org/wiki/Kevytkola_ja_Mentos_-purkaus

**Comment by YSO-kokous** [comment]
### Päätös
Selvitetään vielä onko yksi vai kaksi käsitettä

**Comment by mariaforsen** [comment]
Myös GEOssa: https://finto.fi/geo/fi/page/GTK2015ID2628

**Comment by ilona-x** [comment]
RAMEAU:
 
Nucléation
Chimie https://data.bnf.fr/en/12258147/nucleation/

Nucléation (météorologie) 
Sciences de la Terre https://data.bnf.fr/en/11979681/nucleation__meteorologie_/

**Comment by mirmaid** [comment]
Eikö tässä https://en.wikipedia.org/wiki/Nucleation#Examples_of_the_nucleation_of_fluids_(gases_and_liquids) kyse kuitenkin ole tuosta meteorologian nukleaatiosta? Wikipedian sivulla on siis mielestäni kaikki laajasti käsitelty saman asian ilmenemismuotoina.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Ohjaustermi ydintyminen? 
https://fi.wikipedia.org/wiki/Nukleaatio
https://termipankki.fi/tepa/fi/haku/k%C3%A4rnbildning

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/334208
https://helda.helsinki.fi/handle/10138/332625

**Comment by mirmaid** [comment]
https://www.uef.fi/fi/artikkeli/fm-kimmo-korhonen-vaitos-9122021-uutta-tutkimustietoa-pienhiukkasten-vaikutuksesta-jaapilvien
