### ISSUE TITLE
Skvättan (Maalahti)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10379]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Skvättan (Maalahti)

**Ehdotettu termi ruotsiksi**

Skvättan (Malax)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa
HUOM. Maalahdessa myös toinen Skvättan-niminen saari/luoto

**Ehdotettu yläkäsite YSOssa (LT)**

 [Maalahti](http://www.yso.fi/onto/yso/p94283)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [PNR](http://paikkatiedot.fi/so/1000772/10814224), [Wikipedia: Skvättan (vid Storskäret, Malax)](https://sv.wikipedia.org/wiki/Skv%C3%A4ttan_(vid_Storsk%C3%A4ret,_Malax))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Skvättan : sundombornas forna fiskeläger : 63,13091º N 20,69463º Ö

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Skvättan (Maalahti)](http://finto.fi/yse/fi/page/Y510379)

**Comment by mirmaid** [comment]
Maria selvittää.

**Comment by mariaforsen** [comment]
Toinen näyttää olevan Bergön ulkopuolella ja toinen melko lähellä Storskäret, joten eiköhän riittävän selkeä olisi "Skvättan (Storskäret)" tai "Skvättan (Malax, Storskäret), sitä ei ainakaan voi sekoittaa Bergön lähellä olevaan Skvättaniin.

**Comment by mirmaid** [comment]
Skvättan (Malax, Storskäret)
