### ISSUE TITLE
viheltäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10376]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[viheltäminen](http://www.yso.fi/onto/yso/p30126)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT vihellys

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Ehdotetaan samalla määritelmän ja huomautuksen poistamista.
