### ISSUE TITLE
lehikäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10372]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lehikäiset

**Ehdotettu termi ruotsiksi**

rån (bakverk)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Ohut voitaikinaleivonnainen (https://www.kielitoimistonsanakirja.fi/lehikäinen)

**Perustelut ehdotukselle**

Tarve lehikäisiä/rooneja käsittelevän aineiston kuvailussa, vaan vanhastaan ei sopivaa tarkkaa asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [leivonnaiset](http://www.yso.fi/onto/yso/p2455)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

 roonit

**Alakäsitteet (RT)**

 [vohvelit](http://www.yso.fi/onto/yso/p16617)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q19978986)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/001085740

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [lehikäiset](http://finto.fi/yse/fi/page/Y510372)

**Comment by jtuohini** [comment]
KT-muodoiksi myös _pyöreät roonit_ (= tunnrån) ja _nelikulmaiset roonit_ (= gorån). Nimitysten lähde: Erkki Fredrikssonin kirja Roonit ja vohvelit, s. 10–11.

Ja **vohvelit**-asiasana siis RT-suhteiseksi, ei ST-suhteiseksi. Ellei sitten kaikkia näitä erilaisia koota sen yhteyteen samaan tapaan kuin LCSH:ssa.
