### ISSUE TITLE
tortillat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10375]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tortillat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Meksikolainen tav. maissijauhoista tehty ohut, pyöreä, us. täytettynä tarjottava leipä. 
Kielitoimiston sanakirja

**Perustelut ehdotukselle**

On eri asia kuin wrap.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ruokalajit](http://www.yso.fi/onto/yso/p368)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 978-1-84188-544-5 The tortilla cookbook

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [tortillat](http://finto.fi/yse/fi/page/Y510375)

**Comment by mariaforsen** [comment]
Sv. tortillor
https://svenska.se/tre/?sok=tortilla&pz=1
