### ISSUE TITLE
yleisötilaisuudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10373]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yleisötilaisuudet](http://www.yso.fi/onto/yso/p2109)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "kansanjuhlat" tälle tai vastaavasti vielä paremmin sopivalle asiasanalle

**Perustelut ehdotukselle**

"Kansanjuhlat" on sana, jolla haettaessa olisi hyvä löytyy sitä parhaiten vastaavaa aineistoa. On siinä määrin keskeinen sana, että Kielitoimiston sanakirjassa ei edes selitetä sen merkitystä (https://www.kielitoimistonsanakirja.fi/kansanjuhla)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Mikähän olisi vielä paremmin sopiva asiasana? Yleisötilaisuus ei mielestäni ehkä välttämättä ole kansanjuhla.

**Comment by fantsby-m** [comment]
Omana terminään termin [_juhlat_ ](http://www.yso.fi/onto/yso/p1574)alle? Ja huomautus, joka rajaa käytön kansanjuhliin esim urheilu- tai euroviisuvoittojen (ja vast.) yhteydessä?

**Comment by fantsby-m** [comment]
Toisaalta jos _kansanjuhlat_ olisi ohjausterminä termille _yleisötilaisuudet_, niin eihän se tarkoittaisi että kaikki yleistötilaisuudet olisivat kansanjuhlia vaan että kaikki kansanjuhlat ovat yleisötilaisuuksia.

**Comment by mariaforsen** [comment]
Kannatan erillisenä (folkfester).

**Comment by ilona-x** [comment]
Onkohan tämän termin käyttötarve kuinka suuri, ja millaisia juhlia tällä olisi tarkoitus kuvailla. 🤔 

Melindassa käytetty 2 kertaa:
- Leikit, näytelmät : 1965-1967 
- Ensimmäistä maailmansotaa edeltäneistä kansanjuhlista Huittisissa

YLEllä kansanjuhlat-termillä on kuvailtu hyvin erilaisia tapahtumia, joista osaa ehkä ei mieltäisi mitenkään erityisiksi kansanjuhliksi vaan ihan tavallisiksi yleisötilaisuuksiksi/tapahtumiksi/juhliksi. Toki suurin osa näyttää olevan erilaisia urheiluun liittyviä "kansanjuhlia".
https://yle.fi/aihe/t/18-216264
Mutta mukana myös esim. tällaisia:

- Perinteinen itsenäisyyspäivän juhla perutaan Tampereella, mutta suuren suosion saaneet valot tulevat taas koristamaan rakennuksia
- Rovaniemen Ounaskosken uimarannan juhannusjuhla jää väliin - kulttuurituottaja Roosa Nevala: "Tehdään ensi vuonna, kun toivottavasti eletään erilaista aikaa"
- Imatralla ei oteta koronariskiä – Imatra-päivä on peruttu
- Jyväskylän Valon kaupunki houkutteli yli 100 000 kävijää
- Mitä joulu merkitsee uskonnottomalle? "Tämänkin kansanjuhlan kirkko on ominut itselleen"
- Kaupunkilaisen mieli metsään tekevi – Jukolan jättiläinen tulee yllättäen Helsingistä

**Comment by mirmaid** [comment]
Mulle ei tullut urheilupuoli lainkaan mieleen, vaan enemmän just vappu, juhannus yms.

**Comment by YSO-kokous** [comment]
### Päätökset
Ei lisätä ohjaustermiä.
