### ISSUE TITLE
Medusa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10378]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Medusa](http://www.yso.fi/onto/yso/p5466)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään sulkutarkenne "(tietokoneohjelma)" tms.

**Perustelut ehdotukselle**

Termiä on käytettä väärin Meduusaa käsittelevässä aineistossa, esim. kirjan Medusa: in the Mirror of Timessa. On myös sekaantumisvaara "meduusat"-asiasanaan.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Samaista asiasanaa käytetty väärin myös valaisimesta artikkelin _Ohoh, lamppu elää (huonekalu- ja valaisinsuunnittelija Mikko Paasasen kuitu-ja ledtekniikkaa hyödyntävä Medusa-valaisin)_ yhteydessä!

**Comment by jarmosaarikko** [comment]
Ehdotan käsitteen Medusa (p5466) poistamista YSOsta.  Melindassa vain yksi viite ko. ohjelman käyttöoppaaseen vuodelta 1987.

Sanastoon voisi kuitenkin lisätä uuden käsitteen, sillä tähän liittyviä aineistoja löytyy ja väärin käyttö liittyy tähän.
**Medusa (taruolennot)**   sv,en: Medusa (Gorgon)

- https://fi.wikipedia.org/wiki/Medusa
- https://sv.wikipedia.org/wiki/Medusa
- http://www.wikidata.org/entity/Q160730
- http://id.loc.gov/authorities/names/no2019169628 Medusa (Gorgon)

esim. https://melinda.kansalliskirjasto.fi/byid/007026006
vapaana asiasana "Meduusa (taruhahmo)" - 8 viitettä; Medusa (Gorgon) 5 viitettää;

**Comment by jtuohini** [comment]
Taruhahmo on menossa jossain vaiheessa Kantoon, kuten (tarpeen mukaan) kaikki muutkin todelliset ja fiktiiviset henkilöt. KK:ssa on valmisteilla ohje tällaisten kuvailusta.

**Comment by mirmaid** [comment]
Poistetaan käsite?
