### ISSUE TITLE
Suojärvi (Mikkeli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10374]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Suojärvi (Mikkeli)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
esimerkkiaineistossa oli käytetty YSO-paikoista löytyvää Suojärvi-termiä, joten se vaatinee tarkenteen? http://www.yso.fi/onto/yso/p105450

HUOM. Mikkelissä myös toinen Suojärvi-niminen järvi!

**Ehdotettu yläkäsite YSOssa (LT)**

 [Mikkeli](http://www.yso.fi/onto/yso/p94289)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [PNR](http://paikkatiedot.fi/so/1000772/10388389)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Suojärven hajakuormitusselvitys 1993

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Suojärvi (Mikkeli)](http://finto.fi/yse/fi/page/Y510374)

**Comment by mirmaid** [comment]
Suojärvi (Mikkeli, Otava)

**Comment by mirmaid** [comment]
Tässä puuttuu vielä tarkenne luovutetulle kunnalle: http://www.yso.fi/onto/yso/p105450

**Comment by mirmaid** [comment]
Lisätään toistaiseksi tarkenne (kunta), mutta tehdään myöhemmin linjaus luovutettujen kuntien käsittelystä.
