### ISSUE TITLE
People's Republic of China

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10377]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[People&#039;s Republic of China](http://www.yso.fi/onto/yso/p104984)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englanninkielinen ohjaustermi China olisi paikallaan

**Perustelut ehdotukselle**

People's Republic of China on kovin kömpelö.

**Ehdottajan organisaatio**

KK

**Comment by jarmosaarikko** [comment]
Ohjaustermi on paikallaan.

People's Republic of China 
KT Kiinan kansantasavalta   - tämä on virallinen nimi
UF China   
vs. 
Taiwan  
KT Kiinan tasavalta  
UF Republic of China  -  tämä on virallinen nimi ja Taiwan epävirallinen (toistaiseksi).

Periaatteellista estettä ei ole vaikka Kiinan päätermin vaihtamiselle, vaikka se voi olla poliittisesti arka asia.  
Lisäksi voi tarkastella myös seuraavia:
- http://id.loc.gov/vocabulary/countries/cc "China"
- http://id.loc.gov/vocabulary/countries/ch "China (Republic : 1949- )"
- http://id.loc.gov/vocabulary/geographicAreas/a-ch "Taiwan" UF Formosa
- http://id.loc.gov/vocabulary/geographicAreas/a-cc "China" UF Mainland China, People's Republic of China
- Wikipedia: [Kiinan tasavalta (1912–1949)](https://fi.wikipedia.org/wiki/Kiinan_tasavalta_(1912%E2%80%931949)) - http://www.wikidata.org/entity/Q13426199

**Comment by mirmaid** [comment]
Englanninkieliset muodot tulevat Wikidatasta.
