### ISSUE TITLE
tieteenhistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10388]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tieteenhistoria](http://www.yso.fi/onto/yso/p16328)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSAssa tällä on ollut huomautus, onko edelleen ajankohtainen?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
On ajankohtainen! Menee muuten pahasti sekaisin **oppihistoria**-asiasanan kanssa.

**Comment by mirmaid** [comment]
Huomautus siis: _Tarkoittaa tieteen historiaa ja kehitystä yleensä. Yksittäisten tieteenalojen historioista käytä oppihistoria._

**Comment by fantsby-m** [comment]
Tuo huomautus selkiyttäisi sanastoa, mutta selkiyttäisikö myös käyttöä? Verkossa ja jopa yliopistoissa käyttö on hyvin moninaista, termejä _tieteenhistoria_, _tieteen historia_, _oppihistoria_ ja _aatehistoria_ käytetään ristiin ja päällekkäin.

**Comment by mariaforsen** [comment]
Vetenskapshistoria on ainakin laajempi käsite kuin aikaisempi YSA-huomautus antaa ymmärtää. En kannata vanhaa YSA:n huomautusta, olisiko ihan tarkoituksellakin poistettu?
Nationalencyklopedin: "historisk disciplin som studerar vetenskapens, särskilt naturvetenskapens, utveckling.Den innefattar såväl enskilda discipliners historia som den samlade vetenskapens betydelse och samband med världsbild och samhällsutveckling." 
Vanhan YSA-huomautuksen ohjaus oppihistoriaan ei myöskään oikein täsmää ruotsiksi (lärdomshistoria). Ks. myös https://sv.wikipedia.org/wiki/Id%C3%A9historia
https://agricolaverkko.fi/review/kiinnostava-johdatus-aate-ja-oppihistoriallisen-tutkimuksen-perusteisiin/

**Comment by mirmaid** [comment]
^ En usko että on tarkoituksella poistettu, vaan suuri osa on jäänyt alun perin pois YSOsta. Jälkimmäisessä linkissä yhdistetään oppihistoria ja tieteenhistoria, ensimmäisessä aatehistoria ja oppihistoria 🤔

**Comment by YSO-kokous** [comment]
### Päätös
Ei lisätä huomautusta.
