### ISSUE TITLE
sotilashallinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10385]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sotilashallinto](http://www.yso.fi/onto/yso/p20835)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tällä on YSAssa määritelmä, pitäisikö olla edelleen?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
YSA: _Tarkoittaa sotilasviranomaisten hoitamaa hallintoa. Sotavoimien hallinnon yhteydessä käytä puolustushallinto_

**Comment by mirmaid** [comment]
Ehdotus: lisätään huomautus.
