### ISSUE TITLE
Irlanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10389]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Irlanti](http://www.yso.fi/onto/yso/p105195)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "Irlannin tasavalta" sekä otetaan YSO-paikkoihin oma asiasanansa Irlannin saarelle (Wikidata-siltaus https://www.wikidata.org/wiki/Q22890)

**Perustelut ehdotukselle**

Irlannin tasavalta ja Pohjois-Irlanti ovat hallintoalueita, Irlanti saarena taas varsinainen maantieteellinen alue

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
eli tässä samankaltainen tapaus "saari vs. valtio" kuin **Kypros** #9369

**Comment by mirmaid** [comment]
Jaottelu ei ehkä palvelisi käyttäjää/kuvailijaa parhaalla mahdollisella tavalla.
