### ISSUE TITLE
kilpailukiellot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10383]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kilpailukiellot](http://www.yso.fi/onto/yso/p22830)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne?

**Perustelut ehdotukselle**

Käytetty Melindassa muustakin kuin urheilusta.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
YSA: _Käytetään urheilun yhteydessä. Juridiikan yhteydessä käytä kilpailunrajoitukset_

**Comment by mirmaid** [comment]
Esim.
kilpailukiellot (urheilu)
kilpailukiellot (kilpailunrajoitukset tai jokin havainnollisempi tarkenne) KÄ kilpailunrajoitukset

**Comment by mariaforsen** [comment]
Ruotsiksi onkin tävlingsförbud, ja sitä ei voi käyttää muissa merkityksissä kuin urheilussa yms.

**Comment by YSO-kokous** [comment]
### Päätökset
LIsätään tarkenteet.
