### ISSUE TITLE
jaloittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10387]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[jaloittelu](http://www.yso.fi/onto/yso/p24850)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSAssa huomautus. Käytetty Melindassa 9 kertaa, kerran ihmisistä.

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
YSA: _Käytetään eläinten yhteydessä_

**Comment by mariaforsen** [comment]
Ruotsiksi rastning (aina eläinten yhteydessä)

**Comment by mirmaid** [comment]
Pitäisikö lisätä jopa tarkenne?

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään tarkenne: jaloittelu (eläimet)
