### ISSUE TITLE
levyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10381]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[levyt](http://www.yso.fi/onto/yso/p13827)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitaanko YSAn huomautusta tai ohjaustermiä levyt (äänilevyt) KÄ äänilevyt?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Ohjaustermi äänilevyille, vai peräti molemmat?

**Comment by YSO-kokous** [comment]
**Päätös**

Ehdotuksen mukaan.
