### ISSUE TITLE
inkerikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10386]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[inkerikot](http://www.yso.fi/onto/yso/p20725)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kaipaako edelleen YSAssa ollutta määritelmää?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Tuskin haittaisi selitys, kun mennee muuten helposti sekaisin Inkerinmaan savakoiden ja äyrämöisten kanssa.

**Comment by mirmaid** [comment]
YSA: _Inkerikot ovat Inkerin alkuperäistä itämerensuomalaista väestöä. Tarkoitettaessa Suomesta aikoinaan Inkeriin siirtyneitä suomalaisia käytä inkeriläiset_

**Comment by jtuohini** [comment]
Inkeriläiset siis koostuvat pääasiassa savakoista (Savon suunnalta muuttaneista suomalaisista) ja äyrämöisistä (Äyräpään kihlakunnan alueelta muuttaneista suomalaisista), joilla oli Venäjän keisarikunnan kansalaisuus, samoin kuin tuoreempana kerrostumana lisäksi myös ambulanteista (Pietarin kuvernementin niistä suomenkielisistä maanviljelijöitä, joilla oli Suomen suuriruhtinaskunnan kansalaisuus).

**Comment by AuHo22** [comment]
Kannatan huomautuksen lisäämistä YSOon. Tarvitseeko täydennystä - ovat yleensä olleet ortodokseja siinä missä inkeriläiset luterilaisia. (Puhuvat/puhuivat inkeroisen kieltä siinä missä jälkimmäiset inkerinsuomea)

**Comment by nikopartanen** [comment]
Inkeriläiset ja inkerikot menevät niin laajalti sekaisin kaikkialla, että täydennys on varmasti hyödyllinen.

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään huomautus .
Inkerikot ovat Inkerin alkuperäistä itämerensuomalaista perinteisesti inkeroisen kieltä puhuvaa väestöä. Tarkoitettaessa Suomesta aikoinaan Inkeriin siirtyneitä suomalaisia käytä inkeriläiset.

Lisätään vastaava huomautus myös inkeriläisiin.
