### ISSUE TITLE
emigranttikirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10384]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[emigranttikirjallisuus](http://www.yso.fi/onto/yso/p20922)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSAssa tällä on ollut määritelmä, pitäisikö edelleen olla?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
YSA: _Tarkoittaa emigranttien kirjoittamaa kirjallisuutta. Käytetään lähinnä historiallisissa yhteyksissä, muissa tapauksissa käytä pakolaiskirjallisuus. Emigrantilla tarkoitetaan henkilöä, joka uskonnollisista tai poliittisista syistä on joutunut jättämään kotimaansa_

**Comment by mariaforsen** [comment]
Yllä oleva huomautus erittäin ongelmallinen ruotsin kannalta. 
SAOssa https://id.kb.se/find?q=emigrantlitteratur ja huomautuksena ruotsiksi pätevä: "...skildringar av förhållandena i det nya landet av personer som frivilligt har utvandrat, t.ex. av svenskar i Nordamerika." Eli ruotsin kannalta ei ole mahdollista rajata pelkästään uskonnollisista tai poliittisista syistä muuttaneihin.

**Comment by mirmaid** [comment]
Sama huomautus on myös SLM:ssä. Jos halutaan käsitellä _emigranttikirjallisuus_-termiä laajemmin (määritelmän tarkentamista tai termin poistoa), varmaan aloitetaan KAUNO-kokouksesta > SLM-kokous. Itse _emigrantit_-käsitteen käsittely puolestaan kuuluu YSOon. 

Emigranttikirjallisuus Melindassa 214 kertaa YSO, 50 kertaa SLM. 
Emigrantit 1789 kertaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _emigrantit_, käytetään _pakolaiset_ tai _siirtolaiset_. _Emigrantit_ näille ohjaustermiksi.

**Comment by mirmaid** [comment]
_Emigranttikirjallisuus_ KAUNO ja SLM -ryhmien käsittelyyn.

**Comment by mariaforsen** [comment]
Sanastossa on siis myös siirtolaiskirjallisuus=migrantlitteratur ja pakolaiskirjallisuus=exillitteratur.

**Comment by mirmaid** [comment]
Poistetaan/SLM.

**Comment by mirmaid** [comment]
Ehdotus: tehdään vastaava yhdistäminen YSOssa.
