### ISSUE TITLE
ruokalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10395]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ruokalat](http://www.yso.fi/onto/yso/p26639)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "kanttiinit" tai jos sen koetaan viittaavaan ennemmin rajatusti kenttäkeittiöön tms, niin otetaan omaksi asiasanakseen

**Perustelut ehdotukselle**

Ruokaloita nimitetään ainakin puhekielessä myös kanttiineiksi. Lisäksi Melindassa on useita julkaisuja, joiden otsikossakin sana esiintyy mainitussa merkityksessä, ja Finna-aineistoissa on yli 1 800 kuvaa, joiden metatiedoissa esiintyy sana kanttiini.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Vai KT-muodoksi myös asiasanoille **kahvilat** ja **ravintolat** ja ehkä muillekin?

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: kanttiini: varuskunta- t. rintama-alueella sijaitseva pieni (kahvi- ja virvoke)myymälä; vastaavanlainen sairaalan, leirin tms. (kiertävä) myymälä.

**Comment by mirmaid** [comment]
Vähän huonosti ehkä sopii ohjaustermiksi millekään mainituista, koska vain pieni osa ruokaloista, kahviloista ja ravintoloista olisi kanttiineja, jolloin kanttiinit-haku toisi paljon viitteitä, joissa ei ole kyse niistä. Toisaalta ongelmallinen myös itsenäisenä terminä, koska merkitys on vähän epämääräinen. Ei Melindassa.

**Comment by YSO-kokous** [comment]
### Päätös
Keskustelussa ehdotettiin kanttiinit lisäämistä omana käsitteenään. Tutkitaan FInnan aineistostia kattaako vain sotilaskantiinit. 
Esimerkiksi:  **kanttiinit**   KT sotilaskanttiinit
Määritelmä voisi olla kielitoimiston mukaisesti.
TOdetaan, että nykyään käytetään muita termejä.

Tarkistetaan "ruokalat" käsitteen englanninkielinen termi. Esim. "cafeteria".

**Comment by mirmaid** [comment]
^ Finnassa laajemmin, kaiken kaikkiaan 17 kertaa.

**Comment by mirmaid** [comment]
Jospa jättäisi tilanteen nykyiselleen?

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
