### ISSUE TITLE
konsolipelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10398]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[konsolipelit](http://www.yso.fi/onto/yso/p21628)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ainakin SLM:ssä yhdistetään "konsolipelit" ja "videopelit" samaksi

**Perustelut ehdotukselle**

Konsoli- eli videopelejä pelataan pelikonsolilla ja SLM:n näkökulmasta ei ole mielekästä tehdä niiden välille eroa. Tietokonepelit ovat asia erikseen.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Kommentti meiltä: " On ollut pitkäaikainen tapa merkitä molemmat, mutta jos siitä luovutaan niin toivottavasti konsolipelit on jatkossa se termi mitä käytetään."

**Comment by ilona-x** [comment]
käsitelty YSA-kokouksessa v. 2017:  
konsolipelit #5268

**Comment by ilona-x** [comment]
video games https://id.loc.gov/authorities/subjects/sh85143202.html

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Digitaalinen_peli
https://fi.wikipedia.org/wiki/Videopeli
https://fi.wikipedia.org/wiki/Tietokonepeli

**Comment by mirmaid** [comment]
Kysytään yleisten kirjastojen pelivastaavilta, onko videopelit määriteltävissä niin, että se ei näytä olevan täysin sama asia kuin digitaaliset pelit.

**Comment by mariaforsen** [comment]
Ruotsinkielinen wikipedia: "Datorspel (dator-spel), i viss utsträckning även dataspel (data-spel), tidigare kallat videospel"
SAOssa on vain yksi termi https://id.kb.se/term/saogf/Datorspel

**Comment by mirmaid** [comment]
Yhdistetään, päätermiksi konsolipelit. Videopelit KÄ konsolipelit, digitaaliset pelit.

**Comment by mirmaid** [comment]
YSO?

**Comment by YSO-kokous** [comment]
Yhdistetään ehdotuksen mukaisesti.
