### ISSUE TITLE
Mayo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10390]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mayo](http://www.yso.fi/onto/yso/p164659)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCNAF/LCSH-asiasanastoon: http://id.loc.gov/authorities/names/n80149077

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja toiseksi siltaukseksi sama hierarkkisessa muodossa eli http://id.loc.gov/authorities/names/n80149077-781

**Comment by jarmosaarikko** [comment]
Voisiko ohjausterminä olla myös Mayon kreivikunta - https://fi.wikipedia.org/wiki/Mayon_kreivikunta, Tällöin huomautuksen voisi poistaa?
