### ISSUE TITLE
kellopeli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10396]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kellopeli

**Ehdotettu termi ruotsiksi**

klockspel

**Ehdotettu termi englanniksi**

glockenspiel

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Finnassa nyt aineistoja, jotka kuvailtu väärin toisen soittimen nimellä, ja jos metatiedot halutaan korjata, täytyy saada asianmukainen termi sanastoon.

**Ehdotettu yläkäsite YSOssa (LT)**

 [lyömäsoittimet](http://www.yso.fi/onto/yso/p441)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 metallofon [swe], metallofon [fin], metallophone [eng]

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85055309), [Wikidata](https://www.wikidata.org/wiki/Q626035)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/hkm.HKMS000005%3Akm0000ncpe ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kellopeli](http://finto.fi/yse/fi/page/Y510396)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by jtuohini** [comment]
Ja suomeksi KT-muoto siis _metallofoni_ (loppu-I oli kadonnut ehdotuksesta).

**Comment by mariaforsen** [comment]
Sisältyykö tämä https://fi.wikipedia.org/wiki/Carillon suomeksi? Ruotsiksi klockspel voi viitata myös tähän.

**Comment by jtuohini** [comment]
Marian mainitsema on käsitelty esimerkiksi Seko-sanastossa erillään (http://urn.fi/urn:nbn:fi:au:seko:00185; vrt. käsilläolevan asiasanaehdotuksen kellopeli: http://urn.fi/urn:nbn:fi:au:seko:00487). Ei siis ole tarkoitus sisältyä YSO:nkaan puolella.

**Comment by mariaforsen** [comment]
Näyttää siltä että tarkenne olisi tarpeen molemmilla kielillä: https://www.kielitoimistonsanakirja.fi/#/kellopeli?searchMode=all

**Comment by jtuohini** [comment]
Ja siis on kolmaskin soitin, johon tuo Kielitoimiston sanakirja samassa yhteydessä viittaa: putkikellot (http://urn.fi/urn:nbn:fi:au:seko:00811)

**Comment by MUUSA-kokous** [comment]
Tarkennetta ei tarvita suomenkieliseen termiin. Soittimet erottuvat ilmankin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään määritelmä SEKOsta.

**Comment by mariaforsen** [comment]
Sv. klockspel (slaginstrument)
