### ISSUE TITLE
Galway

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10394]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Galway](http://www.yso.fi/onto/yso/p508105)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCNAF/LCSH-asiasanastoon: http://id.loc.gov/authorities/names/n81112107 ja http://id.loc.gov/authorities/names/n81112107-781

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSO-paikoilla ei ole toistaiseksi LCSH-linkityksiä.
