### ISSUE TITLE
Ulster

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10392]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ulster](http://www.yso.fi/onto/yso/p165674)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCNAF/LCSH-asiasanastoon: http://id.loc.gov/authorities/subjects/sh85139457

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSO-paikoilla ei ole toistaiseksi LCSH-linkityksiä.
