### ISSUE TITLE
hummus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10399]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hummus

**Ehdotettu termi ruotsiksi**

hummus

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan hummus-reseptejä sisältävän keittokirjan kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Malin & Nimrod Regev: Hummus 978-91-27-17711-6

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [hummus](http://finto.fi/yse/fi/page/Y510399)

**Comment by jarmosaarikko** [comment]
- http://www.wikidata.org/entity/Q241987 
- https://fi.wikipedia.org/wiki/Hummus
- ei löydy LCSH:sta
