### ISSUE TITLE
Aransaaret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10391]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Aransaaret](http://www.yso.fi/onto/yso/p179356)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCNAF/LCSH-asiasanastoon: http://id.loc.gov/authorities/names/n80082472 ja http://id.loc.gov/authorities/names/n80082472-781

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSO-paikoilla ei ole toistaiseksi LCSH-linkityksiä.
