### ISSUE TITLE
langaton sähköinen kaupankäynti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1040]
#### Ehdotettu termi suomeksi

langaton sähköinen kaupankäynti
#### Ehdotetut ohjaustermit

langaton kaupankäynti, mobiilikauppa
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 13.01.2004

**Muokkauspäivämäärä:** 31.8.2004, 3.8.2006, 13.1.2004, 13.1.2004, 16.12.2008

**Voyager-id:** 128936

**Termiehdotus Fintossa:** [langaton sähköinen kaupankäynti](http://finto.fi/yse/fi/page/Y328936)

**Comment by mirmaid** [comment]
Finto-feedback 26.1.2017: Ehdotan ysaan termiä MOBIILIKAUPPA. Se tarkoittaa älypuhelimilla tapahtuvaa verkkokauppaa.

**Comment by mirmaid** [comment]
Melindassa kerran muodossa _langaton kaupankäynti_.

YSAssa on _mobiilimarkkinointi_, mutta _verkkomainonta, verkkokauppa_ ja _verkkomaksaminen_.

LIITOssa on _mobiilikauppa_ ja _mobiilimaksaminen_ (mutta _mobiilimarkkinointi_ KÄ _suoramarkkinointi_).

**Comment by mirmaid** [comment]
LCSH: Mobile commerce
https://en.wikipedia.org/wiki/Mobile_commerce

**Comment by mariaforsen** [comment]
Ruotsiksi mahdollisesti "mobil handel".

**Comment by mirmaid** [comment]
Hyväksytty mobiilikauppa (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
mobil handel 
ET m-handel
ET mobil e-handel
ET mobilhandel
