### ISSUE TITLE
machine learning

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10409]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[machine learning](http://www.yso.fi/onto/yso/p21846)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

For frame-level variance identification and multi-label classification of heterogeneous colon illnesses in VCE data, the authors presented a novel pathology-sensitive deep learning (Mohammed, Farup et al. 2020). The key inclusion is motion estimation error, with only robust motion estimation being employed to estimate the intensity of the intermediate frame (Mohammed, Farup, Pedersen et al. 2018).  Due to low image quality in the WCE image area, there are at least two fundamental challenges with medical image classification and prediction. This means that sample datasets are so short that we cannot extract enough information to extract discriminative features private security of the patients (Dodge, Karam Jun 2016). The enhancements of CLAHE and gamma correction have been proposed, however they have had no effect on improving detection accuracy (Mohammed, Farup, Yildirim et al. 2018). 

**Perustelut ehdotukselle**

For frame-level variance identification and multi-label classification of heterogeneous colon illnesses in VCE data, the authors presented a novel pathology-sensitive deep learning (Mohammed, Farup et al. 2020). The key inclusion is motion estimation error, with only robust motion estimation being employed to estimate the intensity of the intermediate frame (Mohammed, Farup, Pedersen et al. 2018).  Due to low image quality in the WCE image area, there are at least two fundamental challenges with medical image classification and prediction. This means that sample datasets are so short that we cannot extract enough information to extract discriminative features private security of the patients (Dodge, Karam Jun 2016). The enhancements of CLAHE and gamma correction have been proposed, however they have had no effect on improving detection accuracy (Mohammed, Farup, Yildirim et al. 2018). 

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
"Machine learning" suomeksi "koneoppiminen", näyttää olevan YSO:ssa jo.
