### ISSUE TITLE
patristiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10407]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[patristiikka](http://www.yso.fi/onto/yso/p11629)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCSH-asiasanastoon (http://id.loc.gov/authorities/subjects/sh85047462)

**Perustelut ehdotukselle**

Siltaus puuttuu

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Tämä LCSH siltaus on lisätty YSO käsitteeseen  http://www.yso.fi/onto/yso/p11630, **kirkkoisät**, kyrkofäder, church fathers
