### ISSUE TITLE
harjoituskirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10402]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[harjoituskirjat](http://www.yso.fi/onto/yso/p155)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä ehdotus koskee SLM-termiä harjoituskirjat: Lisätään määritelmä?

**Perustelut ehdotukselle**

Myös suhde termeihin oppimateriaali ja opetusoppaat olisi hyvä selventää. Harjoituskirjat on nyt käytetty myös esim. kirjasta Erityistä kuvataidetta : ideoita ja tehtäviä kuvataidetyöskentelyyn / Nina Wallenstjerna-Heiskanen. Tässä ei ole täytettäviä sivuja tms. vaan kirja näyttää olevan suunnattu ohjaajille/opettajille, joten onko harjoituskirjat oikea termi tässä tapauksessa? Määritelmä selventäisi. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://www.kielitoimistonsanakirja.fi/#/harjoituskirja?searchMode=all

**Comment by mirmaid** [comment]
Määritelmä: Harjoitustehtäviä sisältävä kirja. 

RT oppimateriaali
