### ISSUE TITLE
sarkopenia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10418]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sarkopenia

**Ehdotettu termi ruotsiksi**

sarkopeni

**Ehdotettu termi englanniksi**

sarcopenia

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 5

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Sarkopenia), [FinMeSH](http://www.yso.fi/onto/mesh/D055948)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sarcopenia as a predictor of survival in vascular patients https://urn.fi/URN:ISBN:978-952-03-2018-8

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [sarkopenia](http://finto.fi/yse/fi/page/Y510418)

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

sarkopenia
sarcopenia la, sarcopenia e, sarkopeni ‑n r (< sarx kr liha + penia kr puute) lihasten surkastuneisuus | vanhuudessa esiintyvä lihaskudoksen kato, useimmilla vanhuksilla lievä, joillakuilla huomattava

Suomenkielisempi olisi "lihasten surkastuneisuus" tms.
