### ISSUE TITLE
kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10412]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kirjallisuus](http://www.yso.fi/onto/yso/p8113)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko YSOon lisättävissä ohjaustermeinä esim. tanskalainen kirjallisuus, norjalainen kirjallisuus, ranskalainen kirjallisuus jne., vai miten suhtaudutaan kirjallisuus-termin alakäsitteiden merkityskenttään? Jos sellaiset muodot ei ole lisättävissä niin pitäisikö ne jopa olla erikseen? 

**Perustelut ehdotukselle**

Ruotsiksi esim. tanskankielinen kirjallisuus on ALLFOssa dansk litteratur (joka voi yhtä hyvin olla tanskankielinen kirjallisuus kuin Tanskassa kirjoitettu/tanskalaisen kirjoittama kirjallisuutta. Tämä siis vain esimerkkinä, mutta vastaavia tapauksia on paljon ja osa kirjallisuus-termin alakäsitteistä on tarkasti käännetty -språkig/litteratur på, eli nimenomaan -kielinen kirjallisuus, mutta osa (varsinkin vanhemmat Allärs-ajalta olevat asiasanat) on laajemmassa merkityksessä, kuten yllä olevassa tapauksessa. Tästä ongelmasta tulee aina välillä kysymyksiä... SAOssa vastaavat termit ovat siinä muodossa että kattavat ensisijaisesti tietyn maan kirjallisuutta", ei niinkään pelkästään sitä, millä kielellä se on kirjoitettu (voihan se olla käännös jne.). 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Suomeksi _tanskankielinen kirjallisuus_ ei kata Tanskassa muilla kielillä tuotettua kirjallisuutta, joten olisihan tällainen vähän hankalaa.

**Comment by fantsby-m** [comment]
Tämä voi tosiaan olla ongelma ainakin jos aineisto kuvaillaan ensin ruotsiksi ja suomenkieliseen kuvailuun tulee sitten suppeampi termi (kuten _dansk litteratur_ > _tanskankielinen kirjallisuus_, jos aineisto käsitteleekin kaikkea tanskalaista kirjallisuutta kielestä riippumatta), mutta miten tämän voisi ohjaustermeillä edes ratkaista?

Myös englanniksi on YSOssa _Danish language literature_.

**Comment by YSO-kokous** [comment]
### Päätös
ruotsinkielisiä termejä täytyy tarkistaa tämän jaon ilmaisuun eli maahan viittaavat termit muutetaan kieleen viittaavaksi.
Käsittely AASI ryhmässä.

**Comment by mariaforsen** [comment]
Yllä mainitut muutokset tehty ruotsiksi.
