### ISSUE TITLE
saamen kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10415]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[saamen kieli](http://www.yso.fi/onto/yso/p18720)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan "saamelaiskielet" päätermiksi ja "saamen kieli" ohjaustermiksi. Englannille hyvä vaihtoehto olisi "Sámi languages".

**Perustelut ehdotukselle**

"Saamen kieli" viittaamassa kaikkiin saamelaiskieliin on vanhanaikainen termi. Sama ongelma näkyy myös LCSHssa, sillä eri saamelaiskieliä on listattu täällä käsitteen "Sami language" murteina. Termiä "saamelaiskielet" käytetään nykyään vakiintuneesti viittamaan tähän kieliryhmään. Erityisesti näin on kielitieteessä, joka oletettavasti on myös suomalais-ugrilaisten kielten luokituksen yleinen asiayhteys. 

Mainitsen samalla, että erityisesti yhteiskunnallisessa yhteydessä käytetään myös käsitettä "saamen kielet" puhuttaessa esimerkiksi Suomessa puhutuista saamen kielistä. YSOssa "saamelaiskielet" on kuitenkin mielestäni perustelluin valinta, sillä sitä käytetään yhdessä samalla tasolla olevien käsitteiden "itämerensuomalaiset kielet" ja "permiläiset kielet" kanssa. 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Samiska%20spr%C3%A5k

**Comment by mirmaid** [comment]
Ehdotus: muutetaan päätermi.
