### ISSUE TITLE
ruskettuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10417]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ruskettuminen

**Ehdotettu termi ruotsiksi**

solbränna

**Ehdotettu termi englanniksi**

suntan

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 tanning (Suntan), rusketus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85130566), [FinMeSH](http://www.yso.fi/onto/mesh/D055107)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Effects of narrow-band ultraviolet B radiation on formation of neuroendocrine mediators in the skin and on mood, and findings on tanning dependence and winter blues among sunbathers

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [ruskettuminen](http://finto.fi/yse/fi/page/Y510417)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Solbränna=rusketus, varmaan ok silti, koska vastaavaa "passiivimuotoa" ei ruotsiksi ole ("bli brun")

**Comment by ilona-x** [comment]
Suomeksikin voisi varmaan olla ihan hyvin pääterminä rusketus. Laitoin ehdotukseen FinMeSHin mukaisen muodon, siellä siis ruskettuminen KT rusketus ja ruotsiksi solbränna ja englanniksi suntan http://www.yso.fi/onto/mesh/D055107

**Comment by YSO-kokous** [comment]
### Päätös
**rusketus** KT ruskettuminen

**Comment by mariaforsen** [comment]
Sv. solbränna HT solbrändhet
