### ISSUE TITLE
auringonotto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10416]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

auringonotto

**Ehdotettu termi ruotsiksi**

solande

**Ehdotettu termi englanniksi**

sunbathing

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 auringon ottaminen, solbad

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D055108), [LCSH: Sun-baths](http://id.loc.gov/authorities/subjects/sh85130485), [Wikidata](http://www.wikidata.org/entity/Q47125651)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Effects of Narrow-band Ultraviolet B Radiation on Formation of Neuroendocrine Mediators in the Skin and on Mood, and Findings on Tanning Dependence and Winter Blues among Sunbathers

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [auringonotto](http://finto.fi/yse/fi/page/Y510416)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. solbad HT solning, solande 
https://id.kb.se/term/sao/Solbad
