### ISSUE TITLE
haittavero

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10426]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[haittavero](http://www.yso.fi/onto/yso/p11123)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan suhteessa ympäristöveroihin, myös ruotsiksi ja englanniksi

**Perustelut ehdotukselle**

Ruotsiksi ja englanniksi vastineet viittaavat nyt ympäristöveroihin. Ruotsiksi voidaan muuttaa miljöskatt > pigouviansk skatt tms. jos tarkoitus on viitata tähän https://fi.wikipedia.org/wiki/Haittavero ja siis laajemmin kuin pelkästään ympäristöveroihin.  Jos taas halutaan että termi viittaa nimenomaan ympäristöveroihin, niin olisi varmaan hyvä tehdä termimuutos > ympäristöverot (ks. Tepa ja Valter). Tosin sanastossa on myös ympäristöverotus, sille voisi laittaa OT ympäristöverot, jos pidetään tämä termi muodossa haittavero (OT Pigoun vero).

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Käytetty tosiaan ainakin Melindassa pääosin ympäristöhaittoihin liittyen, vaikka perinteisesti on tarkoitettu myös esim. terveydelle vaarallisten tuotteiden verotusta (tupakka, makeiset jne.).

**Comment by fantsby-m** [comment]
Ruotsiksi tuo pigouviansk skatt, englanniksi Pigovian tax? Ongelmahan on vain noissa kieliversioissa?

**Comment by ilona-x** [comment]
fi        ympäristövero
**ei: haittavero**
sv       miljöskatt
en      environmental tax; green tax; ecological tax; eco-tax


määritelmä
vero, joka peritään tietystä luonnonvarojen käytöstä tai haitallisia ympäristövaikutuksia aiheuttavasta toiminnasta

huomautus
Ympäristöveroilla pyritään ohjaamaan muun muassa teollisuutta, maataloutta ja kuluttajia valitsemaan ympäristölle vähemmän haitallisia aineita, tuotteita, menetelmiä jne.
Ympäristöverotukseen kuuluvat toimet kohdistuvat muun muassa luonnonvarojen käyttöön (esim. maa-ainesvero), tuotantopanoksen ominaisuuksiin (esim. energiavero), tuotteen ominaisuuksiin (esim. polttoaineverot, katalysaattorivähennys, lannoitevero ja kertakäyttöpakkausten vero) tai päästöihin.

Lähde: Ympäristösanasto (TSK 27, 1998)
https://termipankki.fi/tepa/fi/haku/haittavero

**Comment by ilona-x** [comment]
EKS:
Asiasana:	ympäristöverot	
Korvaa termin:	haittavero

**Comment by mirmaid** [comment]
haittavero (ympäristöverotus) KÄ ympäristöverotus?

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Taloustiede:Pigou-vero

**Comment by YSO-kokous** [comment]
### Päätös
Tarkistetaan suomenkielisnen termi (vrt. Pigou-vero)

Lisätään ohjaustermi
ympäristöverot KÄYTÄ ympäristoverotus
Mahdollisesti myös
haittavero (ympäristöverotus) KÄYTÄ ympäristöverotus 

Lisätään määritelmä: "Haittavero on markkinatoiminnan ympäristölle tai terveydelle aiheuttaman haitan vähentämiseksi asetettu vero."

Ruotsin- ja englanninkieliset päätermit vaihdettava.
