### ISSUE TITLE
Normandian maihinnousu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10424]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Normandian maihinnousu

**Ehdotettu termi ruotsiksi**

Invasionen av Normandie

**Ehdotettu termi englanniksi**

Operation Overlord

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [taistelut](http://www.yso.fi/onto/yso/p920)

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540), [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-82-535-4394-9

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Normandian maihinnousu](http://finto.fi/yse/fi/page/Y510424)

**Comment by jtuohini** [comment]
LCSH-vastine: [**World War, 1939-1945--Campaigns--France--Normandy**](http://id.loc.gov/authorities/subjects/sh85148319).

**Comment by mariaforsen** [comment]
SAOssakin kaksi eri käsitettä: https://id.kb.se/term/sao/Slaget%20om%20Normandie%201944  ja https://id.kb.se/term/sao/D-dagen%201944

Mihin tämä nyt tarkalleen viittaisi? Operation Overlord ei vaikuta oleva täsmällinen vastine myöskään. 

https://sv.wikipedia.org/wiki/Landstigningen_i_Normandie
https://sv.wikipedia.org/wiki/Invasionen_av_Normandie

**Comment by AuHo22** [comment]
Lienee kokonaisuus eri operaatioita - meille riittäisi tuo yleisin kuvaus asiasta, eli Normandian maihinnousu.

LC:n korvatut termit:
D-Day, 1944 (Normandy invasion)
Normandy (France)--History--Invasion, 1944
Normandy Invasion, 1944 (Military operation)

**Comment by YSO-kokous** [comment]
### Päätökset
Hyväksytään käsite. Tarvittaessa voidaan lisätä huomautus, että käsite viittaa koko operaatioon eikä vain ensimmäiseen D-päivään.

Ohjaustermejä voidaan lisätä enemmän ruotsiksi ja englanniksi.

**Comment by ilona-x** [comment]
YLE:llä 
Normandian maihinnousu - Invasionen av Normandie
https://yle.fi/aihe/t/18-197243

**Comment by mariaforsen** [comment]
Sv. invasionen av Normandie HT landstigningen i Normandie, D-dagen, slaget om Normandie, invasionen i Normandie, landstigningen vid Normandie

https://sv.wikipedia.org/wiki/Invasionen_av_Normandie
https://sv.wikipedia.org/wiki/Landstigningen_i_Normandie
https://fi.wikipedia.org/wiki/Normandian_maihinnousu
