### ISSUE TITLE
elokuvataide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10429]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[elokuvataide](http://www.yso.fi/onto/yso/p16327)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "kamerataide"

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/kamerataide

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Elokuvataide on kuitenkin hyvin paljon laajempi ilmiö kuin vain kamerataidetta.

**Comment by YSO-kokous** [comment]
### Päätös
ei lisätä ohjautermiä elokuvataiteeseen. Vain valokuvataiteeseen.
