### ISSUE TITLE
vieraannuttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10425]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vieraannuttaminen](http://www.yso.fi/onto/yso/p24255)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan niin että vieraannuttaminen käännösstrategiana on erillisenä terminä?

**Perustelut ehdotukselle**

Vieraannuttaminen on nyt muissa ryhmissä ja sen mukaisesti on myös ollut ruotsiksi fjärmande. Käännöstrategian merkityksessä termi on eri, exotisering/främmandegörande (foreignization). Melindassa nyt virheellinen käyttö tässä merkityksessä.

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Miten jaettaisiin? Paitsi kääntämisestä, tätä käytetään myös taiteen yhteydessä ja toisaalta lapsen huoltoon liittyen.

**Comment by mariaforsen** [comment]
Voisiko olla ainakin vieraannuttaminen (käännösstrategiat)=foreignisation ja vieraannuttaminen (sosiaalinen/psykologinen)=nykyinen distancing? alienation tms? 
YSOssa on myös vieraantuminen (liittyy asiaan ainakin muiden kielten kannalta)

https://sv.wikipedia.org/wiki/F%C3%B6r%C3%A4ldraalienation
https://id.kb.se/find?q=f%C3%B6rfr%C3%A4ml%2a
https://id.kb.se/term/sao/Verfremdungseffekt

JS: kts. myös 
kts. https://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:vieraannuttamisefekti

**Comment by YSO-kokous** [comment]
### Päätökset
Jaetaan käsite kolmeen osaan:
- vieraannuttaminen (käännöstiede) tai vieraannuttaminen (kääntäminen)
- vieraannuttaminen (taide)  -- mietitään vielä päätermiä...
  KT vieraannuttamisefekti, vieraantumisefekti 
- vieraannuttaminen (ihmissuhteet) 
  KT vieraannuttaminen vanhemmasta,

**Comment by mariaforsen** [comment]
Sv. 
-främmandegörande (översättning) HT främmandegöring (översättning), exotisering (översättning) 
-främmandegöring (konst) HT Verfremdungseffekt, förfrämligande (konst) https://id.kb.se/term/sao/Verfremdungseffekt
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_47f666b4f03ca135fc09c81b089e772b&list_id=1&keyword=vieraannuttaa&word=vieraannuttaa
https://sv.wikipedia.org/wiki/Fr%C3%A4mmandeg%C3%B6ring
-fjärmande (relationer) HT förfrämligande (relationer), föräldraalienation
