### ISSUE TITLE
daaliat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10421]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

daaliat

**Ehdotettu termi ruotsiksi**

dahlior

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan aineiston kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ulrika Grönlund: Dahlia : 222 sorter, odling, skötsel & inspiration 978-91-7843-555-5

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [daaliat](http://finto.fi/yse/fi/page/Y510421)

**Comment by mariaforsen** [comment]
Sv. dahlior https://namnochslaktskap.artfakta.se/taxa/1005796/details
