### ISSUE TITLE
Mafia (saari)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10423]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Mafia (saari)

**Ehdotettu termi ruotsiksi**

Mafiaön

**Ehdotettu termi englanniksi**

Mafia Island

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Matkaopas kyseiseen alueeseen on julkaistu

**Ehdotettu yläkäsite YSOssa (LT)**

 [Tansania](http://www.yso.fi/onto/yso/p94438)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://fi.wikipedia.org/wiki/Mafia_(saari)](http://Mafia (saari))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/F/VP1S2RPYEMF6NIHYNG8PGS1ID2YHM78DCUL7R6CX1IMRKELNG9-02910?func=full-set-set&set_number=038775&set_entry=000001&format=999

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Mafia (saari)](http://finto.fi/yse/fi/page/Y510423)

**Comment by mirmaid** [comment]
Mafia (Tansania)
