### ISSUE TITLE
vähävaraisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10433]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vähävaraisuus](http://www.yso.fi/onto/yso/p3903)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko mahdollinen OT varattomuus, vai olisiko varattomuus erillinen termi?

**Perustelut ehdotukselle**

Englanniksi lack of means, joka motissa on varattomuus. Ks. myös https://termipankki.fi/tepa/fi/haku/v%C3%A4h%C3%A4varaisuustodistus
Yksi mahdollinen vastine ruotsiksi voisi mahdollisesti olla medellöshet, mutta se on kyllä tarkasti käännettynä varattomuus. Varattomuus myös käytetty Melindassa. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Mielestäni on ok ohjaustermi.
