### ISSUE TITLE
jutun palautus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10438]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[jutun palautus](http://www.yso.fi/onto/yso/p18657)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi jutun palauttaminen?
RT-suhteeksi muutoksenhaku?

**Perustelut ehdotukselle**

https://tieteentermipankki.fi/wiki/Oikeustiede:jutun_palauttaminen

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
EKS:
Asiasana: jutun palauttaminen
Asiasana ruotsiksi: återförvisa målet till lägre rätt
Asiasana englanniksi: return of a case to the lower court

**Comment by mariaforsen** [comment]
Ruotsiksi pitää harkita päätermin muutosta. Mihin kaikkeen tämä voi viitata? Googlessa ei hirveästi tuloksia. Käytetty Melindassa vain 2 kertaa näköjään.

**Comment by YSO-kokous** [comment]
**Päätös**

Päätermi vaihdetaan muotoon _jutun palauttaminen (oikeus)_. Tarkistetaan kielivastineet. Otetaan määritelmä Tieteen termipankista.

**Comment by mariaforsen** [comment]
Sv.  återförvisning (till lägre rätt) HT återförvisa målet till lägre rätt /eks
https://www.aklagare.se/ordlista/a1/aterforvisning/
https://www.rikstermbanken.se/simpleSearch.html
https://svenska.se/tre/?sok=remittera&pz=1
https://sv.wikipedia.org/wiki/%C3%85terf%C3%B6rvisning
https://finto.fi/hklj/fi/page/332.5?clang=sv
jfr https://www.tyoelakelakipalvelu.fi/telp-publishing/vepa/document.faces?document_id=307870#
