### ISSUE TITLE
liikennemaksut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10439]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[liikennemaksut](http://www.yso.fi/onto/yso/p1311)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mitä tällä termillä tarkoitetaan? YSOssa nyt RT matkaliput
Käytetty Melindassa esim. seuraavissa:
Ruuhkamaksuilla poliisivaltioon
Etu työsuhdematkalipusta paranee
Selvitys väylämaksulain ja -asetuksen uudistamistarpeista 
jne.

**Perustelut ehdotukselle**

Kielitoimiston sanakirja 
liikennemaksu
1. laivoilta t. lentokoneilta satamaan t. lentokentälle saapumisen yhteydessä perittäviä palvelu- tms. maksuja.
2. teleyritysten asiakkailtaan perimistä puhelin- ja tietoliikenteen maksuista. 

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
LIIKO:
liikennemaksut http://www.yso.fi/onto/mero/m9845
Alakäsitteet
   [ merenkulkumaksut](https://finto.fi/liiko/fi/page/m8987)
   [ ratamaksut](https://finto.fi/liiko/fi/page/m10232)
   [ tiemaksut](https://finto.fi/liiko/fi/page/m9844)
   [väylämaksut](https://finto.fi/liiko/fi/page/m8470)

**Comment by mariaforsen** [comment]
Sv. trafikavgifter on ok molemmissa merkityksissä, mutta ovathan nämä eri asioita, eli pitäisikö ainakin määritellä..
https://svenska.se/tre/?sok=trafikavgift&pz=1
https://termipankki.fi/tepa/fi/haku/liikennemaksu
https://www.sanakirja.fi/custom/en-sv-fi/liikennemaksu

**Comment by ilona-x** [comment]
YSOssa erikseen 
[ruuhkamaksut ](http://www.yso.fi/onto/yso/p21274)
[väylämaksut](http://www.yso.fi/onto/yso/p22369)
[ratamaksut (rautatieliikenne)](http://www.yso.fi/onto/yso/p38029)

**Comment by fantsby-m** [comment]
Ja myös
[tietullit](http://www.yso.fi/onto/yso/p7477)

(ks. myös https://github.com/Finto-ehdotus/YSE/issues/9930)

**Comment by mirmaid** [comment]
Melindassa tosiaan käytetty varsin laidasta laitaan, niin hevoskyytien taksoista kuin joukkoliikenteen tarkastusmaksuista, laiva- ja lentoliikenteen maksuista - ei kuitenkaan teleliikenteestä. Matkalippujen osalta tarpeeton, mutta toisaalta jos aineisto käsittelisi laajemmin vaikka sekä matkalippujen hintoja että esim. liityntäpysäköinnin maksullisuutta niin tuntuisikin jo ehkä sopivan...

Mikä on tavoitetila?

**Comment by ilona-x** [comment]
Tämä taisi tulla vastaan, kun käsiteltiin tiemaksuja https://github.com/Finto-ehdotus/YSE/issues/9930

Sitä en muista, mitä tässä oli tarkoitus tehdä, mutta ainakin hierarkia ja suhteet ovat YSOssa erilaiset kuin LIIKOssa:
[liikennemaksut ](http://www.yso.fi/onto/mero/m9845)
Alakäsitteet
merenkulkumaksut
ratamaksut
tiemaksut
väylämaksut

ja YSOssa:
[liikennemaksut ](http://www.yso.fi/onto/yso/p1311)
RT matkaliput

**Comment by YSO-kokous** [comment]
**Päätös**

Tarkistetaan hierarkiaa suhteessa LIIKOon. Kootaan näkemyksiä merkitysten rajaamisen vaihtoehdoista.
