### ISSUE TITLE
kaarisillat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10436]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaarisillat

**Ehdotettu termi ruotsiksi**

bågbroar

**Ehdotettu termi englanniksi**

arch bridges

**Tarkoitusta täsmentävä selite**

Huom. wikipediassa suomeksi artikkelit sekä kaarisillasta että holvisillasta. Holvisilta-artikkelin vastineet en arch bridge & sv bågbro

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 1

**Ehdotettu yläkäsite YSOssa (LT)**

 [sillat](http://www.yso.fi/onto/yso/p14830)

**Ehdotetut temaattiset ryhmät**

 [37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568)

**Vaihtoehtoiset termit**

 holvisillat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85016862), [MAO/TAO](http://www.yso.fi/onto/mao/p5628), [Wikipedia](https://fi.wikipedia.org/wiki/Kaarisilta), [Wikipedia](https://fi.wikipedia.org/wiki/Holvisilta)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Yläpuolisen siltakaaren optimaalinen muoto http://urn.fi/urn:isbn:9789526229089

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [kaarisillat](http://finto.fi/yse/fi/page/Y510436)

**Comment by mirmaid** [comment]
Myös LIIKOssa.

**Comment by mariaforsen** [comment]
Sv. bågbroar HT valvbroar
