### ISSUE TITLE
hyväosaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10432]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hyväosaisuus](http://www.yso.fi/onto/yso/p27092)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko mahdollista muuttaa muotoon hyväosaiset tms.?

**Perustelut ehdotukselle**

Ruotsiksi on ollut välsituerade, joka ei ontologisesti toimi ja aiheuttaa hierarkiavirheen. Englanniksi on näköjään privileged social position, onko se tarpeeksi täsmällinen (sanastoissa kyllä painotetaan taloudellista puolta). Ks. https://www.kielitoimistonsanakirja.fi/#/hyv%C3%A4osainen?source=suggestion Tämän perusteella ruotsiksi voisi mahdollisesti olla myös (kompromissiratkaisuna) "god ekonomisk ställning" tms?  Hyväosaisuus käytetty vain 19 kertaa Melindassa. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Varmaan tosiaan tavallisemmin tulee käytettyä neutraalimpaa termistöä (sosioekonominen asema, elintaso, toimeentulo). Sanastossa on kuitenkin myös _huono-osaisuus_, jota on käytetty paljon enemmän ymmärrettävästi. Englanniksi sillä on vastaavanlainen käännös, mutta ruotsiksi eri tavalla. Suomeksi nämä -uus-muodot ovat kyllä toimivampia.

**Comment by YSO-kokous** [comment]
vrt. [huono-osaisuus](http://www.yso.fi/onto/yso/p6220)

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään huomautus: Tarkoittaa hyvää sosioekonomista asemaa.
Tarkistetaan englanninkielinen termi.

**Comment by mariaforsen** [comment]
Sv. välsituerade > god socioekonomisk ställning
