### ISSUE TITLE
garanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10434]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[garanti](http://www.yso.fi/onto/yso/p9806)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa?

**Perustelut ehdotukselle**

Takuu on ryhmässä 69 ja 75, mutta alakäsitteinä on myös nuorisotakuu ja hoitotakuu, eli mihin kaikkeen tätä saa käyttää? Ks. https://www.kielitoimistonsanakirja.fi/#/takuu Ruotsiksi tarkenne olisi tarpeen, sanastossa on myös vakuudet. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Enimmäkseen käytetty tuotteisiin tai vastaaviin liittyen, mutta jonkin verran myös sosiaaliturvan yhteydessä. Mun nähdäkseni tässä ei ole suomeksi kyse suorastaan eri merkityksestä, vaan ehkä niin että merkitys on suomeksi sitten vähän väljempi kuin muilla kielillä, "jotain mitä takuun saajalle luvataan ja mihin takuun antaja sitoutuu".

**Comment by mirmaid** [comment]
Edellyttääkö muutoksia?

**Comment by mariaforsen** [comment]
Ruotsin kannalta ehkä ongelmallisempi, koska garanti voi viitata myös vakuudet-käsitteeseen. Mutta ehkä voidaan käytännössä silti olla rajaamatta tätä termiä, jos suomeksi ei haluta minkäänlaista tarkennusta takuu-termiin? Siinä tapauksessa olisi ehkä kuitenkin syytä lisätä muitakin ryhmiä, ehkä jopa 00?

**Comment by YSO-kokous** [comment]
### Päätös
- Selvitetään tarkenteiden käyttöä esim. rajataanko vain kauppaan liittyväksi. vrt.  granti  on tuotetakuu, muttä suomenkielisenä käsitteenä voi olla liian suppea.
- Selvitetään Melindan viitteistä kuinka suureen osaan sopisi takuu (kauppa) ja mitä jäljelle näistä jäävät takuut ovat.
- vientitakuu  LT valtiontakaukset

**Comment by fantsby-m** [comment]
Vientitakuu ei ehkä kuitenkaan ole valtiontakauksen alakäsite, pikemminkin rinnakkainen:
https://www.finnvera.fi/finnvera/uutishuone/artikkelit/takaus-vientitakaus-vientitakuu-nain-finnveran-rahoitustermit-kaantyvat-arkikielelle

**Comment by mirmaid** [comment]
Enpä tiedä miten toimiva tuo (kauppa)-tarkenne olisi, kun puhutaan _työn takuusta_ (esim. huollon, rakennusurakan takuu). Onko Melindan viitteissä ruotsin kannalta virheellisiä nyt?

**Comment by mariaforsen** [comment]
Jos ajatellaan garanti laajempana, kuten Suomessa myös käytetään (esim. vårdgaranti jne.) niin ei ainakaan takuu=garanti-termin Melindakäytössä näy isompia ongelmia. Ehkä joissain tapauksissa garanti/takuu on päätynyt tietueeseen ruotsinkielisen termin kautta, esim. Självständiga bankgarantier : vad innebär de och när kan betalningskrav under dem vägras / Hans Swolin ; red. Lars Gorton ; Juridiska personers borgensåtaganden / Torbjörn Ingvarsson Vai onko takuu oikein myös vakuus/takaus-asioissa?

**Comment by mirmaid** [comment]
^ Itsekin mietin välillä, että onkohan näissä mennyt sekaisin, mutta toisaalta ruotsinkielisessä on nyt ohjaustermi, eli pitäisi kai osata käyttää _säkerheter_ silloin. Virheellisiä on hyvin vähän, joihinkin voisi korjata ehkä _takuueläkkeen_.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei lisätä tarkennetta suomeksi.
