### ISSUE TITLE
elokuvajulisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10435]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

elokuvajulisteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Asiasanojen "julisteet" + "elokuvat" tms. yhdistelmä ei tuota samaa tarkkuutta kuin oma asiasanansa tuottaisi: kuvailtu aineisto ei välttämättä käsittele elokuvia itseään ollenkaan

**Ehdotettu yläkäsite YSOssa (LT)**

 [julisteet](http://www.yso.fi/onto/yso/p18786)

**Ehdotetut temaattiset ryhmät**

 [80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547), [92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569), [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85048229), [Wikidata](http://id.loc.gov/authorities/subjects/sh85048229)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://id.loc.gov/authorities/subjects/sh85048229 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [elokuvajulisteet](http://finto.fi/yse/fi/page/Y510435)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. filmaffischer HT filmpostrar, filmposters /sao
