### ISSUE TITLE
villasukat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10448]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

villasukat

**Ehdotettu termi ruotsiksi**

yllesockor

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sukat](http://www.yso.fi/onto/yso/p15415)

**Ehdotetut temaattiset ryhmät**

 [26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578), [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Villasukkia ja värssyjä / Jaana Huhtanen ja Timo Värssy

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [villasukat](http://finto.fi/yse/fi/page/Y510448)

**Comment by satuniininen** [comment]
Sukat+ käsityöohjeet käytetty 665 kertaa. Villasukat voisi lisätä ohjaustermiksi?

**Comment by mariaforsen** [comment]
Villapaidat ja villatakit kyllä on sanastossa.

**Comment by mirmaid** [comment]
Muista sukista tuskin ohjeita onkaan.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _villasukat_ ohjaustermiksi _sukille_.
