### ISSUE TITLE
seinämaalaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10442]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seinämaalaukset](http://www.yso.fi/onto/yso/p9903)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "muraalit"

**Perustelut ehdotukselle**

Kyseistä nimitystä käytetty mediassa viime vuosina huomattavan ahkerasti, joten siitä olisi hyvä saada viittausmuoto sanastoon.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT muralmålningar
