### ISSUE TITLE
ikääntyneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10444]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ikääntyneet](http://www.yso.fi/onto/yso/p2433)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan englanninkielisen termin "senior citizens" muuttamista muotoon "older people"

**Perustelut ehdotukselle**

Käytännössä juuri kukaan eurooppalainen ikääntymisen tutkija ei käytä muotoa "senior citizens". Tuota muotoa näkyy jonkin verran Yhdysvalloissa, mutta useimmat tutkijat eivät sielläkään käytä kyseistä muotoa. "Elderly"-muotoa puolestaan pidetään nykyisin ikäsyrjivänä.

**Ehdottajan organisaatio**

Suomen Akatemian Ikääntymisen ja hoivan tutkimuksen huippuyksikkö/Jyväskylän yliopisto

**Comment by fantsby-m** [comment]
https://journals.lww.com/jgpt/fulltext/2011/10000/use_of_the_term__elderly_.1.aspx
