### ISSUE TITLE
vaginismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10443]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vaginismi

**Ehdotettu termi ruotsiksi**

vaginism

**Ehdotettu termi englanniksi**

vaginismus 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tuli vastaan nuorten kaunokirjassa, jossa oli vahvana teemana vaginismin kanssa eläminen. Myös endometrioosi ja muut vaivat löytyvät YSO:sta, niin sopisi paremmin sinne kuin Kaunoon. Hakutermi olisi hyvä olla, jos joku etsii tietoa aiheesta. Löytyy jo FinMeSHistä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 emätinkouristus , vaginismus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH/FinMeSH](https://finto.fi/mesh/fi/page/D052065)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Joya Goffney: Confessions of an alleged good girl.

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [vaginismi](http://finto.fi/yse/fi/page/Y510443)

**Comment by mirmaid** [comment]
4 viitettä Melindassa.
