### ISSUE TITLE
sinsillat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10449]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sinsillat](http://www.yso.fi/onto/yso/p14666)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

sinsillat -> chinchillat

**Perustelut ehdotukselle**

Tunnetaan ainakin nykyään paremmin chinchilla-käsitteellä. 

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Kielitoimiston sanakirjassa muodot chinchilla ja tsintsilla
https://www.kielitoimistonsanakirja.fi/#/tsintsilla

Laji.fi:
Tsintsillat – Chinchillidae https://laji.fi/taxon/MX.50620
suomeksi? - Chinchilla https://laji.fi/taxon/MX.51881
Andientsintsilla – Chinchilla chinchilla https://laji.fi/taxon/MX.50431
Chilentsintsilla – Chinchilla lanigera https://laji.fi/taxon/MX.50432

Wikipedia:
Chinchillidae https://fi.wikipedia.org/wiki/Tsintsillat
Chinchilla https://fi.wikipedia.org/wiki/Tsintsillat_(suku)
Chinchilla lanigera https://fi.wikipedia.org/wiki/Chinchilla

**Comment by nikopartanen** [comment]
Ilmeisesti _sinsilla_ on ollut joskus tietosanakirjoissa terminä (Wikipedian lähteiden perusteella). Päätermiksi _tsintsillat_ tai _chinchillat_, toinen niistä + _sinsillat_ ohjaustermeiksi?

**Comment by mariaforsen** [comment]
Ruotsiksi nyt chinchilla. Entä lajina Chinchilla lanigera?

**Comment by mirmaid** [comment]
Ehdotus: päätermiksi _chinchilla_ (käytetyin) - ja käsiteltäisiin lajina, koska ovathan ne lemmikkichinchillat (joista varmaan aineistoa yleensä) samaa lajia. KT chilentsintsilla
