### ISSUE TITLE
risteilijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10447]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

risteilijät

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Luokka:Risteilij%C3%A4t

**Perustelut ehdotukselle**

Olemassa oleva laivatyyppi - risteilyalus on matkustajaliikenteen tyyppi puolestaan.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575), [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtamerten turvaajat : risteilijöiden synty ja kehitys / Kai Varsio

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [risteilijät](http://finto.fi/yse/fi/page/Y510447)

**Comment by mariaforsen** [comment]
Sv. kryssare 
https://sv.wikipedia.org/wiki/Kryssare
https://svenska.se/saol/?sok=kryssare&pz=1

**Comment by ilona-x** [comment]
varmaan pitäisi olla tarkenne: risteilijät (sota-alukset)?
https://www.kielitoimistonsanakirja.fi/#/risteilij%C3%A4


LCSH:
Cruisers (Warships) http://id.loc.gov/authorities/subjects/sh85034369

**Comment by mirmaid** [comment]
Huvitti kun ensimmäinen mielikuva itselle oli merkitys 3. https://fi.wiktionary.org/wiki/risteilij%C3%A4

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. kryssare (krigsfartyg)
