### ISSUE TITLE
urheilupelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10440]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[urheilupelit](http://www.yso.fi/onto/yso/p26233)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään tarkenne (videopelit tai digitaaliset pelit)? 
Ja yläkäsitteeksi digitaaliset pelit tai videopelit?

**Perustelut ehdotukselle**

Käytetty Melindassa mm. seuraavissa:

https://melinda.kansalliskirjasto.fi/byid/015378201
https://melinda.kansalliskirjasto.fi/byid/018027488

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Digitaaliset pelit on käytetty kerran tarkenteena, videopelit ei. Digitaalisten pelien aineistotyyppejä pitäisi kyllä varmaan taas tarkastella (ehkä SLM:ssä ensin, siellä onkin jo konsolipeleistä issue).

**Comment by mirmaid** [comment]
Mutta siis olisiko vaikka (digitaaliset pelit) tässä vaiheessa?

**Comment by mariaforsen** [comment]
Jääkö termiä urheiluaiheisille lautapeleille yms. "fyysisille" peleille? Niitä on myös jonkin verran.
