### ISSUE TITLE
rescuekoirat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10450]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rescuekoirat

**Ehdotettu termi ruotsiksi**

rescue hundar

**Ehdotettu termi englanniksi**

rescue dogs

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Rescuekoirat on yleisesti käytetty termi. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [eläimet](http://www.yso.fi/onto/yso/p2023)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [löytöeläimet](http://www.yso.fi/onto/yso/p4438), [kulkukoirat](http://www.yso.fi/onto/yso/p25154)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Teos "Etsii omaa ihmistä : 25 tarinaa rescuekoirista".

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [rescuekoirat](http://finto.fi/yse/fi/page/Y510450)

**Comment by mariaforsen** [comment]
Olisi kyllä tarpeen, sanastossa on nyt vain kulkukoirat, joka on aika lailla eri asia. 
https://fi.wikipedia.org/wiki/Rescuekoira

**Comment by mirmaid** [comment]
Eli = löytökoirat? _Löytöeläimistä_ varmaan valtaosa on kissoja ja koiria (vaikka muitakin on tietysti olemassa).

**Comment by ilona-x** [comment]
LCSHssa rescue dogs merkityksessä [pelastuskoirat](https://finto.fi/yso/fi/page/p7460)

**Comment by ilona-x** [comment]
https://www.kielikello.fi/-/rescuekoira-loytokoira-ja-kodinvaihtaja

**Comment by mariaforsen** [comment]
Yllä oleva artikkeli kyllä melko tyhjentävä. Ruotsiksi tilanne on siinä mielessä eri että meillä on **ALLFOssa kulkukoirille vastineena hemlösa hundar** fi. "kodittomat koirat". Olisiko se suomeksikin mahdollinen ratkaisu? 
Näissä termeissä on tietty kyllä näkökulma-ero "ennen pelastusta" (koditon koira/kulkukoira/löytökoira) vs. "pelastuksen jälkeen" (=rescue/adoptoitu koira). Löytökoirahan ei ole välttämättä saanut uutta kotia, vaan saattaa joutua lopetettavaksi (ks. Suomen laki). Siinä mielessä ymmärrän hyvin ehdotuksen tarvetta.

**Comment by mirmaid** [comment]
Vähän epäilen, että erottelu rescue-/löytöeläimiin ei kuitenkaan onnistu käytännössä johdonmukaisesti. Mutta onko eläinlajien mukainen termistökään tarpeen? Löytökissoja on Suomessa varmaan moninkertaisesti löytökoiriin/rescuekoiriin verrattuna, mutta koirista kirjoitetaan kai eniten. 

Kodittomat koirat/kissat -muotojen vaihtaminen päätermiksi muuttaa merkityksiä niin, että eläin ei välttämättä enää ole vapaana, vaan voi olla jo myös otettu talteen, mutta sillä ei vielä ole lopullista kotia.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _löytökoirat_ ja _löytökissat_, ohjaustermeiksi _rescuekoirat_, _rescuekissat_.

**Comment by mariaforsen** [comment]
Sv. 
-hittehundar HT upphittade hundar
-hittekatter HT upphittade katter
http://www.hittehund.se/
https://polisen.se/tjanster-tillstand/hittegods/upphittat-djur/
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_6713f6214b30530039a62647e52a202c&list_id=1&keyword=l%C3%B6yt%C3%B6el%C3%A4in&word=l%C3%B6yt%C3%B6el%C3%A4in
