### ISSUE TITLE
Ukrainan kriisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10451]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ukrainan kriisi](http://www.yso.fi/onto/yso/p38096)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Termin pikainen muutos YSOon ja KOKOon. Nykyinen termi ei vastaa nykyistä tilannetta eli Venäjän hyökäystä Ukrainaan 2022. Olisiko perusteltu termi Venäjän-Ukrainan sota ja/tai Venäjän hyökkäys Ukrainaan 2022.

**Perustelut ehdotukselle**

Nykyinen termi ei vastaa nykyistä sotatilannetta. Ukrainan kriisi termiä ei voi käyttää. Se antaa väärän kuvan nykyisestä sotatilanteesta ja on luokkaava erityisesti ukrainalaisia kohtaan. Se ei ilmaise Venäjän kansainvälisten oikeuksien vastaisia hyökkäystoimia sodassa.

**Ehdottajan organisaatio**

Museoviraston Kuvakokoelmat

**Comment by ilona-x** [comment]
Tätä käsiteltiin YSO-kokouksessa 12.5.2012 ehdotus: https://github.com/Finto-ehdotus/YSE/issues/10225

YSO-kokouksen päätös https://github.com/Finto-ehdotus/YSE/issues/10225#issuecomment-1124847083
