### ISSUE TITLE
klusterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10452]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[klusterit](http://www.yso.fi/onto/yso/p18755)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tarvitseeko jakaa?

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/klusteri

Kielitoimiston sanakirja:

**klusteri** https://www.kielitoimistonsanakirja.fi/#/klusteri

ryväs, kimppu.

Mus. samanaikaisesti soivien sävelten ryhmä, joka tav. käsittää tietyn välin kaikki sävelkorkeudet.

Tilastot. = ryväs.

Tal. useiden toisiaan vuorovaikutteisesti tukevien toimialojen keskittymä, osaamiskeskittymä.
Metsä-, teleklusteri.

Nyt ohjausterminä osaamiskeskittymät, jota ehdotettu YSOon myös omana terminään: https://github.com/Finto-ehdotus/YSE/issues/1540

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Ruotsiksikin ainakin musiikki, tilastotiede ja yritykset. https://svenska.se/saol/?sok=kluster&pz=1

**Comment by AuHo22** [comment]
LC esim. Tone clusters (so. musiikki)
LC Industrial clusters KT Firm clusters
LC Cluster analysis YSO klusterianalyysi
Ja lisäksi muita cluster* sanoja.

**Comment by mirmaid** [comment]
Näitä on kyllä ihan laidasta laitaan, n. 900 viitettä Melindassa. Paljon esim. erilaisia luonnontieteiden väitöskirjoja (fysiikka, kemia, ilmatieteet, tähtitiede). 

https://en.wikipedia.org/wiki/Cluster

**Comment by mirmaid** [comment]
Jos halutaan lähteä jakamaan tätä, vaatisi aika perinpohjaisen selvityksen Melindan suhteen, millainen jako on tehtävissä.

**Comment by tpalonen** [comment]
Klusteri on tosiaan myös musiikkitermi (Ks. http://web.uniarts.fi/1900/sanasto/klusteri_san.html ) mutta löysin pienen etsiskelyn jälkeen kylläkin vain yhden esiintymän Melindasta tässä merkityksessä: Tonaaliset rakenteet Nightwish-yhtyeen musiikissa / Sami Boman
Eli ainakaan Melinda-kuvailun perusteella ei tunnu olevan suurempaa tarvetta käsitteelle musiikkimerkityksessä.

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Klusteri_(taloustiede)

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta. Poistetaan ohjaustermi _osaamiskeskittymät_.
