### ISSUE TITLE
kansanjuhlat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10453]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kansanjuhlat

**Ehdotettu termi ruotsiksi**

folkfester

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

 [yleisötilaisuudet](http://www.yso.fi/onto/yso/p2109), [juhlat](http://www.yso.fi/onto/yso/p1574)

**Ehdotetut temaattiset ryhmät**

 [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/museovirasto.BCE6B76E83A220160C0E0973581FEAA8 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kansanjuhlat](http://finto.fi/yse/fi/page/Y510453)

**Comment by jtuohini** [comment]
Ks. https://github.com/Finto-ehdotus/YSE/issues/10373

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kansanjuhlat_.
