### ISSUE TITLE
historiadokumentit / historialliset dokumentit / historialliset dokumenttielokuvat [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10468]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

historiadokumentit / historialliset dokumentit / historialliset dokumenttielokuvat [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [dokumenttielokuvat](http://www.yso.fi/onto/yso/p13105)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://historiallinen dokumentti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [historiadokumentit / historialliset dokumentit / historialliset dokumenttielokuvat [SLM]](http://finto.fi/yse/fi/page/Y510468)

**Comment by mariaforsen** [comment]
Sv. historiska dokumentärer HT historiedokumentärer, historiadokumentärer, historiska dokumentärfilmer
jfr https://id.kb.se/find?q=historiska ..historiska filmer etc.

**Comment by jtuohini** [comment]
Hyväksytään /SLM

Tarkka muoto päätetään myöhemmin ehdotettujen kolmen kesken.

**Comment by AuHo22** [comment]
https://areena.yle.fi/tv/ohjelmat/30-2390
https://fi.wikipedia.org/wiki/Dokumenttielokuva#Historiadokumentti

**Comment by mirmaid** [comment]
Historiadokumentit KT historialliset dokumentit, historialliset dokumenttielokuvat
