### ISSUE TITLE
kansatieteelliset elokuvat [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10465]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kansatieteelliset elokuvat [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [dokumenttielokuvat](http://www.yso.fi/onto/yso/p13105)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://kansatieteellinen elokuva)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kansatieteelliset elokuvat [SLM]](http://finto.fi/yse/fi/page/Y510465)

**Comment by jtuohini** [comment]
KT-muodoiksi tai jopa päätermiksi _kansatieteelliset dokumentit_ (https://elokuvapolku.kavi.fi/katso-elokuvia/katso-dokumenttielokuvia/) ja _kansatieteelliset dokumenttielokuvat_.

**Comment by mariaforsen** [comment]
Sv. etnografiska filmer/dokumentärer

**Comment by jtuohini** [comment]
Hyväksytään /SLM
Tarkka sanamuoto päätetään myöhemmin ehdotetun kolmen kesken.

**Comment by jtuohini** [comment]
Tenhossa myös **perinne-elokuva** vastaa suunnilleen samaa, mutta on vähemmän "vaativa" kansatieteelliseltä kannalta. Joten neljänneksi pohdittavaksi muodoksi myös _perinne-elokuvat_.

**Comment by ilona-x** [comment]
Elonet:
[kansatieteelliset elokuvat -genren elokuvat ](https://elonet.finna.fi/Search/Results?sort=main_date_str+desc&type=AllFields&filter%5B%5D=%7Egenre_facet%3A%22kansatieteellinen+elokuva%22)

**Comment by AuHo22** [comment]
Aina moni yo- elokuvista näyttäisi olevan dokumentaarinen, eli voisin kannattaa kansatieteelliset dokumentit -termiä. Tämäkin kuitenkin laskettaneen dokumentiksi enemmän: Seitsemän laulua tundralta (Elonetin laji: fiktio & dokumentti) -> -elokuvat-loppuosa slm:ssä on monessa yhteydessä varattu nimenomaan fiktiivisille tuotoksille (vrt. musiikkielokuvat, -dokumentit)

**Comment by mirmaid** [comment]
Kansatieteelliset elokuvat KT kansatieteelliset dokumentit, kansatieteelliset dokumenttielokuvat, perinne-elokuvat

**Comment by mariaforsen** [comment]
Sv. etnografiska filmer OT etnologiska filmer
https://svenska.se/so/?id=117285&ref=lnr144641
https://svenska.se/so/?id=117283&ref=lnr144635
https://id.kb.se/term/saogf/Etnografiska%20filmer

Eng. Ethnographic films? /lcgft
