### ISSUE TITLE
tiedotuselokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10467]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tiedotuselokuvat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [dokumenttielokuvat](http://www.yso.fi/onto/yso/p13105)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://tiedotuselokuva)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [tiedotuselokuvat](http://finto.fi/yse/fi/page/Y510467)

**Comment by AuHo22** [comment]
Voivatko nämä olla myös tietoiskuja, vai ovatko tietoiskut valistusfilmejä?  

https://fi.wikipedia.org/wiki/Tietoisku

https://areena.yle.fi/1-50094984

**Comment by jtuohini** [comment]
Tässä Elonetin kyseiset: https://elonet.finna.fi/Search/Results?lookfor=%22tiedotuselokuva%22&type=Subject

**Comment by AuHo22** [comment]
Minulla ainakin menee vähän sekaisin valistusfilmien kanssa, esim. Osta oikein - valitse viisaasti. 

vrt. https://en.wikipedia.org/wiki/Public_information_film 

Ovatko sitten myös tilauselokuvia, eli ehdotetut määritelmät limittyvät vahvasti toisiinsa. Kansallisbibliografialla lienee oma  käyttötarkoituksensa näille termeille, mutta käyttävätkö lähtökohtaisesti slm-sanastoa eli onko tarvetta välttämättä slm-sanastossa, joskaan eivät haittaakaan?

**Comment by mariaforsen** [comment]
Sv. informationsfilmer

**Comment by mirmaid** [comment]
KÄ opetuselokuvat?

**Comment by jtuohini** [comment]
Tenhossa _tiedotuselokuva_ on neutraalimpi kuin [_valistuselokuva_](https://github.com/Finto-ehdotus/YSE/issues/10463), joka voi olla näkökulmaltaan moraalinen. Yritysten tiedotuselokuvat rajaltaan osin häilyvä suhteessa mainoselokuviin.

Siirretään näiden käsittely tuonnemmaksi /SLM

**Comment by ilona-x** [comment]
Elonet:
[tiedotuselokuvat-genren elokuvat ](https://elonet.finna.fi/Search/Results?sort=main_date_str+desc&type=AllFields&filter%5B%5D=%7Egenre_facet%3A%22tiedotuselokuva%22)

Elonetissä tuorein tällä termillä kuvailtu elokuva näyttää olevan vuodelta 1993

**Comment by AuHo22** [comment]
Esim. ko. yllä olevista elokuvista Työtä terveyden edistämiseksi -synopsis kertoo -> Käytännön esimerkkeinä nuorille annettava sukupuolivalistus, tupakointivalistus ja kansainvälinen yhteistyö. -> myös valistuselokuva? Tai yhtä hyvin Isku tekee kipeää -> molemmat ehkä pyrkivät muuttamaan käyttäytymistä, eikä valistuksen mielestäni aina tarvitse olla moraalistakaan

**Comment by mirmaid** [comment]
Tiedotuselokuvat KT tietoiskut, RT opetuselokuvat

**Comment by mariaforsen** [comment]
Sv. informationsfilmer OT informationsinslag, upplysningsfilmer
https://id.kb.se/find?q=informationsfilmer 
"Genre/formterm för rörlig bild. Icke-fiktiva filmer med samhällsinformation, upplysningsfilm."
https://www.sanakirja.fi/custom/fi-en-sv/tietoisku
jfr https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_c12d642772df9428c8abd1e65f4d6676&list_id=1&keyword=tiedotus&word=tiedotus

**Comment by mirmaid** [comment]
Lisäsin dokumentit-loppuisille uusille käsitteille monihierarkian dokumenttielokuvat + dokumenttiohjelmat. Miten tehdään tämän osalta, termissä "elokuvat", mutta ohjausterminä tietoiskut?

(Huom. myös hierarkialinjauksiin, tähän ei haluttu erikseen elokuvat vs. ohjelmat. Voidaan toki väittää, että kaikki dokumenttiohjelmat ovat dokumenttielokuvia pituudesta riippumatta, mutta se olisi ehkä vähän hassua kun sanastossa kuitenkin on erikseen dokumenttiohjelmat ja dokumenttisarjat.)

**Comment by mirmaid** [comment]
^ Samoin myös _kansatieteelliset elokuvat_.

**Comment by AuHo22** [comment]
#8923 Tässä vaiheessa oli keskustelua hierarkialinjauksista-> SLM-kokous: toistaiseksi monihierarkia

Ks. esim. kyberpunk -> ratkaistu sen mukaisesti: 
YK tieteiselokuvat
YK tieteiskirjallisuus
YK tieteissarjakuvat
YK tieteissarjat

#8652 -> Tässä lisäksi tuhkimotarinat, joiden myötä hierarkiakeskustelu jälleen virisi:
"SLM-käsite tuhkimotarinat on nyt fiktioelokuvien ST. Käytetään myös kirjallisuuteen."

Vrt. veijaritarinat RT veijarielokuvat RT veijariromaanit
Hierarkialinjaukset - monihierarkia?

Molempia on juuri korjattu, mutta ST/RT -suhteet ovat eri tavoin, perusteltavissa?

**Comment by mirmaid** [comment]
^ Varmaan hajonta liittyy juuri siihen, että lopullinen linjaus puuttuu ja ryhmän sisälläkin on ehkä vähän elänyt näkemykset siitä, miten hierarkia pitäisi toteuttaa (ja sekin vaihtelee, miten jonkin genren katsotaan soveltuvan eri aineistotyypeille).

Ehkä tässä issuessa voisi ratkaista nyt nuo elokuvat-termit ainakin toistaiseksi, ja palata laajemmin asiaan syksyllä?

**Comment by mirmaid** [comment]
YK dokumenttielokuvat molemmille.
