### ISSUE TITLE
revyyelokuvat [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10460]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

revyyelokuvat [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [draamaelokuvat](http://www.yso.fi/onto/yso/p26500)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://revyyelokuva)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [revyyelokuvat [SLM]](http://finto.fi/yse/fi/page/Y510460)

**Comment by mariaforsen** [comment]
Sv. revyfilmer

**Comment by mirmaid** [comment]
Ei Elonetissä.

**Comment by mirmaid** [comment]
KÄ musikaalielokuvat

**Comment by mirmaid** [comment]
Ohjaustermi myös YSOon?

**Comment by mariaforsen** [comment]
Revy=före­ställning med blandad under­hållning vanligen med sång, musik och sketcher och ofta med skämtsamma och satiriska an­spelningar på aktuella händelser /Svensk ordbok Ei aivan sama asia ruotsiksi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, laitetaan kuten SLM:ssä.
