### ISSUE TITLE
valistuselokuvat (draamaelokuvat) [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10463]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

valistuselokuvat (draamaelokuvat) [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [draamaelokuvat](http://www.yso.fi/onto/yso/p26500)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://valistuselokuva)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [valistuselokuvat (draamaelokuvat) [SLM]](http://finto.fi/yse/fi/page/Y510463)

**Comment by jtuohini** [comment]
Sittenkään ei tarvitse tarkennetta, ja LT-suhteeksi pelkkä **elokuvat**?

**Comment by jtuohini** [comment]
KT-muodoksi myös _valistusfilmit_ (https://elokuvapolku.kavi.fi/katso-elokuvia/katso-dokumenttielokuvia/).

**Comment by mariaforsen** [comment]
Sv. upplysningsfilmer?

**Comment by mirmaid** [comment]
KÄ opetuselokuvat?

**Comment by mirmaid** [comment]
Ei tarkennetta?

**Comment by mirmaid** [comment]
Ehdotettu, että otetaan erikseen, tai muutetaan opetuselokuvat > opetus- ja valistuselokuvat.

**Comment by ilona-x** [comment]
Elonet: 
[valistuselokuva-genren elokuvat](https://elonet.finna.fi/Search/Results?sort=main_date_str+desc&type=AllFields&filter%5B%5D=%7Egenre_facet%3A%22valistuselokuva%22) uusimmasta vanhimpaan

Elonetissä uusin tälllä termillä kuvailtu elokuva on vuoldelta 1998.

**Comment by AuHo22** [comment]
YSO:ssa esimerkiksi -valistus-loppuiset termit on muutettu muotoon -kasvatus, -neuvonta (mm. terveyskasvatus, terveysneuvonta, terveyden edistäminen). Kansanvalistus-termiä käytetään sitten vain historiallisissa yhteyksissä, pitäisikö valistuselokuvatkin rajata historiallisiin yhteyksiin, se voisi olla yksi vaihtoehto, muuten käyttää nykyaikaisempia tiedotus- tai opetuselokuvat?
Valistusfilmit -muoto myös sopiva historiallisessa yhteydessä? https://elokuvapolku.kavi.fi/katso-elokuvia/katso-dokumenttielokuvia/

**Comment by mirmaid** [comment]
Ei hyväksytty /SLM
