### ISSUE TITLE
yhteiskunnalliset dokumentit [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10469]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yhteiskunnalliset dokumentit [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [dokumenttielokuvat](http://www.yso.fi/onto/yso/p13105)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 julkisaihedokumentit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://yhteiskunnallinen dokumentti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [yhteiskunnalliset dokumentit [SLM]](http://finto.fi/yse/fi/page/Y510469)

**Comment by jtuohini** [comment]
Lisäksi KT-muoto _yhteiskunnalliset dokumenttielokuvat_, tai se peräti päätermiksi. Toiseksi KT-muodoksi myös _sosiaaliset dokumentit_ (Tenho-vastine **sosiaalinen dokumentti**).

**Comment by mariaforsen** [comment]
Sv. samhällsdokumentärer HT sociala dokumentärer
jfr https://finto.fi/slm/fi/search?clang=fi&anylang=on&q=yhteiskunn

**Comment by jtuohini** [comment]
Hyväksytään /SLM

Tarkka sanamuoto päätetään myöhemmin ehdotettujen kesken, ml. sosiaalinen-alkuiset.

**Comment by AuHo22** [comment]
"yhteiskunnallinen" voi sisältää paljonkin aiheita ja sen voi lisätä aika moneen tietueeseen, eli kuinka se rajattaisiin, ja puhutaanko enemmän aiheen tasolla kuvailusta, esim.
 https://yle.fi/aihe/artikkeli/2020/05/14/yle-shortdox-2020-dokumentit-yhteiskunnallisia-aiheita-kasittelevat-teokset
https://seura.fi/tv/poiminnat/kirjallisuuden-nobelin-voittaneesta-annie-ernauxista-kertova-dokumentti-on-yhteiskunnallinen-mutta-intiimi/

Yleensä ne olisivat kai myös ajankohtaisdokumentteja (myös aikalaisdokumentit mukaan lukien), elleivät historiadokumentteja? Melkeinpä tätäkin haluaisi kuvailla aiheitten avulla..

**Comment by mirmaid** [comment]
Yhteiskunnalliset dokumentit KT yhteiskunnalliset dokumenttielokuvat, sosiaaliset dokumenttielokuvat
