### ISSUE TITLE
sikurikasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10475]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sikurikasvit](http://www.yso.fi/onto/yso/p5906)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaanko muotoon sikurit?

**Perustelut ehdotukselle**

On nyt tribus, mutta kasvisukuna voisi olla hyödyllisempi? Vrt. myös latinankielinen muoto ja ks. Laji.fi. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://laji.fi/taxon/MX.39911
Eli Cichorium = sv. cikorior (släkte)/cikoriasläktet 
Ruotsiksi on jo oikeastaan vastine tämä, eli muutos olisi hyvä.

**Comment by mirmaid** [comment]
Sanastossa on myös _sikuri_, joka riittäisi kaikkiin Melindaan viiteen sikurikasvit-viitteeseen.

**Comment by mirmaid** [comment]
Ehdotan siis että poistetaan sikurikasvit, ei muuteta sikurit-muotoon.
