### ISSUE TITLE
koristekasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10476]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koristekasvit](http://www.yso.fi/onto/yso/p489)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään koristekasvien alakäsitteeksi 'daaliat'.

**Perustelut ehdotukselle**

Täsmätermi teokseen, mikä esittelee ainoastaan daalioita. (Teos:  Floret Farm's discovering dahlias)

**Ehdottajan organisaatio**

Kirjastopalvelu/OH

**Comment by ilona-x** [comment]
daaliat hyväksytty YSO-termiksi YSO-kokouksessa 2/2022 https://github.com/Finto-ehdotus/YSE/issues/10421
