### ISSUE TITLE
Ruotsin vallan aika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10474]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ruotsin vallan aika](http://www.yso.fi/onto/yso/p15359)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus Wikidataan (https://www.wikidata.org/wiki/Q12375230)

**Perustelut ehdotukselle**

Siltaus puuttuu

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Harkitaan ruotsiksi myös päätermin muutosta.
