### ISSUE TITLE
alueelliset vastuumuseot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10479]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

alueelliset vastuumuseot

**Ehdotettu termi ruotsiksi**

museer med regionalt ansvar

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Uudistetun museolain (314/2019) mukaan alueelliset ja valtakunnalliset vastuumuseot korvasivat maakunta- ja aluetaidemuseojärjestelmän sekä valtakunnalliset erikoismuseot vuoden 2020 alusta. Alueellisilla vastuumuseoilla on kolme tehtävää: alueellisen museotoiminnan edistäminen, kulttuuriympäristötyö ja alueellinen taidemuseotehtävä. (Wikipedia, Museovirasto)

Ks. myös 
https://www.museovirasto.fi/fi/kulttuuriymparisto/kulttuuriymparistopalvelut-tehtavat-ja-yhteistyo/alueelliset-vastuumuseot-niiden-tehtavat-ja-toimialueet

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [museot](http://www.yso.fi/onto/yso/p4934)

**Ehdotetut temaattiset ryhmät**

 [81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/yso/p26572)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Suomen_alueelliset_vastuumuseot)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-9840-19-9

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [alueelliset vastuumuseot](http://finto.fi/yse/fi/page/Y510479)

**Comment by mariaforsen** [comment]
Rajoittuu sitten varmaan Suomeen, pitäisikö siitä myös huomauttaa? https://fi.wikipedia.org/wiki/Suomen_alueelliset_vastuumuseot

**Comment by ilona-x** [comment]
Ei näytä ainakaan vielä olevan MAOssa.

**Comment by ilona-x** [comment]
Ehdotuksesa mainittu teos: Kulttuuriperintöä, kulttuurielämää : Porvoon museoyhdistys ja Porvoon museo 1896-2021 https://melinda.kansalliskirjasto.fi/byid/018214673

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by fantsby-m** [comment]
Englanniksi täällä:
https://www.museovirasto.fi/en/cultural-environment/duties-and-cooperation-of-cultural-environment-services-department/alueelliset-vastuumuseot-niiden-tehtaevaet-ja-toimialueet

**Comment by mariaforsen** [comment]
Sv. museer med regionalt ansvar HT regionala ansvarsmuseer 
https://www.hamhelsinki.fi/sv/ham-info/for-museiprofessionella/
https://www.museovirasto.fi/sv/kulturmiljo/uppgifter-och-samarbete-i-avdelningen-kulturmiljotjanster/alueelliset-vastuumuseot-niiden-tehtaevaet-ja-toimialueet
