### ISSUE TITLE
teollisuusdokumentit / teollisuusdokumenttielokuvat / teollisuuselokuvat [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10471]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

teollisuusdokumentit / teollisuusdokumenttielokuvat / teollisuuselokuvat [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan elokuvien teosauktoriteettien konvertoimiseksi Elonetistä Marc 21 -formaattiin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [dokumenttielokuvat](http://www.yso.fi/onto/yso/p13105)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tenho](http://teollisuusdokumentti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [teollisuusdokumentit / teollisuusdokumenttielokuvat / teollisuuselokuvat [SLM]](http://finto.fi/yse/fi/page/Y510471)

**Comment by mariaforsen** [comment]
Sv. industridokumentärer HT industrifilmer

https://www.idg.se/2.1085/1.395593/industrifilm-fran-forr-ren-kunskap-fran-filmarkivet

**Comment by jtuohini** [comment]
LCGFT-vastine [**Industrial films**](http://id.loc.gov/authorities/genreForms/gf2011026329).

**Comment by jtuohini** [comment]
Hyväksytään /SLM

Tarkka sanamuoto päätetään myöhemmin ehdotettujen kolmen kesken.

**Comment by mirmaid** [comment]
Teollisuusdokumentit KT teollisuusdokumenttielokuvat, teollisuuselokuvat
