### ISSUE TITLE
psykologinen turvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10473]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

psykologinen turvallisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Psykologinen turvallisuus muuttuu koko ajan tärkeämmäksi esimerkiksi työyhteisöissä. Psykologista turvallisuutta on vasta alettu tutkia Suomessa enemmän, mutta ensimmäisen kerran se on esitelty käsitteenä jo vuonna 1963.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Opinnäytetyöni on valmistumassa Satakunnan Ammattikorkeakoulussa ja se koskee psykologisen turvallisuuden kehittämistä tutkimassani kohdeorganisaatiossa. Asiasanana psykologinen turvallisuus on oleellinen tähän työhön liittyen.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [psykologinen turvallisuus](http://finto.fi/yse/fi/page/Y510473)

**Comment by mariaforsen** [comment]
Sv. psykologisk trygghet https://temahr.se/arbetsmiljo-kultur/psykologisk-trygghet-vad-ar-det-och-vad-sager-forskningen/

Turvallisuus on YSOssa "säkerhet och trygghet", joten sitä ei varmaan kovin helposti käytetä tästä, ainakaan ruotsiksi.

**Comment by mirmaid** [comment]
Aika paljon myös muodossa _psyykkinen turvallisuus_.

**Comment by mariaforsen** [comment]
Myös ruotsiksi HT psykisk trygghet.

**Comment by mirmaid** [comment]
^^^ Suomeksi _turvallisuus_ ei kyllä poissulje psyykkistä 🤔. Mielestäni psyykkinen turvallisuus olisi turvallisuuden alakäsite (ja on vähän jännä, että perusturvallisuus ei ole). 

Myös "henkinen turvallisuus". 

Yhdistelmällä _turvallisuus & henkinen hyvinvointi_ näyttäisi löytyvän tämän aihepiirin aineistoa.

**Comment by YSO-kokous** [comment]
**Päätös**

Jää termiehdotukseksi. Henkistä hyvinvointia ja työilmapiiriä kuvaavaa termistöä on YSOssa jo ennestään melko runsaasti. Termiä pidettiin hyvin laajana, joten tarkempien termien käyttö on suositeltavaa.
