### ISSUE TITLE
hätärahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10482]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hätärahat

**Ehdotettu termi ruotsiksi**

nödmynt

**Ehdotettu termi englanniksi**

notgeld

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan aineiston luetteloinnissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [raha](http://www.yso.fi/onto/yso/p3574)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 mynttecken, emergency coins

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/N%C3%B6dmynt), [MAO/TAO](http://www.yso.fi/onto/mao/p1964), [Tieteen termipankki](https://tieteentermipankki.fi/wiki/Nimitys:mynttecken)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Deutsche Geldgeschichte seit 1914 / Herbert Rittmann (FI-MELINDA)001075615 

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [hätärahat](http://finto.fi/yse/fi/page/Y510482)

**Comment by mariaforsen** [comment]
SAOssa linkki: Emergency currency • lcsh

**Comment by mirmaid** [comment]
Muutama viite Melindassa yksikkö/monikko.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _hätärahat_. Lisätään määritelmä Tieteen termipankista.
