### ISSUE TITLE
rudimentit (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10480]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rudimentit (sävellykset)](http://www.yso.fi/onto/yso/p29991)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan sulkutarkenne "sävellykset".

Muutetaan LT:ksi musiikilliset objektit.

Poistetaan määritelmästä ensimmäinen virke.

**Perustelut ehdotukselle**

Finto-postiin tulleen palautteen perusteella Muusa totesi kokouksessaan, että rudimentit on käsitteenä laajempi kuin tällä hetkellä YSOssa annetaan ymmärtää.

**Ehdottajan organisaatio**

Muusa

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Varmaan täytyy kuitenkin jokin tarkenne olla (musiikki?) Näin ainakin ruotsiksi. 
https://termipankki.fi/tepa/fi/haku/rudimentti
https://www.kielitoimistonsanakirja.fi/#/rudimentti?searchMode=all
https://svenska.se/tre/?sok=rudiment&pz=1

**Comment by mirmaid** [comment]
_Sävellykset_ on kyllä hyvin laaja, sen alla on mm. _improvisaatiot (sävellykset)_. Mutta omasta puolestani näillä molemmillakin voisi olla tarkenteena yhtä hyvin _(musiikki)_.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan tarkenne muotoon _rudimentit (musiikki)_.
