### ISSUE TITLE
Kaikki Helsingin kaupunginosien puuttuvat osa-alueet. Nyt osa löytyy ja osa ei... https://fi.wikipedia.org/wiki/Helsingin_alueellinen_jako

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10481]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kaikki Helsingin kaupunginosien puuttuvat osa-alueet. Nyt osa löytyy ja osa ei... https://fi.wikipedia.org/wiki/Helsingin_alueellinen_jako

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tällä hetkellä tilanne vähän omituinen kuin osa osa-alueista löytyy ja osa ei. Yson avulla ei voi tehdä "samantasoista" kuvailua riippuen paikasta.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ainakin meillä Helsingin kaupunginmuseolla olisi kovasti tarvetta: https://hkm.finna.fi/

**Ehdottajan organisaatio**

Helsingin kaupunginmuseo
**Termiehdotus Fintossa:** [Kaikki Helsingin kaupunginosien puuttuvat osa-alueet. Nyt osa löytyy ja osa ei... https://fi.wikipedia.org/wiki/Helsingin_alueellinen_jako](http://finto.fi/yse/fi/page/Y510481)

**Comment by mirmaid** [comment]
Puuttuu Wikipedia-sivun mukaan:

Vilhonvuori
Linjat
Vanha Ruskeasuo
Pohjois-Pasila
Hermanninmäki
Hermanninranta
Kyläsaari
Maunulanpuisto
Kivihaka
Lassila
Vanha Munkkiniemi
Niemenmäki
Talinranta
Kotkavuori
Vattuniemi
Myllykallio
Honkasuo
Länsi-Pakila
Tuomarinkartano
Latokartano
Viikinranta
Viikin tiedepuisto
Tattariharju
Malmin lentokenttä
Alppikylä
Länsi-Herttoniemi
Herttoniemen yritysalue
Herttoniemenranta
Pitäjänmäen yritysalue
Reimarla
Itäsaaret
Länsisaaret
Keski-Vuosaari
Nordsjön kartano
Niinisaari
Mustavuori
Puroniitty

**Comment by mariaforsen** [comment]
https://kaino.kotus.fi/asutusnimihakemisto/

**Comment by mirmaid** [comment]
Auktorisoidaan ne, jotka löytyvät myös Asutusnimihakemistosta (tai Paikkatietoalustalta osa-alueena).

**Comment by ilona-x** [comment]
Vilhonvuori 🆗 
Linjat 🆗 
Vanha Ruskeasuo 🆗 
Pohjois-Pasila 🆗 
Hermanninmäki 🆗 
Hermanninranta🆗 
Kyläsaari 🆗 
Maunulanpuisto 🆗 
Kivihaka 🆗 
Lassila 🆗 
Vanha Munkkiniemi 🆗 
Niemenmäki 🆗 
Talinranta 🆗 
Kotkavuori 🆗 
Vattuniemi 🆗 
Myllykallio 🆗 
Honkasuo 🆗 
Länsi-Pakila 🆗 
Tuomarinkartano 🆗 
Latokartano 🆗 
Viikinranta 🆗 
Viikin tiedepuisto 🆗 
Tattariharju 🆗 
**Malmin lentokenttä - ei Paikkatietoalustalla eikä Asutusnimihakemistossa ; https://fi.wikipedia.org/wiki/Malmin_lentokentt%C3%A4**
Alppikylä 🆗 
Länsi-Herttoniemi 🆗 
**Herttoniemen yritysalue - Paikanlaji Teollisuus- tai yritysalue http://paikkatiedot.fi/so/1000772/10903037**
Herttoniemenranta 🆗 
**Pitäjänmäen yritysalue - Paikanlaji Teollisuus- tai yritysalue http://paikkatiedot.fi/so/1000772/12021957**
Reimarla 🆗 
Itäsaaret 🆗 
Länsisaaret 🆗 
Keski-Vuosaari 🆗 
**Nordsjön kartano - Paikkatietoalustalla rakennus**
Niinisaari 🆗 
Mustavuori 🆗 
Puroniitty 🆗

**Comment by ilona-x** [comment]
Helsingin osa-alueiden ja kaupunginosien hierarkiaan liittyvä issue: https://github.com/Finto-ehdotus/YSE/issues/11434

**Comment by ilona-x** [comment]
Lisätäänkö seuraavat?

- Malmin lentokenttä - ei Paikkatietoalustalla eikä Asutusnimihakemistossa ; https://fi.wikipedia.org/wiki/Malmin_lentokentt%C3%A4
- Herttoniemen yritysalue - Paikanlaji Teollisuus- tai yritysalue http://paikkatiedot.fi/so/1000772/10903037
- Pitäjänmäen yritysalue - Paikanlaji Teollisuus- tai yritysalue http://paikkatiedot.fi/so/1000772/12021957
- Nordsjön kartano - Paikkatietoalustalla rakennus

**Comment by mirmaid** [comment]
Ei lisätä yllä mainittuja.
