### ISSUE TITLE
syanotypia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10483]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

syanotypia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

cyanotype

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tämä valokuvaustekniikka puuttuu YSOsta. Finna.fi:stä löytyy sanalla parisenkymmentä viitettä. Googlettamalla paljon. Kongressin kirjaston sanastosta löytyy Cyanotypes, https://id.loc.gov/authorities/subjects/sh2021005693.html sekä Blueprinting, https://id.loc.gov/authorities/subjects/sh85015113.html 

**Ehdotettu yläkäsite YSOssa (LT)**

 [valokuvaus tekniikan mukaan](http://www.yso.fi/onto/yso/p7680)

**Ehdotetut temaattiset ryhmät**

 [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [en.wikipedia.org](http://Cyanotype)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Yksi aihetta käsittelevä opinnäytetyö tuli juuri Theseus.fi-julkaisuarkistoon, eikä systeemin Annif sallinut opiskelijan lisätä tätä YSOsta puuttuvaa käsitettä.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [syanotypia](http://finto.fi/yse/fi/page/Y510483)

**Comment by mariaforsen** [comment]
Sv. cyanotyper https://id.kb.se/term/gmgpc/swe/Cyanotyper
Entä sinikopio/blåkopia?

**Comment by ilona-x** [comment]
"Syanotypia eli sinikopio on vanha valokuvan vedostustekniikka, jossa kuva valotetaan rautasuolojen avulla herkistetylle, huokoiselle materiaalille."
Lähde: https://www.artists.fi/fi/loyda-tekijat-ja-teokset/kuvataiteen-osto-opas

"Syanotypia on 1800-luvulta peräisin oleva jalovedostusmenetelmä, joka perustuu kahteen UV-valolla valotettavaan rautasuolaan. Menetelmästä on käytetty myös nimitystä sinikopio."
Lähde: https://kamera-lehti.fi/kauppa/koulutus/syanotypia-tyopaja-16-17-9-2022/

**Comment by ilona-x** [comment]
VALO:
syanotypia  
Ohjaustermit  sinikopiomenetelmät

http://www.yso.fi/onto/valo/p1771

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan tarkemmin.

**Comment by mariaforsen** [comment]
Nationalencyklopedin:  cyanotypi: "fotografisk kopieringsmetod som bygger på järnsalters ljuskänslighet...Som fotografisk metod fick cyanotypi ingen större genomslagskraft, däremot levde principen kvar länge för kopiering av ritningar (blåkopior)."
SAO: cyanotyper: "Blåtonade fotografier framställda med ljuskänsliga järnsalter, vanligen på papper. Introducerades på 1840-talet men användes inte allmänt före 1880. Användes ofta som råkopior."

**Comment by mirmaid** [comment]
Mielestäni tämä on ok: syanotypia KT sinikopio, sinikopiomenetelmä(t)

**Comment by mirmaid** [comment]
syanotypia KT sinikopio (syanotypia), sinikopiomenetelmä(t)

**Comment by mariaforsen** [comment]
Sv. cyanotypi HT blåkopia
