### ISSUE TITLE
voimistelunopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10496]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[voimistelunopettajat](http://www.yso.fi/onto/yso/p21931)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa tai lähinnä yhdistettävissä termiin liikunnanopettajat?

**Perustelut ehdotukselle**

Ks. https://www.kielitoimistonsanakirja.fi/#/voimistelunopettaja?searchMode=all ja https://fi.wiktionary.org/wiki/voimistelunopettaja ja https://www.wikidata.org/wiki/Q2312637  Melindassa käytetty sekavasti, ehkä ruotsin vastineen takia? Ruotsiksi riittäisi yksi termi (tai sitten nämä selkeästi tarkennettuina). 

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
voimistelunopettajat-termiä käytetty Melindassa 38 kertaa

--

KANTO: Suomen voimistelunopettajaliitto 1912-1972 http://urn.fi/URN:NBN:fi:au:finaf:000027596, seuraaja Suomen liikunnanopettajain liitto

--

"Viimeiset voimistelunopettajat valmistuivat Helsingistä keväällä 1974. Tästä lähtien Suomessa liikunnanopettajia on koulutettu ainoastaan Jyväskylässä."
Lähde: Jumpan jalanjäljiltä akateemiseen maisterintutkintoon / Jukka Lahti http://urn.fi/URN:ISBN:978-951-39-6897-7

**Comment by mirmaid** [comment]
Varmaan on yhdistettävissä - käytetty jonkin verran myös tapauksissa, joissa kyseessä liikunnanohjaaja, ei varsinaisesti liikunnanopettaja (koulussa).

**Comment by mariaforsen** [comment]
Sille eri termi ruotsiksi, idrottsinstruktörer fi. liikunnanohjaajat (myös YSOssa).

**Comment by mirmaid** [comment]
^ Lähinnä kommenttina, että ei voi aina suoraan muuttaa > liikunnanopettajat tietueissa (vaikka en nyt tiedä olisiko se ihan välttämättä väärin, tai enemmän väärin kuin voimistelunopettajat).

**Comment by mirmaid** [comment]
Eli ehdotus on, että yhdistetään, jos ei kukaan vastusta.
