### ISSUE TITLE
pysymättömyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10498]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pysyvyys](http://www.yso.fi/onto/yso/p20306)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pysymättömyys

**Perustelut ehdotukselle**

Ilmeisesti buddhalaisen filosofian käsite. Termi 'vaihtuvuus' ei - oletettavasti - ole aivan sama asia. Teos: Opetuksia pysymättömyydestä ja karmasta

**Ehdottajan organisaatio**

Kirjastopalvelu/OH

**Comment by mariaforsen** [comment]
Tämä on varmaan oikeastaan uusi ehdotus?

Sv. obeständighet tms.

Vaihtuvuus on muuten sv. omsättning, joten sitä ei voi ainakaan ruotsin kannalta käyttää ollenkaan tällaisissa aineistoissa.

**Comment by mirmaid** [comment]
Eli ehdotettu uutena _pysymättömyys_.

Tämä?: https://fi.wikipedia.org/wiki/Anicca

Eikö tähän sovi _muutos_?

**Comment by ilona-x** [comment]
Impermanence (Buddhism)
Variants
    Anicca (Buddhism)
    Anitya (Buddhism)
        http://id.loc.gov/authorities/subjects/sh85064630

**Comment by jarmosaarikko** [comment]
pysymättömyys wikidatassa http://www.wikidata.org/entity/Q220797

**Comment by YSO-kokous** [comment]
**Päätös**

Palataan myöhemmin, jos aihetta tutkittaessa selviää tarvetta.

**Comment by AuHo22** [comment]
Meiltä ehdotetaan käsitettä _katoavaisuus KT pysymättömyys, hetkellisyys_
Ryhmät taiteet ja uskonto, jollei ihan yleisterminä.

Esim. Buddhalaisuuden sanasto http://www.sbu.fi/sanakirja/index.php?title=Buddhalainen_sanasto
->
http://www.sbu.fi/sanakirja/index.php?title=Kolme_olemassaolon_tunnusmerkki%C3%A4

https://www.theseus.fi/bitstream/handle/10024/494088/kohonentitta_opinnaytetyo.pdf?sequence=2&isAllowed=y

**Comment by mariaforsen** [comment]
Kannatan! Katoavaisuus=förgänglighet -tärkeä käsite uskonnossa, filosofiassa, taiteessa jne. 

https://www.sanakirja.fi/custom/en-sv-fi/f%C3%B6rg%C3%A4nglighet

**Comment by mirmaid** [comment]
Ei Melindassa, mutta kuulostaa varsin käyttökelpoiselta. Eng. transience?

**Comment by AuHo22** [comment]
Myös: https://en.wikipedia.org/wiki/Impermanence
Käykö myös kristillisessä kontekstissa, jotain kuitenkin löytyi:
 https://godinallthings.com/2014/10/13/impermanent-things-2/

LC Impermanence (Buddhism)

**Comment by mirmaid** [comment]
katoavaisuus KT pysymättömyys, hetkellisyys

**Comment by mariaforsen** [comment]
Sv. förgänglighet HT obeständighet, flyktighet
