### ISSUE TITLE
pitsineuleet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10493]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pitsineuleet](http://www.yso.fi/onto/yso/p26899)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

kuvioneuleet (ehkä myös jakardineuleet)

**Perustelut ehdotukselle**

Neulonnassa kuvioneulonta on yhtä suuri kokonaisuus kuin pitsineulonta.

**Ehdottajan organisaatio**

Kirjastopalvelu/OH

**Comment by mirmaid** [comment]
Eli tässäkin ilmeisesti ehdotettu kuvioneuleita omana käsitteenään.

**Comment by satuniininen** [comment]
Millaisten aineistojen kuvailussa kuvioneuleita olisi tarkoitus käyttää? Se on käsitteenä aika monitulkintainen ja saattaa käyttäjästä riippuen viitata joko pintakuvioituun neuleesen (kohoneuleet löytyy jo) tai värikuvioituun neuleeseen (kirjoneuleet löytyy, toisaalta myös intarsia yms. tekniikat). Jakardi taitaa mennä enemmän kudonnan puolelle kuin neulonnan.

**Comment by mariaforsen** [comment]
Voi olla hankala ruotsiksi: https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1f0d7ab8b32eb403e54a64146310e845&list_id=1&keyword=kuvioneule&word=kuvioneule ..Sanastossa on jo mönsterstickade plagg = kirjoneuleet 
https://www.kielitoimistonsanakirja.fi/#/kuvioneule?searchMode=all
https://sv.wikipedia.org/wiki/Flerf%C3%A4rgsstickning 

Saisiko näille käsitteille määritelmiä?

**Comment by YSO-kokous** [comment]
**Päätös**

_kohoneuleet_ KT _kuvioneuleet (kohoneuleet)_, _kirjoneuleet_ KT _Kuvioneuleet (kirjoneuleet)_.
