### ISSUE TITLE
Tarto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10499]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Tarto

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Monen kertaa olisin jo tarvinnut, mutta nyt laitan ehdotuksen

**Ehdotettu yläkäsite YSOssa (LT)**

 [Viro](http://www.yso.fi/onto/yso/p104987)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Matkaoppaat esim. jne., nyt kaunokuvailussa

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Tarto](http://finto.fi/yse/fi/page/Y510499)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/10500
