### ISSUE TITLE
asutuspolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10503]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[asutuspolitiikka](http://www.yso.fi/onto/yso/p13697)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mikä tämän merkityskenttä on, olisiko huomautus mahdollinen?

**Perustelut ehdotukselle**

Ruotsiksi vastine on ollut kolonisationspolitik, mutta kolonisation on kaksimerkityksinen sana (att ett tidigare (mer eller mindre) outnyttjat område befolkas och odlas upp, eller att en stat gör ett område till koloni /Nationalencyklopedin) ja nyt tämä on käytetty myös sellaisista julkaisuista kuin esim. 
-Slaves, Danes, and African coast society : the Danish slave trade from West Africa and Afro-Danish relations on the eighteenth-century Gold Coast  
-The Oxford history of the British Empire. Vol. 1, The origins of empire : British overseas enterprise to the close of the seventeenth century....

Onko tämä ok suomeksi (että käytetään kolonisaatiosta) vai pitääkö ainakin ruotsiksi jotenkin selkeyttää?

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Vaihtoehtoina päätermin vaihto > bosättningspolitik tai mahdollisesti tarkenteen lisäys > kolonisationspolitik (bosättning) tms.?

**Comment by mirmaid** [comment]
^ Kumpi tahansa näistä on mielestäni ok. Pääasia on, että termi ei viittaa siirtomaapolitiikkaan. Suomeksi asutuspolitiikka tarkoittaa sekä alueen asuttamista, että ihmisten asuttamista jonnekin, mutta ei mitään siirtomaa-asiaa (tai korkeintaan asutuspolitiikkaa siirtomaassa).

**Comment by YSO-kokous** [comment]
**Päätös**

Tarkennetaan ruotsiksi.

**Comment by mariaforsen** [comment]
Sv. bosättningspolitik HT kolonisationspolitik (bosättning), koloniseringspolitik (bosättning)
https://www.sanakirja.fi/custom/fi-en-sv/asutus
https://termipankki.fi/tepa/fi/haku/asutus
https://fho.sls.fi/search?q=asutus&svenskatiden=on&autonomatiden=on&sjalvstandighetstiden=on&year_from=&year_to=
