### ISSUE TITLE
musiikin tulkinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10501]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[musiikin tulkinta](http://www.yso.fi/onto/yso/p29842)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT: tulkinta (musiikki)

**Perustelut ehdotukselle**

Ohjausterminä, jotta käytetään oikein

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
