### ISSUE TITLE
Tartto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10500]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Tartto](http://www.yso.fi/onto/yso/p107486)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi Tarto

**Perustelut ehdotukselle**

En löydä tätä termiä, suomenkielinen termi Tartto lienee perua viron kielen pidennetystä äännemuodosta. Pakostakin välillä kuulostaa vähän vanhahtavalta. 

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mirmaid** [comment]
Kaupungin nimi suomeksi kuitenkin on Tartto, eikä nimeä Tarto mainita suomenkielisissä lähteissä.

**Comment by ilona-x** [comment]
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=2061&ex=Tartto

**Comment by mirmaid** [comment]
Ei lisätä.
