### ISSUE TITLE
poliittiset toimittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10504]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

poliittiset toimittajat

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisäys: poliittiset toimittajat

**Perustelut ehdotukselle**

Puuttuu toimittajat-listauksesta

**Ehdottajan organisaatio**

Kirjastopalvelu/OH

**Termiehdotus Fintossa:** [poliittiset toimittajat](http://finto.fi/yse/fi/page/Y510504)

**Comment by mariaforsen** [comment]
Sv. politiska redaktörer / politiska journalister / politiska reportrar

**Comment by ilona-x** [comment]
Pitäisikö olla kuitenkin politiikan toimittajat?  
https://www.politiikantoimittajat.fi/

**Comment by LeKorsu** [comment]
Ehdottomasti politiikan toimittajat!

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _politiikan toimittajat_.

**Comment by mariaforsen** [comment]
Sv. politiska journalister HT politikjournalister, politiska reportrar, politiska redaktörer
jfr https://finto.fi/yso/fi/search?clang=sv&anylang=on&q=*toimittajat
https://www.politiikantoimittajat.fi/pa-svenska/
