### ISSUE TITLE
Hiirijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10509]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Hiirijärvi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kylä Harjavallassa.

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [Harjavalta](http://www.yso.fi/onto/yso/p94127)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Hiirij%C3%A4rvi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-951-96456-8-1

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Hiirijärvi](http://finto.fi/yse/fi/page/Y510509)

**Comment by ilona-x** [comment]
http://paikkatiedot.fi/so/1000772/10044323
