### ISSUE TITLE
suomumatelijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10508]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suomumatelijat

**Ehdotettu termi ruotsiksi**

fjällbärande kräldjur

**Ehdotettu termi englanniksi**

squamata

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 6

**Ehdotettu yläkäsite YSOssa (LT)**

 [matelijat](http://www.yso.fi/onto/yso/p6614)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

 fjällreptiler

**Alakäsitteet (RT)**

 [liskot](http://www.yso.fi/onto/yso/p11766), [käärmeet](http://www.yso.fi/onto/yso/p10342)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85127082), [wikipedia](https://fi.wikipedia.org/wiki/Suomumatelijat)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Developmental Growth and Regeneration Processes in Squamate Eyes
http://urn.fi/URN:ISBN:978-951-51-6963-1

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [suomumatelijat](http://finto.fi/yse/fi/page/Y510508)

**Comment by mariaforsen** [comment]
Sv. fjällbärande kräldjur https://namnochslaktskap.artfakta.se/taxa/3000297/details HT fjällbärande reptiler, fjällreptiler
