### ISSUE TITLE
glysiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10507]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

glysiini

**Ehdotettu termi ruotsiksi**

glycin

**Ehdotettu termi englanniksi**

glycine

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 2

**Ehdotettu yläkäsite YSOssa (LT)**

 [aminohapot](http://www.yso.fi/onto/yso/p9530)

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [AFO](http://www.yso.fi/onto/afo/p5024), [FinMeSH](http://www.yso.fi/onto/mesh/D005998), [LCSH](http://id.loc.gov/authorities/subjects/sh85055394), [Wikipedia](https://fi.wikipedia.org/wiki/Glysiini)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Leaching and recovery of gold from low grade raw materials in cyanide-free media 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [glysiini](http://finto.fi/yse/fi/page/Y510507)

**Comment by mariaforsen** [comment]
Sv. glycin (aminosyror)
https://svenska.se/tre/?sok=glycin&pz=1
