### ISSUE TITLE
Mommila (Hausjärvi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10505]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Mommila (Hausjärvi)

**Ehdotettu termi ruotsiksi**

Mommila (Hausjärvi)

**Ehdotettu termi englanniksi**

Mommila (Hausjärvi)

**Tarkoitusta täsmentävä selite**

Tämä paikka on Mommilan asemakylä Hausjärvellä Torholan kylässä. Aiemmin Lammiin kuuluneesta kylästä Hausjärvellä Mommilan kartanon ympärillä, katso: Hietoinen (Hausjärvi).

**Perustelut ehdotukselle**

Sekaannusten välttämiseksi olisi parempi, että molemmat Mommilan kylät löytyvät sanastosta.   

Hietoinen (Hausjärvi) -paikkaan voisi lisätä vastaavan selitteen: "Tämä paikka on aiemmin Lammille kuulunut kylä Hausjärvellä Mommilan kartanon ympärillä. Mommilan asemakylä Hausjärvellä, katso Mommila (Hausjärvi)."

**Ehdotettu yläkäsite YSOssa (LT)**

 [Hausjärvi](http://www.yso.fi/onto/yso/p94132)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Mommilan asemakylä

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata: Mommila](http://www.wikidata.org/entity/Q11883141), [Wikipedia: Mommila](https://fi.wikipedia.org/wiki/Mommila)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/musketti_rautatie.M014:SRMV1:2059

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto
**Termiehdotus Fintossa:** [Mommila (Hausjärvi)](http://finto.fi/yse/fi/page/Y510505)

**Comment by mirmaid** [comment]
Niin kauan kuin tätä ei ole sanastossa, sekaannuksen vaaraa ei ole. Jos tämä halutaan lisätä, se tarvitsee muun tarkenteen kuin (Hausjärvi).

**Comment by mirmaid** [comment]
Ei tarvetta toistaiseksi.
