### ISSUE TITLE
gluonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10510]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

gluonit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Nonlinear evolution in the colour glass condensate

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [gluonit](http://finto.fi/yse/fi/page/Y510510)

**Comment by ilona-x** [comment]
voisi käyttää myös tähän väitökseen: http://urn.fi/URN:ISBN:978-951-39-8893-7

**Comment by mariaforsen** [comment]
Sv. gluoner
