### ISSUE TITLE
suhdemyynti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10519]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suhdemyynti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

relationship selling

**Tarkoitusta täsmentävä selite**

https://journal.fi/prologi/article/view/113559/67065
https://erepo.uef.fi/handle/123456789/26434

**Perustelut ehdotukselle**

Olisi tarvittu sisällönkuvailussa, termi puuttuu YSOsta

**Ehdotettu yläkäsite YSOssa (LT)**

 [myynti](http://www.yso.fi/onto/yso/p15269), [suhteet](http://www.yso.fi/onto/yso/p1372)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/26434

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [suhdemyynti](http://finto.fi/yse/fi/page/Y510519)

**Comment by mariaforsen** [comment]
Sv. relationsförsäljning

**Comment by mirmaid** [comment]
KÄ yritysmyynti? http://www.yso.fi/onto/yso/p25650

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermiksi _yritysmyynnille_.
