### ISSUE TITLE
sosiaalioppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10516]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sosiaalioppaat](http://www.yso.fi/onto/yso/p17693)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan käsite SLM:stä

**Perustelut ehdotukselle**

Ei ole itsenäinen teostyyppinsä. Helppo ilmaista kuvailussa yhdistämällä aihe 650-kentässä/-kentissä + SLM-termi "oppaat (teokset)" 655-kentässä. Melindassa tällä hetkellä 0 tietuetta, jossa mainittua on käytetty.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
YSO-terminä käytetty 174 kertaa, mutta ehkä ei sitten tarvita genreterminä. (Toinen muoto sosiaaliturvaopas? https://sosiaaliturvaopas.fi/ )

**Comment by mirmaid** [comment]
Tutkitaan lisää.

**Comment by mirmaid** [comment]
Tätä on kyllä käytetty YSO-terminä nimen omaan genrenä, mutta viimeksi v. 2007. Sisällöt varmaan siirtyneet verkkoon.

**Comment by AuHo22** [comment]
Sosiaalioppaat KÄ sosiaaliturvaoppaat (kaikkinensa selkeämpi?)

**Comment by mirmaid** [comment]
Vaihdetaan sosiaalioppaat KÄ sosiaaliturvaoppaat /SLM.

**Comment by mariaforsen** [comment]
Sv. guider för social trygghet HT guider om social trygghet, socialskyddsguider 
https://sosiaaliturvaopas.fi/social-trygghet-guide/
https://www.sanakirja.fi/custom/fi-en-sv/sosiaaliturva
https://termipankki.fi/tepa/fi/haku/sosiaaliturva
https://thl.fi/sv/web/handbok-om-funktionshinderservice/stod-och-service/forsakringar-socialskydd-och-beskattning
jfr https://finto.fi/yso/fi/page/p17693?clang=sv 
se https://www.hel.fi/helsinki/sv/social-och-halso/barnfamiljens/familjers-specialtjanster/socialhandledning/

**Comment by mirmaid** [comment]
Muutos myös YSOon?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _sosiaaliturvaoppaat_.
