### ISSUE TITLE
myoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10512]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

myoni

**Ehdotettu termi ruotsiksi**

myon

**Ehdotettu termi englanniksi**

muon

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [leptonit](http://www.yso.fi/onto/yso/p4031)

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Myoni)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://lutpub.lut.fi/handle/10024/162686

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [myoni](http://finto.fi/yse/fi/page/Y510512)

**Comment by fantsby-m** [comment]
Ehdotus siis monikossa: myonit, EN muons, SV myoner.

**Comment by mariaforsen** [comment]
Sv. myoner HT muoner, μ-partiklar 
https://termipankki.fi/tepa/en/search/myoni
