### ISSUE TITLE
algerialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10522]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

algerialaiset

**Ehdotettu termi ruotsiksi**

algerisk

**Ehdotettu termi englanniksi**

Algerian

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-381-070-9 
https://melinda.kansalliskirjasto.fi/F/SC5MJRUYG3HQ19E1U5CH8FUC94UG2EV2NF8GX9L7LG9KPMLM7R-18426?func=full-set-set&set_number=009991&set_entry=000001&format=999

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [algerialaiset](http://finto.fi/yse/fi/page/Y510522)

**Comment by mariaforsen** [comment]
Sv. algerier
