### ISSUE TITLE
sosiaalisen läpäisyn teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10521]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sosiaalisen läpäisyn teoria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

social penetration theory

**Tarkoitusta täsmentävä selite**

https://www.jyu.fi/hytk/fi/laitokset/kivi/opiskelu/tutkinto-ohjelmat-ja-oppiaineet/viestinta/opiskelu/sanasto/viestinnan-sanasto-23052017.pdf
https://erepo.uef.fi/bitstream/handle/123456789/26434/urn_isbn_978-952-61-4383-5.pdf?sequence=1&isAllowed=y
"Social penetration theory (SPT) is defined as a
theory that explains interpersonal relationship
development over time in phases via the process
of relational cost and reward evaluation and
self-disclosure (Altman, 1993; Altman & Taylor,
1973; Altman, Vinsel, & Brown, 1981). "

**Perustelut ehdotukselle**

Olisi tarvittu sisällönkuvailussa, puuttuu YSOsta

**Ehdotettu yläkäsite YSOssa (LT)**

 [sosiaaliset suhteet](http://www.yso.fi/onto/yso/p411)

**Ehdotetut temaattiset ryhmät**

 [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/26434

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [sosiaalisen läpäisyn teoria](http://finto.fi/yse/fi/page/Y510521)

**Comment by mariaforsen** [comment]
Sv. sociala penetrationsteorin HT social penetrationsteori 
http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A974663&dswid=639

**Comment by mirmaid** [comment]
Melindassa vain ko. aineisto.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Social_penetration_theory. On käännetty suomeksi noin, hyvin vähän kyllä löytyy Googlella.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
