### ISSUE TITLE
kenialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10524]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kenialaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Kenyans

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://en.wiktionary.org/wiki/Kenyan](http://Kenyan)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/F/SC5MJRUYG3HQ19E1U5CH8FUC94UG2EV2NF8GX9L7LG9KPMLM7R-00279?func=find-b&request=978-0-86154-387-8&find_code=WRD&x=0&y=0

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [kenialaiset](http://finto.fi/yse/fi/page/Y510524)

**Comment by mariaforsen** [comment]
Sv. kenyaner
