### ISSUE TITLE
arvot (käsitykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10529]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[arvot (käsitykset)](http://www.yso.fi/onto/yso/p1044)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "arvomaailma"

**Perustelut ehdotukselle**

Kielitoimiston sanakirjan mukaan arvomaailma on yhtä kuin "arvojen kokonaisuus, arvot" (https://www.kielitoimistonsanakirja.fi/arvomaailma)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi.
