### ISSUE TITLE
kouristukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10538]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kouristukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/334907

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kouristukset](http://finto.fi/yse/fi/page/Y510538)

**Comment by ilona-x** [comment]
Esimerkkiaineistossa tämä näyttäisi olevan englanniksi seizures, minkä suomenkielinen vastine näyttäisi olevan FinMeSHissä [kohtaukset](http://www.yso.fi/onto/mesh/D012640). Ja YSOssa on sairauskohtaukset KT kohtaukset (sairauskohtaukset) eng [seizures (medicine)](https://finto.fi/yso/fi/page/p19057?clang=en)



Aineistossa mainitaan esim. epilepsia ja kuumekouristukset, joten olisikohan tässä parempi käyttää joko termiä sairaskohtaukset tai sitten tarvittaessa ottaa tarkempia termejä, esim. [kuumekouristukset](https://finto.fi/mesh/fi/page/D003294) löytyy myös FinMeSHistä.

**Comment by mirmaid** [comment]
Pelkkä _sairauskohtaukset_ on kyllä todella laaja.

**Comment by mariaforsen** [comment]
Kouristus on ruotsiksi kramp tai spasm, ja se täsmää Kielitoimiston sanakirjan kanssa: "tahdosta riippumaton, us. tuskallinen lihassupistus, kramppi, spasmi." En sekoittaisi sitä näihin muihin mainittuihin (paljon laajempiin) termeihin.

**Comment by ilona-x** [comment]
samat Marian mainitsemat merkitykset kouristukselle myös täällä: https://www.terveyskirjasto.fi/ltt01761/kouristus

spasmi = kouristus; lihaksen (lihasten) voimakas, muutaman sekunnin tai minuutin kestävä supistus; vrt. [konvulsio](https://www.terveyskirjasto.fi/ltt01732/konvulsio)
konvulsio = lihasten laaja lyhytkestoinen kouristus tai kohtaussarja; vrt. [spasmi](https://www.terveyskirjasto.fi/ltt03200/spasmi)

**Comment by ilona-x** [comment]
Ehdotuksessa mainitussa aineistossa käsiteltiin lasten erilaisia kouristuskohtauksia kuten epilepsiakohtauksia ja kuumekouristuksia, eli mielestäni tuossa väitöksessä sairauskohtaus on lähempänä oikeaa termiä kuin kouristus, tai ainakaan tuossa väitöksessä käsitellyistä kouristuskohtauksista ei voisi käyttää spasmi tai konvulsio, jotka viittaavat lihaskouristuksiin 🤔 

Väitöksessä on määritelty seizure (käännetty suomenkielisessä tiivistelmässä kohtaus) näin:

"Seizure
The International League Against Epilepsy (ILAE) and the International Bureau for
Epilepsy (IBE) define an epileptic seizure as "a transient occurrence of signs and /or
symptoms due to abnormal excessive or synchronous neuronal activity in the brain" [70].
To differentiate an epileptic seizure from any type of severe or acute incident (such as
"heart seizure"), authors underline the "epileptic" in the definition. In the present work,
a seizure refers to an epileptic seizure, unless otherwise stated."
Lähde: https://helda.helsinki.fi/handle/10138/334907

**Comment by mirmaid** [comment]
Pitää ehkä tutkia tätä lisää. Sairauskohtaushan voi olla vaikka sydänkohtaus, ja sitten taas puhutaan krampeista jos joku yksittäinen lihas on ongelma. Voi toki olla, että pahemmille kouristuskohtauksille ei sitten ole hyvää yleispätevää termiä.

Lääketieteen termit: 
kouristus: 1. paikallinen kouristus; ks. spasmi, lihaskouristus; 2. yleistynyt kouristus; ks. konvulsio
konvulsio: kouristus | lihasten laaja lyhytkestoinen kouristus tai kohtaussarja; ks. myös eklampsia, epileptinen kohtaus, kuumekouristukset

Eli se mistä tässä puhutaan, on mielestäni tuo merkitys 2. yleistynyt kouristus, konvulsio.

**Comment by YSO-kokous** [comment]
**Päätös**

Seuraava kokous.

**Comment by mirmaid** [comment]
Tässäkin olisi sopinut: https://helda.helsinki.fi/handle/10138/330906

**Comment by ilona-x** [comment]
Voisiko **kouristuskohtaukset** olla mahdollinen termi näille vakavammille kouristuksille. Luulisi, että se ei ainakaan sekoittuisi lihaskouristuksiin 🤔 Ja ehkä voisi ottaa samalla myös **lihaskouristus** -termin (FinMeSH: [lihaskouristus](https://finto.fi/mesh/fi/page/D009120))?

**Comment by mariaforsen** [comment]
Lihaskouristukset=muskelkramper olisi hyvä.

**Comment by mirmaid** [comment]
_Kouristuskohtaukset_ (eng. convulsions, LCSH http://id.loc.gov/authorities/subjects/sh85031755) kuulostaisi toimivalta. Ja miksei myös _lihaskouristukset_ KT krampit, suonenveto. Vähän vaihtelee eri lähteissä, pidetäänkö _kramppia_ ja _spasmia_ samana asiana. 
Lääketieteen termit:
spasmi: _kouristus, ”kramppi” | lihaksen (lihasten) voimakas, muutaman sekunnin tai minuutin kestävä supistus, vrt. lihaskouristus_
lihaskouristus: _lihaskramppi, ”suonenveto” | lihassyiden suhteellisen pitkään kestävä tahaton supistus, joka voi johtua useasta syystä_ 

LCSH: Spasms http://id.loc.gov/authorities/subjects/sh85126339, linkattu Krampf https://d-nb.info/gnd/4193786-7, Wikidatassa erikseen, Wikipedia-artikkeleissa hajontaa
FinMeSHissä on sekä spasmi, että spasmi KÄ lihaskouristus

**Comment by mirmaid** [comment]
Kouristuskohtaukset ja lihaskouristukset erikseen.

**Comment by mariaforsen** [comment]
Sv. -krampanfall HT konvulsioner 
-muskelkramper HT sendrag, spasmer, muskelspasmer 

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_5bd9079942e7baa2b4004e665bd17865&list_id=1&keyword=kouristuskohtaus&word=kouristuskohtaus
https://www.sanakirja.fi/custom/en-sv-fi/kouristuskohtaus
https://svenska.se/tre/?sok=krampanfall&pz=1

https://www.sanakirja.fi/custom/en-sv-fi/lihaskouristus
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_10bc5ce8c49e306522be3b362541d144&list_id=1&keyword=lihaskouristus&word=lihaskouristus
https://svenska.se/tre/?sok=spasm&pz=1
https://svenska.se/tre/?sok=muskelkramp&pz=1
https://mesh.kib.ki.se/term/D013035/spasm
