### ISSUE TITLE
cancel-kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10535]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

cancel-kulttuuri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Cancel culture

**Tarkoitusta täsmentävä selite**

"tarkoitetaan sellaista internet-aktivismia, missä tavoitteena on eristää vääriä mielipiteitä esittävä ihminen, asettaa hänet boikottiin ja saada hänet menettämään työpaikkansa. Tämä tehdään nostamalla henkilö negatiivisen huomion kohteeksi puheistaan tai eleistään, jotka määritellään äärimmäisen sopimattomiksi, vaikka kyse ei ole rikoksista. Teot voivat myös olla vuosikymmeniä vanhoja" wikipedia https://fi.wikipedia.org/wiki/Cancel-kulttuuri
ja
https://www.humak.fi/blogit/cancel-kulttuuri-peruttu-vai-nouseva-trendi/

**Perustelut ehdotukselle**

Tarve käyttää sisällönkuvailussa, käsite puuttuu YSOsta

**Ehdotettu yläkäsite YSOssa (LT)**

 [informaatiovaikuttaminen](http://www.yso.fi/onto/yso/p39619), [boikotti](http://www.yso.fi/onto/yso/p3851)

**Ehdotetut temaattiset ryhmät**

 [80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

 vaientamiskulttuuri, tuomitsemiskulttuuri

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://Cancel culture )

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018034622

**Ehdottajan organisaatio**

Itä-Suomen yliopisto
**Termiehdotus Fintossa:** [cancel-kulttuuri](http://finto.fi/yse/fi/page/Y510535)

**Comment by jtuohini** [comment]
Pitäisikö sanastossa huomioida myös ostrakismi?

**Comment by mariaforsen** [comment]
Sv. cancelkultur https://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1643469&dswid=-9269
SAOssakin on https://id.kb.se/term/sao/Cancelkultur

**Comment by mirmaid** [comment]
LCSH-linkki: http://id.loc.gov/authorities/subjects/sh2020006329

**Comment by mirmaid** [comment]
Ostrakismi missä mielessä?

**Comment by mirmaid** [comment]
Melindassa kerran LCSH Cancel culture.

**Comment by jtuohini** [comment]
Cancel-kulttuurin ja ostrakismin sukulaisuudesta (psykologisessa mielessä, ei antiikin historiallisena käytänteenä) äkkiseltään suomeksi ks. esim. https://anna.fi/hyvinvointi/ostrakismi-on-sosiaalista-kipua, https://www.perustalehti.fi/tag/cancel-kulttuuri/, https://timoeskola.wordpress.com/2021/09/13/mita-on-cancel-kulttuuri-applebaum-ja-keskustelun-uusi-asento/

**Comment by mirmaid** [comment]
Mieltäisin ostrakismin enemmän syrjintänä (jopa KT?) laajemmin ja cancel-kulttuurin nimenomaan tämän ajan ilmiönä. Omaan korvaani se on kovin värittynyt, eikä myöskään terminä hirveän onnistunut (ainakaan täkäläisestä näkökulmasta) - mielestäni kyse on tietynlaisesta ilmiöstä enemmän kuin mistään varsinaisesta "kulttuurista". Mutta noin sitä (kaikilla kielillä) kuitenkin käytetään.

**Comment by LeKorsu** [comment]
Varmasti tarpeellinen käsite, koska se on nyt pinnalla (onko kuinka kauan, on sitten toinen juttu). Cancel-ilmiö olisi minustakin parempi - sikäli kuin tällaiset anglismit ylipäätänsä voivat olla "hyviä" -  kuin cancel-kulttuuri, mutta se ei taida mennä enää läpi. Mutta tuo Wikipedia-määritelmä, että cancelointi koskisi vain ihmisiä, on ihan liian suppea. Eikös tämä koske myös niitä erinäköisiä patsaiden poistamisia yms. Vai olenko ymmärtänyt koko asian ihan väärin?

**Comment by YSO-kokous** [comment]
**Päätös**

Jää termiehdotukseksi.
