### ISSUE TITLE
soranottoalueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10531]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[soranottoalueet](http://www.yso.fi/onto/yso/p24054)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätäänkö OT soranottopaikat ja RT-suhde termiin soranotto?

**Perustelut ehdotukselle**

Synonymi ja liittyvät toisiinsa. https://termipankki.fi/tepa/fi/haku/soranottopaikka

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _sorakuopat_ ohjaustermiksi.
