### ISSUE TITLE
kassava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10537]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kassava

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/329382

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kassava](http://finto.fi/yse/fi/page/Y510537)

**Comment by mariaforsen** [comment]
Sv. maniok /ne, wp HT kassava
https://finto.fi/juho/sv/page/p1767

**Comment by ilona-x** [comment]
käytettäväksi termiksi maniokki KT kassava KT tapioka?


AFO:
[maniokki](https://finto.fi/afo/fi/page/p2058) KT kassava

--

Laji.fi:
Tieteellinen nimi **Manihot esculenta**
Yleiskieliset nimet **maniokki (suomi)** 
http://tun.fi/MX.5009580 

--

fi        
maniokki ★★★☆;
kassava ★★★☆;
tapioka ★★★☆

sv       
maniok ★★★☆

en      
bitter cassava ★★★☆;
mandioca ★★★☆;
tapioca plant ★★★☆;
cassava ★★★☆;
manioc ★★★☆
  
Lähde: IATE 02.02.2022, Euroopan unioni (757438)
https://termipankki.fi/tepa/fi/haku/maniokki

**Comment by ilona-x** [comment]
LCSH:
Cassava
http://id.loc.gov/authorities/subjects/sh85020615

**Comment by mirmaid** [comment]
^^ Ok, kyseisessä julkaisussa käytettiin kassava-nimeä.
