### ISSUE TITLE
jamaikalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10548]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jamaikalaiset

**Ehdotettu termi ruotsiksi**

jamaicanska

**Ehdotettu termi englanniksi**

Jamaican

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4980993

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [jamaikalaiset](http://finto.fi/yse/fi/page/Y510548)

**Comment by mariaforsen** [comment]
Sv. jamaicaner 
https://svenska.se/tre/?sok=jamaicaner&pz=1
