### ISSUE TITLE
Kärsivällisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10546]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kärsivällisyys

**Ehdotettu termi ruotsiksi**

Tålamod

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvittaisiin aihetta käsittelevän kirjan kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Är vi inte framme snart? : väntan, längtan och tålamod 9789173879415

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Kärsivällisyys](http://finto.fi/yse/fi/page/Y510546)

**Comment by mariaforsen** [comment]
https://id.kb.se/term/sao/T%C3%A5lamod lc-linkki patience

**Comment by mirmaid** [comment]
Melindassa 5 kertaa tietoaineistossa (nimekkeissä maltti, itsekuri).

**Comment by mirmaid** [comment]
Sanastossa on _odottaminen_.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
