### ISSUE TITLE
energianhallinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10545]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[energianhallinta](http://www.yso.fi/onto/yso/p2388)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

onko huomautus tarpeellinen vai voisiko sen poistaa?

Huomautus
Tarkoittaa tuotantolaitoksessa, tavallisimmin prosessiteollisuudessa tapahtuvaa energiantuotannon ja energiankäytön suunnittelua ja toteutusta siten, että kokonaiskustannukset jäävät mahdollisimman pieniksi.

**Perustelut ehdotukselle**

termiä käytetty Melindassa muissakin yhteyksissä kuin teollisuudessa, esim. rakennukset

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
RT energiankulutus (energiateknologia)?
RT energiatehokkuus?

**Comment by ilona-x** [comment]
englanniksi nyt energy control pitäisikö olla energy management?
ks. https://termipankki.fi/tepa/fi/haku/energianhallinta

**Comment by mariaforsen** [comment]
Harkitaan myös ruotsiksi olisiko energiadministration tai energiledning mahdollinen vastine.
https://termipankki.fi/tepa/fi/haku/energiledningssystem
https://termipankki.fi/tepa/fi/haku/energiadministration
https://www.svenskcertifiering.se/sida7.html
https://www.rikstermbanken.se/termposter/2349/energiledning "systematiskt arbetssätt som syftar till att uppnå ständig förbättring av en organisations energiprestanda"

Melindassa näyttäisi olevan aika paljon energy management. Tästä löytyy standardikin: https://sfs.fi/standardeista/tutustu-standardeihin/suositut-standardit/iso-50001-energianhallinta/ Onko sama asia?

**Comment by YSO-kokous** [comment]
**Päätös**

Tiivistetään huomautusta.

**Comment by mariaforsen** [comment]
Sv. energihantering HT energikontroll, energiadministration, energiledning 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a5fd448e5dac62e956166021a158826a&list_id=1&keyword=hallinta&word=hallinta
https://www.motiva.fi/sv/offentliga_sektorn/den_offentliga_sektorns_energieffektivitetsplan
https://www.energimyndigheten.se/energieffektivisering/jag-vill-energieffektivisera-min-organisation/vagledning-och-hjalp/energiledning/
https://termipankki.fi/tepa/fi/haku/energiledningssystem
https://termipankki.fi/tepa/fi/haku/energiadministration
https://www.svenskcertifiering.se/sida7.html
https://www.rikstermbanken.se/termposter/2349/energiledning 
https://www.epv.fi/sv/hallbarhet/energihantering/
https://finto.fi/yso/fi/search?clang=sv&anylang=on&q=*hallinta
energiledning=energiajohtaminen?
