### ISSUE TITLE
venezuelalainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10544]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

venezuelalainen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Venezuelans

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [eteläamerikkalaiset](http://www.yso.fi/onto/yso/p5188)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/piki.4846861

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [venezuelalainen](http://finto.fi/yse/fi/page/Y510544)

**Comment by petraunk** [comment]
Oikea muoto monikossa: venezuelalaiset

**Comment by mariaforsen** [comment]
Sv. venezuelaner HT venezolaner /svenska.se
