### ISSUE TITLE
brasilialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10543]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

brasilialaiset

**Ehdotettu termi ruotsiksi**

brasiliansk

**Ehdotettu termi englanniksi**

Brazilian

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [eteläamerikkalaiset](http://www.yso.fi/onto/yso/p5188)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Kielitoimiston sanakirja](https://www.kielitoimistonsanakirja.fi/#/brasilialainen)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/piki.4770587

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [brasilialaiset](http://finto.fi/yse/fi/page/Y510543)

**Comment by mariaforsen** [comment]
Sv. brasilianer HT brasilianare
https://id.kb.se/term/sao/Brasilianare
https://svenska.se/tre/?sok=brasilianer&pz=1
https://tt.se/tt-spraket/ord-och-begrepp/internationellt/stat-och-nationalitet/
