### ISSUE TITLE
bangladeshilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10542]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

bangladeshilaiset

**Ehdotettu termi ruotsiksi**

bangladeshier

**Ehdotettu termi englanniksi**

Bangladeshis

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Bangladeshis)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/eepos.2841503#details

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [bangladeshilaiset](http://finto.fi/yse/fi/page/Y510542)

**Comment by mariaforsen** [comment]
Sv. bangladeshier /sao HT bangladeshare /ne
https://svenska.se/tre/?sok=bangladeshier&pz=1
