### ISSUE TITLE
TIG-hitsaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10540]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

TIG-hitsaus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://lutpub.lut.fi/handle/10024/163056

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [TIG-hitsaus](http://finto.fi/yse/fi/page/Y510540)

**Comment by ilona-x** [comment]
LCSH: Gas tungsten arc welding http://id.loc.gov/authorities/subjects/sh85053344

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/TIG-hitsaus

Reilut 10 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. TIG-svetsning HT gasvolframsvetsning
https://www.rikstermbanken.se/termposter/784/gasvolframsvetsning

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään,
