### ISSUE TITLE
eteläafrikkalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10547]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

eteläafrikkalaiset

**Ehdotettu termi ruotsiksi**

sydafrikan

**Ehdotettu termi englanniksi**

South African

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus kenttään 386

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.5007465

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [eteläafrikkalaiset](http://finto.fi/yse/fi/page/Y510547)

**Comment by mariaforsen** [comment]
Sv. sydafrikaner
