### ISSUE TITLE
sovellusrajapinnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10541]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sovellusrajapinnat

**Ehdotettu termi ruotsiksi**

programmeringsgränssnitt för applikationer

**Ehdotettu termi englanniksi**

Application program interfaces (Computer software)

**Tarkoitusta täsmentävä selite**

IATE4
fi        sovellusrajapinta;
ohjelmointirajapinta;
sovellusliittymä;
API
sv       gränssnitt för applikationsprogrammering;
applikationsprogrammeringsgränssnitt;
gränssnitt för tillämpningsprogram;
programmeringsgränssnitt;
API
en      application program interface;
application programming interface;
API
  
Lähde: IATE 02.02.2022, Euroopan unioni (855315)
https://termipankki.fi/tepa/fi/haku/application%20program%20interface	

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda:
ohjelmointirajapinta x 4
ohjelmointirajapinnat x 3

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

 API, ohjelmointirajapinnat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH: Application program interfaces (Computer software)](http://id.loc.gov/authorities/subjects/sh98004527), [Wikidata](https://www.wikidata.org/wiki/Q165194)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-64-0594-0

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [sovellusrajapinnat](http://finto.fi/yse/fi/page/Y510541)

**Comment by ilona-x** [comment]
vai voiko sovellusrajapinnat ohjata rajapinnat (tietokoneohjelmat) -käsitteeseen? 

rajapinnat (tietokoneohjelmat) on linkattu LCSH-termiin Computer interfaces http://id.loc.gov/authorities/subjects/sh85029507, mikä vaikuttaisi viittaavan laitteisiin?

**Comment by mariaforsen** [comment]
Ruotsiksi programmeringsgränssnitt (fi. ohjelmointirajapinta) enemmän käytetty, onko syytä miksei se voisi olla päätermi (jos siis on pakko ottaa erillisenä terminä) ? 
https://it-ord.idg.se/ord/programmeringsgranssnitt/
https://valtioneuvosto.fi/sv/-//10623/gemensamma-principer-for-utvecklingen-av-programmeringsgranssnitt-inom-den-offentliga-forvaltningen

**Comment by juhoinkinen** [comment]
Minusta yksinkertaista olisi jos sekä ohjelmointirajapinta ja sovellusrajapinta molemmat ohjaisivat rajapinnat (tietokoneohjelmat) -käsitteeseen. Tai sitten vähän yksityiskohtaisempaa olisi, jos ohjelmointirajapinta olisirajapinnat (tietokoneohjelmat) -käsitteen alakäsite, ja sovellusrajapinta ohjaisi jompaan kumpaan (en oikein tiedä kumpaan kuuluisi). Periaatteessa rajapintojen alla voisi olla myös ainakin komentorivirajapinta.

Mutta tuo on kummallisesti, että [rajapinnat (tietokoneohjelmat)](http://www.yso.fi/onto/yso/p27641) on hierarkiassa tietokoneohjelmien alla. Rajapinta on tietojärjestelmissä ja -ohjelmissa joittenkin toimintojen kokonaisuus; ei mikään tietty ohjelma tai ohjelmatyyppi, niinkuin nuo muut tietokoneohjelmien alla listatut käsitteet ovat. 

Parempi olisi, jos rajapinnat (tietokoneohjelmat) -käsite olisi yhtä tasoa ylempänä tekniset objektit (abstraktit objektit) -käsitteen alla. Ja ehkä vielä vähän laajemmalla määrittelyllä: ~rajapinnat (tietojenkäsittely)~ edit: rajapinnat (tietotekniikka), niin se voisi kattaa myös rajapinnat laitteistojen kanssa/välillä.

**Comment by mirmaid** [comment]
Eli Juhon ehdotus:
rajapinnat (tietokoneohjelmat) > rajapinnat (tietojenkäsittely), YK tekniset objektit

Ohjelmointirajapinnat joko ohjausterminä edelliselle, tai erikseen.

Sovellusrajapinnat ohjausterminä jommalle kummalle.

**Comment by osma** [comment]
Juhon ehdotus on minusta muuten hyvä, mutta näen ongelman siinä, että se niputtaa kaikentyyppiset tietotekniikan rajapinnat yhteen käsitteeseen. Kuitenkin esim. Termipankin huomautuksessa todetaan näin:

> Ohjelman ja käyttäjän välisen rajapinnan muodostaa [käyttöliittymä](https://termipankki.fi/tepa/mot/mot.exe?Opt=256&ListWord=@40@40ID@3D@22TSKTT@2DID0114@22&SearchWord=application+program+interface&dic=1&page=results&UI=figr&Source=Record).

Rajapintoja (interface) on tosiaan sekä ohjelmistojen/sovellusten välisiä (API), laitteistojen kanssa/välillä että myös käyttäjän suuntaan. Suomen kielessä käytetään termiä käyttöliittymä (eikä yleensä esim. käyttörajapinta tai käyttäjärajapinta), mutta ruotsiksi ja englanniksi yhteys muihin rajapintoihin on selkeämpi: användar**gränssnitt**, user **interface**.

Voisiko olla jotenkin näin:

* rajapinnat (tietojenkäsittely), YK tekniset objektit (tai tekniset järjestelmät?)
* ohjelmointirajapinnat YK rajapinnat (tietojenkäsittely)
  * ohjaustermit: sovellusrajapinnat, API...
* laitteistorajapinnat YK rajapinnat (tietojenkäsittely)
  * tätä ei ole pakko lisätä jos ei ole tarvetta, mutta jos tarvitaan, niin tämä olisi sen looginen paikka
* käyttöliittymät YK rajapinnat (tietojenkäsittely)

Näistä [käyttöliittymät](http://www.yso.fi/onto/yso/p1295) löytyy jo YSOsta, voisi harkita sen siirtoa rajapinnat (tietojenkäsittely) -käsitteen alle kuten yllä.

**Comment by YSO-kokous** [comment]
**Päätös**

Käsite _rajapinnat (tietokoneohjelmat)_ muutetaan muotoon _rajapinnat (tietojenkäsittely)_. Käsite _sovellusrajapinnat_ ohjaustermiksi käsitteelle _ohjelmointirajapinnat_.

**Comment by mariaforsen** [comment]
Sv. programmeringsgränssnitt HT API, applikationsprogrammeringsgränssnitt, gränssnitt för applikationsprogrammering, gränssnitt för tillämpningsprogram, applikationsgränssnitt
https://it-ord.idg.se/ord/programmeringsgranssnitt/
https://sv.wikipedia.org/wiki/Applikationsprogrammeringsgr%C3%A4nssnitt
https://www.rikstermbanken.se/termposter/2918/API
