### ISSUE TITLE
zimbabwelaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10552]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

zimbabwelaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.5022081

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [zimbabwelaiset](http://finto.fi/yse/fi/page/Y510552)

**Comment by mariaforsen** [comment]
Sv. zimbabwier
https://svenska.se/tre/?sok=zimbabwier&pz=2
