### ISSUE TITLE
prioritarismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10556]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

prioritarismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

prioritarianism

**Tarkoitusta täsmentävä selite**

Englanninkielinen selitys : 
https://en.wikipedia.org/wiki/Prioritarianism

**Perustelut ehdotukselle**

Tarvittu sisällönkuvailussa, termi puuttuu YSOsta

**Ehdotettu yläkäsite YSOssa (LT)**

 [teoriat](http://www.yso.fi/onto/yso/p127)

**Ehdotetut temaattiset ryhmät**

 [02 Filosofia](http://www.yso.fi/onto/yso/p26545)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018208272

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [prioritarismi](http://finto.fi/yse/fi/page/Y510556)

**Comment by mariaforsen** [comment]
Sv.  prioritarism /http://www.diva-portal.se/smash/get/diva2:868461/FULLTEXT02.pdf https://www.vardanalys.se/wp-content/uploads/2020/06/Rapport-2020-7-Styra-mot-horisonten.pdf HT prioritarianism

**Comment by mirmaid** [comment]
Filosofian sanakirja ei tunne tätä. Hyvin vähän suomeksi Googlella, mutta on kuitenkin ihan selkeä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
