### ISSUE TITLE
srilankalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10551]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

srilankalaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Sri Lankans

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4917901

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [srilankalaiset](http://finto.fi/yse/fi/page/Y510551)

**Comment by mariaforsen** [comment]
Sv. srilankeser
https://svenska.se/tre/?sok=srilankes&pz=2
