### ISSUE TITLE
kyproslaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10550]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kyproslaiset

**Ehdotettu termi ruotsiksi**

cypriot

**Ehdotettu termi englanniksi**

Cypriot

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4863378

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [kyproslaiset](http://finto.fi/yse/fi/page/Y510550)

**Comment by mariaforsen** [comment]
Sv. cyprioter
https://svenska.se/tre/?sok=cypriot&pz=1
