### ISSUE TITLE
maakuntapäivät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10559]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maakuntapäivät](http://www.yso.fi/onto/yso/p22265)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaatisiko tämä tarkenteen tai määritelmän? Nyt vaikuttaisi siltä, että ruotsinkielinen ja englanninkielinen termi viittaavat eri asioihin: Provincial Parliament & landskapsdagar, ja suomenkieliselläkin termillä taitaa useampi merkitys. 

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/maakuntap%C3%A4iv%C3%A4t?searchMode=all

https://yle.fi/aihe/t/18-337474

MOT:
maakuntapäivät

1. Ahvenanmaan
lagting
Suomessa 
vanhahtava landsting

2. historia
landskapsting

3. juhla
landskapsdag

--

EKS: maakuntapäivät
Korvaa termin:	Ahvenanmaan maakuntapäivät
Asiasana ruotsiksi:	lagtinget
Asiasana englanniksi:	Åland Parliament

KANTO:
Suomi. Ålands lagting http://urn.fi/URN:NBN:fi:au:finaf:000036697

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Määritelmä tosiaan tarvitaan jotta saataisiin oikeat vastineet. Ks. myös https://www.sanakirja.fi/custom/en-sv-fi/maakuntap%C3%A4iv%C3%A4t

**Comment by mirmaid** [comment]
Käytetty Melindassa 16 kertaa. Jos kaikkiin Ahvenanmaata käsitteleviin riittää Kanton yhteisö, ja muutamaan sopii lisäksi _maapäivät_, jää kourallinen, jotka voisi katsoa vielä ongelmakokouksessa.

**Comment by mirmaid** [comment]
https://maakuntapaiva.fi/maakuntapaiva/
https://epliitto.fi/etela-pohjanmaan-liitto/paatoksenteko/maakuntapaivat/

**Comment by mirmaid** [comment]
7 viitettä, hyvin erilaisia tapauksia. Ehkä näissä riittää 653?

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _maakuntapäivät_.
