### ISSUE TITLE
canariet [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10553]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

canariet [SLM]

**Ehdotettu termi ruotsiksi**

canarier

**Ehdotettu termi englanniksi**

canaries (music)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

 [tanssimusiikki](http://www.yso.fi/onto/yso/p181)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 canariot

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/009583375 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [canariet [SLM]](http://finto.fi/yse/fi/page/Y510553)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Sv. canarier HT canarior  /ne, mdo

**Comment by mirmaid** [comment]
Hyväksytty /SLM.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
