### ISSUE TITLE
lasiainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10554]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lasiainen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/330518

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lasiainen](http://finto.fi/yse/fi/page/Y510554)

**Comment by ilona-x** [comment]
FinMeSH: 
lasiainen http://www.yso.fi/onto/mesh/D014822

LCSH:
Vitreous body http://id.loc.gov/authorities/subjects/sh85144027

**Comment by mariaforsen** [comment]
Sv. glaskropp 
https://svenska.se/tre/?sok=glaskropp&pz=1
