### ISSUE TITLE
käyttömuistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10563]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[käyttömuistit](http://www.yso.fi/onto/yso/p15250)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mikä on suhde keskusmuistiin (pitäisikö olla ainakin RT)? Ja onko molempien eng. oikeat? Entä OT RAM-muistit?

**Perustelut ehdotukselle**

Ks. esim. TEPA: https://termipankki.fi/tepa/fi/haku/keskusmuisti 
Ja Wikipedia: https://fi.wikipedia.org/wiki/Keskusmuisti "Keskusmuisti (engl. main memory) eli käyttömuisti on tietokoneen muistia, jonne suoritettavat ohjelmat ladataan näiden suorituksen ajaksi."

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
[käyttömuisti ](https://fi.wiktionary.org/wiki/k%C3%A4ytt%C3%B6muisti) (Wiktionary)

1. (tietotekniikka) tietokoneen luettavissa ja kirjoitettavissa oleva keskusmuisti, RAM-muisti

1. ihmisen lyhytaikaisia muistettavia asioita tallentava muisti, työmuisti


**käyttömuisti (tietotekniikka)**  - olisin sanonut tähän RAM.... voisio olla KÄ keskusmuisti ??
**käyttömuisti (psykologia)** -  KÄ työmuisti - working memory

**Comment by ilona-x** [comment]
molemmat termit otettu sanastoon v. 1986

Melinda:
käyttömuistit x 22
keskusmuistit x 36
molemmat x 3

**Comment by ilona-x** [comment]
Tässä taitaa olla kyse siitä, että tietokoneen muisteja voidaan jaotella eri tavoin. Wikipediasta löytyi tällaisia jaotteluja:

"Tietokoneen muistijärjestelmä toteutetaan tavallisesti käyttämällä useita erilaisia komponentteja muistin eri osien käyttötarpeiden mukaisesti. Muistit voidaan luokitella usean eri kriteerin perusteella eri tyyppeihin:

- välimuisti tai keskusmuisti käyttötarkoituksen mukaan
- hajasaanti-, suorasaanti ja sarjasaantimuisteihin muistin hakutavan perusteella
- lukumuisteihin (ROM) ja luku-/kirjoitusmuisteihin (RAM) sen mukaan voidaanko muistiin kirjoittaa vai ei
- haihtuviin ja haihtumattomiin muisteihin tiedon keston mukaan (volatile, non-volatile)
- tallennusvälineen (media) perusteella levy-, nauha- tai puolijohdemuisteihin, ks. massamuisti  "

Lähde: https://fi.wikipedia.org/wiki/Muisti_(tietokone)#Muistin_k%C3%A4ytt%C3%B6-_ja_toteutustavat

**Comment by ilona-x** [comment]
"Keskusmuisti on työmuisti, johon latautuvat käyttöjärjestelmän lisäksi suoritettavat sovellukset sekä näiden tarvitsemat tiedot. Keskusmuisti on tyypiltään [hajasaantimuistia](https://fi.wikipedia.org/wiki/Hajasaantimuisti) (RAM, Random Access Memory[[2]](https://fi.wikipedia.org/wiki/Keskusmuisti#cite_note-kotus-2))"
Lähde: https://fi.wikipedia.org/wiki/Keskusmuisti

**Comment by ilona-x** [comment]
Eli tämän pohjalta olisin valmis laittamaan käyttömuistit & keskusmuistit termeille RT-suhteen

**Comment by ilona-x** [comment]
Ja näköjään random access memory antaa suomeksi monta eri käännöstä:
https://termipankki.fi/tepa/fi/haku/random%20access%20memory
hajasaantimuisti
suorasaantimuisti
poimintamuisti
käyttömuisti
keskusmuisti
työmuisti
hakumuisti
😵

**Comment by ilona-x** [comment]
Ja vielä Wikipediasta https://fi.wikipedia.org/wiki/Hajasaantimuisti:
"RAM-muistin käyttökohteita ovat muun muassa:
    [Välimuisti](https://fi.wikipedia.org/wiki/V%C3%A4limuisti)
    [Keskusmuisti](https://fi.wikipedia.org/wiki/Keskusmuisti)"

**Comment by miguelvaara** [comment]
Käyttömuisti = keskusmuisti = työmuisti ovat minusta synonyymejä keskenään. Nämä kaikki taas ovat tyypiltään hajasaantimuistia eli RAM:ia (Random Access Memory)


Käyttömuisti/keskusmuisti/työmuisti eivät siis ole ihan sama asia kuin hajasaantimuisti, vaikka hajasaantimuistin englanninkielistä akronyymiä RAM käytetäänkin hämäävästi puhekielessä kuin se olisi käyttömuistin synonyymi (perua PC:iden teknisemmiltä alkuajoilta).

Jos halutaan ilmaista tarkasti, niin tekisin itse näin:
hajasaantimuistit (yläkäsite) -> ohjaustermi: RAM
  |_keskusmuisti (alakäsite)-> ohjaustermit: käyttömuisti, työmuisti

Valitsisin siis "keskusmuistin" prefLabeliksi käsitteelle, joka on hajasaantimuistien alakäsite. Keskusmuisti-termi sen takia, että se on ehkä yleiskäyttöisin.

Käytännössä hajasaantityyppisessä muistissa olevat asiat eivät ole järjestettyjä ja muistin rakennustavasta riippuen se vaihtelee, miten muistista poistetaan asioita. Tämä toteutetaan eri tavoin ja esimerkiksi tietokoneen ostajan näkökulmasta tällaisia ei paljoa tarvitse miettiä, vaan myyjältä lähinnä kysytään, "paljonko on keskusmuistia/työmuistia/käyttömuistia/RAM:ia?". 

Haetaanko tässä enemmän ihmisläheistä lähestymistä vai teknisesti tarkempaa kuvausta?

**Comment by mirmaid** [comment]
Sanastossa ei nyt ole _hajasaantimuistit_-käsitettä, eikä sitä ole käytetty myöskään asiasanana Melindassa kertaakaan. 

Mutta ilmeisesti voidaan yhdistää käyttömuistit, työmuistit (tietotekniikka) KÄ keskusmuistit? RAM-muistit ei kuitenkaan siis sovi ohjaustermiksi (tai korkeintaan tarkenteella varustettuna, ja sen kai pitäisi ohjata sekä keskus- että välimuisteihin).

**Comment by mirmaid** [comment]
Ehdotus
käyttömuistit KÄ keskusmuistit (lisäksi KT työmuistit (tietotekniikka))

**Comment by YSO-kokous** [comment]
**Päätös**

Yhdistetään käyttömuistit KÄ keskusmuistit ja lisätään ohjaustermi työmuistit (tietotekniikka).

**Comment by mariaforsen** [comment]
Sv. arbetsminnen, centralminnen > primärminnen HT centralminnen, arbetsminnen (informationsteknik), internminnen (primärminnen)
