### ISSUE TITLE
Pilvimetsät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10567]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Pilvimetsät

**Ehdotettu termi ruotsiksi**

Molnskogar

**Ehdotettu termi englanniksi**

Cloud forests

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Asiasana olisi tarpeen kuvaillessa nimenomaan pilvimetsiin keskittyvää aineistoa erotuksena sademetsistä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sademetsät](http://www.yso.fi/onto/yso/p3487)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533), [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh94003224), [Wikipedia](https://fi.wikipedia.org/wiki/Pilvimets%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The Andean cloud forest (ISBN 978-3-030-57343-0, Melinda-ID 018232442)

**Ehdottajan organisaatio**

Itä-Suomen yliopisto
**Termiehdotus Fintossa:** [Pilvimetsät](http://finto.fi/yse/fi/page/Y510567)

**Comment by mariaforsen** [comment]
Sv. molnskog HT dimskog
