### ISSUE TITLE
itsensä johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10564]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[itsensä johtaminen](http://www.yso.fi/onto/yso/p27940)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

itsensä hyväksyminen 

**Perustelut ehdotukselle**

Kuvaa eri ilmiötä kuin esim. identiteetti, itsensä johtaminen, itsensä toteuttaminen.
Termiä tarvittu aina välillä.

**Ehdottajan organisaatio**

Kirjastopalvelu/OH

**Comment by mirmaid** [comment]
Eli tässä ilmeisesti ehdotettu uutena käsitettä _itsensä hyväksyminen_.

**Comment by mirmaid** [comment]
Sanastossa on _hyväksyminen (psykologia)_. Sitä on varmaan käytetty myös näissä, vaikka on toki laajempi.

_Itsensä hyväksyminen_ on KAUNOssa.

**Comment by mariaforsen** [comment]
Sv. självacceptans (kaunossa självuppskattning) https://www.psykologiguiden.se/psykologilexikon/?Lookup=sj%C3%A4lvuppskattning
https://id.kb.se/find?q=Self-acceptance

**Comment by ilona-x** [comment]
LCSH:
Self-acceptance
        http://id.loc.gov/authorities/subjects/sh85119710

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _itsensä hyväksyminen_. Ohjaustermiksi _itsemyötätunto_.
