### ISSUE TITLE
elinkaarimallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10565]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[elinkaarimallit](http://www.yso.fi/onto/yso/p18563)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettavaksi/jaettavaksi?

**Perustelut ehdotukselle**

Näyttää siltä ettei ole aina käytetty tässä merkityksessä: https://www.kielitoimistonsanakirja.fi/#/elinkaarimalli?searchMode=all

Oikeammat sv. ja eng. termit olisivat mahdollisesti tämänsuuntaisia: https://en.wikipedia.org/wiki/Public%E2%80%93private_partnership mutta vain jos tarkoitus on viitata Kielitoimiston sanakirjan merkitykseen. Ruotsiksi livscykelmodell käytetään myös ihan muissa merkityksissä kuin "julkisen ja yksityisen yhteistyön" merkityksessä. 

Melindassakin aika paljon epäselviä tapauksia, esim. 
Kestävän kehityksen mittaaminen ja elinkaariarviointi / Katri Achrén 
Sisäilmaongelmien ennaltaehkäisy elinkaarimallia käytettäessä ja energiatehokkuutta tavoiteltaessa : loppuraportti / Rauno Holopainen [ja 12 muuta] 
Environmental Life Cycle Assessment: Measuring the Environmental Performance of Products / Rita Schenck and Philip White, editors 
Elinkaarimalli auttaa henkilötietojen käsittelyssä : jotta henkilötietoja käsitellään asianmukaisesti, tietosuojalainsäädäntö tulee ottaa huomioon jo ennen käsittelyn aloittamista sekä myös sitten, kun perustetta tietojen käsittelemiselle ei enää ole 
Palvelun elinkaarimallien tarkastelu eläkevakuutussopimuksen ydinprosessien avulla / Anssi Nieminen.

Näissä ei kai ole kyseessä "toimintatapa jossa yksityinen yritys rahoittaa ja toteuttaa julkisen sektorin projektin ja ylläpitää sitä sovitun ajan."

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Elinkaarimalli "Tämä artikkeli kertoo julkisten hankintojen toteuttamisesta. Muun muassa politiikkaan sekä sosiaali- ja terveystyöhön liittyy käsite [elämänkaarimalli](https://fi.wikipedia.org/wiki/El%C3%A4m%C3%A4nkaari)."

Onko siis tämä käsite sekoitettu myös "elämänkaarimalli"-merkitykseen? Jos tässä on kaksi eri merkitystä, tarvitaan varmaan myös toista termiä (myös käännöksen takia). 

https://www.kotus.fi/nyt/kolumnit_artikkelit_ja_esitelmat/kieli-ikkuna_%281996_2010%29/elinkaarimalli

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4fd620ffd0b7071b0b099a0e3aa1514b&list_id=1&keyword=elinkaarimalli&word=elinkaarimalli

**Comment by mirmaid** [comment]
Ehkä tuossa viimeisessä viitteessä on kyse elämänkaarimallista (en kyllä tässä vaiheessa lähtisi ottamaan sitä sanastoon). Muissa ehkä elinkaariarvioinnista?

Tähän voisi lisätä tarkenteen, esim. (hankintamallit) tai (julkiset hankinnat)?

**Comment by ilona-x** [comment]
YSO:n ohjaustermiin PPP voisi lisätä perään -mallit, kun PPP voi tarkoittaa muutakin: https://termipankki.fi/tepa/fi/haku/ppp

---------

LIIKO:ssa näin, mutta LIIKO:n ratkaisu ei taida kuitenkaan toimia YSO:ssa.

Käytettävä termi
[**PPP-urakat**  ](http://www.yso.fi/onto/koko/p81743)
Ohjaustermit
    elinkaarimallit
    elinkaariurakat
    Public Private Partnership -mallit

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään sulkutarkenne _elinkaarimallit (hankintamallit)_, PPP-ohjaustermiin lisätään _-mallit_.

**Comment by mariaforsen** [comment]
Sv. livscykelmodeller > livscykelmodeller (upphandlingsmodeller) HT offentlig-privat samverkan, PPP-modeller, OPS-lösningar (inte vilken som helst offentlig-privat samverkan, se Kielitoimiston sk. och de olika definitionerna, jfr även eng.)
