### ISSUE TITLE
pääkomponenttianalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10569]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pääkomponenttianalyysi

**Ehdotettu termi ruotsiksi**

principalkomponentanalys

**Ehdotettu termi englanniksi**

principal components analysis

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melinda x 32

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85106729), [Wikipedia](https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4komponenttianalyysi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/urn:isbn:9789526230443

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [pääkomponenttianalyysi](http://finto.fi/yse/fi/page/Y510569)

**Comment by mirmaid** [comment]
Mikähän on tämän yläkäsite...😓

**Comment by ilona-x** [comment]
yläkäsite saattaisi olla [monimuuttujamenetelmät](https://finto.fi/yso/fi/page/p2131) ks. https://www.mv.helsinki.fi/home/kvehkala/mmm/moniste.pdf

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. principalkomponentanalys HT principalkomponentsanalys
