### ISSUE TITLE
majakkalaivat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10566]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

majakkalaivat

**Ehdotettu termi ruotsiksi**

fyrfartyg

**Ehdotettu termi englanniksi**

lightships

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda:
majakkalaivat x 25
majakka-alukset x 1

**Ehdotettu yläkäsite YSOssa (LT)**

 [laivat](http://www.yso.fi/onto/yso/p4911)

**Ehdotetut temaattiset ryhmät**

 [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

 majakka-alukset, lightvessels, fyrskepp

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [majakat](http://www.yso.fi/onto/yso/p523)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85076908), [Wikipedia](https://fi.wikipedia.org/wiki/Majakkalaiva), [MAO: majakkalaivat](http://www.yso.fi/onto/mao/p4355), [LIIKO: majakka-alukset](http://www.yso.fi/onto/mero/m8583)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Majakkalaiva Kemi : historiaselvitys 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [majakkalaivat](http://finto.fi/yse/fi/page/Y510566)

**Comment by mariaforsen** [comment]
Sv. fyrskepp HT fyrfartyg
https://svenska.se/tre/?sok=fyrskepp&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
