### ISSUE TITLE
vertaileva politiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10560]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vertaileva politiikka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

comparative government

**Tarkoitusta täsmentävä selite**

https://wblog.wiki/fi/Comparative_politics

**Perustelut ehdotukselle**

Tarvittu sisällönkuvailussa, termi puuttuu YSOsta. Melindassa käytetty eks-termiä "vertaileva politiikantutkimus"

**Ehdotettu yläkäsite YSOssa (LT)**

 [politiikka](http://www.yso.fi/onto/yso/p454), [politiikantutkimus](http://www.yso.fi/onto/yso/p8773)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

 vertaileva politiikantutkimus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85029298)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018225288

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [vertaileva politiikka](http://finto.fi/yse/fi/page/Y510560)

**Comment by mariaforsen** [comment]
Sv. jämförande politik HT komparativ politik, jämförande statskunskap, jämförande statsvetenskap, komparativ politologi 
https://id.kb.se/find?q=j%C3%A4mf%C3%B6rande%20politik
https://www.eduskunta.fi/kirjasto/EKS/ 
https://sv.wikipedia.org/wiki/Komparativ_politik

**Comment by mirmaid** [comment]
Eikö EKS-termi olisi parempi?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _vertaileva politiikan tutkimus_.

**Comment by mariaforsen** [comment]
SAOssa linkattu Comparative government • lcsh, mutta EKS comparative political research, comparative political studies ?
