### ISSUE TITLE
härmistyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10570]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[härmistyminen](http://www.yso.fi/onto/yso/p14925)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

1. Siirretään käsite yhtä tasoa ylemmäs hierarkiassa, jolloin yläkäsitteeksi tulee "aineen olomuodon muutokset"
2. Poistetaan tämän käsitteen ohjaustermit "sublimaatio (fysiikka)" ja "sublimoituminen (fysiikka)" ja vastaavat muunkieliset termit (mutta jätetään "deposition")
3. Luodaan uusi käsite "sublimoituminen" tasolle "aineen olomuodon muutokset".

**Perustelut ehdotukselle**

Taustaksi: https://fi.wikipedia.org/wiki/Olomuoto#Aineen_olomuodon_muutokset

1. Härmistyminen (kaasu -> kiinteä) ei ole höyrystymisen (neste -> kaasu) erikoistapaus, vaan erillinen aineen muutosten ilmiö
2. & 3. Sublimoituminen (kiinteä -> kaasu) on myös yksi oma aineen muutosten ilmiönsä

PS Näitähän voi periaatteessa olla jo muutettukin ajantasaisessa tuotanto-YSOssa, nyt heinäkuussa ongelmisen vuoksi on vanhempi(?) kehitysversio käytössä.

**Ehdottajan organisaatio**

KK

**Comment by mariaforsen** [comment]
Ruotsinkielinen termi pitää tosiaan tutkia/muuttaa (> desublimering tai deposition (fasomvandling))
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_3f88950319f64987a479e092d3653814&list_id=1&keyword=h%C3%A4rmistyminen&word=h%C3%A4rmistyminen
https://www.rikstermbanken.se/termposter/1958/desublimering

https://sv.wikipedia.org/wiki/Deposition_(fysik)

https://termipankki.fi/tepa/fi/haku/h%C3%A4rmistyminen (Eli jostain syystä ei täsmää Tepassa..)

Onko määritelmä siis: "kaasumaisen aineen muuttuminen nesteytymättä suoraan kiinteäksi aineeksi."? https://www.kielitoimistonsanakirja.fi/#/h%C3%A4rmisty%C3%A4?searchMode=all Sen mukaan voidaan laittaa myös ruotsiksi.

Ja tärkeää onkin sitten myös luoda uusi käsite (sublimoituminen sv. sublimering (fasomvandling)) tämän lisäksi.

**Comment by mariaforsen** [comment]
Sv. -sublimation (förångning) > desublimering HT deposition (fasomvandling)
-sublimering (fasomvandling)
