### ISSUE TITLE
skoolaaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10573]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

skoolaaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Näyttäisi puuttuvan ja on kuitenkin aika keskeinen osa ravintolaetikettiä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kuvaan, jossa skoolataan

**Ehdottajan organisaatio**

Helsingin kaupunginmuseo
**Termiehdotus Fintossa:** [skoolaaminen](http://finto.fi/yse/fi/page/Y510573)

**Comment by jtuohini** [comment]
Lisäksi KT-muodoksi ainakin _lasin kilistäminen_, _maljan kohottaminen_, _maljan nostaminen_, _maljat (skoolaaminen)_, _maljojen kohottaminen_ ja _maljojen nostaminen_.

**Comment by mariaforsen** [comment]
Sv. skålande HT skål (gest)

https://www.sprakinstitutet.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/1993/mera_om_batting_och_skalning

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään termi _skoolaus_.

**Comment by jarmosaarikko** [comment]
Englanniksi "toasting" 
- https://www.collinsdictionary.com/dictionary/english/toasting 
- https://www.merriam-webster.com/dictionary/toasting
- http://www.wikidata.org/entity/Q154168
- Wikipediassa  "toast (honour)  https://en.wikipedia.org/wiki/Toast_(honor) 
eri kuin
- http://www.wikidata.org/entity/Q1369991 toasting --  jamaikalaista musiikkia
