### ISSUE TITLE
tiekartat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10579]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tiekartat](http://www.yso.fi/onto/yso/p10668)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Oikestaan ehdottaisin täsmennystä SLM:n vastaavalle käsitteelle http://urn.fi/URN:NBN:fi:au:slm:s1298, mutta siinä ei ollut muutoslinkkiä. Eli täsmennys termille, jotta erotellaan varsinaiset kartat ja suunnitelmatyyppiset tiekartat

**Perustelut ehdotukselle**

Termiä tiekartta käytetään myös suunnitelmista tms.

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
tiekartat (kartat)?

**Comment by mariaforsen** [comment]
Sv. on ollut vägkarta, eli vain teihin liittyvä kartta. Suunnitelmamerkityksessä sv. olisi jokin muu, ehkä färdplaner, ks. https://termipankki.fi/tepa/fi/haku/tiekartta

**Comment by mariaforsen** [comment]
Käytetty 192 kertaa Melindassa SLM-terminä ja varsinaisessa karttamerkityksessä, lisätäänko varmuuden vuoksi silti tarkenne, vai riittääkö huomautus? YSO-terminä paljon enemmän käytetty, ja jonkin verran virhekäyttöä näytti olevan.. 
https://www.kielitoimistonsanakirja.fi/#/tiekartta?searchMode=all

**Comment by AuHo22** [comment]
Entäpä ohjauksen avulla? 
tiekartat (suunnitelmat) KÄ suunnitelmat
tiekartat (kartat) KÄ tiekartat

https://www.kielikello.fi/-/pysytko-kartalla-

**Comment by mirmaid** [comment]
tiekartat (suunnitelmat) KÄ suunnitelmat
