### ISSUE TITLE
jukagiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10577]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jukagiirit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSO:ssa on käsite jukagiirin kieli, mutta ei jukagiirit. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [kansa (kansanihmiset)](http://www.yso.fi/onto/yso/p3992)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kuvailen kirjan, jonka aiheena on jukagiirien etnohistoria (Melindan id 018199735)

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [jukagiirit](http://finto.fi/yse/fi/page/Y510577)

**Comment by mariaforsen** [comment]
Sv. jukagirer
