### ISSUE TITLE
joustava tuotanto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10576]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[joustava tuotanto](http://www.yso.fi/onto/yso/p4452)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi myös FMS-järjestelmä ja englanniksi FMS (Production engineering)?

**Perustelut ehdotukselle**

http://id.loc.gov/authorities/subjects/sh85049095

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Pitäisikö olla FMS-järjestelmät tai pelkkä FMS?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään molemmat ohjaustermit.
