### ISSUE TITLE
pH

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10571]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pH](http://www.yso.fi/onto/yso/p4555)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Siirretään käsite "happamuus"- ja "emäksisyys" käsitteiden alakäsitteeksi. (Voiko olla useampi kuin yksi yläkäsite? Jos ei ja pitää valita toinen, ehkä "happamuus" on parempi yläkäsitteeksi.)

**Perustelut ehdotukselle**

pH ei ole suoraan kemiallinen ominaisuus, vaan enemmänkin asteikko, jolla aineen happamuus (tai emäksisyys) voidaan ilmoittaa.

**Ehdottajan organisaatio**

KK

**Comment by mirmaid** [comment]
pH ei ole happamuuden alakäsite, nykyinen ratkaisu on kuitenkin ontologian kannalta oikeampi.

**Comment by mirmaid** [comment]
Ontologian rakenteessa esitetty ratkaisu olisi vaikea, pH on "happamuustaso" tai "-arvo", ei varsinaisesti "tietynlainen happamuus".
