### ISSUE TITLE
ennakkoäänestys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10583]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ennakkoäänestys](http://www.yso.fi/onto/yso/p21427)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeihin lisäksi kirjeäänestys/kirjeäänestäminen.

**Perustelut ehdotukselle**

Kirjeäänestys on äänestystapa (2019 alkaen) ulkomailla pysyvästi asuville äänioikeutetuille ja muille vaalien ajan ulkomailla oleskeleville äänioikeutetuille.

**Ehdottajan organisaatio**

Tampereen yliopisto

**Comment by mariaforsen** [comment]
Sv. HT brevröstning

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi.
