### ISSUE TITLE
panseksuaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10584]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

panseksuaalit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

pansexuals

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailen kirjaa biseksuaalisuudesta ja panseksuaalisuudesta ja YSO:sta löytyvät asiasanat biseksuaalisuus, panseksuaalisuus sekä biseksuaalit mutta ei sanaa panseksuaalit. Tämä tuntuu hassun epäsymmetriseltä ; jos on asiasana biseksuaalit niin pitäisi olla yhtälailla panseksuaalit. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [väestöryhmään liittyvä rooli](http://www.yso.fi/onto/yso/p487)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [panseksuaalisuus](http://www.yso.fi/onto/yso/p38180), [biseksuaalit](http://www.yso.fi/onto/yso/p29723)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Jenny Kangasvuo: Bi- ja panseksuaalisuus.

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [panseksuaalit](http://finto.fi/yse/fi/page/Y510584)

**Comment by mariaforsen** [comment]
Sv. pansexuella
https://svenska.se/tre/?sok=pansexuell&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
