### ISSUE TITLE
Särkänniemi (Tampere)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10581]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Särkänniemi (Tampere)

**Ehdotettu termi ruotsiksi**

Särkänniemi (Tammerfors)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Särkänniemi on myös kaupunginosa.

**Perustelut ehdotukselle**

Tarvitaan YSO-paikat-sanastossa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/S%C3%A4rk%C3%A4nniemi_(kaupunginosa))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tuomo Koivisto: Asunto-osakeyhtiö Särkänniemen Tammi : osa Onkiniemeä. 018264352/id

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Särkänniemi (Tampere)](http://finto.fi/yse/fi/page/Y510581)

**Comment by mirmaid** [comment]
Paikkatietoalustalta löytyy niemi ja huvipuisto. 
https://webpages.tuni.fi/koskivoimaa/kaupunki/1918-40/kosat.html
https://fi.wikipedia.org/wiki/S%C3%A4rk%C3%A4nniemi_(kaupunginosa)
https://kartta.com/kaupunginosat/tampereen-kaupunginosat/sarkanniemi/

**Comment by ilona-x** [comment]
Kapunginosan virallinen nimi näyttää olevan tosiaan Särkänniemi, vaikka sitä ei paikkatietoalustalta löydykään. Käytännössä kuitenkin varmaan kaikki Särkänniemen kaupunginosan asukkaat asuvat Onkiniemen asuinalueella, mutta myöskään sitä ei näytä löytyvän paikkatietoalustalta (löytyy vain niemi).

**Comment by mirmaid** [comment]
Särkänniemi (Tampere : kaupunginosa), ei linkkiä Paikkatietoalustalle.
