### ISSUE TITLE
Kiinan provinssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10589]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kiinan provinssit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://en.wikipedia.org/wiki/Administrative_divisions_of_China#Provincial_level_(1st)

**Perustelut ehdotukselle**

Kiinan eri provinssit olisi hyvä saada yso-paikkoihin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Kiina](http://www.yso.fi/onto/yso/p104984)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Bai ge fuhao kan Jiangsu, isbn 9787214118585

**Ehdottajan organisaatio**

Espoon kaupunginkirjasto
**Termiehdotus Fintossa:** [Kiinan provinssit](http://finto.fi/yse/fi/page/Y510589)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kiinan_alueellinen_hallinto

**Comment by ilona-x** [comment]
Eli ilmeisesti nuo suomenkielisessä Wikipediassa listatut maakunnat = provinssit?

![kuva](https://user-images.githubusercontent.com/21304210/186654493-b39a2bd7-747c-4e75-a25b-1e5879373c88.png)
Lähde: https://fi.wikipedia.org/wiki/Kiinan_alueellinen_hallinto#/media/Tiedosto:Kiinan_provinssit.png

**Comment by mirmaid** [comment]
Lisätään kartan mukaan (& eksonyymit).
