### ISSUE TITLE
sähkö- ja automaatioala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10588]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sähkö- ja automaatioala

**Ehdotettu termi ruotsiksi**

el- och automationsbranschen

**Ehdotettu termi englanniksi**

electrical engineering and automation technology

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

sähköala löytyy erikseen, mutta ei automaatioalaa eikä tätä yhdistelmää, yksittäin automaatioalaa ei taideta juurikaan käyttää

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-206-736-4 https://karvi.fi/wp-content/uploads/2022/06/KARVI_1522.pdf

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [sähkö- ja automaatioala](http://finto.fi/yse/fi/page/Y510588)

**Comment by mariaforsen** [comment]
Ruotsiksi käytetty lähinnä tämän yhteydessä [Grundexamen inom el- och automationsbranschen](https://eperusteet.opintopolku.fi/#/sv/esitys/3328286/reformi/rakenne)

**Comment by mirmaid** [comment]
Vähän hankala, kun varmaan ei kuitenkaan haluta poistaa _sähköalaa_.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _automaatioala_, lisätään myös _automaatiotekniikka_.

**Comment by mariaforsen** [comment]
Sv. automationsbranschen HT automatiseringsbranschen
https://eperusteet.opintopolku.fi/#/sv/ammatillinen/3328286/rakenne
