### ISSUE TITLE
oikeushenkilötunnus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10587]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

oikeushenkilötunnus

**Ehdotettu termi ruotsiksi**

LEI-nummer

**Ehdotettu termi englanniksi**

legal entity identifier

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Laajalti käytössä oleva virallinen lakisääteinen tunniste
https://www.gleif.org/en/lei-solutions/regulatory-use-of-the-lei

**Ehdotettu yläkäsite YSOssa (LT)**

 [pysyvät tunnisteet](http://www.yso.fi/onto/yso/p29018)

**Ehdotetut temaattiset ryhmät**

 [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524), [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

 LEI-tunnus, LEI-koodi, LEI number, LEI code

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [oikeussubjekti](http://www.yso.fi/onto/yso/p19279)

**Vastaava käsite muussa sanastossa**

 [Wikidata LEI-tunnus](http://www.wikidata.org/entity/Q6517388)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Uutiset, hallinto
PRH
https://suomilei.fi/

**Ehdottajan organisaatio**

Finto
**Termiehdotus Fintossa:** [oikeushenkilötunnus](http://finto.fi/yse/fi/page/Y510587)

**Comment by fantsby-m** [comment]
https://www.prh.fi/fi/lei-tunnus.html

**Comment by mirmaid** [comment]
Kerran Melindassa monikossa. Googlella moninkertaisesti muodossa _LEI-tunnus_.

**Comment by jarmosaarikko** [comment]
Ohjeet oikeushenkilötunnuksen (LEI) käytöstä: 
https://www.eiopa.europa.eu/sites/default/files/publications/eiopa_guidelines/eiopa_2014_00120000_fi_tra_0.pdf

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _LEI-tunnus_ päätermiksi, ohjaustermiksi _oikeushenkilötunnus_.

**Comment by ilona-x** [comment]
fi        LEI-tunnus
sv       LEI-nummer 
en      LEI code

määritelmä
maailmanlaajuinen yhteisötunnus, joka on tarkoitettu rahoitusmarkkinoilla toimivien yritysten ja yhteisöjen tunnistamiseen

huomautus
LEI-tunnuksen käytön tarkoituksena on parantaa rahoitusmarkkinoiden läpinäkyvyyttä.

Lähde: Patentti- ja rekisterihallituksen sanasto (TSK 54, 2018)
https://termipankki.fi/tepa/fi/haku/lei-tunnus

**Comment by mariaforsen** [comment]
Sv. LEI-nummer HT LEI-kod
