### ISSUE TITLE
walesilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10590]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

walesilaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kirjailijan kansallisuus

**Ehdotettu yläkäsite YSOssa (LT)**

 [britit](http://www.yso.fi/onto/yso/p11004)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [skotit](http://www.yso.fi/onto/yso/p11003)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4849561

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [walesilaiset](http://finto.fi/yse/fi/page/Y510590)

**Comment by mariaforsen** [comment]
Sv. walesare
https://svenska.se/tre/?sok=walesare&pz=1
