### ISSUE TITLE
auteur-teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10601]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

auteur-teoria

**Ehdotettu termi ruotsiksi**

auteur-teori

**Ehdotettu termi englanniksi**

auteur theory

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Keskeinen käsite, jota näyttää käytetyn jonkin verran auktorisoimattomana asiasanana Melindassa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh96007478), [Wikidata](https://www.wikidata.org/wiki/Q788514)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/007537874, https://melinda.kansalliskirjasto.fi/byid/018269763

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [auteur-teoria](http://finto.fi/yse/fi/page/Y510601)

**Comment by mariaforsen** [comment]
Sv. auteurteori HT auteur-teori

**Comment by mirmaid** [comment]
4 kertaa Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _elokuvateorian_ alakäsitteenä.
