### ISSUE TITLE
adpositiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10615]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

adpositiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/151713

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [adpositiot](http://finto.fi/yse/fi/page/Y510615)

**Comment by mariaforsen** [comment]
Sv. adpositioner
https://termipankki.fi/tepa/fi/haku/adpositio

**Comment by mirmaid** [comment]
Ehdotuksen aineiston lisäksi 6 viitettä Melindassa & muutama ketju.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
