### ISSUE TITLE
porapistiäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10613]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

porapistiäiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/151151

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [porapistiäiset](http://finto.fi/yse/fi/page/Y510613)

**Comment by mariaforsen** [comment]
Eli lat. Rhyssinae?
Sv. raspryggsteklar
https://namnochslaktskap.artfakta.se/taxa/1000031/details

**Comment by mirmaid** [comment]
Nimi on otettu suoraan väitöstiivistelmästä, Laji.fi "pora-ahmaset", https://laji.fi/taxon/MX.309079.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _pora-ahmaset_, ohjaustermiksi _porapistiäiset_. 

(Kommentti: Alkuperäinen päätös puuttuu jostain syystä, rekonstruoitu sihteerin muistiinpanoista)
