### ISSUE TITLE
aasiannorsu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10612]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aasiannorsu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/152776

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [aasiannorsu](http://finto.fi/yse/fi/page/Y510612)

**Comment by mariaforsen** [comment]
Sv.
-asiatisk elefant (Elephas maximus, indisk elefant=Elephas maximus indicus)
-afrikansk elefant /ne

**Comment by LeKorsu** [comment]
Pitäisikö samassa yhteydessä ottaa mukaan myös afrikannorsu(t)? Monikossa? koska niitä on kahta eri lajia (wwf.fi:Afrikassa elää metsänorsuja ja savanninorsuja, jotka luokitellaan kahdeksi eri lajiksi. Metsänorsu luokitellaan äärimmäisen uhanalaiseksi ja savanninorsu erittäin uhanalaiseksi.)

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan eri norsut uusiksi termeiksi.
