### ISSUE TITLE
sukupuolielämä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10617]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuolielämä](http://www.yso.fi/onto/yso/p5897)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

seksielämä

**Perustelut ehdotukselle**

Sukupuolielämä viittaa sukupuoleen ei seksuaalisuuteen. Vanhentunut ja heteronormatiivinen ilmaus ("sukupuoli määrää seksuaalisen kiinnostuksen kohteen"). Sukupuoli on aivan erillinen asia seksuaalisuudesta. Olisi aika päivittää näin pahasti vanhentunut käsite.

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by ilona-x** [comment]
sukupuolielämä-termiä käsitelty viimeksi keväällä:  sukupuolielämä #9817

**Comment by mirmaid** [comment]
Täytyykö tämä taas avata? Mielestäni _sukupuolielämä_ ei sisällä mainittua heteronormatiivista oletusta.

**Comment by YSO-kokous** [comment]
**Päätös**

Jää termiehdotukseksi.
