### ISSUE TITLE
antrasykliinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10614]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

antrasykliinit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/152416

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [antrasykliinit](http://finto.fi/yse/fi/page/Y510614)

**Comment by mariaforsen** [comment]
Sv. antracykliner /mesh

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D018943

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
