### ISSUE TITLE
pohjukaissuolen kasvaimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10619]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pohjukaissuolen kasvaimet

**Ehdotettu termi ruotsiksi**

tumörer i tolvfingertarmen

**Ehdotettu termi englanniksi**

duodenal neoplasms 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [suolistosyövät](http://www.yso.fi/onto/yso/p25845)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 duodenal cancer, pohjukaissuolen syöpä, pohjukaissuolisyöpä

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D004379), [wikipedia](https://en.wikipedia.org/wiki/Duodenal_cancer)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Carbonic anhydrases II, IX, and XII in esophageal and duodenal diseases http://urn.fi/urn:isbn:9789526231211

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [pohjukaissuolen kasvaimet](http://finto.fi/yse/fi/page/Y510619)

**Comment by mirmaid** [comment]
Googlella eniten muodossa _pohjukaissuolen syöpä_.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _pohjukaissuolen syöpä_, KT _pohjukaissuolen kasvaimet_.

**Comment by mariaforsen** [comment]
Sv. cancer i tolvfingertarmen HT duodenalcancer, duodenal cancer, tumörer i tolvfingertarmen, duodenaltumörer
https://mesh.kib.ki.se/term/D004379/duodenal-neoplasms
