### ISSUE TITLE
kartografit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10611]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kartografit](http://www.yso.fi/onto/yso/p19615)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "kartoittajat" (suomi) ja "mapmakers" (englanti)

**Perustelut ehdotukselle**

Jälkimmäinen LCSH:ssa KT-muotona asiasanalle "Cartographers"

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
YSOssa on myös kartoittajat erikseen https://finto.fi/yso/fi/page/p4126

**Comment by ilona-x** [comment]
kartanpiirtäjät #10610

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään RT-suhteita. Varmistetaan Melindasta, ettei käsitettä _kartoittajat_ ole käytetty virheellisesti.

**Comment by FinMeSHienPaimentaja** [comment]
Tässä vielä alan ihmisen näkemys:


"Kartoittaja voi tarkoittaa ulkona kartoitusta (mittausta) tekevää henkilöä tai maanmittausalan perustutkinnon (ammattitutkinto) suorittanutta henkilöä.


Kartografi on ennen ollut varmaankin kartanlaatija, nyt ehkä historian havinaa ja jotkut hienoja kauniita karttoja tekevät graafikot tykkäävät käyttää sitä.

 
Kartanpiirtäjä on ollut vanha ammattitutkinto, nykyisin sen suorittaneet ovat 50+ ikäisiä. Kaikki koulutetaan nyt kartoittajiksi. Kartanpiirtäjä voi myös tarkoittaa karttaa piirtävää henkilöä tai olla ammattinimike.

 
Nykyään puhumme ennemmin paikkatiedosta ja paikkatiedon käsittelystä ja kartta on yksi ilmentymä paikkatiedolle."
