### ISSUE TITLE
marja-aronia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10616]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

marja-aronia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/152605

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [marja-aronia](http://finto.fi/yse/fi/page/Y510616)

**Comment by mariaforsen** [comment]
Sv. bäraronia? https://namnochslaktskap.artfakta.se/taxa/1005756/details 
lat. Aronia mitschurinii?

**Comment by mirmaid** [comment]
Väitöstiivistelmän mukaan Sorbaronia mitschurinii, vanha nimi Aronia mitchurinii.

**Comment by ilona-x** [comment]
Onkohan tämän yleiskielinen nimikin muuttunut.🤔 Vie toki aikansa ennen kuin uusi nimi vakiintuu. Puutarhamyymälät näyttävät edelleen myyvän marja-aroniaa.

https://laji.fi/taxon/MX.4978975
Tieteellinen nimi
×Sorbaronia mitschurinii
Yleiskieliset nimet
    marjapihlonia (suomi)
    bärsorbaronia (ruotsi) 

"Marja-aronian uusi nimi on [marjapihlonia](https://fi.wikipedia.org/wiki/Marjapihlonia) (×Sorbaronia mitschurinii)[[5]](https://fi.wikipedia.org/wiki/Aroniat#cite_note-5), sillä uusimman taksonomian mukaan se on siirretty aronioista hybridisukuun ×Sorbaronia, johon on risteytetty aronian lisäksi pihlajia."
Lähde: https://fi.wikipedia.org/wiki/Aroniat

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi.

**Comment by mariaforsen** [comment]
Sv. bäraronia HT bärsorbaronia /laji.fi 
https://svenska.yle.fi/a/7-10006897
https://gronbacka.fi/butik/bararonia-aronia-mitchurinii-viking/
