### ISSUE TITLE
suprajuoksevuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1062]
#### Ehdotettu termi suomeksi

suprajuoksevuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[07 Fysiikka](http://www.yso.fi/onto/ysa/ryhma_07)
#### Lähde

Lähde: HS 18.11.2003

**Luontipäivämäärä:** 13.01.2004

**Muokkauspäivämäärä:** 13.1.2004, 16.12.2008

**Voyager-id:** 129000

**Termiehdotus Fintossa:** [suprajuoksevuus](http://finto.fi/yse/fi/page/Y329000)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1063

**Comment by mariaforsen** [comment]
Sv. suprafluiditet ET supravätskor

**Comment by YSO-kokous** [comment]
Hyväksytään suprajuoksevuus ja ohjaustermiksi supranesteet.
