### ISSUE TITLE
pohjukaissuoli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10620]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pohjukaissuoli

**Ehdotettu termi ruotsiksi**

tolvfingertarm

**Ehdotettu termi englanniksi**

duodenum

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melinda x 8

**Ehdotettu yläkäsite YSOssa (LT)**

 [ohutsuoli](http://www.yso.fi/onto/yso/p11193)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikipedia](https://fi.wikipedia.org/wiki/Pohjukaissuoli), [LCSH](http://id.loc.gov/authorities/subjects/sh85039998), [FinMeSH](http://www.yso.fi/onto/mesh/D004386)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Carbonic anhydrases II, IX, and XII in esophageal and duodenal diseases

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [pohjukaissuoli](http://finto.fi/yse/fi/page/Y510620)

**Comment by mariaforsen** [comment]
Sv. tolvfingertarm HT duodenum
