### ISSUE TITLE
supranesteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1063]
#### Ehdotettu termi suomeksi

supranesteet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[07 Fysiikka](http://www.yso.fi/onto/ysa/ryhma_07)
#### Lähde

Lähde: HS 18.11.2003

**Luontipäivämäärä:** 13.01.2004

**Muokkauspäivämäärä:** 21.2.2013, 13.1.2004, 21.02.2013

**Voyager-id:** 129001

**Termiehdotus Fintossa:** [supranesteet](http://finto.fi/yse/fi/page/Y329001)

**Comment by mirmaid** [comment]
Myös _Dynamics and vortex structures in topological superfluid 3He at ultra-low temperatures and under confinement_

**Comment by mariaforsen** [comment]
Sv. supravätskor?

**Comment by ilona-x** [comment]
LCSH: Superfluidity KT Superfluids
http://id.loc.gov/authorities/subjects/sh85130598

Wikipedia-sivut: fi Supraneste - sv Suprafluiditet - en Superfluidity
https://fi.wikipedia.org/wiki/Supraneste

http://www.tsk.fi/tepa/fi/haku/superfluidity
supranesteisyys, suprajuoksevuus
