### ISSUE TITLE
Donetsin allas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10649]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Donetsin allas

**Ehdotettu termi ruotsiksi**

Donetsbäckenet

**Ehdotettu termi englanniksi**

Donbas

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailen teosta, joka käsittelee kyseistä aluetta.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Ukraina](http://www.yso.fi/onto/yso/p107664)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Donbass

**Alakäsitteet (RT)**

 [Donetsk (Ukraina : kaupunki)](http://www.yso.fi/onto/yso/p508551)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.5054455

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Donetsin allas](http://finto.fi/yse/fi/page/Y510649)

**Comment by petraunk** [comment]
Käytetty asisanoituksessa myös ulkomaisessa tietokannassa kyseisen teoksen alkukielisessä versiossa:
https://seattle.bibliocommons.com/v2/record/S30C3798976

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Donbas
https://fi.wikipedia.org/wiki/Donetsin_allas
- näitä ei linkattu?

**Comment by ilona-x** [comment]
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1372&ex=Donetsin+allas

**Comment by mirmaid** [comment]
Donbass KT Donbas, Donetsin allas (linkitys wikidatassa siihen, jossa sv. wikipedia)
