### ISSUE TITLE
lämpökeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10652]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lämpökeskukset](http://www.yso.fi/onto/yso/p10620)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi lämpölaitokset

**Perustelut ehdotukselle**

Lämpölaitos (usein myös lämpökeskus) jne... https://fi.wikipedia.org/wiki/L%C3%A4mp%C3%B6laitos

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
TEPA **lämpölaitos** https://termipankki.fi/tepa/fi/haku/l%C3%A4mp%C3%B6laitos

fi      lämpöenergian tuotantorakennus; lämmön tuotantorakennus; lämpölaitos
sv     byggnad för produktion av värme-energi
en    production building for thermal energy

määritelmä
energiantuotantorakennus, jossa tuotetaan erillistuotantona lämpöä
huomautus

Lähde: Rakennetun ympäristön sanasto (2020)


fi      lämpölaitos; kaukolämpölaitos
sv      värmeverk; fjärrvärmeverk
en      district heating plant

definition
A heating plant producing heat for an urban community without producing electricity.

Lähde: Tieteen termipankki 02.02.2022, Ympäristötieteet:lämpölaitos


TEPA **lämpökeskus** https://termipankki.fi/tepa/fi/haku/l%C3%A4mp%C3%B6keskus

fi      lämpökeskus
sv      värmecentral; värmeverk
en      heat station

määritelmä
energiantuotantolaitos, joka tuottaa yksinomaan lämpöenergiaa; vrt. voimalaitos, lämmitysvoimalaitos
Lähde: Energiasanasto (TSK 16, 1989)

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
