### ISSUE TITLE
aikapaine

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10656]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aikapaine

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

time pressure

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [stressi](http://www.yso.fi/onto/yso/p133)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh93005764), [TSR](http://www.yso.fi/onto/tsr/p7591)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Time pressure and well-being in software engineering http://urn.fi/urn:isbn:9789526231358

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [aikapaine](http://finto.fi/yse/fi/page/Y510656)

**Comment by mariaforsen** [comment]
Sv. tidspress

**Comment by mirmaid** [comment]
Kerran aiemmin Melindassa. Varmaan käytetty _kiire, työhyvinvointi (ym)_?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _aikapaine_ ohjaustermiksi _kiireelle_.
