### ISSUE TITLE
olkanivel

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10653]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

olkanivel

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/332922

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [olkanivel](http://finto.fi/yse/fi/page/Y510653)

**Comment by ilona-x** [comment]
FinMeSH:
olkanivel http://www.yso.fi/onto/mesh/D012785

YSOssa nivelet-käsitteellä ei ole tällä hetkellä yhtään alakäsitteitä vrt. MeSH.

Melinda:
haku olkapäät & nivelet tuottaa 83 viitettä

**Comment by mirmaid** [comment]
Olisihan siellä ainakin muutama muu, mistä varmasti myös säännöllisesti aineistoa.

**Comment by mariaforsen** [comment]
Sv. 
-skulderled
-armbågsled

**Comment by ilona-x** [comment]
Tuli sopivasti vastaan väitöskirja, joka käsittelee kyynärniveltä. Jos näitä otetaan, ehkä tämä olisi sitten vahva ehdokas seuraavaksi, sillä väitöstiedotteen mukaan : "Kyynärnivel on toiseksi yleisin sijoiltaan menevä nivel olkanivelen jälkeen." http://urn.fi/URN:ISBN:978-952-61-3767-4

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään termit _olkanivel_ ja _kyynärnivel_.
