### ISSUE TITLE
vastat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10667]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vastat](http://www.yso.fi/onto/yso/p22770)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaihdetaan LT suhde "elottomat objektit" --> "välineet"

**Perustelut ehdotukselle**

Vasta eli vihta on enemminkin väline kuin pelkkä objekti.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi vastat on bastukvastar ja välineet on redskap, eli ei sovi.

**Comment by jtuohini** [comment]
Onko ruotsin _redskap_ siis paremminkin laite, apuväline yms. ennemmin kuin minkä tahansa lainen väline tai jonkin asian tekemisen mahdollistava esine? Suomeksi väline kun aika väljä, Kielitoimiston mukaan "jssak apuna käytettävä esine, asia tms., apuneuvo, -keino, välikappale" (https://www.kielitoimistonsanakirja.fi/v%C3%A4line). Suomenkielisenä on vaikea nähdä, miksi hammasharjat, pelinappulat ja soittimet käyvät YSO:ssa hierarkkisesti välineiden alle myös ruotsiksi, mutta vastat, jotka kumminkin ovat vihdontavälineitä, eivät.

**Comment by mirmaid** [comment]
Objektien hierarkiaa ei ole toistaiseksi käyty läpi - vastaava muutos olisi perusteltavissa suurelle joukolle muitakin käsitteitä, jos siihen päädytään vastojen osalta.
