### ISSUE TITLE
verkostoteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10662]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

verkostoteoria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://jultika.oulu.fi/Record/isbn978-952-62-2938-6

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Esimerkkiaineiston tiivistelmästä:

"Teoreettinen viitekehys on koostettu latourilaisesta toimijaverkostoteoriasta ja olemassaolon ilmenemismuodosta, sekä edesmenneen David Graeberin antropologisesta talousteoriasta."

Ja sama kohta englanniksi:

"The theoretical framework is formed around Latourian Actor-Network Theory and Modes of Existence, and the anthropological economic theory of the late David Graeber."

Eli onko tässä ehdotettu verkostoteoria sama kuin toimijaverkkoteoria, joka löytyy jo YSOsta [toimijaverkkoteoria](https://finto.fi/yso/fi/page/p19013)? 🤔  
https://fi.wikipedia.org/wiki/Toimijaverkkoteoria

**Comment by mariaforsen** [comment]
Sv. nätverksteori Ruotsiksi nätverksteori voi olla laajempikin merkitykseltään.
https://www.psykologiguiden.se/psykologilexikon/?Lookup=akt%C3%B6r%2Dn%C3%A4tverksteori%2C+ANT

**Comment by mirmaid** [comment]
^^ Varmaankin, _verkostoteoria_ on tekijän antama avainsana. Pitäisikö lisätä KT toimijaverkostoteoria?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi _toimijaverkostoteoria_ käsitteelle _toimijaverkkoteoria_.
