### ISSUE TITLE
kvasikonformikuvaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10666]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kvasikonformikuvaukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/335569

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kvasikonformikuvaukset](http://finto.fi/yse/fi/page/Y510666)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kvasikonformikuvaus
LCSH: http://id.loc.gov/authorities/subjects/sh85109745

Melindassa 6 x monikko, 3 x yksikkö.

**Comment by mariaforsen** [comment]
Sv. kvasikonforma avbildningar
https://www.blf.fi/artikel.php?id=7201

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
