### ISSUE TITLE
diskurssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10663]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[diskurssi](http://www.yso.fi/onto/yso/p17817)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT diskurssit tai päätermin muutos monikkoon

**Perustelut ehdotukselle**

Esiintyy hyvin usein monikossa aineistoissa.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermiksi monikollinen _diskurssit_.
