### ISSUE TITLE
suorituspaineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10668]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suorituspaineet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Nykyään kirjoitetaan paljon suorituspaineista sekä yhteiskunnan että yksilön tasolla, sillä uupumus on lisääntynyt yhteiskunnan suorituskeskeisyyden koventuessa ja nuoret uupuvat yhä nuorempina. Asiaa käsittelevää kirjallisuutta ilmestyy yhä enemmän. Kaipaisin sanaa "suorituspaineet", koska esimerkiksi stressi, uupumus tai psyykkinen kuormitus kuvaavat ilmiöstä vain (yksilöllistä) seurausten puolta. "Suorituspaineet" kuvaisivat sekä yksilöllistä kokemusta että laajempaa yhteiskunnallista ilmiötä ja syytä stressin ja uupumuksen takana. Esimerkiksi nyt kuvailemani kirja käsittelee sitä, miten nuoret "voivat huonommin koventuneiden suorituspaineiden maailmassa". Kyse ei ole siis pelkästään jonkun yksilön suorituspaineista, vaan suorituspaineisesta yhteiskunnasta. 

YSO:ssa ei ole edes laajempaa käsitettä "paineet". Kaunossa on sentään suorituskeskeisyys, joka on parempi kuin ei mitään. Mutta suorituspaineet olisi parempi tässä tapauksessa. 

Artikkeleja suorituspaineista esim: https://www.kaleva.fi/suoritusyhteiskunta-painostaa-identiteettiprojekti/4361121 
https://www.ts.fi/uutiset/4160670 
https://www.fennia.fi/sisaltostudio/suorituspaineet-hallintaan

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 paineet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [TEPA-termipankki](https://termipankki.fi/tepa/fi/haku/suorituspaine), [Wiktionary](https://en.wiktionary.org/wiki/suorituspaine)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Liisa Huhta: Uupuneet nuoret pärjääjät (2022)

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [suorituspaineet](http://finto.fi/yse/fi/page/Y510668)

**Comment by mirmaid** [comment]
YSOssa on _suoriutuminen_, joka juuri ehdolla poistettavaksi: https://github.com/Finto-ehdotus/YSE/issues/10100. Lisäksi on _opintosuoritukset_ (vähän eri tulokulma kyllä) ja _opintomenestys_.

**Comment by mariaforsen** [comment]
Suoriutuminen on ruotsiksi presterande, se ei oikein sovi tähän. Ruotsiksi on myös sellainen termi kuin prestationsångest, ja se ainakin olisi hyvä saada YSOon (ei rajaudu pelkästään opintoihin). Myös SAOssa on prestationsångest https://id.kb.se/term/sao/Prestations%C3%A5ngest Performance anxiety • lcsh 
Toisaalta suorituspaineet voisi olla myös prestationskrav, mikä on hieman eri tulokulma.

**Comment by mirmaid** [comment]
_Performance anxiety_ viittaa usein esiintymispelkoon, vaikka se ei ihan rajaudukaan siihen. Suorituspaineita voi olla vastaavissa tilanteissa, mutta myös ihan yksin puurtaessa voi olla esim. siihen liittyen, saako tehtyä jotain tarpeeksi tai riittävän hyvin.

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
suorituspaine
henkinen paine, joka aiheutuu voimakkaasta halusta t. ulkoisista vaatimuksista suoriutua hyvin jstak vaativaksi koetusta työstä, tehtävästä tms.
Pianistia vaivannut suorituspaine kuului hänen soitostaan.
Tappio kasvatti joukkueen suorituspaineita.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään käsite _suorituspaineet_.

**Comment by jarmosaarikko** [comment]
englanniksi ainakin ohjaustermiksi "test anxiety" - se on eräänlaista "performance anxiety"
- https://www.oxfordlearning.com/what-is-test-anxiety/
- Esiintymiseen liittyvä on "stage fright" - https://en.wikipedia.org/wiki/Stage_fright
- kts. myös "sexual performance anxiety", a type of [sexual dysfunction](https://en.wikipedia.org/wiki/Sexual_dysfunction)

**Comment by mariaforsen** [comment]
Sv. prestationsångest HT prestationskrav
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_d26909ac9ba2b8de261f1d1be5dfa475&list_id=1&keyword=suorituspaine&word=suorituspaine
https://svenska.se/tre/?sok=prestations%C3%A5ngest&pz=1
