### ISSUE TITLE
sierraleonelaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10661]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sierraleonelaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kirjailijan kansallisuus

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/eepos.2876873

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto

**Comment by mariaforsen** [comment]
Sv. sierraleonier
https://svenska.se/tre/?sok=sierraleonier&pz=1
