### ISSUE TITLE
funikulaarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10660]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[funikulaarit](http://www.yso.fi/onto/yso/p27378)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "kiskohissit" ja "rinnehissit" ja tarpeen mukaan vaihdetaan näistä edellinen päätermiksi.

**Perustelut ehdotukselle**

Kielitoimiston sanakirjan mukaan ensisijainen suomenkielinen nimitys on kiskohissi (https://www.kielitoimistonsanakirja.fi/kiskohissi)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Myös "vinohissi" (Google n. 13700, kiskohissi n. 1300). Rinnehissi n. 5700, mutta voi sekoittua hiihtohissiin. Teknisesti funikulaari ilmeisesti olisi vain kahden vastapaino-vaunun muodostama kokonaisuus, mutta kyllä funikulaari meillä on kovin käytetty näistä vinohisseistä.

**Comment by YSO-kokous** [comment]
**Päätös**

Säilytetään _funikulaarit_. Ohjaustermiksi _kiskohissit_.
