### ISSUE TITLE
sanastotyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10669]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sanastotyö](http://www.yso.fi/onto/yso/p7405)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT terminologinen työ 

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/sanastoty%C3%B6

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ruotsinkielinen termi vaatii muutoksia. Ordinsamlingsarbete > terminologiarbete HT terminologiskt arbete
https://termipankki.fi/tepa/fi/haku/sanastoty%C3%B6
https://vnk.fi/sv/termradgivning
https://thl.fi/sv/web/informationshantering-inom-social-och-halsovarden/kodtjansten/informationsarkitekturen/terminologiarbete
http://www.terminfo.fi/sisalto/terminologiarbete-vid-en-svensk-myndighet-204.html
https://svenska.se/tre/?sok=terminologi&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _terminologinen työ_ ohjaustermiksi.
