### ISSUE TITLE
vaarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10677]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vaarat](http://www.yso.fi/onto/yso/p3054)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne?

**Perustelut ehdotukselle**

Käytetty aika paljon väärin Melindassa, eli "vaaratilanteista", riskeistä yms. Täysin virheellisiä tietueita kun ruotsiksi lukee "skogsbevuxna fjäll" tämäntyyppisissä tapauksissa: Kemikaaliturvallisuus työpaikoilla / teksti: Marjo Hämäläinen, Niina Kallio, Pia Taxell. ; Lääkitysturvallisuus esillä Valtakunnallisilla potilasturvallisuuspäivillä ; Extreme fear : the science of your mind in danger / Jeff Wise ; Med egna ord : barn och deras föräldrar om vad som kan vara obehagligt på internet / Olle Findahl, Elza Dunkels och Cecilia von 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Ehdotus: lisätään tarkenne > vaarat (pinnanmuodot)
