### ISSUE TITLE
RFTA

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10674]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[RFTA](http://www.yso.fi/onto/yso/p17270)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT:n tarkennus

**Perustelut ehdotukselle**

https://www.utupub.fi/handle/10024/152415 myös kuumennushoito

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Entä suhde tähän [radiotaajuusablaatio](https://finto.fi/mesh/fi/page/D000078703)

**Comment by mirmaid** [comment]
^ Eikö tuo ole siis sama käsite? Ehkä päätermi voisi olla sama YSOssakin. Ohjaustermiin tarkenne (RFTA) tai (radiotaajuusablaatio)?

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan viimeisen kommentin mukaisesti.
