### ISSUE TITLE
härdar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10670]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[härdar](http://www.yso.fi/onto/yso/p38758)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennys

**Perustelut ehdotukselle**

Ruotsiksi on lisättävä tarkenne (ugnar, pannor, förbränning, eldstäder tms.), mutta täytyy selventää mihin kaikki tulipesiin tämä on tarkoitus viitatata. Melindassa 4. Ks. myös https://fi.wikipedia.org/wiki/Tulipes%C3%A4 

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
tulipesät otettu sanastoon v. 2020 https://github.com/Finto-ehdotus/YSE/issues/7966

[YSO-kokous](https://github.com/YSO-kokous) commented [on 9 Mar 2020](https://github.com/Finto-ehdotus/YSE/issues/7966#issuecomment-596389232)

Hyväksytään käsite sanastoon.
Ei nähty tarvetta erottaa eri tyyppisiä tulipesiä toisistaan.

**Comment by mariaforsen** [comment]
EI valitettavasti ollutkaan ihan niin helppoa ruotsiksi.
https://svenska.se/saol/?sok=h%C3%A4rd&pz=1
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_94223360253d82b16dc1cd11cbee41ac&list_id=1&keyword=tulipes%C3%A4&word=tulipes%C3%A4

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: lieden, kiukaan tms. tila, jossa polttoaine palaa

**Comment by mirmaid** [comment]
Muistelen, että kokouksessa pohdittiin lähinnä, onko tuo höyrykattilan tulipesä varmasti sama asia. Nuo takat, uunit jne. ovat varmasti sama. 

_Takat_ on muuten hiukan ongelmallinen ehkä, koska suomeksi ei oteta kantaa siihen, onko kyseessä avotakka.

**Comment by mariaforsen** [comment]
On ongelma joo.. Olisiko yksi mahdollinen ratkaisu takat=öppna spisar och braskaminer?
Jos tulipesät suomeksikin rajautuisi kodeissa yms. olevien tulisijojen "sydämiin" niin tarkenne voisi ruotsiksi olla eldstäder? Mutta näin ei näytä olevan Melindassa..

**Comment by mirmaid** [comment]
_Kamiinat_ on vielä erikseen sanastossa. Näissä on kyllä varmaan melko hankala sanoa missä edes menee takan ja kamiinan raja. Mutta mikä on varaava takka ruotsiksi? Nunnauunilla on sivut myös ruotsiksi, käyttää sanoja brasugnar ja eldstäder 😣

**Comment by mirmaid** [comment]
_Tulisijat_ on hyvin laaja suomeksi, miten siis ruotsiksi rajautuu?

**Comment by mirmaid** [comment]
Entä ehdotuksen förbränning? Tuli siinä kuitenkin on olennainen...onko noissa saolin merkityksissä 3. ja 4. kyse jostain metallin sulatuksesta? 3. = ahjo?

**Comment by mariaforsen** [comment]
On joo varmasti metallin tms. sulatuksesta kyse. Kyllä, ahjo olisi varmaan oikea vastine sille 3. merkitykselle.

https://www.sanakirja.fi/custom/fi-en-sv/varaava%20takka

Förbränning olisi hyvä, mutta en tiedä miten hyvin kuvailijat osaa erottaa sitä sitten siitä 3. merkityksestä. Ahjot-termin otto erikseen voisi auttaa? https://finto.fi/fi/search?clang=sv&anylang=on&q=ahjot&vocabs=

**Comment by mirmaid** [comment]
Suomeksi myös ahjo on kyllä tulisija, tosin jos aineisto käsittelisi ahjoja, niin ehkä silloin haluttaisiin käyttää tarkempaa termiä. Saolin merkityksistä 4. on sellainen, etten tiedä mikä se on, enkä myöskään siis vastinetta, mutta se ei kuulosta tulipesältä.

**Comment by mirmaid** [comment]
Toinen kysymys on sitten _takat_ ja _kamiinat_ -käsitteiden kohtalo, halutaanko niitä yhdistää.

**Comment by jarmosaarikko** [comment]
takka (sekä avotakka että umpinainen) on yleensä kai kiinteä rakenne ja kamina erillinen jaloilla seisova esine.  Tosin nykyään kyllä näkyy mainoskuvissa jonkinlaisia  "kevyttakkoja", joka saattaa olla vaikka ripustettu katosta.  Sitten on vielä kaasutakkoja, joissa lämpö tuotetaan kaasuliekillä (tai se on vain koristetakka).

- En yhdistäisi takkoja ja kamiinoja.

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan uusi käsite _ahjot_. Aasi-ryhmä pohtii, onko löydettävissä jokin sekä avotakat että luukulliset takat sisällyttävä käsite tai ilmaisu ruotsiksi. Ruotsiksi tarkenne termille _tulipesät_.

**Comment by mariaforsen** [comment]
Sv. ässjor HT härdar (ässjor), smideshärdar, smidesugnar, smidesässjor 
https://svenska.se/tre/?sok=%C3%A4ssja&pz=1
https://www.sanakirja.fi/custom/fi-en-sv/ahjo
https://www.sanakirja.fi/custom/fi-en-sv/%C3%A4ssja

**Comment by mirmaid** [comment]
Vaatiiko _takat_ vielä toimenpiteitä? https://github.com/Finto-ehdotus/YSE/issues/10670#issuecomment-1413281322

**Comment by mariaforsen** [comment]
Viimeksi käsitelty AASIssa 30.3.23: "Svårt att hitta en term/termer som täcker bägge spistyperna, men ändå inte överlappar med de redan befintliga (eldstäder, kaminer, kakelungar, vedspisar..) Ur svenskans synvinkel hade det varit naturligt att detta begrepp begränsats till öppna spisar." Eli AASI-ryhmän mielestä tämän olisi ollut hyvä pitää avotakkoina, kun kerta muuntyyppiset tulisijat ovat jo sanastossa erikseen. Mutta kielierohan tässä on ja jos tämä rajaus avotakkoihin ruotsiksi nyt aiheuttaa virheitä, niin varmaan ainoa mahdollinen ratkaisu on laittaa "öppna spisar och braskaminer". Ongelmana siinä on sitten myös että se on osittain päällekkäinen kaminer eli kamiinat-käsitteen kanssa. Eli jos aineistossa on kamiinatyyppisistä tulisijoista kyse niin ainakin ruotsiksi olisi laitettava sekä "öppna spisar och braskaminer" (joka on sitten osittain väärin -jos aineistossa ei ole kysymys avotakoista), että kaminer. Miten suomeksi asiasanoitettaisiin?

**Comment by mirmaid** [comment]
Kysyinkin tuolla jo aiemmin, halutaanko yhdistää takat ja kamiinat, kun vähän näytti että tämä ottaa sen suunnan. Kamiinahan on sellainen melko pieni ja yksinkertainen lämmityslaite (Googlen kuvahaulla kamiina) ja takka tyypillisesti suurempi ja usein huoneen sisustuksessa hallitseva elementti, joko avotakka tai varaava. Kuvailussa tulisi aineistosta riippuen jompi kumpi tai molemmat termit. Kamiinat/takat käytetään ristiin sellaisista modernimmista, pienehköistä mutta myös sisustusarvoa omaavista takoista (näköjään joskus kevyttakat). 

Olisihan se vähän hassu jos kyse olisi jostain [retkikamiinasta](https://www.baits.fi/haghus-bunker-kamiina-120-36x37x25cm.html) että kuvailussa olisi takat ja kamiinat, mutta on tässä hassumpaakin nähty 🙂

**Comment by YSO-kokous** [comment]
**Päätös**

Yhdistetään _takat_ ja _kamiinat_.

**Comment by mariaforsen** [comment]
Sv. brasspisar och kaminer HT öppna spisar
https://termipankki.fi/tepa/fi/haku/takka
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_867ed529da7ee611417611f9752f8809&list_id=1&keyword=takka&word=takka
https://www.sanakirja.fi/custom/en-sv-fi/takka
