### ISSUE TITLE
norrsken

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10675]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[norrsken](http://www.yso.fi/onto/yso/p12044)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus etenkin ruotsiksi ja englanniksi ja/tai uusien termien lisäys?

**Perustelut ehdotukselle**

Ruotsiksi vastineena norrsken ja englanniksi northern lights, mutta onko suomenkielinen termi tarkoitus viitata sekä pohjoiseen että eteläiseen versioon, ks. https://www.kielitoimistonsanakirja.fi/#/revontulet?searchMode=all ? Eli polarsken/auroras (lcsh). SAOssa on kaikki, eli polarsken, norrsken (aurora borealis) ja sydsken (aurora australis, suomeksi eteläntuli?)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Voisi lisätä KT eteläntulet/eteläntuli. Revontulet-sanaa käytetään myös samasta ilmiöstä muilla planeetoilla.

**Comment by YSO-kokous** [comment]
**Päätös**

Ohjaustermiksi _eteläntulet_ tai _eteläntuli_.
