### ISSUE TITLE
MAL-sopimukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10671]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

MAL-sopimukset

**Ehdotettu termi ruotsiksi**

avtal om markanvändning, boende och trafik

**Ehdotettu termi englanniksi**

land use, housing and transport agreements

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://ym.fi/maankayton-asumisen-ja-liikenteen-sopimukset
Maankäytön, asumisen ja liikenteen (MAL) sopimukset ovat sopimuksia, jotka valtio solmii suurimpien kaupunkiseutujen kanssa. Sopimukset vahvistavat seudun kuntien keskinäistä sekä seudun ja valtion välistä yhteistyötä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Maankäytön, asumisen ja liikenteen sopimukset

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

MAL-sopimusmenettelyn tila ja kehittämistarpeet ISBN 978-952-293-836-7

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [MAL-sopimukset](http://finto.fi/yse/fi/page/Y510671)

**Comment by ilona-x** [comment]
Kuvailu onnistunee termeillä maankäyttö + asuminen + liikenne + sopimukset

**Comment by mariaforsen** [comment]
Sv. avtal om markanvändning, boende och trafik HT MBT-avtal
Olisi kieltämättä kätevämpi tämä lyhyt ja tarkka muoto, kuin asiasanojen yhdistely.

**Comment by fantsby-m** [comment]
Tuolla on ruotsiksi MBT-avtal:
https://ym.fi/sv/avtal-om-markanvandning-boende-och-trafik

**Comment by mariaforsen** [comment]
Kyllä, kirjoitusvirhe yllä.

**Comment by mirmaid** [comment]
Melindassa kerran MAL-yhteistyö.

**Comment by mirmaid** [comment]
Googlella n. 7000.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
