### ISSUE TITLE
robottikirurgia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10681]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[robottikirurgia](http://www.yso.fi/onto/yso/p24936)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT robottiavusteiset leikkaukset

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. HT robotassisterad kirurgi, robotassisterade operationer
