### ISSUE TITLE
sapovirukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10689]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sapovirukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sapovirus

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Sapovirukset
Sapovirukset ovat viruksia, jotka aiheuttavat ihmisissä vatsatautia, kuumetta, ripulia ja päänsärkyä. Ne kuuluvat kalikivirusten heimoon yhdessä lähisukulaisensa noroviruksen kanssa.
Norovirus jostain syystä yksikössä, pitäisikö senkin olla monikko?

**Ehdotettu yläkäsite YSOssa (LT)**

 [virukset](http://www.yso.fi/onto/yso/p1123)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 sapovirus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://hdl.handle.net/10138/338722

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [sapovirukset](http://finto.fi/yse/fi/page/Y510689)

**Comment by ilona-x** [comment]
FinMeSHissä yksikössä **Sapovirus** http://www.yso.fi/onto/mesh/D029341

**Comment by mirmaid** [comment]
Pitäisikö olla yksikössä myös YSOssa, jos kyse on yhdestä viruksesta? 

_Kansainvälisen virusluokituskomitean (ICTV) mukaan sapoviruksiin sisältyy vain yksi viruslaji nimeltä sapporovirus. Sapovirukset ovat siitä huolimatta erittäin heterogeeninen virusryhmä, joka jakaantuu 19 genoryhmään ja vähintään 17 genotyyppiin._

_It is a monotypic taxon containing only one species, the Sapporo virus._ https://en.wikipedia.org/wiki/Sapovirus

**Comment by mirmaid** [comment]
https://laji.fi/taxon/MX.282909

**Comment by mariaforsen** [comment]
Sv. sapovirus HT sapporovirus
https://mesh.kib.ki.se/term/D029341/sapovirus

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään yksikössä, ohjaustermiksi _sapporovirus_.
