### ISSUE TITLE
Vesunnin kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10680]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vesunnin kartano](http://www.yso.fi/onto/yso/p20507)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö kuitenkin olla Vesunnan kartano?
Paikoissa Vesunti (Hattula)

**Perustelut ehdotukselle**

Julkaisussa tätä muotoa käytetään https://www.dropbox.com/sh/t34wtt0xszr0in3/AABl96hXIKLPV2A8qs1zm_Mfa?dl=0
"Virallisesti tila eli kartano
on viime aikoina ollut Vesunta ja koko kylä
puolestaan Vesunti, mutta tässäkin asiassa
on ollut käytännössä horjuntaa"
Ja täällä https://www.hamewiki.fi/wiki/Vesunta

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Wikipedia: https://fi.wikipedia.org/wiki/Vesunnin_kartano

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan _Vesunnan kartano_, ohjaustermiksi _Vesunnin kartano_ ja _Vesunta (kartano)_.
