### ISSUE TITLE
sosiaalinen robotiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10688]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sosiaalinen robotiikka

**Ehdotettu termi ruotsiksi**

social robotik

**Ehdotettu termi englanniksi**

social robotics

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ollut käytössä jo lähes kymmenen vuotta.  Löytyy TSR-sanastosta ja KOKOsta.  http://www.yso.fi/onto/koko/p66321  
Tämä on eri käsite kuin "sosiaaliset robotit" joka on sosiaalisen robotiikan tutkimuskohde.

**Ehdotettu yläkäsite YSOssa (LT)**

 [robotiikka](http://www.yso.fi/onto/yso/p2615)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553), [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549)

**Vaihtoehtoiset termit**

 hoivarobotiikka, avustusrobotiikka

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [robotit](http://www.yso.fi/onto/yso/p2619)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. https://sites.tuni.fi/tamk-julkaisut/terveys/sosiaalinen-robotiikka-osaksi-hoitotyota-sallamaari-isoniemi-jenna-lamberg-ja-sari-himanen/

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [sosiaalinen robotiikka](http://finto.fi/yse/fi/page/Y510688)

**Comment by mirmaid** [comment]
_Sosiaaliset robotit_ kerran Melindassa. Googlella n. 1200 kertaa, sosiaalinen robotiikka n. 300.

**Comment by mariaforsen** [comment]
Sv. social robotik, sociala robotar

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Social_robot

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään termi _sosiaaliset robotit_, ohjaustermeiksi _hoivarobotit_ ja _avustusrobotit_. Käytä käsitettä _robotiikka_ tarvittaessa.

**Comment by mariaforsen** [comment]
Sv. sociala robotar HT assisterande robotar, vårdrobotar
https://www.kth.se/student/kurser/kurs/DD2413?l=sv
