### ISSUE TITLE
lapsenlapsettomuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10692]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lapsenlapsettomuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Asialle ei löydy minkäänlaista asiasanaa. Esim. Pirjo Lääperin kirjassa Lapsettomuuden monet kasvot 978-952-94-6129-5 (2022) tuotakin näkökulmaa käsitellään, mutta Kipa:n asiasanoitus ei sitä mitenkään paljasta. Voisiko tuo lapsenlapsettomuus olla sopiva käsite ottaa käyttöön?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lapsenlapsettomuus](http://finto.fi/yse/fi/page/Y510692)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by jarmosaarikko** [comment]
englanniksi esim.  https://en.wiktionary.org/wiki/grandchildless
tai lack of grandchildren.  Kts. myös https://childlessbymarriageblog.com/tag/grandchildlessness/

**Comment by mariaforsen** [comment]
Sv. barnbarnslöshet HT barnbarnlöshet
