### ISSUE TITLE
TAVI-toimenpide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10699]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

TAVI-toimenpide

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/334561

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [TAVI-toimenpide](http://finto.fi/yse/fi/page/Y510699)

**Comment by mirmaid** [comment]
https://sydan.fi/fakta/lappavikojen-hoidon-yleisperiaatteet/
https://www.terveyskyla.fi/sydansairaudet/toimenpiteet/katetrin-avulla-teht%C3%A4v%C3%A4-aorttal%C3%A4p%C3%A4n-toimenpide-eli-tavi

**Comment by ilona-x** [comment]
FinMeSH:
katetriteitse tehtävä aortan tekoläpän asennus http://www.yso.fi/onto/mesh/D065467
KT aortan tekoläpän asennus katetrin kautta 
KT aortan tekoläpän katetriasennus

**Comment by mariaforsen** [comment]
Sv. kateterburen aortaklaffimplantation HT TAVI-ingrepp

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _TAVI-toimenpide_, ohjaustermit FinMeSHistä.
