### ISSUE TITLE
pysyvät orgaaniset yhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10698]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pysyvät orgaaniset yhdisteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/335753

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pysyvät orgaaniset yhdisteet](http://finto.fi/yse/fi/page/Y510698)

**Comment by mirmaid** [comment]
6 viitettä Melindassa, 13 kertaa POP-yhdisteet.

https://www.ymparisto.fi/POP
https://fi.wikipedia.org/wiki/POP-yhdiste

**Comment by mariaforsen** [comment]
Sv. långlivade organiska föreningar /tukes, HT långlivade organiska föroreningar, POP-föreningar, POP-föroreningar
https://mesh.kib.ki.se/term/D000083462/lnglivade-organiska-froreningar

**Comment by fantsby-m** [comment]
Myös
https://tukes.fi/kemikaalit/pysyvat-orgaaniset-yhdisteet-pop

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
suomeksi myös [pysyvät orgaaniset saasteet](https://finto.fi/mesh/fi/page/D000083462) ? https://finto.fi/mesh/fi/page/D000083462?clang=sv
