### ISSUE TITLE
kannabidioli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10691]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kannabidioli

**Ehdotettu termi ruotsiksi**

cannabidiol

**Ehdotettu termi englanniksi**

cannabidiol 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kannabidioli eli CBD on hampussa (Cannabis sativa) esiintyvä psykoaktiivinen yhdiste,[4] jota on Suomessa saatavilla Epidyolex-nimisenä lääkevalmisteena,[5] Yliopiston Apteekin valmistamana oraaliliuoksena[6] sekä THC-CBD-yhdistelmävalmiste Sativexina.[7]
https://fi.wikipedia.org/wiki/Kannabidioli

**Ehdotettu yläkäsite YSOssa (LT)**

 [kannabinoidit](http://www.yso.fi/onto/yso/p24479)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 CBD

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

CBD ja hampunviljely Suomessa https://doi.org/10.6084/m9.figshare.19097018

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kannabidioli](http://finto.fi/yse/fi/page/Y510691)

**Comment by ilona-x** [comment]
FinMeSH:
kannabidioli http://www.yso.fi/onto/mesh/D002185

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
