### ISSUE TITLE
tehostettu tuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10693]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tehostettu tuki

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://jultika.oulu.fi/Record/isbn978-952-62-2928-7

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tehostettu tuki](http://finto.fi/yse/fi/page/Y510693)

**Comment by mirmaid** [comment]
https://verneri.net/yleis/yleinen-tehostettu-ja-erityinen-tuki

Sanastossa on _erityinen tuki_ (ja _vaativa erityinen tuki_).

**Comment by mirmaid** [comment]
2 kertaa Melindassa + ehdotuksen aineisto.

**Comment by mariaforsen** [comment]
Sv. intensifierat stöd (undervisning)
https://www.oph.fi/sv/utbildning-och-examina/stod-larande-och-skolgang

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan parasta tarkennetta ennen hyväksyntää. Tarkenteeksi (opetus), jos siinä ei ole ongelmia.
