### ISSUE TITLE
päästölähteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10697]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

päästölähteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/335753

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [päästölähteet](http://finto.fi/yse/fi/page/Y510697)

**Comment by ilona-x** [comment]
fi        päästölähde
sv       emissionskälla; utsläppskälla
en      emission source

määritelmä
Laitos, laite tai prosessi, josta päästetään epäpuhtauksia ilmaan.
definition
Any factory, furnace, chemical process, etc. that discharges pollutants into the air (SWM).

Luokitus: ympäristötieteet
	  
Lähde:Tieteen termipankki 02.02.2022, Ympäristötieteet:päästölähde
https://termipankki.fi/tepa/fi/haku/p%C3%A4%C3%A4st%C3%B6l%C3%A4hde

**Comment by mariaforsen** [comment]
Sv. utsläppskällor HT emissionskällor
https://svenska.se/tre/?sok=utsl%C3%A4ppsk%C3%A4lla&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, ohjausterminä lähteet (päästölähteet).
