### ISSUE TITLE
lähteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10696]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lähteet](http://www.yso.fi/onto/yso/p14935)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitseeko tarkenteen?

**Perustelut ehdotukselle**

Käytetty ainakin joskus myös merkityksessä "tiedonlähteet".

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
käytetty myös muutaman kerran merkityksessä päästölähteet
Melinda päästöt & lähteet tuottaa 4 viitettä

--

päästölähteet ehdotettu https://github.com/Finto-ehdotus/YSE/issues/10697

**Comment by mariaforsen** [comment]
Kannatan tarkentamista ja ehkä ohjauksia.
SAOssa https://id.kb.se/term/sao/K%C3%A4llor%20%28vattendrag%29

**Comment by ilona-x** [comment]
olisiko **lähteet (pienvedet)**, jos otetaan yläkäsite tarkenteeksi?

**Comment by mirmaid** [comment]
Ehdotus: lisätään tarkenne lähteet (pienvedet)
