### ISSUE TITLE
laukkaneilikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10695]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laukkaneilikka](http://www.yso.fi/onto/yso/p13658)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus, myös eng. ja sv. Mikä on oikea latinankielinen nimi?

**Perustelut ehdotukselle**

Epätarkka, nyt eng. Armeria ja ruotsiksi taas backtrift=Armeria maritima subsp. elongata
https://laji.fi/taxon/MX.38291
https://laji.fi/taxon/MX.38292

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Yksikössä, eli viittaa alun perin sanastossa lajiin. https://fi.wikipedia.org/wiki/Rusolaukkaneilikka

Kerran Melindassa myös suvusta.

**Comment by mirmaid** [comment]
Ehdotus > rusolaukkaneilikka KT laukkaneilikka (laji)
