### ISSUE TITLE
kosketinsoitinmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10690]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kosketinsoitinmusiikki

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

keyboard instrument music

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [soitinmusiikki](http://www.yso.fi/onto/yso/p1514)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 klaveerimusiikki, klaverimusiikki, klaveeriteokset, klaveriteokset, kosketinsoitinteokset

**Alakäsitteet (RT)**

 [cembalomusiikki](http://www.yso.fi/onto/yso/p38833), [pianomusiikki](http://www.yso.fi/onto/yso/p38044), [urkumusiikki](http://www.yso.fi/onto/yso/p38028)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85072115)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/009075118 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kosketinsoitinmusiikki](http://finto.fi/yse/fi/page/Y510690)

**Comment by mariaforsen** [comment]
Sv. musik för tangentinstrument HT tangentinstrumentmusik

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
