### ISSUE TITLE
treffit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10703]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[treffit](http://www.yso.fi/onto/yso/p27030)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Deittailu-asiasana tarvitaan ehdottomasti erikseen, ei käy ohjausterminä käsitteeseen treffit. 

**Perustelut ehdotukselle**

Jos kirja käsittelee deittailua (esim. deittailuelämää, deittipalveluja, deittailukokemuksia tms.), ei siihen käy mitenkään asiasanaksi "treffit" (yksittäinen tapahtuma) tai seurustelu. "Ihmissuhteet" taas on laajempi ja viittaa jotenkin jo vakiintuneisiin ihmissuhteisiin, ei siihen että tutustuu siellä täällä moniin ihmisiin, joihinkin vain hieman ja joihinkin enemmän. Käsitys ihmissuhdekentästä vaikuttaa jotenkin auttamatta vanhentuneelta, jos treffit ja seurustelu ovat ainoat vaihtoehdot. Deittailu on aivan oma maailmansa ja iso osa nykytodellisuutta. Deittailu ei välttämättä edes sisällä treffejä. Jos esim. käyttää deittipalveluja, selaa ja matchaa ihmisiä mutta ei päädy treffeille heidän kanssaan - henkilö on silti deittailumaailmassa. Jos puhutaan esim. syrjinnästä deittailumaailmassa, niin syrjintää voi kokea deittipalveluissa ilman että käy edes kenenkään kanssa treffeillä.

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by satuniininen** [comment]
Olisiko syytä vaihtaa käytettävä termi? Molempia tuskin tarvitaan ja Melindasta löytyi vain yksi kuvailu, johon deittailu ei sopisi (Anna-lehden artikkeli, jossa neljän pariskunnan haastattelu laatuajasta treffeillä)

**Comment by mariaforsen** [comment]
Sv. onkin tähän asti ollut dejter. Toinen mahdollinen vastine olisi träffar, mutta se on jo YSOssa fi. tapaamiset.

**Comment by mirmaid** [comment]
Ehdotus: Satun esittämä treffit KÄ deittailu.

**Comment by krinay** [comment]
Voisiko/kannattaisiko lisätä _treffit_ ohjaustermiksi myös termille _tapaamiset_? 

Kielitoimiston sanakirja:
**treffit**
ark. sovittu tapaaminen (us. seurustelutarkoituksessa).
Tehdä treffit.
Sopia treffeistä jkn kanssa.
Lähteä treffeille.
Mulla on treffit siskon kanssa.
