### ISSUE TITLE
bifobia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10702]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

bifobia

**Ehdotettu termi ruotsiksi**

bifobi

**Ehdotettu termi englanniksi**

biphobia

**Tarkoitusta täsmentävä selite**

Bifobia on biseksuaalisuutta tai biseksuaalisia henkilöitä kohtaan tunnettua pelkoa, vastenmielisyyttä tai heihin kohdistuvaa syrjintää.

**Perustelut ehdotukselle**

Tullut viimeaikoina vastaan kolme eri teosta joissa käsitellään bifobiaa ja biseksuaalisuutta. YSO:ssa on asiasana homofobia, joten loogisesti myös bifobia pitäisi löytyä sieltä (YSO ei varmaankaan halua osallistua biseksuaalisuuden häivyttämiseen joka on yleinen bifobian muoto https://fi.wikipedia.org/wiki/Biseksuaalisuuden_h%C3%A4ivytt%C3%A4minen). Homofobia-sanaa ei voi käyttää tässä yhteydessä, koska se on aivan eri asia. Bifobia kohdistuu biseksuaalisuuteen kahdelta suunnalta: sekä heteroyhteisön suunnalta että queer-yhteisön sisältä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [asenteet](http://www.yso.fi/onto/yso/p5619)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [homofobia](http://www.yso.fi/onto/yso/p25221), [heteroseksismi](http://www.yso.fi/onto/yso/p39232), [ennakkoluulot](http://www.yso.fi/onto/yso/p12678)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Bifobia)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lois Sharing: Bi the way - The bisexual guide to life, 
Julia Shaw : Bi - the hidden culture, history, and science of bisexuality,
Jenny Kangasvuo : Bi- ja panseksuaalisuus. 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [bifobia](http://finto.fi/yse/fi/page/Y510702)

**Comment by mirmaid** [comment]
Hierarkia (?):
eng. wikipedia: _It is a form of homophobia against those in the bisexual community._ Homophobia: _Homophobia encompasses a range of negative attitudes and feelings toward homosexuality or people who are identified or perceived as being lesbian, gay, bisexual, or transgender (LGBT)._
sv. wikipedia: _Bifobi och homofobi är skilda fenomen som delar vissa gemensamma drag._

**Comment by mariaforsen** [comment]
Sanastosta puuttuu myös transfobia. Ruotsin osalta nämä saisivat kaikki olla samalla tasolla hierakiassa (nyt YK asenteet, ruotsiksi voisi olla myös YK diskriminering)
https://svenska.se/so/?sok=homofobi&pz=1
https://svenska.se/so/?id=186103&ref=kcnr3005832
https://id.kb.se/find?q=transfobi 
https://id.kb.se/find?q=homofobi

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan _bifobia_ ja _transfobia_.
