### ISSUE TITLE
entiteetti-suhdemalli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10705]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

entiteetti-suhdemalli

**Ehdotettu termi ruotsiksi**

entitet-relation modell

**Ehdotettu termi englanniksi**

entity-relationship model

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esimerkiksi kirjastojen käyttämä RDA tai BIBFRAME.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tietomallit](http://www.yso.fi/onto/yso/p25167)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

 ER-malli, ERM

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata: entiteetti-suhdemalli](http://www.wikidata.org/entity/Q624546), [LCSH : Entity-relationship modeling](http://id.loc.gov/authorities/subjects/sh00009200)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Artikkeleita ja julkaisuja, joissa aiheena RDA tai Bibframe.

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [entiteetti-suhdemalli](http://finto.fi/yse/fi/page/Y510705)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/ER-kaavio

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään käsite _entiteetti-suhdemallit_, _ER-mallit_ ohjaustermiksi.

**Comment by mariaforsen** [comment]
Sv. entitet-relationsmodeller HT ER-modeller https://dbwebb.se/guide/kom-igang-med-sql-i-mysql-v2/entity-relationship-modell
http://www.diva-portal.org/smash/get/diva2:1310447/FULLTEXT01.pdf
http://www.databasteknik.se/webbkursen/er/index.html
