### ISSUE TITLE
muurinpohjapannu?

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10708]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

muurinpohjapannu?

**Ehdotettu termi ruotsiksi**

stekhäll

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvittaisiin aineiston kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Keittokirja Laga mat på stekhäll : utrustning, tekniker och recept 978-91-89371-94-1

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [muurinpohjapannu?](http://finto.fi/yse/fi/page/Y510708)

**Comment by mirmaid** [comment]
KT muurikat, muurinpohjalettupannut

**Comment by mirmaid** [comment]
_Muurikka_ näistä eniten käytetty (ylivoimaisesti), mutta se on kuitenkin tuotemerkki, ja muutenkin _muurinpohjapannut_ varmaan selkein termi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. stekhällar HT murbottenpannor
https://svenska.se/tre/?sok=stekh%C3%A4ll&pz=1
