### ISSUE TITLE
syrjäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10707]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[syrjäytyminen](http://www.yso.fi/onto/yso/p8917)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englanninkielisissä ohjaustermeissä kirjoitus-/lyöntivirheet, po. 
marginalisation (social exclusion) (nyt: maginalisation...)
marginalization (social exclusion) (nyt: maginalization...)
social marginality (nyt: social maginality)

**Perustelut ehdotukselle**

Termit eivät virheen takia löydy haussa.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Korjattu.
