### ISSUE TITLE
riisitauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10700]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

riisitauti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/335661

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [riisitauti](http://finto.fi/yse/fi/page/Y510700)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D012279
TERO: http://www.yso.fi/onto/tero/T01011
AFO: http://www.yso.fi/onto/afo/p941

**Comment by mariaforsen** [comment]
Sv. rakit  HT engelska sjukan, rakitis
