### ISSUE TITLE
golemit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10706]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

golemit

**Ehdotettu termi ruotsiksi**

golemer

**Ehdotettu termi englanniksi**

golems

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sanastossa ei ennestään sopivaa tarkkaa asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [taruolennot](http://www.yso.fi/onto/yso/p797)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85055800), [Wikidata](https://www.wikidata.org/wiki/Q215085)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/005767255, https://melinda.kansalliskirjasto.fi/byid/002500763 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [golemit](http://finto.fi/yse/fi/page/Y510706)

**Comment by mariaforsen** [comment]
Sv. golem
SAO: https://id.kb.se/term/sao/Golem%20%28judisk%20mystik%29
En löydä mitään lähteitä sille että monikkomuoto olisi ruotsiksi golemer, sen sijaan käytetään kyllä golem myös monikkomuotona useissa eri lähteissä. Kysytty myös: https://frageladan.isof.se/fragasr.py

**Comment by jtuohini** [comment]
Yksikkömuodossa olisi ongelmallinen, kun tarusto tuntee useita golemeja (joista Prahan toki tunnetuin): yksikössä asiasana viittaisi yksittäiseen taruhahmoon, monikossa useaan, ja jos viitattaisiin yksittäiseen, kuuluisi erisnimisenä Kantoon.

**Comment by mirmaid** [comment]
^ Sanastossa on myös Jumala yksikössä käsitteenä "monoteistisen uskonnon jumala" ja Pyhä Henki. Myös LCSH:ssa Golem on yksikössä (150). 

Omasta puolestani monikko kyllä käy, mutta yksikkökin tuntuu sikäli luontevalta, että näissä legendoissa tuntuu olevan kyse nimenomaan yhdestä olennosta "kerrallaan".

Sanastossa yksikössä myös (vaikeasti taipuva) poltergeist ja antikristus.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään käsite _golemit_.
