### ISSUE TITLE
Asemakylä (Ii, Iin keskustaajama?)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10717]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Asemakylä (Ii, Iin keskustaajama?)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

HUOM. Iissä kaksi Asemakylää, joista toisen aiempi sijaintikunta Kuivaniemi
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=asemakyl%C3%A4

MML-karttapalvelussa toisen tyyppi on  Kaupunkialue tai taajama ja toisen Kaupunkialueen tai taajaman osa

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [Ii](http://www.yso.fi/onto/yso/p105167)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Asemanseutu (Ii), Asemankylä (Ii)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [PNR](http://paikkatiedot.fi/so/1000772/10123969), [Wikipedia](https://fi.wikipedia.org/wiki/Asemankyl%C3%A4_(Ii))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Iin aseman seudun elämää 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Asemakylä (Ii, Iin keskustaajama?)](http://finto.fi/yse/fi/page/Y510717)

**Comment by mirmaid** [comment]
Auktorisoidaan molemmat Asemakylät, tämän tarkenne ehdotuksen mukaan.
