### ISSUE TITLE
matkakirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10718]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[matkakirjallisuus](http://www.yso.fi/onto/yso/p5978)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM, matkakirjallisuus: Tarkennus suhteessa matkakertomuksiin tai poisto?

**Perustelut ehdotukselle**

Kuuluuko todella SLM-sanastoon? 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. on ollut reselitteratur, epäselvää mihin se viittaa? Sanastossahan on myös sekä matkaoppaat että matkakertomukset.

**Comment by mirmaid** [comment]
KAUNO-kokoukseen. Suhde _matkakertomukset_-termiin?

**Comment by AuHo22** [comment]
https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:matkakirjallisuus
https://fi.wikipedia.org/wiki/Matkakertomus

**Comment by mirmaid** [comment]
Ehdotettu SLM-ryhmässä:
matkakirjallisuus (kaunokirjallisuus)
matkakertomukset (tietokirjallisuus) KT matkakirjallisuus (tietokirjallisuus)
matkaoppaat KT matkakirjallisuus (matkaoppaat)

**Comment by mirmaid** [comment]
KAUNO-ryhmä:
Kannatetaan SLM-ryhmän ehdotusta:
o	matkakirjallisuus (kaunokirjallisuus)
o	matkakertomukset (tietokirjallisuus) KT matkakirjallisuus (tietokirjallisuus)

**Comment by mirmaid** [comment]
Hyväksytään:
matkakirjallisuus (kaunokirjallisuus)
matkakertomukset (tietokirjallisuus) KT matkakirjallisuus (tietokirjallisuus)
matkaoppaat KT matkakirjallisuus (matkaoppaat)

**Comment by mirmaid** [comment]
YSO?

**Comment by krinay** [comment]
Kuinka helppoa on tehdä ero kaunokirjallisen matkakirjallisuuden ja tietokirjallisuudeksi tulkittavien matkakertomusten välillä? (Melindan viitteitä selaillessa ero vaikuttaa usein epäselvältä.)

Ylle linkitettyjen Wikipedia-artikkelin tai Tieteen termipankin (kirjallisuudentutkimus) määritelmät eivät taida juuri auttaa.
Wikipedia: "Matkakertomus sijoittuu kaunokirjallisuuden ja tietokirjallisuuden, faktan ja fiktion välimaastoon." 
Tieteen termipankki (kirjallisuudentutkimus): "Matkakirjallisuuden skaala ulottuu viihteellisistä seikkailukertomuksista tieteellisiin esityksiin."

Jos YSOssa olisi vain yksi termi, voisi kuvailua tarkentaa muilla käsitteillä silloin, kun kyse on selvästi tieto- tai kaunokirjallisuudesta. Usein ollaan varmaan jossakin välimaastossa. 

Matkaoppaat on erikseen ja lienee käsitteenä aika selvä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään tarkenteet.
