### ISSUE TITLE
läpilyönti (sähkötekniikka)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10715]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

läpilyönti (sähkötekniikka)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/336482

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [läpilyönti (sähkötekniikka)](http://finto.fi/yse/fi/page/Y510715)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/L%C3%A4pily%C3%B6ntij%C3%A4nnite
https://en.wikipedia.org/wiki/Electrical_breakdown

**Comment by mirmaid** [comment]
Melindassa kerran kerran läpilyönti-ilmiö ja kerran läpilyöntijännite.

**Comment by mariaforsen** [comment]
Sv. genomslag (elektricitet)

**Comment by ilona-x** [comment]
LCSH:
[Breakdown (Electricity)](https://id.loc.gov/authorities/subjects/sh85016670)

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/electric%20breakdown

IEC Electropedia
fi      sähköinen läpilyönti
sv      isolationssammanbrott
en      (electric) breakdown

	  
Lähde:	IEC Electropedia 2017-10, IEV 121-13-15
	  
IATE1
fi        läpilyönti;
eristyksen pettäminen
sv       isolationssammanbrott
en      electric breakdown;
disruptive discharge

  
Lähde:IATE 02.02.2022, Euroopan unioni (1372640)
	  
IATE4
fi        eristimen läpilyönti
sv       genomslag;
punktering
en      puncture;
electric breakdown;
discharge failure
  
Lähde:IATE 02.02.2022, Euroopan unioni (1375086)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Ohjaustermiksi läpilyönti (sähkö).
