### ISSUE TITLE
valokaari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10714]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

valokaari

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/336482

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [valokaari](http://finto.fi/yse/fi/page/Y510714)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Valokaari
LCSH: http://id.loc.gov/authorities/subjects/sh85041587

3 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. ljusbåge

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
