### ISSUE TITLE
genotoksisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10710]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

genotoksisuus

**Ehdotettu termi ruotsiksi**

genotoxitet

**Ehdotettu termi englanniksi**

genotoxicity 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 4 (+ 6 x afo-terminä)

**Ehdotettu yläkäsite YSOssa (LT)**

 [myrkyllisyys](http://www.yso.fi/onto/yso/p12637)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 perimämyrkyllisyys

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [TSR](http://www.yso.fi/onto/tsr/p7904), [AFO](http://www.yso.fi/onto/afo/p5841)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Nanomateriaalien syöpävaarallisuuden tunnistaminen : loppuraportti työsuojelurahaston hankkeesta n:o 117369 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [genotoksisuus](http://finto.fi/yse/fi/page/Y510710)

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Nimitys:genotoksinen

Lääketieteen termit: _(aineen) taipumus vahingoittaa DNA:ta ja aiheuttaa mutaatioita_

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. genotoxicitet HT gentoxicitet, genotoxitet
https://www.fass.se/LIF/wordlist?userType=0&page=G
