### ISSUE TITLE
Taka-Karpatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10721]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Taka-Karpatia

**Ehdotettu termi ruotsiksi**

Transkarpatiens oblast

**Ehdotettu termi englanniksi**

Zakarpattia Oblast

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailen kaunokirjallista teosta, joka kertoo alueesta 1939 alkaen. Ukraina ei silloin hallinnut aluetta, vaan Tsekkoslovakia ja sitten Unkari. Vasta sen jälkeen Neuvostoliitto liitti alueen Ukrainan alaisuuteen. Olisi tärkeä kuvailla oikealla termillä Transkarpatia alueen mukaan, eikä sen maan, joka sitä milloinkin on hallinnut.
Karpaatit on liian laaja termi kuvailemaan nimenomaan Ukrainan aluetta, joka sijaitsee Karpaateilla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Ukraina](http://www.yso.fi/onto/yso/p107664), [Karpaatit](http://www.yso.fi/onto/yso/p107670)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Transkarpatia

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Taka-Karpatia](https://fi.wikipedia.org/wiki/Taka-Karpatia), [Rutenia](https://fi.wikipedia.org/wiki/Rutenia)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Koly vidtšyneni vorota raju...978-617-7457-15-1

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto

**Comment by mirmaid** [comment]
Transkarpatia KT Taka-Karpatia, YK Ukraina, RT muut valtiot.
