### ISSUE TITLE
väriaineaurinkokennot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10720]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

väriaineaurinkokennot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://en.wikipedia.org/wiki/Dye-sensitized_solar_cell

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.aalto.fi/fi/tapahtumat/vaitos-teknillisen-fysiikan-alalta-di-aapo-poskela

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [väriaineaurinkokennot](http://finto.fi/yse/fi/page/Y510720)

**Comment by mirmaid** [comment]
2 kertaa Melindassa aikaisemmin.

**Comment by ilona-x** [comment]
LCSH: 
Dye-sensitized solar cells http://id.loc.gov/authorities/subjects/sh2004001083

**Comment by mariaforsen** [comment]
Sv. Grätzelsolceller HT färgämnessensiterade solceller, färgkänsliga solceller, färgsensibiliserade solceller, färgsensiterade solceller
https://sv.wikipedia.org/wiki/Gr%C3%A4tzelsolcell
https://www.theseus.fi/bitstream/handle/10024/500209/Linden_Nico.pdf?sequence=2&isAllowed=y
https://www.energinyheter.se/20190803/14251/kinesisk-solcell-ger-el-i-alla-vader

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään käsite _väriaineaurinkokennot_.
