### ISSUE TITLE
jälkikaihi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10725]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jälkikaihi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/334235

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [jälkikaihi](http://finto.fi/yse/fi/page/Y510725)

**Comment by mirmaid** [comment]
FinMeSH: mykiön kotelon samentuminen, http://www.yso.fi/onto/mesh/D058442

https://www.terveyskirjasto.fi/dlk01210

**Comment by mariaforsen** [comment]
Sv. efterstarr /mesh HT sekundär katarakt
