### ISSUE TITLE
Humanitär logistik

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10738]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Humanitaarinen logistiikka

**Ehdotettu termi ruotsiksi**

Humanitär logistik

**Ehdotettu termi englanniksi**

Humanitarian logistics

**Tarkoitusta täsmentävä selite**

https://en.wikipedia.org/wiki/Humanitarian_logistics

**Perustelut ehdotukselle**

Vi har använt den termen mycket på Hanken

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Till exempel: https://www.finna.fi/Record/hanna.779485 och https://www.finna.fi/Record/hanna.692132

**Ehdottajan organisaatio**

Hanken Svenska handelshögskolans bibliotek
**Termiehdotus Fintossa:** [Humanitär logistik](http://finto.fi/yse/fi/page/Y510738)

**Comment by mirmaid** [comment]
3 kertaa Melindassa. Käytetty ainakin _katastrofiapu + logistiikka_.

**Comment by LeKorsu** [comment]
Tässä en näe - ainakaan toistaiseksi - mitään Pandoran lipasta, eli kovin monia uusia  x:n logistiikka -ehdotuksia.
