### ISSUE TITLE
valokaapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10737]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[valokaapelit](http://www.yso.fi/onto/yso/p11672)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermeiksi kuitukaapelit ja valokuitukaapelit?

LCSH-linkki mahdollisesti tähän?:
Fiber optic cables http://id.loc.gov/authorities/subjects/sh96010068

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/kuitukaapeli
https://termipankki.fi/tepa/fi/haku/valokuitukaapeli
https://www.wikidata.org/wiki/Q197961

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Ja optiset kaapelit myös ohjaustermiksi? https://termipankki.fi/tepa/fi/haku/optinen%20kaapeli
