### ISSUE TITLE
SLM tietovisat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10736]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM tietovisat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

lautapeleistä ja konsolipeleistä puuttuu tämä kategoria aivan täysin ja nyt ei ole enää edes älykkyyspelejä, jotka ehkä menisi jotenkin lähimmäksi tätä?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Are you smarter than 5th grader konsolipelit

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mariaforsen** [comment]
Sv. frågesporter, frågesportspel?
RT visailukysymykset=frågesportsfrågor? On jo sanastossa.

**Comment by mirmaid** [comment]
^ Eikö nämä olisi jo aika päällekkäiset?

**Comment by mariaforsen** [comment]
Jos ei haluta erikseen, niin varmaan pitäisi olla ainakin ohjausterminä (käytä visailukysymykset)? Mutta eihän se sama asia ole, ja ymmärrän ettei visailukysymykset sovi jos kyseessä on esim. konsolipeli. Entä termi tietopelit? https://www.lautapelit.fi/category/157/tietopelit

**Comment by ilona-x** [comment]
> Entä termi tietopelit? https://www.lautapelit.fi/category/157/tietopelit

Tietopelit kuulostaisi kyllä monikäyttöisemmältä kuin tietovisat. Microsoftin pelikaupassa näyttää olevan kategoria  "Ongelmanratkaisu- ja tietopelit" https://www.microsoft.com/fi-fi/store/top-paid/games/pc?category=Puzzle+%26+trivia&cid=msft_web_chart

Ehdotuksessa on esimerkkinä annettu ["Are you smarter than 5th grader"-peli ](https://store.playstation.com/fi-fi/product/EP4539-PPSA03676_00-8414225684065533)näyttää perustuvan samannimiseen tv-tietovisailuohjelmaan.

**Comment by AuHo22** [comment]
Meidän av:n kommentti:
Visailukysymykset liittyy enemmän lautapeleihin/seurapeleihin.
Tuota tietovisat kaipasin konsolipeliin, mutta ei näitä montaa ole ollut, että voi ottaa ohjaustermiksi tai jos SLM ei katso tarpeelliseksi niin sitten voi unohtaa.
JA
Niin, en tiedä mikä tietopelit sitten olisi, ainakin omiin korviin omituinen termi.

**Comment by ilona-x** [comment]
Tietopelit-kategorian lautapelejä on listattu tuolla Marian linkkaamalla lautapelit.fi-sivustolla https://www.lautapelit.fi/category/128/tietopelit ja kategoriassa näyttää olevan myös lautapelitietovisoja esim. https://www.lautapelit.fi/product/45691/maailman-ruokakulttuurit-tietovisa.

**Comment by mirmaid** [comment]
Omaan korvaan _tietovisat_ sellaisenaan kuulostaa tv-ohjelman genreltä. Toki kyse on tavallaan samasta asiasta. Nyt visailukysymykset on käytetty 11 kertaa Melindassa, osin tietopeleistä, osin kirjoista, joissa kysymyksiä. Halutaanko nämä erottaa vai koota yhteen?

**Comment by mirmaid** [comment]
Hyväksytään tietopelit, KT tietovisat (pelit) RT visailukysymykset.

**Comment by mariaforsen** [comment]
Sv. kunskapsspel HT frågespel 
https://se.lautapelit.fi/category/128/tietopelit
https://sv.wikipedia.org/wiki/Kunskapsspel
https://sv.wikipedia.org/wiki/Fr%C3%A5gespel

**Comment by mirmaid** [comment]
YSO?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
