### ISSUE TITLE
paloekologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10734]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

paloekologia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

fire ecology

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Artikkelin nimi: Heinikoiden ja metsiköiden paloekologia vuonna 2020.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85048479.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ilmastometsät: metsät planeetan pelastajina

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [paloekologia](http://finto.fi/yse/fi/page/Y510734)

**Comment by mirmaid** [comment]
Kolme viitettä Melindassa. _Metsäpalot/maastopalot + ekologia_ varmaankin tähän asti käytetty.

Sanastossa on muuten _paleoekologia_, onnistuin koko ajan lukemaan tämän niin.

https://en.wikipedia.org/wiki/Fire_ecology

**Comment by mariaforsen** [comment]
Sv. brandekologi
https://id.kb.se/term/sao/Brandekologi
https://www.metsakeskus.fi/sites/default/files/document/tuli-metsassa-sanasto.pdf
