### ISSUE TITLE
Loput SLM:stä puuttuvat Tenho-termit: alueellinen kuvaus, ammatinkuvaus, esittelyelokuva [esittelee paikkakuntia!], maatalousdokumentti, mediataide, metsätalousdokumentti, musiikkidokumentti, perinne-elokuva, taidedokumentti, uskonnollinen dokumentti, ympäristöelokuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10739]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Loput SLM:stä puuttuvat Tenho-termit: alueellinen kuvaus, ammatinkuvaus, esittelyelokuva [esittelee paikkakuntia!], maatalousdokumentti, mediataide, metsätalousdokumentti, musiikkidokumentti, perinne-elokuva, taidedokumentti, uskonnollinen dokumentti, ympäristöelokuva

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tutkittava, miten nämä konvertoidaan SLM-termeiksi

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kaikki Elonet-elokuvat, joissa kyseisiä on käytetty.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Alueellinen kuvaus ja ammatinkuvaus hankalia, kuvaus voi olla ruotsiksi sekä beskrivning (tietoaineisto) että skildring (kaunokirjallisuus), ja jos nämä halutaan sen lisäksi myös rajata vain elokuviin, niin se pitäisi SLM:ssä näkyä termeissä. Myös perinne-elokuva epäselvä. Muut ok ruotsin kannalta.

**Comment by jtuohini** [comment]
Hyväksytty: **taidedokumentit**. Käyttöhuomautus: musiikin osalta käytä _musiikkidokumentit_ TAI näiden välille LT–ST-suhde (päätetään myöhemmin).

**Comment by mirmaid** [comment]
^ Eli otetaan myös _musiikkidokumentit_ erikseen?

**Comment by jtuohini** [comment]
Varmaan tuo _**musiikkidokumentit**_ siis hyväksyttiin, vaikka en sitä kokouksen tuoksinassa huomannut kirjata. Siitähän on myös erillinen YSE:nsä, jossa Muusa on puoltanut ehdotusta (https://github.com/Finto-ehdotus/YSE/issues/10892).

**Comment by mariaforsen** [comment]
Sv. konstdokumentärer

**Comment by AuHo22** [comment]
Dokumenttielokuvia, joissa on aiheena tietty perinne kuten saunominen, uskonnollisia tai ympäristöaiheita, maataloutta, tiettyä aluetta tai paikkakuntaa käsittelevä kuvaus jne. eli aiheen kuvausta, ei slm-termi? Mediataide?

**Comment by jtuohini** [comment]
Muut kuin _**musiikkidokumentit**_ ja _**taidedokumentit**_ päätettiin jo viimeksi olla ottamatta SLM-sanastoon. Kokouksen tuoksinassa näistä jälkimmäisen muistin kirjata, edellistä en, ja oma muistikuvani on se, että muille näytettiin punaista valoa.
