### ISSUE TITLE
hevosvoima (tai hevoskäyttöinen / hevoskäyttöisyys)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10746]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hevosvoima (tai hevoskäyttöinen / hevoskäyttöisyys)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Hevosen voimin käytettävä työkone tai -väline

**Perustelut ehdotukselle**

Hevos-alkuisissa sanoissa on vain hevoskierto ja hevosajoneuvot, mutta olisi tarvetta merkitä kaikenlaisia hevosvoimalla toimivia työkaluja, erotukseksi moottorivoimaa käyttävistä. Tiedän että teillä on joku ehdotus-osio, mutta en taaskaan löytänyt sitä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museoesineet, esimerkiksi hevoskäyttöinen jääsaha

**Ehdottajan organisaatio**

Espoon kaupunginmuseo
**Termiehdotus Fintossa:** [hevosvoima (tai hevoskäyttöinen / hevoskäyttöisyys)](http://finto.fi/yse/fi/page/Y510746)

**Comment by mirmaid** [comment]
_Hevosvoima_ ei varmaan oikein sovellu, jos ei tarkoiteta nimenomaan tehoa. _Hevoskäyttöiset koneet_ tms. olisi ehkä toimiva, mutta ihan keksitty termi.

**Comment by satuniininen** [comment]
_Hevosvetoiset koneet_ kuulostaisi aavistuksen luontevammalta, vaikka yhtä keksitty sekin.

**Comment by mariaforsen** [comment]
Sv. hästdragna maskiner olisi ok.

**Comment by mirmaid** [comment]
Sekä hevoskäyttöinen, että hevosvetoinen tuovat kyllä tuloksia kun hakee tiettyä konetta, esim. hevosvetoinen/-käyttöinen puimakone.

**Comment by ilona-x** [comment]
Parikkalassa näkyy olevan jopa tällainen museo:
[Hevosvetoisten ajoneuvojen ja työkoneiden museo](https://visitparikkala.fi/nahtavyydet/hevosvetoisten-ajoneuvojen-ja-tyokoneiden-museo/)

**Comment by mirmaid** [comment]
Hevosvetoiset koneet
