### ISSUE TITLE
Sampo (kansanrunous)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10747]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Sampo (kansanrunous)](http://www.yso.fi/onto/yso/p25677)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "kirjokansi"

**Perustelut ehdotukselle**

"Sampo eli kirjokansi on suomalaisessa mytologiassa ihmeellinen kone tai esine, kosintalahja ja sotasaalis, joka liittyy usein Pohjolaan." (https://fi.wikipedia.org/wiki/Sampo_(Kalevala))

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by krinay** [comment]
En kannata _kirjokannen_ lisäämistä _Sammon_ ohjaustermiksi.

Kirjokansi liittyy kyllä Samporunostoon ja on joskus Sammon epiteettikin, mutta ei sama asia. Kirjokansi on tähtitaivas yms.

**Comment by YSO-kokous** [comment]
**Päätös**

Jää termiehdotukseksi.
