### ISSUE TITLE
opinnäytteiden arviointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10759]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

opinnäytteiden arviointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Korkeakoulussa tehtävä opinnäytteen arviointi, kandidaatintyöstä väitöskirjaan.
(ammattikoulut tms.?)

**Perustelut ehdotukselle**

Käsitettä ei oikein voi muodostaa yhdistelemällä muita termejä. Olisi tarvittu jo aikaisemmin...

**Ehdotettu yläkäsite YSOssa (LT)**

 [ohjaus (neuvonta ja opastus)](http://www.yso.fi/onto/yso/p178)

**Ehdotetut temaattiset ryhmät**

 [57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554)

**Vaihtoehtoiset termit**

 opinnäytetöiden arviointi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tieteidenvälisillä poluilla : kokemuksia tieteidenvälisten tutkielmien ohjauksesta ja arvioinnista
https://melinda.kansalliskirjasto.fi/byid/018283593

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [opinnäytteiden arviointi](http://finto.fi/yse/fi/page/Y510759)

**Comment by mariaforsen** [comment]
Sanastossa on kyllä arvointi ja opinnäytteet. Arviointi tosin on monimerkityksinen termi, siitä issue tässä https://github.com/Finto-ehdotus/YSE/issues/10536

**Comment by mirmaid** [comment]
Tämä on ongelma varmaan ennen kaikkea siksi, että tietokannoissa opinnäytteet-lajityypin erottaminen opinnäytteet-asiasanasta ei useinkaan onnistu (ainakaan tavallisen hakijan käytettävissä olevissa keinoilla). Eli opinnäytteet + arviointi -haku tuottaa enimmäkseen opinnäytteitä, joissa on asiasana arviointi. Ongelmaa ei tietenkään pitäisi joutua kiertämään ottamalla sen takia tietty fraasi sanastoon, mutta en tiedä onko nähtävillä olevassa tulevaisuudessa tulossa ratkaisua tähän isompaan ongelmaan.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. bedömning av lärdomsprov HT bedömning av examensarbeten, utvärdering av lärdomsprov, utvärdering av examensarbeten

https://termipankki.fi/tepa/fi/haku/opinn%C3%A4yte
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_5de1543a746971a92f4ffb7ae93b743b&list_id=1&keyword=opinn%C3%A4yte&word=opinn%C3%A4yte
https://termipankki.fi/tepa/fi/haku/arviointi
https://www.oph.fi/sv/utbildning-och-examina/bedomningsordlista-larare
https://www.sanakirja.fi/custom/en-sv-fi/opinn%C3%A4yte
https://finto.fi/yso/fi/page/p1380?clang=sv
