### ISSUE TITLE
aivovienti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10757]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aivovienti](http://www.yso.fi/onto/yso/p16218)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ruotsiksi ohjaustermi hjärnflykt?

**Perustelut ehdotukselle**

tuli vastaan julkaisussa "Hjärnflykt eller inte? " 

https://termipankki.fi/tepa/fi/haku/hj%C3%A4rnflykt

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Lisätty, ja myös muut TEPAssa mainitut muodot.
