### ISSUE TITLE
Bloomsburyn ryhmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10751]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Bloomsburyn ryhmä

**Ehdotettu termi ruotsiksi**

Bloomsburygruppen

**Ehdotettu termi englanniksi**

Bloomsbury group

**Tarkoitusta täsmentävä selite**

"Bloomsburyn ryhmä oli taiteilijoiden ja oppineiden ryhmä, joka kokoontui noin vuodesta 1905 toiseen maailmansotaan asti." Wikiepdia.

**Perustelut ehdotukselle**

Tarvitaan Bloomsburyn ryhmää käsittelevän aineiston kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ryhmät](http://www.yso.fi/onto/yso/p1127), [taiteilijaryhmät](http://www.yso.fi/onto/yso/p2393), [kirjailijaryhmät](http://www.yso.fi/onto/yso/p17381)

**Ehdotetut temaattiset ryhmät**

 [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564), [90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://lccn.loc.gov/sh85015043), [](https://id.kb.se/term/sao/Bloomsburygruppen)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018163651

**Ehdottajan organisaatio**

Taideyliopiston kirjasto 
**Termiehdotus Fintossa:** [Bloomsburyn ryhmä](http://finto.fi/yse/fi/page/Y510751)

**Comment by mirmaid** [comment]
LCSH:ssa 150, mutta itselleni taas vähän epäselvää, miksi tämä ei olisi yhteisö...en tiedä voiko tätä myöskään mitenkään sanoa taiteilija/kirjailijaryhmäksi, kun kaikki jäsenet eivät ole näistä kumpaakaan?

**Comment by mariaforsen** [comment]
Sv. Bloomsburygruppen HT Bloomsbury-gruppen
https://id.kb.se/term/sao/Bloomsburygruppen
