### ISSUE TITLE
Patamäki (Pielavesi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10756]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Patamäki (Pielavesi)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

huom. tälle ei löydy pnr-linkkiä

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mäkien kylät : Venetmäen, Katajamäen, Löytynmäen, Leppämäen ja Patamäen vaiheita

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Patamäki (Pielavesi)](http://finto.fi/yse/fi/page/Y510756)

**Comment by mirmaid** [comment]
Patamäki (Kuopio)
