### ISSUE TITLE
opinnäytteiden ohjaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10758]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

opinnäytteiden ohjaus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Korkeakoulussa tehtävä opinnäytteen ohjaus, kandidaatintyöstä väitöskirjaan.
(ammattikoulut tms.?)

**Perustelut ehdotukselle**

Käsitettä ei oikein voi muodostaa yhdistelemällä muita termejä. Olisi tarvittu jo aikaisemmin...

**Ehdotettu yläkäsite YSOssa (LT)**

 [ohjaus (neuvonta ja opastus)](http://www.yso.fi/onto/yso/p178)

**Ehdotetut temaattiset ryhmät**

 [57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554)

**Vaihtoehtoiset termit**

 opinnäytetöiden ohjaus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tieteidenvälisillä poluilla : kokemuksia tieteidenvälisten tutkielmien ohjauksesta ja arvioinnista
https://melinda.kansalliskirjasto.fi/byid/018283593

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [opinnäytteiden ohjaus](http://finto.fi/yse/fi/page/Y510758)

**Comment by mariaforsen** [comment]
Sv. handledning av lärdomsprov HT handledning av examensarbeten

https://termipankki.fi/tepa/fi/haku/opinn%C3%A4yte
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_5de1543a746971a92f4ffb7ae93b743b&list_id=1&keyword=opinn%C3%A4yte&word=opinn%C3%A4yte
https://www.sanakirja.fi/custom/en-sv-fi/opinn%C3%A4yte
https://finto.fi/yso/fi/page/p1380?clang=sv

**Comment by mirmaid** [comment]
Melindasta löytyy kyllä runsaasti viitteitä yhdistelmällä _opinnäytteet & ohjaus (neuvonta ja opastus)_. En osaa sanoa onko tämä mikään varsinainen Pandoran lipas -tapaus, mutta ainakin _(työ)harjoittelun ohjaus_ tulee mieleen vastaavana.

**Comment by LeKorsu** [comment]
En kannata, komppaan Mirjaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _opinnäytteen ohjaus_ TAI opinnäyteohjaus/opinnäytetyön ohjaus //tutkitaan.

**Comment by ilona-x** [comment]
myös opinnäytetyön ohjaus?
