### ISSUE TITLE
aamukaste

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10750]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aamukaste

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

- 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 kaste (meteorologia)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/326514

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [aamukaste](http://finto.fi/yse/fi/page/Y510750)

**Comment by mirmaid** [comment]
Nyt sanastossa _kaste_ vain sakramenttina.

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

LCSH: http://id.loc.gov/authorities/subjects/sh85037410. Sanastossa myös Dew harvesting, joka aiheena tässä väitöskirjassa.
https://fi.wikipedia.org/wiki/Kaste_(s%C3%A4%C3%A4ilmi%C3%B6)

Jos halutaan ottaa muodossa _kaste_, tarvitaan molemmille tarkenteet.

**Comment by ilona-x** [comment]
Pitäisiköhän joka tapauksessa listätä tarkenne kasteelle. 

Melindasta löytyi ainakin muutamia tällaisia kaste-termillä kuvailtuja artikkeleita:

- Vesipisarat synnyttävät kasteen https://melinda.kansalliskirjasto.fi/byid/013732940
- Kaste maalaa maisemaa https://melinda.kansalliskirjasto.fi/byid/013752031
- Humus, kastemato ja palkokasvit https://melinda.kansalliskirjasto.fi/byid/012795330
- Kastematojen merkitys maaperässä ja kompostoinnissa https://melinda.kansalliskirjasto.fi/byid/012544218

**Comment by mariaforsen** [comment]
Kaste on nyt sv. dop, eli pahasti virheellinen termi kun kyseessä on kaste sääilmiönä. 
Kannatan siis ehdottomasti uutta termiä kaste (meteorologia tms.), EI pelkkä aamukaste, koska sitä voi olla myös iltaisin jne. 
https://id.kb.se/term/sao/Dagg

**Comment by fantsby-m** [comment]
https://tieteentermipankki.fi/wiki/Geofysiikka:kaste

**Comment by mirmaid** [comment]
kaste (uskonto)
kaste (meteorologia)

**Comment by mariaforsen** [comment]
Sv. dagg (meteorologi)
https://svenska.se/tre/?sok=dagg&pz=1
