### ISSUE TITLE
inkluusiokappalemyosiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10768]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

inkluusiokappalemyosiitti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/336605

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [inkluusiokappalemyosiitti](http://finto.fi/yse/fi/page/Y510768)

**Comment by mirmaid** [comment]
https://www.terveyskirjasto.fi/orp01841
MeSH: http://www.yso.fi/onto/mesh/D018979
TERO: http://www.yso.fi/onto/tero/t32339

2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. inklusionskroppsmyosit HT sporadisk inklusionskroppsmyosit /swemesh
