### ISSUE TITLE
neuromuskulaariset taudit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10767]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neuromuskulaariset taudit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/336605

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [neuromuskulaariset taudit](http://finto.fi/yse/fi/page/Y510767)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D009468
LCSH: http://id.loc.gov/authorities/subjects/sh85091146

MeSHissä esim. _lihastaudit_ on tämän alakäsite. 

Melindassa muutamia kertoja sairaudet/taudit.

**Comment by mariaforsen** [comment]
Sv. neuromuskulära sjukdomar HT NMD, nerv-muskelsjukdomar /mesh

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
