### ISSUE TITLE
distaaliset myopatiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10766]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

distaaliset myopatiat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/336605

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [distaaliset myopatiat](http://finto.fi/yse/fi/page/Y510766)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D049310
TERO: http://www.yso.fi/onto/tero/D049310

**Comment by mariaforsen** [comment]
Sv. distala myopatier HT distal muskeldystrofi, distal myopati 1, Welanders distala myopati, tibial muskeldystrofi /swemesh
