### ISSUE TITLE
hauraus-raihnausoireyhtymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10769]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hauraus-raihnausoireyhtymä](http://www.yso.fi/onto/yso/p28376)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT gerastenia

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by HeidiRonkainen** [comment]
Kannatan varsinaiseksi termiksi gerasteniaa. http://urn.fi/URN:NBN:fi-fe2022091459015

**Comment by mirmaid** [comment]
^ Kuulostaa kyllä ytimekkäämmältä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään päätermiksi _gerastenia_.

**Comment by mariaforsen** [comment]
Sv. skörhet hos äldre > gerasteni
https://mesh.kib.ki.se/term/D000073496/frailty
https://www.duodecimlehti.fi/duo12298
https://lakartidningen.se/aktuellt/2020/09/efterlangtad-bred-bok-om-det-sjuka-aldrandet/
https://www.hotus.fi/wp-content/uploads/2020/12/kollat-sv-nayttovinkki-14-2019.pdf
