### ISSUE TITLE
Saale-jääkausi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10779]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Saale-jääkausi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oulu.fi/fi/vaitokset/myohaisen-keski-ja-myohaispleistoseenin-ymparisto-ja-jaatikoitymishistoria-pohjois-pohjanmaalla-ja

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Saale-jääkausi](http://finto.fi/yse/fi/page/Y510779)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Saale-j%C3%A4%C3%A4kausi
BnF: https://data.bnf.fr/11964972/riss__glaciation_/

**Comment by mariaforsen** [comment]
Sv. saaleistiden HT saale

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
