### ISSUE TITLE
biolasi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10773]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

biolasi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/334267

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [biolasi](http://finto.fi/yse/fi/page/Y510773)

**Comment by mirmaid** [comment]
Myös _bioaktiivinen lasi_, 17 kertaa Melindassa. Biolasi 4 kertaa.

https://en.wikipedia.org/wiki/Bioactive_glass
LCSH: Bioactive glasses, http://id.loc.gov/authorities/subjects/sh2014001829

**Comment by mariaforsen** [comment]
Sv. bioglas HT bioaktiva glas, bioaktiva glaser 
https://svenska.se/tre/?sok=glas&pz=1

**Comment by LeKorsu** [comment]
Googlaamalla biolasi 95000 viitettä, bioaktiivinen lasi "vain" 5500

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
