### ISSUE TITLE
puusepät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10777]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[puusepät](http://www.yso.fi/onto/yso/p12330)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: nikkarit

**Perustelut ehdotukselle**

synonymi

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

nikkarit (puusepät), käytä puusepät.
