### ISSUE TITLE
Heräämöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10770]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Heräämöt

**Ehdotettu termi ruotsiksi**

Uppvakningsrum

**Ehdotettu termi englanniksi**

Recovery Room 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termiin törmää opinnäytetyöntekijöiden tiedonhaun ohjauksessa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH](https://meshb.nlm.nih.gov/record/ui?ui=D011997), [Cinahl Subject Headings](http://Post Anesthesia Care Units)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. peri- / postoperatiivista hoitötyötä käsittelevien julkaisujen.

**Ehdottajan organisaatio**

Savonia-amk
**Termiehdotus Fintossa:** [Heräämöt](http://finto.fi/yse/fi/page/Y510770)

**Comment by mirmaid** [comment]
TSR: http://www.yso.fi/onto/tsr/p10183
MeSH: http://www.yso.fi/onto/mesh/D011997
LCSH: http://id.loc.gov/authorities/subjects/sh85111943

Lääketieteen termit: _tila jossa valvotaan ja hoidetaan leikkauksen jälkeen nukutuksesta herääviä potilaita ja jota voidaan käyttää myös leikkausta valmistaviin toimenpiteisiin_

**Comment by mirmaid** [comment]
Melindassa 4 kertaa Finmesh-terminä (yksikössä).

**Comment by mariaforsen** [comment]
Sv. uppvakningsrum HT uppvakningsavdelningar, uppvakningsenheter
https://mesh.kib.ki.se/term/D011997/recovery-room
https://termipankki.fi/tepa/fi/haku/her%C3%A4%C3%A4m%C3%B6

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
