### ISSUE TITLE
kuparirahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10771]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kuparirahat

**Ehdotettu termi ruotsiksi**

kopparmynt

**Ehdotettu termi englanniksi**

copper coins

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSO:sta puuttuu vielä suurelta osin numismaattinen sanasto. Kultarahat löytyy jo terminä, mielestäni olisi käytännöllistä lisätä sen rinnalle muut yleiset rahanvalmistusmetallit, ja niiden alatermeiksi sitten tarvittaessa spesifit historialliset rahat (kuten plootut, jotka löytyvät jo ysosta, vähän hassusti samalta abstraktiotasolta kuin kultarahat)

**Ehdotettu yläkäsite YSOssa (LT)**

 [metallirahat](http://www.yso.fi/onto/yso/p11576)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538), [34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576), [92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [plootut](http://www.yso.fi/onto/yso/p39196)

**Assosiatiiviset (RT)**

 [kultarahat](http://www.yso.fi/onto/yso/p38197)

**Vastaava käsite muussa sanastossa**

 [wikipedia](https://sv.wikipedia.org/wiki/Kopparmynt)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

British countermarks on copper and bronze coins

**Ehdottajan organisaatio**

Museovirasto (kirjasto)
**Termiehdotus Fintossa:** [kuparirahat](http://finto.fi/yse/fi/page/Y510771)

**Comment by mirmaid** [comment]
Myös MAOssa vain _kultarahat_ metallilaaduista.

Melindassa 2 kertaa kuparirahat, 10 kertaa hopearahat, 2 kertaa pronssirahat, kerran nikkelirahat.

**Comment by ilona-x** [comment]
Minulla oli kuvailtavana teos Keskiajan hopearahat : rahanlyönti Turun linnassa https://melinda.kansalliskirjasto.fi/byid/018646238 , ja tuota kuvaillessa huomasin, että MAOssa näyttäisi olevan vähän erilainen lähestyminen näihin rahoihin. Metallirahat-termillä http://www.yso.fi/onto/mao/p865 on MAOssa alakäsitteinä eri aikakausien rahoja, esim. keskiaikaiset rahat, millä on puolestaan huima määrä tarkempia alakäsitteitä. 

Näyttäisi, että tuo MAOn hausta löytyvä kultarahat on itseasiassa YSO-termi eikä MAO-termi.

**Comment by mariaforsen** [comment]
Sv. kopparmynt HT kopparpengar 
-silvermynt HT silverpengar

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, myös hopearahat.
