### ISSUE TITLE
zero waste

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10772]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

zero waste

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

zero waste

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Zero waste -kirjoja on ilmestynyt jo paljon, asiasana olisi hyödyllinen ilmiön tavoittamiseksi. Palvelisi aiheesta tietoa etsiviä asiakkaita.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 zero waste -liike, zero waste -ajattelu

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kestävä elämäntapa](http://www.yso.fi/onto/yso/p38791)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Zero_waste), [Zero Waste Finland](https://zwf.fi/)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Gittemarie Johansen: Sustainable badass : a zero-waste lifestyle guide.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [zero waste](http://finto.fi/yse/fi/page/Y510772)

**Comment by ilona-x** [comment]
fi        nollahukka;
          nollahukka-ajattelu;
          jätteettömyys

sv       nollavfall;
          noll avfall

en      zero waste
	  
Lähde: IATE 02.11.2022, Euroopan unioni (3562050) https://termipankki.fi/tepa/fi/haku/zero%20waste

**Comment by mirmaid** [comment]
4 viitettä Melindassa + muutama yhdistelmä. Kerran nollahukka ja kerran jätteetön muoti/vaatetussuunnittelu

Myös _nollahävikki_.

**Comment by mariaforsen** [comment]
Sv. nollavfall HT noll avfall, noll skräp, zero waste
https://spraktidningen.se/2018/12/nyord2018/
https://termipankki.fi/tepa/fi/haku/nollavfall
https://www.isof.se/vart-uppdrag/samarbeten/hallbarhetstermgruppen/hallbarhetstermlistan/termer/noll-avfall

**Comment by LeKorsu** [comment]
Ehdottomasti jokin suomenkielinen, mutta ei vahvaa kantaa mikä noista termipankin vaihtoehdoista.

**Comment by annamarj** [comment]
Zero Waste voisi kuitenkin olla OT, kun on päässyt käytössä niskan päälle noista suomenkielisistä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _nollahukka_.
