### ISSUE TITLE
Veiksel-jääkausi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10778]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Veiksel-jääkausi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oulu.fi/fi/vaitokset/myohaisen-keski-ja-myohaispleistoseenin-ymparisto-ja-jaatikoitymishistoria-pohjois-pohjanmaalla-ja

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Veiksel-jääkausi](http://finto.fi/yse/fi/page/Y510778)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Veiksel-j%C3%A4%C3%A4kausi
GND: https://d-nb.info/gnd/4127180-4
BnF: https://data.bnf.fr/11945807/wurm__glaciation_/

**Comment by mariaforsen** [comment]
Sv. weichselistiden HT weichsel 
https://www.rikstermbanken.se/termposter/1516/weichsel
https://skb.se/forskning-och-teknik/temasidor/klimat/glacial-historia/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
