### ISSUE TITLE
ketamiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10774]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ketamiini

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/334635

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ketamiini](http://finto.fi/yse/fi/page/Y510774)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D007649
LCSH: http://id.loc.gov/authorities/subjects/sh92004206

**Comment by mariaforsen** [comment]
Sv. ketamin
