### ISSUE TITLE
Pyhän Marian kirkko (Pohja)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10776]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pyhän Marian kirkko (Pohja)](http://www.yso.fi/onto/yso/p1226)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT Pohjan kirkko

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Pohjan_kirkko

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ja Pohjan Pyhän Marian kirkko.
