### ISSUE TITLE
kelluvuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10788]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kelluvuus

**Ehdotettu termi ruotsiksi**

flytförmåga

**Ehdotettu termi englanniksi**

buoyancy

**Tarkoitusta täsmentävä selite**

https://termipankki.fi/tepa/fi/haku/kelluvuus

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 3

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LIIKO](http://www.yso.fi/onto/mero/m8052)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Principles of ship buoyancy and stability  http://urn.fi/URN:ISBN:978-952-64-0580-3

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [kelluvuus](http://finto.fi/yse/fi/page/Y510788)

**Comment by mariaforsen** [comment]
Sv. flytförmåga HT flytkraft, flytbarhet (flytförmåga) 
/Nationalencyklopedin, Tepa

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
