### ISSUE TITLE
kultasirppisammal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10789]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kultasirppisammal

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Kultasirppisammal)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-68727-3-5

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [kultasirppisammal](http://finto.fi/yse/fi/page/Y510789)

**Comment by mariaforsen** [comment]
Sv. mässingmossa HT mässingsmossa /artdatabanken
