### ISSUE TITLE
radioisotoopit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10781]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

radioisotoopit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 radionuklidit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/334551

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [radioisotoopit](http://finto.fi/yse/fi/page/Y510781)

**Comment by mirmaid** [comment]
8 viitettä Melindassa.

https://fi.wikipedia.org/wiki/Radioisotooppi
LCSH: http://id.loc.gov/authorities/subjects/sh85110713
GEO: radioaktiiviset isotoopit, http://www.yso.fi/onto/gtk/GTK2015ID3094

**Comment by mariaforsen** [comment]
Sv. radioisotoper HT radioaktiva isotoper, radioaktiva nuklider, radionuklider /sao, ne

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
