### ISSUE TITLE
dehydraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10782]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

dehydraus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/337803

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [dehydraus](http://finto.fi/yse/fi/page/Y510782)

**Comment by mirmaid** [comment]
https://termipankki.fi/tepa/fi/haku/dehydraus
https://fi.wikipedia.org/wiki/Hydraus#Dehydraus
https://en.wikipedia.org/wiki/Dehydrogenation

LCSH: http://id.loc.gov/authorities/subjects/sh85036493

**Comment by mariaforsen** [comment]
Sv. dehydrogenering /ne HT dehydrering (kemi) https://sv.wikipedia.org/wiki/Dehydrogenering
dehydrering monimerkityksinen (esim. lääketiede, keho)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
