### ISSUE TITLE
Åre

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10784]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Åre

**Ehdotettu termi ruotsiksi**

Åre

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

ks. seuraava kohta

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

matkaoppaat, Viveca Stenin dekkarit

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Åre](http://finto.fi/yse/fi/page/Y510784)

**Comment by mirmaid** [comment]
Auktorisoidaan ilman tarkennetta, linkitys kaikkiin wikidatassa.
