### ISSUE TITLE
Eem-interglasiaali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10780]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Eem-interglasiaali

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oulu.fi/fi/vaitokset/myohaisen-keski-ja-myohaispleistoseenin-ymparisto-ja-jaatikoitymishistoria-pohjois-pohjanmaalla-ja

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Eem-interglasiaali](http://finto.fi/yse/fi/page/Y510780)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Eem-interglasiaali
GND: https://d-nb.info/gnd/4124807-7
BnF: https://data.bnf.fr/12216419/interglaciaire_riss-wurm/

**Comment by mariaforsen** [comment]
Sv. eeminterglacialen HT eem, Eem-interglacialen

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
