### ISSUE TITLE
survivalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10798]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

survivalismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Survivalismi (suomeksi myös Prepper-liike)[1] on harrastus tai elämäntapa, jossa pyritään valmistautumaan hätätilanteisiin tai muihin kansainvälisiin katastrofeihin. Survivalismissa harjoitetaan selviytymis- ja eloonjäämistaitoja sekä varaudutaan hätätilanteisiin varaamalla muun muassa vettä, ruokaa, ampuma-aseita sekä muita tarpeellisia varusteita.[2][3][4] Survivalismi tuli tunnetuksi Yhdysvalloissa kylmän sodan aikaan, kun ydinsodan riski kasvoi silloisen Neuvostoliiton kanssa.[5] Nykyään survivalismi on levinnyt maailmanlaajuiseksi ja sitä harjoitetaan laajalla alueella. Suomessa survivalistien määrä kasvaa jatkuvasti.[6] Populaarikulttuurissa muun muassa Maailmanlopun odottajat ja The Walking Dead -televisiosarjat ovat tehneet survivalismia tunnetuksi . (Wikipedia)

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [survivalismi](http://finto.fi/yse/fi/page/Y510798)

**Comment by jtuohini** [comment]
LCSH-vastine [**Survivalism**](http://id.loc.gov/authorities/subjects/sh85130884)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. survivalism HT prepping
https://id.kb.se/term/sao/Survivalism

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
