### ISSUE TITLE
lehtokinnassammal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10790]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lehtokinnassammal

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://laji.fi/taxon/MX.44216)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-68727-3-5

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [lehtokinnassammal](http://finto.fi/yse/fi/page/Y510790)

**Comment by mariaforsen** [comment]
Sv. klippskapania HT brunkornsmossa, klipp-skapania 
https://namnochslaktskap.artfakta.se/taxa/2530/details
