### ISSUE TITLE
komealupiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10792]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

komealupiini

**Ehdotettu termi ruotsiksi**

blomsterlupin

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 9

**Ehdotettu yläkäsite YSOssa (LT)**

 [lupiinit](http://www.yso.fi/onto/yso/p11290)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533)

**Vaihtoehtoiset termit**

 Lupinus polyphyllus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Laji.fi]( http://tun.fi/MX.38950 ), [Wikipedia](https://fi.wikipedia.org/wiki/Komealupiini)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

UPM:n Pietarsaaren tehtaan alueen vieraslajikartoitus 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [komealupiini](http://finto.fi/yse/fi/page/Y510792)

**Comment by mariaforsen** [comment]
Sv. blomsterlupin /artdatabanken
