### ISSUE TITLE
Lehtimäen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10791]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Lehtimäen kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Lehtim%C3%A4en_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lehtimäen kirkosta ja sen papeista : 1 800-2022 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Lehtimäen kirkko](http://finto.fi/yse/fi/page/Y510791)

**Comment by mariaforsen** [comment]
Sv. Lehtimäki kyrka
