### ISSUE TITLE
mikrogeelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10796]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mikrogeelit

**Ehdotettu termi ruotsiksi**

mikrogeler

**Ehdotettu termi englanniksi**

microgels

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D000080386), [LCSH](http://id.loc.gov/authorities/subjects/sh2018001002)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Thermosensitive poly(N-acryloyl glycinamide) microgels and their application in catalysis 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [mikrogeelit](http://finto.fi/yse/fi/page/Y510796)

**Comment by mariaforsen** [comment]
Sv. mikrogeler HT mikrogel 
https://svenska.se/tre/?sok=gel&pz=1
