### ISSUE TITLE
LCSH-genretermit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10797]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

LCSH-genretermit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Pitäisikö YSOsta poistaa linkitykset LCSH:n sisältämiin genresanoihin, jos näillä on tarkoitus kuvata teoksen genreä, eikä aiheena olevaa genreä? Esim. Symphonic poems <http://id.loc.gov/authorities/subjects/sh85131460> vs. Symphonic poem <http://id.loc.gov/authorities/subjects/sh85131459>

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [LCSH-genretermit](http://finto.fi/yse/fi/page/Y510797)

**Comment by mirmaid** [comment]
Tähän liittyy myös ehdotus https://github.com/Finto-ehdotus/YSE/issues/8111, erityisesti kommentti https://github.com/Finto-ehdotus/YSE/issues/8111#issuecomment-1232672425.

**Comment by mirmaid** [comment]
Onkohan jotain listausta näistä LCSH-termeistä, jos kyse tosiaan on LCGFT-sanaston kanssa päällekkäisistä ”jäänteistä”? Ja onko kaikelle LCSH:ssa jokin vastaava ”aihesana”?

**Comment by jtuohini** [comment]
Ei voi poistaa, sillä kyseiset "jäänteet" toimivat jatkossakin ketjun osina, esim. **Symphonic poems--Analysis, appreciation** ≈ YSO:n **musiikkianalyysi** + **sinfoniset runot**. Ketjuja voidaan muodostaa vapaasti, ja mainitun osalta vain _Symphonic poems--History and criticism_ on poikkeus, joka ohjaa (yksikkö)muotoon **Symphonic poem** ≈ **musiikinhistoria** + **sinfoniset runot**. Ketjun osina voi olla monenmoista, esim. **Symphonies--18th century--Bibliography--Catalogs**, **Symphonies--Analysis, appreciation--History**, **Symphonies--Sound recordings**, **Symphonies--Thematic catalogs**.

**Comment by mirmaid** [comment]
Eli ymmärränkö oikein: lisätään takaisin myös Symphonic poems -linkitys? Vrt. myös henkilöhistoria-esimerkki.

**Comment by mirmaid** [comment]
Entä sinfoniat - symphonies? Nyt jälkimmäinen linkattu vain sinfoniettat-käsitteeseen. Ja konsertot vrt. sinfonia konsertantet. Entä sonaatit, oratoriot? Pitäisi varmaan ihan järjestelmällisesti käydä läpi, puuttuuko YSOsta näitä monikkomuotoisia linkityskohteita, jos tarkoitus on linkittää molempiin.

**Comment by mirmaid** [comment]
Jos kyse ei ole LCGFT-sanastoon siirtyneistä jäänteistä, vaan aidosti aihetermeistä, niin tämä ei varsinaisesti ole SLM-kokouksen asia (itselleni on ollut kyllä aika epäselvää, miten nämä tulkitaan). Haluaisiko joku asiaan vihkiytynyt käydä läpi YSOsta puuttuvia linkityksiä näille musiikkikäsitteille?

**Comment by jtuohini** [comment]
Pikasummaus: siltaus YSO:n asiasanoista LCSH-asiasanoihin on ehdottomasti ok, LCGFT-sanaston termeihin taas ei. Samanmuotoisia on kummassakin (esim. **Operas**, **Sonatas**, **Symphonies**), mutta lisäksi vain LCSH:n puolella on yksikkömuotoisia (**Opera**, **Sonata**, **Symphony**), toimien luonteeltaan hieman vastaavina asiasanapareina kuin mitä meillä ovat esimerkiksi **oopperat** ~ **oopperataide**.
