### ISSUE TITLE
sukupuoli-identiteetti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10794]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuoli-identiteetti](http://www.yso.fi/onto/yso/p3440)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Huomautuksen "Tarkoittaa tunnetta jompaankumpaan sukupuoleen kuulumisesta" muuttaminen. 

**Perustelut ehdotukselle**

Lause antaa ymmärtää että sukupuolia on vain kaksi, tai että sukupuoli-identiteetti koskee vain binäärisen sukupuolikokemuksen omaavia ihmisiä. 

**Ehdottajan organisaatio**

yksityishenkilö

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjan mukaan sukupuoli-identiteetti on yhtä kuin "ihmisen oma kokemus sukupuolestaan t. sukupuolettomuudestaan" (https://www.kielitoimistonsanakirja.fi/sukupuoli-identiteetti).
