### ISSUE TITLE
aaltoyhtälö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10795]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aaltoyhtälö

**Ehdotettu termi ruotsiksi**

vågekvation

**Ehdotettu termi englanniksi**

wave equation

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda:
aaltoyhtälö x 1
aaltoyhtälöt x 1

**Ehdotettu yläkäsite YSOssa (LT)**

 [osittaisdifferentiaaliyhtälöt](http://www.yso.fi/onto/yso/p12392)

**Ehdotetut temaattiset ryhmät**

 [04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikipedia](https://fi.wikipedia.org/wiki/Aaltoyht%C3%A4l%C3%B6), [LCSH](http://id.loc.gov/authorities/subjects/sh85145778)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Regularization strategy and focusing energy with a wave equation for an inverse problem 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [aaltoyhtälö](http://finto.fi/yse/fi/page/Y510795)

**Comment by mariaforsen** [comment]
Sv. vågekvation /ne
