### ISSUE TITLE
fennougristiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10805]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fennougristiikka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.helsinki.fi/fi/humanistinen-tiedekunta/tutkimus/tieteenalat/suomalais-ugrilaisten-seka-pohjoismaisten-kielten-ja-kulttuurien-tutkimus/suomalais-ugrilainen-kielentutkimus

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/327972

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [fennougristiikka](http://finto.fi/yse/fi/page/Y510805)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Fennougristiikka

**Comment by mirmaid** [comment]
Vain reilut 10 kertaa Melindassa. Varmaankin kuvailtu yhdistelmillä, mutta sanastossa on toisaalta esim. _slavistiikka_ ja _germaaninen filologia_.

**Comment by mariaforsen** [comment]
Sv. fennougristik /uppslagsverket finland
https://kaino.kotus.fi/finsk-svensk/?p=article&suru_id=SURU_213cc9f30900cbe2b2a5532a11c950ea&word=fennougristiikka&list_id=10002

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
