### ISSUE TITLE
painotettu opetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10807]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

painotettu opetus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/330292

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [painotettu opetus](http://finto.fi/yse/fi/page/Y510807)

**Comment by mirmaid** [comment]
https://www.hel.fi/helsinki/fi/kasvatus-ja-koulutus/perusopetus/mita-opiskellaan/painotettu/
https://yle.fi/a/3-11166370

**Comment by mariaforsen** [comment]
Sv. betonad undervisning HT intensifierad undervisning, undervisning med särskild betoning
https://kaino.kotus.fi/finsk-svensk/?p=article&suru_id=SURU_0354a9a2a925fa9f82e84dc774781a05&word=erikoisluokka&list_id=8678
https://termipankki.fi/tepa/fi/haku/painotettu%20opetus

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
