### ISSUE TITLE
meriruohoniityt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10808]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

meriruohoniityt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sanastossa ei ole käsitettä meriruoho eikä meriruohoniityt. Käsittelemässäni kirjassa on erikseen pääluvut merileville, mikroleville ja meriruohoniityille, joten kysymys on selvästi eri asioista. "Meriruohot sitovat itseensä yhtä paljon hiiltä kuin maapallon metsät, arvioi kansainvälinen tutkimusryhmä Nature Geosciencessa." https://www.tiede.fi/artikkeli/uutiset/meriruohot_nielevat_hiilta_yhta_paljon_kuin_metsat 

Ks. myös https://atmosmare.fi/meriruohoniityt-arvokkaat-hiilinielut 

Library of Congressilla on sekä seagrasses, seagrass restoration, seagrass dieback että seagrasses as fertilizer asiasanoina.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 meriruohot

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Meriruoho), [LCSH](https://id.loc.gov/authorities/subjects/sh85119300.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtameret ja ilmastonmuutos, Jessica Haapkylä.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [meriruohoniityt](http://finto.fi/yse/fi/page/Y510808)

**Comment by mirmaid** [comment]
_Meriruohot_ vai _meriruohoniityt_? 
https://en.wikipedia.org/wiki/Seagrass_meadow

Melindassa 4 x _meriruoho_

**Comment by mariaforsen** [comment]
Sv. sjögräs
https://sv.wikipedia.org/wiki/Sj%C3%B6gr%C3%A4s

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _meriruohot_.
