### ISSUE TITLE
laihdutuskulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10809]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laihdutuskulttuuri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

diet culture

**Tarkoitusta täsmentävä selite**

https://syomishairioliitto.fi/blogi/mita-laihdutuskulttuurilla-tarkoitetaan-ja-miten-se-liittyy-syomishairioihin 
https://www.tuni.fi/moreenimedia/2020/11/05/sosiaalinen-media-yllapitaa-laihdutuskulttuuria-ja-saa-epavarmaksi-omasta-kehosta-somevaikuttajilla-on-hilliton-vastuu/ 

**Perustelut ehdotukselle**

Jos kirja käsittelee laihdutuskulttuuria eikä laihdutusta, niin asiasana laihdutus antaa väärän kuvan. Laihdutuskulttuuri viittaa siis yhteiskunnalliseen ilmiöön, jossa ihannoidaan laihuutta ja normalisoidaan jatkuvaa laihduttamista. "Laihdutuskulttuuri on uskomusjärjestelmä, joka perustuu siihen, että tietyt kehotyypit ovat arvostetumpia kuin toiset." 

"Laihdutuskulttuurin tunnuspiirteinä voi pitää:

    ▪ tietyn kehomallin, yleensä hoikan/lihaksikkaan, ihannoimista ja ihmisarvoltaan paremmaksi asettamista

    ▪ rasvaisuuden pelkoa

    ▪ huolen lietsomista painoa kohtaan

    ▪ ruokien arvottamista “kielletyiksi”, “sallituiksi”, “hyviksi” ja “pahoiksi”

    ▪ syömisen ansaitsemista liikkumisella tai syömättömyydellä

    ▪ erilaisia syömiseen ja liikkumiseen liittyviä sääntöjä koskien esimerkiksi niiden määrää ja ajankohtia

    ▪ sukupuolittuneita käsityksiä siitä, mitä saa syödä

    ▪ tietynlaista hyvinvointi-, terveys- ja ruokamarkkinointia, jotka ilmentävät mm. yllä mainittuja asioita

    ▪ …ja paaljon muuta" 

https://syomishairioliitto.fi/blogi/mita-laihdutuskulttuurilla-tarkoitetaan-ja-miten-se-liittyy-syomishairioihin  

**Ehdotettu yläkäsite YSOssa (LT)**

 [kulttuuri](http://www.yso.fi/onto/yso/p372)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [laihdutus](http://www.yso.fi/onto/yso/p825)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Raisa Omaheimo: Ratkaisuja läskeille.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [laihdutuskulttuuri](http://finto.fi/yse/fi/page/Y510809)

**Comment by mirmaid** [comment]
Kirja, joka käsittelee laihdutuskulttuuria, käsittelee kuitenkin myös laihdutusta, eli jälkimmäistäkään ei voisi jättää pois kuvailusta. En siis sano, etteikö tämä sana voisi olla käypä kuvaamaan tiettyä ilmiötä, mietin vaan tuota "_laihdutus_ antaa väärän kuvan". On aiheesta toki paljon aineistoa, jossa laihdutusta tarkastellaan kriittisesti (tai monipuolisesti).

**Comment by mariaforsen** [comment]
Sv. bantningskultur HT dietkultur

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
