### ISSUE TITLE
synteettinen maakaasu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10814]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

synteettinen maakaasu

**Ehdotettu termi ruotsiksi**

syntetisk naturgas

**Ehdotettu termi englanniksi**

synthetic natural gas

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 2

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [19 Energia. Polttoaineet](http://www.yso.fi/onto/yso/p26566)

**Vaihtoehtoiset termit**

 SNG, substitute natural gas, maakaasua korvaava kaasu , maakaasun kaltaisesti käytettävä kaasu

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Substitute_natural_gas)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Modelling of component dynamics and system integration in power-to-gas process 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [synteettinen maakaasu](http://finto.fi/yse/fi/page/Y510814)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
