### ISSUE TITLE
geronomit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10812]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

geronomit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [tutkinnon suorittaneet](http://www.yso.fi/onto/yso/p8553)

**Ehdotetut temaattiset ryhmät**

 [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Geronomi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-5441-47-5

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [geronomit](http://finto.fi/yse/fi/page/Y510812)

**Comment by mariaforsen** [comment]
Sv. geronomer https://termipankki.fi/tepa/fi/haku/geronomi
