### ISSUE TITLE
kuva-analyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10813]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuva-analyysi](http://www.yso.fi/onto/yso/p16870)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pitäisikö tälle lisätä ryhmiä esim. 43? Nyt ryhmänä vain 90 

**Perustelut ehdotukselle**

ks. Melinda
https://termipankki.fi/tepa/fi/haku/kuva-analyysi
LCSH: Image analysis http://id.loc.gov/authorities/subjects/sh98002813

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
SAOssa kaksi eri käsitettä:
Bildanalys (datorbehandling) •
Bildanalys (konst) • sao

"Kuvan analyysi tarkoittaa kuvan tarkkaa havainnointia ja tarkastelua eri näkökulmista. Tämän avulla päädytään tulkintaan eli käsitykseen kuvan sisällöstä ja sen viesteistä. Tulkintaan vaikuttavat teos, sen tekijä ja katsoja..." /peda.net 

"Digital Image Analysis or Computer Image Analysis is when a computer or electrical device automatically studies an image to obtain useful information from it. Note that the device is often a computer but may also be an electrical circuit, a digital camera or a mobile phone. It involves the fields of computer or machine vision, and medical imaging, and makes heavy use of pattern recognition, digital geometry, and signal processing. This field of computer science developed in the 1950s at academic institutions such as the MIT A.I. Lab, originally as a branch of artificial intelligence and robotics." 
/ https://en.wikipedia.org/wiki/Image_analysis

**Comment by mirmaid** [comment]
_Taide_ olisi kovin suppea tarkenne:
esim.
https://melinda.kansalliskirjasto.fi/byid/017615981
https://melinda.kansalliskirjasto.fi/byid/015517080

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ryhmä ehdotetusti.
