### ISSUE TITLE
pelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10819]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pelit](http://www.yso.fi/onto/yso/p6062)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko termi jaettavissa tai tarkemmin määriteltävissä?

**Perustelut ehdotukselle**

Ruotsiksi tarkenteen lisäys on tarpeen, koska "spel" on monimerkityksinen termi ja sanastossa on myös termi "spel (fåglar)", mutta ennen tarkenteen valinta pitää tietää mihin kaikkeen on tarkoitus käyttää suomenkielinen "pelit". 

Kielitoimiston sanakirja: 
1.
ajanvietteeksi harjoitettavista määrämuotoisista ja -sääntöisistä kilpailuista t. leikeistä, joissa on välineenä kortteja, nappuloita tms.; myös näissä käytettävistä välineistä. Laajemmin
Video-, tietokonepelit.
2.
urheiluna harjoitettavista kilpailuista, joissa on välineenä pallo tms.
3.
em. kilpailussa määräkertana pelattu oman kokonaisuutensa muodostava ottelu; pelaaminen, pelitapa.
4.
määrätuloksinen kilpailujakso.
(5. kuv. 6. ark.)

Vrt https://svenska.se/tre/?sok=spel&pz=1

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
No, suomeksi tämä on laaja. _Ottelut_ on sanastossa erikseen, mutta aineistoissa nyt varmaan aina on läsnä sekä se, että pelataan pelejä/otteluita, että se, että pelataan peliä (tiettyä lajia).

Nyt kun on e-urheilukin olemassa, jakaminen urheiluun ja muihin peleihin on varmaan aika mahdotonta.

**Comment by YSO-kokous** [comment]
**Päätös**

Ruotsiin lisätään mahdollisesti tarkenne, Aasi-ryhmä tutkii.

**Comment by mariaforsen** [comment]
Sv. spel > spel (objekt)? 
AASI-kokous 24.11: ei ole toimiva/ymmärrettävä tarkenne.
