### ISSUE TITLE
perovskiitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10810]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

petrovskiitit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.aalto.fi/sites/g/files/flghsv161/files/2020-09/Tiittanen_v%C3%A4it%C3%B6stiedote_press_release.pdf

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [perovskiitit](http://finto.fi/yse/fi/page/Y510810)

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh88007689
GEO: http://www.yso.fi/onto/gtk/GTK2015ID2842

**Comment by mirmaid** [comment]
Voisi myös (ehkä täsmällisemmin) olla _perovskiitti_ yksikössä ja _perovskiittiyhdisteet_.

**Comment by mariaforsen** [comment]
Sv. perovskit(er) /ne

**Comment by YSO-kokous** [comment]
**Päätös**

Mirja tutkii.

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q409787 - perovskiitti YK [perovskite mineral group](https://www.wikidata.org/wiki/Q3777775). Jälkimmäinen varmaankin perovskiittiyhdisteet?

**Comment by mirmaid** [comment]
Ehkäpä _perovskiittimateriaalit_. Varmaan voi ottaa myös yksikössä perovskiitti tarkoittamaan (alkuperäistä) siten nimettyä mineraalia, virheellisen käytön mahdollisuus kyllä on, ellei sitten tarkenteena ole (kalsiumtitanaatti). Mutta ehkä tuo "materiaalit" riittää.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _perovskiittimateriaalit_.

**Comment by mariaforsen** [comment]
Sv. perovskitmaterial
https://svenska.yle.fi/a/7-10021961
https://www.solenerginyheter.se/20200213/1504/snart-ar-kommersiella-perovskitsolceller-har
