### ISSUE TITLE
Frill (Uusikaarlepyy)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10817]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Frill (Uusikaarlepyy)

**Ehdotettu termi ruotsiksi**

Frill (Nykarleby)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [Uusikaarlepyy](http://www.yso.fi/onto/yso/p94462)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [PNR](http://paikkatiedot.fi/so/1000772/10701113)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Uudenkaarlepyyn Frillin alueen hoitosuunnitelma 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Frill (Uusikaarlepyy)](http://finto.fi/yse/fi/page/Y510817)

**Comment by mariaforsen** [comment]
Sv. Frill (Nykarleby) HT Frillan (Nykarleby)
https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=frill
https://www.nykarleby.fi/boende-trafik-och-miljo/miljovard
https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/tietokortit/nimisto/paikka/10701113
