### ISSUE TITLE
aatelisarvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10816]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aatelisarvot](http://www.yso.fi/onto/yso/p20850)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisäyksiä assosiat. käsitteisiin: herttuatar, paronitar, vapaaherratar, varakreivi, varakreivitär, markiisi, markiisitar, jaarli.

**Perustelut ehdotukselle**

Lisäykset tarpeellisia

**Ehdottajan organisaatio**

Porvoon kaupunginkirjasto

**Comment by mariaforsen** [comment]
Eli uusia käsitteitä:
herttuattaret=hertiginnor
paronittaret=baronessor
vapaaherrattaret=friherrinnor
varakreivit=vicomter och viscounter 
varakreivittäret=vicomtesser och viscountesser
markiisit=markiser (titlar)
markiisittaret=markisinnor
jaarlit=jarlar HT earler https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_e9e0be3481a55876ef0d247d443a91bf&list_id=1&keyword=jaarli&word=jaarli

**Comment by mirmaid** [comment]
Ja lisäksi vielä _terassimarkiisit_, tuo ulkojuottoloidemme aatelisto.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ehdotuksen mukaan.

**Comment by mariaforsen** [comment]
Viittaako jaarlit siis Iso-Britannian jaarleihin (sv. earl) vai skandinaaviseen (historialliseen) arvonimeen (sv. jarl)?
Ks. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_e9e0be3481a55876ef0d247d443a91bf&list_id=1&keyword=jaarli&word=jaarli https://fi.wikipedia.org/wiki/Jaarli
https://sv.wikipedia.org/wiki/Jarl
