### ISSUE TITLE
naistentaudit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10826]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[naistentaudit](http://www.yso.fi/onto/yso/p1409)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT tai päätermiksi gynekologiset sairaudet

**Perustelut ehdotukselle**

http://www.yso.fi/onto/mesh/D005831

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Sairaalat vahvasti naistentautien kannalla...

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermiksi.
