### ISSUE TITLE
siirtymämetallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10825]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

siirtymämetallit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.uef.fi/fi/artikkeli/fm-toni-eskelinen-vaitos-10122021-uutta-tietoa-siirtymametallikompleksien-optisten-ominaisuuksien

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [siirtymämetallit](http://finto.fi/yse/fi/page/Y510825)

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85136954

24 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. övergångsmetaller HT övergångselement /ne, sao
