### ISSUE TITLE
pionit (hiukkaset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10822]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pionit (hiukkaset)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [hiukkaset](http://www.yso.fi/onto/yso/p7436)

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [WikipediA](https://fi.wikipedia.org/wiki/Pioni_(fysiikka)), [LCSH](https://id.loc.gov/authorities/subjects/sh85102318.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/78496#

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [pionit (hiukkaset)](http://finto.fi/yse/fi/page/Y510822)

**Comment by ilona-x** [comment]
Jos tämä otetaan, niin nyt sanastossa oleva pionit YK pionikasvit tarvitsee myös tarkenteen.

pionit (pionikasvit)? http://www.yso.fi/onto/yso/p21432

**Comment by mariaforsen** [comment]
Sv. pi-mesoner /ne HT π-mesoner, pioner (partiklar), pimesoner
https://sv.wikipedia.org/wiki/Pimeson
