### ISSUE TITLE
hadronit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10823]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hadronit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [hiukkaset](http://www.yso.fi/onto/yso/p7436)

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Hadroni), [LCSH](https://id.loc.gov/authorities/subjects/sh85058212.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/78496#

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [hadronit](http://finto.fi/yse/fi/page/Y510823)

**Comment by mariaforsen** [comment]
Sv. hadroner
