### ISSUE TITLE
Pohjoismaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10827]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pohjoismaat](http://www.yso.fi/onto/yso/p94350)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Skandinavia - ellei katsota eri käsitteeksi, niin lisätään toinen wikidata linkki

**Perustelut ehdotukselle**

Skandinavia on Wikidatassa omana käsitteenään http://www.wikidata.org/entity/Q21195

**Ehdottajan organisaatio**

Finto/js

**Comment by tpalonen** [comment]
Saimme palautetta finto-postiin: "Minkä vuoksi Skandinavia ei ole erillinen termi vaan ohjautuu Pohjoismaiksi? Skandinavia kuuluu Pohjoismaihin, mutta siihen eivät kuulu kaikki Pohjoismaat."

**Comment by mariaforsen** [comment]
Myös SAOssa Skandinavien ja Norden erikseen:

https://id.kb.se/term/sao/Skandinavien "Används om Skandinaviska halvön, samt om området bestående av Sverige, Danmark, Norge."

https://id.kb.se/term/sao/Norden "Används om området bestående av Sverige, Norge, Danmark, Finland, Island och Färöarna."

**Comment by tpalonen** [comment]
PÄÄTÖS:
lisätään ohjaustermi Skandinavian maat KÄYTÄ Pohjoismaat

Skandinavia-termi ei tässä sanastossa ole tarkoitettu olevan synonyymi Pohjoismaille, vaan se vain ohjaa käyttämään Pohjoismaita.

Skandinavia-termiin liittyy ongelmia. Joidenkin määritelmien mukaan siihen sisältyy vain Ruotsi ja Norja, joidenkin mukaan lisäksi myös Tanska, joidenkin mukaan lisäksi myös Islanti. Lisäksi se on myös niemimaan nimitys. Pohjoismaiden ulkopuolella tätä Skandinavia / Pohjoismaat -erottelua ei tyypillisesti tehdä ja ulkolaisessa kirjallisuudessa, kun puhutaan Skandinaviasta, puhutaan usein myös Suomesta. Vrt. LCSH:ssa Nordic countries on ohjaustermi Scandinavialle: http://id.loc.gov/authorities/subjects/sh85117937
