### ISSUE TITLE
säteilynkesto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10821]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

säteilynkesto

**Ehdotettu termi ruotsiksi**

strålningshårdhet

**Ehdotettu termi englanniksi**

radiation hardness / radiation tolerance

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tepa](https://termipankki.fi/tepa/fi/haku/s%C3%A4teilynkesto), [LCSH](https://id.loc.gov/authorities/subjects/sh89004270.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Relevance and guidelines of radiation effect testing beyond the standards for electronic devices and systems used in space and at accelerators

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [säteilynkesto](http://finto.fi/yse/fi/page/Y510821)

**Comment by mirmaid** [comment]
KT (tai päätermiksi) säteilynkestävyys (molempia kerran käytetty Melindassa)

**Comment by ilona-x** [comment]
Google:
"säteilynkestävyys" 2 280 
"säteilynkesto"  576

**Comment by mariaforsen** [comment]
Onko sama kuin meshissä oleva säteilytoleranssi https://finto.fi/mesh/fi/page/D011836?clang=sv ?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään säteilynkestävyys.

**Comment by mariaforsen** [comment]
Sv. strålningshärdighet HT strålningsresistans
Strålningstolerans lääketieteellinen/biologinen.
