### ISSUE TITLE
transsendentaalinen idealismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10820]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[transsendentaalinen idealismi](http://www.yso.fi/onto/yso/p24105)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: kriittinen idealismi

**Perustelut ehdotukselle**

Synonymi. Ks. esim. https://tieteentermipankki.fi/wiki/Nimitys:kriittinen_idealismi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. HT kritisk idealism
