### ISSUE TITLE
oikeuskieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10833]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oikeuskieli](http://www.yso.fi/onto/yso/p25452)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pitäisikö lakikielellä (otettu sanastoon v. 1987) ja oikeuskielellä (otettu sanastoon v. 2011) olla jokin suhde tai voisiko nämä jopa yhdistää?

**Perustelut ehdotukselle**

EKS:
lakikieli KT oikeuskieli

https://tieteentermipankki.fi/wiki/Oikeustiede:oikeuskieli
https://tieteentermipankki.fi/wiki/Oikeustiede:lakikieli

https://www.kielitoimistonsanakirja.fi/#/lakikieli?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/oikeuskieli?searchMode=all

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Lagspråk = sär­präglad språklig stil som an­vänds i lagtexter / https://svenska.se/tre/?sok=lagspr%C3%A5k&pz=1 eli lakitekstissä käytetty kieli, on siis RT tai ST juridiskt språk-termille.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään joko RT- tai hierarkiasuhde.
