### ISSUE TITLE
lähiesimiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10838]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lähiesimiehet](http://www.yso.fi/onto/yso/p26353)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi ohjaustermi lähijohtajat

**Perustelut ehdotukselle**

myös käytössä ja sukupuolineutraali
https://www.theseus.fi/bitstream/handle/10024/170831/piirala_saavinen_ukkola_holappa.pdf?sequence=2&isAllowed=y
http://julkaisut.turkuamk.fi/isbn9789522161284.pdf

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Google-haun perusteella myös **lähiesihenkilöt** näyttää olevan käytössä

**Comment by YSO-kokous** [comment]
**Päätös**

Päätermiksi _lähiesihenkilöt_, muut ohjaustermeiksi.
