### ISSUE TITLE
gliasolut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10834]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

gliasolut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.uef.fi/fi/artikkeli/fm-henna-konttinen-vaitos-3122021-ihmisen-kantasoluista-tuotetut-aivojen-gliasolut-paljastavat

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [gliasolut](http://finto.fi/yse/fi/page/Y510834)

**Comment by mirmaid** [comment]
Lääketieteen termit: gliosyytti, (keskushermoston) hermotukisolu, neurogliasolu | hermosoluja eri tavoin huoltavia useantyyppisiä soluja; ks. myös astrosyytti, ependyymisolu, mikrogliasolu, oligodendrosyytti, Schwannin solu

MeSH: neuroglia KT glia http://www.yso.fi/onto/mesh/D009457
LCSH: http://id.loc.gov/authorities/subjects/sh85091124

**Comment by mariaforsen** [comment]
Sv. gliaceller HT neuroglia, glia NE: "stödjevävnad bestående av gliaceller i hjärna, ryggmärg och ögats näthinna"

**Comment by FinMeSHienPaimentaja** [comment]
"Hermotukisolut" olisi suomenkielisempi, mutta "gliasolut" näyttää käytettävän paljon. Joka tapauksessa lääketieteen puolella terminä ihan tarpeen.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
