### ISSUE TITLE
kaksinnaiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10832]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaksinnaiminen

**Ehdotettu termi ruotsiksi**

tvegifte

**Ehdotettu termi englanniksi**

bigamy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kaunon asiasana joka puuttuu Yso:sta

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ostler, Catherine: The Duchess Countess

**Ehdottajan organisaatio**

Porvoon kaupunginkirjasto
**Termiehdotus Fintossa:** [kaksinnaiminen](http://finto.fi/yse/fi/page/Y510832)

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Bigami ja LC Bigamy
Sv. bigami HT tvegifte

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85013973

Kerran Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
