### ISSUE TITLE
feministinen musiikintutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10836]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

feministinen musiikintutkimus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Feministinen musiikintutkimus on tärkeä tutkimushaara nykyaikaisessa musiikintutkimuksessa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Teen musiikkitieteen gradua, jossa käytän tätä näkökulmaa.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [feministinen musiikintutkimus](http://finto.fi/yse/fi/page/Y510836)

**Comment by jtuohini** [comment]
Eikö riitä YSO:n nykyinen **feministinen tutkimus** + sopiva(t) musiikintutkimuksellinen/-set asiasana(t)? Ja onko gradu nimenomaan oppihistoriallinen, siis feminististä musiikintutkimusta tutkiva, vai sitä edustava (jolloin ei edes tulisi ehdotettua YSO-asiasanaa asiasananaksi, ellei siten 567-kenttään?

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT musiikintutkimus
Englanninkielinen vastine: feminist music research

**Comment by jtuohini** [comment]
Jos tulee sanastoon, niin varmaan toiseksi LT:ksi sitten **feministinen tutkimus**.

**Comment by mirmaid** [comment]
Sanastossa on _feministinen kirjallisuudentutkimus_ ja _feministinen mediatutkimus_.

Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. feministisk musikforskning/musikvetenskap?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
