### ISSUE TITLE
Nummen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10837]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Nummen kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Nummen_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tässä on Jumalan huone. Tässä on taivaan ovi: Nummen kirkon juhlakirja

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Nummen kirkko](http://finto.fi/yse/fi/page/Y510837)

**Comment by mariaforsen** [comment]
Sv. Nummis kyrka
