### ISSUE TITLE
opetusmateriaali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10830]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[opetusmateriaali](http://www.yso.fi/onto/yso/p12049)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitaan myös SLM-sanastoon

**Perustelut ehdotukselle**

Jos tämä on (kuten OKSAssa) "aineisto, jota opettaja käyttää opetuksen yhteydessä tai jonka avulla opettaminen tapahtuu", niin näitä on paljon kuvailtavana. Vai olisiko mahdollisesti ohjaustermi?

**Ehdottajan organisaatio**

ALLFO

**Comment by jtuohini** [comment]
SLM:ssä on jo [**oppimateriaali**](http://urn.fi/URN:NBN:fi:au:slm:s719). Olisiko ehdotettu jotenkin siitä poikkeava?

**Comment by mariaforsen** [comment]
YSO-kokouksen mukaan varmaan oli, koska haluttiin ne kaikki YSOssa pitää, ks. https://github.com/Finto-ehdotus/YSE/issues/9989
OKSAn määritelmät: 
opetusmateriaali=aineisto, jota opettaja käyttää opetuksen (1) yhteydessä tai jonka avulla opettaminen tapahtuu
oppimateriaali=aineisto, jota oppija käyttää opetuksen (1) yhteydessä tai jonka avulla oppiminen tapahtuu

Jos ei pääterminä niin varmaan johonkin ohjausterminä, koska tämänkaltaisia opettajille suunnattuja aineistoja on aika paljon ja nyt jää epäselväksi mitä pitäisi laittaa 655-kenttään. Suhde opetusoppaisiin?

**Comment by mirmaid** [comment]
Käsissä juuri https://melinda.kansalliskirjasto.fi/byid/017996605, voisi käyttää genrenä.

**Comment by AuHo22** [comment]
Itse voisin nähdä vivahde-eroa opetusoppaan ja opetusmateriaalin välillä, eli ensimmäinen voi auttaa opettajaa myös esim. pedagogisissa taidoissa / ohjaustaidoissa ja jälkimmäinen voi sitten olla hyvinkin harjoituskirjamainen, ts. itse opetettavaan asiaan / tehtäviin keskittyvä. Oppaasta tulee myös ensinnä  mieleen kirjamaisuus, kun taas -materiaali voi liittyä laajempaan aineistomuotojen käyttöön.

**Comment by ilona-x** [comment]
Tähän https://melinda.kansalliskirjasto.fi/byid/018758632 olisi voinut käyttää genreä opetusmateriaali

https://kulttuurinvuosikello.fi/polkujakulttuuriseenkestavyyteen/
https://kulttuurinvuosikello.fi/wp-content/uploads/2021/01/Polkuja-kulttuuriseen-kestavyyteen_sivukerralla-RGB.pdf

**Comment by mirmaid** [comment]
Hyväksytty/SLM
Lisätään OKSA-sanaston määritelmät.
