### ISSUE TITLE
maankäyttösopimukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10839]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maankäyttösopimukset

**Ehdotettu termi ruotsiksi**

markanvändningsavtal

**Ehdotettu termi englanniksi**

land use agreements

**Tarkoitusta täsmentävä selite**

https://www.kuntaliitto.fi/tilastot-ja-julkaisut/verkko-oppaat/maapolitiikan-opas/maapolitiikan-keinot/maankayttosopimukset

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sopimukset](http://www.yso.fi/onto/yso/p3356)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [JUPO](http://www.yso.fi/onto/jupo/p1604), [EKS](http://maankäyttösopimus), [OIKO](http://maankäyttösopimus), [MAO](http://www.yso.fi/onto/mao/p7919)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Maankäyttömaksut ja kehittämiskorvaukset :oikeudellinen selvitys maankäyttösopimuksia koskevista käytänteistä 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [maankäyttösopimukset](http://finto.fi/yse/fi/page/Y510839)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

Useammassa erikoisontologiassa, joten varmaankin ok.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
