### ISSUE TITLE
aluevaltuutetut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10849]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aluevaltuutetut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [valtuutetut](http://www.yso.fi/onto/yso/p21148), [luottamushenkilöt](http://www.yso.fi/onto/yso/p350)

**Ehdotetut temaattiset ryhmät**

 [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524)

**Vaihtoehtoiset termit**

 aluevaltuuston jäsenet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Politiikan polttava tuolileikki : edustuksellinen demokratia ja päällekkäisten mandaattien aiheuttamat intressiristiriidat suomalaisessa julkisesssa vallankäytössä 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [aluevaltuutetut](http://finto.fi/yse/fi/page/Y510849)

**Comment by mariaforsen** [comment]
Ks. aluevaltuusto, jonkinlainen tarkennus tarpeen, sv. joko välfärdsområdesfullmäktige tai regionfullmäktige (+tarkenne) l
https://valtioneuvosto.fi/sv/-//1271139/handbok-for-valfardsomradesfullmaktig-har-publicerats

Sv. välfärdsområdesfullmäktige (ledamöter) HT ledamöter i  välfärdsområdesfullmäktige,  välfärdsområdesfullmäktiges ledamöter

https://svenska.se/tre/?sok=fullm%C3%A4ktige&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään tarkenteella (Suomi).
