### ISSUE TITLE
sosiaalihistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10842]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sosiaalihistoria](http://www.yso.fi/onto/yso/p7586)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "yhteiskuntahistoria"

**Perustelut ehdotukselle**

Erittäin käytetty nimitys, josta soisi olevan viittaus sanastossa.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Näin myös SAOssa, eli HT samhällshistoria https://id.kb.se/term/sao/Socialhistoria
