### ISSUE TITLE
vapaa-ajan asuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10844]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vapaa-ajan asuminen

**Ehdotettu termi ruotsiksi**

fritidsboende

**Ehdotettu termi englanniksi**

leisure-time housing 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 6

**Ehdotettu yläkäsite YSOssa (LT)**

 [asuminen](http://www.yso.fi/onto/yso/p1797)

**Ehdotetut temaattiset ryhmät**

 [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549), [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [JUPO](http://www.yso.fi/onto/jupo/p658)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Aika lähteä mökille : kestävän vapaa-ajan asumisen kehittäminen Etelä-Savossa 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [vapaa-ajan asuminen](http://finto.fi/yse/fi/page/Y510844)

**Comment by mirmaid** [comment]
6 kertaa Melindassa.

Sanastossa on _mökkeily_.

**Comment by ilona-x** [comment]
Mökkeily tuntuu viittaavan erityisesti kesämökkeilyyn, englanniksi vastineena näyttää olevan 'summer cottage life'.
 
Toisaalta YSOssa
mökkiläiset → [kesäasukkaat](https://finto.fi/yso/fi/page/p11250)
mökkiläiset → [vapaa-ajan asukkaat](https://finto.fi/yso/fi/page/p27411)

vapaa-ajan asunnot http://www.yso.fi/onto/yso/p21784
ST kesämökit

Eli tämä voisi olla
vapaa-ajan asuminen
ST mökkeily

**Comment by mirmaid** [comment]
_Vapaa-ajan asuminen_ kuulostaa ehkä virallisemmalta "tutkimustermiltä" (ja _mökkeily s_ellaiselta arkisemmalta, "mökkiläisen puutarhakirja" -termiltä), mutta luulen että käyttäisin ainakin itse kyllä aika usein molempia.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _vapaa-ajan asuminen_.

**Comment by mariaforsen** [comment]
Sv. fritidsboende (att bo)
https://svenska.se/tre/?sok=fritidsboende&pz=1
https://svenska.se/tre/?sok=boende&pz=1
https://termipankki.fi/tepa/fi/haku/boende
