### ISSUE TITLE
Laiterla (Salo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10840]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Laiterla (Salo)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Laiterla on kylä Perniössä, nykyisessä Salossa.

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [Salo](http://www.yso.fi/onto/yso/p94396)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/tietokortit/nimisto/paikka/10316610)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-68350-5-1

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Laiterla (Salo)](http://finto.fi/yse/fi/page/Y510840)

**Comment by mirmaid** [comment]
https://www.wikidata.org/wiki/Q18660444
https://fi.wikipedia.org/wiki/Laiterla

Paikkatietoalustalla tämä Salon toinen Laiterla on "talo", http://paikkatiedot.fi/so/1000772/10595415. 
Tarvitaanko tarkempi tarkenne?

**Comment by ilona-x** [comment]
[Asutusnimihakemistossa näin](https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=laiterla): 

**Laiterla** 
Kylä (vir.)
Sijaintikunta: 	Salo
Aiempi sijainti: 	Perniö (Varsinais-Suomi)

**Laiterla**
Kylä (vir.), yksinäistalo
Sijaintikunta: 	Salo
Aiempi sijainti: 	Halikko (Varsinais-Suomi)

**Comment by mirmaid** [comment]
Laiterla (Salo, Perniö)
