### ISSUE TITLE
Neste Oil Ralli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10848]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Neste Oil Ralli](http://www.yso.fi/onto/yso/p27107)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi nimi uutena terminä, ohjausterminä vai muutoksena?

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Suomen_ralli
Sanastossa myös Jyväskylän suurajot, mutta ei tietoa nimenmuutoksista..

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Kyseessä erisniminen tapahtuma, joten kuuluu Kantoon, ei Ysoon. Ja siellä onkin jo huomioitu pari nimenmuotoa: [**Jyväskylän suurajot**](http://urn.fi/URN:NBN:fi:au:finaf:000167895) ja [**Neste Rally Finland**](http://urn.fi/URN:NBN:fi:au:finaf:000167900). Nimenmuutoksen aika (1997) on kummassakin mainittu.

**Comment by jtuohini** [comment]
Nyt Kannossa loputkin erinimiset: [**Neste Oil Rally Finland**](http://urn.fi/URN:NBN:fi:au:finaf:000219548) ja [**Neste Rally Finland (2016-2020)**](http://urn.fi/URN:NBN:fi:au:finaf:000219558).
