### ISSUE TITLE
koirahiihto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10845]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koirahiihto](http://www.yso.fi/onto/yso/p26942)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään käsitteeseen valjakkohiihto?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Siinä mielessä voi olla ongelmallista ettei aina ole kysymys valjakosta, voi olla myös yksittäisen koiran kanssa. Spann on ruotsiksi siis useamman eläimen ryhmä. 
https://www.vul.fi/wanhat-sivut/arkisto/koirahiihtoopas.htm

https://www.vul.fi/aloita-harrastus/talvilajit/valjakkohiihto/ : "Koirahiihdossa suksilla hiihtävä urheilija on kytketty yhteen tai kahteen koiraan vetonarulla. Mikäli koiria on kaksi, ne voidaan kytkeä vetämään joko rinnakkain tai peräkkäin."

**Comment by mirmaid** [comment]
Joo, muistinkin tämän sitten myöhemmin. Tuli vain vastaan kun korjasin valjakkourheilu-viitteitä, joissa hyvin usein oli kyse nimenomaan koirahiihdosta (yhden koiran kanssa).

Tuolla mainitulla sivulla tosin koirahiihto on yksi valjakkohiihdon muoto, muut ovat pulkkahiihto ja valjakkohiihdon yhdistetty. Ja myös koirahiihdossa voi olla kaksi koiraa.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
