### ISSUE TITLE
fetisismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10843]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[fetisismi](http://www.yso.fi/onto/yso/p14324)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaettavaksi: fetisismi (uskonto), fetisismi (seksuaalisuus)

**Perustelut ehdotukselle**

Kaksimerkityksinen termi ja käytetty Melindassa molemmissa (eri) merkityksissä. Myös SAOssa jaettu seksologia vs. uskonto. https://www.kielitoimistonsanakirja.fi/#/fetisismi?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Entä https://en.wikipedia.org/wiki/Commodity_fetishism? 

Tavarafetisismin ja antropologisen fetisismin rajapintaa mm. https://journal.fi/mediaviestinta/article/download/62915/24457 s. 56-57

**Comment by krinay** [comment]
Tieteen termipankki - Uskontotiede:
"Länsimaissa fetisismi irtaantui jo varhain sen alkuperäisestä uskonnollisesta merkityksestä ja sitä on käytetty kriittisenä käsitteenä monilla eri tieteenaloilla (esim. hyödykefetisismi marxilaisessa yhteiskunta- ja talousteoriassa tai seksuaalinen fetisismi psykiatriassa ja psykologiassa)."

**Comment by YSO-kokous** [comment]
**Päätös**

Jatketaan käsittelyä ensi kokouksessa, perehdytään sillä välin.

**Comment by mariaforsen** [comment]
Melindassa 92 kertaa. Näyttää siltä että tarvittaisiin aiemmin mainittujen lisäksi tavarafetisismi-merkityksessä? Sv. varufetischism. Yllä mainitussa artikkelissa pitäisi varmaan olla molemmat asiansanat.
https://fi.wikipedia.org/wiki/Tavarafetisismi

**Comment by krinay** [comment]
Pelkään, että käytännössä voi olla aika hankala erottaa selvästi tosistaan fetisismin eri merkityksiä. Jos termi jaettaisiin, joutuisi ainakin tieteellisten tekstien kuvailussa todennäköisesti aika usein käyttämään molempia asiasanoja tai kaikkia kolmea (koska termin määrittelyssä varmaan käsiteltäisiin noita eri ulottuvuuksia). 
Tieteen termipankki: https://tieteentermipankki.fi/wiki/Uskontotiede:fetisismi

LCSH:ssa on kyllä erikseen Fetishism (BT Rites and ceremonies ja Worship), Commodity Fetishism, Fetishism (Sexual behavior) ja Fetishes (Ceremonial objects). Miten olisi lisäksi kenkä-, saapas- ja sukkafetisismi, nekin LCSH:ssa (hih). 
https://id.loc.gov/search/?q=fetishism&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects#

**Comment by tpalonen** [comment]
Luulisin, että ei ole kovin vaikea erottaa näitä kolmea käsitettä toisistaan. Varsinkin jos marxilaiselle fetisismille valitaan päätermiksi _hyödykefetisismi_ ja yläkäsitteeksi teoriat tai aatteet. Jos päätermi sen sijaan on tavarafetisismi niin ymmärrän, että voi termitasolla mennä sekaisin seksuaalisen fetisismin kanssa, kun usein seksuaalinen fetisismi kohdistuu johonkin vaatteeseen. Ainakin jos Wikipediaa on uskominen, niin mikä tahansa vaate-alkuinen fetisismi on aina seksuaalista fetisismiä.
Ehkä: tavarafetisismi (hyödykefetisismi) KÄYTÄ hyödykefetisismi

**Comment by mirmaid** [comment]
Onko mielestänne (uskonto) riittävän kattava tarkenne kaikelle sille fetisismille, johon Melindassa ei sovi hyödykefetisismi tai seksuaalinen fetisismi?

Kaikissa vaikeiksi kuvittelemissani tapauksissa tulen kääntymään @tpalonen puoleen 😌

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään kolme käsitettä _hyödykefetisismi_ KT _tavarafetisismi (hyödykefetisismi)_, _fetisismi (uskonto)_, _fetisismi (seksuaalisuus)_. _Kulttiesineet_ RT _fetisismi (uskonto)_. _taikaesineet_ RT _fetisismi (uskonto)_.

**Comment by mariaforsen** [comment]
Sv. 
-varufetischism HT fetischism (marxism)
https://www.humanistportalen.se/ordlista/
https://sv.wikipedia.org/wiki/Varufetischism
-fetischism (religion) HT fetischism (antropologi)
-fetischism (sexualitet)
https://id.kb.se/find?q=fetischism
