### ISSUE TITLE
oppilaslähtöisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10846]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oppilaslähtöisyys](http://www.yso.fi/onto/yso/p39191)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "opiskelijalähtöinen opetus" ja "opiskelijalähtöinen pedagogiikka" 

**Perustelut ehdotukselle**

Käytetty kirjallisuussa, esim. Kristian Wahlströmin väitöskirja 2022

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja lisätään siltaus LCSH-sanastoon: [**Student-centered learning**](http://id.loc.gov/authorities/subjects/sh2003008925), KT-muotoinaan _Learner-centered education_, _Learner-controlled instruction_ ja _Student-centered teaching_.

**Comment by YSO-kokous** [comment]
**Päätös**

Oppijalähtöisyys? Tutkitaan seuraavaan kokoukseen.

**Comment by mariaforsen** [comment]
Sv. lärandecentrering?
https://www.psykologiguiden.se/psykologilexikon?Lookup=l%C3%A4randecentrering 
Nykyinen elevcentrering kyllä paljon enemmän käytetty. Ehkä se voi kuitenkin jäädä ruotsiksi.

**Comment by mirmaid** [comment]
Kyllä suomeksikin erityisesti muoto _oppilaslähtöinen opetus_ on hyvin vakiintunut. Ehkä opiskelijalähtöisyys ja oppijalähtöisyys ohjaustermeiksi tässä vaiheessa?

**Comment by jtuohini** [comment]
Kai viittausmuodoiksi lisätään myös nuo alkuperäisessä ehdotuksessa mainitut Wahlströmin väitöskirjassaan käyttämät termit _opiskelijalähtöinen opetus_ ja _opiskelijalähtöinen pedagogiikka_, vaikka asiasana itsessään pidettäisiin nykyisellään?

**Comment by YSO-kokous** [comment]
**Päätös**

Ohjaustermeiksi _opiskelijalähtöisyys_, _oppijalähtöisyys_, _opiskelijalähtöinen opetus_ ja _opiskelijalähtöinen pedagogiikka_.
