### ISSUE TITLE
kompostikäymälät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10847]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kompostikäymälät](http://www.yso.fi/onto/yso/p12730)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi ulkokäymälät tai uutena pääterminä

**Perustelut ehdotukselle**

melko ajankohtainen aihe, mutta toisaalta komposti- ja kuivakäymälöitä tehdään myös sisätiloihin.. https://www.kielitoimistonsanakirja.fi/#/ulkok%C3%A4ym%C3%A4l%C3%A4?searchMode=all
https://fi.wikipedia.org/wiki/Ulkok%C3%A4ym%C3%A4l%C3%A4

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Eikö ulkokäymälät olisi ennemmin ohjaustermi _käymälät_-käsitteelle?

**Comment by mariaforsen** [comment]
Käymälät=toaletter, eli ruotsiksi mikä tahansa vesivessa, kyllä kannatan sitä että myös ulkokäymälät olisi kuvailtavissa. Vai onko käymälät-käsite ongelmallinen monikielisyyden kannalta?

**Comment by mirmaid** [comment]
Voi olla erikseenkin, mutta ei mielestäni ohjausterminä kompostikäymälöille.

**Comment by annamarj** [comment]
Kaikki ulkokäymälät eivät taida tarkemmin ottaen edes olla kompostikäymälöitä. Kannatan mirmaidin huomioita.

**Comment by mariaforsen** [comment]
Samaa mieltä siis, mieluiten uutena erillisenä terminä ulkokäymälät (ja ehkä RT kompostikäymälät).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. utedass HT torrklosetter, dass, utetuppar, hemlighus, avträden
https://id.kb.se/term/sao/Avtr%C3%A4den
https://svenska.se/tre/?sok=avtr%C3%A4de&pz=1
https://svenska.se/so/?id=190311&ref=xnr381640
https://sv.wikipedia.org/wiki/Avtr%C3%A4de
