### ISSUE TITLE
ennustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10859]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ennustukset

**Ehdotettu termi ruotsiksi**

spådomar

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ennustaminen (magia)](http://www.yso.fi/onto/yso/p6090), [profetiat](http://www.yso.fi/onto/yso/p3912)

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/Sp%C3%A5domar)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Keskusteluja Nostradamuksen kanssa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ennustukset](http://finto.fi/yse/fi/page/Y510859)

**Comment by mirmaid** [comment]
On KAUNOssa. YSOssa tämä pitäisi pitää selkeästi erillään _ennusteista_. Sanastossa on _ennustaminen (magia)_ ja _ennustajat_. _Profetiat_ myös paljon käytetty Melindassa Nostradamuksen yhteydessä.

**Comment by mariaforsen** [comment]
Kyllä, ehdottomasti erillisenä terminä, ennuste on aivan eri asia, prognos vs. spådom.

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään seuraavaan kokoukseen.

**Comment by mariaforsen** [comment]
Tässä kuvaillaan selkeästi näiden käsitteiden eroa: https://blogs.helsinki.fi/eksegetiikanmenetelmat/tutkimusta/profetia/profetia/ 

"Toiseksi on tarkasteltava ennustamisen suhdetta profetiaan. Tämä tarve ei nouse vain arkikielenkäytöstä vaan myös siitä tosiasiasta, että profetia usein todella on tulevaisuuteen suuntautunutta. Tässäkin tapauksessa profetia on ensisijaisesti kommunikaatiota. **Profetia voi sisältää ennustuksia ja muita tulevaisuudenvisioita, mutta mikä tahansa ennustus ei ole profetia. Tekstiä ei ole syytä kutsua profetiaksi sillä perusteella, että se sisältää ennustuksia**, ellei se millään tavoin ilmennä yllä kuvattua kommunikaatioprosessia."

**Comment by tpalonen** [comment]
Em. sitaatin lisäksi profetiassa ja ennustuksessa toki sekin ero, että profetia on enemmän uskonnollinen termi ja ennustus yleistermi. Ehdotuksessa mainittu Nostradamus kylläkin teki paljon ennustuksia, mutta en puhuisi hänen kohdallaan profetioista, ainakaan suomen kielen näkökulmasta.

**Comment by jarmosaarikko** [comment]
Kun ennustaminen on
- "divination" http://www.wikidata.org/entity/Q1043197 (divinaatio, ennustaminen)
- "precognition" http://www.wikidata.org/entity/Q520667 (ennaltatietäminen, prekognitio)
- "fortune-telling" http://www.wikidata.org/entity/Q8011595  (myös povaaminen)
  - Fortune telling is the practice of [predicting](https://en.wikipedia.org/wiki/Prediction) information about a person's life 
- https://fi.wikipedia.org/wiki/Ennustaminen_(taikausko)
niin ennustamisen tuloksena syntyy  "tulevaisuutta koskeva tieto", englanniksi näkyy tässä yhteydessä käytettävän termiä "predictions", joka mennee siis sekaisin "ennusteet" käsitteen kanssa. Toinen termi on to tell "fortunes".  povaus?
- oraakkeli tuottaa profeetallisia ennustuksia  "prophetic predictions most notably including [precognition](https://en.wikipedia.org/wiki/Precognition) of the future"

Ehdotus:
**ennustukset**  en: **predictions (divination)** 
KT [fortunes](https://en.wiktionary.org/wiki/fortune#Noun), [precognitions](https://en.wiktionary.org/wiki/precognition), [predictions](https://en.wiktionary.org/wiki/prediction#English) (profecy)

**Comment by mariaforsen** [comment]
Ruotsiksi näiden välillä on ainakin hyvin selkeä ero (uskonnollisuus/jumalallinen vs. mikä tahansa ilman jumalallista näkökulmaa) ja SAOssa on tietysti molemmat.
https://id.kb.se/term/sao/Profetior
https://id.kb.se/term/sao/Sp%C3%A5domar

**Comment by fantsby-m** [comment]
Englannin _prophecies_ sopii sekä profetioihin että ennustuksiin, jälkimmäiseen luontevammin kuin _predictions (divination)_, joka voisi olla ohjausterminä. Asian voisi profetioiden osalta ratkaista tarkenteella: _prophecies (religion)_.

**Comment by mirmaid** [comment]
_Ennustukset_ tarvitsisi siis tarkenteen _(magia)_, jotta se ei sekoittuisi ennusteet-käsitteen kanssa. Itse en oikein hahmota tarvetta, kun sanastossa on jo _ennustaminen (magia)_ - vaikea ajatella, että aineisto käsittelisi vain ennustuksia, mutta ei ennustamista. 

Wikipedia: Nostradamus är mest känd för att ha nedtecknat profetior...samoin suomeksi on siis käytetty profetiat-sanaa Nostradamuksen yhteydessä, joten jos tämä on virheellistä, tarvittaisiin varmaan sillekin jokin tarkenne/määritelmä ja/tai ohjaus ennustukset-termiin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _ennustukset (magia)_, lisätään tarkenne _profetiat (jumalalliset ilmoitukset)_. Tarkastellaan sopivaa yläkäsitettä.
