### ISSUE TITLE
autosoittimet, autostereot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10854]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

autosoittimet, autostereot

**Ehdotettu termi ruotsiksi**

bilstereor

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Eri asia kuin autoradiot

**Ehdotettu yläkäsite YSOssa (LT)**

 [äänentoistolaitteet](http://www.yso.fi/onto/yso/p3137)

**Ehdotetut temaattiset ryhmät**

 [41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [autoradiot](http://www.yso.fi/onto/yso/p13153)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Autosoittimen valinnanvaikeus – näin valitset oikein

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [autosoittimet, autostereot](http://finto.fi/yse/fi/page/Y510854)

**Comment by mirmaid** [comment]
_Autostereot_ 17 kertaa Melindassa. 

Osaakohan joku ottaa kantaa ehdotettuihin termeihin, mitä eroa näillä?

**Comment by nikopartanen** [comment]
Autosoittimista myös puhutaan. LCSH:sta löytyy _Automobiles--Audio equipment_:

http://id.loc.gov/authorities/subjects/sh85010206

**Comment by mariaforsen** [comment]
Autosoitin on kai osa autostereoita, autostereot on kuulemma se kokonaisuus mihin myös kaiuttimet kuuluvat (hifiharrastajalta kysytty). Olisiko siis hyvä ottaa autostereot OT autosoittimet? 

Sv. bilstereor HT bilspelare

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
