### ISSUE TITLE
miinakoirat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10855]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[miinakoirat](http://www.yso.fi/onto/yso/p13185)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi tai päätermiksi pommikoirat, räjähdekoirat

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Pommikoira

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja: 

pommikoira https://www.kielitoimistonsanakirja.fi/#/pommikoira?searchMode=all
kätkettyjen pommien etsintään koulutettu koira. 

miinakoira https://www.kielitoimistonsanakirja.fi/#/miinakoira?searchMode=all
maamiinojen ja räjähteiden etsintään koulutettu koira. 

Mutta varmaan räjähdekoirat KT miinakoirat & KT pommikoirat voisi olla mahdollinen? 🤔 

Suomeksi ei taida oikein olla mitään hyvää vastinetta tälle https://en.wikipedia.org/wiki/Detection_dog 
LCSH: detector dogs http://id.loc.gov/authorities/subjects/sh2001011725

Kun näitä eri asioiden löytämiseen erikoistuneita koiria tuntuu riittävän, olisi kätevää, jos olisi yleiskäyttöisempi termi. 
Esim. [rahakoirat](https://tulli.fi/web/tullikoirat/-/matka-tullin-ensimmaisen-rahakoiran-mukana), [ruokakoirat ](https://tulli.fi/web/tullikoirat/-/ruokakoira-rico-rikkoi-2-000-kilon-loytorajan)
ja YSOsta jo löytyvät huumekoirat ja homekoirat

**Comment by mariaforsen** [comment]
Tavallisin nimitys ruotsiksi taitaa olla bombhund. Sprängämneshund (räjähdekoira) sen sijaan taitaa olla melko kapeamerkityksinen (sellainen jolla tulli on käytössä..) Ks. esim. https://www.iltalehti.fi/fiidifi/a/201608120143359 Räjähdekoirilla ei hirveästi tuloksia googlessakaan tai sanastoissa. En siis kannata miina/pommikoirien korvaamista räjähdekoirat-termillä.

**Comment by YSO-kokous** [comment]
**Päätös**

YSO-ryhmä ehdottaa _räjähdekoirat_ KÄ _pommikoirat_, _miinakoirat_. Aasi-ryhmä tutkii.

**Comment by mariaforsen** [comment]
Eng. "explosive detection dog"? https://ik9i.com/fi/edd/

Sv. sprängämneshundar HT bombhundar, bomb- och minhundar, minhundar, sprängämnessökande hundar

**Comment by mirmaid** [comment]
^ Eli päätermiksi _räjähdekoirat_?

**Comment by jarmosaarikko** [comment]
detection dog on vaikeasti käännettävä, kun yleistermi ei ole vakiintunut

Ehdotan uudeksi yläkäsitteeksi näille nuuskiville "detection dog" koirille termiä 
- **ilmaisukoirat**  | **uttryckshundar** | **detection dogs**   
YK  **työkoirat**
AK huumekoirat, homekoirat, miinakoirat, pommikoirat, hypokoirat, pelastuskoirat

Ilmaisukoirat -termiä on käytetty joissakin opinnäytteissä ja lehtijutuissa. Koirien koulutuksessa puhutaan myös "ilmaisusta", kun koira ilmoittaa havaitsemansa kohteen.

kts. myös https://www.kennelliitto.fi/koirat/hyotykoirat/virkakoirat/tullikoirat   **Tullikoiria** ovat: huumekoirat, savukekoirat, rahakoirat,  ase- ja räjähdekoirat.    Tullikoiria käytetään myös ihmisten etsimiseen. Silloin voisi käyttää tuota ilmaisukoirat -termiä, kun tullikoirat-käsitettä ei ole YSOssa.  Samoin rauniokoirat ja vedesta ruumiita nuuskivat koirat.   Jäljityskoiratkin kuuluisivat tähän kastiin (siis esim. haavoittuneita eläimiä tai rikollisia etsivät nuuskijat).

**Comment by FinMeSHienPaimentaja** [comment]
Tuli mieleen myös "etsintäkoirat", "etsijäkoirat", mutta tarkoittanee enimmäkseen ihmisiä (pelastuskoirat) ja/tai muita eläimiä (kuten karkuteillä olevia koiria) etsiviä koiria.  "Ilmaisukoirat" olisi mielestäni merkityksen osalta hyvä kattokäsite näille kaikille nenätyöskentelyn avulla jotain etsiville koirille, josko se  olisi vaan tarpeeksi käytetty ja ihmisten ymmärtämä termi, mitä epäilen...

**Comment by mariaforsen** [comment]
Ehdotettu "uttryckshund" ei ole ruotsinkielinen termi. Itse keksittyjä termejä en kannata missään tapauksessa. 
Ei näköjään ilmaisukoirakaan ole käytetty.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään YSO-ryhmän edellinen päätös.
