### ISSUE TITLE
sosialisointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10851]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sosialisointi](http://www.yso.fi/onto/yso/p12920)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaettavaksi, yhdistettäväksi, määriteltäväksi tms. selvennys

**Perustelut ehdotukselle**

Ryhmässä 75, mutta käytetty Melindassa myös toisessa merkityksessä (sosiaalipsykologia, sosiologia). Sanastossa myös sosialisaatio ja kansallistaminen. 

**Ehdottajan organisaatio**

ALLFO

**Comment by jtuohini** [comment]
Ehdotan yhdistämistä **kansallistaminen**-asiasanaan ynnä _sosialisoiminen_- ja _valtiollistaminen_-KT-muotojen lisäämistä. Ks. esim. https://www.kielitoimistonsanakirja.fi/kansallistaa.

Nykyisen asiasanan käyttäminen väärässä merkityksessä ei pitäisi johtaa nykyisen sanan jakamiseen, vaan virheelliset pitäisi korjata ennen mehdollista asiasanojen yhteensulauttamista. Vastaava usein väärin käytetty asiasanapari on _symboliikka_ ~ _symbolismi_.

**Comment by jtuohini** [comment]
Nyt Melindasta korjattu kaikki sellaiset tietueet, joissa oli samassa sekä **sosialisaatio** että **sosialisointi**, samoin kuin valtaosa 2000-luvun teoksista (osa jäi vielä). Vaikuttaa siltä, että ruotsin "socialisering" on kuulostanut sopivalta (merkityksessä 'sosialiseeraus', 'sosiaalinen kanssakäyminen') ja siksi päätynyt **socialisation**-asiasanan sijaan, jopa julkaisuissa, joiden otsikossa luki "sosialisaatio"! Ruotsinkielisissä opinnäytteissä näitä oli ja varmastikin edelleen on erityisen paljon väärin, joten ehkä jokin huomautus todella tarvitaan, ellei asiasanaa yhdistetä jo sanamuodoltaan valmiiksi yksiselitteisempään.

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi pitää lisätä tarkenne.

**Comment by mirmaid** [comment]
^^ Ehdotan Jaakolle ansiomitalia 🥇

**Comment by mirmaid** [comment]
_Sosialisoinnin_ yhdistäminen _kansallistamiseen_ olisi ehkä vähän mutkien suoristamista, vaikka toisaalta varmaan hyvin usein niitä käytetään synonyymeina. Suomeksi sosialisointi ei mielestäni tarkoita sosialisaatiota minkäänlaisessa kielenkäytössä, ja sosiaalista kanssakäymistä vain niin epämuodollisessa puhekielessä, että ei varmasti kukaan käyttäisi sitä kuvailussa niin. En ole varma tarvitaanko tässä suomeksi mitään muutosta välttämättä, mutta ruotsiksi varmasti tarkennus paikallaan (talous/sosialismi/marxismi?).

**Comment by YSO-kokous** [comment]
**Päätös**

Ei vaadi muutosta suomeksi. Aasi-ryhmä lisää tarkenteen ruotsiksi.

**Comment by mariaforsen** [comment]
Sv. socialisering (överförande av egendom)
https://svenska.se/tre/?sok=socialisering&pz=1

**Comment by jtuohini** [comment]
Kai _sosialisoiminen_ ja _valtiollistaminen_ kuitenkin lisätään viittausmuodoiksi suomenkielisiin, näemmä erillisiksi jääviin **kansallistaminen**- ja **sosialisointi**-asiasanoihin?

**Comment by mariaforsen** [comment]
Ruotsiksi jo förstatligande (fi. valtiollistaminen) ANVÄND nationalisering (fi. kansallistaminen).
