### ISSUE TITLE
kadunkalusteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10857]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kadunkalusteet](http://www.yso.fi/onto/yso/p13260)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi ohjaustermi katukalusteet

**Perustelut ehdotukselle**

synonymi, https://www.kielitoimistonsanakirja.fi/#/katukaluste?searchMode=all

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Voisi olla päätermikin, tosin ei mikään välttämätön muutos.
