### ISSUE TITLE
aluevaltuustot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10850]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aluevaltuustot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://vaalit.fi/aluevaltuustot

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [valtuustot](http://www.yso.fi/onto/yso/p5256)

**Ehdotetut temaattiset ryhmät**

 [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Politiikan polttava tuolileikki : edustuksellinen demokratia ja päällekkäisten mandaattien aiheuttamat intressiristiriidat suomalaisessa julkisesssa vallankäytössä

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [aluevaltuustot](http://finto.fi/yse/fi/page/Y510850)

**Comment by mariaforsen** [comment]
Näköjään tämä voi suomeksi viitata muuhunkin kuin hyvinvointialueiden valtuustoihin?https://termipankki.fi/tepa/fi/haku/aluevaltuusto
https://regionuppsala.se/fi/politiikka-ja-vaikuttaminen/nain-politiikka-toimii/

"Aluevaltuusto ([ruots.](https://fi.wikipedia.org/wiki/Ruotsin_kieli) regionfullmäktige) valitaan samaan aikaan kuin valtiopäiväedustajat ja kunnanvaltuustot. Vaaleja varten Tukholman lääni on jaettu seuraaviin 12 vaalipiiriin:[[1]](https://fi.wikipedia.org/wiki/Tukholman_alue#cite_note-1)" /https://fi.wikipedia.org/wiki/Tukholman_alue

Sv. joko regionfullmäktige ("yleisempi" valtuusto, varsinkin ruotsissa) TAI välfärdsområdesfullmäktige (hyvinvointialueiden valtuustot) 
https://vaalit.fi/sv/valfardsomradesfullmaktige 
https://www.finlex.fi/sv/laki/ajantasa/2021/20210611 
https://valter.sanakirja.fi/all/all/aluevaltuusto

Eli voisiko lisätä ainakin määritelmän, jos tarkoitus viitata vain hyvinvointialueiden valtuustoihin? Tai sitten mahdollisesti kaksi eri termiä (tarkenteilla). 

Sv. välfärdsområdesfullmäktige (organ)
https://svenska.se/tre/?sok=fullm%C3%A4ktige&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _aluevaltuustot (Suomi)_.
