### ISSUE TITLE
kahlekuninkaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10858]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kahlekuninkaat

**Ehdotettu termi ruotsiksi**

utbrytarkungar

**Ehdotettu termi englanniksi**

escape artists

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [viihdetaiteilijat](http://www.yso.fi/onto/yso/p5329)

**Ehdotetut temaattiset ryhmät**

 [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh97006017), [wikipedia](https://fi.wikipedia.org/wiki/Kahlekuningas), [SAO](https://id.kb.se/term/sao/Utbrytarkungar)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Houdinin legenda 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [kahlekuninkaat](http://finto.fi/yse/fi/page/Y510858)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
