### ISSUE TITLE
osatyökykyiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10852]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[osatyökykyiset](http://www.yso.fi/onto/yso/p27077)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

täsmätyökyky

**Perustelut ehdotukselle**

puhekielessä nykyisin enemmän käytetty, positiivisempi sävytteinen ja vähemmän leimaava käsite 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. anpassad arbetsförmåga? https://valtioneuvosto.fi/-/1410877/tyovoimaa-ja-osaajia-on-tyonantajista-osatyokykyisyys-on-yha-useammin-mahdollisuus?languageId=sv_SE

**Comment by YSO-kokous** [comment]
**Päätös**

Ohjaustermiksi _täsmätyökykyiset_.
