### ISSUE TITLE
samnilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10860]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

samnilaiset

**Ehdotettu termi ruotsiksi**

samniter

**Ehdotettu termi englanniksi**

 samnites

**Tarkoitusta täsmentävä selite**

Keski- ja Etelä-Italiassa (Samniumissa) asuneiden muinaisten kansojen yhteisnimi.
Wikipedia https://fi.wikipedia.org/wiki/Samnilaiset

**Perustelut ehdotukselle**

tarvitaan antiikintutkimuksen aineiston kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

 oskit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Samnium und die Samniten: Roms letzter Rivale ISBN 978-3-933200-40-2  https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9934346979506253

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [samnilaiset](http://finto.fi/yse/fi/page/Y510860)

**Comment by jtuohini** [comment]
LCSH-vastineet: [**Oscans**](http://id.loc.gov/authorities/subjects/sh85095894) ja [**Samnites**](http://id.loc.gov/authorities/subjects/sh85117028).

**Comment by mirmaid** [comment]
Wikipediassa sekä samniter/samnites, että sabeller/sabellians. Onko kattavuus ihan selvä, jos LCSH-vastineita on kaksi? 

Wikipedia: _Although the language of the Samnites was called Oscan, the Samnites were never referred to as Osci, nor were the Osci called Samnites_. https://en.wikipedia.org/wiki/Osci

Tähän olisi vielä hyvä saada ehdottajalta kannanotto.

**Comment by mariaforsen** [comment]
Sv. samniter /nationalencyklopedin: " samlingsnamn för fyra fornitaliska stammar (caracener, caudier, hirpiner och pentrer), löst knutna till varandra i en federation."

**Comment by pirjakara** [comment]
Kyselin antiikintutkimuksen professoreilta, miten samnilaiset, sabelliinit ja oskit suhteutuvat toisiinsa. Sain tällaisen vastauksen: nämä ovat kaikki samaa joukkoa; näillä (ja muillakin, vrt. alh.) nimityksillä tarkoitetaan niitä Italian kansoja, jotka puhuivat latinalla enemmän tai vähemmän sukua olevia kieliä tai, kuten joskus sanotaan, murteita (vastakohtana esim. etruski). Näitä olivat erityisesti samnilaiset, joiden kielestä käytetään nimitystä oski (Keski- ja Etelä-Italiassa), ja umbrialaiset (Umbriassa, siis jo vähän pohjoiseen), sekä pienemmistä ryhmistä esim. paelignit, marrukiinit ja vestiinit; näiden jälkimmäisten kielestä käytetään joskus nimitystä pohjoisoskilaiset tai sabellilaiset murteet (joskus nimitystä Sabellic tms. käytetään myös kaikista näistä kielistä/murteista, esim. H. Rix, Sabellische Texte). Kaikista näistä kielistä/murteista käytetään myös nimitystä Italisch/Italic (vastakohtana Italienisch/Italian).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Varmistetaan linkityksissä suhteen oskeihin menevän oikein.
