### ISSUE TITLE
tuohtumus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10869]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tuohtumus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

indignation

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termi puuttuu YSOsta. Olisi tarvittu sisällönkuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tunteet](http://www.yso.fi/onto/yso/p3485)

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

 närkästys

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018214824

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [tuohtumus](http://finto.fi/yse/fi/page/Y510869)

**Comment by jtuohini** [comment]
Jos otetaan, niin KT-muodoiksi varmaankin _kiivastus_, _kiihtymys_, _suuttumus_ ja _tulistus_. (https://www.kielitoimistonsanakirja.fi/tuohtua)

**Comment by mirmaid** [comment]
Jokin _vihaa_ lievempi negatiivinen tunne varmaan olisi tarpeellinen, mutta tuohtumus ei ehkä ole tarpeeksi luonteva, närkästys samoin - hakisiko kukaan aineistoa tuohtumuksesta tai närkästyksestä?

**Comment by mariaforsen** [comment]
Sv. indignation HT förtrytelse, harm, förargelse

**Comment by ilona-x** [comment]
aiemmin ehdotettu **suuttumus** (ohjaustermeiksi suuttuminen, kiukku) https://github.com/Finto-ehdotus/YSE/issues/2182

FinMeSHissä 
**kíukku**  http://www.yso.fi/onto/mesh/D000786
Ohjaustermit
    suuttuminen
    suuttumus

TSR-ontologiassa puolestaan on **suuttumus** http://www.yso.fi/onto/tsr/p9796
ja KAUNOssa **suuttuminen** http://www.yso.fi/onto/kauno/p375

**Comment by mariaforsen** [comment]
Sv. vrede HT ilska
https://id.kb.se/term/sao/Vrede 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_eff56d069dee89f15d36320a64c428e2&list_id=1&keyword=suuttumus&word=suuttumus
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_09eb6e361171d31426def175560b0a8a&list_id=1&keyword=kiukku&word=kiukku
https://www.sanakirja.fi/custom/en-sv-fi/suuttumus
https://svenska.se/tre/?sok=vrede&pz=1
https://svenska.se/tre/?sok=ilska&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _suuttumus_, ohjaustermiksi _kiukku_.
