### ISSUE TITLE
juutalainen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10864]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[juutalainen kirjallisuus](http://www.yso.fi/onto/yso/p23523)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaihdetaan ryhmä 53 --> 87

**Perustelut ehdotukselle**

Jos asiasana ei ole varattu uskonnolliseen kirjallisuuteen, pitäisi ryhmän olla kirjallisuus, ei uskonto.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan ryhmän lisäämistä, nykyisen ryhmän lisäksi. Nationalencyklopedin: judisk litteratur= "efterbiblisk litteratur som behandlar judiska förhållanden och problem och som återspeglar det judiska folkets öde att leva som en mer eller mindre diskriminerad minoritet. Den är därmed mångspråkig men innehållsligt ofta begränsad till teologiska och religiösa ämnen."

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, lisätään ryhmä.
