### ISSUE TITLE
glutamaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10861]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[glutamaatit](http://www.yso.fi/onto/yso/p13575)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi ohjaustermi: glutamiinihappo

**Perustelut ehdotukselle**

Wikipedia: Glutamiinihappo (C5H9NO4) eli 2-aminopentaanidihappo (lyhenne Glu tai E) on yksi luonnon 20 yleisimmästä aminohaposta. Se tunnetaan myös anioni-nimellään glutamaatti.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
_Glutamate flavoring is the generic name for flavor-enhancing compounds based on glutamic acid and its salts (glutamates)._ https://en.wikipedia.org/wiki/Glutamate_flavoring
