### ISSUE TITLE
ekumenik

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10865]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ekumenik](http://www.yso.fi/onto/yso/p15154)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettava ainakin ruotsiksi

**Perustelut ehdotukselle**

Sanastossa on sekä ekumeniikka että ekumenia, ruotsin vastineet ovat synonymejä, joten ruotsiksi pitää ainakin lisätä tarkenteita, mutta Melindassa on selkeästi myös ekumeniikka käytetty laajempana kuin teologisena oppiaineena jne. Onko asia selvä suomeksi (myös tavalliselle kuvailijalle) ilman tarkenteita tai huomautuksia? https://evl.fi/sanasto/-/glossary/word/Ekumenia https://evl.fi/sanasto/-/glossary/word/Ekumeniikka

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Näiden välillä pitäisi myös olla RT (jos molemmat halutaan pitää).

**Comment by tpalonen** [comment]
Ovathan nuo kaksi eri käsitettä. Huomautukset voisivat ehkä auttaa ja niissä viittaukset toiseen käsitteeseen.

**Comment by mirmaid** [comment]
Ekumenia: Toimintaa, jonka tarkoituksena on edistää kirkkojen yhteyttä.
Ekumeniikka: Ekumeniaa ja sen edellytyksiä tutkiva tiede.

Lisätään RT-suhde, mutta en tiedä, miten tätä voisi suomeksi tarkenteilla ohjata - jos on käytetty väärin, se on ehkä enemmän johtunut siitä, että kuvailija ei ole tuntenut termistöä, kuin siitä, että termien merkityksessä olisi varsinaisesti horjuntaa alalla. Onko esimerkkejä viitteistä, joissa olisi virheellisesti ekumeniikka?

**Comment by mariaforsen** [comment]
Sv. -ekumenik/ekumenism (enhetssträvanden)
-ekumenik (forskning) 
https://id.kb.se/term/sao/Ekumenik
https://evl.fi/sv/sanasto/ekumenik/

Ekumeniikka on käytetty 937 kertaa, mielestäni seassa on aika paljonkin mitä ei koske ekumeniikka tieteenä. 
Ekumenia 3136 kertaa, siinä näyttää olevan myös jonkin verran missä olisi ehkä paremmin myös tieteenä. Minusta rajanveto on monesti aika vaikeaa.

**Comment by mirmaid** [comment]
^ Pystytkö laittamaan muutaman esimerkkitapauksen? Tuo virheellinen käyttö ei ehkä oikein satu silmään, jos ei tunne aihepiiriä niin hyvin. Jotenkin tuntuu, että suomeksi olisi epätodennäköistä, että ekumeniikka-termiä käytettäisiin, jos aineisto käsittelisi vain ekumenian harjoittamista, ja sitten taas toisin päin aineisto, joka käsittelee ekumeniikkaa, melkein väkisinkin käsittelee myös ekumeniaa. Mutta se on toki hyvinkin todennäköistä, että ei ole silloin aina huomattu käyttää molempia.

Ja varmaan ihan vastaavasti historia vs. historiantutkimus jne.

**Comment by mariaforsen** [comment]
Esim.  
Can a renewal movement be renewed? : questions for the future of ecumenism / Michael Kinnamon.
Förverkligad katolicitet : Max Thurians syn på vägar till kyrkans enhet / Jakob Tronêt.
Community, participation, and faith : contemporary challenges of the Evangelical Lutheran Church of Finland / Church Research Institute.
Growing consensus. The dialogue between the Catholic Church and the Oriental Orthodox Churches .
Baptized into Christ : a guide to the ecumenical discussion on baptism / Dagmar Heller.
Haastettu kirkko : Suomen evankelis-luterilainen kirkko vuosina 2008-2011.
Lappeenranta 1998 & Moscow 2002 : the eleventh and twelfth theological discussions between the Evangelical Lutheran Church of Finland and the Russian Orthodox Church / editor: Matti Kotiranta ; redactorial staff: Tomi Karttunen, Kaisamari Hintikka, Minna Väliaho ; translated from Russian and English into English: Malcolm Hicks.

**Comment by mirmaid** [comment]
^ Eli nämä on tapauksia, joissa on lisäksi tai pelkästään ekumeniikka, kun pitäisi olla ekumenia. 

Lisätään määritelmät ja RT-suhde. Periaatteessa on mahdollista lisätä ekumeniikalle tarkenne (tieteet/tieteenalat), mutta en tiedä olisiko hyöty suuren  suuri - joissakin organisaatioissa joka tapauksessa käytetään asiasanoja myös luokituksen tapaan, ja tätä käyttöä tarkenne ei estä. 

Edit. Tarkenteen lisääminen tuntuisi myös vähän periaatteellisesti väärältä, kun suomeksi ekumeniikka ei (ainakaan löytämieni määritelmien mukaan) tarkoita mitään muuta kuin tieteenalaa. Eli ei voi myöskään ohjata ekumeniikka (ekumenia) KÄ ekumenia, koska ekumeniikalla ei ole tällaista toista merkitystä.

**Comment by mariaforsen** [comment]
Ruotsiksi lisätään sitten tarkenteita molemmille (forskning) ja (enhetssträvande), ja toivotaan että myös suomeksi käytetään jatkossa oikein. Tulee sitten tietty näkyviä virheitä tietueissa, jos aineistossa ei käsitellä tutkimusta/tiedettä ollenkaan ja sv. asiasanana on ekumenik (forskning), mutta pitäisihän kuvailijoiden lukea määritelmät.

**Comment by YSO-kokous** [comment]
Lisätään määritelmät ja RT-suhde.
