### ISSUE TITLE
diakonissalaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10862]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

diakonissalaitokset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://www.hdl.fi/meista/historia/

**Perustelut ehdotukselle**

Usein jo tarvetta olisi ollut

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550), [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. teos:  Diakonia on kutsumustyötä / Mikko Malkavaara 978-952-493-397-1

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [diakonissalaitokset](http://finto.fi/yse/fi/page/Y510862)

**Comment by mirmaid** [comment]
Kerran Melindassa. Ovatko kaikki Suomen diakonissalaitokset kuitenkin Helsingin diakonissalaitoksen alaisia? Kantossa Helsingin, Oulun ja Pieksämäen. Ruotsiksi ja englanniksi haut tuovat lähinnä tämän suomalaisen, joten mietin miten tarpeellinen on Kanto-auktoriteettien lisäksi.

**Comment by mariaforsen** [comment]
Sv. diakonissanstalter HT diakonissaanstalter
https://fho.sls.fi/uppslagsord/5026/diakonissanstalt/
https://www.hdl.fi/sv/om-oss/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
