### ISSUE TITLE
Malaijan sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10867]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Malaijan sota](http://www.yso.fi/onto/yso/p13814)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Oikeampi termi Malaijan taistelu

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Malaijan_taistelu

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. Malayakriget > slaget om Malackahalvön HT slaget om Malaya
https://sv.wikipedia.org/wiki/Slaget_om_Malackahalv%C3%B6n

**Comment by mirmaid** [comment]
Kävi ilmi, että kyse on kahdesta eri käsitteestä Malaijan sota / Malaijan kriisi v. 1948-1960 ja taistelu v. 1941-1942. Lisätään alkuperäiseen käsitteeseen aikatarkenne ja otetaan taistelu erikseen. Mahdollista myös muuttaa sota > kriisi, mutta ilmeisesti  aiemmin on käytetty termiä Malaijan sota, joka on ihan perusteltu: _The conflict was called the "Anti–British National Liberation War" by the MNLA, but an "Emergency" by the British, as London-based insurers would not have paid out in instances of civil wars_.
Ohjaustermiksi joka tapauksessa Malaijan kriisi ja Malaijan poikkeustila.

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85080083

**Comment by mariaforsen** [comment]
Sv. Malayakrisen
https://sv.wikipedia.org/wiki/Malayakrisen
