### ISSUE TITLE
ansiomerkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10866]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ansiomerkit](http://www.yso.fi/onto/yso/p4348)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi ansiomitalit (vai onko tarkoitus käyttää muistomitalit?)

**Perustelut ehdotukselle**

käytössä oleva termi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Molemmat? _Muistomitalit_ kai yleensä nimenomaan sotiin liittyen.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Ansiomitalit KÄ ansiomerkit, ansiomitalit (muistomitalit) KÄ muistomitalit.
