### ISSUE TITLE
asiakastietojärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10874]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

asiakastietojärjestelmät

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Hei, Olen sosiaali- ja terveydenhuollon tiedonhallinnan opiskelija Itä-Suomen yliopistosta ja haluaisin tiedustella mahdollisuuksista saada käyttöön sosiaalihuollon tiedonhallintaan liittyviä termejä. YSO:lta löytyy esimerkiksi käsite potilastietojärjestelmästä, mutta ei asiakastietojärjestelmää. Asiakastietojärjestelmä käsitteen lisääminen YSO:n sanastoihin olisi tärkeää, jotta sosiaalihuollon tiedonhallinnan näkökulma saataisiin nostettua esille. Toinen käsite koskee myös asiakas- ja potilastietojärjestelmän pääkäyttäjiä, olisi hienoa mikäli YSO:an saisi käsitteen myös heihin liittyen. Pääkäyttäjät ovat kuitenkin olennainen osa sosiaali- ja terveydenhuoltoa järjestelmän ylläpito- ja taustatehtävissä. Käsitteen ehdotukset nousevat esille, koska yliopistot vaativat, että opinnäytetöissä avainsanat olisivat YSA:sta/YSO:sta löytyviä termejä. Tämä tuottaa haasteita mikäli en voi kohdistaa opinnäytetyöni avainsanoja koskemaan aihettani, vaan avainsanat tulee valita vain ympäripyöreästi liittyen esimerkiksi sosiaalihuoltoon ja tietojärjestelmiin, joka kuvaa liian laajasti opinnäytetyöni aihetta.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Opinnäyte

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [asiakastietojärjestelmät](http://finto.fi/yse/fi/page/Y510874)

**Comment by mirmaid** [comment]
Ei Melindassa.

Sanastossa on _asiakastiedot_ ja _tietojärjestelmät_ (70 kertaa samoissa viitteissä).

**Comment by mariaforsen** [comment]
Silloin kun kyseessä on sosiaalihuollon asiakastietojärjestelmä on sv. klientdatasystem https://www.valvira.fi/web/sv/halso-och-sjukvard/informationssystem-inom-social-och-halsovarden
https://www.valvira.fi/web/sv/-/social-och-halsovardens-patient-och-klientdatasystem-finns-nu-i-valviras-register
Huom. asiakas=klient kun sosiaalihuolto yms. kyseessä

**Comment by ilona-x** [comment]
Tämä varmaan tosiaan kannattaisi rajata sosiaalihuollon tietojärjestelmiin. https://www.valvira.fi/terveydenhuolto/sosiaali-ja-terveydenhuollon-tietojarjestelmat

Yritysmaailmassa asiakastiedot taitavat olla erilaisissa toiminnanohjaus- ja asiakkuuksienhallintajärjestelmissä. Mutta näköjään CRM (customer relationship management)-järjestelmiin viitataan näköjään välillä myös termillä asiakastietojärjestelmä. Ja toisaalta Apotti kertoo olevansa "sosiaali- ja terveydenhuollon tieto- ja toiminnanohjausjärjestelmä" (https://www.apotti.fi/)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _sosiaalihuollon tietojärjestelmät_.

**Comment by mariaforsen** [comment]
Sv. socialvårdens informationssystem HT socialvårdens klientdatasystem, socialvårdens datasystem
https://termipankki.fi/tepa/fi/haku/sosiaalihuolto
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9d9c608c147519c5a808b88b0416cccf&list_id=1&keyword=tietoj%C3%A4rjestelm%C3%A4&word=tietoj%C3%A4rjestelm%C3%A4
