### ISSUE TITLE
levuliinihapot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10870]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

levuliinihapot

**Ehdotettu termi ruotsiksi**

levulinsyror

**Ehdotettu termi englanniksi**

levulinic acids

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D007982), [Wikipedia](https://fi.wikipedia.org/wiki/Levuliinihappo)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Hydrotreatment of lignocellulose-derived molecules to renewable fuels and chemicals 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [levuliinihapot](http://finto.fi/yse/fi/page/Y510870)

**Comment by mariaforsen** [comment]
Sv. levulinsyror HT lävulinsyror /ne
