### ISSUE TITLE
pääkäyttäjät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10875]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pääkäyttäjät

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Hei, Olen sosiaali- ja terveydenhuollon tiedonhallinnan opiskelija Itä-Suomen yliopistosta ja haluaisin tiedustella mahdollisuuksista saada käyttöön sosiaalihuollon tiedonhallintaan liittyviä termejä. YSO:lta löytyy esimerkiksi käsite potilastietojärjestelmästä, mutta ei asiakastietojärjestelmää. Asiakastietojärjestelmä käsitteen lisääminen YSO:n sanastoihin olisi tärkeää, jotta sosiaalihuollon tiedonhallinnan näkökulma saataisiin nostettua esille. Toinen käsite koskee myös asiakas- ja potilastietojärjestelmän pääkäyttäjiä, olisi hienoa mikäli YSO:an saisi käsitteen myös heihin liittyen. Pääkäyttäjät ovat kuitenkin olennainen osa sosiaali- ja terveydenhuoltoa järjestelmän ylläpito- ja taustatehtävissä. Käsitteen ehdotukset nousevat esille, koska yliopistot vaativat, että opinnäytetöissä avainsanat olisivat YSA:sta/YSO:sta löytyviä termejä. Tämä tuottaa haasteita mikäli en voi kohdistaa opinnäytetyöni avainsanoja koskemaan aihettani, vaan avainsanat tulee valita vain ympäripyöreästi liittyen esimerkiksi sosiaalihuoltoon ja tietojärjestelmiin, joka kuvaa liian laajasti opinnäytetyöni aihetta.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Opinnäyte

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pääkäyttäjät](http://finto.fi/yse/fi/page/Y510875)

**Comment by mirmaid** [comment]
Ei Melindassa.

Kielitoimiston sanakirja: ensisijainen käyttäjä. _Seura on urheiluhallin pääkäyttäjä. Konserttisalilla on pääkäyttäjinä kaksi orkesteria._
Tietotekn. erikoisoikeuksiensa perusteella tietojärjestelmää, tietoverkkoa tms. hallinnoiva, valvova ja ylläpitävä henkilö.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Superuser

**Comment by juhoinkinen** [comment]
YSO:ssa on ["käyttäjät"-käsite](https://finto.fi/yso/fi/page/p16550), jonka alla on "loppukäyttäjät", joten myös pääkäyttäjät vois olla käyttäjien alakäsite.

Mikan ehdottamien lisäksi "ylläpitäjät" voisi olla ohjausterminä.

**Comment by mariaforsen** [comment]
Sv. huvudanvändare?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, ATK-alan merkityksessä.

**Comment by mariaforsen** [comment]
Sv. systemadministratörer HT huvudanvändare, superuser, superanvändare
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_8f73af11c6903c04a96f1836751a259b&list_id=1&keyword=p%C3%A4%C3%A4k%C3%A4ytt%C3%A4j%C3%A4&word=p%C3%A4%C3%A4k%C3%A4ytt%C3%A4j%C3%A4
https://www.wikidata.org/wiki/Q327353
https://www.sanakirja.fi/custom/en-sv-fi/systemadministrat%C3%B6r%20
https://www.sanakirja.fi/custom/fi-en-sv/p%C3%A4%C3%A4k%C3%A4ytt%C3%A4j%C3%A4
https://it-ord.idg.se/ord/administrator/
https://it-ord.idg.se/ord/superuser/
https://en.wikipedia.org/wiki/Superuser
https://www.yumpu.com/it/document/view/20410695/finsk-svensk-engelsk-dataordlista-arbis
https://gupea.ub.gu.se/handle/2077/62403 (superanvändare ett bredare begrepp)

it-ord: "superuser, superanvändare – användare som har alla behörigheter i ett fleranvändarsystem. Termen används bland annat i Linux och har då samma betydelse som rot. I Windows och macOS kallas funktionen för administratör"
