### ISSUE TITLE
atk-järjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10872]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[atk-järjestelmät](http://www.yso.fi/onto/yso/p14105)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

nykinen termi tietokonejärjestelmä

**Perustelut ehdotukselle**

https://finto.fi/mesh/fi/page/D003199

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan, voidaanko poistaa kokonaan ja korvata käsitteellä tietojärjestelmät?

**Comment by ilona-x** [comment]
LCSH:
**Computer systems** https://id.loc.gov/authorities/subjects/sh98003200.html
Variants
    ADP systems (Computer systems)
    Computing systems
    Systems, Computer

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/computer%20system

**Comment by ilona-x** [comment]
Melinda:
atk-järjestelmät x 1542
tietojärjestelmät x 12357
atk-järjestelmät & tietojärjestelmät x 770

YSOn hierarkiassa tietojärjestelmät on atk-järjestelmien yläkäsite, joten tämän perusteella korvaaminen pitäisi olla ok.

Myös Melindan viitteiden selaamisen perusteella suuressa osassa tietojärjestelmät vaikuttaisi ihan oikealta termiltä. Joissain tapauksissa vaikea pelkän viitteen perusteella tietää, käsitelläänkö julkaisussa tietojärjestelmiä vai laajemmin tietotekniikkaa (laitteistot ym.) Esim.
- Jätehuollon tietojenkäsittelyn kehittäminen https://melinda.kansalliskirjasto.fi/byid/000685232

Joitaikin viitteitä löytyy, missä tietojärjestelmät olisi ehkä virheellinen, esim.
- Laiteympäristöt nopeusvertailussa : pitääkö PC pintansa?. https://melinda.kansalliskirjasto.fi/byid/012750819

**Comment by mariaforsen** [comment]
Vaikuttaa siltä että ainakin ruotsiksi informationssystem ja datorsystem ovat osittain eri asioita, tai ainakin näkökulma on vahvasti eri (laitteisto vs. sisältö)
NE: 
informationssystem= system som behandlar, det vill säga insamlar, bearbetar, lagrar och distribuerar information
datorsystem=dator(er) med ansluten maskinvara
https://www.rikstermbanken.se/search?q=informationssystem&s=termer
https://sv.wikipedia.org/wiki/Datorsystem
https://sv.wikipedia.org/wiki/Informationssystem

**Comment by mirmaid** [comment]
https://termipankki.fi/tepa/fi/haku/tietokonej%C3%A4rjestelm%C3%A4

**Comment by miguelvaara** [comment]
Ehkä minun pitää tietojärjestelmätieteilijänä kommentoida:

Tietojärjestelmät eivät rajaudu pelkästään laitteisiin tai ohjelmistoihin, vaan niiden osana nähdään myös ihminen. Sen takia ATK:n eli automaattisen tietojenkäsittelyn korvaaminen tietojärjestelmät-käsitteellä on ongelmallista, koska ATK:hon taas ei samalla tapaa liitetä ihmisen kontribuutiota.

**Comment by juhoinkinen** [comment]
Vahva mutu on, että on parempi vaihtaa preflabel atk-järjestelmät -> tietokonejärjestelmät kuin korvata atk-järjestelmät -käsite tietojärjestelmät-käsitteellä.

(Voisi myös harkita siirtää [kirjastojärjestelmät](https://finto.fi/yso/fi/page/p21516)-käsite suoraan tietojärjestelmät-käsitteen alle; nyt se on atk-järjestelmien alla. Esim. vanhat pahviset lainauskorttisysteemit varmaan olivat jonkinlaisia kirjastojärjestelmiä ja tietojärjestelmiä, mutta eivät atk-järjestelmiä.)

**Comment by mirmaid** [comment]
Oma mutu on, että kirjastojärjestelmä-sana on vahvasti sidoksissa tietotekniikan tuloon kirjastoihin, mutta pakko myöntää, että oma mutu ei ihan yllä tätä edeltävälle ajalle...mun korvaani sitten taas kaikki tietojärjestelmät voisivat hyvin olla jollain lailla IT:n kanssa tekemisissä.

**Comment by mirmaid** [comment]
Eli ehdotettu muutos on > tietokonejärjestelmät.
