### ISSUE TITLE
lampaanliha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10871]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lampaanliha](http://www.yso.fi/onto/yso/p14056)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi karitsanliha

**Perustelut ehdotukselle**

Melkein synonymi

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Jää termiehdotukseksi.
