### ISSUE TITLE
Firenzen tasavalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10887]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Firenzen tasavalta

**Ehdotettu termi ruotsiksi**

Republiken Florens

**Ehdotettu termi englanniksi**

Republic of Florence

**Tarkoitusta täsmentävä selite**

Vuosina 1115-1532 olemassa ollut kaupunkivaltio.

**Perustelut ehdotukselle**

Italia yhdistyi vasta v. 1861. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ptolemaios-atlasten. 

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [Firenzen tasavalta](http://finto.fi/yse/fi/page/Y510887)

**Comment by mariaforsen** [comment]
Sv. Republiken Florens HT Florentinska republiken 
jfr https://sv.wikipedia.org/wiki/Hertigd%C3%B6met_Florens
https://sv.wikipedia.org/wiki/Florens_(olika_betydelser)
