### ISSUE TITLE
eheytysterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10889]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

eheytysterapia

**Ehdotettu termi ruotsiksi**

konversionsterapi

**Ehdotettu termi englanniksi**

conversion therapy 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Eheytyksestä on puhuttu paljon julkisuudessa, ja se on jo sangen pitkään ollut tunnettu käsite. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 eheytyminen, eheytys, eheyttäminen, eheytyshoito 

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [sielunhoitoterapia](http://www.yso.fi/onto/yso/p23867), [vaihtoehtolääkintä](http://www.yso.fi/onto/yso/p391)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wiktionary.org/wiki/eheytyshoito)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/186043

**Ehdottajan organisaatio**

Åbo Akademi 
**Termiehdotus Fintossa:** [eheytysterapia](http://finto.fi/yse/fi/page/Y510889)

**Comment by mirmaid** [comment]
Eniten muodossa _eheytyshoidot_?

Ei Melindassa.

**Comment by ilona-x** [comment]
Näiden Wikipedia-artikkeleiden pohjalta en olisi innokas ottamaan tätä termiä YSOon:

https://fi.wikipedia.org/wiki/Eheytymiskurssi
https://en.wikipedia.org/wiki/Conversion_therapy
https://sv.wikipedia.org/wiki/Omv%C3%A4ndelseterapi

**Comment by mariaforsen** [comment]
Siis tämä on todella ikävä ilmiö, josta kuitenkin on paljon kirjoitettu ja puhuttu (paljon kritiikkiä). Ilmiö ei valitettavasti häviä mihinkään, on tärkeä että siitä voi löytää tietoa. 

Motissakin https://www.sanakirja.fi/custom/en-sv-fi/eheytyshoito

Esim. tässä tarvittaisiin [Uskonnon varjot : hengellinen väkivalta kristillisissä yhteisöissä / Aini Linjakumpu.](javascript:open_window("/F/QA28HILGEQBGTVNBFJY14XPGR7H9NIAQNL9Q7F6X77JQXPD77S-04604?func=service&doc_number=007021408&line_number=0021&service_type=TAG%22);) Nyt siinä on käytetty "eheyttäminen", joka on ruotsiksi täysin väärin, eikä kyllä suomeksikaan kerro mistä on oikeasti kysymys (eli nämä hyvin kyseenalaiset eheyttämishoidot/-terapiat)

Eheytyshoidot lienee tavallisin termimuoto esim. sateenkaariliikkeen sisällä. https://ranneliike.net/artikkelit/asiasana/Eheytys
https://www.psyli.fi/suomen-psykologiliiton-kanta-eheytyshoitoihin-on-ehdottoman-kielteinen/ 
https://yle.fi/a/3-12068861
https://www.rfsl.se/hbtqi-fakta/begreppsordlista/

Psykologiliiton määritelmä: "Eheytyshoidoilla (conversion therapy) tarkoitetaan seksuaali- tai sukupuoli-identiteetin muuttamiseen pyrkiviä hoitoja. Eheytyshoitojen tausta-ajatus on, että heteroseksuaalisuudesta eroava seksuaalinen suuntautuminen tai cis-sukupuolesta eroava sukupuoli-identiteetti olisivat jollakin tavoin muutettavissa1..."

Onhan tästä jo ollut kansalaisaloitekin https://www.kansalaisaloite.fi/fi/aloite/8747

**Comment by ilona-x** [comment]
Huomasin  nyt, että ehdotuksessa on laitettu vaihtoehtoiset termit -kohtaan myös **eheyttäminen**, joka löytyy jo YSOsta http://www.yso.fi/onto/yso/p9021, ja tuota termiä on näköjään käytettykin kuvailussa. esim:

https://melinda.kansalliskirjasto.fi/byid/007021408
https://melinda.kansalliskirjasto.fi/byid/013196413

**Comment by mariaforsen** [comment]
Eheyttäminen on siis nyt sv. enande, aivan väärä termi tässä asiayhteydessä. 

Eheyttäminen on monimerkityksinen termi, ks. esim. https://fi.wikipedia.org/wiki/Eheytt%C3%A4minen ja muutenkin hyvin kyseenalainen tässä asiayhteydessä (ihan kuin homoseksuaaleissa olisi jotain "rikki") 

Kannatan eheyttämisen tarkempaa määrittelyä (eikä tässä ehdotuksessa haetussa merkityksessä ollenkaan) ja tämän yllä ehdotetun termin hyväksymistä uutena käsitteenä. 

Erillinen issue tehty eheyttäminen-termin ongelmallisuudesta https://github.com/Finto-ehdotus/YSE/issues/10977

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään eheytyshoidot, ohjaustermiksi eheytysterapia.

**Comment by mariaforsen** [comment]
Sv. omvändelseterapi HT omvändelseförsök (behandlingar), konverteringsterapi, konversionsterapi

https://www.hedersfortryck.se/wp-content/uploads/Myndighetsgemensam-vagledning-vid-hedersrelaterad-brottslighet.pdf 
https://sv.wikipedia.org/wiki/Omv%C3%A4ndelseterapi
https://www.riksdagen.se/sv/dokument-lagar/dokument/motion/forbud-mot-konverteringsterapi_H9022194
https://www.qx.se/tag/omvandelseterapi/
https://www.rfsl.se/omvandelseterapi-inom-frikyrkan/
