### ISSUE TITLE
hevoskirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10883]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hevoskirjat](http://www.yso.fi/onto/yso/p13986)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan määritelmä muotoon: Käytetään lasten- ja nuortenkirjoista, jotka käsittelevät hevosia ja ratsastusta.
Hevoskirjat pois tyttökirjojen alakäsitteistä.

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

KAUNO-kokous

**Comment by mirmaid** [comment]
Huom. myös YSO

**Comment by jtuohini** [comment]
Kai tämä kattaa vain kaunokirjallisuuden, ei siis lapsille suunnattua hevosia käsittelevää tietokirjallisuutta?

**Comment by mirmaid** [comment]
Käytetään lasten- ja nuorten kaunokirjallisuudesta, joka käsittelee hevosia ja ratsastusta.

**Comment by mirmaid** [comment]
Sama YSOon.
