### ISSUE TITLE
emigranttikirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10884]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[emigranttikirjallisuus](http://www.yso.fi/onto/yso/p20922)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

emigranttikirjallisuus KÄ pakolaiskirjallisuus, siirtolaiskirjallisuus

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

KAUNO-kokous

**Comment by mirmaid** [comment]
SLM, YSO

**Comment by mirmaid** [comment]
Hyväksytty /SLM.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
