### ISSUE TITLE
sukupuolinen häirintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10885]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuolinen häirintä](http://www.yso.fi/onto/yso/p5385)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KÄ seksuaalinen häirintä

**Perustelut ehdotukselle**

Sukupuolinen häirintä on väärin ilmaistu termi seksologiassa, termi viittaa sukupuoleen, jota sillä ei välttämättä tarkoiteta. Seksuaalinen häirintä on ilmaisuna oikeampi.

KAUNO-ryhmä: kannatetaan muutosta

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjan mukaan kumpikin on oikein, ks. https://www.kielitoimistonsanakirja.fi/seksuaalinen ja https://www.kielitoimistonsanakirja.fi/sukupuolinen. Mutta eittämättä nykyään ero hahmottunee helpommin, jos viitataan suoraan seksuaalisuuteen eikä kovin siveellisesti sukupuolisuuteen.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
