### ISSUE TITLE
musiikkidokumentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10892]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

musiikkidokumentit

**Ehdotettu termi ruotsiksi**

musikdokumentärer

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-sanastoon. Yläkäsite: dokumenttielokuvat.

**Perustelut ehdotukselle**

Tarvitaan musiikkiaiheisten dokumenttielokuvien kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [saogf](http://musikdokumentärer)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/009245044

**Ehdottajan organisaatio**

Muusa-ryhmä
**Termiehdotus Fintossa:** [musiikkidokumentit](http://finto.fi/yse/fi/page/Y510892)

**Comment by MUUSA-kokous** [comment]
Hyväksytty.

**Comment by mirmaid** [comment]
LT taidedokumentit, vaiko RT?

**Comment by mirmaid** [comment]
LT taidedokumentit
