### ISSUE TITLE
Windows 2003

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10898]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Windows 2003](http://www.yso.fi/onto/yso/p14527)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi: Windows server 2003

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Windows_Server_2003

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Vaihdetaan Windows Server 2003 päätermiksi.
