### ISSUE TITLE
orkesterisäestyksellinen soitinmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10893]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

orkesterisäestyksellinen soitinmusiikki

**Ehdotettu termi ruotsiksi**

orkestermusik med soloinstrument

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-sanastoon. Yläkäsite: taidemusiikki.

**Perustelut ehdotukselle**

Tarvitaan kuvaeltassa taidemusiikkia, jota ei ole nimetty konsertoksi, mutta jonka esityskokoonpanona on orkesteri ja solistinen instrumentti.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/009581128

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [orkesterisäestyksellinen soitinmusiikki](http://finto.fi/yse/fi/page/Y510893)

**Comment by mariaforsen** [comment]
Mistäköhän ehdotettu ruotsinnos tulee? Sv. voisi olla myös instrumentalmusik med orkesterackompanjemang?

**Comment by MUUSA-kokous** [comment]
Kannatetaan muodossa "orkesterisäestyksellinen soolosoitinmusiikki". Samalla _konsertot_ voisi siirtää tämän uuden termin alakäsitteeksi.
LT _orkesterimusiikki_
ST _konsertot_
Mahdollinen määritelmä (ei ehkä välttämätön): Taidemusiikki, jonka esityskokoonpanona on orkesteri ja yksi tai useampi solistinen soitin.

**Comment by mirmaid** [comment]
Hyväksytty muodossa orkesterisäestyksellinen soolosoitinmusiikki, lisätään ehdotettu määritelmä.

**Comment by mariaforsen** [comment]
Sv. orkesterackompanjerad soloinstrumentalmusik HT soloinstrumentalmusik med orkesterackompanjemang
