### ISSUE TITLE
denialismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10894]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

denialismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

denialism

**Tarkoitusta täsmentävä selite**

"Denialismiksi on kutsuttu tilannetta, jossa väitteen mukaan henkilö [tai yritys/instituutio] kieltää asian, jonka tiedeyhteisö kykenee todistamaan mm. toistettavin ja tilastollisesti merkitsevin mittaustuloksin. Käsitteen käyttäjien mukaan denialisti kieltää tosiasiat välttääkseen epämiellyttävän totuuden.[1] Denialismissa retorisia väitteitä käyttämällä annetaan vaikutelma kiistasta asiassa, jossa ristiriitaa todellisuudessa ei ole.[2] Päämääränä on naamioitua osaksi kriittistä tiedekeskustelua." Wikipedia 

**Perustelut ehdotukselle**

Tarve käsitteelle on tullut vastaan useamman kerran ja nyt viimeksi tietokirjan yhteydessä, joka käsittelee esim. öljy-yhtiöiden ja tupakkayhtiöiden taktiikoita levittää denialismia eli kieltää toimintansa haitallisuutta ja tietoisesti kiistää tiedettä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 kieltäminen

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [propaganda](http://www.yso.fi/onto/yso/p5617), [disinformaatio](http://www.yso.fi/onto/yso/p29444)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2017004461), [Wikipedia](https://fi.wikipedia.org/wiki/Denialismi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Jennifer Jacquet: The playbook : how to deny science, sell lies, and make a killing in the corporate world.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [denialismi](http://finto.fi/yse/fi/page/Y510894)

**Comment by mirmaid** [comment]
Käsitelty aiemmin täällä: https://github.com/Finto-ehdotus/YSE/issues/9703

**Comment by mirmaid** [comment]
Sanastossa on _tiedevastaisuus_. Yksi mahdollisuus voisi olla ohjaus denialismi (tiedevastaisuus) KÄ tiedevastaisuus?

**Comment by mariaforsen** [comment]
Sv. negationism? https://www.psykologiguiden.se/psykologilexikon/?Lookup=f%C3%B6rnekande : "Negationism (eng: denialism, negationism): Avsiktligt och systematiskt förnekande av vetenskapliga fakta, till exempel om människans inflytande på klimatet, eller av historiska fakta, till exempel om förintelsen i nazisternas koncentrationsläger." 
Ks. myös https://en.wikipedia.org/wiki/Historical_negationism

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ehdotus denialismi (tiedevastaisuus) KÄ tiedevastaisuus.
