### ISSUE TITLE
kokoonpano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10897]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kokoonpano](http://www.yso.fi/onto/yso/p14500)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettavaksi (tarkenne, huomautus tai ryhmän muutos)?

**Perustelut ehdotukselle**

Termi on monimerkityksinen: https://www.kielitoimistonsanakirja.fi/#/kokoonpano?searchMode=all Ruotsinnos on myös epäselvä https://svenska.se/tre/?sok=sammans%C3%A4ttning&pz=1 eli tarvitaan ainakin ruotsiksi jonkinlainen tarkenne tms, mutta ensin täytynee selkeyttää suomeksi, Melindassa suurin osa ensimmäisen merkityksen mukainen, mutta jonkin verran myös kakkosmerkityksessä, esim. "Määräaikaisten tuomareiden nimittäminen ja eräiden tuomioistuinten johtamisjärjestelmän kehittäminen." ; "LinkBoard Diversity: Does it Exist and does it Matter? / Jaana Auvinen.", "Pienet ja hankalat : Vasemmistoliitto pohtii hallituksesta lähtemistä : pian niin tekee myös vihreät"

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Voisikohan päätermi olla _kokoaminen_? KT kokoonpano. Tosin sekin voi suomeksi sopia aika laajasti.

**Comment by mariaforsen** [comment]
Taitaa olla hankala edelleen monikielisyyden kannalta..
https://www.sanakirja.fi/custom/en-sv-fi/kokoaminen
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_8b769ccdc10842b3c24ecba23325fa40&list_id=1&keyword=koota&word=koota

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksyttiin _kokoonpano (valmistus)_, ohjaustermiksi _kokoonpano (tuotanto)_ ja _kokoonpano (rakentaminen)_. Tarkastellaan korjauksen jälkeen tarvitseeko myös teoksen koostaminen osista ottaa huomioon.

**Comment by mariaforsen** [comment]
Sv. sammansättning (tillverkning) HT hopsättning (tillverkning), montering (tillverkning)
https://svenska.se/tre/?sok=sammans%C3%A4ttning&pz=1

**Comment by ilona-x** [comment]
Korjattu ne viitteet, mihin sopi kokoonpano (valmistus). Jäljelle jäi 119 viitettä.

- Joukossa paljon viitteitä esimerkiksi valtioiden/yhteisöjen hallitusten & tuomioistuinten/lautakuntien kokoonpanosta.

- Jonkin verran viitteitä Kalevalan & tesaurusten kokoamisesta.

- Viitteitä, mihin sopisi suomeksi [koostumus](http://www.yso.fi/onto/yso/p11294). Pitäisikö mahdollisesti ruotsiksi olla jokin sammansättning -alkuinen ohjaus koostumukseen, esimerkiksi tässä kokoonpano tullut varmaankin ruotsinkielisen kuvailun kautta tietueeseen https://melinda.kansalliskirjasto.fi/byid/012346168

**Comment by krinay** [comment]
Voisiko olla ohjaustermi _kokoonpano (teokset)_ KÄ _rakenne (ominaisuudet)_ - jos siis tuota rakenne-termiä voi käyttää tässä merkityksessä. Voiko? Rakenne (ominaisuudet) on vain ryhmässä 00 Yleistermit. Sillä on paljon alakäsitteitä, mutta ei yhtään kirjallisuuteen viittaavaa.

**Comment by mariaforsen** [comment]
Alustavasti lisätty sv. sammansättning (fysiska egenskaper) ANV uppbyggnad (fi. koostumus), sekä lisätty ongelmalistalle (päätermin muutos mahdollinen).

**Comment by mirmaid** [comment]
Nuo Kalevalat on kyllä vähän hankalia - oikea termi olisi varmaan editointi, mutta tuntuu sopivan vähän huonosti.

Riittäisiköhän yritysten ja kuntien hallitusten yhteydessä _jäsenistö_? Valtion tasolla ei enää oikein sovi...

**Comment by mariaforsen** [comment]
Koostumus nyt muutettu ruotsiksi > sammansättning (fysiska egenskaper)
Silloin kun kyseessä on kokoonpano esim. kirjallisten teosten yhteydessä se olisi ruotsiksi varmaan lähinnä sammanställning tms. Silloin kun kyseessä tuomioistuimet tms. näyttää olevan "sammansättning" käytössä (siihen sopivaa termiä ei nyt ole)

**Comment by mirmaid** [comment]
Tarvitaanko tämän tyyppisissä kokoonpano-sanaa kertomaan, että aineisto käsittelee tietyn ryhmän "rakennetta" iän, sukupuolen, etnisen taustan tai valtion hallituksen osalta hallituspuolueiden suhteen:

https://melinda.kansalliskirjasto.fi/byid/005761833
https://melinda.kansalliskirjasto.fi/byid/013853076

Muuten mahdollinen voisi olla esim. kokoonpano (jäsenet/jäsenrakenne), mutta valtion tapauksessa sekään ei toimi.

**Comment by fantsby-m** [comment]
> Tarvitaanko tämän tyyppisissä kokoonpano-sanaa kertomaan, että aineisto käsittelee tietyn ryhmän "rakennetta" iän, sukupuolen, etnisen taustan tai valtion hallituksen osalta hallituspuolueiden suhteen:
> 
> https://melinda.kansalliskirjasto.fi/byid/005761833 https://melinda.kansalliskirjasto.fi/byid/013853076
> 
> Muuten mahdollinen voisi olla esim. kokoonpano (jäsenet/jäsenrakenne), mutta valtion tapauksessa sekään ei toimi.

kokoonpano (toimielimet)

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Otetaan sanastoon käsite: kokoonpano (toimielimet)

**Comment by tpalonen** [comment]
Ehkä sivuseikka mutta: jäin pohtimaan tuota terimmuotoa vielä tuossa. Eli onko termin pakko olla yksikössä? Yksikköhän viittaa tässä tesaurusstandardien mukaan, ainakin omassa luennassani, enemmän toimintaan, (vrt. edellä mainittu Kalevalan yms kokoonpano) eli siihen hetkeen ja toimintaan kun hallitusta tms aktiivisesti muodostetaan. Monikossa taas viittaisi enemmänkin, omassa luennassani, kaikkien niitten henkilöiden joukkoon, jotka kulloinkin jonkin hallituksen tms muodostavat. Eli käytettävä termi voisi minusta olla myös muotoa kokoonpanot (toimielimet).

**Comment by mirmaid** [comment]
^ Toisaalta on tässä käytössä vahvasti sukua sellaisille käsitteille kuin ikärakenne, sukupuolirakenne.

**Comment by mariaforsen** [comment]
Sv. sammansättning (administrativa organ) 
https://termipankki.fi/tepa/fi/haku/toimielin
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_869bbb704806a1af30910564eac60bf5&list_id=1&keyword=toimielin&word=toimielin
https://www.sanakirja.fi/custom/en-sv-fi/toimielin
https://finto.fi/yso/fi/page/p4052

**Comment by mirmaid** [comment]
Jäljellä 24 viitettä, eniten Kalevalan ja tesaurusten kokoonpanosta. Ainakaan tesaurusten osalta en tiedä onko mikään tällainen "valmistus"-termi välttämätön.

**Comment by krinay** [comment]
Onko YSOn termi _toimitustyö_ tarkoitettu käytettäväksi vain journalismin aihealueella vai voisiko sitä käyttää Kalevalan ja tesaurusten kokoonpanosta? Toimitustyö kuuluu nyt vain ryhmään 80 (Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta), mutta voisiko lisätä ainakin ryhmän 87 (Kirjallisuus)? Jos tällaiseen ratkaisuun päädyttäisiin, voisiko _toimitustyölle_ lisätä ohjaustermiksi _kokoonpanon_ sopivalla tarkenteella?

**Comment by mariaforsen** [comment]
ALLFOn redaktionsarbete sopii kyllä tähän samalla tavalla kuin suomeksi.

**Comment by mirmaid** [comment]
Tesauruksia koskevissa aineistoissa onkin jo termi sanastotyö, mikä varmaan on ihan riittävä. Kalevala-aineistoissa toimitustyö kuulostaa ihan hyvältä (jossakin olikin jo), ja osasta näyttää puuttuvan perinteenkeruu, minkä voisi samalla lisätä.

**Comment by ilona-x** [comment]
Tästä ei taida enää puuttua kuin YSO-kokouksen "hyväksymisleima"?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi

kokoonpano (toimitustyö) KÄYTÄ toimitustyö
Lisätään toimitustyölle ryhmät 80 ja 87.
