### ISSUE TITLE
viherhämähäkki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10896]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

viherhämähäkki

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

laji 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 https://fi.wikipedia.org/wiki/Viherh%C3%A4m%C3%A4h%C3%A4kki

**Alakäsitteet (RT)**

 [hämähäkit](http://www.yso.fi/onto/yso/p2595)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikipedia](https://fi.wikipedia.org/wiki/Viherh%C3%A4m%C3%A4h%C3%A4kki)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Hämähäkit -kirja

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [viherhämähäkki](http://finto.fi/yse/fi/page/Y510896)

**Comment by mariaforsen** [comment]
Sv. grön bladspindel
