### ISSUE TITLE
purjelaudat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10899]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[purjelaudat](http://www.yso.fi/onto/yso/p14654)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi ohjaustermi: surffilaudat

**Perustelut ehdotukselle**

synonyminen termi

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**surffilauta** https://www.kielitoimistonsanakirja.fi/#/surffilauta?searchMode=all

1. purjelauta.
2. lainelauta. 

**lainelauta** https://www.kielitoimistonsanakirja.fi/#/lainelauta?searchMode=all
sukkulamainen, purjeeton lauta, jonka päällä seisten liu’utaan ranta-aalloilla, surffilauta, surfilauta. 

**purjelauta** https://www.kielitoimistonsanakirja.fi/#/purjelauta?searchMode=all
pitkänomainen levy, jonka yläpintaan niveltyy kallisteltava masto purjeineen ja puomeineen ja jolla purjehditaan sen päällä seisten ja käsillä puomiin tukeutuen, surffilauta, surfilauta.

**Comment by ilona-x** [comment]
lainelaudat ei YSOssa, mutta MAOsta löytyy http://www.yso.fi/onto/mao/p1565

**Comment by mariaforsen** [comment]
lainelauta+surffilauta=surfbräde

**Comment by mirmaid** [comment]
Sanastossa on muuten _surffaus KÄ lainelautailu, purjelautailu_. _Lainelaudat_ käytetty 2 kertaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _lainelaudat_, lisätään surffilaudat ohjaustermiksi kahdelle käsitteelle.

**Comment by mariaforsen** [comment]
Sv. surfbrädor HT surfingbrädor
https://svenska.se/tre/?sok=surfingbr%C3%A4da&pz=1
https://sv.wikipedia.org/wiki/Surfingbr%C3%A4da
