### ISSUE TITLE
työpajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10900]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[työpajat](http://www.yso.fi/onto/yso/p19245)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaettavaksi?

**Perustelut ehdotukselle**

Kaksimerkityksinen termi: https://www.kielitoimistonsanakirja.fi/#/ty%C3%B6paja?searchMode=all Ruotsinkielinen vastine viittaa nyt vain ykkösmerkitykseen. Mielestäni nämä ovat aivan eri asioita, ja ainakin ruotsiksi tarvitaan kaksi eri termiä: workshop, verkstad https://svenska.se/tre/?sok=verkstad&pz=1 https://svenska.se/tre/?sok=workshop&pz=1

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Paljon käytetty, veikkaan että eniten erilaisista workshopeista. 

Uudemmassa aineistossa lähes yksinomaan workshopeista jonkin asian ympärillä tai nuorten työpajatoiminnasta. Vanhimmassa aineistossa myös verstaista, mutta kyllä workshop-tyyppinen käyttö on sielläkin mukana. Nuorten työpajatoiminta on myös mukana jo vanhimmassa aineistossa, ja se on kyllä aika lailla näiden kahden rajalla...https://www.intory.fi/tyopajatoiminta/

**Comment by mariaforsen** [comment]
Molemmat sanat/merkitykset ovat ainakin ruotsiksi tärkeitä ja Melindassa on aineistoa molemmista, joten toiveena on että molemmille olisi termi. 

Verkstäder esim: 
Verkstäder : tryckeri, bilservice, konstsmide, tapetserare, fiskebetestillverkare, skomakeri, möbelkonservator, korgmakare, blyfönsterspecialst, konstgjuteri, dekorateljé / Cilla Ramnek : fotografi: Patric Johansson.

Rakenna täydellinen verstas / [päätoimittaja: Rune Michaelsen] ; [toimitus: Klaus Krabbe] ; [kääntäjä: Arne Wesenberg] ; [tekstisisältö: Allan Numelin... ja muita] ; [valokuvat: Flemming Rasmussen ... ja muita]

Working with wood : a Nordic perspective on cabinetmaking = näkökulma pohjoiseen puusepäntyöhön / Päivi Häikiö, Päivi Karvinen, Matilda Kivelä, Marja Salmela ; translation from Finnish = käännös suomesta: Verbum Kielipalvelut Oy / August Translations.

Würthiläisiä tarinoita : legendaarista palvelua, legendaarisia tosielämän tapauksia / [teksti ja toimitustyö: Marko Kulmala ja Maria Sjövik].

Textile-making in central Tyrrhenian Italy from the final Bronze Age to the Republican Period / Sanna Lipkin.

**Työpajatoiminnasta** on kyllä niin paljon aineistoa (ja sen merkitys on aika spesifi) että kannatan sitä erillisenä terminä. 
**https://www.intory.fi/tyopajatoiminta/mita-on-tyopajatoiminta/**
https://okm.fi/tyopajat-ja-etsiva-nuorisotyo
https://avi.fi/tietoa-meista/tehtavamme/opetus-ja-kulttuuri/nuorisotoimi/nuorten-tyopajatoiminta
Nuorten työpajatoiminnasta on näköjään jo tehty ehdotus **https://github.com/Finto-ehdotus/YSE/issues/3684**

Haku työpajat-termillä ei mielestäni nyt palvele käyttäjää kovin hyvin, koska tulee aineistoa toisaalta kokous-tyyppisistä workshopeista, sitten toisaalta nuorten työpajatoiminnasta (joka liittyy työnhakuun yms.) ja myös jonkin verran ihan fyysisistä työpajoista missä työstetään jotain materiaalia jne.

**Comment by jarmosaarikko** [comment]
LCSH vastineet
- [Workshops](http://id.loc.gov/authorities/subjects/sh85148187) vastaa tällä hetkellä 1. merkitystä
- [Forums (Discussion and debate)](http://id.loc.gov/authorities/subjects/sh85051014)  vastannee jälkimmäistä

Wikidatassa
- [työpaja](http://www.wikidata.org/entity/Q656720) vastaa verstasta ja on linkattu YSOn käsitteeseen
- [workshop](https://www.wikidata.org/wiki/Special:SpecialPages) (ei suomenkielistä termiä) vastannee jälkimmäistä
- https://fi.wikipedia.org/wiki/Ty%C3%B6paja - erottelee kolme merkistystä. Kolmas on [erityistyöllistämisen](https://fi.wikipedia.org/wiki/Erityisty%C3%B6llist%C3%A4minen) muoto. Sille ei ehkä ole wikidata-vastinetta.

Tässä olisi siis selvästi kolme eri käsitettä.  Ehdotuksia:
-  **verstaat** KT työpajat (ehdotan päätermin vaihtoa)
- **työpajat (kokoukset)** , workshops (meetings)
  YK kokoukset
  RT neuvottelut,   
- **työpajat (työtoiminta)**  
  YK työtoiminta

**Comment by mirmaid** [comment]
Tai olisiko vaan
- verstaat
- workshopit
- työpajatoiminta

**Comment by ilona-x** [comment]
Huomasin, että verstaat ohjaa YSOssa myös termiin konepajat.

Lisäksi  YSOssa on myös näiden työpajojen ja konepajojen yläkäsite [pajat (sepät) ](http://www.yso.fi/onto/yso/p16295), joka mielestäni kuulostaa osittain päällekäiseltä mahdollisen verstaat -termin kanssa. Pajat on saanut tarkenteen (sepät) viime kokouksessa: https://github.com/Finto-ehdotus/YSE/issues/10901

Ja jotta ei menisi liian helpoksi, niin YSOssa on myös termi takomot ja tämä taas kuulostaa päällekäiseltä pajat (sepät) termin kanssa. Esim. [takomot ](http://www.yso.fi/onto/yso/p16296)on linkattu LCSH-termiin [forge shops](http://id.loc.gov/authorities/subjects/sh85050752), mikä puolestaan on linkattu Wikidatassa termiin [smithy ](https://www.wikidata.org/wiki/Q40558), mikä näyttää olevan suomeksi paja.

Ehdotus:
voisiko verstaat ohjata KÄYTÄ pajat (sepät) / takomot / konepajat? Tai mahdollisesti jos nyt otettaisiin vain nuo workshopit ja työpajatoiminta, ja työpajat -korjauksen yhteydessä/jälkeen katsottaisiin, onko tarve vielä jollekin verstaille vai pärjättäisiinkö YSOsta löytyvillä termeillä? 

----

Kielitoimiston sanakirja:
**takomo** https://www.kielitoimistonsanakirja.fi/#/takomo?searchMode=all
verstas jossa tehdään takomalla metalliesineitä.


**verstas** https://www.kielitoimistonsanakirja.fi/#/verstas?searchMode=all
työ-, korjauspaja.
Puusepän, suutarin, verhoilijan verstas myös →←.
Huonekaluverstas.


**konepaja** https://www.kielitoimistonsanakirja.fi/#/konepaja?searchMode=all
koneita ja koneenosia tms. valmistava ja korjaava teollisuuslaitos. 


**paja** https://www.kielitoimistonsanakirja.fi/#/paja?searchMode=all
1) sepän verstas.
2) vars. yhdyssanojen jälkiosana: työhuone, (käsityö- t. pienteollisuus)verstas, teollinen yritys.
Työpaja.
Keramiikka-, korupaja.
Proteesipaja.
Konepaja.
Videopaja.
Nyrkkipaja.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _työpajatoiminta_ ja _workshopit_, korjataan viitteet. Tutkitaan jäljellä olevien perusteella tarvitaanko kolmatta termiä. Tarkistetaan _pajat (sepät)_ ja _takomot_ -termien käyttö ja voidaanko ne yhdistää.

**Comment by mirmaid** [comment]
Tutkitaan siis vielä takomot / pajat (sepät) ja konepajat - mihin kaikkiin verstaat ohjaisi?

**Comment by mariaforsen** [comment]
Sv. -verkstadsverksamhet https://finto.fi/jupo/fi/page/p1544?clang=sv https://www.intory.fi/kort-pa-svenska/ https://okm.fi/sv/-/ansokan-om-ratt-till-statsunderstod-verkstadsverksamhet-for-unga-1
-workshoppar HT workshopar https://svenska.se/tre/?sok=workshop&pz=1
https://frageladan.isof.se/visasvar.py?svar=25840
https://www.sprakbruk.fi/-/workshoppar

**Comment by mirmaid** [comment]
Usein takomot olisi korvattavissa > pajat (sepät) (toisinpäin ei). Silloin kun puhutaan isommista teollisen mittakaavan takomoyrityksistä, joissa tuotteet valmistetaan muoteilla, pajat (sepät) ei kuitenkaan oikein sovi. Taidetakomojen osalta käsitteet ovat pitkälti päällekkäiset.

**Comment by mirmaid** [comment]
Voisi olla ainakin
verstaat (sepät) KÄ pajat (sepät)
verstaat (konepajat) KÄ konepajat

_Tuotantorakennukset_-käsitteen alakäsitteiden sijoitusta hierarkiassa voisi vielä miettiä. _Tuotantolaitokset_ voisi olla ainakin osalle parempi, esim. takomojen osalta kyse tuskin on niinkään rakennuksesta kuin yrityksestä. 

_Työpajat_ voisi mielestäni poistaa, viitteitä on joka tapauksessa niin paljon että korjaus tuskin tulee tehdyksi kokousten välissä. Jos jää jokin viitejoukko korjaamatta ja sille tarvitaan uusi termi, käsitellään sitten uutena ehdotuksena?

**Comment by mariaforsen** [comment]
Melindassa ei kieltämättä ole kovin paljoa aineistoa työpajoista merkityksessä "(käsityö- t. pienteollisuus)verstas, paja (2); työhuone". Esim. 
Verkstäder : tryckeri, bilservice, konstsmide, tapetserare, fiskebetestillverkare, skomakeri, möbelkonservator, korgmakare, blyfönsterspecialst, konstgjuteri, dekorateljé / Cilla Ramnek : fotografi: Patric Johansson 
Mulle Mecks verktyg / George Johansson, Jens Ahlbom 
Rautakourien tarina : Lappeenrannan konepajan historia / Into Pitkänen ; toimittanut Pertti Kolari 
Den perfekta verkstan  / [chefredaktör: Rune Michaelsen]
Rakenna täydellinen verstas / [päätoimittaja: Rune Michaelsen] 
Würthiläisiä tarinoita : legendaarista palvelua, legendaarisia tosielämän tapauksia / [teksti ja toimitustyö: Marko Kulmala ja Maria Sjövik]
Sisusta verstas hyvin toimivaksi.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään ohjaustermit: verstaat (sepät) KÄYTÄ pajat (sepät) ja verstaat (konepajat) KÄYTÄ konepajat
Poistetaan sanasosta työpajat-käsite.
Pohditaan hierarkiaa, quoting mirmaid: _"Tuotantorakennukset-käsitteen alakäsitteiden sijoitusta hierarkiassa voisi vielä miettiä. Tuotantolaitokset voisi olla ainakin osalle parempi, esim. takomojen osalta kyse tuskin on niinkään rakennuksesta kuin yrityksestä."_

Säilytetään takomot sanastossa.
