### ISSUE TITLE
linopiirros

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10909]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[linopiirros](http://www.yso.fi/onto/yso/p11700)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermi: linopainanta

**Perustelut ehdotukselle**

Onko synonyminen? Todettu Wikidatalinkityskokouksessa.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Myös _linoleikkaus_. Eikö nämä ole sama asia, vai osaako joku sanoa, että on jokin ero?
