### ISSUE TITLE
pajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10901]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pajat](http://www.yso.fi/onto/yso/p16295)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettavaksi tai mahdollisesti jaettavaksi?

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/PAJA?searchMode=all
Ruotsinkielinen termi viittaa ykkösmerkitykseen, eli sepän verstaaseen. Huom. sanastossa myös työpajat=verkstäder, siitä myös ehdotus. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Käytetty Melindassa monenlaisista, esim. erilaiset konepajat. Jos pitää rajata ihan tiukasti, niin olisiko sitten _pajat (sepät)_ tai _pajat (taonta)_?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _pajat (sepät)_.
