### ISSUE TITLE
sekvenssit (hymnit) [YSO + SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10904]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sekvenssit (hymnit) [YSO + SLM]

**Ehdotettu termi ruotsiksi**

sekvenser (hymner)

**Ehdotettu termi englanniksi**

Sequences

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [gregoriaaninen laulu](http://www.yso.fi/onto/yso/p6553), [hymnit](http://www.yso.fi/onto/yso/p16052)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85120146), [LCGFT](http://id.loc.gov/authorities/genreForms/gf2014027082), [Wikidata](https://www.wikidata.org/wiki/Q1147354)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018119101, https://melinda.kansalliskirjasto.fi/byid/008458702 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [sekvenssit (hymnit) [YSO + SLM]](http://finto.fi/yse/fi/page/Y510904)

**Comment by mariaforsen** [comment]
SAOssa https://id.kb.se/find?q=sekvenser
Nationalencyklopedin: "inom den religiösa musiken en medeltida liturgisk sånggenre med poetiska texter som sjöngs omedelbart före evangeliet i mässan vid vissa kyrkliga högtider"

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

SLM: LT gregoriaaninen laulu, hymnit

YSO: LT hymnit

Voisiko ehdottaja laatia määritelmän?

**Comment by mirmaid** [comment]
Hyväksytty/SLM

**Comment by jtuohini** [comment]
Alleluia-sävelmän edellä tai jälkeen laulettava latinankielinen ehtoollishymni. Tunnetuimmat näistä noin vuosina 850–1150 muotoutuneista ovat _Dies irae_, _Lauda Sion_, _Veni Sancte Spiritus_ ja _Victimae paschali laudes_.

**Comment by mirmaid** [comment]
^ laitoin _muotoutuneista hymneistä_

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
