### ISSUE TITLE
responsoriot [YSO + SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10903]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

responsoriot [YSO + SLM]

**Ehdotettu termi ruotsiksi**

responsorier

**Ehdotettu termi englanniksi**

responsories

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85113234), [LCGFT](http://ttp://id.loc.gov/authorities/genreForms/gf2014027049), [Wikidata](https://www.wikidata.org/wiki/Q604748)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018119101, https://melinda.kansalliskirjasto.fi/byid/017397180 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [responsoriot [YSO + SLM]](http://finto.fi/yse/fi/page/Y510903)

**Comment by jtuohini** [comment]
Kuuluu temaattisiin ryhmiin _53 Uskonto. Teologia. Uskontotiede_ ja _89 Musiikki_. LT-suhteeksi ainakin _liturginen musiikki_.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta. Voisiko ehdottaja laatia vielä määritelmän?
LT _liturginen musiikki_

**Comment by mariaforsen** [comment]
Sv. https://id.kb.se/term/saogf/Responsorier
"växel­sång mellan präst och församling" /https://svenska.se/tre/?sok=responsorium&pz=1
https://fi.wikipedia.org/wiki/Responsorio

**Comment by mirmaid** [comment]
Hyväksytty /SLM.

**Comment by jtuohini** [comment]
Ehdotus määritelmäksi: "Aamupalveluksessa tai vesperissä eli iltajumalanpalveluksessa esitettävä liturginen vuorolaulu."

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
