### ISSUE TITLE
metoprololi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10908]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

metoprololi

**Ehdotettu termi ruotsiksi**

metoprolol

**Ehdotettu termi englanniksi**

metoprolol

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [beetasalpaajat](http://www.yso.fi/onto/yso/p39263)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85084438.html), [FinMeSH](http://www.yso.fi/onto/mesh/D008790)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/25914

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [metoprololi](http://finto.fi/yse/fi/page/Y510908)

**Comment by mariaforsen** [comment]
Sv. metoprolol /https://mesh.kib.ki.se/term/D008790/metoprolol
