### ISSUE TITLE
negridit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10907]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[negridit](http://www.yso.fi/onto/yso/p1473)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan termin poistoa

**Perustelut ehdotukselle**

Vanhentunut termi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Nationalencyklopedin: "negrider, benämning på den ”svarta” människorasen; termen, såväl som hela den gamla klassifikationen av raser hos människan, har numera frångåtts av vetenskapen."

**Comment by mirmaid** [comment]
Samalla pitäisi varmaankin poistaa _mongolidit_ ja _europidit_.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _negridit_, _mongolidit_ ja _europidit_. Tarkastellaan käsitettä _mestitsit_.
