### ISSUE TITLE
kestävyystiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10911]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kestävyystiede

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sustainability science

**Tarkoitusta täsmentävä selite**

https://journal.fi/tt/article/view/60788/22593
https://www.helsinki.fi/fi/helsingin-yliopiston-kestavyystieteen-instituutti/tutkimus/mita-kestavyystiede "Kestävyystiede on ongelma- ja ilmiölähtöinen ja ratkaisuhakuinen tieteidenvälinen tutkimusala, joka tarkastelee ihmisen ja muun luonnon välisiä vuorovaikutussuhteita. Sen tavoitteena on kestävä luonnon ja ihmisten hyvinvointi."

**Perustelut ehdotukselle**

Tarve käyttää termiä sisällönkuvailussa. Merkitty vapaaksi termiksi

**Ehdotettu yläkäsite YSOssa (LT)**

 [tieteenalat](http://www.yso.fi/onto/yso/p352)

**Ehdotetut temaattiset ryhmät**

 [56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544), [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018196019

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [kestävyystiede](http://finto.fi/yse/fi/page/Y510911)

**Comment by mariaforsen** [comment]
Sv. hållbarhetsvetenskap HT hållbarhetsforskning
https://www.helsinki.fi/sv/om-oss/hallbarhet-och-ansvar/hallbarhetsforskning
https://www.helsinki.fi/sv/pedagogiska-fakulteten/aktuellt/nyheter-och-artiklar/pedagogiska-fakulteten-med-i-institutet-hallbarhetsvetenskap

**Comment by mirmaid** [comment]
Kaksi ehdotusta samasta: https://github.com/Finto-ehdotus/YSE/issues/10915

**Comment by mirmaid** [comment]
https://www.helsinki.fi/fi/helsingin-yliopiston-kestavyystieteen-instituutti/tutkimus/mita-kestavyystiede

**Comment by mirmaid** [comment]
Käytetty myös termiä _kestävyystutkimus_, mutta sitä on myös käytetty muissa yhteyksissä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
