### ISSUE TITLE
aminohartsit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10913]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aminohartsit

**Ehdotettu termi ruotsiksi**

aminhartser

**Ehdotettu termi englanniksi**

amino resins

**Tarkoitusta täsmentävä selite**

https://termipankki.fi/tepa/fi/haku/aminohartsi
https://termipankki.fi/tepa/fi/haku/aminomuovi-ryhm%C3%A4

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

 amino plastics, aminoplast, aminoplasts, aminoplastic resins

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH: Aminoplastics KT amino resins](http://id.loc.gov/authorities/subjects/sh85004506)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Direct capture of CO₂ from air using amine-functionalized resin https://urn.fi/URN:ISBN:978-952-335-765-5

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [aminohartsit](http://finto.fi/yse/fi/page/Y510913)

**Comment by mariaforsen** [comment]
Sv. aminohartser HT aminhartser
Mot kemi
https://www.rikstermbanken.se/termposter/3465/aminharts 
https://svenska.se/tre/?sok=harts&pz=1
