### ISSUE TITLE
kirkkotekstiilit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10918]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kirkkotekstiilit](http://www.yso.fi/onto/yso/p6840)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "paramentit"

**Perustelut ehdotukselle**

"Paramentti on kirkkotekstiili, jonka väri- ja muotokieli saa aiheensa kristillisestä symboliikasta ja kirkkovuodesta. Paramentteja ovat esimerkiksi alttarin edustan peittävä liina eli antependium, kirjaliina, kalkkiliina, korporaaliliina, alba, vyö, stola, messukasukka ja kuorikaapu." (https://evl.fi/sanasto/-/glossary/word/Paramentti)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. paramenta https://evl.fi/ordlista/-/glossary/word/Paramenta

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
