### ISSUE TITLE
digitaalinen hyvinvointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10919]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

digitaalinen hyvinvointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Digitaalista hyvinvointia ja pahoinvointia käsittelevää aineistoa on alkanut ilmestyä yhä enemmän, sekä yhteiskunnan tasolla että yksilötasolla. Tarvetta käsitteille olisi. Jompikumpi tai molemmat.

Lisätietoa esim: https://www.mll.fi/vanhemmille/tietoa-lapsiperheen-elamasta/hyvinvointia-digiajassa/vauvana-ja-taaperona-digiajassa/digitaalinen-hyvinvointi-lapsiperheessa/ 
https://stm.fi/-//10616/tutkimus-digilaitteista-on-seka-haittaa-etta-hyotya-perhesuhteille-yhdessa-vietetty-aika-on-parasta 
https://www.vaestoliitto.fi/tutkimus/perheiden-hyvinvointi/digitaalinen-hyvinvointi-perheissa/

**Ehdotettu yläkäsite YSOssa (LT)**

 [hyvinvointi](http://www.yso.fi/onto/yso/p1947)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 digitaalinen pahoinvointi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kimmo Jylhämö: Digi-askeesi : miten elää ja ajatella digitaalisella aikakaudella. Johann Hari: Stolen focus.

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [digitaalinen hyvinvointi](http://finto.fi/yse/fi/page/Y510919)

**Comment by ilona-x** [comment]
aiempi ehdotus  **digihyvinvointi** #9217

**Comment by mariaforsen** [comment]
Sv. digitalt välbefinnande HT digitalt välmående, digital välfärd, digivälmående

**Comment by mirmaid** [comment]
Suomeksi mielestäni _digihyvinvointi_ on vähemmän kömpelö, koska se ei suoraan väitä hyvinvoinnin olevan digitaalista. Jos tämä siis nyt nähdään riittävän vakiintuneena - googlaus tuo ennen kaikkea ruutuajan hallintaan (?) liittyviä äppejä, virallisemmissa (suomalaisissa) lähteissä yleensä taas laajemmin liittyen myös esim. sähköisiin palveluihin ja digitaaliseen kuiluun.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _digihyvinvointi_, ohjaustermiksi _digitaalinen hyvinvointi_.
