### ISSUE TITLE
gnut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10912]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[gnut](http://www.yso.fi/onto/yso/p15080)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

(ainakin) ohjaustermiksi gnuut 

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Gnuut

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Laji.fi:ssä _gnut_. Ohjaustermiksi?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
