### ISSUE TITLE
kestävyystiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10915]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kestävyystiede

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sustainability science

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Uusi tieteenala joka puuttuu YSO:sta. Suomessakin on alan instituutti. Kuvailen kirjaa, joka käsittelee nimenomaan kestävyystiedettä (ei pelkästään kestävyystieteen näkökulmasta).

**Ehdotettu yläkäsite YSOssa (LT)**

 [tieteenalat](http://www.yso.fi/onto/yso/p352)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Sustainability_science)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kestävyyden avaimet : kestävyystieteen keinoin ihmisen ja luonnon yhteiseloon.

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [kestävyystiede](http://finto.fi/yse/fi/page/Y510915)

**Comment by mirmaid** [comment]
https://www.helsinki.fi/fi/helsingin-yliopiston-kestavyystieteen-instituutti/tutkimus/mita-kestavyystiede

**Comment by mirmaid** [comment]
Käytetty myös termiä _kestävyystutkimus_, mutta sitä on myös käytetty muissa yhteyksissä.
