### ISSUE TITLE
kestävyysmurros

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10916]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kestävyysmurros

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sustainability transformation

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kestävyystieteessä ilmeisesti puhutaan juuri kestävyysmurroksesta, sillä ainakin tässä kestävyystieteen kirjassa läpi teoksen käytetään juuri tätä käsitettä ja se erotetaan kestävyyssiirtymästä (jota sitäkään ei ole YSO:ssa).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 kestävyyssiirtymä

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kestävä kehitys](http://www.yso.fi/onto/yso/p8470), [vihreä siirtymä](http://www.yso.fi/onto/yso/p39666)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kestävyyden avaimet : kestävyystieteen keinoin ihmisen ja luonnon yhteiseloon

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [kestävyysmurros](http://finto.fi/yse/fi/page/Y510916)

**Comment by mirmaid** [comment]
https://www.ymparisto.fi/fi-FI/Kulutus_ja_tuotanto/SYKE_Policy_Brief_On_kestavyysmurroksen_(62080)

Onkohan tämä varsinainen oma käsitteensä? Juuri otettiin vihreä siirtymä, mielestäni tässä kuvataan aika samaa asiaa ehkä vähän eri näkökulmasta.

Tällainen löytyy kyllä: https://tieteentermipankki.fi/wiki/Kest%C3%A4vyystiede:kest%C3%A4vyysmurros

**Comment by mariaforsen** [comment]
Sv. hållbarhetstransformation, hållbarhetsövergång? ..ei juuri käytetty

**Comment by ilona-x** [comment]
Voisiko tämä jäädä vielä termiehdotukseksi, tai mahdollisesti lisätä ohjaustermiksi vihreälle siirtymälle?

"Kestävyysmurrosta nimitetään myös kestävyys- tai vihreäksi siirtymäksi, mutta ympäristöpolitiikan professori Janne Hukkinen liputtaa kestävyysmurros-sanan puolesta."
Lähde: https://www.helsinki.fi/fi/uutiset/kestavyysmurros/viisi-asiaa-jotka-kestavyysmurroksesta-kannattaa-tietaa

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan ohjaustermiksi, käytä vihreä siirtymä.
