### ISSUE TITLE
ritarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10920]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ritarit](http://www.yso.fi/onto/yso/p17100)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitseeko tarkenteen?

**Perustelut ehdotukselle**

Varmistetaan, onko käytetty laajemmin. Vrt. ritarikunnat.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Kolme eri mahdollista merkitystä ruotsiksi: https://svenska.se/tre/?sok=riddare&pz=1 Joten on mahdollista että on käytetty väärin, jos kuvailija ei ole lukenut määritelmää. Melindassa näyttää aika hyvältä, muutama "asiaton" käyttö esim. Sarjakuvataiteilija Ville Rannasta ritari. Miten tällaiset "rajalla" olevat aineistot: Finlands ridderskaps och adelskalender 2001 = Suomen ritariston ja aatelin kalenteri 2001 ?

**Comment by mirmaid** [comment]
^ Onko tuo nimi vanhaa perua, vai katsotaanko osa aatelistosta edelleen kuuluvaksi "ritaristoon"? 

Melindassa käyttö on kyllä niin yhdenmukaista, että tuntuu ehkä turhalta lähteä rajaamaan - enemmän kuin nämä muutamat virheelliset käyttötapaukset, ajattelisi keskiajasta kiinnostunutta tiedonhakijaa hiertävän se, että kaikenlainen fiktio Lego-ritareista Game of Thronesiin floodaa hakutuloksia.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
