### ISSUE TITLE
luonnonvaraoikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10922]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

luonnonvaraoikeus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://tieteentermipankki.fi/wiki/Oikeustiede:luonnonvaraoikeus

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [ympäristöoikeus](http://www.yso.fi/onto/yso/p5971)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Luonnonvaraoikeus)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Näkökulmia ympäristöoikeuteen 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [luonnonvaraoikeus](http://finto.fi/yse/fi/page/Y510922)

**Comment by mariaforsen** [comment]
Sv. naturresursrätt? ..vain vähän

**Comment by fantsby-m** [comment]
https://tieteentermipankki.fi/wiki/Oikeustiede:luonnonvaraoikeus

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by ilona-x** [comment]
tähän väitökseen voi myös käyttää: Luonnonvaraoikeudelliset konfliktit ja legitimiteetti
