### ISSUE TITLE
sääntely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10927]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sääntely](http://www.yso.fi/onto/yso/p10664)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Suhde säätely-käsitteeseen selkeytettävä ja kielivastineet tarkistettava.

**Perustelut ehdotukselle**

Esim. tässä https://www.doria.fi/handle/10024/182711?locale=lfi ruots. reglering olisi suomeksi ennemmin säätely

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Hankala tapaus kun eri kielillä käytetään eri termejä eri asiayhteyksissä. Yllä mainitussa tosiaan reglering oikein ruotsiksi. 

Ruotsiksi käytetään justering tavallisimmin merkityksessä "ställa in (något) i rätt läge" eli säätää esim. jonkin laitteen toimintaa. Tosin myös muissa merkityksissä, ks. Nationalencyklopedin ja https://svenska.se/tre/?sok=justera&pz=8 

Reglering on paljon yleisempi ja laajempi merkitykseltään. Ks. svenska.se: reglera=
1 styra så att lämplig verkan upp­nås hos något; med hjälp av åter­koppling
JFR anpassa, avpassa, dimensionera, justera 1
2 ofta pass. el. perfekt particip kontrollera med hjälp av regler
JFR normera
3 ekonomiskt ut­jämna visst oavslutat ekonomiskt förhållande
Esim. yhteiskunnassa ja myös kehossa tapahtuu erityyppistä reglering.
https://sv.wikipedia.org/wiki/Reglering_(olika_betydelser)

https://termipankki.fi/tepa/fi/haku/s%C3%A4%C3%A4ntely
https://termipankki.fi/tepa/fi/haku/s%C3%A4%C3%A4tely
https://termipankki.fi/tepa/fi/haku/reglering
https://termipankki.fi/tepa/fi/haku/justering

Summa summarum: sääntely täytyy varmaan olla reglering (ellei tarkenneta suomeksi johonkin tiettyyn merkitykseen). Säätely sen sijaan voisi periaatteessa olla useita eri vaihtoehtoja, mutta tämä vaatisi miten vain että määriteltäisiin mikä merkitys/käyttöyhteys tarkaalleen tässä haetaan. Vai onko vaihtoehtona että tehtäisiin niin kuin englanniksi, eli molemmat reglering + tarkenne? Justering voi olla myös säätö, ja se on erikseen sanastossa (sv. inställning).

**Comment by mirmaid** [comment]
Sääntely vaatisi varmaan ainakin ruotsiksi tarkenteen, mun mielestäni se on edellisistä merkitys 2 (en ole ihan varma mitä 3 tarkoittaa). Eli sääntely tapahtuu sääntöjen avulla.

**Comment by mariaforsen** [comment]
Eli mahdollisesti: reglering (med bestämmelser/regler) + olisiko huomautus tarpeen, jotta varmasti myös suomeksi käytetään sitten vain säännöillä sääntelyyn? https://www.kielitoimistonsanakirja.fi/#/s%C3%A4%C3%A4nnell%C3%A4?searchMode=all
Tarkenne saattaa muutenkin olla vähän hämmentävä, joten määritelmä olisi tarpeen myös ruotsiksi. 

Ohjauksena ruotsiksi voisi myös olla reglering (justering) ANV justering ja justering (inställning) ANV inställning

**Comment by mirmaid** [comment]
Suomeksi on tosiaan tämä hassu tapa puhua riistakantojen sääntelystä. Niitä viitteitä on muutama, aineistoa näkemättä on aika vaikea sanoa onko kyse oikeasti kannan koon säätelystä, vai aiheeseen liittyvästä sääntelystä. Ainakin kalakantojen kohdalla näytti siltä, että pääasiassa kuitenkin jälkimmäisestä (kalastuksen sääntely). Tästä voisi ehkä lisätä käyttöhuomautuksen ("Riistakantojen koon säätelystä käytetään käsitettä säätely" tms.), mutta en tiedä näyttääkö se jotenkin kuriositeetilta, kun tällainen käyttö on kuitenkin todella vähäistä (myös muuten kuin Melindassa).

**Comment by mariaforsen** [comment]
Säätely on sv. justering, eli ei sovi kovin hyvin riistakantojen säätelystä, mutta parempaan vastaavuuteen ei varmaan näissä hyvin hankalissa tapauksissa päästä.. Se vaatisi siinä tapauksessa tarkempia termejä, esim. "kannan säätely".

**Comment by jarmosaarikko** [comment]
Kuten Mirja ja Maria toteavat, puhekielessä ja sitä kautta helposti teksteissä menevät juuri tuo eläinkantojen ym. säätely ja sääntely helposti sekaisin. Siksi ne olisi hyvä sanastossa tarkentaa kuvailijaa varten, sillä tekstistä suoraan poimittuna menee helposti merkitys väärin. Mitenköhän Annif pärjää tässä tunnistamisessa?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään sulkutarkenne ruotsiksi. Tarkistetaan säätelyn ja sääntelyn ryhmät.

**Comment by mariaforsen** [comment]
Sv. reglering (med bestämmelser) Sen mukaisesti sopisi ryhmiksi 69 ja 71 (nyt ryhminä säätely-termillä)
