### ISSUE TITLE
Kursk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10929]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kursk

**Ehdotettu termi ruotsiksi**

Kursk

**Ehdotettu termi englanniksi**

Kursk

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [Venäjä](http://www.yso.fi/onto/yso/p94479)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Kursk)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-82-535-4400-7

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Kursk](http://finto.fi/yse/fi/page/Y510929)

**Comment by fantsby-m** [comment]
Täsmennys termiehdotukseen: Kursk (kaupunki)
