### ISSUE TITLE
kuivatislaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10926]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuivatislaus](http://www.yso.fi/onto/yso/p11948)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko varmasti = pyrolyysi

**Perustelut ehdotukselle**

https://www.abo.fi/fi/uutiset/tohtorinvaitos-muovijatteiden-kasittelysta/

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ainakin SAOssa nämä ovat kyllä erillisiä termejä. 
Nationalencyklopedin: pyrolys="process vid vilken ett ämne upphettas utan närvaro av syre. **Industriellt används pyrolys t.ex. vid torrdestillation** av fasta bränslen i syfte att överföra dem i gasformiga produkter och vid råvaruåtervinning av plast."

Eli pyrolyysiä voidaan käyttää esim. kuivatislauksessa, mutta ehkä myös muissa asioissa, esim. Gigantin sivulla pyrolyysiuunista: "Pyrolyysi on puhdistusmenetelmä, jossa ruokajäämät, rasva ja muut liat poltetaan korkeassa lämpötilassa (400–500 astetta) tuhkaksi."

https://termipankki.fi/tepa/fi/haku/pyrolys
https://termipankki.fi/tepa/fi/haku/kuivatislaus

https://en.wikipedia.org/wiki/Dry_distillation "the heating of solid materials to produce gaseous products (which may condense into liquids or solids). **The method may involve pyrolysis or thermolysis, or it may not** "

https://en.wikipedia.org/wiki/Pyrolysis "the thermal decomposition of materials at elevated temperatures in an inert atmosphere."

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan pyrolyysi omana käsitteenään, muutetaan ohjaustermejä.

**Comment by ilona-x** [comment]
LCSH: 
Pyrolysis
http://id.loc.gov/authorities/subjects/sh85109347

**Comment by mariaforsen** [comment]
Sv. pyrolys /sao, ne
