### ISSUE TITLE
Notch-signalointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10925]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Notch-signalointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.abo.fi/fi/uutiset/tohtorinvaitos-solubiologian-alalta-3/

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Notch-signalointi](http://finto.fi/yse/fi/page/Y510925)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Notch_signaling_pathway

_Notch-signalointi on solujen viestintäjärjestelmä, joka löytyy useimmista monisoluisista eliöistä_. https://terveysportti.mobi/kotisivut/uutismaailma.duodecimapi.uutisarkisto?p_arkisto=1&p_palsta=24&p_artikkeli=uux18783

**Comment by mariaforsen** [comment]
Sv. Notch-signalering https://www.abo.fi/nyheter/doktorsavhandling-i-cellbiologi-3/
