### ISSUE TITLE
vimentiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10924]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vimentiini

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.abo.fi/fi/uutiset/tohtorinvaitos-solubiologian-alalta-3/

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [vimentiini](http://finto.fi/yse/fi/page/Y510924)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D014746

**Comment by mariaforsen** [comment]
Sv. vimentin
https://mesh.kib.ki.se/term/D014746/vimentin
