### ISSUE TITLE
ritarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10921]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ritarit](http://www.yso.fi/onto/yso/p17100)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT ritaristo

**Perustelut ehdotukselle**

Nyt kyseinen ohjaustermi viittaa vain ritarikuntiin

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. ridderskap=adels­ståndet i Sverige (och tidigare Fin­land) el. mot­svarande samhälls­grupp i andra länder
