### ISSUE TITLE
Metsävaratieto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10930]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Metsävaratieto

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Erittäin keskeinen käsite metsätaloudessa ja metsänhoidossa. Metsävaratieto on yleensä linkitettynä paikkatietoon. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [metsävarat](http://www.yso.fi/onto/yso/p15460)

**Ehdotetut temaattiset ryhmät**

 [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

 metsävara-aineisto

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Metsätieteen opinnäytetyö

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Metsävaratieto](http://finto.fi/yse/fi/page/Y510930)

**Comment by mirmaid** [comment]
9 kertaa Melindassa, kerran monikossa.

**Comment by mariaforsen** [comment]
Sv. skogsresursinformation HT skogsresursdata, skogstillgångsdata, skogsresursuppgifter https://www.luke.fi/sv/bloggar/varfor-tva-olika-metoder-for-inhamtning-av-skogsresursinformation

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Tutkitaan monikollisuutta.
