### ISSUE TITLE
kulttuurianalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10933]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kulttuurianalyysi

**Ehdotettu termi ruotsiksi**

kulturanalys

**Ehdotettu termi englanniksi**

cultural analysis

**Tarkoitusta täsmentävä selite**

Ks. esim. 
https://www.abo.fi/fi/aineet/kulttuurianalyysi/

**Perustelut ehdotukselle**

Tarvetta sisällönkuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

 kulturell analys

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/find?q=kulturanalys), [Wikipedia](https://en.wikipedia.org/wiki/Cultural_analysis)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. https://melinda.kansalliskirjasto.fi/byid/018653079  

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kulttuurianalyysi](http://finto.fi/yse/fi/page/Y510933)

**Comment by mirmaid** [comment]
11 viitettä Melindassa.

**Comment by mirmaid** [comment]
Englanninkielisessä wikipediassa: _This developed at the intersection of cultural studies, comparative literature, art history, fine art, philosophy, literary theory, theology, anthropology_.

En ihan saa kiinni (ehkä suomenkielisten lähteiden puutteessa), mikä tämän suhde on _kulttuurintutkimukseen_? Åbo Akademissa tämä näyttää olevan oppiaine:  _Kulttuurianalyysi on oppiaine, jossa tarkastellaan arjen kulttuurisia malleja ja niiden muuttumista._

_Ämnena Kulttuurien tutkimus vid Åbo universitet och Kulturanalys vid Åbo Akademi ordnar i samarbete med Åbo museicentral en kurs_...https://fokaus.wordpress.com/tag/opiskelijat/

**Comment by mirmaid** [comment]
Helsingin yliopistolta löytyy _soveltavan kulttuurianalyysin_ opintojakso.

**Comment by ilona-x** [comment]
Onkohan tämä mahdollisesti kulttuurintutkimuksen tutkimusmenetelmä? 🤔 
Turun yliopiston tarjonnasta löytyi tällainen kurssi:

KULT0007 Kulttuurien tutkimuksen metodologia, 5 op https://opas.peppi.utu.fi/fi/opintojakso/KULT0007/17692

Sisältö
Metodologiat ja tutkimusperinteet kulttuurintutkimuksessa, teorioiden ja menetelmien keskinäinen riippuvuus, laadulliset tutkimusmenetelmät, sisällönanalyysi, narratiivinen analyysi, diskurssianalyysi, **kulttuurianalyysi**, verkkoetnografia, visuaalinen analyysi, merkitysanalyysi.

**Comment by mariaforsen** [comment]
On tieteenala, ks. https://en.wikipedia.org/wiki/Cultural_analysis : "As a discipline, cultural analysis is based on using [qualitative research](https://en.wikipedia.org/wiki/Qualitative_research) methods of the arts, humanities, social sciences, in particular [ethnography](https://en.wikipedia.org/wiki/Ethnography) and [anthropology](https://en.wikipedia.org/wiki/Anthropology), to collect data on [cultural phenomena](https://en.wikipedia.org/wiki/Culture) and to interpret cultural representations and practices; in an effort to gain new knowledge or understanding through analysis of that data and cultural processes. This is particularly useful for understanding and mapping trends, influences, effects, and affects within cultures."

**Comment by mariaforsen** [comment]
Onkohan tämä vähemmän suosittu tieteenala Suomessa?

**Comment by krinay** [comment]
Ehkä tutkimussuuntaus tms.? Kulttuurianalyysia käsittelevän kirjallisuuden kirjoittajat ovat usein etnologeja tai folkloristeja, yhteys näihin aloihin näkyy myös noissa em. suomalaisten yliopistojen opintojaksoissa (ÅA ja HY). 

Kirjallisuutta (Melinda):
[Arvidsson, Alf. Kulturanalys och metakultur (2022) ](https://melinda.kansalliskirjasto.fi/byid/018653079)
[Under ytan : kulturanalyser av det bortglömda, dolda och triviala. Red. Lena Marander-Eklund & Fredrik Nilsson. (2018)](https://melinda.kansalliskirjasto.fi/byid/015293444)
[Kulturanalyse - Psychoanalyse - Sozialforschung: Positionen, Verbindungen und Perspektiven-- Elisabeth Timm, Elisabeth Katschnig-Fasch (Hg.) (2007).](https://melinda.kansalliskirjasto.fi/byid/000497815)
 ja suomenkielistä artikkeliaineistoa jne.

**Comment by mirmaid** [comment]
^ Tuli vaan vähän sellainen tunne, että se mikä ÅA:ssa oli kulttuurianalyysin oppiaine, olisi vastannut kulttuurien tutkimusta "oppiaine, jossa tarkastellaan arjen kulttuurisia malleja ja niiden muuttumista". Mutta jos ei ole näin, niin onko se sitten analyysin alakäsite (analyysi kohteen mukaan)?

**Comment by krinay** [comment]
Totta. ÅA:n sivulla sanotaan myös näin: "Kulttuurianalyysia opiskellaan kandidaattivaiheessa. Maisterin tutkintoa varten pääaineeksi voi valita pohjoismaisen etnologian tai pohjoismaisen folkloristiikan. "

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään analyysien alle, RT kansatieteeseen, folkloristiikkaan ja etnologiaan.
