### ISSUE TITLE
kuviointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10931]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuviointi](http://www.yso.fi/onto/yso/p24446)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kuviointi kuuluu lisäksi ryhmään metsätalous ja metsänhoito

**Perustelut ehdotukselle**

Kuviointi on keskeinen osa metsäsuunnittelua ja metsävaratiedon ylläpitoa. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Tämä vaatii siinä tapauksessa aivan uuden (tarkemman) termin, ks. 
https://www.metsalehti.fi/metsanomistus/metsasanasto/ (kuvio) 
https://forest.fi/fi/sanasto/kuvio-metsikkokuvio-forest-compartment/ (kuvio)
https://www.upmmetsa.fi/tietoa-ja-tapahtumia/tietoartikkelit/metsasanasto/ (kuvio)
https://www.keitelegroup.fi/puukauppa/metsasanasto/ (kuvio)

"Metsässä kuviolla tarkoitetaan toimenpidetarpeiltaan, kasvupaikaltaan ja puustoltaan yhtenäistä metsän osaa. Käytetään myös nimitystä metsikkö tai metsikkökuvio."

"Kuvio
Metsikkökuvio on kasvupaikkatyypiltään, puustoltaan ja käsittelytarpeiltaan yhtenäinen metsän osa."

"Kuvio, metsikkökuvio (forest compartment)
Kuvio on kasvupaikaltaan ja puustoltaan yhtenäinen metsän osa, toiselta nimeltään metsikkökuvio tai metsikkö. Kuvioiden koko vaihtelee, Etelä-Suomen perhemetsissä keskikoko on runsaan hehtaarin, muiden omistajien ja Pohjois-Suomen metsissä enemmän. Kuvioiden rajat merkitään metsätalouskarttoihin ja metsänhoitosuunnitelmat tehdään jokaiselle kuvuiolle erikseen."

Kuviointi on nyt sv. mönstring ja eng. patterning. Tämänmuotoista termiä (kuviointi) metsä-merkityksessä ei kuitenkaan löydy sanakirjoista, sanastoista, tepasta jne. 

TNC 96: Skogsordlista (1994)
sv       avdelning
en      compartment
de      Abteilung f
fi        hoitolohko; kuvio; osasto; metsikkökuvio
definition
avgränsat område, ägofigur på skogskarta som karakteriseras av viss enhetlighet med avseende på skogliga faktorer
anmärkning
Ofta tillåts en större variation inom en avdelning än inom ett bestånd.
Jfr [bestånd]

https://termipankki.fi/tepa/fi/haku/kuvio

**Comment by mirmaid** [comment]
Sanastossa on _metsiköt_. Onkohan tälle kuitenkaan tarvetta kuvailussa? Metsäalan termistöä on YSOssa ja aiemmin YSAssa ollut vanhastaan jo hyvin runsaasti, mutta kun kyse on kuitenkin yleissanastosta ja alalla on omat sanastonsa lisäksi, kaikkien termien lisääminen ei ehkä ole tarpeen. Ainakin olisi hyvä olla kuvailutarvetta havainnollistava esimerkki.

**Comment by mariaforsen** [comment]
YSOssa metsiköt=skogsdungar eli EI metsätalousmerkitys ruotsiksi.
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_05836ae33de7d589f0a0b7eb5a011fa0&list_id=1&keyword=metsikk%C3%B6&word=metsikk%C3%B6 
Nykyinen ruotsinnos viittaa siis ykkösmerkitykseen (pienehkö metsä): https://www.kielitoimistonsanakirja.fi/#/metsikk%C3%B6?searchMode=all

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
