### ISSUE TITLE
öljylamput

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10938]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[öljylamput](http://www.yso.fi/onto/yso/p15716)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennys monikielisyyden kannalta, minkälaisiin öljylamppuihin tällä viitataan?

**Perustelut ehdotukselle**

Valopetrolilla vai muulla öljyllä? https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1c78bd1aba8ec69fc1cef7e0d354fec7&list_id=1&keyword=%C3%B6ljylamppu&word=%C3%B6ljylamppu  Sen mukaan ruotsinnos joko oljelampor tai fotogenlampor. Vrt https://fi.wikipedia.org/wiki/%C3%96ljytuikku ja https://www.wikidata.org/wiki/Q215628 Mikä on oikea englanninkielinen vastine? Jos pidetään jonkinlaisena yleisterminä (ks. https://fi.wikipedia.org/wiki/%C3%96ljylamppu ) niin ehdotan että poistamme linkityksen tähän tarkempaan kerosiinilamppuun https://www.wikidata.org/wiki/Q215628 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Eikö olisi hyvä, jos voidaan pitää ihan laaja merkitys, vrt. esim. Melinda https://melinda.kansalliskirjasto.fi/byid/009597368.

**Comment by YSO-kokous** [comment]
**Päätös**

Säilytetään laaja merkitys. Tarkistetaan linkitys.

**Comment by mariaforsen** [comment]
Ruotsiksi laitettiin fotogenlampor ohjaustermiksi (toinen vaihtoehto olisi ollut "oljelampor och fotogenlampor".
