### ISSUE TITLE
monikulttuurisuuskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10936]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

monikulttuurisuuskasvatus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/342840

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [monikulttuurisuuskasvatus](http://finto.fi/yse/fi/page/Y510936)

**Comment by mirmaid** [comment]
Ko. väitöskirjan lisäksi 2 viitettä Melindassa. 

Voi toki yhdistää _monikulttuurisuus + kasvatus_, mutta viitteitä esim. Melindasta tulee tällä yhdistelmällä jo valtavasti, kun voivat muutenkin esiintyä samassa kontekstissa. Sanastossa tälle läheiset _tasa-arvokasvatus, kansainvälisyyskasvatus_ ja _suvaitsevaisuuskasvatus_ taas eivät tavoita ihan oikeaa aspektia asiasta. Mutta voi toki jäädä tässä vaiheessa vielä odottamaankin, kun ns. virallisempia lähdetekstejä ei juuri ole. 

Täällä sivuttu: https://erityisopettaja.fi/monikulttuurisuuskasvatus-ja-monikulttuurinen-oppilaitos

**Comment by mariaforsen** [comment]
Sv. mångkulturell pedagogik HT mångkulturell fostran, multikulturell pedagogik, multikulturell fostran

https://www.helsinki.fi/sv/nyheter/den-finlandska-skolan/enbart-valmenande-mangkulturell-pedagogik-racker-inte-att-motverka-ojamlikhet
https://studiehandboken.abo.fi/sv/kurs/6200BX84/13357?period=2020-2022
https://www.nytid.fi/2011/06/mangkulturell-pedagogik-%E2%80%93-ett-maste-i-skolan/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
