### ISSUE TITLE
Heck-reaktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10939]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Heck-reaktio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Heck reaction

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

Melinda:
Heck reaction x 3
Mizoroki-Heck reaction x 1

**Ehdotettu yläkäsite YSOssa (LT)**

 [kemialliset reaktiot](http://www.yso.fi/onto/yso/p3658)

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

 Mizoroki–Heck-reaktio, Mizoroki-Heck reaction

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2008004901), [WIkipedia](https://fi.wikipedia.org/wiki/Heck-reaktio)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mizoroki-Heck cross-coupling - Palladium based catalysts and operation modes
https://urn.fi/URN:ISBN:978-952-12-4121-5

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Heck-reaktio](http://finto.fi/yse/fi/page/Y510939)

**Comment by mirmaid** [comment]
Sanastotyössä paremmin tunnettu on _what the heck -reaktio_ (hain jo takkini).

**Comment by mariaforsen** [comment]
Sv. Heck-reaktion HT Mizoroki-Heck-reaktion, Heck-reaktionen 
https://www.uu.se/press/pressmeddelande/?id=1162&typ=pm

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
