### ISSUE TITLE
heikot sidokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10932]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

heikot sidokset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 heikot vuorovaikutukset

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.jyu.fi/fi/ajankohtaista/arkisto/2022/02/25-2-2022-fm-essi-taipale-matemaattis-luonnontieteellinen-tiedekunta-kemian-laitos-verkkovalitteinen

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [heikot sidokset](http://finto.fi/yse/fi/page/Y510932)

**Comment by mirmaid** [comment]
Vahvoja kemiallisia sidoksia ovat ionisidos, kovalenttinen sidos ja metallisidos. Sidos voi olla myös kovalenttisen ja ionisidoksen väliltä. Kovalenttisia sidoksia esiintyy epämetalliatomien välillä ja ionisidoksia epämetalli- ja metalliatomien välillä. _Lisäksi on olemassa heikkoja sidoksia, kuten van der Waalsin voima, dipoli-dipolisidos ja vetysidos._

**Comment by mirmaid** [comment]
Väitöstiedotteessa puhutaan _heikoista vuorovaikutuksista_ (väitös: weak interactions), tämä on kuitenkin kemiaa, eli kyse ei (käsittääkseni) ole _heikosta vuorovaikutuksesta_, http://www.yso.fi/onto/yso/p39549.

**Comment by mariaforsen** [comment]
Sv. svaga bindningar
https://www.solunetti.fi/se/solubiologia/valkuaisaineiden_rakenne/3/

**Comment by mirmaid** [comment]
Olisiko _heikot sidokset KT heikot vuorovaikutukset (kemia)_?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mirmaid** [comment]
Tuomas: Mietin että valittiinko tässä nyt paras mahdollinen preflabel tai pitäisikö ainakin miettiä altlabeli(e)n lisäämistä? "Molekyylien väliset sidokset" (tai vuorovaikutukset) kertoisi ehkä terminä paremmin mikä sidos(tyyppi) on kyseessä, ja "heikot sidokset" taas enemmänkin kuvailee minkälainen sidos on kyseessä, molekyylien väliset sidokset ymmärtääkseni ovat nimenomaan heikkoja sidoksia, mutta ensin mainittu termi lienee vähän kertovampi. Wikipedia: "Intermolecular forces are weak relative to intramolecular forces – the forces which hold a molecule together. For example, the covalent bond, involving sharing electron pairs between atoms, is much stronger than the forces present between neighboring molecules." 

peda.netissä oleva sanasto tarjoaa heikolle sidokselle enkun vastineeksi intermolecular force(s). https://peda.net/p/myllyviita/OrbitaaliMarvinSketch2/sanasto kuitenkin suomeksi sanatarkka vastine tälle enkun termille olisi juurikin "molekyylien välinen sidos" ja ruotsiksi intermolekylär bindning, ks. https://sv.wikipedia.org/wiki/Intermolekyl%C3%A4r_bindning
heikolle sidokselle tarkin enkkukäännös taas olisi weak bond. Tämä termi on kyllä käytössä mutta esim. LCSH:ssa on intermolecular forces, samoin enkku-Wikipediassa eikä weak bonds. Ja kuten sanoin intermolecular force/bond olisi mielestäni terminä vähän kertovampi kuin weak bonds. YSEssä/Githubissa mainitaan esimerkkinä heikosta sidoksesta dipolidipolisidos. ja edellä mainittu pedan sanasto taas sanoo että dipolidipolisidos on "molekyylien välinen heikko sidos". vrt. myös: "There are two major bond types: weak bonds between moleucles, and strong bonds between atoms."
http://chemsite.lsrhs.net/chemkinetics/strongandweakoverview.html

**Comment by mirmaid** [comment]
Mirja: 
https://jyx.jyu.fi/handle/123456789/78050# - väitöskirjassa on annettu suomeksi ei-kovalenttiset vuorovaikutukset, joka vastaa tätä https://en.wikipedia.org/wiki/Non-covalent_interaction. 

https://en.wikipedia.org/wiki/Chemical_bond: The strength of chemical bonds varies considerably; there are "strong bonds" or "primary bonds" such as covalent, ionic and metallic bonds, and "weak bonds" or "secondary bonds" such as dipole–dipole interactions, the London dispersion force, and hydrogen bonding.

Yllä mainitut heikot sidokset ovat molekyylien välisiä sidoksia, paitsi vetysidokset, jotka voivat olla myös molekyylin sisäisiä (samoin väitöskirjassa tutkitut halogeenisidokset). Ei-kovalenttiset sidokset voivat olla molekyylien välisiä tai molekyylien sisäisiä.

Heikot sidokset/vuorovakutukset vastaa muuten suunnilleen ei-kovalenttiset vuorovaikutukset -sivulla mainittuja, mutta  ionisidokset (ja metallisidokset) ovat myös vahvoja sidoksia, mutta eivät (varsinaisesti) kovalenttisia.

Summa summarum (sikäli kuin tämän oikein ymmärrän): kemiallinen sidos voi olla heikko, kovalenttinen tai molekyylien välinen, mutta nämä eivät ole vaihtoehtoja toisilleen vaan erillisiä sidosten ominaisuuksia.

Toinen vaihtoehto on, ettei oteta tätä ollenkaan, mutta lisätään heikolle vuorovaikutukselle tarkenne (hiukkasfysiikka).

**Comment by mirmaid** [comment]
Päätetty päivityspalaverissa ottaa sanastoon heikot sidokset, eng. weak bonds.
