### ISSUE TITLE
kääntymys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10944]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kääntymys](http://www.yso.fi/onto/yso/p5412)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pitäisikö ruotsiksi ohjata konversion (religion) tähän kääntymys-termiin?

**Perustelut ehdotukselle**

tuli vastaan tapaus, jossa väitöskirjan "Intermarriage, conversion, and Jewish identity in contemporary Finland" https://urn.fi/URN:ISBN:978-952-12-4038-6 kuvailussa oli käytetty termiä konversion - konvertointi, mikä suomeksi kuulostaa aika hassulta. Ruotsinkielisessä väitöstiivistelmässä käytetään termiä konvertera.

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Olisi varmaan hyvä ohjausterminä (vaikka näkökulma on hieman eri), eli konversion (religion), konvertering (religion) ANV omvändelse
https://sv.wikipedia.org/wiki/Konvertering_(religion)
