### ISSUE TITLE
diffuusio (matematiikka) tms.

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10946]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

diffuusio (matematiikka) tms.

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Diffusion_equation

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Korjatessa diffuusio-viitteitä Melindassa.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [diffuusio (matematiikka) tms.](http://finto.fi/yse/fi/page/Y510946)

**Comment by mariaforsen** [comment]
Sv. diffusion (matematik)? Mikä on tämän käsitteen määritelmä (matemaattisena)?

**Comment by mirmaid** [comment]
Jaa-a...oli mitä oli, niin sitä on melko paljon Melindassa, eikä voi käyttää _diffuusio (fysikaaliset ilmiöt)_.

**Comment by mirmaid** [comment]
Voisi varmaan olla myös diffuusioyhtälöt...

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _diffuusioyhtälöt_.

**Comment by mariaforsen** [comment]
Sv. diffusionsekvationer 
https://sv.wikipedia.org/wiki/V%C3%A4rmeledningsekvationen
https://www.aalto.fi/sites/g/files/flghsv161/files/2020-05/Svenska_Disputationsmeddelande.pdf
