### ISSUE TITLE
lainaustoiminta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10943]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lainaustoiminta](http://www.yso.fi/onto/yso/p8431)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pitäisikö tätä tarkentaa tai rajata? Nyt ryhmänä vain 81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt

**Perustelut ehdotukselle**

Käytetty muutamia kertoja myös luotoista:

Comparison of Loan Insurances https://melinda.kansalliskirjasto.fi/byid/006456456
Maa- ja metsätalousministeriön hallinnonalan korkotukityöryhmän muistio https://melinda.kansalliskirjasto.fi/byid/005347026
Hur kreditanalysen påverkar prissättningen och kraven på säkerheter i utlåning till företag https://melinda.kansalliskirjasto.fi/byid/001002576

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
luottojen yhteydessä pitäisi varmaankin käyttää luotonanto-termiä?

**Comment by ilona-x** [comment]
käytetty myös esim. taidelainaamoiden yhteydessä https://melinda.kansalliskirjasto.fi/byid/013885473
ja kaupunkipyörien yhteydessä https://melinda.kansalliskirjasto.fi/byid/013985164

**Comment by mirmaid** [comment]
Kuulostaa kyllä erikoiseltä valinnalta jos luotonannosta on kyse.

**Comment by mirmaid** [comment]
Varmaan mahdollista jokin _lainaus/lainaustoiminta (luotonanto)_ -ohjaustermikin lisätä (vaikka sekin tuntuu hiukan hassulta), jos muuten ok ruotsiksi käyttää myös esim. taidelainaamoista? Siihen se tuntuisi suomeksi sopivan ihan hyvin, kaupunkipyöristä kuulostaa jotenkin kaukaa haetulta, vaikka toimintaperiaate onkin aika samanlainen.

**Comment by ilona-x** [comment]
Tähän termiin törmäsin, kun oli käsillä jokin englanninkielinen aineisto ja tekoäly ehdotti termiä lainaustoiminta. Eli ehkä tuo sitten on ihan ok, jos suomeksi ja ruotsiksi lainaustoiminta rajautuu paremmin muuhun kuin rahan lainaamiseen kuin englanniksi lending. 🤔

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _lainaus (luotonanto)_ KÄ _luotonanto_.
