### ISSUE TITLE
kareninkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10948]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kareninkielinen kirjallisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9786167225050

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [kareninkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y510948)

**Comment by mariaforsen** [comment]
Sv. litteratur på karenska
https://finto.fi/lexvo/fi/page/?clang=sv&uri=http%3A%2F%2Flexvo.org%2Fid%2Fiso639-5%2Fkar
