### ISSUE TITLE
afrosuomalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10949]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

afrosuomalaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

afrofinns

**Tarkoitusta täsmentävä selite**

Suomalainen, joilla on sukujuuria Saharan eteläpuolisessa Afrikassa

**Perustelut ehdotukselle**

Yleistyvä käsite, joka kuvaa suhteellisen isoa vähemmistöä Suomessa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570), [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Afrosuomalaiset), [Kielitoimiston sanakirja](https://www.kielitoimistonsanakirja.fi/#/afrosuomalainen)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Search/Results?lookfor=%22afrosuomalaisuus%22&type=Subject&page=2 

**Ehdottajan organisaatio**

Helsingin kaupunginmuseo
**Termiehdotus Fintossa:** [afrosuomalaiset](http://finto.fi/yse/fi/page/Y510949)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/10172

**Comment by mirmaid** [comment]
Käsiteltiin siis edellisen kerran vuoden ensimmäisessä kokouksessa, sen jälkeen sana on otettu Kielitoimiston sanakirjaan.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Määritelmä Kielitoimiston sanakirjasta.

**Comment by mariaforsen** [comment]
Sv. afrofinländare
https://www.helsinginkaupunginmuseo.fi/sv/2022/09/01/delta-i-enkaten-helsingfors-stadsmuseum-samlar-in-afrofinlandarnas-ungdomsupplevelse/
