### ISSUE TITLE
diffuusio (yritysjärjestelyt)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10945]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

diffuusio (yritysjärjestelyt)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa paljon aineistoa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Korjatessa diffuusio-viitteitä

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [diffuusio (yritysjärjestelyt)](http://finto.fi/yse/fi/page/Y510945)

**Comment by mirmaid** [comment]
https://www.finlex.fi/fi/laki/ajantasa/2006/20060624#O5L17
Lakitekstissä suomeksi _jakautuminen_, ruots. _delning_.

https://virtuallawyer.fondia.com/fi/articles/yleisesti-jakautumisesta

Sanastossa on _jakautuminen_ (00), ruots. _fördelande_.

**Comment by mirmaid** [comment]
_Jakautuminen eli diffuusio tarkoittaa yritysjärjestelyä, jossa osakeyhtiö (jakautuva yhtiö) purkautuu selvitysmenettelyttä siten, että sen varat ja velat siirtyvät yleisseuraantona kahdelle tai useammalle osakeyhtiölle (vastaanottavat yhtiöt). Jakautuminen on siis fuusion peilikuva_. https://www.lrhto.fi/artikkelit/miksi-jakautuminen/

**Comment by mirmaid** [comment]
Taloussanasto: diffuusio: _Yritysten jakautuminen esim. toimialarationalisoinnin tai uudelleenorganisoitumisen johdosta_.

**Comment by mariaforsen** [comment]
Jakautuminen on 00-ryhmässä ja ilman minkäänlaista määritelmää, joten ruotsinnoksen kannalta ei ole mahdollista ottaa kantaa vain johonkin tiettyyn merkitykseen, ks. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_3af9f44b77f1e2ca9b3e464ce2821a5d&list_id=1&keyword=jakautua&word=jakautua Onhan se myös monimerkityksinen termi https://www.kielitoimistonsanakirja.fi/#/jakautua Se olisikin siis hyvä tarkentaa ensin. 

Diffusion ei taida olla ruotsiksi kovin hyväksytty yritysmerkityksessä? Ks. Rikstermbanken, NE jne. sekä https://www.sprakinstitutet.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/1988/frustrerande_diffusion

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _jakautuminen (yritysjärjestelyt)_, jos toimii myös Aasi-ryhmän mielestä.

**Comment by mariaforsen** [comment]
Eli termi suomeksi: diffuusio (yritysjärjestelyt)

Sv. delning av företag HT fission (företagsarrangemang), delning av bolag, delning (företagsarrangemang)
https://www.vero.fi/sv/Detaljerade_skatteanvisningar/anvisningar/49340/foretagsomstrukturering-och-beskattning--fission/
https://svenska.se/tre/?sok=fission&pz=1 
https://termipankki.fi/tepa/fi/haku/jakautuminen
https://www.rikstermbanken.se/termposter/3527/fission
https://virtuallawyer.fondia.com/fi/articles/yritysjarjestelyista-yleisesti
https://www.finlex.fi/sv/laki/ajantasa/2006/20060624
Huom. ALLFOssa myös _delning_.
