### ISSUE TITLE
tiedonsiirto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10941]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tiedonsiirto](http://www.yso.fi/onto/yso/p5429)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko sekoittunut tietämyksen siirtoon (knowledge transfer) kuvailukäytössä? Voidaanko ohjata johonkin nykyiseen käsitteeseen (tiedonsiirto (tietämyksen siirto)) tai tarvitaanko jokin uusi termi? Tarvitaanko tiedonsiirrolle tarkenne?

**Perustelut ehdotukselle**

https://trepo.tuni.fi/handle/10024/140739

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Monikielisyyden kannalta on tosiaan tärkeä että pidetään nämä eri merkitykset erillään: dataöverföring, informationsöverföring vs. kunskapsöverföring. Nyt meillä on ohjauksena kunskapsöverföring ANVÄND kompetensöverföring (osaamisen siirto). 

Tarvitaan kyllä (ainakin ruotsiksi) joko erikseen kunskapsöverföring (on myös SAOssa), eng. knowledge transfer https://en.wikipedia.org/wiki/Knowledge_transfer tai sitten kaikkien kielten kannalta sama ohjaus: tietämyksen siirto/knowledge transfer KÄYTÄ osaamisen siirto? 

(Datansiirto voisi varmaan olla ohjausterminä myös, https://www.sanakirja.fi/custom/en-sv-fi/datansiirto )

**Comment by mirmaid** [comment]
Riittääkö tiedonsiirto (tietämyksen siirto) KÄ osaamisen siirto?

**Comment by mirmaid** [comment]
https://melinda.kansalliskirjasto.fi/byid/017440127 - osaamisen siirto ei sovi (en tiedä sopiiko mikään muukaan kyllä)
https://melinda.kansalliskirjasto.fi/byid/014432346 - osaamisen siirto sopii

https://melinda.kansalliskirjasto.fi/byid/018006983 - mitä tarkoitettu?
https://melinda.kansalliskirjasto.fi/byid/017997942 - ?

**Comment by YSO-kokous** [comment]
**Päätös**

Ehdotettu _tietämyksen siirto_, käytä _osaamisen siirto_ ja _mentorointi_. _Tiedonsiirto (osaamisen siirto)_ KÄ _osaamisen siirto_.
