### ISSUE TITLE
karbidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10940]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

karbidit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/139029

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [karbidit](http://finto.fi/yse/fi/page/Y510940)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Karbidi
http://id.loc.gov/authorities/subjects/sh85020077

**Comment by mariaforsen** [comment]
Sv. karbider
