### ISSUE TITLE
taruolennot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10942]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taruolennot](http://www.yso.fi/onto/yso/p797)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi mytologiset olennot?

**Perustelut ehdotukselle**

Vastine on ruotsiksi mytologiska väsen, eli "mytologiset olennot". Sanastossa on myös satuolennot=sagoväsen, tämäkin (taruolennot) voisi olla sagoväsen mutta ratkaisuna varmaan otettu mytologiska väsen. Ks. myös eng. mythical creatures. Onko nykyinen ratkaisu ok (ja lisätään ehdotettu ohjaustermi) vai pitääkö miettiä muita ratkaisuja?

**Ehdottajan organisaatio**

ALLFO

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
