### ISSUE TITLE
langat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10953]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[langat](http://www.yso.fi/onto/yso/p15828)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ruotsinkielisen (ja englanninkielisen?) vastineen tarkistus

**Perustelut ehdotukselle**

Sv. on tähän asti ollut garn, mutta se viittaa vain paksumpiin lankoihin, joita käytetään neulomisessa yms. Jos kyseessä on ohuet ompelu- yms. langat niin termi on ruotsiksi tråd. Onko ok että sv. termi viittaa vain tietynlaiseen (paksuun) lankaan, vai pitääkö miettiä muita vaihtoehtoja, esim. langat=trådar och garn, tai mahdollisesti uuden termin ottamista: ompelulangat=sytrådar?

**Ehdottajan organisaatio**

ALLFO

**Comment by satuniininen** [comment]
Melindassa 705 kertaa, käytetty ilahduttavan yhdenmukaisesti juuri näistä paksummista langoista. Ensimmäisen 100 viitteen joukossa oli vain muutama artikkeliaineisto, johon garn ei ehkä sopisi, mutta ei välttämättä  myöskään sytrådar:

[Eläimen jalkajänteistä syntyy lankaa, liimaa ja jännejousi](https://melinda-test.kansalliskirjasto.fi/byid/013479378)
[Spinnova kehrää lankaa](https://melinda-test.kansalliskirjasto.fi/byid/013358291)

**Comment by mirmaid** [comment]
Varmaan aineistoissa näin (käsityölehdet ja -kirjat), mutta toki suomeksi _langat_ tarkoittaa ihan kaiken paksuisia lankoja.

**Comment by YSO-kokous** [comment]
**Päätös**

Aasi-ryhmä käsittelee tarvittaessa.

**Comment by mariaforsen** [comment]
Sv. garn ev. > garn och trådar? 
https://id.kb.se/term/sao/Garn
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a3b390e97c96fe53af97e16198a056a5&list_id=1&keyword=lanka&word=lanka
https://termipankki.fi/tepa/fi/haku/lanka
https://svenska.se/tre/?sok=tr%C3%A5d&pz=8
https://svenska.se/tre/?sok=garn&pz=1

**Comment by mariaforsen** [comment]
AASI-ryhmä ehdottaa uutena terminä ompelulangat=sytrådar.

**Comment by mirmaid** [comment]
^ Eli onko ajatus, että ohjataan langat (ompelulangat) KÄ _ompelulangat_, ja toivotaan, että _langat_ rajautuisi vain paksumpiin? En ole ihan varma, että tämä mitenkään aukottomasti ratkaisee potentiaalisen ongelman, kun ompelulangat-termille ei varsinaisesti kai ole ollut käyttötarvetta. Onko jotain muita lankoja kuin ompelulangat, jotka ruotsiksi eivät ole garn?

**Comment by mariaforsen** [comment]
Osittain oli varmaan tällainen ajatus myös. Jos vertaa Kielitoimiston sanakirjaan niin kaikki muut langat jotka eivät liity käsityöhön, eli "metallista tms. valmistettu tav. ohuehko säie t. säiepunos", sähköjohdot ja ansat. Mikään näistä ei ole garn.

**Comment by mirmaid** [comment]
Ansalangat tms. eivät ole myöskään ompelulankoja, eli en tiedä ratkeaisiko näin...monet näistä ovat varmaan lankoja vain yhdyssanan osana (rautalanka, puhelinlanka), mutta ei suomeksikaan käytettäisi _langat_ kuitenkaan kuvailussa. Satun löytämät esimerkkitapaukset kuitenkin on mahdollista suomeksi kuvailla langat-termillä, mutta ei ompelulangat. Eli hyväksytäänkö pieni virheellinen käyttö ruotsiksi, vai yhdistetäänkö > garn och trådar, vai tehdäänkö jotain muuta?

**Comment by jarmosaarikko** [comment]
sekavaa on:
* sv wikipediassa  **[garn (tråd)](https://sv.wikipedia.org/wiki/Tr%C3%A5d#Garn)** on ohjattu käsitteeseen **[Tråd](https://sv.wikipedia.org/wiki/Tr%C3%A5d)**
* en wikipediassa vastaava käsite  on **[yarn](https://en.wikipedia.org/wiki/Yarn)**, mutta siellä on oma sivunsa käsitteelle **[thread (yarn)](https://en.wikipedia.org/wiki/Thread_(yarn))**, jolle ei ole mappausta ruotsiksi eikä suomeksi.
* fi https://fi.wikipedia.org/wiki/Lanka
  * kts myös https://fi.wikipedia.org/wiki/Lanka_(t%C3%A4smennyssivu)

Wikdatassa:
* http://www.wikidata.org/entity/Q1391831 ompelulanka, tråd, thread  -- tämä lienee sytråd?
* http://www.wikidata.org/entity/Q49007  lanka, tråd, yarn -- tämä lienee garn?

Ja sitten nuo kaikki muut metalli- ym. langat sekä garn (rep).

**Comment by mirmaid** [comment]
Tämäntyyppisessä aineistossa onko kyseessä garn vai tråd https://melinda.kansalliskirjasto.fi/byid/017994096?

**Comment by mariaforsen** [comment]
Eikö periaattessa voi olla sekä tråd että garn? Pelkästään viitteen perusteella lienee tässä tapauksessa vaikeaa sanoa onko kyseessä ohuet esim. ompelulangat vai paksummat neulomiseen ja virkkaamiseen käytetyt (garn), vai molemmat.

**Comment by mirmaid** [comment]
^ Mun mielestäni tuossa esimerkin aineistossa siis on kyse langoista, joista koneellisesti kudotaan erilaisia kankaita. Nämä voivat olla hyvinkin ohuita, eli olisiko silloin tråd? Silkkilanka näyttäisi olevan silkestråd. Kun näitäkin aineistoja kuitenkin Melindassa on, mielestäni pitäisi olla _garn och tråd_ (tai tråd pääterminä ja garn ohjausterminä, jos se tuntuu paremmalta).

**Comment by mariaforsen** [comment]
Tråd ei varmaan voi olla pääterminä, kun suurin osa aineistoista kuitenkin käsittelevät garn:ia, mutta yhdistelmätermi joo varmaan ainoa mahdollisuus. 

Jos ohuita niin tråd, esim. silkestråd. 

Ja toivottavasti tämän asiasanan käyttö rajautuisi käsityöaineistoihin, koska jos tätä voi käyttää mihin tahansa, esim. puhelinlankoihin, ansalankoihin jne. niin sitten ei ole mahdollista saada täsmääviä termejä muilla kielillä (eikä sellainen käyttö ole järkevä myöskään tiedonhakijoiden kannalta, eikä se ole ontologinen ratkaisu.)

**Comment by mirmaid** [comment]
^ No olen aika varma että puhelinlankoihin ei käytettäisi, ansalankoihin ehkä mutta niistä voi tulla varmaan yksi aineisto kymmenessä vuodessa...

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään ohjaustermi: ansalangat KÄYTÄ ansat
Langat-käsitteelle vaihdetaan ruotsinkieliseksi käytettäväksi termiksi och-muoto.
