### ISSUE TITLE
parat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10950]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

parat

**Ehdotettu termi ruotsiksi**

bjärör

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa, kun vastaavaa tarkkaa ei ennestään

**Ehdotettu yläkäsite YSOssa (LT)**

 [yliluonnolliset olennot](http://www.yso.fi/onto/yso/p796)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532), [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 mjölkharar [swe], pukharar [swe], trollharar [swe], trollkatter [swe]

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q16426763), [Kulo](http://www.yso.fi/onto/kulo/k824)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013318242, https://melinda.kansalliskirjasto.fi/byid/015339326 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [parat](http://finto.fi/yse/fi/page/Y510950)

**Comment by mirmaid** [comment]
5 kertaa Melindassa.

**Comment by jtuohini** [comment]
Ruotsiksi tietysti _**bjäror**_ (ilman ylimääräisiä pisteitä O:ssa). Ja Melindassa siis muutama muukin, jotka oli kuvailtu Kula-termein, ml. Uno Harvan vuoden 1928 vertaileva tutkimus moisista maitovarkaista.

**Comment by mariaforsen** [comment]
Sv. bjäror HT pukar, pukharar, trollharar, mjölkharar
https://svenska.se/tre/?sok=bj%C3%A4ra&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
