### ISSUE TITLE
kotkat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10954]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kotkat](http://www.yso.fi/onto/yso/p15206)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennys/monikielisyyden tarkennus

**Perustelut ehdotukselle**

Vastine on ruotsiksi ollut Aquila, mutta se viittaa tiettyyn sukuun, ja jos siihen todella halutaan viitata niin sv. vastine olisi "Aquila". Ruotsiksi haluttaisiin tietty viitata vähän laajemmin, eli tähän https://namnochslaktskap.artfakta.se/taxa/6006148/details siis yleisnimityksenä. Kuten wikipediassa: https://fi.wikipedia.org/wiki/Kotka_(lintu) https://sv.wikipedia.org/wiki/%C3%96rnar https://en.wikipedia.org/wiki/Eagle Näinhän se on nyt myös englanniksi. Onko mahdollista tehdä näin, eli sv. ja eng. saisivat olla kuten tähän asti, vai pitääkö kuitenkin olla nimenomaan vain Aquila-sukuun viittaava?

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
YSOn hierarkioita on päivitetty Laji.fi:tä vastaaviksi (kun joku on kiinnittänyt huomiota, että eivät ole taksonomisesti oikein). Suomalaisessa kontekstissa _kotkat_-sanalla varmaan usein tarkoitetaan täkäläistä maakotkaa ja merikotkaa (näköjään myös esim. https://melinda.kansalliskirjasto.fi/byid/013568086), mutta halutaanko tässä kohtaa hierarkian osalta poiketa Laji.fi:stä?

**Comment by jarmosaarikko** [comment]
Kotkat tarkoittaa Lajistossa Aquila sukua eli varataan se nyt tälle suvulle nimeksi.  Muille kotkasuvuille käytetään eri nimiä eikä yleistä "yläkäsitettä" niille ole  ehkä kuin petolinnut

**Comment by jarmosaarikko** [comment]
Vaikka yleinen ajatus kotkista kattaisi suomeksi ja ruotsiksi molemmat, en jotenkin haluaisi poiketa taksonomiasta tässä tapauksessa, kun noita erilaisia kotkasukuja on aika paljon. kts. kuva. 
![image](https://user-images.githubusercontent.com/32375550/204223460-83f4798c-3a5f-4ede-9d99-bee33a191f2c.png)
