### ISSUE TITLE
vegaaniruoat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10955]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vegaaniruoat

**Ehdotettu termi ruotsiksi**

veganrätter 

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

nyt kuvailussa käytetään yhdistelmää kasvisruoat & veganismi, mikä tuntuu hassulta

**Ehdotettu yläkäsite YSOssa (LT)**

 [kasvisruoat](http://www.yso.fi/onto/yso/p9025)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 vegaaniset ruoat, veganska rätter

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. Yhden astian vegaaniruoat 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [vegaaniruoat](http://finto.fi/yse/fi/page/Y510955)

**Comment by ilona-x** [comment]
YKLssa on luokkakin näille: 
68.221  Vegaaniruoat  | Veganrätter | Vegan dishes
https://finto.fi/ykl/fi/page/68.221

**Comment by mariaforsen** [comment]
Olisi tärkeä ja on kaivattu, harva vegaani-keittokirja sisältää tietoa veganismista aatteena, eli nykyinen tilanne johtaa jopa virheellisyyteen.  

(Lisäksi sanastossa on nyt monikielisyyden kannalta se ongelma että kasvisruoat on sv. vegetariska rätter ja samoin englanniksi. Se pitää mahdollisesti muuttaa > grönsaksrätter? Silloinkin entistä tärkeämpänä tämä toinen termi vegaaniruoat, koska läheskään kaikki vegaaniruoka ei ole "grönsaksrätter" vaan koostuvat myös nykyaikaisista tuotteista joissa on toki vain kasvi_peräisiä_ ainesosia, mutta niitä ei mielletä grönsaker:iksi. Ainakin ruotsin kannalta tarvittaisiin oikeastaan kolme eri termiä: grönsaksrätter, vegetariska rätter, veganrätter, mutta tästä pitää ehkä tehdä erillinen issue)

**Comment by mirmaid** [comment]
^ Olettaisin kyllä että suomeksi kasvisruoat = "vegetaariset ruuat", eli ei riipu siitä, onko käytetty vihanneksia.

**Comment by nikopartanen** [comment]
http://id.loc.gov/authorities/subjects/sh96001805
http://www.wikidata.org/entity/Q20669090

**Comment by fantsby-m** [comment]
_Vegaaniset ruoat_ olisi parempi päätermi (myös YKL:ssä). Vegaani on henkilö, vegaaninen on adjektiivi.

**Comment by fantsby-m** [comment]
Suomeksi kasvisruoka ei tarkoita pelkästään kasviksista/vihanneksista tehtyä ruokaa vaan mitä tahansa vegetaarista tai vegaanista ruokaa.

**Comment by mariaforsen** [comment]
Kasvisruoka-termi on tosiaan ongelmallinen monikielisyyden kannalta, pääterminä ei kuitenkaan voi olla "vegetariska eller veganska rätter", täyttä vastaavuutta ei saada?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _vegaaniset ruoat_, ohjaustermiksi _vegaaniruoat_.

**Comment by mariaforsen** [comment]
Sv. veganska rätter HT veganrätter, vegankost, veganmat 
Jfr https://id.kb.se/term/sao/Vegankost
https://svenska.se/tre/?sok=vegansk&pz=1
https://svenska.se/tre/?sok=vegan&pz=1
Jfr https://finto.fi/yso/fi/search?clang=fi&q=*ruoat
