### ISSUE TITLE
vegaani

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10958]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vegaani

**Ehdotettu termi ruotsiksi**

veganer

**Ehdotettu termi englanniksi**

vegans

**Tarkoitusta täsmentävä selite**

henkilö joka ei nauti mitään eläinkunnasta peräisin olevaa ravintoa eikä käytä muitakaan eläinperäisiä tuotteita, nahkavaatteita tms.

**Perustelut ehdotukselle**

tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555), [02 Filosofia](http://www.yso.fi/onto/yso/p26545)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [veganismi](http://www.yso.fi/onto/yso/p9028)

**Vastaava käsite muussa sanastossa**

 [vegans](http://id.loc.gov/authorities/subjects/sh2003011014), [veganer](https://id.kb.se/term/sao/Veganer)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. Veganism : politics, practice, and theory / Eva Haifa Giraud ; The vegan matrix : understanding and discussing privilege among vegans to build a more inclusive and empowered movement / Melanie Joy ; Vystopia : the anguish of being vegan in a non vegan world / Clare Mann.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [vegaani](http://finto.fi/yse/fi/page/Y510958)

**Comment by mirmaid** [comment]
Ei vastaavia sanastossa, mutta tätä käytetty vapaana avainsanana melko paljon.

**Comment by fantsby-m** [comment]
Toki monikossa. Entä kasvissyöjät/vegetaristit?

**Comment by jtuohini** [comment]
Sukulaiskäsitteistä _kasvissyöjät_ eli _vegetaristit_ lienee samalla tavoin helposti rajattavissa (https://www.kielitoimistonsanakirja.fi/kasvissyöjä), mutta samalla logiikalla sanastoon kenties tarvittava _lihansyöjät_ ei niinkään: "lihaa ravintonaan käyttävä eläin t. kasvi; myös lihaa syövästä ihmisestä tav. kasvissyöjän vastakohtana" (https://www.kielitoimistonsanakirja.fi/lihansyöjä).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _vegaanit_.

**Comment by jtuohini** [comment]
Ja KT-muodoksi varmaan myös _veganistit_ (= **veganismin** kannattaja/käytännön toteuttaja)?

**Comment by mariaforsen** [comment]
Sv. veganer
