### ISSUE TITLE
januskinaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10951]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

januskinaasit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/140099

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [januskinaasit](http://finto.fi/yse/fi/page/Y510951)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D053612 muodossa _Janus-kinaasit_. Lääketieteen termit: _januskinaasit_.

**Comment by mariaforsen** [comment]
Sv. januskinaser /mesh
