### ISSUE TITLE
indoliini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10952]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

indoliini

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/140401

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [indoliini](http://finto.fi/yse/fi/page/Y510952)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Indoliini

https://d-nb.info/gnd/4298729-5

**Comment by mariaforsen** [comment]
Sv. indolin
https://sv.wikipedia.org/wiki/Indolin
