### ISSUE TITLE
Viipuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10959]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Viipuri](http://www.yso.fi/onto/yso/p94486)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko mahdollista lisätä tähän osakäsite Monrepos? Termi on kyllä yleisessä YSO:ssa, mutta ei paikoissa. https://fi.wikipedia.org/wiki/Monrepos

**Perustelut ehdotukselle**

Luetteloin m.m. Monreposta lähetettyjä kirjeitä

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by ilona-x** [comment]
YSOssa yläkäsitteenä kartanot, mutta huomautuksen mukaan puisto ja kartano.

**Monrepos** http://www.yso.fi/onto/yso/p10671
Huomautus
    Puisto ja kartano Viipurissa.

--

Wikipedian mukaan Monrepos on puisto- ja luonnonsuojelualue https://fi.wikipedia.org/wiki/Monrepos

--

Luonnonsuojelualueet ja puistot on auktorisoitu YSOon.
puistot http://www.yso.fi/onto/yso/p3227
luonnonsuojelualueet http://www.yso.fi/onto/yso/p1371

**Comment by mirmaid** [comment]
YSOn auktoriteetti kattaa myös puiston. Tulevaisuudessa mahdollisesti tämäntyyppisten käsitteiden paikka tulee muuttumaan, mutta toistaiseksi YSOn käsitettä voi käyttää myös puistoalueesta.
