### ISSUE TITLE
vuosikatsaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10964]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vuosikatsaukset](http://www.yso.fi/onto/yso/p28686)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi vuosiraportit?

**Perustelut ehdotukselle**

vai onko tarkoitus käyttää raportit tai toimintakertomukset? vrt. SLM

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Vuosikatsauksella YSOssa tarkoitetaan mitä tahansa vuosikatsausta mikä näkyy kuvailukäytössäkin, erityisesti näkyy korostuvan kirja-alan katsaukset, "Runovuosi 2007" yms, Toimintakertomukset taas liittyvät jonkin organisaation vuoteen ja siihen yhteyteen vuosiraportit voisi sopia ohjaustermiksi paremmin.

Jos kuitenkin tarkastellaan yleiskielen (tai talouden) näkökulmasta niin vuosikatsaus viittaa terminä vahvasti juuri organisaation vuosiraporttiin eli toimintakertomukseen. Jos googlaa "vuosikatsaus" niin suurin osa tuloksista on tällaisia organisaatioiden vuosiraportteja. Käsitteiden _vuosikatsaukset_ ja _toimintakertomukset_ eroa voisi siis YSOssa tähdentää, ettei käytetä tai haeta väärin.

Riittäiskö tarkentava käyttöhuomautus näille käsitteille? Tekisi mieli ehdottaa vuosikatsauksille sulkutarkennetta, mutta mitään järkevää ei varmaan löytyisi kuitenkaan.

**Comment by mirmaid** [comment]
SLM:ssä ei ole vuosikatsaukset tai vuosiraportit -termejä (myöskään ohjaustermeinä). Vuosikertomukset on molemmissa sanastoissa ohjausterminä toimintakertomukset-käsitteelle, ja SLM:ssä on osavuosikatsaukset ohjausterminä toimintakertomuksille. 

En sitten tiedä, onko vuosikatsaukset tuossa "sarjakuvavuosi 2022" -merkityksessä kovin tarpeellinen kuitenkaan.

**Comment by mirmaid** [comment]
Pitäisikö lisätä vuosikatsaukset (toimintakertomukset) KÄ toimintakertomukset (toki näissä pitäisi yleensä käyttää SLM-termiä)? Ja lisätä tälle määritelmä: "Katsaus tiettyyn vuoteen yleisesti tai jonkin aihealueen osalta, esim. julkaistu kirjallisuus tai tärkeimmät tapahtumat." Tjsp. Vai pitäisikö vain poistaa vuosikatsaukset?

**Comment by mirmaid** [comment]
Ehdotus
vuosikatsaukset (toimintakertomukset) KÄ toimintakertomukset

**Comment by mirmaid** [comment]
Ehdotus
vuosikatsaukset: lisätään määritelmä: "Katsaus tiettyyn vuoteen yleisesti tai jonkin aihealueen osalta, esim. julkaistu kirjallisuus tai tärkeimmät tapahtumat" TAI poistetaan käsite.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään ohjaustermi: vuosikatsaukset (toimintakertomukset) KÄYTÄ toimintakertomukset
Poistetaan vuosikatsaukset-käsite sanastosta.
Kysytään SLM-kokouksessa, onko vuosikatsaukset-käsitteelle tarvetta genreterminä.

**Comment by mirmaid** [comment]
KÄ katsaukset /SLM.
