### ISSUE TITLE
kuvakirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10962]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuvakirjat](http://www.yso.fi/onto/yso/p11808)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko kuvakirja vain kaunoa vai voiko myös (lasten) tietoaineistoa nimittää kuvakirjaksi (aiheena)? 

**Perustelut ehdotukselle**

Nousi esiin SLM-kokouksessa

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Myös KAUNO-kokoukseen kysymys käytöstä.

**Comment by mariaforsen** [comment]
Ruotsiksi bilderbok on neutraali termi sen suhteen onko kaunokirja vai tietokirja. Nationalencyklopedin: ursprungligen tysk benämning på en rikt illustrerad bok, från 1800-talet genrebeteckning för böcker för yngre barn där bilderna är viktiga för innehållet.  Eli ratkaisevaa on se että kuvitus on tärkeä sisällön kannalta, käytetään lasten sekä kauno- että tietokirjallisuudesta. 
https://svenska.se/tre/?sok=bilderbok&pz=1
SAO: bilderböcker
"En kombination av text och bilder med minst en bild på varje uppslag, där bilderna utgör hälften eller mer av boken. Genreämnesord för barn- och ungdomslitteratur."

Jos jostain syystä haluttaisiin rajata vain kaunokirjallisuuteen (en kannata), se pitäisi näkyä jo termissä, ainakin ruotsiksi.

**Comment by ilona-x** [comment]
SLM:n käyttöhuomautus:
    Käytetään lastenkirjoista ja tyyliltään lastenkirjaa muistuttavista kirjoista, jotka perustuvat yhtä paljon tai enemmän kuvaan kuin tekstiin. http://urn.fi/URN:NBN:fi:au:slm:s739

**Comment by YSO-kokous** [comment]
**Päätös**

YSO-ryhmä ei nähnyt välttämättömänä rajaamista fiktioon. Jos tämä katsotaan välttämättömäksi, voisi tarkenteen lisäämistä harkita.

**Comment by mirmaid** [comment]
Entä _runokuvakirjat_? Törmäsin genreen "aikuisten" runokirjassa, mutta näyttää käytetyn pääosin lastenkirjoista.

**Comment by mariaforsen** [comment]
Samalla tavalla pitäisi se olla ok myös aikuisten runokuvakirjoista.

**Comment by AuHo22** [comment]
Runokuvakirjat-termi näyttäisi kaipaavan tarkentamista: -> Po. Käytetään kuvakirjoista, joissa runot muodostavat yhtenäisen tarinan tai runo ja kuva ei toimi ilman vuorovaikutussuhdetta.

Enisimmäisessä tapauksessa käytetään lastenkirjallisuuden yhteydessä, mutta jälkimmäinen tarvitaan aikuisten aineiston kuvailua varten. Esim. Hankala muusa / Epe Niiranen, Eero Suvilehto, jossa hauskuus lähti nimenomaan runon /aforismin ja kuvan välisestä jännitteestä.

Lastenkirjallisuudesta:  "lastenkirjallisuudessa runokuvakirjoilla tarkoitetaan kuvakirjaa, jossa on riimitelty, yhtenäinen tarina, eikä yksittäisiä runoja. Kuvakirja, jossa on yksittäisiä runoja, jotka eivät muodosta yhtenäistä tarinaa, luokitellaan runokirjaksi luokkaan 82.2."

kuvateokset ja runot -> on käytetty esim. valokuvateoksissa (tai myös maalauksia, akvarelleja), joissa on sitten myös runoja (yleensä yksittäisiä), usein uskontoaiheisia tai sitten voi olla luontoaiheisia.

**Comment by mirmaid** [comment]
KAUNO-ryhmä: Kuvakirjat-termin käyttö lasten tietokirjoissa. Kauno-ryhmä kannattaa ehdotusta.

**Comment by mirmaid** [comment]
Runokuvakirjat: lisätään käyttöhuomautus: Käytetään kuvakirjoista, joissa runot muodostavat yhtenäisen tarinan tai runo ja kuva eivät toimi ilman vuorovaikutussuhdetta.
