### ISSUE TITLE
joustava tuotanto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10967]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[joustava tuotanto](http://www.yso.fi/onto/yso/p4452)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko toimiva näin, vai pitäisikö FMS-järjestelmät vaihtaa päätermiksi? Suhde joustavaan automaatioon, jolla osin samoja ohjaustermejä?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
joustava automaatio x 60
joustava tuotanto x 177
joustava automaatio & joustava tuotanto x 43

eli vain 23 viitettä, joissa joustava automaatio ilman joustava tuotanto -termiä, 
ja näistäkin moneen näyttäisi sopivan joustava tuotanto (tai FMS-järjestelmät, jos päätermi vaihdetaan). Monissa viitteissä esiintyy nimekkeessä tai 653-kentässä FMS.

Joustava automaatio -termi näkyy olevan todennäköisesti virheellisesti mm. näissä viitteissä:

- Kehittävä työntutkimus : perusteita, tuloksia ja haasteita 
- Joustavien materiaalien simulointi
- [Kirja-arvostelu:Kehittävä työntutkimus : perusteita, tuloksia ja haasteita]

Ehdotus; 
yhdistetään
joustava automaatio KÄYTÄ joustava tuotanto (tai FMS-järjestelmät)

**Comment by ilona-x** [comment]
Tuli vastaan tähän mahdollisesti liittyvä vanha ehdotus: **joustava tuotantoautomaatio** #120  https://github.com/Finto-ehdotus/YSE/issues/120

TEPA (https://termipankki.fi/tepa/fi/haku/joustava%20tuotantoautomaatio):

fi        joustava tuotantoautomaatio

määritelmä
tuotantomenetelmä, jossa tietokoneohjauksen ja automaation avulla voidaan tehokkaasti valmistaa pieniäkin sarjoja asiakkaan erityistarpeisiin sovitettuja tuotteita

Lähde: Teollisen talonrakennuksen sanasto (Tekes ja TSK, 1991)

**Comment by ilona-x** [comment]
Eli tämä yhdistämisehdotus on yhä voimassa;
yhdistetään joustava automaatio & joustava tuotanto 

LCSH:ssa pääterminä [Flexible manufacturing systems](http://id.loc.gov/authorities/subjects/sh85049095) , 
joten ehkä YSOssakin voisi olla pääterminä **joustavat tuotantojärjestelmät** KT FMS-järjestelmät, joustavat valmistusjärjestelmät, joustava tuotanto, joustava automaatio, joustava tuotantoautomaatio

**Comment by mariaforsen** [comment]
Sv.   flexibla produktionssystem HT FMS (produktionssystem), flexibla tillverkningssystem, flexibel produktion
https://www.rikstermbanken.se/search?q=fms&s=termer
/uppslagsverk/encyklopedi/lång/fms-(flexible-manuf-system)
https://termipankki.fi/tepa/fi/haku/fms
https://libris.kb.se/hitlist?q=Flexibla+tillverkningssystem&r=&f=simp&t=&s=c&g=&m=10
https://libris.kb.se/hitlist?d=libris&q=flexibla+produktionssystem&f=ext&spell=true&hist=true&mf=&p=1
https://www.sanakirja.fi/custom/all/tillverkningssystem
https://www.sanakirja.fi/custom/en-sv-fi/tuotantoj%C3%A4rjestelm%C3%A4

**Comment by YSO-kokous** [comment]
Hyväksytään tämä ehdotus:
https://github.com/Finto-ehdotus/YSE/issues/10967#issuecomment-2348761871

**Comment by mariaforsen** [comment]
OT joustavat valmistusjärjestelmät?

**Comment by ilona-x** [comment]
Joo, varmasti olisi hyvä olla ohjaustermeinä myös ne kaikki termimuodot, jotka nyt ovat joustavan tuotannon ja joustavan automaatioon ohjaustermeinä. En huomannut niitä tuohon aiempaan ehdotukseen listata.
