### ISSUE TITLE
laki julkisen hallinnon tiedonhallinnasta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10963]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laki julkisen hallinnon tiedonhallinnasta](http://www.yso.fi/onto/yso/p39166)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi tiedonhallintalaki?

**Perustelut ehdotukselle**

JUHO: 
Laki julkisen hallinnon tiedonhallinnasta KT tiedonhallintalaki
http://www.yso.fi/onto/juho/p14184

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Jo tehty: https://finto.fi/yso/fi/page/p39166
