### ISSUE TITLE
vaihtuvuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10960]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vaihtuvuus](http://www.yso.fi/onto/yso/p22840)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ryhmien lisäys/vaihto: 71 ja mahdollisesti 75

**Perustelut ehdotukselle**

Ks. eng. ja sv. -termit. Jos tarkoitus olisi viitata yleisempään "muuttuvuuteen" (sv. föränderlighet) niin termi voisi käyttää myös esim. tällaisiin: Opetuksia pysymättömyydestä ja karmasta / Geshe Pema Dorjee, mutta silloin muunkieliset termit olisivat eri kuin nyt. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
_Työvoiman vaihtuvuus_ kaipaisi ehkä ohjaustermejä _vaihtuvuus (työntekijät), henkilöstön vaihtuvuus_. Aika suuri osa Melindan vain 72:sta viitteestä on nimittäin tätä, mihin olisi tarkempikin termi. Sopii ehkä vähän huonosti jos kyse on johtajatason työntekijän tai tietyn viranhaltijan vaihtumisesta, mutta voisi kuitenkin korjailla ensin kaikki mihin sopii. Muissakaan tapauksissa _vaihtuvuus_ ei välttämättä ole paras mahdollinen - termi, joka toimii paremmin ketjun osana kuin yksin.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään ohjaustermit: 
vaihtuvuus (työntekijät) KÄYTÄ työvoiman vaihtuvuus
henkilöstön vaihtuvuus KÄYTÄ työvoiman vaihtuvuus
Poistetaan sanastosta vaihtuvuus. Korjataan viitteet tapauskohtaisesti.
