### ISSUE TITLE
e-kirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10965]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[e-kirjat](http://www.yso.fi/onto/yso/p7797)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan SLM-terminä, kuten myös muut e-slm-termit kuten verkkolehdet (ei siis YSO-termejä)

**Perustelut ehdotukselle**

* OCLC on luopunut 655 e-kirjamerkinnöistä, ja Ex Libris seuraa perässä
  * ks "Kentän 655 e-aineistomerkinnöt - voidaanko luopua?"  https://www.kiwi.fi/x/J4D6E
* nyky-OPACit tarjoavat rajausmahdollisuuden e-aineistoon ilman slm-termiäkin

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Koskeeko tämä myös tietokannat-termiä?

**Comment by HeidiRonkainen** [comment]
Tietokanta -termi säilyy / Kumea

**Comment by HeidiRonkainen** [comment]
Kumean kokouksessa 14.12.2022 ei nähty ongelmia hakujen kannalta termien poistamisessa.

**Comment by ilona-x** [comment]
Kumean kokouksen muistio:
https://www.kiwi.fi/display/kumea/2022-12-14

**Comment by mirmaid** [comment]
SLM-ryhmä kannattaa varovasti poistoa (paitsi blogikirjoitukset ja verkkopelit), Kirjastopalvelu selvittää vielä yleisten kirjastojen näkemystä poistettaviin termeihin.

**Comment by AuHo22** [comment]
Näistä termeistä taidettiin keskustella, mutta henkilöstövaihdoksista jne. johtuen Kirjastopalvelulla on asiakasohjausryhmän kokous vasta syksyllä 3.10.

e-kirjat
verkkolehdet
verkkojulkaisut 
verkkosarjakuvat

**Comment by mirmaid** [comment]
Käsitellään kokouksen jälkeen.

**Comment by AuHo22** [comment]
Tiukasta ohjelmasta johtuen tätä ei ollut ehditty käsitellä, mutta tarkoituksena on ohjata kysymys sitten kirjastoille viikkotiedotteen tms. kautta, tähän hätään ei ole uutta tiedotettavaa.

**Comment by mirmaid** [comment]
Päätös seuraavassa kokouksessa, siihen mennessä Helmet-kirjastojen ja Kirjastopalvelun kommentit.

**Comment by AuHo22** [comment]
Hei,
tässä meidän kommentti:
**e-kirjat -> ei poisteta**
verkkolehdet -> poistetaan
verkkojulkaisut -> poistetaan 
verkkosarjakuvat -> poistetaan

**Comment by mirmaid** [comment]
Poistetaan kaikki /SLM.
