### ISSUE TITLE
merinahkiainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10961]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

merinahkiainen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sea lamprey

**Tarkoitusta täsmentävä selite**

https://laji.fi/taxon/MX.53086

**Perustelut ehdotukselle**

kalalaji

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

kuvailussa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [merinahkiainen](http://finto.fi/yse/fi/page/Y510961)

**Comment by mariaforsen** [comment]
Sv. havsnejonöga

**Comment by jarmosaarikko** [comment]
en: sea lamprey  
KT Petromyzon marinus  
YK nahkiaiskalat
http://www.wikidata.org/entity/Q385764
