### ISSUE TITLE
Valmet L-70 Vinka (lentokone)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10971]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Valmet L-70 Vinka (lentokone)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Täsmällinen lentokonetyyppi

**Ehdotettu yläkäsite YSOssa (LT)**

 [lentokoneet](http://www.yso.fi/onto/yso/p1053)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Teos: 978-952-229-220-9

**Ehdottajan organisaatio**

Kirjastopalvelu /Outi Hintikka
**Termiehdotus Fintossa:** [Valmet L-70 Vinka (lentokone)](http://finto.fi/yse/fi/page/Y510971)

**Comment by mariaforsen** [comment]
Sv. Valmet L-70 Vinka (flygplan)
