### ISSUE TITLE
maastamuuttajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10970]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maastamuuttajat](http://www.yso.fi/onto/yso/p20631)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "emigrantit"

**Perustelut ehdotukselle**

YSO:ssa tällä hetkellä viittaussuhteet harhaanjohtavat; historiallinen (Neuvosto-)Venäjältä Suomeen suuntautunut huomioitava, mutta muutoin "emigrantit" on yhtä kuin "maastamuuttajat", vastakohtanaan "immigrantit" eli "maahanmuuttajat"

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Tämä on jo tehty: https://finto.fi/yso/fi/page/p20631

**Comment by jtuohini** [comment]
YSO:ssa siis epätasapaino, että _immigrantit_ viittaa vain **maahanmuuttajat**-asisanaan, _emigrantit_ taas kolmeen eri asiasanaan (**maastamuuttajat**, **pakolaiset**, **siirtolaiset**). Joko kummastakin pitäisi viitata kolmeen tai vaihtoehtoiseseti vain yhteen, koska **pakolaiset** ja **siirtolaiset** eivät kerro muuton suuntaa. Venäjän emigrantit eli vuoden 1917 vallankumousta Suomeen paenneet ovat oma lukunsa ja mieluiten ilmaistava huomautuksena.

**Comment by mirmaid** [comment]
Emigrantit-viittaukset tehtiin vastikään, kun aikaisempi emigrantit-käsite poistettiin. Immigrantit-muoto ei ole ollut vastaavalla tavalla suomeksi käytetty. Tarkoitus oli siis ohjata käyttämään myös pakolaiset/siirtolaiset -käsitteitä soveltuvasti silloin, kun aineistossa puhutaan emigranteista.

**Comment by mirmaid** [comment]
En ehkä näe tarvetta muutokselle tässä?
