### ISSUE TITLE
Valmet L-90 TP Redigo (lentokone)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10972]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Valmet L-90 TP Redigo (lentokone)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Lentokonetyyppi

**Perustelut ehdotukselle**

Täsmällinen lentokonetyyppi

**Ehdotettu yläkäsite YSOssa (LT)**

 [lentokoneet](http://www.yso.fi/onto/yso/p1053)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-229-220-9

**Ehdottajan organisaatio**

Kirjastopalvelu / Outi Hintikka
**Termiehdotus Fintossa:** [Valmet L-90 TP Redigo (lentokone)](http://finto.fi/yse/fi/page/Y510972)

**Comment by mariaforsen** [comment]
Sv. Valmet L-90 TP Redigo (flygplan)

**Comment by mariaforsen** [comment]
Onko tässä sekaannuksen vaaraa vai miksi tarkenne?
