### ISSUE TITLE
eheyttäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10977]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eheyttäminen](http://www.yso.fi/onto/yso/p9021)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus/määritelmä tai jako

**Perustelut ehdotukselle**

Monimerkityksinen termi, monikielisyys ei nyt toimi. Ks. Melindaa. 
https://fi.wikipedia.org/wiki/Eheytt%C3%A4minen
https://termipankki.fi/tepa/fi/haku/eheytt%C3%A4minen

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Taitaa olla opetuksen yhteydessä pitkälti sama asia kuin _integroitu opetus (oppiaineet)_ - termistö ehkä muuttunut. Korjataan eheytyshoitoja käsittelevät viitteet ja tutkitaan em. yhdistämistä. Jos ei onnistu, niin varmaankin _eheyttäminen (opetus)_.

**Comment by YSO-kokous** [comment]
PÄÄTÖS 

Toteutetaan mirmaidin edellä olevan ehdotuksen mukaisesti.

**Comment by mirmaid** [comment]
Aika paljon aineistoa myös yhdyskuntasuunnittelusta.

**Comment by mirmaid** [comment]
Päätermiksi _opetuksen eheyttäminen_ (YSO-päivityskokous 23.10.2023).

**Comment by mariaforsen** [comment]
Sv. helhetsskapande undervisning HT helhetsperspektiv på undervisningen, integrering (av undervisningen)

https://termipankki.fi/tepa/fi/haku/eheytt%C3%A4minen
http://www03.oph.fi/sanasto/r_alaluokka2_3_1.asp
https://eperusteet.opintopolku.fi/#/sv/perusopetus/419550/tekstikappale/429106
https://www.doria.fi/bitstream/handle/10024/181727/mard_nina.pdf?sequence=1&isAllowed=y
https://blogs2.abo.fi/magisteravhandlingariskolsamfundet/category/helhetsskapande-undervisning/
jfr integrerad undervisning (läroämnen)

**Comment by mirmaid** [comment]
Opetuksen eheyttäminen korjattu.

**Comment by mirmaid** [comment]
Googlella mm. _yhdyskuntarakenteen eheyttäminen_ ja _eheyttävä yhdyskuntasuunnittelu_.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _yhteiskuntarakenteen eheyttäminen_, jos vaikuttaa sopivan aineistojen puolesta.

**Comment by mariaforsen** [comment]
Termi "yhdyskuntarakenteen eheyttäminen" enemmän käytetty googlessa. 

Sv. förenhetligande samhällsplanering
https://byaservice.wordpress.com/tag/samhallsplanering/
https://helda.helsinki.fi/bitstreams/6d3197dd-1ac2-44a7-88ce-6acbafa93796/download

**Comment by mirmaid** [comment]
^ Varmaankin vaan typo tuossa päätöskirjauksessa.

**Comment by mirmaid** [comment]
Jäljellä 25 viitettä, osalle varmaankin riittää vielä korvaaminen jollain olemassaolevalla termillä ja muille ehkä 653.
