### ISSUE TITLE
vastineet [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10975]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vastineet [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [mielipidekirjoitukset](http://www.yso.fi/onto/yso/p24007)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/012640874 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [vastineet [SLM]](http://finto.fi/yse/fi/page/Y510975)

**Comment by mirmaid** [comment]
https://journalisti.fi/artikkelit/2017/05/vastine-vai-mielipidekirjoitus/

**Comment by mirmaid** [comment]
Jaakko varmistaa, onko riski sekoittua oikeustieteelliseen aineistoon.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by jtuohini** [comment]
Varmistettu: Helsingin yliopiston kirjaston oikeustieteestä vastaavan kokoelmanhoitajan mukaan ei ole riski sekoittua, sillä vastaajien antamia vastineita haasteisiin ei käytännössä julkaista missään (eli niiden kuvailutarvetta ei ole).

**Comment by mariaforsen** [comment]
Sv. genmälen HT bemötanden (svar), repliker (genmälen) 

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_6347a71b1bdebf3e017291cd97e78f9d&list_id=1&keyword=vastine&word=vastine
https://svenska.se/so/?sok=replik&pz=1
https://svenska.se/so/?sok=bem%C3%B6tande&pz=1
https://svenska.se/so/?sok=genm%C3%A4le&pz=1
https://www.sanakirja.fi/custom/fi-en-sv/vastine
https://termipankki.fi/tepa/fi/haku/vastine

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. genmälen HT bemötanden (svar) ?
