### ISSUE TITLE
datafikaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10974]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

datafikaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Datan määrä ihmisistä ja heidän toimistaan kasvaa digitoituneessa, edelleen digitoituvassa maailmassa, tätä prosessia kutsutaan - DATAFIKAATIOKSI - eng datafication https://fi.wikipedia.org/wiki/Datafikaatio Lähitermejä: valvonta/digitalisaatio/big data

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [datafikaatio](http://finto.fi/yse/fi/page/Y510974)

**Comment by mariaforsen** [comment]
Sv. datafiering HT datafikation 
https://www.helsinki.fi/sv/aktuellt/teknologi-manniskan/samhallets-datafiering
http://www.diva-portal.se/smash/get/diva2:1307030/FULLTEXT01.pdf
https://www.umu.se/sociologiska-institutionen/forskning/forskargrupper/digital-sociologi/

**Comment by mirmaid** [comment]
Ei Melindassa, ei LCSH, GND, SAO.

**Comment by ilona-x** [comment]
Voisiko vielä jättää termiehdotukseksi? Aineistoesimerkkiä jäin kaipaamaan tähän ehdotukseen.

**Comment by jarmosaarikko** [comment]
Wikidata:  http://www.wikidata.org/entity/Q16954558 - Wikipediassa en ja fi kuvaukset.

**Comment by fantsby-m** [comment]
HY on nostanut datafikaation teemaksi verkkosivuilleen: 
https://www.helsinki.fi/fi/ajankohtaista/ihmisten-teknologia/yhteiskunnan-datafikaatio

**Comment by fantsby-m** [comment]
Melindasta löytyi hakusanalla "datafication" kuitenkin 34 tulosta johon asiasana varmaankin sopisi:
 https://melinda.kansalliskirjasto.fi/F/?func=find-b&request=%22datafication%22&find_code=WRD&x=0&y=0&local_base=fin01_opac

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. RT _big data_.
