### ISSUE TITLE
harjoituskoneet.

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10973]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

harjoituskoneet.

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

SOTOn sanastossa. On hyvä täsmätermi. Aihetta vaikea kuvata täsmällisesti muilla termeillä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [lentokoneet](http://www.yso.fi/onto/yso/p1053)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [hävittäjät (sotilaslentokoneet)](http://www.yso.fi/onto/yso/p3104)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 978-952-229-220-9

**Ehdottajan organisaatio**

Kirjastopalvelu / Outi Hintikka
**Termiehdotus Fintossa:** [harjoituskoneet.](http://finto.fi/yse/fi/page/Y510973)

**Comment by mirmaid** [comment]
Ainakin ohjaustermiksi harjoituslentokoneet, mutta näyttää kyllä ehkä siltä, että ei tämä sekoitu muihin laitteisiin (google-tulokset taitaa olla lähinnä automaattikäännettyjä).

**Comment by mariaforsen** [comment]
Minkälainen suhde koulutuslentokoneisiin? Ruotsiksi termi rajautuu miten vain lentokoneisiin, joten on tärkeää että myös suomeksi on selkeästi siihen rajautuva. Ks. 
https://en.wikipedia.org/wiki/Trainer_aircraft
https://sv.wikipedia.org/wiki/Skolflygplan 
https://fi.wikipedia.org/wiki/Koulutuslentokone

https://sv.wikipedia.org/wiki/%C3%96vningsflygplan : 
"Från mitten av 1930-talet har ingen skillnad gjorts på övningsflygplan och skolflygplan, utan alla flygplan som är avsedda för flygutbildning (grundläggande eller mer avancerad) benämns skolflygplan med beteckningen Sk." Eli ruotsiksi ei enää tehdä eroa övnings- ja skolflygplan-termien välillä. 

https://svenska.se/tre/?sok=skolflygplan&pz=1

Myös SAOssa vain skolflygplan =**LCSH training planes**
https://id.kb.se/find?q=skolflygplan

**Comment by mirmaid** [comment]
^ Varmaan sama asia?

**Comment by ilona-x** [comment]
Ehdotuksessa mainitun teoksen kuvauksessa puhutaan näköjään koulukoneista: https://www.koalakustannus.fi/p/valmet-vinka-ja-redigo-jyrki-laukkanen

Ja myös Wikipedian [Koulutuslentokone](https://fi.wikipedia.org/wiki/Koulutuslentokone)-artikkelissa puhutaan koulukoneista 

Asiaa sen paremmin tuntematta koulutuslentokoneet kuulostaisi näistä selkeimmältä termimuodolta.

Kielitoimiston sanakirjasta näkyy näistä vaihtoehdoista löytyvän vain koulukone https://www.kielitoimistonsanakirja.fi/#/koulukone?searchMode=all

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _koulutuslentokoneet_, muut ohjaustermeiksi.

**Comment by mariaforsen** [comment]
Sv. skolflygplan HT övningsflygplan, träningsflygplan
