### ISSUE TITLE
tilannejohtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10976]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tilannejohtaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve asiasanalle esimerkiksi ensihoidon, puolustusvoimien, poliisitoimen ja pelastustoimen aineistoa kuvailtaessa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [johtaminen](http://www.yso.fi/onto/yso/p554)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Leadership in dangerous situations - handbook for the armed forces, emergency services, and first responders
https://www.theseus.fi/discover?query=tilannejohtaminen
https://www.finna.fi/Search/Results?lookfor=tilannejohtaminen&type=AllFields

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tilannejohtaminen](http://finto.fi/yse/fi/page/Y510976)

**Comment by mariaforsen** [comment]
Sv. situationsledning HT situationsstyrning, lägesledning
https://www.theseus.fi/bitstream/handle/10024/152922/POLAMK_Oppikirja_27_web.pdf?sequence=1&isAllowed=y
https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/74629/Opp200006swe.pdf?sequence=1

**Comment by mirmaid** [comment]
N. 15 x Melindassa, runsaasti Googlella, mutta mikähän tämä on englanniksi? Situational management / leadership tms. ei tunnu vastaavan (?).

**Comment by LeKorsu** [comment]
Kyseinen teos on asiasanoitettu Kongressin kirjastossa
leadership - psychological aspects
leadership - social aspects

**Comment by fantsby-m** [comment]
_**Incident command**_, mahdollisesti. Tai ehkä _**incident command and control**_.

**Comment by fantsby-m** [comment]
Vrt. https://www.wikidata.org/wiki/Q1308801

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
