### ISSUE TITLE
three-step support

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10981]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[three-step support](http://www.yso.fi/onto/yso/p28718)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

three-tiered support

**Perustelut ehdotukselle**

käytetään alan julkaisuissa

**Ehdottajan organisaatio**

Lapin korkeakoulukirjasto

**Comment by mirmaid** [comment]
Ehdotettu muoto englanninkieliseksi päätermiksi? Tarvitsisiko myös tarkenteita englanniksi?
