### ISSUE TITLE
pölytyspalvelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10982]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pölytyspalvelu

**Ehdotettu termi ruotsiksi**

pollineringsservice

**Ehdotettu termi englanniksi**

pollination service

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

 pölytyspalvelut

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [AFO pölytyspalvelu]( http://www.yso.fi/onto/afo/p3700)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pölytyspalveluopas : satoa ja laatua mehiläistarhaajan ja viljelijän yhteistyöllä https://urn.fi/URN:NBN:fi-fe2021120859603

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [pölytyspalvelu](http://finto.fi/yse/fi/page/Y510982)

**Comment by mariaforsen** [comment]
Sv. pollineringstjänster HT pollineringsservice
https://ym.fi/sv/-/ny-strategi-for-att-trygga-pollinerare-och-pollineringstjanster-miljoministeriet-ber-om-utlatanden-om-forslaget
https://hunaja.net/sv/pollinering/

**Comment by mirmaid** [comment]
Suurin osa palveluista on monikossa, ja myös tätä löytyy monikossa Googlella lähes yhtä paljon kuin yksikössä. Tämä on kyllä niin hurmaava termi, kun mielikuva on, että mehiläiset tarjoavat näitä palveluita viljelijöille 🐝🐝🐝

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään monikossa.
