### ISSUE TITLE
mesenkefaalinen astrosyyttiperäinen hermokasvutekijä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10988]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mesenkefaalinen astrosyyttiperäinen hermokasvutekijä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

mesencephalic astrocyte-derived neurotrophic factor

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [hermokasvutekijät](http://www.yso.fi/onto/yso/p37764)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 MANF

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Exploring the role of CDNF and MANF removal in the brain and in the unfolded protein response

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [mesenkefaalinen astrosyyttiperäinen hermokasvutekijä](http://finto.fi/yse/fi/page/Y510988)

**Comment by mariaforsen** [comment]
Sv. mesenkefalisk astrocyt-deriverad nervtillväxtfaktor HT MANF ?
https://helda.helsinki.fi/bitstream/handle/10138/16161/pro_gradu_Nordstrom_2010.pdf?sequence=1&isAllowed=y

**Comment by jarmosaarikko** [comment]
Wikipedia en  https://en.wikipedia.org/wiki/ARMET
Wikidata http://www.wikidata.org/entity/Q18032649
