### ISSUE TITLE
Vuoremijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10980]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Vuoremijoki

**Ehdotettu termi ruotsiksi**

Jakobs älv

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [Norja](http://www.yso.fi/onto/yso/p94309), [Venäjä](http://www.yso.fi/onto/yso/p94479)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Vuoremijoki)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/183645

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Vuoremijoki](http://finto.fi/yse/fi/page/Y510980)

**Comment by mariaforsen** [comment]
Sv. Jakobs älv HT Jakobselva
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=3132&ex=Vuoremijoki
uppslagsverk/encyklopedi/lång/jakobselva

**Comment by mirmaid** [comment]
YK Norja, Venäjä.
