### ISSUE TITLE
esiintymispelko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10983]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[esiintymispelko](http://www.yso.fi/onto/yso/p19677)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaihdetaan pääkäsitteeksi "esiintymisjännitys"

**Perustelut ehdotukselle**

Kielitoimisto määrittelee esiintymispelon ja ramppikuumeen nimenomaan esiintymisjännitykseksi, ei toisinpäin. Pelko on myös vahvemmin yhteydessä fobia-sanaan, joka on selvästi jo lääketieteellinen; jännitys on väljempi ja kattaa myös muun kuin pahimman luokan esiintysmikammon.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Varmaan voi vaihtaakin, mutta samaa molemmilla tarkoitetaan - ja silloin, kun jännitys/pelko on aineiston aiheena, se on yleensä varmaan aika voimakasta kuitenkin. Eli mielestäni varsinaista tarvetta muutokselle ei kyllä ole.

**Comment by annamarj** [comment]
Olisin ehdotuksen hyväksymisen kannalla. Jos kerran on kielitoimistonkin mukainen ja ehdotuksessa on perustelutkin ihan ok. Eli esiintymispelko käytä esiintymisjännitys?

**Comment by FinMeSHienPaimentaja** [comment]
On toki lievän epämiellyttävyyden tunteen ja/tai jännityksen ja kunnon kammon ja/tai pelon (fobian) välillä jatkumo - kuinka vahvasta tai lievästä esiintymisjännityksestä mahtaa olla kyse kuvailtavassa aineistossa enimmäkseen...?

**Comment by tpalonen** [comment]
Kannatan päätermin vaihtamista. On melko yleinen ilmiö esiintymistyötä sisältävissä ammateissa. Käytetty Melindassakin jonkun verran esim. näyttelijät ja muusikot ja opettajat -asiasanojen yhteydessä. Pelko olisi esim. tällaisessa asiayhteydessä vähän outo sanavalinta, koska ihmiset esiintyvät työkseen.

**Comment by jtuohini** [comment]
Ja alkuperäinen ehdotus kumpusi Muska-työryhmän piiristä, jossa valmistellaan musiikkialan opiskelijoille tiedonhaun sivustoa, yhtenä alasivunaan esiintymisjännitystä (ennemmin kuin todellista -pelkoa) koskevat lähteet.

**Comment by mirmaid** [comment]
Ovatko muut pelon alakäsitteet selkeämmin oikeaa pelkoa kuin tämä? Jos muutetaan, vaihtanee käsite paikkaansa myös YSOn päähierarkian haarasta toiseen - koska jos kerran kyse ei ole "oikeasta pelosta", ei yläkäsitekään kaiketi voi olla pelko, vaan _jännittäminen_. 

Edelleenkään itse termimuoto ei omasta puolestani ole kovin olennainen, esiintymisjännitys on ihan yhtä hyvä päätermi kuin esiintymispelko ellei parempikin. Mutta aina kun tehdään päätermin muutos, tietueet voi kertaalleen päivittää Melindassa - paikalliskannat sen sijaan todennäköisesti jäävät pitkälti entiselleen, ja vanhaa termimuotoa valuu myös niistä takaisin Melindaan päin. Siksi itse välttäisin päätermin muutosta silloin kun nykytilakaan ei ole varsinaisesti ongelma.

**Comment by mariaforsen** [comment]
Molemmilla on kai kuitenkin hieman eri merkitysvivahteita, kuten esim. Wikipediassakin mainitaan "Esiintymisjännitys on julkisen esiintymisen aiheuttamaa jännitystä.[1] Esittävien taiteilijoiden kohdalla voidaan puhua myös ramppikuumeesta.[2] Kun ihminen kokee jännityksen niin vahvasti, että se häiritsee esiintymistä, puhutaan puolestaan esiintymispelosta". Näin ainakin ruotsiksi, mutta sv. tulee todennäköisesti olemaan scenskräck jatkossakin. 
https://www.varden.se/hitta/scenskrack-s
https://www.psykologiguiden.se/psykologilexikon/?Lookup=scenskr%C3%A4ck

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Säilytetään yläkäsitteenä pelko, mutta vaihdetaan käytettäväksi termiksi esiintymisjännitys ja ohjaustermiksi esiintymispelko.

Kihelmöivän jännittävän ja monivaiheisen äänestyksen jälkeen yllä mainittu ehdotus sai selkeästi enemmistön kannatuksen.
