### ISSUE TITLE
Kestävän kehityksen tavoite

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10999]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kestävän kehityksen tavoite

**Ehdotettu termi ruotsiksi**

målen för hållbar utveckling

**Ehdotettu termi englanniksi**

Sustainable Development Goal (SDG)

**Tarkoitusta täsmentävä selite**

YKn kestävän kehityksen tavoitteet, 17 kpl, jotka lyhennetään SDG (+tavoitenumero)
https://fn.se/globala-malen-for-hallbar-utveckling/
https://www.undp.org/sustainable-development-goals?utm_source=EN&utm_medium=GSR&utm_content=US_UNDP_PaidSearch_Brand_English&utm_campaign=CENTRAL&c_src=CENTRAL&c_src2=GSR&gclid=Cj0KCQiA4uCcBhDdARIsAH5jyUkGMREewA1BCj0-hgho7RkKmoKC59SGFiv0gbTEBc-O_YeoVQl7meUaAraTEALw_wcB

**Perustelut ehdotukselle**

YKn kestävän kehityksen tavoitteet maailmanlaajuinen termi, johon viitataan eri maiden ja organisaatioiden tavoitteissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [vastuullisuus](http://www.yso.fi/onto/yso/p24111)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:NBN:fi:amk-2022112323741

**Ehdottajan organisaatio**

Metropolian Ammattikorkeakoulu
**Termiehdotus Fintossa:** [Kestävän kehityksen tavoite](http://finto.fi/yse/fi/page/Y510999)

**Comment by mariaforsen** [comment]
Sv. mål för hållbar utveckling HT globala mål för hållbar utveckling, globala målen för hållbar utveckling, hållbara utvecklingsmål, Agenda 2030 
https://termipankki.fi/tepa/fi/haku/sdg
https://www.sanakirja.fi/custom/fi-en-sv/sdg
https://www.kth.se/om/miljo-hallbar-utveckling/utbildning-miljo-hallbar-utveckling/verktygslada/sustainable-development/fn-s-globala-mal-for-hallbar-utveckling-1.612059
https://maailma2030.fi/sv/hem/

**Comment by mirmaid** [comment]
_Kestävä kehitys & tavoitteet_ käytetty.

**Comment by tpalonen** [comment]
En vastusta vaikka onkin vähän ketjumainen ja yksilökäsitemäinen. Onhan sanastossa jo esim. maailmanperintökohteet, joka on niin ikään yhden organisaation (Unesco) lanseeraama ja administroima käsite.

**Comment by mirmaid** [comment]
Meillä on muuten sanastossa Agenda 21 ja Agenda 2000, voisi varmaan olla myös Agenda 2030? LCSH:ssa _Sustainable Development Goals_ on auktorisoitu yhteisönä.

**Comment by YSO-kokous** [comment]
**Päätös**

kestävän kehityksen tavoitteet, Agenda 2030 ohjaustermiksi.

**Comment by fantsby-m** [comment]
653:ssa näissä
https://melinda.kansalliskirjasto.fi/byid/018759704
https://melinda.kansalliskirjasto.fi/byid/018759707
