### ISSUE TITLE
mahicanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10990]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mahicanit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Mahicanit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9789518874976

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [mahicanit](http://finto.fi/yse/fi/page/Y510990)

**Comment by mariaforsen** [comment]
Sv. mohikaner HT mahikaner, mohikanindianer
https://id.kb.se/term/sao/Mohikaner

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Mahicanit

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q776280
