### ISSUE TITLE
depolymerointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10992]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

depolymerointi

**Ehdotettu termi ruotsiksi**

depolymerisaatio

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/181798?locale=lfi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [depolymerointi](http://finto.fi/yse/fi/page/Y510992)

**Comment by mariaforsen** [comment]
Sv.   depolymerisation HT depolymerisering
https://www.rikstermbanken.se/search?q=depolymerisation&s=termer
https://termipankki.fi/tepa/sv/s%C3%B6k/depolymerisation

**Comment by mirmaid** [comment]
Eli polymeerin pilkkominen monomeereiksi.

**Comment by jarmosaarikko** [comment]
RT **polymerointi** http://www.yso.fi/onto/yso/p19505  (vastakohta)
http://www.wikidata.org/entity/Q906487
- Wikidatassa YK on "kemiallinen reaktio"

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
