### ISSUE TITLE
Kestävyysraportointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#10997]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kestävyysraportointi

**Ehdotettu termi ruotsiksi**

Hållbarhet reporting

**Ehdotettu termi englanniksi**

Sustainability reporting

**Tarkoitusta täsmentävä selite**

Englannin kielen sana sustainability. ja siitä johdettu sustainability reporting. 

Kestävyys sanan suomenkielinen määrittely (kuten nyt) ei vastaa tähän näkökulmaan.

Mielellään olisi myös Kestävyys  (sana) määritelty erikseen (Vastaamaan Sustainability sanaa)

**Perustelut ehdotukselle**

Vakiintuva termi. Esim.. Suomen tilintarkastajat palkitsi tänä vuonna kestävyysraportoinnista:

https://tilintarkastajat.fi/toimintamme/kestavyysraportointikilpailu/

**Ehdotettu yläkäsite YSOssa (LT)**

 [vastuullisuus](http://www.yso.fi/onto/yso/p24111)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Vastuullisuusraportointi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:NBN:fi:amk-2022112323741

**Ehdottajan organisaatio**

Metropolian Ammattikorkeakoulu
**Termiehdotus Fintossa:** [Kestävyysraportointi](http://finto.fi/yse/fi/page/Y510997)

**Comment by mariaforsen** [comment]
Sv. hållbarhetsrapportering HT ansvarsrapportering
https://www.sitra.fi/julkaisut/polkuja-tavoitteelliseen-kestavyysraportointiin/

Nykytilanne kestävyys-termin osalta on tosiaan hankala monikielisyyden kannalta, koska nyt kestävyys=hållbarhet (resistens)=endurance, eli ei ihan tähän liittyvä käsite ruotsin ja englannin kohdalla.

**Comment by mirmaid** [comment]
Sanastossa on _ympäristöraportointi_, vaikuttaisivat olevan aika läheiset.

**Comment by mariaforsen** [comment]
Näiden välillä voisi varmaan olla RT?

"Kestävyysraportointi antaa kokonaiskuvan yhtiön ympäristövastuusta sekä sosiaalisesta ja taloudellisesta vastuusta. Kestävyysraportoinnista voidaan myös käyttää termiä ESG, joka tulee sanoista environment, social ja governance (hyvä hallintotapa)." 
/ https://sites.uwasa.fi/ssiteam/2022/04/06/mita-on-kestavyysraportointi-ja-miksi-se-on-tarkeaa-myos-pk-yrityksille/
https://fibsry.fi/ajankohtaista/kohti-maaramuotoista-kestavyysraportointia/
https://www.ey.com/fi_fi/assurance/laadukas-kestaevyysraportointi-avaa-yritykselle-uusia-ovia

"Ympäristöraportointia tehdään viranomaisille (kunta tai ELY-keskus) vuosittain ympäristölupien mukaisesti, mutta myös muille sidosryhmille osana yritysvastuuraportointia. Joskus raportointia tehdään tapauskohtaisesti esim. Asiakkaiden tai omistajien tarpeista johtuen. Ympäristöraportoinnissa esitetään yrityksen toiminnan tietoja liittyen mm. energian ja veden kulutukseen, hiilijalanjälkeen ja toiminnassa syntyneisiin jätteisiin. Ympäristöraportointi tehdään yleensä vuoden alussa, sillä ympäristöluvan mukaisen raportoinnin takaraja on helmikuun lopussa. "
/ https://ecobio.fi/ymparistoraportointi/
https://www.hel.fi/Helsinki/fi/asuminen-ja-ymparisto/ymparistonsuojelu/ymparistopolitiikka/raportointi/
https://termipankki.fi/tepa/fi/haku/ymp%C3%A4rist%C3%B6raportti

**Comment by fantsby-m** [comment]
EU:n kestävyysraportointidirektiivi CSRD tuli voimaan tammikuussa:

- https://finance.ec.europa.eu/capital-markets-union-and-financial-markets/company-reporting-and-auditing/company-reporting/corporate-sustainability-reporting_en
- https://eur-lex.europa.eu/legal-content/FI/TXT/HTML/?uri=CELEX:32022L2464

Joten tälle termille on varmaankin perusteet.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kestävyysraportointi_. Ohjaustermiksi _vastuullisuusraportointi_.
