### ISSUE TITLE
(the) long covid

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11004]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

(the) long covid

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

(the) long covid

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Täsmätermi

**Ehdotettu yläkäsite YSOssa (LT)**

 [koronavirukset](http://www.yso.fi/onto/yso/p29062)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [COVID-19](http://www.yso.fi/onto/yso/p38829)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 The Long Covid handbook / ‡c Gez Medinger & Professor Danny Altmann. 

**Ehdottajan organisaatio**

Outi Hintikka / Kirjastopalvelu
**Termiehdotus Fintossa:** [(the) long covid](http://finto.fi/yse/fi/page/Y511004)

**Comment by mariaforsen** [comment]
Mesh: Post-Acute COVID-19 Syndrome

Sv. långtidscovid HT postakut Covid-19 syndrom, långcovid, postcovid

https://mesh.kib.ki.se/term/D000094024/lngcovid

https://sv.wikipedia.org/wiki/Postcovid 
"[Socialstyrelsen](https://sv.wikipedia.org/wiki/Socialstyrelsen) rekommenderar likt internationella organ att benämningar som långtidscovid, långcovid eller postakut covid undviks då de kan indikera att en infektion fortsatt pågår utan att detta är säkerställt."

https://thl.fi/fi/web/infektiotaudit-ja-rokotukset/taudit-ja-torjunta/taudit-ja-taudinaiheuttajat-a-o/koronavirus-sars-cov-2/pitkittynyt-koronatauti-eli-long-covid

**Comment by tpalonen** [comment]
Suomeksi pitkittynyt koronatauti?
Ks. https://www.kielikello.fi/-/long-covid-eli-pitkittynyt-koronatauti
Ks. myös Marian THL-linkki yllä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _pitkittynyt koronatauti_.
