### ISSUE TITLE
Järvenpään ortodoksinen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11006]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Järvenpään ortodoksinen kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 Jumalansynnyttäjän kazanilaisen ikonin kirkko

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/w/index.php?title=J%C3%A4rvenp%C3%A4%C3%A4n_ortodoksinen_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018326498

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Järvenpään ortodoksinen kirkko](http://finto.fi/yse/fi/page/Y511006)

**Comment by mariaforsen** [comment]
Sv. Träskända ortodoxa kyrka

**Comment by jarmosaarikko** [comment]
Tällä on kyllä ihan nimikin:  Jumalansynnyttäjän Kazanilaisen ikonin kirkko - pitäisikö tämän olla päätermi?
- Lähde: [Helsingin ortodoksinen seurakunta](https://www.hos.fi/kirkot/jarvenpaa-jumalansynnyttajan-kazanilaisen-ikonin-kirkko/?area=all&church=J%C3%A4rvenp%C3%A4%C3%A4n%20kirkko&month=03)
- http://www.wikidata.org/entity/Q4207751
- Järvenpää Orthodox Church
- [Träskända ortodoxa kyrka](https://www.katolinen.net/min-faders-hus/20160528)

**Comment by mirmaid** [comment]
Näissä on vähän hajontaa, eikä ortodoksisten kirkkojen omilla verkkosivuilla nimessä ymmärrettävästi ole mukana ortodoksinen-sanaa. Mutta jos Kaunisniemen kirkko auktorisoitaisiin, niin tuskin nimellä _Apostoli Jaakobin ja Herran äidinäidin, pyhän Annan kuolonuneen nukkumisen muistolle pyhitetty kirkko_...
