### ISSUE TITLE
Pedersören kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11008]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Pedersören kirkko

**Ehdotettu termi ruotsiksi**

Pedersöre kyrka

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Peders%C3%B6ren_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018267611

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Pedersören kirkko](http://finto.fi/yse/fi/page/Y511008)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q7159141
