### ISSUE TITLE
ekologinen sosiaalityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11003]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ekologinen sosiaalityö

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

ecological social work

**Tarkoitusta täsmentävä selite**

https://doi.org/10.1093/acrefore/9780199975839.013.1166

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sosiaalityö](http://www.yso.fi/onto/yso/p3286)

**Ehdotetut temaattiset ryhmät**

 [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/009802165

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [ekologinen sosiaalityö](http://finto.fi/yse/fi/page/Y511003)

**Comment by mariaforsen** [comment]
Sv. ekologiskt socialt arbete HT ekosocialt arbete, ekologiskt socialarbete, grönt socialt arbete
https://studier.se/studier/introduktion-till-ekologiskt-socialt-arbete/
https://ethesis.helsinki.fi/repository/handle/123456789/39281?show=full

**Comment by mirmaid** [comment]
Sama kuin _ekososiaalinen sosiaalityö_? https://github.com/Finto-ehdotus/YSE/issues/4197

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _ekososiaalinen sosiaalityö_, ohjaustermiksi _ekologinen sosiaalityö_.
