### ISSUE TITLE
Ulrika Eleonoran kirkko (Kristiinankaupunki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11009]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Ulrika Eleonoran kirkko (Kristiinankaupunki)

**Ehdotettu termi ruotsiksi**

Ulrika Eleonora kyrka (Kristinestad)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 Kristiinankaupungin vanha kirkko

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Ulrika_Eleonoran_kirkko_(Kristiinankaupunki))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018267611

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Ulrika Eleonoran kirkko (Kristiinankaupunki)](http://finto.fi/yse/fi/page/Y511009)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q10708877
