### ISSUE TITLE
kantillaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11005]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kantillaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

cantillation

**Tarkoitusta täsmentävä selite**

"The musical or semi-musical chanting of sacred texts, prayers and so on by a solo singer in a liturgical context. The term primarily refers to such chanting in the Jewish Synagogue [- -], but is used also for the comparable public recitation of lessons and so on in the various Christian traditions and in other religious rites (e.g. those of Manicheism)."

**Perustelut ehdotukselle**

Tarvitaan kuvailussa; sopivaa asiasanaa ei ole vanhastaan.

**Ehdotettu yläkäsite YSOssa (LT)**

 [laulaminen](http://www.yso.fi/onto/yso/p2428), [liturginen musiikki](http://www.yso.fi/onto/yso/p24740)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 kantillointi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [latinalainen kirkkolaulu](http://www.yso.fi/onto/yso/p27549), [ortodoksinen kirkkomusiikki](http://www.yso.fi/onto/yso/p7860), [synagogamusiikki](http://www.yso.fi/onto/yso/p39659)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85019811), [Wikidata](https://www.wikidata.org/wiki/Q15990884)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018678596

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kantillaatio](http://finto.fi/yse/fi/page/Y511005)

**Comment by jtuohini** [comment]
Ja _Otavan ison musiikkitietosanakirjan_ määritelmä: "uskonnollisten tekstien lauluäänellä tapahtuva resitointi. Tällaista puhelaulua esiintyy laajalti eri uskontojen piirissä vaihtelevin muodoin. [- -] Kantillaatio-termiä käytettiin aiemmin pääasiassa synagogajumalanpalvelusten liturgisista resitaatioista [- -]. Nykyisin sanotaan kantillaatioksi myös vastaavaa "laululuentaa" eri kristillisissä kirkoissa. Gregoriaanisessa laulussa kantillaatio kuuluu ns. sidonnaismuotoihin ja sitä kutsutaan myös nimellä _accentus_."

Joten KT-muodoksi kävisi myös _laululuenta_ ja RT- tai jopa LT-suhteeksi **puhelaulu**.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

LT laulaminen
KT laululuenta, resitointi

**Comment by mariaforsen** [comment]
Sv. kantillation
https://id.kb.se/term/sao/Kantillation

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by tpalonen** [comment]
Saimme ehdotuksen @MUUSA-kokous :lta että ohjaustermit _resitointi_ ja _resitoiminen_ voisi poistaa _puhelaulu_-käsitteeltä ja varata _kantillaatio_-käsitteelle.

Kommenttini tähän: resitointi sanaa käytetään myös esim. folkloristiikan puolella. Kalevalaisia runonlauluja voi esimerkiksi resitoida. Ks. esim. https://melinda.kansalliskirjasto.fi/byid/002480390 Kantillaatio-termi tällaisissa tapauksissa taas olisi virheellinen. Tästä syystä säilyttäisin _resitointi_ ja _resitoiminen_ -termit myös _puhelaulu_-käsitteellä. Eli toisin sanoen ne voisivat ohjata sekä _puhelaulu_- että _kantillaatio_-käsitteisiin.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ohjaustermien resitointi ja resitoiminen säilyttämistä myös puhelaululla.

Ehdotus kantillaation yläkäsitteeksi: puhelaulu
Määritelmäehdotus kantillaatiolle: Uskonnollisten tekstien lauluäänellä tapahtuva puhelaulu.
