### ISSUE TITLE
nielurisat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11018]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nielurisat](http://www.yso.fi/onto/yso/p6043)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutettu monikkoon

**Perustelut ehdotukselle**

MeSH, yleinen kielenkäyttö

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Tämä siis on jo monikossa YSOssa
