### ISSUE TITLE
haihtuvat orgaaniset yhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11019]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[haihtuvat orgaaniset yhdisteet](http://www.yso.fi/onto/yso/p17386)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö lisätä ohjaustermiksi myös NMVOC ja ei-metaaniset haihtuvat orgaaniset yhdisteet

**Perustelut ehdotukselle**

https://www.ymparisto.fi/fi-fi/ilmasto_ja_ilma/ilmansuojelu/Ilman_epapuhtaudet_Suomessa/Haihtuvat_orgaaniset_yhdisteet

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. HT NMVOC tai erillisenä terminä lättflyktiga organiska ämnen utom metan HT NMVOC
https://www.rikstermbanken.se/search?q=NMVOC&s=termer
https://www.stat.fi/meta/kas/nmvoc_sv.html
https://utslappisiffror.naturvardsverket.se/sv/Amnen/Andra-gaser/Flyktiga-organiska-amnen/

**Comment by mirmaid** [comment]
https://termipankki.fi/tepa/fi/haku/nmvoc

**Comment by mirmaid** [comment]
Kerran Melindassa _NMVOC-yhdisteet_.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta. Seurataan käytön mahdollista lisääntymistä tulevaisuudessa.
