### ISSUE TITLE
anekdoottit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11017]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

anekdoottit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

anecdotes

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tällä hetkellä hakusana anekdootit ohjaa kaskuihin, mutta kasku on ihan eri asia eikä sitä voi käyttää kirjoissa jotka koostuvat anekdooteista eli tarinoista esimerkiksi jääkiekon maailmasta.

Wikipediasta:

"Anekdootti on lyhyt ja mahdollisesti todentamaton, usein viihteellinen tai humoristinen, tarina henkilöstä tai tapahtumasta."

"Kasku ja sutkautus tarkoittavat hauskaa kertomusta. Kaskun ja vitsin karkea ero on siinä, että kasku on sijoitettu todelliseen aikakauteen ja siinä esiintyvät usein todelliset, tunnetut henkilöt, kun taas vitsissä tapahtumapaikkaa ja -aikaa ei määritellä tarkasti ja henkilöt ovat keksittyjä karikatyyrejä. Suomessa suosittu kaskuissa esiintyvä henkilö on esimerkiksi presidentti Urho Kekkonen."

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kaskut](http://www.yso.fi/onto/yso/p11410)

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85004931.html), [Wikipedia](https://fi.wikipedia.org/wiki/Anekdootti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Beauties : hockey's greatest untold stories /  James Duthie 978-1-4434-6077-4  

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [anekdoottit](http://finto.fi/yse/fi/page/Y511017)

**Comment by mariaforsen** [comment]
Sv. anekdoter / eng. anecdotes on jo sanastossa =fi. kaskut
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_b7d6674bbc60f1eb8b09f99d0ee7e212&list_id=1&keyword=kasku&word=kasku

https://termipankki.fi/tepa/fi/haku/kasku
https://termipankki.fi/tepa/fi/haku/anekdootti

https://www.kielitoimistonsanakirja.fi/#/kasku?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/anekdootti?searchMode=all

**Comment by tpalonen** [comment]
Ainakaan englanniksi huumori ei painotu anedcote-termissä erityisen vahvasti. Eli jos otetaan anekdootit sanastoon niin ehkä pitää vaihtaa tuo kaskut-käsitteen enkkuvastine. _"Occasionally humorous"_, sanoo Wikipedian Anecdote-artikkeli.
https://en.wikipedia.org/wiki/Anecdote
Merriam Webster: anecdote: _"a usually short narrative of an interesting, amusing, or biographical incident"_
https://www.merriam-webster.com/dictionary/anecdote
Collins Cobuild Dictionary (1987): anecdote: _"An anecdote is a short, entertaining account of something that has happened, usually to the person telling it. E.g. She told him anecdotes about the hospital and the patients. He followed this up with a few horrifying anecdotes from his own past."_

**Comment by krinay** [comment]
Kaskuun/anekdoottiin perinteen- ja kirjallisuuden lajina liittyy jossakin määrin huumori, kuten edellä linkitetyistä Tieteen termipankin määrittelyistä käy ilmi.  Yleisessä kielenkäytössä anekdootilla saatetaan viitata muunkinlaiseen juttuun, mutta on ongelmallista, jos YSOon otetaan kovin sumea määritelmä. (Vrt. termi _myytti_, jolla on uskontotieteellisessä ja folkloristisessa tutkimuksessa varsin erilainen merkitys kuin toisinaan yleisessä kielenkäytössä. YSOssa ongelmaa ei tässäkään ole.)

LCSH ja SAO ovat samoilla linjoilla kuin YSO tällä hetkellä:
LCSH https://id.loc.gov/authorities/subjects/sh85004931.html (_Anecdote_. Variants: Ana, Facetiae, Humor. BT Biography, Wit and humor) 
SAO https://id.kb.se/term/sao/Anekdoter (_Anekdoter_. Bredare: Biografier, Humor)

Oikeastaan anekdooteilla tarkoitetaan nimenomaan _henkilökaskuja_ eli tunnettuun ihmiseen tai stereotyyppiseen henkilöhahmoon liittyvää kaskua. Muunkinlaisia kaskuja on. Mutta en tiedä, onko tätä erottelua mahdollista tehdä ruotsiksi (skämthistoria ja anekdot???) tai englanniksi (jests tai Schwänke ja anecdote???).

**Comment by mariaforsen** [comment]
Skämthistoria voi olla mikä tahansa hauska tarina, ei siis välttämättä ole nimenomaan kasku, tämä tilanne johtaisi siihen että kaskut-sana voisi tulla mihin tahansa vitsikkäiden tarinoiden tietueisiin. Kannatan siis että toinen näistä hyväksytään ohjaustermiksi. Vastaavalla tavalla tehtiin kun ruotsiksi viimeksi ehdotettiin erillistä kertomuksiin liittyvää termiä, mutta suomeksi ei ollut vastaavaa. 
https://svenska.se/tre/?sok=sk%C3%A4mthistoria&pz=8

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: kasku: leikillinen pikku juttu, anekdootti; vitsi.

Voisiko anekdootit ohjata myös _kertomukset_-käsitteeseen?

**Comment by jarmosaarikko** [comment]
Wikipediassa
-  nämä on yritetty erotella  [Anekdootti](https://fi.wikipedia.org/wiki/Anekdootti) - [Kasku](https://fi.wikipedia.org/wiki/Kasku)

Wikidatassa:
- **kasku** - termiksi on pantu kasku kaikilla kielillä ja yläkäsitteeksi vitsi ilman viittauksia anekdootteihin, joten en ehkä mappaisi tähän ilman muutoksia: http://www.wikidata.org/entity/Q11870258
- **anekdootti** - on mapattu YSOon käsitteeseen [kaskut](http://www.yso.fi/onto/yso/p11410) 
- **vitsi** (skämt|joke)  http://www.wikidata.org/entity/Q131138 - mapattu YSO käsitteeseen [pilailu](http://www.yso.fi/onto/yso/p20641) (skämt|joking)
- on tämmöinenkin **anecdote joke** (Russian joke) http://www.wikidata.org/entity/Q2374151

Wikidata-mappaukset pitäisi ehkä tarkistaa ja korjata.

**Comment by tpalonen** [comment]
Nyt muistin, että sanastossa on myös historialliset tarinat, jolle mahdollisesti tulossa ohjaustermi historialliset kertomukset. Tässäkin vähän päällekkäisyyden riskiä anekdoottien kanssa. Vrt yllä mainitsemani Collins-sanakirjan määritelmä: _"An anecdote is a short, entertaining account of something that has happened.."_ Eli jos anekdootit otetaan sanastoon niin varmaan pitäisi lisätä näille käsitteille huomautuksia, joissa viittaukset muihin likeisiin käsitteisiin.

Anekdootissa on se etu, että jos ajatellaan taviskäyttäjää / -tiedonhakijaa niin se on ihan kätevä yleiskielinen sana, jota näkee nykyisin käytettävän ja on siinä mielessä moderni. Vrt. esim. kaskut, joka ainakin omasta mielestäni on aika lailla väistymässä oleva termi yleiskielessä. Ja vrt. esim. kronikaatit, joka on enemmän perinteentutkijain erikoissanastoa.

Eli ottaisin anekdootit ohjaustermiksi ainakin ellei sitten ihan omaksi käsitteekseen.

**Comment by krinay** [comment]
Anekdootit on jo ohjaustermi (KÄYTÄ kaskut). 

Kaskut, anekdootit (eli henkilökaskut), historialliset tarinat ja kronikaatit ovat tosiaan perinnelajeja, ja pidän myös folkloristista ja kirjallisuudentutkimuksen aspektia tärkeänä YSOssa.

Ymmärrän hyvin tarpeen saada anekdootti päätermiksi, mutta ongelma syntyy käännöksistä ruotsiksi ja englanniksi. Anekdootti ei voi korvata kaskua (eli kasku ei voi olla ohjaustermi), koska kaikki kaskut eivät ole henkilökaskuja eli anekdootteja. Sen sijaan anekdootti voisi olla kaskujen alakäsite, jos löydettäisiin sopivat käännökset. Onko niin, että tällaisesta mallista tulisi sotkua:

kaskut / skämthistorier [englanniksi jests (narrative) tms.]
ST anekdootit / anekdoter
RT vitsit / vitsar

**Comment by tpalonen** [comment]
Äh joo. Onpas tässä nyt kaikkea. Toki folkloristiikka ja kirjallisuudentutkimus tärkeitä käyttöaloja myös YSOlle. Henkkoht olen kuitenkin sitä mieltä että anekdootti on kaskua laajempi käsite, tai vain osittain päällekkäinen sen kanssa. Eli tuo anekdootit > kaskut -ohjaus on mielestäni vähän tuollainen laajemmasta kapeampaan ohjaus. Ehkä anekdootit voisi ohjata johonkin muuhunkin käsitteeseen, jos ei oteta omana käsitteenään?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11017#issuecomment-1456189793

**Comment by mariaforsen** [comment]
Kuten yllä kommentoin, niin skämthistorier ei toimi ratkaisuna kaskut-käsitteelle. En kyllä tiedä millaisia termejä voisi keksiä ruotisksi, jos nämä termit olisivat molemmat erillisinä?

**Comment by fantsby-m** [comment]
> Kielitoimiston sanakirja: kasku: leikillinen pikku juttu, anekdootti; vitsi.
> 
> Voisiko anekdootit ohjata myös _kertomukset_-käsitteeseen?

Myös KTS:
anekdootti: pikku tarina, juttu, kasku. 

Mutta kaikki kaskut eivät ole anekdootteja eivätkä kaikki anekdootit kaskuja.

Yksittäisten tieteenalojen - kuten kirjallisuustiede tai folkloristiikka - huomioiminen on tärkeää, mutta onko perusteltua rajata yleisasiasanastossa yleiskielinen merkitys (osittain) pois.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kaskut ja anekdootit_. Lisätään ohjaustermit.
