### ISSUE TITLE
lehtikirjoitukset (SLM)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11013]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lehtikirjoitukset (SLM)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Toisinaan tulee kuvailtavaksi kirjoja, joiden sisältö koostuu sellaisenaan sanoma- tai aikakauslehdissä julkaistuista artikkeleista.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018662505

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [lehtikirjoitukset (SLM)](http://finto.fi/yse/fi/page/Y511013)

**Comment by ilona-x** [comment]
aiempi 09/2020 käsitelty ehdotus:  lehtikirjoitukset #1978

**Comment by mirmaid** [comment]
Lehtikirjoituskokoelmat KT lehtikirjoitukset (kokoelmat)

**Comment by mariaforsen** [comment]
Sv. tidningsartikelsamlingar HT tidningsskriverier (samlingar) 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_f1c3090add26ea9308ba3edd95f99f6a&list_id=1&keyword=lehtikirjoitus&word=lehtikirjoitus
