### ISSUE TITLE
siviilipalvelusmiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11011]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[siviilipalvelusmiehet](http://www.yso.fi/onto/yso/p22935)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Parempi termi: siviilipalvelusvelvolliset

**Perustelut ehdotukselle**

Yritetään välttää kyseisen termin käyttöä Siviilipalveluskeskuksella, koska laki sallii siviilipalveluksen suorittamisen myös (väestörekisterimääritelmän mukaisille) naisille. Suosittelisin yleiseen käyttöön siviilipalvelusvelvollista, koska se on sukupuolineutraali ilmaisu.

**Ehdottajan organisaatio**

Koulutusasiantuntija Vihtori Kylänpää, Siviilipalveluskeskus

**Comment by jarmosaarikko** [comment]
Siviilipalveluslaki https://finlex.fi/fi/laki/ajantasa/2007/20071446#L1P2  2§ 1 mom.
- käyttää termiä **siviilipalvelusvelvolliset**, joten kannatettava muutos!
- Ruotsiksi **civiltjänstgörare**
- Englanniksi vähän monimutkaisempi termi. Lain [käännös](https://finlex.fi/en/laki/kaannokset/2007/en20071446_20130940.pdf) käyttää muotoa:  **persons liable for non-military service** (mon.)

**Comment by jarmosaarikko** [comment]
tälle on nyt oma http://www.wikidata.org/entity/Q116995131
