### ISSUE TITLE
kaivohuoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11015]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaivohuoneet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

pump rooms

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Espoon terveyslähde

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kaivohuoneet](http://finto.fi/yse/fi/page/Y511015)

**Comment by mariaforsen** [comment]
Sv. brunnshus
https://sv.m.wiktionary.org/wiki/brunnshus
https://svenska.se/saob/?sok=brunnshus&pz=4#U_B4207_155482

**Comment by mirmaid** [comment]
https://www.oxfordlearnersdictionaries.com/definition/english/pump-room

**Comment by ilona-x** [comment]
Täältä löytyi tietoa tuosta ehdotuksessa mainitusta Espoon terveyslähteestä: https://web.archive.org/web/20070416011820/https://www.keskiespooseura.fi/sanomat/1-1990.htm

**Comment by LeKorsu** [comment]
Olisiko terveyslähteet (sv hälsobrunnar) laajemmin käyttökeltoisempi? Kaivohuoneet voisi olla ohjaustermi

**Comment by jarmosaarikko** [comment]
Kaivonhuonessa terveyslähde on siis rakennuksen sisällä?
Tämä Wikidatan käsite **pump room** on tosiaan tuo terveyslähteen juontipaikka ... http://www.wikidata.org/entity/Q4101440
Saksaksi Trinkhalle (Kuranlage) tai Brunnenhalle.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
