### ISSUE TITLE
salaattikasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11029]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[salaattikasvit](http://www.yso.fi/onto/yso/p10152)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

päätermiksi salaatti (salaattikasvit)

**Perustelut ehdotukselle**

lat. Lactuca sativa. Saadaan johdonmukaiset kielivastineet ja rajattu käyttö.

**Ehdottajan organisaatio**

YSO-työryhmä

**Comment by mariaforsen** [comment]
Eli tämä https://laji.fi/taxon/MX.40788 ja sv. trädgårdssallat, sallat (art), sallat (Lactuca sativa)

**Comment by jarmosaarikko** [comment]
Wikidatassa
- salaattikasvit http://www.wikidata.org/entity/Q9266
- lehtisalaatti http://www.wikidata.org/entity/Q83193 (eli Lactuca sativa)
Tässä oli mapattuna myös YSOn **keräsalaatti**, mutta Wikidatassa sille on eri käsite:  [jäävuorisalaatti](http://www.wikidata.org/entity/Q1310886) 
Kts myös 
- https://kasvikset.fi/kasvitieto/salaatit/bataviasalaatti/  Bataviasalaatti
  - (lactuca sativa var. capitata) Bataviat ovat salaattiristeytyksiä, oikeastaan tyypiltään rapeaa keräsalaattia
- https://kasvikset.fi/kasvitieto/salaatit/rapea-kerasalaatti/ **Rapea keräsalaatti**
  - (Lactuca sativa var. capitata)  Rapea keräsalaatti tunnetaan myös nimillä amerikansalaatti ja **jäävuorisalaatti**

**Comment by tpalonen** [comment]
Jarmon yllä esittämä YSO keräsalaatti-käsitteen linkityksen korjaus > Wikidata: https://www.wikidata.org/wiki/Q1310886
on nyt tehty sekä Wikidataan että YSOon.
