### ISSUE TITLE
nokkakala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11024]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nokkakala

**Ehdotettu termi ruotsiksi**

näbbgädda

**Ehdotettu termi englanniksi**

Garfish

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 6

**Ehdotettu yläkäsite YSOssa (LT)**

 [kalat](http://www.yso.fi/onto/yso/p901)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 Belone belone, nokkahauki

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Laji.fi](https://laji.fi/taxon/MX.53192), [wikipedia](https://fi.wikipedia.org/wiki/Nokkakala), [LCSH](http://id.loc.gov/authorities/subjects/sh85013070)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kartering av fisksamhällen och förekomst av plattfiskar och näbbgädda (Belone belone) på exponerade stränder på Åland 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [nokkakala](http://finto.fi/yse/fi/page/Y511024)

**Comment by mariaforsen** [comment]
Sv. näbbgädda HT horngädda
