### ISSUE TITLE
ympäristöjalanjälki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11026]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ympäristöjalanjälki

**Ehdotettu termi ruotsiksi**

miljöavtryck

**Ehdotettu termi englanniksi**

product environmental footprint 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ympäristöjalanjälki pyrkii yhdistämään elinkaariarvioinnin kuvaamat erilaiset ympäristövaikutukset ja erilaiset jalanjäljet

https://www.ymparisto.fi/fi-fi/kulutus_ja_tuotanto/tuotesuunnittelu_ja_tuotteet/elinkaariarviointi_jalanjaljet_ja_panostuotosmalli#Ymp%C3%A4rist%C3%B6jalanj%C3%A4lki

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 PEF

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [hiilijalanjälki](http://www.yso.fi/onto/yso/p21899)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-11-5156-9

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ympäristöjalanjälki](http://finto.fi/yse/fi/page/Y511026)

**Comment by mariaforsen** [comment]
Sv. miljöavtryck HT miljöfotavtryck, PEF, produktmiljöavtryck
https://www.eionet.europa.eu/gemet/sv/concept/15155

**Comment by LeKorsu** [comment]
Kysyin chatGPT:ltä hiilijalanjäljen ja ympäristöjalanjäljen eroa  =)
![image](https://user-images.githubusercontent.com/22166248/222417858-7d8b7c87-aa69-47bd-9e6c-53b237d87a28.png)
Selitä mitä eroa on hiilijalanjäljellä ja ympäristöjalanjäljellä
!

**Comment by annamarj** [comment]
Voisiko  olla 
KÄYTÄ ekologinen jalanjälki 
https://finto.fi/yso/fi/page/p15389

**Comment by ilona-x** [comment]
"Ympäristövaikutuksia on perinteisesti mitattu erilaisilla yhden aiheen jalanjäljillä kuten hiilijalanjälki, vesijalanjälki ja ekologinen jalanjälki. Uusi ympäristöjalanjälki ottaa huomioon yhteensä jopa 16 ympäristövaikutusluokkaa kuten hiilidioksidipäästöt, vedenkulutuksen sekä vaikutukset otsonikerrokseen ja rehevöitymiseen."
Lähde: https://www.syke.fi/fi-FI/Ajankohtaista/Uusi_ymparistojalanjalki_muuttaa_ymparis(47963)

**Comment by fantsby-m** [comment]
On EU-lainsäädännössäkin:
https://www.sttinfo.fi/tiedote/jachym-judl-ja-suvi-lehtoranta-eun-ymparistojalanjalki-miksi-siita-kannattaa-kiinnostua?publisherId=69819243&releaseId=69960294

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään määritelmä _ekologiselle jalanjäljelle_. Hyväksytään _ympäristöjalanjälki_.
