### ISSUE TITLE
kertomukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11022]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kertomukset](http://www.yso.fi/onto/yso/p24639)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM:ssä muutetaan suhde RT kertomakirjallisuus --> LT kertomakirjallisuus

**Perustelut ehdotukselle**

Kaikki kertomukset ovat kertomakirjallisuutta, joten termin välisen suhteen pitäisi ilmaista kyseinen asia.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Tuhkimotarinat ylätasolle, RT kertomukset. Kertomukset YK kertomakirjallisuus.
