### ISSUE TITLE
sadut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11023]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sadut](http://www.yso.fi/onto/yso/p15564)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM:ssä poistetaan suhde RT kertomakirjallisuus.

**Perustelut ehdotukselle**

Jos sadut ovat kertomuksia ja kertomukset kertomakirjallisuutta, ei ylimääräistä RT-suhdetta tarvita hierarkian kahden eri tason välille. Liittyy aiempaan YSE-ehdotukseen, ks. https://github.com/Finto-ehdotus/YSE/issues/11022

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Kuinkas sitten suullinen kertomusperinne, onko se aina kirjallisuutta? YSO

**Comment by mirmaid** [comment]
Ok/SLM
