### ISSUE TITLE
salaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11028]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[salaatit](http://www.yso.fi/onto/yso/p9714)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne (ruokalajit)

**Perustelut ehdotukselle**

Menee sekaisin salaattikasvien kanssa.

**Ehdottajan organisaatio**

YSO-työryhmä

**Comment by mariaforsen** [comment]
Sv. sallader (maträtter)
