### ISSUE TITLE
Varuboden Areena

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11035]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Varuboden Areena

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [rakennukset](http://www.yso.fi/onto/yso/p1786)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Varuboden-areena)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Varuboden Areena : miten mahdottomasta tehtiin mahdollinen? 

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. Varuboden Arena

**Comment by LeKorsu** [comment]
Sama kommentti kuin Nokia Arenan kanssa, voiko käytettäväksi ottaa muodon ilman sponsorinimeä: esim. Kirkkonummen monitoimihalli. (Hartwall Areenakaan ei ole enää Hartwall Areena.)

**Comment by ilona-x** [comment]
Jos tämä ja Nokia Arena päätetään ottaa ilman sponsorinimiä, niin siinä tapauksessa pitäisi varmaan myös Hartwall Areena muuttaa Helsinki-halliksi. 

Ja Finnair Stadium ei myöskään ole enää aikoihin ollut tuolla nimellä https://fi.wikipedia.org/wiki/T%C3%B6%C3%B6l%C3%B6n_jalkapallostadion

**Comment by jarmosaarikko** [comment]
ohdotan omistajan mukaista nimeä:
KÄ **Kirkkonummen monitoimihalli** KT Varuboden Arena

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. Kirkkonummen monitoimihalli HT Kyrkslätt allaktivitetshall, Varuboden Arena
https://www.finder.fi/Keilahalli/Varuboden+Areena/Kirkkonummi/yhteystiedot/835128

**Comment by mirmaid** [comment]
Kirkkonummella on toinenkin monitoimihallina tunnettu halli, joten päädyttiin kuitenkin muotoon Varuboden Areena.
