### ISSUE TITLE
Luonetjärvi (Jyväskylä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11039]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Luonetjärvi (Jyväskylä)](http://www.yso.fi/onto/yso/p198837)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mihin tällä termillä on tarkoitus viitata?

Termin muoto viittaisi siihen, että tämä on alun perin otettu sanastoon tarkoittamaan jotain muuta kuin järveä.

Kyseessä ei kuitenkaan taida olla kylä. Aineistot näyttävät käsittelevän Luonetjärven varuskuntaa / varuskunta-aluetta. Varuskunnan nimi ilmeisesti nykyään Jyväskylän varuskunta https://fi.wikipedia.org/wiki/Jyv%C3%A4skyl%C3%A4n_varuskunta

**Perustelut ehdotukselle**

Linkattu Wikidataan Luonetjärvi-nimistä järveä käsittelevään artikkeliin.

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Korjataan viitteisiin soveltuvin osin Kanton Luonetjärven varuskunta. Muokataan auktoriteettia niin, että se viittaa järveen. Huomautus: _Järvi Jyväskylän Tikkakoskella, tarkoitettaessa varuskuntaa merkitään kohteeksi soveltuva Kanton yhteisö_.
