### ISSUE TITLE
uskontunnustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11038]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[uskontunnustukset](http://www.yso.fi/onto/yso/p12309)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-sanastoon

**Perustelut ehdotukselle**

Tarve uskontunnustuksia (Apostolinen uskontunnustus, Augsburgin tunnustus, Nikean uskontunnustus ym) sisältävien aineistojen kuvailuun.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Vrt. https://github.com/Finto-ehdotus/YSE/issues/6833

**Comment by mirmaid** [comment]
Hyväksytty/SLM. YK ei-fiktiiviset aineistot, RT tunnustuskirjat.

**Comment by mariaforsen** [comment]
Sv. trosbekännelser
