### ISSUE TITLE
hip hop

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11036]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hip hop](http://www.yso.fi/onto/yso/p14336)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan LT-suhde "popmusiikki" --> "osakulttuurit" ja vaihdetaan/lisätään ryhmä(ksi) "60 Sosiologia. Sosiaalipsykologia"

**Perustelut ehdotukselle**

Tällä hetkellä määritelmä on "Kollektiivinen käsite urbaanille kulttuurille ja taiteelle [- -]" eli ei yksinomaisesti musiikille toisin kuin sanaston hierarkia antaa ymmärtää. Vertaa myös LCSH:n termisuhde, jossa rap on varattu musiikinlajille, hip hop osakulttuurille, ja YSO:n vastaava "punk rock" ~ "punk (kulttuuri)".

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja lisätään **rap**-asiasanaan viittausmuodot _hip hop (musiikki)_ ja _hiphop (musiikki)_.

**Comment by tpalonen** [comment]
Jos rapille tulee altlabel hip hop (musiikki) niin ehkä olisi hyvä lisätä tämän käsitteen preflabeliin sulkutarkenne: "hip hop (kulttuuri)". 

Tilaisuuden tultua en voi myöskään olla kysymättä: joko aika olisi vihdoin kypsä preflabel-muutokselle, joka vastaa paremmin suomen kieltä ja suomenkielistä käyttöä: eli hip hop > hiphop? Ks. https://github.com/Finto-ehdotus/YSE/issues/8126

**Comment by MUUSA-kokous** [comment]
Ehdotetaan seuraavaa: muutetaan nykyinen termi muotoon hiphop-musiikki, rajataan määritelmä koskemaan musiikkia ja luodaan uusi käsite hiphop-kulttuurille, jonka yläkäsite on osakulttuurit (tälle nykyisen hip hop -käsitteen määritelmä).

Kielitoimiston sanakirjan hiphop-musiikin muokattu määritelmä: "hiphop-kulttuuriin liittyvää musiikkia, jolle on tyypillistä rumpukoneilla ja samplereilla luotavat biitit ja niiden päälle räppääminen".

Näiden välille assosiatiivinen suhde.

Kannatetaan kirjoitusasun muuttamista yhteenkirjoitettuun muotoon "hiphop". Samoin SLM:n puolella.

**Comment by jtuohini** [comment]
Eikö tuo Kielitoimiston sanakirjan määritelmä nyt osu aika lailla yksiin myös räpin kanssa? Eli muutosten jälkeen olisi hiphop-musiikin ja räpin ero YSO:ssa?

**Comment by tpalonen** [comment]
Kieltämättä hiphop-musiikki olisi vahvasti päällekkäinen rap-käsitteen kanssa. Kentällä ymmärtääkseni näillä on ainakin konnotaatioero; rap voi olla spontaania, improvisoitua ja termi korostaa räppäämistä, taituruutta, "aitoutta"; hiphopissa on kaupallisempi vivahde. Mutta en tiedä tarviiko yleissanastossa olla erikseen rap ja hiphop-musiikki, ellei sitten haluta rajata rap-käsitettä nimenomaan tähän puhelaulutekniikkaan, jolloin päätermiksi kuitenkin voisi sopia paremmin _räppääminen_.

**Comment by AuHo22** [comment]
Ei ole ykkösaluettani, mutta kun uusin silmin katselen, niin eikö voisi olla hiphop-kulttuuri samalla tavalla kuten on ravekulttuuri, goottikulttuuri ja jo mainittu punk (kulttuuri), esim.
https://www.kennedy-center.org/education/resources-for-educators/classroom-resources/media-and-interactives/media/hip-hop/hip-hop-a-culture-of-vision-and-voice/
https://fi.wikipedia.org/wiki/Hip_hop
Ja rap toimisi sitten musiikkiterminä (ehdotetut viittausmuodot: hip hop (musiikki) ja hiphop (musiikki)?) Sen huomasin että breakdance on myös YSOssa kirjoitettu erikseen break dance, mutta esim. kotuksen sanakirja: _hiphop-kulttuurista lähtöisin oleva akrobaattinen tanssi(tyyli), breikki; myös urheilulajina.
Oppilaat esittivät kevätjuhlassa breakdancea._

**Comment by mariaforsen** [comment]
SAOssa ja LCSHssa kaksi eri käsitettä, hip-hop ja rap (music): 
https://id.loc.gov/authorities/subjects/sh85111437.html
https://id.loc.gov/authorities/subjects/sh95009601.html

**Comment by tpalonen** [comment]
Kun puhutaan musiikkigenrestä niin tämä hiphop vs. rap on kyllä hankala. Näitä käytetään ristikkäin, pientä konnotaatioeroa näissä on kuten edellä yritin avata. Kuitenkin molempia käytetään ja hiphop / hip hop on musiikistakin puhuttaessa hieman enemmän käytetty maailmalla kuin rap. Tässä pientä listaa siitä, kumpaa termiä isot musiikkimediat käyttävät genre-/kategoriaterminä:

Pitchfork: rap
All Music Guide: rap
The Source: hip hop
Vibe: hip hop
XXL: hip hop
Rolling Stone: hip hop
Billboard charts: hip hop
The Wire: hip hop

Eli jos sanastossa on vain yksi käsite musiikille niin suosittaisin siinä tapauksessa käytettäväksi termiksi muotoa hiphop-musiikki, tai hiphop (musiikki).

Edit: Englanniksi esiintyy myös kirjoitusmuotoja hip-hop ja hiphop.

**Comment by YSO-kokous** [comment]
**Päätös**

Odotetaan MUUSAn kantaa.

**Comment by MUUSA-kokous** [comment]
Hiphop ja rap ovat monelta osin päällekkäisiä, mutta eivät aina, joten käsitteiden yhdistäminen yksinkertaistaisi asiaa liikaa. Esimerkiksi instrumentaalinen hiphop ei ole rapia, ja toisaalta rapmusiikin elementtejä käytetään muussakin kuin hiphop-musiikissa. Muusa pitäytyy siis kannassaan pitää käsitteet erillään (ks. https://github.com/Finto-ehdotus/YSE/issues/11036#issuecomment-1730964079).

**Comment by mirmaid** [comment]
Tulkitsenko kommentteja nyt oikein, jos luen, että termimuoto muuttuu > hiphop, ei tarkennetta tai uusia termejä? Pysyykö hiphopin määritelmä ennallaan?

**Comment by mirmaid** [comment]
Hyväksytään Muusan ratkaisu.

**Comment by mariaforsen** [comment]
Sv. -hiphopmusik HT hiphop (musik), hiphop-musik
-hiphopkultur HT hiphop (kultur), hiphop-kultur
https://id.kb.se/find?q=hiphop
https://svenska.se/tre/?sok=hiphopkultur&pz=1

**Comment by mirmaid** [comment]
SLM: hiphop
