### ISSUE TITLE
laastarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11040]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laastarit

**Ehdotettu termi ruotsiksi**

plåster

**Ehdotettu termi englanniksi**

bandages; plasters

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Laastareita käytetään paljon arkipäivässä, ja on hassua, ettei kyseistä sanaa tai edes sen "sukulaissanoja" tuntunut löytyvän. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [haavanhoito](http://www.yso.fi/onto/yso/p29704)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 sidetarpeet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Laastari)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/186364

**Ehdottajan organisaatio**

Åbo Akademis bibliotek
**Termiehdotus Fintossa:** [laastarit](http://finto.fi/yse/fi/page/Y511040)

**Comment by ilona-x** [comment]
KAUNOssa: **laastarit** http://www.yso.fi/onto/kauno/p6539

FinMeSHissä tarkempi termi: **lääkelaastarit** http://www.yso.fi/onto/mesh/D057968
TEROssa: **nikotiinilaastarit** http://www.yso.fi/onto/tero/t31746

**Comment by LeKorsu** [comment]
Pitäisikö ottaa kaikki kolme?
laastarit (jos tarvitaan sulkutarkenne niin haavanhoito)
lääkelaastarit
nikotiinilaastarit

**Comment by jarmosaarikko** [comment]
yläkäsite ei kai voi olla toimintaa (haavanhoito), vaan esim.
YK sairaanhoitotarvikkeet http://www.yso.fi/onto/yso/p15919

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _laastarit_ ja _lääkelaastarit_. Lisätään ohjaustermejä.

**Comment by mariaforsen** [comment]
Sv. 
-plåster HT sårplåster
-läkemedelsplåster HT medicinplåster, transdermala plåster 
https://www.fimea.fi/documents/542801/0/Ohjeita+turvalliseen+l%C3%A4%C3%A4kehoitoonSV.pdf
https://www.hsy.fi/sv/avfall-och-atervinning/avfallsguide/jatteet/medicinplaster/
https://mesh.kib.ki.se/term/D057968/transdermal-patch
https://www.sanakirja.fi/custom/fi-en-sv/l%C3%A4%C3%A4kelaastari
