### ISSUE TITLE
palmoplantaarinen keratoderma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11042]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

palmoplantaarinen keratoderma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/342842

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [palmoplantaarinen keratoderma](http://finto.fi/yse/fi/page/Y511042)

**Comment by mariaforsen** [comment]
Sv. palmoplantar keratoderma HT palmoplantar keratos, keratos på handflator och fotsulor, PPK /mesh

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D007645

Lääketieteen termit: käden ja jalan sarveisihoisuus | keratooseja joille ovat ominaisia kämmenten ja jalkapohjien paksuntumat

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q7128426
