### ISSUE TITLE
järjestöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11044]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[järjestöt](http://www.yso.fi/onto/yso/p1393)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sosiaalialalla on vakiintunut käännös järjestöistä (http://www.yso.fi/onto/yso/p1393) 'non-profit organizations' käsitteen associations sijaan. Voisiko se olla myös YSO:ssa käsitteen yhtenä käännöksenä.

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

Diakonia-amk

**Comment by mariaforsen** [comment]
TEPA: 

fi        yhdistys
sv       förening
en      association
määritelmä
julkisen tehtävän tai aatteellisen päämäärän perusteella kokonaisuuden muodostava yhteisö
huomautus
Yhdistyksiä ovat aatteelliset, julkisoikeudelliset ja taloudelliset yhdistykset. Yhdistykset voivat olla rekisteröityjä tai rekisteröimättömiä. Yhdistysrekisteriin merkitään ainoastaan aatteelliset yhdistykset. Vuonna 2013 kaupparekisteriin oli merkittynä yksi taloudellinen yhdistys.
Käsitekaaviot: Organisaatiot, Yhdistykset ja Toiminnan päättyminen.

Patentti- ja rekisterihallituksen sanasto (TSK 54, 2018)

Sv. förening (sovittu silloin kun käsiteltiin järjestöt-termiä ongelmana käännöksen kannalta). Tämä vastine viittaa oikeastaan ohjaustermiin "yhdistykset". Järjestöt+organisaatiot=sv. organisationer.

**Comment by ilona-x** [comment]
ehdotuksessa mainittu non-profit organisations on nyt ohjausterminä käsitteelle 
**yleishyödylliset yhteisöt** http://www.yso.fi/onto/yso/p4610
