### ISSUE TITLE
nesteytetty biokaasu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11049]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nesteytetty biokaasu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Opinnäytetyön aihe

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [nesteytetty biokaasu](http://finto.fi/yse/fi/page/Y511049)

**Comment by mariaforsen** [comment]
Sv. flytande biogas HT kondenserad biogas, LBG
https://www.rikstermbanken.se/search?q=flytande+biogas&s=termer

**Comment by ilona-x** [comment]
Polttoaineluokituksessa 
nesteytetty biometaani (LBG)
https://www.stat.fi/fi/luokitukset/polttoaineet/?code=22.30.60

**Comment by ilona-x** [comment]
toinen ehdotus ilmeisesti samasta opinnäytteestä: biometaani https://github.com/Finto-ehdotus/YSE/issues/11048

**Comment by jarmosaarikko** [comment]
RT  http://www.yso.fi/onto/yso/p29068  nesteytetty maakaasu (LNG) 
Wikidata http://www.wikidata.org/entity/Q84297230

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
