### ISSUE TITLE
keskiaasiankoira

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11041]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

keskiaasiankoira

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/346442

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [keskiaasiankoira](http://finto.fi/yse/fi/page/Y511041)

**Comment by mariaforsen** [comment]
Sv. sredneasiatskaja ovtjarka HT sredneasiatskaja ovcharka, centralasiatisk ovtjarka, centralasiatisk herdehund, centralasiatisk ovcharka, mellanasiatisk ovtjarka
https://www.skk.se/globalassets/dokument/rasdokument/ras-sredneasiatskaja-ovtjarka.pdf
http://www.ovcharkaklubben.se/?page_id=131
https://www.kennelliitto.fi/lomakkeet/championatbestammelser-i-finland-2022
https://www.skk.se/sv/hundraser/sredneasiatskaja-ovtjarka/

**Comment by mirmaid** [comment]
https://www.kennelliitto.fi/files/keskiaasiankoira

**Comment by jarmosaarikko** [comment]
- http://www.wikidata.org/entity/Q38570
   - Central Asian Shepherd Dog
   - KT Alabai, CAO, Central Asia Ovcharka, Central Asian Shepherd
- https://fi.wikipedia.org/wiki/Keskiaasiankoira
