### ISSUE TITLE
Jurvansalo (Viitasaari)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11045]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Jurvansalo (Viitasaari)](http://www.yso.fi/onto/yso/p123519)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennus tarpeen?

**Perustelut ehdotukselle**

Ruotsiksi on ollut huomautus siitä että viittaa sekä saareen että kylään, mutta onko näin, ja mihin näistä se oikeastaan viittaa? Kartalla saari näyttää olevan erillään kylän keskustasta ainakin. Tarvitaanko siis molemmat erikseen?

**Ehdottajan organisaatio**

ALLFO-orter

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Jurvansalo
https://fi.wikipedia.org/wiki/Jurvansalo_(kyl%C3%A4)

Jurvansalo on myös saaren nimi. Kyseinen saari sijaitsee Hännilänsalmen pohjoispuolella, kun taas kylän pääosa sijaitsee salmen eteläpuolisella alueella mantereella. https://pikkasenparempiakylia.fi/jurvansalo/

Melindassa vain yksi viite. Nämä ovat kyllä ihan vierekkäin, joten sama aineisto voi hyvin käsitellä molempia.

**Comment by mirmaid** [comment]
Ei muutoksia.
