### ISSUE TITLE
Pello

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11047]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pello](http://www.yso.fi/onto/yso/p105479)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennus tarpeen vai onko ok että Pello viittaa sekä kuntaan että kylään?

**Perustelut ehdotukselle**

Näillä on tietysti eri maantieteellinen "kattavuus" ja Pello on myös Ruotsin puolella..

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Tämänkaltaisia tapauksia on YSO-paikoissa varmaan enemmänkin, kun YSAn aikaan ohje on ollut:

> E. Kylän tai kaupunginosan nimi on sama kuin kunnan/kaupungin nimi
> 
> esim. Pihtipudas on sekä kunta että kylä Pihtiputaalla, tehdään näin
> 
> 151 Pihtipudas

**Comment by mariaforsen** [comment]
NE: "Byn delas sedan 1809 av riksgränsen i svenska Pello och finska Pello." Ruotsissa se on vain kylä, Suomessa tietty kuntakin.

**Comment by mirmaid** [comment]
vrt. Alatornio, tarkenteet nyt valtioita, tällä hetkellä kumpikaan ei ole itsenäinen kunta.

Pello (Suomi) ja Pello (Ruotsi, Ylitornio), huom. tässäkin historiakysymys. vrt. myös luovutettu Karjala, esim. Salla.
