### ISSUE TITLE
biometaani

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11048]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

biometaani

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Opinnäytetyön aihe

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [biometaani](http://finto.fi/yse/fi/page/Y511048)

**Comment by mariaforsen** [comment]
Sv. biometan
https://www.rikstermbanken.se/search?q=biometan&s=termer

**Comment by LeKorsu** [comment]
Tarvitsee varmaankin jotain selitystä, miten biometaani eroaa biokaasusta. Itselleni oli ainakin epäselvää ennen kuin luin tätä, enkä siltikään ole varma ymmärsinkö.
https://biokierto.fi/biokaasu/tuotanto/
Biometaani on yhteisnimitys enimmäkseen metaanista koostuville ja biologisesta materiaalista tuotetuille kaasuille. Biokaasua voidaan tuottaa mädättämällä kaikesta orgaanisesta jätteestä paitsi puusta ja muusta paljon ligniiniä sisältävästä aineksesta. Puusta erotettu selluloosa on kuitenkin mahdollista mädättää. Biometaania voidaan tuottaa puuaineksesta termisellä kaasutuksella.

**Comment by ilona-x** [comment]
Polttoaineluokitus 2020 antaa joitain määritelmiä:
https://www.stat.fi/fi/luokitukset/polttoaineet/polttoaineet_1_20200101/?code=321&name=Biokaasu
https://www.stat.fi/fi/luokitukset/polttoaineet/polttoaineet_1_20200101/?code=3214&name=Biometaani

Mutta näköjään tuo luokitus on jo ehtinyt muuttua, eikä siinä ole noita määritelmiä. Polttoaineluokitus 2022:
https://www.stat.fi/fi/luokitukset/polttoaineet/?code=22.30&name=Biokaasut

**Comment by mirmaid** [comment]
Ilmeisesti biometaani on biokaasua, josta on poistettu hiilidioksidi ja ns. hivenkaasut. https://www.europeanbiogas.eu/about-biogas-and-biomethane/

Biometaani on siis metaania, ja bio viittaa tähän tuotanto- ja jalostusprosessiin (ei tavallisen biokaasun sisältämään metaaniin tai luonnossa esiintyvään metaaniin).

**Comment by jarmosaarikko** [comment]
jos ja kun on selvästi eri käsite ja tärkeä hiilineutraaliuden tavoittelussa, niin ok.
**biometaani**  sv: biomethane en:biomethane
YK biokaasu

Määritelmä: Biomethane is the purified form of raw biogas and can be used as a natural gas substitute. It is one of the main renewable gases of the future and available today to decarbonise the EU's energy system. Lähde: https://energy.ec.europa.eu/topics/renewable-energy/bioenergy/biomethane_en

Wikidata http://www.wikidata.org/entity/Q2622192
- tuolla on ruotsiksi Bio-SNG ja englanniksi "Renewable natural gas" mutta ainakin tuo eng sivu käsittelee samaa asiaa eli on vaihtoehoinen termi
  - _**Renewable natural gas (RNG)**, also known as **sustainable natural gas (SNG**) or **biomethane**, is a [biogas](https://en.wikipedia.org/wiki/Biogas) which has been upgraded to a quality similar to [fossil](https://en.wikipedia.org/wiki/Fossil_fuel) [natural gas](https://en.wikipedia.org/wiki/Natural_gas) and having a [methane](https://en.wikipedia.org/wiki/Methane) concentration of 90% or greater_
  - _**Bio-SNG** SNG står för Subsitute Natural Gas, på svenska används ibland benämningen syntetisk [naturgas](https://sv.wikipedia.org/wiki/Naturgas)._

**Comment by jarmosaarikko** [comment]
Finlexistä löytyi yksi maininta. 
Laki liikenteessä käytettävien vaihtoehtoisten polttoaineiden jakelusta [478/2017 3§](https://finlex.fi/fi/laki/ajantasa/2017/20170478#P3) 
- 3 § Määritelmät
   - 3 ) _vaihtoehtoisella polttoaineella_ seuraavia polttoaineita tai voimanlähteitä, joilla korvataan ainakin osittain fossiilisen öljyn käyttö liikenteen energianlähteenä ja joilla on mahdollista parantaa liikenteen ympäristösuorituskykyä:
      - e ) maakaasu, mukaan lukien **biometaani**, kaasumaisessa ja nesteytetyssä muodossa;

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
