### ISSUE TITLE
SLM/mukaelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11052]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM/mukaelmat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kaivattaisiin määritelmää  SLM-sanastoon samoin kuin myös rinnakkaisteokselle.

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Parallel_novel
Voivat sekaantua keskenään.
YSOn ohjaustermit:  uudelleenkirjoitukset/ versiot
SLM-ohjaustermit: adaptaatiot/ versiot
Onko myös rinnakkaisteos uudelleenkirjoitus, mutta usein teoksessa esiintyvän toisen henkilön näkökulmasta?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kuvailukysymys: "Tässä kerrotaan Alcottin Pikku naisia -kirjan tapahtumista uudesta näkökulmasta, eli perheen äidin. Tätä kutsutaan sekä kirjan kannessa että liepeessä mukaelmaksi, eli ”a retelling of Louisa May Alcott’s Little Women”."
Myös https://en.wikipedia.org/wiki/Parallel_novel ks. Examples:
March (2005) by Geraldine Brooks parallels Little Women (1868).[8]

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mariaforsen** [comment]
Kannatan määritelmää tms. ainakin rinnakkaisteoksille. Omarbetningar (fi. mukaelmat) on ruotsiksi hyvin vakiintunut ja selkeä termi, mutta parallellverk-termi (fi. rinnakkaiseteokset) on epäselvä, eikä sillä termillä ole mitään vakiintunutta määritelmää ruotsiksi.

**Comment by AuHo22** [comment]
Joitain mainintoja rinnakkaisteoksista:
https://tuulevi.wordpress.com/2016/02/18/kate_atkinson_havityksen_jumala/
https://www.nidekauppa.fi/tuote/louis-edouard-naisen-taistelut-ja-muodonmuutokset/

https://en.wikipedia.org/wiki/Sequel ->
Parallels, paraquels, or sidequels are stories that run at the same point in time as the original story. For instance, three different novels by John Morressy — Starbrat (1972), Stardrift (1973; also known as Nail Down the Stars), and Under a Calculating Star (1975) — involve different lead characters, mostly in different places, but overlap at one dramatic event to which each novel provides a different perspective. Jne.

**Comment by mirmaid** [comment]
Myös Harold Fryn odottamaton toivioretki ja Miss Queenie Hennessyn rakkauslaulu - rinnakkaisteokset, sama kirjoittaja

**Comment by mirmaid** [comment]
Kirjastopalvelu laatii määritelmäehdotuksen rinnakkaisteokset-termille, KAUNO-ryhmä kommentoi.

**Comment by jtuohini** [comment]
Mukaelma on "[t]eos, joka on muokattu jotain muuta kuin alkuperäistä tarkoitusta, käyttöä tai viestintävälinettä varten. Kattaa sekä teoksen muotoon kohdistuvat muutokset että samassa muodossa kokonaan uudelleenmuokatut teokset." ([RDA, liite J.2.2](http://original.rdatoolkit.org/rdaappj-fi_rdaj-9994.html).)

**Comment by mirmaid** [comment]
^ Mukaelmat-termin määritelmä.

**Comment by AuHo22** [comment]
Rinnakkaisteoksessa sama tarina kerrotaan tarinassa esiintyvän toisen henkilön, esimerkiksi sivuhenkilön näkökulmasta. (??) 

These stories further the works of already well-known novels by focusing on a minor character and making them the major character. 

Määritelmissä on horjuntaa:
Sanottua: Creating parallel novels can have significant legal implications when the copyright of the original author's work has not expired, and a later author makes a parallel novel derived from the original author's work. -> Onko jo mukaelma, jos/kun henkilöiden nimimuotoja on muutettu? 

Viitttauksia myös pastissiin: A parallel novel is an in-universe pastiche (but often non-canonical)  (or sometimes sequel) piece of literature written within, derived from, or taking place during the framework of another work of fiction by the same or another author with respect to continuity. -> Pitäisi erottaa jatkokertomuksesta - sequel?

https://en.wikipedia.org/wiki/Parallel_novel

**Comment by mirmaid** [comment]
Ehdotus KAUNO-työryhmälle kommentoitavaksi:
Rinnakkaisteoksessa alkuperäisen teoksen tarina kerrotaan siinä esiintyvän toisen henkilön, esimerkiksi sivuhenkilön näkökulmasta.

**Comment by mirmaid** [comment]
_Mukaelmat_ ja _johdannaisteokset_ käsitellään vielä erillisessä issuessa RDA:n mukaan. Mukaelmat, ks. https://github.com/Finto-ehdotus/YSE/issues/11052#issuecomment-1531075395.
