### ISSUE TITLE
luostarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11057]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luostarit](http://www.yso.fi/onto/yso/p816)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "munkkikunnat" ja "nunnakunnat"

**Perustelut ehdotukselle**

Munkki- ja/tai nunnakunnat voivat olla joko konventteja tai luostareita (organisaatioina). Ja kun konventeista käytetään YSO:ssa "luostarit"-asiasanaa, pitäisi sen yhteyteen koota kaikki asianmukaiset käytetyt ilmaisut, ml. munkkikunnat ja nunnakunnat, ks. esim. https://fi.wiktionary.org/wiki/konventti. Toki viittauksen pitäisi olla mieluummin kongregaatiotasolla, mutta sille taas ei YSO:ssa ole omaa asiasanaansa.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Ainakin ruotsin kannalta oikeat kohteet olisivat:

-munkkijärjestöt https://finto.fi/yso/fi/page/p5866 
Munkkijärjestöt on sv. munkordnar, ja munkkikunta=munkorden

-nunnajärjestöt https://finto.fi/yso/fi/page/p1002
Nunnajärjestöt ovat sv. nunneordnar, ja nunnakunta=nunneorden

**Comment by fantsby-m** [comment]
Myös suomeksi sopii paremmin ohjaustermeiksi termeille munkkijärjestöt ja nunnajärjestöt.
