### ISSUE TITLE
historialliset tarinat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11055]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[historialliset tarinat](http://www.yso.fi/onto/yso/p14345)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi historialliset kertomukset

**Perustelut ehdotukselle**

Vaihtoehtoinen muoto

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Myös SLM:sanastoon. Pitäisi myös tehdä hierarkiamuutos: > YK kertomukset
Käytetty Melindassa näin, ei pelkästään kansantarinoina.

**Comment by krinay** [comment]
_Historialliset tarinat_ on folkloristisessa kontekstissa tärkeä käsite, perinnelaji. Siihen tarpeeseen riittävän täsmällisen termin soisi jäävän YSOon.

_Historialliset kansantarinat_ olisi kai yksi vaihtoehto, mutta en usko tutkijoiden tai muiden nimenomaan folkloristisesta tutkimuksesta tietoa hakevien hoksaavan käyttää sellaista uudistermiä.

Miten olisi tällainen ratkaisu:

historialliset tarinat
LT kansantarinat
RT historialliset kertomukset

historialliset kertomukset
LT kertomukset
RT historialliset tarinat

**Comment by mariaforsen** [comment]
Jos halutaan _uutena erillisenä_ käsitteenä "historialliset kertomukset", niin sille on erittäin vaikeaa saada täsmääviä kielivastineita.

**Comment by krinay** [comment]
historialliset tarinat sv historiska sägner
historialliset kertomukset sv historiska berättelser

Ks. esim. https://www.sls.fi/sv/utgivning/historiska-sagner-om-1808-09-ars-krig

**Comment by mirmaid** [comment]
^ Vähän epäilen, että huonommin aihetta tunteva kuvailija voi erehtyä. Pitäisikö olla tarkenteella _historialliset tarinat (kansantarinat)_?

**Comment by mariaforsen** [comment]
Ehdottamasti pitäisi tarkentaa siinä tapauksessa, muuten menee väärin melindassa (kuten on nähty tarinat/kertomukset-tapauksessa)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _historialliset kertomukset_ uutena terminä. Muutetaan muotoon _historialliset tarinat (kansantarinat)_.

**Comment by mariaforsen** [comment]
Sv. 
-historiska berättelser som ny term 
-historiska berättelser > historiska sägner

**Comment by mirmaid** [comment]
^ Sama muutos SLM:ään.

**Comment by mirmaid** [comment]
Jäin vielä miettimään, tarvitaanko SLM:ään historialliset kertomukset -termiä? Siellä nimittäin on ennestään YSOa enemmän termistöä erilaisille historiallisille teostyypeille.

Toisaalta kannattaako näiden olla eri tavalla keskenään?

**Comment by mariaforsen** [comment]
Kannatan että myös SLM:ssä olisi historialliset kertomukset. Näin on siis ollut koko ajan ruotsiksi (nyt muutettu berättelser > sägner).

Melindassa historialliset tarinat käytetty 154 kertaa, ja suuri osa näistä ovat nimenomaan kertomus-merkityksessä (EI sägner/kansantarina-merkityksessä). Melinda-viitteet pitäisi periaatteessa myös korjata > sägner/tarinat pois niistä missä ei ole kansantarinoista kyse.

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään ensi kokoukseen.

**Comment by mirmaid** [comment]
Historialliset novellit > historialliset kertomukset (historialliset novellit ohjaustermiksi).

**Comment by mirmaid** [comment]
Ks. tämän ja muutamien muiden historialliset-alkuisten termien huomautukset.

http://urn.fi/URN:NBN:fi:au:slm:s936
http://urn.fi/URN:NBN:fi:au:slm:s649
http://urn.fi/URN:NBN:fi:au:slm:s461
http://urn.fi/URN:NBN:fi:au:slm:s445

**Comment by mariaforsen** [comment]
Historialliset näytelmät-termin huomautus pitäisi varmaan muuttaa > "
Historiallisiin tapahtumiin perustuva näytelmä" ? Kronikkanäytelmät ovat muuten rinnakkaisterminä, SAOssa se on alakäsitteenä (krönikespel="en form av historisk dramatik som blomstrade i England vid 1500-talets slut"). 

Voisiko historiallisten romaanien huomautus olla samankaltainen kuin muut historialliset... -termit"? Nyt voisi periaatteessa saada sen käsityksen että pitää perustua todellisiin tapahtumiin?(https://www.kielitoimistonsanakirja.fi/#/historiallinen?searchMode=all)

Ks. https://www.kirjasampo.fi/fi/genre/historialliset%20romaanit ja
https://fi.wikipedia.org/wiki/Historiallinen_romaani

**Comment by mirmaid** [comment]
Käytetään romaaneista/xx, jotka tekijä on sijoittanut historialliseen aikaan.

**Comment by mirmaid** [comment]
Lisätäänkö käyttöhuomautukset myös YSOon? (Historialliset romaanit, -rakkausromaanit, -näytelmät - kaikilla nyt sama huomautus SLM:ssä.)

**Comment by YSO-kokous** [comment]
Otetaan yllä mainitut SLM-huomautukset myös YSOon. Muutetaan kuitenkin YSOon käyttöhuomautuksesta määritelmäksi:
Käytetään romaaneista, jotka tekijä on sijoittanut historialliseen aikaan. -> Tarkoittaa romaaneja, jotka tekijä on sijoittanut historialliseen aikaan.
