### ISSUE TITLE
litaniat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11058]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[litaniat](http://www.yso.fi/onto/yso/p29821)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään YSO:ssa oleva määritelmä myös SLM-sanaston puolelle ja vaihdetaan LT-suhde "musiikki" --> "liturginen musiikki"

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Ok/SLM
