### ISSUE TITLE
kirjoituskilpailut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11053]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kirjoituskilpailut](http://www.yso.fi/onto/yso/p11024)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM-sanastossa - onko tämä todella genre/lajityyppi?

**Perustelut ehdotukselle**

https://kirjoittaminen.fi/kirjoituskilpailut/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Termi on ehkä huono?

**Comment by AuHo22** [comment]
Näissä ei kuitenkaan kuvata kirjoituskilpailua toimintana, eli ei voi asiasanaksikaan muuttaa, esim. 978-951-1-43665-2 tai 978-952-381-133-1 Ja näitä kyllä meillä ainakin kuvaillaan paljon, itse en äkkiseltään keksi, mikä voisi olla korvaava muoto.

**Comment by ilona-x** [comment]
voisiko slm-termi olla esim. **kirjoituskilpailujen antologiat**? 🤔 

https://msl.fi/material/kirjoituskilpailujen-antologiat/

**Comment by AuHo22** [comment]
_Kilpailurunot_ näytettäisiin käytettävän jonkin verran, mutta ei sitten kilpailunovelleja kuitenkaan..

**Comment by mirmaid** [comment]
Muutetaan > kirjoituskilpailuantologiat

**Comment by mariaforsen** [comment]
Sv. skrivtävlingsantologier HT skrivartävlingsantologier,  skrivartävlingstexter
