### ISSUE TITLE
sukupuoli-identiteetti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11050]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuoli-identiteetti](http://www.yso.fi/onto/yso/p3440)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Huomautus "Tarkoittaa tunnetta jompaankumpaan sukupuoleen kuulumisesta" tulisi muuttaa muotoon: "Sukupuoli-identiteetillä tarkoitetaan henkilön kokemusta omasta sukupuolestaan." 

**Perustelut ehdotukselle**

Nykyinen huomautus on binäärinen ja syrjivä. Käsitteen tulisi sisältää kaikki mahdolliset sukupuoli-identiteetit. "Tasa-arvolaissa sukupuoli-identiteetillä tarkoitetaan henkilön kokemusta omasta sukupuolestaan." https://tasa-arvo.fi/sukupuoli-identiteetti 

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/10794
