### ISSUE TITLE
kellopikarikulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11054]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kellopikarikulttuuri

**Ehdotettu termi ruotsiksi**

klockbägarkulturen

**Ehdotettu termi englanniksi**

Bell beaker culture

**Tarkoitusta täsmentävä selite**

The Bell Beaker culture, also known as the Bell Beaker complex or Bell Beaker phenomenon, is an archaeological culture named after the inverted-bell beaker drinking vessel used at the very beginning of the European Bronze Age. (wikipedia)

**Perustelut ehdotukselle**

Melindassa 6 tietuetta

**Ehdotettu yläkäsite YSOssa (LT)**

 [pronssikautiset kulttuurit](http://www.yso.fi/onto/yso/p38521)

**Ehdotetut temaattiset ryhmät**

 [51 Arkeologia](http://www.yso.fi/onto/yso/p26593)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh87007797.html), [sao](https://id.kb.se/term/sao/Klockb%C3%A4garkulturen), [wikipedia](https://fi.wikipedia.org/wiki/Kellopikarikulttuuri)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/qatqfk/alma9934345528406253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [kellopikarikulttuuri](http://finto.fi/yse/fi/page/Y511054)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
