### ISSUE TITLE
laki julkisista hankinnoista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11062]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laki julkisista hankinnoista](http://www.yso.fi/onto/yso/p23270)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisi ehkä ottaa myös uusi laki

**Perustelut ehdotukselle**

https://www.finlex.fi/fi/laki/smur/2007/20070348 - vanha hankintalaki
https://www.finlex.fi/fi/laki/smur/2016/20161397 - hankintalaki (nyt meillä ohjaa vanhaan lakiin)

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. lag om offentlig upphandling och koncession

**Comment by jarmosaarikko** [comment]
en: Act on Public Procurement and Concession Contracts
source: https://www.finlex.fi/fi/laki/kaannokset/2016/en20161397
