### ISSUE TITLE
ympäristöntutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11065]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ympäristöntutkimus](http://www.yso.fi/onto/yso/p10900)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotettu ohjaustermin vaihtoa päätermiksi

**Perustelut ehdotukselle**

Käytetympi

**Ehdottajan organisaatio**

JUPO

**Comment by ilona-x** [comment]
ehdotettu siis ohjaustermin **ympäristötutkimus** muuttamista päätermiksi
