### ISSUE TITLE
tupakkalaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11063]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tupakkalaki](http://www.yso.fi/onto/yso/p26558)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan?

**Perustelut ehdotukselle**

Kaksi lakia samalla nimellä: https://www.finlex.fi/fi/laki/smur/1976/19760693
https://www.finlex.fi/fi/laki/ajantasa/2016/20160549

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Muutetaan mieluummin monikkoon (_**tupakkalait**_), jotta asiasanalla voidaan kuvailla eri maissa säädettyjä tupakkaa ja tupakointia koskevia lakeja. Yksittäiset lait ovat joka tapauksessa RDA:n näkökulmasta teoksia, ja Suomen tasavallan vuosien 1976 ja 2016 tupakkalait on nyt auktorisoitu _Kansalliset teos- ja ekspressiotiedot_ -tietokantaan ("teka") ja niiden auktorisoidut hakutiedot siis käytettävissä Asterin kautta. Seuraaviin Melindan bib-tietueisiin kyseiset hakutiedot on jo lisätty: https://melinda.kansalliskirjasto.fi/byid/014061618, https://melinda.kansalliskirjasto.fi/byid/013825076 ja https://melinda.kansalliskirjasto.fi/byid/016638007.

**Comment by mariaforsen** [comment]
Sv. tobakslag (1976), tobakslag (2016)

**Comment by mirmaid** [comment]
Jaetaan. Jos halutaan kuvailla eri maiden tupakkalakeja, voi varmaan käyttää muita asiasanoja? Aikanaan nämä varmasti siirtyvät teosauktoriteeteiksi, mutta yritetään nyt tehdä johdonmukaisesti YSOn puolella siihen asti.

**Comment by jtuohini** [comment]
Yritin Melindassa teosauktoriteettien tekemisen yhteydessä lisätä nykyisiin bibliografisiin tietueisiin teosviittaukset asianomaisiin lakeihin, ja huomasin, että hankalaa on: osa käsittelee voimassaolevaa lakia, osa valmisteilla olevaa, osa kumpaakin, osa tupakkalainsäädäntöä yleisesti. Onnea vain sille, joka käy läpi nykyiset tietueet ja tekee erittelyn, kun monikkoon vaihtaminen olisi mennyt lennosta. Ks. esim. https://melinda.kansalliskirjasto.fi/byid/009849123, https://melinda.kansalliskirjasto.fi/byid/009849123, https://melinda.kansalliskirjasto.fi/byid/013987990, https://melinda.kansalliskirjasto.fi/byid/007049017, https://melinda.kansalliskirjasto.fi/byid/007051251.

**Comment by jtuohini** [comment]
Ja YSO:n johdonmukaisuuteen liittyen: [**perustuslait**](http://www.yso.fi/onto/yso/p1594)-asiasana on nytkin monikossa, viitaten useaan eri lakiin, joten miksi ei tupakkalakien osalta voisi olla samoin?

**Comment by kovero** [comment]
Älkää jaatko, käy aivan liian vaikeaksi aineiston käsittelijälle ryhtyä selvittelemään minkä vuoden laista on kysymys yms.  Vuosilukuja voidaan ilmaista jossakin muussa yhteydessä kuvailua. Kysymys ryhdytäänkö kaikkien lakien osalta asiasainoituksessa viittaamaan tiuettyyn vuoteen? Jokin muu ratkaisu täytyy löytyä.

Katsoin LCSH:ta jossa auktorisoituna: Tobacco--Law and legislation. 
ja listalta löytyy mm: Tobacco--Law and legislation--Finland. 
Tartteeko meidän mennä tämän tarkemmaksi asiasanoituksessa. 
Teosauktoriteeteilla voidaan sitten tarkentaa mitä yksittäistä lakia tarkoitetaan
joten kannatan ehdotusta "tupakkalait"

**Comment by kovero** [comment]
> Jaetaan. Jos halutaan kuvailla eri maiden tupakkalakeja, voi varmaan käyttää muita asiasanoja? Aikanaan nämä varmasti siirtyvät teosauktoriteeteiksi, mutta yritetään nyt tehdä johdonmukaisesti YSOn puolella siihen asti.

Pyytäkää että näistä tehdään valmiiksi teosauktoriteetit odottamaan. (eiks näitä jo huhti toukokuun aikana pitäisi olla jaossa)
Miettikää miten itse toimisitte siinä tilanteessa kun ryhdytte kuvailemaan. Ulkomaiseen aineistoon nämä kelpaa. Mitäs niihin sitten keksitään. 
Toinen vaihtoehto on että nyt valmiiksi teosauktoriteetit ja termi pysyy "tupakkalaki" terminä joka sopii myös ulkomaiseen aineistoon ja termin kuvauksessa kerrotaan että on yleistemi koskemaan tupakkalakeja ja tarkennusta varten koskien kotimaista lainsäädäntöä käyttää lisäksi teosaukt. jossa tarkempi lakitieto

**Comment by jtuohini** [comment]
Kummastakin kotimaisesta tupakkalaista on jo kattavat teosauktoriteetit tehtynä ((FI-ASTERI-W)000015183 ja (FI-ASTERI-W)000015184)! Niitä voi ja olisi myös syytä jo käyttää Melinda-kuvailussa. Muutamiin bib-tietueisiin ne jo laitoin, mutta samala huomasin, että isosta osasta tietueita on mahdotonta ilman aineistoon tutustumista oikeasti sanoa, kumpaa lakia koskevat jos edes kumpaakaan.

**Comment by fantsby-m** [comment]
Meillä voi toki käyttää YSOn nykyisiä asiasanoja _lainsäädäntö_ ja _tupakka_, jos aineisto käsittelee muiden maiden tupakkaa koskevaa lainsäädäntöä.

**Comment by fantsby-m** [comment]
> Ja YSO:n johdonmukaisuuteen liittyen: [**perustuslait**](http://www.yso.fi/onto/yso/p1594)-asiasana on nytkin monikossa, viitaten useaan eri lakiin, joten miksi ei tupakkalakien osalta voisi olla samoin?

YSO:ssa on kuitenkin myös [Suomen perustuslaki](http://www.yso.fi/onto/yso/p12122).

**Comment by mirmaid** [comment]
Tämä on aikoinaan otettu sanastoon tarkoittamaan silloin voimassa ollutta tupakkalakia - silloin ei vielä ollut missään horisontissakaan YSAsta erillistä teosauktoriteettikantaa, ja lakeja oli jo pitkään auktorisoitu YSAan sekä merkityksessä "tietty suomalainen laki", että "tietynlaiset lait" (perustuslait jne.). Epäilen, että aika monella YSOn yksikkömuotoisella lailla on vastineita muissakin maissa, mutta en oikein näe, että kaikkien tai suuren osan muuttaminen monikkoon parantaisi sanaston tai varsinkaan bib-tietueiden tilannetta, kai kuitenkin parempi olisi korjata bibbeihin se laki, jota on oikeasti tarkoitettu, kohdeteoksena, kuin yleistermi? 

_Tupakkalaki_ on Melindassa 55 tietueessa, mikä on vielä aika maltillinen määrä siihen nähden, että koko ajan työlistalle tulee satoja ja tuhansia tietueita käsittäviä korjauksia.

**Comment by kovero** [comment]
> Meillä voi toki käyttää YSOn nykyisiä asiasanoja _lainsäädäntö_ ja _tupakka_, jos aineisto käsittelee muiden maiden tupakkaa koskevaa lainsäädäntöä.

En usko että tähän halutaan mennä: tarkoittaisi varmaankin myös tällöin _lainsäädäntö_ ja _alkoholi_, (alkoholilaki)
kun yhdellä termillä voidaan ilmaista että ei ole tupakka yleensä vaan jokin lainsäädäntöön liittyvä aspekti.

Pitäkää termi: tupakkalaki ja tarkennukseksi että jos kyseessä on kotimainen laki niin käyttää lisäksi kyseiseen lakiin viittaavaa teosauktoriteettia.
Mutta ihmisten tavallisen tallaajan on pystyttävä hakemaan näitä (sen lisäksi että kuvailijan on puystyttävä erottamaan mikä vuosi)

**Comment by satuniininen** [comment]
Asiasanahakuna Melindassa
tupakka + lainsäädäntö 234 kpl
alkoholi + lainsäädäntö 283 kpl

**Comment by fantsby-m** [comment]
> > Meillä voi toki käyttää YSOn nykyisiä asiasanoja _lainsäädäntö_ ja _tupakka_, jos aineisto käsittelee muiden maiden tupakkaa koskevaa lainsäädäntöä.
> 
> En usko että tähän halutaan mennä: tarkoittaisi varmaankin myös tällöin _lainsäädäntö_ ja _alkoholi_, (alkoholilaki) kun yhdellä termillä voidaan ilmaista että ei ole tupakka yleensä vaan jokin lainsäädäntöön liittyvä aspekti.
> 

YSO-asiasanaa _lainsäädäntö_ on käytetty 39031 kertaa Melindassa, suurimmassa osassa niistä lienee muilla asiasanoilla tarkennettu minkä alan lainsäädännöstä on kyse.

**Comment by jarmosaarikko** [comment]
wikidatassa on käsite "Suomen tupakkalaki", johon on mapattu kaksikin YSO-käsitettä: http://www.wikidata.org/entity/Q4184824
- pitäisi korjailla wikdatan labelit.
- YSO [26558](https://www.yso.fi/onto/yso/p26558) tupakkalaki ja [21903](https://www.yso.fi/onto/yso/p21903) laki toimenpiteistä tupakoinnin vähentämiseksi. 
- jälkimmäinen on oikein. Ensimmäinen pitäisi liittää seuraavaan:
- Wikdatassa on merkitty pääteemaksi "[smoking ban](http://www.wikidata.org/entity/Q751734)" , joka viittaa tupakoinnin kieltäviin säädöksiin eli sopisi vastineeksi yleisemmälle tupakkalaki-käsitteelle? pitäisi ehkä olla yläkäsitteenä WD:ssäkin?
