### ISSUE TITLE
Nokia Arena

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11061]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Nokia Arena

**Ehdotettu termi ruotsiksi**

Nokia Arena

**Ehdotettu termi englanniksi**

Nokia Arena

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [rakennukset](http://www.yso.fi/onto/yso/p1786)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 Nokia Areena, Nokia-areena, Tampereen kannen areena

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Tampereen_Kannen_areena)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansi ja Areena = Deck and Arena 

**Ehdottajan organisaatio**

kk/il

**Comment by LeKorsu** [comment]
Nämä sponsorialkuiset markkinointinimet ovat mielestäni pienimuotoinen ongelma, jos auktorisoitua nimimuotoa ei tule päivitettyä samassa tahdissa kuin mitä markkinointinimi muuttuu, Esimerkkinä Töölön jalkapallostadion, joka oli kaiketi ensimmäiseksi Finnair stadium (https://finto.fi/yso/fi/page/p19123), joka on nykyisin Bolt Arena ja ollut siinä välissä niin Sonera Stadium kuin Telia 5G Arena.
Senpä vuoksi ehdotankin käytettäväksi termiksi Tampereen kannen areena ja Nokia Arena & Nokia Areena ohjaustermeiksi.

**Comment by fantsby-m** [comment]
Joo ^ , Turun Typhoon/HK-areena/Elysée Areenakin on YSOssa **[Turkuhalli](http://www.yso.fi/onto/yso/p25564)**. (Nykyinen nimi on muuten Gatorade Center, jonka voisi lisätä ohjaustermiksi)

**Comment by mariaforsen** [comment]
Sv. Tammerfors allaktivitetsarena
https://okm.fi/sv/-/tampereen-monitoimiareenalle-tukea-syksyn-lisabudjetista

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11035#issuecomment-1459926646

**Comment by jarmosaarikko** [comment]
WIkipedian mukaan: _Hallia on kutsuttu myös nimillä Tampereen keskusareena ja Tampereen monitoimiareena_
jälkimmäinen on areenaa pyörittävän yrityksen nimi (ei ole Kantossa).

Y-tunnus	Nimi	Yritysmuoto
2792951-4 	KOY Tampereen Monitoimiareena 	Osakeyhtiö 
2865799-5 	Tampereen Monitoimiareena GP Oy 	Osakeyhtiö 
2858981-4 	Tampereen Monitoimiareena Ky 	Kommandiittiyhtiö

**Comment by ilona-x** [comment]
YLEllä **Tampereen areena** https://yle.fi/aihe/t/18-288986

**Comment by ilona-x** [comment]
Tälle löytyy niin monta nimivaihtoehtoa, että olisi kiva, jos olisi jokin paikka, mistä voisi tarkistaa virallisen ei-sponsorinimen. 🤔 Tampereen kaupungin karttapalvelussakin näyttää olevan Nokia Arena.

Turkuhalli näyttää löytyvän paikkatietoalustalta http://paikkatiedot.fi/so/1000772/10294785

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _Tampereen monitoimiareena_. Muut ohjaustermeiksi.
