### ISSUE TITLE
asumistuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11067]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[asumistuki](http://www.yso.fi/onto/yso/p13997)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Monikko (tai KT yleinen asumistuki)?

**Perustelut ehdotukselle**

https://www.kela.fi/kelan-tuet-asumiseen

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Ääni monikkomuodolle. Yleisen asumistuen ja eläkkeensaajan asumistuen lisäksi on myös opintotuen asumislisä ja sotilasavustuksen asumisavustus, joiden yhteydessä voisi ehkä olla rohkeutta käyttää tätä käsitettä, jos olisi monikkomuotoinen.

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/asumistuki

**Comment by mirmaid** [comment]
^ Kannattaa tutustua näihin, huom. myös "asumisen tuet". Muutetaanko monikkoon tarkoittaa mainittua neljää tukimuotoa, ei kuitenkaan muita asumisen tukia? Ja haittaako, jos monikko joskus tulkitaan laajemmin?

**Comment by ilona-x** [comment]
JUPOssa:
**asumistuet** http://www.yso.fi/onto/jupo/p1039
ja asumistuet-termin alakäsitteinä:
[asumislisät](https://finto.fi/jupo/fi/page/p2626)
   [ eläkkeensaajien asumistuet](https://finto.fi/jupo/fi/page/p2676)
   [ yleiset asumistuet](https://finto.fi/jupo/fi/page/p2909)

**Comment by LeKorsu** [comment]
Ääni myös monikkomuodolle niin kuin jupossa.

**Comment by mirmaid** [comment]
Kelan sanastossa siis

Asumistuki = etuus, jota pienituloinen henkilö tai ruokakunta voi saada suoriutuakseen asumismenoistaan.

huomautus
Kelan maksamia asumistukia ovat eläkkeensaajan asumistuki, yleinen asumistuki, opintotuen asumislisä ja sotilasavustuksen asumisavustus.
Asumisen tuki -termi voidaan ymmärtää laajemmin tarkoittamaan myös muuta asumisen tukemista, esimerkiksi asuntolainojen korkovähennystä, valtion myöntämiin asuntolainoihin liittyvää korkotukea, erilaisia investointiavustuksia sekä korjausavustuksia.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan muotoon _asumistuet_.
