### ISSUE TITLE
vanhempainraha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11064]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vanhempainraha](http://www.yso.fi/onto/yso/p9409)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitaanko muutosta/lisäyksiä?

**Perustelut ehdotukselle**

https://www.kela.fi/vanhempainpaivarahat-4-9-2022-jalkeen

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Kyllä tarvitaan.
vanhempainraha=föräldrapenning
vanhempainpäiväraha=föräldradagpenning

"Vanhempainpäiväraha on perhe-etuus. Vanhempainpäivärahoja ovat erityisäitiys-, äitiys-, isyys- ja vanhempainraha"

Ks. https://termipankki.fi/tepa/fi/haku/vanhempainraha

https://www.kielitoimistonsanakirja.fi/#/vanhempainraha?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/vanhempainp%C3%A4iv%C3%A4raha?searchMode=all

**Comment by mirmaid** [comment]
Sanastossa on nyt siis vanhempainraha, ja sen alakäsitteet isyysraha ja äitiysraha. 

Uuden lain mukaiset etuudet ovat raskausraha, erityisraskausraha, vanhempainraha ja vanhempainraha osittaisena. Ongelmaton uusi termi lienee raskausraha.

Vanhempainraha uuden lain mukaan on vähän eri asia kuin aiemmin, koska enää ei ole erillistä äitiys- ja isyysrahaa. Onko ongelma? 

_Vanhempainpäivärahat_ on vain kattotermi näille etuuksille, ts. se ei ole maksettava etuus itsessään.

**Comment by mirmaid** [comment]
Entinen vanhempainraha: https://www.kela.fi/vanhempainraha

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Otetaan sanastoon uusi käsite: raskausraha
Ei muita muutoksia.

**Comment by mariaforsen** [comment]
Sv. graviditetspenning HT graviditetspeng
https://www.sanakirja.fi/custom/en-sv-fi/raskausraha
https://www.kela.fi/graviditetspenning-och-sarskild-graviditetspenning
