### ISSUE TITLE
flavivirukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11069]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

flavivirukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/345528

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [flavivirukset](http://finto.fi/yse/fi/page/Y511069)

**Comment by mariaforsen** [comment]
Sv. flavivirus 
https://sv.wikipedia.org/wiki/Flavivirus
https://www.rikstermbanken.se/search?q=flavivirus&s=termer

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D018067

https://fi.wikipedia.org/wiki/Flavivirukset
