### ISSUE TITLE
lavastus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11060]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lavastus](http://www.yso.fi/onto/yso/p4110)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT näyttämöllepano

**Perustelut ehdotukselle**

sv. termi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Lavastus on nyt sv. iscensättning, ja se taas käännetään myös =näyttämöllepano

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_41b5353e2883db9dcdf570df43b253d0&list_id=1&keyword=n%C3%A4ytt%C3%A4m%C3%B6llepano&word=n%C3%A4ytt%C3%A4m%C3%B6llepano

https://www.kielitoimistonsanakirja.fi/#/n%C3%A4ytt%C3%A4m%C3%B6llepano?searchMode=all

**Comment by mirmaid** [comment]
On nyt ohjausterminä _skenografialle_. Jos oikein tulkitsen, skenografia on laajempi kuin lavastus, ja näyttämöllepano voidaan ymmärtää sitäkin laajempana (?).

https://tieteentermipankki.fi/wiki/Nimitys:n%C3%A4ytt%C3%A4m%C3%B6llepano
https://fi.wikipedia.org/wiki/Mise-en-sc%C3%A8ne
https://en.wikipedia.org/wiki/Mise-en-sc%C3%A8ne

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
