### ISSUE TITLE
laajentava kardiomyopatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11074]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laajentava kardiomyopatia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 dilatoiva kardiomyopatia, DCM

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH](http://www.yso.fi/onto/mesh/D002311)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153199

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [laajentava kardiomyopatia](http://finto.fi/yse/fi/page/Y511074)

**Comment by mirmaid** [comment]
Lääketieteen termit: dilatoiva kardiomyopatia, (sydäntä) laajentava sydänlihassairaus | laminopatia, jolle ovat ominaisia sydänlihaksen supistusvoiman heikkenemisestä aiheutuva kammioiden täyttöpaineen kasvu, sydämen laajeneminen ja sen vajaatoiminta

**Comment by mirmaid** [comment]
https://www.terveyskirjasto.fi/ltt01853

Googlella eniten muodossa _dilatoiva kardiomyopatia_.

**Comment by mariaforsen** [comment]
Sv. dilaterad kardiomyopati 
https://mesh.kib.ki.se/term/D002311/cardiomyopathy-dilated
