### ISSUE TITLE
lamiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11073]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lamiinit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153199

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lamiinit](http://finto.fi/yse/fi/page/Y511073)

**Comment by mirmaid** [comment]
https://www.solunetti.fi/fi/solubiologia/lamiinit/2/
https://en.wikipedia.org/wiki/Lamin

MeSH: http://www.yso.fi/onto/mesh/D034882

**Comment by mariaforsen** [comment]
Sv. laminer 
https://mesh.kib.ki.se/term/D034882/lamins
