### ISSUE TITLE
formiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11075]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

formiinit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153441

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [formiinit](http://finto.fi/yse/fi/page/Y511075)

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Mikrobiologia:formiini
https://en.wikipedia.org/wiki/Formins

MeSH: http://www.yso.fi/onto/mesh/D000080865

**Comment by mariaforsen** [comment]
Sv. forminer
