### ISSUE TITLE
hyötypelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11071]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hyötypelit](http://www.yso.fi/onto/yso/p29628)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tälle näyttäisi löytyvän vastine LCSHsta eli voisi linkata http://id.loc.gov/authorities/subjects/sh2021008610

**Perustelut ehdotukselle**

LCSH-linkkaus puuttuu 

**Ehdottajan organisaatio**

kk/il

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q1506693

**Comment by tpalonen** [comment]
Toteutettu ehdotetusti. Myös Wikidata-linkki lisätty. Kiitos huomioista!
