### ISSUE TITLE
neuroborrelioosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11079]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neuroborrelioosi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153604

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [neuroborrelioosi](http://finto.fi/yse/fi/page/Y511079)

**Comment by LeKorsu** [comment]
MeSH/FinMeSHissä neuroborrelioosi ohjausterminä Lymen neuroborrelioosille.

**Comment by mirmaid** [comment]
Lääketieteen termit: Lymen borrelioosin muoto, joka voi ilmetä aivokalvon, aivohermojen tai hermojuurten tulehduksena tai näiden yhdistelmänä ja aiheuttaa monimuotoisia oirekuvia, kroonisessa muodossa myös dementiaa, ataksiaa, huimausta ja psyykkisiä oireita

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D020852

**Comment by mariaforsen** [comment]
Sv. neuroborrelios /ne, mesh HT neuroborrelia

**Comment by mirmaid** [comment]
Meillä siis borrelioosin osalta päädyttiin ottamaan päätermiksi borrelioosi ja ohjaustermiksi Lymen borrelioosi, joten varmaan samoin myös tässä?

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q819124
