### ISSUE TITLE
etuotsalohko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11072]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

etuotsalohko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ysossa on hippokampus ja mantelitumake, joten myös etuotsalohko on perusteltua olla. Kaikkia kolmea käsitellään käsillä olevassa teoksessa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ruumiinosat](http://www.yso.fi/onto/yso/p109)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Nestori Neuroni ja hämmästyttävät aivot.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [etuotsalohko](http://finto.fi/yse/fi/page/Y511072)

**Comment by mirmaid** [comment]
Lääketieteen termit: isoaivojen otsalohkon etuosa

Myös _otsalohko_ puuttuu sanastosta, MeSH: http://www.yso.fi/onto/mesh/D005625 / prefrontaalinen aivokuori: http://www.yso.fi/onto/mesh/D017397

**Comment by mariaforsen** [comment]
Sv. -prefrontal hjärnbark
-frontallob

**Comment by mirmaid** [comment]
Mikähän tarkkuus tässä esimerkkiaineistossa on ollut? Jos tosiaan _etuotsalohko_, niin toivottavasti se on sama kuin prefrontal cortex. Lääketieteen termeissä etuotsalohko on eng. prefrontal area, mutta jos kerran otsalohko on osa aivokuorta, niin kaiketi etuotsalohko silti = etuaivokuori. 

https://fi.wikipedia.org/wiki/Otsalohko

**Comment by ilona-x** [comment]
Itse olisin saattanut tyytyä tuon esimerkkikirjan kuvailussa pelkkään aivot-termiin, mutta tämä siis teosta näkemättä. 🤔  
https://www.ps-kustannus.fi/Taina-Sainio/Nestori-Neuroni-ja-h%C3%A4mm%C3%A4stytt%C3%A4v%C3%A4t-aivot.html
https://melinda.kansalliskirjasto.fi/byid/018411398

**Comment by tpalonen** [comment]
Kannatan käsitteen ottamista. Frontal lobe eli otsalohko prefrontal cortexin sisältävänä isompana alueena varmaan tarpeellisempi? Tai riittäisikö yleissanastoon tarkkuustasolla yksi käsite, jossa yhdistetään frontal lobe ja prefrontal cortex eli otsalohko ja prefrontaalinen aivokuori, toinen päätermiksi, toinen ohjaustermiksi?

**Comment by FinMeSHienPaimentaja** [comment]
MeSH-näkemys:

https://meshb.nlm.nih.gov/record/ui?ui=D017397

![image](https://user-images.githubusercontent.com/33662610/223732889-3f61aad3-5a31-49f7-9ab2-9f8219ba8b4a.png)

sekä koko aivokuoresta:
https://meshb.nlm.nih.gov/record/ui?ui=D002540

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _otsalohko_.

**Comment by mariaforsen** [comment]
Sv. frontallob HT pannlob, lobus frontalis
https://www.psykologiguiden.se/psykologilexikon/?Lookup=pannlob%2C+frontallob
https://www.sanakirja.fi/custom/fi-en-sv/otsalohko
https://mesh.kib.ki.se/term/D005625/frontal-lobe
