### ISSUE TITLE
vatsa-aortta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11078]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vatsa-aortta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153760

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [vatsa-aortta](http://finto.fi/yse/fi/page/Y511078)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D001012
LCSH: http://id.loc.gov/authorities/subjects/sh85000106

**Comment by mariaforsen** [comment]
Sv. bukaorta
