### ISSUE TITLE
Suomen luonnon päivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11086]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Suomen luonnon päivä

**Ehdotettu termi ruotsiksi**

Finska naturens dag

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Juhlapäivä ja liputuspäivä

**Perustelut ehdotukselle**

https://almanakka.helsinki.fi/fi/24-suomi/juhlap%C3%A4iv%C3%A4t-ja-liputus.html
https://suomenluonnonpaiva.fi/

**Ehdotettu yläkäsite YSOssa (LT)**

 [juhlapäivät](http://www.yso.fi/onto/yso/p2571)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Suomen_luonnon_p%C3%A4iv%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Artikkeli tämän päivän vietosta ja juhlallisuuksista

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Suomen luonnon päivä](http://finto.fi/yse/fi/page/Y511086)

**Comment by mariaforsen** [comment]
Sv. HT finländska naturens dag
https://almanakka.helsinki.fi/sv/flagg-och-festdagar/flaggdagar-2023.html
Kontakta arrangören om det svenska namnvalet.
