### ISSUE TITLE
Monterey

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11088]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Monterey

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kaupunki Kaliforniassa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Kalifornia](http://www.yso.fi/onto/yso/p105835)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

A dangerous business / Jane Smiley.

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mirmaid** [comment]
Monterey (Kalifornia)
