### ISSUE TITLE
Länsi-Rooma / Länsi-Rooman valtakunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11080]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Länsi-Rooma / Länsi-Rooman valtakunta

**Ehdotettu termi ruotsiksi**

Västromerska riket / Västrom

**Ehdotettu termi englanniksi**

Western Roman Empire 

**Tarkoitusta täsmentävä selite**

Ks. esim. Wikipedia. DNB:ssä maantieteellinen käsite, saossa kronologisena. Pitäisi ehkä käsitellä kuitenkin Bysantin kaltaisesti?

**Perustelut ehdotukselle**

Ajan mahtivaltioita kuten myös Kirkkovaltio pitkään, eikä kumpaakaan sanastossa. Toisin kuin Itä-Rooma -> Bysantti

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [DNB](http://Weströmisches Reich / variantti: Römisches Reich (West) / Geschichte 395-476 ), [sao/variant](http:// Romerska riket (Västromerska riket) Västromerska riket, Romerska riket, 395-476 e.Kr. )

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. teokseen Jaro Karkinen: Paaviuden historia, myös kansainvaellusten jne. muun ajan historian kuvauksissa tarpeellinen.

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mariaforsen** [comment]
Nationalencyklopedin:  västromerska riket: "sentida benämning på romerska rikets västra hälft efter delningen mellan Theodosius I:s söner Honorius (i väster) och Arcadius år 395."
https://sv.wikipedia.org/wiki/V%C3%A4stromerska_riket

**Comment by mirmaid** [comment]
Länsi-Rooman valtakunta KT Länsi-Rooma

**Comment by mariaforsen** [comment]
Sv. Västromerska riket HT Västrom

Se NE etc. I ALLFO-orter avses dock nationen/det geografiska namnet, inte en tidsperiod. https://kommuntorget.fi/blogg/2012/12/stor-eller-liten-bokstav/ 
https://www.isof.se/download/18.17dda5f1791cdbd2873a99/1620030264840/Mynd-skrivreg2014-1.pdf
"...geografiska egennamn skrivs med stor bokstav" 
..."Det gäller även vissa benämningar som ser ut som nationsnamn men avser en historisk period, t.ex. romarriket"

https://sv.wikipedia.org/wiki/V%C3%A4stromerska_riket
"Västromerska riket" och "Östromerska riket" är inte samtida termer, utan mer moderna benämningar för två stater som var [de facto](https://sv.wikipedia.org/wiki/De_facto) självständiga, men det fanns egentligen ingen punkt då romarna själva såg kejsardömet som indelat i två separata stater.."

https://publications.europa.eu/code/sv/sv-4100500sv.htm  "Väderstrecksbenämningar som används för tämligen klart avgränsade geografiska områden inleds med versal"

Jfr även **Ö**stromerska riket och **R**omerska riket i ALLFO-orter
