### ISSUE TITLE
ruokasooda

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11083]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ruokasooda](http://www.yso.fi/onto/yso/p23260)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus ruotsin suhteen, uutena terminä leivinjauhe?

**Perustelut ehdotukselle**

Ruotsinkielinen vastine on ollut bakpulver. Hyväksytäänkö leivinjauhe erillisenä terminä (sv. bakpulver) ? Niissä on kuitenkin eroja https://www.hs.fi/ruoka/art-2000008744845.html

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
LCSH:
Sodium bicarbonate (KT Baking soda) http://id.loc.gov/authorities/subjects/sh94006042
Baking powder http://id.loc.gov/authorities/subjects/sh85011090

--

Melinda:
leivinjauhe x 1

**Comment by mirmaid** [comment]
Otetaan erikseen.
