### ISSUE TITLE
aciditet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11085]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aciditet](http://www.yso.fi/onto/yso/p4554)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mistä kaikesta on tarkoitus käyttää, myös mausta? Lisätäänkö OT happamuusaste?

**Perustelut ehdotukselle**

Ruotsiksi aciditet, joka viittaa kemialliseen merkitykseen, ei käytetä mausta, vaan viittaa lähinnä happamuusasteeseen. Voidaan mahdollisesti muuttaa > surhet, jos tämä pitääkin viitata laajempaan merkitykseen. https://www.kielitoimistonsanakirja.fi/#/happamuus

**Ehdottajan organisaatio**

ALLFO

**Comment by fantsby-m** [comment]
Jotenkin tuntuisi että kemiallinen happamuus ja happamuus (maku) pitäisi olla sanastossa erikseen, jälkimmäinen termin **[maku (aineen ominaisuudet)](http://www.yso.fi/onto/yso/p3459)** alakäsitteenä kuten muutkin perusmaut.

**Comment by mirmaid** [comment]
Melindassa myös kaikenlaista ruokavalioon ja terveyteen liittyvää, jossa puhutaan happo-emästasapainosta, niissä happamuus kaiketi myös aciditet (toivottavasti ainakin, jos jako tehdään maku vs. kemia)?

**Comment by mariaforsen** [comment]
Aciditet käytetään lähinnä kemiassa, ehkä voidaan kuitenkin "soveltaa vähän laajemmin"..
https://halsokraft.se/inspiration/halsa/darfor-ska-du-basa-kroppen

**Comment by mirmaid** [comment]
Eli jako
happamuus (maku)
happamuus (kemia)

**Comment by YSO-kokous** [comment]
**Päätös**

Jaetaan käsitteisiin _happamuus (maku)_ ja _happamuus (kemia)_.

**Comment by mariaforsen** [comment]
Sv. aciditet >
-surhet (kemi) HT aciditet, surhetsgrad 
-surhet (smak) HT syrlighet (smak)

https://termipankki.fi/tepa/fi/haku/happamuus
https://svenska.se/tre/?sok=aciditet&pz=1
https://svenska.se/tre/?sok=sur&pz=1
https://svenska.se/tre/?sok=syrlig&pz=1
https://www.vesi.fi/sv/sanasto/surhet/
https://www.dinkemi.se/elearning/sinnen/surhet-och-syror
https://www.kielitoimistonsanakirja.fi/#/happamuus?searchMode=all
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_c12a3628ed1b3ebe8f84d188891f0292&list_id=1&keyword=happamuus&word=happamuus
https://www.sanakirja.fi/custom/en-sv-fi/happamuus
https://sv.wikipedia.org/wiki/Grundsmak
http://www.kunskapskokboken.se/action/subProductCuisineGroup;jsessionid=122E9C1F1EE8DCBB96B9C3EF23AC5486?productGroupId4=20842
