### ISSUE TITLE
SLM: haitarikirjat

### ISSUE THREAD

**Issue by mirmaid** [Finto-ehdotus/YSE#11087]
KT taitekirjat, leporellot

**Comment by jtuohini** [comment]
Wikidata-siltaus: https://www.wikidata.org/wiki/Q38143405

**Comment by mariaforsen** [comment]
Eli kyseessä on vain ohjaustermien lisäys? 
Myös sv. leporello ANV dragspelsböcker

**Comment by jtuohini** [comment]
Nimenomaan ohjaustermien lisäys. Mirja teki ehdotuksen tänne pyynnöstäni, kun en ollut ihan varma, miten YSE:ssä tällaiset menevät näppärimmin.

**Comment by mirmaid** [comment]
Ok/SLM

**Comment by mirmaid** [comment]
Onko muuten lelukirjat oikea yläkäsite tälle?
