### ISSUE TITLE
metsiköt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11082]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[metsiköt](http://www.yso.fi/onto/yso/p19312)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan, mihin termi viittaa?

**Perustelut ehdotukselle**

Ruotsiksi skogsdunge, joka viittaa "pienehköön metsään". Termi on eri, jos halutaan viitata metsätaloustieteelliseen merkitykseen. https://www.kielitoimistonsanakirja.fi/#/metsikk%C3%B6?searchMode=all
https://termipankki.fi/tepa/fi/haku/metsikk%C3%B6 
Sanastossa on myös puusto=trädbestånd https://termipankki.fi/tepa/fi/haku/puusto

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Muutetaan siis sv > skogsbestånd, jos rajataan suomeksi metsätaloustieteelliseen merkitykseen.

**Comment by mirmaid** [comment]
Varmaan käyttö kyllä pääosin metsätalouteen liittyvää, tosin harmillisen vaikea erottaa viitteistä. Ja riittääkö sitten muissa aineistoissa _metsät_?

**Comment by mariaforsen** [comment]
Näyttää tosiaan Melindan perusteella siltä että voidaan määritellä metsätalouteen liittyvänä ja siten muuttaa sv. > skogsbestånd. 

Voisiko esim. _Helsingin kaupunkimetsiköiden havupuiden elinvoimaisuus_ ja _Muistometsiköt sekä muistopuut ja -puuryhmät_ viitata "pieneen metsään"? Ja olisiko sellaisten takia hyvä olla myös viittaus **"metsiköt (pienet metsät)" KÄYTÄ metsät?**

**Comment by mirmaid** [comment]
^ Täytyy varmaan ottaa työn alle selvittää Finnan kanssa, miten ohjaustermit nyt jatkossa tulevat toimimaan haussa. Olisi oikeastaan hyvä, jos olisi mahdollista merkitä ohjaustermi vain kuvailua ohjaavaksi silloin, kun sitä ei saisi lisätä rikastuksena Finnaan.

**Comment by mirmaid** [comment]
Olisiko lisättävä tarkenne siis _metsiköt (metsätalous)_?

**Comment by mariaforsen** [comment]
Ehkä huomautuskin? 
TEPA: "kasvupaikaltaan ja puustoltaan yhtenäinen metsän osa
Metsänhoidossa metsiköt ovat metsänkäsittely-yksikköjä, joissa tarvitaan samanlaisia hoitotoimia. Nimitystä metsikkö käytetään yleiskielessä myös pienehköstä metsästä (ruotsi: dunge)."

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Lisätään sulkutarkenne metsiköt (metsätalous)
Lisätään käsitteelle määritelmä.
