### ISSUE TITLE
Kirkkovaltio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11081]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kirkkovaltio

**Ehdotettu termi ruotsiksi**

Kyrkostaten

**Ehdotettu termi englanniksi**

Papal States

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Euroopan historiassa vallinnut uskonnollinen ja poliittinen voimatekijä, jolle tarvetta kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Jaro Karkinen 9789519831268

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by jtuohini** [comment]
LCNAF-vastine [**Papal States**](http://id.loc.gov/authorities/names/n79066158).
