### ISSUE TITLE
laki vesi- ja energiahuollon, liikenteen ja postipalvelujen alalla toimivien yksiköiden hankinnoista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11098]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laki vesi- ja energiahuollon, liikenteen ja postipalvelujen alalla toimivien yksiköiden hankinnoista](http://www.yso.fi/onto/yso/p23538)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi laki: Laki vesi- ja energiahuollon, liikenteen ja postipalvelujen alalla toimivien yksiköiden hankinnoista ja käyttöoikeussopimuksista

**Perustelut ehdotukselle**

Tämä on kumottu. Ks. https://www.edilex.fi/smur/20161398

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Olivatka yksittäiset lait voimassa tai kumottuja, RDA:n näkökulmasta ne ovat silti teoksia, eikä kahden eri lain välille voi vetää yhtäsuuruusmerkkejä eli eivät voi olla toisilleen KT-suhteisia.

**Comment by mariaforsen** [comment]
Eli uutena terminä pitäisi ottaa tämä, vanha jää myös sanastoon. 
Sv. lag om upphandling och koncession inom sektorerna vatten, energi, transporter och posttjänster
https://www.finlex.fi/sv/laki/ajantasa/2016/20161398
