### ISSUE TITLE
laki kilpailunrajoituksista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11093]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laki kilpailunrajoituksista](http://www.yso.fi/onto/yso/p18566)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi termi kilpailulaki (pääterminä)

**Perustelut ehdotukselle**

https://finlex.fi/fi/laki/ajantasa/kumotut/1992/19920480
https://finlex.fi/fi/laki/ajantasa/2011/20110948

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Olivatka yksittäiset lait voimassa tai kumottuja, RDA:n näkökulmasta ne ovat silti teoksia, eikä kahden eri lain välille voi vetää yhtäsuuruusmerkkejä eli eivät voi olla toisilleen KT-suhteisia.

**Comment by mariaforsen** [comment]
Eli uutena terminä kilpailulaki sv. konkurrenslag
