### ISSUE TITLE
Ruskon kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11096]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Ruskon kirkko

**Ehdotettu termi ruotsiksi**

Rusko kyrka

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Ruskon_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ruskon vuorella :kirkko, seurakunta ja hautausmaa

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Ruskon kirkko](http://finto.fi/yse/fi/page/Y511096)

**Comment by mariaforsen** [comment]
OT Maria Magdalenan kirkko (Rusko)
 https://www.ruskonseurakunta.fi/kirkot-ja-tilat/kirkot-ja-kappelit/ruskon-kirkko

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q5408186
sijainti: http://paikkatiedot.fi/so/1000772/12010022 sekä  http://www.yso.fi/onto/yso/p94386
