### ISSUE TITLE
protokollat (käyttäytymissäännöt)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11091]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

protokollat (käyttäytymissäännöt)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. 
Nyt sanastossa olevaa tietotekniikan termiä protokollat (sv. länkprotokoll) on käytetty väärin myös tapakulttuuriin/etikettiin tms. liittyvässä merkityksessä esim julkaisuissa
https://melinda.kansalliskirjasto.fi/byid/011187702
https://melinda.kansalliskirjasto.fi/byid/005772409

tai hoitoprotokollaan (joka voisi tarvita oman termin myös) liittyen, mm.:
https://melinda.kansalliskirjasto.fi/byid/006185529

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Protokollaopas maanpuolustajalle /Markus Anaja.

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [protokollat (käyttäytymissäännöt)](http://finto.fi/yse/fi/page/Y511091)

**Comment by jtuohini** [comment]
Pitää olla yksikössä, ks. esim. https://www.kielitoimistonsanakirja.fi/protokolla ("protokolla [on] diplomatiassa noudatettavat säännöt ja muodot"). Samantapainen sana siis kuin _etiketti_, joka jaollisena ei esiinny monikossa puhuessa käyttäytymissäännöistä.

**Comment by mariaforsen** [comment]
Sv. länkprotokoll pitäisi ehkä olla protokoll (datakommunikation), ja protokoll > protokoll (dokument)

**Comment by mirmaid** [comment]
Protokollat vaatii siis tarkenteen (tietotekniikka/tietoliikenne?). 

Eikö näitä protokollia toisessa merkityksessä ole kuitenkin useampia, yksikkö tuntuisi siksi väärältä?

**Comment by fantsby-m** [comment]
Monikossa, koska on esim. ehdotuksessa mainitun teoksen (https://maanpuolustusmitali.fi/protokollaopas/) sotilaisiin liittyvä protokolla ja jtuohinin mainitsema diplomaattinen protokolla.

**Comment by jtuohini** [comment]
Edelleen olen sitä mieltä, että asiasanan tulee olla yksikössä. Vertaa ilmaisuja "millaista protokollaa täällä noudatetaan" (ei "millaisia protokollia täällä noudatetaan"), "millaista etikettiä täällä noudatetaan" (ei "millaisia etikettejä täällä noudatetaan") ja "millaisia (käytös)tapoja täällä noudatetaan" (ei "millaista käytöstapaa täällä noudatetaan"). Se, että on erikseen protokollaoppaita sotilaille ja diplomaateille, ei muuta sitä seikkaa, että niissä kyse on yhdestä samasta asiasta, ohjeista tiettyjen sääntöjen ja muotojen noudattamiseen.

Vertaa myös seuraavat kirjat: _Yrityksen uusi etikettikirja_, _Etikettikirja matkapuhelimen käyttäjälle_,  _Kansainvälinen etikettikirja_, _Miehen etikettikirja_, joista ei kuitenkaan juonnu ajatusta, että olisi "etikettejä". Asia erikseen on, tarvitaanko SLM-sanaston puolelle esimerkiksi _protokollaoppaat_-termi.

Lisähuomioksi, että Kielitoimiston sanakirjan selitys protokollan 1-merkitykselle on kokonaisudessaan "diplomatiassa noudatettavat säännöt ja muodot; myös muista virallisten tilaisuuksien menettelytapasäännöistä tms", joten se sisältää myös sotilaselämän, ei vain diplomatian.

**Comment by mirmaid** [comment]
Voi olla, etten tunne protokolla-sanan merkitystä tarpeeksi hyvin, mutta omaan korvaani myös etiketti olisi monikossa, jos tarkoitettaisiin eri tilaisuuksiin tarkoitettuja (kirjoitettuja) säännöstöjä: hääetiketti, syntymäpäiväetiketti, hautajaisetiketti = etiketit. Jos viitataan tällaisten sääntöjen yhteisesti hyväksyttyyn kokonaisuuteen, niin sitten etiketti yksikössä. Olen siis ajatellut, että nämä eri tilanteiden protokollat eivät muodostaisi etiketin tapaista yhtä kokonaisuutta, vaan olisivat omia säännöstöjään. Jos näin ei ole, niin onko oikeastaan sanoilla etiketti ja protokolla niin suuri ero, ettei protokolla voi olla vain ohjaustermi etiketille?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _protokollat (tietoliikenne)_ sekä _protokollat (käyttäytymissäännöt)_.

**Comment by mariaforsen** [comment]
Sv. protokoll (beteende) HT militärt protokoll, diplomatiskt protokoll
https://fho.sls.fi/uppslagsord/4031/protokoll/
https://um.fi/utrikesministeriets-protokolltjanster 
https://akateeminenwebshop.com/tuote/nicolas_espinoza/protokoll_grundkurs_i_normalt_beteende/9789186185008
