### ISSUE TITLE
ympäristöluokittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11090]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ympäristöluokittelu

**Ehdotettu termi ruotsiksi**

miljöklassificering

**Ehdotettu termi englanniksi**

environmental Classification

**Tarkoitusta täsmentävä selite**

Rakennusalalla esim. "RTS-ympäristöluokitus on suomalainen rakennusalan ympäristöluokitus, joka perustuu eurooppalaisiin standardeihin. Se myönnetään valmiille rakennukselle kolmannen osapuolen puolueettomaan auditoinnin jälkeen, jos rakennuksen todetaan täyttävän vaadittavat ehdot. " (Skanskan verkkosivut) 

**Perustelut ehdotukselle**

Vaikuttaa vakiintuneen käyttöön? Fennicassa ainakin rakennus-, energia- ja tähän lääkealaan liittyen. Sopisi mahdollisesti myös tuotantotalouden temaattiseen ryhmään.

**Ehdotettu yläkäsite YSOssa (LT)**

 [luokitusjärjestelmät](http://www.yso.fi/onto/yso/p12633)

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lääkeaineiden ympäristöluokittelun käyttöönoton mahdollisuudet Suomessa

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [ympäristöluokittelu](http://finto.fi/yse/fi/page/Y511090)

**Comment by LeKorsu** [comment]
Mieluummin kaiketi ympäristöluokitus, koska luokittelu KÄ luokitus (toiminta)

**Comment by mariaforsen** [comment]
Sv. miljöklassningar OT miljöklassificeringar, miljögraderingar
NE, https://sv.wikipedia.org/wiki/Milj%C3%B6klassning

**Comment by mirmaid** [comment]
Ehdotettu YK _luokitusjärjestelmät_, eli tulisiko termiksi _ympäristöluokitukset_? Muut vastaavat _luokitusten_ alla.

**Comment by vthuhtal** [comment]
"luokitukset" alle, sillä vastaa kait enemmän jonkinlaisen numeerisen/sanallisen arvion antamista kuin ykl-luokitusta. Esim. taso 0 (tervetuloa, ympäristöapokalypsi) - taso 10 (hiilineutraali tönö)

**Comment by annamarj** [comment]
Ok! Taisin ehdottaa muotoa "luokittelu" nähtyäni sitä(kin) käytettävän katsomassani julkaisussa, Mutta olisi siis ympäristöluokittelu käytä ympäristöluokitus. Näitä ympäristöluokituksiahan on monenlaisia, ja ei kai se haittaa tässä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _ympäristöluokitukset_.
