### ISSUE TITLE
biopsia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11095]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[biopsia](http://www.yso.fi/onto/yso/p6704)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tähän voisi lisätä ohjaustermit:
koepalan otto
kudosnäytteen otto 

**Perustelut ehdotukselle**

FinMeSH: http://www.yso.fi/onto/mesh/D001706

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. HT vävnadsprov, vävnadsprovtagning
