### ISSUE TITLE
sirkusarvostelut [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11097]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sirkusarvostelut [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

 [arvostelut](http://www.yso.fi/onto/yso/p6612)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013899940 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. cirkusrecensioner (ALLFO)

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
