### ISSUE TITLE
Afganistanin sota (2001-)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11109]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Afganistanin sota (2001-)](http://www.yso.fi/onto/yso/p27437)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käsitteen nimi: Afganistanin sota (2001-2021)

**Perustelut ehdotukselle**

Afganistanin sota päättyi vuonna 2021.

**Ehdottajan organisaatio**

Jyväskylän yliopisto

**Comment by ilona-x** [comment]
LCSH:

Afghan War, 2001-2021 http://id.loc.gov/authorities/subjects/sh2004004460

**Comment by mariaforsen** [comment]
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/afghanistankriget-2001-2021
