### ISSUE TITLE
jakardikankaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11103]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jakardikankaat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Interwoven

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [jakardikankaat](http://finto.fi/yse/fi/page/Y511103)

**Comment by jtuohini** [comment]
Viittamuodoiksi ainakin _jacquard-kankaat_ ja _jacquardit_. Ks. esim. https://www.eurokangas.fi/vaatetus/juhlakankaat/jacquardit

**Comment by LeKorsu** [comment]
Tarvitseeko kangas-loppua, käykö pelkkä jakardi(t), niin kuin sametti, poppana, gobeliinit?
https://finto.fi/yso/fi/page/p2540

**Comment by mariaforsen** [comment]
Sv. jacquardtyger HT jacquard, jacquardväv
https://svenska.se/tre/?sok=jacquard&pz=1
https://tygvaruhuset.se/mobeltyger/jacquardtyger/

**Comment by mirmaid** [comment]
^^ @satuniininen

**Comment by satuniininen** [comment]
Pitää vähän maistella vielä, mutta varmaan voi olla kummin vaan.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _jakardikankaat_, ohjaustermiksi _jakardit_.

**Comment by jtuohini** [comment]
Miksei ohjaustermeiksi myös _jacquard-kankaat_ ja _jacquardit_, kun niitä suomeksi käytetään (ks. yllä)?
