### ISSUE TITLE
Grey-aseksuaalisuus ja grey-seksuaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11107]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Grey-aseksuaalisuus ja grey-seksuaalisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Täsmällinen termi. Vaikeka kuvata muuten. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [seksuaalisuus](http://www.yso.fi/onto/yso/p1826)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [aseksuaalisuus](http://www.yso.fi/onto/yso/p26750)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ace voices : what it means to be asexual, aromantic, demi or grey-ace / Eris Young.

**Ehdottajan organisaatio**

Kirjastopalvelu / OH
**Termiehdotus Fintossa:** [Grey-aseksuaalisuus ja grey-seksuaalisuus](http://finto.fi/yse/fi/page/Y511107)

**Comment by jtuohini** [comment]
Englanninkieliselle kirjastomaailmalle näyttää WorldCatin mukaan riittäneen mainitun kirjan kuvailuun (https://www.worldcat.org/title/1350686400) seuraavat neljä asiasanaa: **Aromantic people**, **Aromanticism**, **Asexual people** ja **Asexuality**.

**Comment by LeKorsu** [comment]
Jättäisin toistaiseksi termiehdotukseksi

**Comment by mariaforsen** [comment]
Vaihtoehtoisesti _harmaa-aseksuaalisuus_. https://seta.fi/sateenkaaritieto/seksuaalinen-suuntautuminen/aseksuaalisuus/ 
https://seta.fi/2018/10/22/aseksuaalisuus-on-kirjava-kokonaisuus/
https://sexpo.fi/kootusti-tietoa/aseksuaalisuus/

**Comment by mirmaid** [comment]
_Aseksuaalisuus_ on otettu sanastoon 2012 ja käytetty Melindassa 20 kertaa. Palveleekohan hakijaa kuitenkaan tätä hienojakoisempi termistö? Marian linkin takaa: _Aseksuaalisuus on kattotermi, jonka kirjoon kuuluvat myös esimerkiksi demiseksuaalisuus, harmaa-aseksuaalisuus, apothiseksuaalisuus ja autoseksuaalisuus_.

**Comment by annamarj** [comment]
ohjaustermiksi?

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan ohjausterminä.
