### ISSUE TITLE
demiseksuaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11106]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

demiseksuaalisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Täsmällinen termi

**Ehdotettu yläkäsite YSOssa (LT)**

 [seksuaalisuus](http://www.yso.fi/onto/yso/p1826)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [aseksuaalisuus](http://www.yso.fi/onto/yso/p26750)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 Ace voices : what it means to be asexual, aromantic, demi or grey-ace / Eris Young.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [demiseksuaalisuus](http://finto.fi/yse/fi/page/Y511106)

**Comment by LeKorsu** [comment]
Sama juttu kuin edellä, jättäisin toistaiseksi hautumaan.

**Comment by mariaforsen** [comment]
Tämä on jo melko runsaasti käytetty, ks. esim. https://seta.fi/sateenkaaritieto/seksuaalinen-suuntautuminen/aseksuaalisuus/
https://fi.wikipedia.org/wiki/Demiseksuaalisuus
https://fi.wiktionary.org/wiki/demiseksuaali
https://trepo.tuni.fi/bitstream/handle/10024/121991/ThilRiikka.pdf
En näe syytä olla ottamatta.

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mirmaid** [comment]
Setan sivuston mukaan tämäkin on kuitenkin aseksuaalisuuden muoto, ja aseksuaalisuus siis käytetty toistaiseksi vain 20 kertaa Melindassa. En nyt tätä suoranaisesti vastusta, mutta en tiedä palveleeko hakijaa kauhean hienojakoinen jaottelu, jos sitten käyttökertoja tulee vain muutama. Toki määritelmien mukaan tämä kuulostaa kyllä ehkä vähän muulta, kuin varsinainen aseksuaalisuus, vaikka sen alalajiksi lasketaankin.

**Comment by annamarj** [comment]
ainakin ohjaustermiksi?

**Comment by mariaforsen** [comment]
Sv. demisexualitet /ne
https://ungpride.munstadi.fi/infobank/hbtiqa-termer/
https://rfslstockholm.se/asexual-awareness-week/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
