### ISSUE TITLE
radioisotoopit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11108]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

radioisotoopit

**Ehdotettu termi ruotsiksi**

radioisotoper

**Ehdotettu termi englanniksi**

radioisotopes

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda:
radionuklidit x 21 + 13 x AFO-terminä
radioisotoopit x 8
radioisotooppi x 1

**Ehdotettu yläkäsite YSOssa (LT)**

 [isotoopit](http://www.yso.fi/onto/yso/p6387)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 radioaktiva nuklider , radioaktiva isotoper, radionuklider, radionuklidit, radionuclides

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO: radioisotoper](https://id.kb.se/term/sao/Radioisotoper), [LCSH: radioisotopes](http://id.loc.gov/authorities/subjects/sh85110713), [WIkipedia](https://fi.wikipedia.org/wiki/Radioisotooppi), [AFO: radionuklidit](http://www.yso.fi/onto/afo/p2709)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The Long-term Biogeochemistry of Se-79, Tc-99, and Sr-90 in Complex Environmental Systems 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [radioisotoopit](http://finto.fi/yse/fi/page/Y511108)

**Comment by ilona-x** [comment]
tämä olikin näköjään jo hyväksytty viime kokouksessa https://github.com/Finto-ehdotus/YSE/issues/10781
