### ISSUE TITLE
elokuva-ala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11101]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[elokuva-ala](http://www.yso.fi/onto/yso/p11124)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään "elokuvateollisuus"-asiasanan kanssa tai lisätään kumpaankin määritelmä.

**Perustelut ehdotukselle**

Monet "--ala"- ja "--teollisuus"-tyyppisistä asiasanoista tuntuvat tarkoittavan yhtä ja samaa, ml. "elokuva-ala" ja "elokuvateollisuus". Jos kuitenkin tarkoittavat selvästi eri asiaa, seikka pitäisi tuoda ilmi huomautuksella tms.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sao:ssa vain yksi päätermi: https://id.kb.se/term/sao/Filmbranschen

Nationalencyklopedin: filmindustri: den kommersiella verksamhet som ägnas åt inspelning, bearbetning, förvärv, distribution, visning, försäljning och uthyrning av film, se [filmbranschen](https://www-ne-se.ezproxy.vasa.abo.fi/uppslagsverk/encyklopedi/l%C3%A5ng/filmbranschen).

Wiktionary:
-elokuva-ala
ammattiala, jolla toiminta suuntautuu elokuvien tuottamiseen, valmistukseen ja levittämiseen
-elokuvateollisuus
teollisuuden haara, jonka toiminta keskittyy elokuva-alan tavoitteita toteuttavaan teolliseen toimintaan

**Comment by fantsby-m** [comment]
Voisi ratkaista kuten jtuohinin yllä linkkaaman **musiikkiala**-ehdotuksen, eli ei yhdistetä, samoilla perusteluilla.

**Comment by jtuohini** [comment]
Mutta jos ei yhdistetä, niin pitää antaa selvä määritelmä, koska ovat niin suurelti osin merkitykseltään yhtä ja samaa. Tai sitten pitää tehdä selvä hierarkia näiden välille, jolloin **-ala**-tyyppiset asiasanat olisivat LT–ST-suhteessa **-teollisuus**-asiasanoihin. Nykytilanne on hyvin epäammattimainen, jos edes tiedontallentajat itse eivät ole selvillä, mitä näillä asiasanoilla todella tarkoitetaan, vrt. mainittu kummankin yhtäaikainen käyttäminen. Lisäksi olen todella hämmästynyt Muusan päätöksestä, että **musiikkiala**-asiasana ei tarvitse määritelmää siksi, että määritelmää ei ole muillakaan **-ala**-asiasanoilla.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
**teollisuus**: alkutuotannon t. luonnon raaka-aineiden (suurimittainen) koneellinen, tehdasmainen jalostaminen elinkeinona; massa-, tehdastuotanto. 
**toimiala**: ala jolla jk t. jku toimii t. työskentelee, toiminta-ala, työ-, tehtäväala. 

_Teollisuus_ ja _toimialat_ siis yläkäsitteet mainituille käsitepareille.
