### ISSUE TITLE
nuotiosammalet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11100]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nuotiosammalet](http://www.yso.fi/onto/yso/p27810)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan tieteellinen nimi

**Perustelut ehdotukselle**

Alakäsitteestä päätellen https://laji.fi/taxon/MX.212933, englanniksi nyt lajitasolla. Miten käytetty?

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kerran Melindassa, aiheena laji https://laji.fi/taxon/MX.43617. Väitöskirjassa tekijän antamana avainsanana nuotiosammalet, eng. vastaavasti "fire-loving mosses". Ko. väitöskirjassa toisena "tulta rakastavana" sammalena mainitaan päärynäsammal, joka on eri heimoakin. 

Muutetaan lajiksi, kun nyt kerran on jo (vähän heppoisin perustein) sanastossa?

**Comment by mariaforsen** [comment]
https://namnochslaktskap.artfakta.se/taxa/2002621/details
https://namnochslaktskap.artfakta.se/taxa/2252/details
