### ISSUE TITLE
globaali etelä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11102]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

globaali etelä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

global south

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

"Kehitysmaat" on arvolatautunut ja vanhentunut käsite. Globaali etelä on neutraalimpi ja vähemmän loukkaava.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Globaali_pohjoinen_ja_globaali_etel%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Jason Hickel: The divide : a brief guide to global inequality and its solutions

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [globaali etelä](http://finto.fi/yse/fi/page/Y511102)

**Comment by jtuohini** [comment]
Alikehittyneet maat > kehitysmaat > kehittyvät maat > globaali etelä. Sitä seuraavaa ilmausta odotellessa…

**Comment by ilona-x** [comment]
Tähän liittyvä aiempi issue **kehittyvät maat** https://github.com/Finto-ehdotus/YSE/issues/1276

**Comment by LeKorsu** [comment]
Kehitysmaat on kieltämättä vanhentunut ja arvolatautunut. Asia on silti sen verran moniselitteinen, että minusta tämä on ongelmakokouksen asia. En siis olisi hyväksymässä tätä ehdotusta tässä vaiheessa enkä välttämättä tässä muodossa.
https://fingo.fi/ajankohtaista/yleinen-fi/kehitysmaat-kehittyvat-maat-kolmas-maailma-globaali-etela-miten-puhua-maailman-enemmistosta/

**Comment by mariaforsen** [comment]
Sv. globala södern, globala syd eivät ole vielä vakiintuneessa käytössä. Nykyinen sv. utvecklingsland on hyväksytty ja ok.

**Comment by LeKorsu** [comment]
Kysyin asiaa Fingossa työskentelevältä ystävältäni, ja hän vastasi näin: "Tuo globaali etelä on tullut maailmalta meidän käyttöömme (global south ja global north), se jakaa jonkin verran eri toimijoita ja esim. virkamiehet eivät käytä sitä. Osa järjestöistä ja tutkijoista kylläkin. Virkamiespuoli ja yritykset käyttävät kehittyvät maat-käsitettä, joka taas tulee kehittyvät markkinat-sanoituksen myötä.
Kehitysmaa taas elää tietenkin ns. ulkopuolisten kielenkäytössä edelleen ja kyllä mekin käytetään edelleen aika sekaisin näitä kaikkia."

**Comment by YSO-kokous** [comment]
**Päätös**

@LeKorsu ja @tpalonen tutkivat vaihtoehtoja ongelmakokoukseen mennessä.

**Comment by mirmaid** [comment]
Leenalta:
Kehitysmaat-käsitteen korvaaminen globaalilla etelällä ei edelleenkään ole yksiselitteinen. Globaalia etelää käyttävät kyllä tutkijat ja aktivistit, mutta kaupan ja diplomatian alalla käytetään mieluummin käsitettä _kehittyvät maat, kehittyvät markkinat_. 

Vaihtoehtoehdotukseni kehitysmaiden tilalle on _köyhimmät maat_ (sv fattigaste länderna, eng [the] poorest countries).  Ja globaali etelä ohjaustermiksi tälle. Ja kehitysmaat tietysti myös. Pitääkö kehitysmaat korvata Melindassa uudella (mikä sitten valitaankaan) vai voisiko sen jättää historiallisena kerrostumana, mutta että nyt ohjattaisiin käyttämään modernimpaa käsitettä?

Me emme voi ottaa mukaan niin monia luokituksia kuin mihin [ko. artikkelissa ](https://fingo.fi/ajankohtaista/yleinen-fi/kehitysmaat-kehittyvat-maat-kolmas-maailma-globaali-etela-miten-puhua-maailman-enemmistosta/)viitataan, mutta mielestäni köyhimmät maat olisi kuitenkin vähän neutraalimpi kuin kehitysmaat, koska rahasta - ja sen puutteestahan - tässä on kyse. Siitäkin huolimatta, että artikkelissa mainitaan, että olisi parempi puhua köyhistä ihmisistä kuin köyhistä valtioista.

Ei tuokaan varmasti mikään hyvä ole, mutta asiaan vihkiytymättömälle varmaan parempi kuin epämääräinen globaali etelä.

**Comment by mariaforsen** [comment]
Ruotsiksi ei varmaan voida ohjata pois "utvecklingsländer"-termin käytöstä (ainakaan tässä vaiheessa), koska se on edelleen täysin käytössä oleva ja suositeltu termi, ks. esim Nationalencyklopedin, SAO jne. Se että maa "kehittyy" ei kai ole ajateltu olevan huono asia sitten.

Entä suomeksi "kehittyvät maat"? https://termipankki.fi/tepa/fi/haku/utvecklingsland Onko se yhtä huono?

Köyhimmät maat sv. fattigaste länderna olisi toki sinänsä ok.

**Comment by LeKorsu** [comment]
Itä-Suomen yliopiston tutkija Teppo Eskelinen, jolle lähetin syyskuun alussa meiliä, ehti vihdoin vastata soittamalla ja tässä referaattia hänen näkemyksistään:
- kehitysmaat vaikka onkin vanhentunut käsite, ei ole edelleenkään suoraan loukkaava kuin moni muu rastistiseksi koettu käsite, esim. YK:n piirissä monet maat kuulemma esittelevät itseään ihan hyvillä mielin kehitysmaaksi
- globaali etelä -käsite on vakiintumassa, kiertokulku on aktivistit > tutkijat > viranomaiset & kauppa, mutta hankaluus on, että ei ole välttämättä selvää mistä puhutaan; kylmän sodan aikana oli maantieteellisesti aika selvää, mitkä maat olivat kehitysmaita, globaalin etelän kanssa ei ole niin
- jos halutaan tehdä raja siihen, mitkä valtiot ovat oikeutettuja kehitysapurahoitukseen, näissä on selvä Maailmanpankin määritelmä. LDC-maat (least developed countries), matalimman tulotason maat, joita on noin 50
- "kehittyvät maat" ovat keskitulotason maita, mutta voiko Intiaa, jolla on avaruustutkimusta, sanoa edes kehittyväksi maaksi
- globaali etelä [joka siis on tutkijan oma suosikki, kun kysyin, millä käsitteellä hän haluaisi omia julkaisujaan kuvailtavan] on viittausalaltaan laajempi, joka kävisi myös esim. Intian ja Brasilian kaltaisista maista.

En tiedä, tuliko tästä nyt sittenkään mitään ratkaisuehdotusta, muuta kuin että kannattaisiko globaali etelä ottaa uutena käsitteenä mukaan sanastoon.

En valitettavasti pysty osallistumaan tiistain kokoukseen. Minulle on tullut tärkeä ohjelmatyöeste.

**Comment by mirmaid** [comment]
Ehdolla ratkaisuksi on siis "sensitiivisyyshuomautuksen" lisääminen termille, globaali etelä -käsitteen ottaminen mukaan joko kehitysmaat-käsitteen lisäksi tai sijasta ja kehitysmaat-termin muutos muotoon kehittyvät maat. Jos kehitysmaat jää päätermiksi, lisätäänkö ohjaustermit kehittyvät maat, köyhimmät maat?

**Comment by mirmaid** [comment]
OECD:n kehitysyhteistyökomitean lista valtioista, joille annettavaa apua voi tilastoida kehitysavuksi:
https://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/DAC-List-of-ODA-Recipients-for-reporting-2022-23-flows.pdf

**Comment by tpalonen** [comment]
Tämä käsite on ollut pohdinnoissa kun tätä kulttuurisensitiivisyyteen liittyvää disclaimer-huomautustekstiä on työstetty. Ehdotuksemme tällä hetkellä on seuraava (tästä on tarkoitus vielä keskustella Ontologiakehittäjien yhteistyöryhmässä ja päätös voi hieman muuttua): 

__Ehdotamme seuraavaa ratkaisua: kaksi geneeristä huomautustekstiä, koska tapauksia on (ainakin) kahta tyyppiä: a) selvästi vanhentuneet termit ja b) vanhentumassa olevat, joille ei ole vielä vakiintunutta korvaajaa:_

_a) "Termimuoto on havaittu vanhentuneeksi tai syrjiväksi. Se on säilytetty sanastossa tiedonhaun mahdollistamiseksi."
b) "Termimuoto on havaittu vanhentuneeksi tai syrjiväksi, mutta käytettävissä ei ole toistaiseksi korvaavaa, vakiintunutta termiä.”_

_Kohta a):ssa tyypillisesti kyseessä on jokin vanhentunut/väistynyt ohjaustermi, ja uusi neutraali termi on yleistynyt ja on YSOssa käytettävä termi. Kohta b) esimerkkinä voi ajatella termiä "kehitysmaat", joka on edelleen käsitteen käytettävä termi. Tästä olemme saaneet palautetta ja tilalle on ehdotettu "globaali etelä", joka ei kuitenkaan näytä vielä vakiintuneen.__

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään kehitysmaat-käsitteele seuraavat ohjaustermit:
kehittyvät maat, köyhimmät maat, globaali etelä

Lisätään kehitysmaat-termille mainittu disclaimer-teksti.

Keskustelua
Globaali etelä ja kehitysmaat ovat merkitykseltään hyvin sama-alaiset termit, ja niillä viitataan samoihin maihin ilman suurta eroa. Keskusteltiin myös kolmannet maat -käsitteestä ja kyseisen termin vanhentumisesta, mutta tässä yhteydessä ei päätetty tehdä sen osalta mitään. Palataan tarvittaessa asiaan näiden käsitteiden kohdalla.

HUOM
YSO-ylläpito ottaa yllä mainittuun disclaimer-tekstiehdotuksiin erittäin mielellään tässä kohtaa palautetta vastaan. Tekstejä ei ole vielä alettu soveltaa eli tässä kohtaa ehtii vielä kommentoida.

**Comment by tpalonen** [comment]
Kehityslinjauksista keskusteltiin 12.10.2023 Ontologiakehittäjien yhteistyöryhmässä ja päädyttiin tekemään linjauksiin lisäys, jonka liitän kokonaisuudessaan alle. Siinä on myös disclaimer-tekstit kirjattuna. Tähän kehitysmaat-tapaukseen sovelletaan linjauksessa mainittua tekstivaihtoehtoa b:

==========================
**_Termit ja kulttuurisensitiivisyys_**

 _Käytettävä termi tai ohjaustermi, joka on tunnistettu kulttuurisensitiivisyyden kannalta ongelmalliseksi, varustetaan huomautustekstillä. Huomautusteksti on termi- ja kielikohtainen. YSOssa termi varustetaan infoikonilla, jonka yhteydessä huomautusteksti näytetään._ 

 _Huomautusteksteissä on kaksi vaihtoehtoa, koska ongelmallisia termejä on kahta tyyppiä. Vaihtoehto a sopii tapauksiin, joissa on kyseessä ohjaustermi, vaihtoehto b tapauksiin, joissa on kyseessä käytettävä termi:_
        _a) "Termimuoto on havaittu vanhentuneeksi tai syrjiväksi. Se on säilytetty sanastossa tiedonhaun mahdollistamiseksi."_
        _b) "Termimuoto on havaittu vanhentuneeksi tai syrjiväksi, mutta käytettävissä ei ole toistaiseksi korvaavaa, vakiintunutta termiä.”_
        _Vaihtoehto b:n tapauksissa mikäli korvaava, vakiintunut termi myöhemmin havaitaan, voidaan ongelmallinen termi siirtää ohjaustermiksi ja muuttaa huomausteksti vaihtoehto a:n mukaiseksi._

Ks. YSO-pohjaisten ontologioiden kehityslinjauksiin 12.10.2023 tehdyt lisäykset löytyvät myös Finton asiakaspalveluwikistä: 
https://www.kiwi.fi/pages/viewpage.action?pageId=371491272
