### ISSUE TITLE
polyketidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11104]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

polyketidit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/342707

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [polyketidit](http://finto.fi/yse/fi/page/Y511104)

**Comment by LeKorsu** [comment]
OK, näyttää olevan jo MeSH/FinMeSH: https://finto.fi/mesh/fi/page/D061065

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Polyketidit
LCSH: http://id.loc.gov/authorities/subjects/sh85104652

**Comment by mariaforsen** [comment]
Sv. polyketider
