### ISSUE TITLE
ympäristötavoitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11113]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ympäristötavoitteet

**Ehdotettu termi ruotsiksi**

miljömålsättningar

**Ehdotettu termi englanniksi**

environmental goals

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

nähtävästi vakiintuntut yleiseen käyttöön useammilla tahoilla, selkeä ja tarkka.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [vastuullisuus](http://www.yso.fi/onto/yso/p24111)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kestävän yhdyskuntarakenteen jäljillä
– näkökulmia ja ratkaisuja kaupunkien
ja maaseutujen suunnittelun haasteisiin

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [ympäristötavoitteet](http://finto.fi/yse/fi/page/Y511113)

**Comment by mariaforsen** [comment]
Sv. miljömål HT miljömålsättningar, detaljerade miljömål, övergripande miljömål 
https://termipankki.fi/tepa/fi/haku/ymp%C3%A4rist%C3%B6tavoite
https://www.rikstermbanken.se/search?q=milj%C3%B6m%C3%A5l&s=termer

**Comment by ilona-x** [comment]
Ehdotuksen esimerkkiaineistossa on käytetty termiä ympäristötavoitteet yhden kerran, ja muuten julkaisussa puhutaan vain tavoitteista tai on julkaisuissa myös yksittäisiä mainintoja muista tavoitteista esim. ilmastotavoitteet, kestävyystavoitteet, päästövähennystavoitteet. 

Riittäisikö tässä kuitenkin tavoitteet ja se mihin tavoitteet liittyvät ilmaistaisiin muilla termeillä, esim. ympäristöpolitiikka + tavoitteet, kestävä kehitys + tavoitteet? 🤔

**Comment by mirmaid** [comment]
5 x Melindassa. Googlella _ilmastotavoitteet_ tuo tuplasti enemmän viitteitä.

**Comment by ilona-x** [comment]
YSO-kokouksen 1/2023 listalla myös **kestävän kehityksen tavoitteet**  #10999 .

**Comment by mariaforsen** [comment]
Mielestäni tämä on selkeä omana terminään, eikä ole niinkään kyse vain politiikasta, eli kannatan tätä aivan erillisenä käsitteenä, ks. https://termipankki.fi/tepa/fi/haku/ymp%C3%A4rist%C3%B6tavoite

Sanastossa on jo muitakin -tavoitteita: 
[kasvatustavoitteet](https://finto.fi/yso/fi/page/p2745)
[koulutustavoitteet](https://finto.fi/yso/fi/page/p25781)
[oppimistavoitteet](https://finto.fi/yso/fi/page/p11960)
[tulostavoitteet](https://finto.fi/yso/fi/page/p18641)

**Comment by fantsby-m** [comment]
Aika paljon käytössä yrityksillä ja organisaatioilla, kannatan.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään tarvittavia RT-suhteita.
