### ISSUE TITLE
eläinkaupat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11117]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eläinkaupat](http://www.yso.fi/onto/yso/p15729)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi lemmikkikaupat

**Perustelut ehdotukselle**

https://www.wikidata.org/wiki/Q220142
Jonkun verran tulee hittejä myös Googlella.

**Ehdottajan organisaatio**

Finto

**Comment by ilona-x** [comment]
Pitäisikö ohjaustermeiksi lisätä myös lemmikkitarvikeliikkeet/-kaupat ja eläintarvikeliikket/-kaupat?

**Comment by mirmaid** [comment]
Entä lemmikkieläintarvikeliikkeet/-kaupat...

**Comment by mirmaid** [comment]
^ Aika vähän käytetty kyllä 😅

**Comment by ilona-x** [comment]
Luulin ehdottaneeni tuota lemmikkieläintarvikekaupat/-liikkeet, mutta näköjään kirjoitin lyhyemmän muodon. 😃

**Comment by jarmosaarikko** [comment]
**eläinkauppa** on kyllä eri asia kuin eläintarvikeliike. Jälkimmäisessä voidaan myydä vaikkpa hevoshoitoon littyviä tarvikkeita, muttei yleensä eläimiä. En sekoittaisi näitä samaan käsitteeseen. Eläinkaupassa voi tosin olla tarvikkeita, esim. **akvaarioliikkeissä** on kalojen lisäksi akvaarioita. Tämä voisikin olla tässä ohjausterminä. 

Eläinten myynti ja ostaminen eli "eläinkauppa" onkin eri asia ja voi liittyä esim. hyötyeläimiin. Eihän mene sekaisin?

Ehdotan siis kaksi käsitettä:
- eläinkaupat KT lemmikkikaupat, akvaarioliikkeet, lemmikkieläinkaupat ja -liikkeet, en: pet stores - http://www.wikidata.org/entity/Q220142 (tämä kattaa jälkimmäisenkin)
- eläintarvikeliikkeet  KT lemmikkieläintarvikeliikkeet ja -kaupat, en: pet care stores, animal care stores
