### ISSUE TITLE
Villa Malmi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11110]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Villa Malmi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kulttuurihistoriallinen entinen asuinrakennus, nykyinen juhla- ja kokoustila Imatralla.

Ks. https://kareliangourmet.fi/villa-malmi/

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [rakennukset](http://www.yso.fi/onto/yso/p1786)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Villa Malmi (978-952-94-1955-5)

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Villa Malmi](http://finto.fi/yse/fi/page/Y511110)

**Comment by mariaforsen** [comment]
Sv. Villa Malmi
