### ISSUE TITLE
organiska gödselmedel

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11116]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[organiska gödselmedel](http://www.yso.fi/onto/yso/p4886)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeiksi luonnonlannoitteet (fi) ja naturgödsel (sv).

**Perustelut ehdotukselle**

https://www.biolan.fi/tuotteet/biolan-luonnonlannoite.html
https://www.biolan.fi/svenska/produkter/biolan-naturgodsel.html
https://www.wikidata.org/wiki/Q539815   (ks. norja)

**Ehdottajan organisaatio**

Finto

**Comment by mariaforsen** [comment]
https://odlamednaturen.se/kunskapsbank/definition/
