### ISSUE TITLE
fenoliset yhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11127]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[fenoliset yhdisteet](http://www.yso.fi/onto/yso/p23393)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeiksi fenolit (fi), phenols (en) ja fenoler (sv).

**Perustelut ehdotukselle**

Näitä ilmeisesti käytetään synonyymeina ja yksi fenoli on ilmeisesti myös fenolinen yhdiste.
Ks. https://www.wikidata.org/wiki/Q407142
Wikipedia: "Phenolic compounds are classified as simple phenols or polyphenols based on the number of phenol units in the molecule."
https://en.wikipedia.org/wiki/Phenols
Britannica: "phenol, any of a family of organic compounds characterized by a hydroxyl (―OH) group attached to a carbon atom that is part of an aromatic ring. Besides serving as the generic name for the entire family, the term phenol is also the specific name for its simplest member, monohydroxybenzene (C6H5OH)"
https://www.britannica.com/science/phenol

**Ehdottajan organisaatio**

Finto

**Comment by ilona-x** [comment]
YSOssa on eriksen [fenolit ](http://www.yso.fi/onto/yso/p6772)

**Comment by mirmaid** [comment]
Onkohan tämä ehdotus yhdistämisestä?

**Comment by ilona-x** [comment]
LCSH:
**phenols** http://id.loc.gov/authorities/subjects/sh85100676
Variants
Phenolic compounds
Phenolics

---

Kielitoimiston sanakirja:
**fenoli**
kem. aromaattisia yhdisteitä, joita käytetään mm. kemianteollisuuden raaka-aineina. 
https://www.kielitoimistonsanakirja.fi/#/fenoli?searchMode=all

**Comment by mirmaid** [comment]
Aineistoissa usein fenoliset yhdisteet / phenolic compounds. Googlella jkvr "phenols and phenolic compounds", mutta en nyt löydä selkeää lähdettä missä tätä erottelua avattaisiin. Löytääkö kukaan muu?

**Comment by ilona-x** [comment]
Huomiona tämäkin:

Wikipediassa englanniksi phenols & phenol
https://en.wikipedia.org/wiki/Phenols - tätä sivua ei ole suomeksi
https://en.wikipedia.org/wiki/Phenol - tällä suomenkielisenä vastinsivuna https://fi.wikipedia.org/wiki/Fenoli

Ja myös LCSHssa
Phenols http://id.loc.gov/authorities/subjects/sh85100676
Phenol http://id.loc.gov/authorities/subjects/sh85020087

**Comment by LeKorsu** [comment]
Terveyskirjastossa hakusanassa fenoli https://www.terveyskirjasto.fi/ltt00836, tuodaan esiin nimenomaan se että kyse on myrkyllisestä aromaattisesta yhdisteestä, kun taas täällä fenolihappojen yhteydessä https://www.leipatiedotus.fi/leipa-ravitsemuksessa/taysjyva/mita-taysjyvaviljasta-saa/bioaktiiviset-yhdisteet/fenolihapot.html sanotaan fenolisten yhdisteiden olevan antioksidantteja.

Ja vielä yksi sitaatti: "Fenoliset yhdisteet voivat vaikuttaa terveyteen monella tavalla. Ne saattavat mm. estää syöpäää ja vähentää sydän- ja verisuonitautien riskiä. Lisäksi joidenkin fenolisten yhdisteiden on todettu estävän allergioita sekä..."
https://jukuri.luke.fi/handle/10024/440272

Kemia on kilometrien päässä mukavuusalueeltani, mutta jos yhtään ymmärsin niin fenolia ja fenolisia yhdisteitä ei pidä yhdistää, koska ovat eri asia. Mutta pitääkö fenolit muuttaa yksikköön fenoliksi, jotta ero selkenee? 
Ähh, en minä tiedä tästä mitään...

**Comment by mariaforsen** [comment]
NE: "fenol: beteckning för karbolsyra, hydroxibensen, C6H5OH, den enklaste aromatiska hydroxiföreningen"
WP: "Fenoler (efter fenol) är kolföreningar med en eller flera hydroxigrupper bunden till en eller flera bensenringar."
WP: "In organic chemistry, phenols, sometimes called phenolics, are a class of chemical compounds consisting of one or more hydroxyl groups (−OH) bonded directly to an aromatic hydrocarbon group.[1] The simplest is phenol, C6H5OH. Phenolic compounds are classified as simple phenols or polyphenols based on the number of phenol units in the molecule."

Myös MESHissä on kaksi:
fenolit https://finto.fi/mesh/fi/page/D010636 ja 
fenoli https://finto.fi/mesh/fi/page/D019800

Eli varmaan on syytä pitää erillään fenolit/fenoliset yhdisteet ja fenoli, mutta olisiko päätermin muutos tarpeen, niin että toinen olisi fenoli?

**Comment by mirmaid** [comment]
Sain tähän vastauksen kolmelta henkilöltä kemian laitokselta, kaikki kannattivat käsitteiden **fenolit** ja **fenoliset yhdisteet** säilyttämistä erikseen sanastossa.

Fenoliset yhdisteet on laajempi käsite kuin fenolit. Fenoli on molekyyli jossa voi olla substituentteja, useita ja suuriakin, mutta fenoleista puhutaan kun kirjoittaja näkee fenolirakenteen korkeimmalla pririteetilla. Yhdiste on todennäköisesti nimettävissä "x-fenoliksi". 
 
Fenoliset yhdisteet taas on tuota "pääryhmää" välttelevä nimitys(joukko).  Meillä on fenoli(substituentti) tai useita osana (todennäköisesti) mutkikkaampaa rakennetta. Ääriesimerkki: Kun katsotaan ligniinin rakennetta, tai osaa sellaisista. Kyseiselle mutkikkaalle hässäkälle ei voi molekyyli(n)nimeä antaa. Rakenteessa on kuitenkin fenoliryhmiä siellä täällä. Se on pilkottunakin osa joukkoa fenoliset yhdisteet. Ja aika kauan saa pilkkoa että sieltä saa kiteytettyä puhdasta pikku molekyyliä jota fenoliksi uskaltaisin kutsua. Selvästi fenolisia yhdisteitä "kaikki", ligniinit ja sen pirstaleet.

Orgaanisen kemian puolelta:

1) fenolit ovat yhdisteitä, joiden pääasiallinen funktionaalinen ryhmä on fenoliryhmä (Aryyli-OH). Ne voidaan usein, mutta ei aina, myös nimetä jonkin sortin fenolina (ja tietty koko joukolla triviaalinimiä kuten katekoli, resorsinoli ...)

2) fenoliset yhdisteet on mielestäni hieman laajempi joukko yhdisteitä, jotka yleensä mielletään johonkin muuhun erilliseen ryhmään (esim flavonoidit), mutta sisältävät fenolisen hydroksiryhmän. 

Ovatko ne synonyymejä, onkin hyvä kysymys. Katsoisin, että fenoliset yhdisteet sisältävät alajoukkona fenolit, mutta kaikkia fenolisia yhdisteitä ei välttämättä voi kutsua fenoleiksi. Otetaanpa toinen esimerkki noiden flavonoidien lisäksi. Luonnollisessa aminohapossa tyrosiinissa on fenolinen hydroksiryhmä. Epäilen aika monen biokemistin tai miksei kemistinkin hieman kavahtavan ajatusta, että tyrosiinia kutsuttaisiin fenoliksi (ehkä se sitä on, mutta...). Sen sijaan fenoliseksi yhdisteeksi sitä voidaan kyllä hyvinkin kutsua.

**Comment by FinMeSHienPaimentaja** [comment]
Fenoliyhdisteet eikä fenoliset yhdisteet? Esim. kun antioksidanteista puhe, näytetään käytettävän fenoliyhdisteet (tosin voi olla haitallisiakin sellaisia esim. vedessä).

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
