### ISSUE TITLE
spinaalipuudutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11121]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

spinaalipuudutus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/337969

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [spinaalipuudutus](http://finto.fi/yse/fi/page/Y511121)

**Comment by ilona-x** [comment]
FinMeSH: spinaalipuudutus http://www.yso.fi/onto/mesh/D000775

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85126663

Lääketieteen termit: selkäydinpuudutus, lumbaalipuudutus, intratekaalipuudutus, subaraknoidaalipuudutus | puudutus jossa puudute ruiskutetaan lukinkalvo-onteloon

**Comment by mariaforsen** [comment]
Sv. ryggbedövning HT spinalanestesi, lumbalanestesi, ryggmärgsbedövning, spinalbedövning /ne, mesh, https://www.1177.se/behandling--hjalpmedel/smartbehandlingar-och-rehabilitering/ryggbedovning/
