### ISSUE TITLE
tilapäinen suojelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11123]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tilapäinen suojelu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Tilapäinen suojelu on tarkoitettu Ukrainasta sotaa pakeneville henkilöille. Tilapäisen suojelun tarkoituksena on, että heille voidaan tarjota nopeasti väliaikaista suojelua.

**Perustelut ehdotukselle**

Uusi käsite, jota tarvitaan kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston aineistot.

**Ehdottajan organisaatio**

JUHO, Leena Granholm
**Termiehdotus Fintossa:** [tilapäinen suojelu](http://finto.fi/yse/fi/page/Y511123)

**Comment by ilona-x** [comment]
JUHOssa: 
tilapäinen suojelu http://www.yso.fi/onto/juho/p14178

**Comment by LeKorsu** [comment]
sv tillfällig/kortvarig skyddande?

**Comment by mariaforsen** [comment]
Sv. tillfälligt skydd HT tillfälligt skydd för fördrivna personer
https://termipankki.fi/tepa/fi/haku/tilap%C3%A4inen%20suojelu
https://www.sanakirja.fi/custom/fi-en-sv/tilap%C3%A4inen%20suojelu
https://migri.fi/sv/tillfalligt-skydd
https://intermin.fi/sv/krisen-i-ukraina/tillfalligt-skydd
https://valtioneuvosto.fi/sv/-//1410869/en-smidig-fortsattning-pa-tillfalligt-skydd-for-ukrainare-tryggas-genom-en-speciallag
https://www.infofinland.fi/sv/temporary-protection-in-finland
https://www.consilium.europa.eu/sv/infographics/temporary-protection-displaced-persons/

**Comment by mirmaid** [comment]
Ei Melindassa. 

https://www.finlex.fi/fi/laki/ajantasa/2004/20040301#V18

**Comment by vnkgranhol** [comment]
VNK:n kääntäjät antoivat nämä käännökset 
tillfälligt skydd; tillfälligt skydd för fördrivna personer
temporary protection; temporary protection for displaced persons

**Comment by fantsby-m** [comment]
Perustuu EU-direktiiviin:
https://eur-lex.europa.eu/FI/legal-content/summary/temporary-protection-if-there-is-a-mass-influx-of-displaced-people.html
https://ec.europa.eu/commission/presscorner/detail/en/ip_22_1469 
Direktiivin mukainen suojelu otettiin nyt ensimmäistä kertaa käyttöön:
https://home-affairs.ec.europa.eu/policies/migration-and-asylum/common-european-asylum-system/temporary-protection_en

**Comment by fantsby-m** [comment]
> VNK:n kääntäjät antoivat nämä käännökset 
tillfälligt skydd; tillfälligt skydd för fördrivna personer 
temporary protection; temporary protection for displaced persons

IATE:n mukaan suom. pidempi muoto: _kotiseudultaan siirtymään joutuneiden henkilöiden tilapäinen suojelu_

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
