### ISSUE TITLE
perustuslait

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11128]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[perustuslait](http://www.yso.fi/onto/yso/p1594)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-sanastoon

**Perustelut ehdotukselle**

Tarvitaan julkaistujen perustuslakien kuvailussa, esim. https://melinda.kansalliskirjasto.fi/byid/000214426

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
