### ISSUE TITLE
betoniauto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11122]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

betoniauto

**Ehdotettu termi ruotsiksi**

betongbil

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan aineiston kuvailuun

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Johan Anderblad: Bojan och betongbilen 9789179778514

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [betoniauto](http://finto.fi/yse/fi/page/Y511122)

**Comment by jtuohini** [comment]
Olisiko ennemmin muodossa _**betoninkuljetusautot**_? Englanniksi ainakin _concrete mixing transport trucks_ ja _in-transit mixers_ (https://en.wikipedia.org/wiki/Concrete_mixer).

**Comment by mariaforsen** [comment]
Sv. betongbilar

**Comment by mirmaid** [comment]
Kumpikin muoto lienee ok.

**Comment by ilona-x** [comment]
Onkohan tälle miten paljon käyttöä tietoaineistossa? Ehdotuksessa esimerkkiaineistona on lasten kuvakirja (https://www.adlibris.com/fi/kirja/bojan-och-betongbilen-9789179778514) eikä Melindassa näytä olevan kertaakaan käytetty betoniautot termiä. 🤔 

edit. No ainakin YLEltä näyttää löytyvän paljon uutisia betoniautoista : https://yle.fi/uutiset/18-69889

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _betoniautot_. Ohjaustermiksi _betoninkuljetusautot_.

**Comment by tpalonen** [comment]
https://www.liquor.com/cement-mixer-shot-recipe-5180879
