### ISSUE TITLE
kaaviot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11129]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kaaviot](http://www.yso.fi/onto/yso/p24172)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi graafit (kaaviot). Graafit-käsitteelle ehkä sulkutarkenne (matematiikka) tms. https://finto.fi/yso/fi/page/p26018

**Perustelut ehdotukselle**

https://infograafikko.fi/blogi/paremmat-graafit-esityksiin
https://www.wikidata.org/wiki/Q141488
https://www.wikidata.org/wiki/Q28923

**Ehdottajan organisaatio**

Finto

**Comment by mirmaid** [comment]
Sanastossa myös _diagrammit_. En ole varma, onko (matematiikka) tarkenteena riittävän tarkka, ehkä (verkkoteoria).

**Comment by YSO-kokous** [comment]
**Päätös**

Sulkutarkenne _verkkoteoria_ graafeille. Diagrammeille ohjaustermi _graafit (kaaviot)_.
