### ISSUE TITLE
tiekartat (suunnitelmat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11125]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tiekartat (suunnitelmat)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Konkreettisen merkityksensä lisäksi tiekartalla tarkoitetaan nykyään laajemmin jonkinlaista pitkän aikavälin suurimittaista suunnitelmaa. (Kotimaisten kielten keskus)

**Perustelut ehdotukselle**

Tarvitaan Valtioneuvoston julkaisujen kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston aineistot.

**Ehdottajan organisaatio**

VNK/JUHO Leena Granholm
**Termiehdotus Fintossa:** [tiekartat (suunnitelmat)](http://finto.fi/yse/fi/page/Y511125)

**Comment by ilona-x** [comment]
SLM-ehdotus samaan aiheeseen liittyen: tiekartat #10579

**Comment by LeKorsu** [comment]
Onkohan tämä kuinka pitkäaikainen ilmaus tässä merkityksessä? Eikö kävisi suunnitelmien ohjaustermiksi?
tiekartat (suunnitelmat) KÄ suunnitelmat

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään yllä oleva ehdotus.
