### ISSUE TITLE
vuokrasäännöstely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11120]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vuokrasäännöstely](http://www.yso.fi/onto/yso/p9555)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT vuokrasääntely

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
_Vuokrasääntely_ olisi mielestäni parempi päätermi

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan päätermiksi _vuokrasääntely_.
