### ISSUE TITLE
tapahtuma-ala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11133]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tapahtuma-ala

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Valtioneuvoston asiakirjojen, nettisivujen ja julkaisujen kuvailu.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtioneuvoston asiakirjojen, nettisivujen ja julkaisujen kuvailu.

**Ehdottajan organisaatio**

VNH/JUHO Leena Granholm
**Termiehdotus Fintossa:** [tapahtuma-ala](http://finto.fi/yse/fi/page/Y511133)

**Comment by LeKorsu** [comment]
sv evenemangsbranschen?

**Comment by mariaforsen** [comment]
Sv. evenemangsbranschen HT evenemangssektorn, evenemangsnäringen, evenemangsindustri
Entä tapahtumateollisuus, RT vai OT?

**Comment by mirmaid** [comment]
Nyt löytyy _tapahtumatuotanto_. Olisi kyllä kiinnostavaa nähdä vähän tarkemmin jotain aineistoesimerkkejä.

**Comment by tpalonen** [comment]
Tämähän on covidin myötä ollut paljon otsikoissa. Ylellä ja hs.fi:ssä paljon uutisia, samoin esim. okm.fi:ssä.

RT kulttuuriala?

**Comment by ilona-x** [comment]
Alan etujärjestö on nimeltään Tapahtumateollisuus ry.
https://www.tapahtumateollisuus.fi/mita-on-tapahtumateollisuus/

**Comment by fantsby-m** [comment]
Mahdollisia aineistoesimerkkejä
https://melinda.kansalliskirjasto.fi/byid/018093424
https://melinda.kansalliskirjasto.fi/byid/013659488
https://melinda.kansalliskirjasto.fi/byid/017641156

**Comment by mirmaid** [comment]
Lähinnä mietin, tuleeko vähän ajan päästä palautetta, jossa kritisoidaan _tapahtumatuotannon_ ja _tapahtuma-alan_ päällekkäisyyttä ja perätään määritelmiä, kuten nyt _musiikkiala_ ja _elokuva-ala_ -käsitteiden osalta (niissä parina -teollisuus).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään ohjaustermi _tapahtumateollisuus_.
