### ISSUE TITLE
NLP

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11130]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[NLP](http://www.yso.fi/onto/yso/p14701)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Parempi yläkäsite hoitomenetelmät, teoriat tms.?

**Perustelut ehdotukselle**

Ei taida olla mikään varsinainen "tutkimusmenetelmä". Tämä lyhenne voi myös viitata muihin merkityksiin. https://fi.wikipedia.org/wiki/Neurolingvistinen_ohjelmointi
https://termipankki.fi/tepa/fi/haku/nlp

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Suosittelisin käsitteen preflabeliksi pitkää muotoa.
Vrt. "natural language processing" asiasanaa käytetty 100 kertaa Melindassa.
"natural language programming" asiasanaa käytetty 2 kertaa Melindassa.
NLP-käsitettä on taidettu pari kertaa käyttää väärinkin. Ks. https://melinda.kansalliskirjasto.fi/byid/002546958

**Comment by mariaforsen** [comment]
Tämä käsite oli siis ryhmässä 55 ja vaihtoehtoisena terminä neurolinguistic programming. 
https://www.nlpyhdistys.fi/tietoa/usein-kysyttya/
Eli jos halutaan myös natural language processing-merkityksessä, tarvitaan varmaan uutta termiä.
https://fi.wikipedia.org/wiki/Luonnollisen_kielen_k%C3%A4sittely
Siihen liittyen meillä on nyt vain https://finto.fi/yso/sv/page/p26762?clang=fi

**Comment by mirmaid** [comment]
Eli ehdotettu ohjaustermin vaihtoa päätermiksi ja hierarkian tarkistusta. Ehdotetuista yläkäsitteistä kannattaisin ehkä hoitomenetelmät-laaria, koska useammassa paikassa todettiin, että NLP ei ole yhtenäinen teoria.

**Comment by ilona-x** [comment]
FinMeSH:
neurolingvistinen ohjelmointi 
Ohjaustermit NLP
http://www.yso.fi/onto/mesh/D020557

**Comment by nikopartanen** [comment]
Minustakin menee käsitteen _natural language processing_ kanssa niin päällekkäin, että noita preflabeleja kannattaa miettiä. Tämän NLP:n harjoittajat eivät varmasti myöskään yleisesti tiedä, että termi on missään muussa käytössä, joten varmasti on kaikenlaista käyttöä.

**Comment by mariaforsen** [comment]
Muutetaan ruotsiksi NLP > neurolingvistisk programmering

https://id.kb.se/term/sao/Neurolingvistisk%20programmering
https://mesh.kib.ki.se/term/D020557/neurolinguistic-programming
https://www.psykologiguiden.se/psykologilexikon/?Lookup=neurolingvistisk+programmering%2C+NLP
