### ISSUE TITLE
physical activeness

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11132]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[physical activeness](http://www.yso.fi/onto/yso/p23102)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

physical activity

**Perustelut ehdotukselle**

Tutkimuskirjallisuudessa käytetty vastine suomenkieliselle termille "fyysinen aktiivisuus" on physical activity. Myös merkittävät järjestöt kuten WHO ja American College of Sports Medicine käyttävät termiä "physical activity" esimerkiksi liikkumisen suositusten yhteydessä (physical activity guidelines).

**Ehdottajan organisaatio**

Liikuntatieteellinen tiedekunta, Jyväskylän yliopisto

**Comment by tpalonen** [comment]
Korjattu ehdotetusti.
