### ISSUE TITLE
luontoselvitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1113]
#### Ehdotettu termi suomeksi

luontoselvitykset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
#### Lähde

Lähde: Luontoinventointien ja -selvitysten kehittäminen... (Ympäristö 7/2003)

**Luontipäivämäärä:** 02.04.2004

**Muokkauspäivämäärä:** 2.4.2004, 2.4.2004, 13.8.2004, 16.12.2008

**Voyager-id:** 130411

**Termiehdotus Fintossa:** [luontoselvitykset](http://finto.fi/yse/fi/page/Y330411)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2616

**Comment by mirmaid** [comment]
Tarvittu tässä: https://www.utupub.fi/handle/10024/175920

**Comment by mirmaid** [comment]
6 viitettä Melindassa, mutta osittain käytetty genrenä.

**Comment by mariaforsen** [comment]
Sv. naturinventeringar HT naturutredningar
https://www.syke.fi/sv-FI/Aktuellt/Ny_handbok_for_utarbetande_av_naturutred(62166)
https://ym.fi/sv/-/ny-handbok-for-utarbetande-av-naturutredningar-och-bedomning-av-konsekvenser-for-naturen
https://www.ymparisto.fi/sites/default/files/documents/SYKEra_47_2021_Luontoselvitykset%20ja%20luontovaikutusten%20arviointi.pdf

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon. Tutkittaneen sopisiko luontokartoitukset tälle ohjaustermiksi.
