### ISSUE TITLE
tanssimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11141]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tanssimusiikki](http://www.yso.fi/onto/yso/p181)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Siirretään SLM:n puolella "csárdásit", "jenkat" ja "moriskat" tämän suppeammiksi termeiksi (nykyisen "musiikki"-termin alta)

**Perustelut ehdotukselle**

Jääneet aiemmin siirtämättä muun tanssimusiikin mukana.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Ok/SLM
