### ISSUE TITLE
survivalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11143]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

survivalismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

survivalism

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vakiintunut käsite ja ilmiö, jolle ei ole asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Survivalismi), [LCSH](https://id.loc.gov/authorities/subjects/sh85130884.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Douglas Rushkoff: Survival of the richest : escape fantasies of the tech billionaires

**Ehdottajan organisaatio**

Kirjastopalvelu / PA

**Comment by ilona-x** [comment]
survivalismi hyväksytty sanastoon joulukuun 2022 YSO-kokouksessa. https://github.com/Finto-ehdotus/YSE/issues/10798#issuecomment-1333507265
