### ISSUE TITLE
kranio-sakraaliterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11148]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kranio-sakraaliterapia](http://www.yso.fi/onto/yso/p14699)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

kraniosakraaliterapia

**Perustelut ehdotukselle**

yleisempi käytetty muoto 

**Ehdottajan organisaatio**

amk

**Comment by mariaforsen** [comment]
Sv. > kraniosakralterapi?
https://termipankki.fi/tepa/fi/haku/kraniosakraaliterapia
https://www.fysios.fi/palvelut/kraniosakraaliterapia
https://sv.wikipedia.org/wiki/Kraniosakralterapi

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Muutetaan nykyinen muoto ohjaustermiksi.
