### ISSUE TITLE
sukupuoleen perustuva häirintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11149]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sukupuoleen perustuva häirintä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

-

**Perustelut ehdotukselle**

Saimme finto-postia Lastenkirjainstituutista koskien KAUNOa ja YSOa: "nykyisin puhutaan paitsi seksuaalisesta häirinnästä, myös sukupuoleen perustuvasta häirinnästä (ks. esim. https://tasa-arvo.fi/hairinta). --- ehdottaisin, että sanastoihin lisättäisiin sukupuoleen perustuva häirintä -asiasana"

**Ehdotettu yläkäsite YSOssa (LT)**

 [häirintä](http://www.yso.fi/onto/yso/p11442)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [seksuaalinen häirintä](http://www.yso.fi/onto/yso/p5385)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

Finto
**Termiehdotus Fintossa:** [sukupuoleen perustuva häirintä](http://finto.fi/yse/fi/page/Y511149)

**Comment by mirmaid** [comment]
Ihan kannatettava ehdotus, mutta sanastossa on _sukupuolisyrjintä_ ja _sukupuoleen perustuva vaino_. Vaatiiko jotain määrittelyä erityisesti suhteessa ensimmäiseen?

**Comment by mariaforsen** [comment]
Sv. trakasserier på grund av kön HT trakasserier på grund av könsidentitet eller könsuttryck
https://tasa-arvo.fi/sv/sexuella-trakasserier
https://syrjinta.fi/sv/trakasserier
https://finlex.fi/sv/laki/ajantasa/1986/19860609
https://sv.wikipedia.org/wiki/Trakasserier_p%C3%A5_grund_av_k%C3%B6n

**Comment by mirmaid** [comment]
**Sukupuoleen perustuva häirintä**

Sukupuoleen perustuvalla häirinnällä tarkoitetaan henkilön sukupuoleen liittyvää ei-toivottua käytöstä, joka ei ole luonteeltaan seksuaalista ja jolla tarkoituksellisesti tai tosiasiallisesti loukataan tämän henkistä tai fyysistä koskemattomuutta ja jolla luodaan uhkaava, vihamielinen, halventava, nöyryyttävä tai ahdistava ilmapiiri. Sukupuoleen perustuva häirintä voi olla esimerkiksi sukupuoleen liittyvää halventavaa nimittelyä. Sukupuoleen perustuva häirintä on tasa-arvolain mukaan syrjintää.

**Sukupuolisyrjintä**

Sukupuoleen perustuvaa syrjintää on henkilön asettaminen sukupuolen vuoksi eriarvoiseen asemaan. Syrjintää on myös seksuaalinen tai sukupuoleen perustuva häirintä tai ahdistelu. Kohtelu, joka vaikuttaa sukupuoleen, sukupuoli-identiteettiin tai sukupuolen ilmaisuun nähden neutraalilta, mutta jonka vaikutuksesta henkilöt voivat tosiasiallisesti joutua epäedulliseen asemaan sukupuolen perusteella, on välillistä syrjintää. Tasa-arvolaki kieltää sukupuoleen perustuvan välittömän ja välillisen syrjinnän.

https://thl.fi/fi/web/sukupuolten-tasa-arvo/sukupuoli/tasa-arvosanasto

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Määritelmät muokataan esimerkiksi tasa-arvosanaston pohjalta.
