### ISSUE TITLE
paruusia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11142]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

paruusia

**Ehdotettu termi ruotsiksi**

parusi

**Ehdotettu termi englanniksi**

parousia

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

teologinen käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 Jeesuksen toinen tuleminen, second coming, Kristi återkomst

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [eskatologia](http://www.yso.fi/onto/yso/p3913)

**Vastaava käsite muussa sanastossa**

 [evl.fi](https://evl.fi/sanasto/-/glossary/word/Paruusia), [wikipedia](https://fi.wikipedia.org/wiki/Jeesuksen_toinen_tuleminen), [wikipedia](https://en.wikipedia.org/wiki/Second_Coming)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Jeesuksen paluun laskelmat / Harri Veijonen

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [paruusia](http://finto.fi/yse/fi/page/Y511142)

**Comment by mirmaid** [comment]
Kerran Melindassa, varmaankin tähän asti kuvailtu _eskatologia (& Jeesus Kristus)_.

**Comment by ilona-x** [comment]
LCSH:
**Second Advent**       http://id.loc.gov/authorities/subjects/sh85119409
Variants
    Jesus Christ--Second Advent
    Parousia
    Second Coming of Christ

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Kristi%20%C3%A5terkomst

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Ohjaustermiksi _Jeesuksen toinen tuleminen_.
