### ISSUE TITLE
lait

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11165]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lait](http://www.yso.fi/onto/yso/p1464)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään myös SLM-sanastoon

**Perustelut ehdotukselle**

Tarvitaan SLM-sanastoon, jotta laeista tehtävissä teostietueissa saadaan ilmaistu teoksen tyyppi asianmukaisesti.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
lakikokoelmat, lait (lakikokoelmat), lakikirjat KÄ säädöskokoelmat
säädöskokoelmat: toinen YK kokoomateokset

**Comment by jtuohini** [comment]
LCGFT-vastine: [**Statutes and codes**](http://id.loc.gov/authorities/genreForms/gf2011026611).
