### ISSUE TITLE
Ruotsi-ottelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11164]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Ruotsi-ottelu

**Ehdotettu termi ruotsiksi**

Finnkampen

**Ehdotettu termi englanniksi**

Finland-Sweden track and field match????

**Tarkoitusta täsmentävä selite**

https://ruotsiottelu.fi/. Finnkampenin kielivastineeksi on viime vuosina otettu käyttöön Ruotsi-ottelu, Suomi-Ruotsi -ottelun sijasta.

**Perustelut ehdotukselle**

Vanhan julkaisun asiasanotusta tarkastellessa huomasin, että tämä vanha ja perinteikäs urheilukilpailu puuttuu sanastosta.

**Ehdotettu yläkäsite YSOssa (LT)**

 [urheilukilpailut](http://www.yso.fi/onto/yso/p1934)

**Ehdotetut temaattiset ryhmät**

 [97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)

**Vaihtoehtoiset termit**

 KT Suomi-Ruotsi -yleisurheilumaaottelu, KT Suomi-Ruotsi -ottelu

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tiina Vainio: Siniristi ja superlatiivi

**Ehdottajan organisaatio**

Yle Arkisto
**Termiehdotus Fintossa:** [Ruotsi-ottelu](http://finto.fi/yse/fi/page/Y511164)

**Comment by jtuohini** [comment]
Kyseessä vuotuinen nimetty tapahtuma eli RDA:n näkökulmasta kokous ja kuuluu siis Kantoon, ei asiasanastoon. Toimijakuvailupalvelua pyydetty tekemään toimija-auktoriteetti tästä.

**Comment by jtuohini** [comment]
On nyt valmiina Kannossa: http://urn.fi/URN:NBN:fi:au:finaf:000221180

**Comment by mariaforsen** [comment]
Ruotsinkielinen muoto ei ole nyt käytettävissä, mutta toivotaan että pian tulee käyttöön.
