### ISSUE TITLE
osallistava johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11169]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

osallistava johtaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

participative management

**Tarkoitusta täsmentävä selite**

https://lluh.org/health-professionals/nursing-patient-care-services/professional-practice-model/professional-governance
"Professional governance is a collaborative governance structure that gives professionals, such as nurses, a voice regarding issues that affect their practice.
Professional governance is a professional model that empowers direct-care nurses to contribute collaboratively as decision makers regarding the nursing practice setting. " 

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa, samaa aihetta käsitteleviä teoksia löyty Melindasta

**Ehdotettu yläkäsite YSOssa (LT)**

 [johtaminen](http://www.yso.fi/onto/yso/p554)

**Ehdotetut temaattiset ryhmät**

 [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524), [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538), [78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525)

**Vaihtoehtoiset termit**

 professional governance, transformational leadership

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://Management--Employee participation.)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018697909

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [osallistava johtaminen](http://finto.fi/yse/fi/page/Y511169)

**Comment by mirmaid** [comment]
3 x Melindassa.

https://en.wikipedia.org/wiki/Participatory_management

**Comment by mariaforsen** [comment]
Sv. deltagande ledning, deltagande ledarskap, inkluderande ledning..?
https://www.sanakirja.fi/custom/fi-en-sv/osallistava
https://termipankki.fi/tepa/fi/haku/osallistava%20johtaminen

**Comment by mirmaid** [comment]
Näköjään hoitotyön yhteydessä käytetään termiä professional governance: _Professional governance is a collaborative governance structure that gives professionals, such as nurses, a voice regarding issues that affect their practice. Professional governance is a professional model that empowers direct-care nurses to contribute collaboratively as decision makers regarding the nursing practice setting._

**Comment by mirmaid** [comment]
_Things organizations can do to enhance **professional governance** and shared decision-making: ...Fully invest in nurses collaborating with leaders to make decisions (**shared decision-making**) rather than requesting nurse input (**participatory management**) on policies and procedures impacting practice_ [https://oregoncenterfornursing.org/professional-governance-and-shared-decision-making](https://oregoncenterfornursing.org/professional-governance-and-shared-decision-making)

Eli ehkä tällä on hoitotyön kontekstissa oma terminsä englanniksi ja hiukan omanlaisensa merkitys myös?

**Comment by YSO-kokous** [comment]
**Päätös**

Periaatteessa voidaan hyväksyä. Kysytään ehdottajan organisaatiolta lisätietoja englanninkielisten termien suhteesta ja tarkasta käyttötarpeesta.

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään seuraavaan kokoukseen.

**Comment by mirmaid** [comment]
Ehdottajan organisaation vastauksesta:

Business Source -tietokannan sanastossa tällaista:
 
PARTICIPATIVE leadership Use INCLUSIVE leadership    
PARTICIPATIVE management Use EMPLOYEE participation in management  
 
Tuo collaborative leadership enemmän jaettua johtamista, kuten myös Business Source viittaa:
COLLABORATIVE leadership Use SHARED leadership    
... ja 
CINAHL
Participatory Management Use: Shared Governance
- tämä siis eri asia kuin osallistava..
- ja näyttää CINAHListakin tuovan shared governance -asiaa asiasanoihin.

**Comment by mirmaid** [comment]
Shared leadership olisi suomeksi _jaettu johtajuus_. Jos tämä _osallistava johtaminen_ otetaan, eng. labeliksi ehkä sitten participative management (tai tuo employee participation in management) ja professional governance ehkä ohjaustermiksi (?)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Englanniksi mahdollisesti muoto _participative management_.

**Comment by mariaforsen** [comment]
Sv.  deltagande ledarskap HT deltagande ledning, participativt ledarskap, inkluderande ledning (deltagande ledarskap) (fi. inklusiivinen johtaminen)
https://www.sanakirja.fi/custom/fi-en-sv/osallistava
https://termipankki.fi/tepa/fi/haku/osallistava%20johtaminen
https://www.theseus.fi/bitstream/handle/10024/266559/Olika%20generationers%20syn%20p%C3%A5%20ledarskap%20-%20En%20enk%C3%A4tstudie%20i%20Svensk-Finland.pdf?sequence=2&isAllowed=y
https://www.ledarskap.top/vad-menas-med-ett-inkluderande-ledarskap
https://www.tng.se/ledarskap/inkluderande-ledarskap/
https://www.hrviesti.fi/natiivi/2273/hyva-johtaja-innostaa-osallistumaan
https://gupea.ub.gu.se/bitstream/handle/2077/1351/Nr_37_JJ,KM.pdf?sequence=1 : "Ordet participativ kommer från engelskans participative och betyder gemensam. (Nationalencyklopedin, 2004). När vi talar om participative management menar vi en företagsledning där de anställda medverkar.  "

**Comment by fantsby-m** [comment]
Tässä väitöksessä (joka oli aineistona ehdotuksessa) engl. termi on _professional governance_. Ks. esim. s. 30 viimeisestä kappaleesta eteenpäin, pohdintaa termistä ja sen merkityksestä.
https://erepo.uef.fi/handle/123456789/29005
