### ISSUE TITLE
narratiivit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1117]
#### Ehdotettu termi suomeksi

narratiivit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/ysa/ryhma_52)
#### Lähde

Lähde: web-Facta
#### Käsitteen määritelmä

Historiantutkimuksessa kerronnallisuuteen, kertovaan esitysmuotoon, historiantutkimuksen metodologiaan sekä laajemminkin inhimilliseen ajan kokemiseen ja jäsentämiseen liittyvä käsite. Narratiivi saatetaan samastaa kertomukseen ja näkemykseen kerronnallisesta esitystavasta historiankirjoituksen ominaispiirteenä, joka auttaa erottamaan historian vars. yhteiskuntatieteistä. Toisaalta narratiivin ongelma ei liity vain esitystapaan, vaan se kuvaa myös syvemmin historiantutkimuksen koko suhdetta kohteenaan olevaan todellisuuteen. Esim. ransk. filosofin Paul Ricoeurin mukaan narratiivi, ajan kokeminen kertomuksellisesti jäsentyneessä muodossa, on ihmisen kokemusmaailmaan liittyvä antropologinen perusseikka

**Luontipäivämäärä:** 02.04.2004

**Muokkauspäivämäärä:** 4.12.2008, 2.4.2004, 20.8.2004, 22.6.2004, 16.12.2008, 05.02.2009

**Voyager-id:** 130415

**Termiehdotus Fintossa:** [narratiivit](http://finto.fi/yse/fi/page/Y330415)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin poliittisen narratiivin merkityksessä https://www.hybridcoe.fi/publications/hybrid-coe-research-report-8-russia-and-china-as-hybrid-threat-actors-the-shared-self-other-dynamics/

**Comment by krinay** [comment]
YSOssa on mm. _narratiivisuus_, _kerronta_, _narratiivinen tutkimus_, _kertomukset_, _diskurssi_ yms. 

Onko mahdollista määritellä käsite _narratiivit_ niin, että se toisi sanastoon jotakin lisäarvoa ja että sen käyttö tulisi olemaan suhteellisen johdonmukaista? (Olen itsekin joskus kaivannut tällaista termiä, mutta näiden epäilysten takia jättänyt ehdotuksen tekemättä. Hyvä, jos riittävän selvä määritelmä löytyy.) 

Kielitoimiston sanakirja:

**narratiivi**
kertomus, tarina, kertova esitys.
Erik.
jtak tulkintaa t. näkökulmaa painottavasta asioiden esittämistavasta.

_Kansallisen narratiivin keskittyminen saavutuksiin._
_Poliittinen narratiivi._
_Vaihtoehdottomuuden narratiivi_ asian esittäminen niin, ettei ole vaihtoehtoja.

**Comment by mariaforsen** [comment]
Onko mahdollista ottaa tarkkana terminä "poliittiset narratiivit"? Esim. https://lauda.ulapland.fi/bitstream/handle/10024/63767/Laurila_gradu_painoon.pdf?sequence=1&isAllowed=y 
Tai mahdollisesti laajempana, mutta niin ettei kata mitä tahansa kertomusta, esim. narratiivit (esittämistapa)?
Vrt. https://termipankki.fi/tepa/fi/haku/narratiivi
Sv. politiska narrativ, narrativ (framställningssätt)..?

**Comment by fantsby-m** [comment]
Esittämistapa-näkökulmasta riittäisi usein varmaankin _diskurssi_.
**_Jos_** narratiivin hyväksyisi niin sekin voisi olla yksikössä, jolloin ei sekoittuisi niin helposti kertomuksiin, ja sama yläkäsite & ryhmä kuin diskurssilla myös?

**Comment by mirmaid** [comment]
On kyllä aika hankala. _Kertomukset_ löytyy vastaavassa merkityksessä ja myös yllä mainitussa Pieni maa preerialla -julkaisussa kirjoittaja käyttää sitä narratiivin ohella. Usein varmaan myös _diskurssista_ puhutaan, kun puhutaan narratiiveista. Ymmärrän tarpeen, mutta hakijan kannalta tilanne ei välttämättä helpotu Kristiinan mainitsemista syistä. 

_Poliittiset narratiivit_ on mahdollinen, suomeksi aika vähän käytetty. https://en.wikipedia.org/wiki/Political_narrative Tulisiko ohjaustermiksi jotain kertomukset-tyyppistä?
Esim. https://melinda.kansalliskirjasto.fi/byid/017458821

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _poliittiset narratiivit_.

**Comment by mariaforsen** [comment]
Sv. politiska narrativ
https://www.su.se/sok-kurser-och-program/mk7026-1.411891
https://mfaa.abo.fi/article/vart-politiska-narrativ-binder-oss/
