### ISSUE TITLE
manganiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11199]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

manganiitti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utu.fi/fi/ajankohtaista/vaitos/manganiitista-tehty-ohutkalvo-toimii-memristorina-vaitos-msc-azar-beiranvand

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [manganiitti](http://finto.fi/yse/fi/page/Y511199)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Manganiitti
http://id.loc.gov/authorities/subjects/sh99003720

**Comment by mariaforsen** [comment]
Sv. manganit
