### ISSUE TITLE
luokkaopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11201]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luokkaopetus](http://www.yso.fi/onto/yso/p25840)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Saimme palautetta Finto-sähköpostiin: "teillä on sanastossa 'luokkatyöskentely' ja 'luokkaopetus'. Olisivatko nämä termit ehkä jäämässä pois käytöstä ja korvautuneet termeillä 'lähiopiskelu' ja 'lähiopetus'? Englanniksi käännös voisi olla vaikkapa 'onsite learning' ja 'onsite teaching'. Sitten on hybridiopetus, joka poikkeaa monimuoto-opetuksesta siten, että opetustilanteessa opettaja opettaa fyysisesti läsnä olevia että etänä osallistuvia samanaikaisesti. Monimuoto-opiskelun käsittäisin niin, että se on opetusmuoto, jossa on vaihtelevasti etäopetusta, lähiopetusta ja mahdollisesti muita muotoja. Olisi hyvä antaa määritelmät YSOssa? Törmäsin näihin asioihin etsiessäni YSOsta asiasanoja eurooppalaisen ELSST-tesauruksen uusien asiasanojen suomennoksiksi. Yritän pitää ne yhteneväisenä YSOn kanssa.

**Perustelut ehdotukselle**

ks ed

**Ehdottajan organisaatio**

tuni.fi

**Comment by jtuohini** [comment]
Lähiopiskelua voi olla esimerkiksi ampumaharjoitus, paikkana ennemmin ampumarata kuin luokkahuone, ja monella alalla on erikseen teoriaa luokkaopetuksena ja käytännön harjoitteita lähiopetuksena muualla kuin varsinaisessa luokassa, joten _luokka_- ja _lähi_-alkuisia termejä ei voi vaihtaa päittäin. Määritelmät sanastoon eittämättä tarvittaisiin (kaikista asiasanoista).

**Comment by mirmaid** [comment]
Mielestäni _luokkaopetus_ ja _luokkatyöskentely_ ovat aika läpinäkyviä termejä. Ensin mainitulle löytyy määritelmä, jos tarvitaan: https://termipankki.fi/tepa/fi/haku/luokkaopetus. Jälkimmäiselle en onnistunut löytämään, mutta en kyllä tosiaan itse koe, että kumpikaan olisi mitenkään vaikeatulkintainen.

^ Jos YSOsta haluttaisiin tehdä hakuteos, tarvittaisiin nykyistä paljon isommat ylläpitoresurssit.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
