### ISSUE TITLE
Turun palo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11217]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Turun palo

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Hyvin usein tarvittu termi sekä tieto- että kaunokirjallisuudessa. Moninaisesti yhteiskuntaan vaikuttava historiallinen tapahtuma. Samantyyppisiä ulkomaisia tapahtumia auktorisoitu kuten esim. Venäjän hyökkäys Ukrainaan 2022 jne.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540)

**Vaihtoehtoiset termit**

 ohjaustermiksi: Turun palo (1827) 

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Hovimäki

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Turun palo](http://finto.fi/yse/fi/page/Y511217)

**Comment by jtuohini** [comment]
Sisällönkuvailuoppaassa juurikn tämä sattumus on esimerkkinä muodossa: "647 _4  |a  Turun palo  |c  (Turku, Suomi :  |d  1827)". Vuosiluku on vältämätön osa hakutietoa, koska Turun paloja on useita, t.s. miten kuvailla esim. seuraava aineisto: https://blogit.utu.fi/suomenhistoria/turun-palo-1681-mita-raastuvanoikeuden-poytakirjat-kertovat/

**Comment by jtuohini** [comment]
Lisäksi pitää huomioida Kannnossa jo oleva [**Turun Palo (yhdistys)**](http://urn.fi/URN:NBN:fi:au:finaf:000031754).

**Comment by mirmaid** [comment]
Varmaan aika selvää mihin paloon tällä viitataan, mutta voidaan auktorisoida myös aikatarkenteella _Turun palo (1827)_.

**Comment by mariaforsen** [comment]
Sv. Åbo brand (1827) HT Åbo brand

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q2989671
Great Fire of Turku https://en.wikipedia.org/wiki/Great_Fire_of_Turku

**Comment by tpalonen** [comment]
PÄÄTÖS

auktorisoidaan aikatarkenteella _Turun palo (1827)_
