### ISSUE TITLE
Goldbachin konjektuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11213]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Goldbachin konjektuuri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153603

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Goldbachin konjektuuri](http://finto.fi/yse/fi/page/Y511213)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Goldbachin_konjektuuri
http://id.loc.gov/authorities/subjects/sh97007184

**Comment by mariaforsen** [comment]
Sv. Goldbachs förmodan HT Goldbachs hypotes
https://fof.se/artikel/2013/7/tva-matematiska-genombrott/
https://books.google.fi/books?id=GgoaAwAAQBAJ&pg=PA96&lpg=PA96&dq=%22goldbachs+f%C3%B6rmodan%22&source=bl&ots=w2QNhW95BW&sig=ACfU3U3Ql5MAWaCdi1-m_QJtPF8sltWKPQ&hl=sv&sa=X&ved=2ahUKEwjH3rSMh739AhUQjosKHS9yD804FBDoAXoECBMQAw
