### ISSUE TITLE
perätilasynnytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11215]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

perätilasynnytys

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/343862

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [perätilasynnytys](http://finto.fi/yse/fi/page/Y511215)

**Comment by mirmaid** [comment]
Tai vaihtoehtoisesti _sikiön tarjonta_, http://www.yso.fi/onto/mesh/D007746.

**Comment by mirmaid** [comment]
Melindassa 11 kertaa perätilasynnytys, 9 kertaa perätarjontaraskaus, 2 kertaa sikiön tarjonta.

**Comment by mirmaid** [comment]
Lääketieteen termit: sikiön tarjonta: presentaatio | termi joka ilmoittaa, mikä sikiön osa on synnytyksessä alimpana synnytyskanavassa (tarjoutuvana osana). Tällä on 15 alakäsitettä (mm. perätarjonta).

perätilasynnytys: perätarjontasynnytys | synnytys jossa sikiö on pää ylöspäin

**Comment by mariaforsen** [comment]
Sv. 
-fosterbjudning
-sätesförlossning HT sätesbjudning, sätesändläge

**Comment by mirmaid** [comment]
Käytännössä molemmatkin näistä olisivat ihan ok ja lääketieteen väitöskirjoissa varmaan käyttöä tulee aina välillä.

**Comment by jarmosaarikko** [comment]
MeSH "**perätila**"  http://www.yso.fi/onto/mesh/D001946
[Sätesbjudning](https://finto.fi/mesh/fi/page/D001946?clang=sv)
[Breech Presentation](https://finto.fi/mesh/fi/page/D001946?clang=en)  
KT perätilasynnytys
http://www.wikidata.org/entity/Q813687

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _perätilasynnytys_ ja _sikiön tarjonta_.
