### ISSUE TITLE
Waringin ongelma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11212]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Waringin ongelma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/153603

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Waringin ongelma](http://finto.fi/yse/fi/page/Y511212)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Waringin_probleema
http://id.loc.gov/authorities/subjects/sh91006162

**Comment by mariaforsen** [comment]
Sv. Warings problem
