### ISSUE TITLE
korvaushoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11221]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[korvaushoito](http://www.yso.fi/onto/yso/p979)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

termi korvaushoito ei ole ohjausterminä termin hoitomenetelmät kuvailutiedoissa

**Perustelut ehdotukselle**

Minusta korvaushoito kuuluisi saattaa ohjaustermiksi . Jos on syy miksi ei niin  kuuulisin sen mielellläni

**Ehdottajan organisaatio**

Anne-Mari Salmela / Turun yliopiston kirjasto asalmela{at]utu.fi

**Comment by mariaforsen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8029

**Comment by mirmaid** [comment]
Korvaushoito ohjausterminä hoitomenetelmät-käsitteelle toisi haussa valtavasti hälyä, jos järjestelmässä haku ohjaustermillä tuo kaikki päätermillä kuvaillut viitteet. Sen sijaan korvaushoito-alkuiset muodot voisi lisätä ainakin opiaattikorvaushoidolle, nikotiinikorvaushoidolle ja hormonihoidolle.
