### ISSUE TITLE
kriittiset editiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11220]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kriittiset editiot](http://www.yso.fi/onto/yso/p27876)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritelmän tarkistus: (Kirjastopalvelu): käytin slm-termiä kriittinen editio, koskapa itse sarjan toimittajat olivat sitä käyttäneet, mm. professori Sirkka Saarinen esipuheessaan. Teoksessa ei kuitenkaan ole alkuteosta vaan sisältää englanninkielisen käännöksen. Ei täsmää slm-määritelmän kanssa.

**Perustelut ehdotukselle**

978-952-7262-31-3

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Määritelmä: 
Tieteellisesti toimitettu julkaisu, joka pohjautuu teoksen alkuperäislähteisiin ja koostuu tekstikriittisin perustein valikoidusta ja toimitetusta alkuperäistekstistä tai nuottiaineistosta sekä sitä täydentävistä kommentaareista.

**Comment by AuHo22** [comment]
Alunperin ehdotettu määritelmä: #9187
Kriittiset editiot ovat teosten alkuperäislähteisiin pohjautuvia julkaisuja, jotka koostuvat tekstikriittisin perustein valikoidusta ja toimitetusta tekstistä tai nuottiaineistosta sekä sitä täydentävästä kommentaariosiosta.

**Comment by AuHo22** [comment]
Vastaavanlainen julkaisu edelleen: Syrjaenica 978-952-7262-39-9

**Comment by mirmaid** [comment]
Auli muotoilee uuden ehdotuksen määritelmäksi, Ilkka kommentoi sitä.

**Comment by AuHo22** [comment]
Esitän tähän nyt kaksikin määritelmäehdotusta taustatietoineen: 

1. #9187 eli alkuperäinen ehdotus, joka seuraa sanatarkasti SKS:n sivuilla olevaa määritelmää:
**Kriittiset editiot ovat teosten alkuperäislähteisiin pohjautuvia julkaisuja, jotka koostuvat tekstikriittisin perustein valikoidusta ja toimitetusta tekstistä tai nuottiaineistosta sekä sitä täydentävästä kommentaariosiosta.**
https://www.finlit.fi/fi/tutkimus/edith-suomalaisen-kirjallisuuden-kriittiset-editiot#.ZG3bSXZBxPZ
tai
2. **Kriittinen laitos on tieteellinen editio,  joka pohjautuu huolelliseen lähdeaineiston tutkimukseen ja sisältää kommentoitavan tekstin tekstikriittisen menetelmin tarkasteltuna. Sävellysten kriittisten laitosten ensisijaisia lähteitä ovat säveltäjän käsikirjoitukset, säveltäjän hyväksymät käsikirjoituskopiot sekä säveltäjän hyväksymät painetut laitokset.**
(Käytetty myös wikiwand/wikipedia lähteineen)
https://www.wikiwand.com/fi/Kriittinen_laitos#introduction

Nykyisen määritelmän ongelmat:
_tieteellisesti toimitettu julkaisu_ - onko yksiselitteisesti ymmärrettävissä, mielestäni ei, esim. sisältö- ja/tai muotoaspektit
_alkuperäisteksti -_ tarkoittanee "original text", ks. esim. Raamatusta 
https://en.wikipedia.org/wiki/Biblical_manuscript

Voidaan tietenkin sitten äänestääkin erilaisten muotoilujen pohjalta. Oletan että määritelmään haluttiin nimenomaan sisällyttää tieteellisyys eli rajata se tiedeyhteisön julkaisuihin, wikipedia erikseen mainitsee tieteelliset kriittiset editiot, tieteen termipankki taas viittaa lähtökohtaisesti tieteelliseen editioon.

**Comment by mirmaid** [comment]
Lisätään määritelmä: Kriittiset editiot ovat teosten alkuperäislähteisiin pohjautuvia julkaisuja, jotka koostuvat tekstikriittisin perustein valikoidusta ja toimitetusta tekstistä tai nuottiaineistosta sekä sitä täydentävästä kommentaariosiosta.

**Comment by mirmaid** [comment]
^ Sama YSOon.
