### ISSUE TITLE
talouskuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11233]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

talouskuri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

austerity

**Tarkoitusta täsmentävä selite**

Talouskuri, talouskuripolitiikka, austerity tai kurjistava talouspolitiikka (engl. fiscal austerity) tarkoittaa politiikkaa, jossa erilaisilla talouspoliittisilla toimenpiteillä pyritään pienentämään valtiontalouden budjetin alijäämää.  Wikipedia

**Perustelut ehdotukselle**

Perus talouskäsite, joka puuttuu kokonaan sanastosta. Aiheesta puhutaan ja kirjoitetaan paljon, mutta asiakkaan vaikea löytää ilman asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 talouskuripolitiikka, austerity

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [talouspolitiikka](http://www.yso.fi/onto/yso/p978)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Talouskuri)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The capital order : how economists invented austerity and paved the way to fascism / Clara E. Mattei. 

Ja esim: Mark Blyth: Talouskuri.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [talouskuri](http://finto.fi/yse/fi/page/Y511233)

**Comment by mirmaid** [comment]
3 x Melindassa. Jos otetaan, niin mielestäni jossain politiikka-loppuisessa muodossa, muuten termi tuntuu vähän epämääräiseltä, mutta toisaalta yhdistelmällä _talouspolitiikka & menoleikkaukset (valtiontalous, alijäämä, veronkorotukset...)_ selviää varmaan aika pitkälle?

**Comment by mariaforsen** [comment]
Sv. ekonomisk åtstramningspolitik HT åtstramningspolitik 
https://termipankki.fi/tepa/fi/haku/austerity
https://svenska.se/tre/?sok=%C3%A5tstramningspolitik&pz=8

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _talouskuripolitiikka_.
