### ISSUE TITLE
Eritrean–Etiopian sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11231]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Eritrean–Etiopian sota

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Eritrean%E2%80%93Etiopian_sota)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9789198775945

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Eritrean–Etiopian sota](http://finto.fi/yse/fi/page/Y511231)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Eritrean-Ethiopian War, 1998-2000**](http://id.loc.gov/authorities/subjects/sh00004255).

**Comment by mariaforsen** [comment]
Sv. eritreansk-etiopiska kriget (1998-2000) HT eritreansk-etiopiska kriget, etiopisk-eritreanska kriget (1998-2000), konflikten Etiopien Eritrea 1998-2000
https://id.kb.se/find?q=Eritrean-Ethiopian%20War

**Comment by fantsby-m** [comment]
Tarvitsisi ehkä vuositarkenteen (1998-2000), ettei sekoitu Eritrean itsenäisyyssotaan (1961-1991)? 
https://fi.wikipedia.org/wiki/Eritrean_itsen%C3%A4isyyssota

**Comment by mariaforsen** [comment]
Pitäisikö ottaa molemmat? Löytyy ainakin muutama aineisto Melindassa.
