### ISSUE TITLE
intermezzot (kamarioopperat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11257]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[intermezzot (kamarioopperat)](http://www.yso.fi/onto/yso/p10244)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan assosiatiivinen suhde "soitinmusiikki"-asiasanaan

**Perustelut ehdotukselle**

Lauletulla intermezzolla ja soitinmusiikilla ei ole suhdetta, jota tarvitsisi tällä tavoin tuoda esille. Asiasanalla on myös jo erillinen viite soitinmusiikki-intermezzoihin.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
