### ISSUE TITLE
maksimaalifunktiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11258]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maksimaalifunktiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

maximal functions

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85082367), [Wikipedia](https://en.wikipedia.org/wiki/Maximal_function)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Endpoint regularity of maximal functions in higher dimensions http://urn.fi/URN:ISBN:978-952-64-0949-8

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [maksimaalifunktiot](http://finto.fi/yse/fi/page/Y511258)

**Comment by mariaforsen** [comment]
Sv. maximalfunktioner HT maximala funktioner (matematik)
https://www.kau.se/utbildning/program-och-kurser/kurser/MAAD21
