### ISSUE TITLE
kuuntelukasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11259]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuuntelukasvatus](http://www.yso.fi/onto/yso/p25043)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "musiikin kuuntelukasvatus" tai otetaan tämä päätermiksi ja lisätään nykyinen KT-muodoksi.

**Perustelut ehdotukselle**

Sanana kuuntelukasvatus ei viittaa suoraan musiikkiin, joten sen tarkoituksen voi ymmärtää väärin. Ks. myös esim. https://www.oph.fi/fi/koulutus-ja-tutkinnot/artikkeli-musiikin-kuuntelukasvatus

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by fantsby-m** [comment]
Kannatan ohjaustermiä, koska kuuntelukasvatus voi nähtävästi liittyä muuhunkin kuin musiikkiin. 
Ks. esim. 
https://www.tamk.fi/web/tamk/-/kuuntelukasvatus-100-kuuntelu-ja-aaniharjoitusta.html
https://www.theseus.fi/handle/10024/509063

**Comment by jtuohini** [comment]
Vaan tällä hetkellä kuuntelukasvatus on hierarkkisesti nimenomaan osa musiikkikasvatusta. Jos asiasanalla tarkoitetaan muutakin, pitää myös hierarkia muuttaa, ja silloin viittaussuhde muuttuu hassuhkoksi.

**Comment by YSO-kokous** [comment]
**Päätös**

Muusalta kommentti.

**Comment by MUUSA-kokous** [comment]
Kannatetaan termin muutosta muotoon "musiikin kuuntelukasvatus".

**Comment by mariaforsen** [comment]
Sv. fostran i musiklyssning HT fostran i att lyssna på musik, lyssnarfostran, fostran i musiklyssnande

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan muotoon _musiikin kuuntelukasvatus_.
