### ISSUE TITLE
lectio praecursoriat [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11255]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lectio praecursoriat [SLM]

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Kandidaattien tuli pitää myös luentoja, useimmiten yksi. Tästä luennosta on jäljelle jäänyt nykyisten väitöstilaisuuksien alkajaisesitelmä, lectio praecursoria. (https://www.helsinki.fi/fi/tutkimus/tohtorikoulutus/tervetuloa-vaitostilaisuuteen#lectio-praecursoria--title)

**Perustelut ehdotukselle**

Tarvetta lektioiden kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [esitelmät](http://www.yso.fi/onto/yso/p12644)

**Ehdotetut temaattiset ryhmät**

 [56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544)

**Vaihtoehtoiset termit**

 lektiot, väittelijän alkupuheenvuorot, väitöstilaisuuksia alkajaisesitelmät

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018693197, https://melinda.kansalliskirjasto.fi/byid/018214781, https://melinda.kansalliskirjasto.fi/byid/018693629 ja parituhatta muuta

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**lektio**
väittelijän väitöstilaisuuden alussa pitämä puhe. 
https://www.kielitoimistonsanakirja.fi/#/lektio?searchMode=all

**Comment by mirmaid** [comment]
lektiot, KT muut muodot

**Comment by mariaforsen** [comment]
Sv. lectio (disputationer) HT lectio praecursoria
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1a668618742f24ccce2236f0fb11584e&list_id=1&keyword=lektio&word=lektio
https://www.abo.fi/forska-hos-oss/forskarutbildning/for-forhandsgranskare-och-opponenter/proceduren-for-disputationen/
https://www.helsinki.fi/sv/forskning/doktorsutbildning/valkommen-pa-disputation
https://sv.wikipedia.org/wiki/Disputation
https://www-ne-se.ezproxy.vasa.abo.fi/uppslagsverk/encyklopedi/l%C3%A5ng/lectio
