### ISSUE TITLE
Vallisärkkä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11265]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Vallisärkkä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [rakennukset](http://www.yso.fi/onto/yso/p1786)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Vallis%C3%A4rkk%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tuhansien tarinoiden ja miljoonien muistojen Vallisärkkä

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Vallisärkkä](http://finto.fi/yse/fi/page/Y511265)

**Comment by mariaforsen** [comment]
Sv. Vallisärkkä
