### ISSUE TITLE
sivuvirrat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11266]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sivuvirrat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.uef.fi/en/article/doctoral-defence-of-sandra-sandar-msc-18-feb-2022-potential-of-neglected-biomass-and-industrial-side

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [sivuvirrat](http://finto.fi/yse/fi/page/Y511266)

**Comment by ilona-x** [comment]
https://www.sitra.fi/tulevaisuussanasto/sivuvirta/

Melinda x 10

**Comment by mirmaid** [comment]
_Materiaalivirrat_ on englanniksi _material flows_, mutta tämä näyttäisi kääntyvän _(material) side streams_. Melko vähän kyllä englanniksi.

**Comment by mariaforsen** [comment]
Sv. sidoflöden HT sidoströmmar 
https://www.sanakirja.fi/custom/fi-en-sv/sidostr%C3%B6m
https://termipankki.fi/tepa/fi/haku/sivuvirta
https://www.sanakirja.fi/custom/fi-en-sv/sivuvirta
https://tem.fi/documents/1410877/3323088/Kestavaa_kasvua_materiaalitehokkuudella.pdf/36f86514-3f46-4ffa-87a5-45e23d08828b/Kestavaa_kasvua_materiaalitehokkuudella.pdf?t=1476785072000
https://www.metsakeskus.fi/sv/om-oss/verksamhetens-prioriteter/skogsenergi
https://www.businessfinland.fi/sv/for-finlandska-kunder/tjanster/finansiering/materialsyn
https://soilfood.se/industri/livsmedelsindustrin/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
