### ISSUE TITLE
ruokaneofobia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11270]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ruokaneofobia

**Ehdotettu termi ruotsiksi**

matneofobi

**Ehdotettu termi englanniksi**

food neophobia

**Tarkoitusta täsmentävä selite**

Tai sitten yleisemmässä muodossa neofobia.
Ks. https://en.wikipedia.org/wiki/Neophobia

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/27223

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [ruokaneofobia](http://finto.fi/yse/fi/page/Y511270)

**Comment by ilona-x** [comment]
FinMeSH:
**rajoittunut syöminen**

eng 
Avoidant Restrictive Food Intake Disorder
ohjausterminä Food Neophobia
http://www.yso.fi/onto/mesh/D000080146

**Comment by mirmaid** [comment]
Melindassa 2 x neofobia, ruokaan liittyen.

Lääketieteen termit: **uutuudenkammo**: neofobia | voimakas uusiin ja tuntemattomiin asioihin kohdistuva pelko

Varmaankin tätä tutkitaan ennen kaikkea ruokaan liittyen (erit. lasten ruokatottumukset, kuten esimerkkiaineistossakin).

**Comment by mirmaid** [comment]
Wikipedian mukaan taas _Food neophobia in humans has been described as the fear of eating new or unfamiliar foods. It differs from [avoidant/restrictive food intake disorder](https://en.wikipedia.org/wiki/Avoidant/restrictive_food_intake_disorder)._

**Comment by mariaforsen** [comment]
Sv. matneofobi 
jfr https://mesh.kib.ki.se/term/D000080146/avoidant-restrictive-food-intake-disorder

**Comment by mirmaid** [comment]
Mielestäni ei kannata ainakaan MeSHin tavoin yhdistää, koska _rajoittunut syöminen_ on käsitelty lähteissä syömishäiriönä (ja kieliversiotkin viittaavat siihen), mutta ruokaneofobia on aika tavallinen ja usein ohimenevä piirre lapsilla.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
