### ISSUE TITLE
trombektomia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11291]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

trombektomia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/142422

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [trombektomia](http://finto.fi/yse/fi/page/Y511291)

**Comment by mirmaid** [comment]
Lääketieteen termit: verisuonitukoksen poisto

MeSH: http://www.yso.fi/onto/mesh/D017131

Melinda x 10

**Comment by mariaforsen** [comment]
Sv. trombektomi
https://mesh.kib.ki.se/term/D017131/thrombectomy
