### ISSUE TITLE
yarsanism

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11294]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jarsanismi?

**Ehdotettu termi ruotsiksi**

yarsanism

**Ehdotettu termi englanniksi**

yarsanism

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Behövs vid indexering (Melinda). 

**Ehdotettu yläkäsite YSOssa (LT)**

 [religion och religioner](http://www.yso.fi/onto/yso/p2921)

**Ehdotetut temaattiset ryhmät**

 [53 Religion. Teologi. Religionsvetenskap](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 yari

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kurder](http://www.yso.fi/onto/yso/p17382)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://sv.wikipedia.org/wiki/Yarsanism), [Wikipedia](https://en.wikipedia.org/wiki/Yarsanism)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kakai Calamity in the Iraqi Disputed Territories : Alert of Genocide / Kristiina Koivunen, Hussain Talabani

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [yarsanism](http://finto.fi/yse/fi/page/Y511294)

**Comment by jarmosaarikko** [comment]
kts. https://fi.wikipedia.org/wiki/Kakait   **jarsanismin** eli Ahl-i Haqq -uskonnon harjoittajat Irakissa. Iranissa "jaresanit".

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _jarsanismi_. Lisätään soveltuvat ohjaustermi.
