### ISSUE TITLE
taseet (kirjanpito)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11293]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taseet (kirjanpito)](http://www.yso.fi/onto/yso/p2695)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Hierarkian muutos, maksutase jne. tämän alle

**Perustelut ehdotukselle**

vrt. kansantalouden tilinpito YK kirjanpito

**Ehdottajan organisaatio**

**Comment by nikopartanen** [comment]
Kuulostaisi äkkiseltään ihan perustellulta.
