### ISSUE TITLE
immuunijärjestelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11296]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[immuunijärjestelmä](http://www.yso.fi/onto/yso/p16041)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi immuunipuolustus

**Perustelut ehdotukselle**

https://finto.fi/mesh/fi/page/D007107

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
löytyi vanha termiehdotus: immuunipuolustus #2299 

TSR-ontologiassa: immuunipuolustus http://www.yso.fi/onto/tsr/p8563

https://www.solunetti.fi/fi/histologia/immuunipuolustus/

**Comment by mirmaid** [comment]
Sanastossa on lisäksi _immuunivaste_.

TSR:ssä näköjään on myös immuunivaste erikseen, mutta ei immuunijärjestelmää.

**Comment by mirmaid** [comment]
Lääketieteen termit:

**immuunipuolustus**: pieneliöiden, kasvainsolujen ja muiden haittatekijöiden torjuntaan johtava immuunijärjestelmän toiminta; ks. myös immuniteetti, immuunivaste

**immuunijärjestelmä**: spesifisten immunoreaktioiden tuottamiseen liittyvät elimet ja kudokset, joiden toimivana soluna on aina imusolu

**immuunivaste**: immunovaste | elimistön tapa reagoida kohtaamaansa antigeeniin (vasta-ainevälitteinen tai soluvälitteinen immuniteetti); ks. myös immuunireaktio

**Comment by fantsby-m** [comment]
Eli _Lääketieteen termien_ mukaan immuunipuolustus on - nähtävästi - toimintaa jota immuunijärjestelmä tekee

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _immuunipuolustus_ ohjaustermiksi molemmille.
