### ISSUE TITLE
aselepo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11297]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aselepo](http://www.yso.fi/onto/yso/p16073)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi tulitauko

**Perustelut ehdotukselle**

läheinen merkitys

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. eldupphör

**Comment by mirmaid** [comment]
Muilla kielillä näköjään tehty näin.
https://tieteentermipankki.fi/wiki/Historia:aselepo
Sotilaskielessä tulitauolla on vielä vähän eri merkitys: https://www.kielikello.fi/-/aselepo-ja-tulitauko

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi _tulitauko_.
