### ISSUE TITLE
poromiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11298]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[poromiehet](http://www.yso.fi/onto/yso/p16312)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermiksi poronhoitajat

**Perustelut ehdotukselle**

Oikeampi ja modernimpi termi, joka toimii sukupuolesta riippumatta. Myös poronomistajat?

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. renskötare, olisi tosiaan parempi. Myös SAOssa näin https://id.kb.se/term/sao/Rensk%C3%B6tare

**Comment by mariguttorm** [comment]
Pohjoissaameksi tämä on jo käännetty "badjeolbmot", ei ole riippuvainen sukupuolesta.

**Comment by mirmaid** [comment]
Ollapa vielä ketjutus käytössä, niin Melindassa olisi paljon _poromiehet - naiset_ -ketjuja. Onko nämä muutettavissa yksi yhteen, poronhoitaja = poroelinkeinon harjoittaja (mitä varmaankin poromiehellä on tarkoitettu)?

**Comment by mariaforsen** [comment]
https://www.kielitoimistonsanakirja.fi/#/poromies?searchMode=all 
_Jos_ yllä ehdotettu ei toimi niin pitäisikö siis ottaa myös poronomistajat erikseen, poronhoitajien lisäksi?
SAOssa vain yksi.

**Comment by FinMeSHienPaimentaja** [comment]
Mielestäni "poronomistajat" olisi parempi kuin "poronhoitajat", jos kohta ei sekään ole oikein hyvin luontuva. Perusteluna, että "poromies/miehet" merkitsee lähinnä porojen omistajaa, hoitaja voi olla esim. porojen omistajan palkkaama työntekijä, toki voi porojen omistajakin hoitaa (esim. talvitarhoilla ruokinta, kesäaikanahan / sulan maan aikana porot laiduntavat vapaasti pitkin maita ja mantuja eikä niitä kukaan varsinaisesti hoida (siinä mielessä, miten eläinten hoitaminen (vaikkapa lehmien tai koiran hoito) yleisesti ymmärretään). 

Olennaista mielestäni puheena olevassa asiassa on omistajuus (eläintenkouluttajaopinnoissani ns. kakkoseläimenäni oli poro, ja poronhoitoon ja poroelinkeinoon tutustumiseni perusteella ->  em. näkemykseni). 

Olisikohan Paliskuntain yhdistyksellä tähän asiaan jotain kantaa?

**Comment by mirmaid** [comment]
Täällä https://www.mela.fi/poronhoitajat/ kuitenkin puhutaan poronhoitajista maatalousyrittäjinä, joten ehkä voisi olla poronhoitajat KT poronomistajat?

**Comment by mariaforsen** [comment]
Sv. renkarlar > renskötare
https://id.kb.se/term/sao/Rensk%C3%B6tare
