### ISSUE TITLE
sinkitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11300]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sinkitys](http://www.yso.fi/onto/yso/p16483)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi ohjaustermi: galvanointi

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/galvanointi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ehkä uutena terminä? Ainakin SAOssa molemmat: 
https://id.kb.se/term/sao/F%C3%B6rzinkning
https://id.kb.se/term/sao/Galvanisering

**Comment by mirmaid** [comment]
Sanastossa on myös **galvanotekniikka**; Kielitoimiston sanakirja: esineiden päällystäminen metallilla sähkövirtaa käyttäen.
Sinkityksen menetelmiä ovat sähkösinkitys (galvanointi) ja kuumasinkitys, mutta galvanointi-termiä käytetään myös (kai vähän virheellisesti) sinkityksen synonyymina, ja englanniksi puhutaan erikseen elektrogalvanoinnista.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _galvanointi_ ohjaustermiksi _galvanotekniikalle_.
