### ISSUE TITLE
huulet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11307]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

huulet

**Ehdotettu termi ruotsiksi**

läpps

**Ehdotettu termi englanniksi**

lips

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Puuttuu YSOsta. FinMeSHissä on yksikkömuoto.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ruumiinosat](http://www.yso.fi/onto/yso/p109)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH / FinMeSH](http://www.yso.fi/onto/mesh/D008046)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018738245

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [huulet](http://finto.fi/yse/fi/page/Y511307)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q15173

**Comment by mariaforsen** [comment]
Sv. läppar
https://mesh.kib.ki.se/term/D008046/lip
