### ISSUE TITLE
poski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11306]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

poski

**Ehdotettu termi ruotsiksi**

kind

**Ehdotettu termi englanniksi**

cheek

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Puuttuu YSOsta.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ruumiinosat](http://www.yso.fi/onto/yso/p109)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH / FinMeSH](http://www.yso.fi/onto/mesh/D002610)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018738245

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [poski](http://finto.fi/yse/fi/page/Y511306)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q47038  
YK kasvot  ?

**Comment by mirmaid** [comment]
YSOn hierarkiassa partOf kasvot, YK ruumiinosat. YSOssa on auktorisoitu monikossa ruumiinosat, joita on yhdellä ihmisellä enemmän kuin yksi (MeSHissä eri periaate).

**Comment by mariaforsen** [comment]
Sv. kinder 
https://mesh.kib.ki.se/term/D002610/cheek
