### ISSUE TITLE
verkostovaikutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11308]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

verkostovaikutus

**Ehdotettu termi ruotsiksi**

nätverkseffekt

**Ehdotettu termi englanniksi**

network effect

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [taloudelliset tapahtumat](http://www.yso.fi/onto/yso/p27716)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Verkostovaikutus), [Tepa](https://termipankki.fi/tepa/fi/haku/verkostovaikutus)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Digitaalisten alustayritysten kehityksestä ja vaikutuksista /Martti Hetemäki

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [verkostovaikutus](http://finto.fi/yse/fi/page/Y511308)

**Comment by mirmaid** [comment]
Kerran Melindassa yksikössä, 4 x monikossa. Yksikkö kuulostaisi kuitenkin luontevammalta, koska kyseessä on tietynlainen vaikutustyyppi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
