### ISSUE TITLE
otsa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11305]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

otsa

**Ehdotettu termi ruotsiksi**

panna

**Ehdotettu termi englanniksi**

forehead

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tämä puuttuu YSOsta. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [ruumiinosat](http://www.yso.fi/onto/yso/p109)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH / FinMeSH](http://www.yso.fi/onto/mesh/D005546)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018738245

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [otsa](http://finto.fi/yse/fi/page/Y511305)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q41055
YK kasvot ?

**Comment by mariaforsen** [comment]
Sv. panna (kroppsdelar)
https://mesh.kib.ki.se/term/D005546/forehead
https://svenska.se/tre/?sok=panna&pz=1
