### ISSUE TITLE
palomiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11314]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[palomiehet](http://www.yso.fi/onto/yso/p8405)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

muutetaan käytettävä termi muotoon  "pelastajat".  
Ohjaustermeinä "palopelastajat" , "palontorjujat" ja "palomiehet" sekä "palosotilaat".  
Englanninkielinen termi "fire fighters" on neutraali.
Ruotsinkielisen "brandmän" voisi vaihtaa vastaavasti  muotoon "räddare" ja ohjaustermi "brandräddare" sekä nykyinen "brandmän".

**Perustelut ehdotukselle**

Siirrytään sukupuolineutraaliin muotoon. 
Vastaava koulutusnimike on "pelastaja".  Vrt. http://www.yso.fi/onto/yso/p24442 pelastajatutkinto
Tilastokeskuksen ammattinimikeluettelossa 2010 termi on edelleen palomiehet.
kts. YLE uutinen sisäasiainministeriön kehitystyöstä: https://yle.fi/a/74-20004242
vaihtoehtoisesti voidaan tietysti odottaa tuota SM:n ehdotusta.
- Katso myös muita mahdollisia muutoksia:  https://duunitori.fi/sukupuolineutraalit-ammattinimikkeet
- Taustatietoa (THL)  https://blogi.thl.fi/sukupuolella-valia-kielessa-thl-luopuu-sukupuolitetuista-ammattinimikkeista/

YSO:n käsitteiden termejä voisi näiden pohjalta käydä läpi laajemminkin ja tehdä muutosehdotuksia.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mariaforsen** [comment]
"Räddare" ei ole mahdollinen ruotsinkielisenä vaihtoehtona, mutta muita muotoja löytyy kyllä https://sprakkonsulterna.se/brandman-brandperson-eller-brandsoldat/

**Comment by mirmaid** [comment]
_Pelastajat_ on terminä kyllä harmillisen altis väärintulkinnalle. Ehkä sitten jollain tarkenteella (pelastusala?). Mutta pitäisikö odottaa ehdotusta?

**Comment by tpalonen** [comment]
Olisiko päätermi kuitenkin _palopelastajat_ väärinymmärrysten välttämiseksi? Jos päätermi on _pelastajat (pelastusala)_ tms niin ei ole kovin käyttäjäystävällinen ja selventävä. Käyttäjät eivät välttämättä tunnista, että tämä on se käsite, mitä he etsivät. Painottaisin tässä mieluummin käytettävyyttä kuin virallisuutta, yleissanastosta kun on kuitenkin kyse.

**Comment by mirmaid** [comment]
^ Varmaan parempi, tosin vielä tällä hetkellä ainakin siitäkin tulee mielikuva, että kyseessä olisi jokin erityistehtävä, eikä palonsammuttaminen. Mutta jos ohjausterminä on palomiehet, niin eiköhän se mene oikein. Pelastustehtävä ei tietysti aina liity tulipaloon, siksi varmaan halutaan mieluummin pelastajat viralliseksi termiksi.

**Comment by mariaforsen** [comment]
Huom. **Palopelastaja**-nimityksestä löytyy kyllä hyvin vahvoja mielipiteitä (sitä vastaan): "Medialle palo-sanasta näyttääkin tulleen jonkinlainen pakkomielle, josta ei haluta poisoppia. Pelastusalan ihmisten on vaikea ymmärtää, miksi se ”palo”-etuliite on pakko säilyttää, vaikka se kuvaa huonosti alan ammattilaista, ja vaikka sitä ei alan virallisissakaan yhteyksissä ole käytetty enää kymmeniin vuosiin. Mediassa palomies-nimike on jo jonkin aikaa korvattu erikoisella palopelastaja-nimikellä. Se kuulostaa tökeröltä, teennäiseltä ja suoraan sanottuna hölmöltä." 
Lue lisää: https://pelastustieto.fi/pelastustieto-blogi/palopelastaja-on-huono-nimike/#36ee8965

https://pelastustieto.fi/pelastustoimi/palomies-voitti-pelastustiedon-aanestyksen-ammattinimikkeista-kansalaisen-taytyy-tunnistaa-pelastusviranomainen/#36ee8965

https://www.spal.fi/kirjallinen-lausunto-pelastustoimen-virkanimikkeiden-yhdenmukaistamiseksi-seka-muuttamiseksi-sukupuoli-neutraaleiksi-diaari-vn-6593-2022/

**Comment by mariaforsen** [comment]
https://www.spal.fi/kirjallinen-lausunto-pelastustoimen-virkanimikkeiden-yhdenmukaistamiseksi-seka-muuttamiseksi-sukupuoli-neutraaleiksi-diaari-vn-6593-2022/
