### ISSUE TITLE
rikosuhrit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11313]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rikosuhrit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85143177)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Luomme yhdessä kasvutarinoita. Vuolle 75

**Ehdottajan organisaatio**

KK
**Termiehdotus Fintossa:** [rikosuhrit](http://finto.fi/yse/fi/page/Y511313)

**Comment by jtuohini** [comment]
KT-muodoksi ainakin _rikoksen uhrit_ ja _rikosten uhrit_. Entä _rikoksen kohteeksi joutuneet henkilöt_, joka tosin kävisi myös asiasanan selitykseksi?

**Comment by mariaforsen** [comment]
Tuo nykyinen YSOssa oleva uhrit KT rikoksen uhrit on mielestäni hämmentävä ilman tarkennetta.

**Comment by mirmaid** [comment]
^ Mikä siinä on hämmentävää?

**Comment by jtuohini** [comment]
Kenties se, että uhri voi olla myös katastrofin, onnettomuuden, sairaudun tms. uhri, ja viittaussuhde voi saada ajattelemaan, että vain **uhrit**-asiasanalla ei tarkoiteta muita kuin rikoksen uhreja.

**Comment by jarmosaarikko** [comment]
**rikoksen uhrit** on tällä hetkellä YSO-käsitteen **uhrit** ohjausterminä.
- MeSH käyttää termiä "[rikosuhrit](http://www.yso.fi/onto/mesh/D019548)"  (Brottsoffer, Crime Victims) YK henkilöt
- TEROssa käsite "[rikoksen uhrit](http://www.yso.fi/onto/tero/TNR802)"    YK "uhrit".
- JUHOssa on "[rikoksen uhrit](http://www.yso.fi/onto/juho/p2480)"  YK  oikeudelliseen asemaan liittyvä rooli   (brottsoffer,victims of crime)
- KOKO "[rikosuhrit](http://www.yso.fi/onto/koko/p67400)" (tulee JUPOsta)  (brottsoffer | victims of crime KT crime victims)

Ehdotan  uuttaa käsitettä seuraavasti:
fi: **rikosuhrit**  
sv: **brottsoffer**
en:  **crime victims**    (en. termi kts. Kanto "[Finnish Service for Crime Victims](http://urn.fi/URN:NBN:fi:au:finaf:000033300)" 
KT **rikosten uhrit**, **rikoksen uhrit**, **victims of crime**, **victims of crimes**
YK **uhrit**
poistetaan "uhrit" käsitteestä ohjaustermi.
Wikidata - http://www.wikidata.org/entity/Q10436169  (ehkä fi-termin voisi siellä vaihtaa YSOn mukaiseksi?)
LCSH https://id.loc.gov/authorities/sh85143177

**Comment by mirmaid** [comment]
_Uhrit_ on käytetty Melindassa asiasanana 5164 kertaa. _Uhrit & rikokset_ on samoissa tietueissa vähän vajaat 1000 kertaa, _uhrit & murha_ 661 kertaa, _uhrit & seksuaalirikokset_ 548 kertaa, _uhrit & väkivaltarikokset_ 400 kertaa. 

Toki viitteissä on muutakin, esim. narsistien, häirinnän, sodan ja katastrofien uhrit aiheena. Lisäksi tapauksia, joissa kyse on rikoksesta, mutta mittakaava tuntuu "liian suurelta" (terroriteot, joukkosurmat). Valtaosa viitteistä kuitenkin juuri rikosuhreista.

**Comment by mariaforsen** [comment]
Sv. offer on kyllä vahvasti kaksimerkityksinen termi ja SAOssa samanmuotoinen termi viittaakin uskonnollisiin uhreihin: https://id.kb.se/term/sao/Offer Erikseen on sitten rikosuhrit https://id.kb.se/term/sao/Brottsoffer Ks. myös https://svenska.se/tre/?sok=offer&pz=1 Ruotsiksi pitäisi siis kyllä oikeastaan lisätä tarkenteen > offer (drabbade/för något..?)

**Comment by mirmaid** [comment]
^ Tässä ei vaan vaihtoehdot ole rikokset vs. uskonto, vaan yleensä joutuminen jonkun henkilön ei-rikollisen, mutta muuten haitallisen toiminnan vaikutuspiiriin, tai vaikeiden olosuhteiden uhriksi.

_Uhrit (uskonto)_ lisättiin ohjaustermiksi _uhraaminen_-käsitteelle juuri siksi, että uskonnon yhteydessä käytettäisiin sitä käsitettä.

**Comment by mariaforsen** [comment]
Ymmärrän joo, mutta ruotsiksi offer yhdistetään niin vahvasti nimenomaan uskonnolliseen uhraamiseen (kuten sanakirjakin sen määrittelee), että ruotsiksi pitää varmaan jonkinlaisen tarkenteen keksiä, ja tämä pitää toki olla laajempi kuin pelkästään varsinaiset rikokset (jos suomeksi ei haluta rikosuhrit erikseen). Onko tässä muitakin kielikohtaisia eroja, koska offer-termiä ei kyllä voi käyttää ihan mistä tahansa, kuten pelkästään vaikeissa olosuhteissa olevista ihmisistä?

**Comment by mirmaid** [comment]
Silloin kun heidät nimen omaan nähdään uhreina, ei varmasti mitenkään yleisesti. Mutta siis yritin tuossa eritellä Melindan tämänhetkistä käyttöä uhrit-käsitteelle, jossa ei välttämättä ole ihmistoimijaa, jonka uhriksi olisi jouduttu, vaan esim. sota tai katastrofi.

**Comment by YSO-kokous** [comment]
**Päätös**

Käsitteen _rikosuhrit_ hyväksyminen sai enemmistön puoltoa äänestyksessä, mutta siirretään lopullinen käsittely seuraavaan kokoukseen.

**Comment by mirmaid** [comment]
Huom. Jos _rikosuhrit_ otetaan erikseen, mutta sanastoon jää edelleen myös _uhrit_, ruotsin ongelma uskonto-merkityksestä ei oikeastaan ratkea. Jos taas toive on, että uhrit muuttuisi muotoon rikosuhrit, mitä kaikille katastrofien uhreja käsitteleville aineistoille tehtäisiin?

**Comment by mariaforsen** [comment]
Ruotsiksi voidaan miten vain muuttaa offer > offer (drabbade) tai offer (för något), eli sen takia ei ole pakko ottaa uusia termejä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _rikosuhrit_.

**Comment by mariaforsen** [comment]
Sv. 
-offer > offer (drabbade), offer (för något)
-brottsoffer
