### ISSUE TITLE
SLM manhuat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11317]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM manhuat

**Ehdotettu termi ruotsiksi**

manhuat

**Ehdotettu termi englanniksi**

manhuat

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käytetään kiinalaisista manhuasarjakuvista. Vastine Japanissa on manga ja Koreassa manhwa. Näitä on alettu kääntää englanniksi, ensin romaaneina ja nyt niihin pohjautuvia sarjakuvia on ilmestynyt. Kun kerran manga ja manhwakin löytyvät, niin tämä täytyy myös, sillä Kiina on nouseva sarjakuvamaa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sarjakuvat](http://www.yso.fi/onto/yso/p1148)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [mangat](http://www.yso.fi/onto/yso/p13956), [manhwat](http://www.yso.fi/onto/yso/p22675)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mm. 9781638585237

**Ehdottajan organisaatio**

Suomen kirjastopalvelu Oy

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Manhua

**Comment by ghost** [comment]
Kauno-ryhmä kannattaa. Kysytty kommentit myös Helsingin kaupunginkirjaston sarjakuva-asiantuntijalta.

**Comment by mirmaid** [comment]
Hyväksytty /SLM.

**Comment by mariaforsen** [comment]
Sv. manhua
https://sv.wikipedia.org/wiki/Manhua
