### ISSUE TITLE
verkkoteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11311]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[verkkoteoria](http://www.yso.fi/onto/yso/p2543)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään englanniksi KT graph theory tai mahdollisesti jopa eng-päätermiksi? 
Ja linkitys LCSH-termiin Graph theory http://id.loc.gov/authorities/subjects/sh85056471 ?

**Perustelut ehdotukselle**

suomeksi verkkoteoria KT graafiteoria
https://termipankki.fi/tepa/fi/haku/graafiteoria
https://fi.wikipedia.org/wiki/Verkkoteoria

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Ja vielä Wikipediasta:

> In [mathematics](https://en.wikipedia.org/wiki/Mathematics), [computer science](https://en.wikipedia.org/wiki/Computer_science) and [network science](https://en.wikipedia.org/wiki/Network_science), network theory is a part of [graph theory](https://en.wikipedia.org/wiki/Graph_theory).

Lähde: https://en.wikipedia.org/wiki/Network_theory

**Comment by tpalonen** [comment]
Lisäsin graph theory ohjaustermiksi. Laitoin broadermatchin LCSH-käsitteeseen sen perusteella että "network theory is part of graph theory".
