### ISSUE TITLE
anturit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11319]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[anturit](http://www.yso.fi/onto/yso/p11460)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi sensorit?

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/anturi

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. HT sensorer

**Comment by tpalonen** [comment]
Sensori-sanalla on muitakin merkityksiä, mm. sensuurin virkamies. Ks. Kielitoimiston sanakirja. Vaatinee siis sulkutarkenteen? _sensorit (anturit)_? Tai ehkä parempi olisi _sensorit (laitteet)_?

Toinen vaihtoehto voisi olla päätermi _anturit ja sensorit_. Esimerkiksi diabeteksen hoitoon tarkoitettuun insuliinipumppuun kuuluu erillinen sensori, joka mittaa potilaan verensokeria (https://www.diabetes.fi/inspis/diabeteksen_hoitaminen_ruoka/sensori_jelppaa_verensokeriviidakossa#f525559a). Anturi-päätermi tuntuisi kyseisessä yhteydessä aika epäintuitiiviselta eikä laitteesta käytetä sitä nimitystä. Ehkä ihmisen toimintoja mittaavissa laitteissa sensori-sana tuntuu ylipäätään sopivammalta kuin anturi. Vrt. https://www.labopen.fi/lab-pro/sensoriteknologia-tukemassa-paihteetonta-arkea/

Ja mahdollisesti kyse voi olla siitäkin, että anturi on sanana vanhempi ja sensori on pikku hiljaa syrjäyttämässä sen.

**Comment by ilona-x** [comment]
No kävisikö tuo sensorit (anturit) KÄYTÄ anturit?

Tänään viimeksi törmäsin aineistoon, jossa englanniksi käytetään termiä sensors ja suomeksi anturit, eli ainakin tekniikassa anturit vaikuttaa olevan ihan käypä termi. https://urn.fi/URN:ISBN:978-952-03-2275-5

Nyt ongelmana on se, että jos aineistossa puhutaan suomeksi sensoreista, niin yso-termi löytyy vain englanninkielisen vastineen kautta. 

Ja verensokerin mittaamisessakin glukoosianturi näyttää olevan synonyymi glukoosisensorille https://www.terveyskirjasto.fi/ltt04119/glukoosisensori 

> glukoosianturi, glukosensori | diabeteksen hoidossa käytettävä, yleensä ihonalaiskudokseen asetettava anturi, joka mittaa soluvälinesteen glukoosipitoisuutta

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _sensorit (laitteet)_ ohjaustermiksi.

**Comment by mariaforsen** [comment]
Sv. givare och sensorer 

https://www.rikstermbanken.se/search?q=givare&s=termer
https://www.rikstermbanken.se/search?q=sensor&s=termer
https://termipankki.fi/tepa/fi/haku/anturi
https://svenska.se/tre/?sok=sensor&pz=1
https://svenska.se/tre/?sok=givare&pz=1
https://regal.se/sv/nyheter/givare-sensor-transducer-och-transmitter-vad-ar-skillnaden/
