### ISSUE TITLE
retkeilymajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11312]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[retkeilymajat](http://www.yso.fi/onto/yso/p2772)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotamme, että käytettävän termin "Retkeilymajat" tilalle muutetaan sana "Hostellit" ja sana "Retkeilymajat" sijoitetaan sanan "Hostellit" ohjaustermiksi. Eli toisin sanoan ehdotamme, että käsitteen käytettävä termi ja ohjaustermi vaihtavat paikkoja keskenään.

**Perustelut ehdotukselle**

Retkeilymaja on jo Suomessakin vanhahtava termi, nykyään hostelli on terminä tunnetumpi sekä laajemmin käytössä myös Suomessa. Myös Suomen Hostellijärjestö (entinen Suomen Retkeilymajajärjestö SRM ry) vaihtoi nimekseen nykyaikaisemman Suomen Hostellijärjestö ry vuonna 2014.

Suomessa otettiin 90-luvun alkupuolella SRM-kohteiden yleistermiksi kansainvälisen mallin mukaan "hostellit", millä yhdistettiin varsin erilaiset retkeilymajat, retkeilyhotellit ja kesähotellit saman nimikkeen alle. Hostelli-nimike kuvasi myös alalla tapahtunutta muutosta koulumajoituksista ja suurista yhteismajoitustiloista tasokkaisiin ja viihtyisiin tiloihin.

**Ehdottajan organisaatio**

Suomen Hostellijärjestö Ry

**Comment by mirmaid** [comment]
Jos muutetaan näin, vaatii varmaan viitteiden korjaukset, koska retkeilymajat on nyt käytetty myös esim. erämaamajoista, https://melinda.kansalliskirjasto.fi/byid/013802064.

Mitähän nyt olisivat ne mökit/tuvat/majat, jotka eivät ole autiotupia, mutta ei myöskään ihan hostelleja (ainakin retkeilyalueiden varattavat mökit)? Sanastossa on ulkoilumajat, mutta se tuntuu vähän vieraalta.

**Comment by LeKorsu** [comment]
Kannatan muutosta hostelleiksi. 
Miksei tähän kävisi asiasanaksi autiotuvat? https://melinda.kansalliskirjasto.fi/byid/013802064
Autiotuvissakin on varattavia puolia

**Comment by mirmaid** [comment]
^ Laitoin sen esimerkkinä tapauksesta, jossa ei voi muuttaa suoraan > hostellit. 

_Ulkoilumajat_-termiä on käytetty vain 10 kertaa. Ohjaustermiksi ehkä ulkoilukeskukset, https://fi.wikipedia.org/wiki/Ulkoilukeskus? Näissä ei kuitenkaan ilmeisesti yövytä, mutta riittäisikö sitten pelkkä _majoitus_-termi, kun kyse on mökkimajoituksesta muussa kuin autiotuvassa?

**Comment by mariaforsen** [comment]
Ruotsin kannalta ok että olisi hostellit pääterminä: 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_501cb62f25ee06f76e39977e92313f5a&list_id=1&keyword=retkeilymaja&word=retkeilymaja 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9e343e81f37d30e9c5c97f9d11a48e45&list_id=1&keyword=hostelli&word=hostelli

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan päätermi muotoon _hostellit_. Ohjaustermiksi _retkeilymajat_. Tarkistetaan tilanne vielä viitteiden korjaamisen jälkeen.

**Comment by mirmaid** [comment]
Aika paljon esim. Metsähallituksen ym. vuokratuvista. Laitetaanko näille vain _tuvat (rakennukset)_, sv. stugor? Tulisiko tähän jotain ohjauksia? (esim. retkeilytuvat, retkeilymajat (tuvat))

Vähän mietin myös termien _ulkoilumajat, urheilumajat_ rajautumista käytännössä...

**Comment by LeKorsu** [comment]
Kannatan näiden lisäämistä tuvat (rakennukset) -käsitteen ohjaustermeiksi: retkeilytuvat, ulkoilumajat, urheilumajat (vaikka moni urheilumaja onkin nykyään myös juhlatila).
Tuon retkeilymajat (tuvat) KÄYTÄ tuvat (rakennukset) tarpeellisuutta mietin. Kun retkeilymajat ohjaa hostelleihin, osaisiko käyttäjä  hakea toisella termillä?

**Comment by mariaforsen** [comment]
Eli pitäisikö yllä olevan ehdotuksen mukaan poistaa urheilumajat=sportstugor ja ulkoilumajat=raststugor? En kannata. Stuga on "mindre (trä)hus vanligen beläget på landet" eli ei sovellu kovin hyvin sellaiseen käyttöön.

Ja eikö niistä Metsähallituksen vuokratuvista voisi käyttää lähinnä ulkoilumajat? Näin ruotsiksi (raststugor), mutta tässä saattaa olla kieliero..
https://www.kielitoimistonsanakirja.fi/#/ulkoilumaja?searchMode=all  https://www.luontoon.fi/tuvat/tupatyypit/ohjeitavuokratupa
https://www.luontoon.fi/tuvat

Käyttäjän kannalta olisi ehkä parasta että olisi tämäntyyppisille _retkeilytuville_ oma terminsä. Tästä aiheesta kun olen kiinnostunut niin ei tulisi mieleen/en näkisi järkevänä hakea termillä "stugor".  Toisaalta sanastossa on kyllä osittain päällekkäinen "autiotuvat"...

**Comment by ilona-x** [comment]
YSOssa on siis tällä hetkellä:
ulkoilumajat
urheilumajat 
tuvat (rakennukset)
autiotuvat

--

Lisäksi löytyi termiehdotus:
varaustuvat #1567  
KT vuokratuvat

--

Ei ehkä kuitenkaan kannata ottaa näitä kaikkia eri tupatyyppejä omina termeinään, vaikka näistä autiotuvat nyt jo sanastossa onkin. 🤔 
https://kansallispuistot.fi/autiotuvat-varaustuvat-vuokratuvat-ja-paivatuvat-mita-eroa-niilla-on/

**Comment by mirmaid** [comment]
Sitä juuri mietin, että kun omaan korvaan _ulkoilumajat_ kyllä hyvinkin sopisi, niin esim. Google-haku tuo sillä sitten taas lähinnä sellaisia isompia ihan kunnon "taloja", joissa on esim. kahvilaa ym. palveluja. 

_Varaustuvat_ ja _autiotuvat_ kyllä varmaan kattaisi nämä retkeilytupa-aineistot.

Onkohan _ulkoilumajalla_ ja _urheilumajalla_ mitään eroa oikeastaan?

**Comment by krinay** [comment]
Ainakaan Melindan viitteiden perusteella ei ole helppoa mieltää eroa _ulkoilumajojen_ (YSO-terminä 10 tietueessa) ja _urheilumajojen_ (14 tietuetta) välillä. 

Kuinka paljon aineistoa näistä erilaisista tuvista ja majoista on? Voisiko yhdistää ainakin _ulkoilu- ja urheilumajat_?

**Comment by ilona-x** [comment]
Joo, vaikuttavat kyllä nopealla tutkimisella aika päällekäisiltä.

Näistä **urheilumajat** näyttää olleen sanastossa vuodesta 1986 ja **ulkoilumajat** on otettu sanastoon v. 2002 mahdollisesti tämän v. 2002 ilmestyneen teoksen pohjalta: Ulkoilumaja : opas taukopaikkojen ja ulkoilumajojen parissa toimiville https://melinda.kansalliskirjasto.fi/byid/000310988

--

Kielitoimiston sanakirja:
**ulkoilumaja**  https://www.kielitoimistonsanakirja.fi/#/ulkoilumaja?searchMode=all
ulkoilijoiden virkistäytymispaikaksi tarkoitettu rakennus. 

Urheilumajaa ei Kielitoimiston sanakirjasta löydy, mutta hiihtomaja löytyy ⛷️ :
**hiihtomaja**
hiihtäjille tarkoitettu ulkoilumaja.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _retkeilytuvat_, ohjaustermeiksi _varaustuvat_, _päivätuvat_, _vuokratuvat_. Alakäsitteeksi _autiotuvat_. Hyväksytään _ulkoilumajat_, ohjaustermiksi _urheilumajat_.

**Comment by mariaforsen** [comment]
Sv. rast- och övernattningsstugor HT vandringsstugor, utfärdsstugor (i naturen), utflyktsstugor (i naturen), friluftsstugor (i naturen), raststugor (i naturen), stugor (naturutfärd), reserveringsstugor, hyresstugor, övernattningsstugor, vandrarstugor, gratisstugor (i naturen)

https://www.utinaturen.fi/stugor/stugtyper
https://www.vildmarksliv.nu/fjallvandring/
https://www.friluftsframjandet.se/lat-aventyret-borja/kunskap--guider/hallbart-friluftsliv/200-oppna-stugor/
https://termipankki.fi/tepa/fi/haku/retkeily
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_d8e9e51cd34226d186f4163bf867b5a5&list_id=1&keyword=retkeily&word=retkeily
https://www.sanakirja.fi/custom/all/retkeily
https://fi.wikipedia.org/wiki/Retkeily
jfr https://finto.fi/yso/fi/page/p1103

Sv. rasttugor  > friluftsstugor ..raststugor även ~retkeilytuvat/päivätuvat (Fortsstyrelsen) ..urheilumajat=sportstugor ANV ulkoilumajat
jfr https://finto.fi/yso/fi/search?clang=sv&anylang=on&q=ulkoilu 
https://www.suomi.fi/service/friluftsstugor-helsingfors-stad-kultur-och-fritidssektorn/12f572de-9db7-4584-87c0-bb5f82b6163b
https://sundsvall.se/uppleva-och-gora/idrott-motion-och-friluftsliv/friluftsliv-och-motion/friluftsanlaggningar/friluftsstugor
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_ac5ca40901a1ce5462f829114eb1614c&list_id=1&keyword=ulkoilu&word=ulkoilu
https://termipankki.fi/tepa/fi/haku/ulkoilu
