### ISSUE TITLE
taloudenhoitajat (rahatalous)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11318]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taloudenhoitajat (rahatalous)](http://www.yso.fi/onto/yso/p7819)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan kielivastaavuus vielä

**Perustelut ehdotukselle**

sv. kassörer sopii muihinkin kuin yhdistyksiin

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ongelmatapauksia ainakin:
https://melinda.kansalliskirjasto.fi/byid/018751153
https://melinda.kansalliskirjasto.fi/byid/006064949
https://melinda.kansalliskirjasto.fi/byid/000935091 (yrityksen kassanhoitaja)
https://melinda.kansalliskirjasto.fi/byid/009581215
https://melinda.kansalliskirjasto.fi/byid/009581196

**Comment by mariaforsen** [comment]
Mikä olikaan ongelma?

**Comment by mirmaid** [comment]
Eli kaikki, jotka ruotsiksi ovat kassörer, eivät ole suomeksi taloudenhoitajia. Joissakin em. tapauksista titteli olisi suomeksi ollut kassanhoitaja, joissakin tapauksissa jotain muuta. Ja esim. ensimmäisessä kai on tarkoitettu valtiovarainministeriä vastaavaa virkaa, eli ei taida olla ruotsiksikaan oikein nyt. 

Eli tuntuu, että tämä melkein pitäisi rajata yhdistyksiin, ettei tule virheitä.

**Comment by mariaforsen** [comment]
Ok, kuulostaa kyllä siltä että rajaaminen molemmilla kielillä on ainoa tapa saada täsmäämään. Nimitykset tosiaan vaihtelevat.

**Comment by mirmaid** [comment]
Ehdotus siis: taloudenhoitajat (rahatalous) > taloudenhoitajat (yhdistykset)

**Comment by YSO-kokous** [comment]
**Päätös**

Yhdistetään ehdotuksen mukaisesti.
