### ISSUE TITLE
VTLS

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11324]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[VTLS](http://www.yso.fi/onto/yso/p18349)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yläkäsitteeksi kirjastojärjestelmät?

**Perustelut ehdotukselle**

https://journal.fi/signum/article/view/112163

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Ohjaustermiksi Virginia Tech library system?
