### ISSUE TITLE
SLM: pienpainatteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11323]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM: pienpainatteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

ephemera (publications)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termi pienpainatteet on jo YSO:ssa, mutta se tarvittaisiin myös SLM-sanastoon, vrt. muu pienpainatekokoelmaan kuuluva aineisto, joka jo on SLM-sanastossa: esitteet, hinnastot, julisteet, käsiohjelmat, luettelot, mainokset, oppaat (teokset)... 

**Ehdotettu yläkäsite YSOssa (LT)**

 [julkaisut](http://www.yso.fi/onto/yso/p1548)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556), [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564)

**Vaihtoehtoiset termit**

 -

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [efemärt tryck](https://id.kb.se/term/sao/Efem%C3%A4rt%20tryck)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pienpainatekokoelma-aineiston takautuva kuvailu arkistojärjestelmään. 

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6962

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

KT tilapäispainatteet, tilapääjulkaisut

**Comment by mariaforsen** [comment]
Sv. småtryck HT efemärt tryck, vardagstryck 

https://id.kb.se/find?q=efem%C3%A4rt%20tryck
https://blogs.helsinki.fi/scriptaselecta/tag/pienpainatteet/
https://www.kansalliskirjasto.fi/sv/samlingar/smatryckssamlingen-huvudsamlingen

**Comment by mirmaid** [comment]
Ovatko _esitteet, hinnastot, julisteet, käsiohjelmat, luettelot, mainokset_ tämän alakäsitteitä (ks. ehdotus)? (YSOssa vain käsiohjelmat).

**Comment by mirmaid** [comment]
Käsiohjelmat, postikortit ok alakäsitteenä.

**Comment by Liisa-h** [comment]
Vapaakappaletoimiston laatimassa pienpainateluettelossa (aineistoa, jota kirjapainon tulee luovuttaa kaksi kappaletta) mainituista seuraavat löytyvät SLM:sta. 

eripainokset
esitteet
hakemistot
hinnastot
julisteet
kalenterit
kunnalliskertomukset
kuvastot
luettelot
mainokset
ohjelmat (esim. teatteri-, näyttely- ja urheilukilpailuohjelmat) -> SLM:ssa käsiohjelmat
oppaat (esim. käyttö-, henkilöstö-, opinto- ja palveluoppaat)
pelit: lautapelit, korttipelit, roolipelit
postikortit
puhelinluettelot
puuhakirjat
sanaristikot
standardit
toimintakertomukset
värityskirjat

**Comment by mariaforsen** [comment]
SLM-termi "oppaat (teokset)" viittaa tosin yleensä varmaan tavallisiin kirjoihin, jotka eivät ole pienpainatteita.

**Comment by mirmaid** [comment]
Listalla myös muita, jotka eivät välttämättä ole pienpainatteita.

**Comment by mirmaid** [comment]
Esitteet, eripainokset, hinnastot, julisteet, kalenterit, kunnalliskertomukset, toimintakertomukset, tuoteluettelot, huutokauppaluettelot, jäsenluettelot, osoiteluettelot, puhelinluettelot, mainokset, opinto-oppaat, postikortit, käsiohjelmat.

Matrikkelit pois hakemistojen alta?

**Comment by fantsby-m** [comment]
"Pienpainatteet ovat enimmäkseen käytännön elämään liittyviä, yleensä lyhytaikaiseen käyttöön tarkoitettuja ja ajankohtaisuutensa verrattain nopeasti menettäviä painotuotteita. Julkaisun kuuluminen pienpainatteisiin ei perustu painoksen suuruuteen tai julkaisun fyysiseen kokoon."
(lähde: https://www.kansalliskirjasto.fi/fi/vapaakappaletoimisto/painotuotteet-ja-tallenteet)

**Comment by mirmaid** [comment]
^ Määritelmä myös YSOon? Entä hierarkia (ei kuitenkaan mainokset)?

**Comment by vthuhtal** [comment]
Termiä ei kai pysty määritteemään mitenkään järkevästi?

**Comment by Liisa-h** [comment]
Ei kaiketi pysty.  TYK:n sivuilla on hieman pitempi määritelmä kuin ylläesitetty Kansalliskirjaston, mutta siinäkin toistuvat sanat yleensä, enimmäkseen, usein... eli  täsmällinen määritys jää avoimeksi.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään YSOon määritelmä ja hierarkiaa yhdenmukaistetaan soveltuvin osin.
