### ISSUE TITLE
rukouskirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11322]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rukouskirjat](http://www.yso.fi/onto/yso/p21730)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM: rukoukset ohjausterminä tai uutena erillisenä terminä

**Perustelut ehdotukselle**

Kuvailijan ja tiedonhakijan avuksi, ainakin ohjaustermiksi. Kaikki rukouksia sisältävät aineistot eivät tosin ole kirjoja, ja osa aineistoista eivät ole varsinaisia "rukouskirjoja", vaikka sisältävät runsaasti rukouksia. Esimerkkiaineistona tällä kertaa Suojele luotujasi / Satu Saarikko & Limppu Witick

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
Vrt. ruokaohjeet / keittokirjat

**Comment by mirmaid** [comment]
Toinen vastaava vähän vastaava lajityyppi olisi vitsit, vitsikirjat-genreä ei ole erikseen. Jos on molemmat, päällekkäistä käyttöä on paljon (kuten nyt ruokaohjeet/keittokirjat-parin kanssa).

**Comment by AuHo22** [comment]
Vaihtoehdoksi jäänee sitten 650-kentän käyttö näissä jonkin verran tietyn tyyppistä aineistoa sisältävissä teoksissa.

**Comment by mirmaid** [comment]
Ehdotettu muutosta rukouskirjat KÄ rukoukset. Jaakko kysyy kommenttia tähän teologisen tiedekunnan kirjastosta.

**Comment by jtuohini** [comment]
HYK:n teologian kokoelmavastaavan mukaan **rukouskirjat** tarvitaan lajityyppiterminä.

**Comment by jtuohini** [comment]
Kysytty uudestaan. Sittenkin nykyinen **rukouskirjat** voidaan muuttaa itse teoksiin (_**rukoukset**_) viittaavaksi, joten saadaan tältä osin SLM yhteismitalliseksi LCGFT:n kanssa, ks. [**Prayers**](http://id.loc.gov/authorities/genreForms/gf2015026049). Rukouskirjoihin voidaan laittaa erillinen SLM-termi ilmaisemaan, että kyse on kokoomateoksesta.

**Comment by mirmaid** [comment]
Rukouskirjat KÄ rukoukset
