### ISSUE TITLE
tiedolla johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11334]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tiedolla johtaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

knowledge-based management

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tietotermit](https://finto.fi/tt/fi/page/t90)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018735721

**Ehdottajan organisaatio**

KK/MP

**Comment by ilona-x** [comment]
Tietotermeissä siis näin:

**tiedolla johtaminen**  http://urn.fi/URN:NBN:fi:au:tt:t90
Määritelmä
tietojohtamisen osa-alue, joka tähtää tietoperustaiseen päätöksentekoon ja sen mahdollistamiseen

--

YSOssa
tietojohtaminen KÄYTÄ tietämyksenhallinta http://www.yso.fi/onto/yso/p9226

**Comment by mariaforsen** [comment]
Tietämyksenhallinta on sv. kunskapshantering, joten se on kieltämättä eri asia kuin tiedolla johtaminen. Kannatan siis uutta termiä.

**Comment by mirmaid** [comment]
Tietotermit-sanastossa ei ole tietämyksenhallinta-käsitettä, mutta tietojohtaminen = knowledge management, joka on ysossa tietämyksenhallinnan eng. käännös.

YSOssa on tietämyksenhallinnan lisäksi tiedonhallinta (löytyy myös Tietotermeistä: tietoprosessien järjestäminen siten, että tietojen saatavuus, löydettävyys ja hyödynnettävyys eri tarkoituksiin pyritään varmistamaan tiedon elinkaaren ajan).

Tietojohtaminen http://urn.fi/URN:NBN:fi:au:tt:t9

**Comment by mirmaid** [comment]
Ks. myös https://fi.wikipedia.org/wiki/Tietojohtaminen#Tietojohtamisen_tutkimus_maailmalla

**Comment by mariaforsen** [comment]
Tässä myös huomioitava että tieto voi olla kolme eri asiaa, ruotsiksi data vs. information vs.  kunskap. YSOssa tietämyksenhallinta on kunskapshantering ja tiedonhallinta informationshantering.

**Comment by fantsby-m** [comment]
Knowledge management ja knowledge-based management ovat eri käsitteitä. Kyse ei ole tietämyksenhallinnasta eikä tiedonhallinnasta vaan tiedolla johtamisesta.

Ks. myös
https://soteuudistus.fi/-/tiedolla-johtaminen-mahdollistaa-sote-palvelujarjestelman-uudistamisen

**Comment by ilona-x** [comment]
Mainitsin tuon tietämyksenhallinta KT tietojohtaminen asian, kun huomasin, että tämä tiedolla johtaminen on Tietotermeissä [tietojohtamisen ](http://urn.fi/URN:NBN:fi:au:tt:t9)alakäsite ja Tietotermeissä on tietojohtamisella vielä toinenkin alakäsite tiedon johtaminen. Ja ajattelin, että jos tämä tietojohtamisen alakäsite otetaan YSOon, niin olisi hyvä tarkastella myös tuo tietojohtaminen KÄYTÄ tietämyksenhallinta-asia samalla.

**Comment by mirmaid** [comment]
^ Tai siis **tietämyksen**hallinta.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _tiedolla johtaminen_, lisätään tietotermien määritelmä. 

Lisätään ohjaustermiin _tietojohtamiseen_ tarkenne _tietämyksenhallinta_.

**Comment by mariaforsen** [comment]
Sanastossa on jo tietoperustainen johtaminen http://www.yso.fi/onto/yso/p25368 Eroaako se tästä, miten? 
Jos tiedolla johtaminen on "..ajantasaiseen ja laadukkaaseen tietoon perustuvaa päätöksentekoa"?

**Comment by ilona-x** [comment]
Tässä ehdotuksessa  on englanninkielisenä terminä knowledge-based management, mikä näyttää olevan tuon Marian mainitseman [tietoperustainen johtaminen](http://www.yso.fi/onto/yso/p25368) -termin englanninkielisenä vastineena.

**Comment by ilona-x** [comment]
ja ehdotuksessa https://github.com/Finto-ehdotus/YSE/issues/11629 on ehdotettu, että tiedolla johtaminen vaihdettaisiin tietoperustaisen johtamisen päätermiksi

**Comment by mirmaid** [comment]
Huh, eli olisiko mahdollista tehdä tuo muutos tietoperustainen johtaminen > tiedolla johtaminen? Aivoni ovat nyt liian solmussa hahmottaakseni, mitä muuta mahdollisesti pitäisi korjata, mutta ehkä jonain virkeänä aamuhetkenä...

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään viimeisin ehdotus.

**Comment by mariaforsen** [comment]
Sv. kunskapsbaserad ledning HT ledning genom information (fi) (ingen ändring på svenska i detta skede) 

https://www.avoindata.fi/sv/handlingsmodellen/1-fr%C3%A5n-informationshantering-till-utnyttjande-och-%C3%B6ppnande-av-information#informationspolicy
https://soteuudistus.fi/sv/kunskapsbaserad-ledning
https://oikeusministerio.fi/sv/kunskapsbaserad-ledning-och-forskningsverksamhet
https://www.tietoosaava.fi/sv/hem/
https://vm.fi/sv/kunskapsbaserad-ledning
https://www.ilmarinen.fi/sv/arbetsformaga/kunskapsledning/implementering/
https://www.fimea.fi/web/sv/-/mot-kunskapsbaserad-ledning-av-rationell-lakemedelsbehandling-och-lakemedelsforsorjning-utredningen-ar-klar
https://www.keha-keskus.fi/sv/uppgifter-och-tjanster/framjande-av-integration/koto-digi-projektet/koto-digi-och-ledning-genom-information
https://finto.fi/tt/fi/page/t90?clang=sv
https://www.sanakirja.fi/custom/en-sv-fi/tiedolla%20johtaminen

**Comment by mirmaid** [comment]
Ja ilmeisesti myös tämä päätös "Lisätään ohjaustermiin tietojohtamiseen tarkenne tietämyksenhallinta." on edelleen ok?
