### ISSUE TITLE
itsevaltius

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11335]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[itsevaltius](http://www.yso.fi/onto/yso/p8528)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT autokratia

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan tarkemmin mm. suhdetta käsitteeseen _yksinvalta_.

**Comment by mariaforsen** [comment]
NE: "autokrati: styrelseform där makten helt ligger i en enda härskares händer och utövas av denne ensam"
NE: "envälde: betyder att en person har all makt"
Wikipediassa nämä käsitellään synonymeinä sekä ruotsiksi että suomeksi:
https://sv.wikipedia.org/wiki/Env%C3%A4lde
https://fi.wikipedia.org/wiki/Itsevaltius

https://www.kielitoimistonsanakirja.fi/#/yksinvalta
https://www.kielitoimistonsanakirja.fi/#/itsevaltius

SAOssa envälde https://id.kb.se/term/sao/Env%C3%A4lde 
Autokrati ohjaa despotismiin (ei ysossa) ja absolutismiin. 

Joissakin lähteissä sv. autokrati vastakohtana demokratiaan: "Autokrati: Styrelseskick som innebär en form av envälde, där en ensam person eller gupp har makten att styra ett land eller stat. Exempel på autokratiska länder är Iran och Kina." /https://globalportalen.org/artiklar/demokratin-i-europa-gar-det-framat-eller-bakat Joskus sv. autokrati käsitellään eräänlaisena diktatuurina.

Itsevaltius voisi ehkä muuttaa > sv. despotism. Jos despotismi olisi ohjaustermi? https://www.kielitoimistonsanakirja.fi/#/despotismi

**Comment by mirmaid** [comment]
^ Voisi varmaan olla, mutta en tiedä hahmottuisiko suomeksi kuitenkaan ero itsevaltiuden ja yksinvallan ja toisaalta diktatuurin välillä.

**Comment by mirmaid** [comment]
Jos molemmat säilytetään sanastossa, kannatan määritelmiä, ja itsevaltiudelle vähintään ohjaustermejä absolutismi, despotismi, (absoluuttinen monarkia?) - jos siis katsotaan, että se on riittävän selkeä sellaisenaan. 

Entä autokratia?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11527

**Comment by FinMeSHienPaimentaja** [comment]
Maallikon näkemys: autokratia == itsevaltius.  

Itsevaltiuteen maallikon näkemyksen mukaan sisältyy tyrannia, despotismi, monarkia jne. jne., jotka tavallaan tarkentavat autokratian luonnetta, että millaista missäkin tapauksessa on/oli. 

https://www.etymonline.com/word/autocracy

**Comment by mirmaid** [comment]
Turvauduin taas vanhaan kunnon Otavan Isoon tietosanakirjaan, ja sen mukaan näyttäisi suunnilleen pätevältä jaottelu yksinvalta vs. itsevaltius KT autokratia ym. Tässä siis monarkia ja itsevaltius olisivat yksinvallan alakäsitteitä, diktatuuri itsevaltiuden alakäsite. Mutta tämä pätee nyt huonosti kielten välillä. Lähtisinkin ehkä sittenkin liikkeelle siitä, että korjataan kaikki ne yksinvalta-viitteet, joissa kyse on itsevaltiudesta, ja katsotaan mitä jää jäljelle. En tiedä onko niin, että suomeksi sekä monarkian että itsevaltiuden määritelmät ovat vähän tiukemmat kuin vastaavien eng. termien, jolloin tuo yksinvalta kuitenkin tarvitaan kattokäsitteeksi yhden henkilön vallalle.

**Comment by AuHo22** [comment]
Siis ko. absoluuttinen monarkia, ei pelkkä monarkia, koskapa on myös perustuslaillisia tai parlamentaarisia monarkioita, jotka eivät enää ole itsevaltiaita järjestelmiä, tarkennuksena siis

**Comment by mirmaid** [comment]
^ Monarkia ei siis olisi itsevaltiuden alakäsite vaan yksinvallan. Toki voidaan sanoa, ettei parlamentaarinen monarkia ole edes yksinvaltainen, mutta toisaalta miten yksinvalta sitten loppujen lopuksi määriteltäisiin, ts. kuinka paljon valtaa yli instituutioiden hallitsijalla pitää olla, että kyseessä on yksinvalta 🤔

**Comment by AuHo22** [comment]
Näissä määritelmissä on myös eri aikakausiin liittyviä piirteitä, esim. _Sanalla itsevaltius viitataan yleensä 1900-lukua edeltäneeseen aikaan; nykyisistä valtioista, joiden valtionpäämiehien valtaa ei lainkaan rajoiteta, käytetään tavallisemmin nimeä diktatuuri ja niiden hallitsijoista nimeä diktaattori._ https://fi.wikipedia.org/wiki/Itsevaltius (+puoluediktatuuri ja sotilasdiktatuuri jo YSOssa hyvin)
Ja yo. ohjaustermit voisivat olla kannatettavia: itsevaltius KT absolutismi (valtiomuoto?), despotismi, absoluuttinen monarkia.
YSO-sanastossa on sitten myös käsite autoritaarisuus, jota on voitu käyttää eri asteisten autoritaaristen hallintojen kuvaamiseen. https://fi.wikipedia.org/wiki/Autoritarismi

Yksinvalta-käsitettä näyttäisi olevan käytetty enemmän kuvaamaan ilmiötä, so. vallan laatua  laajemmin (vrt. myös autoritaarisuus), kun taas sitten yo. termit kuvaavat enemmän poliittisista järjestelmää?
Myös https://politiikasta.fi/kysy-politiikasta-mika-on-autoritaarisen-ja-totalitaarisen-jarjestelman-ero/

**Comment by YSO-kokous** [comment]
Lisätään seuraavat ohjaustermit: 
absolutismi (itsevaltius) KÄYTÄ itsevaltius 
despotismi KÄYTÄ itsevaltius
absoluuttinen monarkia KÄYTÄ itsevaltius
autokratia KÄYTÄ itsevaltius

Lisätään nykyiselle absolutismi-käsitteelle sulkutarkenne eli käytettäväksi termiksi absolutismi (filosofia).

Tutkitaan, onko tarvetta uudelle absolutismi-johdannaiselle käsitteelle (tai ohjaustermille) alkoholin käyttöön liittyen. Tästä tehtäneen oma issuensa.

Huom! YSOn absolutismi-käsite on nyt linkattu väärin: http://www.yso.fi/onto/yso/p17309
Korjataan linkitys.

**Comment by mirmaid** [comment]
Absolutismi (päihteet) KÄ päihteettömyys, raittius

**Comment by tpalonen** [comment]
Virheellinen absolutismi-linkkaus poistettu.
