### ISSUE TITLE
SLM : eripainokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11338]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM : eripainokset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

offprints

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Pienpainatekokoelmassa on runsaasti eripainoksia, joten SLM-termi olisi tarpeellinen.

**Ehdotettu yläkäsite YSOssa (LT)**

 [painokset](http://www.yso.fi/onto/yso/p26771)

**Ehdotetut temaattiset ryhmät**

 [82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston pienpainatekokoelman takautuva kuvailu arkistojärjestelmään.

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6804

**Comment by mariaforsen** [comment]
Sv. särtryck HT separat (publikationer), separattryck
https://finto.fi/yso/fi/search?clang=sv&anylang=on&q=eripainos

https://termipankki.fi/tepa/fi/haku/eripainos
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_63d59b1347b55b1de5f58d44b8147707&list_id=1&keyword=eripainos&word=eripainos
https://www.sanakirja.fi/custom/fi-en-sv/eripainos
https://termipankki.fi/tepa/fi/haku/eripainos

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

Lisätään Tieteen termipankin määritelmä: _Kokoomateoksessa tai lehdessä julkaistun itsenäisen kirjoituksen julkaiseminen erillisenä painotuotteena. Eripainos painetaan samalla ladelmalla kuin alkuperäinen julkaisu, mutta sivunumerointia voidaan muuttaa ja siihen voidaan lisätä oma kansilehti._
