### ISSUE TITLE
SLM : kirjastoluettelot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11339]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM : kirjastoluettelot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

library catalogues

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Pienpainatekokoelmassa on runsaasti kirjastoluetteloita, joten SLM-termi olisi tarpeellinen.

**Ehdotettu yläkäsite YSOssa (LT)**

 [bibliografiat](http://www.yso.fi/onto/yso/p3462)

**Ehdotetut temaattiset ryhmät**

 [81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/yso/p26572)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston pienpainatekokoelman takautuva kuvailu arkistojärjestelmään.

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen

**Comment by AuHo22** [comment]
En oikein hahmota, mitä tällä tarkoitetaan: Onko kyseessä ns. korttiluettelo? https://www.kansalliskirjasto.fi/fi/kokoelmat/caucasica
Termi kirjastoluettelo voi sitten kuvata sitten jo laajemminkin kirjastotietokantoja 
https://en.wikipedia.org/wiki/Library_catalog
https://www.tyovaenperinne.fi/tiedonhaku/tietokannat/

**Comment by mirmaid** [comment]
Kysytään tarkennusta, millaisia aineistoja tällä kuvattaisiin. Sanastossa on jo kokoelmaluettelot, soveltuisiko se (tai mahdollisesti luettelot + soveltuva asiasana)?

**Comment by jaaskelj** [comment]
Kyseessä ei ole korttiluettelo eikä varsinainen kokoelmaluettelo, vaan ns. uutuusluettelo, joita kirjastot ovat vuosittain tehneet kirjahankinnoista ja lehtitilauksista. Voimme korvata genretermillä ja asiasanalla, koska esim. YSO-termi kirjastoluettelot viitannee juuri korttiluetteloihin, vai kuinka?

**Comment by mariaforsen** [comment]
Voisiko tällaisille uutuusluetteloille olla ihan oma termi: https://termipankki.fi/tepa/fi/haku/uutuusluettelo 
"sekundaarijulkaisu, joka sisältää tietoa yhteisön määräaikana hankkimista julkaisuista"

**Comment by mirmaid** [comment]
Hyväksytty muodossa uutuusluettelot (kirjastot).

YSO: muutetaan uutuustiedotteet > uutuusluettelot (kirjastot)

**Comment by mariaforsen** [comment]
Sv. nyhetskataloger (bibliotek) HT nyförvärvslistor (bibliotek), nyhetsförteckningar (bibliotek), nyhetslistor (bibliotek)

https://termipankki.fi/tepa/fi/haku/uutuusluettelo
https://www.sanakirja.fi/custom/en-sv-fi/uutuusluettelo
https://www.rikstermbanken.se/search?q=nyf%C3%B6rv%C3%A4rvslista&s=termer 
https://www.kansalliskirjasto.fi/sv/tjanster/fennica-finlands-nationalbibliografi

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
