### ISSUE TITLE
teatteriohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11337]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

teatteriohjelmat

**Ehdotettu termi ruotsiksi**

teaterprogram

**Ehdotettu termi englanniksi**

theater programs (US) 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käsiohjelmien alakäsite konserttiohjelmat on SLM- ja YSO-sanastoissa. Teatteriohjelmat on vastaava käsite ja ehdotan sitä molempiin sanastoihin. Ehdotus tehty myös käsitteestä elokuvaohjelmat.

**Ehdotettu yläkäsite YSOssa (LT)**

 [käsiohjelmat](http://www.yso.fi/onto/yso/p28147)

**Ehdotetut temaattiset ryhmät**

 [95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582)

**Vaihtoehtoiset termit**

 theater programmes (UK)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/Teaterprogram), [LCSH](https://id.loc.gov/authorities/subjects/sh85134577.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston pienpainatekokoelman takautuva kuvailu arkistojärjestelmään.

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen
**Termiehdotus Fintossa:** [teatteriohjelmat](http://finto.fi/yse/fi/page/Y511337)

**Comment by mirmaid** [comment]
Ei Melindassa. Sanastossa on jo _käsiohjelmat_, jota käytetty kaiken kaikkiaan vain 113 kertaa, usein juuri teatteriohjelmista. Jos jaotellaan tarkempiin alakäsitteisiin, voi kyllä seurata epäjohdonmukaista käyttöä tai käydä niin, että laajempi termi jää kokonaan ylimääräiseksi 🤔

**Comment by mariaforsen** [comment]
https://id.kb.se/term/sao/Teaterprogram

**Comment by mirmaid** [comment]
SLM-ryhmä suosittelee genretermin käsiohjelmat ja sopivan asiasanan käyttöä.

**Comment by jaaskelj** [comment]
Pienpainatekokoelmassa on erillinen kokoelma, joka sisältää sidottuna pääsääntöisesti teatteriohjelmia: https://www.kansalliskirjasto.fi/fi/kokoelmat/mathias-weckstromin-kokoelma

**Comment by mirmaid** [comment]
Hyväksytään muodossa teatteriohjelmat (käsiohjelmat).

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Sv. teaterprogram (programblad)
https://id.kb.se/find?q=teaterprogram
https://www.sanakirja.fi/custom/en-sv-fi/teatteriohjelma

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
