### ISSUE TITLE
saamelaiskielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11332]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[saamelaiskielet](http://www.yso.fi/onto/yso/p18720)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään englanninkielisiin viittausmuotoihin "Lappic languages"

**Perustelut ehdotukselle**

On UDK-luokan =511.12 nimessä "Sami / Saami / Lappic languages"

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja päätös on mikä? Ja miksi on peukutettu alaspäin ilman perusteluja? Eikö tarkoitus ole joko kannattaa esitystä vai vastustaa kera perusteluin?

**Comment by tpalonen** [comment]
Lisätään tämä Lappic-muoto, mutta varustamme sen englanninkielisellä kulttuurisensitiivisyys/disclaimer-tekstillä, kuten lappalais-muodot myös suomen kielen puolella sanastossa. Sanastossa ei ole vielä näitä englanninkielisiä disclaimer-merkintöjä, mutta ovat tulossa piakkoin.

**Comment by mirmaid** [comment]
^ YSO-ylläpitoryhmässä lappic languages -muotoa ei pidetty tarpeellisena ohjausterminä.
