### ISSUE TITLE
baryogeneesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11349]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

baryogeneesi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/82745#

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [baryogeneesi](http://finto.fi/yse/fi/page/Y511349)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Baryogenesis
https://areena.yle.fi/podcastit/1-50273397

Ei LCSH:ssa, eikä aiemmin Melindassa, mutta asiaa on aika vaikea muuten ilmaista.

**Comment by mariaforsen** [comment]
Sv. baryogenes
https://www.lu.se/lup/publication/8877188

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
