### ISSUE TITLE
virtsahappo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11340]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[virtsahappo](http://www.yso.fi/onto/yso/p23154)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi uraatti

**Perustelut ehdotukselle**

FinMeSH http://www.yso.fi/onto/mesh/D014527

väitöskirja: https://www.tuni.fi/fi/ajankohtaista/venla-kurra-veren-korkealla-uraattipitoisuudella-seka-suotuisia-etta-haitallisia

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. HT urat
