### ISSUE TITLE
fermionit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11348]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fermionit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/82745#

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [fermionit](http://finto.fi/yse/fi/page/Y511348)

**Comment by mariaforsen** [comment]
Sv. fermioner /ne, sao

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85047833
https://fi.wikipedia.org/wiki/Fermioni

3 viitettä Melindassa.
