### ISSUE TITLE
pienpuolueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11341]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pienpuolueet

**Ehdotettu termi ruotsiksi**

småpartier

**Ehdotettu termi englanniksi**

minor parties

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vakiintunut käsite. Yläkäsitteellä puolueet on useita samankaltaisia alakäsitteitä, esim. europuolueet, vasemmistopuolueet. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [puolueet](http://www.yso.fi/onto/yso/p8958)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://sv.wikipedia.org/wiki/Svenska_sm%C3%A5partier_och_deras_resultat_i_riksdagsval), [Wikipedia](https://en.wikipedia.org/wiki/Minor_party)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston pienpainatekokoelman takautuva kuvailu arkistojärjestelmään.

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen
**Termiehdotus Fintossa:** [pienpuolueet](http://finto.fi/yse/fi/page/Y511341)

**Comment by mirmaid** [comment]
Ei varmaan haittaa, että tämä ei ehkä maasta toiseen ole ihan tarkasti sama asia?

**Comment by fantsby-m** [comment]
Puolueet-termin nykyiset alakäsitteet eivät ole ihan samantyyppisiä tämän kanssa, ne ovat kansainvälisestikin vakiintuneita käsitteitä. Miten pienpuolue määritellään? Termi kuulostaa helposti arvottavalta. Onko puolue pienpuolue, jos se on nyt pieni vaikka olisi joskus ollut suuri, siirretäänkö puolue pienpuolueeksi kun se kutistuu tarpeeksi pieneksi - ja päinvastoin: poistuuko pienpuolue-label jos puolue kasvaakin suureksi?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. småpartier HT små partier
