### ISSUE TITLE
kallioimarrekasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11346]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kallioimarrekasvit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/346274

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kallioimarrekasvit](http://finto.fi/yse/fi/page/Y511346)

**Comment by mirmaid** [comment]
https://laji.fi/taxon/MX.37794
https://fi.wikipedia.org/wiki/Kallioimarrekasvit
LCSH: http://id.loc.gov/authorities/subjects/sh85104713

**Comment by mariaforsen** [comment]
Sv. stensöteväxter /ne
https://namnochslaktskap.artfakta.se/taxa/2002668/details
