### ISSUE TITLE
viulistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11355]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[viulistit](http://www.yso.fi/onto/yso/p22505)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään RT-suhteita eri muusikoiden ja soittimien välille, eli esim. viulistit RT viulut, rumpalit RT rummut, pianistit RT piano jne. 

**Perustelut ehdotukselle**

Liittyvät vahvasti toisiinsa. 

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Hyvä ehdotus! Ehdottaisin myös seuraavia:
soitinmusiikin alakäsitteille RT-suhde vastaavaan soittimeen. Esim. viulumusiikki RT viulu.
Lisäksi ehdottaisin:
laulajat RT laulaminen
kuoronjohtajat RT kuorot
kansanmuusikot RT kansanmusiikki
kansanlaulajat RT kansanmusiikki
säveltäjät RT säveltäminen
orkesterimuusikot RT orkesterit

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään RT-suhteet ehdotusten mukaisesti.

**Comment by tpalonen** [comment]
YSO-kokouksessa todettiin myös, että jatkossa olisi hyvä lisätä vastaavanlaiset RT suhteet kun sanastoon tulee uusia soitin- tai soittajakäsitteitä.
