### ISSUE TITLE
suomalaistyyppinen suvuittainen amyloidoosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11352]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[suomalaistyyppinen suvuittainen amyloidoosi](http://www.yso.fi/onto/yso/p5247)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT gelsoliiniamyloidoosi, AGel-amyloidoosi

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
Niin tai näin, mielestäni ohjaustermeihin kiinnitettävä huomiota (Meretojan tauti yms.) Selkeyden vuoksi olisi mielestäni hyvä, että perinnöllisyys-aspekti näkyisi käytettävässä termissä myös. 

https://www.terveyskirjasto.fi/dlk00625

**Comment by mirmaid** [comment]
^ En siis ehdota termin muutosta, vain ohjaustermien lisäystä.
