### ISSUE TITLE
penissyöpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11358]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[syöpätaudit](http://www.yso.fi/onto/yso/p678)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisää penissyöpä hierarkiaan

**Perustelut ehdotukselle**

Koska se puuttuu hierarkiasta.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. peniscancer /ne HT penistumörer
https://mesh.kib.ki.se/term/D010412/penile-neoplasms
https://finto.fi/mesh/fi/page/D010412
