### ISSUE TITLE
erikoiskielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11354]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[erikoiskielet](http://www.yso.fi/onto/yso/p1349)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennys termin merkityskenttään ja ruotsinkieliseen vastineeseen

**Perustelut ehdotukselle**

Ruotsinkielinen vastine on ollut "specialspråk". Sanastossa on myös ammattikieli, ruotsin kannalta päällekkäisyyttä. 

Vaihtoehtoinen ratkaisutapa voisi olla: ammattikieli =  yrkesspråk HT fackspråk (yrkesspråk), erikoiskielet = fackspråk (specialspråk?), mutta siinä tapauksessa alakäsitteenä ei voi olla selkokieli. Miten laajasti tämän termin on siis tarkoitus viitata? Ruotsin käsitteenmuodostus eroaa suomenkielisestä.

Pitäisikö lisätä huomautuksia termien merkityksistä?  

https://termipankki.fi/tepa/fi/haku/erikoiskieli 
https://www.kielitoimistonsanakirja.fi/#/erikoiskieli?searchMode=all
https://termipankki.fi/tepa/fi/haku/ammattikieli
https://www.wikidata.org/wiki/Q109582287
https://termipankki.fi/tepa/fi/haku/erikoiskieli
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_7e2d6fdeaf9eac8bfdee8c7d6b65c6c2&list_id=1&keyword=ammattikieli&word=ammattikieli
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_ac91915afc14016e0b3b878769770d6f&list_id=1&keyword=erikoiskieli&word=erikoiskieli
https://www.sanakirja.fi/custom/en-sv-fi/erikoiskieli
https://www.rikstermbanken.se/search?q=fackspr%C3%A5k&s=termer
https://svenska.se/tre/?sok=fackspr%C3%A5k&pz=1
https://svenska.se/tre/?sok=yrkesspr%C3%A5k&pz=8
https://id.kb.se/find?q=fackspr%C3%A5k
https://www.isof.se/lar-dig-mer/kunskapsbanker/lar-dig-mer-om-facksprak-och-terminologi/facksprak

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Molemmat paljon käytettyjä kuvailussa...selkokieli voisi varmaan olla hierarkiassa muuallakin, mutta ammattikieli suomeksi kuitenkin paljon suppeampi kuin erikoiskielet. Eli myös jonkin tieteenalan tai harrastuksen kieli tai esim. uskonnollinen kieli. Ammattikieli on kuitenkin käytetty enemmän kuin erikoiskielet, joten olisi vaikea poistaa sitäkään.

**Comment by tpalonen** [comment]
Ohjaustermiksi tälle (ja ammattikielille) jargon tai jargonit?

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Terminologiaoppi:erikoiskieli
https://tieteentermipankki.fi/wiki/Terminologiaoppi:ammattikieli

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitetaan ehdotuksen mukaisesti. Lisätään Ohjaustermiksi _jargon_ / _jargonit_. Lisätään määritelmä.

Poistetaan RT-suhteita. Selvitetään mm. käsitteet _selkokieli_ paras paikka hierarkiassa.

Varmistetaan Melindasta tarvitaanko esimerkiksi _keinotekoisiin kieliin_ ohjaustermejä virheellisen käytön välttämiseksi.
