### ISSUE TITLE
risteytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11356]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[risteytys](http://www.yso.fi/onto/yso/p9177)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

päätermiksi risteyttäminen

**Perustelut ehdotukselle**

Nyt näyttää sekoittuneen käytössä risteytyminen-merkityksen kanssa

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tutkittava risteytys-viitteet, onko kyse missä määrin risteytyksestä ja missä määrin risteytymisestä. Mikä olisi paras korjaus sanastossa...

Samalla tarkistettava eng. vastineet, nyt cross-breed, joka vastaa vain osaa merkityksestä, ja lisäksi on muodoltaan eri (ei toimintaa).

**Comment by mariaforsen** [comment]
Sv. korsning (biologi) eli voi tosiaan olla yhtä lailla risteyttäminen kuin risteymä ja risteytyminen. Jos suomeksi > risteyttäminen niin sv. ehkä korsning (biologisk aktivitet tms.) Riippuen siitä mikä risteyttämisen merkityskenttä olisi suomeksi? Esim. Wikipediassa puhutaan eri roduista, entä lajien väliset? Ja jos risteyttäminen suomeksi viittaa vain ihmisten tekemiin risteytyksiin (?) niin sekin vaikuttaa sv-termin tarkenteeseen (ei voi olla sitten "biologisk process, joka olis muuten luonteva ruotsin kannalta kun ruotsiksi ei tehdä samaa passiivi/aktiivi -eroa). 

https://fi.wikipedia.org/wiki/Risteytt%C3%A4minen
https://termipankki.fi/tepa/fi/haku/risteytt%C3%A4minen
https://www.rikstermbanken.se/search?q=hybridisering&s=termer

**Comment by mirmaid** [comment]
_Risteytys (jalostus)_ sopisi ehkä luontevammin viitteisiin kuin _risteyttäminen_. Tai ainakin omaan korvaan niissä on pieni sävyero, ja tuo risteytys (jalostus) sopii hyvin kotieläimiin ja kasveihin. Risteyttäminen-sanasta tulee vähän "kertaluonteisempi" mielikuva, ja risteytystä voi ajatella myös ehkä vähän yleisemmällä tasolla.

**Comment by mariaforsen** [comment]
Se olisikin tosi hyvä ratkaisu, sv. voisi sitten olla korsning (förädling).

**Comment by YSO-kokous** [comment]
Muutetaan muotoon _risteytys (jalostus)_.
