### ISSUE TITLE
glymfaattinen järjestelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11369]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

glymfaattinen järjestelmä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/341726

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [glymfaattinen järjestelmä](http://finto.fi/yse/fi/page/Y511369)

**Comment by mirmaid** [comment]
Lääketieteen termit: glianestekierto: glymphatic system, glymphatic clearance pathway e, glymfatiska systemet r | imunesteen kiertoa muistuttava, gliasolujen väleistä tapahtuva aivo-selkäydinnesteen virtaus, joka poistaa aivokudoksesta aineenvaihduntajätteitä ja liiallista soluvälinestettä

FinMeSH: http://www.yso.fi/onto/mesh/D000077502
https://en.wikipedia.org/wiki/Glymphatic_system
https://www.duodecimlehti.fi/xmedia/duo/duo15417.pdf

**Comment by mariaforsen** [comment]
Sv. glymfatiska systemet HT glymfatiskt system
https://mesh.kib.ki.se/term/D000077502/glymphatic-system
https://lakartidningen.se/klinik-och-vetenskap-1/artiklar-1/klinisk-oversikt/2023/02/glymfatiska-systemet-renar-hjarnan-fran-slaggprodukter/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _glymfaattinen järjestelmä_, ohjaustermiksi _glianestekierto_.
