### ISSUE TITLE
nekroosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11368]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nekroosi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/347732

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [nekroosi](http://finto.fi/yse/fi/page/Y511368)

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

**nekroosi**

_necrosis, kuolio, kudoskuolio; elävän elimistön yhteydessä olevan kudoksen kuolema, kuolio patologisena käsitteenä; vrt. gangreeni_

-> Kuolioita voi olla sekä nekroosit että gangreenit.

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D009336 (gangreeni on MeSHissä nekroosin alakäsite)
LCSH: http://id.loc.gov/authorities/subjects/sh85090575

Lääketieteen termit: gangreeni: kuolio | (etenkin verenkierron estymisen aiheuttama) kudoksen paikallinen tuhoutuminen (jota usein seuraa infektoituminen)

**Comment by mirmaid** [comment]
MeSHissä kuolio on ohjaustermi gangreenille, mutta varmaan YSOon pitäisi ottaa joko _nekroosi_ tai _kuolio/kuoliot_ päätermiksi. Omaan korvaan nekroosi kuulostaa prosessilta ja kuolio enemmän lopputulokselta, mutta molempia ei varmasti kannata olla erikseen. Eng. wikipedian perusteella gangreeni olisi hyytymiskuolion tyyppi, Lääketieteen termien määrittelyt on kyllä varsin vaikeaselkoisia.

**Comment by mariaforsen** [comment]
Sv. nekros HT vävnadsdöd, lokal vävnadsdöd
https://svenska.se/tre/?sok=nekros&pz=8
https://ki.se/forskning/fakta-om-celldod
https://www.solunetti.fi/se/solubiologia/nekroosi_1/
https://www.medicinskordbok.se/term/nekros
https://termipankki.fi/tepa/fi/haku/nekroosi

"Kallbrand (gangrän) är spontan vävnadsdöd (nekros) på grund av dålig blodförsörjning."

Eli ainakin ruotsiksi kallbrand (gangreeni) ja nekros (nekroosi) olisi hyvä pitää erillisinä termeinä, kuten meshissäkin:
https://finto.fi/mesh/fi/page/D005734?clang=sv
https://finto.fi/mesh/fi/page/D009336?clang=sv

https://mesh.kib.ki.se/term/D009336/necrosis
https://www.ne.se/s%C3%B6k/?t=uppslagsverk&q=nekros
https://www.ne.se/s%C3%B6k/?t=uppslagsverk&q=kallbrand

**Comment by mirmaid** [comment]
Kyllä tuo tilanne MeSHissäkin ainakin suomeksi on epäselvä, koska kuolio ohjaa vain gangreeniin - muissa lähteissä ei ole näin.

**Comment by FinMeSHienPaimentaja** [comment]
Juu, totta, että FinMeSH:eissä on parantamisen varaa tuossa - laitetaan päivityslistalle.

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:nekroosi

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _nekroosi_. Tarkastellaan aineistoja tarvittaessa.
