### ISSUE TITLE
satunnaiskasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11362]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[satunnaiskasvit](http://www.yso.fi/onto/yso/p5762)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus, varsinkin eng. ja sv. termien suhteen

**Perustelut ehdotukselle**

Huomautus ei näytä täsmäävän eng. termin merkityksen kanssa. Adventive plant olisi ruotsiksi adventivväxt, mutta se ei tosiaan aivan täsmää suomenkielisen määritelmän kanssa (vakiintunut alueella vs. ei vakiintunut). Mahdollisesti myös suhde tulokaslaji-termiin?
https://termipankki.fi/tepa/fi/haku/satunnaiskasvi
https://en.wikipedia.org/wiki/Adventive_plant

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Määrittelyt näyttävät vähän eroavan eri lähteissä, mutta RT-suhde olisi varmaan ainakin vieraslajiin. Nyt RT tulokaslajit, joka on vähän ristiriidassa Tieteen termipankin määritelmän kanssa, mutta ei kaikkien.
