### ISSUE TITLE
digitaalinen hallintatodistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11361]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

digitaalinen hallintatodistus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

non-fungible token

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

erittäin relevantti termi nykyään, lisäksi Sitra on keksinyt hiljattain suomennoksen termille https://www.is.fi/digitoday/art-2000009426364.html 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

 NFT

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

mm. tieteelliset NFT:tä käsittelevät artikkelit

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [digitaalinen hallintatodistus](http://finto.fi/yse/fi/page/Y511361)

**Comment by ilona-x** [comment]
LCSH:
NFTs (Tokens) http://id.loc.gov/authorities/subjects/sh2021003705

Wikipedia:
https://fi.wikipedia.org/wiki/NFT

**Comment by mariaforsen** [comment]
Sv. icke-fungibla objekt HT non-fungible token, icke-fungibla tokens, digitala äkthetsbevis
https://termipankki.fi/tepa/fi/haku/nft
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/non-funguble-token
https://sv.wikipedia.org/wiki/Non-fungible_token
https://www.vero.fi/sv/privatpersoner/egendom/placeringar/virtuella-valutor/nft-och-ett-konstverk-i-digitalt-format/
https://www.sitra.fi/sv/artiklar/spraket-utvecklas-begrepp-om-den-tredje-utvecklingsfasen-av-internet/
https://eur-lex.europa.eu/legal-content/SV/TXT/HTML/?uri=OJ:L:2022:277:FULL&from=EN
https://it-ord.idg.se/ord/icke-fungibelt-objekt/

**Comment by mirmaid** [comment]
Nöftät 💸

**Comment by LeKorsu** [comment]
Pitäisikö olla monikossa?

**Comment by ilona-x** [comment]
https://www.sitra.fi/tulevaisuussanasto/digitaalinen-hallintatodistus-nft/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään Sitran määritelmä.
