### ISSUE TITLE
lotshemman

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11363]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

luotsitilat

**Ehdotettu termi ruotsiksi**

lotshemman

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Vid kusten beläget krono- eller skattehemman. Lotshemmanet var antingen anslaget till boställe åt lots eller så var ägaren var skyldig att själv utföra lotsning i närbelägna farleder. /FHO

**Perustelut ehdotukselle**

Typ av hemman, behövs vid indexering.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [lantgårdar](http://www.yso.fi/onto/yso/p6821)

**Vastaava käsite muussa sanastossa**

 [Förvaltningshistorisk ordbok](https://fho.sls.fi/uppslagsord/5667/lotshemman/)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Rembas, Porkala – Hangö tur och retur : 300 år med släkten Strömsten på Rembas i Kyrkslätts skärgård / arbetsgrupp: Sigbritt Backman, Sheila Liljeberg-Elgert, Viveca Strömsten.

**Ehdottajan organisaatio**

Åbo Akademi
**Termiehdotus Fintossa:** [lotshemman](http://finto.fi/yse/fi/page/Y511363)

**Comment by mirmaid** [comment]
Ei Melindassa, mutta on toki ihan selkeä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
