### ISSUE TITLE
Perm

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11365]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Perm

**Ehdotettu termi ruotsiksi**

Perm, Ryssland

**Ehdotettu termi englanniksi**

Perm, Russia

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ennestään YSO-paikoissa on Permin Komi, joka on on Permin aluepiiriin kuuluva hallintoalue. Tämä Perm on kaupunki.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Permin Komi](http://www.yso.fi/onto/yso/p109624)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Perm](https://fi.wikipedia.org/wiki/Perm)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4816794?sid=2897955373&imgid=2

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Perm](http://finto.fi/yse/fi/page/Y511365)

**Comment by jtuohini** [comment]
LCNAF/LCSH-vastine: [**Permʹ (Russia)**](http://id.loc.gov/authorities/names/n80106972).

**Comment by nikopartanen** [comment]
Permin kaupunki ei sijaitse Permin Komissa, vaan on [Permin aluepiirin](https://fi.wikipedia.org/wiki/Permin_aluepiiri) hallinnollinen keskus.
