### ISSUE TITLE
merkkihenkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11364]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[merkkihenkilöt](http://www.yso.fi/onto/yso/p20057)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "suurmiehet" ja "merkkinaiset"

**Perustelut ehdotukselle**

Ilmaisuista edellinen esiintyy kirjojen nimissä ym. taajaan, Melindassa yli 1 100 osumaa sanahaulla, uusimmat julkaisut kuluvalta vuodelta (2023). Jälkimmäistä vastaavasti vain kymmenkunta kertaa, mutta viittauksista ei koskaan ole haittaa…

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Suurmiehet-ohjaustermi on aiemmin päätetty poistaa: https://github.com/Finto-ehdotus/YSE/issues/10108. 

Varmaan sekä _merkkimiehet_, että _merkkinaiset_, jos lisätään?

**Comment by YSO-kokous** [comment]
**Päätös**

Jää termiehdotukseksi.

**Comment by jtuohini** [comment]
Olisi kiva kuulla, miksi tämänkaltaisia **ohjaustermejä** ei huolita sanastoon, kun kyseessä on kuitenkin kuvailtavassa aineistossa itsessään esiintyvät käsitteet. Ymmärrän, ettei varsinaisiksi asiasanoiksi oteta "epämääräisiä" käsitteitä, mutta tässä kyse on ihan muusta. YSE:ssä olevasta keskustelusta on vaikea nähdä päätöksen perusteluja.

**Comment by mirmaid** [comment]
^ Merkkinaiset on aika vähän käytetty, lähinnä silloin jos ihan erityisesti on haluttu nostaa henkilöiden sukupuoli keskeiseksi asiaksi. Kokouksessa oltiin sitä mieltä, että kuvailija/hakija keksii merkkihenkilöt-termin myös ilman erillisiä ohjaustermejä miehille ja naisille.

**Comment by jtuohini** [comment]
Näissä KT-ehdotelmissa on usein kyse myös siitä, että jokin ilmaisu esiintyy esimerkiksi aineistoissa: jos ajatellaan automaattista sisällönkuvailua varsinkin suhteessa tekstintunnistukseen, niin silloin kaikki erilaiset käsitteet, jotka viittaavat samaan tarkoitteeseen, olisi hyvä olla mukana viittausmuotoina. "Merkkinainen" (yks. tai mon.) esiintyy Digissä noin 650 kertaa, "merkkimies" noin 31 800, ja jos oletetaan, että sukupuolta ilmaiseva osa automaattisesti tunnistautuu "henkilöksi", niin ihmettelen.
