### ISSUE TITLE
sähkökojeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11379]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähkökojeet](http://www.yso.fi/onto/yso/p19152)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus, yhdistäminen tms. ratkaisu, joka toimii monikielisesti

**Perustelut ehdotukselle**

Sanastossa on myös sähkölaitteet. Sähkäkojeet käytetty 49 kertaa (vaikka on vanha termi, 1986), eikä näytä olevan johdonmukaisesti eri asia kuin sähkölaitteet? Ruotsiksi elutrustningar, elapparater; englanniksi electric apparatus, electrical devices. Googlessakin melko vähän sähkökojeella (lähinnä yritysten nimiä, kuten Tepassakin)
https://www.sanakirja.fi/custom/fi-en-sv/s%C3%A4hk%C3%B6koje
https://www.kielitoimistonsanakirja.fi/#/s%C3%A4hk%C3%B6koje?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Sääli poistaa tällainen sympaattinen vanha termi 🙂. Mutta eiköhän tämä nyt ole kuitenkin KÄ sähkölaitteet.

**Comment by mariaforsen** [comment]
Sv. elapparater, elutrustningar > elapparater HT elektriska apparater, elmateriel, elektriska anordningar, elutrustningar
https://www.sanakirja.fi/custom/fi-en-sv/s%C3%A4hk%C3%B6laite
https://termipankki.fi/tepa/fi/haku/s%C3%A4hk%C3%B6laite
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_7c9549a46655064b18266ec516965464&list_id=1&keyword=s%C3%A4hk%C3%B6laite&word=s%C3%A4hk%C3%B6laite
https://svenska.se/tre/?sok=elapparat&pz=1
https://www.rikstermbanken.se/search?q=elmateriel&s=termer
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_7dca39b0f34056cdfe8029c9e1c4ac21&list_id=1&keyword=laite&word=laite
https://termipankki.fi/tepa/sv/s%C3%B6k/laite
