### ISSUE TITLE
Thelema

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11375]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Thelema

**Ehdotettu termi ruotsiksi**

Thelema

**Ehdotettu termi englanniksi**

Thelema

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Olisi hyvä pystyä hakemaan myös tarkalla uskonnon nimellä 

**Ehdotettu yläkäsite YSOssa (LT)**

 [uskonnolliset liikkeet](http://www.yso.fi/onto/yso/p4851)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.5112704?sid=2899477939

**Ehdottajan organisaatio**

Tampereen kuapunginkirjasto
**Termiehdotus Fintossa:** [Thelema](http://finto.fi/yse/fi/page/Y511375)

**Comment by mirmaid** [comment]
Kerran Melindassa, ei LCSH:ssa, mutta varmaan tämä on ihan selkeä. https://en.wikipedia.org/wiki/Thelema

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _thelema_.
