### ISSUE TITLE
matruusit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11371]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

matruusit

**Ehdotettu termi ruotsiksi**

matroser

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan, yleistermi

**Ehdotettu yläkäsite YSOssa (LT)**

 [merimiehet](http://www.yso.fi/onto/yso/p1684)

**Ehdotetut temaattiset ryhmät**

 [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577), [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [puolimatruusit](http://www.yso.fi/onto/yso/p1683)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Matruusi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Varsinkin historialliset aineistot

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [matruusit](http://finto.fi/yse/fi/page/Y511371)

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

**Comment by LeKorsu** [comment]
Kirjastoboksin ulkopuolelta ajateltuna varmaan hyödyllinen esim. valokuvien asiasanoituksessa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
