### ISSUE TITLE
lunastus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11378]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lunastus](http://www.yso.fi/onto/yso/p7439)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa myös lunastus (uskonto)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Meneekö muuten sekaisin uskonnon kanssa, vaikka päätermiksi vaihtaisi _lunastaminen_? Jos se ei auta, mikähän olisin selkein tarkenne?

**Comment by mariaforsen** [comment]
Pelkästään muodon muuttaminen ei taida auttaa, esim. googlehaku "lunastaminen" + "kristinusko" antaa aika paljon viitteitä. Voisiko tarkenteena olla esim. "oikeudellinen toimenpide"?

**Comment by mirmaid** [comment]
^ Mieluummin ehkä (oikeus), mutta onko se, vai esim. (talous)?

**Comment by AuHo22** [comment]
lunastus (talousoikeus)?

**Comment by fantsby-m** [comment]
Kielitoimiston sanakirjassa on sanassa [lunastus](https://www.kielitoimistonsanakirja.fi/#/lunastus?searchMode=all) esimerkkinä
_Vuokra-alueen lunastus itsenäiseksi tilaksi._ 
Mikä ei liene oikeudellinen toimenpide vaan taloudellinen. Toisaalta toisena esimerkkinä artikkelissa on pakkolunastus, mikä perustuu lakiin eli on varmaankin sekä oikeudellinen ja taloudellinen toimenpide. Onkohan koskaan olut kahta tarkennetta tyyliin _lunastus (oikeus tai talous)_?

**Comment by mirmaid** [comment]
Ja-yhdistelmiä on joitakin, esim. ohjaus (taiteet ja media), mutta se on ehkä vähän luontevampi kuin "oikeus ja talous". Jos ajatellaan, että lunastuksessa on aina talouden alaan kuuluva puoli, niin voisi olla lunastus (talous) KT lunastus (oikeus).

**Comment by ilona-x** [comment]
Itse miellän lunastuksen jollain tapaa lainsäädäntöön perustuvaksi toimenpiteeksi. Eli lunastukselle tulee olla jokin peruste. Sanastossa on myös ostaminen ja hankinta, jotka varmaan voisivat käydä tapauksissa, joissa lunastus (oikeus) ei sovi.

Oliko Melindasta esimerkkejä viitteistä, mihin ei kävisi (oikeus) tarkenne?

Tuo mainittu vuokra-alueen lunastuskin taitaa liittyä oikeuteen tai ainakin tällainen vanha laki löytyy https://fi.wikipedia.org/wiki/Laki_vuokra-alueiden_lunastamisesta

Melindassa näytti olevan viitteitä osakkeiden lunastuksesta, mutta tämäkin talouteen liittyvä asia pohjaa lainsäädäntöön (yhtiöoikeuteen).
https://tilisanomat.fi/nuijan-kopautukset/yhtiooikeus/osakkeen-lunastaminen-ja-lunastushinta-kko-202099

Myös kiinteistöihin/maankäyttöön liittyvässä lunastuksessa mielestäni toimivampi tarkenne olisi (oikeus).
https://www.maanmittauslaitos.fi/kiinteistot/hae-maanmittaustoimitusta/lunastaminen

**Comment by mirmaid** [comment]
^ Sanastossa on myös _lunastusoikeus_, voi ehkä vähän hämätä jos on sen lisäksi _lunastus (oikeus)_.

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**lunastusoikeus**
oik. oikeus hankkia jtak maksamalla sen arvo. 



**lunastus**
lunastaminen.

Pakkolunastus.
Vuokra-alueen lunastus itsenäiseksi tilaksi.

**lunastaa** https://www.kielitoimistonsanakirja.fi/#/lunastaa?searchMode=all
1. hankkia haltuunsa maksamalla t. suorittamalla korvaus, ostaa, maksaa. 



----

Melinda:
lunastus x 528
lunastusoikeus x 109
lunastus & lunastusoikeus x 48

**Comment by ilona-x** [comment]
OIKOssa lunastusoikeus & lunastus, ja siellä [lunastuksen ](https://finto.fi/oiko/fi/page/p1492)yläkäsitteenä on omistuksen siirtäminen. Joten miten olisi lunastus (omistuksen siirtäminen)? 😃

**Comment by mariaforsen** [comment]
Kannatan. Ja molemmat tietty tarvitaan, aivan eri käsitteitä kun ovatkin.

**Comment by mirmaid** [comment]
No entä _lunastus (omistus)_? En hirveästi tykkää näistä YSOn vanhoista hierarkisoivista käsitteistä tarkenteina...

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _lunastus (omistus)_.
