### ISSUE TITLE
alligaattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11370]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[alligaattorit](http://www.yso.fi/onto/yso/p16804)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennys, Alligatoridae? 

**Perustelut ehdotukselle**

Ruotsiksi muutetaan > alligatorer och kajmaner, jos tarkoitus on viitata yllä mainittuun (ks. esim. Wikidata) Entä englanniksi, https://en.wikipedia.org/wiki/Alligatoridae ?

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
LCSH:
Crocodylidae KT Alligatoridae KT  Gavialidae http://id.loc.gov/authorities/subjects/sh85034213
Narrower Terms
    **Alligators KT Alligator (Genus) (YSO:n alligaattorit linkattu tähän)** http://id.loc.gov/authorities/subjects/sh85003688
    Caiman (Genus)
    Caimans
    Crocodiles
    Crocodylus
    Paleosuchus

**Comment by mirmaid** [comment]
![image](https://user-images.githubusercontent.com/10060845/236220395-580820fe-f8a9-407a-889c-bd46738a56a5.png)

**Comment by mirmaid** [comment]
Alligaattorit taitaa olla nyt hierarkiassa väärin suomumatelijoiden alla. Helpointa varmaan olisi tulkita, että alligaattorit viittaa sukuun. Sanastoon voisi myös lisätä kaimaanit - jos käsitellään alligaattorien heimoa, niin silloin käsitellään alligaattoreita ja kaimaaneja. Ja jos joku ei huomaa silloin lisätä kaimaanit-käsitettä kuvailuun tai peräti erhettyy käyttämään alligaattorit-käsitettä, niin ei tästäkään taida ihan hirveää ongelmaa seurata, kun veikkaan että meikäläisissä tietokannoissa ei ihan valtavasti alligaattoritutkimusta löydy.

**Comment by mariaforsen** [comment]
Eli latinaksi Alligator? Tai mahdollisesti Alligatorinae (fi. varsinaiset alligaattorit)?
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/alligator-(2)

**Comment by mirmaid** [comment]
_Varsinaisten alligaattoreiden sukuun (Alligator) kuuluu kaksi nykyään elävää lajia_. https://fi.wikipedia.org/wiki/Alligaattorit

Mutta ei siis mitään "varsinaiset" siihen nimeen, suurin osa aineistoista taitaa olla lasten piirrettyjä kirjoja jostain Anselmi Alligaattorista, tjsp, ja on kyllä melko kyseenalaista, miten varsinaisia ne ovat alligaattoriudessaan 😄

**Comment by mirmaid** [comment]
Ehdotan siis hierarkian tarkistusta ja uutta käsitettä kaimaanit, ei muutosta termimuotoon alligaattorit (ja tulkitaan sen viittaavan sukuun, jonka mukaan kielivastineet).

**Comment by tpalonen** [comment]
Samantyyppinen huomautus tälle kuin kotkille?

**Comment by mariaforsen** [comment]
Sv. kajmaner (lat. Caiman)

https://sv.wikipedia.org/wiki/Kajmaner
https://fi.wikipedia.org/wiki/Kaimaanit
