### ISSUE TITLE
transferenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11373]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[transferenssi](http://www.yso.fi/onto/yso/p16934)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne ainakin englanniksi? 

**Perustelut ehdotukselle**

Käytetty melko paljon myös kielimerkityksessä, liittykö englannin termiin (olisiko hyvä lisätä (psychology) kuten LCSH:ssa)? Tutkitaan ruotsiksi (överföring vs. transferens). 
Väärin nyt esim. Kielellisiä ilmiöitä opiskelijatulkkien saksa-suomi ja suomi-saksa -simultaanitulkkeissa / Johanna Johansson ; The Cambridge handbook of areal linguistics / edited by Raymond Hickey ; Language transfer in the written English of Finnish students / Lea Meriläinen.

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Olisiko transferenssi (psykologia) ja ehkä transferenssi (kielitiede) KÄ interferenssi (kielitiede)?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään sulkutarkenne, toimitaan yllä olevan ehdotuksen mukaan.

**Comment by tpalonen** [comment]
Lisäsin englanniksi ohjaustermit:
language transfer KÄYTÄ linguistic interference
interference (linguistics) KÄYTÄ linguistic interference
