### ISSUE TITLE
mekot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11380]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mekot](http://www.yso.fi/onto/yso/p20766)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus (tai mahdolliesti yhdistäminen) suhteessa leningit-termiin

**Perustelut ehdotukselle**

Todettu YSO-linkityskokouksessa. Klänningar=mekot+leningit
https://www.kielitoimistonsanakirja.fi/#/mekko?searchMode=all 
https://www.kielitoimistonsanakirja.fi/#/leninki?searchMode=all
Toisessa merkityksessä voi olla myös "koltar" ruotsiksi (lähinnä ennen vanhaan lapsilla) 
Vrt. myös eng. 

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/11402

**Comment by mirmaid** [comment]
Mekot käytetty paljon enemmän, joten varmaankin leningit KÄ mekot?

**Comment by mariaforsen** [comment]
Kannatan, mutta pitäisikö vielä lisätä huomautus merkityksestä? Ruotsiksi kun tulee "klänningar" niin sehän ei sovi tähän: "paidan tapainen umpinainen väljä (pikkulapsen) pukine" vaan se olisi "koltar". Onhan se myös käsitteellisesti aika eri asia, ja hakija joka etsii naisten mekkoja tuskin haluaa pikkulasten pukineita tulokseksi.

**Comment by mirmaid** [comment]
Toisaalta aikuisten ja lasten mekkojen erottelu ei mitenkään onnistu, kun molemmat ovat mekkoja (tai leninkejä, jos se olisi päätermi) - ja ovathan ne usein ihan samanlaisiakin. En oikein saa kiinni, mikä tuo "pikkulapsen mekko" on, kun kastemekko nyt on ihan erilainen kuin muut vauvojen mekot, jotka usein muistuttaa aikuisten mekkoja. Ja Kielitoimiston sanakirjassa ei esim. sanota, että kyse olisi jostain entisaikojen vaatekappaleesta. 

Eli onko ongelma se, että klänningar ei pidä sisällään kaikenlaisia mekkoja? Miten esim. https://www2.hm.com/fi_fi/productpage.1062576003.html

**Comment by ilona-x** [comment]
Mekko: suojavaatteesta juhlapuvuksikin / Jukka Korpela
https://jkorpela.fi/sana/mekko.html

--

Kielitoimiston sanakirja:
[kolttu ](https://www.kielitoimistonsanakirja.fi/#/kolttu?searchMode=all)
vars. pikkulapsen puku, pikkutytön mekko.
Vauvan kolttu.
Tytön uusi pyhäkolttu.

**Comment by mirmaid** [comment]
^ Hyvä historiikki. Kolttu tosiaan varmasti on ollut suomenkielinen versio "koltar"-sanasta aikoinaan, mutta nykyään suomeksi lasten mekot eivät enää ole kolttuja (ja myös linkittämäni h&m:n vaate, joka omaan silmääni muistuttaa malliltaan lapsen mekkoa, olisi mekko, ei kolttu - siksi mietin, onko se ruotsiksi jotain muuta kuin klänning).

**Comment by mariaforsen** [comment]
Onhan tässä joo monikielisyysongelma, mutta tämä annettu esimerkki näyttää melkein tunikalta ruotsiksi https://www2.hm.com/fi_fi/productpage.1062576003.html

**Comment by mirmaid** [comment]
Nyt vasta älysin katsoa, miten nuo on ruotsinkielisellä puolella lajiteltu. Eli kaikki ovat klänningar. Voisikohan tuon "koltar" nyt vain unohtaa?

**Comment by YSO-kokous** [comment]
**Päätös**

Yhdistetään.
