### ISSUE TITLE
ilmaradat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11383]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ilmaradat](http://www.yso.fi/onto/yso/p14826)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus termin merkitykseen

**Perustelut ehdotukselle**

Viittaako junaratatyyppiin (ks. https://www.kielitoimistonsanakirja.fi/#/ilmarata?searchMode=all ) vai johonkin ilmassa olevaan rataan (ks. suhteet YSOssa) ? Muunkieliset vastineet sen mukaisiksi (nykyinen sv. luftbana ei ole junaratatyyppi). 
Todettu YSO-linkityskokouksessa. 

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Vrt. todelliset junatyyppiset ilmaradat: kohorata eli monorail (https://www.wikidata.org/wiki/Q187934) ja riippurata (https://www.wikidata.org/wiki/Q339401), joista edellisessä juna tms. kulkee kiskon yläpuolella, jälkimmäisessä taas alapuolella kiskosta riippuen. Teollisuuslaitoksissa kuljetuslaitteina paljonkin näitä. Ja lisäksi ilmaradat, joissa ei ole kiskoja, vaan kaapelit, mutta kumpaa YSO:ssa tosiaan tarkoitetaan, on hieman epäselvää.

**Comment by mirmaid** [comment]
5 viitettä Melindassa.
http://willimiehenjaljilla.blogspot.com/2014/04/kaukas-ilmarata.html (aineisto 1)
https://fi.wikipedia.org/wiki/Tornion_ja_Haaparannan_posti-ilmarata (aineistot 2,3,5?)

Poistetaan käsite. Tarvitaanko ohjaus ilmaradat (köysiradat) KÄ köysiradat?

**Comment by mariaforsen** [comment]
SAOssa on https://id.kb.se/term/sao/H%C3%B6gbanor =ilmaradat (rautatiet), ja ehkä tulevaisuudessa tulee enemmän Suomeenkin? Mutta voihan sen tarvittaessa ottaa uudestaan siinä tapauksessa.
