### ISSUE TITLE
seksityöläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11389]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

seksityöläiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sex workers

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

"Prostituoitu-käsite sisältää kuitenkin halventavan sivumerkityksen eikä se kuvasta henkilön toimijuutta eikä kokemusta riittävästi. Myös Skaffari (2010, 40) näkee prostituoidun käsitteen ongelmallisena, koska se sisältää ajatuksen toimijasta objektina. Wardlow (2004) tuo esille, että seksityöntekijä-käsite ei ole yhtä leimaava kuin prostituoitu-käsite, sillä se ei määrittele toimijan identiteettiä yhtä kokonaisvaltaisesti. Monet seksityöntekijätkään eivät näe itseään prostituoituina (Järvinen 1990, 197; Kontula 2008, 200; Bjønness 2012; Van de Walle ym. 2012), sillä he eivät tunnista itsessään prostituutioon yleisesti liitettyä uhriutumista eikä riskikäyttäytymistä (Kontula 2008, 200). Skaffarin (2010, 40) mukaan oleellista onkin naisten oma käsitys itsestä toimijana. Suomalaiset itsenäisesti toimivat, seksiä myyvät henkilöt käyttävät itsestään pääsääntöisesti mieluummin käsitettä seksityöntekijä (Tuomaala 2013).

Seksityöntekijän käsite voidaan ymmärtää monilla eri tavoilla. Hubbard ja Whowell (2008)
käyttävät seksityöntekijän käsitettä yläkäsitteenä, joka sisältää kaikki kaupallisen seksin toimintamuodot, kuten striptease-tanssijat, pornografiatyöntekijät sekä prostituoidut. Myös Orchardin ym. (2012) mukaan seksityöntekijän käsitettä voidaan käyttää puhuttaessa laajalti erilaisista seksialan muodoista, joissa seksuaalisia palveluita vaihdetaan rahaan, materiaalisiin hyödykkeisiin tai palveluksiin."

https://jyx.jyu.fi/bitstream/handle/123456789/43311/1/URN%3ANBN%3Afi%3Ajyu-201405051613.pdf 

**Ehdotettu yläkäsite YSOssa (LT)**

 [työntekijät](http://www.yso.fi/onto/yso/p1075)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 seksityöntekijät

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Kielitoimiston sanakirja](https://www.kielitoimistonsanakirja.fi/#/seksity%C3%B6l%C3%A4inen), [LCSH](http://id.loc.gov/authorities/subjects/sh2017000417)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

How sex changed the internet and the internet changed sex : an unexpected history / Samantha Cole

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [seksityöläiset](http://finto.fi/yse/fi/page/Y511389)

**Comment by mariaforsen** [comment]
Sv. sexarbetare
https://sv.wikipedia.org/wiki/Sexarbetare
https://svenska.se/tre/?sok=sexarbetare&pz=1

**Comment by vthuhtal** [comment]
Onhan tämä termimuutos 'prostituoidut' termille?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _seksityöntekijät_. Ei korvaa käsitettä _prostituoidut_.
