### ISSUE TITLE
aurinkokunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11388]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aurinkokunnat](http://www.yso.fi/onto/yso/p1325)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yksikköön: aurinkokunta
Samalla termi aurinkokunnat -> planeettakunnat

**Perustelut ehdotukselle**

Aurinkokunta on Aurinkoa kiertävä planeettakunta. 
Ks. esim
https://fi.wikipedia.org/wiki/Aurinkokunta
https://en.wikipedia.org/wiki/Solar_System
https://fi.wikipedia.org/wiki/Planeettakunta
https://en.wikipedia.org/wiki/Planetary_system
https://www.kielitoimistonsanakirja.fi/#/aurinkokunta?searchMode=all

**Ehdottajan organisaatio**

KK/MP

**Comment by mirmaid** [comment]
Näinhän se toki on.

**Comment by mariaforsen** [comment]
Ruotsiksi käytetään samaa termiä myös muista aurinkokunnista kuin meidän, vrt. https://sv.wikipedia.org/wiki/Solsystem ja https://sv.wikipedia.org/wiki/Solsystemet eli siinä mielessä nykyinen muoto on ollut ihan hyvä, mutta kaksi eri käsitettä voisi tietty myös olla.

https://en.wikipedia.org/wiki/Solar_System_(disambiguation)

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/T%C3%A4htitiede:aurinkokunta

https://tieteentermipankki.fi/wiki/T%C3%A4htitiede:muut_aurinkokunnat

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Jaetaan käsitteisiin _aurinkokunta_ ja _planeettakunnat_. Jälkimmäiselle RT _eksoplaneetat_.

**Comment by mariaforsen** [comment]
Sv. -solsystemet HT solsystem 
-planetsystem
