### ISSUE TITLE
poistumistiet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11382]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[poistumistiet](http://www.yso.fi/onto/yso/p22094)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistumisreitit? Suhde vara/hätäuloskäyntiin?

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/poistumisreitti
Eng. emergency exits - vrt. Tepa ja fi. https://www.sanakirja.fi/custom/fi-en-sv/emergency%20exit 
Olisi lisättäviä ohjaustermejä, varsinkin jos pidetään samana käsitteenä myös vara/hätäuloskäynnit jne.? Mikä olisi paras päätermi (vrt. esim. Palo- ja pelastussanasto).
Todettu YSO-linkityskokouksessa.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
TEPA
fi        poistumisreitti
ei: poistumistie
sv       utrymningsväg
en      escape route; means of egress
de      Fluchtweg m; Rettungsweg m
ru       путь m эвакуации
määritelmä
reitti, joka koostuu kulkureitistä ja uloskäytävästä tai varatiestä
huomautus
Poistumisreittejä suunniteltaessa on otettava huomioon erityisesti tilassa olevien henkilöiden edellytykset ja kyky poistua hätätilanteessa.
Käsitekaavio: Poistumisalue ja -reitit.
Lähde: Palo- ja pelastussanasto (TSK 33, 2006)

Mm. TEPAssa eng. termi on escape routes, pitäisikö se mahdollisesti olla YSOssakin? Vrt. https://termipankki.fi/tepa/fi/haku/emergency%20exit

https://pelastustoimi.fi/en/home-everyday-life/accident-prevention/evacuation-safety

Ks. myös https://termipankki.fi/tepa/fi/haku/emergency%20exit -pitäisikö osa näistä lisätä ohjaustermeiksi, esim. varauloskäynnit, hätäreitit? Vai olisiko hätäuloskäynti KT varauloskäynnit oikeastaan erillinen käsite (ei käsitteellisesti ole sama asia kuin poistumisreitti)? 

https://fi.wikipedia.org/wiki/H%C3%A4t%C3%A4ulosk%C3%A4ynti

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _poistumisreitit_. Ohjaustermeiksi _varauloskäynnit_, _hätäuloskäynnit_, _häräreitit_.
