### ISSUE TITLE
Cane corso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11387]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Cane corso

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Cane_corso

**Ehdotettu yläkäsite YSOssa (LT)**

 [koira](http://www.yso.fi/onto/yso/p5319)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://issuu.com/granmarina

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [Cane corso](http://finto.fi/yse/fi/page/Y511387)

**Comment by mariaforsen** [comment]
Sv. cane corso /ne
https://www.skk.se/sv/hundraser/cane-corso/
