### ISSUE TITLE
uudelleenkäyttö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11386]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[uudelleenkäyttö](http://www.yso.fi/onto/yso/p13211)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uudelleenkäyttö on rinnakkainen käsite kierrätykselle. Molemmat kuuluvat hyötykäytön alle. Uudelleenkäytössä ei käsitellä jätteitä, vaan tuotteita ennen kuin ne ovat muuttuneet jätteiksi (ns. end-of-life -määrittely). Kierrätys kuuluu edelleen hierarkiassa jätteiden hyötykäytön alle.

**Perustelut ehdotukselle**

Uudelleenkäyttö on tavaran tai valmistusosan käyttöä sellaisenaan tai vähäisen korjauksen jälkeen (esim. tuolien siirtäminen koulusta päiväkotiin, kirpputorit, kasvihuoneen tekeminen puretuista ikkunoista jne.). 

Kierrätys tarkoittaa tavaran materiaalien erottelua ja muokkausta (esim. sulattaen) ja näiden materiaalien käyttöä uusien tuotteiden valmistuksessa.

**Ehdottajan organisaatio**

Ympäristökoulu Polku

**Comment by mariaforsen** [comment]
Näin myös ruotsiksi, kannatan yläkäsitteen vaihtamista. Voi tosin olla ongelmallista laittaa hyötyäyttö yläkäsitteeksi, koska YSOssa se ei ole määritelty pelkästään siihen merkitykseen, ks. MOT sanakirjat ja esim. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4baf47b56ef932216e5355215b2d97e5&list_id=1&keyword=hy%C3%B6tyk%C3%A4ytt%C3%B6&word=hy%C3%B6tyk%C3%A4ytt%C3%B6 

Huom. esim. bookcrossing on nyt virheellisesti RT kierrätys

**Comment by mirmaid** [comment]
Todettiin, että yleiskielessä kierrätys nähdään laajempana kuin vain jätteen käsittelyyn liittyvänä toimintana. Esim. kierrätyskeskukset eivät kierrätä jätettä, ja vaatteiden kierrätyksellä voidaan tarkoittaa paitsi tekstiilijätteen kierrätystä, myös käyttökelpoisten vaatteiden lahjoittamista tai myymistä edelleen.
