### ISSUE TITLE
Opiskeluhuolto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11385]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Opiskeluhuolto

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Asiakas kertoi, että opiskeluhuolto on nykyinen lainsäädännön ja opetussuunnitelmien termi (aiemmin oppilashuolto tai opiskelijahuolto kouluasteesta riippuen).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Asiakas etsi asiasanoja väitöskirjaansa. 

**Ehdottajan organisaatio**

Oulun yliopiston kirjasto
**Termiehdotus Fintossa:** [Opiskeluhuolto](http://finto.fi/yse/fi/page/Y511385)

**Comment by mariaforsen** [comment]
OKSA (TEPAssa):
fi        oppilashuolto (esiopetus, perusopetus); opiskelijahuolto (lukiokoulutus, ammatillinen koulutus); **opiskeluhuolto (yhteinen nimitys oppilashuollolle ja opiskelijahuollolle)**
sv       elevvård (esiopetus, perusopetus); studerandevård (lukiokoulutus, ammatillinen koulutus); elevhälsa (opiskeluhuolto)
en      student welfare (oppilashuolto, opiskelijahuolto ja niiden yhdessä muodostama opiskeluhuolto); ~ student welfare body (opiskeluhuoltoryhmä)
not: pupil and student welfare (opiskeluhuolto); student care services ...
oppilashuolto, opiskelijahuolto, opiskeluhuolto: Oppilas- ja opiskelijahuollosta on säädetty laissa 1287/2013. **Laissa** käytetään termiä opiskeluhuolto, jolla viitataan sekä perusopetuslain (628/1998) mukaiseen oppilashuoltoon että lukiolain (714/2018) ja ammatillisesta koulutuksesta annetun lain (531/2017) mukaiseen opiskelijahuoltoon." 

Eli alan sanastossa ei ainakaan suljeta pois mahdollisuutta käyttää myös tarkempia termejä. 

https://www.kielitoimistonsanakirja.fi/#/opiskeluhuolto?searchMode=all

**Comment by mirmaid** [comment]
Otetaanko tämä lisäksi, vai lisätäänkö ohjaustermiksi oppilas- ja opiskelijahuollolle?

**Comment by LeKorsu** [comment]
Voisiko noihin oppilas- ja opiskelijahuoltoihin lisätä nuo koulutusasteet selityksiksi / huomautuksiksi? 
Käännyn kannattamaan, että otetaan lisäksi opiskeluhuolto näiden yläkäsitteeksi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _opiskeluhuolto_ ohjaustermiksi _oppilas-_ ja _opiskelijahuollolle_.
