### ISSUE TITLE
puhvelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11381]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[puhvelit](http://www.yso.fi/onto/yso/p15172)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennys mihin (lat.) tällä termillä viitataan (ja muunkieliset vastineet)

**Perustelut ehdotukselle**

Todettu YSO-linkityskokouksessa.
https://www.kielitoimistonsanakirja.fi/#/puhveli?searchMode=all
https://fi.wikipedia.org/wiki/Puhveli

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
26 kertaa Melindassa: vesipuhveli, kafferipuhveli/afrikanpuhveli, biisoni tai yleisemmin Bubalus ja Syncerus -suvut. Yhteisesti voisi olla myös tämä https://en.wikipedia.org/wiki/Bubalina. 

Voisi lisätä puhveli (biisoni) KÄ biisoni.

**Comment by mirmaid** [comment]
Jätetäänkö tuossa yleismerkityksessä (Bubalina), vai poistetaanko ja lisätään afrikanpuhveli ja vesipuhveli?

**Comment by mariaforsen** [comment]
Bubalina=sv. Bubalina eli ei kovin hyvä termi. Kannatan tarkempia termejä, afrikanpuhveli ja vesipuhveli olisi hyvä olla sanastossa, Melindassa on aineistoa molemmista.

**Comment by jarmosaarikko** [comment]
Agrovocissa
* ruminants
   * [African buffaloes](https://agrovoc.fao.org/browse/agrovoc/en/page/c_167) 
   * [bison](https://agrovoc.fao.org/browse/agrovoc/en/page/c_939) UF American buffaloes
   * [domestic buffaloes](https://agrovoc.fao.org/browse/agrovoc/en/page/c_25410) 
      * [water buffaloes](https://agrovoc.fao.org/browse/agrovoc/en/page/c_8313)
* breeds (animals)
   * [buffalo breeds](https://agrovoc.fao.org/browse/agrovoc/en/page/c_f4d3d459) 
      * [Anatolian Water Buffalo](https://agrovoc.fao.org/browse/agrovoc/en/page/c_96005219)

Yksikään noista ei tällä hetkellä vastaan YSOn käsitettä. 
Onko tarveen erotella 
* villit puhvelit (lajit) ml. afrikkalainen, aasialainen ja amerikkalainen 
* kotielämet (ja "puhvelirodut") ml. "vesipuhveli"

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _afrikanpuhveli_ ja _vesipuhveli_, toimitaan Marian yllä esittämän ehdotuksen mukaisesti.

**Comment by mariaforsen** [comment]
Sv. -afrikansk buffel HT kafferbuffel 
https://sv.wikipedia.org/wiki/Afrikansk_buffel
-vattenbuffel HT asiatisk buffel, indisk buffel 
https://sv.wikipedia.org/wiki/Vattenbuffel
