### ISSUE TITLE
optiset pinsetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11393]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

optiset pinsetit

**Ehdotettu termi ruotsiksi**

optiska pincetter

**Ehdotettu termi englanniksi**

optical tweezers

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 8

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH: optical tweezers](http://id.loc.gov/authorities/subjects/sh2009008496), [FinMeSH: optiset pinsetit](http://www.yso.fi/onto/mesh/D052898), [Wikipedia](https://en.wikipedia.org/wiki/Optical_tweezers)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Red blood cells and novel nanomaterials http://urn.fi/urn:isbn:9789526234229

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [optiset pinsetit](http://finto.fi/yse/fi/page/Y511393)

**Comment by mariaforsen** [comment]
Sv. optiska pincetter /ne HT laserpincetter
https://mesh.kib.ki.se/term/D052898/optical-tweezers
