### ISSUE TITLE
globaali etelä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11397]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

globaali etelä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

global south

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kehitysmaat-termiä ei oikein voi enää käyttää, kun se on kolonialistinen ja asenteellinen ja viittaa eurosentriseen käsitykseen kehityksestä, jossa länsimaat ovat jotenkin "kehityksessä edellä" ja globaalin etelän maat "kehityksessä jäljessä". Ehdotan sitä ja kehittyneitä maita poistettavaksi sanastosta.

Termit globaali etelä ja pohjoinen eivät ehkä nekään ole täydellisiä ja yksiselitteisiä, mutta niitä globaalin etelän ihmiset itse käyttävät, joten ovat parempia ja neutraalimpia. Ainakaan ne eivät ole kolonialistisia ja rasistisia.

https://fingo.fi/ajankohtaista/yleinen-fi/kehitysmaat-kehittyvat-maat-kolmas-maailma-globaali-etela-miten-puhua-maailman-enemmistosta/ 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Globaali_pohjoinen_ja_globaali_etel%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Strange and difficult times : notes on a global pandemic / Nanjala Nyabola

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [globaali etelä](http://finto.fi/yse/fi/page/Y511397)

**Comment by ilona-x** [comment]
Aiempi ehdotus samasta termistä (käsittely kesken): https://github.com/Finto-ehdotus/YSE/issues/11102

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään seuraavaan kokoukseen.

**Comment by ilona-x** [comment]
tästä siis toinen issue, mikä on ongelmakokouksen listalla https://github.com/Finto-ehdotus/YSE/issues/11102
