### ISSUE TITLE
Vepsä, Kärsälä, Kopola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11395]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Vepsä, Kärsälä, Kopola

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Karjalankannaksen pitäjä Rautu oli laaja alue. Sieltä Suomeen muuttaneiden jälkeläiset tekevät kylistä paikallis- ja sukukirjoja ainakin jonkin verran. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [Rautu](http://www.yso.fi/onto/yso/p107726)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Vepsa

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Vauhkonen, Markku: Rautu valokuvina ja tarinoina 
2. Vepsa
3. Kärsälä ja Kopola

**Ehdottajan organisaatio**

Pieksämäen kaupunginkirjasto (Lumme-kirjasto)
**Termiehdotus Fintossa:** [Vepsä, Kärsälä, Kopola](http://finto.fi/yse/fi/page/Y511395)

**Comment by mariaforsen** [comment]
Sv. 
Kärsälä (Rautus) ? https://finna.fi/Record/narc.VAKKA-312109.KA_VAKKA-1214945.KA/HierarchyTree?recordID=narc.VAKKA-312109.KA_VAKKA-1214945.KA
Kopola (Rautus) ? https://katiha.kansallisarkisto.fi/hakutulos.php?vapaahaku=kopola&maxHits=100&maxFacets=20&jarjestys=&jarjestyssuunta=1&fasettihaku=1&asuinpaikka_p=Kopola&s=1&kieli=sv
Vepsä (Rautus) ? HT Vepsa (Rautus), Wepsä (Rautus)
