### ISSUE TITLE
haavoittuvat väestöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11396]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

haavoittuvat väestöt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

vulnerable populations

**Tarkoitusta täsmentävä selite**

Minors, unaccompanied minors, disabled people, elderly people, pregnant women, single parents with minor children, victims of trafficking in human beings, persons with serious illnesses, persons with mental disorders and persons who have been subjected to torture, rape or other serious forms of psychological, physical or sexual violence, such as victims of female genital mutilation.
https://home-affairs.ec.europa.eu/networks/european-migration-network-emn/emn-asylum-and-migration-glossary/glossary/vulnerable-person_en

**Perustelut ehdotukselle**

Puuttuva YSO-termi, tarvittu sisällönkuvailussa. Käsite, jolla paljon käyttöä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [väestöryhmään liittyvä rooli](http://www.yso.fi/onto/yso/p487)

**Ehdotetut temaattiset ryhmät**

 [61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570)

**Vaihtoehtoiset termit**

 vulnerable people

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH / FinMeSH](http://haavoittuvat väestöt ), [MeSH / FinMeSH](https://finto.fi/mesh/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmesh%2FD035862)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018711600

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [haavoittuvat väestöt](http://finto.fi/yse/fi/page/Y511396)

**Comment by ilona-x** [comment]
onkohan tämä 'haavoittuvat väestöt' -termi sama kuin Tepasta löytyvä haavoittuvassa asemassa oleva väestöryhmä, 🤔 https://termipankki.fi/tepa/fi/haku/haavoittuvassa%20asemassa%20oleva%20v%C3%A4est%C3%B6ryhm%C3%A4

**Comment by mariaforsen** [comment]
Sv. utsatta befolkningsgrupper HT sårbara befolkningsgrupper, sårbar befolkning, sårbara grupper, utsatta personer, utsatt ställning, grupper i utsatt ställning
https://www.sanakirja.fi/custom/fi-en-sv/haavoittuva%20v%C3%A4est%C3%B6ryhm%C3%A4
https://www.sanakirja.fi/custom/fi-en-sv/utsatt%20befolkningsgrupp
https://mesh.kib.ki.se/term/D035862/vulnerable-populations
https://thl.fi/sv/web/thlfi-sv/forskning-och-utveckling/undersokningar-och-projekt/en-barndom-utan-vald-atgardsplan/grupper-i-utsatt-stallning
https://home-affairs.ec.europa.eu/networks/european-migration-network-emn/emn-asylum-and-migration-glossary/glossary/vulnerable-person_sv

**Comment by mirmaid** [comment]
Täällä myös: https://thl.fi/fi/web/hyvinvointi-ja-terveyserot/eriarvoisuus/keskeisia-kasitteita

Varmaan aika lailla kontekstista riippuu, mitkä ryhmät ovat tällaisia - jos vertaa esim. ehdotuksen listaa tähän THL:n sanastoon.

_Väestöryhmät_ tuntuisi selkeämmältä kuin _väestöt_. Toistaiseksi kuitenkin Melindassa vain 5 viitettä, joissa FinMeSH-terminä. YSOssa on _haavoittuvuus_, jota on käytetty erilaisiin haavoittuviin ryhmiin liittyen. 

https://melinda.kansalliskirjasto.fi/byid/018647222
https://melinda.kansalliskirjasto.fi/byid/018711600
https://melinda.kansalliskirjasto.fi/byid/018330790
https://melinda.kansalliskirjasto.fi/byid/018682381

**Comment by fantsby-m** [comment]
_Haavoittuvat väestöryhmät_ olisi parempi.

**Comment by YSO-kokous** [comment]
**Päätös**

Keskusteluun tuotiin:

_haavoittuvat ryhmät_
_haavoittuvat väestöryhmät_
_haavoittuvassa asemassa olevat väestöryhmät_
_haavoittuvassa asemassa olevat ryhmät_
_haavoittuvassa asemassa olevat_ 
_haavoittuva asema_ 

Näistä _haavoittuvat väestöryhmät_ päätettiin parhaaksi päätermiksi, muut ohjaustermiksi.
