### ISSUE TITLE
tuottajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11394]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tuottajat](http://www.yso.fi/onto/yso/p8823)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään ryhmä 80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta.
Toinen vaihtoehto: uusi asiasana tuottajat (taiteet ja media), jolloin pitää miettiä pitäisikö elokuvatuottajat yhdistää tähän

**Perustelut ehdotukselle**

Tarve media-alan tuottaja -käsitteelle. Tähän asti käytetty tuota tuottajat (kelpaa jatkossakin), mutta vasta nyt huomasin, että käsitteestä puuttuu joukkoviestinnän ryhmä.

**Ehdottajan organisaatio**

Yle Arkisto

**Comment by mirmaid** [comment]
Melindassa ainakin uudemmissa viitteissä eniten musiikkialaa, lisäksi elokuva/tv-maailmaa (tuottajat/elokuvatuottajat-valinnassa saattaa olla hajontaa). Joukossa siellä täällä mun tyyppistä myös (maataloustuottajat, palveluntuottajat). Mikä olisi tavoitetila? Käytetty vähän vajaat 2000 kertaa.

**Comment by mariaforsen** [comment]
Sv. producent toimii samalla tavalla kuin suomeksi: https://www.kielitoimistonsanakirja.fi/#/tuottaja?searchMode=all paitsi _ei_ 3. merkityksessä.

**Comment by mirmaid** [comment]
^ 3. merkityksessä olisi kyllä ihan tarpeeton sisällönkuvailussa.

**Comment by tpalonen** [comment]
Musiikkialalla tämä on vähän hankala termi sikäli, että sanaa käytetään kahdesta hyvin erilaisesta roolista. Nämä molemmat ovat erikseen YSOssa käsitteinä: _äänitetuottajat_ ja _kulttuurituottajat_ (lisäksi myös _tapahtumatuotanto_). Melindasta näkee, että käsitettä tuottajat on käytetty musiikin yhteydessä molemmissa merkityksissä. Harmillinen tilanne sikäli, kun kuitenkin tarkempia termejäkin olisi tarjolla. 

Ehkä jokin huomautus voisi olla paikallaan tuottajat-käsitteelle?

Jos otetaan tuottajat (taiteet ja media) -tyyppinen käsite niin pitäisi miettiä miten äänitetuottajat ja kulttuurituottajat suhteutuvat siihen. Ja tarvitaanko sellaisessa tilanteessa tätä yleistä tuottajat-käsitettä enää ollenkaan?

**Comment by YSO-kokous** [comment]
**Päätös**

Seuraavaan kokoukseen mennessä Tuomas Palonen valmistelee ehdotuksen, jota Leena Korsumäki kommentoi.

**Comment by tpalonen** [comment]
Alan kallistua siihen, että tämä yleinen _tuottajat_ olisi hyvä poistaa sanastosta ja korvata kuvailuissa tarkemmilla käsitteillä. Sanastoon voi lisäksi ottaa tarpeen mukaan spesifimpiä tuottajakäsitteitä. Ei ole kovin kestävää, että sanastossa on näitä spesifimpiä käsitteitä ja sitten tämä yleinen tuottajat niin että yleiskäsitettä kuitenkin käytetään näiden spesifimpien rinnalla samassa merkityksessä. Tiedonhakijan kannalta olisi myös järkevää, että hän ei saisi tuloksiksi maataloustuottajia jos on kiinnostunut äänitetuottajista. Uskon että ongelma säilyy niin kauan kuin yleinen tuottajat-käsite on sanastossa. En myöskään usko, että sitä pystyy mitenkään järkevästi ja ihmisystävällisesti rajaamaan millään keinolla: "kaikki ne tuottajat jotka eivät ole äänitetuottajia, tapahtumatuottajia, palveluntuottajia jne". Esimerkiksi LCSH:ssa näitä erikoisempia tuottajakäsitteitä on iso liuta, mutta ei lainkaan tällaista yleistä tuottajat-käsitettä. 

Ehdotetussa _tuottajat (taiteet ja media)_ -käsitteessä on se ongelma, että se ei noin muotoiltuna rajaa pois äänitetuottajia tai kulttuurituottajia. Ehkä _tuottajat (radio ja televisio)_ voisi olla kaikkein selkein? Sanastoylläpidon, kuvailun ja tiedonhaunkin näkökulmasta näkisin, että on parempi pitää erillään elokuvatuottajat radio- ja tv-tuottajista. Olisi vaikea rajata käsitettä ja päätermiä niin että se a) sisältäisi sekä radion, tv:n että elokuvat ja samalla b) ei sisältäisi äänitetuottajia ja kulttuurituottajia. Tässä esimerkkejä:
- _tuottajat (taiteet ja media)_ -termi ei tosiaan rajaa pois äänitetuottajia tai kulttuurituottajia
- _tuottajat (audiovisuaalinen media)_ ei sekään rajaa pois äänitetuottajia
- _tuottajat (media)_ - jos elokuvatuottajat on erikseen niin meneekö sekaisin sen kanssa?

EHDOTUS:
- poistetaan _tuottajat_
- otetaan sanastoon _tuottajat (radio ja televisio)_
- lisätään _tuottajat (äänitetuotanto)_ -tyyppisiä ohjaustermejä käsitteille

**Comment by LeKorsu** [comment]
Yleisen tuottajat-käsitteen poistaminen ja korvaaminen tarkemmilla saa kannatukseni. 
Mutta radio ja televisio tarkenteena on liian spesifi. Myös lehdistöllä on nykyään tuottajia ammattinimekkeinä. Siksi kalastelin sinne tarkenteeksi yleisempää media-tarkennetta. Ja toisaalta "radio ja televisio" rajaa kirjaimellisesti ulkopuolelle myös suoratoistopalveluissa näkyvien ohjelmien tuottajat, kun tarkkoja ollaan. 

Kävisikö pelkästään tuottajat (media), tai tuottajat (joukkoviestimet)?

**Comment by mariaforsen** [comment]
Tarvitaan varmaan yleismerkityksen kohdalla sitten ohjauksia, ja tarvitaanko vielä uusia termejäkin, esim. alkutuottajat?
https://www.kielitoimistonsanakirja.fi/#/tuottaja?searchMode=all
https://termipankki.fi/tepa/fi/haku/tuottaja
https://finto.fi/koko/fi/page/p60710

**Comment by tpalonen** [comment]
Joo, tuottajat-alkuisia ohjaustermejä varmasti kaivattaisiin, mikäli yleisestä tuottajat-käsitteestä luovuttaisiin. Tutkin Melindasta ensimmäiset 150 kuvailtua kohdetta. Tuottajat-käsitettä oli käytetty erityisesti äänitetuottajista, mutta myös tapahtumatuottajista, elokuvatuottajista ja palveluntuottajista. Ja niiden lisäksi ainakin näissä yhteyksissä:

_elintarvikkeet, maataloustuotteet, ruoka, raaka-aineet (melko paljon esim. viinintuotannon yhteydessä)_

Muuntogeenisen ruoan etiikka / toimittaneet Helena Siipi ja Marko Ahteensuu.
https://melinda.kansalliskirjasto.fi/byid/018670189
Perceptions and Experiences of Sustainability among Producers in the REKO Alternative Food Network in Finland.
https://melinda.kansalliskirjasto.fi/byid/017361677
Food studies : a hands-on guide / Willa Zhen.
https://melinda.kansalliskirjasto.fi/byid/016603440
Château vadå : det okända fusket med ditt vin / Mats-Eric Nilsson.
https://melinda.kansalliskirjasto.fi/byid/016756307

_hankkeet_

Avaimia hanketuottajuuteen : ketterää kehittämistä ja luovia ratkaisuja / Katri Halonen (toim.).
https://melinda.kansalliskirjasto.fi/byid/018101648

_kulutushyödykkeet_

Extended producer responsibility solution of plastic packaging in the EU / Kevin Kainulainen.
https://melinda.kansalliskirjasto.fi/byid/018039610

_luonnonvarat, alkutuotanto, raaka-aineet, teollisuustuotanto, energiatuotanto_

The political economy of international commodity cartels : an economic history of the European timber trade in the 1930s / Elina Kuorelahti.
https://melinda.kansalliskirjasto.fi/byid/018647842
Dyadic study on perceived performance implications of relationship quality in international B2B context / Ksenia Plyusnina.
https://melinda.kansalliskirjasto.fi/byid/011555050
Bioenergian tuottajat 2015 = Biopower and heat producers 2015
https://melinda.kansalliskirjasto.fi/byid/009781871

_teatteri_

Introduction to production : creating theatre onstage, backstage, & offstage / Robert I. Sutherland-Cohen
https://melinda.kansalliskirjasto.fi/byid/012056227
Jatkuva närästys vei Radioteatterin johtoon / Paula Immonen.
https://melinda.kansalliskirjasto.fi/byid/013156699

**Comment by tpalonen** [comment]
Mietin miten edellä olevia voisi kuvailussa ehkä ratkaista:

_elintarvikkeet, maataloustuotteet, ruoka, raaka-aineet_

tuottajat-käsitteen tilalle kuvailussa maatalousyrittäjät tai soveltuva -tuotanto-loppuinen käsite (esim. elintarviketuotanto, viininviljely)

_hankkeet_

tuottajat-käsitteen tilalle esim. projektijohtaminen, projektinhallinta tai projektipäälliköt

_kulutushyödykkeet_

tuottajat-käsitteen tilalle esim. valmistajat

_luonnonvarat, alkutuotanto, raaka-aineet, teollisuustuotanto, energiatuotanto_

tuottajat-käsitteen tilalle soveltuva -tuotanto-loppuinen tai -teollisuus-loppuinen käsite (esim. alkutuotanto, energiatuotanto, energiateollisuus)
TAI Marian ehdottama uusi käsite _alkutuottajat_

_teatteri_

Tämä ehkä vähän kinkkinen ja voisi hieman tutkia, mutta tuottajat-käsitteen tilalla voisi olla kulttuurituottajat tai kulttuurituotanto
TAI uusi käsite teatterituottajat

**Comment by tpalonen** [comment]
PLUS:
lisäisin sanastoon joka tapauksessa tällaisen ohjaustermin

tapahtumatuottajat KÄYTÄ kulttuurituottajat

(nämä ovat melko lähellä toisiaan ja tuskin tarvitaan sanastossa erikseen)

**Comment by fantsby-m** [comment]
> Tiedonhakijan kannalta olisi myös järkevää, että hän ei saisi tuloksiksi maataloustuottajia jos on kiinnostunut äänitetuottajista

Tämä on totta, toisaalta tiedohakija tuskin hakisi pelkästään hakusanalla _tuottajat_, vaan esim. yhdistelmillä _tuottajat_ AND _äänitteet_ tai _tuottajat_ AND _maataloustuotteet_ (jne.).

Termi on käytössä harmittavan monella eri alalla, mutta jos se jätetään pois joudutaan potentiaalisesti ottamaan valtava määrä joko tarkempia _tuottaja_-loppuisia termejä tai _tuottaja (ala)_ -tyyppisiä ohjaustermejä, mikä sekään ei ole tiedonhakijan kannalta kovin kätevää.

**Comment by mirmaid** [comment]
Maataloustuottajat ohjaa nyt siis käyttämään maatalousyrittäjät. Tuottajat on kuitenkin varmaan tuntunut hyvältä täydennykseltä silloin, jos näkökulma on tuotannossa, eikä selkeästi yritystoiminnassa (tai esim. jonkinlaisessa tuottaja-ostaja-tarkastelussa).

_Alkutuottajat_ olisi suurelta osin päällekkäinen tämän kanssa.

**Comment by mirmaid** [comment]
Voisi ainakin lisätä Tuomaksen ehdottaman tuottajat (äänitetuotanto) KÄ äänitetuottajat (joka siis on jo sanastossa). Viitejoukko selkeytyisi ja pienenisi kyllä jonkun verran, jos tuon korjauksen saisi tehtyä, mutta näin suureen massaan se vie paljon aikaa. Vähän pelkään minäkin, että lopuksi jää kuitenkin satoja viitteitä, joissa tuottajat-käsitteelle ei ole poiston jälkeen sopivaa korvaajaa...

**Comment by MUUSA-kokous** [comment]
Kannatetaan edellistä kommenttia.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Lisätään ohjaustermi tuottajat (äänitetuotanto) KÄYTÄ äänitetuottajat
Korjataan Melinda-kuvailua.
