### ISSUE TITLE
seksityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11390]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

seksityö

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sex work

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Prostituutio-sanalla on halventava sävy, seksityö on ilmaisuna neutraali.

"Seksityö-termi voidaan nähdä kulttuurisesti neutraalimpana ilmaisuna kuin prostituutio."
https://jyx.jyu.fi/bitstream/handle/123456789/43311/1/URN%3ANBN%3Afi%3Ajyu-201405051613.pdf 

Seksityö voi olla myös merkitykseltään laajempi kuin prostituutio ja sisältää prostituution lisäsi sylitanssin, stripteasen ja web cam -työn. https://id.loc.gov/authorities/subjects/sh2017000417.html 

**Ehdotettu yläkäsite YSOssa (LT)**

 [työ](http://www.yso.fi/onto/yso/p1810)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [seksiala](http://www.yso.fi/onto/yso/p7175)

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh2022006936.html), [Kielitoimiston sanakirja](https://www.kielitoimistonsanakirja.fi/#/seksity%C3%B6)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

How sex changed the internet and the internet changed sex : an unexpected history / Samantha Cole

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [seksityö](http://finto.fi/yse/fi/page/Y511390)

**Comment by mariaforsen** [comment]
Sv. sexarbete HT sex mot ersättning
https://www.rfsu.se/vad-vi-gor/i-sverige/fragor-vi-jobbar-med/sex-mot-ersattning/
"RFSU undviker begrepp som prostitution, prostituerad, sexarbete och sexarbetare eftersom de bara delvis beskriver hela fenomenet och kan upplevas som stigmatiserande."
https://sv.wikipedia.org/wiki/Sexarbete

**Comment by mirmaid** [comment]
LCSH:ssakin näyttää olevan kaikki kolme, ja myös seksityöläiset. Tiedä sitten, miten johdonmukaiseksi käyttö muodostuu näiden vaihtoehtojen kesken 🤔

**Comment by vthuhtal** [comment]
Onhan tämä termimuutos 'prostituutio' termille?

**Comment by mirmaid** [comment]
^ LCSH:ssa on tosiaan molemmat. En ehkä kovin helposti lähtisi vaihtamaan prostituutio-käsitettä seksityön ohjaustermiksi, tuntuisi jo liian neutraalilta moneen aineistoon 🤔

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään käsite _seksityö_. Ei korvaa käsitettä _prostituutio_.
