### ISSUE TITLE
apokryfit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11391]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[apokryfit](http://www.yso.fi/onto/yso/p7204)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mitä apokryfit tarkoittaa ysossa?
Mikä on sen suhde teokseen Raamattu. Apokryfit?

**Perustelut ehdotukselle**

Termiä on käytetty sekä Raamattuun kuuluville apokryfisille teksteille että Raamattuun kuulumattomille teksteille.

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
Wikipedian mukaan:

https://fi.wikipedia.org/wiki/Apokryfiset_kirjat

Eri aikoina ja eri kirkkokunnissa on siis eri tavoin suhtauduttu apokryfikirjoihin ja niitä kelpuutettu "virallisiksi" teksteiksi. 

Prefiksi "apo" tullee siitä, että ovat olleet maailmalta kätkettyjä/piilossa, kuten κρύβω από τον κόσμο.

Lieneekö tarvetta tarkentaa/jakaa ko. käsitettä ja termiä?

**Comment by mirmaid** [comment]
YSOn käsitettä voi käyttää kaikista apokryfisista teksteistä, kirkkokunnasta riippumatta. Teos _Raamattu. Apokryfit_ on suppeampi: Kreikkalainen Esran kirja, Esran ilmestys, Tobitin kirja, Juditin kirja, Kreikkalainen Esterin kirja, Viisauden kirja, Sirakin kirja, Barukin kirja, Susanna, Asarjan rukous ja Kolmen miehen kiitoslaulu, Danielin maineteot ja koettelemukset, Manassen rukous, Ensimmäinen makkabilaiskirja, Toinen makkabilaiskirja (= katolisen kirkon hyväksymät deuterokanoniset kirjat)

**Comment by mirmaid** [comment]
Halutaanko tähän määritelmä tai käyttöhuomautus?

**Comment by mariaforsen** [comment]
Siinä tapauksessa ehkä käyttöhuomautuksena yllä mainittu huomautus siitä että voi käyttää kaikista apokryfisista teksteistä kirkkokunnasta riippumatta?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään käyttöhuomautus.
