### ISSUE TITLE
tunikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11402]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tunikat](http://www.yso.fi/onto/yso/p20768)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään määritelmä ja tarpeen tullen RT-suhde asiasanaan "mekot"

**Perustelut ehdotukselle**

Tunikalla kaksi hieman eroavaa merkitystä: "Tunika (lat. tunica) on pitkän paidan tyylinen roomalainen vaatekappale, joka vastasi kreikkalaisten kitonia. [– –] Nykyisin tunikalla tarkoitetaan yleensä naisten käyttämää mekkomaista pitkää paitaa." (https://fi.wikipedia.org/wiki/Tunika)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Melindasta löytyi 3 viitettä yhdistelmällä tunikat & historia, joissa kyse on näistä aivan varhaisista vaatteista. Tunikat/tunikor/tunics tuo haulla ihan keskenään vastaavanlaisia naisten vaatteita, mutta LCSH:n lähdemerkinnät viittaavat antiikkiin, vaikka käsitteestä ei toisaalta muuten käy ilmi, mistä kaikesta sitä on tarkoitus käyttää.

**Comment by mariaforsen** [comment]
Myös sv. tunikor voidaan käyttää samoissa (kolmessa) merkityksissä https://www.kielitoimistonsanakirja.fi/#/tunika?searchMode=all

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta. Historiallinen ja nykyaikainen vaate katsottiin riittävän samankaltaisiksi, että ne edustavat samaa käsitettä.
