### ISSUE TITLE
lahjasoluhoidot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11406]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lahjasoluhoidot](http://www.yso.fi/onto/yso/p39090)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT sukusolujen luovutus

**Perustelut ehdotukselle**

KAUNOssa otettu em. muodossa

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta, mahdollisesti erikseen jos tarvetta.
