### ISSUE TITLE
esimiestaidot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11403]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[esimiestaidot](http://www.yso.fi/onto/yso/p24183)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

esihenkilötaidot

**Perustelut ehdotukselle**

Vastaavasti kuin termi esihenkilöt KT esimiehet

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11344

**Comment by mariaforsen** [comment]
Sv. chefsegenskaper > chefsfärdigheter
https://www.sanakirja.fi/custom/fi-en-sv/esimiestaidot
https://termipankki.fi/tepa/fi/haku/taito
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_850b9694092fa0896a298655d6fa0555&list_id=1&keyword=taito&word=taito
