### ISSUE TITLE
yhteishuolto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11405]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yhteishuolto](http://www.yso.fi/onto/yso/p5419)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KAUNOssa haluttiin ottaa muodossa yhteishuoltajuus. Säilytetäänkö entisellään YSOssa?

**Perustelut ehdotukselle**

KAUNO

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://thl.fi/fi/web/lapset-nuoret-ja-perheet/sote-palvelut/perheoikeudelliset-palvelut/lapsen-huolto-tapaaminen-ja-asuminen#yhteishuolto
https://www.minilex.fi/a/sopiminen-yhteishuoltajuudesta-ja-lapsen-tapaamisoikeudesta

Yhteishuoltajuus sopii varmasti paremmin kaunoaineistoon, mutta tietopuolella ehkä yhteishuolto kuitenkin parempi. Yhteishuoltajuus vie ajatukset enemmän siihen vanhemman kokemukseen (vrt. yritystoiminta/yrittäjyys). Toisaalta YSOssa on yksinhuoltajat, eikä yksinhuolto.

**Comment by mariaforsen** [comment]
Ruotsiksi termi on miten vain nykyinen gemensam vårdnad, ei ole vastaavaa -uus muotoa.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
