### ISSUE TITLE
Tekopyhyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11408]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Tekopyhyys

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Hypocrisy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Olisi tarpeen tekopyhyyttä käsittelevän aineiston kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562), [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85063768)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Shklar: Tavanomaisia paheita (Melinda ID 018646270)

**Ehdottajan organisaatio**

Itä-Suomen yliopisto
**Termiehdotus Fintossa:** [Tekopyhyys](http://finto.fi/yse/fi/page/Y511408)

**Comment by mariaforsen** [comment]
Sv. skenhelighet HT hyckleri, skrymteri
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_0c5e30c0a85c1ba86886d1ad6a2658b1&list_id=1&keyword=tekopyhyys&word=tekopyhyys
https://www.sanakirja.fi/custom/fi-en-sv/tekopyhyys
jfr https://www.kielitoimistonsanakirja.fi/#/tekopyh%C3%A4?source=suggestion
https://id.kb.se/term/sao/Hyckleri
https://svenska.se/tre/?sok=skenhelighet&pz=1
https://svenska.se/tre/?sok=hyckleri&pz=1

**Comment by mirmaid** [comment]
On KAUNOssa. 

11 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
