### ISSUE TITLE
glykosylaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11417]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

glykosylaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oulu.fi/fi/vaitokset/epanormaali-golgin-ph-homeostaasi-syovissa-sen-syyt-ja-seuraukset-syopasolun-fenotyypin-muutoksissa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [glykosylaatio](http://finto.fi/yse/fi/page/Y511417)

**Comment by mariaforsen** [comment]
Sv. glykosylering /ne
https://mesh.kib.ki.se/term/D006031/glycosylation

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh91003264
https://fi.wikipedia.org/wiki/Glykosylaatio

12 viitettä Melindassa.
