### ISSUE TITLE
Golgin laite

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11416]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Golgin laite

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oulu.fi/fi/vaitokset/epanormaali-golgin-ph-homeostaasi-syovissa-sen-syyt-ja-seuraukset-syopasolun-fenotyypin-muutoksissa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Golgin laite](http://finto.fi/yse/fi/page/Y511416)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Golgin_laite

https://www.solunetti.fi/fi/solubiologia/golgin_laite/2/

--

LCSH:
Golgi apparatus
http://id.loc.gov/authorities/subjects/sh85055819

FinMeSH:
Golgin laite
http://www.yso.fi/onto/mesh/D006056

**Comment by mariaforsen** [comment]
Sv. golgiapparat HT Golgiapparat, Golgi-apparat, golgikomplex
https://mesh.kib.ki.se/term/D006056/golgi-apparatus
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/golgiapparat
