### ISSUE TITLE
interferometria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11415]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

interferometria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oulu.fi/fi/vaitokset/passiivisen-seismisen-interferometrian-kehittaminen-maankuoren-pintaosan-geofysikaalisiin

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [interferometria](http://finto.fi/yse/fi/page/Y511415)

**Comment by mariaforsen** [comment]
Sv. interferometri
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/interferometri
https://sv.wikipedia.org/wiki/Interferometri

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85067258
https://en.wikipedia.org/wiki/Interferometry
https://fi.wikipedia.org/wiki/Interferometri

23 viitettä Melindassa.
