### ISSUE TITLE
kuriositeettikabinetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11413]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kuriositeettikabinetit

**Ehdotettu termi ruotsiksi**

kuriosakabinett

**Ehdotettu termi englanniksi**

Cabinets of curiosities  

**Tarkoitusta täsmentävä selite**

"Kunstkammern, art and curiosity cabinets housed in a dedicated room or suite of chambers, were often filled with thousands of diverse and sometimes shocking objects reflecting the bounty of nature and human creativity. These could range from a cherry pit carved with dozens of faces to an intricate drinking cup fashioned from a rhinoceros horn. Whether as a setting for personal contemplation or as a manifestation of the wealth and prestige of its owners, these proto-museums dazzled visitors of the time. This book offers the first in-depth comparative examination of the history, theory, organization and character of the major Kunstkammern in the Holy Roman Empire" (Kunstkammer : early modern art and curiosity cabinets in the Holy Roman Empire / Jeffrey Chipps Smith, 2022)

**Perustelut ehdotukselle**

Kuriositeettikabinetit Melinda-haussa, 11 viitettä

**Ehdotettu yläkäsite YSOssa (LT)**

 [kokoelmat](http://www.yso.fi/onto/yso/p12676)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [museokokoelmat](http://www.yso.fi/onto/yso/p38380)

**Vastaava käsite muussa sanastossa**

 [Sao](https://id.kb.se/find?inScheme.%40id=https%3A%2F%2Fid.kb.se%2Fterm%2Fsao&q=Kuriosakabinett%20), [LCSH](https://id.loc.gov/authorities/subjects/sh2002010501.html), [maotao](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp6173), [wikipedia](https://fi.wikipedia.org/wiki/Kuriositeettikabinetti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/1a9ac4k/alma9934422127006253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [kuriositeettikabinetit](http://finto.fi/yse/fi/page/Y511413)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11412
