### ISSUE TITLE
taiteilijaparit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11419]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taiteilijaparit

**Ehdotettu termi ruotsiksi**

konstnärspar

**Ehdotettu termi englanniksi**

artist couples

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Taiteellisia työpareja käsittelevän aineiston kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581)

**Vaihtoehtoiset termit**

 taiteilijaduot

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://lccn.loc.gov/sh93003367), [](https://id.kb.se/term/sao/Konstn%C3%A4rspar )

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018080739

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [taiteilijaparit](http://finto.fi/yse/fi/page/Y511419)

**Comment by mariaforsen** [comment]
SAOssa sekä taiteilija- että "kirjailijaparit": https://id.kb.se/term/sao/Konstn%C3%A4rspar
https://id.kb.se/find?q=f%C3%B6rfattarpar

**Comment by mirmaid** [comment]
26 viitettä Melindassa. Onko taiteilijapari tietynlainen taiteilijaryhmä?

**Comment by tpalonen** [comment]
Onko taiteilijapari sellainen, jossa ihmisten välillä on romanttinen suhde? Ovatko Coenin veljekset taiteilijapari?

**Comment by mirmaid** [comment]
^ Itsekin ensin ajattelin että onko kyse pariskunnista, mutta siis ei. Vaikka ei se poissuljettuakaan ole.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään sanastoon _työparit_. Pohditaan lisätäänkö ohjaustermeiksi _taiteilijaparit_ ja _kirjailijaparit_.

**Comment by tpalonen** [comment]
Päätöksen mukaisesti _parityöskentely_-käsitteeltä pois ohjaustermi _työparit_.

**Comment by mariaforsen** [comment]
Sv. arbetspar HT partner/s (arbetspar), författarpar, konstnärspar
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1dd4f6b9dd94bedc9f75481ea788c240&list_id=1&keyword=ty%C3%B6pari&word=ty%C3%B6pari
