### ISSUE TITLE
toimikortit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11427]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[toimikortit](http://www.yso.fi/onto/yso/p11633)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSOssa toimikortit, älykortit ja SIM-kortit ovat saman käsitteen labeleita. Onko toimikortit paras mahdollinen preflabel käsitteelle? Käsite / asiasana on ollut YSAssa vuodesta 1996 toimikortit-nimellä, mutta toimikortit ei ehkä nykykäyttäjälle terminä ole näistä tutuin. Lisäksi YSOssa on erikseen sirukortit-käsite. SIM-kortit ovat sirukortteja eli SIM-kortit voisi olla myös sirukorttien ohjaustermi. Wikidatassa tämä meneekin eri tavalla: siellä älykortti-kohteen ohjausterminä on sirukortti ja SIM-kortti taas on erikseen ihan omana kohteenaan.

**Perustelut ehdotukselle**

älykortti: https://www.wikidata.org/wiki/Q41349
SIM-kortti: https://www.wikidata.org/wiki/Q230110

**Ehdottajan organisaatio**

Finto / Tuomas

**Comment by ilona-x** [comment]
LCSH:
**Smart cards** http://id.loc.gov/authorities/subjects/sh85123621
Variants
    Cards, Smart
    Chip cards
    IC cards
    Integrated circuit cards
    Memory cards

SAO:
**smartkort** https://id.kb.se/term/sao/Smartkort
variant
Smarta kort
Aktiva kort

**Comment by ilona-x** [comment]
Tepa:
sirukortti https://termipankki.fi/tepa/fi/haku/sirukortti
älykortti https://termipankki.fi/tepa/fi/haku/%C3%A4lykortti
toimikortti https://termipankki.fi/tepa/fi/haku/toimikortti
SIM-kortti https://termipankki.fi/tepa/fi/haku/sim-kortti
tietokortti https://termipankki.fi/tepa/fi/haku/tietokortti

**Comment by ilona-x** [comment]
YSOssa myös 
**tietokortit** (sv. aktivkort) http://www.yso.fi/onto/yso/p10777

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**älykortti**
mikrosuorittimen ja muistia sisältävä tietokortti, toimikortti. 

**toimikortti**
= älykortti. 

**tietokortti**
pankki-, luotto- tms. kortti, johon voidaan tallentaa koneellisesti luettavaa tietoa. 

**sirukortti**
mikrosirun sisältävä muisti- t. älykortti. 

**SIM-kortti**
matkaviestimeen sijoitettava kortti, joka sisältää tilaajan tunnistamiseen ja radioliikenteen salaamiseen tarvittavia tietoja.

**Comment by mirmaid** [comment]
Eli kaksi kysymystä:
vaihdetaanko älykortit päätermiksi (KT toimikortit)?
otetaanko sim-kortit erikseen? Eikö toimikortti ole aina sirukortti, joten ei varmaan kannata ohjata sim-kortit KÄ sirukortit, jos on jo KÄ toimikortit?

Hierarkiaa pitänee myös muokata Tepan määritelmien mukaan.

**Comment by ilona-x** [comment]
tässä vielä linkki aiemmin ehdotettuun **eSIM**-termiin https://github.com/Finto-ehdotus/YSE/issues/7877

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Vaihdetaan toimikortit-termi käsitteen ohjaustermiksi eli muutetaan termit näin:
toimikortit KÄYTÄ älykortit
Poistetaan käsitteeltä ohjaustermi SIM-kortit.
Otetaan sanastoon erikseen käsite: SIM-kortit.
Mietitään SIM-kortit-käsitteelle ohjaustermejä, joka ilmaisee elektronisia SIM-kortteja, mahdollisesti ainakin eSIM-kortit.

Ks. myös https://github.com/Finto-ehdotus/YSE/issues/7877

**Comment by mariaforsen** [comment]
Sv. sim-kort HT SIM-kort, simkort
-https://termipankki.fi/tepa/fi/haku/sim-kortti
-https://www.mediesprak.fi/sim-kort-sim-kort-eller-simkort
-https://svenska.se/tre/?sok=SIM-kort&pz=1
-https://www.rikstermbanken.se/search?q=sim-kort&s=termer
