### ISSUE TITLE
peri-implantiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11422]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

peri-implantiitti

**Ehdotettu termi ruotsiksi**

periimplantit

**Ehdotettu termi englanniksi**

peri-Implantitis

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D057873)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Modern and Future aMMP-8 Point-of-Care/Chairside Diagnostic and Treatment Modalities in Periodontitis and Peri-Implantitis http://urn.fi/URN:ISBN:978-951-51-8490-0

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [peri-implantiitti](http://finto.fi/yse/fi/page/Y511422)

**Comment by mariaforsen** [comment]
Sv. periimplantit HT peri-implantit
https://mesh.kib.ki.se/term/D057873/peri-implantitis
