### ISSUE TITLE
aviorikokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11429]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aviorikokset](http://www.yso.fi/onto/yso/p19707)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Rajataan rikoksiin.

**Perustelut ehdotukselle**

Sanastossa on myös uskottomuus, joten tämä on siinä merkityksessä tarpeeton.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Riittäisikö hierarkian korjaus ja ohjaus aviorikokset (uskottomuus) KÄ uskottomuus? Aviorikokset (rikokset) tuntuu vähän hassulta, mutta mahdollinen sekin on (pää- tai ohjausterminä).

**Comment by vthuhtal** [comment]
Voitaisiin määritellä (Wikipediaa myötäillen) näin, jotta historiallinen yhteys säilyisi: Rikoslain alainen rikos, jossa avioliitossa elävä henkilö harjoittamaa sukupuoliyhteyttä muun kuin oman aviopuolisonsa kanssa. Suomessa tämä oli rikoslain alainen rikos vuoteen 1948. Aviorikos on kuitenkin rikoslain alainen asia monissa maissa, kuten esimerkiksi Iranissa.

Silloin myös nyt assosiatiivinen käsite 'rikokset' voitaisiin siirtää yläkäsitteeksi.

Suhde käsitteseen 'salavuoteus'?

**Comment by mirmaid** [comment]
^ Oisko RT?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Toimitaan Mirjan ehdotuksen mukaisesti ja lisätään yllä esitettyä lisäystä mukaileva huomautus.
