### ISSUE TITLE
polyhydroksialkanoaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11420]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

polyhydroksialkanoaatit

**Ehdotettu termi ruotsiksi**

polyhydroxialkanoater

**Ehdotettu termi englanniksi**

polyhydroxyalkanoates

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Polyhydroksialkanoaatit), [FinMeSH](http://www.yso.fi/onto/mesh/D054813)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Polyhydroxyalkanoate production in yeast Saccharomyces cerevisiae  http://urn.fi/URN:ISBN:978-952-64-0846-0

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [polyhydroksialkanoaatit](http://finto.fi/yse/fi/page/Y511420)

**Comment by mariaforsen** [comment]
Sv. polyhydroxialkanoater /mesh HT polyhydroxyalkanoater
