### ISSUE TITLE
ruuhet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11426]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ruuhet](http://www.yso.fi/onto/yso/p9452)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sanalla ruuhi on kaksi merkitystä: 1. yhdestä puunrungosta koverrettu vene.
2. pienehkö laudoista tehty tasapohjainen, -keulainen ja -peräinen vene. Kumpi merkitys käsitteellä YSOssa on? Vaiko molemmat?

**Perustelut ehdotukselle**

Tämä vaikuttaa linkitykseen ja muiden kielten termivalintoihin. Kontroversiaali situaatio observoitiin Wikidata-linkitystä implementoitaessa. 
Ks. https://www.wikidata.org/wiki/Q596073
https://www.wikidata.org/wiki/Q572738

**Ehdottajan organisaatio**

Finto / Tuomas

**Comment by mirmaid** [comment]
En ehkä uskaltaisi vetää yhtäläisyyttä punt-veneen ja ruuhen välille.

Museon ruuhista kaksi on tehty yhdestä puunrungosta kovertamalla. -- Museon kolmas ruuhi (YL 190) on kaksipuinen ja tasapohjainen ruuhi, jonka puuosat on liitetty toisiinsa tappiliitoksilla. Näitä liitoksia on vielä tuettu poikittaisilla tukipuilla, joista yksi on vielä jäljellä ja aluksen rungossa on vielä jäljellä tappeja sekä koloja merkkeinä muiden liitosten kohdista. https://vuosituhannet.wordpress.com/2017/09/01/ylojarven-museon-muinaisruuhet/
- tässä tapauksessa kyse ei ole kuitenkaan lautaveneestä.

**Comment by mirmaid** [comment]
Tässä olisi varmaan hyvä lähdeteos pohdinnalle: https://melinda.kansalliskirjasto.fi/byid/014824225

**Comment by mariaforsen** [comment]
Sv. on ollut ekor > stockbåtar? Jos kyseessä on **"yhdestä puunrungosta tehty vene"**
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_0276c86e63f2ea7ca716959da17aae51&list_id=1&keyword=ruuhi&word=ruuhi
https://www.sanakirja.fi/custom/fi-en-sv/ruuhi
https://www.wikidata.org/wiki/Q596073
-https://svenska.se/tre/?sok=eka&pz=1
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/stockb%C3%A5t

**Comment by mirmaid** [comment]
^ Miten tuollainen muinaisvene, joka on tehty useammasta puusta liittämällä, mutta ei laudoista? 

Selvää siis on, että tässä on kielieroja, eikä vastaavuus varmaan helposti ole yksi-yhteen, mutta vaikka näitä yrittäisi jakaakin, pitäisi tietää missä raja menee - kun ilmeisesti ruuhi ei ole vain joko yksipuinen tai laudoista tehty, vaan voi olla myös muulla tavoin useammasta puusta rakennettu.

**Comment by fantsby-m** [comment]
> Tässä olisi varmaan hyvä lähdeteos pohdinnalle: https://melinda.kansalliskirjasto.fi/byid/014824225

Löytyy digitoituna:
https://fennougrica.kansalliskirjasto.fi/handle/10024/89799

**Comment by mirmaid** [comment]
^ Tästähän löytyy myös hyviä ohjaustermimuotoja, kuten _lorja, öykki_ ja _paklootapaatti_. Myös ruotsiksi!

Mukana on myös etymologiaa ja ruuhien tyyppien kansainvälistä vertailua. S. 151 alkaen useampipuisista ruuhista esim. ruotsissa. Jospa tähän saisi jonkun x och x -termin ja ehkä myös määritelmät?

**Comment by mariaforsen** [comment]
Näyttää siltä että lautaruuhi=eka ja ruuhi (yhdestä puunrungosta)=stockbåt ?

**Comment by jarmosaarikko** [comment]
Onko tässä siis kolme erilaista venettä?
* ruuhet KT purtilot - yleensä yhdestä puunrungosta veistetty vene
* lautaruuhet KT laatikkoruuhet, purrit, tasut  - useammasta puunkappaleesta lautapohjainen ruuhi
  * Tasapohjainen ruuhi (eka, oka, äska, flatäska, fläta, träskabät) 
* jokiveneet  (punt, stakbåt, punt-boats)  (MOT-sanakirja)  vrt. punters = sauvojat    "sauvalla liikuteltava tasapohjainen vene" (?)

**Comment by YSO-kokous** [comment]
**Päätös**

Selvitetään voisiko käsitettä selkeyttää määritelmällä. Ei päätetä vielä muutoksia, mutta tarkistetaan eri kielten käännöksiä ja linkityksiä.

**Comment by tpalonen** [comment]
Punt ei liene englanniksi paras vastine ruuhelle, vaikuttaa lähinnä brittiläiseltä venetyypiltä.

**Comment by mariaforsen** [comment]
Sv. ekor > ekor och stockbåtar
"Ruuheksi kutsutaan myös alkukantaista, matalaa, yleensä pienikokoista lautavenettä, jonka muoto ja rakenne muistuttaa yksipuisia ruuhia." / https://fi.wikipedia.org/wiki/Ruuhi
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_0276c86e63f2ea7ca716959da17aae51&list_id=1&keyword=ruuhi&word=ruuhi
https://www.sanakirja.fi/custom/fi-en-sv/ruuhi
https://www.wikidata.org/wiki/Q596073
-https://svenska.se/tre/?sok=eka&pz=1
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/stockb%C3%A5t

**Comment by mariaforsen** [comment]
Jos kerran näin tarkalle tasolle mennään venetyypeissä, niin olisiko syytä ensin ottaa ainakin soutuveneet=roddbåtar erillisenä terminä? Nyt se on KÄYTÄ veneet. Moottoriveneet on jo sanastossa.

**Comment by mirmaid** [comment]
Melindasta päätellen ruuhet ovat paljon suositumpia kuin soutuveneet 😄. Mutta mun puolestani se on kyllä ok.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Valitaan ruotsiksi käytettäväksi termiksi och-muoto.
Mietitään englanniksi jokin kelvollinen termiratkaisu. YSO-ylläpito pohtii tätä tykönään. YSO-ylläpito pohtii myös, onko käsitteessä termitasolla mukana yhdestä puunrungosta valmistetun veneen merkitys vai ei.

Keskustelua
Suomeksi olisi haastavaa muodostaa käsitejakoa tässä.
