### ISSUE TITLE
haalarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11421]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[haalarit](http://www.yso.fi/onto/yso/p25888)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Suomen haalareita vastaa englannissa ja ruotsissa kaksi käsitettä. Englanniksi boilersuit ja overalls. Ruotsiksi overall ja snickarbyxor. Erottelevana tekijänä on, onko kyseessä kokovartalohaalari (esim. pilkkihaalari) vai onko kyseessä hihattomat haalarit, joissa yleensä olkaimet. Jo olemassa olevaa kuvailua voi toki olla haastava käydä läpi, jos käsite päätetään jakaa.

**Perustelut ehdotukselle**

Tilanne havaittiin Wikidata-linkityksen yhteydessä. 
Ks. https://www.wikidata.org/wiki/Q1077396
Ks. https://www.wikidata.org/wiki/Q13383825

**Ehdottajan organisaatio**

Finto / Tuomas

**Comment by mirmaid** [comment]
Melindan viitteet ovat enimmäkseen käsityölehtien lastenvaateohjeita, joissa usein onneksi on melko hyvä kuvaus vaatteesta - en kyllä osaa sanoa miten kattavasti. 

Suomeksi vähän kömpelösti ilmaistavissa, ehkä mahdollinen:
haalarit (olkaimelliset) KÄ lappuhaalarit
haalarit (hihalliset) KÄ kokohaalarit/umpihaalarit

**Comment by satuniininen** [comment]
Myös avohaalareista puhutaan, mutta lähinnä työvaatteiden yhteydessä. Eng. ohjaustermiksi myös dungarees.

**Comment by YSO-kokous** [comment]
**Päätös**

Pidetään käsite _haalarit_, mutta lisätään _työhaalarit_. Ohjaustermi _haalarit (työvaatteet)_. Linkitys- ja kielivastineet päätöksen mukaan.

**Comment by tpalonen** [comment]
Perusteluja päätökselle: suomen kannalta jako hihattomiin ja hihallisiin oli ongelma sikäli, että intuitiivista ja yleispätevää termiä ei näille olisi löytynyt. Ruotsin kannalta taas yksi haalarit-käsite olisi ollut huono ratkaisu. Päädyttiin tällaiseen rajaukseen, jossa jakoperuste ja termit ovat ymmärrettävät.

**Comment by mariaforsen** [comment]
Sv. arbetshalare och -snickarbyxor HT arbetsoveraller och -snickarbyxor, arbetsoveraller, overaller (arbetskläder), halare (arbetskläder), snickarbyxor (arbetskläder)

https://www.sprakbruk.fi/-/fr%C3%A5n-overalls-till-halare
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1fc52132abec689e5c4863b78495e49a&list_id=1&keyword=ty%C3%B6haalari&word=ty%C3%B6haalari
https://termipankki.fi/tepa/fi/haku/haalari
https://www.wikidata.org/wiki/Q1077396
https://kaino.kotus.fi/fsob/?p=qs-article&fsob_id=FSOB_8ade8060acb4d5a5a66aec8a0f1faf76&list_id=1&keyword=halare&word=halare
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_e7207bfaf57acdd648cb089a0416d810&list_id=1&keyword=haalari&word=haalari
