### ISSUE TITLE
konsulit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11423]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[konsulit](http://www.yso.fi/onto/yso/p14900)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Termillä on useita merkityksiä. Tärkeimpiä lienevät nämä kaksi: 1) "an agent who looks after his country's residents in (part of) a foreign country" 2) "either of the two chief magistrates in ancient Rome". Suomen, ruotsin ja englannin osalta tilanne lienee sama. 

Muita merkityksiä: Ranskaa vuosina 1799–1804 hallinneen konsulaatin jäsen; Suomessa myönnettävä arvonimi. Lisäksi: kunniakonsuli = valtion palkaton ja usein sivutoiminen edustaja toisessa maassa. Ks. https://fi.wikipedia.org/wiki/Konsuli

**Perustelut ehdotukselle**

Havaittiin Wikidata-linkityksen yhteydessä. 
https://www.wikidata.org/wiki/Q40779
https://www.wikidata.org/wiki/Q207978
Melinda-kuvailussa on käytetty sekä merkityksessä korkea virka antiikin Roomassa että valtion edustaja ulkomailla. Nämä kaksi lienee helposti erotettavissa, mikäli käsite päätetään jakaa. 

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Olisiko sitten
konsulit (ulkomaanedustajat)
konsulit (Rooman valtakunta)

**Comment by mariaforsen** [comment]
Sv. -konsuler (utlandsrepresentanter)
-konsuler (romerska riket)
