### ISSUE TITLE
angolalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11436]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

angolalaiset

**Ehdotettu termi ruotsiksi**

angolan

**Ehdotettu termi englanniksi**

Angolan

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://fi.wiktionary.org/wiki/angolalainen](http://angolalainen)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.3841844?sid=2929315815

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [angolalaiset](http://finto.fi/yse/fi/page/Y511436)

**Comment by mariaforsen** [comment]
Sv. angolaner
https://svenska.se/tre/?sok=angolaner&pz=1
