### ISSUE TITLE
Taipaleen kanava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11435]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Taipaleen kanava](http://www.yso.fi/onto/yso/p115597)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tämän ja muut pienet Suomessa sijaitsevat kanavat mahdollisesti siirtää niiden sijaintikuntien alakäsitteiksi?

https://finto.fi/yso-paikat/fi/search?clang=fi&q=*kanava

**Perustelut ehdotukselle**

Esimerkiksi tämän Taipaleen kanavan sijainti on PNR:n mukaan Savonlinna:
http://paikkatiedot.fi/so/1000772/10686411

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Kanavilta näyttää puuttuvan myös PNR-linkit, vaikka ainakin osa näistä löytyy PNR:stä.

**Comment by mirmaid** [comment]
Lisätään linkit ja hierarkia.

**Comment by ilona-x** [comment]
Hierarkia ja linkit lisätty.
