### ISSUE TITLE
jemeniläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11439]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jemeniläiset

**Ehdotettu termi ruotsiksi**

yemenitisk, jemenitisk ?

**Ehdotettu termi englanniksi**

Yemeni

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [aasialaiset](http://www.yso.fi/onto/yso/p3255)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://fi.wiktionary.org/wiki/jemenil%C3%A4inen](http://jemeniläiset)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4514895?sid=2929341054

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [jemeniläiset](http://finto.fi/yse/fi/page/Y511439)

**Comment by mariaforsen** [comment]
Sv. jemeniter HT yemeniter
https://svenska.se/tre/?sok=jemenit&pz=1
https://sv.wikipedia.org/wiki/Kategori:Jemeniter
https://www.ne.se/uppslagsverk/ordbok/svensk/yemenit
