### ISSUE TITLE
bolivialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11437]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

bolivialaiset

**Ehdotettu termi ruotsiksi**

boliviansk

**Ehdotettu termi englanniksi**

Bolivian

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallsisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [eteläamerikkalaiset](http://www.yso.fi/onto/yso/p5188)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://fi.wiktionary.org/wiki/bolivialainen](http://bolivialaiset)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.3979194?sid=2929328172

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [bolivialaiset](http://finto.fi/yse/fi/page/Y511437)

**Comment by mariaforsen** [comment]
Sv. bolivianer
https://svenska.se/tre/?sok=bolivianer&pz=1
