### ISSUE TITLE
Helsingin kaupunginosien ja osa-alueiden hierarkia

### ISSUE THREAD

**Issue by ilona-x** [Finto-ehdotus/YSE#11434]
Helsingin kaupunginosien ja osa-alueiden hierarkiaa voisi parantaa esimerkiksi siirtämällä osa-alueita kaupunginosien alakäsitteiksi.

Tässä listattuna issueita, joissa hierarkiaan liittyviä muutosehdotuksia:
https://github.com/Finto-ehdotus/YSE/issues/11027
https://github.com/Finto-ehdotus/YSE/issues/11025
https://github.com/Finto-ehdotus/YSE/issues/11021
https://github.com/Finto-ehdotus/YSE/issues/10742
https://github.com/Finto-ehdotus/YSE/issues/10741

**Comment by mirmaid** [comment]
Lisätään hierarkiaa silloin kun soveltuu (ei RT-suhteita vaan ylä-alakäsitesuhteita kaupunginosille ja osa-alueille). Mahdollisia muutoksia voidaan seurata PNR-linkkien kautta, jos paikkatyyppi muuttuu. Tämän voisi ehkä kirjata linkitysstrategiaan?

**Comment by mirmaid** [comment]
^ Itse asiassa paikkatyyppi on sama, eli ei voi sitä kautta seurata.
