### ISSUE TITLE
tutkimustieto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11432]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tutkimustieto](http://www.yso.fi/onto/yso/p27006)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "tutkimusdata"

**Perustelut ehdotukselle**

Paljon käytetty termi.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Suhde [**data**](http://www.yso.fi/onto/yso/p27250)-asiasanaaan?

**Comment by mariaforsen** [comment]
Sv. on forskningsdata, eli ruotsiksi tämä on jo varsinainen "tutkimusdata". Englanniksi samoin.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: tutkimustieto: _(tieteelliseen) tutkimukseen perustuva tieto_

Tutkimusdatasta esim. täällä https://libraryguides.helsinki.fi/datanhallinta/data

Suomeksi siis tutkimustieto tarkoittaa tutkimuksen tuottamaa tietoa (kunskap). Se voi olla tutkimuksen tuottamaa "dataa" (esim. tilastotietoa), mutta ei dataa, jonka pohjalta tutkimusta tehdään. Tai näin ainakin itse tämän ymmärrän. 

Suomeksi voisi laittaa tutkimusdata (tutkimustieto) KÄ tutkimustieto ja ehkä myös tutkimusdata (lähdeaineisto) KÄ lähdeaineisto. En tiedä miten suhtauduttaisiin siihen, että tutkimustieto-käsitteeseen muilla kielillä lisättäisiin tarkenne "tutkimustulokset"?

Ei varmaan sekään ihan mahdotonta ole, että otetaan myös suomeksi tutkimusdata, ja tutkimustieto muutetaan muilla kielillä kunskap/knowledge -muotoon.

**Comment by mariaforsen** [comment]
No siinä tapauksessa monikielisyyden kannalta ainoa vaihtoehto tässä lienee se että tutkimustieto muutetaan > kunskap ja tutkimusdata = forskningsdata otetaan uutena terminä? Tarkenteella ei siis pysty muuttamaan sv. data-termin merkitystä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään eri käsitteet _tutkimustieto_ ja _tutkimusdata_, jälkimmäinen uutena käsitteenä. Tarkistetaan ohjaustermit ja määritelmät.

**Comment by mariaforsen** [comment]
Sv. -forksningsbaserad kunskap HT forskningskunskap, forskningsinformation, forskningsrön, vetenskapliga rön
-forskningsdata
https://www.sanakirja.fi/custom/fi-en-sv/tutkimustieto
https://termipankki.fi/tepa/fi/haku/tutkimustieto
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_c3f33486495d00770cc3defe3229d9df&list_id=1&keyword=tutkimustieto&word=tutkimustieto
https://www.aka.fi/sv/om-oss/aktuellt/pressmeddelanden-och-nyheter/2021/temaaret-for-forskningsbaserad-kunskap-gav-438-tillfallen-att-bekanta-sig-med-forskningskunskap/
https://finna.fi/Content/tutkittu-tieto?lng=sv
https://www.abo.fi/nyheter/abo-akademi-mangvsidigt-med-i-temaaret-for-forskningsbaserad-kunskap/
https://okm.fi/hanke?tunnus=OKM047:00/2020
https://www.helsinki.fi/sv/nyheter/vetenskapspolitik/forskningsbaserad-kunskap-ger-hopp-och-losningar-darfor-ska-vi-varna-om-den
