### ISSUE TITLE
Perhelähtöisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11431]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Perhelähtöisyys

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Perheiden palveluissa asiakaslähtöisyyttä kuvaava termi.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Perhekeskustoimintamallin yksi pääperiaatteista.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Perhelähtöisyys](http://finto.fi/yse/fi/page/Y511431)

**Comment by mariaforsen** [comment]
Sanastossa on jo perhekeskeisyys https://finto.fi/yso/fi/page/p6295
eng. family orientation.. Olisiko ohjaustermi? Tai sitten RT. 

Ks. esim. http://jultika.oulu.fi/files/nbnfioulu-201905231977.pdf : "Perhekeskeisyyden käsitettä on korvaamassa suomenkielessä perhelähtöisyyden käsite, jossa keskeistä on lapsen vanhempien toimiminen tasavertaisina kumppaneina lasta hoitavan hoitohenkilökunnan kanssa"...

Myös tässä käsitellään käsitteiden mahdollista eroa: https://jyx.jyu.fi/bitstream/handle/123456789/25455/9789513940447.pdf

**Comment by mirmaid** [comment]
Vastaavat -lähtöisyys/-keskeisyys parit ovat sanastossa pää- ja ohjaustermeinä, ei siis erikseen. Ehdotan tämänkin lisäämistä ohjaustermiksi. Käytännön kuvailussa erottelu olisi todella vaikeaa. _Perhekeskeisyys_ ainakin toistaiseksi käytetympi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermiksi.
