### ISSUE TITLE
Onnela

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11433]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Onnela](http://www.yso.fi/onto/yso/p20126)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne (Tuusula)

**Perustelut ehdotukselle**

Käytetty muistakin samannimisistä paikoista.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Onnela (monimerkityksinen)

Tämäkö https://krapi.fi/onnelan-alue-on-osa-krapia/ ? https://www.syry.fi/kiinteistot/onnela
Ruotsiksi jo aiemmasta ollut Onnela (pensionat)..Parempi tarkenne olisi tosiaan tarpeen.
https://fi.wikipedia.org/wiki/Onnela_(Tuusula)

**Comment by ilona-x** [comment]
YSAssa on ollut huomautus: 
"Täysihoitola Tuusulanjärven rannalla"

--

Käytetty Melindassa 42 kertaa. Suurin osa Melindan viitteistä käsittelee Kajaanin asuntomessualueena toiminutta kaupunginosaa http://paikkatiedot.fi/so/1000772/10266853, joten Onnela (Kajaani) olisi ainakin tarpeen auktorisoida YSO-paikkoihin.
