### ISSUE TITLE
nettivideot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11443]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nettivideot](http://www.yso.fi/onto/yso/p22834)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö tälle lisätä video-alkuinen ohjaustermi? Mahdollisesti voisi myös tarkentaa tämän käsitteen eroa videoelokuvat-käsitteeseen.

**Perustelut ehdotukselle**

YSOssa ei ole lainkaan videot-alkuista termiä pääterminä tai ohjausterminä videotallenteille. Kun käyttäjä etsii Youtube/Tiktok-tyyppistä materiaalia, hän ei välttämättä tule ajatelleeksi, että pitäisi hakea netti-alkuisella hakusanalla. Toisaalta videoelokuvat-käsitettä on Melindassa käytetty myös itsetehdyistä videoista, jotka eivät ole koko illan elokuvia. Veikkaan, että kyseisen termin video-alkuisuus on juuri osasyynä tähän, vaikka tarkempi käsite Youtube/Tiktok-videoille olisi varmasti tämä nettivideot. Tilanne siis ehkä kaipaisi lisää ohjaustermejä ja mahdollisesti täsmentämistä myös muilla keinoin. 
Tein issuen myös videoelokuvat-käsitteestä. Ks. https://github.com/Finto-ehdotus/YSE/issues/11442

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Esimerkkejä Melindasta. Näiden kuvailussa on käytetty videoelokuvat-käsitettä mutta ei nettivideot-käsitettä:

Adobe After Effects : the official training workbook from Adobe / Brie Gyncild & Lisa Fridsma.
Like, comment, share, buy : the beginner’s guide to marketing your business with video storytelling / Jonathan Creek.
The discourse of YouTube : multimodal text in a global context / Phil Benson.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ehdotus.
