### ISSUE TITLE
oppilaskunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11449]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oppilaskunnat](http://www.yso.fi/onto/yso/p17232)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi oppilasneuvostot? Tai uutena terminä. 

**Perustelut ehdotukselle**

Käytetään joissakin kouluissa. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. elevråd
https://termipankki.fi/tepa/fi/haku/elevr%C3%A5d

**Comment by mirmaid** [comment]
Ohjaustermi varmaankin ok.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
