### ISSUE TITLE
kambodžalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11440]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kambodžalaiset

**Ehdotettu termi ruotsiksi**

kambodjan

**Ehdotettu termi englanniksi**

Cambodian

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjailijan kansallisuus 386-kenttään

**Ehdotettu yläkäsite YSOssa (LT)**

 [aasialaiset](http://www.yso.fi/onto/yso/p3255)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [https://fi.wiktionary.org/wiki/kambod%C5%BEalainen](http://kambodžalaiset)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.4500397?sid=2929350762

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [kambodžalaiset](http://finto.fi/yse/fi/page/Y511440)

**Comment by mariaforsen** [comment]
Sv. kambodjaner
https://svenska.se/tre/?sok=kambodjaner&pz=1
