### ISSUE TITLE
ansiomerkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11448]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ansiomerkit](http://www.yso.fi/onto/yso/p4348)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "muistoristit"

**Perustelut ehdotukselle**

Talvi- ja jatkosodan muistoristit eivät ole virallisia (valtiollisia) kunniamerkkejä, vaan epävirallisia eli paremminkin ansiomerkkejä. Nyt niitä käsittelevää aineistoa on kuvailtu vaihtelevasti, myös "kunniamerkit"- ja "mitalit"-asiasanoilla (esim. https://www.finna.fi/Record/hkm.4E6A7876-64B9-48E3-ADAE-BF6883D8B0C8?imgid=1). Selkeydyn vuoksi kaivattaisiin sana "muistoristi" sanastoon viittaamaan asianmukaiseen asiasanaan.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT minneskors (utmärkelsetecken)
https://fi.wikipedia.org/wiki/Muistoristi

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
