### ISSUE TITLE
rahit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11441]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rahit](http://www.yso.fi/onto/yso/p26194)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkemmin määriteltäväksi, tarkistetaan miten täsmää englanniksi ja ruotsiksi?

**Perustelut ehdotukselle**

Ks. https://www.kielitoimistonsanakirja.fi/#/rahi?searchMode=all
Eng. nyt kuitenkin nimenomaan jalkarahi, ruotsiksi taas ei ("låg stol utan rygg­stöd") 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Onko oikeastaan kaksimerkityksinen termi? 
https://www.kielitoimistonsanakirja.fi/#/rahi?searchMode=all 
https://en.wiktionary.org/wiki/rahi
Käännös riippuu merkityksestä. Määritelmän lisääminen auttaisi?

**Comment by mirmaid** [comment]
25 viitettä Melindassa, kaikki käsityöohjeita esim. rahin päällisistä. En hahmota tässä varsinaisesti selkeitä eri merkityksiä, enemmänkin on ehkä vähän epätarkkaa, missä menee rahin ja jakkaran ero (tai jakkaran ja tuolin).

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan nykyinen _rahi_ muotoon _jalkarahit_. Tämän lisäksi _rahit_ KÄYTÄ _jakkarat_, _rahit_ KÄYTÄ _penkit_, _rahit_ KÄYTÄ _jalkarahit_.

**Comment by mariaforsen** [comment]
Olisiko OT jalkajakkara? /MOT, google (sv. fotpall)
https://en.wiktionary.org/wiki/jalkajakkara
