### ISSUE TITLE
yhteyskeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11446]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yhteyskeskukset](http://www.yso.fi/onto/yso/p23471)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Eng. call centres vai contact centres?

**Perustelut ehdotukselle**

Harkitaan korjausta myös ruotsiksi. Ei ole enää vain puhelinpalvelusta kyse.. 
https://aiworks.twoday.fi/blogi/mika-on-contact-center
https://www.linecarrier.fi/artikkelit/mika-on-contact-center/
https://www.theseus.fi/bitstream/10024/97622/1/Mustonen_Tanja.pdf
https://www.tivi.fi/uutiset/yhteyskeskus-kohentaa-asiakaspalvelua/2706a09d-0a29-385f-ab89-19197eb1d2c1
https://www.hs.fi/talous/art-2000004211042.html

**Ehdottajan organisaatio**

ALLFO

**Comment by fantsby-m** [comment]
Mahdollisiin en ohjaustermeihin myös us en -muoto _center_.

Sama koskenee kaikkia [centres (organisations)](https://finto.fi/yso/fi/page/p801?clang=en) -termin alakäsitteitä.
