### ISSUE TITLE
ARP

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11456]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ARP](http://www.yso.fi/onto/yso/p9893)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettavaksi?

**Perustelut ehdotukselle**

Käytetty kahdesta eri asioista (autoradiopuhelin vs. address resolution protocol) ? Ks. Melinda. 
https://termipankki.fi/tepa/fi/haku/arp

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
ARP (protokollat)? Onkohan tuo toinen tarpeen, aika vähän viitteitä...

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _ARP (protokollat)_ ja _ARP (telepalvelut)_.

**Comment by mariaforsen** [comment]
Sv. -ARP (protokoll) HT address resolution protocol
-ARP (teletjänster) HT ARP (mobiltelefonsystem)
https://www.rikstermbanken.se/search?q=arp&s=termer
https://termipankki.fi/tepa/fi/haku/arp
https://sv.wikipedia.org/wiki/Address_Resolution_Protocol

**Comment by mirmaid** [comment]
ARP (protokollat) ja ARP (matkapuhelinjärjestelmät).
