### ISSUE TITLE
rytmihäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11457]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rytmihäiriöt](http://www.yso.fi/onto/yso/p9887)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeiksi arytmia ja sydämen rytmihäiriöt

**Perustelut ehdotukselle**

https://www.terveyskirjasto.fi/ltt00280
https://finto.fi/mesh/fi/page/D001145

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
"Arytmiat" monikko myös, sydämen rytmihäiriöitä on monenlaisia.
