### ISSUE TITLE
jäteautot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11452]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[jäteautot](http://www.yso.fi/onto/yso/p6857)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "jätteenkuljetusautot"

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT avfallstransportbilar

**Comment by tpalonen** [comment]
Ohjaustermiksi myös yleiskielinen _roska-autot_?

Vrt.
https://www.mtvuutiset.fi/artikkeli/tien-tukkinut-roska-auto-johti-sykahdyttavaan-kohtaamiseen-tampereella-leo-oli-ihan-taivaissa-sen-jalkeen/8297054#gs.x0h9ax
https://yle.fi/a/3-10440763
