### ISSUE TITLE
hylkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11454]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hylkeet](http://www.yso.fi/onto/yso/p9962)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko lat. Phocidae? Tarkistetaan muunkieliset termit.

**Perustelut ehdotukselle**

https://laji.fi/sv/taxon/MX.50568

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Jos lisäisi KT varsinaiset hylkeet?

**Comment by mariaforsen** [comment]
Sv. Phocidae= > öronlösa sälar HT egentliga sälar
https://en.wikipedia.org/wiki/Earless_seal
https://namnochslaktskap.artfakta.se/taxa/2002159/details
