### ISSUE TITLE
Painter

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11455]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Painter](http://www.yso.fi/onto/yso/p9904)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Toinen nimi Corel Painter?

**Perustelut ehdotukselle**

https://www.corel.com/en/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Pitäisikö vaihtaa?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Muutetaan _Corel Painter_ päätermiksi.
