### ISSUE TITLE
kornin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11453]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kornin kieli

**Ehdotettu termi ruotsiksi**

korniska

**Ehdotettu termi englanniksi**

Cornish language

**Tarkoitusta täsmentävä selite**

"Korni on Cornwallissa puhuttu kelttiläinen kieli, jota puhuivat kornit. Se sammui 1700-luvulla, mutta sitä on sittemmin yritetty elvyttää."--Wikipedia.

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kelttiläiset kielet](http://www.yso.fi/onto/yso/p18155)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Korni), [LCSH](https://lccn.loc.gov/sh85032849)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melinda ID 018769384
Llawlyfr cernyweg canol / Henry Lewis.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kornin kieli](http://finto.fi/yse/fi/page/Y511453)

**Comment by mariaforsen** [comment]
Sv. korniska HT corniska, kernewek
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/korniska
