### ISSUE TITLE
presuppositiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11459]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

presuppositiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/138668

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [presuppositiot](http://finto.fi/yse/fi/page/Y511459)

**Comment by mariaforsen** [comment]
Sv. presuppositioner
https://termipankki.fi/tepa/fi/haku/presuppositio
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/presupposition

**Comment by mirmaid** [comment]
N. 10 kertaa Melindassa yksikössä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
