### ISSUE TITLE
Arc/Info

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11451]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Arc/Info](http://www.yso.fi/onto/yso/p17402)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ArcInfo

**Perustelut ehdotukselle**

Uudempi versio, ks. https://en.wikipedia.org/wiki/ArcInfo

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Yleensä tämän tyyppisissä on taidettu vaihtaa uudempi nimi päätermiksi.
