### ISSUE TITLE
kylmäkuivaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11458]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kylmäkuivaus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/343133

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kylmäkuivaus](http://finto.fi/yse/fi/page/Y511458)

**Comment by mariaforsen** [comment]
Sv. frystorkning HT lyofilisering
https://sv.wikipedia.org/wiki/Frystorkning
https://termipankki.fi/tepa/fi/haku/kylm%C3%A4kuivaus
https://id.kb.se/term/sao/Frystorkning

**Comment by mirmaid** [comment]
N. 15 kertaa Melindassa.

https://fi.wikipedia.org/wiki/Kylm%C3%A4kuivaus

**Comment by jarmosaarikko** [comment]
* kylmäkuivaus KT lyofilisaatio, pakastekuivaus, pakkaskuivaus  
* freeze drying KT freeze-drying, cryodessication, lyophilisation
* frystorkning KT lyofilisering
YK kuivaus 
RK pakastus

http://www.wikidata.org/entity/Q723912

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
