### ISSUE TITLE
Juche-aate

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11462]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Juche-aate

**Ehdotettu termi ruotsiksi**

Juche

**Ehdotettu termi englanniksi**

Juche

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. 
Sekä muotoja Juche että Juche-aate käytetty jonkin verran Melindassa

**Ehdotettu yläkäsite YSOssa (LT)**

 [aatteet](http://www.yso.fi/onto/yso/p220)

**Ehdotetut temaattiset ryhmät**

 [02 Filosofia](http://www.yso.fi/onto/yso/p26545), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

 Juche

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Juche)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kim Il Sung: valitut teokset. Osa 1

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Juche-aate](http://finto.fi/yse/fi/page/Y511462)

**Comment by jtuohini** [comment]
KT-muodoksi myös _kimilsungismi_ (https://fi.wikipedia.org/wiki/Juche).

**Comment by mariaforsen** [comment]
Sv. juche /ne HT juche-ideologi, jucheideologi, kimilsungism, jucheism
https://sv.wikipedia.org/wiki/Juche
https://www.ui.se/landguiden/lander-och-omraden/asien/nordkorea/politiskt-system/
https://www.sprakbruk.fi/-/bindestreck-en-liten-repetition

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
