### ISSUE TITLE
biseksuaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1146]
#### Ehdotettu termi suomeksi

biseksuaalit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[61 Väestötiede. Demografia](http://www.yso.fi/onto/ysa/ryhma_61)

**Luontipäivämäärä:** 17.06.2004

**Muokkauspäivämäärä:** 17.6.2004, 16.12.2008

**Voyager-id:** 131618

**Termiehdotus Fintossa:** [biseksuaalit](http://finto.fi/yse/fi/page/Y331618)

**Comment by mirmaid** [comment]
Hyväksytty https://github.com/Finto-ehdotus/YSE/issues/5020
