### ISSUE TITLE
muinaiskielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11469]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[muinaiskielet](http://www.yso.fi/onto/yso/p10326)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Historialliset kielet ohjaustermiksi tai päätermiksi tai omaksi käsitteekseen.

**Perustelut ehdotukselle**

Historiallinen kieli on yksi ISO 639-3 -standardin kieliluokka. Esimerkiksi muinaisenglanti, muinaisvenäjä ja muinaisturkki ovat em. standardin mukaan historiallisia kieliä (YSOssa nämä ovat muinaiskielet-käsitteen alla). Historiallinen kieli on kieli, jota on puhuttu jonakin historiallisena aikana ja se eroaa nykykielistä. Historiallisella kielellä on myös kirjallisuutta. Standardissa on viisi kieliluokkaa. Historiallisen kielen lisäksi muut ovat: "living languages (languages with currently living native speakers), extinct languages (for languages whose last native speaker died within the last few centuries), ancient languages (whose last attested native speaker died more than a millennium ago), and constructed languages (which may or may not have native speakers)."

Historiallinen kieli ei siis ole täsmälleen sama asia kuin muinaiskieli (ancient language), mutta päädyin tekemään ehdotuksen YSOn nykyisen hierarkian inspiroimana.

Ks. https://en.wikipedia.org/wiki/Historical_language
https://en.wikipedia.org/wiki/Historical_language

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermiksi.

**Comment by tpalonen** [comment]
Linkitetty nyt Wikidatan ancient language -kohteeseen. https://www.wikidata.org/wiki/Q436240
