### ISSUE TITLE
ohjelmavälitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11461]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ohjelmavälitys](http://www.yso.fi/onto/yso/p10116)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Keikkamyynti päätermiksi. RT:ksi tapahtumatuotanto

**Perustelut ehdotukselle**

Suomen päätermi ohjelmavälitys ei vastaa nykypäivän kielenkäyttöä. En muista törmänneeni tällaiseen termiin musiikkipuolella, vaikka pitkään olen alalla pyörinyt. Google-haulla tulee hyvin laiha tulos, ottaen huomioon, miten yleisestä ilmiöstä on kyse. On otettu sanastoon vuonna 1986. Kertonee heikosta assosioitumisesta keikkamyyntiin, että YSO-käsitettä on käytetty kuvailussa tv-ohjelmistakin, mikä ei varmaan ole toivottua, ks. https://lvm.fi/-/pohjoisamerikkalaisten-tv-ohjelmien-osuus-kasvoi-viime-vuonna-741207

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
https://www.sanakirja.fi/custom/fi-en-sv/ohjelmav%C3%A4litys
Sv. on programförmedling, se ei taida olla sama asia kuin keikkamyynti..

**Comment by mirmaid** [comment]
Tv- ja radio-ohjelmien osalta Leena osaa varmaan valaista asiaa?

**Comment by fantsby-m** [comment]
> Tv- ja radio-ohjelmien osalta Leena osaa varmaan valaista asiaa?

Termiä tuskin on tarkoitettu koskemaan _ohjelmien_ myyntiä vaan ohjelmatoimistojen toimintaa (ks. sv ja en vastineet).

Sopisiko suom. termi- tai ohjaustermimuodoksi _ohjelmamyynti_? Sitä ainakin ohjelmatoimistot itse näyttävät usein käyttävän. Ongelmana tosin, että se on myös yhden ohjelmatoimiston nimi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _ohjelmamyynti (ohjelmatoimistot)_ KT _keikkamyynti_. Viitteiden korjausten jälkeen voidaan tarkastella uudelleen.

**Comment by mariaforsen** [comment]
Sv. programförsäljning (programbyråer) HT försäljning av framträdanden, eventförsäljning 
Jfr ex. https://www.sanakirja.fi/custom/fi-en-sv/ohjelmatoimisto 
https://www.ohjelmamyynti.fi/ 
https://vm.fi/sv/-/esiintyvien-taiteilijoiden-arvonlisaverotukseen-esitetaan-muutosta

**Comment by mirmaid** [comment]
Jäi 14 viitettä.

**Comment by fantsby-m** [comment]
Moniin sopisi _ohjelmatarjonta_, mahdollisesti myös _ohjelmapalvelut_, tai sitten _tv-ohjelmat_ ja _välitys_? 
Tähän sopisi ehkä _ohjelmistot (taiteet)_: https://melinda.kansalliskirjasto.fi/byid/012782533

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Ei enempää muutoksia sanastoon.
Tarkistetaan vielä Melindan kuvailutietoja.
