### ISSUE TITLE
Asbury Park

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11460]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Asbury Park

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan asiasanaksi kirjaan, joka käsittelee New Jerseyn Asbury Parkissa vaikuttaneita muusikoita ja muita musiikkialan ihmisiä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mårtensson, Anders: Greetings till och från Asbury Park 9789197744973

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Asbury Park](http://finto.fi/yse/fi/page/Y511460)

**Comment by jtuohini** [comment]
LCNAF/LSCH-vastine: [**Asbury Park (N.J.)**](http://id.loc.gov/authorities/names/n81143862).
