### ISSUE TITLE
kollaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11476]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kollaasit](http://www.yso.fi/onto/yso/p777)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "collaget"

**Perustelut ehdotukselle**

Kyseistä ilmausta käytetty suomen kielessä (ks. esim. https://melinda.kansalliskirjasto.fi/byid/018009209), joten olisi hyvä saada viittausmuodoksi.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by fantsby-m** [comment]
Ehdotuksen esimerkki on vuodelta 1964, eikä uudempaa käyttöä nopealla haulla löydy, joten onko tarpeellinen? **Kollaasi** on vakiintunut suomenkielinen termi.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei lisätä ohjaustermiksi.
