### ISSUE TITLE
Härjedalen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11470]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Härjedalen](http://www.yso.fi/onto/yso/p210730)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus

**Perustelut ehdotukselle**

Maakunta vai kunta?
https://sv.wikipedia.org/wiki/H%C3%A4rjedalen_(olika_betydelser)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Lisätään ainakin KT Härjedalen (maakunta), kuten Skånen tapauksessa. Kunnasta ei ehkä aineistoa...

**Comment by mirmaid** [comment]
Härjedalen (maakunta) päätermiksi.
