### ISSUE TITLE
sorbmen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11473]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sorbmen](http://www.yso.fi/onto/yso/p5068)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käsite: tappo

**Perustelut ehdotukselle**

Joku taitaa olla vahingossa vaihtanut käsitteen tappo suomenkieliseksi nimeksi sorbmen. Sana "sorbmen" on varmaan jotain sanaston saamenkielistä. Olisi hyvä korjata. Katsoin, että Finnaan on mennyt jonkin verran sorbmen-termiä automaattisesti(?), joten toivottavasti korjaantuvat

**Ehdottajan organisaatio**

Jyväskylän yliopiston kirjasto

**Comment by mirmaid** [comment]
^ Juuri näin on käynyt, pyritään korjaamaan pikaisesti.
