### ISSUE TITLE
Mäntyharjun kanava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11474]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mäntyharjun kanava](http://www.yso.fi/onto/yso/p110530)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

säilytetäänkö tämä YSO-paikoissa, vaikka kanavaa ei ole rakennettu ja hanke on kuopattu? 

**Perustelut ehdotukselle**
"Mäntyharjun kanava oli kanavahanke, jonka tarkoituksena oli yhdistää [Kymijoki](https://fi.wikipedia.org/wiki/Kymijoki) [Saimaaseen](https://fi.wikipedia.org/wiki/Saimaa)."
https://fi.wikipedia.org/wiki/M%C3%A4ntyharjun_kanava

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
3 viitettä Melindassa

**Comment by mirmaid** [comment]
Poistetaan.
