### ISSUE TITLE
Fiskarsinmäki (Espoo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11475]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Fiskarsinmäki (Espoo)](http://www.yso.fi/onto/yso/p108503)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä viittaa ilmeisesti Espoonlahden luonnonsuojelualueeseen? Pitäiskö lisätä ohjaustermi tai muuttaa päätermi. Muut luonnonsuojelualueet tällä hetkellä YSOn puolella

**Perustelut ehdotukselle**

https://www.luontoon.fi/espoonlahti
https://uuvi.fi/fi/kohde/espoonlahden-luonnonsuojelualue/

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
http://paikkatiedot.fi/so/1000772/10071418 - pää- tai ohjaustermiksi Fiskars (Espoo). Myös Espoon karttapalvelussa tällä nimellä.

**Comment by mirmaid** [comment]
Muutetaan luonnonsuojelualueeksi, KT Fiskarsinmäki.
