### ISSUE TITLE
Hartwall Areena

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11478]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Hartwall Areena](http://www.yso.fi/onto/yso/p17505)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaanko nimi?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Helsinki-halli

--

YLEllä käytössä nimimuoto Helsingin areena: https://yle.fi/aihe/t/18-172897

**Comment by mariaforsen** [comment]
Sv. Helsinki Halli HT Helsingforsarenan, Helsingforshallen
https://www.myhelsinki.fi/sv/se-och-g%C3%B6ra/evenemang/helsinki-halli
https://svenska.yle.fi/a/7-10013653
https://sv.wikipedia.org/wiki/Helsinki_Halli
https://www.hbl.fi/artikel/bcb5a76e-7409-4d00-b1bb-dd8719bb30d7

**Comment by mirmaid** [comment]
Vaihdetaanko Helsinki-halli?

**Comment by vthuhtal** [comment]
Toimijakuvailuun, sillä yhteisöjä, joilla on edeltäjä-seuraaja -suhde

**Comment by ilona-x** [comment]
https://www.kotus.fi/nyt/kolumnit_artikkelit_ja_esitelmat/kieli-ikkuna_%281996_2010%29/euroviisut_jarjestetaan_hartwall-areenassa

**Comment by YSO-kokous** [comment]
**Päätös**

Valitaan muoto _Helsinki-halli_.
