### ISSUE TITLE
Finnair Stadium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11479]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Finnair Stadium](http://www.yso.fi/onto/yso/p19123)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaanko nimi?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Wikipedia: **Töölön jalkapallostadion** https://fi.wikipedia.org/wiki/T%C3%B6%C3%B6l%C3%B6n_jalkapallostadion

"Töölön jalkapallostadion (markkinointinimeltään Bolt Arena ; aikaisemmin Finnair Stadium, Sonera Stadium ja Telia 5G Areena)"

**Comment by mariaforsen** [comment]
Sv. Tölö fotbollsstadion 
https://www.hel.fi/helsinki/sv/kultur-och-fritid/motion/idrottsplatser-utomhus/tolo-fotbollsstadion
https://www.sprakbruk.fi/-/varldsnyheter-och-lokala-handelser-paverkar-namnvardarens-jobb

**Comment by mirmaid** [comment]
^^ Vaihdetaan?

**Comment by vthuhtal** [comment]
Toimijakuvailuun, sillä yhteisöjä, joilla on edeltäjä-seuraaja -suhde
