### ISSUE TITLE
sukupuoleen perustuva vaino

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11483]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuoleen perustuva vaino](http://www.yso.fi/onto/yso/p27581)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng. gender persecution, gender-related persecution etc. - ohjaustermeiksi?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Gender-based persecution löytyy esim. IATEsta:
https://iate.europa.eu/entry/result/3629171/fi-en
