### ISSUE TITLE
perinnejärjestöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11484]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

perinnejärjestöt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

esim. https://www.suomenlottaperinneliitto.fi/

**Perustelut ehdotukselle**

Erilaisia perinneliittojen/perinnejärjestöjen historiikkeja tulee usein vastaan kuvailussa, ja näille järjestöille ei oikein ole sanastossa mitään kuvaavaa termiä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 perinneyhdistykset, perinneliitot

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lottaperinne Pori ry 30 vuotta 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [perinnejärjestöt](http://finto.fi/yse/fi/page/Y511484)

**Comment by jtuohini** [comment]
Lukeutuvatko perinnesäätiöt jollain tapaa samaan, esim. Paloheimon perinnesäätiö, Suomen marsalkka Mannerheimin perinnesäätiö ja Vapaussoturien perinnesäätiö?

**Comment by mariaforsen** [comment]
Sv. traditionsorganisationer, traditionsföreningar? (=yhdistykset)

**Comment by jarmosaarikko** [comment]
Englanniksi luultavasti kävisi jompi kumpi termeistä
* "heritage organisation" . 
* "legacy organisation" KT "legacy foundation", "legacy organization"

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _perinneyhdistykset_.

**Comment by mariaforsen** [comment]
Sv. traditionsföreningar HT traditionsförbund
https://perinne.fi/perinnetyo/jasenyhteisot/
