### ISSUE TITLE
people&#039;s houses (community halls)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11480]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[people&#039;s houses (community halls)](http://www.yso.fi/onto/yso/p5835)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Labour halls ohjaustermiksi?

**Perustelut ehdotukselle**

Millä termillä pitäisi asiasanoittaa julkaisua "Labour halls in Finland"? 978-952-68778-7-7 (PDF)
Ks. myös https://yle.fi/a/3-12583440

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Lisäksi tarvittaisiin KT-muodoksi _Workers’ halls_.

**Comment by fantsby-m** [comment]
Myös us-en muoto: _labor halls_
