### ISSUE TITLE
kaavoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11482]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kaavoitus](http://www.yso.fi/onto/yso/p8268)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaatiiko tarkenteen / jakamisen? 

**Perustelut ehdotukselle**

Nyt kaavoituksen yläkäsitteenä kunnan toimialat, mutta huomasin, että termiä on käytetty Melindassa esim. ompelun yhteydessä https://melinda.kansalliskirjasto.fi/byid/018156750

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. planläggning, eli ei käy ompelusta tms.

**Comment by mirmaid** [comment]
On kyllä yritetty ohjata ompelukaavoihin...tarvitaanko erikseen kaavoitus (käsityöt/ompelu), vai riittääkö niissä pelkkä ompelukaavat?
Mikä olisi tämän varsinaisen kaavoituksen tarkenne? Voisi ehkä olla (alueet), mutta sanastossa on myös kaavoitusalueet. Tai sitten (maankäyttö)?

**Comment by ilona-x** [comment]
kaavoitus (maankäyttö) kuulostaa hyvältä 👍 

Ja riittäisi varmaan jos olisi ohjaus kaavoitus (käsityöt) KÄYTÄ ompelukaavat.
