### ISSUE TITLE
ympäristömerkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11481]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ympäristömerkit](http://www.yso.fi/onto/yso/p17643)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään tämä ja ympäristömerkintä?

**Perustelut ehdotukselle**

Onko näillä jotain eroa?

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Merkintä voisi tietysti viitata toimintaan/prosessiin, mutta näköjään on hierarkisoitu kuitenkin niin että näyttää samalta asialta kuin -merkit.

**Comment by ilona-x** [comment]
Vaikuttavat tosiaan aika päällekkäisiltä termeiltä.

YSO:n **ympäristömerkintä**-termi näyttää olevan linkattu LCSH-termiin **Eco-labeling** http://id.loc.gov/authorities/subjects/sh96008868, mikä puolestaan on linkattu Wikidata-kohteeseen **ecolabel** http://www.wikidata.org/entity/Q1053399, mikä puolestaan on linkattu YSO-termiin **ympäristömerkit**.

--

Melinda:
ympäristömerkit x 335
ympäristömerkintä x 437
ympäristömerkit & ympäristömerkintä x 170

**Comment by mirmaid** [comment]
Tässä yhteydessä toiminta-aspekti tuntuu myös vähän tarpeettomalta näkökulmalta (ympäristömerkin antaminen/hakeminen?).

**Comment by mirmaid** [comment]
Yhdistetään ympäristömerkintä KÄ ympäristömerkit
