### ISSUE TITLE
palveluntuottajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11489]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[palveluntuottajat](http://www.yso.fi/onto/yso/p12069)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätäänko palveluntarjoajat ohjaustermiksi vai uudeksi termiksi?

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/palveluntarjoaja
https://termipankki.fi/tepa/fi/haku/palveluntuottaja
https://www.kielitoimistonsanakirja.fi/#/palveluntarjoaja?searchMode=all
Ks. Wikidatalinkki

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Palveluntarjoaja

**Comment by LeKorsu** [comment]
Ja sitten kun joku ehdottaa "palveluntoteuttajia"... Kannattaisiko kysyä, mitä mieltä Kielitoimisto on?

**Comment by ilona-x** [comment]
palveluntuottajat-termiä taidetaan käyttää pääosin sote-palveluiden yhteydessä https://valter.sanakirja.fi/all/all/palveluntuottaja

palveluntarjoaja-termin osalta [Tepan esimerkeissä](https://termipankki.fi/tepa/fi/haku/palveluntarjoaja) tuntuu korostuvan telepalvelut. Ja esim. YLEn uutisissa on käytetty termiä Internet-palveluntarjoaja https://yle.fi/uutiset/18-127715
https://fi.wikipedia.org/wiki/Internet-palveluntarjoaja

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan lisää ja siirretään seuraavaan kokoukseen. Tarkistetaan myös suhde käsitteeseen _palveluyritykset_.

**Comment by mariaforsen** [comment]
https://finto.fi/jupo/fi/page/p5175

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
palveluyritys: palveluja myyvä yritys. 
palveluntarjoaja: yrityksistä, instituutioista tms., jotka tarjoavat eril. palveluja.

**Comment by mirmaid** [comment]
Englanniksi service providerilla on laaja käytettävyys: https://en.wikipedia.org/wiki/Service_provider. 

Silloin kun palveluntarjoaja myy "omia palvelujaan" kuluttajalle, sopisi mielestäni ohjaus KÄ palveluyritykset. Jos myyty palvelu on esim. levytila, teleyhteys tai pääsy johonkin sisältöön (vaikka kanavapaketti), palveluyritys ei kuulosta niin toimivalta. Samoin jos vertailussa on esim. yksityisen ja julkisen sektorin terveyspalvelut. Pitäisikö kuitenkin lisätä palveluntarjoajat (palveluyritykset) KÄ palveluyritykset?

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään ohjaustermi: palveluntarjoajat (palveluyritykset) KÄYTÄ palveluyritykset
Tarkistetaan palveluntuottajat-käsitteen linkitys.
Ei muita muutoksia.

Keskustelua
Palveluntarjoaja on suomeksi varsin päällekkäinen palveluyrityksen kanssa. Palveluntarjoaja ja palveluntuottaja ei myöskään aina ole sama asia. Vrt. tv:n kanavapakettien välittäjät. Aiheeseen voidaan palata tarvittaessa.
