### ISSUE TITLE
ilmatorjuntaohjukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11498]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ilmatorjuntaohjukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Antiaircraft missiles

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ilmatorjuntaohjus on sotilaskäytössä oleva ohjus, joka on tarkoitettu ilmassa liikkuvien kohteiden (lentokoneiden, helikoptereiden, ohjusten) tuhoamiseen ja torjuntaan.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ohjukset](http://www.yso.fi/onto/yso/p17763)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://finto.fi/soto/fi/page/p1471), [](https://id.loc.gov/authorities/subjects/sh85005626.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.110091

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by jtuohini** [comment]
LCSH-vastine: [**Antiaircraft missiles**](http://id.loc.gov/authorities/subjects/sh85005626).

**Comment by mariaforsen** [comment]
Sv. luftvärnsrobotar HT luftvärnsmissiler, luftförsvarsrobotar
https://www.ne.se/uppslagsverk/encyklopedi/enkel/luftv%C3%A4rnsrobot
https://id.kb.se/term/sao/Luftv%C3%A4rnsrobotar
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_644fb23d4b016cf16f428f75ee7223b1&list_id=1&keyword=ilmatorjuntaohjus&word=ilmatorjuntaohjus
https://sv.wikipedia.org/wiki/Luftv%C3%A4rnsrobot
https://termipankki.fi/tepa/fi/haku/ilmatorjuntaohjus
https://svenska.se/so/?id=151841&ref=xnr245605
https://svenska.se/tre/?sok=luftv%C3%A4rnsrobot&pz=1

**Comment by mirmaid** [comment]
Melinda 577 / 154 (soto)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
