### ISSUE TITLE
asymmetrinen sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11497]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

asymmetrinen sota

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

asymmetric warfare

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

sodankäynti kahden voimasuhteiltaan epäsuhtaisen vihollisen välillä, tarkoitetaan myös tilanteita, joissa molemmat osapuolet käyttävät erilaisia strategioita.
https://www.doria.fi/handle/10024/74423

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://id.loc.gov/authorities/subjects/sh2001001771.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.167090

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [asymmetrinen sota](http://finto.fi/yse/fi/page/Y511497)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Asymmetric warfare**](http://id.loc.gov/authorities/subjects/sh2001001771).

**Comment by mariaforsen** [comment]
Sv. asymmetrisk krigföring HT asymmetrisk krigsföring
https://id.kb.se/term/sao/Asymmetrisk%20krigf%C3%B6ring

**Comment by mirmaid** [comment]
Kerran Melindassa, 20 x epäsymmetrinen sodankäynti.
https://fi.wikipedia.org/wiki/Ep%C3%A4symmetrinen_sodank%C3%A4ynti

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
