### ISSUE TITLE
kategoriateoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11492]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kategoriateoria

**Ehdotettu termi ruotsiksi**

kategoriteori

**Ehdotettu termi englanniksi**

category theory 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kategoriateoria on tärkeä matemaattinen käsite, jonka sisällönkuvailuun tarvittaisiin oma asiasana. Opiskelija ehdotti tätä. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [matematiikka](http://www.yso.fi/onto/yso/p3160)

**Ehdotetut temaattiset ryhmät**

 [04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Kategoriateoria)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/187002

**Ehdottajan organisaatio**

Åbo Akademis bibliotek
**Termiehdotus Fintossa:** [kategoriateoria](http://finto.fi/yse/fi/page/Y511492)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Categories (Mathematics)**](http://id.loc.gov/authorities/subjects/sh85020992), KT _Category theory (Mathematics)_.

**Comment by mirmaid** [comment]
3 kertaa Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
