### ISSUE TITLE
tractor pulling

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11490]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tractor pulling

**Ehdotettu termi ruotsiksi**

traktorpulling

**Ehdotettu termi englanniksi**

tractor pulling

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Saimme palautetta Kirjastopalvelulta finto-postiin. "Aihetta muuten vaikea ilmaista."

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q977576)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sanna Salo: Semmosta touhua - Pekka Herlevin tarina (Into-kustannus)
https://kauppa.intokustannus.fi/kirja/semmosta-touhua/

**Ehdottajan organisaatio**

Tuomas / Finto
**Termiehdotus Fintossa:** [tractor pulling](http://finto.fi/yse/fi/page/Y511490)

**Comment by jtuohini** [comment]
Alan kotimaisen yhdistyksen suomenkielinen nimi sisältää sanan "traktoriurheilu" (http://www.tractorpulling.fi/), joten eikö se olisi ihan hyvä suomenkielinen vastine? Englanninkielisessä nimessä vastaavasti on "tractor pulling".

**Comment by mariaforsen** [comment]
Sv. traktorpulling HT tractorpulling
https://stpf.nu/
https://id.kb.se/term/sao/Traktorpulling
https://www.sanakirja.fi/custom/fi-en-sv/tractorpulling 

"Tractor Pulling eli traktoriveto on moottoriurheilulaji, jossa traktorilla tai muulla vetoajoneuvolla vedetään painonsiirtolaitetta eli jarruvaunua vähintään 130 metrin pituisella (turva-alue mukaan luettuna) ja vähintään 10 metriä leveällä maaradalla mahdollisimman pitkä matka." Ks. http://www.tractorpulling.fi/?sivu=viewpage&pageid=2
Traktoriurheilu ei ole aivan sama asia (voi olla laajempi). Kannatan täsmällistä, ja tässä tapauksessa perinteistä, sekä lajin harrastajien käyttämää termiä. 
https://fi.wikipedia.org/wiki/Tractor_pulling

**Comment by jtuohini** [comment]
LCSH-vastine: [**Tractor pulling (Motorsports)**](http://id.loc.gov/authorities/subjects/sh2013001865).

**Comment by fantsby-m** [comment]
Traktoriveto? Ks. esim. 
https://fi.wikipedia.org/wiki/Tractor_pulling
http://www.tractorpulling.fi/?sivu=viewpage&pageid=2
https://www.maaseuduntulevaisuus.fi/aihe/traktoriveto

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _traktoriveto_.
