### ISSUE TITLE
asutuskeskustaistelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11495]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

asutuskeskustaistelut

**Ehdotettu termi ruotsiksi**

strid i bebyggelse

**Ehdotettu termi englanniksi**

urban warfare

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Urbaanissa ympäristössä tapahtuva sotilasoperaatio. Asutuskeskustaistelu eroaa maastossa tapahtuvasta taistelussa erityisesti siinä suhteessa, että se on kolmiulotteista: joukkoja voi olla katutason lisäksi katoilla ja rakennuksien yläkerroksissa, mutta myös maanalaisissa huolto-, metro- ja muissa tunneleissa.
https://fi.wikipedia.org/wiki/Asutuskeskustaistelu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://id.loc.gov/authorities/subjects/sh91005725.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.167870

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [asutuskeskustaistelut](http://finto.fi/yse/fi/page/Y511495)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Urban warfare**](http://id.loc.gov/authorities/subjects/sh91005725), ST [**Street fighting (Military science)**](http://id.loc.gov/authorities/subjects/sh85128586).

**Comment by mariaforsen** [comment]
Sv. strider i bebyggelse HT stadskrig, SIB, militära operationer i urban terräng, urban krigföring, urban krigsföring
https://www.fortifikationsverket.se/fastighetsforvaltning/fastighetsbestand/byggnader/2010-2020-talet/sib-ovningsanlaggning-for-strid-i-bebyggelse/
https://maavoimat.fi/sv/gardesjagarregementet/om-oss
https://www.rikstermbanken.se/search?q=SIB&s=termer

**Comment by mirmaid** [comment]
Melinda 46 / 106 (soto)

**Comment by mirmaid** [comment]
KAUNOssa on kaupunkisota, olisiko KT?

**Comment by mariaforsen** [comment]
Olisiko kaupunkisota oikeastaan RT? Asutuskeskuksia on kai maalaiskunnissakin yms. https://www.kielitoimistonsanakirja.fi/#/asutuskeskus?searchMode=all

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Ohjaustermiksi mm. _kaupunkisota_.
