### ISSUE TITLE
meritorjuntaohjukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11499]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

meritorjuntaohjukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Antiship missiles

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Meritorjuntaohjus on pinta-alusten tuhoamiseen tarkoitettu ohjus. Useimmat meritorjuntaohjukset ovat lähellä merenpintaa lentäviä, nopeudeltaan alle äänennopeuden ja ovat inertia- ja tutkaohjautuvia. Meritorjuntaohjus voidaan laukaista lentokoneesta, laivasta, sukellusveneestä tai maalla sijaitsevasta laukaisualustasta. https://fi.wikipedia.org/wiki/Meritorjuntaohjus

**Ehdotettu yläkäsite YSOssa (LT)**

 [ohjukset](http://www.yso.fi/onto/yso/p17763)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://finto.fi/soto/fi/page/p1691), [](https://id.loc.gov/authorities/subjects/sh2006001391.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.144383

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by jtuohini** [comment]
LSCH-vastine: [**Antiship missiles**](http://id.loc.gov/authorities/subjects/sh2006001391).

**Comment by mariaforsen** [comment]
Sv. sjömålsrobotar HT sjömålsmissiler
https://sv.wikipedia.org/wiki/Sj%C3%B6m%C3%A5lsrobot
https://www.sanakirja.fi/custom/fi-en-sv/meritorjuntaohjus
https://www.forsvarsmakten.se/sv/information-och-fakta/materiel-och-teknik/vapen/robotsystem-15/
https://aeroseum.se/vagen-till-marinens-forsta-sjomalsrobot/

**Comment by mirmaid** [comment]
Melinda 8 /12 (soto)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
