### ISSUE TITLE
haupitsit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11493]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

haupitsit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Howitzers

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

"Käsite haupitsi on vakiintunut tarkoittamaan suhteellisen lyhytputkista, suurella korotuskulmalla ja yleensä alle 20 kilometrin etäisyydelle ampuvaa tykkiä. Haupitsien putken pituus on yleensä alle 30 kertaa kaliiperi. Eri maissa nykyisin käytössä olevat haupitsit ovat kaliiperiltaan 105–203 millimetriä. Tyypillisimmät venäläiset kaliiperit ovat 122 ja 152 millimetriä ja läntiset 105 ja 155 millimetriä.""
-Puolustusvoimien kalustokuvasto, https://puolustusvoimat.fi/kalusto#/asset/view/id/234

**Ehdotettu yläkäsite YSOssa (LT)**

 [tykit](http://www.yso.fi/onto/yso/p2312)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://id.loc.gov/authorities/subjects/sh85062664.html), [](https://fi.wikipedia.org/wiki/Haupitsi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.127927?sid=2937493416

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [haupitsit](http://finto.fi/yse/fi/page/Y511493)

**Comment by mariaforsen** [comment]
Sv. haubitsar HT haubitser
https://termipankki.fi/tepa/fi/haku/haubits
https://svenska.se/tre/?sok=haubits&pz=1
https://www.finlex.fi/sv/laki/alkup/1997/19970192

**Comment by jtuohini** [comment]
LCSH-vastine: [**Howitzers**](http://id.loc.gov/authorities/subjects/sh85062664).

**Comment by mirmaid** [comment]
Melinda 38 (soto)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
