### ISSUE TITLE
kaljaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11491]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaljaasit

**Ehdotettu termi ruotsiksi**

galeas

**Ehdotettu termi englanniksi**

galeas

**Tarkoitusta täsmentävä selite**

Wikipedia: Kaljaasi on purjealuksesta takiloinnin perusteella käytetty nimitys, joka on alun perin tarkoittanut kaleeria. Perämeren rannikolla kaljaasityyppisistä aluksista on käytetty nimitystä jähti. Kaljaasitakila muodostuu kahdesta tai kolmesta mastosta, joissa jokaisessa on kahveli- ja latvapurjeet, sekä näiden lisäksi vielä kokkapurjeita kahdesta kolmeen kappaletta. Runkoratkaisuiltaan kaljaasit oli suunniteltu rahdin kuljettamiseen, ja ruumatila oli lähes koko rungon pituinen. Ruorihytti ja messi sijaitsivat yleensä perässä ja varasto- ja miehistötilat keulassa.

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [purjelaivat](http://www.yso.fi/onto/yso/p20211)

**Ehdotetut temaattiset ryhmät**

 [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

 jähdit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Kaljaasi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melindassa haku "kaljaasit" - 35 osumaa.
Esimerkiksi: 
Loviisan seudun kaljaasit  https://melinda.kansalliskirjasto.fi/byid/006644525

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kaljaasit](http://finto.fi/yse/fi/page/Y511491)

**Comment by ilona-x** [comment]
MAO: kaljaasit http://www.yso.fi/onto/mao/p5405
LIIKO: kaljaasit http://www.yso.fi/onto/mero/m9230

**Comment by mariaforsen** [comment]
Sv. galeaser
https://svenska.se/tre/?sok=galeas&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
