### ISSUE TITLE
häiveteknologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11494]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

häiveteknologia

**Ehdotettu termi ruotsiksi**

smygteknik

**Ehdotettu termi englanniksi**

stealth technology

**Tarkoitusta täsmentävä selite**

Teknologiat, joilla pyritään tekemään kulkuneuvo tai ohjus lähes näkymättömäksi tutkilta tai muulta elektroniselta seurannalta.

**Perustelut ehdotukselle**

Vakiintunut sotatekniikan termi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sotatekniikka](http://www.yso.fi/onto/yso/p9292)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

 häivetekniikka

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Soto](http://finto.fi/soto/fi/page/p92), [LCHS](https://id.loc.gov/authorities/subjects/sh2015003069.html), [Wikipedia](https://fi.wikipedia.org/wiki/H%C3%A4iveteknologia)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/taisto.168335; https://mpkk.finna.fi/Record/taisto.168532

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [häiveteknologia](http://finto.fi/yse/fi/page/Y511494)

**Comment by mariaforsen** [comment]
Sv. smygteknik HT stealthteknik, smygteknologi 
https://www.ne.se/s%C3%B6k/?t=uppslagsverk&q=smygteknik
https://sv.wikipedia.org/wiki/Smygteknik

**Comment by mirmaid** [comment]
Melindassa muodossa häivetekniikka 14 / 26 (soto), kerran häiveteknologia. Wikipediassa otsikko on häiveteknologia, tekstissä molempia muotoja.

**Comment by nikopartanen** [comment]
YSOssa on aika paljon tapauksia, joissa _*tekniikka_ on ohjausterminä _*teknologialle_. Esim. [geeniteknologia](https://finto.fi/yso/fi/page/p17994).

**Comment by YSO-kokous** [comment]
Hyväksytään.
