### ISSUE TITLE
ebola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11496]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ebola

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9780300192216

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [ebola](http://finto.fi/yse/fi/page/Y511496)

**Comment by jtuohini** [comment]
LCSH-vastine [**Ebola virus disease**](http://id.loc.gov/authorities/subjects/sh85040654).

**Comment by mariaforsen** [comment]
Virus vai tauti? https://finto.fi/mesh/fi/page/D019142

Sv. -ebola (sjukdom) HT ebolafeber, ebolavirussjukdom
-ebolavirus HT ebola (virus)
https://mesh.kib.ki.se/term/D019142/hemorrhagic-fever-ebola
https://mesh.kib.ki.se/term/D029043/ebolavirus
https://www.sprakbruk.fi/-/ebolavirus
https://www.netdoktor.se/resemedicin-vaccin/sjukdomar/ebolafeber/
https://www.folkhalsomyndigheten.se/smittskydd-beredskap/smittsamma-sjukdomar/ebola/
https://thl.fi/sv/web/infektionssjukdomar-och-vaccinationer/sjukdomar-och-bekampning/sjukdomar-och-sjukdomsalstrare-a-o/ebola

**Comment by mirmaid** [comment]
^ Tässä muodossa (ja aineistossa) varmasti tauti, mutta Melindassa on aineistoa myös viruksesta (MeSHissä muodossa Ebolavirus-suku, https://en.wikipedia.org/wiki/Ebolavirus).

**Comment by fantsby-m** [comment]
https://thl.fi/fi/web/infektiotaudit-ja-rokotukset/taudit-ja-torjunta/taudit-ja-taudinaiheuttajat-a-o/ebola

**Comment by jarmosaarikko** [comment]
Ehdotan kahta käsitettä:
* **ebolavirukset** LT virukset 
  * closeMatch http://www.wikidata.org/entity/Q5331908 Ebolavirus
  * closeMatch http://www.yso.fi/onto/mesh/D029043 Ebolavirus-suku

* **ebolatauti**  KT ebola, ebolakuume  LT virustaudit    ; ebola feber, Ebola infection
  * exactMatch http://www.yso.fi/onto/tero/t203 Ebola
  * exactMatch http://www.yso.fi/onto/mesh/D019142 ebolatauti, (Ebola Hemorrhagic Fever; Ebola Hemorragisk feber)
  * closeMatch http://www.wikidata.org/entity/Q51993 ebola
  * closeMatch http://id.loc.gov/authorities/subjects/sh85040654 Ebola virus disease

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _ebolatauti_.
