### ISSUE TITLE
panssarintorjuntaohjukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11501]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

panssarintorjuntaohjukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Antitank missiles

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Panssarintorjuntaohjus (Pst-ohjus, Pst-ohj.) on panssaroitujen maalien tuhoamiseen tarkoitettu rakettikäyttöinen maaliin ohjattava tai itseohjautuva ase.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ohjukset](http://www.yso.fi/onto/yso/p17763)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://finto.fi/soto/fi/page/p1368), [](https://id.loc.gov/authorities/subjects/sh85005776.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.13821

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by jtuohini** [comment]
LCSH-vastine: [**Antitank missiles**](http://id.loc.gov/authorities/subjects/sh85005776).

**Comment by mariaforsen** [comment]
Sv. pansarvärnsrobotar HT pansarvärnsmissiler
https://sv.wikipedia.org/wiki/Pansarv%C3%A4rnsrobot
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/pansarv%C3%A4rnsrobot
https://www.rikstermbanken.se/search?q=Pansarv%C3%A4rnsrobot&s=termer

**Comment by mirmaid** [comment]
Melinda 294 / 40 (soto)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q282472   aliaksia mm. ATGM, ATM, anti-tank guided missile

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
