### ISSUE TITLE
irokeesikielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11507]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

irokeesikielet

**Ehdotettu termi ruotsiksi**

irokesiska språk

**Ehdotettu termi englanniksi**

Iroquoian languages

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailussa tarvitaanuutta termiä  'cherokeen kieli', mutta sen kielikuntaa ei ole vielä ysossa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kieli ja kielet](http://www.yso.fi/onto/yso/p556)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kielikunnat](http://www.yso.fi/onto/yso/p19079)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Irokeesikielet), [LCSH](https://lccn.loc.gov/sh85068259)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tarvitaan kuvailussa
Muskogean charm songs among the Oklahoma Cherokees
https://melinda.kansalliskirjasto.fi/byid/002136651

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. irokesiska språk HT irokesspråk
