### ISSUE TITLE
Haifa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11509]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Haifa

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Haifa

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Yksi suurimmista kaupungeista Israelissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Israel](http://www.yso.fi/onto/yso/p105162)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Haifa)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://piki.finna.fi/Record/piki.5206997?sid=2956675977

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto

**Comment by jtuohini** [comment]
LCNAF/LCSH-vastineet: [**Haifa (Israel)**](http://id.loc.gov/authorities/names/n79065148) ja asiasanaketjun osana [**—Israel—Haifa**](http://id.loc.gov/authorities/names/n79065148-781).
