### ISSUE TITLE
operaatiotaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11500]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

operaatiotaito

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Operational art (Military science)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Operaatiotaito on sodankäynnissä perinteisesti oppi taistelujen yhdistämisestä sotatoimen voittamiseksi. Operaatiotaito sisältää myös operaation valmistelun, joukkojen siirrot sekä operaation suorituksen. Operaatiotaito ei ole ensisijaisesti sodankäynnin taso, vaan operaation suunnittelusta vastuussa olevien tahojen älyllistä ajattelua, jossa yhdistetään taktisen tason toiminnallisuus strategisen tason visioihin. Sodankäynnin tasona operatiivinen sijoittuu taktisen ja strategisen tason väliin.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://finto.fi/soto/fi/page/p379), [](https://id.loc.gov/authorities/subjects/sh90004545.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.168652

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by jtuohini** [comment]
LCSH-vastine: [**Operational art (Military science)**](http://id.loc.gov/authorities/subjects/sh90004545).

**Comment by mariaforsen** [comment]
Sv. operationskonst (militärväsen)
https://webbokhandel.fhs.se/produkt/operationskonst/
https://id.kb.se/term/sao/Operationskonst%20%28milit%C3%A4rv%C3%A4sen%29
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/krigskonst
https://fi.wikipedia.org/wiki/Operaatiotaito

**Comment by mirmaid** [comment]
Melinda 144 / 189 (soto)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
