### ISSUE TITLE
Ilmaoperaatiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11504]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Ilmaoperaatiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

air campaign

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ilmaoperaatio koostuu yhdelle tai useammalle ilma-alukselle annetuista tehtävistä. Yhdysval-
tain Ilmavoimien ilmasodan doktriineja mukaillen operaatiot voidaan jakaa viiteen pääkatego-
riaan. Nämä kategoriat ovat: vastailmaoperaatiot, strategiset ilmaoperaatiot, vastamaaoperaa-
tiot, vastamerioperaatiot sekä tehtävää tukevat ilmaoperaatiot. https://www.doria.fi/bitstream/handle/10024/143555/SM1177.pdf?sequence=2&isAllowed=y

**Ehdotettu yläkäsite YSOssa (LT)**

 [ilmasota](http://www.yso.fi/onto/yso/p14791)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://finto.fi/soto/fi/page/p376)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.169458

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by jtuohini** [comment]
LCSH-vastineet: [**—Aerial operations**](http://id.loc.gov/authorities/subjects/sh99002242) ja [**—Aerial operations, American, [British, etc.]**](http://id.loc.gov/authorities/subjects/sh99002243) osana asiasanaketjua ("Use as a topical subdivision under individual wars").

**Comment by mariaforsen** [comment]
Sv. luftoperationer HT flygoperationer 
https://id.kb.se/term/sao/Flygoperationer
https://ilmavoimat.fi/sv/om-oss
https://ilmavoimat.fi/sv/internationell-verksamhet
https://www.forsvarsmakten.se/siteassets/4-om-myndigheten/dokumentfiler/doktriner/doktrin-for-gemensamma-operationer.pdf
http://www.diva-portal.se/smash/record.jsf?aq2=%5B%5B%5D%5D&c=395&af=%5B%22thesisLevel%3AM3%22%2C%22topOrganisationId%3A2805%22%5D&searchType=SIMPLE&sortOrder2=title_sort_asc&query=&language=sv&pid=diva2%3A328708&aq=%5B%5B%5D%5D&sf=all&aqe=%5B%5D&sortOrder=author_sort_asc&onlyFullText=false&noOfRows=50&dswid=4549

**Comment by mirmaid** [comment]
Melindassa 51 / 65 (soto)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by jtuohini** [comment]
LCSH-siltaukset uupuvat YSOsta (ks. yllä)!
