### ISSUE TITLE
Kemiallinen sodankäynti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11505]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kemiallinen sodankäynti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Chemical warfare

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Chemical warfare (CW) involves using the toxic properties of chemical substances as weapons. This type of warfare is distinct from nuclear warfare, biological warfare and radiological warfare, which together make up CBRN, the military acronym for chemical, biological, radiological, and nuclear (warfare or weapons), all of which are considered "weapons of mass destruction" (WMDs), a term that contrasts with conventional weapons.  https://en.wikipedia.org/wiki/Chemical_warfare

**Ehdotettu yläkäsite YSOssa (LT)**

 [sodankäynti](http://www.yso.fi/onto/yso/p4130)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://id.loc.gov/authorities/subjects/sh85022958.html), [](http://www.yso.fi/onto/soto/p1551)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.168941?sid=2955202932

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by jtuohini** [comment]
LCSH-vastine: [**Chemical warfare**](http://id.loc.gov/authorities/subjects/sh85022958).

**Comment by mariaforsen** [comment]
Sv. kemisk krigföring HT kemisk krigsföring, C-krigföring
https://id.kb.se/term/sao/Kemisk%20krigf%C3%B6ring
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/kemisk-krigf%C3%B6ring

**Comment by mirmaid** [comment]
Sanastossa on _kemialliset aseet_.

Melindassa 44 (ilman sanastokoodia) / 12 (soto)

**Comment by ilona-x** [comment]
> Sanastossa on kemialliset aseet.

YSOssa myös pari: biologiset aseet & biologinen sodankäynti

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
