### ISSUE TITLE
cherokeen kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11508]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

cherokeen kieli

**Ehdotettu termi ruotsiksi**

cherokesiska

**Ehdotettu termi englanniksi**

Cherokee language

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa
Huom! Erikseen ehdotettu tälle termille uutta kielikunnan yläkäsitettä 'irokeesikielet'

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

 tsalagi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Cherokeen_kieli), [LCSH](https://lccn.loc.gov/sh85023087)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Muskogean charm songs among the Oklahoma Cherokees
https://melinda.kansalliskirjasto.fi/byid/002136651

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. cherokesiska HT cherokee (språk)
https://id.kb.se/term/sao/Cherokee%20%28spr%C3%A5k%29
