### ISSUE TITLE
cherokeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11506]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

cherokeet

**Ehdotettu termi ruotsiksi**

cherokeser

**Ehdotettu termi englanniksi**

Cherokee Indians

**Tarkoitusta täsmentävä selite**

Wikipedia: Cherokeet ovat Pohjois-Amerikan asukasluvultaan suurin intiaanikansa, joka 1500-luvulla, eurooppalaisten kontaktin aikaan asutti nykyisen Yhdysvaltojen itä- ja kaakkoisosia. Myöhemmin 1800-luvulla heidät pakkosiirrettiin Ozarkin ylätasangolle, Kansasiin ja Oklahomaan. 

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [intiaanit](http://www.yso.fi/onto/yso/p646)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532), [52 Historia](http://www.yso.fi/onto/yso/p26540)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Cherokeet), [LCSH](https://lccn.loc.gov/sh85023080)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Friends of thunder : folktales of the Oklahoma Cherokees
https://melinda.kansalliskirjasto.fi/byid/018783231

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. cherokeser /sao, ne HT cherokee (folk), cherokee-indianer, cherokeeindianer
