### ISSUE TITLE
panssarihaupitsit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11515]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

panssarihaupitsit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

self-propelled howitzers

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Panssarihaupitsi on telatykki, jonka miehistö on tulitoiminnan aikana suojassa, ja jonka putken pituus on 12–20 kertaa putken kaliiperi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tykit](http://www.yso.fi/onto/yso/p2312)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [panssarivaunut](http://www.yso.fi/onto/yso/p9333)

**Vastaava käsite muussa sanastossa**

 [SOTO](https://finto.fi/soto/fi/page/p1435), [Wikidata](https://www.wikidata.org/wiki/Q63214752)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.145162?sid=2937489453

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [panssarihaupitsit](http://finto.fi/yse/fi/page/Y511515)

**Comment by mirmaid** [comment]
11 kertaa Melindassa SOTO-terminä, muutamia kertoja vapaana avainsanana.

**Comment by mariaforsen** [comment]
Sv. pansarhaubitsar HT pansarhaubitser
https://www.defmin.fi/sv/aktuellt/pressmeddelanden_och_nyheter/nyhetsarkiv/2021/forsvarsmakten_loser_in_optionen_pa_pansarhaubitsar_med_kalibern_155_millimeter.12196.news#454260c1
https://svenska.yle.fi/a/7-1165867
https://maavoimat.fi/sv/-/maavoimien-tykistokaluston-uusiminen-etenee

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
