### ISSUE TITLE
oksalaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11512]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

oksalaatit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9780593139585

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [oksalaatit](http://finto.fi/yse/fi/page/Y511512)

**Comment by ilona-x** [comment]
LCSH: Oxalates http://id.loc.gov/authorities/subjects/sh87000414

FinMeSH: oksalaatit http://www.yso.fi/onto/mesh/D010070

https://en.wikipedia.org/wiki/Oxalate

**Comment by mariaforsen** [comment]
Sv. oxalater
