### ISSUE TITLE
instrumentalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11514]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[instrumentalismi](http://www.yso.fi/onto/yso/p5765)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö lisätä sulkutarkenne? Esim. instrumentalismi (filosofia)?

**Perustelut ehdotukselle**

Ei toistaiseksi käytetty väärin (eli musiikkikontekstissa) kuvailussa, ainakaan Melindassa, mutta riski on olemassa. 
Vrt. "Ryynäsen vahva instrumentalismi ja vavahduttava läsnäolo.." https://musiikkitalo.fi/tapahtumat/hanna-ryynanen-saarijarven-kantele/
"Narsistinen instrumentalismi on musiikin sudenkuoppa.."
https://ylioppilaslehti.fi/2002/09/kaikki-soittaa-kaikkien-kaa/
Erityisesti termiä multi-instrumentalismi näkee:
"Multi-instrumentalismi on harvemmin tutkittu aihealue..."
https://taju.uniarts.fi/handle/10024/7338
"Multi-instrumentalismi on ihanne.."
https://www.ku.fi/artikkeli/3869634-kanteletaiteilija-maija-kauhanen-olen-onnekas-jos-tekstini-koskettavat-ihmisia

Vrt. instrumentalisti. Tälle sanalle esim. Kielitoimiston sanakirja antaa vain musiikkimerkityksen.

**Ehdottajan organisaatio**

Finto / Tuomas

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
