### ISSUE TITLE
esikunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11516]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

esikunnat

**Ehdotettu termi ruotsiksi**

staber

**Ehdotettu termi englanniksi**

staff (military)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Komentajan lähimpänä apuna toimiva sotilashenkilöstö, keskeinen organisaatiokäsite.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85007318.html), [Wikipedia](https://fi.wikipedia.org/wiki/Esikunta)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.102132?sid=2960516310

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [esikunnat](http://finto.fi/yse/fi/page/Y511516)

**Comment by jtuohini** [comment]
Varmaan LCSH-siltaus lisäksi myös asiasanaan [**Staffs**](http://id.loc.gov/authorities/subjects/sh99005748), jonka käyttöohjeena on "Use as a topical subdivision under military services"?

**Comment by mariaforsen** [comment]
Mahdollisesti monimerkityksinen? https://oikeusministerio.fi/esikunta

Sv. staber (militära organisationer) HT militära staber, militärstaber
sök/?t=uppslagsverk&q=stab
https://svenska.se/tre/?sok=stab&pz=1
https://oikeusministerio.fi/sv/stab
https://sv.wikipedia.org/wiki/Stab
https://fho.sls.fi/uppslagsord/1125/stab/

**Comment by ilona-x** [comment]
SOTO:
**esikunnat** http://www.yso.fi/onto/soto/p1519
(yläkäsite sotilashenkilöstö)

**Comment by tpalonen** [comment]
On monimerkityksinen ja vaatii tarkenteen, jos halutaan rajata sotilaskäyttöön. Esimerkiksi eri ministeriöillä, hätäkeskuksilla ja Verohallinnolla on esikunta. Rajavartiolaitoksen esikunta lienee rajatapaus (ehhehe).

_esikunnat (sotilaalliset organisaatiot)_ ?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _esikunnat (sotilaalliset organisaatiot)_.
