### ISSUE TITLE
magnetiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11518]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

magnetiitti

**Ehdotettu termi ruotsiksi**

magnetit

**Ehdotettu termi englanniksi**

magnetite

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 18

**Ehdotettu yläkäsite YSOssa (LT)**

 [rautamalmit](http://www.yso.fi/onto/yso/p12443)

**Ehdotetut temaattiset ryhmät**

 [11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikidata](http://www.wikidata.org/entity/Q181395), [LCSH](http://id.loc.gov/authorities/subjects/sh85079771), [GEO](http://www.yso.fi/onto/gtk/GTK2015ID2242)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Dissolution of magnetite and hematite in acid mixtures https://urn.fi/URN:ISBN:978-952-335-875-1

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [magnetiitti](http://finto.fi/yse/fi/page/Y511518)

**Comment by mariaforsen** [comment]
Sv. magnetit HT svartmalm (magnetit)
