### ISSUE TITLE
sotilaallinen yhteistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11517]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sotilaallinen yhteistyö](http://www.yso.fi/onto/yso/p17552)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermi: puolustusyhteistyö

**Perustelut ehdotukselle**

yleisesti käytetty termi, joka viittaa samaan asiaan

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu

**Comment by mariaforsen** [comment]
Sv. försvarssamarbete
