### ISSUE TITLE
oksaalihappo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11513]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

oksaalihappo

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9780593139585

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [oksaalihappo](http://finto.fi/yse/fi/page/Y511513)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D019815

https://fi.wikipedia.org/wiki/Oksaalihappo

**Comment by mariaforsen** [comment]
Sv. oxalsyra
