### ISSUE TITLE
yksinvalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11527]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yksinvalta](http://www.yso.fi/onto/yso/p8525)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan suhteessa käsitteeseen itsevaltius. Tutkitaan myös ohjaustermit (lisätään myös despotia, absolutismi?)

**Perustelut ehdotukselle**

Vaikuttavat päällekkäisiltä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
yksinvalta: monarkia, yksinvaltius; harv. itsevaltius, diktatuuri.
itsevaltius: rajaton yksinvalta, itsevalta(isuus), despotismi, diktatuuri.
absolutismi: 2. itsevaltius.

**Comment by mirmaid** [comment]
Wikipediassa eri kielet eroavat siinä, määritelläänkö yksinvalta/autokratia vain yhden henkilön vallaksi vai voiko kyseessä olla myös ryhmä, esim. puolue.

**Comment by mariaforsen** [comment]
Sv. autokrati voi myös viitata ryhmän valtaan. Envälde (yksinvalta) vain yhden henkilön.

**Comment by mirmaid** [comment]
Suomeksi ehkä voi puhua puolueen yksinvallasta, mutta sekä itsevaltius että yksinvalta kyllä varmaan useimmiten mielletään yhden henkilön vallaksi. Mutta luulen että menevät muutenkin sekaisin, kun ero on vain yksinvalta/rajaton yksinvalta.
