### ISSUE TITLE
kameet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11523]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kameet

**Ehdotettu termi ruotsiksi**

Kaméer

**Ehdotettu termi englanniksi**

Cameos

**Tarkoitusta täsmentävä selite**

Kamee (ransk. camée) on korukivestä, simpukankuoresta tai sarvesta kaiverrettu reliefi, jota käytetään yleensä rintakoruna. Tavallisesti kamee valmistetaan korukivestä, kuten akaatista tai onyksistä, jossa on erilaisia ohuita värikerrostumia. Tummempi kerros muodostaa taustan, ja varsinainen kohokuvio kaiverretaan vaaleampaan kerrokseen. (wikipedia)

**Perustelut ehdotukselle**

Melindassa 17

**Ehdotettu yläkäsite YSOssa (LT)**

 [korut](http://www.yso.fi/onto/yso/p10789)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 kameekorut

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/Kam%C3%A9er), [LCSH](https://id.loc.gov/authorities/subjects/sh85019125.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9921046913506253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [kameet](http://finto.fi/yse/fi/page/Y511523)

**Comment by ilona-x** [comment]
MAO: kameet http://www.yso.fi/onto/mao/p4286

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. kaméer HT kamésmycken
