### ISSUE TITLE
nuolenkärjet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11528]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nuolenkärjet

**Ehdotettu termi ruotsiksi**

Pilspetsar

**Ehdotettu termi englanniksi**

Arrowheads

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa nuolenkärjet 17 kertaa

**Ehdotettu yläkäsite YSOssa (LT)**

 [nuolet](http://www.yso.fi/onto/yso/p23064)

**Ehdotetut temaattiset ryhmät**

 [51 Arkeologia](http://www.yso.fi/onto/yso/p26593)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/Pilspetsar), [LCSH](https://id.loc.gov/authorities/subjects/sh85007439.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9934036875906253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [nuolenkärjet](http://finto.fi/yse/fi/page/Y511528)

**Comment by ilona-x** [comment]
MAO: nuolenkärjet http://www.yso.fi/onto/mao/p5659

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
