### ISSUE TITLE
morsiuskruunut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11522]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

morsiuskruunut

**Ehdotettu termi ruotsiksi**

Brudkronor

**Ehdotettu termi englanniksi**

Bridal crowns

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa 7 morsiuskruunua

**Ehdotettu yläkäsite YSOssa (LT)**

 [kruunut](http://www.yso.fi/onto/yso/p19933), [korut](http://www.yso.fi/onto/yso/p10789)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [hääpuvut](http://www.yso.fi/onto/yso/p10635)

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/Brudkronor), [LCSH](https://id.loc.gov/authorities/subjects/sh85016813.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9924160733506253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [morsiuskruunut](http://finto.fi/yse/fi/page/Y511522)

**Comment by ilona-x** [comment]
MAO: **morsiuskruunut** http://www.yso.fi/onto/mao/p1647

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
