### ISSUE TITLE
siviili-sotilassuhteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11520]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

siviili-sotilassuhteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Civil-military relations

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuten Oxford research encyclopediassa (https://doi.org/10.1093/acrefore/9780190846626.013.123) todetaan, siviili-sotilassuhteita on tutkittu 1940-luvun lopulta alkaen. Kirjallisuutta on runsaasti ja myös suomenkieliset tutkijat ovat vakiinnuttaneet vastaavan suomenkielisen termin.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85026352.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.016637572

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [siviili-sotilassuhteet](http://finto.fi/yse/fi/page/Y511520)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. civil-militära relationer (militärpolitik)
https://www.fhs.se/utbildningar/civil-militara-relationer.html
https://fhs.diva-portal.org/smash/record.jsf?pid=diva2%3A1672342&dswid=-7131
https://www.raddabarnen.se/vad-vi-gor/trygghet/CivMil/
https://kkrva.se/hot/2015:3/westberg_triangelns.pdf
SAO > https://id.kb.se/term/sao/Milit%C3%A4ren%20och%20samh%C3%A4llet

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään ensi kokoukseen. Mietitään sopivaa tarkennetta.

**Comment by mirmaid** [comment]
Voisiko tähän saada Maanpuolustuskorkeakoululta ihan jonkun selkeän määritelmän? Löytämissäni lähteissä määrittely on sen verran rivien välissä, että en niiden pohjalta uskalla sanoa, mikä olisi sulkutarkenne. Sanastossa on jo _yhteiskuntasuhteet_, mutta jos tämä rajautuu jotenkin tarkasti poliittiseen päätöksentekoon (?), tarkenne olisi varmaan ennemmin (sotilaspolitiikka) tai (puolustuspolitiikka). Toisaalta sitten herää kysymys, riittäisikö kuvailussa esim. pelkkä sotilaspolitiikka, mutta varmaan pohdintaa helpottaisi, jos löytyisi jokin selkeä määritelmä tälle käsitteelle.

**Comment by tapiopitkaranta** [comment]
Saimme professorilta lausunnon asiaan: "Civil-military relations teoria ja tutkimus eivät ole Suomessa kovin vakiintuneita käsitteitä. Kansainvälisesti tämä amerikkalaislähtöinen tutkimushaara sen sijaan on hyvinkin vakiintunut. Sillä ei kuitenkaan yleensä viitata laajasti asevoimien ja siviiliyhteiskunnan vuorovaikutukseen, vaan erityisesti seuraavaan problematiikkaan: Miten asevoimat voivat kehittyä itsenäisenä instituutiona ja osaamisalueena (professiona) mahdollisimman vapaasti niin, että ympäröivä yhteiskunta säilyttää kuitenkin asevoimien kontrollin? Useimmiten keskiössä ovat länsimaiset demokratiat ja asevoimien parlamentaarinen kontrolli, joskus politiikan militarisoituminen tai sotilasvallankaappaukset."

Kuvailun kohteena on meillä enimmäkseen juuri kansainvälinen aineisto. Tarkenne (sotilaspolitiikka) sopisi mielestäni hyvin tähän määritelmään.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _siviili-sotilassuhteet (sotilaspolitiikka)_.
