### ISSUE TITLE
taskukellot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11521]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taskukellot

**Ehdotettu termi ruotsiksi**

fickur

**Ehdotettu termi englanniksi**

pocket watches

**Tarkoitusta täsmentävä selite**

ajanottolaitteet

**Perustelut ehdotukselle**

25 osumaa Melindassa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kellot](http://www.yso.fi/onto/yso/p3229)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85103655.html), [SAO](https://id.kb.se/find?q=fickur)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9928342053506253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [taskukellot](http://finto.fi/yse/fi/page/Y511521)

**Comment by mariaforsen** [comment]
Sv. fickur HT fickklockor

**Comment by ilona-x** [comment]
MAO:
**taskukellot** http://www.yso.fi/onto/mao/p2617

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
