### ISSUE TITLE
Meksiko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11534]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Meksiko](http://www.yso.fi/onto/yso/p105032)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään viittausmuoto "Meksikko"

**Perustelut ehdotukselle**

Aiemmin paljon käytetty, nyttemmin harvakseltaan: Kansalliskirjaston digitoimissa kausijulkaisuissa yli 7 000 osumaa, joista uusin käyttötapaus vuodelta 2020.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Tarkistetaan löytyykö muotoa hakuteoksista - toistaiseksi ei ole mahdollisuutta osoittaa termimuodon olevan vanhentunut tai virheellinen.

**Comment by mirmaid** [comment]
Lisätty.
