### ISSUE TITLE
ihmeparannus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11530]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ihmeparannus](http://www.yso.fi/onto/yso/p16304)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdottaisin, että sana henkiparannus otettaisiin asiasanaksi, tai vähintään ohjattaisiin käyttämään asiasanaa healing nykyisen ihmeparannuksen sijaan. 

**Perustelut ehdotukselle**

Henkiparantamisessa tai healingissa sairaudesta parantumista ei välttämättä tapahdu, tai sitä ei edes hoitaessa odoteta, mutta oloon ja tilanteeseen voi saada helpotusta. Ihmeparannus on eri asia ja käsitteenä kuvaa sitä, että parannustapahtumassa sairaus paranee ikään kuin ihmetekona. Terkuin healingia eli henkiparannusta tekevä kirjastovirkailija, joka ei todellakaan tarjoa ihmeparannusta

**Ehdottajan organisaatio**

**Comment by krinay** [comment]
Kannatan termin henkiparannus ottamista varsinaiseksi asiasanaksi (ihmeparannus ohjaustermiksi). 

LCSH:
**Spiritual healing**
_Variants_
Divine healing
Faith-cure
Faith healing
Spiritual therapies
_Broader Terms_
Healing--Religious aspects

https://id.loc.gov/authorities/subjects/sh85126755.html

**Comment by mirmaid** [comment]
Eli tässä pää- ja ohjaustermi vaihtuisivat päittäin.

**Comment by mariaforsen** [comment]
Nämä eivät välttämättä ole aina sama asia (kuten ilmenee ehdottajan tekstistäkin): 
https://www.kielitoimistonsanakirja.fi/#/henkiparannus?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/ihmeparannus?searchMode=all 
https://www.sanakirja.fi/custom/en-sv-fi/henkiparannus
https://www.sanakirja.fi/custom/en-sv-fi/ihmeparannus
https://www.henkinenkehitys.fi/henkisetlahjat/henkiparannus
https://fi.wikipedia.org/wiki/Henkiparannus
https://kaino.kotus.fi/suomi-ruotsi/?p=article&suru_id=SURU_cd848cc001addb6bd63ea97fd15fb0ed&word=ihmeparannus&list_id=17839
Eli riippuu myös mitä ihmeparannuksella tarkoitetaan... 
SAOssa kaksi eri termiä: helbrägdagörelse ja healing.

**Comment by krinay** [comment]
Eivät ole sama asia. Esimerkiksi skepsiksen sivulla (https://www.skepsis.fi/ihmeellinen/henkiparannus.html) sanotaan näin:

"Henkiparannuksen erottaa ihmeparantamisesta jumaluuden mukanaolo: henkiparannuksessa sellainen toimii korkeintaan vain taustalla, ihmeparantamisessa jumaluus on aktiivisesti mukana parantamisessa. Tämä ei yleensä tarkoita, että henkiparantaja kokisi olevansa parantamisen lähde, sillä hän toimii ainoastaan ”energioita tasapainottaen” tms. Henki- ja ihmeparantamisen voisikin erottaa magian ja taikauskon avulla: henkiparantaminen on maagista, ihmeparantaminen taikauskoista parantamista."

Mutta pahoin pelkään, ettei suomenkielisiä termejä _henkiparannus_ ja _ihmeparannus_ pystyttäisi käyttämään kovin johdonmukaisesti, jos molemmat olisivat käytettävissä. Pitäisi varmaan käytännössä aina hakea kummallakin asiasanalla. _Parantaminen (terveys)_ on YSOssa ja viittaa kaikenlaiseen parantamiseen, ei erityisesti henkiseen.

LCSH:ssa varsinaisena asiasanana on siis _Spiritual healing_ (henkiparannus) (RT miracles) ja sen ohjaustermeinä mm. _Faith healing_ ja _Divine healing_ (joka voisi ehkä olla suomeksi ihmeparannus).

**Comment by YSO-kokous** [comment]
**Päätös**

Päätermiksi _henkiparannus_, _ihmeparannus_ ohjaustermiksi.

**Comment by mariaforsen** [comment]
Sv.
-helbrägdagörelse > healing

https://www.kielitoimistonsanakirja.fi/#/henkiparannus?searchMode=all
https://www.sanakirja.fi/custom/en-sv-fi/henkiparannus
https://www.henkinenkehitys.fi/henkisetlahjat/henkiparannus
https://fi.wikipedia.org/wiki/Henkiparannus
https://sv.wikipedia.org/wiki/Healing
https://id.kb.se/term/sao/Healing 
https://paranormal.se/topic/helande.html
https://mesh.kib.ki.se/term/D008602/mental-healing
https://mesh.kib.ki.se/term/D029221/faith-healing
https://mesh.kib.ki.se/term/D026443
https://www.psykologiguiden.se/psykologilexikon/?Lookup=sj%C3%A4lslig+behandling
https://www.psykologiguiden.se/psykologilexikon/?Lookup=mental%20healing
wp: "Helande eller helbrägdagörelse innebär i traditionell bemärkelse detsamma som botande av sjukdomar genom tro. Det brukar dock avse botande på övernaturlig väg, det vill säga en typ av under. Det nyare begreppet healing är kopplad till alternativmedicin och dess verksamhet."
ne: "helbrägdagörelse, botande av sjukdomar på övernaturlig väg."

-helande > helande (hälsoförbättring) HT hälsoförbättring, läkande, läkande och botande, botande
https://finto.fi/yso/fi/page/p425?clang=sv 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_327d818f3191c1d555c819892e29301a&list_id=1&keyword=parantaa&word=parantaa
https://www.sanakirja.fi/custom/en-sv-fi/parantaminen
https://svenska.se/tre/?sok=l%C3%A4ka&pz=1 
https://svenska.se/tre/?sok=bota&pz=8 
https://www.sanakirja.fi/custom/en-sv-fi/l%C3%A4ka
https://www.sanakirja.fi/custom/en-sv-fi/bota
https://erepo.uef.fi/handle/123456789/28770
https://melinda.kansalliskirjasto.fi/F/KN8S7EXG14Q6S72LH1LKNDTFVE6H8UA2XSSURS91D5M4SFN25A-01176?func=scan&scan_start=parantaminen+%28terveys%29&scan_code=SUB&x=37&y=13
ne: helande, se healing
