### ISSUE TITLE
resitatiivit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11532]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[resitatiivit](http://www.yso.fi/onto/yso/p25250)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tämä nyt liian suppeasti tulkittu? 

**Perustelut ehdotukselle**

https://www.ortodoksi.net/index.php/Resitatiivi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Jos myös uskonnollinen, pitäisi olla myös RT kantillaatio.

**Comment by jtuohini** [comment]
Ei ole liian suppeasti tulkittu: resitatiivit teoksina (tai paremminkin teoksen osina) eivät ole suhteessa kantillointiin, mutta resitointi eli puhelaulaminen on, ja näiden väliltä RT-suhde YSO:sta jo löytyy. Ortodoksisen liturgian puhelaulaen esitetystä ohjelmistosta/teoksista/liturgiasta taas käytetään **ortodoksinen kirkkomusiikki**- tai **bysanttilainen kirkkomusiikki** -asiasanaa, ei missään nimessä **resitatiivit**-asiasanaa.

**Comment by MUUSA-kokous** [comment]
Ei nähdä tarvetta muutoksille.

**Comment by mirmaid** [comment]
The term recitative (or occasionally liturgical recitative) is also applied to the simpler formulas of Gregorian chant, such as the tones used for the epistle, gospel, preface and collects; see accentus. https://en.wikipedia.org/wiki/Recitative

https://melinda.kansalliskirjasto.fi/byid/002559780

Viitteitä Melindassa vain 7, joten ei liene suurta vahinkoa vaikka joskus käytettäisiin myös uskonnollisesta musiikista.

**Comment by YSO-kokous** [comment]
**Päätös**

Tarkistetaan määritelmät.
