### ISSUE TITLE
soolosävellykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11536]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[soolosävellykset](http://www.yso.fi/onto/yso/p8463)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM-sanastoon: olisiko termi mahdollista muuttaa esim. muotoon "soolomusiikki"?

**Perustelut ehdotukselle**

"Soolomusiikki" sopisi paremmin kuvailemaan myös sovitusten esityskokoonpanoja. 

**Ehdottajan organisaatio**

Taideyliopiston kirjasto

**Comment by jtuohini** [comment]
Jos laulumusiikissa käytetään pääsääntöisesti teoksen muotoa kuvaavaa SLM-termiä, esim. **kansanlaulut** ja **vokaliisit (laulut)**, onko nykyinen **soolosävellykset** erityisesti tarkemman muotoa kuvaavan termin ulottumattomissa olevaa soitinmusiikkia kuvaava termi? Jos on, kävisikö termin uudeksi muodoksi _**soolosoitinmusiikki**_? Kattaisi sekä alkuperäiskokoonpanoiset teokset että sovitukset, mutta rajautuisi soitinmusiikkiin.

**Comment by MUUSA-kokous** [comment]
Kannatetaan termin muuttamista muotoon _soolosoitinmusiikki._

**Comment by YSO-kokous** [comment]
**Päätös**

Odotetaan SLM-ryhmän kantaa.

**Comment by tpalonen** [comment]
Soolosävellykset jäänee kuitenkin ohjaustermiksi?

**Comment by mariaforsen** [comment]
Sv. "soloinstrumentalmusik"? Ei oikein löydy mitään, mutta toisaalta ei myöskään ""soolosoitinmusiikki" juuri löydy googlesta.

**Comment by mirmaid** [comment]
Hyväksytty muodossa soolomusiikki KT soolosävellykset (YK musiikki).

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Sv. solomusik HT solokompositioner

**Comment by YSO-kokous** [comment]
**Päätös**

Muusa tarkastelee vielä hierarkian kannalta.

**Comment by mirmaid** [comment]
Hyväksytään muutos YSOon, hierarkia säilyy entisellään.
