### ISSUE TITLE
säteilyvalvonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11535]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

säteilyvalvonta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. 30 kertaa Melindassa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ympäristövalvonta](http://www.yso.fi/onto/yso/p12002)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 ympäristön säteilyvalvonta

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [säteilyturvallisuus](http://www.yso.fi/onto/yso/p14081)

**Vastaava käsite muussa sanastossa**

 [LCSH (close match?)](https://id.loc.gov/authorities/subjects/sh86006811.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtakunnallisen säteilyvalvonnan kehittyminen Suomessa 

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [säteilyvalvonta](http://finto.fi/yse/fi/page/Y511535)

**Comment by jtuohini** [comment]
Vai LCSH-siltaus sittenkin seuraavaan neljään, joiden kaikkien viittausmuotona _Radiation monitoring_: **Radiation dosimetry**, **Radiation--Measurement**, **Radiation--Safety measures** ja **Radioactivity--Measurement**? Näistä kolmannella on lisäksi KT-muotona _Radiation protection_.

**Comment by mariaforsen** [comment]
Sv. strålningsövervakning HT strålningsbevakning
https://termipankki.fi/tepa/fi/haku/s%C3%A4teilyvalvonta

**Comment by ilona-x** [comment]
FinMeSH:
**säteilyn seuranta** http://www.yso.fi/onto/mesh/D011834
Ohjaustermit
    säteilyn monitorointi
    säteilyn tarkkailu
    säteilyn valvonta
    säteilytarkkailu
    säteilyvalvonta

**Comment by fantsby-m** [comment]
https://stuk.fi/ympariston-sateilyvalvonta

**Comment by mariaforsen** [comment]
Voisiko säteilyn seuranta olla ohjaustermi? Molemmat sv. strålningsövervakning

**Comment by mirmaid** [comment]
^ Mielestäni hyvin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
