### ISSUE TITLE
G-proteiinikytkentäiset reseptorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11537]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

G-proteiinikytkentäiset reseptorit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://trepo.tuni.fi/handle/10024/143874

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [G-proteiinikytkentäiset reseptorit](http://finto.fi/yse/fi/page/Y511537)

**Comment by ilona-x** [comment]
FinMeSHistä löytyy **G-proteiiniin kytketyt reseptorit** http://www.yso.fi/onto/mesh/D043562

**Comment by mariaforsen** [comment]
Sv. G-proteinkopplade receptorer HT GPCR
/uppslagsverk/encyklopedi/lång/g-proteinkopplade-receptorer
https://sv.wikipedia.org/wiki/G-proteinkopplade_receptorer
