### ISSUE TITLE
uskontoon liittyvät abstraktit objektit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11533]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[uskontoon liittyvät abstraktit objektit](http://www.yso.fi/onto/yso/p38222)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan päätermi muotoon uskomusjärjestelmiin liittyvät abstraktit objektit

**Perustelut ehdotukselle**

Olisi tässä muodossa hieman kattavampi eli sisältäisi edelleen myös uskontoon liittyvät objektit, mutta myös hieman laajemmin ja sallivammin. YSOssahan on uskomusjärjestelmät-käsite, jonka alla on käsite uskonto ja uskonnot. Jos termi olisi "uskomusjärjestelmiin liittyvät abstraktit objektit", sen alle voisi siirtää esim. horoskoopit, ennustukset (magia) ja yliluonnolliset olennot alakäsitteineen. Nyt nämä ovat likeisiä uskonnollisille objekteille, mutta eivät ehkä kaikkien mielestä täytä uskonnollisen objektin kriteereitä.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by ilona-x** [comment]
Tässä siis kyseessä hierarkisoiva käsite, jota ei ole tarkoitettu käytettäväksi kuvailussa.
