### ISSUE TITLE
matstrupsinflammation

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11549]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[matstrupsinflammation](http://www.yso.fi/onto/yso/p10776)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

siirretäänkö OT refluksiesofagiitti KÄYTÄ refluksitauti?

**Perustelut ehdotukselle**

Tässä näyttää olevan jonkinlainen sekaannus, koska sanastossa on myös refluksitauti
https://www.terveyskirjasto.fi/ltt02889/refluksitauti 
Todettu Wikidatalinkitys-kokouksessa

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Tälle olisi oikeastaan kaksi eri ala-käsitettä: https://finto.fi/mesh/fi/page/D004941 YSOsta puuttuu eosinofiilinen ruokatorvitulehdus
https://www.iltalehti.fi/terveysuutiset/a/296cfba1-3f15-4cb8-8436-c37f719ddef0

**Comment by mariaforsen** [comment]
Ehdotan vielä lisättäväksi OT esofagiitti (kuten myös Meshissä)
https://fi.wikipedia.org/wiki/Esofagiitti

**Comment by tpalonen** [comment]
Refluksitauti ja ruokatorventulehdus ovat tosiaan YSOssa erikseen. Refluksiesofagiitti-termi ohjaa nyt ruokatorventulehdukseen, mikä on väärin, kuten Maria tuossa toteaa. 

MeSHissä on refluksiesofagiitti KÄYTÄ refluksitauti.
Ja MeSHissä, toisin kuin YSOssa, refluksitauti on ruokatorvitulehduksen alakäsite.
Ks. http://www.yso.fi/onto/mesh/D004942

Kannatan myös Marian ehdotusta esofagiitti KÄYTÄ ruokatorvitulehdus. Vrt. vastaavan Wikipedia-artikkelin nimi on suomeksi esofagiitti. https://fi.wikipedia.org/wiki/Esofagiitti
