### ISSUE TITLE
hengityshäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11541]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hengityshäiriöt

**Ehdotettu termi ruotsiksi**

andningsstörningar

**Ehdotettu termi englanniksi**

respiration disorders

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 5 (FinMeSH)

**Ehdotettu yläkäsite YSOssa (LT)**

 [hengityselinten taudit](http://www.yso.fi/onto/yso/p2304)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D012120)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sleep and Breathing in Preterm Infants : Polysomnography Studies on the Effects of Caffeine and Supplemental Oxygen http://urn.fi/URN:ISBN:978-951-51-8502-0

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [hengityshäiriöt](http://finto.fi/yse/fi/page/Y511541)

**Comment by mariaforsen** [comment]
Sv. andningsstörningar HT andningssvårigheter, respiratoriska störningar
https://mesh.kib.ki.se/term/D012120/respiration-disorders
