### ISSUE TITLE
ennenaikainen murrosikä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11540]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ennenaikainen murrosikä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

precocious puberty

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 11

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh89003319), [Wikidata](http://www.wikidata.org/entity/Q224513)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Molecular Genetics of Rare Growth and Puberty Disorders in Finland

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [ennenaikainen murrosikä](http://finto.fi/yse/fi/page/Y511540)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D011629

**Comment by mariaforsen** [comment]
Sv. för tidig pubertet HT pubertas praecox, förtidig pubertet
https://sv.wikipedia.org/wiki/F%C3%B6r_tidig_pubertet
https://mesh.kib.ki.se/term/D011629/puberty-precocious
https://medibas.se/handboken/kliniska-kapitel/pediatrik/tillstand-och-sjukdomar/utvecklingshamning/pubertet-for-tidig

**Comment by tpalonen** [comment]
Nyt sanastossa on
esimurrosikä KÄYTÄ murrosikä
Pitäisikö olla myös?
esimurrosikä KÄYTÄ ennenaikainen murrosikä

**Comment by mirmaid** [comment]
^ Esimurrosikä on ihan normaali kehitysvaihe, eli ei ole ennenaikainen.
