### ISSUE TITLE
Friuli-Venezia Giulia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11543]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Friuli-Venezia Giulia

**Ehdotettu termi ruotsiksi**

Friuli-Venezia Giulia

**Ehdotettu termi englanniksi**

Friuli Venezia Giulia

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Friuli-Venezia Giulia on itsehallinnollinen alue Koillis-Italiassa. Termiä tarvittaisiin esim. alueelle sijoittuvan kirjallisuuden ja aluetta käsittelevien matkaoppaiden kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

matkaoppaat

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Friuli-Venezia_Giulia
