### ISSUE TITLE
lyydian kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11542]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lyydian kieli

**Ehdotettu termi ruotsiksi**

lydiska ?

**Ehdotettu termi englanniksi**

Lydian

**Tarkoitusta täsmentävä selite**

Tarkempi yläkäsite olisi anatolialaiset kielet

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [indoeurooppalaiset kielet](http://www.yso.fi/onto/yso/p3045)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Lexvo](https://finto.fi/lexvo/fi/page/xld), [LCSH](https://id.loc.gov/authorities/subjects/sh85079103.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The mummy of Zagreb and other Etruscan, Lydian and Lycian written monuments / S.S. Bilbija.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lyydian kieli](http://finto.fi/yse/fi/page/Y511542)

**Comment by mirmaid** [comment]
Toinen YK muinaiskielet.

**Comment by mariaforsen** [comment]
Sv. lydiska
https://id.kb.se/term/sao/Lydiska
