### ISSUE TITLE
mehiläissyöjä (laji)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11545]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mehiläissyöjä (laji)

**Ehdotettu termi ruotsiksi**

biätare

**Ehdotettu termi englanniksi**

European Bee-eater

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailutarve

**Ehdotettu yläkäsite YSOssa (LT)**

 [mehiläissyöjät](http://www.yso.fi/onto/yso/p7164)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 Merops apiaster

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Laji.fi](https://laji.fi/taxon/MX.29998), [Wikipedia](https://fi.wikipedia.org/wiki/Mehil%C3%A4issy%C3%B6j%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Artikkeli

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [mehiläissyöjä (laji)](http://finto.fi/yse/fi/page/Y511545)

**Comment by mirmaid** [comment]
Jos tämä otetaan, _mehiläissyöjät_-käsitteelle lisättävä tarkenne (suku) tai (heimo).

**Comment by mariaforsen** [comment]
Sv. biätare (art)
