### ISSUE TITLE
multimodaalinen kuvantaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11547]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

multimodaalinen kuvantaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

multimodal imaging

**Tarkoitusta täsmentävä selite**

 Eri kuvantamismuotoja yhdistävä kuvantamismenetelmä https://uefconnect.uef.fi/tutkimusryhma/lisaarvoa-kuvantamisesta-petmri-terveys-ja-hyvinvointiteknologian-kehitysalustana-kehitys/

**Perustelut ehdotukselle**

Tarvittu sisällönkuvailussa, puuttuu YSOsta. Melindassa käytetty vapaana asiasanana sekä FinMeSH -asiasanana.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kuvantaminen](http://www.yso.fi/onto/yso/p3532)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 hybrid imaging

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH/FinMeSH](http://multimodaalinen kuvantaminen)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018780482 ja 
https://melinda.kansalliskirjasto.fi/byid/018780675

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [multimodaalinen kuvantaminen](http://finto.fi/yse/fi/page/Y511547)

**Comment by mirmaid** [comment]
Yhteensä 4 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. multimodal avbildning /mesh

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
