### ISSUE TITLE
sampi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11546]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sampi](http://www.yso.fi/onto/yso/p25369)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

päätermiksi euroopansampi

**Perustelut ehdotukselle**

"Aikaisemmin sampena tunnettu kala (Acipencer sturio) on tästä eteenpäin suomeksi euroopansampi." 
Lähde: https://www.hs.fi/kotimaa/art-2000009612720.html

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
https://laji.fi/taxon/MX.53293

**Comment by mariaforsen** [comment]
Sv. -europeisk stör /ne, wp  HT stör (europeisk)
https://namnochslaktskap.artfakta.se/taxa/249905/details
-atlantstör HT atlantisk stör, stör (atlantisk), amerikansk atlantstör /ne
https://laji.fi/taxon/MX.206815
https://namnochslaktskap.artfakta.se/taxa/100002/details
https://www.dyntaxa.se/Taxon/Info/100002
https://www.havochvatten.se/arter-och-livsmiljoer/arter-och-naturtyper/atlantstor-och-europeisk-stor.html

**Comment by mariaforsen** [comment]
Pitäisikö samalla ottaa toisen artikkelissa mainitun sammen nimi mukaan, eli sinisampi OT atlantinsampi?

"Sinisammeksi aikaisemmin kutsuttu kala (Acipenser oxyrinchus) on puolestaan jatkossa atlantinsampi."
Ainakin ruotsiksi tuo stör on voinut viitata myös siihen, ja aineistoa taitaa löytyä. 

https://laji.fi/taxon/MX.206815
