### ISSUE TITLE
aseveljeys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1154]
#### Ehdotettu termi suomeksi

aseveljeys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/ysa/ryhma_67)

**Luontipäivämäärä:** 15.10.2004

**Muokkauspäivämäärä:** 15.10.2004, 16.12.2008, 1.4.2009, 16.12.2010, 16.12.2010

**Voyager-id:** 133827

**Termiehdotus Fintossa:** [aseveljeys](http://finto.fi/yse/fi/page/Y333827)

**Comment by henriyli** [comment]
YSAan 14.1.2016 http://www.yso.fi/onto/ysa/Y206854
