### ISSUE TITLE
tykit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11548]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tykit](http://www.yso.fi/onto/yso/p2312)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

uusi OT kanuunat

**Perustelut ehdotukselle**

eräänlainen tykki 
https://www.kielitoimistonsanakirja.fi/#/kanuuna 
tykit=sv. kanoner

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Eikö puoltaisi paikkaansa ennemmin erillisenä?

**Comment by mariaforsen** [comment]
Ruotsiksi monesti tykit+kanuunat=kanoner. Jos lisätään molemmille tarkenteita kanuuna (tykki jonka putken pituus on yli 20 kertaa putken kaliiperi) niin sitten se on tietty mahdollista. 
https://www.kielitoimistonsanakirja.fi/#/kanuuna?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/tykki?searchMode=all
Tai mahdollisesti tykit=artilleripjäser (merkityskenttä ei taida aina olla sama), kanuunat=kanoner

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermi.
