### ISSUE TITLE
taistelupanssarivaunut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11557]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taistelupanssarivaunut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

"Taistelupanssarivaunuilla tuhotaan vihollisen taistelupanssarivaunuja ja jalkaväkeä. Ammunnanhallintajärjestelmä mahdollistaa tarkan tulittamisen pääaseella (panssarivaunukanuuna) liikkeestä 3,5 km etäisyydelle asti myös huonoissa sää- ja valaistusolosuhteissa. Sillä voidaan ampua panssarin läpäiseviä sirpale- ja painevaikutteisia ammuksia sekä panssarintorjuntaohjuksia. Konekivääreillä tehokas ampumaetäisyys 1 – 1,5 km."
-Taistelijan opas 2013. Saatavilla verkossa: https://puolustusvoimat.fi/documents/1948673/2258487/PEVIESTOS-Taistelijan-Opas-2013.pdf

”Taistelupanssarivaunut kykenevät taistelemaan sekä panssarivaunuja että jalkaväkeä vastaan. Ne ovat tulivoimaisia ja vahvasti panssaroituja. Tulivoima koostuu pääaseena olevasta suurikaliiperisesta panssarivaunukanuunasta, sen monipuolisesta ampumatarvikevalikoimasta sekä konekivääreistä. Suojalla pyritään estämään vihollisen taistelupanssarivaunun tuhoava osuma etusektorista. Taistelupanssarivaunuilla on hyvä maastoliikkuvuus. Ne ylittävät alle 1,5 m syvät kovapohjaiset ojat kahlaamalla ja 1,5-5 m syvät kovapohjaiset joet syväkahlaamalla.” -Yleinen ase- ja asejärjestelmäopas 2001. Saatavilla verkossa: https://urn.fi/URN:NBN:fi-fe2020040110108

Määritelmä myös PV:n kalustokuvastossa: https://puolustusvoimat.fi/kalusto#/asset/view/id/240

**Perustelut ehdotukselle**

Panssarivaunut on kuvailussa haasteellinen termi, sillä sen alle sisältyy erilaisia ilmatorjunta-, rynnäkkö-, taistelu-, miehistönkuljetus- jne. ajoneuvoja, joiden käyttötarkoitukset ovat hyvin erilaisia, ja joita yhdistää panssarointi ja teloilla kulkeminen. Yleisimmät helposti erotettavat alatyypit voisi olla aiheellista erottaa panssarivaunun alakäsitteiksi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [panssarivaunut](http://www.yso.fi/onto/yso/p9333)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Main_battle_tank), [Wikipedia](https://fi.wikipedia.org/wiki/Taistelupanssarivaunu)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.018752237
https://finna.fi/Record/taisto.166347
https://finna.fi/Record/taisto.169360
https://finna.fi/Record/taisto.169345

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [taistelupanssarivaunut](http://finto.fi/yse/fi/page/Y511557)

**Comment by mirmaid** [comment]
Huima määrä viitteitä Melindassa.

**Comment by mariaforsen** [comment]
Sv. stridsvagnar 
OBS https://finto.fi/yso/fi/page/p9333?clang=sv
https://puolustusvoimat.fi/sv/materiel#/category/view/id/38348301?page-size=15
https://sv.wikipedia.org/wiki/Stridsvagn
