### ISSUE TITLE
materiaalifysiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11552]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

materiaalifysiikka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

On oppiaineenakin ainakin Helsingin yliopistossa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-951-29-9141-9

**Ehdottajan organisaatio**

Turun yliopiston kirjasto
**Termiehdotus Fintossa:** [materiaalifysiikka](http://finto.fi/yse/fi/page/Y511552)

**Comment by mirmaid** [comment]
YSOssa on _materiaalitiede_ ja _materiaalitutkimus_. Eng. wikipediassa materials physics ohjaa sivulle materials science. Suomenkielisellä sivulla: _On jossain määrin hankalaa vetää rajaa materiaalitieteen ja materiaalifysiikan välille, sillä materiaalien tutkimuksessa kemia ja fysiikka ovat hyvin lähellä toisiaan ja tutkimus on yleensä monitieteellistä_.

13 viitettä Melindassa.

**Comment by mirmaid** [comment]
https://www.helsinki.fi/fi/koulutusohjelmat/materiaalitutkimus-maisteriohjelma

**Comment by mariaforsen** [comment]
Sv. materialfysik /ne, universitet

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermiksi _materiaalitutkimukselle_ ja _materiaalitieteelle_.
