### ISSUE TITLE
taistelutekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11556]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taistelutekniikka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

"Taistelutekniikka on joukkojen tulta, liikettä, perustaistelumenetelmiä ja aseiden- ja asejärjestelmien käyttöä taistelutilanteessa. Se on esimerkiksi sitä, kun joukkue tekee hyökätessään telamiinoilla takatulpan ja panssarintorjuntapartio tuhoaa siihen vaunun."" - Paronen, A. (2022). Keskusteluja taktiikasta: Ajatuksia taktiikan kehittämisestä. Maasotakoulu. s. 21. Saatavilla verkossa: https://puolustusvoimat.fi/documents/1951253/4047542/Paronen_Keskusteluja_taktiikasta.pdf/

"Strategian, operaatiotaidon ja taktiikan käsitteen lisäksi sotataidon sisältöön kuuluu myös taistelutekniikan käsite. Taistelutekniikka koostuu puolustushaarojen, aselajien ja toimialojen vakioiduista toimintatavoista. Tykistöjärjestelmään kuuluu myös taisteluteknisiä toimintatapoja. Ne liittyvät kiinteästi tykistöjärjestelmän eri osa järjestelmien käyttöön taistelussa, mutta ne eivät ole taktiikkaa, koska toimintatavat ovat vakioituja siinä, missä taktiikka on tilanteenmukaista soveltamista." - Kesseli, P. (2017). Tykistö taistelee tulellaan: Tykistötaktiikan kehitys Suomessa itsenäisyytemme aikana. Maanpuolustuskorkeakoulu. s. 17.  Saatavilla verkossa: https://urn.fi/URN:ISBN:978-951-25-2941-4

**Perustelut ehdotukselle**

Termi on Suomessa käyttöön vakiintunut sodankäynnin alinta toiminnallinnasta tasoa kuvaava termi, jota käytetään esimerkiksi ohjesäännöissä, tutkimuksissa ja muissa julkaisuissa.  

**Ehdotettu yläkäsite YSOssa (LT)**

 [sotataito](http://www.yso.fi/onto/yso/p15037)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Taistelutekniikka](https://fi.wikipedia.org/wiki/Taistelutekniikka)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.018641370
https://finna.fi/Record/taisto.164833
https://finna.fi/Record/arto.013577636

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [taistelutekniikka](http://finto.fi/yse/fi/page/Y511556)

**Comment by mirmaid** [comment]
25 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. stridsteknik (krigskonst)
https://sv.wikipedia.org/wiki/Stridsteknik

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _taistelutekniikka (sotataito)_.
