### ISSUE TITLE
rynnäkköpanssarivaunut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11558]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rynnäkköpanssarivaunut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

"Rynnäkköpanssarivaunussa on taistelupanssarivaunua kevyempi panssarointi. Sen tehtävänä on kuljettaa taisteluun noin ryhmän kokoista osastoa jalkaväkeä kevyiltä aseilta ja sirpaleilta suojattuna sekä tukea sitä taistelussa jalkautumisen jälkeen. Taistelukosketuksessa jalkaväkeä ei aina jalkauteta. Rynnäkköpanssarivaunun ammunnanhallintajärjestelmä mahdollistaa tarkan tulitoiminnan pääaseella myös liikkeestä. Sillä kyetään ampumaan panssarin läpäiseviä ja sirpalevaikutteisia ammuksia noin 2,5 km etäisyydelle. Konekiväärillä kyetään vaikuttamaan noin 1–1,5 km etäisyydelle." - Taistelijan opas 2013. Saatavilla verkossa: https://puolustusvoimat.fi/documents/1948673/2258487/PEVIESTOS-Taistelijan-Opas-2013.pdf

Määritelmä myös PV:n kalustokuvastossa: https://puolustusvoimat.fi/kalusto#/asset/view/id/240

SOTO-terminä on "jalkaväen taisteluajoneuvot", mikä on ilmeisesti suora käännös englanninkielisestä termistä "infantry fighting vehicle", jonka oikea käännös olisi siir rynnäkköpanssarivaunu. "Jalkaväen taisteluajoneuvo" esiintyy joissakin MPKK:n opinnäytteissä IFV:n käännöksenä, mutta ei nähdäkseni virallisissa aineistoissa.

**Perustelut ehdotukselle**

Panssarivaunut on kuvailussa haasteellinen termi, sillä sen alle sisältyy erilaisia ilmatorjunta-, rynnäkkö-, taistelu-, miehistönkuljetus- jne. ajoneuvoja, joiden käyttötarkoitukset ovat hyvin erilaisia, ja joita yhdistää panssarointi ja teloilla kulkeminen. Yleisimmät helposti erotettavat alatyypit voisi olla aiheellista erottaa panssarivaunun alakäsitteiksi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [panssarivaunut](http://www.yso.fi/onto/yso/p9333)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Infantry_fighting_vehicle), [Wikipedia](https://fi.wikipedia.org/wiki/Rynn%C3%A4kk%C3%B6panssarivaunu)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/taisto.169361
https://finna.fi/Record/arto.013360481
https://finna.fi/Record/arto.013360457

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [rynnäkköpanssarivaunut](http://finto.fi/yse/fi/page/Y511558)

**Comment by mariaforsen** [comment]
Sv. pansarskyttebandvagnar HT pansarskyttefordon, stormpansarvagnar
https://puolustusvoimat.fi/sv/materiel#/asset/view/id/240
https://sv.wikipedia.org/wiki/Pansarskyttefordon
https://fi.wikipedia.org/wiki/Rynn%C3%A4kk%C3%B6panssarivaunu
https://www.sanakirja.fi/custom/en-sv-fi/rynn%C3%A4kk%C3%B6panssarivaunu
https://valtioneuvosto.fi/sv/-/forsvarsmakten-uppdaterar-pansarskyttebandvagnarna-cv9030?languageId=sv_SE
https://maavoimat.fi/sv/om-oss
https://www.defmin.fi/sv/aktuellt/pressmeddelanden_och_nyheter/nyhetsarkiv/2021/forsvarsmakten_uppdaterar_pansarskyttebandvagnarna_cv9030.12054.news#454260c1

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
