### ISSUE TITLE
kuljetuspanssariajoneuvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11559]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kuljetuspanssariajoneuvot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Armoured personnel carrier

**Tarkoitusta täsmentävä selite**

"Kuljetuspanssariajoneuvo ja -vaunu kuljettavat noin ryhmän kokoista osastoa jalkaväkeä kevyiltä aseilta ja sirpaleilta suojattuna. Niiden ammunnanhallinta ja optiikka eivät välttämättä ole yhtä tehokasta kuin taistelu- ja rynnäkköpanssarivaunuissa. Taistelupanssarivaunujen tavoin myös kuljetuspanssariajoneuvolla ja -vaunulla pyritään tukemaan jalkaväen hyökkäystä."
-Taistelijan opas 2013. Saatavilla verkossa: https://puolustusvoimat.fi/documents/1948673/2258487/PEVIESTOS-Taistelijan-Opas-2013.pdf

Määritelmä myös PV:n kalustokuvastossa: https://puolustusvoimat.fi/kalusto#/asset/view/id/240 (Lisätietoa>Rynnäkkö- ja kuljetuspanssarivaunut)

**Perustelut ehdotukselle**

Kuljetuspanssariajoneuvot kulkevat pyörillä, kuljetuspanssarivaunut teloilla. Suomessa käytössä olevia kuljetuspanssariajoneuvoja ovat Patria XA-360, Sisu XA-180M, Patria XA-203. Kuljetuspanssarivaunu on MT-LBV (https://puolustusvoimat.fi/kalusto#/asset/view/id/238) 

**Ehdotettu yläkäsite YSOssa (LT)**

 [sotilasajoneuvot](http://www.yso.fi/onto/yso/p9334)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

 kuljetuspanssarivaunut

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Armoured_personnel_carrier)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/eepos.2767278
https://finna.fi/Record/taisto.165066
https://finna.fi/Record/arto.018160740

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [kuljetuspanssariajoneuvot](http://finto.fi/yse/fi/page/Y511559)

**Comment by mariaforsen** [comment]
Sv.  transportpansarfordon HT bepansrade transportfordon, bepansrade trupptransportfordon, 
 trupptransportfordon (bepansrade)

https://puolustusvoimat.fi/sv/materiel#/category/view/id/38348302?page-size=15
https://puolustusvoimat.fi/kalusto#/category/view/id/38348302?page-size=15
https://maavoimat.fi/sv/-/de-forsta-nya-bepansrade-trupptransportfordonen-6x6-till-armen
https://maavoimat.fi/sv/-/de-forsta-nya-bepansrade-trupptransportfordonen-6x6-till-armen?languageId=fi_FI
https://sv.wikipedia.org/wiki/Skyddat_trupptransportfordon

**Comment by ilona-x** [comment]
LCSH:
Armored personnel carriers http://id.loc.gov/authorities/subjects/sh85007330

Wikipediassa suomeksi:
panssaroitu miehistönkuljetusvaunu https://fi.wikipedia.org/wiki/Panssaroitu_miehist%C3%B6nkuljetusvaunu

**Comment by ilona-x** [comment]
SOTO:
panssaroidut miehistönkuljetusajoneuvot http://www.yso.fi/onto/soto/p1699

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotuksen mukaisesti.
