### ISSUE TITLE
polvinivel

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11555]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

polvinivel

**Ehdotettu termi ruotsiksi**

knäled

**Ehdotettu termi englanniksi**

knee joint

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [nivelet](http://www.yso.fi/onto/yso/p14975)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [TEPA](https://termipankki.fi/tepa/fi/haku/polvinivel), [Wikipedia](https://fi.wikipedia.org/wiki/Polvinivel)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Dual energy triple contrast computed tomography of articular cartilage /Miitu Honkanen

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [polvinivel](http://finto.fi/yse/fi/page/Y511555)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D007719
