### ISSUE TITLE
metabolomiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11551]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

metabolomiikka

**Ehdotettu termi ruotsiksi**

metabolomik

**Ehdotettu termi englanniksi**

metabolomics

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 26

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Finmesh](http://www.yso.fi/onto/mesh/D055432), [Wikipedia](https://en.wikipedia.org/wiki/Metabolomics)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Machine learning methods for structural elucidation in untargeted metabolomics 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [metabolomiikka](http://finto.fi/yse/fi/page/Y511551)

**Comment by ilona-x** [comment]
toinen väitös, mihin olisi voinut käyttää: Metabolomics and metagenomics in hypertension https://urn.fi/URN:ISBN:978-951-29-8896-9
