### ISSUE TITLE
Libanonin sota (2006)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11560]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Libanonin sota (2006)

**Ehdotettu termi ruotsiksi**

Libanonkriget 2006  (sao)

**Ehdotettu termi englanniksi**

Lebanon War, 2006

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Aiheesta on kirjallisuutta, artikkeleita ja opinnäytteitä. Termi tarvitaan erotukseksi muista Libanonin sodista (Libanonin sisällissota 1975-1990, Libanonin sota 1982). 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Libanonin_sota_2006), [LCSH](https://id.loc.gov/authorities/subjects/sh2006008286.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/taisto.152419
https://finna.fi/Record/taisto.166743
https://finna.fi/Record/taisto.143808
https://finna.fi/Record/doria_mpkk.10024_169998

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [Libanonin sota (2006)](http://finto.fi/yse/fi/page/Y511560)

**Comment by mariaforsen** [comment]
Sv. Libanonkriget (2006) HT Libanonkriget 2006, andra Libanonkriget (2006)
tidigare modell se: https://finto.fi/yso/sv/page/p1271

**Comment by annamarj** [comment]
Kannatan...mietin, pitäisikö sitten olla vielä ohjaustermi "toinen Libanonin sota" (joka on kiistanalainen nimi, estäisikö OT sitten jotain väärinkäsityksiä?)
"seitsemän kuukautta myöhemmin Israelin hallitus antoi tapahtuneelle virallisesti nimen toinen Libanonin sota veteraanien ja kaatuneiden omaisten painostuksesta, vaikka ensimmäistä sotaa ei ole virallisesti käyty. Näin tätä nimeä voidaan käyttää haudoilla ja kunniamitaleissa". Toisaalta tuo vuosilukutarkenne voi ihan riittää?
