### ISSUE TITLE
keskiaikaiset rahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11562]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

keskiaikaiset rahat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Lisäksi
roomalaisaikaiset rahat
uuden ajan rahat
viikinkiaikaiset rahat

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Numismaattinen kirjallisuus

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [keskiaikaiset rahat](http://finto.fi/yse/fi/page/Y511562)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Coins, Medieval**](http://id.loc.gov/authorities/subjects/sh85027846).

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

Uuden ajan rahat 5 x, muista ei viitteitä.

**Comment by mariaforsen** [comment]
Sv. 
-medeltida mynt HT medeltida pengar

-romerska mynt HT romerska pengar 
https://id.kb.se/term/sao/Romerska%20mynt

-vikingatida mynt HT vikingamynt

-? nya tidens pengar (?) 

uuden ajan rahat, eli mikä aika tarkalleen? EI osumia Googlessa.. englanniksi?

uppslagsverk/encyklopedi/lång/nya-tiden
https://www.so-rummet.se/kategorier/historia/nya-tiden
https://fi.wikipedia.org/wiki/Uusi_aika
https://finto.fi/yso/fi/search?clang=fi&q=uusi+aika

**Comment by ilona-x** [comment]
MAO:
**keskiaikaiset rahat** http://www.yso.fi/onto/mao/p10601
**viikinkiaikaiset rahat** http://www.yso.fi/onto/mao/p10674
**uuden ajan rahat** http://www.yso.fi/onto/mao/p10520
**roomalaisaikaiset rahat** http://www.yso.fi/onto/mao/p10658

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään seuraavaan kokoukseen. Selvitetään ennen käsittelyä mm. kuvailussa käytettyjä nimikkeitä.

**Comment by AuHo22** [comment]
Eli oletettavasti nämä olivat kolikoita, myös antiikin aika eli Kreikka mukaan lukien? https://www.jncoins.com/category/391/antiikin-ja-keskiajan-kolikot, ed. mynt ja coins

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään:

keskiaikaiset rahat http://www.yso.fi/onto/mao/p10601
viikinkiaikaiset rahat http://www.yso.fi/onto/mao/p10674
uuden ajan rahat http://www.yso.fi/onto/mao/p10520
roomalaisaikaiset rahat http://www.yso.fi/onto/mao/p10658

**Comment by mariaforsen** [comment]
Termi "uuden ajan rahat" ei oikein annan tuloksia googlessa, minkä ajan rahoja nämä ovat? Onko kyseessä "1400–1500-luvuilta nykypäiviin saakka" https://fi.wikipedia.org/wiki/Uusi_aika

**Comment by AuHo22** [comment]
Ainakin tässä yhteydessä keskusteltiin uusi aika - rajauksista ->
varhaismoderni #7396

**Comment by mariaforsen** [comment]
Olisiko sitten huomautus/määritelmä tarpeen? Sen perusteella voidaan luoda vastine myös ruotsiksi.
