### ISSUE TITLE
pronssirahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11561]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pronssirahat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Numismaattinen kirjallisuus

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [pronssirahat](http://finto.fi/yse/fi/page/Y511561)

**Comment by mariaforsen** [comment]
Sv. bronsmynt HT bronspengar

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
