### ISSUE TITLE
rahajäljitelmät / jäljitelmät (numismatiikka)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11563]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rahajäljitelmät / jäljitelmät (numismatiikka)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Numismaattinen kirjallisuus

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [rahajäljitelmät / jäljitelmät (numismatiikka)](http://finto.fi/yse/fi/page/Y511563)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. myntimitationer HT imitationer (numismatik)
Jfr https://www.sanakirja.fi/custom/en-sv-fi/rahaj%C3%A4ljitelm%C3%A4n%20levitys

**Comment by ilona-x** [comment]
MAOssa [jäljitelmät](http://www.yso.fi/onto/mao/p4104)
Assosiatiiviset käsitteet
   [ bysanttilaiset hopearahajäljitelmät](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp10197)
   [ dirhemijäljitelmät](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp10203)
   [ drakhmajäljitelmät](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp10739)
   [ miliaresionijäljitelmät](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp10914)
   [ penninkijäljitelmät](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp10972)

**Comment by YSO-kokous** [comment]
**Päätös**

Selvitetään _rahajäljitelmien_ tarkempaa merkitystä.

**Comment by mirmaid** [comment]
Joka yleisölle levittämistä varten valmistaa tai hankkii taikka yleisölle levittää käypää rahaa erehdyttävästi muistuttavan lomakkeen, merkin, kuvan tai muun esineen, on tuomittava rahajäljitelmän levityksestä sakkoon tai vankeuteen enintään yhdeksi vuodeksi. https://www.finlex.fi/fi/laki/ajantasa/1889/18890039001#L37

**Comment by mirmaid** [comment]
Kysytty ehdottajaorganisaatiolta, vastaus:

Kun rahankäyttö on levinnyt, on tehty tunnettuja valuutoita mukailevaa rahaa. Eri asia siis kuin väärennökset tai kopiot.

MAOsta löytyvät bysanttilaiset hopearahajäljitelmät, dirhemijäljitelmät, drakhmajäljitelmät, miliaresionijäljitelmät, penninkijäljitelmät ovat näitä, mutta rahajäljitelmät eivät rajoitu näihin ja toisaalta kirjastoaineiston kuvailussa ei välttämättä noin spesifejä termejä tarvitse. Pelkkä ”jäljitelmät” tuntuisi kuitenkin liian epätarkalta termiltä.

Ruotsiksi käytetään mielestäni termiä myntimitationer ja eng. coin imitations, mutta en löydä kunnollista lähdettä näille. Toisin kuin ruotsiksi ja englanniksi, suomeksi ei puhuta kolikkojäljitelmistä, vaikka metallirahasta näissä on kyllä kyse. 

Tämä  on sikäli vähän hankala termi, että noita samoja termejä käytetään usein myös moderneista replikoista, joita myydään rekvisiitaksi ja matkamuistoiksi jne., mutta en usko, että tässä on suurta sekaantumisen mahdollisuutta. 

Tässä esimerkki teoksesta, jonka luetteloinnissa termiä olisi voinut käyttää:
https://melinda.kansalliskirjasto.fi/byid/018331356

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään tarkenteella _rahajäljitelmät (historia)_. Lisätään huomautus merkityksestä. Käsitteelle _väärennökset_ lisätään ohjaustermi _rahajäljennökset (väärennökset)_.
