### ISSUE TITLE
Ravistellun vauvan oireyhtymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11568]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Ravistellun vauvan oireyhtymä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termille olisi tarvetta aiheesta kertovan kirjan kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Skakvåld : en vetenskaplig kontrovers med ödesdigra sociala och rättsliga konsekvenser 978-91-89526-48-8 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Ravistellun vauvan oireyhtymä](http://finto.fi/yse/fi/page/Y511568)

**Comment by ilona-x** [comment]
FinMeSH: ravistellun vauvan oireyhtymä http://www.yso.fi/onto/mesh/D038642

Wikipedia: https://fi.wikipedia.org/wiki/Ravistellun_vauvan_oireyhtym%C3%A4

LCSH: Shaken baby syndrome http://id.loc.gov/authorities/subjects/sh2002006057

**Comment by mariaforsen** [comment]
Sv. skakvåld HT shaken baby syndrom, shaken baby-syndrom
https://mesh.kib.ki.se/term/D038642/shaken-baby-syndrome
https://sv.wikipedia.org/wiki/Skakv%C3%A5ld
