### ISSUE TITLE
irtolöydöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11564]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

irtolöydöt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Lisäksi
kertymälöydöt
kirkkolöydöt (numismatiikka)

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Numismaattinen kirjallisuus

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [irtolöydöt](http://finto.fi/yse/fi/page/Y511564)

**Comment by mirmaid** [comment]
Irtolöydöt 17 kertaa Melindassa masa-terminä, 9 kertaa vapaana avainsanana. (Ei muita ehdotettuja termejä.)

**Comment by mariaforsen** [comment]
Sv. 
-lösfynd HT lösa fynd
https://www.vasamuseet.se/skola/i-klassrummet/lektionsmaterial-om-kallor/uppgift-ett-undersok-slutna-fynd/slutna-fynd
https://www.raa.se/kulturarv/arkeologi-fornlamningar-och-fynd/fornfynd-inlosensersattning-och-hittelon/vad-ar-ett-fornfynd/
https://svenska.se/tre/?sok=l%C3%B6sfynd&pz=1

-hopade fynd HT ackumulerade fynd
uppslagsverk/encyklopedi/lång/hopat-fynd
https://termipankki.fi/tepa/fi/haku/kertym%C3%A4l%C3%B6yt%C3%B6
https://www.diva-portal.org/smash/get/diva2:1289567/FULLTEXT01.pdf

**Comment by ilona-x** [comment]
MAO: 
**irtolöydöt**  KT hajalöydöt http://www.yso.fi/onto/mao/p3059

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _irtolöydöt_ sekä _kertymälöydöt_.
