### ISSUE TITLE
baikalinhylje

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11565]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

baikalinhylje

**Ehdotettu termi ruotsiksi**

Bajkalsälen

**Ehdotettu termi englanniksi**

Baikal seal

**Tarkoitusta täsmentävä selite**

"Hyljelaji, joka elää ainoastaan Siperian Baikaljärvessä Venäjällä."--Wikipedia

**Perustelut ehdotukselle**

Tarvitaan kuvailussa/voi lopettaa agriforssin käytön
Melinda-haku tuottaa 3 osumaa - mutta toisaalta termin otto ysoon ei aiheuttane ylläpitotyötä myöhemmin...

**Ehdotettu yläkäsite YSOssa (LT)**

 [hylkeet](http://www.yso.fi/onto/yso/p9962)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 Pusa sibirica, Phoca sibirica, Baikalin norppa

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh89000483), [Wikipedia](https://fi.wikipedia.org/wiki/Baikalinhylje), [LAJI.FI](https://laji.fi/taxon/MX.47304)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/004695330

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [baikalinhylje](http://finto.fi/yse/fi/page/Y511565)

**Comment by mariaforsen** [comment]
Sv. bajkalsäl
