### ISSUE TITLE
diminuutio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11571]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[diminuutio](http://www.yso.fi/onto/yso/p29871)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Isompien aika-arvojen pilkkomista osiin erilaisilla kuvioilla, ornamenteilla, hypyillä, juoksutuksilla ja murtosoinnuilla.

**Perustelut ehdotukselle**

Määritelmä on käännetty Oxford University Pressin julkaisemasta Nicholas Baragwanathin teoksesta The Solfeggio Tradition. Teoksen alussa on sanasto, josta käsite löytyi.

Käsitettä käytetään laajasti englannin kielisessä kirjallisuudessa liittyen historialliseen improvisaatioon. Ks. John Mortensen The Pianists Guide to Historic Improvisation. 

Myös toinen merkittävä akateemikko Robert Gjerdingen käyttää termiä säännöllisesti (Music in the Galant Style)

Kummatkin ovat ahkeria tubettajia.
Robert O. Gjerdingenin materiaali aiheesta: https://www.youtube.com/watch?v=QfGK400Hphw 
Julkaisijana Oxford University Press. Teos on Child Composers in the Old Conservatories.

Ja italialainen musiikkitieteilijä Elam Rotemin otto aiheesta: https://www.youtube.com/watch?v=1Amufu6K1JI

Suomen kielellä aiheesta löytyy tämä lähde.
https://muhi.uniarts.fi/retoriikka-affektit-kuvio-oppi/

Kyseessä ei ole ornamentaatio, koska diminuutio on historiallisessa improvisaatiossa rakenteellinen elementti, eikä koriste. Ornamentaatio on yleinen osa diminuutiota.

Tämä ei välttämättä ole korvaava ehdotus, sillä kyseinen "diminuutio" käsite on myös olemassa. Tämä on oma käsitteensä

**Ehdottajan organisaatio**

Yksityishenkilö

**Comment by tpalonen** [comment]
Mietin, onko riski sotkea tähän, mutta ehkä ei. https://tieteentermipankki.fi/wiki/Nimitys:diminutiivi

**Comment by mariaforsen** [comment]
Eli poikkeaa nykyisestä määritelmästä "Sävelten (äänten) aika-arvojen rytmillinen tihentyminen, jonka vastakohta on additio."? Molemmat termit tarvitsevat siinä tapauksessa tarkenteita.
https://kmh.diva-portal.org/smash/record.jsf?pid=diva2%3A735184&dswid=-7376

**Comment by MUUSA-kokous** [comment]
Ehdotetaan, että käsitteelle ornamentiikka (musiikki) lisätään ohjaustermi diminuutio (ornamentiikka).

**Comment by mirmaid** [comment]
Hyväksytään Muusan ehdotus.
