### ISSUE TITLE
mediapolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11577]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mediapolitiikka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

(mass) media policy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [joukkoviestintä](http://www.yso.fi/onto/yso/p10539), [media-ala](http://www.yso.fi/onto/yso/p5710)

**Ehdotetut temaattiset ryhmät**

 [80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85081902.html), [SAO](https://id.kb.se/term/sao/Mediepolitik)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Public service media's contribution to society, https://norden.diva-portal.org/smash/record.jsf?pid=diva2%3A1760972&dswid=-2975

**Ehdottajan organisaatio**

Yle Arkisto
**Termiehdotus Fintossa:** [mediapolitiikka](http://finto.fi/yse/fi/page/Y511577)

**Comment by mirmaid** [comment]
Sanastossa on _viestintäpolitiikka_. Mediapolitiikka käytetty kerran Melindassa, tietueessa on myös viestintäpolitiikka. Onko näillä selkeä ero, vai voiko lisätä esim. ohjaustermiksi?

**Comment by mariaforsen** [comment]
Mediepolitik on "statliga åtgärder som rör mediers funktioner, villkor och ställning i samhället och syftar till att viss produktion ska främjas (t.ex. inhemsk film) eller motverkas (t.ex. videovåld)." /Nationalencyklopedin
Kommunikationspolitik eli viestintäpolitiikka ei ymmärtääkseni ole aivan sama asia, esim. https://www.europarl.europa.eu/factsheets/sv/sheet/144/viestintapolitiikka mutta ehkä suhde on suomeksi läheisempi. Ruotsiksi on paremman puuttuessa ollut jo ohjausterminä.

**Comment by LeKorsu** [comment]
Tämä voidaan vielä jättää pöydälle seuraavaan kokoukseen, johon mennessä voin yrittää tutkia ja määritellä viestintäpolitiikan ja mediapolitiikan eroa (alkuperäinen ehdotus on siis minun). 3/23 kokoukseen en valitettavasti ehdi sitä tehdä.

**Comment by LeKorsu** [comment]
Niin kuin Maria tuossa ylempänä jo postasi mediapolitiikalla tarkoitetaan nimenomaan valtiovallan toimenpiteitä koskien media-alan lainsdäädäntöä ja sääntelyä (wikipedia: Media policy / M. politics is a term describing all legislation and political action directed towards regulating the media, especially mass media, and the media industry.)
https://journalisti.fi/nakokulmat/2023/01/suomalainen-mediapolitiikka-on-murusina-ministerioissa/
https://www.hs.fi/mielipide/art-2000009261609.html

Viestintäpolitiikan näen laajempana käsitteenä kuin mediapolitiikan. (LCSH:ssa communication policy on mass media policyn yläkäsite.)  
 Kenen media? -kirjan kuvauksesta: "Viestintäpolitiikka koskettaa yhä useammin ihmisten arkielämää jopa heidän tietämättään. Poliittiset päätökset vaikuttavat jokaisen mahdollisuuksiin saada ja jakaa tietoa, ilmaista itseään ja päättää omasta yksityisyydestään. Viestintäkysymysten ajankohtaisuudesta ja poliittisuudesta kertovat esimerkiksi internetin hallinnan, yksityisyydensuojan, tekijänoikeuksien tai julkisen palvelun tiedonvälityksen herättämä keskustelu. Päätöksenteko on tavoitteellista toimintaa, ja viestintää koskeviin päätöksiin vaikuttavat vahvasti yhteiskunnalliset valtarakenteet, intressit ja ihanteet. Mitä esimerkiksi tarkoitetaan kun puolustetaan sanavapautta, demokratiaa tai vapaita markkinoita? Vaikeasti rajattavasta aiheesta ei siksi saa selkoa käymällä läpi pelkkiä lakitekstejä, vaan on tutkittava niiden laatijoiden intressejä sekä niiden oikeuttamiseksi esitettyjä argumentteja. Sananvapauden ja demokratian nimissä voidaan ajaa hyvin monenlaisia linjauksia ... Viestintäpolitiikan tutkimuksessa yhdistyvät muun muassa viestinnän, oikeustieteen ja politiikan tutkimuksen menetelmät ja lähestymistavat. Kirja painottaa joukkoviestimiä koskevaa päätöksentekoa, tekijänoikeuksia tai televiestintää ja sen yksityisyydensuojaa unohtamatta. "

Eli kärjistäen ja tiivistäen: mediapolitiikka koskee yhtiöitä, joukkoviestimiä ja niiden rahoitusta, lainsäädäntöä ja säätelyä, jota valtiovala/hallitus tekee, viestintäpolitiikka yksilöitä ja yhteiskuntaa ja mediapolitiikka on yksi osa-alue viestintäpolitiikkaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään mahdollisesti määritelmä.

**Comment by mariaforsen** [comment]
Sv. mediepolitik HT mediapolitik
NE, https://id.kb.se/find?q=mediepolitik 
https://svenska.se/tre/?sok=mediepolitik&pz=1
