### ISSUE TITLE
vanhustenhuolto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11578]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vanhustenhuolto](http://www.yso.fi/onto/yso/p12787)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

englannikieliseksi ohjaustermiksi elderly care

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Elderly_care

**Ehdottajan organisaatio**

kk/il

**Comment by fantsby-m** [comment]
Myös _care for the elderly_?
