### ISSUE TITLE
puhelaulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11573]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[puhelaulu](http://www.yso.fi/onto/yso/p2427)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritelmä olisi hyvä muuttaa. Nykyinen on turhan spesifinen. Esimerkki on tarpeeton ja assosioi kenties vähän liiaksi vain tietynlaiseen puhelauluun.
RT:ksi rap.

**Perustelut ehdotukselle**

Vrt. tälle lisättiin ohjaustermiksi resitoiminen ja resitointi. Nykyinen määritelmä: "Puhelaulu on täsmällisesti nuotinnettua puhetta ilman melodiaa tai harmonioita. Suomessa esimerkiksi mieskuoro Huutajat on käyttänyt puhelaulua."

Puhelaulua, kuten puhettakin, voi kuitenkin pitää melodisena. Melodia on vain erilainen kuin ns. tavallisessa laulussa. Riittäisikö määritelmäksi: "Puhetta lähenevä laulutapa."?

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Enkun termiäkin voisi pondeerata (sprechstimme). Ja käsitteessä myös linkki LCSH:n Sprechstimmeen. Näköjään käsitteellä on ollut vahva kytkös klassiseen musiikkiin eikä niinkään muualle, mutta tosiaan esim. rap on monessa yhteydessä määritelty puhelauluksi ainakin suomen kielen vinkkelistä. Ks. esim.
https://fi.wikipedia.org/wiki/Rap
https://www.koulukino.fi/oppimateriaalit/ei-koskaan-enaa/rap-ja-sanoitukset/
https://fi.wiktionary.org/wiki/rap

**Comment by tpalonen** [comment]
Ei ole erityisen helppo löytää järkevää muuta englannin vastinetta käsitteelle kuin tuo Sprechstimme. Puhelaulu tuntuu joktap olevan suomen kielessä skopukseltaan melko omalaatuinen termi, helppotajuisena yhdyssanana sitä on käytetty jonkin verran rockin, popin, räpin ja myös folkloristisen tutkimuksen puolella ja täten sille ei ole täydellistä vastinetta englannissa. Itseäni häiritsee Sprechstimme-termissä se, että se rajautuu lähinnä klassisen musiikin traditioon. Kuitenkin puhelaulu-käsitettä on käytetty Melindassa jokunen kerta myös muunlaisessa kontekstissa.
https://melinda.kansalliskirjasto.fi/byid/007054869
https://melinda.kansalliskirjasto.fi/byid/002401027

Groven Rap-artikkelissa räppääminen määritellään näin: "semi-spoken rhymes declaimed over a rhythmic musical backing". Ja BBC:n Bitesize-oppimisympäristössä räppääminen taas määritellään näin: "Rapping is rhythmical, rhyming, semi-spoken recitation." Näistä inspiroituneena voisin kääntää termin englanniksi: _semi-spoken singing technique_ tai _semi-spoken singing style_ tai yksinkertaisesti _semi-spoken singing_. Ja Spechstimme siirtyisi ohjaustermiksi.

Kaipaisin tähän siis Muusan mielipidettä: haluttaisiinko käsite rajata nimenomaan klassiseen musiikkiin? Tällöin Sprechstimme voi jäädä englannin vastineeksi. Mutta Melinda-kuvailuita lienee hyvä tässä tapauksessa hieman korjata. Vai sallitaanko laveampi tulkinta, jolloin suosittaisin termiksi semi-spoken singing?

**Comment by mariaforsen** [comment]
Sv. talsång on "vokalt framställningssätt mellan tal och sång" /Nationalencyklopedin, eli ei ota tarkempaa kantaa. 
https://sv.wikipedia.org/wiki/Sprechgesang

**Comment by MUUSA-kokous** [comment]
YSO-termi viittaa sprechstimme/sprechgesang-perinteeseen eli taidemusiikkiin.
Ehdotetaan sulkutarkennetta termin perään ja määritelmän tarkennusta Wikipedian mukaisesti:

_puhelaulu (taidemusiikki)_
Puhelaulu (Sprechgesang, Sprechstimme) on taidemusiikin vokaalinen ilmaisutapa, joka sijoittuu laulun ja puheen välimaastoon. Tekniikkaa on käytetty yleisimmin oopperoissa 1800-luvun lopulta lähtien.

**Comment by mariaforsen** [comment]
Sv. talsång (konstmusik) HT sprechgesang
https://sv.wikipedia.org/wiki/Sprechgesang
uppslagsverk/encyklopedi/lång/talsång

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
