### ISSUE TITLE
slangi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11572]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[slangi](http://www.yso.fi/onto/yso/p1348)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan käsitettä huomautuksella, sulkutarkenteella tai muulla keinolla. Tai mahdollisesti yhdistetään johonkin muuhun käsitteeseen.

**Perustelut ehdotukselle**

Sanastossa on myös ammattikieli, erikoiskieli ja puhekieli. Slangi-asiasanan merkitys on Melinda-käytön perusteella epäselvä ja osin päällekkäinen edellisten kanssa:
The A to Z of business bullshit
The language of thieves
Sähkömiesten ammattislangia Turussa 2016
Sanaa tutkimassa : näkökulmia uskonnolliseen kieleen ja sen käyttöön
Suomalainen purjehdussanasto

Jos haluaisi tarkentaa niin ehkä käsitettä voisi huomautuksella rajata epämuodolliseen urbaaniin puhekieleen, ei yksittäisen ammattikunnan, harrastuksen tai aihealueen erikoiskieleen.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Sv. slang on ruotsiksi "vardagligt språkbruk som ligger på en stilistisk nivå under det neutrala språkets."  Eli EI liity ruotsiksi ammattikieleen, tms. erikoisalueen kieleen, vaan ainoastaan epämuodolliseen arkikieleen.  

"Det finns många olika definitioner på vilka ord som egentligen är slang, men den grundläggande regeln är att slang är ord som inte är accepterade i vårdat språk, och som sällan eller aldrig förekommer i skriftspråk."
/ https://sv.wikipedia.org/wiki/Slanguttryck

**Comment by ilona-x** [comment]
Voisiko käyttöä yrittää ohjata myös uusilla ohjaustermeillä, esim. slangi (ammattikieli) KÄYTÄ ammattikieli?

--

Kielitoimiston sanakirja:
[ammattislangi ](https://www.kielitoimistonsanakirja.fi/#/ammattislangi?searchMode=all)
huolittelematon, ”epävirallinen” ammattikieli.

**Comment by mirmaid** [comment]
Osaan Tuomaksen listaamista viitteistä sopisi _erikoiskielet_-termi. Pitäisikö siis olla myös slangi (erikoisalat) KÄ erikoiskielet? Toisaalta pitäisikö näillä ollakin hierarkkinen suhde? Aika samalla tavalla suomeksi, ruotsiksi ja englanniksi näyttäisi olevan päällekkäisyyttä näillä termeillä.

**Comment by fantsby-m** [comment]
> Osaan Tuomaksen listaamista viitteistä sopisi _erikoiskielet_-termi. Pitäisikö siis olla myös slangi (erikoisalat) KÄ erikoiskielet? 

Myös slangi (ammattikieli), KÄ ammattikieli. -- Vrt _jargon_, joka on ohjausterminä: _jargonit KÄ ammattikieli_ ja _jargonit KÄ erikoiskielet_

**Comment by mirmaid** [comment]
^ Joo, tarkoitin että Ilonan ehdottaman lisäksi.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Lisätään sanastoon seuraavat ohjaustermit:
slangi (ammattikieli) KÄYTÄ ammattikieli
slangi (erikoisalat) KÄYTÄ erikoiskielet
slangi (arkikieli) KÄYTÄ slangi

Tarkistetaan termit myös muiden kielten osalta.

YSO-ylläpito pohtinee, lisätäänkö slangi-käsitteelle myös käyttöhuomautus, joka erottaa sen selkeämmin ammattikieli- ja erikoiskielet-käsitteistä vai pärjätäänkö ilman.
