### ISSUE TITLE
hyljetuhot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11570]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hyljetuhot

**Ehdotettu termi ruotsiksi**

sälskador

**Ehdotettu termi englanniksi**

seal (animal) damage

**Tarkoitusta täsmentävä selite**

Hylkeiden kaupalliselle kalastukselle ja kalankasvatukselle aiheuttamat vahingot

**Perustelut ehdotukselle**

Tarvitaan kuvailussa/agriforssin positaminen
hyljevahingot:
* Melinda: 6 osumaa
* Helka: 10 osumaa

**Ehdotettu yläkäsite YSOssa (LT)**

 [eläintuhot](http://www.yso.fi/onto/yso/p9799)

**Ehdotetut temaattiset ryhmät**

 [23 Erätalous. Kalastus. Metsästys](http://www.yso.fi/onto/yso/p26561)

**Vaihtoehtoiset termit**

 hyljevahingot

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [AFO](http://www.yso.fi/onto/afo/p7698)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/000253568

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [hyljetuhot](http://finto.fi/yse/fi/page/Y511570)

**Comment by mirmaid** [comment]
Sanastossa on hirvi-, hyönteis- ja myyrätuhot sekä YK eläintuhot.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
