### ISSUE TITLE
Cork

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11579]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Cork

**Ehdotettu termi ruotsiksi**

Cork

**Ehdotettu termi englanniksi**

Cork

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Cork on Irlannin tasavallan toiseksi suurin kaupunki.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kaupunkiin sijoittuvat fiktiiviset teokset sekä matkaoppaat.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Cork](http://finto.fi/yse/fi/page/Y511579)

**Comment by jtuohini** [comment]
Pitää huolehtia, ettei sekoitu samannimiseen kreivikuntaan, LCNAF:ssa nämä RDA:n mukaisesesti [**Cork (Ireland)**](http://id.loc.gov/authorities/names/n79027115) ja [**Cork (Ireland : County)**](http://id.loc.gov/authorities/names/n79129259).

**Comment by mirmaid** [comment]
Cork (kaupunki)

_[Suomessa ei toistaiseksi kuvailla eikä identifioida paikkoja RDA:n mukaisesti](https://access.rdatoolkit.org/PolicyStatement/Index?externalId=fi-FI_ala-53333005-bcf0-38a7-b349-8a8c28e1548f)_.

**Comment by mirmaid** [comment]
Dublin (Irlanti : kaupunki)
