### ISSUE TITLE
Dallas (

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11587]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Dallas (

**Ehdotettu termi ruotsiksi**

Dallas (Tex.)

**Ehdotettu termi englanniksi**

Dallas (Tex.)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Paljon aineistoa, jossa aiheena, eikä YSO:lla pääse nykyisellään osavaltiotasoa tarkemmalle tasolle tässä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Texas](http://www.yso.fi/onto/yso/p107723)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCNAF/LCSH](http://id.loc.gov/authorities/names/n79023321), [Wikidata](https://www.wikidata.org/wiki/Q16557)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [Dallas (](http://finto.fi/yse/fi/page/Y511587)

**Comment by mirmaid** [comment]
Auktorisoitu, vrt. Melinda 🤔

**Comment by jtuohini** [comment]
Osavaltiotarkenne on kyllä RDA:n mukaan pakollinen, eikä muutenkaan haittaisi estämästä sotkeutumista _Dallas_-televisiosarjaan, joka aiemmin oli Melindassa merkitty joko 630- tai 653-kenttään täsmälleen samalla merkkisarjalla "Dallas" kuin paikka ennen kuin rupesin niitä toisistaan erottelemaan.

**Comment by mirmaid** [comment]
Tutustutaan RDA:n sääntökohtaan. Tämä koskisi suurta määrää YSO-paikkojen auktoriteeteista (useissa valtioissa), jos tehdään muutos käytäntöön, on huomioitava myös muut valtiot kuin vain Yhdysvallat. Englanninkielisten lyhenteiden käyttö muuten suomen- ja ruotsinkielisessä sanastossa on tuskin tarkoituksenmukaista. 

https://data.bnf.fr/15238453/dallas__texas__etats-unis_/
https://d-nb.info/gnd/4085382-2

**Comment by mirmaid** [comment]
^ Jos joku tietää, mikä sääntökohta RDA:ssa tarkalleen käsittelee osavaltioiden lyhenteiden käytön pakollisuutta paikka-auktoriteeteissa, käsittelyä voi nopeuttaa merkitsemällä ko. RDA:n kohdan tähän tiedoksi.

**Comment by jtuohini** [comment]
Kaivattu sääntökohta on RDA:n luku [16.2.2.9.2](http://original.rdatoolkit.org/rdachp16-fi_rda16-469.html).

**Comment by mirmaid** [comment]
Dallas (Texas)
