### ISSUE TITLE
neuralgia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11588]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neuralgia

**Ehdotettu termi ruotsiksi**

neuralgi

**Ehdotettu termi englanniksi**

neuralgia

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kipu](http://www.yso.fi/onto/yso/p14193)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 hermokipu, neuropaattinen kipu, hermosärky

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D009437), [wikidata](https://www.wikidata.org/wiki/Q1136940), [LCSH](http://id.loc.gov/authorities/subjects/sh85091099)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

What makes nerve injury painful? : Characterization of neuropathic pain after intercostobrachial nerve resection in women treated for breast cancer http://urn.fi/URN:ISBN:978-951-51-8384-2 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [neuralgia](http://finto.fi/yse/fi/page/Y511588)

**Comment by mariaforsen** [comment]
Sv. nervsmärta HT neuralgi, neuropatisk smärta, neurogen smärta, neurodyni
https://id.kb.se/term/sao/Neuralgi
https://mesh.kib.ki.se/term/D009437/neuralgia
https://www.sanakirja.fi/custom/en-sv-fi/hermokipu
https://www.rikstermbanken.se/search?q=nervsm%C3%A4rta&s=termer
sök/?t=uppslagsverk&q=nervsmärta

**Comment by FinMeSHienPaimentaja** [comment]
"Hermokipu" olisi suomenkielisempi, mutta en "neuralgiaakaan" vastusta (FinMeSH:issäkin näyttää olevan "neuralgia" prio-terminä).
