### ISSUE TITLE
snacksit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11586]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[snacksit](http://www.yso.fi/onto/yso/p25879)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "naksut"

**Perustelut ehdotukselle**

Aiheesta (puhe)kielessä käytetty nimitys, joka on huomioitu myös Kielitoimiston sanakirjassa (https://www.kielitoimistonsanakirja.fi/naksu).

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Aika spesifi ohjaustermi olisi. Lähinnä tulee juustonaksut mieleen.

**Comment by jtuohini** [comment]
Niin tarkoitus onkin, ks. esim. https://melinda.kansalliskirjasto.fi/byid/013706989.
