### ISSUE TITLE
jalkojen sitominen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11580]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jalkojen sitominen

**Ehdotettu termi ruotsiksi**

fotbindning

**Ehdotettu termi englanniksi**

footbinding

**Tarkoitusta täsmentävä selite**

"Jalkojen sitominen oli Kiinassa harjoitettu tapa, jossa nuorten tyttöjen varpaat taivutettiin jalkapöydän alle ja sidottiin, minkä johdosta jalat kasvoivat vääristyneeseen muotoon. Sidotut jalat myös vaikeuttivat kävelemistä."--Wikipedia.

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [epämuodostumat](http://www.yso.fi/onto/yso/p6004), [jalat](http://www.yso.fi/onto/yso/p13757)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 jalkojen sidonta

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh85050424), [Wikipedia](https://fi.wikipedia.org/wiki/Jalkojen_sitominen)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/005117109

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [jalkojen sitominen](http://finto.fi/yse/fi/page/Y511580)

**Comment by mirmaid** [comment]
Kaipasin tätä muutamia kertoja itsekin sidonta-viitteitä korjatessa, lisäsin 653-kenttään.

**Comment by mariaforsen** [comment]
Sv. fotbindning HT liljefötter, lotusfötter
https://sv.wikipedia.org/wiki/Fotbindning
https://id.kb.se/term/sao/Liljef%C3%B6tter

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään tarvittaessa huomautus.
