### ISSUE TITLE
hepatiitti D-virus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11594]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hepatiitti D-virus

**Ehdotettu termi ruotsiksi**

hepatit D-virus

**Ehdotettu termi englanniksi**

hepatitis D virus 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [hepatiittivirukset](http://www.yso.fi/onto/yso/p20854)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 HDV

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-951-51-8372-9

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [hepatiitti D-virus](http://finto.fi/yse/fi/page/Y511594)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D003698?

**Comment by mariaforsen** [comment]
Sv. hepatit D-virus HT HDV, deltavirus, hepatit delta-virus 
/uppslagsverk/encyklopedi/lång/deltavirus
https://mesh.kib.ki.se/term/D003698/hepatitis-delta-virus
https://laji.fi/taxon/MX.282654/taxonomy?showTree=true
https://www.folkhalsomyndigheten.se/smittskydd-beredskap/smittsamma-sjukdomar/hepatit-d/
https://sv.wikipedia.org/wiki/Hepatit_D
https://medibas.se/handboken/kliniska-kapitel/infektion/tillstand-och-sjukdomar/hepatit/hepatit-d
