### ISSUE TITLE
luonnollinen kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11614]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luonnollinen kieli](http://www.yso.fi/onto/yso/p26762)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

luonnolliset kielet

**Perustelut ehdotukselle**

tämän vastakohta keinotekoiset kielet on monikossa, joten joko tämä monikkoon tai sitten keinotekoiset kielet yksikköön. Monikko kuitenkin sopii ontologiaan paremmin.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kyse usein tästä https://fi.wikipedia.org/wiki/Luonnollisen_kielen_k%C3%A4sittely

**Comment by tpalonen** [comment]
Aineisto ei niinkään käsittele yksittäisiä luonnollisia kieliä, vaan enemmänkin esim. kieliteknologian kautta luonnollisen kielen koneellista analyysiä, eli juuri tuota mihin ylläoleva Wikipedia-artikkeli viittaa. Säilyttäisin yksikössä.

Mutta tämä on itse asiassa niin keskeinen teema aineistoissa että ehdottaisinkin, että luonnollisen kielen käsittely otetaan ohjaustermiksi. Tähän tapaan:
luonnollisen kielen käsittely KÄYTÄ luonnollinen kieli
natural language processing KÄYTÄ natural language
NLP (natural language processing) KÄYTÄ natural language

Ja jos tämä ehdotus menee läpi niin samalla pitänee nuo neurolingvistinen ohjelmointi -käsitteen NLP-ohjaustermitkin muuttaa avattuun muotoonsa tähän tapaan:

NLP (neurolinguistic programmig) KÄYTÄ neurolinguistic programming

**Comment by fantsby-m** [comment]
Yksikössä säilyttäisin minäkin. Kieliteknologian ym. lisäksi aineistossa on jonkin verran kielifilosofiaa ja mm. de Saussuren ja Wittgensteinin klassikoita, joten termin käyttö ei rajaudu NLP-tyyppiseen sisältöön - ehkä _luonnollisen kielen käsittely_ voisi siis olla omana terminäänkin?

**Comment by fantsby-m** [comment]
LCSH:ssa on ainoastaan [Natural language processing (Computer science)](https://id.loc.gov/authorities/subjects/sh88002425.html), saksalaisten tuohon linkattu termi puolestaan on [Natürliche Sprache](https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4041354-8), joka on määritelty "Definition: Nur verwendet in Informatik sowie Information und Dokumentation, nicht in der Linguistik".

**Comment by mirmaid** [comment]
LCSH:ssa näyttää olevan myös [Natural language generation (Computer science)](http://id.loc.gov/authorities/subjects/sh2017004703).

**Comment by mirmaid** [comment]
Ainakin osittain tuo luonnollisen kielen generointi nähdään luonnollisen kielen käsittelyn osa-alueena, joten ehkä se voisi toistaiseksi kattaa aihepiirin. Jäisikö siis pelkkä luonnollinen kieli myös sanastoon?

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Otetaan sanastoon uusi käsite: luonnollisen kielen käsittely. 
Ohjaustermiksi tälle suomeksi ja ruotsiksi NLP (natural language processing).
YSO-ylläpito pohtii, otetaanko lisäksi ohjaustermiksi luonnollisen kielen tuottaminen/generointi -muoto(j)a ja  (suomeksi) natural language processing.

Säilytetään sanastossa erikseen luonnollinen kieli, yksikkömuotoisena.

**Comment by mariaforsen** [comment]
Sv. bearbetning av naturligt språk HT naturlig språkbehandling, datorhantering av naturligt språk, naturlig språkbearbetning, NLP (natural language processing)

https://termipankki.fi/tepa/fi/haku/nlp
https://www.sanakirja.fi/custom/en-sv-fi/NLP
https://www.europarl.europa.eu/doceo/document/TA-8-2018-0332_SV.html
https://mesh.kib.ki.se/term/D009323/natural-language-processing
https://www.su.se/sok-kurser-och-program/ml273n-1.581408
https://www.oru.se/utbildning/kurser/kurs/datateknik-avancerad-niva-naturlig-sprakbehandling-dt712a
https://studier.se/studier/datateknik-avancerad-niva-naturlig-sprakbehandling/
https://www.unite.ai/sv/what-is-natural-language-processing/
https://www.psykologiguiden.se/psykologilexikon/?Lookup=NLP : "'Naturlig språkbehandling' är rent språkligt en felkonstruktion, eftersom det inte är behandlingen utan språket som är naturligt."
