### ISSUE TITLE
aravajärjestelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11616]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aravajärjestelmä](http://www.yso.fi/onto/yso/p20358)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Aravajärjestelmän sijaan ohjausterminä käytetty ara-asunnot olisi parempi yläkäsite.

**Perustelut ehdotukselle**

Aravalainojen myöntäminen lakkasi vuonna 2007. Nykyisin valtion tukema asuntotuotanto tehdään ara-rahoituksella. Ara-tuotantoa on määritelty Rakennetun ympäristön sanastossa, ks. https://termipankki.fi/tepa/fi/haku/ara

**Ehdottajan organisaatio**

Asumisen rahoitus- ja kehittämiskeskus

**Comment by mariaforsen** [comment]
Olisivatko nämä mahdollisesti RT? Asunto vs. järjestelmä, laina jne.
https://www.kielitoimistonsanakirja.fi/#/arava?searchMode=all
https://fi.wikipedia.org/wiki/Arava

**Comment by mirmaid** [comment]
Luen ehdotuksen niin, että päätermi haluttaisiin muuttaa ara-asunnot-muotoon (nyt ohjausterminä). Varmaankin siis koska arava-lainat ovat jääneet historiaan, ja aravajärjestelmä terminä on/kuulostaa olevan sidottu (?) näihin lainoihin. 

Ehkäpä tähän voisi yrittää kysyä ehdottajalta vielä tarkennusta, vanhemmassa aineistossa ei luonnollisesti puhuta ara-asunnoista, mutta kaksi erillistä termiä vasta ongelmallinen tilanne olisikin.

**Comment by ilona-x** [comment]
aravajärjestelmän ohjausterminä on nyt myös aravalainat, mutta jos päätermiksi vaihdettaisiin arava-asunnot, ei tämä aravalainat varmaankaan olisi mahdollinen ohjaustermi

---

**fi        aravalaina**
sv       aravalån n
en      arava loan

määritelmä
valtion myöntämä, valtion tukea sisältävä laina vuokra-, omistus- ja asumisoikeusasuntojen valtion tukemaan asuntotuotantoon

huomautus
Aravalaina voi olla joko vuokra-, omistus- tai asumisoikeustalon aravalaina.
Uusia aravalainoja ei ole myönnetty vuoden 2007 jälkeen. Aravalainojen sijasta nykyisin myönnetään korkotukilainoja.
Arava oli vuonna 1949 perustetun Asuntorakennustuotannon valtuuskunnan lyhenne. Valtion tukemaa asuntotuotantoa kutsuttiin aravatuotannoksi, lainoja aravalainoiksi, rakennettavia taloja aravataloiksi ja asuntoja arava-asunnoiksi. Nykyisin aravajärjestelmää hoitaa Asumisen rahoitus- ja kehittämiskeskus.
Aravalainasta säädetään aravalaissa (1189/1993) ja siihen liittyvissä aiemmissa laeissa.

Lähde: Rakennetun ympäristön sanasto (2020) https://termipankki.fi/tepa/fi/haku/aravalaina


**fi        arava-asunto**
sv       aravabostad
en      apartment financed by arava loan

määritelmä
aravalainalla rahoitettu asunto

huomautus
Nykyisin aravalainoja ei enää myönnetä, mutta aravalainalla rahoitettua asunto- ja lainakantaa on vielä jäljellä. Arava-asunnot ovat nykyisin aravavuokra-asuntoja tai aravalainoitettuja asumisoikeusasuntoja, aiemmin aravalainoilla rahoitettiin myös omistusasuntoja (omistusarava-asunto). Aravavuokra-asuntoja kutsutaan myös ARA-vuokra-asunnoiksi.
Arava-asuntoihin valitaan asukkaat noudattaen asukasvalintaperusteita.
Aravavuokra-asunnoista peritään omakustannusvuokraa.

Lähde: Rakennetun ympäristön sanasto (2020) https://termipankki.fi/tepa/fi/haku/arava-asunto

**Comment by mirmaid** [comment]
Palaute tähän: 
Muokkausehdotuksen alkuperäinen tarve on siis lähtenyt siitä, että aravajärjestelmän sijasta nykyisin on käytössä korkotukijärjestelmä. 
Asumisen korkotukijärjestelmällä tuotetut asunnot ovat ara-asuntoja; aravajärjestelmällä tuotetut arava-asuntoja.

Ara-asuntojen yläkäsite on asumisen korkotukijärjestelmä, joka ei ole vakiintunut tai virallinen termi, mutta kuvaa asiaa. Korkotukijärjestelmä tai siihen tarkemmin kuuluvat korkotukilainat menevät Rakennetun ympäristön sanastossa (2020) määritellyn termin ”asumisen tuotantotuki” alle.

Yläkäsite näille voisi olla asuinrakentamisen valtiontukijärjestelmä tai asumisen tuotantotukijärjestelmä.
Ne sisältäisivät sekä arava- että korkotukijärjestelmät, ara-asunnot ja arava-asunnot.

Jos aravajärjestelmän muuttaminen tai uuden termin lisääminen ei onnistu, voisiko aravajärjestelmään vähintään lisätä maininnan, että sitä ei tällä hetkellä enää käytetä ja sen sijalla on tuo toinen järjestelmä?

**Comment by ilona-x** [comment]
fi        korkotukivuokra-asunto; korkotukiasunto
sv       räntestödshyresbostad
en      interest-subsidy rental dwelling

määritelmä
korkotukilainalla rahoitettu vuokra-asunto

huomautus
Korkotukivuokra-asuntoihin valitaan asukkaat noudattaen asukasvalintaperusteita.
Korkotukivuokra-asunnoista peritään omakustannusvuokraa.
ARA-vuokra-asunnolla tarkoitetaan sekä korkotuki- että aravavuokra-asuntoja.

Lähde: Rakennetun ympäristön sanasto (2020) https://termipankki.fi/tepa/fi/haku/korkotukiasunto

**Comment by ilona-x** [comment]
> ARA-vuokra-asunnolla tarkoitetaan sekä korkotuki- että aravavuokra-asuntoja.

Eli ongelmana taitaa olla ainakin se, että nyt YSO:ssa ARA-asunnot on ohjausterminä aravajärjestelmä-termille, vaikka ARA-asunnot kattaa myös korkotukivuokra-asunnot.

**Comment by mirmaid** [comment]
Entä jos olisi korkotukiasunnot? Ja ARA-asunnot olisi ohjaustermi näihin molempiin?

**Comment by mariaforsen** [comment]
Sv. räntestödsbostäder HT räntestödda bostäder, bostäder med räntestöd
https://www.finlex.fi/sv/laki/alkup/2016/20160574
https://termipankki.fi/tepa/fi/haku/korkotuki
https://www.sanakirja.fi/custom/en-sv-fi/korkotuki

**Comment by YSO-kokous** [comment]
Hyväksytään korkotukiasunnot ja ehdotettu ohjaus.
