### ISSUE TITLE
tunnesäätely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11617]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tunnesäätely

**Ehdotettu termi ruotsiksi**

känsloreglering

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan Melindassa. Nyt käytetty säätely + tunteet esim. Muuta asenteesi, muuta elämäsi /Eija Hinkkala. Säätely=sv. justering, eli ei sovi ruotsiksi (säätely ilman tarkennuksia/määrittelyä on kyllä miltei mahdoton saada täsmäämään monikielisesti, ja yksi mahdollinen ratkaisu on tarkempien termien ottaminen, ks. ISO-standardia 25964-1)

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://www.mielenterveystalo.fi/fi/omahoito/epavakauden-omahoito-ohjelma/mita-tunnesaately)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Muuta asenteesi, muuta elämäsi /Eija Hinkkala

**Ehdottajan organisaatio**

ALLFO
**Termiehdotus Fintossa:** [tunnesäätely](http://finto.fi/yse/fi/page/Y511617)

**Comment by mirmaid** [comment]
2 viitettä Melindassa. Sanastossa on kyllä _itsesäätely (psykologia)_ ja _tunnetaidot_, en ole ihan vakuuttunut että tämä tarvitaan lisäksi.

**Comment by mariaforsen** [comment]
Miten voisi sitten ohjata käyttöä niin ettei käytettäisi tunteet + säätely, kun se menee nyt tosiaan virheelliseksi ruotsiksi?

**Comment by mirmaid** [comment]
_Tunnetaidot tarkoittavat kykyä havaita, ilmaista ja säädellä omia tunteita_. (yths) 
https://www.terveyskirjasto.fi/lnv00003
https://peda.net/kouvola/kot/materiaalit/itses%C3%A4%C3%A4tely

Voisiko olla ohjaustermi molempiin mainittuihin?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ehdotuksen mukaisesti ohjaustermit.
