### ISSUE TITLE
bayesilainen menetelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11628]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[bayesilainen menetelmä](http://www.yso.fi/onto/yso/p17803)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT bayesiläinen tilastotiede?

**Perustelut ehdotukselle**

https://tieteentermipankki.fi/wiki/Nimitys:bayesil%C3%A4inen_tilastotiede
https://fi.wikipedia.org/wiki/Bayesil%C3%A4inen_tilastotiede

On tehty Wikidatalinkitys.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Vaikuttaa myös siltä että bayesilaisia menetelmiä on useita, ks. esim. https://helda.helsinki.fi/handle/10138/12322 Ruotsinkielisillä yliopistojen sivuilla useinkin monikossa.

**Comment by ilona-x** [comment]
LCSH:
Bayesian statistical decision theory http://id.loc.gov/authorities/subjects/sh85012506
Variants
    Bayes' solution
    Bayesian analysis

**Comment by mirmaid** [comment]
Voi kyllä olla, että monikko liittyy enemmän menetelmän soveltamiseen eri aloilla - ja varmaan sitä voidaan soveltaa eri tavoilla, mutta alun perin kai kyse on yhdestä menetelmästä: https://en.wikipedia.org/wiki/Bayesian_inference. Tämä on linkattu wikipediassa suomen- ja ruotsinkielisiin tilastotiedettä käsitteleviin sivuihin, englanniksi bayesilaiselle tilastotieteelle on oma sivunsa. Mutta en ehdota sen ottamista erikseen, koska kuvailussa rajanveto olisi ihan mahdotonta.

**Comment by YSO-kokous** [comment]
**Päätös**

Jätetään päätermi yksikköön. Hyväksytään _bayesilaiset menetelmät_ ja _bayesilainen tilastotiede_ ohjaustermiksi.
