### ISSUE TITLE
tarkka-ampujat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11626]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tarkka-ampujat](http://www.yso.fi/onto/yso/p16429)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määriteltäväksi, mahdollisesti jaettavaksi?

**Perustelut ehdotukselle**

Kaksi eri merkitystä, Kielitoimiston sanakirja : https://www.kielitoimistonsanakirja.fi/#/tarkka-ampuja
Ruotsiksi historiallisessa merkityksessä (ja myös osana yksikköä) skarpskyttar, ks. esim.
https://fho.sls.fi/uppslagsord/19842/skarpskyttar/ Nykyään käytetään kyllä yleensä sv. prickskyttar. Ks. https://www.sanakirja.fi/custom/fi-en-sv/tarkka-ampuja
Wikipediassa yleistäkin sekavuutta. Ruotsiksi on näiden lisäksi myös termi "krypskytt" (osittain fi. sala-ampujat?)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
En kyllä tiedä miten nuo kaksi Kielitoimiston sanakirjan merkitystä olisivat kuvailijan erotettavissa?

**Comment by tpalonen** [comment]
En lähtisi jakamaan, vaan ottaisin mieluummin joustavamman tulkinnan tässä. Tässähän on pitkä historiallinen jatkumo ja teknologinen kehitys ja eri armeijoissa varmasti hieman eri käytännöt ja organisaatiorakenteet yms.

Käytetty Melindassa myös mm. tästä:
Tarkka-ammunta harrasteena / Juha Jormanainen
https://melinda.kansalliskirjasto.fi/byid/009853602

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.

**Comment by mariaforsen** [comment]
Sv. skarpskyttar > skarpskyttar och prickskyttar
svenska.se, Nationalencyklopedin
https://id.kb.se/term/sao/Krypskyttar
https://sv.wikipedia.org/wiki/Prickskytt 
https://sv.wikipedia.org/wiki/Skarpskytt
https://popularhistoria.se/krig/prickskytten-beundrad-hatad-och-helt-ovarderlig
https://www.kielitoimistonsanakirja.fi/#/tarkka-ampuja
https://fho.sls.fi/uppslagsord/19842/skarpskyttar/ 
https://www.sanakirja.fi/custom/fi-en-sv/tarkka-ampuja
