### ISSUE TITLE
linnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11624]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[linnat](http://www.yso.fi/onto/yso/p6790)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko mahdollista jakaa/tarkentaa minkälaisista linnoista on kyse? Sen mukaisesti saataisiin myös ruotsinkieliset termit oikein. 

**Perustelut ehdotukselle**

Kielitoimiston sanakirjassa:
1. entisaikainen varustettu väestön turvapaikka.  (sv. borg)
2. suuri ja komea hallitsijan tm. mahtihenkilön asuinrakennus t. yl. valtiolle kuuluva rakennus, palatsi. (sv. slott)

Melindassa käytetty molemmista linnatyypeistä, ja osassa viitteistä on nyt ruotsiksi virheellisesti vain slott, esim. Retkeilijän linnat ja rauniot / Tuomo Kesäläinen, Matka muinaiseen Suomeen : 11 000 vuotta ihmisen jälkiä / Ilari Aalto ja Elina Helkala..

Jos suomen kannalta ei haluta jakaa/tarkentaa, niin ruotsiksi pitää harkita muutosta > slott och borgar?

**Ehdottajan organisaatio**

ALLFO

**Comment by jtuohini** [comment]
Mikä on _slott_-sanan tarkka suhde _palats_-sanaan? YSO:ssahan on asiasana [**palatsit**](url), joka mielestäni vastaa parhaiten useita Googlen kuvahaun antamia "slott"-sanahaun tuloksia, vaikka kuvien rakennuksista linnoina puhuttaisiinkin. Puhekielessä suomen _linna_-sanaa käytetään usein myös palatseista ja kartanoista (esim. Mustion linna, Vanajanlinna – jonka tarkenteena YSO:ssa on muuten virheellisesti linna!), ja onhan se mainittuna ylläkin Kielitoimiston sanakirjan 2-merkityksessä, ainakin osin.

**Comment by mirmaid** [comment]
Aika vaikea jako varmaan olisi, jos esim. Olavinlinna/Olofsborg on ollut aiemmin nimeltään Nyslott.

**Comment by mariaforsen** [comment]
Ruotsiksi palats ja slott ovat ainakin hyvin läheisiä merkitykseltään.

**Comment by mirmaid** [comment]
^ Toki suomeksikin. Halutaanko siihen jotain muutosta? Molemmilla kuitenkin LCSH-vastine, joten en nyt riemusta hihkuen olisi yhdistämässä.

Drottningholmin linnan voi varmaan siirtää palatsien alle ja muuttaa eng. termin.

**Comment by jtuohini** [comment]
Ei suomeksi ainakaan linnoja ja palatseja voi yhdistää, kun ovat eri asia. Jos puhekielessä palatseja usein nimitetäänkin linnoiksi, niin tarkoite on ihan eri kuin palatsi-käsitteellä.

**Comment by mirmaid** [comment]
^ Lähinnä siis joku _linnat ja palatsit_ voisi tulla kysymykseen, mutta en itse ainakaan kannata.

**Comment by jtuohini** [comment]
Ei missään nimessä "linnat ja palatsit"! Ovat kaksi eri asiaa, vaikka puhekielessä useita palatseja nimitetään linnoiksi. Eli pitää olla kaksi eri asiasanaa ja niillä viittausmuodot kunnossa.

**Comment by mirmaid** [comment]
Paikannimet eivät ole johdonmukaisia sen paremmin kummallakaan kielellä, myös esim. Raseborgs slott on kuitenkin "borg". Ja Drottningholmin linna on myös ruotsiksi slott, mutta eng. palace. Ruotsinkielisissä wikipedia-artikkeleissa on käsitelty sekä terminologiaa että rakentamisen historiaa, mutta vaikka erottelu voidaan ruotsiksi tehdä (esim. keskiaikainen = borg), todellisten rakennusten nimet eivät siis välttämättä vastaa määrittelyjä.

Sekä suomeksi että ruotsiksi linna/slott on osin päällekkäinen palatsin kanssa (ja osin myös linnoituksen).

**Comment by mariaforsen** [comment]
On toki myös keskiajalla ollut "slott", mutta ne ovat sitten niitä melko "kehittyneitä" rakennuksia missä on sisustusta jne. Eli kuninkaiden ja aatelisten asuttamia, ei yksinkertaisia puolustukseen käytettyjä rakennuksia (eli Kielitoimiston ykkösmerkitys "entisaikainen varustettu väestön turvapaikka")

Yksittäisten rakennusten nimityksissä on vaihtelevuutta joo, joten niiden katsominen ei auta tähän. 

Mutta siis oliko tässä nyt toiveena että linnat jää suomeksi entiselleen, ja että sitä käytetään sekä ykkös- että kakkosmerkityksestä? Siinä tapauksessa pitää tosiaan ruotsiksi varmaan laittaa "borgar och slott".

**Comment by mirmaid** [comment]
^ Joo, en keksi mitään tapaa millä suomeksi voisi jaotella. Sisustus ja varustustaso on kuitenkin kehittynyt pikkuhiljaa ja alunperin vaatimaton puolustuslinna on voinut sitten lopuksi olla hyvinkin hieno kuninkaallisten asumus. Sellainen ihan pelkkä väestön turvapaikka olisi usein varmaan myös muinaislinna tai linnoitus. Kyllä yleensä varmaan ajatellaan että linnassa on vähintään jonkun verran kalustettuja asuintiloja.

**Comment by jtuohini** [comment]
Suomeksihan nämä on jo jaoteltu YSO:ssa: 1) **linnat**, 2) **palatsit**. Yksittäisten rakennusten niputtaminen sanastossa näiden alle, varsinkin väärän termin alle, on ehkä ongelman ydin. Joten voisiko nykyisiin asiasanoihin muotoilla määritelmän Kielitoimiston sanakirjan ja muiden lähteiden pohjalta?

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Ruotsiksi valitaan käytettäväksi termiksi och-muoto. Suomeksi ei muutoksia.

Keskustelua
Suomen kielessä ei ole ruotsia vastaavaa slott/borg-jakoa ja käsitejako olisi suomen kannalta hyvin hankala.
