### ISSUE TITLE
Tarton rauha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11627]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Tarton rauha](http://www.yso.fi/onto/yso/p17714)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaettavaksi?

**Perustelut ehdotukselle**

Voi viitata useampaan rauhaan, ks. https://fi.wikipedia.org/wiki/Tarton_rauha_(Viro)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Olisiko nämä sitten
Tarton rauha (Suomi)
Tarton rauha (Viro)

**Comment by mariaforsen** [comment]
Sv. freden i Dorpat > 
-freden i Dorpat (Finland) HT Dorpatfreden (Finland), freden i Tartu (Finland), fredsfördraget i Tartu (Finland), fredsfördraget i Dorpat (Finland) 
-freden i Tartu (Estland) HT Dorpatfreden (Estland), fredsfördraget i Tartu (Estland), fredsfördraget i Dorpat (Estland)  

https://www.uppslagsverket.fi/sv/sok/view-170045-Dorpatfreden
https://sv.wikipedia.org/wiki/Fredsf%C3%B6rdraget_i_Tartu
https://sv.wikipedia.org/wiki/Fredsf%C3%B6rdraget_i_Tartu_(Estland-Ryssland)
https://leht.se/ev100/1920.html
https://svenska.yle.fi/a/7-761096
https://popularhistoria.se/politik/historisk-snabbguide-eu-s-nya-medlemmar
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/estland
