### ISSUE TITLE
erityisalueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11623]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[erityisalueet](http://www.yso.fi/onto/yso/p13700)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voiko tätä käyttää myös muissa merkityksissä kuin aluesuunnittelun? 

**Perustelut ehdotukselle**

Ryhmä on 62, mutta sv. termi on monimerkityksinen, ks. https://svenska.se/tre/?sok=specialomr%C3%A5de&pz=8 Lisätään ruotsiksi tarkenne, jos suomeksi todella rajoittuu vain aluesuunnitteluun (tosin googlessa käytetään kyllä erityisalue-termiä myös aihealueena/osaamisalueena kuten ruotsiksikin). Melindassa kyllä lähinnä aluesuunnittelu-merkityksessä. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Periaatteessa suomeksikin voisi puhua jonkun erityisalueesta kyllä, mutta todennäköisemmin varmaan erikoisalasta. Ja näin terminä (ja monikollisena) tuntuisi kyllä aika kaukaa haetulta, jos aineisto käsittelisi esim. jonkun henkilön erityisen kiinnostuksen kohteita tai jonkun tieteenalan sisäisiä erikoistumisaloja (?).

**Comment by mariaforsen** [comment]
Riittäisikö siinä tapauksessa huomautuksena "Käytetään aluesuunnittelun yhteydessä" tms. ja ehkä jonkinlaisen ohjaustermin lisäys (mutta erikoisalat ei näköjään enää ole sanastossa)? Sen jälkeen voisimme tarkentaa ruotsiksi aluesuunnitteluun, ruotsiksi kun emme voida jättää ilman tarkennetta, sen takia kun specialområde niin vahvasti tulkitaan olevan "tiedon tai osaamisen alue".

**Comment by mirmaid** [comment]
^ Ei tarkenne voisi olla jotain region/plats -tyyppistä? Tuo aluesuunnittelu voi olla vähän turhan tarkka, kun ei näissä välttämättä kyse ole nimenomaan suunnitteluvaiheesta, vaan näkökulma voi olla johonkin toimintaan tietyllä (tavalla tai toisella erityisellä) alueella.

**Comment by mariaforsen** [comment]
Region ei käy (sillä on tarkkakin merkitys joka todennäköisesti aiheuttaisi hämmennystä), eikä varmaan plats, koska plats on merkitykseltään suppeampi kuin alue, mutta ehkä jokin muu (kunhan rajautuu fyysisiin alueisiin), geografiska?

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään ruotsiksi sulkutarkenne, mahdollisesti geografiska.
