### ISSUE TITLE
hydrokefalia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11625]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hydrokefalia](http://www.yso.fi/onto/yso/p17426)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: hydrokefalus

**Perustelut ehdotukselle**

https://finto.fi/mesh/fi/page/D006849

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. hydrocefali HT  hydrocefalus, vattenskalle 

se ne uppslagsverk/encyklopedi/lång/hydrocefalus
https://svenska.se/tre/?sok=hydrocefali&pz=1
https://svenska.se/tre/?sok=vATTENSKALLE&pz=1
https://mesh.kib.ki.se/term/D006849/hydrocephalus 
https://www.medicinskordbok.se/term/hydrocefalus
https://janusinfo.se/beslutsstod/faktaomolikafosterskador/fakta/hydrocefali.5.65173e411659127e422ca71e.html
https://www.hjarnfonden.se/om-hjarnan/diagnoser/hydrocefalus-vattenskalle/
https://neuroreg.se/hydrocefalus/
https://sv.wikipedia.org/wiki/Vattenskalle
https://www.netdoktor.se/neurologi/sjukdomar/hydrocefalus-vattenskalle/
