### ISSUE TITLE
tietoperustainen johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11629]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tietoperustainen johtaminen](http://www.yso.fi/onto/yso/p25368)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi tiedolla johtaminen

**Perustelut ehdotukselle**

Tiedolla johtaminen enemmän käytetty. Voisi ehkä kääntää päittäin?

**Ehdottajan organisaatio**

KK/HR

**Comment by ilona-x** [comment]
tiedolla johtaminen #11334
