### ISSUE TITLE
MetaEdit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11638]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[MetaEdit](http://www.yso.fi/onto/yso/p18429)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Nykyään MetaEdit+

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/MetaEdit%2B

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Eli versio 1 oli ilman plussaa ja sittemmin plussalla...aineistoista vanhin käsittelee ykkösversiota (yhteensä 7 viitettä). Jotenkin tuntuisi oikeammalta laittaa MetaEdit+ ohjaustermiksi, niin ei väittäisi sen ykkösversionkin olleen +.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _MetaEdit+_ ohjaustermiksi.
