### ISSUE TITLE
Gay pride

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11635]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Gay pride](http://www.yso.fi/onto/yso/p24816)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaus- tai päätermiksi Pride

**Perustelut ehdotukselle**

Nykyään käytetään yleensä inklusiivisempaa termiä Pride (ei koske pelkästään homoja). Ks. esim. https://seta.fi/sateenkaaritieto/sateenkaarisanasto/ Pride-haulla ei saa mitään YSOsta (suomeksi).

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Tarvitseeko tarkenteen jos vain Pride? Esim. muodossa _Pride (sukupuoli- ja seksuaalivähemmistöt)_?

**Comment by ilona-x** [comment]
YLEllä aiheena 
Pride-liike https://yle.fi/aihe/t/18-17758
Pride-kulkueet https://yle.fi/aihe/t/18-141914

--

Voisiko termi olla pride-liike?

YSOssa Gay Pride -termillä huomautus:
Tarkoittaa maailmanlajuista liikettä ja filosofiaa, jonka mukaan lesbot, homot, biseksuaalit ja transihmiset voivat olla ylpeitä seksuaalisesta suuntautumisestaan ja sukupuoli-identiteetistään.

**Comment by mariaforsen** [comment]
Olisiko pride-kulkueet sitten ohjaustermi vai erillisenä terminä?

**Comment by mirmaid** [comment]
^^ Mietin tätä itsekin ja varmaan yleensä soveltuu, mutta onko joskus liian suppea https://melinda.kansalliskirjasto.fi/byid/018792346?

**Comment by ilona-x** [comment]
> ^^ Mietin tätä itsekin ja varmaan yleensä soveltuu, mutta onko joskus liian suppea https://melinda.kansalliskirjasto.fi/byid/018792346?

Tuon teoksen [LC:n tietueessa](https://lccn.loc.gov/2022055024) on käytetty seuraavia termejä:
LC Subjects
    Gays--Travel--Guidebooks.
    Sexual minorities--Travel--Guidebooks.
    Gay travelers--Guidebooks.
    Gay business enterprises--Guidebooks.
    Gay pride celebrations--Guidebooks.

**Comment by mariaforsen** [comment]
Minusta molemmatkin voisivat olla sanastossa.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Vaihdetaan käsitteen käytettäväksi termiksi Pride (seksuaali- ja sukupuolivähemmistöt)
Ohjaustermeiksi Pride-liike ja Gay pride.
Tarkistetaan LCSH-linkitys.

YSO-ylläpito pohtinee, onko sulkutarkenne (seksuaali- ja sukupuolivähemmistöt) vai (sukupuoli- ja seksuaalivähemmistöt).

Käytettävästä termistä äänestettiin: Pride (seksuaali- ja sukupuolivähemmistöt) vs. Pride-liike. Ensin mainittu voitti äänin 11-3.

**Comment by mariaforsen** [comment]
Sv. Gay pride > pride (sexuella minoriteter och könsminoriteter)  HT pridefiranden, prideparader, pridefestivaler

https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/prider%C3%B6relsen
https://sv.wikipedia.org/wiki/Prider%C3%B6relsen 
https://termipankki.fi/tepa/fi/haku/pride
https://www.mediesprak.fi/pride-stort-eller-litet-p
https://sv.wiktionary.org/wiki/pride
https://sv.wikipedia.org/wiki/Pride
