### ISSUE TITLE
kiskoautot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11630]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kiskoautot](http://www.yso.fi/onto/yso/p15498)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "kiskobussit" tai tehdään siitä päätermi

**Perustelut ehdotukselle**

Kiskoauto voi olla myös aivan muuta kuin kiskobussi ("lättähattu"), esim. tavallinen auto, johon on vaihdettu renkaat kiskoilla ajamista varten, ks. esim. https://autotoday.fi/paivan-museoauto-volvon-kiskoauto-pv831-1953/ ja http://www.overdrive.fi/forum/threads/cadillac-1929-kiskoauto.262799/; vertaa myös https://fi.wikipedia.org/wiki/Kiskobussi

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Yhtenä ongelmana nykytilanteessa siis mm. LCSH-siltaus, joka selvästi kattaa vain kiskobussit.

**Comment by ilona-x** [comment]
YSOssa kiskoautojen yläkäsitteenä junat

Käytetty Melindassa 12 kertaa ja kaikissa viiitteissä on kyse junista.

Kielitoimiston sanakirja:

**kiskoauto** https://www.kielitoimistonsanakirja.fi/#/kiskoauto?searchMode=all
vars aik. kiskobussista. 

**kiskobussi**
dieselmoottorilla kulkeva moottorijuna. 

YLEllä käytetty enemmän kiskobussi-termiä:

**kiskobussi** https://yle.fi/aihe/t/18-221534
**kiskoauto** https://yle.fi/aihe/t/18-212067

**Comment by mirmaid** [comment]
Eli kiskobussit KT kiskoautot? Halutaanko myös Lättähatut ohjaustermiksi? Ei varmaan kuitenkaan Peräkylän Pendolinot 😄

**Comment by mariaforsen** [comment]
Ruotsiksi rälsbuss ja rälsbil ovat aika eri asioita: https://sv.wikipedia.org/wiki/R%C3%A4lsbil 
https://sv.wikipedia.org/wiki/R%C3%A4lsbuss

**Comment by mirmaid** [comment]
Suomeksi ainakin myös tässä merkityksessä, voi varmaan laittaa tarkenteen jos tarpeen.

**Comment by mariaforsen** [comment]
Ok eli kiskobussit OT kiskoautot (bussit) ? 
Ruotsiksi muutetaan sitten rälsbilar > rälsbussar

**Comment by jtuohini** [comment]
Olisiko sittenkin paras vaihtoehto kaksi erillistä asiasanaa seuraavaan tapaan?
1. _**kiskoautot**_ (ruotsiksi _**rälsbilar**_), LT **autot**
2. _**kiskobussit**_ (ruotsiksi _**rälsbussar**_), KT _dieselmoottorivaunut_, _kiskoautot (kiskobussit)_, _lättähatut (kiskobussit)_, _moottorivaunut_, LT **junat**

Finnasta löytyy aineistoa kummastakin aiheesta, jälkimmäisestä toki eniten, mutta edellisestä myös: https://finna.fi/Record/musketti_rautatie.M014:VR1:5478?sid=3099847224, https://finna.fi/Record/musketti_rautatie.M014:ND4:373?sid=3099847224, https://finna.fi/Record/lusto.knp-90305?sid=3099847224 jne.

**Comment by mirmaid** [comment]
^^ Tai ehkä selkeämpää olisi kiskoautot (junat), koska eihän nämä busseja ole - tai (kiskobussit) kuten Jaakko ehdottaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Päätermiksi _kiskobussit_, ohjaustermeiksi _kiskoautot (junat)_, _lättähatut (junat)_.

**Comment by jtuohini** [comment]
Nyt varmaan meni ohjaustermeissä jotain pieleen, jos mukaan tuli _kiskoautot (autot)_ KÄ _**kiskobussit**_, kun juuri ne ovat eri asia! Ja itse asiassa junankin määritelmä on hieman ongelmallinen suhteessa kiskobusseihin: "juna [on yhtä kuin] veturin ja rautatievaunujen jono" (https://www.kielitoimistonsanakirja.fi/juna). Tämä sana tuli mieleen tarkistaa Kielitoimiston sanakirjasta vasta nyt eikä harmillisesti aiemman kommenttini laatimisen yhteydessä.

**Comment by mariaforsen** [comment]
Päätös oli ymmärtääkseni että pidetään kaksi erillistä termiä:
-kiskobussit OT kiskoautot (junat), lättähatut = sv. rälsbussar
-kiskoautot (autot) = sv. rälsbilar
