### ISSUE TITLE
suuret kuolonvuodet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11634]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suuret kuolonvuodet

**Ehdotettu termi ruotsiksi**

Hungersnöden 1695–1697

**Ehdotettu termi englanniksi**

Great Famine of 1695–1697

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

On merkittävä tapahtuma Suomen historiassa. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [suuret nälkävuodet](http://www.yso.fi/onto/yso/p18028)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Suuret_kuolonvuodet)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Jumalan vihan ruoska : suuri nälänhätä Suomessa 1695-1697 / Mirkka Lappalainen.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [suuret kuolonvuodet](http://finto.fi/yse/fi/page/Y511634)

**Comment by mirmaid** [comment]
2 viitettä Melindassa. Ehkä määritelmä tälle, ellei sitten jopa aikatarkennetta, tosin tutkijat varmasti käyttävät näitä oikein ja sitä myöten kuvailussakin erehdyksen riski aika pieni.

**Comment by mariaforsen** [comment]
Sv. stora hungersnöden (1695–1697) HT hungersnöden 1695–1697
https://historia.hel.fi/sv/vandpunkter/forstorelse-och-ateruppbyggnad/hungersnoden-1695-1697-i-helsingfors
https://sv.wikipedia.org/wiki/Hungersn%C3%B6den_1695%E2%80%931697
https://tieteentermipankki.fi/wiki/Nimitys:den_stora_hungersn%C3%B6den

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan sanastoon, lisätään aikatarkenteet.
