### ISSUE TITLE
idyllit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11631]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[idyllit](http://www.yso.fi/onto/yso/p27463)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Termin määrittely ja/tai mahdollisesti jako, sekä ryhmän muokkaus?

**Perustelut ehdotukselle**

Termi sinänsä monimerkityksinen, mutta ryhmänä vain 87. Melindassa käytetty myös maalaustaiteesta, sekä ainakin ruotsiksi myös 1. merkityksessä: https://www.kielitoimistonsanakirja.fi/#/idylli?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Tieteen termipankki: rauhallisen, viattoman, yksinkertaisen maalaiselämän tai luonnonläheisyyden idealisoiva runo- tai proosamuotoinen kuvaus; sopusointuinen, onnellinen olotila

**Comment by mirmaid** [comment]
https://melinda.kansalliskirjasto.fi/byid/009362023

**Comment by mariaforsen** [comment]
Eli yllä mainitussa viitteessä varmaan kyseessä ykkösmerkitys "sopusointuinen, rauhallinen olotila."

**Comment by mirmaid** [comment]
^ Joo, näitä oli pari Melindan 40 viitteestä, joissa oli käytetty muuten kuin kirjallisuuden tai kuvataiteen yhteydessä.

**Comment by fantsby-m** [comment]
Sävellyksiä myös, joissa ainakin nimekkeessä Idylli (tms) mutta ei ole YSO-asiasanaa käytetty, SLM-termiä on käytetty jokunen kerta, esim.
https://melinda.kansalliskirjasto.fi/byid/006911650
https://melinda.kansalliskirjasto.fi/byid/017577822

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään käsitteelle YSO-ryhmiä ja tarkistetaan hierarkia.

Keskustelua
Katsottiin paremmaksi, että käsite on vapaatulkintainen ja vapaakäyttöinen kuin että jaettaisiin käsite eri taiteenaloihin yms. Eli käsitettä saa jatkossakin käyttää eri taiteenlajeista ja laajemminkin.
