### ISSUE TITLE
sähköjohdot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11639]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähköjohdot](http://www.yso.fi/onto/yso/p185)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi sähkökaapelit?

**Perustelut ehdotukselle**

Mahdollisesti synonymeja

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. elkablar

**Comment by ilona-x** [comment]
SAO:
Elkablar  https://id.kb.se/term/sao/Elkablar
Elektriska ledningar https://id.kb.se/term/sao/Elektriska%20ledningar

LCSH:
Electric wire http://id.loc.gov/authorities/subjects/sh85042050
Electric cables http://id.loc.gov/authorities/subjects/sh85041594

**Comment by mariaforsen** [comment]
Ruotsin kannalta voisi tosiaan olla elledningar ja elkablar erikseen, mutta ei ole välttämätöntä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermi _sähkökaapelit_.
