### ISSUE TITLE
angina

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11644]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[angina](http://www.yso.fi/onto/yso/p18672)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko paras mahdollinen englanninkielinen termi?

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Angina

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Englanninkielinen termi on yksiselitteisesti väärä. Suomeksikin parempi päätermi olisi varmaankin _nielutulehdus_, sille ohjaustermeiksi (kuten MeSHissä) _faryngiitti, nielun tulehdus, pharyngitis, ja angiina (nielutulehdus)_? Ja muut kielet myös kuten MeSH?

**Comment by mariaforsen** [comment]
Sv. angina > svalginflammation HT faryngit
https://finto.fi/mesh/fi/page/D010612
https://www.kaypahoito.fi/sv/khr00002
https://finto.fi/tero/sv/page/D010612
https://www.medicinskordbok.se/term/faryngit
sök/?t=uppslagsverk&q=faryngit
https://sv.wikipedia.org/wiki/Faryngit
