### ISSUE TITLE
slasher

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11640]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

slasher

**Ehdotettu termi ruotsiksi**

slasher

**Ehdotettu termi englanniksi**

slasher film

**Tarkoitusta täsmentävä selite**

LoC: "Films that feature a psychotic killer who stalks and murders a series of victims, usually with unconventional weapons. For films that feature graphic depictions of gore, hard-core violence, and murder see Splatter films."

**Perustelut ehdotukselle**

Toivoisin termiä myös ja erityisesti SLM-sanastoon, jossa jo on splatter. Tämän tästä tulee kirjastoonkin elokuvia, jotka määritellään slasher-elokuvaksi (vaikka Wikipedia-artikkeleissa genre on jo jäänyt historiaan)
https://en.wikipedia.org/wiki/Slasher_film

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://slasher films)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pearl DVD: Melinda 018811718/lt

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [slasher](http://finto.fi/yse/fi/page/Y511640)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Slasher

**Comment by mirmaid** [comment]
Ryhmä kannatti termin lisäämistä, mutta sen rajaus ja hierarkia herätti keskustelua. Sanastossa on ennestään splatter, jota ei ole tarmitasolla rajattu käytettäväksi elokuvista. Yläkäsite on fiktioelokuvat, todennäköisesti koska elokuvat on tyypillisin aineistotyyppi splatter-genren käytöstä. RT:nä on kauhusarjakuvat. Sanastossa on myös joitakin muita vastaavia termejä, joissa termimuoto antaa mahdollisuuden käyttää eri aineistotyyppien kuvailussa. Hierarkiaratkaisut saattavat vaihdella, koska linjausta SLM:n hierarkiasta ollaan vasta laatimassa. Ei voida kuitenkaan olettaa, että hierarkia riittäisi ohjaamaan kuvailijaa, joka ei välttämättä edes näe hierarkiaa kuvailua tehdessään. 

Linjausten kannalta on olennaista, sallitaanko monihierarkia, esim. splatter YK kauhuelokuvat, kauhukirjallisuus, vai sijoitetaanko aineistotyypistä riippumattomat termit omaan hierarkiapolkuunsa (ehdotettu esim. "tyylit" tai "useille aineistotyypeille soveltuvat termit"), tai soveltuvalle ylemmälle hierarkiasatolle (esim. tuhkimotarinat kertomusten alle, jos sen ei katsota rajautuvan kirjallisuuteen, true crime ei-fiktiiviset aineistot -hierarkiaan). 

Sovittiin, että etsitään vastaavia esimerkkejä ja yritetään jo ennen seuraavaa kokousta muodostaa oma näkemys ratkaisusta.

**Comment by mirmaid** [comment]
Esimerkkejä gernretermeistä, joita voi käyttää useille aineistotyypeille (esim. elokuvat ja televisio-ohjelmat, liikkuva kuva ja painettu aineisto, kuunnelma ja painettu aineisto jne.). Enimmäillään näillä on tällä hetkellä viisikin yläkäsitettä, joten termien jako aineistotyypeittäin tarkempiin termeihin saattaisi edellyttää joissakin tapauksissa monia suppeita korvaajatermejä. Toisaalta joissakin tapauksissa tällainen jako on historiallisista syistä jo olemassa (fantasia, scifi). 

allegoriat
animet
avaruusoopperat
dystopiat
esiosat
haastattelut
huumori
klassikot
komediat
maaginen realismi
mainokset
opetusmateriaali
robinsonadit
splatter
steampunk
true crime
tuhkimotarinat
urbaani fantasia
uusi aalto (toistaiseksi vain musiikki-tarkenteella)

**Comment by mirmaid** [comment]
Kaikkien tämänkaltaisten termien suhteen ei toki ole välttämätöntä päätyä samaan ratkaisuun, vaan on mahdollista ottaa joissakin tapauksissa suppeampi termi, jos katsotaan termiä tarvittavan meillä vain yhden aineistotyypin kuvailussa, ja silti säilyttää muita termejä, joita voidaan käyttää useille aineistotyypeille. Linjauksissa olisi kuitenkin hyvä jollain lailla selventää, millä periaatteella ratkaistaan se, otetaanko uusia termejä hyväksyttäessä sanastoon tarkempia termejä vai aineistotyypistä riippumattomia. Usein käy niin, että tietty genre vakiintuu ensin jonkin aineistotyypin sisällä, ja leviää myöhemmin myös muihin aineistotyyppeihin (esim. digitaalisten pelien maailmaan levinneet genret, jotka ovat vakiintuneet ensin kirjallisuuteen ja myöhemmin elokuvaan/sarjoihin). Toisaalta myös itse aineistotyypit muuntuvat tekniikan myötä (radio-ohjelmat/kuunnelmat/podcastit tai tv-ohjelmat/netissä esitettävät ohjelmat).

**Comment by mariaforsen** [comment]
Pitäisikö myös miettiä sitä että miten usein kirjastonkäyttäjä haluaisi löytää suoraan tietyssä formaatissa olevaa aineistoa, eli onko niin että hakija on usein kiinnostunut esim. slasherista riippumatta onko formaattina kirja, elokuva tms.? Vai haluavatko tiedonhakijat (entä tutkijat?) yleensä nimenomaan tietyssä formaatissa olevaa kun hakee, esim. niin että nimenomaan kirjat kiinnostavat, ei niinkään elokuvat. Vertailuna niin SAOssa nämä taitavat olla yleensä erikseen.

**Comment by mirmaid** [comment]
Slasher /SLM.

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Sv. slasher
