### ISSUE TITLE
kameli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11649]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kameli](http://www.yso.fi/onto/yso/p19201)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT kaksikyttyräinen kameli ? Tarvitaan myös uutena erillisenä terminä dromedaari lat. Camelus dromedarius 

**Perustelut ehdotukselle**

https://laji.fi/taxon/MX.47945
https://laji.fi/taxon/MX.47946
Kameli ja dromedaari ovat erillisiä lajeja ja ainakin ruotsiksi "kamel" viittaa vain Camelus bactrianukseen. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Viitteissä näyttää pääosin olevan kyse aineistoista, joissa kamelin tarkka laji joko on epärelevantti tai ei käy ilmi. Ruotsiksikin muuten "kamelkapplöpning är en sport där dromedarer tävlar mot varandra". Toisaalta laajemmin kamelit = kamelieläimet, joka kattaa myös esim. laamat.

**Comment by mariaforsen** [comment]
Melindassa löytyy aineistoa dromedaareista ja "kameli"-termiä ei ole mahdollista käyttää niistä, joten olisiko kuitenkin hyvä ottaa tämä harvinaisen selkeä laji omana terminä?

**Comment by mirmaid** [comment]
Kyllä sen siis voi ottaa, mutta aika monissa Melindan aineistoissa voi olla mahdoton päätellä kumpi on oikea termi. Ei niitä onneksi ihan määrättömästi ole.

**Comment by mirmaid** [comment]
Ehdotus siis
muutos: kameli KÄ kaksikyttyräinen kameli
lisätään: kameli (yksikyttyräinen kameli) KÄ dromedaari

**Comment by mariaforsen** [comment]
Laji.fissä päätermeinä ovat kuitenkin "kameli" ja "dromedaari":
https://laji.fi/taxon/MX.47945 
https://laji.fi/taxon/MX.47946

**Comment by mirmaid** [comment]
^ Kameli voi eläintieteen ulkopuolella tarkoittaa kumpaa vain, joten virheen mahdollisuus jää jos toisen päätermi on kameli. Tietysti se helpottaa niissä tilanteissa, joissa tuntuu hassulta käyttää tarkempaa (lautapelit tai lastenkirjat). Eli mun puolestani voi myös olla kaksikyttyräinen kameli KÄ kameli.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kameli_ ja _dromedaari_.

**Comment by mariaforsen** [comment]
Sv. dromedar HT enpucklig kamel
