### ISSUE TITLE
SURFACE

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11645]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[SURFACE](http://www.yso.fi/onto/yso/p18763)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Microsoft Surface?

**Perustelut ehdotukselle**

Vai mihin tämä viittaa?

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Melindassa käytetty ilmeisen erilaisissa merkityksissä (5 kertaa yhteensä)

**Comment by mirmaid** [comment]
On kyllä todella erikoinen valikoima viitteitä. Ehdotan että poistetaan tämä käsite.
