### ISSUE TITLE
luumu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11648]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luumu](http://www.yso.fi/onto/yso/p19192)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi luumupuu

**Perustelut ehdotukselle**

https://laji.fi/taxon/MX.38935

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Näyttää siltä että tarvitaan myös luumu(t) erikseen (YK hedelmät). Vrt. omena ja omenapuut.

**Comment by mirmaid** [comment]
Appelsiini, päärynä ym. vain yksi termi.

**Comment by mariaforsen** [comment]
Olen kuvailijana joskus kaivannut hedelmä-termejä, ja päätynyt laittamaan vain "hedelmät" (aika laaja termi kyllä), koska osa hedelmistä ovat nyt pelkästään kasvihierarkiassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Päätettiin lisätä käyttöhuomautus. Omena- ja kirsikka -käsitteitä tarkastellaan mm. hierarkian sekä hedelmän ja puun suhteiden kannalta.

**Comment by mirmaid** [comment]
^ Lisättiin ohjaustermi. Todettiin kuitenkin, että hedelmien lisäksi muillekin viljelykasveille voisi perustellusti ehdottaa vastaavaa huomautusta, joten joko huomautus pitäisi lisätä hyvin suurelle käsitejoukolle, tai löytää jokin syy miksi se on tarpeen tietyille käsitteille, mutta ei muille. Pidettiin parempana säilyttää mahdollisuus tarvittaessa lisätä erillinen termi kasville ja sen käytettävälle osa. Pohdittuja käsitteitä mm. viinirypäle/aitoviiniköynnös, mansikat/puutarhamansikka, herukat, ruusut/ruusunmarja, peruna, viljakasvit-käsitteen alakäsitteet.
