### ISSUE TITLE
jokamiehenoikeudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11641]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[jokamiehenoikeudet](http://www.yso.fi/onto/yso/p5265)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermiksi jokaisenoikeudet

**Perustelut ehdotukselle**

Esim.
https://yle.fi/a/74-20038340

**Ehdottajan organisaatio**

KK/MP

**Comment by ilona-x** [comment]
jokamiehenoikeudet #11632

**Comment by mirmaid** [comment]
Luin ensin, että ehdottaja kannatti päätermin muutosta muotoon jokanaisenoikeudet 💃

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan muotoon _jokaisenoikeudet_.
