### ISSUE TITLE
kaakao

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11647]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kaakao](http://www.yso.fi/onto/yso/p8376)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne?

**Perustelut ehdotukselle**

Monimerkityksinen, sanastossa on myös muita kaakaotermejä, mutta tätä on käytetty Melindassa muustakin kuin juomasta (nyt yläkäsitteenä).
https://www.kielitoimistonsanakirja.fi/#/kaakao?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Ehdotus: kaakao (juomat)

Voi olla, että sopii korjauksissa aika harvoin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kaakao (juomat)_.

**Comment by mariaforsen** [comment]
Sv. kakao > kakao (drycker) HT varm choklad, choklad (drycker)
https://kaino.kotus.fi/fsob/?p=qs-
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_292561dc0d8daa6837c4b1ebe48744e7&list_id=1&keyword=kaakao&word=kaakaoarticle&fsob_id=FSOB_1fd97e8482e10edebbb498f6b5a07871&list_id=1&keyword=kakao&word=kakao
https://svenska.se/tre/?sok=chocklad&pz=1
https://www.sanakirja.fi/custom/en-sv-fi/kaakao
