### ISSUE TITLE
metagenomiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11657]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

metagenomiikka

**Ehdotettu termi ruotsiksi**

metagenomik

**Ehdotettu termi englanniksi**

metagenomics

**Tarkoitusta täsmentävä selite**

https://tieteentermipankki.fi/wiki/Mikrobiologia:metagenomiikka

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2012000572), [wikipedia](https://en.wikipedia.org/wiki/Metagenomics)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Metabolomics and metagenomics in hypertension https://urn.fi/URN:ISBN:978-951-29-8896-9

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
tähänkin väitökseen olisi voinut käyttää: http://hdl.handle.net/10138/349862

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D056186

**Comment by mariaforsen** [comment]
Sv. metagenomik HT genetisk metaanalys
https://mesh.kib.ki.se/term/D056186/metagenomics
