### ISSUE TITLE
chili

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11655]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[chili](http://www.yso.fi/onto/yso/p19645)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: chilipippuri

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/chilipippuri?searchMode=all

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
ruotsiksi näyttää jo olevan YSOssa
chili KT chilipeppar

**Comment by mariaforsen** [comment]
Aivan ja yläkäsite on mausteet, joten se lienee ok.
