### ISSUE TITLE
simppukalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11653]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[simppukalat](http://www.yso.fi/onto/yso/p19465)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

 Oikea lat. Scorpaeniformes?

**Perustelut ehdotukselle**

Varmistetaan ennen ruotsin termin korjaamista, että oikea lat. todella on Scorpaeniformes, eikä Cottoidei (kuten laji.fi:ssä tässä: https://laji.fi/taxon/MX.53314 )
https://fi.wikipedia.org/wiki/Simppukalat 
https://luontoportti.com/t/1957
https://laji.fi/taxon/MX.5073983/identification
https://kalassa.net/kalapedia/index.php/Simppukalat
https://tieteentermipankki.fi/wiki/El%C3%A4intiede:simppukalat

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Scorpaeniformes on laajin, Lafi.fi:ssä sekä se, että alalahko ovat nimeltään simppukalat. Eikö meidän siis ole järkevintä päättää, että se on tuo laajin vaihtoehto?
