### ISSUE TITLE
anniskeluoikeudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11654]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[anniskeluoikeudet](http://www.yso.fi/onto/yso/p19611)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi OT anniskeluluvat, vai mahdollisesti erillisenä terminä?

**Perustelut ehdotukselle**

Todettu wikidatalinkityksen yhteydessä.
Ks. https://www.kielitoimistonsanakirja.fi/#/anniskeluoikeus?searchMode=all

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
OIKO;
anniskelulupa http://www.yso.fi/onto/oiko/p991

**Comment by mirmaid** [comment]
Muutetaanko päätermi? Anniskeluoikeuksista on puhuttu v. 1968 Alkoholilaissa, mutta seuraavassa (1994) jo alkoholiluvista, samoin nykyisessä laissa (2017).

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**anniskelulupa** https://www.kielitoimistonsanakirja.fi/#/anniskelulupa?searchMode=all
aluehallintoviraston määräehdoin myöntämä lupa alkoholin anniskeluun.
Ravintolalle myönnetty anniskelulupa.

**anniskeluoikeus** https://www.kielitoimistonsanakirja.fi/#/anniskeluoikeus?searchMode=all
us. mon. vrt. anniskella; aik. anniskeluluvasta.
Ravintolalla oli täydet anniskeluoikeudet.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan päätermiksi _anniskeluluvat_.

**Comment by mariaforsen** [comment]
Sv. serveringstillstånd HT utskänkningstillstånd
https://sv.wikipedia.org/wiki/Utsk%C3%A4nkningstillst%C3%A5nd
https://avi.fi/sv/valj-arende/foretag-eller-organisation/tillstand-anmalningar-och-ansokningar/alkohol-och-servering/serveringstillstand
https://www.mediesprak.fi/restauranger-och-serveringstillst%C3%A5nd
https://www.finlex.fi/sv/laki/ajantasa/1994/19941346
