### ISSUE TITLE
Lopen vanha kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11658]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Lopen vanha kirkko

**Ehdotettu termi ruotsiksi**

Loppis gamla kyrka

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Ks. myös
https://www.lopenseurakunta.fi/vanha-kirkko

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 Santa Pirjon kirkko (fi), Sankta Birgittakyrkan (sv)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Lopen_vanha_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Suomen katolisen ajan puukirkko :Lopen "Santa-Pirjon" kirkon vaiheita /Sakari Vuorenrinne.

**Ehdottajan organisaatio**

KK/MP

**Comment by mariaforsen** [comment]
Sv. HT Sankta Birgittakyrkan (Loppis)
