### ISSUE TITLE
Pohjois-Italia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11651]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Pohjois-Italia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Finto-palaute. Sanastossa on Etelä-Italia KÄ Mezzogiorno

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melindassa yli 100 viitettä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. Norra Italien HT Norditalien
Wikipedia: "Italien är inofficiellt indelat i tre områden: Norra Italien..."
https://www.wikidata.org/wiki/Q4345530
