### ISSUE TITLE
valkoiset (Venäjän sisällissota)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11668]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

valkoiset (Venäjän sisällissota)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Slaavilaisessa kirjastossa on paljon aineistoa, joka käsittelee punaisia ja valkoisia Venäjän sisällissodassa. YSO:ssa nyt olevat termit "punaiset" ja "valkoiset" liittyvät vain Suomen sisällissotaan.

**Ehdotettu yläkäsite YSOssa (LT)**

 [toimintaan liittyvä rooli](http://www.yso.fi/onto/yso/p418)

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540), [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [Venäjän sisällissota](http://www.yso.fi/onto/yso/p28370), [valkokaartit](http://www.yso.fi/onto/yso/p10969)

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Ven%C3%A4j%C3%A4n_valkoinen_armeija), [](https://www.wikidata.org/wiki/Q104309)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

uusimmat kirjat: https://kansalliskirjasto.finna.fi/Record/fikka.5602394?sid=3022644698
https://kansalliskirjasto.finna.fi/Record/fikka.5629873?sid=3022644263

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [valkoiset (Venäjän sisällissota)](http://finto.fi/yse/fi/page/Y511668)

**Comment by mariaforsen** [comment]
Sv. vita (ryska inbördeskriget)
"Jämsides med huvudmotsättningen mellan röda och vita fanns andra kampavsnitt som delvis överlappade den stora konflikten. Redan under vintern 1917–18 kämpade kosackförband vid floden Don och i Ural mot bolsjevikerna och anslöt sig därefter till de vita styrkorna"  /https://popularhistoria.se/krig/ryska-inbordeskriget-1918-22

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
