### ISSUE TITLE
Kimble (peli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11664]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kimble (peli)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [lautapelit](http://www.yso.fi/onto/yso/p2758)

**Ehdotetut temaattiset ryhmät**

 [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Kimble)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kimble-lautapelin kestävä tuotesuhde – Kulttuurituotteiden uustuotantoprosessit https://urn.fi/URN:ISBN:978-951-29-8863-1

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. Kimble (spel) 
https://roligabradspel.se/alla-spel/familjespel/kimble
https://www.partykungen.se/kimble-40327.html
