### ISSUE TITLE
selkäydinstimulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11663]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

selkäydinstimulaatio

**Ehdotettu termi ruotsiksi**

Ryggmärgstimuleringv

**Ehdotettu termi englanniksi**

  Spinal Cord Stimulation 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

FinMeSH-käsite, joka olisi hyvä saada YSOon nyt, kun Alma-kirjastojen Melinda-integraatiota on tiukennettu sanastojen suhteen. Melindassa 12 kertaa (monot + artikkelit).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [kiertäjähermon stimulaatio](http://www.yso.fi/onto/yso/p39581), [syväaivostimulaatio](http://www.yso.fi/onto/yso/p38675), [transkraniaalinen tasavirtastimulaatio](http://www.yso.fi/onto/yso/p38969)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://id.nlm.nih.gov/mesh/2022/D062187.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-61-4867-0

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. ryggmärgsstimulering HT ryggmärgstimulering /mesh
https://sv.wikipedia.org/wiki/Ryggm%C3%A4rgsstimulering
