### ISSUE TITLE
pikornavirukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11667]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pikornavirukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/173109

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pikornavirukset](http://finto.fi/yse/fi/page/Y511667)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D010849

**Comment by mariaforsen** [comment]
Sv. picornavirus HT Picornaviridae
