### ISSUE TITLE
punaiset (Venäjän sisällissota)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11669]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

punaiset (Venäjän sisällissota)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Slaavilaisessa kirjastossa on paljon aineistoa, joka käsittelee punaisia ja valkoisia Venäjän sisällissodassa. YSO:ssa nyt olevat termit "punaiset" ja "valkoiset" liittyvät vain Suomen sisällissotaan.

**Ehdotettu yläkäsite YSOssa (LT)**

 [toimintaan liittyvä rooli](http://www.yso.fi/onto/yso/p418)

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540), [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [punakaartit](http://www.yso.fi/onto/yso/p10968), [Venäjän sisällissota](http://www.yso.fi/onto/yso/p28370)

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Ven%C3%A4j%C3%A4n_sis%C3%A4llissota#Puna-armeijan_organisointi), [](https://fi.wikipedia.org/wiki/Puna-armeija)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://kansalliskirjasto.finna.fi/Record/fikka.5602394?sid=3022644698

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [punaiset (Venäjän sisällissota)](http://finto.fi/yse/fi/page/Y511669)

**Comment by mariaforsen** [comment]
Sv. röda (ryska inbördeskriget)

**Comment by mirmaid** [comment]
Sanastossa on nyt vain _bolševismi_. _Bolševikit_ käytetty 36 kertaa vapaana avainsanana Melindassa - on toki kattavuudeltaan eri, mutta sisällissodan yhteydessä melko päällekkäinen. Eng. reds/whites vaiko red army (tarkenne) / white army?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
