### ISSUE TITLE
taljat (nahkatuotteet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11677]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taljat (nahkatuotteet)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 9

**Ehdotettu yläkäsite YSOssa (LT)**

 [nahkatuotteet](http://www.yso.fi/onto/yso/p6630)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MAO/TAO](http://www.yso.fi/onto/mao/p1686)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Porontaljan kuivauksen massatuotanto https://urn.fi/URN:ISBN:978-952-316-445-1

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [taljat (nahkatuotteet)](http://finto.fi/yse/fi/page/Y511677)

**Comment by mariaforsen** [comment]
Sv. fällar HT hudar (fällar)
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_758ef08366d3bb374fd6dcdf5f800860&list_id=1&keyword=talja&word=talja
https://svenska.se/tre/?sok=f%C3%A4ll&pz=1

**Comment by mirmaid** [comment]
Onnistuukohan englanniksi erottelu vuodat/taljat? Ehkä tarkenteella (material tms.).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by tpalonen** [comment]
https://www.hannanore.fi/perinnenahkurin-sanasto/
