### ISSUE TITLE
uusmedia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11676]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[uusmedia](http://www.yso.fi/onto/yso/p5575)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

voisiko tämän päätermiksi mahdollisesti muuttaa digitaalinen media?

**Perustelut ehdotukselle**

Aineistoissa käytetään termiä digitaalinen media, ja uusmedia tuntuu hieman vanhentuneelta termiltä. 

https://fi.wikipedia.org/wiki/Uusmedia
https://fi.wikipedia.org/wiki/Digitaalinen_media

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Käytetty niin paljon, että toivottavasti muutettavissa suoraan korjausajolla...

**Comment by ilona-x** [comment]
LCSH:
Digital media http://id.loc.gov/authorities/subjects/sh98006600
    Variants
        Electronic media
        New media (Digital media)

**Comment by ilona-x** [comment]
fi        verkkomedia; digitaalinen media; digimedia; uusmedia
mieluummin kuin: uusi media
en      digital media; new media

määritelmä
vuorovaikutteiset, digitaaliset viestintävälineet sisältöineen

huomautus
Verkkomedian piirteitä ovat reaaliaikaisuus, päivitettävyys, ympäristön virtuaalisuus sekä tiedon haku- ja suodatusmahdollisuudet.

Lähde: Tietotekniikan termitalkoot, 2012-10-05 https://termipankki.fi/tepa/fi/haku/uusmedia

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
[uusmedia](https://www.kielitoimistonsanakirja.fi/#/uusmedia?searchMode=all)
tietotekniikkaan perustuvista, us. vuorovaikutteisista sähköviestinnän muodoista kuten tietoverkon välityksellä käytettävistä sovelluksista, sähkökirjoista, tietokonepeleistä yms.; tällaisia tekevästä tuotannonalasta. 

YSO:n huomautus:
[uusmedia](http://www.yso.fi/onto/yso/p5575)
Tarkoittaa tietokonevälitteistä, vuorovaikutteista sähköviestinnän muotoa kuten tietoverkko-, hyper- ja multimediasovellusta.
Lähde: Kielitoimisto

**Comment by ilona-x** [comment]
YLE:n uutisia aiheesta uusmedia:
https://yle.fi/uutiset/18-207443

**Comment by ilona-x** [comment]
Melindassa käytetty uusmedia-termiä 2966 kertaa, joten kovin kattavasti ei viitteitä pysty käymään läpi, mutta tässä joitain havaintoja. 

- Kävin läpi 1990-luvulla julkaistut viitteet eikä sieltä mielestäni noussut esiin sellaisia, missä termimuutos uusmedia->digitaalinen media tuntuisi huonolta. 
- Ja huomiona, että jo 1990-luvulla uusmedia-termillä kuvailtujen aineistojen nimekkeissä/muissa tiedoissa näkyi esiintyvän digitaalinen media -termiä. Valitsin 1990-luvun viitteet, kun Wikipedian mukaan "[Uusmedia ](https://fi.wikipedia.org/wiki/Uusmedia)(myös ”uusi media”) on 1990-luvulla syntynyt nimike vuorovaikutteiselle digitaaliselle medialle.."

- Melinda-tietueissa uusmedia-sana on esiintynyt nimekkeissä 206 kertaa, mutta vain 7 kertaa v. 2010 jälkeen ilmestyneissä aineistoissa.
- katsoin myös joitain viitteitä vuosilta 2018-2020 ja näissä uudemmissa viitteissä digitaalinen media tuntuisi paremmalta termiltä kuin uusmedia

**Comment by mariaforsen** [comment]
Sv. nya media > digitala medier HT digital media 

https://id.kb.se/term/sao/Digitala%20medier
https://www.rikstermbanken.se/search?q=digitala+medier&s=termer

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Vaihdetaan käsitteen ohjaustermiksi uusmedia ja käytettäväksi termiksi digitaalinen media.
