### ISSUE TITLE
B-imusolut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11675]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

B-imusolut

**Ehdotettu termi ruotsiksi**

B-lymfocyter

**Ehdotettu termi englanniksi**

B-Lymphocytes 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [lymfosyytit](http://www.yso.fi/onto/yso/p2766)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 B-lymfosyytit, B-solut

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D001402), [Wikipedia](https://fi.wikipedia.org/wiki/B-solu), [LCSH](http://id.loc.gov/authorities/subjects/sh85010707)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

B Cell Activation and Antibody Responses: The role of vesicle trafficking and Rab GTPases https://urn.fi/URN:ISBN:978-951-29-8922-5

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [B-imusolut](http://finto.fi/yse/fi/page/Y511675)

**Comment by ilona-x** [comment]
toinen väitös:
Antigen processing and intracellular trafficking in B cells https://urn.fi/URN:ISBN:978-951-29-8966-9

**Comment by mariaforsen** [comment]
Sv. B-lymfocyter HT B-celler

**Comment by FinMeSHienPaimentaja** [comment]
Mieluummin "B-lymfosyytit" ensisijaiseksi, samoin kaikki termit, joissa esiintyy "imusolut" -> "lymfosyytit".  "Imusolut" sisältävät voi jättää ohjausterm(e)iksi. "Imusolut" on mielestäni aika vanhahtava.

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan käyttöä.
