### ISSUE TITLE
varautuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11673]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[varautuminen](http://www.yso.fi/onto/yso/p22460)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko valmius ok ohjaustermi?

**Perustelut ehdotukselle**

https://sanastot.suomi.fi/terminology/02462623-9925-43d7-b117-2ee271cebdb7/concept/6d3358fe-16f1-434b-9e99-e1f6de14a5b7
https://rednet.punainenristi.fi/node/5959
https://mmm.fi/valmiusasiat
...Katso google varautuminen + valmius
Ruotsiksi muutettu föregripande > beredskap (fi. varautuminen + valmius)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Ei kyllä oikein luontevalta tunnu - varautuminen on kuitenkin selkeästi toimintaa, ja jotta varautuminen-sana olisi kuvailussa oikein, pitäisi aineistossa jotenkin käsitellä sitä toimintaa, eikä pelkästään esim. jonkun toimijan kykyä reagoida jossain tilanteessa 🤔

**Comment by mariaforsen** [comment]
Entä tarkenteellisena? Ehkä ruotsiksikin olisi hyvä lisätä > beredskap (verksamhet), tai sitten määritelmänä https://sanastot.suomi.fi/terminology/02462623-9925-43d7-b117-2ee271cebdb7/concept/6d3358fe-16f1-434b-9e99-e1f6de14a5b7

**Comment by ilona-x** [comment]
YSO:ssa erikseen:
[kriisivalmius](https://finto.fi/yso/fi/page/p728)
[muutosvalmius](https://finto.fi/yso/fi/page/p25177)
[puolustusvalmius](https://finto.fi/yso/fi/page/p19325)
[toimintavalmius (organisaatiot)](https://finto.fi/yso/fi/page/p39509)

**Comment by mirmaid** [comment]
^^ Pitäisi varmaan olla ennemmin _valmistautuminen (varautuminen)_. Jos tuntuu luontevalta, en nyt itse enää osaa sanoa...

**Comment by YSO-kokous** [comment]
**Päätös**

Tarkistetaan termien käyttöä. Yksi mahdollinen ohjaustermi on _valmiustoiminta_.

**Comment by AuHo22** [comment]
YSOssa on myös termi valmiussuunnittelu, jolla nimenomaan lienee tarkoitetaan mm. organisaatioiden jne. varautumista kriiseihin; varautuminen taas on yleistermi, jolla voidaan tarkoittaa vaikkapa yksilön lakiasioitten hoitoa tulevaisuutta varten (voi tietenkin olla myös valmistautumista) kuten esim.
https://lexly.fi/elamantilanteesi/tulevaisuuteen-varautuminen
https://www.vanheneminen.fi/varautuminen-kuolemaan-muistilista-elaville
YSOssa myös termi valmiudet

**Comment by mirmaid** [comment]
Ruotsiksi ainakin ohjaustermiksi bereda sig? 

Suomeksi varautuminen = toimintaa. Valmius taas ei ole toimintaa, eikä se oikein sellaiseksi tarkenteellakaan muutu. Tuntuu, että tilanne muuttuisi vain ehkä sekavammaksi suhteessa valmiussuunnitteluun, valmistautumiseen ja toimintavalmiuteen. 

Ehkä pitäisi lähteä vielä purkamaan sitä kautta, että mikä ruotsin kielen ongelma pitää saada ratkaistua?

**Comment by mariaforsen** [comment]
Lisäsin HT bereda sig
Sv. huomautuksena on nyt myös "Avser verksamhet för att vara beredd på kommande utveckling, särskilt faror, kriser och dylikt."

Varsinaista ongelmaa ei (toivon mukaan) enää ole, mutta halusin varmistaa että nämä nyt ymmärretään ja käytetään samalla tavalla.

Huom. YSOssa ei enää ole valmiudet-termiä.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutoksia.
