### ISSUE TITLE
filovirukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11674]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

filovirukset

**Ehdotettu termi ruotsiksi**

filovirus

**Ehdotettu termi englanniksi**

filoviridae

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 2

**Ehdotettu yläkäsite YSOssa (LT)**

 [RNA-virukset](http://www.yso.fi/onto/yso/p39061)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 filoviruses

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D016563), [Wikipedia](https://fi.wikipedia.org/wiki/Filovirukset)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Interaction of filovirus proteins with RIG-I signaling pathways 
https://urn.fi/URN:ISBN:978-951-29-8900-3

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [filovirukset](http://finto.fi/yse/fi/page/Y511674)

**Comment by mariaforsen** [comment]
Sv. filovirus /ne HT filoviridae
https://mesh.kib.ki.se/term/D016563/filoviridae
