### ISSUE TITLE
floristiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11685]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[floristiikka](http://www.yso.fi/onto/yso/p22058)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Merkitys? YSAssa huomautus merkityksestä, vrt. Tieteen termipankki vs. wikipedia.

**Perustelut ehdotukselle**

Onko tarkennettava? Kaksi eri merkitystä.

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
YSA:n huomautus:
Floristiikka tutkii tietyllä alueella esiintyvää kasvistoa ja kasvilajiien levinneisyyttä

Tepa:
https://termipankki.fi/tepa/fi/haku/floristiikka

Wikipedia:
https://fi.wikipedia.org/wiki/Floristiikka

**Comment by mirmaid** [comment]
Melindassa vain 14 kertaa, mutta molemmissa merkityksissä. Toinen voisi olla _floristiikka (kasvitiede/kasvimaantiede)_, mutta voisikohan toinen olla ihan vaan _kukka-ala_?

**Comment by mariaforsen** [comment]
Sv. floristik kukka-kauppa-merkityksessä ei kovin yleinen (suorakäännös?)
https://taitaja2022.fi/sv/grenar/service/304-floristik/ 
https://www.su.se/sok-kurser-och-program/bl2035-1.536762

**Comment by fantsby-m** [comment]
Nähtävästi engl. _floristry_ on tuota kukka-alaa ja _floristics_ on floristiikkaa - ja molemmista on nähtävästi käytetty suomessa _floristiikka_-sanaa

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Otetaan sanastoon kaksi käsitettä: kukka-ala ja floristiikka (kasvitiede)
Lisätään myös ohjaustermi: floristiikka (kukka-ala) KÄYTÄ kukka-ala

Mahdollisesti lisätään myös ohjaustermi: kukkakauppa-ala KÄYTÄ kukka-ala

YSO-ylläpito pohtii, muodostetaanko kaksi kokonaan uutta käsitettä vai muodostetaanko käsite floristiikka (kasvitiede) tästä olemassaolevasta floristiikka-käsitteestä.

**Comment by mariaforsen** [comment]
Sv. blomsterbranschen HT blombranschen, blomsterhandelsbranschen
Jfr https://finto.fi/yso/fi/page/p1427?clang=sv
https://opintopolku.fi/konfo/sv/toteutus/1.2.246.562.17.00000000000000011782
https://www.studentum.fi/koulutukset/axxell/florist-for-foretagare-1799980
