### ISSUE TITLE
Matkustajasilta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11684]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Matkustajasilta

**Ehdotettu termi ruotsiksi**

Ombordstigningsbrygga

**Ehdotettu termi englanniksi**

Passenger boarding bridge

**Tarkoitusta täsmentävä selite**

Matkustajasilta on suljettu, liikuteltava silta, jota pitkin matkustajat pääsevät siirtymään terminaalista lentokoneeseen tai laivaan ilman, että heidän täytyy kulkea ulkona.

**Perustelut ehdotukselle**

Yleisesti käytössä sekä lentokentillä että satamissa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sillat](http://www.yso.fi/onto/yso/p14830)

**Ehdotetut temaattiset ryhmät**

 [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Matkustajasilta)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://hkm.finna.fi/Record/hkm.AE1904E8-170B-4266-A1AF-E1D945122621?sid=3034733938

**Ehdottajan organisaatio**

Helsingin kaupunginmuseo
**Termiehdotus Fintossa:** [Matkustajasilta](http://finto.fi/yse/fi/page/Y511684)

**Comment by mariaforsen** [comment]
Sv. passagerarbryggor HT ombordstigningsbryggor, landstigningsbryggor, landgångar

**Comment by mirmaid** [comment]
KT maihinnoususillat (ehkä tarkenteella)?

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/matkustajasilta

IATE1
fi        matkustajasilta (★★☆☆);
matkustajakäytävä (★★☆☆);
terminaalin siipi (★★☆☆);
terminaalin "sormiosa" (★★☆☆);
matkustajalaituri (★★☆☆)
sv       pir (★★★☆)
en      pier (★★★☆);
boarding gate pier (★★★☆);
finger (★★★☆);
passenger pier (★★★☆);
aircraft pier (★★★☆)

Luokitus: air transport
	  
Lähde: IATE 01.08.2023, Euroopan unioni (1357832)
	  
IATE2
fi        matkustajasilta (★★★★)
sv       passagerarbrygga (★★☆☆)
en      aerobridge (★★★☆);
passenger loading bridge (★★★☆);
jetway (★★★☆);
airbridge (★★★☆);
air bridge (★★★☆);
jetty (★★★☆);
passenger boarding bridge (★★★☆);
jet bridge (★★★☆)

Luokitus: air transport
technology and technical regulations
	  
Lähde: IATE 01.08.2023, Euroopan unioni (862703)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
