### ISSUE TITLE
sosiaalivirastot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11689]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sosiaalivirastot](http://www.yso.fi/onto/yso/p21613)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sosiaalivirastot/sosiaalitoimistot/sosiaaliasemat - YSAn huomautuksen mukaan mahdollisesti yhdistettävissä?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
TEPAssa on:
https://termipankki.fi/tepa/fi/haku/sosiaalivirasto
https://termipankki.fi/tepa/fi/haku/sosiaalitoimisto
Ei sosiaaliasemaa

Kielitoimiston sk.:
https://www.kielitoimistonsanakirja.fi/#/sosiaalitoimisto?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/sosiaalivirasto?searchMode=all
Ei sosiaaliasemaa

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4fefa45df42217a9b664bae6dc057785&list_id=1&keyword=sosiaalitoimisto&word=sosiaalitoimisto
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_c7d91ef865b2e2d6a92a636c74f20e4a&list_id=1&keyword=sosiaalivirasto&word=sosiaalivirasto

 ..eli vaikuttaa siltä että virasto voisi olla vähän "korkeammalla" organisaatiossa / laajempana kokonaisuutena, ks. https://termipankki.fi/tepa/fi/haku/virasto ja esim. https://finto.fi/finaf/sv/page/000034924?clang=fi  ..mutta miten sosiaaliasema eroaa sosiaalitoimistosta? Molemmista kai voi saada "käytännön" apua ja palveluja? Taitaa sosiaaliasema olla lähinnä nimitys, kun ei myöskään löydy sanakirjoista, TEPAsta tms.

**Comment by mirmaid** [comment]
YSAssa näillä kaikilla on siis ollut huomautus: _Sosiaalitoimistojen, -asemien ja -virastojen tehtävät ovat pääasiassa samat, organisaation nimi riippuu kunnan tavasta nimetä eri toimipisteensä_

**Comment by lamminen** [comment]
Miten (sosiaali-)viranomainen (sosiaali-)palveluitaan tarjoaa, verkossa vai toimistossa? Verkossa, puhelimessa (sosiaali-)neuvontaa, tai paikan päällä (sosiaali-)asemalla tai (sosiaali-)virastossa. Termi ”sosiaalitoimisto” kattaisi sekä virastot että asemat, vaikuttaisi siltä. Sosiaalitoimi organisoi sosiaalihuollon palveluita asiakkaille, sosiaalialantyöntekijät sosiaalitoimistoissa sosiaaliturvaa heille tarjoavat.
Kirjassa Armeliaisuus, yhteisöapu ja sosiaaliturva kirjoitettiin 1994 näin: Sosiaalityöntekijöiden kokonaismäärästä on edelleenkin vaikea saada tietoa, koska ryöntekijät hajaantuvat eri nimikkein monille hallinnon ja tiIastoinnin aloille. Arvion perusteella heitä oli vuonna 1987 noin 3590.

http://urn.fi/URN:ISBN:978-951-39-6973-8

Näin jo kauan ennen sote-uudistusta.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Säilytetään sanastossa sosiaalitoimistot. Tälle ohjaustermeiksi sosiaalivirastot ja sosiaaliasemat. Poistetaan sanastosta käsitteet sosiaalivirastot ja sosiaaliasemat.
