### ISSUE TITLE
Särkijärvi (Puolanka)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11682]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Särkijärvi (Puolanka)](http://www.yso.fi/onto/yso/p212267)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Myös kylä ja aineistoa Melindassa.

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kylää ei löydy lähteistä > 653. Järvi tarkennettava, Puolangalla kaksi saman nimistä.

**Comment by mirmaid** [comment]
Aineiston mukaan Lylykylässä, mutta niin on toinenkin Puolangan Särkijärvi. Aineistosta kuitenkin kartan perusteella järvi on identifioitavissa, lähin kylä paikkatietoalustalla on Tuijolanvaara. Toinen Särkijärvi on lähinnä Lylykylää (ilmeisesti isompi kylä).

**Comment by mirmaid** [comment]
Aineistossa käsitelty Särkijärvi: http://paikkatiedot.fi/so/1000772/10453091

Puolangan Lylykylän toinen Särkijärvi: http://paikkatiedot.fi/so/1000772/10453045

**Comment by mirmaid** [comment]
Särkijärvi (Puolanka, Tuijolanvaara)
