### ISSUE TITLE
lehdistötilaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11683]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lehdistötilaisuus

**Ehdotettu termi ruotsiksi**

presskonferens

**Ehdotettu termi englanniksi**

press conference

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sitä tarvitaan asiasanoituksessa ja kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [tiedotus](http://www.yso.fi/onto/yso/p35), [tapahtumat](http://www.yso.fi/onto/yso/p2108), [journalismi](http://www.yso.fi/onto/yso/p1161)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556), [80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547)

**Vaihtoehtoiset termit**

 pohjoissaameksi: preassakonferánsa

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valokuvien kuvailussa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lehdistötilaisuus](http://finto.fi/yse/fi/page/Y511683)

**Comment by mariaforsen** [comment]
Varmaankin lehdistötilaisuudet = presskonferenser.

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

LCSH: http://id.loc.gov/authorities/subjects/sh85106517

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
