### ISSUE TITLE
nudismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11699]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nudismi](http://www.yso.fi/onto/yso/p11824)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "alastomuuskulttuuri" ja "naturismi"

**Perustelut ehdotukselle**

"Alastomuuskulttuuri, nudismi, naturismi, Saksassa syntynyt liike, joka katsoo alastomuuden edistävän ihmisten luonnollista ja estotonta kanssakäymistä ja terveitä elämäntapoja. A:n harrastajilla on eräissä maissa eristettyjä alueita, nudistileirejä, joissa sukupuoleen ja ikään katsomatta harrastetaan luonnossa oleilua vaatteitta." (Uusi tietosanakirja)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. nakenkultur
https://svenska.se/saol/?id=2011672&pz=5

**Comment by mirmaid** [comment]
_Alastomuuskulttuuri_ näyttää käytettävän myös tyyliin "suomalainen sauna- ja alastomuuskulttuuri" - siis viittaamaan siihen missä yhteyksissä yhteiskunnassa ollaan alasti ja miten siihen suhtaudutaan. Esim. https://yle.fi/a/3-6882018

_Naturismi_ oli joskus aiemminkin ehdolla ja silloin taidettiin epäröidä, onko kuitenkin eri tavalla määritelty kuin nudismi, koska ei hyväksytty. Mutta ehkä sen voisi ottaa, ei niillä mielestäni ainakaan selkeää eroa ole.

**Comment by jtuohini** [comment]
Jos epäilyttää, voisivatko viittausmuodot olla _alastomuuskulttuuri (nudismi)_ KÄ **nudismi** ja _naturismi (nudismi)_ KÄ **nudismi**? Silloin saataisiin peräti tietosanakirjan tunnistamat käsitteet mukaan hakuihin ilman väärinymmärtämisen vaaraa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermit ehdotetuilla tarkenteilla.
