### ISSUE TITLE
neoadjuvanttihoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11692]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neoadjuvanttihoito

**Ehdotettu termi ruotsiksi**

neoadjuvant behandling

**Ehdotettu termi englanniksi**

neoadjuvant therapy 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [hoito](http://www.yso.fi/onto/yso/p824)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [ MeSH / FinMeSH](http://www.yso.fi/onto/mesh/D020360), [Wikipedia](https://en.wikipedia.org/wiki/Neoadjuvant_therapy)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://hdl.handle.net/10138/349894

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [neoadjuvanttihoito](http://finto.fi/yse/fi/page/Y511692)

**Comment by mariaforsen** [comment]
Sv. neoadjuvant behandling HT neoadjuvant terapi, neoadjuvantbehandling
https://www.alltomcancer.fi/information-om-cancer/cancerterminologi/#n
https://mesh.kib.ki.se/term/D020360/neoadjuvant-therapy
