### ISSUE TITLE
taistelustressi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11701]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taistelustressi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

combat stress

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Combat stress, also known as battle fatigue, is a common response to the mental and emotional strain that can result from dangerous and traumatic experiences. It is a natural reaction to the wear and tear of the body and mind after extended and demanding operations.

Combat stress usually happens for brief periods and is considered a natural reaction to the traumatic events that service members experience. Symptoms often disappear after a service member is home for a few months or even weeks. https://www.militaryonesource.mil/military-basics/wounded-ill-injured-and-caregivers/understanding-and-dealing-with-combat-stress-and-ptsd/

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.168874

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by mariaforsen** [comment]
Entä taisteluväsymys? MOTissa battle fatigue on taisteluväsymys. Ovatko nämä saman asian eri puolia vai onko syytä pitää erillään? Tämä on avainkysymys kun käännetään.

Sv.  stridsutmattning (stress) HT stridströtthet (stress), stridsstress 
https://sv.wikipedia.org/wiki/Stridsutmattning
https://en.wikipedia.org/wiki/Combat_stress_reaction
https://psykmuseet.se/2013/03/krigsneuros-stridsutmattning-posttraumatisk-stress/
https://www.psykologiguiden.se/psykologilexikon/?Lookup=stridsutmattning%2C+stridstr%C3%B6tthet
https://lakartidningen.se/tema-livsstil-och-psykisk-ohalsa-1/2011/09/psykiskt-sjuk-av-stress-diagnostik-patofysiologi-och-rehabilitering/

WP: "Combat stress reaction (CSR) is acute behavioral disorganization as a direct result of the trauma of war. Also known as "combat fatigue", "battle fatigue", or "battle neurosis", it has some overlap with the diagnosis of acute stress reaction used in civilian psychiatry."

**Comment by mirmaid** [comment]
Sanastossa on _stressi, väsymys, uupumus_. Erikseen _teknostressi_ ja _vähemmistöstressi_. 19 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Onko taisteluväsymys OT? Mietin ruotsinnoksen kannalta.. 
https://www.psykologiguiden.se/psykologilexikon/?Lookup=stridsutmattning%2C+stridstr%C3%B6tthet
