### ISSUE TITLE
lentotiedustelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11700]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lentotiedustelu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

aerial examination of enemy territory to obtain military information concerning installations, movements, resources, strength, etc.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tiedustelu](http://www.yso.fi/onto/yso/p13152)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SOTO](https://finto.fi/soto/fi/page/p1135), [LCSH](https://id.loc.gov/authorities/subjects/sh85001281.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.169090

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by mariaforsen** [comment]
Sv. flygspaning 
https://id.kb.se/term/sao/Flygspaning

**Comment by mirmaid** [comment]
N. 30 kertaa Melindassa.

LCSH myös http://id.loc.gov/authorities/subjects/sh85001374. Onko kattavuus siis vain tuo suppeampi _aerial reconnaissance_?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Tutkitaan suhdetta ilmatiedusteluun ainakin ohjaustermin tasolla. Tarkistetaan LCSH-linkki.
