### ISSUE TITLE
Sallan kansallispuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11704]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Sallan kansallispuisto

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Salla national park

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Sallan_kansallispuisto

**Ehdotettu yläkäsite YSOssa (LT)**

 [kansallispuistot](http://www.yso.fi/onto/yso/p75)

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560), [62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://julkaisut.metsa.fi/fi/julkaisut/show/2831

**Ehdottajan organisaatio**

KK/HR

**Comment by mariaforsen** [comment]
Sv. Salla nationalpark
