### ISSUE TITLE
Ei-valtiolliset toimijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11705]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Ei-valtiolliset toimijat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Non-state actors

**Tarkoitusta täsmentävä selite**

"Non-state actors come in many forms. They
range from individuals to private corporations,
religious institutions, humanitarian organiza-
tions, armed groups and de facto regimes in
actual control of territory and population."

**Perustelut ehdotukselle**

Vaikea ottaa haltuun muilla termeillä ainakin esimerkkiaineistossa, vaikuttaa vakiintuneelta tutkimusalan käsitteeltä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://authorities.loc.gov/cgi-bin/Pwebrecon.cgi?GetAuthRecs=1&SEQ=20230726060733&PID=_7O5bbX4fFQvtJAQa5Nowd2VeK6u)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Hybrid threats from non-state actors: A taxonomy
https://www.hybridcoe.fi/publications/hybrid-coe-research-report-6-hybrid-threats-from-non-state-actors-a-taxonomy/

**Ehdottajan organisaatio**

Kansalliskirjasto (Anna Tuominen)

**Comment by ilona-x** [comment]
LCSH: 
Non-state actors (International relations) http://id.loc.gov/authorities/subjects/sh2007010917

**Comment by ilona-x** [comment]
ehdotettu myös muodossa **valtiosta riippumaton toimija**  https://github.com/Finto-ehdotus/YSE/issues/11642

**Comment by mariaforsen** [comment]
Sv. icke-statliga aktörer
https://termipankki.fi/tepa/fi/haku/icke-statlig%20akt%C3%B6r
https://id.kb.se/find?q=icke-statliga%20akt%C3%B6rer

**Comment by mirmaid** [comment]
Melindassa 3 kertaa _ei-valtiolliset toimijat_, kerran _ei-valtiolliset terroristiset toimijat_.

**Comment by ilona-x** [comment]
Tepa: https://termipankki.fi/tepa/fi/haku/%20valtiosta%20riippumaton%20toimija

**fi        valtiosta riippumaton toimija (suositeltava);**
valtiosta riippumaton taho

**sv       icke-statlig aktör**

**en      non-State actor;**
non-governmental actor;
NSA

	  
Lähde: IATE 01.08.2023, Euroopan unioni (920502)

**Comment by mirmaid** [comment]
^ Ei-valtiollinen kuulostaa minusta selkeämmältä. Valtiosta riippumaton kuulostaa siltä kuin ko. toimija olisi jotenkin vapaa valtion vaikutuksesta.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _valtiosta riippumattomat toimijat_, ohjaustermiksi _ei-valtiolliset toimijat_.
