### ISSUE TITLE
yksinolo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11712]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yksinolo

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

solitude

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Yksinolo erotuksena yksinäisyydestä, joka on negatiivinen tunne. Yksinolo on neutraali ilmaus, sen voi kokea joko positiivisena tai negatiivisena tilanteesta riippuen. Minulla on kuvailussa kirja Yksin, kiitos, joka käsittelee nimenomaan yksinolemisen positiivisia puolia, mutta sanastossa ei ole mitään käsitettä ilmaisemaan juuri tätä teoksen keskeisintä asiaa. Asiasanoituksesta tulee aivan hassu ja vinksahtanut, kun edes tätä neutraalia yksinolon perustilaa ei voi ilmaista (puhumattakaan sitten hyvästä yksinolosta). Kyse ei välttämättä ole yksineläjistä tai erakoista tai introversiosta, vaan ihan vain tavallisesta yksinolemisesta, jota kaikki ihmiset tarvitsevat ja kaipaavat enemmän tai vähemmän.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 yksinoleminen

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [yksinäisyys](http://www.yso.fi/onto/yso/p6935)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Solitude), [LCSH](https://id.loc.gov/authorities/subjects/sh85124673.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Marika Riikonen: Yksin, kiitos. 978-952-406-015-8

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mariaforsen** [comment]
Sv. ensamvarande HTvara ensam, positiv ensamhet, frivillig ensamhet
ofrivillig ensamhet ANV ensamhet

**Comment by mirmaid** [comment]
On KAUNOssa. Toisaalta kyllä epäilen, että yksinolo-termi helposti lisättäisiin myös kaikkiin yksinäisyyttä käsitteleviin aineistoihin...mahdollista toki lisätä jotain yksinolo (yksinäisyys) KÄ yksinäisyys.

8 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, huomioidaan ehdotetut ohjaustermit.
