### ISSUE TITLE
matalan intensiteetin konflikti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11711]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

matalan intensiteetin konflikti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

 low-intensity conflict 

**Tarkoitusta täsmentävä selite**

https://en.wikipedia.org/wiki/Low-intensity_conflict
A low-intensity conflict (LIC) is a military conflict, usually localised, between two or more state or non-state groups which is below the intensity of conventional war. It involves the state's use of military forces applied selectively and with restraint to enforce compliance with its policies or objectives. 

**Perustelut ehdotukselle**

On eri asia kuin YSOsta löytyvä jäätyneet konfliktit (aktiivisemmin käynnissä oleva sota?). Tai ohjaustermin kautta mukaan? 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 matalan intensiteetin sodat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The relevance of Clausewitzian theory in hybrid war :the Iranian-Saudi rivalry
https://www.hybridcoe.fi/publications/hybrid-coe-working-paper-15-the-relevance-of-clausewitzian-theory-in-hybrid-war-the-iranian-saudi-rivalry/

**Ehdottajan organisaatio**

Kansalliskirjasto (Anna Tuominen)

**Comment by ilona-x** [comment]
LCSH:
Low-intensity conflicts (Military science) http://id.loc.gov/authorities/subjects/sh86000256

**Comment by mariaforsen** [comment]
Sv. lågintensitetskonflikter HT konflikter med låg intensitet, lågintensiva konflikter
https://www.rikstermbanken.se/search?q=l%C3%A5gintensitetskonflikt&s=termer
[urn:nbn:se:fhs:diva-1579](https://urn.kb.se/resolve?urn=urn%3Anbn%3Ase%3Afhs%3Adiva-1579)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
