### ISSUE TITLE
etelänapa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11748]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[etelänapa](http://www.yso.fi/onto/yso/p12433)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pohjoissaameksi lullináhpi (lähinnä Suomen puolella), lullipola (koulukirjoissa Norjan ja Ruotsin puolella) ja lullipovla (harvinanen, mutta olemassa). 

**Perustelut ehdotukselle**

Samoista syistä kuin pohjoisnavan muutosten ehdotukselle. Löytyy myös Lapponicasta nimellä lullipola: https://finto.fi/lapponica/fi/page/L99?clang=se. Lullipola löytyy koulukirjoista kuten Min eana 1 -kirjasta ja sen opettajan oppaasta: "Árktalaš-, buolaš-, dahje galbma dálkkádatguovllut lea davvipolas ja lullipolas." (s. 28 https://calliidlagadus.org/do2/assets/min-eana-1---oahpaheaddjibagadus.pdf)

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by kmakarai** [comment]
Pahoittelut, piti ehdottaa tätä muutosta käsitteeseen p12433 eli etelänavalle, eikä p11748 eli napa-alueille.

**Comment by nikopartanen** [comment]
Hyväksytään ehdotettu pohjoissaamen päätermi ja ohjaustermit.
