### ISSUE TITLE
ajokorttilaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11749]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ajokorttilaki

**Ehdotettu termi ruotsiksi**

körkortslag

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.finlex.fi/fi/laki/ajantasa/2011/20110386

**Ehdotettu yläkäsite YSOssa (LT)**

 [lait](http://www.yso.fi/onto/yso/p1464)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559), [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.traficom.fi/sites/default/files/media/file/Raportti_ajokorttilaki_taloudelliset_vaikutukset.pdf

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [ajokorttilaki](http://finto.fi/yse/fi/page/Y511749)

**Comment by jtuohini** [comment]
Tästä tehty nyt Asterin kautta käytettävissä oleva teostietue Tekaan: (FI-ASTERI-W)000015215. Teosviite korjattu yhteen Melinda-tietueeseen ja lisätty kuuteen, joista se vaikutti puuttuvan.

**Comment by mirmaid** [comment]
^ Olisi hyvä, jos Teka-projektissa otettaisiin käsittelyyn myös lakien kaltaisten aineistojen kieliversioiden (ekspressioiden?) käsittely, koska lakien poistaminen YSOsta ei ole ihan yksinkertaista jos tämä aspekti sivuutetaan - ja on myös vähän hankalaa tässä tilanteessa tehdä päätöstä, että uusia lakeja ei enää otettaisi YSOon. Kun Tekan ylläpitovastuu uusien teostietueiden ja kieliversioiden osalta on selvillä, päästään varmasti eteenpäin asiassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Tämänhetkisen välivaiheen käytännöistä sovitaan erikseen SISKU-ryhmässä. YSOssa on kaksi terminmuodostuskieltä, suomi ja ruotsi.

**Comment by mirmaid** [comment]
@mirja.anttila@helsinki.fi
