### ISSUE TITLE
teoreettinen kielitiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11742]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

teoreettinen kielitiede

**Ehdotettu termi ruotsiksi**

teoretisk språkvetenskap

**Ehdotettu termi englanniksi**

theoretical linguistics

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

On ollut KOKOssa, jostain syystä ei YSOssa. Pohjoissaameksi: teorehtalaš gielladieđa. En ole onnistunut löytämään sitä teorehtalaš lingvistihkka -versiona, mutta sekin on teoreettisesti mahdollista.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kielitiede](http://www.yso.fi/onto/yso/p1631)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [soveltava kielitiede](http://www.yso.fi/onto/yso/p14827)

**Vastaava käsite muussa sanastossa**

 [WD](https://www.wikidata.org/wiki/Q351625), [KOKO](https://finto.fi/koko/fi/page/p57681), [Tieteen termipankki](https://tieteentermipankki.fi/wiki/Kielitiede:teoreettinen_kielitiede)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mm. kirjastotyössä

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. teoretisk språkvetenskap HT teoretisk lingvistik 
https://svenska.se/tre/?sok=lingvistik&pz=8
https://www.masterstudies.se/institutions/uit-the-arctic-university-of-norway/master-i-teoretisk-lingvistik

**Comment by mirmaid** [comment]
3 kertaa Melindassa KTA-terminä.

YSOssa on vain _teoreettinen filosofia_ ja _teoreettinen fysiikka_.

**Comment by tpalonen** [comment]
RT soveltava kielitiede? Vrt. http://www.yso.fi/onto/kto/p888

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
