### ISSUE TITLE
lypsylehmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11743]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lypsylehmä

**Ehdotettu termi ruotsiksi**

mjölkko

**Ehdotettu termi englanniksi**

dairy cow

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Jos on emolehmä, tämä on täysin looginen ja alalla merkittävä käsite

**Ehdotettu yläkäsite YSOssa (LT)**

 [lehmät](http://www.yso.fi/onto/yso/p10991)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [emolehmät](http://www.yso.fi/onto/yso/p16474)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

alan opinnäytetyöt

**Ehdottajan organisaatio**

Seinäjoen ammattikorkeakoulu

**Comment by mariaforsen** [comment]
Sv. mjölkkor HT mjölkkossor
https://termipankki.fi/tepa/fi/haku/lypsylehm%C3%A4

**Comment by mirmaid** [comment]
Tässä on varmaan se ongelma, että _lehmät_-käsitteellä yleensä viitataan juuri lypsylehmiin (vrt. maito/lehmänmaito), ja _emolehmät_ on otettu sitten erotukseksi näistä ns. tavallisista lehmistä. Jos meillä on YSOssa sekä _lehmät_, että _lypsylehmät_, millaista käyttöeroa näille kahdelle tavoitellaan?

_Lehmät_ käytetty melkein 3000 kertaa Melindassa. Sanastossa on lisäksi _lypsykarja_, lehmät ja lypsykarja samoissa viitteissä 1161 kertaa.

**Comment by YSO-kokous** [comment]
**Päätös**

_Lypsylehmät_ käytä _lypsykarja_, käytä _lehmät_.
