### ISSUE TITLE
pohjoisnapa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11747]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pohjoisnapa](http://www.yso.fi/onto/yso/p15051)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pohjoissaamenkielisiksi ohjaustermeiksi davvipola ja davvipovla (harvinainen, mutta löytyy silti Korpista). Vrt. napa-alueet pohjoissaameksi eli polaguovllut.

**Perustelut ehdotukselle**

Davvipola on yleisin vastine muualla kuin Suomessa, jossa davvináhpi on yleisempi. Käytössä myös koulukirjoissa, kuten Min eana 1. Esim. sen opettajankirjassa näkyy davvipola: "Árktalaš-, buolaš-, dahje galbma dálkkádatguovllut lea davvipolas ja lullipolas." (s. 28 https://calliidlagadus.org/do2/assets/min-eana-1---oahpaheaddjibagadus.pdf)

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by jtuohini** [comment]
Pohjoisnapa-asiasana pitäisi siirtää YSO:sta YSO-paikkoihin, sillä kyseessä on paikka, jolla on määritellyt koordinaatit. Vai onko kyse siitä, että on erikseen magneettinen pohjoisnapa? (Ja kumpaan näistä halutaan YSO:ssa viitata?)

**Comment by nikopartanen** [comment]
Hyväksytään ehdotetut pohjoissaamen ohjaustermit.
