### ISSUE TITLE
intiaanikielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11741]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[intiaanikielet](http://www.yso.fi/onto/yso/p6009)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käsitteen intiaanikielet alakäsitteet olisi hyvä jakaa omiin kieliperheisiinsä.

**Perustelut ehdotukselle**

Intiaanikielet ei ole kielitieteessä nykyään käytetty käsite, eikä ole syytä jaotella Pohjois- ja Etelä-Amerikan kieliä omaan ryhmäänsä muista kielistä poikkeavalla tavalla. Kielten uudelleenjärjestelylle kieliperheiden mukaisesti on jo olemassa selvä malli muista YSOn kielistä. Näihin lukeutuu jo kieliperheitä, joista on YSOssa vain yksi kieli. Alla yksi mahdollinen järjestelytapa.

Käsite -> uusi yläkäsite
abenakin kieli -> algonkin-kielet
aimaran kieli -> aimarakielet
irokeesikielet -> kieli ja kielet
ketšuan kieli -> ketšualaiset kielet
k'iche'n kieli -> mayakielet
mayakielet -> kieli ja kielet
nahuatlin kieli -> uto-asteekkilaiset kielet
wari'n kieli -> chapacura-kielet (?)

**Ehdottajan organisaatio**

KK / Niko

**Comment by tpalonen** [comment]
Hyvä ehdotus! Käsitteen voisi mielestäni poistaa. 

(Kiinnostavasti muuten varovaista hyväksyntää tiedeyhteisössä on saanut teoria kielikunnasta, jota nimitetään Dene-jeniseiläiskieliksi. Teorian mukaan Siperiassa puhuttavat jeniseikielet ja Pohjois-Amerikassa puhuttavat na-dené-kielet (mm. navajo) ovat sukua keskenään. https://en.wikipedia.org/wiki/Den%C3%A9%E2%80%93Yeniseian_languages )

**Comment by nikopartanen** [comment]
Poistaa tai ehkä muuttaa, tosin "Pohjois- ja Etelä-Amerikan alkuperäiskansojen kielet" on aika pitkä ja ehkä ontologisestikin ongelmallinen. Melindassa on käsitteellä "intiaanikielet" kuvattu [423 tietuetta](https://melinda.kansalliskirjasto.fi/F/JPULF471RDPTILBNJA93B9QRN33193HQB4CLMI25Q6CQNAV4UB-00186?func=short-0&set_number=031590). Meillä ei ole muita alueeseen rajautuvia käsitteitä kieli ja kielet -käsitteen alla, mutta varmaan siitä voi keskustella mitä tuon kanssa tekisi. 

(Tämä onkin hyvä kysymys, millä tahdilla pitää seurata uusien teorioiden kehitystä ja vakiintumista, toki tällaiset kuten japanilaiset kielet ja korealaiset kielet edustavat myös juuri melko tuoretta ajattelua eri kielten ryhmittelyistä. Myös esimerkiksi uralilaisten kielten hierarkia on nykyisellään hieman vanhentunut (volgalaisista kielistä ei paljoa puhuta nykyään), mutta ehkä tutkimusyhteisö voi siitä vielä kiistellä jonkin vuosikymmenen konsensusta etsien, ja muutetaan sitten.)

**Comment by mirmaid** [comment]
Mitä pikaisesti katsoin, niin voi olla aika hankalaa lähteä korvaamaan intiaanikielet-käsitettä kuvailussa tapaus kerrallaan uudemmalla kieliryhmällä/-ryhmillä, kun näitä on käsitelty ja tutkittu kuitenkin sillä ajatuksella, että muodostavat oman kokonaisuutensa kielten joukossa. Viitteistä ei välttämättä käy mitenkään ilmi, mitä kieliä aineisto käsittelee - tai se käsittelee alkuperäiskansojen kielten tutkimusta yleisesti. Toki sitten on mahdollista vain muuttaa > kieli ja kielet + intiaanit (mitä epäilemättä käsittelemme myös pian).

**Comment by tpalonen** [comment]
Ehkä alkuperäiskielet voisi olla myös hyvä korvaaja?

**Comment by mirmaid** [comment]
Entä _Amerikan alkuperäiskielet_? https://fi.wikipedia.org/wiki/Amerikan_alkuper%C3%A4iskielet

**Comment by mariaforsen** [comment]
Sv. amerikanska ursprungsspråk toimisi vastaavalla tavalla Löytyy toki myös tarkempi jaottelu (ja alakäsitteitä): 
https://sv.wikipedia.org/wiki/Kategori:Nordamerikanska_ursprungsspr%C3%A5k
https://sv.wikipedia.org/wiki/Kategori:Sydamerikanska_ursprungsspr%C3%A5k

Suppeampia termejä voisi kyllä myös hyväksyä:
sv. algonkinspråk
https://id.kb.se/term/sao/Algonkinspr%C3%A5k
sv. aymara (språkfamilj) 
https://sv.wikipedia.org/wiki/Aymara_(spr%C3%A5k)
sv. quechua (språkfamilj)
https://sv.wikipedia.org/wiki/Quechua
sv. mayanska språk
https://sv.wikipedia.org/wiki/Mayaspr%C3%A5k
sv. uto-aztekiska språk
https://sv.wikipedia.org/wiki/Uto-aztekiska_spr%C3%A5k
sv. chapacura (språk)

**Comment by mirmaid** [comment]
^ Mayakielet onkin jo.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Muutetaan käytettäväksi termiksi Amerikan alkuperäiskielet
Ohjaustermeiksi Etelä-Amerikan alkuperäiskielet, Väli-Amerikan alkuperäiskielet, Pohjois-Amerikan alkuperäiskielet ja intiaanikielet.

Pohditaan vielä, liitetäänkö intiaanikielet-termille kulttuurisensitiivisyys-huomautusteksti.

Pohdittiin myös, pitäisikö lisätä käyttöhuomautus, koska "Amerikka" suomen kielessä assosioituu vahvasti pelkästään Pohjois-Amerikkaan. Arveltiin, että ohjaustermit kuitenkin tässä riittävät.

**Comment by mariaforsen** [comment]
Sv. amerikanska ursprungsspråk
