### ISSUE TITLE
Lasikangas (Raahe)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11759]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lasikangas (Raahe)](http://www.yso.fi/onto/yso/p191279)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö Lasikangas (Raahe) ja Ylipää (Pattijoki) yhdistää?

**Perustelut ehdotukselle**

YSO-paikkojen huomautus: 
Pattijoki liitetty 1.1.2003 Raaheen. Raahen Lasikangas tunnetaan paremmin Pattijoen Ylipään nimellä

Raahe – Lasikangas linkattu nyt metsäalueeseen (Lasikangas -nimellä löytyy Paikkatietoalustalta vain tämä metsäalue) 

https://fi.wikipedia.org/wiki/Lasikangas

Raahessa on kaksi Ylipää-nimistä kylää, joista tässä kysessä siis entisen Pattijoen kunnan alueella sijaitseva kylä

https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=tietue&id=20798

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Lasikangas (Raahe), KT Ylipää (Raahe, Pattijoki), Ylipää (Pattijoki)
