### ISSUE TITLE
anortosiitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11751]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

anortosiitit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/69ac12c9-068a-4562-a38a-aaef345efc2f

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [anortosiitit](http://finto.fi/yse/fi/page/Y511751)

**Comment by mariaforsen** [comment]
Sv. anortosit
https://termipankki.fi/tepa/fi/haku/anortosit
https://sv.wikipedia.org/wiki/Anortosit

**Comment by fantsby-m** [comment]
Yksikkö vai monikko?

**Comment by mirmaid** [comment]
Ehkä yksikkö...väitöskirjassa monikossa, kivilajit YSOssa vähän vaihtelevasti.

**Comment by ilona-x** [comment]
GEOssa yksikössä:
**anortosiitti** http://www.yso.fi/onto/gtk/GTK2015ID210

**Comment by mirmaid** [comment]
Voidaan pohtia kivilajien yksikkö/monikkomuotoja sisäisessä yso-kokouksessa, tarvitaan ehkä jotain yhdenmukaistamista.
