### ISSUE TITLE
ekoenergia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11758]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ekoenergia](http://www.yso.fi/onto/yso/p1214)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi tai päätermiksi kestävä energia. Samoin englanniksi sustainable energy ja ruotsiksi hållbar energi. Englanniksi pitää ainakin vaihtaa päätermiksi. Ks. perustelut.
+ RT uusiutuvat energialähteet?

**Perustelut ehdotukselle**

Käsite on otettu sanastoon vuonna 2001. Tuohon aikaan eko-etuliite oli muodissa, mutta sanasto aiheen ympärillä on elänyt eikä ekoenergia-termi tunnu nykyisin enää olevan juurikaan käytössä. Esimerkiksi IATEsta ei löydy lainkaan termejä ekoenergia, ecoenergy tai ekoenergi. Wikipediassa on artikkeli otsikolla Sustainable energy ja esim. green energy ohjaa siihen. Ks. myös:
https://european-union.europa.eu/priorities-and-actions/actions-topic/energy_fi
https://european-union.europa.eu/priorities-and-actions/actions-topic/energy_sv
https://european-union.europa.eu/priorities-and-actions/actions-topic/energy_en

Englanninkielisessä Wikipediassa on myös Ecoenergy-artikkeli, joka käsittelee Kanadan hallituksen tämän nimistä energiahanketta. Eli englannin nykyinen termi on ainakin harhaanjohtava.
https://en.wikipedia.org/wiki/Ecoenergy

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
https://en.wikipedia.org/wiki/Sustainable_energy

**Comment by mariaforsen** [comment]
hållbar energi HT grön energi 
https://termipankki.fi/tepa/fi/haku/h%C3%A5llbar%20energi
https://www.globalamalen.se/om-globala-malen/mal-7-hallbar-energi-alla/

Myös suomeksi on Ekoenergia enerigamerkki: https://fi.wikipedia.org/wiki/Ekoenergia

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään päätermiksi _kestävä energia_.
