### ISSUE TITLE
hulevesialtaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11754]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hulevesialtaat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Hulevesiallas on hulevesien varastoimiseen tai viivyttämiseen käytetty tai rakennettu allas. https://www.vesi.fi/sanasto/hulevesiallas/

**Ehdotettu yläkäsite YSOssa (LT)**

 [altaat](http://www.yso.fi/onto/yso/p4465)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

KasviHAVA-hanke Haitta-aineiden pidättyminen hulevesialtaissa https://www.vhvsy.fi/sivut/Julkaisut

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [hulevesialtaat](http://finto.fi/yse/fi/page/Y511754)

**Comment by mariaforsen** [comment]
Sv. dagvattenbassänger HT dagvattenmagasin, bassänger för dagvattenblandat spillvatten
https://termipankki.fi/tepa/fi/haku/hulevesiallas
https://www.vesi.fi/sv/sanasto/dagvattenbassang/
https://www.sanakirja.fi/custom/en-sv-fi/hulevesiallas

**Comment by mirmaid** [comment]
Alustavasti pohdin, tarvitaanko kuitenkin jotain kattavampaa (hulevesijärjestelmät tms.)...

**Comment by mariaforsen** [comment]
Sv. dagvattensystem
https://www.vesi.fi/sv/sanasto/dagvattensystem/
https://termipankki.fi/tepa/fi/haku/hulevesi

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _hulevesijärjestelmät_.

**Comment by mirmaid** [comment]
Sanastossa on jo _sadevesijärjestelmät_. Ovatko sama asia? Eri termejä käytetään vähän eri yhteyksissä, mutta ei kuitenkaan selkeää rajaa.

**Comment by mariaforsen** [comment]
Hulevesi ja sadevesi-termeillä taitaa olla eri merkityskenttiä (eri käyttöyhteyksien lisäksi), ja tällä kertaa onneksi samalla tavalla myös ruotsiksi.

"Hulevedellä tarkoitetaan maan pinnalta, rakennusten katoilta ja muilta vastaavilta pinnoilta poisjohdettavaa sade- tai sulamisvettä. Yleisesti huleveteen lasketaan mukaan myös perustusten kuivatusvedet. Huleveden synonyymeja ovat sadevesi ja pintavalunta. Hulevesi-termistä on muotoutunut yleisesti käytetty termi, joka tarkoittaa erilaisilta pinnoilta valuvaa sadevettä." /Matleena Hallikainen HULEVESISUUNNITELMA IIN VIHREÄÄN KORTTELIIN 

"Kiinteistöjen perustusten kuivatusvesistä, kattovesistä ja mahdollisesti piha-alueelta kerättävistä sadevesistä muodostuu yhdessä kiinteistön hulevesi, jota ei saa johtaa jätevesiviemäriin."
/ https://lieto.fi/palvelut-ja-asiointi/asuminen-ja-elinymparisto/vesihuolto/hule-ja-sadevesi/

"Hulevesiksi kutsutaan sade- ja sulamisvesiä, jotka johtuvat pois katoilta ja muilta vastaavilta tiiviiltä pinnoilta. " / https://rakennusmaailma.fi/sadevesi-on-ilmainen-luonnonvara-joka-kannattaa-kayttaa-hyodyksi-pihalla/ 

https://www.vesi.fi/teemasivu/hulevedet/

**"Skillnaden mellan dagvatten och avrinnande regnvatten är att regnvatten endast avser vatten med ursprung i regn. Dagvatten är exempelvis även smältvatten och tillfälligt framträngande grundvatten. "**

"**Med dagvatten avses regnvatten och smältvatten samt dräneringsvatten från byggnaders grunder.**" 
/ https://www.hsy.fi/sv/vatten-och-avlopp/dagvatten/

**Comment by mirmaid** [comment]
Esim. Bauhaus puhuu sadevesi- eli hulevesijärjestelmistä. Jos sanastossa on molemmat, päällekkäisyyttä tulee kyllä jonkun verran.

**Comment by mirmaid** [comment]
Melindassa nyt 16 kertaa käytetty käsitettä sadevesijärjestelmät, mutta viitteistä noin puolessa olisi ehkä kyse oikeammin hulevesijärjestelmistä, jos nämä ovat erikseen:

https://melinda.kansalliskirjasto.fi/byid/007319992
https://melinda.kansalliskirjasto.fi/byid/003180770
https://melinda.kansalliskirjasto.fi/byid/006176568

**Comment by fantsby-m** [comment]
Entä jos sanastossa olisi vain _hulevesijärjestelmät_ ja _sadevesijärjestelmät_ ohjaisi siihen? Sadevesijärjestelmät kuitenkin ovat kaiketi hulevesijärjestelmiä, vaikka kaikki hulevedet eivät olekaan sadevesiä.

**Comment by ilona-x** [comment]
Maankäyttö- ja rakennuslain käsitteitä · Luonnos :
[hulevesijärjestelmä](http://uri.suomi.fi/terminology/mrl/concept-182)
[hulevesien hallinta](http://uri.suomi.fi/terminology/mrl/concept-198)

**Comment by ilona-x** [comment]
Ja varmaan myös tuo alun perin ehdotettu hulevesialtaat olisi voinut olla ihan hyvä käsite. 🤔 
LCSH: [Storm water retention basins](http://id.loc.gov/authorities/subjects/sh85128395)  
GND: [Regenrückhaltebecken ](https://d-nb.info/gnd/4264174-3)
Wikidata: [retention basin](http://www.wikidata.org/entity/Q1413117)

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Otetaan sanastoon hulevesialtaat.
Lisätään ohjaustermi sadevesijärjestelmät KÄYTÄ hulevesijärjestelmät

Keskustelua
Riski on että käyttö on sekavaa ja päällekkäistä jos sanastossa on sekä hulevesi- että sadevesijärjestelmät. Hulevesialtaat-käsitteellä ei vastaavaa päällekkäisyysriskiä.

**Comment by mariaforsen** [comment]
Sv. dagvattenbassänger, dagvattenmagasin HT bassänger för dagvattenblandat spillvatten
https://termipankki.fi/tepa/fi/haku/hulevesiallas
https://www.vesi.fi/sv/sanasto/dagvattenbassang/
https://www.sanakirja.fi/custom/en-sv-fi/hulevesiallas
