### ISSUE TITLE
palleatyrä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11750]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

palleatyrä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/75fd8581-1c73-4460-bedb-4918686c847e

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [palleatyrä](http://finto.fi/yse/fi/page/Y511750)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D006548

**Comment by mariaforsen** [comment]
Sv. diafragmabråck  HT mellangärdsbråck, hiatushernia
https://sv.wikipedia.org/wiki/Diafragmabr%C3%A5ck
