### ISSUE TITLE
SLM/aikakausiromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11752]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM/aikakausiromaanit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Määritelmä olisi hyvä erottaa paremmin taparomaanin määritelmästä, esim. Käytetään teoksista, joissa kuvataan jotakin aikakautta ilmiöineen.

**Perustelut ehdotukselle**

Aikakausiromaani ei rajoitu "tapojen" kuvauikseen, vaan voi kuvata esim. Zeitgeistia, ajan henkeä, esim. Vilnan pokeri / Gavelis, Tuuliajolla Berliinissä / Kästner

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Jatkuvasti käytössä.

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by mirmaid** [comment]
Hyväksytään ehdotettu muotoilu ja ohjaustermin epookkiromaanit lisäys myös taparomaanit-termille.
