### ISSUE TITLE
suomi vieraana kielenä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11755]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[suomi vieraana kielenä](http://www.yso.fi/onto/yso/p38757)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

"suomi vieraana kielenä" laitetaan ohjaustermiksi termille "suomi toisena kielenä"

**Perustelut ehdotukselle**

Termien "suomi toisena kielenä" ja "suomi vieraana kielenä" ero näyttää olevan veteen piirretty viiva, ainakin jos katsoo tätä keskustelua https://tieteentermipankki.fi/wiki/Keskustelu_Kielitiede:vieras_kieli

Melindassa auktorisoituja termejä käytetty:
* 758 suomi toisena kielenä (yso/fin) - [Asteri-termitietue]
* 14  suomi vieraana kielenä (yso/fin) - [Asteri-termitietue]

Tuo 758 termiä sisältää esimerkiksi suomen kielen oppikirjoja, vaikka oppikirjojen pitäisi em. keskusteluketjun perusteella olla aina "suomi vieraana kielenä"!

Koska termejä ei pysty yksiselitteisesti määrittelemään (eikä erottamaan takautuvassa korjauksessa!), ehdotan että "suomi vieraana kielenä" laitetaan ohjaustermiksi termille "suomi toisena kielenä"

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
**suomi vieraana kielenä** otettu YSOon v. 2020 https://github.com/Finto-ehdotus/YSE/issues/7886

**Comment by mirmaid** [comment]
Tieteen termipankki kuitenkin toistaiseksi määrittelee nämä erikseen, joten en lähtisi tekemään YSOon muutoksia ennakoivasti. 

https://www.kielikello.fi/-/suomi-toisena-kielena-ja-suomi-vieraana-kielena

**Comment by mariaforsen** [comment]
Kyllä tässä on aika huomattava ero, itsekin ole opiskellut suomea toisena kielenä, ei sentään vieraana kielenä.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
