### ISSUE TITLE
Keravanjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11753]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Keravanjärvi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Keravanj%C3%A4rvi

Keravanjärvi on järvi Mäntsälässä ja Hyvinkäällä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.vhvsy.fi/content/fi/1007/1042/Julkaisut.html

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [Keravanjärvi](http://finto.fi/yse/fi/page/Y511753)

**Comment by ilona-x** [comment]
PNR: http://paikkatiedot.fi/so/1000772/10694826
