### ISSUE TITLE
Untamala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11760]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Untamala](http://www.yso.fi/onto/yso/p112931)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tämän poistaa? Untamala-termin huomautus YSO-paikoissa:
"Untamala on Laitilan kaupungin ja seurakunnan entinen nimi, nykyisin rukoushuonekunta, kylä ja taajama Laitilassa"

**Perustelut ehdotukselle**

YSO-paikoissa erikseen termi kylälle/taajamalle Untamala (Laitila) eli ei varmaankaan tarvita erikseen termiä 'Laitilan kaupungin ja seurakunnan entiselle nimelle' / rukoushuonekunnalle.

Tätä termiä käytetty paljon kylää käsittelevissä aineistoissa.

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Poistetaan, ei viittauksia.
