### ISSUE TITLE
piharatamo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11766]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

piharatamo

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://laji.fi/taxon/MX.39673

**Perustelut ehdotukselle**

Melindakuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Plantago major

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lappilaisia kokemuksia piharatamon ja ruusujuuren viljelystä.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [piharatamo](http://finto.fi/yse/fi/page/Y511766)

**Comment by mariaforsen** [comment]
Sv. groblad HT gårdsgroblad
