### ISSUE TITLE
kollegat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1176]
#### Ehdotettu termi suomeksi

kollegat
#### Ehdotetut ohjaustermit

ammattitoverit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/ysa/ryhma_78)

**Luontipäivämäärä:** 15.10.2004

**Muokkauspäivämäärä:** 15.10.2004, 16.12.2008

**Voyager-id:** 133888

**Termiehdotus Fintossa:** [kollegat](http://finto.fi/yse/fi/page/Y333888)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8897
