### ISSUE TITLE
Vårdö (Helsingfors)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11761]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vårdö (Helsingfors)](http://www.yso.fi/onto/yso/p199347)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ruotsinkieliseltä puolelta pois:
OHJAUSTERMIT Vårdö

**Perustelut ehdotukselle**

koska on olemassa kunta Vårdö http://www.yso.fi/onto/yso/p104969

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by vthuhtal** [comment]
Kyseessä on ilmiselva virhe sanastossa, koska sama termi on nyt yhtä aikaa sekä kielletty että sallittu. Ihmettelen, miksi tämän korjaaminen kestää näin kauan!?

**Comment by mariaforsen** [comment]
Tämä on ehdotusjärjestelmä, jos kyseessä on virhe, johon toivotaan nopeaa korjausta, se pitää laittaa Finto:fi:ssä olevan palautelomakkeen kautta: https://finto.fi/yso-paikat/fi/feedback?clang=sv&anylang=on (Jos asia koskee ruotsinkielisiä termejä, on kaikista nopeinta laittaa sähköpostia suoraan minulle.)
