### ISSUE TITLE
standard model of particle physics

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11762]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[standard model of particle physics](http://www.yso.fi/onto/yso/p27292)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Parempi muoto olisi: Standard model (Nuclear physics)  https://lccn.loc.gov/sh91002552

**Perustelut ehdotukselle**

LCSH siltaus

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
En laittaisi tätä päätermiksi. Ohjaustermiksi kylläkin. Standard model of particle physics näyttää selvästi olevan nuclear physicsiä yleisempi muoto kentällä. Esim. alan johtava tutkimuslaitos CERN käyttää tätä muotoa. 
https://home.cern/science/physics/standard-model
https://www.britannica.com/science/standard-model
https://www.energy.gov/science/doe-explainsthe-standard-model-particle-physics
https://www.astronomy.com/science/what-is-the-standard-model-of-particle-physics-and-why-are-scientists-looking-beyond-it/

Standard model of physics voisi myös olla ohjaustermi. Ks.
https://www.energy.gov/science/doe-explainsthe-standard-model-particle-physics
https://www.scientificamerican.com/article/is-the-standard-model-of-physics-now-broken/
