### ISSUE TITLE
få ungar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11763]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[få ungar](http://www.yso.fi/onto/yso/p19492)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus (monikielisyyden kannalta) tms.

**Perustelut ehdotukselle**

YSOssa on nyt useita eri "synnytyksiä eläinlajin mukaan" : https://finto.fi/yso/fi/page/p4556 Näistä muutamat ovat monikielisyyden kannalta ongelmallisia, ks. poikimisen lisäksi myös penikointi ja vasominen

Ks. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_7fa6f1fc10b327c4b9d583a635966ae0&list_id=1&keyword=poikia&word=poikia 

Eli ruotsiksi on nyt "få ungar" ja englanniksi samoin niin että voi olla kyseessä melkein mikä tahansa eläinlaji.. Vrt. https://www.kielitoimistonsanakirja.fi/#/poikia?searchMode=all Kun sanastossa on myös tarkempia termejä, tämä johtaa siihen että näitä käytetään epäjohdonmukaisesti. 

Ainakin ruotsin kannalta voisi olla erikseen kalvning (kor) - https://www.kielitoimistonsanakirja.fi/#/vasikoida?searchMode=all  kun kerran muiden lajien kohdalla on näin. Vasominen taas pitäisi varmaan olla sv. kalvning (hjortdjur). Mikä on YSOn tavoitetila, lisää tarkkoja termejä ja/tai myös yleinen termi poikia (mikä tahansa eläin?) = få ungar =bringing forth young

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Penikointi taas on nyt valpning (rajoittuu koiraelämiin ruotsiksi), vrt. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_02eb3039fd9f97747520d11b36759753&list_id=1&keyword=penikoida&word=penikoida ja https://www.sanakirja.fi/custom/fi-en-sv/penikointi Voitaisiinko rajoittaa koiraeläimiin YSOssa?

**Comment by mariaforsen** [comment]
Poikiminen on näköjään linkitetty tähän https://www.wikidata.org/wiki/Q11888518 eli eng. calving, sv. kalva -huono ainakin ruotsin kannalta.

**Comment by mirmaid** [comment]
Onkohan tässä taustalla vasikointi-sanan kaksoismerkitys suomeksi...

**Comment by mirmaid** [comment]
Poikiminen 121 kertaa Melindassa. Lähes kaikki viitteet koskevat nautakarjaa, joukossa muutamia yksittäisiä, joissa todennäköisesti viitataan useampaan eläinlajiin, ja sikoja, lampaita, ahmaa ja villisikaa käsitteleviä kutakin yksi.

porsiminen x 55
varsominen x 40
karitsoiminen x 21
penikointi x 41 (koirista ja turkiseläimistä)
vasominen x 31 (poroista ja muutamia kertoja virheellisesti lehmistä)

synnytys + koira x 61
synnytys + kissa x 11
synnytys + lehmät x 15
synnytys + hevonen x 12
synnytys + lammas x 1
synnytys + poro x 1

**Comment by mariaforsen** [comment]
Monikielisyyden kannalta olisi siis tärkeää saada joko yksi kaikkia eläimiä koskeva käsite tai sitten tarkempia käsitteitä. Ei voida myöskään muuttaa få ungar > pelkkä kalvning, vaan sille täytyy lisätä tarkenne (nötdjur/nautaeläimet?) siinä tapauksessa.

**Comment by mirmaid** [comment]
^ Tuossa nyt siis lähinnä nykytilan kuvaus. Poikiminen voidaan varmasti muuttaa tavalla tai toisella yksiselitteisesti nautoja koskevaksi, mutta lisähuomiona että penikointi käytetään myös turkiseläimistä (jopa enemmän kuin koirista), ja että myös synnytys-termiä käytetään usein eläimistä. Koirista sitä on käytetty enemmän kuin penikointi-termiä. Enkä kyllä tiedä mikä voisi olla yhteinen eläinten synnytystä kuvaava termi, paitsi synnytys. Monien eläinlajien kohdalla poikiminen olisi todella omituinen ja jopa jotenkin halventavan kuuloinen sana.

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään myöhemmäksi ja tutkitaan tarkemmin. Poikiminen pystyttäneen muuttamaan.

**Comment by mirmaid** [comment]
Tarkennettu > poikiminen (nautaeläimet). Miten jatketaan?

**Comment by mariaforsen** [comment]
Onko penikointi lähinnä koiraeläimen, tai voisiko sen rajata niin? Nyt sen mukaan käännetty ainakin. 
https://www.kielitoimistonsanakirja.fi/#/penikoida?searchMode=all
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_8c2c63d81d32910e6b6d245cc191fbcd&list_id=1&keyword=penikointi&word=penikointi ..Eli sv. ynglande on lähinnä kaloista, sammakkoeläimistä yms. EI ole siis myöskään mahdollista laittaa "valpning och ynglande", vaan tarvitaan selkeä rajaus siitä minkätyyppisistä eläimistä on kyse. 

Muut synnytys eläinlajin mukaan-termin alakäsitteet taitavat nyt olla ok ainakin suomi-ruotsi-suhteen kannalta: 
[karitsoiminen](https://finto.fi/yso/fi/page/p18518)
[penikointi](https://finto.fi/yso/fi/page/p14940)
[poikiminen (nautaeläimet)](https://finto.fi/yso/fi/page/p19492)
[porsiminen](https://finto.fi/yso/fi/page/p12895)
[varsominen](https://finto.fi/yso/fi/page/p17034)
[vasominen](https://finto.fi/yso/fi/page/p19491)

**Comment by mirmaid** [comment]
Penikointi käytetty Melindassa myös minkeistä, ja aineistoissa "minkvalpar", eli varmaan oikeasti on käytössä myös ruotsiksi niistäkin.

**Comment by mirmaid** [comment]
Miten lähdetään ratkomaan tätä muuten, jos förlossning sopii vain ihmisiin? Sen alakäsite on kyllä nyt djurförlossning (ryhmittelevä käsite, suom. synnytys eläinlajin mukaan), joten vähän hämmentävää jos voi olla djurförlossning, mutta pelkkä förlossning rajautuu ihmisiin? Vai onko tuo djurförlossning virhe? 

Jos on pakko tarkentaa synnytys (ihmiset) niin sitten on pakko keksiä vielä joku yleistermi eläinten synnytykselle (tyyliä synnytys (eläimet) tai poikasten synnytys).

**Comment by mariaforsen** [comment]
Näyttää (mielenkiintoista kyllä) siltä että ainakin googlessa förlossning käytetään entistä enemmän myös eläimistä, esim. kattförlossning yms. Joten aivan virheelliseksikään ei voi sanoa. Kuvailijoita voisi siinä tapauksessa vielä vakuuttaa lisäämällä ohjausterminä födsel (djur) ANV förlossning. Djurförlossning on jonkinlainen keksitty käännös tuolle ryhmittelevälle käsitteelle (en tiedä tai ainakaan muista taustoja sille), mutta se voisi mieluummin olla "födsel enligt djurart" tms. koska sehän ei ylipäätään ole tarkoitus toimia asiasanana. 
Summa summarum: jos tahtotila suomeksi on että ihmisten ja muiden eläinten synnytyksiä käsitellään ja haetaan samalla termillä, se on varmaan mahdollista myös ruotsin kannalta (varsinkin jos/kun ajattelee että ihminen on vain eläin muiden joukossa).

**Comment by YSO-kokous** [comment]
PÄÄTÖS
synnytys (koira) KÄYTÄ penikointi
ruotsiksi synnytys/förlossning-käsitteelle lisättäneen ohjaustermejä, jotka selkeyttävät käyttöä.

Keskustelua:
Pohdittiin, pitäisikö penikointi-käsite poistaa, jos synnytys-käsitettä voi hyvin käyttää vastaavissa konteksteissa.
Päädyttiin kuitenkin säilyttämään, koska käsitteen merkitys on suhteellisen selvä ja päätetty ohjaustermi myös ohjaa käyttöä. Asiaan voidaan palata tarvittaessa.
