### ISSUE TITLE
patongit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11779]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

patongit

**Ehdotettu termi ruotsiksi**

batong

**Ehdotettu termi englanniksi**

baguette

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjastoomme hankitaan paljon keittokirjoja ja muita ruokaaiheisia kirjoja restonomikoulutusta varten joista monet käsittelevät jotakin tiettyä ruokalajia, -ainetta tai valmistusmenetelmää, ja näiden teosten tehokasta kuvailua varten tarvitsisimme tarkempia termejä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [leipä](http://www.yso.fi/onto/yso/p9121)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018807384

**Ehdottajan organisaatio**

Haaga-Helia ammattikorkeakoulu
**Termiehdotus Fintossa:** [patongit](http://finto.fi/yse/fi/page/Y511779)

**Comment by mariaforsen** [comment]
Sv. baguette HT batong (bröd), bagett (bröd), pain riche, painriche
https://svenska.se/tre/?sok=batong&pz=1
https://svenska.se/tre/?sok=painriche&pz=8
https://svenska.se/tre/?sok=baguette&pz=1
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_8db2d18dd33045fba1996d5bf633d763&list_id=1&keyword=patonki&word=patonki

**Comment by mirmaid** [comment]
Melindassa runsaasti yksikössä. YSOssa _leipä_ ja sen alakäsitteet (paitsi _sämpylät_ ja _tortillat_) ovat yksikössä. _Voileivät_ taas monikossa _ruokalajit_-käsitteen alla.

**Comment by nikopartanen** [comment]
Ehkä patongilla ei varsinaisesti ajatella olevan erilaisia alatyyppejä, tosin juuri kulinarismikontekstissa varmaan onkin. 🤔

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään yksikössä _patonki_.
