### ISSUE TITLE
poikuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11775]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

poikuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

boyhood

**Tarkoitusta täsmentävä selite**

Poikana oleminen, poikaikä

**Perustelut ehdotukselle**

Koska sanastossa on tyttöyskin, pitäisi olla myös poikuus. Sen voi täsmentää että ei käytetä merkityksessä "neitsyys". 

**Ehdotettu yläkäsite YSOssa (LT)**

 [mentaaliset ominaisuudet](http://www.yso.fi/onto/yso/p115), [yhteiskunnalliset ominaisuudet](http://www.yso.fi/onto/yso/p28822)

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543), [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

 poikana oleminen

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [tyttöys](http://www.yso.fi/onto/yso/p24107)

**Vastaava käsite muussa sanastossa**

 [Kielitoimiston sanakirja](https://www.kielitoimistonsanakirja.fi/#/poikuus?searchMode=all)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lastenkirja poikana olemisesta: Ranj Singh : How to be a boy and do it your own way! 978-1-5263-6496-8 

**Ehdottajan organisaatio**

Kirjastopalvelu / PA
**Termiehdotus Fintossa:** [poikuus](http://finto.fi/yse/fi/page/Y511775)

**Comment by tpalonen** [comment]
Vähintäänkin tarvittaisiin sulkutarkenne. Esimerkiksi Google-tulokset ja termin käyttö hs.fi-sivustolla käsittelevät melkeinpä yksinomaan seksuaalista kokemattomuutta. Olisiko mikään muu termi mahdollinen? Esim. _poikaikä_? Tai _poikaidentiteetti_?

**Comment by mariaforsen** [comment]
Sv. pojkskap HT pojktid, pojkålder, pojkidentitet
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4fb5ea25f2680e8b62a5a523b1a67474&list_id=1&keyword=poikuus&word=poikuus

**Comment by mirmaid** [comment]
_Poikuus_ on KAUNOssa RT-termeistä päätelleen juuri tuossa kokemattomuus-merkityksessä. Onhan tässä selkeä puute, mutta en tiedä toimisiko poikaikä tai -identiteetti korvaajana, kun ne tuntuvat painottuvan vähän tarkemmin tiettyyn aspektiin. Ehkä poikuus (identiteetti), ja mahdollisesti vielä selitys.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _poikuus (poikana oleminen)_.

**Comment by tpalonen** [comment]
Päätermin muodosta äänestettiin. Vaihtoehtoina olivat _poikana oleminen_ ja _poikuus (poikana oleminen)_. Enemmistö kannatti jälkimmäistä.

Päätettiin myös lisätä ohjaustermi:
_poikuus (neitsyys)_ KÄYTÄ _neitsyys_
