### ISSUE TITLE
ehiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11770]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ehiöt

**Ehdotettu termi ruotsiksi**

helsaker

**Ehdotettu termi englanniksi**

postal stationery

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Filatelian aineistona postimerkkeihin rinnastettava, puuttuu kuitenkin YSO:sta.

**Ehdotettu yläkäsite YSOssa (LT)**

 [postilähetykset](http://www.yso.fi/onto/yso/p12531)

**Ehdotetut temaattiset ryhmät**

 [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [filatelia](http://www.yso.fi/onto/yso/p11146)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85105517), [Tesaurus för grafiskt material](https://id.kb.se/term/gmgpc/swe/Helsaker)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Finland postal stationery envelopes 1845-1884 : Juhani Pietilän kokoelma / Juhani Pietilä. (Melinda-ID 018844114)

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [ehiöt](http://finto.fi/yse/fi/page/Y511770)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ehi%C3%B6

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
