### ISSUE TITLE
koiranpennut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11772]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

koiranpennut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Häiritsee korjata pennut > poikaset, kun kyse koirasta...

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melinda

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [koiranpennut](http://finto.fi/yse/fi/page/Y511772)

**Comment by mariaforsen** [comment]
Sv. hundvalpar

**Comment by ilona-x** [comment]
koiranpennut ja kissanpennut -termien tarpeesta keskusteltiin pennut-issuessa https://github.com/Finto-ehdotus/YSE/issues/9445#issuecomment-972936871
 
--

LCSH:
puppies http://id.loc.gov/authorities/subjects/sh85109152
kittens http://id.loc.gov/authorities/subjects/sh85072589

SAO:
hundvalpar https://id.kb.se/term/sao/Hundvalpar

**Comment by mirmaid** [comment]
^ Tilanne konkretisoitui, kun olin ajamassa korjausta Melindaan 🙂. Koiranpennuista paljon aineistoa, kuten voi arvatakin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
