### ISSUE TITLE
croissantit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11776]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

croissantit

**Ehdotettu termi ruotsiksi**

croissanter

**Ehdotettu termi englanniksi**

croissants

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjastoomme hankitaan paljon keittokirjoja ja muita ruokaaiheisia kirjoja restonomikoulutusta varten joista monet käsittelevät jotakin tiettyä ruokalajia, -ainetta tai valmistusmenetelmää, ja näiden teosten tehokasta kuvailua varten tarvitsisimme tarkempia termejä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [leivonnaiset](http://www.yso.fi/onto/yso/p2455)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

 voisarvet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018807390

**Ehdottajan organisaatio**

Haaga-Helia ammattikorkeakoulu
**Termiehdotus Fintossa:** [croissantit](http://finto.fi/yse/fi/page/Y511776)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _croissantit_.
