### ISSUE TITLE
Malayan colugos

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11793]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Malayan colugos](http://www.yso.fi/onto/yso/p13032)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

flying lemurs?

**Perustelut ehdotukselle**

Oikea kohde lienee lat. Dermoptera
https://laji.fi/taxon/MX.50470

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
^ Varmaan riittävä tarkkuus. Eng. colugos?

**Comment by tpalonen** [comment]
Muutettu englanti -> colugos
