### ISSUE TITLE
Kuuden päivän sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11823]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kuuden päivän sota

**Ehdotettu termi ruotsiksi**

Sexdagarskriget

**Ehdotettu termi englanniksi**

Six-Day War

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Six-Day War | Definition, Causes, History, Summary, Outcomes, & Facts | Britannica
https://fi.wikipedia.org/wiki/Kuuden_p%C3%A4iv%C3%A4n_sota
On ollut Puolustushallinnon asiasanaston (pha) terminä ja siksi esiintyy edelleen vanhemmassa asiasanoituksessa. Pha-termit voitaisiin korvata YSO-termeillä ja käyttää uutta YSO-termiä myös jatkossa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85068715.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.152391?sid=2987057784

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [Kuuden päivän sota](http://finto.fi/yse/fi/page/Y511823)

**Comment by mirmaid** [comment]
Pienellä alkukirjaimella sotien nimien ohjeistuksen mukaan.

**Comment by mariaforsen** [comment]
Sv. sexdagarskriget HT tredje arabisk–israeliska kriget.
