### ISSUE TITLE
Georgian sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11824]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Georgian sota

**Ehdotettu termi ruotsiksi**

Kriget i Georgien 2008

**Ehdotettu termi englanniksi**

South Ossetia War, 2008

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Georgian_sota Aiheesta on kirjoitettu paljon vuoden 2008 jälkeen, sekä kirjoja että artikkeleita. "Georgian sota" on myös ollut Puolustushallinnon asiasanaston (pha) terminä ja siksi esiintyy edelleen vanhemmassa asiasanoituksessa. Pha-termit voitaisiin korvata YSO-termeillä ja käyttää uutta YSO-termiä myös jatkossa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh2009006442.html), [SOTO](https://finto.fi/soto/fi/page/p1320), [Libris](https://id.kb.se/term/sao/Kriget%20i%20Georgien%202008)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://libris.kb.se/bib/fw3f0pskclx1smp7?tab2=subj 

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [Georgian sota](http://finto.fi/yse/fi/page/Y511824)

**Comment by mirmaid** [comment]
Aikatarkenne tarpeen tässä?

**Comment by mariaforsen** [comment]
Sv. kriget i Georgien (2008) HT Georgienkriget (2008), rysk-georgiska kriget (2008), Rysslands invasion av Georgien (2008), Sydossetienkriget (2008), sydossetiska kriget (2008) 
https://id.kb.se/find?q=kriget%20i%20georgien
https://sv.wikipedia.org/wiki/Kriget_i_Georgien_2008
https://en.wikipedia.org/wiki/List_of_wars_involving_Georgia_(country)
