### ISSUE TITLE
raketinheittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11835]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

raketinheittimet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Raketinheitin on tykistöase, mutta se eroaa merkittävästi perinteisestä kenttätykistä. Varsinainen ase muodostuu molemmista päästä avoimista putkista tai muista ohjaimista, joiden tehtävänä on antaa raketille oikea lähtösuunta.

**Perustelut ehdotukselle**

Tarvitaan kyseistä asetyyppiä käsittelevien lähteiden kuvailuun erottamaan muista aseista.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tykit](http://www.yso.fi/onto/yso/p2312)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Soto](https://finto.fi/soto/fi/page/p97), [Wikipedia](https://en.wikipedia.org/wiki/Rocket_artillery)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/arto.013357806?sid=2931368412

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [raketinheittimet](http://finto.fi/yse/fi/page/Y511835)

**Comment by mariaforsen** [comment]
Sv. raketkastare (vapen) (fi) HT raketartilleri, salvpjäser

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a52a55462a9da50d2a19ccea3472b77c&list_id=1&keyword=raketinheitin&word=raketinheitin
https://www.google.com/search?sca_esv=568147601&rlz=1C1GCEU_enFI883FI883&sxsrf=AM9HkKnBsjzM80caVJhj1QIMNjW_aeA70Q:1695636750093&q=%22raketkastare%22&tbm=isch&source=lnms&sa=X&ved=2ahUKEwj-4qCRw8WBAxW5FxAIHSEQDPQQ0pQJegQIChAB&biw=948&bih=489&dpr=1.88
https://www.google.com/search?sca_esv=568147601&rlz=1C1GCEU_enFI883FI883&sxsrf=AM9HkKnyBPaI5De9tMZ6FNs5eIbXLuMdYw:1695636776155&q=%22raketartilleri%22&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiOw9edw8WBAxUuIBAIHcNpAkQQ0pQJegQICxAB&biw=948&bih=489&dpr=1.88
https://sv.wikipedia.org/wiki/Raketartilleri
https://www.wikidata.org/wiki/Q167682
https://www.finlex.fi/sv/laki/alkup/1994/19940396
https://www.kielitoimistonsanakirja.fi/#/raketinheitin?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/rakettiase?searchMode=all
https://svenska.se/tre/?sok=pj%C3%A4s&pz=1
https://svenska.se/tre/?sok=artilleri&pz=1
https://www.sanakirja.fi/custom/en-sv-fi/raketkastare
