### ISSUE TITLE
korvayökkö, pohjanlepakko, viiksisiippa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11838]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

korvayökkö, pohjanlepakko, viiksisiippa

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://www.luomus.fi/fi/suomessa-tavatut-lepakkolajit

**Perustelut ehdotukselle**

Näistä löytyy ja tulee lisää aineistoja. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [lepakot](http://www.yso.fi/onto/yso/p11728)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikipedia](https://fi.wikipedia.org/wiki/Korvay%C3%B6kk%C3%B6), [wikipedia](https://fi.wikipedia.org/wiki/Viiksisiippa), [wikipedia](https://fi.wikipedia.org/wiki/Pohjanlepakko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lepakkotutkimuksen aineistot

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [korvayökkö, pohjanlepakko, viiksisiippa](http://finto.fi/yse/fi/page/Y511838)

**Comment by mariaforsen** [comment]
Sv. -brunlångöra HT långörad fladdermus https://namnochslaktskap.artfakta.se/taxa/206002/names/47168
-nordfladdermus HT nordisk fladdermus https://namnochslaktskap.artfakta.se/taxa/205998/details
-mustaschfladdermus https://namnochslaktskap.artfakta.se/taxa/102102/names/47153
