### ISSUE TITLE
strateginen kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11836]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

strateginen kulttuuri

**Ehdotettu termi ruotsiksi**

strategisk kultur

**Ehdotettu termi englanniksi**

strategic culture

**Tarkoitusta täsmentävä selite**

"Kansainvälisen politiikan tutkimuksessa strategisella kulttuurilla tarkoitetaan 
viime kädessä maan turvallisuuspolitiikassa, voimapolitiikassa ja sotilaallisessa 
suuntautumisessa vallalla olevaa kansallista politiikan toteuttamisen tapaa tai 
tyyliä. Tämän identifioinnin pohjalta on ajateltu voitavan tehdä ennusteita valtion toimintamalleista ja selittää tehtyjä ratkaisuja. Käsitettä on käytetty ennen 
kaikkea vahvojen valtioiden toiminnan selittämisessä, varsinkin voimankäyttöä 
koskevan päätöksenteon osalta." Sivonen, Pekka (Tiede ja ase nro 1, 2019)

**Perustelut ehdotukselle**

Ajankohtainen ja kuvaava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh2008004130.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/arto.018217725
https://mpkk.finna.fi/Record/taisto.168989

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [strateginen kulttuuri](http://finto.fi/yse/fi/page/Y511836)

**Comment by mirmaid** [comment]
10 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _strateginen kulttuuri (sotilaspolitiikka)_.

**Comment by mariaforsen** [comment]
Sv. strategisk kultur (militärpolitik)
