### ISSUE TITLE
Kuuban ohjuskriisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11834]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kuuban ohjuskriisi

**Ehdotettu termi ruotsiksi**

Kubakrisen

**Ehdotettu termi englanniksi**

Cuban missile crises

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuuban ohjuskriisi oli lokakuussa 1962 Yhdysvaltain ja Neuvostoliiton välille kehittynyt suurvaltapoliittinen kriisi liittyen ballististen ohjusten sijoittamiseen Kuubaan. Konfliktia pidetään kylmän sodan uhkaavimpana tilanteena, joka olisi voinut kärjistyä ydinsodaksi.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85034624.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.167955?sid=2986992678

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [Kuuban ohjuskriisi](http://finto.fi/yse/fi/page/Y511834)

**Comment by mariaforsen** [comment]
Sv. Kubakrisen HT Cubakrisen, Kubakrisen (1962)

**Comment by mirmaid** [comment]
KT Kuuban kriisi

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
