### ISSUE TITLE
kapinat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11833]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kapinat](http://www.yso.fi/onto/yso/p9852)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotetaan lisättäväksi ohjaustermi: kumouksellinen sota

**Perustelut ehdotukselle**

Kapinat-termin englannin- ja ruotsinkieliset termit viittaavat myös kumoukselliseen sotaan. Aineistoa, johon kyseinen käsite soveltuu: https://mpkk.finna.fi/Record/taisto.165843?sid=2986994883.

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu

**Comment by mariaforsen** [comment]
Ruotsinkielinen termi on ALLFOssa uppror, ja tämä termi ei ota kantaa siihen minkälaisesta kapinasta on kyse (https://svenska.se/tre/?sok=uppror&pz=1), eikä välttämättä liity sotaan.

**Comment by mirmaid** [comment]
Kumouksellinen sodankäynti (insurgency) on määritelty organisoiduksi liikkeeksi perustuslaillisen hallituksen syöksemiseksi vallasta kumouksellista toimintaa ja aseellisia konflikteja käyttäen. Kumouksellisessa sodassa osa maan asukkaista käy hallitsevaa valtaa vastaan suunnattua taistelua valtakunnan alueella joko ulkopuolisen tuen turvin tai ilman sitä. https://www.doria.fi/handle/10024/124044

Kapina = jnk joukon (aseellinen) nousu esivaltaa vastaan. (Kielitoimiston sanakirja)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermi _kumouksellinen sota_.

**Comment by mariaforsen** [comment]
Sv. revolutionärt krig
