### ISSUE TITLE
robottiaseet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11839]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[robottiaseet](http://www.yso.fi/onto/yso/p27732)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSO-käsite tulisi olla autonomiset asejärjestelmät, robottiaseiden tulisi olla ohjaustermi.

**Perustelut ehdotukselle**

Alan tutkimuksen piirissä käytettävä termi on autonomiset asejärjestelmät. Termi on vakiintunut käyttöön viimeisen 10 vuoden kuluessa. Robottiaseet-termiä käytetään joskus mediassa, mutta ei juurikaan asiantuntijaorganisaatioissa. Opinnäytteiden, alan kirjojen ja artikkeleiden asiasanoittaminen robottiaseet-termillä antaa väärän mielikuvan eikä myöskään tue tiedonhakua.

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by mirmaid** [comment]
_Autonomiset asejärjestelmät_ on nyt ohjaustermi, eli muutosehdotus ohjaustermin vaihtamisesta päätermiksi.

**Comment by mariaforsen** [comment]
Sv. robotvapen > autonoma vapensystem
https://sv.wikipedia.org/wiki/Autonoma_vapensystem
https://www.ui.se/globalassets/personal-cv--publikationer/frnd_rapport_dodliga-autonoma-vapensystem.pdf
https://www.europarl.europa.eu/doceo/document/B-8-2018-0355_SV.html
https://id.kb.se/term/sao/Robotvapen

**Comment by ilona-x** [comment]
LCSH:
Autonomous weapons systems  http://id.loc.gov/authorities/subjects/sh2020000673
Autonomous weapons systems (International law) http://id.loc.gov/authorities/subjects/sh2020000047

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
