### ISSUE TITLE
vastakumouksellinen sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11837]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vastakumouksellinen sota

**Ehdotettu termi ruotsiksi**

upprorsbekämpning

**Ehdotettu termi englanniksi**

counterinsurgency

**Tarkoitusta täsmentävä selite**

Vastaavasti termi counterinsurgency määritellään vallassa olevan hallituksen sotilaallisiksi, puolisotilaallisiksi, poliittisiksi, taloudellisiksi, psykologisiksi ja siviiliasiain toimiksi kumouksellisen sodankäynnin
voittamiseksi.

**Perustelut ehdotukselle**

Vaikea kuvata asiaa muilla käsitteillä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85033442.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://libris.kb.se/bib/13589279?tab2=subj
https://mpkk.finna.fi/Record/taisto.169132?sid=3083376675

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [vastakumouksellinen sota](http://finto.fi/yse/fi/page/Y511837)

**Comment by mariaforsen** [comment]
Sv. upprorsbekämpning /sao HT militär motaktion, kontrarevolutionärt krig 
https://www.sanakirja.fi/custom/en-sv-fi/counterinsurgency

**Comment by mirmaid** [comment]
Saan Google-haulla lähinnä vain teokseen _Kumouksellinen ja vastakumouksellinen sota_ liittyviä viitteitä. Sanakirjassa counterinsurgency = vastakumouksellinen toiminta. 

https://en.wikipedia.org/wiki/Counterinsurgency

Varmasti mahdoton kuvata ilman tarkkaa termiä, SOTO-käsitettä käytetty n. 30 kertaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Varmistetaan parhaiten sopiva termi. Ehdotetaan varauksella hyväksyttäväksi _vastakumouksellinen sota_, ohjaustermiksi _vastakumouksellinen toiminta_, tai mahdollisesti toisinpäin.
