### ISSUE TITLE
kielellinen erityisvaikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11848]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kielellinen erityisvaikeus](http://www.yso.fi/onto/yso/p12073)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

kehityksellinen kielihäiriö (DLD, Developmental Language Disorder)

**Perustelut ehdotukselle**

Kehityksellinen kielihäiriö on ajanmukainen käsite, aiemmin ollut kielellinen erityisvaikeus. Kehityksellinen kielihäiriö termi on käytössä esimerkiksi 2019 julkaistussa Käypä Hoito suosituksessa

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://www.kielipolku.info/kielihairio/

Edellisen kerran muutettu 2016, toivottavasti nyt olisi pysyvä nimi.

**Comment by mariaforsen** [comment]
Sv. specifik språkstörning > utvecklingsrelaterad språkstörning
https://www.kaypahoito.fi/sv/gvr00033
https://www.kela.fi/familjekurs-for-barn-med-utvecklingsrelaterad-sprakstorning
https://www.aivoliitto.fi/svenska/utvecklingsrelaterad-sprakstorning/#734514e7
https://www.abo.fi/projekt/barnsprak-storningar-i-sprakutvecklingen/
https://ki.se/clintec/spets-projektbeskrivning
https://logopeden.se/konsekvenser-av-sprakstorning-jobb-och-utbildning/
https://sv.wikipedia.org/wiki/Specifik_spr%C3%A5kst%C3%B6rning
https://logopeden.se/fokus-pa-sprakstorning-dld/
