### ISSUE TITLE
korean kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11842]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[korean kieli](http://www.yso.fi/onto/yso/p19675)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Luodaan uusi käsite 'korealaiset kielet', jonka alle 'korean kieli' siirretään.

**Perustelut ehdotukselle**

Nykyään kielitieteessä ajatellaan usein, että korean kieli ei olisi isolaatti, vaan oma pieni korealaisten kielten kieliperheensä. Korean kielen lisäksi tähän kuuluu ainakin omaksi kieleksi katsottava jeju, jota on perinteisesti ajateltu korean murteena (https://fi.wikipedia.org/wiki/Korealaiset_kielet). 

**Ehdottajan organisaatio**

KK / Niko

**Comment by mariaforsen** [comment]
Sv. koreanska språk
