### ISSUE TITLE
ulkomaantoimittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11849]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ulkomaantoimittajat](http://www.yso.fi/onto/yso/p24634)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT ulkomaankirjeenvaihtajat

**Perustelut ehdotukselle**

Wikidata-linkityksen yhteydessä ehdotettu. Onko ongelma, jos ulkomaantoimittajat-käsitettä käytetään myös kotimaassa työskentelevistä ulkomaanuutisten toimittajista?

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
YSOssa myös [kirjeenvaihtajat ](http://www.yso.fi/onto/yso/p4843), mikä linkattu Wikidataan https://www.wikidata.org/wiki/Q1155838 
ja Wikidata-kohteen yhteydessä olevassa Wikipedia-artikkelissa näin:
"Kirjeenvaihtaja tai ulkomaankirjeenvaihtaja on lehden, televisioyhtiön tai muun [joukkoviestimen](https://fi.wikipedia.org/wiki/Joukkotiedotusv%C3%A4line) [toimittaja](https://fi.wikipedia.org/wiki/Toimittaja) tai avustaja, joka [asuu ulkomailla](https://fi.wikipedia.org/wiki/Ulkomaanty%C3%B6ntekij%C3%A4) ja lähettää sieltä raportteja ja juttuja toimitukseen"
https://fi.wikipedia.org/wiki/Kirjeenvaihtaja

**Comment by mirmaid** [comment]
^ Tosiaan. Eli ulkomaankirjeenvaihtajat olisi ehkä ennemmin ohjaustermi kirjeenvaihtajat-käsitteelle.

**Comment by LeKorsu** [comment]
Ulkomaantoimittaja voi ehdottomasti olla kotitoimituksessa työskentelevä toimittaja (joka välillä käy juttumatkoilla ulkomailla). Ulkomaankirjeenvaihtajasta ohjaustermi kirjeenvaihtajille,

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään, seurataan yllä olevaa ehdotusta.
