### ISSUE TITLE
akvaporiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11845]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

akvaporiinit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/a6c0593c-e442-4b77-86d6-6726b36c0e61

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [akvaporiinit](http://finto.fi/yse/fi/page/Y511845)

**Comment by mariaforsen** [comment]
Sv. akvaporiner HT aquaporiner, vattenporiner

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Akvaporiini
