### ISSUE TITLE
planetaarinen ruokavalio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11844]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

planetaarinen ruokavalio

**Ehdotettu termi ruotsiksi**

planetär hälsodiet

**Ehdotettu termi englanniksi**

planetary health diet

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tämäntyyppinen aineisto tullee lisääntymään, myös nykyisissä ravitsemussuosituksissa otettu huomioon planeetan terveys

**Ehdotettu yläkäsite YSOssa (LT)**

 [ruokavaliot](http://www.yso.fi/onto/yso/p3790)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550), [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Planetaarinen_ruokavalio#Ruokasuositukset)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim.
Positively green : everyday tips to help the planet and calm climate anxiety 
Planetaarinen ruokavalio & elämäntapa  / Hanna Haveri

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [planetaarinen ruokavalio](http://finto.fi/yse/fi/page/Y511844)

**Comment by mariaforsen** [comment]
Sv. planetär hälsodiet HT planetär kost, planetär diet, Eat-Lancetkost
https://sv.wikipedia.org/wiki/Planet%C3%A4r_h%C3%A4lsodiet
https://www.vetenskaphalsa.se/hallbar-kost-for-manniska-och-planet/

**Comment by mirmaid** [comment]
Ei vielä Melindassa, mutta uskon ja toivon että aineistoa kyllä tulee.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
