### ISSUE TITLE
PCDD-yhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11843]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[PCDD-yhdisteet](http://www.yso.fi/onto/yso/p21056)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi polyklooratut dibentsodioksiinit

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/pcdd
https://finto.fi/mesh/sv/page/D000072317

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. polyklorerade dibensodioxiner
