### ISSUE TITLE
suljettu talousjärjestelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11857]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[suljettu talousjärjestelmä](http://www.yso.fi/onto/yso/p11772)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan ohjaustermiksi tälle autarkia (en. autarky, sv. autarki). 

**Perustelut ehdotukselle**

Wikipediassa ja Wikidatassa closed economy ohjaa Autarky-käsitteeseen/-artikkeliin. En-Wikipedian mukaan: "Autarky is the characteristic of self-sufficiency, usually applied to societies, communities, states, and their economic systems." Encyclopedia Britannica: "autarky, an economic system of self-sufficiency and limited trade. A country is said to be in a complete state of autarky if it has a closed economy, which means that it does not engage in international trade with any other country."

Lisäisin ohjaustermin, koska Wikipedia on nykyisin niin paljon käytetty lähde ja siellä kuitenkin kyseinen termi pääterminä. Päätös vaikuttaa myös käsitteen linkityksiin.
https://en.wikipedia.org/wiki/Autarky
https://www.britannica.com/money/autarky

Obs! Autarkia-termi voi tarkoittaa myös valtiota, joka harjoittaa autarkiaa.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Ehkä sulkutarkenteella, vrt. https://tieteentermipankki.fi/wiki/Filosofia:autarkia

**Comment by mariaforsen** [comment]
Sv. autarki (ekonomi)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _autarkia (talous)_ ohjaustermiksi.
