### ISSUE TITLE
raamatunkritiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11854]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[raamatunkritiikki](http://www.yso.fi/onto/yso/p10496)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Merkitystä selvennettävä. Ehdotetaan käsitteen rajaamista Raamatun tutkimukseen / tulkintaan kriittisin metodein.

**Perustelut ehdotukselle**

Ongelma havaittiin YSO-Wikidata-linkityksessä. Käsitteen sisällön perusteella on epäselvää, tarkoittaako se kritiikkiä Raamattua (eli sen oppia) kohtaan, vai tarkoittaako se Raamatun tulkintaa ja tutkimusta kriittisin metodein (vrt. kirjojen kriittiset editiot). Melinda-kuvailussa tätä on käytetty molemmissa merkityksissä. Tällä on RT:nä uskontokritiikki, mikä antaisi ymmärtää, että käsite viittaa Raamatun opin kritisointiin. Kuitenkin englannin termi on biblical criticism, mikä tarkoittaa Raamatun tulkintaa/tutkimusta. Vrt. Teologian asiasanastossa termillä on RT:t sekä eksegetiikkaan että uskontokritiikkiin eli kaksoismerkitys saattaa olla peräisin sieltä.  
Päätöksen myötä olisi syytä tarkistaa eri kieliset termit ja linkitys.

Ks. Wikipedia-artikkelit:
https://en.wikipedia.org/wiki/Biblical_criticism
https://en.wikipedia.org/wiki/Criticism_of_the_Bible

Esimerkkejä Melinda-kuvailusta:
The meaning of the Pentateuch : revelation, composition, and interpretation / John H. Sailhamer.
https://melinda.kansalliskirjasto.fi/byid/005722941
Marxist feminist criticism of the Bible / edited by Roland Boer and Jorunn Økland.
https://melinda.kansalliskirjasto.fi/byid/005712055

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Sivuhuomio: Melindassa käytetty muutamaan kertaan vapaata asiasanaa _raamattukritiikki_.

**Comment by mariaforsen** [comment]
Sv. voisi olla bibelkritik (bibelforskning)

**Comment by mirmaid** [comment]
Tähän on pyydetty kommentti myös teologisen tiedekunnan kirjastosta.

**Comment by leinon** [comment]
Entisessä teologian asiasanastossa raamatunkritiikki vertautuu asiasanaan uskontokritiikki. 
Uskontokritiikki RT ateismi, epäily, marxismi, raamatunkritiikki 

Raamatuntulkinta ja eksegetiikka ovat siis erikseen. Kuten aikaisemmin mainittiin, englanninkielisen Criticism-sanan voi ymmärtää analyysina ja tulkintana.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _raamatunkritiikki (kriittisyys)_. Tutkitaan käyttöhuomautuksen mahdollisuutta.

**Comment by mariaforsen** [comment]
Sv. bibelkritik (kritik mot)
