### ISSUE TITLE
laserit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11856]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laserit](http://www.yso.fi/onto/yso/p1145)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan käsitteen eroa laserlaitteet-käsiteeseen. Poistetaan tarvittaessa jompikumpi käsite sanastosta.

**Perustelut ehdotukselle**

YSOssa on kaksi likeistä käsitettä: laserit ja laserlaitteet. Laser-termi jo yksistään viittaa laitteeseen. Laserit-käsite on säteilylaitteiden alla eli kyse on YSO-hierarkiankin mukaan laitteesta. Englannin Wikipedia: "Laser is a device". Suomen Wikipedia: "Laser on laite". Kielitoimiston sanakirja: "laser: laite."

Sanastossa tuskin tarvitaan kahta käsitettä, kun ne tarkoittavat samaa asiaa.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Lisäksi löytyy _lasersäteily, laserpulssit, lasertekniikka_ jne. joten yhdistäminen ei varmaankaan ongelma. Kumpi päätermiksi? _Laserit_ on vanhempi (1986/1993), _laserlaitteet_ ehkä yksiselitteisempi.

**Comment by ilona-x** [comment]
Jotenkin laserit tuntuisi helpommalta käyttää kuvailussa kuin laserlaitteet. 🤔 

Melinda: 
laserlaitteet x 156 
laserit 609 
laserlaitteet & laserit 70

FinMeSH: [laserit ](http://www.yso.fi/onto/mesh/D007834)KT laserlaitteet

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään päätermit _laserit_, ohjaustermi _laserlaitteet_.

**Comment by tpalonen** [comment]
Laittaisin tämän päätöksen myötä lasersoittimet laserit-käsitteen alle, koska laser = laserlaite.

**Comment by mariaforsen** [comment]
Vai äänentoistolaitteiden alle?
