### ISSUE TITLE
herpes

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11855]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[herpes](http://www.yso.fi/onto/yso/p11103)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käsitteen merkitystä tarkennettava tai jaettava useaksi eri käsitteeksi.

**Perustelut ehdotukselle**

Ongelma havaittu Wikidata-linkityksessä. Sanastossa on jo erikseen herpes simplex -virus ja herpesvirukset, joten tämän käsitteen merkitys on epäselvä. Herpes-virusten aiheuttamia tauteja on useita, kuten esim. MeSHistä ja Wikidatasta käy ilmi. Herpes simplex (https://www.wikidata.org/wiki/Q6473911) on virus ja infektio, joka voi ilmetä  huuliherpeksenä (https://www.wikidata.org/wiki/Q2364836) tai sukupuoliherpeksenä (https://www.wikidata.org/wiki/Q7476596). On myös olemassa koirien herpesrvirus (https://www.wikidata.org/wiki/Q1033307) ja Melinda-kuvailussa YSOn herpes-käsitettä on käytetty myös tässä merkityksessä. Lisäksi on herpes varicella zoster -virus, joka aiheuttaa vyöruusua (https://www.wikidata.org/wiki/Q6868). Pikaisesti ei selvinnyt, oliko herpes-käsitettä käytetty Melindassa myös tässä zoster-merkityksessä.

Ehdotus:
Poistetaan herpes-käsite ja otetaan tarvittaessa sanastoon em. tarkempia käsitteitä.

**Ehdottajan organisaatio**

Finto / Tuomas

**Comment by mirmaid** [comment]
Lääketieteen termit: herpes: rokahtuma | jonkin herpesviruksen aiheuttama iho- tai limakalvotauti, joka ilmenee ryhmissä sijaitsevina, kirkasta nestettä sisältävinä rakkuloina

Lääketieteen termit on perinteisesti ollut päälähde YSAn lääketietellisten termien osalta, joten luultavasti merkitys siis on ollut tuo "herpesvirusten aiheuttamat taudit".

Huuliherpes ei varmaan toimi, vaan otettava tämä laajempi (jos jaetaan): https://www.terveyskirjasto.fi/dlk00217

**Comment by mirmaid** [comment]
Herpesvirus 6 aiheuttaa puolestaan esim. _vauvarokkoa_, joka varmaan hyvä lisätä myös sanastoon.

Kerran aiheena Melindassa kissa, kerran poro. Näissä riittänee herpesvirukset tai 653-kenttä. Koirasta aineistoa on aika runsaasti, mutta niissäkin useimmiten pääasiana herpesvirukset.

**Comment by fantsby-m** [comment]
Voisiko muuttaa muotoon _herpesvirusinfektiot_, kuten MeSHissä. Ja yläkäsitteeksi sairaudet (nyt ihotaudit). Voivat olla muitakin kuin ihotauteja.

**Comment by FinMeSHienPaimentaja** [comment]
Infektion ja sairauden välille ei voi laittaa yhtäläisyysmerkkejä tässäkään tapauksessa - infektiosta voi tulla sairaus (hetimmiten tai myöhemmin elämässä), tai infektio voi jäädä vain infektioksi (tartunnaksi) ilman sairauden kehittymistä. (Eivät aina ole MeSH:eissäkään ja FinMeSH:eissäkään loogisesti nämä tällaiset).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _herpesvirusinfektiot_.

**Comment by mariaforsen** [comment]
Laitetaanko myös osa Meshin ohjaustermeistä, esim. herpesinfektiot?

Sv. herpes > herpesvirusinfektioner HT herpesinfektioner 
mesh: [Herpesviridaeinfektioner](https://finto.fi/mesh/fi/page/D006566?clang=sv)
https://www.vardhandboken.se/vardhygien-infektioner-och-smittspridning/infektioner-och-smittspridning/herpesinfektioner-vard-och-behandling/
https://roi.socialstyrelsen.se/fmb/herpesinfektioner/72
https://www.rvn.se/sv/delplatser/2022-mitt-lakemedel/mitt-lakemedel/behandlingsomraden/infektioner/herpesinfektioner/
https://www.vetenskaphalsa.se/sankt-tryck-kan-avvapna-herpesvirus/
