### ISSUE TITLE
androidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11866]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[androidit](http://www.yso.fi/onto/yso/p38190)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään KT-muodoksi humanoidirobotit (tai mahdollisesti päätermin vaihto)?

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Humanoidirobotti
LCSH:
androids http://id.loc.gov/authorities/subjects/sh85004921
Variants
    Humanoid robots
    Humanoids (Androids)

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Päätermin vaihto ehkä parempi, jos androidi on suppeampi?

**Comment by mariaforsen** [comment]
Sv. humanoida robotar  HT humanoider (robotar), humanoidrobotar, människoliknande robotar
https://termipankki.fi/tepa/fi/haku/humanoid
https://id.kb.se/term/sao/Androider
https://sv.wikipedia.org/wiki/Humanoid_robot
https://id.kb.se/term/sao/Robotar
https://www.abo.fi/nyheter/doktorsavhandling-om-anvandningen-av-humanoida-robotar-i-social-och-halsovarden/
https://it-ord.idg.se/category/robotar/androider-och-humanoider/
ne: humanoid

**Comment by YSO-kokous** [comment]
**Päätös**

Vaihdetaan päätermiksi _humanoidirobotit_.
