### ISSUE TITLE
soijapavut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11861]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[soijapavut](http://www.yso.fi/onto/yso/p21747)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan käsite. Tai tarkennetaan sen merkitystä jollakin konstilla.

**Perustelut ehdotukselle**

Tämä on YSOssa tarkoitettu taksonomiseksi käsitteeksi eli tarkoittaa Glycine-sukua, ei siis ruoan raaka-aineena käytettäviä papuja. Yläkäsitteenä YSOssa on hernekasvit. Käsitettä on kuitenkin kuvailussa käytetty tässä jälkimmäisessäkin merkityksessä eli väärin. YSOssa on myös käsite soijatuotteet.

Ks. esim.
https://melinda.kansalliskirjasto.fi/byid/013971338
https://melinda.kansalliskirjasto.fi/byid/013718254

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/11860

**Comment by tpalonen** [comment]
Yksi ratkaisu voisi olla:
_soijapapu/pavut_ KÄYTÄ _soijatuotteet_
_soijapapu/pavut_ KÄYTÄ _peltosoijapapu_

**Comment by mariaforsen** [comment]
Joko niin tai sitten tarkenteen lisäys: soijapavut (suku). Jos halutaan käyttää ratkaisuna poisto, niin sitten pitää olla varma ettei Melindassa ole käytetty kasvisuvusta.
https://laji.fi/taxon/MX.38969

**Comment by YSO-kokous** [comment]
**Päätös**

_Soijapapu_ muutetaan tarkoittamaan kasvia ja rehua. Ohjataan _soijasta_.

**Comment by mariaforsen** [comment]
Tarkoitus oli ymmärtääkseni poistaa "soijapavut" kasvisukuna, ja muuttaa peltosoijapapu > soijapapu
