### ISSUE TITLE
soija

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11860]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[soija](http://www.yso.fi/onto/yso/p12239)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan käsite.

**Perustelut ehdotukselle**

YSOssa on jo erikseen soijatuotteet, soijakastike sekä itse soijakasvia tarkoittava käsite peltosoijapapu. Soija-käsite tarkoittanee YSOssa näitä kaikkia, mutta koska ne ovat erillisiä käsitteitä, tätä käsitettä ei tarvittane.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/11861

**Comment by mirmaid** [comment]
Jos poistetaan, tarvitaan ohjaus soija-muodosta.

**Comment by YSO-kokous** [comment]
**Päätös**

Käsite soija poistetaan.

**Comment by ilona-x** [comment]
voisiko soijatuotteille lisätä ohjaustermiksi soijavalmisteet ja ehkä myös soijajalosteet?

Ja nyt soijatuotteiden yläkäsitteenä on tuotteet, mutta muut vastaavat ovat -valmisteet-loppuisia esim. liha- kala- ja sienivalmisteet ja ovat ruokavalmisteet-käsitteen alakäsitteitä, minne tämä soijatuotteetkin ehkä sopisi paremmin.
