### ISSUE TITLE
kaihtimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11881]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kaihtimet](http://www.yso.fi/onto/yso/p12282)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan käsitteen merkitys. Vaikuttaa muiden kielten termeihin ja linkitykseen.

**Perustelut ehdotukselle**

Viittaako käsite sälekaihtimiin vai muunkinlaisiin kaihtimiin? Tämä vaikuttaa linkitykseen ja muiden kielten termeihin. Kielitoimiston sanakirjan määritelmä: "vars. ikkunaan kiinnitetty erilaisin mekanismein liikuteltava verho. Rulla-, sälekaihdin." Voittopuolisesti sanaa kuitenkin varmastikin käytetään nykyisin sälekaihdin-merkityksessä. Ja rullakaihtimista käytetään nykyään useimmiten nimitystä rullaverho. Wikipedia-artikkelin nimi on Rullaverho, ei rullakaihdin. Rullakaihdin-haulla hs.fi:ssä tulee 2 tulosta, rullaverho-haulla 40 tulosta.

YSOssa on erikseen verhot.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Esim. käytetty Melindassa näistä 
https://www.tamar.fi/tuotteet/kaihtimet/screenkaihtimet/ 
https://ppkaihdin.fi/ppkaihdin/ 
https://visor.fi/collections/terassikaihtimet

**Comment by mirmaid** [comment]
Jos on rajattava pelkästään sälekaihtimiin, pitää otta ko. termi (aika niukasti aineistoja, joissa kyse on yksinomaan niistä), mutta jokin termi olisi kyllä tarpeen näille muille. Tai sitten yhdistetään verhot ja kaihtimet?

**Comment by mariaforsen** [comment]
Kannatan termiä sälekaihtimet=persienner. Ehkä verhot-termiä voi sitten käyttää kaikenlaisista muista verhoista.
https://fi.wikipedia.org/wiki/S%C3%A4lekaihdin
https://sv.wikipedia.org/wiki/Persienn

**Comment by mirmaid** [comment]
^ Vähän huonosti kyllä suomeksi, tai vaatii ainakin ohjauksen kaihtimet KÄ verhot. Esim. alhaalta ylöspäin nostettavaa terassikaihdinta ei ehkä ihan ajattelisi verhona.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan _verhot_ muotoon _verhot ja kaihtimet_, erikseen _sälekaihtimet_.

**Comment by mariaforsen** [comment]
Sv. -gardiner HT rullgardiner
https://www.sanakirja.fi/custom/en-sv-fi/kaihdin
-persienner HT spjälgardiner, jalusier
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_472a8136f259794f1626fec39a4526f5&list_id=1&keyword=s%C3%A4lekaihdin&word=s%C3%A4lekaihdin
https://svenska.se/tre/?sok=persienn&pz=1
https://svenska.se/tre/?sok=jalusi&pz=8
https://svenska.se/tre/?sok=spj%C3%A4lgardin&pz=1
https://www.sanakirja.fi/custom/en-sv-fi/s%C3%A4lekaihdin
https://sv.wikipedia.org/wiki/Persienn

**Comment by mirmaid** [comment]
Käydään vielä kuitenkin läpi kaihtimet-viitteet ja mietitään, onko mahdollista ratkaista tämä muuten kuin verhot-päätermin muutoksella. Jos päätermi muuttuu, myös hierarkia muutettava.

**Comment by mirmaid** [comment]
50 viitteestä 8 käsitteli varmuudella sälekaihtimia, loput 42 todennäköisesti tai varmasti myös muunlaisia kaihtimia. 

Saisiko mitään muuta yhdistelmää aikaan tuon verhot ja kaihtimet sijasta, esim. kaihtimet ja markiisit, niin että löytyisi ruotsiksi jokin vastine? Tässä hyvin nämä erilaiset kaihtimet: https://ppkaihdin.fi/ppkaihdin/palvelut/
Eng. varmaan "blinds"

**Comment by mariaforsen** [comment]
Sv. persienner och markiser? Pitääkö sisältää myös rullaverhoja?

**Comment by mirmaid** [comment]
Täällä on ehkä samaan tapaan ruotsiksi https://www.skanskabyggvaror.se/markiser/

Mietin voisiko olla jotain markiser och gardiner (solskydd) tai jos siitä voisi kehitellä jonkun paremman. Tietty muillakin verhoilla on se aurinkosuojafunktio, mutta ei ehkä niin keskeisenä. Mutta jos tämä ei onnistu niin sitten pitää vaan mennä tuolla verhot ja kaihtimet -yhdistelmällä suomeksi.

**Comment by mariaforsen** [comment]
Eli siis sälekaihtimet on miten vain jäämässä sanastoon? Entä eikö sitten markiisitkin voisi olla erikseen? Onko pelkkä "kaihtimet" oltava sanastossa? Taitaa sellaisenaan olla muutenkin hieman monimerkityksinen ja päällekkäinen sitten muiden termien kanssa. 
MOT Finnish: kaihdin
1 varjostava tai suojaava verho
Sälekaihdin.
2 varjostin
Lampun kaihdin.

**Comment by mirmaid** [comment]
^ Muut kaihtimet eivät ole suomeksi markiiseja, yritin hakea jotain sellaista, mikä ruotsiksi vastaisi suunnilleen sitä, mitä nimitetään suomeksi kaihtimiksi, ettei olisi tarvinnut kaikkia verhoja yhdistää tähän. Verhot kuitenkin suomeksi tarkoittaa yleensä kankaisia verhoja, joilla on vahvasti sisustuksellinen funktio, niin mietin olisiko _kaihtimet ja markiisit_ vähemmän tuskallinen ratkaisu kuin _verhot ja kaihtimet_. 

Jos kuitenkaan ei haluta eritellä, tekisin loppujen lopuksi ehkä ennemmin vain kaihtimet KÄ verhot, sälekaihtimet, kun tuntuisi ehkä paremmalta säilyttää tuo verhot-termi sellaisenaan. Noista screen-kaihtimista ja terassikaihtimista pitäisi vaan sitten käyttää termiä verhot, mutta ei kai se ihan mahdotonta ole.

**Comment by mariaforsen** [comment]
Kannatan ratkaisua kaihtimet KÄYTÄ verhot, sälekaihtimet

**Comment by YSO-kokous** [comment]
PÄÄTÖS
kaihtimet KÄYTÄ verhot
kaihtimet KÄYTÄ sälekaihtimet
