### ISSUE TITLE
joulumerkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#119]
#### Ehdotettu termi suomeksi

joulumerkit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)

**Luontipäivämäärä:** 01.07.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 113988

**Termiehdotus Fintossa:** [joulumerkit](http://finto.fi/yse/fi/page/Y313988)

**Comment by mirmaid** [comment]
Tarvittu kirjaan Joulumerkit - tuberkuloosia vastaan Suomessa 1908-1955

**Comment by ilona-x** [comment]
tällä näköjään kaksi merkitystä hyväntekeväisyysmerkit ja joulupostimerkit. 

Kielitoimiston sanakirja https://www.kielitoimistonsanakirja.fi/#/joulumerkki?searchMode=all
joulumerkki
joulun aikaisiin postilähetyksiin kiinnitettävä hyväntekeväisyysmerkki; myös jouluaiheisista postimerkeistä.

**Comment by mirmaid** [comment]
Sanastossa on muuten jo _joulumerkkikodit_.

https://kysymuseolta.fi/postimuseo/#!id=472

**Comment by YSO-kokous** [comment]
Joulumerkit (hyväntekeväisyysmerkit).

**Comment by mariaforsen** [comment]
Sv. julmärken (välgörenhetsmärken) HT välgörenhetsmärken, helgmärken
uppslagsverk/encyklopedi/lång/julfrimärke
https://tuberkuloosi.fi/se/tuberkuloosi-fi/julmarken/
https://www.brevporto.se/brevporto-julkort
https://www.alandpost.ax/om-aland-post/sponsring/julmarkesmedel
