### ISSUE TITLE
muoviveneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1190]
#### Ehdotettu termi suomeksi

muoviveneet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)
#### Lähde

Julkaisu: Kauhanen, I. Veneenrakentaja Eino Antinoja

**Luontipäivämäärä:** 15.10.2004

**Muokkauspäivämäärä:** 9.11.2004, 15.10.2004, 15.10.2004, 16.12.2008

**Voyager-id:** 133912

**Termiehdotus Fintossa:** [muoviveneet](http://finto.fi/yse/fi/page/Y333912)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
