### ISSUE TITLE
maissi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11907]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maissi](http://www.yso.fi/onto/yso/p4148)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi viljamaissi

**Perustelut ehdotukselle**

synonymi

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Laji.fi ja suomenkielinen Wikipedia mainitsevat viljamaissin maissin synonyymina.
https://laji.fi/taxon/MX.40666
https://fi.wikipedia.org/wiki/Maissi
