### ISSUE TITLE
Mannerheimintie (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11905]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mannerheimintie (Helsinki)](http://www.yso.fi/onto/yso/p163517)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään ohjaustermeiksi Mannerheimintien vanhat nimet: Heikinkatu, Läntinen ja Itäinen Henrikinkatu, Turuntie, Läntinen Viertotie

**Perustelut ehdotukselle**

tärkeät kyseisen tien historialliset nimet, joita löytyy paljon aineistosta

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermit:
Heikinkatu (Helsinki)
Läntinen Henrikinkatu
Itäinen Henrikinkatu
Turuntie (Helsinki)
Läntinen Viertotie
