### ISSUE TITLE
käädyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11908]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

käädyt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Käädyt = "kaulaketju, vars. jkn aseman virallisena symbolina" (https://www.kielitoimistonsanakirja.fi/käädyt)

**Perustelut ehdotukselle**

YSO:ssa ei ole sopivaa asiasanaa ennestään.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kaulakorut](http://www.yso.fi/onto/yso/p23319)

**Ehdotetut temaattiset ryhmät**

 [34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576), [94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Search/Results?lookfor=k%C3%A4%C3%A4dyt&type=AllFields + Melindassa useita tietueita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [käädyt](http://finto.fi/yse/fi/page/Y511908)

**Comment by mirmaid** [comment]
Mahtaako löytyä vastineita muilla kielillä? https://en.wikipedia.org/wiki/Livery_collar

Ja vaatisi ehkä tarkenteen suomeksi?

**Comment by AuHo22** [comment]
Voivat olla siis virkamerkkejä tai yleisemmin arvomerkkejä? käädyt (arvomerkit)?

**Comment by mirmaid** [comment]
Finnan kuvissa aika lailla ihan muitakin kaulakoruja. Kaipasikohan ehdottaja tätä nimenomaan arvoasemaan liittyvistä koruista vai yleisemmin...

**Comment by mariaforsen** [comment]
Voi olla hankala kääntää, onko siis kyseessä tämä https://en.wikipedia.org/wiki/Collar_(order) 
https://kaino.kotus.fi/finsk-svensk/?p=article&word=k%C3%A4%C3%A4dyt&suru_id=SURU_484d9da6a4cca148ece3f93d80092795
Kun määritelmä on "kaulaketju, vars. jkn aseman virallisena symbolina" niin voi vaatia tarkempaa määrittelyä käännöksen kannalta, pelkkä kaulaketjuna meillä on jo kaulakorut (näin ainakin ruotsiksi, halssmycke=halskedja)

**Comment by jarmosaarikko** [comment]
MAO/TAO http://www.yso.fi/onto/mao/p10118 **kaulaketjut**, chain necklaces  (KT neck chains.)
kielitoimiston mukaan tämä on synonyymi käädyille.
[Ritarikunnat](https://ritarikunnat.fi/kunniamerkit-rk/) sivustolta:  _"kunniamerkistä tulee erikoinen kunnianosoitus, jos se annetaan **ketjuineen**, jalokivineen, solkineen, tammenlehvineen jne."_
Ehdotus. Lisätään ohjaustermiksi käsitteelle "kaulaketjut".

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermiksi _kaulaketjuille_.
