### ISSUE TITLE
Kalevalan juhlavuosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11906]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kalevalan juhlavuosi](http://www.yso.fi/onto/yso/p13368)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSOssa on erikseen Kalevalan juhlavuosi ja Uuden Kalevalan juhlavuosi. Näihin kaipaisi määritelmää. Tarkoitetaanko niillä jotakin tiettyä vuotta kumpaisellakin vai juhlavuosia ylipäätään? 

**Perustelut ehdotukselle**

Kalevalan 1. painos (ns. Vanha Kalevala) ilmestyi v. 1835 ja toinen (laajennettu) painos (ns. Uusi Kaleva) v. 1849. Tuo jälkimmäinen on se, josta nykyisin puhutaan Kalevalana, Suomen kansalliseepoksena, ja josta esimerkiksi suurin osa Kalevan käännöksistä on tehty. 

Molempien painosten juhlavuosia on vietetty (mm. 1935 Kalevalan riemujuhla, 1949 Uuden Kalevalan 100-vuotisjuhla, 1985 Vanhan Kalevalan 150-vuotisjuhla, vuonna 1999 Kalevalan juhlavuosi).

Viittaavatko kaksi YSO-käsitettä erityisesti johonkin/joihinkin näistä vuosista vai voiko niitä käyttää mihin tahansa niistä? 

**Ehdottajan organisaatio**

SKS:n kirjasto

**Comment by AuHo22** [comment]
Juhlavuosista on keskusteltu toimijakuvailukokouksessa 10.1.2023 kenttään 111_2 lisättäviksi, ja toimijakuvailuohjeessa nyt esim.
NIMETYT JUHLAT, KANSALAISJUHLAT, VUOSIPÄIVÄT
111 2# ‡a Kalevalan juhlavuosi
111 2# ‡a Kalevalan riemuvuoden juhla ‡d (1935 : ‡c Helsinki, Suomi)

Kuuluuko ehdotus siis toimijakuvailuryhmälle ja millaista tarkkuutta sitten toivotaan, ovatko nuo vuosittain mainitut juhlat kaikki kuitenkin Kalevalan juhlavuosia eri nimekkeineen?

**Comment by mariaforsen** [comment]
Sv. on Kalevalas jubileumsår, siinä ei oteta kantaa mihinkään tietyn juhlavuoden suuntaan.

**Comment by krinay** [comment]
Olisiko yksinkertaisinta, että YSOssa olisi Kalevalan juhlavuosille vain yksi ikään kuin yleisniminen termi (monikossa?). Sitä voisi käyttää tarvittaessa yhdessä vuosiluvun kanssa. (Vai termiyhdistelmä: juhlavuodet + Kalevala + vuosiluku?)

Yksittäiset juhlavuodet, joiden taustalla on ollut suunnittelusta ja järjestelyistä vastaava organisaatio, sopisivat tosiaan KANTOon. Juhlavuosiahan on ollut edellä mainittujen lisäksi muitakin (viimeisimpänä muistaakseni Kalevalan 175-vuotisjuhlavuosi vuonna 2010) ja tulee varmaan jatkossa lisää. 

KANTOssa onkin jo _Kalevalan juhlavuosi_ ja _Uuden Kalevalan juhlavuosi_ sekä _Kalevalan juhlavuoden toimikunta_ ja _Uuden Kalevalan 150-vuotisjuhlavuoden työryhmä_, kaikki neljä ilman selityksiä tai tarkenteita.

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään seuraavaan kokoukseen.

**Comment by AuHo22** [comment]
Kantossa keskusteltu se, että Kalevalan juhlavuosia auktorisoidaan yksittäisinä juhlavuosina, tässä vaiheessa ainakin merkittävimmät juhlavuodet, eli 100- ja 150-vuotisjuhlavuodet, ja tarvittavia voi ehdottaa lisää:
https://www.kalevala175.net/juhlinta/
Ehdotetaan YSOon kokoavaa yleistermiä Kalevalan juhlavuodet

**Comment by YSO-kokous** [comment]
Muutetaan monikkoon.
