### ISSUE TITLE
rokot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11923]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rokot](http://www.yso.fi/onto/yso/p1319)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan käsitteen merkitystä. Tarkistetaan kielivastineet. Tautikategoriat rajautuvat eri kielissä eri tavoin.

**Perustelut ehdotukselle**

Saimme finto-palautetta virologian dosentilta.

"Rokkotauti" ei ole sama asia kuin poxvirus-diseases englanniksi tai koppor ruotsiksi. Rokko suomeksi tarkoittaa kaikkia virusten (ja erään bakteerin) aiheuttamia lasten ihottumatauteja, kun taas "Pox" on erään tietyn virusheimon nimi (Poxviridae), johon kuuluu mm. isorokko ja apinarokko. Sanaa "koppor"-sanaa käytetään ruotsiksi vain seuraavissa: smittkoppor, vattkoppor, svinkoppor (märkärupi) ja apkoppor (mpox). Sen sijaan tavallisimmat rokkotaudit, kuten esim. enterorokko, tuhkarokko, vihurirokko, tulirokko ja parvorokko eivät ole "koppor" ollenkaan, vaan höstblåsor, mässling, röda hund, scharlakansfeber ja femte sjukan (tai erythema infektiosum). Kun puhutaan vain “koppor”:ista niin silloin tarkoitetaan yleensä isorokkoa, joten väärin ymmärrys on vaarallista, sillä koppor on hengenvaarallinen tauti (isorokko), kun taas rokkotauti (yleensä) ei.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Lääketieteen termit: 2. pox (disease), koppor rokkotauti | eräitä tarttuvia iho-oireisia tauteja

https://www.terveyskirjasto.fi/dlk00602

Englanniksi parempi käännös olisi pox diseases, https://www.britannica.com/science/pox-disease. En osaa sanoa miten täydellinen vastaavuus näin saataisiin, mutta löytyy ainakin tekstejä, joissa tuhkarokko (measles) ja vihurirokko (rubella) sisällytetään pox diseases -ryhmään.

**Comment by mariaforsen** [comment]
Mihin tämä termi siis tarkaalleen viittaa suomeksi? Meshissä ei ole tällaista termiä, ja voi tosiaan olla mahdotonta saada täsmällinen vastine, ks. esim. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_e8c7c27435f1fa294e67a8d48d5393fe&list_id=1&keyword=rokkotauti&word=rokkotauti
Olisiko mahdollista luopua tästä? Kun kerta ei ole täsmällinen termi, ja ne oikeat taudit löytyvät erillisinä päätermeinä?

Tämäkin sivu vain suomeksi https://fi.wikipedia.org/wiki/Rokkotaudit

**Comment by ilona-x** [comment]
Rokot on käytetty Melindassa vain 56 kertaa, vaikka termi on ollut sanastossa vuodesta 1986.  Eli kannatan Marian ehdotusta poistamisesta, sillä on varmastikin korvattavissa joko *rokko-päätteisillä tarkemmilla termeillä tai tarvittaessa laajemmilla termeillä kuten esimerkiksi tartuntataudit tai virustaudit.

**Comment by YSO-kokous** [comment]
Poistetaan.
