### ISSUE TITLE
sähköajoneuvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11932]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähköajoneuvot](http://www.yso.fi/onto/yso/p27472)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

LCSH-linkkaus?

**Perustelut ehdotukselle**

Electric vehicles
http://id.loc.gov/authorities/subjects/sh85042036

**Ehdottajan organisaatio**

kk/il

**Comment by tpalonen** [comment]
Samalla voisi linkata tähän: https://www.wikidata.org/wiki/Q13629441

**Comment by tpalonen** [comment]
Toteutettu.
