### ISSUE TITLE
uudistava maaatalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11963]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

uudistava maaatalous

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

regenerative agriculture 

**Tarkoitusta täsmentävä selite**

Uudistava tai regeneratiivinen maatalous on vaihtoehtoinen lähestymistapa ruuantuotantoon. Siinä tavoitellaan luonnon ekosysteemejä jäljittelevää maatalousjärjestelmää, jossa tapahtuvat prosessit lisäävät systeemin kaikkien osapuolten elinvoimaisuutta. Tutkijat ja uudistavaa maataloutta edistävät tahot käyttävät määrittelyn lähtökohtina uudistavan maatalouden periaatteita ja käytäntöjä (mm. muokkauksen vähentäminen, kasvipeitteisyyden lisääminen, kerääjäkasvien käyttö, viljelykiertojen monipuolistaminen) tai hyötyjä (mm. ekosysteemin elpyminen, monimuotoisuuden lisääntyminen, vesitalouden parantuminen, vesistökuormituksen väheneminen, maan kasvukunnon parantuminen, hiilen varastoituminen) tai molempia.

**Perustelut ehdotukselle**

Tullut toistuvasti vastaan tarvetta termille. Kummallista ettei sitä ole ollenkaan sanastossa vielä. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [maatalous](http://www.yso.fi/onto/yso/p4503)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 regeneratiivinen maatalous

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Uudistava_maatalous)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tony Rinaudo: The forest underground : hope for a planet in crisis

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [uudistava maaatalous](http://finto.fi/yse/fi/page/Y511963)

**Comment by ilona-x** [comment]
ehdotettu edellisen kerran v. 2021: 
uudistava maatalous #9741

**Comment by AuHo22** [comment]
Myös seuraavassa termi uudistava viljely, raja kestävään maatalouteen on sen sijaan vaikeampi hahmottaa:

https://valtioneuvosto.fi/documents/1410837/178555033/Kest%C3%A4v%C3%A4+maatalous,+maaper%C3%A4n+hiilensidonta,+Liisa+Pietola.pdf/6e10dc2c-827b-163e-5f1e-12bb6e9292bb/Kest%C3%A4v%C3%A4+maatalous,+maaper%C3%A4n+hiilensidonta,+Liisa+Pietola.pdf?t=1695383479132

**Comment by mirmaid** [comment]
Regenerative agriculture is not a specific practice itself. Rather, proponents of regenerative agriculture use a variety of sustainable agriculture techniques in combination. https://en.wikipedia.org/wiki/Regenerative_agriculture

**Comment by mariaforsen** [comment]
Sv. regenerativt jordbruk, regenerativt lantbruk
https://www.regenerativtjordbruk.fi/
https://www.arla.se/artiklar/regenerativt-jordbruk/
https://www.sitra.fi/sv/projekt/grunderna-i-regenerativt-jordbruk/
https://www.ekolantbruk.se/nyheter/nytt-initiativ-ska-definiera-vad-regenerativt-lantbruk-innebar-under-nordiska-forhallanden

https://www.uudistavaviljely.fi/
https://www.bsag.fi/uudistava-viljely/
https://www.yara.fi/tietoa-yarasta/vastuullisuus/tavoitteemme/uudistava-viljely-on-osa-kannattavaa-kasvintuotantoa/
https://www.farmit.net/kasvinviljely/2020/12/09/regeneratiivinen-eli-uudistava-viljely-mita-se
https://www.maaseuduntulevaisuus.fi/maatalous/64e2ee20-44de-46f3-b994-c4ba1938273d

**Comment by tpalonen** [comment]
Aika paljonhan tätä jo näkyy esiintyvän. Kestävä maatalous on laajempi käsite kuin uudistava maatalous eli ottaisin uudistavan maatalouden tai uudistavan viljelyn omana käsitteenään mieluummin kuin ohjaustermiksi.
Ks. esim. tuo jo edelläkin linkattu: https://valtioneuvosto.fi/documents/1410837/178555033/Kest%C3%A4v%C3%A4+maatalous,+maaper%C3%A4n+hiilensidonta,+Liisa+Pietola.pdf/6e10dc2c-827b-163e-5f1e-12bb6e9292bb/Kest%C3%A4v%C3%A4+maatalous,+maaper%C3%A4n+hiilensidonta,+Liisa+Pietola.pdf?t=1695383479132

**Comment by mirmaid** [comment]
^ Katsoin kyllä tuota, mutta edelleen mielestäni ero kestävään maatalouteen jää epäselväksi. Jos tämä otetaan, niin ehkä kannattaisin ennemmin uudistava viljely tai uudistavat viljelymenetelmät, mutta silti toivoisin konkretiaa siihen, mitä tällä tarkalleen haetaan.

Jos esim. sanotaan, että "hyvän sadon lisäksi tavoitellaan maaperän kasvukunnon parantamista", niin tätä varmaan tavoitellaan kaikessa viljelyssä, koska hyvä sato ja maaperän kasvukunto väistämättä liittyvät yhteen. Esim. [täällä](https://www.yara.fi/tietoa-yarasta/vastuullisuus/tavoitteemme/uudistava-viljely-on-osa-kannattavaa-kasvintuotantoa/) kuvaus on hyvin abstrakti; "joukko tavoitteita ja toimenpiteitä", "jokaiselle hieman eri asioita". Jos selkeää määrittelyä ei löydy, saatetaan olla hetken päästä tilanteessa, jossa kysytään miksi meillä on kaksi termiä, joilla tarkoitetaan suunnilleen samaa, mutta joita käytetään kuvailussa epäjohdonmukaisesti.

**Comment by ilona-x** [comment]
**fi        uudistava maatalous**
sv       regenerativt jordbruk n (1)
en      regenerative agriculture (1)

määritelmä
maatalousjärjestelmä, jossa ruoantuotannon yhteydessä pyritään hillitsemään ilmastonmuutosta sekä parantamaan ympäristön tilaa jatkuvasti ja kokonaisvaltaisesti

huomautus
Uudistava maatalous pyrkii uudistamaan ja parantamaan maatalouden keskeisiä resursseja, kuten peltomaan kasvukuntoa, viljelijän taloutta sekä ihmisten ja eläinten hyvinvointia. Se on myös keino maataloudelle sopeutua ilmastonmuutoksen aiheuttamiin voimakkaasti vaihteleviin sääolosuhteisiin.
Uudistavassa maataloudessa käytetään uudistavan viljelyn menetelmiä. Menetelmiä sovelletaan tilannetajuisesti kunkin tilan olosuhteiden mukaan.
Uudistavaa maataloutta kutsutaan myös regeneratiiviseksi maataloudeksi.

definition
jordbrukssystem, vars syfte är att i samband med livsmedelsproduktionen stävja klimatförändringarna och förbättra miljöns tillstånd på ett kontinuerligt och helhetsmässigt sätt

anmärkning
Regenerativt jordbruk strävar efter att förnya och förbättra jordbrukets centrala resurser, såsom jordhälsa, jordbrukarens ekonomi och människors och djurs välbefinnande. Det är också ett sätt för jordbruket att anpassa sig till de stora variationerna i väderförhållandena som klimatförändringarna orsakar.
Inom regenerativt jordbruk används regenerativa odlingsmetoder. Metoderna anpassas enligt förhållandena på varje enskild gård.

Lähde: Uudistavan viljelyn sanasto (Baltic Sea Action Group, 2023) https://termipankki.fi/tepa/fi/haku/uudistava%20maatalous

---

**fi        uudistava viljely**
sv       regenerativ odling; regenerativt jordbruk n (2)
en      regenerative farming; regenerative agriculture (2)

määritelmä
viljelytapa, jolla pyritään ruoantuotannon yhteydessä parantamaan maaperän kasvukuntoa, vesiensuojelua ja maatalousekosysteemien tilaa jatkuvasti ja kokonaisvaltaisesti

huomautus
Uudistavassa viljelyssä hiiliviljely on keskeistä, mutta lisäksi uudistavalla viljelyllä on muitakin tavoitteita ja hyötyjä.
Uudistava viljely on monihyötyistä, koska se lisää satovarmuutta, tehostaa ravinteiden kierrätystä sekä parantaa pelto- ja vesiekosysteemien tilaa ja luonnon monimuotoisuutta.
Uudistavan viljelyn menetelmiä ovat muun muassa ympärivuotisen kasvipeitteisyyden lisääminen, maan muokkauksen minimointi, viljelykiertojen monipuolistaminen sekä tilannetajuinen laidunnus. Pellon toimiva vesitalous ja hyvä maan rakenne ovat uudistavan viljelyn perusta.
Uudistavasta viljelystä käytetään etenkin Suomen ulkopuolella ruotsiksi termiä regenerativt jordbruk ja englanniksi termiä regenerative agriculture. Suomessa kuitenkin tehdään ero uudistavan viljelyn ja maatalouden välille, jolloin uudistavasta viljelystä suositetaan käytettäväksi ruotsiksi termiä regenerativ odling ja englanniksi termiä regenerative farming.

definition
odlingssätt, vars syfte är att i samband med livsmedelsproduktionen förbättra jordhälsan, vattenskyddet och jordbruksekosystemens tillstånd på ett kontinuerligt och helhetsmässigt sätt

anmärkning
Kolinlagrande odling som bromsar klimatförändringarna är central i regenerativ odling, men regenerativ odling har också andra mål och fördelar.
Regenerativ odling är mångnyttigt, eftersom det ökar odlingssäkerheten, främjar återvinningen av näringsämnen samt förbättrar åker- och vattenekosystemens tillstånd och den biologiska mångfalden.
Regenerativa odlingsmetoder är bland annat att öka den växttäckta arealen året runt, minimera jordbearbetningen, diversifiera växtföljden och tillämpa adaptiv betesgång. En välfungerande vattenhushållning och en god markstruktur i åkrarna är grundläggande för regenerativ odling.
Särskilt utanför Finland benämns regenerativ odling på svenska med termen regenerativt jordbruk och på engelska med termen regenerative agriculture. I Finland gör man dock en distinktion mellan regenerativt jordbruk och regenerativ odling, varvid rekommendationen är att använda termen regenerativ odling på svenska och regenerative farming på engelska.

Lähde:  Uudistavan viljelyn sanasto (Baltic Sea Action Group, 2023) https://termipankki.fi/tepa/fi/haku/uudistava%20viljely

---

Käsitekaavio: Uudistava viljely.
Begreppsdiagram: Regenerativt odling.
Concept diagram: Regenerative farming.
![kuva](https://github.com/Finto-ehdotus/YSE/assets/21304210/c991ab9c-788f-4401-9e6c-58fb29a1861f)

Lähde: https://termipankki.fi/tepa/mot/mot.php?base=2&att=BSAG2023\uudistava_viljely.svg

**Comment by AuHo22** [comment]
Wikipedian englanninkielisessä artikkelissa tehdään eroa rinnakkaistermeihin, ja keskeisesti uudistava maatalous tuntuu rajautuvan uudistavaan viljelyyn siihen lisättynä sitten joitain kiertotalouden piirteitä, laajemmat määritelmät eivät sitten oikein enää poikkea kestävän maatalouden määritelmistä: https://en.wikipedia.org/wiki/Sustainable_agriculture

_Regenerative agriculture is a conservation and rehabilitation approach to food and farming systems. It focuses on topsoil, increasing biodiversity, improving the water cycle, enhancing ecosystem services, supporting biosequestration, increasing resilience to climate change, and strengthening the health and vitality of farm soil. Practices include, recycling as much farm waste as possible, and adding composted material from sources outside the farm._

**Comment by mirmaid** [comment]
Jos joku on jostain lähteestä onnistunut löytämään näiden kahden käsitteen eron, niin kopioikaa mielellään suoraan tähän. Kun mä en siis hahmota vieläkään mitä uudistava maatalous ihan konkreettisesti on, mikä ei sisältyisi myös kestävään maatalouteen - tai päinvastoin jos kestävä maatalous on yläkäsite, niin mikä osa siitä on uudistavaa maataloutta ja mikä on jotain muuta.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _uudistava viljely_.

**Comment by mariaforsen** [comment]
Sv. regenerativ odling HT regenerativt jordbruk
https://termipankki.fi/tepa/fi/haku/uudistava%20viljely
https://www.bsag.fi/sv/grunderna-i-regenerativt-jordbruk/
