### ISSUE TITLE
orkesterimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11993]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[orkesterimusiikki](http://www.yso.fi/onto/yso/p13806)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko orkesterimusiikki sama asia kuin symphonic music / musique symphonique / musica sinfonica? Liittyy Wikidata-linkitykseen ja ohjaustermeihin.

**Perustelut ehdotukselle**

Tässä kaivattaisiin Muusan asiantuntemusta. Voidaanko orkesterimusiikki linkittää tähän Wikidata-kohteeseen? https://www.wikidata.org/wiki/Q3328774
Ks. kohteeseen linkitetyt erikieliset Wikipedia-artikkelit, jotka löytyvät kyseisen sivun alalaidasta. Eri kielissä tässä kohteessa toistuu tuo sinfoniamusiikki-termi. Tarkoittaako orkesterimusiikki sinfoniaorkesterin soittamaa musiikkia? Onko sinfoniamusiikki sen synonyymi? Näin olin päättelevinäni yllä olevasta Wikidata-kohteesta.

Vai onko niin, että Wikidatassa on virheellisesti yhdistetty samaan kohteeseen (ja toisetensa vastineiksi) suomen orkesterimusiikki ja englannin symphonic music ja vastaavat?

LCSH on kyllä vetänyt yhtäläisyysmerkin heidän Orchestral music -asiasanansa ja tämän symphonic music Wikidata-kohteen välille, ks. http://id.loc.gov/authorities/subjects/sh85095326

Jos orkesterimusiikki ja sinfoniamusiikki ovat synonyymeja, pitäisikö sinfoniamusiikki ja muun kieliset vastineet lisätä tälle käsitteelle ohjaustermiksi?

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by jtuohini** [comment]
Pieni huomoi: ei niinkään "sinfoniamusiikki" kuin "sinfoninen musiikki". Ja tarkoittaa käytännössä samaa kuin "orkesterimusiikki".

Digistä löytyy "sinfoninen musiikki" -osumia noin 3 330 kpl aikaväliltä 1907–2021 ja näemmä kyllä "sinfoniamusiikki"-sanaa myös runsaasti eli 1 130 kpl aikaväliltä 1901–2021. Eli varmaan molemmat viittausmuodoksi?

**Comment by ilonahei** [comment]
On olemassa paljon orkesterimusiikkia, joka ei ole välttämättä sinfonista, esim. iso osa puhallinorkesterimusiikkia. LC:llä on termin Orchestral music alakäsitteenä Dance orchestra music, joka harvemmin lienee sinfonista.

**Comment by MUUSA-kokous** [comment]
Linkitys Wikidata-kohteeseen OK.
Ei tarvita uusia ohjaustermejä YSO-käsitteelle.

**Comment by jtuohini** [comment]
Nyt en ymmärrä Muusan päätöstä: jos asiasanan linkitys Wikidata-kohteeseen on ok, niin miksi Wikidatan sisältämät ohjaustermit eivät samalla olisi?

**Comment by YSO-kokous** [comment]
**Päätös**

Linkitys ok, ei ohjaustermien lisäystä.

**Comment by tpalonen** [comment]
Wikidata-linkitys toteutettu.
