### ISSUE TITLE
Pietarhovi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11999]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pietarhovi](http://www.yso.fi/onto/yso/p219178)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "Kuusoja"

**Perustelut ehdotukselle**

Ks. esim. http://wikimapia.org/119995/fi/Kuusoja, https://www.visit-plus.com/fi/node/222, http://www.inkeri.fi/virtuaali-inkeri/kylat-seurakunnittain/ jne. Ehkä nykyinen viittausmuoto "Kuusioja" on kirjoitusvirhe?

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Molempia muotoja esim. digitoiduissa lehdissä, Kuusioja lisäksi muuallakin (mm. wikipedia).
