### ISSUE TITLE
postkapitalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1199]
#### Ehdotettu termi suomeksi

postkapitalismi
#### Ehdotetut ohjaustermit

jälkikapitalismi
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)
#### Lähde

Lähde: Albert, M. Parecon : kapitalismin jälkeinen elämä

**Luontipäivämäärä:** 18.10.2004

**Muokkauspäivämäärä:** 18.10.2004, 16.12.2008

**Voyager-id:** 133925

**Termiehdotus Fintossa:** [postkapitalismi](http://finto.fi/yse/fi/page/Y333925)

**Comment by fantsby-m** [comment]
Tähän tarvittaisiin:
[For postcapitalist studies :inheriting futures of space and economy /Tuomo Alhojärvi](https://melinda.kansalliskirjasto.fi/byid/018110918)

**Comment by mirmaid** [comment]
Edellämainitun lisäksi 2 viitettä Melindassa. 

https://en.wikipedia.org/wiki/Post-capitalism
https://fi.wikipedia.org/wiki/J%C3%A4lkikapitalistinen_yhteiskunta

**Comment by mariaforsen** [comment]
Sv. postkapitalism HT postkapitalistiskt samhälle

**Comment by annamarj** [comment]
Kannattaisin toisinpäin: jälkikapitalismi (ihan käytetty termi) ja sille OT postkapitalismi.
https://fi.wikipedia.org/wiki/J%C3%A4lkikapitalistinen_yhteiskunta

**Comment by mirmaid** [comment]
Jälkikapitalismi KT postkapitalismi
