### ISSUE TITLE
varastointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11994]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[varastointi](http://www.yso.fi/onto/yso/p6576)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

onko tämän englanninkielinen vastine warehousinkg ok vai olisiko mahdollista vaihtaa termiksi storage? Storage nyt säilytyksen eng. vastineena

**Perustelut ehdotukselle**

tähän aina välillä törmää esim. energian ja lämmön varastointia käsittelevissä aineistoissa, joissa suomeksi ja ruotsiksi varastointi & lagring ovat ok, mutta englanniksi warehousing tuntuu hassulta

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/lagring

**Comment by tpalonen** [comment]
Joo, kuulostaa järkevältä. Vaikea kyllä keksiä mitään sulkutarkennetta jolla tämä varastointi/storage erotettaisiin tuosta säilytys/storagesta. Mutta onneksi englannin kohdalla ei olekaan ehdotonta vaatimusta sulkutarkenteista tällaisissa tapauksissa.

**Comment by tpalonen** [comment]
Muutettu
