### ISSUE TITLE
maalittaminen (sosiaalinen media)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11996]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maalittaminen (sosiaalinen media)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

online shaming?

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ei ole muita sopivia (tarkkoja) käsitteitä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kunnianloukkaus](http://www.yso.fi/onto/yso/p19569), [uhkailu](http://www.yso.fi/onto/yso/p22366), [sosiaalinen media](http://www.yso.fi/onto/yso/p20774)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Maalittaminen_(sosiaalinen_media))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tieto, valta ja vaikuttaminen oikeusvaltiossa / toimittaneet Niina Mäntylä, Jukka Viljanen & Laura Perttola.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [maalittaminen (sosiaalinen media)](http://finto.fi/yse/fi/page/Y511996)

**Comment by mirmaid** [comment]
Melindassa joitakin viitteitä (enemmän sotilaallisena terminä).

**Comment by mirmaid** [comment]
Online shaming on vastineena ehkä vähän epätarkka (?). https://intermin.fi/en/police/hate-crime/online-targeting, https://intermin.fi/sv/polisvasendet/hatbrott/riktade-trakasserier

Targeted harassment, https://www.riku.fi/en/various-crimes/maalittaminen/

**Comment by AuHo22** [comment]
Eihän tätä tapahdu ainoastaan sosiaalisessa mediassa - maalittaminen (häirintä) tms.?

**Comment by mariaforsen** [comment]
Sv. riktade trakasserier 

https://www.sanakirja.fi/custom/en-sv-fi/maalittaa
https://termipankki.fi/tepa/fi/haku/maalittaminen

 "Maalittaminen on ilmiö, jossa yksi tai useampi toimija kehottaa ja yllyttää suurta joukkoa hyökkäämään yhden ihmisen kimppuun eri tavoin, esimerkiksi lähettämällä vihaviestejä sähköpostilla tai sosiaalisessa mediassa" /https://intermin.fi/poliisiasiat/viharikollisuus/maalittaminen

https://www.riku.fi/sv/olika-brott/maalittaminen/

https://svenska.yle.fi/a/7-10040162

**Comment by tpalonen** [comment]
RT:ksi trollaus? joukkoistaminen? hybridivaikuttaminen? vihapuhe?

**Comment by AuHo22** [comment]
Kannatan trollaus ja vihapuhe RT:tä:

trollaus KT 
    nettihäiriköinti
    nettitrollaus
    provoilu
    trollaaminen
    verkkohäiriköinti
    verkkoprovosointi

vihapuhe 
KT verkkoviha

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _maalittaminen (häirintä)_.
