### ISSUE TITLE
Keltainen kirjasto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#11998]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Keltainen kirjasto](http://www.yso.fi/onto/yso/p18813)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan asiasanastosta

**Perustelut ehdotukselle**

Kyseessä on yksittäisen kirjasarjan nimi, joka sattuu vielä olemaan sama kaikilla kielillä. Toisin sanoen poistaminen ei vaikuta haettavuuteen, koska kyseisestä sarjasta on jo Teka-tietue ja tieto muutenkin (aiheena) kuuluu bib-tietueissa kenttään 630.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by fantsby-m** [comment]
Ei yhtään kertaa Melindassa
