### ISSUE TITLE
salonkikulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12003]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

salonkikulttuuri

**Ehdotettu termi ruotsiksi**

salongskultur

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kyseistä ilmiötä käsittelevän aineiston kuvailemiseen (YSO:ssa ei vanhastaan sopivaa asiasanaa; "kulttuurielämä" ja "kulttuurihistoria" turhan epätarkkoja).

**Ehdotettu yläkäsite YSOssa (LT)**

 [kulttuurielämä](http://www.yso.fi/onto/yso/p4023)

**Ehdotetut temaattiset ryhmät**

 [90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581), [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564), [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 salongit (kultttuurielämä), kirjalliset salongit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85116845)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/002107716, https://melinda.kansalliskirjasto.fi/byid/002134841, https://melinda.kansalliskirjasto.fi/byid/002293453 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [salonkikulttuuri](http://finto.fi/yse/fi/page/Y512003)

**Comment by lamminen** [comment]
Salongit, aikansa...  julkisuus tai tarkemmin: some/ lehdistö/ajatusten vaihtopaikka/ poliittisen vaikuttamisen, epävirallisen vaikuttamisen takahuoneita  - Salongin pitäjät aikansa "influenssereitä" myös naiset kuten "salonnière" Germaine de Staël - 

https://en.wikipedia.org/wiki/Germaine_de_Sta%C3%ABl

https://en.wikipedia.org/wiki/Salon_(gathering)#Salonni%C3%A8re

https://agricolaverkko.fi/review/perin-ranskalainen-ilmio-kirjalliset-salongit/
perustuu kirjaan: https://melinda.kansalliskirjasto.fi/byid/011115722

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

**Comment by jtuohini** [comment]
Lisäksi on tietueita, jotka tarvitsisivat kyseisen, mutta joista se puuttuu tai on korvattu muualla asiasanalla, ks. esim. https://melinda.kansalliskirjasto.fi/byid/013848819 ja https://melinda.kansalliskirjasto.fi/byid/006981452.

**Comment by AuHo22** [comment]
Voisi harkita KT seurapiirielämä (tämänkin kaltaista käsitettä on ajoittain tarvinnut, joskin voi ajatella hieman laajempana) tai sitten viittaukset päinvastoin
https://fi.wikipedia.org/wiki/Salonki

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Salongskultur

**Comment by mirmaid** [comment]
Meillä on nyt seuraelämä KÄ sosiaalinen elämä, aiemmin seuraelämä oli päätermi.

**Comment by jtuohini** [comment]
Salonkikulttuurille kuuluisi KT-muodoksi myös _musiikilliset salongit_ (ruots. _musiksalonger_, engl. _musical salons_). Salonkikulttuuri ja seurapiirielämä toki kietoutuvat yhteen, mutta siinä määrin eri ilmiöistä on kyse, että jälkimmäinen ainakaan ei voi olla edellisen KT-muotona.

**Comment by AuHo22** [comment]
Ymmärtänenkö oikein, että ehdottaja haluaa rajoittaa salonkikulttuurin tietyntyyppiseen aikakauteen (?) ja taide-elämään. Sitten on kuitenkin - kuten kuvataan - "poliittisia salonkeja" tai laajemmin seurapiirisalonkeja myöhemmälläkin ajalla, jotka lähenevät määritelmää, eli onko näitä hankala pitää erillään:

_[Hella Wuolijoki] piti vuosina 1918–1920 ”poliittista salonkia” Helsingin Eirassa Neitsytpolulla sijainneessa asunnossaan. Wuolijoen luona vieraili suuri määrä ulkomaiden diplomaatteja ja kansalaisia, englantilaisia upseereita sekä suomalaisia toisinajattelijoita kuten Eino Leino, Elli Tompuri, Väinö Tanner ja Hannes Ryömä._ https://fi.wikipedia.org/wiki/Hella_Wuolijoki

__Vuosina 1955–1965 Slioorin huoneisto toimi taiteilijoiden, diplomaattien, politiikan ja liike-elämän edustajien, älymystön sekä muiden seurapiirihenkilöiden kohtauspaikkana. Slioorin tuttavapiiriin kuuluivat muun muassa Pentti Saarikoski, Alpo Jaakola, Lauri Leppänen, George de Godzinsky, Kullervo Linna, Olavi Virta, Armo Hormia, Rakel Wihuri, Viktor Lebedev, Hertta Kuusinen ja Jussi Lappi-Seppälä._ https://fi.wikipedia.org/wiki/Tabe_Slioor

**Comment by AuHo22** [comment]
Salongit (seurapiirielämä)?

**Comment by LeKorsu** [comment]
Jos hyväksytään salongit (seurapiirielämä), pitäisikö myöskin olemassaolevaan salonkeihin laittaa tarkenne (tilat) tai (huoneet), että varmasti ymmärretään ero.

**Comment by AuHo22** [comment]
Saksan kansalliskirjastossa kaikki kolme käsitettä: **LT Salon** '(Definition: Ohne HZ verwendet für die regelmäßige Zusammenkunft eines intellektuellen Zirkels) **ST Literarischer Salon + Musikalischer Salon**
Salon
https://portal.dnb.de/opac/opacPresentation?cqlMode=true&reset=true&referrerPosition=1&referrerResultId=ubRef%3D041789652%26any&query=idn%3D041789652

Itse kaipaisin nimenomaan laajempaa termiä, koskapa salongeissa laajemminkin on käsitelty yhteiskunnallis-poliittisia kysymyksiä, myös historiassa yllä mainittu esimerkki Madame de Staël. Kuinka laajasti sitten voidaan ymmärtää esim. salongit (kulttuurielämä)? Eli ei liene mahdoton sekään.

**Comment by YSO-kokous** [comment]
**Päätös**

Tutkitaan seuraavaan kokoukseen mennessä nykyisen käsitteen _salongit_ käyttöä.

**Comment by mariaforsen** [comment]
Sv. salong on monimerkityksinen termi: https://svenska.se/tre/?sok=salong&pz=1
SAOssa on Musikaliska salonger, Litterära salonger ja Salongskultur 

Melindassa 38 kertaa, näyttää liittyvän läheisesti salonkikulttuuriin.

**Comment by mirmaid** [comment]
Yhtä lukuunottamatta kaikki liittyvät salonkikulttuuriin, yhdessä kyse muotisalongista. Pitäisikö muuttaa salongit > salonkikulttuuri?

**Comment by YSO-kokous** [comment]
Muutetaan > salonkikulttuuri.

**Comment by mariaforsen** [comment]
Sv. salongskultur
