### ISSUE TITLE
Lempaala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12000]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lempaala](http://www.yso.fi/onto/yso/p176822)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Miksi LT-muotona ei ole Ruotsi? Miksi englanninkielinen vastine on aivan muuta kuin paikannimi?

**Perustelut ehdotukselle**

Jos Lempaala on hierarkkiassa kahden eri aikaan olleen valtion alla, niin olisi asiallista huomioida myös aiempi valtiollinen yhteys eli Ruotsi. Englanninkielisen vastineen soisi myös myös olevan linjassa eli puhdas paikannimi. Lempaala on kaiken lisäksi määritelty seurakunnaksi, ja jos kyse tässä on sellaisesta, kuuluisi termi kaikkiaankin Kantoon.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
^ Venäjä/Neuvostoliitto -tuplahierarkia on YSO-paikoissa vanhaa perua, mutta on kyllä tarkoitus ratkaista tilanne nykyistä paremmalla tavalla. Monien muitten kysymysten ohella se on odottanut uutta paikkojen tietomallia, jota jo useampi ryhmä on yrittänyt työstää. Tässä vaiheessa sanoisin kuitenkin, että hierarkian muodostaminen nykytilanteen perusteella on todennäköisemmin toimiva ratkaisu kuin kaikkien entisten kytkösten ylläpitäminen (varsinkaan maailmanlaajuisesti).

**Comment by YSO-kokous** [comment]
Muutetaan huomautusta muotoon "Entisen seurakunnan alue Pohjois-Inkerissä..."
