### ISSUE TITLE
transnationaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12004]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[transnationaalisuus](http://www.yso.fi/onto/yso/p21700)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Varsinaiseksi asiasanaksi ylirajaisuus? (Eli päätermi ja ohjaustermi vaihtaisivat paikkaa.)

**Perustelut ehdotukselle**

Ylirajaisuus näyttää vakiintuneen suomenkielisessä tutkimuksessa käytetyksi termiksi.  Tämän voi todeta selaamalla Melindassa suomenkielistä aineistoa, joka on kuvailtu YSOn termillä transnationaalisuus.

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan muotoon _ylirajaisuus_.
