### ISSUE TITLE
kaksisuuntainen lataus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12008]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaksisuuntainen lataus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

bidirectional charging

**Tarkoitusta täsmentävä selite**

Tekniikka, jossa sähköajoneuvon akkuun varastoitua energiaa voidaan syöttää myös (rakennuksen) sähköverkkoon päin. 

**Perustelut ehdotukselle**

Lähivuosina yleistyvä tekniikka, on jo käytössä mutta kallis. Hyvä saada sanastoon niin tätä koskevat lehtijutut, kuvat ym. saadaan katalookiin oikein.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sähköautojen latauspisteet](http://www.yso.fi/onto/yso/p39562)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 kaksisuuntainen tehonsiirto, V2G (vehicle-to-grid), V2H (vehicle-to-home)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [älykkäät sähköverkot](http://www.yso.fi/onto/yso/p29493)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Kaksisuuntainen_lataus)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. tämä
http://sahkotelelehti.fi/lehdet/st52022/#/article/8/page/1-1

Myös reseach.fi:stä löytyy paljon kamaa hakusanalla V2G

**Ehdottajan organisaatio**

SESKO SK 69 (olen komitean sihteeri, en SESKOlla töissä)
**Termiehdotus Fintossa:** [kaksisuuntainen lataus](http://finto.fi/yse/fi/page/Y512008)

**Comment by mirmaid** [comment]
Ei Melindassa, mutta lienee kyllä ajan kysymys.

**Comment by AuHo22** [comment]
Kaipaisin termiehdotuksiin -tekniikka-sanan lisäämistä, po. kaksisuuntainen lataustekniikka / V2G-tekniikka, esim.
https://nordicplug.fi/blogs/sahkoautot-ja-lataaminen-blogi/kaksisuuntainen-lataus-v2g

**Comment by linjaaho** [comment]
En ainakaan pahasti vastusta jos siihen lisätään tekniikka (tein alkuperäisen ehdotuksen). Toisaalta nopea googlaus näyttää että termiä "kaksisuuntainan lataus" käytetään aika yleisesti, ja se on päätynyt myös IATEen:
https://termipankki.fi/tepa/fi/haku/kaksisuuntainen%20lataus

**Comment by AuHo22** [comment]
YSO kun on yleissanasto, niin kaikenlaisia assosiaatioita voi syntyä termistä jos toisesta, ja itselleni pakosti tuli mieleen ensimmäiseksi kaksisuuntainen mielialahäiriö (huonommin teknisiä aloja hallitsevana), ja latauksesta vielä sähköhoito jota voidaan käyttää myös ko. sairauden hoitamiseksi. Eli näistä syistä ehdotin viittausta ja selkeytystä tekniikan alaan...

**Comment by mariaforsen** [comment]
Sv. dubbelriktad laddning HT tvåvägsladdning, V2G
https://termipankki.fi/tepa/fi/haku/kaksisuuntainen%20lataus
https://laddboxbolaget.se/allt-om-v2g/
Ruotsiksi ei -tekniikkaa, kun sitä ei käytetä ja termi on sellaisenaan selkeä.

**Comment by mirmaid** [comment]
_Lataus_-käsite saattaa kaivata toimenpiteitä...🤔

**Comment by AuHo22** [comment]
https://www.kielitoimistonsanakirja.fi/#/lataamo

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
