### ISSUE TITLE
arvostelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12001]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[arvostelut](http://www.yso.fi/onto/yso/p6612)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM-käsite ravintola-arvostelut : uudeksi ohjaustermiksi ravintola-arviot

**Perustelut ehdotukselle**

Synonymi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Hyväksytty, myös muut vastaavat /SLM.

**Comment by mirmaid** [comment]
YSO?
