### ISSUE TITLE
vihreät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12007]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vihreät](http://www.yso.fi/onto/yso/p14162)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan käytettävä termi muotoon vihreät puolueet. Lisätään ohjaustermiksi ympäristöpuolueet.

**Perustelut ehdotukselle**

Nykyinen päätermi "vihreät" voi antaa kuvan, että tämä viittaa ainoastaan Suomen Vihreään liittoon, jonka lyhyempi nimimuoto on Vihreät (ks. esim. puolueen logo). Vihreät puolueet olisi selkeämpi.

Ympäristöpuolue-termiä käytetään usein Suomen Vihreistä ja Ruotsissa toimii puolue, jonka virallinen nimi on Ympäristöpuolue Vihreät. Wikipediassa artikkelin nimi on Ympäristöpuolueet, ei Vihreät puolueet tms. https://fi.wikipedia.org/wiki/Ymp%C3%A4rist%C3%B6puolue

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Sv. gröna partier 
Myös SAOssa https://id.kb.se/term/sao/Gr%C3%B6na%20partier
https://sv.wikipedia.org/wiki/Gr%C3%B6na_partier

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan muotoon _vihreät puolueet_.
