### ISSUE TITLE
raja-arvot (rajoitukset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12005]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[raja-arvot (rajoitukset)](http://www.yso.fi/onto/yso/p11977)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan sulkutarkennetta (En nyt vaan keksi mikä se voisi olla.)

**Perustelut ehdotukselle**

Jos tällä on tarkoitus viitata pitoisuuksien tms. raja-arvoon (viite-arvoon?), kuten assosiatiivinen käsite viittaisi, sulkutarkenne on vähän huono. 

**Ehdottajan organisaatio**

KK/HR

**Comment by AuHo22** [comment]
raja-arvot (mittaukset)? raja-arvo (matematiikka) on jo YSOssa

**Comment by mirmaid** [comment]
Viitearvot on sanastossa erikseen = jnk suureen arvoja, jotka on mitattu tietystä populaatiosta ja joiden avulla määritellään kyseisen suureen viiteraja(t) (Kielitoimiston sanakirja).

Raja-arvot = jnk suureen ylin t. alin arvo (esim. melun, kemiallisen altistuksen tms. suurin sallittu arvo)

Rajoitukset on kyllä tarkenteena tosi kömpelö, mutta sillä on haettu mielestäni eroa juuri tuohon viitearvot-käsitteeseen.

**Comment by FinMeSHienPaimentaja** [comment]
raja-arvot (pitoisuus) tms.?

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
