### ISSUE TITLE
nauhakeraaminen kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12010]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nauhakeraaminen kulttuuri

**Ehdotettu termi ruotsiksi**

Bandkeramisk kultur

**Ehdotettu termi englanniksi**

Bandkeramik culture

**Tarkoitusta täsmentävä selite**

Nauhakeraaminen kulttuuri oli kivikautinen maanviljelykulttuuri Keski-Euroopassa  c. 5500–4500 eaa (wikipedia)

**Perustelut ehdotukselle**

tarvitaan kirjastoaineiston kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kivikautiset kulttuurit](http://www.yso.fi/onto/yso/p4740)

**Ehdotetut temaattiset ryhmät**

 [51 Arkeologia](http://www.yso.fi/onto/yso/p26593)

**Vaihtoehtoiset termit**

 Linear Pottery culture, Linear Band Ware

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [sao](https://id.kb.se/find?q=bandkeramisk), [LCSH](https://id.loc.gov/search/?q=linear+pottery&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects), [MAO](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp6576), [wikipedia](https://fi.wikipedia.org/wiki/Nauhakeraaminen_kulttuuri)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9934508231206253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [nauhakeraaminen kulttuuri](http://finto.fi/yse/fi/page/Y512010)

**Comment by mirmaid** [comment]
Sanastossa on _nuorakeraaminen kulttuuri_, KT vasarakirveskulttuuri. Nämä ovat eri kulttuureja, mutta nimissä on ehkä sen verran sekaantumisen riski, että ainakin huomautus tai määritelmä olisi varmaan hyödyllinen.

**Comment by mirmaid** [comment]
16 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. bandkeramisk kultur HT bandkeramiska kulturen

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
