### ISSUE TITLE
maapolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12015]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maapolitiikka](http://www.yso.fi/onto/yso/p8272)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng. ohjaustermiksi land policy?

**Perustelut ehdotukselle**

MOT-sanakirja

**Ehdottajan organisaatio**

kk/il

**Comment by fantsby-m** [comment]
Näyttää olevan tässä käytössä mm. Helsingin kaupungilla ja kansainvälisestikin.
Esim.
https://www.hel.fi/en/urban-environment-and-traffic/plots-and-building-permits/applying-for-a-plot/land-policy-guidelines-and-statistics
https://gltn.net/land-policy-and-legislation/
