### ISSUE TITLE
ilmoittajansuojelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12016]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ilmoittajansuojelu

**Ehdotettu termi ruotsiksi**

visselblåsning

**Ehdotettu termi englanniksi**

whistleblowing

**Tarkoitusta täsmentävä selite**

Saimme finto-palautetta:

Hej, Det har kommit en ny lag som kallas "Visselblåsarlagen" https://www.finlex.fi/sv/laki/alkup/2022/20221171 Jag saknar ordet 'visselblåsare' och eventuellt (om passligt) 'visselblåsarlagen'

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

finto-palaute
**Termiehdotus Fintossa:** [ilmoittajansuojelu](http://finto.fi/yse/fi/page/Y512016)

**Comment by mirmaid** [comment]
https://vm.fi/ilmoittajansuojelu, sv. visselblåsarskyd, en. whistleblower protection

Ei Melindassa.

**Comment by fantsby-m** [comment]
Laki on tullut voimaan 2023 alusta ja sen perusteella yli 50 työntekijän organisaatioiden on viimeistään 17.12. otettava käyttöön sisäinen ilmoituskanava väärinkäytöksistä. Lienee oletettavissa että tuosta tulee aineistoa varsin nopeasti. Koskee melkoista määrää organisaatioita (mainittu laki 10 §):

> 1. lailla tai valtioneuvoston asetuksella perustetut valtion hallintoviranomaiset sekä muut valtion virastot ja laitokset, valtioneuvoston kanslia, ministeriöt, eduskunnan kanslia ja eduskunnan yhteydessä tai valvonnassa toimivat virastot ja laitokset, tasavallan presidentin kanslia, tuomioistuimet, valtion liikelaitokset ja itsenäiset julkisoikeudelliset laitokset;
> 2. hyvinvointialueet ja hyvinvointiyhtymät;
> 3. kunnat, kuntayhtymät, liikelaitoskuntayhtymät ja kunnalliset liikelaitokset;
> 4. seurakunnat ja seurakuntayhtymät, tuomiokapitulit, kirkkohallitus ja kirkollishallitus;
> 5. kaupparekisterilain (129/1979) 3 §:n 1 momentin 1, 2 ja 4–6 kohdassa tarkoitetut yhteisöt; sekä
> 6. säätiölaissa (487/2015) tarkoitetut säätiöt, eläkelaitokset, vakuutuskassat ja työttömyyskassat.

**Comment by mariaforsen** [comment]
Mitä tässä oikeastaan on toivottu?

Visselblåsare = [väärinkäytösten paljastaja](https://www.sanakirja.fi/custom/en-sv-fi/v%C3%A4%C3%A4rink%C3%A4yt%C3%B6sten%20paljastaja) ?

"Visselblåsarlagen"=Lag om skydd för personer som rapporterar om överträdelser av EU-rätten och den nationella lagstiftningen = fi. Euroopan unionin ja kansallisen oikeuden rikkomisesta ilmoittavien henkilöiden suojelusta

Visselblåsning = fi. väärinkäytöksen paljastaminen (TEPAssa suositeltava), väärinkäytöksestä ilmoittaminen..? 
https://www.sanakirja.fi/custom/en-sv-fi/visselbl%C3%A5sning
https://termipankki.fi/tepa/fi/haku/visselbl%C3%A5sning

Ilmoittajansuojelu = sv. visselblåsarskydd 
https://valvira.fi/sv/visselblasarskyddet
https://raja.fi/sv/visselblasarskydd
https://um.fi/visselblasarskydd
https://oikeuskansleri.fi/sv/visselblasarskydd
https://oikeus.fi/tuomioistuimet/sv/index/domstolsvasendet/ansvarsfullhet/visselblasarskydd.html

Varmaan ainakin viimeisin mainittu pitäisi hyväksyä sanastoon, viranomaisten ahkerassa käytössä kun on.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
