### ISSUE TITLE
kulttuuriosaaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12013]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kulttuuriosaaminen](http://www.yso.fi/onto/yso/p8342)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi kulttuurinen osaaminen?

**Perustelut ehdotukselle**

termimuoto tuli vastaan julkaisussa "Kulttuurista osaamista sosiaali- ja terveysalalle Pohjois-Suomesta"

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
https://thl.fi/fi/web/maahanmuutto-ja-kulttuurinen-moninaisuus/tyon-tueksi/hyvia-kaytantoja/kulttuurisensitiivinen-tyoote

Sv. HT kulturell kompetens
