### ISSUE TITLE
palo-osastointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12014]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

palo-osastointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarpeellinen asiasana rakentamisen ja paloturvallisuuden aloille. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Rakenteellinen paloturvallisuus (ril-julkaisut)
esimerkiksi https://finna.fi/Record/3amk.297699?sid=3115631910

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [palo-osastointi](http://finto.fi/yse/fi/page/Y512014)

**Comment by mirmaid** [comment]
9 viitettä Melindassa. 

_Rakennusmääräysten mukaan rakennus tulee jakaa palo-osastoihin. Esimerkiksi kerrostalossa jokainen asunto muodostaa oman palo-osastonsa. Osastoinnin tarkoituksena on estää palon ja haitallisten savukaasujen leviäminen palo-osastosta toiseen._

**Comment by ilona-x** [comment]
LIIKO: palo-osastot http://www.yso.fi/onto/mero/m8925

--

Tepa:
https://termipankki.fi/tepa/fi/haku/palo-osastointi
https://termipankki.fi/tepa/fi/haku/palo-osasto

**Comment by mariaforsen** [comment]
Sv. brandsektionering /fler träffar HT brandteknisk sektionering /finlex, brandcellsindelning
https://www.finlex.fi/sv/laki/alkup/2017/20170848
https://termipankki.fi/tepa/fi/haku/brandsektionering
https://sv.wiktionary.org/wiki/brandsektionering
https://www.rikstermbanken.se/search?q=brandteknisk+sektionering&s=termer

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _palo-osastointi_.
