### ISSUE TITLE
Pohjoismaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12021]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pohjoismaat](http://www.yso.fi/onto/yso/p94350)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Erotetaan Skandinavia omaksi käsitteekseen.  
"Pohjois-Euroopan alue, joka käsittää Ruotsin ja Norjan, usein myös Tanskan."@fi 
"Geografiskt område i norra Europa som omfattar Danmark, Norge och Sverige."@sv
"Subregion in Northern Europe, which most commonly refers to Denmark, Norway, and Sweden. "@en

**Perustelut ehdotukselle**

Skandinavia on tällä hetkellä merkitty Pohjoismaat-käsitteen ohjaustermiksi. 

Suomi ei kuulu Skandinaviaan.  Skandinavia on osa Fennoskandiaa, mutta Islanti ei kuulu kumpaankaan. Suomi ja Islanti kuuluvat Pohjoismaihin.
Sama virhe toistuu LCSH:ssa. (sh85117937) Wikidatassa näyttäisi olevan "oikein".

YSO-paikoissa pitäisi olle neljä erillistä paikkakäsitettä:

1) Skandinavia, jossa vain  Tanska, Norja, Ruotsi (3 maata)  
     - maantieteellinen alue  (Wikidata: Q21195)
     - Skandinavia   :partOf Fennoskandia.
     - vrt. Skandinavian niemimaa (Skandit)  - vain Ruotsi ja Norja!  (wd:Q73169)

2) Fennoskandia on  Skandinavia+Suomi(+Karjala+Kuolan niemimaa)
    - (4 maata) maantieteellinen ja geologinen alue (wd: Q604496)
    - http://www.yso.fi/onto/yso/p124012 
    - YSO-paikkojen mukaan Tanska ei kuulu Fennoskandiaan

3) Baltoskandia on Fennoskandia+Viro+Latvia+Liettua
    - (7 maata) maantieteellinen alue  (wd: Q3735991)

4) Pohjoismaat (Pohjola, Norden, Nordic countries) on Tanska+Norja+Ruotsi+Suomi+Islanti
     - (5 maata)  poliittiinen alue  (wd: Q52062) 
     - http://www.yso.fi/onto/yso/p94350

Valtioden listasta näkyy, että nämä ovat päällekkäisiä, mutta eri käsitteitä, joita olisi syytä erottaa toisistaan.  Voisi luoda myös uuden käsitteen "Baltoskandia".

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by ilona-x** [comment]
aiempi ehdotus https://github.com/Finto-ehdotus/YSE/issues/10827

**Comment by mirmaid** [comment]
Aiempi issue on juuri käsitelty ja perustelut päätökselle kirjattu siihen. Tilanne ei varmasti ole niiden osalta muuttunut.

**Comment by YSO-kokous** [comment]
Palataan asiaan, jos Kongressin kirjasto muuttaa omaa ratkaisuaan.
