### ISSUE TITLE
testosteroni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12020]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[testosteroni](http://www.yso.fi/onto/yso/p23240)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pohjoissaamenkieliseksi vaihtoehtotermiksi testosterona (myös muut vastaavat -oni-loppuiset termit; pitäisi olla sekä -ovdna että -ona pohjoissaameksi)

**Perustelut ehdotukselle**

Testosterona myös käytössä ja molemmin puolin valtiorajaa, mm. https://www.hyvakysymys.fi/uploads/2018/10/422e2bc3-pohjoissaame-seksuaalisuuden-sanakirja_final_28.10.2019.pdf, https://tjenester.helsenorge.no/samvalg/prostatakreft-med-spredning/hormonhemmende-tabletter-prostatakreft-med-spredning?languageCode=se, https://satni.uit.no/termwiki/index.php?title=Medisiidna:dievdohormona

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by nikopartanen** [comment]
Palaute otetaan huomioon työn edetessä ja sitä dokumentoitaessa. Kiitos!
