### ISSUE TITLE
SLM: taulukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12027]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM: taulukot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

tables of squares

**Tarkoitusta täsmentävä selite**

SLM-ehdotus.

**Perustelut ehdotukselle**

Pienpainatekokoelmassa usein erillinen julkaisu eikä mikään liite. Yksilöi aineiston yksiselitteisesti. Termiä on hankala korvata millään muulla genretermillä ja asiasanalla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [yhteiskunnalliset objektit](http://www.yso.fi/onto/yso/p605)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556), [04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAOGF](https://id.kb.se/term/saogf/Tabeller)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston pienpainatekokoelman takautuva kuvailu arkistojärjestelmään, esim. https://www.doria.fi/handle/10024/87268

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen

**Comment by mariaforsen** [comment]
Sv. tabeller
https://id.kb.se/term/saogf/Tabeller
https://termipankki.fi/tepa/fi/haku/taulukko

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

taulukot (tilastot) KÄ tilastot
