### ISSUE TITLE
SLM: säännöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12025]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM: säännöt

**Ehdotettu termi ruotsiksi**

stadgar

**Ehdotettu termi englanniksi**

bylaws?

**Tarkoitusta täsmentävä selite**

SLM-termi. Tämä on hankala, koska tarvitsisimme laajan SLM-termin 'säännöt', sv. 'regler'. Suurin osa pienpainatekokoelman säännöistä on kuitenkin yhdistysten ja muiden organisaatioiden sääntöjä, sv. 'stadgar'. 

**Perustelut ehdotukselle**

Sääntökirjasia on runsaasti pienpainatekokoelmassa, ja termi on hankalasti korvattavissa genretermillä + asiasanalla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [yhteiskunnalliset objektit](http://www.yso.fi/onto/yso/p605)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

 regler

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAOGF](https://id.kb.se/term/saogf/Stadgar), [MeSH/SweMeSH](https://finto.fi/mesh/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmesh%2FD003249&clang=sv)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskokoelman pienpainateaineiston kuvailu arkistojärjestelmään, esim. Suomen naisyhdistyksen säännöt: https://www.doria.fi/handle/10024/84238 ja https://www.doria.fi/handle/10024/84233

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen

**Comment by mariaforsen** [comment]
Eli tarvitaanko tässä jonkinlaista sulkutarkenne-ratkaisua?

YSOn puolella säännöt on tietysti =sv. regler, mutta tämä tarve on sen verran spesifinen, ettei varmaan voida ratkaista samalla tavalla. 

https://termipankki.fi/tepa/fi/haku/stadga
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_593902b14caca1232c70516c4ea24d58&list_id=1&keyword=s%C3%A4%C3%A4nt%C3%B6&word=s%C3%A4%C3%A4nt%C3%B6
https://forening.se/bilda/stadgar/
https://www.rikstermbanken.se/search?q=stadgar&s=termer
https://sv.wikipedia.org/wiki/Stadgar

**Comment by mirmaid** [comment]
Hyväksytty muodossa järjestöjen säännöt KT säännöt (järjestöt), yhdistysten säännöt, seurojen säännöt
