### ISSUE TITLE
SLM: aikataulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12023]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM: aikataulut

**Ehdotettu termi ruotsiksi**

SLM: tidtabeller

**Ehdotettu termi englanniksi**

timetables

**Tarkoitusta täsmentävä selite**

SLM-termiehdotus

**Perustelut ehdotukselle**

Aikataulut on mielestäni yksiselitteinen ja selkeä SLM-käsite,  hankalasti korvattavissa genretermillä + asiasanalla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [yhteiskunnalliset objektit](http://www.yso.fi/onto/yso/p605)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAOGF](https://id.kb.se/term/saogf/Tidtabeller), [LCSH](https://id.loc.gov/authorities/subjects/sh89002894.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kansalliskirjaston pienpainatekokoelman takautuva kuvailu arkistojärjestelmään, esim. https://digi.kansalliskirjasto.fi/aikakausi/binding/869711?page=17

**Ehdottajan organisaatio**

Kansalliskirjasto / Johanna Jääskeläinen

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
