### ISSUE TITLE
ääniteknikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12024]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ääniteknikot](http://www.yso.fi/onto/yso/p27529)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään ohjaustermiksi äänitarkkailijat.

**Perustelut ehdotukselle**

Äänitarkkailija on käytössä oleva ammattinimeke. Meinasin tehdä uuden käsite-ehdotuksen kun en löytänyt äänitarkkailijaa, mutta sitten löysin ääniteknikot ruotsinkielisen ljudteknikerin avulla.

**Ehdottajan organisaatio**

Yle Arkisto

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
