### ISSUE TITLE
peura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12031]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[peura](http://www.yso.fi/onto/yso/p27948)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne, määritelmä tms. 

**Perustelut ehdotukselle**

Tarkoitus on ollut varmaan viitata tähän: https://laji.fi/taxon/MX.47636 (ks. myös alemmat taksonit). Ainakin sv. on ollut ren (vild). Nyt käytetty Melindassa kuitenkin "mistä tahansa" peurasta, esim:
-Hirvieläinonnettomuuksien vähentäminen kantatiellä 54 välillä Vojakkala-Riihimäki, esiselvitys : Loppi, Riihimäki / Laura Soosalu, Antti Udd, Kari Lehto
-Uudenmaan ELY-keskuksen alueellinen hirvieläinvaaraselvitys 2019 / Laura Soosalu, Antti Udd, Nina Lindroos, Janne Pakarinen.
-Deer and people / edited by Karis Baker, Ruth Carden, and Richard Madgwick.
-Talvi houkuttelee arat peurat pihoihin ja puutarhoihin.
-Suuri riista- ja kalakeittokirja / Clarissa Dickson Wright ja Johnny Scott ; ruokavalokuvat: Gus Filgate.
-Jäniksen, kuusipeuran ja saksanhirven metsästys
Jne. Eli virheellisiä tietueita ainakin ruotsiksi. 

https://termipankki.fi/tepa/fi/haku/peura
Ks. myös Wikidata/Wikipedia

Tunturipeura=fjällren muuten puuttuu sanastosta. 
https://laji.fi/taxon/MX.206375
https://namnochslaktskap.artfakta.se/taxa/6006719/details

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Tämä on taas näitä perin pohjin hankalia eläintaksoneita, tuskin kukaan muu kuin eläintieteilijä arvaisi, että poro, metsäpeura ja karibu ovat kaikki samaa lajia, hirvi niiden kanssa samaa alaheimoa ja kuusipeura taas eri alaheimoa.

Laji.fi nimittää peuroiksi Rangifer-sukua, jonka ainoa laji on peura-poro-karibu, Wikipedia puolestaan Capreolinae-alaheimoa, joka Laji.fi:n mukaan taas on kauriit (=Odocoileinae, aiempi latinalainen nimi). 

Voidaan tietysti muuttaa > peura (laji) (en kyllä osaa sanoa miten käyttäjä tämän tulkitsee) tai peurat (suku), joka voidaan silti olettaa laajemmaksi kuin on.

**Comment by mariaforsen** [comment]
Monikielisyyden kannalta on kuitenkin välttämätöntä selkeyttää termin tarkoitusta. Vai aiheuttaako tämä termi enemmän harmia kuin hyötyä, ja olisi siten poistettavissa tai muutettavissa peurat (suku) = sv. Rangifer? Melindakäyttö on kyllä suorastaan virheellinen/täysin sekava.

NE: "Rangifer, det vetenskapliga namnet på ett släkte hjortdjur med en art, ren."
https://www.kielitoimistonsanakirja.fi/#/peura?searchMode=all

**Comment by FinMeSHienPaimentaja** [comment]
Menisin laji.fi mukaan, jos vaan muuten mahdollista ja onnistuisi ilman suuria pulmia.

**Comment by mirmaid** [comment]
_Peurat (suku)_ on siis taksonomisesti sama asia kuin _peura (laji)_, koska peura on sukunsa ainoa laji. (Taksonomisesti vastaava _kani_ on lajina https://github.com/Finto-ehdotus/YSE/issues/4942, siinä ei ole tarkennetta koska ei ole samanlaista merkityskentän epäselvyyttä).

**Comment by mirmaid** [comment]
Mahdollinen ratkaisu olisi esim. peura (laji) + määritelmä jossa avattaisiin tuo metsäpeura/poro/karibu-kuvio. Ja ehkä peura (valkohäntäpeura) KÄ valkohäntäpeura.

**Comment by jarmosaarikko** [comment]
Valkohäntä**peuran** lajinimeä on kovasti yritetty muuttaa valkohäntä**kauriiksi**, kun laji kerran ei ole sukua peuralla, vaan on kauris, mutta näitä väkiintuneita "vääriä" nimityksiä on vaikea muuttaa.    Sen vuoksi nuo scopeNotet olisivat kovin tärkeitä.   Selkeyden vuoksi tuossa voisi myös olla yksi väliporras. Tummennukset ovat minun suosikkejani nimityksiksi, jotka lienevät kaikki nisäkkäiden nimistötoimikunnalta.
- hirvieläimet (_Cervidae_) -  heimo
   - varsinaiset hirvet (KT **kauriit**  _Capreolinae_) - alaheimo
     - hirvi ((KT _Alces alces_) - laji
     - metsäkauris (KT Capreolus capreolus) - laji
     - valkohäntäpeura (KT **valkohäntäkauris** laukonpeura, _Odocoileus virginianus_)  - laji
     - peura (KT _Rangifer tarandus_, karibu) - laji 
        - poro  (KT tunturipeura, _Rangifer tarandus tarandus_) - alalaji
       - metsäpeura (KT _Rangifer tarandus fennicus_) - alalaji
  - jalohirvet (KT **jalokauriit**, _Cervinae_) - alaheimo
    - kuusipeura  (KT **täpläkauris**, _Dama dama_) - laji
    - saksanhirvi (KT **isokauris**,  _Cervus elaphus_) - laji

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan Mirjan ehdotuksen mukaisesti.
