### ISSUE TITLE
saamenkäsityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12049]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

saamenkäsityö

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Saimme palautetta finto-postiin: "Toivon asiasanastoon: saamenkäsityö - duodji"

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 duodji

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

Tuomas / Finto
**Termiehdotus Fintossa:** [saamenkäsityö](http://finto.fi/yse/fi/page/Y512049)

**Comment by tpalonen** [comment]
https://siida.fi/tuote-osasto/duodji-eli-saamenkasityo/

**Comment by mariguttorm** [comment]
Duodji on pohjoissaamea, muilla saamen kielillä omat termivastineensa. Saamenkäsityö tarkoittaa perinteistä saamelaista käsityötä (näitä käsitöitä näkyy hyvin esim. tuolla Siidan sivustolla) ja saamelaisten tekemää käsityötä. On myös yksi saamelaisten perinteisistä elinkeinoista kalastuksen, poronhoidon, metsästyksen ja keräilyn lisäksi. Pohjoissaamessa duodji tarkoittaa myös "teos", "luomus" ja "käsityö" yleisemmin. Usein näkee saamessakin muotoa sámi duodji/sápmelaš duodji eli on tarkennettu kyseessä olevan nimenomaan saamelainen käsityö. 

https://saamelaisensyklopedia.fi/wiki/Duodji,handicraft
https://www.oktavuohta.com/sami-duodji-saamelaista-kaesityoeta
https://finto.fi/lapponica/fi/page/L172

**Comment by jtuohini** [comment]
Tarvitaanko eri etnisten ryhmien käsityölle (yleensä) omaa asiasanaa? Eikö olisi selkeämpää käyttää yhdistelmää **käsityö (toiminta)** ja/tai **käsityöt** (tai tarpeen mukaan jokin tarkempi käsityön alalajia kuvaava asiasana, esim. **nahkatyöt**, **sarvityöt** tai **tekstiilityöt**) + ryhmää kuvaava asiasana (tässä tapauksessa joko **saamelaiset**, **inarinsaamelaiset**, **kolttasaamelaiset** tms.)? Eihän meillä ole erillisiä asiasanoja karjalaiselle käsityölle, metsäsuomalaiselle käsityölle, baijerilaiselle käsityölle, sorbilaiselle käsityölle eikä muillekaan.

**Comment by tpalonen** [comment]
YSO on suomalainen sanasto, suomalaisesta näkökulmasta rakennettu ja ainakin tästä vinkkelistä käsite näyttäytyy hyvinkin merkityksellisenä.
Vrt. esim. 
https://github.com/Finto-ehdotus/YSE/issues/12278
http://www.yso.fi/onto/yso/p9797
http://www.yso.fi/onto/yso/p4485
http://www.yso.fi/onto/yso/p8112

**Comment by jtuohini** [comment]
YSO:ssa pitäisi olla periaatteellinen ratkaisu, miten etnisyyden suhde eri taiteenlajeihin käsitellään johdonmukaisesti, kattaen kaikki taiteenlajit ja vastaavasti kukin kuvailun kannalta tärkeät etnokset. LCSH:ssa on yleensä selkeä kaava, jonka mukaan mennään, mutta YSO:ssa tulee koko ajan vastaan yksittäistapauksia, jolloin lopputulos on epäjohdonmukainen. Miten siis tähän liittyen muut saamelaiskulttuurin osa-alueet: saamelaiselokuva, saamelaisten kirjoittaam kaunokirjallisuus, saamelaisten musiikki, ml. joiut (joita siis teostyyppinä on esiintynyt myös Vienankarjalassa) jne.

**Comment by tpalonen** [comment]
YSOa rakennetaan eri periaatteilla kuin LCSH:ta, joten monikin asia varmasti näyttäytyy epäjohdonmukaisena, jos YSOa tarkastellaan LCSH:sta käsin. 

Vielä saamenkäsityöstä: siitä voi mm. suorittaa ammattitutkinnon, mikä jo itsessään on riittävä peruste sille että voidaan puhua ihan itsenäisestä käsitteestä. 
https://www.sogsakk.fi/fi/Hakijalle/Koulutustarjonta/Saamenkasityoalan-ammattitutkinto

Ja termiä näkyy käytettävän julkisella sektorilla esim. Opetushallitus puhuu saamenkäsityöstä ja saamenkäsityöalasta. Eli kyllä näkisin, että tässä kriteerit sanastoon ottamiseen täyttyvät.
https://www.oph.fi/fi/uutiset/2022/saamenkasityoalan-tutkintojen-perusteita-uudistetaan

**Comment by mirmaid** [comment]
^^ YSOssa on vanhastaan joitakin poikkeuksellisesti käsiteltyjä termejä (esim. afroamerikkalainen kirjallisuus), joiden poistoa ollaan kokouksessa pohdittu. Onko parempi hyväksyä pieni horjuvuus vai poistaa vanhoja termejä takautuvasti, on tottakai mielipidekysymys - jokin tuleva kokous voi päätyä myös erilaiseen ratkaisuun.

En ole saamenkäsityön suhteen asiantuntija, mutta mietin muodostaako se kuitenkin myös tyylillisesti oman käsityölajinsa, ts. merkitys ei olisi pelkästään saamelaisten tekemä käsityö.

**Comment by mariaforsen** [comment]
Sv. sameslöjd, samisk slöjd, duodji? HT samehantverk, samehantverk och -handarbete, samiskt konsthantverk
https://www.hbl.fi/artikel/446f030b-2066-4d18-b952-14965aca008e
https://id.kb.se/find?q=samesl%C3%B6jd
https://sv.wikipedia.org/wiki/Duodji
https://www.samer.se/duodji
https://hantverkslarling.se/utbildningar/duodji/
https://urplay.se/program/196347-ur-samtiden-samiska-veckan-2016-duodji-och-urfolksperspektivet
https://www.oktavuohta.com/opetusmateriaali-saamenkasityot

Olisiko tarkoitus viitata toimintaan vai valmiiseen tuotteeseen? Vrt. https://www.kielitoimistonsanakirja.fi/#/k%C3%A4sity%C3%B6?searchMode=all

**Comment by FinMeSHienPaimentaja** [comment]
Olen samoilla linjoilla kuin jtuohini eli pitäisi olla johdonmukainen näissä eikä jokaisen etnisen ryhmän käsityölle ym. tarvi erikseen termiä, mutta olen myös samoilla linjoilla kuin tpalonen eli "saamenkäsityö" on kuitenkin tärkeämpi/mekityksellisempi kuin monet muut tällaiset vastaavanlaiset jonkin etnisen ryhmän käsityöt/käsityö.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
