### ISSUE TITLE
Mailbox

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12047]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mailbox](http://www.yso.fi/onto/yso/p18792)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onkohan tämä käsite tarpeellinen? Tämä voi ilmeiseti tarkoittaa useampia asioita, kun nyt YSOssa on yläkäsitteenä käyttöliittymät ja termiä on käytetty Melindassa tietueessa  "Mailbox, käyttöliittymä Telebox-järjestelmään", jonka julkaisuvuosi on 1990. Wikidata-linkki johtaa kuitenkin Mailbox-nimistä vuonna 2013 julkaistua sovellusta käsittelevälle sivulle.

**Perustelut ehdotukselle**

Melindassa yhteensä kaksi viitettä:
jo edellä mainittu Mailbox, käyttöliittymä Telebox-järjestelmään https://melinda.kansalliskirjasto.fi/byid/000689030
ja lisäksi jostain syystä tämä viite vuodelta 1979:
Tekijä   	Kojo:.
Nimeke   So mean.
https://melinda.kansalliskirjasto.fi/byid/014560307

**Ehdottajan organisaatio**

kk/il

**Comment by tpalonen** [comment]
Tuo Kojo lienee kuvailuvirhe. Levy sisältää kappaleen nimeltä Mailbox. "Toiseksi viimeisenä lauluna kuullaan jälleen näppärä albumiraita Mailbox, joka on kolmeminuuttinen jykevä rokki. Jälleen esille nousee Jukka Orman tiukka kitarasoolo, joka nostaa kokonaisuuden uusiin sfääreihin."
https://www.finnhitsaaja.fi/2016/04/kojo-so-mean-finnlevy-1979.html
