### ISSUE TITLE
vanhurskauttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12055]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vanhurskauttaminen](http://www.yso.fi/onto/yso/p5252)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng. justification by faith? 

**Perustelut ehdotukselle**

https://helda.helsinki.fi/items/60ed5b3c-9e8b-4907-b844-1e23b0e9e53a

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://en.wikipedia.org/wiki/Justification_(theology)
