### ISSUE TITLE
suutuntuma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12053]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suutuntuma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/471ea879-c5cc-49c1-8e96-66b1e58ee890

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [suutuntuma](http://finto.fi/yse/fi/page/Y512053)

**Comment by jtuohini** [comment]
Ja kenties RT-suhde [**tekstuuri**](http://www.yso.fi/onto/yso/p24297)-asiasanaan?

**Comment by mirmaid** [comment]
2 viitettä Melindassa. Aika paljon tutkimuskohteena, https://yle.fi/a/74-20017882.

**Comment by jtuohini** [comment]
Ja lisäksi aineistoja, jotka tätä asiasanaa kaipaisivat, mutta joista se puuttuu tykkänään: https://melinda.kansalliskirjasto.fi/byid/016643866, https://melinda.kansalliskirjasto.fi/byid/000915587 jne.

**Comment by fantsby-m** [comment]
Myös ohjaus tekstuuri (suutuntuma) KÄ suutuntuma

**Comment by mariaforsen** [comment]
Sv. munkänsla
https://sv.wikipedia.org/wiki/Munk%C3%A4nsla
https://sverigesradio.se/avsnitt/1648212

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
