### ISSUE TITLE
kasvituotteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12054]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kasvituotteet](http://www.yso.fi/onto/yso/p9249)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT kasvipohjaiset tuotteet/valmisteet

**Perustelut ehdotukselle**

Sanastossa on useita mahdollisia termejä, mutta käytännössä joskus vaikea valita sopivaa: kasvituotteet, viljavalmisteet, vihannesvalmisteet, kasviproteiinivalmisteet. Aineistossa kyseessä kasvipohjainen jugurtti, https://helda.helsinki.fi/items/471ea879-c5cc-49c1-8e96-66b1e58ee890

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. päätermi on vegetabiliska produkter, eli ="kasviperäiset tuotteet". 
YSOssa on kasviperäiset maidot KÄYTÄ kasvimaidot

**Comment by FinMeSHienPaimentaja** [comment]
Onko "kasvipohjaisten tuotteiden/valmisteiden" ideana se, että aiemmin esim. eläinperäisen maidon sijaan / vaihtoehdoksi tuleekin (kasvipohjainen) kauramaito...? Kasviperäisiä/pohjaisia tuotteitahan on muuten vaikka kuinka paljon ihan sinänsäkin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ehdotus.
