### ISSUE TITLE
tieteenalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12050]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tieteenalat](http://www.yso.fi/onto/yso/p352)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT tutkimusalat?

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/tutkimusala
Sv. HT forskningsområden

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://www.aka.fi/tutkimusrahoitus/hae-rahoitusta/nain-haet-rahoitusta/ohjehakemisto/tutkimusalaluokitus/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
