### ISSUE TITLE
Pyhäjärvi (Karjalan tasavalta)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12058]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pyhäjärvi (Karjalan tasavalta)](http://www.yso.fi/onto/yso/p226071)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

vrt. myös http://www.yso.fi/onto/yso/p106244, sekoittuu?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Pyh%C3%A4j%C3%A4rvi_(Karjalan_tasavalta)

https://fi.wikipedia.org/wiki/Pyh%C3%A4j%C3%A4rvi_(Pyh%C3%A4j%C3%A4rvi_Vpl)

**Comment by mirmaid** [comment]
Pyhäjärvi (Karjalan tasavalta) pitäisi kai olla ok (linjausten mukaan tyyppitarkenne ei välttämätön), mutta tuo Pyhäjärvi (Venäjä : järvi) on epäselvä - mahdollisia Käkisalmen piiri, Leningradin alue, Karjalankannas.

**Comment by YSO-kokous** [comment]
Muutetaan muotoon Pyhäjärvi (Karjalan kannas : järvi)

Mikäli käy ilmi, että Karjalan kannaksella on toinenkin Pyhäjärvi, voidaan palata asiaan.
