### ISSUE TITLE
Mantšuria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12066]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mantšuria](http://www.yso.fi/onto/yso/p110034)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pidetäänkö erillään tämä ja Dongbei?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Eksonyymi (suomenkielinen nimi)	Koillis-Kiina, Mantšuria (vanh.)
Endonyymi (paikallinen nimi) ja kielen tunnus	Dongbei kiina
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1577&ex=Koillis-Kiina

**Comment by mariaforsen** [comment]
SAOssa ja Nationalencyklopedinissa vain Manchuriet. 
https://sv.wikipedia.org/wiki/Nord%C3%B6stra_Kina
"Nordöstra Kina eller Dongbei (kinesiska: 东北?, pinyin: Dōngběi) är en geografisk region i Kina bestående av de tre nordligaste provinserna. Heilongjiang, Jilin och Liaoning...Dessa tre provinser utgör nästan samma område som historiskt kallats Manchuriet"

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi Koillis-Kiina KÄYTÄ Dongbei.
Poistetaan olemassa olevat huomautukset Dongbeilta ja Mantsurialta.
