### ISSUE TITLE
Svalbard

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12061]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Svalbard](http://www.yso.fi/onto/yso/p129738)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-linkitys, vrt. Huippuvuoret

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Pitäisikö yhdistää?

**Comment by ilona-x** [comment]
Svalbardilla YSO-paikoissa huomautus: Huippuvuoret ja Karhusaaren käsittävä Norjan hallintoalue

--

Eksonyymi (suomenkielinen nimi)	Huippuvuoret
Paikan laji	saaristo
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=169&ex=Huippuvuoret

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet eli:
Svalbard KÄYTÄ Huippuvuoret

**Comment by mariaforsen** [comment]
Sv. Spetsbergen > Svalbard
