### ISSUE TITLE
Imatranajot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12060]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Imatranajot](http://www.yso.fi/onto/yso/p29103)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Imatranajo

**Perustelut ehdotukselle**

Tapahtuman virallinen nimi on yksikössä Imatranajo, ks. tapahtuman kotisivu www.imatranajo.fi.

**Ehdottajan organisaatio**

Imatran kaupunginkirjasto

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan yksikköön.
