### ISSUE TITLE
Lapväärtinjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12076]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lapväärtinjoki](http://www.yso.fi/onto/yso/p105397)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään käsitteeseen Isojoki (joki)

**Perustelut ehdotukselle**

Isojoki tai Lapväärtinjoki on kaakkois-lounaissuuntaisesti Isojoen, Karijoen ja Kristiinankaupungin alueilla virtaava 75 kilometriä pitkä joki
https://fi.wikipedia.org/wiki/Isojoki_(joki)
https://fi.wikipedia.org/wiki/Lapv%C3%A4%C3%A4rtinjoen_vesist%C3%B6

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Paikkatietoalusta käsittelee jokien erinimisiä osio usein eri paikkoina. Lähdetäänkö yhdistämään? Vrt. myös esim. Mustionjoki/Vanjoki (tosin omanlaisensa tapaus, koska välissä on Lohjanjärvi). Nyt Pajulanjoki/Virkaanjoki on yhtenä, mutta lisätty toinen linkki. Myös mahdollista käsitellä näitä niin, että toisella nimellä tunnettu joen osa olisi alakäsite.

**Comment by YSO-kokous** [comment]
Säilytetään ja lisätään RT-suhteet muihin saman joen osiin.
