### ISSUE TITLE
Kullaanjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12077]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kullaanjoki](http://www.yso.fi/onto/yso/p109885)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KÄ Harjunpäänjoki

**Perustelut ehdotukselle**

Harjunpäänjoki (eri jokiosuuksilla nimenä myös Kaasmarkunjoki, Kullaanjoki ja Joutsijoki)

https://fi.wikipedia.org/wiki/Harjunp%C3%A4%C3%A4njoki
kaikki eri nimet näkyvät myös Karttapaikan kartassa

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ks. Lapväärtinjoki. Suhde joka tapauksessa selvennettävä.

**Comment by YSO-kokous** [comment]
Säilytetään ja lisätään RT-suhteet muihin saman joen osiin.
