### ISSUE TITLE
Salonjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12075]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Salonjoki](http://www.yso.fi/onto/yso/p135842)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KÄ Uskelanjoki

**Perustelut ehdotukselle**

Uskelanjoki & Salonjoki
Joki Varsinais-Suomessa. Salon kaupungin kohdalla joen nimi on Salonjoki
https://fi.wikipedia.org/wiki/Uskelanjoki
Karttapaikan (https://asiointi.maanmittauslaitos.fi/karttapaikka/) sijaintilinkit vievät samaan kohtaan ja kartassa lukee Salonjoki eli Uskelanjoki

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ks. Lapväärtinjoki

**Comment by YSO-kokous** [comment]
Säilytetään ja lisätään RT-suhteet muihin saman joen osiin.
