### ISSUE TITLE
Tunham

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12072]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Tunham](http://www.yso.fi/onto/yso/p170391)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sama kuin Tunnhamn?

**Perustelut ehdotukselle**

http://paikkatiedot.fi/so/1000772/10307284
https://fi.wikipedia.org/wiki/Tunhamn

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Oikea termi sekä suomeksi että ruotsiksi lienee Tunnhamn, ks. esim. Paikkatietoikkuna ja https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=tunnhamn

Helsingin sanomat 22.4.23: "Virallisissa kartoissa saaren nimi kirjoitetaan kahdella n-kirjaimella Tunnhamn, mutta paikallisten käyttämä vakiintunut muoto on Tunhamn."
