### ISSUE TITLE
Säkylänharju

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12079]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Säkylänharju](http://www.yso.fi/onto/yso/p135369)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-linkin tarkistus

**Perustelut ehdotukselle**

Myös Virttaankangas on sanastossa. Karttapaikan mukaan sijaitsevat eri kunnissa
https://fi.wikipedia.org/wiki/S%C3%A4kyl%C3%A4nharju_ja_Virttaankangas

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Wikidata-wikipedia yhdistää nämä samaksi harjukokonaisuudeksi, joita käsitellään yhdessä.

**Comment by jarmosaarikko** [comment]
Lisäsin Wikidataan poikkeuksen YSO-ID määrittelyyn ja siellä on nyt molemmat tunnisteet.
http://www.wikidata.org/entity/Q24305840
