### ISSUE TITLE
Kaukoitä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12071]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kaukoitä](http://www.yso.fi/onto/yso/p112148)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

vrt. Itä-Aasia, kaipaako tarkennusta?

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kaukoit%C3%A4
https://fi.wikipedia.org/wiki/It%C3%A4-Aasia

**Comment by mirmaid** [comment]
Kaukoitä-käsitteellä nyt huomautus: Kaukoitä on Kiinasta, Mongoliasta, Korean niemimaasta, Ja- panista ja Venäjän itäisimmästä osasta käytetty yleisnimi. Joskus Kaukoitään luetaan myös Kaakkois-Aasia saaristoineen - eli wikipedia-sivun teksti.

**Comment by ilona-x** [comment]
Eksonyymi (suomenkielinen nimi)	**Kaukoitä**
Paikan laji	alue
Paikan lajityyppi	alueet
Paikan sijainti tai osat	Aasia (= Kaakkois-Aasia + Itä-Aasia + Kaukoidän federaatiopiiri [Venäjä])
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1491&ex=Kaukoit%C3%A4

**Comment by ilona-x** [comment]
Eksonyymi (suomenkielinen nimi)	**Kaakkois-Aasia**
Paikan laji	alue
Paikan lajityyppi	alueet
Paikan sijainti tai osat	Aasia (= Taka-Intia + Malaijien saaristo [Brunei + Filippiinit + Indonesia + Itä-Timor + Kambodža + Laos + Malesia + Myanmar + Singapore + Thaimaa + Vietnam])
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1468&ex=Kaakkois-Aasia

**Comment by mariaforsen** [comment]
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/fj%C3%A4rran-%C3%B6stern Eli fjärran östern "aikaisempi nimitys", eikä löydy SAOssa vaan viittaa näihin: https://id.kb.se/find?q=fj%C3%A4rran%20%C3%B6stern

**Comment by ilona-x** [comment]
Itä-Aasia
Paikan sijainti tai osat	Aasia (= Japani + Etelä-Korea + Kiina + Mongolia + Pohjois-Korea + Taiwan)
https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1438&ex=It%C3%A4-Aasia

**Comment by YSO-kokous** [comment]
Päätös: 
Lisätään Itä-Aasiaan huomautus Kotuksen Eksonyymien mukaan.
Kaukoitä RT Itä-Aasia. Korjataan huomautuksen kirjoitusvirhe: Ja- pani.
