### ISSUE TITLE
Virkaanjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12078]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Virkaanjoki](http://www.yso.fi/onto/yso/p139505)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KÄ Pajulanjoki

**Perustelut ehdotukselle**

Pajulanjoki (myös Virkaanjoki) on Paimionjoen sivujoki Somerolla ja Tammelassa
https://fi.wikipedia.org/wiki/Pajulanjoki

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Vanjoki / Mustionjoki (erikseen YSO-paikoissa) oli samankaltainen tapaus?

**Comment by YSO-kokous** [comment]
Säilytetään ja lisätään RT-suhteet muihin saman joen osiin.
