### ISSUE TITLE
Etelä-Suomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12074]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Etelä-Suomi](http://www.yso.fi/onto/yso/p105917)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-linkityksen tarkistus, vrt. Etelä-Suomen lääni

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Etelä-Suomen lääni erikseen YSO-paikoissa
http://www.yso.fi/onto/yso/p111726 linkattu Wikidataan Etelä-Suomen lääni

Etelä-Suomi linkattu Wikidatassa sekä Etelä-Suomen lääni -käsitteeseen että Etelä-Suomi -käsitteeseen:
[Etelä-Suomi](http://www.wikidata.org/entity/Q107033548)
[Etelä-Suomen lääni](http://www.wikidata.org/entity/Q188752) 

--
Wikidatan Etelä-Suomi käsitteessä viitataan tähän luokitukseen https://www.stat.fi/fi/luokitukset/nuts/

**Comment by ilona-x** [comment]
Riittääkö tässä, että korjataan wikidata-linkitys eli poistetaan YSO-paikkojen Etelä-Suomi -käsitteeltä Etelä-Suomen lääni -linkki?

YSO-paikoissa myös Länsi-Suomi ja Länsi-Suomen lääni sekä Itä-Suomi ja Itä-Suomen lääni

**Comment by YSO-kokous** [comment]
Poistetaan Wikidata-linkki Etelä-Suomen lääniin.
