### ISSUE TITLE
Viipurin kuvernementti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12073]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Viipurin kuvernementti](http://www.yso.fi/onto/yso/p197138)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sama vai eri kuin Vanha Suomi?

**Perustelut ehdotukselle**

wikidata

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Koskeekohan kysymys wikidata-linkitystä? Nyt Viipurin kuvernementilla on molemmat linkit.

**Comment by mariaforsen** [comment]
https://fho.sls.fi/uppslagsord/19793/viborgs-guvernement/
https://fho.sls.fi/uppslagsord/14124/gamla-finland/

**Comment by YSO-kokous** [comment]
Poistetaan Wikidata-linkki Vanha Suomeen.
