### ISSUE TITLE
Hirsimetsä (Kälviä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12081]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Hirsimetsä (Kälviä)](http://www.yso.fi/onto/yso/p105929)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan

**Perustelut ehdotukselle**

Kälviä -- Hirsimetsä - mikä paikka kyseessä, metsäalue? http://www.kalvianhirsimetsa.fi/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Minkähänlaista tarkistusta tässä on toivottu? Melindassa yksi aineisto, joka käsittelee metsää. Linkityskohteita ei löydy.

**Comment by ilona-x** [comment]
Tämä taitaa olla peräisin vanhalta ongelmatapauslistalta ja on varmaan peruja siitä, kun kävin läpi käsitteitä, joilla ei ollut yläkäsitettä, kun sitä ei ollut automaattisesti tullut, kun PNR-linkkiä ei ollut. 

Tämän kohdalla taisin vain ihmetellä, että paikkatyyppi on erikoinen eli auktorisoidaanko tällaisia yhteismetsiä YSO-paikkoihin? Joitakin yhteismetsiä näyttää löytyvän Kantosta: https://finto.fi/finaf/fi/search?clang=fi&q=*yhteismets%C3%A4*

Melindan ainoa viite on paikallisen metsänhoitoyhdistyksen historiikki:
https://melinda.kansalliskirjasto.fi/byid/000697050

**Comment by YSO-kokous** [comment]
Poistetaan, koska vain kerran käytetty kuvailussa. Kälviä riittänee jatkossa kuvailussa.
