### ISSUE TITLE
Romuvaara (Kuhmo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12088]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Romuvaara (Kuhmo)](http://www.yso.fi/onto/yso/p112910)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kuhmossa 6 Romuvaara -nimistä kohoumaa, mutta kaikki Melindan aineistot käsittelevät yhtä Romuvaara, jonka alueelle on suunniteltu ydinjätteiden loppusijoitusta

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
(Kuhmo, Pitämävaara)? Pitämävaara on ko. Romuvaaraa lähinnä oleva kylä, mutta Romuvaara ei sijaitse Pitämävaaran kylässä. Pitämävaara on myös vaara. 

En kyllä näe ongelmana tarkentamatta jättämistä, koska Kuhmon muista Romuvaaroista tuskin tulee aineistoa - ainakaan niin paljon, ettei hakija löytäisi etsimäänsä.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

_Romuvaara (Kuhmo, Pitämävaara)_

Pitämävaara on lähin isompi lähellä oleva paikka, jonka avulla voi yksilöidä käsitteen. Vastaavanlaista merkintätapaa on käytetty muissakin. 
Ks. esim. http://www.yso.fi/onto/yso/p215759
http://www.yso.fi/onto/yso/p173436
http://www.yso.fi/onto/yso/p508761
