### ISSUE TITLE
Niskala (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12082]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Niskala (Helsinki)](http://www.yso.fi/onto/yso/p124931)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Helsinki – Niskala  -kyseessä Niskalan arboretum? Nyt linkattu taloon, mutta kaikki viitteet käsittelevät arboretumia, pitäisikö auktorisoida puistona eikä paikkana? Asutusnimihakemistosta löytyy kylä Helsinki – Niskala

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Svenska ortnamnin mukaan "del av Domarby"
https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=nackb%C3%B6le

**Comment by YSO-kokous** [comment]
Poistetaan tämä käsite ja otetaan YSOon käsite muodossa Niskalan arboretum.
Ohjaustermeiksi Niskalan puulajipuisto ja Niskala (arboretum).
