### ISSUE TITLE
Jokilehto (Kärsämäki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12080]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Jokilehto (Kärsämäki)](http://www.yso.fi/onto/yso/p163749)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Koulupiiri? 

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ainakin Jokilehdolla on kylätoimikunta, vaikka Paikkatietoalusta tai Asutusnimihakemisto ei kylää tunnekaan: https://karsamaki.fi/vapaa-aika/kylatoimintaa/

https://www.ppkylat.fi/seutukunnat-ja-kylat/

**Comment by mirmaid** [comment]
Huomautuksen voisi poistaa. Tämä oli siis kahdesta koulupiiristä yhdistetty koulupiiri (nyt sekin koulu on jo lakkautettu, eikä enää puhuta koulupiireistä). Nykyään paikalla on jonkinlainen kylästatus.

**Comment by YSO-kokous** [comment]
Jätetään toistaiseksi sanastoon, mutta poistetaan huomautus, koska ei pidä enää paikkaansa. 

Otetaan Maanmittauslaitokseen yhteyttä ja kysytään tarkempaa tietoa Jokilehdosta. Jokilehdolla on mm. kylätoimikunta/kyläyhdistys. YSO-paikkojen ylläpito yritti selvittää Jokilehdon tarkkaa sijaintia, mutta ei onnistunut yrityksissään.

**Comment by mirmaid** [comment]
Poistetaan Jokilehto, lisätään ohjaustermiksi Ojalehdolle ja Alajoelle.
