### ISSUE TITLE
lukinkalvonalainen verenvuoto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12090]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lukinkalvonalainen verenvuoto

**Ehdotettu termi ruotsiksi**

subaraknoidalblödning

**Ehdotettu termi englanniksi**

subarachnoid hemorrhage

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu
Melinda x 16 + 6 x FinMeSH-terminä

**Ehdotettu yläkäsite YSOssa (LT)**

 [verenvuoto](http://www.yso.fi/onto/yso/p16148), [aivoverenvuoto](http://www.yso.fi/onto/yso/p1712)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 aivoaneurysman ruptuura , subaraknoidaalivuoto, SAV

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85129404), [Wikipedia](https://fi.wikipedia.org/wiki/Lukinkalvonalainen_verenvuoto), [FinMeSH](http://www.yso.fi/onto/mesh/D013345)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Delayed Cerebral Ischemia and Blood Coagulation Changes After Aneurysmal Subarachnoid Hemorrhage https://urn.fi/URN:ISBN:978-952-03-2786-6

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Lääketieteen termit: 
aivoverenvuoto: verenvuoto aivokudokseen tai aivokammioon; vrt. kovakalvonalainen verenvuoto, kovakalvonulkoinen verenvuoto, lukinkalvonalainen verenvuoto

kovakalvonalainen verenvuoto: subduraalinen verenvuoto, subduraalivuoto | (yleensä vammasta aiheutunut) verenvuoto aivojen →kovakalvon (2) ja →lukinkalvon väliin

lukinkalvonalainen verenvuoto: subaraknoidaalivuoto| valtimoverenvuoto →lukinkalvo-onteloon

**Comment by mariaforsen** [comment]
Sv. subaraknoidalblödning HT hjärnhinneblödning, aneurysmal subaraknoidalblödning, spontan subaraknoidalblödning, intrakraniell subaraknoidalblödning
https://mesh.kib.ki.se/term/D013345/subarachnoid-hemorrhage
https://www.internetmedicin.se/behandlingsoversikter/neurokirurgi/subaraknoidalblodning/
