### ISSUE TITLE
valkoiset (Suomen sisällissota)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12107]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[valkoiset (Suomen sisällissota)](http://www.yso.fi/onto/yso/p25937)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi valkokaartilaiset

**Perustelut ehdotukselle**

Synonyminen termi.

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Ehkä sulkutarkenne olisi tässä tarpeen? _valkokaartilaiset (Suomen sisällissota)_
Valkokaartilla voidaan viitata myös Venäjän sisällissotaan ja Venäjän valkoiseen armeijaan. "Venäjän valkoinen armeija (ven. Белая Армия, Belaja Armija) tai Valkokaartit (ven. Белая Гвардия, белогвардейцы, Belaja Gvardija, belogvardeitsy) oli venäläinen monarkistiliike, joka taisteli Venäjän sisällissodassa (1918–1921) punaisia sekä niin sanottuja Vihreää armeijaa (nationalistit) ja Mustaa armeijaa (anarkistit) vastaan."
https://fi.wikipedia.org/wiki/Ven%C3%A4j%C3%A4n_valkoinen_armeija
