### ISSUE TITLE
punaiset (Suomen sisällissota)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12106]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[punaiset (Suomen sisällissota)](http://www.yso.fi/onto/yso/p25898)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi punakaartilaiset

**Perustelut ehdotukselle**

Synonyminen termi. 

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Ehkä sulkutarkenne olisi tässä hyväksi? _punakaartilaiset (Suomen sisällissota)_
Punakaartilla voidaan viitata myös Venäjän sisällissotaan ja puna-armeijaan muodostui punakaarteista. "Venäjän armeija järjestettiin 15. tammikuuta 1918 kansankomissaarien määräyksellä uudelleen työläisten ja talonpoikien punaiseksi olemassa olevien punakaartien pohjalle."
https://fi.wikipedia.org/wiki/Ven%C3%A4j%C3%A4n_sis%C3%A4llissota
