### ISSUE TITLE
okasolusyöpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12109]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[okasolusyöpä](http://www.yso.fi/onto/yso/p27078)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muitakin levyepiteelikarsinoomia kuin tämä?

**Perustelut ehdotukselle**

https://helda.helsinki.fi/items/eff79bfe-e68f-40c3-98fb-1bc580455d61

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Lääketieteen termit:
levyepiteelikarsinooma: levyepiteelikarsinooma, spinosellulaarinen karsinooma | kerrostuneen epiteelin tai sen kaltaiseksi muuttuneen muun epiteelin syöpä esim. ihossa (→okasolusyöpä) tai keuhkoputken, kohdunkaulan tai ruokatorven limakalvossa; ks. myös akantooma, papillooma

okasolusyöpä: ihon →levyepiteelisyöpä

MeSHissä ohjaus on toisin päin.

Joskus näytetään käyttävän okasolusyöpä-muotoa myös silloin kun kyse ei ole ihosyövästä.

**Comment by YSO-kokous** [comment]
**Päätös**

Tehdään muutos MeSHin mallin mukaan.
