### ISSUE TITLE
liposarkooma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12108]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

liposarkooma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/77b7c8c3-ae49-4b3c-a9c1-15f3e730a1b0

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [liposarkooma](http://finto.fi/yse/fi/page/Y512108)

**Comment by ilona-x** [comment]
FinMeSH: **liposarkooma** http://www.yso.fi/onto/mesh/D008080

LCSH: **Liposarcoma** http://id.loc.gov/authorities/subjects/sh88002663

Wikidata: http://www.wikidata.org/entity/Q1827425

**Comment by mariaforsen** [comment]
Sv. liposarkom 
https://mesh.kib.ki.se/term/D008080/liposarcoma
