### ISSUE TITLE
ihmeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12119]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ihmeet](http://www.yso.fi/onto/yso/p627)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT ihmeparantumiset?

**Perustelut ehdotukselle**

 Ovat eräänlaisia ihmeitä, ja aineistoa löytyy. Kuvailija tai tiedonhakija joka hakee tällä, pitäisi varmaan saada jotain.. 

**Ehdottajan organisaatio**

ALLFO

**Comment by AuHo22** [comment]
Meillä on henkiparannus KT ihmeparannus, joka on toimintaa, eli kaivattaisiin varmaankin termi joka kuvaisi "lopputuotetta". Ihmeet-termillä on useita ulottuvuuksia eli merkityksiä, uskonnolliset ihmeet, rajatiedon tai selittämättömät ihmeet, ja sitten vielä yleiskielinen ihmeet-käyttö, kuten maailman seitsemän ihmettä samoin kuin yleistajuisissa tietokirjoissa kuvataan ihmeitä yli-inhimillistä lähestyvässä merkityksessä, esim. Guinness world records - tarvittaisiinko tarkenteita? Mysteerit-ehdotuksen esimerkeissä oli viittauksia myös näihin "luonnon ihmeisiin" -> The seventy great mysteries of the natural world : unlocking the secrets of our planet ("Any general-interest or school collection strong in natural wonders needs The Seventy Great Mysteries of the Natural World") Eli ihmeet-termiä on paremman puutteessa taidettu käyttää ikään kuin ihmettelyn kohteistakin.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksyttiin ohjaustermi _ihmeparantumiset (ihmeet)_.
