### ISSUE TITLE
mansikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12136]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mansikat](http://www.yso.fi/onto/yso/p37830)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne (suku) tms. tarkennus suomeksi, ja ehkä ohjaustermi mansikat (marjat) KÄYTÄ puutarhamansikka?

**Perustelut ehdotukselle**

Vaarana on että käytetään suomeksi tätä termiä, silloin kun kyseessä on mansikat marjana (ja näin tehtykin Melindassa). Ainakin ruotsiksi tämä aiheuttaa virheitä kuvailuihin. 

**Ehdottajan organisaatio**

ALLFO

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ehdotus.
