### ISSUE TITLE
avainlajit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12138]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

avainlajit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

 key species

**Tarkoitusta täsmentävä selite**

ekosysteemin tai eliöyhteisön toimintaan voimakkaasti vaikuttava laji

**Perustelut ehdotukselle**

Ajankohtainen käsite
https://yle.fi/aihe/a/20-10004263

**Ehdotettu yläkäsite YSOssa (LT)**

 [lajit](http://www.yso.fi/onto/yso/p2765)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579), [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533), [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [TEPA](https://termipankki.fi/tepa/fi/haku/avainlaji)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Korvaamattomat : kertomuksia maailman avainlajeista  / kirjoittanut Juha Kauppinen ; kuvittanut Janne Toriseva

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [avainlajit](http://finto.fi/yse/fi/page/Y512138)

**Comment by mirmaid** [comment]
Melindassa 4 x monikossa, 3 x yksikössä.

https://tieteentermipankki.fi/wiki/Biologia:avainlaji
https://fi.wikipedia.org/wiki/Avainlaji

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. nyckelarter
https://sv.wikipedia.org/wiki/Nyckelart
https://termipankki.fi/tepa/fi/haku/nyckelart
