### ISSUE TITLE
ilmatorjuntajärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12139]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ilmatorjuntajärjestelmät

**Ehdotettu termi ruotsiksi**

luftvärnssystem

**Ehdotettu termi englanniksi**

air defense systems

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kongressin kirjaston sanastossa (https://id.loc.gov/authorities/subjects/sh85002625.html) on lueteltuna tietyt järjestelmät nimeltä, mutta laajempi termi olisi monikäyttöisempi. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [asejärjestelmät](http://www.yso.fi/onto/yso/p15948)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [ilmatorjuntaohjukset](http://www.yso.fi/onto/yso/p40019)

**Assosiatiiviset (RT)**

 [ilmatorjunta](http://www.yso.fi/onto/yso/p18174)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.169506?sid=2989479945

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [ilmatorjuntajärjestelmät](http://finto.fi/yse/fi/page/Y512139)

**Comment by mirmaid** [comment]
N. 50 kertaa Melindassa.

**Comment by ilona-x** [comment]
SOTO-termi ilmatorjuntajärjestelmät http://www.yso.fi/onto/soto/p1470

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
