### ISSUE TITLE
työstäkieltäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12148]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

työstäkieltäytyminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käytetään terminomaisesti nykyään ja pari kirjaa ainakin kirjoitettu aiheesta jo Suomessa. Lisätietoa esim. http://kumu.info/usein-kysytyt-kysymykset-i/ tai https://tk-liitto.tumblr.com/ 

**Ehdotettu yläkäsite YSOssa (LT)**

 [kieltäytyminen](http://www.yso.fi/onto/yso/p1697)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Eurooppa kieltäytyy työstä 978-952-65243-1-3, (tai esim. Työstäkieltäytyjän käsikirja).

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [työstäkieltäytyminen](http://finto.fi/yse/fi/page/Y512148)

**Comment by mirmaid** [comment]
Kerran Melindassa (em. Eurooppa kieltäytyy työstä).

**Comment by mariaforsen** [comment]
Sv. arbetsvägran
https://www.sanakirja.fi/custom/en-sv-fi/ty%C3%B6st%C3%A4kielt%C3%A4ytyminen
https://svenska.yle.fi/a/7-1307910
https://yle.fi/a/3-10072790
Ylellä näyttää olevan aineistoa..

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
