### ISSUE TITLE
joustavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12144]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[joustavuus](http://www.yso.fi/onto/yso/p17703)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään joustavuuden käsitteeksi myös resilienssi.

**Perustelut ehdotukselle**

Työelämässä tarvittavalle joustavuudelle on hankala löytää mitään konkreettista pohjatietoa pelkästään joustavuus termiä käyttämällä, mutta jos hakusanaksi vaihtaa resilienssin niin työelämän joustavuudelle löytää paljon tietoa suomeksi.

**Ehdottajan organisaatio**

Opiskelija Humak.

**Comment by mirmaid** [comment]
Sanastossa on _resilienssi_ erikseen. Näillä voisi varmaan olla RT-suhde.

Kielitoimiston sanakirja: resilienssi: kyky pysyä toimintakykyisenä vaikeissa muutostilanteissa ja palautua niistä.

**Comment by mirmaid** [comment]
_Joustavuus_ myös käsittelyssä: https://github.com/Finto-ehdotus/YSE/issues/9714

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään RT-suhde.
