### ISSUE TITLE
Muistokoti Aappola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12140]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Muistokoti Aappola

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [taiteilijakodit](http://www.yso.fi/onto/yso/p956), [kotimuseot](http://www.yso.fi/onto/yso/p11345)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Taiteilijakoti Aappola, Abraham Ojanperän muistokoti

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Aikamatkoja menneisyyteen : sanoja toisesta todellisuudesta 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Muistokoti Aappola](http://finto.fi/yse/fi/page/Y512140)

**Comment by jtuohini** [comment]
Kyseessä on RDA:n näkökulmasta yhteisö, joten kuuluu Kantoon, jonne se myös on auktorisoitu ([**Muistokoti Aappola**](http://urn.fi/URN:NBN:fi:au:finaf:000223985)).

**Comment by ilona-x** [comment]
Ok, yhteisö on näköjään lisätty Kantoon 2.10.2023 eli ehdotuksen tekemisen jälkeen.

**Comment by mariaforsen** [comment]
Sv. Abraham Ojanperä museum HT Aappola (museum), Hemmuseet Aappola
https://museot.fi/sokmuseer/?museo_id=22009

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
