### ISSUE TITLE
tofu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12143]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tofu](http://www.yso.fi/onto/yso/p12238)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään viittausmuoto "soijajuusto"

**Perustelut ehdotukselle**

"Tofu --, jota joskus kutsutaan myös nimellä soijajuusto --" (https://fi.wikipedia.org/wiki/Tofu)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja Wikidatassa (https://www.wikidata.org/wiki/Q177378) näyttäisi olevan lisää muitakin muotoja: _soijapapujuusto_ suomeksi ja ainakin _bönost_ ja _sojabönsost_ ruotsiksi.

**Comment by mariaforsen** [comment]
Ilman tarkennetta voi olla hämmentävää, koska on myös soijasta tehtyjä juustoja/juustovalmisteita, jotka eivät siis ole tofua. Tarkenteella varmaan ok. 
https://www.greenoption.org/vegprodukter/ost.html

**Comment by fantsby-m** [comment]
En pidä tätä ohjaustermiä tarpeellisena, tofu tunnetaan tofuna jo ihan yleisesti. Juustoa se ei ole.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei lisätä ohjaustermejä.
