### ISSUE TITLE
bunkkerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12142]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[bunkkerit](http://www.yso.fi/onto/yso/p18710)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne (rakennukset) tms.?

**Perustelut ehdotukselle**

Monimerkityksinen: https://www.kielitoimistonsanakirja.fi/#/bunkkeri?searchMode=all Melindassa myös esim. turvallisuusvaatimukset ja sähkömagneettista yhteensopivuutta koskevat vaatimukset : massatavaran varastointi siiloissa, bunkkereissa, säiliöissä ja suppiloissa : standardi

**Ehdottajan organisaatio**

**Comment by vthuhtal** [comment]
Ei kai bunkkerin merkitys muutu käyttötarkoituksen perusteella (asumus, varastotila jne.)?

**Comment by mirmaid** [comment]
^^ Tuo viite ei varmaan rajautuisi pois, vaikka olisikin tarkenne (rakennukset). Ja olisiko se tarpeenkaan?

**Comment by fantsby-m** [comment]
Tarkenne (rakennukset) on hyvä, sulkee pois golfin ja laivan säiliöt.

**Comment by mariaforsen** [comment]
Sv. bunkrar (byggnader) 
https://svenska.se/tre/?sok=bunker&pz=1

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään tarkenne _(rakennukset)_.
