### ISSUE TITLE
kapiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12141]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kapiot](http://www.yso.fi/onto/yso/p23594)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko kapioarkut ohjaustermi?

**Perustelut ehdotukselle**

Ongelma ruotsiksi, tähän asti ollut sv. brudkistor, joka tosin viittaa vain arkkuun. Hemgift ei ole mahdollinen ratkaisu, koska sanastossa on erikseen myötäjäiset=hemgift. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
https://blogs.helsinki.fi/museoaineisto/kapiot/
https://www.kielitoimistonsanakirja.fi/#/kapiot?searchMode=all
https://www.kotus.fi/nyt/kolumnit_artikkelit_ja_esitelmat/kieli-ikkuna_%281996_2010%29/ovatko_kapiot_valmiina

Voiko olla muutakin kuin tekstiilejä?

**Comment by mirmaid** [comment]
Käsittääkseni liinavaatteita ja vaatteita, ainakin pääosin. En tiedä miten säännönmukaisesti kapioarkku oli osa kapioita.

**Comment by mariaforsen** [comment]
Yhdistäminen (käytä myötäjäiset) ei varmaan ole suomen kannalta mielekästä? 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_57ac19362649fbd1df5ddd0440236eac&list_id=1&keyword=kapiot&word=kapiot

"Morsiamen myötäjäisinä uuteen kotiinsa viemiä vaatetavaroita merkitsevällä kapiot-sanalla ei ole vastineita sukukielissä." /MOT Nykysuomen etymologinen sanakirja

Eli luodaan jonkinlainen kuvaava vastine ruotsiksi? "Textilier som hemgift", "brudkistor med textilier" ..tms.? Jos kapioarkut sisältyvät (pitäisi päättää suomeksi että olisiko tämä erillinen termi vai sisältyykö?)

https://sv.wikipedia.org/wiki/Brudkista

**Comment by mirmaid** [comment]
^ Olennaisempaa on varmaan se, että kapioita voidaan käsitellä aiheena ilman, että kapioarkuista puhutaan mitään. Silloin kuvailu ei ole ihan luontevaa jos ruotsiksi viitataan nimenomaan arkkuihin. Ymmärrän kyllä ongelman, ja tätä on käytetty tosi vähän Melindassa, mutta tuntuu ikävältä ajatukselta poistaa termi, joka on suomeksi niin selkeä. On myös MAOssa. Kapiot KÄ myötäjäiset on tottakai mahdollinen, mutta sinne se sitten hukkuu...

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään uusi käsite _kapioarkut_, ohjaustermiksi _kapiokirstut_ ja _kapiot (kapioarkut)_. Käsitteelle _kapiot_ ei muutoksia.

**Comment by mariaforsen** [comment]
Sv. -brudkistor > textilier som hemgift
-brudkistor 
se https://melinda.kansalliskirjasto.fi/F/T8U5133U8296B74EX9KR77BUM3NQFY4PQ6SK2NMCGXXB8F9KI4-02985?func=find-acc&acc_sequence=000323896
https://www.kotus.fi/nyt/kolumnit_artikkelit_ja_esitelmat/kieli-ikkuna_%281996_2010%29/ovatko_kapiot_valmiina
