### ISSUE TITLE
magneettiset myrskyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12146]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[magneettiset myrskyt](http://www.yso.fi/onto/yso/p20877)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi aurinkomyrskyt? Vai erillisenä terminä?

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Aurinkomyrsky

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ohjaustermi mielestäni.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
