### ISSUE TITLE
Kreikkalainen mytologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12147]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kreikkalainen mytologia

**Ehdotettu termi ruotsiksi**

Grekisk mytologi

**Ehdotettu termi englanniksi**

Greek mythology

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Antiikin mytologia termi löytyy YSO:sta. Tiedonhakija toivoo varmasti voivansa erotella Rooman ja Kreikan mytologiset teokset toisistaan. Kuvailussa on toki mahdollista kohdistaa paikka YSO-paikat ontologiaan, mutta aina teos ei kerro maantieteellisesti Rooman valtakunnasta tai Kreikasta. Asiasana ketjututksia on aikaisemmin käytetty. Tässä keskustelua myös: https://github.com/Finto-ehdotus/YSE/issues/5502 Jos Kreikkalainen mytologia hyväksytään, niin myös Roomalainen mytologia https://fi.wikipedia.org/wiki/Roomalainen_mytologia

**Ehdotettu yläkäsite YSOssa (LT)**

 [antiikin mytologia](http://www.yso.fi/onto/yso/p18483)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [germaaninen mytologia](http://www.yso.fi/onto/yso/p37782), [skandinaavinen mytologia](http://www.yso.fi/onto/yso/p20461), [suomalainen mytologia](http://www.yso.fi/onto/yso/p8976)

**Vastaava käsite muussa sanastossa**

 [https://id.loc.gov/authorities/subjects/sh85089396.html](http://Mythology, Greek), [https://fi.wikipedia.org/wiki/Kreikkalainen_mytologia](http://Kreikkalainen mytologia)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ege kıyılarından eski zaman masalları 

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Kreikkalainen mytologia](http://finto.fi/yse/fi/page/Y512147)

**Comment by mirmaid** [comment]
KULAssa on aikanaan ollut ketjut _mytologia - antiikki - Kreikka_ ja _mytologia - antiikki - Rooma_. 

Melindassa 29 ja 8 viitettä. (antiikin mytologia x 922)

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Grekisk%20mytologi
https://id.kb.se/term/sao/Romersk%20mytologi

**Comment by tpalonen** [comment]
_antiikin mytologia_ -käsitettä käytetty muutaman kerran myös Egyptin yhteydessä. Eli pitäisikö ottaa myös _egyptiläinen mytologia_, jos tälle tielle lähdetään? Käytetty 7 kertaa Melindassa, kaikki tosin kaunokirjallisuutta.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kreikkalainen mytologia_ ja _roomalainen mytologia_.

**Comment by mariaforsen** [comment]
Sv. -grekisk mytologi 
-romersk mytologi
