### ISSUE TITLE
tekstiiliarkeologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12155]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tekstiiliarkeologia

**Ehdotettu termi ruotsiksi**

textilarkeologi

**Ehdotettu termi englanniksi**

textile archaeology

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tekstiiliarkeologia on tutkimusala, johon liittyen on myönnetty esimerkiksi dosentuuri Turun yliopistossa. Suomessa on myös tekstiiliarkeologiasta väitelleitä arkeologeja ja aktiivisesti alalla tutkimusta tekeviä ihmisiä ja sitä opetetaan yliopistoissa. Muinaistutkijan tämän syksyn erikoisnumeron aiheena on tektiiliarkeologia (julkaistaan joulukuussa 2023).

**Ehdotettu yläkäsite YSOssa (LT)**

 [tekstiilit](http://www.yso.fi/onto/yso/p13512)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Interdisciplinary approaches to research of North and Central European archaeological textiles

**Ehdottajan organisaatio**

Oulun yliopisto
**Termiehdotus Fintossa:** [tekstiiliarkeologia](http://finto.fi/yse/fi/page/Y512155)

**Comment by mirmaid** [comment]
Ei Melindassa, eikä MAOssa, myös Googlella suomeksi hyvin niukasti. Toisaalta termi on selkeä ja läpinäkyvä.

**Comment by fantsby-m** [comment]
Yläkäsite olisi varmaankin arkeologia eikä ehdotuksessa oleva tekstiilit.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
