### ISSUE TITLE
osallistava johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12158]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[osallistava johtaminen](http://www.yso.fi/onto/yso/p40180)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT osallistava johtajuus?

**Perustelut ehdotukselle**

Ruotsiksi päädyttiin päätermiin "deltagande ledarskap" (käytetympi ruotsiksi). Varmistaisin kuitenkin että vastaava termi suomeksi olisi myös tarkoitus sisällyttää tähän? Ks. esim. https://www.theseus.fi/bitstream/handle/10024/508873/Osallistava%20johtajuus%20hoiva-alalla_tapaustutkimus%20hoiva-alan%20yrityksess%C3%A4_Sari%20kuurne%20ja%20Aleksanteri%20Virta.pdf?sequence=2&isAllowed=y

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Sanastossa on _johtaminen_ ja _johtajuus_. Muilla johtamisen alakäsitteillä ei ole vastaavia ohjaustermejä, jos tämä lisätään, varmaan muitakin mahdollisia olisi (esim. valmentava johtajuus, kestävä johtajuus).

**Comment by mariaforsen** [comment]
Olettaisin kuitenkin että näistä on tarkoitus käyttää osallistava johtaminen-termiä (ei erillisenä uutena terminä)? Sama teema se kuitenkin on, ks. esim. https://www.hrviesti.fi/natiivi/2273/hyva-johtaja-innostaa-osallistumaan

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Katsotaan myös muiden johtamisen alakäsitteiden ohjaustermejä.
