### ISSUE TITLE
suorittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12157]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suorittaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Suorittamismentaliteetille, suorittamisen tyhjälle tunteelle tai ylisuorittamiselle ei ole mitään sanaa sanastossa, vaikka on niin elävä osa kulttuuriamme, että siitä ilmestyy kokonaisia kirjoja. Ks myös esim. https://yle.fi/aihe/artikkeli/2016/10/31/suorittaja-ei-ole-ikina-tyytyvainen-mihinkaan-riittaako-sinulle-riittavan-hyva 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Juha T. Hakala: Suoritusyhteiskunta : oireita ja selviytymiskeinoja  9789523633919 . Olen aiemminkin kaivannut käsitettä, tämä ei ole ensimmäinen kerta.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [suorittaminen](http://finto.fi/yse/fi/page/Y512157)

**Comment by mirmaid** [comment]
_Suorituspaineet_ on sanastossa (hyväksytty vuosi sitten).

**Comment by mariaforsen** [comment]
Sv. presterande on suoriutuminen YSOssa, eli ruotsin kannalta tälle on jo sana, mutta tämä odottaa vielä korjauksia: issue https://github.com/Finto-ehdotus/YSE/issues/10100 

Voisiko meillä mahdollisesti olla tämäntyyppisille suorittamis/suorituskulttuuri tai -yhteiskunta tms. termi? Sv. prestationskultur/samhälle?

**Comment by mirmaid** [comment]
^ Eikö se olisi kuitenkin tosi päällekkäinen tuon _suorituspaineet_-käsitteen kanssa? Voisiko vaikka ohjata jotenkin esim. suorittaminen (suorituspaineet) KÄ suorituspaineet? 

Tuo _suoriutuminen_ on tosiaan vielä kesken, mutta suomeksi tosiaan suorittaminen ja suoriutuminen eivät tarkoita ihan samaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan yllä olevan ehdotuksen mukaisesti.
