### ISSUE TITLE
lestadiolaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12159]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lestadiolaisuus](http://www.yso.fi/onto/yso/p5426)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi myös rauhansanalaisuus

**Perustelut ehdotukselle**

Yksi kolmesta lestadiolaisuuden pääsuuntauksista.
https://fi.wikipedia.org/wiki/Rauhansanalaisuus

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
