### ISSUE TITLE
ideointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12160]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ideointi](http://www.yso.fi/onto/yso/p14566)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko OT aivoriihi?

**Perustelut ehdotukselle**

Englanniksi ja ruotsiksi ollut brainstorming. 
https://fi.wikipedia.org/wiki/Aivoriihi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
No, miksipä ei 🙂

**Comment by AuHo22** [comment]
myös KT ideariihi ja KT aivoriihityöskentely

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
