### ISSUE TITLE
taloudellinen väkivalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12164]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taloudellinen väkivalta

**Ehdotettu termi ruotsiksi**

ekonomiskt våld

**Ehdotettu termi englanniksi**

financial abuse

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Yhä yleisemmin käsitellään tätä aihetta (esim. Googlen ngram viewerillä sen käyttö on monikertaistunut 1980-luvun jälkeen). Sen lisäksi se on jo niin tunnettu, että se on yksi niistä väkivaltamuodoista, joita Naisten linja käsittelee omilla sivuilla (https://naistenlinja.fi/vakivallan-syklisyys-ja-muodot)

**Ehdotettu yläkäsite YSOssa (LT)**

 [väkivalta](http://www.yso.fi/onto/yso/p67)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 pohjoissaame: ekonomalaš veahkaváldi, englanti: economic abuse, englanti: financial violence, englanti: economic violence

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [hengellinen väkivalta](http://www.yso.fi/onto/yso/p29647), [henkinen väkivalta](http://www.yso.fi/onto/yso/p66), [rakenteellinen väkivalta](http://www.yso.fi/onto/yso/p25652)

**Vastaava käsite muussa sanastossa**

 [Wikidata](http://Q5333424), [Yle](https://yle.fi/aihe/t/18-317444)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tieteellisiä julkaisuja

**Ehdottajan organisaatio**

WMFI-AG/Kimberli
**Termiehdotus Fintossa:** [taloudellinen väkivalta](http://finto.fi/yse/fi/page/Y512164)

**Comment by kmakarai** [comment]
Samasta käsitteestä englanniksi:
- [Käsitteen sivu Analysis & Policy Observatoryn sivuilla](https://apo.org.au/subject/37d8f1c7-7f2e-4173-8a11-0e979761eb27)
- [Käsitteen sivu Euroopan tasa-arvoinstituutti EIGEn sivuilla](https://eige.europa.eu/publications-resources/thesaurus/terms/1229)
- [Australian parlamentin pohdintoja ja suositus aiheesta](https://www.aph.gov.au/Parliamentary_Business/Committees/Senate/Legal_and_Constitutional_Affairs/DowryAbuse/Report/b01)
- [Tiedote lakiehdotuksesta aiheena "enhanced domestic abuse" gov.uk:ssa](https://www.gov.uk/government/news/enhanced-domestic-abuse-bill-introduced-to-parliament)
- [Käsitteestä Illinois Legal Aidin sivuilla](https://www.illinoislegalaid.org/legal-information/what-economic-abuse)

Samasta käsitteestä ruotsiksi:
- [Kansanedustajan aloite Ruotsin valtiopäivillä](https://www.riksdagen.se/sv/dokument-och-lagar/dokument/motion/ekonomiskt-vald-mot-kvinnor_HA022070/)
- [Länsstyrelsen Östergötlandin esite siitä, miten päästä taloudellisesta väkivallasta eroon](https://www.lansstyrelsen.se/download/18.792af7217dc2822143d28c/1640095656263/En%2520v%25C3%25A4g%2520ut!%2520Det%2520ekonomiska%2520v%25C3%25A5ldet%2520i%2520n%25C3%25A4ra%2520relationer.pdf)
- [Taloudellinen väkivalta tutuksi –hanke — Projektet Känn det ekonomiska våldet (2021-2024)](https://ensijaturvakotienliitto.fi/violary/kehittamistyo/taloudellinen-vakivalta-tutuksi-hanke-2021-2024/)

Samasta käsitteestä pohjoissaameksi:
- [THL:n turvakoti esite Dorvoruovttus oaččut veahki veahkaváldái dahje dan áitagii lagaš gaskavuođas](https://www.julkari.fi/bitstream/handle/10024/143581/THL_Turvakotien_yleisesite_pohjoissaame.pdf?sequence=1&isAllowed=y)
- [Osana VOlinjen sivua, jossa käsittellään erilaisia väkivaltamuotoja](https://www.volinjen.no/languages/samegiella/)
- [Försäkringskassenin sivu "Dus lea riekti eallit eallima gos ii leat veahkaváldi"](https://www.forsakringskassan.se/information-in-other-languages/nordsamiska/du-har-ratt-till-ett-liv-utan-vald), [saatavilla myös suomeksi](https://www.forsakringskassan.se/information-in-other-languages/finska/du-har-ratt-till-ett-liv-utan-vald)

**Comment by mirmaid** [comment]
Taloudellisella väkivallalla tarkoitetaan tilannetta, jossa tekijä kontrolloi, riistää tai tuhoaa toisen taloudellisia resursseja heikentääkseen hänen taloudellista itsenäisyyttään tai hyötyäkseen itse taloudellisesti. Tyypillisesti taloudellinen väkivalta on parisuhteessa ilmenevä väkivallan muoto, mutta sitä voi esiintyä myös muissa lähisuhteissa kohdistuen esimerkiksi lapseen, vanhempaan tai isovanhempaan. https://ensijaturvakotienliitto.fi/violary/kehittamistyo/taloudellinen-vakivalta-tutuksi-hanke-2021-2024/

Ainakin ohjaustermiksi myös _taloudellinen hyväksikäyttö_, jos otetaan.

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by AuHo22** [comment]
Sitä mietin, voiko käsite kuvata asiaa myös laajempana, yhteisöllisenä ilmiönä, ja esim. seuraavassa on näköjään otettu kaksi eri tarkastelukulmaa: https://www.julkari.fi/bitstream/handle/10024/139150/URN_ISBN_978-952-343-211-6.pdf
Joskin verkosta löytyy lähinnä aineistoa ihmisten välisenä väkivallan muotoja, ei niinkään laajempana ilmiönä.
Ja onko rakenteellinen väkivalta ehkä kuitenkaan oikea RT kuvaamaan kuitenkaan tässä tarkoitettua merkitystä, pikemminkin lähisuhdeväkivalta?
https://www.pesapuu.fi/wp-content/uploads/2021/05/Rakenteellisethaasteet.pdf

**Comment by kmakarai** [comment]
Hyviä huomioita kyllä ja tuo julkarin teksti on loistava lähde. Mielestäni voisimme miettiä YSO:n rakennetta tästä uusiksi tämän asiakirjan pohjalla, kun YSO:sta puuttuu moni noista termeistä ja käsitteistä. Tulee kuitenkin eroja käsitejärjestelmässä eri kielten välissä ja todennäköisesti myös eri oikeusjärjestelmien välissä, vaikka kieli olisi sama. En tiedä miten tällaista mallinnetaan YSO:ssa.

Esimerkiksi englanniksi economic abuse on minun mielestäni selkeästi ihmistenvälistä, mutta tuo economic violence voi olla joko tai. Esim. kun englanninkielisessä Wikipediassa käytetään tuosta kollektiivisestä taloudellisesta väkivallasta termiä [economic violence](https://en.wikipedia.org/wiki/Economic_violence), se viittaa Maailman terveysjärjestön määritelmään: 

> [_Collective violence refers to violence committed by larger groups of individuals and can be subdivided into social, political and economic violence._](https://web.archive.org/web/20041027070233/http://www.who.int/violenceprevention/approach/definition/en/)

Tuo on selkeästi kollektiivinen väkivalta.  Kuitenkin samassa _economic violence_ -artikkelissa myös puhutaan asioista, jotka kuuluvat _[economic abuselle](https://en.wikipedia.org/wiki/Economic_abuse)_. Eri lähteissä myös näkyy, että _economic abuse_ on aina ihmisten välissä, mutta economic violence voi olla joko tai. Minusta silloin kun puhutaan yhteisötasoisesta taloudellisesta väkivallasta (economic violence), rakenteellinen väkivalta on oikea RT kyllä. Kollektiivisen väkivallan käsite taas puuttuu YSO:sta.

**Comment by kmakarai** [comment]
Suomenkielisten yliopistojen eri tietokannoista löytyy taloudellisesta väkivallasta näin paljon osumia. Ensimmäinen luku on "taloudellinen väkivalta" lainausmerkeillä ja toinen taloudelliselle väkivallalle ilman niitä (ei kaikki välttämättä aina liity taloudelliselle väkivallalle): 

- Lapin yliopiston Laudasta:  [23 krt](https://lauda.ulapland.fi/discover?scope=%2F&query=%22taloudellinen+v%C3%A4kivalta%22&submit=), [297 krt](https://lauda.ulapland.fi/discover?scope=%2F&query=taloudellinen+v%C3%A4kivalta&submit=)
- Helsingin yliopiston e-thesis, vain väitöskirjat ja tutkielmat: [4 krt](https://helda.helsinki.fi/search?search=&scope=29bacde1-2a5b-4f5b-82f2-b925ce898000&query=%22taloudellinen%20v%C3%A4kivalta%22), [8 krt ](https://helda.helsinki.fi/search?search=&scope=29bacde1-2a5b-4f5b-82f2-b925ce898000&query=taloudellinen%20v%C3%A4kivalta)
- Tampereen yliopiston Treposta: [32 krt](https://trepo.tuni.fi/discover?query=%22taloudellinen+v%C3%A4kivalta%22), [1143 krt](https://trepo.tuni.fi/discover?scope=%2F&query=taloudellinen+v%C3%A4kivalta&submit=)
- Turun yliopiston UTUpubista: [26 krt](https://www.utupub.fi/discover?query=%22taloudellinen+v%C3%A4kivalta%22), [505 krt](https://www.utupub.fi/discover?scope=%2F&query=taloudellinen+v%C3%A4kivalta&submit=)
- Vaasan yliopiston Osuvasta: 0 krt, [100 krt](https://osuva.uwasa.fi/discover?scope=%2F&query=taloudellinen+v%C3%A4kivalta&submit=)

Ja sitten myös Doriasta ja Finnasta:
- Doria: [2 krt](https://doria.fi/discover?query=%22taloudellinen+v%C3%A4kivalta%22), [418 krt](https://doria.fi/discover?scope=%2F&query=taloudellinen+v%C3%A4kivalta&submit=)
- Finna: [27 krt](https://www.finna.fi/Search/Results?lookfor=%22taloudellinen+v%C3%A4kivalta%22&type=AllFields), [579 krt](https://www.finna.fi/Search/Results?lookfor=taloudellinen+v%C3%A4kivalta&type=AllFields&limit=20&sort=relevance%2Cid+asc)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _taloudellinen väkivalta_, lisätään määritelmä.
