### ISSUE TITLE
eripainokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12166]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eripainokset](http://www.yso.fi/onto/yso/p10805)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään SLM:ään ja YSO:on viittausmuodoksi "ylipainokset"

**Perustelut ehdotukselle**

Kyseistä ilmausta on käytetty useissa eripainoksissa, joten olisi tarpeen saada ohjaus siitä asianmukaiseen asiasanaan/termiin.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Nimitys:ylipainos

**Comment by fantsby-m** [comment]
Jos otetaan, niin tarkenteella: _ylipainokset (eripainokset)_, ei sekoittuisi tuohon Tieteen termipankin merkitykseen?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään tarkenteella.
