### ISSUE TITLE
hengellinen väkivalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12163]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hengellinen väkivalta](http://www.yso.fi/onto/yso/p29647)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

spirital abuse

**Perustelut ehdotukselle**

* abuse on yleisempi termi

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by kmakarai** [comment]
spirital abuse -> spirit**u**al abuse
