### ISSUE TITLE
Novelisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12165]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Novelisaatio

**Ehdotettu termi ruotsiksi**

Novelisering

**Ehdotettu termi englanniksi**

novelization

**Tarkoitusta täsmentävä selite**

Novelisaatio
Olisi tarvetta luoda hakusana/laji: novelisaatio.
Eli kun toinen taidelaji inspiroi kirjoittamaan novelli tai lyhytproosa.
Nyt ilman hakusana on vaikea etsiä ko. kirjallisuus.

**Perustelut ehdotukselle**

kirjallisuuden laji

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

noveli

**Ehdottajan organisaatio**

yksityinen
**Termiehdotus Fintossa:** [Novelisaatio](http://finto.fi/yse/fi/page/Y512165)

**Comment by jtuohini** [comment]
YSO:ssa vanhastaan mm. [**intertekstuaalisuus**](http://www.yso.fi/onto/yso/p17213) ja [**taiteidenvälisyys**](http://www.yso.fi/onto/yso/p4100), joilla on kuvailtu tämäntapaisia ilmiöitä. SLM:ssä taas löytyy mm. [**romaanisovitukset**](http://urn.fi/URN:NBN:fi:au:slm:s379) ja YSO:sta myös [**vaikutushistoria**](http://www.yso.fi/onto/yso/p21324), jolla kuvailla taiteellisten teosten (kirjalliset teokset, maalaukset, sävellykset ym.) vaikutusta varsinkin muihin (taiteellisiin) teoksiin.

Lisäksi RDA-kuvailusäännöissä on erilliset suhdetermit, joilla voidaan ilmaista teosten välinen vaikutussuhde hyvinkin yksilöidysti: **innoituksen perustana**, **jäljitelmän perustana**, **mukaelman perustana (teos)** ja erilliset eri taiteenlajeille (esim. **romaanimukaelman perustana (teos)**), **parodian perustana**, **teoksen perustana** jne. Kenties ensimmäisenä listattu, innoituksen lähteeseen viittaava, voisi ajaa ehdotuksessa tarkoitetun tarpeen?

**Comment by mirmaid** [comment]
Onkohan kyseessä kuitenkin tämä: https://en.wikipedia.org/wiki/Novelization (eli tuo SLM-romaanisovitukset).

**Comment by jtuohini** [comment]
Mutta SLM:n **romaanisovituksethan** on juurikin sama kuin mistä mainittu Wikipedia-artikkeli kertoo eli toisen taidemuodon tarina sovitettuna romaaniksi: "A novelization (or novelisation) is a derivative novel that adapts the story of a work created for another medium, such as a film, TV series, stage play, comic book, or video game."

**Comment by fantsby-m** [comment]
RDAssa myös **[romaanimukaelma teoksesta](http://www.rdaregistry.info/Elements/w/?language=fi#P10130)**, jota Metatietosanastossa vastaa edellä jo mainittu **[romaanimukaelman perustana (teos)](http://urn.fi/URN:NBN:fi:au:mts:m613)**

Ja myös [**romaanimukaelma ekspressiosta**](http://www.rdaregistry.info/Elements/e/?language=fi#P20126), Metatietosanastossa **[romaanimukaelman perustana (ekspressio)](http://urn.fi/URN:NBN:fi:au:mts:m4180)**

**Comment by mariaforsen** [comment]
https://taloudellinenvakivalta.fi/se/om-ekonomiskt-vald/

**Comment by krinay** [comment]
Tieteen termipankki / Kirjallisuudentutkimus (https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:romaanisointi):  

> **romaanisointi**:
> Määritelmä: romaanin kirjoittaminen johonkin toiseen lajiin kuuluvan teoksen pohjalta.
> Selite: Suomennos englannin termille _novelization_. Kustakin _Tähtien sodan_ alkuperäisen trilogian (episodit IV-VI) elokuvasta tehtiin romaanisointi. Donald F. Glutin romaanisointi _Imperiumin vastaiskusta_ ilmestyi 1980.

(SLM ja RDA:n suhdetermit palvelevat tietynlaisia tarpeita, mutta ehkä ehdottaja kaipaa käsitettä nimenomaan asiasanana. Eli jotakin täsmällisempää kuin _intertekstuaalisuus_ ja _taiteidenvälisyys_. En tiedä.)

**Comment by fantsby-m** [comment]
^mutta kun ehdotus perustuu tarpeeseen **löytää** tällaista kirjallisuutta niin ei siihen YSO-asiasana auta, eivät nämä romaanit käsittele "novelisaatiota", vaan ovat sitä. Eli kyse on lajityypistä -> mainittu SLM-termi. Ja myös Kaunossa on termi [romaanisovitukset ](http://www.yso.fi/onto/kauno/p1481).

**Comment by jtuohini** [comment]
Ehdotus siis, että lisätään SLM:ään viittausmuoroiksi _novelisaatiot_, _novelisoinnit_ ja _romaanisaatiot_ (mutta ei romanisointia, joka viittaisi translitterointiin latinalaiselle kirjaimistolle).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _romaanisovitukset_ yllä ehdotetun mukaisesti.

**Comment by mariaforsen** [comment]
Sv. bearbetningar till romaner HT romanbearbetningar
https://finto.fi/slm/fi/page/s379?clang=sv
