### ISSUE TITLE
sysijokisimpukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12162]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sysijokisimpukka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [simpukat](http://www.yso.fi/onto/yso/p1480)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 Unio tumidus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Suomen lajitietokeskus](https://laji.fi/taxon/MX.212397/images), [Wikipedia](https://fi.wikipedia.org/wiki/Sysijokisimpukka), [LCSH (broad match)](https://id.loc.gov/authorities/subjects/sh88021252.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/29184

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [sysijokisimpukka](http://finto.fi/yse/fi/page/Y512162)

**Comment by mariaforsen** [comment]
Sv. spetsig målarmussla https://namnochslaktskap.artfakta.se/taxa/106664/details
