### ISSUE TITLE
rahoitustaloustiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12184]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taloustieteet](http://www.yso.fi/onto/yso/p2849)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Alakäsite: Rahoitustaloustiede, eng. financial economics 

**Perustelut ehdotukselle**

https://www.wikidata.org/wiki/Q2294553
Rahoitustaloustiede keskittyy rahaan/rahoitukseen ja jättää pois reaalitalouden, tämän soveltajia on pörsseissä ja yritysten talousjohdoissa. Ehkä voisi olla kauppatieteiden alla.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Rahoitustaloustiede

Ei Melindassa, rahoitus & taloustieteet n. 200 kertaa samoissa viitteissä.

**Comment by mariaforsen** [comment]
Sv. finansiell ekonomi Myös SAOssa https://id.kb.se/term/sao/Finansiell%20ekonomi
Vakiintunut ruotsiksi. Myös "rahoituksen taloustiede"

https://www.sanakirja.fi/custom/en-sv-fi/finansiell%20ekonomi
https://termipankki.fi/tepa/fi/haku/finansiering
https://www.hanken.fi/sv/sok-till-hanken/magisterutbildning-pa-svenska/olika-huvudamnen/finansiell-ekonomi
https://www.soininvaara.fi/2018/12/03/aallon-taloustieteen-laitos-tahtaa-opetuksen-jattiloikkaan-uusi-englanninkielinen-kandiohjelma-lahjakkaille-opiskelijoille/

**Comment by ilona-x** [comment]
> Myös "rahoituksen taloustiede"

IATE2
fi        rahoituksen taloustiede
sv       finansiell ekonomi
en      financial economics
 
Lähde: IATE 01.08.2023, Euroopan unioni (3572262) https://termipankki.fi/tepa/fi/haku/rahoituksen%20taloustiede

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _rahoitustaloustiede_.

**Comment by xpxaxsxi** [comment]
Kiva juttu että hyväksyttiin, mä ilmoitin tämän ehdotuksen https://finto.fi/fi/ sivuston kautta. Ei sitä joka päivä harrastelijat saa asioita ontologioihin tai sanakirjoihin, kehun itseäni.

**Comment by mirmaid** [comment]
^ Kiitos ehdotuksesta!
