### ISSUE TITLE
fotopletysmografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12185]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fotopletysmografia

**Ehdotettu termi ruotsiksi**

fotopletysmografi

**Ehdotettu termi englanniksi**

photoplethysmography 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH](http://www.yso.fi/onto/mesh/D017156), [U.S. National Library of Medicine](http://id.nlm.nih.gov/mesh/2022/D017156)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-61-4889-2

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [fotopletysmografia](http://finto.fi/yse/fi/page/Y512185)

**Comment by mirmaid** [comment]
Lääketieteen termit:
pletysmografia: eräs tilavuusmittaus | esim. veren määrän muutoksista aiheutuvien (raajan tai koko kehon) tilavuudenmuutosten mittaaminen pletysmografin avulla

fotopletysmografia:  valon kahden aallonpituuden →absorbanssien eroon perustuva mittaustapa, jolla voidaan kajoamattomasti määrittää mm. veren hemoglobiinin happisaturaatio ja valtimon pulssiaallon nopeus

**Comment by mirmaid** [comment]
4 x Melindassa.

**Comment by ilona-x** [comment]
Voisko YSOoon riittää tuo FinMeSHin yläkäsite pletysmografia? Sitä tosin ei ole käytetty Melindassa.🤔

LCSH: Plethysmography http://id.loc.gov/authorities/subjects/sh85103492

**Comment by mariaforsen** [comment]
On selkeä termi ja useampiakin aineistoja Melindassa, joten kannatan hyväksymistä. 
https://mesh.kib.ki.se/term/D017156/photoplethysmography

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
