### ISSUE TITLE
karjankutsut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12186]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[karjankutsut](http://www.yso.fi/onto/yso/p22943)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko kyylaus ohjaustermi? Ja ehkä karjankutsunta?
Linkki nyt tähän https://www.wikidata.org/wiki/Q379288 mutta muunkieliset ovat kulning (ehkä oikeastaan narrow match?)

**Perustelut ehdotukselle**

Ruotsiksi pitää todennäköisesti muuttaa kulning > lockrop (för boskap)
Palautteen perusteella. 

**Ehdottajan organisaatio**

ALLFO

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermit.
