### ISSUE TITLE
lockrop (djurbeteende)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12188]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kutsuhuudot (eläinten käyttäytyminen)?

**Ehdotettu termi ruotsiksi**

lockrop (djurbeteende)

**Ehdotettu termi englanniksi**

call (zoology)?

**Tarkoitusta täsmentävä selite**

https://www.sanakirja.fi/custom/en-sv-fi/lockrop
Lockrop som djur använder för att locka till sig andra av samma art. 

**Perustelut ehdotukselle**

Behövs vid arkivering, innehållsbeskrivning. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [djurläten](http://www.yso.fi/onto/yso/p14137)

**Ehdotetut temaattiset ryhmät**

 [17 Zoologi](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Material som gäller lockrop inom zoologi. 

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lockrop (djurbeteende)](http://finto.fi/yse/fi/page/Y512188)

**Comment by mirmaid** [comment]
Suom. varmaan _kutsuäänet_, mutta onkohan tällaisesta aineistoa? Ehdotuksessa ei ole mainittu julkaisuesimerkkejä. Vaikea myös keksiä tarkennetta, jolla poissuljettaisiin ihmisen tuottamat äänet (joilla houkutellaan eläimiä).

**Comment by mariaforsen** [comment]
Tämäkin oli Feedback från Svenska litteratursällskapet i Finland /Finlands svenska folkmusikinstitut) Heillä ymmärtääkseni myös ääniteaineistoa.

**Comment by mirmaid** [comment]
^ Varmaan niistä ihmisten tuottamista äänistä, mutta arkistoisivatko he tallenteita eläinten äänistä?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kutsuäänet_, ohjaustermiksi _houkutusäänet_.

**Comment by mariaforsen** [comment]
Sv. lockljud HT lockläten
