### ISSUE TITLE
valtiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12189]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[valtiot](http://www.yso.fi/onto/yso/p3215)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään viittausmuoto "valtakunnat"

**Perustelut ehdotukselle**

Kielitoimiston sanakirjan mukaan valtakunta on yhtä kuin "itsenäinen valtio vars. pol. ja alueellisena kokonaisuutena" (https://www.kielitoimistonsanakirja.fi/valtakunta)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. OT riken (stater)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Valtakunta

**Comment by AuHo22** [comment]
valtakunnat (valtiot) KÄ valtiot
ja
valtakunnat (imperiumit) KÄ imperiumit?

esim. https://fi.wikipedia.org/wiki/Luettelo_historiallisista_valtioista

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään Aulin ehdotuksen mukaiset ohjaustermit. Tarkastellaan hierarkiaa.

**Comment by mirmaid** [comment]
^ Ovat kaikki valtioiden alakäsitteet nyt oikeassa paikassa? Palataan ongelmakokouksessa.

**Comment by mirmaid** [comment]
Eli esim. _kolmannet maat_ ovat valtioita, ja sitä kautta julkisyhteisöjä, mutta "kolmas maa" ei ole varsinaisesti ehkä is-a-suhteessa valtion yläkäsitteeseen _julkisyhteisöt_. Samaa ongelmaa on myös muissa julkisyhteisöjen alakäsitteissä. Annetaanko olla?

**Comment by AuHo22** [comment]
Useammatkin valtiot-termin ST:t taitavat olla ns. ihmisen määrittämiä alueita valtioryhmittyminä, ja sitten siirtomaat tai osavaltiot varsinaisten valtioiden osia. Jälkimmäiset lienevät ns. hallintoalueita ja ensimmäiset kai jonkinlaisia ihmisen määrittämiä alueita, mutta hierarkiaa pitäisi sitten aika monilta osin tarkastella uudelleen. Itseäni ei nykyinenkään ratkaisu häiritse.

**Comment by mirmaid** [comment]
^ Nuo esimerkit kyllä varmaan pitäisi siirtää.

**Comment by mariaforsen** [comment]
Kolonier/siirtomaat ja delstater/osavaltiot ovat ainakin ruotsin kannalta nyt väärässä paikassa. Kannatan siirtoa.
