### ISSUE TITLE
ohimoluu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12182]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ohimoluu

**Ehdotettu termi ruotsiksi**

tinningben

**Ehdotettu termi englanniksi**

temporal bone 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kallo](http://www.yso.fi/onto/yso/p12820)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH](http://www.yso.fi/onto/mesh/D013701), [LCSH](http://id.loc.gov/authorities/subjects/sh85133778)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/29398

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [ohimoluu](http://finto.fi/yse/fi/page/Y512182)

**Comment by mirmaid** [comment]
Myös https://helda.helsinki.fi/items/e5eb3f02-5721-47e5-bacb-746c5d48965a
