### ISSUE TITLE
lockrop (till sjöfåglar / till djur / ev. jakt?)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12187]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kutsuäänet, kutsuhuudot, kutsusävelet, hokemat..?

**Ehdotettu termi ruotsiksi**

lockrop (till sjöfåglar / till djur / ev. jakt?)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Lockrop som människan använder för att locka till sig t.ex. fåglar eller hundar. 

**Perustelut ehdotukselle**

Det behövs också svenska termer för andra lockrop än dem som gäller boskap (kulningar, lockrop (boskap))

**Ehdotettu yläkäsite YSOssa (LT)**

 [kommunikation](http://www.yso.fi/onto/yso/p36)

**Ehdotetut temaattiset ryhmät**

 [23 Viltvård. Fiske. Jakt](http://www.yso.fi/onto/yso/p26561), [50 Folktradition. Traditionsforskning. Kulturantropologi. Ockultism](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [kulningar](http://www.yso.fi/onto/yso/p22943)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

T.ex. insamling som arkiveras, som återger hur man lockat på sjöfågel med olika ljud som imiterar sjöfåglarnas lockrop och läten.

**Ehdottajan organisaatio**

Feedback från Svenska litteratursällskapet i Finland /Finlands svenska folkmusikinstitut)
**Termiehdotus Fintossa:** [lockrop (till sjöfåglar / till djur / ev. jakt?)](http://finto.fi/yse/fi/page/Y512187)

**Comment by mirmaid** [comment]
En tiedä yhtään mikä tämä voisi olla suomeksi.

**Comment by mariaforsen** [comment]
Kutsuhuudot+metsästys ainakin käytetty paljon: 
https://www.google.com/search?q=kutsuhuudot+mets%C3%A4stys&rlz=1C1GCEU_enFI883FI883&oq=kutsuhuudot+mets%C3%A4stys&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRigATIHCAIQIRigAdIBCDU0NDVqMGo0qAIAsAIA&sourceid=chrome&ie=UTF-8

https://www.riistainfo.fi/uusi-metsastaja/suomalainen-metsastys/aktiiviset-metsastysmuodot-ilman-koiraa/houkuttelumetsastys/

**Comment by jarmosaarikko** [comment]
> En tiedä yhtään mikä tämä voisi olla suomeksi.

olisiko "**houkutusäänet**"?  Niihin myydään monenlaisia pillejä.  Yleisin varmaan "sorsapilli".
*kts myös myytävät: [houkutuspillit linnuille](https://www.metsovaruste.fi/metsastysmaailma/houkuttelu-ja-naamiointi/houkutuspillit-linnuille/c/19603/) - on myös petoeläimille, suurriistalle jne.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kutsuäänet_, ohjaustermiksi _houkutusäänet_.
