### ISSUE TITLE
yhteisömetsätalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12183]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yhteisömetsätalous

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

community forestry

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [metsätalous](http://www.yso.fi/onto/yso/p1861)

**Ehdotetut temaattiset ryhmät**

 [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2002009922)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-61-4733-8

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [yhteisömetsätalous](http://finto.fi/yse/fi/page/Y512183)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

https://en.wikipedia.org/wiki/Community_forestry

**Comment by AuHo22** [comment]
Tarvitsisiko tämä määritelmän, ettei vahingossakaan sekoittuisi yhteismetsiin tai yhteisöjen harjoittamaan metsätalouteen siinä merkityksessä kuin sitä Suomessa harjoitetaan, ja senkin takia, olisiko vaikkapa muoto yhteisöllinen metsätalous/metsänhoito selkeämpi? Ymmärränkö oikein, että tällä viitataan nimenomaan kehittyvissä maissa ja usein myös alkuperäiskansojen oikeuksia kunnioittavaan metsänhoitoon? Tai kuinka paljon on kyse eri asiasta?
https://www.maailma.net/uutiset/yhteisollinen-metsatalous-tuottaa-tulosta-meksikossa
https://dodo.org/2002/09/29/yhteisollinen-metsatalous-juurtuu-boliviaan/
https://www.theseus.fi/bitstream/handle/10024/91936/Lappalainen_Esa.pdf?sequence=1&isAllowed=y

**Comment by fantsby-m** [comment]
Yhteisömetsätalous näyttää olevan muoto jota tuosta käytetään (myös Melindassa olevien viitteiden julkaisuissa). 
Ks. myös esim. https://www.google.com/search?q="yhteisömetsätalous"

Mutta määritelmä olisi varmaankin tarpeen.

**Comment by mariaforsen** [comment]
"Den närmaste motsvarigheten är byskogsbruk som motsvarar engelskans community  forestry eller community-based forestry (fi. kylämetsätalous). Den exakta termen på finska är så krånglig som paikallisyhteisöpohjainen metsätalous. Mot den bakgrunden är det förståeligt att man vill korta av uttrycket, men innehållet i förkortningen yhteisömetsätalous kan vara svårt att begripa också för en finskspråkig." 
/ https://sprakbruk.fi/artiklar/byskogsbruk/

https://www.skogen.se/glossary/byskogsbruk/
https://www.wwf.se/om-oss/aret-som-gatt/arsoversikt-2019/byskogsbruk-raddar-vaxter-och-djur/

Eli sv. voisi olla byskogsbruk, jos myös yllä mainitut vaihtoehtoiset muodot suomeksi lisätään ohjaustermeiksi? Ja pitäisi tosiaan määritellä..

Vai olisiko **_kylämetsätalous_** tosiaan parempi päätermi? Tämä on **_jo AFOssa_** https://finto.fi/afo/fi/page/p5718

**Comment by AuHo22** [comment]
Kylämetsätalous-termiä kyllä näkyy käytettävän nimenomaan kehitysyhteistyön/luonnonsuojelunkin yhteyksissä, sitä vain mietin, että onko sitten eroa siinä, kuinka pienestä tai suuresta alueesta puhutaan, ehkä "kylä" täytynee ymmärtää metaforisesti?
Paikallisyhteisöpohjainen metsätalous tietenkin kuvaisi asiaa hyvin, mutta toimisi tietenkin myös hyvänä ohjausterminä kylämetsätaloudelle.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Ohjaustermeiksi _kylämetsätalous_ ja _paikallisyhteisöpohjainen metsätalous_. Harkitaan määritelmää.
