### ISSUE TITLE
basilika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12191]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

basilika

**Ehdotettu termi ruotsiksi**

basilika (växt)

**Ehdotettu termi englanniksi**

basil

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käytetty Melindassa yli 40 kertaa pääasiassa 653-kentässä. (Tarve tälle, jotta basilikat rakennuksina eivät missään nimessä sekoittuisi kuvailussa.)

**Ehdotettu yläkäsite YSOssa (LT)**

 [maustekasvit](http://www.yso.fi/onto/yso/p2610), [yrtit](http://www.yso.fi/onto/yso/p2612)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528), [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85012089)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013697750, https://melinda.kansalliskirjasto.fi/byid/013701275, https://melinda.kansalliskirjasto.fi/byid/013977049 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [basilika](http://finto.fi/yse/fi/page/Y512191)

**Comment by jtuohini** [comment]
Ja äsken unohtunut Wikidata-siltaus: https://www.wikidata.org/wiki/Q38859

**Comment by ilona-x** [comment]
Laji.fi [maustebasilika ](https://laji.fi/taxon/MX.5022264) (Ocimum basilicum) https://fi.wikipedia.org/wiki/Maustebasilika

Laji.fi [basilikat (suku)](https://laji.fi/taxon/MX.5009228) (Ocimum) https://fi.wikipedia.org/wiki/Basilikat

**Comment by mirmaid** [comment]
Oisko maustebasilika KT basilika (yrtit)?

**Comment by mariaforsen** [comment]
Eli lat. Ocimum basilicum?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
