### ISSUE TITLE
basilikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12192]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

basilikat

**Ehdotettu termi ruotsiksi**

basilikor (arkitektur)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käytetty Melindassa yli kymmenen kertaa pääasiassa 653-kentässä tai Masa-asiasanana. (Tarve myös, ettei sekoitu samannimiseen yrttiin.)

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552), [37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85012100), [Wikidata](https://www.wikidata.org/wiki/Q163687)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/006095248, https://melinda.kansalliskirjasto.fi/byid/006770988, https://melinda.kansalliskirjasto.fi/byid/001924433 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [basilikat](http://finto.fi/yse/fi/page/Y512192)

**Comment by jtuohini** [comment]
Ja vielä: pitää tulla selväksi, että viitataan basilikaan arkkitehtonisena muotona, ei patriarkaalisiin/paavillisiin basilikoihin (_basilicae maiores_) tai pieniin basilikoihin (_basilicae minores_), jotka ovat kirkkorakennuksille paavin myöntämiä arvoja (vaikka kyseiset rakennukset eivät arkkitehtuuriltaan olisikaan basilikoja).

**Comment by mirmaid** [comment]
Eli _basilikat (arkkitehtuuri)_, vaikka en tiedä poissulkeeko se varmuudella nuo mainitut basilikoiksi nimitetyt kirkkorakennukset?

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12191

**Comment by mariaforsen** [comment]
Sv. basilikor (arkitektur) 
https://id.kb.se/term/sao/Basilikor

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
