### ISSUE TITLE
lipeäkala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12198]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lipeäkala

**Ehdotettu termi ruotsiksi**

lutfisk

**Ehdotettu termi englanniksi**

lutefisk

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ilman tarkkaa asiasanaa tulee kuvailusta helposti sekavaa, ja nytkin on lipeäkalaa käsittelevässä aineistossa asiasanana esim. "lipeä", vaikka aineisto ei lipeää käsittelisikään.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kalaruoat](http://www.yso.fi/onto/yso/p6498)

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

 lipiäkala, livekala

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2004003315), [Wikidata](https://www.wikidata.org/wiki/Q890197)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013504621, https://melinda.kansalliskirjasto.fi/byid/013579504, https://melinda.kansalliskirjasto.fi/byid/009080334 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [lipeäkala](http://finto.fi/yse/fi/page/Y512198)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
