### ISSUE TITLE
mysteerit (riitit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12194]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mysteerit (riitit)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://www.kielitoimistonsanakirja.fi/#/mysteeri?searchMode=all

**Perustelut ehdotukselle**

Vrt. mysteerit (selittämättömät). Nämä merkitykset ovat nyt sekaisin Melindassa (mysteerit vapaana terminä)

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 mysteeriot 

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The religious context of early Christianity : a guide to Graeco-Roman religions

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [mysteerit (riitit)](http://finto.fi/yse/fi/page/Y512194)

**Comment by jtuohini** [comment]
RT-suhteeksi varmaankin [**mysteeriuskonnot**](http://www.yso.fi/onto/yso/p12285)?

**Comment by mirmaid** [comment]
Aamenesta öylättiin -sanastossa monimerkityksinen: https://evl.fi/sanasto/mysteeri/
_Mysteeri (kreik. mysterion, lat. mysterium) tarkoittaa salaisuutta sekä salaperäistä tai arvoituksellista asiaa, tapahtumaa tai toimitusta. Kristinuskossa on käytetty muun muassa ehtoollisesta nimitystä mysteeri (ehtoollisen mysteeri), koska emme voi ymmärtää ehtoollista loppuun asti, mutta voimme ottaa sen uskossa vastaan. Sanalla voidaan tarkoittaa myös keskiaikaista hengellistä näytelmää._

Teologian asiasanastossa ei ollenkaan.

Entä vain KÄ riitit?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermiksi.
