### ISSUE TITLE
aktivkort

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12197]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aktivkort](http://www.yso.fi/onto/yso/p10777)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaihdetaan YK?

**Perustelut ehdotukselle**

Ks. tietokorttien alakäsitteet, nämä ovat ainakin ruotsin kannalta väärässä paikassa, eivät siis ole eräänlaisia "inspelningar" 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Ehkä YK tekniset objektit (fyysiset objektit)?
