### ISSUE TITLE
mysteerit (selittämättömät tapaukset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12193]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

mysteerit (selittämättömät tapaukset)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

mysteries

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Mysteeri_(t%C3%A4smennyssivu)

**Perustelut ehdotukselle**

Vrt. mysteerit (riitit). Nämä merkitykset ovat nyt sekaisin Melindassa (mysteerit vapaana terminä)

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Edgar Allan Poen aivopähkinät
Maailman salaperäisin kirja ja muita historian mysteerejä 
The seventy great mysteries of the natural world : unlocking the secrets of our planet 

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [mysteerit (selittämättömät tapaukset)](http://finto.fi/yse/fi/page/Y512193)

**Comment by AuHo22** [comment]
Mysteerit esimerkkien 1. merkityksessä tarkoittanee myös arvoitusten ratkaisemista. 
Nykyisin YSO arvoitukset ryhmässä 50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi: kuitenkin sen ST kuva-arvoitukset ryhmässä: 98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt? Näitä linjauksia voisi myös miettiä uudelleen? https://fi.wikipedia.org/wiki/Arvoitus

**Comment by mirmaid** [comment]
^ Olisiko siis mysteerit (arvoitukset) KÄ arvoitukset?

**Comment by mariaforsen** [comment]
Arvoitukset on nyt sv. gåtor, eli ei ole sama asia eikä sellaista ohjausta voi oikein ruotsiksi tehdä (paitsi ehkä Poe-kirjan kohdalla voisi puhua gåtor-sanasta, jos on jotain ratkaistavia "aivopähkinöitä") 

Siis arvoituksen ykkösmerkityksestä https://www.kielitoimistonsanakirja.fi/#/arvoitus?searchMode=all käytetään kyllä gåtor, mutta nämä ovat tosiaan eri asioita. Mysteerit (selittämättömät tapaukset) olisi hyvä olla erikseen (sv. mysterier) ja arvoitukset ykkösmerkityksessä ("ratkaistavaksi asetettu, tav. vertauskuvallinen ajatustehtävä" =sv. gåtor) erikseen.

Samoin varmaan englanniksi: arvoitukset=riddles ja mysteerit=mysteries?
https://www.sanakirja.fi/custom/en-sv-fi/arvoitus

**Comment by mirmaid** [comment]
Sanastossa on myös _selittämättömät ilmiöt_.

**Comment by krinay** [comment]
YSOn _arvoitukset_ on myös suomeksi eri asia kuin mysteerit. Se kannattaisi pitää ennallaan, siis kokonaan erillään mysteereistä. (Kuva-arvoituksillekin voisi lisätä kansanperinteen ryhmän 50.)

Riittäisikö lisäksi tämä: 
mysteerit (selittämättömät tapaukset) KÄ selittämättömät ilmiöt, salaisuudet yms.
(lisäksi, jos tuntuu olevan tarvetta: mysteerit (arvoitukset) KÄ selittämättömät ilmiöt, salaisuudet jne.)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään yllä esitetty ehdotus.
