### ISSUE TITLE
Gazan sota / Hamasin hyökkäys Israeliin 2023

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12199]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Gazan sota / Hamasin hyökkäys Israeliin 2023

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan sisällönkuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sodat](http://www.yso.fi/onto/yso/p1271)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Hamasin_hy%C3%B6kk%C3%A4ys_Israeliin_2023)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Uutisartikkelit

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Gazan sota / Hamasin hyökkäys Israeliin 2023](http://finto.fi/yse/fi/page/Y512199)

**Comment by jtuohini** [comment]
Ei ainakaan pelkkä _**Gazan sota**_ ilman vuotta; vrt. LCSH:n asiasanat [**Gaza War, 2008-2009**](http://id.loc.gov/authorities/subjects/sh2009004478) ja [**Gaza War, 2014**](http://id.loc.gov/authorities/subjects/sh2016001997).

**Comment by mirmaid** [comment]
Gazan sota (2023)?

**Comment by vthuhtal** [comment]
Gazan sota (2023-)?

Yläkäsitteenä varmaan kuitenkin "Lähi-idän kriisi"

**Comment by jtuohini** [comment]
Yläkäsitteiksi ehkä kuitenkin sekä **Lähi-idän kriisi** että **sodat**, koska osa osa edellistä ja samalla on yksi tapaus jälkimmäisistä. Ja rohkenemmeko jo ennustaa, että tämä sota jatkuu vuonna 2024 (ellei YSO-kokous vasta siinä vaiheessa tätä sanastoasiaa päätä)?

**Comment by AuHo22** [comment]
Voisi harkita myös LT-suhteen rakentamista intifada-termiin, jolla on myös yleiskielinen merkityksensä, mutta määritelmällisesti linkittyy Lähi-idän kriisiin? LC.ssä myös vuosilukutarkentein.

**Comment by mariaforsen** [comment]
Sv. kriget mellan Israel och Hamas (2023-) HT kriget mellan Hamas och Israel, Gazakriget (2023-), kriget i Gaza (2023-)..?
https://svenska.yle.fi/t/18-354470
https://www.svt.se/nyheter/utrikes/hamas-attack-mot-israel
https://abounderrattelser.fi/manskliga-rattigheter-och-internationell-ratt-bor-respekteras-aa-lektor-efterlyser-vapenvila-i-kriget-mellan-israel-och-hamas/

**Comment by mirmaid** [comment]
Toivotaan ettei yhdysmerkkiä tarvita.

**Comment by fantsby-m** [comment]
https://www.britannica.com/event/Israel-Hamas-War-of-2023

**Comment by annamarj** [comment]
Minäkin kannattaisin tuota   "Israelin ja Hamasin sota 2023" päätermiksi. (Näkökohtina nekin, että tapahtumia on miehitetyllä Länsirannalla, Itä-Jerusalemissa ja Libanonin rajalla. Hamas ei hyökännyt Israeliin yksin eikä ole yksin sodan osapuolena, mutta jotain yksinkertaistuksia tähän joka tapauksessa tarvitaan, ja onhan se nyt tulitaukosopimuksen osapuolenakin selkeä.)

**Comment by mirmaid** [comment]
Näköjään MTV:llä ainakin, https://www.mtvuutiset.fi/aihe/israelin-ja-hamasin-sota/8795292. Ylellä Gazan sota, https://yle.fi/uutiset/18-354470.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _Israelin ja Hamasin sota (2023)_.
