### ISSUE TITLE
immunosuppressio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12195]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

immunosuppressio

**Ehdotettu termi ruotsiksi**

immunosuppression

**Ehdotettu termi englanniksi**

immunosuppression

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. 13 kertaa Melindassa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [TERO](http://www.yso.fi/onto/tero/D007165), [LCSH](http://id.loc.gov/authorities/subjects/sh85064588)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-61-4788-8

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [immunosuppressio](http://finto.fi/yse/fi/page/Y512195)

**Comment by mirmaid** [comment]
MeSH: [immunosuppressiohoito](http://www.yso.fi/onto/mesh/D007165)

**Comment by fantsby-m** [comment]
Immunosuppressiohoidosta ei ole tuossa teoksessa kyse.

**Comment by mariaforsen** [comment]
Sv. immunsuppression HT immunhämning 
Nationalencyklopedin: "immunsuppression, immunhämning, nedsättning av immunsystemets funktion som följd av medicinsk behandling med immunsuppressiva läkemedel eller med strålning"
vrt. https://mesh.kib.ki.se/term/D007108/immune-tolerance
https://sv.wikipedia.org/wiki/Immunsuppression

**Comment by mirmaid** [comment]
Tässä väitöskirjassa tosiaan kyse ei ole hoidon aiheuttamasta immunosuppressiosta: _Vaikka ihomelanooma on erityisen vahvasti immuunipuolustusta aktivoiva syöpä, immuunijärjestelmä ei kuitenkaan usein pysty estämään melanooman kehittymistä ja etenemistä. Tämä on seurausta kasvaimen mikroympäristön muuttumisesta immunosuppressiiviseksi, eli immuunijärjestelmää heikentäväksi..._

**Comment by mirmaid** [comment]
Lääketieteen termit: immunosuppressio: immuunivasteen heikentäminen | 1. immuunivasteen heikentäminen (siirteen suojelemiseksi) mm. lääkkeillä, antilymfosyyttiseerumilla tai säteilyn avulla; 2. infektion (esim. immuunikadon) tai muun tekijän aiheuttama immuunivasteen heikkeneminen

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mirmaid** [comment]
Myös https://helda.helsinki.fi/items/c98327ff-17d7-4127-82dd-5b8599a79cfa
