### ISSUE TITLE
saamenkäsityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12200]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

saamenkäsityö

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Saamenkielinen sana duodji ohjaa tällä hetkellä vain käsityö-sanaan, ja suorana käännöksenä se sitä tarkoittaakin, mutta kun suomeksi puhutaan duodjista eli saamenkäsityöstä sillä tarkoitetaan paljon spesifimpää asiaa, jonka kuvaamiseksi käsityö-termi ei ole riittävä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 duodji

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/luc.994809852806246?sid=3212156811

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [saamenkäsityö](http://finto.fi/yse/fi/page/Y512200)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12049
