### ISSUE TITLE
kolmiportainen tuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12207]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kolmiportainen tuki](http://www.yso.fi/onto/yso/p28718)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kolmitasoinen tuki

**Perustelut ehdotukselle**

Varhaiskasvatuksen kolmitasoinen tuki kirjattiin varhaiskasvatuslakiin (540/2018, §15 a) ja uudistettu laki astui voimaan 2022 elokuun alussa. 

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Entä viittausmuodoksi _kolmiportainen tuen malli_ ja kielellisesti vielä oikeampi _kolmiportaisen tuen malli_ (http://www.lukimat.fi/lukimat-oppimisen-arviointi/tietopalvelu/taustaa/kolmiportainen-tuen-malli)?

**Comment by mirmaid** [comment]
Kaikki ovat ok ohjaustermeiksi, päätermiä en lähtisi muuttamaan tässä vaiheessa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ohjaustermit.
