### ISSUE TITLE
kellot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12208]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kellot](http://www.yso.fi/onto/yso/p3229)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "ajannäyttäjät"

**Perustelut ehdotukselle**

Nimitystä käytetty suomalaisessa lainsäädännössä viittaamaan kelloihin (https://finlex.fi/fi/laki/alkup/1999/19990115)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ajann%C3%A4ytt%C3%A4j%C3%A4 🌸

**Comment by YSO-kokous** [comment]
**Päätös**

Ei lisätä ohjaustermiä.

**Comment by jtuohini** [comment]
Eli viittausmuotoa ajanosoittimet (kellot) KÄ kellot ei lisätä sanastoon? (Kysehän ei ollut uudesta asiasanaehdotuksesta.)

**Comment by mirmaid** [comment]
Ryhmä ei puoltanut tämän ohjaustermin lisäämistä.
