### ISSUE TITLE
snapsvisor

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12236]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

**Ehdotettu termi ruotsiksi**

snapsvisor

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Wikipedia: Snapsvisor, supvisor, brännvinsvisor eller nubbevisor är moderna skålvisor, ämnade att sjungas direkt innan ett middagssällskap utbringar nästa skål, och dricker snapsen. Snapsvisorna härstammar från 1800-talet, med anor i den äldre traditionen av dryckesvisor. Snapsvisor sjungs gärna vid kräftskivor, studentikosa fester samt vid jul- och midsommarfirande.

Snapsvisan i snäv mening är inte bara typiskt svensk, utan unikt svensk. Det är bara i Sverige och i svenska Finland som man fortsätter att skapa och sjunga snapsvisor enligt den modell som blivit så vanlig: en känd melodi med nya ord som passar till snapsarnas numeriska ordning. En av förutsättningarna för snapsvisans fortlevnad har varit det nära sambandet med svensk matkultur, inte minst smörgåsbordet.

**Perustelut ehdotukselle**

Det nu närmast tillgängliga ämnesordet "dryckesvisor" för idag tankarna till en äldre tradition där visorna man sjöng inte hade samma specifika funktion som dagens snapsvisor har.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musik](http://www.yso.fi/onto/yso/p26571), [50 Folktradition. Traditionsforskning. Kulturantropologi. Ockultism](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](http://Snapsvisa)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

I SLS arkiv finns ett 20-tal samlingar som upptar material om Finlandssvenska Rimakademins tävlingar i nyskrivna snapsvisor: https://sls.finna.fi/Search/Results?lookfor=T%C3%A4vlingar+i+nyskrivna+snapsvisor&type=AllFields&limit=50&sort=relevance%2Cid+asc. Det digitala materialet i samlingarna kommer nu att föras in i arkivets nya databas som endast godkänner ämnesord ur ALLFO eller KOKO.

**Ehdottajan organisaatio**

Svenska litteratursällskapet i Finland, SLS arkiv
**Termiehdotus Fintossa:** [snapsvisor](http://finto.fi/yse/fi/page/Y512236)

**Comment by mirmaid** [comment]
fi. snapsilaulut

Muutama viite Melindassa ruotsiksi.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. HT snapssånger
