### ISSUE TITLE
FIP

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12252]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[FIP](http://www.yso.fi/onto/yso/p16211)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

voisiko poistaa?

**Perustelut ehdotukselle**

vain yksi viite Melindassa:
v. 1989 julkaistu FIP - Fluorescence Induction Program : user’s manual   https://melinda.kansalliskirjasto.fi/byid/000682709

**Ehdottajan organisaatio**

kk/il

**Comment by tpalonen** [comment]
Tässä myös sekaannuksen vaara. Vrt. https://www.wikidata.org/wiki/Q9692 tai https://www.wikidata.org/wiki/Q961891 tai https://www.wikidata.org/wiki/Q204288

**Comment by jarmosaarikko** [comment]
owl:deprecated true ;
skos:note "FIP - Fluorescence Induction Program"@en ;
dc:source  <http://urn.fi/URN:NBN:fi:bib:me:I00068270900> ;
