### ISSUE TITLE
munuaiskeränen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12258]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

munuaiskeränen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

väitös

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/9db65351-ca81-4a6f-a89b-bea2fe93d6cb

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [munuaiskeränen](http://finto.fi/yse/fi/page/Y512258)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D007678

**Comment by mariaforsen** [comment]
Sv. njurglomerulus HT njurglomeruli https://mesh.kib.ki.se/term/D007678/kidney-glomerulus
