### ISSUE TITLE
LOG

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12259]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[LOG](http://www.yso.fi/onto/yso/p20219)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan tai tarkennetaan?

**Perustelut ehdotukselle**

Melindassa 3 viitettä, mutta näissä kaikissa ei todennäköisesti ole kyse samasta ohjelmasta:
1988 : Kallioreikätutkimusten tulosten käsittely- ja tulkintaohjelma LOG
1989 : Computability, complexity, logic
2007 : LogDeveloper : |b loppuraportti

**Ehdottajan organisaatio**

kk/il

**Comment by jarmosaarikko** [comment]
Ehdotan, että deprekoidaan ja ohjataan liikenne tämän yläkäsitteeseen "tietokoneohjelmat".  
Lisäksi tulevaisuutta ajatelleen voisi olla hyvä lisätä deprekoituun käsitteeseen huomautus ja lähde: 
- skos:note  "Kallioreikätutkimusten tulosten käsittely- ja tulkintaohjelma LOG"@fi 
- dc:source http://urn.fi/URN:NBN:fi:bib:me:I00064094600
