### ISSUE TITLE
GWB

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12251]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[GWB](http://www.yso.fi/onto/yso/p20191)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

voisiko poistaa?

**Perustelut ehdotukselle**

vain yksi viite Melindassa:
Geometric WorkBench version 1.0 programmer’s guide https://melinda.kansalliskirjasto.fi/byid/000651120

**Ehdottajan organisaatio**

kk/il

**Comment by tpalonen** [comment]
Tässä myös sekaannuksen vaara. Vrt. https://www.wikidata.org/wiki/Q5598005 ja https://www.wikidata.org/wiki/Q125821. Ja ennen kaikkea: https://www.wikidata.org/wiki/Q207
