### ISSUE TITLE
Contram

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12254]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Contram](http://www.yso.fi/onto/yso/p16222)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan

**Perustelut ehdotukselle**

Käytetty kerran Melindassa, vuonna 1992.
https://melinda.kansalliskirjasto.fi/byid/000716206

**Ehdottajan organisaatio**

Finto / Tuomas

**Comment by tpalonen** [comment]
Contram on myös mm. yritys Italiassa. https://it.wikipedia.org/wiki/Contram
