### ISSUE TITLE
hyponatremia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12267]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hyponatremia

**Ehdotettu termi ruotsiksi**

hyponatremi

**Ehdotettu termi englanniksi**

hyponatremia 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 25

**Ehdotettu yläkäsite YSOssa (LT)**

 [aineenvaihduntahäiriöt](http://www.yso.fi/onto/yso/p6239)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D007010), [Wikipedia](https://fi.wikipedia.org/wiki/Hyponatremia), [LCSH](http://id.loc.gov/authorities/subjects/sh85063797)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Electrolyte disturbances and intravenous fluid therapy in acutely ill children http://urn.fi/urn:isbn:9789526236483

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [hyponatremia](http://finto.fi/yse/fi/page/Y512267)

**Comment by mariaforsen** [comment]
Sv. hyponatremi HT hyponatriemi https://www.fass.se/LIF/wordlist?page=H
