### ISSUE TITLE
ASB

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12262]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ASB](http://www.yso.fi/onto/yso/p9304)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tarkennetaan tai poistetaan?

**Perustelut ehdotukselle**

Melindassa vain yksi viite:
ASB, survo-ohjelmistoon perustuva aikasarjojen seurantaohjelma

Lisäksi lyhenteellä monia merkityksiä https://en.wikipedia.org/wiki/ASB

**Ehdottajan organisaatio**

kk/il

**Comment by jarmosaarikko** [comment]
owl:deprecated true ;
  dc:isReplacedBy yso:p26592 .
  skos:note "ASB, survo-ohjelmistoon perustuva aikasarjojen seurantaohjelma"@fi ;
