### ISSUE TITLE
Google-dokumentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12266]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Google-dokumentit](http://www.yso.fi/onto/yso/p25240)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Google Docs? Onko nykyinen termi tarpeeksi selkeä? Tällä tarkoitetaan varmaan kuitenkin Google docs-ohjelma, eikä tällä tehtyjä dokumentteja?

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Google_Docs
https://www.google.com/intl/fi/docs/about/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Varmaan kannattaa vaihtaa, vaikka on tuota suomennettua nimeä jonkun verran YSOn ulkopuolellakin käytetty 🙂.

**Comment by mariaforsen** [comment]
Sv. Google Dokument HT Google Docs
applikationen Google Dokument
https://www.pcforalla.se/article/1722166/google-drive-dokument-kalkylark-presentationer.html
