### ISSUE TITLE
ACR

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12264]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ACR](http://www.yso.fi/onto/yso/p8615)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan tai tarkennetaan?

**Perustelut ehdotukselle**

Melindassa 2 viitettä, joista uudemmassa on varmasti kyse eri asiasta, kun julkaisuvuodet ovat 1989 ja 2008
**Ehdottajan organisaatio**

kk/il

**Comment by jarmosaarikko** [comment]
viittaisiko kuitenkin tähän: https://melinda.kansalliskirjasto.fi/byid/000682043 ?
- The ACR-program for automatic finite element model generation for part through cracks / Mikko S. Leinonen, Timo P. J. Mikkola.

Lyhtenteelle löytyy hetkessä kymmenkunta eri merkitystä englanniksi, joten tarkenne olisi välttämätön, mutta mieluummin
deprekoidaan pois.

**Comment by ilona-x** [comment]
> viittaisiko kuitenkin tähän: https://melinda.kansalliskirjasto.fi/byid/000682043 ?
> 
>     * The ACR-program for automatic finite element model generation for part through cracks / Mikko S. Leinonen, Timo P. J. Mikkola.

Juu, varmasti tuon perusteella termi on otettu aikanaan YSAan. Tuossa ehdotuksessa olin muotoillut asian huonosti ja muokkasin sitä, eli tarkoitin, että tuo v. 1989 ACR on varmasti eri asia kuin tuossa toisessa v. 2008 julkaistussa viitteessä, jossa on käytetty tätä samaa YSO-termiä ACR.
