### ISSUE TITLE
BEEF

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12261]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[BEEF](http://www.yso.fi/onto/yso/p9483)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan tai tarkennetaan?

**Perustelut ehdotukselle**

Melindassa 2 viitettä (saman julkaisun 2 painosta) julkaisuvuodet 1990-1991
BEEF reference manual : a programmer's guide to the BEEF frame system 

**Ehdottajan organisaatio**

kk/il

**Comment by jarmosaarikko** [comment]
owl:deprecated true ;
dc:source http://urn.fi/URN:NBN:fi:bib:me:I00068299100 ;
