### ISSUE TITLE
kohoaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12277]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kohoaminen](http://www.yso.fi/onto/yso/p25467)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa tai mahdollisesti poistettavissa?

**Perustelut ehdotukselle**

Mihin oikeastaan viittaa? Ruotsiksi (ja varmaan englanniksikin) eri mahdollisia vastineita, ks. esim. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_eda51c44497eaf94cf38f0c3eeb885b6&list_id=1&keyword=kohota&word=kohota Muutama viite Melindassa. 

**Ehdottajan organisaatio**

ALLFO

**Comment by vthuhtal** [comment]
"maankohoaminen" löytyy jo YSOsta...

**Comment by mirmaid** [comment]
Vain 9 viitettä Melindassa (otettu sanastoon 2011). Yksi näistä maankohoamista, muuten erilaisten "tasojen" noususta (esim. elintaso, koulutustaso) tai merenpinnan tai jonkin pitoisuuden noususta.

**Comment by mariaforsen** [comment]
Sv-vastine nyt stigning (vain yksi monesta mahdollisesta). Jos kyseessä elin- tai koulutustaso niin oikeampi voisi olla höjning. Mutta vaatii tosiaan jonkinlaista määritelmää/rajausta.

**Comment by ilona-x** [comment]
> Vain 9 viitettä Melindassa (otettu sanastoon 2011)

Oliskohan tässä helpoin ratkaisu poistaa termi, kun käyttö on ollut noin vähäistä. 🤔 6 x artikkeliaineistoissa ja 3 x  muissa aineistoissa.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan.
