### ISSUE TITLE
GIMMS

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12279]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[GIMMS](http://www.yso.fi/onto/yso/p16601)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan.

**Perustelut ehdotukselle**

Vain yksi Melinda-hitti, vuodelta 1989.
https://melinda.kansalliskirjasto.fi/byid/000642170

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Ei poisteta.
