### ISSUE TITLE
sinhalan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12275]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sinhalan kieli](http://www.yso.fi/onto/yso/p25434)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT sinhali

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Sinhali

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
sinhalin kieli
