### ISSUE TITLE
kieltoilmaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12271]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kieltoilmaukset](http://www.yso.fi/onto/yso/p12335)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "negerande uttryck"

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Käytetty mm. opinnäytetyön otsikossa: [Negerande uttryck i Veijo Meris Kersantin poika och deras återgivning i den svenska översättningen av Bertel Kihlman](https://melinda.kansalliskirjasto.fi/byid/002025743).

**Comment by mariaforsen** [comment]
Ohjaustermi lisätty ruotsiksi.
