### ISSUE TITLE
akuutti munuaisvaurio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12274]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

akuutti munuaisvaurio

**Ehdotettu termi ruotsiksi**

akut njurskada

**Ehdotettu termi englanniksi**

acute kidney injury

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 10

**Ehdotettu yläkäsite YSOssa (LT)**

 [munuaistaudit](http://www.yso.fi/onto/yso/p9826), [munuaisten vajaatoiminta](http://www.yso.fi/onto/yso/p11061)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D058186), [Wikipedia](https://fi.wikipedia.org/wiki/Akuutti_munuaisvaurio)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Inflammation and septic acute kidney injury http://urn.fi/URN:ISBN:978-951-51-8918-9

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [akuutti munuaisvaurio](http://finto.fi/yse/fi/page/Y512274)

**Comment by mariaforsen** [comment]
Sv. akut njurskada HT akut njursvikt, akut njurinsufficiens 
https://mesh.kib.ki.se/term/D058186/acute-kidney-injury
