### ISSUE TITLE
erikoistumisopinnot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12276]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[erikoistumisopinnot](http://www.yso.fi/onto/yso/p25458)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT erikoistumiskoulutus?

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/erikoistumisopinnot

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
