### ISSUE TITLE
historialliset kertomukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12273]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[historialliset kertomukset](http://www.yso.fi/onto/yso/p40092)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan ja mahdollisesti täsmennetään eroa käsitteeseen historialliset romaanit.

**Perustelut ehdotukselle**

Ymmärtääkseni historiallinen kertomus voi olla joko faktaa tai fiktiota. Onko erona siis kertomuksen pituus? Eli historiallinen kertomus on lyhempi kuin romaanin mittainen kertomus? Historiallisten romaanien ohjaustermeinä on tällä hetkellä historical fiction (en) ja historisk fiktion (sv).
Vrt. myös YSOsta löytyvät: kehityskertomukset ja kehitysromaanit sekä rakkauskertomukset ja rakkausromaanit.

Pitäisikö eroa täsmentää jollakin tavalla? Mielestäni se olisi suotavaa. Olen tuskaillut englannin käännöksen kanssa. "Historical stories" ei minusta erota tätä riittävästi "historical novels"-käsitteestä. 
Toisaalta: jos kukaan muu ei koe tätä ongelmaksi niin ei kai siinä.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Keskustelua käyty myös täällä: https://github.com/Finto-ehdotus/YSE/issues/11055

**Comment by tpalonen** [comment]
Ehkä jokin huomautus voisi olla hyvä? Esim. "Jokin muu kuin romaani, esimerkiksi romaania lyhyempi kertomus." tms? Voiko historiallinen kertomus olla faktaa?

Ja pitäisikö tälläkin käsitteellä olla ohjaustermit historical fiction, historisk fiktion jne?

**Comment by mariaforsen** [comment]
Ohjauksena on jo historisk fiktion (romaner) ANV romaner ..siinä tapauksessa voisi lisätä historisk fiktion (berättelser) ANV berättelser
Historiallinen fiktio-ohjaus puuttuu kyllä kokonaan suomeksi.

**Comment by AuHo22** [comment]
SLM: historialliset novellit + määritelmä: Käytetään teoksista, jotka tekijä on sijoittanut historialliseen aikaan.

**Comment by mirmaid** [comment]
Ks. tämän ja muutamien muiden historialliset-alkuisten termien huomautukset.

**Comment by AuHo22** [comment]
Jonkin verran näkee käytettävän englanniksi muotoa historical fiction short stories (?)

**Comment by mirmaid** [comment]
SLM:ssä nyt siis historialliset kertomukset, KT historialliset novellit, käyttöhuomautus: Käytetään teoksista, jotka tekijä on sijoittanut historialliseen aikaan.

Historialliset novellit ei löydy YSOsta edes ohjausterminä. SLM:ssä huomautukset vielä käsittelyssä.

**Comment by mariaforsen** [comment]
Olisiko sama termi YSOssakin hyvä? Ei varmaan ole yhtä paljoa aineistoa, mutta jonkin verran esim. kirjallisuudentutkimusta?

SAOgf:ssa historiska skildringar: https://id.kb.se/term/saogf/Historiska%20skildringar

**Comment by YSO-kokous** [comment]
Lisätään seuraava ohjaustermi:
historialliset novellit KÄYTÄ historialliset kertomukset
