### ISSUE TITLE
flebografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12284]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[flebografia](http://www.yso.fi/onto/yso/p16751)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Venografia ohjaustermiksi (tai käytettäväksi termiksi).

**Perustelut ehdotukselle**

Termit flebografia ja venografia vaihtelevat. Flebografia tuo enemmän hittejä suomen kielellä hakiessa. MESHissä käytettävä termi on flebografia, ohjausterminä venografia:
http://www.yso.fi/onto/mesh/D010690 
LCSH:ssa sekä phlebography että venography ovat ohjaustermejä:
https://id.loc.gov/authorities/subjects/sh85142548.html
HUS preferoi termiä venografia: https://www.hus.fi/sites/default/files/2021-03/laskimoiden-varjoainetutkimus.pdf
Wikipediassa (en) tämä on venography:
https://en.wikipedia.org/wiki/Venography

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Lisäsin jo enkun ohjaustermiksi venography

**Comment by mariaforsen** [comment]
Kannatan ohjausterminä.

**Comment by mirmaid** [comment]
Lääketieteen termeissä on molemmat (sama selitys). Voisi lisätä myös muodot laskimoiden varjoainekuvaus ja laskimoiden varjoainetutkimus.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään ehdotetut ohjaustermit.
