### ISSUE TITLE
sääri/sääret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12289]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sääri/sääret

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

---

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH](http://www.yso.fi/onto/mesh/D007866)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/items/00fc47d8-c6fb-46d5-a5ad-f1095cfae3f0

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [sääri/sääret](http://finto.fi/yse/fi/page/Y512289)

**Comment by mirmaid** [comment]
Melindassa muutamia kertoja sekä yksikössä että monikossa. YSOssa vastaavat monikossa.

**Comment by mariaforsen** [comment]
Sv. underben (jos "polven ja nilkan välinen jalan osa") /https://www.kielitoimistonsanakirja.fi/#/s%C3%A4%C3%A4ri?searchMode=all)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
