### ISSUE TITLE
kehitysmaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12281]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kehitysmaat](http://www.yso.fi/onto/yso/p17004)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan ohjaustermin "globaali etelä" erottamista kehitysmaat-termistä.

**Perustelut ehdotukselle**

"kehitysmaat" on talouspoliittinen termi, kun taas "globaali etelä" kuvaa maantieteellisesti puolta maapalloa. Termit ovat joissain tilanteissa päällekkäiset, mutta eivät automaattisesti tai aina.

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Asiaa käsiteltiin 10.10.2023 YSO-kokouksessa. Päätös löytyy täältä:
https://github.com/Finto-ehdotus/YSE/issues/11102

Lisäksi asiaa käsiteltiin 12.10.2023 myös Ontologiakehittäjien yhteistyöryhmän kokouksessa, jossa päätettiin kulttuurisensitiivisten termien huomautustekstistä. Liitän päätöksen alle. Kehitysmaat-termille on suunniteltu lisättäväksi linjauksessa mainittu huomautustekstivaihtoehto b:

=============================

**_Termit ja kulttuurisensitiivisyys_**

_Käytettävä termi tai ohjaustermi, joka on tunnistettu kulttuurisensitiivisyyden kannalta ongelmalliseksi, varustetaan huomautustekstillä. Huomautusteksti on termi- ja kielikohtainen. YSOssa termi varustetaan infoikonilla, jonka yhteydessä huomautusteksti näytetään._

_Huomautusteksteissä on kaksi vaihtoehtoa, koska ongelmallisia termejä on kahta tyyppiä. Vaihtoehto a sopii tapauksiin, joissa on kyseessä ohjaustermi, vaihtoehto b tapauksiin, joissa on kyseessä käytettävä termi:_
_a) "Termimuoto on havaittu vanhentuneeksi tai syrjiväksi. Se on säilytetty sanastossa tiedonhaun mahdollistamiseksi."_
_b) "Termimuoto on havaittu vanhentuneeksi tai syrjiväksi, mutta käytettävissä ei ole toistaiseksi korvaavaa, vakiintunutta termiä.”_
_Vaihtoehto b:n tapauksissa mikäli korvaava, vakiintunut termi myöhemmin havaitaan, voidaan ongelmallinen termi siirtää ohjaustermiksi ja muuttaa huomausteksti vaihtoehto a:n mukaiseksi._

Ks. YSO-pohjaisten ontologioiden kehityslinjauksiin 12.10.2023 tehdyt lisäykset löytyvät myös Finton asiakaspalveluwikistä:
https://www.kiwi.fi/pages/viewpage.action?pageId=371491272

**Comment by vthuhtal** [comment]
Ahaa, Australia ja Uusi-Seelanti ovat siis kehitysmaita!?

**Comment by fantsby-m** [comment]
Kannattaa lukea tuo tpalosen linkkaama issue ja siinä oleva keskustelu, jos globaali etelä ei ole käsitteenä tuttu. Kyse ei ole maantieteellisestä käsitteestä, ks. esim.
https://en.wikipedia.org/wiki/Global_North_and_Global_South

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutoksia.

**Comment by AuHo22** [comment]
kehittyvät maat #1276

**Comment by AuHo22** [comment]
Satuin kuuntelemaan Maailmanpolitiikan arkipäivää radiosta, ja siinä oli käytetty termiä köyhät maat.  Samalla tavalla on henkilöitä kuvaavat köyhät- ja pienituloiset-termit olemassa, eli voisi olettaa että köyhät maat -termi olisi myös objektiivisesti määriteltävissä. Itse olisin myös kaivannut termiä kehittyvät taloudet ajoittain - siirtymätalous-termi taidettiin joskus ottaa Itä-Euroopan maitten talousjärjestelmiä kuvaamaan tietyssä ajassaan, mutta siinä on sitten jo kyse talousjärjestelmän muutoksesta.
