### ISSUE TITLE
StarImage

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12286]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[StarImage](http://www.yso.fi/onto/yso/p16809)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan tämä ja poistetaan myös StarScedule.

**Perustelut ehdotukselle**

Yksi Melinda-hitti molemmilla, vuodelta 2001.
https://melinda.kansalliskirjasto.fi/byid/000231060
(Muilla Star-alkuisilla ohjelmistoilla oli kaksi tai useampi Melinda-hitti.)

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Ei poisteta.
