### ISSUE TITLE
eettinen sijoittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12288]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eettinen sijoittaminen](http://www.yso.fi/onto/yso/p16872)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään termejä tai mahdollisesti otetaan sanastoon uusia käsitteitä. Päätös vaikuttaa myös linkityksiin.

**Perustelut ehdotukselle**

Tuntuu, että kentällä käytetään nykyisin vähemmän "eettinen sijoittaminen"-termiä ja puhutaan enemmän muilla termeillä, esimerkiksi kestävästä sijoittamisesta. Englanniksi sustainable investing. Tai (sosiaalisesti) vastuullisesta sijoittamisesta. Englanniksi socially responsible investing.  Tai ESG-sijoittamisesta. Englanniksi ESG investing. Tai vaikuttavuussijoittamisesta. Englanniksi impact investing. (Tämän voi nähdä hieman kapeampana käsitteenä.) Ja englanniksi, muttei niinkään suomeksi, esiintyy vielä termit green investing ja eco-investing ja environmental investing. Nämä viime mainitutkin voi nähdä suppeampina käsitteinä. 

Esimerkiksi EU:ssa on erilaisia hankkeita, joissa tuo sustainable investment esiintyy: European Sustainable Investment Forum,  Africa – Europe Alliance for Sustainable Investment and Jobs, Joint European Support for Sustainable Investment in City Areas (lyhenne JESSICA, heh). Ja niin edelleen. Ks. esim. https://finance.ec.europa.eu/sustainable-finance_fi

Hs.fi:stä tulee paljon hittejä haulla "vastuullinen sijoittaminen", jonkin verran myös "vaikuttavuussijoittaminen"-haulla, mutta ei niinkään haulla "eettinen sijoittaminen". (Ei tosin myöskään haulla "kestävä sijoittaminen".) Yle.fi:ssä on koko lailla sama tilanne.

Parin viime vuoden Melinda-hiteissä esiintyy sustainable-termiä ja ESG-kirjainlyhennettä melko paljon otsikkotasolla. Jonkin verran myös näkyy termejä responsible ja green. Eettisyys ei esiintynyt uusimmissa otsikoissa lainkaan.

Ks. myös:
https://www.wikidata.org/wiki/Q1371297
https://www.wikidata.org/wiki/Q5333094
https://www.wikidata.org/wiki/Q17082023
https://www.investopedia.com/terms/e/environmental-social-and-governance-esg-criteria.asp
https://www.investopedia.com/sustainable-investing-4427774
https://www.investopedia.com/terms/g/green-investing.asp

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Mielestäni kestävä ja vastuullinen sijoittaminen ovat merkitykseltään varsin lähellä eettistä sijoittamista. Suurin piirtein samaa voisi sanoa ESG-sijoittamisesta. Eli nämä voisivat sopia saman käsitteen termeiksi. Vaikuttavuus- ja vihreä/ekologinen sijoittaminen ovat meritykseltään hieman suppeampia, mutta voisivat ehkä silti sopia ohjaustermeiksi. En tiedä miten paljon aineistoa näistä tulee, että olisiko kuitenkin tarvetta tarkemmalle käsitejaolle?

Toisaalta ESG-asioita voi tarkastella ja käsitellä myös sijoittamisesta irrallaan eli tuo sijoittaminen ei ole ainoa mahdollinen tulokulma siihen. IATEssa ei esimerkiksi ole ESG investment -termiä ollenkaan, mutta löytyy kylläkin ESG risks, ESG criteria, ESG benchmark ja ESG rating.

VAHVA SUOSITUS SEURAAVILLE

_käytettäväksi termiksi: vastuullinen sijoittaminen (eng. (socially) responsible investing)
eettinen sijoittaminen KÄYTÄ vastuullinen sijoittaminen
sosiaalisesti vastuullinen sijoittaminen KÄYTÄ vastuullinen sijoittaminen
kestävä sijoittaminen KÄYTÄ vastuullinen sijoittaminen
ESG-sijoittaminen KÄYTÄ vastuullinen sijoittaminen_

LISÄKSI HARKINTAAN

_vaikuttavuussijoittaminen KÄYTÄ vastuullinen sijoittaminen_ [1]
_vihreä sijoittaminen KÄYTÄ vastuullinen sijoittaminen_ [2]
_eco-investing, green investing, environmental investing KÄYTÄ (socially) responsible investing_ [2]
 _Otetaan sanastoon myös erillisenä käsitteenä jokin ESG-johdannainen. Esimerkiksi ESG-tekijät / ESG-kriteerit / kestävyystekijät_
Vrt. https://vm.fi/pankkien-vakavaraisuus-ja-maksuvalmius
https://vm.fi/rahoitusmarkkinat/paaomamarkkinat

TAI VAIHTOEHTOISESTI

[1] _Otetaan sanastoon erillisenä käsitteenä: vaikuttavuussijoittaminen_
[2] _Otetaan sanastoon erillisenä käsitteenä: vihreä sijoittaminen (eng. green investing, eco-investing, environmental investing)_

**Comment by mariaforsen** [comment]
Ruotsiksi "ansvarsfull investering" tms. suhteellisen harvinainen, sen sijaan "hållbar investering/placering" on erittäin paljon käytetty, se olisi siinä tapauksessa ehkä päätermi ruotsiksi.

**Comment by mirmaid** [comment]
Nuo vahvan suosituksen alla olevat varmaan ovat ok, muita pitänee vähän tutkia. Uusia termejä en lähtisi ottamaan jos ei ole ollut toistaiseksi tarvetta kuvailussa. Kestävyyteen ja yhteiskuntavastuuseen liittyvää termistöä on kuitenkin jo otettu runsaasti.

**Comment by AuHo22** [comment]
https://www.theseus.fi/bitstream/handle/10024/93187/Laakso_Harri.pdf?sequence=1&isAllowed=y

Itse ehkä puhuisin mieluummin arvopohjaisesta sijoittamisesta kuin eettisestä sijoittamisesta, mutta sillä on sitten näköjään eri  merkityksensä: https://pankki-opas.com/arvopohjainen-sijoittaminen.html

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään Tuomaksen vahvan suosituksen alla listatut ehdotukset. Suppeammat termit jäävät harkintaan.

**Comment by mariaforsen** [comment]
Sv. ansvarsfull investering HT hållbar investering, hållbar placering, ansvarsfull placering, ansvarsfull placeringsverksamhet, etisk placering
-https://termipankki.fi/tepa/fi/haku/sijoitus
-https://www.finanssivalvonta.fi/sv/finansiella-aktorer/banker/hallbar-finansiering/
-https://eur-lex.europa.eu/legal-content/SV/TXT
-https://www.finanssivalvonta.fi/sv/finansiella-aktorer/banker/hallbar-finansiering/
-https://eur-lex.europa.eu/legal-content/SV/TXT/HTML/?uri=CELEX:32019R2088
-https://www.s-pankki.fi/sv/private-banking-och-kapitalforvaltning/ansvarsfullhet-och-paverkan/ansvarsfulla-investeringar/hallbarhetspreferenser/
-https://www.nordea.fi/sv/privat/vara-tjanster/besparingar-placeringar/spara-och-placera-hallbart.html
/HTML/?uri=CELEX:32019R2088
-https://www.s-pankki.fi/sv/private-banking-och-kapitalforvaltning/ansvarsfullhet-och-paverkan/ansvarsfulla-investeringar/hallbarhetspreferenser/
-https://www.nordea.fi/sv/privat/vara-tjanster/besparingar-placeringar/spara-och-placera-hallbart.html
-https://www.suomenpankki.fi/sv/finlands-bank/hallbarhet/ansvarsfulla-investeringar/
-https://www.diva-portal.org/smash/get/diva2:823122/FULLTEXT01.pdf
-https://www.suomenpankki.fi/sv/finlands-bank/hallbarhet/ansvarsfulla-investeringar/
-https://www.keva.fi/globalassets/2-tiedostot/tama-on-keva--tiedostot/sijoitukset-talous-ja-raportointi/principer-for-ansvarsfulla-investeringar.pdf
-https://www.lansforsakringar.se/stockholm/privat/om-oss/hallbarhet--forskning/ansvarsfulla-investeringar/fns-principer/
-https://saatiotrahastot.fi/wp-content/uploads/2021/06/SR_Ansvarsfull-placerande.pdf
-https://www.hbl.fi/artikel/8f9e40d0-b74a-4af7-a2a0-6905b04f0859
-https://www.mandatum.fi/490a2e/globalassets/tuotesivut/16.-vastuullinen-sijoittaminen/pdf/mandatum-policy-for-ansvarsfulla-investeringar_2023.pdf
