### ISSUE TITLE
Fintosta lähetetty testiehdotus 1

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12287]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Fintosta lähetetty testiehdotus 1

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Fintosta lähetetty testiehdotus 1

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Fintosta lähetetty testiehdotus 1

**Ehdottajan organisaatio**

KK / Mika
**Termiehdotus Fintossa:** [Fintosta lähetetty testiehdotus 1](http://finto.fi/yse/fi/page/Y512287)

**Comment by miguelvaara** [comment]
Tämä oli testi-issue, jolla todettiin ehdotuksen/issuen YSEen siirtymisen toimivan ok, jos siihen lisätään vastaanotettu-label. Sulkemisen jälkeen testiehdotuksen pitäisi poistua YSEstä. @MikkoAleksanteri @mirmaid @jarmosaarikko @mariaforsen @tpalonen 

https://dev.finto.fi/yse/fi/page/Y512287
