### ISSUE TITLE
Puotinen (Espoo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12285]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Puotinen (Espoo)](http://www.yso.fi/onto/yso/p118220)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermiksi Bodom (Espoo)

**Perustelut ehdotukselle**

Virallinen nimi Bodom.
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=puotinen 
https://www.kielikello.fi/-/nimipohdintoja-kaksikielisesta-kunnasta

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
PNR: Bodom http://paikkatiedot.fi/so/1000772/10067249
