### ISSUE TITLE
Pride (seksuaali- ja sukupuolivähemmistöt)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12283]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pride (seksuaali- ja sukupuolivähemmistöt)](http://www.yso.fi/onto/yso/p24816)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT pride-kulkueet, pride-tapahtumat (vai uutena terminä?)

**Perustelut ehdotukselle**

Aineistoa löytyy, esim. https://yle.fi/aihe/t/18-141914 
https://seta.fi/jarjesto/pride-tapahtumat-suomessa/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
En tiedä olisiko näistä ohjaustermeistä hyötyä - varmaan tuo päätermi löytyy pelkällä pride-haulla ilmankin, eikä tarkoitus kuitenkaan ole, ettei saisi lisäksi käyttää termejä _kulkueet_ ja _tapahtumat_. Sanastossa on toistaiseksi

kulkueet, uskonnolliset kulkueet (& paraatit ja ristisaatot)
tapahtumat, hyväntekeväisyys-, kirjallisuus-, taide-, kulttuuri, liikunta, tanssi-, teatteri- ja lähiverkkotapahtumat sekä yleisötilaisuudet

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään erikseen _Pride-tapahtumat_, ohjaustermiksi _Pride-kulkueet_.

**Comment by mariaforsen** [comment]
Sv. prideevenemang HT pride-evenemang, pridetåg, prideparader, pridefestivaler
https://sprakbruk.fi/artiklar/bindestreck-en-liten-repetition/
