### ISSUE TITLE
kimalaiskärpäset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12297]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kimalaiskärpäset

**Ehdotettu termi ruotsiksi**

[object InputEvent]

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kärpäset](http://www.yso.fi/onto/yso/p9953)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Bombyliidae

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Lajisto](http://tun.fi/MX.276582), [Wikipedia](https://fi.wikipedia.org/wiki/Kimalaisk%C3%A4rp%C3%A4set), [LCSH](http://id.loc.gov/authorities/subjects/sh85015482)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Suomen petokärpäset sukulaisineen :opaskirja lajien määrittämiseen, biologiaan ja uhanalaisuuteen 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [kimalaiskärpäset](http://finto.fi/yse/fi/page/Y512297)

**Comment by mariaforsen** [comment]
Sv. svävflugor https://namnochslaktskap.artfakta.se/taxa/2001313/details
