### ISSUE TITLE
Lakeuden risti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12294]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lakeuden risti](http://www.yso.fi/onto/yso/p23374)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ruotsinkielinen nimi: Korset på slätten

**Perustelut ehdotukselle**

KÄytetään Visit Seinäjoen ruotsinkielisellä sivulla
https://visitseinajoki.fi/sv/attraktioner/aalto-sevardheter/korset-pa-slatten/

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Voisi myös olla ohjaustermi, "korset på slätten" käsitellään yleensä käännöksenä, ei virallisena nimenä, ks. esim: 
https://www.uppslagsverket.fi/sv/sok/view-170045-AaltoAlvar
https://www.visitfinland.com/sv/produkt/9e56f101-6be4-49a2-a5bb-9cf1514d65d9/lakeuden-risti-church/
https://tarinasoitin.fi/seinajoenaalto/se/lakeudenristi
https://www.seinajoenseurakunta.fi/documents/78941/99324/Kyrkorna_i_Seinajoki_2016_web.pdf/3704d4c1-eab8-45ca-ac4c-34730d7a261d

Ehdotuksessa mainittu lähdesivu on kielellisesti kyseenalainen, esim. yksi otsikko "Aalto sig själv". Google mapsissa tietona että nimitys "käännetty englannista"._ 

AASI-ryhmän päätös: lisätään ohjausterminä (ehdotettu ruotsinkielinen nimi ei ole virallinen)
