### ISSUE TITLE
jätinkirkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12293]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jätinkirkot

**Ehdotettu termi ruotsiksi**

jättekyrkor

**Ehdotettu termi englanniksi**

giant's churches

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [muinaisjäännökset](http://www.yso.fi/onto/yso/p5340)

**Ehdotetut temaattiset ryhmät**

 [51 Arkeologia](http://www.yso.fi/onto/yso/p26593), [06 Tähtitiede. Astronomia. Avaruustutkimus](http://www.yso.fi/onto/yso/p26588)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/J%C3%A4tinkirkko), [MAO/TAO](http://www.yso.fi/onto/mao/p8281)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Suuret jätinkirkot: rakenteet ja suuntaukset / Marianna P. Ridderstad

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [jätinkirkot](http://finto.fi/yse/fi/page/Y512293)

**Comment by mariaforsen** [comment]
https://www.uppslagsverket.fi/sv/sok/view-170045-Jaettekyrkor
https://svenska.yle.fi/a/7-927511
http://web.abo.fi/fc/pix/SKaRGaRD/SKARGARD%20NR04-2005/Herrg%C3%A5rd%20o%20Holmblad.doc

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
