### ISSUE TITLE
Vanaja kyrka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12295]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vanaja kyrka](http://www.yso.fi/onto/yso/p26084)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vanajan kirkko - > Vånå kyrka

**Perustelut ehdotukselle**

Vanajan ruotsinkielinen nimi on Vånå. 
kts: https://kaino.kotus.fi/svenskaortnamn/?a=abc&b=V&pos=100

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Korjattu.
