### ISSUE TITLE
varumärkesintrång

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12290]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tavaramerkin loukkaus

**Ehdotettu termi ruotsiksi**

varumärkesintrång

**Ehdotettu termi englanniksi**

trademark infringement

**Tarkoitusta täsmentävä selite**

Om ett varumärke är skyddat för en vara eller tjänst så får ingen använda ett identiskt eller liknande märke för samma eller liknande varor och tjänster. Gör man det kan det innebära att man begår ett varumärkesintrång, enligt Varumärkeslagen.

Det kan även innebära varumärkesintrång om ett nytt varumärke skadar ett varumärke som är känt sedan länge.

**Perustelut ehdotukselle**

Ordet förekommer ofta i handelsrättsliga sammanhang

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [ LCSH](http:// Trademark infringement.)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://hdl.handle.net/10138/566602
http://hdl.handle.net/10138/564818
http://hdl.handle.net/10138/565046

**Ehdottajan organisaatio**

Hankens bibliotek
**Termiehdotus Fintossa:** [varumärkesintrång](http://finto.fi/yse/fi/page/Y512290)

**Comment by mirmaid** [comment]
_Tekijänoikeuden loukkaus_ olisi vastaava. Melindassa kuvailtu (ainakin) tavaramerkit/tekijänoikeus + rikokset. YLEllä käytetty tekijänoikeuden loukkaus -fraasia.

**Comment by mariaforsen** [comment]
N. 50 000 googleosumaa ruotsiksi, "tavaramerkin loukkaus" n. 1500 suomeksi. Ainakin ruotsin kannalta olisi hyvä käsite. 
https://www.rikstermbanken.se/search?q=varum%C3%A4rkesintr%C3%A5ng&s=termer
https://www.sanakirja.fi/custom/en-sv-fi/varum%C3%A4rkesintr%C3%A5ng
https://www.minilex.fi/a/tavaramerkin-loukkaus-voi-aiheuttaa-vakavia-seurauksia
https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/varumarkeslag-20101877_sfs-2010-1877/

**Comment by fantsby-m** [comment]
Oikea LCSH-linkki:
http://id.loc.gov/authorities/subjects/sh96001071

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään seuraavaan kokoukseen. Tutkitaan myös käsitteitä _tekijänoikeusloukkaus_ ja _tekijänoikeusrikkomus_.

**Comment by mariaforsen** [comment]
"**Tekijänoikeudenloukkaus** voi tulla rangaistavaksi **tekijänoikeusrikoksena** (Rikoslaki 49:1§) tai **tekijänoikeusrikkomuksena** (Tekijänoikeuslaki 56 a §)" 
/https://ttvk.fi/tekijanoikeus/loukkaukset

"Tavaramerkin loukkaus tarkoittaa sitä, että joku käyttää luvatta toisen omistamaa tavaramerkkiä, tai siihen sekoitettavissa olevaa tavaramerkkiä"
https://www.minilex.fi/a/tavaramerkin-loukkaus-voi-aiheuttaa-vakavia-seurauksia
Vrt. https://ttvk.fi/tekijanoikeus/loukkaukset 

..Eli olisiko hyvä olla sanastossa sekä "tekijänoikeudenloukkaukset" että "tavaramerkin loukkaukset"?

**Comment by YSO-kokous** [comment]
Hyväksytään molemmat.

**Comment by mariaforsen** [comment]
Sv. -varumärkesintrång
-kränkning av upphovsrätt HT kränkande av upphovsrätt, upphovsrättsintrång
https://ttvk.fi/sv/upphosvratt/krankning-av-upphovsratten
https://www.sanakirja.fi/custom/en-sv-fi/tekij%C3%A4noikeuden
https://operight.fi/sv/artiklar/allmant/krankning-av-upphovsratten
https://kopiraittila.fi/sv/upphovsrattens-abc/krankande-av-upphovsratten/
https://www.rikstermbanken.se/search?q=upphovsr%C3%A4ttsintr%C3%A5ng&s=termer
