### ISSUE TITLE
traumatietoisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12308]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

traumatietoisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

trauma awareness

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Traumainformoidusta sotesta, traumainformoidusta työstä, traumainformoidusta työotteesta ja traumatietoisuudesta puhutaan paljon ja monilla aloilla (koulutus, sosiaalityö, terveydenhuolto, terapia jne.). Koska käsitteitä on niin monia, voisi ajatella että yksi laaja yleiskäsite "traumatietoisuus" voisi sopia kaikkiin konteksteihin.

https://uasjournal.fi/4-2021/traumatietoisuus-luo-kestavaa-vuorovaikutusta/ 

https://traumainformoitu.fi/traumainformoitu-orientaatio-auttamistyossa/

**Ehdotettu yläkäsite YSOssa (LT)**

 [tietoisuus](http://www.yso.fi/onto/yso/p7672)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 traumainformoitu työote, traumainformoitu orientaatio, traumainformoitu hoito, traumainformoitu hoiva, traumatietoinen orientaatio

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [traumat](http://www.yso.fi/onto/yso/p9794)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Traumainformoitu työote /Johanna Linner Matikka ja Tiia Hipp (toim.).

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [traumatietoisuus](http://finto.fi/yse/fi/page/Y512308)

**Comment by mirmaid** [comment]
Ei Melindassa, Googlella kyllä löytyy.

**Comment by mariaforsen** [comment]
Sv. traumamedvetenhet HT traumamedveten omsorg
https://www.uppdragpsykiskhalsa.se/verktyg/traumamedveten-omsorg-hjalp-for-barn-som-har-varit-med-om-traumatiska-handelser/
Olisi käyttöä, esim. tässä https://melinda.kansalliskirjasto.fi/F/TXGSYNAELN4C29P5VTI41F8HK2P16MF39JBQGAY1SS7E5RUHC3-05352?func=full-set-set&set_number=029311&set_entry=000001&format=999

**Comment by FinMeSHienPaimentaja** [comment]
Pärjättäisiinkö jo olemassa olevilla "traumat", "traumatisoituminen"?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
