### ISSUE TITLE
vähäkimalaiskärpäset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12300]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vähäkimalaiskärpäset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kärpäset](http://www.yso.fi/onto/yso/p9953)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Mythicomyiidae

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Mythicomyiidae), [Lajisto: Mythicomyiidae](http://tun.fi/MX.276620)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Suomen petokärpäset sukulaisineen :opaskirja lajien määrittämiseen, biologiaan ja uhanalaisuuteen 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [vähäkimalaiskärpäset](http://finto.fi/yse/fi/page/Y512300)

**Comment by mariaforsen** [comment]
Sv. dvärgsvävflugor /artdatabanken
