### ISSUE TITLE
Vesunti (Hattula)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12305]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vesunti (Hattula)](http://www.yso.fi/onto/yso/p109269)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus tms. muutos

**Perustelut ehdotukselle**

Mihin viittaa? Linkitetty kartanoon. Karttapaikassa: 1) Vesunti =talo Huittisissa 2) Vesunti =kylä Sastamalassa 3) VesuntA =talo Hattulassa

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Asutusnimihakemisto: 
Vesunti : Vesunnissa
Kylä (vir.), kartano
Sijaintikunta: 	Hattula
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=vesunti

--

Vesunnan kartano on YSOssa http://www.yso.fi/onto/yso/p20507

**Comment by mirmaid** [comment]
Linkki poistettu YSO-paikoista. Tarvitaanko muita toimenpiteitä?

**Comment by mirmaid** [comment]
Poistetaan, aineistoihin Hattula.
