### ISSUE TITLE
stereokuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12306]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[stereokuvaus](http://www.yso.fi/onto/yso/p17128)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi stereoskopia, englanniksi stereoscopy ja stereoscopic photography.

**Perustelut ehdotukselle**

Ks. käsitteen LCSH-linkki. http://id.loc.gov/authorities/subjects/sh85101299
Vrt. myös Wikipedia: "Stereo photography techniques are methods to produce stereoscopic images, videos and films. "
https://en.wikipedia.org/wiki/Stereo_photography_techniques

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Termit ovat varsin päällekkäisiä. Ks. esim. https://termipankki.fi/tepa/fi/haku/stereokuva
Vrt. Encyclopedia Britannica: "Stereoscopic photographic views (stereographs) were immensely popular in the United States and Europe from about the mid-1850s through the early years of the 20th century."
https://www.britannica.com/technology/photography/Development-of-stereoscopic-photography

Oliver Sacks kertoo kiinnostavasti stereoskopiasta kirjassaan Kirjailija joka kadotti kirjaimet: "Vuosien varrella minulle on kertynyt suuri kokoelma stereokuvia ja stereoskopiasta kertovia kirjoja. Minusta tuli newyorkilaisen Stereoskooppisen yhdistyksen aktiivijäsen, ja kokouksissamme olen tavannut muita stereointoilijoita. Me stereoharastajat tilaamme stereolehtiä, ja jotkut meistä osallistuvat stereokongresseihin. - - - jos pystyy ymmärtämään stereoskopian, pystyy ymmärtämään paitsi yksinkertaisen ja loistavan visuaalisen ilmiön myös jotain näköaistimusten luonteesta ja jopa tietoisuudesta."
