### ISSUE TITLE
unijooga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12309]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[unijooga](http://www.yso.fi/onto/yso/p25275)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan, esim. tiibetiläinen unijooga, tai mahdollisesti jaetaan?

**Perustelut ehdotukselle**

Ruotsiksi sömnyoga, mutta englanniksi dream yoga, muutetaan varmaan sv. > drömyoga. Viimeisin mainittu on siis tiibetiläinen unijooga, joka on hyvin eri asia kuin "unen jooga", eli miten pitää hengittää jne. että saisi hyvin unta. Melindassa kaksi viitettä, myöhempi ehkä "unen jooga" merkityksessä? Löytyy myös uutisia YLE:ltä yms. Olisiko siis syytä jakaa, vai riittääkö niihin aineistoihin, joissa käsitellään fyysisiä asioita jooga + uni (lepotila)? 

Linkki tähän https://en.wikipedia.org/wiki/Dream_yoga jos/kun tarkennettu termin alkuperäiseen merkitykseen. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Eli esim. nämä ovat siitä oikeasta unijoogasta:
https://www.unijooga.fi/
https://www.adlibris.com/fi/kirja/tiibetilainen-unijooga-9789525728309
https://www.selkouni.fi/tiibetilainen-unijooga
https://www.ligmincha.fi/fi/bon/opetukset/61-unijooga

Vrt. tällaiset:
https://liisauusitaloarola.fi/tuote/unijooga/

**Comment by YSO-kokous** [comment]
Muutetaan muotoon _tiibetiläinen unijooga_.
