### ISSUE TITLE
raketit (ammukset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12302]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

raketit (ammukset)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Ammuksena käytetty raketti, joka laukaistaan esimerkiksi singolla, raketinheittimellä tai tykillä.

**Perustelut ehdotukselle**

YSO:ssa on jo käsite raketit, joka kuuluu luokkiin 06-tähtitiede ja 30-kemianteollisuus. Noin puolet tällä käsitteellä Melindassa kuvaillut aineistot käsittelevät nimen omaan sotilaskäyttöä. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [ammukset](http://www.yso.fi/onto/yso/p5857)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ohjukset](http://www.yso.fi/onto/yso/p17763)

**Vastaava käsite muussa sanastossa**

 [](https://id.loc.gov/authorities/subjects/sh85114741.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.171225
https://mpkk.finna.fi/Record/taisto.170685

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto
**Termiehdotus Fintossa:** [raketit (ammukset)](http://finto.fi/yse/fi/page/Y512302)

**Comment by mirmaid** [comment]
Olemassaoleva käsite tarvinnee toimenpiteitä muutenkin.

**Comment by vthuhtal** [comment]
rakettiammukset?

**Comment by mirmaid** [comment]
Wikipediassa _rakettiaseet_.

**Comment by vthuhtal** [comment]
> Wikipediassa _rakettiaseet_.

mutta ehdotuksena puhutaankin _ammuksista_

**Comment by mariaforsen** [comment]
Eli ainakin kolme eri merkitystä, avaruusalukset, ilotulitukset, aseet + ammukset? 
Vrt SAO https://id.kb.se/find?q=raket%2a

**Comment by mirmaid** [comment]
Näille voidaan kyllä löytää myös yhteinen nimittäjä (rakettitekniikka), mikä tekee jakamisesta hiukan hankalampaa - oletan että kuitenkin haluamme erotella. Ammukset voi käsittääkseni sisältää myös hätä- ja ilotulitusraketit (?). Varmaan looginen kokonaisuus olisivat kuitenkin aseina käytetyt raketit.

Sanastosta löytyy myös _avaruussukkulat_ ja _avaruusalukset_.

**Comment by YSO-kokous** [comment]
**Päätös**

Maanpuolustuskorkeakoulun kirjasto tutkii.

**Comment by tapiopitkaranta** [comment]
MPKK:n kirjasto tutki asiaa, mutta emme keksineet riittävän yksiselitteistä ratkaisua uudelle termille. Pystymme elämään nykyisen termin kanssa. Voisi lisätä ryhmän 67: Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet. Näin olisi selvempää, että nykyistä termiä voi käyttää myös tarkoittamaan rakettiammuksia.

**Comment by mirmaid** [comment]
Voisi ehkä kuitenkin lisätä ainakin ohjaustermejä avaruussukkuloille ym.

**Comment by YSO-kokous** [comment]
Mietitään tarvittavia ohjaustermejä.

**Comment by tpalonen** [comment]
YSO-ylläpidossa on keskusteltu myös mitä tarkoittaa _raketinheittimet_-käsite: a) tykkimäistä heitintä vai b) olalta laukaistavaa vai c) molempia? Tämä olisi hyvä tietää, sillä vaikuttaa eri kielisiin termeihin (rocket artillery vs rocket launcher) sekä käsitteen linkityksiin. Osaisiko joku kommentoida tätä?

**Comment by AnuAlatera** [comment]
Maanpuolustuskorkeakoulun kommentit:
Raketinheittimillä tarkoitetaan tällä hetkellä kalustoa, joka ei ole olalta laukaistavaa. Olalta laukaistavista käytetään termiä sinko tai panssarintorjuntaohjus.
Raketinheittimistä lisätietoja: https://puolustusvoimat.fi/kalusto#/asset/view/id/501 -> Lisätietoja-välilehti.

**Comment by mariaforsen** [comment]
Olisiko yllä olevassa linkissä olevat raskaat raketinheittimet ohjaustermi?

**Comment by YSO-kokous** [comment]
YSOn ylläpitoryhmä tutkii raketinheittimet-käsitettä mpkk:n kommenttien pohjalta.

**Comment by mirmaid** [comment]
Onko tykit oikea yläkäsite? Mitä kaikkea tykit kattaa? Vrt. kielivastineet.

**Comment by AnuAlatera** [comment]
Raketinheittimien yläkäsite voi MPKK:n puolesta olla tykit.
