### ISSUE TITLE
Novgorod

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12314]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Novgorod](http://www.yso.fi/onto/yso/p110900)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermiksi Veliki Novgorod, KT Novgorod (kaupunki)

**Perustelut ehdotukselle**

Ei sekoittuisi Novgorodin tasavaltaan

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Muutetaan > Veliki Novgorod

**Comment by mariaforsen** [comment]
Sv. Novgorod > Velikij Novgorod HT Novgorod (stad)

-https://sv.wikipedia.org/wiki/Velikij_Novgorod
-https://sv.wikipedia.org/wiki/Novgorod_(olika_betydelser)
-https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/novgorod
