### ISSUE TITLE
psykedeelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12310]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

psykedeelit

**Ehdotettu termi ruotsiksi**

psykedeliska droger

**Ehdotettu termi englanniksi**

psychedelic drugs

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Minun mielestäni olisi luotava tämä luokka, koska aiheesta puhutaan yhä enemmän eri julkaisuissa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 psykedeeliset aineet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia.org](https://fi.wikipedia.org/wiki/Psykedeelit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9781847926975

**Ehdottajan organisaatio**

Vantaan kaupunginkirjasto
**Termiehdotus Fintossa:** [psykedeelit](http://finto.fi/yse/fi/page/Y512310)

**Comment by mariaforsen** [comment]
Sanastossa on jo [hallusinogeenit](https://finto.fi/yso/fi/page/p29592), SAOssa se on päätermi  ja psykedeliska droger ohjaustermi. Tämä voisi toki olla alakäsitekin: "Hallusinogeenit voidaan jakaa kolmeen ryhmään: [psykedeelit](https://fi.wikipedia.org/wiki/Psykedeelit), [dissosiatiivit](https://fi.wikipedia.org/wiki/Dissosiatiivit) ja [deliriantit](https://fi.wikipedia.org/wiki/Deliriantit)." /wp

Meshissä vain hallusinogeenit https://finto.fi/mesh/fi/page/D006213

**Comment by mirmaid** [comment]
Lääketieteen termit: 
psykedeelinen aine:  psykedeeli | aistiharhoja aiheuttava aine
hallusinogeeni: aistiharhoja aiheuttava aine

Wikipedia: https://fi.wikipedia.org/wiki/Hallusinogeenit#Psykedeelit_(klassiset_hallusinogeenit)

**Comment by mirmaid** [comment]
https://paihdelinkki.fi/fi/tietopankki/tietoiskut/huumeet-ja-muut-paihdyttavat-aineet/hallusinogeenit

https://www.duodecimlehti.fi/duo15480

**Comment by mirmaid** [comment]
Also referred to as classic hallucinogens or serotonergic hallucinogens, the term psychedelic is sometimes used more broadly to include various types of hallucinogens, such as those which are atypical or adjacent to psychedelia like salvia and MDMA, respectively. https://en.wikipedia.org/wiki/Psychedelic_drug

**Comment by mirmaid** [comment]
Varmaan erityisesti lääketieteen yhteydessä olisi hyödyllinen erillisenä, mutta vähän mietityttää tuo osin epätarkka käyttö (esim. empatogeenit ilmeisesti toisinaan sisällytetään, toisinaan ei).

**Comment by FinMeSHienPaimentaja** [comment]
MeSH:eissä näyttää olevan "psykedeelit" ja "hallusinogeenit" synonyymejä - vaihdelleet vuosien kuluessa, kumpi on milloinkin  ollut käytössä. https://meshb.nlm.nih.gov/record/ui?ui=D006213

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään uutena ohjausterminä.
