### ISSUE TITLE
Itä-Suomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12315]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Itä-Suomi](http://www.yso.fi/onto/yso/p94161)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vanhalla ongelmalistalla (YSAn/Allärsin maantieteellisten ongelmatapauksia)

**Perustelut ehdotukselle**

Miten tämä ja vastaavat halutaan linkittää wikidatassa?

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Viimeksi käsiteltiin [Etelä-Suomi](https://github.com/Finto-ehdotus/YSE/issues/12074)
Varmaan sama ratkaisu myös tähän Itä-Suomeen?

**Comment by mirmaid** [comment]
Poistetaan näistä linkitykset, MML-linkit eivät johda enää mihinkään ja wikidata-linkit vievät disambiguaatio-sivuille.

**Comment by mirmaid** [comment]
Poistettu linkit YSO-paikoista, linkit ovat myös Wikidatassa...joissakin (esim. Koillis-Suomi) on kuitenkin tekstiä.

**Comment by mirmaid** [comment]
Jätetään linkit, jos kyseessä ei ole täsmennyssivu (merkitty wikidatassa täsmennyssivuksi), niistä poistetaan.
