### ISSUE TITLE
Sansibar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12319]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Sansibar](http://www.yso.fi/onto/yso/p105999)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan 

**Perustelut ehdotukselle**

Huomautuksensa takia vanhalla ongelmalistalla monimerkityksisten paikkojen ryhmässä.

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
https://kaino.kotus.fi/eksonyymit/?a=listaus&hakunimi=sansibar

**Comment by mirmaid** [comment]
Sansibarin saaristo KT Sansibar

**Comment by mariaforsen** [comment]
Sv. Zanzibar > Zanzibararkipelagen  HT Zanzibars skärgård, Zanzibars övärld
https://sv.wikipedia.org/wiki/Zanzibararkipelagen
