### ISSUE TITLE
Virmaila

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12311]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Virmaila](http://www.yso.fi/onto/yso/p17330)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö olla sulkutarkenne?

**Perustelut ehdotukselle**

YSOssa tämä on ratsutila. Wikipediasta taas löytyy kolme Virmailaa, joista yksikään ei ole ratsutila.
Ks.
https://fi.wikipedia.org/wiki/Virmaila
https://fi.wikipedia.org/wiki/Virmaila_(saari)
https://fi.wikipedia.org/wiki/Virmailan_linnasaari

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Ei ole varmaan enää ratsutila 🙂. Voisi olla myös Virmailan rustholli.

**Comment by mariaforsen** [comment]
Sv. on jo Virmaila gård, voisi olla myös Virmaila rusthåll

**Comment by YSO-kokous** [comment]
Ok.
