### ISSUE TITLE
averages (traffic damages)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12312]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[averages (traffic damages)](http://www.yso.fi/onto/yso/p10406)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

averages (shipping), sea damages (/MOT) tms. tarkempi termi

**Perustelut ehdotukselle**

pitäisi rajautua merenkulkuun

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Päätermi muutettu: averages (shipping)
