### ISSUE TITLE
Siikajärvi (Kuopio)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12318]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Siikajärvi (Kuopio)](http://www.yso.fi/onto/yso/p158728)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan

**Perustelut ehdotukselle**

Vanhalla ongelmalistalla

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kopioitu ongelmalistalta:
PNR-linkki ristiriidassa YSAn termimuodon kanssa. PNR-linkki Ylä-Siikajärveen, löytyy myös Ala-Siikajärvi. Teos: _Torpparista talonpojaksi: elämää Siikajärven hovin maisemissa 100 vuotta_ (on kylähistoriikki) (Mirja, 5.7.2018)
Päätetty: Tutkitaan vielä kylää, poistetaan kuitenkin PNR-linkki vesistöön.

**Comment by mirmaid** [comment]
Jatkuu:
vesistölinkki poistettu, Kuopiosta löytyy Keski-Siikajärvi ja Ylä-Siikajärvi nimiset kylät, joihin toiseen tai molempiin tämä Kuopio – Siikajärvi (Nilsiä – Siikajärvi) ilmeisesti viittaa. Lisäksi samoilla nurkilla Kuopiossa sijaitsee myös Ala-Siikajärven kylä, mutta se näyttää sijainneen aiemmin Juankoskella, eli tästä kylästä ei ilmeisesti ole kyse.(leveä virnistys)15.8./Ilona

**Comment by ilona-x** [comment]
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=siikaj%C3%A4rvi

**Comment by mirmaid** [comment]
Muutetaan > Ylä-Siikajärvi (tarkistetaan aineisto, mahd. myös Keski-Siikajärvi)

**Comment by mariaforsen** [comment]
Kuopion seudulla näyttää olevan kaksi eri Ylä-Siikajärveä, ks. https://asiointi.maanmittauslaitos.fi/karttapaikka/?lang=sv

**Comment by mirmaid** [comment]
Lisätään myös Ala-Siikajärvi, nämä aineiston kuvailuun.
