### ISSUE TITLE
tarpeisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12313]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tarpeisto](http://www.yso.fi/onto/yso/p14806)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Listäänkö huomautus tms. joka rajoittaa teatteri/elokuvamerkitykseen?

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/tarpeisto?searchMode=all
Tarpeisto on myös juridinen termi, Melindassa nyt esim. Esineoikeuden perusteet / Leena Kartio. Sv. termi on aivan väärä muissa asiayhteyksissä kuin teatterin/elokuvan. 

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
EKS:issä näyttää olevan tarpeisto tuossa oikeustieteen merkityksessä:
Asiasana:	tarpeisto
Asiasana ruotsiksi:	pertinens
Asiasana englanniksi:	appurtenances

**Comment by mirmaid** [comment]
Jos rajataan, soveltuuko tarkenteeksi nykyinen ohjaustermi rekvisiitta?

**Comment by mirmaid** [comment]
https://www.kansallisteatteri.fi/serve/teatterisanasto-kansallisteatteripdf

TARPEISTO / REKVISIITTA
Kaikki irtotavara, jota lavalla on ja jota näyttelijät käyttävät esityksen aikana.

**Comment by mariaforsen** [comment]
Tarpeisto teatterimerkityksessä on sv. rekvisita.

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:rekvisiitta

Päätermi voisi myös olla rekvisiitta, jos lavaste tarkoittaa vain kiinteää kulissia? Nyt rekvisiitta ohjaa molempiin.

**Comment by YSO-kokous** [comment]
Muutetaan suomeksi muotoon _rekvisiitta_.
