### ISSUE TITLE
Okanniemi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12317]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Okanniemi](http://www.yso.fi/onto/yso/p200843)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan, mihin viittaa

**Perustelut ehdotukselle**

Linkattu niemeen, vrt. huomautus & Melindassa vain 1 viite: "Selänpään ja Okanniemen pohjavesialueiden suojelusuunnitelma"

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Poistetaan huomautus.
