### ISSUE TITLE
Jurmo (Brändö)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12316]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Jurmo (Brändö)](http://www.yso.fi/onto/yso/p508610)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään linjaus MML-linkityksestä (tämä esimerkkinä tapauksesta, jolla useampi linkki)

**Perustelut ehdotukselle**

vrt. esim. Salo ja muut kunta/kaupunki + keskustaajama -tapaukset

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Lisätään linjaus, että MML-linkkejä voidaan lisätä useampia silloin kun paikkoja ei auktorisoida YSO-paikkoihin erikseen.
