### ISSUE TITLE
Lempäälän kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12320]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Lempäälän kirkko

**Ehdotettu termi ruotsiksi**

Lembois kyrka

**Ehdotettu termi englanniksi**

Saint Birgitta Church (Lempäälä)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa erottamaan Pyhän Birgitan kirkko (Uusikaarlepyy)

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 Pyhän Birgitan kirkko (Lempäälä), Sankta Birgitta kyrka (Lempäälä)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Lemp%C3%A4%C3%A4l%C3%A4n_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lempäälän Pyhän Birgitan kirkko / Olavi Tapio
https://melinda.kansalliskirjasto.fi/byid/002508400

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [Lempäälän kirkko](http://finto.fi/yse/fi/page/Y512320)

**Comment by mariaforsen** [comment]
Sv. Lempäälä kyrka HT Lembois kyrka (Lembois vanhentunut Svenska ortnamnin mukaan), Heliga Birgittas kyrka (Lempäälä) /google maps
https://sv.wikipedia.org/wiki/Lembois_kyrka

https://researchportal.tuni.fi/en/publications/lemp%C3%A4l%C3%A4-lemp%C3%A4%C3%A4l%C3%A4-lembois-mik%C3%A4-on-lemp%C3%A4%C3%A4l%C3%A4n-ruotsinkielinen-nimi

" Lempäälän vanhentuneet ruotsinkieliset nimet olivat Lembois ja Lempälä.[[10]](https://fi.wikipedia.org/wiki/Lemp%C3%A4%C3%A4l%C3%A4#cite_note-10) Vuonna 2019 annetun Kotimaisten kielten keskuksen ja ruotsin kielen lautakunnan uuden suosituksen mukaan Lempäälällä ei ole ruotsinkielistä nimeä"
/https://fi.wikipedia.org/wiki/Lemp%C3%A4%C3%A4l%C3%A4

https://runeberg.org/finvaglapp/0396.html
