### ISSUE TITLE
valtaneuvokset/valtaneuvosto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12322]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

valtaneuvokset/valtaneuvosto

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Valtaneuvos

**Perustelut ehdotukselle**

Melindassa joitakin kertoja virheellisesti valtioneuvokset

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/011116443

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Mihin maihin rajoitetaan, pohjoismaat? "Riksråd är i Skandinavien dels en titel på en kunglig rådgivare (rådsherre), dels på samlingen av dessa rådgivare." /wp
Ks. myös esim. https://svenska.se/tre/?sok=riksr%C3%A5d&pz=1
SAOssa https://id.kb.se/find?q=riksr%C3%A5d  "Hit verk om medlemmar av det svenska riksrådet."

**Comment by mirmaid** [comment]
^ Itselleni valtaneuvos/-neuvosto suomeksi on tuttu vain Ruotsin historian yhteydessä, mutta toisaalta näköjään eng. privy council, joka olisi yhtä lailla ollut Englannin hallinnossa vastaavanlainen organisaatio ja näköjään olemassa edelleen. Wikipedian mukaan sekin voi olla suomeksi valtaneuvosto, ruotsiksi näköjään "kronrådet". Ilmankin kyllä pärjätään, tai sitten voidaan rajata esim. (Ruotsi).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _valtaneuvokset (Ruotsi)_.

**Comment by mariaforsen** [comment]
Sv. riksråd (ämbete i Sverige)
