### ISSUE TITLE
lääkitysvirheet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12328]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lääkitysvirheet

**Ehdotettu termi ruotsiksi**

medicineringsfel

**Ehdotettu termi englanniksi**

medication errors

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [lääkehoito](http://www.yso.fi/onto/yso/p10851)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 lääkityspoikkeamat, lääkityspoikkeama

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D008508), [LCSH](http://id.loc.gov/authorities/subjects/sh85083061)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-61-4827-4

**Ehdottajan organisaatio**

KK/MP

**Comment by mirmaid** [comment]
Nyt on näköjään lääkintävirheet KÄ hoitovirheet. Lisätäänkö myös tämä muoto ohjaustermiksi, vai otetaanko erikseen?

**Comment by mariaforsen** [comment]
Kannatan erillisenä terminä, hyvin tärkeä asia kuitenkin, josta pitäisi voida tehdä täsmällisiä tiedonhakuja. 

Sv. medicineringsfel HT felhantering av läkemedel, medicineringsmisstag
https://mesh.kib.ki.se/term/D008508/medication-errors

**Comment by mariaforsen** [comment]
Sv. medicineringsfel HT felhantering av läkemedel, medicineringsmisstag
https://mesh.kib.ki.se/term/D008508/medication-errors
