### ISSUE TITLE
vaikutushistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12327]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vaikutushistoria](http://www.yso.fi/onto/yso/p21324)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään RT-suhteet asiasanoihin "vaikutteet" ja "vaikutukset"

**Perustelut ehdotukselle**

Käsilläoleva asiasana jää nyt helposti huomaamatta ja käyttämättä, jos kuvailija päätyy aprikoimaan kuvailemaansa asiaa yleiskielisemmän vaikutteet- ja/tai vaikutukset-sanan kautta. "Vaikutushistoria"-asiasana kaipaisi lisäksi saman tai samankaltaisen selityksen kuin mikä oli YSA:ssa (http://www.yso.fi/onto/ysa/Y161860).

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSO-ylläpito päätyi jättämään RT-suhteet pois, koska vaikutteet ja vaikutukset ovat laajasti käytettyjä yleistermejä ja vaikutushistoria niiden suunnalta katsoen paljon tarkemmin rajautuva. Määritelmän lisäämistä kannatettiin.
