### ISSUE TITLE
Kalevalapuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12325]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kalevalapuisto](http://www.yso.fi/onto/yso/p25536)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne?

**Perustelut ehdotukselle**

Muita samannimisiä näyttää olevan, sanastossa myös Kalevalan kansallispuisto. 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tarkenteeksi (luonnonsuojelualueet)?

**Comment by YSO-kokous** [comment]
Ok.
