### ISSUE TITLE
cancel-kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12323]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

cancel-kulttuuri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kyseessä on aihe, josta puhutaan mediassa paljon ja jonka käsittely varmasti lisääntyy myös kirjallisuudessa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://cancel culture)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Cancelled, ISBN 978-1-5095-5091-3

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/10535

**Comment by mariaforsen** [comment]
Sv. cancelkultur HT cancel-kultur, call out-kultur, cancellering, utfrysningskultur, kränkthetskultur, utraderingskultur
https://id.kb.se/term/sao/Cancelkultur
https://svenskateatern.fi/cancelkulturens-tva-ansikten/
https://spraktidningen.se/qa/rimligaste-valet-ar-att-cancellera/
https://sv.wikipedia.org/wiki/Cancelkultur
https://svenska.yle.fi/a/7-1484022

**Comment by ilona-x** [comment]
LCSH: 
Cancel culture http://id.loc.gov/authorities/subjects/sh2020006329

Wikidata:
cancel-kulttuuri http://www.wikidata.org/entity/Q60297962

**Comment by annamarj** [comment]
Riittäisikö kuitenkin jo YSOssa oleva "poliittinen korrektius"?

**Comment by YSO-kokous** [comment]
Cancel-ilmiö KT cancel-kulttuuri, cancelointi, callout-kulttuuri.
