### ISSUE TITLE
rannikkojoukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12341]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rannikkojoukot

**Ehdotettu termi ruotsiksi**

kusttrupper

**Ehdotettu termi englanniksi**

coastal troops

**Tarkoitusta täsmentävä selite**

Rannikkojoukot ovat saaristo- ja rannikko-olosuhteissa toimimaan koulu­tettuja ja varustettuja joukkoja. Rannikkojoukkojen päätehtävänä on täydentää tilannekuvaa saaristossa ja rannikkoalueilla, turvata merivoimien joukkojen toimintavapaus saaristossa, rajoittaa vastustajan erikoisjoukkojen toimintaa, pitää käsketyt kohteet ja torjua mereltä tulevat hyökkäykset. Rannikkojoukkojen toiminta-aluetta ovat rannikko- ja saaristoalueet. 

**Perustelut ehdotukselle**

Rannikkojoukoilla on Suomessa pitkä historia, myös kuvailtavaa aineistoa on runsaasti.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sotilaalliset organisaatiot](http://www.yso.fi/onto/yso/p3949)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [merivoimat](http://www.yso.fi/onto/yso/p3944)

**Vastaava käsite muussa sanastossa**

 [Soto](https://finto.fi/soto/fi/page/p328)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.148857?sid=3279986058

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu, kirjasto
**Termiehdotus Fintossa:** [rannikkojoukot](http://finto.fi/yse/fi/page/Y512341)

**Comment by mirmaid** [comment]
Runsaasti Melindassa.

**Comment by mariaforsen** [comment]
Sv. kusttrupper, kustförband
https://merivoimat.fi/sv/truppforband
https://www.fanbararen.fi/marinen-under-vinter-och-fortsattningskriget/
https://svenska.se/tre/?sok=trupp&pz=1
https://www.finlex.fi/sv/laki/alkup/1982/19820214
https://www.sanakirja.fi/custom/all/f%C3%B6rband
https://sv.wikipedia.org/wiki/F%C3%B6rband_(milit%C3%A4r)
