### ISSUE TITLE
prostituoidut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12344]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seksityöntekijät](http://www.yso.fi/onto/yso/p40083)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "gigolot", "huorat", "katunaiset", "katutytöt", miesprostituoidut", "seksinmyyjät" ja "rattopojat"

**Perustelut ehdotukselle**

Tällä hetkellä YSO antaa ymmärtää, että vain seksiä myyvät naiset voivat olla prostituoituja (ainoa KT-muoto kattaa naiset). Ks. myös https://www.kielitoimistonsanakirja.fi/huora, https://www.kielitoimistonsanakirja.fi/katutyttö, https://www.kielitoimistonsanakirja.fi/rattopoika jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Hups, ehdotuksen oli tarkoitus koskea [**prostituoidut**](http://www.yso.fi/onto/yso/p10351)-asiasanaa.

**Comment by YSO-kokous** [comment]
Poistetaan nykyinen ohjaustermi.
