### ISSUE TITLE
eudaimonia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12346]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

eudaimonia

**Ehdotettu termi ruotsiksi**

eudaimoni

**Ehdotettu termi englanniksi**

eudoinism

**Tarkoitusta täsmentävä selite**

https://filosofia.fi/fi/ensyklopedia/onnellisuus
"Eudaimonia tarkoitti siis sitä kuinka hyvin yksilön elämä on eletty tai kuinka onnistunut se ylipäänsä on" ja "Antiikin ajattelijat lähtivät siis liikkeelle antiikin arkipäiväisestä ajattelusta, jossa eudaimonia tarkoittaa ulkoisesti onnistunutta elämää. " ja kappale "Eudaimonia"
https://filosofia.fi/fi/eudaimoni ks. ruotsinkielinen selite 
"Eudaimonism (av gr. eudaimonia, lycka, lyckligt tillstånd, lycksalighet), filosofisk ståndpunkt enligt vilken det yttersta målet är - eller bör vara - lyckan"...

**Perustelut ehdotukselle**

On eri sisältöinen käsite kuin hedonismi (johon olisi hyvä liittää selite myös) vaikka LSCH:ssa Eudemonism on ohjauskäsitteenä USE Hedonism

**Ehdotettu yläkäsite YSOssa (LT)**

 [teoriat](http://www.yso.fi/onto/yso/p127)

**Ehdotetut temaattiset ryhmät**

 [02 Filosofia](http://www.yso.fi/onto/yso/p26545)

**Vaihtoehtoiset termit**

 Eudemonism

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [onnellisuus](http://www.yso.fi/onto/yso/p2416)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melindassa usea tekstiaineisto, jossa käsitellään termiä ja pari kirjaa, joiden nimekkeessä termi mainitaan. Esillä myös tässä kirjassa "Emotions in the digital world : ‡b exploring affective experience and expression in online interactions"

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [eudaimonia](http://finto.fi/yse/fi/page/Y512346)

**Comment by mirmaid** [comment]
Kerran Melindassa, 4 x _eudaimonismi_. 

https://fi.wikipedia.org/wiki/Eudaimonismi
https://tieteentermipankki.fi/wiki/Filosofia:eudaimonismi

**Comment by mariaforsen** [comment]
Sv. eudaimonism HT eudemonism, eudaimoni
https://filosofia.fi/sv/eudaimoni
https://svenska.se/tre/?sok=eudemonism&pz=1
https://www.psykologiguiden.se/psykologilexikon/?Lookup=eudaimoni

**Comment by YSO-kokous** [comment]
Eudaimonismi KT eudaimonia.
