### ISSUE TITLE
kolmikolkkahattu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12343]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kolmikolkkahattu

**Ehdotettu termi ruotsiksi**

trekornshatt

**Ehdotettu termi englanniksi**

tricorne

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Erittäin tunnettu hattumalli (ks. esim. https://en.wikipedia.org/wiki/Tricorne), jollaisia ja joita esittäviä kuvia löytyy museoista, mutta joiden kuvailuun ei ole täsmällistä asiasanaa YSO:ssa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578)

**Vaihtoehtoiset termit**

 trekantshatt, tricorn, cocked hat, three-cornered hat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q763457)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Search/Results?lookfor=kolmikolkkahattu&type=AllFields&filter%5B%5D=%7Eformat_ext_str_mv%3A%220%2FImage%2F%22

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kolmikolkkahattu](http://finto.fi/yse/fi/page/Y512343)

**Comment by mariaforsen** [comment]
Sv. tricorne HT trekantiga hattar, trekantshattar, trekornshattar 
/uppslagsverk/encyklopedi/lång/tricorne
https://www.sanakirja.fi/custom/en-sv-fi/kolmikolkkahattu
https://sv.wikipedia.org/wiki/Trekornshatt
