### ISSUE TITLE
kaksikolkkahattu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12342]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaksikolkkahattu

**Ehdotettu termi ruotsiksi**

bikorn

**Ehdotettu termi englanniksi**

bicorne

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Erittäin tunnettu hattumalli (ks. esim. https://en.wikipedia.org/wiki/Bicorne), jollaisia löytyy paljon museoista, mutta joiden kuvailuun ei ole täsmällistä asiasanaa YSO:ssa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578)

**Vaihtoehtoiset termit**

 bicorn, tvåhörning, båthatt, Napoleonhatten, cocked hat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q233104)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Search/Results?lookfor=kaksikolkkahattu&type=AllFields

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kaksikolkkahattu](http://finto.fi/yse/fi/page/Y512342)

**Comment by mariaforsen** [comment]
Sv. bicorne HT bikorn, tvåhörningar, napoleonhattar (huvudbonader)
https://samlingar.shm.se/object/43A6ACB9-ACB4-4BD2-B8D3-B006C948578F
uppslagsverk/encyklopedi/lång/bicorne
https://www.handelsgillet.se/produkt-kategori/hattar/
https://sv.wikipedia.org/wiki/Bicorne
