### ISSUE TITLE
eritrealaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12345]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

eritrealaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9789198649918

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [eritrealaiset](http://finto.fi/yse/fi/page/Y512345)

**Comment by mariaforsen** [comment]
Sv. eritreaner /sao
