### ISSUE TITLE
Borland Pascal with Objects

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12347]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Borland Pascal with Objects](http://www.yso.fi/onto/yso/p17589)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan.

**Perustelut ehdotukselle**

Vain yksi Melinda-hitti, vuodelta 1994.
https://melinda.kansalliskirjasto.fi/byid/000779281

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
