### ISSUE TITLE
avaruusoikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12353]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[avaruusoikeus](http://www.yso.fi/onto/yso/p17775)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko avaruuslainsäädäntö ohjaustermi?

**Perustelut ehdotukselle**

Esim. https://tem.fi/avaruuslaki 
https://julkaisut.valtioneuvosto.fi/handle/10024/160429

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Vastaavia on joitakin.

**Comment by mariaforsen** [comment]
Sv. HT rymdjuridik, rymdlagstiftning
