### ISSUE TITLE
joulumarkkinat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12354]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

joulumarkkinat

**Ehdotettu termi ruotsiksi**

julmarknader

**Ehdotettu termi englanniksi**

Christmas markets

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Olennainen osa joulua, vuosittainen joulutapahtuma (tämä käsite myös puuttuu YSO:sta).

**Ehdotettu yläkäsite YSOssa (LT)**

 [markkinat (tapahtumat)](http://www.yso.fi/onto/yso/p24062), [jouluperinne](http://www.yso.fi/onto/yso/p28264)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

 pohjoissaame: juovlamárkanat, suomi: joulutorit, englanti: Christmas fairs

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q57607), [LOC](https://id.loc.gov/authorities/subjects/sh2023000972.html), [Yle](https://yle.fi/aihe/t/18-127840)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Finnassa olevien kuvien kuvailussa ja Commonsissa. 

**Ehdottajan organisaatio**

WMFI-AG/Kimberli
**Termiehdotus Fintossa:** [joulumarkkinat](http://finto.fi/yse/fi/page/Y512354)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by LeKorsu** [comment]
Joulutorit ohjaustermiksi

**Comment by YSO-kokous** [comment]
Joulutorit KT joulumarkkinat

**Comment by mariaforsen** [comment]
Sv. julmarknader HT jultorg
https://www.imt.fi/teemat/tapahtumia-ja-elamyksia/euroopan-upeat-joulutorit/
https://resebokningen.se/artiklar/basta-julmarknaderna-i-europa/
https://svenska.se/tre/?sok=julmarknad&pz=1
https://www.sanakirja.fi/custom/en-sv-fi/joulutori
https://id.kb.se/term/sao/Julmarknader
https://sv.wikipedia.org/wiki/Julmarknad
