### ISSUE TITLE
perheryhmäkodit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12356]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

perheryhmäkodit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

---

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

---

**Ehdottajan organisaatio**

Suomi.fi-palvelutietovaranto, Digi- ja väestötietovirasto
**Termiehdotus Fintossa:** [perheryhmäkodit](http://finto.fi/yse/fi/page/Y512356)

**Comment by mirmaid** [comment]
Ehdottajan lisäys:
Tätä tarvittaisiin asiasanaksi Suomi.fi-palvelutietovarantoon. Tarve nousi Hyvinvointialueiden palveluluokituksen ja PTV:n käyttämän Julkisten palveluiden ja järjestöpalveluiden luokituksen yhteensovittamisessa.

Kyseessä on Hyvinvointialueiden palveluluokituksen palvelu 2940 Maahanmuuttajien sosiaalipalvelut, joka sisältää ilman huoltajaa maassa olevien lasten ja nuorten perheryhmäkotitoiminnan. Valitettavasti en löydä tähän hätään mistään tälle käännösversioita.

**Comment by mariaforsen** [comment]
Sv. familjegrupphem HT barnhem för familjegrupper
https://www.sanakirja.fi/custom/en-sv-fi/perheryhm%C3%A4koti
https://termipankki.fi/tepa/fi/haku/perheryhm%C3%A4koti
https://kotoutuminen.fi/perheryhmakodit-selkosuomi

Tässä https://www.theseus.fi/bitstream/handle/10024/266148/Iisakkila_Tatu.pdf?sequence=2&isAllowed=y eng. family group home
