### ISSUE TITLE
tiehöylät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12350]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tiehöylät

**Ehdotettu termi ruotsiksi**

väghyvlar

**Ehdotettu termi englanniksi**

road graders

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [tiekoneet](http://www.yso.fi/onto/yso/p8155)

**Ehdotetut temaattiset ryhmät**

 [37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568), [39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)

**Vaihtoehtoiset termit**

 tiekarhut

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Tieh%C3%B6yl%C3%A4), [LCSH](http://id.loc.gov/authorities/subjects/sh85056167), [TEPA](https://termipankki.fi/tepa/fi/haku/tieh%C3%B6yl%C3%A4), [LIIKO](http://www.yso.fi/onto/mero/m10802)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Man and the machine :articles from Northern European road history /edited by Mikko Pentti.

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [tiehöylät](http://finto.fi/yse/fi/page/Y512350)

**Comment by mariaforsen** [comment]
Sv. väghyvlar HT vägbjörnar, vägskrapor
