### ISSUE TITLE
peräkärryt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12352]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

peräkärryt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Peräkärry on pienehkö henkilöauton, pakettiauton, mönkijän tai traktorin vetämä kärry. Perävaunu-nimitystä käytetään lähinnä kuorma-auton tms. isommasta kuljetusvälineestä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ajoneuvojen kuljetusvälineitä käsittelevä aineisto. 

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [peräkärryt](http://finto.fi/yse/fi/page/Y512352)

**Comment by mirmaid** [comment]
_Perävaunut_ on siis sanastossa.

11 x Melindassa.

**Comment by ilona-x** [comment]
Englanniksi peräkärry & perävaunu taitavat olla molemmat trailer eli vaatinee tarkenteen ainakin englanniksi?

**Comment by ilona-x** [comment]
Voisiko tehdä ohjauksen peräkärryt KÄYTÄ perävaunut?

Esim. täällä puhutaan perävaunuista:
"Tavallisena jarruttomana henkilö- ja pakettiauton peräkärrynä yleisesti tunnettu O1-luokan perävaunu "
Lähde: https://www.traficom.fi/fi/liikenne/tieliikenne/usein-kysyttya-peravaunujen-massojen-saantelysta

**Comment by mariaforsen** [comment]
Släpkärra voisi periaatteessa olla erikseen alakäsitteenä, mutta on varmaan myös ok laittaa suppeampana ohjaustermiksi. 
https://sv.wikipedia.org/wiki/Sl%C3%A4pvagn
https://www.rikstermbanken.se/search?q=sl%C3%A4pk%C3%A4rra&s=termer

**Comment by LeKorsu** [comment]
Ohjaus peräkärryt KÄYTÄ perävaunut ok, jos se käy, että perävaunuilla tarkoitetaan sekä henkilöauton että rekan vetämää perävaunua. Silloin trailers tuskin tarvitsee tarkennetta.

Yksi vaihtoehto on  ottaa ja-yhdistelmä: peräkärryt ja perävaunut. Yleiskielessä tosin näyttävät olevan aika lailla sekaisin synonyymikäytössä.

**Comment by YSO-kokous** [comment]
KÄ perävaunut
