### ISSUE TITLE
piispanvihkimys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12355]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[piispanvihkimys](http://www.yso.fi/onto/yso/p27605)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään englanninkielinen viittausmuoto "installations of bishops"

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Installation_(Christianity)

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Lisätty ohjaustermi installation of bishops

**Comment by jtuohini** [comment]
Varmaan kuitenkin monikossa "installations", ei siis "isstallation"?

**Comment by tpalonen** [comment]
Yksikössä koska myös muut kielet ja termit ovat yksikössä tällä käsitteellä

**Comment by jtuohini** [comment]
Tietysti! Oli niin kirkkaana mielessä, että oli suomeksikin monikossa. Pahoitteluni turhasta lisävaivasta.
