### ISSUE TITLE
laitostuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12359]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laitostuminen](http://www.yso.fi/onto/yso/p12590)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitseeko tarkennusta?

**Perustelut ehdotukselle**

Joitakin kertoja käytetty eri merkityksessä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Aina merkitys ei ole pelkän viitetiedon perusteella selvä. Näissä ehkä eri merkitys:

https://melinda.kansalliskirjasto.fi/byid/005310773
https://melinda.kansalliskirjasto.fi/byid/013138091
https://melinda.kansalliskirjasto.fi/byid/012750081

**Comment by mariaforsen** [comment]
Sv. on hospitalisering, eli aivan väärä termi jos kyseessä ykkösmerkitys "muuttua laitosmaiseksi, institutionaalistua, institutionalisoitua"
https://www.kielitoimistonsanakirja.fi/#/laitostua?searchMode=all

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a1ffa769eeaee14511c89af03f417a29&list_id=1&keyword=laitostua&word=laitostua

**Comment by mirmaid** [comment]
Käytetty Melindassa 59 kertaa, nuo kolme sellaisia, joissa mahdollisesti eri merkitys (keskimmäisessä voi olla myös oikea). Käytetty joitakin kertoja myös eläimistä, jos se halutaan pitää mahdollisena, psykologia ei varmaan sovi tarkenteeksi.

**Comment by mariaforsen** [comment]
Psykologia sopii mielestäni myös kalojen kohdalla. Jos kyseessä on aivottomia eläimiä niin silloin ei psykologia varmaan sovi, mutta sellaisia viitteitä ei tainnut olla.

**Comment by mariaforsen** [comment]
Nykyinen vastine sv. hospitalisering ei kyllä sovi eläimistä.

**Comment by mirmaid** [comment]
Sopiiko muuten hospitalisering myös kun kyse ei ole sairaalahoidon aiheuttamasta laitostumisesta, vaan vaikkapa vankien kohdalla? Mietin vaan sv. wikipedian ja nationalencyklopedin pohjalta.

**Comment by mariaforsen** [comment]
Ei taida oikein sopia vangeista (ellei vankilaa mielletä hoitolaitokseksi). 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a1ffa769eeaee14511c89af03f417a29&list_id=1&keyword=laitostua&word=laitostua

Tämä onkin ongelmistalla, ehdotuksena että muutettaisiin > institutionalisering (individer)? Jolloin sopisi myös vangeista.

**Comment by mirmaid** [comment]
On siis käytetty vankiloista, ja lisäksi koulutuksen ja lastenhoidon yhteydessä (eniten toki vanhustenhuollon ja sairaanhoidon yhteydessä).

**Comment by mariaforsen** [comment]
Päätermin muutos ruotsiksi onnistuu siis, kunhan saadaan ykkösmerkitys (muuttua laitosmaiseksi, institutionaalistua, institutionalisoitua) poisrajattu?
https://www.kielitoimistonsanakirja.fi/#/laitostua?searchMode=all

**Comment by mirmaid** [comment]
Jos ei ole tarpeen (tai edes haluta) että katetaan myös eläimiä, voisi olla myös _laitostuminen (psykologia)_.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Lisätään sulkutarkenne: laitostuminen (psykologia)

**Comment by mariaforsen** [comment]
Sv hospitalisering > institutionalisering (psykologi) 
https://www.psykologiguiden.se/psykologilexikon/?Lookup=institutionalisering
https://termipankki.fi/tepa/fi/haku/laitostuminen[](url)
https://mesh.kib.ki.se/term/D007326/institutionalization
