### ISSUE TITLE
kielimalli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12365]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kielimalli

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailussa tulee nyt paljon esille tekoälyyn  ja siihen liittyviä olennaisia käsitteitä. Kielimalli-asiasanaa ei löytynyt.  Tarkistettu KOKO-ontologiasta sekä YSOsta.
(Huomiona että asiasana tietomalli sen sijaan löytyy).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tekoälyä koskevissa tieteellisissä julkaisuissa, ja oppimateriaalituotannossa. Julkaisut lisääntyvät jatkuvasti 
Tässä vain yksi esimerkki Theseuksesta:  Julkaisun pysyvä osoite on
https://urn.fi/URN:NBN:fi-fe20231107143424

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kielimalli](http://finto.fi/yse/fi/page/Y512365)

**Comment by mirmaid** [comment]
Ei Melindassa.

https://fi.wikipedia.org/wiki/Kielimalli

**Comment by LeKorsu** [comment]
Kannatan ottamista. Monikossa?

**Comment by mariaforsen** [comment]
Sv. språkmodeller
https://sv.wikipedia.org/wiki/Spr%C3%A5kmodell
https://www.ri.se/sv/berattelser/resurseffektiva-sprakmodeller-for-hela-manskligheten
https://www.ai.se/sv/projekt/sprakmodeller-svenska-myndigheter

**Comment by YSO-kokous** [comment]
KT suuret kielimallit
