### ISSUE TITLE
biologinen antropologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12363]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[biologinen antropologia](http://www.yso.fi/onto/yso/p3879)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermi:
bioantropologia

**Perustelut ehdotukselle**

Käytössä

**Ehdottajan organisaatio**

kk

**Comment by mariaforsen** [comment]
Sv. HT bioantropologi
