### ISSUE TITLE
systemaattiset kirjallisuuskatsaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12369]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[systemaattiset kirjallisuuskatsaukset](http://www.yso.fi/onto/yso/p29683)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-sanastoon

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan, kun löytyy tällaista aineistoa Melindassakin, esim. Ukrainan sodan terveydenhuollosta - systemaattinen kirjallisuuskatsaus.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
