### ISSUE TITLE
Laatukamari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12367]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Laatukamari](http://www.yso.fi/onto/yso/p18152)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan

**Perustelut ehdotukselle**

Vain yhden kerran Melindassa, vuodelta 1997. Tavallisehkona suomen sanana ehkä tässä olisi riskiä käyttää tätä myös väärin jossakin väärässä merkityksessä.
https://melinda.kansalliskirjasto.fi/byid/011532524

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Ei tämä varmaan kauhean hyödyllinen ole, vaikka en ehkä näe että tässä varsinaista virheellisen käytön riskiä on (Googlellakin ihan johdonmukaisesti).

**Comment by YSO-kokous** [comment]
Poistetaan.
