### ISSUE TITLE
lapsenmurha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12361]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lapsenmurha](http://www.yso.fi/onto/yso/p6913)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään viittausmuoto "lapsensurma"

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/lapsensurma

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Joka synnytyksestä johtuvassa uupumuksessa tai ahdistuksessa surmaa lapsensa, on tuomittava lapsensurmasta vankeuteen vähintään neljäksi kuukaudeksi ja enintään neljäksi vuodeksi. https://www.finlex.fi/fi/laki/ajantasa/1889/18890039001

Lapsenmurha-termiä käytetty Melindassa laajemmin kuin alkuperäisen rikoslain merkityksessä, eikä sekään taida olla sama kuin tämä nykyisen rikoslain lapsensurma.

**Comment by mariaforsen** [comment]
Eivätkö nämä ole eri asioita, kun lakikin erittelee? Dråp ja mord ovat ainakin juridisesti eri asioita. 
Sv. -barnamord = lapsenmurha
-barnadråp = lapsensurma

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä, tutkitaan eng. vastine ja linkitys. Pitäisikö olla erikseen lapsensurma?

**Comment by tpalonen** [comment]
Vaihdettu englannin termiksi child murder, poistettu LCSH-linkitys ja muutettu Wikidata-linkitys tähän:
https://www.wikidata.org/wiki/Q13587273
