### ISSUE TITLE
urheilu- ja liikuntaseurat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12374]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[urheilu- ja liikuntaseurat](http://www.yso.fi/onto/yso/p2041)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

voisiko lisätä ohjaustermiksi myös liikunta- ja urheiluseurat?

**Perustelut ehdotukselle**

aina ei muista, kumminpäin liikunta ja urheilu tässä yhdistelmätermissä olivatkaan 

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
vastaavan lisäyksen voisi tehdä myös urheilu- ja liikuntajärjestöt -termille eli ohjaustermiksi liikunta- ja urheilujärjestöt
