### ISSUE TITLE
Finlandia Junior -palkinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12373]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Finlandia Junior -palkinto](http://www.yso.fi/onto/yso/p26798)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lasten- ja nuortenkirjallisuuden Finlandia

**Perustelut ehdotukselle**

palkinnon nimi muuttunut jo vuonna 2016. 
Wikipedia: Lasten- ja nuortenkirjallisuuden Finlandia-palkinto (ennen vuotta 2016 Finlandia Junior -palkinto) 

**Ehdottajan organisaatio**

Kuopion kaupunginkirjasto

**Comment by mariaforsen** [comment]
Sv. Finlandiapriset i barn- och ungdomslitteratur https://kirjasaatio.fi/sv/
https://www.finlex.fi/sv/laki/alkup/2022/20221137
