### ISSUE TITLE
kirjallisuuskatsaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12370]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kirjallisuuskatsaukset](http://www.yso.fi/onto/yso/p7595)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-sanastoon

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan, aineistoa on, esim. Kaduilla, poluilla ja puutarhoissa : iäkkäiden ihmisten ulkona liikkuminen ja hyvinvointi.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
