### ISSUE TITLE
johdannaisteokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12378]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

johdannaisteokset

**Ehdotettu termi ruotsiksi**

härledda verk

**Ehdotettu termi englanniksi**

derivative works 

**Tarkoitusta täsmentävä selite**

SLM-sanastoon. RDA-termi: "teos, joka on toisen teoksen muunnos [modification]". 

**Perustelut ehdotukselle**

Tarvitaan SLM-yläkäsitteeksi (mm. termille "mukaelmat"). 

Alakäsitteiksi SLM-sanastossa:

juonitiivistelmät 
katkelmat
lyhennelmät (nykyisen yläkäsitteen "mukaelmat" sijaan) 
mukaelmat
muunnelmat (musiikki)
näköispainokset 
parafraasit (musiikki) 
rinnakkaisteokset 
sovitukset (musiikki) (nykyisen yläkäsitteen "mukaelmat" sijaan)
uusintatuotantoelokuvat

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

 johdetut teokset 

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [derivative works ](https://lccn.loc.gov/gf2014026084), [Härledda verk](https://id.kb.se/term/saogf/H%C3%A4rledda%20verk)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tarvitaan SLM-yläkäsitteeksi. 

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [johdannaisteokset](http://finto.fi/yse/fi/page/Y512378)

**Comment by mirmaid** [comment]
Toivottiinko myös määritelmää mukaelmat-käsitteelle? Täällä ehdotus: https://github.com/Finto-ehdotus/YSE/issues/11052#issuecomment-1531075395

**Comment by mirmaid** [comment]
Huom. myös mukaelmat ja rinnakkaisteokset -termien hierarkia! Mahdollisuuksien mukaan sama ratkaisu YSOon?

**Comment by mirmaid** [comment]
Seuraava kokous.

**Comment by AuHo22** [comment]
Sama määritelmä on metatietosanastossa kohdassa **mukaelma (teos**), joskin joissakin versioissa _viestintäväline_ on korvattu _esitysmuodolla_, esim. **mukaelman perustana (teos)**? ->
Mukaelma on "[t]eos, joka on muokattu jotain muuta kuin alkuperäistä tarkoitusta, käyttöä tai viestintävälinettä/esitysmuotoa varten. Kattaa sekä teoksen muotoon kohdistuvat muutokset että samassa muodossa kokonaan uudelleenmuokatut teokset." ([RDA, liite J.2.2]

**Comment by mirmaid** [comment]
Alakäsitteet: 
juonitiivistelmät
_katkelmat /ei_
lyhennelmät (nykyisen yläkäsitteen "mukaelmat" sijaan)
mukaelmat
_muunnelmat (musiikki) /ei
näköispainokset /ei_
parafraasit (musiikki)
rinnakkaisteokset
_sovitukset (musiikki) (nykyisen yläkäsitteen "mukaelmat" sijaan) /ei_ (suoraan musiikin alle)
uusintatuotantoelokuvat

**Comment by mirmaid** [comment]
Mukaelmat alakäsitteet:
dramatisoinnit
filmatisoinnit
lyhennelmät YK johdannaisteokset
näytelmäsovitukset 
romaanisovitukset
sarjakuvasovitukset
sovitukset (musiikki)

**Comment by mirmaid** [comment]
Mukaelma on teos, joka on muokattu jotain muuta kuin alkuperäistä tarkoitusta, käyttöä, viestintävälinettä tai esitysmuotoa varten. Kattaa sekä teoksen muotoon kohdistuvat muutokset että samassa muodossa kokonaan uudelleenmuokatut teokset (esim. proosateoksen runomukaelma).

**Comment by mirmaid** [comment]
YSO?

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
