### ISSUE TITLE
tilannekeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12379]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tilannekeskukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Tilannekeskus (lyh. Tike) on paikka, jossa keskitetysti ja jatkuvasti seurataan erilaisia tilanteita ja välitetään tieto eteenpäin. Sellaisia on esimerkiksi poliisilla,  pelastustoimella ja ensihoidossa.

**Perustelut ehdotukselle**

Jo pelkästään Finnasta löytyy "tilannekeskukset" sanalla yli 10000 hakutulosta, joista usea tarvitsisi oman virallisen asiasanan.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

www.urn.fi/URN:ISBN:978-952-324-247-0

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tilannekeskukset](http://finto.fi/yse/fi/page/Y512379)

**Comment by mirmaid** [comment]
Ei Melindassa. 

https://fi.wikipedia.org/wiki/Tilannekeskus

**Comment by mariaforsen** [comment]
Sv. lägescentraler
https://termipankki.fi/tepa/fi/haku/tilannekeskus
https://www.finlex.fi/sv/laki/ajantasa/2017/20170300

**Comment by fantsby-m** [comment]
Finnasta löytyy mainitulla hakusanalla (lainausmerkeissä) 65 hakutulosta. Ehdotuksessa mainitut yli 10000 saa jos hakee ilman lainausmerkkejä, mutta sumea haku löytää silloin kaikenlaista epärelevanttia valtavat määrät.

**Comment by LeKorsu** [comment]
Jupossa on johtokeskukset, pitääkö jotenkin määritellä suhdetta siihen käsitteeseen (vaikkei sitä ysossa olekaan)?
https://finto.fi/jupo/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fjupo%2Fp943
Jupossa ei ole tilannekeskuksia.

**Comment by mirmaid** [comment]
Näköjään tosiaan esiintyvät säännöllisesti yhdessä ja myös esimerkkiaineistossa "tike" ja "joke".

**Comment by mirmaid** [comment]
**Tilannekeskus (TIKE)**
Tilannekeskus on paikka tai organisaatio, jossa kerätään ja muokataan tietoa johtamista ja päätöksentekoa varten. Tilannekeskus voi toimia johtokeskuksen osana. (Kokonaisturvallisuuden sanasto 2014, 106) 

Tilannekeskus voi olla myös yhteinen useamman pelastuslaitoksen ja/tai viranomaisen kanssa. Tilannekeskus on valmiudessa 24/7 tai tarvittaessa perustettavissa. TIKE:n päätehtävä on pelastustoiminnan ja sen johtamisen tukeminen keräämällä tarvittavaa tietoa päätöksenteon tueksi ja tilannekuvan muodostamiseksi sekä välittää tietoa yhteistoimintatahoille. TIKE ylläpitää omaa tilannepäiväkirjaa. Pel-JoKen perustamisen jälkeen TIKE voi toimia tarvittaessa myös Pel-JoKen viestikeskuksena.

**Comment by mirmaid** [comment]
**Johtokeskus**
Toiminnan johtamista varten perustettu toiminnallinen kokonaisuus, joka käsittää henkilöstön, tilan ja välineet.

Johtokeskus voi tarkoittaa suppeammin myös kiinteää, erikseen suunniteltua tilaa, josta toimintaa johdetaan. Johtokeskus voidaan tarvittaessa (erikseen säädettäessä, esimerkiksi pelastustoimen johtokeskus) sijoittaa väestönsuojista annettujen normien mukaiseen tilaan, jossa johtaminen on mahdollista myös poikkeusoloissa. Johtokeskuksia ovat esimerkiksi sisäministeriön johtokeskus, kunnan johtokeskus, kuntayhtymän johtokeskus ja alueen pelastustoimen johtokeskus.

Englannin termit ”situation centre” ja ”situation center” voidaan ymmärtää myös suppeammin tarkoittamaan johtokeskuksen osana olevaa tilannekeskusta (Kokonaisturvallisuuden sanasto 2014, 106).

Johtokeskustoiminnot voivat olla tarvittaessa hajautettuna, kuten pelastuslaitosten yhteinen tilannekeskus (Helismaa 2015).

**Pelastustoiminnan johtokeskus (PEL-JOKE)**
Pel-JoKe on pelastustoiminnan johtokeskus ja sen perustaa pelastusviranomainen. Häiriötilanteiden aikaista toiminnan johtamista varten perustettu toiminnallinen kokonaisuus, joka käsittää henkilöstön, tilan, välineet ja toiminta-asiakirjat.

Alueen pelastustoimen tulee kyetä perustamaan tilanteen aikainen johtokeskus. Suurissa onnettomuustilanteissa johtokeskuksia voi olla tarpeen perustaa usealle johtamistasolle. Johtokeskuksen on tarvittaessa kyettävä koordinoimaan pelastustoimen ja yhteistoimintatahojen voimavarojen tehokasta käyttöä. (Pelastustoimen toimintavalmiuden suunnitteluohje 2012, 10.)

https://www.pelastuslaitokset.fi/sites/default/files/2020-11/Pelastustoiminnan%20k%C3%A4sitteit%C3%A4%202.p%C3%A4ivitetty%20versio%202016.pdf

**Comment by ilona-x** [comment]
**fi        johtokeskus**
sv       ledningscentral
en      command centre; command center /US/; operation centre; operation center /US/; situation centre (2); situation center (2) /US/; control centre; control center /US/

määritelmä
toiminnan johtamista varten perustettu toiminnallinen kokonaisuus, joka käsittää henkilöstön, tilan ja välineet

huomautus
Johtokeskus voi tarkoittaa suppeammin myös kiinteää, erikseen suunniteltua tilaa, josta toimintaa johdetaan. Johtokeskus voidaan tarvittaessa (erikseen säädettäessä, esimerkiksi pelastustoimen johtokeskus) sijoittaa väestönsuojista annettujen normien mukaiseen tilaan, jossa johtaminen on mahdollista myös poikkeusoloissa.
Johtokeskuksia ovat esimerkiksi sisäministeriön johtokeskus, kunnan johtokeskus, kuntayhtymän johtokeskus ja alueen pelastustoimen johtokeskus.
Englannin termit ”situation centre” ja ”situation center” voidaan ymmärtää myös suppeammin tarkoittamaan johtokeskuksen osana olevaa tilannekeskusta.

Lähde: Kokonaisturvallisuuden sanasto (TSK 50, 2017) https://termipankki.fi/tepa/fi/haku/johtokeskus


	  

**fi        tilannekeskus**
sv       lägescentral
en      situation centre (1); situation center (1) /US/

määritelmä
paikka tai organisaatio, jossa kerätään ja muokataan tietoa johtamista ja päätöksentekoa varten

huomautus
Tilannekeskus voi toimia johtokeskuksen osana.

Lähde: Kokonaisturvallisuuden sanasto (TSK 50, 2017) https://termipankki.fi/tepa/fi/haku/tilannekeskus

**Comment by YSO-kokous** [comment]
Hyväksytään sekä johtokeskukset, että tilannekeskukset.

**Comment by mariaforsen** [comment]
Sv. -ledningscentraler HT ledningscentrum (centraler)
https://www.rikstermbanken.se/search?q=ledningscentral&s=termer
https://termipankki.fi/tepa/fi/haku/johtokeskus
-lägescentraler
https://termipankki.fi/tepa/fi/haku/tilannekeskus
https://www.finlex.fi/sv/laki/ajantasa/2017/20170300
