### ISSUE TITLE
DisCo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12371]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[DisCo](http://www.yso.fi/onto/yso/p18393)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan tai sulkutarkenne

**Perustelut ehdotukselle**

Tämä on ohjelmointikielen nimi, mutta tätä on käytetty ilmeisesti vain kaksi kertaa oikein Melindassa ja kymmenen kertaa väärin, kun on luultu musiikkitermiksi.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Saattaa olla useampia saman nimisiä (?). Tämä siis jo 90-luvulta.
