### ISSUE TITLE
Autionjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12372]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Autionjoki](http://www.yso.fi/onto/yso/p113493)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennus nimelle, mm. "Autionjoki (Korpilahti)" tai "Autionjoki (Raspion laskuoja)"

**Perustelut ehdotukselle**

Tarkentamattoman nimen voi sekoittaa toiseen nykyisen Jyväskylän kunnan alueella olevaan jokeen: Luonetjärvestä alkavaan Autiojokeen, etenkin, kun tällaista "genetiivi-nominatiivi-vaihtelua" esiintyy joissakin paikannimissä (mm. Laukaan Kuhanniemi - Kuhaniemi)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tämä toinen johon viitataan on siis Autiojoki, http://paikkatiedot.fi/so/1000772/10716862.

Autionjoki: http://paikkatiedot.fi/so/1000772/10160978

**Comment by mirmaid** [comment]
Autionjokia on Suomessa kaksi, joten lisätään tarkenne (Jyväskylä). Sanastokokous ei kuitenkaan pitänyt tarpeellisena tarkempaa tarkennetta, koska joilla virallisesti on eri nimet, vaikka ero onkin pieni.
