### ISSUE TITLE
tšerkessit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12386]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tšerkessit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailen kirjoja, jotka käsittelevät tšerkessien historia ja kansatiedettä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Tšerkessit](https://fi.wikipedia.org/wiki/T%C5%A1erkessit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Bliki skazanij čerkesov, isbn 978-5-6049669-6-9

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [tšerkessit](http://finto.fi/yse/fi/page/Y512386)

**Comment by mariaforsen** [comment]
Sv. tjerkesser HT circasser, kirkassier
