### ISSUE TITLE
lauseet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12389]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lauseet](http://www.yso.fi/onto/yso/p21419)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Huomioidaan sanastossa myös "virkkeet" joko viittausmuotona tähän tai itsenäisenä asiasananaan.

**Perustelut ehdotukselle**

Keskeinen käsite kielitieteessä, ks. esim. https://tieteentermipankki.fi/wiki/Kielitiede:virke.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Vain pari kertaa Melindassa.

**Comment by mariaforsen** [comment]
Viitataanko ykkösmerkitykseen: https://www.kielitoimistonsanakirja.fi/#/lause?searchMode=all > sv. riippuu merkityksestä: https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1ee971446d26543bcb27c2b8e296ecae&list_id=1&keyword=lause&word=lause 
Nykyinen vastine on satser, meningar=virkkeet puuttuu vielä.

**Comment by mirmaid** [comment]
^ _Lauseet_ on siis sanastossa kielitieteen käsitteenä, ehdotus siis _virkkeet_-termin lisääminen ohjaustermiksi tai erilliseksi asiasanaksi.

**Comment by jtuohini** [comment]
Virke-sana esiintyy useissa nimekkeissä, myös ilman **lauseet**-asiasanaa, joten hyvä se olisi huomioida sanastossa. Ks. esim. https://melinda.kansalliskirjasto.fi/byid/007017461, https://melinda.kansalliskirjasto.fi/byid/005711644, https://melinda.kansalliskirjasto.fi/byid/005282409 jne.

**Comment by YSO-kokous** [comment]
Hyväksytään virkkeet erikseen.

**Comment by mariaforsen** [comment]
Sv. meningar
