### ISSUE TITLE
adygeit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12385]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

adygeit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailen kirjoja, jotka käsittelevät adygien historia ja kansatiedettä

**Ehdotettu yläkäsite YSOssa (LT)**

 [väestöryhmään liittyvä rooli](http://www.yso.fi/onto/yso/p487)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Adygeit](https://fi.wikipedia.org/wiki/Adygeit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Adygskij geroičeskij èpos, isbn 978-5-9208-0587-4; 
Alʹternativnye izyskaniâ po abazo-adygskoj istorii, isbn 978-5-4461-0905-0

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [adygeit](http://finto.fi/yse/fi/page/Y512385)

**Comment by mariaforsen** [comment]
Sv. adygeer /ne HT adygéer
https://sv.wikipedia.org/wiki/Adyg%C3%A9er
https://www.ne.se/s%C3%B6k/?t=uppslagsverk&q=adyge
