### ISSUE TITLE
omaishoitovapaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12383]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

omaishoitovapaa

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://tyosuojelu.fi/tyosuhde/muut-vapaat-tyosta/perhevapaat/omaishoitovapaa

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [perhevapaat](http://www.yso.fi/onto/yso/p2449)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Työpaikan vapaat ja poissaolot käytännönläheisesti 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [omaishoitovapaa](http://finto.fi/yse/fi/page/Y512383)

**Comment by tpalonen** [comment]
Ehdotettu muoto lienee yleisempi, mutta esiintyy myös muotoa _omaishoitajan vapaa_. Ohjaustermiksi?
https://omaishoitajat.fi/tuet-ja-palvelut/omaishoidon-tuki/omaishoitajien-vapaat/
https://stm.fi/omaishoito
https://thl.fi/fi/web/vammaispalvelujen-kasikirja/oikeuskaytanto/omaishoidontuki/omaishoitajan-vapaan-jarjestaminen

**Comment by mirmaid** [comment]
^ Eri asia? Tässä käsittäkseni on kyse oikeudesta vapaapäiviin palkkatyöstä omaisen hoidon takia, omaishoitajan vapaalla taas viitataan yleensä vapaapäiviin omaishoidosta.

**Comment by mariaforsen** [comment]
Kaksi eri asiaa. Sv. 
-ledighet för vård av anhörig HT ledighet för närståendevård 
(fi omaishoitovapaa)   
https://termipankki.fi/tepa/fi/haku/omaishoitovapaa
https://finlex.fi/sv/laki/alkup/2022/20220032

-ledighet för närståendevårdare HT närståendevårdares ledighet
(fi omaishoitajan vapaa)
https://www.finlex.fi/sv/laki/ajantasa/2005/20050937
https://thl.fi/sv/publikationer/handbocker/handbok-om-funktionshinderservice/rattspraxis/rattspraxis-om-narstaendevard/ordnande-av-ledighet-for-narstaendevardare
https://www.kommunforbundet.fi/cirkular/2005/ny-lag-om-stod-narstaendevard

**Comment by YSO-kokous** [comment]
Hyväksytään sekä omaishoitajan vapaa että omaishoitovapaa.  
Omaishoitovapaa (omaishoitajan vapaa) KÄ omaishoitajan vapaa.
