### ISSUE TITLE
sosiaalityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12388]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sosiaalityö](http://www.yso.fi/onto/yso/p3286)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lapsityö, nuorisotyö, pakolaistyö - mikä on suhde sosiaalityöhön?

**Perustelut ehdotukselle**

YSAssa RT, YSOssa vain pakolaistyö

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Mitähän tässä on ehdotettu?
YSOssa kaikilla mainituilla eli lapsityö, nuorisotyö, pakolaistyö, on RT sosiaalityö

Kielitoimiston sanakirja:
**lapsityö** https://www.kielitoimistonsanakirja.fi/#/lapsity%C3%B6?searchMode=all
lasten parissa tehtävä, vars. seurakunta-, sosiaali- t. vapaa-ajan työ.
Kirkon lapsi- ja nuorisotyö.
Seurakunnan lapsityön ohjaaja.
Lapsityötä tekevät yhdistykset ja urheiluseurat.


**nuorisotyö** https://www.kielitoimistonsanakirja.fi/#/nuorisoty%C3%B6?searchMode=all
nuorten harrastustoimintaa ja persoonallista kehitystä tukeva työ.
Kirkon, urheiluseurojen nuorisotyö.
Etsivä nuorisotyö ks. etsiä 1.

**Comment by mirmaid** [comment]
Voi olla, että olen itse lisännyt nuo RT-suhteet samalla kun kirjasin tämän issuen. Mutta varmaan pohdin samalla sitä, miksi suhde ei ole ST (vrt. miestyö, naistyö).
