### ISSUE TITLE
raskausvapaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12381]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

raskausvapaa

**Ehdotettu termi ruotsiksi**

graviditetsledighet

**Ehdotettu termi englanniksi**

pregnancy leave

**Tarkoitusta täsmentävä selite**

https://tem.fi/hoitovapaa

**Perustelut ehdotukselle**

tarve kuvailusssa

**Ehdotettu yläkäsite YSOssa (LT)**

 [perhevapaat](http://www.yso.fi/onto/yso/p2449)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [äitiysvapaa](http://www.yso.fi/onto/yso/p2451)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Työpaikan vapaat ja poissaolot käytännönläheisesti

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [raskausvapaa](http://finto.fi/yse/fi/page/Y512381)

**Comment by LeKorsu** [comment]
On jo äitysvapaa + vanhempainvapaa. Yritin hakea raskausvapaata Kelan sivustolta, mutta vastaan tuli lähinnä raskausrahaa.
EDIT: No, TEMin sivuilta näyttää löytyvän myös raskausvapaa, mutta onko tämä kuinka sama asia kuin äitiysvapaa. Pitäisikö raskausvapaa ottaa preflabeliksi ja äitiysvapaa sen ohjaustermiksi?
https://tem.fi/hoitovapaa

**Comment by mariaforsen** [comment]
Sv. graviditetsledighet HT gravidledighet
https://tem.fi/sv/vardledighet

"Raskausvapaa alkaa yleensä 30 arkipäivää ennen lapsen laskettua syntymäaikaa. Voit myös sopia työnantajasi kanssa, että jäät raskausvapaalle myöhemmin, mutta vapaa pitää aloittaa kuitenkin viimeistään 14 arkipäivää ennen laskettua aikaa. Jos et ole työsuhteessa, voit jäädä raskausvapaalle oman valintasi mukaan 14–30 arkipäivää ennen laskettua aikaa. Kela maksaa raskausrahaa 40 arkipäivältä riippumatta lapsen todellisesta syntymähetkestä." 

Äitiysvapaa: "Äitiysvapaan pituus on 105 arkipäivää. Oikeus äitiysrahaan alkaa aikaisintaan 50 arkipäivää ja viimeistään 30 arkipäivää ennen laskettua synnytysaikaa. " /https://termipankki.fi/tepa/fi/haku/%C3%A4itiysvapaa

Toisaalta kun lainsäädäntö on muuttunut niin miten tehdään?
"1.8.2022 voimaan tulleen perhevapaauudistuksen myötä äitiysvapaa muuttuu raskausvapaaksi. Raskausvapaa (40 päivää) on yhtäjaksoinen ja se tulee aloittaa 14–30 päivää ennen laskettua aikaa. "
/https://www.ytkpalvelut.fi/tyoelamaopas/perhevapaat-perhevapaa/raskausvapaa/
