### ISSUE TITLE
maabiologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12384]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maabiologia](http://www.yso.fi/onto/yso/p18921)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi tai käytettäväksi termiksi geobiologia

**Perustelut ehdotukselle**

Englanninkielinen vastine tälle on geobiology (ks. myös MOT). Maabiologia-termiä käytetään varsin vähän, Googlella tulee tuskin mitään. Geobiologiaa näkyy enemmän. Wikipediassa termi on Geobiologia.
https://fi.wikipedia.org/wiki/Geobiologia
Geobiologia löytyy myös UDK:sta, toisin kuin maabiologia. https://finto.fi/udcs/fi/page/033104

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
_Maaperätiede_ on otettu sanastoon vasta 2016, joten olisikohan tämä _maabiologia_ ollut enemmän siinä käytössä...

**Comment by mariaforsen** [comment]
Markbiologi= "den del av markläran som behandlar organismerna i marken och de biologiska processer genom vilka näringsämnen omsätts." /Nationalencyklopedin 
Eli ei taida olla sama asia kuin geobiologia. 
https://www.sanakirja.fi/custom/en-sv-fi/soil%20biology

**Comment by mirmaid** [comment]
Maaperäbiologia voisi olla ohjaustermi (on mm. YKL hakemistosana)...ellei jopa päätermi. 

https://en.wikipedia.org/wiki/Soil_biology

**Comment by YSO-kokous** [comment]
Vaihdetaan päätermiksi maaperäbiologia.
