### ISSUE TITLE
ravintolavaunut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12380]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ravintolavaunut

**Ehdotettu termi ruotsiksi**

restaurangvagnar

**Ehdotettu termi englanniksi**

restaurant cars

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [junanvaunut](http://www.yso.fi/onto/yso/p21347)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 dining cars

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LIIKO](http://www.yso.fi/onto/mero/m11646), [Wikipedia](https://fi.wikipedia.org/wiki/Ravintolavaunu), [LCSH](http://id.loc.gov/authorities/subjects/sh2006006167)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Hanuristi ja vaunuemännät 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [ravintolavaunut](http://finto.fi/yse/fi/page/Y512380)

**Comment by mariaforsen** [comment]
Sv. restaurangvagnar HT bistrovagnar
