### ISSUE TITLE
turvallisuuskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12387]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[turvallisuuskasvatus](http://www.yso.fi/onto/yso/p4903)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT turvataitokasvatus

**Perustelut ehdotukselle**

KAUNO-ehdotus

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://thl.fi/aiheet/vakivalta/vakivallan-ehkaisy/turvataitokasvatus

Käytössä tyypillisesti kun puhutaan väkivallan, häirinnän, kiusaamisen jne. ehkäisystä, mutta jos tätä ei oteta erikseen, ohjaustermi olisi varmaan paikallaan.

**Comment by ilona-x** [comment]
linkkaan tähän ehdotuksen: turvataidot #3804

**Comment by mariaforsen** [comment]
https://thl.fi/sv/teman/vald/forebyggande-av-vald/integritetskunskaper
