### ISSUE TITLE
taskukirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12392]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taskukirjat](http://www.yso.fi/onto/yso/p13669)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kuuluuko termi SLM-sanastoon?

**Perustelut ehdotukselle**

Onko SLM/655-kenttä oikea paikka tälle tiedolle? Nyt ei ole ainakaan käytetty johdonmukaisesti kaikista "pienemmistä pehmeäkantisista kirjoista".

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Kuuluu! On manifestaation ominaisuutta kuvaava (samalla tavoin kuin _isotekstiset kirjat_, jolla ei myöskään kuvailla teosta eikä ekspressiota).

**Comment by AuHo22** [comment]
Pokkareitten yhteydessä kustantajat voivat joskus käyttää painostermiä 1. taskukirjapainos - eli mielestäni tämä ei siis eroa pokkareista millään tavoin, on mielestäni enemmänkin painostieto kuin genretermi? Ja käytettäisiinkö tätä sitten johdonmukaisesti kaikista kustantajien 18 cm:n kokoisista pehmeäkantisista kirjoista, tämä ei minusta vaikuta järkevältä. Termi ei mielestäni oikein enää ole nykypäivää, pokkarit on.

**Comment by jtuohini** [comment]
Ainakin Kielitoimiston sanakirjan mukaan taskukirja on hyvinkin nykypäivää, kun pokkari määritellään taskukirjaksi (https://www.kielitoimistonsanakirja.fi/pokkari) ja itse taskukirjan yhteydessä on selitys ja pokkari merkittynä puhekieliseksi (https://www.kielitoimistonsanakirja.fi/taskukirja). Onko näille sitten tarvetta kuvailussa, on oma kysymyksensä. Mutta ainakaan tieto ei kuulu 650-kenttään, vaan 655-kenttään (viitaten alkuperäiseen ehdotukseen).

**Comment by AuHo22** [comment]
Taisi olla mustavalkoisten elokuvien yhteydessä kun keskusteltiin siitä, voidaanko asioita kuvata muitten kenttien avulla, ja silloin taidettiin keskustella siitä, että mustavalkoisuus näkyy sekä 300-kentässä sekä kiinteissä kentissä sille on oma koodinsa. Samalla tavalla koko (muissakin tapauksissa kuin pokkareissa) laitetaan ulkoasukenttään, ja usein ne ovat uusintapainoksia kovakantisista, jolloin KP:ssa merkitään tieto [Uusi painos] 250-kenttään. Taidettiin sama keskustelu käydä näköispainosten kohdalla, joka oli kuitenkin termi jota puolsin, mutta tässä alkaa sitten varsinkin yleisille kirjastoille kuvailevana olla jo rajausongelmia - mikä sitten on pokkari ja mikä ei? Ovatko ne aina pienempitekstisiä vai eivät ja koskevatko ne yleensä vain aikuisten kirjallisuutta, myös wikipedia  kiinnittää huomiota rajausongelmiin https://fi.wikipedia.org/wiki/Taskukirja
Meiltä tulleita kommentteja: 
-_Muuten en näe tarvetta. ei ole olemassa mitään tiettyä taskukirjatyyppiä. Ehkä aiemmin tälle olisi_ _ollut enemmän käyttöä, kun matkaoppaita ja sanakirjoja tehtiin pocketteina. Nyt nämä ovat verkossa yms._
-_Eipä se taida enää koskea kuin Aku Ankan taskukirjoja? Kun tuo määritelmä on epämääräinen nykyään._
-_Itse en ole koskaan käyttänyt._

**Comment by AuHo22** [comment]
Esim. Helmet -> nidetiedoissa Pokkarihylly (jos ei Jännitys tms.) eli kokoelman rakentamiseen liittyvästi. Melindassa on voitu kuitenkin käyttää/lisätä

**Comment by mirmaid** [comment]
Määritelmä: Tarkoittaa 10-18 cm korkeita pehmeäkantisia kirjoja.

Otetaan myös pienoiskirjat: Enintään 10 cm korkeita kirjoja.

**Comment by mariaforsen** [comment]
Sv. miniatyrböcker

**Comment by mirmaid** [comment]
Määritelmät myös YSOon?

**Comment by YSO-kokous** [comment]
Lisätään määritelmät.
