### ISSUE TITLE
ensitieto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12398]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ensitieto](http://www.yso.fi/onto/yso/p17337)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne tai ainakin huomautus?

**Perustelut ehdotukselle**

Jos tarkoitus on viitata erikoismerkitykseen "ensi kertaa vammaiselle t. sairastuneelle taikka hänen läheisilleen annettava tieto vammasta t. sairaudesta ja sen hoitamisesta" Ks. https://www.kielitoimistonsanakirja.fi/#/ensitieto?searchMode=all
Vrt. https://www.sanakirja.fi/custom/en-sv-fi/ensitieto
Tarkistetaan myös muunkieliset termit.

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Käytetty vain tässä merkityksessä Melindassa. Useimmissa lähteissä määritellään tiedoksi, joka annetaan perheelle lapsen tai sikiön vammaisuudesta/sairaudesta, mutta Kielitoimiston sanakirjassa, Melindassa ja osassa muista lähteistä laajemmin myös aikuisen sairastuessa.

**Comment by mariaforsen** [comment]
Ei ole varmaan mitään syytä rajata vain lapsiin, se vaatisi ainakin ruotsiksi sulkutarkenteen siinä tapauksessa. 
https://www.muistiliitto.fi/fi/tuki-ja-palvelut/hoito-ja-kuntoutus/ensitieto
https://kilpirauhasliitto.fi/kilpirauhassairaudet/ensitieto/
https://www.suomenkipu.fi/tietoa/oppaat/kroonisen-kivun-ensitieto-opas/

**Comment by mirmaid** [comment]
^ Tuo määrittely tosiaan vaihtelee lähteestä riippuen, mainitsin rajauksen lapsiin, koska se tuli vastaan selkeästi eniten.

**Comment by YSO-kokous** [comment]
Lisätään tarkenne (lääketiede).

**Comment by mariaforsen** [comment]
Sv. första vetskap > första information (vid diagnos)
obs. betydelsen "ensi kertaa vammaiselle t. sairastuneelle taikka hänen läheisilleen annettava tieto vammasta t. sairaudesta ja sen hoitamisesta"

https://svenska.se/tre/?sok=vetskap&pz=1
https://barnstrategi.fi/2023/10/en-ny-omfattande-konsensusrekommendation-om-att-ge-forsta-information/
https://reumaliitto.fi/sv/till-insjuknade-och-narstaende/
https://www.muistiliitto.fi/sv/stod-och-tjanster/vard-och-rehabilitering/information-och-stod
https://stm.fi/sv/-/en-verksamhetsmodell-for-hur-den-forsta-informationen-ska-ges-kommer-att-utarbetas-i-den-nationella-barnstrategin
https://www.allergia.fi/arkisto/pa-svenska/broschyrer-och-videor/astma-hos-barn-och-unga/socialskydd-forsta-information-och-anpassningstraning/
