### ISSUE TITLE
fonologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12397]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[fonologia](http://www.yso.fi/onto/yso/p6016)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään äänneoppiin

**Perustelut ehdotukselle**

Tarvitaanko käsitettä erikseen? Äänneoppi ja fonologia ovat molemmat englanniksi phonology. Wikipediassa fonologia ja äänneoppi esitetään synonyymina. https://fi.wikipedia.org/wiki/Fonologia
Ks. myös: https://tieteentermipankki.fi/wiki/Nimitys:%C3%A4%C3%A4nneoppi

Huom! Fonologialla on alakäsitteenä fonotaksi, joka pitää siirtää hierarkiassa mikäli ehdotettu yhdistely tehdään.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Yhdistäminen olisi hyvä myös ruotsiksi: ljudlära ANV fonologi, fonetik

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**äänneoppi** 
kiel. äänteitä käsittelevä kieliopin osa. 
https://www.kielitoimistonsanakirja.fi/#/%C3%A4%C3%A4nneoppi?searchMode=all

**fonologia**
kiel. äännejärjestelmien tutkimus, funktionaalinen äänneoppi. 
https://www.kielitoimistonsanakirja.fi/#/fonologia?searchMode=all

**Comment by ilona-x** [comment]
Melinda:
fonologia x 1813
äänneoppi x 1988
fonologia & äänneoppi x 196

--

YSA/YSO:
fonologia  - Luotu 1.2.1987,
äänneoppi -  Luotu 1.11.1989

**Comment by YSO-kokous** [comment]
Fonologia KT äänneoppi.
