### ISSUE TITLE
linnustonsuojelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12393]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

linnustonsuojelu

**Ehdotettu termi ruotsiksi**

fågelskydd

**Ehdotettu termi englanniksi**

bird conservation

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. Melindassa käytetty ainakin linnustonsuojelu, lintujensuojelu ja lintujen suojelu

**Ehdotettu yläkäsite YSOssa (LT)**

 [eläimistön suojelu](http://www.yso.fi/onto/yso/p1110)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529), [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

 lintujensuojelu, lintujen suojelu

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Lintujen_suojelu), [LCSH](http://id.loc.gov/authorities/subjects/sh85014335)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Aspskär :100 vuotta linnustonsuojelua

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [linnustonsuojelu](http://finto.fi/yse/fi/page/Y512393)

**Comment by ilona-x** [comment]
Melinda:
linnustonsuojelu x 3
lintujensuojelu x 16
lintujen suojelu x 9
linnuston suojelu x 2

eläimistön suojelu & linnut x 389
eläimistön suojelu & linnusto x 68
