### ISSUE TITLE
hypokloorihappo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12391]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hypokloorihappo

**Ehdotettu termi ruotsiksi**

hypoklorsyra

**Ehdotettu termi englanniksi**

hypochlorous acid 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

 hypokloorihapoke

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D006997), [Wikipedia](https://fi.wikipedia.org/wiki/Hypokloorihapoke)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Catalyzed and non-catalyzed hypochlorous acid bleaching of kraft pulps https://urn.fi/URN:ISBN:978-952-64-1277-1

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [hypokloorihappo](http://finto.fi/yse/fi/page/Y512391)

**Comment by mariaforsen** [comment]
Sv. hypoklorsyra HT hypokloritsyra
https://mesh.kib.ki.se/term/D006997/hypochlorous-acid
https://www.sanakirja.fi/custom/en-sv-fi/hypokloorihappo
