### ISSUE TITLE
kovetettu nahka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12390]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kovetettu nahka

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

hardened leather, boiled leather

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Boiled leather, often referred to by its French translation, cuir bouilli (French: [kɥiʁ buji]), was a historical material common in the Middle Ages and Early Modern Period and used for various purposes. It was leather that had been treated so that it became tough and rigid, as well as able to hold moulded decoration
https://en.wikipedia.org/wiki/Boiled_leather

Ehkä myös/tai nahan kovetus

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Hardened leather and related materials - An armourer's guide ISBN 978-952-94-7840-8

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [kovetettu nahka](http://finto.fi/yse/fi/page/Y512390)

**Comment by mirmaid** [comment]
Melindassa kerran _kovettaminen_ ja 2 kertaa _kovettuminen_.

**Comment by mariaforsen** [comment]
Sv. härdat läder
"Härdat läder (alt. läderpansar) är en mycket ovanlig typ av pansar som utgörs av läder som härdats för att bli hårt. Läder kan härdas genom kokning, torkning och impregnering etc" /WP
