### ISSUE TITLE
jälkikäyttö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#124]
#### Ehdotettu termi suomeksi

jälkikäyttö
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

julkaisu: Perälä, M., Esiselvitys turvetuotannon jälkikäyttömuodoista ja niiden vesistönkuormituksista

**Luontipäivämäärä:** 02.07.1998

**Muokkauspäivämäärä:** 9.7.2001, 9.5.2006, 19.2.2004, 4.10.2007, 16.12.2008, 22.03.2012

**Voyager-id:** 113994

**Termiehdotus Fintossa:** [jälkikäyttö](http://finto.fi/yse/fi/page/Y313994)

**Comment by henriyli** [comment]
Otettu YSAan 24.4.2012: http://www.yso.fi/onto/ysa/Y185610
