### ISSUE TITLE
kaupallinen joukkoviestintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12407]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kaupallinen joukkoviestintä](http://www.yso.fi/onto/yso/p8920)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uudeksi päätermiksi kaupallinen media ja tämä kaupallinen joukkoviestintä sen ohjaustermiksi.

**Perustelut ehdotukselle**

Kaupallinen media on  nykyään paljon käytetympi kuin kaupallinen joukkoviestintä. Ja koska broadcasting (televisio ja radio) on nykyään hyvin yhteensulautunutta ja ennen kaikkea verkossa, kaupallinen media on myös hyvä yhdistävä yläkäsite näille molemmille. En siis kuitenkaan ehdota kaupallisen radion ja kaupallisen television poistamista sanastosta, niille on edelleen käyttöä.

**Ehdottajan organisaatio**

Yle Arkisto

**Comment by mariaforsen** [comment]
Sv. kommersiell masskommunikation > kommersiella medier HT kommersiell media
Jfr UB https://finto.fi/yso/sv/page/p2445
