### ISSUE TITLE
vetytalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12409]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vetytalous

**Ehdotettu termi ruotsiksi**

väteekonomi

**Ehdotettu termi englanniksi**

hydrogen economy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vetytaloudella viitataan energian siirtämiseen ja varastointiin molekylaarista vetyä käyttäen.
https://fi.wikipedia.org/wiki/Vetytalous

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://pirkanmaa.mediafiles.fi/catalog/Pirkanmaa/r/2050/viewmode=previewview/qsr=Pirkanmaan%20vetytalouden%20tilannekuva

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [vetytalous](http://finto.fi/yse/fi/page/Y512409)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. väteekonomi HT vätebaserad ekonomi
