### ISSUE TITLE
hindustanimusiikki [YSO + SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12400]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hindustanimusiikki [YSO + SLM]

**Ehdotettu termi ruotsiksi**

hindustanimusik

**Ehdotettu termi englanniksi**

Hindustani music

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvetta kuvailussa. Karnaattinen musiikki on jo aiemmin otettu sanastoihin, mutta jostain syystä tämä jäänyt tuolloin väliin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [taidemusiikki](http://www.yso.fi/onto/yso/p18434)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 Hindustani classical music

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [http://id.loc.gov/authorities/subjects/sh85088852](http://Hindustani music)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/006532766, https://melinda.kansalliskirjasto.fi/byid/006532688 (kuvailtu väärin, kun ei koske hindulaista musiikkia), https://melinda.kansalliskirjasto.fi/byid/005980524, https://melinda.kansalliskirjasto.fi/byid/002325749 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [hindustanimusiikki [YSO + SLM]](http://finto.fi/yse/fi/page/Y512400)

**Comment by mariaforsen** [comment]
onko sama: https://en.wikipedia.org/wiki/Hindustani_classical_music ?

https://sv.wikipedia.org/wiki/Hindustani_(olika_betydelser)

**Comment by jtuohini** [comment]
On sama!

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
KT hindustaanimusiikki, hindustanilainen musiikki, Pohjois-Intian taidemusiikki

**Comment by mirmaid** [comment]
LCGFT http://id.loc.gov/authorities/genreForms/gf2014026859

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. hindustansk musik HT hindustanimusik, nordindisk klassisk musik 
https://sv.wikipedia.org/wiki/Klassisk_indisk_musik
https://www.diva-portal.org/smash/get/diva2:1446266/FULLTEXT01.pdf
https://www.indien.nu/allt_om_indien/Film_Musik/indisk-musik

**Comment by YSO-kokous** [comment]
Hyväksytään käsite myös YSOon.
