### ISSUE TITLE
sukupuolielinten silpominen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12405]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuolielinten silpominen](http://www.yso.fi/onto/yso/p38703)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

birračuohppan (nissonat)

**Perustelut ehdotukselle**

p38830:n mukaan ympärileikkaus (miehet) on pohjoissaameksi birračuohppan (albmát), niin ohjaustermiksi voisi sitten tänne laittaa birračuohppan (nissonat).

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Hyväksytään ehdotus
