### ISSUE TITLE
proskriptio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12404]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

proskriptio

**Ehdotettu termi ruotsiksi**

proskription

**Ehdotettu termi englanniksi**

proscription

**Tarkoitusta täsmentävä selite**

Lainsuojattomaksi julistaminen antiikin Roomassa.
”Valtion vihollisen julkinen nimeäminen ja virallinen tuomitseminen. Se tarkoittaa käytännössä tuomitsemista kuolemaan tai maanpakoon. Proskriptioita käytettiin yleisesti Rooman valtakunnassa etenkin tasavallan aikana poliittisten vastustajien eliminointiin.” (Wikipedia)

**Perustelut ehdotukselle**

tarvitaan antiikintutkimuksen aineiston kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [tuomiot](http://www.yso.fi/onto/yso/p3192)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Proskriptio)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Les proscriptions de la Rome républicaine / Francois Hinard. ISBN 2-7283-0094-1 
https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9934562136906253

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [proskriptio](http://finto.fi/yse/fi/page/Y512404)

**Comment by jtuohini** [comment]
LCSH-siltaus: [**Proscription**](http://id.loc.gov/authorities/subjects/sh85107564).

**Comment by mirmaid** [comment]
Ei Melindassa.
