### ISSUE TITLE
ympärileikkaus (miehet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12406]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ympärileikkaus (miehet)](http://www.yso.fi/onto/yso/p38830)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pohjoissaamenkielinen ohjaustermi: birračuohpahus (albmát)

**Perustelut ehdotukselle**

p38703:n mukaan ympärileikkaus (naiset) on pohjoissaameksi birračuohpahus (nissonat), niin ohjaustermiksi voisi sitten vastaavasti laittaa tänne birračuohpahus (albmát). 

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Hyväksytään ehdotus
