### ISSUE TITLE
vaalivaikuttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12418]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vaalivaikuttaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

election interference

**Tarkoitusta täsmentävä selite**

Wikipedia (= laajempi kuin LCSH, jossa tuo "foreign"
Election interference generally refers to efforts to change the outcome of a election. Kinds of election interference may include:

Electoral fraud, illegal interference with the process of an election
Vote buying, when a political party or candidate distributes money to a voter with the expectation that they will vote for them
Voter impersonation, when an eligible voter votes more than once or a non-eligible voter votes under the name of an eligible one
Foreign electoral intervention, attempts by governments to influence elections in another country

**Perustelut ehdotukselle**

Kuvailutarve, aiheen merkittävyys ja ajankohtaisuus

**Ehdotettu yläkäsite YSOssa (LT)**

 [informaatiovaikuttaminen](http://www.yso.fi/onto/yso/p39619)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541), [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575), [80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh2020000621.html), [Wikipedia](https://en.wikipedia.org/wiki/Election_interference)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.hybridcoe.fi/publications/hybrid-coe-research-report-10-preventing-election-interference-selected-best-practices-and-recommendations/

**Ehdottajan organisaatio**

KK / Anna Tuominen
**Termiehdotus Fintossa:** [vaalivaikuttaminen](http://finto.fi/yse/fi/page/Y512418)

**Comment by mirmaid** [comment]
Myös ehdotus https://github.com/Finto-ehdotus/YSE/issues/2266

**Comment by mariaforsen** [comment]
Sv. valpåverkan HT valstörning
https://oikeusministerio.fi/sv/-/koulutushanke-vaalivaikuttamisesta-puolueille-ja-viranomaisille
https://vaalit.fi/sv/valpaverkan
https://vnk.fi/sv/-//1410853/ensi-viikolla-keskustellaan-vaalivaikuttamisesta-seuraa-seminaaria-verkoss
https://www.kyberturvallisuuskeskus.fi/sites/default/files/media/file/Traficom_INFORMATIONSS%C3%84KERHET_2019_uppslag.pdf
https://www.sanakirja.fi/custom/en-sv-fi/vaalih%C3%A4irint%C3%A4
https://svenska.yle.fi/a/7-10029857
https://www.svt.se/nyheter/inrikes/myndigheter-rustar-mot-valpaverkan-infor-hostens-val

**Comment by fantsby-m** [comment]
_Vaalihäirintä_ olisi ehkä sopivampi termi.
https://vaalit.fi/vaalihairinta.

Termiä _vaalivaikuttaminen_ käytetään myös ihan normaalista ja laillisesta vaaleihin liittyvästä poliittisesta työstä, ks. esim.
https://www.epilepsia.fi/epilepsialiitto/vaikuttaminen-ja-yhteistyo/kansallinen-vaikuttaminen/vaalivaikuttaminen/
https://www.kuuloliitto.fi/yhdistysten-vaalivaikuttaminen/
https://tamko.fi/edunvalvonta/edunvalvonta-tamkossa/vaalivaikuttaminen/

**Comment by YSO-kokous** [comment]
Vaalihäirintä KT vaalivaikuttaminen (vaalihäirintä).
