### ISSUE TITLE
Phoenix

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12412]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Phoenix](http://www.yso.fi/onto/yso/p20208)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sulkutarkenne tai poisto

**Perustelut ehdotukselle**

Käytetty ilmeisesti kerran oikein ja kaksikymmentäneljä kertaa väärin Melindassa, esim. Phoenixin kaupungista ja avaruusluotaimesta.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Ennemmin poisto tässä tapauksessa.
