### ISSUE TITLE
Längelmäen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12415]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Längelmäen kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/L%C3%A4ngelm%C3%A4en_kirkko)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Längelmäen kirkko 250 : Finn VERNADOC 2021 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Längelmäen kirkko](http://finto.fi/yse/fi/page/Y512415)

**Comment by mariaforsen** [comment]
Sv. Längelmäki kyrka
