### ISSUE TITLE
gospelrock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12410]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[gospelrock](http://www.yso.fi/onto/yso/p19827)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käytettäväksi termiksi tai ohjaustermiksi kristillinen rock

**Perustelut ehdotukselle**

Kristillinen rock tuntuu ainakin googlaamisen perusteella olevan jonkin verran käytössä, ja vähintään yhtä paljon kuin termi gospelrock. Wikipedia-artikkeli on otsikoltaan Kristillinen rock. https://fi.wikipedia.org/wiki/Kristillinen_rock

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by asormune** [comment]
Ohjaustermiksi ainakin, helpommalla päästäisiin, jos päätermiksi jäisi gospelrock.

**Comment by mariaforsen** [comment]
Onko se varmasti aivan samanlaista tyyliltään? https://fi.wikipedia.org/wiki/Gospel 
Gospel on kai yleensä tietyntyylistä, ei tarkoita pelkästään että se on kristillistä, näin ainakin ruotsiksi. 

Gospel: "typ av jazz- eller blues­liknande religiös sång ur­sprungligen fram­förd av afro­amerikaner" /https://svenska.se/tre/?sok=gospel&pz=1

**Comment by MUUSA-kokous** [comment]
Kannatetaan kristillisen rockin lisäämistä gospelrockin ohjaustermiksi.
Sama SLM:ään.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
