### ISSUE TITLE
dokumentointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12417]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[dokumentointi](http://www.yso.fi/onto/yso/p16361)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT kirjaaminen?

**Perustelut ehdotukselle**

Palaute: Toivoisin, että sanasto "vinkkaisi" kirjaaminen termin oheen dokumentoinnin. Niin hoitotyössä kuin lähialoilla puhutaan kirjaamisesta, mutta käytännön tiedonhaussa toimiva termi on myös dokumentointi.

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Tulipa RT-suhdetta tai ei, kannattaisi KT-muodoksi lisätä _dokumentoiminen_ (https://www.kielitoimistonsanakirja.fi/dokumentointi).

**Comment by mariaforsen** [comment]
Millä tavalla kirjaaminen rajautuu? Ruotsinkielinen vastine riippuu käyttökontekstista: https://termipankki.fi/tepa/fi/haku/kirjaaminen
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_788b25f86c23007ae1a31d95d3a7741b&list_id=1&keyword=kirjata&word=kirjata

Vrt. esim. "viranomaisen tai yhteisön käsittelemiin asioihin liittyvän kirjeenvaihdon ja päätösten sekä asioiden käsittelyvaiheiden merkitseminen diaariin"  ->sv. diarieföring 
ja
"sosiaalihuollon asiakastyössä kirjaaminen tarkoittaa sitä, että sosiaalihuollon ammattihenkilö tai muu asiakastyöhön osallistuva henkilö laatii sosiaalihuollon asiakasasiakirjoja. Sosiaalihuollossa käytetään kirjaamisesta myös dokumentointi-termiä" 
->sv. dokumentation/anteckning

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotettu ohjaustermi ja suhde.

**Comment by mariaforsen** [comment]
Sv. dokumentation
https://www.kielitoimistonsanakirja.fi/#/dokumentointi?searchMode=all
https://svenska.se/tre/?sok=dokumentation&pz=1
https://www.rikstermbanken.se/search?q=dokumentation&s=termer
https://www.ne.se/s%C3%B6k/?t=uppslagsverk&q=dokumentation
https://termipankki.fi/tepa/fi/haku/dokumentointi
https://sv.wikipedia.org/wiki/Dokumentation
