### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12413]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Flash](http://www.yso.fi/onto/yso/p20398)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käytettäväksi termiksi tai ohjaustermiksi Adobe Flash

**Perustelut ehdotukselle**

On nykyisin ohjelman virallinen nimi. Ks. https://en.wikipedia.org/wiki/Adobe_Flash

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Adobe_Flash

**Comment by mirmaid** [comment]
Näissä on tainnut olla vähän erilaisia ratkaisuja, vrt. esim. Java EE, ArcInfo. Eli otetaanko (kuten wikipediassa) uusin nimi, ja käytetään sitä hiukan anakronistisesti myös aikaisemmista versioista (jotka saattavat liittyä esim. yrityskauppoihinkin, kuten tässäkin tapauksessa).

**Comment by YSO-kokous** [comment]
Ohjaustermiksi.
