### ISSUE TITLE
Puhtaan maan buddhalaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12414]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Puhtaan maan buddhalaisuus

**Ehdotettu termi ruotsiksi**

Rena land-buddhism

**Ehdotettu termi englanniksi**

Pure Land Buddhism

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Buddhalaisuuden koulukunta, tarpeen sisällönkuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [mahajana](http://www.yso.fi/onto/yso/p39193), [buddhalaisuus](http://www.yso.fi/onto/yso/p8624)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH: Pure Land Buddhism](http://id.loc.gov/authorities/subjects/sh85109172)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pure land, real world : modern Buddhism, Japanese leftists, and the Utopian imagination / Melissa Anne-Marie Curley, ISBN: 9780824892449

**Ehdottajan organisaatio**

Itä-Suomen yliopisto
**Termiehdotus Fintossa:** [Puhtaan maan buddhalaisuus](http://finto.fi/yse/fi/page/Y512414)

**Comment by ilona-x** [comment]
Wikipedia: https://fi.wikipedia.org/wiki/Puhtaan_maan_buddhalaisuus

**Comment by mariaforsen** [comment]
Sv. rena land-buddhism
https://sv.wikipedia.org/wiki/Rena_land-buddhism
https://sv.wikipedia.org/wiki/Mahayana
