### ISSUE TITLE
lääkintälaitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12428]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lääkintälaitteet](http://www.yso.fi/onto/yso/p18016)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lääkinnälliset laitteet

**Perustelut ehdotukselle**

----

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Muutetaanko päätermi? Ohjaustermiksi toki ainakin.

**Comment by mariaforsen** [comment]
Sv. medicinteknisk utrustning > medicintekniska produkter

https://termipankki.fi/tepa/fi/haku/l%C3%A4%C3%A4kinn%C3%A4llinen%20laite
https://eur-lex.europa.eu/SV/legal-content/summary/ensuring-the-safety-and-performance-of-medical-devices.html
https://fimea.fi/sv/medicintekniska_produkter/vad-ar-medicintekniska-produkter-
https://sfs.fi/standardeista/tutustu-standardeihin/suositut-standardit/laakinnalliset-laitteet/
https://fimea.fi/laakinnalliset_laitteet/mita-ovat-laakinnalliset-laitteet-
https://finlex.fi/fi/laki/alkup/2021/20210719
https://finlex.fi/sv/laki/alkup/2021/20210719

Kannatan muutosta.

**Comment by YSO-kokous** [comment]
Hyväksytään muutos.
