### ISSUE TITLE
digitoitu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12435]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

digitoitu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Objekti, joka on digitoitu

**Perustelut ehdotukselle**

Tarvittaisiin alkujaan digitaalinen -käsitteen pariksi termi. Käyttäisimme sitä luetteloidessa niitä objekteja, joista meillä on vain digitoitu objekti kokoelmissa. Esim. lahjoittaja on lainannut alkuperäiset analogikuvat, jotka olemme hänelle palauttaneet ja meille kokoelmiin jää digitoidut tiedostot. Kokossa on termi digitointi, mutta se käsittääkseni tarkoittaa toimintaa, ei lopputulosta. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/yso/p26572), [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. https://hkm.finna.fi/Record/hkm.38da9689-91d9-45c8-b595-63c5892da9d0

**Ehdottajan organisaatio**

Helsingin kaupunginmuseo
**Termiehdotus Fintossa:** [digitoitu](http://finto.fi/yse/fi/page/Y512435)

**Comment by mirmaid** [comment]
Tämä taitaa olla ehdotus MAO-ontologiaan, josta myös tuo _alkujaan digitaalinen_ löytyy.

Ehdotus välitetty MAOn vastuuhenkilölle.
