### ISSUE TITLE
monogrammit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12433]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[monogrammit](http://www.yso.fi/onto/yso/p20840)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pohjoissaame: monográmmat

**Perustelut ehdotukselle**

Monográmma on myös käytössä, esim. Norjan kuninkaallisten sivuilla ja Muittut muitalusat -sivuilla (https://muittut.com/logo/?lang=sme). Korpista löytyy vain á:lla.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Hyväksytään ehdotus _monográmmat_
