### ISSUE TITLE
vahvistusoppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12439]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vahvistusoppiminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

reinforcement learning

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [koneoppiminen](http://www.yso.fi/onto/yso/p21846)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh92000704), [Wikidata](http://www.wikidata.org/entity/Q830687)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. Safe and efficient transfer of robot policies from simulation to the real world 
https://urn.fi/URN:ISBN:978-952-64-1233-7

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [vahvistusoppiminen](http://finto.fi/yse/fi/page/Y512439)

**Comment by mirmaid** [comment]
10 viitettä Melindassa. 

https://tieteentermipankki.fi/wiki/Nimitys:vahvistusoppiminen

**Comment by mariaforsen** [comment]
Sv. förstärkningsinlärning
https://www.psykologiguiden.se/psykologilexikon/?Lookup=f%C3%B6rst%C3%A4rkningsinl%C3%A4rning
https://www.su.se/sok-kurser-och-program/mt7051-1.667578
https://learn.microsoft.com/sv-se/azure/ai-services/personalizer/concepts-reinforcement-learning
