### ISSUE TITLE
landsättningsbåtar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12438]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[landsättningsbåtar](http://www.yso.fi/onto/yso/p7081)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätäänkö tarkenne?

**Perustelut ehdotukselle**

Kaksimerkityksinen termi (käännös sopii vain 1. merkitykselle): https://www.kielitoimistonsanakirja.fi/#/uisko?searchMode=all

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Uisko
https://fi.wikipedia.org/wiki/Uisko-luokan_joukkojenkuljetusvene

landsättningsbåt = maihinnousualus

**Comment by mariaforsen** [comment]
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_2d299d7f9760eb9d8c18f10eda94a73d&list_id=1&keyword=uisko&word=uisko
https://www.sanakirja.fi/custom/en-sv-fi/uisko

**Comment by mirmaid** [comment]
Ehkä näillä on sama tausta, matalalla uiva vene, joka soveltuu maihinnousuun tai (aiemmin) kannasten ylitykseen. Uisko yleisnimenä maihinnousuveneelle tuntuu hyvin vieraalta ja on käytetty Melindassa vain kolme kertaa yhteensä.

**Comment by YSO-kokous** [comment]
Maihinnousuveneet tai -alukset (tutkitaan kumpi). Poistetaan uiskot.

**Comment by ilona-x** [comment]
SOTO: maihinnousualukset KT maihinnousuveneet http://www.yso.fi/onto/soto/p332

**Comment by mariaforsen** [comment]
Sv. landstigningsfartyg /svensk-finsk militärordbok HT landsättningsfartyg, landsättningsbåtar (pienemmät) 

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_8a2d659418b1ff8b45e17c036a6a1636&list_id=1&keyword=maihinnousualus&word=maihinnousualus

https://svenska.se/tre/?sok=landstigningsfartyg&pz=1

https://sv.wikipedia.org/wiki/Landstigningsfartyg

**Comment by AnuAlatera** [comment]
MPKK:n kirjaston näkemys on, että termi maihinnousualukset on asiallinen.
