### ISSUE TITLE
huan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12434]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[huan kieli](http://www.yso.fi/onto/yso/p2603)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Termi kuuluisi oikeastaan olla muotoa "huan murre" ja lisäksi olisi hyvä olla sulkutarkenne (Papua-Uusi-Guinea). Saman nimisiä kieliä on myös Afrikassa. Ks. https://en.wikipedia.org/wiki/Hua_language
Oikeastaan hua on siis murre, ei kieli, ja itse pääkieli on nimeltään yagaria. Termiä/käsitettä ja sen rajausta voisi ehkä revisioida, jos nähdään tarpeelliseksi. Tätähän ei tosin kuvailussa kuitenkaan ole hirveästi käytetty.

**Perustelut ehdotukselle**

LCSH nimeää tämän murteeksi: https://id.loc.gov/authorities/subjects/sh85062719.html
Ks. myös:
https://finto.fi/lexvo/fi/page/ygr?clang=en
https://en.wikipedia.org/wiki/Yagaria_language

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Lisäsin jo englannille sulkutarkenteen (Papua New Guinea). Lisämuutoksia sitten sen mukaan, mitä käsitteestä päätetään.

**Comment by mariaforsen** [comment]
Eli Lexvossa ainoastaan Yagaria. Hualle ei taida oikeasti olla ruotsinkielistä nimitystä.

**Comment by mirmaid** [comment]
Alun perin kirjasta Itkonen, Esa: Ten non-European languages, jossa käsitellään useita kieliä perustuen alkuperäistutkimuksiin; Huan osalta Haiman, John: Hua: a Papuan language of the Eastern Highlands of New Guinea.
