### ISSUE TITLE
yhteistyörobotit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12436]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yhteistyörobotit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

cobot, collaborative robot

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Cobot
A cobot, or collaborative robot, is a robot intended for direct human-robot interaction within a shared space, or where humans and robots are in close proximity. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [robotit](http://www.yso.fi/onto/yso/p2619)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

 cobotit, kobotit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:NBN:fi-fe20231221156621
Yhteistyörobotit - ruokaturvallisuus ja tuottavuus

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [yhteistyörobotit](http://finto.fi/yse/fi/page/Y512436)

**Comment by mirmaid** [comment]
Cobot on ihmisen kanssa yhteistyössä toimiva robotti, joka ei tarvitse erityisiä turvalaitteita ympärilleen. Toisin, kuin tavallinen robotti, se voi olla myös kontaktissa ihmisen kanssa. https://www.treston.fi/blog/mika-cobot-ja-mita-etuja-silla-teollisessa-tyossa

**Comment by ilona-x** [comment]
IATE2
fi        yhteistyörobotti (★★★☆)
sv       samarbetande robot (★★★☆);
kollaborativ robot (★★★☆);
samarbetsrobot (★★★☆);
cobot (★★★☆)
en      collaborative robot (★★★☆);
cobot (★★★☆)

	  
Lähde: IATE 01.08.2023, Euroopan unioni (293792) https://termipankki.fi/tepa/fi/haku/yhteisty%C3%B6robotti

**Comment by mariaforsen** [comment]
Sv. kollaborativa robotar HT cobotar, samarbetsrobotar, samarbetande robotar, samverkande robotar 
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/fj%C3%A4rde-industriella-revolutione
https://it-kanalen.se/universal-robots-levererar-framtidens-cobots/
https://termipankki.fi/tepa/fi/haku/cobot
https://www.sanakirja.fi/custom/en-sv-fi/cobot
https://it-ord.idg.se/ord/cobot/
