### ISSUE TITLE
dependence grammar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12431]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[dependence grammar](http://www.yso.fi/onto/yso/p25713)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Myös dependency grammar

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Dependency_grammar

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Muutettu
