### ISSUE TITLE
Nivalan Pyhän sydämen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12443]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Nivalan Pyhän sydämen kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

----

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pyhän sydämen kirkko

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Nivalan Pyhän sydämen kirkko](http://finto.fi/yse/fi/page/Y512443)

**Comment by mariaforsen** [comment]
Varmaan OT Nivalan kirkko https://fi.wikipedia.org/wiki/Nivalan_kirkko
Sv. Nivala kyrka
