### ISSUE TITLE
harjoitusalueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12448]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

harjoitusalueet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sanastosta puuttuu asiasana, jolla kuvailla esimerkiksi puolustusvoimien tai pelastustoimen harjoitusalueet.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Puolustusvoimien, pelastustoimen, työturvallisuuden yms. harjoitusalueita käsittelevä aineisto.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [harjoitusalueet](http://finto.fi/yse/fi/page/Y512448)

**Comment by jtuohini** [comment]
LT-suhteeksi varmaan [**erityisalueet**](http://www.yso.fi/onto/yso/p13700)? Entä RT [**ampuma-alueet**](http://www.yso.fi/onto/yso/p23616) ja [**sotilasalueet**](http://www.yso.fi/onto/yso/p7336)?

**Comment by mirmaid** [comment]
Käytetty Melindassa runsaasti vapaana avainsanana juuri sotilaallisessa kontekstissa, mutta tulkittavissa myös laajemmin (esim. urheilu).

**Comment by mariaforsen** [comment]
Sv. övningsområden
https://termipankki.fi/tepa/fi/haku/harjoitusalue
https://www.rikstermbanken.se/search?q=%C3%B6vningsomr%C3%A5de&s=termer

Olisi hyvä rajata pois "mikä tahansa urheiluun liittyvä", silloin termi olisi ruotsiksi träningsområde.

**Comment by YSO-kokous** [comment]
Harjoitusalueet (viranomaistoiminta), KT harjoitusalueet (työturvallisuus), harjoitusalueet (pelastustoimi), harjoitusalueet (maanpuolustus).

**Comment by ilona-x** [comment]
vanha ehdotus: paloharjoitusalueet https://github.com/Finto-ehdotus/YSE/issues/4213

**Comment by mariaforsen** [comment]
Sv. övningsområden (myndighetsverksamhet)
https://termipankki.fi/tepa/fi/haku/harjoitusalue
https://www.rikstermbanken.se/search?q=%C3%B6vningsomr%C3%A5de&s=termer
