### ISSUE TITLE
ekstaasi (huumeet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12449]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ekstaasi (huumeet)](http://www.yso.fi/onto/yso/p5464)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi MDMA. Ehkä myös pitempi muoto metyleenidioksimetamfetamiini, tai jos tarkkoja ollaan, 3,4-metyleenidioksimetamfetamiini.

**Perustelut ehdotukselle**

Ks. https://fi.wikipedia.org/wiki/MDMA
https://id.loc.gov/authorities/subjects/sh89002646.html
https://paihdelinkki.fi/tietopankki/pikatieto/mdma-ekstaasi/

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Sv. HT MDMA, 3,4-metylendioximetamfetamin
