### ISSUE TITLE
Öölanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12442]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Öölanti](http://www.yso.fi/onto/yso/p165610)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitääkö jakaa tai tarkentaa?

**Perustelut ehdotukselle**

Miten toimitaan kun kyseessä on sekä saari että maakunta?

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Ei auktorisoida erikseen - sama koskee läänejä ja vastaavia, joiden koko on suunnilleen sama kuin saaren. Linkitetään wikidatassa kaikkiin. Lisätään linjauksiin.
