### ISSUE TITLE
arkkitehtuuripolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12440]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

arkkitehtuuripolitiikka

**Ehdotettu termi ruotsiksi**

arkitekturpolitik

**Ehdotettu termi englanniksi**

architectural policy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. Käytetty Melindassa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Architectural policy in Finland :architecture as civic education /Turit Fröbe

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [arkkitehtuuripolitiikka](http://finto.fi/yse/fi/page/Y512440)

**Comment by mariaforsen** [comment]
Sv. HT arkitekturpolicy
https://data.riksdagen.se/dokument/H3B388
https://www.arkitekt.se/sa-tycker-vi/var-politik/var-arkitekturpolitik/
https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/164412/VN_2022_61.pdf?sequence=1&isAllowed=y
https://www.rikstermbanken.se/search?q=arkitekturpolitik&s=mer
Finlands arkitekturpolitik / redaktionsarbete: Finlands arkitektförbund, SAFA
