### ISSUE TITLE
Kuusiston kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12446]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kuusiston kartano

**Ehdotettu termi ruotsiksi**

Kustö gård

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Kuusiston_kartano
Kuusiston kartano (ruots. Kustö gård) on kartano Kaarinassa, Varsinais-Suomessa. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [kartanot](http://www.yso.fi/onto/yso/p832)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-368-145-3
https://www.senaatti.fi/app/uploads/2024/01/978-952-368-145-3_2024_Arkkitehtitoimisto-Livady_Kuusiston-kartano-Museoksi-muuttaminen_Livady__rhs_s.pdf

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [Kuusiston kartano](http://finto.fi/yse/fi/page/Y512446)

**Comment by mariaforsen** [comment]
Sv. Kustö gård HT Kustö herrgård
