### ISSUE TITLE
Psykologinen turvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12447]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Psykologinen turvallisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Psychological safety

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Psykologinen turvallisuus on yleisesti käytössä oleva termi, jolla tarkoitetaan työyhteisön ilmapiiriä, jossa on turvallista ottaa sosiaalisia riskejä, kuten tuoda esiin huolenaiheita, kysymyksiä ja ideoita ilman nolaamista tai rankaisemista. https://www.ttl.fi/oppimateriaalit/pelotta-toissa-psykologinen-turvallisuus-tyoyhteisossa/mita-psykologinen-turvallisuus

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Opinnäytetyö

**Ehdottajan organisaatio**

Humanistinen ammattikorkeakoulu
**Termiehdotus Fintossa:** [Psykologinen turvallisuus](http://finto.fi/yse/fi/page/Y512447)

**Comment by mirmaid** [comment]
Aikaisempi ehdotus: https://github.com/Finto-ehdotus/YSE/issues/10473

**Comment by mariaforsen** [comment]
Sv. psykologisk trygghet HT psykisk trygghet, psykologisk säkerhet, psykisk säkerhet
https://temahr.se/arbetsmiljo-kultur/psykologisk-trygghet-vad-ar-det-och-vad-sager-forskningen/
https://www.psykologiguiden.se/psykologilexikon/?Lookup=psykologisk+trygghet
https://ttk.fi/sv/2023/09/01/psykologisk-trygghet-pa-arbetsplatsen-arbetarskyddscentralen-ger-ut-en-handbok-om-att-arbeta-tillsammans/
[Psykologisk trygghet : att välkomna den som utmanar / Louise Bringselius.](https://melinda.kansalliskirjasto.fi/F/D611VGFYFNSCR52VEX62TF89TUBRDFC2IYLQM1YK7GUKNA9PFN-09390?func=full-set-set&set_number=058987&set_entry=000001&format=999)
https://www.oph.fi/sv/utbildning-och-examina/psykisk-sakerhet

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Huom. myös psyykkinen turvallisuus (KT?)
