### ISSUE TITLE
lentolehtiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12457]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lentolehtiset](http://www.yso.fi/onto/yso/p25907)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään ohjaustermiksi flyerit.

**Perustelut ehdotukselle**

Yleinen termi nykyisin näille. Ks. esim.
https://www.vistaprint.fi/markkinointimateriaalit/flyerit
https://www.painotalo.fi/fi/tuotteet/flyerit
https://www.grano.fi/tuote/flyerit

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Myös muodoissa flaijeri, flaieri.
