### ISSUE TITLE
sepelvaltimotauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12459]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sepelvaltimotauti](http://www.yso.fi/onto/yso/p16060)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään englanniksi ohjaustermiksi (tai vaihdetaan päätermiksi) coronary artery disease

**Perustelut ehdotukselle**

FinMeSH:
sepelvaltimotauti = coronary artery disease
http://www.yso.fi/onto/mesh/D003324

**Ehdottajan organisaatio**

kk/il

**Comment by tpalonen** [comment]
Muutettu ehdotus päätermiksi
