### ISSUE TITLE
suojaosuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12456]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suojaosuus

**Ehdotettu termi ruotsiksi**

skyddat belopp

**Ehdotettu termi englanniksi**

protected portion

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSOsta ei löydy käsitettä, jolla asian voisi ilmaista toisin.
Käsitettä tarvitaan toistuvasti. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [ulosmittaus](http://www.yso.fi/onto/yso/p14771)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esimerkiksi ulosmittaukseen liittyvien valtiopäiväasiakirjojen kuvailussa.

Myös tässä julkaisussa se olisi tarpeen:
https://www.finna.fi/Record/valto.10024_164861?sid=3743196305 

**Ehdottajan organisaatio**

Eduskunnan kanslia
**Termiehdotus Fintossa:** [suojaosuus](http://finto.fi/yse/fi/page/Y512456)

**Comment by ilona-x** [comment]
OIKO:
suojaosuus http://www.yso.fi/onto/oiko/p1747

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Suojaosuus_(ulosotto)

https://tieteentermipankki.fi/wiki/Oikeustiede:suojaosuus_ulosotossa

**Comment by fantsby-m** [comment]
> OIKO: suojaosuus http://www.yso.fi/onto/oiko/p1747

Tuo linkki ei toimi ainakaan minulla, tämä toimii:
https://finto.fi/oiko/fi/page/p1747

**Comment by mirmaid** [comment]
Ilman tarkennetta voi mennä sekaisin työttömyyspäivärahan suojaosan kanssa.

**Comment by mariaforsen** [comment]
https://melinda.kansalliskirjasto.fi/F/CVIR1597I76YANJI1M22L7M353BBLQMQJAQKMLK1H7QNB7P342-01577?func=full-set-set&set_number=040169&set_entry=000001&format=999

**Comment by YSO-kokous** [comment]
Suojaosuus (ulosotto)

**Comment by mariaforsen** [comment]
Sv. skyddat belopp (utsökning)
