### ISSUE TITLE
hoitokodit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12451]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hoitokodit](http://www.yso.fi/onto/yso/p17316)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi hoivakodit?

**Perustelut ehdotukselle**

FinMeSH:
hoivakodit KÄYTÄ hoitokodit http://www.yso.fi/onto/mesh/D009735

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Taitaa olla käytetympikin nykyään.

**Comment by YSO-kokous** [comment]
Hyväksytty ohjaustermiksi.
