### ISSUE TITLE
Tarvasjoki (Lieto)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12454]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Tarvasjoki (Lieto)](http://www.yso.fi/onto/yso/p236172)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

MML-linkki nyt väärässä tietueessa

**Perustelut ehdotukselle**

kyllä näin on

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Eikös wikidata-linkin voi jättää myös entiseen kuntaan, jos ei ole erillisia wikidata-sivuja?

**Comment by mirmaid** [comment]
^ Ok näin (closeMatch). MML-relatedMatch.
