### ISSUE TITLE
aktinobakteerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12455]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aktinobakteerit

**Ehdotettu termi ruotsiksi**

aktinobakterier

**Ehdotettu termi englanniksi**

actinobacteria

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 4

**Ehdotettu yläkäsite YSOssa (LT)**

 [bakteerit](http://www.yso.fi/onto/yso/p1749)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 actinomycetes, aktinomykeetit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Aktinobakteerit), [FinMeSH](http://www.yso.fi/onto/mesh/D039903), [LCSH](http://id.loc.gov/authorities/subjects/sh2007000158)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Metabolic pathway engineering of actinomycetes for novel antibiotics discovery https://urn.fi/URN:ISBN:978-951-29-8756-6

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [aktinobakteerit](http://finto.fi/yse/fi/page/Y512455)

**Comment by mariaforsen** [comment]
Sv. aktinobakterier HT aktinomyceter
https://mesh.kib.ki.se/term/D039903/actinobacteria
