### ISSUE TITLE
rahaliitot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12450]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rahaliitot](http://www.yso.fi/onto/yso/p26734)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi rahaunionit?

**Perustelut ehdotukselle**

ehdotettu aikanaan sanastoon, mutta voisi ehkä ottaa ohjaustermiksi tälle
rahaunionit https://github.com/Finto-ehdotus/YSE/issues/267

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Ja valuuttaunionit?

**Comment by mariaforsen** [comment]
Ruotsiksi valutaunioner vastineena.
