### ISSUE TITLE
etäjohtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12464]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[etäjohtaminen](http://www.yso.fi/onto/yso/p24289)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi e-johtaminen

**Perustelut ehdotukselle**

Riittävän sama asia?
https://erepo.uef.fi/bitstream/handle/123456789/19516/urn_nbn_fi_uef-20180618.pdf?sequence=-1&isAllowed=y
https://www.theseus.fi/bitstream/handle/10024/355081/Siiri%C3%A4inen_Minna.pdf?sequence=2&isAllowed=y

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
"E-ledarskap är ett virtuellt ledarskap som utövas på distans, även kallat distansledarskap"
/https://temahr.se/ledarskap/ledarskap-nya-ron-och-trender-inom-forskningen/

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/E-leadership
