### ISSUE TITLE
korkki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12463]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[korkki](http://www.yso.fi/onto/yso/p3812)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne?

**Perustelut ehdotukselle**

Sanastossa myös korkit. Monikkomuoto on yksiselitteinen, mutta yksikkömuoto ei

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. kork (material)? Sopisi Melindan kanssa, paitsi esim. [Korkki : kielikeskustietojärjestelmän käyttöopas / Timo Sikanen.](javascript:open_window("/F/DLBDXIVPKMCHY46UH5NUTNYB6B5VLI6K5SNYJ4G8P5HYUB6J1I-05745?func=service&doc_number=000684209&line_number=0017&service_type=TAG%22);)

**Comment by YSO-kokous** [comment]
Korkki (materiaalit).
