### ISSUE TITLE
eläintiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12469]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eläintiede](http://www.yso.fi/onto/yso/p12326)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermi (pohjoissaame): zoologiija

**Perustelut ehdotukselle**

zoologiija myös käytössä, esim. https://www.regjeringen.no/se/dokumenter/st.die.-nr.-34-2001-2002/id196279/?ch=6, http://meahcci.info/rapport/gmgc.htm ja http://skuvla.info/skolehist/aarseth2-s.htm

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Lisätään ohjaustermi _zoologiija_
