### ISSUE TITLE
yleisötilaisuudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12466]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yleisötilaisuudet](http://www.yso.fi/onto/yso/p2109)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Miten laajasti halutaan tällä käsitteellä viitata, olisiko julkiset tilaisuudet/tapahtumat ohjaustermi, vai mahdollisesti erillinen termi? 

**Perustelut ehdotukselle**

Eng. nyt public events ja sv. evenemang för allmänheten, eli julkisia tilaisuuksia. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/yleis%C3%B6tilaisuus
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_763401cc6686c1ca019b958b8f38eb44&list_id=1&keyword=yleis%C3%B6tilaisuus&word=yleis%C3%B6tilaisuus
https://www.sanakirja.fi/custom/en-sv-fi/yleis%C3%B6tilaisuus
https://finlex.fi/sv/laki/ajantasa/1999/19990530

**Comment by mirmaid** [comment]
Tässä ongelmana ollut ehkä siis suomenkielisen termin "yleisö" = tilaisuuden osallistujat tulevat katsomaan tai kuuntelemaan jotain mitä esitetään. Konsertti olisi yleisötilaisuus, mutta markkinat ei. (?)

Täällä laajemmin: https://poliisi.fi/yleisotilaisuudet

**Comment by YSO-kokous** [comment]
Ongelmakokous.

**Comment by mariaforsen** [comment]
Sv-termi riippuu tosiaan siitä miten tämä määritellään, eli onko se niin kuin laissa ja esim. poliisin sivulla määritellään: "Tilaisuus tai tapahtuma on yleisötilaisuus silloin, kun se on avoin kenelle tahansa, joko ilmaiseksi tai pääsylipun ostamalla. Tyypillisiä yleisötilaisuuksia ovat erilaiset **messut ja markkinat, urheilukilpailut, näytökset ja yleisölle suunnatut juhlat**. Yleisötilaisuuteen osallistuminen ei siis edellytä erillistä kutsua tai jonkin yhteisön jäsenyyttä." Vai onko kyseessä siitä että joku esittää jotain ja yleisö kuuntelee, katsoo tms.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi _julkiset tilaisuudet_ ja _julkiset tapahtumat_.

**Comment by mariaforsen** [comment]
Sv. evenemang för allmänheten > ev. offentliga tillställningar?

https://termipankki.fi/tepa/fi/haku/yleis%C3%B6tilaisuus
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_763401cc6686c1ca019b958b8f38eb44&list_id=1&keyword=yleis%C3%B6tilaisuus&word=yleis%C3%B6tilaisuus
https://www.sanakirja.fi/custom/en-sv-fi/yleis%C3%B6tilaisuus
https://finlex.fi/sv/laki/ajantasa/1999/19990530
https://valter.sanakirja.fi/all/all/yleis%C3%B6tilaisuus
https://verksamt.se/bransch/hitta-tillstand/tillstand/offentlig-tillstaellning-UKR2008
/uppslagsverk/encyklopedi/lång/offentlig-tillställning
https://www.rikstermbanken.se/search?q=offentlig+tillst%C3%A4llning&s=termer

**Comment by mariaforsen** [comment]
AASI: Ei voida valita oikeaa vastinetta, niin kauan kuin termillä on suomeksi kaksi eri merkitystä, eli juridinen "tilaisuus tai tapahtuma joka on avoin kenelle tahansa, joko ilmaiseksi tai pääsylipun ostamalla" (offentliga tillställningar), tai "tilaisuus jossa on mukana yleisöä" (publika evenemang). Eli olisiko mahdollista lisätä määrittelevä huomautus suomeksi, vai pitääkö tehdä niin että laitetaan ruotsiksi "publika evenemang och offentliga tillställningar" tms?
