### ISSUE TITLE
tekstit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12468]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tekstit](http://www.yso.fi/onto/yso/p16697)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään asiasanalle selitys ja käyttöohje.

**Perustelut ehdotukselle**

Nykyisellään erittäin epäselvä niin sisällön kuin käytön suhteen.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Minkälainen epäselvyys tähän liittyy?

**Comment by jtuohini** [comment]
"Teksti eli kirjoitelma on luettavaksi tarkoitettua kirjoitusta, jolla ilmaistu sisältö muodostaa asiakokonaisuuden, kuten artikkelin, novellin, runon tai romaanin." (https://fi.wikipedia.org/wiki/Teksti)
"Teksti [on] sanojen, lauseiden tai lausumien muodostama yhtenäiseksi tulkittavissa oleva merkityskokonaisuus puhutussa, viitotussa tai kirjoitetussa kielenkäytössä[.]" (https://tieteentermipankki.fi/wiki/Kielitiede:teksti)
"Teksti [on] sanoista, välimerkeistä, lauseista ja näitä laajemmista yksiköistä muodostuva, suullisesti tai kirjallisesti esitetty kielellinen kokonaisuus[.]" (https://tieteentermipankki.fi/wiki/Tekstuaalitieteet:teksti(2))
"Teksti [on] yleensä rajattu ja yhteenkuuluva kokonaisuus kirjoitettua kieltä[.]" (https://tieteentermipankki.fi/wiki/Language_Technology:text)
"Teksti [on] mikä tahansa, joka on tulkittavissa merkityskokonaisuudeksi[.]" (https://tieteentermipankki.fi/wiki/Semiotiikka:teksti)

YSO-asiasanan LT-suhde on **kirjalliset teokset**, mikä on hieman yllättävää ottaen huomioon **tekstit**-asiasanan kuuulumisen ryhmään 85. Jos tekstit ovat kirjallisia teoksia, pitäisi mainitut kaksi asiasanaa sulauttaa toisiinsa tai sitten katsoa hierarkiakokonaisuus uusiksi. Jos taas nykyisellä **tekstit**-asiasanalla haluttaisiin viitata korostetusti Tieteen termipankin tarjoamaan merkitykseen, pitäisi nykyinen asiasana muuttaa yksikköön ja rajata käyttö selvästi viittaaamaan nimenomaan tekstiin, ei tekstuaalisiin teoksiin. Ja huomioksi: kaikki **tekstit**-asiasanan ST-suhteiset asiasanat ovat jo yksikössä!

Nykyisellään Melindassa on käytetty **tekstit**-YSO-asiasanaa lähes 9 000 kertaa. Välillä viitataan tekstiin Tieteen termipankin tarjoamassa merkityksessä, välillä teoksiin. Välillä viitataan aiheeseen, välillä taas olisi kuvailussa pitänyt käyttää SLM-termiä, esim. **puheet** tapauksissa https://melinda.kansalliskirjasto.fi/byid/002460709 ja https://melinda.kansalliskirjasto.fi/byid/002483910, **näytelmät** tapauksessa https://melinda.kansalliskirjasto.fi/byid/002486370 ja jotakin ihan muuta tapauksessa https://melinda.kansalliskirjasto.fi/byid/002478644 (vrt. LC:n kuvailu samasta https://lccn.loc.gov/2008487001).

Summaten: nykyinen **tekstit**-YSO-asiasana on merkitykseltään epäselvä ja käyttönsä siksi äärettömän sekavaa.

**Comment by mariaforsen** [comment]
Sv. text = "språkligt yttrande, vanligen skrivet eller tryckt, ibland även muntligt" /Nationalencyklopedin
https://sv.wikipedia.org/wiki/Text

**Comment by mirmaid** [comment]
Mielestäni nuo kaikki määritelmät ovat kyllä hyvin saman kaltaisia. Jos ongelma syntyy YSOn hierarkiasta ja siitä mikä kaikki nähdään teoksena, niin hierarkian muuttaminen on varmaan täysin mahdollista. Varmaankaan kaikki tekstit eivät ole kirjallisia teoksia siinä mielessä kuin se yleisesti ymmärrettäisiin. Mutta jos tutkitaan vaikka säilyneitä antiikin tekstejä, ne eivät välttämättä ole kokonaisia teoksia, mutta myöskään yksikkö ei tuntuisi luontevalta.

**Comment by jtuohini** [comment]
Noiden viiden määritelmän mukaan teksti on joko "kirjoitusta", "merkityskokonaisuus", "kielellinen kokonaisuus", "kirjoitettua kieltä" tai "mikä tahansa, joka on tulkittavissa merkityskokonaisuudeksi". Eli kaikki ovat kaukana siitä, että kyseessä olisi teos. Teos voidaan ilmaista tekstinä (yhtä hyvin kuin puheena, lauluna, mimiikkana tms.), mutta teksti itsessään ei ole teos. Ja tämä kahtiajako on nyt YSO:ssa harhaanjohtavasti, ja sanaston nykyhierarkin mukaan esimerkiksi asiateksti, hyperteksti ja subteksti ovat kirjallisia teoksia.

**Comment by YSO-kokous** [comment]
Korjataan hierarkia vastaamaan paremmin arkiymmärrystä käsitteen tekstit-merkityksestä.

**Comment by jtuohini** [comment]
Ja olisi hyvä muuttaa asiasana yksikköön, jos halutaan viitata siteerauksissa vallitsevaan merkitykseen: teksti kirjoitettuna merkityskokonaisuutena ei ole kappalemäärällisesti laskettavissa oleva asia, joten ei ole luontevaa puhua "teksteistä" vaan vain "tekstistä".

**Comment by mirmaid** [comment]
^ Tämä ei saanut kannatusta kokouksessa, tyypillisesti Melindan viitteissä muutos yksikköön toimisi huonosti.

**Comment by jtuohini** [comment]
Miksi tämän ST-suhteiset asiasanat voivat olla yksikössä, jos tätä ei voi muuttaa yksikköön, kun niidenkin kohdalla on kyse asiasta, jota ei voida laskea kappalemääräisesti? Nimittäin Ysoon keväällä tehty muutos ei selvästikään ole riittävä, kun Melindaan on edelleen tullut tietueita, joissa **tekstit**-asiasanaa on käytetty väärin eli kuvaamaan kirjallisia teoksia, ei tietyntyyppistä tekstiä.
