### ISSUE TITLE
siviilipuolustus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12479]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[siviilipuolustus](http://www.yso.fi/onto/yso/p13732)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitaanko määritelmää?

**Perustelut ehdotukselle**

Huom. ero suhteessa väestönsuojaan. 
Ks. Wikidata, https://www.sanakirja.fi/custom/en-sv-fi/siviilipuolustus 
https://www.kielitoimistonsanakirja.fi/#/siviilipuolustus?searchMode=all

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. civilförsvar = "delvis civil försvarsorganisation med upp­gift att skydda civil­befolkning och icke-militära an­läggningar i händelse av krig"

https://termipankki.fi/tepa/fi/haku/civilf%C3%B6rsvar

**Comment by mirmaid** [comment]
Eli pitäisikö lisätä Kielitoimiston sanakirjan huomautus ja ohjaustermi siviilipuolustus (siviiliväestön suojelu) KÄ väestönsuojelu?

**Comment by fantsby-m** [comment]
Vaikea nähdä että nuo kaksi sekoittuisivat. Missä kontekstissa siviilipuolustus-termiä käytetään väestönsuojelumerkityksessä?

[huomautus: nuo www.sanakirja.fi/custom -alkuiset linkit eivät toimi]

**Comment by ilona-x** [comment]
MOT Englanti -sanakirja
antaa siviilipuolustus-haulla tuloksen, jossa on tuo väestönsuojelu ja maininta "vanhahtava"

Toimisiko tämä alla oleva linkki tuohon yllä mainittuun termiin:
http://www.sanakirja.fi/mot.general.en/finnish-english/siviilipuolustus

**Comment by mariaforsen** [comment]
Varsinkin ruotsalaisilla suomenkielisillä sivuilla käytetään siviilipuolustus-termiä paljon merkityksessä "väestön suojelu". Ruotsiksi pitää varmaan lisätä tarkenne, ks. https://termipankki.fi/tepa/fi/haku/civilf%C3%B6rsvar 
https://sv.wikipedia.org/wiki/Civilf%C3%B6rsvar

**Comment by YSO-kokous** [comment]
Ei muutosta suomeksi.

**Comment by mariaforsen** [comment]
"Siviilipuolustus on se työ, mitä valtion viranomaiset, kunnat, maakäräjät, alueet, yksityisyritykset ja vapaaehtoisjärjestöt tekevät. Työn tavoitteena on suojella siviiliväestöä ja varmistaa, että esimerkiksi sairaanhoito ja kuljetukset toimivat sodanuhan ja sodan aikana." / https://rib.msb.se/filer/pdf/30305.pdf
https://journal.laurea.fi/ukraine-forum-2023-ukrainan-puolustussodan-opit-vaestonsuojelun-ja-siviilipuolustuksen-kannalta/#8259b630 
Eli kun suomeksikin käytetään vähän vaihtelevista asioista niin emme varmaan voida ruotsiksi tarkentaa (vaikka ongelmaksi toki jää että sv-termi käytetään paljon enemmän myös väestönsuojelumerkityksessä).

**Comment by mirmaid** [comment]
^ Tuo on se, mitä oikeastaan yritin sanoa kokouksessa. Sekä toteuttajana että kohteena ovat siviilit, mutta toki puolustuksen kohteena aina ovat siviilit (sen ohella että puolustetaan alueen koskemattomuutta tms. ei-inhimillistä).
