### ISSUE TITLE
laki toimenpiteistä tupakoinnin vähentämiseksi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12472]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laki toimenpiteistä tupakoinnin vähentämiseksi](http://www.yso.fi/onto/yso/p21903)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sama kuin tupakkalaki (1976)

**Perustelut ehdotukselle**

Nimi mahdollisesti muutettu myöhemmin?

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Finlexissa kaksi eri: 
https://www.finlex.fi/fi/laki/ajantasa/kumotut/1976/19760693
https://www.finlex.fi/fi/laki/alkup/1976/19760693

**Comment by mirmaid** [comment]
^ Nuo ovat siis käsittääkseni sama - numero ja päiväys on sama. Toisessa on alkuperäinen teksti ja toisessa viimeisin?

**Comment by YSO-kokous** [comment]
Yhdistetään.
