### ISSUE TITLE
substraatti (kielitiede)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12473]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[substraatti (kielitiede)](http://www.yso.fi/onto/yso/p22968)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Maaritelmä/termimuodon/hierarkian tarkistus. Yksikkö vai monikko?

**Perustelut ehdotukselle**

Ristiriita hierarkian ja määritelmän välillä.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
TEPAssa substraatti määritellään: "valta-asemaan päässeessä kielessä säilynyt kadonneen kielen vaikutus"

https://fi.wikipedia.org/wiki/Substraatti : "kielitieteessä syrjäyttävässä kielessä ilmenevä syrjäytyneen kielen vaikutus."

**Comment by mirmaid** [comment]
^ Tuo voisi olla parempi määritelmä.

**Comment by YSO-kokous** [comment]
Muutetaan määritelmä.
