### ISSUE TITLE
henkilöityminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12475]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[henkilöityminen](http://www.yso.fi/onto/yso/p23095)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritellään/rajataan suhteessa personfikaatioon (ainakin ruotsiksi ja englanniksi)

**Perustelut ehdotukselle**

Ruotsiksi ja englanniksi nämä termit sekoittuvat nyt (eng. personification ja personification, ruotsiksi personifikation ja personifiering)

Voidaako lisätä määritelmiä vai ovatko rajat jo sellaisenaan selvät suomeksi, ja onko käyttö aina johdonmukaista? Jos suomeksi ok niin tarvitaan kuitenkin varmistusta siitä että kielikuvat=bildspråk soveltuu yläkäsitteeksi ja ruotsiksi sulkutarkenteeksi toiselle, mutta myös tietoa siitä viittaako henkilöityminen aina tähän "tulla liitetyksi tiettyyn henkilöön"? (Siinä tapauksessa on mahdollista luoda tarkenne ruotsiksi)

https://www.kielitoimistonsanakirja.fi/#/personifikaatio?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/henkil%C3%B6ity%C3%A4?searchMode=all

Molemmat termit ovat sen lisäksi monimerkityksisiä ruotsiksi (eri tavalla kuin suomeksi), ks. esim. https://www.psykologiguiden.se/psykologilexikon/?Lookup=personifikation%2C+personifiering

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:personifikaatio
https://tieteentermipankki.fi/wiki/Kielitiede:personifikaatio
https://sv.wikipedia.org/wiki/Personifikation

Voisi ehkä olla myös _elollistaminen_ (tai tarkenteena)? Mutta onko tässä https://melinda.kansalliskirjasto.fi/byid/018682361 kyse personifikaatiosta (suomalaisuus saa inhimillisiä ominaisuuksia)? Tätä ehkä käytetty jonkin verran väärin. Kielikuvat on tarkenteena liian suppea, esiintyy myös kuvataiteessa. 

Pitäisikö henkilöityminen eng. olla myös personalization, https://melinda.kansalliskirjasto.fi/byid/009249877

https://melinda.kansalliskirjasto.fi/byid/007053935, onkohan tässä kyseessä tietynlainen personifikaatio?

Henkilöityminen itselleni lähinnä "asian nähdään liittyvän tiettyyn henkilöön", mutta käytetään myös hiukan toisin "henkilöiden roolin korostuminen" ("politiikan henkilöityminen" = yksittäisten poliitikkojen roolin korostuminen puolueen tai asian ohi).

**Comment by YSO-kokous** [comment]
Personifikaatio (elollistaminen), KT personifikaatio (inhimillistäminen).

**Comment by mariaforsen** [comment]
Sv. -personifikation (fi. personifikaatio (elollistaminen) > personifikation (levandegörande) HT personfikation (förmänskligande), personifiering (levandegörande) 

-personifiering (fi. henkilöityminen) > personifiering (till viss person) > personifiering (politik och samhälle)

https://melinda.kansalliskirjasto.fi/F/5DJSEQPIEBVAB41IHPXPEV2NG95FY6IT2FFNVNHBRG53SMDN4D-02132?func=find-acc&acc_sequence=000320860
https://www.abo.fi/projekt/politikens-personifiering-institutionella-effekter-pa-relationen-parti-valjare-och-partisystem/
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_42939413387d34d1ba07a00612320186&list_id=1&keyword=henkil%C3%B6ity%C3%A4&word=henkil%C3%B6ity%C3%A4
https://www.sanakirja.fi/custom/en-sv-fi/henkil%C3%B6ityminen
https://www.sanakirja.fi/custom/en-sv-fi/henkil%C3%B6ity%C3%A4
https://termipankki.fi/tepa/fi/haku/personifiering
https://termipankki.fi/tepa/fi/haku/personifikation
https://www.lunduniversity.lu.se/lup/publication/8873049
https://research.abo.fi/en/publications/cirkusen-som-icke-%C3%A4r-personfixering-i-ett-finl%C3%A4ndskt-v%C3%A4ljarperspe
https://helda.helsinki.fi/server/api/core/bitstreams/4dd70294-2207-4cc9-a60e-427f36c9c99f/content
