### ISSUE TITLE
kulttuuridiplomatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12474]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kulttuuridiplomatia

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

cultural diplomacy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu. Käytetty Melindassa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Cultural_diplomacy), [LCSH](http://id.loc.gov/authorities/subjects/sh2013000948)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018114177

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [kulttuuridiplomatia](http://finto.fi/yse/fi/page/Y512474)

**Comment by mirmaid** [comment]
Olisi voinut käyttää myös tässä: https://melinda.kansalliskirjasto.fi/byid/018527377

5 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. kulturdiplomati HT kulturell diplomati 
https://termipankki.fi/tepa/fi/haku/kulttuuridiplomatia
https://www.sanakirja.fi/custom/en-sv-fi/kulttuuridiplomatia
https://melinda.kansalliskirjasto.fi/F/23GG9EI6188CK7YXB52AXSYQJGDRB8GN6K64L96SIVBAURHCG7-02896?func=find-b&request=kulturdiplomati&find_code=WRD&x=0&y=0
https://libris.kb.se/hitlist?d=libris&q=kulturdiplomati&f=ext&spell=true&hist=true&mf=&p=1
