### ISSUE TITLE
juhlapäivät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12477]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[juhlat](http://www.yso.fi/onto/yso/p1574)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko määritelmä tms. rajaus lisättävissä?

**Perustelut ehdotukselle**

Ruotsinkielinen vastine riippuu merkityksestä: https://www.kielitoimistonsanakirja.fi/#/juhla?searchMode=all 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_475290236487592b8a972f2b4197695b&list_id=1&keyword=juhla&word=juhla

Sanastossa on myös juhlapäivät, joka on tähän asti ollut "högtider" > pitäisi oikeastaan olla högtidsdagar

Högtider voi olla myös =juhlat, riippuen merkityksestä, vrt. https://svenska.se/tre/?sok=h%C3%B6gtid&pz=1

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
_Juhlat_-käsitteen rajaaminen joko "högtider" tai "fester" olisi varmaan aika mahdotonta, koska suomeksi ei ole käytettävissä kahta eri sanaa erilaisille juhlille. Voisiko olla _högtider och fester_?

**Comment by YSO-kokous** [comment]
Ei muutosta suomeksi.

**Comment by mariaforsen** [comment]
Sv. -högtider (fi. juhlapäivät) > högtidsdagar HT fest- och högtidsdagar

-fester (fi. juhlat) > fester och högtider 

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_756efbb6b33fddb072274aab40b4111a&list_id=1&keyword=juhlap%C3%A4iv%C3%A4&word=juhlap%C3%A4iv%C3%A4

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_475290236487592b8a972f2b4197695b&list_id=1&keyword=juhla&word=juhla

https://www.kielitoimistonsanakirja.fi/#/juhla?searchMode=all
Jfr
https://svenska.se/tre/?sok=fest&pz=1
https://svenska.se/tre/?sok=h%C3%B6gtid&pz=1
https://svenska.se/tre/?sok=h%C3%B6gtidsdag&pz=1

https://almanakka.helsinki.fi/sv/flagg-och-festdagar/
https://fi.wikipedia.org/wiki/Juhlap%C3%A4iv%C3%A4
