### ISSUE TITLE
työssäoloehto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12471]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

työssäoloehto

**Ehdotettu termi ruotsiksi**

arbetsvillkor

**Ehdotettu termi englanniksi**

previous employment requirement

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käsitettä tarvittaisiin niiden valtiopäiväasiakirjojen kuvailussa, joiden pääsisältö on ansiopäivärahan työssäoloehto.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ansiopäiväraha](http://www.yso.fi/onto/yso/p39101)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Valtiopäiväasiakirjojen kuvailussa.

**Ehdottajan organisaatio**

Eduskunnan kanslia
**Termiehdotus Fintossa:** [työssäoloehto](http://finto.fi/yse/fi/page/Y512471)

**Comment by ilona-x** [comment]
JUPO: työssäoloehdot http://www.yso.fi/onto/jupo/p675

**Comment by mirmaid** [comment]
Yleensä yksikössä, monikolla voidaan kuitenkin viitata esim. eri aikoina voimassa olleisiin ehtoihin tai sekä yrittäjän että palkansaajan työssäoloehtoon.

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/ty%C3%B6ss%C3%A4oloehto #
Eli "vaatimus, jonka mukaan henkilön on täytynyt olla töissä tietyn aikaa tietyn ajanjakson kuluessa ennen työttömäksi jäämistään" ? Vaatii ruotsiksi varmaan selitettä tai tarkennetta, koska arbetsvillkor voi viitata myös laajempaan asiaan.

Sv. arbetsvillkor (understöd)

**Comment by YSO-kokous** [comment]
Monikossa.
