### ISSUE TITLE
adult students

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12478]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[adult students](http://www.yso.fi/onto/yso/p25875)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi adult learners

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/adult%20learner

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Lisätty
