### ISSUE TITLE
yhteisöteatteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12485]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yhteisöteatteri](http://www.yso.fi/onto/yso/p12614)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ovatko englannin vastine (community theatre) ja linkitys oikein?
On nyt linkitetty tähän LCSH-käsitteeseen: http://id.loc.gov/authorities/subjects/sh85029256

**Perustelut ehdotukselle**

Wikidot-oppiympäristön mukaan "yhteisöteatteri on yleisnimitys teatterimuodoille, jotka korostavat teatterin kollektiivista yhteisöajatusta, vuorovaikutteisuutta ja yleisöä osallistavaa esitystapaa."
Q-teatterin mukaan "yleisötyö ja yhteisöteatteri tarjoavat kaikenlaisille ihmisille mahdollisuuden osallisuuteen, yhteisöllisyyteen ja vaikuttamiseen teatterin keinoin."

Sen sijaan englanninkielisen Wikipedian määritelmä community theatrelle on erilainen: "may refer to a production that is made entirely by a community with no outside help, or a collaboration between community members and professional theatre artists, or a performance made entirely by professionals that is addressed to a particular community."
Vrt. Cambridge Dictionary: "theatre performances involving or created for a group of people who live in a particular area. 'The play involved many local schoolchildren and was a wonderful piece of community theatre.'"

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Sv. on ollut social teater. Jos tällä viitataan samaan kuin LCSH community theater niin sv. olisi varmaan sama kuin SAOssa https://id.kb.se/term/sao/Communityteater%20 Ruotsiksi on lähikäsite myös samhällsteater, mutta meillä on erikseen yhteiskunnallinen teatteri. 

https://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:yhteis%C3%B6teatteri
https://www.sanakirja.fi/custom/en-sv-fi/yhteis%C3%B6teatteri

Wikipedia: community teater är en teaterform som involverar grupper av individer direkt för utveckling av gemenskap, kulturarbete, delaktighet, synliggörande, vidgad förståelse och stärkning av självkänslan

https://www.theseus.fi/bitstream/handle/10024/24227/Hiltunen_Marjukka.pdf?sequence=1&isAllowed=y

https://jyx.jyu.fi/handle/123456789/66486?locale-attribute=en

..Eli lähteiden perusteella minusta community theater/theatre vaikuttaa olevan oikea vastine.

**Comment by fantsby-m** [comment]
Marian linkittämässä Jyväskylän väitöksessä:

> Teoksen Draamaa ja teatteria yhteisöissä johdannossa (Ventola & Renlund 2005, 12) yhteisöteatteri määritellään paikalliseksi draamalliseksi toiminnaksi, joka kiinnittyy yhteisöjen tai yhteisöryhmien arkielämään pyrkien samalla tukemaan muutoksen mahdollisuutta.

**Comment by YSO-kokous** [comment]
Eng. vastine ja linkitys ok.

**Comment by mariaforsen** [comment]
Sv. social teater > communityteater
https://id.kb.se/term/sao/Communityteater%20
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/communityteater
https://sv.wikipedia.org/wiki/Communityteater
