### ISSUE TITLE
psykofysiologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12487]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[psykofysiologia](http://www.yso.fi/onto/yso/p7543)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mikä on tämän käsitteen ero fysiologiseen psykologiaan? Ovatko ne kaksi eri käsitettä vai sama käsite? Yhdistetäänkö vai ei? Jos ei yhdistetä, tarvitaanko muutoksia?

**Perustelut ehdotukselle**

LCSH:ssa Physiological psychology on ohjaustermi Psychophysiologialle. 
http://id.loc.gov/authorities/subjects/sh85108484
MESHissä on täsmälleen sama tilanne: https://finto.fi/mesh/fi/page/D011603
Wikipediassa nämä ovat erikseen:
https://en.wikipedia.org/wiki/Physiological_psychology
https://en.wikipedia.org/wiki/Psychophysiology
Wikipedian mukaan Psysiological psychology on "subdivision of behavioral neuroscience (biological psychology) that studies the neural mechanisms of perception and behavior through direct manipulation of the brains of nonhuman animal subjects in controlled experiments"
Wikipedian määritelmä psychophysiologylle taas on: "the branch of psychology that is concerned with the physiological bases of psychological processes."

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Myös SAOssa vain yksi termi ja toinen ohjausterminä: ttps://id.kb.se/term/sao/Psykofysiologi
Myös Psykologilexikon: https://www.psykologiguiden.se/psykologilexikon/?Lookup=psykofysiologi

**Comment by mirmaid** [comment]
Psykologian sanasto (v. 2005):

psykofysiologia: psykologisten ja fysiologisten prosessien suhteita tutkiva psykologian ja fysiologian raja-alue. Tutkimuksessa vaikutetaan jollakin tavalla koehenkilön psyykkiseen toimintaan ja selvitetään, miten hermoston toiminta tällöin muuttuu.

fysiologinen psykologia: psykologian osa-alue. Tutkii psyykkisten prosessien ja käyttäytymisen hermostollista, materiaalista ja toiminnallista perustaa. Esim. koehenkilölle voidaan antaa aivotoimintaan vaikuttavaa kemiallista ainetta, ja sitten seurataan, miten hän selviytyy tietyistä tehtävistä. Eläinkokeet ovat yleisiä.

**Comment by mirmaid** [comment]
Ja biologinen psykologia (myös YSOssa): psykologian suuntaus, jonka mukaan ihmisen käyttäytyminen ja mielen toiminta ovat kiinteässä yhteydessä ihmisen ruumiillisuuteen, esim. aivojen ja hermoston toimintaan. Biologisessa psykologiassa tutkitaan mm. hermoston rakenteen ja toimintojen, geeniperimän ja lajinkehityksen suhdetta ihmisen toimintaan

**Comment by mirmaid** [comment]
Lääketieteen termeissä nämä on käsitelty synonyymeinä.

**Comment by mirmaid** [comment]
Laitoin viestiä psykologian laitokselle aiheesta.

**Comment by mirmaid** [comment]
Vastauksia:
Vaikka termejä psykofysiologia ja fysiologinen psykologia käytetään usein synonyymeinä, niin näistä psykofysiologia painottuu selvästi ihmisillä tehtävään tutkimukseen, jossa tutkitaan aivojen ja muun kehon toiminnan ja psyykkisen toiminnan suhdetta, kun taas fysiologinen psykologia viittaa pikemminkin koe-eläimillä tehtävään tutkimukseen.

Esimerkiksi USA:ssa toimivan Society for Psychophysiological Research'n vuotuisissa konferensseissa ja sen julkaisemassa Psychophysiology-lehdessä  julkistetaan pääasiassa ihmisiillä tehtyä tutkimusta. Aivojen toiminnan osalta painottuu erityisesti EEG:llä tehtävä tutkimus, aivokuvantamistutkimusta (esim. fMRI) tekevien suosiessa muita konferensseja ja lehtiä. Psykofysiologian alan jonkin asteista hiipumista osoittaa se, että Federation of European Psychophysiology Societies on ilmeisesti lakkautettu, joskin Journal of Psychophysiology, jota se julkaisi, jatkaa toimintaansa. Kylmän sodan aikana, ja sen jälkeenkin, itä-länsi-suhteita vaalinut International Organization of Psychophysiology ja sen julkaisema International Journal of Psychophysiology näyttävät yhä olevan olemassa. Kahdessa viimeksi mainitussa lehdessä painotus on hyvin samansuuntainen kuin Psychophysiology-lehdessä.

Kansainvälisesti fysiologinen psykologia viittaa erityisesti koe-eläimillä tehtävään tutkimukseen, jossa psykologisissa koetilanteissa manipuloidaan tai mitataan aivojen toimintaa tai muuta fysiologista toimintaa. Terminä fysiologinen psykologia alkaa ehkä olla hieman vanhentunut ja alan tutkijat puhunevat nykyään käyttäytymisneurotieteestä (behavioral neuroscience) tms.

**Comment by mirmaid** [comment]
Yhden määritelmän mukaan kumpikin kokeellisia tutkimusotteita, mutta fysiologisessa psykologiassa tutkijan manipuloima riippumaton muuttuja on (koe-eläimen) hermoston toiminta (esim leesiokokeet) ja riippuva muuttuja koe-eläimen käyttäytyminen. Psykofysiologiassa taas riippumaton muuttuja on ihmisen kognitiivinen toiminta tai käyttäytyminen (esim tarkkaavaisuuden suunta) ja riippuva muuttuja aivotoiminnassa havaittavat muutokset. Tosin tämän määritelmän mukaan ihmisellä tehtävä  TMS-tutkimus olisi sitten kai fysiologista psykologiaa, kun siinä manipuloidaan koehenkilön aivotoimintaa.

**Comment by mirmaid** [comment]
Alkuperäinen vastaaja jatkaa:
Hyviä täsmennyksiä. En kuitenkaan sulkisi ihmisillä tehtävää TMS-tutkimusta psykofysiologian ulkopuolelle, jos tutkimus liittyy mielen toimintoihin. Nykyäänhän tehdään psykofysiologian piirissä TMS:n lisäksi myös aivojen stimulaatiota tasa- tai vaihtovirralla (direct current stimulation, DCS; alternating current stimulation, ACS).

**Comment by YSO-kokous** [comment]
Ei muutosta.
