### ISSUE TITLE
noviisit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12483]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[noviisit](http://www.yso.fi/onto/yso/p25201)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätäänkö määritelmä tai tarkenne?

**Perustelut ehdotukselle**

Kaksi mahdollista merkitystä, käytetty Melindassa molemmissa. 

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
YSA:ssa näyttää olleen huomautus:
>     Tarkoittaa munkki- tai nunnakokelasta

**Comment by mirmaid** [comment]
Ehkä voisi myös lisätä noviisit (vasta-alkajat) KÄ vasta-alkajat.

**Comment by YSO-kokous** [comment]
Noviisit (vasta-alkajat) KÄ vasta-alkajat. Palautetaan huomautus. Noviisit KT munkkikokelaat, nunnakokelaat, luostarikokelaat.

**Comment by mariaforsen** [comment]
Sv. noviser (kloster) 
https://svenska.se/tre/?sok=novis&pz=1
https://www.rikstermbanken.se/search?q=novis&s=termer
