### ISSUE TITLE
biometria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12484]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[biometria](http://www.yso.fi/onto/yso/p16671)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö varustaa sulkutarkenteella? Ja ohjaustermillä? Sama koskee myös biotunnistus-käsitettä.

**Perustelut ehdotukselle**

YSOssa on siis kaksi käsitettä: 1) biotunnistus eli biometrinen tunnistus, joka tarkoittaa ihmisen tai eläimen tunnistusta, esim. sormenjälkitunnistusta ja 2) biometria eli biostatistiikka, joka tarkoittaa tilastotieteen osa-aluetta, joka tutkii biologisia ilmiöitä. Tässä termit tulevat toisiaan lähelle ja voivat aiheuttaa sekaannusta. Biometriaa on käytetty kuvailussa aika paljonkin biotunnistuksen merkityksessä, esim. Melindassa ja Ylen kuvailussa.
https://melinda.kansalliskirjasto.fi/byid/018711539
https://melinda.kansalliskirjasto.fi/byid/018715979
https://melinda.kansalliskirjasto.fi/byid/016766691
Ks. Ylen kuvailu: https://yle.fi/t/18-83701/fi
Toisaalta esimerkiksi LCSH:ssa Biometrics on ohjaustermi molempiin: Biometric identification ja Biometry. Ja englannin adjektiivi biometric esiintyy molemmissa konteksteissa, vrt. MESH: Biometric Analysis KÄYTÄ Biometry ja lisäksi Biometric Authentication KÄYTÄ Biometric Identification. Eli ei sinänsä ihme, jos menevät keskenään sekaisin.
https://finto.fi/mesh/fi/page/D001699?clang=en
https://finto.fi/mesh/fi/page/D056667?clang=en

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Sv. -biometri (statistik)?
-biometri (identifiering) ANV biometrisk identifiering

**Comment by mirmaid** [comment]
Biometria (biotunnistus) KÄ biotunnistus. Toisen päätermi voisi olla biostatistiikka?

**Comment by YSO-kokous** [comment]
Biometria (biotunnistus) KÄ biotunnistus. Toisen päätermi voisi olla biostatistiikka, KT biometria (tilastotiede).

**Comment by mariaforsen** [comment]
https://mesh.kib.ki.se/term/D001699/biometry
https://mesh.kib.ki.se/term/D056808/biostatistics
( https://mesh.kib.ki.se/term/D056667/biometric-identification )

Sv. biostatistik HT biologisk statistik, biometri (statistik)
https://www.ne.se/s%C3%B6k/?t=uppslagsverk&q=biostatistik
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/biometri
https://id.kb.se/term/sao/Biometri

Jfr https://www.imy.se/verksamhet/dataskydd/dataskydd-pa-olika-omraden/arbetsliv/biometri/
