### ISSUE TITLE
attribuutio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12493]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[attribuutio](http://www.yso.fi/onto/yso/p4690)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan?

**Perustelut ehdotukselle**

Taiteen ja psykologian yhteydessä melko eri asia ehkä kuitenkin.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Myös Kyberturvallisuuden sanastossa
https://termipankki.fi/tepa/fi/haku/attribuutio
https://www.sanakirja.fi/custom/en-sv-fi/attribuutio

**Comment by mirmaid** [comment]
^ Jos tuon haluaisi huomioida, niin ehkä voisi olla attribuutio (tekijyys/tekijän henkilöllisyys/tjsp), oli sitten taideteoksen tai rikoksen tekijästä kyse. Ei taida olla Melindassa tuossa yhteydessä, mutta voi tietysti tulla. Tai sitten jätetään nykyiselleen, samaa kantaahan nämä ovat.

**Comment by YSO-kokous** [comment]
Ei muutosta.
