### ISSUE TITLE
Vihdin kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12494]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Vihdin kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

----

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Saman taivaan alla: kuvaelma Vihdin kirkon 250-vuotisjuhlissa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Vihdin kirkko](http://finto.fi/yse/fi/page/Y512494)

**Comment by mariaforsen** [comment]
Sv. Vichtis kyrka
