### ISSUE TITLE
DVD-äänilevyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1249]
#### Ehdotettu termi suomeksi

DVD-äänilevyt
#### Ehdotetut ohjaustermit

DVD-audiolevyt
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)
[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)

**Luontipäivämäärä:** 16.12.2004

**Muokkauspäivämäärä:** 16.12.2004, 16.12.2008

**Voyager-id:** 134947

**Termiehdotus Fintossa:** [DVD-äänilevyt](http://finto.fi/yse/fi/page/Y334947)

**Comment by MUUSA-kokous** [comment]
Löytyy muodossa DVD-levyt http://www.yso.fi/onto/yso/p15917.
Voisiko tämän sulkea ja poistaa YSAn ja YSOn käsite-ehdotuksista Fintosta? http://www.yso.fi/onto/ysa/Y334947

**Comment by mirmaid** [comment]
Lisätäänkö ohjaustermiksi?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi DVD-äänilevyt, DVD-audiolevyt KÄ DVD-levyt
