### ISSUE TITLE
mazurka (danser)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12498]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mazurka (danser)](http://www.yso.fi/onto/yso/p5781)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

masurka (danser)

**Perustelut ehdotukselle**

Dansen masurka har ofta stavats med z, men borde stavas med s.
https://www.saob.se/artikel/?unik=M_0337-0263.O7M9

**Ehdottajan organisaatio**

Svenska litteratursällskapet i Finland/Finlands svenska folkmusikinstitut

**Comment by mariaforsen** [comment]
Enligt Svenska Akademiens ordlista (2015) borde ordet hellre stavas "mazurka". 
https://svenska.se/tre/?sok=masurka&pz=1 Även i Nationalencyklopedin anges "mazurka" som primär form. På detta vis stavas ordet även i SAO: https://id.kb.se/term/sao/Mazurkor
