### ISSUE TITLE
renal artery stenosis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12507]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[renal artery stenosis](http://www.yso.fi/onto/yso/p26008)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englanniksi myös renal artery obstruction 

**Perustelut ehdotukselle**

Mesh

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Lisätty
