### ISSUE TITLE
uudistava oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12503]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[uudistava oppiminen](http://www.yso.fi/onto/yso/p25956)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englanniksi myös transformative learning

**Perustelut ehdotukselle**

https://tieteentermipankki.fi/wiki/Kest%C3%A4vyystiede:transformative_learning

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Lisätty.
