### ISSUE TITLE
hyvät käytännöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12508]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hyvät käytännöt](http://www.yso.fi/onto/yso/p18007)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi parhaat käytännöt?

**Perustelut ehdotukselle**

'parhaat käytännöt' -termillä tulee jonkin verran hakutuloksia. Käytetty esimerkiksi näissä julkaisuissa: https://shipowners.fi/uusi-merenkulun-kyberturvallisuusohjeistus-varustamoille-ja-aluksille-2/

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. OT bästa praxis
