### ISSUE TITLE
armeijakunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12505]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

armeijakunnat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

tämän lisäksi ehdotetaan samalla YSOon seuraavat SOTOssa ja Metatietosanastossa olevat käsitteet:

eskadroonat
laivueet (ilmavoimat)
laivueet (merivoimat)
lennostot
lentueet
lippueet
lippukunnat (ei linkitetty mihinkään)
patteri
patteristot

**Perustelut ehdotukselle**

Termit on Metatietosanastossa linkitetty nyt SOTOon, jota ei enää suositella käytettäväksi kuvailussa, halutaan linkittää johdonmukaisesti YSOon.

**Ehdotettu yläkäsite YSOssa (LT)**

 [joukko-osastot](http://www.yso.fi/onto/yso/p3948)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

moninainen julkaisu

**Ehdottajan organisaatio**

KK/MP

**Comment by fantsby-m** [comment]
Tuo _lippukunnat_ -termin jälkeen oleva _(ei linkitetty mihinkään)_ kopioitui ehdotukseen vahingossa, ei tarvitse huomioida.
Ja _patterit_ toki monikossa kuten muutkin.

**Comment by mariaforsen** [comment]
Sv.

armeijakunnat = armékårer

eskadroonat = skvadroner

laivueet (ilmavoimat) = flottiljer (flygvapnet)
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_fa92baba69058d07f4dd894253b71a6a&list_id=1&keyword=laivue&word=laivue

laivueet (merivoimat) = flottiljer (marinen)

lennostot = flygflottiljer
https://www.kielitoimistonsanakirja.fi/#/lennosto?searchMode=all
https://sv.wikipedia.org/wiki/Flygflottilj

lentueet = flyggrupper /Svensk-finsk militärordbok (1967)

lippueet = flottavdelningar https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_876464e12993f0ec8ea4a2b80328c0b9&list_id=1&keyword=lippue&word=lippue

_lippukunnat_ -huom! pitäisi määritellä tai rajata jos on tarkoitus viitata johonkin sotilaalliseen, ks. https://www.kielitoimistonsanakirja.fi/#/lippukunta?searchMode=all 
https://www.sanakirja.fi/custom/en-sv-fi/lippukunta
https://fho.sls.fi/uppslagsord/4433/fanika/

_patterit_ =batterier (militära enheter)
jfr https://finto.fi/mts/sv/page/m4678

_patteristot_ = sektioner (militära enheter), tarkenne tarvitaan ainakin ruotsiksi.. https://www.sanakirja.fi/custom/en-sv-fi/patteristo

**Comment by mirmaid** [comment]
lentue: ilmavoimien perusyksikkö, johon kuuluu yksi t. kaksi neljän lentokoneen parvea. 
lippue: merivoimien perusyhtymä, johon kuuluu 3–6 laivuetta sekä huoltoyksiköitä. 
eskadroona: ratsuväen perusyksikkö.
laivue: 1. esiupseerin johtama laivastoyksikkö. 
laivua: 2. ilmavoimien 2–3 lentuetta käsittävä taktis-hallinnollinen yksikkö. 
armeijakunta: divisioonaa suurempi (armeijaa pienempi) sotatoimiyhtymä. 
patteri: tykistön perusyksikkö; siihen kuuluvat tykit ja henkilöstö. 
patteristo: pattereista koostuva tykistön joukkoyksikkö. 

lennosto: 1. ilmavoimien osa, jonka yksiköt käyttävät kaikki samaa lentokonelajia. 2. ilmavoimien joukko-osasto. 
lippukunta: https://fi.wikipedia.org/wiki/Puolirykmentti (?)

**Comment by YSO-kokous** [comment]
Patterit/patteristot tarkenteella (sotilasyksiköt). Lippueet (merivoimat). Lennostot ok ilman tarkennetta.

Toivotaan Maanpuolustuskorkeakoulun kirjastolta määrittelyä käsitteelle lippukunta. Onko sama kuin wikipedian puolirykmentti? Vrt. myös https://fho.sls.fi/uppslagsord/4433/fanika/

**Comment by JoonasParviainen** [comment]
> Toivotaan Maanpuolustuskorkeakoulun kirjastolta määrittelyä käsitteelle lippukunta. Onko sama kuin wikipedian puolirykmentti? Vrt. myös https://fho.sls.fi/uppslagsord/4433/fanika/

Tätä ei ole nähdäkseni ihan helppo määritellä, koska organisaatiot kehittyivät nopeassa tahdissa. Alla eri tutkijoiden näkemyksiä aiheesta:

“The theoretical model for Swedish infantry was set in 1621 as a regiment of eight companies, each of 16 officers and non-commissioned officers and 126 corporals and men – 54 pikemen and 72 musketeers. A regiment would thus consist of 1,008 men, the same number as the theoretical Dutch regiment described by Henry Hexham. As with the Dutch battalions, a Swedish regiment would be divided to form two units (called ‘squadrons’ in Swedish usage), each of about 500 rankers plus NCOs and officers.”
-Roberts, Keith. Pike and Shot Tactics 1590-1660, Bloomsbury Publishing Plc, 2010.

“Kustaa lisäsi muskettimiesten osuutta. Hallinnolliseksi yksiköksi vakiintuneeseen komppaniaan tuli 72 muskettimiestä eli musketööriä ja 54 piikkimiestä eli pikinieeriä. Neljä komppaniaa muodosti skvadroonan, jossa oli siis 288 musketti- ja 216 piikkimiestä sekä upseereita ja aliupseereita. Skvadroona ryhmitettiin aivan niin kuin Morits Oranialaisella, jonka sotataito suuresti vaikutti ruotsalaiseen. Tavallisesti kolme skvadroonaa ryhmitettiin taistelussa prikaatiksi, jolla oli erilaisia muotoja tarvittavan taistelutavan mukaan.”
-Lappalainen, Jussi T. Aseet ja taistelut: sotataidon kolme vuosituhatta, Otava 1989. 

”Jalkaväen organisaation jakautuminen yksiköihin oli jo vuosina 1616-1618 monien harkintojen ja kokeilujen kohteena. Vanhan organisaation mukaan perusyksikkönä oli lippukunta, jonka rivivahvuus oli alun perin ollut jopa noin 500 miestä, mutta pudonnut siitä käytännössä noin 200-300:aan. Pyrkimyksenä näyttää olleen muodostaa taisteluyksiköksi alankomaalaiseen tapaan runsaan viidensadan miehen vahvuinen puolirykmentti, jota Länsi-Euroopassa jo tähän aikaan kutsuttiin skvadroona-nimellä. Jos tämä olisi jaettu neljään osaan, kuten Alankomaissa, olisi kuitenkin tullut toivoton pula sellaisesta päällystöstä, joka kykeni toimimaan ja opettamaan miehensä uuden järjestelyn ja taktiikan mukaisesti. Tässä vaiheessa oli siis tyydyttävä vähempiin alayksiköihin. Vuonna 1618 lippukunnat vahvistettiin 272 miehen vahvuisiksi. Kaksi lippukuntaa muodosti yhden skvadroonan. Skvadroonasta tuli kuitenkin pelkkä taistelumuodostelma. Hallinnolliseksi portaaksi tuli lippukuntien yläpuolelle rykmentti.” 
-Lappalainen, Jussi T. Sadan vuoden sotatie: Suomen sotilaat 1617-1721, Suomalaisen Kirjallisuuden Seura, 2001. 

”Pienimmäksi taisteluyksiköksi kuningas oli näihin aikoihin [1626] mennessä omaksunut neljästä komppaniasta muodostetun ”eskadroonan” eli ”kvaternian”, toisin sanoen taistelua varten järjestetyn pataljoonan.” 
”Kokeiltuaan Puolan-sodassa alankomaalaisten esikuvien mukaisilla taktillisilla muodoilla, Kustaa Aadolf oli v:een 1630 mennessä päässyt haluamaansa tulokseen. Pienin ala-osasto, 408 miehen vahvuinen eskadroona eli kvaternia, oli ryhmitetty suurin piirtein samalla tavoin kuin alankomaalainen puolirykmentti.”
-Hannula, J. O. [Kustaa II Aadolfin taktillinen reorganisaatio: 300-vuotismuistoksi](https://digi.kansalliskirjasto.fi/aikakausi/binding/1124367/articles/81621828), Suomen sotilasaikakauslehti (1932): 1, s. 577-598.

**Comment by mirmaid** [comment]
Vaikuttaa siltä, että fänika oli siis suomeksi lippue/lippukunta, myöhemmin nimeksi tuli komppania (eri kielillä), jotka muodostivat puolestaan puolirykmentin/skvadroonan (joka vakiintui tuossa 1600-luvun alussa sotilasyksiköksi). Eli voisi olla lippueet (jalkaväki) tai lippukunnat (jalkaväki) https://fi.wikipedia.org/wiki/Lippue_(jalkav%C3%A4ki). PartOf jalkaväki, mutta lisäisin myös YSOon määritelmän (Metatietosanaston määritelmän lähde ei ole tiedossa, voi olla että pitäisi puhua löyhemmin esim. "keskiajan lopulla ja uuden ajan alussa"). 

Otavan iso tietosanakirja: lippukunta: Ruots. fänika, ilmeisesti jo keskiajalla Ruotsissa saksalaisen esikuvan mukaan käyttöön otettu jalkaväkiyksikkö (vahvuudeltaan n. 500 miestä) ; jaettiin neljänneksiin ja ruotuihin. Ensimmäiset suomalaiset lippukunnat asetettiin 1555. Kustaa II Aadolfin aikana sijaan tuli komppania. (Tietosanakirja tuntee lippue-termille vain laivastoyksikön merkityksen.)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon lippukunnat (jalkaväki).
Lisäksi  otetaan sanastoon:
partiolippukunnat ja tälle ohjaustermiksi lippukunnat (partio)

**Comment by mariaforsen** [comment]
Sv.
-fänikor (infanteri)
https://sv.wikipedia.org/wiki/F%C3%A4nika
https://fho.sls.fi/uppslagsord/4433/fanika/
-scoutkårer 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_206eb991a9fb877868ba392f882d51a3&list_id=1&keyword=lippukunta&word=lippukunta
