### ISSUE TITLE
kasvattajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12504]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kasvattajat](http://www.yso.fi/onto/yso/p25974)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätäänkö tarkenne tms?

**Perustelut ehdotukselle**

Käytetty myös eri eläinten "kasvattajista", esim. turkiseläimistä, hevosista jne. Termi on ruotsiksi (ja englanniksi) eri kun viitataan johonkin muuhun kuin pedagogiikkaan. 
https://termipankki.fi/tepa/fi/haku/kasvattaja

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Mikähän olisi sopiva tarkenne? Lasten lisäksi kasvattajista voidaan puhua esim. nuorten urheiluseuratoiminnassa, jolloin (lasten kasvatus) ei ehkä oikein toimisi. Pedagogiikka tarkenteena rajaisi liikaa.

**Comment by mariaforsen** [comment]
Entä kasvatus (ihmiset)? Fostran rajautuu ihmisiin.

**Comment by YSO-kokous** [comment]
Kasvattajat (lasten ja nuorten).
