### ISSUE TITLE
rantasaunat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12509]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rantasaunat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Rantasaunat on käsitteenä selvästi tarkempi termi kuin saunat. Tällä hetkellä 
YSO-ontologiassa on tällä hetkellä "saunat" termin alakäsitteinä "yleiset saunat" ja "savusaunat", mutta rantasauna puuttuu. KOKO-ontologiassa on lisäksi vielä alakäsitteenä "tilaussaunat". 
Saunakulttuuri on merkittävä osa suomalaista kulttuuria ja siitä syystä toivoisi, että saunaan liittyvät asiasanat löytyisivät riittävällä tarkkuudella YSO-ontologiasta. Rantasaunalla tarkoitetaan selkeästi muista saunoista eroavaa saunatyyppiä, joka on  Suomessa hyvin yleinen saunatyyppi. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [saunat](http://www.yso.fi/onto/yso/p6381)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Rantasauna)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museokokoelmien luettelointi/asiasanoitus (aineistojen riittävän tarkka asiasanoitus tärkeää, jotta aineistot löytyvät Finna-hakupalvelusta). 

**Ehdottajan organisaatio**

Keski-Suomen museo

**Comment by mirmaid** [comment]
Ei Melindassa. https://fi.wikipedia.org/wiki/Rantasauna

**Comment by mariaforsen** [comment]
Sv. strandbastur

**Comment by YSO-kokous** [comment]
Hyväksytään rantasaunat, tutkitaan otetaanko myös pihasaunat/ulkosaunat.

**Comment by mirmaid** [comment]
Pihasaunat/ulkosaunat ei Melidassa. Finna.fi:ssä pihasauna pari kertaa asiasanana, vapaasanahaku tuottaa reilut 100 viitettä joissa pihasauna otsikossa tai esim. kuvauksessa.

Omasta puolestani voidaan odottaa kuvailutarvetta.

**Comment by mariaforsen** [comment]
Sv. gårdsbastur HT ute/utomhusbastur
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_8c69400393160196c916c6846bff897d&list_id=1&keyword=pihasauna&word=pihasauna

Varsinkin artikkeliaineistoa pihasaunoista löytyy kyllä jo Melindasta.

**Comment by nikopartanen** [comment]
Kun kerrottu tarve liittyy museoalan kuvailuun, voisi ajatella myös termin lisäämistä MAOon eikä YSOon. Jossainhan yleis- ja erikoisontologioidenkin rajojen on kuljettava. Tämä ei ole meidän päätettävissämme, mutta nostan keskusteluun.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa pihasaunat; otettaneen ohjaustermiksi ulkosaunat.
