### ISSUE TITLE
operatiiviset joukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12516]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

operatiiviset joukot

**Ehdotettu termi ruotsiksi**

Operativa trupper (puolustusselonteon 2021 käännös)

**Ehdotettu termi englanniksi**

Operational forces (puolustusselon 2021 käännös termille)

**Tarkoitusta täsmentävä selite**

"Koko valtakunnan alueella käytettäväksi tarkoitettuja sodan ajan joukkoja, jotka koulutetaan ja varustetaan soveltuviksi monipuolisiin ja vaativiin taistelutehtäviin eri toimintaolosuhteissa. Operatiivisia joukkoja käytetään tilanteen mukaan puolustuksen painopisteen muodostamiseen ja vaativimpiin taistelutoimiin"
-Valtioneuvoston puolustusselonteko 2021

**Perustelut ehdotukselle**

Konsepti on esiintyy puolustusjärjestelmän osana jo 1960-luvulla.

**Ehdotettu yläkäsite YSOssa (LT)**

 [puolustusvoimat](http://www.yso.fi/onto/yso/p7457)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.013291953
https://finna.fi/Record/arto.013165548
https://finna.fi/Record/taisto.108627

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by mirmaid** [comment]
14 + 2 kertaa Melindassa.

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/operativ%20trupp

**Comment by ilona-x** [comment]
SOTO: operatiiviset joukot http://www.yso.fi/onto/soto/p2062
