### ISSUE TITLE
kodinturvajoukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12517]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kodinturvajoukot](http://www.yso.fi/onto/yso/p25184)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Aiemmin ehdotettu "paikallisjoukot" olisi parempi termi suomalaisessa kontekstissa kuin kodinturvajoukot. 

**Perustelut ehdotukselle**

Suomessa ei ole kodinturvajoukkoja, termi ei esiinny puolustusvoimien virallisissa lähteissä eikä nähdäkseni edes kansanomaisena synonyymina paikallisjoukoille. 

Toiveita kodinturvajoukkojen perustamisesta esitettiin 2010-luvun alussa, mutta ne eivät johtaneet tuloksiin,  kts. esim: Puuperä, J. (2011). Parlamentaarinen neuvottelukunta esittää "Kodinturvakonseptia": Tuleeko Suomeen sittenkin kodinturvajoukot? Suomen sotilas : valtakunnallinen maanpuolustuslehti, 92(2), 31-32.

Puolustusselonteon 2021 määritelmän mukaisesti Puolustusvoimien sodan ajan joukot jaetaan käyttöperiaatteen mukaan operatiivisiin joukkoihin ja paikallisjoukkoihin. Kts. myös: https://fi.wikipedia.org/wiki/Kodinturvajoukot

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulun kirjasto

**Comment by mariaforsen** [comment]
https://www.sanakirja.fi/custom/en-sv-fi/kodinturvajoukot
https://www.sanakirja.fi/custom/en-sv-fi/hemv%C3%A4rn

Se että Suomessa ei ole tämännimisiä joukkoja ei mielestäni ole syy termin poistamiseen yleissanastosta. Ainakin meidän kirjastoon tulee myös paljon ruotsalaista ja muuta ulkomaista aineistoa. 

Ehkä paikallisjoukot voisi ottaa erillisenä terminä? 
https://www.kielitoimistonsanakirja.fi/#/paikallisjoukot?searchMode=all

**Comment by ilona-x** [comment]
tässä vielä linkki tuohon mainittuun ehdotukseen:  paikallisjoukot #12515

**Comment by fantsby-m** [comment]
https://www.kielitoimistonsanakirja.fi/kodinturvajoukot

**Comment by YSO-kokous** [comment]
Ei muutosta.
