### ISSUE TITLE
epäillyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1252]
#### Ehdotettu termi suomeksi

epäillyt
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)
#### Lähde

Lähde: Virolainen. Rikosprosessioikeus 2: Rikosprosessinosalliset

**Luontipäivämäärä:** 20.12.2004

**Muokkauspäivämäärä:** 20.12.2004, 16.12.2008

**Voyager-id:** 134993

**Termiehdotus Fintossa:** [epäillyt](http://finto.fi/yse/fi/page/Y334993)

**Comment by ilona-x** [comment]
Tälle olisi ollut tarvetta julkaisun "Poliisin tietoon tullut turvapaikanhakijoihin liittyvä rikollisuus 2016"  kuvailussa.

EKS: rikoksesta epäilty
Kaunokki: epäillyt

**Comment by mariaforsen** [comment]
Sv. brottsmisstänkta ET  misstänkta

**Comment by YSA-kokous** [comment]
rikoksesta epäillyt
