### ISSUE TITLE
Taiteiden yö -tapahtumat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12521]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Taiteiden yö -tapahtumat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Toimijakuvailun asiantuntijaverkoston kokous 10.1.2023:
"Ehdotetaan YSO-termin muuttamista Taiteiden yö -> Taiteiden yö -tapahtumat
Kantoon esim. Taiteiden yö (Helsinki, Suomi)" jne. yksittäiset auktorisoinnit olemassa
Vastaavasti (sama kokous):
"itsenäisyyden juhlavuosi (YSO) -> Kantoon eriteltyinä 
Ehdotetaan YSO-termin muuttamista itsenäisyyden juhlavuosi -> YSOon monikkomuotoon"

**Ehdotettu yläkäsite YSOssa (LT)**

 [kulttuuritapahtumat](http://www.yso.fi/onto/yso/p360)

**Ehdotetut temaattiset ryhmät**

 [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527), [90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ks. esim. Melinda

**Ehdottajan organisaatio**

Suomen kirjastopalvelu

**Comment by mariaforsen** [comment]
Sv. konstens natt-evenemang HT Konstens natt
https://sprakkonsulterna.se/stor-eller-liten-bokstav-i-ord-med-namn/
https://sprakbruk.fi/artiklar/bindestreck-en-liten-repetition/
jfr ex. https://www.mediesprak.fi/pride-stort-eller-litet-p

**Comment by YSO-kokous** [comment]
Hyväksytään. Tarkistetaan linkitys.
