### ISSUE TITLE
Niemelän kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12539]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Niemelän kartano

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

kartano Heinolassa, purettu v. 1985
https://finna.fi/Record/museovirasto.9a0fee60-28fa-4f48-a0f3-0e45b34cd737

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kartanot](http://www.yso.fi/onto/yso/p832)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Niemelän kakarat : elämää kartanossa ja muonamiesten mökeissä 

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. Niemelä gård (Heinola)
https://www.museovirasto.fi/sv/samlings-och-informationstjanster/bildsamlingarna/aktuellt/kamera-tidningens-artiklar-2020/lille-pietaris-stad
