### ISSUE TITLE
abessiv

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12533]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[abessiv](http://www.yso.fi/onto/yso/p29139)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mikan testi

**Perustelut ehdotukselle**

Mikan testi

**Ehdottajan organisaatio**

Mikan testi

**Comment by ilona-x** [comment]
testi

**Comment by ilona-x** [comment]
testikommentti2
sdfasdf

sadffdsa
asdffa
asdffd
