### ISSUE TITLE
alkuperäiskansojen tieto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12544]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

alkuperäiskansojen tieto

**Ehdotettu termi ruotsiksi**

urbefolknings vetskap

**Ehdotettu termi englanniksi**

indigenous knowledge

**Tarkoitusta täsmentävä selite**

Alkuperäiskansojen tieto on usein erityisesti paikallista tietoa, joka on suhteessa yhteisöllisiin järjestelmiin ja historiaan. Tämä sukupolvelta toiselle siirtynyt tieto voi käsittää tietoa paikallista ympäristöstä ja siinä elämisen tavoista sekä kulttuurisesti ja sosiaalisesti kestävästä elämäntavasta. - Tieteen termipankki 8.2.2024: Alkuperäiskansatutkimus:alkuperäiskansojen tieto.

**Perustelut ehdotukselle**

Suhde Kongressin kirjaston sanastoon on mutkikkaampi:  'Indigenous knowledge systems' löytyy auktorisoimattomana varianttina käsitteen Ethnoscience alta, ja termipankin määritelmä näyttää kuin olisi vapaasti käännetty sen huomautuksesta (https://lccn.loc.gov/sh96010624)
Toisaalta käsitteen Ethnoecology  (https://lccn.loc.gov/sh2001000104) tiedonlähdehuomautuksessa on (jo aika vanhasta lähteestä) kuvaus, jota käyttäisin perusteluna; juuri tämä on ymmärtäneekseni esim. alla olevien 'indigenous knowledge' -aiheisten teosten tulokulmaa: 
Encyclopedia of biodiversity, 2001 (ethnoecology: typically defined as the study of local knowledge and management of ecological interactions. Recently, some researchers have proposed an alternative definition, considering ethnoecology as an emerging field that focuses on local peoples' perception and management of complex and coevolved relationships between the cultural, ecological, and economic components of anthropogenic and natural ecosystems. It is concerned with the interaction between knowledge, practice, and production, and it is oriented toward applied research on conservation and community development)
Googletuksen perusteella suomenkielinen 'alkuperäiskansatieto' näyttää olevan aika vakiintunut juuri tässä merkityksessä, mm. seuraavassa:
 Saamelaisten alkuperäiskansaoikeudet ja saamelaiskulttuuria koskevien vaikutusten arviointi YVA-lain mukaisessa menettelyssä. (Ympäristöministeriön julkaisuja 2023:2) https://urn.fi/URN:ISBN:978-952-361-219-8
 s. 265: "Perinteiselle tiedolle ei ole olemassa yhtä yhtenäistä ja tyhjentävää määritelmää. Perinteisestä tiedosta puhuttaessa voidaan käyttää myös termejä ekologinen perinnetieto tai 
alkuperäiskansatieto. Arktinen YVA-raportissa käytetään termiä alkuperäiskansatieto, 
jonka määritelmä raportin kontekstissa on yhteneväinen Ottawan periaatteiden kanssa." https://static1.squarespace.com/static/58b6de9e414fb54d6c50134e/t/5dd4097576d4226b2a894337/1574177142813/Ottawa_TK_Principles.pdf

**Ehdotettu yläkäsite YSOssa (LT)**

 [tieto](http://www.yso.fi/onto/yso/p261)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532), [56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544), [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

 alkuperäiskansatieto

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [alkuperäiskansat](http://www.yso.fi/onto/yso/p5737), [perimätieto](http://www.yso.fi/onto/yso/p3690), [tutkimustieto](http://www.yso.fi/onto/yso/p27006), [tieteellinen tieto](http://www.yso.fi/onto/yso/p7837), [kokemustieto](http://www.yso.fi/onto/yso/p379)

**Vastaava käsite muussa sanastossa**

 [Tieteen termipankki ](https://tieteentermipankki.fi/wiki/Alkuper%C3%A4iskansatutkimus:alkuper%C3%A4iskansojen_tieto), [AIATSIS](https://www1.aiatsis.gov.au/subject/mtw36ba.html?k=default&l=60&linkType=term&w=2548&n=1&s=5&t=2), [LCSH](https://lccn.loc.gov/sh2003006652)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Routledge handbook of international law and anthropocentrism https://melinda.kansalliskirjasto.fi/byid/019017406

Resilience through knowledge co-production : indigenous knowledge, science, and global environmental change 
https://doi.org/10.1017/9781108974349 (maksullinen/sis.luettelo ja abstraktit)

Bridging Cultural Concepts of Nature : Indigenous People and Protected Spaces of Nature
https://doi.org/10.33134/AHEAD-1 (OA)

**Ehdottajan organisaatio**

Lapin korkeakoulukirjasto

**Comment by mirmaid** [comment]
2 kertaa Melindassa (alkuperäiskansojen tieto).

**Comment by mariaforsen** [comment]
Kannatan ehdotusta, mutta ei ehdotettua ruotsinkielistä muotoa. 

Sv. urfolkskunskap HT traditionskunskap (urfolkskunskap), traditionell kunskap (urfolkskunskap) 

-https://umu.diva-portal.org/smash/get/diva2:1633025/FULLTEXT01.pdf
-https://www.vtv.fi/sv/meddelanden/urfolkskunskap-och-forandringen-i-den-arktiska-miljon-ar-huvudteman-vid-motet-mellan-varldens-revisionsmyndigheter/
-https://sverigesradio.se/artikel/7173608
-https://www.miun.se/utbildning/kurser/genusvetenskap/genusvetenskap-gr-a-urfolksfeminismer/
-https://www.sttinfo.fi/tiedote/70085965/alkuperaiskansatieto-ja-arktisen-ympariston-muutos-paateemoina-maailman-tarkastusvirastojen-tapaamisessa?publisherId=1512&lang=fi
-https://www.oru.se/nyheter/nyhetsarkiv/nyhetsarkiv-2020/urfolkskunskap-av-vikt-for-bevarande-av-biologisk-mangfald/
-https://fou-anslag.raa.se/raa/default.asp?goto=raa.A&eid=Nzk1QjA4MDQxMDc5NUMwODAwMTA3ODQyMDgwMzAwMDgwNjE1Nzg3NDA0MDgwMjAxMDIwMTA2MjM=
-https://core.ac.uk/download/523299854.pdf
-https://www.sametinget.se/kunskapsmaterial-om-traditionell-kunskap-biologisk-mangfald

**Comment by krinay** [comment]
Yhdistelmä alkuperäiskansat + perimätieto Melindassa 68 kertaa.

**Comment by mariaforsen** [comment]
Yson perimätieto on sv. hävd (ongelmallinen vastine), ei oikein auta tähän ruotsin kohdalla.
