### ISSUE TITLE
Vanajaveden reitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12547]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vanajaveden reitti](http://www.yso.fi/onto/yso/p105261)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi Vanajan reitti?

**Perustelut ehdotukselle**

Myös käytössä.
https://fi.wikipedia.org/wiki/Vanajaveden_reitti

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. Vanajavesistråten > Vånåstråten
-https://kaino.kotus.fi/svenskaortnamn/?a=find&qfind=vanaja
-/uppslagsverk/encyklopedi/lång/vanajavesi
-https://sv.wikipedia.org/wiki/Vanajavesi
-https://www.uppslagsverket.fi/sv/sok/view-170045-Tavastland
