### ISSUE TITLE
luonnonmetsät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12549]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luonnonmetsät](http://www.yso.fi/onto/yso/p14250)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi luonnontilaiset metsät

**Perustelut ehdotukselle**

https://wwf.fi/alueet/suomen-metsat/luonnonmetsa/

https://urn.fi/URN:ISBN:978-952-11-5642-7

**Ehdottajan organisaatio**

KK/HR

**Comment by mariaforsen** [comment]
Sv. OT naturliga skogar
