### ISSUE TITLE
seksualisoituminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1254]
#### Ehdotettu termi suomeksi

seksualisoituminen
#### Ehdotetut ohjaustermit

erotisoituminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)
#### Lähde

Lähde: Lapsuuden muuttuva maisema; Näre, S. Julkisuudesta ja intimiteetistä; Jokapäiväinen pornomme

**Luontipäivämäärä:** 20.12.2004

**Muokkauspäivämäärä:** 23.8.2005, 23.8.2005, 8.6.2005, 8.6.2005, 20.12.2004, 16.12.2008

**Voyager-id:** 134996

**Termiehdotus Fintossa:** [seksualisoituminen](http://finto.fi/yse/fi/page/Y334996)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8184

**Comment by mariaforsen** [comment]
Sv. sexualisering
YSOssa on ennestään ollut tämä merktiys ruotsiksi: sexualisering (virheellinen vastine termille sukupuolittumiselle). Kannatan siis tämänkin termin ottamista, oli sitten muoto yllä ehdotettu tai seksualisointi tms. 
Melindassa esim. Elävät barbiet : lapsimissit rantautuvat Suomeen, Lasten seksualisointi kielletty.
https://sv.wikipedia.org/wiki/Sexualisering
https://en.wikipedia.org/wiki/Sexualization

**Comment by mirmaid** [comment]
Melindassa 2 kertaa seksualisointi, 8 kertaa seksualisoituminen.

**Comment by satuniininen** [comment]
Minusta näiden välillä on kuitenkin selkeä merkitysero. _Seksualisointi_ on aktiivista toimintaa mutta _seksualisoituminen_ toiminnan lopputulos.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. YSO-ylläpito tutkii ja valitsee kuitenkin vielä, kumpi termi soveltuisi paremmin käytettäväksi termiksi, seksualisoituminen_, vai _seksualisointi_. Ei tarvetta jatkokäsittelylle YSO-kokouksessa.
