### ISSUE TITLE
Nuutajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12542]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Nuutajärvi](http://www.yso.fi/onto/yso/p139767)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa on myös Nuutajärvi (Urjala)

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. Nuutajärvi =Notsjö > Nuutajärvi (Urjala : sjö)
Inga källor för svensk namnform på sjön.
https://kartta.paikkatietoikkuna.fi/?lang=sv

Jfr även Notsjö by: https://finto.fi/yso-paikat/fi/page/p107759 (egentligen inget officiellt svenskt namn på själva byn?)
