### ISSUE TITLE
neuroleptit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12559]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[neuroleptit](http://www.yso.fi/onto/yso/p9917)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermeiksi seuraavat ja mahdollisesti vaihdetaan päätermi FinMeSHin mukaiseksi (psykoosilääkkeet):
psykoosilääkkeet
antipsykootit
antipsykoottiset lääkkeet
psykoosilääkitys

**Perustelut ehdotukselle**

FinMeSH: https://finto.fi/mesh/fi/page/D014150
Wikipedia: https://fi.wikipedia.org/wiki/Antipsykoottiset_l%C3%A4%C3%A4kkeet

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
YSOssa on siis jo englanniksi ohjaustermi antipsychotic drugs ja tämä neuroleptit on linkattu Wikidatatan käsitteeseen antipsykottiiset lääkkeet http://www.wikidata.org/entity/Q208144 ja LCSH-termiin Antipsychotic drugs http://id.loc.gov/authorities/subjects/sh89002390

**Comment by mirmaid** [comment]
Lääketieteen termien mukaan psykoosilääkkeet voidaan jakaa ensimmäisen ja toisen sukupolven lääkkeisiin, termillä neuroleptit voidaan viitata joko näihin kaikkiin tai erityisesti vanhempiin. 

neurolepti:
ensimmäisen polven →psykoosilääkkeitä (mm. fentiatsiini-, tioksanteeni- tai butyrofenonijohdoksia), jotka vähentävät ajatusharhoja, kiihtyneisyyttä, sekavuutta, tunteiden ilmaisua ja aloitekykyä; käytetään myös kaikista psykoosilääkkeistä; vrt. toisen polven →psykoosilääke

toisen polven psykoosilääkkeet: atyyppinen psykoosilääke, epätyypillinen psykoosilääke | 1990-luvulta lähtien käyttöön tulleista psykoosilääkkeistä käytettävä yleisnimitys; ks. myös aripipratsoli, ketiapiini, klotsapiini, olantsapiini, paliperidoni, risperidoni, sertindoli, tsiprasidoni, tsotepiini

**Comment by mirmaid** [comment]
Em. perusteella siis kannattaisin päätermin muutosta (jota ehdotettukin).

**Comment by mariaforsen** [comment]
Sv. neuroleptika >  antipsykotiska läkemedel HT antipsykotika, antipsykotiska medel, psykosmediciner, psykosläkemedel

https://mesh.kib.ki.se/term/D014150/antipsychotic-agents
https://www.psykologiguiden.se/psykologilexikon/?Lookup=antipsykotika%2C+antipsykotiska+l%C3%A4kemedell
uppslagsverk/encyklopedi/lång/antipsykotika
"Ordet [neuroleptika](https://www.psykologiguiden.se/psykologilexikon/?Lookup=neuroleptika) används dels om första generationens antipsykotika, dels som synonymt med antipsykotika (oavsett vilken generation som avses)." 
https://www.1177.se/undersokning-behandling/behandling-med-lakemedel/lakemedel-utifran-diagnos/lakemedel-vid-psykossjukdomar/
https://kunskapsguiden.se/omraden-och-teman/psykisk-ohalsa/schizofreni/antipsykotisk-lakemedelsbehandling/
https://www.vardochinsats.se/schizofreni-och-liknande-tillstaand/behandling-och-stoed/antipsykotisk-laekemedelsbehandling/

**Comment by YSO-kokous** [comment]
Muutetaan käsitteen käytettäväksi termiksi psykoosilääkkeet. YSO-ylläpito tutkii ja päättää tykönään onko tarvetta muille ehdotuksessa mainituille ohjaustermeille.
