### ISSUE TITLE
tarraimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12550]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tarraimet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa käytetty

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Robotin työkalut: tartuntajärjestelmät

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: tarrain: _nostettavaan t. muuten liikuteltavaan esineeseen tarttuvia nosto- ja siirtolaitteita_. 

tarttuja: _tekn. työkalu jonka avulla robotti tm. laite pystyy käsittelemään eril. kappaleita_.

**Comment by mariaforsen** [comment]
Sv. gripare
Ei varmaan rajaudu robotteihin, ainakaan ilman tarkennetta, mutta ei se varmaan haittaa että käy kaikille koneellisille ratkaisuille. 
https://www.sanakirja.fi/custom/en-sv-fi/tarrain
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_f70fb0b426db4ea6dda815a07b8b712c&list_id=1&keyword=tarttuja&word=tarttuja

**Comment by YSO-kokous** [comment]
Tarraimet KT tarttujat.

**Comment by ilona-x** [comment]
TSR: tarttujat http://www.yso.fi/onto/tsr/p12695
