### ISSUE TITLE
HDL-kolesteroli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12551]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[HDL-kolesteroli](http://www.yso.fi/onto/yso/p16832)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

HDL-kolestroli > HDL lipoproteiini sama juttu LDL:lle.

Englanniksi High Density Lipoprotein ja Low-Density Lipoprotein

**Perustelut ehdotukselle**

HDL, LDL.. ovat lipoproteiineja eivät kolestrolia.  Liproteiinit sisältävät kolestrolia. Kolestroli on kolestrolia, ei hyvää eikä pahaa.

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
FinMeSHissä näyttää olevan molemmat:
HDL-lipoproteiinit http://www.yso.fi/onto/mesh/D008075
HDL-kolesteroli http://www.yso.fi/onto/mesh/D008076
LDL-lipoproteiinit http://www.yso.fi/onto/mesh/D008077
LDL-kolesteroli http://www.yso.fi/onto/mesh/D008078

**Comment by mariaforsen** [comment]
https://www.terveyskirjasto.fi/snk03083
Varmaan aika moni tiedonhakija haluaakin tietoa HDL-kolesterolista, mutta ei niinkään proteiineistä. Tutkija taas voi haluta tietoa proteiineistä.

**Comment by mirmaid** [comment]
Lääketieteen termit:

HDL: suuritiheyksinen rasvaproteiini | veriplasman lipoproteiini, jonka tiheys on yli 1,063 g/cm3 ja jonka runsaus pienentää sepelvaltimotaudin vaaraa 

IDL: keskitiheyksinen rasvaproteiini | veriplasman lipoproteiini, jonka tiheys on 1,006–1,019 g/cm3 (voidaan myös lukea LDL:n keveimmäksi jaokseksi) 

LDL: pienitiheyksinen rasvaproteiini | veriplasman lipoproteiini, jonka tiheys on 1,019–1,063 g/cm3 ja jonka runsaus katsotaan sepelvaltimotaudin vaaratekijäksi 

VLDL: hyvin pienitiheyksinen rasvaproteiini | veriplasman lipoproteiini, jonka tiheys on 0,93–1,006 g/cm3

lipoproteiini: rasvaproteiini | lähinnä veriplasmassa esiintyviä rasva-aineiden (mm. kolesterolin) ja proteiinien yhteenliittymiä

HDL-kolesteroli: suojakolesteroli, ”hyvä kolesteroli” | (veriplasman) suuritiheyksisen rasvaproteiinin osana oleva kolesteroli; ks. myös high-density lipoprotein

LDL-kolesteroli: haitallinen kolesteroli, ”paha kolesteroli” | (veriplasman) pienitiheyksisen rasvaproteiinin osana oleva kolesteroli; ks. myös low-density lipoprotein

VLDL-kolesteroli: (veriplasman) hyvin pienitiheyksisen rasvaproteiinin osana oleva kolesteroli, ks. myös very-low-density lipoprotein

**Comment by mirmaid** [comment]
Yritin etsiskellä tietoa HDL-proteiineista, joissa olisi jokin muu rasva kuin kolesteroli, mutta tulokset olivat riittävän ajan ja ymmärryksen puutteessa vähän inkonklusiivisia...

**Comment by YSO-kokous** [comment]
Ei muutosta.
