### ISSUE TITLE
hazaran kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12552]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hazaran kieli

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9789936801066

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto

**Comment by mariaforsen** [comment]
Sv. hazaragi
https://sv.wikipedia.org/wiki/Hazaragi 
NE
