### ISSUE TITLE
Östersund

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12555]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Östersund](http://www.yso.fi/onto/yso/p504973)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätäänkö tarkenne?

**Perustelut ehdotukselle**

Östersund on tavallinen paikannimi mm. Ruotsissa, ks. https://ortnamn.lantmateriet.se/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Wikipediassa se on kuitenkin vain kunta ja sen kunnan taajama, https://sv.wikipedia.org/wiki/%C3%96stersund_(olika_betydelser). Onko tarpeen huomioida kaikki mahdolliset pienet kohteet, johtaako samaan kaikkien kaupunkien kohdalla...

**Comment by mirmaid** [comment]
Ei tarvetta tarkenteelle.
