### ISSUE TITLE
kroonikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12554]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kroonikot](http://www.yso.fi/onto/yso/p15652)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö termit laittaa toisinpäin eli pitkäaikaissairaat varsinaiseksi termiksi ja ohjaustermiksi kroonikot?

**Perustelut ehdotukselle**

Pitkäaikaissairaat enemmän käytössä ja kroonikot tuntuu omituiselta käyttää joissakin julkaisuissa.

**Ehdottajan organisaatio**

KK/HR

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/kroonikko

Sv. kroniker > personer med långvarig sjukdom HT personer med långtidssjukdom, personer med kronisk sjukdom, långtidssjuka, kroniker 

-skillnad i betydelsen kronisk vs. långtidssjukdom
-https://termipankki.fi/tepa/sv/s%C3%B6k/pitk%C3%A4aikaissairas%20henkil%C3%B6
-https://svenska.se/tre/?sok=kronisk&pz=1
-https://www.sanakirja.fi/custom/en-sv-fi/pitk%C3%A4aikaissairaus
-https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_fb02fe91a84d68c8d2c2aef0b62541f9&list_id=1&keyword=pitk%C3%A4aikaissairas&word=pitk%C3%A4aikaissairas
-https://mesh.kib.ki.se/term/D002908
-https://www.1177.se/riktlinjer-och-material/sprakliga-riktlinjer/diverse-ord-och-uttryck-a-o/k2/kronisk-sjukdom--fortydliga/
-https://termipankki.fi/tepa/fi/haku/pitk%C3%A4aikaissairaus
-https://www.kielitoimistonsanakirja.fi/#/krooninen?searchMode=all
-https://www.stat.fi/meta/kas/pitkaaikainen_s.html
-https://www.stat.fi/meta/kas/pitkaaikainen_s_sv.html
-https://gupea.ub.gu.se/bitstream/handle/2077/20351/gupea_2077_20351_1.pdf?sequence=1&isAllowed=y
-https://www.finlex.fi/sv/laki/alkup/2023/20230117

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mariaforsen** [comment]
Muuttuiko samalla termin merkityskenttä? :

"Krooninen sairaus on pysyvä fyysinen tai psyykkinen tila, kun taas pitkäaikaissairaus on
sairaus, joka on kestänyt vähintään kuusi kuukautta ja siitä voi parantua. Krooninen
sairaus aiheuttaa hoidon tarpeen, pitkäaikaissairauden hoidon tarve voi olla joko pysyvä
tai ajoittainen (Kantola 2009)." /https://erepo.uef.fi/bitstream/handle/123456789/12985/urn_nbn_fi_uef-20131092.pdf?sequence=1&isAllowed=y
