### ISSUE TITLE
unilääketiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12568]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

unilääketiede

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

sleep medicine

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan sisällönkuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [lääketiede](http://www.yso.fi/onto/yso/p469)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH](http://Sleep Medicine Speciality)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018980442
https://melinda.kansalliskirjasto.fi/byid/018980465

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [unilääketiede](http://finto.fi/yse/fi/page/Y512568)

**Comment by ilona-x** [comment]
FinMeSH: [unilääketiede ](http://www.yso.fi/onto/mesh/D056508)

**Comment by mirmaid** [comment]
Kerran Melindassa.

Lääketieteen termit: uni- ja vireystilan säätelyä ja sen häiriöitä tutkiva ja hoitava erityisala (jota harjoittavalle voidaan myöntää → erityispätevyys)

**Comment by mariaforsen** [comment]
Sv. sömnmedicin (kunskapsområden) HT sömnmedicinsk specialitet
https://mesh.kib.ki.se/term/D056508/sleep-medicine-specialty
https://lakartidningen.se/wp-content/uploads/OldWebArticlePdf/6/6886/LKT0723s1835_1835.pdf
https://svenska.se/tre/?sok=specialitet&pz=1
https://www.sls.se/globalassets/svkf/bilder/utbildningsutskottet/oversyn.pdf
https://www.swedishsleepresearch.com/

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon unilääketiede.
