### ISSUE TITLE
Pukinmäen kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12562]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Pukinmäen kartano

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kartanot](http://www.yso.fi/onto/yso/p832)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](http://www.wikidata.org/entity/Q123671040)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pukinmäen kartano :rakennushistoriaselvitys : Helsinki 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Pukinmäen kartano](http://finto.fi/yse/fi/page/Y512562)

**Comment by mariaforsen** [comment]
Sv. Bocksbacka gård
https://www.hbl.fi/2022-02-28/har-ar-hela-listan-pa-hus-helsingfors-vill-bli-av-med/
https://sv.wikipedia.org/wiki/Bocksbacka
