### ISSUE TITLE
lapinkylät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12565]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lapinkylät](http://www.yso.fi/onto/yso/p17716)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään suomenkielinen ohjaustermi: siidat.

**Perustelut ehdotukselle**

Ks. https://melinda.kansalliskirjasto.fi/byid/018927599.

**Ehdottajan organisaatio**

**Comment by krinay** [comment]
Pitäisikö ohjaustermillä olla tarkenne erotukseksi kasvisuvusta, ks. Wikipedia: [Siidat](https://fi.wikipedia.org/wiki/Siidat)

**Comment by mariaforsen** [comment]
Sv. siidor HT sijddor ..Pitäisiköhän päätermiä tarkentaa/muuttaa ruotsiksi (tosin vaikeaa kun on hieman epäselvä merkityskenttä ja käyttö)?

https://samer.se/siidasamhallet
"Den första renbeteslagen och dess indelning av samerna i lappbyar ”kollektiviserade” samernas rätt till olika skatteland till en gemensam rätt inom den egna lappbyn. (Lappbyn hade sitt ursprung i siida, som var ett flyttningslag med tillhörande renhjord och renbetesland)" /Nationalencyklopedin

Sv-termi tosiaan riippuu siitä mitä tällä tarkoitetaan?

Wikipediassa: "Lapinkylä on saamelaisyhteisöihin viittaava historiallinen käsite. Nimitys tarkoitti sekä tiettyä [saamelaisten](https://fi.wikipedia.org/wiki/Saamelaiset) asumaa aluetta että sen hallintomallia ja ihmisiä." ...  "Myöhempinä aikoina lapinkylällä on tarkoitettu yksinkertaisesti Lapissa sijaitsevaa, usein saamelaisten asumaa kylää. Saamelaiskylistä käytetään nykyisin myös nimitystä saamenkylä"

https://saamelaisensyklopedia.fi/wiki/Siida Onko jokin syy sille ettei päätermi voisi olla siida? Vai onko tässä jopa kaksi eri käsitettä (toinen historiallinen/lainsäädännöllinen)?
https://saamelaisensyklopedia.fi/wiki/Lapinkyl%C3%A4t_ja_veromaat

**Comment by mirmaid** [comment]
94 viitettä Melindassa. Onko lapinkylät niissä korvattavissa > siidat, jos muutettaisiin?

**Comment by mariguttorm** [comment]
Saamentutkimuksessa käytetään Siidat esim. https://www.finna.fi/Record/tuni.9911486315605973 
 Siidan lait : saamelaisen poronhoidon oikeusperiaatteet ja -teoria

**Comment by YSO-kokous** [comment]
Palataan seuraavassa kokouksessa. Tutkitaan Melinda-viitteitä: sopiiko siidat-termi korvaavaksi nyt kuvaillulle aineistolle. Keskusteltiin siitä, ovatko lapinkylä ja lappby -termit synonyymisia siida-termille.

**Comment by mariguttorm** [comment]
Valtaosaan Melindassa nyt lapinkylät-termillä kuvailtuun aineistoon sopisi myös kuvailu _siidat_. Näissä aineistoissa Siida ja Lapinkylä tarkoittavat samaa eli saamelaisten asuttamaa aluetta, joka oli sopimuksilla rajattu muista lapinkylistä ja joka maksoi yhteistä lapinveroa. 

Melindassa 16 aineistoa kuvailtu siidat-termillä, nämä pääosin saamentutkimusta, esim. Siita eli lapinkylä yhteisöeläman perustana / Klemetti Näkkäläjärvi. tai Máttut - Máddagat : The roots of Saami ethnicities, societies and spaces / places / [editor: Tiina Äikäs]. tai Siidan lait : saamelaisen poronhoidon oikeusperiaatteet ja -teoria / Anne-Maria Magga. , jossa ” Siida tarkoittaa suvuista ja perheistä koostuvaa yhteisöä, joka hoitaa porojaan tietyllä maantieteellisellä alueella.” 

Käytetty myös Lapinkyläjärjestelmä, Siidajärjestelmä, Porokylät, Siitat. Pitäisikö olla ohjaustermeinä? 

Kuitenkin esim. alla olevassa sanottu, etteivät kaikki lapinkylät olleet siidoja: 

Ikimuistoinen oikeus : tutkimus Lapin alkuperäisistä maa- ja vesioikeuksista / Juha Joona.
”Lapinkylistä on ollut tapana käyttää myös ilmausta ‘siida’. Kaikki lapinkylät eivät kuitenkaan olleet siidoja ainakaan siinä merkityksessä, että kaikki - hallinnollisen - lapinkylän alueella asuvat l*********t olisivat käyttäneet kylän aluetta yhteisesti.”

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi:

siidat KÄYTÄ lapinkylät
