### ISSUE TITLE
lukukirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12560]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lukukirjat](http://www.yso.fi/onto/yso/p1637)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään "lukemistot"-viittausmuoto myös SLM:ään

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Kielitoimiston määritelmä - lukukirja: _koulussa äidinkielen opetukseen käytettävä lukemisto._

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
