### ISSUE TITLE
kesäleirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12563]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kesäleirit](http://www.yso.fi/onto/yso/p21435)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Korjataan Wikidatalinkki

**Perustelut ehdotukselle**

YSOssa on kesäsiirtolat ja se pitäisi linkittää Wikidatan kesäsiirtolaan.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tässä on vähän kulttuurisia eroja eri maissa, eikä linkitetyt wikipedia-sivut täysin vastaa toisiaan. Mutta ainakin kesäsiirtolat pitäisi linkittää ko. wikidatakohteeseen, kesäleirit taas olisi ihan ok linkityskohde englanninkielisen sivun sisältöön, suomenkielisessä historiallinen painotus.

**Comment by tpalonen** [comment]
Vaihdettu linkitys ehdotuksen mukaisesti.
