### ISSUE TITLE
monimenetelmätutkimus

### ISSUE THREAD

**Issue by OutiHintikka** [Finto-ehdotus/YSE#12561]
YSO-termiksi. Monimenetelmätutkimus, monimenetelmäisyys (ks. esim. https://journal.fi/sla/article/view/41281/10526) Teos: **Johdatus monimenetelmätutkimukseen.**

**Comment by mariaforsen** [comment]
Nythän sanastossa on jo tämä https://finto.fi/yso/fi/page/p40347
