### ISSUE TITLE
spelmansstämmor

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12567]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

**Ehdotettu termi ruotsiksi**

spelmansstämmor

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Ordet spelmansstämma har ingen direkt motsvarighet i finska och engelska. På engelska används också ordet "spelmansstämma" när man avser fenomenet som är utbrett i Sverige och Svenskfinland.

**Perustelut ehdotukselle**

Spelmansstämmor ordnas årligen i Svenskfinland (liksom i Sverige). Spelmansstämma är ett vedertaget begrepp som beskriver en speciell sorts verksamhet där spelmän träffas för att spela tillsammans. Inte samma sak som t.ex. folkmusikfestival.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musik](http://www.yso.fi/onto/yso/p26571), [98 Fritid. Hobbyer. Turism. Handarbeten](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Spelmansstämma](https://sv.wikipedia.org/wiki/Spelmansst%C3%A4mma), [Spelmansstämma](https://svenska.se/saol/?sok=spelmansst%C3%A4mma&pz=4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

För material i SLS arkiv, särskilt Samlingen för folklig musik och dansutövning (med förled "FMI" i signum för resurserna på olika nivåer). På sls.finna.fi, sök "spelmansstämma".

**Ehdottajan organisaatio**

Svenska litteratursällskapet i Finland
**Termiehdotus Fintossa:** [spelmansstämmor](http://finto.fi/yse/fi/page/Y512567)

**Comment by mariaforsen** [comment]
Wikipedia: "Skillnaden mellan en spelmansstämma och en folkmusikfestival är syftet. En festivals huvudsyfte är att inhyrda artister spelar för åhörare eller dansare, medan en spelmansstämmas huvudsyfte är att spelmän träffas och spelar med varandra."

https://svenska.se/tre/?sok=spelmansst%C3%A4mma&pz=1

Nationalencyklopedin: "publikt arrangemang i spelmansmusikens tecken, som består av ett scenprogram, där det samlande allspelet utgör ett obligatoriskt inslag, och ett informellt s.k. buskspel."

**Comment by MUUSA-kokous** [comment]
Kannatetaan käsitteen lisäämistä YSOon. Suoraa suomenkielistä vastinetta ei tunnu löytyvän, joten ehdotetaan  suomenkieliseksi muodoksi _spelmansstämmat_.
LT kansanmusiikkijuhlat

**Comment by mirmaid** [comment]
Jossakin verkkokeskustelussa oli suomeksi käännetty "pelimannipäivät". Mahdollinen olisi myös spelmansstämma-tapahtumat. Omaan korvaan tuo ruotsinkielisen sanan taivuttaminen monikoksi kuulostaa aika keinotekoiselta, täällä kerran käytetty noin: https://kansanmusiikkiliitto.fi/uudistusten-aika/.

**Comment by LeKorsu** [comment]
Pelimannijamit?

**Comment by YSO-kokous** [comment]
Hyväksytään käsite. Suomenkieliseksi käytettäväksi termiksi spelmansstämma-tapahtumat.

Keskustelussa pohdittiin, tarvittaisiinko sanastoon myös pelimannipäivät-tyyppistä käsitettä. Nähtiin, että tämä spelmansstämmä-tapahtumat käsite halutaan rajata kuitenkin suomenruotsalaiseen ja ruotsalaiseen kulttuuriin, joten suomenkielisenä vastineena sille ei käytetä pelimannitapahtumat-termiä.
