### ISSUE TITLE
Child Behavior Checklist

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12564]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Child Behavior Checklist](http://www.yso.fi/onto/yso/p19244)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Myös Child Behaviour Checklist

**Perustelut ehdotukselle**

Brittienglanti

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Muutettu
