### ISSUE TITLE
väkivaltarikokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12569]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[väkivaltarikokset](http://www.yso.fi/onto/yso/p20257)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Haluaisin hierarkian tarkistamista: nykyisin LT väkivaltarikokset ST koulusurmat JA perhesurmat -> po. LT henkirikokset ST koulusurmat JA perhesurmat 
LT väkivaltarikokset ST tai RT pahoinpitely

**Perustelut ehdotukselle**

Esim. https://fi.wikipedia.org/wiki/Luokka:Henkirikokset
https://rikoksentorjunta.fi/henkirikokset
https://rikoksentorjunta.fi/vakivaltarikokset

**Ehdottajan organisaatio**

Suomen Kirjastopalvelu

**Comment by mariaforsen** [comment]
"Suomen rikoslaissa henkirikoksiksi luetaan murha, tappo, surma, lapsensurma sekä pahoinpitelyn ja kuolemantuottamuksen rikosnimikeyhdistelmä." 

https://poliisi.fi/vakivaltarikokset
https://www.riku.fi/erilaisia-rikoksia/vakivaltarikos/
Eli ainakin pahoinpitely pitäisi varmaan olla alakäsite väkivaltarikoksille.
