### ISSUE TITLE
lähisuhdeväkivalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12574]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lähisuhdeväkivalta](http://www.yso.fi/onto/yso/p5389)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englanninkielinen termi Domestic violence on yleisesti käytetty turvakotien yhteydessä, kun puhutaan lähisuhdeväkivallasta.
Ja turvakodista käytetään englanninkielistä termiä Shelters for victims of domestic violence.

**Perustelut ehdotukselle**

THL: Shelters for victims of domestic violence

**Ehdottajan organisaatio**

Vantaan turvakoti, josta opintovapaalla ja opiskelen Metropoliassa sosionomi ylempi amk-tutkintoa.

**Comment by kmakarai** [comment]
Tämä on hankalampaa kuin miltä näyttää:

[WHO](https://iris.who.int/bitstream/handle/10665/77432/WHO_RHR_12.36_eng.pdf):
>"The term ‘domestic violence’ is used in many countries to refer to partner violence but
the term can also encompass child or elder abuse, or abuse by any member of a household.
‘Battering’ refers to a severe and escalating form of partner violence characterized by
multiple forms of abuse, terrorization and threats, and increasingly possessive and
controlling behaviour on the part of the abuser."

[YK](https://www.un.org/en/coronavirus/what-is-domestic-abuse):
>Domestic abuse, also called "domestic violence" or "intimate partner violence", can be defined as a pattern of behavior in any relationship that is used to gain or maintain power and control over an intimate partner. Abuse is physical, sexual, emotional, economic or psychological actions or threats of actions that influence another person. This includes any behaviors that frighten, intimidate, terrorize, manipulate, hurt, humiliate, blame, injure, or wound someone. Domestic abuse can happen to anyone of any race, age, sexual orientation, religion, or gender. It can occur within a range of relationships including couples who are married, living together or dating. [...]
>
>Victims of domestic abuse may also include a child or other relative, or any other household member.
>
>Domestic abuse is typically manifested as a pattern of abusive behavior toward an intimate partner in a dating or family relationship, where the abuser exerts power and control over the victim.

(Ainakin jenkeissä "domestic violence shelter" käytetään paljon enemmän kuin THL:n käyttämää termiä ja usein sitä vielä sukupuolitetaan, esim. "women's shelter" tai "battered women's shelter". Englannissa taas tuntuu olevan "domestic abuse refuge" enemmän käytössä.)

WMFI-AG/Kimberli

**Comment by AuHo22** [comment]
YSOn hierarkia oikeellisesti:

**YSO lähisuhdeväkivalta** LT 
intimate partner violence, po. _violence in close relationships_
https://research.fi/en/results/publication/02090377YJ

**YSO perheväkivalta** ST 
domestic violence
KT
family violence
household violence
intrafamily violence

**YSO parisuhdeväkivalta** ST 
intimate partner violence

https://thl.fi/aiheet/vakivalta/vakivallan-muodot/lahisuhdevakivalta

**Comment by tpalonen** [comment]
Yksi vaihtoehto olisi laittaa tuo domestic violence (kenties sulkutarkenteen kera) ohjaustermiksi useammalle käsitteelle. Tuo domestic abuse olisi varmasti hyvä lisä myös ohjaustermiksi.

**Comment by tpalonen** [comment]
Tein seuraavat muutokset:
perheväkivalta englanniksi family violence [oli aiemmin domestic violence]
domestic violence (family violence) KÄYTÄ family violence
domestic violence (intimate partner violence) KÄYTÄ intimate partner violence
domestic abuse KÄYTÄ family violence
