### ISSUE TITLE
appropriaatio (taide)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12579]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

appropriaatio (taide)

**Ehdotettu termi ruotsiksi**

appropriering (konst)

**Ehdotettu termi englanniksi**

appropriation (art) 

**Tarkoitusta täsmentävä selite**

""Appropriering" (efter engelskans appropriate: annektera, tillägna tis, passande) är en term inom samtidskonsten som används då ett konstverk ger en exakt återgivning av ett annat konstverk, men under den approprierande konstnärens namn. Material och teknik behöver inte överensstämma mellan de bägge verken. /Falskt & äkta"
sao 

**Perustelut ehdotukselle**

Tarvitaan (kuva)taiteellista appropriaatiota käsittelevän aineiston kuvailuun. 

Appropriaatio (taiteessa)
https://fi.wikipedia.org/wiki/Appropriaatio_(taiteessa)

**Ehdotettu yläkäsite YSOssa (LT)**

 [kohdistuva toiminta](http://www.yso.fi/onto/yso/p38217)

**Ehdotetut temaattiset ryhmät**

 [90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [taide](http://www.yso.fi/onto/yso/p2851)

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh93007118), [sao](https://id.kb.se/term/sao/Appropriering%20%28konst%29 )

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/005273554

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [appropriaatio (taide)](http://finto.fi/yse/fi/page/Y512579)

**Comment by jtuohini** [comment]
Eikö kuvailussa riittäisi taiteenlajia kuvaavan asiasanan käyttö yhdessä [**kulttuurinen omiminen**](http://www.yso.fi/onto/yso/p35073) -asiasanan kanssa?

**Comment by AuHo22** [comment]
Jonkin verran asian vieressä liikkuu termi, joka löytyy KOKO-sanastosta 
(Valokuvausalan ontologia VALO) eli ready made -teokset (tai ready made -taide), termi jota olisin ajoittain kaivannut kuvailussa. 
https://www.theartstory.org/definition/readymade-and-found-object/

Voisin kannattaa molempien ottamista YSO-sanastoon.
https://en.wikipedia.org/wiki/L.H.O.O.Q.
https://fi.wikipedia.org/wiki/Readymade

**Comment by mirmaid** [comment]
Melindassa 2 kertaa _appropriaatio_, kerran _appropriaatiotaide_ (kerran readymade ja kerran ready made -taide)

**Comment by mariaforsen** [comment]
Kannattan ehdotusta. Tämä löytyy tosiaan jo LCSH:sta ja SAOsta. Kulttuurinen omiminen ei ole sama asia.

**Comment by tpalonen** [comment]
Tarvitaan ainakin käyttöhuomautus, ettei mene sekaisin kulttuurisen omimisen kanssa. Sen ohjausterminä on kulttuurinen appropriaatio.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon muodossa appropriaatiotaide.
Lisätään sanastoon myös ohjaustermi:
appropriaatio (kulttuurinen omiminen) KÄYTÄ kulttuurinen omiminen

Tutkitaan seuraavaa kokousta varten ready made -taide. Huom! Tässä merkityksessä esiintyy myös muoto found object.

**Comment by mariaforsen** [comment]
Sv. appropriationskonst HT approprieringskonst, appropriering (konst) 

https://researchportal.helsinki.fi/sv/persons/alicia-johanna-nylund
https://lup.lub.lu.se/student-papers/record/1329972/file/1329973.pdf
https://www.filosofisktidskrift.se/fulltext/2016-3/pdf/FT_2016-3_56-64_claes_entzenberg.pdf

**Comment by mariaforsen** [comment]
Sv. ready-made, readymade
/uppslagsverk/encyklopedi/lång/ready-made
https://sv.wikipedia.org/wiki/Readymade

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Estetiikka:readymade

Otettaisiinko siis readymade-taide (YK taide vai taiteenlajit?) vai readymade-teokset (YK taideteokset)?

**Comment by tpalonen** [comment]
Ääni taiteelle. Tästä puhutaan tekniikkana tai taiteena, taidesuuntauksena. Genrenäkökulma tekee tästä minusta vähän "todellisemman" käsitteen, teosnäkökulma antaisi ehkä vähän hajanaisemman kuvan tai että on olemassa vain teoksia mutta ei taidetta.

**Comment by ilona-x** [comment]
ready made #2166

**Comment by ilona-x** [comment]
VALO: ready made -teokset http://www.yso.fi/onto/valo/p1180
OMA: ready made -teokset http://www.yso.fi/onto/oma/p103 KT readymade-teokset KT valmisesineet

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa readymade-teokset.

**Comment by mariaforsen** [comment]
Sv. ready-made-verk HT readymade-verk, ready-made konstverk
/uppslagsverk/encyklopedi/lång/ready-made
https://sv.wikipedia.org/wiki/Readymade
https://www.sttinfo.fi/tiedote/69961940/vasa-stads-museer-lyfter-fram-lokal-och-regional-konst-ar-2023?publisherId=67975446
https://svenska.se/tre/?sok=ready-made&pz=1
https://uppslagsverket.fi/sv/sok/view-170045-ReadyMade
