### ISSUE TITLE
kirkonopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12575]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kirkonopettajat

**Ehdotettu termi ruotsiksi**

kyrkolärare

**Ehdotettu termi englanniksi**

Doctors of the church

**Tarkoitusta täsmentävä selite**

Kirkonopettajilla (lat. Doctor Communis Ecclesiae) tarkoitetaan katolisessa kirkossa teologeja, joiden opetuksista on ollut hyötyä koko kristilliselle kirkolle, ja joiden oppineisuuden ja pyhyyden paavi tai ekumeeninen kirkolliskokous on tunnustanut. (wikipedia)

**Perustelut ehdotukselle**

Tähän olisi ollut tarvetta jo aiemmin Jeesus-lapsen Teresaa käsittelevän teoksen kohdalla, nyt sitten myös seuraavassa (ks. alla) ; mm. kirkkoisät-termi on asianmukaisesti YS0-sanastossa

**Ehdotettu yläkäsite YSOssa (LT)**

 [uskontoon liittyvä rooli](http://www.yso.fi/onto/yso/p687)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85038717), [Wikipedia](https://fi.wikipedia.org/wiki/Kirkonopettaja)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-7153-74-1 Heikkojen voima
978-952-7272-15-2 Pastoraalisääntö jne. Gregorius Suuren kirjoituksia

**Ehdottajan organisaatio**

Suomen Kirjastopalvelu
**Termiehdotus Fintossa:** [kirkonopettajat](http://finto.fi/yse/fi/page/Y512575)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/kyrkol%C3%A4rare
https://www.katolskakyrkan.se/aktuellt/stiftsnyheter/2021/tre-kyrkolarare-har-inforts-i-kyrkans-kalender

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
