### ISSUE TITLE
viralliset kuulutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12577]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[viralliset kuulutukset](http://www.yso.fi/onto/yso/p606)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan myös SLM-sanastoon

**Perustelut ehdotukselle**

Tarvitaan kuulutusten kuvailuun, esim. https://melinda.kansalliskirjasto.fi/byid/005373076

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
https://www.suomi.fi/palvelut/viralliset-ilmoitukset-ja-kuulutukset-ulvilan-kaupunki/93b8f6e5-d298-4b8b-9e73-2b31b66aaea9
https://www.kuntaliitto.fi/ajankohtaista/2019/julkiset-kuulutukset-viedaan-kunnan-verkkosivuille-112020-alkaen

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. officiella kungörelser /allfo HT offentliga kungörelser (fi. julkiset)

https://valter.sanakirja.fi/all/all/kuulutus
https://www.sanakirja.fi/custom/en-sv-fi-de-da-no/kuulutus
https://termipankki.fi/tepa/fi/haku/kuulutus
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9ba4d8620d1a44d63012d5a2bfff4240&list_id=1&keyword=virallinen&word=virallinen
https://termipankki.fi/tepa/fi/haku/virallinen
