### ISSUE TITLE
postludit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12576]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[postludit](http://www.yso.fi/onto/yso/p29929)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään "loppusoitot" viittausmuodoksi myös SLM:ään ja "sortiet" viittausmuodoksi sekä SLM:ään ja YSO:on.

**Perustelut ehdotukselle**

Postludeista käytetään ranskaksi myös nimitystä "sortie", esiintyen usein varsinaisena otsikkona (säveltäjinään mm. Marcel Dupré, Charles Gounod, Louis Lefébure-Wély, Heni Mulet ja Charles Tournemire), joten on luontevaa, että teoksen auktorisoidun hakutiedon alkuosalle on vastine SLM-sanastossa.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Ehdotus uudeksi määritelmäksi: Loppusoitto, yleisimmin liturgisen musiikin yhteydessä uruilla esitettävä itsenäinen kappale.
Lisätään sama määritelmä SLM:ään.

**Comment by mariaforsen** [comment]
Sv. OT efterspel (postludier) 
https://www.svenskakyrkan.se/salem/ord-och-moment

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mirmaid** [comment]
Hyväksytään/SLM.
