### ISSUE TITLE
luonto-oppaat (teokset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12572]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luonto-oppaat (teokset)](http://www.yso.fi/onto/yso/p9654)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Huomautuksen lisäys?

**Perustelut ehdotukselle**

Mikä on termin käyttötarkoitus? Nyt käytetty myös esim. tästä: Pöllöt : metsiemme hiljaiset saalistajat / Matti Alasaarela, Esa Hohtola, Jari Peltomäki ; kuvat: Matti Alasaarela ja Jari Peltomäki. Kirja käsittelee pöllöjä, ei luontoa tai erilaisia eläin-, kasvi- yms. lajeja. 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Maria tekee ehdotuksen määritelmästä.

**Comment by mariaforsen** [comment]
Esim: "Käytetään teoksista, jotka esittelevät luontoa ja siinä esiintyviä eri lajeja laajemmin, esim. nisäkkäitä, lintuja, kaloja, hyönteisiä, kasvia, puita, sammaleita, sieniä jne., ja joiden avulla voidaan oppia tunnistamaan näitä eri lajeja ympäristössään." ? Ks. esim. Kotimaan luonto-opas, Koko perheen luonto-opas, Suuri suomalainen luonto-opas, Lasten luontokirja : opas Suomen luontoon, Lapin luonto-opas...

**Comment by mirmaid** [comment]
Käytetään teoksista, jotka esittelevät luontoa ja siinä esiintyvää lajistoa laajasti, ja joiden avulla voidaan oppia tunnistamaan eri lajeja.
