### ISSUE TITLE
Vaahteramäki (Hultsfred, Ruotsi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12573]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Vaahteramäki (Hultsfred, Ruotsi)

**Ehdotettu termi ruotsiksi**

Lönneberga (Hultsfred, Sverige)

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Paikka esiintyy koko joukossa Vaahteramäen Eemeli -kirjoja, joista osan kuvailussa paikkakuntatieto viittaa todelliseen paikkaan, osassa virheellisesti fiktiiviseen paikkaan. Paikan auktorisointi ehkä poistaisi tämän sekaannuksen.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Kalmarin lääni](http://www.yso.fi/onto/yso/p508718)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q1879736)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018325814 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [Vaahteramäki (Hultsfred, Ruotsi)](http://finto.fi/yse/fi/page/Y512573)

**Comment by jtuohini** [comment]
"Lastenkirjailija Astrid Lindgrenin luoma satuhahmo Vaahteramäen Eemeli asuu Hultsfredin alueella sijaitsevassa Vaahteramäessä eli Lönnebergassa." (https://fi.wikipedia.org/wiki/Hultsfredin_kunta)

**Comment by mirmaid** [comment]
Pitäisikö paikan nimi olla suomeksi Lönneberga vai Vaahteramäki? https://www.wikidata.org/wiki/Q1879736

**Comment by mirmaid** [comment]
YSO-paikkoihin tämä kaiketi auktorisoidaan muodossa Lönneberga (Hultsfred) KT Vaahteramäki (Hultsfred), sen mukaan mihin kuntaan Lönneberga nykyään kuuluu. Onko tämä sitten lastenkirjallisuuden hakijalle ihanteellinen ratkaisu, on toinen kysymys...

**Comment by jtuohini** [comment]
Mielestäni yleensäkin on parempi käyttää suomenkielistä paikannimeä, jos sellainen on (aktiivisesti käytössä), olipa kyse aikuisille tai lapsille suunnatusta aineistosta. Ihan vain Ruotsin osalta esim. vanhastaan suomenkielinen paikkakunta _Alatornio (Ruotsi)_ ~ _Nedertorneå (Sverige)_, koko valtio _Ruotsi_ ~ _Sverige_, suomalaisvähemmistöinen pääkaupunki _Tukholma_ ~ _Stockholm_ jne.

**Comment by mirmaid** [comment]
Varmasti, mutta voiko sanoa että ko. todellisen paikan nimi suomeksi on Vaahteramäki, jos se esiintyy ainoastaan fiktiossa ja mahdollisesti tätä fiktiota käsittelevässä tutkimuksessa?

**Comment by jtuohini** [comment]
Todellinen ja käytetty nimi vastaan virallinen eli julkishallinnollisen päätöksen mukainen nimi lienevät pohdinnan kaksi ääripäätä. Jos hyväksytään edellisen mukaiset nimet sanastoon, niin vaikkapa _Lontoo_ on kelvollinen, mutta jos hyväksynnän ehtona on vain jälkimmäinen, niin pitäisi varmaan käyttää muotoa _London_. Mitähän tesaurusstandardi sanoo paikannimien kelvollisuudesta tältä osin?

**Comment by mirmaid** [comment]
Noin tarkkaan ei tätä rajattu, mutta ajatus oli sen suuntainen, että nimeä olisi kuitenkin käytetty tietoaineistoissa kyseisestä paikasta. Kutsuttaisiinko Lönnebergaa Vaahteramäeksi esim. lehtiartikkelissa, jossa käsiteltäisiin vaikka sinne rakennettua tehdasta, eikä mitenkään viitattaisi Eemeli-kirjojen käännöksiin? Jos näin on, niin epäilemättä voidaan harkita uudelleen. Tai voidaan käsitellä tätä Siskussa. Ei mikään itsestäänselvä ratkaisu kyllä - tosin vähän ihmettelimme sitäkin, miksi ylipäätään paikka oli haluttu kuvailuun merkitä.

**Comment by jtuohini** [comment]
"Tieto kuvailtavan teoksen aiheena olevasta todellisesta paikasta tallennetaan, mikäli se on mainittu otsikossa, mainittu tiivistelmässä ja/tai se on hahmotettavissa aineistosta keskeisenä seikkana." (Sisällönkuvailuoppaan luku 8; vrt. oppaan prosessikaavio.) Ehkä Vaahteramäen Eemeli -kirjoissa paikka on keskeinen, kun aika monta kertaa oli Melindassa Vaahteramäki pistetty, tosin muodossa Vaahteramäki (fiktiivinen paikka)?

**Comment by mirmaid** [comment]
Ratkaistu Siskun kokouksessa 23.8.2024.

**Comment by mirmaid** [comment]
Tähän saatiin myös Kotukselta vahvistus:
_Vaahteramäkeä ei voi pitää Ruotsin Lönneberga-nimisestä paikkakunnasta vakiintuneena eksonyyminä. Jos esimerkiksi suomenkielisessä mediassa kirjoitettaisiin tapahtumista kyseisessä paikassa, tulisi käyttää paikallista nimeä Lönneberga. Myös kaunokirjallisuudessa Lönneberga on suositettava nimimuoto: jos joku kirjoittaisi esimerkiksi paikkakunnalle sijoittuvan salapoliisitarinan, tapahtuisi se Lönnebergassa._
