### ISSUE TITLE
sienirihmastot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12580]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sienirihmastot](http://www.yso.fi/onto/yso/p20267)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi myseeli

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/sienirihmasto

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ok, lisäisin kuitenkin monikossa kuten päätermikin.
