### ISSUE TITLE
hutsulit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12584]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hutsulit

**Ehdotettu termi ruotsiksi**

huzuler

**Ehdotettu termi englanniksi**

Hutsuls

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [itäslaavit](http://www.yso.fi/onto/yso/p38377)

**Ehdotetut temaattiset ryhmät**

 [61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ukrainalaiset](http://www.yso.fi/onto/yso/p10166)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85062771), [Wikipedia, suomi](https://fi.wikipedia.org/wiki/Hutsulit), [Wikipedia, englanti](https://en.wikipedia.org/wiki/Hutsuls)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim.
https://melinda.kansalliskirjasto.fi/byid/017463361
https://melinda.kansalliskirjasto.fi/byid/019045131

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [hutsulit](http://finto.fi/yse/fi/page/Y512584)

**Comment by mariaforsen** [comment]
Sv. huzuler HT huculer, hutsuler
