### ISSUE TITLE
Kiimajärvi (Pyhäjärvi : järvi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12589]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kiimajärvi (Pyhäjärvi : järvi)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Samalla myös kylä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melinda

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Kiimajärvi (Pyhäjärvi : järvi)](http://finto.fi/yse/fi/page/Y512589)

**Comment by mariaforsen** [comment]
Sv. Kiimajärvi (Pyhäjärvi i Viborgs län : sjö) HT Kiimajärvi (Pyhäjärvi : sjö), Komsomolskoye?
https://en.wikipedia.org/wiki/Lake_Komsomolskoye
https://tupa.gtk.fi/kartta/geologinenkartta200/sgs_037_r.pdf
https://www.google.fi/travel/hotels/entity/ChcIkK2jh8zZgdAIGgsvZy8xMjE5c2JqdhAE?utm_campaign=sharing&utm_medium=link&utm_source=htls&ved=0CAAQ5JsGahcKEwi4tIndtPaGAxUAAAAAHQAAAAAQBQ&ts=CAEaBAoCGgAqBAoAGgA

Sv. Kiimajärvi (Pyhäjärvi i Viborgs län : by) HT Kiimajärvi (Pyhäjärvi : by)

https://www.sprakinstitutet.fi/sv/sprakhjalp/namnhjalp/ortnamn/namn_pa_ryska_orter_i_svenskan : "I en finländsk kontext kan det kännas onaturligt att använda translittererade former som Lachdenpochja, Kanneljarvi, Impilachti, Pitkjaranta och Achvenlambi på svenska eftersom formerna ser finska ut men har en för finskan främmande stavning. Därför rekommenderas de finska namnen Lahdenpohja, Kanneljärvi, Impilahti, Pitkäranta och Ahvenlampi i stället." ... "Det är aldrig fel att välja en translittererad form, men i vissa fall är det mer ändamålsenligt att välja det finska namnet. I osäkra fall är det klokast att välja translitterering."

https://www.sprakinstitutet.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/2000/primorsk_eller_bjorko
