### ISSUE TITLE
metamodernismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12582]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

metamodernismi

**Ehdotettu termi ruotsiksi**

metamodernism

**Ehdotettu termi englanniksi**

metamodernism

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Metamodernismi on postmodernismin syrjäyttäjä, uusi tyylisuunta taiteessa ja filosofiassa, joka yleistynee terminä tulevina vuosina/vuosikymmeninä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [02 Filosofia](http://www.yso.fi/onto/yso/p26545), [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564), [90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-91-89526-13-6

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [metamodernismi](http://finto.fi/yse/fi/page/Y512582)

**Comment by mirmaid** [comment]
Määritelmäkin saadaan wikipediasta: ..."värähtelyksi modernistisen innostuneen sitoutuneisuuden sekä postmodernin ironisen irtonaisuuden välillä, värähtelyksi toivon ja melankolian, naiiviuden ja tietämisen, empatian ja apatian, yhtenäisyyden ja moninaisuuden, totaalisuuden ja fragmentoituneisuuden sekä puhtauden ja epäselvyyden välillä. He huomauttavat, ettei värähtely ole tasaista, vaan ennemminkin heiluriliikkeen kaltaista, jossa innostus muuttuu fanatismiksi, fanatismi ironiaksi, ironia apatiaksi ja apatia taas innostukseksi. Metamoderni haluaa tietoisesti olla irti ajasta ja paikasta ja viitata moniin aikoihin ja paikkoihin samanaikaisesti: tavoitella alati pakenevaa horisonttia."

**Comment by mirmaid** [comment]
7 kertaa Melindassa.

**Comment by mariaforsen** [comment]
https://fritanke.se/bokhandel/bocker/metamodernism/
https://www.bbl.fi/2024-04-26/ar-du-barbie-eller-kaarija-metamodernismen-raddar-oss/

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon. YSO-ylläpito miettii tälle sopivat YSO-ryhmät. Mentäneen laajalla tulkinnalla eli ei ainoastaan taiteeseen rajautuva käsite.
