### ISSUE TITLE
koettu terveys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12585]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koettu terveys](http://www.yso.fi/onto/yso/p21377)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi itsearvioitu terveys?

**Perustelut ehdotukselle**

termimuoto tuli vastaan yhdessä väitöskirjassa ja lisäksi YSOssa tämä näyttää olevan englanniksi self-rated health 

**Ehdottajan organisaatio**

kk/il

**Comment by AuHo22** [comment]
Mielestäni seuraavassa käytetty synonyymisesti: itsearvioitu terveys = koettu terveys vs. objektiivisesti arvioitu terveys
https://www.duodecimlehti.fi/duo11490

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.

**Comment by ilona-x** [comment]
Nyt tuli vastaan väitöskirjassa muoto "itse raportoitu terveys", jonka varmaan voisi myös lisätä ohjaustermiksi?

"Self-rated health (also called Self-reported health, Self-assessed health, or perceived health) "
Lähde: https://en.wikipedia.org/wiki/Self-rated_health
