### ISSUE TITLE
hoitosuunnitelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12583]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hoitosuunnitelmat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

fi        hoitosuunnitelma

määritelmä
potilaan, hänen läheisensä tai laillisen edustajansa ja terveydenhuollon ammattihenkilön yhteisymmärryksessä laatima terveydenhuollon suunnitelma, joka sisältää tiedot potilaan tunnistetusta hoidon tarpeesta, asetetuista tavoitteista, toimenpiteistä niiden saavuttamiseksi sekä tavoitteiden toteuttamisaikataulusta

huomautus
Potilaan asemasta ja oikeuksista annetun lain (785/1992) mukaan terveyden- ja sairaanhoitoa toteutettaessa on tarvittaessa laadittava tutkimusta, hoitoa, lääkinnällistä kuntoutusta koskeva tai muu vastaava suunnitelma. Potilasasiakirjoista annetun sosiaali- ja terveysministeriön asetuksen (298/2009) mukaan potilasasiakirjoihin, kuten hoitosuunnitelmaan, tulee merkitä potilaan hyvän hoidon järjestämisen, suunnittelun, toteuttamisen ja seurannan turvaamiseksi tarpeelliset sekä laajuudeltaan riittävät tiedot.
Käsitekaavio: Suunnitelmat.

Lähde: Sosiaali-, terveys- sekä työ- ja elinkeinoalojen yhteisten palvelujen sanasto (TEM ja STM, 2020) https://termipankki.fi/tepa/fi/haku/hoitosuunnitelma

**Perustelut ehdotukselle**

kuvailu

Melinda:
hoitosuunnitelma x 24
hoitosuunnitelmat x 28
+ lisäksi FinMeSH-terminä x 17 ja hoidokki-terminä x 11

**Ehdotettu yläkäsite YSOssa (LT)**

 [suunnitelmat](http://www.yso.fi/onto/yso/p1751)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH: hoitosuunnitelma](http://www.yso.fi/onto/mesh/D010347)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Patients with chronic cardiovascular diseases and diabetes in primary health care :self-care activity, health-related quality of life and effect of participatory care plan : a randomized controlled trial http://urn.fi/URN:ISBN:978-952-61-4944-8

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [hoitosuunnitelmat](http://finto.fi/yse/fi/page/Y512583)

**Comment by AuHo22** [comment]
KT terveys- ja hoitosuunnitelmat (?)

Näköjään myös esim. susi- ja kalakannoilla voi olla hoitosuunnitelmia:

https://www.consilium.europa.eu/fi/policies/eu-fish-stocks/multiannual-management-plans/
https://julkaisut.valtioneuvosto.fi/handle/10024/161865

**Comment by mirmaid** [comment]
Aulin ehdottama muoto olisi yksiselitteinen päätermiksi? https://www.kanta.fi/ammattilaiset/terveys-ja-hoitosuunnitelma

**Comment by ilona-x** [comment]
Voisiko mahdollisesti olla hoitosuunnitelmat (terveydenhuolto), kun tuo terveys-ja hoitosuunnitelmat kuulostaa omaan korvaan hiukan kömpelöltä, ja onkohan se mahdollisesti merkitykseltään rajatumpi kuin mitä hoitosuunnitelmat. 🤔 

---

"Mikä on terveys-ja hoitosuunnitelma?
- Terveydenhuoltolain ja potilasasiakirja-asetuksen edellyttämä kiireettömissä hoidoissa tarvittaessa tehtävä suunnitelma, jonka sisältö on määritelty kansallisesti

- Tiedonhallintapalvelussa jatkuvasti ylläpidettäväasiakirja, joka laaditaan potilaskeskeisesti pitkäaikais-ja monisairaiden henkilöiden hoidon suunnittelun ja koordinoinnin tueksi avohoitoon"

Lähde: https://www.julkari.fi/bitstream/handle/10024/146415/Terveys-%20ja%20hoitosuunnitelma%20-toimintamalli_2022.pdf?sequence=1&isAllowed=y

---

Kielitoimiston sanakirja https://www.kielitoimistonsanakirja.fi/#/hoitosuunnitelma?searchMode=all

hoitosuunnitelma

1. terveyden- t. sairaanhoitoa koskeva suunnitelma.
Hoitosuunnitelma vanhuksen toimintakyvyn tukemiseksi.

---

Tepa https://termipankki.fi/tepa/fi/haku/hoitosuunnitelma
fi        hoitosuunnitelma

määritelmä
potilaan, hänen läheisensä tai laillisen edustajansa ja terveydenhuollon ammattihenkilön yhteisymmärryksessä laatima terveydenhuollon suunnitelma, joka sisältää tiedot potilaan tunnistetusta hoidon tarpeesta, asetetuista tavoitteista, toimenpiteistä niiden saavuttamiseksi sekä tavoitteiden toteuttamisaikataulusta

huomautus
Potilaan asemasta ja oikeuksista annetun lain (785/1992) mukaan terveyden- ja sairaanhoitoa toteutettaessa on tarvittaessa laadittava tutkimusta, hoitoa, lääkinnällistä kuntoutusta koskeva tai muu vastaava suunnitelma. Potilasasiakirjoista annetun sosiaali- ja terveysministeriön asetuksen (298/2009) mukaan potilasasiakirjoihin, kuten hoitosuunnitelmaan, tulee merkitä potilaan hyvän hoidon järjestämisen, suunnittelun, toteuttamisen ja seurannan turvaamiseksi tarpeelliset sekä laajuudeltaan riittävät tiedot.

Lähde: Sosiaali-, terveys- sekä työ- ja elinkeinoalojen yhteisten palvelujen sanasto (TEM ja STM, 2020)

---

Tepa https://termipankki.fi/tepa/fi/haku/terveyssuunnitelma
<työterveyshuolto>

fi        terveyssuunnitelma

määritelmä
asiakkaan ja terveydenhuollon ammattihenkilön yhteisymmärryksessä laatima työterveyshuollon suunnitelma, jonka tavoitteena on terveyden ja työkyvyn edistäminen sekä työkyvyttömyyden ehkäisy

huomautus
Terveyssuunnitelmasta säädetään hyvästä työterveyshuoltokäytännön periaatteista, työterveyshuollon sisällöstä sekä ammattihenkilöiden ja asiantuntijoiden koulutuksesta annetussa valtioneuvoston asetuksessa (708/2013). Sen mukaan jokaisessa terveystarkastuksessa on laadittava henkilökohtainen terveyssuunnitelma.
Terveyssuunnitelmaa seurataan ja toteutetaan jatkuvasti työuran aikana. Myös työttömälle voidaan laatia terveyssuunnitelma.

Lähde: Sosiaali-, terveys- sekä työ- ja elinkeinoalojen yhteisten palvelujen sanasto (TEM ja STM, 2020)

**Comment by ilona-x** [comment]
LCSH:
Nursing care plans http://id.loc.gov/authorities/subjects/sh85093387

Wikipedia: 
https://en.wikipedia.org/wiki/Nursing_care_plan

**Comment by AuHo22** [comment]
Lieneekö niin, että kyseessä on kaksi eri asiaakin, eli terveyden edistämisen ja sairauksien ehkäisyn suunnitelma, so. terveyssuunnitelma (usein työterveyshuollon yhteydessä), ja sitten hoitosuunnitelma joka tehdään jo olemassa olevan sairauden/sairauksien hoitoon, jossa yhteydessä näkee kyllä myös tuota kombinatorista muotoa?

**Comment by mariaforsen** [comment]
Sv. vårdplaner (sjukvård)
https://id.kb.se/term/sao/V%C3%A5rdplanering
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/v%C3%A5rdplan

Sv. hälsoplaner
https://www.ttl.fi/teemat/tyoterveys/tyoterveyshuolto/terveystarkastukset/terveyssuunnitelma

**Comment by AuHo22** [comment]
Linkkaukset voisivat ehdottaa esim. hoitosuunnitelmat (sairaanhoito) ja terveyssuunnitelmat (työterveys) suuntaan. Toisaalta vanhusten toimintakykyä edistäviä terveyssuunnitelmiakin voi olla.. (?)´

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa hoitosuunnitelmat (terveydenhuolto).

**Comment by mariaforsen** [comment]
Sv. vårdplaner (hälso- och sjukvård) HT behandlingsplaner, omvårdnadsplaner https://termipankki.fi/tepa/fi/haku/hoitosuunnitelma
https://www.rikstermbanken.se/search?q=v%C3%A5rdplan&s=termer
https://termipankki.fi/tepa/fi/haku/terveydenhuolto
https://svenska.se/tre/?sok=h%C3%A4lsov%C3%A5rd&pz=1
