### ISSUE TITLE
Rahkolankylä (Saarijärvi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12581]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Rahkolankylä (Saarijärvi)](http://www.yso.fi/onto/yso/p168104)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Synonyymi: "Rahkola (Saarijärvi)"

**Perustelut ehdotukselle**

Rahkolankylää kutsutaan myös vain Rahkolaksi, tämä nimi näkyy ainakin tiekylteissä. Rahkolankylän pitäisi silti olla ensisijainen nimi, koska se on MML:n käyttämä.

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Asutusnimihakemisto:

Rahkolankylä : Rahkolankylällä
= Rahkola : Rahkolassa

Kyläkunta

Sijaintikunta: 	Saarijärvi
Maakunta: 	Keski-Suomi

Lähde:https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=rahkolankyl%C3%A4
