### ISSUE TITLE
neuropsykiatriset häiriöt, neuropsykiatria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12587]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neuropsykiatriset häiriöt, neuropsykiatria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Nepsy on lyhenne neuropsykiatrisista haasteista, jotka johtuvat aivotoiminnan rakenteellisesta ja toiminnallisesta poikkeavuudesta. Neuropsykiatrisia vaikeuksia ovat esimerkiksi ADHD ja ADD, Aspergerin oireyhtymä ja muut autismikirjon häiriöt, kehityksellinen kielihäiriö sekä Touretten oireyhtymä.

**Perustelut ehdotukselle**

täällä tuli eteen kun haettiin nepsy-materiaalia ettei sitä ole käytetty asiasanana tmv joten asiakkaat eivät löydä. Ja kysyntä on todella suurta. Lyhennettä kuitenkin käytetään jo melko virallisesti,   on kirjojen nimissä ym.
Voisiko sitä lisätä neuropsykiatriaa käsitteleviin teoksiin? Ilmeisesti juuri tuon löydettävyysongelman vuoksi Tampereella on tehty yhteistyönä terveydenhuoltopuolen kanssa materiaalipaketti aiheeseen liittyvästä kirjallisuudesta, 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Nepsy

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kts yllä.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [neuropsykiatriset häiriöt, neuropsykiatria](http://finto.fi/yse/fi/page/Y512587)

**Comment by mirmaid** [comment]
_Neuropsykiatriset häiriöt_ -käsitteellä on ohjausterminä nepsy-häiriöt ja nepsy-oireet. Nepsy esiintyy tyypillisesti monenlaisten yhdyssanojen alkuosana, vähemmän ihan pelkästään. Pelkkä "nepsy" ohjausterminä neuropsykiatrian tieteenalalle tuntuu omaan korvaani vähän liian puhekieliseltä (vähän niin kuin matematiikkaan tai historiaan viitattaisiin termeillä matikka tai hissa), lisäksi pelkkä nepsy(t) viittaa usein neurokirjon ihmisiin.

Toisaalta liittyykö vaikeus mahdollisesti siihen, että haussa käytetty järjestelmä ei hyödynnä olemassaolevia ohjaustermejä?

**Comment by mariaforsen** [comment]
Olisiko nepsy KÄ neuropsykiatriset häiriöt kuitenkin ok? Sitä toista ohjausta en kyllä kannata. 
https://naenepsy.fi/
Sv. nepsy, neuropsykiatriska svårigheter ANV neuropsykiatriska störningar https://osterbottensvalfard.fi/om-oss/projekt/prima-botnia-valmaende-osterbotten-2/unga-med-neuropsykiatriska-utmaningar-nepsy/

**Comment by YSO-kokous** [comment]
Kokous ei nähnyt aihetta muutoksille tällä hetkellä.

Keskustelua: Nepsy on jo sanastossa ohjausterminä muodoissa "nepsy-häiriöt" ja "nepsy-oireet". Nähtiin, että "nepsy" sellaisenaan arkikielessä, ilman liitteitä, viittaa enemmän henkilöihin kuin häiriöihin. Keskusteltiin myös, onko nimittäminen häiriöksi hyvä. Todettiin, että pysytään toistaiseksi tässä nimityksessä, mutta seurataan terminkäyttöä ja tehdään mahdollisia muutoksia tilanteen mukaan.
