### ISSUE TITLE
taiteilijakirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12591]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taiteilijakirjat](http://www.yso.fi/onto/yso/p13272)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritelmä kaipaa laajennusta: Tarkoittaa kirjanmuotoista taiteilijan tekemää kuvataideteosta -> po. Tarkoittaa kirjanmuotoista taiteilijan tekemää taideteosta.

**Perustelut ehdotukselle**

Ei tarvitse olla kuvataideteos, voi olla määritelmältään laajemmin taideteos vs. kirjaveistos tms.
Esim. https://nmwa.org/learn/library-research/artists-books/
https://www.theseus.fi/bitstream/handle/10024/813601/Korhonen_Heini.pdf;jsessionid=C0644EF41B8567BC0BA0D3B97227A2F7?sequence=3
Kuvataiteen näkökulmasta:
https://jyx.jyu.fi/bitstream/handle/123456789/51069/URN%3aNBN%3afi%3ajyu-201608263886.pdf?sequence=1&isAllowed=y

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by jtuohini** [comment]
Kuvanveisto eli veistotaide on kuvataiteen alalaji (myös YSO:ssa), joten muutos olisi huononnus: jos määritelmästä uupuu kuva-sana, voisi kyseeseen tulla myös maataiteen, äänitaiteen ym. piiriin kuuluvat teokset, joita tuskin luettaisiin taiteilijakirjoiksi.

**Comment by AuHo22** [comment]
Kysymys on oikeastaan se, että taiteilijakirja on/tai voi olla myös kirja, ei vain kuvataideteos, eli kirjamaisuus uupuu määritelmästä?
"_Rikhardinkadun kirjaston taiteilijakirjakokoelman ja kirjaston
vaihtuvan näyttelytoiminnan tavoitteena on ollut esitellä taiteilijakirjojen monimuotoisuutta.
Informaatikko, nyt jo eläkkeelle jäänyt Emmi Martin kuvailee: ”Taiteilijakirja voi olla kirja tai
kirjaa muistuttava taideteos_." yo. linkki s. 58 
Myös https://www.kirjastokaista.fi/taiteilijakirjat-esittelyssa/     "voi olla sarjakuva tms." myös  esimerkki Pirstaleisuudesta / Timo Rytkönen (joka ei ehkä visuaalisuudellaan ensi sijassa toimi, vaan kommentoi kirjan ideaa muuten)

Tällä hetkellä taiteilijakirjat LT on kirjalliset teokset, ja jos halutaan pitää kiinni suppeasta määritelmästä, niin sitten oikea LT olisi taideteokset, eli taiteilijakirja halutaan nähdä kuvataiteilijan lähes uniikkina tuotoksena? 
Ja voidaanko rinnalle sitten ottaa termi livres d´artistes kuvaamaan näitä modernistien "historiallisia taiteilijakirjoja", joissa voi olla kyse poikkitaiteellisista kokeiluista typografian/kuvan+sanan vuorovaikutuksessa tms. -ismien nimissä näin jälkikäteen ajateltuna, ks. yo. linkki luku 3; Livre d´artiste – taiteilijakirjan ranskalainen edustaja vai edeltäjä?

**Comment by mirmaid** [comment]
Tarkoittaa kirjanmuotoista taiteilijan tekemää taideteosta.

YK taideteokset
