### ISSUE TITLE
koptit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12590]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koptit](http://www.yso.fi/onto/yso/p26243)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Coptics -> Copts. Coptics ja "Coptic Christians" ohjaustermeinä.

**Perustelut ehdotukselle**

Ihmisistä käytetään "Copts"; Coptic taas on pikemmin attribuutti, esim. "Coptic Orthodox Church", "Coptic Catholic Church" ja "Coptic language".

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by tpalonen** [comment]
Tehty ehdotetut muutokset. Otin "Coptics"-termin pois.
