### ISSUE TITLE
Me too -kampanja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12595]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Me too -kampanja

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

----

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 metoo, #metoo

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.abo.fi/fi/uutiset/tohtorinvaitos-siita-miten-naiset-kertovat-kokemuksistaan-raiskauksesta-suomenruotsalaisessa-metoo-kampanjassa-dammen-brister/

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Me too -kampanja](http://finto.fi/yse/fi/page/Y512595)

**Comment by jtuohini** [comment]
LCSH-siltaus: http://id.loc.gov/authorities/subjects/sh2020006001.
 
Olisiko suomeksi parempi Me too -liike? Kampanja kai on organisoidumpi kuin liike, Kielitoimiston sanakirjankin mukaan "määrätarkoitukseen tähtäävä tehokas (lyhytaikainen) toiminta, tempaus" (https://www.kielitoimistonsanakirja.fi/kampanja).

**Comment by AuHo22** [comment]
Ylellä on nähtävissä myös termiä Me too -liike 
https://yle.fi/a/74-20082342

Hashtagillinen ilmaisu sitten ilmeisesti ohjaustermiksi

**Comment by mirmaid** [comment]
Melindassa metoo, #metoo, Me Too movement, #MeToo-kampanja, kerran MeToo -liike.

**Comment by mariaforsen** [comment]
Myös SAOssa -liike: https://id.kb.se/term/sao/Me%20too-r%C3%B6relsen 

Sv. me too-rörelsen HT #metoo, metoo-rörelsen, me too-kampanjen...
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/me-too-r%C3%B6relsen

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa _me too -liike_.
