### ISSUE TITLE
ympäristöystävälliset tuotteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12593]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ympäristöystävälliset tuotteet](http://www.yso.fi/onto/yso/p12629)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

OT vihreät tuotteet, ympäristötuotteet
eng environmental goods

**Perustelut ehdotukselle**

Käytössä esim. tässä https://www.etla.fi/en/publications/reports/green-goods-in-finlands-manufacturing/

**Ehdottajan organisaatio**

KK/HR

**Comment by mariaforsen** [comment]
Sv. HT gröna produkter?
http://publications.europa.eu/resource/genpub/PUB_KH0216451SVN.1.1

**Comment by ilona-x** [comment]
Löytyi mahdollisesti tähän liittyvä vanha ehdotus:
**ympäristöhyödykkeet** https://github.com/Finto-ehdotus/YSE/issues/1943

---

TEPA https://termipankki.fi/tepa/fi/haku/environmental%20goods

IATE1
fi        ympäristöhyödykkeet (★★★☆);
ympäristöön liittyvät julkishyödykkeet (★★★☆)
sv       miljönyttigheter (★★★☆);
miljömässiga kollektiva nyttigheter (★★★☆)
en      environmental goods (★★★☆);
environmental public goods (★★★☆)

	  
Lähde: IATE 01.08.2023, Euroopan unioni (3518438)
	  
IATE3
fi        ympäristöhyödykkeet (★★★☆)
sv       miljöskonande produkter (★★☆☆);
miljövaror (★★★☆);
miljöanpassade produkter (★★☆☆)
en      environmental goods (★★★☆);
green goods (★★★☆)

	  
Lähde: IATE 01.08.2023, Euroopan unioni (1408569)

---

https://en.wikipedia.org/wiki/Environmental_good

**Comment by annamarj** [comment]
Katselin vielä "ympäristöhyödykkeet" -termin käyttöä. Se ei näytä liittyvän tähän ehdotukseen laisinkaan, koska ei viittaa kulutushyödykkeisiin / tuotteisiin.  Ympäristöhyödykkeinä mainittu esim. puhdas vesi sekä maalaismaisema. Engl. "environmental amenity." (https://netn.fi/artikkelit/juoksua-tyhjan-paalla-epavarmuudesta-ja-ilmastonmuutoksesta/ ja http://www.mtt.fi/mtts/pdf/mtts7.pdf). Tämä "ympäristöystävälliset tuotteet" / kulutushyödykkeet olisi minusta ihanteellista jopa korvata vielä vähän selkeämmällä ja neutraalimmalla termillä ja lisätä ohjaustermiksi sitten. En vielä kuitenkaan suoraan keksi ehdotusta. Lisätäkö sitten vaan nuo ehdotetut OTt?

**Comment by YSO-kokous** [comment]
Hyväksytään seuraavat ohjaustermit:
vihreät tuotteet
ympäristötuotteet (ympäristöystävälliset tuotteet)

Ympäristötuote-termillä on muitakin merkityksiä ja siksi sulkutarkenne nähtiin tässä hyvänä.
