### ISSUE TITLE
mainosmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12599]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mainosmusiikki](http://www.yso.fi/onto/yso/p6268)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT muzak?

**Perustelut ehdotukselle**

Muzakilla osin sama tarkoitus, lisätä ihmisten ostohalua.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by MUUSA-kokous** [comment]
Muzak ei ole YSOssa ensisijaisena terminä, vaan ainoastaan ohjausterminä taustamusiikille, joten sitä ei voi lisätä RT:ksi mainosmusiikille.

**Comment by YSO-kokous** [comment]
Ei lisätä RT suhdetta.
