### ISSUE TITLE
induktio (filosofia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12597]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[induktio (filosofia)](http://www.yso.fi/onto/yso/p5901)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeiksi induktiivinen päättely ja inductive reasoning, mahdollisesti muitakin.

**Perustelut ehdotukselle**

Selkeyttää käsitettä. Vrt. https://www.wikidata.org/wiki/Q484511

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mariaforsen** [comment]
Sv. HT induktiv slutledning
https://media.medfarm.uu.se/play/attachmentfile/video/2597/Forelasningsbilder.pdf

**Comment by mirmaid** [comment]
@LeKorsu
