### ISSUE TITLE
Honkajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12592]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Honkajoki](http://www.yso.fi/onto/yso/p110198)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Honkajoki liitetty Kankaanpäähän v. 2021 eli tälle ja Honkajoelle pitäisi lisätä huomautus ja lisäkäi Honkajoen alla oleva kylä siirtää Kankaanpään alle.

**Perustelut ehdotukselle**

https://www.kankaanpaa.fi/honkajoki-yhdistyy-kankaanpaahan-vuoden-vaihteessa/

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Huomautukset lisätty ja kylä siirretty Kankaanpään alle
