### ISSUE TITLE
fraktiointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12594]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fraktiointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

----

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.abo.fi/fi/uutiset/tohtorinvaitos-rakenteen-ja-ominaisuuksien-vastaavuudesta-liuottimella-fraktioidussa-ligniinissa-funktionaalisiin-materiaaleihin/

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [fraktiointi](http://finto.fi/yse/fi/page/Y512594)

**Comment by mirmaid** [comment]
Melindassa n. 30 kertaa agriforest-terminä, 15 kertaa vapaana avainsanana. Näkyy olevan käytössä useilla tieteenaloilla, onko sama?

**Comment by mariaforsen** [comment]
Voisiko ottaa jossain tarkemmassa muodossa? https://termipankki.fi/tepa/fi/haku/fraktionering
https://svenska.se/saol/?hv=xnr159785,xnr481339
NE: fraktionering: "fysikalisk metod att separera en blandning i beståndsdelar (fraktioner) eller att framställa rena substanser"

Sv. fraktionering (kemi)

**Comment by mirmaid** [comment]
Tarkemmin tutkittuna taitaa olla kuitenkin kaikki tuota kemiallista fraktiointia, ja myös Kielitoimiston sanakirja tuntee vain sen merkityksen. Sädehoidossa varmaan eri, mutta en tiedä tuleeko aineistoa jossa tarvetta niin tarkassa merkityksessä. 

MeSH: http://www.yso.fi/onto/mesh/D005591

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Pohditaan tarkennetta ruotsin vastineelle, kenties (kemi).
