### ISSUE TITLE
suonensisäinen hoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12601]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suonensisäinen hoito

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

endovascular therapy

**Tarkoitusta täsmentävä selite**

https://www.duodecimlehti.fi/duo91100

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa. Käytetty muutaman kerran vapaana asiasanana Melindassa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [hoitomenetelmät](http://www.yso.fi/onto/yso/p392)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 endovascular treatment

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018872814

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [suonensisäinen hoito](http://finto.fi/yse/fi/page/Y512601)

**Comment by mirmaid** [comment]
MeSHissä on _suonensisäiset toimenpiteet_, http://www.yso.fi/onto/mesh/D057510.

Lääketieteen termit:
**endovaskulaarinen hoito**
suonensisäinen hoito | verisuonen sairauden tai epämuodostuman hoito esim. tukkimalla (→embolisaatiolla), hyytymän liuotushoidolla (→trombolyyttisellä hoidolla), ahtauman laajennuksella, suonensisäisellä →stentillä tai täyttämällä valtimonpullistuma (aneurysma) lankavyyhdellä (→koililla)

**Comment by mirmaid** [comment]
Melindassa kaikkia kolmea muotoa käytetty n. 10 kertaa kutakin.

**Comment by mariaforsen** [comment]
Sv.  endovaskulära ingrepp HT endovaskulär behandling, endovaskulära tekniker
https://mesh.kib.ki.se/term/D057510/endovascular-procedures

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa suonensisäiset toimenpiteet. Muita muotoja ohjaustermeiksi.
