### ISSUE TITLE
linnanpäälliköt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12605]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

linnanpäälliköt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [johtajat](http://www.yso.fi/onto/yso/p23894)

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540), [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524)

**Vaihtoehtoiset termit**

 KT linnanherrat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Luokka:Suomen_linnanvoudit_ja_linnanp%C3%A4%C3%A4llik%C3%B6t)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-69004-4-5 Reconsidering Raseborg -> kokonainen luku linnanpäälliköistä: The castellans of Raseborg in 1373–1558 / Tapio Salminen 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [linnanpäälliköt](http://finto.fi/yse/fi/page/Y512605)

**Comment by mirmaid** [comment]
Sanastossa on _linnanvoudit_.

**Comment by mariaforsen** [comment]
Ehdotettu termi ei löydy sanakirjoista. Olisiko KÄ linnanvoudit ok?

**Comment by mirmaid** [comment]
Olisiko esim. Kristiinalla tähän kommenttia? Eri henkilöistä näytetään käyttävän eri titteleitä (tai samastakin henkilöstä) - linnanvouti, linnanpäällikkö, käskynhaltija - mutta mikä näiden suhde mahtaa olla toisiinsa?

**Comment by YSO-kokous** [comment]
Siirretään seuraavaan kokoukseen. Konsultoidaan SKS:ää tässä.

**Comment by krinay** [comment]
_Linnanpäällikkö_ ja _linnanherra_ (_slottshövitsman_, lat. capitaneus) ovat synonyymejä, kuten ehdotuksessakin esitetään.  Nimikkeen merkitys täsmentyi 1300-luvun lopulta lähtien merkitsemään linnan ja linnaläänin korkea-arvoisinta virkamiestä (aiemmin merkitys oli laveampi). _Kansallisbiografiassa_ on [58 linnanpäällikköä](https://kansallisbiografia.fi/kansallisbiografia?professions=linnanp%C3%A4%C3%A4llikk%C3%B6), pääosin 1400- ja 1500-luvuilta (varhaisimmat 1300-luvun lopulta, viimeiset 1600-luvulta). Ks. [capitaneus](https://fho.sls.fi/uppslagsord/15191/capitaneus/) / SLS. 

Vouti-terminologia on sekavaa. Historialliselta merkitykseltään _vouti_ kai on ylipäätään virkamies, mutta erilaisia tarkempia nimityksiä on käytetty hyvin vaihtelevasti eri aikoina ja eri paikoissa. Wikipediassa on lueteltu maa-, lohi-, jahti- ja siltavouti: https://fi.wikipedia.org/wiki/Vouti. 

YSOssa on tällä hetkellä 
voudit/fogdar
ST kruununvoudit/kronofogdar
ST linnanvoudit/slottsfogdar
kaikki ilman määrittelyjä.  

_Linnanvouti_ (_slottsfogde_, lat. advocatus) oli kai useimmiten linnanpäällikön alainen, jonka vastuulla oli käytännön hallinnollisia toimia. Mutta jotta asia olisi mahdollisimman epäselvä, käytetään linnanpäälliköistäkin tutkimuskirjallisuudessa joskus nimitystä linnanvouti. _Kansallisbiografiassa_ on [23 linnanvoutia](https://kansallisbiografia.fi/kansallisbiografia?professions=linnanvouti), pääosin 1400- ja 1500-luvuilta.  

_Kruununvouti_ (_kronofogde_) on myöhempi nimitys, se virallistettiin voutien ensimmäisessä ohjesäännössä 1688. Kruununvoudit olivat aluehallinnossa veronkanto- ja toimeenpanoviranomaisia. Virallisen nimityksen rinnalla käytettiin muitakin nimityksiä, mm. kihlakunnanvoutia. Kruununvouti-virat lakkautettiin vuoden 1944 lopussa. Ks. 
[https://portti.kansallisarkisto.fi/fi/aineisto-oppaat/kruununvoudit](https://portti.kansallisarkisto.fi/fi/aineisto-oppaat/kruununvoudit).  

Nykyään _linnanvouti_ on tasavallan presidentin kanslian talous- ja henkilöstöjohtajan virkanimike ja _kihlakunnanvouti_ (_häradsfogde_) ulosottoviranomaisen virkanimike (ulosottotarkastajien ja -ylitarkastajien esihenkilö) (Ahvenanmaalla maakunnanvouti).

**Comment by mariaforsen** [comment]
Löytyy myös https://fho.sls.fi/uppslagsord/11140/slottshovitsman/  "Under 1500–1600-talen benämning på slottsfogde. Slottshövitsmannen förvaltade slottet, skötte försvaret och verkade som domare i lägsta instans.
linnan käskyhaltija, linnavouti (1500- ja 1600-luvulla)"

**Comment by krinay** [comment]
Joo, hankalaa, että jossakin vaiheessa historiaa linnanvouti näyttää selvästi olleen linnanpäällikön/linnanherran alainen, mutta sitten taas jonakin toisena ajankohtana (tai jossakin toisessa kirjallisessa lähteessä) linnanvouti on ollut linnanpäällikkö.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon linnanpäälliköt.
Otetaan ohjaustermit:
linnanherrat, linnanvoudit (linnanpäälliköt) KÄYTÄ linnanpäälliköt

**Comment by mariaforsen** [comment]
Sv. slottsherrar HT slottshövitsmän
https://svenska.se/tre/?sok=slottsherre&pz=1
https://fho.sls.fi/search?q=slottsherre&svenskatiden=on&autonomatiden=on&sjalvstandighetstiden=on&year_from=&year_to=
/uppslagsverk/encyklopedi/lång/kastellan
