### ISSUE TITLE
glysyrritsiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12607]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[glysyrritsiini](http://www.yso.fi/onto/yso/p6501)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi lakritsihappo

**Perustelut ehdotukselle**

Tuli vastaan Wikidata-linkityksessä. Ks. https://www.wikidata.org/wiki/Q418705

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by ilona-x** [comment]
FinMeSH: 
**lakritsihappo** KT lakritsahappo
Muunkieliset termit
englanti **Glycyrrhizic** Acid KT Acid, Glycyrrhizinic / Glycyrrhizin / Glycyrrhizinic Acid
ruotsi **Lakritssyra**
https://finto.fi/mesh/fi/page/D019695

**Comment by ilona-x** [comment]
Huom. YSOssa yläkäsitteenä nyt **myrkylliset aineet**, pitäisikö mahdollisesti muuttaa? Vrt. FinMeSHin hierarkia: [orgaaniset kemikaalit](https://finto.fi/mesh/fi/page/D009930) > [hiilivedyt](https://finto.fi/mesh/fi/page/D006838) > [terpeenit](https://finto.fi/mesh/fi/page/D013729) > [triterpeenit](https://finto.fi/mesh/fi/page/D014315) > [pentasykliset triterpeenit](https://finto.fi/mesh/fi/page/D053978) > lakritsihappo

[triterpeenit ](https://finto.fi/yso/fi/page/p27486)näyttäisi löytyvän myös YSOsta

**Comment by mariaforsen** [comment]
Sv. HT lakritssyra, glycyrrhizinsyra
https://www.livsmedelsverket.se/livsmedel-och-innehall/oonskade-amnen/vaxtgifter/glycyrrhizinsyra
