### ISSUE TITLE
lihaskato

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12602]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lihaskato

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://ukkinstituutti.fi/liike-laakkeena/liikunta-ja-sairaudet/sarkopenia-ja-gerastenia/

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa. Käytetty muutaman kerran vapaana asiasanana Melindassa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [lihakset](http://www.yso.fi/onto/yso/p2784)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 sarkopenia

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018872814

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [lihaskato](http://finto.fi/yse/fi/page/Y512602)

**Comment by ilona-x** [comment]
Ehdotuksessa on 'vaihtoehtoiset termit' -kohdassa mainittu **sarkopenia**, mikä näyttää löytyvän YSOsta http://www.yso.fi/onto/yso/p39656, joten kävisikö tämä ehdotettu lihaskato mahdollisesti ohjaustermiksi sarkopenialle?

YSOssa sarkopenialla ei ole nyt yhtään ohjaustermiä, mutta FinMeSHistä löytyy seuraavat ohjaustermit:
sarkopenia http://www.yso.fi/onto/mesh/D055948
Ohjaustermit:
lihasten surkastuma
lihasten surkastuneisuus
vanhuuden lihassurkastuma

**Comment by mirmaid** [comment]
Lääketieteen termit:

sarkopenia: lihasten surkastuneisuus | vanhuudessa esiintyvä lihaskudoksen kato, useimmilla vanhuksilla lievä, joillakuilla huomattava

lihaskato: nälkiintymisen, sairauden tai liikkumattomuuden (immobilisaation) aiheuttama lihasten massan vähentyminen; vrt. myatrofia, myastenia

lihasatrofia: 1. lihasten surkastuminen, ks. lihaskato

MeSHissä on [lihasatrofia](http://www.yso.fi/onto/mesh/D009133), ST sarkopenia (ja lisäksi erikseen lihasatrofiat)

https://en.wikipedia.org/wiki/Muscle_atrophy

**Comment by mirmaid** [comment]
Aloituksen aineistoon sopii _sarkopenia_.

Pitäisikö lisätä ohjaustermeiksi esim. vanhuuden lihassurkastuma ja lihaskato (sarkopenia)?

**Comment by mariaforsen** [comment]
Kannatan ohjaustermiä. HT muskelförlust
"Sarkopenia eli lihaskato ja gerastenia eli hauraus-raihnausoireyhtymä ovat ikääntyneen terveyttä ja fyysistä toimintakykyä uhkaavia tiloja."

**Comment by FinMeSHienPaimentaja** [comment]
Maallikolle nuo ovat mielestäni aika samamerkityksisiä - sarkopeniassa kuitenkin etymologisesti painotus lienee enemmän lihaskadossa eli lihasmassan vähenemisessä, atrofia taas enemmän varsinaista surkastumista/surkastuneisuutta. MeSH:eissä tosiaan sarkopenia lihasatrofian alla. Lääketieteen termien näkemyksethän olikin jo yllä mainittu.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermeiksi vanhuuden lihassurkastuma ja lihaskato (sarkopenia).
