### ISSUE TITLE
maasota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12603]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maasota

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

land warfare

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Maasota tarvitaan terminä jos YSOssa olevien ilmasota ja merisota -termien rinnalle.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sodankäynti](http://www.yso.fi/onto/yso/p4130)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

 maasodankäynti

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SOTO](https://finto.fi/soto/fi/page/p798), [Wikipedia](https://en.wikipedia.org/wiki/Land_warfare)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/188039?show=full

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [maasota](http://finto.fi/yse/fi/page/Y512603)

**Comment by mirmaid** [comment]
Runsaasti Melindassa.

**Comment by mariaforsen** [comment]
Sv. markkrig
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_70857d46ede758ef185bc9243c7d71c6&list_id=1&keyword=maasota&word=maasota
https://svenska.se/tre/?sok=markkrig&pz=8

**Comment by YSO-kokous** [comment]
Hyväksytään käsite.
