### ISSUE TITLE
rikosten ehkäisy

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12609]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rikosten ehkäisy

**Ehdotettu termi ruotsiksi**

brottsprevention/brottsförebyggande

**Ehdotettu termi englanniksi**

crime prevention

**Tarkoitusta täsmentävä selite**

https://rikoksentorjunta.fi/rikosten-ehkaisy

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [ehkäisy](http://www.yso.fi/onto/yso/p793)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [rikoksentorjunta](http://www.yso.fi/onto/yso/p19910)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Crime_prevention), [LCSH](https://id.loc.gov/authorities/subjects/sh85034011.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Nordic criminal justice in a global context : practices and promotion of exceptionalism

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [rikosten ehkäisy](http://finto.fi/yse/fi/page/Y512609)

**Comment by mirmaid** [comment]
Ohjaustermiksi käsitteelle _rikoksentorjunta_?

**Comment by mariaforsen** [comment]
Tässä on ainakin ruotsiksi merkitysero: prevention/förebyggande vs. bekämpning: ensimmäinen ennaltaehkäisee, toinen myös "taistelee" olemassa olevaa rikollisuutta vastaan.

**Comment by mirmaid** [comment]
_Rikoksentorjunta_ on ainakin linkattu ehdotuksessa mainittuun LCSH-käsitteeseen. On tuo Marian mainitsema ero suomeksikin, mutta käytännössä kyllä todella hiuksenhieno, veikkaan että menisivät kuvailussa sekaisin.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi:
rikosten ehkäisy KÄYTÄ rikoksentorjunta

**Comment by mariaforsen** [comment]
Sv. brottsbekämpning ok?
