### ISSUE TITLE
paikallispuolustus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12600]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

paikallispuolustus

**Ehdotettu termi ruotsiksi**

Lokalförsvaret (puolustusselonteko 2021 käännös)

**Ehdotettu termi englanniksi**

Local defence (puolustusselonteko 2021 käännös)

**Tarkoitusta täsmentävä selite**

https://maavoimat.fi/-/paikallispuolustus-
https://julkaisut.valtioneuvosto.fi/handle/10024/163405

**Perustelut ehdotukselle**

Konseptista on kirjoitettu paljon vuosikymmenien saatossa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [puolustusvoimat](http://www.yso.fi/onto/yso/p7457)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/79703
https://finna.fi/Record/arto.019008564
https://finna.fi/Record/arto.019043698
https://finna.fi/Record/arto.018818763

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [paikallispuolustus](http://finto.fi/yse/fi/page/Y512600)

**Comment by mirmaid** [comment]
Melindassa 8 x soto-terminä, 13 kertaa vapaana avainsanana.

**Comment by mariaforsen** [comment]
Sv. lokalförsvar HT lokalt försvar
https://svenska.se/tre/?sok=lokalf%C3%B6rsvar&pz=1

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
