### ISSUE TITLE
Tammisaaren saaristo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12606]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Tammisaaren saaristo

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Otetaanko? https://fi.wikipedia.org/wiki/Tammisaaren_saaristo

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ekenäs skärgård: historia och historier

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Tammisaaren saaristo](http://finto.fi/yse/fi/page/Y512606)

**Comment by mirmaid** [comment]
Hyväksytään. Lisätään saaristoille yläkäsite.

Linjaus: Kotimaisten saaristojen yläkäsite on kunta tai yksi tai useampi maakunta, ulkomaisten valtio. (Korjataan myös teiden osalta.)

**Comment by ilona-x** [comment]
Turun saaristo #12625 
 Merenkurkun saaristo #12626
