### ISSUE TITLE
kelttalaš gielat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12613]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kelttalaš gielat](http://www.yso.fi/onto/yso/p18155)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

manksgiella váilu

**Perustelut ehdotukselle**

Idea on kai näyttää koko kieliperhe

**Ehdottajan organisaatio**

UiT
**Termiehdotus Fintossa:** [kelttalaš gielat](http://finto.fi/yse/fi/page/Y512613)

**Comment by mirmaid** [comment]
Puuttuu siis manksin kieli, https://fi.wikipedia.org/wiki/Manksin_kieli.

**Comment by mariaforsen** [comment]
Sv. manx (språk)
https://id.kb.se/find?q=manx
