### ISSUE TITLE
iMode

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12618]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[iMode](http://www.yso.fi/onto/yso/p6626)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ilmeisesti oikea kirjoitusasu on i-mode.

**Perustelut ehdotukselle**

Ks. https://www.wikidata.org/wiki/Q284305

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by tpalonen** [comment]
Ehkä määritelmääkin voisi vähän korjata? Tuollaiset "on käytössä"-tyyppiset preesensmuodot IT-alan termistön määritelmissä eivät  pidä ikuisesti paikkaansa. _"iMode on WAPin kaltaiseen käyttötarkoitukseen kehitetty järjestelmä, joka WAPista poiketen on käytössä ainoastaan yhden suuren japanilaisen puhelinoperaattorin, NTT DoCoMon verkossa."_

**Comment by mariaforsen** [comment]
https://www.rikstermbanken.se/search?q=i-mode&s=termer
https://it-ord.idg.se/ord/i-mode/
