### ISSUE TITLE
identification (cognition )

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12619]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[identification (cognition )](http://www.yso.fi/onto/yso/p2484)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selkeämpi termi identification (psychology)?

**Perustelut ehdotukselle**

Myös toinen identification voidaan tulkita kognitioksi. Ryhmänä on psykologia. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ruotsiksikin on nimenomaan psykologi tarkenteena.

**Comment by tpalonen** [comment]
Muutettu ehdotetusti
