### ISSUE TITLE
korrespondenssioppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12617]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[korrespondenssioppi](http://www.yso.fi/onto/yso/p6569)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeiksi totuuden vastaavuusteoria, totuuden korrespondenssiteoria ja korrespondenssiteoria

**Perustelut ehdotukselle**

Ks. https://fi.wikipedia.org/wiki/Totuuden_vastaavuusteoria
https://tieteentermipankki.fi/wiki/Filosofia:korrespondenssiteoria
https://tieteentermipankki.fi/wiki/Filosofia:totuuden_korrespondenssiteoria
https://filosofia.fi/fi/ensyklopedia/totuusteoriat

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by AuHo22** [comment]
https://filosofia.fi/fi/ensyklopedia/totuusteoriat

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotetut termit tälle käsitteelle, mutta YSO-ylläpito tutkii, pitäisikö käsitteen käytettävä termi vaihtaa. Tutkitaan referenssinä vielä Filosofian sanakirjaa. YSO-ylläpito päättää itsenäisesti mahdollisen käytettävän termin muutoksen.

**Comment by mariaforsen** [comment]
Sv. korrespondenslära > korrespondensteorin för sanning
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/korrespondensteorin-f%C3%B6r-sanning
https://id.kb.se/term/sao/Korrespondensteorin%20f%C3%B6r%20sanning
Eri asia: https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/korrespondensl%C3%A4ra
