### ISSUE TITLE
indoiránalaš gielat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12612]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[indoiránalaš gielat](http://www.yso.fi/onto/yso/p3257)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

indoiránlaš?

**Perustelut ehdotukselle**

Mu mielas indoiránalaš.  fintos lea dál iranlaš (=Giellagáldu 30.8.2016) muhto indoiránAlaš. Gal ferte leat seammá málle (A dahje A haga).

**Ehdottajan organisaatio**

UiT

**Comment by mariguttorm** [comment]
Hyväksytään ehdotus.
