### ISSUE TITLE
kroatiagiella

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12615]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kroatiagiella](http://www.yso.fi/onto/yso/p10394)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

kroátiagiella

**Perustelut ehdotukselle**

kroátiagiella 700, kroatiagiella 17 googlessa (toki Wikipedia suuri osa 700:sta)

**Ehdottajan organisaatio**

UiT

**Comment by mariguttorm** [comment]
Hyväksytään ehdotus
