### ISSUE TITLE
Svenskfinland

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12610]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Svenskfinland](http://www.yso.fi/onto/yso/p108720)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tällä voisi varmaan olla RT-suhde termiin Ruotsinkielinen Pohjanmaa?

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Svenskfinland
https://sv.wikipedia.org/wiki/Svenskspr%C3%A5kiga_%C3%96sterbotten

**Ehdottajan organisaatio**

kk/il

**Comment by jtuohini** [comment]
Eikö enemmin LT–ST-suhde? Ruotsinkielinen Pohjanmaa on osa edellistä, ei sille rinnakkainen.

**Comment by ilona-x** [comment]
> Eikö enemmin LT–ST-suhde? Ruotsinkielinen Pohjanmaa on osa edellistä, ei sille rinnakkainen.

Joo, mietin LT-ST-suhdettakin, mutta jäi sitten kirjaamatta tuohon ehdotukseen.

**Comment by mirmaid** [comment]
Lisätään hierarkia + Svenskfinland YK Suomi
