### ISSUE TITLE
folkdansare

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12611]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kansantanssija

**Ehdotettu termi ruotsiksi**

folkdansare

**Ehdotettu termi englanniksi**

folk dancer

**Tarkoitusta täsmentävä selite**

utövare av folkdans, personer som dansar folkdans

**Perustelut ehdotukselle**

Behövs som ämnesord till bilder där man ser människor som dansar folkdans (utövare av folkdans). För tillfället finns i ontologin termen folkdanser, men på bilden syns inte folkdansen utan endast utövarna i ett specifikt ögonblick under dansens förlopp.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [95 Teater. Dans](http://www.yso.fi/onto/yso/p26582), [98 Fritid. Hobbyer. Turism. Handarbeten](http://www.yso.fi/onto/yso/p26527), [50 Folktradition. Traditionsforskning. Kulturantropologi. Ockultism](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

I SLS arkivs samlingar finns filmer och fotografier från folkdansrörelsen. Endast ett fåtal finns ännu på sls.finna.fi. Mer fotografier av folkdansare och eventuellt också videofilmer kommer framöver att publiceras på sls.finna.fi.

**Ehdottajan organisaatio**

Svenska litteratursällskapet i Finland r.f.
**Termiehdotus Fintossa:** [folkdansare](http://finto.fi/yse/fi/page/Y512611)

**Comment by mirmaid** [comment]
Sanastossa on toistaiseksi ainoastaan _tanssijat_, jopa balettitanssijat on ohjaustermi sille.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon kansantanssijat. (Tutkittaneen: tälle kenties ohjaustermi tanhuajat?)
Otetaan myös uutena käsitteenä balettitanssijat.

Tarkistetaan tanssijat-käsitteen hierarkia. Nykyinen yläkäsite on näyttämötaiteilijat, mutta ovatko kansantanssijat näyttämötaiteilijoita?

**Comment by mariaforsen** [comment]
Sv.
-folkdansare
-balettdansare HT balettdansöser, balettdansörer
https://id.kb.se/term/sao/Balettdansare

**Comment by jtuohini** [comment]
Nykypäivän kansantanssijoita voi pitää näyttämötaiteilijoina, koska tanssinsa, varsinkin erillisillä kursseilla ja tanssiryhmissä opeteltuna, on usein nimenomaan esittämistä varten eikä toimi osana elävää paikallisyhteisöllistä rituaalia ja viihdykettä samalla tavoin kuin aiemmin (tanssi häissä, nurkkatanssit ym.). Entistaikaanhan lähes kaikki kyläyhteisön jäsenet tanssivat (kansan)tansseja olematta erillisiä "kansantanssijoita".

Toki jos ajatellaan asiasanan käyttöä kuvailussa, nousee kysymys esimerkiksi valokuvien osalta, missä tilanteessa sopii laittaa _kansantanssijat_ 1900-luvun vaihteen tanssijoita esittävään kuvaan ja missä tilanteessa pelkkä _tanssijat_: pitääkö tunnistaa, mistä tanssista on kyse ja nimenomaan sen rahvaanomaisesta muodosta (poloneesi, polska, hovimenuetti ~ kansanmenuetti, erilaiset kontratanssit, valssi, polkka) vai riittääkö, että kuvan tanssija vaikuttaa muulta kuin ylempien sosiaaliluokkien edustajalta (vaikka nämä tanssisivatkin jotakin kansantanssia)?
