### ISSUE TITLE
portugalgiella

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12614]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[portugalgiella](http://www.yso.fi/onto/yso/p19823)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

portugálagiella

**Perustelut ehdotukselle**

portugálagiella -- google 3400 , portugalgiella 5, portugalagiella 7. giellagáldu ii leat dadjan maidege (?).

**Ehdottajan organisaatio**

UiT

**Comment by mariguttorm** [comment]
Hyväksytään ehdotus.
