### ISSUE TITLE
torjunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12616]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[torjunta](http://www.yso.fi/onto/yso/p792)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Virheellinen wikidata-linkitys

**Perustelut ehdotukselle**

YSOn käsite ei viittaa psykologiaan ollenkaan. 

**Ehdottajan organisaatio**

**Comment by nikopartanen** [comment]
Wikidatassa deprekoitu ja YSOsta linkki poistettu. Voidaan sulkea.
