### ISSUE TITLE
hoidonohjaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1261]
#### Ehdotettu termi suomeksi

hoidonohjaus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 20.12.2004

**Muokkauspäivämäärä:** 27.5.2005, 20.12.2004, 16.12.2008, 23.03.2009

**Voyager-id:** 135008

**Termiehdotus Fintossa:** [hoidonohjaus](http://finto.fi/yse/fi/page/Y335008)

**Comment by jarmosaarikko** [comment]
ISSUE näkyy olevan edelleen auki?  YSAssa on hoitoonohjaus, mutta tämä lienee hieman eri asia? Vastaava tästä käsitteestä käytetty termi olisi potilaanohjaus.    Tästä on nyt käytetty pelkkää **ohjaus** termiä Melindassa, mutta tässä merkityksessä on Melindassa runsaasti julkaisuja, joten voisi olla hyödyllistä erottaa omaksi käsitteekseen. Sekaannuksten välttämiseksi ehdotan termiä:
**potilaanohjaus** KT hoidonohjaus  YK ohjaus (neuvonta ja opastus)  RT hoitoonohjaus

**Comment by mirmaid** [comment]
YSAssa on _potilasneuvonta_ http://finto.fi/ysa/fi/page/Y98222

**Comment by jarmosaarikko** [comment]
ahaa, en ollut huomannut tuota... FInton ja devin ysa on juuri nyt rikki, en voi tarkistaa nyt (0 käsitettä!). Tuo pätee aivan hyvin tähän. Ehkä tämän voi lisätä sitten tuonne potilasneuvonnan ohjaustermiksi. pitänee ottaa tämä huomioon Melindan ohjaus-termien korjailuissa.

**Comment by YSA-kokous** [comment]
KÄ potilasneuvonta
