### ISSUE TITLE
Halikonjokilaakso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12627]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Halikonjokilaakso](http://www.yso.fi/onto/yso/p119945)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yläkäsite Varsinais-Suomi?

**Perustelut ehdotukselle**

yläkäsite puuttuu

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Tämän ja muiden jokilaaksojen yläkäsitteeksi maakunta/maakunnat?

**Comment by ilona-x** [comment]
Huom. YSOssa ulkomaisten jokilaaksojen yläkäsite on sijaintivaltio:
[Loiren laakso](http://www.yso.fi/onto/yso/p204337) YK Ranska
[Douron laakso](http://www.yso.fi/onto/yso/p211870) YK Portugali
