### ISSUE TITLE
aleneminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12621]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aleneminen](http://www.yso.fi/onto/yso/p25507)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkistetaan merkitys ja muunkieliset vastineet, vai onko poisto mahdollinen?

**Perustelut ehdotukselle**

Melindassa sekalaista, 17 tietuetta
https://www.kielitoimistonsanakirja.fi/#/aleta
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_96e91c71e307655f8c3f4dab9fae7af4&list_id=1&keyword=aleta&word=aleta
Vrt. https://svenska.se/tre/?sok=nedg%C3%A5ng&pz=1 
Eli samaa merkityskenttää lienee mahdotonta saada ilman tarkennusta. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Mielestäni voisi poistaa, ja ehkä ohjata aleneminen (heikentyminen) KÄ heikentyminen, aleneminen (väheneminen) KÄ väheneminen.

**Comment by YSO-kokous** [comment]
Hyväksytään käsitteen poisto. Lisätään seuraavat ohjaustermit:
aleneminen (heikentyminen) KÄYTÄ heikentyminen
aleneminen (väheneminen) KÄYTÄ väheneminen
