### ISSUE TITLE
igbot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12624]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

igbot

**Ehdotettu termi ruotsiksi**

Igbo (folk)

**Ehdotettu termi englanniksi**

Igbo people

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu
Melinda x 9

**Ehdotettu yläkäsite YSOssa (LT)**

 [afrikkalaiset](http://www.yso.fi/onto/yso/p1680), [nigerialaiset](http://www.yso.fi/onto/yso/p39628)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH: Igbo (African people)](http://id.loc.gov/authorities/subjects/sh85064199), [Wikidata](http://www.wikidata.org/entity/Q244157), [SAO:  Igbo (folk) ](https://id.kb.se/term/sao/Igbo%20%28folk%29)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Predictors of Igbo adolescents' well-being and behavioral problems in Southeastern Nigeria  https://urn.fi/URN:ISBN:978-952-12-4312-7

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [igbot](http://finto.fi/yse/fi/page/Y512624)

**Comment by mariaforsen** [comment]
Sv. igbo (folk) HT ibo (folk)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Esiintyy myös muodossa ibot, joka lisättäneen ohjaustermiksi. Ks. https://fi.wikipedia.org/wiki/Igbot
