### ISSUE TITLE
palveluskelpoisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12623]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

palveluskelpoisuus

**Ehdotettu termi ruotsiksi**

duglighet till militärtjänst

**Ehdotettu termi englanniksi**

fitness for military service

**Tarkoitusta täsmentävä selite**

" Asevelvollisen palveluskelpoisuudella tarkoitetaan sitä, että asevelvollinen suoriutuu asevelvollisuuslaissa tarkoitetusta palveluksesta eikä vaaranna omaa tai muiden palvelusturvallisuutta." https://puolustusvoimat.fi/documents/1948673/2015558/Terveystarkastusohje/95c74723-da6f-47f8-b1cf-964fc3affb73/Terveystarkastusohje.pdf%22

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [kelpoisuus](http://www.yso.fi/onto/yso/p3599)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Soto](http://www.yso.fi/onto/soto/p31)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.018922451?sid=4155251963
https://puolustusvoimat.fi/-/1950813/syksyn-2023-kutsunnat-alkavat

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu, kirjasto
**Termiehdotus Fintossa:** [palveluskelpoisuus](http://finto.fi/yse/fi/page/Y512623)

**Comment by mirmaid** [comment]
13 kertaa Melindassa sosto-terminä, 16 kertaa vapaana avainsanana.

**Comment by mariaforsen** [comment]
Mistä mahtaa tulla ehdotettu ruotsinkielinen termi?

Sv. tjänsteduglighet HT tjänstduglighet, duglighet till militärtjänst
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9091d2cc2d9baea73811ed7b24463a9d&list_id=1&keyword=palveluskelpoisuus&word=palveluskelpoisuus
https://www.finlex.fi/sv/laki/ajantasa/2007/20071438
https://www.uppslagsverket.fi/sv/view-170045-Reserven
https://www.siviilipalveluskeskus.fi/sv/fore-tjanstgoringen/att-ansoka-om-civiltjanst/
https://www.laakariliitto.fi/lakaretik/lakare-patient-och-tredje-part/lakare-krig-och-forsvarsmakten/

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
