### ISSUE TITLE
Paimionjokilaakso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12634]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Paimionjokilaakso](http://www.yso.fi/onto/yso/p169022)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yläkäsitteeksi Varsinais-Suomi tai Paimio?

**Perustelut ehdotukselle**

yläkäsite puuttuu

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Paimionjokilaakso: Paimionjokilaakso on 156 hehtaarin SCI Natura 2000 -alue.

Mutta tulkittaisiinko me kuitenkin niin, että jokilaakso on koko joen alueella? (Muut jokilaaksot samoin)

**Comment by mirmaid** [comment]
Sama yläkäsite jokilaaksoille ja joille.
