### ISSUE TITLE
hyvinvointikertomukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1263]
#### Ehdotettu termi suomeksi

hyvinvointikertomukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/ysa/ryhma_71)
#### Käsitteen määritelmä

Sosiaali- ja terveysministeriö on antanut Stakesin tehtäväksi yhdessä kuntien kanssa valmistella kunnan terveyskertomuksen mallia. Varsin pian aloimme puhua hyvinvointikertomuksesta ajatellen, että terveyskäsitteen laajentamisen sijasta voisimme yhtä hyvin ottaa alusta lähtien yläkäsitteeksi hyvinvoinnin. Hyvinvointikertomus kertoo luottamushenkilöille "mahdollisimman tarkasti sen hetken, mikä kunnassa on juuri ja nyt eli mikä on paikallinen todellisuus". Näin hyvinvointikertomus katsoo nykyhetkeen ja myös siihen polkuun, jota nykyhetkeen on tultu. Sen on kuvattava nimenomaan paikallista todellisuutta eli kyseisen kunnan hyvinvointitilannetta jne. (Googlesta löytynyttä tietoa)

**Luontipäivämäärä:** 20.12.2004

**Muokkauspäivämäärä:** 20.12.2004, 16.12.2008, 21.04.2015

**Voyager-id:** 135010

**Termiehdotus Fintossa:** [hyvinvointikertomukset](http://finto.fi/yse/fi/page/Y335010)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
