### ISSUE TITLE
karrageenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12649]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

karrageenit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

carrageenans 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [polysakkaridit](http://www.yso.fi/onto/yso/p23997)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 carrageenins

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Karrageeni), [FinMeSH: karrageeni](http://www.yso.fi/onto/mesh/D002351)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Utilizing κ-carrageenan hydrogels in teaching, outreach and chemical gardens https://urn.fi/URN:ISBN:978-952-12-4302-8

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. karragenan HT karragenaner, karragen 
https://www.rikstermbanken.se/search?q=karragen&s=termer
https://www.sanakirja.fi/custom/all/karragen
https://www.livsmedelsverket.se/livsmedel-och-innehall/tillsatser-e-nummer/sok-e-nummer/e-407---karragenan 
https://sv.wikipedia.org/wiki/Karragenan
https://mesh.kib.ki.se/term/D002351/carrageenan
