### ISSUE TITLE
Löytäneenoja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12647]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Löytäneenoja](http://www.yso.fi/onto/yso/p139900)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Löytyisiköhän tälle yläkäsite? Huomautuksen mukaan sijaitsee Varsinais-Suomessa, mutta muualla myös mainintoja Satakunnasta ja Lounais-Suomesta. Ei löydy Maanmittauslaitoksen palveluista

**Perustelut ehdotukselle**

yläkäsite puuttuu

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Veikkaan, että on jossain näillä seutuvilla http://paikkatiedot.fi/so/1000772/10005418. Aineistossa myös summittainen kartta https://helda.helsinki.fi/server/api/core/bitstreams/a46bb323-03e8-4b9a-a29f-c00071d79ee2/content. Eli olisi YK Satakunta? Mistäköhän huomautuksen tieto on peräisin...

**Comment by mirmaid** [comment]
YK Satakunta.
