### ISSUE TITLE
Vuoksenlaakso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12642]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vuoksenlaakso](http://www.yso.fi/onto/yso/p108242)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään yläkäsite? Etelä-Karjala, Karjalankannas, Suomi, Venäjä?

**Perustelut ehdotukselle**

yläkäsite puuttuu

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Tämän jokilaakson yläkäsite, kun sijaitsee rajaseudulla? 
https://urn.fi/URN:ISBN:9789526200484

**Comment by mirmaid** [comment]
YK Etelä-Karjala, Venäjä.
