### ISSUE TITLE
Rovajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12648]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Rovajärvi](http://www.yso.fi/onto/yso/p112246)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yläkäsite puuttuu ja huomatusta pitäisi päivittää, kun siinä mainitaan Rovaniemen maalaiskunta. Pitäisikö myös termimuotoa miettiä, kun Wikipediassa näyttää olevan muodossa Rovajärven ampuma-alue?

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Rovaj%C3%A4rven_ampuma-alue

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Rovajärvi (harjoitusalue), YK Rovaniemi, Kemijärvi, Pelkosenniemi, Sodankylä.
