### ISSUE TITLE
Kymijoen kanava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12643]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kymijoen kanava](http://www.yso.fi/onto/yso/p110529)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan? 

**Perustelut ehdotukselle**

Kanavaa on suunniteltu, mutta ei toteutettu. Aiemmin käsitelty vastaavaa tapausta Mäntyharjun kanava, joka päätettiin poistaa YSO-paikoista https://github.com/Finto-ehdotus/YSE/issues/11474

https://fi.wikipedia.org/wiki/Kymijoen_kanava

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Huom. tämän lisäksi myös [Rikalan kanava ](http://www.yso.fi/onto/yso/p214106)vastaava tapaus https://fi.wikipedia.org/wiki/Rikalan_kanava

**Comment by mirmaid** [comment]
Kymijoen kanava YSOon kuten Vuotos, Rikalan kanavalle YK Lempäälä.

Linjaus: Toteutumattomat rakennushankkeet auktorisoidaan YSOon käsitteen rakennushankkeet alle tyypistä riippumatta.
