### ISSUE TITLE
wolfdog

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12657]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[wolfdog](http://www.yso.fi/onto/yso/p21863)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

wolfdog (hybrid)?

**Perustelut ehdotukselle**

Kaksimerkityksinen termi, ks. https://www.merriam-webster.com/dictionary/wolf%20dog

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. on ollut varghundar, joka viittaa koiranrotuihin, ei susihybrideihin. Eli jos/kun tämä viittaa koiran ja suden risteymiin niin sv-termi pitää muuttaa > hundvarg (finl.), varghybrid.

https://fi.wikipedia.org/wiki/Koirasusi
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_3cd8c25b4ae699f7644ce5e5ef7cc538&list_id=1&keyword=koirasusi&word=koirasusi
https://vieraslajit.fi/lajit/MX.5014936
https://laji.fi/taxon/MX.5014936/taxonomy?showTree=true

**Comment by tpalonen** [comment]
Muutettu ehdotetusti
