### ISSUE TITLE
religiöst språk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12653]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[religiöst språk](http://www.yso.fi/onto/yso/p21766)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi liturginen kieli

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Liturginen_kieli

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. ohjausterminä on jo liturgiskt språk.

**Comment by mirmaid** [comment]
Wikipediassa myös kirkkokieli, pyhä kieli, kirkollinen kieli ja hengellinen kieli. Kaksi jälkimmäistä voisi myös olla käyttökelpoisia ohjaustermejä?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermeiksi kirkollinen kieli, liturginen kieli ja hengellinen kieli
