### ISSUE TITLE
kalsipotrioli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12652]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kalsipotrioli

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

calcipotriol

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

Melinda x 4

**Ehdotettu yläkäsite YSOssa (LT)**

 [lääkeaineet](http://www.yso.fi/onto/yso/p1707)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Calcipotriol)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Vitamin D analogue calcipotriol in the local treatment of arthritis : observations from preclinical studies https://urn.fi/URN:ISBN:9789526237961

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [kalsipotrioli](http://finto.fi/yse/fi/page/Y512652)

**Comment by mariaforsen** [comment]
Sv. kalcipotriol
(https://docetp.mpa.se/LMF/Calcipotriol_Betamethasone%20Orifarm%2C%20gel%20PL_09001bee81bb25f9.pdf)
https://www.fass.se/LIF/substance;jsessionid=node01q93tohanaliv177ygr8gyr85m35932.node0?userType=2&substanceId=IDE4POGTUB5YNVERT1
https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/nationella-riktlinjer/2019-3-11-kunskapsbilaga-nr-psoriasis.pdf
