### ISSUE TITLE
vuokratyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12650]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vuokratyö](http://www.yso.fi/onto/yso/p16301)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko OT vuokratyövoima ok suomeksi?

**Perustelut ehdotukselle**

Vastaa sv. hyrd arbetskraft (muutetaan termiä ruotsiksi, jos ei ok)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Mun mielestäni alkaa jo olla liian kaukana toisistaan 🤔

**Comment by ilona-x** [comment]
TSR: vuokratyöntekijät http://www.yso.fi/onto/tsr/p12984
JUPO: vuokratyövoima http://www.yso.fi/onto/jupo/p4506

**Comment by YSO-kokous** [comment]
Otetaan sanastoon uutena käsitteenä vuokratyöntekijät. Tälle ohjaustermiksi vuokratyövoima.

Tarkistetaan vuokratyö-käsitteen ruotsinkielinen käytettävä termi. Ruotsin ja suomen kielen käytettävissä termeissä on tässä käsitteessä ollut eri painotus.

**Comment by mariaforsen** [comment]
Sv.
-fi. vuokratyö =hyrd arbetskraft > hyrt arbete
-fi. vuokratyöntekijät =hyrda arbetstagare HT hyrd arbetskraft (eg. fi. työvoima), hyrda arbetare, hyrarbetare

-se hierarkin
-https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1dfc9f076e3c153f80d1c6dfb54b0656&list_id=1&keyword=vuokraty%C3%B6&word=vuokraty%C3%B6
-https://www.suomi.fi/medborgare/arbetsliv-och-arbetsloshet/regel-for-arbetslivet/guide/olika-saett-att-arbeta/hyrt-arbete
-https://tem.fi/documents/1410877/3229884/Guide+om+hyrt+arbete/84113ead-c68a-45e5-92ab-46c7ddaab14c
-https://tyosuojelu.fi/sv/anstallningsforhallande/hyrt-arbete
-se dock https://toimistot.te-palvelut.fi/documents/244949/12920089/iJOBB.pdf/0ef2d91e-7277-40ea-879c-6f7d85b19139
-https://www.stat.fi/meta/kas/vuokratyo_sv.html
-https://www.suomi.fi/medborgare/arbetsliv-och-arbetsloshet/regel-for-arbetslivet/guide/olika-saett-att-arbeta/hyrt-arbete
-https://www.finlex.fi/sv/laki/ajantasa/2002/20020738
-https://termipankki.fi/tepa/fi/haku/vuokraty%C3%B6ntekij%C3%A4
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_2be5a4445a1ed35671c3f280f79294e7&list_id=1&keyword=vuokraty%C3%B6ntekij%C3%A4&word=vuokraty%C3%B6ntekij%C3%A4
https://termipankki.fi/tepa/fi/haku/ty%C3%B6ntekij%C3%A4
https://tyoelamaan.fi/sv/arbetslivet/olika-satt-att-arbeta/
