### ISSUE TITLE
järjestelmäarkkitehtuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12656]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[järjestelmäarkkitehtuuri](http://www.yso.fi/onto/yso/p20656)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä kuuluisi myös arkkitehtuurin alle.

**Perustelut ehdotukselle**

Julkaisussa Myyrinpuhos ISBN 978-952-7520-30-7 on luku 'Järjestelmäarkkitehtuuri', jonka alla
"Järjestelmäajattelusta suomalaisessa arkkitehtuurissa
1960-luvulla on kirjoittanut Timo Koho kirjassaan
Suomalaisen arkkitehtuurin 60-luku – konstruktivismi ja
järjestelmäajattelu43. Järjestelmäajattelulla tarkoitettiin
arkkitehtuurijärjestelmiä, jotka huomioivat uudet
rakennustekniikan mahdollisuudet. Paitsi teknologian
tarjoamista mahdollisuuksista, 1960-luvulla oltiin
kiinnostuneita myös tieteidenvälisen tutkimuksen
tuottamasta tiedosta ja uudenlaisen arkkitehtuurin
luomisesta44. Uusi arkkitehtuuri olisi arkkitehti Kirmo
Mikkolan mukaan45 anonyymiä, esteettisesti kontrolloitua,
käyttäjäkeskeistä ja loogis-matemaattista, teknologisesti
korostunutta systeemi- tai järjestelmäarkkitehtuuria.
Arkkitehti Juhani Pallasmaa korosti vuonna 1967, että
erillisten kohteiden sijasta arkkitehtuurissa keskityttäisiin
järjestelmien ja struktuurien suunnitteluun46. Arkkitehtilehdessä
julkaistiin vuonna 1970 suunnittelun
järjestelmällisyyteen keskittynyt teemanumero47

**Ehdottajan organisaatio**

KK/HR

**Comment by mirmaid** [comment]
Käytössä on varmaan ollut lähinnä merkityksessä "tietojärjestelmäarkkitehtuuri", mutta sanastossa on myös erikseen _tietotekniikka-arkkitehtuuri_...
