### ISSUE TITLE
kiinan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12666]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kiinan kieli](http://www.yso.fi/onto/yso/p17318)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan lisättäväksi ainakin alakäsitteet mandariinikiina ja kantoninkiina. Ehkä myös ainakin  Min-kiina ja Hakka voisivat olla erikseen. 

**Perustelut ehdotukselle**

Kiinan eri "murteet" ovat oikeastaan eri kieliä, ja varsinkin kantoninkiinasta on olemassa kirjastoissa varmasti ihan oppikirjoja, kielioppikirjoja ja sanakirjoja. Suomalaiset kiinanopiskelijat menevät usein vaihtoon Taiwaniin, joten Min-kiinakin varmasti kiinnostaa opiskelijoita

**Ehdottajan organisaatio**

Turun yliopiston kirjasto

**Comment by mariaforsen** [comment]
SAOssa kiinan alakäsitteitä:
[Dunganska språket • sao](https://id.kb.se/term/sao/Dunganska%20spr%C3%A5ket)
[Hakka (språk) • sao](https://id.kb.se/term/sao/Hakka%20(spr%C3%A5k))
[Kantonesiska • sao](https://id.kb.se/term/sao/Kantonesiska)
[Min (språk) • sao](https://id.kb.se/term/sao/Min%20(spr%C3%A5k))
Mandarin KÄ kinesiska språket https://id.kb.se/term/sao/Kinesiska%20spr%C3%A5ket

**Comment by YSO-kokous** [comment]
Konsultoidaan Kotusta (ja Kielten nimien projektia) ja tehdään päätös sen pohjalta.
