### ISSUE TITLE
siirtovaikutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12668]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[siirtovaikutus](http://www.yso.fi/onto/yso/p16213)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne? 

**Perustelut ehdotukselle**

Käytetty myös kielitieteessä. vrt. transferenssi

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. on transfer, eli vaatii tosiaan tarkenteen, ks. esim. https://svenska.se/tre/?sok=transfer&pz=8
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_d38e2c8bf9da964a838eaa6daaefc85f&list_id=1&keyword=siirtovaikutus&word=siirtovaikutus
se Nationalencyklopedin

**Comment by mirmaid** [comment]
Tarkemmin tutkien tämä ei ehkä ole ongelma, vaan siirtovaikutus ja interferenssi ovat lähikäsitteitä, joilla voisi varmaan olla RT-suhde.
