### ISSUE TITLE
Kuortaneenjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12663]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kuortaneenjoki](http://www.yso.fi/onto/yso/p151789)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tältä puuttuu yläkäsite, mutta onkohan termi tarpeellinen, kun sitä on käytetty Melindassa vain kerran "Kuortaneenjärven kalastoselvitykset" https://melinda.kansalliskirjasto.fi/byid/004048366  Sanastossa on myös Kuortaneenjärvi, mitä ei ole ko. aineistossa asiasanana, vaikka se olisi oikeampi kuin tämä joki

**Perustelut ehdotukselle**

Kuortaneenjoki ei löydy MML:n palveluista eikä Googlekaan löydä tietoa tästä joesta, kun yhteensä tuloksena 6 viitettä, joista 5 kpl on Finton sanastoihin liittyviä. Eli herää epäilys, olisiko aikanaan vahingossa auktorisoitu Kuortaneenjoki, vaikka aineistossa oli kyseessä Kuortaneenjärvi.

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Poistetaan.
