### ISSUE TITLE
lyöntimetalli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12664]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lyöntimetalli

**Ehdotettu termi ruotsiksi**

slagmetall

**Ehdotettu termi englanniksi**

imitation gold leaf

**Tarkoitusta täsmentävä selite**

Lyöntimetalli on metallilehti, jonka koostumus ei ole kultaa tai hopeaa, vaan yleensä messinkiä, eli sinkkiä ja kuparia.

**Perustelut ehdotukselle**

Lyöntimetalli on kultauksessa ja konservoinnissa Suomessa ja kansainvälisesti yleisesti käytössä oleva käsite.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kultaus](http://www.yso.fi/onto/yso/p16930)

**Ehdotetut temaattiset ryhmät**

 [92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569), [94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Huonekalut, taulunkehykset, interiöörien osat, joiden pintakäsittelyssä ollaan käytetty lyöntimetallia. Lyöntimetalli on jopa lehtikultaa yleisempi pintakäsittely, joka imitoi lehtikultaa. Viitteet esim. konservoinnin opinnäytetyö: https://urn.fi/URN:NBN:fi:amk-2010052410265, ja julkaisu Kunnosta, kultaa ja verhoile ISBN 978-951-0-33699-1

**Ehdottajan organisaatio**

Helsingin kaupunginmuseo
**Termiehdotus Fintossa:** [lyöntimetalli](http://finto.fi/yse/fi/page/Y512664)

**Comment by mariaforsen** [comment]
Eli tämäkö? https://www.slojd-detaljer.fi/tuotteet/luo-koristele/kultaus/lyontimetalli-1121 
https://konstnarernas.se/product.html/slagmetall

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
