### ISSUE TITLE
Pelkosenniemi (kirkonkylä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12661]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Pelkosenniemi (kirkonkylä)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Pelkosenniemen kunnan keskus, Pelkosenniemen kirkonkylä.

**Perustelut ehdotukselle**

Maantieteellinen paikannimi.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Pelkosenniemi](http://www.yso.fi/onto/yso/p105303)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esimerkiksi: Pelkosenniemen kirkonkylän kyläsuunnitelma

**Ehdottajan organisaatio**

Rovaniemen kaupunginkirjasto - Lapin maakuntakokoelma.
**Termiehdotus Fintossa:** [Pelkosenniemi (kirkonkylä)](http://finto.fi/yse/fi/page/Y512661)

**Comment by ilona-x** [comment]
PNR:

Pelkosenniemi http://paikkatiedot.fi/so/1000772/10257984
Paikanlaji Kunta

Pelkosenniemi http://paikkatiedot.fi/so/1000772/12002529
Paikanlaji
Kaupunkialue tai taajama

---

Huom. YSA:n aikaisissa auktorisointiohjeissa ollut tällainen kohta:

**E. Kylän tai kaupunginosan nimi on sama kuin kunnan/kaupungin nimi**

esim. Pihtipudas on sekä kunta että kylä Pihtiputaalla, tehdään näin

151 Pihtipudas

**Comment by mirmaid** [comment]
Sama tilanne on lukuisissa Suomen kunnissa, aiheuttaisi tarpeen tehdä vastaava muutos laajasti koko sanastossa, jolloin myös kunnille pitäisi lisätä tarkenne. 

Kun kylän tai kaupunginosan nimi on sama kuin sen kunnan/kaupungin nimi, johon se kuuluu, sitä ei oteta sanastoon erikseen. (Lisätään linjauksiin.)
