### ISSUE TITLE
muistitietotutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12673]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

muistitietotutkimus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

memory studies

**Tarkoitusta täsmentävä selite**

Tieteen termipankki: muistitietotutkimus 
omaehtoisiin joko omakohtaisiin tai yhteisöllisiin kokemuksiin perustuvaan historialliseen tietoon kohdistuva tutkimus

**Perustelut ehdotukselle**

Tarpeellinen asiasanoitettaessa  humanistien tutkimuksen teoksia eri aloilta

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Yleensä teoksissa, joissa abstraktissa tai asiasanana on " memory studies "

**Ehdottajan organisaatio**

Turun yliopiston kirjasto
**Termiehdotus Fintossa:** [muistitietotutkimus](http://finto.fi/yse/fi/page/Y512673)

**Comment by mariaforsen** [comment]
Sv. ? minnesstudier? 
https://www.historisktidskrift.se/index.php/june20/article/view/652/595
https://www.su.se/institutionen-for-kultur-och-estetik/kalender/symposium-contested-sites-of-memory-1.700131
https://www.adlibris.com/fi/sv/bok/mellan-minne-och-glomska-studier-i-det-kulturella-minnets-forvandlingar-9789171734877

**Comment by krinay** [comment]
Melindassa 332 tietuetta, joissa asiasanat muistitieto + tutkimus.

**Comment by krinay** [comment]
Englanniksi oral history research? Ks. Tieteen termipankki (folkloristiikka): [muistitietotutkimus](https://tieteentermipankki.fi/wiki/Folkloristiikka:muistitietotutkimus).

**Comment by krinay** [comment]
Ks. myös [#12696](https://github.com/Finto-ehdotus/YSE/issues/12696
)

**Comment by AuHo22** [comment]
https://agricolaverkko.fi/review/monitieteinen-ja-paikkainen-muistitietotutkimus/

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon. Tutkitaan termivastineita muille kielille.

Lisättäneen käsitteelle englanniksi sekä termi oral history research että cultural memory studies. Ks. https://agricolaverkko.fi/review/monitieteinen-ja-paikkainen-muistitietotutkimus/

**Comment by mariaforsen** [comment]
Sv. oral history (forskning)?

http://www.oralhistory.se/
/uppslagsverk/encyklopedi/lång/oral-history
https://id.kb.se/term/sao/Oral%20history
https://oa.finlit.fi/site/books/10.21435/skst.1478/read/?loc=Muistitietotutkimuksen_paikka-5.xhtml
https://github.com/Finto-ehdotus/YSE/issues/12696
https://tieteentermipankki.fi/wiki/Nimitys:suullinen_historia
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_24c18a9cfd0586c63be262d8c3547d3e&list_id=1&keyword=muistitieto&word=muistitieto
https://www.kielitoimistonsanakirja.fi/#/muistitieto?searchMode=all
https://helda.helsinki.fi/server/api/core/bitstreams/c634cf7b-632c-4258-a119-4b3c792ed99e/content
https://thy.fi/wp-content/uploads/2011/09/HM6-61-82.pdf
https://libris.kb.se/bib/10278769
https://journal.fi/budkavlen/article/download/130269/78845/281951 :
"I boken utreds begreppet utgående från engelskans oral history, vilket även är en term som ofta förekommer på svenska vid sidan av muntlig historia. Eftersom detta dock markerar det specifikt muntliga, vilket inte alltid är önskvärt, har man på finskt håll försökt hitta en finsk översättning för begreppet oral history, och stannat för muistitietotutkimus. Detta innebär alltså en term för forskning om hågkomstmaterial som kan vara både muntligt och skriftligt."
