### ISSUE TITLE
selkolehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12670]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[selkolehdet](http://www.yso.fi/onto/yso/p1799)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT-suhde "selkoaineistot"-asiasanaan muutetaan LT-suhteeksi

**Perustelut ehdotukselle**

Eivätkö kaikki selkolehdet ole selkoaineistoja? Jos ovat, niin suhteen pitäisi olla LT.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Tämä on kielletty monihierarkia YSOssa, eli vaatii selkoaineistot-käsitteen hierarkian tarkistusta.
