### ISSUE TITLE
neuromoninaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12675]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neuromoninaisuus

**Ehdotettu termi ruotsiksi**

neurodiversitet

**Ehdotettu termi englanniksi**

neurodiversity

**Tarkoitusta täsmentävä selite**

Neuromoninaisuus (neurodiversity) 
= Ihmiskunnan luonnollista neurobiologista vaihtelevuutta ja neurokehityksellistä erilaisuutta. Neuromoninaisuus on kattotermi ja sen alle kuuluvat kaikki neuromoninaisuuden muodot kuten autismin kirjo, ADHD, oppimisvaikeudet, persoonallisuushäiriöt, myös neurotyypillisyys.
https://www.neuromoninaiset.fi/sanasto 

**Perustelut ehdotukselle**

tarvitaan kirjastoaineisto kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [neuropsykologia](http://www.yso.fi/onto/yso/p14664)

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

 neurodiversiteetti 

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh2021004083.html), [neurokirjon syrjimätön sanasto](https://asy.fi/autismin-ja-neurokirjon-uusi-syrjimaton-sanasto-on-julkaistu/), [wikipedia](https://fi.wikipedia.org/wiki/Neurodiversiteetti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helka.helsinki.fi/permalink/358UOH_INST/q5v72t/alma9934581731106253

**Ehdottajan organisaatio**

Museoviraston kirjasto
**Termiehdotus Fintossa:** [neuromoninaisuus](http://finto.fi/yse/fi/page/Y512675)

**Comment by mariaforsen** [comment]
Sv. neurodiversitet HT neuromångfald, neurologisk mångfald
https://www.psykologiguiden.se/psykologilexikon/?Lookup=neurodiversitet
https://tidningenattention.se/artiklar/neurodiversitet-neurologisk-mangfald/

**Comment by mirmaid** [comment]
Kerran Melindassa. Sanastossa on _moninaisuus_ ja _sukupuolen moninaisuus_ (+ geo- ja biodiversiteetti).

**Comment by FinMeSHienPaimentaja** [comment]
Ainakaan lääketieteen puolella ei ole toistaiseksi tullut vastaan, että puheena olevalle termille olisi tarvetta sis.kuvailussa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. YSO-ylläpito päättää tykönään valitaanko käytettäväksi termiksi neuromoninaisuus vai neurodiversiteetti. Muita muotoja on esim. neuromonimuotoisuus, neurobiologinen diversiteetti/monimuotoisuus.
