### ISSUE TITLE
lääkinnälliset laitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12676]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lääkinnälliset laitteet](http://www.yso.fi/onto/yso/p18016)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yläkäsitteen vaihto > tuotteet tms. 

**Perustelut ehdotukselle**

Kaikki "lääkinnälliset laitteet" eivät ole varsinaisia laitteita
https://fimea.fi/laakinnalliset_laitteet/mita-ovat-laakinnalliset-laitteet-
https://www.kielitoimistonsanakirja.fi/#/laite?searchMode=all

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
"Lääkinnällisiä laitteita ovat perinteisesti lääkinnällisiksi laitteiksi miellettävien hengityskoneiden tai defibrillaattorien lisäksi myös useat kotoa löytyvät tarvikkeet, esimerkiksi verenpainemittari, laastari, silmälasit, kuulolaite ja kondomit. Lääkinnällisiä laitteita ovat myös esimerkiksi silmien kostutukseen tarkoitetut silmätipat tai lihaskipuihin käytettävä kylmägeeli."
Laitteet on sv. apparater (https://svenska.se/tre/?sok=apparat&pz=1)

**Comment by mirmaid** [comment]
Vähän hassua että niitä halutaan nimittää juuri laitteiksi, kun kielestä löytyisi aivan tuttuja ja ymmärrettäviä kattavampia sanoja (tuotteet, tarvikkeet, välineet) 🙄

**Comment by mirmaid** [comment]
Alakäsitteille YK laitteet, tälle RT laitteet, YK välineet.
