### ISSUE TITLE
Finlandia-palkinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12678]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Finlandia-palkinto](http://www.yso.fi/onto/yso/p25254)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermiksi Kaunokirjallisuuden Finlandia

**Perustelut ehdotukselle**

Nykyinen nimi, on myös muita Finlandia-palkintoja
https://kirjasaatio.fi/finlandia/kaunokirjallisuuden-finlandia

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. [Finlandiapriset i skönlitteratur](http://kirjasaatio.fi/finlandia/kaunokirjallisuuden-finlandia)
