### ISSUE TITLE
seulontamenettely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12685]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seulontamenettely](http://www.yso.fi/onto/yso/p22979)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkenne, esim. (oikeus)

**Perustelut ehdotukselle**

Sana saattaa olla vakiintumassa omaksi käsitteekseen myös EU:n ulkorajojen turvaamista ja muuttovirtojen hallintaa käsittelevissä asiakirjoissa, esim. 

https://www.eduskunta.fi/FI/vaski/JulkaisuMetatieto/Documents/EDK-2024-AK-2393.pdf

**Ehdottajan organisaatio**

Eduskunnan kanslia

**Comment by mirmaid** [comment]
Vain 5 viitettä Melindassa, ja tästä on jo luovuttu. Voisi muuttaa > hovioikeuksien seulontamenettely KT hovioikeuden seulontamenettely, seulontamenettely hovioikeudessa.

**Comment by YSO-kokous** [comment]
Muutetaan käytettäväksi termiksi hovioikeuksien seulontamenettely.

**Comment by mariaforsen** [comment]
Sv. sållningsförfarande (hovrätter) HT hovrätters sållningsförfarande
https://oikeusministerio.fi/sv/-/hovioikeuksien-seulontamenettelya-kohdennettaisiin-uudelleen
