### ISSUE TITLE
lounassetelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12683]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lounassetelit](http://www.yso.fi/onto/yso/p22665)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lounasetu 

**Perustelut ehdotukselle**

parempi kuvaus, koska nykyään seteliä ei enää käytetä vaan joko luottokortin omaista palvelua tai puhelinappia. sitten lounasseteli olisi yksi näistä muodoista, nyt muoto on ohittanut asiat. Sen sijaan luontoisedut ei ole tarpeeksi kuvaava

**Ehdottajan organisaatio**

DVV, mutta omissa nimissäni kirjoittelen, Anna Lind

**Comment by ilona-x** [comment]
JUPOssa: 
ravintoedut http://www.yso.fi/onto/jupo/p4510
lounassetelit http://www.yso.fi/onto/jupo/p5037

--

fi        ravintoetu; ateriaetu

määritelmä
luontoisetu, joka syntyy, kun työnantaja tarjoaa työntekijälleen aterian

huomautus
Työnantaja voi tukea ruokailukustannuksia lounasseteleillä tai -kortilla tai järjestämällä työpaikkaruokailun. Ravintoedun verotusarvo määräytyy Verohallinnon päätöksen mukaan. Ravintoetuna voidaan tarjota yksi ateria kotimaan työssäolopäivää kohti käypää alempaan hintaan tai täysin vastikkeetta.

Lähde: Palkkahallinnon sanasto (2016) https://termipankki.fi/tepa/fi/haku/ravintoetu

**Comment by mariaforsen** [comment]
Sv. lunchförmån, kostförmån (ravinto/ateriaetu)

**Comment by mirmaid** [comment]
Muutos varmaankin ok, mutta mikä olisi paras päätermi? Omaan korvaan ateriaetu on tutuin, mutta ravintoetu näyttää olevan verotuksessa käytetty muoto.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa ateriaetu, ohjaustermeiksi lounassetelit ja ravintoetu. YSO-ylläpito tutkii valitaanko yksikkö- vai monikkomuoto.

**Comment by mariaforsen** [comment]
Sv. måltidsförmåner HT lunchförmåner (fi. lounasetu), kostförmåner (fi. ravintoetu) 
https://www.maltidsstodet.se/
https://www.sanakirja.fi/custom/all/ateriaetu
https://www.vero.fi/sv/Detaljerade_skatteanvisningar/anvisningar/47886/naturaf%C3%B6rm%C3%A5ner-i-beskattningen/
https://finlex.fi/sv/laki/alkup/2023/20231034
https://tyoelamanpelisaannot.fi/se/lon/
jfr https://finto.fi/jupo/sv/page/p4510
