### ISSUE TITLE
knallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12687]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

knallit

**Ehdotettu termi ruotsiksi**

knallar / knallhattar / kubbar / plommonstop

**Ehdotettu termi englanniksi**

bowler hats

**Tarkoitusta täsmentävä selite**

(Miesten) koholierinen pyöreäkupuinen kovitettu hattu

**Perustelut ehdotukselle**

Finnassa ja Melindassa paljon hakutuloksia knallilla, mutta puuttuu sanastosta (MAO-ontologiassa kylläkin on, mutta kyseessä yksikielinen sanasto).

**Ehdotettu yläkäsite YSOssa (LT)**

 [hatut](http://www.yso.fi/onto/yso/p25504)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh95003037), [Wikidata](https://www.wikidata.org/wiki/Q650570)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [knallit](http://finto.fi/yse/fi/page/Y512687)

**Comment by mariaforsen** [comment]
Sv. plommonstop HT knallar (hattar), knallhattar (hattar), kubbar (hattar), bowlerhattar
https://sv.wikipedia.org/wiki/Plommonstop

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
