### ISSUE TITLE
kuntouttava työtoiminta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12682]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuntouttava työtoiminta](http://www.yso.fi/onto/yso/p3321)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

"Tarkoittaa hyvinvointialueen järjestämää toimintaa..."

**Perustelut ehdotukselle**

Hyvinvointialueet vastaavat nykyään kuntouttavan työtoiminnan järjestämisestä, ei kunnat.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Nykyinen määritelmä on otettu v. 2001 laista: 

_Tarkoittaa kunnan järjestämää toimintaa, jonka tarkoitus on parantaa henkilön elämänhallintaa sekä luoda edellytyksiä työllistymiselle. Kuntouttavassa työtoiminnassa ei synny virkasuhdetta eikä työsuhdetta henkilön ja toimintaa järjestävän tai toteuttavan tahon välille._

Tällä hetkellä vastaava lainkohta: _"kuntouttavalla työtoiminnalla palvelua, jonka tarkoituksena on parantaa henkilön elämänhallintaa sekä luoda edellytyksiä työllistymiselle ja jossa ei synny virkasuhdetta eikä työsuhdetta henkilön ja toimintaa järjestävän tai toteuttavan tahon välille"_.

Ja eri pykälän alla: _Kuntouttavan työtoiminnan järjestää hyvinvointialue_.

Eli ehdotan, että muutetaan määritelmä vastaamaan uuden lain muotoilua, esim. "Hyvinvointialueen järjestämä palvelu, jonka tarkoituksena on parantaa henkilön elämänhallintaa sekä luoda edellytyksiä työllistymiselle (ja jossa ei synny virkasuhdetta eikä työsuhdetta henkilön ja toimintaa järjestävän tai toteuttavan tahon välille)." (En tiedä onko tuo suluissa oleva tarpeellinen.)
