### ISSUE TITLE
hyvä kohtelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12684]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hyvä kohtelu

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Saimme Finto-palautetta: 
"Hyvä kohtelu" olisi oleellinen käsite lisättäväksi YSO-asiasanastoon. Olimme laittamassa opinnäytetyötä Theseukseen ja tämä ongelma tuli eteen. Pystyttekö lisäämään käsitteen YSO-asiasanastoon ja kuinka kauan asiassa menee? Käsite on todella tärkeä lastensuojelun sijaishuollon valvontaan liittyen. Aihe on vielä tuore ja siitä tulee varmasti vielä lisää opinnäytetöitä ja tutkimusta. Laissa määrätyllä "Hyvää kohtelua koskevalla suunnitelmalla" turvataan lastensuojelun sijaishuollossa olevien lasten oikeudet. Säädös on lisätty lastensuojelulakiin vuonna 2019 (Laki lastensuojelulain muuttamisesta 61 b § 542/2019). Tässä vielä muutamia lainauksia opinnäytetyöstämme: "Hyvää kohtelua koskeva suunnitelma on säädetty lastensuojelulaissa ja se toimii osana lastensuojelulaitoksen omavalvontaa ollen kuitenkin erillinen oma kokonaisuutensa." "Hyvää kohtelua koskevan suunnitelman tarkoituksena on turvata lastensuojeluyksikköön sijoitettujen lasten oikeudenmukainen kohtelu, oikeusturvakeinot sekä vähentää lastensuojelulaissa säädettyjen rajoitustoimenpiteiden käyttöä." "Hyvää kohtelua koskeva suunnitelma on osa lastensuojelulaitosten omavalvontasuunnitelmaa. Hyvää kohtelua koskeva suunnitelma arvioidaan ja tarkastetaan vuosittain. Säännös hyvää kohtelua koskevasta suunnitelmasta on velvoittava lastensuojelulaitoksille." "Suunnitelmassa kuvataan kokonaisvaltaisesti ja perustellen - opinnäytetyön tilaajaorganisaationa toimineen lastensuojelun sijaishuollon erityisyksikön - arkea ja toimintatapoja sekä lapsen oikeuksia ja velvollisuuksia." "Hyvää kohtelua koskeva suunnitelma on lisätty lastensuojelulakiin vuonna 2019. Vaatimus suunnitelman sisällyttämisestä sijaishuoltoa tarjoavien yksiköiden omavalvontasuunnitelmaan on tullut voimaan 1.1.2020. Sijaishuoltopaikan tulee varmistaa, että jokainen sijoitettu lapsi sekä sijoittava hyvinvointialue ja lapsen asioista vastaava sosiaalityöntekijä tutustuu yksikön Hyvää kohtelua koskevaan suunnitelmaan. Suunnitelman tulee olla asukkaille helposti saatavilla. (Laki lastensuojelulain muuttamisesta 61 b § 542/2019.) Suunnitelman pääpaino on ongelmien ennaltaehkäisyssä, kuten rajoitustoimien käytön ehkäisyssä (Sosiaali- ja terveysministeriö. 2018)." "Lastensuojelun keskusliiton julkaisu “Oikeus ihmisarvoa ja itsemääräämisoikeutta kunnioittaviin palveluihin” (Pollari & Toivonen) vuodelta 2019 nousi esiin opinnäytetyötä tehdessä. Julkaisussa nostetaan esiin kyseiseen aikaan tapahtuneet lapsen oikeuksien räikeät rikkomiset lastensuojelun sijaishuollossa. Tärkeäksi nostetaan sosiaalihuoltolain (1301/2014) ensimmäisen pykälän neljännessä momentissa oleva asiakkaan oikeus hyvään palveluun ja kohteluun sosiaalihuollossa. Opinnäytetyötämme ajatellen, kaikki nämä vuonna 2019 ilmi tulleet epäkohdat ja niiden uutisoinnit ovat varmasti olleet merkittävästi vaikuttamassa 1.1.2020 voimaan tulleeseen lakimuutokseen ja vaatimukseen koskien hyvää kohtelua koskevaa suunnitelmaa lastensuojelulaitoksissa. " "Uskomme opinnäytetyömme omalta osaltaan edistävän lapsen edun toteutumista ja sen valvontaa Tahtorannassa ja mahdollisesti muissakin lastensuojelu-laitoksissa. Toiminnan läpinäkyvyys lisää luotettavuutta lastensuojelua kohtaan, mikä toivottavasti välittyy myös lastensuojelun asiakkaana oleviin perheisiin. Toivomme suunnitelman käyttämisen lastensuojelun sijaishuollossa tuovan positiivista ja välittävää kuvaa sijaishuoltoon ja koko lastensuojeluun." Kiitos teille!

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ks. perustelut

**Ehdottajan organisaatio**

Finto-palaute
**Termiehdotus Fintossa:** [hyvä kohtelu](http://finto.fi/yse/fi/page/Y512684)

**Comment by mariaforsen** [comment]
Kun sanasto on myös muunlaisia "kohteluita" niin ehkä tämäkin olisi hyvä, mutta termi käytetään muissakin konteksteissa kuin lastensuojelussa. https://finto.fi/yso/fi/page/p27806

Sv. gott bemötande
https://www.theseus.fi/bitstream/handle/10024/796012/Solin_Linn-Sophie.pdf;jsessionid=FCB19812280A0F2210077F8A8E47DA05?sequence=2
https://stm.fi/potilaan-oikeudet
https://www.vardochinsats.se/missbruk-och-beroende/kommunikation-och-delaktighet/gott-bemoetande/
https://www.lapsenoikeudet.fi/sv/ratt-till-gott-bemotande/
https://thl.fi/sv/publikationer/handbocker/handbok-for-barnskyddet/arbetsprocesser/vard-utom-hemmet/barnets-rattigheter-vid-vard-utom-hemmet

**Comment by mirmaid** [comment]
Ei Melindassa. Sanastossa on toki myös _kohtelu_. (Jos tutkitaan sitä, millaista on _hyvä kohtelu_ jossakin yhteydessä, tutkitaan tai määritellään todennäköisesti myös sitä mikä ei ole _hyvää_ kohtelua.)

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
