### ISSUE TITLE
Wegenerin granulomatoosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12680]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Wegenerin granulomatoosi](http://www.yso.fi/onto/yso/p26083)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Nykyään granulomatoottinen polyangiitti

**Perustelut ehdotukselle**

Mesh

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://reumaliitto.fi/reuma-aapinen/granulomatoottinen-polyangiitti-gpa-ent-wegenerin-granulomatoosi/
