### ISSUE TITLE
merkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12699]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[merkit](http://www.yso.fi/onto/yso/p1581)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Hierarkia kaipaa tarkistamista.

**Perustelut ehdotukselle**

Nykyinen hierarkia tieto > merkit > ansiomerkit/arvomerkit/asevelimerkit/... ei vaikuta läpeensä loogiselta, varsinkaan verrattuna muiden tieto-asiasanan ST-suhteisten rinnalla.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan. Tieto on =kunskap YSOssa, on kyllä virheellinen hierarkia.

**Comment by mirmaid** [comment]
Täällä https://github.com/NatLibFi/Finto-data/issues/859 ehdotettu YK yhteiskunnalliset objektit.
