### ISSUE TITLE
hyperteksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12693]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hyperteksti](http://www.yso.fi/onto/yso/p14671)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCSH-asiasanaan "Hypertext systems" (http://id.loc.gov/authorities/subjects/sh88002671)

**Perustelut ehdotukselle**

Siltaus LCSH-sanastoon puuttuu.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sama linkki SAOssa.

**Comment by tpalonen** [comment]
Linkki lisätty
