### ISSUE TITLE
Erbin pareesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12697]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Erbin pareesi](http://www.yso.fi/onto/yso/p10112)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Päätermin tarkistus ja suhde englantiin

**Perustelut ehdotukselle**

Jos/kun Erbin pareesi on olkahermopunoksen syntymävaurio, niin ehkä myös muunkielisten termien pitäisi rajautua siihen? 

https://www.invalidiliitto.fi/sites/default/files/2016-11/Erbinpareesiopas_2013_netti.pdf 

Eng. taitaa nyt olla mikä tahansa tällainen vamma, joka on voinut syntyä elämän aikana (ks. esim. https://www.healthline.com/health/brachial-plexopathy ) 

Vai tehdäänkö kuten Meshissä? https://finto.fi/mesh/fi/page/D020516

**Ehdottajan organisaatio**

**Comment by FinMeSHienPaimentaja** [comment]
Erbin pareesi näyttäisi olevan yksi, tietynlainen vaurio näistä hermohämmingeistä. Enkuksi Erb's palsy?

**Comment by tpalonen** [comment]
Vaihdoin päätermiksi Erb's palsy
