### ISSUE TITLE
planetaarinen terveys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12691]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

planetaarinen terveys

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://thl.fi/thl/tietoa-meista/vaikuttamistavoitteet/planetaarinen-terveys-ja-hyvinvointi
Planetaarinen terveys ja hyvinvointi perustuu ymmärrykseen ihmisen ja muun luonnon välisistä yhteyksistä. Luonnon järjestelmät ylläpitävät elämää tuottaessaan muun muassa puhdasta vettä, happea ja ravintoa. Luonto suojaa meitä tulvilta, myrskyiltä ja muilta sään ääri-ilmiöiltä. Kosketus monimuotoiseen luontoon vahvistaa ihmiskehon mikrobistoa ja suojaa meitä monilta sairauksilta. Ihminen on osa luonnon kokonaisuutta ja täysin riippuvainen tämän kokonaisuuden elinvoimaisuudesta.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 planetaarinen terveys ja hyvinvointi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [planetaarinen ruokavalio](http://www.yso.fi/onto/yso/p40151)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.sitra.fi/julkaisut/tavoitteena-planetaarinen-terveys/
Tavoitteena planetaarinen terveys ISBN 978-952-347-341-6

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [planetaarinen terveys](http://finto.fi/yse/fi/page/Y512691)

**Comment by mariaforsen** [comment]
Sv. planetär hälsa
https://www.sls.se/om-oss/aktuellt/Nyheter/2022/planetart-perspektiv-pa-halsa/
https://medarbetare.ki.se/planetar-halsa-en-sjalvklar-del-av-hogre-utbildning-for-halsoprofessioner

**Comment by mirmaid** [comment]
_Planetary Health refers to "the health of human civilization and the state of the natural systems on which it depends"._ 
https://en.wikipedia.org/wiki/Planetary_health

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
