### ISSUE TITLE
oikeusapu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12690]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oikeusapu](http://www.yso.fi/onto/yso/p9200)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään "yleinen oikeusapu" -asiasanan kanssa?

**Perustelut ehdotukselle**

Asialla ei voi aikarajausta samalla tavalla kuin yhteisöillä ym., joten näiden asiasanojen merkitys ja varsinkin selitys pitäisi tarkistaa ja korjata.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
https://www.kielitoimistonsanakirja.fi/#/oikeusapu?searchMode=all
Sv. viittaa siis kakkosmerkitykseen. 

NE: "[allmän rättshjälp](https://www-ne-se.ezproxy.vasa.abo.fi/uppslagsverk/encyklopedi/l%C3%A5ng/allm%C3%A4n-r%C3%A4ttshj%C3%A4lp): staten betalar rättegångskostnaderna för en person som beviljats rättshjälp, se [rättshjälp](https://www-ne-se.ezproxy.vasa.abo.fi/uppslagsverk/encyklopedi/l%C3%A5ng/r%C3%A4ttshj%C3%A4lp)."

**Comment by mirmaid** [comment]
Erottelu perustuu siis lainsäädäntöön, aikaisemman lain puitteissa _yleinen oikeusapu_. Vastaavia edeltäjä-seuraaja-suhteita on sanastossa jonkin verran, osittain kyse on siitä että uudemman termin käyttö vanhemmissa aineistoissa toisi kummallista anakronismia, ja osittain jos on muilla perusteilla katsottu olevan kyse eri käsitteestä. Tässä perusteena on siis tuo eri lakeihin perustuva säätely. Termiongelmaa ei toki ole, jos yhdistetään.

Eli asialla ei ole aikarajausta, vaan kyse on näissä tapauksissa jollain perusteella eri asioista.

**Comment by YSO-kokous** [comment]
YSO-ylläpito tutkii vielä asiaa.

**Comment by jtuohini** [comment]
Yleinen huomio liittyen sanaston periaatteisiin ja Mirjan kommenttiin "uudemman termin käyttö vanhemmissa aineistoissa toisi kummallista anakronismia": koko asiasanoitus ymmärtääkseni pyrkii perustumaan nykykieleen, joten anakronismilta ei voi välttyä, olipa kyse harmittoman kuuloisista muuttuvan kielen käsitteistä, kuten "keuhkotauti" ~ "tuberkuloosi" tai "muusikeri" ~ "muusikko", tai ongelmallisemmiksi koetuista, kuten "lappalaiset" ~ "saamelaiset" tai "neekerit" ~ "mustat", saati tilanteista, joissa kuvailtavalle asialle ei edes (omana) aikanaan ollut käsitettä, jollaista siitä nykyään käytetään eli josta käytetty terminologia on kaikkiaan takautuvaa, kuten aikakausimääreet "barokki", "Ruotsin vallan aika" ja "vanha aika".

**Comment by mirmaid** [comment]
^ Usein nämä ovatkin ihan ongelmattomia. Joskus esim. uusi ammattinimike tuntuu väärältä käyttää henkilöistä, jotka eivät oikeastaan ole olleet ko. ammatin edustajia, vaan heillä on ollut toinen ammattinimike (esim. suuhygienistit, fysioterapeutit). Muita esimerkkejä ovat ajassa eläneet yhteiskunnan instituutiot (YSOssa esim. kasvatuslaitokset/koulukodit, värvätyt/sotilasammattihenkilöt). Mutta en siis ota kantaa nyt siihen, onko edeltäjä-seuraaja-suhde näissä paras mahdollinen.
