### ISSUE TITLE
Uudenmaan murteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12698]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Uudenmaan murteet](http://www.yso.fi/onto/yso/p29238)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään sulkutarkenne (suomenruotsi)

**Perustelut ehdotukselle**

On riski, että tämän tulkitaan viittaavan suomen kielen murteisiin. Suomen kielen murteiden puolella on olemassa esim. Länsi-Uudenmaan murre. Ks. https://www.kotus.fi/kielitieto/murteet/suomen_murteet

Turunmaan murteille voisi harkita samaa sulkutarkennetta? Suomen kielen puolella on olemassa Turun ylämaan murteet. Ks. linkki edellä.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by YSO-kokous** [comment]
Lisätään ehdotetut sulkutarkenteet.
