### ISSUE TITLE
historialliset sarjaohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12705]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[historialliset sarjaohjelmat](http://www.yso.fi/onto/yso/p40247)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko sama asia kuin epookkisarjat (SLM)

**Perustelut ehdotukselle**

----

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
Aiemmin keskusteltiin aikakausromaanien/taparomaanien eroista (ohjaus epookkiromaanit), myös historiallisten romaanien määritelmä.

**Comment by mirmaid** [comment]
Epookkisarjat YK historialliset sarjaohjelmat
Tilannekomediat YK komediasarjat
