### ISSUE TITLE
Web 3.0

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12703]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Web 3.0

**Ehdotettu termi ruotsiksi**

Web 3.0

**Ehdotettu termi englanniksi**

Web 3.0

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Web3 (myös Web 3.0), on idea World Wide Webin uudesta kehityskierroksesta lohkoketjuihin perustuen. Siihen liittyy ajatuksia desentralisaatiosta ja tokeneihin perustuvasta taloudesta.
https://fi.wikipedia.org/wiki/Web3

**Ehdotettu yläkäsite YSOssa (LT)**

 [tekniset järjestelmät](http://www.yso.fi/onto/yso/p2536)

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553), [45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542)

**Vaihtoehtoiset termit**

 Web3

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [Web 2.0](http://www.yso.fi/onto/yso/p22305)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.sitra.fi/julkaisut/miten-kestavaa-maailmaa-web-3-0-rakentaa/

**Ehdottajan organisaatio**

KK/HR

**Comment by mariaforsen** [comment]
Sv. web 3.0 HT web3 
https://www.sitra.fi/sv/artiklar/web-3-0-och-utvecklingen-mot-det-nya-internet-vad-ar-det-fraga-om-och-vad-erbjuder-det-oss/
https://innowise.com/sv/blog/what-is-web-3-0-and-why-it-matters-for-business/
https://it-ord.idg.se/ord/web3/ 
https://it-ord.idg.se/ord/webb-3-0/
https://www.voister.se/voister-forklarar/vad-ar-web3-och-vad-innebar-det-for-mig

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
