### ISSUE TITLE
voimistelusalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12700]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[voimistelusalit](http://www.yso.fi/onto/yso/p15880)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarpeen / miten rajautuu?

**Perustelut ehdotukselle**

wikidata-linkitys

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
On nyt siis sv. gymnastiksalar (lähinnä koulujen liikuntatilat)... Vrt. https://finto.fi/yso/fi/page/p8504?clang=sv

**Comment by mirmaid** [comment]
Käytetty Melindassa 25 kertaa, eniten koulujen liikuntasaleista mutta myös muusta. Varmaan _liikuntatilat_ olisi riittävä?

**Comment by YSO-kokous** [comment]
Poistetaan käsite sanastosta. Lisätään ohjaustermi:
voimistelusalit KÄYTÄ liikuntatilat
