### ISSUE TITLE
ekosysteemitilinpito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12702]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ekosysteemitilinpito

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.syke.fi/ekosysteemitilinpito
Ekosysteemitilinpito laajentaa perinteistä kansantalouden tilinpidon järjestelmää ottamalla kokonaisvaltaisesti huomioon niin luonnon ekosysteemipalveluiden tuomat hyödyt kuin ihmistoiminnan luonnolle aiheuttamat haitat ihmiskunnalle ja taloudelliselle toiminnalle. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirjanpito](http://www.yso.fi/onto/yso/p2692)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ympäristötilinpito](http://www.yso.fi/onto/yso/p15883)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.sitra.fi/julkaisut/luontopaaoma-kartalle-ja-euroiksi/

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [ekosysteemitilinpito](http://finto.fi/yse/fi/page/Y512702)

**Comment by mariaforsen** [comment]
Sv. ekosystemräkenskaper 
https://www.ivl.se/vart-erbjudande/forskning/biologisk-mangfald/ekosystemrakenskaper.html
https://termipankki.fi/tepa/fi/haku/ekosystemr%C3%A4kenskaper
https://norden.diva-portal.org/smash/get/diva2:1706961/FULLTEXT01.pdf
https://www.sitra.fi/sv/nyheter/naturkapitalet-kan-matas-med-en-ny-typ-av-rakenskaper-finland-skulle-ha-nytta-av-ett-heltackande-genomforande/






Eng. ecosystem accounting?

**Comment by mirmaid** [comment]
Sanastossa on _ympäristötilinpito_.

Ekosysteemitilinpito on myös osa laajempaa ympäristötilinpidon kokonaisuutta. -- Ekosysteemitilinpito eroaa muista ympäristötilinpidon tileistä kahdella merkittävällä tavalla. Ensimmäiseksi tilinpidon kohteena ovat luonnonvarojen sijaan kaikki maapallon ekosysteemit sekä niiden tuottamat ekosysteemipalvelut. Näin ollen myös sellaiset ekosysteemipalvelut, joista ei synny markkinoilla myytäviä tuotteita tai palveluita, tulevat huomioiduksi.  Toiseksi, ekosysteemitilinpidossa on alueellinen (spatiaalinen) ulottuvuus – tilien sisältämä tieto voidaan esittää niin tilinpidon tauluina, kuin erilaisina karttaesityksinä. https://www.syke.fi/ekosysteemitilinpito

**Comment by FinMeSHienPaimentaja** [comment]
Lieneekö näillä paljonkin tarvetta/käyttöä sis.kuvailussa...?

**Comment by YSO-kokous** [comment]
Hyväksytään uutena käsitteenä sanastoon.
