### ISSUE TITLE
follikulaarinen lymfooma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12709]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

follikulaarinen lymfooma

**Ehdotettu termi ruotsiksi**

follikulärt lymfom

**Ehdotettu termi englanniksi**

follicular lymphoma

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu
Melinda x 9

**Ehdotettu yläkäsite YSOssa (LT)**

 [non-Hodgkin-lymfoomat](http://www.yso.fi/onto/yso/p20931)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D008224), [Wikidata](http://www.wikidata.org/entity/Q123251)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Follicular lymphoma: mortality, treatment patterns, and identification of high-risk subgroups  http://urn.fi/URN:ISBN:978-952-61-4934-9

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [follikulaarinen lymfooma](http://finto.fi/yse/fi/page/Y512709)

**Comment by mariaforsen** [comment]
Sv. HT: https://mesh.kib.ki.se/term/D008224/lymphoma-follicular
