### ISSUE TITLE
turvallinen tila

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12718]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

turvallinen tila

**Ehdotettu termi ruotsiksi**

frizon

**Ehdotettu termi englanniksi**

safe space

**Tarkoitusta täsmentävä selite**

Ks. esim. https://www.ykliitto.fi/turvallinen-tila
https://yhdenvertaisuus.fi/turvallisemman-tilan-ohjeistus
https://nuorisoala.fi/palvelut/yhdenvertaisuus/turvallisemman-tilan-periaatteet-ja-vihapuheesta-vapaan-keskustelun-saannot/

**Perustelut ehdotukselle**

Saimme tästä palautetta. "Tämä "termi" tulee nyt jatkuvasti eteen eli "turvallinen tila" en äkkiseltään löytänyt ko asiaa ehdotuksista. Voisiko harkita?"

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

 turvallisen tilan periaatteet, turvallisempi tila, safer space, turvallisen tilan ohjeistus, turvallisemman tilan ohjeistus, turvallisemman tilan periaatteet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [syrjintä](http://www.yso.fi/onto/yso/p6303), [vihapuhe](http://www.yso.fi/onto/yso/p24781), [inkluusio](http://www.yso.fi/onto/yso/p18355), [syrjimättömyys](http://www.yso.fi/onto/yso/p27398)

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q4080972)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/019000654

**Ehdottajan organisaatio**

Finto-palaute
**Termiehdotus Fintossa:** [turvallinen tila](http://finto.fi/yse/fi/page/Y512718)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Safe spaces**](http://id.loc.gov/authorities/subjects/sh2023000011). Olisiko LT-suhde YSO-asiasanaan [**periaatteet**](http://www.yso.fi/onto/yso/p9391), [**sosiaaliset normit**](http://www.yso.fi/onto/yso/p7135) vai [**tilat**](http://www.yso.fi/onto/yso/p3602) eli onko ehdotetulla asiasanalla tarkoitus viitata periaatteisiin vai niiden käytännön toteutukseen t.s. onko painotus tilasta ajatusluomuksena (tila abstraktiona, ihmisten muodostama joukko) vai todellisuutena (konkreettinen fyysinen tila, joka täyttää tietyt turvallisuusmääritykset)?

**Comment by mariaforsen** [comment]
Sv. principer för tryggare rum HT principer för trygga rum, principer för tryggare utrymmen, principer för trygga utrymmen
https://yhdenvertaisuus.fi/sv/anvisningar-for-ett-tryggt-rum
https://sv.wikipedia.org/wiki/Frizon_(tryggt_rum)
https://svenska.se/tre/?sok=frizon&pz=1
https://www.kulturfonden.fi/2024/05/13/riktlinjer-och-regler-for-trygga-rum/
https://www.vaestoliitto.fi/sv/organisation/verksamhet/principer-for-tryggare-rum/
https://nuorisoala.fi/sv/pa-svenska/principer-for-ett-sakrare-utrymme-och-regler-for-diskussioner-fria-fran-hatpropaganda/
https://web.abo.fi/karen/bilagor/publikationer/%C3%85AS%20principer%20f%C3%B6r%20tryggare%20rum%20svenska.pdf
https://rednet.rodakorset.fi/node/65757

**Comment by mirmaid** [comment]
Voisikohan olla _turvalliset tilat_ KT turvallisen tilan periaate?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa turvallisemman tilan periaatteet. Muita muotoja ohjaustermeiksi.

Komparatiivimuoto herätti keskustelua, mutta näytti kuitenkin olevan yleisemmin käytössä kuin turvallisen tilan periaatteet.
