### ISSUE TITLE
Arts and Crafts -liike

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12716]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Arts and Crafts -liike](http://www.yso.fi/onto/yso/p24034)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Hierarkia pitää korjata ja tämä asiasana siirtää pois "organisaatiot"-asiasanan alka

**Perustelut ehdotukselle**

Kyseessä ei ole organisaatio, vaan liike, jonka piirissä luotu taide on suhteessa ja verrattavissa muihin taidesuuntauksiin, kuten jugendiin ja funktionalismiin.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Itse asiassa muutkin liikkeet ovat organisaatioiden alla. Muita mahdollisia olisi[ koulukunnat](http://www.yso.fi/onto/yso/p8954) (alakäsitteinä vain koulukunta-päätteisiä), taiteilijaryhmät (alakäsitteenä esim. prerafaeliitit), tai tyylit (alla mainitut jugend ja funktionalismi).

**Comment by mirmaid** [comment]
YSOssa organisaatiot-käsite on tulkittu väljästi, muutkin liikkeet ja esim. yhteisöt ovat siis sen alakäsitteitä. Ylläpito piti nykyistä paikkaa kuitenkin loogisimpana käsitteelle ottaen huomioon termimuodon.
