### ISSUE TITLE
portugalinsuomalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12711]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

portugalinsuomalaiset

**Ehdotettu termi ruotsiksi**

finländare i Portugal

**Ehdotettu termi englanniksi**

Finnish Portuguese

**Tarkoitusta täsmentävä selite**

Portugalissa asuvat suomalaiset

**Perustelut ehdotukselle**

Espanjansuomalaisten rinnakkaiskäsite. Perustelut samansuuntaiset. 
Tämän vastakkaiskäsite on suomenportugalilaiset, Portuguese in Finland

**Ehdotettu yläkäsite YSOssa (LT)**

 [ulkosuomalaiset](http://www.yso.fi/onto/yso/p5281), [portugalilaiset](http://www.yso.fi/onto/yso/p23621)

**Ehdotetut temaattiset ryhmät**

 [61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570)

**Vaihtoehtoiset termit**

 portugalin suomalaiset, portugalfinländare

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.finna.fi/Record/trepo.10024_93264
https://www.finna.fi/Record/arto.013581461
https://www.finna.fi/Record/jykdok.1274780

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [portugalinsuomalaiset](http://finto.fi/yse/fi/page/Y512711)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
