### ISSUE TITLE
Pyhä saksalais-roomalainen valtakunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12714]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pyhä saksalais-roomalainen valtakunta](http://www.yso.fi/onto/yso/p110651)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan päätermiksi nykyinen ohjaustermi -> Pyhä saksalais-roomalainen keisarikunta 

**Perustelut ehdotukselle**

On yleisimmin käytetty nimimuoto, jota pitäisi suosia, ellei ole vankkoja perusteluja olla muuttamatta.

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12712
