### ISSUE TITLE
espanjansuomalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12710]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

espanjansuomalaiset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Espanjassa asuvat suomalaiset.

**Perustelut ehdotukselle**

Sanastossa on paljon vastaavia, mutta tämä yllättäen puuttuu. Espanjan Aurinkorannikko (ja erityisesti Fuengirola) on kuitenkin tunnettu suomalaiskeskittymä ulkomailla, Tukholman jälkeen suurin, 25 000–30 000 suomalaista. Ks. https://yle.fi/a/3-9627767
Ja toki suomalaisia asuu muuallakin Espanjassa. Kirjoja ja artikkeleja on aiheesta kirjoitettu.

**Ehdotettu yläkäsite YSOssa (LT)**

 [ulkosuomalaiset](http://www.yso.fi/onto/yso/p5281), [espanjalaiset](http://www.yso.fi/onto/yso/p16199)

**Ehdotetut temaattiset ryhmät**

 [61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570)

**Vaihtoehtoiset termit**

 Aurinkorannikon suomalaiset

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018876501
https://melinda.kansalliskirjasto.fi/byid/006772867
https://melinda.kansalliskirjasto.fi/byid/005936927

**Ehdottajan organisaatio**

Tuomas / Finto
**Termiehdotus Fintossa:** [espanjansuomalaiset](http://finto.fi/yse/fi/page/Y512710)

**Comment by mariaforsen** [comment]
Sv. finländare i Spanien HT Spanienfinländare

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
