### ISSUE TITLE
europarlamenttivaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12715]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[europarlamenttivaalit](http://www.yso.fi/onto/yso/p8448)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

EU-vaalit ohjaustermiksi (tai päätermiksi)

**Perustelut ehdotukselle**

Valmistaudumme täällä [oikeusministeriössä] EU-vaaleihin eli europarlamenttivaaleihin. Käytämme valtioneuvostossa verkkoviestinnän julkaisujärjestelmässämme JUHO- ja YSO-asiasanoituksia ja ehdottaisin täydennystä.
Voisiko JUHOon tai YSOon lisätä asiasanan”EU-vaalit”? YSOsta ”europarlamenttivaalit” löytyykin jo. Euroopan parlamentti käyttää itse ja suosittaa käyttämään käsitettä EU-vaalit.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ainakin ohjaustermiksi. Kysyin tarkennusta halutaanko päätermiin muutosta, mutta en saanut siihen enää vastausta. Eri sivustoilla käyttö vaihtelee.

**Comment by LeKorsu** [comment]
Eduskunnan kirjaston asiasasanastossa ei näyttäisi olevan kumpaakaan (europarlamenttivaalit / EU-vaalit), mutta kylläkin useita muita EU-alkuisia asiasanoja.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermeiksi EU-vaalit ja eurovaalit.
