### ISSUE TITLE
Pyhä saksalais-roomalainen valtakunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12712]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pyhä saksalais-roomalainen valtakunta](http://www.yso.fi/onto/yso/p110651)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Otetaan "Pyhä saksalais-roomalainen keisarikunta" päätermiksi

**Perustelut ehdotukselle**

On tunnetumpi ja käytetympi kuin "Pyhä saksalais-roomalainen valtakunta". Seikka nousi esille Toimijakuvailun asiantuntijaverkoston kokouksessa 9.4.2024.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Muutetaan (huomautuksesta pois "virallinen").
