### ISSUE TITLE
mediaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12713]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mediaanit](http://www.yso.fi/onto/yso/p22469)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään Wikidata-linkki http://www.wikidata.org/entity/Q226995

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Mediaani

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Vai onkohan tämä jätetty linkkaamatta, kun mediaani voi näköjään tarkoittaa myös geometrian keskijanaa https://fi.wikipedia.org/wiki/Keskijana 🤔 

--
Kielitoimiston sanakirja:
mediaani
1. geom. keskijana.
2. tilastot. jakauman lukuarvoista suuruusjärjestyksessä keskimmäinen.

**Comment by mariaforsen** [comment]
Pitäisi varmaan jakaa? Samalla tavalla monimerkityksinen ruotsiksi.
https://svenska.se/tre/?sok=median&pz=1

**Comment by mirmaid** [comment]
2 viitettä Melindassa. En ihan usko että tuosta keskijanasta ilmestyy aineistoja, kun ei kerran tilastollisestakaan ole 17 vuodessa tullut enempää.
