### ISSUE TITLE
nuorisorikollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12726]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nuorisorikollisuus](http://www.yso.fi/onto/yso/p14411)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

youth crime käytettäväksi termiksi ja juvenile delinquency ohjaustermiksi.

**Perustelut ehdotukselle**

Valtioneuvostossa suositellaan youth crime termin käyttöä.

**Ehdottajan organisaatio**

VNKn kielipalvelun huomion välitti Leena Granholm/JUHO ylläpito

**Comment by tpalonen** [comment]
Muutettu ehdotetusti
