### ISSUE TITLE
embleemit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12729]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[embleemit](http://www.yso.fi/onto/yso/p9990)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodot "tunnuskuvat" ja "tunnusmerkit"

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/embleemi

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Pitäisikö siinä tapauksessa olla tarkenteella, eli tunnuskuvat (embleemit) KÄ embleemit? Koska tunnuskuva voi viitata muuhunkin: https://www.kielitoimistonsanakirja.fi/#/tunnuskuva?searchMode=all

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermit sanastoon muodossa:
tunnuskuvat (embleemit)
tunnusmerkit (embleemit)
