### ISSUE TITLE
Koivumaa (Kolari)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12723]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Koivumaa (Kolari)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [Kolari](http://www.yso.fi/onto/yso/p94218)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Paikkatiedot](https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/tietokortit/nimisto/paikka/10622086)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/018981652

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Koivumaa (Kolari)](http://finto.fi/yse/fi/page/Y512723)

**Comment by fantsby-m** [comment]
Ehdotuksessa kirjoitusvirhe, pitää olla
Koivumaa (Kolari)
