### ISSUE TITLE
saamelaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12725]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[saamelaiset](http://www.yso.fi/onto/yso/p11537)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Oikea muoto: the Sami tai Sami people

**Perustelut ehdotukselle**

Englanninkielinen vastine Samis on virheellinen

**Ehdottajan organisaatio**

VNK:n kielipalvelun huomion välitti Leena Granholm/JUHO-ylläpito

**Comment by tpalonen** [comment]
Muutettu
