### ISSUE TITLE
Valtion vierastalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12724]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Valtion vierastalo](http://www.yso.fi/onto/yso/p29241)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englannin kielinen käännös on muuttunut: State Guest House

**Perustelut ehdotukselle**

Englannin kielinen käännös on muuttunut: State Guest House

**Ehdottajan organisaatio**

VNK. Kielipalvelun huomion välitti Leena Granholm/JUHO-ylläpito

**Comment by tpalonen** [comment]
Muutin englannin termiksi _State Guest House (Finland)_. Tuntui että tämä tarvitsi tarkenteen. Vrt. https://en.wikipedia.org/wiki/State_guest_house
