### ISSUE TITLE
salafismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12721]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

salafismi

**Ehdotettu termi ruotsiksi**

salafism

**Ehdotettu termi englanniksi**

Salafīyah

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sunnalaisuus](http://www.yso.fi/onto/yso/p2081)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [jihadismi](http://www.yso.fi/onto/yso/p39609)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh00008437), [Wikipedia](https://fi.wikipedia.org/wiki/Salafismi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Contemporary puritan Salafism https://melinda.kansalliskirjasto.fi/byid/016557898

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [salafismi](http://finto.fi/yse/fi/page/Y512721)

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
