### ISSUE TITLE
kuosit (pintakuviointi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12722]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuosit (pintakuviointi)](http://www.yso.fi/onto/yso/p22246)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö tällä olla jokin mallit-ohjaus?

**Perustelut ehdotukselle**

----

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
Kokouksessa ei nähty toistaiseksi tarvetta ohjaustermille.
