### ISSUE TITLE
resilienssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12727]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[resilienssi](http://www.yso.fi/onto/yso/p25253)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan ohjaustermiksi: kriisinkestävyys

**Perustelut ehdotukselle**

Käytetään ainakin Naton yhteydessä.

**Ehdottajan organisaatio**

JUHO-ylläpito Leena Granholm

**Comment by mariaforsen** [comment]
Sv. HT kristålighet
https://termipankki.fi/tepa/fi/haku/kriisinkest%C3%A4vyys

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
