### ISSUE TITLE
Systeemitiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12731]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Systeemitiede

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

systems science

**Tarkoitusta täsmentävä selite**

Wikipedia: Systeemitiede on poikkitieteellinen ala, joka keskittyy systeemien ymmärtämiseen luonnossa ja yhteiskunnassa. Se edistää formaalia kehitystä fyysisten, sosiaalisten ja sovellettujen systeemien alueilla käsittäen teknologian koko laajuudessaan sekä tieteen tutkimisen.

**Perustelut ehdotukselle**

Koko maailma on nykyisin kompleksisten systeemien muodostama verkosto!
To systems scientists, the world can be understood as a system of systems. The field aims to develop transdisciplinary foundations that are applicable in a variety of areas, such as psychology, biology, medicine, communication, business, technology, computer science, engineering, and social sciences.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tieteenalat](http://www.yso.fi/onto/yso/p352)

**Ehdotetut temaattiset ryhmät**

 [56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

 [systeemiteoria](http://www.yso.fi/onto/yso/p13479), [systeemiäly](http://www.yso.fi/onto/yso/p23094)

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9789526500713 ja kaikki vastaavat systeemialkuiset kirjan nimet ja käsitteet

**Ehdottajan organisaatio**

Metayliopisto
**Termiehdotus Fintossa:** [Systeemitiede](http://finto.fi/yse/fi/page/Y512731)

**Comment by Eki2Laitila** [comment]
Tutkimusarkistoissa esim. SemanticScholar-sivustolla on yli 25.000 julkaisua aiheesta Systems science. Suomen yliopistoihin se ei ole vielä kunnolla levinnyt, mutta systeemitiede on ehdottomasti tulevaisuuden tutkimuksen ja kehittämisen kärkeä, sillä tekoälykin liittyy siihen vahvasti. https://www.semanticscholar.org/search?q=%22systems%20science%22&sort=relevance

**Comment by mariaforsen** [comment]
Sanastossa on jo systemvetenskap=tietojärjestelmätiede... onkohan tässä korjattavaa vai mikä suhde näillä on, jos mikään?
https://www.sanakirja.fi/custom/all/systemvetenskap

Sv. systemvetenskap
systemvetenskap (fi. tietojärjestelmätiede) > informationssystem (vetenskaper)
informationssystem (fi. tietojärjestelmät) > informationssystem (tekniska system)

https://www.abo.fi/fi/aineet/tietojarjestelmatiede/
https://www.sanakirja.fi/custom/all/tietoj%C3%A4rjestelm%C3%A4tiede 
https://mau.se/forskning/forskningsamnen/informationssystem/
http://sisa-org.se/informationssystem/

**Comment by mirmaid** [comment]
Sanastossa on mainitut _systeemiteoria_ ja _systeemiäly_, sekä _systeemiajattelu_. LCSH:ssa Systems science on ohjaustermi käsitteelle System theory: http://id.loc.gov/authorities/subjects/sh85131743.

**Comment by Eki2Laitila** [comment]
Olen tutkinut systeemialaa 10 vuotta, ja tunnen sen käsitteistön hyvin. Te ette taksonomiassanne voi poiketa maailmanlaajuuisesta käsitteistöstä, josta on kirjoitettu erittäin paljon. Sellainen asenne olisi denialismia. 
En tunne sanaa tietojärjestelmätiede, vaikka väittelin Informaatioteknologiasta.
Systeemitiede on tiedettä joka käyttää systeemiajattelun ja systeemienteorian menetelmiä.  Taksonomiassanne on kaikenlaista kieroutumista ja väärinkäsitystä eroteltu. Uskokaa nyt edes Wikipediaa: https://en.wikipedia.org/wiki/Systems_science. 

Kuka Teillä tekee päätöksiä tieteen käsitteistöistä? Tulen neuvomaan ja opettamaan hänelle alan perusteita Kaikenteoria-kirjani avulla. Aalto yliopistolla systeemitieteet ovat sivuaine: https://www.aalto.fi/fi/sivuaineet/systeemitieteet-sivuaine

**Comment by mirmaid** [comment]
^ Päätökset hyväksyttävistä termeistä ja muutoksista tekee sanaston ylläpitoryhmä, ks. https://www.kiwi.fi/display/Finto/YSOn+kehityksen+organisointi. Tieteen käsitteissä käytämme lähteinä esim. Tieteen termipankkia, eri alojen sanastoja ja tietosanakirjoja, erikielisiä wikipedia-sivuja, sekä tarvittaessa konsultoimme yliopistojen oppiaineiden henkilökuntaa. Myös edellä mainittu Kongressin kirjaston sanasto ja muut kansainvälisesti käytetyt kirjastoalan sanastot ja luokitukset ovat keskeisiä tiedonlähteitä.

**Comment by Eki2Laitila** [comment]
Tiedättehän, että tiede kehittyy keskustellen, ja termistöjen teossa parhaiden asiantuntijoiden tulee olla yhteyksissä keskenään. Miksi en voi keskustella heidän kanssaan, keneen ottaisin yhteyttä?
Miksi Wikipedia - sivu ei riitä termin hyväksymiseen, jos toisaalla sanastosta löytyy kaikenlaista sukupuolitautiakin ilmiöineen?

Systeemialan tohtorina en osaa arvostaa tahoja, jotka eivät ole valmiita akateemiseen keskusteluun.  Tässä ajankohtainen sivu tähänkin tarkoitukseen (juuri luotu): https://metayliopisto.fi/kaikenteoria/kaikenteoria-maapallon-isot-ongelmat-vaativat-ajattelutapamme-uudistamista-pdf/

**Comment by Eki2Laitila** [comment]
Kansalliskirjaston tulisi nähdä tiede omana alueenaan, johon sovelletaan tieteen tarkastelun periaatteista, ettei se muistuttaisi viihdettä ja kaikenlaista hömppää, jolla ei ole mitään kunnon tarkoitusta. Tieteelle tulee nähdä oma sisäinen taksonomiansa.

Wikipedia on esimerkki siitä, tosin tieteen isot hakemistot, kuten Google Scholar, eivät vielä ole kunnolla organisoituneet, vaan saattavat olla kymmeniä vuosia ajastaan jäljessä. Siksikin tarvitaan systeemitiedettä, että saadaan järjestystä aikaan sen avulla.

Toivottavasti ette suutu mielipiteistäni. Tällainen keskustelu on akateemisissä piireissä jokapäiväistä.

**Comment by mirmaid** [comment]
Eng. ainakin ohjaustermiksi muoto _systems theory_.

**Comment by Eki2Laitila** [comment]
En ymmärrä teidän pohdintaa, koska yksinkertaisia toteamuksia vaan tulee, ilman keskustelua.
Mitä tarkoittaa tuo kommentti? Haluan, että tiede ja systeemitiede tulevat esille ilman sensuuria, koska ne ovat elintärkeitä aiheita Suomenkin menestymiselle. Kuka teillä päättää? Keneen otan yhteyttä?

**Comment by mirmaid** [comment]
Hyväksytty muodossa _systeemitieteet_.

**Comment by Eki2Laitila** [comment]
Tuo "systeemitieteet" ei ole mitenkään pätevä, vaikka Aalto-yliopistolla sitä on käytetty.
Onko teillä termi "matematiikat" käytössä vai "matematiikka", entä fysiikat, psykologiat jne.

Minusta te ette hallitse akateemista keskustelua, vaan pimeästä esitätte faktojanne ilman perusteluja, kuuntelematta alan tohtorin mielipiteitä tai tieteen käsitteitä. 

Tämä FINTO-yhteisö ottaa valtaa itselleen näin yksityiskohtaisissa asioissa, ilman asiantuntemusta. Valtataisteluksiko tämä keskustelu siis meni? Denialismiksi kutsutaan tieteen julkista väheksymistä ja taipumusta aliarvoida tieteen merkitystä.

Muuttakaa termi systeemitieteeksi. Muutoin valitan tästä päätöksestä niiden asiantuntijoiden esimiehille, joilla on vastuu isommastakin tontista kuin tämä.
