### ISSUE TITLE
Bristol

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12738]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Bristol

**Ehdotettu termi ruotsiksi**

Bristol

**Ehdotettu termi englanniksi**

Bristol

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termiä tarvitaan paikkaa käsittelevissä teoksissa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paikkaa käsittelevät matkaoppaat ja sinne sijoittuvat fiktiiviset teokset.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Bristol](http://finto.fi/yse/fi/page/Y512738)

**Comment by jtuohini** [comment]
Tarvinnee tarkenteen, ettei sekoitu esimerkiksi Coloradon tai Pennsylvanian samannimisiin paikkoihin.
