### ISSUE TITLE
tutkimusviestintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12733]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tutkimusviestintä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tutkimusviestintä kattaa tutkimusalan sisäisen viestinnän, alojen välisen viestinnän ja populaarin tiedeviestinnän suurelle yleisölle. Laajempi termi kuin tiedeviestintä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Selkeä kieli, toimivat tekstit : opas asiakastekstien käytettävyyteen

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tutkimusviestintä](http://finto.fi/yse/fi/page/Y512733)

**Comment by mariaforsen** [comment]
Sv. forskningskommunikation?
https://v-a.se/vara-fragor/forskningskommunikation/
"Vetenskaplig kommunikation (scholarly communication) handlar om kommunikation inom akademin/mellan forskare, medan Forskningskommunikation (science communication) beskriver kommunikation om forskning med andra än forskarsamhället."
https://www.vr.se/uppdrag/forskningskommunikation.html
https://termipankki.fi/tepa/fi/haku/tiedeviestint%C3%A4

**Comment by mirmaid** [comment]
2 viitettä Melindassa. Vähän epäilyttää, pysyisikö ero tiedeviestintään selkeänä käytännössä.

**Comment by YSO-kokous** [comment]
Ei oteta tätä omana käsitteenä sanastoon, koska vaikuttaa olevan vahvasti päällekkäinen tiedeviestinnän kanssa. Lisätään kuitenkin ohjaustermi:

tutkimusviestintä KÄYTÄ tiedeviestintä
