### ISSUE TITLE
pelastajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12734]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pelastajat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://pelastustoimi.fi/-/pelastaja-on-monitaitoinen-pelastusalan-ammattilainen

Pelastaja-termi on nykyään laajemmin käytössä pelastusalalla tehtävänimekkeenä kuin palomies ja kuvaa paremmin tehtävän työnkuvaa. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pelastusalaan ja sen henkilöstöön liittyvä aineisto

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pelastajat](http://finto.fi/yse/fi/page/Y512734)

**Comment by mariaforsen** [comment]
Eikö se ole oikeastaan laajempi termi kuin palomies, ks. https://www.pelastusopisto.fi/tutkinnot/pelastajatutkinto/pelastaja/
https://www.hbl.fi/artikel/f8633940-6b62-51d6-bd3c-7c7854b7b0bb
