### ISSUE TITLE
Bath

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12737]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Bath

**Ehdotettu termi ruotsiksi**

Bath

**Ehdotettu termi englanniksi**

Bath, Somerset

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termiä tarvitaan paikkaa käsittelevissä teoksissa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paikkaa käsittelevät matkaoppaat ja sinne sijoittuvat fiktiiviset teokset.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Bath](http://finto.fi/yse/fi/page/Y512737)

**Comment by jtuohini** [comment]
Tarvinnee kaikesta maineestaan huolimatta tarkenteen, ettei vain sekoitu esimerkiksi Illinoisin, Iowan tai Mainen samannimisiin paikkoihin.

**Comment by mirmaid** [comment]
Bath (Englanti)
