### ISSUE TITLE
Kantalinnoitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12739]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kantalinnoitteet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

permanent fortifications

**Tarkoitusta täsmentävä selite**

Pysyväksi rakennettuja varustuksia, joiden tekemiseen tarvitaan ammattitaitoisia rakentajia ja erityismateriaaleja kuten kiveä, betonia tai terästä. (https://akp.nba.fi/wiki;kestolinnoite?s%5b%5d=kantalinnoite)

**Perustelut ehdotukselle**

YSO:ssa tällä hetkellä kenttälinnoitukset, jonka alla virheellisesti Maginot-linja ja Mannerheim-linja. 

Arkeologisen kulttuuriperinnön oppaan mukaan: "Kenttälinnoitteet ovat luonteeltaan tilapäisiä varustuksia ja niistä yhdistettyjä linnoitusjärjestelmiä, joita sotaväen joukot voivat itse rakentaa sodan aikana paikalla löytyvistä materiaaleista käyttämällä yksinkertaisia työkaluja."
https://akp.nba.fi/wiki;kentt%C3%A4linnoitteet

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Kestolinnoitteet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Kantalinnoite), [](https://www.kielitoimistonsanakirja.fi/#/kantalinnoite), [](https://akp.nba.fi/wiki;kestolinnoite?s%5b%5d=kantalinnoite)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://mpkk.finna.fi/Record/taisto.166998?sid=4589797698

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [Kantalinnoitteet](http://finto.fi/yse/fi/page/Y512739)

**Comment by mariaforsen** [comment]
Ja varmaan myös kantalinnoitukset synonyminä? https://www.kielitoimistonsanakirja.fi/#/kanta%20linnoitus?searchMode=all

Sv. permanenta befästningar HT tunga befästningar

**Comment by mirmaid** [comment]
Melindassa 4 x soto-terminä, 3 x vapaana avainsanana.

Kielitoimiston sanakirja: (betonirakentein yms.) erityisen lujaksi rakennettu linnoite, kantalinnoitus.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
