### ISSUE TITLE
Somerset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12736]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Somerset

**Ehdotettu termi ruotsiksi**

Somerset

**Ehdotettu termi englanniksi**

Somerset

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termiä tarvitaan paikkaa käsittelevissä teoksissa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paikkaa käsittelevät matkaoppaat ja sinne sijoittuvat fiktiiviset teokset.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Somerset](http://finto.fi/yse/fi/page/Y512736)

**Comment by jtuohini** [comment]
Kyseessä ei varmaan Bermudan Somerset eikä Marylandin samanniminen piirikunta, joten tarvinnee tarkenteen.
