### ISSUE TITLE
kolmannet maat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12745]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kolmannet maat](http://www.yso.fi/onto/yso/p21755)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

virheellinen wikidatalinkitys (kolmas maailma)

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/kolmas%20maa
https://fi.wikipedia.org/wiki/Kolmas_maailma

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Pitäisikö määritelmää tarkentaa, jos kolmannet maat oikeastaan ovat maat jotka eivät ole EU:n **tai EFTAn** jäseniä?

**Comment by nikopartanen** [comment]
Wikidatassa deprekoitu ja YSOsta linkki poistettu. Voidaan sulkea.
