### ISSUE TITLE
kuunnelmat (käsikirjoitukset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12740]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kuunnelmat (käsikirjoitukset)

**Ehdotettu termi ruotsiksi**

hörspel (manuskript)

**Ehdotettu termi englanniksi**

radio plays 

**Tarkoitusta täsmentävä selite**

SLM-sanastoon, yläkäsitteenä "näytelmät". Fiktiivisen radio-ohjelman käsikirjoitus. 

**Perustelut ehdotukselle**

Tarvitaan kuunnelmatekstien kuvailuun. Lisäksi: nykyiselle "kuunnelmat"-termille sulkutarkenne "radio-ohjelmat". 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCGFT](https://lccn.loc.gov/gf2014026499)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/003092018

**Ehdottajan organisaatio**

Taideyliopiston kirjasto 
**Termiehdotus Fintossa:** [kuunnelmat (käsikirjoitukset)](http://finto.fi/yse/fi/page/Y512740)

**Comment by mariaforsen** [comment]
Sv. päätermi voisi mahdollisesti olla "hörspelsmanuskript" (fi. kuunnelmien käsikirjoitukset)? 
Näytelmät=skådespel olisi ruotsin kannalta väärä yläkäsite. https://www.kielitoimistonsanakirja.fi/#/n%C3%A4ytelm%C3%A4?searchMode=all "puheen **ja** visuaalisen ilmaisun avulla..."

https://www.google.com/search?q=%22kuunnelman+k%C3%A4sikirjoitus%22&sca_esv=8add4daed646876f&sca_upv=1&rlz=1C1JJTC_enFI1095FI1096&ei=-x5PZqvMOc-iwPAPm82ZwA0&udm=&ved=0ahUKEwjrtZ_UzKOGAxVPERAIHZtmBtgQ4dUDCBE&uact=5&oq=%22kuunnelman+k%C3%A4sikirjoitus%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiGyJrdXVubmVsbWFuIGvDpHNpa2lyam9pdHVzIjIIEAAYgAQYogQyCBAAGIAEGKIEMggQABiABBiiBEjuDVCrBljjDHACeACQAQCYAYsBoAHAA6oBAzQuMbgBA8gBAPgBAZgCBqACyQLCAgsQABiABBiwAxiiBMICBxAhGKABGArCAgQQIRgKmAMAiAYBkAYDkgcBNqAHxhE&sclient=gws-wiz-serp

**Comment by mirmaid** [comment]
Seuraava kokous.

**Comment by mirmaid** [comment]
Kuunnelmakäsikirjoitukset?

**Comment by AuHo22** [comment]
Esim. https://www.theseus.fi/bitstream/handle/10024/171358/Riekkola_Solina.pdf;jsessionid=3376A1098FC782796F4FB64B66E89AE8?sequence=1

vrt. elokuvakäsikirjoitukset KT käsikirjoitukset (elokuvat)

**Comment by mirmaid** [comment]
Hyväksytään kuunnelmakäsikirjoitukset KT käsikirjoitukset (kuunnelmat) (SLM).

**Comment by mariaforsen** [comment]
Sv. hörspelsmanuskript HT hörspelsmanus
https://svenska.se/tre/?sok=manuskript&pz=1
https://svenska.se/tre/?sok=manus&pz=1
