### ISSUE TITLE
afrobeat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12743]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

afrobeat

**Ehdotettu termi ruotsiksi**

afrobeat

**Ehdotettu termi englanniksi**

afrobeat

**Tarkoitusta täsmentävä selite**

Piti ihan nipistää itseä, kun huomasin, että YSOssa ei tosiaankaan ole afrobeat-käsitettä. Sen sijaan löytyy kotimainen kummajainen "afro-rock", joka on käsite, jota ei esiinny suomalaisen kirjastokentän ulkopuolisessa maailmassa. Ainakaan siinä merkityksessä, missä sitä on meillä musiikin kuvailussa käytetty, eli siis afrobeat-käsitteen merkityksessä. (Lisäksi näköjään on tässä kontekstissa käytetty myös paremman puutteessa käsitettä "funk" ja vanhemmassa aineistossa toista kummallista YSO-termiä "afro", joka sentään on jo saatu poistettua sanastosta.)

**Perustelut ehdotukselle**

Tuskin kukaan kutsuisi Fela Kutin musiikkia afro-rock:iksi, mutta näin se näköjään on kotimaisessa kuvailussa valitettavasti mennyt. Tässä ratkaisussa ei nyt ikävä kyllä toteudu minkäänlainen kirjallisuustakuu tai käyttäjätakuu. Afrobeat on kenties afrikkalaissyntyisen populaarimusiikin tunnetuin genre, ja siitä käytetään nimenomaan nimitystä afrobeat, ei afro-rock. Tuskin yksikään tiedonhakija hakee Fela Kutin musiikkia hakusanalla "afro-rock". Termi ei vastaa todellisuutta.

**Ehdotettu yläkäsite YSOssa (LT)**

 [populaarimusiikki](http://www.yso.fi/onto/yso/p3064)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [juju](http://www.yso.fi/onto/yso/p29956), [afro-rock](http://www.yso.fi/onto/yso/p29904)

**Vastaava käsite muussa sanastossa**

 [LCSG](http://id.loc.gov/authorities/subjects/sh99011295), [Wikidata](https://www.wikidata.org/wiki/Q388296)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esimerkiksi Fela Kutin, Tony Allenin ja monien muiden tuotanto. Ja vaikkapa tämä kirja:
https://melinda.kansalliskirjasto.fi/byid/018998031

Tässä sen sijaan esimerkki, jossa "afro-rock"-käsitteen käyttö kuvailussa on perusteltu:
https://helmet.finna.fi/Record/helmet.2053062?sid=4594509033

**Ehdottajan organisaatio**

Tuomas / Finto
**Termiehdotus Fintossa:** [afrobeat](http://finto.fi/yse/fi/page/Y512743)

**Comment by tpalonen** [comment]
Ei muuten pidä sotkea genreen _afrobeats_, yhden kirjaimen ero, mutta se on sitten taas eri genre.

Obs! RT _funk_ voisi olla vielä hyvä

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Lisätään termi myös SLM:ään.
Olisiko ehdottajalla tarjota määritelmää?

**Comment by mariaforsen** [comment]
https://id.kb.se/term/sao/Afrobeat

**Comment by tpalonen** [comment]
Ehdotus määritelmästä: 
_Länsi-Afrikassa 1960-luvulla syntynyt musiikkityyli, jossa on vaikutteita funk-, soul- ja jazz-musiikista sekä varhaisemmista länsiafrikkalaisista musiikkityyleistä kuten highlifesta._

Highlife voisi olla hyvä RT myös.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.

**Comment by mariaforsen** [comment]
AASI: Käytetään myös tanssista > tarkenne olisi hyvä YSOssa
https://nuorten.hel.fi/tekemista-ja-paikkoja/harrastuksia/tanssi/afrobeat/

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by YSO-kokous** [comment]
Muutetaan muotoon afrobeat (musiikki).
