### ISSUE TITLE
palomiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12749]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[palomiehet](http://www.yso.fi/onto/yso/p8405)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pelastajat

**Perustelut ehdotukselle**

https://www.pelastusopisto.fi/tutkinnot/pelastajatutkinto/pelastaja/

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11314 ja https://github.com/Finto-ehdotus/YSE/issues/12734

**Comment by mariaforsen** [comment]
Onko kuitenkaan aivan korvattavissa näin  (ja pitäisi varmaan ainakin olla tarkenne)? 
"Pelastajien keskeiset ammattinimikkeet työelämässä ovat pelastaja, palomies tai palomies-ensihoitaja."
/ https://www.pelastusopisto.fi/tutkinnot/pelastajatutkinto/pelastaja/
https://pelastustoimi.fi/pelastustoimi/opiskelemaan
https://pelastustoimi.fi/sv/raddningsvasendet/borja-studera

**Comment by nikopartanen** [comment]
https://pelastustoimi.fi/-/pelastuslaitoksen-tehtavanimikkeet-sukupuolineutraaleiksi-palomiehesta-pelastaja

**Comment by YSO-kokous** [comment]
Kokous kannatti pelastajat-muotoa palomiehet-muodon sijaan. Pohditaan tälle vielä sopiva sulkutarkenne, (pelastusala) tai (palo- ja pelastustoimi) nousivat kokouksessa esiin.

Päätetään sulkutarkenne myöhemmässä kokouksessa.
