### ISSUE TITLE
anomaliat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12744]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[anomaliat](http://www.yso.fi/onto/yso/p37794)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan KT anomaliat -> anomaalisuus

**Perustelut ehdotukselle**

Anomalia ei ole ominaisuus, vaan enemmänkin se asia/olio, joka on anomaalinen, ks.  
- https://fi.wiktionary.org/wiki/anomalia
- https://www.terveyskirjasto.fi/ltt00214

Anomaalisuus on se ominaisuus, mikä hierarkian tässä kohtaa pitäisi olla:
- https://fi.wiktionary.org/wiki/anomaalisuus
- https://www.suomisanakirja.fi/anomaalisuus

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Korrektimpi tapa toimia on varmaan hierakian muuttaminen. 
Ruotsin kannalta en kannata muutosta.

**Comment by mirmaid** [comment]
Olen kyllä samaa mieltä hierarkiasta 🙂. Anomalia on varmaan nykyisessä paikassaan, koska sen sijoittaminen YSOn nykyiseen olio-hierarkiaan on hankalaa - kaikki objektit on jaettu joko fyysisiin tai abstrakteihin. Jos ajatellaan, että fyysisen anomaliankin anomaalisuus on se abstrakti tulkinta poikkeavuudesta, voidaan sitten miettiä, että anomalia = anomaalisuus = ominaisuus. Jos siirretään niin varmaankin YK abstraktit objektit, jossa mm. _virheet_.

**Comment by mirmaid** [comment]
Jätetään nykyiselle paikalleen hierarkiassa, lisätään ohjaustermiksi anomaalisuus.
