### ISSUE TITLE
kitaramusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12746]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kitaramusiikki

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

guitar music

**Tarkoitusta täsmentävä selite**

Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle kitaralle tai muulle kokoonpanolle, jossa kitara on keskeisessä osassa.

**Perustelut ehdotukselle**

YSO:ssa ei ennestään sopivaa asiasanaa, jolla kuvailla kitaramusiikkia käsittelevää aineistoa täsmällisesti.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85057830)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/002282639

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [kitaramusiikki](http://finto.fi/yse/fi/page/Y512746)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT soitinmusiikki

**Comment by mariaforsen** [comment]
Sv. gitarrmusik

**Comment by tpalonen** [comment]
Onko tarpeen rajata? Onko tällä tarkoitus viitata ainoastaan taidemusiikkiin vai sopisiko myös kitaravetoinen pop- ynnä muu musiikki tällä käsitteellä kuvailtavaksi? On olemassa paljon ei-taidemusiikkia soolokitaralle tai eri kokoisille kitarakokoonpanoille. Ja sitten on sellaisia kuin Rhys Chatham ja Glenn Branca, jotka sijoittunevat taidemusiikin ja pop/rock-musiikin rajamaastoon.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite.

Kokous ei nähnyt tarvetta rajata käsitettä millään tavalla eli tulkitaan käsitteen soveltuvan mihin tahansa kitaramusiikkiin.
