### ISSUE TITLE
intermediot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12755]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[intermediot](http://www.yso.fi/onto/yso/p29795)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään SLM:ssä LT-suhde "näyttämömusiikki"-termiin

**Perustelut ehdotukselle**

Kaikki intermediot ovat näyttämömusiikkia ja ainakin lähes kaikki muut näyttämömusiikin alalajit ovat jo ST-suhteisina, joten myös tämän osalta pitäisi suhde huomioida.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
