### ISSUE TITLE
desorptio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12757]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

desorptio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

desorption

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Desorptio
Kemiallinen Desorptio tarkoittaa fysiikassa tai kemiassa adsorption vastakohtaa eli pintaan nousevien atomien, molekyylien tai ionien vapautumista aineen pinnalle tai pintaan kiinnittyneiden molekyylien irtoamisprosessia. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [pintailmiöt](http://www.yso.fi/onto/yso/p3148), [sorptio](http://www.yso.fi/onto/yso/p13396)

**Ehdotetut temaattiset ryhmät**

 [07 Fysiikka](http://www.yso.fi/onto/yso/p26565), [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [adsorptio](http://www.yso.fi/onto/yso/p13395)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 https://doi.org/10.14214/df.341
Biochar as a water protection tool in peatland forestry – nutrient recovery from runoff water.

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [desorptio](http://finto.fi/yse/fi/page/Y512757)

**Comment by mariaforsen** [comment]
Sv. desorption
https://www.rikstermbanken.se/search?q=desorption&s=termer
https://termipankki.fi/tepa/fi/haku/desorption

**Comment by mirmaid** [comment]
GEO-ontologiassa
