### ISSUE TITLE
laparotomia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12754]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laparotomia

**Ehdotettu termi ruotsiksi**

laparotomi

**Ehdotettu termi englanniksi**

laparotomy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 7

**Ehdotettu yläkäsite YSOssa (LT)**

 [lääketieteelliset toimenpiteet](http://www.yso.fi/onto/yso/p2709)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Laparotomy), [FinMeSH](http://www.yso.fi/onto/mesh/D007813)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Complications and outcomes of patients after emergency laparotomy https://urn.fi/URN:ISBN:9789526237909

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [laparotomia](http://finto.fi/yse/fi/page/Y512754)

**Comment by ilona-x** [comment]
Ohjaustermit unohtui laittaa ehdotukseen. FinMeSHissä ohjaustermeinä:
    vatsaleikkaus
    vatsanpeitteiden avaus
    vatsaontelon aukaisu
    vatsaontelon avaus

**Comment by mariaforsen** [comment]
https://mesh.kib.ki.se/term/D007813/laparotomy
