### ISSUE TITLE
Korteela (Jaakkima)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12759]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Korteela (Jaakkima)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [Jaakkima](http://www.yso.fi/onto/yso/p107493)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Korteelan kylä – järven kainaloinen 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Korteela (Jaakkima)](http://finto.fi/yse/fi/page/Y512759)

**Comment by mariaforsen** [comment]
Sv. Korteela (Jakimvaara) HT Kortela (Jakimvaara)

https://sv.wikipedia.org/wiki/Jakimvaara

**Comment by mariaforsen** [comment]
Ei löydy YSO-paikoista?
