### ISSUE TITLE
sosiaalinen konstruktivismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12752]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sosiaalinen konstruktivismi](http://www.yso.fi/onto/yso/p17923)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sosiaalinen konstruktionismi on eri käsite, joten se omaksi YSO termiksi. "Termien käyttö toistensa synonyymeina saattaa kuitenkin herättää hämmennystä muun muassa psykologian ja sosiaalipsykologian kentillä...." lähde: "Sosiaalinen konstruktionismi : miten tarkastella tulkintojen ja todellisuuden sosiaalista rakentumista" S. 20-22. ISBN 978-952-397-045-8

**Perustelut ehdotukselle**

Tarve käyttää ohjaustermiä sosiaalinen konstruktionismi YSOn terminä sisällönkuvailussa.
https://melinda.kansalliskirjasto.fi/byid/018922201 

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto

**Comment by mariaforsen** [comment]
https://www.psykologiguiden.se/psykologilexikon/?Lookup=socialkonstruktivism : "Socialkonstruktivism och socialkonstruktionism är två [termer](https://www.psykologiguiden.se/psykologilexikon/?Lookup=termer) som trots sin likhet används i delvis olika betydelse."

**Comment by mirmaid** [comment]
Jo nyt tämä konstruktivismi/konstruktionismi/sosiaalinen konstruktivismi on vaikea pitää käsissä. Wikipedian mukaan ovat sama asia. Löytyykö jostain määritelmiä, joista ero käy ilmi niin selkeästi, että kuvailijan on mahdollista pitää nämä erillään? Edellä linkitetyssä ero on kyllä ainakin itselleni niin hiuksenhieno, etten tiedä miten erotella kuvailussa muuten kuin sen mukaan, mitä sitten aineistossa on käytetty.

**Comment by YSO-kokous** [comment]
Ei hyväksytä toistaiseksi. Vaikea tehdä eroa muihin keskustelussa mainittuihin käsitteisiin.
