### ISSUE TITLE
spirituaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12756]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[spirituaalit](http://www.yso.fi/onto/yso/p8502)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään SLM:n puolella YSOssa olevat KT-muodot ja vaihdetaan LT-suhde "musiikki" --> "hengelliset laulut (kristinusko)" ja lisätään RT-suhde SLM-termiin "gospelmusiikki"

**Perustelut ehdotukselle**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Toiseksi yläkäsitteeksi kansanlaulut, kuten LC:lläkin.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
