### ISSUE TITLE
poliittinen aktiivisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12751]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

poliittinen aktiivisuus

**Ehdotettu termi ruotsiksi**

politisk verksamhet on jo YSO:ssa

**Ehdotettu termi englanniksi**

political activity

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ehdottaisin tätä RT-termiksi  POLIITTINEN OSALLISTUMINEN termille

**Ehdotettu yläkäsite YSOssa (LT)**

 [osallistuminen](http://www.yso.fi/onto/yso/p10727)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/F/32A6C88NC64XHHA2QE8L622Y2JYJNLV4XP3BDF82KGP1AUXGD2-01301?func=find-acc&acc_sequence=009544978

**Ehdottajan organisaatio**

Tampereen yliopiston kirjasto / TAMK
**Termiehdotus Fintossa:** [poliittinen aktiivisuus](http://finto.fi/yse/fi/page/Y512751)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12750

**Comment by mariaforsen** [comment]
Sv. politisk aktivitet? Ruotsiksi myös https://finto.fi/yso/fi/page/p2646?clang=sv > voisi olla politiskt deltagande tms.

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

Sanastossa on mainitun _poliittisen osallistumisen_ lisäksi jo _poliittinen toiminta_ ja _poliittinen käyttäytyminen_, sekä _puolueaktiivit_ ja _aktivismi_.

_Poliittinen toiminta_ on linkattu LCSH-termiin [Political activity](http://id.loc.gov/authorities/subjects/sh2002011434).

**Comment by YSO-kokous** [comment]
Ei oteta sanastoon uutta käsitettä. Tätä käsitteistöä on sanastossa jo viljalti. Lisätään sanastoon seuraava ohjaustermit.

poliittinen aktiivisuus KÄYTÄ poliittinen osallistuminen
poliittinen aktiivisuus KÄYTÄ poliittinen toiminta

**Comment by mariaforsen** [comment]
Sv. politisk aktivitet > politiskt deltagande
https://id.kb.se/find?q=Political%20participation
