### ISSUE TITLE
maahanlaskut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12765]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maahanlaskut

**Ehdotettu termi ruotsiksi**

luftanfall

**Ehdotettu termi englanniksi**

air assault, air landing

**Tarkoitusta täsmentävä selite**

air assault: A combined-arms assault using firepower and mobility of rotary-wing aircraft to engage adversary forces and/or seize and hold key terrain or objects. (NATOTerm)

air assault: The movement of friendly assault forces by rotary-wing or tiltrotor aircraft  to engage and destroy enemy forces or to seize and hold key terrain. (DOD Dictionary of Military and Associated Terms, November 2021). 

**Perustelut ehdotukselle**

Käsitteelle ei ole vielä kuvaavaa YSO-termiä. Hostomelin lentokentän maahanlasku helmikuussa 2022 teki konseptista laajemmin tunnetun.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sotilasoperaatiot](http://www.yso.fi/onto/yso/p37840)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.018708509
https://finna.fi/Record/arto.018020423
https://finna.fi/Record/taisto.4111

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [maahanlaskut](http://finto.fi/yse/fi/page/Y512765)

**Comment by mariaforsen** [comment]
Minkä perusteella on ehdotettu sv. luftanfall (yleensä fi. ilmahyökkäys tms.)?

Sv. luftlandsättningar
https://www.sanakirja.fi/custom/all/maahanlasku
https://www.sanakirja.fi/custom/all/luftlands%C3%A4ttning
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_518cb95c89f9f371f98831ab6187a7b7&list_id=1&keyword=maahanlasku&word=maahanlasku
https://svenska.se/tre/?sok=luftanfall&pz=8
https://sv.wikipedia.org/wiki/Luftlands%C3%A4ttning
https://www.forsvarsmakten.se/sv/aktuellt/2017/06/att-luftlandsatta-en-bataljon/
https://svenska.se/tre/?sok=luftlands%C3%A4tta&pz=8

**Comment by AnuAlatera** [comment]
Alkuperäinen ruotsinkielinen ehdotus oli virheellinen, luftlandsättning  on oikea termi.

**Comment by mirmaid** [comment]
Tarvitseeko tarkenteen? Samaa sanaa käytetään ainakin hautauksen yhteydessä. Melindassa toistaiseksi vain sotilaallisena, mutta esim. kuva-aineiston kuvailussa virhe olisi mahdollinen (?).

**Comment by YSO-kokous** [comment]
Hyväksytään käsite muodossa maahanlaskut.
