### ISSUE TITLE
maahanlaskujoukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12764]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maahanlaskujoukot

**Ehdotettu termi ruotsiksi**

Luftburna styrkor, luftanfallstyrkor

**Ehdotettu termi englanniksi**

Airborne troops

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSO:n laskuvarjojoukot -käsite ei kuvaa kovin hyvin maahanlaskujoukkoja (esim. Venäjän VDV), jotka tyypillisesti lasketaan ilma-aluksesta (esim. helikopterista) maahan. 

https://www.kielitoimistonsanakirja.fi/#/maahanlasku?source=suggestion&searchMode=all

**Ehdotettu yläkäsite YSOssa (LT)**

 [sotilaalliset organisaatiot](http://www.yso.fi/onto/yso/p3949)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [laskuvarjojoukot](http://www.yso.fi/onto/yso/p3940)

**Vastaava käsite muussa sanastossa**

 [](https://id.loc.gov/authorities/subjects/sh85002729.html), [](https://fi.wikipedia.org/wiki/Maahanlaskujoukot)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.013340409 
https://finna.fi/Record/arto.017560810
https://finna.fi/Record/doria_mpkk.10024_160426

**Ehdottajan organisaatio**

Maanpuolustuskorkeakoulu
**Termiehdotus Fintossa:** [maahanlaskujoukot](http://finto.fi/yse/fi/page/Y512764)

**Comment by mariaforsen** [comment]
Sv. luftlandsättningstrupper HT luftlandsättningsstyrkor
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/luftlands%C3%A4ttningstrupper
https://termipankki.fi/tepa/fi/haku/maahanlaskujoukot
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_013b7442c22f473d1beba2e043715fbd&list_id=1&keyword=joukko&word=joukko
https://www.sanakirja.fi/custom/all/maahanlaskujoukko

**Comment by AnuAlatera** [comment]
Myös tässä virheellinen alkuperäinen ruotsinkielinen ehdotus, kannatamme korjausta.

**Comment by mirmaid** [comment]
Olisiko _laskuvarjojoukot_ siis tämän alakäsite?

**Comment by AnuAlatera** [comment]
Maahanlaskujoukkojen suhde laskuvarjojoukkoihin on assosiatiivinen.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite.
