### ISSUE TITLE
RNA-sekvensointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12768]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

RNA-sekvensointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ehkä myös geenisekvensointi?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/175829

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [RNA-sekvensointi](http://finto.fi/yse/fi/page/Y512768)

**Comment by mirmaid** [comment]
https://www.utupub.fi/handle/10024/175552

**Comment by mariaforsen** [comment]
Sv. genomsekvensering, gensekvensering, RNA-sekvensering?
https://sfmg.se/download/externadokument/patientinformation_genomik/Broschyr-Vad-aCC88r-genomsekvensering.pdf

Suhde tähän https://finto.fi/mesh/fi/page/D017423 ?

**Comment by mirmaid** [comment]
> Suhde tähän https://finto.fi/mesh/fi/page/D017423 ?

En kyllä uskalla sanoa, onko sama vai RT...

YSOssa nyt siis _sekvensointi_ ja _eksomisekvensointi._ Ainakin tuo RNA-sekvensointi tuntuu kuitenkin olevan oma suppeampi toimenpiteensä. https://en.wikipedia.org/wiki/RNA-Seq

**Comment by ilona-x** [comment]
> > Suhde tähän https://finto.fi/mesh/fi/page/D017423 ?
> 
> En kyllä uskalla sanoa, onko sama vai RT...
> 
> YSOssa nyt siis _sekvensointi_ ja _eksomisekvensointi._ Ainakin tuo RNA-sekvensointi tuntuu kuitenkin olevan oma suppeampi toimenpiteensä. https://en.wikipedia.org/wiki/RNA-Seq

Huomasin, että tuon mainitun FinMeSH-termin alakäsitteenä on RNA-seq-tekniikka, joka on englanniksi [RNA-Seq](https://finto.fi/mesh/fi/page/D000081246?clang=en) eli sama kuin tuo Wikipedian termi.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon RNA-sekvensointi.

**Comment by mariaforsen** [comment]
Sv. RNA-sekvensering
https://svenska.se/tre/?sok=rna&pz=8
https://nyheter.ki.se/samarbete-ska-utveckla-helgenomsekvensering-for-patienter-med-akut-leukemi
https://neuroliitto.fi/genominformation-revolutionerar-varden/
