### ISSUE TITLE
maahanmuuttajatausta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12760]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[maahanmuuttajatausta](http://www.yso.fi/onto/yso/p21851)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

vieraskielinen

**Perustelut ehdotukselle**

Tarve korostaa enemmän kielitaustaa kuin lähtömaata henkilöstä puhuttaessa.

**Ehdottajan organisaatio**

Laurea-ammattikorkeakoulu

**Comment by mariaforsen** [comment]
Eli "vieraskielinen tausta"? Eivät toki välttämättä ole sama asia (periaatteessa voi olla maahanmuuttaja jolla ei ole vieraskielinen tausta)

**Comment by mirmaid** [comment]
Voisi olla myös laajemmin _kielitausta_, jos tämä otettaisiin omana käsitteenään. Tässä kaipaisi kyllä aineistoesimerkkiä. Varmaan esim. opetusalalla tärkeä aihe (maahanmuuttajatausta + kielitaito?), mutta tosiaan mikä olisi se toimivin tapa kuvailla, kun oppilaan kielitausta ja maahanmuuttajatausta voivat olla sekä yhdessä että ihan erikseen relevantteja. Ja tosiaan onko kyse edes opetusalasta vai jostain muusta...

**Comment by YSO-kokous** [comment]
Tehdään uusi käsite-ehdotus käsitteestä _kielitausta_.
