### ISSUE TITLE
informaatiolukutaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12761]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[informaatiolukutaito](http://www.yso.fi/onto/yso/p15108)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT informaatiotaidot, vai eri asia?

**Perustelut ehdotukselle**

https://www.utupub.fi/handle/10024/176335

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ruotsiksi on jo "informationsfärdigheter" (informaatiotaidot) ohjausterminä.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
