### ISSUE TITLE
leuddit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12762]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

leuddit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

(Kolttasaamelaiset joiut)

https://www.samimuseum.fi/saamjiellem/suomi/leudd.html

**Perustelut ehdotukselle**

Saimme viestin toimijakuvailuun: "löysin teidän henkilö- sivunne. Luokittelussa on joikaaja. X ei ollut joikaaja vaan leu´ddaaja. Joikaaminen kuuluu läntisiin saamelaisperinteisiin, mutta X oli kolttasaamelainen ja koltat ei joikaa. " Tässä tulee myös ajankohtaiseksi leu´ddaaja AT 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [joiut](http://www.yso.fi/onto/yso/p18242)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Asteritietue (toiminta-ala) 

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [leuddit](http://finto.fi/yse/fi/page/Y512762)

**Comment by jtuohini** [comment]
"Eri saamelaiskielissä on omat nimityksensä joiulle ja joikaamiselle. Ero ei jää pelkästään nimien erilaisuuteen, vaan itse musiikkikin poikkeaa huomattavasti toisistaan. Suurin ero joikutyyleissä on itä- ja länsisaamelaisten välillä. Läntisen alueen voi jakaa vielä pohjoiseen ja eteläiseen alueeseen." (https://fi.wikipedia.org/wiki/Joiku)

Kun tämä Wikipedia-artikkeli käsittelee sekä itä- että länsisaamelaista joikutraditiota (riippumatta niiden saamenkielisistä nimistä), voi vetää johtopäätöksen, että _joikaaja_ voidaan käsittää kattotermiksi minkä tahansa joikutradition edustajalle. Laulajissa ei ole tehty ero edes niinkin erilaisten laulutyylien välille kuin heavy, ooppera tai swing, joten tuntuu hiuksenhalkomiselta tehdä juuri näiden kansanmusiikkityylien osalta, vieläpä niin, ettei suomeksi ole edes eri nimitystä näille (vaan pitäisi käyttää sitaattilainaa).

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta. Sama SLM:ään.
KT leeud'it, leu'ddit
Määritelmä: Kolttasaamelaisten perinteeseen kuuluva laulu.

**Comment by mariaforsen** [comment]
Sv. ? leudd?
https://www.ur.se/mb/pdf/handledningar/205000-205999/205099-2_104562_Samernas_tid_handledning.pdf
https://www.ilposaastamoinen.fi/musiikki/saamelaismusiikki/saamen-musiikki-73-13/1973-2013-saamen-musiikki-ii
https://www.ajtte.com/wp-content/uploads/2019/05/SAMISKT-JOJKARKIV-SLUTRAPPORT.pdf

**Comment by YSO-kokous** [comment]
Hyväksytään käsite. Käytettäväksi termiksi leuʹddit. Yksikkömuoto suomeksi leuʹdd.

Otetaan sanastoon myös kaksi muuta käsitettä:
leuʹddaajat
leuʹddaaminen

Termissä esiintyvä erikoismerkki on kirjoitettu oikein Wikipedia-artikkelissa. Tarkistetaan, että käytetään oikeaa erikoismerkkiä.
https://fi.wikipedia.org/wiki/Leu%CA%B9dd

**Comment by mariaforsen** [comment]
Sv. 
-leu´dd HT leudd
-leu´ddare
-leu´ddande HT leu´ddning

https://www.hbl.fi/2022-11-09/en-resa-till-de-egna-rotterna-fyra-musiker-speglar-skoltsamisk-och-karelsk-kultur-i-varandra/
https://www.ur.se/mb/pdf/handledningar/205000-205999/205099-2_104562_Samernas_tid_handledning.pdf
https://www.ilposaastamoinen.fi/musiikki/saamelaismusiikki/saamen-musiikki-73-13/1973-2013-saamen-musiikki-ii
https://www.ajtte.com/wp-content/uploads/2019/05/SAMISKT-JOJKARKIV-SLUTRAPPORT.pdf
https://www.samer.se/1188
https://abundolive.se/event/stockholm/arktisk_kv%C3%A4ll
https://litteraturbanken.se/ljudochbild/2023/04/26/om-jojkning/
https://varldensfestival.se/samisk-jojk/
https://skellefteamuseum.se/utstallning/storsia/ofredsar-1520-1730/nasafjall/fortvivlan-over-tvangsarbetet-i-nasa-jojk-i-tva-delar-2
-Svenska språkrådet, Isof

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
