### ISSUE TITLE
taloudellinen kestävyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12778]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taloudellinen kestävyys](http://www.yso.fi/onto/yso/p23888)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Economic sustainability käytetympi

**Perustelut ehdotukselle**

Internet

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Muutettu ehdotetusti
