### ISSUE TITLE
geneettinen sukututkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12770]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

geneettinen sukututkimus

**Ehdotettu termi ruotsiksi**

DNA-släktforskning

**Ehdotettu termi englanniksi**

Genetic genealogy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Aiheesta ruvennut ilmestymään yhä enemmän kirjallisuutta ja siitä tehty myös televisio-ohjelmia ym.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sukututkimus](http://www.yso.fi/onto/yso/p18055), [perinnöllisyystiede](http://www.yso.fi/onto/yso/p5147), [DNA-analyysi](http://www.yso.fi/onto/yso/p25695)

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540), [56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544), [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

 geneettinen geneaalogia, DNA-sukututkimus, DNA genealogy, DNA-avusteinen sukututkimus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [DNA-testit](http://www.yso.fi/onto/yso/p25342)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2009007194)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/011321222 ym.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [geneettinen sukututkimus](http://finto.fi/yse/fi/page/Y512770)

**Comment by jtuohini** [comment]
Wikidata-siltaus: https://www.wikidata.org/wiki/Q913584

**Comment by mariaforsen** [comment]
Sv. genetisk släktforskning HT genetisk genealogi, DNA-släktforskning, dna-släktforskning 
https://www.genealogia.fi/genetisk-slaktforskning/
https://education.myheritage.se/article/genetic-genealogy-for-family-history-researchers/
https://svenska.se/tre/?sok=dna&pz=1

**Comment by mirmaid** [comment]
https://www.genealogia.fi/geneettinen-sukututkimus/
https://fi.wikipedia.org/wiki/Geneettinen_sukututkimus

3 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
