### ISSUE TITLE
Viannankoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12775]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Viannankoski](http://www.yso.fi/onto/yso/p109024)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Hierarkia, lisätäänkö niille koskille, jotka yhdistävät järvi, jokin suhde ko. järviin.

**Perustelut ehdotukselle**

Ei voi lisätä jokea yläkäsitteeksi.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ei lisätä.
