### ISSUE TITLE
Likasenoja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12776]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Likasenoja](http://www.yso.fi/onto/yso/p131471)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Hierarkia, lisätäänkö vesistöalue (silloin kun mahdollista)?

**Perustelut ehdotukselle**

xxxx

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ei merkitä puroille yms.
