### ISSUE TITLE
suuri skisma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12777]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

suuri skisma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/176060

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [suuri skisma](http://finto.fi/yse/fi/page/Y512777)

**Comment by jtuohini** [comment]
LCSH:ssa _Great Schism_ KÄ **Schism--Eastern and Western Church** ja **Schism, The Great Western, 1378-1417**.

**Comment by mariaforsen** [comment]
**Tarkenne tai vuosiluvut tarvitaan varmaan suomeksikin**: "Tämä artikkeli käsittelee kristikunnan hajaannusta roomalaiskatoliseksi ja ortodoksiseksi kirkoksi. Roomalaiskatolisen kirkon sisäistä hajaannusta vuosina 1378–1417 käsittelee artikkeli [Suuri skisma (katolisuus)](https://fi.wikipedia.org/wiki/Suuri_skisma_(katolisuus))"
https://fi.wikipedia.org/wiki/Suuri_skisma

Sv. stora schismen (1054) HT öst-västliga schismen, östliga schismen

https://sv.wikipedia.org/wiki/%C3%96stliga_schismen
https://id.kb.se/term/sao/Stora%20schismen%201378-1417
https://sv.wikipedia.org/wiki/%C3%96stliga_schismen
https://sv.wikipedia.org/wiki/V%C3%A4stliga_schismen
"Västliga schismen, även kallad occidentala schismen, stora schismen eller påveschismen, är beteckningen på tiden mellan 1378 och 1417, då det rådde allvarliga meningsskiljaktigheter om successionen inom den latinska kyrkan. Den ska inte förväxlas med den stora schism som ledde till en varaktig åtskillnad av de ortodoxa och romerska kyrkorna."

**Comment by mirmaid** [comment]
Eli olisiko _suuri skisma (1054)_, en oikein keksi mitä muuta tarkennetta voisi käyttää suomeksi, "idän ja lännen kirkot" tms. olisi kovin kömpelö.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite muodossa suuri skisma (1054).
