### ISSUE TITLE
varusmiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12772]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[varusmiehet](http://www.yso.fi/onto/yso/p12919)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään viittausmuoto "varussotilaat"

**Perustelut ehdotukselle**

Ainakin lehdistössä näkyy tätä todella käytetyn, ks. esim. https://www.aamulehti.fi/rikos/art-2000010403985.html ja https://fi.wiktionary.org/wiki/varussotilas

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Myös _varushenkilöt_. Pitäisikö päätermin kanssa vielä odottaa kumpi vakiintuu?

**Comment by LeKorsu** [comment]
Kielitoimiston sanakirjassa varushenkilöt, ei varussotilaita.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermeiksi varussotilaat ja varushenkilöt.
