### ISSUE TITLE
kielimaisemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12771]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kielimaisemat

**Ehdotettu termi ruotsiksi**

språklandskap

**Ehdotettu termi englanniksi**

linguistic landscapes

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kielitieteen, erityisesti sosiolingvistiikan alan käsite, joka vaikuttaa olevan vakiintuneessa käytössä. Sille löytyy englannin- ja ruotsinkieliset vastineet. Englanninkielisen käsitteen "linguistic landscape" ovat määritelleet Rodrigue Landry ja Richard Bourhis vuonna 1997 (tähän viitattiin myös kuvailemassani teoksessa). Käsitettä on kuvailussa vaikea korvata muilla asiasanoilla.

Ks. https://fi.wikipedia.org/wiki/Kielimaisema ja artikkelin englannin- ja ruotsinkieliset vastineet.

**Ehdotettu yläkäsite YSOssa (LT)**

 [sosiolingvistiikka](http://www.yso.fi/onto/yso/p1353)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [monikielisyys](http://www.yso.fi/onto/yso/p6720)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sociolinguistic Variation in Urban Linguistic Landscapes, 978-951-858-870-5

(SKS:n pian ilmestymässä oleva teos.)

**Ehdottajan organisaatio**

Suomalaisen Kirjallisuuden Seura, SKS
**Termiehdotus Fintossa:** [kielimaisemat](http://finto.fi/yse/fi/page/Y512771)

**Comment by mariaforsen** [comment]
Aineistoa riittää, eikä YSOssa tosiaan taida olla mitään termejä millä voisi korvata, kannatan. 

Sv. språklandskap HT språkligt landskap, lingvistiskt landskap 
https://www.abo.fi/centret-for-livslangt-larande/fb1/spraklandskap-berattar-om-mangfalden/
https://sv.wikipedia.org/wiki/Spr%C3%A5klandskap
https://blogs2.abo.fi/sprakligalandskap/lyft-blicken/
https://tidsskrift.dk/sin/article/view/97002
https://research.abo.fi/ws/portalfiles/portal/45229434/Haapam_ki_preprint_0905_1_.pdf

**Comment by mirmaid** [comment]
7 viitettä Melindassa yksikössä. Jotenkin tämä tuntuisi luontevammalta yksiköllisenä (samoin ovat muutkin maisema-termit).

**Comment by nikopartanen** [comment]
Tutkimuksessa jo hyvän aikaa vakiintunut ja käytetty termi.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon yksikkömuodossa eli kielimaisema.
