### ISSUE TITLE
agenttiteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12779]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[agenttiteoria](http://www.yso.fi/onto/yso/p23547)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT päämies-agenttiongelmat / agenttiongelmat, vai erikseen?

**Perustelut ehdotukselle**

https://www.utupub.fi/handle/10024/176062

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ehkä OT riittäisi? 
https://ekonomiivartid.se/ekonomisk-historia/agentteorin.html
https://www.psykologiguiden.se/psykologilexikon/?Lookup=agentteorin

"Agenttiteoria kuvaa päämies-agentti-ongelmaa, jossa päämies palkkaa agentin toimimaan puolestaan." 
/ https://ahtiviita.com/agenttiteoria-kuvaa-paamies-agentti-ongelmaa/
Wikipediassakin näyttää olevan vain yksi termi.

**Comment by AuHo22** [comment]
Myös termejä päämies-agenttisuhteet sekä agenttikustannukset on käytössä - onko tässä aina ongelma kyseessä ja kuinka suppeasta/laajasta asiasta puhutaan? Agenttiteoria lienee teorian lähestymistapa asiaan?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermeiksi: päämies-agenttiongelmat ja agenttiongelmat ja päämies-agenttisuhteet.
