### ISSUE TITLE
Vesikoski (Loimaa)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12774]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vesikoski (Loimaa)](http://www.yso.fi/onto/yso/p125925)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ei varmaan ok kaksi paikkatyyppiä?

**Perustelut ehdotukselle**

xxxx

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tarkennetaan kyläksi.
