### ISSUE TITLE
translaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12782]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

translaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/175817

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [translaatio](http://finto.fi/yse/fi/page/Y512782)

**Comment by jtuohini** [comment]
Tarvinnee tarkenteen, kun _translaatio_ on myös kirkollinen käsite (pyhäinjäännösten juhlallinen siirto).

**Comment by mariaforsen** [comment]
Translaatio (biologia)? Liittyykö tähän: https://finto.fi/mesh/fi/page/D014176 ?
https://fi.wikipedia.org/wiki/Translaatio_(biologia)
Vrt. https://termipankki.fi/tepa/fi/haku/translaatio

Sv. translation (biologi)
https://www.rikstermbanken.se/search?q=translation&s=termer

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa translaatio (biologia).
