### ISSUE TITLE
transaktiokustannukset / transaktiokustannusteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12780]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

transaktiokustannukset / transaktiokustannusteoria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/176062

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [transaktiokustannukset / transaktiokustannusteoria](http://finto.fi/yse/fi/page/Y512780)

**Comment by ilona-x** [comment]
LCSH: Transaction costs http://id.loc.gov/authorities/subjects/sh85136870

---

Wikidata: Transaction cost theory  http://www.wikidata.org/entity/Q20820098

---

Tieteen termipankki

fi      transaktio kustannukset
en      transaction costs

määritelmä
tuotteiden omistusoikeuksien ja vastuiden siirtymisen aiheuttamia kuluja

selite
Transaktiot aiheuttavat kustannuksia, joiden määrän on arvioitu olevan jopa yli puolet tuotteen kokonaiskustannuksista. Transaktiokustannukset koostuvat mm. markkinoiden tarjonnan selvittämisestä, vaihdannan sopimuskustannuksista ja mahdollisten ristiriitojen sovittelukustannuksista.

  
Lähde: Tieteen termipankki 03.08.2023, Taloustiede:transaktio_kustannukset https://termipankki.fi/tepa/fi/haku/transaktiokustannukset
	  
---

IATE2

fi        liiketoimikustannukset (★★★☆);
kaupankäyntikulu (★★★☆);
transaktiokustannukset (★★★☆)

sv       transaktionskostnader (★★★☆);
transaktionskostnad (★★★☆)

en      transaction costs (★★★☆)

	  
Lähde: IATE 01.08.2023, Euroopan unioni (1113111) Tieteen termipankki https://termipankki.fi/tepa/fi/haku/transaktiokustannukset

**Comment by mariaforsen** [comment]
Sv. transaktionskostnader
https://id.kb.se/term/sao/Transaktionskostnader

**Comment by mirmaid** [comment]
Melindassa transaktiokustannukset n. 20 kertaa, -teoria n. 10 kertaa.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa transaktiokustannukset.
