### ISSUE TITLE
jom kippur

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12786]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jom kippur

**Ehdotettu termi ruotsiksi**

jom kippur

**Ehdotettu termi englanniksi**

yom kippur

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Juutalaisten juhlapäivä

**Ehdotettu yläkäsite YSOssa (LT)**

 [uskonnolliset juhlat](http://www.yso.fi/onto/yso/p9055)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [SAO](https://id.kb.se/term/sao/Yom%20Kippur), [LCSH](http://id.loc.gov/authorities/subjects/sh85149210)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The fast : the history, science, philosophy, and promise of doing without / John Oakes.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [jom kippur](http://finto.fi/yse/fi/page/Y512786)

**Comment by AuHo22** [comment]
Tarvitseeko tarkenteen, jom kippur -juhla tms.? vrt. jom kippur -sota, LC Israel-Arab War, 1973

**Comment by YSO-kokous** [comment]
Otetaan käsite sanastoon muodossa jom kippur (juhla).

**Comment by mariaforsen** [comment]
Sv. jom kippur HT yom kippur, försoningsdagen (judendom)
https://www.isof.se/lar-dig-mer/kunskapsbanker/lar-dig-mer-om-arets-namn-och-handelser/handelser/jom-kippur
https://svenska.se/tre/?sok=jom+kippur&pz=1
