### ISSUE TITLE
selkeä kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12783]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

selkeä kieli

**Ehdotettu termi ruotsiksi**

klarspråk

**Ehdotettu termi englanniksi**

plain language

**Tarkoitusta täsmentävä selite**

"Selkeä kieli on yleiskieltä, joka on kielenhuollon suositusten mukaista eikä sisällä erikoiskielten sanastoa."
https://www.kotus.fi/nyt/kotus-blogi/minna_pyhalahti?17245_m=21357
https://www.saavutettavasti.fi/verkkosisaltojen-saavutettavuus/selkea-kieli/
https://sales.sfs.fi/fi/index/tuotteet/SFS/ISO/ID2/2/1304684.html.stx

**Perustelut ehdotukselle**

Tarvitaan kuvailussa, aineistoa tulee koko ajan enemmän tästä aiheesta. Olisi tärkeää että juuri tästä aiheesta voisi tehdä aihehakuja. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [kieli ja kielet](http://www.yso.fi/onto/yso/p556)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

 selkeä yleiskieli, klartext

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kielenhuolto](http://www.yso.fi/onto/yso/p4640), [virkakieli](http://www.yso.fi/onto/yso/p8563), [oikeakielisyys](http://www.yso.fi/onto/yso/p4642)

**Vastaava käsite muussa sanastossa**

 [](https://id.kb.se/term/sao/Klarspr%C3%A5k), [Wikipedia](https://en.wikipedia.org/wiki/Plain_language), [Tieteen termipankki](https://tieteentermipankki.fi/wiki/Selkokielen_tutkimus:selke%C3%A4_yleiskieli), [IATE ](https://iate.europa.eu/entry/result/1609102/all), [SAO](https://id.kb.se/term/sao/Klarspr%C3%A5k)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Selkeä kieli, toimivat tekstit /Eeva Öörni
Selkeä kieli. Osa 1, keskeiset periaatteet ja ohjeet = Plain language. Part 1, governing principles and guidelines / SFS Suomen standardit.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [selkeä kieli](http://finto.fi/yse/fi/page/Y512783)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/3830

**Comment by mirmaid** [comment]
3 x Melindassa

https://valtioneuvosto.fi/-//1410829/selkea-kieli-on-oikeudenmukaista

**Comment by AuHo22** [comment]
Itse voisin kannattaa muotoja selkeäkielisyys (vrt. oikeakielisyys) tai selkeä yleiskieli (kansalaisille tarkoitetussa viestinnässä)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa selkeäkielisyys. Ohjaustermeiksi selkeä kieli ja selkeä yleiskieli.

**Comment by mariaforsen** [comment]
Sv. klarspråk HT klarspråkighet, klartext, klart allmänspråk
