### ISSUE TITLE
liikehäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12787]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

liikehäiriöt

**Ehdotettu termi ruotsiksi**

rörelsestörningar

**Ehdotettu termi englanniksi**

movement disorders

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Liikeh%C3%A4iri%C3%B6

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 liikehäiriösairaudet

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [Parkinsonin tauti](http://www.yso.fi/onto/yso/p294)

**Vastaava käsite muussa sanastossa**

 [MeSH](http://www.yso.fi/onto/mesh/D009069)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/urn:isbn:9789526237718
Deep brain stimulation in Parkinson’s disease and paediatric DBS service.

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [liikehäiriöt](http://finto.fi/yse/fi/page/Y512787)

**Comment by mariaforsen** [comment]
Sv.  rörelsestörningar HT rörelserubbningar
https://mesh.kib.ki.se/term/D009069/movement-disorders
https://id.kb.se/term/sao/R%C3%B6relserubbningar

Movement disorders • lcsh

**Comment by mirmaid** [comment]
Lääketieteen termit:
 
**liikehäiriö**: 1. motor disturbance, motorisk störning | lihastoiminnan säätelyhäiriöstä johtuva liikkeiden epätarkoituksenmukaisuus tai vajavuus, esim. silmien liikehäiriö; vrt. dyskinesia; 2. disorder of motility, störd motilitet | ruuansulatuskanavan lihaksiston toimintahäiriö, esim. ruokatorven liikehäiriö ja sappitiedyskinesia; 3. movement disorder, rörelsestörning ‑en | neurologisesta sairaudesta johtuvia lihastoiminnan ja liikkumisen häiriöitä; vrt. pakkoliike; ks. myös liikehäiriösairaus, silmänliikehäiriö

**liikehäiriösairaus**: movement disorder, rörelsesjukdom ‑en →liikehäiriöitä (3) aiheuttavien neurologisten sairauksien (esim. parkinsonismi, Huntingtonin tauti, Touretten oireyhtymä) yhteisnimitys

**Comment by mirmaid** [comment]
Melindassa muodoissa liikehäiriö/-häiriöt erilaisissa lähinnä kai neurologisissa sairauksissa.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon käsite liikehäiriöt. Otetaan tämä sanastoon laajalla tulkinnalla eli voidaan käyttää erilaisissa tapauksissa.

**Comment by mariaforsen** [comment]
Linkityskohteet: 
https://en.wikipedia.org/wiki/Movement_disorder 
LC https://id.loc.gov/authorities/subjects/sh85088017.html
Myös meshissä Movement Disorders
