### ISSUE TITLE
mediatutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12788]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mediatutkimus](http://www.yso.fi/onto/yso/p14168)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään käsitteeseen mediatiede

**Perustelut ehdotukselle**

Ero on epäselvä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/81

**Comment by mariaforsen** [comment]
SAOssa https://id.kb.se/term/sao/Medie-%20och%20kommunikationsvetenskap

**Comment by YSO-kokous** [comment]
Konsultoimme Yleä tässä. Seuraavaan kokoukseen.

**Comment by LeKorsu** [comment]
Ysossa on nyt nämä alan tutkimukseen liittyvät käsitteet:
journalistiikka / journalistikvetenskap / journalism studies (melinda 150 yso-käsitettä)
mediatutkimus / medieforskning / media studies (melinda: 1952)
mediatiede / medievetenskap / media science (melinda: 215)
tiedotustutkimus / massmedieforskning / communications research (melinda: 1237)
tiedotusoppi / kommunikationslära / communications theory (melinda: 294)
viestintätutkimus / kommunikationsforskning / communication studies (melinda: 424)

Selasin läpi mediatiede-asiasanan sata ensimmäistä viitettä. Niistä puolessa sitä oli käytetty yhdessä mediatutkimuksen, viestintätutkimuksen ja/tai tiedotustutkimuksen kanssa. 
Ne viitteet, joissa mediatiede oli ainoa yllämainituista asiasanoista, suuri enemmistö käsitteli Lapin yliopiston mediatieteen graduja, väikkäreitä, opettajia tai opiskelijoita.
Sitten oli joitakin pelitutkimukseen liittyviä viitteitä, saksankielisiä Mediewissenschaft-sanakirjoja ja joissakin viitteissä käytetty mediatiede oli oman käsitykseni väärä asiasana (Mediewissenschaft ei ole journalistiikkaa/tiedotusoppia). 

Mediatieteen käsite on tullut Suomeen Saksasta (Medienwissenschaft) 
https://www.kaleva.fi/friedmann-mediatiede-ja-aistien-historia/2306031
“Mediatieteellä tarkoitetaan humanistis-kulttuurista, viestintää ja ilmaisua tutkivaa oppiainetta, jota Saksassa kutsutaan nimellä Medienwissenschaft. Mediatieteen perusajatuksen mukaan mediat eivät ole vain teknisiä välineitä ulkopuolellamme vaan ne muovaavat jatkuvasti ajattelumme ja havaintomme muotoja. Vuorovaikutus kulttuuriympäristön, esittämisen tapojen ja havainnon muotojen välillä on mediatieteen perusajatus.”

Mediatiede on oppiaineena  Suomessa vain Lapin yliopistossa.
Mauri Ylä-Kotola: Mediatieteen kysymyksiä 1 (1999): “Lapin yliopiston ‘mediatiede’ (Media Studies [LK huom! käännös]) on määritelty humanistiselta ja kulttuurintutkimukselliselta pohjalta lähteväksi monitieteiseksi tutkimusalaksi, joka kuuluu taideteollisen tutkintoasetuksen piiriin” 
mediatiede wikipediassa: https://fi.wikipedia.org/wiki/Mediatiede

Mediatutkimus on oppiaineena Turun yliopistossa ja nykyään myös Tampereen yliopistossa

Kysyin käsitteiden erosta  professori Anu Koivuselta, johon olen tutustunut hänen tehdessään tutkimustyötä Yle 100 -juhlavuoden tutkimushankkeen parissa. 
Koivunen: 
Mediatieteen käsite tulee Saksasta – Medienwissesschaft - ja jos en väärin muista Vaasan yliopistossa pitkään vaikuttanut professori Tarmo Malmberg on kirjoittanut tästä pitkiä artikkeleita. Ylä-Kotola ja Hannu Eerikäinen Lapin yliopistossa linkittäneet siihen. Tunnen sikäläisiä keskusteluja huonosti, mutta Saksa keskeinen referenssi käsitteelle.

Media studies/mediatutkimus käsite otettiin Turussa alanimikkeeksi vuoden 2000 tienoossa, kun silloinen viestinnän sivuaine ja elokuva- ja tv-tieteen pääaine yhdistettiin. Käsite kertoo siis humanistisen ja kulttuurintutkimuksellisen median tutkimuksen ja yhteiskuntatieteellisen joukkoviestinnän – ja tuolloin myös puheopin - yhdistämisestä.

Tuohon mediaTIEDE sanaan liittynee Lapin yliopistossa profiloituminen, koska siellä tieteiden ja taiteiden tutkinnot jotenkin samassa.”

Koivusen mainitsema Tarmo Malmberg on muuten yhden artikkelinsa tiivistelmässä suomentanut Mediewissenschaftin mediafilosofiaksi
https://journal.fi/mediaviestinta/article/view/62853
“mediafilosofia – eli saksalaisittain Medienwissenschaft – muuttamassa alan intellektuaalista tyyliä”

mediatutkimus wikipediassa  https://fi.wikipedia.org/wiki/Mediatutkimus

Summa summarum: 
Minun nähdäkseni mediatutkimus ja mediatiede ovat sen verran läheisiä käsitteitä, että ne voidaan hyvin yhdistää siten, että mediatutkimus olisi käytettävä käsite, ellei sitten mediatiedettä tarvita tomijakuvailussa tms., jossa oppiaineet voivat olla tärkeitä. (minulla ei ole pääsyä RDA-toolkittiin, ja meikäläisen rda-tietous on mallioppimista, joten en ole ollenkaan varma, onko yso-käsitteillä merkitystä tässä.)

Marian linkkaama sao-käsite, jossa on yhdistetty media- ja viestintätutkimus olisi kompakti yhteiskäsite, mutta niin isoon muutokseen tuskin on kannattavaa lähteä.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta mediatiede.
Lisätään ohjaustermi: mediatiede KÄYTÄ mediatutkimus.
Hierarkisoidaan mediatutkimus tieteenalat-hierarkiaan.

**Comment by mariaforsen** [comment]
Sv. medievetenskap > - ANV medieforskning HT mediaforskning, mediavetenskap 
Jfr https://id.kb.se/term/sao/Medie-%20och%20kommunikationsvetenskap
https://www.rikstermbanken.se/search?q=medievetenskap&s=termer
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_64d1a51a8dfc0ef58efbd43edd51b5bd&list_id=1&keyword=mediatutkimus&word=mediatutkimus
https://www.sanakirja.fi/custom/all/mediatutkimus
https://svenska.se/tre/?sok=medieforskning&pz=1
