### ISSUE TITLE
ympäristövastuu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12796]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ympäristövastuu](http://www.yso.fi/onto/yso/p14214)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi ekologinen vastuu

**Perustelut ehdotukselle**

https://www.ykliitto.fi/sites/ykliitto.fi/files/yritysvastuun_sanakirja.pdf
LCSH: environmental responsibility KT ecological responsibility http://id.loc.gov/authorities/subjects/sh93002599

**Ehdottajan organisaatio**

kk/il

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
