### ISSUE TITLE
hyperemeesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12794]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hyperemeesi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 hyperemesis gravidarum

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/174542

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [hyperemeesi](http://finto.fi/yse/fi/page/Y512794)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Morning sickness**](http://id.loc.gov/authorities/subjects/sh92006613).

**Comment by jtuohini** [comment]
Eli onko asiasana itse asiassa samaa asiaa kuvaava kuin YSO:ssa jo oleva [**raskauspahoinvointi**](http://www.yso.fi/onto/yso/p26717)?

**Comment by mariaforsen** [comment]
Vrt. https://finto.fi/mesh/fi/search?clang=fi&q=hyperemesis&vocabs= 

Tässä oli varmaan tarkoitus saada erillinen termi vakavalle ja hoitoa vaativalle raskauspahoinvoinnille? https://hyperemeesi.fi/fi/tietoa-hyperemeesista/mita-hyperemeesi-on/#erot-taulukko

Sv. hyperemesis HT hyperemesis gravidarum, extremt graviditetsillamående, svårt graviditetsillamående
/uppslagsverk/encyklopedi/lång/hyperemesis
https://mesh.kib.ki.se/term/D006939/hyperemesis-gravidarum
https://sv.wikipedia.org/wiki/Hyperemesis_gravidarum
https://www.terveyskyla.fi/sv/kvinnohuset/graviditet/problem-under-graviditeten/svart-graviditetsillamaende
https://www.1177.se/barn--gravid/graviditet/graviditetsbesvar-och-sjukdomar/graviditetsillamaende/

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D006939

_Oireiston ääripää, hyperemesis gravidarum eli hillitön raskausoksentelu, on puolestaan huomattavasti harvinaisempi tila, jonka esiintyvyys on eri lähteiden mukaan 0,3-3 %. Tällöin hillitön oksentelu johtaa kuivumiseen ja elektrolyyttihäiriöihin, vajaaravitsemukseen ja painon vähenemiseen. Tila vaatii usein sairaalahoitoa._ https://www.duodecimlehti.fi/duo15039

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
