### ISSUE TITLE
kehitysmaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12793]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kehitysmaat](http://www.yso.fi/onto/yso/p17004)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

kehittyvät maat

**Perustelut ehdotukselle**

englanniksi puhutaan kehittyvistä maista ja termi kehitysmaat ei ole sopiva kaikissa tilanteissa.

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12281 ja muut samaan liittyvät

**Comment by YSO-kokous** [comment]
Käsitteelle on lisätty jo huomautus, jossa tunnistetaan kehitysmaat-termin ongelmallisuus (ks. infoikoni termin yhteydessä). Termi on edelleen käsitteen käytettävä termi, koska se näyttää olevan vakiintunein ja yleisin termi aiheelle.

Asia liittyy viime vuonna YSOa varten laadittuihin kulttuurisensitiivisyyslinjauksiin, joista löytyy tietoa mm. täältä:
https://www.kiwi.fi/pages/viewpage.action?pageId=371491272
https://tietolinja.kansalliskirjasto.fi/2-2023/ajankohtaista-meilta-ja-muualta/

Toistaiseksi ei nähdä tarvetta muutokselle, mutta seurataan tilannetta.
