### ISSUE TITLE
kestävä johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12797]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kestävä johtaminen](http://www.yso.fi/onto/yso/p20425)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT kestävyysjohtaminen?

**Perustelut ehdotukselle**

xxxx

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
https://wwf.fi/opettajille/koulutukset/me-tulevaisuudentekijat-avaimia-kestavyysjohtamiseen/
https://kestavyys.hel.fi/strategista-kestavyysjohtamista/

**Comment by mariaforsen** [comment]
Onko välttämättä sama asia, jos kestävä johtaminen on "Kestävän johtamisen voidaan ajatella olevan toimintaa, jolla edistetään työyhteisön hyvinvointia ja liiketoiminnan kannattavuutta ottamalla huomioon sekä yksilön, että organisaation tarpeet."?
https://www.kosek.fi/teema/kestavasta-johtajuudesta-hyotyvat-kaikki-tyontekija-tyonantaja-ja-lopulta-itse-tyo/
Vrt. https://ymparistojamieli.fi/uudistava-regeneratiivinen-johtajuus-kestavyysjohtamisen-uusi-aikakausi/

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä.
