### ISSUE TITLE
siRNA

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12791]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

siRNA

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/174337

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [siRNA](http://finto.fi/yse/fi/page/Y512791)

**Comment by mariaforsen** [comment]
Sv. siRNA HT small interfering RNA
https://mesh.kib.ki.se/term/D034741/rna-small-interfering
https://www.genteknik.se/ordlista/sirna/

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D034741

11 x Melindassa
