### ISSUE TITLE
korvatorvet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12799]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

korvatorvet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/175984

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [korvatorvet](http://finto.fi/yse/fi/page/Y512799)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D005064

**Comment by mariaforsen** [comment]
Sv. örontrumpeter HT eustachiska röret
