### ISSUE TITLE
asikloviiri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12792]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

asikloviiri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/174337

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [asikloviiri](http://finto.fi/yse/fi/page/Y512792)

**Comment by mariaforsen** [comment]
Sv. aciklovir
uppslagsverk/encyklopedi/lång/aciklovir
https://sv.wikipedia.org/wiki/Aciklovir
