### ISSUE TITLE
delirium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12790]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[delirium](http://www.yso.fi/onto/yso/p10962)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT sekavuus(tila)

**Perustelut ehdotukselle**

xxxx

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. HT förvirringstillstånd, konfusion
https://www.terveyskyla.fi/sv/operationshuset/information-om-intensivvard/symtom-och-fenomen-i-anslutning-till-intensivvard/behandling-av-delirium-forvirringstillstand-pa-intensivvardsavdelning
https://www.psykologiguiden.se/psykologilexikon/?Lookup=delirium

**Comment by AuHo22** [comment]
https://www.terveyskirjasto.fi/dlk00357
Sekavuustila (delirium)

**Comment by LeKorsu** [comment]
Peukku KT sekavuustila

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermeiksi sekavuus ja sekavuustila.
