### ISSUE TITLE
Grignardin reagenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12804]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Grignardin reagenssi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Grignard reagent

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Grignardin_reagenssi

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Grignardin_reagenssi

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Korvola, Jorma: Grignard additions of methylmagnesium iodide to fenchone and dehydrofenchone : Configurations of 1,2,3,3-tetramethylnorbornan-2-ols and 1,2,3,3,-tetramethyl-5-norbornen-2-ols.
951-677-027-4

**Ehdottajan organisaatio**

Jyväskylän yliopisto
**Termiehdotus Fintossa:** [Grignardin reagenssi](http://finto.fi/yse/fi/page/Y512804)

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85057347

5 kertaa Melindassa englanniksi.

**Comment by mariaforsen** [comment]
Sv.  Grignardreagens HT Grignardreagenser, Grignards reagens 
https://www.kva.se/app/uploads/2022/06/Documents-Priser-Nobel-2010-Kemi-popkesv10.pdf
https://svenska.se/tre/?sok=reagens&pz=1
