### ISSUE TITLE
Balderin talo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12807]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Balderin talo

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [rakennukset](http://www.yso.fi/onto/yso/p1786)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Balderin_talo)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Elämää Balderin talossa

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Balderin talo](http://finto.fi/yse/fi/page/Y512807)

**Comment by mariaforsen** [comment]
Sv. Balders hus (Helsingfors)
