### ISSUE TITLE
Suuri rantatie

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12806]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Suuri rantatie](http://www.yso.fi/onto/yso/p107306)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

On ainakin osittain sama asia kuin Kuninkaantie.

**Perustelut ehdotukselle**

https://kuninkaantie.fi/fi/kuninkaantie-on-suomen-kolmanneksi-vanhin-tieyhteys/
https://www.vantaansanomat.fi/paikalliset/2465789
https://vantaaseura.fi/site/assets/files/1521/helsingin_pitaja_-_vantaa_2019_-majuri.pdf
https://www.visitkingsroad.fi/fi/info-2/yhdistys-foreningen/

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Yhdistetään, KT Suuri rantatie.
