### ISSUE TITLE
viruskuljetin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12801]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

viruskuljetin

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

viral vector

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Viral_vector
Viral vectors are modified viruses designed to deliver genetic material into cells. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-61-4990-5
Next-generation AAV vectors :improved vector production and regulated expression 

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [viruskuljetin](http://finto.fi/yse/fi/page/Y512801)

**Comment by mirmaid** [comment]
Lääketieteen termit:

**virusvektori:** virus jota käytetään DNA:n viemiseen elävän organismin tai soluviljelmän soluihin

**Comment by mirmaid** [comment]
YSOssa on _vektorit (biologia)_ KT geenikuljettimet

https://tieteentermipankki.fi/wiki/Nimitys:geenikuljetin
https://tieteentermipankki.fi/wiki/Biotekniikka:geenivektori

**Comment by mariaforsen** [comment]
Sv. virusvektorer, virala vektorer
https://www.genteknik.se/ordlista/virusvektor/
https://termipankki.fi/tepa/fi/haku/viral%20vector
https://www.solunetti.fi/fi/solubiologia/virusvektorit/2/

Jos vektori voi olla myös esim. eläin tms. jolla tartunta leviää (näin ainakin ruotsiksi), niin se on kieltämättä aika kaukana tästä virusvektorista? Olisiko tämä alakäsite suhteessa siihen?

**Comment by FinMeSHienPaimentaja** [comment]
Näin perinnöllisyystiedettä pääaineena opiskelleena "virusvektorit" kuulostaa tosi tutulta, olkoonkin, että "viruskuljetin" sinänsä merkitykseltään sama, josko sillä tarkoitetaan virusta, joka kuljettaa geenejä/nukleiinihappopätkiä. Voiko sekaantua virusten 'kuljettimeen'...?

**Comment by mirmaid** [comment]
AFOssa on myös virusvektorit, mutta sitä on käytetty päinvastoin, eli kun jokin toimii vektorina kasvitautia aiheuttavalle virukselle. 

Geenivektorit kattaisi myös virusvektorit, toisaalta vaikka AFO-termiä on Melindassa käytetty tuossa taudinkantaja-merkityksessä, Googlella tätä tulee olemattoman vähän. Ja tarkennekin on mahdollista lisätä. 

Sekin kyllä tulee mieleen, pitäisikö nämä erotella tarkemmin, esim. (biologia) > (epidemiologia)?

**Comment by YSO-kokous** [comment]
Muutetaan vektorit (biologia) -käsite rajaamaan pelkkään epidemologiaan.

Otetaan uutena käsitteenä sanastoon geenivektorit TAI geenikuljettimet. Sulkutarkenteeksi kenties geenitekniikka. Aatos oli, että käsitteen olisi hyvä kattaa virusvektorit.

YSO-ylläpito tutkii termimuotoja itsenäisesti ja tekee päätöksen autokraattisesti.

**Comment by mariaforsen** [comment]
Sv. 
-vektorer (biologi) > vektorer (epidemiologi)
-genvektorer HT virusvektorer, virala vektorer
https://www.sanakirja.fi/custom/all/geenivektori
https://termipankki.fi/tepa/fi/haku/geenivektori
