### ISSUE TITLE
uususkonnollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12803]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[uususkonnollisuus](http://www.yso.fi/onto/yso/p16664)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi uushenkisyys

**Perustelut ehdotukselle**

Käytössä esim. väitöskirjassa https://urn.fi/URN:ISBN:978-951-51-9479-4

"Kristinuskon kannalta uususkonnollisuus (on myös käytetty sanaa ”uushenkisyys”) tarkoittaa sellaisia uskonnollisia ilmiöitä, joita ei ole totuttu kohtaamaan perinteisesti kristinuskon vaikutuspiirissä."
https://evl.fi/sanasto/uususkonnollisuus-uususkonnot/

**Ehdottajan organisaatio**

KK/HR

**Comment by AuHo22** [comment]
Kotimaisten kielten sanakirja (ei termiä uususkonnollisuus):
**uushenkisyys**
yhteisnimitys mm. Aasian uskonnoista vaikutteita saaneille, kunkin yksilön omaa henkistä kokemusta korostaville elämänkatsomuksille; vrt. new age
Esimerkki: Jooga ja vaihtoehtoiset hoitomuodot uushenkisyydessä

**Comment by krinay** [comment]
Jos _uushenkisyys_ lisätään ohjaustermiksi termille _uususkonnollisuus_, pitäisikö se lisätä ohjaustermiksi myös termille _henkisyys_?

Kirjassa _Uushenkisyys_ (SKS 2022) (https://melinda.kansalliskirjasto.fi/byid/018650904) ei juurikaan puhuta uususkonnollisuudesta, mutta uushenkisyydestä käytetään usein lyhyempää muotoa henkisyys. Kirjassa määritellään uushenkisyyttä monella tavalla, johdannossa mm. näin:
"Tässä teoksessa rajaamme tarkastelumme uushenkisyys-käsitteellä nimeämäämme ilmiöön, josta englanniksi puhutaan termeillä spirituality tai new spiritualities. " ja 
"Uushenkisyys onkin eräänlainen sateenvarjotermi, jolla voidaan viitata hyvin monenlaisiin asioihin. Viitattuja asioita ja ilmiöitä yhdistävät kuitenkin tietyt painotukset, kuten individualismi eli yksilöllisyys, eklektisyys eli se, että ammennetaan aineksia useista eri perinteistä, sekä progressio eli pyrkimys henkiseen kasvuun, kehitykseen ja muutokseen--"

**Comment by AuHo22** [comment]
Käsitteestä esim. myös seuraavassa rajaten sitä myös rajatietoon sekä new age -liikkeeseen;  uushenkisyys kuitenkin tuntuisi olevan ns. moderni virtaus, henkisyyttä kuitenkin on ollut kaikkina aikoina ja on siten paljon laajempi käsitteenä ja ilmiönä.

https://dialogi.diak.fi/2022/09/13/elamani-kasittee-uushenkisyys/
https://www.humak.fi/blogit/uushenkisyyden-nousu-trenditiistai-blogisarja-osa-3/

**Comment by mariaforsen** [comment]
Vastaava sv. nyandlighet on jo ohjaustermi uususkonnollisuudelle/nyreligiositet.

**Comment by krinay** [comment]
Tieteen termipankki (uskontotiede): [uushenkisyys](https://tieteentermipankki.fi/wiki/Uskontotiede:uushenkisyys)
"1960- ja 1970-luvuilla länsimaisen vaihtoehtokulttuurin vaikutuspiirissä syntynyt, moninaisin tavoin ilmenevä henkisyyden muoto, jossa keskiössä ovat yksilön omat kokemukset ja jossa sekoitetaan näkemyksiä ja harjoitteita eri uskonnoista vastaamaan yksilön henkisiä tarpeita ja kehitystä nykyhetkessä."  Selitteessä lisää määrittelyä.

Uususkonnollisuuden ohjausterminä on _uudet uskonnolliset liikkeet_ ja englanninkielisenä vastineena _new religious movements_. 

Vivahde-ero uususkonnollisuuden ja uushenkisyyden välillä liittyy kaiketi mm. eroihin institutionaalisuuden asteessa, siihen kuinka organisoidusta uskonnollisuudesta on kyse. Ja toisaalta siihen, kuinka yksilökeskeisestä ilmiöstä on kyse.

Mutta termit ovat epämääräisiä ja eronteko saattaa olla sellaista hiusten halkomista, joka ei ole YSOssa paikallaan.

**Comment by YSO-kokous** [comment]
Lisätään uushenkisyys ohjaustermiksi sekä uususkonnollisuudelle että henkisyydelle.

Uushenkisyyden soveltuvuus ohjaustermiksi henkisyydelle herätti keskustelua. Asia ratkesi äänestämällä.
