### ISSUE TITLE
epäluottamus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12802]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

epäluottamus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vaikka luottamus löytyy voisi näissä selkeästi epäluottamusta käsittelevissä julkaisuissa käyttää täsmällisempääkin termiä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543), [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [luottamus](http://www.yso.fi/onto/yso/p1725)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

ISBN 978-951-51-9474-9
Poliitikkojen ja virkamiesten välinen epäluottamus Suomessa :esiintyminen, syyt ja vaikutukset 

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [epäluottamus](http://finto.fi/yse/fi/page/Y512802)

**Comment by mirmaid** [comment]
6 viitettä Melindassa vapaana avainsanana, 12 + 4 x kauno/kaunokki-terminä.

**Comment by mariaforsen** [comment]
Sv. misstroende HT misstro
https://finto.fi/kauno/fi/page/p5942
https://svenska.se/tre/?sok=misstro&pz=1
https://svenska.se/tre/?sok=misstroende&pz=1
https://www.rikstermbanken.se/search?q=misstroende&s=termer

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
