### ISSUE TITLE
puutarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12809]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[puutarhat](http://www.yso.fi/onto/yso/p2225)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "hedelmätarhat"

**Perustelut ehdotukselle**

Runsaasti käytetty sana, josta olisi hyvä viitata sopivaan YSO-vastineeseensa, olipa se "puutarhat" tai jokin tarkempi

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: hedelmäpuita kasvava puutarha t. puutarhan osa, hedelmäpuutarha. 

YSOssa lisäksi _hedelmänviljely_. AFOssa ja MAOssa on erikseen _hedelmätarhat_.

**Comment by YSO-kokous** [comment]
Otetaan ohjaustermit:

hedelmätarhat, hedelmäpuutarhat KÄYTÄ puutarhat
