### ISSUE TITLE
Virtain kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12808]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Virtain kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Virtain kirkko 250 vuotta

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Virtain kirkko](http://finto.fi/yse/fi/page/Y512808)

**Comment by ilona-x** [comment]
WIkidata: http://www.wikidata.org/entity/Q11901720

**Comment by mariaforsen** [comment]
Sv. Virdois kyrka
