### ISSUE TITLE
Pekka ja Pätkä -elokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12800]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Pekka ja Pätkä -elokuvat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

On tukku julkaisuja, jotka käsittelevät Pekka ja Pätkä -elokuvia joukkona, ja yksittäisiin elokuviin viittaaminen olisi turhan raskasta ja/tai tarpeettoman tarkkaa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [draamaelokuvat](http://www.yso.fi/onto/yso/p26500), [komediat](http://www.yso.fi/onto/yso/p13876)

**Ehdotetut temaattiset ryhmät**

 [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

 Pekka Puupää -elokuvat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013517814, https://melinda.kansalliskirjasto.fi/byid/000603117 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [Pekka ja Pätkä -elokuvat](http://finto.fi/yse/fi/page/Y512800)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Pekka_ja_P%C3%A4tk%C3%A4_-elokuvat

7 x Melindassa.

**Comment by nikopartanen** [comment]
Varmaanhan tällaisia on ainakin Suomen mittakaavassa rajallinen, muttei aivan pieni, joukko. Nyt myös käsittelyssä on kaksi kansainvälistä sarjaa, jollaisia on varmasti loputtomasti. 

Tavallaanhan tämä menee periaatepäätöksen suuntaan, jos aletaan avata tällaisia elokuva- tai muita sarjoja omina käsitteinään.

**Comment by mariaforsen** [comment]
Sv. Kalle Träskalle och Stumpen-filmer HT Träskalle och Stumpen-filmer 
https://sv.wikipedia.org/wiki/Kalle_Tr%C3%A4skalle

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
