### ISSUE TITLE
työn varjostaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12810]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

työn varjostaminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

job shadowing

**Tarkoitusta täsmentävä selite**

Ks. esim. http://eosmo.pkamk.fi/tyokirja/varjostaminen/index.html

**Perustelut ehdotukselle**

Saimme palautetta finto-postiin. Erään AMK-opiskelijan opinnäytteen aiheena on työn varjostaminen.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ks. ed.

**Ehdottajan organisaatio**

finto-posti
**Termiehdotus Fintossa:** [työn varjostaminen](http://finto.fi/yse/fi/page/Y512810)

**Comment by jtuohini** [comment]
Mikä on ehdotetun suhde seuraaviin, sanastossa jo oleviin asiasanoihin: **ammatillinen kehitys**, **benchmarking**, **havainnointi**, **osaamisen kehittäminen**, **osaamisen siirto**, **työssäoppiminen**?

**Comment by mariaforsen** [comment]
Myös LCSH:ssa: https://id.loc.gov/authorities/subjects/sh00006845.html 

"Työn varjostaminen on työelämässä tapahtuvaa oppimista, jossa varjostaja seuraa itseään kiinnostavaa työtä tekevän ammattilaisen työskentelyä sovitun ajan, esimerkiksi päivän." 
/ https://www.ttl.fi/oppimateriaalit/monimuotoisuus-ja-inklusiivisuus-asiantuntijaorganisaatiossa/syrjimattomien-urapolkujen-luominen Eli olisiko työssäoppiminen YK ja muut voisivat olla RT? Jättäisin kyllä benchmarkingin pois. 

Sv. jobbskuggning HT arbetsskuggning 

https://www.abo.fi/samverkan/talent-boost/job-shadowing/
https://termipankki.fi/tepa/fi/haku/jobbskuggning
https://spraktidningen.se/okategoriserade/jobbskugga/

**Comment by mirmaid** [comment]
Tätä käytetään ilmeisesti myös työn kehittämiseksi.

Ei Melindassa.

**Comment by nikopartanen** [comment]
Viime aikoina tämä on ollut hyvin yleinen termi esimerkiksi Erasmus+-vaihtojen yhteydessä, eli toivotaan nimenomaan tällaista job shadowing -ohjelmaa, jossa voisi seurata asiantuntijan työtä lähemmin. Ainakin tämän kokemuksen perusteella vaikuttaa olemassa olevalta asialta, tosin voi olla, että noissa EU:n hauissa on yhtenä painopisteenä nykyään tällainen toiminta, minkä takia se on eri hakemuksissakin vastaavasti paljon esillä.

**Comment by FinMeSHienPaimentaja** [comment]
Kielikorvani vierastaa tuota "varjostamista".

**Comment by LeKorsu** [comment]
Komppaan FinMeshienPaimentajaa tuosta kielikorvasta.

**Comment by ilona-x** [comment]
TEPA:
https://termipankki.fi/tepa/fi/haku/job%20shadowing
IATE1
fi        työn varjostaminen (suositeltava, ★★★☆);
käytännön oppimiskokemus (★★★☆)
sv       praktisk lärandeerfarenhet (★★★☆);
jobbskuggning (★★★☆)
en      practical learning experience (★★★☆);
job shadowing (★★★☆)

	  
Lähde: IATE 01.08.2023, Euroopan unioni (3578092)
	  
IATE2
fi        työn varjostaminen (★★★☆);
job shadowing (★★★☆);
työn havainnointi (★★★☆);
työn seuraaminen (★★★☆);
työelämävarjostus (★★★☆)
sv       jobbskuggning (★★★☆)
en      work shadowing (★★★☆);
job shadowing (★★★★)

	  
Lähde: IATE 01.08.2023, Euroopan unioni (2217833)

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon. YSO-ylläpito tutkii tykönään, mikä valitaan käytettäväksi termiksi ja otetaanko tälle mahdollisesti ohjaustermejä.
