### ISSUE TITLE
ohjelmointivirheet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12817]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ohjelmointivirheet](http://www.yso.fi/onto/yso/p27382)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

njunuštearbma: programmerenfeaillat
stivrentearbma: programmerenmeattáhusat, prográmmameattáhusat, meattáhusat, dihkit
englanniksi, lisää ohjaustermeiksi "computer bugs" and "software bugs", suomeksi "ohjelmavirheet" ja "ohjelmistovirheet".

**Perustelut ehdotukselle**

Käytössä oph.fi:n ohjelmointiosaamisen kuvauksessa (https://eperusteet.opintopolku.fi/#/_Toc505873059/digiosaaminen/8706410/tekstikappale/8837705). Sammallahden sanakirjoista löytyy termille "ohjelmavirhe" sekä dihkki että prográmmameattáhus; dihkki on ollut käytössä esim. Skolelinuxisssa. Pelkästään meattáhus on myös käytössä bugeista.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mirmaid** [comment]
Suomenkieliset ohjaustermit lisätty. Eng. & saame?
