### ISSUE TITLE
laki eläinten hyvinvoinnista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12814]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lait](http://www.yso.fi/onto/yso/p1464)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko lait-käsitteen alle saada alakäsitteeksi laki
eläinten hyvinvoinnista? 

**Perustelut ehdotukselle**

Lait-käsitteen alla oleva eläinsuojelulaki on kumottu (Edilexistä tarkistettu: Eläinsuojelulaki (kumottu) 4.4.1996/247) ja nyt on voimassa Laki eläinten hyvinvoinnista 23.3.2023/693. 

**Ehdottajan organisaatio**

Hämeen ammattikorkeakoulu, Kirjasto- ja tietopalvelut

**Comment by jtuohini** [comment]
(Peruskitinääni, joten ysolaiset voivat jättää huomiotta:)

Kyseessä on juridinen teos, eli jos on aiheena, tulisi merkitä "610 14 |a Suomi. |t Laki eläinten hyvinvoinnista. |0 [Asteri-tunniste]", ja jos on vain tämän juridisen teoksen sisältävä manifestaatio, niin "110 1_ |a Suomi, |e säätävä lainkäyttöalue. |0 [Asteri-tunniste]" + "240 14 |a Laki eläinten hyvinvoinnista [jne.]" ja jos tämän ja muita teoksia sisältävä manifestaatio, niin "710 1_ |i Sisältää (ekspressio): |a Suomi. |t Laki eläinten hyvinvoinnista [jne.]".

Voin auktorisoida tämän Tekaan muiden lakien jatkoksi, jahka palaan lomalta.

**Comment by mariaforsen** [comment]
Sv. lag om djurvälfärd
https://finlex.fi/sv/laki/alkup/2023/20230693
