### ISSUE TITLE
X-kromosomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12812]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

X-kromosomi

**Ehdotettu termi ruotsiksi**

X-kromosom

**Ehdotettu termi englanniksi**

X chromosome

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa (pelkkä "sukupuolikromosomit" on turhan epätarkka)

**Ehdotettu yläkäsite YSOssa (LT)**

 [sukupuolikromosomit](http://www.yso.fi/onto/yso/p21593)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

 chromosome X

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85148724), [MeSH](http://id.nlm.nih.gov/mesh/D014960), [Wikidata](https://www.wikidata.org/wiki/Q61333)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013459465 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [X-kromosomi](http://finto.fi/yse/fi/page/Y512812)

**Comment by mariaforsen** [comment]
Sv. X-kromosom HT x-kromosom
https://svenska.se/tre/?sok=x-kromosom&pz=1
