### ISSUE TITLE
Y-kromosomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12811]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Y-kromosomi

**Ehdotettu termi ruotsiksi**

Y-kromosom

**Ehdotettu termi englanniksi**

Y chromosome

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailussa (pelkkä "sukupuolikromosomit" liian epätarkka)

**Ehdotettu yläkäsite YSOssa (LT)**

 [sukupuolikromosomit](http://www.yso.fi/onto/yso/p21593)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85148874), [Wikidata](https://www.wikidata.org/wiki/Q202771)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/005811321 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [Y-kromosomi](http://finto.fi/yse/fi/page/Y512811)

**Comment by mariaforsen** [comment]
Sv. Y-kromosom HT y-kromosom
https://svenska.se/tre/?sok=y-kromosom&pz=1
