### ISSUE TITLE
SLM/lintuoppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12815]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM/lintuoppaat

**Ehdotettu termi ruotsiksi**

fågelguider?

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sanastossa on myös kasviot, ja vastaava tarve lintujen tunnistamista käsitteleville oppaille. YKL 56.8 sanottua -> Erikoisalojen luonto-oppaat ja lajinmääritysoppaat luokitetaan alan mukaan. Yleisimmät voisi olla olemassa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paljon on tämäntyyppisiä lintukirjoja.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [SLM/lintuoppaat](http://finto.fi/yse/fi/page/Y512815)

**Comment by mirmaid** [comment]
Hyväksytty/SLM (KT lajinmääritysoppaat (linnut)), hyväksytään myös sienioppaat KT sienikirjat.
Kasviot: vaihdetaan päätermiksi kasvioppaat.

**Comment by mariaforsen** [comment]
Sv. 
-fågelguider HT fågelböcker, fågelhandböcker
https://svenska.se/tre/?sok=f%C3%A5gelbok&pz=1
-svampguider HT svampböcker, svamphandböcker
https://svenska.se/tre/?sok=svampbok&pz=1

https://kaino.kotus.fi/finsk-svensk/?p=article&word=opaskirja&suru_id=SURU_a97d9c71cd31a8ac238f3d8c56430eab
jfr https://finto.fi/slm/fi/search?clang=fi&anylang=on&q=*guider
