### ISSUE TITLE
twerkkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12819]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

twerkkaus

**Ehdotettu termi ruotsiksi**

twerking

**Ehdotettu termi englanniksi**

twerking

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582)

**Vaihtoehtoiset termit**

 twerk

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tinze : periksiantamaton / 978-952-04-5156-1

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [twerkkaus](http://finto.fi/yse/fi/page/Y512819)

**Comment by jtuohini** [comment]
Wikidata-siltaus: https://www.wikidata.org/wiki/Q7857851.

LCSH:ssa ei ole vastaavaa asiasanaa, mutta sisällytettäneen samaan joukkoon kuin muut [**Hip-hop dance**](http://id.loc.gov/authorities/childrensSubjects/sj2021060283) -asiasanalla kuvailtavat, ks. esim. https://lccn.loc.gov/2021054127 (jossa mukana _Twerking and P-Popping in the Context of New Orleans’ Local Hip-Hop Scene_ -artikkeli).

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. twerking HT twerkning
https://dansbyran.se/danser/twerking/
https://spraktidningen.se/sprakbloggen/veckans-nyord-twerka/
https://sv.wiktionary.org/wiki/twerking
