### ISSUE TITLE
siviilivalmius

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12827]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

siviilivalmius

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Siviilivalmius on Suomen Sisäministeriön laatiman määritelmä mukaan huoltovarmuutta, pelastuspalvelua, väestönsuojelua sekä kriittisen infrastruktuurin suojelua edistävää ja ylläpitävää toimintaa. Pelastusopiston määritelmän mukaan siviilivalmius on kansalaisten turvaamista turvallisuusuhkia vastaan, pitäen sisällään myös laaja-alaista viranomaisyhteistyötä [2]. Siviilivalmius uutena yhteiskunnallisena toimintamuotona on osa turvallisuusajattelun muutostrendiä kohti laajempaa näkemystä, jossa turvallisuus nähdään niin kansalaisten kuin organisaatioiden yhteisenä vastuuna.

**Perustelut ehdotukselle**

Sanastosta puuttuva termi, joka tarvitaan väestönsuojeluun liittyvien teosten kuvailuun. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Väestönsuojeluun ja sisäiseen turvallisuuteen liittyvät teokset. 

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [siviilivalmius](http://finto.fi/yse/fi/page/Y512827)

**Comment by mirmaid** [comment]
Suhde siviilipuolustukseen?

**Comment by mariaforsen** [comment]
VALTER https://valter.sanakirja.fi/all/all/siviilivalmius

Sv. civil beredskap HT civilberedskap 
jfr https://termipankki.fi/tepa/fi/haku/siviilivalmiussuunnittelukyky
https://id.kb.se/find?q=civil%20beredskap
https://polamk.fi/sv/siva-sv
https://finlandabroad.fi/web/nato/civil-beredskap

**Comment by ilona-x** [comment]
Tuli vastaan vanha ehdotus  **siviilivalmiudet** #357

**Comment by mirmaid** [comment]
VALTERin määritelmä on paremmin synkassa termimuodon kanssa, eli _**kyky** ylläpitää yhteiskunnalle elintärkeitä toimintoja, väestön perushuoltoa ja valtion toimintakykyä kriisitilanteessa_. Tosin sielläkin mainitaan "kyvyn" kolme tärkeintä tehtävää. Mutta tämä olisi siis vastaava kuin _kriisivalmius_ tai _toimintavalmius (organisaatiot)_.

**Comment by YSO-kokous** [comment]
Hyväksytään yksikkömuodossa.
