### ISSUE TITLE
ortogonaaliset polynomit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12826]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ortogonaaliset polynomit

**Ehdotettu termi ruotsiksi**

ortogonala polynom

**Ehdotettu termi englanniksi**

orthogonal polynomials

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [polynomit](http://www.yso.fi/onto/yso/p17241)

**Ehdotetut temaattiset ryhmät**

 [04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574)

**Vaihtoehtoiset termit**

 ortogonalpolynom 

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85095794), [Wikidata](http://www.wikidata.org/entity/Q619458), [SAO](https://id.kb.se/term/sao/Ortogonalpolynom)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Complex analysis and orthogonal polynomials

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [ortogonaaliset polynomit](http://finto.fi/yse/fi/page/Y512826)

**Comment by mariaforsen** [comment]
Sv. ortogonalpolynom HT ortogonala polynom
https://id.kb.se/term/sao/Ortogonalpolynom
