### ISSUE TITLE
Kapernaum

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12824]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kapernaum

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Capernaum (Extinct city)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Muinaiskaupunki, josta tietoa haetaan  varmasti nimellä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [Galilea](http://www.yso.fi/onto/yso/p234809)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http://Capernaum (Extinct city)), [Wikipedia](https://fi.wikipedia.org/wiki/Kapernaum)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9786176798699

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Kapernaum](http://finto.fi/yse/fi/page/Y512824)

**Comment by mirmaid** [comment]
Hierarkia? 
Eng. wikipedian mukaan kalastajakylä, ruots. "stad", suom. "kaupunki tai kalastajakylä".

**Comment by mirmaid** [comment]
Ok nykyisellä tavalla.

**Comment by mariaforsen** [comment]
Sv. Kafarnaum (Nationalencyklopedin) HT Kapernaum 
https://sv.wikipedia.org/wiki/Kafarnaum
