### ISSUE TITLE
boori-neutronikaappaushoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12821]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

boori-neutronikaappaushoito

**Ehdotettu termi ruotsiksi**

borneutroninfångningsterapi

**Ehdotettu termi englanniksi**

boron neutron capture therapy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

Melinda:
boorineutronikaappaushoito x 4
boorineutronisädehoito x 12
BNCT x 13
BNCT-hoito x 1

**Ehdotettu yläkäsite YSOssa (LT)**

 [sädehoito](http://www.yso.fi/onto/yso/p15892)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 boorineutronisädehoito, BNCT-hoito

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D016754), [Wikipedia](https://fi.wikipedia.org/wiki/BNCT), [LCSH](http://id.loc.gov/authorities/subjects/sh86005080)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Development and early stage investigation of carbohydrate-based delivery agents for boron neutron capture therapy http://urn.fi/URN:ISBN:978-951-51-9511-1

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [boori-neutronikaappaushoito](http://finto.fi/yse/fi/page/Y512821)

**Comment by mariaforsen** [comment]
Sv. borneutroninfångningsterapi HT BNCT-behandling, BNCT-strålbehandling
https://mesh.kib.ki.se/term/D016754/boron-neutron-capture-therapy
https://lakartidningen.se/wp-content/uploads/OldPdfFiles/2002/24094.pdf
https://www.hbl.fi/2016-09-15/finland-forst-i-varlden-med-unik-maskin-som-behandlar-cancer/
