### ISSUE TITLE
YH

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12822]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[YH](http://www.yso.fi/onto/yso/p20275)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö käytettävää termiä tarkentaa jollakin tavalla?

**Perustelut ehdotukselle**

YH-kirjainlyhenne ei välttämättä nykykäyttäjällä assosioidu automaattisesti kyseiseen aiheeseen (eli vuoden 1939 ylimääräiset kertausharjoitukset). YH voi tarkoittaa esim. yksinhuoltajaa, yhteiskuntaoppia, yhteyshenkilöä jne.
https://fi.wikipedia.org/wiki/Yh

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Olisiko ratkaisu yksinkertaisesti päätermin ja ohjaustermin vaihto päittäin?

**Comment by mariaforsen** [comment]
Rajautuuko tämä nimenomaan vuoden 1939 kertausharjoituksiin ja onko se kaikille selvää ilman tarkennetta? (Ruotsiksi ei välttämättä)
https://fho.sls.fi/uppslagsord/18417/extra-ovningar/

**Comment by YSO-kokous** [comment]
Vaihdetaan käsitteen päätermiksi ylimääräiset kertausharjoitukset. Ruotsin termiin voi lisätä tarkenteeksi 1939.

**Comment by mariaforsen** [comment]
Sv. YH (extraordinära repetitionsövningar) > extra övningar (1939) HT extra repetitionsövningar (1939)
https://fho.sls.fi/uppslagsord/18417/extra-ovningar/
https://veteraanienperinto.fi/index.php/sv/vinterkriget/vinterkrigets-gang/krigsutbrottet/
https://yle.fi/a/7-1499041
