### ISSUE TITLE
Helsingin olympiastadion

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12835]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Helsingin olympiastadion](http://www.yso.fi/onto/yso/p805)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi Olympiastadion (Helsinki)

**Perustelut ehdotukselle**

Puhekielessä esiintyy usein yksinkertaisesti muodossa Olympiastadion. Ja kyseisellä sanalla kun lähtee hakemaan YSOsta niin ei tule Fintossa hakukentän dropdowniin tuloksia.
Ks. esim. https://www.stadion.fi/fi

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by jtuohini** [comment]
Sama lisäys varmaan myös Kannon puolelle?
