### ISSUE TITLE
kielitausta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12830]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kielitausta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Toivottu termiä, jolla voisi korostaa henkilön kielitaustaa lähtömaan sijasta. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

xxxx

**Ehdottajan organisaatio**

Laurea-ammattikorkeakoulu
**Termiehdotus Fintossa:** [kielitausta](http://finto.fi/yse/fi/page/Y512830)

**Comment by mirmaid** [comment]
Alkuperäinen ehdotus: https://github.com/Finto-ehdotus/YSE/issues/12760

**Comment by mirmaid** [comment]
Tässä olisi voinut käyttää: https://www.utupub.fi/handle/10024/174277

**Comment by ilona-x** [comment]
Jos hyväksytään, niin ohjaustermiksi **kielellinen tausta,**? Termiä on käytetty tuossa yllä mainitussa väitöskirjassa.

**Comment by mirmaid** [comment]
Kumpaakaan ei toistaiseksi Melindassa.

**Comment by mariaforsen** [comment]
Sv. språkbakgrund HT språklig bakgrund
https://sprakbruk.fi/artiklar/sprakrum-och-sprakbruk/
https://www.kieliverkosto.fi/fi/journals/kieli-koulutus-ja-yhteiskunta-maaliskuu-2021/sprakstigen-i-de-svensksprakiga-skolorna-utmaningar-och-mojligheter
https://www.lararen.fi/kolumn/ord-for-ord/vi-ar-experter-pa-elever-med-olika-sprakbakgrund/
https://www.abo.fi/wp-content/uploads/2019/09/Jan-Hellgren-Hur-klarar-lararna-av-att-mota-elever-med-olika-sprakbakgrund_Abo_Vasa_september2019.pdf
https://www.oph.fi/sv/utbildning-och-examina/flersprakighet-och-att-stodja-skolspraket

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Ohjaustermiksi kielellinen tausta.
