### ISSUE TITLE
Tolkkilan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12839]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Tolkkilan kartano

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kartanot](http://www.yso.fi/onto/yso/p832)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tolkkilan kartano : perinteet elävät 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [Tolkkilan kartano](http://finto.fi/yse/fi/page/Y512839)

**Comment by mariaforsen** [comment]
Sv. Tolkkilan kartano HT Tolkkila gård
