### ISSUE TITLE
klinkkerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12836]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[klinkkerit](http://www.yso.fi/onto/yso/p7880)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käsitettä voisi tarkentaa. Klinkkeri on yhtä kuin "solid material produced in the manufacture of portland cement as an intermediary product". Klinkkerilaatta taas on keraaminen laatta eli pinnoitemateriaali. Pitäisikö päätermi varustaa sulkutarkenteella tai vaihtaa nykyinen ohjaustermi (klinkkerilaatat) päätermiksi? Jos käsitteen rajauksessa tulee muutoksia, hierarkia pitäisi tarkistaa myös.

**Perustelut ehdotukselle**

Ks. esim. https://en.wikipedia.org/wiki/Cement_clinker
https://fi.wikipedia.org/wiki/Keraaminen_laatta
En ole asiantuntija, mutta tulkitsen, että esim. tämän blogikirjoituksen mukaan klinkkerilaatoiksi kutsuttuja laattoja ei välttämättä tehdä klinkkeristä. "The ceramic tiles that “claim” to be clinker are made today from plastic ceramic mass.."
https://royalfacade.eu/how-clinker-tiles-are-made-today/

Huom! On olemassa myös klinkkeritiili: https://fi.wikipedia.org/wiki/Klinkkeritiili

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Molemmissa merkityksissä Melindassa, mutta varmaan _sementti_ riittää niissä aineistoissa, joissa kyse ei ole laatoista. Yhteensä vain 20 kertaa Melindassa-

**Comment by mariaforsen** [comment]
Tarvitaan varmaan tarkenne ruotsiksi https://www.rikstermbanken.se/search?q=klinker&s=termer  

Olisiko tosiaan parempi jakaa > klinkkerilaatat ja klinkkeri (sementti)? 

Onhan tämä https://fi.wikipedia.org/wiki/Klinkkeri myös https://www.betonitieto.fi/kirjasto-ja-sanasto/betonisanasto/klinkkeri.html aika eri asia tosiaan, verrattuna klinkkerilaattoihin.
