### ISSUE TITLE
spermatogeneesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12848]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

spermatogeneesi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/175850

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [spermatogeneesi](http://finto.fi/yse/fi/page/Y512848)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh85126541
https://fi.wikipedia.org/wiki/Spermatogeneesi

Vähän toistakymmentä kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. spermatogenes
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/spermatogenes
https://www.rikstermbanken.se/search?q=spermatogenes&s=termer
