### ISSUE TITLE
kasvurusto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12842]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kasvurusto

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

growth plate

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kasvurusto; kasvavalla lapsella esiintyvä pitkän luun varren (diafyysin) ja pään (epifyysin) tai apofyysin (luuhaarakkeen) välinen uusiutuva rustoinen osa, jossa luun pituuskasvu tapahtuu siten, että rusto korvautuu metafyysissä muodostuvalla luukudoksella

https://www.terveyskirjasto.fi/ltt01515
https://en.wikipedia.org/wiki/Epiphyseal_plate

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 kasvulevy

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-951-51-9507-4

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [kasvurusto](http://finto.fi/yse/fi/page/Y512842)

**Comment by ilona-x** [comment]
FinMeSH: [kasvulevy ](http://www.yso.fi/onto/mesh/D006132) 
LCSH: [Growth plate]( http://id.loc.gov/authorities/subjects/sh88001051)

**Comment by mariaforsen** [comment]
Sv. tillväxtplattor HT epifysbrosk, epifysplattor, tillväxtbrosk
/uppslagsverk/encyklopedi/lång/epifysbrosk
https://mesh.kib.ki.se/term/D006132/growth-plate
