### ISSUE TITLE
tanrekit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12849]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tanrekit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Blum: Erikoiset eläimet

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tanrekit](http://finto.fi/yse/fi/page/Y512849)

**Comment by mariaforsen** [comment]
Sv. tanrekar HT borstigelkottar /ne
