### ISSUE TITLE
panhypopituitarismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12843]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

panhypopituitarismi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

combined pituitary hormone deficiency (CPHD), panhypopituitarism

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://medlineplus.gov/genetics/condition/combined-pituitary-hormone-deficiency/
Tämä on samaa asiaa: Aivolisäkkeen vajaatoiminta (hypopituitarismi) https://www.terveyskirjasto.fi/dlk00996

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 usean aivolisäkehormonin vajaatoiminta

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-951-51-9507-4

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [panhypopituitarismi](http://finto.fi/yse/fi/page/Y512843)

**Comment by mirmaid** [comment]
Lääketieteen termit: hypopituitarismi: aivolisäkkeen etulohkon vajaatoiminta
Lääketieteen termit: panhypopituitarismi: aivolisäkkeen etulohkon kaikkien hormonien vajaaeritys

**Comment by mariaforsen** [comment]
Mesh https://finto.fi/mesh/fi/page/D007018 

Sv. hypofysinsufficiens HT hypopituitarism, hypofyssvikt, hypofysär underproduktion
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/hypofysinsufficiens
https://mesh.kib.ki.se/term/D007018/hypopituitarism
https://vardpersonal.1177.se/kunskapsstod/kliniska-kunskapsstod/hypofysinsufficiens/?selectionCode=profession_primarvard
https://www.terveyskyla.fi/sv/genetikochsallsynta/sjukdomsgrupper/sallsynta-endokrina-sjukdomar/soktjanst-for-sallsynta-endokrina-sjukdomar/hypofysinsufficiens

**Comment by fantsby-m** [comment]
Tautiluokitus ICD-10:
[Panhypopituitarismi](https://koodistopalvelu.kanta.fi/codeserver/pages/code-view-page.xhtml?callerViewId=%2Fpages%2Fcodelist-quick-search-page.xhtml&conceptCodeKey=100054395&hierarchyView=false&classificationType=1&rowIndex=0)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa hypopituitarismi.

**Comment by mariaforsen** [comment]
Varmaan ohjausterminä aivolisäkkeen vajaatoiminta? https://www.terveyskirjasto.fi/dlk00996
https://sellanet.com/aivolisake/aivolisakkeen-vajaatoiminta/
https://www.terveyskyla.fi/genetiikkajaharvinaiset/tautiryhmat/harvinaiset-endokrinologiset-sairaudet/harvinaisten-endokrinologisten-sairauksien-hakukone/aivolisakkeen-vajaatoiminta
https://www.endo.fi/tietoa-endokrinologisista-sairau/potilasohjeet/aivolisakkeen-vajaatoiminta-eli-/
