### ISSUE TITLE
sivukirjastot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12840]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sivukirjastot](http://www.yso.fi/onto/yso/p22524)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lähikirjaston vastine pohjoissaameksi: lagasgirjerájut, lagasgirjerádjosat.

**Perustelut ehdotukselle**

Lagasgirjerádju ollut käytössä sekä OPH:n perusopetuksen vuoden 2014 opetussuunnitelmassa (https://www.oph.fi/sites/default/files/documents/pohjoissaame_perusopetuksen_opetussuunnitelman_perusteet_2014.pdf) että OKM:n kirjastoesitteessä "Suomas girjerádju lea juohkeovtta nuvttá vuođđobálvalus" (https://www.kirjastot.fi/sites/default/files/matbank/palvelua-kaikille-suomen-yleiset-kirjastot-pohjsaame.pdf)

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Ehdotus hyväksytään.
