### ISSUE TITLE
somaattiset mutaatiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12841]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

somaattiset mutaatiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

somatic mutations

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.duodecimlehti.fi/duo94707 
mutta myös:
https://www.luke.fi/fi/luonnonvaratieto/tiedetta-ja-tietoa/metsatuhot/metsatuhonaiheuttajat/taudit/somaattiset-mutaatiot

**Ehdotettu yläkäsite YSOssa (LT)**

 [mutaatiot](http://www.yso.fi/onto/yso/p15346)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:ISBN:978-951-51-9571-5

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [somaattiset mutaatiot](http://finto.fi/yse/fi/page/Y512841)

**Comment by mirmaid** [comment]
Lääketieteen termit: muissa kuin ituradan soluissa tapahtuva mutaatio, joka ei periydy.

Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. somatiska mutationer
https://sv.wikipedia.org/wiki/Mutation

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/items/0ddb5a38-cbcd-429f-b5be-057ee2e0fa8c
