### ISSUE TITLE
haploryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12854]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

haploryhmät

**Ehdotettu termi ruotsiksi**

haplogrupper

**Ehdotettu termi englanniksi**

haplogroups

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Geneettisen sukututkimuksen ja väestötutkimuksen kannalta hyvin keskeinen asia, josta ilmestyy varmasti yhä enemmän aineistoa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [perimä](http://www.yso.fi/onto/yso/p8862)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kromosomit](http://www.yso.fi/onto/yso/p7688)

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q80686)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/019096219, https://melinda.kansalliskirjasto.fi/byid/018179700 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [haploryhmät](http://finto.fi/yse/fi/page/Y512854)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Haploryhm%C3%A4

**Comment by jtuohini** [comment]
Ja monista Melindan tietueista puuttuu tykkänään tämä, esim. https://melinda.kansalliskirjasto.fi/byid/003766261.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
