### ISSUE TITLE
syntymätapa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12853]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

syntymätapa

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 synnytystapa

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.utupub.fi/handle/10024/174491

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [syntymätapa](http://finto.fi/yse/fi/page/Y512853)

**Comment by mariaforsen** [comment]
Syntymätapa n. 283 googlessa ja myös muissa merkityksissä..
Synnytystapa n. 29 200 ja helpompi kääntää..

Sv. förlossningssätt HT födelsesätt

**Comment by mirmaid** [comment]
^ Varmaan ok sekin. Ehkä silloin kun tutkitaan syntymätavan yhteyttä johonkin lapsen myöhemmässä kehityksessä, tuo synnytystapa tuntuu nurinkuriselta, mutta tietysti toisissa yhteyksissä se on paljon toimivampi.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa synnytystapa, ohjaustermiksi syntymätapa.

Käsitteen sanastoon ottamisesta äänestettiin. Enemmistö kannatti käsitteen hyväksymistä.
