### ISSUE TITLE
saostusaltaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12852]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

saostusaltaat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sakokaivosta ohjataan saostuskaivon käyttöön AFOa lukuun ottamatta. AFO myöskin kääntää sakokaivon englanniksi muotoon septic tank. Muissa sanastoissa sakokaivo on kielletty muoto, josta ohjataan saostuskaivon käyttöön. Tämä puolestaan kääntyy englanniksi muotoon sedimentation basins. Suomen kielellä sekä sako- että saostuskaivo näyttäisivät tarkoittavan samaa asiaa, eli jonkinlaista maan alla olevaa erillistä säiliötä, jonka pohjalle saostuu aineksia läpivirtaavan jäteveden joukosta. Tätä tarkoittaa myös septic tank. Sedimentation basins puolestaan Google-haun mukaan tarkoittaa saostusallasta, siis maan pinnalla olevaa avointa allasta, jossa läpivirtaavasta vedestä saostuskaivon tapaan saostuu altaan pohjalle kiintoainesta. Tätä käytetään usein esim. kaivosteollisuudessa jätevesien puhdistamiseen ja altaat saattavat olla kooltaan kymmeniä hehtaareja. Eli tältä pohjalta esittäisin, että kaikissa sanastoissa otettaisiin saostuskaivon yhteydessä käyttöön englanninkielinen termi septic tank, joka vastaa parhaiten saostuskaivoa. Saostusallas ei näytä olevan suomalaisissa sanastoissa oleva termi, mutta sekin voisi siellä olla, koska saostusaltaita on käytössä myös Suomessa olevilla kaivoksilla, ainakin Talvivaaran allas on vuotanut järviin. Sen käännös voisi sitten olla sedimentation basins.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

xxxx

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [saostusaltaat](http://finto.fi/yse/fi/page/Y512852)

**Comment by mariaforsen** [comment]
Sv. sedimenteringsbassänger?
https://www.sanakirja.fi/custom/all/saostusallas
https://www.vesi.fi/sv/sanasto/sedimenteringsbassang/
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/sedimenteringsbass%C3%A4ng-(s%C3%A4nka-i-jordskorpan)

**Comment by mirmaid** [comment]
Sanastossa on jo _laskeutusaltaat_, ruotsiksi sedimenteringsbassänger. 
https://en.wikipedia.org/wiki/Settling_basin#Mining

**Comment by fantsby-m** [comment]
_saostusaltaat_ ohjaustermiksi?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi:
saostusaltaat KÄYTÄ laskeutusaltaat
