### ISSUE TITLE
tinaoksidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12856]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tinaoksidit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

tin dioxide

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [oksidit](http://www.yso.fi/onto/yso/p2803)

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Tinadioksidi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Electroblowing of Metal Oxide Fibers for Removal of Hazardous Trace Metal Ions from Industrial Wastewaters http://urn.fi/URN:ISBN:978-951-51-9463-3

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [tinaoksidit](http://finto.fi/yse/fi/page/Y512856)

**Comment by mariaforsen** [comment]
Wikipedialinkki vie nyt tina**di**oksidiin. Löytyy myös https://fi.wikipedia.org/wiki/Tinaoksidi 
Vrt. eng.

Sv. tennoxider 
https://svenska.se/tre/?sok=tennoxid&pz=1
..skillnad oxid vs. dioxid (se svenska.se)
