### ISSUE TITLE
seskviterpeenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12863]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

seskviterpeenit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Seskviterpeenit

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Seskviterpeenit

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/96186

**Ehdottajan organisaatio**

Jyväskylän yliopisto
**Termiehdotus Fintossa:** [seskviterpeenit](http://finto.fi/yse/fi/page/Y512863)

**Comment by mariaforsen** [comment]
Sv. seskviterpener
https://mesh.kib.ki.se/term/D012717/sesquiterpenes
