### ISSUE TITLE
digitaalinen tuotepassi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12865]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

digitaalinen tuotepassi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

digital product passport

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://gs1.fi/fi/kehitys/digitaalinen-tuotepassi

Digitaalisen tuotepassin tarkoituksena on tarjota kuluttajille tietoa esimerkiksi tuotteiden korjaamiseen ja kierrätykseen tai niiden materiaalien alkuperään liittyen.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.sitra.fi/en/publications/digital-product-passports/
Digital product passports :catalysing Europe's sustainable growth : key lessons from Finnish pilots to support the development of circular economy business models

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [digitaalinen tuotepassi](http://finto.fi/yse/fi/page/Y512865)

**Comment by mariaforsen** [comment]
Sv. digitala produktpass
https://termipankki.fi/tepa/fi/haku/digitalt%20produktpass
https://www.ri.se/sv/berattelser/hog-tid-att-forbereda-sig-for-digitala-produktpass
https://www.svenskhandel.se/nyheter/nyhet/hog-tid-att-lara-sig-mer-om-digitala-produktpass

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by fantsby-m** [comment]
https://gs1.fi/fi/kehitys/digitaalinen-tuotepassi
"Lähivuosina lähes kaikille EU:n markkinoille saatettaville tuotteille vaaditaan digitaalinen tuotepassi."

https://www.sitra.fi/hankkeet/digitaaliset-tuotepassit/

**Comment by YSO-kokous** [comment]
Hyväksytään monikkomuodossa.
