### ISSUE TITLE
erityisliikunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12860]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[erityisliikunta](http://www.yso.fi/onto/yso/p3093)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pitäisikö vaihtaa päätermiksi soveltava liikunta ja mahdollisesti yhdistää tähän käsitteeseen myös vammaisliikunta, joka on nyt YSOssa erikseen?

**Perustelut ehdotukselle**

fi        soveltava liikunta
mieluummin kuin: sovellettu liikunta; erityisliikunta
ei: erityisryhmien liikunta (vanhentunut); vammaisliikunta (vanhentunut)
Lähde: Soveltavan liikunnan ja paraurheilun sanasto (Liikuntatieteellinen Seura, 2023) https://termipankki.fi/tepa/fi/haku/soveltava%20liikunta

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Kuulostaa perustellulta.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta vammaisliikunta.
Vaihdetaan erityisliikunnan päätermiksi soveltava liikunta.
Ohjaustermeiksi vammaisliikunta, erityisliikunta KÄYTÄ soveltava liikunta.

**Comment by mariaforsen** [comment]
Sv. specialidrott > anpassad motion HT anpassad fysisk aktivitet, specialmotion, motion för specialgrupper, specialgruppsmotion, handikappmotion

https://termipankki.fi/tepa/fi/haku/soveltava%20liikunta
https://sanastokeskus.fi/tsk/sv/ordlista_f%C3%B6r_anpassad_motion_och_paraidrott-1478.html
https://idrott.fi/idrott/projekt/vi-ocksa/anpassadmaterial/
https://idrott.fi/idrott/anpassad-motion/

Borde även ändra handikappidrott > parasport, paraidrott?
https://www.handikappidrott.se/
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/parasport
https://id.kb.se/term/sao/Parasport
https://svenska.se/tre/?sok=handikappidrott&pz=1
https://termipankki.fi/tepa/fi/haku/vammaisurheilu
https://frageladan.isof.se/visasvar.py?svar=79533
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_d62067daebb42359a08ae2532b269da5&list_id=1&keyword=vammaisurheilu&word=vammaisurheilu
https://www.skolidrott.se/for-skol-if/paraidrott
