### ISSUE TITLE
käynnistetty synnytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12868]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

käynnistetty synnytys

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [synnytys](http://www.yso.fi/onto/yso/p4557)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 synnytyksen käynnistäminen

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D007751), [Wikidata](http://www.wikidata.org/entity/Q1497276), [LCSH](http://id.loc.gov/authorities/subjects/sh85073634)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Labor induction at term and beyond http://urn.fi/URN:ISBN:978-951-51-9529-6

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [käynnistetty synnytys](http://finto.fi/yse/fi/page/Y512868)

**Comment by mariaforsen** [comment]
Sv. igångsatt förlossning HT framkallat värkarbete, förlossningsinduktion, igångsättning av förlossning 
https://finto.fi/mesh/sv/page/D007751
https://www.terveyskyla.fi/sv/kvinnohuset/forlossning/igangsattning-av-forlossningen/risker-vid-igangsaettning-av-forlossning
/uppslagsverk/encyklopedi/lång/förlossningsinduktion
