### ISSUE TITLE
hydroksyylit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12862]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hydroksyylit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Hydroksyyli

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Hydroksyyli

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://jyx.jyu.fi/handle/123456789/96186

**Ehdottajan organisaatio**

Jyväskylän yliopisto
**Termiehdotus Fintossa:** [hydroksyylit](http://finto.fi/yse/fi/page/Y512862)

**Comment by mariaforsen** [comment]
Sv. hydroxyler
https://www.rikstermbanken.se/search?q=hydroxyl&s=termer
