### ISSUE TITLE
brintsolamidi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12876]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

brintsolamidi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

brinzolamide

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Brinzolamide)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Pharmacokinetics and study size considerations of topical ocular suspensions of brinzolamide and dexamethasone in rabbits 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [brintsolamidi](http://finto.fi/yse/fi/page/Y512876)

**Comment by mariaforsen** [comment]
Sv. brinzolamid
https://janusinfo.se/beslutsstod/lakemedelochmiljo/databasmiljosv/brinzolamid.5.30a7505616a041a09b065493.html
https://www.sanakirja.fi/custom/all/brinzolamide
