### ISSUE TITLE
esteettömyys ja saavutettavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12874]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[esteettömyys ja saavutettavuus](http://www.yso.fi/onto/yso/p16241)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä on ehkä enemmän kysymys kuin muutosehdotus, mutta miksiköhän esteettömyys ja saavutettavuus on niputettu samaan yhdysasiasanaan? 

**Perustelut ehdotukselle**

Esteettömyydellä viitataan fyysiseen toimintaympäristöön ja saavutettavuudella verkkoympäristöön ja viestintään. Yleisellä tasolla käsitteistä puhutaan toistensa synonyymeinä, mutta tiedonhaun näkökulmasta mielestäni nämä olisi hyvä pitää erillään. Lisäksi yhdysasiasanan käyttö on mahdollista vain teoksissa, joissa käsitellään kumpaakin aihetta. Tästä syystä käytössä onkin edelleen erilliset asiasanat "esteettömyys" ja "saavutettavuus", minkä takia niitä voisi käyttää yhdenmukaisesti erikseen kaikissa teoksissa. 

**Ehdottajan organisaatio**

Vantaan kaupunki / Myyrmäen kirjasto

**Comment by mirmaid** [comment]
Taustaa ratkaisulle täällä: https://github.com/Finto-ehdotus/YSE/issues/9659

**Comment by mirmaid** [comment]
Saavutettavuus-termiä saatetaan käyttää myös "fyysisemmin": palveluiden saavutettavuus, pääsy käyttämään palveluita esim. liikennevälineillä. 

Tarkoitus ei toki ole, että yhdistelmäasiasanaa käytetään vain jos aineisto käsittelee molempia aspekteja, vaan kaikissa tapauksissa.

**Comment by YSO-kokous** [comment]
YSO-kokous ei nähnyt tarvetta muutoksille.
