### ISSUE TITLE
oppimaan oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12879]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oppimaan oppiminen](http://www.yso.fi/onto/yso/p17048)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko oppimaan oppimisvalmiudet ohjaustermi tälle vai oppimisvalmiudet-termille?

**Perustelut ehdotukselle**

Mietitään ruotsinnosta, nyt inlärningsfärdigheter, mikä olisi oikeastaan tämä yllä mainittu. Ruotsiksi inlärningsfärdigheter on myös hyvin lähellä oppimiskyky-käsitettä. 
http://www02.oph.fi/asiakkaat/itsearviointi/suomi/toiminta/ammkoulu.html
https://termipankki.fi/tepa/fi/haku/oppimaan%20oppimisvalmiudet

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Oppimaan oppimisvalmiuksilla tarkoitetaan niitä yleisiä oppimisvalmiuksia, joita tarvitaan ei vain tietyn oppiaineen tai ammatin opiskelussa vaan oppimisessa yleensä. https://www.edilex.fi/mt/sivm19980003

_Oppimaan oppimisvalmiudet_ tuo hyvin vähän Google-viitteitä, ja veikkaisin että _oppimisvalmiudet_ ymmärretään kyllä yleensä laajemmin kuin vain tiettyyn aineeseen tai tutkintoon liittyvinä valmiuksina, esim.
_Ensiluokkalaisten oppimaan oppimisen arvioinnissa keskitytään ei-kielellisiin oppimisvalmiuksiin sekä työskentelytaitoihin ja sosiaaliseen toimintaan opettajien ja vanhempien arvioimana. Oppimisvalmiustehtävät mittaavat oppilaiden päättelytaitoa, vaaka/pystysuuntien hahmottamista, työmuistia ja toiminnanohjausta._ https://helda.helsinki.fi/server/api/core/bitstreams/0a35fbfb-16ce-461f-96d2-ce216aac2a68/content

**Comment by mirmaid** [comment]
En siis välttämättä lisäisi oppimaan oppimisvalmiudet -termiä ohjaustermiksi ollenkaan, mutta jos lisäisin, niin oppimisvalmiudet-käsitteelle.

Täällä hyvin määritelty oppimaan oppimista: https://tieteentermipankki.fi/wiki/Kasvatustieteet:oppimaan_oppiminen

**Comment by YSO-kokous** [comment]
Ei muutoksia suomeksi. Ruotsin termejä tutkitaan.

**Comment by mariaforsen** [comment]
Sv. inlärningsfärdigheter >lära sig att lära HT lära att lära

-eng. learning to learn (obs. inte _teaching_ to learn) 
-https://psykologiguiden.se/psykologilexikon/?Lookup=learning+to+learn
-https://dik.se/saco-akademikervecka-att-lara-att-lara
-https://termipankki.fi/tepa/fi/haku/oppimaan%20oppiminen
https://termipankki.fi/tepa/sv/s%C3%B6k/inl%C3%A4rningsf%C3%A4rdigheter
-https://www.sanakirja.fi/custom/en-sv-fi/inl%C3%A4rningsf%C3%A4rdigheter
-https://www.sanakirja.fi/custom/en-sv-fi/oppimaan%20oppiminen
-https://sv.wikipedia.org/wiki/L%C3%A4ra_att_l%C3%A4ra
-https://www.sanakirja.fi/custom/en-sv-fi/oppimisvalmius
-https://www.skolverket.se/skolutveckling/forskning-och-utvarderingar/artiklar-om-forskning/effektiva-larstrategier-ett-viktigt-uppdrag-for-skolan
-https://eur-lex.europa.eu/SV/legal-content/summary/lifelong-learning-key-competences.html
-i ALLFO flera näraliggande begrepp (oppimisvalmiudet= inlärningsförutsättningar, oppimiskyky=inlärningsförmåga, se även hierarkin
