### ISSUE TITLE
sukupolvet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12885]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupolvet](http://www.yso.fi/onto/yso/p2209)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Asiasanan hierarkia on jossain määrin harhaanjohtava ja kaipaa tarkistamista.

**Perustelut ehdotukselle**

Suppeammat asiasanat "suuret ikäluokat" jne. viittaavat joukkoon ihmisiä, eikä joukko ihmisiä ole luonnontieteellinen järjestelmä toisin kuin nykyhierarkia antaa ymmärtää.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjaston

**Comment by mirmaid** [comment]
Korjattu.
