### ISSUE TITLE
sulamisvesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12889]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sulamisvesi

**Ehdotettu termi ruotsiksi**

smältvatten

**Ehdotettu termi englanniksi**

meltwater

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu
Melinda:
sulamisvesi x 10
sulamisvedet x 2

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2002010022), [GEO](http://www.yso.fi/onto/gtk/GTK2015ID3580), [Tieteen termipankki](https://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:sulamisvesi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Spatiotemporal evaluation of snowmelt water and snowpack isotopes
(18O and 2H) and their application in subarctic catchment hydrology https://urn.fi/URN:ISBN:9789526239064 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [sulamisvesi](http://finto.fi/yse/fi/page/Y512889)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. smältvatten HT smältningsvatten, avsmältningsvatten
https://svenska.se/tre/?sok=sm%C3%A4ltvatten&pz=1
https://www.sanakirja.fi/custom/all/sulamisvesi
