### ISSUE TITLE
Vasikoiden pidempi vierihoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12883]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Vasikoiden pidempi vierihoito

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Cow-calf contact

**Tarkoitusta täsmentävä selite**

Vasikoiden kasvattaminen kontaktissa emään tai muuhun aikuiseen lehmään

**Perustelut ehdotukselle**

Termi on jo laajasti käytössä maidontuottajien keskuudessa ja alan tutkimuksessa. Englanninkielinen termi on myös vakiintunut ja määritelty katsausartikkeleissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [karjanhoito](http://www.yso.fi/onto/yso/p6049)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

 Vasikoiden vierihoito

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Luonnonvara- ja biotalouden tutkimus- sarjassa syyskuussa 2024 julkaistavassa maidontuottajille suunnatussa oppaassa, joka käsittelee vasikoiden pidempää vierihoitoa

**Ehdottajan organisaatio**

Luonnonvarakeskus
**Termiehdotus Fintossa:** [Vasikoiden pidempi vierihoito](http://finto.fi/yse/fi/page/Y512883)

**Comment by mariaforsen** [comment]
Jos todella cow-calfcontact? > sv. ko-kalvkontakt
https://www.slu.se/forskning/kunskapsbank/publicerat/notkreatur/hur-paverkas-mjolkforetagets-ekonomi-av-ko-kalvkontakt/
https://stud.epsilon.slu.se/14724/
https://lantbruksnytt.se/for-och-nackdelar-med-att-halla-ko-och-kalv-tillsammans/

Olisiko parempi muodossa "vasikoiden vierihoito"? Kun aika voi vaihdella, ja niin ainakin tuo cow-calfcontact sekä sv. vaihtelee (eri vaihtoehtoja)..

**Comment by mirmaid** [comment]
Jonkun verran Melindassa käytetty nykyistä _vierihoito_-termiä.

**Comment by mirmaid** [comment]
Juuri tuli vastaan: https://yle.fi/a/74-20110263

**Comment by mariaforsen** [comment]
Sv. on ollut rooming in, sitä ei käytetä tästä vasikka-asiasta (vain tässä merkityksessä https://www.kielitoimistonsanakirja.fi/#/vierihoito?searchMode=all )

**Comment by LeKorsu** [comment]
Kuinka tarpeellista on erotella eri nisäkkäiden vierihoto vai pärjättäisiinkö nykyisellä?

**Comment by mariaforsen** [comment]
Ruotsiksi eri termit näille eri asioille (tässähän on kyllä muitakin eroja kuin että laji on eri)
Rooming in: "inom förlossningsvården system där det nyfödda barnet under tiden efter förlossning på en BB-avdelning vistas tillsammans med sin moder i hennes vårdrum" /Nationalencyklopedin
Vasikoiden "vierihoidossa" sen sijaan on erilaisia malleja, ks. esim. https://nauta.fi/hyvinvoiva-nauta/vasikoiden-vierihoidossa-on-monia-malleja/

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa vasikoiden vierihoito. YSO-ylläpito pohtinee ohjaustermejä.

**Comment by mariaforsen** [comment]
Sv.  ko-kalvkontakt (eng. cow-calfcontact) HT samskötsel av ko och kalv https://www.slu.se/forskning/kunskapsbank/publicerat/notkreatur/hur-paverkas-mjolkforetagets-ekonomi-av-ko-kalvkontakt/
https://stud.epsilon.slu.se/14724/
https://lantbruksnytt.se/for-och-nackdelar-med-att-halla-ko-och-kalv-tillsammans/
https://www.theseus.fi/bitstream/handle/10024/861385/Smeds_Viktor.pdf;jsessionid=AEFFB4FCE9A33FDAACE1BC70584832C0?sequence=2
