### ISSUE TITLE
ksantaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12888]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ksantaatit

**Ehdotettu termi ruotsiksi**

xantater

**Ehdotettu termi englanniksi**

xanthates

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [orgaaniset yhdisteet](http://www.yso.fi/onto/yso/p3841)

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Ksantaatit), [LCSH](http://id.loc.gov/authorities/subjects/sh85148759)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sustainable mining in the Arctic environment : development of analytical methods for the determination of xanthates and application of the methods to environmental and process water samples https://urn.fi/URN:ISBN:9789526238425

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [ksantaatit](http://finto.fi/yse/fi/page/Y512888)

**Comment by mariaforsen** [comment]
Sv. xantater HT xantat, xantogenat
https://svenska.se/tre/?sok=xantat&pz=1
