### ISSUE TITLE
haikalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12880]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[haikalat](http://www.yso.fi/onto/yso/p12927)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tieteellisen nimen lisäys?

**Perustelut ehdotukselle**

Mihin tämä viittaa, vaihtelevia "väitteitä", vrt. esim. 
https://termipankki.fi/tepa/fi/haku/haikalat
https://finto.fi/afo/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp12927
Eli onko se squaliformes vai Lamniformes vai jotain ihan muuta?

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Vrt. myös:
https://fi.wikipedia.org/wiki/Sillihaikalat
https://fi.wikipedia.org/wiki/Piikkihaikalat
https://fi.wikipedia.org/wiki/Hait (selachii)

**Comment by mirmaid** [comment]
YSO-ylläpito tutkii.
