### ISSUE TITLE
dorvobáikepolitihkka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12892]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[dorvobáikepolitihkka](http://www.yso.fi/onto/yso/p23830)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

+pohjoissaamenkieliset ohjaustermit: dorvoohcciidpolitihkka ja asylapolitihkka 

**Perustelut ehdotukselle**

Ei niin laajasti käytössä, mutta kuitenkin käytössä [Norjan](https://www.regjeringen.no/se/dep/jd/Organisauvdna/etater-ogvirksomheter/Olgoriikkalaaiddirektorahta-ODI/id85817/) ja [Ruotsin puolella](https://www.riksdagen.se/se-SE/other-languages/davvisamegiella/dat-lea-eu/) rajaa viranomaisten sivuilla.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Ehdotus hyväksytään.
