### ISSUE TITLE
antisosiaalinen persoonallisuushäiriö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12894]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

antisosiaalinen persoonallisuushäiriö

**Ehdotettu termi ruotsiksi**

antisocial personlighetsstörning, antisocialt personlighetssyndrom

**Ehdotettu termi englanniksi**

antisocial personality disorder

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Epäsosiaalinen persoonallisuushäiriö (engl. antisocial personality disorder, lyh. ASPD tai APD), myös antisosiaalinen persoonallisuushäiriö, on persoonallisuushäiriö, jonka kantaja ei ymmärrä toisten tunteita tai erillisyyttä omasta itsestä samoin kuin muut tai vaihtoehtoisesti ei kykene ottamaan niitä huomioon tavalliseen tapaan.
https://fi.wikipedia.org/wiki/Ep%C3%A4sosiaalinen_persoonallisuus

**Ehdotettu yläkäsite YSOssa (LT)**

 [persoonallisuushäiriöt](http://www.yso.fi/onto/yso/p327)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550), [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

 ASP, epäsosiaalinen persoonallisuushäiriö

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:ISBN:978-951-51-9537-1

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [antisosiaalinen persoonallisuushäiriö](http://finto.fi/yse/fi/page/Y512894)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh85005772

**Comment by mirmaid** [comment]
Melindassa kerran _epäsosiaalinen persoonallisuus_.

Voisi ehkä ottaa päätermiksi muodon _epäsosiaalinen persoonallisuushäiriö_, joka näyttäisi olevan suomenkielisissä lääketieteellisissä aineistoissa enemmän käytetty.

**Comment by mariaforsen** [comment]
Sv. antisocial personlighetsstörning HT antisocialt personlighetssyndrom, dyssocial personlighetsstörning, dissocial personlighetsstörning, asocialitet (personlighetsstörningar)
jfr https://id.kb.se/find?q=Antisocial%20personality%20disorders 
https://finto.fi/mesh/fi/page/D000987
https://sv.wikipedia.org/wiki/Antisocial_personlighetsst%C3%B6rning
https://www.psykologiguiden.se/psykologilexikon/?Lookup=antisocialt%20personlighetssyndrom
https://mesh.kib.ki.se/term/D000987/antisocial-personality-disorderhttps://verktyg.internetmedicin.se/koder/diagnos/f00_f99/f60_f69/f60-specifika-personlighetsstorningar

**Comment by fantsby-m** [comment]
ICD-10:ssä on [epäsosiaalinen persoonallisuus](https://koodistopalvelu.kanta.fi/codeserver/pages/code-view-page.xhtml?callerViewId=%2Fpages%2Fcodelist-quick-search-page.xhtml&conceptCodeKey=100055539&hierarchyView=false&classificationType=1&rowIndex=0)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Päätermiksi antisosiaalinen persoonallisuus.
