### ISSUE TITLE
sosiaalisen läsnäolon teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12897]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sosiaalisen läsnäolon teoria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

social presence theory, presence theory

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Social presence theory explores how the "sense of being with another" is influenced by digital interfaces in human-computer interactions
https://en.wikipedia.org/wiki/Social_presence_theory

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 läsnäolon teoria

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Augmented reality in consumer retail : a presence theory approach 
https://urn.fi/URN:ISBN:978-952-335-973-4

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [sosiaalisen läsnäolon teoria](http://finto.fi/yse/fi/page/Y512897)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. teorin om social närvaro
http://www.diva-portal.se/smash/get/diva2:1181597/FULLTEXT01.pdf
https://kommunikatoren.webnode.page/l/teorin-om-social-narvaro/
https://www.diva-portal.org/smash/get/diva2:1737222/FULLTEXT01.pdf

**Comment by mirmaid** [comment]
_Sosiaalinen läsnäolon teorian (Short ym. 1976) mukaan sosiaalinen läsnäolo on subjektiivinen kokemus, joka vaihtelee sen mukaan, miten käytetty viestintäväline tukee sosiaalisten vihjeiden välittymistä ja niiden välittömyyttä_.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
