### ISSUE TITLE
nganasanin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12898]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nganasanin kieli

**Ehdotettu termi ruotsiksi**

nganasaniska

**Ehdotettu termi englanniksi**

Nganasan language

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Nganasanin_kieli

**Ehdotettu yläkäsite YSOssa (LT)**

 [samojedikielet](http://www.yso.fi/onto/yso/p7463)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:ISBN:978-951-51-9567-8
SuomiEtymologia ex silentio :Nganasanin äännehistoria ja kielikontaktit 

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [nganasanin kieli](http://finto.fi/yse/fi/page/Y512898)

**Comment by mariaforsen** [comment]
Sv. nganasaniska
https://id.kb.se/term/sao/Nganasaniska%20spr%C3%A5ket
