### ISSUE TITLE
dorvobáikeohccit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12891]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[dorvobáikeohccit](http://www.yso.fi/onto/yso/p6461)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

+pohjoissaamenkielinen ohjaustermi "dorvoohcci"

**Perustelut ehdotukselle**

Tämä termi on käytössä Norjan ja Ruotsin puolella rajaa, jopa [Norjan hallituksen sivuilla](https://www.regjeringen.no/se/dep/jd/Organisauvdna/Ossodagat/sisafarrenossodat-/id589391/) ja [Ruotsin Migrin sivuilla](https://www.migrationsverket.se/English/About-the-Migration-Agency/About-the-website/Other-languages/Davvisamegiella.html). On käytössä myös koulukirjoissa tuolla puolella rajaa.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Ehdotus hyväksytään.
