### ISSUE TITLE
geenisäätely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12907]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

geenisäätely

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/Regulation_of_gene_expression

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.uef.fi/en/article/doctoral-defence-of-ana-hernandez-de-sande-msc-11-dec-2023-genome-wide-study-of-primary-mirna

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [geenisäätely](http://finto.fi/yse/fi/page/Y512907)

**Comment by mariaforsen** [comment]
Onko siis sama kuin Meshin geeniekspression säätely? https://finto.fi/mesh/fi/page/D005786?clang=sv ?

(YSOn säätely on sv. justering, joten se ei sovi kovin hyvin tällaiseen)

Sv. genreglering HT reglering av genexpression, reglering av genuttryck, genuttrycksreglering
https://sv.wikipedia.org/wiki/Genreglering
https://www.rikstermbanken.se/search?q=genreglering&s=termer
https://mesh.kib.ki.se/term/D005786/gene-expression-regulation

**Comment by mirmaid** [comment]
^ Toivottavasti 😅🙈

**Comment by ilona-x** [comment]
Eli otettaisiinko tämä sanastoon ehdotetussa muodossa geenisäätely vai FinMeShin mukainen [geeniekspression säätely](http://www.yso.fi/onto/mesh/D005786)?

LCSH: [Genetic regulation](http://id.loc.gov/authorities/subjects/sh85053870) 
Variants
    Gene expression--Regulation
    Gene expression regulation
    Gene regulation

**Comment by FinMeSHienPaimentaja** [comment]
"Geenisäätely" on oikein mukavan ympäripyöreä, on monesti varmaankin melko samaa tarkoittava kuin "geeniekspression säätely", geenien ilmentymisen säätelyähän voi olla monessa kohdassa (transkriptio ym.). 

yst. terv. nimim. "perinnöllisyystiede pääaineena"

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa geenisäätely. Ohjaustermiksi geeniekspression säätely.
