### ISSUE TITLE
laki eläinten hyvinvoinnista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12905]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laki eläinten hyvinvoinnista

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvittu kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9789521450754

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [laki eläinten hyvinvoinnista](http://finto.fi/yse/fi/page/Y512905)

**Comment by jtuohini** [comment]
Mainittuun tietueeseen lisätty viittaus kohdeteokseen asianmukaisiin kenttiin niin suomeksi kuin ruotsiksi:

- 610 14 |a Suomi. |t Laki eläinten hyvinvoinnista. |0 (FIN11)000038009
- 610 14 |a Finland. |t Lag om djurvälfärd.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
