### ISSUE TITLE
data-avaruudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12906]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

data-avaruudet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

data spaces

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

According to the Commission Staff Working Document on Common European Data Spaces, “a common European data space brings together relevant data infrastructures and governance frameworks in order to facilitate data pooling and sharing.”
https://joinup.ec.europa.eu/collection/semic-support-centre/data-spaces

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.sitra.fi/en/publications/state-of-finnish-data-spaces/
State of Finnish data spaces : Experiences of pioneers in building the data economy

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [data-avaruudet](http://finto.fi/yse/fi/page/Y512906)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Dataspace

**Comment by mariaforsen** [comment]
Sv. dataområden HT datarymder
https://www.sitra.fi/sv/ordbok/dataomrade/
https://www.sbhss.eu/sv/bidra-till-skapandet-av-ett-dataomrade-for-smarta-samhallen/
https://www.regeringen.se/contentassets/6866c386b0ec492c8171c92c9c8922cf/en-reform-for-datadelning-sou-202396.pdf

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
