### ISSUE TITLE
viranomaisvalvonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12902]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

viranomaisvalvonta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://termipankki.fi/tepa/fi/haku/viranomaisvalvonta

**Perustelut ehdotukselle**

On yleinen termi, ja aina ei löydy ns. kohteen mukaista valvonnan tyyppiä, ja on vähemmän selkeä ja vähän vanhanaikaistakin käyttää ikään kuin ketjua viranomaiset-valvonta

**Ehdotettu yläkäsite YSOssa (LT)**

 [valvonta valvojan mukaan](http://www.yso.fi/onto/yso/p8032)

**Ehdotetut temaattiset ryhmät**

 [71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524), [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Eläinten hyvinvointilaki (2024)

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [viranomaisvalvonta](http://finto.fi/yse/fi/page/Y512902)

**Comment by mariaforsen** [comment]
Sv. myndighetstillsyn HT myndighetsövervakning, myndigheternas tillsyn
https://fho.sls.fi/uppslagsord/16719/myndighetsovervakning/
https://valter.sanakirja.fi/all/all/viranomaisvalvonta
https://www.sanakirja.fi/custom/all/viranomaisvalvonta
https://valvira.fi/sv/social-och-halsovard/myndighetstillsyn
https://www.finlex.fi/sv/laki/ajantasa/2006/20060044
läs https://termipankki.fi/tepa/fi/haku/viranomaisvalvonta

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

**Comment by fantsby-m** [comment]
Esiintyy toistuvasti myös lainsäädännössä:
https://www.google.com/search?q=%22viranomaisvalvonta%22+site%3Afinlex.fi

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
