### ISSUE TITLE
kelaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12903]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kelaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/31002

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kelaatio](http://finto.fi/yse/fi/page/Y512903)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kelaatio

**Comment by mariaforsen** [comment]
Olisiko kelatointi ohjaustermi?

Sv. kelering HT kelatering
https://www.alensa.se/ordbok/kelering.html
https://mesh.kib.ki.se/term/D015913/chelation-therapy
https://www.sanakirja.fi/custom/all/kelering
https://termipankki.fi/tepa/fi/haku/kelatointi

**Comment by mirmaid** [comment]
^ Varmaan mahdollinen, vaikka näyttää olevan suomeksi suosiossa lähinnä kauneudenhoidon yms. yhteydessä. Käsittelisin kuitenkin hierarkian suhteen kemiallisena reaktiona tms. soveltuva yläkäsite, eli "passiivisena".

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
