### ISSUE TITLE
asiakasturvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12901]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

asiakasturvallisuus

**Ehdotettu termi ruotsiksi**

klientsäkerhet

**Ehdotettu termi englanniksi**

client safety

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Asiakasturvallisuus on nostettu käsitteeksi potilasturvallisuuden rinnalle ja on yleisesti käytössä terveydenhuollossa. Esimerkiksi sosiaali- ja terveysministeriöllä on Asiakas- ja potilasturvallisuussuunnitelma. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Olen käyttänyt termiä useissa englanninkielisissä artikkeleissa, nyt olisin lisännyt termin ensimmäiseen suomenkieliseen artikkeliini asiasanaksi.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [asiakasturvallisuus](http://finto.fi/yse/fi/page/Y512901)

**Comment by mirmaid** [comment]
Sanastossa on _asiakasturvallisuus (sosiaalihuolto)_. https://github.com/Finto-ehdotus/YSE/issues/9051

**Comment by LeKorsu** [comment]
Pitääkö laajentaa tarkennetta, sosiaali- ja terveydenhuolto?

**Comment by ilona-x** [comment]
Tämän mukaan asiakasturvallisuus terveydenhuollon puolella = potilasturvallisuus:

**fi        asiakasturvallisuus**

määritelmä
tila, jossa asiakas saa tarvitsemansa palvelun oikeaan aikaan oikealla tavalla siten, että palvelusta aiheutuu mahdollisimman vähän haittaa ja että asiakas kokee olonsa turvalliseksi

huomautus
Sosiaalihuollossa asiakasturvallisuudella tarkoitetaan palvelujen järjestämistä, tuottamista ja toteuttamista siten, etteivät asiakkaan fyysinen, psyykkinen, sosiaalinen ja taloudellinen turvallisuus vaarannu.

**Terveydenhuollossa käytetään potilasturvallisuus-termiä. Siihen kuuluu hoidon turvallisuus, lääkehoidon turvallisuus sekä lääkinnällisten laitteiden turvallisuus.**

Sosiaali- ja terveydenhuollossa toimivien henkilöiden ja organisaatioiden on noudatettava sellaisia periaatteita ja toimintatapoja, joilla varmistetaan asiakasturvallisuus. Asiakasturvallisuuden kannalta henkilökunnan osaaminen ja sen varmistaminen ja kehittäminen on ensiarvoisen tärkeää.

Lähde: Sosiaali- ja terveyspalvelujen yhdenvertaisuuden käsitteet (THL, 2019) https://termipankki.fi/tepa/fi/haku/asiakasturvallisuus

**Comment by mariaforsen** [comment]
Hyvä pitää termit erillään. Sairaanhoidossa termi on ruotsiksi patientsäkerhet, ja sosiaalihuollossa klientsäkerhet.

**Comment by YSO-kokous** [comment]
PÄÄTÖS:

asiakasturvallisuus (terveydenhuolto) KÄYTÄ potilasturvallisuus

Ei muita muutoksia/lisäyksiä sanastoon.
