### ISSUE TITLE
narratiivinen identiteetti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12910]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

narratiivinen identiteetti

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

narrative identity

**Tarkoitusta täsmentävä selite**

https://yle.fi/aihe/artikkeli/2019/06/12/kuka-kirjoittaa-elamantarinasi
https://helda.helsinki.fi/items/7e9494f4-d0e8-41da-96be-d18c9ec9822b "hmiselle on ominaista sanoittaa elämäänsä ja kertoa tarinoita oman elämänsä tapahtumista. Kertomalla tarinoita itsestään ihminen luo ja rakentaa identiteettiään (esim. McAdams, 1985; 2006; Bruner, 1990)."

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa
Ko. termiä on käytetty Melindassa vapaana asiasanana muutamassa teoksessa/artikkelissa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [identiteetti](http://www.yso.fi/onto/yso/p9743)

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543), [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562), [87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:ISBN:978-952-61-5114-4 ;  

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [narratiivinen identiteetti](http://finto.fi/yse/fi/page/Y512910)

**Comment by mirmaid** [comment]
N. 10 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. narrativ identitet
https://www.psykologiguiden.se/psykologilexikon/?Lookup=narrativ
https://www.sprakforskning.se/forskningsbloggen2/2018/personligtberattande
https://www.mdu.se/forskning/forskningsprojekt/utbildningsvetenskap-och-matematik/det-gransoverskridande-jaget-narrativ-och-kulturell-identitet-i-autofiktiv-migrationslitteratur
https://libris.kb.se/bib/14932196

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mirmaid** [comment]
Sopii tässä https://erepo.uef.fi/handle/123456789/31518
