### ISSUE TITLE
douglaskuuset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12917]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

douglaskuuset

**Ehdotettu termi ruotsiksi**

douglasgran

**Ehdotettu termi englanniksi**

douglas-fir

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Douglaskuuset
Douglaskuuset (Pseudotsuga) on havupuusuku mäntykasvien (Pinaceae) heimossa.[2][3] Sukuun kuuluu lajien määrittelystä riippuen 4–6 lajia. Douglaskuuset ovat suurehkoja ainavihantia puita, jotka kasvavat luonnonvaraisina läntisessä Pohjois-Amerikassa ja itäisessä Aasiassa. Nimestään huolimatta douglaskuuset eivät kuulu kuusiin (Picea) vaan ovat läheisempää sukua lehtikuusille (Larix).[1][4][5][6]

**Ehdotettu yläkäsite YSOssa (LT)**

 [lehtikuuset](http://www.yso.fi/onto/yso/p20489)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533), [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-5980-66-0 Douglas-fir – an option for Europe

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [douglaskuuset](http://finto.fi/yse/fi/page/Y512917)

**Comment by mariaforsen** [comment]
Sv. 
-douglasgranar (släkte)
https://artfakta.se/taxa/1005726/information
https://laji.fi/sv/taxon/MX.37809

-douglasgran (art)
https://artfakta.se/taxa/219883/information?lang=sv

**Comment by ilona-x** [comment]
Nimekkeen (Douglas-fir – an option for Europe) perusteella aineisto käsittelee lännendouglaskuusta = douglas fir, mutta halutaanko tässä kuitenkin ottaa laajempi termi douglaskuuset? Nyt ehdotuksessa suomeksi douglaskuuset ja englanniksi douglas fir, jotka eivät vastaa toisiaan.
 
https://fi.wikipedia.org/wiki/L%C3%A4nnendouglaskuusi | https://en.wikipedia.org/wiki/Douglas_fir
https://fi.wikipedia.org/wiki/Douglaskuuset | https://en.wikipedia.org/wiki/Pseudotsuga

https://laji.fi/taxon/MX.37809 Douglaskuuset – Pseudotsuga
https://laji.fi/taxon/MX.37810 Lännendouglaskuusi – Pseudotsuga menziesii

LCSH:
Douglas fir http://id.loc.gov/authorities/subjects/sh85039200
Pseudotsuga http://id.loc.gov/authorities/subjects/sh85108310

AFOssa molemmat:
[douglaskuuset](https://finto.fi/afo/fi/page/p5567)
[douglaskuusi](https://finto.fi/afo/fi/page/p5566)

**Comment by mariaforsen** [comment]
Sama tilanne ruotsiksi: douglasgranar, douglasgran
https://artfakta.se/taxa/219883/information
https://artfakta.se/taxa/1005726/information
