### ISSUE TITLE
kaanonit (valikoimat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12914]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kaanonit (valikoimat)](http://www.yso.fi/onto/yso/p9577)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi kulttuurikaanonit. Ehkä myös taidekaanonit.

**Perustelut ehdotukselle**

Linkitin käsitteen tähän Wikidata-kohteeseen, joka on suomeksi kulttuurikaanon.
https://www.wikidata.org/wiki/Q20080754

Sitten sivuhuomio: tajusin myös, että kaanon tarkoittaa fiktion näkökulmasta kahta eri asiaa. En tiedä tarviiko tätä huomioida sanastossa mutta tiedoksi. Fiktiossa kaanon voi siis tarkoittaa myös "the body of works taking place in a particular fictional world that are widely considered to be official or authoritative" eli esim. Star Wars -kaanon, Sherlock Holmes -kaanon jne.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by jtuohini** [comment]
Samalla voisi lisätä siltaukset LCSH-sanaston hieman tarkempaan asiasanaan [**Canon (Literature)**](http://id.loc.gov/authorities/subjects/sh85019643), jonka määritelmä on "Here are entered works on the accepted or sanctioned list of works which have achieved recognition in literary history for their superior qualities."

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermit:
kulttuurikaanonit KÄYTÄ kaanonit (valikoimat)
taidekaanonit KÄYTÄ kaanonit (valikoimat)
