### ISSUE TITLE
nanokuidut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12919]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nanokuidut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://aaltodoc.aalto.fi/server/api/core/bitstreams/63f9565c-2b45-4057-aec7-b5f2caac4704/content

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [nanokuidut](http://finto.fi/yse/fi/page/Y512919)

**Comment by mariaforsen** [comment]
Onko sama asia kuin nanosäikeet? https://finto.fi/mesh/fi/page/D057139?clang=sv 

Sv. nanofibrer HT nanofiber
https://svenska.se/tre/?sok=fiber&pz=1
https://www.vetenskaphalsa.se/darfor-vill-forskarna-att-vi-inte-andas-in-nanofibrer/
https://www.abo.fi/nyheter/trabaserade-1d-nanomaterial-ger-genombrott-inom-3d-printning/
https://betongvarlden.se/tag/nanofibrer/

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Nanofiber

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
