### ISSUE TITLE
Ars

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12918]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ars](http://www.yso.fi/onto/yso/p9873)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko selkeämpi termi Ars-näyttelyt? Vrt. Wikipedia: https://fi.wikipedia.org/wiki/Ars-n%C3%A4yttelyt

**Perustelut ehdotukselle**

Ars on monimerkityksinen termi eikä pelkän termin perusteella voi vielä päätellä mihin käsite viittaa. Muutin jo englannin termiksi "Ars (art exhibitions)", koska varsinkaan englanninkieliselle käyttäjälle termi ei välttämättä avaudu lainkaan.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by jtuohini** [comment]
Ehkä koko asiasana pitäisi poistaa Ysosta, kun kyseessä on yksittäinen nimetty tapahtuma(sarja), joka on jo auktorisoitu Kantoon (http://urn.fi/URN:NBN:fi:au:finaf:000219808)?

**Comment by mirmaid** [comment]
Ehkä jätetään tässä vaiheessa entiselleen.

**Comment by mariaforsen** [comment]
Termi on kyllä nykyisessä muodossaan epäselvä.

**Comment by mirmaid** [comment]
Mietin vaan, että minkä verran kannattaa laittaa työaikaa sanaston ja tietokannan muutoksiin, jos tämä kuitenkin jossain vaiheessa poistuu.

**Comment by YSO-kokous** [comment]
Muutetaan päätermiksi Ars-näyttelyt.

Ensin päätettiin poistaa, mutta sitten päätös pyörrettiin. Käsitettä ei ole käytetty Melinda-kuvailussa, mutta on kuitenkin käytetty Ylellä.

**Comment by ilona-x** [comment]
YLEllä https://yle.fi/t/18-207437/fi

**Comment by mariaforsen** [comment]
Sv. Ars-utställningar
