### ISSUE TITLE
olympialaččat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12913]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[olympialaččat](http://www.yso.fi/onto/yso/p7930)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pohjoissaamenkielinen ohjaustermi: olympiagilvvut

**Perustelut ehdotukselle**

Käytössä [asiasanana Ávvir-lehdessä](https://www.avvir.no/tag/olympiagilvvut/) ja koulukirjoissa Norjan puolella.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Ehdotus hyväksytään.
