### ISSUE TITLE
fosforesenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12923]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fosforesenssi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 fosforenssi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/30784?locale-attribute=fi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [fosforesenssi](http://finto.fi/yse/fi/page/Y512923)

**Comment by mariaforsen** [comment]
Sv. fosforescens
https://termipankki.fi/tepa/sv/s%C3%B6k/fosforescens
https://www.rikstermbanken.se/search?q=fosforescens&s=termer

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Fosforesenssi
http://id.loc.gov/authorities/subjects/sh85101112

2 viitettä Melindassa.
