### ISSUE TITLE
implementaatiotiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12928]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

implementaatiotiede

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

implementation science

**Tarkoitusta täsmentävä selite**

https://impsciuw.org/implementation-science/learn/implementation-science-overview/
"✪ Glasgow, Eckstein, and ElZarrad (2013): Implementation science is the 'application and integration of research evidence in to practice and policy.'"

**Perustelut ehdotukselle**

Uusi tieteenala, tarve käyttää sisällönkuvailussa 

**Ehdotettu yläkäsite YSOssa (LT)**

 [tieteenalat](http://www.yso.fi/onto/yso/p352)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://implementation science https://authorities.loc.gov/cgi-bin/Pwebrecon.cgi?AuthRecID=11882380&v1=1&HC=1&SEQ=20240805032818&PID=cgvOVCCEHVzgCyS3gOsHQOsR3ajYZO)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/019137700

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [implementaatiotiede](http://finto.fi/yse/fi/page/Y512928)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. implementeringsvetenskap HT implementeringsforskning, implementationsforskning
https://finto.fi/mesh/fi/page/D000077626?clang=sv
https://mesh.kib.ki.se/term/D000077626/implementation-science
https://sv.wikipedia.org/wiki/Implementeringsvetenskap
https://valtel.ostersund.se/index.php/2022/03/15/highway-to-health-vagen-mot-en-lyckad-implementering-av-digitala-losningar/

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
