### ISSUE TITLE
atsobentseenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12922]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

atsobentseenit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://aaltodoc.aalto.fi/server/api/core/bitstreams/043cdf3c-1f2f-4c71-ace7-d59ff4dc3335/content

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [atsobentseenit](http://finto.fi/yse/fi/page/Y512922)

**Comment by mariaforsen** [comment]
Sv. azobensener 
https://www.forskning.se/2002/11/21/ljuset-styr-plastfilmens-egenskaper/
