### ISSUE TITLE
mahalaukun kiertymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12920]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mahalaukun kiertymä](http://www.yso.fi/onto/yso/p26348)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Esiintyy myös muodossa vatsalaukun kiertymä.

**Perustelut ehdotukselle**

Ks. esim. 
https://fi.wikipedia.org/wiki/Vatsalaukunkiertym%C3%A4
https://www.agria.fi/koira/artikkeleita/sairaudet-ja-terveys/koiran-vatsalaukunkiertyma-vaatii-pikaista-hoitoa/

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by jtuohini** [comment]
Ja KT-muodoksi varmaan sama myös yhdyssanana? (Ehkä varsinaisen käytettävän muodonkin pitäisi olla nimenomaan yhdyssanana.)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D013277

Lääketieteen termit: volvulus ventriculi, gastric volvulus | mahalaukun kiertymä, ventrikkelivolvulus

**Comment by mirmaid** [comment]
Nyt huomautus rajaa koiriin, mutta on tätä muillakin lajeilla, vaikka koirilla kai sitten erityisen paljon.

**Comment by mariaforsen** [comment]
YSOn ruotsinkielinen termi viittaa koirien sairauteen, Meshin termi ihmisten..

**Comment by mirmaid** [comment]
Melindassa koirista.

**Comment by YSO-kokous** [comment]
Lisätään tarkenne: mahalaukun kiertymä (eläintaudit)
Ohjaustermi: 
vatsalaukun kiertymä KÄYTÄ mahalaukun kiertymä
Yhteenkirjoitetut muodot ohjaustermeiksi myös.

Otetaan huomautus pois. Tauti voi olla myös kissalla.
