### ISSUE TITLE
Charcot'n jalka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12929]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Charcot'n jalka](http://www.yso.fi/onto/yso/p26607)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi neurogeeninen artropatia.

**Perustelut ehdotukselle**

MeSHissä se on tämän käytettävä termi. Vrt. myös englannin kieli. MeSHissä olisi myös lisäsynonymiaa tälle, jos katsotaan tarpeelliseksi.
https://finto.fi/mesh/fi/page/D001177

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Lääketieteen termit: 
neurogeeninen artropatia:  neuroartropatia, neuropaattinen artropatia | hermoperäinen, heikentyneestä kipu- ja asentotunnosta johtuva tai niihin liittyvä nivelsairaus, joka voi hoitamattomana edetä nopeasti; ks. esim. Charcot’n jalka

Charcot’n jalka: Charcot´n neuro-osteoartropatia | etenkin diabeteksen yhteydessä esiintyvä nilkan ja jalkaterän neurogeeninen artropatia, joka hoitamattomana voi johtaa näiden virheasentoon ja jopa amputaatioon

**Comment by mirmaid** [comment]
Varmaan mahdollista ottaa kuitenkin päätermiksi ehdotettu muoto.

**Comment by ilona-x** [comment]
FinMeSHissä  Charcot-jalka on ohjausterminä [diabeetikon jalka](http://www.yso.fi/onto/mesh/D017719) -termille eli tämä Charcot'n jalka on diabetekseen liitännäissairaus ja tuo neurogeeninen artropatia lienee yleisempi eli en lähtisi korvaamaan tätä sillä, vaan ottaisin erikseen, mikäli termille on tarve.

**Comment by YSO-kokous** [comment]
PÄÄTÖS: Ei muutoksia. Ks. keskustelu yllä.
