### ISSUE TITLE
itsetyydytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12925]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[itsetyydytys](http://www.yso.fi/onto/yso/p17262)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "autoerotiikka"

**Perustelut ehdotukselle**

Käytetty nimitys, ks. esim. https://finna.fi/Record/helka.9910208633506253?sid=4761719378

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Onko kuitenkin laajempi merkitykseltään?

**Comment by YSO-kokous** [comment]
PÄÄTÖS: Ei oteta ohjaustermiä. Autoerotiikka ei ole sama käsite kuin itsetyydytys.
