### ISSUE TITLE
miehittämättömät ajoneuvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12927]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[miehittämättömät ajoneuvot](http://www.yso.fi/onto/yso/p24152)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT autonomiset ajoneuvot

**Perustelut ehdotukselle**

xxxx

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Huomasin, että itseohjautuvat ajoneuvot on nyt ohjausterminä [robottiautot](http://www.yso.fi/onto/yso/p29485)-termille.

**Comment by mirmaid** [comment]
^ Sekin olisi varmaan parempi ohjata tähän.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

autonomiset ajoneuvot KÄYTÄ miehittämättömät ajoneuvot
itseohjautuvat ajoneuvot KÄYTÄ miehittämättömät ajoneuvot

Poistetaan robottiautoilta ohjaustermi itseohjautuvat ajoneuvot.
