### ISSUE TITLE
El Niño merivirta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12933]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

El Niño merivirta

**Ehdotettu termi ruotsiksi**

El Niño havsström

**Ehdotettu termi englanniksi**

El Niño Current

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [merivirrat](http://www.yso.fi/onto/yso/p16780)

**Ehdotetut temaattiset ryhmät**

 [13 Hydrologia](http://www.yso.fi/onto/yso/p26580)

**Vaihtoehtoiset termit**

 El Niño ilmiö

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh85041456), [Wikipedia](https://fi.wikipedia.org/wiki/El_Ni%C3%B1o)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013282331

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [El Niño merivirta](http://finto.fi/yse/fi/page/Y512933)

**Comment by mariaforsen** [comment]
Yleensä meteorologinen ilmiö, ei pelkästään merivirta..

Sv. El Niño (meteorologiska fenomen) HT El Niño, El Niño-fenomen
/uppslagsverk/encyklopedi/lång/el-nino
https://www.klimatfakta.info/article.php?i=2993
https://sv.wikipedia.org/wiki/El_Ni%C3%B1o
https://www.ui.se/landguiden/svara-ord/el-nino/
https://id.kb.se/term/sao/El%20Ni%C3%B1o

**Comment by LeKorsu** [comment]
Olen kommentoinut Niñan kohdalle, että olen myös sitä mieltä, että kyse ei ole merivirrasta vaan sää- tai meteorologisesta ilmiöstä ja komppaan Mariaa.

**Comment by YSO-kokous** [comment]
Hyväksytään. Päätermiksi El Niño -ilmiö.
