### ISSUE TITLE
La Niña merivirta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12934]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

La Niña merivirta

**Ehdotettu termi ruotsiksi**

La Niña havsström

**Ehdotettu termi englanniksi**

La Niña Current

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [merivirrat](http://www.yso.fi/onto/yso/p16780)

**Ehdotetut temaattiset ryhmät**

 [13 Hydrologia](http://www.yso.fi/onto/yso/p26580)

**Vaihtoehtoiset termit**

 La Niña ilmiö

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh99002366), [Wikipedia](https://fi.wikipedia.org/wiki/La_Ni%C3%B1a)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013282331

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [La Niña merivirta](http://finto.fi/yse/fi/page/Y512934)

**Comment by mariaforsen** [comment]
Onko enemmänkin kuin merivirta? Tämä käsitellään yleensä meteorologisena ilmiönä... 

Sv. La Niña (havsström/väderfenomen)?
https://fof.se/artikel/2012/1/el-nino-och-la-nina-barnen-som-styr-var-planet/

**Comment by LeKorsu** [comment]
Minäkin laittaisin tarkennukseksi mieluummin sääilmiön kuin merivirran.

**Comment by FinMeSHienPaimentaja** [comment]
Wikipedian mukaan:


"El Niño on merivirran ajoittainen muuttuminen Tyynellämerellä.

..//..

Lämpeneminen ilmenee 2–7 vuoden jaksoissa (tavallisimpia ovat 3–4 vuoden jaksot), ja kukin lämmin kausi kestää vuoden tai puolitoista vuotta.

..//..

Päinvastainen poikkeama normaalitilasta on La Niña, jolloin Tyynenmeren päiväntasaajanläheisillä osilla on keskimääräistä kylmempää vettä.

Ilmakehän osuus ilmiöstä on nimeltään eteläinen heilahtelu, ja koko ilmiötä kutsutaan lyhenteellä ENSO (El Niño – Southern Oscillation)."


https://fi.wikipedia.org/wiki/El_Ni%C3%B1o


https://www.who.int/news-room/fact-sheets/detail/el-nino-southern-oscillation-(enso)

https://oceanservice.noaa.gov/facts/ninonina.html

**Comment by YSO-kokous** [comment]
Hyväksytään. Päätermiksi La Niña -ilmiö. Ohjaustermiksi La Nina -ilmiö.

**Comment by mariaforsen** [comment]
Sv. La Niña (meteorologiska fenomen) HT La Niña, La Niña-fenomen(et) https://id.kb.se/find?q=El%20Ni%C3%B1o
/uppslagsverk/encyklopedi/lång/la-nina
https://sv.wikipedia.org/wiki/La_Ni%C3%B1a
