### ISSUE TITLE
hopit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12931]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hopit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Hopit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

0140195459
1860076122
0486229599

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [hopit](http://finto.fi/yse/fi/page/Y512931)

**Comment by mariaforsen** [comment]
Sv. hopi (folk) HT hopi-indianer, hopiindianer
https://id.kb.se/find?q=hopi

**Comment by krinay** [comment]
Suomeksikin ohjaustermi _hopi-intiaanit_ olisi tarpeellinen.
