### ISSUE TITLE
pääaine

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12938]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pääaine

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://aaltodoc.aalto.fi/items/becca4f8-a36b-4897-8daa-5dee42e6f696

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pääaine](http://finto.fi/yse/fi/page/Y512938)

**Comment by mirmaid** [comment]
Aineistossa esseen aiheena pääaineen vaihtaminen, tässä yhteydessä yksikkö tuntui luontevalta, mutta monikko varmaan ok sekin. Sanastossa on jo _sivuaineet_.

**Comment by mariaforsen** [comment]
Sv. huvudämnen HT huvudområden
https://termipankki.fi/tepa/fi/haku/p%C3%A4%C3%A4aine
https://www.rikstermbanken.se/search?q=huvud%C3%A4mne&s=termer

**Comment by tpalonen** [comment]
Tarviiko sulkutarkenteen?

"Moussakan pääaineena toimivat munakoisot.." https://kotiliesi.fi/ruoka/10-herkullista-reseptia-kreikan-ja-italian-maut-vievat-valimeren-rannalle/
"Esimerkiksi terästeollisuudessa pölyn pääaine, rautaoksidi... on sinänsä vaaraton aine."
https://metallinjalostajat.teknologiateollisuus.fi/fi/puhtaampi-tulevaisuus/paastot-ilmaan-ja-veteen

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa pääaineet (oppiaineet).

YSO-ylläpito tutkii, tarvitseeko sivuaineet-käsitteelle sulkutarkennetta.
