### ISSUE TITLE
bolometrit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12943]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

bolometrit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://aaltodoc.aalto.fi/items/2cb41658-fea3-499e-960a-934333a41ce5

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [bolometrit](http://finto.fi/yse/fi/page/Y512943)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Bolometri
http://id.loc.gov/authorities/subjects/sh85015445

2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. bolometrar 
https://termipankki.fi/tepa/sv/s%C3%B6k/bolometer

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
