### ISSUE TITLE
brutalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12942]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

brutalismi

**Ehdotettu termi ruotsiksi**

brutalism

**Ehdotettu termi englanniksi**

brutalism

**Tarkoitusta täsmentävä selite**

"Brutalismi eli betonibrutalismi on modernistisen arkkitehtuurin suuntaus, joka kehittyi 1950-luvulla reaktiona hillitylle modernismille."

**Perustelut ehdotukselle**

Arkkitehtuurisuuntaus, jonka tuntuu herättävän keskustelua ja kiinnostavan monia. Olisi siis hyvä, jos löytyisi myös YSOsta. Melindassa brutalismia on käytetty muutamaan kertaan vapaana asiasanana, ja kirjallisuutta Melindasta löytyy paljonkin. Myös Ylellä tätä on ilmeisesti käytetty kuvailussa, tässä ainakin esiintyy asiasanana: https://yle.fi/aihe/artikkeli/2007/06/08/satunnainen-matkailija-pasilassa

**Ehdotettu yläkäsite YSOssa (LT)**

 [tyylit](http://www.yso.fi/onto/yso/p421)

**Ehdotetut temaattiset ryhmät**

 [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 betonibrutalismi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [betonirakennukset](http://www.yso.fi/onto/yso/p7394), [betoni](http://www.yso.fi/onto/yso/p11671), [elementtirakentaminen](http://www.yso.fi/onto/yso/p5950)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85017364), [Wikidata](https://www.wikidata.org/wiki/Q994776)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/019124527
https://melinda.kansalliskirjasto.fi/byid/018159957
https://melinda.kansalliskirjasto.fi/byid/017856959
https://melinda.kansalliskirjasto.fi/byid/018645029
https://melinda.kansalliskirjasto.fi/byid/018040416

**Ehdottajan organisaatio**

Tuomas / Finto
**Termiehdotus Fintossa:** [brutalismi](http://finto.fi/yse/fi/page/Y512942)

**Comment by tpalonen** [comment]
Facebookkia käyttäville vinkkinä, sieltä löytyy suosittu ryhmä Brutalism Appreciation Society, jossa näkee välillä kuvia myös suomalaisesta arkkitehtuurista: https://www.facebook.com/groups/824626641393544

**Comment by ilona-x** [comment]
MAO/TAO:
[brutalismi](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp6970), jolla ST
[betonibrutalismi](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp8886)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
