### ISSUE TITLE
beetasäteily

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12945]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[beetasäteily](http://www.yso.fi/onto/yso/p5257)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT betahajoaminen, betasäteily

**Perustelut ehdotukselle**

xxxx

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/T%C3%A4htitiede:betahajoaminen
