### ISSUE TITLE
kvanttipiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12944]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kvanttipiirit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://aaltodoc.aalto.fi/items/2cb41658-fea3-499e-960a-934333a41ce5

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kvanttipiirit](http://finto.fi/yse/fi/page/Y512944)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kvanttipiiri

2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. kvantkretsar 
https://www.su.se/sok-kurser-och-program/ml730n-1.654854
https://www.nyteknik.se/nyheter/google-bygger-egen-kvantkrets/644494
https://www.kth.se/om/nyheter/centrala-nyheter/kth-forskare-ett-steg-narmare-att-mojliggora-integrerade-kvantoptiska-kretsar-1.749362

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
