### ISSUE TITLE
kasviot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12948]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kasviot](http://www.yso.fi/onto/yso/p2598)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

YSO:ssa lisätään LT-suhde asiasanaan "hakuteokset" ja SLM:ssä vaihdetaan LT-suhde "ei-fiktiiviset teokset" --> "hakuteokset" ja lisätään LT-suhde "kuvateokset"

**Perustelut ehdotukselle**

Kaikki kasviot ovat sekä hakuteoksia että kuvateoksia, ja sanastojen hierarkian pitäisi vastata tätä.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Huomiona tähän, että kasviot päätettiin muuttaa SLM:ssa muotoon [kasvioppaat ](http://urn.fi/URN:NBN:fi:au:slm:s477)
https://github.com/Finto-ehdotus/YSE/issues/12815#issuecomment-2314544197

**Comment by mirmaid** [comment]
YSOssa nyt siis sekä _kasviot_, että _herbaariot_ - varmaan hyvä tarkentaa näiden merkityksiä.

**Comment by jtuohini** [comment]
Ehdotus määritelmiksi: kasviolle "Määräalueen kasviston järjestelmällisesti kuvaava teos" ja herbaariolle "kasvikokoelma", jotka kumpikin poimittu suoraan Kielitoimiston sanakirjasta (https://www.kielitoimistonsanakirja.fi/kasvio).

**Comment by jtuohini** [comment]
Ja nyt kun älysin kurkistaa itse sanastoon, niin herbaariohan onkin jo kauniisti määritelty siellä, ja suhde **kokoelmat**-asiasanaankin on kunnossa.

**Comment by YSO-kokous** [comment]
Muutetaan kasviot-käsitteen päätermiksi kasvioppaat.

Lisätään ohjaustermit:

kasviot (kasvioppaat) KÄYTÄ kasvioppaat
kasviot (herbaariot) KÄYTÄ herbaariot

Muutetaan herbaarion huomautus määritelmäksi.
