### ISSUE TITLE
jakojärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12958]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jakojärjestelmät

**Ehdotettu termi ruotsiksi**

fördelningssystem

**Ehdotettu termi englanniksi**

pay-as-you-go system

**Tarkoitusta täsmentävä selite**

- 

**Perustelut ehdotukselle**

Saimme palautetta Eläketurvakeskuksesta: "Olisiko sanastoon mahdollista lisätä termit: Jakojärjestelmä - pay-as-you-go system - fördelningssystem rNäitä termejä käytetään kuvaamaan eläkkeiden rahoitusta. Eläkkeet ovat hyvinvointivaltion suurin yksittäinen menoerä. Suurin osa eläkkeistä rahoitetaan jakojärjestelmällä, jossa siis työssäkäyvät jakavan osan palkastaan eläkeläisille. Rahastoivassa järjestelmässä työssäkäyvien eläkemaksut sijoitetaan finanssimarkkinoille. Termiä jakojärjestelmä käytetään englanniksi myös yleisesti kuvaamaan rahoitustapaa, jossa maksut siirtyvät suoraan etuuksiksi. On ongelmallista, että tällaisia perustermejä ei löydy asiasanoina."

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ks. ed.

**Ehdottajan organisaatio**

finto-posti / Eläketurvakeskuksesta
**Termiehdotus Fintossa:** [jakojärjestelmät](http://finto.fi/yse/fi/page/Y512958)

**Comment by ilona-x** [comment]
Pitäisikö rajata vain eläkkeisiin vai yleisempänä terminä: https://termipankki.fi/tepa/fi/haku/jakoj%C3%A4rjestelm%C3%A4

**Comment by mariaforsen** [comment]
Sv. fördelningssystem (pensionssystem) HT ofonderade pensionssystem

..monimerkityksinen, joten ruotsiksi pitää miten vain tarkentaa

/uppslagsverk/encyklopedi/lång/fördelningssystem
https://www.rikstermbanken.se/search?q=f%C3%B6rdelningssystem&s=termer
vs. https://www.voltimum.se/glossary/fordelningssystem

**Comment by mirmaid** [comment]
Jakojärjestelmät (eläkejärjestelmät)?

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa jakojärjestelmät (eläkejärjestelmät).
