### ISSUE TITLE
(kaasu)kaarihitsaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12951]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

(kaasu)kaarihitsaus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://lutpub.lut.fi/handle/10024/166533

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [(kaasu)kaarihitsaus](http://finto.fi/yse/fi/page/Y512951)

**Comment by mariaforsen** [comment]
Sv. gasbågsvetsning
https://termipankki.fi/tepa/fi/haku/kaasukaarihitsaus
https://www.sanakirja.fi/custom/all/kaasukaarihitsaus

**Comment by mirmaid** [comment]
Ehkä sekä kaarihitsaus että kaasukaarihitsaus tai vain tarkempi. Jos nyt oikein ymmärrän, kaasuhitsaus on eri asia, https://fi.wikipedia.org/wiki/Hitsaus.

Melinda 22 / 10.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon kaksi käsitettä:

kaarihitsaus
kaasukaarihitsaus

**Comment by mariaforsen** [comment]
Sv. -bågsvetsning
-gasbågsvetsning
https://termipankki.fi/tepa/fi/haku/kaasukaarihitsaus
https://www.sanakirja.fi/custom/all/kaasukaarihitsaus
https://www.rikstermbanken.se/search?q=b%C3%A5gsvetsning&s=termer
