### ISSUE TITLE
kappelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12953]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kappelit](http://www.yso.fi/onto/yso/p11797)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yläkäsitteeksi uskonnolliset rakennukset

**Perustelut ehdotukselle**

On uskonnollinen rakennus

**Ehdottajan organisaatio**

KK/MP

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjan mukaan kappeli on "pienehkö kirkko t. sen osa t. huone kirkollisia toimituksia varten" (https://www.kielitoimistonsanakirja.fi/kappeli), joten kaikki kappelit eivät ole itsenäisiä rakennuksia, mistä taas seuraa, että ehdotettu LT-suhde ei päde kaikissa tilanteissa. Ehkäpä kappelit-asiasana vaatii määritelmän sanastoon?

**Comment by mirmaid** [comment]
Tällä on yksi alakäsite, vs. muut kappeleiksi nimetyt.

**Comment by mirmaid** [comment]
^^ Totta, mutta sama koskee myös ainakin rukoushuoneet ja pyhäköt -käsitteitä. Sijoittaminen samaan paikkaan kirkkojen jne. kanssa on kuitenkin niin käyttäjäystävällistä, että ohittaisin tässä tiukan hierarkiatulkinnan. Vaikea keksiä mitä haittaa ratkaisusta voisi olla mitään tulevaisuuden hakuun tai kuvailuun kohdistuvaa koneellista päättelyäkään ajatellen.
