### ISSUE TITLE
teatterineuvokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12950]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

teatterineuvokset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Jostain syystä jäänyt pois YSOn *neuvokset listalta

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Teatterineuvos)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Teuvo Puro : teatterineuvos ja elokuvapioneeri / Kari Glödstaf

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [teatterineuvokset](http://finto.fi/yse/fi/page/Y512950)

**Comment by mariaforsen** [comment]
Sv. teaterråd (hederstitlar)
https://www.sanakirja.fi/custom/all/teatterineuvos
