### ISSUE TITLE
rahastoivat järjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12959]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rahastoivat järjestelmät

**Ehdotettu termi ruotsiksi**

fonderat system

**Ehdotettu termi englanniksi**

funded system

**Tarkoitusta täsmentävä selite**

Saimme palautetta Eläketurvakeskuksesta: "Olisiko sanastoon mahdollista lisätä termit:  rahastoiva järjestelmä - funded system - fonderat system Näitä termejä käytetään kuvaamaan eläkkeiden rahoitusta. Eläkkeet ovat hyvinvointivaltion suurin yksittäinen menoerä. Suurin osa eläkkeistä rahoitetaan jakojärjestelmällä, jossa siis työssäkäyvät jakavan osan palkastaan eläkeläisille. Rahastoivassa järjestelmässä työssäkäyvien eläkemaksut sijoitetaan finanssimarkkinoille. Termiä jakojärjestelmä käytetään englanniksi myös yleisesti kuvaamaan rahoitustapaa, jossa maksut siirtyvät suoraan etuuksiksi. On ongelmallista, että tällaisia perustermejä ei löydy asiasanoina."

**Perustelut ehdotukselle**

Ks. ed.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ks. ed.

**Ehdottajan organisaatio**

finto-posti / Eläketurvakeskus
**Termiehdotus Fintossa:** [rahastoivat järjestelmät](http://finto.fi/yse/fi/page/Y512959)

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/rahastoiva%20el%C3%A4kej%C3%A4rjestelm%C3%A4

**Comment by mariaforsen** [comment]
Sv. fonderade pensionssystem HT fonderande pensionssystem
https://www.pensionsmyndigheten.se/forsta-din-pension/om-pensionssystemet/pensionsordlista#42
https://www.rikstermbanken.se/search?q=fonderat+system&s=termer

**Comment by mirmaid** [comment]
Tämä voisi olla siis _rahastoivat eläkejärjestelmät_, jolloin ei tarvita tarkennetta (KT rahastoivat järjestelmät (eläkejärjestelmät)).

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa rahastoivat eläkejärjestelmät.
