### ISSUE TITLE
Mutasen kappeli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12954]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Mutasen kappeli

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kuvailu

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552)

**Vaihtoehtoiset termit**

 Mutasen rukoushuone

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mutasen rukoushuone: Rakennushistoriallinen selvitys ja inventointi
ISBN 978-952-94-7296-3

**Ehdottajan organisaatio**

KK/MP
**Termiehdotus Fintossa:** [Mutasen kappeli](http://finto.fi/yse/fi/page/Y512954)

**Comment by jtuohini** [comment]
Tämä mieluummin Kantoon kuin YSO:on… (https://www.loc.gov/aba/publications/FreeSHM/H0405.pdf)

**Comment by mariaforsen** [comment]
Sv. Mutasen kappeli
