### ISSUE TITLE
säteilylähde

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12966]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

säteilylähde

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

xxxx

**Ehdottajan organisaatio**

Säteilyturvakeskus
**Termiehdotus Fintossa:** [säteilylähde](http://finto.fi/yse/fi/page/Y512966)

**Comment by mariaforsen** [comment]
Sv. strålkällor HT strålningskällor
https://www.rikstermbanken.se/search?q=str%C3%A5lk%C3%A4lla&s=termer
https://svenska.se/tre/?sok=str%C3%A5lk%C3%A4lla&pz=1

**Comment by mirmaid** [comment]
8 viitettä Melindassa.

https://www.tvo.fi/tuotanto/perustietoaydinvoimasta/sateily/sateilylahteet.html
https://en.wikipedia.org/wiki/Radioactive_source

**Comment by ilona-x** [comment]
Tepa:
fi        säteilylähde
sv       strålkälla
en      radiation source

määritelmä
**säteilylaite tai radioaktiivinen aine**

huomautus
Avolähde on säteilylähde, jossa radioaktiivinen aine ei ole tiiviin vaipan suojaama. Umpilähde on säteilylähde, jossa radioaktiivinen aine on suljettu suojavaippaan siten, ettei aine voi levitä ympäristöön normaalissa käytössä.

definition
strålningsalstrande apparat eller radioaktivt ämne

anmärkning
En öppen källa är en strålkälla i vilken det radioaktiva ämnet inte skyddas av en tät mantel. En sluten källa är en strålkälla i vilken det radioaktiva ämnet är sluten i en skyddsmantel så att ämnet inte kan spridas i miljön i normal användning.

Lähde: Varautumisen ja väestönsuojelun sanasto (TSK 39, 2009) https://termipankki.fi/tepa/fi/haku/s%C3%A4teilyl%C3%A4hde
	  
automaattisesti kootut käsitesuhteet
Hierarkkiset alakäsitteet: säteilylaite ja radioaktiivinen aine

**Comment by ilona-x** [comment]
YSOssa on säteilylaitteet ja radioaktiiviset aineet

**Comment by LeKorsu** [comment]
Monikossa?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa säteilylähteet.
