### ISSUE TITLE
säteilytoiminta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12965]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

säteilytoiminta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

xxxx

**Ehdottajan organisaatio**

Säteilyturvakeskus
**Termiehdotus Fintossa:** [säteilytoiminta](http://finto.fi/yse/fi/page/Y512965)

**Comment by mariaforsen** [comment]
Sv. strålningsverksamhet HT strålverksamhet
https://finlex.fi/sv/laki/ajantasa/2018/20180859
https://stuk.fi/sv/stuk-overvakar-stralningsverksamhet

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by fantsby-m** [comment]
Ei aineistoja eikä perusteluja ehdotuksessa. Mutta termi löytyy laista hyvin määriteltynä.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
