### ISSUE TITLE
seutuhallinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12969]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seutuhallinto](http://www.yso.fi/onto/yso/p774)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selkeytetään termin merkitystä

**Perustelut ehdotukselle**

Englanniksi sama termi sekä aluehallinnolla että seutuhallinnolla. Ruotsiksi molemmilla vastineilla sama merkitys, tarvitaan siis joko termien muutoksia tai sulkutarkenteiden lisäyksiä, ainakin ruotsiksi. 
Ks. MOT-sanakirjat
Valterissa vain aluehallinto: https://valter.sanakirja.fi/all/all/aluehallinto

**Ehdottajan organisaatio**

ALLFO

**Comment by ilona-x** [comment]
Tällainen laki löytyi, kun googlailin seutuhallintoa:
Laki seutuvaltuustokokeilusta  https://finlex.fi/fi/laki/alkup/2004/20040062?search%5Btype%5D=pika&search%5Bpika%5D=365%2F1995

ja ko. laki on kumottu: https://vm.fi/-/seutuyhteistyokokeilusta-annettu-laki-kumotaan

**Comment by mariaforsen** [comment]
Yllä mainittussa laissa käytetään ruotsiksi regionsförvaltning, joka siis ei valitettavasti millään tavalla ole yksilöivä, merkitykseltään selkeä tai rajattu.

**Comment by mirmaid** [comment]
Kumpaankohan tätä kannattaisi ohjata jos yhdistetään, aluehallintoon vai paikallishallintoon?

**Comment by ilona-x** [comment]
HKLJ-luokituksessa seutuhallinto-hakemistosana ohjaa luokkaan 345 [Suomen kunnallishallinto. Kuntien yhteistoiminta](http://urn.fi/URN:NBN:fi:au:hklj:345), joten tämä puoltaisi ehkä ohjausta termiin paikallishallinto.

Voisiko termi mahdollisesti ohjata myös seutuyhteistyö-termiin, sillä siitä ainakin puhutaan näiden nykyisinkin toimivien seutuhallitusten kohdalla? 🤔  https://tampereenseutu.fi/seutuyhteistyo/seutuhallitus/

**Comment by YSO-kokous** [comment]
PÄÄTÖS
seutuhallinto KÄYTÄ seutuyhteistyö
seutuhallinto KÄYTÄ paikallishallinto
Poistetaan seutuhallinto-käsite sanastosta.
