### ISSUE TITLE
piilokuvakirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12964]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[piilokuvakirjat](http://urn.fi/URN:NBN:fi:au:slm:s414)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM-termi piilokuvakirjat: 
Ohjaustermiksi "etsi ja löydä -kirjat"

**Perustelut ehdotukselle**

Yleisesti käytössä

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ruotsinkielinen vastine (päätermi) voisikin olla titta-och-hitta-böcker, nykyinen termi taitaa olla virheellinen.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
