### ISSUE TITLE
piilokamera

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12960]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[piilokamera](http://www.yso.fi/onto/yso/p27402)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko sulkutarkenne hyvä? 

**Perustelut ehdotukselle**

Käsite viittaa tv-ohjelmiin. Termi on kuitenkin helpohkosti sekoitettavissa esim. turvakameroihin, valvontakameroihin, salakuvaukseen tms.
Ks. https://www.wikidata.org/wiki/Q1151191
https://www.seurantalaitteet.fi/valvontakamerat/vakoilukamerat
https://play.google.com/store/apps/details?id=hiddencamdetector.spycamerafinder&hl=fi
https://melinda.kansalliskirjasto.fi/byid/013927953

Ylellä piilokamerat-termiä [sic] onkin näköjään käytetty kuvailussa molemmissa merkityksissä.
https://www.google.com/search?q=piilokamerat+site%3Ayle.fi

Sivuhuomio 1: Ilmeisesti tätä ei ole kertaakaan käytetty kuvailussa Melindassa. 
Sivuhuomio 2: SOTOssa on turvakamerat KÄYTÄ valvontakamerat.

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by ilona-x** [comment]
Tulisiko tarkenteeksi termin yläkäsite eli piilokamera (televisio-ohjelmat)?

**Comment by mirmaid** [comment]
Voisi olla myös _piilokameraohjelmat_?

**Comment by mariaforsen** [comment]
Sv.  dolda kameran-program HT dolda kameran (program), dolda kameranprogram
/uppslagsverk/encyklopedi/lång/dolda-kameran

**Comment by YSO-kokous** [comment]
Muutetaan muotoon piilokameraohjelmat.
