### ISSUE TITLE
verkkotallennus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12961]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[verkkotallennus](http://www.yso.fi/onto/yso/p27494)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermeiksi pilvitallennus ja molnlagring.

**Perustelut ehdotukselle**

Linkitin käsitteen tähän, jossa nämä termit. 
https://www.wikidata.org/wiki/Q914359
Pilvitallennus näyttää olevan asiasana Ylellä:
https://yle.fi/aihe/a/20-10002779
Microsoft käyttää cloud storagen vastineena pilvitallennusta:
https://www.microsoft.com/fi-fi/microsoft-365/onedrive/online-cloud-storage

**Ehdottajan organisaatio**

Tuomas / Finto

**Comment by mirmaid** [comment]
Tämä vaatii ehkä tarkennusta. Veikkaan että alun perin on tarkoitettu tätä https://fi.wikipedia.org/wiki/Network-attached_storage. Käytetty kuitenkin pilvitallennuksesta.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Vaihdetaan päätermiksi pilvitallennus.

YSO-ylläpito tutkii sopisiko tämä ohjaustermi: verkkotallennus (pilvitallennus) KÄYTÄ pilvitallennus
