### ISSUE TITLE
umpilähde

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12967]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

umpilähde

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

xxxx

**Ehdottajan organisaatio**

Säteilyturvakeskus
**Termiehdotus Fintossa:** [umpilähde](http://finto.fi/yse/fi/page/Y512967)

**Comment by mariaforsen** [comment]
Sv. sluten källa, sluten strålkälla
https://termipankki.fi/tepa/fi/haku/umpil%C3%A4hde

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mirmaid** [comment]
https://archive.epa.gov/radiation/source-reduction-management/web/html/sources.html

**Comment by fantsby-m** [comment]
Ei perusteluja eikä esimerkkejä aineistoista johon tarvittaisiin? Tarvitaanko myös _avolähde_ - ja yläkäsite _säteilylähteet_?
Edit: viimeksi mainitusta olikin oma issue: https://github.com/Finto-ehdotus/YSE/issues/12966

**Comment by LeKorsu** [comment]
Jos otetaan, kannattaa varmaan ottaa koko hierarkia
säteilylähteet, ST avolähde, ST umpilähde

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon

umpilähteet
avolähteet (säteilylähteet)

**Comment by mariaforsen** [comment]
Sv. 
-slutna strålkällor HT slutna källor (strålkällor), slutna strålningskällor
-öppna strålkällor HT öppna källor (strålkällor)
https://termipankki.fi/tepa/fi/haku/umpil%C3%A4hde
https://www.rikstermbanken.se/search?q=%C3%B6ppen+str%C3%A5lk%C3%A4lla&s=termer
https://www.rikstermbanken.se/search?q=sluten+str%C3%A5lk%C3%A4lla&s=termer
