### ISSUE TITLE
narkomaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12962]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[narkomaanit](http://www.yso.fi/onto/yso/p4475)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

huumeiden käyttäjät, huumeita käyttävät ihmiset, huumeita käyttävät henkilöt

**Perustelut ehdotukselle**

Pitäisikö harkita termin muutosta vähemmän leimaavaksi? Ks. https://www.sininauhaliitto.fi/ajankohtaista/ei-narkomaani-vaan-huumeita-kayttava-ihminen-termit-haltuun/ 
https://www.ept-verkosto.fi/narkkari-sana-toiseuttaa-mutta-ehka-juuri-siksi-sita-kaytetaan/

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjan mukaan narkomaani on "huumeiden väärinkäyttäjä, huumeista riippuvainen henkilö" eli ei kuka tahansa huumeita käyttävä henkilö (https://www.kielitoimistonsanakirja.fi/narkomaani).

**Comment by mirmaid** [comment]
Sanastossa siis päihdeongelmaiset, ST alkoholistit, narkomaanit (jolla ohjausterminä huumeiden käyttäjät). Yksimahdollinen muoto olisi myös _huumeriippuvaiset_. _Huumeiden käyttäjät_ pääterminä soveltuisi myös viihdekäyttäjiin.

**Comment by ilona-x** [comment]
FinMeSH:
[huumeiden käyttäjät](http://www.yso.fi/onto/mesh/D055030)
KT 
    huumeidenkäyttäjät
    huumeongelmaiset
    huumeriippuvaiset
    narkomaanit

**Comment by FinMeSHienPaimentaja** [comment]
MeSHin mukaan:

Scope Note

People who take drugs for a non-therapeutic or non-medical effect. The drugs may be legal or illegal, but their use often results in adverse medical, legal, or social consequences for the users.

https://meshb.nlm.nih.gov/record/ui?ui=D055030

**Comment by annamarj** [comment]
Narkomaani-sanan leimaavuudesta ja muista aiheeseen liittyvistä termeistä esim.
https://www.sininauhaliitto.fi/ajankohtaista/ei-narkomaani-vaan-huumeita-kayttava-ihminen-termit-haltuun/

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Vaihdetaan käsitteelle uusi päätermi: huumeriippuvaiset

Lisäksi ohjaustermi:
narkomaanit KÄYTÄ huumeriippuvaiset

Lisäksi toiselle käsitteelle ohjaustermi
huumeiden käyttäjät KÄYTÄ huumeiden käyttö

Keskustelu: Huumeiden käyttäjät ohjasi vain narkomaaneihin. Ajateltiin, että termi voisi ohjata myös neutraalimpaan käsitteeseen.
