### ISSUE TITLE
tehostettu palveluasuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12972]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tehostettu palveluasuminen](http://www.yso.fi/onto/yso/p25128)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tehostettu palveluasuminen poistetaan 

**Perustelut ehdotukselle**

Termiä ei enää käytetä. Vanhuspalvelulaissakin puhutaan ympärivuorokautisesta palveluasumisesta.

**Ehdottajan organisaatio**

Itä-Suomen yliopisto

**Comment by jtuohini** [comment]
Eikö siis olisi parempi vaihtaa päätermiksi nykyinen ohjaustermi, jolloin kummallakin olisi aineisto haettavissa? (Eli ei poistoa, jolloin menetettäisiin mahdollisuus käyttää hauissa.)

**Comment by ilona-x** [comment]
Tepa: 

**(vanhentunut)**
fi        tehostettu palveluasuminen
sv       serviceboende med heldygnsomsorg (2)
määritelmä
sosiaalipalvelu, jossa palvelunantaja järjestää sosiaalihuollon asiakkaalle palveluasunnon ja sinne asiakkaan tarvitsemaa hoitoa ja huolenpitoa sekä asumiseen liittyviä palveluja asiakkaan ympärivuorokautiseen hoidon ja huolenpidon tarpeeseen

huomautus
Tehostettuun palveluasumiseen sisältyy asiakkaan tarvitsemat ateria-, vaatehuolto-, peseytymis- ja siivouspalvelut sekä osallisuutta ja sosiaalista kanssakäymistä edistävät palvelut.
Tehostettuun palveluasumiseen tarkoitetun asunnon voi omistaa joko valtio, kunta, yritys, järjestö, säätiö tai henkilö, mutta myös jotkut edellä mainituista omistajista yhdessä (ns. sekaomistus). Asiakas voi asua joko omistus- tai vuokra-asunnossa.
Kehitysvammaisille henkilöille annettavissa palveluissa tehostettua palveluasumista kutsutaan usein autetuksi asumiseksi.
**Tehostettu palveluasuminen on korvautunut sosiaalipalvelulla ympärivuorokautinen palveluasuminen.**

definition
socialservice där en tillhandahållare av tjänster för en klient inom socialvården ordnar en servicebostad och den vård och omsorg klienten behöver samt tjänster i anslutning till boendet för att möta klientens behov av vård och omsorg dygnet runt

anmärkning
I serviceboende med heldygnsomsorg (2) ingår måltids-, klädvårds-, bad- och städservice samt service som främjar delaktighet och socialt umgänge.
Bostäder avsedda för serviceboende med heldygnsomsorg (2) kan ägas av staten, en kommun, ett företag, en organisation, en stiftelse eller en person, men även samägas av några av de ovan nämnda (så kallat samägande). Klienten kan bo antingen i en ägar- eller hyresbostad.
När det handlar om personer med utvecklingsstörning kallas serviceboende med heldygnsomsorg (2) ofta för assisterat boende.
**Serviceboende med heldygnsomsorg (2) (tehostettu palveluasuminen på finska) har ersatts med socialservicen serviceboende med heldygnsomsorg (1) (ympärivuorokautinen palveluasuminen på finska).**

Lähde: Sosiaalialan tiedonhallinnan sanasto (THL, 11.06.2024) https://termipankki.fi/tepa/fi/haku/tehostettu%20palveluasuminen

**Comment by mariaforsen** [comment]
Eli termi ei ole muuttunut ruotsiksi. 
https://termipankki.fi/tepa/fi/haku/ymp%C3%A4rivuorokautinen%20palveluasuminen
