### ISSUE TITLE
kristillinen oikeisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12971]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kristillinen oikeisto

**Ehdotettu termi ruotsiksi**

kristen höger

**Ehdotettu termi englanniksi**

Christian right, religious right

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Kristillinen_oikeisto
"Kristillinen oikeisto on Yhdysvalloissa Ronald Reaganin aikana vahvistunut poliittinen suuntaus, joka yleensä tukee Yhdysvaltain republikaanista puoluetta. "

Uskonnollinen oikeisto olisi ehkä kuitenkin parempi, koska se kattaa muitakin vastaavia.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 uskonnollinen oikeisto

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://urn.fi/URN:ISBN: 978-951-51-9569-2
Governing God’s Way or Man’s Way?” :a philosophical analysis of theocratic impulses in the United States’ religious right /

**Ehdottajan organisaatio**

KK/HR
**Termiehdotus Fintossa:** [kristillinen oikeisto](http://finto.fi/yse/fi/page/Y512971)

**Comment by mirmaid** [comment]
Molempia muotoja parin viitteen verran Melindassa.

**Comment by mirmaid** [comment]
LCSH: Religious right http://id.loc.gov/authorities/subjects/sh2003003066

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa uskonnollinen oikeisto, ohjaustermiksi kristillinen oikeisto.

**Comment by mariaforsen** [comment]
Sv. religiös höger HT religiösa högern, kristen höger, kristna högern
