### ISSUE TITLE
tiedepääoma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12976]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tiedepääoma

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

science capital

**Tarkoitusta täsmentävä selite**

"Tiedepääoma on tieteeseen liittyvän ymmärryksen summa: mitä ihminen tieteestä tietää, mitä hän siitä ajattelee, keitä hän tieteen ammateissa tuntee ja miten hän kaiken tämän valossa toimii arjessaan. Tiedepääoman pohja rakentuu koulussa ja opinnoissa, mutta elinikäinen oppiminen kartuttaa sitä myös kunkin omissa sosiaalisissa verkostoissa." https://www.finsci.fi/

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [pääoma](http://www.yso.fi/onto/yso/p6249)

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [aineeton pääoma](http://www.yso.fi/onto/yso/p9327)

**Vastaava käsite muussa sanastossa**

 [wikipedia](http://Tiedepääoma https://fi.wikipedia.org/wiki/Tiedep%C3%A4%C3%A4oma)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/019076916

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [tiedepääoma](http://finto.fi/yse/fi/page/Y512976)

**Comment by mariaforsen** [comment]
Sv. vetenskapligt kapital HT vetenskapskapital
https://vetenskapallmanhet.se/2021/10/vetenskapen-jag-va-dagen-om-hur-vetenskap-paverkar-vara-val/
https://fssc.se/vetenskapligt-kapital-en-introduktion/
https://www.finsci.fi/sv
https://instituutit.fi/hallinta/wp-content/uploads/2021/02/SV_vetenskapligt-kapital_manifest2021.pdf

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
