### ISSUE TITLE
tietokirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12973]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tietokirjallisuus](http://www.yso.fi/onto/yso/p12202)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muodoto "tiedekirjallisuus" ja "tutkimuskirjallisuus"

**Perustelut ehdotukselle**

Tiedekirjallisuus ja tutkimuskirjallisuus ovat tietokirjallisuutta.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja lisäksi _tieteellinen kirjallisuus_, jota nimitystä myös käytetään (esim. https://www.uef.fi/fi/kirjasto/kirjojen-hakeminen ja https://hobbyhall.fi/fi/kirjat/lasten-ja-nuorten-kirjat/lasten-tietokirjat/f/all/tieteellinen-kirjallisuus [!])

**Comment by mirmaid** [comment]
Ehdotus käsitelty edellisen kerran v. 2021: https://github.com/Finto-ehdotus/YSE/issues/8809.

**Comment by mariaforsen** [comment]
Tiedekirjallisuus on kyllä myös oma lajinsa. 
https://arkisto.acatiimi.fi/3_2012/03_12_14t.php
https://www.suomentietokirjailijat.fi/media/lomakkeet_julkaisut_tietokirjallisuuden-lajit/tietokirjallisuus_lajit_svenska.pdf

**Comment by YSO-kokous** [comment]
PÄÄTÖS: Ei muutoksia.

Keskustelu: Käsitteet ovat hankalasti rajautuvia ja näiden päällekkäisyys ei ole erityisen selvä.
