### ISSUE TITLE
kuntoutussuunnitelma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12979]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kuntoutussuunnitelma

**Ehdotettu termi ruotsiksi**

rehabiliteringsplan

**Ehdotettu termi englanniksi**

rehabilitation plan

**Tarkoitusta täsmentävä selite**

Kuntoutuksen asiakkaan tarvitsemien palvelujen järjestämiseksi ja yhteensovittamiseksi laadittava suunnitelma. Laki Kansaneläkelaitoksen kuntoutusetuuksista ja kuntoutusrahaetuuksista edellyttää, että vaativa lääkinnällinen kuntoutus perustuu hyvän kuntoutuskäytännön mukaiseen kirjalliseen kuntoutussuunnitelmaan. 

**Perustelut ehdotukselle**

Kuntoutussuunnitelma on eri asia kuin kuntoutustutkimus. Kuntoutustutkimuksen tavoitteena on lääkinnällisen ja/tai ammatillisen kuntoutussuunnitelman laatiminen. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [suunnitelmat](http://www.yso.fi/onto/yso/p1751)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kuntoutus](http://www.yso.fi/onto/yso/p3320), [kuntoutustutkimus](http://www.yso.fi/onto/yso/p12945)

**Vastaava käsite muussa sanastossa**

 [Kelan terminologinen sanasto / Tepa](https://termipankki.fi/tepa/fi/haku/kuntoutussuunnitelma)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/search?query=kuntoutussuunnitelma&scope=707c2799-3e07-49f5-8a9a-196ec83a5230 

**Ehdottajan organisaatio**

Kela
**Termiehdotus Fintossa:** [kuntoutussuunnitelma](http://finto.fi/yse/fi/page/Y512979)

**Comment by mirmaid** [comment]
Melindassa sekä yksikössä että monikossa 4 kertaa.

**Comment by ilona-x** [comment]
TERO: kuntoutussuunnitelmat http://www.yso.fi/onto/tero/TNR1739

**Comment by LeKorsu** [comment]
Kaiketi monikossa?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
