### ISSUE TITLE
SPC

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12977]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[SPC](http://www.yso.fi/onto/yso/p2022)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Vaihdetaan päätermiksi tilastollinen prosessinohjaus tai otetaan ainakin ohjaustermiksi? https://fi.wikipedia.org/wiki/Tilastollinen_prosessinohjaus

**Perustelut ehdotukselle**

SPC-lyhenteellä on monia merkityksiä:
https://termipankki.fi/tepa/fi/haku/spc

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Kannatan vaihtoa.
