### ISSUE TITLE
skolträdgårdar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12980]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

koulupuutarhat

**Ehdotettu termi ruotsiksi**

skolträdgårdar

**Ehdotettu termi englanniksi**

school gardens

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Behövs vid beskrivning av material inom pedagogiken

**Ehdotettu yläkäsite YSOssa (LT)**

 [trädgårdar](http://www.yso.fi/onto/yso/p2225)

**Ehdotetut temaattiset ryhmät**

 [57 Uppfostran. Undervisning. Utbildning](http://www.yso.fi/onto/yso/p26554)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85118334), [SAO](https://id.kb.se/term/sao/Skoltr%C3%A4dg%C3%A5rdar), [Wikipedia](https://sv.wikipedia.org/wiki/Skoltr%C3%A4dg%C3%A5rd), [Wikipedia](https://fi.wikipedia.org/wiki/Koulupuutarha)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Dyrk framtida! : håndbok for å starte skolehage. 
Skolehagen som læringsarena

**Ehdottajan organisaatio**

ÅA
**Termiehdotus Fintossa:** [skolträdgårdar](http://finto.fi/yse/fi/page/Y512980)

**Comment by ilona-x** [comment]
KEKO: [koulupuutarha](https://finto.fi/keko/fi/page/p154)
MAO/TAO: [koulupuutarhat](https://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp8534)

**Comment by mirmaid** [comment]
15 kertaa Melindassa, 2 x koulupuutarhatoiminta.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
