### ISSUE TITLE
varpuset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12986]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[varpuset](http://www.yso.fi/onto/yso/p15224)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennettavaksi, lisätään alt Passeridae?

**Perustelut ehdotukselle**

Epäselvä
https://laji.fi/sv/taxon/MX.293056
https://luontoportti.com/t/717/varpuset-passeridae
https://artfakta.se/taxa/2002120/information

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
YSOn ylläpito tutkii.
