### ISSUE TITLE
deepfake

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12988]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

deepfake

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.aalto.fi/fi/tapahtumat/vaitos-taidekasvatuksen-alalta-ma-bogdan-chernyakevich

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [deepfake](http://finto.fi/yse/fi/page/Y512988)

**Comment by ilona-x** [comment]
Tepa:

fi        syväväärennös (★★★☆);
syvähuijausvideo (★★★☆);
valevideo (★★★☆);
deepfake (★★★☆);
huijausvideo (★★★☆)

sv       deepfake (★★★☆)

en      deepfake (★★★☆);
deepfake video (★★★☆)
	  
Lähde: IATE 01.08.2023, Euroopan unioni (3576653) https://termipankki.fi/tepa/fi/haku/deepfake

**Comment by ilona-x** [comment]
LCSH: Deepfakes http://id.loc.gov/authorities/subjects/sh2021003690

Wikipedia: https://fi.wikipedia.org/wiki/Deepfake

**Comment by satuniininen** [comment]
Myös Kielikellossa: https://kielikello.fi/deepfake-eli-syvavaarennos/

_Englannin deepfake-ilmauksesta käytetään jo melko yleisesti suomennosta syväväärennös, joka on siis käännöslaina. Käännöslainan etuna on, että sana on melko helppo oppia, jos lainanantajakielen termi on tuttu ja suomennosta käytetään toistuvasti oikeissa yhteyksissä. Vuonna 2024 syväväärennös-sanaa on esiintynyt muun muassa median artikkeleissa ja viranomaisten tiedotteissa._

**Comment by mariaforsen** [comment]
Sv. deepfakes HT deepfake, djupförfalskningar, djupfejk, deep fake 

https://it-ord.idg.se/ord/deepfake/
https://www.psykologiguiden.se/psykologilexikon/?Lookup=deepfake
/uppslagsverk/encyklopedi/lång/deepfake
https://spraktidningen.se/artiklar/ratt-klimat-nyord/
https://internetkunskap.se/artiklar/kallkritik/deepfakes-ar-har-nu-kan-datorn-forfalska-ditt-ansikte/
https://svenska.yle.fi/a/7-10014606
https://su.diva-portal.org/smash/record.jsf?pid=diva2%3A1683386&dswid=-8537
https://www.kyberturvallisuuskeskus.fi/sv/aktuellt/valet-tryggas-genom-myndighetssamarbete
-https://www.kyberturvallisuuskeskus.fi/sv/aktuellt/cybersakerhetscentrets-veckooversikt-032024

**Comment by mirmaid** [comment]
_Syväväärennökset_ sopii yhtä lailla, mutta varmaan hyvä ottaa jokin termi. Melindassa kerran myös hauskasti "deepfaket".

**Comment by YSO-kokous** [comment]
Hyväksytään. Päätermiksi syväväärennökset.
