### ISSUE TITLE
sotilaspuvut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12987]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sotilaspuvut](http://www.yso.fi/onto/yso/p14725)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Olisiko "sotilasvaatteet" ok ohjaustermi tälle suomeksi, vai viitataanko tällä ensisijaisesti univormuihin? 

**Perustelut ehdotukselle**

Ruotsiksi termi on ollut militärkläder, olisi todennäköisesti hyvä muuttaa > militära uniformer. 
LCSH military uniforms

**Ehdottajan organisaatio**

ALLFO

**Comment by JoonasParviainen** [comment]
MPKK:n kirjaston kommentti: puolustusvoimien aineistoissa "sotilasvaatteet" ei esiinny. Militärkläder ei ole myöskään käytössä ruotsiksi käännetyissä ohjesäännöissä. Pääasiassa käytössä olevat termit ovat "sotilaspuvut" ja "militäruniformer". 

https://puolustusvoimat.fi/sv/reglementen
https://puolustusvoimat.fi/asiointi/aineistot/ohjesaannot-ja-oppaat
https://puolustusvoimat.fi/sotilas-ja-virkapuvut

**Comment by fantsby-m** [comment]
"Sotilasvaatteet" näyttäisi esiintyvän siviileille myytävissä sotilashenkisissä tekstiileissä, tämän tyyppisiä sivustoja löytyy:
https://armeija-shop.fi/sotilasvaatteet/
https://armeija-suomi.fi/kokoelma/sotilasvaatteet-103/

**Comment by mariaforsen** [comment]
SAOssa muodossa "militära uniformer" https://id.kb.se/find?q=milit%C3%A4ra%20uniformer
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_de3d1e8724fc5cd5174b41c92bca5178&list_id=1&keyword=sotilaspuku&word=sotilaspuku
https://sv.wikipedia.org/wiki/Kategori:Milit%C3%A4ra_uniformer

**Comment by LeKorsu** [comment]
Sotilasvaatteet (armeija/puolustusvoimat) KÄ sotilaspuvut
sotilasvaatteet  (siviilit??) KÄ maastopuvut

**Comment by YSO-kokous** [comment]
Ei muutoksia suomeksi. Ruotsin kielen termi tarkistettaneen.

**Comment by mariaforsen** [comment]
Sv. militärkläder > militäruniformer HT militära uniformer, militärkläder
https://svenska.se/tre/?sok=milit%C3%A4runiform&pz=1
https://id.kb.se/find?q=milit%C3%A4ra%20uniformer
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_de3d1e8724fc5cd5174b41c92bca5178&list_id=1&keyword=sotilaspuku&word=sotilaspuku
https://sv.wikipedia.org/wiki/Kategori:Milit%C3%A4ra_uniformer
