### ISSUE TITLE
meriharakka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12984]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

meriharakka

**Ehdotettu termi ruotsiksi**

strandskata

**Ehdotettu termi englanniksi**

Eurasian oystercatcher

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melko yleinen lintulaji rannikolla

**Ehdotettu yläkäsite YSOssa (LT)**

 [meriharakat](http://www.yso.fi/onto/yso/p15241)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 Haematopus ostralegus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Meriharakka)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ks. Melinda

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [meriharakka](http://finto.fi/yse/fi/page/Y512984)

**Comment by tpalonen** [comment]
Jos otetaan niin tarvitaan sulkutarkenteet tälle ja yläkäsitteelleen. Eli _meriharakka (laji)_ ja _meriharakat (heimo)_.
