### ISSUE TITLE
informantit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12997]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[informantit](http://www.yso.fi/onto/yso/p22029)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Korjataan virheellinen linkitys

**Perustelut ehdotukselle**

Linkitetty wikidatan ilmiantajiin (aivan eri merkitys)

**Ehdottajan organisaatio**

**Comment by krinay** [comment]
Harmillista, ettei LCSH-linkitys onnistu, kun siellä on kaksi informantti-termiä (Linguistic informants ja Ethnographic informants).

**Comment by nikopartanen** [comment]
Voiko LCSH-linkkejä olla kaksi? Deprekoitu Wikidatassa ja linkki poistettu YSOsta.
