### ISSUE TITLE
orfilaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12992]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[orfilaisuus](http://www.yso.fi/onto/yso/p25753)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "orfiset mysteerit"

**Perustelut ehdotukselle**

Kirjallisuudessa käytetty nimitys.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Vastaava ohjaustermi on jo ollut ruotsiksi.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
orfiset mysteerit KÄYTÄ orfilaisuus
