### ISSUE TITLE
funktioner (aktiviteter)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12998]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[funktioner (aktiviteter)](http://www.yso.fi/onto/yso/p21294)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Korjataan linkitys

**Perustelut ehdotukselle**

Wikipediassa tämä on suppeampi käsite

**Ehdottajan organisaatio**

**Comment by nikopartanen** [comment]
Deprekoitu Wikidatassa ja jo poistettu YSOsta. Voidaan sulkea.
