### ISSUE TITLE
Pride events

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12991]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pride events](http://www.yso.fi/onto/yso/p40235)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

nykyisen käsitteen jako kolmeen erilliseen käsitteeseen: 1) pride-tapahtuma, 2) pride-kulkue ja 3) pride-festivaali.

**Perustelut ehdotukselle**

Sekä kulkue että festivaali ovat tapahtumia, mutta nämä kolme eivät ole toistensa synonyymejä. Esim. Helsinki Pride on tapahtuma eli pride-festivaali, johon kuuluu yksittäisinä tapahtumina pride-kulkue, pride-piknik, sateenkaarimessut jne.

Wikidatassa nämä ovat olleet ihan sekaisin, mutta nyt ne on lopultakin jaettu kolmeen eri itemiin:

1) [pride-kulkue](https://www.wikidata.org/wiki/Q51404)
2) [pride-tapahtuma](https://www.wikidata.org/wiki/Q129596243)
3) [pride-festivaali](https://www.wikidata.org/wiki/Q129598636)

[Helsinki Pride 2022:n itemistä Wikidatassa](https://www.wikidata.org/wiki/Q112842218) voi nähdä ehkä paremmin miten tämä hierarkia menee.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mirmaid** [comment]
Palveleeko tämä parhaalla tavalla hakijaa? Jos on kiinnostunut kaikista pride-tapahtumista, mutta osa niistä on kuvailtu termillä pride-kulkueet ja osa termillä pride-festivaalit, joutuu varmuuden vuoksi tekemään kolme hakua. Jos taas haluaa hakea vain pride-kulkueita, voi nykytilanteessakin hakea pride-tapahtumat + kulkueet. Tarkka jaottelu puoltaa yleensä parhaiten paikkaansa silloin kun aineistojen määrä on suuri.

_Pride-tapahtumat_ on otettu sanastoon vajaa vuosi sitten, eikä sitä ole käytetty Melindassa vielä kertaakaan.

**Comment by YSO-kokous** [comment]
YSO-kokous ei nähnyt tarvetta muutoksille. Ks. ed. kommentti.
