### ISSUE TITLE
laika (koirat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12995]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laika (koirat)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Laika_(koiratyyppi)

**Perustelut ehdotukselle**

Tarve laika-koiria käsittelevän aineiston kuvailussa (neljään oli Melindassa laitettu vahingossa nykyinen "laika"-YSO-asiasana!)

**Ehdotettu yläkäsite YSOssa (LT)**

 [metsästyskoirat](http://www.yso.fi/onto/yso/p7934)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013756950, https://melinda.kansalliskirjasto.fi/byid/013108207, https://melinda.kansalliskirjasto.fi/byid/013310417 jne.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [laika (koirat)](http://finto.fi/yse/fi/page/Y512995)

**Comment by jtuohini** [comment]
Vai pitäisikö olla muodossa _**laikat**_? Ja tuleeko jokin suhde asiasanaan [**länsisiperianlaika**](http://www.yso.fi/onto/yso/p28410)?

**Comment by mirmaid** [comment]
Sanastossa myös _itäsiperianlaika_, puuttuu _venäläis-eurooppalainen laika_.

**Comment by mariaforsen** [comment]
Siinä tapauksessa pitäisi varmaan olla laikat (monikkosäännöt tässä sanastossa vs. Wikipedia), mutta mieluummin tarkkoja rotuja.

Sv. rysk-europeisk lajka
https://www.skk.se/hundraser/rysk-europeisk-lajka/
uppslagsverk/encyklopedi/lång/rysk-europeisk-lajka

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon uutena käsitteenä venäläiseurooppalainen laika.

Otetaan ohjaustermit
laika (itäsiperianlaika) KÄYTÄ itäsiperianlaika
laika (länsisiperianlaika) KÄYTÄ länsisiperianlaika
laika (venäläiseurooppalainen laika) KÄYTÄ venäläiseurooppalainen laika
