### ISSUE TITLE
HIV-tartunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12993]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[HIV-tartunta](http://www.yso.fi/onto/yso/p12006)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi HIV-infektio

**Perustelut ehdotukselle**

https://finto.fi/mesh/fi/page/D015658

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
Hyväksytään. YSO-ylläpito tarkistaa vielä kumpi: yksikkö- vai monikkomuoto.
