### ISSUE TITLE
kannattajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#12999]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kannattajat](http://www.yso.fi/onto/yso/p21319)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan linkitys

**Perustelut ehdotukselle**

Wikipediassa tämä rajautuu urheilumaailmaan

**Ehdottajan organisaatio**

**Comment by nikopartanen** [comment]
Poistettu YSOsta ja deprekoitu Wikidatassa, voidaan sulkea.
