### ISSUE TITLE
kansainvälinen markkinointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#130]
#### Ehdotettu termi suomeksi

kansainvälinen markkinointi
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 06.07.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114005

**Termiehdotus Fintossa:** [kansainvälinen markkinointi](http://finto.fi/yse/fi/page/Y314005)

**Comment by mariaforsen** [comment]
Tarvitaan myös ruotsiksi (internationell marknadsföring). Käytetty yli sata kertaa Melindassa!

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
