### ISSUE TITLE
konstruktivismi (filosofia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13001]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[konstruktivismi (filosofia)](http://www.yso.fi/onto/yso/p39513)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT konstruktivismi (tieteenfilosofia)

**Perustelut ehdotukselle**

Löytyy paremmin?

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
PÄÄTÖS

konstruktivismi (tieteenfilosofia) KÄYTÄ konstruktivismi (filosofia)
