### ISSUE TITLE
tarhaketut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13006]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tarhaketut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa on nyt käytetty termiä kettu/rödräv (muutos tehty ruotsiksi) aineistoissa, joissa käsitellään yleisesti kaikkia tarhattuja kettuja, riippumatta onko kyseessä ketun eli punaketun, hopeaketun tai siniketun variantteja. Varsinkin ruotsiksi tämä näyttää väärältä. Olisiko hyvä olla erillisenä käsitteenä "tarhaketut", käytettäväksi turkistarhaus-aineistoissa? Näissä aineistoissa on harvemmin kyse vain nimenomaan ketuista/punaketuista, joten kuvailu on nyt osittain puutteellinen.
https://www.kielitoimistonsanakirja.fi/#/tarhakettu?searchMode=all 

**Ehdotettu yläkäsite YSOssa (LT)**

 [koiraeläimet](http://www.yso.fi/onto/yso/p2229)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529), [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melindan turkistarhausaineistot, esim. Hyvän toimintatavan opas ketun lopetukseen ; Suomi tehtailee ketunnahkoja : Suomessa tuotetaan joka vuosi lähes kaksi miljoonaa ketunnahkaa, eniten maailmassa ; Mitä WelFur-käynnit kertovat nälästä ja janosta kettu- ja minkkitiloilla jne.

**Ehdottajan organisaatio**

ALLFO
**Termiehdotus Fintossa:** [tarhaketut](http://finto.fi/yse/fi/page/Y513006)

**Comment by mirmaid** [comment]
Ilmeisesti hopeakettu on punaketun värimuoto, mutta sinikettu naalin. KT turkisketut?

**Comment by ilona-x** [comment]
YSOssa on termi [turkiseläimet](http://www.yso.fi/onto/yso/p2230), jolla on RT-suhde mm. termiin kettu. Eli jos ei haluta kuvailussa käytettävän kettu-termiä tarhatuista turkiseläimistä, niin pitäisikö myös noita RT-suhteita tarkastella uudelleen? Vaikka toki tässä on sitten metsästys vs. turkistarhaus. 🤔 Mutta tuli mieleen, että jos otetaan erikseen tarhaketut KT turkisketut niin sillä varmaan pitäisi olla myös joku kettu-alkuinen ohjaustermi?

**Comment by mirmaid** [comment]
Nyt vasta huomaan, että _hopeakettu_ ja _sinikettu_ ovat sanastossa myös erikseen. Tarvitaanko lisäksi turkisketut?

**Comment by fantsby-m** [comment]
Ratkaisuna voisi olla myös ottaa päätermiksi/omaksi termikseen monikollinen termi ketut, sv. rävar.

**Comment by mariaforsen** [comment]
Ja sen alla olisi toivon mukaan sitten edelleen myös kettu=rödräv? Ja jokin ohjaus niin ettei sitä käytetä turkisketuista (ellei oikeasti ole nimenomaan punakettu kyseessä)

Tarve jollekin "lisäketulle" näyttää miten vain olevan olemassa, kun nyt on käytetty (virheellisesti) kettu-termiä siihen (monessa aineistossa on varmaan epäselvää mistä tarhakettutyypistä tarkaalleen puhutaan, eli ei voida laittaa sinikettu-, hopeakettu- yms. termejä kuvailuun)

**Comment by mirmaid** [comment]
^^ Jos tehdään näin, tulisi ketut (suku), kettu (laji).

**Comment by mirmaid** [comment]
Tätä issueta yhä uudestaan lukiessa alkoi kettu-sana kuulostaa korvaani niin hassulta, että piti googlata:
https://www.kotus.fi/nyt/kysymyksia_ja_vastauksia/sanojen_alkuperasta/sanojen_alkuperasta_j-k/kettu_ja_repo

**Comment by LeKorsu** [comment]
Punakettu ohjaa jo kettuun, mutta olisiko tällaisesta ohjaustermistä mitään lisähyötyä ilman että lisätään tarhakettuja:
kettu (punakettu) KÄ kettu ?

**Comment by YSO-kokous** [comment]
Päätös:

Lisätään ketulle sulkutarkenne: kettu (punakettu)

Otetaan uutena käsitteenä ketut (suku).

**Comment by mariaforsen** [comment]
Sv. rävar (släkt) HT rävsläktet
https://artfakta.se/taxa/1001644/information
