### ISSUE TITLE
Keuruun kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13000]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Keuruun kirkko

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.keuruunseurakunta.fi/kirkot-ja-tilat/kirkot-ja-kappelit/keuruun-kirkko
https://fi.wikipedia.org/wiki/Keuruun_kirkko

**Ehdotettu yläkäsite YSOssa (LT)**

 [kirkkorakennukset](http://www.yso.fi/onto/yso/p25)

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551)

**Vaihtoehtoiset termit**

 Keuruun uusi kirkko

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [Keuruun vanha kirkko](http://www.yso.fi/onto/yso/p22155)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Artikkeliaineisto

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Keuruun kirkko](http://finto.fi/yse/fi/page/Y513000)

**Comment by mariaforsen** [comment]
Sv. Keuru kyrka HT Keuru nya kyrka /google maps, kyrkan dock inte särskilt ny (1800-tal).
