### ISSUE TITLE
ammatilliset tutkinnot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13005]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ammatilliset tutkinnot](http://www.yso.fi/onto/yso/p22253)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Hierarkiamuutoksia: uusia alakäsitteitä?

**Perustelut ehdotukselle**

Tämän ja ammattitutkinnot-termien välillä ei ole nyt suhdetta ollenkaan, ja tämän ainoa alakäsite on pelastajatutkinnot. 
"Ammatillisia tutkintoja ovat ammatillinen perustutkinto, ammattitutkinto ja erikoisammattitutkinto." Ks. https://termipankki.fi/tepa/fi/haku/ammatillinen%20tutkinto
YSOssa ei kuitenkaan ole termiä ammatillinen perustutkinto, eikö pitäisi olla, jos halutaan jatkossakin pitää ammattitutkinnot eri asiana kuin ammatilliset tutkinnot?

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Hierarkiaa tarkistettava YSOn ylläpidossa.

**Comment by mirmaid** [comment]
https://sakky.fi/fi/hakijalle/koulutusalat/termit-haltuun

**Comment by mariaforsen** [comment]
Sv. yrkesinriktade grundexamina 

https://www.oph.fi/sv/utbildning-och-examina/yrkesinriktade-grundexamina
https://termipankki.fi/tepa/fi/haku/ammatillinen%20perustutkinto
https://opintopolku.fi/konfo/fi/sivu/ammatillinen-koulutus

**Comment by YSO-kokous** [comment]
Otetaan tälle uusi käsite alakäsitteeksi:
ammatilliset perustutkinnot
