### ISSUE TITLE
Sörnäinen (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13007]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Sörnäinen (Helsinki)](http://www.yso.fi/onto/yso/p105607)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "Söörnäinen (Helsinki)"

**Perustelut ehdotukselle**

Vanhemmassa aineistossa käytetty muoto, ks. esim. https://digi.kansalliskirjasto.fi/search?query=s%C3%B6%C3%B6rn%C3%A4inen

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja tuliko Söörnäinen viittausmuodoksi? Kysyn, kun ei ilmene tästä ketjusta eikä Alephissa ainakaan vielä tällaista viittausta näy.
