### ISSUE TITLE
aromanttisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13003]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aromanttisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

aromantic

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tällä hetkellä aromanttisuus niputetaan aseksuaalisuuden alle, vaikka ne ovat aivan eri asioita

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Freestyle, Tess Derentjeva.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [aromanttisuus](http://finto.fi/yse/fi/page/Y513003)

**Comment by mariaforsen** [comment]
Sv. aromantik HT aromantiskhet, aromanticism
https://www.rfsl.se/hbtqi-fakta/begreppsordlista/
https://id.kb.se/find?q=aromantik

https://fi.wikipedia.org/wiki/Aromanttisuus

"..Aromanttisuus ja aseksuaalisuus eivät kulje aina käsikädessä: aromanttinen ihminen voi olla seksuaaliselta suuntautumiseltaan mitä vain. Jotkut ihmiset tunnistavat olevansa sekä aromanttisia että aseksuaaleja. Samaistuminen yhteen näistä termeistä ei kuitenkaan tarkoita, että samaistut toiseen."
/ https://seta.fi/sateenkaaritieto/seksuaalinen-suuntautuminen/aseksuaalisuus/

https://www.kirjastot.fi/kysy/onko-kirjavinkkeja-aromanttisuudesta?language_content_entity=fi

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by ilona-x** [comment]
Tätä on siis kaivattu kaunon kuvailuun, ehdotuksessa mainittu teos https://www.wsoy.fi/kirja/dess-terentjeva/freestyle/9789510486368

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
