### ISSUE TITLE
huumekoirat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13014]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[huumekoirat](http://www.yso.fi/onto/yso/p8583)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q38523 => Q112111120

**Perustelut ehdotukselle**

Vastaa paremmin tätä termiä. Merkitsin YSO-tunnisteen vanhentuneeksi kohteessa Q38523  ja lisäsin uuden kohteeseen Q112111120.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja oikein Wikidatassa, voidaan sulkea.
