### ISSUE TITLE
paikkatiedot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13019]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[paikkatiedot](http://www.yso.fi/onto/yso/p2152)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q350758 => Q5915793

**Perustelut ehdotukselle**

Vastaa paremmin kohdetta Q5915793. Merkitsin YSO-tunnisteen vanhentuneeksi entisessä kohteessa, ja lisäsin sen myös uuteen kohteeseen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Linkki lisätty YSOon ja kunnossa Wikidatassa. Voidaan sulkea.
