### ISSUE TITLE
piimä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13016]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[piimä](http://www.yso.fi/onto/yso/p8949)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohteen muutos Q106612 => Q253333

**Perustelut ehdotukselle**

Kohde Q253333 vastaa piimää. Merkitsin entisen esityksen vanhentuneeksi Wikidatassa, ja lisäsin YSO-tunnisteen uuteen kohteeseen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa, voidaan sulkea.
