### ISSUE TITLE
seokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13012]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seokset](http://www.yso.fi/onto/yso/p13887)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohteen muutos Q18678542 => Q169336

**Perustelut ehdotukselle**

Q18678542 on Klamydian EP-levy nimeltä "Seokset". Oikea kohde on Q169336 (seos).

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa, voidaan sulkea.
