### ISSUE TITLE
ravintoketjut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13010]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ravintoketjut](http://www.yso.fi/onto/yso/p12241)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q111396014 vanhentunut

**Perustelut ehdotukselle**

Merkitsin tämän YSO-termin linkityksen vanhentuneeksi Wikidata-kohteessa Q111396014 (ravintoekologia, trophic ecology), joka käsittelee ennemminkin ravintoketjuja tutkivaa ekologian haaraa kuin ravintoketjuja itsessään. Ainoan Wikidata-linkityksen tulisi olla siis kohde Q159462.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa. Voidaan sulkea.
