### ISSUE TITLE
väsymislujuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13013]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[väsymislujuus](http://www.yso.fi/onto/yso/p9083)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q507234 => Q1172868

**Perustelut ehdotukselle**

Q507234 on Wikidata-kohde väsymisille, ja YSO-termi 3089 (väsyminen (materiaalitekniikka)) viittaa jo siihen. Oikea Wikidata-kohde on Q1172868 (väsymislujuus). 

**Ehdottajan organisaatio**

Wikidata

**Comment by mariaforsen** [comment]
Wikidatan ruotsinkielinen termi (Haighdiagram) on valitettavasti huono.

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa. Ruotsin labelia Wikidatassa ei muutettu, voidaan korjata nähdäkseni.

**Comment by nikopartanen** [comment]
Voisi tarkistaa, onko edelliseen käsitteeseen jäänyt väärä ruotsin label ja poistaa tarvittaessa.

**Comment by mariaforsen** [comment]
Sv. Haighdiagram on kyllä väärä vastine, eli voinee poistaa Wikidatasta.
