### ISSUE TITLE
ydintekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13015]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ydintekniikka](http://www.yso.fi/onto/yso/p14463)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohteen vaihdos Q83504 => Q348091

**Perustelut ehdotukselle**

Vastaa paremmin ydintekniikan käsitettä. Merkitsin vanhan esityksen Wikidatassa vanhentuneeksi ja lisäsin YSO-tunnisteen uuteen kohteeseen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu molempiin, voidaan sulkea.
