### ISSUE TITLE
piparkakut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13018]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[piparkakut](http://www.yso.fi/onto/yso/p14853)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohteen muutos Q178600 => Q7879663

**Perustelut ehdotukselle**

Q7879663 vastaa paremmin piparkakkua. Merkitsin entisen kohteen YSO-tunnisteen vanhentuneeksi, ja lisäsin sen uuteen kohteeseen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu linkki YSOon, oikein Wikidatassa. Voidaan sulkea.
