### ISSUE TITLE
sähkötekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13017]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähkötekniikka](http://www.yso.fi/onto/yso/p1585)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q126095 => Q43035

**Perustelut ehdotukselle**

Vastaa paremmin sähkötekniikkaa. Merkitsin Wikidatassa YSO-tunnisteen entisessä kohteessa vanhentuneeksi, ja lisäsin YSO-tunnisteen uuteen kohteeseen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja oikein Wikidatassa.
