### ISSUE TITLE
amerikanpitbullterrieri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13011]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

amerikanpitbullterrieri

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Koirarotu
https://www.sathy.fi/

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 pitbullterrieri

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Amerikanpitbullterrieri)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Artikkeliaineisto

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [amerikanpitbullterrieri](http://finto.fi/yse/fi/page/Y513011)

**Comment by mariaforsen** [comment]
Sv. amerikansk pitbullterrier HT pitbullterrier, pitbull /NE
https://nn.wikipedia.org/wiki/Amerikansk_pitbullterrier
https://svenska.se/so/?id=161547
https://www.apbtfederationen.se/var-berattelse/
"Pitbull är ett samlingsnamn men används främst för amerikansk pitbullterrier. Rasen är inte godkänd i Sverige men i många andra länder. "
