### ISSUE TITLE
opiskelijaelämä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13024]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[opiskelijaelämä](http://www.yso.fi/onto/yso/p11456)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään WD linkki http://www.wikidata.org/entity/Q10682341

**Perustelut ehdotukselle**

Tunniste on wikidatassa, ei YSOssa.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by nikopartanen** [comment]
Lisätty YSOon, voidaan sulkea.
