### ISSUE TITLE
lupaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13023]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lupaukset](http://www.yso.fi/onto/yso/p22477)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan virheellinen linkki

**Perustelut ehdotukselle**

Virheellisesti linkitetty korttipeliin https://www.wikidata.org/wiki/Q973596

**Ehdottajan organisaatio**

**Comment by nikopartanen** [comment]
Poistettu YSOsta ja deprekoitu Wikidatassa, voidaan sulkea.
