### ISSUE TITLE
persimoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13021]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

persimoni

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://fi.wikipedia.org/wiki/Kaki

**Perustelut ehdotukselle**

Tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [hedelmäpuut](http://www.yso.fi/onto/yso/p11415), [hedelmät](http://www.yso.fi/onto/yso/p4647)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533), [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

 kaki, kakiluumu, sharon, saaron

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/013580635, https://melinda.kansalliskirjasto.fi/byid/013504636 ja muita

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [persimoni](http://finto.fi/yse/fi/page/Y513021)

**Comment by mariaforsen** [comment]
Sv. persimon HT kaki, sharon, kakiplommon
https://sv.wikipedia.org/wiki/Persimon
https://sv.wikipedia.org/wiki/Kaki
https://www.hebe.se/recept-sharonpersimon/
https://svenska.se/tre/?sok=kaki&pz=1
https://svenska.se/tre/?sok=persimon&pz=1
https://svenska.se/tre/?sok=sharon&pz=1

"Israelissa viljeltävä sharon on kakin jalostettu muoto, jossa ei ole parkkihappoa eikä siemeniä... Espanjassa viljeltävää lajiketta kutsutaan persimoniksi ja Uudessa-Seelannissa viljeltävää lajiketta kakiksi."
https://fi.wikipedia.org/wiki/Kaki

"Nimi riippuu kotimaasta
Persimon, kaki ja sharon kasvavat kaikki eri maissa, mutta ovat samaa lajiketta. Persimoneja viljellään Espanjassa ja sharoneja Israelissa. Kakit tulevat Suomeen Aasiasta, pääasiassa Japanista ja Kiinasta. "
https://www.valio.fi/keittion/persimon/

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Päätermistä äänestettiin (persimoni, kaki, sharon). Persimoni-muoto voitti äänestyksessä. Muut ohjaustermeiksi.
