### ISSUE TITLE
pitopalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13020]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pitopalvelut](http://www.yso.fi/onto/yso/p19003)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q377117 => Q777754

**Perustelut ehdotukselle**

Q777754 vastaa pitopalveluita. Merkitsin entisen kohteen YSO-tunnisteen vanhentuneeksi, ja lisäsin tunnisteen uuteen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Nyt oikein Wikidatassa ja YSOssa, voidaan sulkea.
