### ISSUE TITLE
seksuaalivähemmistöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13029]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[seksuaalivähemmistöt](http://www.yso.fi/onto/yso/p1828)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö lisätä queer ohjaustermiksi tähän ja sukupuolivähemmistöihin

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Queer

**Ehdottajan organisaatio**

KK/HR

**Comment by mariaforsen** [comment]
SAOssa tämä on erillinen termi: https://id.kb.se/find?q=queer Huomautuksella: "Hit verk som behandlar personer, kultur och livsstil som ifrågasätter dominerande idéer om hur människor ska leva i sexuella och andra relationer, hur man ska bilda familj, hur man ska uttrycka kön osv. Queer som identitet kan innebära en önskan att inte behöva definiera sitt kön eller sin sexuella läggning, medan en del använder queer som ett sätt att beskriva sin könsidentitet eller sin sexualitet."

**Comment by mirmaid** [comment]
Jos otettaisiin erikseen, tarvitsisi suomeksi ehkä jonkun lisäkkeen?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermit:

queer-ihmiset KÄYTÄ seksuaalivähemmistöt
queer-ihmiset KÄYTÄ sukupuolivähemmistöt
