### ISSUE TITLE
positiointiteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13022]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

positiointiteoria

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

positioning theory

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve sisällönkuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sosiaalipsykologia](http://www.yso.fi/onto/yso/p19035)

**Ehdotetut temaattiset ryhmät**

 [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Positioning_theory)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/019150847

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto
**Termiehdotus Fintossa:** [positiointiteoria](http://finto.fi/yse/fi/page/Y513022)

**Comment by mariaforsen** [comment]
Sv. positioneringsteori HT positionsteori 
https://www.psykologiguiden.se/psykologilexikon/?Lookup=positionera
https://lup.lub.lu.se/luur/download?func=downloadFile&recordOId=8910364&fileOId=8910365

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
