### ISSUE TITLE
värisokeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13034]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[värisokeus](http://www.yso.fi/onto/yso/p4645)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohteen Q432396 voi poistaa tästä käsitteestä

**Perustelut ehdotukselle**

Käsitteeseen on linkattu Wikidata-kohteet Q432396 (akromatopsia) ja Q133696 (värisokeus), joista vain jälkimmäinen vastaa tätä YSO-käsitettä. Akromatopsia on eräs värisokeuden alatyyppi.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa, voidaan sulkea.
