### ISSUE TITLE
indigo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13033]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[indigo](http://www.yso.fi/onto/yso/p18804)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q422662 => Q5967009

**Perustelut ehdotukselle**

Tämänhetkinen Wikidata-kohde käsittelee värjäysainetta, ei itse väriä. Merkitsin YSO-tunnisteen entisessä kohteessa vanhentuneeksi ja lisäsin sen uuteen kohteeseen.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa, voidaan sulkea.
