### ISSUE TITLE
šlávvavuohta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13038]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[šlávvavuohta](http://www.yso.fi/onto/yso/p11204)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pohjoissaamenkielisen ohjaustermiksi šlávavuohta

**Perustelut ehdotukselle**

Käytössä koulukirjoissa Norjan puolella ja Norjan hallituksen teksteissä yhdellä v:llä.

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Ehdotus hyväksytään.
