### ISSUE TITLE
fluoresenssimikroskopia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13037]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[fluoresenssimikroskopia](http://www.yso.fi/onto/yso/p27588)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata kohde Q840211 => Q73490850

**Perustelut ehdotukselle**

Nykyinen kohde kertoo mikroskoopista, eli mikroskopiasta. Muutin YSO-tunnisteen Wikidatassa ohjeiden mukaisesti

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Deprekoitu Wikidatassa eikä linkkiä ole YSOssa, voidaan sulkea.

**Comment by nikopartanen** [comment]
Linkki nyt myös YSOssa, Wikidata kunnossa.
