### ISSUE TITLE
vedeneristys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13035]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vedeneristys](http://www.yso.fi/onto/yso/p22013)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q811964 => Q2326110

**Perustelut ehdotukselle**

Q2326110 vastaa paremmin kyseistä käsitettä. Tein muutoksen Wikidatassa ohjeiden mukaisesti.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Sekä YSO että WIkidata kunnossa, voidaan sulkea.
