### ISSUE TITLE
sankarihaudat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13031]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sankarihaudat](http://www.yso.fi/onto/yso/p22967)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi sotilashaudat, sotilashautausmaat?

**Perustelut ehdotukselle**

Linkitetty militärkyrkogårdar, harkitaan ruotsiksi tämän lisäämistä ohjaustermiksi? Vai olisiko sotilashautausmaat erillinen termi?
https://www.kielitoimistonsanakirja.fi/#/sotilashautausmaa
Vrt. Suomen sankarihaudat ja sotilashautausmaat ulkomailla, esim. Saksan ja Ranskan. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Varmaan sitten myös sankarihautausmaat.

**Comment by fantsby-m** [comment]
Sotilashautausmaat voisi olla päätermikin? Ja sankarihautausmaat & sankarihaudat sitten ohjauksena.
https://www.kielitoimistonsanakirja.fi/sotilashautausmaa
Vrt. myös tuossa nyt oleva engl. päätermi.

**Comment by LeKorsu** [comment]
En näiltä näppäimiltä kannata sotilashautaismaiden ottamista päätermiksi, koska sankarihaudat on niin suomalainen käsite. Sodassa kaatuneet on tuotu oman kotipaikkakunnan hautausmaalle. Sen sijaan voin kannattaa sotilashautausmaiden ottamista omaksi termiksi, koska sellaisiakin on, myös Suomessa.  

https://www.visitrovaniemi.fi/fi/kayntikohde/saksalaisten-sotilaiden-hautausmaa/
https://fi.wikipedia.org/wiki/Saksalaisten_sotilaiden_hautausmaa_(Vantaa)

Minun ikäiseni ymmärtää eron, mutta jos otetaan sotilashautausmaat, pitäisikö sankarihaudoille lisätä jokin selite?

**Comment by ilona-x** [comment]
MAOssa molemmat:
sotilashaudat http://www.yso.fi/onto/mao/p8860
sankarihaudat http://www.yso.fi/onto/mao/p3748

**Comment by YSO-kokous** [comment]
PÄÄTÖS:

Sanastoon kaksi käsitettä.

sankarihautausmaat, sotilashaudat KÄYTÄ sankarihaudat
sankarihautausmaat KÄYTÄ sotilashautausmaat

Pohdittiin, että olisi vain yksi käsite, mutta todettiin, että sankarihaudoille on tarvetta suomalaisessa kontekstissa.

**Comment by mariaforsen** [comment]
Sv. krigskyrkogårdar HT militärkyrkogårdar, soldatkyrkogårdar 
uppslagsverk/encyklopedi/lång/krigskyrkogård
https://id.kb.se/term/sao/Krigskyrkog%C3%A5rdar
https://sv.wikipedia.org/wiki/Milit%C3%A4rkyrkog%C3%A5rd
uppslagsverk/encyklopedi/lång/krigskyrkogård
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_d0c162ba6a48920ff9034b89d1ce7730&list_id=1&keyword=sotilashautausmaa&word=sotilashautausmaa
