### ISSUE TITLE
nivelsairaudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13030]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nivelsairaudet](http://www.yso.fi/onto/yso/p22871)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

artropatiat

**Perustelut ehdotukselle**

synonymi, myös meshissä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
TEROssa on tämä ohjaustermi, ja MeSHissä ruotsiksi.
