### ISSUE TITLE
afrokuubalainen jazz

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13036]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[afrokuubalainen jazz](http://www.yso.fi/onto/yso/p30059)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-kohde Q837389 => Q3163340

**Perustelut ehdotukselle**

Q3163340 vastaa afrokuubalaista jazzia. Tein muutokset Wikidataan ohjeiden mukaisesti.

**Ehdottajan organisaatio**

Wikidata

**Comment by nikopartanen** [comment]
Korjattu YSOssa ja Wikidatassa, voidaan sulkea.
