### ISSUE TITLE
diagnostiset menetelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13049]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

diagnostiset menetelmät

**Ehdotettu termi ruotsiksi**

diagnostiska metoder

**Ehdotettu termi englanniksi**

diagnostic methods

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melindassa on aineistoa ja YSOssa on erilaisia diagnostisia menetelmiä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [menetelmät](http://www.yso.fi/onto/yso/p1913)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 diagnoosimenetelmät

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [diagnoosi](http://www.yso.fi/onto/yso/p14134)

**Vastaava käsite muussa sanastossa**

 [Mesh ](https://finto.fi/mesh/fi/page/D019937)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim.
Patologia / päätoimittaja: Markus Mäkinen ; toimittajat Johanna Arola [ja yhdeksän muuta]
Macleod’s clinical diagnosis / Alan G. Japp, Colin Robertson ; co-authors: Rohana J. Wright, Matthew J. Reed, Andrew Robson
Peruselintoimintojen häiriöt ja niiden hoito / toimittajat: Seppo Alahuhta, Tero Ala-Kokko, Kai Kiviluoma, Esko Ruokonen, Tom Silfvast ; kirjoittajat: Seppo Alahuhta [ja 50 muuta]
Kliinisen fysiologian perusteet / toimittajat: Anssi Sovijärvi ... [ja muita] ; [kirjoittajat: Aapo Ahonen ... ja muita]

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [diagnostiset menetelmät](http://finto.fi/yse/fi/page/Y513049)

**Comment by mirmaid** [comment]
Erikoisia menetelmiä MeSHissä, http://www.yso.fi/onto/mesh/D011291.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. diagnostiska metoder HT diagnosmetoder
https://id.kb.se/term/sao/Diagnostiska%20metoder
