### ISSUE TITLE
työorientaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13046]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[työorientaatio](http://www.yso.fi/onto/yso/p11379)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan?

**Perustelut ehdotukselle**

Voi ilmeisesti ainakin osalla kielistä tarkoittaa nykyisen määritelmän lisäksi ohjausta/perehdytystä. 

**Ehdottajan organisaatio**

YSO

**Comment by mirmaid** [comment]
Yläkäsite päätettävä tämän jälkeen, voisi olla esim. mentaaliset objektit. (tavoiteorientaatio YK orientoituminen)

Sulkutarkenteen keksiminen on kyllä todella vaikeaa...auttaisiko jos lisäisi ohjauksia toiseen suuntaan: työorientaatio (perehdytys) KÄ perehdytys?

**Comment by mariaforsen** [comment]
Eli olisi KÄ perehdyttäminen=introduktion? Varmaan tuo sv. introduktion pitäisi myös tarkentaa (lisää ongelmia).. Jos tuo perehdyttäminen on siis lähinnä työelämän (ryhmä 78). 
https://termipankki.fi/tepa/fi/haku/perehdytt%C3%A4minen
https://svenska.se/tre/?sok=introduktion&pz=1

Eli väärin suomeksi esim. tässä https://www.theseus.fi/bitstream/handle/10024/173161/Kurt%C3%A9n_Alexander.pdf?sequence=2&isAllowed=y

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi:
työorientaatio (perehdytys) KÄYTÄ perehdytys

**Comment by mariaforsen** [comment]
Tarkoittaa varmaan KÄYTÄ [perehdyttäminen](https://finto.fi/yso/fi/page/p303)

**Comment by mariaforsen** [comment]
Sv. arbetsorientering > förhållningssätt i arbetet HT attityd till arbetet

Se anmärkningen. Termen kan inte vara arbetsorientering utan parentes, eftersom det på svenska vanligen avser arbetsintroduktion. Nu sådana fel i Melinda, se t.ex.
https://www.theseus.fi/handle/10024/120996
https://www.theseus.fi/bitstream/handle/10024/173161/Kurt%C3%A9n_Alexander.pdf?sequence=2&isAllowed=y
https://oma.tsr.fi/api/projects/46ae7726-ed01-4575-9c7c-5c32b8697c86/attachment/0567da56-591b-4a6a-8ade-aa28c567af45

https://www.sanakirja.fi/custom/all/ty%C3%B6orientaatio
