### ISSUE TITLE
konvehdit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13041]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[konvehdit](http://www.yso.fi/onto/yso/p27537)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ruotsiksi ohjaustermi praliner?

**Perustelut ehdotukselle**

https://sv.wikipedia.org/wiki/Pralin

**Ehdottajan organisaatio**

kk/il

**Comment by jtuohini** [comment]
Ja myös suomeksi viittausmuodoksi _praliinit_ (https://www.kielitoimistonsanakirja.fi/praliini).

**Comment by mariaforsen** [comment]
Lisätty sv.

**Comment by mirmaid** [comment]
https://www.kirjastot.fi/kysy/mita-varsinaisesti-on-praliini?language_content_entity=fi

https://kotijakeittio.fi/artikkeli/praliini-6.165.126538.c49798b4cc

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
[praliini](https://www.kielitoimistonsanakirja.fi/#/praliini?searchMode=all)

1. likööri-, marsipaani- tm. täytteinen suklaamakeinen.
2. paahdetusta sokerista ja kokonaisista pähkinöistä t. manteleista tehty massa. 

--

Eli ehkä suomeksi tosiaan tarvitaan tarkenne, jos halutaan lisätä ohjaustermiksi eli voisiko olla praliinit (konvehdit) KÄYTÄ konvehdit?

Itselleni tämä tuli vastaan vain ruotsiksi Melindan kaakao-viitteitä korjatessa.

**Comment by mirmaid** [comment]
^ Jos se on tarpeen. Mun mielikuvissa praliini voi olla yksittäinen konvehti rasiassa, en siis itse osaisi mitään sellaiseksi nimetä, mutta tuohon on törmännyt niissä lehdyköissä missä kerrotaan mitä makuja rasiasta löytyy (nugaa, tryffeli, praliini).

**Comment by jtuohini** [comment]
Mielestäni on tarpeen: tunnen ihmisiä, jotka puhuvat nimenomaan praliineista, eivät konvehdeista. Miten tällaiset käyttäjät saavat asiasanahausta mitään irti, jos sanasto ei edes tunnista käyttämäänsä käsitettä?

**Comment by mariaforsen** [comment]
Praliinin määritelmä on erilainen ruotsiksi, ja termi käytetään usein nimenomaan konvehdin synonyyminä, sen takia tärkeä lisäys ruotsiksi.

**Comment by YSO-kokous** [comment]
PÄÄTÖS: praliinit (konvehdit) KÄYTÄ konvehdit
