### ISSUE TITLE
kognitiiviset prosessit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13045]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kognitiiviset prosessit](http://www.yso.fi/onto/yso/p5283)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään käsitteeseen kognitio

**Perustelut ehdotukselle**

Vaikea esim. hakutuloksia selaamalla nähdä, että jako kognitioon ja kognitiivisiin prosesseihin palvelisi kuvailua ja tiedonhakua. Psykologian sanakirjassa annettu määritelmä näyttäisi kehäpäätelmältä.

**Ehdottajan organisaatio**

YSO-päivityskokous

**Comment by mirmaid** [comment]
Psykologian sanasto
kognitio: tietäminen; se, miten yksilö vastaanottaa, säilöö, käyttää, välittää ja kehittää tietoa eli tiedonkäsittely. Yleinen termi kehittyneille kognitiivisille toiminnoille.

Kognitiiviset toiminnot (cognitive processes): tiedon vastaanottoon, käsittelyyn, säilyttämiseen ja käyttöön liittyvät psyykkiset toiminnot. Esim. havaitseminen, oppiminen, muistaminen, päättely, evaluointi, ajattelu.

**Comment by Rockyman-star** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/954

KT myös kognitiiviset toiminnot

**Comment by mariaforsen** [comment]
SAOssa on sekä kognition että kognitiva processer (mutta ei kognitiva funktioner=kognitiiviset toiminnot). Psykologilexikonissa kaikki erikseen:
https://www.psykologiguiden.se/psykologilexikon?Lookup=kognitiva%20funktioner
https://www.psykologiguiden.se/psykologilexikon/?Lookup=kognitiv+process
https://www.psykologiguiden.se/psykologilexikon/?Lookup=kognition
Sekä kognitio että kognitiiviset prosessit on käytetty tuhansia kertoja Melindassa...

**Comment by mirmaid** [comment]
^ Eri asia sitten, miten johdonmukaisesti.

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet:
kognitiiviset prosessit, kognitiiviset toiminnot KÄYTÄ kognitio
