### ISSUE TITLE
taiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13040]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taiat](http://www.yso.fi/onto/yso/p7776)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

-Parempi YK: uskomusjärjestelmiin liittyvät abstraktit objektit
-Uusi ohjaustermi: uskonnolliset abstraktit objektit KÄYTÄ uskomusjärjestelmiin liittyvät abstraktit objektit 

**Perustelut ehdotukselle**

Siinä muut vastaavat, esim. loitsut, kiroukset..  
Uusi ohjaustermi jotta tämä hierarkisoiva termi löytyy yhtä hyvin kuin muut "uskonnolliset..." -hierarkisoivat käsitteet

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Uskomusjärjestelmiin liittyvät abstraktit objektit on hierarkisoiva käsite, jota ei ole tarkoitettu käytettäväksi kuvailussa. Tällaisille ei ole YSOssa aiemmin ollut ohjaustermejä. Peruste lienee ollut, että tiedonhakija ei ole näistä kiinnostunut, koska näiden avulla ei löydy (tai ei ainakaan pitäisi löytyä) kuvailtua aineistoa ja siksi käyttäjää ei tarvitse ohjata tällaisen käsitteen äärelle.
