### ISSUE TITLE
ECR

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13044]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ECR](http://www.yso.fi/onto/yso/p21378)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö tämän päätermi vaihtaa/tarkentaa, kun lyhenteellä ECR on muitakin merkityksiä?

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/ecr

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Päätermiksi _kysyntälähtöinen hankintayhteistyö_?

**Comment by mariaforsen** [comment]
Eng. kuitenkin edelleen efficient consumer response?

Sv. efficient consumer response HT effektiv konsumentrespons, effektiv kundrespons, ECR (handel), EKR (handel)
https://www.ecr.se/
https://www.rikstermbanken.se/search?q=ecr&s=termer
https://sv.wikipedia.org/wiki/Efficient_Consumer_Response__
https://www.diva-portal.org/smash/record.jsf?faces-redirect=true&aq2=%5B%5B%5D%5D&af=%5B%5D&searchType=SIMPLE&sortOrder2=title_sort_asc&query=&language=sv&pid=diva2%3A1483954&aq=%5B%5B%5D%5D&sf=all&aqe=%5B%5D&sortOrder=author_sort_asc&onlyFullText=false&noOfRows=50&dswid=-4963
https://www.diva-portal.org/smash/record.jsf?faces-redirect=true&aq2=%5B%5B%5D%5D&af=%5B%5D&searchType=SIMPLE&sortOrder2=title_sort_asc&query=&language=sv&pid=diva2%3A192289&aq=%5B%5B%5D%5D&sf=all&aqe=%5B%5D&sortOrder=author_sort_asc&onlyFullText=false&noOfRows=50&dswid=9100
https://www.diva-portal.org/smash/get/diva2:15218/FULLTEXT01.pdf
http://flowinstitute.se/pdf/Logistiklexikon.pdf

**Comment by YSO-kokous** [comment]
Vaihdetaan päätermiksi kysyntälähtöinen hankintayhteistyö.
