### ISSUE TITLE
toimintamallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13043]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[toimintamallit](http://www.yso.fi/onto/yso/p3817)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-linkitys on kohteeseen, joka näyttää olevan suomeksi Tajua Mut! -toimintamalli ja ruotsin ja englannin termit ehkä lisätty YSO-linkityksen yhteydessä

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Tajua_Mut!_-toimintamalli
http://www.wikidata.org/entity/Q25450992

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Selkeästi virheellinen linkitys ja sv-lisäys Wikidatassa.

**Comment by nikopartanen** [comment]
Poistetaan WD-linkki YSOsta ja deprekoidaan tai poistetaan Wikidatassa.

**Comment by nikopartanen** [comment]
Deprekoitu Wikidatassa ja linkki poistettu YSOssa. Myös Wikidatan englannin ja ruotsin labelit poistettu selkeästi virheellisinä.
