### ISSUE TITLE
Syväri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13059]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Syväri](http://www.yso.fi/onto/yso/p112710)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tälle pitäisi varmaan lisätä jokin tarkenne, kun sanastossa on nyt myös järveä tarkoittava Syväri (Pohjois-Savo)?

**Perustelut ehdotukselle**

joki Venäjällä: https://fi.wikipedia.org/wiki/Syv%C3%A4ri
järvi Pohjois-Savossa: https://fi.wikipedia.org/wiki/Syv%C3%A4ri_(j%C3%A4rvi)

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Lisätään tarkenne (joki). Lisätään linjaus liittyen luonnonmaantieteellisten paikkojen tarkenteisiin.
