### ISSUE TITLE
psykiatriijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13053]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[psykiatriijat](http://www.yso.fi/onto/yso/p16458)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pohjoissaamen ohjaustermi: psykiáhter

**Perustelut ehdotukselle**

Mm. Kela käyttää [psykiáhter](https://www.kela.fi/documents/d/saame/brosyra-buohcan-ja-doaibmavattolasvuodadoarjagat-sme).

**Ehdottajan organisaatio**

WMFI-AG/Kimberli

**Comment by mariguttorm** [comment]
Ehdotus hyväksytään.
