### ISSUE TITLE
uruguaylaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13054]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

uruguaylaiset

**Ehdotettu termi ruotsiksi**

uruguayaner

**Ehdotettu termi englanniksi**

Uruguayans

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarve kuvailla kirjailijan kansallisuus

**Ehdotettu yläkäsite YSOssa (LT)**

 [eteläamerikkalaiset](http://www.yso.fi/onto/yso/p5188)

**Ehdotetut temaattiset ryhmät**

 [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

9781668049778

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [uruguaylaiset](http://finto.fi/yse/fi/page/Y513054)

**Comment by mariaforsen** [comment]
Sv. uruguayaner HT uruguayare
