### ISSUE TITLE
Säynätlahti (Kuhmoinen)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13060]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Säynätlahti (Kuhmoinen)](http://www.yso.fi/onto/yso/p150274)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onkohan tämän tarkoitus olla kylä eikä järven osa? Nyt yläkäsitteinä sekä Päijänne että Kuhmoinen

**Perustelut ehdotukselle**

Melindassa yksi viite:
Tehinselän rantakylissä : Ruolahden, Tehinniemen ja Säynätlahden seudun asutusta ja elämää https://melinda.kansalliskirjasto.fi/byid/003013409

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Ei muutosta.
