### ISSUE TITLE
Rein

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13075]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Rein](http://www.yso.fi/onto/yso/p192078)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pohdittavaksi, toimiiko YSO-paikkojen linjaus luonnonmaantieteellisten paikkojen yläkäsitteistä myös esimerkiksi isojen jokien ja vuoristojen kohdalla

**Perustelut ehdotukselle**

esimerkiksi Rein sijaitseee 7 valtion alueella

Vastaavia mm. 
Tonava http://www.yso.fi/onto/yso/p113317
Alpit http://www.yso.fi/onto/yso/p115088 huom. Alpeilla alakäsite Dolomiitit, joka sijaitsee Italiassa
Andit http://www.yso.fi/onto/yso/p107390
Kordillieerit http://www.yso.fi/onto/yso/p107391

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
16.12.2024
Tarkennettiin linjausta, että yläkäsite on maanosa, jos paikka ulottuu yli 10 valtion alueelle.
