### ISSUE TITLE
mikrofluidistiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1307]
#### Ehdotettu termi suomeksi

mikrofluidistiikka
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[07 Fysiikka](http://www.yso.fi/onto/ysa/ryhma_07)
#### Lähde

Lähde: HS 16.3.2004

**Luontipäivämäärä:** 21.12.2004

**Muokkauspäivämäärä:** 21.12.2004, 17.6.2013, 17.6.2013, 10.1.2014, 16.12.2008, 10.01.2014

**Voyager-id:** 135083

**Termiehdotus Fintossa:** [mikrofluidistiikka](http://finto.fi/yse/fi/page/Y335083)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Mikrofluidistiikka

LCSH: Microfluidics http://id.loc.gov/authorities/subjects/sh2005000678

FinMeSH: mikronesteoppi http://www.yso.fi/onto/mesh/D044085

**Comment by mirmaid** [comment]
10 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. mikrofluidik
