### ISSUE TITLE
Långörn

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13072]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Långörn](http://www.yso.fi/onto/yso/p119414)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Saisikohan tälle vanhalle tutulle mysteerisaarelle jonkin yläkäsitteen, varmaan ainakin Varsinais-Suomi olisi mahdollinen, kun kuntataso voi olla haastava. Toinen vastaava ilman yläkäsitettä oleva samasta kirjasta peräisin oleva saari Dömaskär

**Perustelut ehdotukselle**

Näillä ei siis ole paikkakoordinaatteja, ja sijaintia on yritetty selvittää ko. julkaisusta (https://melinda.kansalliskirjasto.fi/byid/000248426) huonolla menestyksellä 

**Ehdottajan organisaatio**

kk/il

**Comment by ilona-x** [comment]
Tässä vielä vanhaa selvitystyötä muistin virkistämisesksi 😄 

> Oli ihan pakko tutkia tätä vielä lisää...vahvin kandidaatti Dömaskäriksi on [Dömmaskär](https://tools.wmflabs.org/geohack/geohack.php?language=sv&pagename=D%C3%B6mmask%C3%A4r_(%C3%B6,_lat_59,99,_long_22,13)&params=59.99191_N_22.12838_E_type:isle_region:FI); saaren koko on suunnilleen kirjan kuvausta vastaava ja kirjan kartassa Dömaskärin viereen on merkitty Långörn, Google mapsissa tämän Dömmaskärin eteläpuolella on Långören. Molemmat kuitenkin etelämpänä kuin kirjan kartassa, johon merkityt saaret vastaavat todellisuudessa Östra ja Västra Dömmaskär -nimisiä saaria. Hassua myös että kirjan tekstin mukaan sijaitsee ulkosaaristossa 30 km mantereelta, mutta tosiasiassa on varsin lähellä Kemiönsaarta. Kirjan Långörn puolestaan tuskin on Dömmaskärin eteläpuolinen saari, koska kirjoittaja menee sinne taksiveneellä Jurmosta, ja Jurmon läheltä löytyykin todennäköisempi Långören. Toisaalta olisi hauska säilyttää auktoriteetit, koska ko. saarista tuskin on muuta matskua, mutta ihan täysin varma näistä ei voi olla, ja jos haluaisi yksilöidä tarkenteella sen pitäisi olla varmaan lähin kartassa mainittu merenselkä.

Ja tässä vielä se aineistossa ollut kartta 
![langorn](https://github.com/user-attachments/assets/a1825c4f-179b-40d5-8939-fe8ff9eb9018)

**Comment by mirmaid** [comment]
Poistin nämä nyt kun aiemmassa sprintissä oli niin päätetty ja siirsin 653-kenttään.
