### ISSUE TITLE
tullitariffit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13119]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tullitariffit](http://www.yso.fi/onto/yso/p11243)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistäminen käsitteen "tullit" (https://finto.fi/yso/fi/page/p660) kanssa

**Perustelut ehdotukselle**

Eikös tämä ole käytännössä ihan sama asia kuin tulli(maksut), jolla löytyy oma käsitteensä? 

**Ehdottajan organisaatio**

Wikidata

**Comment by ilona-x** [comment]
[Tullisanastossa](https://tulli.fi/tutustu-tulliin/aineistot/tullisanasto) näin:

**tullitariffi**

säännöstö, johon on koottu tavaroiden tullinimikkeet, niihin liittyvät tullimaksujen määräytymisperusteet, etuuskohtelut sekä tuonti- ja vientirajoitukset ja -kiellot

Huomautus: Koko EU:n tullialueella noudatetaan yhteistä tullitariffia. Lisäksi EU-mailla voi olla omia kansallisia vienti- ja tuontirajoituksia ja -kieltoja.

Ei-suositeltava: käyttötariffi

--

**tullimaksu, tulli**

veroluonteinen maksu, joka kannetaan tullitariffin perustella tullauspäätöksen mukaisesti tietyn tullialueen ulkopuolelta tuotavista tavaroista

Huomautus: Tullimaksu määräytyy tulliselvityksessä tullitariffin perusteella. Tullimaksun määrään vaikuttavat tavaran tullinimike, arvo, alkuperä, määrä ja käytetty tullimenettely. Tullimaksu saattaa sisältää korotuksia tai vähennyksiä, esimerkiksi etuuskohtelujen, tariffikiintiöiden tai tullisuspensioiden perusteella. Tullitariffin perusteella tavara voi olla myös tulliton.

**Comment by mariaforsen** [comment]
Eri asia myös ruotsiksi.

**Comment by YSO-kokous** [comment]
Kokous ei nähnyt tarvetta muutoksille.
