### ISSUE TITLE
Jamalin niemimaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13125]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Jamalin niemimaa

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

xxxx

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/31490

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Jamalin niemimaa](http://finto.fi/yse/fi/page/Y513125)

**Comment by mariaforsen** [comment]
Sv. Jamalhalvön /Nationalencyklopedin HT Jamal (halvö), Samojedhalvön
