### ISSUE TITLE
purjelentokoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13151]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[purjelentokoneet](http://www.yso.fi/onto/yso/p18514)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermiksi liitolentokoneet, liitokoneet

**Perustelut ehdotukselle**

Synonymi

**Ehdottajan organisaatio**

**Comment by LeKorsu** [comment]
Käykö ihan synonyymistä? Sotahistoriaa mietin ja esim. valokuvien asiasanoitusta. Liitokoneilla kuljetettiin kymmeniä sotilaita yhdessä koneessa mm. Normandian maihinnousun yhteydessä. Nykyiset purjelentokoneet ovat käsittääkseni pienkoneita, joihin mahtuu 1-2 henkeä.

**Comment by YSO-kokous** [comment]
YSO-kokous ei nähnyt tarvetta ohjaustermeille. Kokous näki tässä sekaantumisen mahdollisuuden.
