### ISSUE TITLE
rodut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13189]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rodut](http://www.yso.fi/onto/yso/p21376)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

käsitteen tarkentaminen: eläinrodut KT rodut

**Perustelut ehdotukselle**

Muu käyttö voi olla pejoratiivista, jos sitä vahingossa käytetään viittaamaan ihmisryhmiin. Myos rotusyrjintä-termiä voisi miettiä siltä kannalta, että sen voisi ohjata esim. termeihin etninen syrjintä/apartheid/rasismi?

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by ilona-x** [comment]
toinen ehdotus: eläinrodut KT rodut (poistetaan sanastosta) #13258

**Comment by mirmaid** [comment]
Jatketaan keskustelua toisessa issuessa, suljen tämän.
