### ISSUE TITLE
mesenaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13220]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mesenaatit](http://www.yso.fi/onto/yso/p8159)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään viittausmuoto "tukijat" ja ehkä myös "taiteentukijat", "taiteensuosijat"

**Perustelut ehdotukselle**

Ks. https://www.kielitoimistonsanakirja.fi/mesenaatti

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Jos tukijat lisätään ohjaustermiksi, pitäisi varmaan olla jokin tarkenne, kun esimerkiksi sponsorikin voi olla tukija, ja tukijat voisi olla mahdollinen ohjaustermi myös ainakin YSO-termeille rahoittajat ja kannattajat?  (Huom. sponsorit ei ole YSOssa)

**Comment by YSO-kokous** [comment]
Ehdotusta ei hyväksytty. Nähtiin, että taiteentukijat ohjausterminä voisi rajata käyttöä pelkästään taiteeseen. Mesenaatti-termi itsessään on selkeä ja tunnettu.
