### ISSUE TITLE
persimoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#13231]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[persimoni](http://www.yso.fi/onto/yso/p40447)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään suhde asiasanaan "hedelmät"

**Perustelut ehdotukselle**

Melindan persimonia käsittelevä aineisto keskittyy persimoniin syötävänä hedelmänä, ei kasvina.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätty.
