### ISSUE TITLE
esiintymiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1336]
#### Ehdotettu termi suomeksi

esiintymiset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)
[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)
[95 Teatteri. Tanssi](http://www.yso.fi/onto/ysa/ryhma_95)
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)
#### Lähde

Lähde: Rokatessa roiskuu. 3. (kertoo muusikoiden muistelmista, joissa kerrotaan etupäässä keikoista)

**Luontipäivämäärä:** 25.02.2005

**Muokkauspäivämäärä:** 25.2.2005, 28.2.2005, 16.12.2008

**Voyager-id:** 136384

**Termiehdotus Fintossa:** [esiintymiset](http://finto.fi/yse/fi/page/Y336384)

**Comment by MUUSA-kokous** [comment]
YSOsta löytyy esiintyminen, esiintymiskeikat, esitykset ja yleisötilaisuudet, jotka kattanevat tämän ehdotuksen käyttöalan.
Voisiko tämän sulkea ja poistaa YSAn ja YSOn käsite-ehdotuksista? http://www.yso.fi/onto/ysa/Y336384

**Comment by mirmaid** [comment]
Halutaanko tätä ohjaustermiksi mainituille (esim. esiintyminen, esiintymiskeikat)?

**Comment by YSO-kokous** [comment]
lisätään  esiiintyminen KT esiintymiset,  esiintymiskeikat KT esiintymiset
