### ISSUE TITLE
kuukautiskierto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1345]
#### Ehdotettu termi suomeksi

kuukautiskierto
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 28.02.2005

**Muokkauspäivämäärä:** 28.2.2005, 16.12.2008, 05.05.2010

**Voyager-id:** 136427

**Termiehdotus Fintossa:** [kuukautiskierto](http://finto.fi/yse/fi/page/Y336427)

**Comment by petrapel** [comment]
Ehdotan yso-sanastoon termiä kuukautiskierto (ruotsiksi menstruationscykel). Termi löytyy Mesh-sanastosta sekä LCSH-sanastosta (Menstrual cycle).

Tarvitaan kuvailussa, esim. In the FLO : a 28-day plan working with your monthly cycle to do more and stress less (9780008327071)

**Comment by mariaforsen** [comment]
Sv. menstruationscykel

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
