### ISSUE TITLE
rasva-aineenvaihdunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1359]
#### Ehdotettu termi suomeksi

rasva-aineenvaihdunta
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/ysa/ryhma_15)
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 28.02.2005

**Muokkauspäivämäärä:** 28.2.2005, 16.12.2008, 14.05.2009

**Voyager-id:** 136461

**Termiehdotus Fintossa:** [rasva-aineenvaihdunta](http://finto.fi/yse/fi/page/Y336461)

**Comment by ilona-x** [comment]
Tälle termille olisi ollut käyttöä väitöskirjan "Characterization of angptl3 deficiency and molecular mechanisms of angptl3 deficiency induced hypolipidemia" kuvailussa.

FinMeSH: http://www.yso.fi/onto/mesh/D050356
LCSH: Lipids--Metabolism http://id.loc.gov/authorities/subjects/sh85077297

Melinda x 27

**Comment by ilona-x** [comment]
Jälleen yksi väitöskirja, jonka kuvailussa olisi tälle termille käyttöä:
Heterogeneity of non-alcoholic fatty liver disease :genetic and nutritional modulation of hepatic lipid metabolism

**Comment by mariaforsen** [comment]
Sv. fettomsättning https://sv.wikipedia.org/wiki/Fettoms%C3%A4ttning
