### ISSUE TITLE
rollaattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1364]
#### Ehdotettu termi suomeksi

rollaattorit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/ysa/ryhma_73)

**Luontipäivämäärä:** 28.02.2005

**Muokkauspäivämäärä:** 28.2.2005, 16.12.2008

**Voyager-id:** 136483

**Termiehdotus Fintossa:** [rollaattorit](http://finto.fi/yse/fi/page/Y336483)

**Comment by mianikula** [comment]
Rollaattori on liikkumisen apuväline. Kirjastoissa on rollaattoreita asiakkaiden käyttöön, jotta "huonommin" liikkuvien on helpompi kulkea kirjastossa. Rollaattorit ovat siis yksi osa esteettömyyteen liittyviä laitteita/palveluja.

**Comment by satuniininen** [comment]
En. rollators, rolling walkers
LCSH:ssa broadMatch [Walkers (Orthopedic apparatus)](http://id.loc.gov/authorities/subjects/sh85144898.html)
