### ISSUE TITLE
vientiyritykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1404]
#### Ehdotettu termi suomeksi

vientiyritykset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 17.03.2005

**Muokkauspäivämäärä:** 17.3.2005, 16.12.2008

**Voyager-id:** 136863

**Termiehdotus Fintossa:** [vientiyritykset](http://finto.fi/yse/fi/page/Y336863)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
