### ISSUE TITLE
vihersillat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1405]
#### Ehdotettu termi suomeksi

vihersillat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
#### Lähde

Lähde: Väre, S. Eläinten kulkujärjestelyt tiealueen poikki
#### Käsitteen määritelmä

Puilla ja pensailla maisemoitu silta, jota pitkin eläimet pääsevät tien yli (Suomen kuvalehti 1/2006: Vuoden sanat)

**Luontipäivämäärä:** 17.03.2005

**Muokkauspäivämäärä:** 17.3.2005, 17.3.2005, 24.1.2006, 24.1.2006, 16.12.2008

**Voyager-id:** 136865

**Termiehdotus Fintossa:** [vihersillat](http://finto.fi/yse/fi/page/Y336865)

**Comment by satuniininen** [comment]
Tarvitaan taas: https://www.doria.fi/handle/10024/180960

**Comment by FinMeSHienPaimentaja** [comment]
"Vihersillat" "ekologisten käytävien" alalaji..? "Viherkäytävät" olemassa myös.

**Comment by mariaforsen** [comment]
Sv. viltbroar HT grönbroar, ekodukter, faunabroar, gröna broar

https://svenska.se/tre/?sok=ekodukt&pz=1
https://svenska.se/so/?id=192983&ref=kcnr918936
faunapassage är ett bredare begrepp (innefattar även t.ex. tunnlar)
se även avhandlingen "Gröna broar ekologiska, sociala och estetiska tillgångar"

Motissa myös ekologinen käytävä ja eläinten ylikulkusilta

**Comment by annamarj** [comment]
Myös liikenteen ryhmään 39?
