### ISSUE TITLE
voittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1407]
#### Ehdotettu termi suomeksi

voittaminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

Lähde: Andersson, C.: The winning helix

**Luontipäivämäärä:** 17.03.2005

**Muokkauspäivämäärä:** 17.3.2005, 31.1.2006, 16.12.2008, 28.01.2016

**Voyager-id:** 136869

**Termiehdotus Fintossa:** [voittaminen](http://finto.fi/yse/fi/page/Y336869)

**Comment by mirmaid** [comment]
Hyväksytty https://github.com/Finto-ehdotus/YSE/issues/5091
