### ISSUE TITLE
yhteentoimivuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1414]
#### Ehdotettu termi suomeksi

yhteentoimivuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

Lähde: Gustafsson, T. Yhteentoimivuus : informaation siirrettävyyttä ja yhdistettävyyttä...

**Luontipäivämäärä:** 17.03.2005

**Muokkauspäivämäärä:** 17.3.2005, 16.12.2008

**Voyager-id:** 136881

**Termiehdotus Fintossa:** [yhteentoimivuus](http://finto.fi/yse/fi/page/Y336881)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
