### ISSUE TITLE
marionetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1454]
#### Ehdotettu termi suomeksi

marionetit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[95 Teatteri. Tanssi](http://www.yso.fi/onto/ysa/ryhma_95)

**Luontipäivämäärä:** 24.05.2005

**Muokkauspäivämäärä:** 24.5.2005, 16.12.2008

**Voyager-id:** 138296

**Termiehdotus Fintossa:** [marionetit](http://finto.fi/yse/fi/page/Y338296)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
