### ISSUE TITLE
muotopuutarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1462]
#### Ehdotettu termi suomeksi

muotopuutarhat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/ysa/ryhma_22)

**Luontipäivämäärä:** 24.05.2005

**Muokkauspäivämäärä:** 24.5.2005, 16.12.2008

**Voyager-id:** 138312

**Termiehdotus Fintossa:** [muotopuutarhat](http://finto.fi/yse/fi/page/Y338312)

**Comment by jtuohini** [comment]
Tarvetta on termille edelleen, esim. https://helka.finna.fi/Record/helka.1573344! Termiksi **muotopuutarhat**, KT _barokkipuutarhat_, _muodolliset puutarhat_ ja _ranskalaiset puutarhat_, LT _**puutarhat**_, RT _**puistot**_ ja _**puutarhataide**_. Ja toiseksi sanaryhmäksi _**91 Arkkitehtuuri**_.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Muotopuutarha

2 viitettä Melindassa

**Comment by mariaforsen** [comment]
Sv. formträdgårdar
