### ISSUE TITLE
työmarkkina-asema

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1487]
#### Ehdotettu termi suomeksi

työmarkkina-asema
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/ysa/ryhma_78)

**Luontipäivämäärä:** 25.05.2005

**Muokkauspäivämäärä:** 25.5.2005, 14.6.2005, 6.8.2007, 31.1.2008, 16.12.2008

**Voyager-id:** 138352

**Termiehdotus Fintossa:** [työmarkkina-asema](http://finto.fi/yse/fi/page/Y338352)

**Comment by henriyli** [comment]
YSAan 27.5.2008: http://www.yso.fi/onto/ysa/Y159272
