### ISSUE TITLE
vesien tila

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1492]
#### Ehdotettu termi suomeksi

vesien tila
#### Ehdotetut ohjaustermit

vesistöjen tila
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[13 Hydrologia](http://www.yso.fi/onto/ysa/ryhma_13)
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)

**Luontipäivämäärä:** 25.05.2005

**Muokkauspäivämäärä:** 25.5.2005, 16.12.2008

**Voyager-id:** 138360

**Termiehdotus Fintossa:** [vesien tila](http://finto.fi/yse/fi/page/Y338360)

**Comment by HeidiRonkainen** [comment]
Minusta tämä olisi hyvä ottaa sanastoon. Tarvitsisin taas https://www.doria.fi/bitstream/handle/10024/120153/Raportteja_129_2015.pdf?sequence=2

**Comment by HeidiRonkainen** [comment]
Ja taas tarvitsisin. http://urn.fi/URN:ISBN:978-952-314-569-6

**Comment by mirmaid** [comment]
Yhteensä kolme kertaa Melindassa. YSAssa on _ympäristön tila_ ja _ekologinen tila_.

**Comment by mariaforsen** [comment]
Sv. vattendragens tillstånd ET sjöars och vattendrags status, sjöars och vattendrags tillstånd, vattendragens status

**Comment by PaiviLipsanen** [comment]
Ympäristöhallinto käyttää:
Vesien tilaa seurataan jatkuvasti ympäristöhallinnon seurannoilla ja vesistöjen velvoitetarkkailulla. Ympäristöhallinnon seurannat ja toiminnanharjoittajien kustantamat velvoitetarkkailut kattavat jokien, järvien ja merialueen tilan seurannan.
http://www.ymparisto.fi/fi-FI/Kartat_ja_tilastot/Vesien_tila

**Comment by PaiviLipsanen** [comment]
Yllä mainitun sivun alareunassa on aihealueina mainittu:
seuranta, vesien tila
"Vesien tila" - klikkaamalla löytyy 9 osumaa

**Comment by AuHo22** [comment]
Ekologinen tila -termiä on ainakin meillä käytetty lähes poikkeuksetta vesien tilaa kuvaamassa, vaikka periaatteessa on merkitykseltään laajempi. Mikä ero tällä on vesien tilaan?

**Comment by jarmosaarikko** [comment]
**Vesien tila** voisi olla "**ympäristön tila**" alakäsitteenä. Rajautuu siis vain vesistöihin.  Kyllä puhutaan paljon myös "**metsien tila**" -käsitteestä. Esim.  https://www.hs.fi/paakirjoitukset/art-2000002911418.html  ja http://www.metla.fi/tiedotteet/2011/2011-06-14-metsien-tila.htm "Suomen **metsien tila** on arvioitu". Tämän voisi lisätä samalla kertaa "ympäristön tila" -käsitteen alle.   Sopii tähän paremmin kuin ekologisen tilan alle.

**Comment by jarmosaarikko** [comment]
vesien tila -- **vattendragens tillstånd**   ?
http://www.ymparisto.fi/sv-FI/Paverka_vattendragen
Tai sitten "**vattnens status**"  kuten tällä sivulla olevassa kuvassa: http://www.ymparisto.fi/sv-FI/Paverka_vattendragen/Vattenvarden (edited)
