### ISSUE TITLE
erikoismuseot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1508]
#### Ehdotettu termi suomeksi

erikoismuseot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/ysa/ryhma_81)

**Luontipäivämäärä:** 22.09.2005

**Muokkauspäivämäärä:** 22.9.2005, 22.9.2005, 22.9.2005, 16.3.2006, 16.12.2008

**Voyager-id:** 141017

**Termiehdotus Fintossa:** [erikoismuseot](http://finto.fi/yse/fi/page/Y341017)

**Comment by tpusa** [comment]
Kannatan ehdotusta. Tarpeen julkaisussa 978-952-263-160-2 Valtakunnalliset erikoismuseot : selvitys erikoismuseojärjestelmän tilasta ja tulevaisuudesta. 
Erikoismuseoista: https://www.museovirasto.fi/fi/museoalan-kehittaminen/tietoa-suomen-museoista/valtakunnalliset-erikoismuseot

**Comment by mirmaid** [comment]
MAO-ontologiassa, käytetty paljon Melindassa (yleensä masa-terminä).

**Comment by mariaforsen** [comment]
Sv. specialmuseer https://www.museovirasto.fi/sv/utveckling-av-museibranschen/tietoa-suomen-museoista/valtakunnalliset-erikoismuseot
