### ISSUE TITLE
puretut rakennukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1547]
#### Ehdotettu termi suomeksi

puretut rakennukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/ysa/ryhma_37)

**Luontipäivämäärä:** 26.09.2005

**Muokkauspäivämäärä:** 26.9.2005, 16.12.2008

**Voyager-id:** 141104

**Termiehdotus Fintossa:** [puretut rakennukset](http://finto.fi/yse/fi/page/Y341104)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5239

**Comment by mirmaid** [comment]
MAO-ontologiassa, 2 kertaa Melindassa masa-terminä.

**Comment by mariaforsen** [comment]
Sv. rivna byggnader
