### ISSUE TITLE
radiolääkkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1549]
#### Ehdotettu termi suomeksi

radiolääkkeet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)
#### Lähde

Lähde: Mäkelä, O. Radiation synovectomy jne.
#### Käsitteen määritelmä

Tarkoittaa radioaktiivisesta molekyylistä kehitettyjä lääkkeitä

**Luontipäivämäärä:** 26.09.2005

**Muokkauspäivämäärä:** 26.9.2005, 16.12.2008, 20.06.2012

**Voyager-id:** 141106

**Termiehdotus Fintossa:** [radiolääkkeet](http://finto.fi/yse/fi/page/Y341106)

**Comment by mirmaid** [comment]
Tarvittu: https://www.utupub.fi/handle/10024/175536

**Comment by mirmaid** [comment]
Myös KT radiolääkeaineet

**Comment by ilona-x** [comment]
FinMeSH:
[radiolääkeaineet ](https://finto.fi/mesh/fi/page/D019275)
Ohjaustermit
    radioaktiivinen lääke
    radioaktiiviset lääkkeet
    radiofarmaseuttinen aine
    radiofarmaseuttiset aineet
    radiolääke
    radiolääkeaine
    radiolääkkeet

**Comment by mirmaid** [comment]
Lääketieteen termit:

radioaktiivinen lääke:  radiolääke | sairauksien tutkimukseen ja hoitoon käytettäviä radioaktiivisia lääkevalmisteita

LCSH: http://id.loc.gov/authorities/subjects/sh85110790

https://fi.wikipedia.org/wiki/Radiol%C3%A4%C3%A4ke

**Comment by mariaforsen** [comment]
Sv. radiofarmaka HT radioaktiva läkemedel, radioläkemedel
https://mesh.kib.ki.se/term/D019275/radiopharmaceuticals
https://www.karolinska.se/vard/funktion/funktion-medicinsk-diagnostik-karolinska/medicinsk-stralningsfysik-och-nuklearmedicin/karriarsidor-nuklearmedicin/radiofarmaci/
https://www.lakemedelsverket.se/sv/tillstand-godkannande-och-kontroll/kontroll/inspektion-av-beredning-av-radiofarmaka

**Comment by FinMeSHienPaimentaja** [comment]
"Lääke" viittaa minusta ennen kaikkea aineeseen, jota käytetään lääkehoido(i)ssa, mutta nämä radiofarmaseuttiset/aktiiviset  aineet ovat käytössä myös diagnostiikassa. Juu, FinMeSH-termit kaipaavat myös tarkastelua tämän osalta.

**Comment by YSO-kokous** [comment]
Otetaan käsite sanastoon muodossa radiolääkeaineet. Ohjaustermeiksi valittaneen muita muotoja.
