### ISSUE TITLE
eläketuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1585]
#### Ehdotettu termi suomeksi

eläketuki
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/ysa/ryhma_73)
#### Käsitteen määritelmä

Eläketuki koskee vuosina 1941-1947 syntyneitä, erityisen pitkään työttöminä olleita henkilöitä. Eläketuen saajien tulee olla ollut lähes yhtäjaksoisesti työttöminä 1.1.1992 lukien

**Luontipäivämäärä:** 07.12.2005

**Muokkauspäivämäärä:** 7.12.2005, 16.12.2008

**Voyager-id:** 142737

**Termiehdotus Fintossa:** [eläketuki](http://finto.fi/yse/fi/page/Y342737)

**Comment by pappila** [comment]
Määritelmä on aika vanha ja sisältää vuosilukuja ja muita muuttuvia määreitä. 
Ehdottaisin yleisempää määritelmää.
Esim. 
Kelan terminologinen sanasto, 5. laitos 
Määritelmä: pitkäaikaisesti työttömänä olleelle ja vaikeaan työmarkkinatilanteeseen joutuneelle ikääntyneelle henkilölle maksettava etuus
tai
Eläketukilaki 29.12.2016/1531
1 luku, 1 §
Lain tarkoitus
Lain tarkoituksena on toteuttaa kertaluonteinen järjestely, jossa eräiden pitkäaikaisesti työttöminä olleiden ja vaikeaan työmarkkinatilanteeseen joutuneiden henkilöiden toimeentulo turvataan eläketuella ennen vanhuuseläkkeen alkamista.

Julkaisuja joihin termiä voisi käyttää
https://helda.helsinki.fi/handle/10138/2260/discover?rpp=20&sort_by=score&order=DESC&query=el%C3%A4ketuki&context=%2Fhandle%2F10138%2F2260%2Fdiscover

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. pensionsstöd
https://termipankki.fi/tepa/fi/haku/el%C3%A4ketuki
