### ISSUE TITLE
kehityspolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1604]
#### Ehdotettu termi suomeksi

kehityspolitiikka
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 08.12.2005

**Muokkauspäivämäärä:** 8.12.2005, 10.1.2006, 11.7.2007, 16.12.2008, 31.05.2010

**Voyager-id:** 142785

**Termiehdotus Fintossa:** [kehityspolitiikka](http://finto.fi/yse/fi/page/Y342785)

**Comment by henriyli** [comment]
YSAan 31.10.1986: http://www.yso.fi/onto/ysa/Y96042
