### ISSUE TITLE
neulahuovutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1627]
#### Ehdotettu termi suomeksi

neulahuovutus
#### Ehdotetut ohjaustermit

kuivahuovutus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)
#### Lähde

Lähde: Mäkelä, T. Neulahuovutus

**Luontipäivämäärä:** 09.12.2005

**Muokkauspäivämäärä:** 9.12.2005, 16.12.2008, 05.10.2009

**Voyager-id:** 142842

**Termiehdotus Fintossa:** [neulahuovutus](http://finto.fi/yse/fi/page/Y342842)

**Comment by mirmaid** [comment]
9789188945266
Nåltovning : en handbok för nybörjare

**Comment by mirmaid** [comment]
18 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. nåltovning ET torrtovning?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon ehdotettuine ohjaustermeineen.
