### ISSUE TITLE
oikeudenhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1628]
#### Ehdotettu termi suomeksi

oikeudenhoito
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)
#### Lähde

Lähde: Artikkeli ”Oikeudenhoidon yhteistyö ja arvostus maassamme” (Defensor legis 2/2004)

**Luontipäivämäärä:** 09.12.2005

**Muokkauspäivämäärä:** 9.12.2005, 9.12.2005, 16.12.2008, 16.10.2012

**Voyager-id:** 142843

**Termiehdotus Fintossa:** [oikeudenhoito](http://finto.fi/yse/fi/page/Y342843)

**Comment by tpusa** [comment]
Kaivataan myös julkaisun "Suomen sisäisen turvallisuuden ja oikeudenhoidon tulevaisuus", http://urn.fi/URN:ISBN:978-952-259-463-1, kuvailussa.

**Comment by mariaforsen** [comment]
Sv. rättsvård
