### ISSUE TITLE
paahdeympäristö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1631]
#### Ehdotettu termi suomeksi

paahdeympäristö
#### Ehdotetut ohjaustermit

paahdealueet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/ysa/ryhma_11)
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)

**Luontipäivämäärä:** 09.12.2005

**Muokkauspäivämäärä:** 9.12.2005, 16.12.2008, 02.01.2012

**Voyager-id:** 142847

**Termiehdotus Fintossa:** [paahdeympäristö](http://finto.fi/yse/fi/page/Y342847)

**Comment by HeidiRonkainen** [comment]
Olisi tarvetta tälle termille: http://urn.fi/URN:ISBN:978-952-11-3674-0

**Comment by mirmaid** [comment]
Paahdealueella tai paahdeympäristöllä tarkoitetaan auringonpaisteelle altista, kuumaa ja kuivaa aluetta. 

AFOssa yksikössä - monikko tuntuisi tässä jotenkin luontevalta.

**Comment by mariaforsen** [comment]
Hankala monikielisyyden kannalta, ruotsiksi mahdollisesti luotuna terminä "solig, varm och torr miljö" tms.? Eli aurinkoisista, lämpimistä ja kuivista paikoista?

**Comment by mirmaid** [comment]
Voisiko olla solexponerade miljöer? http://www.metsa.fi/web/sv/ljusocheldlife

**Comment by AuHo22** [comment]
Englanniksi xerothermic habitats? http://hdl.handle.net/10138/38375
