### ISSUE TITLE
potilasvaatteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1635]
#### Ehdotettu termi suomeksi

potilasvaatteet
#### Ehdotetut ohjaustermit

sairaalavaatteet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/ysa/ryhma_26)
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)
#### Lähde

Lähde: Iltanen & Topo. Pyjamasta turvaliiviin

**Luontipäivämäärä:** 09.12.2005

**Muokkauspäivämäärä:** 9.12.2005, 9.12.2005, 16.12.2008

**Voyager-id:** 142856

**Termiehdotus Fintossa:** [potilasvaatteet](http://finto.fi/yse/fi/page/Y342856)

**Comment by annemikkanen** [comment]
Käsityön ja muotoilun sanastossa:
**potilasvaatteet**
LT sairaalatekstiilit
LT vaatteet
Varsinkin opinnäytetöinä tehdään potilasvaatteiden tuotekehitystä.

**Comment by mirmaid** [comment]
MAOssa (LT vaatteet ja roolivaatetus?), TAOssa ja TSR-ontologiassa (jossa erikseen myös _sairaalavaatteet_).

Ei Melindassa

**Comment by mirmaid** [comment]
Potilasvaatteiden ei puolestaan ole tarkoituskaan olla kauniita. Ne ovat löysiä ja roikkuvia, vaaleita ja kalpeita, ne ovat osa karua ja todellista sairaalamaailmaa. Päiväläinen painottaa, että niiden ei kuulukaan olla imartelevia. ”Sairaalavaatteet tuovat lisädraamaa ja traagisuutta potilaiden kohdalla ja kuvastavat sitä pahaa oloa, jota kuhunkin keissiin liittyy.” (artikkeli kertoo Syke-sarjasta, mutta pätee kyllä tosielämässäkin  :simple_smile:)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
patientkläder
ET sjukhuskläder
