### ISSUE TITLE
kolorismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1683]
#### Ehdotettu termi suomeksi

kolorismi
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/ysa/ryhma_90)
#### Lähde

Julkaisu: Joel Pettersson : en åländsk kolorist

**Luontipäivämäärä:** 23.02.2006

**Muokkauspäivämäärä:** 23.2.2006, 16.12.2008, 15.4.2011, 15.04.2011

**Voyager-id:** 144516

**Termiehdotus Fintossa:** [kolorismi](http://finto.fi/yse/fi/page/Y344516)

**Comment by mirmaid** [comment]
Termi on jo YSAssa.
