### ISSUE TITLE
lastenraamatut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1691]
#### Ehdotettu termi suomeksi

lastenraamatut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)

**Luontipäivämäärä:** 24.02.2006

**Muokkauspäivämäärä:** 24.2.2006, 16.12.2008

**Voyager-id:** 144535

**Termiehdotus Fintossa:** [lastenraamatut](http://finto.fi/yse/fi/page/Y344535)

**Comment by ilona-x** [comment]
Tälle olisi ollut tarve väitöskirjan '"Jumala pyörähti pari tanssiaskelta" :lastenraamatut funktionaalisen ekvivalenssin valossa' kuvailussa

**Comment by ilona-x** [comment]
LCSH: Children's Bibles http://id.loc.gov/authorities/subjects/sh2014001759

**Comment by mirmaid** [comment]
2 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. barnbiblar

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
