### ISSUE TITLE
koulutuspalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#171]
#### Ehdotettu termi suomeksi

koulutuspalvelut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 10.07.1998

**Muokkauspäivämäärä:** 9.7.2001, 2.8.2004, 16.12.2008

**Voyager-id:** 114073

**Termiehdotus Fintossa:** [koulutuspalvelut](http://finto.fi/yse/fi/page/Y314073)

**Comment by henriyli** [comment]
YSAan 15.2.2005: http://www.yso.fi/onto/ysa/Y136128
