### ISSUE TITLE
elintarvikejärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1752]
#### Ehdotettu termi suomeksi

elintarvikejärjestelmät
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/ysa/ryhma_24)
#### Lähde

Lähde: Ruokakysymys
#### Käsitteen määritelmä

Elintarvikejärjestelmän käsite (agri-food system tai food system) on yhteiskuntatieteellisessä elintarviketutkimuksessa tärkeä. Se kuvaa elintarvikkeiden tuottamiseen ja kuluttamiseen liittyvien toimintojen ja suhteiden kokonaisuutta. Sen osien vuorovaikutuksen seurauksena määrittyy mitä, kuinka paljon, millä menetelmillä ja kenelle ruokaa tuotetaan ja jaetaan. Laajemmin määriteltynä elintarvikejärjestelmään kuuluvat alkutuotanto, tiede ja maatalousteknologia, jatkojalostus, jakelu, kauppa sekä elintarvikkeiden kulutus. Myös näitä säätelevät maatalouden instituutiot sekä instituutioiden välinen sosiaalinen, taloudellinen ja teknologinen vuorovaikutus ovat osa elintarvikejärjestelmää. Elintarvikejärjestelmä muodostuu elintarvikeketjuista, jotka kuvaavat tietyn elintarvikkeen kulkeutumista elintarvikejärjestelmässä

**Luontipäivämäärä:** 04.10.2006

**Muokkauspäivämäärä:** 27.11.2008, 4.10.2006, 16.12.2008

**Voyager-id:** 148464

**Termiehdotus Fintossa:** [elintarvikejärjestelmät](http://finto.fi/yse/fi/page/Y348464)

**Comment by PaiviLipsanen** [comment]
AFOssa on ruokajärjestelmät, joka esiintyy seuraavan väitöskirjan tiivistelmässä
Perspectives on the sustainability promise of alternative food networks (2017)
https://helda.helsinki.fi/handle/10138/215614

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5846

**Comment by PaiviLipsanen** [comment]
Googlaamalla
elintarvikejärjestelmä 1000 osumaa
ruokajärjestelmä 11 000 osumaa
