### ISSUE TITLE
fotokatalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1757]
#### Ehdotettu termi suomeksi

fotokatalyysi
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[30 Kemianteollisuus. Keraaminen teollisuus. Lasiteollisuus. Muoviteollisuus. Kumiteollisuus](http://www.yso.fi/onto/ysa/ryhma_30)
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/ysa/ryhma_37)
#### Käsitteen määritelmä

Teknologia, jota käytetään epäpuhtauksien, esimerkiksi orgaanisten yhdisteiden (hajut, bakteerit, savu) hajottamiseen joko kaasumaisista tai nestemäisistä aineista (http://ar2004.ahlstrom.com/ar2004/?PageId=933&site=0)

**Luontipäivämäärä:** 04.10.2006

**Muokkauspäivämäärä:** 4.10.2006, 10.4.2008, 16.12.2008

**Voyager-id:** 148469

**Termiehdotus Fintossa:** [fotokatalyysi](http://finto.fi/yse/fi/page/Y348469)

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä väitöskirjan "Synthesis of TiO2 by various methods :structural characteristics, photocatalytic activity and usability of powders and coatings" kuvailussa

Käytetään myös muotoa valokatalyysi.

LCSH: Photocatalysis http://id.loc.gov/authorities/subjects/sh93001301

**Comment by mariaforsen** [comment]
Sv. fotokatalys
