### ISSUE TITLE
historialliset novellit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1761]
#### Ehdotettu termi suomeksi

historialliset novellit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 04.10.2006

**Muokkauspäivämäärä:** 4.10.2006, 4.10.2006, 16.12.2008

**Voyager-id:** 148475

**Termiehdotus Fintossa:** [historialliset novellit](http://finto.fi/yse/fi/page/Y348475)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/12273

**Comment by tpalonen** [comment]
Tässä pitäisi pohtia, mikä olisi historiallisten novellien suhde historialliset kertomukset -käsitteeseen ja tarvitaanko molempia ja jos ei, mikä valitaan käytettäväksi termiksi. Sanastossa myös historialliset romaanit.
