### ISSUE TITLE
hymiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1762]
#### Ehdotettu termi suomeksi

hymiöt
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)

**Luontipäivämäärä:** 04.10.2006

**Muokkauspäivämäärä:** 4.10.2006, 4.10.2006, 16.12.2008

**Voyager-id:** 148476

**Termiehdotus Fintossa:** [hymiöt](http://finto.fi/yse/fi/page/Y348476)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
