### ISSUE TITLE
investituurariita

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1764]
#### Ehdotettu termi suomeksi

investituurariita
#### Ehdotetut ohjaustermit

investituurakiista
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/ysa/ryhma_52)
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)
#### Lähde

Lähde: Wikipedia
#### Käsitteen määritelmä

Investituurariita oli merkittävin maallisen ja kirkollisen vallan yhteenotto keskiajalla. Se alkoi 1000-luvulla Pyhän saksalais-roomalaisen keisarikunnan ja paavin välisenä riitana siitä, kuka hallitsee oikeutta nimittää kirkon toimihenkilöt (investituura). Riita johti lopulta lähes 50 vuotta kestäneeseen sisällissotaan Saksassa ja Saksan keisarikunnan hajoamiseen, joka kesti 1800-luvulle asti

**Luontipäivämäärä:** 04.10.2006

**Muokkauspäivämäärä:** 4.10.2006, 16.12.2008

**Voyager-id:** 148480

**Termiehdotus Fintossa:** [investituurariita](http://finto.fi/yse/fi/page/Y348480)

**Comment by jtuohini** [comment]
Tarvitaan edelleen! Wikidata-siltaus: https://www.wikidata.org/wiki/Q154764

**Comment by mirmaid** [comment]
Melindassa 5/4 kertaa. 
https://fi.wikipedia.org/wiki/Investituurariita

**Comment by mariaforsen** [comment]
SAOssa: https://id.kb.se/term/sao/Investiturstriden%201075-1122

**Comment by AuHo22** [comment]
Investiturstreit (DNB) ->

Geografischer Bezug | Deutschland
Oberbegriffe | Konflikt, 1050-1122
Verwandter Begriff: Laieninvestitur, Kirchengeschichte
DDC-Notation | 274.04943.023
Systematik | 3.3b Kirchengeschichte: Mittelalter ; 16.5 Geschichte einzelner Länder und Völker

**Comment by mariaforsen** [comment]
Sv. investiturstriden
