### ISSUE TITLE
maataloustuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1791]
#### Ehdotettu termi suomeksi

maataloustuki
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/ysa/ryhma_22)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 05.10.2006

**Muokkauspäivämäärä:** 5.10.2006, 16.12.2008, 01.10.2009

**Voyager-id:** 148515

**Termiehdotus Fintossa:** [maataloustuki](http://finto.fi/yse/fi/page/Y348515)

**Comment by tarjaturunen** [comment]
Kannatan hyväksymistä YSO termiksi. Tarve käyttää sis.kuvailussa.

**Comment by LeKorsu** [comment]
Afossa monikossa maataloustuet http://www.yso.fi/onto/koko/p74339. Eli otetaan varmaan monikossa. Varsinkin kun on EU-tukea ja kansallista tukea.

**Comment by mirmaid** [comment]
Aineistoa paljon ennestään yhdistelmillä _maatalous & tukimuodot, maatalous & EU-tuet_ ym.

**Comment by mariaforsen** [comment]
Tarvittu myös ruotsiksi: jordbruksstöd (on SAOssakin)
ET lantbruksstöd

**Comment by ilona-x** [comment]
EKS: maatalouden tukeminen (sv. lantbruksstöd)

**Comment by YSA-kokous** [comment]
maataloustuet
