### ISSUE TITLE
amatöörimuusikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#18]
#### Ehdotettu termi suomeksi

amatöörimuusikot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)
#### Lähde

Lähde: Musiikin asiasanasto

**Luontipäivämäärä:** 22.06.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 113839

**Termiehdotus Fintossa:** [amatöörimuusikot](http://finto.fi/yse/fi/page/Y313839)

**Comment by MUUSA-kokous** [comment]
Tämä on ohjausterminä käsitteelle harrastajamuusikot http://www.yso.fi/onto/yso/p29785.
Voisiko tämän sulkea ja poistaa tarpeettomana YSAn ja YSOn käsite-ehdotuksista Fintosta? http://www.yso.fi/onto/ysa/Y313839
