### ISSUE TITLE
osakesijoittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1803]
#### Ehdotettu termi suomeksi

osakesijoittaminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 05.10.2006

**Muokkauspäivämäärä:** 5.10.2006, 16.12.2008

**Voyager-id:** 148530

**Termiehdotus Fintossa:** [osakesijoittaminen](http://finto.fi/yse/fi/page/Y348530)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6867
