### ISSUE TITLE
romanimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1837]
#### Ehdotettu termi suomeksi

romanimusiikki
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)
#### Käsitteen määritelmä

Kriistiina Näyhö SKS:stä lähetti Suomen romanimusiikki -kirjan toisen toimittajan (SKS:n tutkija Risto Blomster) viestin termeistä romani/mustalaismusiikki:  ”Käytin itse omassa työssäni seuraavia käsitteitä:  - mustalaismusiikki: Tällä viittaisin sekä romaneiden että myös ei-romaneiden  esittämään 1800-luvulta lähtien syntyneisiin musiikintyyleihin, jotka jollain  lailla yhdistetään romaneihin, syystä tai toisesta. Tähän kategoriaan menevät  siis esim. romanitangot ja -iskelmät, romanssit ym.  - romanimusiikki: Tällä tarkoitin romanivästön pääasiassa omassa keskuudessaan  esittämää musiikkia. Musiikin tyylipiirteet on tavallisesti omaksuttu  ymnpäröivistä musiikkikulttuureista.  - romanilaulut: Tämä on edellisen "alaluokka", Suomen romanien musiikki on nim.  ollut pitkälle 1960-luvulle saakka pääasiassa lauluja.  Uudessa kirjassamme käytimme lisäksi romanien perinnelaulut -käsitettä. Tämä  tuli oikeastaan Kai Åbergin teksteistä, sillä viitataan tuohon samaan  romanilaulut-asiaan, mutta koska Kai on perinnetieteen opiskelija ja hänen  juttunsa oli rakennettu siitä näkökulmasta, otimme myös sen yhteiseksi  käsitteeksi.

**Luontipäivämäärä:** 20.12.2006

**Muokkauspäivämäärä:** 20.12.2006, 16.12.2008

**Voyager-id:** 149805

**Termiehdotus Fintossa:** [romanimusiikki](http://finto.fi/yse/fi/page/Y349805)

**Comment by MUUSA-kokous** [comment]
Asia on käsitelty ja päätetty issuessa https://github.com/Finto-ehdotus/YSE/issues/6682. Tämän issuen voisi sulkea, jotta termi poistuu myös Finton käsite-ehdotuksista: https://finto.fi/yse/fi/page/Y349805.
