### ISSUE TITLE
hallintosäännöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1850]
#### Ehdotettu termi suomeksi

hallintosäännöt
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/ysa/ryhma_71)

**Luontipäivämäärä:** 12.03.2007

**Muokkauspäivämäärä:** 12.3.2007, 16.12.2008

**Voyager-id:** 151435

**Termiehdotus Fintossa:** [hallintosäännöt](http://finto.fi/yse/fi/page/Y351435)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tätä: https://www.kuntaliitto.fi/julkaisut/2021/2139-hyvinvointialueen-hallintosaantomalli

https://fi.wikipedia.org/wiki/Hallintos%C3%A4%C3%A4nt%C3%B6

**Comment by mariaforsen** [comment]
Sv. förvaltningsstadgor

**Comment by ilona-x** [comment]
fi      hallintosääntö
sv      förvaltningsstadga
en      administrative regulations pl

määritelmä
johtosääntö, jossa määrätään kunnan tai kuntayhtymän hallinto- ja päätöksentekomenettelystä

huomautus
Hallintosääntö on ainoa pakollinen johtosääntö. Hallintosääntöön voidaan koota kaikkia kunnan toimielimiä koskevat määräykset.

definition
instruktion som innehåller bestämmelser om kommunens eller samkommunens förvaltnings- och beslutsförfarande

anmärkning
Förvaltningsstadgan är den enda obligatoriska instruktionen. Den kan innehålla bestämmelser om alla organ i kommunen.

definition
rules of procedure that govern the administrative and decision-making procedures of a municipality or joint municipal authority

note
Administrative regulations are the only mandatory rules of procedure. Regulations concerning all of the municipality's decision-making bodies can be assembled in the administrative regulations.


Lähde: Kuntasanasto (2013), C019 https://termipankki.fi/tepa/fi/haku/hallintos%C3%A4%C3%A4nt%C3%B6

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
