### ISSUE TITLE
musiikkijournalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1892]
#### Ehdotettu termi suomeksi

musiikkijournalismi
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)
[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)
#### Lähde

Lähde: Pakko vatkaa : kirjoituksia popmusiikista

**Luontipäivämäärä:** 12.03.2007

**Muokkauspäivämäärä:** 12.3.2007, 16.12.2008, 11.11.2011, 11.11.2011, 11.11.2011

**Voyager-id:** 151518

**Termiehdotus Fintossa:** [musiikkijournalismi](http://finto.fi/yse/fi/page/Y351518)

**Comment by mariaforsen** [comment]
Sv. musikjournalistik ET musikjournalism

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin ottamista YSOon, mutta ei SLM:ään.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite.
