### ISSUE TITLE
sosiaalinen älykkyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1917]
#### Ehdotettu termi suomeksi

sosiaalinen älykkyys
#### Ehdotetut ohjaustermit

sosiaalinen äly
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)

**Luontipäivämäärä:** 12.03.2007

**Muokkauspäivämäärä:** 12.3.2007, 24.10.2007, 24.10.2007, 16.12.2008, 09.12.2010

**Voyager-id:** 151556

**Termiehdotus Fintossa:** [sosiaalinen älykkyys](http://finto.fi/yse/fi/page/Y351556)

**Comment by tarjaturunen** [comment]
Tarve käyttää sisällönkuvailussa, teos "Social intelligence and nonverbal communication"

**Comment by mirmaid** [comment]
13 viitettä Melindassa lähinnä artikkeliaineistossa. 
LCSH: Social intelligence, http://id.loc.gov/authorities/subjects/sh86007174: _Here are entered works on the ability to understand and adjust to social situations and relations. Works on the skills needed by an individual to achieve social acceptance are entered under [Social skills.]_ 

https://fi.wikipedia.org/wiki/Sosiaalinen_%C3%A4lykkyys 

Sanastossa on _sosiaaliset taidot_, ja ainakin itse koen nämä melko vaikeasti erotettavina (jos on hyvät sosiaaliset taidot, on varmaankin sosiaalisesti älykäs?). _Sosiaalinen älykkyys on taito, jota voi oppia. Sosiaaliseen älykkyyteen liittyy mm. aktiivinen toisten kuuntelu, empatia, myötätunto, ystävällisyys ja joustavuus._ https://www.koulunterveyskirjasto.fi/aihe/opettajalle-ja-opiskeluhuollolle/opettajan-opas-luonteenvahvuudet/ool00013

**Comment by mariaforsen** [comment]
Sv. social intelligens tai korvattuna ainakin.

**Comment by tpalonen** [comment]
En vastusta uutta käsitettä. Sanastossa on myös _sosioemotionaaliset taidot_.

On myös olemassa termi _sosiaalinen kompetenssi_, jonka voisi lisätä ohjaustermiksi, kävi niin tai näin. (vrt. YSOn _sosiaaliset taidot_ on ruotsiksi _social kompetens_)

**Comment by LeKorsu** [comment]
Minä en oikein lämpene tälle uudelle, kun on olemassa jo sosiaaliset taidot, sosioemotionaaliset taidot, tunneäly. Olen samaa mieltä Mirjan kanssa, vaikeasti eroteltavissa.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermit:
sosiaalinen älykkyys KÄYTÄ sosiaaliset taidot
sosiaalinen kompetenssi KÄYTÄ sosiaaliset taidot
