### ISSUE TITLE
teollisuuskylät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1924]
#### Ehdotettu termi suomeksi

teollisuuskylät
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/ysa/ryhma_62)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 12.03.2007

**Muokkauspäivämäärä:** 12.3.2007, 16.12.2008

**Voyager-id:** 151567

**Termiehdotus Fintossa:** [teollisuuskylät](http://finto.fi/yse/fi/page/Y351567)

**Comment by jtuohini** [comment]
Tarve tälle on edelleen olemassa, joten toivottavasti saadaan takaisin käsiteltäväksi.
LCSH-siltaus: [**Industrial districts**](http://id.loc.gov/authorities/subjects/sh85065857).
Wikidata-siltaus: https://www.wikidata.org/wiki/Q105093704

**Comment by jtuohini** [comment]
"A form of industrial organization characterized by a geographic concentration of SMEs and some large enterprises, differently but highly specialized in several phases of the process, actively involved in the production of a distinctive product or family of products through cooperative and competitive relations." [https://www.igi-global.com/dictionary/networks-industrial-clusters/14207]

**Comment by mirmaid** [comment]
7 viitettä Melindassa. 
Kielitoimiston sanakirja: _vars. kehitysalueelle valtion tm. tuella perustetusta teollisuusalueesta_.

**Comment by mirmaid** [comment]
Sanastossa vähän vastaavia teknologiakylät KÄ _teknologiakeskukset_ ja _yrityspuistot_.

**Comment by mariaforsen** [comment]
Sv. "industriby"

**Comment by YSO-kokous** [comment]
Ohjaustermiksi: teolllisuuskylät KÄ teollisuusalueet
