### ISSUE TITLE
vaha-animaatioelokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1931]
#### Ehdotettu termi suomeksi

vaha-animaatioelokuvat
#### Ehdotetut ohjaustermit

vaha-animaatiot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)

**Luontipäivämäärä:** 12.03.2007

**Muokkauspäivämäärä:** 12.3.2007, 16.12.2008, 27.08.2012

**Voyager-id:** 151577

**Termiehdotus Fintossa:** [vaha-animaatioelokuvat](http://finto.fi/yse/fi/page/Y351577)

**Comment by mirmaid** [comment]
Animaatioelokuvan alalajeja löytyy nyt Kauno-sanastosta enemmän kuin SLM:stä. Siellä on esimerkiksi vaha-animaatioelokuvat, tietokoneanimaatioelokuvat ja piirrosanimaatioelokuvat, joiden erityisesti toivoisin löytyvän myös SLM:stä. Koska erityisesti animaationa tehdään paljon myös televisiosarjoja, olisi hyvä, että vastaavia termejä löytyisi myös televisiosarjojen alakäsitteinä: esimerkiksi vaha-animaatiosarjat ja tietokoneanimaatiosarjat. 

Arvelen, että elokuvan genretermien olemassaolo (vain) Kaunossa liittyy jotenkin ontologioiden siirtymävaiheeseen… Miten vaivatta termien siirtäminen Kaunosta SLM:ään onnistuisi? Mielestäni Kaunon animaatioelokuvien alakäsitteet ovat kuvaavia ja käytettyjä termejä.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/3675

**Comment by mariaforsen** [comment]
Muistaakseni jo kerran päätettiin ettei nämä (ainakaan piirrosanimaatioelokuvat) hyväksytä sanastoon (siihen aikaan kun dokumentaatio oli sähköpostissa)? Googlestakaan ei kunnollisia tuloksia. Jos silti otetaan niin onko eng. tämä: https://en.wikipedia.org/wiki/Clay_animation Ruotsiksi varmaan siinä tapauksessa leranimerade filmer.

**Comment by mirmaid** [comment]
Hyväksytään muodossa vaha-animaatiot.

**Comment by jtuohini** [comment]
LCGFT-vastine [**Clay animation films**](http://id.loc.gov/authorities/genreForms/gf2011026140).

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Sv. leranimationer HT leranimerade filmer

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _vaha-animaatiot_.
