### ISSUE TITLE
latinalainen kirkkolaulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#195]
#### Ehdotettu termi suomeksi

latinalainen kirkkolaulu
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)
#### Lähde

Lähde: Musiikin asiasanasto

**Luontipäivämäärä:** 15.07.1998

**Muokkauspäivämäärä:** 9.7.2001, 14.3.2003, 16.12.2008

**Voyager-id:** 114109

**Termiehdotus Fintossa:** [latinalainen kirkkolaulu](http://finto.fi/yse/fi/page/Y314109)

**Comment by henriyli** [comment]
Otettu YSAan 17.1.2014: http://www.yso.fi/onto/ysa/Y196861
