### ISSUE TITLE
lehtikirjoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1978]
#### Ehdotettu termi suomeksi

lehtikirjoitukset
#### Ehdotetut ohjaustermit

lehtijutut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 07.06.2007

**Muokkauspäivämäärä:** 7.6.2007, 16.12.2008

**Voyager-id:** 152824

**Termiehdotus Fintossa:** [lehtikirjoitukset](http://finto.fi/yse/fi/page/Y352824)

**Comment by mirmaid** [comment]
Tämä tai jokin vastaava olisi tarpeen kokoelmissa, joissa on tietyn henkilön tuottamaa aineistoa, esim. puheita, mielipidekirjoituksia ja muita lehtikirjoituksia. Esim. _Jorma Kuosmanen: Huone huoneelta virkistyen_.

**Comment by mirmaid** [comment]
Jää termiehdotukseksi / SLM.
