### ISSUE TITLE
marginalisoituminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1985]
#### Ehdotettu termi suomeksi

marginalisoituminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 07.06.2007

**Muokkauspäivämäärä:** 7.6.2007, 25.2.2008, 16.12.2008, 11.6.2009, 30.05.2012

**Voyager-id:** 152833

**Termiehdotus Fintossa:** [marginalisoituminen](http://finto.fi/yse/fi/page/Y352833)

**Comment by mirmaid** [comment]
Myös tämä ohjaustermiksi _syrjäytymiselle_?

**Comment by YSO-kokous** [comment]
Hyväksytään  syrjäytyminen KT marginalisoituminen
