### ISSUE TITLE
merenpinnan nousu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1986]
#### Ehdotettu termi suomeksi

merenpinnan nousu
#### Ehdotetut ohjaustermit

merenpinnan kohoaminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/ysa/ryhma_11)

**Luontipäivämäärä:** 07.06.2007

**Muokkauspäivämäärä:** 7.6.2007, 16.12.2008

**Voyager-id:** 152834

**Termiehdotus Fintossa:** [merenpinnan nousu](http://finto.fi/yse/fi/page/Y352834)

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä väitöskirjan [Statehood, statelessness, and continuity in a climate-changed world : A worst-case scenario analysis](https://urn.fi/URN:ISBN:978-952-12-4328-8) kuvailussa

YSOssa on merenpinnan vaihtelut, mutta se ei oikein tunnu sopivalta tämän väitöskirjan kohdalla.

--

Melinda: x 3

FinMesh: merenpinnan nousu http://www.yso.fi/onto/mesh/D000080763 

https://fi.wikipedia.org/wiki/Merenpinnan_nousu

Merenpinnan nousu aiheena YLEllä: https://yle.fi/t/18-257900/fi

**Comment by mariaforsen** [comment]
Sv. havsnivåhöjning HT höjning av havsnivån, havsnivåns höjning
https://www.rikstermbanken.se/search?q=havsniv%C3%A5h%C3%B6jning&s=termer

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
