### ISSUE TITLE
metamateriaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1987]
#### Ehdotettu termi suomeksi

metamateriaalit
#### Ehdotetut ohjaustermit

meta-aineet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

Lähde: http://www.tekniikka.info/?page=selite&word=61134&criteria=1&keyword=&ID=06dd77f098242c95370f4a6bc9d1edeb
#### Käsitteen määritelmä

Metamateriaali on keinotekoisesti valmistettu sähkömagneettinen materiaali, jolla on ylivertaisia tai ainutlaatuisia sähkömagneettisia ominaisuuksia, joita ei ole löytynyt tai voi olla luonnossa esiintyvissä materiaaleissa tai yhdisteissä.   Tyypillinen esimerkki metamateriaalista, jolle ei ole löytynyt luonnon vastinetta, on negatiivisen taittokertoimen omaava vasenkätinen materiaali

**Luontipäivämäärä:** 07.06.2007

**Muokkauspäivämäärä:** 7.6.2007, 16.12.2008, 12.01.2010

**Voyager-id:** 152835

**Termiehdotus Fintossa:** [metamateriaalit](http://finto.fi/yse/fi/page/Y352835)

**Comment by henriyli** [comment]
YSAan 17.5.2016, http://www.yso.fi/onto/ysa/Y208595
