### ISSUE TITLE
opintosetelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#1991]
#### Ehdotettu termi suomeksi

opintosetelit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)
#### Lähde

Lähde: Aikuisten opintosetelin käyttöönottomahdollisuudet

**Luontipäivämäärä:** 07.06.2007

**Muokkauspäivämäärä:** 7.6.2007, 16.12.2008

**Voyager-id:** 152845

**Termiehdotus Fintossa:** [opintosetelit](http://finto.fi/yse/fi/page/Y352845)

**Comment by tpusa** [comment]
Kannatetaan. Tarpeen julkaisussa 978-952-263-188-6 Selvitys henkilökohtaisista koulutustileistä: ehdotukset ja vaikuttavuuden arviointi : loppuraportti

**Comment by mariaforsen** [comment]
sv. studiesedlar
