### ISSUE TITLE
ruumisarkut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2003]
#### Ehdotettu termi suomeksi

ruumisarkut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 08.06.2007

**Muokkauspäivämäärä:** 8.6.2007, 8.6.2007, 16.12.2008

**Voyager-id:** 152864

**Termiehdotus Fintossa:** [ruumisarkut](http://finto.fi/yse/fi/page/Y352864)

**Comment by jtuohini** [comment]
Tarvetta kyseiselle käsitteelle olisi, kun pitää kuitenkin kyetä tekemään mielekäs ero muihin, varsinkin kansanomaiseen kalustukseen kuuluviin arkkuihin (kapioarkut yms). Sarkofagi ei myöskään kuulu luontevasti ST-suhteisena suoraan asiasanan arkut alle, jos arkuilla tarkoitetaan myös kalusteita. Ks. esim. https://melinda.kansalliskirjasto.fi/byid/000598874, jossa on koko joukko alalukuja koskien erilaisia arkkuja (ei ruumis-sellaisia): "Ståndkistor", "Stockkistor", "Kistor av yngre typ med kupigt lock" jne.

**Comment by mariaforsen** [comment]
Sv. likkistor

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
