### ISSUE TITLE
suihkuvirtaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2009]
#### Ehdotettu termi suomeksi

suihkuvirtaukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[14 Klimatologia. Meteorologia. Ilmatiede](http://www.yso.fi/onto/ysa/ryhma_14)
#### Lähde

Lähde: Wikipedia
#### Käsitteen määritelmä

Lentäjien ja meteorologien slangissa jetti, on käärmemäinen voimakkaan tuulen alue hyvin korkealla troposfäärissä. Kovimman tuulen alue on putkimainen, mutta tuuli heikkenee laajalla alueella suihkuvirtauksen ympärillä. Suihkuvirtaus voi vauhdittaa tai hidastaa lentokonetta. Yläpilvet muuttuvat nauhamaiseksi suihkuvirtauksissa. Suihkuvirtaus kulkee matalapaineen säärintamien yllä. Suihkuvirtaus on siis karkeasti ottaen aina huonon sään alueella. Joillain alueilla suihkuvirtaus heikkenee vienommaksi tuuleksi.

**Luontipäivämäärä:** 08.06.2007

**Muokkauspäivämäärä:** 8.6.2007, 16.12.2008

**Voyager-id:** 152873

**Termiehdotus Fintossa:** [suihkuvirtaukset](http://finto.fi/yse/fi/page/Y352873)

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/305985

Tässä alatroposfäärin suihkuvirtaus. https://fi.wikipedia.org/wiki/Alatroposf%C3%A4%C3%A4rin_suihkuvirtaus

**Comment by mirmaid** [comment]
Melindassa 2 kertaa monikossa ja kerran yksikössä.
Alatroposfäärin suihkuvirtaus kerran yksikössä ja kerran monikossa.

**Comment by mariaforsen** [comment]
Sv. jetströmmar

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
