### ISSUE TITLE
tekstinlouhinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2018]
#### Ehdotettu termi suomeksi

tekstinlouhinta
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)
[81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/ysa/ryhma_81)
#### Lähde

Lähde: Toivonen, J. Text mining as a tool in real-life tasks
#### Käsitteen määritelmä

Googlella löytynyttä tietoa: ”Tekstinlouhinta on läheistä sukua tiedonlouhinnalle, mutta niiden välillä on yksi merkittävä ero: tiedonlouhinnalla voidaan käsitellä vain määrämuotoista dataa. Tämän  vuoksi ei-määrämuotoisen tekstidataan ei voida käyttää perinteisiä tiedonlouhintamenetelmiä, vaan on tullut tarvetta kehittää oma lähestymistapansa luonnollisen kielen automatisoituun käsittelyyn.”   - ja tällaista:  ”Tekstinlouhinnassa analysoidaan suuria tekstimassoja luonnollisen kielen käsittelyn, perinteisen tiedonhaun ja tiedonlouhinnan menetelmillä”

**Luontipäivämäärä:** 08.06.2007

**Muokkauspäivämäärä:** 21.3.2013, 8.6.2007, 8.6.2007, 8.6.2007, 3.10.2008, 16.12.2008, 10.3.2009, 5.2.2009, 21.03.2013

**Voyager-id:** 152883

**Termiehdotus Fintossa:** [tekstinlouhinta](http://finto.fi/yse/fi/page/Y352883)

**Comment by henriyli** [comment]
YSAan 12.6.2013 : http://www.yso.fi/onto/ysa/Y193215
