### ISSUE TITLE
tila-autot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2022]
#### Ehdotettu termi suomeksi

tila-autot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)
#### Lähde

Lähde: Kielitoimiston sanakirja
#### Käsitteen määritelmä

Pakettiautoa muistuttava tilava, tav. 7-8-paikkainen henkilöauto

**Luontipäivämäärä:** 08.06.2007

**Muokkauspäivämäärä:** 8.6.2007, 16.12.2008

**Voyager-id:** 152889

**Termiehdotus Fintossa:** [tila-autot](http://finto.fi/yse/fi/page/Y352889)

**Comment by henriyli** [comment]
Otettu YSAan 9.10.2008: http://www.yso.fi/onto/ysa/Y161601
