### ISSUE TITLE
kodin ja koulun yhteistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2057]
#### Ehdotettu termi suomeksi

kodin ja koulun yhteistyö
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 29.10.2007

**Muokkauspäivämäärä:** 29.10.2007, 16.12.2008

**Voyager-id:** 155235

**Termiehdotus Fintossa:** [kodin ja koulun yhteistyö](http://finto.fi/yse/fi/page/Y355235)

**Comment by vthuhtala** [comment]
Käytetty 51 kertaa Helkassa. YSAan, kiitos!

**Comment by ilona-x** [comment]
Melinda:  
kodin ja koulun yhteistyö x 228
kodin ja koulun välinen yhteistyö x  3
koti + koulut + yhteistyö  x 968

**Comment by mariaforsen** [comment]
Sv. samarbete mellan hem och skola ET hem-skola-samarbete, hem- och skola-samarbete, samarbete mellan skola och hem
