### ISSUE TITLE
kolmannen polven oikeudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2058]
#### Ehdotettu termi suomeksi

kolmannen polven oikeudet
#### Ehdotetut ohjaustermit

kansojen oikeudet, kollektiiviset oikeudet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)

**Luontipäivämäärä:** 29.10.2007

**Muokkauspäivämäärä:** 29.10.2007, 16.12.2008, 15.12.2010

**Voyager-id:** 155236

**Termiehdotus Fintossa:** [kolmannen polven oikeudet](http://finto.fi/yse/fi/page/Y355236)

**Comment by henriyli** [comment]
YSAan 6.3.2012: http://www.yso.fi/onto/ysa/Y184729
