### ISSUE TITLE
uraohjaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2105]
#### Ehdotettu termi suomeksi

uraohjaus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/ysa/ryhma_78)
#### Lähde
- julkaisu: Uraohjauksesta Ristiin Rastiin

**Luontipäivämäärä:** 30.10.2007

**Muokkauspäivämäärä:** 30.10.2007, 16.12.2008, 25.8.2009, 13.04.2012

**Voyager-id:** 155302

**Termiehdotus Fintossa:** [uraohjaus](http://finto.fi/yse/fi/page/Y355302)

**Comment by ilona-x** [comment]
Tälle termille olisi ollut käyttöä julkaisun "Tukea urapolulle" kuvailussa. 

Melinda x 4
TSR-ontologia: uraohjaus http://www.yso.fi/onto/tsr/p12069

Huom. YSOssa on ammatinvalinnanohjaus http://www.yso.fi/onto/yso/p19421

**Comment by mariaforsen** [comment]
Sv. karriärvägledning ET karriärhandledning

**Comment by YSO-kokous** [comment]
RT ammattinvalinnanohjaus
