### ISSUE TITLE
viikkolehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2109]
#### Ehdotettu termi suomeksi

viikkolehdet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 30.10.2007

**Muokkauspäivämäärä:** 30.10.2007, 16.12.2008

**Voyager-id:** 155307

**Termiehdotus Fintossa:** [viikkolehdet](http://finto.fi/yse/fi/page/Y355307)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
