### ISSUE TITLE
ilmastopakolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2141]
#### Ehdotettu termi suomeksi

ilmastopakolaiset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
[61 Väestötiede. Demografia](http://www.yso.fi/onto/ysa/ryhma_61)

**Luontipäivämäärä:** 04.02.2008

**Muokkauspäivämäärä:** 4.2.2008, 16.12.2008

**Voyager-id:** 156912

**Termiehdotus Fintossa:** [ilmastopakolaiset](http://finto.fi/yse/fi/page/Y356912)

**Comment by mirmaid** [comment]
Kerran Melindassa, Google n. 2300.
https://fi.wikipedia.org/wiki/Ilmastopakolaisuus

**Comment by satuniininen** [comment]
Tässä on paljon päällekkäisyyttä ympäristöpakolaisten kanssa. 
Vrt. Wikipedia: "Ilmastopakolainen on henkilö, joka pakenee kotipaikastaan muualle paikallisen ilmaston muuttumisen tai ympäristökatastrofin seurauksena."
