### ISSUE TITLE
ympäristöpakolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2142]
#### Ehdotettu termi suomeksi

ympäristöpakolaiset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
[61 Väestötiede. Demografia](http://www.yso.fi/onto/ysa/ryhma_61)

**Luontipäivämäärä:** 04.02.2008

**Muokkauspäivämäärä:** 4.2.2008, 16.12.2008, 09.11.2012

**Voyager-id:** 156913

**Termiehdotus Fintossa:** [ympäristöpakolaiset](http://finto.fi/yse/fi/page/Y356913)

**Comment by mariaforsen** [comment]
Toivottu nyt ruotsiksi "miljöflyktingar", kannatan lisäämistä. 

On myös MOTissa, Kielitoimiston sanakirjassa ja TEPAssa (mm. Ympäristösanasto /TSK, 1998): "elinkelvottomaksi muuttuneesta asuinympäristöstään (toiseen maahan) muuttavasta henkilöstä. "

Käytetty Melindassa, esim. "Ympäristöä paossa : käsiteanalyysi ympäristöpakolaisuuden konteksteista / Katri Mäenpää."

**Comment by satuniininen** [comment]
Kannatan!

LCSH:ssa [Environmental refugees](http://id.loc.gov/authorities/subjects/sh00006280.html)
