### ISSUE TITLE
konkreettinen runous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2149]
#### Ehdotettu termi suomeksi

konkreettinen runous
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)
#### Lähde
- julkaisu: Kirjallisuuden avantgarde ja kokeellisuus
#### Käsitteen määritelmä

Modernin lyriikan runous, jossa hyödynnetään optisia - visuaalisia ja typografisia - keinoja; konkretismi (Hosiaisluoma, Y. Kirjallisuuden sanakirja)

**Luontipäivämäärä:** 04.02.2008

**Muokkauspäivämäärä:** 4.2.2008, 16.12.2008

**Voyager-id:** 156923

**Termiehdotus Fintossa:** [konkreettinen runous](http://finto.fi/yse/fi/page/Y356923)

**Comment by mariaforsen** [comment]
Visuaalinen runous on näköjään hyväksytty, hyväksytäänkö myös konkreettinen runous?

**Comment by mirmaid** [comment]
SLM-sanastossa on _konkreettinen runous_, Kaunokissa molemmat. Melindassa kuitenkin vain 5 viitettä (samoin termillä _visuaalinen runous_).

"I define concrete poems as those in which only letters and/or words are utilized to form a visual image, whereas visual poems constitute those in which images are integrated into the text of the poem". (Sackner, https://en.wikipedia.org/wiki/Visual_poetry). 

Toisaalta Hosiaisluoma: Tekstin lisänä saattaa olla piirroksia, valokuvia tms., jolloin lukijan on usein hankala ratkaista, onko kyseessä pikemmin katsottavaksi tarkoitettu kuva kuin luettavaksi tarkoitettu teksti. (konkreettinen runous, http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:konkreettinen_runous)

**Comment by YSA-kokous** [comment]
Tuomas selvittää. Otetaan ainakin konkreettinen runous.
