### ISSUE TITLE
karjankutsut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2207]
#### Ehdotettu termi suomeksi

karjankutsut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/ysa/ryhma_50)

**Luontipäivämäärä:** 28.05.2008

**Muokkauspäivämäärä:** 28.5.2008, 16.12.2008

**Voyager-id:** 159339

**Termiehdotus Fintossa:** [karjankutsut](http://finto.fi/yse/fi/page/Y359339)

**Comment by henriyli** [comment]
YSAan 13.10.2008, http://www.yso.fi/onto/ysa/Y161686
