### ISSUE TITLE
lääketurvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2225]
#### Ehdotettu termi suomeksi

lääketurvallisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 28.05.2008

**Muokkauspäivämäärä:** 28.5.2008, 16.12.2008

**Voyager-id:** 159368

**Termiehdotus Fintossa:** [lääketurvallisuus](http://finto.fi/yse/fi/page/Y359368)

**Comment by PaiviLipsanen** [comment]
Tätä tarvitaan jatkuvasti esim. Dosis-lehden artikkelien kuvailuun.
https://dosis.fi/

**Comment by mirmaid** [comment]
Kolme kertaa Melindassa. FinMeSHissä on _lääketurvatoiminta_.

**Comment by mariaforsen** [comment]
Sv. läkemedelssäkerhet ET läkemedelstrygghet

**Comment by PaiviLipsanen** [comment]
http://www.kliinisenfarmasianseura.fi/kliininen-farmasia/laake-ja-laakitysturvallisuus/
Lääke- ja lääkitysturvallisuus
Iso osa potilaan turvallista ja asianmukaista hoitoa on lääkehoidon turvallisuus. **Turvallinen lääkehoito koostuu lääketurvallisuudesta ja lääkitysturvallisuudesta.**
Lääkkeen farmakologisten ominaisuuksien ja vaikutusten tunteminen on osa **lääketurvallisuutta**. Tämän lisäksi lääkkeen laadukas valmistusprosessi, lääkkeen pakkaaminen ja merkitseminen sekä lääkkeen tehon ja turvallisuuden arviointi kuuluvat lääketurvallisuuteen. Lääketurvallisuutta valvoo Lääkealan turvallisuus- ja kehittämiskeskus Fimea mm. myöntäessään myyntilupia ja valtakunnallisen haittavaikutusrekisterin kautta. Myös lääkkeen valmistajalla on vastuu valmisteidensa turvallisuuden seurannasta.
**Lääkkeiden asianmukainen ja oikea käyttö sekä lääkehoidon toteuttaminen liittyvät puolestaan lääkitysturvallisuuteen.** Lääkkeen käyttöön liittyvään turvallisuuteen kuuluvat terveydenhuollon toimintayksiköiden ja organisaatioiden toiminta, säännöt ja periaatteet. Lääkitysturvallisuutta voidaan kehittää esim. lääkkeiden käyttöön liittyvien haittatapahtuminen/poikkeamien seurannalla. Seuranta voi olla manuaalista tai seurannassa voi käyttää valtakunnallista haittatapahtumien seurantaan suunniteltua atk-työkalua, HaiPro:a. Seurannasta ei ole hyötyä ellei lääkityspoikkeamia pyritä estämään, välttämään tai korjaamaan uusilla toimintatavoilla tai ohjeistuksilla.
**Lääketurvallisuus on helppo erottaa lääkitysturvallisuudesta**. Lääketurvallisuus liittyy aina itse tuotteeseen tai lääkeaineeseen kun taas lääkitysturvallisuus liittyy lääkehoidon toteuttajien inhimilliseen toimintaan ja toimintayksikkökohtaisen prosessin virheettömyyteen.

**Comment by AuHo22** [comment]
Lääkitysturvallisuus on terminä tietenkin lähellä potilasturvallisuutta, mutta onko lääketurvallisuus sitten korvattavissa olemassaolevalla termillä lääkevalvonta, tai toisin päin?

**Comment by jarmosaarikko** [comment]
Jos molemmat Päivin ehdotukset otetaan, niin pitäisi lisätä lyhyet määritelmät, termit ovat niin lähellä toisiaan.

**Comment by YSA-kokous** [comment]
Otetaan molemmat.
