### ISSUE TITLE
uurnalehdot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2265]
#### Ehdotettu termi suomeksi

uurnalehdot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/ysa/ryhma_62)

**Luontipäivämäärä:** 28.05.2008

**Muokkauspäivämäärä:** 28.5.2008, 16.12.2008

**Voyager-id:** 159430

**Termiehdotus Fintossa:** [uurnalehdot](http://finto.fi/yse/fi/page/Y359430)

**Comment by henriyli** [comment]
Otettu YSAan 10.6.2011: http://www.yso.fi/onto/ysa/Y179881
