### ISSUE TITLE
esityslistat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2293]
#### Ehdotettu termi suomeksi

esityslistat
#### Ehdotetut ohjaustermit

asialistat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 17.10.2008

**Muokkauspäivämäärä:** 17.10.2008, 17.10.2008, 16.12.2008

**Voyager-id:** 161916

**Termiehdotus Fintossa:** [esityslistat](http://finto.fi/yse/fi/page/Y361916)

**Comment by mirmaid** [comment]
Tätä on kaipailtu SLM-sanastoon: Täällä kaupunginarkistossa on sidoksena mm. valtuuston esityslistat vuosittain. Sanaa ei ole tosin lajityyppisanastossakaan. Tai sitten etsin väärin. Teen sisäistä aineistolistausta arkistossa sijaitsevasta erillisestä kirjastokokoelmasta. On lähinnä henkilökunnan tukiaineistona ja joskus myös tutkijoiden käytettävissä. Tärkeää olisi löytää sopivilla asiasanoilla aineisto listauksesta.

**Comment by mariaforsen** [comment]
Sv. föredragningslistor HT dagordningar (möten), agendor (möten), ärendelistor 
https://termipankki.fi/tepa/fi/haku/esityslista
https://sv.wikipedia.org/wiki/Dagordning
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_5db35f5759042c96e1558ee89f6ff77b&list_id=1&keyword=esityslista&word=esityslista
https://www.sanakirja.fi/custom/en-sv-fi/esityslista
https://svenska.se/tre/?sok=dagordning&pz=1
https://svenska.se/so/?id=123332&ref=kcnr488048
https://fho.sls.fi/uppslagsord/4940/dagordning/
https://www.sprakbruk.fi/-/arendelista
https://www.rikstermbanken.se/search?q=f%C3%B6redragningslista&s=termer

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
YSO?

Pitäisikö pöytäkirjoilla ja muistioilla olla YSOssa RT-suhde?
Pitäisikö muistioilla olla SLM:ssä KT pöytäkirjat?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
