### ISSUE TITLE
joustava perusopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2302]
#### Ehdotettu termi suomeksi

joustava perusopetus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)
#### Lähde

Julkaisu: Joustava perusopetus
#### Käsitteen määritelmä

Joustava perusopetus JOPO® -hanke käynnistyi tammikuussa 2006, kun opetusministeriö myönsi määrärahaa kunnille koulupudokkaiden aktivointiin tähtäävän toiminnan kehittämiseen perusopetuksessa ja toisen asteen nivelvaiheessa. Joustavan perusopetuksen tavoitteena on tukea oppilaita, jotka ovat vaarassa jäädä ilman perusopetuksen päättötodistusta. Samalla pyritään ehkäisemään toisen asteen koulutuksesta pois jäämistä ja koulutuksen keskeyttämistä.  Toimintamallin avulla kehitetään perusopetukseen yksilöllisiä, oppilaiden erilaiset tarpeet huomioivia toimintatapoja ja opetusmenetelmiä. Joustavassa perusopetuksessa korostuvat toiminnallisuus, erilaisten oppimisympäristöjen käyttö ja työssäoppiminen (http://www.minedu.fi/OPM/Koulutus/artikkelit/koulupudokkaiden_aktivointi/index.html?lang=fi)

**Luontipäivämäärä:** 20.10.2008

**Muokkauspäivämäärä:** 20.10.2008, 16.12.2008, 19.05.2009

**Voyager-id:** 161962

**Termiehdotus Fintossa:** [joustava perusopetus](http://finto.fi/yse/fi/page/Y361962)

**Comment by mirmaid** [comment]
Tarvittu teoksessa _Jopolla pääsee: laadukas joustava perusopetus_

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/Kasvatustieteet:joustava_perusopetus

https://termipankki.fi/tepa/fi/haku/joustava%20perusopetus

**Comment by mariaforsen** [comment]
Sv. flexibel grundläggande utbildning ET flexibel grundundervisning
https://www.oph.fi/sv/utbildning-och-examina/flexibel-grundlaggande-utbildning

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
