### ISSUE TITLE
panssarijunat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2337]
#### Ehdotettu termi suomeksi

panssarijunat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/ysa/ryhma_67)

**Luontipäivämäärä:** 22.10.2008

**Muokkauspäivämäärä:** 22.10.2008, 16.12.2008

**Voyager-id:** 162052

**Termiehdotus Fintossa:** [panssarijunat](http://finto.fi/yse/fi/page/Y362052)

**Comment by AuHo22** [comment]
Teokseen Wetterstrand: Punaisten panssarijuna 1918, mm. takakannessa: Suomen sisällissodassa punakaarti käytti asetta, jollaista ei ennen ollut näillä main nähty: panssarijunaa.
Wikipediassa myös: https://fi.wikipedia.org/wiki/Panssarijuna

**Comment by mariaforsen** [comment]
Sv. pansartåg
