### ISSUE TITLE
konsertoinnit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2422]
#### Ehdotettu termi suomeksi

konsertoinnit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)

**Luontipäivämäärä:** 19.02.2009

**Muokkauspäivämäärä:** 19.2.2009, 19.02.2009

**Voyager-id:** 164324

**Termiehdotus Fintossa:** [konsertoinnit](http://finto.fi/yse/fi/page/Y364324)

**Comment by asormune** [comment]
Vertaa:  luennointi ; luennoitsijat ; luennot. Olisiko samalla kaavalla: konsertointi : konsertoijat ; konsertit

**Comment by mariaforsen** [comment]
Vaikeaa kääntää ruotsiksi monikkomuotoisena. Konserterande (konsertointi) voisi toimia, mutta siitä ei ole mahdollista tehdä monikkomuotoa, vaan silloin käytetään lähinnä konserter (konsertit)

**Comment by asormune** [comment]
Yleisterminä (00) on esiintymiskeikat ; onko konsertit myös esiintymiskeikkoja? On myös termi kiertueet.  Sitten on termi "musiikin esittäminen". Onko konsertointi "musiikin esittämistä konserttitilanteessa" ? Joka on eri asia, kuin musiikin esittäminen (tai soittaminen/laulaminen...)

**Comment by jtuohini** [comment]
Monikkomuoto ei käy, kun kyseessä on jaollinen substantiivi. Mutta Anun analogia asiasanaan **luennointi** osuu napakymppiin, joten siltä osin toki! Voin helpostikin kuvitella tälle löytyvän ainakin jotakin kuvailtavaa aineistoa.
 
Esiintymiskeikat ehkä RT:ksi tälle, kun ehdotettu on tekemistä, keikat taas tapahtumia.

**Comment by jarmosaarikko** [comment]
Missä tätä tarvitaan, oikeasti? "_Muusikko konsertoi konsertissa taitavasti_".  Konsertit löytyy YSA:sta, eikö se riitä?  Esim. trubaduuri voi "esittää musiikia" kulmakapakassa "esiintymiskeikalla", mutten pitäisi sitä konserttina, silti hän voi myös "konsertoida" konsertissa. Olen esiintynyt ja käynyt kymmenissä konserteissa, mutten ole koskaan mieltänyt olevan "konsertoimassa". Ehkä tämä on sitten kielen kehitystä, joka on hyväksyttävä?   Luennoinnin yläkäsite on "opetusmenetelmät" Mikä  olisi konsertoinnin yläkäsite? Esiintyminen?

**Comment by asormune** [comment]
Riitäisikö termit: esittäminen ja esiintyminen (konsertoinnit pois)

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: emme kannata ehdotusta.
