### ISSUE TITLE
purentavirheet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2451]
#### Ehdotettu termi suomeksi

purentavirheet
#### Ehdotetut ohjaustermit

purentaviat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 20.02.2009

**Muokkauspäivämäärä:** 20.2.2009, 02.11.2011

**Voyager-id:** 164368

**Termiehdotus Fintossa:** [purentavirheet](http://finto.fi/yse/fi/page/Y364368)

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä väitöskirjan [Malocclusions and their associations with oral health-related quality of life in the Northern Finland Birth Cohort 1966](https://urn.fi/URN:ISBN:9789526239316) kuvailussa 

FinMeSH: **purentavirhe** http://www.yso.fi/onto/mesh/D008310
LCSH: **Malocclusion** http://id.loc.gov/authorities/subjects/sh85080183
Wikipedia: https://en.wikipedia.org/wiki/Malocclusion

--
Melinda:
purentavika x 15
purentavirhe x 4
purentavirheet x 1

**Comment by mariaforsen** [comment]
Sv. bettfel HT malocklusioner, felaktiga bett, bettanomalier, felbett
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_ef328a8054f28810a8f45a4f42639b65&list_id=1&keyword=purentavika&word=purentavika
/uppslagsverk/encyklopedi/lång/bettfel
https://mesh.kib.ki.se/term/D008310/malocclusion
https://www.sanakirja.fi/custom/all/bettfel
https://www.varden.se/hitta/bettfel-s
