### ISSUE TITLE
ehdollinen arvottaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2502]
#### Ehdotettu termi suomeksi

ehdollinen arvottaminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[02 Filosofia](http://www.yso.fi/onto/ysa/ryhma_02)
#### Lähde

Lähde: Julkaisu: Ahtiainen, H., Järven tilan parantamisen hyödyt
#### Käsitteen määritelmä

Taloudelliset arvottamismenetelmat jaotellaan tyypillisesti kahteen joukkoon: lausuttujen  (tai ilmaistujen) preferenssien menetelmiin ja paljastettujen preferenssien menetelmiin.  Ehdollinen arvottaminen kuuluu lausuttujen preferenssien menetelmiin, jotka perustuvat kyselyiden tekoon.  Ehdollisen arvottamisen menetelmalla ymparistohyodykkeen arvo selvitetaan huolellisesti suunnitellun kyselyn avulla, joissa kysytaan ihmisten maksuhalukkuutta tietysta ymparistohyodykkeen muutoksesta, esimerkiksi vedenlaadun parantumisesta. Kysely sisaltaa kuvauksen ymparistohyodykkeesta ja sen arvottamista varten rakennetuista hypoteettisista markkinoista, joilla ymparistohyodyketta ostetaan ja myydaan. Maksuhalukkuusvastaukset riippuvat (tai ovat ehdollisia) kyselyssa esitetysta hyodykkeesta ja hypoteettisista markkinoista, ja siita tuleekin menetelman englanninkielinen nimi ja myos suomenkielinen kaannos (Mitchell & Carson 1989, 3).

**Luontipäivämäärä:** 19.05.2009

**Muokkauspäivämäärä:** 19.05.2009

**Voyager-id:** 165955

**Termiehdotus Fintossa:** [ehdollinen arvottaminen](http://finto.fi/yse/fi/page/Y365955)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
