### ISSUE TITLE
ilmatiiviys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2511]
#### Ehdotettu termi suomeksi

ilmatiiviys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

Julkaisu: Ilmanpitävien rakenteiden ja liitosten toteutus asuinrakennuksissa

**Luontipäivämäärä:** 19.05.2009

**Muokkauspäivämäärä:** 19.05.2009

**Voyager-id:** 165965

**Termiehdotus Fintossa:** [ilmatiiviys](http://finto.fi/yse/fi/page/Y365965)

**Comment by mirmaid** [comment]
KÄ ilmanpitävyys
