### ISSUE TITLE
kaksikieliset teokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2514]
#### Ehdotettu termi suomeksi

kaksikieliset teokset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/ysa/ryhma_82)

**Luontipäivämäärä:** 19.05.2009

**Muokkauspäivämäärä:** 19.5.2009, 19.05.2009

**Voyager-id:** 165968

**Termiehdotus Fintossa:** [kaksikieliset teokset](http://finto.fi/yse/fi/page/Y365968)

**Comment by mirmaid** [comment]
Palaute: Kaunossa on asiasana "kaksikieliset teokset". Eikö se kuuluisi paremmin slm-sanastoon?

**Comment by mirmaid** [comment]
Kauno-työryhmän käsittelyyn. Samoin monikieliset teokset.

**Comment by jtuohini** [comment]
Viitattaisiinko tällä "kielipelilliseen" kaksikieliseen teokseen vai julkaisuun (manifestaatioon), jossa on yhdestä teoksesta kaksi erikielistä ekspressiota?

**Comment by AuHo22** [comment]
978-952-7347-97-3 Kuinka krokotiili kadotti kielensä
 978-951-1-37739-9 / Tervetuloa! = ‡b Soo dhawoow! = Benvenuti! = Xoš âmadid! = Bi xêr bi!

Ja kirjastolta tullut kysymys: "Onko sellaisille lastenkirjoille, joissa teksti on useammalla eri kielellä, olemassa jokin yhteinen asiasana, jolla niitä voisi etsiä? Meillä on täällä 15 eri kieltä puhuvia lapsia ja tarvetta tällaisille kirjoille. Nyt tuli esim. kaksi aika uutta juuri tähän tarpeeseen." Huomasin, että KAUNOsta löytyy monikieliset teokset. Miksiköhän vain KAUNOsta? Tätä ei ilmeisesti ole meillä käytetty."

**Comment by jtuohini** [comment]
Monikielisistä teoksista ks. oma YSE:nsä [**_monikieliset teokset_**](https://github.com/Finto-ehdotus/YSE/issues/9251).

**Comment by AuHo22** [comment]
https://www.kirjastot.fi/kysy/onko-helmetissa-italiankielisia-kirjoja-joissa?language_content_entity=fi

**Comment by mirmaid** [comment]
KÄ monikieliset kirjat (rinnakkaiskäännökset)
