### ISSUE TITLE
uusi aalto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#258]
#### Ehdotettu termi suomeksi

uusi aalto
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)
#### Lähde

Lähde: Musiikin asiasanasto

**Luontipäivämäärä:** 29.09.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114217

**Termiehdotus Fintossa:** [uusi aalto](http://finto.fi/yse/fi/page/Y314217)

**Comment by mirmaid** [comment]
Tuli YSAan MUSAsta. Tarvitseeko tarkenteen? Entä elokuvaterminä, tarvitaanko? https://fi.wikipedia.org/wiki/Ranskalaisen_elokuvan_uusi_aalto

**Comment by tpalonen** [comment]
Käsite pitäisi jakaa jos halutaan sekä musiikki että elokuva merkityksessä.

**Comment by mariaforsen** [comment]
Nationalencyklopedin:  
-nya vågen: benämning på den grupp av regissörer som vitaliserade och förändrade den franska filmen från genombrottsåret 1959 och några år in på 1960-talet.
-new wave: rockmusikstil som vid 1970-talets slut avlöste punkrockens attack på en stagnerad rockmusik. 

Tarvitaan siis jakoa. Melindassa molempia, esim. : 
-Franska bilder : filmens födelse till Nya vågen / Lasse Bergström.
-Ny våg : svensk punk, new wave, synth 1977-1982/ Peter Kagerland.

**Comment by YSA-kokous** [comment]
uusi aalto (elokuva), uusi aalto (musiikki), LT?

**Comment by mariaforsen** [comment]
Sv. 
-nya vågen (film) ET  nouvelle vague
-new wave (musik)

**Comment by MUUSA-kokous** [comment]
Voisko tämän suljetun ehdotuksen poistaa YSAn ja YSOn käsite-ehdotuksista? http://www.yso.fi/onto/ysa/Y314217
