### ISSUE TITLE
poikatutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2633]
#### Ehdotettu termi suomeksi

poikatutkimus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)

**Luontipäivämäärä:** 18.11.2009

**Muokkauspäivämäärä:** 18.11.2009

**Voyager-id:** 169474

**Termiehdotus Fintossa:** [poikatutkimus](http://finto.fi/yse/fi/page/Y369474)

**Comment by mariaforsen** [comment]
Sv. pojkforskning
