### ISSUE TITLE
psykologinen sopimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2635]
#### Ehdotettu termi suomeksi

psykologinen sopimus
#### Ehdotetut ohjaustermit

psykologinen työsopimus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)
[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/ysa/ryhma_78)
#### Käsitteen määritelmä

Työodotukset liittyvät psykologiseen sopimukseen, joka on määritelty ”ryhmäksi uskomuksia, joita kukin osapuoli on oikeutettu saamaan ja sitoutunut antamaan, vastapainona toisen osapuolen panokselle työympäristössä” (Morrison & Robinson, 1997). Psykologinen sopimus määrittelee siis sen mitä toinen odottaa saavansa vastapainoksi omasta panoksestaan (http://www.basium.fi/tyoodotukset.htm)

**Luontipäivämäärä:** 18.11.2009

**Muokkauspäivämäärä:** 18.11.2009, 18.11.2009, 27.9.2012, 20.12.2011, 20.12.2011, 20.12.2011, 20.12.2011, 27.09.2012

**Voyager-id:** 169477

**Termiehdotus Fintossa:** [psykologinen sopimus](http://finto.fi/yse/fi/page/Y369477)

**Comment by fantsby-m** [comment]
Nosto. Tarvitaan kuvailussa: väitös Psykologinen sopimus omaishoidon sopimuksellisuuden ilmentäjänä /Marjo Ring (978-952-61-3788-9)

**Comment by fantsby-m** [comment]
Ks. myös https://en.wikipedia.org/wiki/Psychological_contract

**Comment by ilona-x** [comment]
TSR:
psykologiset sopimukset http://www.yso.fi/onto/tsr/p6606

**Comment by mariaforsen** [comment]
Sv. psykologiskt kontrakt HT psykologiska kontrakt, psykologiskt avtal
https://www.psykologiguiden.se/psykologilexikon/?Lookup=psykologiskt+kontrakt

**Comment by mirmaid** [comment]
18 kertaa Melindassa yksikössä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _psykologinen sopimus_, monikko ohjaustermiksi.
