### ISSUE TITLE
etäseuranta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2694]
#### Ehdotettu termi suomeksi

etäseuranta
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 11.03.2010

**Muokkauspäivämäärä:** 11.03.2010

**Voyager-id:** 171615

**Termiehdotus Fintossa:** [etäseuranta](http://finto.fi/yse/fi/page/Y371615)

**Comment by tarjaturunen** [comment]
Tarve termille sis.kuvailussa ks. teos http://epublications.uef.fi/pub/urn_isbn_978-952-61-2440-7/urn_isbn_978-952-61-2440-7.pdf
teoksessa käytetty muotoa etämonitorointi

**Comment by mirmaid** [comment]
YSAssa on _etäluenta_, KT etämittaus.

TSR-ontologiassa on _etävalvonta_.

Melindassa kerran etämonitorointi ja etäseuranta, 2 x etävalvonta, 10 x etäluenta. Kaikkia käytetään monenlaisissa konteksteissa, vähän erilaisin painotuksin.

**Comment by Elmukelmu** [comment]
Olisi oikein käyttökelpoinen! Ja nimenomaan tuo etäseuranta. YSAssa tällä hetkellä lisäksi etäkäyttö, etäpalvelut ja lisäksi kaukovalvonta (joka taitaa olla yksinomaan vartiointi/turva-alaa).

**Comment by YSA-kokous** [comment]
etäseuranta

**Comment by mariaforsen** [comment]
Sv.  distansmonitorering ET distansuppföljning ET uppföljning på distans
