### ISSUE TITLE
halveksunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2698]
#### Ehdotettu termi suomeksi

halveksunta
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)

**Luontipäivämäärä:** 11.03.2010

**Muokkauspäivämäärä:** 11.03.2010

**Voyager-id:** 171620

**Termiehdotus Fintossa:** [halveksunta](http://finto.fi/yse/fi/page/Y371620)

**Comment by tarjaturunen** [comment]
Tätä termiä olisi tarvittu sisällönkuvailussa tämä kirjan kohdalla https://melinda.kansalliskirjasto.fi/byid/018214824

**Comment by mirmaid** [comment]
KAUNOssa.
LCSH: http://id.loc.gov/authorities/subjects/sh00001122

3 kertaa Melindassa vapaana avainsanana, muutaman kerran KAUNO-terminä.

**Comment by mariaforsen** [comment]
Sv. förakt HT ringaktning, missaktning
https://kaino.kotus.fi/finsk-svensk/?p=article&word=halveksinta&suru_id=SURU_8502b4955ab1dd82ff0432023ef06a71

**Comment by mirmaid** [comment]
Sanastossa on väheksyntä KÄ _vähättely_. Ei toki ole aivan sama, mutta likeinen.
