### ISSUE TITLE
luonnonvarapolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2749]
#### Ehdotettu termi suomeksi

luonnonvarapolitiikka
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)

**Luontipäivämäärä:** 15.03.2010

**Muokkauspäivämäärä:** 18.5.2010, 15.3.2010, 13.5.2011, 13.5.2011, 13.05.2011

**Voyager-id:** 171722

**Termiehdotus Fintossa:** [luonnonvarapolitiikka](http://finto.fi/yse/fi/page/Y371722)

**Comment by marikava** [comment]
Luonnonvarapolitiikka soveltuisi seuraavaan teokseen asiasanaksi: 
Hiedanpää, J. (2021) Tiedeneuvo : ihmistieteen näkökulmia luonnonvarapolitiikan muotoiluun . Tampere: Vastapaino.

**Comment by mariaforsen** [comment]
Sv. naturresurspolitik

**Comment by LeKorsu** [comment]
Melindasta kuusi osumaa, joista yksi tuo yllämainittu teos ja loput artikkeleita. En vastusta ottamista, vaikkei tuon enempää käytössä Melindassa. Googlella  noin 19800 osumaa.
