### ISSUE TITLE
viestintätoimistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#276]
#### Ehdotettu termi suomeksi

viestintätoimistot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 30.09.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114243

**Termiehdotus Fintossa:** [viestintätoimistot](http://finto.fi/yse/fi/page/Y314243)

**Comment by LeKorsu** [comment]
Voisiko tämän ottaa preflabeliksi mediatoimistojen sijaan, jos niiden katsotaan olevan päällekkäiset? Viestintätoimisto on nykyisin paljon yleisemmin käytetty kuin mediatoimisto. Luetteloitavana kirja Viestintätoimistojen valta (isbn 978-951-768-988-5).

**Comment by ilona-x** [comment]
Wikipediassa suomeksi molemmat, mutta vain mediatoimisto-artikkelilla on kielivastineita:
https://fi.wikipedia.org/wiki/Viestint%C3%A4toimisto
https://fi.wikipedia.org/wiki/Mediatoimisto

**Comment by mariaforsen** [comment]
Nämä eivät välttämättä ole sama asia (ainakaan ruotsiksi):
https://www.gigstr.com/blogg/kommunikationsbyra-7-tips-for-att-valja-ratt : 
"Först och främst, låt oss reda ut lite begrepp. Ordet kommunikationsbyrå är ett samlingsnamn namn för flera typer av byråer, till exempel:
Eventbyrå
Reklambyrå
Webbyrå
Mediebyrå
PR-byrå
Sociala medier-byrå
Många byråer väljer att benämna sig med något av dessa mer specialiserade namn. Namnen förtydligar vilken del av marknadskommunikationen byrån fokuserar på. Alla samlas under huvudkategorin kommunikationsbyrå"

Mutta siitä olen samaa mieltä että viestintätoimistot on ainakin tärkeä käsite, eli mieluummin se, jos täytyy valita. 

Sv. kommunikationsbyråer

**Comment by mirmaid** [comment]
Ainakin suomeksi nämä ilmeisesti nähdään osittain eri asioina, mutta en kyllä löydä lähdettä, jossa olisi jotenkin määritelty merkityksiä suhteessa toisiinsa. Englanniksi kyllä communications agency tuo runsaasti viitteitä sekin, mutta media agency paljon enemmän. Mahtaako Leenan aineistossa olla mitään selvennystä?

**Comment by LeKorsu** [comment]
Yllämainitussa Viestintätoimistojen valta -kirjassa sanotaan näin: "Tätä kirjaa varten on haastateltu yli viittäkymmentä alan asiantuntijaa, mutta heilläkään ei ollut tarjota selkeää kuvausta siitä, mitä viestintätoimistot oikeastaan tekevät. Yleisin määritlmä kuvasi viestintätoimistoa yrityksenä, joka tuottaa laajalti erilaisia viestintäpalveluja...Viestintätoimistoissa ei kuitenkaan tehdä ensisijaisesti markkinointia, joka on enemmän mainostoimistojen työsarkaa."

Ville Blåfieldin twiitti parin vuoden takaa: https://twitter.com/villebla/status/1299085990754160649
Se ei tosin auta meitä eron määrittelyssä.

Oma mutu-tuntuma suomalaisesta mediakirjoittelusta on vain se, että missään ei enää kirjoiteta mediatoimistoista, vain viestintätoimistoista.

**Comment by mirmaid** [comment]
Omana terminään.
