### ISSUE TITLE
profaani

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2775]
#### Ehdotettu termi suomeksi

profaani
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)

**Luontipäivämäärä:** 16.03.2010

**Muokkauspäivämäärä:** 16.03.2010

**Voyager-id:** 171755

**Termiehdotus Fintossa:** [profaani](http://finto.fi/yse/fi/page/Y371755)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
