### ISSUE TITLE
roolirunot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2783]
#### Ehdotettu termi suomeksi

roolirunot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)
#### Lähde

Julkaisu: Olla elävän sanat
#### Käsitteen määritelmä

Runo, jonka puhuja esittää ajatuksiaan ja tunteitaan roolihahmossa, usein draamallisen monologin muodossa (esim. Spoon River antologia) (Kaunokin määritelmä)

**Luontipäivämäärä:** 16.03.2010

**Muokkauspäivämäärä:** 16.03.2010

**Voyager-id:** 171765

**Termiehdotus Fintossa:** [roolirunot](http://finto.fi/yse/fi/page/Y371765)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2247

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä väitöskirjan "Rolldiktens jag :aspekter på svenskspråkiga rolldikter från Bellman till Runeberg" kuvailussa. 

SLM-sanastossa: http://finto.fi/slm/fi/page/s860

**Comment by mariaforsen** [comment]
Sv. rolldikter
