### ISSUE TITLE
valokuvakirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2806]
#### Ehdotettu termi suomeksi

valokuvakirjat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/ysa/ryhma_82)
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)

**Luontipäivämäärä:** 16.03.2010

**Muokkauspäivämäärä:** 16.3.2010, 16.03.2010

**Voyager-id:** 171796

**Termiehdotus Fintossa:** [valokuvakirjat](http://finto.fi/yse/fi/page/Y371796)

**Comment by jtuohini** [comment]
Tästä mieluummin KÄ-viittaus YSO-asiasanaan [**kuvateokset**](http://www.yso.fi/onto/yso/p2599) ja SLM-termiin [**kuvateokset**](http://urn.fi/URN:NBN:fi:au:slm:s487).

**Comment by YSO-kokous** [comment]
Hyväksytään valokuvakirjat KÄ kuvateokset
