### ISSUE TITLE
kuivakausi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2839]
#### Ehdotettu termi suomeksi

kuivakausi
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[14 Klimatologia. Meteorologia. Ilmatiede](http://www.yso.fi/onto/ysa/ryhma_14)

**Luontipäivämäärä:** 26.05.2010

**Muokkauspäivämäärä:** 26.05.2010

**Voyager-id:** 173088

**Termiehdotus Fintossa:** [kuivakausi](http://finto.fi/yse/fi/page/Y373088)

**Comment by henriyli** [comment]
YSAan 10.1.2014: http://www.yso.fi/onto/ysa/Y196619
