### ISSUE TITLE
älyliikenne

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2885]
#### Ehdotettu termi suomeksi

älyliikenne
#### Ehdotetut ohjaustermit

älykäs liikenne
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)
#### Käsitteen määritelmä

Tarkoittaa tieto- ja viestintätekniikan hyväksi käyttämistä liikennejärjestelmässä, kaikissa liikennemuodoissa sekä henkilö- että tavaraliikenteessä. Älyliikenne auttaa ja ohjaa valitsemaan ja optimoimaan liikkumisen kokonaisuuden kannalta edullisimmalla tavalla ja siten parantaa liikennejärjestelmän tuottavuutta, turvallisuutta, sujuvuutta, tehokkuutta ja ympäristöystävällisyyttä. Älyliikenne on keskeinen osa liikennepolitiikkaa ja tietoyhteiskuntapolitiikkaa (Kansallinen älyliikenteen strategia)

**Luontipäivämäärä:** 26.05.2010

**Muokkauspäivämäärä:** 26.05.2010

**Voyager-id:** 173176

**Termiehdotus Fintossa:** [älyliikenne](http://finto.fi/yse/fi/page/Y373176)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin kuvailussa https://www.doria.fi/bitstream/handle/10024/120904/lts_2011-16_978-952-255-649-3.pdf?sequence=1

**Comment by ilona-x** [comment]
YSA:ssa: älykäs liikenne KÄYTÄ liikennetelematiikka http://finto.fi/ysa/fi/page/Y164136

**Comment by mariaforsen** [comment]
Sv. intelligent trafik, smarttrafik?

**Comment by mirmaid** [comment]
Liikennetelematiikka (ITS, Intelligent Transportation System tai Intelligent Transportation Systems and Services) tarkoittaa tieto- ja viestintätekniikan, erityisesti tietoliikenne- ja paikkatietotekniikan yhdistelmien soveltamista henkilö- ja tavaraliikenteessä maalla, merellä ja ilmassa. https://fi.wikipedia.org/wiki/Liikennetelematiikka

KÄ liikennetelematiikka
