### ISSUE TITLE
huudot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2915]
#### Ehdotettu termi suomeksi

huudot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

Julkaisu: Kalikali - kalikali -ooaa (partiohuutoja)

**Luontipäivämäärä:** 03.11.2010

**Muokkauspäivämäärä:** 03.11.2010

**Voyager-id:** 175774

**Termiehdotus Fintossa:** [huudot](http://finto.fi/yse/fi/page/Y375774)

**Comment by krinay** [comment]
KULA-termi (KT katuhuudot). 
LCSH: http://id.loc.gov/authorities/subjects/sh85033990 (cries UF street cries)
Esim. teos Danish street cries: a study of their musical structure and a complete edition of tunes with words collected before 1960

**Comment by mirmaid** [comment]
Melindassa 6 kertaa, käsittelevät katukauppaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
rop
