### ISSUE TITLE
opintotoimistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2958]
#### Ehdotettu termi suomeksi

opintotoimistot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 03.11.2010

**Muokkauspäivämäärä:** 03.11.2010

**Voyager-id:** 175830

**Termiehdotus Fintossa:** [opintotoimistot](http://finto.fi/yse/fi/page/Y375830)

**Comment by henriyli** [comment]
YSAan 7.6.2012 : http://www.yso.fi/onto/ysa/Y186390
