### ISSUE TITLE
urbaani  löytöretkeily

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2992]
#### Ehdotettu termi suomeksi

urbaani  löytöretkeily
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)
#### Lähde

Lähde: Wikipedia
#### Käsitteen määritelmä

Urbaani löytöretkeily (engl. urban exploration, urban exploring, UE, urbex) tarkoittaa normaalisti näkymättömien, usein kaupungeissa sijaitsevien tilojen tutkimista. Suosittuja tutkimuskohteita ovat muun muassa:  - hylätyt rakennukset (esimerkiksi tehtaat, autiotalot) ja rauniot  - aavekaupungit  - käytössä olevat rakennukset ja rakennelmat (katto, kellarikerros, huoltotilat)  - tunnelit  - viemärit  - kaivokset ja louhokset

**Luontipäivämäärä:** 04.11.2010

**Muokkauspäivämäärä:** 4.11.2010, 04.11.2010

**Voyager-id:** 175882

**Termiehdotus Fintossa:** [urbaani  löytöretkeily](http://finto.fi/yse/fi/page/Y375882)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
