### ISSUE TITLE
uskonnolliset lait

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#2993]
#### Ehdotettu termi suomeksi

uskonnolliset lait
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)

**Luontipäivämäärä:** 04.11.2010

**Muokkauspäivämäärä:** 04.11.2010

**Voyager-id:** 175884

**Termiehdotus Fintossa:** [uskonnolliset lait](http://finto.fi/yse/fi/page/Y375884)

**Comment by YSO-kokous** [comment]
Tarvitaan YSOn hierarkiaan
alakäsitteeksi  sharia
Wikidata http://www.wikidata.org/entity/Q670732
LCSH 
http://id.loc.gov/authorities/subjects/sh85112661 Religious law and legislation
http://id.loc.gov/authorities/subjects/sh85112572 Religion and law --- **ei ehkä tämä**

Wikipedia
https://en.wikipedia.org/wiki/Religious_law
https://sv.wikipedia.org/wiki/Religi%C3%B6s_lag
https://fi.wikipedia.org/wiki/Luokka:Uskonnolliset_lait

**Comment by mariaforsen** [comment]
Sv. religiösa lagar

**Comment by AuHo22** [comment]
Käytetäänkö termiä silloin, kun laki on omaksuttu osaksi kansallista lainsäädäntöä vai silloinkin, kun se on normi jonkin uskonnon harjoittamisen sisällä? Esim. "Myös nykyisin Israelin oikeusjärjestelmä joka pääasiassa perustuu tapaoikeuteen, on omaksunut myös halakhasta kohtia. Halakhan tarkempi noudattaminen jää kuitenkin yksilön vastuulle." (Wikipedia: Halakha) Vai molemmista?

**Comment by YSO-kokous** [comment]
### Päätös
uskonnolliset lait  LT yhteiskunnalliset järjestelmät
