### ISSUE TITLE
kylmäaineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3046]
#### Ehdotettu termi suomeksi

kylmäaineet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[09 Kemia](http://www.yso.fi/onto/ysa/ryhma_09)
#### Lähde

Julkaisu: Ilmalämpöpumpun toiminta ja asennus

**Luontipäivämäärä:** 09.03.2011

**Muokkauspäivämäärä:** 09.03.2011

**Voyager-id:** 177959

**Termiehdotus Fintossa:** [kylmäaineet](http://finto.fi/yse/fi/page/Y377959)

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä julkaisun "Kylmäaineet, kylmäkoneöljyt, lainsäädäntö SFS-EN 378" kuvailussa.

Melinda: kylmäaineet x 11

LCSH: http://id.loc.gov/authorities/subjects/sh85112274
https://en.wikipedia.org/wiki/Refrigerant

**Comment by mirmaid** [comment]
KT jäähdytysaineet?

**Comment by mariaforsen** [comment]
Sv. köldmedier ET kylmedel, kylmedier
