### ISSUE TITLE
nuorisopalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3064]
#### Ehdotettu termi suomeksi

nuorisopalvelut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/ysa/ryhma_73)

**Luontipäivämäärä:** 09.03.2011

**Muokkauspäivämäärä:** 12.12.2013, 12.12.2013

**Voyager-id:** 177981

**Termiehdotus Fintossa:** [nuorisopalvelut](http://finto.fi/yse/fi/page/Y377981)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
