### ISSUE TITLE
superruoka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3092]
#### Ehdotettu termi suomeksi

superruoka
#### Ehdotetut ohjaustermit

superfood
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/ysa/ryhma_24)
#### Käsitteen määritelmä

Terveyttä edistävä ruoka, Suomessa esim. mustikat

**Luontipäivämäärä:** 10.03.2011

**Muokkauspäivämäärä:** 4.11.2013, 10.3.2011, 27.10.2015

**Voyager-id:** 178073

**Termiehdotus Fintossa:** [superruoka](http://finto.fi/yse/fi/page/Y378073)

**Comment by henriyli** [comment]
YSAan 9.6.2016, http://www.yso.fi/onto/ysa/Y209038
