### ISSUE TITLE
televisioteollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3096]
#### Ehdotettu termi suomeksi

televisioteollisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)

**Luontipäivämäärä:** 10.03.2011

**Muokkauspäivämäärä:** 10.03.2011

**Voyager-id:** 178077

**Termiehdotus Fintossa:** [televisioteollisuus](http://finto.fi/yse/fi/page/Y378077)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2171
