### ISSUE TITLE
tendenssikirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3097]
#### Ehdotettu termi suomeksi

tendenssikirjallisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 10.03.2011

**Muokkauspäivämäärä:** 10.03.2011

**Voyager-id:** 178078

**Termiehdotus Fintossa:** [tendenssikirjallisuus](http://finto.fi/yse/fi/page/Y378078)

**Comment by amssi** [comment]
Tendenssikirjallisuus (tendentious literature, tendenslitteratur) on asiasanana KAUNOssa. Miksei tätä siis voisi hyväksyä YSAankin? Mielipidekirjallisuus (pamphlet literature, debattlitteratur) ei ole sama asia, kuten käännöksistäkin näkyy.

**Comment by mirmaid** [comment]
Myös KITOssa ja SLM:ssä. 
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:tendenssikirjallisuus

**Comment by mariaforsen** [comment]
Sv. tendenslitteratur
