### ISSUE TITLE
vertaislainat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3111]
#### Ehdotettu termi suomeksi

vertaislainat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)
#### Lähde

Lähde: Suomen kuvalehti 1/2011
#### Käsitteen määritelmä

Laina, jonka henkilö ottaa toisilta henkilöiltä Internet-palvelun välityksellä

**Luontipäivämäärä:** 10.03.2011

**Muokkauspäivämäärä:** 10.03.2011

**Voyager-id:** 178101

**Termiehdotus Fintossa:** [vertaislainat](http://finto.fi/yse/fi/page/Y378101)

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä väitöskirjan "Predicting risk and return in peer-to-peer lending with machine learning" kuvailussa.

Löytyy JUPOsta http://www.yso.fi/onto/jupo/p6568

LCSH Peer-to-peer loans http://id.loc.gov/authorities/subjects/sh2018000384

Wikipediassa vertaislainaus https://fi.wikipedia.org/wiki/Vertaislainaus

**Comment by ilona-x** [comment]
Melinda:
vertaislaina x 1
vertaislainat x 2
vertaislainaus x 2

**Comment by mariaforsen** [comment]
Sv. person-till-person-lån HT peer-to-peer-lån, peer to peer lån, p2p-lån
https://www.sanakirja.fi/custom/en-sv-fi/vertaislaina
https://www.vero.fi/sv/Detaljerade_skatteanvisningar/stallningstaganden/76763/person-till-person-l%C3%A5n-till-privatpersoner-och-l%C3%A5nebaserad-gr%C3%A4srotsfinansiering-till-f%C3%B6retag--beskattning-av-%C3%B6verl%C3%A5telse-och-slutlig-f%C3%B6rlust-av-skuldkapital/
https://www.suomenpankki.fi/sv/statistik/grasrotsfinansiering-och-person-till-person-lan2/
https://sv.wikipedia.org/wiki/Person-till-person-l%C3%A5n
