### ISSUE TITLE
ajanvietelehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3121]
#### Ehdotettu termi suomeksi

ajanvietelehdet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 15.06.2011

**Muokkauspäivämäärä:** 15.06.2011

**Voyager-id:** 180060

**Termiehdotus Fintossa:** [ajanvietelehdet](http://finto.fi/yse/fi/page/Y380060)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9
