### ISSUE TITLE
ihminen-tietokone-vuorovaikutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3139]
#### Ehdotettu termi suomeksi

ihminen-tietokone-vuorovaikutus
#### Ehdotetut ohjaustermit

ihmisen ja tietokoneen vuorovaikutus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)
[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)
#### Lähde

Julkaisu: Ihmisen ja tietokoneen vuorovaikutus

**Luontipäivämäärä:** 15.06.2011

**Muokkauspäivämäärä:** 15.06.2011

**Voyager-id:** 180082

**Termiehdotus Fintossa:** [ihminen-tietokone-vuorovaikutus](http://finto.fi/yse/fi/page/Y380082)

**Comment by mariaforsen** [comment]
Otetaanko tämä erillisenä terminä vai riittääkö mahdollisesti  korvattuna terminä jo sanastossa olevalle termille "ihminen-konejärjestelmät"? 

Allärsissa on tällä hetkellä: människa-dator-interaktion=ihminen-konejärjestelmät, mutta harkitaan pitäisikö tämä muuttaa, koska "människa-dator-interaktion" on oikeastaan =ihminen-tietokone-vuorovaikutus. 

SAOssa on:
-Människa-dator-interaktion=LCSH Human-computer interaction 
-Människa-maskin-interaktion= LCSH Human-machine systems

Näiden termien merkityskentät ovatkin kyllä erilaisia.

**Comment by ilona-x** [comment]
LCSH:ssa molemmat: 
Human-machine systems http://id.loc.gov/authorities/subjects/sh85080326.html
Human-computer interaction http://id.loc.gov/authorities/subjects/sh88003229

Käytettävyystutkimuksessa ihmisen ja tietokoneen vuorovaikutus (tai ihminen-tietokone-vuorovaikutus) olisi mielestäni parempi termi kuin ihminen-konejärjestelmät, vaikka termin muoto onkin vähän huono.

https://fi.wikipedia.org/wiki/HCI
http://tieteentermipankki.fi/wiki/Tietojenk%C3%A4sittelytiede:ihmisen_ja_tietokoneen_vuorovaikutus

Eli ottaisin tuon 'ihmisen ja tietokoneen vuorovaikutus' erikseen. Tai toinen vaihtoehto olisi ottaa se päätermiksi ja muuttaa ihminen-konejärjestelmät korvatuksi termiksi, mutta ensin pitäisi tutkia, miten tuota on Melindassa käytetty ja olisiko vaihto mahdollinen.

Google: 
ihminen-konejärjestelmät 1 750 
ihminen-tietokone-vuorovaikutus 155 000

**Comment by mirmaid** [comment]
Fraasina käytetympi on _ihmisen ja tietokoneen vuorovaikutus_, ja varmaan käytetyin suomeksikin _HCI_.

**Comment by YSA-kokous** [comment]
ihmisen ja tietokoneen vuorovaikutus KT HCI

**Comment by mirmaid** [comment]
RT katseenseuranta (?)
