### ISSUE TITLE
kuvaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3154]
#### Ehdotettu termi suomeksi

kuvaukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Käsitteen määritelmä

Kielitoimiston sanakirja:  kuvaus   =  1. valo- t. elokuvaamisesta. Opetusfilmin kuvaus. Valo-, elokuvaus. Muotikuvaus. Lähikuvaus.   2. muusta kuvantamisesta. Röntgen-, kaiku-, magneettikuvaus. Keuhkokuvaus.   3. kuvaileva esitys, kuvailu, kertomus, selostus. Sanallinen, matemaattinen kuvaus jstak. Henkilö-, matkakuvaus. Luonteenkuvaus. Toimenkuvaus. Antaa kuvaus jstak tapahtumasta.   4. fys. kuvan syntyminen optisessa laitteessa t. järjestelmässä.

**Luontipäivämäärä:** 15.06.2011

**Muokkauspäivämäärä:** 15.06.2011

**Voyager-id:** 180099

**Termiehdotus Fintossa:** [kuvaukset](http://finto.fi/yse/fi/page/Y380099)

**Comment by mirmaid** [comment]
YSOon on otettu käsite kuvaukset (tuotokset). (Kielitoimiston sanakirjan merkitys 3. kuvaileva esitys, kuvailu, kertomus, selostus. _Sanallinen, matemaattinen kuvaus jstak. Henkilö-, matkakuvaus. Luonteenkuvaus. Toimenkuvaus. Antaa kuvaus jstak tapahtumasta._ )

**Comment by mirmaid** [comment]
Käytetty Melindassa myös monikossa (kirjallisista kuvauksista). Sekä kuvaus että kuvaukset voivat viitata sekä kirjalliseen että elokuva/videokuvaukseen. Monikkoa on käytetty kerran jälkimmäisessä merkityksessä.

**Comment by mirmaid** [comment]
Kun kyse on kirjallisista kuvauksista, myös yksikköä on käytetty samaan tapaan kuin monikkoa – aineiston kohteena on ”rakkauden kuvaus kirjallisuudessa” tai ”rakkauden kuvaukset kirjallisuudessa”.

**Comment by mariaforsen** [comment]
Ruotsiksi kuvaus=skildring ja ALLFOssa kuvaukset=skildringar, eli ei mitään elo/valokuviin liittyvää. Sanastossa myös: kuvailu=beskrivning, elokuvaus=filmning, valokuvaus=fotografering. 

Päätettävä ensin missä merkityksessa kuvaukset otetaan, vai jaettuna?

**Comment by mirmaid** [comment]
Elokuvaus on ehkä suomeksi vähän kömpelö ja pelkkää kuvaus-termiä on käytetty siinä merkityksessä myös. Mutta tosiaan siis päätettävä mitä tarvitaan. En oikein näe tarpeellisena (tai lähinnä kovin käytössä toimivana) tuota toiminta vs. tuotos jaottelua tässä kuitenkaan.

**Comment by mirmaid** [comment]
Elokuvan jne. kuvaus pitäisi saada erotettua, elokuvaus-termi ei ole toimiva (liian suppea ja vieras). Jatketaan seuraavassa kokouksessa. (YSA-kokous 6.10.2016)

**Comment by mirmaid** [comment]
Kuvaus (toiminta) ja kuvaukset (tuotokset) - seuraava kokous

**Comment by mariaforsen** [comment]
Siis kai nykyiset elokuvaus ja valokuvaus ainakin saavat olla.. Ne ovat nyt selkeitä ruotsinkin osalta: http://finto.fi/ysa/sv/page/Y100002?clang=fi ja http://finto.fi/ysa/sv/page/Y95003?clang=fi

**Comment by mirmaid** [comment]
Jatketaan siis elokuvan jne. käsittelyä issuessa #5258. Tässä issuessa kirjalliset kuvaukset/kirjallinen kuvaus. Päätettävä:
1. tarvitaanko erikseen kirjallinen kuvaus toimintana - ”rakkauden kuvaus (=kuvaaminen) kirjallisuudessa” ja toiminnan tuotokset ”rakkauden kuvaukset kirjallisuudessa”

2. sulkutarkenne/-tarkenteet
2a. mikäli ei tarvita erikseen toiminta ja tuotos -merkityksiä, tarvitaan tarkenne joka erottaa tämän käsitteen elokuvan tms. kuvauksesta
2b. mikäli tarvitaan erikseen toiminta ja tuotos -merkitykset, tarvitaan tarkenteet jotka erottavat: 
2ba. kirjallisen kuvaamisen elokuvan jne. kuvaamisesta ja kirjallisen kuvaamisen tuotoksista, sekä 
2bb. kirjallisen kuvaamisen tuotokset elokuvan jne. kuvauksista ja kirjallisesta kuvaamisesta

**Comment by krinay** [comment]
Niin, olennaista tosiaan on se, onko enemmän käyttöä genre-termeille (kuvaukset) vai asiasanoille, joilla voi kuvata tutkimuksia kirjailijan tavasta kuvailla jotakin. Vai molemmille. 

Jos haetaan tuota jälkimmäistä (Mirjan vaihtoehto 2a), voisiko yläkäsitteenä olla **kuvailu** ja sen alakäsitteinä:
ajankuvaus
henkilökuvaus
kansankuvaus
kotiseutukuvaukset [sic]
luonnonkuvaus
miljöökuvaus
yhteiskuntakuvaus

Noin on YSOssa tällä hetkellä. Lisäksi _kuvailun_ alakäsitteenä on _bibliografinen kuvailu_, mutta riittäisikö sille yläkäsitteeksi pelkästään _bibliografinen valvonta_, joka nyt on sen toinen yläkäsite YSAssa?

**Kuvaus** voisi sitten olla elokuvauksen, valokuvauksen jne. yläkäsite. Käsitteet kuvaus ja kuvailu olisivat assosiatiivisessa suhteessa toisiinsa. 

Meillä kirjallisuudentutkimuksen informaatikot pitävät nimenomaan tätä kuvailu-aspektia tärkempänä kuin genre-aspektia, mutta toisaalta Melindassa noita kuvaus-loppuisia on käytetty todella paljon kauno- ja muunkin kirjallisuuden lajityyppeinä.  Siinä merkityksessähän monikkomuoto olisi kai parempi. 

Mikä muuten on YSAn ja Genresanaston suhde? Ovatko kaikki monografioiden genretermit YSA-sanoja?

**Comment by siikaa** [comment]
Minusta myös kuvaus (liikkua kuva) voi olla kunhan nuo muut jo olemassaolevat säilyvät. Siis elokuvaus, videokuvaus jne.

**Comment by mirmaid** [comment]
^ Toistaiseksi ovat olleet YSA-sanoja, mutta voivat kyllä olla jatkossa myös ihan erillisiä. 

En itse näkisi että monikollinen muoto on pelkästään genretermi, vaan voidaan myös tutkia rakkauden kuvauksia kirjallisuudessa. Lähinnä näen hakijan ja kuvailijan kannalta hankalana jos täytyy erottaa toisistaan kuvaus toimintana ja tämän toiminnan tulokset - oletan että hakija on kiinnostunut sekä rakkauden kuvaamisesta kirjallisuudessa että näin syntyneistä rakkauden kuvauksista, ja kuvailijoiden olisi myös varsin hankalaa käyttää näitä johdonmukaisesti laittamatta jokaiseen aineistoon molempia, mikäli molemmat ovat käytettävissä samassa sanastossa.

**Comment by krinay** [comment]
Samaa mieltä. Käytännössä on hankalaa, jos sanastossa on sanasta sekä yksiköllinen että monikollinen muoto.

**Comment by mirmaid** [comment]
Päätettävä ensin tarvitaanko sekä kuvaus että kuvaukset, vai riittääkö jompikumpi.

**Comment by krinay** [comment]
Jompikumpi varmasti riittää.

**Comment by satuniininen** [comment]
Pitäisin yksiköllistä tarpeellisempana.

**Comment by mirmaid** [comment]
Jos jätetään yksikkömuoto, se on kirjastokontekstin ulkopuolella tosiaan hyvin lähellä _kuvailu_-termiä kuten Kristiina kommentoikin. Sulkutarkenteena voisi olla joko _kuvaus (kuvailu)_, jolloin varmaankin olisi jo loogista yhdistää nämä kaksi - merkityskenttä olisi laajempi kuin (kauno)kirjallisuus, mutta kirjastokuvailu olisi kuitenkin eri asia (bibliog. kuvailu). Toinen mahdollinen tarkenne olisi sitten vain _(kirjallisuus)_, KT kuvailu (kirjallisuus), kuvaukset (kirjallisuus).

**Comment by AuHo22** [comment]
Joitakin yo. -kuvaus -loppuisia termejä voidaan käyttää myös maalaustaiteen yhteydessä, esim. kansankuvaus. Eli onko kirjallisuus-tarkenne liian suppea?

**Comment by YSA-kokous** [comment]
kuvaus (kuvailu)

**Comment by mariaforsen** [comment]
Sv. skildring
