### ISSUE TITLE
näytelmäsovitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3165]
#### Ehdotettu termi suomeksi

näytelmäsovitukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 15.06.2011

**Muokkauspäivämäärä:** 15.06.2011

**Voyager-id:** 180110

**Termiehdotus Fintossa:** [näytelmäsovitukset](http://finto.fi/yse/fi/page/Y380110)

**Comment by ilkkahaataja** [comment]
SLM-sanasto: SLM-sanastossa on sekä "näytelmäsovitukset" että "dramatisoinnit". Ehdotus: poistetaan toinen ("näytelmäsovitukset"?) SLM-sanastosta tai muokataan termien määritelmiä.

**Comment by mariaforsen** [comment]
Myös ruotsin kannalta riittäisi varmaan dramatiseringar.
https://svenska.se/tre/?sok=dramatisering&pz=1

**Comment by ilkkahaataja** [comment]
Toisaalta LCGFT-sanastossa "dramatizations" esiintyy vain viittausterminä: 

 dramatizations ->  film adaptations = filmatisoinnit (SLM)
 dramatizations ->  radio adaptations = SLM puuttuu, radiosovitus (mts-suhdetermi)
 dramatizations -> television adaptations = SLM puuttuu, televisiosovitus (mts-suhdetermi)
 dramatizations -> theatrical adaptations = näytelmäsovitukset vai dramatisoinnit? (SLM)

**Comment by mirmaid** [comment]
Uutena radiosovitukset, poistetaan dramatisoinnit (KÄ näytelmäsovitukset, radiosovitukset, filmatisoinnit).

**Comment by mariaforsen** [comment]
Sv. -radiobearbetningar https://finto.fi/slm/fi/page/s1531
-bearbetningar till skådespel HT dramatiseringar (skådespel)

Jfr även MDO https://finto.fi/mts/sv/search?clang=sv&anylang=on&q=*dramatisoi*&vocabs=
I ALLFO dramatisointi
https://id.kb.se/find?q=dramatiseringar
https://svenska.se/tre/?sok=dramatisering&pz=8
https://tieteentermipankki.fi/wiki/Nimitys:dramatisering
https://www.kielitoimistonsanakirja.fi/#/n%C3%A4ytelm%C3%A4sovitus?searchMode=all
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_18ea9998c1b4d3242d269baa4ff5d853&list_id=1&keyword=n%C3%A4ytelm%C3%A4sovitus&word=n%C3%A4ytelm%C3%A4sovitus
