### ISSUE TITLE
kauhupelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3172]
#### Ehdotettu termi suomeksi

kauhupelit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)

**Luontipäivämäärä:** 15.06.2011

**Muokkauspäivämäärä:** 15.06.2011

**Voyager-id:** 180120

**Termiehdotus Fintossa:** [kauhupelit](http://finto.fi/yse/fi/page/Y380120)

**Comment by mirmaid** [comment]
BTJ: Tästä on paljon esimerkkejä ja olisin monta kertaa tarvinnut genrenä.

**Comment by mariaforsen** [comment]
Sv. skräckspel
