### ISSUE TITLE
australianenglanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#32]
#### Ehdotettu termi suomeksi

australianenglanti
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[85 Kielitiede](http://www.yso.fi/onto/ysa/ryhma_85)

**Luontipäivämäärä:** 23.06.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 113859

**Termiehdotus Fintossa:** [australianenglanti](http://finto.fi/yse/fi/page/Y313859)

**Comment by henriyli** [comment]
YSAan 23.6.1998, http://www.yso.fi/onto/ysa/Y172847
