### ISSUE TITLE
parkkihallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3249]
#### Ehdotettu termi suomeksi

parkkihallit
#### Ehdotetut ohjaustermit

paikoitushallit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)

**Luontipäivämäärä:** 15.11.2011

**Muokkauspäivämäärä:** 15.11.2011

**Voyager-id:** 182571

**Termiehdotus Fintossa:** [parkkihallit](http://finto.fi/yse/fi/page/Y382571)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/10341

**Comment by mariaforsen** [comment]
Kannatan uutena terminä pysäköinti/parkki/paikoitushallit=parkeringshallar, mutta myös pysäköintitilat-termin poistamista/yhdistämistä. 

Sanastossa olisi sitten:
pysäköintialueet
pysäköintipaikat
pysäköintitalot
pysäköintiluolat
pysäköintihallit
