### ISSUE TITLE
prokura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#326]
#### Ehdotettu termi suomeksi

prokura
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 05.10.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114329

**Termiehdotus Fintossa:** [prokura](http://finto.fi/yse/fi/page/Y314329)

**Comment by jtuohini** [comment]
Tarvetta tälle olisi edelleen. Lisäksi KT-muodoksi _nimenkirjoitusoikeus_ ja toiseksi aihealueryhmäksi _69 (Oikeus. Lainsäädäntö)_.

**Comment by ilona-x** [comment]
EKS: valtuutus KT prokura

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Prokura

**Comment by LeKorsu** [comment]
Kannattaisiko ottaa eks-muoto?

**Comment by ilona-x** [comment]
valtuutus on YSAssa http://www.yso.fi/onto/ysa/Y104797

**Comment by YSA-kokous** [comment]
prokura, nimenkirjoitusoikeus KÄ valtuutus
