### ISSUE TITLE
rakennusterveys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3262]
#### Ehdotettu termi suomeksi

rakennusterveys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/ysa/ryhma_37)
#### Lähde

Julkaisu: Rakennusterveyskoulutus ammattikorkeakouluissa

**Luontipäivämäärä:** 15.11.2011

**Muokkauspäivämäärä:** 15.11.2011

**Voyager-id:** 182591

**Termiehdotus Fintossa:** [rakennusterveys](http://finto.fi/yse/fi/page/Y382591)

**Comment by frosterus** [comment]
Sai kannatusta Finto-postin kautta.

**Comment by mirmaid** [comment]
TSR-ontologiassa

YSAssa on _asumisterveys_ (otettu sanastoon 2015, ei käytetty Melindassa. Useimmiten varmaankin _sisäilma, rakentaminen_.)

**Comment by mirmaid** [comment]
Rakennusterveydellä  tarkoitetaan  rakennuksen  sisäilmaston,  sisä-  tai  ulkopintojen, rakenteiden ja järjestelmien sellaista tilaa, jossa niistä ei aiheudu rakennuksen käyttäjille  terveyshaittoja  tai  niiden  syntymisen  riskiä.  Rakennusterveys  sisältää  asuntojen ja  muiden  oleskelutilojen  sekä  työpaikkojen  terveydellisten  ja  turvallisten  olojen varmentamisen  terveydensuojelu-,  työturvallisuus-  ja  rakennuslainsäädännön  mukaisesti. http://epublications.uef.fi/pub/urn_isbn_978-952-61-0326-6/

**Comment by Elmukelmu** [comment]
Asumisterveys ja rakennusterveys näyttää menevän päällekkäin. esim. Valviran sivuilla sanotaan: Asumisterveydellä tarkoitetaan asuntojen, päivähoito- ja koulutilojen, oppilaitosten, lastenkotien, vanhainkotien ja muiden vastaavien julkisten tilojen terveydellisiä olosuhteita. Meillä Aleksissa asumisterveyttä käytetty 79 viitteessä. Kumpi sitten ois parempi vai onko näissä näkökulmaero?

**Comment by mirmaid** [comment]
KÄ asumisterveys (YSA-kokous 7.3.2017).
