### ISSUE TITLE
sekarotuiset koirat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3283]
#### Ehdotettu termi suomeksi

sekarotuiset koirat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[17 Eläintiede](http://www.yso.fi/onto/ysa/ryhma_17)
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/ysa/ryhma_22)

**Luontipäivämäärä:** 15.11.2011

**Muokkauspäivämäärä:** 15.11.2011

**Voyager-id:** 182614

**Termiehdotus Fintossa:** [sekarotuiset koirat](http://finto.fi/yse/fi/page/Y382614)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
