### ISSUE TITLE
sivistymättömyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3287]
#### Ehdotettu termi suomeksi

sivistymättömyys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 15.11.2011

**Muokkauspäivämäärä:** 15.11.2011

**Voyager-id:** 182620

**Termiehdotus Fintossa:** [sivistymättömyys](http://finto.fi/yse/fi/page/Y382620)

**Comment by mirmaid** [comment]
Hyväksytty https://github.com/Finto-ehdotus/YSE/issues/5055
