### ISSUE TITLE
televisioteollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3302]
#### Ehdotettu termi suomeksi

televisioteollisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)

**Luontipäivämäärä:** 16.11.2011

**Muokkauspäivämäärä:** 16.11.2011

**Voyager-id:** 182648

**Termiehdotus Fintossa:** [televisioteollisuus](http://finto.fi/yse/fi/page/Y382648)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2171
