### ISSUE TITLE
puhelinvaihteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#331]
#### Ehdotettu termi suomeksi

puhelinvaihteet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)

**Luontipäivämäärä:** 06.10.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114337

**Termiehdotus Fintossa:** [puhelinvaihteet](http://finto.fi/yse/fi/page/Y314337)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7651
