### ISSUE TITLE
yhteiskehittäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3334]
#### Ehdotettu termi suomeksi

yhteiskehittäminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
#### Lähde

Julkaisu: InnoSchool

**Luontipäivämäärä:** 16.11.2011

**Muokkauspäivämäärä:** 20.12.2012, 13.8.2013, 16.11.2011, 27.4.2012, 13.08.2013

**Voyager-id:** 182686

**Termiehdotus Fintossa:** [yhteiskehittäminen](http://finto.fi/yse/fi/page/Y382686)

**Comment by satuniininen** [comment]
Tätä tarvittaisiin teoksessa _Arvonluonnin muutoksen aakkoset: arvot, arki ja arvostus._ 978-951-38-7448-3

Googlessa 9 920 kertaa, Melindassa 0.

**Comment by mirmaid** [comment]
https://www.utu.fi/fi/yksikot/tse/ajankohtaista/uutiset/Sivut/Yhteiskehitt%C3%A4minen_kaikki-siit%C3%A4-puhuu,-mutta-mit%C3%A4-se-on-ja-miten-siin%C3%A4-onnistua.aspx

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 14.9.2016)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin termiä yhteiskehittely, nämä ilm,eisesti ovat sama asia.
ISBN 978-952-216-736-1 Co-creation of public service innovation
https://fi.wikipedia.org/wiki/Yhteiskehittely

**Comment by mirmaid** [comment]
Melindassa _yhteiskehittely_ 2 kertaa, _yhteiskehittäminen_ 4 kertaa. 

Yhdistelmää _tuotekehitys & joukkoistaminen_ 17 kertaa, _tuotekehitys & yhteistyö_ 294 kertaa.

Sanastossa on _käyttäjälähtöisyys, käyttäjäkeskeinen suunnittelu_.

**Comment by ilona-x** [comment]
YSOssa on yhteissuunnittelu http://www.yso.fi/onto/yso/p8340
"Yhteissuunnittelu, yhteiskehittäminen (co-design, co-creation, participatory design) tarkoittaa ohjattua yhdessä suunnittelua ja tekemistä."
Lähde: https://codesign2020.wordpress.com/2018/02/16/tulevaisuustietoinen-yhteissuunnittelu/

**Comment by mariaforsen** [comment]
Sv. gemensam utveckling, samutveckling

**Comment by YSA-kokous** [comment]
Yhteiskehittäminen jätetään termiehdotukseksi.
Yhteissuunnittelun määritelmää ja hierarkiaa muutettava.

**Comment by Kivmer** [comment]
Voisiko tätä termiä vielä harkita uudestaan. Yhteiskehittämis-termiä on otettu käyttöön ja määritelty esim. julkisten  hyvinvointipalvelujen kehittämisessä (sote-uudistus). Käsitteellä on ehkä vähän eri merkitys kuin yhteissuunnittelu. Olisi ainakin tärkeää, että yhteiskehittäminen olisi hakuterminä ja ohjaisi yhteissuunnitteluun. Esim. tässä yhteiskehittämisen oppaassa on määritelty käsitettä: 
https://urn.fi/URN:ISBN:978-952-331-876-2

**Comment by ilona-x** [comment]
Tämän julkaisun kuvailussa olisi voinut käyttää: "Yhteiskehittämällä ratkaisuja sote-palveluhin - kansalaiset ja palvelunkäyttäjät mukaan kehittämiseen" https://urn.fi/URN:ISBN:978-952-493-392-6

**Comment by mirmaid** [comment]
Wikipediassa co-creation = samskapande. On kyllä sikäli aika päällekkäinen yhteissuunnittelun kanssa, että tuskin toteutusta on kuitenkaan kovin usein tehty yhdessä. Mutta ehkäpä suunnittelu mielletään tapahtuvaksi prosessin alussa ja jos jotain tehdään yhdessä myöhemmässä vaiheessa (jatkokehittelyä), sitä ei enää mielletä suunnitteluksi.

**Comment by Kivmer** [comment]
Yhteiskehittäminen on terminä tosiaankin laajempi kuin yhteissuunnittelu. Yhteiskehittämisessä tuote tai palvelu ymmärretään siten, että asiakas on mukana koko kehittämisprosessin aikana, suunnittelussa, kehittämisessä, toteuttamisessa ja arvioinnissa. Keskeistä tässä on asiakkaan osallisuus, vaikuttaminen omiin palveluihinsa.
Finnassa yhteiskehittäminen-sanalla löytyy jo aika paljon samoin kuin netistä. Varsinkin ot-töiden nimissä näkyy - eli tulevaisuuden asiantuntijoiden käyttämä termi :)

**Comment by YSO-kokous** [comment]
**Päätös**

_Yhteiskehittäminen_ ohjaustermiksi _yhteissuunnitteluun_.
