### ISSUE TITLE
komediasarjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3351]
#### Ehdotettu termi suomeksi

komediasarjat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 16.11.2011

**Muokkauspäivämäärä:** 3.10.2013, 03.10.2013

**Voyager-id:** 182705

**Termiehdotus Fintossa:** [komediasarjat](http://finto.fi/yse/fi/page/Y382705)

**Comment by henriyli** [comment]
YSAan 8.1.2014 : http://www.yso.fi/onto/ysa/Y196543
