### ISSUE TITLE
minäpystyvyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3378]
#### Ehdotettu termi suomeksi

minäpystyvyys
#### Ehdotetut ohjaustermit

pystyvyysusko, pystyvyysuskomukset, minäpystyvyysuskomukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)
#### Käsitteen määritelmä

Tarkoittaa ihmisen uskoa omasta kyvykkyydestään   TAI  Tarkoittaa ihmisen arviota siitä, kuinka kykenevä hän on suoriutumaan tietyistä tehtävistä

**Luontipäivämäärä:** 14.03.2012

**Muokkauspäivämäärä:** 20.12.2012, 4.11.2013, 27.3.2014, 27.03.2014

**Voyager-id:** 184991

**Termiehdotus Fintossa:** [minäpystyvyys](http://finto.fi/yse/fi/page/Y384991)

**Comment by HeidiRonkainen** [comment]
joko otetaan?
https://www.kansanopistot.fi/wp-content/uploads/2020/04/SKY_Oppimisen-pulmat_160519_web_korjattu.pdf

**Comment by ilona-x** [comment]
Self-efficacy http://id.loc.gov/authorities/subjects/sh93006407 (HUOM. tämä linkattu nyt YSOssa omatoimisuus-käsitteeseen)
https://en.wikipedia.org/wiki/Self-efficacy

Voisiko olla pelkkä **pystyvyys** tai **pystyvyys (sosiaalipsykologia)**? https://www.avoin.helsinki.fi/oppimateriaalit/sosiaalipsykologia/bandura.htm

Joitain tuloksia löytyy myös termeillä pystyvyysusko & pystyvyysuskomukset

**Comment by tpalonen** [comment]
Olen miettinyt "Minäpystyvyys YSOon"-t-paidan teettämistä. Sitä voisi aina YSO-kokouksissa pitää.

**Comment by mirmaid** [comment]
^ Kovaa peliä

**Comment by FinMeSHienPaimentaja** [comment]
Miten "itseluottamus" suhteutuu "minäpystyvyyteen"?

**Comment by mirmaid** [comment]
^ Kuten Joe Biden suhteutuu Donald Trumpiin? :upside_down_face:

**Comment by mirmaid** [comment]
_Pystyvyys_ kuulostaa ensi hätään ihan hyvältä. Tuota _pystyvyysuskomukset_ myös joskus mietittiin mahdollisena.

**Comment by mariaforsen** [comment]
Pystyvyys vaikuttaa vaikealta kääntää, tarvittaiisin siinä tapauksessa ainakin määritelmä ja tieto mitä laitetaan englanniksi jne. 

Kielitoimisto:  "vrt. pystyvä. Veitsen pystyvyys. Osoittaa pystyvyytensä."

MOT antaa:  
1(terävyys) skärpa [-n,-,-], vasshet [-en,-,-]
2 (kyky) förmåga [-an,-or,-orna]
3 (kykenevyys) kapacitet [-en,-er,-erna]
4 (taitavuus) skicklighet [-en,-,-], kunnande [-t,-,-]

..mutta synonymeja näille on jo YSOssa, eli förmåga=kyvykkyys, kapacitet=kapasiteetti, kunande=osaaminen jne. En siis kannata lisää synonyymeja erillisinä termeinä.

**Comment by ilona-x** [comment]
Eli tarve siis Albert Banduran vuonna 1977 esittelemälle self-efficacy -käsitteelle, joka on käännetty suomeksi vaihtelevasti minäpystyvyys, pystyvyys, pystyvyysusko.

https://www.psykologiguiden.se/psykologilexikon/?Lookup=self-efficacy

**Comment by ilona-x** [comment]
tämän väitöksen kuvailuun olisi voinut käyttää: Mastering learning situations: Self-regulation, executive functions and selfregulatory efficacy among elementary school pupils http://urn.fi/URN:ISBN:978-951-39-7928-7

**Comment by ilona-x** [comment]
tässä vielä pari käännösvaihtoehtoa lisää: 

> "Minäpystyvyys (self-efficacy) on osa Albert Banduran (1977) kehittämää sosiokognitiivista teoriaa. Suomenkielisessä kirjallisuudessa self-efficacy käännetään kolmella eri tavalla: **minäpystyvyys, itsepystyvyys ja itsetehokkuus.**" 

Lähde: https://unlimited.hamk.fi/ammatillinen-osaaminen-ja-opetus/kansanopistot-ja-minapystyvyys/#.YEDpoOfkuUk

**Comment by mariaforsen** [comment]
Sv. självförmåga ET egenförmåga

**Comment by ilona-x** [comment]
TSR: pystyvyys http://www.yso.fi/onto/tsr/p6899
