### ISSUE TITLE
tietoaineisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3396]
#### Ehdotettu termi suomeksi

tietoaineisto
#### Ehdotetut ohjaustermit

tietoaineistot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[56 Tiede. Tutkimus](http://www.yso.fi/onto/ysa/ryhma_56)
#### Lähde

Julkaisu: Tutkimuksen tietoaineistot

**Luontipäivämäärä:** 15.03.2012

**Muokkauspäivämäärä:** 15.5.2012, 15.05.2012

**Voyager-id:** 185025

**Termiehdotus Fintossa:** [tietoaineisto](http://finto.fi/yse/fi/page/Y385025)

**Comment by jtuohini** [comment]
Vastaava ehdotus SLM:n puolella: https://github.com/Finto-ehdotus/YSE/issues/9470

**Comment by jarmosaarikko** [comment]
eng:  KÄ **data sets**  KT datasets, documentation, raw data  sets  YK aineistot / materials (role) RT data
- lähde MOT Pro Englanti, [Termipankki](https://termipankki.fi/tepa/fi/haku/tietoaineisto)
- WD: data set https://www.wikidata.org/wiki/Q1172284
- LCSH: Data sets http://id.loc.gov/authorities/subjects/sh2018002256

**Comment by jtuohini** [comment]
Eli sitten pitäisi ehkä olla meikäläisittäin **_tietoteokset_** = **_informativa verk_** = **_informational works_**, jonka LCGFT-vastine on [**Informational works**](http://id.loc.gov/authorities/genreForms/gf2014026113).

Tutkimusdata ei siis ollut se, mitä YSO/SLM-ehdotuksella haettiin, vaan tuo LCGFT-vastaavuus sanaston hierarkian kattotermiksi.

**Comment by mirmaid** [comment]
https://melinda.kansalliskirjasto.fi/byid/005904081

Aihepiiriä sivuttiin myös edellisessä kokouksessa: https://github.com/Finto-ehdotus/YSE/issues/8809.

**Comment by YSO-kokous** [comment]
Käsitellään SLM  ehdotuksena.

**Comment by mariaforsen** [comment]
Täytyy huomioida että tällä termillä voi olla kaksi merkitystä: "tietoa sisältävä aineisto; tiettyä tarkoitusta varten kerättyjen dokumenttien muodostama kokonaisuus" /Kielitoimiston sk. Ja käännös riippuu merkityksestä (ihan eri termi ruotsiksi)

Ks. myös https://termipankki.fi/tepa/fi/haku/tietoaineisto Eli jos todella halutaan suomeksi termi joka vastaa LCSH:n informational works, niin onko tietoaineistot todella paras vaihtoehto?

**Comment by jtuohini** [comment]
Eikö ero syntyisi sitten välille _**tietoteokset**_ ~ _**tietoaineistot**_, joista edelliset olisivat "tietoa sisältävää aineistoa" ja jälkimmäiset "tiettyä tarkoitusta varten kerättyjen dokumenttien muodostamat kokonaisuudet".
