### ISSUE TITLE
hyötypelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3415]
#### Ehdotettu termi suomeksi

hyötypelit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)

**Luontipäivämäärä:** 25.04.2012

**Muokkauspäivämäärä:** 25.04.2012

**Voyager-id:** 185733

**Termiehdotus Fintossa:** [hyötypelit](http://finto.fi/yse/fi/page/Y385733)

**Comment by satuniininen** [comment]
Käsite olisi tarpeen myös teoksessa Serious Gaming Research Lab: opas hyötypeleihin ja palvelumallin kehittämiseen

Tällä hetkellä Melindassa 2 osumaa.

**Comment by mirmaid** [comment]
Ks. myös issue https://github.com/Finto-ehdotus/YSE/issues/4982

**Comment by mirmaid** [comment]
Toisinaan hyöty tarjotaan pelaajalle (oppimispelit, liikuntapelit), mutta esim. mainospelien tapauksessa hyötyjä on mainostaja...

"Voidaan  sanoa,  että  liikehdintä  hyötypelien  parissa  alkoi  vuonna  2002  kun  Yhdysvaltain  armeija  
lanseerasi America’s Army -pelin sotilaiden koulutuskäyttöön.  Samana  vuonna  perustettiin  Serious  
Games   Iniative   Washingtonissa,   Yhdysvalloissa  ja   organisaatio   vaikutti   voimakkaasti   käsitteen   
”serious  games”  yleistymiseen.  (America’s  Army  2016;  Gudmundsen  2006.)  ”Serious  games”  käsi-
tettä vastaa suomenkielessä termi hyötypelit.

Hyötypeleissä peliteknologiaa hyödynnetään ja käytetään muussa kuin viihteellisessä tarkoituksessa (Miller, Chang, Wang, Beier & Klisch 2011). Hyötypelit voivat olla digitaalisia pelejä, simulaatioita, virtuaaliympäristöjä  tai  todellisen  ja  virtuaaliympäristön  yhdistelmiä,  jotka interaktiivisten kokemusten, kohtaamisten, tarinan tai pelimekanismien avulla mahdollistavat tiedottamisen,  vaikuttamisen  ja  merkitysten  luomisen  erilaisten  aktiviteettien  yhteydessä  (Marsh  2011)." http://www.kuopioinnovation.fi/uploads/aineistopankki/muut_fi/SGRL_Opas.pdf
