### ISSUE TITLE
kansainväliset vaikutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3444]
#### Ehdotettu termi suomeksi

kansainväliset vaikutukset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)

**Luontipäivämäärä:** 25.04.2012

**Muokkauspäivämäärä:** 25.04.2012

**Voyager-id:** 185771

**Termiehdotus Fintossa:** [kansainväliset vaikutukset](http://finto.fi/yse/fi/page/Y385771)

**Comment by henriyli** [comment]
Suljetaan tupla ehdotuksesta #1274
