### ISSUE TITLE
lihankorvikkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3467]
#### Ehdotettu termi suomeksi

lihankorvikkeet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/ysa/ryhma_24)

**Luontipäivämäärä:** 25.04.2012

**Muokkauspäivämäärä:** 25.04.2012

**Voyager-id:** 185797

**Termiehdotus Fintossa:** [lihankorvikkeet](http://finto.fi/yse/fi/page/Y385797)

**Comment by Hanneletar** [comment]
Nowadays, in 2022 lihankorvikkeet is a term that is no longer used. In 2022 as well as from 2023 onwards the correct term is kasviproteiinit: plantbased proteins. Nowadys also environmental benefits (including health related benefots, etc) are better understood when talking about plantbased proteins. 

Thank you in advance & kind regads,
Ms. Hannele Ollilainen

**Comment by mariaforsen** [comment]
Sanastossa on hyväksyttynä terminä kasviproteiinit: http://www.yso.fi/onto/yso/p27261
Lihankorvike-sana käytetään mielestäni enemmän ruoanlaiton yhteydessä, kuvaamaan että se vastaa jotain perinteistä lihan osuuttaa jossain ruoassa (esim. jauheliha makaronilaatikossa tai lasagnessa korvataan herneproteiini-, papu- tms. jauhelihalta näyttävälllä ainesosalla). Kasviproteiinilla voi varmaan olla mikä tahansa "rooli" jossain tietyssä ruokalajissa. Lihankorvike-sana voi toki kuulostaa hieman oudolta, varsinkin silloin kun pitäisi puhua nimenomaan kasviproteiineistä, joten olisiko lihankorvikkeet hyvä korvattuna terminä sille?
https://vegefrendit.fi/mika-on-lihankorvike/

**Comment by annamarj** [comment]
Kannattaisin "lihankorvikkeet KÄYTÄ kasvisproteiinit"

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _lihankorvikkeet_ ohjaustermiksi _kasviproteiinivalmisteille_.
