### ISSUE TITLE
kuulevat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3471]
#### Ehdotettu termi suomeksi

kuulevat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 26.04.2012

**Muokkauspäivämäärä:** 26.04.2012

**Voyager-id:** 185804

**Termiehdotus Fintossa:** [kuulevat](http://finto.fi/yse/fi/page/Y385804)

**Comment by ilona-x** [comment]
tälle termille olisi ollut tarve väitöskirjan 'Two languages, two modalities : a special type of early bilingual language acquisition in hearing children of deaf parents" kuvailussa.

Melindassa käytetty seuraavia: 
kuulevat x 6 
kuulevat lapset x 12
kuulevat sisarukset x 2
kuulevat vanhemmat x 4
kuulevat lapset - kuurot vanhemmat x 3 
kuurot vanhemmat - kuulevat lapset x 31

http://www.coda.fi/yhdistys/

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Hyväksytty muodossa kuulevat (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
hörande personer
ET hörande
ET hörande individer
