### ISSUE TITLE
alkuperäisväestö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3515]
#### Ehdotettu termi suomeksi

alkuperäisväestö
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[61 Väestötiede. Demografia](http://www.yso.fi/onto/ysa/ryhma_61)

**Luontipäivämäärä:** 08.06.2012

**Muokkauspäivämäärä:** 08.06.2012

**Voyager-id:** 186454

**Termiehdotus Fintossa:** [alkuperäisväestö](http://finto.fi/yse/fi/page/Y386454)

**Comment by vthuhtala** [comment]
Käytetty 54 kertaa Helkassa. YSAan, kiitos!

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:alkuper%C3%A4iskansat
http://www.tsk.fi/tepa/fi/haku/alkuper%C3%A4isv%C3%A4est%C3%B6

YSO alkuperäiskansat http://www.yso.fi/onto/yso/p5737
KAUNO alkuperäisväestö http://www.yso.fi/onto/kauno/p6233

**Comment by mirmaid** [comment]
Sanastossa on myös _kantaväestö_, Kielitoimiston sanakirjan mukaan _jnk seudun alkuperäinen väestö_.

**Comment by mariaforsen** [comment]
Kantaväestö=ortsbor ALLFOssa, eli se ei käy tähän merkitykseen, mutta sen sijaan alkuperäiskansat=ursprungsbefolkningar on kyllä synonymi ehdotetun merkityksen kanssa. Onko tässä syytä muutoksiin? Ei ainakaan uusia päätermejä.

**Comment by YSA-kokous** [comment]
KÄ alkuperäiskansat, kantaväestö

**Comment by mariaforsen** [comment]
Sv. urbefolkningar (alkuperäiskansat) > ? 
ortsbor (kantaväestö) > ?
SAO: Ursprungsbefolkningar ET urbefolkningar, urfolk, urinvånare, ursprungsbefolkning, ursprungsfolk
