### ISSUE TITLE
kansalaisraadit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3527]
#### Ehdotettu termi suomeksi

kansalaisraadit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)

**Luontipäivämäärä:** 08.06.2012

**Muokkauspäivämäärä:** 8.6.2012, 27.10.2015

**Voyager-id:** 186467

**Termiehdotus Fintossa:** [kansalaisraadit](http://finto.fi/yse/fi/page/Y386467)

**Comment by mirmaid** [comment]
Ehdotettu uudelleen 30.11.2016.
"Käsite liitty deliberatiiviseen demokratiaan eli kansalaisten osallistumiseen lainsäädännöllisesten tai vaikkapa kotiseutua koskevien päätösten valmisteluun. Ks. esim. http://www.deliberaatio.org/~delibero/wordpress/?tag=helsinki"

**Comment by mirmaid** [comment]
Käytetty myös esim. Euroviisujen yhteydessä. http://yle.fi/aihe/artikkeli/2015/02/06/hae-umk15-finaalin-kansalaisraatiin

**Comment by ilona-x** [comment]
Kansalaisraatikäsikirja : opas kansalaisraadin järjestäjälle:
https://setlementti-fi-bin.directo.fi/@Bin/dd25ea8f0371e6fb7a6a3d7c5c00a569/1488527715/application/pdf/770707/Kansalaisraati_nettiin.pdf

**Comment by mariaforsen** [comment]
Sv. medborgarråd, medborgarpaneler

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
medborgarråd 
ET medborgarpaneler
