### ISSUE TITLE
kyberpuolustus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3536]
#### Ehdotettu termi suomeksi

kyberpuolustus
#### Ehdotetut ohjaustermit

tietoverkkopuolustus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/ysa/ryhma_67)

**Luontipäivämäärä:** 08.06.2012

**Muokkauspäivämäärä:** 8.6.2012, 08.06.2012

**Voyager-id:** 186477

**Termiehdotus Fintossa:** [kyberpuolustus](http://finto.fi/yse/fi/page/Y386477)

**Comment by AnuAlatera** [comment]
Kyberpuolustus on ollut SOTO terminä (https://finto.fi/soto/fi/page/p2075) ja ehdottaisimme sen lisäämistä YSOon siten, että laajempi termi olisi kyberturvallisuus (http://www.yso.fi/onto/yso/p26189). Englanninkielinen termi: cyber defence.

EU:n kyberpuolustusstrategia (https://eda.europa.eu/news-and-events/news/2022/11/10/cyber-defence-eu-boosts-action-against-cyber-threats) määrittelee, että kyberpuolustusstrategian tavoitteena on "prevent, detect, deter and defend against cyberattacks". Suomessa puolestaan Puolustusministeriön "Kyberpuolustuksen kehittämisen strategiset linjaukset" (http://urn.fi/URN:ISBN:978-951-663-069-7)  määrittelee että "Sotilaallinen kyberpuolustuskyky muodostuu tiedustelun, vaikuttamisen ja 
suojautumisen suorituskyvyistä". 

Esimerkki aineistosta, jonka kuvailuun käsitettä tarvittaisiin: #kyberpuolustus : kyberkäsikirja Puolustusvoimien henkilöstölle http://www.urn.fi/URN:ISBN:978-951-25-3120-2

**Comment by mirmaid** [comment]
Melindassa 3 kertaa soto-terminä, 12 kertaa vapaana avainsanana.

**Comment by mariaforsen** [comment]
Sv. cyberförsvar
https://termipankki.fi/tepa/fi/haku/kyberpuolustus
https://www.forsvarsmakten.se/sv/var-verksamhet/det-har-gor-forsvarsmakten/cyberforsvar/

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
