### ISSUE TITLE
sosiaalinen elämä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3594]
#### Ehdotettu termi suomeksi

sosiaalinen elämä
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)

**Luontipäivämäärä:** 08.06.2012

**Muokkauspäivämäärä:** 08.06.2012

**Voyager-id:** 186546

**Termiehdotus Fintossa:** [sosiaalinen elämä](http://finto.fi/yse/fi/page/Y386546)

**Comment by mirmaid** [comment]
Ehdotettu muutosta _seuraelämä_ > sosiaalinen elämä.

**Comment by krinay** [comment]
_Sosiaalinen elämä_ lienee merkitykseltään laveampi kuin _seuraelämä_, jonka saattaa mieltää jotenkin julkisemmaksi ja järjestyneemmäksi kanssakäymisen muodoksi (Kielitoimiston sanakirja seuraelämästä: "ihmisten us. julkisesta kanssakäymisestä t. seurustelusta vars. huvi-, kulttuuri- yms. tilaisuuksissa"). 

Termi _sosiaalinen elämä_ sopisi ehkä monipuolisemman aineiston kuvailuun eli sille olisi enemmän käyttöä.

**Comment by YSO-kokous** [comment]
Muutetaan seuraelämän käytettäväksi muodoksi sosiaalinen elämä, ohjaustermiksi seuraelämä. Kokous kannatti muutosta varsin yksimielisesti.
