### ISSUE TITLE
sivupersoonat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#360]
#### Ehdotettu termi suomeksi

sivupersoonat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)
#### Lähde

Lähde: Kaunokki

**Luontipäivämäärä:** 07.10.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114385

**Termiehdotus Fintossa:** [sivupersoonat](http://finto.fi/yse/fi/page/Y314385)

**Comment by mariaforsen** [comment]
Sv. multipla personligheter
