### ISSUE TITLE
tuomiopäivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3626]
#### Ehdotettu termi suomeksi

tuomiopäivä
#### Ehdotetut ohjaustermit

viimeinen tuomio
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)

**Luontipäivämäärä:** 08.06.2012

**Muokkauspäivämäärä:** 08.06.2012

**Voyager-id:** 186581

**Termiehdotus Fintossa:** [tuomiopäivä](http://finto.fi/yse/fi/page/Y386581)

**Comment by jtuohini** [comment]
Tarvetta tälle on edelleen, mieluummin muodossa **_viimeinen tuomio_**! Teologisen tiedekunnan kirjaston asiasanastojen lopettamisen yhteydessä pitäisi saada YSO:on. Yms.

**Comment by jtuohini** [comment]
Wikidata-siltaus: https://www.wikidata.org/wiki/Q1821239

KT-muodoksi myös ainakin _tuomionpäivä_.

**Comment by mariaforsen** [comment]
Myös SAOssa: https://id.kb.se/term/sao/Yttersta%20domen
Kannatan!

**Comment by mirmaid** [comment]
Eli nämä ohjaustermeiksi käsitteelle _viimeinen tuomio_, jos se hyväksytään.

**Comment by AuHo22** [comment]
https://id.loc.gov/authorities/subjects/sh85070918.html
Judgment Day

**Comment by YSO-kokous** [comment]
Hyväksytään viimeinen tuomio KT tuomiopäivä

**Comment by mariaforsen** [comment]
Sv. yttersta domen HT domedagen, domens dag, yttersta dagen
