### ISSUE TITLE
ulkoliikunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3639]
#### Ehdotettu termi suomeksi

ulkoliikunta
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[97 Liikunta. Urheilu](http://www.yso.fi/onto/ysa/ryhma_97)
#### Lähde

Julkaisu: Utomhusträning

**Luontipäivämäärä:** 08.06.2012

**Muokkauspäivämäärä:** 08.06.2012

**Voyager-id:** 186597

**Termiehdotus Fintossa:** [ulkoliikunta](http://finto.fi/yse/fi/page/Y386597)

**Comment by henriyli** [comment]
YSAan 7.12.2012 : http://www.yso.fi/onto/ysa/Y189807
