### ISSUE TITLE
vaha-animaatiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3675]
#### Ehdotettu termi suomeksi

vaha-animaatiot
#### Ehdotetut ohjaustermit

vaha-animaatioelokuvat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)

**Luontipäivämäärä:** 14.12.2012

**Muokkauspäivämäärä:** 14.12.2012

**Voyager-id:** 190089

**Termiehdotus Fintossa:** [vaha-animaatiot](http://finto.fi/yse/fi/page/Y390089)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
