### ISSUE TITLE
agape

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3689]
#### Ehdotettu termi suomeksi

agape
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[02 Filosofia](http://www.yso.fi/onto/ysa/ryhma_02)
[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012, 20.12.2012

**Voyager-id:** 190238

**Termiehdotus Fintossa:** [agape](http://finto.fi/yse/fi/page/Y390238)

**Comment by jtuohini** [comment]
Kuuluisi myös ryhmään 53. LCSH-vastine "Agape" (LT "Love--Religious aspects--Christianity" ja "Sacred meals")

**Comment by mirmaid** [comment]
Agape tarkoittaa jumalallista rakkautta, Jumalan vaikuttamaa rakkautta. Se on kristinuskon oppien mukaan rakkauden korkein muoto. 

Eikö tämä oikeastaan kuulu pelkästään ryhmään 53?

**Comment by mariaforsen** [comment]
Ruotsiksi tämä on ryhmä 02 ja 53.

**Comment by mirmaid** [comment]
02 ja 53

**Comment by mirmaid** [comment]
Agape on kreikkaa ja tarkoittaa epäitsekästä rakkautta. Jumalan rakkaus syntistä ihmistä kohtaan on agape-rakkautta. Tällainen ajattelu pohjautuu luterilaiseen ristin teologiaan. Agape-rakkauden vastakohtana pidetään omaa etua tai mielihyvää etsivää eros-rakkautta. Agapella tarkoitetaan myös ensimmäisten kristittyjen rakkauden ateriaa eli ehtoollista. http://evl.fi/sanasto/-/glossary/word/Agape

**Comment by mirmaid** [comment]
Ei Teologian asiasanastossa.

Käytetty Melindassa joitakin kertoja LCSH-terminä.

Wikipediassa agape (kristinusko) https://fi.wikipedia.org/wiki/Agape_%28kristinusko%29

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
agape
