### ISSUE TITLE
arvioijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3702]
#### Ehdotettu termi suomeksi

arvioijat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012

**Voyager-id:** 190272

**Termiehdotus Fintossa:** [arvioijat](http://finto.fi/yse/fi/page/Y390272)

**Comment by ilona-x** [comment]
tälle termille olisi ollut käyttöä väitöskirjan "[Rimaa hipoen selviää tilanteesta : yleisten kielitutkintojen suomen kielen arvioijien käsityksiä kielitaidon arvioinnista ja suullisesta kielitaidosta](http://urn.fi/URN:ISBN:978-951-39-9005-3)" kuvailussa

**Comment by mariaforsen** [comment]
Sv. bedömare HT utvärderare, värderingsmän
https://termipankki.fi/tepa/fi/haku/arvioija
https://www.oph.fi/sv/utbildning-och-examina/att-visa-och-bedoma-kunnande

**Comment by mirmaid** [comment]
Saattaa kyllä mennä ristiin _arvostelijoiden_ kanssa.

**Comment by ilona-x** [comment]
Varmasti menee ristiin, kun nyt tuon väitöskirjan kuvailussa oli käytetty asiasanaa arvostelijat, mikä on kielivastineiden osalta väärin, eikä kyllä suomeksikaan tunnu sopivalta https://melinda.kansalliskirjasto.fi/byid/018145144

**Comment by mariaforsen** [comment]
Olisi tärkeä saada myös monikielisyyden kannalta, yllä linkatussa Melinda-tietueissa on nyt tosiaan virhe muiden kielten osalta. 

Arvostelijat=recensenter viittaa kakkosmerkitykseen: https://www.kielitoimistonsanakirja.fi/#/arvostelija?searchMode=all OT on kyllä suomeksikin kriitikot, että sen termin ei pitäisi varmaan liittyä tähän arvioijat-termiin?

**Comment by mirmaid** [comment]
_Arvostelu_ (bedömning) kattaa nyt YSOssa (hierarkian mukaan) kritiikin ja oppilasarvioinnin. 

Pitäisikö olla jokin ohjaustermi, arvostelijat (kokeet/tutkinnot/opintosuoritukset/??) KÄ arvioijat?

**Comment by mirmaid** [comment]
Tällainenkin: https://tieteentermipankki.fi/wiki/Nimitys:arvioija

Huom. myös tämä issue https://github.com/Finto-ehdotus/YSE/issues/10536

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _arvioijat_. Muutetaan _arvostelijat_ KÄYTÄ _kriitikot_.

**Comment by tpalonen** [comment]
Ks. Suomen arviointiyhdistyksen sivut: https://www.sayfes.fi/
Ks. Suomen arvostelijain liitto: https://fi.wikipedia.org/wiki/Suomen_arvostelijain_liitto
