### ISSUE TITLE
energiahoidot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3710]
#### Ehdotettu termi suomeksi

energiahoidot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012

**Voyager-id:** 190282

**Termiehdotus Fintossa:** [energiahoidot](http://finto.fi/yse/fi/page/Y390282)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tätä: https://holvi.com/shop/heidimiranda/product/62024b5f3b3f7d8354b03f75069b7b86/

**Comment by mariaforsen** [comment]
Tästä löytyy paljon aineistoa, ja energia + hoitomenetelmät tms. ei ole tähän suositeltava. 
Sv. energibehandlingar
https://www.kielitoimistonsanakirja.fi/#/energiahoito

**Comment by mirmaid** [comment]
18 kertaa Melindassa yksikössä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _energiahoidot_.
