### ISSUE TITLE
grooming

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3716]
#### Ehdotettu termi suomeksi

grooming
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)
#### Käsitteen määritelmä

”Grooming-termillä viitataan kaikkiin niihin tekoihin ja toimintoihin, joita seksuaaliseen hyväksikäyttöön pyrkivä käyttää päästäkseen tavoitteeseensa. Prosessilla viitataan sen asteittaiseen etenemiseen, jatkumoon, joka sisältää alun, keskivaiheen ja lopulta hyväksikäytön realisoitumisen.”

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012

**Voyager-id:** 190288

**Termiehdotus Fintossa:** [grooming](http://finto.fi/yse/fi/page/Y390288)

**Comment by fantsby-m** [comment]
Termille olisi käyttöä, vaikka asian voikin kuvailla muilla asiasanoilla.
Esim: https://jyx.jyu.fi/handle/123456789/67584#

Wikpedia:
https://fi.wikipedia.org/wiki/Grooming

**Comment by jarmosaarikko** [comment]
- svenska.se suosittelee muotoa [gromning](https://svenska.se/tre/?sok=grooming&pz=2),  till groma 1,2
- https://sv.wikipedia.org/wiki/Gromning
- https://www.wikidata.org/wiki/Q1147070
Kts myös:
- LCSH [Child grooming (Child sexual abuse)](http://id.loc.gov/authorities/subjects/sh2021000100), sillä pelkkä [grooming](http://id.loc.gov/authorities/subjects/sh00007723) viittaa myös eläinten hyväilyyn jne. 
- Huom. näitä ei pidä sekoittaa käsitteisiin "[grooming behaviour](https://www.wikidata.org/wiki/Q999981)"  ja "[personal grooming](https://en.wikipedia.org/wiki/Personal_grooming)"

**Comment by ilona-x** [comment]
https://www.kotus.fi/nyt/kuukauden_sana/kuukauden_sanat_2019/grooming.29298.news

**Comment by mariaforsen** [comment]
Sv. gromning ET groomning, grooming 
 https://id.kb.se/term/sao/Gromning

**Comment by mirmaid** [comment]
KT groomaus
