### ISSUE TITLE
supertietokoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#372]
#### Ehdotettu termi suomeksi

supertietokoneet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)

**Luontipäivämäärä:** 08.10.1998

**Muokkauspäivämäärä:** 9.7.2001, 12.9.2003, 16.12.2008

**Voyager-id:** 114403

**Termiehdotus Fintossa:** [supertietokoneet](http://finto.fi/yse/fi/page/Y314403)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
