### ISSUE TITLE
ilmaispelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3721]
#### Ehdotettu termi suomeksi

ilmaispelit
#### Ehdotetut ohjaustermit

free-to-play-pelit, freemium-pelit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)
#### Käsitteen määritelmä

Ovat ilmaisia digitaalisia/video-/nettipelejä, joihin saa lisää sisältöä rahalla; peliin voi esim. ostaa lisää tavaroita tai virtuaalirahaa.  Julkaisu: Helsingin  Sanomat 23.5.2012

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012

**Voyager-id:** 190293

**Termiehdotus Fintossa:** [ilmaispelit](http://finto.fi/yse/fi/page/Y390293)

**Comment by ilona-x** [comment]
tälle olisi ollut käyttöä tämän väitöskirjan kuvailussa: The Rise of Free-to-Play: How the Revenue Model Changed Games and Playing http://urn.fi/URN:ISBN:978-952-03-1774-4

--

https://fi.wikipedia.org/wiki/Ilmaispeli

Melinda:
ilmaispeli x 1
ilmaispelit x 2

**Comment by mariaforsen** [comment]
Sv. gratisspel ET freemiumspel
