### ISSUE TITLE
kuvitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3739]
#### Ehdotettu termi suomeksi

kuvitukset
#### Ehdotetut ohjaustermit

kuvitustyöt
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/ysa/ryhma_82)
[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/ysa/ryhma_92)

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012

**Voyager-id:** 190311

**Termiehdotus Fintossa:** [kuvitukset](http://finto.fi/yse/fi/page/Y390311)

**Comment by jtuohini** [comment]
Sanana 'kuvitus' lienee ennemmin jaollinen substantiivi kuin laskettavissa olevien erillisten yksiköiden kuvaama sana, joten se ei oikein istu kieleen monikollisena. Merkityksestä ks. myös https://www.kielitoimistonsanakirja.fi/#/kuvitus

**Comment by tpalonen** [comment]
Käytetään yleisesti monikossa. Vrt. "kuvitukset"-haulla Googlessa 1 280 000 hakutulosta, "kuvitukset" esiintymiä hs.fi-sivuilla 263 kpl ja yle.fi-sivuilla 142 kpl.

**Comment by jtuohini** [comment]
Montaa muutakin sanaa käytetään kovin vapaasti monikossa, kuten "ruokahaluja" (pro ruohalua), "apuja" (pro apua), "olla yhteyksissä" (olla yhteydessä). Aiemmin Helsingin Sanomat oli hyvä esimerkki virheettömästä kielestä, mutta ei enää. Ja Ylen uutisia alkaa olla suorastaan rasittava lukea, kun kirjoistusvirheitä esiintyy sangen taajaan (puuttuvia yhdysviivoja, väärin kirjoitettuja sanoja, jopa vääriä sanoja).

**Comment by tpalonen** [comment]
Yleissanaston olisi hyvä seurata myös yleistä kieltä ja sen kehitystä. Minusta yli miljoona Google-tulosta on tosi iso määrä.

**Comment by mirmaid** [comment]
Koska sanastossa on jo _kuvitus_, tämä on siis oikeastaan muutosehdotus, eli kuvitus muutettaisiin muotoon _kuvitustaide_ ja toiseksi käsitteeksi otettaisiin _kuvitukset_. Viitteissä kuitenkin luultavammin kuvitus > kuvitukset kuin kuvitus > kuvitustaide. 

Toki siis kuten Jaakko kirjoittaa, _kuvitus_ viittaa esim. kirjan kuvasisältöön kokonaisuutena, jolloin yksikkö on luonteva (toki voidaan ajatella kuvittajan tehneen useita kuvituksia, eli kuvittaneen esim. useita kirjoja). Nykyään sitten ehkä _kuvitukset_ on alkanut viitata myös useisiin yksittäisiin [kuvituskuviin](https://www.elinalappalainen.fi/nyt-pelittaa/miten-kirjan-kuvitukset-on-tehty-jussi-kaakinen-kertoo-kuvittajan-tyosta/), jolloin se ainakin joidenkin korvaan kuulostaa virheelliseltä (yhden sivun kuva ei ole vielä kuvitus).

**Comment by tpalonen** [comment]
Suomalaisten kuvittajien ammatillisen yhdistyksen Kuvittajat ry:n sivuilla (kuvittajat.fi) monikkomuotoa "kuvitukset" esiintyy 695 kertaa eli ammattipuolella monikkomuoto näyttää kyllä jo hyvin vakiintuneen.

**Comment by mirmaid** [comment]
^ Mitähän sanovat ammattilaiset tuohon ylläolevaan käyttöön kuvituskuvan synonyymina?

**Comment by tpalonen** [comment]
Näin sitä juuri monikkomuodossa käytetään eli kun yhdessä kirjassa on useita kuvia niin käytetään sanaa kuvitukset. Poimintoja kuvittajat.fi-sivuilta:
_"Kissa Kasuli ja eläinten turvametsä -lastenkirjan kuvitukset"
"Olikohan se dinosauruskirjan kuvitukset tilannut kustantamo englantilainen?"
"Konferenssin toisessa osassa kankaalle heijastetut kuvitukset toimivat keskustelun herättäjänä ja summaajana."
"Tein kirjaan kuvitukset ja taiton"
"Suuria suosikkejani olivat Dorén kuvitukset Danten Jumalaiseen näytelmään."_

**Comment by jtuohini** [comment]
Ja jotkut puhuvat "musiikeista", jopa musiikkialan henkilöt, eikä ole outoa nähdä soitinsävellyksiä nimitettävän "lauluiksi"…

**Comment by mirmaid** [comment]
Tässä vaiheessa lisäisin monikkomuodon ohjaustermiksi.
