### ISSUE TITLE
mediankäyttö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3755]
#### Ehdotettu termi suomeksi

mediankäyttö
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 20.12.2012

**Muokkauspäivämäärä:** 20.12.2012

**Voyager-id:** 190327

**Termiehdotus Fintossa:** [mediankäyttö](http://finto.fi/yse/fi/page/Y390327)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
