### ISSUE TITLE
täydellisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3809]
#### Ehdotettu termi suomeksi

täydellisyys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 21.12.2012

**Muokkauspäivämäärä:** 21.12.2012

**Voyager-id:** 190387

**Termiehdotus Fintossa:** [täydellisyys](http://finto.fi/yse/fi/page/Y390387)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2174
