### ISSUE TITLE
tauot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#382]
#### Ehdotettu termi suomeksi

tauot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 09.10.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114423

**Termiehdotus Fintossa:** [tauot](http://finto.fi/yse/fi/page/Y314423)

**Comment by henriyli** [comment]
Otettu YSAan 14.3.2012: http://www.yso.fi/onto/ysa/Y184936
