### ISSUE TITLE
ylisukupolvisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3825]
#### Ehdotettu termi suomeksi

ylisukupolvisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[61 Väestötiede. Demografia](http://www.yso.fi/onto/ysa/ryhma_61)

**Luontipäivämäärä:** 08.04.2013

**Muokkauspäivämäärä:** 8.4.2013, 4.11.2013, 14.11.2013

**Voyager-id:** 192101

**Termiehdotus Fintossa:** [ylisukupolvisuus](http://finto.fi/yse/fi/page/Y392101)

**Comment by mirmaid** [comment]
Käsitelty viimeksi YSA-kokouksessa 1/2016.

**Comment by vilkkier** [comment]
Tarvitsisin väitöskirjaan Institutions and the intergenerational transmission of socioeconomic resources /Heta Pöyliö. Siinä pohditaan  mahdollisuuksia murtaa ylisukupolvista eriarlvoisuutta. Tuohon ei oikein käy periytyvyys, jota on tällaisissa ainakin joskus käytetty.

**Comment by mirmaid** [comment]
Ylisukupolvinen huono-osaisuus tai ylisukupolvinen syrjäytyminen?

**Comment by vilkkier** [comment]
Ehdotan ylisukupolvisuus-termiä. On myös yleisempi kuin huono-osaisuus tai syrjäytyminen esim. "Kolmiosuhteiden ylisukupolvisesta vaikutuksesta parisuhteeseen." "Ylisukupolviset perhesuhteet", Ylisukupolviset tulonsiirrot. Tutkimus ylisukupolvisista leikeistä. Ylisukupolviset traumat (esim. sota) jne.

**Comment by mirmaid** [comment]
_Ylisukupolviset vaikutukset_ olisi myös mahdollinen?

**Comment by vilkkier** [comment]
Miksei. Mutta entä vaikka nuo leikkien siirtyminen ylisukupolvisesti tai ylisukupolviset tulonsiirrot. Joskus tutkitaan vain ilmiötä ei vaikutuksia. Onkohan LC:ssä jotain vastaavaa? Intergenerational transmission -muotoa näkyi julkaisuissa (finnassa),

**Comment by mirmaid** [comment]
Mitenkäs ruotsiksi @mariaforsen?

**Comment by mariaforsen** [comment]
Sv. överföring mellan generationer

**Comment by ilona-x** [comment]
KEKO: ylisukupolvisuus  
MÄÄRITELMÄ
    ominaisuus, johon kuuluu näkemys siitä, että tiedot, taidot, kulttuuri ja hyvinvointi siirtyvät sukupolvien välillä molempiin suuntiin

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa ylisukupolvisuus. Käsite ei sopine käytettäväksi, kun puhutaan asioista/ilmiöistä, jotka hyppäävät yhden sukupolven yli.
