### ISSUE TITLE
pienlehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3861]
#### Ehdotettu termi suomeksi

pienlehdet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 11.04.2013

**Muokkauspäivämäärä:** 11.04.2013

**Voyager-id:** 192210

**Termiehdotus Fintossa:** [pienlehdet](http://finto.fi/yse/fi/page/Y392210)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
