### ISSUE TITLE
soitintutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3864]
#### Ehdotettu termi suomeksi

soitintutkimus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)

**Luontipäivämäärä:** 11.04.2013

**Muokkauspäivämäärä:** 11.04.2013

**Voyager-id:** 192213

**Termiehdotus Fintossa:** [soitintutkimus](http://finto.fi/yse/fi/page/Y392213)

**Comment by jtuohini** [comment]
Taas olisi tarvetta tälle termille (ja ollut kyllä aiemminkin), kun pitäisi korjata teoksen _Musikinstrument berättar: instrumentforskning idag_ kuvailua... Ja ruotsinkielinen vastine termille olisi tuo kirjan nimekkeessäkin oleva **instrumentforskning** ja RT-suhteiseksi termiksi ehkä osuvin **musiikkitiede**.

**Comment by mariaforsen** [comment]
Sv. instrumentforskning ET musikinstrumentforskning
