### ISSUE TITLE
tarkistuslistat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3869]
#### Ehdotettu termi suomeksi

tarkistuslistat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 11.04.2013

**Muokkauspäivämäärä:** 11.4.2013, 11.04.2013

**Voyager-id:** 192222

**Termiehdotus Fintossa:** [tarkistuslistat](http://finto.fi/yse/fi/page/Y392222)

**Comment by tarjaturunen** [comment]
Ehdotettu asiasana tarpeellinen. Tarvittu teoksen "The checklist manifesto : how to get things right" https://melinda.kansalliskirjasto.fi/F/646EE9LRUEI811MYFXR7LP14KNRM8VLI49R9A93YCXDVRF84SC-09663?func=full-set-set&set_number=007100&set_entry=000003&format=999
kuvailussa, jo joku käyttänyt ko. teoksen kuvailussa vapaana asiasanana

**Comment by mirmaid** [comment]
6 viitettä Melindassa, niiden perusteella ryhmä ei voi olla ainakaan pelkästään 48. Suurin osa viitteistä liittyi säiliöaluksiin.

**Comment by mariaforsen** [comment]
Sv. checklistor ET kontrollistor -ryhmä 00.
