### ISSUE TITLE
eteläinen pallonpuolisko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3887]
#### Ehdotettu termi suomeksi

eteläinen pallonpuolisko
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[06 Tähtitiede. Astronomia. Avaruustutkimus](http://www.yso.fi/onto/ysa/ryhma_06)
[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/ysa/ryhma_11)

**Luontipäivämäärä:** 17.06.2013

**Muokkauspäivämäärä:** 17.06.2013

**Voyager-id:** 193288

**Termiehdotus Fintossa:** [eteläinen pallonpuolisko](http://finto.fi/yse/fi/page/Y393288)

**Comment by ilona-x** [comment]
Melinda x 13

LCSH:
Southern Hemisphere
http://id.loc.gov/authorities/subjects/sh86007206

SAO:
södra halvklotet 
https://id.kb.se/term/sao/S%C3%B6dra%20halvklotet

https://fi.wikipedia.org/wiki/Etel%C3%A4inen_pallonpuolisko

**Comment by mariaforsen** [comment]
Sv. södra halvklotet HT södra hemisfären

**Comment by jarmosaarikko** [comment]
Wikidatassa on seuraavat, jotka ovat osa kohdetta "maa"  YSOssa 
- eteläinen pallonpuolisko - http://www.wikidata.org/entity/Q41228
- pohjoinen pallonpuolisko - http://www.wikidata.org/entity/Q39061
- itäinen pallonpuolisko - http://www.wikidata.org/entity/Q186198
- läntinen pallonpuolisko - http://www.wikidata.org/entity/Q181982
kaikille 
YK "luonnon muodostamat alueet"  
RT [maapallo](http://www.yso.fi/onto/yso/p11861)

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään YSOon.
