### ISSUE TITLE
pohjoinen pallonpuolisko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3888]
#### Ehdotettu termi suomeksi

pohjoinen pallonpuolisko
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[06 Tähtitiede. Astronomia. Avaruustutkimus](http://www.yso.fi/onto/ysa/ryhma_06)
[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/ysa/ryhma_11)

**Luontipäivämäärä:** 17.06.2013

**Muokkauspäivämäärä:** 17.06.2013

**Voyager-id:** 193289

**Termiehdotus Fintossa:** [pohjoinen pallonpuolisko](http://finto.fi/yse/fi/page/Y393289)

**Comment by ilona-x** [comment]
Melinda x 10

LCSH:
Northern Hemisphere
http://id.loc.gov/authorities/subjects/sh86007205

SAO:
norra halvklotet 
https://id.kb.se/term/sao/Norra%20halvklotet

https://fi.wikipedia.org/wiki/Pohjoinen_pallonpuolisko

**Comment by mariaforsen** [comment]
Sv. norra halvklotet HT norra hemisfären

**Comment by mirmaid** [comment]
LCSH:ssa nämä ovat paikkoja (samoin myös taivaankappaleet ja maailmankaikkeus).

**Comment by jarmosaarikko** [comment]
KTS #3887 
YSO vai YSO-paikat?  
YSO-paikoissa on maanosat ja valtameret, muttei laajempia alueita tai vyöhykkeitä.
Pallonpuoliskot ja Maa voisivat siis olla yso-paikoissakin mantereiden ja valtamerien yläkäsitteinä ja "Maa" pallonpuoliskojen yläkäsitteenä (siis koko ontologian top concept) 
- Kuun pinnanmuodot ja paikat ovat LCSH:ssa http://id.loc.gov/authorities/subjects/sh85087143).

yso-paikat suhteita niin haluttaessa:
- N  RT - pohjoinen jäämeri, pohjoinen atlantti, pohjois-amerikka, eurooppa, pohjois-aasia
- S  RT - eteläinen jäämeri, antarktis, australia, intian valtameri, eteläinen afrikka
- E RT Itä-aasia, Tyyni valtameri, Australia, Oseania
- W RT  Pohjois-Amerikka, Etelä-Amerikka, Oseania

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään YSOon.
