### ISSUE TITLE
resurssiviisaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3890]
#### Ehdotettu termi suomeksi

resurssiviisaus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/ysa/ryhma_21)
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/ysa/ryhma_22)
[23 Erätalous. Kalastus. Metsästys](http://www.yso.fi/onto/ysa/ryhma_23)

**Luontipäivämäärä:** 17.06.2013

**Muokkauspäivämäärä:** 17.06.2013

**Voyager-id:** 193292

**Termiehdotus Fintossa:** [resurssiviisaus](http://finto.fi/yse/fi/page/Y393292)

**Comment by tpalonen** [comment]
Finto-palautteeseen on tullut viesti: _"Resurssiviisaus-sanaa tarvittaisiin kuvailussa liittyen muun muassa asiayhteydessä liittyen energiaan, luonnonvaroihin, kestävään kehitykseen jne. Voisiko sanan resurssiviisaus saada YSOn?"_

**Comment by ilona-x** [comment]
Melinda x 1

Wikipediassa vain suomeksi https://fi.wikipedia.org/wiki/Resurssiviisaus

**Comment by mirmaid** [comment]
Sanastossa on _kestävä käyttö_. _Resurssiviisaus on kykyä käyttää erilaisia resursseja (luonnonvarat, raaka-aineet, energia, tuotteet ja palvelut, tilat ja aika) harkitusti ja hyvinvointia sekä kestävää kehitystä edistävällä tavalla_. https://fi.wikipedia.org/wiki/Resurssiviisaus

**Comment by mariaforsen** [comment]
Sv. resursvisdom, resursvishet jonkin verran Suomessa

**Comment by YSO-kokous** [comment]
Otetaan ohjaustermiksi:
resurssiviisaus KÄYTÄ kestävä käyttö
