### ISSUE TITLE
terveystiedot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#391]
#### Ehdotettu termi suomeksi

terveystiedot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 09.10.1998

**Muokkauspäivämäärä:** 9.7.2001, 7.11.2008, 10.11.2008, 10.11.2008, 16.12.2008

**Voyager-id:** 114436

**Termiehdotus Fintossa:** [terveystiedot](http://finto.fi/yse/fi/page/Y314436)

**Comment by mirmaid** [comment]
http://jultika.oulu.fi/Record/isbn978-952-62-2976-8

**Comment by mirmaid** [comment]
_Terveystieto_-asiasanaa käytetty myös muusta kuin oppiaineesta.

**Comment by mariaforsen** [comment]
Myös ruotsiksi olisi hälsoinformation hyvä käsite, tämäntyyppisiin: Hälsoinformation idag och i morgon : östgötarnas användning av och förtroende för olika informationskällor ; Hälsoinformation via Internet, bibliotek och patientinformationscentraler.

**Comment by ilona-x** [comment]
terveystieto https://www.kielitoimistonsanakirja.fi/#/terveystieto?searchMode=all
**1. ihmisen terveyttä käsittelevä oppiaine.**
**2. tietous terveydestä.**
Kansalaisten terveystiedon lisääminen.
**3. tieto jnk terveydestä.**
Potilaan terveystiedot.

Vaatiiko tarkenteen vai voidaanko käyttää samaa termiä 2. & 3. merkityksistä? 🤔

**Comment by mirmaid** [comment]
^ Ehkä ei...

**Comment by mirmaid** [comment]
Pitäisikö tämä aloittaa > _terveystieto (oppiaineet)_ -siivouksella? Toisaalta 1 ja 2 ovat kyllä samaa asiaa ihan samalla tavalla kuin vaikka historia oppiaineena ja muissa yhteyksissä (_terveystieto (tietämys tms.)_), mutta _terveystiedot_ olisi oma kokonaisuutensa.

**Comment by mariaforsen** [comment]
1
(Suom)kouluaineena hälsokunskap -en
2
tietous terveydestä hälsokunskap -en -er
hälsoinformation -en
tietoisuus hälsomedvetenhet -en hälsomedvetande -t
3
tieto jkn terveydestä hälsouppgift -en -er
/Stora finsk-svenska ordboken

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _terveystieto (oppiaineet)_,

Käsitteeseen _terveysosaaminen_ ohjaustermi _terveystietous_ tms.

Tarkistetaan jäljelle jäävä väärä käyttö.

**Comment by mirmaid** [comment]
Jäljelläolevien viitteiden korjaukseen sopii usein terveysosaaminen tai terveysviestintä, joskus terveyskäsitykset. Viitelistan alussa (Melinda, selaushaku _terveystieto_) on nyt kymmenkunta viitettä, joissa kyse on joko a) terveyteen liittyvästä tiedosta merkityksessä "informaatio, data" tai b) potilastiedosta. 

Sanastossa on potilasasiakirjat ja potilastietojärjestelmät. Potilasasiakirja on ilmeisesti käsittenä melko laaja: _Potilasasiakirjoihin kuuluvat potilaskertomus ja siihen liittyvät potilastiedot tai asiakirjat sekä lääketieteelliseen kuolemansyyn selvittämiseen liittyvät tiedot tai asiakirjat samoin kuin muut potilaan hoidon järjestämisen ja toteuttamisen yhteydessä syntyneet tai muualta saadut tiedot ja asiakirjat_. https://finlex.fi/fi/laki/alkup/2022/20220094
_Potilasasiakirjat määritellään potilaan hoidon järjestämisessä ja toteuttamisessa käytettäväksi laadituiksi tai saapuneiksi asiakirjoiksi tai teknisiksi tallenteiksi, jotka sisältävät potilaan terveydentilaa koskevia tietoja tai muita henkilökohtaisia tietoja. Potilasasiakirjoihin kuuluvat varsinaiset potilaan hoitoa ja tutkimusta koskevat merkinnät ja myös muut sairaan- ja terveydenhoitotoimenpiteiden yhteydessä syntyneet asiakirjat, kuten erilaiset lähetteet, tulokset ja lausunnot, röntgenkuvat, potilaspäiväkirjat sekä muut tallenteet_. https://www.laakariliitto.fi/laakarin-etiikka/potilas-laakarisuhde/potilasasiakirjat/

Sanastossa on nyt potilastiedot KÄ potilasasiakirjat, ehkäpä tämän osalta riittää jos tehdään vielä joku terveystiedot (potilastiedot) KÄ potilasasiakirjat -ohjaus? Ihan jokaiseen tapaukseen tämä ei sovi, esim. https://melinda.kansalliskirjasto.fi/byid/011478778, mutta lienevät kuitenkin melko pieni joukko.

Terveyteen liittyvä informaatio (usein melkein lääketieteellinen data) olisi sanastossa vähän poikkeuksellinen tapaus (tiettyyn aiheeseen liittyvä tieto/informaatio), joten ehkä paras ratkaisu olisi pyrkiä korjaamaan nämä useamman termin yhdistelmällä.

**Comment by mariaforsen** [comment]
Kannatan myös että "tieto jnk terveydestä"-merkityksessä ohjataan käyttämään potilastiedot-termiä (tai tällä hetkellä tietty potilasasiakirjat)

**Comment by annamarj** [comment]
Minulle on hiljan tullut sisällönkuvailussa vastaan pari julkaisua, joissa keskeiseksi asiaksi nimetään "terveysdata" ja "sote-data" sekä "työaika- ja potilastietoihin perustuva rekisteriaineisto ". Tämäkin tullee vaikuttamaan siihen, miten puhutaan. https://www.sitra.fi/julkaisut/datasta-voimaa-sote-jarjestelmaan/ sekä https://www.etla.fi/julkaisut/raportit/tehokkuus-ja-tyohyvinvointi-tiedolla-kohti-tasapainoista-tyota/
Näissä kai olennaista se, että dataa voidaan koostaa eri järjestelmästä laajasti niin, että se ei enää kytkeydy yksittäisen ihmisen potilastietoihin/terveystietoihin/potilasasiakirjoihin. Esim. "mm. potilaille määriteltyjen hoitoisuusluokituksien, päiväkohtaisten juoksevien keskimääräisten hoitojaksojen pituuksien, osaston keski-määräisen diagnoosijakauman, hoitotyyppien ja osastontäyttöasteen avulla. " Tämänhän mahdollistaa mm. rakenteistettuun dataan perustuvan Apotin käyttöönotto. Tällainen sivuhuomio jo muutenkin vähän kimurantin oloiseen kysymykseen.

**Comment by mirmaid** [comment]
Jäljelläolevista n. kolmasosassa terveystieto vaikuttaisi tarkoittavan terveysinformaatiota (ei ehkä niinkään varsinaista dataa). Tuloksissa tätä aineistoa nyt 40 ensimmäistä viitettä.

**Comment by mariaforsen** [comment]
Voisiko siis sanastossa olla terveysinformaatio/terveystieto (informaatio) suomen kannalta? Ruotsiksi hälsoinformation olisi hyvä.

**Comment by HeidiRonkainen** [comment]
Tässäkin tarpeen https://www.sitra.fi/en/publications/advancing-data-sharing-to-improve-health-for-all-in-europe/

**Comment by mariaforsen** [comment]
Onko sitten oikeastaan niin että tarvittaisiin kahta eri käsitettä: 

1) terveysdata / terveystiedot (data) sv. hälsodata 
"henkilön fyysiseen tai psyykkiseen terveyteen liittyvä henkilötieto"

2) terveystieto (informaatio), sv. hälsoinformation ?
"terveystieto kattaa informaation terveenä pysymiseksi, sairauksien ehkäisemiseksi ja hallitsemiseksi sekä muiden terveyttä ja terveydenhoitoa koskevien päätösten tekemiseksi"  

Lähde: https://termipankki.fi/tepa/fi/haku/terveystieto
https://www.kielitoimistonsanakirja.fi/#/terveystieto?searchMode=all
https://www.sitra.fi/tulevaisuussanasto/terveysdata/
https://eur-lex.europa.eu/legal-content/FI/TXT/HTML/?uri=CELEX:32016R0679

Melindassa runsaasti hälsoinformation / health information -aineistoa. Myös yllä mainittu hälsodata / health data.

**Comment by annamarj** [comment]
Terveysdata -käsite sen kun yleistyy, olettaisin. On mm. hallitusohjelmassa "Toteutetaan datataloudesta laaja-alainen, strateginen teemakokonaisuus, jonka kärkiä ovat kvanttilaskenta, nopeat langattomat verkot, terveysdata, kyberturvallisuus ja tekoäly. Hallitus pyrkii ennakoimaan ja seuraamaan myös muiden avainteknologioiden läpimurtoa"

**Comment by mirmaid** [comment]
Tässä ehkä tyypillinen esimerkki tuosta terveysinformaatio-merkityksestä: https://melinda.kansalliskirjasto.fi/byid/013458477. Tämä ei viittaa terveysdataan, mutta jos sana olisi terveysinformaatio, data-aiheet tulisivat helposti samaan haaviin, ellei myös terveysdata olisi sanastossa erikseen. Jos se otetaan, löytyy varmaan vastaavia, esim. talousdata, työllisyysdata (?).

Toisaalta olisiko kuvailu erityisen puutteellinen ilman terveystieto/terveysinformaatio -sanoja? Käytettävissä toki myös pelkkä informaatio, tiedonlähteet, terveysviestintä ja terveysosaaminen. Tässä toinen vastaava: https://melinda.kansalliskirjasto.fi/byid/013464721

**Comment by FinMeSHienPaimentaja** [comment]
Ihmisille ja potilaille suunnattu "terveysinfomaatio" ohjaavassa, opastavassa ja valistavassa mielessä on minusta hyvinkin eri asia kuin terveysdata (siinä mielessä, että kerätään big dataa, tai kyseessä on yksittäisen ihmisen terveyteen liittyvät tiedot tai jotain siltä väliltä, esim. tietyn sairaalan tai hyvinvointialueen potilaiden (tietyt) terveystiedot).

**Comment by AuHo22** [comment]
Itse mietin eroa potilastiedot/sosiaalitoimen asiakasrekisterit/ja terveysdata (tai sotedata) merkityksessä tutkimusdata -tarkoitusten välillä:
-> terveysdata tai sote-data -termeistä itselleni tulee ensimmäiseksi mieleen ns. big datan käyttö (anonyymisti) eli mainittu toissijainen käyttö?, _luoda johdonmukainen, luotettava ja tehokas perusta terveystietojen käytölle tutkimus-, innovointi-, päätöksenteko- ja sääntelytarkoituksia varten_ 
https://health.ec.europa.eu/ehealth-digital-health-and-care/european-health-data-space_fi   
-> itsekin olen satunnaisotantojen takia joissakin geenitutkimuspankeissa ko. merkityksessä
mutta toisaalta terveystiedot-sanaa käytetään yhtä hyvin henkilön omien terveystietojen, so. potilastietojen kohdalla, ja tämä kaksinaismerkitys pitäisi siis välttää?

**Comment by mariaforsen** [comment]
Mielestäni terveystieto (informaatio) / terveysinformaatio on tosi tärkeä termi, jota tarvitaan vain entistä enemmän. Ainakin meillä on tehty tutkimusta juuri tästä aiheesta. 

Kannatan siis molempien ottamista.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon terveysinformaatio ja terveysdata. Pohditaan näille ohjaustermejä.

**Comment by mariaforsen** [comment]
Sv. 
-hälsoinformation 
-hälsodata

https://mesh.kib.ki.se/term/D054626/consumer-health-information
https://termipankki.fi/tepa/fi/haku/terveystieto
https://www.kielitoimistonsanakirja.fi/#/terveystieto?searchMode=all
https://lakartidningen.se/wp-content/uploads/OldPdfFiles/2001/23055.pdf

https://www.sitra.fi/tulevaisuussanasto/terveysdata/
https://eur-lex.europa.eu/legal-content/FI/TXT/HTML/?uri=CELEX:32016R0679
https://smer.se/teman/halsodata/
https://www.ehalsomyndigheten.se/om-oss/halsodata/
