### ISSUE TITLE
käyttäytymistaloustiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3921]
#### Ehdotettu termi suomeksi

käyttäytymistaloustiede
#### Ehdotetut ohjaustermit

behavioristinen taloustiede, psykologinen taloustiede
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 17.06.2013

**Muokkauspäivämäärä:** 17.6.2013, 05.11.2013

**Voyager-id:** 193327

**Termiehdotus Fintossa:** [käyttäytymistaloustiede](http://finto.fi/yse/fi/page/Y393327)

**Comment by mirmaid** [comment]
_Essays in Behavioral Economics_

**Comment by ilona-x** [comment]
LCSH: 
Economics--Psychological aspects KT Behavioral economics KT Behavioural economics
http://id.loc.gov/authorities/subjects/sh85040859

**Comment by mirmaid** [comment]
7 viitettä Melindassa. 
FinMeSH: behavioraalinen taloustiede 
https://fi.wikipedia.org/wiki/K%C3%A4ytt%C3%A4ytymistaloustiede

**Comment by mariaforsen** [comment]
Sv. beteendeekonomi

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
