### ISSUE TITLE
true crime

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3925]
#### Ehdotettu termi suomeksi

true crime
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)

**Luontipäivämäärä:** 17.06.2013

**Muokkauspäivämäärä:** 17.06.2013

**Voyager-id:** 193332

**Termiehdotus Fintossa:** [true crime](http://finto.fi/yse/fi/page/Y393332)

**Comment by ilkkahaataja** [comment]
Käsite tarvitaan ainakin SLM-sanastoon,.

Ehdotettu termi suomeksi:

true crime -tarinat

Termi ruotsiksi:
sanna kriminalhistorier

Termi englanniksi:
true crime stories 

Vaihtoehtoiset termit ja ilmaisut:
todelliset rikostarinat

Yläkäsite YSOssa (LT):
tietokirjallisuus

YSA/YSO temaattinen ryhmä:
56   87

Vastaava käsite muussa sanastossa:

LCSH
 true crime stories

LCGFT
 true crime stories 

SAOGF
 sanna kriminalhistorier

Tarkoitusta täsmentävä selite:
Suurelle yleisölle suunnattu, todellisia rikoksia käsittelevä, usein kaunokirjallisuuden keinoja käyttävä tietokirjallisuus. 

Minkä aineiston kuvailussa tarvitsisit käsitettä? (esim. nimeke tai URL): *
Truman Capote. In cold blood
Norman Mailer. The executioner's song
Tilda Laaksonen. Jäljillä : selvittämättömiä rikostapauksia meiltä ja maailmalta.

**Comment by mirmaid** [comment]
Hyväskytty muodossa true crime /SLM.

**Comment by mirmaid** [comment]
Lisätty kolme narrower match -linkkiä. RT-suhteet (rikossarjakuvat)? Yläkäsite?

**Comment by ilona-x** [comment]
SLM-kokous/ ei yläkäsitettä

**Comment by mariaforsen** [comment]
Kannatan myös YSOon.

**Comment by mirmaid** [comment]
YSO-yläkäsitteestä toivottiin näkemystä (ja voisiko olla myös SLM:ssä kertomukset)?

**Comment by mirmaid** [comment]
Jos joku tekisi podcastin kansankertomuksista, niin kai ko. genretermiä voisi silloin käyttää? Entä elokuvat, jos saagasta tehdään elokuvaversio, saako termiä käyttää sen kuvailussa? Entä sadut-termiä esim. Disney-elokuvien kuvailussa? Jos nykyisiä alakäsitteitä saa käyttää laajemmin, silloin kai true crime sopii joukkoon?

**Comment by mirmaid** [comment]
LT ei-fiktiiviset aineistot
