### ISSUE TITLE
kestävä elämäntapa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3935]
#### Ehdotettu termi suomeksi

kestävä elämäntapa
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 04.11.2013

**Muokkauspäivämäärä:** 4.11.2013, 04.11.2013

**Voyager-id:** 195478

**Termiehdotus Fintossa:** [kestävä elämäntapa](http://finto.fi/yse/fi/page/Y395478)

**Comment by PaiviLipsanen** [comment]
Väitöskirja: Avoiding Consumer Scapegoatism : Towards a Political Economy of Sustainable Living
https://helda.helsinki.fi/handle/10138/303978

Onko kestävä kulutus = kestävä elämäntapa?

**Comment by mirmaid** [comment]
^ Onhan se varmaan ainakin erittäin lähellä.

**Comment by mariaforsen** [comment]
SAOssa on hållbar livsstil LCSH Sustainable living. Kestävä kulutus on osa kestävää elämäntapaa. 
https://sv.wikipedia.org/wiki/H%C3%A5llbar_livsstil
https://finto.fi/keko/fi/page/p88

**Comment by ilona-x** [comment]
https://www.luontokoulut.fi/ops2016/kestava-elamantapa/

**Comment by YSA-kokous** [comment]
Keskustelua, eroaako kestävästä kulutuksesta. Tarvitaanko tämän lisäksi erikseen?

**Comment by ilona-x** [comment]
KEKO: **kestävä elämäntapa** http://www.yso.fi/onto/keko/p88 
KEKOn määritelmä: "elämäntapa, johon sitoutuneet yksilöt noudattavat erilaisissa tehtävissään ja elämänkaarensa kaikissa vaiheissa kestäviä toimintatapoja ottaen huomioon valintojensa ekologisia, taloudellisia, sosiaalisia ja kulttuurisia vaikutuksia sekä paikallisesti että maailmanlaajuisesti"

KEKO: **kestävät kulutusvalinnat** http://www.yso.fi/onto/keko/p230
KEKOn määritelmä: "yksilön tai yhteisön elämäntapaan ja hankintapäätöksiin liittyvät valinnat, jotka pyrkivät vähentämään kulutuksen kielteisiä vaikutuksia ympäristöön ja ihmisiin paikallisesti ja maailmanlaajuisesti"

**Comment by tpalonen** [comment]
Esim. jätteistä huolehtiminen ja jätteiden vähentäminen ei suoranaisesti liene kuluttamista?
https://en.wikipedia.org/wiki/Sustainable_living#Waste

**Comment by mirmaid** [comment]
^ Itse näen senkin kyllä kulutuksen osana - ei ehkä oikein voi sanoa jonkun kuluttavan kestävästi jos hän heittää jätteensä tienposkeen. Mutta tästä voi varmaan olla useampaa mieltä.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. hållbar livsstil
