### ISSUE TITLE
vähähiilisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3942]
#### Ehdotettu termi suomeksi

vähähiilisyys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)

**Luontipäivämäärä:** 04.11.2013

**Muokkauspäivämäärä:** 04.11.2013

**Voyager-id:** 195485

**Termiehdotus Fintossa:** [vähähiilisyys](http://finto.fi/yse/fi/page/Y395485)

**Comment by HeidiRonkainen** [comment]
Sopisi tähän http://urn.fi/URN:ISBN:978-952-361-039-2

**Comment by mariaforsen** [comment]
Sv. koldioxidsnålhet
https://finto.fi/koko/sv/page/p86111

**Comment by ilona-x** [comment]
Melinda:
vähähiilisyys x 1

Esimerkkijulkaisussa asiasanana vähähiilinen rakentaminen, joka tuntuisi muodoltaan paremmalta termiltä. Mutta toisaalta taas vähähiilisyys -termiä voisi käyttää muissakin kuin rakentamista käsittelevissä julkaisuissa. Pitäisikö jättää vielä termiehdotukseksi?

**Comment by HeidiRonkainen** [comment]
Taas tulisi tarpeeseen: http://urn.fi/URN:ISBN:978-952-11-5501-7

**Comment by satuniininen** [comment]
Tännekin sopisi: https://www.vttresearch.com/sites/default/files/pdf/technology/2018/T325.pdf

**Comment by mirmaid** [comment]
Onko _hiilijalanjälki_ riittämätön näissä? Jos on, ja jos kääntäminen ei onnistu, voiko tätä lähestyä jollain muulla uudella termillä (päästövähennykset tms.?).

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään käsite _vähähiilisyys_
