### ISSUE TITLE
digitaaliset taidot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#3952]
#### Ehdotettu termi suomeksi

digitaaliset taidot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)
[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 04.11.2013

**Muokkauspäivämäärä:** 04.11.2013

**Voyager-id:** 195495

**Termiehdotus Fintossa:** [digitaaliset taidot](http://finto.fi/yse/fi/page/Y395495)

**Comment by leen989** [comment]
Ehdotan lisäystä. Tarvitaan Valtioneuvoston aineistoissa.

**Comment by jarmosaarikko** [comment]
Wikidatassa on 
-digitaalinen lukutaito [digital literacy](http://www.wikidata.org/entity/Q242069)  
-digitaidot [digital competence](http://www.wikidata.org/entity/Q1273263) , digital skills 
mikä on näiden ero?
LCSH: [Computer literacy](http://id.loc.gov/authorities/subjects/sh85029509) KT Digital literacy

Fintossa: tietotermit: on **monilukutaito**, jonka alla  [digitaalinen lukutaito](https://finto.fi/tt/fi/page/t22), [informaatiolukutaito](https://finto.fi/tt/fi/page/t128), [medialukutaito](https://finto.fi/tt/fi/page/t101), [verkkolukutaito](https://finto.fi/tt/fi/page/t110), [visuaalinen lukutaito](https://finto.fi/tt/fi/page/t8)

**Comment by mariaforsen** [comment]
Sv. digital kompetens HT digitala färdigheter, digital litteracitet, digikompetens, digifärdigheter
Myös SAOssa https://id.kb.se/find?q=Computer%20literacy linkitetty: LCSH Computer literacy

Ohjaustermiehdotuksia: https://termipankki.fi/tepa/fi/haku/digitaaliset%20taidot

**Comment by YSO-kokous** [comment]
### Päätös
Otetaan sanastoon digitaalistet taidot OT digitaidot
Otetaan ohjaustermejä TEPAsta https://termipankki.fi/tepa/fi/haku/digitaaliset%20taidot
