### ISSUE TITLE
viherpesu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4022]
#### Ehdotettu termi suomeksi

viherpesu
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)
[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 16.01.2014

**Muokkauspäivämäärä:** 16.01.2014

**Voyager-id:** 196820

**Termiehdotus Fintossa:** [viherpesu](http://finto.fi/yse/fi/page/Y396820)

**Comment by Pan2345** [comment]
Kannatan viherpesun ottamista YSOon. Viherpesu on laajasti ja yleisesti käytetty käsite. Sitä käsittelevää aineistoa on ilmestynyt yhä enemmän. Olisi hyvä, että asiakkailla olisi mahdollisuus löytää aihetta käsittelevää kirjallisuutta. Vastikään on ilmestynyt mm. teos Viherpesuopas (Antti Isokangas, Jani Niipola, Riku Vassinen). Ja myös muita teoksia on tullut, joissa aihetta käsitellään. Käsite on myös LCSH:ssa: https://id.loc.gov/authorities/subjects/sh2021008185.html . Wikipediassa: https://en.wikipedia.org/wiki/Greenwashing .

**Comment by mirmaid** [comment]
6 viitettä Melindassa. 

LCSH: http://id.loc.gov/authorities/subjects/sh2021008185

**Comment by mariaforsen** [comment]
Sv. grönmålning HT gröntvättning, greenwashing
https://terminologiframjandet.se/h552a9FtZ/tnc.se/termfraga/gronmalning/
https://www.isof.se/vart-uppdrag/samarbeten/hallbarhetstermgruppen/hallbarhetstermlistan/termer/gronmalning

**Comment by LeKorsu** [comment]
Tarvinnee kuitenkin jonkinlaisen määritelmän.

**Comment by mariaforsen** [comment]
Hyviä määritelmiä esim. tässä https://joutsenmerkki.fi/viherpesua-vai-ymparistovastuuta/ ja https://www.ykliitto.fi/sites/ykliitto.fi/files/yritysvastuun_sanakirja.pdf
