### ISSUE TITLE
oppilaslähtöisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4144]
#### Ehdotettu termi suomeksi

oppilaslähtöisyys
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 11.06.2014

**Muokkauspäivämäärä:** 11.06.2014

**Voyager-id:** 199222

**Termiehdotus Fintossa:** [oppilaslähtöisyys](http://finto.fi/yse/fi/page/Y399222)

**Comment by mirmaid** [comment]
Tarvittu myös: _Tehdään yhdessä #uuttakoulua_

**Comment by mariaforsen** [comment]
Sv. elevcentrering ET elevorientering, elevcentrerad undervisning
https://termipankki.fi/tepa/fi/haku/elevcentrering

**Comment by ilona-x** [comment]
tuosta ruotsinkielisestä termistä tuli mieleen tarkistaa oppilaskeskeisyys:
Melinda: 
oppilaskeskeisyys x 13
oppilaskeskeinen opetus x 1
oppilaskeskeinen opetuskäsitys  x 1

**Comment by fantsby-m** [comment]
oppilaskeskei* Melindassa asiasanana 18 kertaa, sanahaulla 107 kertaa

oppilaslähtöi* asiasanana 8 kertaa, sanahaulla 41 kertaa

**Comment by mirmaid** [comment]
Googlella oppilaslähtöisyys 5100, oppilaskeskeisyys 2230. YSOssa on _perhekeskeisyys_ ja _ratkaisukeskeisyys_, _potilas-, lapsi, käyttäjä-, asiakas-_ ja _työelämälähtöisyys_.

**Comment by YSO-kokous** [comment]
Hyväksytään oppilaslähtöisyys KT oppilaskeskeisyys

**Comment by mariaforsen** [comment]
Laitetaanko KT https://fi.wikipedia.org/wiki/Oppilasl%C3%A4ht%C3%B6inen_opetus ?
