### ISSUE TITLE
rodullistaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4148]
#### Ehdotettu termi suomeksi

rodullistaminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)

**Luontipäivämäärä:** 11.06.2014

**Muokkauspäivämäärä:** 11.06.2014

**Voyager-id:** 199226

**Termiehdotus Fintossa:** [rodullistaminen](http://finto.fi/yse/fi/page/Y399226)

**Comment by mirmaid** [comment]
Tarvittu taas: https://helda.helsinki.fi/handle/10138/294719

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. rasifiering
Melindassa esim. Stadens rasifiering : etnisk boendesegregation i folkhemmet = [Racialization of the city] : [ethnic residential segregation in the Swedish Folkhem] / Irene Molina.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
