### ISSUE TITLE
etäpalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4163]
#### Ehdotettu termi suomeksi

etäpalvelut
#### Ehdotetut ohjaustermit

etäpalvelu
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 11.06.2014

**Muokkauspäivämäärä:** 11.6.2014, 11.06.2014

**Voyager-id:** 199243

**Termiehdotus Fintossa:** [etäpalvelut](http://finto.fi/yse/fi/page/Y399243)

**Comment by ilona-x** [comment]
Tälle termille olisi ollut käyttöä teoksen 'Etäkuntoutus' kuvailussa. 
http://www.kela.fi/etakuntoutus-kuntoutuksen-uusi-mahdollisuus
YSAssa on etäkäyttö + kuntoutuspalvelut

Melinda x 2

http://vm.fi/etapalvelut
http://www.kela.fi/etapalvelu
http://www.valvira.fi/terveydenhuolto/yksityisen_terveydenhuollon_luvat/potilaille-annettavat-terveydenhuollon-etapalvelut

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
