### ISSUE TITLE
ympäristöaktivistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#418]
#### Ehdotettu termi suomeksi

ympäristöaktivistit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)

**Luontipäivämäärä:** 17.11.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114471

**Termiehdotus Fintossa:** [ympäristöaktivistit](http://finto.fi/yse/fi/page/Y314471)

**Comment by mariaforsen** [comment]
Sv. miljöaktivister. Kannatan, ajankohtainen termi ja aineistoa riittää. Sanastossa on ennestään ihmisoikeusaktivistit. 
Myös SAOssa: https://id.kb.se/term/sao/Milj%C3%B6aktivister

**Comment by ilona-x** [comment]
KAUNO: ympäristöaktivistit http://www.yso.fi/onto/kauno/p4592

**Comment by mirmaid** [comment]
2 viitettä Melindassa. YSOssa on _ympäristöaktivismi_ (ja eläinaktivismi).

**Comment by ilona-x** [comment]
YSOssa myös aktivistit, joten näitä varmaan kuvailtu ympäristöaktivismi & aktivistit -yhdistelmällä, jota on Melindassa käytetty 60 kertaa.

Huomasin, että SAO:n miljöaktivister  on linkattu LCSH-termiin Environmentalists, joka taas on linkattu YSO-termiin luonnonsuojelijat.
https://id.kb.se/term/sao/Milj%C3%B6aktivister

MOT Pro Englanti; englanti-suomi

environmentalist 
luonnonsuojelija, ympäristöaktivisti

ympäristöaktivisti
environmentalist, eco-activist, green, green campaigner, br m eco-warrior

https://en.wikipedia.org/wiki/Environmentalist

**Comment by fantsby-m** [comment]
Kielitoimiston sanakirja:

ympäristöaktivisti
aktiivisesti toimivasta ympäristönsuojelijasta, ympäristöaktiivi. 

luonnonsuojelija
aktiivisesti luonnonsuojelun puolesta toimivasta henkilöstä.

Ovat erittäin päällekkäisiä.

**Comment by AuHo22** [comment]
LC / DNB -> LT Environmentalists / Umweltschützer + ST Conservationists / Naturschützer

**Comment by YSO-kokous** [comment]
Selvitetään määritelmä ja ero luonnonsuojelijaan

**Comment by jarmosaarikko** [comment]
kyse on ylä-alakäsitteen erosta. Aktivistit eroavat ilmeiesti samalla tavalla, mutta juuri sen vuoksi -aktivistit ovat käsitteenä päällekkäisiä.  

[ympäristönsuojelu](http://www.yso.fi/onto/yso/p13) miljöskydd **LT** suojelu
- Kotus: "elinympäristön ja luonnon suojelu ihmisen toiminnan aiheuttamilta haitoilta."
- Ympäristösanasto: "toimet, joilla pyritään hoitamaan ympäristöä ja suojelemaan sitä ihmisen aiheuttamilta ympäristöhaitoilta"

[luonnonsuojelu](http://www.yso.fi/onto/yso/p11) naturskydd **LT** ympäristönsuojelu
- YSO: "Ympäristönsuojelun osa, jossa pyritään säilyttämään luonnon monimuotoisuus ja toimintakyky suojaamalla luontoa ihmisen aiheuttamilta ympäristöhaitoilta. -- Ympäristösanasto TSK 27"
- Kotus:  "luonnon suojaaminen ihmisen vahingoittavalta toiminnalta."

kannatan Ilonan ehdotusta:
ympäristöaktivistit KÄYTÄ ympäristöaktivismi + aktivistit 

luonnonsuojelija ei ole välttämättä aktivsti, joten en yhdistäisi siihen käsitteeseen aktivisteja ohjaustermiksikään

Mikäli lisätään uutena käsitteeenä, niin ehdotan:
ympäristöaktivistit | miljöaktivister | environmentalists
**LT** aktivistit
**RT** luonnonsuojelijat
LCSH closeMatch [Environmentalists](http://id.loc.gov/authorities/subjects/sh88003150)

luonnonsuojelijat - LCSH ja  eng. vastineeksi voisi tällöin vaihtaa [conservationists](http://id.loc.gov/authorities/subjects/sh85031271)

**Comment by mirmaid** [comment]
^ Varmaan kaikki ympäristöaktivistit kuitenkin ovat luonnonsuojelijoita, vaikka kaikki luonnonsuojelijoina itseään pitävät eivät ajattelisikaan olevansa aktivisteja? Toki pelkkä ympäristöaktivistit KÄ ympäristöaktivismi on varmaan sekin riittävä.

**Comment by AuHo22** [comment]
_ympäristöaktivistit KÄYTÄ ympäristöaktivismi + aktivistit_ -> En oikein kannata näitä tårta på torta -ilmaisuja, eli po. uutena käsitteenä ottaminen.
Oikea linkkaus yo. olisi tietenkin _SAO:n miljöaktivister on linkattu LCSH-termiin Environmentalists, joka taas on linkattu YSO-termiin luonnonsuojelijat._-> termiin ympäristöaktivistit (jota nyt ehdotetaan). SAO:ssa ei puolestaan ole termiä naturskyddare/-vårdare.
Kotimaisten kielten sanakirjassa myös: ympäristönsuojelija - aktiivisesti ympäristönsuojelun hyväksi toimivasta henkilöstä. - Ympäristöaktivisti - aktiivisesti toimivasta ympäristönsuojelijasta, ympäristöaktiivi. - Luonnonsuojelija - aktiivisesti luonnonsuojelun puolesta toimivasta henkilöstä.
Wikipedia:
Luonnonsuojelu on toimintaa, jonka tavoitteena on eliölajien, luontotyyppien,  luonnonkauneuden ja maisema-arvojen eli nk. luonnon säilyttäminen.
Ympäristönsuojelu: Ympäristönsuojelun tavoitteena on ratkaista, lievittää ja ennaltaehkäistä ympäristöongelmia. --Ympäristö rakentuu luonnonympäristöstä sekä rakennetusta ja sosiaalisesta ympäristöstä.
Ks. myös ELY-keskuksen määritelmät: https://www.ely-keskus.fi/ymparisto

**Comment by mirmaid** [comment]
^ Ei ympäristöaktivistit KÄ aktivistit, suppeammasta laajempaan viittauksista on enemmän haittaa kuin hyötyä. Mutta itse ehkä koen, että meillä on tårta på tårta -tilanne jos sanastossa on sekä _ympäristöaktivistit, ympäristöaktivismi_, että _luonnonsuojelijat_. Merkityskentät ovat niin päällekkäiset, että on vaikea keksiä mitä erottelua näillä johdonmukaisesti pystyttäisiin tekemään.

**Comment by AuHo22** [comment]
Suomen kielessä ainakin itselleni sana aktivistit tarkoittaa nimenomaan sitä joukkoa ihmisiä, jotka tsaarin vallan aikana vastustivat venäläistämispolitiikkaa, enkä haluaisi sanaa sotkea joka yhteyteen. Tarkennettuna se on ok kuten ihmisoikeusaktivistit, ja termi aktivismi on sitten käyttöalueeltaan jo laajempi. Mielestäni paras termi olisi ehkä kuitenkin ympäristöaktiivit, johon joukkoon on helppo lukea sitten myös rauhanomaista järjestötyötä tekevät eikä vain barrikadeille nousevat (konnotaatio on olemassa?). 
385/386-kenttien yleistyessäkin sanastoissa on jo olemassa se ongelma, ettei näitä -ismi-muotoisia termejä saisi käyttää niissä kentissä, mutta siinäkin on sitten kai pakollista harrastaa jonkin näköistä epäkorrektia aktivismia, kun ei saada termejä sanastoon. Tarvetta yhtä lailla vaikkapa erilaisten pamflettien/mielipidekirjoitusten kohdalla tälläkin aihealueella.

**Comment by mirmaid** [comment]
^ Pitäisikö siis muuttaa luonnonsuojelijat KÄ ympäristöaktiivit?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirjan mukaan ympäristöaktiivi = ympärsitöaktivisti:

ympäristöaktivisti
aktiivisesti toimivasta ympäristönsuojelijasta, **ympäristöaktiivi**. 
https://www.kielitoimistonsanakirja.fi/#/ymp%C3%A4rist%C3%B6aktivisti?searchMode=all

Jos halutaan luonnonsuojelijaa laajempi termi, voisiko se olla mahdollisesti ympäristönsuojelijat, kun YSOssa ympäristönsuojelu ST luonnonsuojelu? Nyt siis ympäristönsuojelijat KÄ luonnonsuojelijat, mutta voisiko kääntää toisinpäin?

Kielitoimiston sanakirja:

**ympäristönsuojelija**
aktiivisesti ympäristönsuojelun hyväksi toimivasta henkilöstä. 

**luonnonsuojelija**
aktiivisesti luonnonsuojelun puolesta toimivasta henkilöstä.

**Comment by AuHo22** [comment]
LT ympäristönsuojelijat/ympäristöaktiivit ST luonnonsuojelijat -> maailmallakin Saksan kansalliskirjasto ja LC:

LT Environmentalists ST Conservationists ja DNB LT Umweltschützer ST Naturschützer

Itselleni ero on niin selkeä, että en ymmärrä oikein dilemmaa.

**Comment by mariaforsen** [comment]
Luonnonsuojelija on mielestäni eri käsite kuin ympäristöaktivistit, enkä kannata sen poistoa tai yhdistämistä.  
https://www.sll.fi/luonnonsuojelija

**Comment by mirmaid** [comment]
On totta että sanastossa on sekä _ympäristönsuojelu_, että _luonnonsuojelu_, ja _ympäristö_ ja _luonto_ -sanojen voidaan perustella tarkoittavan tässä eri asioita. Mun olisi kyllä silti vaikea yrittää tehdä jotain erottelua _luonnonsuojelijat_ ja _ympäristönsuojelijat/ympäristöaktivistit_ -termien avulla, luultavasti laittaisin varmuuden vuoksi molemmat. Kiinnostaisi, millaisissa tapauksissa te, joille ero on selvä, käyttäisitte vain jompaa kumpaa?

**Comment by AuHo22** [comment]
Esim. Kurkikuiskaaja / Riitta Saarinen tai Nuoren luonnontutkijan päiväkirja / Dara McAnulty -> luonnonsuojelijat

Esim. Liikkuvia utopioita, hidastamisen politiikkaa : tutkimus nuorista liikkeessä ilmastokriisin ajassa / Mikko Piispa.
T[u]li on irti : maapallon polttava tulevaisuus / Naomi Klein -> ympäristönsuojelijat

**Comment by mariaforsen** [comment]
Tähän liittyen myös "Heräämisiä : kuinka minusta tuli luonnonsuojelija" / Juha Kauppinen. Sen kohdalla sopisi varmaan molemmat.

**Comment by mirmaid** [comment]
Sekä _Kurkikuiskaajan_, että _Nuoren luonnontutkijan päiväkirjan_ päähenkilöistä käytetään verkkosivuilla sanaa "luontoaktivisti". Ilmeisesti ongelma koetaan siis ennen muuta ilmastonsuojeluun liittyen.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa _ilmastoaktivistit_.

**Comment by mariaforsen** [comment]
Sv. klimataktivister
