### ISSUE TITLE
ulkoilmaopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4228]
#### Ehdotettu termi suomeksi

ulkoilmaopetus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 07.11.2014

**Muokkauspäivämäärä:** 07.11.2014

**Voyager-id:** 200981

**Termiehdotus Fintossa:** [ulkoilmaopetus](http://finto.fi/yse/fi/page/Y400981)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
