### ISSUE TITLE
elektroninen nenä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4232]
#### Ehdotettu termi suomeksi

elektroninen nenä
#### Ehdotetut ohjaustermit

diginenä, keinonenä, konenenä, sähköinen nenä
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)

**Luontipäivämäärä:** 15.01.2015

**Muokkauspäivämäärä:** 15.01.2015

**Voyager-id:** 201833

**Termiehdotus Fintossa:** [elektroninen nenä](http://finto.fi/yse/fi/page/Y401833)

**Comment by tarjaturunen** [comment]
Tätä tarvittaisiin sis.kuvailussa esim. e-kirja "Electronic Nose: Algorithmic Challenges" julkaisuvuosi 2018

**Comment by ilona-x** [comment]
FinMeSH: sähkönenä http://www.yso.fi/onto/mesh/D062609

**Comment by mirmaid** [comment]
Googlella käytetyimmältä vaikuttaa ehdotettu muoto, seuraavaksi yleisin olisi _keinonenä_ (jos poistaa samankaltaiset tulokset, keinonenä on jopa hiukan käytetympi).

**Comment by ilona-x** [comment]
Keinonenä vie ajatukset keinoelimiin. 🤔 FinMeSHissä ainoa keino-alkuinen KT-muoto on keinotekoinen haistaja.

**Comment by mariaforsen** [comment]
elektronisk näsa ET artificiell näsa, elektrisk näsa

**Comment by tpalonen** [comment]
Minä sain Google-tuloksiksi tällaista.
sähkönenä 1730
elektroninen nenä 3340
keinonenä 2320^
sähköinen nenä 628
diginenä 6

^ Huom! Keinonenää on kuitenkin käytetty jonkin verran muussakin merkityksessä, trakeostomian yhteydessä keinonenä on apulaite hengittämiseen.
Ks. https://trakeostomia.info/trakeostomia/hoito-ohjeet-trakeostomia

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa elektroninen nenä. Ohjaustermeiksi diginenä, keinonenä, konenenä, sähköinen nenä, sähkönenä.
