### ISSUE TITLE
ex situ -suojelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4265]
#### Ehdotettu termi suomeksi

ex situ -suojelu
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/ysa/ryhma_18)

**Luontipäivämäärä:** 21.04.2015

**Muokkauspäivämäärä:** 21.04.2015

**Voyager-id:** 203047

**Termiehdotus Fintossa:** [ex situ -suojelu](http://finto.fi/yse/fi/page/Y403047)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016 muodossa etäsuojelu.
