### ISSUE TITLE
LCHF

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4267]
#### Ehdotettu termi suomeksi

LCHF
#### Ehdotetut ohjaustermit

Low carb high fat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/ysa/ryhma_24)
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 21.04.2015

**Muokkauspäivämäärä:** 21.04.2015

**Voyager-id:** 203050

**Termiehdotus Fintossa:** [LCHF](http://finto.fi/yse/fi/page/Y403050)

**Comment by mirmaid** [comment]
Palaute: _Teiltä puutuvat esimerkiksi tällä hetkellä erittäin suositut LCHf-dieetti ja ketogeeninen dieetti. Toki ne ovat molemmat vähähiilihydraattisia ruokavalioita mutta ne ovat ennen kaikkea ruokavalioita, joissa pääpaino on hyvissä rasvoissa. Rasvaa syödään ketogeenisessa dieetissä vähintään 75 prosenttia kaikista makroravinteista. Eimerkkejä 978-1-936303-94-6, 978-1-628601-00-8, 978-91-1305101-7, 978-1-4735-4929-6 Olisi mukava jos asiasanastonne heijastelisi ajan henkeä..South Beachit ym ovat jo menneen talven lumia._

**Comment by mirmaid** [comment]
_Teillä on termi 'ketoosi' sanastossanne. Se on luokiteltu aineenvaihduntahäiriöihin. Sitä se ei todellakaan ole. Se on tila johon pyritään ketogeenisellä dieetillä. https://fi.m.wikipedia.org/wiki/Ketoosi_(tila)
https://www.adlibris.com/fi/kirja/parantava-ketoosi-9789522604859_

**Comment by mariaforsen** [comment]
Mesh:  Ravitsemus- ja aineenvaihduntasairaudet > Aineenvaihduntasairaudet > Happo-emästasapainohäiriö > Asidoosi > Ketoosi

**Comment by YSA-kokous** [comment]
LCHF-dieetti

**Comment by mariaforsen** [comment]
Sv. LCHF-diet ET LCHF-dieten, LCHF-kost
