### ISSUE TITLE
itsehoito-oppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4269]
#### Ehdotettu termi suomeksi

itsehoito-oppaat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)

**Luontipäivämäärä:** 21.04.2015

**Muokkauspäivämäärä:** 21.04.2015

**Voyager-id:** 203052

**Termiehdotus Fintossa:** [itsehoito-oppaat](http://finto.fi/yse/fi/page/Y403052)

**Comment by OutiHintikka** [comment]
Kaipaisin jälleen em. termiä. Ilmeisesti tätä ei ole otettu aiemmin ruotsalaisen termimuodon vuoksi.  Termi olisi tarpeellinen tietyntyyppisten täsmäongelmien (psyykkisten tai fyysisten) ennaltaehkäisyyn ja/tai hoitoon tarkoitetun aineiston kuvailussa. Teen parhaillaan teosta **Stressitohtori.** Tähän sopii kovin huonosti slm-termiksi 'elämäntaito-oppaat' (vaikka toki se laajassa mielessä on sitäkin), mutta esim. esimerkkiteos on hyvin ongelmakeskeinen ja konkreettisia neuvoja ongelmaan anatava. Samanlainen tilannen oli esim. teoksen kuvailun kohdalla, mikä käsitteli traumoista selviytymistä. Tähän ei kovin hyvin sopinut tuo elämäntaito-oppaat termi. Nyt näitä teoksia on kuvailtu aika usien elämäntaito-oppaat-termillä ja oppaat (teokset) -termillä.

**Comment by mariaforsen** [comment]
Sv. egenvårdsguider

**Comment by mirmaid** [comment]
Hyväksytty / SLM.

**Comment by YSO-kokous** [comment]
Hyväksytään myös YSOon.

Keskustelua, mikä on tämän suhde elämänhoito-oppaisiin. Ei varsinainen synonyymi.
