### ISSUE TITLE
entiset elämät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4276]
#### Ehdotettu termi suomeksi

entiset elämät
#### Ehdotetut ohjaustermit

aiemmat elämät
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)

**Luontipäivämäärä:** 21.04.2015

**Muokkauspäivämäärä:** 21.04.2015

**Voyager-id:** 203059

**Termiehdotus Fintossa:** [entiset elämät](http://finto.fi/yse/fi/page/Y403059)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016 muodossa **aiemmat elämät**.
