### ISSUE TITLE
kehotietoisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4281]
#### Ehdotettu termi suomeksi

kehotietoisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)

**Luontipäivämäärä:** 21.04.2015

**Muokkauspäivämäärä:** 21.04.2015

**Voyager-id:** 203064

**Termiehdotus Fintossa:** [kehotietoisuus](http://finto.fi/yse/fi/page/Y403064)

**Comment by Pan2345** [comment]
Kannatan. Itsekin kaipaisin juuri käsitettä teoksen Erica Hornthal: Body aware kuvailussa. 

Sanalle olisi käyttöä kehotietoisuutta käsittelevässä kirjallisuudessa. Millä muullakaan hakusanalla tiedonetsijät voisivat löytää aineistoa kehotietoisuudesta. Ruumiillisuus on liian laaja käsite, hakutuloksia tulisi liikaa ja aiheen ohi. Muitakin "tietoisuuksia" on YSO:ssa: historiatietoisuus, kielellinen tietoisuus, luokkatietoisuus, minätietoisuus, ympäristötietoisuus.

LCSH: https://id.loc.gov/authorities/subjects/sh88000621.html 
Terveyskirjasto: https://www.terveyskirjasto.fi/ltt04207 

Englanniksi: body awareness / somesthesia.

"Kehotietoisuus tarkoittaa kahta asiaa:

 1.) kehon anatomian tiedostamista sekä liikkeen, kuten esimerkiksi venytyksen, vaikutusta kehoon. 

2.) herkkyyttä tunnistaa kehon ja elimistön hienovaraisia viestejä ja tarpeita." 

https://www.piilotettupilvilinna.fi/kehotietoisuus/kehotietoisuus-mita-se-on-ja-miksi-se-on-tarkeaa/

Myös esim. https://www.terve.fi/artikkelit/tama-on-hyvan-itsetuntemuksen-perusta

**Comment by mirmaid** [comment]
7 viitettä Melindassa.

Lääketieteen termit: somatestesia: _somestesia | oman ruumiin aistiminen_

**Comment by mariaforsen** [comment]
Sv. kroppsförnimmelse HT kroppssensation, kroppsmedvetande (fysiologi), medvetenhet om kroppsförnimmelser? 

https://www.psykologiguiden.se/psykologilexikon/?Lookup=kroppssensation%2C+kroppsf%C3%B6rnimmelse

Ks. https://www.psykologiguiden.se/psykologilexikon?Lookup=kroppsmedvetenhet 

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_80b0e88c364c759664344172bc24a7a8&list_id=1&keyword=kehotietoisuus&word=kehotietoisuus
https://www.sanakirja.fi/custom/en-sv-fi/somesthesia

**Comment by LeKorsu** [comment]
Kannatan määritelmän/tarkenteen lisäämistä. Itse olisin sekoittanut heti: kehotietoisuudesta tulee minulle ensimmäiseksi mieleen juuri tuo Marian linkkaama psykologiguiden.se´n body consciousness eikä niinkään kehon anatomian tiedostaminen.

**Comment by ilona-x** [comment]
LCSH:
Somesthesia http://id.loc.gov/authorities/subjects/sh88000621
Variants
    Bodily sensation awareness
    Body consciousness
    Body sense
    Sense, Body
    Somaesthesia
    Somatesthesia
    Somatic sensation
    Somesthesis

**Comment by mirmaid** [comment]
somatestesia KT kehotietoisuus (fysiologia)
