### ISSUE TITLE
ekologinen teatteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4305]
#### Ehdotettu termi suomeksi

ekologinen teatteri
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[95 Teatteri. Tanssi](http://www.yso.fi/onto/ysa/ryhma_95)

**Luontipäivämäärä:** 22.04.2015

**Muokkauspäivämäärä:** 22.04.2015

**Voyager-id:** 203124

**Termiehdotus Fintossa:** [ekologinen teatteri](http://finto.fi/yse/fi/page/Y403124)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.

**Comment by OutiHintikka** [comment]
ok
