### ISSUE TITLE
soveltava teatteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4323]
#### Ehdotettu termi suomeksi

soveltava teatteri
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[95 Teatteri. Tanssi](http://www.yso.fi/onto/ysa/ryhma_95)

**Luontipäivämäärä:** 22.04.2015

**Muokkauspäivämäärä:** 22.04.2015

**Voyager-id:** 203143

**Termiehdotus Fintossa:** [soveltava teatteri](http://finto.fi/yse/fi/page/Y403143)

**Comment by henriyli** [comment]
Suljetaan tupla ehdotuksesta #2360

**Comment by OutiHintikka** [comment]
ok
