### ISSUE TITLE
perhepelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4329]
#### Ehdotettu termi suomeksi

perhepelit
#### Ehdotetut ohjaustermit

kokoperheen pelit, koko perheen pelit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)

**Luontipäivämäärä:** 21.05.2015

**Muokkauspäivämäärä:** 21.05.2015

**Voyager-id:** 203486

**Termiehdotus Fintossa:** [perhepelit](http://finto.fi/yse/fi/page/Y403486)

**Comment by mirmaid** [comment]
Ehdotettu uudestaan.

**Comment by mirmaid** [comment]
_Asiasana olisi hyvä lisä sellaisiin peleihin, joita voi pelata koko perheen kesken esim. muistipelit, Alias -pelien eri sovellukset yms. Peleihin, joissa iällä ei ole suurta merkitystä._

Ehkä siis tarvetta lähinnä SLM-terminä.

**Comment by mirmaid** [comment]
Hyväksytty/SLM

**Comment by mariaforsen** [comment]
Sv. familjespel
