### ISSUE TITLE
monilukutaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4345]
#### Ehdotettu termi suomeksi

monilukutaito
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)
[85 Kielitiede](http://www.yso.fi/onto/ysa/ryhma_85)

**Luontipäivämäärä:** 30.06.2015

**Muokkauspäivämäärä:** 30.6.2015, 27.10.2015

**Voyager-id:** 204062

**Termiehdotus Fintossa:** [monilukutaito](http://finto.fi/yse/fi/page/Y404062)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 2/2016.
