### ISSUE TITLE
oikeusgenetiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4347]
#### Ehdotettu termi suomeksi

oikeusgenetiikka
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/ysa/ryhma_15)
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)

**Luontipäivämäärä:** 30.06.2015

**Muokkauspäivämäärä:** 30.06.2015

**Voyager-id:** 204064

**Termiehdotus Fintossa:** [oikeusgenetiikka](http://finto.fi/yse/fi/page/Y404064)

**Comment by jtuohini** [comment]
Tarvetta olisi edelleen tälle, ks. esim. https://melinda.kansalliskirjasto.fi/byid/002168691, https://melinda.kansalliskirjasto.fi/byid/019096190 ja https://melinda.kansalliskirjasto.fi/byid/013464696.

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mirmaid** [comment]
"Forensic genetics" (?), https://www.duodecimlehti.fi/duo14881.

Lääketieteen termit: oikeusgenetiikka: oikeusperinnöllisyystiede | oikeusbiologian alue, joka on keskittynyt →DNA-tunnistamiseen ja äkkikuolemalle altistavien geenimuutosten etsimiseen

**Comment by mariaforsen** [comment]
Sv. rättsgenetik
https://termipankki.fi/tepa/fi/haku/r%C3%A4ttsgenetisk%20avdelning
https://www.sanakirja.fi/custom/all/oikeusgenetiikka

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
