### ISSUE TITLE
sateenkaarikirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4371]
#### Ehdotettu termi suomeksi

sateenkaarikirjallisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 27.10.2015

**Muokkauspäivämäärä:** 27.10.2015

**Voyager-id:** 205757

**Termiehdotus Fintossa:** [sateenkaarikirjallisuus](http://finto.fi/yse/fi/page/Y405757)

**Comment by mariaforsen** [comment]
Sv. regnbågslitteratur

**Comment by mirmaid** [comment]
KÄ queer-kirjallisuus
