### ISSUE TITLE
uusi julkinen hallinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4378]
#### Ehdotettu termi suomeksi

uusi julkinen hallinta
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/ysa/ryhma_71)

**Luontipäivämäärä:** 27.10.2015

**Muokkauspäivämäärä:** 27.10.2015

**Voyager-id:** 205764

**Termiehdotus Fintossa:** [uusi julkinen hallinta](http://finto.fi/yse/fi/page/Y405764)

**Comment by fantsby-m** [comment]
Termille olisi tarvetta taas. 
KT _uusi julkishallinta_. 
RT _uusi julkisjohtaminen_
EN _new public governance_. 

Tarvitaan esim väitöksessä: https://trepo.tuni.fi/handle/10024/130812.
Melindassa _"new public governance"_ sanahaulla seitsemän kertaa, _uusi julkinen hallinta_ viisi kertaa, _uusi julkishallinta_ kerran.

**Comment by mariaforsen** [comment]
Onko OT myös "uusi julkinen hallinto"? 

Sv. new public governance

**Comment by ilona-x** [comment]
Esimekiksi julkaisussa "Uusi julkinen hallinta, yhteistyö ja osallisuus sosiaali- ja terveyspalvelujen hankinnassa" kohdassa "Uusi julkinen hallinta käsitteenä ja regiiminä" on taulukko, jossa näiden kahden mallin  (uusi julkinen hallinta (NPG) & uusi julkinen johtaminen (NPM)) eroista https://urn.fi/URN:ISBN:978-952-343-380-9

**Comment by mirmaid** [comment]
^^ En oikein löydä ko. muotoa suomenkielisistä lähteistä.
