### ISSUE TITLE
vaativa erityinen tuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4379]
#### Ehdotettu termi suomeksi

vaativa erityinen tuki
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)

**Luontipäivämäärä:** 27.10.2015

**Muokkauspäivämäärä:** 27.10.2015

**Voyager-id:** 205765

**Termiehdotus Fintossa:** [vaativa erityinen tuki](http://finto.fi/yse/fi/page/Y405765)

**Comment by ilona-x** [comment]
Tälle termille olisi ollut käyttöä teoksen "Puheenvuoroja vaativasta erityisestä tuesta" kuvailussa. 

https://fi.wikipedia.org/wiki/Vaativa_erityinen_tuki

https://termipankki.fi/tepa/fi/haku/vaativa%20erityinen%20tuki

**Comment by mirmaid** [comment]
3 viitettä melindassa.

**Comment by mariaforsen** [comment]
Sv. krävande särskilt stöd
https://www.valteri.fi/sv/tjanster/fortbildning/bestallningsfortbildning/kravande-sarskilt-stod-satt-igang/
https://www.oph.fi/sv/utbildning-och-examina/vip-natverket-kravande-sarskilt-stod
