### ISSUE TITLE
disinformaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4387]
#### Ehdotettu termi suomeksi

disinformaatio
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 26.01.2016

**Muokkauspäivämäärä:** 26.01.2016

**Voyager-id:** 207073

**Termiehdotus Fintossa:** [disinformaatio](http://finto.fi/yse/fi/page/Y407073)

**Comment by jarmosaarikko** [comment]
Määritelmiä:
- **Misinformaatio** on tahattomasti tai tahallisesti levitettyä virheellistä, puutteellista tai valheellista tietoa. 
- **Disinformaatio** taas viittaa tahallaan tehtailtuun misinformaatioon.

Ensin mainittu ei ole sanastossa. Jälkimmäinen on YSO-käsite (ilman määritelmää): - http://www.yso.fi/onto/yso/p29444

Voisiko lisätä määritelmän: "Tahallaan tuotettu ja levitetty virheellinen, puutteellinen tai valheellinen tieto (misinformaatio)."
Erotuksena käsitteistä "[valeuutiset](http://www.yso.fi/onto/yso/p37799)" (fake news)  sekä "[valemedia](http://www.yso.fi/onto/yso/p37810)" (fake media).
katso myös 
- https://evaitaopiskeluun.fi/tiedonlahteet/mis-ja-disinformaatio/
- https://fi.wikipedia.org/wiki/Misinformaatio
- https://fi.wikipedia.org/wiki/Disinformaatio

Oikeastaan voisi YSOon lisätä misinformaation omana käsitteenään, sillä tahaton valeuutisten yms. levittäminen on yleistä ja tätä koskevaa aineistoa löytyy myös.  Edellisen perusteella disinformaatio olisi tämän alakäsite.
