### ISSUE TITLE
duot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4388]
#### Ehdotettu termi suomeksi

duot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)

**Luontipäivämäärä:** 26.01.2016

**Muokkauspäivämäärä:** 26.01.2016

**Voyager-id:** 207074

**Termiehdotus Fintossa:** [duot](http://finto.fi/yse/fi/page/Y407074)

**Comment by mirmaid** [comment]
MUSAssa huomautus: (1) Kahden laulajan tai soittajan muodostama esityskokoonpano ja (2) kahdelle soittimelle sävelletty tai niillä esitettävä sävellys.

Myös triot, kvartetot. Eri merkitykset olisi syytä huomioida sulkutarkenteilla. 

YSAssa näitä termejä ei toistaiseksi ole.

**Comment by ksornova** [comment]
Duoihin tms. oli tulossa seuraavat lisäykset:
 
duot (sävellykset)     LT sävellykset  Duets (LCSH:n vastaavuus)
duot (yhtyeet)          LT yhtyeet

**Comment by tpalonen** [comment]
YSAssa on jo "duetot", joka on päällekkäinen merkitykseltään tuon "duot (sävellykset)"-käsitteen kanssa. Molempia ei varmaan tarvita?

**Comment by ksornova** [comment]
Tarvitaan kyllä.
Duetot on kahdella **lauluäänellä** esitettävä sävellys.
Duot (sävellykset) on nykyisen musan määritelmän mukaan **kahdelle soittimelle** sävelletty tai niillä esitettävä sävellys.

**Comment by jtuohini** [comment]
Nimenomaan tästä on kysymys. Analogiana: "tertsetot" on laulumusiikkia, "triot (sävellykset)" soitinmusiikkia.

**Comment by tpalonen** [comment]
Ok. Jos näillä vielä olisi lyhyet määritelmät niin se voisi selventää maallikoille. Esim. Wikipedian mukaan duetto on "musiikkiteos, joka on sävelletty kahta esittäjää varten" ja englannin puolella duet "is a musical composition for two performers".

**Comment by jtuohini** [comment]
Jos omin selitysten teon tässä itselleni:
 
**duetot**
[89] Musiikki
Kahdelle lauluäänelle sävelletty tai sovitettu teos.
  LT  laulumusiikki

**duot (sävellykset)**
[89] Musiikki
Kahdelle soittimelle sävelletty tai sovitettu teos.
  LT  kamarimusiikki

**duot (yhtyeet)**
[89] Musiikki
Yhtye, joka muodostuu kahdesta esittäjästä.
  LT  yhtyeet

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by MUUSA-kokous** [comment]
Saisikohan tämä suljetun ehdotuksen tarpeettomana pois YSAn ja YSOn käsite-ehdotuksista Fintosta?
http://www.yso.fi/onto/ysa/Y407074
