### ISSUE TITLE
hermoverkko (biologia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4393]
#### Ehdotettu termi suomeksi

hermoverkko (biologia)
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/ysa/ryhma_15)

**Luontipäivämäärä:** 26.01.2016

**Muokkauspäivämäärä:** 26.1.2016, 26.01.2016

**Voyager-id:** 207079

**Termiehdotus Fintossa:** [hermoverkko (biologia)](http://finto.fi/yse/fi/page/Y407079)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin hermoverkot tätä varten: http://urn.fi/URN:ISBN:978-951-51-1397-9
ja http://urn.fi/URN:ISBN:978-951-51-1410-5

**Comment by mirmaid** [comment]
FinMeSH http://www.yso.fi/onto/mesh/D009415

LCSH: Neural networks (Neurobiology) http://id.loc.gov/authorities/subjects/sh93002348, Neural circuitry http://id.loc.gov/authorities/subjects/sh85091089

https://en.wikipedia.org/wiki/Neural_circuit

Lääketieteen termit: 1. _yhdessä (tiettyä tarkoitusta varten) aktivoituvien hermosolujen ryhmä_

**Comment by mariaforsen** [comment]
Sv. nervnät

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa _hermoverkot (biologia)_.
