### ISSUE TITLE
hyönteisten kasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4395]
#### Ehdotettu termi suomeksi

hyönteisten kasvatus
#### Ehdotetut ohjaustermit

hyönteistenhoito, hyönteistuotanto
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/ysa/ryhma_22)

**Luontipäivämäärä:** 26.01.2016

**Muokkauspäivämäärä:** 26.01.2016

**Voyager-id:** 207081

**Termiehdotus Fintossa:** [hyönteisten kasvatus](http://finto.fi/yse/fi/page/Y407081)

**Comment by mariaforsen** [comment]
Sv. insektsuppfödning?
