### ISSUE TITLE
informaatiovaikuttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4396]
#### Ehdotettu termi suomeksi

informaatiovaikuttaminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/ysa/ryhma_80)

**Luontipäivämäärä:** 26.01.2016

**Muokkauspäivämäärä:** 26.01.2016

**Voyager-id:** 207082

**Termiehdotus Fintossa:** [informaatiovaikuttaminen](http://finto.fi/yse/fi/page/Y407082)

**Comment by AuHo22** [comment]
propaganda-sanassa on pakostakin nykyaikana jo vähän vanhanaikaisuutta ; informaatiosodankäynti taas on liian vahva ilmaisemaan sitä, mistä asiassa on kysymys samoin kuin usein informaatiovaikuttamisessa voi olla kyse yhden osapuolen toiminnasta ; vaikuttaminen taasen on laaja yleiskäsite
->ryhmään 65 Valtio-oppi. Politiikka. Kansainvälinen politiikka
-monessakin yhteydessä tarvittu käsite, esim. Himanen: Länttä vai itää - Suomi ja geopolitiikan paluu

**Comment by AuHo22** [comment]
"Informaatiovaikuttaminen kuvaa käsitteenä pikemminkin yksittäisen osapuolen toimia, kun taas informaatiosodankäynti osapuolten välistä kamppailua edellä mainituin keinoin"(esim. wikipedia), eli on eri asia.
ks. määrittelyä esim. 
https://sananvapauteen.fi/artikkeli/2303

Jossain artikkeleista propaganda samaistettiin pitkälti disinformaatioon määritelmällisesti - sisältöjä, kun taas informaatiovaikuttaminen yhdistelmä keinoja? Puhtaita määritelmiä ei ehkä löydy...
http://politiikasta.fi/propagandan-ja-disinformaation-maarittelysta/

**Comment by satuniininen** [comment]
>  Suhteet termeihin disinformaatio, valeuutiset, valemedia ja propaganda pitäisi joka tapauksessa miettiä.

> Jossain artikkeleista propaganda samaistettiin pitkälti disinformaatioon määritelmällisesti 

Tämä tuntuu olevan ainakin osittain päällekkäinen _disinformaation_ kanssa. Käsitteistö on tuoretta ja määritelmät varmaankin vielä hieman elävät. Sanastoon on lyhyen ajan sisällä otettu aika paljon tämän aihepiirin käsitteitä, joten ehkä hetken aikaa voitaisiin odotella ja katsoa, miten määritelmät vakiintuvat.

Tietääkö kukaan, onko tälle vakiintunutta vastinetta englanniksi?

**Comment by AuHo22** [comment]
Täytynee sitten tyytyä käyttämään propaganda -termiä ilmiöstä yleisesti eri muotoineen, kun sitä kuitenkin tunnutaan yhtä lailla käytettävän?

**Comment by AuHo22** [comment]
https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/161512/VNK_11_2019_Informaatiovaikuttamisen%20vastaaminen_web.pdf
fi. informaatiovaikuttaminen
sv. informationspåverkan
eng. information influence activities

**Comment by mirmaid** [comment]
Melindassa 2 x informaatiovaikuttaminen, 2 x informaatiovaikutus. 749 x informaatiosodankäynti.

JUHOn määritelmä: _Toiminta, jossa informaatiota tuottamalla, muokkaamalla tai sen saatavuutta rajoittamalla muutetaan kohteen käsityksiä tai toimintaa informaatio- ja mielipideympäristön kautta [TSK]_

Wikisanakirja: _julkiseen mielipiteeseen, ihmisten käyttäytymiseen ja yhteiskunnan päätöksentekoon vaikuttamaan pyrkivä toiminta tietoa levittämällä_

**Comment by mirmaid** [comment]
_Propagandaan sanana liittyi paljon rasitteita ja siksi haluttiin luoda tilalle uusia käsitteitä. Mutta samalla yhteys vanhaan propagandatutkimukseen katkesi. Toki nyt tutkitaan informaatiovaikuttamista, psykologisia operaatioita tai puhutaan hybridiuhkista – koko ajan keksitään uusia käsitteitä. Minusta ne enemmän hämärtävät kuin valaisevat._ https://ydinlehti.fi/numero-2017-2/propagandan-lumo/

Ks. myös https://www.journalisti.fi/artikkelit/2017/14/vaikuttava-sana-sota/ :upside_down_face:

https://helda.helsinki.fi/bitstream/handle/10138/300180/Nissinen_Valtio-oppi.pdf

**Comment by AuHo22** [comment]
Pitäsikö tässä vaiheessa ko. käsitteissä erottaa sodankäynti turvallisuuspolitiikan/puolustusvoimien näkökulmasta ns. poliittisiin tms. tarkoitusperiin liittyvästä vaikuttamisesta? Esim.
https://www.doria.fi/bitstream/handle/10024/144308/Flyktman_JT_YEK58.pdf?sequence=1&isAllowed=y

"Käsiteanalyysin tuloksena informaatiosodankäynnin käsitteen alaa kavennettiin rajaamalla sen ulkopuolelle kybersodankäynti, disinformaatio, poliittinen vaikuttaminen, eriävän mielipiteen ilmaiseminen  sekä  taistelukentän  informaation  hyödyntäminen  sodankäynnistä -- Siksi kybersodankäynti kattaa useita sellaisia toimintoja, jotka eivät käsitteellisesti kuulu informaatiosodankäyntiin. Disinformaation ja valehtelun havaittiin olevan osa poliittista vaikuttamista,  joten  kaikki  disinformaatio  ei  voi  kuulua  informaatiosodankäynnin  käsitteen alle._" 

Myös  file:///C:/Users/u7184ah/AppData/Local/Temp/67730-Artikkelin%20teksti-82173-1-10-20171130.pdf
"Kybersodankäynnin  käsite  nousi  voimakkaasti  esille  vuosina  2008–2010. Se syrjäytti osin aikaisemmin käytetyn informaatiosodankäynnin käsitteen, joka oli muotoiltu 1990-luvun puolivälissä_." 
Artikkelissa lisäksi elektroninen sodankäynti lähikäsitteena, jotka kaikki osin päällekkäisiä, mutta onko mahdotonta laittaa LT/ST-suhteisiinkaan?

Tämänhetkinen YSOn määritelmä informaatiosodankäynnin kohdalla (viittaus v. 2000 tietoon) voisi olla yhtä hyvin kybersodankäynnin kohdalla?

**Comment by mirmaid** [comment]
SOTOssa _informaatiosodankäynnillä_ ei ole määritelmää. _Kybersodankäynti_-käsitettä ei ole SOTOssa lainkaan. Olisi kuitenkin valaisevaa saada SOTO-ylläpidon kanta informaatio- ja kybersodankäynnin määritelmäeroista.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
**informaatiosota**: pol. informaation tarjonta omia tavoitteita edistävällä ja vastapuolta vahingoittavalla tavalla.
**propaganda**: mielipiteenmuokkaukseen tähtäävä oppien, asenteiden t. ajatusten levittäminen. 
**hybridisota**: aseellisen sodankäynnin ja eril. aseettomien vaikutuskeinojen yhdistelmästä. _Propaganda ja verkkohyökkäykset hybridisodan välineinä._

**Comment by mirmaid** [comment]
Sanastossa siis _informaatiosodankäynti, disinformaatio, vaikuttaminen, propaganda_. Päätetään kokouksessa äänestyksellä, otetaanko näiden lisäksi vielä _informaatiovaikuttaminen_. 

https://github.com/Finto-ehdotus/YSE/issues/4396#issuecomment-721114773

**Comment by mirmaid** [comment]
Kysytään SOTOn ylläpidolta määritelmiä _informaatiosodankäynnille_ ja _kybersodankäynnille_ - jälkimmäinen tosin puuttuu SOTOsta.

**Comment by AuHo22** [comment]
Kielitoimiston sanakirja ei välttämättä ole yo. aiheitten paras asiantuntija ja voi kysyä, kuinka ajantasaisia heidän määritelmänsä oikein ovatkaan, esim. termiä kybersota/-sodankäynti sanastossa ole ollenkaan. Sanakirjan taustasta heidän verkkosivuillaan:
Kielitoimiston sanakirja on uusittu ja laajennettu versio Suomen kielen perussanakirjasta (1990–1994) ja CD-Perussanakirjasta (1997). Perussanakirja puolestaan oli ensimmäinen suuri suomen kielen sanakirja Nykysuomen sanakirjan (1951–1961) jälkeen. 

Kysyn sitten niin päin, että kuinka sitten pitäisi kuvailla yo. Valtioneuvoston opas Informaatiovaikuttamiseen vastaaminen? Mielestäni Suomi ei kuitenkaan ole informaatiosodassa esimerkiksi Venäjän kanssa, vaikka heillä on Suomeenkin päin informaatiovaikuttamista, mutta tilanne ei toimi toisin päin? Onko tämä sitten propagandaa vai mistä on kysymys? Sitten haluaisin edes ohjauksen informaatiovaikuttaminen -termistä propagandaan. Ja eikö disinformaatio samoin kuin valeuutiset ole propagandan ST? Lainaus alla:

"Tässä oppaassa informaatiovaikuttamisella tarkoitetaan toimintaa, jolla pyritään järjestelmällisesti vaikuttamaan yleiseen mielipiteeseen, ihmisten käyttäytymiseen ja päätöksentekijöihin sekä sitä kautta yhteiskunnan
toimintakykyyn. Vaikuttamisen keinoja ovat esimerkiksi väärien tai harhaanjohtavien tietojen levittäminen ja
painostaminen sekä sinänsä oikean tiedon tarkoitushakuinen käyttö. Kyse on strategisesta toiminnasta, jonka
tavoitteena on saada kohde tekemään itselleen haitallisia päätöksiä ja toimimaan omaa etuaan vastaan."

**Comment by jarmosaarikko** [comment]
@AuHo22 tuo kuulostaa niin indoktrinaatiolta, mutta se onkin YSOssa ohjausterminä kolmelle (!) käsitteelle: 
- indoktrinaatio → manipulaatio
- indoktrinaatio → suostuttelu
- indoktrinaatio → vaikuttaminen  KT kansalaisvaikuttaminen, vaikutusmahdollisuudet

Lisäisin tuon ohjaustermiksi:  [manipulaatio](http://www.yso.fi/onto/yso/p5616) KT informaatiovaikuttaminen

**Comment by AuHo22** [comment]
Informaatiovaikuttaminen on kyllä jo eri tiedonalueilla liikkuva termi kuin manipulaatio:
https://fi.wikipedia.org/wiki/Manipulointi
https://fi.wikipedia.org/wiki/Psykologinen_manipulointi

Indoktrinaation ja viestinnän suhteesta sitten myös:
https://fi.wikipedia.org/wiki/Indoktrinaatio
Indoktrinaatio tiedotusopissa:
Kasvatustieteestä indoktrinaatio-termi levisi tiedotusoppiin. Siellä indoktrinaatio (ujuttaminen, mieleen iskostaminen, aatteeseen saattaminen, uskotus) on sanoman tuottajan vaikuttamaan pyrkivää viestintää, jossa viestinnän kohde ei tiedosta olevansa vaikutuksen kohteena. Mikäli viestinnän kohteelle paljastuu, että häneen on yritetty vaikuttaa, muuttuu indoktrinaatio hänen kannaltaan propagandaksi.
Kun lukijoiden, katselijoiden ja kuulijoiden tiedot ja lähdekritiikki kehittyvät, yhä suurempi osa indoktrinaatioksi tarkoitetusta vaikuttamisesta muuttuu vastaanottajan kannalta propagandaksi, koska hän tiedostaa vaikutusyrityksen.
Indoktrinaatiota voidaan toteuttaa objektiivisesti sääntelemällä uutisvirtaa ja uutispainotuksia joukkotiedotusvälineissä. Kun asiasta tuotetaan uutisia valikoimalla riittävän yksipuolinen kuva, alkaa yleinen mielipide muodostua halutun kaltaiseksi, vaikkei käytettäisi propagandan menetelmiä.

**Comment by mirmaid** [comment]
Melindassa nyt vuoden kuluttua (https://github.com/Finto-ehdotus/YSE/issues/4396#issuecomment-721114773) edelleen 2 x informaatiovaikuttaminen, 2 x informaatiovaikutus. Informaatiosodankäynti nyt 790 kertaa.

**Comment by mirmaid** [comment]
Vaihtoehtoja:
1) jätetään termiehdotukseksi, ei toimenpiteitä
2) otetaan informaatiovaikuttaminen
3) informaatiovaikuttaminen KÄ propaganda, disinformaatio, vaikuttaminen

Mitä mieltä Aulin ehdotuksesta _disinformaatio, valeuutiset_ YK _propaganda_?

Huom. Tätä ehdotusta ei enää seuraavaan kokoukseen, vaan sovitaan jokin ratkaisu.

**Comment by AuHo22** [comment]
Englanninkielisissä teksteissä näkee ilmaisua Russian propaganda, jolla viitataan esim. informaatiosodankäyntiin Ukrainassa (varsinaista aseellista konfliktiakin), mm.
https://id.loc.gov/resources/works/18799164.html
Myös vaalivaikuttamisen yhteydessä, esim. https://www.opensecrets.org/news/2021/10/russia-pouring-millions-into-russian-foreign-influence-kremlin-propaganda-targeting-the-us/
Myös suomenkielinen wikipedia-> https://fi.wikipedia.org/wiki/Ven%C3%A4j%C3%A4n_propaganda

Informaatiosodankäynti LCSH:ssa jo Military art and science -termin ST ; näyttäisi siltä, että Melindan tietueissakin osin käytetty informaatiosodankäynti-termiä silloin, kun kyse oikeastaan on informaatiovaikuttamisesta eli sopivamman termin puuttuessa. Propaganda-termin LT:t:
Communication in politics
Political psychology
Social influence

**Comment by mariaforsen** [comment]
Olisiko mahdollisesti informaatiovaikuttaminen KÄYTÄ informaatiosodankäynti? Ks. https://fi.wikipedia.org/wiki/Informaatiosodank%C3%A4ynti

Ks. myös https://www.doria.fi/bitstream/handle/10024/144308/Flyktman_JT_YEK58.pdf?sequence=1&isAllowed=y missä pohditaan tarkemmin näitä käsitteitä ja niiden rajaamista, esim.
"Informaatiovaikuttamisen käsitettä käytetään todennäköisesti myös siitä syystä, että siinä poistuu ongelmallinen yhdyssanan perusosa eli sodankäynti tilanteessa, jossa valtiot eivät käy sotaa, vaan kamppailevat vallasta. Informaatiovaikuttaminen on erityisesti suomenkielisessä keskustelussa yleisesti esiintyvä termi, mutta englanninkielisessä keskustelussa se vaikuttaa olevan suhteellisen harvinainen"

"Esimerkiksi informaatiokampanjoilla, informaatiovaikuttamisella ja informaatiotoiminnoilla viitataan samaan toimintaan kuin tässä tutkimuksessa määritellyllä informaatiosodankäynnillä eli käsityksiin vaikuttamiseen. Kuitenkin joissain tutkimuksissa informaatiosodankäynnillä viitataan toimintaan, jota tämän tutkimuksen käsitejärjestelmässä kutsuttaisiin kybersodankäynniksi."

**Comment by AuHo22** [comment]
Voisin ehdottaa, että otetaan 
informaatiosodankäynti KÄ kybersodankäynti
informaatiosodankäynti KÄ informaatiovaikuttaminen

Suomessa ei ehkä haluta käyttää propaganda-termiä sen mustavalkoisuuden takia toisin kuin se ehkä englanninkieliseen kulttuuripiiriin on vakiintunut, ja toisaalta informaatiovaikuttamisessa on hienovaraisempiakin muotoja kuin räikeämpi propaganda.

**Comment by mirmaid** [comment]
Sanastossa myös _vaikuttaminen_ (7005 kertaa Melindassa) - vaikuttaminen + Venäjä 173 kertaa, propaganda + Venäjä 609 kertaa, informaatiosodankäynti + Venäjä 176 kertaa.

**Comment by mariaforsen** [comment]
Tässä TSK:n sanastossa **https://www.tsk.fi/tiedostot/pdf/Kyberturvallisuuden_sanasto.pdf**  nämä kaikki (informaatiovaikuttaminen, informaatiosodankäynti, kybersodankäynti) ovat erillisiä käsitteitä. Siinä määritellään:

"informaatiosodankäynti=vihamielinen vaikuttaminen valitun kohteen päätöksentekoon, toimintakykyyn ja mielipiteisiin informaatioympäristön kautta sekä suojautuminen toisten vastaavilta vaikuttamisyrityksiltä"

"kybersodankäynti=tietoverkkoja ja niiden haavoittuvuuksia hyödyntävä, valtioiden välinen vihamielinen toiminta"  

Eli meidän ei pitäisi varmaan ainakaan sekoittaa keskenään kyber/informaatio. 

Informaatiovaikuttamisen kohdalla lukee myös: "Englanninkielisten termien käyttö ei ole vakiintunut. Anglosaksisessa maailmassa myös informaatiovaikuttamisesta käytetään laajasti termejä "information warfare" ja "information war", mutta Suomessa pyritään yleensä tekemään ero sodankäynnin ja vaikuttamisen välillä."

Tämän mukaisesti kannatan sitä että joko otetaan informaatiovaikuttaminen erikseen tai lisätään KÄYTÄ informaatiosodankäynti.

**Comment by mirmaid** [comment]
Englanniksi _information operations_, mutta Googlella mm. "synonymous with cyberwarfare" ja jos ei suoraa sodankäyntiä niin näyttää olevan nimenomaan maanpuolustukseen liittyvää.

**Comment by AuHo22** [comment]
Jos ohjausterminä, niin sitten mieluummin informaatiovaikuttaminen KÄ propaganda
Kannatan kuitenkin viime kädessä omana terminä ottamistaan, koskapa yksimielisyyttä ei tunnu merkityksistä löytyvän.

**Comment by AuHo22** [comment]
Termi jäi ensimmäisen kerran pöydälle käännöksen takia, ja tuolloin itselleni tuli vastaan ensin information operations, jonka kuitenkin katsoin kuuluvan military operations -luokkaan, eli sodankäyntiin. Information influencing / information influence activities / influence campaigns käännöstä on myös, joka ilmaisee myös termin laajempia merkityksiä.

**Comment by YSO-kokous** [comment]
### Päätölkset äänestyksen jälkeen
Otetaan sanastoon informaatiovaikuttaminen
Määritelmät: https://termipankki.fi/tepa/fi/haku/informaatiovaikuttaminen
Mutetaan YSOn informaatiosodankäynti määritelmä/käyttöhuomautus

**Comment by mariaforsen** [comment]
Sv. informationspåverkan https://termipankki.fi/tepa/fi/haku/informaatiovaikuttaminen
