### ISSUE TITLE
metsänpeitto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4410]
#### Ehdotettu termi suomeksi

metsänpeitto
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/ysa/ryhma_50)

**Luontipäivämäärä:** 28.01.2016

**Muokkauspäivämäärä:** 28.01.2016

**Voyager-id:** 207140

**Termiehdotus Fintossa:** [metsänpeitto](http://finto.fi/yse/fi/page/Y407140)

**Comment by krinay** [comment]
Käsite on KULOssa, jota ollaan irrottamassa KOKOsta. Sitä tuntuu olevan mahdotonta uudelleenohjata järkevästi mihinkään olemassa olevaan YSO-käsitteeseen.

Termiä ei ole toistaiseksi käytetty kovin usein sisällönkuvailussa, mutta silloin kun julkaisu käsittelee nimenomaan tätä suomalaisen kansanuskon ja kertomusperinteen ilmiötä, on aihetta vaikea kuvata millään muulla sanalla.

Temaattinen ryhmä: 50 Kansanperinne...

englanniksi: forest covering
ruotsiksi: skogstagning 
(Metsänpeitto/skogstagning tunnetaan myös suomenruotsalaisessa perinteessä. Ruotsalaisessa perinteessä samantapainen ilmiö on nimeltään bergtagning.)
