### ISSUE TITLE
orientaaliortodoksiset kirkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4417]
#### Ehdotettu termi suomeksi

orientaaliortodoksiset kirkot
#### Ehdotetut ohjaustermit

idän skismaattiset kirkot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)

**Luontipäivämäärä:** 28.01.2016

**Muokkauspäivämäärä:** 28.01.2016

**Voyager-id:** 207147

**Termiehdotus Fintossa:** [orientaaliortodoksiset kirkot](http://finto.fi/yse/fi/page/Y407147)

**Comment by jtuohini** [comment]
Ohjaustermi tarvitaan edelleen Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä!

**Comment by YSO-kokous** [comment]
Hyväksytään: KT idän skismaattiset kirkot
