### ISSUE TITLE
saamelaiskirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4418]
#### Ehdotettu termi suomeksi

saamelaiskirjallisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 28.01.2016

**Muokkauspäivämäärä:** 28.01.2016

**Voyager-id:** 207148

**Termiehdotus Fintossa:** [saamelaiskirjallisuus](http://finto.fi/yse/fi/page/Y407148)

**Comment by MikkoAleksanteri** [comment]
Palautetta Rovaniemeltä:

_Saamelaiskirjallisuus-termiä käytetään vakiintuneesti esim. saamelaisen erikoiskirjaston kokoelmatyössä tarkoittamaan kaikkea saamelaista (usein arkikielessä kauno)kirjallista toimintaa. Termi kattaa saamelaisaiheisen, -kielisen ja saamelaisten toimesta tehdyn kauno- ja tietokirjallisen julkaisutuotannon, mukaan lukien käännökset. Kieli ei ole tässä ainoa rajaus vaan aihe ja tekijän etnisyys yhtä lailla. Jos saamelainen kirjoittaa suomeksi syystä tai toisesta, hänen tuotos on saamelaiskirjallisuutta vaikkakaan ei saamenkielistä kirjallisuutta._

**Comment by mirmaid** [comment]
Samankaltainen kuin _suomenruotsalainen kirjallisuus_

**Comment by mariaforsen** [comment]
Sv. samisk litteratur ET samelitteratur
Allärs: samisk litteratur=saamenkielinen kirjallisuus > litteratur på samiska ET samiskspråkig litteratur

**Comment by jarmosaarikko** [comment]
saamenkielinen kirjallisuus voi olla muutakin kuin saamelaiskirjallisuutta, esim. käännösteokset. Eli eri käsite.
