### ISSUE TITLE
kesäkisat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4436]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[kesäkisat](http://www.yso.fi/onto/yso/p18499)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Preflabel muotoon kesäolympialaiset. Kesäkisat altlabeliksi.  
#### Perustelut ehdotukselle

Kesäkisat voi terminä tarkoittaa mitä tahansa kisoja. Kuitenkin käsite viittaa pelkästään olympialaisiin.  
#### Ehdottaja

Tuomas Palonen  
#### Ehdottajan organisaatio

KK  
#### Ehdottajan sähköpostiosoite

tuomas.palonen@helsinki.fi

**Comment by tpalonen** [comment]
No nyt on kova ehdotus! Kannatan!

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: kesäkisat: tav. kesäolympialaiset

Googlaamalla tulee toki hauskaa matskua. http://kesakisat.blogspot.fi/

Kesäolympialaiset ei kyllä taida käydä teoksen _Pupu Tupuna: Metsolan kesäkisat_ kuvailuun...(Kaunokki-termi tietueessa)

**Comment by LeKorsu** [comment]
Minun on pitänyt lähettää termiehdotus arvokisat, mutta olen unohtanut (tarvittu Urheilusanomien indeksoinnissa artikkeliin, joka käsitteli urheilijoiden apurahoja ja tuloksia arvokisoissa). Se voisi käydä yläkäsitteeksi kesäkisoille, talvikisoille, olympialaisille, maailmanmestaruuskisoille. Sorry uusi termiehdotus näin viime tipassa. Enkä kyllä tiedä ratkaiseeko se tätä ehdotusta.

**Comment by tpalonen** [comment]
Kiitos huomiosta @LeKorsu ! Voitko vielä tehdä erillisen virallisen termiehdotuksen tuosta arvokisat-käsitteestä alla olevassa osoitteessa? 
http://ehdotus.finto.fi

Ehdotusjärjestelmän ajatuksena on, että jokaisesta termistä tehtäisiin oma ehdotuksensa tuon yllä mainitussa osoitteessa olevan lomakkeen avulla. Täällä Githubissa keskustelun lomassa mainitut ehdotukset hukkuvat helposti muun keskustelun lomaan.

**Comment by LeKorsu** [comment]
Yritin juuri lähettää, mutta lomake ei anna mitään merkkejä, että ehdotus olisi lähtenyt eteenpäin. Olen mielestäni täyttänyt kaikki pakolliset kentät (pahoittelut, jos se on tullut moninkertaisesti).

**Comment by tpalonen** [comment]
@LeKorsu Ilmeisesti nämä ehdotukset eivät ole tulleet perille asti valitettavasti. Kun ehdotuksen lähettää, selaimen pitäisi siirtyä takaisin ehdotuslistaan, jossa lähettämäsi ehdotus pitäisi näkyä ylimpänä. Voitko vielä kuvailla mitä teet (esim. millä selaimella ehdotuksen teet), mitä tapahtuu kun klikkaat "Lähetä ehdotus" ja lähettää kuvauksen meille osoitteeseen finto-posti@helsinki.fi niin voimme selvittää ongelmaa ja jatkaa keskustelua sähköpostitse?

**Comment by LeKorsu** [comment]
Hoksasin missä oli vika, tarjosin liikaa termejä ST-kenttään, se näyttää hyväksyvän vain yhden. Äsken lähti ehdotus.

**Comment by tpalonen** [comment]
Kiitos tiedosta @LeKorsu ! Hyvä, että ehdotus meni perille! Ja tämä on myös tärkeää tietoa meille. Pyrimme kehittämään järjestelmää, jotta ehdotusten teko olisi helpompaa ja järjestelmä antaisi jatkossa paremmin palautetta käyttäjille, mikäli ongelmia ilmenee.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
