### ISSUE TITLE
talvikisat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4437]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[talvikisat](http://www.yso.fi/onto/yso/p10917)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Preflabel muotoon talviolympialaiset. Talvikisat altlabeliksi.  
#### Perustelut ehdotukselle

Talvikisat voi terminä viitata mihin tahansa kisoihin. Käsite kuitenkin viittaa vain olympialaisiin.  
#### fromname

Tuomas Palonen  
#### fromorg

KK  
#### fromemail

tuomas.palonen@helsinki.fi

**Comment by tpalonen** [comment]
Loistelias ehdotus! Täysi tuki tälle!

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
