### ISSUE TITLE
näytöt (tutkintosuoritukset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4438]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[näytöt (tutkintosuoritukset)](http://www.yso.fi/onto/yso/p4202)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Onko todellista eroa käsitteeseen näyttökokeet? Ehdotetaan käsitteiden yhdistämistä.  
#### Perustelut ehdotukselle

Ruotsiksi ei eroa käsitteillä. Kuvailijankin voi olla vaikea tehdä eroa. Kielitoimiston sanakirja näyttäsi olevan vain yhden käsitteen kannalla.  
#### fromname

Mikko Lappalainen  
#### fromorg

Kansalliskirjasto  
#### fromemail

mikko.lappalainen@helsinki.fi

**Comment by mirmaid** [comment]
Nykyinen huomautus termissä näyttökokeet: Näyttökoe ja näyttö ovat lähekkäisiä käsitteitä. Näyttökokeesta saa todistuksen, näytöstä ei. Näytöt ovat osa ammatilllisen koulutuksen opetusprosessia.

Jos yhdistetään, jäisi varmaankin laajempi näytöt (tutkintosuoritukset) -termi?

**Comment by LeKorsu** [comment]
Muistaakseni tätä pähkäiltiin jossakin kokouksessa  aika pitkään, kun pidettiin tarpeellisena tuoda esille tuo huomautuksessa mainittu ero. En muista, osasinko silloin ottaa kantaa, mutta tuntuu siltä, että taas veivattaisiin takaisin jotain, josta on parin vuoden sisällä sovittu, jos tämä nyt yhdistetään.

**Comment by mirmaid** [comment]
näyttökokeet KÄ näytöt (tutkintosuoritukset)
