### ISSUE TITLE
työleirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4439]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[työleirit](http://www.yso.fi/onto/yso/p20323)  
#### Tila

Käsittelyssä  
#### Perustelut ehdotukselle

Todettu YSO-kokouksessa että YSA:ssa ovat termin leirit alakäsitteet:
    kesäleirit
    musiikkileirit
    perheleirit
    Prometheus-leirit
    rippikoululeirit
    tiedeleirit
    työleirit

Työleirit on kuitenkin Melindassa käytetty todella paljon nimenomaan pakkotyöleirit-merkityksessä... Ks. MOT. Pitäisi määrtellä mihin työleirit-asiasanalla viitataan (mahdollisesti jakaa?), ehkä lisätä huomautus ja siirtää johonkin muualle hierarkiassa? Ruotsiksi ja englanniksi nyt nimenomaan "pakkotyöleiri"-merkityksessä.  
#### Ehdotettu muutos

Merkitys määritelty ja niin että myös ruotsin termi (sekä käännös englantiin) täsmää.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: työleiri: 1. aatteellisen tms. yhteisön järjestämä leiri, jossa tehdään vapaaehtoista työtä. Nuorten kansainvälinen työleiri. 2. = pakkotyöleiri

Suurin osa Melindan viitteistä käsittelee pakkotyöleirejä, ja termi voisi varmaankin olla pakkotyöleirit. Jos toiselle tarvitaan tarkenne sen lisäksi että toiseen tehtäisiin ohjaus työleirit (pakkotyö) KÄ pakkotyöleirit, se voisi mahd. olla työleirit (vapaaehtoistyö).

**Comment by LeKorsu** [comment]
Kannatan sitä, että työleirien merkitystä tarkennetaan. Pakkotyöleirit on kuitenkin korvattu termi  > KÄ vankileirit.  Kävisikö työleirit (pakkotyö/vankeus) KÄ vankileirit?

**Comment by mirmaid** [comment]
työleirit (pakkotyö) KÄ vankileirit
työleirit (vapaaehtoistyö)

**Comment by vthuhtala** [comment]
YSAssa ei saa käyttää sanaa 'työleirit', vaan YSA ohjaa käyttämään termejä 

työleirit (pakkotyö) -> vankileirit 
http://finto.fi/ysa/fi/page/Y100073

työleirit (vapaaehtoistyö)
http://finto.fi/ysa/fi/page/Y104701

Mutta miten sitten pitäisi sisällönkuvailla esimerkiksi teos 'Jatkosodan aikaisten erikoistyöleirien organisointi'? https://helka.finna.fi/Record/helka.2470986

- kyseessä ei ole vankileiri, koska "asukit" eivät ole vankeja;
- toisaalta kyseessä ei ole myöskään vapaaehtoinen työleireily, sillä työvelvoite tuli lainsäädännöstä

Lisäksi: vankileirin ei tarvitse olla (pakko)työleiri

Eli pitäisikö työleiri palautta merkityksessä 'työleirit (pakkotyö)' ja samalla poistaa korvattavuus termille 'vankileirit'?

työleirit 
-> työleirit (vapaaehtoistyö)
-> työleirit (pakkotyö)

ass. suhde: vankileirit
