### ISSUE TITLE
induktio -- filosofia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4458]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[induktio -- filosofia](http://www.yso.fi/onto/ysa/Y106396)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Muutetaan termi muotoon "induktiivinen päättely". Lisätään huomautus: "Yleisen tosiasian päätteleminen yksityistapauksista."  
#### Perustelut ehdotukselle

Sekaantumisen riski muihin induktio-alkuisiin vähenee. Induktiivistä päättelyä voidaan hyödyntää muuallakin kuin filosofiassa. Wikipedia käyttää muotoa "induktiivinen päättely" (sekä suom. että engl.). Käsitteen yläkäsite YSOssa on "päättely". "Induktiivinen päättely" tuottaa Googlen kautta enemmän osumia kuin "induktio filosofia". Muutoksen avulla pääsemme eroon ketjusta, ilman että joutuisimme tekemään käsitteelle sulkutarkennetta.  
#### Ehdottajan nimi

Mikko Lappalainen  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

mikko.lappalainen@helsinki.fi

**Comment by mirmaid** [comment]
Induktio -- fysiikka jaettaneen vielä kahdeksi, mutta eivät sen jälkeen ala induktio-sanalla. En usko että mitään sekaantumisen vaaraa jää. Päättelyn alakäsitteinä on lisäksi abduktio ja deduktio.

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 14.9.2016)
