### ISSUE TITLE
ilmiöpohjainen oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4467]
#### Ehdotettu termi suomeksi

ilmiöpohjainen oppiminen  
#### Vaihtoehtoiset termit ja ilmaisut

ilmiölähtöinen oppiminen, ilmiöoppiminen, ilmiölähtöisyys  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)  
#### neededfor

Ilmiömäinen musiikki  
#### Ehdottajan nimi

Kansalliskirjasto  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi  
#### Perustelut ehdotukselle
-  

**Termiehdotus Fintossa:** [ilmiöpohjainen oppiminen](http://finto.fi/yse/fi/page/Y504467)

**Comment by mirmaid** [comment]
Ehdotettu myös _ilmiöpohjainen opetus_

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 14.9.2016)

**Comment by tpusa** [comment]
Kaipasin tätä termiä kuvaillessani julkaisua "Satavuotiaan Suomen digiloikka Kalevankankaalle ja Lenin-museoon Tampereella", ISBN 978-952-68326-7-8.
