### ISSUE TITLE
kyberrikollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4474]
#### Ehdotettu termi suomeksi

kyberrikollisuus  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)  

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)  
#### neededfor

Cybersecurity and cybercrime in the 21st century  
#### Perustelut ehdotukselle

Tietoverkkorikokset eivät mielestäni täysin vastaa tätä.  
#### Ehdottajan nimi

Kansalliskirjasto  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi  

**Termiehdotus Fintossa:** [kyberrikollisuus](http://finto.fi/yse/fi/page/Y504474)

**Comment by mirmaid** [comment]
HYK kommentoi: Helkasta löytyy 40 tietuetta, josta löytyy eri kentistä merkkijono 'cyber crim?'. Kyseessähän on kehittyneen tietotekniikan mukanaan tuoma lieveilmiö, josta julkisuudessa meillä puhutaan hyvin usein.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Cybercrime

**Comment by ilona-x** [comment]
"Kyberrikollisuus voidaan jaotella tietokoneavusteisiin rikoksiin ja varsinaisiin tietotekniikkarikoksiin. Jaottelulle ei ole olemassa vakiintuneita suomenkielisiä termejä, siksi tämän artikkelin jaottelu voi poiketa aiemmin esitetyistä luokitteluista.

1) **Tietokoneavusteistet rikokset** ovat "perinteisiä" rikoslakirikoksia kuten verkon markkinapaikoilla tehdyt petokset, sosiaaliset median kunnianloukkaukset ja muut sellaiset teot, joissa rikoksen tunnusmerkistön täyttyminen ei edellytä tietokoneen käyttämistä. Etenkin verkon markkinapaikat tarjoavat otollisen keinon huijata vähällä vaivalla suurta määrää ihmisiä. Poliisin arvion mukaan vuosina 2014-2015 jo yli puolet petosrikoksista tapahtuu verkossa. Myös parisuhteissa ilmeneviin rikoksiin ja riitoihin saattaa liittyätietokoneavusteista rikollisuutta, kun mustasukkainen puoliso tunkeutuu toisen sähköisille tileille ja tarkkailee luvatta toisen osapuolen viestintää. Puolison sähköisten tilien luvaton käyttö on rikos.

2) **Tietotekniikkarikokset** tapahtuvat vain tietoteknisessä ympäristössä. Tällaisia ovat muun muassa tietomurto tai tietoliikenteen häirintä, esimerkiksi palvelunestohyökkäys. Tietotekniikkarikoksissa rikos tapahtuu tietoteknisessä ympäristössä ja kohdistuu tietoverkon infrastruktuuriin tai siihen liitettyihin laitteisiin. Usein näissäkin rikoksissa on motiivina taloudellisen edun tavoittelu, mutta myös poliittiset motiivit sekä puhdas vandalismi motivoivat tekijöitä."

Lähde: https://www.viestintavirasto.fi/kyberturvallisuus/tietoturvanyt/2015/05/ttn201506031327.html

Tähän liittyviä termejä YSA:ssa:

**atk-rikokset
tieto- ja viestintärikokset
tietotekniikkarikokset
tietoverkkorikokset
tietomurto
hakkerointi
identiteettivarkaus
verkkourkinta
verkkohyökkäykset**

LCSH:
cyber crimes -> computer crimes
http://id.loc.gov/authorities/subjects/sh85029492

**Comment by Elmukelmu** [comment]
Oikein tarpeellinen, kannatetaan!

**Comment by mariaforsen** [comment]
Ainakin osittain päällekkäinen nykyisten Allärs-termien kanssa, eli ongelmallinen.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016) KT tietotekniikkarikollisuus
