### ISSUE TITLE
rumpurakenteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4487]
#### Ehdotettu termi suomeksi

rumpurakenteet  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/ysa/ryhma_37)  
#### Perustelut ehdotukselle
-  
#### Ehdottajan nimi

Kansalliskirjasto  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi  
#### Tarkoitusta täsmentävä selite

Kattaa tierummut, holvirummut jne. ylitysrakenteet.  

**Termiehdotus Fintossa:** [rumpurakenteet](http://finto.fi/yse/fi/page/Y504487)

**Comment by mirmaid** [comment]
Ks. myös issue #4488
