### ISSUE TITLE
siltarummut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4488]
#### Ehdotettu termi suomeksi

siltarummut  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/ysa/ryhma_37)  
#### Perustelut ehdotukselle
-  
#### Ehdottajan nimi

Mirja Anttila  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi  

**Termiehdotus Fintossa:** [siltarummut](http://finto.fi/yse/fi/page/Y504488)

**Comment by mirmaid** [comment]
Ks. myös issue #4487
