### ISSUE TITLE
kosteudenhallinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4504]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

kosteudenhallinta  
#### Tarkoitusta täsmentävä selite

Liittyy kosteusvaurioiden estämiseen rakennuksissa  
#### Perustelut ehdotukselle

Viime aikoina kovasti yleistynyt ja kätevä termi.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

artikkeliaineistoa rakennusalan ja ympäristöterveydenhuollon lehdistä  
#### Ehdottajan nimi

Elina Mäkelä  
#### Ehdottajan organisaatio

BTJ  
#### Ehdottajan sähköpostiosoite

elina.makela@btj.fi  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/ysa/ryhma_37)  

**Termiehdotus Fintossa:** [kosteudenhallinta](http://finto.fi/yse/fi/page/Y504504)

**Comment by mirmaid** [comment]
Melinda: 0 viitettä (6.9.2016)
http://www.kosteudenhallinta.fi/index.php/fi/

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 14.9.2016)

**Comment by mawikstr** [comment]
Går det att ta upp detta begrepp till ny behandling? Fukthantering-kosteudenhallinta används allmänt inom byggnadstekniken. Det senaste exemplet ett examensarbete från 2018.
http://urn.fi/URN:NBN:fi:amk-2018111917449

**Comment by satuniininen** [comment]
Melindassa 18 kertaa lehtiartikkeleissa, ei SAOssa.

**Comment by LeKorsu** [comment]
Kannatan ottamista.

**Comment by mariaforsen** [comment]
Sv. fukthantering ET fuktkontroll
