### ISSUE TITLE
villiintyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4506]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

villiintyminen  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/ysa/ryhma_15)  
#### Tarkoitusta täsmentävä selite

Kotieläinten villiintyminen. Entäs kasvit?  
#### Perustelut ehdotukselle

Tätä on aika vaikea mitenkään muuten ilmaista. YSAssahan on kesytys, joten eiköhän käänteinen prosessikin ole paikallaan.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

artikkeliaineistoa  
#### Ehdottajan nimi

Elina Mäkelä  
#### Ehdottajan organisaatio

BTJ  
#### Ehdottajan sähköpostiosoite

elina.makela@btj.fi  

**Termiehdotus Fintossa:** [villiintyminen](http://finto.fi/yse/fi/page/Y504506)

**Comment by mirmaid** [comment]
Melinda: 0 viitettä (6.9.2016)

https://www.evira.fi/globalassets/elaimet/elainsuojelu-ja-elainten-pito/ukk/villikissat.pdf

Villiintynyt kissa -termi löytyy Metsästyslaista ja -asetuksesta sekä Laista tieteellisiin tai opetustarkoituksiin käytettävien eläinten suojelusta.

**Comment by mirmaid** [comment]
Ks. myös: http://www.kaleva.fi/uutiset/kotimaa/katso-video-sipila-villiintyi-nuorisokumouksesta-nousi-tuolille-ja-lahjoittaa-10-prosenttia-palkastaan/730359/

**Comment by LeKorsu** [comment]
Entäs viidenkympin villlitys? Sulkutarkenteet (eläimet), (luonto), (ihminen)???? Pitäisikö jättää vielä termiehdotukseksi.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
