### ISSUE TITLE
tyylit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4508]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[tyylit](http://www.yso.fi/onto/ysa/Y99740)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Ehdotetaan termin muutosta muotoon "tyylisuunnat", joka on nyt käsitteen ohjausterminä.  
#### Perustelut ehdotukselle

Muuten selkeyttäisi eroa käsitteeseen "tyyli" http://www.yso.fi/onto/ysa/Y104697. Käyttäjälle voi olla hankalaa tietää mikä ero nykyisillä tyyli ja tyylit -käsitteillä on, etenkin kun temaattiset ryhmätkin ovat osittain päällekkäisiä. Näyttääkin siltä, että kuvailussa näitä käsitteitä on käytetty sekaisin.  
#### Ehdottajan nimi

Mikko Lappalainen  
#### Ehdottajan organisaatio

KK  
#### Ehdottajan sähköpostiosoite

mikko.lappalainen@helsinki.fi

**Comment by mirmaid** [comment]
Tyylit-asiasanaa on käytetty Melindassa 1588 kertaa. Korvaaminen tyylisuunnat-termillä menisi luultavasti yleensä metsään (Rock music styles, Hurmaavat häät, How to draw manga made easy...). Helpompi ratkaisu voisi jopa olla vain yhdistää tyyli KÄ tyylit, mutta vaatii vielä perehtymistä viitteisiin.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Käykö monikko, kun kyseessä on kirjallisuudentutkimus/kirjoittamisen tyyli:

Tyylin käsite ja sen rajauksen ongelmat Gérard Genetten esseessä "Style and signification" https://jyx.jyu.fi/dspace/handle/123456789/51637

The story of Jesus and the blind man: a speech act reading of John 9

"I love you, 4-ever I love you, whatever": stil, språk och gestaltning i Amanda Svenssons roman Välkommen till den här världen

Style in literary translation: A study of shifts in the translations of ’Prelude’ and ’The Garden Party’ by Katherine Mansfield

English for journalists

@tpalonen @satuniininen

**Comment by AuHo22** [comment]
Olettaisin että monikko on yhtä lailla ok, esim. SKTL:n kuvauksessa: Kirjallisuuden kääntäjältä vaaditaan hyvää vieraiden kielten ja erinomaista äidinkielen taitoa, erilaisten _tyylien_ ja murteiden hallintaa, laajaa yleissivistystä ja kykyä perehtyä tieteen, tekniikan, yhteiskuntaelämän ja kulttuurin eri alojen sanastoon. https://www.sktl.fi/@Bin/34193/kirjallisuuden+k%C3%A4%C3%A4nt%C3%A4jien+ty%C3%B6nkuvaus.pdf
Yo. esimerkeissä useassa kysymys lienee kirjallisuuden kielen tyylintutkimuksesta, eli niilläkin termeillä jo selviää.

**Comment by tpalonen** [comment]
Jos eläisimme ihannemaailmassa, kannattaisin tyyli vs. tyylisuunnat -jakoa. Kun tutkin tyylit-käsitteen käyttöä Melindassa huomaan, että tilanne on monimutkainen. Rajanveto siihen milloin puhutaan vakiintuneista tyylisuunnista, milloin yleisemmin/epämääräisemmin tietystä tyylistä (suomalainen kodin sisustustyyli tms) on vaikeaa. Tuntuu, että käsitteiden merkitys on isolta osin päällekkäinen, ja useissa kuvailutapauksissa molemmat käsitteet olisivat perusteltavissa. Ylipäätään Melindassa näyttää siltä, että tyylit-käsitettä käytetään enemmän muoti/pukeutuminen/sisustus-tyyppisissä konteksteissa kuin perinteisten taidemuotojen (kuvataide, musiikki jne) ja niiden tyylisuuntien (impressionismi, postmodernismi jne) yhteydessä.

Näin ollen antaisin varovaisen äänen käsitteiden yhdistämiselle.

Yhdistettäessä monikkomuoto lienee kattavampi, vaikka ei olekaan ihanteellinen kaikissa kuvailutapauksissa.

**Comment by satuniininen** [comment]
Kirjallisuudentutkimuksen/kirjoittamisen yhteyteen monikko sopii mielestäni vähän kömpelösti, mutten usko että se varsinaisesti väärinkään olisi. Lisänä voi monesti käyttää tuota mainittua tyylintutkimusta.

**Comment by MikkoAleksanteri** [comment]
YSOssa käsite [tyylit](http://finto.fi/yso/fi/page/p421) on tulkittu nimenomaan tyylisuuntina, ja alakäsitteinä esim. taiteen tyylisuunnat. YSOn kannalta yhdistäminen olisi siis ristiriitaista.

Käsitteellisesti on varmaan helppoa tehdä rajanveto tyylisuuntien ja tyylin välille, eli eri käsitteiden olemassaololle olisi kyllä perusteet. 

(Voidaan myös pohtia myös sitä, kuinka paljon takautuvan kuvailun korjaamisen vaikeus ohjaa sanastotyötä, ja mitä vaikutuksia sillä on tuleville käyttäjille. Jos käsitteet haluttaisiin pitää erillään, voitaisiin luoda uusi tyylisuunnat-käsite ja yhdistää vanhat viitteet vanhojen tyylit- ja tyyli-käsitteiden yhdistelmälle.)

**Comment by mirmaid** [comment]
Nyt siis tyylisuunnat KÄ _tyylikaudet_ & _tyylit_. Jos otetaan erikseen tyylisuunnat, sen täytyy olla erotettavissa myös _tyylikaudet_-käsitteestä.

**Comment by mariaforsen** [comment]
Ruotsiksi on ennestään ollut: tyyli = stil (sätt) eli tyyli (tapa) ja tyylit = stilar (YSOssa stilar (fenomen) eli tyylit (ilmiöt). Toinen olisi varmaan paremmin voinut olla stilar (stilriktningar).

**Comment by YSA-kokous** [comment]
tyyli KÄ tyylit
