### ISSUE TITLE
peronismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4509]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

peronismi  
#### Ehdotettu termi englanniksi

Peronism  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Arvet efter Perón : en undersökning om kirchnerismens populistiska nationalism i Argentina  
#### Ehdottajan nimi

Satu Niininen  
#### Ehdotettu yläkäsite YSOssa (LT)

[ideologiat](http://www.yso.fi/onto/yso/p216)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)  
#### Perustelut ehdotukselle

Teos käsittelee peronismin perintöä Argentiinassa  
#### Ehdottajan sähköpostiosoite

satu.niininen@helsinki.fi  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85100025  

**Termiehdotus Fintossa:** [peronismi](http://finto.fi/yse/fi/page/Y504509)

**Comment by MikkoAleksanteri** [comment]
Kannatetaan. 

Wikipedia: https://fi.wikipedia.org/wiki/Peronismi

**Comment by mirmaid** [comment]
Melinda: [13 viitettä](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-00442?func=short-0&set_number=040983) (6.9.2016)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
