### ISSUE TITLE
Dupuytrenin kontraktuura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4510]
#### Käsitteen tyyppi

Käsite  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Histological characteristics and gene expression profiling of Dupuytren's disease  
#### Ehdotettu termi suomeksi

Dupuytrenin kontraktuura  
#### Vaihtoehtoiset termit ja ilmaisut

kämmenen kalvokutistuma  
#### Ehdotettu termi englanniksi

Dupuytren's contracture  
#### Ehdotettu yläkäsite YSOssa (LT)

[lihassairaudet](http://www.yso.fi/onto/yso/p1959)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85040014  
#### Ehdottajan nimi

Satu Niininen  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

satu.niininen@helsinki.fi  
#### Perustelut ehdotukselle

Teos käsittelee Dupuytrenin kontraktuuraa  

**Termiehdotus Fintossa:** [Dupuytrenin kontraktuura](http://finto.fi/yse/fi/page/Y504510)

**Comment by mirmaid** [comment]
Melinda: Dupuytren's contracture 4 kertaa, kerran Dupuytrenin tauti (Google n. 200) (6.9.2016)

MeSH: Dupuytrenin kutistuskoukistuma (Google n. 1000)

Lääketieteen termit: kämmenen kalvokutistuma (Google n. 600)

Wikipedia: https://fi.wikipedia.org/wiki/Dupuytrenin_kontraktuura (Google n. 2300)

**Comment by mirmaid** [comment]
Otetaan sanastoon, mutta mikä muoto päätermiksi?

**Comment by LeKorsu** [comment]
Saisiko Terkosta suositusta päätermistä?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016) (varmistetaan muoto)
