### ISSUE TITLE
kansalaisuskonto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4512]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

kansalaisuskonto  
#### Vaihtoehtoiset termit ja ilmaisut

yhteiskuntauskonto  
#### Ehdotettu termi englanniksi

civil religion  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85026369  
#### Tarkoitusta täsmentävä selite

http://kans.jyu.fi/sanasto/sanat-kansio/kansalaisuskonto
https://fi.wikipedia.org/wiki/Kansalaisuskonto  
#### Perustelut ehdotukselle

Käytetty asiasanana Melindassa 15 kertaa, Artossa 10 kertaa. 
Esim. Civil religion: a dialogue in the history of political philosophy / Ronald Beiner (2011). 

Teologian asiasanastossa (http://blogs.helsinki.fi/teolasiasanasto/) on sekä kansalaisuskonto että yhteiskuntauskonto. Termiä yhteiskuntauskonto on käytetty asiasanana Melindassa 20 kertaa, Artossa 3 kertaa.  
#### Ehdotettu termi ruotsiksi

civilreligion  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi  

**Termiehdotus Fintossa:** [kansalaisuskonto](http://finto.fi/yse/fi/page/Y504512)

**Comment by mirmaid** [comment]
Wikipedia: Civil religion -käsitteestä on käytetty Suomessa kahtakin käännöstä: kansalaisuskonto sekä yhteiskuntauskonto. Vakiintuneeseen käytäntöön ei ole päästy. Tämä saattaa johtua siitä, että civil religion -käsite sisältää molemmat puolet. Käytännössä on vakiintunut tavaksi, että teologit käyttävät yhteiskuntauskonto-käännöstä, kun taas uskontotieteilijät puhuvat kansalaisuskonnosta. https://fi.wikipedia.org/wiki/Kansalaisuskonto#Kansalaisuskonto_suomalaisessa_tutkimuksessa

**Comment by LeKorsu** [comment]
Pitäisikö vielä odotella, vakiintuuko jompikumpi toista vahvemmaksi? Nyt on tasaista (Arto- & Melinda-viitteiden mukaan).

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016) KT yhteiskuntauskonto
