### ISSUE TITLE
tricksterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4513]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

tricksterit  
#### Vaihtoehtoiset termit ja ilmaisut

triksterit  
#### Ehdotettu termi englanniksi

tricksters  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/ysa/ryhma_50)  

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85137487  
#### Tarkoitusta täsmentävä selite

https://en.wikipedia.org/wiki/Trickster  
#### Assosiatiiviset (ST)

[sankarit](http://www.yso.fi/onto/ysa/Y111516)  
#### Perustelut ehdotukselle

Termi on ollut KULA-asiasanastossa yksikössä (trickster). Siinä muodossa sitä on käytetty Melindassa 60 kertaa, Artossa 13 kertaa. Esim.
Trickster and hero: two characters in the oral and written traditions of the world / Harold Scheub (2012).
Uusia tuulia trickster-tutkimuksessa / Mark Shackleton; suomentanut Tiina Wikström. - Kajo 16 (2012): 2.

Jotkut suomalaiset tutkijat käyttävät kirjoitusmuotoa triksterit, mutta esimerkiksi HY:n viime talven etnografia-seminaarissa puhuttiin trickstereistä, ks. https://www.avoin.helsinki.fi/ajankohtaista/2015/etnografia-seminaari_kevat2016.htm.  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi  

**Termiehdotus Fintossa:** [tricksterit](http://finto.fi/yse/fi/page/Y504513)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016) (KT triksterit)
