### ISSUE TITLE
tantra

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4514]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[tantra](http://www.yso.fi/onto/ysa/Y155114)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

tantrismi - ehdotan tätä joko ohjaustermiksi (korvatuksi termiksi) tai varsinaiseksi asiasanaksi  
#### Perustelut ehdotukselle

LCSH: http://id.loc.gov/authorities/subjects/sh85132368 (LCSH:ssa ei ole ollenkaan termiä tantra) 
Wikipedia: https://fi.wikipedia.org/wiki/Tantra

KULAssa on termi tantrismi. Sitä on käytetty asiasanana Melindassa 94 kertaa (virheellisesti toisinaan myös YSA-terminä) ja Artossa 2 kertaa. YSA-termiä tantra on käytetty asiasanana Melindassa 89 kertaa ja Artossa 2 kertaa.

LCSH- ja SAO-sanastoissa termillä tantrismi viitataan hindulaiseen traditioon, buddhalaisesta tantrismista käytetään termiä Tantric Buddhism (LCSH) tai Vajrayana (SAO). YSAssa ja KULAssa ei ole tehty eroa buddhalaisen ja hindulaisen tantran/tantrismin välille.  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi

**Comment by mirmaid** [comment]
Wikipediassa myös eng. https://en.wikipedia.org/wiki/Tantra - molemmat vaihtoehdot lienevät oikein.

**Comment by mirmaid** [comment]
Ohjaustermi (YSA-kokous 14.9.2016)
