### ISSUE TITLE
ryhmien väliset suhteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4516]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

ryhmien väliset suhteet  
#### Ehdotettu termi englanniksi

intergroup relations  
#### Ehdotettu yläkäsite YSOssa (LT)

[sosiaalinen vuorovaikutus](http://www.yso.fi/onto/yso/p10590)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/ysa/ryhma_60)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh87000911  
#### Perustelut ehdotukselle

KULA-termi. Sanaliitot ovat asiasanoina hankalia, mutta tätä on käytetty asiasanana Melindassa 276 kertaa, Artossa 53 kertaa. Esim.
Identities, intergroup relations and acculturation: the cornerstones of intercultural encounters / Inga Jasinskaja-Lahti & Tuuli Anna Mähönen (eds.) (2009).
Intergroup relations: the role of motivation and emotion / edited by Sabine Otten, Kai Sassenberg, and Thomas Kessler (2009).  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi  
#### Ehdottajan organisaatio

SKS:n kirjasto  

**Termiehdotus Fintossa:** [ryhmien väliset suhteet](http://finto.fi/yse/fi/page/Y504516)

**Comment by mirmaid** [comment]
LCSH: Intergroup relations: in general the interaction of social groups or the study of this. However, very often the term is used to refer quite specifically to the study of the contact, coexistence, or conflict of ethnic, religious, or racial groups ...

YSAssa on termit kulttuurienvälinen vuorovaikutus, kulttuurikosketukset ja kulttuurienvälisyys

Melindassa on käytetty 73 kertaa LCSH-termiä Intergroup relations, mutta vain kolme on samoja joissa myös termi ryhmien väliset suhteet.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
