### ISSUE TITLE
romanimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4517]
#### Käsitteen tyyppi

Käsite  
#### Ehdotettu termi suomeksi

romanimusiikki  
#### Ehdotettu termi englanniksi

Romany music / Roma music  
#### Ehdotettu yläkäsite YSOssa (LT)

[perinnemusiikki](http://www.yso.fi/onto/yso/p1591)  
#### Assosiatiiviset (RT)

[mustalaismusiikki](http://www.yso.fi/onto/ysa/Y97573)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/ysa/ryhma_50)  

[89 Musiikki](http://www.yso.fi/onto/ysa/ryhma_89)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85058111 (Romanies -- music)  
#### Tarkoitusta täsmentävä selite

Tarkoittaa romaniväestön pääasiassa omassa keskuudessaan esittämää perinnemusiikkia. Termillä mustalaismusiikki taas tarkoitetaan sekä romaneiden että muiden kuin romaneiden esittämiä 1800-luvulta lähtien syntyneitä musiikintyylejä, jotka yhdistetään romaneihin, esim. romanitangoja ja -iskelmiä.  
#### Perustelut ehdotukselle

KULA-termi. Käytetty asiasanana Melindassa 4 kertaa, Artossa 24 kertaa. Termiä mustalaismusiikki on käytetty asiasanana Melindassa 448 kertaa ja Artossa 49 kertaa.

Tästä asiasta oli puhetta YSAn ylläpitäjien kanssa jo muutama vuosi sitten. Romanimusiikin tutkijat tekevät em. eron termien romanimusiikki ja mustalaismusiikki välillä, mutta tuolloin todettiin, että termien merkitysero on niin pieni (tai niin suppean käyttäjäryhmän mieltämä), ettei YSAan kannata ottaa molempia termejä. Tämä voi hyvin pitää edelleen paikkansa, mutta olisiko termi romanimusiikki syytä ottaa ainakin korvatuksi termiksi, joka ohjaisi käyttämään termiä mustalaismusiikki?  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi

**Comment by henriyli** [comment]
Tuplaehdotus siirtelen lisätietoja käsin YSE-käsitteeseen. Aikaisemman ehdotuksen issue https://github.com/Finto-ehdotus/YSE/issues/1837

**Comment by mirmaid** [comment]
Termiä ehdotettu edellisen kerran v. 2006.

MUSA: mustalaismusiikki: Termiä ei käytetä romanien varsinaisesta perinnemusiikista, joka indeksoidaan kuten muukin perinteinen musiikki, esim. perinnemusiikki : romanit : Suomi. Koska mustalaismusiikin lajeja ja tyylejä on useita (erityisesti Unkari, Espanja ja Venäjä), lisäksi on aina käytettävä maantieteellistä täsmennettävä, esimerkiksi mustalaismusiikki : kitara : Venäjä. 
Vanhahtava suomalainen ilmaisu erityisesti Keski-Euroopassa elävien romanien tulkitsemalle perinteiselle viihdemusiikille, jossa viululla ja cimbalomilla on keskeinen rooli.

**Comment by mirmaid** [comment]
Luumu-ryhmä ei kannattanut ehdotusta:

”Minusta olisi parempi pysyä ilmaisussa ”perinnemusiikki : romanit” (+ muut täsmennykset). Pitäisi sitten olla myös saamelaismusiikki, karjalaismusiikki, maahanmuuttajamusiikki, saaristolaismusiikki ..”

"LCSH:n käytäntö on ketjuttaa diasporassa elävien etnisten ryhmien musiikkia ja sitä käsittelevää aineistoa kuvailevat termit, esim.
Cuban Americans--Music--2000-2010.
Finns--United States--Music.
German Americans--Iowa--Music.
Romanies--Music.
Swedes--Finland--Music--History and criticism.”

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 14.9.2016)

**Comment by MUUSA-kokous** [comment]
Asia on käsitelty ja päätetty issuessa https://github.com/Finto-ehdotus/YSE/issues/6682. Tämän issuen voisi siis sulkea.
