### ISSUE TITLE
teollisuusyhdyskunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4518]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[teollisuusyhdyskunnat](http://www.yso.fi/onto/ysa/Y99423)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Korvatuksi termiksi: teollisuusyhteisöt. En siis ehdota muutosta asiasanaan, vaan vain uuden ohjaustermin lisäämistä.  
#### Perustelut ehdotukselle

KULAssa on ollut termi teollisuusyhteisöt, mutta sitä on käytetty sisällönkuvailussa vain vähän ja YSA:n termi korvaa sen hyvin.  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
