### ISSUE TITLE
työläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4519]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[työläiset](http://www.yso.fi/onto/ysa/Y107795)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Termi työväestö on YSAssa korvattu termi, sen sijaan pitäisi käyttää termejä työläiset tai työväenluokka. Pitäiskö työväestö kuitenkin sallia varsinaisena asiasanana?  
#### Perustelut ehdotukselle

Termiä työväestö on käytetty asiasanana Melindassa 356 kertaa, Artossa 230 kertaa. Usein sitä on käytetty joko Kaunokki- tai Kula-terminä, mutta varsin yleisesti myös virheellisesti YSA-terminä, esim.
Työväestö ja hyvinvointi / toimittanut Matti Hannikainen (2014)
St Petersburg: shadows of the past / Catriona Kelly (2014)
London labour and the London poor : a selected edition / Henry Mayhew (2010)  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: työväestö = työväki: työntekijät, työläiset, työväestö yhteiskuntaluokkana.

YSAssa on myös työntekijät. En ole varma muuttusiko kuvailijan tehtävä helpommaksi vai hankalammaksi jos tulisi vielä yksi merkitykseltään läheinen termi lisää.

**Comment by LeKorsu** [comment]
Olen ehdottajan kannalla eli että "työväestö"  Sen lukuisa käyttö kaiketi kertoo hyödyllisyydestä. Työntekijät-termiin en sen pelkää sekoittuvan. Se ei assosioi samalla tavalla yhteiskuntaluokan kanssa kuin työväestö tai työläiset.

**Comment by mirmaid** [comment]
Jos tämä hyväksytään, YSAssa olisi siis:
1. työväenluokka
2. työläiset
3. työväestö
4. työntekijät

Nyt on tullut toiveita useiden termien osalta yhdistämiseen jos merkitysero ei ole selkeä ja kuvailussa käytetään termejä ristiin. Onko tässä riittävän erilaiset merkitykset jotta johdonmukainen erottelu on mahdollinen?

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 14.9.2016)
