### ISSUE TITLE
savityöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4520]
#### Käsitteen tyyppi

Käsite  
#### Perustelut ehdotukselle

YSAssa termillä käsityöt on useita alakäsitteitä, mutta tämä puuttuu. Termiä on käytetty asiasanana Melindassa 63 kertaa, usein virheellisesti YSA-terminä, ks. esim.
The pot book / edited and written by Edmund De Waal with Claudia Clare (2011).

YSAssa on termi savenvalajat. MAO/TAO-ontologiassa on keramiikkatyö (korvattu termi savityö) sekä savenvalanta.  
#### Ehdotettu termi suomeksi

savityöt  
#### Ehdotettu termi englanniksi

pottery  
#### Ehdotettu yläkäsite YSOssa (LT)

[käsityöt (objektit)](http://www.yso.fi/onto/yso/p4923)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85105729  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi

**Comment by henriyli** [comment]
Tuplaehdotus... siirrän lisätiedot käsin vanhemman ehdotuksen YSE-käsitteeseen: https://github.com/Finto-ehdotus/YSE/issues/4014

**Comment by mirmaid** [comment]
Termiä ehdotettu edellisen kerran v. 2013.

YSOssa pottery = suom. saviastiat

YSAssa on dreijaus

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
