### ISSUE TITLE
runologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4521]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

runologia
#### Ehdotettu termi ruotsiksi

runologi  
#### Ehdotettu termi englanniksi

runology  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[85 Kielitiede](http://www.yso.fi/onto/ysa/ryhma_85)  

[51 Arkeologia](http://www.yso.fi/onto/ysa/ryhma_51)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Sveriges runinskrifter / Sven B. F. Jansson  
#### Perustelut ehdotukselle

Finns även i t.ex. Svenska ämnesord (SAO). Behövs för att beskriva runologin som disciplin och dess historia.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [runologia](http://finto.fi/yse/fi/page/Y504521)

**Comment by mirmaid** [comment]
Melinda: 0 viitettä (7 kertaa riimukirjoitus + tutkimus) (6.9.2016) 

Vain muutama suomenkielinen Google-hitti:

Runologia tutkii riimukirjoituksia http://www.oulu.fi/sites/default/files/content/Metodien%20maailma_keskiajan%20tutkimus.pdf 

Runologia eli riimujen, riimukivien ja niiden historian tutkimus oli saanut pontta 1500-luvun lopun ja 1600-luvun alun Ruotsissa Johannes Bureuksen (1568–1652) tutkimusten myötä. https://opintokokoelma.wordpress.com/kirja-aarteet/muinaista-menneisyytta-etsimassa/

LCSH: Runology

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
