### ISSUE TITLE
papaja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4522]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

papaija  
#### Ehdotettu termi ruotsiksi

papaja  
#### Ehdotettu termi englanniksi

papaya  
#### Vaihtoehtoiset termit ja ilmaisut

papaya  
#### Ehdotettu yläkäsite YSOssa (LT)

[hedelmät](http://www.yso.fi/onto/yso/p4647)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[16 Kasvitiede](http://www.yso.fi/onto/ysa/ryhma_16)  
#### exactmatch

Papaya  
#### Perustelut ehdotukselle

Använt i Melinda.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [papaja](http://finto.fi/yse/fi/page/Y504522)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
