### ISSUE TITLE
likhet inför lagen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4523]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

yhdenvertaisuus lain edessä  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Equal citizenship and its limits in EU law : we the burden? / Päivi Johanna Neuvonen.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  
#### Ehdotettu termi ruotsiksi

likhet inför lagen  
#### Ehdotettu termi englanniksi

equality before the law  
#### Ehdotettu yläkäsite YSOssa (LT)

[yhdenvertaisuus](http://www.yso.fi/onto/yso/p17567)  
#### Assosiatiiviset (ST)

[yhdenvertaisuuslaki](http://www.yso.fi/onto/ysa/Y146873)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)  
#### exactmatch

Equality before the law  
#### Perustelut ehdotukselle

Begrepp med en klart definierad betydelse.  

**Termiehdotus Fintossa:** [likhet inför lagen](http://finto.fi/yse/fi/page/Y504523)

**Comment by mirmaid** [comment]
Melinda: [15 viitettä](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-02810?func=short-0&set_number=047006) (6.9.2016) - käytetty eks-terminä mutta ei löydy EKS-sanastosta.

http://www.finlex.fi/fi/laki/ajantasa/1999/19990731?search[type]=pika&search[pika]=yhdenvertaisuus%20lain%20edess%C3%A4#a731-1999

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
