### ISSUE TITLE
dopträd

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4524]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi ruotsiksi

dopträd  
#### Ehdotettu termi suomeksi

kastepuut  
#### Ehdotettu yläkäsite YSOssa (LT)

[kirkolliset esineet](http://www.yso.fi/onto/yso/p13651)  
#### Assosiatiiviset (ST)

[kaste](http://www.yso.fi/onto/ysa/Y95920)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Barnen får sin plats i livets träd / Christa Mickelsson (http://www.kyrkpressen.fi/fileupl/KP1619Webb.pdf)  
#### Perustelut ehdotukselle

Behövs i beskrivningen av det relativt nya fenomenet med dopträd (vanligare i Sverige). I detta fall kan inte användas ämnesorden "träd" + "dop", eftersom detta inte syftar på levande träd.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [dopträd](http://finto.fi/yse/fi/page/Y504524)

**Comment by mirmaid** [comment]
Melinda: 0 viitettä (6.9.2016)

http://www.kirkkojakoti.fi/143-puijon-kirkkoon-kastepuu

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
