### ISSUE TITLE
mango

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4525]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

mango  
#### Ehdotettu termi ruotsiksi

mango  
#### Ehdotettu termi englanniksi

mango  
#### Ehdotettu yläkäsite YSOssa (LT)

[hedelmät](http://www.yso.fi/onto/yso/p4647)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[16 Kasvitiede](http://www.yso.fi/onto/ysa/ryhma_16)  
#### exactmatch

Mango  
#### Perustelut ehdotukselle

Även i Melinda.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [mango](http://finto.fi/yse/fi/page/Y504525)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
