### ISSUE TITLE
välgörenhetsevenemang

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4526]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

hyväntekeväisyystapahtumat?  
#### Ehdotettu termi ruotsiksi

välgörenhetsevenemang  
#### Ehdotettu termi englanniksi

charity events?  
#### Ehdotettu yläkäsite YSOssa (LT)

[yleisötilaisuudet](http://www.yso.fi/onto/yso/p2109)  
#### Assosiatiiviset (ST)

[hyväntekeväisyys](http://www.yso.fi/onto/ysa/Y101734)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)  
#### Tarkoitusta täsmentävä selite

Olika typer av evenemang för allmänheten där man riktar uppmärksamhet mot och samlar in medel för något välgörande ändamål.  
#### Perustelut ehdotukselle

Vanlig term som vore behändig att använda för beskrivningen av material som handlar om just denna typ av evenemang. Behövd vid artikelindexering.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [välgörenhetsevenemang](http://finto.fi/yse/fi/page/Y504526)

**Comment by mirmaid** [comment]
Melinda: 0 viitettä (samoin Arto) (hyväntekeväisyys + tapahtumat 4 kertaa) (6.9.2016)

https://fi.wikipedia.org/wiki/Luokka:Hyv%C3%A4ntekev%C3%A4isyystapahtumat

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
