### ISSUE TITLE
polymeria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4527]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[polymeria](http://www.yso.fi/onto/ysa/Y107010)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Polymeria tarkoittaa kahta asiaa. Pitäisikö se jakaa kahdeksi käsitteeksi varustettuna silmät avaavilla sulkutarkenteilla?  
#### Perustelut ehdotukselle

Termi liittyy sekä kemian että biologian alaan. Melindassa termiä on käytetty molemmissa merkityksissä. Kielitoimiston sanakirjan määritelmä: "kem. ilmiö jossa aineen rakenteeltaan samankaltaiset molekyylit ovat erisuuruisi". Lääketiede 2.0a:n määritelmät: "1. lukuisten ylimääräisten elinten tai elinten osien synnynnäinen esiintyminen; 2. [kem.] polymeerien syntyminen ja esiintyminen; 3. [perinn.] ominaisuuden johtuminen useista perintötekijöistä".  
#### Ehdottajan nimi

Tuomas Palonen  
#### Ehdottajan organisaatio

KK  
#### Ehdottajan sähköpostiosoite

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Aika hankala kysymys - ne Melindan viitteet joissa polymeria-asiasanaa on käytetty molekyylibiologian alalla, eivät oikeastaan tunnu liittyvän tuohon Kielitoimiston sanakirjan antamaan 3-merkitykseen, mutta näkemättä aineistoa on mahdotonta olla ihan varma asiasta. (polymeraasi, polymeraasiketjureaktio)

**Comment by mariaforsen** [comment]
Vaikeaa löytää mitään tietoa ja lähteitä elin-merkitykseen (ruots. polymerism Lääketieteen termi-kirjassa).. Onko mahdollisesti olemassa jotain yleisemmin käytettyjä synonymeja sille ilmiölle..?

**Comment by LeKorsu** [comment]
Komppaan edellisiä kommentteja.

**Comment by mirmaid** [comment]
Elin-merkitystä ei löydy myöskään Melindasta, ja tosiaan en saanut ihan selville ovatko ne viitteet jotka ovat kyllä molekyylibiologiaa kuitenkaan käsitelleet aihetta (3.) "ominaisuuden johtuminen useista perintötekijöistä". Voi olla että asiasanaa on niissä käytetty virheellisesti.

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 14.9.2016)
