### ISSUE TITLE
pyrrhonismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4528]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

pyrrhonismi  
#### Ehdotettu termi englanniksi

Pyrrhonism  
#### Ehdotettu yläkäsite YSOssa (LT)

[skeptisismi](http://www.yso.fi/onto/yso/p11675)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[02 Filosofia](http://www.yso.fi/onto/ysa/ryhma_02)  
#### Tarkoitusta täsmentävä selite

The Oxford Companion to Philosophy (2 ed.) : "Pyrrhonism. A sceptical tradition whose leading figure was Pyrrho of Elis (c. 365–270 bc), but handed down to us in the works of Sextus Empiricus. Pyrrho argued that the reasons in favour of a belief are never better than those against (isostheneia—a situation of equal strength), and that the only possible response to this is to stop worrying (ataraxia) and to live by the appearances. He suggested that this life would have a lot to recommend it; critics maintained that it would be very uncomfortable, at best. The question who was right depends on what is meant by ‘live by the appearances’. Sextus' work was rediscovered in the mid-sixteenth century; the sceptical concerns of Montaigne and Descartes are a direct response, though Cartesian scepticism seems to be directed more against the possibility of knowledge than against the possibility of having better reasons in favour of some belief than against it."  
#### Perustelut ehdotukselle

Puutuu YSAsta. Filosofian termi.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Markku Ylinen, väitöskirja, Pyrrhonismi renessanssifilosofiassa ja konstruktiivinen skeptisismi 1600-luvulla :kuusi argumenttia Richard Popkinin tulkintaa vastaan, 2016.  
#### Ehdottajan nimi

Mervi Salomaa-Rauhala  
#### exactmatch

https://fi.wikipedia.org/wiki/Pyrrhonismi  
#### Ehdottajan organisaatio

Tampereen yliopiston kirjasto  
#### Ehdottajan sähköpostiosoite

mervi.salomaa-rauhala@uta.fi  
#### Ehdotettu termi ruotsiksi

Pyrrhonism  (sao)  

**Termiehdotus Fintossa:** [pyrrhonismi](http://finto.fi/yse/fi/page/Y504528)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
