### ISSUE TITLE
monikemikaaliyliherkkyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4529]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

monikemikaaliyliherkkyys  
#### Ehdotettu termi ruotsiksi

multipel kemisk känslighet  
#### Ehdotettu termi englanniksi

multiple chemical sensitivity  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh97004171  
#### Ehdotettu yläkäsite YSOssa (LT)

[yliherkkyys](http://www.yso.fi/onto/yso/p343)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)  
#### Perustelut ehdotukselle

kuvailtavan teoksen aiheena monikemikaaliyliherkkyys
FinMeSH: http://www.yso.fi/onto/mesh/D018777
https://fi.wikipedia.org/wiki/Monikemikaaliyliherkkyys  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

MCS-potilas : omaelämäkerrallinen tietokirja monikemikaaliyliherkkyydestä  

**Termiehdotus Fintossa:** [monikemikaaliyliherkkyys](http://finto.fi/yse/fi/page/Y504529)

**Comment by mirmaid** [comment]
Melinda: [1 viite](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-01075?func=short-0&set_number=054426) (6.9.2016)

**Comment by LeKorsu** [comment]
Riittäisikö kemikaaliyliherkkyys? Tosin pitäisikö sitten listata muitakin yliherkkyyksiä? Nyt yliherkkyydellä ei ole mitään ST-termejä. Termiehdotus.

**Comment by mirmaid** [comment]
YSOssa hierarkiaa on tarkistettu niin että yliherkkyydella on joitakin alakäsitteitä. Tämä taitaa olla nimenomaan käytetty termi kun kyseessä on kemikaaliyliherkkyys (vaikka se kuulostaisi kyllä paremmalta).

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
