### ISSUE TITLE
suojeluala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4530]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

suojeluala  
#### Perustelut ehdotukselle

Suojeluala kattaa monia eri ammatteja (poliisi, palomies, hätäkeskuspäivystäjä, rajavartija, vankeinhoitaja)
http://www.opiskelupaikka.fi/Tyopaikka-harjoittelu/Ammattialat/Suojeluala
http://www.ammattinetti.fi/ammattialat/alahaku/13  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[49 Palotoimi. Pelastustoimi. Tapaturmantorjunta. Turvallisuustekniikka](http://www.yso.fi/onto/ysa/ryhma_49)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Koulutuksesta työmarkkinoille. Osa 9, Muu koulutus (suojeluala)  
#### Ehdotettu termi ruotsiksi

skyddsbranschen  
#### Ehdotettu yläkäsite YSOssa (LT)

[toimialat](http://www.yso.fi/onto/yso/p1427)  

**Termiehdotus Fintossa:** [suojeluala](http://finto.fi/yse/fi/page/Y504530)

**Comment by ilona-x** [comment]
useamman alakäsitteen lisääminen ei näköjään onnistunut, joten tässä nämä ehdotuksen ST:t: turva-ala, pelastusala, rikosseuraamusala

**Comment by mirmaid** [comment]
Melinda: 0 viitettä (6.9.2016)

Käytetään myös yhdistelminä "sotilas- ja suojeluala", turvallisuus- ja suojeluala", "suojelu- ja pelastusala".

**Comment by LeKorsu** [comment]
Ysassa on jo suojelualan oppilaitokset, niin kannatan kyllä myös suojelualan ottamista mukaan.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
