### ISSUE TITLE
maitoproteiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4531]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

maitoproteiinit  
#### Ehdotettu termi ruotsiksi

mjölkproteiner  
#### Ehdotettu termi englanniksi

milk proteins  
#### Vaihtoehtoiset termit ja ilmaisut

maidon proteiinit  
#### Ehdotettu yläkäsite YSOssa (LT)

[proteiinit](http://www.yso.fi/onto/yso/p4332)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/ysa/ryhma_24)  
#### Alakäsitteet (RT)

[laktoferriini](http://www.yso.fi/onto/yso/p25622)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85085363  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Role of chemical and enzymatic modifications of milk proteins on emulsion stability/properties  
#### Perustelut ehdotukselle

proteiinilistan jatkoksi, ja yksi alakäsitekin jo löytyy YSAsta
FinMeSH: http://finto.fi/mesh/fi/page/D008894  

**Termiehdotus Fintossa:** [maitoproteiinit](http://finto.fi/yse/fi/page/Y504531)

**Comment by mirmaid** [comment]
Melinda: 4 viitettä (MeSH) (6.9.2016)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
