### ISSUE TITLE
selkäydinvammat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4532]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

selkäydinvammat  
#### Ehdotettu termi ruotsiksi

ryggmärgsskador  
#### Ehdotettu termi englanniksi

Spinal Cord Injuries  
#### exactmatch

https://fi.wikipedia.org/wiki/Selk%C3%A4ydinvamma  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)  
#### Alakäsitteet (RT)

[palotoimi](http://www.yso.fi/onto/yso/p2379)  
#### Perustelut ehdotukselle

YSAssa on jo selkäydinvammaiset
Melindassa x 9
FinMeSH  http://www.yso.fi/onto/mesh/D013119  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Impact of the peripheral immune system to disease-induced neuroinflammation  https://www.uef.fi/fi/-/11-12-elimiston-tulehdusreaktiota-voidaan-vaimentaa-keskushermostoon-vaikuttavissa-sairauksissa  
#### Ehdotettu yläkäsite YSOssa (LT)

[vammat](http://www.yso.fi/onto/yso/p50)  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Vaihtoehtoiset termit ja ilmaisut

selkäytimen vammat  

**Termiehdotus Fintossa:** [selkäydinvammat](http://finto.fi/yse/fi/page/Y504532)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
