### ISSUE TITLE
viroterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4533]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[viroterapia](http://www.yso.fi/onto/ysa/Y156510)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

ST onkolyyttinen virushoito  
#### Perustelut ehdotukselle

Näillä kahdella termillä ei ole tällä hetkellä toisiinsa suhdetta, mutta ilmeisesti onkolyyttinen virushoito on viroterapian yksi muoto: https://en.wikipedia.org/wiki/Virotherapy  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi

**Comment by mirmaid** [comment]
Lisätään ST-suhde.
