### ISSUE TITLE
yritysmyynti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4534]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[yritysmyynti](http://www.yso.fi/onto/ysa/Y182428)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

KT b2b-myynti  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Perustelut ehdotukselle

tätä tulee haettua usein tuolla b2b-alkuisella termillä, joten se olisi hyvä lisätä ohjaustermiksi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
