### ISSUE TITLE
yritysmarkkinointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4535]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[yritysmarkkinointi](http://www.yso.fi/onto/ysa/Y134712)  
#### Tila

Käsittelyssä  
#### Perustelut ehdotukselle

tätä tulee haettua usein tuolla b2b-alkuisella termillä, joten se olisi hyvä lisätä ohjaustermiksi  
#### Ehdotettu muutos

KT b2b-markkinointi  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
