### ISSUE TITLE
syöksyvirtaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4536]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

syöksyvirtaus  
#### Ehdotettu termi ruotsiksi

fallvind  
#### Ehdotettu termi englanniksi

downburst  
#### Tarkoitusta täsmentävä selite

syöksyvirtaus on ukkospilvestä alaspäin syöksyvä voimakas kylmä ilmavirtaus, joka maan- tai vesipinnan kohdatessaan kääntyy vaakasuoraksi. Tuulen nopeus voi yltyä jopa 50 m/s, mutta ilmiö harvoin kestää muutamaa minuuttia pitempään. Suomessa mahdolliset metsätuhot rajoittuvat suhteellisen pienelle alueelle.  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[14 Klimatologia. Meteorologia. Ilmatiede](http://www.yso.fi/onto/ysa/ryhma_14)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Mesoscale convective systems in Finland  http://ilmatieteenlaitos.fi/tiedotearkisto/-/journal_content/56/30106/121385157  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Ehdotettu yläkäsite YSOssa (LT)

[sääilmiöt](http://www.yso.fi/onto/yso/p537)  
#### Perustelut ehdotukselle

Melinda x 2
https://fi.wikipedia.org/wiki/Sy%C3%B6ksyvirtaus  

**Termiehdotus Fintossa:** [syöksyvirtaus](http://finto.fi/yse/fi/page/Y504536)

**Comment by mirmaid** [comment]
LCSH: Microbursts

Monikko?

**Comment by mirmaid** [comment]
Hyväksytty (monikossa) (YSA-kokous 14.9.2016)
