### ISSUE TITLE
ohjelmistokehittäjät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4537]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

ohjelmistokehittäjät  
#### Ehdotettu termi englanniksi

(computer) software developers  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh00009189  
#### Assosiatiiviset (ST)

[ohjelmoijat](http://www.yso.fi/onto/yso/p10393)  
#### Ehdotettu yläkäsite YSOssa (LT)

[ammatit](http://www.yso.fi/onto/yso/p1179)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

The role of process conformance and developers' skills in the context of test-driven development  http://jultika.oulu.fi/Record/isbn978-952-62-1165-7  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Ehdotettu termi ruotsiksi

programutvecklare  
#### Perustelut ehdotukselle

ammatti, YSAssa ohjelmistokehitys  

**Termiehdotus Fintossa:** [ohjelmistokehittäjät](http://finto.fi/yse/fi/page/Y504537)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ohjelmistosuunnittelija

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
