### ISSUE TITLE
molekyylidynamiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4538]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

molekyylidynamiikka  
#### Ehdotettu termi ruotsiksi

molekyldynamik  
#### Ehdotettu termi englanniksi

molecular dynamics  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[07 Fysiikka](http://www.yso.fi/onto/ysa/ryhma_07)  
#### Perustelut ehdotukselle

käytetty Melindassa asiasanana 26 kertaa  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

The effects of structural and environmental factors on the swelling behavior of montmorillonite-beidellite Smectites : a molecular dynamics approach  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85086583  
#### Ehdotettu yläkäsite YSOssa (LT)

[dynamiikka](http://www.yso.fi/onto/yso/p4095)  

**Termiehdotus Fintossa:** [molekyylidynamiikka](http://finto.fi/yse/fi/page/Y504538)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Molecular_dynamics

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
