### ISSUE TITLE
bioliuotus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4539]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

bioliuotus  
#### Vaihtoehtoiset termit ja ilmaisut

biokasaliuotus  
#### Ehdotettu termi englanniksi

bioleaching  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[32 Kaivosteollisuus. Kaivannaisteollisuus](http://www.yso.fi/onto/ysa/ryhma_32)  

[09 Kemia](http://www.yso.fi/onto/ysa/ryhma_09)  
#### exactmatch

Bacterial leaching: http://id.loc.gov/authorities/subjects/sh89004403  
#### Tarkoitusta täsmentävä selite

https://fi.wikipedia.org/wiki/Bioliuotus  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Heap bioleaching of low-grade multimetal sulphidic ore in boreal conditions  
#### Perustelut ehdotukselle

Melinda x 3  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  

**Termiehdotus Fintossa:** [bioliuotus](http://finto.fi/yse/fi/page/Y504539)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
