### ISSUE TITLE
hallitusneuvottelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#454]
#### Ehdotettu termi suomeksi

hallitusneuvottelut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)
[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/ysa/ryhma_71)

**Luontipäivämäärä:** 19.05.1999

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114535

**Termiehdotus Fintossa:** [hallitusneuvottelut](http://finto.fi/yse/fi/page/Y314535)

**Comment by tpalonen** [comment]
Kannatan termin ottamista sanastoon joko a) omana käsitteenään tai b) yhdistettynä käsitteeseen "hallituksen muodostaminen.", joko ohjausterminä tai pääterminä. Googlaamisen perusteella hallitusneuvottelut on paljon yleisempi termi kuin hallituksen muodostaminen. Eivät toki ole täydellisiä synonyymeja, mutta ovatko riittävän läheisiä, että voisi yhdistää samaan käsitteeseen? Termin tarpeesta kertoo esim. se, että Yle käyttää termiä hallitusneuvottelut aiheena, vaikka sitä ei ole YSOssa/KOKOssa: https://yle.fi/aihe/t/18-218838

Inspiroiduin nostamaan asian esille, kun mietin YSOn "hallituksen muodostaminen"-käsitteen linkittämistä Wikidataan. Linkitin sen kohteeseen, joka on englanniksi "government formation" ja suomeksi "hallitusneuvottelut": https://www.wikidata.org/wiki/Q2137778. Wikidata-linkitystä voi miettiä uudelleen riippuen siitä, mihin tässä issuessa päädytään.

**Comment by ilona-x** [comment]
hallitusneuvottelut ei EKSissä

**Comment by mirmaid** [comment]
32 viitettä Melindassa (lähes kaikki artikkeliaineistoa). _Hallituksen muodostaminen_ 202 kertaa (on myös EKS:ssä). _Hallituksen muodostaminen_ on käsitteenä laajempi, joten päätermin vaihtaminen hallitusneuvotteluihin olisi ongelmallista.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi: hallitusneuvottelut KÄYTÄ hallituksen muodostaminen.
