### ISSUE TITLE
sukupuolirauhaset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4541]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

sukupuolirauhaset  
#### Ehdotettu termi ruotsiksi

könskörtlar  
#### Ehdotettu termi englanniksi

gonads  
#### Vaihtoehtoiset termit ja ilmaisut

sukurauhaset  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)  
#### exactmatch

http://id.loc.gov/authorities/subjects/sh85055840  
#### Tarkoitusta täsmentävä selite

LT sukupuolielimet
LT umpirauhaset
ST kivekset
ST munasarjat  
#### Perustelut ehdotukselle

https://fi.wikipedia.org/wiki/Sukupuolirauhaset  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Accelerated aging after hematopoietic stem cell transplantation in childhood : early menopause, premature cardiovascular aging and frailty  

**Termiehdotus Fintossa:** [sukupuolirauhaset](http://finto.fi/yse/fi/page/Y504541)

**Comment by mirmaid** [comment]
Melinda: [5 viitettä](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-00705?func=short-0&set_number=062146) (2 kertaa sukurauhaset) (6.9.2016)

MeSHissä

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
