### ISSUE TITLE
dekoriini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4542]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

dekoriini  
#### exactmatch

https://en.wikipedia.org/wiki/Decorin  
#### Ehdotettu termi englanniksi

decorin  
#### Ehdotettu yläkäsite YSOssa (LT)

[proteiinit](http://www.yso.fi/onto/yso/p4332)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

The role of extracellular matrix macromolecules in cancer and diabetic macroangiopathy : with special reference to decorin and hyaluronan https://www.utu.fi/fi/Ajankohtaista/mediatiedotteet/vaitostiedotteet/Sivut/soluvaliaineen-muokkauksesta-hoitomahdollisuuksia-syopaan-ja-valtimotautiin.aspx  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Ehdotettu termi ruotsiksi

dekorin  
#### Perustelut ehdotukselle

väitöskirjassa käsitellään juuri tätä proteiinia  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[09 Kemia](http://www.yso.fi/onto/ysa/ryhma_09)  

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/ysa/ryhma_15)  

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/ysa/ryhma_48)  

**Termiehdotus Fintossa:** [dekoriini](http://finto.fi/yse/fi/page/Y504542)

**Comment by mirmaid** [comment]
Lääketieteen termit: proteoglykaani joka mm. estää erään transformoivan kasvutekijän toimintaa ja siten arpeutumista

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
