### ISSUE TITLE
elektroninen urheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4545]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

elektroninen urheilu  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)  

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

http://urn.fi/URN:NBN:fi:amk-2015121621090  
#### Ehdottajan nimi

Pirjo Kangas  
#### Ehdottajan organisaatio

Humak  
#### Ehdottajan sähköpostiosoite

pirjo.kangas@humak.fi  
#### Perustelut ehdotukselle

Elektroninen urheilu (engl. esports) tarkoittaa videopelien pelaamista kilpailumielessä ja on jo sen verran laajalle levinnyttä että ansaitsisi oman asiasanan. Aiheesta on myös kirjoitettu opinnäytetöitä. Elektronisella urheilulla on myös oma yhdistys: http://seul.fi/.  
#### Ehdotettu yläkäsite YSOssa (LT)

[urheilu](http://www.yso.fi/onto/yso/p965)  
#### Assosiatiiviset (ST)

[videopelit](http://www.yso.fi/onto/yso/p17281)  

**Termiehdotus Fintossa:** [elektroninen urheilu](http://finto.fi/yse/fi/page/Y504545)

**Comment by mirmaid** [comment]
Melinda: [1 viite](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-04045?func=short-0&set_number=063690) (6.9.2016)

**Comment by LeKorsu** [comment]
Hyvä ehdotus, pitää varmaan tehdä ohjaustermi e-urheilu KÄ elektroninen urheilu, sillä tuo e-urheilu on varmaan yleisesti käytetympi muoto.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016) (KT e-urheilu, e-sport)
