### ISSUE TITLE
matkailututkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4546]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

matkailututkimus  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Matkailututkimuksen lukukirja, ISBN 978-952-484-639-4  
#### Perustelut ehdotukselle

Meillä Lapin yliopistossa opetetaan matkailututkimusta ja nykyiset asiasanat matkailu ja tutkimus eivät erillisinä anna todellista kuvaa, varsinkin kun ketjutusta ei tehdä. En tiedä menikö tuo temaattinen ryhmä oikein, kun YKL:ssä luokka on 40.7  
#### Ehdottajan nimi

Tarja Juntunen-Niskasaari  
#### Ehdottajan organisaatio

Lapin Korkeakoulukirjasto /Lapin yliopisto  
#### Ehdottajan sähköpostiosoite

tarja.juntunen-niskasaari@ulapland.fi  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)  

**Termiehdotus Fintossa:** [matkailututkimus](http://finto.fi/yse/fi/page/Y504546)

**Comment by mirmaid** [comment]
Melinda: [13 viitettä](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-02769?func=short-0&set_number=064329) (6.9.2016)

http://www.ulapland.fi/FI/Yksikot/Yhteiskuntatieteiden-tiedekunta/Opinnot/Matkailututkimus

http://matkailututkimus.org/

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
