### ISSUE TITLE
seuralaislajit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4547]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

seuralaislajit  
#### Ehdotettu termi englanniksi

accompanying species  
#### Ehdotettu yläkäsite YSOssa (LT)

[lajit](http://www.yso.fi/onto/yso/p2765)  
#### Alakäsitteet (RT)

[asutuksen seuralaislajit](http://www.yso.fi/onto/yso/p5761)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)  
#### Perustelut ehdotukselle

YSAssa on asutuksen seuralaislajit, ehdotettu käsite on laajempi. Voidaan puhua esim. puulajin seuralaiskasveista, tietyllä alueella. Googlaamalla "seuralaislajit" löytyy viitteitä esim. tammen seuralaislajeista, mm. jäkälistä ja hyönteisistä- https://www.vantaa.fi/instancedata/prime_product_julkaisu/vantaa/embeds/vantaawwwstructure/119017_Luonnon_monimuotoisuus_raportti_2005.pdf  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Airola, K. : Hämeen metsälehmukset. Sorbifolia 47:2 (2016), s. 75-81. Taulukko 1. Metsälehmuksen yleisimmät seuralaislajit Hämeessä  
#### Ehdottajan nimi

Päivi Lipsanen  
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto  
#### Ehdottajan sähköpostiosoite

paivi.lipsanen@helsinki.fi  

**Termiehdotus Fintossa:** [seuralaislajit](http://finto.fi/yse/fi/page/Y504547)

**Comment by mirmaid** [comment]
Melinda: [3 viitettä](http://linda.linneanet.fi/F/UX9KAI463D643APF9VCJPPABTR19EPVVU9EKIN63CNLJQMDRL6-03248?func=short-0&set_number=064721) (6.9.2016)

Mennään metsään. Kuljetaan erilaisten metsätyyppien poikki ja mietitään kunkin puun elinpaikkavaatimuksia ja seuralaislajeja. http://www.luontokapinetti.fi/Puut

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
