### ISSUE TITLE
kyselytutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4550]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen  
#### preflabel

[kyselytutkimus](http://www.yso.fi/onto/ysa/Y96643)  
#### Tila

Käsittelyssä  
#### Ehdotettu muutos

Yritin ehdottaa uutta käsitettä 'kyselyt' (questionnaires), mutta lomake ei hyväksynyt ehdotusta, vaan sanoi käsitteen jo olevan YSAssa. Finton kautta en kuitenkaan löydä sitä YSA-terminä.  
#### Perustelut ehdotukselle

Kyselyt-termi on ainakin Kula- ja Helecon-sanastoissa ja Kielitieteen asiasanastossa ja ontologiassa. Se on tarpeellinen kyselytutkimuksen rinnakkaisterminä, koska kuvailtava kirjallisuus ei aina käsittele kyselyitä tutkimuksena, vaan toisinaan tarkastelun kohteena ovat nimenomaan itse kyselyt.  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi

**Comment by henriyli** [comment]
Hei ja kiitos palautteesta! Kyselyt termi löytyy täältä YSE-ehdotuksista: https://github.com/Finto-ehdotus/YSE/issues/2068 . Valitettavasti ehdotuslomake ei osannut aikaisemmin tehdä eroa termiehdotusten ja oikeiden YSA-termien välille. Nyt tämä ominaisuus on toteutettu ja lomake osaa näyttää linkin kyseiseen termiin/ehdotukseen fintossa http://finto.fi/yse/fi/page/Y355246 . Yritämme kehittää ehdotusprosessia jatkossa siihen suuntaan, että vastaavassa tilanteessa ehdottajaa kannustettaisiin tukemaan olemassa olevaa ehdotusta GitHubissa esimerkiksi kommentoimalla ja antamalla lisätietoja.
