### ISSUE TITLE
Kalevalan päivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4551]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

Kalevalan päivä  
#### Ehdotettu termi englanniksi

Kalevala Day (KT Kalevala's Day)  
#### Vaihtoehtoiset termit ja ilmaisut

Kalevalanpäivä, kalevalanpäivä  
#### Ehdotettu yläkäsite YSOssa (LT)

[vuotuisjuhlat](http://www.yso.fi/onto/yso/p1080)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)  
#### Ehdotettu termi ruotsiksi

Kalevaladagen  
#### Tarkoitusta täsmentävä selite
1. helmikuuta, Kalevalan päivä, suomalaisen kulttuurin päivä  
#### Perustelut ehdotukselle

Termiä on käytetty sisällönkuvailussa vain harvoin (Melindassa 7 kertaa, Artossa 8 kertaa), mutta koska tämän juhlapäivän nimestä näkee (varsinkin vanhoissa teksteissä) käytettävän myös yhteenkirjoitettua muotoa (Kalevalanpäivä), voisi sen ottamisesta asiasanastoon olla hyötyä.  
#### Ehdottajan nimi

Kristiina Näyhö  
#### Ehdottajan organisaatio

SKS:n kirjasto (Kula)  
#### Ehdottajan sähköpostiosoite

kristiina.nayho@finlit.fi  
#### exactmatch

https://fi.wikipedia.org/wiki/Kalevalan_päivä  

*\* Termiehdotus Fintossa:*\* [Kalevalan päivä](http://finto.fi/yse/fi/page/Y504551)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
