### ISSUE TITLE
jäteautonkuljettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4552]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

jäteautonkuljettajat  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Työturvallisuuden ja työhyvinvoinnin edistäminen jätteenkuljetuksissa  
#### Ehdotettu termi ruotsiksi

sopbilschaufför  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577)  
#### Ehdotettu yläkäsite YSOssa (LT)

[autonkuljettajat](http://www.yso.fi/onto/yso/p3003)  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  
#### Perustelut ehdotukselle

ammattinimeke
http://www.ammattinetti.fi/ammatit/detail/473_ammatti  

**Termiehdotus Fintossa:** [jäteautonkuljettajat](http://finto.fi/yse/fi/page/Y504552)

**Comment by mirmaid** [comment]
testi

**Comment by satuniininen** [comment]
testi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 14.9.2016)
