### ISSUE TITLE
kollokaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4553]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

kollokaatio  
#### Ehdotettu termi ruotsiksi

kollokation  
#### Ehdotettu termi englanniksi

collocation  
#### Vaihtoehtoiset termit ja ilmaisut

kollokaatiot  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557)  
#### exactmatch

Collocation (Linguistics) http://id.loc.gov/authorities/subjects/sh92000804  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Collocations cross-linguistically : corpora, dictionaries and language teaching  
#### Ehdottajan nimi

Satu Niininen  
#### Ehdottajan sähköpostiosoite

satu.niininen@helsinki.fi  
#### Perustelut ehdotukselle

Wikipedia: Kollokaatio tarkoittaa sanojen taipumusta esiintyä yhdessä vakiintuneena ilmauksena.
Tieteen termipankki: usein yhdessä esiintyvien sanojen muodostama kokonaisuus

Melindassa yksikössä 14 krt, monikossa 41 krt.  

**Termiehdotus Fintossa:** [kollokaatio](http://finto.fi/yse/fi/page/Y504553)

**Comment by mirmaid** [comment]
Kielitieteen asiasanastossa monikossa. Molemmat vaihtoehdot perusteltavissa...

**Comment by LeKorsu** [comment]
Termi ok, yksikkö vai monikko mietityttää, ei selkeää kantaa.

**Comment by mirmaid** [comment]
Hyväksytty monikossa (YSA-kokous 14.9.2016)
