### ISSUE TITLE
alkalimetallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4555]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

alkalimetallit  
#### Ehdotettu termi ruotsiksi

alkalimetaller  
#### Ehdotettu termi englanniksi

alkali metals  
#### Ehdotettu yläkäsite YSOssa (LT)

[alkuaineet](http://www.yso.fi/onto/yso/p4407)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[09 Kemia](http://www.yso.fi/onto/yso/p26531)  
#### exactmatch

Alkali metals  
#### Tarkoitusta täsmentävä selite

toinen LT metallit
ST  natrium, kalium, cesium 

https://fi.wikipedia.org/wiki/Alkalimetalli
https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4ryhm%C3%A4_%28kemia%29  
#### Perustelut ehdotukselle

Alkuaineiden jaksollisen järjestelmän ensimmäinen pääryhmä.
käytetty Melindassa x 5 + alkalimetalli x 2  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  

**Termiehdotus Fintossa:** [alkalimetallit](http://finto.fi/yse/fi/page/Y504555)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
