### ISSUE TITLE
litium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4556]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

litium  
#### Ehdotettu termi englanniksi

lithium  
#### Ehdotettu termi ruotsiksi

litium  
#### Ehdotettu yläkäsite YSOssa (LT)

[alkuaineet](http://www.yso.fi/onto/yso/p4407)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[09 Kemia](http://www.yso.fi/onto/yso/p26531)  
#### exactmatch

Litium  
#### Tarkoitusta täsmentävä selite

toinen LT metallit (tai ehdotettu termi alkalimetallit)  
#### Perustelut ehdotukselle

Alkuaine
Melindassa x 11  
#### Ehdottajan nimi

Ilona Lindfors  
#### Ehdottajan organisaatio

Kansalliskirjasto  
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi  

**Termiehdotus Fintossa:** [litium](http://finto.fi/yse/fi/page/Y504556)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
