### ISSUE TITLE
skotinkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4557]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

skotinkielinen kirjallisuus  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564)  
#### Perustelut ehdotukselle

Skotin kielelle löytyy oma marc-koodinsakin sco. Myös asiasanoitusta olisi mukava käyttää esim kaunokirjallisuuden tiedonhaussa.  
#### exactmatch

https://fi.wikipedia.org/wiki/Skotin_kieli myös LEXVOssa  
#### Ehdottajan nimi

Petra Unkila  
#### Ehdottajan organisaatio

Tampereen kaupunginkirjasto  
#### Ehdottajan sähköpostiosoite

petra.unkila@tampere.fi  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Billionaire Bairn : Billionare boy in scots https://www.worldcat.org/title/billionaire-bairn-billionaire-boy-in-scots/oclc/928836426&referer=brief_results  

**Termiehdotus Fintossa:** [skotinkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y504557)

**Comment by mirmaid** [comment]
Melindassa 5 kertaa. Otetaan samalla myös skotin kieli (38 kertaa).

**Comment by LeKorsu** [comment]
Minä olen kuvitellut tähän asti, että Skotlannin oma kieli on suomeksi gaelin kieli, mutta wikipedia sivistää tässäkin, Scots languagea ei kuulemma saa sekoittaa gaeliin https://en.wikipedia.org/wiki/Scots_language.  Pitäisikö samalla ottaa mukaan myös gaelin kieli?

**Comment by mirmaid** [comment]
Lexvossa gla-kielikoodin nimi on kanadangaeli, joka on kylläkin vain yksi murre...

**Comment by MikkoAleksanteri** [comment]
Ihan vaan pohdiskelen ääneen,  tarvitaanko YSAan aina sekä kieli, että kyseisenkielinen kirjallisuus omaksi käsitteekseen? Eikö riittäisi kielen nimi ja käsite kirjallisuus? Maailmassa on joidenkin arvioiden mukaan n 6000-9000 kieltä...

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
