### ISSUE TITLE
språkundervisning

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4558]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

kielenopetus, kieltenopetus  
#### Ehdotettu termi ruotsiksi

språkundervisning  
#### Ehdotettu termi englanniksi

language teaching  
#### exactmatch

Language and languages - Study and teaching  
#### Ehdotettu yläkäsite YSOssa (LT)

[undervisning](http://www.yso.fi/onto/yso/p2630)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Uppfostran. Undervisning. Utbildning](http://www.yso.fi/onto/yso/p26554)  
#### Perustelut ehdotukselle

Använt i Melinda 86 gånger som Allärs-term. Även kielenopetus och kieltenopetus har använts. Finns också i t.ex. Svenska ämnesord (vilken anger ovan nämnda LCSH-term som motsvarande). Om dessa inte godkänns till Allärs/YSA borde man gå igenom alla posterna i Melinda och korrigera.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Se Melinda.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  
#### Assosiatiiviset (RT)

[språkinlärning](http://www.yso.fi/onto/yso/p24061)  

**Termiehdotus Fintossa:** [språkundervisning](http://finto.fi/yse/fi/page/Y504558)

**Comment by mirmaid** [comment]
Myös ehdotus #1436

**Comment by mirmaid** [comment]
Selvitetään mahdollisuutta viedä takautuvasti tietueisiin.

**Comment by LeKorsu** [comment]
Kannatan muotoa kieltenopetus.

**Comment by vthuhtala** [comment]
Helkassa
- kielenopetus (kta) 299 kpl
- kielet--opetus (ysa) 2624 kpl

**Comment by YSA-kokous** [comment]
kieltenopetus

**Comment by mirmaid** [comment]
Pitäisikö kuitenkin ottaa muoto _kielten opetus_, jolloin tarttuisi myös hakuihin joissa yhdistetään tietty kieli & opetus?

**Comment by LeKorsu** [comment]
Yhteenkirjoitetulla kieltenopetuksella tulee googlaamalla huomattavasti enemmän osumia kuin kielten opetuksella, jotka toki molemmat kieliopillisesti oikein. Kannatan edelleen yhdyssanamuotoa.

**Comment by YSA-kokous** [comment]
kieltenopetus KT kielten opetus
