### ISSUE TITLE
rapportskrivning

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4559]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

raportin kirjoittaminen  
#### Ehdotettu termi ruotsiksi

rapportskrivning  
#### Ehdotettu termi englanniksi

report writing  
#### Ehdotettu yläkäsite YSOssa (LT)

[skrivande](http://www.yso.fi/onto/yso/p2512)  
#### Assosiatiiviset (ST)

[rapportering](http://www.yso.fi/onto/yso/p668)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[80 Kommunikation. Informationsförmedling. Masskommunikation. Reklam](http://www.yso.fi/onto/yso/p26547)  
#### exactmatch

report writing  
#### Perustelut ehdotukselle

Använt 88 gånger i Melinda (även som SAO-term i brist på auktoriserad Allärs-term). Finns alltså också i Svenska ämnesord (vilken anger report writing som motsvarande LCSH-term). Behövs för litteratur som behandlar hur man skriver rapporter. Rapporter är inte nödvändigtvis "vetenskapligt skrivande", de författas även i arbetslivet mm.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Se referenserna i Melinda.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [rapportskrivning](http://finto.fi/yse/fi/page/Y504559)

**Comment by mirmaid** [comment]
YSAssa on tieteellinen kirjoittaminen ja vähän vastaava ainekirjoitus. 

Suomeksi on käytetty ketjua raportit -- kirjoittaminen (tai yhdistelmää raportit & kirjoittaminen). Ei raportinkirjoitus tai raportin kirjoittaminen.

**Comment by mariaforsen** [comment]
Ruotsin kannalta ei ole mahdollista käyttää tieteellinen kirjoittaminen tai ainekirjoitus (aivan eri asia) synonyminä rapportskrivning-termille.

**Comment by mirmaid** [comment]
Joo en siis tarkoittanut että ainekirjoitus olisi sisällöltään samansuuntainenkaan, vaan että se on samantyyppinen "kirjoituksen lajityyppi", noin taustaksi.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
