### ISSUE TITLE
positionering (marknadsföring)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4561]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

positiointi, asemointi  
#### Ehdotettu termi ruotsiksi

positionering (marknadsföring)  
#### Ehdotettu termi englanniksi

positioning (advertising)  
#### exactmatch

Positioning (advertising)  
#### Ehdotettu yläkäsite YSOssa (LT)

[marknadsföring](http://www.yso.fi/onto/yso/p5878)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538)  
#### Tarkoitusta täsmentävä selite

Nationalencyklopedin: "de åtgärder en organisation eller ett företag vidtar för att få människor att uppfatta en produkt eller ett varumärke på ett visst sätt"  
#### Perustelut ehdotukselle

Använt 30 gånger i Melinda, även på finska (bägge ovannämnda).  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Se referenserna i Melinda.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [positionering (marknadsföring)](http://finto.fi/yse/fi/page/Y504561)

**Comment by mirmaid** [comment]
Melinda: positiointi 22 kertaa, asemointi 27 kertaa. Ei aina markkinointia?

YSAssa on _erottautuminen_, _brändäys_, _segmentointi_.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi tämä käsitellään eri asiana kuin marknadsföring ja myös suomeksi näyttää olevan aika tarkkaan määritelty? (ks. esim. https://mycourses.aalto.fi/pluginfile.php/358118/mod_resource/content/1/Luento_3_kohdeasiakkaiden%20valinta.pdf )

**Comment by mirmaid** [comment]
Hyväksytty muodossa positiointi (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Sv. positionering (marknadsföring) ET positionering

**Comment by mirmaid** [comment]
Tämä tarvitsisi luultavasti tarkenteen, positioinnista puhutaan myös yhteiskuntatieteissä, erityisesti sosiaalipsykologiassa. Mahdollisesti silloin sopisi positiointiteoria.

**Comment by mariaforsen** [comment]
Eikö markkinointi kävisi suomeksikin tarkenteena?

**Comment by YSA-kokous** [comment]
Positiointi (markkinointi).
