### ISSUE TITLE
företagsetablering

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4562]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

yrityksen perustaminen/etabloituminen?  
#### Ehdotettu termi ruotsiksi

företagsetablering  
#### Ehdotettu termi englanniksi

establishment/formation of a company?  
#### Vaihtoehtoiset termit ja ilmaisut

grundande av företag, inledande av företagsverksamhet  
#### Ehdotettu yläkäsite YSOssa (LT)

[grundande](http://www.yso.fi/onto/yso/p11600)  
#### Assosiatiiviset (ST)

[företagsplanering](http://www.yso.fi/onto/yso/p5157)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538)  
#### Perustelut ehdotukselle

Använt i Melinda 210 gånger (på finska 323 gånger, bl.a. som helecon-term)  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Se Melinda.  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [företagsetablering](http://finto.fi/yse/fi/page/Y504562)

**Comment by mirmaid** [comment]
Yrityksen perustaminen löytyy Melindasta 323 kertaa. Ketju yritykset -- perustaminen löytyy 881 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty muodossa yrityksen perustaminen (YSA-kokous 13.12.2016)
