### ISSUE TITLE
företagsvärdering

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4563]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

yrityksen arvonmääritys  
#### Ehdotettu termi ruotsiksi

företagsvärdering  
#### Perustelut ehdotukselle

Använt 99 gånger i Melinda.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Se referenserna i Melinda.  
#### Ehdotettu termi englanniksi

company valuation?  
#### Ehdotettu yläkäsite YSOssa (LT)

[värdering](http://www.yso.fi/onto/yso/p9877)  
#### Assosiatiiviset (RT)

[företagsanalys](http://www.yso.fi/onto/yso/p14851)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538)  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan organisaatio

ÅAB  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [företagsvärdering](http://finto.fi/yse/fi/page/Y504563)

**Comment by mirmaid** [comment]
Suomeksi Melindassa 2 kertaa. Ketjua yritykset -- arvonmääritys käytetty 49 kertaa.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mariaforsen** [comment]
Ajankohtainen kirja:  Yrityksen arvonmääritys /Harri Seppänen, 2017

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
företagsvärdering
