### ISSUE TITLE
koncernredovisning

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4564]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi ruotsiksi

koncernredovisning  
#### Ehdotettu termi englanniksi

consolidated financial statement?  
#### Ehdotettu termi suomeksi

konsernitilinpäätös  
#### Perustelut ehdotukselle

Använt 71 gånger i Melinda (på finska 14 gånger). Finsk och engelsk motsvarighet från IATE/MOT m.fl.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Se referenserna i Melinda.  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538)  
#### Ehdotettu yläkäsite YSOssa (LT)

[redovisning](http://www.yso.fi/onto/yso/p7621)  
#### Ehdottajan nimi

Maria Forsén  
#### Ehdottajan sähköpostiosoite

maria.forsen@abo.fi  

**Termiehdotus Fintossa:** [koncernredovisning](http://finto.fi/yse/fi/page/Y504564)

**Comment by mirmaid** [comment]
Pankki- ja rahoitussanasto: Konsernin emoyrityksen laatima tilinpäätös, johon on yhdistelty konserniyritysten tilinpäätökset. (Ketju konsernit -- tilinpäätös 127 kertaa.)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
