### ISSUE TITLE
veripankit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4565]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

veripankit  
#### Ehdotettu termi englanniksi

blood banks  
#### exactmatch

Blood banks  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)  
#### Tarkoitusta täsmentävä selite

MeSH asiasana Blood banks  
#### Perustelut ehdotukselle

Käytetty veripankit -termiä vapaana asiasanana Melindassa usean teoksen kohdalla  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Banking on the body : the market in blood, milk, and sperm in modern America  
#### Ehdottajan nimi

Tarja Turunen  
#### Ehdottajan organisaatio

UEF  
#### Ehdottajan sähköpostiosoite

tarja-liisa.turunen@uef.fi  
#### Ehdotettu yläkäsite YSOssa (LT)

[biopankit](http://www.yso.fi/onto/yso/p10731)  

**Termiehdotus Fintossa:** [veripankit](http://finto.fi/yse/fi/page/Y504565)

**Comment by mirmaid** [comment]
11 kertaa Melindassa FinMeSH-terminä tai vapaana asiasanana.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
