### ISSUE TITLE
maitopankit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4566]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

maitopankit  
#### Ehdotettu termi englanniksi

milk banks  
#### Ehdotettu yläkäsite YSOssa (LT)

[biopankit](http://www.yso.fi/onto/yso/p10731)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)  
#### Tarkoitusta täsmentävä selite

MeSH asiasana Milk Banks  
#### Perustelut ehdotukselle

Käytetty yhdessä teoksessa vapaana asiasanana Melindassa  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Banking on the body : the market in blood, milk, and sperm in modern America  
#### Ehdottajan nimi

Tarja Turunen  
#### Ehdottajan organisaatio

UEF  
#### Ehdottajan sähköpostiosoite

tarja-liisa.turunen@uef.fi  

**Termiehdotus Fintossa:** [maitopankit](http://finto.fi/yse/fi/page/Y504566)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
