### ISSUE TITLE
spermapankit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4567]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

spermapankit  
#### Ehdotettu termi englanniksi

sperm banks  
#### Ehdotettu yläkäsite YSOssa (LT)

[biopankit](http://www.yso.fi/onto/yso/p10731)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)  
#### exactmatch

Sperm banks  
#### Tarkoitusta täsmentävä selite

MeSH asiasana Sperm Banks  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Banking on the body : the market in blood, milk, and sperm in modern America  
#### Perustelut ehdotukselle

Olisin tarvinnut tätä asiasanaa sisällönkuvailussa  
#### Ehdottajan nimi

Tarja Turunen  
#### Ehdottajan organisaatio

UEF  
#### Ehdottajan sähköpostiosoite

tarja-liisa.turunen@uef.fi  

**Termiehdotus Fintossa:** [spermapankit](http://finto.fi/yse/fi/page/Y504567)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
