### ISSUE TITLE
arvokisat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4568]
#### Käsitteen tyyppi

CONCEPT  
#### Ehdotettu termi suomeksi

arvokisat  
#### Ehdotettu yläkäsite YSOssa (LT)

[urheilukilpailut](http://www.yso.fi/onto/yso/p1934)  
#### Alakäsitteet (RT)

[olympialaiset](http://www.yso.fi/onto/yso/p7930)  
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)  
#### exactmatch

https://fi.wikipedia.org/wiki/Arvokisa  
#### Perustelut ehdotukselle

Kokoava termi urheilun kansainvälisille mestaruuskilpailuille. Tietenkin myös oman maan mestaruuskisat ovat arvokisat, mediassa tätä on kuitenkin käytetty nimenomaan kv-urheilukilpailujen yhteydessä. Lisää ST: maailmanmestaruuskisat, Euroopan mestaruuskisat. Arvokisat on urheilujournalismissa yleisesti käytetty termi.  
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Esim. artikkeli Urheilusanomissa (2015), joka käsitteli urheilijoiden apurahoja ja menestystä arvokisoissa.  
#### Ehdottajan nimi

Leena Korsumäki  
#### Ehdottajan organisaatio

Yle Arkisto  
#### Ehdottajan sähköpostiosoite

leena.korsumaki@yle.fi  

**Termiehdotus Fintossa:** [arvokisat](http://finto.fi/yse/fi/page/Y504568)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: arvokilpailu: vars. urh., tav. mon. huomattava kilpailu. 

Käytetty välillä löyhemmin kuin MM-, EM- jne. ja olympialaisista, mutta ehkä silti riittävän selkeärajainen?

**Comment by mariaforsen** [comment]
Entä mestaruuskilpailu/mestaruuskisa?

**Comment by LeKorsu** [comment]
Olympialaisista ei puhuta mestaruuskilpailuina, siksi arvokisat olisi mielestäni parempi kokoava termi.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
