### ISSUE TITLE
käsiohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4570]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[käsiohjelmat](http://www.yso.fi/onto/ysa/Y200911) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Lisätään LT-suhde: "pienpainatteet" 
#### Perustelut ehdotukselle

Käsiohjelmat ovat pääsääntöisesti sivumäärältään vähäisiä, painokseltaan pieniä, sidottu myytävien tapahtumalippujeen määrään ja vain rajatussa jakelussa, joten useampikin pienpainatteeen kriteeri täyttyy helposti. 
#### Ehdottajan nimi

Jaakko Tuohiniemi 
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto 
#### Ehdottajan sähköpostiosoite

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
LT-suhde lisätty
