### ISSUE TITLE
retoromaanin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4571]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

retoromaanin kieli 
#### Ehdotettu termi ruotsiksi

rätoromanska 
#### Ehdotettu termi englanniksi

Raeto-Romance language; Romansh; Romansh language 
#### Vaihtoehtoiset termit ja ilmaisut

retoromaani 
#### Ehdotettu yläkäsite YSOssa (LT)

[romaaniset kielet](http://www.yso.fi/onto/yso/p2888) 
#### exactmatch

Raeto-Romance language 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 
#### Ehdottajan nimi

Jaakko Tuohiniemi 
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto 
#### Ehdottajan sähköpostiosoite

jaakko.tuohiniemi@helsinki.fi 
#### Perustelut ehdotukselle

HYK:ssä esimerkiksi on luokka retoromaania käsittelevälle aineistolle ja termiä on käytetty jo vanhastaan vapaan indeksoinnin puitteissa 

**Termiehdotus Fintossa:** [retoromaanin kieli](http://finto.fi/yse/fi/page/Y504571)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016) (KT retoromanin kieli)
