### ISSUE TITLE
Halle an der Saale

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4572]
#### Käsitteen tyyppi

GEO 
#### Ehdotettu termi suomeksi

Halle an der Saale 
#### Ehdotettu termi ruotsiksi

Halle an der Saale 
#### exactMatch

LCSH : Halle an der Saale (Germany) 
Englanninkielinen Wikipedia : Halle (Saale) 
#### Vaihtoehtoiset termit ja ilmaisut

Halle (Saale) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Händels Weg von Rom nach London 
#### Perustelut ehdotukselle

Kyseistä kaupunkia ei vielä ole auktorisoitu Ysaan [huom: maantieteellinen termi, ei temaattisen ryhmän 11 termi - mutta kun ei voinut jättää lomakkeella tyhjäksi] 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 
#### Tarkoitusta täsmentävä selite

Pelkkä käsite "Halle" ei käy, koska on useita samannimisiä paikkakuntia, myös Saksassa. RDA:n §16.2.2.4 ja 16.2.2.13 mukainen nimenmuoto olisi "Halle an der Saale (Saksa)" tai "Halle (Saksi-Anhalt, Saksa)", jos an der Saale -nimitystä ei valita osaksi nimenmuotoa. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Halle an der Saale](http://finto.fi/yse/fi/page/Y504572)

**Comment by mirmaid** [comment]
Auktorisoitu 22.12. muodossa Halle an der Saale.
