### ISSUE TITLE
Augsburg

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4574]
#### Käsitteen tyyppi

GEO 
#### Ehdotettu termi suomeksi

Augsburg 
#### Ehdotettu termi ruotsiksi

Augsburg 
#### Ehdotettu termi englanniksi

Augsburg 
#### exactMatch

LCSH : Augsburg (Germany) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Beiträge des Internationalen Leopold-Mozart-Kolloquiums, Augsburg 1994 
#### Tarkoitusta täsmentävä selite

Useita samannimisiä paikkakunta, joten vaatii täsmenteen, RDA:n mukainen muoto olisi "Augsburg (Saksa)" 
#### Perustelut ehdotukselle

Käytetty Melindassa asiasanana jo 102 kertaa... 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Augsburg](http://finto.fi/yse/fi/page/Y504574)

**Comment by mirmaid** [comment]
Onko tosiaan tarpeen erotella tarkenteilla kaikki kaupungit, joita on useampia samannimisiä? Esim. Dublin-nimisiä kaupunkeja on Yhdysvalloissakin ainakin kolme, mutta YSA tuntee vain Irlannissa sijaitsevan, ilman tarkennetta. Jos tämä otetaan periaatteeksi, pitäisi tarkenteita lisätä jo olemassaoleviin maantieteellisiin termeihin varmaan aika paljon.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
Augsburg
