### ISSUE TITLE
Salzburg

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4575]
#### Käsitteen tyyppi

GEO 
#### Ehdotettu termi suomeksi

Salzburg 
#### Ehdotettu termi ruotsiksi

Salzburg 
#### Ehdotettu termi englanniksi

Salzburg 
#### exactMatch

LCSH : Salzburg (Austria) 
#### Perustelut ehdotukselle

Melindassa käytetty asiasanana jo 120 kertaa... 
#### Tarkoitusta täsmentävä selite

Vaatii täsmenteen, jotta viittaa itävaltalaiseen Salzburgin osavaltion pääkaupunkiin eikä muihin (ks. esim. https://en.wikipedia.org/wiki/Salzburg_%28disambiguation%29), RDA:n mukaan siis "Salzburg (Itävalta)". 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Beiträge des Internationalen Leopold-Mozart-Kolloquiums, Augsburg 1994 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Salzburg](http://finto.fi/yse/fi/page/Y504575)

**Comment by mirmaid** [comment]
Tarkenne (Itävalta) ei kuitenkaan erottele tätä Salzburgin osavaltiosta. Kaupunki on SAOssa ja GND:ssä ilman tarkennetta.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017), ei tarkennetta.

**Comment by mariaforsen** [comment]
Allärs:
Salzburg
