### ISSUE TITLE
sosiaaliset konfliktit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4577]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

sosiaaliset konfliktit 
#### Ehdotettu termi englanniksi

social conflicts 
#### exactMatch

LCSH : Social conflict 
#### Tarkoitusta täsmentävä selite

"...sosiaalinen konflikti on vuorovaikutus
- toimijoiden välillä (yksilöt, ryhmät, organisaatiot jne.)
- jossa ainakin yksi toimija
- kokee yhteensopimattomuuden omien ja toisen toimijan/toimijoiden
  
  ajatusten/ideoiden/käsitysten
  ja/tai tunteiden
  ja/tai tahdon kanssa
- ja tuntee toisen toiminnan tuovat rajoituksia itselle" (http://tieteentermipankki.fi/wiki/Oikeustiede:konflikti) 
#### Perustelut ehdotukselle

Tarve käyttää sisällönkuvailussa. Käytetty vapaana asiasanana ja YSAn asiasanana Melindassa. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

"Class : feminist and cultural perspectives" 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan organisaatio:** UEF 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [sosiaaliset konfliktit](http://finto.fi/yse/fi/page/Y504577)

**Comment by mirmaid** [comment]
Käytetty Melindassa 10 kertaa. YSAssa on _sosiaaliset ristiriidat_, joka on linkattu YSOssa LC:n Social conflict -termiin.

**Comment by mariaforsen** [comment]
Sociala konflikter on jo Allärsissa vastineena sosiaaliset ristiriidat -termille.

**Comment by LeKorsu** [comment]
Jompikumpi ohjaustermiksi?

**Comment by mirmaid** [comment]
KÄ sosiaaliset ristiriidat
