### ISSUE TITLE
feministinen teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4578]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

feministinen teoria 
#### Ehdotettu termi englanniksi

Feminist theory 
#### exactMatch

LCSH : Feminist theory 
#### Perustelut ehdotukselle

Olen tarvinnut ko. asiasanaa usein sisällönkuvailussa. Käytetty usean teoksen sisällönkuvailussa Melindassa seka vapaan asiasanana että YSAn asiasanana. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

"Class : feminist and cultural perspectives" 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan organisaatio:** UEF 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [feministinen teoria](http://finto.fi/yse/fi/page/Y504578)

**Comment by mirmaid** [comment]
Käytetty Melindassa 77 kertaa (2 kertaa monikossa). https://en.wikipedia.org/wiki/Feminist_theory

**Comment by mariaforsen** [comment]
Myös feministisk teori on paljon käytetty Melindassa ja on myös SAOssa.

**Comment by AuHo22** [comment]
Kuinka pitkälle on sama tai eri asia kuin feministinen tutkimus (joka on YSA-termi). Ks. esim. https://fi.wikipedia.org/wiki/Sukupuolitutkimus

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Asiantuntijan kommentti: 
Feministinen tutkimus on hyvin laaja kategoia, siihen voi kuulua tutkimuksia hyvin erilaisilta tieteenaloilta, ja lisäksi kaikki sellainen kirjallisuus, joka nimenomiasesti tarkastelee feministiseen tutkiseen liittyviä kysymyksiä, tieteenteoriaa, käytäntöjä, tutkimusetiikka jne. Feminististä tutkimusta voidaan tehdä ja tarkastella hyvin monella tieteenalalla.

Feministinen teoria taas on selkeästi erottuva sukupuolentutkimuksen tieteenalaan liittyvä kirjallisuuden laji, jossa on omat klassikkonsa ja nykyklassikkonsa (esim. sellaisia nimiä kuin Kate Millett, Luce Irigaray, Judtih Butler, Sarah Ahmed), ja jossa liikutaan usein filosofian, psykoanalyyisin, kriittisen teorian jne. teoriakeskustelujen parissa. Feministinen teoria on yleensä selkeästi yksi kohta sukupuolentutkimuksen tutkintovaatimuksissa ja uskoisin, että feministinen teoria esiintyy nykyisin hyvin usein asiasanana journal artikkeleissa ja kirjoissa, joissa otetaan osaa teoriakeskusteluun ja kommentoidaan teoreetikoita.   

Eli vastaukseni lyhyesti on; näillä kahdella ei viitata samaan asiaan, ja ne on mahdollista erottaa kun on kyse kirjojen ja artikkeleiden kuvailusta.

**Comment by AuHo22** [comment]
Termi _feministinen filosofia_ olemassa YSA:ssa - kuinka poikkeaa tästä, poikkeaako?
Esim. https://fi.wikipedia.org/wiki/Feministinen_filosofia

**Comment by AuHo22** [comment]
YSAssa esim. yhteiskuntafilosofia ja yhteiskuntateoriat ; kasvatusfilosofia ja kasvatusteoriat -> samoin:
feministinen filosofia ja feministiset teoriat? Erilaisia feministisiä teorioita on selkeästi erotettavissa:
feministinen tietoteoria tai feministinen poliittinen teoria esimerkiksi

**Comment by mirmaid** [comment]
Hyväksytty yksikössä (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
feministisk teori 
ET feministteori
