### ISSUE TITLE
siemen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4579]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[siemen](http://www.yso.fi/onto/ysa/Y102887) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

muotoon siemenet 
#### Perustelut ehdotukselle

Monikkomuotoa olisi luontevampi käyttää esim. teoksessa Pähkinäkirja, joka sisältää ruokaohjeita pähkinöistä ja siemenistä.

YSAssa on kasvinosien nimiä melko sattumanvaraisesti yksikössä ja monikossa, joten sikäli ei ole estettä muuttaa tätäkin. Monikkomuoto näyttäsi sopivan myös Melinda-osumiin. 
#### Ehdottaja

Satu Niininen 
#### Ehdottajan organisaatio

Kansalliskirjasto 
#### Ehdottajan sähköpostiosoite

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
frön
