### ISSUE TITLE
vakat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4589]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

vakat 
#### Ehdotettu termi englanniksi

vakka container? 
#### Ehdotettu yläkäsite YSOssa (LT)

[säilytysastiat](http://www.yso.fi/onto/yso/p22127) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Vakka Suomessa: Pentti ja Anne Siivosen vakkakokoelma /Matti Jussila, Wenzel Hagelstam 
#### Perustelut ehdotukselle

Hyvä ja täsmällinen käsite, joskin hankala kääntää. 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [vakat](http://finto.fi/yse/fi/page/Y504589)

**Comment by mirmaid** [comment]
Käytetty Melindassa 2 kertaa. MAO-ontologiassa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
