### ISSUE TITLE
jätteiden käsittely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4643]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[jätteiden käsittely](http://www.yso.fi/onto/ysa/Y95709) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

KT jätteenkäsittely 
#### Ehdottaja

Ilona Lindfors 
#### Ehdottajan organisaatio

Kansalliskirjasto 
#### Ehdottajan sähköpostiosoite

ilona.lindfors@helsinki.fi 
#### Perustelut ehdotukselle

tämä usein käytetty muoto olisi hyvä lisätä ohjaustermiksi

**Comment by mirmaid** [comment]
JUPOssa ja TSR-ontologiassa käytettävä muoto on jätteenkäsittely. Käytetty Melindassa 5 kertaa tässä muodossa, 580 kertaa jätteiden käsittely. Google: ~36000/62000.

**Comment by mirmaid** [comment]
Hyväksytty ohjaustermiksi (YSA-kokous 7.3.2017).
