### ISSUE TITLE
tylosiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4644]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

tylosiini 
#### Ehdotettu termi englanniksi

tylosin 
#### Ehdotettu yläkäsite YSOssa (LT)

[antibiootit](http://www.yso.fi/onto/yso/p10820) 
#### exactMatch

MeSH : tylosin 
#### Perustelut ehdotukselle

Tarvitaan suomalaisen väitöskirjan kuvailuun 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Väitöskirja https://helda.helsinki.fi/handle/10138/166110?show=full 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [tylosiini](http://finto.fi/yse/fi/page/Y504644)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
