### ISSUE TITLE
Kaposin sarkooma herpesvirus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4647]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

Kaposin sarkooma herpesvirus 
#### Ehdotettu termi englanniksi

Kaposi's sarcoma herpesvirus 
#### Ehdotettu yläkäsite YSOssa (LT)

[herpesvirukset](http://www.yso.fi/onto/yso/p21634) 
#### Assosiatiiviset (ST)

[Kaposin sarkooma](http://www.yso.fi/onto/yso/p27835) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
#### Vaihtoehtoiset termit ja ilmaisut

KSHV 
#### Perustelut ehdotukselle

Tarvitaan suomalaisen väitöskirjan kuvailuus 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://helda.helsinki.fi/handle/10138/166350 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [Kaposin sarkooma herpesvirus](http://finto.fi/yse/fi/page/Y504647)

**Comment by mirmaid** [comment]
FinMeSHissä _Ihmisen herpesvirus 8_, myös muotoa _Kaposin sarkoomaan liittyvä herpesvirus_ käytetään.

**Comment by mirmaid** [comment]
Hyväksytty muodossa ihmisen herpesvirus 8 (YSA-kokous 13.12.2016)
