### ISSUE TITLE
funktionalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4648]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[funktionalismi](http://www.yso.fi/onto/ysa/Y95189) 
#### Tila

Käsittelyssä 
#### Perustelut ehdotukselle

LCSH: Functionalism (Architecture), Functionalism (Psychology), Functionalism (Social sciences)

Melidassa funktionalismi 501 kertaa, joista 207:ssä mukana myös arkkitehtuuri. Loput merkitykset noudattelevat pääsääntäisesti LCSH:n jaottelua (joskin esim. psychology- ja social sciences -merkityksiä on usein hankala erottaa toisistaan), mutta paljon myös (teollista)muotoilua. Loput tapauksista ovat sekalaisia ja osin virheellisiäkin. 
#### Ehdotettu muutos

Termi on jossain määrin monimerkityksinen. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ratkaisuvaihtoehdot:
1.  Erotetaan ns. tieteellinen ja taiteellinen merkitys toisistaan esim. tarkenteilla funktionalismi (tyylit) ja funktionalismi (teoriat). Teoriat-merkitys kattaisi psykologian, yhteiskuntatieteet ja kielitieteen, tyylit puolestaan arkkitehtuurin, muotoilun ja muut mahdollisesti vastaantulevat tyylisuuntaukset.
2.  Tulkitaan funktionalismin tarkoittavan kaikissa käyttötapauksissa pohjimmiltaan samaa ilmiötä, joka realisoituu eri aloilla eri tavoin. Luotetaan, että muut kuvailussa käytetyt käsitteet riittävät ohjaamaan relevantteihin hakutuloksiin

**Comment by AuHo22** [comment]
Funktionalistista taideteoriaakin on olemassa eli jaottelu funktionalismi (tyylit) ja funktionalismi (teoriat) voi olla siinä hankala?

**Comment by mirmaid** [comment]
Ei jaeta. (YSA-kokous 6.10.2016)
