### ISSUE TITLE
haku

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4649]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[haku](http://www.yso.fi/onto/ysa/Y112723) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Pitäisi mahdollisesti jakaa 
#### Perustelut ehdotukselle

Käytetty eri merkityksissä: viran tai opiskelupaikan haku (toisaalta myös rekrytoinnin näkökulmasta, suorahaku), apurahan tai etuuden haku, tiedonhaku, henkilön etsiminen hakukoiran avulla. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Suomenkielen näkökulmasta viran ja apurahan kohdalla kyse varmaan on samasta käsitteestä (pyrkiä saamaan jotain itselleen) – sama pätee myös opiskelupaikan hakuun ja etuuden hakuun. Sen sijaan haku merkityksessä _etsiminen_ voisi ohjata KÄ _etsintä_ ja _tiedonhaulle_ on myös oma terminsä. 

Työvoiman haku KÄ rekrytointi, henkilöstöhankinta?

**Comment by mirmaid** [comment]
Ruotsiksi: 

hakea (yrittää saada), pyrkiä (yrittää päästä), hakeutua: **söka** (söka en tjänst, söka ändring i domen, söka till en utbildning; 

anoa (tehdä hakemus), hakea (anoa), pyytää: **ansöka** (esim. kansalaisuutta). 

Tarvitaanko ansökning välttämättä siis etuuden/apurahan hakua varten, eikö näissä käy sökning?

**Comment by mariaforsen** [comment]
Kenellekään ei varmaan tule mieleen laittaa sökning etuuden/apurahan kontekstissa, mutta sitten täytynee käyttää ansökningar tms. Ja jos ohjataan etsiminen etsintä-termille niin voidaan varmaan ruotsiksi tehdä jokin vastaava ohjaus termille "letande". Mitään molempia kieliä tyydyttävä ratkaisu ei kuitenkaan taida olla mahdollista saada tässä tapauksessa.

**Comment by mirmaid** [comment]
Ohjataan haku (etsiminen) KÄ etsintä ja haku (tiedonhaku) KÄ tiedonhaku. 
Jatketaan muiden selvittelyä. (YSA-kokous 6.10.2016) Ks. myös hakemukset.

**Comment by mirmaid** [comment]
Ehkä vielä haku (tietotekniikka) KÄ tiedonhaku & KÄ hakualgoritmit (ei YSAssa mutta voisi varmaan ottaa).

**Comment by mirmaid** [comment]
Melindassa seuraavat tapaukset:

- rahoituksen tai apurahan haku
- korvauksen, avustuksen, tuen tai etuuden haku
- viran haku
- opiskelupaikan haku
- asunnon haku (asumisoikeusasunnon tai kaupungin asunnon)
- haku tapahtuman järjestäjäksi (urheilutapahtuma, kongressi)
- mallisuojan haku
- kunniamerkin haku
- vian haku (KÄ etsintä?)
- Yksi teos aiheesta miten asiakkaat hakevat kaunokirjallisuutta, tähän kyllä tiedonhaku sopii vähän huonosti...

**Comment by mariaforsen** [comment]
Selvennykseksi: haku
1 (etsiminen) sökande [-t,-,-], letande [-t,-,-]
2 (noutaminen) hämtning [-en,-ar,-arna], avhämtning [-en,-ar,-arna]
3 (hakemus) ansökan [=,ansökningar,ansökningarna] (en), ansökning [-en,-ar,-arna]
4 atk sökning [-en,-ar,-arna], sökande [-t,-n,-na]
5 oik (ulosotto) utsökning [-en,-ar,-arna]
6 (metsästyskoiran) sök [-et,-,-] 

Ei varmaan saada täydellistä vastaavuutta. Monessa tapauksessa varmaan kuitenkin myös mahdollista ruotsiksi käyttää "ansökningar" (hakemukset) tämän sijaan, aina tarvittaessa. Ja kun on nyt myös ohjattu etsiminen etsintä-termille niin eiköhän se riitä.

**Comment by mirmaid** [comment]
Jos ei lisätä tarkennetta haku-termille, sitä tullaan varmaan jatkossakin käyttämään vähän epätarkasti. Toisaalta viitteitä Melindassa on vain muutamia/vuosi. Yksi mahdollisuus on myös yrittää luoda tarkempi termi kaikille tapauksille; esim. opiskelupaikan haku, etuuden haku, viran haku, rahoituksen haku.

**Comment by LeKorsu** [comment]
Meidän talon journalistit, jotka käyttävät verkkotekstien asiasanoitukseen ysoa, kuulemmat inhoavat sulkutarkeinteita, joten ainakin tässä tapauksessa voisivat nuo sanaliittomaiset termit olla paikallaan.

**Comment by krinay** [comment]
Sanaliitot vai yhdyssanat? Kielitoimiston sanakirjassa on yhdyssanana ainakin: viranhaku, paikanhaku (= työpaikan, toimen haku), työnhaku (tämä on jo YSAssa)  jne.

**Comment by AuHo22** [comment]
On myös anomus- ja hakemuslajeja kuten raha-anomukset ja työhakemukset, joilla voi tarpeen vaatiessa täydentää ja tarkentaa...eli kannatan tarkempien termien käyttöä eri yhteyksissään.

**Comment by YSA-kokous** [comment]
Auktorisoidaan tärkeimmät (esim. opiskelupaikan haku), muuten käytetään termiä hakemukset.

**Comment by mirmaid** [comment]
Lisätty _opiskelupaikan haku_ ja _hakualgoritmit_. Tutkitaan mitä muita tarvitaan.

**Comment by ilona-x** [comment]
Melinda-viitteet on nyt korjattu siten, että on käytetty muotoa "hakemukset" jos sopivaa "haku"-termiä ei ole ollut saatavilla. Osassa kyseessä on ollut kuitenkin ennemminkin hakumenettely tai -prosessi kuin varsinaisesti hakemuksen laatiminen. Näissä tapauksissa haun KT-muotona oleva termi **hakumenettely** voisi olla sopiva, esim. maataloustukien haku(menettely), etuuden/tuen haku(menettely), apurahan haku(menettely), olympialaisten haku(menettely), viran-/työpaikanhaku(menettely). 

En tosin ole varma, miten tuo ruotsiksi taipuu, hakumenettelyn vastineeksi löysin termin **ansökningsförfarande**.

Lisäksi hakumenettely olisi osittain päällekkäinen termin 'opiskelupaikan haku' kanssa.

**Comment by mariaforsen** [comment]
Sv. ansökningsförfarande

**Comment by YSA-kokous** [comment]
hakumenettely
