### ISSUE TITLE
interventio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4650]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[interventio](http://www.yso.fi/onto/ysa/Y101863) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

RT-suhteet liittyvät vain sotatoimiin ja vastaavaan? 
#### Perustelut ehdotukselle

Termi on tavallinen mm. psykologiaan ja sosiaalitieteisiin liittyen ja olen huomannut, että sisällönkuvailussa monet käyttävät sitä nykyisin myös siinä merkityksessä (esim. Melindassa, Artossa ja onhan se yleistermi). 
#### Ehdottaja

JYK 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ehdotettu KÄ-viittauksia termeihin interventiohoito, varhainen puuttuminen ja puheeksiotto.

**Comment by mirmaid** [comment]
Vastaus: KÄ-viittauslisäykset ovat hyviä, mutta pitäisikö tuo psykologia -näkökulma saada jotenkin vielä paremmin esille? Interventiohoito viittaa hoitomuotoon (päihdehuolto). Wikipediassa https://fi.wikipedia.org/wiki/Kliininen_psykologia. ”Kliininen psykologia, kuten terveydenhuolto yleensä, voidaan jakaa ehkäisevään, parantavaan ja ylläpitävään apuun (ks. tarkemmin interventio).” Eli tuohon tarkoitukseen tarvittaisiin interventio-termiä.

**Comment by mirmaid** [comment]
Näyttää siltä että interventiosta on tullut kasvatus- ja sosiaalitieteissä muotisana jota käytetään kaikenlaisesta vaikuttamisesta tai puuttumisesta. Vaatii vielä tarkempaa selvitystä voiko näille löytää yhteisen tarkenteen. Yksi vaihtoehto tietysti on vain hyväksyä termin laaja käyttö ja muokata luokkia ja suhteita sen mukaan, koska perusajatus on kuitenkin sama: ulkopuolelta tuleva puuttuminen ja vaikuttaminen ongelmaksi koetussa tilanteessa.

**Comment by satuniininen** [comment]
Kannattaisin laajan käytön hyväksymistä mieluummin kuin yhteisen tarkenteen keksimistä. Tällaisissa tapauksissa, joissa käsitteen käyttö on hyvin rönsyilevää ja tieteenalat ylittävää, tarkenteesta tulee helposti keinotekoinen ja epäintuitiivinen. 

Pohdin myös, olisiko mahdollista laajentaa interventiohoito-käsitteen käyttöä päihdehuollon yhteydestä myös psykologian käsitteeksi. Näin siis sellaisissa tapauksissa, joissa käsitellään interventiota selkeästi terapeuttisena työkaluna, ei minä tahansa puuttumisena. (esim. väitöskirja     Self-injurious behavior : assessment and treatment)

**Comment by mirmaid** [comment]
Hyväksytään interventiolle laaja merkitys, muokataan ryhmiä ja suhteita sen mukaan. Tutkitaan vielä interventiohoito. (YSA-kokous 6.10.2016)

**Comment by mirmaid** [comment]
YSOssa yläkäsitteenä on _hoitomenetelmät_. On käytetty monenlaisissa yhteyksissä (mm. musiikin käyttö kivunlievityksenä, painehaavojen ehkäisy), mutta en tiedä miten tätä voisi estääkään.

**Comment by mirmaid** [comment]
Interventiohoito RT päihdehuolto & sosiaalihuolto (?), LT hoitomenetelmät?

**Comment by mirmaid** [comment]
Hyväksytty muutos interventiohoidolle (YSA-kokous 7.3.2017).
