### ISSUE TITLE
joukkueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4651]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[joukkueet](http://www.yso.fi/onto/ysa/Y111394) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Kaksimerkityksinen, jaettava. 
#### Perustelut ehdotukselle

joukkueet (sotilasosastot) ja joukkueet (urheilu) 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Rakaisuvaihtoehdot:

1)  joukkueet (urheilu) KÄ **urheilujoukkueet** ja lisäksi **joukkueet (sotilasosastot)**, mutta jätetään kuitenkin myös laajempi **joukkueet** (käytetty paljon urheilujoukkueista)
2)  korjataan kaikki urheilua koskevat: joukkueet + jalkapallo > **urheilujoukkueet** + jalkapallo. YSAan jäisi silloin urheilujoukkueet ja **joukkueet (sotilasosastot)**, ei yhteistä yläkäsitettä eikä pelkkää joukkueet-termiä. Joukkueita tosin voi olla myös muissa kuin urheilukilpailuissa. (käytetty teoksessa Cracknell: Race to the Pole)
3)  poistetaan termi urheilujoukkueet ja korvataan se muodolla **joukkueet (urheilu)**

**Comment by mirmaid** [comment]
Wikipedia: Rannikko-, kenttä- tai ilmatorjuntatykistössä samansuuruista joukkoa kutsutaan jaokseksi. Laivastossa taas ruoduksi. Joukkueen vahvuista tulenjohtoyksikköä kutsutaan tulenjohtueeksi.

**Comment by yrjolindegren** [comment]
joukkueet (sotilasosastot) ja joukkueet (urheilu) vaikuttaa käytännölliseltä ratkaisulta

**Comment by mariaforsen** [comment]
Yllä oleva hyvä ratkaisu myös ruotsin kannalta.

**Comment by mirmaid** [comment]
Jaetaan: joukkueet (sotilasosastot) ja joukkueet (urheilu) KT urheilujoukkueet. (YSA-kokous 6.10.2016)
