### ISSUE TITLE
kaappaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4652]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[kaappaukset](http://www.yso.fi/onto/ysa/Y127121) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Jaettava 
#### Perustelut ehdotukselle

Ruotsiksi aluksen ja lapsen kaappauksesta ei voi käyttää samaa termiä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa lapsikaappausten lisäksi merirosvouden, lentokonekaappausten ja toimittajien kaappausten yhteydessä. Toimittajien kaappauksiin sopisi ehkä myös käsite ”ihmisryöstö”.

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
Kaappaukset (ihmisen) KÄ ihmisryöstöt. 

Tarvitaanko erikseen lapsikaappaukset/lapsikaappaus? EKS:ssa on molemmat, lapsikaappaus yksikössä.

**Comment by yrjolindegren** [comment]
Ja sitten on vielä termi sieppaukset = kidnappningar; mitä eroa mahtaa olla siinä joutuuko kaapatuksi vai siepatuksi?

**Comment by ilona-x** [comment]
sieppaukset näyttää tosiaan olevan Allärsissa kidnappningar ja YSAssaa taas kidnappaukset KÄYTÄ ihmisryöstöt. Voisiko 'sieppaukset' termistä tehdä ohjaustermin (KÄYTÄ ihmisryöstöt)?

Kielitoimiston sanakirja antaa sieppaukselle vain seuraavan määritelmän:

**sieppaus sieppaaminen.**
Fys. ulkoa tulevan hiukkasen (vars. elektronin t. neutronin) liittyminen atomiytimeen siten, ettei mikään ainehiukkanen poistu, kaappaus.

Melindassa sieppaukset käytetty YSA-terminä 49 kertaa (joista 21 tietueessa myös ihmisryöstöt) ja Kaunokki-terminä yli 200 kertaa

**Comment by ilona-x** [comment]
Melindassa kaappaukset termillä on kuvailtu paljon lapsikaappauksia käsittelevää aineistoa, joten ehkä lapsikaappaus olisi hyvä ottaa sanastoon.

kaappaukset (ihmisen) KÄYTÄ ihmisryöstöt
lapsikaappaus
kaappaukset (kulkuneuvot)

**Comment by mariaforsen** [comment]
Yllä olevat hyvät ruotsinkin kannalta, mutta ehkä pitäisi silti säilyttää myös kidnappningar (sieppaukset). Esim. jos lemmikkieläin on siepattu ei voi käyttää mikään yllä olevista. 

Ihmisryöstöt=människorov (lapsenryöstöt=barnarov)
lapsikaappaus=bortförande av barn
kaappaukset (kulkuneuvot)=kapningar (transportmedel)

**Comment by mirmaid** [comment]
Otetaan:
- kaappaukset (ihmisen) KÄYTÄ ihmisryöstöt
- lapsikaappaus
- kaappaukset (kulkuneuvot)

(YSA-kokous 6.10.2016)
