### ISSUE TITLE
kuuleminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4653]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[kuuleminen](http://www.yso.fi/onto/ysa/Y113636) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Käytetty väärin, vaatii sulkutarkenteen. 
#### Perustelut ehdotukselle

YSAssa myös kuuleminen – fysiologia. Tarkenteetonta muotoa käytetty kuitenkin myös samassa merkityksessä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Voiko olla jotain sen tyyppistä kuin menettely/oikeus?/päätöksenteko? Ks. Melinda.

**Comment by mariaforsen** [comment]
Voiko oikeus olla liian rajaava? Ruotsiksi voisi laittaa hörande (fysiologi/biologi) ja hörande (förfarande/juridik/beslutsfattande).

**Comment by LeKorsu** [comment]
Kannatan päätöksentekoa sulkutarkenteeksi.

**Comment by mirmaid** [comment]
Kuuleminen (fysiologia) ja kuuleminen (menettely). (YSA-kokous 6.10.2016)
