### ISSUE TITLE
metamorfoosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4654]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[metamorfoosi](http://www.yso.fi/onto/ysa/Y112980) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Tarvitaanko erikseen metamorfoosi (geologia) ja metamorfoosi (taide tms.) vai onko ok ilman tarkenteita? 
#### Perustelut ehdotukselle

Muodonvaihdos (=biologia) on erikseen, mutta silti jää epäselväksi mihin tarkalleen tämä viittaa (yleistermi). 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
1. YSAssa on metamorfiset kivilajit, riittäisikö metamorfoosi (geologia) KÄ metamorfiset kivilajit?
2. metamorfoosi (geologia) + metamorfoosi (taide) (tms.)

**Comment by satuniininen** [comment]
Kannatan ratkaisua metamorfoosi (geologia) + metamorfoosi (taide)

**Comment by mariaforsen** [comment]
Mihin siis metamorfoosi (taide) viittaa, tarinoihin? Kannatan kyllä jakamista ja se onkin ruotsin kannalta välttämätöntä, koska sanastossa on jo metamorfos (biologi)=muodonvaihdos. Tarvitaan siis sulkutarkenne sille toisellekin metamorfoosille, ja sitä ei voida laittaa ennen kuin suomeksi on päätetty mihin "metamorfoosi" viittaa.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: tarina joka kertoo ihmisen muuttumisesta tav. eläimeksi t. kasviksi. Taide-tarkenne varmaankin koska näitä metamorfoosia-kuvauksia voi olla kirjallisuudessa, elokuvassa, kuvataiteessa.

**Comment by mirmaid** [comment]
Otetaan metamorfoosi (geologia) ja metamorfoosi (taide). (YSA-kokous 6.10.2016)
