### ISSUE TITLE
monitaiteisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4655]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[monitaiteisuus](http://www.yso.fi/onto/ysa/Y177739) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Ero taiteidenvälisyys-termiin havainnollistettava tai termit yhdistettävä 
#### Perustelut ehdotukselle

Olemme pohtineet näiden termien eroja/yhtäläisyyksiä ja käytön kannalta näihin termeihin pitäisi laittaa määreet, mikäli molemmat termit jäävät. 
#### Ehdottaja

BTJ 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Useammassa erikoisontologiassa näyttää olevan monitaiteisuus -> taiteidenvälisyys

Melinda; monitaiteisuus x 20 ; taiteidenvälisyys x 382 ja 8 tietuetta, joissa molemmat  

(YSAssa myös monitieteisyys & tieteidenvälisyys, joissa määritelmät (+ poikkitieteisyys))

**Comment by mirmaid** [comment]
Ratkaisuehdotus: yhdistetään?

**Comment by mariaforsen** [comment]
Yhdistäminen olisi tosi hyvä myös ruotsin kannalta, multikonst (monitaiteisuus) ei ole hyvä käännös.

**Comment by AuHo22** [comment]
Outilta tuli illalla vielä kännykkään seuraavasti:
monitaiteisuus - esim. nukketeatteri joka sisältää monta eri taidemuotoa (ääni, kuva, liike, nuket, puhe) ;
taiteidenvälisyys - taiteessa etsitään risteymiä ja kosketuspintoja eri taiteiden välillä pyrkimyksenä luoda / syventää prosessia / teosta.
Itse taisin ajatella monitaiteisuutta tapahtumatuotannon yhteydessä eli siten, että tapahtuma on monitaiteinen, kun siihen sisältyy esimerkiksi kuvataiteita, tanssityöpajaa jne. Ja taiteidenvälisyys - kuten yo. määritelmässäkin - voi toteutua esimerkiksi performanssissa eli yksittäisen taideteoksen kehyksessä.

**Comment by mirmaid** [comment]
BTJ selvittää > seuraava kokous. (YSA-kokous 6.10.2016)

**Comment by AuHo22** [comment]
Kielitoimiston sanakirja: monitaiteinen eli monta taiteenlajia käsittävä, monesta taiteenlajista koostuva. Monitaiteinen tapahtuma.

Esimerkiksi: https://www.theseus.fi/bitstream/handle/10024/21136/Mansikkakorpi_Heini.pdf?sequence=1
Draama on itsessään monitaiteinen taidelaji; se perustuu tanssin, eleen, mimii-
kan, kirjoitetun ja kirjoittamattoman tekstin, puheen, musiikin, kuvan ja värin 
vuorovaikutukseen (mutta eri taiteiden muodot ovat myös itsenäisiä kokonaisuuksia).
Usein myös taidekasvatuksen yhteydessä: esim. Hassin mukaan kokonaisvaltaisen, monitaiteisen taidekasvatuksen avulla alle kouluikäiset lapset voivat tutustua taiteen eri ilmaisumuotoihin, 
omaan itseensä ja persoonallisuuteensa.

Taiteidenvälisessä toiminnassa eri taidelajit muodostavat kokonaisuuden, esimerkiksi happening tai performanssi. Taiteiden väliset rajat ovat madaltuneet ja eri taiteiden lajeja, menetelmiä ja materiaaleja käytetään ja kokeillaan vapaammin.

Kuitenkin, juuri pienten lasten kohdalla, taiteidenvälisyyden voisi nähdä olevan 
parhaimmillaan leikin ja eri taidemuotojen yhdistelmää, jossa taiteita ei olisi 
tarpeen erotella toisistaan. Lasten kokemusmaailmassa taidelajeilla ei ole 
välttämättä vielä selviä rajoja.
https://jyx.jyu.fi/dspace/bitstream/handle/123456789/22206/URN_NBN_fi_jyu-200910133975.pdf?sequen

Tutkielmissa voi nähdä näitä määritelmällisiä eroja, ja niissä voi myös olla hyödyllinen.

**Comment by mirmaid** [comment]
Monitaiteisuus otettu YSAan 2011, ehdottaja ollut (ilmeisesti musiikkiluetteloinnin) Ammus-työryhmä. "YSA:ssa taiteidenvälisyys korvaa monitaiteisuuden, todettiin etteivät sanat ole täysin synonyymejä. Myös monitaiteisuutta olisi voitava käyttää." Kokouksen listalla: Joku taideteos on monitaiteinen ja se on toteutettu taiteidenvälisenä yhteistyönä (saisikohan jostain määritelmät...)

**Comment by mirmaid** [comment]
Monitieteisyys: Käytetään monta tieteenalaa käsittävästä tutkimushankkeesta, instituutiosta tms.

Tieteidenvälisyys: Käytetään tutkimuksesta, jossa hyödynnetään eri tieteiden tietoa, usean tieteenalan käsitteitä, näkökulmia, teorioita ja menetelmiä.

**Comment by mirmaid** [comment]
Pohdintaa: https://aaltodoc.aalto.fi/handle/123456789/3948 s. 9-10

"Taiteidenvälisyys on keskustelua taiteiden välillä, jolloin toinen taiteen laji voi tuoda syvyyttä toisen taiteen lajin sisältöihin ja sitä kautta myös ymmärrykseen. Samaa asiaa voidaan käsitellä eri taitein."

"Itselleni monitaiteisuus on sitä, että teokseen tai teoksen luomiseen käytetään useampia taiteen lajeja. Nykytaide on mielestäni usein monitaiteista juuri tällä tavalla. Hyviä esimerkkejä monitaiteisuudesta ovat muun muassa videoteokset, musiikkivideot ja elokuva, joka yhdistää toisiinsa monia eri taiteen lajeja."

**Comment by LeKorsu** [comment]
Saako tuosta Mirjan käyttämästä lainauksesta määreitä, jos halutaan pitää molemmat? Lehtikielessä (lähteenä Sanoman arkisto) taiteidenvälisyys yleisempi kuin monitaiteisuus, jos halutaan yhdistää. Minä kannatan yhdistämistä [monitaiteisuus KÄ taiteidenvälisyys], mutta en olekaan mikään taiteidentuntija. =)

**Comment by mirmaid** [comment]
Määritelmät on varmaan mahdollista tehdä ja onhan tämän yhdistäminen vähän kyseenalaista kun sama jako on olemassa tiedepuolella. Taiteidenvälisyys on ruotsiksi tvärkonstnärlig verksamhet, voisiko monitaiteisuus olla multikonstnärlig verksamhet? Ainakin sanaa multikonstnärlig käytetään.

**Comment by mariaforsen** [comment]
Ok, tämä ratkaisu on varmaan ihan hyvä "luotuna terminä" (hierarkiavirhe tosin jää YSO:ssa).

**Comment by YSA-kokous** [comment]
monitaiteisuus = multikonstnärlig verksamhet
