### ISSUE TITLE
monitoimisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4656]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[monitoimisuus](http://www.yso.fi/onto/ysa/Y112765) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Ruotsiksi merkitys kapeampi, selkeytettävä. 
#### Perustelut ehdotukselle

ruots. mångprofessionella arbeten. Käytetty suomeksi mm. ihmisistä ja laitteista. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ks. myös päätoimisuus, sivutoimet.

**Comment by mariaforsen** [comment]
Mångsyssleri olisi parempi käännös, mutta sekään ei kata esim. laitteita tms. Onko mahdollista rajata merkitystä? Näistä -uus sanoista ei saada ruotsiksi "ominaisuuksia", eli päätoimisuuskin on käännetty huvudsyssla.

**Comment by ilona-x** [comment]
Melindassa on käytetty 'mångprofessionella arbeten' -termiä 5 kertaa, ja mielestäni näyttäisi, että kaikissa tapauksissa oikeampi termi olisi ollut moniammatillisuus (yrkesmångfald), onko tuo muuten hyvä käännös? NetMotin mukaan moniammatillinen = multiprofessionell, multidisciplinär, yrkesövergripande

**Comment by LeKorsu** [comment]
Toimisiko?
monitoimisuus (työelämä / ihmiset) , sv mångsyssleri (arbetsliv / människor)
monitoimisuus (laitteet), sv mångsyssleri (maskiner)

**Comment by mirmaid** [comment]
Mitenkähän nuo suomenkieliset ihmisiä koskevat, niissäkin voisi toimia moniammatillisuus. Joissakin tapauksissa kyse on monitoimijaisuudesta ja kuvailussa on monitoimisuus :confounded:

Monitoimisuus (laitteet) kattaisi vain osan käyttötapauksista silloinkin kun kyse ei ole ihmisistä.

**Comment by mirmaid** [comment]
Melkein tekisi mieli poistaa koko termi, jollei sitten maatalous-kontekstissa välttämättä tarvita. Useimpiin Melindan tietueisiin saisi varmaan jonkun muunkin termin tilalle ja käyttö on välillä aika jännää http://linda.linneanet.fi/F/GYNENAE9J3LQVTM3LU9JCBQIK2IHS9GL2JFFB3AV92NAKSAKCQ-08209?func=full-set-set&set_number=096765&set_entry=000005&format=999

**Comment by ilona-x** [comment]
Melindan vanhimmat viitteet (vuodet 1977-2001), joissa on käytetty monitoimisuus -termiä, liittyvät maatalouteen ja maatilojen monitoimisuuteen, yhteensä 13 viitettä. Uudemmissa teoksissa käyttö on sitten levinnyt täysin.

**Comment by mirmaid** [comment]
Ei ratkaisua, seuraava kokous. (YSA-kokous 6.10.2016)

**Comment by mirmaid** [comment]
päätoimisuus = huvudsyssla (päätyö, päätoimi)
sivutoimet = bisysslor

**Comment by mariaforsen** [comment]
Vastauksena yllä oleviin kysymyksiin Allärs-termistä: 

Ei, yrkesmångfald ei ole hyvä vastine moniammatillisuudelle, ja tämä termi onkin ongelmalistalla ollut pitkään (on kuitenkin käytetty satoja kertoja)... Multiprofessionalitet olisi parempi vastine, mutta täytyy selvittää päteekö se kaikissa Melindaviitteissä. 

Ja toiseen kysymykseen/ehdotukseen: Ei, koneiden yhteydessä ei voi käyttää mångsyssleri ollenkaan, mutta jos päätetään jakaa näin (ihmiset vs. koneet) niin on kyllä mahdollista luoda hyviä vastineita ruotsiksikin.

**Comment by mirmaid** [comment]
Monialainen maatila on yritys, joka muodostuu maatalouden, metsätalouden ja muun yritystoiminnan harjoittamisesta, jolloin monialaisuus liittyy käsitteenä yritykseen. Monialaisuudesta on käsitteenä erotettava monitoimisuus. Monitoimisella maatilalla tarkoitetaan maatilaa, joka saa tuloja myös tilan ulkopuolisesta palkkatyöstä. Monitoimisuus on siten tilan tulonmuodostukseen liittyvä käsite. (MMM 2005, 10.) https://www.doria.fi/bitstream/handle/10024/114154/50308.pdf?sequence=1

Eikelandin (1999, 359–376) mukaan monitoimisuus tarkoittaa sitä, että tuloja saadaan kotitalouden käyttöön useasta erilaisesta tulonlähteestä. Hän ei rajaa monitoimisuutta ainoastaan viljelijäväestöön. https://publications.theseus.fi/bitstream/handle/10024/13670/Torpo_Sari.pdf?sequence=1

**Comment by mirmaid** [comment]
Jos löydetään ylläolevaa merkitystä (tilan/talouden tulot saadaan monesta tulonlähteestä, tila/talous ei ole itsessään monialainen) vastaava ruotsinkielinen termi, voidaan varmaan suomeksi tarkentaa esim. _monitoimisuus (työelämä)_ tai _monitoimisuus (maatilat)_. 

Laajemmassa merkityksessä sopinee myös tähän (toki YSAssa myös _sivutoimet_): Sivutoimiyrittäjyyden rooli ja merkitys ammattikorkeakoulusta valmistuneiden keskuudessa / Elina Varamäki, Kirsti Sorama, Kari Salo & Tarja Heikkilä.

YSAssa on lisäksi ainakin _monikäyttö_, _muunneltavuus_, _modulaarisuus_ ja _monitoimilaitteet_. Selvittäisiinkö näillä? Siirrettäisiin monitoimisuus muissa viitteissä Melindassa 653-kenttään (tai kokonaan pois - ainakin kun kyseessä on esim. monitoimijaisuus)?

**Comment by mariaforsen** [comment]
Kyllä, Eikelandin mukainen monitoimisuus voisi olla mångsyssleri (ei tosin pelkästään maatilojen kohdalla, se nyt vain on sellainen ala että vaatii usein monitoimisuutta että tulisi toimeen)

**Comment by mirmaid** [comment]
Hyväksytty monitoimisuus (työelämä) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
mångsyssleri (arbetsliv)
Avser inkomstbildning från flera olika näringsgrenar, t.ex. när en lantbruksföretagare får sin inkomst från både sitt jordbruk och lönearbete utanför lantbruket.
