### ISSUE TITLE
osallistuva suunnittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4657]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[osallistuva suunnittelu](http://www.yso.fi/onto/ysa/Y117621) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

KÄ osallistava suunnittelu 
#### Perustelut ehdotukselle

Englanniksi sama kuin osallistava suunnittelu, myös suomeksi käytetään samassa merkityksessä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
osallistava suunnittelu Googlessa 3 670 kertaa ja Melindassa 208
osallistuva suunnittelu Googlessa 2 370 kertaa ja Melindassa 294

Uusissa aineistoissa käytetään enemmän osallistavaa suunnittelua, mutta osallistuva suunnittelu on otettu sanastoon aikaisemmin, joten sitä on ehditty käyttää kokonaismäärällisesti enemmän. Näyttäisi siltä, että osallistava suunnittelu on tällä hetkellä vakiintuneempi ja enemmän käytetty.

**Comment by mirmaid** [comment]
Huom. sanastossa myös osallistava ja osallistuva teatteri

**Comment by LeKorsu** [comment]
Hankala, mutta peukkua silti Mirjan ehdotukselle. Tsekkasin taas lehtikieltä Sanoman arkistosta, "osallistava suunnittelu" 7 osumaa, josta tuorein 2014. "Osallistuva suunnittelu" 11 osumaa, josta tuorein niin ikään 2014. Ei siis anna mitään ratkaisuohjausta.

**Comment by ilona-x** [comment]
YSAssa lisäksi vielä **yhteissuunnittelu** (engl. co-design), jota käytetty Melindassa päällekäin näiden kanssa.  Melindassa yhteissuunnittelu 304 kertaa, joista 153 tietueessa asiasanana myös osallist? -alkuinen termi.

Wikipediassa: "Participatory design (originally co-operative design, now often co-design)"
https://en.wikipedia.org/wiki/Participatory_design

**Comment by mirmaid** [comment]
Osallistuva suunnittelu KÄ osallistava suunnittelu. (YSA-kokous 6.10.2016) Tutkitaan vielä suhde yhteissuunnitteluun (seuraava kokous).

**Comment by mirmaid** [comment]
https://hetkiaikaa.wordpress.com/2011/05/11/miksi-yhteissuunnittelu-jyraa-osallistuvan-suunnittelun/

"Participatory design sounds more expensive." https://www.quora.com/What-is-the-difference-between-co-design-and-participatory-design

https://en.wikipedia.org/wiki/Participatory_design

Jättäisin ehkä kuitenkin molemmat sanastoon.

**Comment by LeKorsu** [comment]
Sanoman arkisto antaa vuodesta 1990 lähtien 42 osumaa "yhteissuunnittelulle". Enemmän kuin osallistuvalle tai osallistavalle suunnittelulle.

**Comment by mariaforsen** [comment]
Siis oliko tarkoitus myös yhdistää osallistava suunnittelu ja yhteissunnittelu? Ne eivät ole sama asia ruotsiksi.

**Comment by mirmaid** [comment]
Jätetään molemmat sanastoon?

**Comment by mariaforsen** [comment]
Eli jätetään sekä osallistava suunnittelu että yhteissuunnittelu? Kannatan!

**Comment by YSA-kokous** [comment]
Molemmat jäävät
