### ISSUE TITLE
perheenyhdistäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4658]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[perheenyhdistäminen](http://www.yso.fi/onto/ysa/Y172974) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Nykyinen KT perheen jälleenyhdistäminen omaksi asiasanakseen? 
#### Perustelut ehdotukselle

Perheenyhdistäminen viittaa yleensä pakolaisten perheenyhdistämiseen, perheen jälleenyhdistäminen biologisen perheen yhdistämiseen huostaanoton jälkeen. 
#### Ehdottaja

KK 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Lastensuojelulaissa puhutaan huostassapidon lopettamisesta ja perheen jälleenyhdistämisestä.

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
perheenyhdistäminen (sijaishuollon jälkeen) KÄ perheen jälleenyhdistäminen (?)

**Comment by mariaforsen** [comment]
Termit sinänsä eivät kai kerro onko kyseessä maahanmuuttokontekstista vai "huostaanoton päättämisestä", joten eikö myös sulkutarkenne ja/tai huomautus olisi tarpeen? Jos siis ajatus todella oli pitää sekä "perheenyhdistäminen" että "perheen jälleenyhdistäminen" sanastossa. 

Vai olisiko mahdollista valita toiselle merkitykselle selkeästi "huostassapidon lopettaminen" tms. jolle löytyisi  ruotsinkielinen vastine myös? "Familjeåterförening" ei kovin yleisesti käytetä huostaanoton yhteydessä (tavallisesti lapsilla on kai oikeus tavata vanhempiaan myös huostassapidon aikana..) vaan ruotsiksi se käsitellään enemmän huostassapidon lopettamisen näkökulmasta.

**Comment by mirmaid** [comment]
Perheen jälleenyhdistäminen KÄ perheenyhdistäminen. (YSA-kokous 6.10.2016)
