### ISSUE TITLE
huviretket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4659]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[huviretket](http://www.yso.fi/onto/ysa/Y110323) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Nykyinen KT piknikit omaksi asiasanakseen. 
#### Perustelut ehdotukselle

aiheena usein ruoka 
#### Ehdottaja

Mirja Anttila 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Kannatan, picknickar (/NE) olisi hyvä erikseen.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 6.10.2016)
