### ISSUE TITLE
profiilit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4660]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[profiilit](http://www.yso.fi/onto/ysa/Y142594) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Jaettava 
#### Perustelut ehdotukselle

Monimerkityksinen ja käytetty Melindassakin niin. Sama ruotsiksi. YSO LT rakennustarvikkeet. KT on sivukuvat. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
1. (esineen t. ihmisen) ääriviivat, siluetti, (kasvojen) sivukuva. Kreikkalainen profiili. Kuvata jkn kasvot, jku profiilissa sivulta päin. Merelle näkyvä Tallinnan profiili. 
2. jnk poikkileikkaus t. pystysuuntainen pituusleikkaus, vars. sen ääriviivat, sitä esittävä piirros, malli tms. Harjun profiili. Rakennuksen pohjapiirros ja profiili. Lentokoneen siiven profiili. Latuprofiili. 
3. rak., tekn. muotolistan, -teräksen t. -levyn poikkileikkauksena näkyvä pinnan muotoilu (uurteet, kohoumat tms.); myös näin muotoillusta listasta, tangosta t. levystä. U-, T-profiili. Alumiini-, teräsprofiili. 
4. kuv. a. jnk tyypilliset, (muista) erottavat piirteet, luonne, ilme, imago. Kirjailijan taiteellinen profiili. Taiteilijaprofiili. Yritys-, tuoteprofiili. Asiakasprofiili ostojen perusteella asiakkaasta luotu kuva markkinointia varten. Rikollisen profiili rikoksen tekotavan yms. seikkojen perusteella määritetty tekijän luonnekuva. Yhteisöpalvelun käyttäjien profiilit palvelun käyttäjäkohtaisista asetuksista, joita käyttäjät yleensä hallinnoivat itse. b. Matala profiili huomaamaton, vaatimaton esiintyminen, julkisuuden välttäminen, varovainen toimintalinja. Hallituksen, presidentin matala profiili. Pitää matalaa profiilia. Nostaa profiiliaan ryhtyä esiintymään näkyvämmin, räväkämmin, terävämmin.

**Comment by mirmaid** [comment]
Melindassa 48 viitettä, tavallisimmin 4. merkitys mutta myös ainakin 3.

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
profiilit (rakenteet) 
profiilit (kuvaukset/ominaisuudet) (?) - tälle on vaikea keksi tarkennetta joka ei olisi kuvailijan kannalta hämmentävä. Ks. Melinda

**Comment by satuniininen** [comment]
Tämä on vaikea. Entä profiilit (olemus) tai profiilit (piirteet)?

**Comment by AuHo22** [comment]
Profiilit (tunnuspiirteet)?

**Comment by mariaforsen** [comment]
Voisi olla ruotsiksi "profiler (strukturer/konstruktioner)" ja "profiler (egenskaper)" (esim. Nationencyklopedin määrittelee näin).

**Comment by LeKorsu** [comment]
Vastaisiko Profiilit (ominaisuudet) parhaiten profiler (egenskaper)?

Marian vastaus: Kyllä

**Comment by mirmaid** [comment]
Profiilit (toimijoiden/kuvaukset) ja profiilit (rakenteiden/rakentaminen/rakenteet/rakennustarvikkeet). (Jatketaan seuraavassa, tutkitaan vielä Melindan viitteet.) (YSA-kokous 6.10.2016)

**Comment by mirmaid** [comment]
Melindan 20 ensimmäistä viitettä:

_profiilit (ominaisuudet TAI kuvaukset)_

Stick ut på LinkedIn
Understanding the formation and evolution of disc break features in galaxies
Yrittäjäprofiilien yhteys yrityksen menestykseen
Profile work for authenticity: self-presentation in social network services
Rooftop Studios: en spelstudio tar form
Katarina Maria: ett företag får färg
KE Construction: en användbar webbsida
Onko talousrikoksista epäilty poliisin tuttu
Korjausaseman säätöparametrien vaikutus elektroniikkakomponenttien juotosprofiilin lämpötilaan
Student motivation and well-being: achievement goal orientation profiles, temporal stability, and academic and socio-emotional outcomes
Opiskelijaprofiili Aalto-yliopiston kauppakorkeakoulun suomenkielisissä maisteriohjelmissa
Kirjasto 2012: asiakkaan asialla
The innovation for development report 2010-2011: innovation as a driver of productivity and economic growth
Bluetooth-kehityskittien hyödyntäminen opetuksessa

_profiilit (rakenteet)_
Koteloprofiilin sekundaarinen estetty vääntö
Teräs: tuotestandardit
Opastimen kiinnittimen kehittäminen

**Comment by mirmaid** [comment]
Yrityksen profiili on se, miten yritys haluaa, että se nähdään. https://www.theseus.fi/bitstream/handle/10024/2696/Tiia%20Haapala.pdf?sequence=1

Concise description which, among other items of information, includes (1) firm's history, (2) number and quality of its human, financial, and physical resources (3) organizational and management structure, (4) past, current and anticipated performance, and (5) its reputation, and the standing of its goods or services.

Read more: http://www.businessdictionary.com/definition/company-profile.html

Läheisiä käsitteitä esim. imago, brändit, yrityskuva (YSO yläkäsite _yhteiskunnalliset objektit_).

**Comment by mirmaid** [comment]
http://www.kanava.to/blogi/asiakasprofiili/

Asiakasprofiilit ovat kuvaus palvelun käyttäjien arkkityypeistä. Ne on rakennettu keräämällä tietoa asiakkaista. Asiakasprofiilien avulla palvelun kehittäjät saavat yhteisen ymmärryksen palvelun käyttäjistä. http://asiakaskehitys.fi/blogi/aivoja-helpottava-oikotie/

Profiili käsitteenä voi tarkoittaa kohteesta muodostettua karkeaa yleiskuvaa, kohdetta
kuvaavia pääpiirteitä tai siitä löydettyjä erityispiirteitä, jotka mahdollisesti erottavat sen
muista vastaanvanlaisista kohteista (Koukkunen, Hosia & Keränen 2001, 532). https://www.doria.fi/bitstream/handle/10024/77092/Vatka2012.pdf?sequence=1

**Comment by mirmaid** [comment]
Bluetooth-profiilit määrittelevät miten Bluetooth-sovellusten tulisi toimia eri käyttökohteissa. Profiilit määrittelevät sen mitä protokollia sovellus tarvitsee.

https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Headset_Profile_.28HSP.29
https://support.microsoft.com/fi-fi/help/10569/windows-10-mobile-supported-bluetooth-profiles

**Comment by mirmaid** [comment]
Juotospastan suositusprofiilissa koko juotosprosessin kestoaika on reilut 5 min (Heraeus Application Recommendation, 13), ja tällä hetkellä nykyisellä juotosprofiililla kestoaika on tuplasti suositusta pitempi eli noin 10 minuuttia. Profiileita vertaamalla voidaan huomata, että nykyisessä juotosprofiilissa esilämmitys 217 ̊C: seen tapahtuu lämmityksen alkupuolella erittäin hitaasti ja loppuosa lämmityksestä ennen juotoslämpötilaa tapahtuu nopeasti. (Ollikainen: Juotosprosessien optimointi)

**Comment by mirmaid** [comment]
As a result of the decrease in the density of stars, the surface brightnesses of galaxies fall with increasing radius. The way in which the brightness falls is described by the surface brightness (or luminosity) profile. 
Elliptical galaxies, and the bulges of spiral galaxies, generally exhibit Sersic surface brightness profiles with a typical n of 4. This is the famous de Vaucouleurs r1/4 profile.
http://astronomy.swin.edu.au/cosmos/S/Surface+Brightness+Profiles

**Comment by mirmaid** [comment]
profiilit (tieto) :hear_no_evil:

**Comment by YSA-kokous** [comment]
profiilit (rakenteet)
profiilit (tieto), lisätään määritelmä

**Comment by mirmaid** [comment]
_Jonkin tyypilliset tai erottavat piirteet tai ominaisuudet; näiden kuvaus._

**Comment by mariaforsen** [comment]
Sv.
-profiler (information)
-profiler (konstruktioner)
