### ISSUE TITLE
kuormituskokeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4661]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[kuormituskokeet](http://www.yso.fi/onto/ysa/Y182267) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Yhdistetään termiin rasituskokeet 
#### Perustelut ehdotukselle

Ainakin ruotsiksi aiheuttavat sanat rasituskokeet ja kuormituskokeet ongelmia, meillä käytetään belastningsprov sekä fysiikan että lääketieteen maailmassa. Onko suomeksi ero suuri vai voisiko olla vain rasituskokeet KT kuormituskokeet tms.? Nyt näytti Melindassakin kuten Googlessakin siltä että käytetään vähän sekaisin myös suomeksi, esim. rasituskokeet huonekalujen rasituskestävyydestä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
kuormituskoe: Siltarakenteiden kuormituskoe. Lääk. koe jossa tutkitaan fyysisen rasituksen vaikutusta mm. sydämen toimintaan, kliininen rasituskoe. Sydämen kuormituskoe. 
Rasituskoe: lääk. 1. = kuormituskoe. 2. Glukoosirasituskoe: koe jolla tutkitaan sokeriaineenvaihduntaa

**Comment by mirmaid** [comment]
FinMeSH: kuormituskoe KT rasituskoe
Lääketieteen termit: rasituskoe ks. kuormituskoe

**Comment by mirmaid** [comment]
YSAssa rasituskokeet on ryhmässä 48, Melindassa kuitenkin käytetty myös tekniikan yhteydessä. Yhteensä 19 viitettä. Kuormituskokeet on ryhmässä 07, Melindassa vain 5 viitettä, kaikki tekniikkaa.

**Comment by mirmaid** [comment]
Kuormituskokeet KÄ rasituskokeet varmasti lääketieteessä ok. Tekniikassa termien käyttö vaihtelee hiukan (kuormitus ehkä usein nimenomaan murtuma- tms. lujuutta testattaessa ja moottoreille). Rasituskokeet on varmasti laajempi ja useimmiten ok, jos lääketieteellisen erottamista tekniikasta ei pidetä tarpeellisena. Tulisiko ryhmiksi 00, 07 ja 48?

**Comment by satuniininen** [comment]
Yhdistäminen sopii. Engl. labeliksi tulisi varmaankin tolerance tests, jota käytetään sekä lääketieteen että tekniikan konteksteissa.

**Comment by satuniininen** [comment]
Ehdotetut ryhmät ok.

**Comment by mariaforsen** [comment]
Tämä olisi hyvä ratkaisu ja ryhmät hyvät.

**Comment by mirmaid** [comment]
Kuormituskokeet KÄ rasituskokeet (YSA-kokous 6.10.2016)
