### ISSUE TITLE
reflektiivisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4662]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[reflektiivisyys](http://www.yso.fi/onto/ysa/Y107532) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Ero käsitteeseen refleksiivisyys selvennettävä 
#### Perustelut ehdotukselle

Käsitteiden refleksiivisyys ja reflektiivisyys ero ei ole käytön perusteella selkeä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
refleksiivisyys Melinda x 194 (kielitiede, sosiaalitieteet, psykologia…)
reflektiivisyys Melinda x 708 (psykologia, kasvatustiede, sosiaalitieteet…)
reflektio Melinda x 280 (kasvatustiede, psykologia…)  
refleksiivisyys + reflektiivisyys Melinda x 21
refleksiivisyys + reflektio Melinda x 12
refleksiivisyys + reflektio Melinda x 49

(vrt. YSAssa itsereflektio KT itserefleksiivisyys, itsereflektiivisyys)

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
reflektio KT reflektiivisyys (tai toisinpäin) + KT refleksiivisyys (yhteiskuntatieteet)
refleksiivisyys (kielitiede)

**Comment by mirmaid** [comment]
Refleksiivisyys (kielitiede) ja reflektio KT reflektiivisyys ja refleksiivisyys (yhteiskuntatieteet). (YSA-kokous 6.10.2016)
