### ISSUE TITLE
laitoskirjastot -- hoitolaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4663]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[laitoskirjastot -- hoitolaitokset](http://www.yso.fi/onto/ysa/Y96715) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Ruotsinkielinen vastine suppeampi, yhdenmukaistettava 
#### Perustelut ehdotukselle

Ruotsinkielinen termi sjukhusbibliotek on merkitykseltään suppeampi. Suomeksikin olisi sille vastine sairaalakirjastot, mutta se ei kata kaikkia hoitolaitoskirjastoja. Voidaan toki kuvailla myös hoitolaitokset + kirjastot. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Laitoskirjastot – yliopistot on ok.

**Comment by mariaforsen** [comment]
Wikipediassa väitetään: "Laitoskirjasto-nimitys otettiin käyttöön vasta 1960-luvulla. Sairaalakirjasto-käsitteellä tarkoitetaan aiemmin vastaavalla tavalla järjestettyä kirjastotoimintaa... Ruotsiksi käsitteellä "sjukhusbibliotek" viitataan edelleen sekä sairaaloissa että muissa hoitolaitoksissa sijaitseviin kirjastoihin." 

Suomenruotsissa käytetään (tosin vain vähän) myös termi "anstaltsbibliotek", voitaisiin mahdollisesti valita tämä vastineeksi? Sjukhusbibliotek olisi kyllä hyvä olla mukana kuitenkin (löytyy myös esim. Svenska ämnesord:issa), mutta se jäisi siinä tapauksessa pois, ellei voida harkita ottaa myös sairaalakirjastot (alakäsitteenä laitoskirjastoille)?

**Comment by LeKorsu** [comment]
Meneekö ihan metsään ja tuleeko älyttömästi korjaamista, jos:
laitoskirjastot (yliopistot), sv institutionsbibliotek (universitet)
laitoskirjastot (hoitolaitokset) sv anstaltsbibliotek (vårdinrättningar) TAI institutionsbibliotek (vårdinrättningar)
ohjaustermeinä:
sairaalakirjastot > laitoskirjastot (hoitolaitokset)
sjukhusbibliotek > anstaltsbibliotek (vårdinrättningar)
By the way, nyt ysassa on lähikirjastot > sivukirjastot, pitäisikö ohjausta vaihtaa toisinpäin?

**Comment by mirmaid** [comment]
Otetaan sairaalakirjastot LT laitoskirjastot (hoitolaitokset), sekä laitoskirjastot (yliopistot). (YSA-kokous 6.10.2016)
