### ISSUE TITLE
syyllisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4664]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[syyllisyys](http://www.yso.fi/onto/ysa/Y99135) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Pitääkö jakaa psykologia/oikeus? Ryhmänä vain 69 
#### Perustelut ehdotukselle

Käytetty molemmissa merkityksissä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
syyllisyys (psykologia) KÄ syyllisyydentunne?

**Comment by mariaforsen** [comment]
Jos jaettaisiin olisi skuld (psykologi) ja skuldkänsla hyvin synonyymisiä. Yllä oleva ehdotus siis hyvä.

**Comment by mirmaid** [comment]
Syyllisyys (psykologia) KÄ syyllisyydentunne. (YSA-kokous 6.10.2016)
