### ISSUE TITLE
tavat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4665]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[tavat](http://www.yso.fi/onto/ysa/Y99336) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Nyt LT tapakulttuuri, tavat ruots. seder. YSO:ssa on toivottu myös tavat-käsitettä ruots. sätt-merkityksessä (toimintavat). 
#### Perustelut ehdotukselle

Olisi hyvä kokoava käsite hierarkiassa 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by yrjolindegren** [comment]
Siis näinkö: tavat (tapakulttuuri) = seder ja tavat (toimintatavat) = sätt ?

**Comment by mariaforsen** [comment]
Yllä oleva ehdotus olisi paras mahdollinen ratkaisu ruotsiksikin. Sätt on kyllä kaivattu, mutta ei voida poistaa tärkeää ja pitkään käytetty seder-termiäkään.

**Comment by mirmaid** [comment]
Lisätään sulkutarkenne tavat (tapakulttuuri) ja otetaan termi tavat (toimintatavat). (YSA-kokous 6.10.2016)
