### ISSUE TITLE
teippaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4666]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[teippaus](http://www.yso.fi/onto/ysa/Y113049) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Onko ratkaisu teippaus KT kinesioteippaus paras mahdollinen? 
#### Perustelut ehdotukselle

Termiä on käytetty Melindassa nimenomaan kinesio-merkityksessä. Ehkä voi olla myös esim. mainosteippauksia yms. Teippaus voisi periaatteessa olla myös yläkäsite. Nykyinen luokka 00, ainakin pitäisi varmaan lisätä urheilu tai lääket. jos niputetaan näin. 
#### Ehdottaja

BTJ 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
1) kiinnittää, sitoa, sulkea, peittää; 
2) urheilu- yms. vammojen hoidossa ja ehkäisyssä: sitoa tiukasti teipin tapaisella siteellä

**Comment by mirmaid** [comment]
Melindassa kerran kinesioteippaus. Teippaus: 63 viitettä, 2 kertaa askartelu/taide, kerran mainosteippausta. Melindan viitteistä useimmat käsittelevät kyllä kinesioteippausta, mutta voidaanko sanoa että silloinkin on kyse kinesioteippauksesta jos kirjassa teippaukseen käytetään liimasidettä?

**Comment by satuniininen** [comment]
Melindan viitteissä oli paljon kinesioteippausta mutta mielestäni vielä enemmän urheiluteippausta yleensä. Kaikki urheiluteippaushan ei ole kinesioteippausta. Mielestäni ohjaus on OK, mutta kinesioteippaus voidaan varmaan ottaa myös omaksi käsitteekseen, mikäli se katsotaan tarpeelliseksi.

**Comment by mariaforsen** [comment]
Kun kerran teippaus/tejpning on käytetty ihan askartelumielessäkin (Ihana ilmastointiteippi : tarttuvaa teippiaskartelua : askartele luovasti arkeen ja juhlaan) ja muutenkin on selkeä termi niin olisiko kuitenkin mahdollista pitää molemmat sanastossa? Eli sekä "yleisterminä" että erikseen urheiluun/kinesioteippaukseen liittyvänä? Tejpning-sana sellaisenaan on kyllä hyvin "yleisluonteinen".

**Comment by LeKorsu** [comment]
Entä teippauksen säilyttäminen yleisterminä, ja urheiluteippaus uutena terminä ja kinesioteippaus KÄ urheiluteippaus?

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Urheiluteippi

**Comment by mirmaid** [comment]
Otetaan urheiluteippaus KT kinesioteippaus LT teippaus. (YSA-kokous 6.10.2016)
