### ISSUE TITLE
toiminnanohjaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4667]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[toiminnanohjaus](http://www.yso.fi/onto/ysa/Y113690) 
#### Tila

Käsittelyssä 
#### Perustelut ehdotukselle

Toiminnanohjaus on YSAssa liitetty vain ryhmiin hallinto ja taloustieteet. Nykyisin myös neuropsykologiaan on vakiintunut käsite TOIMINNANOHJAUS, jota tässä psykologisessa merkityksessä näkyy käytetyn mm. Melindassa. YSAn informaatio kaipaisi siis pientä kehittämistä tästä näkökulmasta. 
#### Ehdotettu muutos

Monimerkityksinen, selkeytettävä 
#### Ehdottaja

JYK 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
http://www.hus.fi/sairaanhoito/sairaanhoitopalvelut/foniatria/lapsen_neuropsykologinen_arvio/toiminnanohjaus/Sivut/default.aspx
https://fi.wikipedia.org/wiki/Toiminnanohjaus 
https://fi.wikipedia.org/wiki/Toiminnanohjausj%C3%A4rjestelm%C3%A4

**Comment by mirmaid** [comment]
Melindassa lähes 1000 viitettä. ”Toiminnanohjaus (eksekutiiviset toiminnot) on yleisnimitys ryhmälle taitoja, joiden avulla toteutetaan tavoitteellista toimintaa.” Löytyy myös toiminnanohjaustaidot-muotoa. 

Yksi mahdollinen ratkaisu olisi toiminnanohjaus (psykologia) KÄ toiminnanohjaustaidot – tosin väärinymmärryksen vaara jää tähänkin. 

Toiminnanohjaus (hallinto) voisi olla mahdollinen toinen vaihtoehto, mutta on kyllä vaikea sanoa sopiiko se kaikkiin tapauksiin.

**Comment by ilona-x** [comment]
Melindassa viitteitä yhteensä 952, näistä 403 tietueessa esiintyy lisäksi jokin seuraavista sanoista: ERP, toiminnanohjausjärjestelm?  tai enterprise resource planning. Näihin tietueisiin sopisi asiasanaksi toiminnanohjausjärjestelmät (KT ERP-järjestelmät) 

LCSH: Enterprise resource planning http://id.loc.gov/authorities/subjects/sh2011002664.html

**Comment by mariaforsen** [comment]
Toiminnanohjaus on nyt ruotsiksi verksamhetsstyrning, joka on tärkeä ja paljon käytetty termi, joten toivottavasti tätä ei muuteta vaan lisätään sitten mieluummin tarkenne, esim. yllä ehdotettu hallinto. Psykologiaan liittyvä toiminnanohjaus taas on ruotsiksi lähinnä "exekutiva funktioner". Eli ruotsin kannalta olisi selkeintä jakaa (hallinto) ja (psykologia).

**Comment by mirmaid** [comment]
ERP ruots. wikipedia affärssystem? https://sv.wikipedia.org/wiki/Aff%C3%A4rssystem

Mietin tuota mahdollisuutta itsekin, mutta ei se kyllä taida kattaa kaikkea mitä on kuvattu termillä tuon psykologian lisäksi. Hallinto on vaan tarkenteena hankala. Johtaminenkin voisi olla vaihtoehto...
https://fi.wikipedia.org/wiki/Ohjaus_%28yritysjohtaminen%29

**Comment by mirmaid** [comment]
Jaetaan toiminnanohjaus (psykologia) KT toiminnanohjaustaidot ja eksekutiiviset toiminnot ja toiminnanohjaus (organisaatiot) RT tuotannonohjaus. Otetaan lisäksi toiminnanohjausjärjestelmät. (YSA-kokous 6.10.2016)
