### ISSUE TITLE
tuntomerkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4668]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[tuntomerkit](http://www.yso.fi/onto/ysa/Y111644) 
#### Tila

Käsittelyssä 
#### Perustelut ehdotukselle

Ruotsiksi signalement, koskee vain ihmisiä, muunlaiset eli esim. kännetecken on nyt termin tunnusmerkit vastine. 
#### Ehdotettu muutos

Ruotsinkielinen ja suomenkielinen termi eivät täysin vastaa toisiaan, selkeytettävä 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
1) ominaisuus, piirre tms., josta jokin voidaan tuntea, tunnistaa; jollekin luonteenomainen piirre; 
2) tunnistusta helpottava merkki

**Comment by mirmaid** [comment]
Melindassa tyypillisesti eläinlajeista, joitakin kertoja sähköisen tunnistamisen tms. yhteydessä ihmisistä. Ennen kaikkea kuitenkin eläin- tai kasvilajien tuntomerkit. 

Tunnusmerkit on käytetty sekä konkreettisista tunnuksista että abstraktimmin ”masennuksen tunnusmerkit”. Tuntomerkit-termin vastine on varmaankin väärä ja mahdollisesti abstraktimpaa käyttöä olisi hyvä ohjata jotenkin muihin termeihin. Tunnusmerkit vaatisi ehkä vielä selvittämistä.

**Comment by mariaforsen** [comment]
Voidaan siinä tapauksessa muuttaa tuntomerkit=kännetecken (vaikka signalement onkin hyvin vanha käännös) ja asia on siltä osin hyvä. 

MOT tunnusmerkistä: "tavallisemmin: tuntomerkki, tunnus" ja jos tämä silti halutaan pitää sanastossa erillisenä terminä tarvitaan tarkempi määritelmä miten eroaa toisesta ja miten rajataan, sen jälkeen voidaan päättää jonkinlaisesta käännöksestä. Kännetecken käytetään nimittäin sekä konkreettisesta että abstraktisemmasta.. Mahdollinen ratkaisu olisi kännemärken, mutta se on todellisuudessa kyllä synonymi kännetecken-termille (siinä mielessä standardin vastainen).

**Comment by LeKorsu** [comment]
Anteeksi, mutta minä en nyt oikein ymmärrä, mikä tässä on ongelma . Eikö signalementia siis voi käyttää eläimistä ja kasveista? Nyt Melindassa 3 viitettä, joista yksi ihmisen tunnistamiseen, 2 viitettä eläintieteeseen.  Löydän pari viitettä, joissa on käytetty kännetecken, kun suomenkielinen termi on ollut tuntomerkit ( > signalement). Niissä viitteissä missä ei ole ruotsinkielistä termiä nämä menevät niin kuin Mirja tuossa ylemmässä kommentissa on laittanut. Pitääkö siis laittaa jokin huomautus / sulkutarkenne, että tuntomerkeillä (signalement) tarkoitetaan elollisia olentoja?

**Comment by mirmaid** [comment]
Wiktionary: signalement: beskrivning av en persons utseende, ofta i samband med polisutredningar

**Comment by mirmaid** [comment]
Joissakin tapauksissa voisi tunnusmerkit korvata termillä tunnukset suomeksi, ruots. beteckningar (näissä esiintyy asiasanoja tavaramerkit, tunnusmerkit.

Sairauksien yhteydessä ehkä ei edes tarpeen, ennemmin diagnosointi tms. 

EKS:ssä rikostunnusmerkistö - voisi sopia joihinkin

**Comment by mirmaid** [comment]
Korjataan tuntomerkit = kännetecken. Tutkitaan voiko tunnusmerkit-termin poistaa ja/tai ohjata käyttöä muihin termeihin (jatketaan seuraavassa kokouksessa). (YSA-kokous 6.10.2016)

**Comment by mirmaid** [comment]
> Joissakin tapauksissa voisi tunnusmerkit korvata termillä tunnukset suomeksi, ruots. beteckningar (näissä esiintyy asiasanoja tavaramerkit, tunnusmerkit.

Käytetty paljon (varsinkin aikaisemmin) nimenomaan konkreettisista merkeistä esim. sotilaspuvuissa

**Comment by mariaforsen** [comment]
Allärsissa siis nyt: tuntomerkit=kännetecken, tunnusmerkit=kännemärken

**Comment by mariaforsen** [comment]
Ei voi, signalement käytetään vain ihmisistä (=noggrann beskrivning av en persons yttre utseende särsk. i samband med efterlysning e.d.). Mutta nykyinen tuntomerkit=kännetecken toimii hyvin. 

Kännemärken on oikeastaan synonymi termille kännetecken, samalla tavalla kuin Kielitoimiston sanakirja antaa tunnusmerkki: tavallisemmin: tuntomerkki, tunnus.

**Comment by mirmaid** [comment]
Poistetaan sanastosta _tunnusmerkit_ ja korvataan se kuvailuissa termeillä _tunnukset_, _tavaramerkit_, _rikostunnusmerkistö_ (otetaan tämä YSAan)?

**Comment by mariaforsen** [comment]
Hyvä ratkaisu. Myös rikostunnusmerkistö=brottsrekvisit ok.

**Comment by YSA-kokous** [comment]
Poistetaan sanastosta _tunnusmerkit_ ja korvataan se kuvailuissa termeillä _tunnukset, tavaramerkit, rikostunnusmerkistö_ (otetaan tämä YSAan).
