### ISSUE TITLE
täyttömaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4669]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[täyttömaat](http://www.yso.fi/onto/ysa/Y175699) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Nyt täyttömaa KÄ täytemaa, lisäksi erikseen täyttömaat. Voiko yhdistää? 
#### Perustelut ehdotukselle

Epäselvä 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
täytemaa Melinda x 12
täyttömaat Melinda x 1 (Malminkartanonhuipun hoito- ja kehittämissuunnitelma)

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
täytemaa (maa-aines)
täyttömaa-alueet (KT täyttömaat, KT täyttöalueet) ruots. fyllnadsområden?

**Comment by mariaforsen** [comment]
Täytemaa hyvä ja saadaan näin oikea vastine (fyllnadsjord) tämän vastineeksi. 

En löydä täyttömaa-alueet mistään sanastosta ja vain vähän osumia Googlessa, onko todella tarpeen? Vai onko kyseessä siis maankaatopaikat? Ks. esim. http://www.hs.fi/kaupunki/a1383453399430 Siinä tapauksessa voitaisiin ehkä valita ruotsiksi schakttippar/schaktmassetippar, vaikkei olekaan -område-loppuisia sanoja olemassa.

**Comment by LeKorsu** [comment]
Täytemaa (maa-aines) hyvä.
Täyttömaa-alueet ei kuulosta yhtä hyvältä.  Sanoman tekstiarkistosta (1990-) löytyy osumia seuraavasti: täyttömaa-alueet > 13, täyttömaat > 491, täytemaa > 148, maantäyttöalueet > 23, maankaatopaikat > 188.  Juttuja en ole ehtinyt kuin silmäillä eikä minulle ole selvää, onko täyttömaaita, maantäyttöalueita ja maankaatopaikkoja käsitelty synonyymeinä.

**Comment by ilona-x** [comment]
Melindassa ainoa viite, jossa on käytetty termiä täyttömaat käsittelee Malminkartanon täyttömäkeä, eli ilmeisesti tarve on ollut juurikin termille, joka kuvaa alueita, joita on aiemmin käytetty maankaatopaikkoina, mutta jotka ovat nykyään muussa käytössä. Eli ainakaan tuohon viitteeseen ei mielestäni maankaatopaikka -termi kävisi. http://www.hel.fi/hel2/hkr/julkaisut/2010/Malminkartanonhuippu_web.pdf

Täyttömäkiä löytyy enemmänkin:
https://fi.wikipedia.org/wiki/Luokka:T%C3%A4ytt%C3%B6m%C3%A4et

Entä jos tuohon lisäisi sulkutarkenteen:

täyttömaat (maa-alueet)
täytemaa (maa-aines)

**Comment by mirmaid** [comment]
Pystyisitkö @LeKorsu vilkaisemaan mitä noissa täyttömaat-jutuissa on käsitelty? Maankaatopaikat voisi olla järkevä...tosin englanniksi ei taida olla eroa maankaatopaikalla ja kaatopaikalla (landfill site) @satuniininen? 

Melindan viitteessä on kyse Malminkartanonhuipusta https://fi.wikipedia.org/wiki/Malminkartanonhuippu. Toisaalta samankaltainen Vuosaarenhuippu on entinen kaatopaikka (ja maankaatopaikka).

Myös termiä maantäyttöpaikat esiintyy.

**Comment by mirmaid** [comment]
Tarvitaanko tuohon täytemaa edes tarkennetta jos täyttömaa-alkuista termiä ei ole? Jos esim. olisi täytemaa ja maankaatopaikat tai vain maankaatopaikat KÄ kaatopaikat.

**Comment by satuniininen** [comment]
Englannin landfills on tosiaankin aika monimerkityksinen, joten sikäli maankaatopaikat KÄ kaatopaikat olisi hyvä ratkaisu. Toisaalta sopivat sulkutarkenteet on kyllä löydettävissä kunhan vaan saadaan merkitys ensin määriteltyä suomeksi ja ruotsiksi. Eli kannatan jompaakumpaa näistä:

täytemaa ja maankaatopaikat 
TAI 
täytemaa ja  maankaatopaikat KÄ kaatopaikat

**Comment by LeKorsu** [comment]
Näyttää siltä, että (ainakin uusimmissa HS-jutuissa) täyttömaita on käytetty nimenomaan rakennus/uudelleen hyödyntämisen kannalta, kun taas maankaatopaikka enemmänkin kaatopaikka/jätemerkityksessä, 

Ja sotkeaksseni lisää, täyttömaa-sanalla tuli muuten osumia myös juttuihin, jossa käytetään termiä merentäyttö.

**Comment by mirmaid** [comment]
Jätetään sanastoon täytemaa KT täyttömaa (maa-aines). Poistetaan täyttömaat. (YSA-kokous 6.10.2016)
