### ISSUE TITLE
törmäys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4670]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[törmäys](http://www.yso.fi/onto/ysa/Y111486) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Pitäisikö olla ennemmin monikossa? 
#### Perustelut ehdotukselle

Useimmissa viitteissä monikko näyttäisi paremmalta (onnettomuudet – törmäys). 
#### Ehdottaja

Mirja Anttila 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by yrjolindegren** [comment]
Kannatan monikkoa

**Comment by ilona-x** [comment]
Tarvitaanko erottelu törmäykset liikenteessä vs. törmäykset fysiikassa?

LCSH:sta löytyy ainakin seuraavat:

Collisions, Automobile -> Traffic accidents
Airplane collisions -> Aircraft accidents
Railroad collisions -> Railroad accidents
Collisions at sea
Collisions (Physics)
Collisions (Astrophysics)

**Comment by LeKorsu** [comment]
Monikkomuoto saa äänen myös täältä. Melindassa näyttäisi olevan niin liikenteeseen, fysiikkaan kuin tähtitieteseen (astrofysiikka?) liittyviä teoksia. Pitäisikö siis tosiaan jaotella sulkutarkentein? Ja kun vielä lisää selaan viitteitä, näkyy törmäystä käytetyn myös kulttuurien törmäyksessä.

**Comment by satuniininen** [comment]
Kannatan myös monikkoa mutta toivoisin, että pärjättäisiin ilman jakamista. Molemmissa tapauksissa on kuitenkin kyse saman asian erilaisista variaatioista. Kuvailussa on aina mukana muitakin asiasanoja kontekstia antamassa.

**Comment by mirmaid** [comment]
Vaihdetaan törmäys monikkoon, ei jaeta tässä vaiheessa. (YSA-kokous 6.10.2016)
