### ISSUE TITLE
uusinnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4671]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[uusinnat](http://www.yso.fi/onto/ysa/Y110244) 
#### Tila

Käsittelyssä 
#### Perustelut ehdotukselle

Ruotsiksi kaksi termiä. 
#### Ehdotettu muutos

Jaettava/selkeytettävä 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
1) uusiminen; 
2) uusintaesitys, -kilpailu tms.; 
3) uusimisen tulos, uusittu laitos

**Comment by mirmaid** [comment]
Melindassa kahta tv-ohjelmia käsittelevää teosta lukuun ottamatta uusiminen olisi parempi. Otetaanko uusiminen lisäksi ja korjataan viitteet? Uusinnat – voisikohan luokaksi vaihtaa 80 ja suhteita ehkä muuttaa?

**Comment by mariaforsen** [comment]
Jos vaihdetaan uusinnat-termin luokaksi 80 on nykyinen ruotsinkielinen repriser hyvä, eli ongelma ratkaistu sen osalta. Uusiminen sen sijaan ei ole ongelmaton, voi olla omtagning (esim. röntgenkuva), förnyande (esim. lääkemääräys), "göra om" (esim. rikos). Ks. MOT: 17 merkitystä termille "uusia"! Jos pitää valita yksi (mikä ei periaatteessa ole mahdollista) olisi "göra om" neutraalein valinta (mutta huono muotonsa puolesta).

**Comment by mirmaid** [comment]
Korjataan uusinnat-termin ryhmä ja suhteet. Tutkitaan vielä mahdollisuuksia ottaa uusiminen-termi niin että myös ruotsiksi saadaan sopiva vastine/vastineet (jatketaan tämän osalta seuraavassa kokouksessa). (YSA-kokous 6.10.2016)

**Comment by mirmaid** [comment]
YSAssa on jo rikoksen uusiminen, joten sitä ei mielestäni tarvitse huomioida tässä. Melindassa 6 viitteistä joissa nyt _uusinnat_ olisi tätä. 

Yhteensä _uusinnat_ Melindassa vain 16 kertaa. 2 näistä televisiota (_uusinnat_ ok). Muut:

- reseptin uusiminen 2 kertaa
- röntgenkuvan uusiminen 3 kertaa
- uusintaleikkaus kerran
- päällysteen uusiminen (tienrakennus) kerran
- huollon uusiminen kerran

**Comment by LeKorsu** [comment]
Uusiminen ryhmään 00 kävisi varmaan suomeksi, mutta ruotsinkielinen vastine tuottanee edelleen ongelmia.

**Comment by mariaforsen** [comment]
Näin on, ruotsin termiä ei voida valita ennen kuin on valittu mihin tämä suomeksi viittaa/miten käytetään.

**Comment by mirmaid** [comment]
Suomeksi noihin kaikkiin kävisi ihan hyvin uusiminen, joten pääsemme parhaiten eteenpäin jos laitat noille edellisessäni kommentissani mainituille käyttötapauksille mitä ruotsiksi käytettäisiin niissä. Sitten voisi yrittää arvioida löytyykö jotain merkitystä joka voidaan vaikka erottaa tarkenteella tai josta voi käyttää jotain fraasia.

**Comment by mirmaid** [comment]
Eli Maria @mariaforsen voitko laittaa ruotsinkielisen vastineen näille:

- reseptin uusiminen
- röntgenkuvan uusiminen
- uusintaleikkaus
- päällysteen uusiminen (tienrakennus)
- huollon uusiminen

**Comment by mariaforsen** [comment]
reseptin uusiminen=receptförnyelse
röntgenkuvan uusiminen=omtagning.. av röntgenbild
uusintaleikkaus=reoperation (myös MESHissä)
päällysten uusiminen=beläggningsförnyelse, förnyelse/förnyande av beläggning
huollon uusiminen= huolto on monimerkityksinen, mutta näissä merkityksissä usein upprepning, göra om tms.

**Comment by mirmaid** [comment]
Suuri ongelmahan tämä ei ole koska käyttökertoja on vain kourallinen. Jos vain poistaa omtagning-vastineen (ja mahd. tietueista pois uusinnat > 653 uusiminen)? Melindan uusin viite 2014.

**Comment by mariaforsen** [comment]
Toivattavasti kuvailijat jatkossa käyttävät nimenomaan ohjelmien uusintoihin, koska tällä hetkellä sehän on käytetty Melindassa lähinnä nimenomaan muihin asioihin kuin niihin. Olisiko hyvä lisätä lyhyt huomautus, kun YSAssa kerran viittaa vain yhdenlaiseen uusintaan (vrt. MOT)?

**Comment by mirmaid** [comment]
Huomautus voidaan laittaa, ja jos tarkenteeksi käy (media), niin ei sekään ole poissuljettu. Omaan korvaani käyttö noissa muissa (esim. lääketieteellisissä) merkityksissä on kyllä niin väkisin väännettyä että tuskin kovin paljon käytettäisiin jatkossakaan.

**Comment by YSA-kokous** [comment]
uusinnat (media)

**Comment by mariaforsen** [comment]
Sv. repriser (media)
