### ISSUE TITLE
vaatetussuunnittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4672]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[vaatetussuunnittelu](http://www.yso.fi/onto/ysa/Y103585) 
#### Tila

Käsittelyssä 
#### Perustelut ehdotukselle

Vaihdettiin vaatetusliikkeet > vaateliikkeet. 
#### Ehdotettu muutos

> vaatesuunnittelu, samoin vaatesuunnittelijat KT vaatetussuunnittelijat 
#### Ehdottaja

Mirja Anttila 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
Kannatan

**Comment by AuHo22** [comment]
Lyhempi muoto on yhteisymmärryksessä suomen kielen yleisen lyhentämispyrkimyksen kanssa. Vaatetussuunnittelu alkaa vivahtaa vähän samalla tavalla vanhanaikaiselta kuin jos joku puhuisi nykyisin vielä vaikkapa klassillisesta, nykyisin po. klassinen.

**Comment by mirmaid** [comment]
Vaihdetaan molemmat (YSA-kokous 6.10.2016)
