### ISSUE TITLE
vaipat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4674]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[vaipat](http://www.yso.fi/onto/ysa/Y125728) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Jaettava 
#### Perustelut ehdotukselle

Melindassa käytetty sekä lastentarvikkeena että rakennustekniikassa. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kaikki YSAan merkityt vaipat ovat yhtä lukuun ottamatta lastentarvikkeita. Halutaanko tuon yhden takia lisätä sanastoon ”rakennuksen vaippa” tai ”rakennusten vaipat” tms.?

**Comment by satuniininen** [comment]
En kannata molempien ottamista sanastoon. Vaipat-käsitteen voisi rajata käytettäväksi pelkästään lastentarvike-merkityksessä. Vaatisiko sulkutarkenteen?

**Comment by mariaforsen** [comment]
En kannata minäkään "rakennusvaippojen" lisäämistä, tietäisi myös lisää ongelmia ruotsin kannalta. Oikeat luokat ja ehkä huomautus riittänee?

**Comment by AuHo22** [comment]
Entäpä termi ulkovaipat - sitäkin näköjään käytetään? Esim. https://fi.wikipedia.org/wiki/Rakennuksen_vaippa, jne.

**Comment by LeKorsu** [comment]
Muuna kuin ysa-terminä vaippoja näytetään käytetyn parissa muussakin teoksessa, peltiseppien oppikirjassa "kappaleen vaipat",  sekä yksi rakennustekniikkaan liittyvä opus sen toisen viitteen lisäksi, jossa vaippoja on käytetty asiasanana. Minäkään en kannata rakennusvaippojen lisäämistä, mutta pitäisikö kuitenkin miettiä sulkutarkenne-jakamista vaipat (lastentarvikkeet), vaipat (tekniikka)?

**Comment by mirmaid** [comment]
Tarkennetaan vaipat (hygieniatuotteet) (YSA-kokous 6.10.2016)
