### ISSUE TITLE
vedenpuute

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4675]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[vedenpuute](http://www.yso.fi/onto/ysa/Y169385) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Tarkoittaako samaa kuin vesipula? 
#### Perustelut ehdotukselle

Ruotsiksi NetMotin mukaan vesipula = vattenbrist ja vedenpuute = vattenbrist 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindassa käytetty vedenpuute x 10, joista 8 tietueessa myös vesipula.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: yhdistetään

**Comment by Elmukelmu** [comment]
Olisko tuolla vedenpuutteella ollut alunperin käyttöä jossain biologian alueella, esim. kasvin vedenpuute?

**Comment by mariaforsen** [comment]
Ruotsiksi vattenbrist riippumatta mistä organismista tms. kyse ja näin taitaa olla yleisestikin.

**Comment by mirmaid** [comment]
Yhdistetään vedenpuute KÄ vesipula (YSA-kokous 6.10.2016)
