### ISSUE TITLE
vesiviljely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4676]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[vesiviljely](http://www.yso.fi/onto/ysa/Y104850) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Jaettava 
#### Perustelut ehdotukselle

Kaksi merkitystä, kalanviljely (tms.) ja kasvien viljelymenetelmä. 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Wikipediassa kasvinviljely on ”hydroviljely” (hydroponics).

**Comment by mirmaid** [comment]
Ratkaisuehdotus:
Kasvinviljely voisi olla hydroviljely (KT vesiviljely (kasvinviljely)), voiko toinen olla vesiviljely (kalatalous)?

**Comment by mariaforsen** [comment]
Tämä olisi hyvä myös ruotsin kannalta: 1. hydrokultur  2. akvakultur/vattenbruk

**Comment by mirmaid** [comment]
Tuo ehdotus siis vaatisi kalatalouden ymmärtämistä laajasti kaikkien vedessä viljeltävien eläinten kasvatukseksi.

**Comment by mirmaid** [comment]
Jaetaan ja lisätään vesiviljely (kalatalous) -termille selitys että sisältää myös simpukat ym. (YSA-kokous 6.10.2016)
