### ISSUE TITLE
voitelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4677]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[voitelu](http://www.yso.fi/onto/ysa/Y100302) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Jaettu YSOssa (käsittely) ja (uskonto) 
#### Perustelut ehdotukselle

Eri asioita 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Onko käsittely hyvä myös jos kyse on automatisoidusta jatkuvasta voitelusta (esim. moottorin tms.)?

**Comment by satuniininen** [comment]
Voisiko olla (tekniikka) ja (uskonto)? Voisi olla kuvailijan kannalta helpompi hahmottaa ero.

**Comment by AuHo22** [comment]
Kannatan myös tuota (tekniikka) -tarkennetta.

**Comment by yrjolindegren** [comment]
Sulkutarkenne (käsittely) kattaisi mielestäni ei-uskonnolliset voitelut paremmin kuin (tekniikka), esim. 
"haavan voitelu", "ihon voitelu"; voitelua esiintyy myös leivonnassa ja ruoanvalmistuksessa.

**Comment by LeKorsu** [comment]
Minä kallistun tuon käsittely-sulkutarkenteen kannalle.

**Comment by OutiHintikka** [comment]
voitelu (uskonto) KÄ viimeinen voitelu

**Comment by OutiHintikka** [comment]
Yrjö: ei haavaa voidella, vaan termi on haavan hoito eli sitä hoidetaan. Myöskään ihoa ei voidella, vaan rasvataan.

**Comment by AuHo22** [comment]
Helmet-haulla saa aika paljon osumia taas suksien voitelusta - mitenkähän ruotsinkieliset käännökset taipuvat kaikkiin näihin tapauksiin?

**Comment by mirmaid** [comment]
Uskonnollista voitelua on muutakin kuin se viimeinen. 

Tekniikka sopisi varmaan useimmiten mutta suksien voitelun yhteydessä käsittely on parempi. Mutta toisaalta uskonnollinen voitelukin on kyllä tietynlaista käsittelyä :grin:

**Comment by mirmaid** [comment]
Otetaan erikseen suksien voitelu, sekä voitelu (uskonto) ja voitelu (tekniikka), mikäli (tekniikka)-tarkenne soveltuu kaikkiin Melindan tapauksiin. (YSA-kokous 6.10.2016)
