### ISSUE TITLE
yhteiskunnallinen kehitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4678]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[yhteiskunnallinen kehitys](http://www.yso.fi/onto/ysa/Y186445) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Mikä on näiden kahden termin (yhteiskunnallinen kehitys, yhteiskuntakehitys) ero?  Voisitko laittaa termeihin määritelmät ja/tai tuoda termit määriteltäväksi tulevaan YSA-kokoukseen. 
#### Perustelut ehdotukselle

Varmaan ero on ollut kristallinkirkas silloin, kun toinen samankaltainen termi on sanastoon tarvittu. Nyt se ei enää sitä ole. 
#### Ehdottaja

BTJ 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ajatus on (mielestäni) että yhteiskuntakehitys on laajemmin koko yhteiskunnan muutos (esim. modernisaatio) ja yhteiskunnallinen voi olla rajatumpaa esim. alueellista, ehkä lyhyelläkin aikajänteellä tai tietyn osa-alueen/sektorin kehittymisen tarkastelua (esim. koulutuksen). Mutta todellakin tämä on vaikea erottelu sekä kuvailijan että hakijan kannalta.

**Comment by mirmaid** [comment]
Melinda yhteiskuntakehitys x 4365 & yhteiskunnallinen kehitys x 273  & 21 tietuetta joissa molemmat

Melindassa käytetty termejä ristiin, ja määritelmätkään eivät välttämättä auta, kun termit ovat niin lähellä toisiaan ja merkityseroa vaikea hahmottaa.

Esim. näissä Melindassa yhteiskunnallinen kehitys:
• Putinin väkeä : Venäjän hiljainen enemmistö
• Civilization and modernization : proceedings of the Russian-Chinese conference 2012
• The great degeneration : how institutions decay and economies die 
• Sounds of modern history : auditory cultures in 19th- and 20th- century Europe

ja näissä yhteiskuntakehitys:
• City of noise : sound and nineteenth-century Paris
• Max Liebermann : modern art and modern Germany
• Kuvis 20XX : oppiaineemme tulevaisuuden koulussa
• Kustavin Kaurissalossa on Itätalo

**Comment by mirmaid** [comment]
YSAssa taloudellinen kehitys KT talouskehitys

**Comment by mirmaid** [comment]
Ratkaisuehdotus: yhteiskuntakehitys KT yhteiskunnallinen kehitys

**Comment by mariaforsen** [comment]
Ei eroa ruotsiksikaan ja SAOssa vain samhällsutveckling. Hyvä ratkaisuehdotus!

**Comment by mirmaid** [comment]
Yhdistetään (YSA-kokous 6.10.2016)
