### ISSUE TITLE
ympäristövauriot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4679]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[ympäristövauriot](http://www.yso.fi/onto/ysa/Y100466) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Yhdistetään termiin ympäristövahingot 
#### Perustelut ehdotukselle

Ruotsiksi sama 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ympäristövahinko määritellään yleensä äkillisen tapahtuman aiheuttamaksi vahingoksi, jonka seurauksena ympäristölle haitallista ainetta tai energiaa joutuu tai saattaa joutua ympäristöön. Ympäristövahinko voi syntyä nopeasti esimerkiksi onnettomuuden tai laiminlyönnin vuoksi tai pidemmän ajan kuluessa ympäristölle haitallisen aineen vuotaessa pikkuhiljaa ympäristöön. Ympäristövahinko voi kohdistua mm. maaperään, ilmaan, luontoon sekä pinta- ja pohjavesiin. http://www.ymparisto.fi/fi-fi/kulutus_ja_tuotanto/Vastuu_ymparistovahingoista

**Comment by mirmaid** [comment]
Voisiko käyttää termiä ympäristövahingot esim. jos julkaisu käsittelee luontomatkailun aiheuttamia ympäristövaurioita? Eli jos toiminta on ihan tarkoituksellista (soranotto), tai ei varsinaisesti kohdistu ympäristöön (esim. sota) vaan ympäristövauriot ovat ”oheistuotetta”. YSAssa on toisaalta myös _ympäristövaikutukset_ ja _ympäristöhaitat_.

**Comment by mirmaid** [comment]
Melinda: ympäristövauriot 215, ympäristövahingot 418

**Comment by mirmaid** [comment]
SYKE: 
Ympäristövaurio:
Minusta se tuntuu vieraalta ja vaurio viittaa minun korvissa johonkin konkreettiseen muutokseen, mutta sitä näköjään käytetään:
Huomaan, että ”ympäristövaurio” esiintyy EU:n sanastossa: EuroVoc homepage Euroopan unionin monikielinen tesaurus.
Huomaan sen kuitenkin esiintyvän env. damage sanan synonyyminä Glosbe-sanakirjassa ja siinä otetaan useita esimerkkejä mm. eduskunnan kielenkäytöstä, jossa se esiintyy.
Myös hallituksen esityksen perusteluissa ympäristövahinkolain muutokseksi vuodelta 1992 tuntee sanan. Sen sijaan lakiteksteissä sanaa ei ole käytetty.

Ympäristövahinko:
Minun määritelmäni, jossa ideana on korostaa sen monenlaista käyttöä:
Ympäristövahinko on oikeustieteessä tunnettu, mutta monimerkityksinen käsite. Laajimmillaan se tarkoittaa kaikkia ihmisen tahallaan tai tahattomasti aiheuttamia haittoja ympäristölle. Kyseessä voi olla äkillinen tapahtuma, jonka seurauksena ympäristölle haitallista ainetta tai energiaa joutuu tai saattaa joutua ympäristöön, mutta myös vähitellen aiheutuva päästö ympäristöön. Puhutaan laillisista vahingoista, joiden aiheuttaminen on ympäristöluvalla nimenomaisesti sallittu ja toisaalta laittomista vahingoista, jotka ovat aiheutuneet lainvastaisen toiminnan tuloksena. Suomen ympäristövahinkoja koskevan erityislain (ympäristövahinkolaki) käsite on suppea, sillä ympäristövahinkona ei pidetä ympäristön muuttumista tai pilaantumista sinänsä, vaan vasta siitä jollekin aiheutunutta henkilö- tai esinevahinkoa taikka muuta taloudellista menetystä. Vahingonkorvausoikeuden ja ennallistamisvastuusääntelyiden väliin jää aiheuttajaltaan yksilöimättömän taustakuormituksen, hajakuormituksen ja ilman saasteiden kaukokulkeutumisen aiheuttama ympäristön pilaantuminen. Esimerkkinä vastuusääntelyn kannalta ”harmaasta alueesta” on viljelykäytössä olevien happamien sulfaattimaiden vaikutus vesistöjen vedenlaatuun ja eliöstöön sekä kalakuolemiin. Lisääntyneen salaojituksen aiheuttaman happamoitumisen myötä peltojen maaperästä liukenee myrkyllisiä metalleja pikkujokiin, jotka ovat olleet käytännössä kalattomia viimeisten vuosikymmenten ajan.

Huomautan lisäksi että ympäristöoikeudessa ja lainsäädännössä esiintyy myös ”öljyvahinko”, joka on yksi muoto ympäristövahinkoja. (kts. esim. Tieteen termipankki)

**Comment by mirmaid** [comment]
ympäristövauriot KÄ ympäristövaikutukset, ympäristövahingot, ympäristöhaitat (?)

**Comment by mariaforsen** [comment]
Hyvä ratkaisu. Miljöskador käytetään hyvin laajasti, riippumatta miten on tapahtunut, kuka aiheuttanut jne. Ympäristövaurio ei edes löydy MOTista, TEPAsta tai IATEsta, joten ei varmaan ihan välttämätön erillisenä terminä asiasanastossakaan.

**Comment by mirmaid** [comment]
Yhdistetään (YSA-kokous 6.10.2016)
