### ISSUE TITLE
kokeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4680]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[kokeet](http://www.yso.fi/onto/ysa/Y102606) 
#### Tila

Käsittelyssä 
#### Perustelut ehdotukselle

Allärsissa kaksi vastinetta: experiment ja prov. 
#### Ehdotettu muutos

Jaettava 
#### Ehdottaja

YSO 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Allärsissa kaksi vastinetta: experiment ja prov. Alakäsitteet yleensä prov-loppuisia, lukuunottamatta seuraavia:
lääketieteelliset kokeet – medicinska _experiment_ (verikokeet _blodprov_)
eläinkokeet, ihmiskokeet, viljelykokeet – _försök_

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
koe: jnk ilmiön, ominaisuuden tms. tutkimiseksi t. määrittämiseksi tehtävä käytännön toimenpide(sarja), testi. _Psykologinen koe. Laboratoriokoe. Avaruus-, ydinkoe. Kestävyys-, vetokoe. Verikoe. Koe murtolujuuden määrittämiseksi. Tehdä kokeita marsuilla._

Erik., us. mon. oppilaitoksen tms. järjestämä tietojen ja taitojen tutkintatilaisuus. _Kirjallinen, suullinen koe. Englannin kielen koe. Soveltuvuus-, valintakoe. Ylioppilaskoe. Epäonnistua kokeissa. Sai kokeesta t. kokeista kympin._ 

Jälkimmäinen = prov. Samoin ensimmäisestä psykologinen ja laboratoriokoe olisivat prov (?).

**Comment by mirmaid** [comment]
Melindan ensimmäinen viite käsittelee perustulokokeiluja (kenttäkokeita). Tämä olisi ruotsiksi ”försök” > experiment. Suomeksi voisi ajatella sulkutarkennatta (tutkimukset), mutta suomenkielinen mieltäisi myös verikokeen tutkimukseksi. 
Verikokeelle voisi ajatella sulkutarkennetta (testit), mutta suomenkielinen voisi hyvin ajatella että se sopii myös mainittuun perustulo-kenttäkokeeseen (tai esim. viljelykokeisiin).

**Comment by mirmaid** [comment]
Jonkinlainen kompromissi voisi olla ketjutusmainen jako useampaan kuin kahteen, esim. 
1. kokeet (terveydenhuolto) – verikokeet ym.
2. kokeet (opiskelu/(oppilas)arviointi) – kokeet koulussa/koulutuksessa
3. kokeet (tutkimustoiminta) – tieteelliset tutkimukset
- Tämä kuitenkin pakottaisi laittamaan esim. asekokeet ryhmään experiment, vaikka nekin ovat ruotsiksi prov.
- Lentokoneille ym. laitteille tehdyt kokeet ovat myös prov. Ei oikein sopisi ehdotettuun jakoon.
- Lapsille suunnatut ”tutkimuskirjat” pitäisi osata laittaa myös tutkimustoimintaan, ei opiskeluun. (”Tutkimus” olisi varmaan paremman kuuloinen tarkenne, mutta mukaan ei saisi tulla terveystutkimuksia…)
- Edellyttäisi varmaan kliinisen tutkimuksen jakamista myös kahtia, mahdollisesti myös lääketieteelliset kokeet  
- Koiraharrastuksen kokeet eivät sovi vielä mihinkään mainituista

**Comment by mirmaid** [comment]
Edellyttäisi varmaan kliinisen tutkimuksen jakamista myös kahtia, mahdollisesti myös lääketieteelliset kokeet

**Comment by mirmaid** [comment]
[Venymämittaus](http://linda.linneanet.fi/F/G63DG19J5YM3N4N5JGN5D2M89ML5BI78CYDLPMBYEXMV6C5K41-06186?func=full-set-set&set_number=184429&set_entry=000001&format=999) – tietueessa sekä experiment että dragprov

**Comment by mariaforsen** [comment]
Yllä oleva jakoehdotus kolmeen näyttää hyvältä (vaikkei olekaan täysin ongelmaton). Jos olisi "kokeet (arviointi)" niin se rajaisi kyllä termin merkitys sopivasti, mutta ei pelkästään opiskeluun (eli sopisi myös koiraharrastuksen kokeisiin olettaen että niissä arvioidaan jotain).
.

**Comment by tpalonen** [comment]
Kannatan "kokeet (opiskelu/(oppilas)arviointi)"-tapauksessa sulkutarkennevaihtoehtoa "opiskelu", arviointi on liian epämääräinen/laaja merkitykseltään eikä välttämättä assosioidu koulumaailmaan.

**Comment by mariaforsen** [comment]
Millä siinä tapauksessa kuvaillaan muunlaisia kokeita joissa arvioidaan jonkun kykyä tms.? Kokeita "arviointi"-merkityksessä voi olla tarpeen muissakin asioissa kuin pelkästään opiskelussa. Esim. Melindan Elämää koiran kanssa : suomalainen koiraharrastus ennen ja nyt / Kaija Unhola.

**Comment by satuniininen** [comment]
Jako kolmeen menisi englanniksi:
1. tests (health care)
2. examinations (education)
3. experiments 

Näistä ensimmäinen on se heikoin lenkki, koska sanastossa on myös testit - tests, jotka nekin liittyvät usein terveydenhuoltoon. Sulkutarkenteita täytyy vielä pohtia.

**Comment by mariaforsen** [comment]
Jos päädytään kakkostapauksessa vähän laajempaan koemerkitykseen niin että kattaa myös koulun ulkopuolella tehtäviä kokeita, joissa arvioidaan jonkun taidot, tiedot tms., niin olisiko esim. examinations (evaluation) tms. mahdollista laittaa?

**Comment by satuniininen** [comment]
On mahdollista, riippuu ihan käsitteen rajauksesta.

**Comment by siikaa** [comment]
Kannatan myös 2. kokeet (arviointi)

**Comment by YSA-kokous** [comment]
kokeet (arviointi)
kokeet (tutkimustoiminta) 

Jatketaan kokeet (terveydenhuolto) -merkityksen selvittämistä.

**Comment by MikkoAleksanteri** [comment]
YSO-kokouksessa nousi kysymys käsitteiden 
_kokeet (terveydenhuolto)_ ja
_[kliiniset kokeet](http://finto.fi/ysa/fi/page/Y214003)_
erosta.

**Comment by ilona-x** [comment]
Korjattu Melindaan kokeet -> kokeet (arviointi) & kokeet (tutkimustoiminta). Jäljelle jäi 6 viitettä:

The role of Abl2 in T cell activation in experimental autoimmune encephalomyelitis / Elina Heinonen

Koelentäminen ilmavoimissa. 1984-2013 / Jyrki Laukkanen

Koelentäminen ilmavoimissa. 1958-1983 / Jyrki Laukkanen

Koelentäminen ilmavoimissa. 1918-1957 / Jyrki Laukkanen

Koelentotoiminta 1939-1945 / Aimo E. Juhola

Relating consumer, descriptive, and laboratory data to better understand consumer responses / Alejandra M. Munoz

**Comment by mariaforsen** [comment]
Kliiniset kokeet=kliniska prövningar -tämä on aivan eri asia kuin kokeet (terveydenhuolto), eli esim. verikokeet. Ks. http://finto.fi/mesh/sv/page/D016430 Kliinisissä kokeissa tutkitaan (tieteellisesti) esim. hoitojen, lääkkeiden yms. toimivuutta jne.)

**Comment by mirmaid** [comment]
Saa nähdä miten hyvin tämä jako jatkossa toimii, voisin kuvitella laittavani noihin koelentokirjoihin kumman tahansa nykyisistä _kokeet_-termeistä.

**Comment by YSA-kokous** [comment]
Jatketaan tarkenteilla (arviointi) ja (tutkimustoiminta).

**Comment by mirmaid** [comment]
Jää vielä _laboratoriokokeet_ ja _verikokeet_. Hierarkia voisi olla:
verikokeet LT laboratoriokokeet LT testit?

**Comment by YSA-kokous** [comment]
verikokeet LT laboratoriokokeet LT testit
