### ISSUE TITLE
länsimainen ruokavalio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4681]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

länsimainen ruokavalio 
#### Ehdotettu termi englanniksi

Western-style diet (WD) 
#### Ehdotettu yläkäsite YSOssa (LT)

[ruokavaliot](http://www.yso.fi/onto/yso/p3790) 
#### exactMatch

MeSH (Termix) : Diet, Western 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 
#### Perustelut ehdotukselle

Tarvitaan suomalaisen väitöskirjasn kuvailussa
http://terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=uut04783&p_teos=uut&p_osio=101&p_selaus=
https://fi.wikipedia.org/wiki/L%C3%A4nsimainen_ruokavalio
http://www.laakarilehti.fi/ajassa/ajankohtaista/lansimainen-ruokavalio-lisaa-sydanriskia-kaikkialla/ 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://helda.helsinki.fi/handle/10138/162207 
#### Vaihtoehtoiset termit ja ilmaisut

Western diet 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [länsimainen ruokavalio](http://finto.fi/yse/fi/page/Y504681)

**Comment by LeKorsu** [comment]
Onhan ysassa jo Välimeren ruokavaliokin, niin mikä ettei, jos tällainen termi on jo yleisesti käytetty.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
