### ISSUE TITLE
liuennut orgaaninen hiili

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4682]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

liuennut orgaaninen hiili 
#### Ehdotettu termi englanniksi

dissolved organic carbon 
#### Ehdotettu yläkäsite YSOssa (LT)

[hiili](http://www.yso.fi/onto/yso/p138) 
#### Assosiatiiviset (ST)

[orgaaninen aines](http://www.yso.fi/onto/yso/p14873) 
#### Vaihtoehtoiset termit ja ilmaisut

DOC 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 
[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 
#### Perustelut ehdotukselle

Tarvitaan suomalaisen väitöskirjan kuvailuun 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

http://www.metla.fi/dissertationes/df215-abstrakti.htm 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [liuennut orgaaninen hiili](http://finto.fi/yse/fi/page/Y504682)

**Comment by mirmaid** [comment]
Liuenneen organisen hiilen (DOC, engl. Dissolved Organic Carbon) mittaaminen antaa kaiken veteen liuenneen hiilen määrän yksikössä milligrammoja litrassa vettä (mgC/l).

**Comment by mirmaid** [comment]
Käytetty Melindassa 3 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
