### ISSUE TITLE
jousikvartetot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4683]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

jousikvartetot 
#### Ehdotettu termi ruotsiksi

stråkkvartetter (komposition) 
#### Ehdotettu termi englanniksi

strings quartets (composition) 
#### exactMatch

LCSH : String quartets 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
#### Tarkoitusta täsmentävä selite

Pitää kyetä erottamaan toisistaan jousikvartetit ja sellaisile sävelletyt jousikvartetot myös muissa kielessä (suomessa ero on jo ilmaisussa, mutta ei ruotsissa tai englannissa) 
#### Perustelut ehdotukselle

Jousikvartetto on yksi tunnetuimmista sävellystyypeistä, josta on myös runsaasti kirjallisuutta; nyt "ketjuttomalla" aikakaudella ei ole mitään tapaan ilmaista täsmällisesti sisällönkuvailussa, että aiheena on sävellykset, joiden esityskokoonpanona on kaksi viulua, alttoviulu ja sello (aiemmin esim.: "musiikkianalyysi : kvartetot : jousisoittimet : Unkari : 1900-luku" 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Muoto, monotemaattisuus, muuntelu ja symmetria Béla Bartókin jousikvartetoissa 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [jousikvartetot](http://finto.fi/yse/fi/page/Y504683)

**Comment by TommiViitamies** [comment]
Luumu-ryhmä ehdottaa: hyväksytään.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)

**Comment by mirmaid** [comment]
LT kamarimusiikki. Voisi olla myös sävellykset, mutta YSAssa sillä ei ole alakäsitteitä.
