### ISSUE TITLE
munasienet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4684]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

munasienet 
#### Ehdotettu yläkäsite YSOssa (LT)

[aitotumaiset](http://www.yso.fi/onto/yso/p20765) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
#### Perustelut ehdotukselle

Tarvitaan artikkelin sisällönkuvailuun ARTOssa 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Rapuruttoloinen - monimuotoinen ja muuntautumiskykyinen. Luonnon tutkija 2016:1, s. 4-12 
#### Vaihtoehtoiset termit ja ilmaisut

Oomycota 
#### Tarkoitusta täsmentävä selite

https://laji.fi/taksonomia/MX.52911/all?locale=fi#show 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [munasienet](http://finto.fi/yse/fi/page/Y504684)

**Comment by mirmaid** [comment]
Ovat sienenkaltaisia aitotumaisia eliöitä, hyvin kaukaista sukua sienille, luetaan samaan kaareen (pääjakso) kuin mm. rusko- ja piilevät. Munasienten ryhmään kuuluu monia taudinaiheuttajia, esim. perunarutto, rapuruttoloinen.

**Comment by mirmaid** [comment]
https://laji.fi/taxon/MX.52950

**Comment by mirmaid** [comment]
Käytetty Melindassa 5 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
