### ISSUE TITLE
luontoonpalautus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4685]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

luontoonpalautus 
#### Ehdotettu yläkäsite YSOssa (LT)

[palautus](http://www.yso.fi/onto/yso/p14970) 
#### Assosiatiiviset (ST)

[lajiensuojelu](http://www.yso.fi/onto/yso/p29081) 
[uhanalaiset lajit](http://www.yso.fi/onto/yso/p11643) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 
#### Perustelut ehdotukselle

Tarvitaan artikkelin kivailuun ARTOssa 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Ex situ -suojelu Korkeasaaren eläintarhassa. Luonnon tutkija 2016:1 s. 13-19 
#### Tarkoitusta täsmentävä selite

Ehdotus: Tarkoittaa eläinlajin yksilöiden siirtämistä eläintarhasta luontoon.
http://www.korkeasaari.fi/suojelutyo/suojelutyo-korkeasaaressa/ 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [luontoonpalautus](http://finto.fi/yse/fi/page/Y504685)

**Comment by mirmaid** [comment]
Käytetty Melindassa 2 kertaa.

**Comment by Elmukelmu** [comment]
Hyvä termi, tälle on käyttöä

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
