### ISSUE TITLE
koraalivirsikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4686]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[koraalivirsikirjat](http://www.yso.fi/onto/ysa/Y96327) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

KT-muoto "koraalikirjat" otetaan omaksi käsitteekseen samalla tavoin kuin on Musassa. 
#### Perustelut ehdotukselle

Kyseessä ovat nuottijulkaisut, jotka sisältävät ensisijaisesti virsien säestysosuudet toisin kuin koraalivirsikirjat, jotka sisältävät vain virsien sanat ja koraalimelodian (ilman säestystä). Koraalikirjaan ei ole välttämättä painettu sanoja laisinkaan. Koraalivirsikirjat KT koraalikirjat pitäisi poistaa, koska kyse on eri asiasta. 
#### Ehdottaja

Jaakko Tuohiniemi 
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto 
#### Ehdottajan sähköpostiosoite

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
On jo hyväksytty.
