### ISSUE TITLE
kauppakaupungit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4687]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

kauppakaupungit 
#### Ehdotettu yläkäsite YSOssa (LT)

[kaupungit](http://www.yso.fi/onto/yso/p1688) 
#### Perustelut ehdotukselle

Kuvailen Aleppon historiasta kertovaa tietokirjaa. Kauppakaupunki termiä käytetään etenkin keskiajalla. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Aleppo : the rise and fall of Syria's great merchant city. Philip Mansel 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi **Termiehdotus Fintossa:** [kauppakaupungit](http://finto.fi/yse/fi/page/Y504687)

**Comment by mirmaid** [comment]
YSAssa on _kaivoskaupungit_, _satamakaupungit_ ja _tapulikaupungit_. 

MAO-ontologiassa

**Comment by mirmaid** [comment]
Ei Melindassa

**Comment by LeKorsu** [comment]
Jos otetaan, tarvitseeko selitystä historiallisesta kontekstista?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
