### ISSUE TITLE
kalatiira

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4688]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

kalatiira 
#### Ehdotettu termi ruotsiksi

fisktärna 
#### Ehdotettu termi englanniksi

common tern 
#### Ehdotettu yläkäsite YSOssa (LT)

[tiirat](http://www.yso.fi/onto/yso/p13122) 
#### Vaihtoehtoiset termit ja ilmaisut

Sterna hirundo 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
#### Perustelut ehdotukselle

Käytetty ARTOssa 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

ARTOssa 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kalatiira](http://finto.fi/yse/fi/page/Y504688)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
