### ISSUE TITLE
lapintiira

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4689]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

lapintiira 
#### Ehdotettu termi ruotsiksi

silvertärna 
#### Ehdotettu termi englanniksi

arctic tern 
#### Ehdotettu yläkäsite YSOssa (LT)

[tiirat](http://www.yso.fi/onto/yso/p13122) 
#### Vaihtoehtoiset termit ja ilmaisut

Sterna paradisaea 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
#### Tarkoitusta täsmentävä selite

https://onki.fi/fi/browser/overview/avio#/www.yso.fi/onto/avio/e1943 
#### Perustelut ehdotukselle

ARTOssa 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

ARTO 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [lapintiira](http://finto.fi/yse/fi/page/Y504689)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
