### ISSUE TITLE
ruokki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4691]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

ruokki 
#### Ehdotettu termi ruotsiksi

tordmule 
#### Ehdotettu termi englanniksi

razorbill 
#### Ehdotettu yläkäsite YSOssa (LT)

[ruokit](http://www.yso.fi/onto/yso/p10853) 
#### Vaihtoehtoiset termit ja ilmaisut

Alca torda 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
#### Tarkoitusta täsmentävä selite

https://onki.fi/fi/browser/overview/avio#/www.yso.fi/onto/avio/e2009 
#### Perustelut ehdotukselle

ARTOssa 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

ARTO 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [ruokki](http://finto.fi/yse/fi/page/Y504691)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
