### ISSUE TITLE
hautausurakoitsija

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4693]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

hautausurakoitsija 
#### Ehdotettu yläkäsite YSOssa (LT)

[ammatit](http://www.yso.fi/onto/yso/p1179) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://www.worldcat.org/title/smoke-gets-in-your-eyes-and-other-lessons-from-the-crematorium/oclc/946987450&referer=brief_results 
#### Perustelut ehdotukselle

Kuvailen hautausurakoitsijan muistelmia. Ainaostaan ketjutus on mahdollinen  $ahautaus  tai $ahautauspalvelut $xyrittäjät 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto

**Comment by henriyli** [comment]
suljetaan tupla ja jätetään #4694
