### ISSUE TITLE
hautausurakoitsijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4694]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

hautausurakoitsijat 
#### Ehdotettu yläkäsite YSOssa (LT)

[ammatit](http://www.yso.fi/onto/yso/p1179) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://www.worldcat.org/title/smoke-gets-in-your-eyes-and-other-lessons-from-the-crematorium/oclc/946987450&referer=brief_results#relatedsubjects 
#### Perustelut ehdotukselle

Kuvailen hautausurakoitsijan muistelmia. Ainaostaan ketjutus on mahdollinen  $ahautaus  tai $ahautauspalvelut $xyrittäjät 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi **Termiehdotus Fintossa:** [hautausurakoitsijat](http://finto.fi/yse/fi/page/Y504694)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
