### ISSUE TITLE
parateksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4695]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

parateksti 
#### exactMatch

LCSH : Paratext 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 
#### Tarkoitusta täsmentävä selite

Tekstin ymmärtämistä säätelevä aputeksti eli kynnysteksti tai lieveteksti. 
#### Perustelut ehdotukselle

KITU-asiasanastosta löytyvä asiasana. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Gérard Genetten teos Paratexte 

**Ehdottajan nimi:** Katja Hyvärinen 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** katja.hyvarinen@uef.fi **Termiehdotus Fintossa:** [parateksti](http://finto.fi/yse/fi/page/Y504695)

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:parateksti
Definition: tekstin ymmärtämistä säätelevä aputeksti, kuten otsikko, väliotsikko, epigrafi, johdanto tai takakansiteksti
Explanation: Parateksti on teksti, joka toimii varsinaisen tekstin kynnyksenä ja ympäristönä. Käsitteen käyttöön ottanut Gérard Genette erottaa teoksessaan Seuils (1978, engl. Paratexts) kahdenlaisia paratekstejä:

1) peritekstit viittaavat tekstiä välittömästi ympäröivään tekstimateriaaliin (kirjailijan nimi, otsikko ja väliotsikot, omistuskirjoitus, epigrafi, esipuhe, huomautukset, takakansiteksti),
2) epiteksti tarkoittaa etäisempiä tekstejä (teokseen liittyvät haastattelut, kirjeet, päiväkirjamerkinnät, käsikirjoitukset, luonnokset, tekstistä esitetyt kommentit tai arvostelut tms.).

**Comment by mirmaid** [comment]
Käytetty Melindassa 10 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)

**Comment by OutiHintikka** [comment]
Ehdottomasti otettava.  Ja muoto parateksti. Tarkka kirj.tutkimuksen käsite.
