### ISSUE TITLE
SketchUp

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4696]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

SketchUp 
#### Ehdotettu yläkäsite YSOssa (LT)

[tietokoneohjelmat](http://www.yso.fi/onto/yso/p26592) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 
#### Perustelut ehdotukselle

Ohjelmien nimi on otettu YSAan 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Teos: SketchUp 2016 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [SketchUp](http://finto.fi/yse/fi/page/Y504696)

**Comment by mirmaid** [comment]
Hyväksytty 7.10.2016
