### ISSUE TITLE
kansanmusiikkisoittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4697]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[kansanmusiikkisoittimet](http://www.yso.fi/onto/ysa/Y98907) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Nykyinen KT-muoto "kansansoittimet" otetaan varsinaiseksi termiksi ja "kansanmusiikkisoittimet" vastaavasti muutetaan KT-muodoksi. 
#### Perustelut ehdotukselle

Termi "kansansoittimet" ilmaisee, että soitin on kansankulttuurin tuote, kun "kansanmusiikkisoittimet" vastaavasti ilmaisee, että soitinta käytetään kansanmusiikissa – olipa se kansansoitin tai ei. Koska kansanmusiikissa käytetään paljon soittimia, jotka eivät ole varsinaisia kansansoittimia, on nykyinen termi harhaanjohtava: nykyistäkin termiä käytettäessä tarkoitetaan useimmiten nimenomaan kansankulttuurin piiriin lukeutuvia soittimia. 
#### Ehdottaja

Jaakko Tuohiniemi 
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto 
#### Ehdottajan sähköpostiosoite

jaakko.tuohiniemi@helsinki.fi

**Comment by TommiViitamies** [comment]
Luumu-ryhmä ehdottaa: hyväksytään.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
