### ISSUE TITLE
musiikkiohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4698]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[musiikkiohjelmat](http://www.yso.fi/onto/ysa/Y97565) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Käsite jaetaan kahdeksi täsmällisemmäksi käsitteeksi: "musiikkiohjelmat (radio-ohjelmat)" ja "musiikkiohjelmat (televisio-ohjelmat)". 
#### Perustelut ehdotukselle

Nykyinen termi ei ota kantaa, onko kyse radio- vai televisio-ohjelmasta; vrt. Ysan termit "ruokaohjelmat (televisio-ohjelmat)" ja "vaaliohjelmat (televisio-ohjelmat)". Musa-asisanastossa nämä ovat eritelty ketjuissa, joita ollaan juuri purkamassa ja tässä olisi valmis vastine niille. 
#### Ehdottaja

Jaakko Tuohiniemi 
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto 
#### Ehdottajan sähköpostiosoite

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ko. tarkenteiden ei ole kuitenkaan tarkoitus erottaa näitä vastaavista radio-ohjelmista. Periaatteessa jonkinlaisia vaaliohjelmia varmaan on radiossakin, toinen vaaliohjelmat-termi viittaa siis puolueiden vaaliohjelmiin ja ruokaohjelma voisi olla myös avustusohjelma tai toisaalta ruokasuunnitelma esim. laihduttajalle tai treenaajalle. 

YSOssa itse ohjelmat-termi on jaettu, toisella sulkutarkenteena (radio- ja tv-ohjelmat).

**Comment by tpalonen** [comment]
YSOn puolella on käsittelyssä "ohjelmat (radio- ja tv-ohjelmat)"-käsitteen alakäsitteet. Käsittely on kesken, mutta tavoitteena on määrittää jonkinlainen linjaus näiden suhteen. Itse suosittaisin, että pidettäisiin genretyyppiset ja formaattityyppiset (tv/radio) käsitteet hierarkkisesti eri lokeroissa, koska samaa genreä voi tehdä useampaan formaattiin. En myöskään lähtisi jakamaan ohjelmagenrekäsitteitä jokaista formaattia kohden erikseen.
https://github.com/NatLibFi/Finto-data/issues/703

**Comment by LeKorsu** [comment]
En kannata välineen/jakelukanavan mukaista sulkutarkennetta, koska televisio- ja radio-ohjelmia esitetään jo nyt ja tulevaisuudessa entistä enemmän verkossa. Silloin varsinkin nuo erilliset sulkutarkenteet vanhenevat nopeasti.
Nyt jälkiviisaana - koska olin paikalla silloin kun päätös tehtiin - tulee mieleen, että tuo vaaliohjelmat (televisio-ohjelmat), tarkenne olisi varmaan kannattanut laittaa (radio- ja televisio-ohjelmat). Enpä vain älynnyt sitä silloin.

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 13.12.2016)
