### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4699]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

Instagram 
#### Ehdotettu termi ruotsiksi

Instagram 
#### Ehdotettu termi englanniksi

Instagram 
#### Ehdotettu yläkäsite YSOssa (LT)

[sosiaalinen media](http://www.yso.fi/onto/yso/p20774) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Jotain uutta, paljon perinteistä, vähän väriä : sosiaalisen median hyödyntäminen jääkiekon SM-liigasssa 
#### Perustelut ehdotukselle

käytetty Melindassa 13 kertaa 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi

**Comment by mirmaid** [comment]
On hyväksytty YSAan.
