### ISSUE TITLE
bookcrossing

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4700]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

bookcrossing 
#### Ehdotettu termi englanniksi

bookcrossing 
#### Tarkoitusta täsmentävä selite

Bookcrossing on kansainvälinen ”kirjojen vapautusliike”, jonka toiminta perustuu yhdysvaltalaiseen internetsivustoon Bookcrossing.com. Bookcrossingin taustalla on se havainto, että useimmat kirjat (varsinkin romaanit) tulevat luetuiksi vain kerran ja päätyvät lopulta kirjahyllyn täytteeksi tai jopa jätteenkeräykseen. Perusajatuksena on tällaisten kirjojen antaminen toisten, aivan tuntemattomienkin, ihmisten luettavaksi. Yksinkertaisimmillaan tämä tapahtuu ”vapauttamalla” kirja eli jättämällä se julkiselle paikalle kenen tahansa kiinnostuneen poimittavaksi.[1] Jos kirjan rekisteröi BookCrossing-sivustolla, sille saa oman kirjaan merkittävän tunnuskoodin (BCID-tunnus), ja juuri tämän kirjan kulkua maailmalla voi jatkossa halutessaan seurata koodin ja sivuston avulla. Sivuston käyttö on maksutonta ja anonyymiä. Kirjojen vapauttamisen lisäksi bookcrossingin yhteydessä harrastetaan nykyisin monenlaista kirjoihin ja lukemiseen liittyvää oheistoimintaa, ja kirjoja siirtyy bookcrossing-harrastajien (eli bookcrossaajien tai bookcrossareiden) kesken paljon myös suoraan kädestä käteen.
by Wikipedia 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

nuorten kaunokirjallisuus 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 
#### Perustelut ehdotukselle

Ei vastaavaa termiä 

**Ehdottajan nimi:** Kaija Karjalainen 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** kaija.karjalainen@btj.fi **Termiehdotus Fintossa:** [bookcrossing](http://finto.fi/yse/fi/page/Y504700)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mariaforsen** [comment]
Hyvä termi!

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
