### ISSUE TITLE
metsäneuvokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4701]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

metsäneuvokset 
#### Ehdotettu termi ruotsiksi

forstråd 
#### Ehdotettu yläkäsite YSOssa (LT)

[arvonimet](http://www.yso.fi/onto/yso/p305) 
#### exactMatch

wikipedia : https://fi.wikipedia.org/wiki/Mets%C3%A4neuvos 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 
#### Perustelut ehdotukselle

arvonimi 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Savottapolku : aikalaiskuvauksiin painottunut elämänpolku metsurista metsäneuvokseksi 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [metsäneuvokset](http://finto.fi/yse/fi/page/Y504701)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
