### ISSUE TITLE
etsivä vanhustyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4702]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

etsivä vanhustyö 
#### Ehdotettu termi ruotsiksi

uppsökande äldrearbete 
#### Ehdotettu yläkäsite YSOssa (LT)

[etsivä sosiaalityö](http://www.yso.fi/onto/yso/p16202) 
[vanhustyö](http://www.yso.fi/onto/yso/p6448) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Etsivä vanhustyö meillä ja muualla : raportti suomalaisista ja eurooppalaisista käytännöistä  http://www.valli.fi/fileadmin/user_upload/Etsivae_mieli/Etsiva_vanhustyo-raportti_2015.pdf 
#### Perustelut ehdotukselle

termille tarve aineiston kuvailussa 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [etsivä vanhustyö](http://finto.fi/yse/fi/page/Y504702)

**Comment by mirmaid** [comment]
YSAssa on _etsivä sosiaalityö_ ja _etsivä nuorisotyö_.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
