### ISSUE TITLE
altmetriikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4703]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

altmetriikka 
#### Ehdotettu termi englanniksi

altmetrics 
#### Ehdotettu termi ruotsiksi

altmetri 
#### Tarkoitusta täsmentävä selite

Altmetriikka on (biblio)metriikan uusi suuntaus, joka muodostuu sanoista alternative (biblio)metrics. Menetelmä täydentää perinteistä metriikkaa tarkastelemalla julkaisujen saamaa huomiota etenkin sosiaalisessa mediassa. 
#### Perustelut ehdotukselle

Altmetriikasta on jo julkaistu paljon, ja aihepiirinä sen suosio on kasvussa. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Käsikirjoituksen "Tutkijan motivoinnista avoimen tieteen käytäntöihin altmetriikan avulla" asiasanaksi (- tulossa Informaatiotutkimus-lehteen 3/2016). Julkaisuista ks. esim. Holmberg, K. (2015). Altmetrics for Information Professionals – Past, Present and Future. Chandos Publishing. 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

**Ehdottajan nimi:** Susanna Nykyri 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto, Tutkimuksen palvelut 
**Ehdottajan sähköpostiosoite:** susanna.nykyri@helsinki.fi **Termiehdotus Fintossa:** [altmetriikka](http://finto.fi/yse/fi/page/Y504703)

**Comment by mirmaid** [comment]
Kerran Melindassa. 

https://en.wikipedia.org/wiki/Altmetrics
http://libguides.oulu.fi/julkaisujenarviointi/altmetriikka
http://blogs.helsinki.fi/librarynews/2015/11/24/altmetriikka-digitaaliset-jalanjaljet-kertovat-dataan-pohjautuvia-tarinoita/

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
