### ISSUE TITLE
asiakkuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4705]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[asiakkuus](http://www.yso.fi/onto/ysa/Y113341) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

YSO-kokouksessa on keskusteltu mahdollisuudesta yhdistää käsitteet asiakassuhde ja asiakkuus. 
#### Perustelut ehdotukselle

Nämä ovat merkitykseltään varsin lähellä toisiaan. Voidaanko ajatella, että jokin kirja käsittelee vain asiakassuhdetta mutta ei asiakkuutta? Englanniksi ja ruotsiksi käännettäessä ilmenee myös ongelmia, koska näillä kielillä käsite-ero on vaikea hahmottaa ja sitä kautta tarkkoja termivastineita vaikea ellei mahdoton löytää. Ovat Melindassa sangen suosittuja käsitteitä ja esiintyvät myös perin useasti yhdessä. 
#### Ehdottaja

Tuomas Palonen 
#### Ehdottajan organisaatio

Kansalliskirjasto 
#### Ehdottajan sähköpostiosoite

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Niissä Melindan viitteissä joissa on _asiakkuus_ muttei _asiakassuhdetta_, on paljon sosiaalityötä käsittelevää aineistoa. Erityisesti lastensuojelun tms. yhteydessä asiakassuhde-termi tuntuu sopivan vähän huonommin. Esim. _Kuullaan, mutta kuunnellaanko? : huostaan otetun ja sijoitetun lapsen kokemuksia osallisuudesta lastensuojelun asiakkuudessaan_ (asiakassuhde sopii paremmin vapaaehtoisempaan asiakkuuteen).

**Comment by mariaforsen** [comment]
Asiakkuus voisi mahdollisesti olla "klientskap" (tämä käytetty Suomessa jonkin verran ja löytyy vastineena TEPAssakin).

**Comment by satuniininen** [comment]
Jos yhdistetään, niin kannatan muotoa asiakkuus KT asiakasuhde.

**Comment by mariaforsen** [comment]
Ruotsiksi on kyllä hankala käyttää kundrelation, jos on kysymys sosiaalihuollosta, silloin mieluummin esim. klientskap, mutta jos on kysymys siitä että on asiakas joka ostaa tavaroita tms. niin klientskap taas ei käy. Ruotsin osalta on ongelman ydin ruotsin kielen jako kund/klient.

**Comment by YSA-kokous** [comment]
Voidaanko yhdistää ruotsiksi, vrt. myös muut asiakas-termit?

**Comment by mariaforsen** [comment]
Eli mikä on viimeisin ehdotus?

**Comment by mirmaid** [comment]
YSOssa on nyt asiakkaat = kunder, korvattuna klienter. Eli varmaankin joko niin että yhdistetään samoin asiakkuus-termin osalta, tai jos tämä malli on täysin toimimaton ruotsiksi, pitää joko tehdä ruotsiksi yhdistelmätermi (kunder och klienter) tai yrittää keksiä suomeksi suppeampia termejä (on kyllä hyvin vaikea sanoa mitä ne voisivat olla).

**Comment by mariaforsen** [comment]
Allärs-päätös: asiakkaat=kunder ET klienter, eli tähän voidaan samalla tavalla laittaa kundrelation ET klientrelation, jos suomeksi yhdistätte asiakkuus KT asiakassuhde

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet. Käytettäväksi termiksi asiakkuus, ohjaustermiksi asiakassuhde.
