### ISSUE TITLE
Puola-Liettua

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4706]
#### Käsitteen tyyppi

GEO 
#### Ehdotettu termi suomeksi

Puola-Liettua 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
#### Perustelut ehdotukselle

https://fi.wikipedia.org/wiki/Puola-Liettua 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Ijäs, Miia: Varjoista valtaistuimelle 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [Puola-Liettua](http://finto.fi/yse/fi/page/Y504706)

**Comment by mirmaid** [comment]
Hyväksytty.
