### ISSUE TITLE
lääkeresistenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4707]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[lääkeresistenssi](http://www.yso.fi/onto/ysa/Y182290) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Termin "antibioottiresistenssi" (ei YSAssa) voisi laittaa ohjaamaan tähän. Vaihtoehtoisesti "antibioottiresistenssi" voisi olla erillinen termi "lääkeresistenssi"-termin alaterminä. 
#### Perustelut ehdotukselle

Antibioottiresistenssi on hyvin yleisesti käytetty käsite/termi, joten sen olisi hyvä näkyä jollain tavalla YSAssa. 
#### Ehdottaja

Matti Rajahonka 
#### Ehdottajan organisaatio

Jyväskylän yliopiston kirjasto 
#### Ehdottajan sähköpostiosoite

matti-petteri.rajahonka@jyu.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa 4 kertaa. MeSHissä ja TERO-ontologiassa on mikrobilääkeresistenssi, jota ei ole käytetty Melindassa. Google ~6600/3500.

**Comment by mariaforsen** [comment]
"Antibiotikaresistens" hyvin paljon käytetty ja on myös SAOssa, eli ruotsin osalta olisi ok lisätä jopa erillisenä terminä.

**Comment by PaiviLipsanen** [comment]
THL:n sivuilta löytyy viitteitä lääkeresistenssistä esim. masennuslääkkeiden ja punkkilääkkeiden yhteydessä, mutta enimmäkseen oli kyse mikrobilääkkeistä, myös virustaudeista (HIV). Kannatan myös antibioottiresistenssin ottamista YSAan.

**Comment by mirmaid** [comment]
Hyväksytty erillisenä (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
antibiotikaresistens /sao
