### ISSUE TITLE
horisontaalinen geeninsiirto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4708]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

horisontaalinen geeninsiirto 
#### Ehdotettu termi ruotsiksi

horisontell genöverföring 
#### Ehdotettu termi englanniksi

horizontal gene transfer 
#### Assosiatiiviset (RT)

[geenit](http://www.yso.fi/onto/yso/p147) 
[DNA](http://www.yso.fi/onto/yso/p7690) 
[plasmidit](http://www.yso.fi/onto/yso/p27720) 
[bakteriofagit](http://www.yso.fi/onto/yso/p25303) 
#### exactMatch

Horisontaalinen geeninsiirto : https://fi.wikipedia.org/wiki/Horisontaalinen_geeninsiirto 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

http://urn.fi/URN:ISBN:978-951-39-6766-6 
#### Perustelut ehdotukselle

"geeninsiirto" löytyy YSAsta termiin "geenitekniikka" ohjaavana. Vastaavankaltaista prosessia tapahtuu kuitenkin myös luonnossa, ja sillä on tärkeä osa yksisoluisten evoluutiossa. Jos "horisontaalinen geeninsiirto" lisätään omana terminään, pitäiskö tuo ohjaava "geeninsiirto" nimetä uudelleen, esim "geeninsiirtotekniikka"... 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto **Termiehdotus Fintossa:** [horisontaalinen geeninsiirto](http://finto.fi/yse/fi/page/Y504708)

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
LCSH:ssa on Genetic transformation.
https://en.wikipedia.org/wiki/Transformation_(genetics)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
horisontell genöverföring
