### ISSUE TITLE
fagiterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4710]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

fagiterapia 
#### Ehdotettu termi ruotsiksi

bakteriofagterapi 
#### Ehdotettu termi englanniksi

phage therapy 
#### Ehdotettu yläkäsite YSOssa (LT)

[hoitomenetelmät](http://www.yso.fi/onto/yso/p392) 
#### Assosiatiiviset (ST)

[bakteriofagit](http://www.yso.fi/onto/yso/p25303) 
[viroterapia](http://www.yso.fi/onto/yso/p21936) 
#### exactMatch

Wikipedia : https://en.wikipedia.org/wiki/Phage_therapy 
#### Vaihtoehtoiset termit ja ilmaisut

faagiterapia 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
#### Tarkoitusta täsmentävä selite

Bakteriofagien (bakteeria isäntänään käyttävien virusten) käyttö bakteeritautien hoidossa. 
#### Perustelut ehdotukselle

Ei vielä laajasti käytössä oleva hoitomuoto, mutta kansainvälinen tutkimus aiheesta on lisääntynyt viime vuosina. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

http://urn.fi/URN:ISBN:978-951-39-6766-6 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi **Termiehdotus Fintossa:** [fagiterapia](http://finto.fi/yse/fi/page/Y504710)

**Comment by mirmaid** [comment]
Myös muodossa bakteriofagihoito. Eniten hittejä termimuodolla _faagiterapia_.

[Bakteriofagihoidon mahdollisuudet](http://www.duodecimlehti.fi/web/guest/uusinnumero;jsessionid=A8E50001CC549DF086E8341E950F3379?p_p_id=Article_WAR_DL6_Articleportlet&_Article_WAR_DL6_Articleportlet_viewType=viewArticle&_Article_WAR_DL6_Articleportlet_tunnus=duo13080&_Article_WAR_DL6_Articleportlet_member=JPPpRX9**SdU)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
