### ISSUE TITLE
räystäspääsky

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4711]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

räystäspääsky 
#### Ehdotettu termi englanniksi

Northern House Martin 
#### Ehdotettu yläkäsite YSOssa (LT)

[pääskyt](http://www.yso.fi/onto/yso/p20062) 
#### Vaihtoehtoiset termit ja ilmaisut

Delichon urbicum 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

ARTOssa 
#### Perustelut ehdotukselle

Yleinen lintulaji Suomessa, YSAssa on haarapääsky 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [räystäspääsky](http://finto.fi/yse/fi/page/Y504711)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
