### ISSUE TITLE
ruskosuohaukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4712]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

ruskosuohaukka 
#### Ehdotettu termi englanniksi

Western Marsh Harrier 
#### Ehdotettu yläkäsite YSOssa (LT)

[haukat](http://www.yso.fi/onto/yso/p5791) 
#### exactMatch

LCSH : Marsh harrier 
#### Vaihtoehtoiset termit ja ilmaisut

Circus aeruginosus 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
#### Perustelut ehdotukselle

Suomessa pesivä laji 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

ARTOssa 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [ruskosuohaukka](http://finto.fi/yse/fi/page/Y504712)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
