### ISSUE TITLE
älykkäät sähköverkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4713]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

älykkäät sähköverkot 
#### Ehdotettu termi ruotsiksi

smarta elnät 
#### Ehdotettu termi englanniksi

Smart power grids 
#### Ehdotettu yläkäsite YSOssa (LT)

[sähköverkot](http://www.yso.fi/onto/yso/p7753) 
#### exactMatch

LCSH : Smart power grids (sh2011003732) 
#### Perustelut ehdotukselle

On tullut vastaan viimeaikoina uusissa kirjoissa. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

978-1-63081-046-7 ja 978-1-60807-963-6 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536) 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulu 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [älykkäät sähköverkot](http://finto.fi/yse/fi/page/Y504713)

**Comment by mirmaid** [comment]
Käytetty Melindassa 4 kertaa.

https://fi.wikipedia.org/wiki/%C3%84lyk%C3%A4s_s%C3%A4hk%C3%B6verkko

**Comment by Elmukelmu** [comment]
Lehtiartikkeleita tästä ilmestyy tasaseen tahtiin. Useimmiten muodossa smart grid. Kyllähän sitä pärjäilee asiasanoilla älytekniikka, älytuotteet.. mutta en pistä hanttiin jos otamme älykkäät sähköverkot.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
