### ISSUE TITLE
musiikinjohtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4714]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

musiikinjohtaminen 
#### Ehdotettu termi englanniksi

conducting 
#### Ehdotettu termi ruotsiksi

dirigering 
#### Alakäsitteet (RT)

[kuoronjohtaminen](http://www.yso.fi/onto/yso/p16775) 
[orkesterinjohtaminen](http://www.yso.fi/onto/yso/p2198) 
#### exactMatch

LCSH : http://id.loc.gov/authorities/subjects/sh85030804 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
#### Tarkoitusta täsmentävä selite

Musiikin johtaminen yleensä, sisältäen yhtyeenjohtamisen, lauluyhtyeenjohtamisen jne. 
#### Perustelut ehdotukselle

Nykyinen ohjaus yksinomaan kuoronjohtamiseen ja orkesterinjohtamiseen on harhaanjohtava, koska musiikinjohtaminen voi olla pienempienkin kokoonpanojen johtamista; ehdotusta on päätetty pyytää Musa–Ysa-yhteensovittamistyöryhmässä (14.10.2016 Kansalliskirjastossa pidetty kokous) 
#### Vaihtoehtoiset termit ja ilmaisut

musiikin johtaminen 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Jazzia johtamiseen : anna osaajien loistaa / Patrick Furu. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [musiikinjohtaminen](http://finto.fi/yse/fi/page/Y504714)

**Comment by TommiViitamies** [comment]
Luumu-ryhmä ehdottaa: hyväksytään. Vaikkakin: esimerkkiaineisto, jonka kuvailussa käsitettä väitetään tarvittavaksi, ei taida olla osuva (Jazzia johtamiseen : anna osaajien loistaa / Patrick Furu).

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)

**Comment by mirmaid** [comment]
RT kapellimestarit, kuoronjohtajat.
