### ISSUE TITLE
Tšernobylin ydinonnettomuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4715]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

Tšernobylin ydinonnettomuus 
#### Ehdotettu termi ruotsiksi

Tjernobylolyckan 1986 (sao) 
#### Ehdotettu yläkäsite YSOssa (LT)

[ydinonnettomuudet](http://www.yso.fi/onto/yso/p28784) 
#### exactMatch

LCSH : https://lccn.loc.gov/sh87003900 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://helka.linneanet.fi/cgi-bin/Pwebrecon.cgi?BBID=811208 
#### Perustelut ehdotukselle

Nyt asian joututuu ilmaisemaan epätäsmällisesti ja osin harhaanjohtavasti:
Radioactivity of vegetables and mushrooms in Finland after the Chernobyl accident in 1986 / Aino Rantavaara.
NYT:
Asiasana: 
    ydinonnettomuudet (ysa)
    sienet (ysa)
    vihannekset (ysa)
    radioaktiivisuus (ysa)
Maantieteellinen asiasana: 
    Suomi
    Tšernobyl

MUUTOKSEN JÄLKEEN
Asiasana: 
    Tšernobylin ydinonnettomuus (ysa)
    sienet (ysa)
    vihannekset (ysa)
    radioaktiivisuus (ysa)
Maantieteellinen asiasana: 
    Suomi 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[19 Energia. Polttoaineet](http://www.yso.fi/onto/yso/p26566) 
[49 Palotoimi. Pelastustoimi. Tapaturmantorjunta. Turvallisuustekniikka](http://www.yso.fi/onto/yso/p26548) 
#### Tarkoitusta täsmentävä selite

Tšernobylin ydinvoimalalaitoksen onnettomuus tapahtui 26.4.1986 Ukrainassa (silloinen Ukrainan sosialistinen neuvostotasavalta). 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Tšernobylin ydinonnettomuus](http://finto.fi/yse/fi/page/Y504715)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
