### ISSUE TITLE
Three Mile Islandin ydinonnettomuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4716]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

Three Mile Islandin ydinonnettomuus 
#### Ehdotettu yläkäsite YSOssa (LT)

[ydinonnettomuudet](http://www.yso.fi/onto/yso/p28784) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[19 Energia. Polttoaineet](http://www.yso.fi/onto/yso/p26566) 
[49 Palotoimi. Pelastustoimi. Tapaturmantorjunta. Turvallisuustekniikka](http://www.yso.fi/onto/yso/p26548) 
#### Tarkoitusta täsmentävä selite

Three Mile Islandin ydinvoimalalaitoksen onnettomuus tapahtui 28.3.1979 Pennsylvaniassa Yhdysvalloissa.

KORVATTU TERMI: Harrisburgin ydinonnettomuus 
#### Perustelut ehdotukselle

Katso käsite-ehdotus Tšernobylin ydinonnettomuus
https://github.com/Finto-ehdotus/YSE/issues/4715 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://helka.linneanet.fi/cgi-bin/Pwebrecon.cgi?BBID=712083 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Three Mile Islandin ydinonnettomuus](http://finto.fi/yse/fi/page/Y504716)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
