### ISSUE TITLE
Fukushiman ydinonnettomuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4717]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

Fukushiman ydinonnettomuus 
#### Ehdotettu termi ruotsiksi

Fukushimaolyckan 2011 (sao) 
#### Ehdotettu yläkäsite YSOssa (LT)

[ydinonnettomuudet](http://www.yso.fi/onto/yso/p28784) 
#### exactMatch

LCSH : https://lccn.loc.gov/sh2011003738 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[19 Energia. Polttoaineet](http://www.yso.fi/onto/yso/p26566) 
[49 Palotoimi. Pelastustoimi. Tapaturmantorjunta. Turvallisuustekniikka](http://www.yso.fi/onto/yso/p26548) 
#### Tarkoitusta täsmentävä selite

Fukushiman ydinonnettomuus tapahtui Japanissa Fukushima Dai-ichin ydinvoimalaitoksessa. Onnettomuus sai alkunsa 11.3.2011 tapahtuneesta maanjäristyksestä ja sitä seuranneesta tsunamista. 
#### Perustelut ehdotukselle

Katso käsite-ehdotus Tšernobylin ydinonnettomuus
https://github.com/Finto-ehdotus/YSE/issues/4715 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://helka.linneanet.fi/cgi-bin/Pwebrecon.cgi?BBID=2271730 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Fukushiman ydinonnettomuus](http://finto.fi/yse/fi/page/Y504717)

**Comment by LeKorsu** [comment]
Mediayhtiössä työskentelevänä kannatan auktorisoituja muotoja erilaisille suuren luokan katastrofeille ja onnettomuuksille.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
