### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4720]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

OS X 
#### Ehdotettu termi ruotsiksi

OS X 
#### Ehdotettu termi englanniksi

Mac OS 
#### Ehdotettu yläkäsite YSOssa (LT)

[käyttöjärjestelmät](http://www.yso.fi/onto/yso/p724) 
#### exactMatch

LCSH : Mac OS (https://lccn.loc.gov/n96060065) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 
#### Perustelut ehdotukselle

Asiasanastossa on muitakin käyttöjärjestelmien nimiä. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Shell programming in Unix, Linux and OS 2 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulu 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi 
**Termiehdotus Fintossa:** [OS X](http://finto.fi/yse/fi/page/Y504720)

**Comment by henriyli** [comment]
YSAssa on nyt termi Mac OS X jona kyseinen käyttöjärjestelmä tunnettiin aina vuoteen 2012 asti. Tämän jälkeen nimi muuttui muotoon OS X ja nyt 2016 nimi on muuttunut jälleen, tällä kertaa muotoon MacOS. Lähde: https://en.wikipedia.org/wiki/MacOS

**Comment by mirmaid** [comment]
Onko näillä edeltäjä-seuraaja -suhde vai ovatko kuitenkin sama käsite, jonka nimi on muuttunut?

LCSH:ssa Mac OS X versionimiä on ohjaustermeinä. 

YSAssa Windowsista on auktorisoitu versioita, muista käyttöjärjestelmistä ei.

**Comment by henriyli** [comment]
Tulkitsisin että tässä on kyseessä sama käsite, jonka nimi on muuttunut.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
