### ISSUE TITLE
balkanilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4723]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

balkanilaiset 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
#### Perustelut ehdotukselle
- 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)
- 

**Ehdottajan nimi:** KK 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi 
**Termiehdotus Fintossa:** [balkanilaiset](http://finto.fi/yse/fi/page/Y504723)

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 14.9.2016)

**Comment by mirmaid** [comment]
_Eteläslaavit_, 16 viitettä Melindassa. https://fi.wikipedia.org/wiki/Etel%C3%A4slaavit
YSAssa on _eteläslaavilaiset kielet_.

**Comment by mirmaid** [comment]
_Balkanilaisiin kuuluu muitakin kuin etelä-slaaveja, mm. romaneja, unkarilaisia, romanialaisia, albaaneja, kreikkalaisia jne. Näiden kansojen sekoituksena on syntynyt käsite balkanilainen kulttuuri, jota ainakin minun käsittelemässäni aineistossa paljon käytetään. Monissa eurooppalaisissa maissa käsite on myös tunnettu.
Kuinka kuvaillaan sitten balkanilaista musiikkia tai balkanilaista identiteettiä?_

**Comment by mirmaid** [comment]
9780804784023
After Yugoslavia : the cultural spaces of a vanished land

9781443836524
The Balkans and Caucasus : parallel processes on the opposite sides of the Black Sea

9789540732671
The dialogue with the other : Balkan dimensions of European identity

LC käyttää näitä usein:

Balkans
South Balkans
Western Balkans

Balkans Bibliographie
National characteristics, Balkan ‡x Psychological aspects.

**Comment by mariaforsen** [comment]
Sv. balkaner

**Comment by LeKorsu** [comment]
Balkanilaiset kuulostaa paremmalta kuin Balkanin niemimaan asukkaat =)
