### ISSUE TITLE
uskonpuhdistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4727]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[uskonpuhdistus](http://www.yso.fi/onto/ysa/Y99927) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Reformaatio on ysa:ssa korvattu termi. Reformaation sijasta tulisi käyttää uskonpuhdistus-termiä. Voitaisiinko reformaatio sallia varsinaisena asiasanana ja uskonpuhdistus muuttaa ohjaustermiksi. 
#### Perustelut ehdotukselle

Reformaatio on tutkimuksen käyttämä käsite:
Ks. esim Pohjoinen reformaatio / toimittaneet Meri Heinonen ja Marika Räsänen (2016)
Kirkko käyttää käsitettä
http://www.reformaatio2017.fi/tietoa-juhlavuodesta/
Melindassa reformaatiota on käytetty sekä kontroilloimattomana hakuterminä, että virheellisesti ysa-terminä.
Uskonpuhdistus-käsite on käytössä koulukirjoissa 
#### Ehdottaja

Hannele Dahl 
#### Ehdottajan organisaatio

Museoviraston kirjasto 
#### Ehdottajan sähköpostiosoite

hannele.dahl@nba.fi

**Comment by mirmaid** [comment]
http://www.kielikello.fi/index.php?mid=2&pid=11&aid=2705

https://peda.net/forssa/forssan-yhteislyseo/oppiaineet/historia/isotalo/historia-2/epookki-2-kurssipohja/uusi-aika/reformaatio

Teologian asiasanastossa kuten YSAssa
http://evl.fi/sanasto/-/glossary/word/Uskonpuhdistus
https://fi.wikipedia.org/wiki/Uskonpuhdistus

Reformaatio Melindassa 2 kertaa, kerran ysa-sanana.

**Comment by MikkoAleksanteri** [comment]
Muutosesitys on perusteltu. Haasteena ehkä kuitenkin Kielikellon artikkelissa mainittu seikka: 

> Vierassanaan verrattuna uskonpuhdistuksella on sekin etu, että se viittaa yksiselitteisesti 1500-luvun kirkolliseen uudistukseen. Reformaatio voi sen sijaan tarkoittaa mitä tahansa uudistamista

Eli jos käsitteen prefLabel muutetaan, olisi hyvä lisätä selite tai sulkutarkenne.

**Comment by AuHo22** [comment]
Reformaatio (uskonto)? Paljon on juhlavuoden 2017 kirjoja mennyt käsien läpi jo, ja ekumeeninen hyvä tahto tuntuu vahvasti suosittelevan reformaatio-sanan käyttöä.

**Comment by mariaforsen** [comment]
Tosiaan hyvä jos osoitetaan että kyseessä on edelleen yksi ja sama "uskonpuhdistus", eikä mikä tahansa.. Allärs: reformationen, eli nimenomaan 1500-luvulla tapahtunut reformaatio.

**Comment by mirmaid** [comment]
Seuraava kokous. Huom. myös vastauskonpuhdistus.

**Comment by MikkoAleksanteri** [comment]
"Kirkkohallitus lepyttelee katolilaisia – uskonpuhdistuksesta puhuminen lopetetaan, tilalle reformaatio
Uskonpuhdistus-termin vaihtaminen reformaatioon kertoo satoja vuosia vanhoista haavoista luterilaisen ja katolisen kirkon välillä." http://www.hs.fi/kotimaa/art-2000002836415.html

http://www.ts.fi/uutiset/kotimaa/790359/Termi+uskonpuhdistus+pannaan++katolista+kirkkoa+ei+haluta+loukata

Reformaatio siis virallinen nimi myös (luterilaisen) kirkon piirissä.

**Comment by mirmaid** [comment]
Tämä jäi viimeksi vielä pöydälle koska huomattiin tarve tehdä muutos vastaavasti myös _vastauskonpuhdistus_-termille.

**Comment by YSA-kokous** [comment]
reformaatio ilman tarkennetta + huomautus

**Comment by mirmaid** [comment]
Muutetaanko myös vastauskonpuhdistus-termi? Katolinen reformaatio tai katolinen reaktio hyvin vähän käytettyjä verrattuna vastauskonpuhdistus-sanaan.

> jätetään ennalleen
