### ISSUE TITLE
keräys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4735]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[keräys](http://www.yso.fi/onto/ysa/Y107280) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Ehdotan sanastoon termiä keruu. Sanasto ohjaa nyt käyttämään keruu -> keräys, Luonnontuotteiden keruusta puhuttaessa olisi luontevaa sisällönkuvailla aineistoja: Luonnontuotteet – keruu. Kielitoimistokin tekee eron näiden kahden termin välillä: keräys: kerääminen, vars. järjestetty hyväntekeväisyys- tms. keruu. Rahan-, jätepaperinkeräys. Kansalaiskeräys. Järjestää keräys jnk hyväksi. keruu: kerääminen. Marjojen keruu. Tutkimusainesten keruu. Tilastokeskuksen toimialaluokitus: 02300 Luonnon tuotteiden keruu (pl. polttopuu) Tähän kuuluu: metsässä kasvavien luonnontuotteiden keruu. 
#### Perustelut ehdotukselle
- 
#### Ehdottaja
- 
#### Ehdottajan sähköpostiosoite

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa lähinnä kansanperinteen keruusta (on KULAssa, mutta käytetty myös YSA-sanana ja vapaana asiasanana). Perinteenkeruu on YSAssa erikseen, muissa yhteyksissä kuulostaa ehkä vähän vieraalta?

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 14.9.2016)
