### ISSUE TITLE
monipaikkaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4744]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

monipaikkaisuus 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 
#### Perustelut ehdotukselle
- 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)
- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi 
**Termiehdotus Fintossa:** [monipaikkaisuus](http://finto.fi/yse/fi/page/Y504744)

**Comment by mirmaid** [comment]
Suomessa monipaikkaisuutta on tarkasteltu muun muassa Itä-Suomen yliopiston matkailualan opetus- ja tutkimuslaitoksessa. Liikkumisen maantiedettä mobiilissa yhteiskunnassa -tutkimushankkeessa käsitteillä “paikkojen ja liikkuvuuden jatkumo” sekä “monipaikkaisuus” viitataan ihmisten jokapäiväisiä elinympäristöjä yhä useammin leimaavaan, monien merkityksellisten paikkojen ja niiden välillä tapahtuvan liikkumisen kokonaisuuteen."

**Comment by mirmaid** [comment]
Tutkimuksissa monipaikkaisuuden osiksi on tunnistettu monipaikkainen työ, monipaikkainen asuminen, monipaikkainen vapaa-aika ja sosiaaliset suhteet sekä liikkuminen eri paikkojen välillä (”time in between”)

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 14.9.2016)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tätä: https://www.sitra.fi/julkaisut/monipaikkaisuus/

**Comment by mariaforsen** [comment]
Sv. multilokalitet? käytetty joillakin suomalaisilla sivuilla

**Comment by satuniininen** [comment]
Sitran mukaan englanniksi multi-locality

**Comment by YSA-kokous** [comment]
Myös _monipaikkainen identiteetti_

**Comment by PaiviLipsanen** [comment]
Monipaikkaisuus maaseudun terveyspalveluiden mahdollistajana 
Maaseudun uusi aika 2019: 2 (Arto-lehti)
http://www.mua-lehti.fi/monipaikkaisuus-maaseudun-terveyspalveluiden-mahdollistajana/
"Yksinkertaisimmillaan monipaikkaisuus tarkoittaa, että ihmisillä on useampi kuin yksi oleskelu- tai asuinpaikka."

**Comment by HeidiRonkainen** [comment]
Tarttisin julkaisuun https://urn.fi/URN:ISBN:978-952-11-5681-6

**Comment by mariaforsen** [comment]
Sv. multilokalitet 
https://www.oph.fi/sv/utbildning-och-examina/forskningsoversikt-digital-litteracitet-och-barn
https://tem.fi/sv/-/nordiska-ministerradets-regionministrar-multilokalitet-skapar-ny-livskraft-i-regionerna
https://www.kommunforbundet.fi/aktuellt/2022/multilokalitet-har-positiva-effekter-pa-kommunekonomin-och-invanargemenskapen
https://vm.fi/sv/multilokalt-arbete-inom-staten

**Comment by ilona-x** [comment]
JUHO: monipaikkaisuus http://www.yso.fi/onto/juho/p14246

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
