### ISSUE TITLE
heitto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4764]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

heitto 
#### Vaihtoehtoiset termit ja ilmaisut

heittäminen 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 
#### Perustelut ehdotukselle

Heittäminen on peruskäsite, joka kuuluu perusliikuntataitoihin. Vaihtoehtoisesti päätermi voisi olla heittäminen ja vaihtoehtoinen termi heitto, mutta näin, jos verrataan sanoja juoksu, juokseminen. Toisaalta taas sanaa hyppy ei ole YSA:ssa, on vain hyppääminen, eikö tämä pitäisi muuttaa yhdenmukaisuuden vuoksi muotoon hyppy? 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://kirjasto.jyu.fi/kauppa/tuotteet/juokse-hyppaa-heita-ota-kiinni 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [heitto](http://finto.fi/yse/fi/page/Y504764)

**Comment by mirmaid** [comment]
Melindassa 2 kertaa muodossa _heittäminen_. 

Liikunnan ja urheilun asiasanastossa on _heittäminen_, _hyppääminen_ ja _juoksu_.

YSAssa on heittolajit

**Comment by LeKorsu** [comment]
Olisiko paras tapa käyttää liikunnan ja urheilun asiasanaston muotoja?

**Comment by mirmaid** [comment]
Hyväksytty muodossa heittäminen (YSA-kokous 13.12.2016)
