### ISSUE TITLE
musikaalielokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4765]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

musikaalielokuvat 
#### Ehdotettu termi englanniksi

musical films 
#### Ehdotettu termi ruotsiksi

musikalfilmer 
#### Ehdotettu yläkäsite YSOssa (LT)

[elokuvat (teokset)](http://www.yso.fi/onto/yso/p1235) 
[musikaalit](http://www.yso.fi/onto/yso/p11693) 
#### exactMatch

LCSH : Musical films 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 
#### Tarkoitusta täsmentävä selite

Elokuva, jonka tarinankerronta perustuu elokuvan hahmojen laulamiin lauluihin. 
#### Vaihtoehtoiset termit ja ilmaisut

elokuvamusikaalit 
#### Perustelut ehdotukselle

Nykyiset termit "elokuvat" ja "musikaalit" eivät irrallisina asianoina käytettyinä ole tuota yhtä täsmällisen haun mahdollisuutta kuin ehdotettu uusi termi. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Musicals : Hollywood and beyond / edited by Bill Marshall and Robynn Stilwell 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [musikaalielokuvat](http://finto.fi/yse/fi/page/Y504765)

**Comment by TommiViitamies** [comment]
Luumu-ryhmä ehdottaa: hyväksytään.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
