### ISSUE TITLE
sukulaisvalinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4767]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

sukulaisvalinta 
#### Ehdotettu termi ruotsiksi

släktskapsselektion 
#### Ehdotettu termi englanniksi

kin selection 
#### Ehdotettu yläkäsite YSOssa (LT)

[luonnonvalinta](http://www.yso.fi/onto/yso/p4473) 
#### Assosiatiiviset (ST)

[altruismi](http://www.yso.fi/onto/yso/p5130) 
[sukulaisuus](http://www.yso.fi/onto/yso/p406) 
#### exactMatch

Wikipedia : https://fi.wikipedia.org/wiki/Sukulaisvalinta 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
#### Tarkoitusta täsmentävä selite

Luonnonvalinnan tyyppi. Sukulaisvalinnassa yksilö voi toimia omien etujen vastaisesti / altruistisesti, jos se hyödyttää (geneettisiä) sukulaisia. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

http://urn.fi/URN:ISBN:978-951-39-6724-6 
#### Perustelut ehdotukselle

On laajasti tutkittu aihe ja käsite on myös vakiintunut. 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi **Termiehdotus Fintossa:** [sukulaisvalinta](http://finto.fi/yse/fi/page/Y504767)

**Comment by mirmaid** [comment]
Käytetty Melindassa 3 kertaa. 

LCSH: Kin selection (Evolution)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
