### ISSUE TITLE
puuastiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4768]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

puuastiat 
#### Ehdotettu yläkäsite YSOssa (LT)

[taloustarvikkeet](http://www.yso.fi/onto/yso/p10206) 
[astiat](http://www.yso.fi/onto/yso/p6290) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 
#### Perustelut ehdotukselle

Saviastiat-asiasana on jo olemassa, tämä olisi siihen verrattavissa. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Jussila, Matti: Vakka Suomessa 

**Ehdottajan nimi:** Mari Ahlstén-Jussila 
**Ehdottajan organisaatio:** Turun kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** mari.ahlsten-jussila@turku.fi **Termiehdotus Fintossa:** [puuastiat](http://finto.fi/yse/fi/page/Y504768)

**Comment by mirmaid** [comment]
Käytetty Melindassa 4 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
