### ISSUE TITLE
sukupuolivalinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4769]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[sukupuolivalinta](http://www.yso.fi/onto/ysa/Y112434) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Sukupuolivalinta käsitteen luonnonvalinta alakäsitteeksi. Tällä hetkellä sen yläkäsite on valinta. 
#### Ehdottaja

Matti Rajahonka 
#### Ehdottajan organisaatio

Jyväskylän yliopiston kirjasto 
#### Perustelut ehdotukselle

Esim. Wikipediassa: https://fi.wikipedia.org/wiki/Seksuaalivalinta "Seksuaalivalinta eli sukupuolivalinta on eräs evoluution luonnonvalinnan mekanismeista." Jos ehdottamani sukulaisvalinta hyväksytään, niin luonnonvalinnalla olisi kaksi alakäsitettä. 
#### Ehdottajan sähköpostiosoite

matti-petteri.rajahonka@jyu.fi

**Comment by mirmaid** [comment]
Suhde muutettu.
