### ISSUE TITLE
koreanologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4770]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

koreanologia 
#### Ehdotettu termi ruotsiksi

koreanologi 
#### Ehdotettu termi englanniksi

koreanology 
#### Assosiatiiviset (ST)

[japanologia](http://www.yso.fi/onto/yso/p11897) 
[sinologia](http://www.yso.fi/onto/yso/p11896) 
[orientalistiikka](http://www.yso.fi/onto/yso/p11898) 
#### exactMatch

Wikipedia : https://en.wikipedia.org/wiki/Korean_studies 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
#### Perustelut ehdotukselle

YSA:ssa on japanologia, sinologia, tibetologia ja indologia. Näiden lisäksi tulisi olla koreanologia. 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

esim. kausijulkaisut Seoul journal of Korean studies ja Hanguk munhwa, e-aineisto http://www.krpia.co.kr/ 
#### Vaihtoehtoiset termit ja ilmaisut

Korean studies 

**Ehdottajan nimi:** Juha Leppämäki 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** juha.leppamaki@helsinki.fi **Termiehdotus Fintossa:** [koreanologia](http://finto.fi/yse/fi/page/Y504770)

**Comment by mirmaid** [comment]
Käytetty Melindassa 3 kertaa.

LCSH: Sinology USE China -- Study and teaching. Vastaavasti tehty Korea -- Study and teaching, ketjua ei kuitenkaan auktorisoitu.

https://no.wikipedia.org/wiki/Koreanologi

Suomeksi ei kovin vakiintunut, Google "koreanologia" 8 viitettä.

**Comment by juhale** [comment]
Näin toteaa koreanologiasta FT, professori Juha Janhunen kirjoituksessaan _Aamuruskon maa_ teoksessa _Korea: kolme ovea tiikerin valtakuntaan_ (Helsinki: Gaudeamus, 2000):

> Korean tutkimuksen uutta aaltoa symboloi myös se nimike, jota tästä tutkimuksesta käytetään. Niin kauan kuin korean kieltä ja kulttuuria harrastettiin vain akateemisen orientalistiikan yhtenä eksoottisena sarkana, puhuttiin yleisesti _koreanistiikasta_ (esim. saksaksi _Koreanistik_, englanniksi _Koreanistics_). 1970-luvulta lähtien tämä termi alkoi sekä korealaisista itsestään että monista länsimaisista tutkijoista tuntua vanhanaikaiselta, etenkin kuin Japanin ja japanilaisuuden tutkimuksesta käytettiin jo tuolloin termiä _japanologia_. Nyttemmin myös Korean ja korealaisuuden tutkimusta kutsutaan _koreanologiaksi_ (saksaksi _Koreanologie_, englanniksi _Koreanology_ tai _Korean Studies_).

ja jatkaa vielä:

> Kansainvälisen tutkimuksen kohteina koreanologia ja japanologia ovat molemmat uusia ja keskenään verrannollisia aloja, joiden piiriin luetaan nyttemmin yhä laajempi kirjo maan, kansan ja kulttuurin tutkimuksen eri näkökulmia.

Tähän minulla ei ole varsinaisesti lisättävää. Totean vain, että Korea on merkittävä maa Itä-Aasian kulttuurialueella siinä missä Japani ja Kiinakin. Koreaa, sen kieltä ja kulttuuria tutkitaan Suomessa. Ja toistan: YSA:ssa on japanologia ja sinologia. Näiden lisäksi tulisi olla koreanologia.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
