### ISSUE TITLE
eideettinen reduktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4771]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

eideettinen reduktio 
#### Ehdotettu termi englanniksi

eidetic reduction 
#### Ehdotettu termi ruotsiksi

eidetisk reduktion 
#### Ehdotettu yläkäsite YSOssa (LT)

[reduktio](http://www.yso.fi/onto/yso/p9999) 
#### Assosiatiiviset (ST)

[hermeneutiikka](http://www.yso.fi/onto/yso/p9695) 
[fenomenologia](http://www.yso.fi/onto/yso/p2977) 
#### exactMatch

Tieteen termipankki : http://tieteentermipankki.fi/wiki/Filosofia:eideettinen_reduktio 
#### Perustelut ehdotukselle

Husserlin fenomenologiassa menetelmä, jolla voidaan hahmottaa ilmiön olemus.

Edmund Husserlin (1859-1938) eideettinen reduktio täydentää fenomenologista reduktiota. Siinä edetään vapaan variaation ja mielikuvituksen avulla tarkastelemaan oman tietoisuuden yleisiä piirteitä, tietoisuuden yleisiä hahmoja eli eidoksia. Eideettinen tutkimus tapahtuu siten, että erilaisia tietoisuuden muotoja, esimerkiksi havaintoa jostakin kappaleesta varioidaan mahdollisimman laajasti ja vapaasti, mutta kuitenkin niin, että pysytellään edelleen juuri tämän saman kokemustyypin piirissä. Esiin nousee lopulta jotakin yleistä, joka pätee kaikkiin kuviteltaviin havaintoihin. Tavoitteena on siis tavoittaa se mikä yksittäisessä ja ainutlaatuisessa on yleistä. On kuitenkin huomattava, että eideettinen reduktio vaatii jonkinlaisen esikäsityksen kulloinkin tarkasteltavana olevasta kokemustyypistä. Tätä voi nimittää eideettiseksi intuitioksi tai näkemiseksi. Husserl ei kuitenkaan hyväksy platonista ideaoppia, jossa olemukset olisivat ideoita. Hänen näkemyksensä olemuksista jää hieman hämäräksi.
Eidosten tavoittaminen vaatii harjoitusta. Esimerkiksi jos näen punaisen täplän, sitä ei pidä käsitellä yhtenä punaisen esiintymänä tai määrällisenä tapauksena, vaan olemuksen itsensä instanssina. Kun ymmärrän puhtaan punaisuuden, voi siitä siirtyä tavoittamaan värin olemuksen. Eideettinen reduktio jää kuitenkin aina hieman vaillinaiseksi: sen tuloksia ei välttämättä voida pitää koko tietoisuutta leimaavina rakenteina ja toisaalta kokemus- ja kohdetyyppien taustalta voi löytyä vielä tarkempia tyyppierotteluita. Tämä kuvaa fenomenologisen tutkimuksen perustavanluonteista keskeneräisyyttä ja rajallisuutta. Husserlin mukaan tutkimus on eräänlaista kriittistä siksakkia, joka vuoroin luo uusia kuvauksia ja vuoroin reflektoi niitä ja niiden asemaa tietoisuuden kokonaisuudessa.
Martin Heideggerin (1889-1976) katsantokannassa voidaan kysyä mikä on se yleinen muoto tai eidos, joka koetun kohteen on toteutettava voidakseen olla todellinen juuri sellaisena kohteena, ei vain kokevalle subjektille, vaan kenelle hyvänsä? Miten koetun on näyttäydyttävä tullakseen koetuksi todellisena ja olevana? Heidegger suhtautui Husserlin eideettiseen reduktioon kriittisesti, kyseenalaistaen sen platonistisen lähtökohdan, jonka mukaan kaikki merkitys on pohjimmiltaan yleispätevää, jonka tavoittaminen edellyttää yksittäiseen ilmentymään liittyvän tilannekohtaisuuden sivuuttamista. Heideggerille nimenomaan kokemus on tilannesidonnainen ja yksilöllinen eikä siitä voi tulla yleispätevää. Heidegger katsoikin, että fenomenologinen analyysi on eideettisen analyysin sijaan hermeneuttista, konkreettisten mielekkyystilanteiden kielellistä tulkintaa, viitoittavaa ymmärrettäväksi saattamista. Silloinkin kun jäsennetään välitöntä kokemusta, sitä tulkitaan historiallisesti välittyneen käsitteistön avulla. 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Taitamisen tiede - tietämisen taide, https://jyx.jyu.fi/dspace/handle/123456789/51643 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi 
**Termiehdotus Fintossa:** [eideettinen reduktio](http://finto.fi/yse/fi/page/Y504771)

**Comment by mirmaid** [comment]
Ei Melindassa. YSAssa on _reduktio_, jota käytetty 47 kertaa.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Eidetic_reduction

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
