### ISSUE TITLE
perusteluvelvollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4772]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

perusteluvelvollisuus 
#### Assosiatiiviset (RT)

[lainsäädäntö](http://www.yso.fi/onto/yso/p13854) 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 
#### Perustelut ehdotukselle

käsiteyhdistelmä: perustelut, velvoitteet ei ole riittävän tarkka lainsäädäntöaineiston yhteydessä 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Soininen: Vesioikeudellinen perusteluvelvollisuus 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi 
**Termiehdotus Fintossa:** [perusteluvelvollisuus](http://finto.fi/yse/fi/page/Y504772)

**Comment by mirmaid** [comment]
Ei EKS:ssa. 

Ei Melindassa asiasanana, sanahaulla 5 viitettä.

**Comment by mirmaid** [comment]
YSAssa on todistustaakka, mutta ilmeisesti tätä termiä käytetään hallintolainkäytössä (tosin hallintolaissa ja hallintolainkäyttölaissa puhutaan vain perusteluista).

http://tieteentermipankki.fi/wiki/Oikeustiede:perusteluvelvollisuus

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
motiveringsskyldighet
ET motiveringsplikt
ET skyldighet att motivera
