### ISSUE TITLE
Mittapiirustus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4774]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

Mittapiirustus 
#### Ehdotettu termi ruotsiksi

Måttritning 
#### Ehdotettu termi englanniksi

Measured drawing 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
#### Perustelut ehdotukselle

Oleellinen osa vanhan rakennuksen dokumentointia on sen tarkka piirtäminen mittojen mukaan 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

arkkitehtuuripiirustuskokoelmien luetteloinnissa 

**Ehdottajan nimi:** Tryggve Gestrin 
**Ehdottajan sähköpostiosoite:** tryggve.gestrin@espoo.fi 
**Ehdottajan organisaatio:** Espoon kaupunginmuseo 
**Termiehdotus Fintossa:** [Mittapiirustus](http://finto.fi/yse/fi/page/Y504774)

**Comment by mirmaid** [comment]
Ei Melindassa.

MAO-ontologiassa monikossa

**Comment by mirmaid** [comment]
YSAssa on _piirustukset_ ja _pohjapiirustukset_ ja toisaalta _rakennuspiirustus_, _sähköpiirustus_ ja _tekninen piirustus_.

**Comment by LeKorsu** [comment]
Teknisen piirustuksen alla olevat kartanpiirustus, koneenpiirustus, rakennuspiirustus ja sähköpiirustus ovat yksikössä, mittapiirustus sopisi sen mukaan yksikköön.

**Comment by mirmaid** [comment]
Hyväksytty monikossa (YSA-kokous 13.12.2016)
