### ISSUE TITLE
ammattikunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4775]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

ammattikunnat 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
#### Perustelut ehdotukselle

Ammattikunnat on käsite, joka sopii kaikkiin teollisuuden alojen ryhmiin. Ei välttämättä päätermiksi, mutta viitteeksi sanalle ammattikuntalaitos 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

https://kirjasto.jyu.fi/kauppa/tuotteet/puusuksia-suomesta 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi 
**Termiehdotus Fintossa:** [ammattikunnat](http://finto.fi/yse/fi/page/Y504775)

**Comment by mirmaid** [comment]
Käytetty Melindassa 11 kertaa. Tuskin kuitenkaan kannattaa olla sekä ammattikunnat että ammattikuntalaitos, eli ohjaustermiksi?

**Comment by mariaforsen** [comment]
Nämä ovat eri asioita/termejä ruotsiksi, eli Motin mukaan: 
1. saman ammatin harjoittajat. =yrkeskår
2. hist. samaa ammattia harjoittavat käsityöläiset; näiden yhdistys. =skråväsen (nyt Allärsissa)

**Comment by MikkoAleksanteri** [comment]
Ammattikuntalaitos viittaa siis tuohon historialliseen järjestelmään, joka esim. Suomessa lakkautettiin 1868: https://fi.wikipedia.org/wiki/Ammattikuntalaitos

Ymmärtääkseni nykyisin termiä ammattikunnat käytetään valjästi tuossa Marian mainitsemassa 1. merkityksessä eli saman ammatin harjoittajat.

**Comment by mirmaid** [comment]
Ehdotettu ohjaustermiksi historiallisessa merkityksessä, liittyykö siihen siis mielestänne ongelma? Tuo ykkösmerkitys ei varmaan ole kuvailussa käyttökelpoinen/tarpeellinen.

**Comment by mirmaid** [comment]
ammattikunnat (historia) KÄ ammattikuntalaitos
