### ISSUE TITLE
ulosteensiirto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4777]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

ulosteensiirto 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
#### Perustelut ehdotukselle

Uusi hoitomenetelmä 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Teos: Kehon mikrobit :avain terveyteen ja hyvinvointiin / Alanna Collen ; suomentanut : Antti Immonen. 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi 
**Termiehdotus Fintossa:** [ulosteensiirto](http://finto.fi/yse/fi/page/Y504777)

**Comment by mirmaid** [comment]
Ei Melindassa. 

https://fi.wikipedia.org/wiki/Ulosteensiirto

Lääketieteen termit: _suolistomikrobien siirto_

**Comment by Elmukelmu** [comment]
Hyvä termi, jo vakiintunutkin

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
