### ISSUE TITLE
sukupolvikokemus/mukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4778]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

sukupolvikokemus/mukset 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 
#### Tarkoitusta täsmentävä selite

Tietyn sukupolven yhteinen kokemus; kollektiivinen kokemus tietyistä (aikakauden) ilmiöistä 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Maamme :itsenäisen Suomen kulttuurihistoria 
#### Perustelut ehdotukselle

Suomen itsenäisyyden aika on ollut täynnä suuria muutoksia. Sadassa vuodessa elintaso on kasvanut huimasti ja Suomi on avautunut entistä enemmän maailmalta tuleville vaikutteille. Yhteiset muistot ja sukupolvikokemukset ovat yhdistäneet kansakuntaa siinä, missä lamat ja poliittinen ilmapiiri ovat sitä jakaneet. Maamme näyttää sanoin ja kuvin, millaista elämä itsenäisessä Suomessa on ollut. Ääneen pääsevät kaikenkirjava kansa ja aikalaislähteet, joiden avulla arkiset kokemukset ja kulttuuri-ilmiöt heräävät henkiin. Kirjan toimittajat ovat kulttuurihistorian professoreita. 

**Ehdottajan nimi:** Outi Hinikka 
**Ehdottajan organisaatio:** BT Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi 
**Termiehdotus Fintossa:** [sukupolvikokemus/mukset](http://finto.fi/yse/fi/page/Y504778)

**Comment by mirmaid** [comment]
Käytetty Melindassa 2 kertaa monikossa.

**Comment by Elmukelmu** [comment]
Tällä olis varmaan käyttöä

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
