### ISSUE TITLE
tarkekirjoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4779]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[tarkekirjoitus](http://www.yso.fi/onto/ysa/Y104543) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

onko sama asia kuin stranskriptio 
#### Ehdottaja

Outi Hintikka 
#### Perustelut ehdotukselle

Teos: Puheesta tekstiksi 
#### Ehdottajan organisaatio

BTJ Finland 
#### Ehdottajan sähköpostiosoite

outi.hintikka@btj.fi

**Comment by mirmaid** [comment]
KT transkriptio -- kielitiede
http://tieteentermipankki.fi/wiki/Kielitiede:transkriptio

Kielitieteen ontologiassa on transkriptio, ei tarkekirjoitusta edes ohjausterminä. (Käytetty kerran Melindassa, tarkekirjoitus 4 kertaa.)

Mikähän tässä on varsinainen ehdotus?

**Comment by satuniininen** [comment]
https://fi.wikipedia.org/wiki/Tarkekirjoitus
"Tarkekirjoitus eli foneettinen kirjoitus eli foneettinen transkriptio"

**Comment by mariaforsen** [comment]
Allär: fonetisk skrift=tarkekirjoitus, transkribering (språkvetenskap)=litterointi

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 7.3.2017).

**Comment by mirmaid** [comment]
Lisätty KT foneettinen transkriptio ja foneettinen kirjoitus
