### ISSUE TITLE
litteraatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4780]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

litteraatio 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 
#### Perustelut ehdotukselle

Litterointi puolestaan määritellään Tieteen termipankissa  nauhoitetun keskusteluaineiston kirjaintamiseksi tekstimuooton. s.10 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Puheesta tekstiksi 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi 
**Termiehdotus Fintossa:** [litteraatio](http://finto.fi/yse/fi/page/Y504780)

**Comment by jtuohini** [comment]
Eli ehdotus olisi oikeastaan:

**litteraatio**
   KT   litterointi
   KT   sanelunpurku

Ja olisiko itse asiassa litterointi kuitenkin parempi päätermi, kun on Tieteen termipankissa (ja Wikipediassa ja on lisäksi analoginen muodolle translitterointi)

**Comment by mirmaid** [comment]
Litterointia ehdotettu aikaisemmin #2529

**Comment by mirmaid** [comment]
Muotoa _litterointi_ käytetty Melindassa 3 kertaa.

**Comment by mariaforsen** [comment]
Kannatan litterointia, löytyy myös MOTista (litteraatio ei löydy sanastoista ollenkaan).

**Comment by mirmaid** [comment]
Hyväksytty muodossa litterointi (YSA-kokous 13.12.2016)

**Comment by jtuohini** [comment]
Jostain syystä KT-muoto _sanelunpurku_ on jäänyt menemättä YSAan eli ehdotan edelleen sen lisäämistä!
