### ISSUE TITLE
lopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4781]
#### Ehdotuksen tyyppi

Muutos olemassa olevaan käsitteeseen 
#### preflabel

[lopetus](http://www.yso.fi/onto/ysa/Y111408) 
#### Tila

Käsittelyssä 
#### Ehdotettu muutos

Lopetus kuuluu myös keskeisesti ryhmiin eläinlääketiede, kotieläintalous. Lopetus / lopettaminen / eutanasia kuuluvat mm. eläinlääkärien arkipäivän sanastoon. Lopettaseen liittyy eettistä ja moraalista pohdintaa ja päätöksentekoa. 
#### Perustelut ehdotukselle

Lopettaminen /lopetus on toimenpide, jolla ihminen tappaa eläimen muutoin kuin metsästys- tai teurastustarkoituksessa. 
#### Ehdottaja

Anne Uusitalo 
#### Ehdottajan organisaatio

Helsingin yliopiston kirjasto / Viikin kampuskirjasto 
#### Ehdottajan sähköpostiosoite

anne.uusitalo@helsinki.fi

**Comment by mirmaid** [comment]
Ks. myös #4799

**Comment by mirmaid** [comment]
Muutamia kertoja Melindassa termeillä _lopetus_ tai _eutanasia_. 

Suurin osa _lopetus_-termillä kuvaillusta aineistosta käsittelee tupakoinnin lopettamista, paljon myös yritystoiminnan lopettamista (toisinaan näissä sopisi paremmin lakkauttaminen) ja jonkin verran esim. urheilun lopettamista.

**Comment by mariaforsen** [comment]
Tähän täytyy saada selkeät merkityserot, eläinten lopettaminen on aivan eri asia kuin lopetus jonkun asian lopettamisena - ja ruotsiksi aivan eri vastineet. 

Ruotsiksi olisi "avlivning" (=lopetus (tappaminen)) tarpeen (esim. http://linda.linneanet.fi/F/42VFUUUNMBMBXYTN8KANKP9242MH3URUDUATEK8A2XTDE146P1-14593?func=full-set-set&set_number=156773&set_entry=000001&format=999 ) Avlivning myös esim. SAOssa.

**Comment by mirmaid** [comment]
Aika ikävä olisi tuo (tappaminen)-tarkenne...löysin Melindasta yhteensä ~5 viitettä eläinten lopettamisesta termeillä _lopetus_ ja _eutanasia_. Tietysti voisi olla (eläimen eutanasia), mutta ne tulisivat kuitenkin mukaan _eutanasia_-termillä haettaessa. Tai sitten tietysti vain (eläimen), en vaan itse tykkää tuollaisesta "vajaasta" tarkenteesta, mutta ehkä se on lähinnä esteettinen asia.

**Comment by mariaforsen** [comment]
Voisiko tarkenne "(eläimen eutanasia) myös auttaa käyttäjiä ymmärtämään että eläinten kohdalla käytetään nimenomaan lopetus-termiä? Vai onko sellaista rajausta ylipäätään olemassa..? Netissä ja muutenkin käytetään kyllä "eutanasia" myös esim. koirien ja muiden lemmikkien kohdalla. 

Vai olisiko syytä ohjata käyttöä -> eläineutanasia, kuten MESH: http://finto.fi/mesh/sv/page/D037901?anylang=on ?

**Comment by mirmaid** [comment]
Tuo onkin hyvä, joko päätermiksi tai tarkenteeksi.

**Comment by mirmaid** [comment]
Hyväksytty eläineutanasia KT lopetus (eläimen) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
avlivning /ne, sao
avlivning av djur /mesh
eutanasi (djur)?

**Comment by mariaforsen** [comment]
Oliko se todella niin että eläineutanasia on sopiva kaikissa tilanteissa missä eläin lopetetaan, vaikka lasketaankin teurastus pois (ja onkohan Meshissä ihan loppuun asti mietitty tätä asiaa, tai ehkä heillä on omanlainen ratkaisu, koska lääketieteen näkökulmasta on nimenomaan eutanasia-aspekti ainoa relevantti aspekti).

Eihän se esim. ole teurastus kun koe-eläin lopetetaan, mutta ei kai se ole oikein kutsua sitä eutanasiaksikaan (eihän tarkoitus ole lieventää eläimen tuska tms. vaan koe-eläimet lopetetaan myös esim. 
yksinkertaisesti koska niistä ei ole enää hyötyä, projekti loppuu jne.)

Tuossa ruotsin termissä "avlivning" ei ole aina eutanasia-näkökulma. Sen takia tuli mieleen että voiko tulla tilanteita missä näitä ei sitten käytetäkään samalla tavalla.. Kun katsoo netistä tarkemmin niin tuo "eläineutanasia" yhteenkirjoitettuna ei olekaan kovin tavallista (11 osumaa), lähinnä mesh ja jotain eläinlääkäriasemia (joilla tietty on yleensä se eutanasia-aspekti).

Ja oliko jokin syy miksei "eläinten lopettaminen" olisi ok? Siitä löytyy paljon enemmän googlessa ja oma lukunsa Finlexissäkin
http://www.finlex.fi/fi/laki/ajantasa/1996/19960396 Siinä termissä ei myöskään oteta minkäänlaista kantaa miksi eläin lopetetaan.. Jos alkaa käyttää "eläineutanasia"-termiä melkein mistä tahansa eläinten lopettamisista niin se menee kai lähinnä jonkinlaiseksi kaunisteluksi.

**Comment by PaiviLipsanen** [comment]
"eläinten lopettaminen" kuulostaa hyvältä vaihtoehdolta

**Comment by mirmaid** [comment]
Entä _eläimen lopetus_?

**Comment by PaiviLipsanen** [comment]
Evira: Eläimen lopetuksella tarkoitetaan prosessia, joka aiheuttaa eläimen kuoleman. Teurastuksella tarkoitetaan ihmisravinnoksi tarkoitetun eläimen lopetusta.
https://www.evira.fi/elaimet/elainsuojelu-ja-elainten-pito/elainsuojelu-teurastuksessa-ja-lopetuksessa/

**Comment by mariaforsen** [comment]
"Eläimen lopetus" hyvä terminä itse tappamiselle, riippumatta mistä syystä tehdään jne. ja vastineena avlivning. Teurastaa: "tappaa teuraseläin ja käsitellä sen ruho määrätavalla."

**Comment by YSA-kokous** [comment]
eläimen lopetus
