### ISSUE TITLE
robottiautot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4783]
#### Käsitteen tyyppi

CONCEPT 
#### Ehdotettu termi suomeksi

robottiautot 
#### Ehdotettu termi ruotsiksi

självkörande bilar 
#### Ehdotettu termi englanniksi

autonomous cars 
#### Ehdotettu yläkäsite YSOssa (LT)

[autot](http://www.yso.fi/onto/yso/p1223) 
#### exactMatch

LCSH : Autonomous vehicles 
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 
#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)

Driverless : intelligent cars and the road ahaed 
#### Tarkoitusta täsmentävä selite

Wikipedia: https://en.wikipedia.org/wiki/Autonomous_car 
#### Perustelut ehdotukselle

Robottiautoista tulee lähitulevaisuudessa varmasti kirjallisuutta enemmänkin. 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi 
**Termiehdotus Fintossa:** [robottiautot](http://finto.fi/yse/fi/page/Y504783)

**Comment by mirmaid** [comment]
Kerran Melindassa

Termiehdotuksena myös _älyautot_ #3345

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016) (tutkitaan voiko tehdä KT älyautot)
