### ISSUE TITLE
katalogimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4784]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

katalogimusiikki 

#### exactMatch   

Production music : https://en.wikipedia.org/wiki/Production_music 
Production music : <http://id.loc.gov/authorities/subjects/sh94002720.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Äänitettyä musiikkia, jonka tekijänoikeudet on luovutettu kertakorvauksella tuotantoyhtiön lisensoitavaksi eri medioiden käyttöön. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://luettelo.helmet.fi/record=b1844653~S9*fin 

#### Perustelut ehdotukselle   

Vanhaa katalogimusiikkia julkaistaan kuluttajille suunnattuina äänitteinä entistä enemmän. 

#### Vaihtoehtoiset termit ja ilmaisut   

kirjastomusiikki, library music, production music, stock music, tuotantomusiikki 

**Ehdottajan nimi:** Tommi Viitamies 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto / Helmet 
**Ehdottajan sähköpostiosoite:** tommi.viitamies@hel.fi **Termiehdotus Fintossa:** [katalogimusiikki](http://finto.fi/yse/fi/page/Y504784)

**Comment by jtuohini** [comment]
Kannatan ehdotusta, joskin ottaisin päätermiksi mieluummin kirjakielisemmän käsitteen "tuotantomusiikki", jota esimerkiksi Teosto käyttää (http://www.teosto.fi/teosto/artikkelit/tuotantomusiikin-tallennusoikeuksien-itsehallinnointi).

**Comment by TommiViitamies** [comment]
Luumu-ryhmä ehdottaa, että hyväksytään Tuohiniemen tarkennuksella: käytettävä termi: tuotantomusiikki.

**Comment by LeKorsu** [comment]
Eli katalogimusiikki KÄ tuotantomusiikki? Sopii minulle.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)

**Comment by mirmaid** [comment]
LT musiikki, RT taustamusiikki. Entä elokuvamusiikki, mainosmusiikki?

**Comment by TommiViitamies** [comment]
Elokuvamusiikki ja mainosmusiikki ovat kyllä tuotantomusiikin keskeisiä käyttötarkoituksia. Sikäli RT varmasti ok.

**Comment by jtuohini** [comment]
Kannatetaan kumpaakin RT-lisäystä.
