### ISSUE TITLE
tilannekuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4785]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tilannekuva](http://www.yso.fi/onto/ysa/Y182376) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö merkitystä rajata? 

#### Perustelut ehdotukselle   

Tilannekuva = tiettyä tilannetta esittävä kuva t. kuvaus; vrt. tuokiokuva. Novellin hauskat tilannekuvat. Ottelusta näpätty tilannekuva. Myös valokuvaustermi? Ryhmitelty yleistermiksi, mutta Melindassa käytössä sodankäyntiterminä, joka kääntyisi luontevasti termillä "situational awareness". 

Ongelma myös ruotsiksi. Nyt näköjään tulkittu valokuvakäsitteenä=situationsbild. TilannekuvaUS olisi varmaan tulkittu toisin=lägesbeskrivning. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by Elmukelmu** [comment]
Yleinen käsite pelastustoimessa ja ensihoidossa. Aleksi-tietokannan viitteistä suurin osa näiltä aloilta + muutama sotilaallinen.

**Comment by mirmaid** [comment]
PUHOssa ja TSR-ontologiassa on _tilannetietoisuus_, jonka vastine on mainittu situational awareness. Se ei kuitenkaan sovi aina, esim. Rikollisuustilanne 2014, Teollisuuden palveluliiketoiminnan kartoitus jne. PUHOssa on erikseen myös tilannekuva. 

Osassa voisi sopia tilannekuvaukset, mutta osassa on kyse enemmän käsityksistä (varmaan esim. Elinan mainitsemissa).

Melindassa ei käytetty valokuvaus-merkityksessä.

**Comment by mirmaid** [comment]
Jos otetaan _tilannetietoisuus_, ja vaihdetaan se tilannekuvan tilalle mikäli mahdollista? Tutkitaan sopiiko jäljelle jääviin tilannekuvaukset.

**Comment by mariaforsen** [comment]
Eli sanastossa olisi tilannetietoisuus ja tilannekuvaukset? Näille molemmille on olemassa hyvät (ja tarpeellisetkin) ruotsinkieliset termit.

**Comment by Elmukelmu** [comment]
Pakko ihan hiukkasen vastustaa.. Tilannetietoisuus tuntuu laajemmalta käsitteeltä kuin tilannekuva. En ole törmännyt pelastus- ja turvallisuusalan artikkeleissa ikinä tilannetietoisuus-termiin, mutta tilannekuva on vakiintuneessa käytössä.

**Comment by EsaMPKK** [comment]
Voisiko tilannekuvan eri käyttötarkoituksiin lisätä sulkutarkenteita? 
tilannekuva (sotatiede)
tilannekuva (pelastusala)
tilannekuva (turva-ala)
Itse tilannekuva käsitteenä tuntuu tuiki välttämättömältä, vaikka PUHOssakin on useita vastaavanlaisia käsitteitä: tilannetietoisuus, tilanneymmärrys, toimintaympäristötietoisuus...

**Comment by mirmaid** [comment]
Onko _tilannekuva_ sotatieteessä eri käsite kuin pelastus- ja turva-alalla, vai onko kyse vain eri kontekstista? Ja onko kyse varmasti eri asiasta kuin tilannetietoisuudessa: "Tilannetietoisuutta, eli sitä että tietää mitä on tapahtumassa ja pystyy ennakoimaan mitä tulee kohta tapahtumaan..." http://www.uef.fi/-/14-2-hatakeskuspaivystaja-ja-ensihoidon-kenttajohtaja-tarvitsevat-hyvaa-tilannetietoisuutta.

**Comment by YSA-kokous** [comment]
Jätetään tilannekuva = lägesbild, lisätään määritelmä.

**Comment by mirmaid** [comment]
**Kokonaisturvallisuuden sanasto:** 
koottu kuvaus vallitsevista olosuhteista, käsillä olevan tilanteen synnyttäneistä tapahtumista, tilannetta koskevista taustatiedoista ja tilanteen kehittymistä koskevista arvioista sekä eri toimijoiden toimintavalmiuksista
huomautus
Tilannekuvaa tarvitaan päätöksenteon tueksi.
Tilannekuva voidaan käsittää myös suppeammin tarkoittamaan vain esimerkiksi karttaa ja suullista tai kirjallista tietoa esillä olevasta tilanteesta.
Määritelmän mukaisesta tilannekuvasta (konkreettinen kuvaus) käytetään englanniksi termiä situation picture, mutta jos termillä tilannekuva viitataan konkreettisen kuvauksen lisäksi esimerkiksi tilannekuvatoimintaan tai tilaan, jossa tilanteesta on pystytty muodostamaan kuva, voidaan käyttää termiä situation awareness.

**Varautumisen ja väestönsuojelun sanasto:**
päättäjien ja heitä avustavien henkilöiden ymmärrys tapahtuneista asioista, niihin vaikuttaneista olosuhteista, eri osapuolten tavoitteista ja tapahtumien mahdollisista kehitysvaihtoehdoista
huomautus
Tilannekuvaa tarvitaan päätöksenteon tueksi.
Tilannekuva voidaan käsittää myös suppeammin tarkoittamaan vain esimerkiksi karttaa ja suullista tai kirjallista tietoa esillä olevasta tilanteesta.

**Comment by mirmaid** [comment]
Tilannekuvalla tarkoitetaan kokonaisnäkemystä yrityksen toimialasta, tulevista trendeistä, mediasta, asiakkaista, henkilöstöstä, kilpailijoista, kumppaneista, sosiaalisesta mediasta jne. http://cocomms.com/2014/09/26/ammutko-sokkona-vai-tahtaatko/

**Comment by mirmaid** [comment]
Olisiko esim. _"Kuvaus tai käsitys vallitsevasta tilanteesta, sen taustatekijöistä ja tilanteen kehittymistä koskevista arvioista (TAI: tilanteen kehittymisen mahdollisista vaihtoehdoista)"_.

**Comment by YSA-kokous** [comment]
Loppuosa suluista
