### ISSUE TITLE
modernisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4786]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[modernisaatio](http://www.yso.fi/onto/ysa/Y128382) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistäminen termiin uudenaikaistuminen, tai merkitysten erottaminen sulkutarkenteella tai muulla tavoin. Molempien ryhmä nyt 60?. 

#### Perustelut ehdotukselle   

Ruotsiksi molemmat modernisering, modernisaation vastineessa nyt sulkutarkenne (samhällsförändring). 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan organisaatio   

Åbo Akademis bibliotek 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Molempien yläkäsite on sosiaalinen muutos, joten siitäkään ei saa mitään apua sulkutarkenteiden luomiseen (ruotsiksi). Modernisaatio on saanut huomautuksen ja kunhan myös uudenaikaistuminen määritellään selkeästi voidaan ehkä saada tarkenteita ruotsiksi. Uudenaikaistuminen ei löydy sanastoista/sanakirjoista ja vain vähän googlessa, joten siitäkään ei juuri apua. Englanniksikin molemmat modernisation.

**Comment by mirmaid** [comment]
Melinda: _modernisaatio_ 772 viitettä, _uudenaikaistuminen_ 933. Vain 75 joissa molemmat termit.

**Comment by mirmaid** [comment]
Usein vaikea sanoa miksi on valittu jompi kumpi termi (varsinkin ehkä miksi uudenaikaistuminen modernisaation asemesta). Jos yhdistettäisiin, ongelmallisia (?):

**modernisaatio**, kävisikö uudenaikaistuminen?:

_Musiikkifanius ja modernisoituva nuoruus : populaarimusiikin ihailijakulttuurin rakentuminen Suomessa 1950-luvulta 1970-luvun alkuun_
_Time, capitalism and alienation : a socio-historical inquiry into the making of modern time_
_Crossing borders : modernity, ideology, and culture in Russia and the Soviet Union_
_The birth of the modern world, 1780-1914 : global connections and comparisons_

**uudenaikaistuminen**, kävisikö modernisaatio?: 

_Isäntien aika : Uudenmaan läänin maanviljelysseura ja maatalouden muutos : seuran synty ja toiminta 1897-1922_
_Kasvavan liikenteen kannattava kanava : Saimaan kanavan rahtiliikenne autonomian aikana_
_Tuotantorakenteen muutoksen hallinta Petsamon kaivosyhdyskunnissa_
_Nykysirkus : aarteita, avaimia ja arvoituksia_

**Comment by mirmaid** [comment]
Nyt uudistaminen KÄ _uudistukset_ (_reformer_), jos uudenaikaistuminen yhdistetään modernisaatioon, voisi _uudistaminen_ ("förnyande") -termin lisääminen ehkä auttaa?

Toki merkitysero suomeksi on tässä pieni ja hämärä.

**Comment by mariaforsen** [comment]
Allärsissa nyt förnyande=uusiutuminen, mutta se voidaan ehkä muuttaa -> återfall (uusiutuminen näyttää olevan käytetty lähinnä lääketieteellisenä). Eli ok ruotsiksi siinä tapauksessa. Reformer=uudistukset on kyllä ainakin ruotsiksi vähän eri asia kuin förnyande=uudistaminen, joten sen lisääminen olisi hyvä.

**Comment by YSA-kokous** [comment]
uudenaikaistuminen KÄ modernisaatio
uudistaminen = förnyande
