### ISSUE TITLE
valtiopäivät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4787]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valtiopäivät](http://www.yso.fi/onto/ysa/Y100027) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa:

- valtiopäivät (kansanedustuslaitokset)
- valtiopäivät (poliittinen historia) 

#### Perustelut ehdotukselle   

1. eduskunnan istuntokausi. Varsinaiset, ylimääräiset valtiopäivät. Valtiopäivien avajaiset, päättäjäiset. Eduskunta kokoontuu valtiopäiville.
2. eräiden maiden kansanedustuslaitoksista, parlamentti. Ruotsin valtiopäivät päättivät, että – –. 

#### Ehdottaja   

YSO 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
YSAan on otettu "maapäivät", päivitetäänkö myös YSOon muotoon "maapäivät"? Nyt vielä "valtiopäivät (maapäivät)".

**Comment by mariaforsen** [comment]
Sulkutarkenne "poliittinen historia" voi mielestäni helposti aiheuttaa hämmennystä ja väärinymmärrystä. Moni yhdistää historia johonkin kauan sitten tapahtuneeseen, mutta aineisto voi yhtä hyvin käsitellä meneillään olevat valtiopäivät. Huomautuksena YSOssa nyt "Eduskunnan istuntokausi." Voisiko tarkenteena yksinkertaisesti olla "istuntokaudet" tms. joka selvästi kertoo mihin viitataan? Olisi selkeämpää jos vaihtoehdot kuvailijalle olisi: valtiopäivät (kansanedustuslaitokset) ja valtiopäivät (istuntokaudet)

**Comment by YSA-kokous** [comment]
valtiopäivät (kansanedustuslaitokset) ja valtiopäivät (istuntokaudet)

**Comment by mariaforsen** [comment]
Sv. 
-riksdagar
-riksmöten
