### ISSUE TITLE
penikkatauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4788]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[penikkatauti](http://www.yso.fi/onto/ysa/Y160939) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Kaksi eri merkitystä, ks. esim. Lääketieteen termit. Ruotsiksi eri termejä riippuen merkityksestä. Tarvitseeko jakaa tms. vai riittäisikö esim. huomautus siitä että käytetään vain eläinlääk. merkityksessä? Melindassa käytetty pari kertaa myös ihmisten kohdalla. Koska nämä taudit/oireet ovat aivan eri asioita on tärkeää ettei käytetä sekavasti. 

#### Ehdotettu muutos   

Jaettava 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan organisaatio   

Åbo Akademis bibliotek 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ihmisen penikkataudista käytetään myös termiä _säären lihasaitio-oireyhtymä_ http://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00317. Tosin _Juoksija_-lehti erottaa nämä toisistaan: http://www.juoksija-lehti.fi/Harjoittelu/Terveysjavammat/tabid/3017/ArticleID/17/Default.aspx. Voisi tehdä penikkatauti (eläintaudit) ja penikkatauti (ihmisen) KÄ säären lihasaitio-oireyhtymä, tai penikkatauti (rasitusvammat)?

MeSHissä on _aitio-oireyhtymät_. Termixistä löytyy penikkatauti-haulla Sääriluun mediaalinen rasitusoireyhtymä, mutta tätä ei löydy muualta.

**Comment by mirmaid** [comment]
Hyväksytty penikkatauti (eläintaudit) ja penikkatauti (rasitusvammat) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
valpsjuka (djursjukdomar)

http://finto.fi/mesh/fi/page/D058923
