### ISSUE TITLE
vastaanotto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4789]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vastaanotto](http://www.yso.fi/onto/ysa/Y104170) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mahdollisesti jaettava tai selkeytettävä. 

#### Perustelut ehdotukselle   

YSOssa jaettu:
- vastaanotto (fyysinen)
- vastaanotto (reseptio)

Olisiko sittenkin parempi ottaa YSAan reseptio, jolle ohjaustermiksi "vastaanotto (reseptio)" tai jotain tuon tapaista? 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by krinay** [comment]
YSAn termiä vastaanotto on käytetty Melindassa satoja kertoja nimenomaan merkityksessä reseptio, muussa merkityksessä ymmärtääkseni vähemmän. Kirjallisuudentutkijat näyttäisivät käyttävän edelleen suomenkielistä termiä vähintään yhtä usein kuin termiä reseptio. 
YSAssa on myös termi reseptioestetiikka. (Hoosiaisluoma, Yrjö. Kirjallisuuden sanakirja: 
reseptioestetiikka - tutkimussuuntaus, joka käsittelee kirjallisuuden ja muun taiteen vastaanottoa, reseptiotutkimus, vastaanottotutkimus).

**Comment by LeKorsu** [comment]
YSOn mukainen  jako ja sulkutarkenteiden käyttöönotto minusta parempi vaihtoehto kuin vaihtaa reseptio käytettäväksi termiksi.

**Comment by mirmaid** [comment]
Innovation and its enemies: why people resist new technologies - vastaanotto (reseptio)?

Melindan 150 uusimmassa viitteessä muutaman kerran pakolaisten vastaanotto ja hotellin vastaanotto (toimintana, ei tiloina), kerran puutavaran vastaanotto.

**Comment by mirmaid** [comment]
Entä jos otetaan vain _vastaanotto (reseptio)_, eikä muuta?

**Comment by mariaforsen** [comment]
Eikö olisi siinä tapauksessa parempi jättää vain vastaanotto, eikä määritellä sen enempää on fyysistä vai "psyykkistä"? Ks. Kielitoimiston sanakirjaa - siinähän ei oikeastaan jaotella termiä ensisijaisesti tällä tavalla vaan verbinä, tilaisuutena ja paikkana. 

Vai voiko pitää vastaanotto sellaisenaan ja sen lisäksi vain lisätä reseptio (alakäsitteenä?) =Mirjan alkuperäinen ehdotus?

 Vrt. myös https://fi.wikipedia.org/wiki/Reseptio

**Comment by krinay** [comment]
Minun on vaikea mieltää (sisällönkuvailun ja tiedonhaun näkökulmasta) yksiselitteisesti YSO:n jakoa fyysiseen vastaanottoon (yläkäsite: liikuttaminen) ja reseptioon (yläkäsite: ymmärtäminen). Lisäksi YSAssa ja YSOssa on vielä _vastaanottotoiminta_ (yläkäsite: keskinäinen toiminta), jota on käytetty Melindassa asiasanana vain kolmesti. Voiko esimerkiksi pakolaisten vastaanotto olla kaikkea tätä eli fyysistä (vrt. vastaanottokeskukset ym.), reseptiota (suhtautumista pakolaisiin) ja vastaanottotoimintaa?

Jos nämä kaikki vastaanotot pidetään ja otetaan YSAan, pitäisi niiden eroa varmaan selittää huomautuksessa. 

_Kielitoimiston sanakirjan_ mukaan 
**reseptio** =
1. = vastaanotto 1. erik. Taideteoksen reseptio tutkimuskohteena.
2. tavallisemmin: vastaanotto (4). Hotellin reseptio. 
[vastaanotto 4.: paikka jossa jtak otetaan vastaan; reseptio]  

ja **vastaanotto** =
1. vastaanottaminen. Lähetyksen, sanoman, tavaran vastaanotto.--
    Erik. Teoksen vastaanotto se miten yleisö ottaa vastaan teoksen, reseptio.
2. tilaisuus, ajankohta, jonka aikana lääkäri ottaa vastaan potilaita; myös muista samantapaisista tilaisuuksista.
3. juhlallinen tilaisuus, jossa otetaan vastaan vieraita, audienssi.
4. paikka jossa jtak otetaan vastaan; reseptio.

_Vastaanotto (reseptio)_ ei siis ainakaan vaikuta kovin yksiselitteiseltä.

**Comment by siikaa** [comment]
Kaunokissa ei ko. sanaa. Helmetissä myös käytetty kaunokirjallisuuden kuvailussa lähinnä tuossa reseptio-merkityksessä. Toisaalta vastaanottotoiminta kuulostaa kyllä kankealta, jos sitä pitäisi käyttää fyysisestä vastaanotosta. Ehkä tuo YSO:n jako on ihan hyvä.

**Comment by mirmaid** [comment]
_Vastaanottotoiminta_ haluttiin YSAan muistaakseni teoksen _Filosofi tavattavissa_ julkaisun jälkeen jotta voitaisiin kuvailla sellaista toimintaa jossa pidetään vastaanottoa, mutta kyse ei ole terapiasta tai terveydenhuollosta. Uusimmassa viitteessä sitä on käytetty tavaran vastaanotosta, mikä ei ollut missään nimessä alkuperäinen tarkoitus - ja on kieltämättä vähän erikoinen ratkaisu. Tähän voisi yrittää tehdä määritelmää ja ehkä vaihtaa luokat 00 > 48, 55, 60 (?). 

Kuten Maria kommentoi, Kielitoimiston sanakirja tosiaan niputtaa yhteen sekä "fyysisen" vastaanoton että reseption. Minun puolestani tämäkin käy, koska vastaanotto-termillä pelkästään on tuskin mahdollista tehdä tiedonhakua muutenkaan, se on yhdistettävä siihen minkä vastaanotosta ollaan kiinnostuneita.

**Comment by tpalonen** [comment]
Tässä on aivan selvästi kyse kahdesta eri käsitteestä: 1) suhtautumisesta johonkin uuteen ilmiöön ja 2) tavaran, henkilöiden tms vastaanottamisesta. Kielitoimiston sanakirjan ratkaisu on tässä kohtaa epätarkka. Kannatan jaon säilyttämistä. Lisäksi en asetu vastustamaan, jos vastaanottotoiminta päätetään poistaa tai lisätä ohjaustermiksi fyysiselle vastaanotolle.

**Comment by mirmaid** [comment]
**Jos jako on säilytettävä, edelleen ehdotan**

_vastaanotto (reseptio)_
_vastaanotto (logistiikka)_ tai _tavaran vastaanotto_
_vastaanotto (maahanmuuttajat)_

Lisäksi _vastaanottotoiminta_ kera määritelmän.

**Comment by AuHo22** [comment]
Mihinkä näistä siis laitetaan hotelli- ja ravintola-opiskelijoiden eli tulevien "aulapalvelijoiden vastaanottotoiminta" hotellin respassa/receptionissa?
Ja vastaanottotoiminnalla googlaamalla saa kyllä juuri näitä sosiaali- ja terveyspalvelujen vastaanottomahdollisuuksia..
http://www.migri.fi/turvapaikka_suomesta/vastaanottotoiminta

Selkeytyykö ylipäätään jakamalla?

**Comment by YSA-kokous** [comment]
tavaran vastaanotto
reseptio KT vastaanotto (suhtautuminen)
vastaanottotoiminta

Jää vielä avoimeksi, tarvitaanko lisäksi ihmisten vastaanottoa varten jokin termi.

**Comment by mirmaid** [comment]
Vastaanottotoiminta:
_Toimintaa, jossa terveydenhuollon, sosiaalityön tms. asiantuntijat/työntekijät ottavat vastaan asiakkaita._

**Comment by YSA-kokous** [comment]
Toimintaa, jossa terveydenhuollon, sosiaalityön tms. asiantuntijat ottavat vastaan asiakkaita.
