### ISSUE TITLE
varusteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4790]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[varusteet](http://www.yso.fi/onto/ysa/Y104819) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Voisiko lisätä tämän päätermin hierarkiaan "retkeilyvarusteet" ja ehkä jotkut muutkin varusteet? 

#### Ehdottaja   

Pirkko Onnela 

#### Ehdottajan organisaatio   

Lahden ammattikorkeakoulu 

#### Ehdottajan sähköpostiosoite   

pirkko.onnela@lamk.fi 

#### Perustelut ehdotukselle   

Samaa voisi ajatella "tarvikkeet" -yleistermin kanssa?

**Comment by mirmaid** [comment]
Lisätty ST retkeilyvarusteet ja turvavarusteet
