### ISSUE TITLE
uurnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4791]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uurnat](http://www.yso.fi/onto/ysa/Y159280) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

Korvattuina termeinä melko erityyppisiä: hautauurnat, tuhkauurnat, vaaliuurnat, äänestysuurnat. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindassa vain muutamia viitteitä, 3 kertaa tuhkauurna (2 näistä ysa-temejä), kerran "house urn", ilmeisesti tämäkin on ollut hautauurna. 

MAO/TAOssa on _tuhkauurnat_. 

Muutetaan muotoon _tuhkauurnat_, tai poistetaan KT vaaliuurnat ja äänestysuurnat, vaihdetaan ryhmäksi 50 ja 53 mutta jätetään termi ennalleen?

**Comment by mariaforsen** [comment]
Vaaliuurnat ja äänestysuurnat ovat mielestäni ihan eri asia, eli ne voisi poistaa kokonaan, mutta muuten kannatan nykyistä muotoa "uurnat".

**Comment by YSA-kokous** [comment]
poistetaan KT vaaliuurnat ja äänestysuurnat, vaihdetaan ryhmäksi 50 ja 53 mutta jätetään termi ennalleen
