### ISSUE TITLE
ohjaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4792]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ohjaajat](http://www.yso.fi/onto/ysa/Y101182) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Ruotsiksi on aivan eri termi elokuva/teatteri-merkitykselle (regissörer). Ongelma on että ruotsiksi ovat sekä handledare (KT instruktörer) että regissörer tosi tärkeitä termejä (vrt. eng. directors vs. instructors). 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/587

**Comment by LeKorsu** [comment]
Yksi ehdotus.  Voiko laittaa ja tarkenteen? Tulisi samalla huomioitua myös televisio-ohjaajat, jotka myös ovat regissörejä ruotsiksi
ohjaajat (taiteet ja media)
ohjaajat (kouluttaminen)

**Comment by mariaforsen** [comment]
Myös JUHO-työssä odotetaan nyt vastausta tähän (siellä taas kuulemma käytössä eniten handledare/kouluttaminen-merkityksessä, toisin kuin nyt ALLFOssa). Jaon tarpeellisuus ilmeinen.

**Comment by OutiHintikka** [comment]
lisäksi elokuvaohjaajat/teatteriohjaajat. toivottavasti säilyvät.

**Comment by mirmaid** [comment]
Jako on ok, mutta _kouluttaminen_ ei ole tarkenteena kaikissa tapauksissa toimiva, esim. kehitysvammatyössä, kerhotoiminnassa tai varhaiskasvatuksessa koulutus tuntuu liian "painavalta". Käytetty muuten myös koiran ohjaajasta (joka varmaan kyllä nimenomaan kouluttaa).

**Comment by asormune** [comment]
Koiraa koulutetaan (tottelevaisuuskoulutus, agility jne.), mutta kun näissä lajeissa kilpaillaan, ihminen on silloin ohjaaja.

**Comment by OutiHintikka** [comment]
Onko tarvetta näin tarkalle määrittelylle. Eikö koiran "ohjaaja"  ole enemminkin (koiran) kouluttaja.


/outi h


________________________________
Lähettäjä: asormune <notifications@github.com>
Lähetetty: 16. toukokuuta 2017 15:59
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] ohjaajat (#4792)


Koiraa koulutetaan (tottelevaisuuskoulutus, agility jne.), mutta kun näissä lajeissa kilpaillaan, ihminen on silloin ohjaaja.

**Comment by mirmaid** [comment]
Koirat eivät aiheuta tässä ongelmaa, vaan se että kaikissa tapauksissa, joissa on kyse "handledare"-ohjaajista kouluttaminen ei ole hyvä sulkutarkenne, koska ohjaaja ei pyri varsinaisesti kouluttamaan ohjattavia. Handleda=ohjata, opastaa.

**Comment by mirmaid** [comment]
(taiteet ja media) on melko toimiva tarkenne, vaikka esim. teatteri-ilmaisun ohjaaja olisi handledare (oik. instruktör) (merkitykset eivät ole lopulta kauhean kaukana toisistaan). Toisellekin merkitykselle voisi toimia jokin vastaavanlainen yhdistelmätarkenne (kasvatus ja opastus tms.). 

Toisaalta voisi ehkä ajatella että regissör on alakäsite handledare-ohjaajalle, ja yrittää ohjata käyttämään tarkempia termejä?

**Comment by satuniininen** [comment]
Kannatan seuraavaa: 

ohjaajat (taiteet ja media)
ohjaajat (kasvatus ja opastus)

**Comment by mariaforsen** [comment]
Nämä yllä olevat olisi sitten "regissörer" ja "handledare", eli varmaan ihan ok ratkaisu.  Vaikka toki taide- tai media-alallakin voi olla ohjaajia kasvatus- ja opastus-merkityksessä, joten toivottavasti kuvailijat ymmärtävät tarkenteiden tarkoitus. Olisi varmaan hyvä lisätä huomautuskin.

**Comment by YSA-kokous** [comment]
ohjaajat (taiteet ja media)
ohjaajat (kasvatus ja opastus)

Yritetään tehdä määritelmät.

**Comment by mirmaid** [comment]
**ohjaajat (taiteet ja media)**

Uusi mediasanasto: _1) Radio- tai tv-toimituksen jäsen, jonka tehtävänä on johtaa ja koordinoida suoraa tai nauhoitettavaa ohjelmatyötä sovittamalla yhteen ohjelman eri vaiheet. 2) Elokuva- tai tv-tuotannon taiteellisesta kokonaisuudesta (rooleista, kuvatuista kohtauksista, kuvakoosteista, esittämisestä) vastaava henkilö._

Wikipedia: _Ohjaaja on henkilö, jolla useamman ihmisen tuottamassa taiteellisessa tuotannossa viime kädessä on vastuu ja valta teoksen taiteellisista puolista.
Pääosa ohjaajista työskentelee joko elokuvaohjaajina tai teatteriohjaajina, mutta myös kuunnelmilla, televisio-ohjelmilla jne. on ohjaajansa. Ohjaajan työ on useimmiten urakkaluontoista, sillä on harvinaista, että ohjaaja saa vakituisen kiinnityksen yhteen työpaikkaan.
Televisio- ja radiotoimituksissa ohjaajan tehtävä on johtaa ja koordinoida suoran tai nauhoitettavan ohjelman tekoa, kuten sovittaa yhteen ohjelman eri vaiheet._

YSA: _Taiteellisessa tai mediatuotannossa esitys- tai ohjelmakokonaisuudesta vastaava henkilö._ - onko ok? Huom. yläkäsite on nyt _taiteilijat_. Onko tämä liian suppea, jos ei ole sopiva sulkutarkenteeksi?

> yläkäsite muutettava

**Comment by mirmaid** [comment]
**ohjaajat (kasvatus ja opastus)**

Kielitoimiston sanakirja: ohjata: _saattaa jk ohjeilla sujumaan halutulla tavalla, opastaa, neuvoa, johtaa._

Ehdotus: _Henkilö, joka neuvoo, opastaa ja avustaa toista henkilöä tai ryhmää jossakin toiminnassa._ (Ohjaaja voi myös käytännössä suunnitella, kehittää, tai muuten tuottaa tällaista palvelua, mutta onko se huomioitava määritelmässä - vähän vaikea muotoilla rajaamatta mitenkään - "suunnittelee ja kehittää toimintaa jossa ohjataan henkilöä tai ryhmää"...)
