### ISSUE TITLE
agentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4794]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[agentit](http://www.yso.fi/onto/ysa/Y110494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu jakoa/ohjaustermejä 

#### Perustelut ehdotukselle   

Kieliopillisena olisi varmaan agentti yksikössä? Asiamiehet jo on, joten tarvitaanko siinä merkityksessä tätä, vai voisiko lisätä siihen KT:ksi agentit (asiamiehet) tms.? Käytetty Melindassa eniten salaisina agentteina jne. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa on _agentiivisuus (kielitiede)_, eikä Melindassa näyttäisi myöskään käytetyn _agentit_-termiä kielitieteen aineistossa.

LCSH: Secret agents USE Spies
YSAssa toki myös _vakoilijat_

agentit (asiamiehet) KÄ _asiamiehet_ on ok, mutta voiko asiamiehet-termiä käyttää liiketalouden yhteydessä? Liiketaloustieteessä agentti on toimeksiantajan päämiehen kaupallinen edustaja, joka palkkiosta toimii tämän laskuun. https://fi.wikipedia.org/wiki/Agentti

Melindassa on runsaasti liiketaloustieteen ja tietotekniikan aineistoa, jonka kuvailussa käytetty _agentit_-termiä.

**Comment by mirmaid** [comment]
Taloussanasto: agentti: 1. asiamies, toimeksiantajan laskuun toimiva henkilö. Kauppa-agentti on itsenäisesti, mutta päämiehensä nimissä toimiva myyntiedustaja. 2. lainasyndikaatin jäsen, jonka tehtävänä on yleensä osallistua lainaneuvotteluihin ja laatia lainasopimus lainanantajien puolesta. 3. kansantaloustieteen sopimusteoriassa työntekijä, joka voi olla joko yksityishenkilö tai yritys.

YSAssa on _myyntiedustajat_.

**Comment by ilona-x** [comment]
Ainakin osaan tietotekniikan aineistoon näyttäisi sopivan YSA:sta löytyvä termi älykkäät agentit

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/Oikeustiede:kauppaedustaja
YSA: kauppaedustajat KÄYTÄ myyntiedustajat

EKS 
Asiasana: **kauppaedustaja** 
Korvaa termin: agentti, kauppa-agentti, myyntimies
Katso myös: asiamies

LCSH http://id.loc.gov/authorities/subjects/sh85028909
**Commercial agents**

**Comment by mirmaid** [comment]
agentit (vakoilijat), salaiset agentit KÄ _vakoilijat_
agentit (asiamiehet) KÄ _asiamiehet_
agentit (myyntiedustajat), kauppa-agentit KÄ _myyntiedustajat_ (tai vaihdetaan kauppaedustajat, jos se on parempi) - tässä varmistettava että on kaikissa tapauksissa oikea termi

**Comment by mirmaid** [comment]
myyntiedustajat vai kauppaedustajat?

**Comment by jarmosaarikko** [comment]
### muutosehdotus käsitteeseen "agentit"
- poistetaan assosiatiivinen käsite "**kaksoisagentit**". 
- kaksoisagentit vain **vakoilijat**  käsitteen alakäsitteeksi. 

###  _muutosagentit_
Aikasemmin ehdotettu: **Muutosagentit** - #1893  voisi nyt lisätä tähän _agenttikokoelmaan_
Yläkäsite epäselvä.

### _älykkäät agentit_ tarvitsee yläkäsitteen.  
Käykö esimerkiksi  _agentit (tietokoneohjelmat)_  ?
Ellei väliporrasta tarvita, niin tämän voisi siirtää suoraan tietokoneohjelmien alakäsitteeksi.
Esimerkiksi "intelligent agents", "agent-based dss" [https://fennica.linneanet.fi/vwebv/holdingsInfo?searchId=1955&recCount=10&recPointer=5&bibId=955531]

Tietokoneohjelmat yläkäsitteenä tukee ehkä seuraava määritelmä Heli Helaakosken väitöskirjasta "_Agents are autonomous, problem-solving **computational entities** capable of effective operation in dynamic and open environments, and they are therefore able to provide a suitable solution for complex process management among networked companies._ "

### Lisätään _agenttiteoria_  RT _asiamehet_


MOT tarjoaa "agent" termille seuraavia käännöksiä:
1. edustaja, kauppaedustaja, agentti
2. asiamies, välittäjä, kaupanvälittäjä, meklari
3. sijaisvaltuutettu, toimitsija
4. aine, vaikute
5. _bet_ lisäaine
6. keino, väline
7. vaikuttava voima, syy
8. _työs_ agenssi

Jos vielä jää agentti-termillä kuvauksia, jotka eivät sovi mihinkään noista yllä mainituista, niin jäljelle jäävälle agentit-käsitteelle olisi ehkä hyvä lisätä **skos:scopeNote** -kenttä, jossa ilmaistaan rajaus mitä tässä kohtaa agenteilla tarkoitetaan.

**Comment by jarmosaarikko** [comment]
kielitieteen "_agentit_"  löytyy yksi julkaisu Melindasta.     002732457
https://melinda.kansalliskirjasto.fi/F/YJMNDJYQ6YFFSQ48BASLC88QIDJG1GF5KTGYHHDQV6UESFJ8BV-02432?func=full-set-set&set_number=021284&set_entry=000001&format=999

Tieteen termipankin mukaan synonyymi olisi "**tekijä**", mutta sitäkään ei löydy YSA:sta.
http://tieteentermipankki.fi/wiki/Kielitiede:agentti

**Comment by jarmosaarikko** [comment]
minä toiminkin juuri noin eli vaihdoin termin tuohon muotoon, niin sain agentit käsiteltyä loppuun.  (Lisäsin agentit 653 -kenttään ... )

**Comment by mirmaid** [comment]
Vielä ratkaistava:

- myyntiedustajat vai kauppaedustajat

- Melindassa on nyt korjattu kaikki, paitsi uusia Artosta tulleita (95) - poistetaan YSAsta?

Jarmon ehdotuksiin edellä: älykkäät agentit LT on jo YSOssa, agenttiteoria RT ei sovi.

**Comment by YSA-kokous** [comment]
myyntiedustajat KT kauppaedustajat
poistetaan agentit
