### ISSUE TITLE
äänikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4795]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänikirjat](http://www.yso.fi/onto/ysa/Y104936) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutosehdotus: Talbok=lukemisesteisten äänikirjat ja ljudbok=äänikirjat. Lukemisesteisten äänikirjat -käsitteen yläkäsitteeksi äänikirjat. 

#### Perustelut ehdotukselle   

Ruotsiksi on eri sanoja: talbok lukemisesteisille ja ljudbok kenelle tahansa. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/592

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/4859

**Comment by mariaforsen** [comment]
DAISY-formaatti on yleisin Ruotsissa ja Suomessa? Ei tosin ole yhtä kuin talbok, vaan näiden yksi formaatti. 

Celia käyttää tietty vain termiä "talbok", joten eniten huolestuttaa näiden tahojen reaktio jos poistetaan talbok sanastosta (tai ei se ole oikeastaan varmaan mahdollista poistaa, mutta jos joskus jäisi pois..) Tosin ei voida myöskään poistaa "ljudbok", koska se on nykyään erittäin yleinen asia ja entistä suositumpi tavallisten esim. kirjastoasiakkaiden palvelu.

**Comment by mirmaid** [comment]
Hyväksytty lukemisesteisten äänikirjat LT äänikirjat (YSA-kokous 7.3.2017).
