### ISSUE TITLE
alistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4796]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[alistus](http://www.yso.fi/onto/ysa/Y110767) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

YSOssa alistus (vallan alaisuuteen): muutetaan sulkutarkenteeksi vallankäyttö? Alistus (ratkaistavaksi): kysytään vielä selvennystä. Myös alistus (kielitiede). 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/609

**Comment by mariaforsen** [comment]
Onko alistus (kielitiede) siis "syntaktisen kytkennän tyyppi, jossa kielellinen yksikkö - tyypillisimmin lause - on toisen osa ja siitä riippuvainen" kuten TEPAssa alistus; subordinaatio, eng. subordination ?

**Comment by mirmaid** [comment]
Ehdotus:
alistus (kielitiede)
alistus (vallankäyttö)
alistusmenettely KT alistamismenettely

**Comment by YSA-kokous** [comment]
alistus (kielitiede)
alistus (vallankäyttö)
alistusmenettely KT alistamismenettely

**Comment by mariaforsen** [comment]
Sv. 
-underordning (grammatik) ET subordination (grammatik)
-underkuvning
-underställningsförfarande
