### ISSUE TITLE
afrikansiili

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4797]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

afrikansiili 

#### Ehdotettu termi englanniksi   

Four-Toed Hedgehog 

#### Ehdotettu yläkäsite YSOssa (LT)   

[siilit (heimo)](http://www.yso.fi/onto/yso/p15735) 

#### exactMatch   

LCSH : African pygmy hedgehog 
Laji.fi : https://laji.fi/taksoni/MX.44983?locale=fi#show 

#### Vaihtoehtoiset termit ja ilmaisut   

Atelerix albiventris, nelivarvassiili, kääpiösiili, afrikkalainen kääpiösiili, valkovatsasiili, pygmisiili 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Lemmikkeläin; Google: kääpiösiili - 6000 osumaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

opinnäyte: Afrikkalaisen kääpiösiilin terveyden- ja sairaanhoito-opas (2008) 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [afrikansiili](http://finto.fi/yse/fi/page/Y504797)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
