### ISSUE TITLE
Bengali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4798]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Bengali 

#### Ehdotettu termi englanniksi   

Bengal 

#### Ehdotettu termi ruotsiksi   

Bengalen 

#### exactMatch   

LCSH : Bengal (India) 
Suomenkielinen Wikipedia : Bengali (alue) 

#### Vaihtoehtoiset termit ja ilmaisut   

Bengalin alue 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Bengali theatre / Kironmoy Raha 

#### Tarkoitusta täsmentävä selite   

Termillä tarkoitetaan Bengalin aluetta, joka vuonna 1947 jakaantui Bangladeshille (Itä-Bengali) ja Intialle (Länsi-Bengali) kuuluviin osiin. 

#### Perustelut ehdotukselle   

Tällä hetkellä Ysassa ei ole auktorisoitua täsmällistä termiä, jolla kuvailla Bengalia, ei sen enempää kokonaisena kuin osana Bangladeshia ja Intiaa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Bengali](http://finto.fi/yse/fi/page/Y504798)

**Comment by mirmaid** [comment]
YSAssa on sentään Länsi-Bengali (LT Intia). Tässä ilmeisesti kaivataan termiä jolla viitata alueeseen ennen jakoa Itä- ja Länsi-Bengaliin (tai ehkä epämääräisemmin sen jälkeenkin)...hankalaa vähän sikäli, että _Bengali_ ei oikein viittaa selkeästi mihinkään tiettyyn historialliseen hallintoalueeseen, LCSH:n Bengal (India) kai Brittiläisen Intian provinssiin. Haittaako?

**Comment by mirmaid** [comment]
SAO: Bengalen: Historiskt landområde i norra delen av Indiska halvön, i dag delat mellan den indiska delstaten Västbengalen och Bangladesh. Tidigare även Bengalen - Indien med SAB-kod Nobbbz och Bengalen - Bangladesh med SAB-kod Nobaz. Ändrat 2005-02-10.

Facta: entinen brittiläisen Intian maakunta Bengalinlahden perukassa

Wikipedia: 

- Bengalen var den största och folkrikaste provinsen i Brittiska Indien.

- Bengali on alue Aasiassa, Intian niemimaan koillispuolella. Se jakautuu nykyisin lähinnä Bangladeshin valtioon (entinen Itä-Bengali) ja Intian Länsi-Bengalin osavaltioon, mutta pieniä osia historiallisesta Bengalista kuuluu muihinkin Intian osavaltioihin. 

- Bengal is a region in Asia which is located in the eastern part of the Indian subcontinent at the apex of the Bay of Bengal. -- Bengal has played a major role in the history of Asia. In antiquity, its kingdoms were known as seafaring nations. At times an independent regional empire, or a bastion of larger empires, the historical region was a leading power of the Indian subcontinent and the Islamic East.

**Comment by mirmaid** [comment]
Eli: _Alue Bengalinlahden pohjukassa. Nykyään Bengali jakaantuu hallinnollisesti Bangladeshin valtioon ja Intian Länsi-Bengalin osavaltioon. Aikaisemmin brittiläisen Intian provinssi (1757-1947),  sitä ennen osa Suurmogulien valtakuntaa, 1352-1576 itsenäinen sulttaanikunta. Nykyisen Bangladeshin alue oli vuosina 1947-1971 osa Pakistania ensin nimellä Itä-Bengali, myöhemmin Itä-Pakistan._

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
Bengalen
