### ISSUE TITLE
lopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4799]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lopetus](http://www.yso.fi/onto/ysa/Y111408) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ lopettaminen? 

#### Perustelut ehdotukselle   

Ainakin joissakin yhteyksissä luontevampi muoto. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by LeKorsu** [comment]
Urheilijoita ja urheilu-uraa käsittelevissä artikkeleissa lopettaminen kuulostaa huomattavasti paremmalta kuin lopetus, ja olen lopettamista kaivannutkin. Kannatan muutosta.

**Comment by PaiviLipsanen** [comment]
Tätä oli ehdottanut Anne Uusitalo Viikistä eläinlääketieellisessä merkityksessä - eläinten lopetus - mikä on eri asia kuin esim. teurastus

**Comment by mirmaid** [comment]
Ks. #4781

**Comment by mirmaid** [comment]
Lopettaminen voi tarkoittaa myös eläimen lopetusta, mutta riittäisikö kuitenkin lopettaminen (eläimen) KÄ lopetus (tai mikä termiksi sitten tuleekaan), olisi helpompaa jos tälle ei tarvittaisi sulkutarkennetta.

Jos tarkenne on pakko olla, se olisi mahdollisesti (toiminnan). Siinä tapauksessa kannattasi ehkä ottaa erikseen tupakoinnin lopettaminen, koska toiminnan lopettaminen kuulostaa ehkä oudolta niissä?

**Comment by PaiviLipsanen** [comment]
Lopetus on sopii merkitykseen eläinten lopetus

**Comment by mariaforsen** [comment]
Huom. myös vaihtoehto "eläineutanasia" joka on MESHissä pääterminä.

**Comment by mirmaid** [comment]
Hyväksytty lopetus (toiminnan) KÄ lopettaminen (YSA-kokous 7.3.2017).

**Comment by mirmaid** [comment]
Entä tupakoinnin lopettaminen?
