### ISSUE TITLE
toimistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4800]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toimistot](http://www.yso.fi/onto/ysa/Y99573) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö jakaa: toimistot (tilat), ruots. kontorer ja toimistot (organisaatiot), ruots. byråer 

#### Perustelut ehdotukselle   

Ruotsiksi kaksi eri termiä. vrt. kuitenkin myös virastot (ämbetsverk, bureaus) 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa on myös _toimitilat_, sv. verksamhetslokaler ja _työtilat_. Toisaalta kontorer ei myöskään taida tarkoittaa pelkästään tiloja vaan myös toimipistettä (organisaationa).

Ehkä toimistot (tilat) KÄ toimitilat?

**Comment by mariaforsen** [comment]
Näin on, kontor voi olla enemmän kuin pelkkä tila, samalla tavalla kuin suomeksikin, ks. Nationalencyklopedin. Ei erityistä syytä ruotsin takia jakaa, mutta jos halutaan myös suomeksi rajata/jakaa niin on ok. Termin byrå lisääminen ei sinänsä ratkaise ongelma ruotsiksi (vaan lähinnä hankaloittaa). 

Allärsissa on kontor=toimipaikat, mutta YSOssa on korjattu paremmaksi: kontor=toimistot (ja verksamhetsställen=toimipaikat). Toimitilat=verksamhetslokaler.

**Comment by YSA-kokous** [comment]
toimistot (tilat) KÄ toimitilat

**Comment by mirmaid** [comment]
Ohjaustermi ei ole estänyt toimistot-käsitteen käyttöä tiloista. Poistetaanko ohjaustermi? Toimistot-käsitteen yläkäsitteena on siis sekä organisaatiot, että tilat.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan ohjaustermi.
