### ISSUE TITLE
rukous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4801]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rukous](http://www.yso.fi/onto/ysa/Y98633) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ rukoileminen 

#### Perustelut ehdotukselle   

Nyt sanastossa rukous yksikössä ja monikossa, ero mahdollisesti vaikea hahmottaa. YSOssa rukous (toiminta). 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
bedjande, bön ANV bön (bedjande)
