### ISSUE TITLE
tuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4802]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tuvat](http://www.yso.fi/onto/ysa/Y113318) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Merkitys tarkennettava tai jaettava. 

#### Perustelut ehdotukselle   

Ruotsiksi kaksi vastinetta, storstugor (huone) ja stugor (mökki, pieni talo). Tietotuvat ei sovi kummankaan alakäsitteeksi. MAOssa tuvat (huoneet). 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty jonkin verran Artossa kaikissa Kielitoimiston sanakirjan mainitsemissa merkityksissä. YSAssa on _autiotuvat_ ja _kirkkotuvat_, sekä savutuvat KÄ _savupirtit_.

Tuvat (huoneet) ok, toinen voisi olla (rakennukset) mutta tarvitaanko? Kerran Melindassa. YSAssa on myös _retkeilymajat_ ja _ulkoilumajat_. http://www.luontoon.fi/tuvat

**Comment by mariaforsen** [comment]
Stugor (tuvat (rakennukset)) on ainakin ruotsiksi tärkeä termi ja rakennus-merkityksessä näyttääkin olevan aika paljon käytetty Melindassa. Esim. http://linda.linneanet.fi/F/7MBJAA19VAUTURM5YMSU4YQ7IH69UD6NSM1VLK957X7NMTM9V8-15462?func=full-set-set&set_number=160237&set_entry=000022&format=999

**Comment by mirmaid** [comment]
Aika monta kertaa käytetty kansasta, joka YSAssa _tuvalaiset_. Rakennus-merkitystä oli enemmän kuin kerran (en tiedä miksi sain ensin vain yhden viitteen), mutta ei kovin montaa kuitenkaan. Epäilyttää vain kun merkitys on aika epämääräinen, ja suomeksi on myös mökki-sana, jota jossain yhteydessä voi käyttää ristiin tuvan kanssa mutta ei aina.

**Comment by LeKorsu** [comment]
Jos tuvat (rakennukset) KÄYTÄ mökit ei hyvä, niin sitten tuvat (rakennukset). Tuvat (huoneet) ok.

**Comment by mariaforsen** [comment]
Mutta eihän YSAssa ole "mökit" -sanaa. Ruotsin osalta ei ole mitään väliä onko suomenkielinen sana mökit vai tuvat, kunhan yksi niistä on mukana. Kesämökit on eri asia.

**Comment by mirmaid** [comment]
Ei YSAssa, mutta stuga ei välttämättä aina olisi suomeksi tupa, vaan toisinaan mökki? Tupa on mielestäni nykykielessä lähinnä retkeilymaja-tyyppinen rakennus.

**Comment by mariaforsen** [comment]
Ruotsin osalta käy yhtä hyvin mökit KT tuvat kuin tuvat KT mökit. Mutta joo, kaikkiin tapauksiin harvemmin sopii mikään vastine.

**Comment by mirmaid** [comment]
Hyväksytty tuvat (huoneet) ja tuvat (rakennukset) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
storstugor 
stugor
