### ISSUE TITLE
lapsikeskeisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4803]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lapsikeskeisyys](http://www.yso.fi/onto/ysa/Y109608) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ lapsilähtöisyys tai toisin päin. 

#### Perustelut ehdotukselle   

Ruotsiksi lapsilähtöisyys nyt barnperspektiv, lapsinäkökulma, joka vars. kaunokirjallisuudessa eri asia (ja Kaunokissa omana terminään). Barncentrering olisi lähempänä? Onko termeillä suomeksikaan merkityseroa? 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ks. myös #2432

**Comment by mirmaid** [comment]
Melindassa _lapsikeskeisyys_ 370 kertaa, _lapsilähtöisyys_ 85 kertaa, (vain 6 kertaa samassa tietueessa), vuosina 2014-2016 on käytetty termiä lapsikeskeisyys 7 kertaa ja lapsilähtöisyys 34 kertaa.

YSAssa on _asiakaslähtöisyys_, _käyttäjälähtöisyys_, _potilaslähtöisyys_ ja _työelämälähtöisyys_, sekä _perhekeskeisyys_ ja _ratkaisukeskeisyys_.

**Comment by mariaforsen** [comment]
Ruotsiksi tosiaan päällekkäisiä. On ollut Allärs-ongelma alusta asti.

**Comment by LeKorsu** [comment]
Googgelissakin lapsilähtöisyys antaa useamman osuman kuin lapsikeskeisyys.

**Comment by mirmaid** [comment]
Yhdistetään (YSA-kokous 13.12.2016)
