### ISSUE TITLE
vauriot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4804]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vauriot](http://www.yso.fi/onto/ysa/Y104824) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ vahingot jne.? 

#### Perustelut ehdotukselle   

Molemmat ruotsiksi skador. 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
ALLFOn kannalta kannatan yhdistämistä. Ellei haluta yhdistää tarvittaisiin selkeät määritelmät niin että voidaan ruotsiksi luoda tarkenteita (mikä lienee mahdotonta ilman tarkkoja määritelmiä/käyttöhuomautusta).

Kielitoimiston sanakirja:
vaurio: onnettomuuden, sairauden tm. vahingollisen ilmiön aiheuttama vahingoittuma, vioittuma, vamma, rikkouma.
vahinko (ykkösmerkitys):
 jnk tapahtuman, toiminnan tms. jklle t. jllek aiheuttama menetys, tappio, haitta, vaurio tms.

**Comment by mirmaid** [comment]
mahdollisia KÄ vahingot, tuhot (?) - eivät kuitenkaan sovellu esim. lääketieteessä
_Ympäristövauriot_ ohjattiin KÄ _ympäristövahingot, ympäristöhaitat ja ympäristövaikutukset_. Vauriot-termille ohjaus vastaavasti termeihin _haitat_ ja _vaikutukset_ ei ehkä sovellu samalla tavalla.

**Comment by mirmaid** [comment]
Olisikohan helpompi tehdä toisin päin, vahingot KÄ _haitat, tuhot, vauriot, onnettomuudet_?

**Comment by ilona-x** [comment]
Jos tehdään ehdotettu ohjaus vahingot KÄ haitat, tuhot, vauriot, onnettomuudet, pitäisi varmaan ohjata myös YSAsta löytyviin "tarkempiin vahinkoihin"?:
henkilövahingot
liikennevahingot
palovahingot
petovahingot
potilasvahingot
rikosvahingot
satovahingot
sotavahingot
taloudelliset vahingot
tulvavahingot
tuotevahingot
vesivahingot
ympäristövahingot
öljyvahingot

Myös tuhoilla http://finto.fi/ysa/fi/page/Y107572 ja vaurioilla http://finto.fi/ysa/fi/page/Y104824 alakäsitteitä.

**Comment by OutiHintikka** [comment]
Lääketieteen sanastossa:
trauma
vamma, vaurio 1. ulkoisen voiman aiheuttama kudosvaurio; 2. voimakkaan elämyksen aiheuttama henkinen vamma

**Comment by mariaforsen** [comment]
Tämä pitäisi varmaan ratkaista ennen konversiota...

**Comment by mirmaid** [comment]
Ongelmaksi taitaa muodostua se, että skador ei välttämättä ole yhtä konkreettinen kuin vauriot, vaan voisi olla myös laajemmin haitat. 

Allärsissa on _skador (medicin) = vammat_, joten skador kai tarvitsee myös tarkenteen? Tosin tässäkään termien merkitykset eivät ihan vastaa toisiaan, koska kaikki lääketieteelliset vauriot eivät ole vammoja suomeksi (esim. sairauden aiheuttamat vauriot kudoksissa).

**Comment by mirmaid** [comment]
Kommentoitavaksi:
vahingot (onnettomuudet) KÄ onnettomuudet
vahingot (virheet) KÄ virheet
vahingot (haitat) KÄ haitat, vahingot ja vauriot
vauriot KÄ vahingot ja vauriot 
vauriot (lääketiede) KÄ vammat ja vauriot
vammat KÄ vammat ja vauriot
:woman_facepalming:

**Comment by mariaforsen** [comment]
Kyllä, ongelma on monimutkainen, varsinkin kun sanastossa on myös vammat=skador (medicin). Tosin harkitaan viimeksi mainitulle toisia mahdollisia vastineita kuten esim. kroppsliga skador/kroppsskador... Täydellistä vastaavuutta ei varmasti ole saavutettavissa (viitaten haitat-ongelmaan). 

vrt. aivovauriot/vammat (molemmat sanastossa)

**Comment by ilona-x** [comment]
FinMeSH: 
haavat ja vammat http://www.yso.fi/onto/mesh/D014947
sv. sår och skador

**Comment by YSA-kokous** [comment]
vauriot (lääketiede) KÄ vammat
vahingot (onnettomuudet) KÄ onnettomuudet
vahingot (virheet) KÄ virheet
vahingot (haitat) KÄ haitat & vahingot ja vauriot
vauriot KÄ vahingot ja vauriot

**Comment by mariaforsen** [comment]
Sv.
vahingot ja vauriot=skador
vammat=skador (medicin) > kroppsliga skador ET fysiska skador, kroppsskador
