### ISSUE TITLE
murrosikäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4805]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[murrosikäiset](http://www.yso.fi/onto/ysa/Y97542) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ teini-ikäiset 

#### Perustelut ehdotukselle   

Nyt teini-ikäiset KÄ nuoret. Kielitoimiston sanakirjan mukaan teini = murrosikäinen. Kielenkäyttö muuttumassa, murrosikäinen negatiivinen sana? Teini-ikä liittyy vain ikävuosiin, murrosikä kehitysvaiheeseen. 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kaunokki-Bella: teini-ikäiset = tonåringar, murrosikäiset = tonåringar

**Comment by mirmaid** [comment]
Teini-ikäiset 6 kertaa Melindassa ysa-sanana (10 kertaa tietoaineistossa).

**Comment by mariaforsen** [comment]
Ruotsiksi molemmat "tonåringar" (EI pubertetsungdomar).

**Comment by mirmaid** [comment]
Viime vuosina arkipäiväiseen käyttöön yleistynyt teini-ikä vastaa siis jotakuinkin 13–19-vuotiaita (wikipedia). 

Lapset tulevat murrosikään hyvin eri-ikäisinä. Tytöillä murrosikä alkaa keskimäärin 9–12 -vuotiaana, pojilla pari vuotta myöhemmin. (MLL)

murrosikä: noin 11. ja 17. ikävuoden väliin sijoittuva ikävaihe (MOT Lääketiede)

**Comment by mirmaid** [comment]
Sanastoon jäisi siis:

_murrosikä_ KT teini-ikä

_teini-ikäiset_ KT murrosikäiset

**Comment by mariaforsen** [comment]
Eikö murrosikä/puberteetti kuitenkin tarvita erillisenä (melko lääketieteellisenä käsitteenä) ? Näin ainakin ruotsiksi: tonår (teini-ikä): "åldern från 13 till 19 år dvs. den sista tredjedelen av människans uppväxttid med bl.a. puberteten" vs. pubertet: "(tidsperiod under tonåren med) utveckling till könsmognad". Eli ruotsiksi tonår ei ole aivan yhtä kuin pubertet. 

Tonåring on: "pojke eller flicka som är i tonåren", mutta vastaavalla tavalla ei ruotsiksi puhuta "pubertetsungdomar":ista, koska se on yksilöllinen vaihe (ei tule kaikille samassa iässä). Tosin en väitä että välttämättä tarvittaisiin "tonår" erikseen kun on jo "tonåringar".

Vrt. myös MESH murrosikä: http://finto.fi/mesh/sv/page/?clang=fi&uri=D011627

**Comment by mirmaid** [comment]
Jos muutetaan näin, olisi varmaankin syytä lisätä kaikkiin tietueisiin sekä termit _murrosikä_ että _teini-ikäiset_, koska _murrosikäiset_-termillä asiasanoitettu aineisto ei välttämättä käsittele ainoastaan 13-19-vuotiaita. Ratkaisu olisi ehkä muutenkin hyvä, koska yleensä varmaan _murrosikä_ on hyvä hakutermi aina kun puhutaan murrosikäisistä. Nyt kuitenkin suurimmassa osassa aineistoa on vain jompikumpi termi.

**Comment by YSA-kokous** [comment]
murrosikä KT murrosikäiset, teini-ikä
teini-ikäiset KT murrosikäiset

**Comment by mariaforsen** [comment]
Sv. 
-pubertet ET tonår
-tonåringar
