### ISSUE TITLE
sovitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4806]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sovitus](http://www.yso.fi/onto/ysa/Y113416) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsee sulkutarkenteen (koettaminen?). 

#### Perustelut ehdotukselle   

Sanastossa on erikseen sovitus (uskonto) ja sovitus (musiikki) KÄ sovittaminen. Entä merkitys "hyvittäminen"? 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kaunokissa _sovitus (uskonto)_, _sovitus (koettaminen)_ ja sovitus (hyvittäminen) KÄ _hyvittäminen_. (YSAssa ei termiä _hyvittäminen_, käytetty Melindassa tietoaineistossa kerran vapaana asiasanana.)

**Comment by tpalonen** [comment]
YSOssa on aiemmin ollut käsite "sovitus (hyvittäminen)". Tämä päätettiin poistaa, koska katsottiin, että "sovitus (uskonto)" kattaa tämän merkityksen ja sovitus-asiasanan käyttö kuvailussa on liittynyt vaatteiden sovittamiseen. "Sovitus (hyvittäminen)" -käsitteen poistosta on päätetty täällä:
https://github.com/NatLibFi/Finto-data/issues/387

Ks. myös Kielitoimiston sanakirja: 
**sovitus**
sovittaminen; sen tulos. _Ikkunoiden sovitus kehyksiinsä. Piilolasien sovitus. Puvun, kenkien sovitus. Aikataulujen sovitus toisiinsa. Romaanin elokuva-, näytelmäsovitus. Piano-, kuorosovitus._
_Usk._ lunastus, hyvitys. _[Jumala] on lähettänyt Poikansa meidän syntiemme sovitukseksi_ UT.

**Comment by mariaforsen** [comment]
Vaatii kai kuitenkin sulkutarkenteen myös YSAssa?
Nyt siis:
Allärs provning = YSA sovitus 
Allärs arrangering (musik) = YSA sovittaminen

**Comment by mirmaid** [comment]
Hyväksytty sovitus (koettaminen) (YSA-kokous 7.3.2017).
