### ISSUE TITLE
pojat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4807]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pojat](http://www.yso.fi/onto/ysa/Y103971) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Kaksi merkitystä ja ruotsiksi kaksi termiä. Onko "ikäryhmät" hyvä sulkutarkenne? Perheenjäsenet toiselle ok. 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by EsaMPKK** [comment]
On hyvä sulkutarkenne.

**Comment by mariaforsen** [comment]
Allärs: pojkar + söner (=pojat)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
pojkar
söner
