### ISSUE TITLE
tottelevaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4808]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tottelevaisuus](http://www.yso.fi/onto/ysa/Y140874) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ totteleminen 

#### Perustelut ehdotukselle   

Nyt ruots. lydnad, joka Kaunokissa totteleminen. Tottelevaisuus (lydaktighet) päätettiin yhdistää Kaunokissa totteleminen-termiin. 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa 38 kertaa, yleensä koirien koulutuksesta. Koirista ok, ihmisistä käytettynä kuulostaa erikoiselta. Tosin totteleminenkaan ei kuulosta oikein hyvältä...YSAssa on myös _nöyryys_ ja _kuuliaisuus_.

**Comment by AuHo22** [comment]
On ollut aineistossa hyvä termi nimenomaan, kun koirien koulutuksesta on kysymys. Ja sitä kirjaa riittää..

**Comment by mariaforsen** [comment]
Eli tässä ehdotetaan vain uusi korvattu termi: totteleminen? Sitähän ei ole vielä YSAssa ollenkaan (eikä toivottavasti tule erillisenä terminä!). Ruotsiksi on laitettu kuuliaisuus=hörsamhet ja siten ratkaistu synonymiaongelma (sekä tottelevaisuus että kuuliaisuus voidaan kääntää lydnad-termillä). Tottelevaisuus on nyt =lydnad (joka ei tosin välttämättä ole käytetty vain eläinten kohdalla).

**Comment by mirmaid** [comment]
Alkuperäinen ehdotus on että termi _tottelevaisuus_ muutettaisiin muotoon totteleminen. Koiristahan ihan ok termi olisi varmaan myös tottelevaisuuskoulutus?

**Comment by mirmaid** [comment]
Tietoaineisto, jossa aiheena muu kuin koirat:

Kuka on kukkulan kuningas (lasten ja aikuisten väliset valtasuhteet)
Växa - inte lyda (lapset-aikuiset)
Lapsityrannit: kehity kasvattajana
Barnen och livet
Föräldern, barnet och lydnaden
Lär ditt barn att lyda

Sotilaan moraalisuus: kyselytutkimus suomalaisten rauhanturvaajien asenteista käskyjen tottelemiseen
Nation of devils: democratic leadership and the problem of obedience
Obedience to authority (sähköshokkikokeet)
The obedience experiments: a case study of controversy in sociel science
The Lucifer effect: understanding how good people turn evil

Kilttien kapina: tottelemattomuuden alkeet naisille
Ylitunnollisuus: eroon suorittamisen pakosta
Interpretation and obedience: from faithful reading to faithful living (uskonto)

**Comment by mirmaid** [comment]
Eli halutaanko:

1) käyttää yllä mainituissa joko termiä _tottelevaisuus_ tai termiä _totteleminen_
2) käyttää koirien kasvatuksesta termiä _tottelevaisuus_ tai _totteleminen_
3) käyttää koirien kasvatuksesta termiä _tottelevaisuuskoulutus_ ja ihmisistä termejä, _nöyryys, kuuliaisuus, tunnollisuus, kiltteys, auktoriteetti, valta_ jne.

**Comment by LeKorsu** [comment]
Kannatan tuota aloitusta tottelevaisuus KÄ totteleminen.

**Comment by mariaforsen** [comment]
Kannatan minäkin näiden yhdistäminen. 

En kannata jakoa eläin vs. ihminen, eikö ole kuitenkin aika sama asia? Eli että tehdään kuten käsketään/pyydetään. Lydnad-termissä ei ainakaan ole sellaista jakoa, vaan se käy yhtä hyvin ihmisille kuin eläimille. Eikö muuten kuuliaisuus ja tottelevaisuus ole aika lähellä toisiaan?

**Comment by AuHo22** [comment]
Kannatan että otetaan tottelevaisuuskoulutus (ainakin koirille - ja mahdollisesti muille eläimille?) ja sen lisäksi tottelevaisuus KÄ totteleminen, jota voidaan käyttää sitten myös yleisterminä. Tottelevaisuuskoulutus on kuitenkin yleisesti hyväksytty termi koiran koulutuksen yhteydessä - ks. esim. googlaamalla saadut osumat.

**Comment by mirmaid** [comment]
Nyt vasta oikeastaan tajusin tuon kuuliaisuus = hörsamhet. – _Hunden får aldrig morra, eller visa att den är missnöjd med något den blir utsatt för._ Du och jag får protestera, vi får till och med protestera mot polis, politiker, regering. Om en hund vill protestera, då måste den också kunna göra det. Det är upp till dig som hundägare att vara hörsam så att du kan underlätta för hunden. http://blogg.agria.se/fredriksteen/2014/06/03/5-saker-en-del-hundagare-kraver-av-sin-hund-men-som-kan-vara-orimligt-att-krava/

Tässä ei suomeksi voisi mitenkään sanoa että "sinun pitää olla kuuliainen että voit auttaa koiraasi"? Ehkä huomaavainen...koiraa taas voi sanoa kuuliaiseksi, mutta tottelevainen on ilman muuta tavallisempi ilmaus. 

Jos ihminen on kuuliainen, hän noudattaa lakeja, auktoriteettien käskyjä jne., ei protestoi.

**Comment by mariaforsen** [comment]
Ei, yllä olevassa blogipostauksessa on kyllä hyvin "luovasti" käytetty sana hörsam. Se on nimittäin: som villigt utför befallning eller begäran ⟨ngt högt.⟩. Ja kyllä, ihminen joka on "hörsam" ei todellakaan protestoi.

**Comment by mirmaid** [comment]
Eli ratkaisu: tottelevaisuus KÄ _totteleminen_, lisäksi mahdollisesti _tottelevaisuuskoulutus_ (jolla voisi myös olla KT tottelevaisuus).

**Comment by mariaforsen** [comment]
Ok ja lydnadsträning=tottelevaisuuskoulutus myös hyvä.

**Comment by YSA-kokous** [comment]
tottelevaisuus KÄ totteleminen
tottelevaisuuskoulutus

**Comment by mariaforsen** [comment]
Sv. 
-lydnad
-lydnadsträning
