### ISSUE TITLE
kasvu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4809]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kasvu](http://www.yso.fi/onto/ysa/Y95961) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennettava suomeksi. 

#### Perustelut ehdotukselle   

Ruots. tillväxt ei sovellu käytettäväksi ihmisen kasvusta merkityksessä iän karttuminen, aikuistuminen, kehitys (olisi uppväxt). Kaunoon otettu kasvu (ihmisen) = uppväxt (entä ihmisen fyysinen kasvu, onko uppväxt ok?). 

#### Ehdottaja   

Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindan ensimmäiset sata viitettä sisältävät seuraavaa (kasvu NOT henkinen, tietoaineisto):

* kasvu (talous) - YSAssa on jo talouskasvu, mutta kaikkiin ei sovi näin tarkka (ja laaja) termi
    * kasvu (yritykset) - YSAssa on kyllä kasvuyritykset, mutta selkeä tarve on käyttää 	myös kasvu-termiä (tämä on ehkä suurin ryhmä ainakin uudemmassa aineistossa)
    * kasvu (teollisuus)
* kasvu (laajeneminen, esim. kaupungin tai hiukkasten (!))
* kasvu (~aikuistuminen) - YSAssa on henkinen kasvu. Toisinaan ei kyse olekaan aikuistumisesta, vaan ihmisenä kasvamisesta, mutta toisinaan nimenomaan nuoren ihmisen kasvusta. YSAssa on myös aikuistuminen, mutta kasvu-termiä ehkä halutaan mieluummin käyttää esim. varhaisnuoren kasvusta, jolloin ei vielä ihan aikuistuta ("tyttöjen kasvun tukeminen").
* kasvu (biologia, esim. kasvin, mikrobien, eläimen, myös ihmisen fyysinen kasvu, solujen tai kudosten kasvu)

**Comment by mirmaid** [comment]
Käytetty tuhansia kertoja Melindassa, tarkenteiden lisääminen ei varmaankaan mahdollista takautuvasti.

**Comment by mariaforsen** [comment]
Ruotsiksi uppväxt ei kata fyysistä kasvua. Hyvin ongelmallinen termi, koska eri merkityksille eri termejä ruotsiksi. Tillväxt kattaa ehkä parhaiten merkityskenttää, mutta ei sekään kaikkia merkityksiä (esim. ei henkistä).

**Comment by mirmaid** [comment]
Sopiiko tillväxt kun kyseessä on ihmisen fyysinen kasvu, yrityksen kasvu, mikrobien kasvu viljelmässä, syöpäsolujen kasvu, eläimen tai kasvin fyysinen kasvu? @mariaforsen

**Comment by tpalonen** [comment]
Huomautuksena, että kasvu on aiemmin ollut jaettu YSOssa, mutta päätimme käsitejakojen läpikäynnin yhteydessä poistaa kyseisen jaon. Sulkutarkenteet tuolloin olivat "kasvu (luonnontieteellinen muutos)" ja "kasvu (yhteiskunnalliset ilmiöt)", joista edellinen viittasi biologiseen kasvuun ja jälkimmäinen yritysten yms. kasvuun. Päätös jaon poistamisesta löytyy täältä:
https://github.com/NatLibFi/Finto-data/issues/406

**Comment by mariaforsen** [comment]
Tillväxt="ökning i omfattning", mutta käytetään vähän vaihtelevasti eri asiayhteyksissä (/Nationalencyklopedin). On kyllä melko ymmärrettävä "fyysisissä" merkityksissä. Täydellistä ratkaisua ei varmaan ole mahdollista saada ruotsiksi...

**Comment by mirmaid** [comment]
kasvu (henkinen) KÄ henkinen kasvu, aikuistuminen, psyykkinen kehitys

**JA**
kasvu (fyysinen)
kasvu (talous)
**TAI**
kasvu (biologia)
kasvu (talous)
kasvu (laajeneminen)

**Comment by mariaforsen** [comment]
Sanastossa on myös ennestään "talouskasvu" KT taloudellinen kasvu, onko tämä turhan lähellä kasvu (talous)-termiä, vai miten nämä oikeastaan eroavat?

Nykyinen pelkkä tillväxt voi oikeastaan olla parempi kuin "puutteellinen" jako (kuvilijalle tulee vain entistä vaikeampaa valita..)

**Comment by mirmaid** [comment]
Tuolla aiemmassa kommentissa pohdiskelin talous-asiaa, eli talouskasvu ei oikein sovi jos kyse on esim. pienen mittakaavan tapahtumasta.

**Comment by YSA-kokous** [comment]
kasvu (henkinen) KÄ henkinen kasvu, aikuistuminen, psyykkinen kehitys
kasvu jää ilman sulkutarkennetta
