### ISSUE TITLE
ryhmäkoot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4810]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ryhmäkoot 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Tarkoitusta täsmentävä selite   

Sopii myös rymhiin Sosiologia ja Kasvatus 

#### Perustelut ehdotukselle   

Ryhmäkoko on yleisesti tunnettu käsite mm. kouluissa ja päiväkodeissä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/lasten-oikeudet-ja-aikuisten-vastuut-varhaiskasvatuksessa 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [ryhmäkoot](http://finto.fi/yse/fi/page/Y504810)

**Comment by mirmaid** [comment]
Käytetty Melindassa 5 kertaa yksikössä.

**Comment by mirmaid** [comment]
Hyväksytty yksikössä (YSA-kokous 13.12.2016)
