### ISSUE TITLE
huojunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4811]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huojunta](http://www.yso.fi/onto/ysa/Y107518) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite jaettava 

#### Perustelut ehdotukselle   

Huojunta tarkoittaa fysiikassa "kahden taajuudeltaan vain hieman erilaisen aallon välisestä interferenssistä aiheutuva ilmiö." Käsitettä on kuitenkin käytetty Melindassa ihmisen liikkumisen ja nostokurkien yhteydessä, ja näiden lisäksi fysikaalisessa merkityksessä. 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan organisaatio   

ÅA & KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Onko tarkenne (fysiikka) riittävän selkeä? Voisi mahdollisesti olla myös interferenssi, mutta sillä on itsellään sulkutarkenne, haittaako tämä? Ehkä myös huojunta (aaltoliike)?

Ihmisistä voisi käyttää muotoa huojunta (tasapaino). Huojunta (liike) kattaisi niin nostokurjet, ihmiset kuin laivatkin, mutta onko se riittävän erottava toisesta merkityksestä?

**Comment by MikkoAleksanteri** [comment]
> Onko tarkenne (fysiikka) riittävän selkeä? Voisi mahdollisesti olla myös interferenssi

Mielestäni ei ole selkeä, onhan ihmisten ja nostokurkienkien huojuminen "fyysistä" ja fysikaalinen ilmiö. Interferenssi olisi parempi. Mielenkiintoisesti englanninkielisessä wikipedia-artikkelissa tarkenne on (acoustics): https://en.wikipedia.org/wiki/Beat_%28acoustics%29

**Comment by mirmaid** [comment]
Mietinkin tuota akustiikkaa tarkenteeksi, mutta se on suppeampi kuin käsitteen todellinen merkitysalue.

**Comment by tpalonen** [comment]
Kannatan ehdotuksia "huojunta (interferenssi)" ja "huojunta (tasapaino)". Tasapaino on mielestäni intuitiivisempi kuin "huojunta (liike)", ja pitäähän nostokurkien pysyä tasapainossa, joten on ymmärrettävissä myös ihmiskontekstia laajemmin.

**Comment by mirmaid** [comment]
Entä tämä: https://fi.wikipedia.org/wiki/Laiva#Laivan_liikkeet_aallokossa

**Comment by mirmaid** [comment]
Entä huojunta (interferenssi) ja huojunta (liike), jolloin laivatkin olisivat mukana? [Laivan] huojunta, vaaruminen (sway) on edestakaista poikittaista siirtymäliikettä y-akselin suunnassa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
svävning (interferens) http://www.ne.se/uppslagsverk/ordbok/svensk/sv%C3%A4vning https://sv.wikipedia.org/wiki/Sv%C3%A4vning

svajning
