### ISSUE TITLE
pikkelssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4812]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pikkelssit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Perustelut ehdotukselle   

Pikkelssi on yleisesti tunnettu käsite 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/hillokellarin-houkutuksia 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [pikkelssit](http://finto.fi/yse/fi/page/Y504812)

**Comment by mirmaid** [comment]
LCSH:ssa on _Pickles_ ja _Pickled foods_.

Myös muodossa pikkelsi (kerran Melindassa tässä kirjoitusasussa).

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
