### ISSUE TITLE
aitososiaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4813]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aitososiaalisuus 

#### Ehdotettu termi englanniksi   

eusociality 

#### Ehdotettu termi ruotsiksi   

eusocialitet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[biologiset ilmiöt](http://www.yso.fi/onto/yso/p132) 

#### Assosiatiiviset (ST)   

[altruismi](http://www.yso.fi/onto/yso/p5130) 
[yhteiskuntahyönteiset](http://www.yso.fi/onto/yso/p20886) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Aitososiaalisuus 
Tieteen termipankki : <http://www.tieteentermipankki.fi/wiki/Eläintiede:aitososiaalisuus> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

Eläimillä (yhteiskuntahyönteisillä) esiintyvä yhteisöllisyyden muoto, jossa yhteisön jäsenet toimivat täysin altruistisesti yhteisön hyväksi, joko synnyttäen uusia yksilöitä tai huolehtien niiden selviämisestä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-39-6724-6 

#### Perustelut ehdotukselle   

On ollut pitkään tutkimuskohteena sosio- ja evoluutiobiologiassa. 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi **Termiehdotus Fintossa:** [aitososiaalisuus](http://finto.fi/yse/fi/page/Y504813)

**Comment by mirmaid** [comment]
Kerran Melindassa (ko. teos)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
