### ISSUE TITLE
anomia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4815]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[anomia](http://www.yso.fi/onto/ysa/Y100778) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Sanalla on kaksi merkitystä. 1) Nimien muistamattomuus. 2) Sosiologiassa normittomuus 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ehdottaisin 1-merkitykselle termiä _anominen afasia_ (Lääketieteen termit: sanojen löytämisen vaikeus muuten sujuvan ja normaalilta vaikuttavan puheen yhteydessä), vaikka MeSHissä onkin terminä anomia. KT anomia (kielihäiriöt) 

Lisätään _anomialle_ huomautus: Normittomuuden tila, toimintaa ohjaavien normien puuttuminen. Käsitettä on käytetty sekä yhteiskuntatieteellisessä että psykologisessa tutkimuksessa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
anomi 
Tillstånd av regellöshet eller normlöshet. 

anomisk afasi
ordglömska /mesh
ET anomi (ordglömska)
