### ISSUE TITLE
dysfasia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4817]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dysfasia](http://www.yso.fi/onto/ysa/Y108137) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ kielen kehityksen erityisvaikeus (jo YSAssa, termin voisi muuttaa muotoon kielellinen erityisvaikeus) 

#### Perustelut ehdotukselle   

Lääketieteen termit: 1. (laaja merkitys:) aivohäiriöstä johtuva osittainen kyvyttömyys kommunikoida puheen tai kirjoituksen avulla, vaikka aisti- ja lihastoiminnot ja älykkyys voivat olla normaalit; 2. (suppea merkitys:) aivoperäinen kielenkehityksen häiriö; vrt. afasia, dyslogia, puheenkehityksen erityisvaikeus

http://www.laakarilehti.fi/ajassa/ajankohtaista/dysfasia-on-nyt-kielellinen-erityisvaikeus/

http://verneri.net/yleis/dysfasia-kielellinen-erityisvaikeus

https://fi.wikipedia.org/wiki/Dysfasia

http://www.kaypahoito.fi/web/kh/suositukset/suositus;jsessionid=F1DB764DD3283A78C58400460A90D821?id=hoi50085 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Ruotsiksi dysfasi.

**Comment by mirmaid** [comment]
Kielen kehityksen erityisvaikeus on nyt Allärsissa _specifik störning i tal- och språkutvecklingen_

**Comment by mariaforsen** [comment]
Päätermi pitää muuttaa ruotsiksi.

**Comment by mirmaid** [comment]
Hyväksytty yhdistäminen & muutos (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
specifik språkstörning /wp, http://www.nv.fi/sites/nv.fi/files/uploads/documents/nv_esite_svenska_naytto_210214.pdf
ET dysfasi
ET primär språkstörning

eng. https://en.wikipedia.org/wiki/Specific_language_impairment
