### ISSUE TITLE
tietotyyppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4818]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tietotyyppi 

#### Ehdotettu termi ruotsiksi   

datatyp 

#### Ehdotettu termi englanniksi   

data type 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2015001723> 
Wikipedia : https://en.wikipedia.org/wiki/Data_type 
Paikkatieto-ontologia : <http://paikkatiedot.fi/def/1001003/p69> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pierce, Banjamin C.: Types and programming languages 978-0-262-16209-8 

#### Perustelut ehdotukselle   

Ohjelmointiin ja ohjelmointikieliin ilmeisen keskeisesti liittyvä käsite. On jo PTO:ssa, joten helppo lisätä myös YSO:on? 

**Ehdottajan nimi:** Aki Pyykkö 
**Ehdottajan organisaatio:** Turun kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** aki.pyykko@turku.fi **Termiehdotus Fintossa:** [tietotyyppi](http://finto.fi/yse/fi/page/Y504818)

**Comment by mirmaid** [comment]
Melindassa kerran yksikössä, kerran monikossa (+ kerran semanttiset tietotyypit, abstrakti tietotyyppi ja XML-tietotyyppi).

**Comment by mirmaid** [comment]
LCSH: Data types (Computer science)

**Comment by henriyli** [comment]
Keskeinen käsite sekä tietojenkäsittelytieteessä että ohjelmoinnissa. Kannatan otettavaksi sanastoon!

**Comment by mirmaid** [comment]
Hyväksytty monikossa (YSA-kokous 13.12.2016)
