### ISSUE TITLE
leuanveto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4819]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

leuanveto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

Leuanveto on yleinen käsite, myös kilpailulaji 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/tikis 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [leuanveto](http://finto.fi/yse/fi/page/Y504819)

**Comment by mirmaid** [comment]
Ei Melindassa, ei Liikunnan ja urheilun asiasanastossa

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
