### ISSUE TITLE
punnerrus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4820]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

punnerrus 

#### Vaihtoehtoiset termit ja ilmaisut   

etunojapunnerrus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

punnerrus / etunojapunnerrus on yleinen käsite liikunnassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/tikis 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [punnerrus](http://finto.fi/yse/fi/page/Y504820)

**Comment by mirmaid** [comment]
Ei kummassakaan muodossa Melindassa eikä Liikunnan ja urheilun asiasanastossa

**Comment by mariaforsen** [comment]
Ruotsiksi useita mahdollisia vastineita:
MOT:
(voimanponnistus) kraftansträngning [-en,-ar,-arna], ansträngning [-en,-ar,-arna]
2 urh (etunojapunnerrus) armhävning [-en,-ar,-arna]
3 urh (käsivarsipunnerrus) armpress [-en,-ar,-arna]
4 urh (painonnostossa) press [-en,-ar,-arna]

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016) KT etunojapunnerrus
