### ISSUE TITLE
ekotase

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4822]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ekotase](http://www.yso.fi/onto/ysa/Y111785) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tähän termiin korvattu termi: elinkaariarviointi

Tai mahdollisesti korvataan ekotase termillä elinkaariarviointi. 

#### Perustelut ehdotukselle   

Elinkaariarviointi (https://fi.wikipedia.org/wiki/Elinkaariarviointi) on suomennos termille life-cycle assessment.

Samaa/lähes samaa asiaa on kuvattu myös käsitteellä ecobalance = ekotase. Elinkaariarviointi taitaa kuitenkin olla nykyään selvästi käytetympi, ks. esim. http://www.ymparisto.fi/fi-FI/Kulutus_ja_tuotanto/Tuotesuunnittelu_ja_tuotteet/Elinkaariarviointi_jalanjaljet_ja_panostuotosmalli 

#### Ehdottaja   

Matti Rajahonka 

#### Ehdottajan organisaatio   

Jyväskylän yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

matti-petteri.rajahonka@jyu.fi

**Comment by mirmaid** [comment]
Nyt YSAssa elinkaariarviointi KÄ elinkaarianalyysi. 
Wikipedia: Elinkaariarvioinnilla (LCA, Life Cycle Assessment) tarkoitetaan tuotteen tai palvelun sen koko elinkaaren ympäristövaikutuksien tutkimista raaka-aineen hankinnasta tuotteen hylkäämiseen asti.

ekotase KT elinkaari-inventaario: Tarkoittaa tasetta, jossa eritellään tuotteeseen tai toimintaan liittyvät materiaali- ja energiavirrat raaka-aineiden käyttönä ja ympäristövaikutuksina.

Ekotase on yrityksen ympäristökuormituksen mallintamisen työkalu, joka selventää kuvaa yrityksen toiminnassaan kuluttamista luonnonvaroista ja vastaavasti tuotetusta hyödystä ja päästöistä. Ekotasetta voidaan avata ja käyttää esimerkiksi toiminnan sisäisten prosessien määrittämisen apuvälineenä. Myös tuotteen koko elinkaarelle voidaan tehdä ekotase, jolloin siihen on huomioitava valmistuksen lisäksi myös käytön ja käytöstä poistamisen aiheuttamat hyödyt sekä haitat. http://www.garbagex.net/01_jatehuollon_ohjaus/04_05_jatteiden_ehkaisy.html

tase, jossa eritellään tuotteeseen tai toimintaan liittyvät materiaali- ja energiavirrat raaka- aineiden käyttönä ja ympäristövaikutuksina http://lipas.uwasa.fi/termino/WasaTerm/ymparistojohtaminen/ekotase.html

**Comment by mirmaid** [comment]
En yhdistäisi näitä kahta. Sen sijaan elinkaariarviointi on huomattavasti käytetympi kuin elinkaarianalyysi (Google: ~4500/~39000), Melindassa toki 23/452.

**Comment by mariaforsen** [comment]
Molemmat hyvät erillisinä termeinä ruotsiksi.

**Comment by mirmaid** [comment]
Ei yhdistetä, elinkaariarviointi KT elinkaarianalyysi (YSA-kokous 7.3.2017).
