### ISSUE TITLE
PFAS

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4823]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

PFAS 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kemialliset yhdisteet](http://www.yso.fi/onto/yso/p324) 

#### Vaihtoehtoiset termit ja ilmaisut   

per- ja polyfluorialkyyliyhdisteet, PFC (Lyhennettä on aiemmin käytetty tarkoittamaan PFAS- tai PFAA-yhdisteitä. PFC-lyhenteen käyttöä ei suositella, koska sitä on käytetty Kioton sopimuksen dokumenteissa vuodesta 1997 merkityksessä perfluorihiilivedyt (sisältävät vain hiiltä ja fluoria), jotka ovat kasvihuonekaasuja) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Tarkoitusta täsmentävä selite   

Per- ja polyfluorialkyyliyhdisteet: alkyyliyhdisteet, joissa vety on korvattu fluorilla (perfluorialkyyliyhdisteet), sekä sellaiset osittain (poly-) fluoratut yhdisteet, jotka sisältävät vähintään yhden perfluoratun hiilen.
http://www.ymparisto.fi/fi-FI/Kulutus_ja_tuotanto/Kemikaalien_ymparistoriskit/Ymparistoon_paatyvat_haitalliset_aineet/Perfluoratut_yhdisteet -> liite (PFC, ym.) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Perfluoratut yhdisteet ympäristössämme...Vesitalous 2016:5, s.12-16 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [PFAS](http://finto.fi/yse/fi/page/Y504823)

**Comment by mirmaid** [comment]
YSAssa on _perfluoratut alkyyliaineet_, KT PFAS-aineet. Pitäisikö termi muuttaa vai lisätäänkö vain ohjaustermejä?

**Comment by mirmaid** [comment]
ohjaustermiksi
