### ISSUE TITLE
PFC-yhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4824]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[PFC-yhdisteet](http://www.yso.fi/onto/ysa/Y117211) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korvatuksi termiksi -> PFAS 

#### Perustelut ehdotukselle   

Lyhennettä on aiemmin käytetty tarkoittamaan PFAS- tai PFAA-yhdisteitä. PFC-lyhenteen käyttöä ei suositella, koska sitä on käytetty Kioton sopimuksen dokumenteissa vuodesta 1997 merkityksessä perfluorihiilivedyt (sisältävät vain hiiltä ja fluoria), jotka ovat kasvihuonekaasuja. 
http://www.ymparisto.fi/fi-FI/Kulutus_ja_tuotanto/Kemikaalien_ymparistoriskit/Ymparistoon_paatyvat_haitalliset_aineet/Perfluoratut_yhdisteet - Liite 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa PFAS nyt muodossa _perfluoratut alkyyliaineet_.

**Comment by mirmaid** [comment]
Käytetty tämän julkaisun kuvailussa tarkoittamaan perfluorihiilivetyjä: _HFC- ja PFC-yhdisteiden sekä SF6:n päästöjen tekniset vähentämiskeinot ja niiden kustannukset Suomessa_.

**Comment by mirmaid** [comment]
Muutetaan muotoon perfluorihiilivedyt?

**Comment by mariaforsen** [comment]
Allärs: PFAS = perfluoratut alkyyliaineet. Pitää korjata?

**Comment by mirmaid** [comment]
PFC-yhdisteet merkityksessä perfluorihiilivedyt on käsittääkseni oikein, sen sijaan sitä ei saa käyttää merkityksessä PFAS/perfluoratut alkyyliaineet. Toki voidaan vaihtaa päätermiksi perfluorihiilivedyt, jos se selventää.

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 7.3.2017).
