### ISSUE TITLE
jämställdhetsombudsman

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4825]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tasa-arvovaltuutetut 

#### Ehdotettu termi ruotsiksi   

jämställdhetsombudsman 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fullmäktige](http://www.yso.fi/onto/yso/p21148) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

I Allärs har motsvarigheten till "yhdenvertaisuusvaltuutetut" felaktigt varit jämställdhetsombudsmän. Dessa är två olika befattningar. Se t.ex. https://www.tasa-arvo.fi/web/sv och https://www.syrjinta.fi/sv/web/SV/framsida 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tasa-arvolaki 2005 / Tasa-arvoyksikkö ja tasa-arvovaltuutettu 

#### Tarkoitusta täsmentävä selite   

Korrekt form: jämställdhetsombudsmän 

**Ehdottajan nimi:** Allärs 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [jämställdhetsombudsman](http://finto.fi/yse/fi/page/Y504825)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
