### ISSUE TITLE
Scratch

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4826]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Scratch 

#### Ehdotettu termi ruotsiksi   

Scratch 

#### Ehdotettu termi englanniksi   

Scratch 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ohjelmointikielet](http://www.yso.fi/onto/yso/p162) 

#### exactMatch   

Scratch : https://fi.wikipedia.org/wiki/Scratch 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Tarkoitusta täsmentävä selite   

Scratch on lapsille ja nuorille tarkoitettu ohjelmointikieli 

#### Perustelut ehdotukselle   

kuvailen kirjaa jossa esitellään kaksi lapsille sopivaa ohjelmointikieltä: Scratch ja Python 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.amazon.co.uk/Beginners-Guide-Coding-Marc-Scott/dp/1472928644/ref=sr_1_1?s=books&ie=UTF8&qid=1478901247&sr=1-1&keywords=9781472928641 

**Ehdottajan nimi:** Mari Saikkonen 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** mari.saikkonen@btj.fi **Termiehdotus Fintossa:** [Scratch](http://finto.fi/yse/fi/page/Y504826)

**Comment by mirmaid** [comment]
LCSH: Scratch (Computer program language) (Melinda 2 kertaa)

Käytetty Melindassa 3 kertaa + 2 x LC-termi.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
