### ISSUE TITLE
äärioikeisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4827]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äärioikeisto](http://www.yso.fi/onto/ysa/Y210492) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ äärioikeistolaisuus 

#### Perustelut ehdotukselle   

Molempia muotoja käytetty Melindassa. Äärioikeistolaisuus sopisi paremmin oikeistolaisuus-termin ST:ksi ja on helpommin miellettävissä ideologiana. Oikeisto-termiä ei ole sanastossa, vain oikeistoliikkeet ja oikeistopuolueet. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Ruotsiksi högerextremism.

**Comment by mirmaid** [comment]
Vaihdetaan termiksi äärioikeistolaisuus (YSA-kokous 13.12.2016)
