### ISSUE TITLE
rekka-autot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4828]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rekka-autot](http://www.yso.fi/onto/ysa/Y113583) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

kuorma-autot KT rekka-autot 

#### Perustelut ehdotukselle   

Melindassa:
rekka-autot 107 kertaa
kuorma-autot 718 kertaa
molemmat yhdessä 67 kertaa

Voisiko näitä yhdistää toisiinsa? Ovat merkitykseltään paljolti päällekkäisiä ja hankalia kääntää. 

Yleisesti nykyään kai puhutaan kuorma-autoista tai ajoneuvoyhdistelmistä. Ajoneuvolain mukaan kuorma-auto on "tavaran kuljetukseen valmistettu ajoneuvo, jonka kokonaismassa on suurempi kuin 3,5 tonnia". (Alle 3,5 tonniset tavarankuljetusautot määritellään pakettiautoiksi) 

Kielitoimiston mukaan rekka on perävaunullinen kuorma-auto. Toisaalta Wikipedia kertoo: "Vaikka nimitystä rekka käytetään yleiskielessä perävaunullisesta kuorma-autosta tai jopa pelkästä kuorma-autosta, ammattisanastossa rekan merkitys puolestaan vaihtelee sen suppeamman, perinteisen merkityksen ollessa pelkkä puoliperävaunu ja laajemman merkityksen tarkoittaessa puolestaan puoliperävaunun ja kuorma-auton yhdistelmää. Alun perin rekka tarkoitti parireen päälle asetettua irtolavaa, jolla kuljetettiin puutavaraa."

Huom. sama koskee myös käsitteitä rekka-autoliikenne & kuorma-autoliikenne ja kuorma-autonkuljettajat & rekka-autonkuljettajat 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by BTJMariSa** [comment]
Hei!
Kommenttina: kuljetusalalla näillä on hyvinkin selvä ero, ja ammattipätevyys/koulutus/vaatimukset. Kuorma-autoa saa ajaa C-kortilla, kun taas rekka-auton (joka on aina ns. moniosainen) kuljetus vaatii omat korttinsa. Alan ihmisille näiden ero on vastaava kuin henkilöauton ja pakettiauton. Yst. terveisin Mari/BTJ

**Comment by ilona-x** [comment]
http://www.logistiikanmaailma.fi/wiki/Maantiekuljetukset_%E2%80%93_mitat_ja_painot

http://www.logistiikanmaailma.fi/wiki/Maantiekuljetukset_%E2%80%93_kalusto

**Comment by mariaforsen** [comment]
Näitä ei olisi hyvä yhdistää ruotsin kannalta - vaatii kaksi erillistä termiä. (lastbil, långtradare).
