### ISSUE TITLE
vaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4829]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vaasit](http://www.yso.fi/onto/ysa/Y149680) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Merkityksen rajaaminen /sulkutarkenteen lisääminen 

#### Perustelut ehdotukselle   

Vaaseissa huomautus "Tarkoittaa antiikin ajan astioita ja ruukkuja. Materiaalina voi olla kivi, lasi tai savi." Löytyy myös maljakot.

Melindassa käytetty:
vaasit 151
maljakot 42
molemmat yhdessä 11

Olisiko syytä rajata vaasien käyttöä ja merkitystä uudestaan? Ja onko ylipäätään tarpeen luokitella astioita aikakauden mukaan? Jos tarvitaan oma käsite vaaseille historiallisina objekteina (erotuksena maljakoista yleensä) niin rajaus olisi syytä laatia mahdollisimman sallivaksi, jotta se kattaisi useita historiallisia aikakausia/kulttuureita.

Kannattaisin myös sulkutarkennetta ettei käyttö mene kovin hajanaiseksi. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
Antiikin käsikirja: vaasit (lat. vas = astia, kulho). Antiikin maailmassa erimuotoisia astioita ja ruukkuja tehtiin monista materiaaleista, kivestä, metallista, lasista ja varsinkin savesta. Muotonsa perusteella v:t jaetaan avonaisiin muotoihin, joissa oli avara suu, tai kapeasuisiin suljettuihin muotoihin, kuten erilaisiin hajuvoidepulloihin. Käytön mukaan ne ryhmitellään juhla-, kultti- tai käyttöastioihin, ja esim. pöytäastiat edelleen sekoitus-, kaato- ja juoma-astioihin. Muotovalikoima oli laajimmillaan 500- ja 400-luvulla eKr. Attikassa.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Luettelo_kreikkalaisten_maljakoiden_malleista

**Comment by mariaforsen** [comment]
Ruotsiksi ollut pitkään ongelma (maljakot+vaasit=vaser). Sama sana ruotsiksi riippumatta miltä aikakaudelta, tarkka muoto jne. Jos halutaan silti pitää molemmat erillisinä termeinä täytyy lisätä tarkenteita ruotsiksi, ja sitä ei voida tehdä ennen kuin on päätetty miten suomeksi selvennetään termien merkityserot jne.

**Comment by MikkoAleksanteri** [comment]
Jos halutaan pitää vaasien nykyinen merkitys (joka käy ilmi huomautuksesta), olisiko tarpeen lisätä sulkutarkenne, esim. _vaasit (antiikki)_. Ruotsiksi voisi olla myös _vaser (antik)_ tms.

**Comment by mirmaid** [comment]
Oikeasti tuo vaan taitaa olla ketju...:see_no_evil:

**Comment by MikkoAleksanteri** [comment]
> Oikeasti tuo vaan taitaa olla ketju...:see_no_evil:

NOOOUUUuuu! En ehdota ketjua, pois se minusta! :)

**Comment by mirmaid** [comment]
Asiantuntijan palaute: 
"Maljakko assosioituu kukkamaljakkoon, vaasi sen sijaan on suoraan latinasta ja merkitsee mitä tahansa (käyttö, muoto) ruukkua. Ruukku taas on käytössä raskaammasta käyttökeramiikasta, vaasi yleensä hienommasta laadusta. Antiikin ympyröissä käytettiin ehkä joskus vielä 1980-luvun alussa suomeksi tuota kammottavaa maljakkoa, mutta onneksi se on vuosikymmenten uutteran työn jälkeen saatu kitketyksi kokonaan pois." 

Eli ehkä kuitenkin vaasit (antiikki), vaikka se kovin ketjumainen on, jollei jollakulla ole ehdottaa jotain elegantimpaa.

**Comment by mariaforsen** [comment]
Eli vaser (antiken) ja vaser (?), tai vaatii ehkä muodot "antikens vaser" ja "vaser".

**Comment by mirmaid** [comment]
Hyväksytty vaasit (antiikki) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
antikens vaser
vaser (kärl)
