### ISSUE TITLE
suojasää

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4830]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suojasää 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581) 

#### Perustelut ehdotukselle   

käsite Neuvostoliiton historiassa: https://fi.wikipedia.org/wiki/Suojas%C3%A4%C3%A4 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kirjallisuudentutkimus, taiteentukimus, kulttuurihistoria 

**Ehdottajan nimi:** Marja-Leena Kock 
**Ehdottajan sähköpostiosoite:** marja-leena.kock@helsinki.fi **Termiehdotus Fintossa:** [suojasää](http://finto.fi/yse/fi/page/Y504830)

**Comment by mirmaid** [comment]
Käytetty Melindassa 10 kertaa, yleensä ketjuna suojasää -- Neuvostoliitto. Tarvitsee kyllä jonkun tarkenteen.

**Comment by mariaforsen** [comment]
Tarvitsee tarkenteen että saadaan oikea vastine ruotsiksikin.

**Comment by mirmaid** [comment]
Hyväksytty muodossa suojasää (Neuvostoliitto) (YSA-kokous 13.12.2016)

**Comment by OutiHintikka** [comment]
Ei saa yhdistää kirjallisuudentutkimukseen. Termiä toki voi muuten käyttää kirj.tutkimuksen aineistossa.
