### ISSUE TITLE
lentoposti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4832]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lentoposti 

#### Ehdotettu termi englanniksi   

airmail 

#### Ehdotettu termi ruotsiksi   

flygpost 

#### Ehdotettu yläkäsite YSOssa (LT)   

[posti](http://www.yso.fi/onto/yso/p6557) 

#### exactMatch   

WIkipedia : https://en.wikipedia.org/wiki/Airmail 
LCSH : <http://id.loc.gov/authorities/subjects/sh85002667> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lentopostia : posti lentää ajan siivellä 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [lentoposti](http://finto.fi/yse/fi/page/Y504832)

**Comment by LeKorsu** [comment]
Tätä nykyä "hukkaposti" termikin taitaa tulla tarpeeseen =)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
