### ISSUE TITLE
sekularismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4834]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sekularismi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Sekularismi on yleisesti tunnettu käsite uskonnosta eroamiselle. Sekularisaatio (maallistuminen) on laajempi käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/constructing-the-secular-imagined-community 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [sekularismi](http://finto.fi/yse/fi/page/Y504834)

**Comment by mirmaid** [comment]
LCSH:ssa on sekä Secularism, että Secularization (Theology). 

Käytetty 37 kertaa Melindassa.

**Comment by LeKorsu** [comment]
Nyt on ysassa ohjausterminä sekularisaatio > maallistuminen ja maallistumisella 740 viitettä.
Jos sekularismi otetaan uutena, omana terminä, pitäisi kyllä olla selkeä selitys, mitä eroa on sekularismilla ja sekularisaatiolla/maallistumisella.

**Comment by mirmaid** [comment]
Aiheesta mm. http://tuomioja.org/puheet/2008/11/sekulaarin-yhteiskunnan-tulevaisuus/

**Comment by mariaforsen** [comment]
SAOssa sekä sekularism (=inomvärldslig åskådning som utesluter all transcendens) että sekularisering (=processer som innebär att religionen förlorar i betydelse i ett samhälle och i medborgarnas medvetande). Näissä on kyllä merkityseroa, mutta ei välttämättä aina käytetä johdonmukaisesti.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016). Lisätään määritelmä.
