### ISSUE TITLE
muinais-DNA

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4835]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Ancient DNA 

#### Ehdotettu termi suomeksi   

muinais-DNA 

#### Ehdotettu yläkäsite YSOssa (LT)   

[DNA](http://www.yso.fi/onto/yso/p7690) 

#### exactMatch   

https://en.wikipedia.org/wiki/Ancient_DNA : Ancient DNA 
http://id.loc.gov/authorities/subjects/sh92005763.html : DNA, Fossil 

#### Tarkoitusta täsmentävä selite   

Arkeologisista löydöistä eristetty DNA
ks. esim.
http://www.sarks.fi/ap/ap2010/ap2010_06_tourunen_niemi.pdf 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Perustelut ehdotukselle   

SUGRIGE-projekti 
http://blogs.helsinki.fi/paleogenetics/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.nba.fi/fi/File/1140/hautakaivausjulkaisu.pdf 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [muinais-DNA](http://finto.fi/yse/fi/page/Y504835)

**Comment by HanneleD** [comment]
"Muinais-DNA:lla tarkoitetaan sellaista geneettistä materiaalia, joka on säilynyt kuolleessa organismissa tai sen osassa, esimerkiksi arkeologisessa, paleontologisessa tai forensisessa näytteessä. Muinais-DNA -näytteiden ikä vaihtelee noin sadasta vuodesta kymmeniin tuhansiin vuosiin – jopa yli satatuhatta vuotta vanhasta näytteestä on voitu monistaa autenttista DNA:ta. Muinais-DNA eroaa tuoreesta DNA:sta pääasiassa kahdella tavalla. DNA:ta on vanhoissa näytteissä jäljellä vähän ja se on fragmentoitunut pieniksi paloiksi." 
DNA-tutkimuksen huomioiminen arkeologisella kaivauksella ja jälkitöissä / T a r j a S u n d e l l j a M i k k o 
P u t k o n e n (Arkeologisten hautakaivausten tutkimusmenetelmät)

**Comment by mirmaid** [comment]
KT aDNA

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
