### ISSUE TITLE
vieraskielisyys, vieraskieliset [oli: kielet]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4836]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kielet](http://www.yso.fi/onto/ysa/Y96135) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

"vieraat kielet" alakäsitteeksi 

#### Perustelut ehdotukselle   

tarvitaan termiä "vieraat kielet", pelkkä "kielet" ei riitä vrt. esim. kuolleet kielet tai kansalliskielet  myös vieraat kielet - opetus 

#### Ehdottaja   

Marja-Leena Kock, Marina Ivanova, Päivi Pakarinen 

#### Ehdottajan sähköpostiosoite   

marja-leena.kock@helsinki.fi

**Comment by mariaforsen** [comment]
Allärs nyt: främmande språk = vieraskielisyys.  Näin koska vastaavaa muotoa (-yys) ei ole mahdollista luoda ruotsiksi.

**Comment by mirmaid** [comment]
Palaute: Yleisesti kielitieteessä hyödyllinen käsite. Eri asia kuin toinen kieli.

**Comment by mirmaid** [comment]
Tässä on itseasiassa useampia ongelmia. Nyt termit eivät vastaa toisiaan, _vieraskielisyys_ on tietenkin eri asia kuin _vieraat kielet_. Koska ominaisuus-labelia ei löydy ruotsiksi, on varmaan paras ratkaisu yrittää korvata vieraskielisyys-termi tarkemmilla tarpeen mukaan, esim. vieraskielinen väestö (?). Käytetty Melindassa onneksi vain 63 kertaa.

Vieraat kielet viittaa siis (yleensä) nimenomaan kielten opetuksen kontekstissa muihin kuin kotimaisiin kieliin. Olettaisin että yhdistelmä _vieraat kielet + opetus_ viittaisi (yleensä) peruskoulun ja toisen asteen muiden kuin kotimaisten kielten opetukseen, ja _kielet + opetus_ viittaisi mihin tahansa muun kuin äidinkielen opetukseen. 

Myös termiä _kieltenopetus_ on ehdotettu: https://github.com/Finto-ehdotus/YSE/issues/4558, https://github.com/Finto-ehdotus/YSE/issues/1436.

**Comment by mirmaid** [comment]
Tieteen termipankki:
http://tieteentermipankki.fi/wiki/Kielitiede:vieras_kieli
http://tieteentermipankki.fi/wiki/Kielitiede:toinen_kieli

**Comment by mariaforsen** [comment]
Vieraskielinen väestö on myös hankala kääntää lyhyellä vastineella (="befolkning med/som talar främmande språk"), eikä sekään vastaa merkitystä kovin hyvin. Toinen mahdollinen ratkaisu (ikävä sekin) voisi olla "på/med främmande språk", ei mitenkään luonteva ruotsiksi, mutta vaihtoehtoja ei juuri olekaan tässä tapauksessa.

**Comment by mirmaid** [comment]
Ottamalla _vieraat kielet_ olisi siis mahdollista uuden aineiston osalta hakea erikseen muiden kuin kotimaisten kielten opetusta peruskoulussa ja toisen asteen koulutuksessa käsittelevää aineistoa. Takautuva korjaaminen ei ole aineiston suuren määrän takia mahdollista, ja on ehkä mahdollista sekin että joku erehtyy luulemaan ruotsia vieraaksi kieleksi.

**Comment by YSA-kokous** [comment]
Otetaan _vieraat kielet_, lisätään määritelmä.

**Comment by mirmaid** [comment]
_vieraskielisyys_ nyt ruotsiksi _på främmande språk_, mutta toimiiko ratkaisu käytännössä?

**Comment by mariaforsen** [comment]
On ruotsin osalta tietysti ikävä ratkaisu, mutta vaihtoehtoja ei ole jos vieraskielisyys täytyy olla mukana ja jokaisella termillä ruotsinkielinen vastine.

**Comment by jarmosaarikko** [comment]
Olisiko liian radikaalia muuttaa **vieraskielisyys** tämän **vieraat kielet** -käsitteen ohjaustermiksi? Se kun ei tunnu oikein sopivan sen rinnakkaisten käsitteiden joukkoon **kielelliset ominaisuudet** käsitteen alla...

**Comment by vthuhtala** [comment]
Pitäisikö 'kieltenopetus' ehdotus selvittää ensin ja sitten miettiä, mitä nämä kaikki äidinkielet, kielet, vieraat kielet ja toiset kielet oikein tarkoittavat kuvailussa?

**Comment by satuniininen** [comment]
Ehdotan, että korvataan **vieraskielisyys** termillä **vieraskieliset**, joka on käytössä mm. Tilastokeskuksella: https://www.stat.fi/tup/maahanmuutto/maahanmuuttajat-vaestossa/vieraskieliset.html

**Comment by mariaforsen** [comment]
Sv. "personer med/som talar främmande språk (som modersmål)"? Vanha oli myös ikävä, mutta parempi kuin tämä.

**Comment by mirmaid** [comment]
Viitteissä on usein kysymys jostain vieraskielisestä ihmisryhmästä: vieraskieliset potilaat, vieraskieliset asiakkaat, vieraskieliset opiskelijat. Näissä _på främmande språk_ tuskin toimii. Miten nämä ilmaistaisiin sujuvasti ruotsiksi kuvailussa?

**Comment by jarmosaarikko** [comment]
svenska.se ei tunne "främmande språk" ollenkaan?  onko tämä enkuksi "foreign language speakers" tms.?

**Comment by mariaforsen** [comment]
Ruotsiksi käytettäisiin varmaan termejä kuten främmande språk, språkkunskap/färdigheter jne. ja erikseen eri ihmisryhmät (ei nähdä tarvetta liittää sitä vieraskielisyyttä jokaiseen erikseen, kuten ei yleensäkään "liitetä ominaisuuksia kiinteästi" henkilöihin, vrt. esim. erityislapset=barn med särskilda behov, vammaiset jne.) Eli esimerkkitapauksessa laitettaisiin varmaan patienter, främmande språk, språkkunskap jne. 

svenska.se:ssä ei muutenkaan yleensä ole sellaisia termejä. 

Eli summa summarum olisi tietysti ruotsin kannalta parasta että olisi vieraat kielet KT vieraskielisyys. Jos kuitenkin pitää olla myös erikseen niin myös "med främmande språk" voisi olla vaihtoehto (tai mahd. vieraskieliset="personer med främmande språk").
