### ISSUE TITLE
hauntologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4837]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hauntologia 

#### Ehdotettu termi ruotsiksi   

hauntologi 

#### Ehdotettu termi englanniksi   

hauntology 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fisher, Mark,|ekirjoittaja: Ghosts of my life :|bwritings on depression, hauntology and lost futures, 978-1-78099-226-6 

#### Perustelut ehdotukselle   

Tarvittu mm. alla näkyvän teoksen indeksointiin 

**Ehdottajan nimi:** Yrjö Lindegren 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** yrjo.lindegren@hel.fi **Termiehdotus Fintossa:** [hauntologia](http://finto.fi/yse/fi/page/Y504837)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Hauntology

**Comment by mirmaid** [comment]
Ranskalaisfilosofi Jacques Derridan Specters of Marx -teoksessa kehittämä termi vaatii tietenkin oman selityksensä. Hauntologia on puolinäppärä sanaleikki, lopputulos yhteenlaskusta haunting plus ontology, kummittelu plus ontologia.

Yksinkertaisimmillaan se tarkoittaa jonkinlaista poissaolon kautta tapahtuvaa olemassaoloa. Esimerkiksi kapitalistisen realismissa, kuten brittiläinen kulttuurintutkija Mark Fisher asian nykymaailmaa kuvaa, kommunismi on (muutamaa erikoisvaltiota lukuun ottamatta) olemassa enää poissaolonsa kautta, hauntologisesti siis. https://kavi.fi/fi/elokuva/1571789-kinokonsertti-metropolis-khid

Tämän lisäksi ei suomenkielisiä viittauksia Googlella.

**Comment by mariaforsen** [comment]
Muutama osuma ruotsinkielisellä termillä hauntologi.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
hauntologi
