### ISSUE TITLE
sotakokemukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4839]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sotakokemukset 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi 
**Ehdottajan organisaatio:** HYK **Termiehdotus Fintossa:** [sotakokemukset](http://finto.fi/yse/fi/page/Y504839)

**Comment by mirmaid** [comment]
Käytetty 14 kertaa Melindassa. (Yleensä toki yhdistetty asiasanat _sota_ ja _kokemukset_.)

YSAssa on uskonnolliset kokemukset, oppimiskokemukset, lukukokemukset ja taidekokemukset.

**Comment by AuHo22** [comment]
Sodasta voi olla monenlaisia kokemuksia - kotirintamalta, sotarintamalta eli sekä siviiliväestön että itse sotilaiden. Voiko itse sotakokemukset terminä olla epäselvä?

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by ilona-x** [comment]
Mielestäni kokemukset + muut asiasanat riittäisivät.

Melinda:

sota? + kokemukset 347
?sota + kokemukset 378

jatkosota + kokemukset 89
talvisota + kokemukset 70
toinen maailmansota + kokemukset 117

**Comment by EsaMPKK** [comment]
Maanpuolustuskorkeakoululla käsitettä sotakokemukset on käytetty lähinnä merkityksessä "lessons learned", eli miten voitaisiin hyödyntää sodasta saatuja kokemuksia jatkossa. 

Muunlaisia sotakokemuksia voi olla kaikilla joita sota koskettaa. Mietin kolmea ratkaisumallia: 
- sotakokemukset pelkästään sotataidollisena käsitteenä
- useita sotakokemukset-käsitteitä eri sulkutarkenteilla
- Ilonan ehdottama malli: kokemukset + muut asiasanat

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
krigserfarenheter
ET krigsupplevelser
