### ISSUE TITLE
Struven ketju

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4840]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Struven ketju 

#### Ehdotettu termi ruotsiksi   

Struves meridianbåge 

#### Ehdotettu termi englanniksi   

Struve Geodetic Arc 

#### exactMatch   

WIkipedia : https://fi.wikipedia.org/wiki/Struven_ketju 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

World heritage in Finland = Le patrimoine mondial en Finlande 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa
Melinda x 7 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [Struven ketju](http://finto.fi/yse/fi/page/Y504840)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
