### ISSUE TITLE
koniini (piperidiinialkaloidi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4841]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koniini (piperidiinialkaloidi) 

#### Ehdotettu termi englanniksi   

coniine 

#### Ehdotettu yläkäsite YSOssa (LT)   

[alkaloidit](http://www.yso.fi/onto/yso/p11306) 

#### Perustelut ehdotukselle   

lisäys alkaloidien ryhmään 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

väitöskirja: The killer of Socrates exposed - Coniine in the plant kingdom 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

**Ehdottajan nimi:** Anne Uusitalo 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** anne.uusitalo@helsinki.fi **Termiehdotus Fintossa:** [koniini (piperidiinialkaloidi)](http://finto.fi/yse/fi/page/Y504841)

**Comment by mirmaid** [comment]
Hyväksytty (muodossa koniini) (YSA-kokous 13.12.2016)
