### ISSUE TITLE
työyhteisöviestintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4843]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

työyhteisöviestintä 

#### Ehdotettu termi ruotsiksi   

kommunikation på arbetsplatsen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viestintä](http://www.yso.fi/onto/yso/p36) 

#### Assosiatiiviset (RT)   

[yhteisöviestintä](http://www.yso.fi/onto/yso/p26123) 
[organisaatioviestintä](http://www.yso.fi/onto/yso/p2777) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Tarkoitusta täsmentävä selite   

"Työyhteisöviestintä on käsite, joka kuvaa työyhteisössä tapahtuvaa vuorovaikutusta,
viestintäkulttuuria ja tiedon vaihdantaa." Hyvät virrat liikkeelle: työyhteisöviestinnän mittaamisesta sen kehittämiseen, s. 2 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hyvän virrat liikkeelle : työyhteisöviestinnän mittaamisesta sen kehittämiseen, ISBN 978-952-6619-89-7. 

#### Perustelut ehdotukselle   

Sanaparin yhteisöviestintä + työyhteisöt tai organisaatioviestintä + työyhteisöt sijaan. Googlessa 9070 osumaa. 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi **Termiehdotus Fintossa:** [työyhteisöviestintä](http://finto.fi/yse/fi/page/Y504843)

**Comment by mirmaid** [comment]
Käytetty Melindassa 3 kertaa. (työyhteisöt & viestintä 355 kertaa)

**Comment by LeKorsu** [comment]
Jos työyhteisöviestintä otetaan uutena terminä ja ysassa on jo organisaatioviestintä, niin miten nämä eroavat/erotellaan toisistaan? Organisaatioviestinnällä nyt yli 2800 osumaa Melindassa.

**Comment by AuHo22** [comment]
Myös sisäinen tiedotus -termi on olemassa... eli näitä riittää

**Comment by mirmaid** [comment]
Ei hyväksytty, jätetään termiehdotukseksi (YSA-kokous 13.12.2016)

**Comment by mariaforsen** [comment]
Myös "arbetsplatskommunikation" ruotsiksi. Eikö pitäisi tehdä tästä ehdotuksesta ainakin korvattu termi? Onko tämä siis osittain synonymi organisaatioviestinnälle?

**Comment by vthuhtala** [comment]
'viestintä- -termin alla on jo 30+ alakäsitettä...

**Comment by AuHo22** [comment]
Lienee kokonaisuus, jossa pitäisi monta asiaa laittaa uusiksi - kukaan ei taida enää oikeastaan nykyaikana puhua sisäisestä / tai ulkoisesta tiedotuksesta ja ovatkohan nämä asiasanat peruja ns. tiedotusopista, johon entisaikaan kuuluivat myös nämä ns. sisäisen viestinnän opinnot. Tietysti kun viestinnän välineet / muodot ovat niin vahvasti vaihtuneet / muuttuneet, niin termienkin pitäisi olla ajan tasalla. 

Työyhteisöviestintä on mielestäni selkeä termi kuvata tiettyä asiaa, KT ja RT -suhteita sitten pitäisi miettiä,  yksi näkemys esim. tässä: 

http://viestijat.fi/mita-yhteisoviestinta-termille-tapahtumassa/

**Comment by jarmosaarikko** [comment]
työyhteisöviestintä sopii ohjaustermiksi organisaatioviestinnälle

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
_Työyhteisöviestintä_ on suunnilleen sama kuin sisäinen viestintä, nyt ohjausterminä _sisäinen tiedotus_ -asiasanalle. _Yhteisöviestinnän_ ja _organisaatioviestinnän_ ero on epäselvä ainakin itselleni.

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
yhteisöviestintä = työyhteisön, organisaation tms. sisäinen ja ulospäin suuntautuva viestintä, organisaatioviestintä

**Comment by mirmaid** [comment]
Organisaatioviestintä on tietokannoissa paljon käytetympi kuin yhteisöviestintä (myös uudemmassa aineistossa).

Näyttää myös siltä, että organisaatioviestintä-termiä käytetään kahdella tavalla: sekä Kielitoimiston sanakirjan laajassa merkityksessä, että sisäisen viestinnän synonyyminä (jolloin yhteisöviestintä nähdään sitten ehkä laajempana). 

- Valitaanko käytettäväksi termiksi _organisaatioviestintä_ vai _yhteisöviestintä_?

- Muutetaanko _sisäinen ja ulkoinen tiedotus_ muotoon _sisäinen/ulkoinen viestintä_?

**Comment by LeKorsu** [comment]
Kannatan sisäisen ja ulkoisen tiedotuksen vaihtamista viestintään eli ohjaustermit toisinpäin. Kuulostaa nykyaikaisemmalta. Tuo organisaatioviestintä vai yhteisöviestintä onkin jo hankalampi keissi. Googlaamalla ei ole paljon eroa (yhteisöviestintä hivenen suositumpi kuin organisaatioviestintä). Wikipediassa yhteisöviestinnällä kunnon artikkeli, organisaatioviestinnällä hyvin tynkä. Lehtikielessä (jälleen HS-arkisto) yhteisöviestintä tuo 116 osumaa, organisaatioviestintä 33.
Yhteisöviestintä kuulostaa nykyajassa "pehmeämmältä" kuin organisaatioviestintä, joten taidan kallistua kannattamaan ensinmainittua.
