### ISSUE TITLE
heraldikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4846]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heraldikot 

#### Ehdotettu termi englanniksi   

heraldists 

#### Ehdotettu termi ruotsiksi   

heraldiker 

#### Ehdotettu yläkäsite YSOssa (LT)   

[historiantutkijat](http://www.yso.fi/onto/yso/p14434) 
[kuvataiteilijat](http://www.yso.fi/onto/yso/p7530) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85060321> 

#### Vaihtoehtoiset termit ja ilmaisut   

vaakunataitelijat, vaakunatieteilijät 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 

#### Perustelut ehdotukselle   

Vastaava ala on Ysassa jo terminä (heraldiikka), mutta alan toimijaa kuvaava termi puuttuu. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

A. W. Ranckenin auktoriteettitietue (ammattikenttään haluaisin auktorisoidun termin ennemmin kuin "vapaata indeksointia") 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [heraldikot](http://finto.fi/yse/fi/page/Y504846)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
