### ISSUE TITLE
sotilasetiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4847]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sotilasetiikka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan organisaatio:** Maanpuolustuskorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [sotilasetiikka](http://finto.fi/yse/fi/page/Y504847)

**Comment by EsaMPKK** [comment]
Teos: Aalto: Hyvä sotilas - oikea toiminta : miksi asevoimissa opetetaan sotilasetiikkaa?

**Comment by mirmaid** [comment]
Käytetty Melindassa 2 kertaa.

LCSH: Military ethics (NT Conscientious objection = aseistakieltäytyminen)

https://en.wikipedia.org/wiki/Ethics#Military_ethics

YSAssa on mm. _ammattietiikka_, _tutkimusetiikka_, _lääketieteellinen etiikka_

**Comment by Elmukelmu** [comment]
Ihan hyvän tuntuinen asiasana, olis varmaan käyttöäkin.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
