### ISSUE TITLE
ekstaattiset ilmiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4848]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ekstaattiset ilmiöt](http://www.yso.fi/onto/ysa/Y101131) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi ekstaattiset kokemukset 

#### Perustelut ehdotukselle   

ekstaattiset kokemukset kyllä käytetään paljon muustakin kuin uskonnollisesta, mutta lähinnä yksikössä; YSOssa ekstaattiset ilmiöt LT kokemukset 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
