### ISSUE TITLE
hajoaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4849]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hajoaminen](http://www.yso.fi/onto/ysa/Y101482) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

Käytetty eri merkityksissä, esim. esineiden tai aineiden hajoaminen, perheen hajoaminen, valtion hajoaminen. Ruotsiksi osittain eri termejä riippuen asiayhteydestä. Allärs: nedbrytnig, sönderfall.
https://github.com/NatLibFi/Finto-data/issues/656

vrt. myös hajotus
https://github.com/NatLibFi/Finto-data/issues/657 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Termiä käytetään luonnontieteissä (kemia, fysiikka, biologia) ja yhteiskuntatieteissä. Jälkimmäisessä useimmiten kyseessä valtion hajoaminen, joskus puolueen. _Hajoaminen (yhteisöt)_ voisi olla mahdollinen mutta käytettäisiinkö tätä valtioista? _Hajoaminen (yhteiskuntatieteet)_?

**Comment by satuniininen** [comment]
Kannatan muotoa _hajoaminen (yhteisöt)_, vaikka valtioiden yhteydessä se ei tosiaan ole se intuitiivisin. Auttaisiko ohjaus KT _valtion hajoaminen_?

**Comment by mariaforsen** [comment]
Vaikeaa saada yksi-yhteen-vastaavuutta ruotsiksi, vaikka jaetaan... Biologia: nedbrytning, fysiikka/kemia: sönderfall ainakin joissakin tapauksissa, yhteiskunta: sönderfall tms. Tarkenne täytyisi varmaan laittaa ruotsiksikin.

**Comment by mirmaid** [comment]
Luulen että luonnontieteet pitäisi myös jakaa tarkemmin: _hajoaminen (fysiikka)_ jne. _Biohajoaminen_ löytyy myös sanastosta, KT biologinen hajoaminen.

Ehdotin jossain toisaalla (vähän epätoivoisesti) erottelua sulkutarkenteilla (valtiot) vs. (yhteisöt), joten ehkä tässäkin pitäisi ottaa erikseen _valtion hajoaminen_ ja _hajoaminen (yhteisöt)_. EU:n hajoaminen on tietysti aika lähellä valtion hajoamista...

**Comment by mirmaid** [comment]
Fysiikan yhteydessä tarvittaisiin varmaankin _radioaktiivinen hajoaminen_.

**Comment by OutiHintikka** [comment]
Tulisiko radioaktiivinen hajoaminen yksinäiseksi fysiikan ilmiöksi? Eikö muita ole

**Comment by ilona-x** [comment]
Tämä hajoaminen kyllä hajottaa, kun noita kemian hajoamisiakin taitaa olla useampaa laatua :roll_eyes: : : http://www.tsk.fi/tepa/fi/haku/hajoaminen

Tässä pari poimintaa:

hajoaminen (Ympäristötieteet) Yhdisteiden tai kappaleiden pilkkoutuminen tai pilkkominen yksinkertaisemmiksi tai pienemmiksi.
fi        hajoaminen; hajottaminen; hajotus
sv       nedbrytning
en      degradation; decomposition; breakdown
http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:hajoaminen


dissosiaatio (Ympäristötieteet) Kemiassa aineen hajoaminen ioneiksi, molekyyleiksi tai radikaaleiksi liuotuksen, lämpöenergian ym. avulla (BS).
fi        dissosiaatio; hajottaminen; hajoaminen
sv       dissociation; dissociering
en      dissociation
http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:dissosiaatio
https://fi.wikipedia.org/wiki/Dissosiaatio_(kemia)
http://id.loc.gov/authorities/subjects/sh85038500.html

**Comment by mirmaid** [comment]
Jos aloitetaan ottamalla _valtion hajoaminen_ ja korjaamalla ne.

**Comment by YSA-kokous** [comment]
valtion hajoaminen

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4466

**Comment by ilona-x** [comment]
valtion hajoamiset korjattu Melindaan

Muita Melindasta löytyviä ei-kemia/fysiikka/biologia hajoamisia esim. perheen hajoaminen, puolueen hajoaminen, hallituksen hajoaminen, bändin hajoaminen, EU:n hajoaminen, kylän hajoaminen...

YSA:ssa oleva **biohajoaminen** (KT biologinen hajoaminen) sopisi ehkä osaan viitteistä.

LCSH:
**Decomposition (Chemistry)** http://id.loc.gov/authorities/subjects/sh85036221
ST **Biodegradation**, Photodegradation, Postmortem changes, Potassium ethylxanthate--Degradation, Proteolysis

**Comment by mirmaid** [comment]
Voidaan varmaan ottaa jotain _hajoaminen (ryhmät ja yhteisöt)_ -tyyppistä, mutta jotta oikeasti näkee tarvitaanko sitä, olisi hyvä jos saisi siivottua ensin luonnontieteet pois.

**Comment by mirmaid** [comment]
**biohajoaminen**
_One can differentiate abiotic from biotic decomposition (biodegradation). The former means "degradation of a substance by chemical or physical processes, e.g., hydrolysis. The latter means "the metabolic breakdown of materials into simpler components by living organisms", typically by microorganisms._

Sanastossa on myös _maatuminen_, käykö se silloin, kun ei voi olla varma onko kyse biohajoamisesta? 
Wikipedia: _Maatuminen tarkoittaa maan eloperäisessä kerroksessa kasvimassaa muuttavia biologisia, kemiallisia ja fysikaalisia tekijöitä. Hajoamisen aiheuttavat maassa elävät mikrobit ja sienet, jotka hajottavat aineen rakenteen ja synnyttävät siitä humusta._ - Ensimmäisen lauseen mukaan sopisi, mutta jälkimmäinen ikäänkuin kumoaa sen?
Esim. https://melinda.kansalliskirjasto.fi/byid/014434763, https://melinda.kansalliskirjasto.fi/byid/011328815
Joskus sopii myös _hajotus_? (esim. https://melinda.kansalliskirjasto.fi/byid/009874677)

**Comment by mirmaid** [comment]
Kemia: ehdottaisin kuitenkin _hajoaminen (kemia)_, joka kattaisi myös dissosiaation. Jos tämä tuottaa virheitä, voidaan kuitenkin myöhemmin korjata.
Ks. esim. https://sv.wikipedia.org/wiki/Spj%C3%A4lkning_(kemi)

Rajanveto tämän ja biohajoamisen/maatumisen välillä ei toki ole helppoa.

**Comment by mirmaid** [comment]
Fysiikka: _radioaktiivinen hajoaminen_, mahdollinen lisäksi _beetahajoaminen_ (_beetasäteily_ on)
_hiukkasten hajoaminen (hiukkasfysiikka)_ (?) https://melinda.kansalliskirjasto.fi/byid/011534486; https://en.wikipedia.org/wiki/Particle_decay

**Comment by mirmaid** [comment]
_Hajoaminen (ryhmät ja yhteisöt)_ - otetaan tämä, jos näyttää siltä, että se on tiedonhaun kannalta tarpeellinen esim. puolueen, EU:n tai hallituksen hajoamista käsittelevissä aineistoissa.

**Comment by YSA-kokous** [comment]
hajoaminen (kemia)
radioaktiivinen hajoaminen, beetahajoaminen
hajoaminen (ryhmät ja yhteisöt)
hiukkasten hajoaminen (hiukkasfysiikka), jos tarpeen

biohajoaminen, maatuminen biologian aineistoissa

**Comment by mariaforsen** [comment]
Sv.
-statsupplösning ET statens sönderfall, statens upplösning 
-spjälkning (kemi) 
-upplösning (grupper) ET sönderfall (grupper)
-partikelsönderfall 


-nedbrytning ANV biologisk nedbrytning, förmultning

**Comment by mirmaid** [comment]
_radioaktiivinen hajoaminen, beetahajoaminen_ lisätty ohjaustermeiksi
poistettu _hajoaminen_
