### ISSUE TITLE
rullalautailu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4850]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rullalautailu](http://www.yso.fi/onto/ysa/Y104208) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selkeytettävä suhde termeihin skeittaus ja mäkirullalautailu. 

#### Perustelut ehdotukselle   

YSAssa nyt skeittaus ja mäkirullalautailu, sekä rullalautailu, jossa huomautus: Vanhentunut muoto. Suositellaan käytettäväksi asiasanaa skeittaus. Rullalautailu-muotoa on käytetty Melindassa 114 kertaa (viimeksi 2015), skeittausta 72 kertaa. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Suomen rullalautaliitto = pelkkää skeittausta. Se, kuuluuko longboarding rullalautailuun (tai jopa skeittaukseen) on ilmeisesti kiinni siitä keneltä kysytään. Oma ehdotukseni on edelleen se ehkä käytännössä helpoin vaihtoehto että säilytetään kaikki kolme, tehdään skeittauksesta ja mäkirullalautailusta alakäsitteitä rullalautailulle ja poistetaan käyttörajoitus.

Ongelmia tämä aiheuttaa englanniksi ja ehkä ruotsiksi, vaikka nyt vastineet on olemassa molemmille. Jos tämä on liian huono ratkaisu, suomeksi rullalautailu & mäkirullalautailu olisi ehkä vähän parempi kuin skeittaus ja mäkirullalautailu, koska rullalautailu on ehkä terminä vähän sallivampi kuin skeittaus - kumpaan esim. menisi kruiserilla liikkuminen, joka on nykyään suosittua varsinkin nuorten tyttöjen keskuudessa?

**Comment by mariaforsen** [comment]
Ruotsiksi ja esim. SAOssa on tosiaan nykyään skateboardåkning käytetty termi ja rullbrädsåkning vanhentunut (ja korvattu termi). Mahdollisena ongelmana monikielisessä "automaattisesssa" kuvailussa olisi sitten tietty se että rullbrädsåkning olisi käytetty Allärs-terminä, vaikka kukaan ei sellaista termiä enää käytäkään. Ja tottakai kuvailijat käyttäisivät nimenomaan aina skateboardåkning eikä ollenkaan rullbrädsåkning. 

Kyllähän esim. MOT, Wikipedia ja harrastussivut Googlessa käsittelevät nämä synonyymeinä myös suomeksi..?

**Comment by mirmaid** [comment]
Tämä on varmaan niitä tapauksia missä ei vaan ole oikeaa vaihtoehtoa. Ruotsiksi tilanne on vähän helpompi kun "ajetaan skeittilaudalla", suomeksi skeittaus ainakin monen mielestä tarkoittaa temppujen tekemistä, jos vaan liikkuu longboardilla tai cruiserilla niin ei skeittaa. Mutta ei kai tästä tosiaan ihan selkeää konsensusta ole.

**Comment by mariaforsen** [comment]
Ruotsiksikin on "longboardåkning" oma lajinsa niin sanotusti. Ei kai ole pakko laittaa rullalautailu/skeittaus tämän yläkäsitteeksi?

**Comment by tpalonen** [comment]
Mikäli rullalaitailulle kattoterminä on vaikea löytää käännöstä englanniksi ja ruotsiksi niin varmaan olisi parasta, että olisi vain skeittaus-käsite, jolla ohjausterminä rullalaitailu.

**Comment by satuniininen** [comment]
Itse kannattaisin vaihtoehtoa rullalautailu KT skeittaus, koska se kattaisi paremmin cruiserit ja sopisi mäkirullalautailun yläkäsitteeksi. Kielenkäyttö on muuttunut siihen suuntaan, ettei rullalautailu-termillä ole enää samanlaista vanhahtavaa sävyä kuin vielä esim. 15-20 vuotta sitten.

Rullalautailulle ja skeittaukselle on tosiaan vaikeaa, ellei mahdotonta löytää erottelevia enkkuvastineita.

**Comment by mirmaid** [comment]
https://www.olympiakomitea.fi/huippu-urheilu/kisat/olympialaiset/olympiahistoria-2/olympialajit/kesalajit/rullalautailu/

Toki molempia nimityksiä käytetään myös puhuttaessa olympialajista.

**Comment by mirmaid** [comment]
Mutta siis joko _rullalautailu_ KT skeittaus ST _mäkirullalautailu_, tai
_skeittaus_ KT rullalautailu RT _mäkirullalautailu_

Äänestetään, jos ei yksimielistä päätöstä.

**Comment by YSA-kokous** [comment]
rullalautailu KT skeittaus ST mäkirullalautailu

**Comment by mariaforsen** [comment]
Sv. skateboardåkning ET rullbrädsåkning
