### ISSUE TITLE
substraatti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4851]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[substraatti](http://www.yso.fi/onto/ysa/Y165913) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Sanalla on monia merkityksiä. 1) Alusta, perustana oleva aine tai esine. 2) Kielitieteessä sana tai kieliopillinen muoto, joka on säilynyt valloittajan, siirtolaisten tai uudisasukkaiden maahan tuomassa valtakielessä jäänteenä siellä aiemmin puhutusta. 3) Filosofiassa substanssi käsitettynä ominaisuuksien koossa pitäjäksi. 4) Biologiassa bakteerin tai soluviljelmän elatusalusta. 5) Kemiassa aine, joka muuttuu kemiallisesti entsyymin vaikutuksesta.

YSOssa jaettu ”alustat”, ”kielelliset ilmiöt” ja ”muu rooli”. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindassa 26 viitettä joista suurin osa kielitiedettä. Erotettiin substraatti (kielitiede), tutkitaan vielä muut ysa-asiasanoiksi merkityt esiintymät (ilmeisesti lähinnä biologiaa/biokemiaa).

**Comment by mirmaid** [comment]
Ehdotan monikollista muotoa substraatit (kemia), vastaavasti monikossa on katalyytit ja reagenssit. 
Ks. myös https://fi.wikipedia.org/wiki/Entsyymi 

Toisena substraatti (filosofia)

**Comment by mirmaid** [comment]
substraatit (kemia) ja substraatti (filosofia) (YSA-kokous 13.12.2016)
