### ISSUE TITLE
kulttuuripaikan haltijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4852]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kulttuuripaikan haltijat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yliluonnolliset olennot](http://www.yso.fi/onto/yso/p796) 

#### Vaihtoehtoiset termit ja ilmaisut   

kodinhaltijat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

KULAssa, käytetty asiasanana Melindassa 3 kertaa, Artossa 3 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [kulttuuripaikan haltijat](http://finto.fi/yse/fi/page/Y504852)

**Comment by mirmaid** [comment]
Käännösongelma

**Comment by mirmaid** [comment]
"käytetty asiasanana Melindassa 3 kertaa, Artossa 3 kertaa" > Melindassa 9 kertaa, Artossa 8 kertaa

**Comment by mirmaid** [comment]
YSAssa on _haltijat_, _luonnonhaltijat_, _vedenhaltijat_ ja _tontut_.

Ei Googlessa lukuunottamatta viitteitä sanastoon.

**Comment by satuniininen** [comment]
Kulossa englanniksi _residential guardian spirits_

**Comment by krinay** [comment]
Kansanuskontutkimuksessa erotetaan toisistaan luonnonhaltijat (= metsänhaltijat, vedenhaltijat jne.) sekä kulttuuripaikan haltijat (kodinhaltijat, riihenhaltijat jne.), mutta ehkä YSAan ei ole tarpeen ottaa näin tarkkoja termejä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
