### ISSUE TITLE
lintukotolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4853]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lintukotolaiset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yliluonnolliset olennot](http://www.yso.fi/onto/yso/p796) 

#### Vaihtoehtoiset termit ja ilmaisut   

taivaanääreläiset 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

KULAssa, käytetty asiasanana Melindassa 3 kertaa, Artossa 3 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [lintukotolaiset](http://finto.fi/yse/fi/page/Y504853)

**Comment by mirmaid** [comment]
Käännösongelma

**Comment by mirmaid** [comment]
Artossa kerran KULA-terminä, Melindassa vapaana asiasanana.

**Comment by mariaforsen** [comment]
Voisiko ruotsinkielinen vastine yksinkertaisesti olla "lintukotolaiset"..?

**Comment by AuHo22** [comment]
On suomalaiseen kansanperinteeseen liittyvä ilmaisu - onko aina pakko ylipäätään kirjata käännös, jos se ei ole tarkoituksenmukaista?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)
