### ISSUE TITLE
työmatkat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4854]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työmatkat](http://www.yso.fi/onto/ysa/Y99771) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

Kodin ja työpaikan välinen matka vs. työntekoon liittyvä pitempi matka. Vrt. myös koulumatkat. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ehdotuksia sulkutarkenteiksi? (välimatkat) / (matkustus) :weary:

**Comment by LeKorsu** [comment]
Onko Ysan liikematkat sv affärsresor käsitteenä sama kuin työntekoon liittyvää pidempää matkaa (melinda 301 osumaa), voivatko virkamiehet olla liikematkalla? No, näyttää siellä ysassa olevan myös virkamatkat. Olisiko suotavampaa löytää näille pidemmille matkoille jokin ohjaustermi(t) näistä ja jättää työmatkat kodin ja työpaikan väliseen matkustamiseen?

**Comment by mariaforsen** [comment]
Ruotsin osalta affärsresor ei ole sama asia, mutta virkamatka=tjänsteresa toimii kyllä.

**Comment by MikkoAleksanteri** [comment]
Kielitoimiston sanakirjan tarkenteet aika hyviä, vaikkakin pitkähköjä:

1. työmatka (matka työhön)
2. työmatka (työasioissa tehtävä matka)

**Comment by mirmaid** [comment]
No laitetaan
työmatkat (työhön)
työmatkat (työasioissa)

:grin:

Entä
työmatkat (työpaikalle)
työmatkat (matkustus työasioissa)

**Comment by mirmaid** [comment]
Äh, en kyllä tykkää tuosta "työasioissa"...

**Comment by mirmaid** [comment]
Onko riittävän selkeä:

työmatkat (työpaikalle)
työmatkat (matkustus)

**Comment by YSA-kokous** [comment]
työmatkat (työpaikalle)
työmatkat (matkustus)

**Comment by mariaforsen** [comment]
Sv. 
-arbetsväg
-arbetsresor
