### ISSUE TITLE
luonnonhistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4856]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luonnonhistoria](http://www.yso.fi/onto/ysa/Y103228) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Merkitys selkeytettävä 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja: aik. biologisista tieteistä vars. koulujen oppiaineena. 

YSAssa LT historia, voisi olla paremmin biotieteet tai biologia kun tarkoitetaan tätä oppiainetta. 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Näyttää siltä että termillä on nykyään myös toinen merkitys http://fi.wikipedia.org/wiki/Luonnonhistoria. Fennicassa uudemmassa aineistossa minusta käytetty tässä merkityksessä, esim. _Suursaimaa: hiekkarantojen elämää 6000 vuotta sitten_, _Sukupolvien maisema: Porvoonjokilaakson kansallismaiseman syntyvaiheita_. Biotieteet sopisi varmaan silti toiseksi yläkäsitteeksi, mutta pitääkö jakaa niin että aikaisempi oppiaine on erikseen?

**Comment by mirmaid** [comment]
"Termiä ei enää juurikaan käytetä luonnontieteiden puolella. Se on tarkoittanut nimenomaan evoluutiota ja esim. paleontologiaa sekä tietoa luonnosta tiettynä aikana ja/tai tietyssä maantieteellisessä paikassa. Englanninkielinen käsite _natural history_ on vielä laajempi kuin suomenkielinen. Tieteen termipankin synonyymi luonnontieto kuvannee hyvin asiaa."

**Comment by mirmaid** [comment]
Ehdotettu myös LT luonnontieteet. LT ei kuitenkaan estä käyttämästä termiä uudella tavalla, luonnontieteet sopii yläkäsitteeksi vaikka tulkinta termin merkityksestä olisi tämä uudempi. Ongelma onkin ehkä siinä että tämä uusi tulkinta termistä on jopa osuvampi kuin aikaisempi, jolloin parempi termi olisi ollut luonnontieto. Yksi vaihtoehto tietysti on vaihtaa termiksi luonnontieto ja tehdä luonnonhistoriasta ohjaustermi – se ainakin ohjaisi käyttöä pois tästä uudesta trendistä…nyt YSAssa tosin on luonnontieto KÄ ympäristö- ja luonnontieto.

**Comment by MikkoAleksanteri** [comment]
Ehdottomasti tärkeää, että termin merkitys selvennetään sanastoon.

Käsitteellä on pitkä historia ja käyttö länsimaisen kulttuurin piirissä, lähtöisin viimeistään Plinius vanhemman Naturalis Historia-teoksesta. Historiallisesta näkökulmasta LT biotieteet tai biologia olisi todella anakronistista. 

En tiedä kyllä yhtään nykyistä kouluakaan, jossa olisi tämänniminen oppiaine, myöskään Melindan viitteet eivät taida käsitellä aihetta oppiaineena.

Ehdotan että pidetään YK historia ja lisätään huomautus "Käytetään silloin kuin kyseessä on luontoa ja sen historiaa käsittelevä aineisto, erityisesti jos näkökulma on eliöissä ja niiden kehityshistoriassa. Oppiaineen yhteydessä KÄ "ympäristö- ja luonnontieto"".

**Comment by YSA-kokous** [comment]
Pidetään YK historia ja lisätään huomautus "Käytetään silloin kuin kyseessä on luontoa ja sen historiaa käsittelevä aineisto, erityisesti jos näkökulma on eliöissä ja niiden kehityshistoriassa. Oppiaineen yhteydessä KÄ "ympäristö- ja luonnontieto"."
