### ISSUE TITLE
rakkaussuhde

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4857]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakkaussuhde](http://www.yso.fi/onto/ysa/Y116122) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Monikko? 

#### Perustelut ehdotukselle   

Ehdotettu termiä "rakastetut", tässä kontekstissa toimisi monikollinen "rakkaussuhteet". 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Teos: Mozart und seine Frauen

**Comment by mirmaid** [comment]
YSAssa on _kiintymyssuhde_, _parisuhde_ ja esim. _esimies-alaissuhde_, _ihminen-eläinsuhde_ ja _vanhempi-lapsisuhde_. Monikossa on mm. _etäsuhteet_, _henkilösuhteet_, _ihmissuhteet_ ja _sosiaaliset suhteet_.

Osa termeistä sopii sekä yksikköön että monikkoon, yksikössä näkökulma on "suhdetyyppi".

**Comment by mirmaid** [comment]
Kerran Melindassa monikossa (samassa tietueessa myös yksikössä). Tietoaineistossa 313 kertaa yksikössä (kaikkiaan 1696 kertaa yksikössä, 9 kertaa monikossa).

**Comment by LeKorsu** [comment]
Ysassa näkyy olevan monikossa romanssit (ihmissuhteet). Tämä varmaan kävisi monikollisen muodon korvaavajana (minä ehdotin aikoinaan tuota rakastetut-termiä, kun en tuon Mozart-kirjan yhteydessä näköjään ole löytänyt tuota romanssit (ihmissuhteet) -asiasanaa.

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 13.12.2016)
