### ISSUE TITLE
võro-seton kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4858]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[võro-seton kieli](http://www.yso.fi/onto/ysa/Y113532) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muotoa võrun kieli on myös käytetty ja ISO-kielikoodilistalla vro = Võro, joten ehkä võrun kieli olisi oikeampi muoto? 

#### Perustelut ehdotukselle   

Võro eli võru on Kaakkois-Viron alueellinen alkuperäiskieli. Sitä on historiallisesti pidetty yhtenä viron etelämurteista, mutta nykyään se luetaan useimmiten omaksi kielekseen. 
Võron kielestä vain vähän poikkeaa Viron kaakkoisimmassa osassa Setumaan maakunnassa sekä sen Venäjän puolelle rajaa jääneessä osassa puhuttu setukaisten eli seton (setun) kieli. Joskus puhutaankin ”võron-seton kielestä”. Seton puhujat eroavat võron puhujista siten, että he ovat uskonnoltaan ortodokseja ja kansalliselta identiteetiltään setukaisia, eivät virolaisia.

http://finto.fi/lexvo/fi/page/vro 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty 12 kertaa Melindassa, sisällysluetteloissa yleensä võron kieli, toisinaan myös võro-seton kieli.

"the Setos generally do not identify as Võro speakers" https://en.wikipedia.org/wiki/Seto_dialect

**Comment by mirmaid** [comment]
Muutetaan?

**Comment by mariaforsen** [comment]
Kannatan muutosta: ruotsiksi "võru".

**Comment by AuHo22** [comment]
võrunkielinen kirjallisuus YSAssa ; eli muotoa kyselin aiemmin Kotuksesta, josta vastaus: "edelleen on voimassa suositus võru, võrun kieli, vaikka omakielinen asu onkin võro" - eli siis u:n kanssa?
