### ISSUE TITLE
DAISY-kirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4859]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

DAISY-kirjat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 

#### Perustelut ehdotukselle   

On Kaunokissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [DAISY-kirjat](http://finto.fi/yse/fi/page/Y504859)

**Comment by mirmaid** [comment]
YSAssa on DAISY.

Ei Melindassa

**Comment by mariaforsen** [comment]
Allärsissa on myös talböcker (äänikirjat=talböcker+ljudböcker), ovat yleensä nimenomaan Daisy-kirjoja.

**Comment by mirmaid** [comment]
Tutkitaan onko sama kuin äänikirjat lukemisesteisille

**Comment by mariaforsen** [comment]
Eli ei ole sama, mutta DAISY on eräs formaatti näille (Ruotsissa ja Suomessa ehkä tavallisin?)

**Comment by vilkkier** [comment]
Daisy-työryhmän palaverissa päätettiin kirjoitusasuksi Daisy. Muutin sen muodon myös Metatietosanastoon.

**Comment by mirmaid** [comment]
Vaihdetaan Daisy-kirjat -muotoon (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
Daisy-böcker
