### ISSUE TITLE
nimikortit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4860]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nimikortit](http://www.yso.fi/onto/ysa/Y109703) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nyt KT käyntikortit. Ehdotettu että käyntikortit otettaisiin erikseen. 

#### Perustelut ehdotukselle   

Käyntikortilla on oma tietty merkityksensä. 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: nimikortti: 1. käyntikortti, 2. paikkakortti (nimikortti joilla merkitään kunkin vieraan paikka aterialla)

**Comment by mirmaid** [comment]
Nimikortit-termiä käytetty Melindassa 101 kertaa. Ainakin kerran merkityksessä paikkakortit, kaikissa tapauksissa ei voi varmasti sanoa onko aineistossa käsitelty (vain) käyntikortteja. Jos otetaan käyntikortit, jätetäänkö nimikortit myös sanastoon? Missä merkityksessä?

**Comment by mariaforsen** [comment]
Nimikortit on Allärsissa visitkort = käyntikortit! 

MOT: 
1 (käyntikortti) visitkort 
2 (paikkakortti) placeringskort

**Comment by LeKorsu** [comment]
KT paikkakortit lisäys nimikorttien ohjaukseenkaan ei toimi ruotsiksi. Pitäisikö sitten ottaa erikseen molemmat käyntikortit ja paikkakortit? Tarvitaanko nimikortit sitten omana ollenkaan? Ei vielä selvää kantaa, tämä "ääneen" pohdiskelua.

**Comment by AuHo22** [comment]
Nimikortit esimerkiksi kongresseissa tms. tilaisuuksissa, yleensä rintaan ripustettavia, eivät ole käyntikortteja  eivätkä paikkakortteja silloin.

**Comment by mirmaid** [comment]
Vaihdetaan termiksi käyntikortit (YSA-kokous 13.12.2016)
