### ISSUE TITLE
tähtikaukoputket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4861]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tähtikaukoputket 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[06 Tähtitiede. Astronomia. Avaruustutkimus](http://www.yso.fi/onto/yso/p26588) 

#### Perustelut ehdotukselle   

YSAssa on tällä hetkellä kaukoputket (KT teleskoopit), mutta tarvetta olisi kuitenkin avaruutta tutkiville kaukoputkille erikseen. On olemassa tähtikaukoputket, mutta siinäkin tuntuu olevan historiallinen konnotaatio monen mielestä. Teoksessa Elämän etsintä avaruudesta on käytetty alvariinsa termiä teleskoopit (ja jättiteleskoopit yhtenä), lisäksi avaruusteleskoopit, jotka on sijoitettu avaruuteen. Olisiko parempi termi avaruuden tutkimusta kuvaamaan vaikka tarkenteen avulla sitten? 

#### Tarkoitusta täsmentävä selite   

Teleskooppi, avaruusteleskooppi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Elämän etsintä avaruudesta 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [tähtikaukoputket](http://finto.fi/yse/fi/page/Y504861)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:

kaukoputki: tav. putkeen sijoitetusta linssi-, peili- t. prismajärjestelmästä koostuva optinen laite kaukaisten kohteiden havaitsemiseksi, teleskooppi. _Tähtikaukoputki._ 

tähtikaukoputki: tähtien tutkimiseen tarkoitettu kaukoputki. 

teleskooppi: kaukoputki. _Peiliteleskooppi._ Laajemmin _Radioteleskooppi._

**Comment by mirmaid** [comment]
LCSH:ssa on Telescopes ja Space telescopes. Jälkimmäinen viitannee avaruudessa sijaitseviin teleskooppeihin? https://en.wikipedia.org/wiki/Space_telescope (suomeksi https://fi.wikipedia.org/wiki/Avaruustutkimusasema)

Suomeksi tähtikaukoputket tai edes avaruusteleskoopit ei viittaa yksinomaan avaruudessa sijaitseviin kaukoputkiin.

**Comment by mirmaid** [comment]
Melindassa 4 kertaa teleskoopit, viitteet eivät käsittele avaruudessa sijaitsevia kaukoputkia. Ei muita ehdotettuja termejä.

**Comment by satuniininen** [comment]
Tarvitaanko tarkennetta vai riittäisivätkö muut asiasanat tuomaan tarpeeksi kontekstia?

**Comment by Elmukelmu** [comment]
Aleksi-tietokannassa olemme käyttäneet avaruusteleskooppi-asiasanaa. Se on populaarissa aineistossa varsinkin aika kätevä, koska nopeasti ilmaisee, että kyse on nimenomaan avaruustutkimuksesta eikä tarvitse miettiä onko tämä nyt radioteleskooppi vai peilikaukoputki (YSAn termejä). Pelkkä kaukoputki taas tuntuu hiukan vaisulta kun on kyse näistä nykyisistä jättimäisistä laitoksista.

**Comment by mariaforsen** [comment]
Ruotsiksi stjärnkikare ja/tai rymdteleskop.

**Comment by LeKorsu** [comment]
Avaruusteleskooppi/koopit kuulostaa muuten ihan hyvältä, mutta onko siitä haittaa, kun muuten teleskoppeista ohjataan käyttämään kaukoputkia?

**Comment by mirmaid** [comment]
Avaruusteleskoopit hyväksytty (YSA-kokous 13.12.2016)
