### ISSUE TITLE
antautuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4863]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

antautuminen 

#### exactMatch   

LCSH : Capitulations, Military 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Sotahistoria on täynnä kuuluisia ja kiisteltyjä antautumisia, mutta Ysa ei tunne koko termiä antautuminen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [antautuminen](http://finto.fi/yse/fi/page/Y504863)

**Comment by mirmaid** [comment]
Melindassa kerran Kaunokki-terminä (ei ole Kaunokissa).

https://fi.wikipedia.org/wiki/Kapitulaatio

**Comment by satuniininen** [comment]
Ihan selkeä ja tarkkarajainen termi sinänsä, mutta mietityttää, että onko kuitenkaan tarvetta. Olisi hyvä saada esimerkki aineistosta, jossa tarvittu.

**Comment by EsaMPKK** [comment]
Taistosta pöyhäisin niin löytyi teos How fighting ends : a history of surrender / edited by Holger Afflerbach and Hew Strachan. Aihetta luonnehditaan OUP:n sivuilla: "Central topic for the history of warfare".

Wikipediassa käsite antautuminen esiintyy muodossa kapitulaatio. Jälkimmäinen on mielestäni kapulakieltä ja muotoa antautuminen puolsi myös strategian tutkija, jolle soitin.

**Comment by mariaforsen** [comment]
Kannatan, ruotsiksi olisi "kapitulation" hyvä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 13.12.2016)

**Comment by mariaforsen** [comment]
SV: kapitulation
