### ISSUE TITLE
lääketieteellinen antropologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4864]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lääketieteellinen antropologia](http://www.yso.fi/onto/ysa/Y102199) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko sama kuin antropologinen lääketiede? 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
MeSH Heading: Anthropology, Medical (ei FinMeSHissä)
Scope Note: Field of social science that is concerned with differences between human groups as related to health status and beliefs.
Entry Term: Medical Anthropology

**Comment by mirmaid** [comment]
Teos: Vuorinen: _Taudit, parantajat ja parannettavat_

**Comment by krinay** [comment]
Lääketieteellinen antropologia (medical anthropology) on antropologian suuntaus. Siinä tutkitaan terveyden, sairauden ja lääketieteen kulttuurisia ja sosiaalisia ulottuvuuksia. Antropologisessa lääketieteessä (anthropological medicine) antropologista lähestymistapaa sovelletaan kliiniseen lääketieteeseen tms. Periaatteessa kai suunnilleen noin, mutta käytännössä käsitteet limittyvät ja sekoittuvat toisiinsa. 

Melindassa on käytetty asiasanaa ’antropologinen lääketiede’ 26 kertaa, usein sellaisten teosten sisällönkuvailuun, joiden nimekkeessä on ”medical anthropology”. Asiasanaa 'lääketieteellinen antropologia' on käytetty 359 kertaa.

LCSH: 
Medical anthropology BT Anthropology
Variants: Medical care -- Anthropological aspects; Medicine -- Anthropological aspects

TEROssa on molemmat: 
antropologinen lääketiede (eng medical anthropology; swe antropologisk medicin) LT lääketiede
lääketieteellinen antropologia (eng medical anthropology; swe medicinsk antropologi) LT antropologia; kulttuuriantropologia

Kannatan silti sitä, että YSAssa antropologinen lääketiede muutetaan ohjaustermiksi.

**Comment by mariaforsen** [comment]
Kannatan, ruotsiksi "medicinsk antropologi" paljon enemmän käytetty.

**Comment by mirmaid** [comment]
Hyväksytty yhdistäminen (YSA-kokous 7.3.2017).
