### ISSUE TITLE
tietopyynnöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4866]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tietopyynnöt 

#### Ehdotettu termi englanniksi   

information requests tai Freedom of Information requests 

#### Ehdotettu termi ruotsiksi   

offentlighetsbegäranden 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pyynnöt](http://www.yso.fi/onto/yso/p26877) 

#### Assosiatiiviset (RT)   

[laki viranomaisten toiminnan julkisuudesta](http://www.yso.fi/onto/yso/p9064) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Teos käsittelee tietopyyntöjä. Melindassa ei osumia, mutta Googlessa 25 300 (yksiköllinen). Ks myös https://tietopyynto.fi/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Läpinäkyvyys kunnan toiminnassa : tietopyyntöihin vastaaminen / Aleksi Koski ja Heikki Kuutti. 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [tietopyynnöt](http://finto.fi/yse/fi/page/Y504866)

**Comment by mirmaid** [comment]
Pitääkö jotenkin täsmentää?
http://merivoimat.fi/artikkeli/-/asset_publisher/merivoimien-taistelualusten-rakentamisen-tietopyynnot-liikkeelle
https://en.wikipedia.org/wiki/Request_for_information

Myös viranomaisten tietopyynnöt esim. facebookin ym. verkkopalveluiden käyttäjistä.

**Comment by mariaforsen** [comment]
Sv. begäran om information, informationsbegäran..?

**Comment by mirmaid** [comment]
Seuraava kokous, Tommi selvittää.

**Comment by mariaforsen** [comment]
Sv. begäranden om information ET begäranden om information, informationsbegäranden, offentlighetsbegäranden
https://www.valvira.fi/web/sv/valvira/begaran-om-information
https://finlex.fi/sv/laki/ajantasa/2019/20190552
https://www.sprakbruk.fi/-/begaran
https://vnk.fi/documents/10616/3457865/Svenskt+lagspr%C3%A5k+i+Finland+2017

**Comment by jarmosaarikko** [comment]
Muutos englanninkieliseen termiin "requests for information" --> "FOIA requests"  KT "freedom of information act requests"

Finto/asiakaspalaute KK-02763226
**[Finto] Tietopyynnöillä väärä muunkielinen termi**

Hei, Tietopyynnöillä on YSO:ssa muunkielinen termi "**requests for information**".  Tämä EI kuitenkaan tarkoita julkisuuslain mukaista tietopyyntöä, mitä tietopyyntö YSO:ssa tarkoittaa. 

Requests for information (RFI) on englanninkielellä: "_The RFI is a solicitation document used to obtain general information about products, services, or suppliers. It is an information request, not binding on either the supplier or the purchaser, and is often used prior to specific requisitions for items_."   Eli liittyy tarjouksen laatimiseen ja osoitettu lähinnä yrityksille. 

Tietopyyntö viittaa tiedon saamiseen viranomaisilta julkisuuslain nojalla. Sen sijaan englanninkielinen synonyymi tietopyynnölle on hankala asia. Kyseessä on tavallisesti Freedom of Information request (FOI request), mutta sillä nimellä haut toimivat huonosti/vajaasti, koska freedom of information on laaja käsite joka kattaa muutakin kuin tietopyynnöt. Yleiseksi käytänteeksi on tullut käyttää lyhennettä "**FOIA**", tietopyynnön tekeminen on "**file a FOIA**". Tämä tulee Yhdysvaltain ja Iso-Britannian julkisuuslakien Freedom of Information Act nimestä. Ja vaikka muissa maissa on erinimiset julkisuuslait,  niin englanninkielisessä kirjallisuudessa "FOIA" tai "**FOIA request**" on tavallinen, kirjoittajien kotimaasta riippumatta. Olen parhaillaan tekemässä kirjallisuuskatsausartikkelia tietopyyntöjen käytöstä tutkimusvälineenä, saanen oikeasta käsitteestä paremmin selkoa sen yhteydessä.

**Comment by YSO-kokous** [comment]
Päätös: Työstetään edelleen

**Comment by mirmaid** [comment]
Jos tarvitaan tarkenne, voisiko se olla a) viranomaisjulkisuus, b) julkisuuslaki, c) julkisuusperiaate?

**Comment by mariaforsen** [comment]
Olisiko selkein sitten julkisuuslaki?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _tietopyynnöt (julkisuuslaki)_,

**Comment by mariaforsen** [comment]
Sv. begäranden om information (offentlighetslagen)

**Comment by mirmaid** [comment]
Ehdotettu englanninkielinen muoto lisätty ohjaustermiksi, suomalaisten viranomaisten käyttämä muoto pääterminä tarkenteella varustettuna.
