### ISSUE TITLE
ranskanruusu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4867]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ranskanruusu 

#### Ehdotettu termi ruotsiksi   

provinsros / gallicaros 

#### Ehdotettu termi englanniksi   

Gallica rose 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ruusut](http://www.yso.fi/onto/yso/p13886) 

#### exactMatch   

LCSH : <Gallica rose http://id.loc.gov/authorities/subjects/sh96006858> 

#### Perustelut ehdotukselle   

Tarvitaan teoksen kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Upeat ranskanruusut / Pirjo Rautio 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [ranskanruusu](http://finto.fi/yse/fi/page/Y504867)

**Comment by mirmaid** [comment]
Wikipedia: Gallianruusu https://fi.wikipedia.org/wiki/Gallianruusu (samoin laji.fi ja [Kassu](http://finto.fi/kassu/fi/page/k14560)), ruots. monikossa Gallikarosor, ja toisaalta yksikössä _provinsros_.
Kassu myös [ranskanruusut](http://finto.fi/kassu/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fkassu%2Fk8469)

Gallicarosor, eller provinsrosor (Rosa Gallica-gruppen) är en grupp av rosor. De har alla sitt ursprung i arten provinsros (Rosa gallica) och kan vara mutationer av den rena arten eller, mer eller mindre, komplexa hybrider med andra arter.

**Comment by mirmaid** [comment]
Jos otetaan muoto ranskanruusu (ei lajinimi), monikko on varmaan oikein ja viittaa kaikkiin puutarharuusuihin joita kutsutaan ranskanruusuiksi.

**Comment by PaiviLipsanen** [comment]
Kannatan yksikköä - ranskanruusu - Rosa Gallica-Ryhmä (Kassu), lienevät gallianruusun lajikeiden risteymiä (Lähde: Viljelykasvien nimistö v. 2012, Kassussa on monikko, mutta lähteenä on mainittu Viljelykasvien nimistön vanhempi painos)

gallianruusu (laji) - Rosa gallica (Kassu)
https://finto.fi/kassu/fi/page/k14560

**Comment by mirmaid** [comment]
Hyväksytty muodossa ranskanruusut (YSA-kokous 7.3.2017).
