### ISSUE TITLE
näkösyvyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4868]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

näkösyvyys 

#### Ehdotettu termi englanniksi   

Secchi depth 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ominaisuudet](http://www.yso.fi/onto/yso/p8691) 

#### Assosiatiiviset (RT)   

[vedenlaatu](http://www.yso.fi/onto/yso/p15738) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 

#### Perustelut ehdotukselle   

Tarvitaan väitöskirjan kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/168525 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [näkösyvyys](http://finto.fi/yse/fi/page/Y504868)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/N%C3%A4k%C3%B6syvyys
http://tieteentermipankki.fi/wiki/Biologia:n%C3%A4k%C3%B6syvyys

**Comment by mirmaid** [comment]
Melindassa 4 kertaa, joista kerran näkökykyyn (mykiö näkösyvyys) liittyvänä. Googlella kuitenkin lähes kaikki viitteet liittyvät vedenlaatuun.

**Comment by mariaforsen** [comment]
Sv. siktdjup.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
siktdjup
ET visibilitetsdjup
