### ISSUE TITLE
intersektionaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4869]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

intersektionaalisuus 

#### Ehdotettu termi ruotsiksi   

intersektionalitet 

#### Ehdotettu termi englanniksi   

intersectionality 

#### Tarkoitusta täsmentävä selite   

Länsimaisen sukupuolentutkimuksen kenttää on jo pitkään muokannut kiinnostus intersektionaalisuuden kysymyksiin. Se tarkoittaa, että yksilön identiteettiin ja asemoitumiseen yhteiskunnallisissa valtasuhteissa vaikuttavat sukupuolen lisäksi monet muutkin erot, kuten yhteiskuntaluokka, ikä, etninen tausta ja seksuaalinen suuntautuminen.

Intersektionaalisuus ei silti ole pelkästään monien eri yhteiskunnallisten erontekojen yhtäaikaista vaikuttamista vaan viittaa nimenomaan siihen, miten ne vaikuttavat toisiinsa. Esimerkiksi naisena oleminen on erilaista keski-ikäiselle valkoiselle heteroseksuaaliselle naiselle kuin nuorelle tummaihoiselle homoseksuaaliselle naiselle. https://www.thl.fi/fi/web/sukupuolten-tasa-arvo/sukupuoli/sukupuolentutkimus/intersektionaalisuus-sukupuolentutkimuksessa
http://wom.fi/tasa-arvotietoa/tasa-arvosanasto/#sanasto3 

#### Perustelut ehdotukselle   

Vastaava termi puuttuu YSAsta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-91-40-69362-4 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

**Ehdottajan nimi:** Anneli Renfors 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** anneli.renfors@btj.fi **Termiehdotus Fintossa:** [intersektionaalisuus](http://finto.fi/yse/fi/page/Y504869)

**Comment by mirmaid** [comment]
10 kertaa Melindassa

https://en.wikipedia.org/wiki/Intersectionality

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
intersektionalitet
