### ISSUE TITLE
äänielokuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4870]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

äänielokuva 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elokuvahistoria](http://www.yso.fi/onto/yso/p27553) 

#### Perustelut ehdotukselle   

Äänielokuvan murroksesta on runsaasti kirjallisuutta ja tutkimusta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The dawn of the sound Essays by Robert Gitt & al., ed. by Mary Lea Bandy New York : Museum of Modern Art, 1989. - 56 s. : kuv. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

**Ehdottajan nimi:** Timo Matoniemi 
**Ehdottajan organisaatio:** Kansallinen audiovisuaalinen instituutti 
**Ehdottajan sähköpostiosoite:** timo.matoniemi@kavi.fi **Termiehdotus Fintossa:** [äänielokuva](http://finto.fi/yse/fi/page/Y504870)

**Comment by mirmaid** [comment]
_Mykkäelokuvat_ on monikossa. (samoin muut elokuva-loppuiset, _elokuva_ on yksikössä ja monikossa)

Melindassa kolme kertaa yksikössä.

**Comment by mariaforsen** [comment]
Sv. ljudfilm/filmer

**Comment by mirmaid** [comment]
Hyväksytty monikossa (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
ljudfilmer
