### ISSUE TITLE
monikanavaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4871]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[monikanavaisuus](http://www.yso.fi/onto/ysa/Y161756) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritellään/rajataan merkitykset. Nyt myös ryhmä 00. Sen jälkeen päätetään ruotsinkieliset vastineet (nyt multikanalsystemet). 

#### Perustelut ehdotukselle   

Termit eivät saa olla monimerkityksisiä, eikä tässä tilanteessa ole mahdollista kääntää yksiselitteisesti. Ongelma todettu YSO-kokouksessa. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mariaforsen** [comment]
Melinda-osumien perusteella näyttää siltä että voitaiisin yleismerkityksessä mahdollisesti kääntää "via flera kanaler" (mikä ei ole tyypillinen/hyvä asiasana, mutta tästä ei myöskään ole mahdollista saada vastaavaa muotoa (-uus) ruotsiksi). Kauppakontekstissa käytetään sanaa "omnikanal".

**Comment by LeKorsu** [comment]
Paha tapaus, jos pitää monia tarkenteita ruveta miettimään.  Niin moninaisissa yhteyksissä sitä on käytetty. "monikanavaisuus (kauppa / liiketoiminta)" lienee selkeimpiä.

**Comment by satuniininen** [comment]
Englanniksi tällä hetkellä multichannel system.

Myös multichannel marketing ja multichannel marketing system ovat yleisesti käytössä.

**Comment by mirmaid** [comment]
Melindan viitteissä lähinnä markkinointi, viestintä, kauppa tai palvelut, mutta myös esim. tekstinkäsittely https://ia.net/topics/multichannel-text-processing/

Jonkin verran tästä näkökulmasta vääriäkin viitteitä (moniaistisuus, monikanavainen äänentoisto), suurin osa kuitenkin ok.

**Comment by mirmaid** [comment]
Google: monikanavainen asiakaspalvelu n. 2000 kertaa, monikanavainen viestintä x 918, monikanavainen kauppa x 918, monikanavainen markkinointi x 1650. Yksi ratkaisumahdollisuus on ottaa nämä kaikki erillisinä.

**Comment by mariaforsen** [comment]
Viimeksi mainitut tuntuvat turhan tarkoilta, mutta olisi kyllä mahdollista kääntää tyyliin "flerkanalig kundservice", "flerkanalig kommunikation".. Olisiko tässä tapauksessa kuitenkin parempi pitää vain monikanavaisuus=via flera kanaler?

**Comment by YSA-kokous** [comment]
monikanavaisuus = via flera kanaler
