### ISSUE TITLE
kuulontutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4872]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuulontutkimus](http://www.yso.fi/onto/ysa/Y206086) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vrt. kuulonmittaus. Selvennys termeihin, esim. lisäämällä huomautus, sulkutarkenne tai ratkaisemalla vastaavalla tavalla kuin Mesh:issä (kuulonmittaus, kuulontutkimus > audiometria). On nyt ruotsiksi hörselforskning ja YSOssa eng. hearing examination (eivät siis täsmää). Sekä kuulonmittaus että kuulontutkimus käytetty vain vähän Melindassa. JUHO-asiantuntijat toivoivat ratkaisua YSOn puolella (eivät halunneet käyttää kuulonmittaus-termiä kuulontutkimuksesta lääketieteellisenä toimenpiteenä (niissä voidaan tehdä muitakin tutkimuksia kuin vain mittauksia kuinka hyvin kuulee jne.) 

#### Perustelut ehdotukselle   

Ks. esim. Kuuloliitto.fi, Mesh... Kuulontutkimus käytetty (Googlessa) yleensä nimenomaan kuulontutkimuksista lääketieteellisinä toimenpiteinä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Onko ehdotus että nämä yhdistetään ja termi olisi joko audiometria tai kuulontutkimus?

**Comment by mariaforsen** [comment]
Pääasia on ettei ainakaan sekoiteta kuulontutkimus tutkimustoimintana (hörselforskning) ja kuulontutkimus lääketieteellisenä toimenpiteenä (hörselundersökning) samaan termiin. Mutta ainakin JUHO-asiantuntijat olivat ymmärtääkseni sitä mieltä että (varsinkin nykyään) on kuulonmittaus-termi liian kapea (eikä enää paljoa käytetty) että voisi korvata kuulontutkimus-termiä (lääketieteellisenä toimenpiteenä) kokonaan. Siis oltiin sitä mieltä että kyllä nykyään käytetään enemmin kuulontutkimus-termiä kun tehdään kuulon"mittauksia" ja muita kuulontutkimuksia ihmisille. Näin myös Kuuloliitolla: http://www.kuuloliitto.fi/fin/kuulo/kuuleminen/kuulontutkimus/ 

Tarvitaanko muuten kuulontutkimusta tutkimustoimintana? Vai voisiko siihen riittää että laittaa "kuulo" ja "tutkimus"?

**Comment by mirmaid** [comment]
Ah, vasta nyt ymmärrän että kuulontutkimusta voi ajatella myös tutkimustoimintana...YSAssa on myös _näöntutkimus_ ja suomeksi _kuulontutkimus_ taitaa olla käytetympi kuin audiometria, mutta molemmat mun puolestani ok. Lääketieteen sanakirjan mukaan tosin audiometria = kuulonmittaus.

**Comment by mirmaid** [comment]
Yhdistetään kuulonmittaus KÄ kuulontutkimus, KT audiometria (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Sv. hörselundersökning ET audiometri ET hörselprov ET hörselmätning
