### ISSUE TITLE
versifikaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4874]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

versifikaatio 

#### Ehdotettu termi ruotsiksi   

versifikation 

#### Ehdotettu termi englanniksi   

versification 

#### exactMatch   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:versifikaatio> 

#### Vaihtoehtoiset termit ja ilmaisut   

runomuotoon tekeminen 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

runomuotoon saattaminen; runomuoto ja -rakenne runomittoineen, riimeineen ja säkseitösommitelmineen 

#### Perustelut ehdotukselle   

Versifikaatiota tai runomuotoon tekemistä on vaikea kuvailla eksaktisti ilman tarkkaa käsitettä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Text and tune, ISBN 978-3-0343-1560-9 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi **Termiehdotus Fintossa:** [versifikaatio](http://finto.fi/yse/fi/page/Y504874)

**Comment by mirmaid** [comment]
Kerran Melindassa, tietueessa myös LCSH-termi Versification, joka viittaa ilmeisesti ennenkaikkea metriikkaan (450 Metrics), vrt. myös https://en.wikipedia.org/wiki/Versification. Myös Tieteen termipankin määritelmä edellä kattaa useampia merkityksiä. YSAssa on _metriikka_.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
versifikation /ne

**Comment by mirmaid** [comment]
En löydä tästä juuri mitään suomeksi, vain tämän http://www.elore.fi/raportti-kaytannon-asiaa-metriikasta/ ja siinäkin kyse metriikasta.

**Comment by OutiHintikka** [comment]
Ehdottomasti tärkeä termi.

**Comment by mirmaid** [comment]
^ mutta missä merkityksessä?

**Comment by mirmaid** [comment]
• överföring till versform ⟨mindre brukl.⟩: egenhändigt hoptotade ~er
BET.NYANS: om det sätt på vilket en vers är uppbyggd

**Comment by OutiHintikka** [comment]
Kuten YSAssa on määritelty se liittyy metriikkaan. Jos otamme eksakteja metriikan termejä, tämä mukaan silloin. 
Silmäilin pikäisesti - nyt  - tuon artikkelin.  Ihan uusi näkökulma! Saattaa tulla jotain RAP-tutkimustam, mutta eihän se nyt ole akuutti asia.

**Comment by mirmaid** [comment]
Versification may be:
- the art of making verses, see poetry
- the theory of the phonetic structure of verse, see metre (poetry)
- the rendition of a prose work into verse, especially of classical works during the Middle Ages, see medieval poetry
- the subdivision of the books of the Bible into "verses", see Versification (Bible)
https://en.wikipedia.org/wiki/Versification

**Comment by OutiHintikka** [comment]
Myös tätä! :)


  *   the rendition of a prose work into verse, especially of classical works during the Middle Ages, see medieval poetry


the theory of the phonetic structure of verse, see metre (poetry)

the rendition of a prose work into verse


/outi
________________________________
Lähettäjä: mirmaid <notifications@github.com>
Lähetetty: 15. toukokuuta 2017 17:08
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] versifikaatio (#4874)


Versification may be:

  *   the art of making verses, see poetry
  *   the theory of the phonetic structure of verse, see metre (poetry)
  *   the rendition of a prose work into verse, especially of classical works during the Middle Ages, see medieval poetry
  *   the subdivision of the books of the Bible into "verses", see Versification (Bible)
https://en.wikipedia.org/wiki/Versification
Versification - Wikipedia<https://en.wikipedia.org/wiki/Versification>
en.wikipedia.org
Versification may be. the art of making verses, see poetry; the theory of the phonetic structure of verse, see metre (poetry) the rendition of a prose work into verse ...

**Comment by mariaforsen** [comment]
Sv. versifikation
