### ISSUE TITLE
hintavaikutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4875]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hintavaikutukset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vaikutukset](http://www.yso.fi/onto/yso/p795) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Sain ehdotuksen THL:n informaatikolta, joka on käyttänyt asiasanaa useamman kerran vapaasanana kuvaillessaan aineistoja, ja hän pyysi minua lisäämään sen TEROon. Asiasana menee kuitenkin TEROn aihealueen ulkopuolelle, joten ehdotan sitä lisättäväksi YSOon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

THL:n Julkarissa olevien aineistojen 

**Ehdottajan nimi:** Johanna Eerola (Pia Portforsin puolesta) 
**Ehdottajan organisaatio:** THL 
**Ehdottajan sähköpostiosoite:** johanna.eerola@thl.fi **Termiehdotus Fintossa:** [hintavaikutukset](http://finto.fi/yse/fi/page/Y504875)

**Comment by mirmaid** [comment]
Ei Melindassa, ketjua _vaikutukset - hinnat_ käytetty 18 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
priseffekter
ET prispåverkningar
ET prisverkningar
