### ISSUE TITLE
lehtialaindeksi | LAI

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4877]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lehtialaindeksi | LAI 

#### Ehdotettu termi englanniksi   

leaf area index 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Tarkoitusta täsmentävä selite   

Tieteen termipankki 1.12.2016: Kasvitiede:lehtialaindeksi. (Tarkka osoite: http://www.tieteentermipankki.fi/wiki/Kasvitiede:lehtialaindeksi.) 

#### Perustelut ehdotukselle   

Keskeinen termi  maatalous-metsätieteellisessä kasvustojen kartoituksissa ja muissa tutkimuksissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. Estimation of leaf area index and the fraction of absorbed photosynthetically active radiation in a boreal forest, väitöskirja (2015) 

**Ehdottajan nimi:** Anne Uusitalo 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** anne.uusitalo@helsinki.fi **Termiehdotus Fintossa:** [lehtialaindeksi | LAI](http://finto.fi/yse/fi/page/Y504877)

**Comment by mirmaid** [comment]
Melindassa 10 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
bladyteindex
ET LAI
