### ISSUE TITLE
metsälauha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4878]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsälauha 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Metsälauha on yksi Suomen tavallisimmista heinäkasveista 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/endosphere-microbial-community-assemblage-of-an-inland-sand-dune-colonizing-plant 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [metsälauha](http://finto.fi/yse/fi/page/Y504878)

**Comment by mirmaid** [comment]
Heinäkasvilaji https://laji.fi/taksoni/MX.40567?locale=fi#show

**Comment by mariaforsen** [comment]
Sv. kruståtel

**Comment by mirmaid** [comment]
Lisätty samalla myös lauhat @mariaforsen

**Comment by mariaforsen** [comment]
Allärs: 
kruståtel

lauhat = tåtlar
