### ISSUE TITLE
seurakuntahistoriat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4880]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seurakuntahistoriat](http://www.yso.fi/onto/ysa/Y98798) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodoksi "seurakuntahistoriikit". 

#### Perustelut ehdotukselle   

Ilmaisua "seurakuntahistoriikit" on käytetty (arvattavasti vahingossa) Melindassa, joten on syytä saada näkyviin ei-käytettäväksi. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
