### ISSUE TITLE
New York

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4881]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[New York](http://www.yso.fi/onto/ysa/Y105663) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite jaettava kahtia eli oma terminsä kaupungille ja osavaltiolle, esim. RDA:n mukaiset "New York (New York, Yhdysvallat)" edelliselle ja "New York (Yhdysvallat)" jälkimmäiselle. 

#### Perustelut ehdotukselle   

Yksi käsite ei voi (ainakaan auktorisoidussa) sanastossa viitataan useaan käsitteeseen samaan aikaan. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
_Let's hear it for New York, New York, New York_ 

Ainakaan jälkimmäinen muoto _New York (Yhdysvallat)_ ei taida rajata halutulla tavalla.
