### ISSUE TITLE
Lehdistötiedote

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4882]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Lehdistötiedote 

#### Ehdotettu termi ruotsiksi   

Pressmeddelande 

#### Ehdotettu termi englanniksi   

Press Release 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tiedotteet](http://www.yso.fi/onto/yso/p37) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan Tullin uuteen verkkopalveluun, joka julkaistaan tammikuussa 2017. Palvelu hyödyntää julkishallinnon ontologiaa (JUHO) sekä Yleistä Suomalaista ontologiaa (YSO). Tiedotukseen liittyen tarvetta laajentaa sanastoa kolmella tiedottamiseen/tiedotteeseen liittyvällä termillä: - lehdistötiedotteet - asiakastiedotteet - häiriötiedotteet. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tullin verkkopalvelu 

**Ehdottajan nimi:** Mikko Lappalainen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** mikko.lappalainen@helsinki.fi **Termiehdotus Fintossa:** [Lehdistötiedote](http://finto.fi/yse/fi/page/Y504882)

**Comment by mariaforsen** [comment]
Ok ruotsin osalta.

**Comment by mirmaid** [comment]
Hyväksytty

**Comment by LeKorsu** [comment]
Miksi tämä on yksikössä? YSOssa on asiakastiedotteet, lehdistötiedotteet jne.

**Comment by mirmaid** [comment]
Ehdotus on tehty yksikössä mutta termi on hyväksytty monikossa.

**Comment by mariaforsen** [comment]
Allärs:
pressmeddelanden
