### ISSUE TITLE
Asiakastiedote

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4883]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Asiakastiedote 

#### Ehdotettu termi ruotsiksi   

Kundmeddelande 

#### Ehdotettu termi englanniksi   

Customer Notice 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tiedotteet](http://www.yso.fi/onto/yso/p37) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan Tullin uuteen verkkopalveluun, joka julkaistaan tammikuussa 2017. Palvelu hyödyntää julkishallinnon ontologiaa (JUHO) sekä Yleistä Suomalaista ontologiaa (YSO). Tiedotukseen liittyen tarvetta laajentaa sanastoa kolmella tiedottamiseen/tiedotteeseen liittyvällä termillä: - lehdistötiedotteet - asiakastiedotteet - häiriötiedotteet. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tullin verkkopalvelu 

**Ehdottajan nimi:** Mikko Lappalainen 
**Ehdottajan sähköpostiosoite:** mikko.lappalainen@helsinki.fi 
**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [Asiakastiedote](http://finto.fi/yse/fi/page/Y504883)

**Comment by mariaforsen** [comment]
Ok ruotsin osalta.

**Comment by mirmaid** [comment]
Hyväksytty

**Comment by mariaforsen** [comment]
Allärs:
kundmeddelanden
