### ISSUE TITLE
Häiriötiedote

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4884]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Häiriötiedote 

#### Ehdotettu termi ruotsiksi   

störningsmeddelande 

#### Ehdotettu termi englanniksi   

service disruption notice 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tiedotteet](http://www.yso.fi/onto/yso/p37) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan Tullin uuteen verkkopalveluun, joka julkaistaan tammikuussa 2017. Palvelu hyödyntää julkishallinnon ontologiaa (JUHO) sekä Yleistä Suomalaista ontologiaa (YSO). Tiedotukseen liittyen tarvetta laajentaa sanastoa kolmella tiedottamiseen/tiedotteeseen liittyvällä termillä: - lehdistötiedotteet - asiakastiedotteet - häiriötiedotteet. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tullin verkkopalvelu 

**Ehdottajan nimi:** Mikko Lappalainen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** mikko.lappalainen@helsinki.fi **Termiehdotus Fintossa:** [Häiriötiedote](http://finto.fi/yse/fi/page/Y504884)

**Comment by mariaforsen** [comment]
Kyseenalainen ruotsinnos, mutta käytetään toki suomalaisilla sivustoilla (joidenkin yritysten, tullin jne.).  "Störningsinformation" paljon käytetty.

**Comment by MikkoAleksanteri** [comment]
> Kyseenalainen ruotsinnos, mutta käytetään toki suomalaisilla sivustoilla (joidenkin yritysten, tullin jne.). "Störningsinformation" paljon käytetty.

@mariaforsen uusi ehdotus ruotsin käännökseksi Tullilta: _meddelande om driftstörning_

**Comment by mirmaid** [comment]
Hyväksytty

**Comment by mariaforsen** [comment]
Allärs:
meddelanden om driftstörning
ET störningsinformation
