### ISSUE TITLE
Katkotiedote

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4885]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Katkotiedote 

#### Ehdotettu termi ruotsiksi   

Driftavbrott 

#### Ehdotettu termi englanniksi   

Service interruption 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tiedotteet](http://www.yso.fi/onto/yso/p37) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan Tullin uuteen verkkopalveluun, joka julkaistaan tammikuussa 2017. Palvelu hyödyntää julkishallinnon ontologiaa (JUHO) sekä Yleistä Suomalaista ontologiaa (YSO). Tiedotukseen liittyen tarvetta laajentaa sanastoa kolmella tiedottamiseen/tiedotteeseen liittyvällä termillä: - lehdistötiedotteet - asiakastiedotteet - häiriötiedotteet. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tullin verkkopalvelu 

**Ehdottajan nimi:** Mikko Lappalainen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** mikko.lappalainen@helsinki.fi **Termiehdotus Fintossa:** [Katkotiedote](http://finto.fi/yse/fi/page/Y504885)

**Comment by mariaforsen** [comment]
Driftavbrott viittaa itse katkoon, ei mihinkään tiedotteeseen. 
Joillakin sivuilla käytetään "avbrottsmeddelande" (joka vastaa suoraan suomenkielistä termiä, mutta ei ole vakiintunut..) "Driftsmeddelande" käytetään aika paljon sekä näistä että häiriötiedotteista. "Avbrottsinformation" paljon käytetty ruotsalaisilla sivuilla, mutta lähinnä sähköverkoista. Myös "meddelande om avbrott" mahdollinen.

**Comment by MikkoAleksanteri** [comment]
Uudet ehdotukset käännöksiksi Tullilta: 

englanti: _service interruption notice_
ruotsi: _meddelande om driftavbrott_

**Comment by mirmaid** [comment]
Hyväksytty

**Comment by mariaforsen** [comment]
Allärs: 
meddelanden om driftavbrott 
ET avbrottsmeddelanden
ET meddelanden om avbrott
