### ISSUE TITLE
Alajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4886]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Alajärvi](http://www.yso.fi/onto/ysa/Y94084) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa sekä kuntaa että järveä 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:
Alajärvi (kaupunki)
Alajärvi (järvi) - Etelä-Pohjanmaa

Lisäksi YSAssa oli jo Alajärvi- Kanta-Häme, joka korjattu muotoon -> Alajärvi (järvi) - Kanta-Häme

Korjattu Melindaan 2.1.2017.
