### ISSUE TITLE
Konnevesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4889]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Konnevesi](http://www.yso.fi/onto/ysa/Y106166) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska on sekä kunta että järvi 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:
Konnevesi (kunta)
Konnevesi (järvi)

Korjattu Melindaan 29.12.2016.
