### ISSUE TITLE
Petäjävesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4890]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Petäjävesi](http://www.yso.fi/onto/ysa/Y107116) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa sekä kuntaa että järveä 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:
Petäjävesi (kunta)
Petäjävesi (järvi)

Korjattu Melindaan 28.12.2016
