### ISSUE TITLE
Saarijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4891]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Saarijärvi](http://www.yso.fi/onto/ysa/Y94389) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa sekä kaupunkia että järveä 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Saarijärvi (kaupunki)

Saarijärvi (järvi) -- Espoo
Saarijärvi (järvi) -- Juuka
Saarijärvi (järvi) -- Mikkelin maalaiskunta
Saarijärvi (järvi) -- Saarijärvi (kaupunki)
Saarijärvi (järvi) -- Suomussalmi, Saarijärven aarnialue
Saarijärvi (järvi) -- Suomussalmi, Yli-Vuokki
Saarijärvi (järvi) -- Taivalkoski

Korjattu Melindaan 13.10.2017
