### ISSUE TITLE
Jämijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4895]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Jämijärvi](http://www.yso.fi/onto/ysa/Y94174) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska nykyinen tarkoittaa sekä kuntaa että järveä 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:
Jämijärvi (kunta)
Jämijärvi (järvi)

Korjattu Melindaan 28.12.2016
