### ISSUE TITLE
Isojärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4897]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Isojärvi](http://www.yso.fi/onto/ysa/Y112748) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista neljään osaan, koska tarkoittaa (ainakin) neljää eri järveä: "Isojärvi on järvi Keuruulla, Multialla, Kuhmoisissa sekä Mäntsälän ja Pornaisten kuntien rajalla. " 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:

Isojärvi (Keuruu)
Isojärvi (Kruunupyy)
Isojärvi (Kuhmoinen)
Isojärvi (Multia)
Isojärvi (Mäntsälä)
ja muutettu YSA:ssa ollut Isojärvi -- Satakunta muotoon Isojärvi (Pomarkku)

Korjattu Melindaan 16.3.2017.
