### ISSUE TITLE
Joutjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4898]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Joutjärvi](http://www.yso.fi/onto/ysa/Y139495) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa kahta eri järveä: "Joutjärvi on järvi Janakkalassa ja Lahdessa" 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Joutjärvi (Janakkala)
Joutjärvi (Lahti)

Korjattu Melindaan 16.3.2017
