### ISSUE TITLE
Kaukjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4900]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kaukjärvi](http://www.yso.fi/onto/ysa/Y118235) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdotettu muutos   

Ehdotan jakamista kolmeen, koska tarkoittaa kolmea eri järveä: "Kaukjärvi on järvi Tammelassa, Uudessakaupungissa ja Viipurin läänin Uudellakirkolla." 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Kaukjärvi (Tammela)
Kaukjärvi (Uusikaupunki)

Korjattu Melindaan 17.3.2017
