### ISSUE TITLE
Lauttaoja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4902]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Lauttaoja](http://www.yso.fi/onto/ysa/Y124951) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa kahta eri puroa: "Puro Taivalkoskella ja Pudasjärvellä" 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:

Lauttaoja (Pudasjärvi)
Lauttaoja (Taivalkoski)

Korjattu Melindaan 16.3.2017
