### ISSUE TITLE
Liesjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4903]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Liesjärvi](http://www.yso.fi/onto/ysa/Y139486) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kolmeen, koska tarkoittaa kolmea eri järveä: "Liesjärvi on järvi Keuruulla, Maaningalla ja Tammelassa." 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Liesjärvi (Keuruu)
Liesjärvi (Kuopio)
Liesjärvi (Tammela)

Korjattu Melindaan 17.3.2017
