### ISSUE TITLE
Nuasjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4904]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Nuasjärvi](http://www.yso.fi/onto/ysa/Y104976) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia koska tarkoittaa kahta eri järveä: "Nuasjärvi on järvi Sotkamossa ja Pellossa." 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:
Nuasjärvi (Pello)
Nuasjärvi (Sotkamo)

Korjattu Melindaan 16.3.2017
