### ISSUE TITLE
Paalijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4906]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Paalijärvi](http://www.yso.fi/onto/ysa/Y112489) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa kahta eri järveä: "Paalijärvi on järvi Alajärvellä ja Riihimäellä." 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Paalijärvi (Riihimäki)
Paalijärvi (Alajärvi)

Korjattu Melindaan 20.2.2017
