### ISSUE TITLE
Punkaharju

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4907]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Punkaharju](http://www.yso.fi/onto/ysa/Y94354) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia, koska tarkoittaa sekä kuntaa että harjua: "Punkaharju on sekä harju että kunta Etelä-Savossa. " 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Punkaharju (harju)
Punkaharju (kunta)

Korjattu Melindaan 20.3.2017.
