### ISSUE TITLE
Särkijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4908]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Särkijärvi](http://www.yso.fi/onto/ysa/Y111308) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista koska tarkoittaa ainakin kymmentä eri järveä: "Särkijärvi on järvi Asikkalassa, Hämeenkyrössä, Juvalla, Karjalohjalla, Kiteellä, Kuivaniemellä, Leppävirralla, Muoniossa, Punkaharjulla ja Utajärvellä." 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:

Särkijärvi (Asikkala)
Särkijärvi (Hämeenkyrö)
Särkijärvi (Ii)
Särkijärvi (Juva)
Särkijärvi (Kitee)
Särkijärvi (Laitila)
Särkijärvi (Leppävirta)
Särkijärvi (Lohja)
Särkijärvi (Muonio)
Särkijärvi (Puolanka)
Särkijärvi (Savonlinna)
Särkijärvi (Tampere)
Särkijärvi (Tohmajärvi)
Särkijärvi (Utajärvi)

Korjattu Melindaan 16.3.2017
