### ISSUE TITLE
Sääksjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4909]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Sääksjärvi](http://www.yso.fi/onto/ysa/Y109187) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista koska tarkoittaa ainakin viittä eri järveä: "Sääksjärvi on järvi Kokemäellä, Lempäälässä, Mäntsälässä, Rautalammilla ja Vimpelissä. " 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Sääksjärvi (Hyvinkää)
Sääksjärvi (Kokemäki)
Sääksjärvi (Lempäälä)
Sääksjärvi (Mäntsälä)
Sääksjärvi (Rautalampi)
Sääksjärvi (Vimpeli)

Korjattu Melindaan 20.2.2017
