### ISSUE TITLE
Takajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4910]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Takajärvi](http://www.yso.fi/onto/ysa/Y112886) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista neljään koska tarkoittaa neljää eri järveä: "Takajärvi on järvi Askolassa, Hattulassa, Kemissä ja Ranualla. " 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:

Takajärvi (Askola)
Takajärvi (Hattula)
Takajärvi (Kemi)
Takajärvi (Ranua)

Korjattu Melindaan 20.2.2017
