### ISSUE TITLE
Tarvasjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4911]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Tarvasjoki](http://www.yso.fi/onto/ysa/Y105727) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahtia koska tarkoittaa sekä jokea että entistä kuntaa: "Tarvasjoki on sekä entinen kunta että joki Varsinais-Suomessa." 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:

Tarvasjoki (kunta)
Tarvasjoki (joki)

Korjattu Melindaan 11.01.2017
