### ISSUE TITLE
Vehmersalmi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4912]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Vehmersalmi](http://www.yso.fi/onto/ysa/Y106675) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista koska tarkoittaa sekä entistä kuntaa että salmea: "On sekä kunta että salmi Itä-Suomen läänissä." Lisäksi huomautusta voisi vielä täsmentää sanomalla että kysymys on entisestä kunnasta, nyt se käy ilmi vain epäsuorasti. 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Vehmersalmi-salmesta ei löydy aineistoja Melindasta. Lisäksi YSA:ssa hyvin vähän salmia, lähinnä vain suuria esim. Beringinsalmi, Bosporinsalmi.  Muokattu YSAn Vehmersalmi koskemaan vain entistä kuntaa.

Melindassa ei siis korjattavaa.
