### ISSUE TITLE
Virojoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4913]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Virojoki](http://www.yso.fi/onto/ysa/Y107962) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista koska tarkoittaa sekä jokea että kylää: "On sekä joki Etelä-Karjalassa että Virolahden keskustaajama, kylä" 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
YSA:ssa erikseen Virolahti - Virojoki. 

Lisätty joelle tarkenne Virojoki (joki), ja lisäksi lisätty ohjaustermi Virojoki (kylä) -> Virolahti - Virojoki.

Melindassa ei viitteitä joesta, joten ei korjattavaa.
