### ISSUE TITLE
Vähäjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4914]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Vähäjärvi](http://www.yso.fi/onto/ysa/Y108260) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan jakamista kahteen tai kolmeen koska voi tarkoittaa kolmea eri järveä: "Vähäjärvi on järvi Kälviällä ja Riihimäellä." Oikeasti Riihimäellä on kaksi suunnilleen yhtä isoa Vähäjärveä, jotka ovat melkein vierekkäin, joten pitäisi myös täsmentää kumpaa niistä tarkoitetaan. 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSA:ssa:

Vähäjärvi (Kokkola)
Vähäjärvi (Pirkkala)
Vähäjärvi (Riihimäki) 
Vähäjärvi (Salo)

Korjattu Melindaan 16.3.2017
