### ISSUE TITLE
Välijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4915]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Välijoki](http://www.yso.fi/onto/ysa/Y105143) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Välijokia on Suomessa kymmeniä. Käsite pitäisi jakaa tarpeen mukaan ja tarkentaa, mitä kymmenistä eri Välijoista tarkoitetaan. 

#### Perustelut ehdotukselle   

Nykytilanne aiheuttaa vaikeuksia Paikannimirekisteri-linkityksessä ja on muutenkin epätarkkaa 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Lisätty YSA:an tarkenne Välijoki (Evijärvi) ja korjattu Melindaan
