### ISSUE TITLE
vahataulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4919]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vahataulut 

#### Ehdotettu termi ruotsiksi   

vaxtavlor 

#### Ehdotettu termi englanniksi   

wax tablets 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjoitusvälineet](http://www.yso.fi/onto/yso/p9432) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 
[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Tarkoitusta täsmentävä selite   

Antiikissa ja keskiajalla käytetty puinen tai norsunluinen levymäinen kirjoitusalusta, joka oli sivelty ohuella vahakerroksella.
Vrt. Wikipedia https://fi.wikipedia.org/wiki/Vahataulu 

#### Perustelut ehdotukselle   

En löytänyt YSAsta muuta tarkoitukseen sopivaa käsitettä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Roman London's first voices: writing tablets from the Bloomberg excavations, 2010-14 / Roger Tomlin, 9781907586408 https://helka.finna.fi/Record/helka.2962692 

**Ehdottajan nimi:** Pirja Kara 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** pirja.kara@helsinki.fi **Termiehdotus Fintossa:** [vahataulut](http://finto.fi/yse/fi/page/Y504919)

**Comment by mirmaid** [comment]
Iconclassissa

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
vaxtavlor
