### ISSUE TITLE
Poukan talo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4920]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Poukan talo 

#### Tarkoitusta täsmentävä selite   

Kulttuurihistoriallinen rakennus Laitilassa. Entinen Poukan tilan päärakennus 1700-luvulta. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Poukasta, kertomuksia suvustani ja Poukan talosta sekä tietoa Laitilasta / Lauri Väättänen (978-952-93-7882-1) 

#### Perustelut ehdotukselle   

Rakennus on paikallisesti tunnettu ja siitä on tähän mennessä ilmestynyt jo pari kirjaa. 

**Ehdottajan nimi:** Anna Viitanen 
**Ehdottajan organisaatio:** Turun kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** anna.viitanen@turku.fi **Termiehdotus Fintossa:** [Poukan talo](http://finto.fi/yse/fi/page/Y504920)

**Comment by mirmaid** [comment]
https://www.laitila.fi/palvelut/kulttuuripalvelut/tilat/poukan-talo/

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
Poukka hus
