### ISSUE TITLE
vertaisarviointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4921]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vertaisarviointi](http://www.yso.fi/onto/ysa/Y130235) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Merkitys pitäisi selventää joko "jakamalla", lisäämällä tarkenne/huomautus tms. 

#### Perustelut ehdotukselle   

Termillä on kaksi eri merkitystä ja on myös käytetty näissä molemmissa merkityksissä: 
1. käytäntö jossa tieteelliseen julkaisuun tarjottu artikkeli, apurahahakemus tms. alistetaan saman alan asiantuntijoiden arvioitavaksi.
2. arviointimenetelmiä jotka perustuvat työsuoritusten, tuotteiden, palvelujen tms. vertailuun. Vertaisarviointi vertailukehittämisen osana.

Ruotsinkielinen vastine valitaan/lisätään tämän jälkeen. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/738

**Comment by mirmaid** [comment]
Voihan eläimen käsi :weary:. Eikö mitään muuta sanaa ole voinut keksiä...oisko tuohon tarkenteet sitten (arviointimenetelmät) ja (julkaiseminen tms.)?

**Comment by LeKorsu** [comment]
Mieleen tulleita vaihtoehtoja: vertaisarviointi (jullkaiseminen / tiede / tiedejulkaiseminen)
Tuo arviointimenetelmät on hyvä tuohon toiseen.

**Comment by mirmaid** [comment]
vertaisarviointi (arviointimenetelmät) ja vertaisarviointi (tieteellinen julkaiseminen) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Sv.
-jämförande utvärdering ET jämförande granskning
-referentgranskning ET inbördes utvärdering ET kollegial granskning ET peer review ET sakkunnigbedömning
