### ISSUE TITLE
koulutettavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4922]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koulutettavuus](http://www.yso.fi/onto/ysa/Y102746) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko mahdollista selventää merkitystä esim. jakamalla, lisäämällä tarkenne/huomautus tms.? 

#### Perustelut ehdotukselle   

Nyt käytetty Melindassa sekä eläinten koulutettavuudesta että ihmisten. Ruotsiksi vastine on "bildbarhet", joka ei käy eläinten kohdalla ollenkaan. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/702

**Comment by mirmaid** [comment]
Käytetty Melindassa kerran koirista, kerran hevosista ja kerran poroista. Yhteensä myös vain 28 kertaa. Riittäisikö koulutettavuus (eläimet) KÄ eläinten koulutus?

**Comment by mirmaid** [comment]
Jaetaan koulutettavuus (eläimet) ja koulutettavuus (ihmiset) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
-bildbarhet
-dresserbarhet
