### ISSUE TITLE
hitupihtisammal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4926]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hitupihtisammal 

#### Ehdotettu termi ruotsiksi   

vedtrådmossa 

#### Ehdotettu yläkäsite YSOssa (LT)   

[maksasammalet](http://www.yso.fi/onto/yso/p18221) 

#### Vaihtoehtoiset termit ja ilmaisut   

Cephalozia macounii 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa
https://laji.fi/taksonomia/MX.44277?locale=fi#show 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hitupihtisammalta etsimässä. Teoksessa: Metsän salainen elämä, ISBN 978-952-495-398-6 (2016), s. 126-137 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [hitupihtisammal](http://finto.fi/yse/fi/page/Y504926)

**Comment by mirmaid** [comment]
Sammallaji https://laji.fi/taksoni/MX.44277?locale=fi

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
vedtrådmossa
