### ISSUE TITLE
kiilukärpäset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4927]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kiilukärpäset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kärpäset](http://www.yso.fi/onto/yso/p9953) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85038848.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

Dolichopodidae 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kiilureita ja päpsiäisiä. Teoksessa: Metsän salainen elämä, ISBN: 978-952-495-398-6 (2016), s. 168-179 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kiilukärpäset](http://finto.fi/yse/fi/page/Y504927)

**Comment by mirmaid** [comment]
Laji.fi Dolichopodidae https://laji.fi/taksoni/MX.277063?locale=fi

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs: 
styltflugor
