### ISSUE TITLE
kultapistiäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4928]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kultapistiäiset 

#### Ehdotettu termi ruotsiksi   

guldsteklar 

#### Ehdotettu yläkäsite YSOssa (LT)   

[myrkkypistiäiset](http://www.yso.fi/onto/yso/p24452) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85025431.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

Chrysididae 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan  ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lentävät jalokivet. Teoksessa: Metsän salainen elämä, ISBN: 978-952-495-398-6 (2016), s. 180-191 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kultapistiäiset](http://finto.fi/yse/fi/page/Y504928)

**Comment by mirmaid** [comment]
Hyönteisheimo https://laji.fi/taksoni/MX.203985?locale=fi

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
guldsteklar
