### ISSUE TITLE
muurahaiskorennot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4929]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muurahaiskorennot 

#### Ehdotettu termi ruotsiksi   

myrlejonsländor 

#### Ehdotettu termi englanniksi   

antlions 

#### Ehdotettu yläkäsite YSOssa (LT)   

[verkkosiipiset](http://www.yso.fi/onto/yso/p1982) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85005478.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

Myrmeleontidae 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Verkkosiipien havinaa. Teoksessa: Metsän salainen elämä, ISBN: 978-952-495-398-6 (2016), s. 192-203 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [muurahaiskorennot](http://finto.fi/yse/fi/page/Y504929)

**Comment by mirmaid** [comment]
Hyönteisheimo https://laji.fi/taksoni/MX.290387?locale=fi

Tämä on siis Muumien muurahaisleijona  :smile:

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs: 
myrlejonsländor
