### ISSUE TITLE
hiekkavalu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4930]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hiekkavalu 

#### Ehdotettu termi englanniksi   

sand casting 

#### Ehdotettu termi ruotsiksi   

sandgjute 

#### Ehdotettu yläkäsite YSOssa (LT)   

[valu](http://www.yso.fi/onto/yso/p4703) 

#### Alakäsitteet (RT)   

[painevalu](http://www.yso.fi/onto/yso/p6986) 
[ruiskuvalu](http://www.yso.fi/onto/yso/p20477) 

#### exactMatch   

hiekkavalu : ktta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576) 
[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi:amk-2016101315176 

#### Perustelut ehdotukselle   

Termiä käytetty Melindassa kentässä 653. 

**Ehdottajan nimi:** Anne Mikkanen 
**Ehdottajan organisaatio:** Savonia-amk 
**Ehdottajan sähköpostiosoite:** anne.mikkanen@savonia.fi **Termiehdotus Fintossa:** [hiekkavalu](http://finto.fi/yse/fi/page/Y504930)

**Comment by mirmaid** [comment]
Wikipedia sv. Råsandsgjutning

https://fi.wikipedia.org/wiki/Valaminen#Hiekkavalu

LCSH: Sand casting

**Comment by mariaforsen** [comment]
Mahdollisia ruotsinnoksia: sandgjutning, råsandsgjutning, sandformsgjutning. (MOTin sandgjute pitäisi korjata)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
sandgjutning
ET råsandsgjutning
ET sandformsgjutning
