### ISSUE TITLE
rusorahtusammal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4931]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rusorahtusammal 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rahtusammalet](http://www.yso.fi/onto/yso/p27508) 

#### Vaihtoehtoiset termit ja ilmaisut   

Cephaloziella rubella 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Rusorahtusammal ja sen kaverit. Teoksessa: Metsä salainen elämä. ISBN: 978-952-495-398-6 (2016), s. 348-359 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [rusorahtusammal](http://finto.fi/yse/fi/page/Y504931)

**Comment by mirmaid** [comment]
Sammallaji https://laji.fi/taksoni/MX.44285?locale=fi

**Comment by mariaforsen** [comment]
Sv. röd mikromossa.

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
röd mikromossa
