### ISSUE TITLE
kissankäpälälude

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4932]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kissankäpälälude 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luteet](http://www.yso.fi/onto/yso/p12851) 

#### Vaihtoehtoiset termit ja ilmaisut   

Galeatus spinifrons 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Antaa paahtaa sanoi lude. Teoksessa: Metsän salainen elämä, ISBN: 978-952-495-398-6 (2016), s. 360-371 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kissankäpälälude](http://finto.fi/yse/fi/page/Y504932)

**Comment by mirmaid** [comment]
Ludelaji https://laji.fi/taksoni/MX.229760?locale=fi

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
Galeatus spinifrons
