### ISSUE TITLE
erityisvartalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4933]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

erityisvartalot 

#### exactMatch   

erityisvartalot (KT kehonkaava, ongelmavartalot, ruumiinkuva) RT vartalo : ktta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

esimerkiksi lyhytkasvuisten, pitkien, tukevien ja erilaisten vartalotyyppien vaatteiden kaavoituksessa käyttökelpoinen asiasana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melinda-haku: erityisvartalot 

**Ehdottajan nimi:** Anne Mikkanen 
**Ehdottajan sähköpostiosoite:** anne.mikkanen@savonia.fi 
**Ehdottajan organisaatio:** Savonia-amk **Termiehdotus Fintossa:** [erityisvartalot](http://finto.fi/yse/fi/page/Y504933)

**Comment by mirmaid** [comment]
Melindassa 8 kertaa ktta-terminä. Ei juuri Google-osumia. TAOssa ja TSR-ontologiassa on myös termi _vartalotyypit_ (Melindassa 12 kertaa), joka tuntuisi neutraalimmalta vaikka todennäköisesti se viittaa lähinnä "tavallisiin" vartalonmuotoihin (esim. http://rullallakelalla.blogspot.fi/2015/05/vartalotyypit-ja-pukeutuminen.html), ei esim. hyvin lyhyisiin/pitkiin.

**Comment by Elmukelmu** [comment]
Erityisvartalot-termi taisi löytyä jostain (nyt jo edesmenneestä?) käsityöalan sanastosta. Aleksissa sitä on käytettykin käsityölehtien XL-ohjeiden indeksoinnissa. Tiedä sitten tuleeko kenellekään mieleen hakea termillä erityisvartalot??

**Comment by satuniininen** [comment]
Mieluummin vartalotyypit.

**Comment by mariaforsen** [comment]
Vartalotyypit hyvä. Sv. kroppstyper.

**Comment by mirmaid** [comment]
Hyväksytty vartalotyypit (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
kroppstyper
