### ISSUE TITLE
poimuhytykät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4934]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

poimuhytykät 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kantasienet](http://www.yso.fi/onto/yso/p21576) 

#### Vaihtoehtoiset termit ja ilmaisut   

Tremella 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sieni, joka eoli sienessä, joka eli puussa. Teoksessa: Metsän salainen elämä, ISBN: 978-952-495-398-6 (2016), s. 52-65 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [poimuhytykät](http://finto.fi/yse/fi/page/Y504934)

**Comment by mirmaid** [comment]
Sienisuku, laji.fi https://laji.fi/taksoni/MX.67210?locale=fi

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
Tremella
