### ISSUE TITLE
pienoiskirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4936]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pienoiskirjat 

#### Ehdotettu termi englanniksi   

miniature books 

#### Ehdotettu termi ruotsiksi   

miniatyrbok 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjat](http://www.yso.fi/onto/yso/p156) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85085643> 
Englanninkielinen Wikipedia : https://en.wikipedia.org/wiki/Miniature_book 

#### Vaihtoehtoiset termit ja ilmaisut   

miniatyyrikirjat, minikirjat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 
[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 

#### Tarkoitusta täsmentävä selite   

Kirja, jonka korkeus, leveys ja paksuus ovat kukin enintään 10 cm [tai jokin muu cm-määrä; ehdotettu LCSH:n mukainen]. 

#### Perustelut ehdotukselle   

Pienoiskirjojen kuvailemiseen ei ole tällä hetkellä mitään sopivaa termiä YSAssa, vaikka niitä sekä on julkaistu että niitä kerätään (ja niistä jotakin on jopa kirjoitettukin). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

(termin tarve tuli vastaan järjestäessäni HYK:n skandinaavisten kielten kokoelmaa, jossa on erityisiä luokkia pienikokoisille kirjoille) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [pienoiskirjat](http://finto.fi/yse/fi/page/Y504936)

**Comment by mirmaid** [comment]
Metatietosanasto ja Onix: Pienoiskokoinen kirja

Melindassa kerran aiheena _pienoiskirjat_.

**Comment by mariaforsen** [comment]
Ruotsiksi miniatyrböcker hyvä.

**Comment by mirmaid** [comment]
Kumpi muoto?

**Comment by mirmaid** [comment]
Hyväksytty muodossa pienoiskirjat (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
miniatyrböcker
