### ISSUE TITLE
televisioilmaisu (ja myös radioilmaisu)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4937]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

televisioilmaisu (ja myös radioilmaisu) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ilmaisu](http://www.yso.fi/onto/yso/p11843) 

#### Assosiatiiviset (RT)   

[elokuvailmaisu](http://www.yso.fi/onto/yso/p14398) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Sanaston yhteismitallisuuden vuoksi olisi hyvä olla em. termit sanastossa - ja ehkä myös termi: audiovisuaalinen ilmaisu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ett medialt museum : lärandets estetik i svensk television 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [televisioilmaisu (ja myös radioilmaisu)](http://finto.fi/yse/fi/page/Y504937)

**Comment by mirmaid** [comment]
Ei Melindassa.

YSAssa on _elokuvailmaisu, kirjallinen ilmaisu, kuvallinen ilmaisu, suullinen ilmaisu, teatteri-ilmaisu, valokuvailmaisu_ ja _visuaalinen ilmaisu_.

Google: radioilmaisu n. 1000, televisioilmaisu n. 300, audiovisuaalinen ilmaisu n. 500.

**Comment by mariaforsen** [comment]
Ei vastaavia termejä ruotsiksi.

**Comment by Elmukelmu** [comment]
Audiovisuaalinen ilmaisu olisi mukavan monipuolinen (televisio, video, elokuva)

**Comment by mirmaid** [comment]
Ehdotuksessa mainittu teos on ruotsinkielinen, mitä termejä siinä käytetään?

**Comment by LeKorsu** [comment]
En kannata yhteinäistä termiä audiovisuaalinen ilmaisu ainakaan ainoana käsitteenä. Radio ja televisio ovat ilmaisuiltaan (tai kerrontakeinoiltaan) erilaisia välineitä, juuri sen vuoksi, että toisessa on kuva ja toisessa ei. Meidän (Yle) kirjatietokannasta tulee 26 osumaa asiasanalle (oma mediasanastomme) "televisioilmaisu" ja 55 osumaa asiasanalle "radioilmaisu". Molempia on käytetty mm. tällaisessa teoksessa: "Presenting on TV and radio". Radioilmaisua on käytetty asiasanana mm. teoksissa "Korville piirretyt kuvat", gradussa "Läsnäolon vaikutelma Yleisradion radiouutisissa",  Televisioilmaisua puolestaan mm. teoksissa "Sight and sound motion : applied media aesthetics", "On camera : how to report, anchor and interview". 

Minulla ei ole nyt antaa mitään mahdollisia ruotsinkielisiä vastineita, mutta voisin kysellä Svenska Ylen väeltä. En uskalla luvata niitä tiistaiksi (en valitettavasti pääse itse paikalle tiistaina).

**Comment by mariaforsen** [comment]
Kannatan Svenska Ylen mielipiteen odottamista.

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by LeKorsu** [comment]
Svenska Yleltä henkilö, joka eniten on perehtynyt asiasanoittamiseen ja ontologioihin, vastasi että "onkin melko vaikea" mutta antoi sitten aika suorasanaiset käännökset "radiouttryck" ja "tv-uttryck". 

Vielä lainaus viestistä "Mutta ne ei ole vakiintuneita termejä (tietääkseni ainakin). Joten jos konteksti ei ole selvä niin ne voi olla melko vaikeasti ymmärrettäviä. Mikä olisi termien hierarkkinen paikka YSA:ssa? Ne tuotaisiin sitten myös YSO:on aikanaan?"

**Comment by ilona-x** [comment]
radioilmaisua ehdotettu myös aiemmin:
https://github.com/Finto-ehdotus/YSE/issues/338

**Comment by mariaforsen** [comment]
Yllä olevat termit ovat tosiaan jonkinlainen "hätäratkaisu" siinä tapauksessa, koska eivät ole varsinaisia ruotsinkielisiä sanoja. Ainakin Ruotsissa niitä ymmärrettäisiin ihan eri tavalla ("termer och uttryck"-merkityksessä), jos ollenkaan.

**Comment by OutiHintikka** [comment]
Kannatan; televiso- ja elokuvatutkimus on paljon ja näiden ilmaisumuodot eroavat oleellisesti esim. elokuvasta

**Comment by OutiHintikka** [comment]
Kannatan! Radio- ja televisiotutkimusta tehdään paljon; molemmilla on omat ilmaisumuotonsa.

**Comment by mirmaid** [comment]
elokuvailmaisu = filmuttryck. Ymmärrettäisiinkö "radiouttryck" ja "tv-uttryck" eri tavalla kuin filmuttryck, vai ymmärretäänkö sekin väärin (elokuvailmaukset?)?

**Comment by OutiHintikka** [comment]
elokuvailmaisu, mikäli teos on tehty televisio-elokuvana,  on sen ilmaisu erilaista kuin elokuvailmaisun. Yleensä intiimimpää. Toki on myös paljon intiimiä elokuvia.


radio/televisio-ilmaisu ovat ainakin suom.kielisellä puolella täysin vakiintuneita käsitteitä. itse tutkin muinaisessa pro-seminaarissa Huojuvaa taloa  ja siinä televisio-ilmaisun (t-teatterin) ja teatteri-ilmaisun eroja. Tutkimuspuolella raja on aika selvä.


Jos elokuvailmaisua käytetään televisioelokuvista, niin tällöin pitää mukana olla termi televisioelokuvat


/outi

________________________________
Lähettäjä: mirmaid <notifications@github.com>
Lähetetty: 15. toukokuuta 2017 16:08
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] televisioilmaisu (ja myös radioilmaisu) (#4937)


elokuvailmaisu = filmuttryck. Ymmärrettäisiinkö "radiouttryck" ja "tv-uttryck" eri tavalla kuin filmuttryck, vai ymmärretäänkö sekin väärin (elokuvailmaukset?)?

**Comment by YSA-kokous** [comment]
Ongelmakokous.

**Comment by mirmaid** [comment]
_Ilmaisu_ sv. _uttryckande_. Alakäsitteet joko muotoa -uttryck tai -framställning.

**Comment by mariaforsen** [comment]
Kyllä, -uttryck käytettynä tällä tavalla varmasti joko ei ymmärretä ollenkaan tai sitten väärinymmärretään (käytetään termer- ja uttryck merkityksessä, kuten esim. googlessakin näkyy, eikä tarkoitus varmaan ole että täytyy osata suomea ymmärtääkseen ruotsiksi valitun termin oikein..). Eli tämä täytyy varmaan ruotsiksi käsitellä vähän eri näkökulmasta, kenties esim. "framställning i film/radio/tv", "film/radio/tv som medium", "film som uttrycksform" tms.? Niin että merkitys vastaa suomenkielisen termin merkitystä.

**Comment by satuniininen** [comment]
Englanniksi myös aika kankea. Elokuvailmaisu = Cinematic expression, mutta nämä muut eivät oikein käänny samalla mallilla vaan vaativat fraasimaisen ratkaisun tyyliin _artistic expression in television/radio_ tjsp.

**Comment by YSA-kokous** [comment]
televisioilmaisu = framställning i tv
radioilmaisu = framställning i radio
elokuvailmaisu = framställning i film
teatteri-ilmaisu = ?
