### ISSUE TITLE
Informaatiomuotoilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4938]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Informaatiomuoitoilu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muotoilu](http://www.yso.fi/onto/yso/p6455) 

#### Assosiatiiviset (RT)   

[muotoilujohtaminen](http://www.yso.fi/onto/yso/p7802) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tieto näkyväksi :informaatiomuotoilun perusteet 

#### Perustelut ehdotukselle   

Termi on aika trendikäs. Muotoilu : informaatio ei ole kovin hyvä kuvaamaan em. ilmiötä. 

**Ehdottajan nimi:** outi hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [Informaatiomuoitoilu](http://finto.fi/yse/fi/page/Y504938)

**Comment by mirmaid** [comment]
Melindassa kaksi kertaa. 

https://fi.wikipedia.org/wiki/Informaatiomuotoilu

**Comment by mariaforsen** [comment]
Ruotsiksi informationsdesign ok. Ruotsiksi YSAn muotoilu on formgivning, eli sitä ei oikein voi ylipäätään käyttää tällaisissa tapauksissa.

**Comment by tpalonen** [comment]
Ohjaustermiksi infografiikka? 

Käsitteet ovat melko lähellä toisiaan. Wikipedia: "Closely related to the field of information graphics is information design, which is the creation of infographics".

Googlen fightin mukaan infographic on information designia selvästi käytetympi termi.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
informationsdesign
