### ISSUE TITLE
tilastografiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4939]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tilastografiikka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Tilastot ja grafiikka -termiyhdistelmä jää epätäsmälliseksi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tieto näkyväksi :informaatiomuotoilun perusteet 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [tilastografiikka](http://finto.fi/yse/fi/page/Y504939)

**Comment by mirmaid** [comment]
Melindassa kaksi kertaa. Ketjua _tilastot - graafinen esitys_ käytetty 16 kertaa.

YSAssa on _käyttögrafiikka_ ja _informaatiografiikka_.

**Comment by satuniininen** [comment]
Melindassa tilastot + visualisointi 23 kertaa

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
statistisk grafik
