### ISSUE TITLE
ruoka-asetelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4940]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruoka-asetelmat 

#### Ehdotettu termi englanniksi   

food styling 

#### Perustelut ehdotukselle   

On ruoka- ja keittokirjoja, joissa ruuan ulkonäön suunnittelu ja visuaalinen estetiikka on keskeinen tekijä, kun aihe esim. kuvanveistosmaiset kakut ja ateriat tai ruokakuvaus ja -markkinointi. Ruoka-alalla yleisesti käytettävä termi on food styling, jota lähinnä vastaava suomenkielinen sana, joskin hieman kapeampi semanttisesti, voisi olla ruoka-asetelmat. Vai voisiko ruoka-alalla vakiintunut englanninkielinen käsite food styling olla hyväksyttävä asiasana ihan sellaisenaan? 

#### Vaihtoehtoiset termit ja ilmaisut   

food styling, ruokamuotoilu 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://haku.helmet.fi/iii/encore/record/C__Rb2275733__Smuotoilu%20keittokirjat__P0%2C1__Orightresult__U__X1?lang=fin&suite=cobalt 

**Ehdottajan nimi:** Riku Nurkka 
**Ehdottajan sähköpostiosoite:** riku.nurkka@espoo.fi **Termiehdotus Fintossa:** [ruoka-asetelmat](http://finto.fi/yse/fi/page/Y504940)

**Comment by mirmaid** [comment]
Googlella suosituin termi näyttäisi olevan _ruokastailaus_. Melindassa ei mitään näistä.

**Comment by mariaforsen** [comment]
Ruoka-asetelma näyttää osittain viittaavan johonkin muuhun? ks. https://finto.fi/ic/fi/page/41C6  
Ruotsiksi olisi "matstyling" mahdollisesti ok, asetelmille voi olla vaikeampaa saada käännöstä (ellei pidäkään viitata stilleben:iin...)

**Comment by mirmaid** [comment]
Melindassa kerran _ruoka_ + _stailaus_.

**Comment by mirmaid** [comment]
Hyväksytty ruokastailaus (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
matstyling
