### ISSUE TITLE
Nuutin päivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4941]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Nuutin päivä 

#### Ehdotettu termi ruotsiksi   

tjugondag Knut (tjugondedag jul, Knut(s)dagen) 

#### Ehdotettu termi englanniksi   

Saint Knut's Day (St Knut's Day) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vuotuisjuhlat](http://www.yso.fi/onto/yso/p1080) 

#### Assosiatiiviset (RT)   

[joulu](http://www.yso.fi/onto/yso/p419) 

#### Vaihtoehtoiset termit ja ilmaisut   

nuutinpäivä, Nuutti 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Nuutin päivän perinteestä (erityisesti nuuttipukeista) on kirjoitettu kansatieteellisessä vuotuisjuhlia ja kalendaariperinteitä käsittelevässä kirjallisuudessa melko paljon, vaikka termiä on käytetty sisällönkuvailussa harvakseltaan. Viime aikoina kiinnostus nuuttipukki- ja muuhun Nuutin päivän perinteeseen on lisääntynyt ja perinnettä elvytetään monella taholla. Aiheesta siis etsitään tietoa ja uuttakin kirjallisuutta (erityisesti artikkeliaineistoa) tullee lisää. Päivää vietetään myös Ruotsissa.

Päivän nimellä on monenlaisia kirjoitusasuja, mutta Kotus suosittelee muotoa Nuutin päivä (Kulassa termi on ollut muodossa nuutinpäivä). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Deltagande observation i mörkret : tjugondag Knut på Iniö för tjugofem år sedan (Bulletin / Laboratorium för folk och kultur 2010/2).  Changes in the St Knut's Day mumming in Äetsä, Finland (Masks and mumming in the Nordic area, 2007). 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [Nuutin päivä](http://finto.fi/yse/fi/page/Y504941)

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
tjugondag Knut 
ET Knutdagen 
ET Knutsdagen
ET tjugondag jul
ET tjugondagknut
ET tjugondedag jul
ET tjugondedag Knut
