### ISSUE TITLE
kaniini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4942]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaniini 

#### Ehdotettu termi ruotsiksi   

vildkanin 

#### Ehdotettu termi englanniksi   

European Rabbit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kaniinit](http://www.yso.fi/onto/yso/p673) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85095844.html> 
Laji.fi : https://laji.fi/taksonomia/MX.50114?locale=fi#show 

#### Vaihtoehtoiset termit ja ilmaisut   

villikaniini, villikani, tamkanin, Oryctolagus cuniculus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

mm. opinnäytteitä 

#### Tarkoitusta täsmentävä selite   

http://laji.fi/taksonomia/MX.50114?locale=fi#show 

#### Perustelut ehdotukselle   

Aineistoa mm. citykaneista pääkaupunkiseudulla, Wikipedia: "Lemmikkikani eli kesykani on nimitys kaniinin (Oryctolagus cuniculus) kesylle, lemmikkieläimenä pidetylle muodolle"
https://fi.wikipedia.org/wiki/Lemmikkikani 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kaniini](http://finto.fi/yse/fi/page/Y504942)

**Comment by mirmaid** [comment]
Laji.fi:n lajinimi on _kani_ (samoin AFOssa), Melindassa 60 kertaa. Muotoa _kaniini_ käytetty tietoaineistossa 37 kertaa. Usein aineisto käsittelee lemmikkikaneja.

**Comment by mirmaid** [comment]
Toisaalta kani/kaniini on sukunsa ainoa laji, joten tuntuu vähän tarpeettomalta ottaa sanastoon sekä lajinimi että suku?

**Comment by mirmaid** [comment]
Muutetaan yksikköön > kani (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Sv. kanin ET europeisk kanin ET tamkanin ET vildkanin
