### ISSUE TITLE
nivhin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4944]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nivhin kieli](http://www.yso.fi/onto/ysa/Y167992) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodoiksi termit "giljakin kieli" ja "giljakki". 

#### Perustelut ehdotukselle   

Kyseisiä termejä näkee käytetyn (oli mm. HYK:n kokoelmahakemistossa), joten olisi hyvä saada viittaussuhde selväksi. Analogia YSAssa "giljakit" KÄ "nivhit". 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
