### ISSUE TITLE
kottarainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4945]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kottarainen 

#### Ehdotettu termi ruotsiksi   

stare 

#### Ehdotettu termi englanniksi   

Common Starling 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kottaraiset](http://www.yso.fi/onto/yso/p18001) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85129369.html> 
Laji.fi : https://laji.fi/taksoni/MX.36817?locale=fi#show 

#### Vaihtoehtoiset termit ja ilmaisut   

Sturnus vulgaris 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Yleinen lintu Suomessa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARTOssa 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kottarainen](http://finto.fi/yse/fi/page/Y504945)

**Comment by mirmaid** [comment]
Vaatii tarkenteen (laji) ja kottaraiset-termille tarkenteen (heimo). Melindan aineisto käsittelee mielestäni ainoastaan kottaraista (Sturnus vulgaris), termiä on käytetty yksikössä ja monikossa 7/11 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty tarkenteilla (laji) ja (heimo) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
stare (art)
starar (familj)
