### ISSUE TITLE
keruutuotteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4947]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

keruutuotteet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luonnontuotteet](http://www.yso.fi/onto/yso/p9545) 

#### Vaihtoehtoiset termit ja ilmaisut   

keräilytuotteet 

#### Tarkoitusta täsmentävä selite   

Luonnonmarjojen, ruokasienten, jäkälien ja muiden luonnontuotteiden keruu on tärkeä osa metsien
monikäyttöä. Puustoltaan ja rakenteeltaan monipuoliset metsät ylläpitävät hyviä keruumahdollisuuksia.
Metsän keräilytuotteista saatavat tulot voivat olla yksityistaloudellisesti ja paikallisesti merkittäviä. Metsien tärkeimpiä keruutuotteita ovat luonnonmarjat, ruokasienet, koristemateriaalit, villiyrtit, koivunmahla, pihka, pakurikääpä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://tapio.fi/wp-content/uploads/2015/12/MHS-Talousmetsien_Luonnonhoito_2015-12-31-TAPIO-1.pdf 

#### Perustelut ehdotukselle   

On esim. keruutuotetarkastajan erikoisammattitukinto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi

**Comment by PaiviLipsanen** [comment]
Metsätilastollisessa vuosikirjassa 2014 s. 206: Metsän keräilytuotteet - hand-picked nature products. s.195 Metsän keräilytuotteet:  Metsistä ja soilta kerätään luonnonmarjoja, -sieniä ja -yrttejä sekä muita luonnontuotteita, kuten puiden sivutuotteita ja koristemateriaaleja. Niistä saatavat tulot voivat
olla yksityistaloudellisesti ja paikallisesti merkittäviä. Taulukko s. 202.  
http://stat.luke.fi/sites/default/files/vsk14_koko_julkaisu.pdf

**Comment by PaiviLipsanen** [comment]
YSAssahan onkin jo keräilytuotteet, eli keruutuotteet tulisi sitten sen korvattavaksi.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
