### ISSUE TITLE
Juankoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4948]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Juankoski](http://www.yso.fi/onto/ysa/Y94168) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirrettävä päätermin Kuopio alle assosiatiiviseksi käsitteeksi. 

#### Perustelut ehdotukselle   

Juankoski liitetty Kuopioon 1.1.2017 

#### Ehdottaja   

Kukka-Maritta Taskinen 

#### Ehdottajan organisaatio   

Savonia-ammattikorkeakoulu 

#### Ehdottajan sähköpostiosoite   

kuka-maritta.taskinen@savonia.fi

**Comment by ilona-x** [comment]
Lisätty YSAan tieto kuntaliitoksesta ja korjattu linkitykset.
