### ISSUE TITLE
Hengellinen väkivalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4949]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Hengellinen väkivalta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

Suomen evankelis-luterilaisen kirkon yhteiskunnallisen työn väkivaltatyöryhmä määritteli hengellisen väkivallan käsitteen ensimmäisen kerran 1980-luvulla. Sen mukaan hengellinen väkivalta on uskonnollissävytteistä käyttäytymistä, jolla pyritään murtamaan tai nujertamaan uskonnollisin uhkauksin, vaatimuksin tai pakottein toisen ihmisen elämänkatsomus, elämäntapa tai mielipide.[2] Määritelmä ei anna täyttä kuvaa uskonnollisen väkivallan ongelman monimuotoisuudesta, sillä siihen liittyy paljon piiloon jääviä menetelmiä. Niitä ei aina osata tunnistaa. Väkivaltaa käyttävään ja siten haitalliseen uskonnolliseen ryhmään kuuluva ei lisäksi itse aina ymmärrä olevansa sellaisen jäsen. 

#### Perustelut ehdotukselle   

Viime aikoina termiä on käytetty paljon, ilmestynyt mm. kirjallisuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. Taivaan taimet : uskonnollinen yhteisöllisyys ja väkivalta / Johanna Hurtig. 

**Ehdottajan nimi:** Mervi Kivirinta 
**Ehdottajan organisaatio:** Diakonia-ammattikorkeakoulu 
**Ehdottajan sähköpostiosoite:** mervi.kivirinta@diak.fi **Termiehdotus Fintossa:** [Hengellinen väkivalta](http://finto.fi/yse/fi/page/Y504949)

**Comment by mirmaid** [comment]
Melindassa kaksi kertaa, kerran _uskonnollinen väkivalta_. Ketjua _uskonto - väkivalta_ käytetty 46 kertaa, ja _väkivalta - uskonto_ 72 kertaa. Myös yhdistelmiä _uskonnolliset yhteisöt_ + _väkivalta/henkinen väkivalta_ käytetty.

**Comment by mirmaid** [comment]
Aamenestä öylättiin: http://evl.fi/sanasto/-/glossary/word/Hengellinen+v%C3%A4kivalta

Uskonnollisella väkivallalla viittaa väkivaltaiseen käyttäytymiseen, jonka kohteena tai motiivina on uskonto. Tähän lukeutuu muun muassa uskonnollisiin instituutioihin, henkilöihin tai esineisiin kohdistuva väkivalta sekä väkivalta, jonka motiivina ovat joko väkivallan käyttäjän tai sen kohteen uskonnolliset käsitykset tai ominaisuudet. Uskonnollisella väkivallalla ei viitata ainoastaan uskonnollisten ryhmien harjoittamaan väkivaltaan, vaan myös sekulaarien ryhmien uskonnollisia rymiä kohtaan harjoittamaan uskonnon motivoimaan väkivaltaan.

Suomen evankelis-luterilainen kirkko kutsuu uskonnollisten yhteisöjen sisällä harjoitettavaa uskonnollista väkivaltaa hengelliseksi väkivallaksi ja määrittelee sen tarkoituksen olevan "toisen ihmisen elämänkatsomuksen, elämäntavan tai mielipiteiden nujertaminen". https://fi.wikipedia.org/wiki/Uskonnollinen_v%C3%A4kivalta

**Comment by Elmukelmu** [comment]
Näppituntumalla ainakin artikkeliaineistossa hengellinen väkivalta näyttäis terminä olevan vakiintumassa. Uskonnollinen väkivalta -fraasilla taas löytyy jonkin verran islamistiterroria etc.

**Comment by mirmaid** [comment]
Miten tämä kääntyy ruotsiksi? @mariaforsen

**Comment by satuniininen** [comment]
Englanniksi on käytössä spiritual violence ja religious violence, joskin jälkimmäistä käytetään paljon juuri terrorismin ja uskonsotien kontekstissa. 

https://en.wikipedia.org/wiki/Religious_violence
http://www.gov.nl.ca/VPI/types/#5

LCSHssa ketju Violence--Religious aspects

**Comment by mariaforsen** [comment]
Ruotsiksi religiöst våld (laajempi termi) ja andligt våld. Andligt våld lähinnä Suomessa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
andligt våld
