### ISSUE TITLE
tukeminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4950]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tukeminen](http://www.yso.fi/onto/ysa/Y113464) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT tuki. Mahdollisesti myös joihinkin muihin termeihin voisi lisätä tämän ohjaustermiksi (tukimuodot?). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty molempiin (YSA-kokous 7.3.2017).
