### ISSUE TITLE
pottaharjoittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4951]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pottaharjoittelu 

#### Ehdotettu termi ruotsiksi   

toaletträning 

#### Ehdotettu termi englanniksi   

toilet training 

#### Vaihtoehtoiset termit ja ilmaisut   

siisteyskavatus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Potträning på 3 dagar 

#### Perustelut ehdotukselle   

Kuvaava ilmaisu asialle,  ja on jo engl. + ruots. sanastoissa 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [pottaharjoittelu](http://finto.fi/yse/fi/page/Y504951)

**Comment by mirmaid** [comment]
YSAssa on _siisteyskasvatus_, jota on Kaunokki-terminä käytetty nimenomaan tässä tarkoituksessa Melindassa yli 70 kertaa.

**Comment by mirmaid** [comment]
Ehkä voisi olla ohjaustermi?

**Comment by mirmaid** [comment]
Hyväksytty ohjaustermiksi (YSA-kokous 7.3.2017).
