### ISSUE TITLE
prospektiivinen muisti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4952]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

prospektiivinen muisti 

#### Ehdotettu termi englanniksi   

prospective memory 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muisti (kognitio)](http://www.yso.fi/onto/yso/p2607) 
[säilömuisti](http://www.yso.fi/onto/yso/p19087) 

#### exactMatch   

LCSH : Prospective memory 

#### Tarkoitusta täsmentävä selite   

"Pitkäkestoisen säilömuistin tulevaisuuden muistamisesta vastaava osa, jonka avulla muistetaan tulevat asiat, tapahtumat ja määräajat." http://www.muistiliitto.fi/fi/muistiliitto/kasitteita/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Perustelut ehdotukselle   

Prospective memory -aiheisia teoksia löytyy Melindasta. Artossa käytetty prospektiivinen muisti -vapaana asiasanana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uef.finna.fi/Record/josku.1169669 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [prospektiivinen muisti](http://finto.fi/yse/fi/page/Y504952)

**Comment by mirmaid** [comment]
Google n. 100 kertaa suomeksi. 

https://en.wikipedia.org/wiki/Prospective_memory

**Comment by mariaforsen** [comment]
Sv. prospektivt minne.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
prospektivt minne 
ET framåtriktat minne
