### ISSUE TITLE
nastat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4953]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nastat](http://www.yso.fi/onto/ysa/Y165872) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

On monimerkityksinen termi ja se aiheuttaa myös ongelmia Allärsin/Allfon puolella. Ristiriitaista on myös se ett RT on kiinnitystarvikkeet, mutta asiasana on käytetty Melindassa vain kerran ja siellä nastarengas-merkityksessä (eli ei täsmää ollenkaan esim. ALLFOn ratkaisun kanssa (entä englanniksi?) Ruotsiksi mahdollisia vastineita esm. stift, häftstift, dubbar, tenar, nubbar.. Ks. MOT sanakirjat. Nyt Allärs: dubbar + häftstift, mutta ALLFOssa häftstift, ja suomeksi siitä linkitys YSAn nastoihin (ongelmallista kun merkitys YSAn puolella on avoin, mutta YSOssa määritelty tarkkaan)... 

#### Ehdotettu muutos   

Selvennys termin merkitykseen, esim. huomautuksella tai sulkutarkenteella? 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
_Nastarenkaat_ on erikseen, joten ei kai niitä nastoja tarvita sentään lisäksi :smile:. Tuon voisi ohjata jotenkin nastat (autonrenkaat) KÄ nastarenkaat tms.? Mun mielestä perusnasta on se millä laitetaan vaikka paperi kiinni ilmoitustauluun eli Kielitoimiston sanakirjan a. leveäkantainen lyhyt (tav. sormin painettava) kiinnitysnaula t. -piikki. = häftstift?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
