### ISSUE TITLE
työuraeläke

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4954]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

työuraeläke 

#### Perustelut ehdotukselle   

Eläkeuudistus vuoden 2017 alusta, esiintyy lehtiartikkeleissa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

lehtiartikkeleissa 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [työuraeläke](http://finto.fi/yse/fi/page/Y504954)

**Comment by mirmaid** [comment]
Työuraeläke on uusi eläkelaji, joka on suunnattu vähintään 63-vuotiaille työntekijöille. Eläke voidaan myöntää vuonna 1955 ja sen jälkeen syntyneille, joten ensimmäiset työuraeläkkeet voivat alkaa 1.2.2018.

Sinulla voi olla oikeus työuraeläkkeeseen, jos takana on pitkä vähintään 38 vuoden pituinen työura rasittuneisuutta ja kuluneisuutta aiheuttavassa työssä ja työkykysi on heikentynyt. https://www.tyoelake.fi/fi/erilaisiaelakkeita/tyouraelake/Sivut/default.aspx

**Comment by mariaforsen** [comment]
Ruotsiksi arbetslivspension ok.

**Comment by satuniininen** [comment]
Englanniksi ilmeisesti years-of-service pension, ks. http://www.elakeuudistus.fi/media/ladattavat-aineistot/tyoelakeuudistus_2017_esite_netti_eng.pdf

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
arbetslivspension
ET arbetskarriärspension
