### ISSUE TITLE
maataloustulo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4955]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maataloustulo](http://www.yso.fi/onto/ysa/Y97219) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö olla monikossa, kuten esim. metsätulot? 

#### Perustelut ehdotukselle   

Osa vastaavista sanoista ovat monikossa ja osa yksikössä..? Ruotsiksi tämä on tähän asti ollut monikossa (lantbruksinkomster). 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Vaikea kysymys! Esiintyy monessa paikassa "käsitteenä": https://portal.mtt.fi/portal/page/portal/taloustohtori/eufadnadvanced/taustatiedot/maataloustulo, http://tieteentermipankki.fi/wiki/Oikeustiede:maataloustulo. Myös EKS-sanastossa yksikössä, ruotsiksi monikko.

**Comment by satuniininen** [comment]
Myös metsätulosta puhutaan paljon yksikössä, mutta YSAssa se on monikossa: http://www.kunnat.net/fi/asiantuntijapalvelut/soster/asiakasmaksut-talous-rahoitus/asiakasmaksut/metsatulo/Sivut/default.aspx
Nämä kannattaisi varmaan yhdenmukaistaa jompaankumpaan suuntaan.

**Comment by LeKorsu** [comment]
Google antaa yksikkömuodoille molemmissa tapauksissa vähän enemmä osumia: metsätulo 4910 (y), 4220 (m), maataloustulo 5460 (y), 2010 (m). Monikkomuodossa se lisäksi kysyy "tarkoititko maataloustuet"?. Yhdenmukaistamista varmastikin kaipaa, mutta kumpi parempi yksikkö vai monikko, minulla ei selkeää kantaa. Tulot-asiasanan kaikki alakäsitteet monikossa, olisiko monikko siksi johdonmukaisempi tässäkin?

**Comment by mirmaid** [comment]
Ei muutosta (YSA-kokous 7.3.2017).
