### ISSUE TITLE
kuntapaikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4956]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuntapaikka 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oleskeluluvat](http://www.yso.fi/onto/yso/p6463) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Asiaa on hankala ilmaista millään muulla termillä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Turvapaikanhakijoiden sekä oleskeluluvan ja kuntapaikan saaneiden kunnalliset sote-palvelut 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [kuntapaikka](http://finto.fi/yse/fi/page/Y504956)

**Comment by mirmaid** [comment]
Monikko?

**Comment by mariaforsen** [comment]
Ruotsiksi kommunplatser ok.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
kommunplatser
