### ISSUE TITLE
urheilu-ura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4957]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

urheilu-ura 

#### Ehdotettu termi ruotsiksi   

idrottskarriär 

#### Ehdotettu termi englanniksi   

sports career? 

#### Assosiatiiviset (RT)   

[työura](http://www.yso.fi/onto/yso/p20671) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artikkeliaineiston sisällönkuvailussa, esim. Jarkko Niemisen laaja uran "lopetushaastattelu", artikkeli Tapio Rautavaaran urheilu-urasta 

#### Perustelut ehdotukselle   

Olen kokenut tämän käyttökelpoiseksi indeksoidessa henkilöhaastatteluja, joiden kohteilla on (ollut) myös mittava urheilutausta. Ysassa on työura, ja ammattilaisuuttahan urheilu nykyään pitkälti on 

**Ehdottajan nimi:** Leena Korsumäki 
**Ehdottajan sähköpostiosoite:** leena.korsumaki@yle.fi 
**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [urheilu-ura](http://finto.fi/yse/fi/page/Y504957)

**Comment by mirmaid** [comment]
YSAssa tällä hetkellä vain _työura_.

Melindassa 9 kertaa.

**Comment by satuniininen** [comment]
Riittäisikö kuvailussa ammattiurheilu + työura?

**Comment by mariaforsen** [comment]
Idrottskarriär hyvä termi ruotsiksi.

**Comment by LeKorsu** [comment]
Puolustan omaa termiehdotustani. Urheilu-ura on mielestäni huomattavasti helpompi hahmottaa kuin ammattiurheilu + työura. Selkeä ja todella yleinen käsite, otetaanhan tänne sanastoon mukaan huomattavasti paljon spesifempejä tieteenalatermejä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
idrottskarriär
ET sportkarriär
