### ISSUE TITLE
maku (arvostelukyky)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4958]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maku (arvostelukyky) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

Esim Bourdeau on puhunut paljon miten eliitti määrittää hyvän maun. Joten ainakin sosiologisessa aineistossa tämä olisi  relevantti termi.  ALEPHissa on joku kirjasto käyttänyt termiä tarkenteen kera maku (arvostelukyky). Minusta tämä oli aika hyvä käsiteyhdistelmä kuvaamaan em. ilmiötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Visuaalinen kuluttaminen :katseita, makuja ja muotokieliä 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [maku (arvostelukyky)](http://finto.fi/yse/fi/page/Y504958)

**Comment by mirmaid** [comment]
Jo YSOssa.

**Comment by Elmukelmu** [comment]
YSAssa on jo hyvä maku

**Comment by mirmaid** [comment]
Niinpä onkin. Ja _kirjallisuusmaku, taidemaku_ ja _musiikkimaku_. Vielä kyllä puuttuu huono maku...

**Comment by LeKorsu** [comment]
Maku (arvostelukyky) voisi sisältää sekä hyvän maun että huonon maun.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017). Toisen maku-termin sulkutarkenne YSOssa (aineen ominaisuudet). Palataan tähän seuraavassa kokouksessa.

**Comment by mariaforsen** [comment]
Sv. smak (omdöme)

**Comment by YSA-kokous** [comment]
Maku (aistimukset/aineen ominaisuudet) vrt. Melinda. Seuraava kokous.

**Comment by tpalonen** [comment]
YSOn käsitteellä on myös ohjausterminä "maku (aineen)" ja "maku (aistimus)". Näistä minusta ensimmäinen on parempi, nehän ovat kaksi eri asiaa. Mutta sinänsä tuo "maku (aineen ominaisuudet)" on riittävän selkeä ja YSOn puolella noudattaa myös sulkutarkennelinjausta eli sulkutarkenteeksi yläkäsite silloin, kun se on ymmärrettävä. Eli äänestän joka tapauksessa muotoa "maku (aineen ominaisuudet)".

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: makuaistilla tunnettava esineen, aineen tms. ominaisuus; makuaistin välittämä aistimus.

Flavor is the sensory impression of food or other substance, and is determined primarily by the chemical senses of taste and smell. https://en.wikipedia.org/wiki/Flavor

**Comment by mirmaid** [comment]
haju LT kemialliset ominaisuudet

**Comment by YSA-kokous** [comment]
maku (aineen ominaisuudet)
