### ISSUE TITLE
muukalaisviha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4959]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muukalaisviha](http://www.yso.fi/onto/ysa/Y109565) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö ksenofobia korvattuna terminä? 

#### Perustelut ehdotukselle   

Ks. MOT-sanastot jne. Ruotsiksi olisi ainakin syytä lisätä xenofobi termille främlingshat (oikeastaan främlingsfientlighet) niin kuin Svenska ämnesord:issa on tehty. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
