### ISSUE TITLE
euroopanmajava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4960]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

euroopanmajava 

#### Ehdotettu termi ruotsiksi   

europeisk bäver 

#### Ehdotettu termi englanniksi   

European Beaver 

#### Ehdotettu yläkäsite YSOssa (LT)   

[majavat](http://www.yso.fi/onto/yso/p3633) 

#### exactMatch   

Laji.fi : https://laji.fi/taksoni/MX.48251?locale=fi#show 

#### Vaihtoehtoiset termit ja ilmaisut   

Castor fiber 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Suomen alkuperäinen majavalaji 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. ARTO 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [euroopanmajava](http://finto.fi/yse/fi/page/Y504960)

**Comment by mirmaid** [comment]
https://laji.fi/taksoni/MX.48251?locale=fi

**Comment by mariaforsen** [comment]
Allärs: 
europeisk bäver
ET bäver 
ET eurasiatisk bäver

**Comment by mirmaid** [comment]
Hyväksytty.
