### ISSUE TITLE
amerikanmajava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4961]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

amerikanmajava 

#### Ehdotettu termi ruotsiksi   

kanadensisk bäver 

#### Ehdotettu termi englanniksi   

Canadian Beaver 

#### Ehdotettu yläkäsite YSOssa (LT)   

[majavat](http://www.yso.fi/onto/yso/p3633) 

#### exactMatch   

Laji.fi : https://laji.fi/taksoni/MX.48250?locale=fi#show 

#### Vaihtoehtoiset termit ja ilmaisut   

kanadanmajava, Castor canadensis 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Suomeen istutettu vieraslaji 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. ARTO 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [amerikanmajava](http://finto.fi/yse/fi/page/Y504961)

**Comment by mirmaid** [comment]
https://laji.fi/taksoni/MX.48250?locale=fi

**Comment by mariaforsen** [comment]
Allärs:
nordamerikansk bäver 
ET amerikansk bäver 
ET kanadabäver
ET kanadensisk bäver

**Comment by mirmaid** [comment]
Hyväksytty.
