### ISSUE TITLE
heinätavi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4962]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heinätavi 

#### Ehdotettu termi ruotsiksi   

årta 

#### Ehdotettu termi englanniksi   

Garganey 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puolisukeltajasorsat](http://www.yso.fi/onto/yso/p15219) 

#### exactMatch   

Laji.fi : https://laji.fi/taksonomia/MX.26388?locale=fi#show 

#### Vaihtoehtoiset termit ja ilmaisut   

Spatula querquedula, Anas querquedula 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Suomessa erittäin uhanalainen lintulaji. 
Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Heinätavikannan kehitys Suomessa : kannanmuutokset ja niihin vaikuttavat tekijät. Suomen Riista 61 (2015): s. 80-90 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [heinätavi](http://finto.fi/yse/fi/page/Y504962)

**Comment by mirmaid** [comment]
https://laji.fi/taksoni/MX.26388?locale=fi

**Comment by mariaforsen** [comment]
Allärs:
årta

**Comment by mirmaid** [comment]
Hyväksytty.
