### ISSUE TITLE
Miehittämättömät vesikulkuneuvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4963]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Miehittämättömät vesikulkuneuvot 

#### Perustelut ehdotukselle   

vrt. YSA 
miehittämättömät ilma-alukset, 
miehittämättömät ajoneuvot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Aikakauslehtiaineisto esim. TM : Tekniikan maailma 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

**Ehdottajan nimi:** Tina Mattsson 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** tina.mattsson@btj.fi **Termiehdotus Fintossa:** [Miehittämättömät vesikulkuneuvot](http://finto.fi/yse/fi/page/Y504963)

**Comment by mirmaid** [comment]
Löytyy (Google) _miehittämättömät laivat/alukset_, mutta jälkimmäistä, käyttökelpoisempaa käytetään myös avaruusaluksista. Miehittämättömät vesikulkuneuvot ei tuo viitteitä googlella. Myös _robottilaivat/veneet_.

https://en.wikipedia.org/wiki/Unmanned_surface_vehicle

**Comment by mirmaid** [comment]
Jätetään termiehdotukseksi (YSA-kokous 7.3.2017).

**Comment by ilona-x** [comment]
Tälle termille olisi ollut jälleen käyttöä julkaisun "D4V - Design for Value program report" kuvailussa.

Lisää termivaihtoehtoja: **itseohjautuvat laivat** & **autonomiset laivat** & **etäohjattavat laivat**

Linkki julkaisun suomenkieliseen versioon: http://hightech.dimecc.com/system/attachments/files/000/000/078/original/D4V-ohjelma_SU.pdf?1547474464

**Comment by LeKorsu** [comment]
Englanninkielinen wikipedia-artikkeli näyttää ohjaavan autonomisen laivan tuohon "miehittämättömään pintakulkuneuvoon". Varmasti tarpeellinen enenevässä määrin, mutta mikä olisi se termi, joka vakiintuu. Itselläni ei ole esittää varmaa kantaa juuri nyt, pähkäilen itseohjautuvuus / autonomisuus / miehittämättömyys.

**Comment by mirmaid** [comment]
Googlen hakutuloksissa kärkipaikkaa pitää tällä hetkellä _itseohjautuvat laivat_.

**Comment by YSA-kokous** [comment]
itseohjautuvat laivat + ohjaustermit

**Comment by mariaforsen** [comment]
Sv.  självstyrande fartyg ET självstyrda fartyg, obemannade fartyg, obemannade vattenfarkoster
