### ISSUE TITLE
kuusipeura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4964]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuusipeura](http://www.yso.fi/onto/ysa/Y108326) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT täpläkauris 

#### Perustelut ehdotukselle   

https://laji.fi/taksoni/MX.47484?locale=fi 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
Laji.fi: täpläkauris. Wikipedia: Nisäkäsnimistötoimikunta ehdotti vuonna 2008, että lajin suomenkieliseksi nimeksi vaihdettaisiin täpläkauris. Ehdotus on kuitenkin saanut osakseen arvostelua, ja esimerkiksi Suomen Metsästäjäliitto suosittelee käyttämään lajista edelleen metsästyslaissakin esiintyvää kuusipeura-nimeä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
