### ISSUE TITLE
saksanhirvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4965]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[saksanhirvi](http://www.yso.fi/onto/ysa/Y108328) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT isokauris, punahirvi 

#### Perustelut ehdotukselle   

https://laji.fi/taksoni/MX.47476?locale=fi 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
Laji.fi: isokauris

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
