### ISSUE TITLE
punasotka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4966]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

punasotka 

#### Ehdotettu termi ruotsiksi   

brunand 

#### Ehdotettu termi englanniksi   

Common Pochard 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sotkat](http://www.yso.fi/onto/yso/p14867) 

#### exactMatch   

Laji.fi : https://laji.fi/taksoni/MX.26407?locale=fi#show 
LCSH : <http://id.loc.gov/authorities/subjects/sh85103645.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

Aythya ferina 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

tarvitaan mm. ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARTO 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [punasotka](http://finto.fi/yse/fi/page/Y504966)

**Comment by mirmaid** [comment]
https://laji.fi/taksoni/MX.26407?locale=fi

**Comment by mariaforsen** [comment]
Allärs: 
brunand

**Comment by mirmaid** [comment]
Hyväksytty.
