### ISSUE TITLE
tukkasotka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4967]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tukkasotka 

#### Ehdotettu termi ruotsiksi   

vigg 

#### Ehdotettu termi englanniksi   

Tufted Duck 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sotkat](http://www.yso.fi/onto/yso/p14867) 

#### exactMatch   

Laji.fi : https://laji.fi/taksoni/MX.26415?locale=fi#show 
LCSH : <http://id.loc.gov/authorities/subjects/sh85138483.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

Aythya fuligula 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan ARTOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARTO 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [tukkasotka](http://finto.fi/yse/fi/page/Y504967)

**Comment by mirmaid** [comment]
https://laji.fi/taksoni/MX.26415?locale=fi

**Comment by mariaforsen** [comment]
Allärs: 
vigg

**Comment by mirmaid** [comment]
Hyväksytty.
