### ISSUE TITLE
vanhat tanssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4968]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vanhat tanssit](http://www.yso.fi/onto/ysa/Y196345) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö lisätä määritelmä? MUSA:ssa huomautus: 

    Nimitys 1900-luvun taitteessa suosituille seuratansseille, kuten mignon, pas d'Espagne, pas de quatre, krakoviak, wengerka, kickapoo ja wienervalssi.

    Termiä ei pidä sekoittaa Ruotsissa ja suomenruotsalaisten keskuudessa esiintyvään gammeldans-käsitteeseen, jolla tarkoitetaan kansanomaisia tansseja kuten valssi, jenkka, polkka, sottiisi, masurkka ja hambo.

Jos YSA:n termillä on sama merkitys..? 

#### Perustelut ehdotukselle   

Nykyistä päätermiä voi ymmärtää useilla tavoilla, "vanhat tanssit" voi myös viitata mihin tahansa vanhoihin tansseihin, sekä yllä mainittuihin tansseihin. Ruotsiksi ei vastinetta ennen kuin merkitys on selvä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Lisätään MUSAn huomautus?

**Comment by TommiViitamies** [comment]
Kannatan.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
