### ISSUE TITLE
Hämeen linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4969]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hämeen linna](http://www.yso.fi/onto/ysa/Y94146) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "Kronoborgin linna" (YSA) ja "Kronoborg" (Allärs) 

#### Perustelut ehdotukselle   

Tällaiset vanhat nimimuodot löytyvät linnalle 1860-luvulla useana painoksena ilmestyneestä Lustfärd till Avasaksa/Huvimatka Avasaksaan -julkaisusta. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
