### ISSUE TITLE
piitimensaame

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4970]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

piitimensaame 

#### Ehdotettu termi ruotsiksi   

pitesamiska 

#### Ehdotettu termi englanniksi   

Pite sami 

#### Ehdotettu yläkäsite YSOssa (LT)   

[saamen kieli](http://www.yso.fi/onto/yso/p18720) 

#### Assosiatiiviset (RT)   

[eteläsaame](http://www.yso.fi/onto/yso/p27284) 
[inarinsaame](http://www.yso.fi/onto/yso/p25599) 
[koltansaame](http://www.yso.fi/onto/yso/p25598) 
[kantasaame](http://www.yso.fi/onto/yso/p28321) 
[luulajansaame](http://www.yso.fi/onto/yso/p28656) 
[pohjoissaame](http://www.yso.fi/onto/yso/p25600) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Saamelaiskielet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Wilbur, Joshua (ed.): Pitesamisk ordbok : samt stavningsregler. https://utu.finna.fi/Record/volter.1837077 

#### Perustelut ehdotukselle   

Ei ole syytä, miksi tätä ei lisättäisi YSAan. Myös muut puuttuvat saamelaiskielet voisi lisätä YSA:an (uumajansaame, kiltinänsaame, turjansaame) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

**Ehdottajan nimi:** Ludvig Forsman 
**Ehdottajan organisaatio:** Turun yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ludvig.forsman@utu.fi **Termiehdotus Fintossa:** [piitimensaame](http://finto.fi/yse/fi/page/Y504970)

**Comment by mirmaid** [comment]
Voitaneen lisätä kaikki?

**Comment by mirmaid** [comment]
Lisätään kaikki.

**Comment by mariaforsen** [comment]
Allärs:
pitesamiska
ET arjeplogssamiska

uumajansaame=umesamiska 
kiltinänsaame=kildinsamiska 
turjansaame=tersamiska
