### ISSUE TITLE
symboliantropologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4971]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

symboliantropologia 

#### Ehdotettu termi ruotsiksi   

symbolantropologi 

#### Ehdotettu termi englanniksi   

symbolic anthropology 

#### exactMatch   

symbolic anthropology : <http://id.loc.gov/authorities/subjects/sh93000388> 

#### Vaihtoehtoiset termit ja ilmaisut   

symbolinen antropologia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

KULA-termi. Käytetty paljon sisällönkuvailussa (Melindassa 230 viitettä). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

"Symbolic anthropology: a reader in the study of symbols and meanings".  "The subject of anthropology: gender, symbolism and psychoanalysis" / Henrietta L. Moore. Ym. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [symboliantropologia](http://finto.fi/yse/fi/page/Y504971)

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
symbolantropologi
