### ISSUE TITLE
marjatuotteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4972]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

marjatuotteet 

#### Ehdotettu termi englanniksi   

berry products 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elintarvikkeet](http://www.yso.fi/onto/yso/p6580) 

#### Vaihtoehtoiset termit ja ilmaisut   

marjajalosteet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Tarkoitusta täsmentävä selite   

Käsite kattaa joukon erilaisia marjapohjaisia jalosteita esim. mehut, hillot, hyytelöt, kiisselit jne. 

#### Perustelut ehdotukselle   

Tarvitaan historiikin kuvailussa. Riitan Herkku valmistaa juustoja, marjatuotteita, konditoriatuotteita ja valmisruokia. Muille tuoteryhmille löytyy asiasanat.
https://www.riitanherkku.fi/tuotteet/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Priimaa: Riitan Herkun 30-vuotishistoriikki 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [marjatuotteet](http://finto.fi/yse/fi/page/Y504972)

**Comment by mirmaid** [comment]
Kerran Melindassa. 

YSAssa on _maitovalmisteet, munavalmisteet, viljavalmisteet_, toisaalta _kasvituotteet, puutarhatuotteet, soijatuotteet_.

**Comment by PaiviLipsanen** [comment]
AFOssa on marjavalmisteet, Eviran sivuilla mainitaan marjavalmisteet.

**Comment by LeKorsu** [comment]
Ruotsista ei taida olla apua tuotteiden tai valmisteiden valinnan välillä, bärprodukter kummassakin tapauksessa?

**Comment by mirmaid** [comment]
Hyväksytty muodossa marjavalmisteet (YSA-kokous 7.3.2017). KT marjatuotteet.

**Comment by mariaforsen** [comment]
Allärs: 
bärprodukter
