### ISSUE TITLE
Östersund

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4973]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Östersund 

#### Ehdotettu termi ruotsiksi   

Östersund 

#### Ehdotettu termi englanniksi   

Östersund 

#### exactMatch   

LCSH : Östersund (Sweden) 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/%C3%96stersund 

#### Vaihtoehtoiset termit ja ilmaisut   

Staare [kaupungin eteläsaamenkielinen nimi] 

#### Tarkoitusta täsmentävä selite   

Kaupunki Jämtlandin läänissä ja maakunnassa 

#### Perustelut ehdotukselle   

Kyseistä kaupunkia ei ennestään ole YSAssa, mutta sitä käsittelevää aineistoa on vanhastaan ja termille on myös uutta käyttöä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Östersund centrum: hus med historia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Östersund](http://finto.fi/yse/fi/page/Y504973)

**Comment by mirmaid** [comment]
Lisätty YSAan.
