### ISSUE TITLE
palkkapolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4974]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[palkkapolitiikka](http://www.yso.fi/onto/ysa/Y97969) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko mahdollista lisätä "solidarinen palkkapolitiikka" korvattuna terminä tai mahdollisesti uutena erillisenä asiasanana (sehän on oikeastaan alakäsite "palkkapolitiikka"-sanalle, eli eräänlainen palkkapolitiikka) ? 

#### Perustelut ehdotukselle   

Näin on jo kauan ollut ruotsiksi "solidarisk lönepolitik" -> "lönepolitik" 
Ks. esim. https://www.tyoelamasanasto.fi/s/solidaarinen-palkkapolitiikka/ 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Kerran Melindassa. Voidaan ottaa erikseenkin?

**Comment by mariaforsen** [comment]
Muun muassa viime aikojen keskustelujen valossa (siitä onko hyvä laittaa korvatuksi suppeampi termi) olisi ehkä syytä ottaa erillisenä terminä.

**Comment by mirmaid** [comment]
Hyväksytty erikseen (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
solidarisk lönepolitik /ne 
(ET raderas)
