### ISSUE TITLE
hallusinogeenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4975]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hallusinogeenit 

#### Ehdotettu termi ruotsiksi   

hallucinogener 

#### Ehdotettu termi englanniksi   

hallucinogens 

#### Ehdotettu yläkäsite YSOssa (LT)   

[huumeet](http://www.yso.fi/onto/yso/p5465) 
[psyykenlääkkeet](http://www.yso.fi/onto/yso/p7977) 

#### Alakäsitteet (RT)   

[LSD](http://www.yso.fi/onto/yso/p27460) 

#### Assosiatiiviset (RT)   

[huumekasvit](http://www.yso.fi/onto/yso/p23392) 
[harha-aistimukset](http://www.yso.fi/onto/yso/p10960) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Hallusinogeenit 
LCSH : <http://id.loc.gov/authorities/subjects/sh85058490.html> 
MeSH/FinMeSH : https://finto.fi/mesh/fi/page/D006213 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Tätä sanaa olisin kaivannut useiden lääketiedettä käsittelevien teosten kuvailussa. Esim. tietyt kirjat, jotka käsittelevät psyykelääkkeitä tai huumausaineiden käyttöä. YSA:sta löytyvä huumekasvit ei ole kuitenkaan riittävän laaja käsite (ei kuvaa synteettisiä huumeita). Myös huumeiden kulttuurihistoriaa yms. käsittelevien kuvailussa tätä tarvitsisi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.lehmanns.de/shop/geisteswissenschaften/2404195-9780753808511-cosmic-serpent ; https://www.abebooks.com/9780451494092/Good-Day-Microdosing-Made-Mega-0451494091/plp ;http://books.wwnorton.com/books/978-0-393-34451-6/ ; https://www.amazon.co.uk/High-Society-Mind-Altering-History-Culture/dp/0500289107  https://www.amazon.co.uk/Food-Gods-Original-Knowledge-Evolution/dp/0712670386/ref=sr_1_1?s=books&ie=UTF8&qid=1485869749&sr=1-1&keywords=9780712670388 

**Ehdottajan nimi:** Maija Tapio 
**Ehdottajan organisaatio:** Turun kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** maija.tapio@turku.fi **Termiehdotus Fintossa:** [hallusinogeenit](http://finto.fi/yse/fi/page/Y504975)

**Comment by mirmaid** [comment]
Lääketieteen termit: aistiharhoja aiheuttava aine

YSAssa on esim. _stimulantit, opioidit_.

LCSH-termi on Hallucinogenic drugs (Melindassa 33 kertaa). Termiä _hallusinogeenit_ käytetty vain 4 kertaa, vaikka se on FinMeSHissä. Myös TERO-ontologiassa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
hallucinogener
