### ISSUE TITLE
madeiraviini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4976]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

madeiraviini 

#### Ehdotettu termi ruotsiksi   

madeiravin 

#### Ehdotettu termi englanniksi   

Madeira wine 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viinit](http://www.yso.fi/onto/yso/p4750) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85079519> 
Wikipedia : https://fi.wikipedia.org/wiki/Madeira_(viini) 

#### Vaihtoehtoiset termit ja ilmaisut   

madeira (viini) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Portvinsdalen : en resa i portvinets värld 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi 
**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [madeiraviini](http://finto.fi/yse/fi/page/Y504976)

**Comment by mirmaid** [comment]
Kumpi muoto: madeiraviini vai madeira (viini)?

**Comment by mariaforsen** [comment]
Sv. madeiravin (ET madeira)

**Comment by LeKorsu** [comment]
Kielitoimiston sanakirjassa madeiraviini.

**Comment by mirmaid** [comment]
Sulkutarkenteella.

**Comment by mariaforsen** [comment]
Allärs:
madeiravin 
ET madeira (vin)
