### ISSUE TITLE
hardcore punk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4977]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hardcore punk 

#### Ehdotettu termi ruotsiksi   

hardcore punk 

#### Ehdotettu termi englanniksi   

hardcore punk 

#### Assosiatiiviset (RT)   

[indie rock](http://www.yso.fi/onto/yso/p21503) 
[black metal](http://www.yso.fi/onto/yso/p20679) 
[death metal](http://www.yso.fi/onto/yso/p26907) 
[heavy rock](http://www.yso.fi/onto/yso/p15521) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2003002059> 
Wikipedia (ENG) : https://en.wikipedia.org/wiki/Hardcore_punk 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Vaihtoehtoiset termit ja ilmaisut   

hard core ; HC ; hoocee ; hardcore (musiikki) 

#### Tarkoitusta täsmentävä selite   

Määritelmä: Punk rockista 1970-luvun lopusta lähtien kehittynyt nopeatempoisempi ja aggressiivisempi alalaji. Hardcore punkin sanoituksissa otetaan usein kantaa yhteiskunnallisiin aiheisiin vastustaen esimerkiksi militarismia, auktoriteetteja ja väkivaltaa. Paino on yleensä enemmän rytmissä kuin melodiassa ja laulu on usein huutavaa tai karjuvaa. Kitaraosuudet ovat toisinaan monitahoisia, teknisesti vaativia ja rytmillisesti haasteellisia. Kokoonpanossa on tyypillisesti laulajan ja säröisen kitaran lisäksi bassokitara ja rummut. 

#### Perustelut ehdotukselle   

Hardcore-yhtyeelle ei tällä hetkellä löydy sopivaa koloa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://viola.linneanet.fi/vwebv/holdingsInfo?bibId=615407 

**Ehdottajan nimi:** Katerina Sornova ja Toni Korpi 
**Ehdottajan organisaatio:** KK ja Espoon kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** katerina.sornova@helsinki.fi **Termiehdotus Fintossa:** [hardcore punk](http://finto.fi/yse/fi/page/Y504977)

**Comment by ksornova** [comment]
Yksi mahdollinen RT on myös trash metal (ei ole ysossa, mutta löytyy musasta).

**Comment by TommiViitamies** [comment]
"Hardcore punk" olisi ST "punk rockille" (MUSA). YSAssa taas muoto "punk", joka on sekä sosiologian että musiikin termi. Jälkimmäisessä roolissa se olisi muutettava muotoon "punk rock". Olisiko "hardcore punk" vain musiikkia, vai myös sen ympärillä ilmenevä muu kulttuuri?

Vielä: "trash metal" (po. thrash metal) on heavy rockin ST, joten sen RT "hardcore punkille" ei ole välttämättä perusteltu.

**Comment by ksornova** [comment]
Tarvitseeko tässä vaiheessa miettiä, onko LT punk vai punk rock? Jälkimmäinen sen tosiaan pitäisi olla. 

hardcore punk -termillä viitataan musiikkiin. Ja mielestäni määritelmässäkin puhutaan ainoastaan musiikissa.

thrash metalista on tosiaan tippunut h-kirjain pois. thrash metal on vain assosiatiivinen käsite, joten niillä ei käsittääkseni tarvitse olla sama LT.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
hardcorepunk
ET hardcore (punk)

**Comment by mirmaid** [comment]
LT toistaiseksi rock. En lisännyt ehdotettu KT-muotoja koska hardcore voi musiikissakin viitata myös ainakin teknoon (samoin HC). Ehdotetut RT-suhteet ovat varmaan ihan ok, mutta toisaalta niillä voisi luultavasti yhtä perustellusti olla myös muita vastaavia RT-suhteita. Voin lisätä ne jos saan Luumun yhteisen kannan asiaan.

**Comment by TommiViitamies** [comment]
LT punk rock

Mirjan KT-perustelu on minusta ok.

RT-suhteisiin Luumu ei ole (toistaiseksi) keksinyt mitään uutta. Ehkä nämä ovat sitten ok:

black metal
death metal
heavy rock
thrash metal

**Comment by ksornova** [comment]
KT-suhteissa säilyttäisin ainakin _HC_ ja _hoocee,_ ne voisi mennä näin:
_HC (hardcore punk)_ tai ihan _HC (punk)_
_hoocee (hardcore punk)_ tai ihan _hoocee (punk)_

Tommin yllä listatut RT:t on puolestani ok

LT punk rock voisi lisätä siinä vaiheessa, kun termi on ysassa

**Comment by TommiViitamies** [comment]
_KT-suhteissa säilyttäisin ainakin HC ja hoocee, ne voisi mennä näin:
 HC (hardcore punk) tai ihan HC (punk)
 hoocee (hardcore punk) tai ihan hoocee (punk)_

Puollan tätä.
