### ISSUE TITLE
kokemusasiantuntijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4978]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kokemusasiantuntijat 

#### Perustelut ehdotukselle   

Terveydenhuollossa kokemusasiantuntijat ovat tällä hetkellä erittäin ajankohtainen asia. Kokemusasiantuntijat eivät ole keitä tahansa asian kokeneita (siis eri asia kuin "kokemukset"). Kokemusasiantuntijat on koulutettu toimimaan terveydenhuollon työntekijöiden apuna. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ysa, Mesh 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [kokemusasiantuntijat](http://finto.fi/yse/fi/page/Y504978)

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/4145 ja https://github.com/Finto-ehdotus/YSE/issues/4146

**Comment by mirmaid** [comment]
Melindassa 6 kertaa. 

https://fi.wikipedia.org/wiki/Kokemusasiantuntija

http://www.kokemusasiantuntija.fi/

**Comment by mirmaid** [comment]
TERO-ontologiassa on _kokemusasiantuntijuus_.

**Comment by mariaforsen** [comment]
Ei ole Meshissä eikä suomenkielisellä wikipediasivulla tai TEROssa ole käännöksiä. Suomessa kuitenkin käytetty "erfarenhetsexpert", eli jos tämä otetaan niin sitä voidaan varmaan käyttää Allärsissakin.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
erfarenhetsexperter
