### ISSUE TITLE
defibrillaattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4979]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[defibrillaattorit](http://www.yso.fi/onto/ysa/Y196523) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

http://www.kotus.fi/nyt/kuukauden_sana/kuukauden_sanojen_arkisto/kuukauden_sanat_2016/sydaniskuri.22326.news

http://www.asema.eu/2016/11/defibrillaattori-on-nyt-virallisesti-sydaniskuri/ 

#### Ehdotettu muutos   

sydäniskurit (ainakin hakutermiksi, vaikka vanha säilyisi käytettävänä terminä) 

#### Ehdottaja   

Lassi Lager 

#### Ehdottajan sähköpostiosoite   

lassi.lager@helsinki.fi

**Comment by mirmaid** [comment]
Sanastoissa toistaiseksi vanhassa muodossaan. Ohjaustermi/vaihdetaan?

**Comment by mariaforsen** [comment]
MOT tai MESH ei tunnista sydäniskuria ollenkaan.

**Comment by LeKorsu** [comment]
Säilyttäisin defibrilaattorit varsinaisena terminä.

**Comment by mirmaid** [comment]
Hyväksytty ohjaustermiksi (YSA-kokous 7.3.2017).
