### ISSUE TITLE
käsinseisonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4980]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

käsinseisonta 

#### Ehdotettu termi englanniksi   

handstand 

#### Ehdotettu termi ruotsiksi   

handstående 

#### Ehdotettu yläkäsite YSOssa (LT)   

[liikunta](http://www.yso.fi/onto/yso/p916) 

#### Assosiatiiviset (RT)   

[akrobatia](http://www.yso.fi/onto/yso/p1277) 
[voimistelu](http://www.yso.fi/onto/yso/p963) 

#### exactMatch   

LCSH : <Handstands http://id.loc.gov/authorities/subjects/sh95007511> 

#### Vaihtoehtoiset termit ja ilmaisut   

käsilläseisonta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa.

Hierkisointi vaatinee pohtimista. Toisaalta voisi sijoittaa myös akrobatian, voimistelun tai liikkumisen alle. (vrt. "seisominen" on suoraan olemisen alla). Vastaavantyyppisiä käsitteitä ei oikein löydy, esim "vikellys" on hevosurheilun alla, toisaalta sirkustemput -> temput -> kulttuuriset objektit. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Käsinseisonnan perusteet ISBN:  978-952-93-8093-0 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [käsinseisonta](http://finto.fi/yse/fi/page/Y504980)

**Comment by mirmaid** [comment]
Kerran Melindassa.

Ei Liikunnan ja urheilun asiasanastossa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
handstående
