### ISSUE TITLE
etäomaishoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4981]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

etäomaishoito 

#### Tarkoitusta täsmentävä selite   

Omaishoito, jossa kauempana asuva omainen osallistuu aktiivisesti omaisensa hoitoon esim. puhelimitse ja käymällä hoidettavan luona viikonloppuisin (vrt. päivittäinen ympärivuorokautinen omaishoito) 

#### Perustelut ehdotukselle   

Omaishoito, jossa kauempana asuva omainen osallistuu aktiivisesti omaisensa hoitoon esim. puhelimitse ja käymällä hoidettavan luona viikonloppuisin (vrt. päivittäinen ympärivuorokautinen omaishoito). Etäomaishoito on yleistyvä omaishoidon muoto. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Viimeisimmäksi Seura 2016: 50-51 S. 72-73 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [etäomaishoito](http://finto.fi/yse/fi/page/Y504981)

**Comment by mirmaid** [comment]
Kerran Melindassa.

http://yle.fi/uutiset/3-7142200

**Comment by LeKorsu** [comment]
Kuulostaa jälleen kerran sellaiselta termiltä, joka tulee nopeammin esille artikkeliaineistossa kuin kirjoissa. Peukkua.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
närståendevård på distans
ET anhörigvård på distans
