### ISSUE TITLE
hyötypeli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4982]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hyötypeli 

#### Ehdotettu termi englanniksi   

serious games 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit](http://www.yso.fi/onto/yso/p6062) 
[pelit sisällön mukaan](http://www.yso.fi/onto/yso/p4296) 

#### exactMatch   

hyötypeli : https://fi.wikipedia.org/wiki/Hy%C3%B6typeli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

mm Pelisuunnittelukirjallisuutta kuvailtaessa tämä termi olisi käyttökelpoinen. Oppismispeli on liian suppea termi. Nykyisellään  hyötyaspekti pitää hakea muuta kautta. Suora termi olisi kätevämpi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Serious  Games : foundations, concepts and practice /Dörner, Göbel, Effelsberg & Wiemeyer 

**Ehdottajan nimi:** Henna Paajala 
**Ehdottajan sähköpostiosoite:** henna.paajala@oamk.fi **Termiehdotus Fintossa:** [hyötypeli](http://finto.fi/yse/fi/page/Y504982)

**Comment by mirmaid** [comment]
Ehdotettu aikaisemmin monikossa https://github.com/Finto-ehdotus/YSE/issues/3415

Satu Niininen: Käsite olisi tarpeen myös teoksessa Serious Gaming Research Lab: opas hyötypeleihin ja palvelumallin kehittämiseen

Tällä hetkellä Melindassa 2 osumaa.

**Comment by mariaforsen** [comment]
Ruotsiksi serious games/nyttospel/allvarliga spel.

**Comment by mirmaid** [comment]
Toisinaan hyöty tarjotaan pelaajalle (oppimispelit, liikuntapelit), mutta esim. mainospelien tapauksessa hyötyjä on mainostaja...

"Voidaan sanoa, että liikehdintä hyötypelien parissa alkoi vuonna 2002 kun Yhdysvaltain armeija
lanseerasi America’s Army -pelin sotilaiden koulutuskäyttöön. Samana vuonna perustettiin Serious
Games Iniative Washingtonissa, Yhdysvalloissa ja organisaatio vaikutti voimakkaasti käsitteen
”serious games” yleistymiseen. (America’s Army 2016; Gudmundsen 2006.) ”Serious games” käsi-
tettä vastaa suomenkielessä termi hyötypelit.

Hyötypeleissä peliteknologiaa hyödynnetään ja käytetään muussa kuin viihteellisessä tarkoituksessa (Miller, Chang, Wang, Beier & Klisch 2011). Hyötypelit voivat olla digitaalisia pelejä, simulaatioita, virtuaaliympäristöjä tai todellisen ja virtuaaliympäristön yhdistelmiä, jotka interaktiivisten kokemusten, kohtaamisten, tarinan tai pelimekanismien avulla mahdollistavat tiedottamisen, vaikuttamisen ja merkitysten luomisen erilaisten aktiviteettien yhteydessä (Marsh 2011)." http://www.kuopioinnovation.fi/uploads/aineistopankki/muut_fi/SGRL_Opas.pdf

**Comment by LeKorsu** [comment]
Hyötypelit kuulostaa hyödylliseltä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: ?
nyttospel 
serious games 
seriösa spel http://computersweden.idg.se/2.2683/1.608499/spel--ett-noje-som-kan-bli-till-nytta
ET allvarliga spel
ET lärande spel http://www.tnc.se/termfraga/larande-spel/
ET lärospel
