### ISSUE TITLE
heteroseksuaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4983]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heteroseksuaalit 

#### Ehdotettu termi ruotsiksi   

heterosexuella 

#### Ehdotettu termi englanniksi   

heterosexual 

#### Ehdotettu yläkäsite YSOssa (LT)   

[seksuaalisuus](http://www.yso.fi/onto/yso/p1826) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ageing and sexualities : interdisciplinary perspectives / edited by Elizabeth Peel and Rosie Harding. --    Farnham, Surrey : Ashgate Publishing Limited, [2016] 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Perustelut ehdotukselle   

Sanastossa on termi homoseksuaalit, mutta ei termiä heteroseksuaalit. Sanastossa on lisäksi termit heteroseksuaalisuus ja homoseksuaalisuus. 

**Ehdottajan nimi:** Mervi Salomaa-Rauhala 
**Ehdottajan organisaatio:** Tampereen yöiopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mervi.salomaa-rauhala@uta.fi **Termiehdotus Fintossa:** [heteroseksuaalit](http://finto.fi/yse/fi/page/Y504983)

**Comment by mirmaid** [comment]
Kerran Melindassa (+ kerran _heterot_).

LCSH: Heterosexuals, lisäksi Heterosexual men, Heterosexual women, Heterosexual parents, Heterosexual mothers ja Heterosexual teachers :dizzy_face:

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
heterosexuella
