### ISSUE TITLE
luutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4984]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luutuminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Microvascular reconstruction of traumatic compound bone and soft tissue defects of the tibia and ankle 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Ei ole vastaavaa termiä YSAssa 

**Ehdottajan nimi:** Anneli Renfors 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** anneli.renfors@btj.fi **Termiehdotus Fintossa:** [luutuminen](http://finto.fi/yse/fi/page/Y504984)

**Comment by mirmaid** [comment]
Melindassa 4 kertaa.

MeSH: Osteogeneesi

LCSH: Bones |x Growth

**Comment by mariaforsen** [comment]
Eli sama kuin osteogeneesi=benvävnadsbildning? Vai voiko luutuminen käyttää myös sellaisissa tapauksissa joissa tämä ei sovi?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017). KT osteogeneesi?

**Comment by mariaforsen** [comment]
Allärs:
benbildning
förbening
ET benvävsbildning http://finto.fi/mesh/sv/page/D010012
ET ossifikation /ne
ET osteogenes

**Comment by mirmaid** [comment]
Lääketieteen termit:
osteogeneesi: luun synty, luun muodostuminen; ks. luutuminen (1)
luutuminen (1): luunmuodostus, ossifioituminen, osteogeneesi | luun synty joko välillisesti ruston kautta tai suoraan sidekudoksesta
luutuminen (2): murtuman paraneminen

Suomeksi siis voi käyttää molemmista termiä luutuminen.

**Comment by mariaforsen** [comment]
Allärs:
benbildning
ET benvävsbildning 
ET förbening
ET ossifikation
ET osteogenes
