### ISSUE TITLE
multikopteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4985]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

multikopteri 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lennokit](http://www.yso.fi/onto/yso/p8578) 

#### Perustelut ehdotukselle   

Tämä ehdotus tuli asiakkaalta, joka etsi kirjallisuutta moderneista lennokeista, jotka eivät enää nykyään muistuta lentokoneita vaan ovat sellaisia monoroottorisia helikopterin tapaisia. Asiakkaan mukaan alan harrastajien käyttämä termi niistä on multikopteri. Siksi olisi hyvä, jos sitä voisi käyttää ihan virallisena asiasanana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Drones for dummies (978-1-119-04978-4) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

**Ehdottajan nimi:** Jarmo Louet 
**Ehdottajan organisaatio:** Jyväskylän kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** jarmo.louet@jkl.fi **Termiehdotus Fintossa:** [multikopteri](http://finto.fi/yse/fi/page/Y504985)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Multikopteri

**Comment by LeKorsu** [comment]
Esimerkkiteoksen nimekkeessä on sana drones. Sitä näkyy jonkin verran suomennettu drooniksi. http://areena.yle.fi/1-2649357
https://suomenkuvalehti.fi/kohinaa/droonit-ilmatilan-uusi-ulottuvuus/
http://www.consilium.europa.eu/fi/press/press-releases/2016/12/01-aviation-safety-easa-drones-rules/

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

droonit KÄ miehittämättömät ilma-alukset

**Comment by mariaforsen** [comment]
Allärs:
multikoptrar

drönare ANV obemannade luftfarkoster
