### ISSUE TITLE
rotuteoriat / kriittinen rotuteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4986]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rotuteoriat / kriittinen rotuteoria 

#### Ehdotettu termi englanniksi   

racial theories / critical race theory 

#### Ehdotettu termi ruotsiksi   

rasteorier / crt (sama kuin englanniksi) ? 

#### Perustelut ehdotukselle   

esim. http://lahi-itanyt.fi/populismi-ja-sen-viholliskuvat/
https://fi.wikipedia.org/wiki/Suomalaisten_alkuper%C3%A4
https://sv.wikipedia.org/wiki/Critical_Race_Theory
Paitsi nykykeskustelussa tarvittu termi, myös historiallisessa aineistossa tarvittuja termejä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

rodut + teoriat -vastineelle olemassa täsmällisempi termi 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [rotuteoriat / kriittinen rotuteoria](http://finto.fi/yse/fi/page/Y504986)

**Comment by mirmaid** [comment]
Melindassa 25 kertaa _rotuteoriat_.

**Comment by mirmaid** [comment]
Kriittinen rotuteoria tuo vain muutamia viitteitä Googlella. 

Eng. toki eri tilanne https://en.wikipedia.org/wiki/Critical_race_theory

Ei LCSH:ssa

YSAssa on _kriittinen teoria_: Kriittisellä teorialla tarkoitetaan monitieteellistä yhteiskunnan ja kulttuurin tutkimusta ja kritiikkiä. Käsitteellä on sosiologinen ja kirjallisuuskriittinen merkitys, joista molemmilla on oma alkuperänsä ja historiansa. Tämän seurauksena kriittinen teoria on sateenvarjokäsite, joka pitää sisällään kaikki kritiikkiin perustuvat teoriat.

**Comment by mariaforsen** [comment]
Ruotsiksi pelkkä rasteori/er lähellä rasbiologi (rotubiologia). https://sv.wikipedia.org/wiki/Rasbiologi 
Crt taas on asia erikseen.

**Comment by LeKorsu** [comment]
En vastusta rotuteoriat. Jos otetaan pitäisikö ottaa rotubiologia ohjaustermiksi? Käykö sama ruotsiksi?

**Comment by mirmaid** [comment]
Hyväksytty rotuteoriat (YSA-kokous 7.3.2017). KT rotubiologia (?)

**Comment by mariaforsen** [comment]
Allärs:
rasteorier
ET rasbiologi?

**Comment by mirmaid** [comment]
Tämä ei olisi ainakaan ihan synonyyminen ohjaustermi, "tieteenala" vs. teoriat samalta alalta. Pitäisikö myös olla rotubiologia KÄ eugeniikka? @mariaforsen

**Comment by AuHo22** [comment]
Hei,
näyttäisi että näillä termeillä on oma historiansa ja voi vaihdella maittainkin. Eikö rotubiologia ole lähellä sitä, mitä nykyisin kuvataan biologisella antropologialla KT fyysinen antropologia. Rotuhygienia eli eugeniikka sitten taasen jo ihan rodunjalostusta eli soveltavaa "tiedettä", jota ei edellisiin pitäisi liittää. Itse en lähtisi pakotettuja viittaus/KT-suhteita etsimään, vaan epäselvissä tapauksissa jättäisin ne vain pois.

http://senc.hum.helsinki.fi/wiki/Rotututkimus_Suomessa
http://www.uta.fi/avoinyliopisto/arkisto/sosiaaliantropologia/antropologia.html

**Comment by mirmaid** [comment]
Biologinen antropologia on minusta paljon laajempi ja nykyään kuitenkin ihan neutraali tiede, rotubiologia tuntuisi yleisesti liittyneen rotuhygienisiin pyrkimyksiin?

**Comment by AuHo22** [comment]
Ongelmana voi olla myös termeihin liittyvät konnotaatiot. Itse jättäisin koko termin rotubiologia pois sanastosta. Jos joku sitä joskus ehdottaa, niin joutuu perustelemaan asiansa. YSAssa on jo eugeniikka KT rotuhygienia.

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Rasbiologi

**Comment by mariaforsen** [comment]
Allärs:
rasteorier
