### ISSUE TITLE
rauhan aika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4990]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rauhan aika 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Sanastossa on sota-aika, sekä myös termit sota ja rauha. Jälkimmäiset termit ovat epätäsmällisiä, kun teos käsittelee (tiettyjen) alueitten oikeudellista sääntelyä em. ajanjaksoissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Merioikeus ja Itämeri 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [rauhan aika](http://finto.fi/yse/fi/page/Y504990)

**Comment by mirmaid** [comment]
PUHOssa.

Käytetty Melindassa 8 kertaa.

**Comment by mariaforsen** [comment]
MOTissa yhteenkirjoitettuna. Sv. fredstid olisi hyvä.

**Comment by LeKorsu** [comment]
Sanoman arkistossa yli 700 osumaa yhteenkirjoitettuna.

**Comment by mirmaid** [comment]
Hyväksytty muodossa rauhanaika (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
fredstid
