### ISSUE TITLE
hauta-antimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4991]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hauta-antimet 

#### Ehdotettu termi ruotsiksi   

gravgåvor 

#### Ehdotettu termi englanniksi   

grave goods 

#### Ehdotettu yläkäsite YSOssa (LT)   

[uskontoon liittyvät objektit](http://www.yso.fi/onto/yso/p5972) 

#### exactMatch   

Grave goods : <http://id.loc.gov/authorities/subjects/sh2001002091> 
Gravgåvor : <http://www.kb.se/katalogisering/Svenska-amnesord/sok-ord/> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Tarkoitusta täsmentävä selite   

Ennen kristinuskon omaksumista oli yleisenä tapana laittaa vainajalle tuonpuoleista elämää varten hautaan erilaisia työ- ja tarvekaluja ja henkilökohtaisia esineitä. Todennäköisesti vainajan ajateltiin tarvitsevan samoja esineitä myös tuonpuoleisessa.
http://www.muinaispolut.fi/sanasto

Hautoihin pantiin mukaan käyttöesineitä, saviastioita, työkirveitä ja miehille myös vasarakirveitä. Hauta-antimet viittaavat uskoon tuonpuoleisesta.
http://www.kansallismuseo.fi/fi/kansallismuseo/opetus/opetuspaketit/esihistoria/tietoa/kivikausi/7 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. esim. Melindan bib-id 010119129 (Gräberfeld und Siedlung Nagornoe 2) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan arkeologisen tutkimuskirjallisuuden sisällönkuvailussa. 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [hauta-antimet](http://finto.fi/yse/fi/page/Y504991)

**Comment by mariaforsen** [comment]
Ks. myös https://fi.wikipedia.org/wiki/Hautaesine

**Comment by mirmaid** [comment]
MAO-ontologiassa, Melindassa 18 kertaa enimmäkseen masa-terminä.

KT hautaesineet, hautalahjat

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
gravgåvor 
ET gravföremål 
ET gravgods
