### ISSUE TITLE
vainajainpalvonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4992]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vainajainpalvonta](http://www.yso.fi/onto/ysa/Y100774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korvatuksi termiksi: esi-isäkultti (ancestor cult) 

#### Perustelut ehdotukselle   

Termiä esi-isäkultti käytetään tutkimuskirjallisuudessa paljon, mutta se on merkitykseltään niin lähellä vainajainpalvontaa, ettei sitä kannata ottaa varsinaiseksi asiasanaksi. 

#### Ehdottaja   

Kristiina Näyhö 

#### Ehdottajan organisaatio   

SKS:n kirjasto 

#### Ehdottajan sähköpostiosoite   

kristiina.nayho@finlit.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
