### ISSUE TITLE
seurakunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4994]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seurakunta](http://www.yso.fi/onto/ysa/Y108560) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen seurakunnat 

#### Perustelut ehdotukselle   

Kuvailukäyttö ei ole johdonmukaista, merkitys teologisena käsitteenä marginaalinen suhteessa aineistomäärään. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).
