### ISSUE TITLE
kehonpainoharjoittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4995]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kehonpainoharjoittelu 

#### Ehdotettu termi englanniksi   

bodyweight exercise 

#### Ehdotettu yläkäsite YSOssa (LT)   

[harjoittelu](http://www.yso.fi/onto/yso/p26412) 

#### Assosiatiiviset (RT)   

[valmennus](http://www.yso.fi/onto/yso/p3734) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

... 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Complete calisthenics 

**Ehdottajan nimi:** Tuija Nevala 
**Ehdottajan sähköpostiosoite:** tuija.e.nevala@jyu.fi **Termiehdotus Fintossa:** [kehonpainoharjoittelu](http://finto.fi/yse/fi/page/Y504995)

**Comment by mirmaid** [comment]
Kerran Melindassa. 

"Kehonpainoharjoittelu on nimensä mukaisesti oman kehon vastuksella suoritettavaa fyysistä harjoittelua." 

...liikkeet näyttävät perinteisiltä punnerruksilta, leuanvedolta jne.

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Bodyweight_exercise

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
kroppsviktsträning
ET kroppsviktsövningar
