### ISSUE TITLE
ohjausjärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4996]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ohjausjärjestelmät](http://www.yso.fi/onto/ysa/Y97737) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko tarpeen jakaa käsite? Näyttäisi viittaavan paitsi teknisiin järjestelmiin, myös organisatoriseen toiminnan ohjaukseen. 

#### Perustelut ehdotukselle   

Merkityset:

1. Ohjausjärjestelmät (tekniset): esim. auton tai ohjuksen ohjausjärjestelmä
2. Ohjausjärjestelmät (hallinto): esim http://vm.fi/hallintopolitiikka/ohjausjarjestelmat ja https://fi.wikipedia.org/wiki/Yritysten_hallinnointi-_ja_ohjausj%C3%A4rjestelm%C3%A4 ja https://fi.wikipedia.org/wiki/Ohjaus_%28yritysjohtaminen%29 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

mikko.lappalainen@helsinki.fi

**Comment by mirmaid** [comment]
Voiko olla _ohjausjärjestelmät (tekniikka)_ tai _(tekniset järjestelmät)_? Hallinto kuulostaa muuten ihan hyvältä tarkenteelta, mutta viekö se ajatukset liikaa "hallinnonalaan"? Yrityksistä puhuttaessa _johdon ohjausjärjestelmät_ tai _ohjausjärjestelmät (johtaminen)_ olisi hyvä ja näitä on viitteissä runsaasti, mutta kaikkiin tapauksiin se ei sovellu.

**Comment by ilona-x** [comment]
Osassa yrityksiin liittyvissä viitteissä kyse toiminnanohjausjärjestelmistä. 50 tietuetta, joissa sekä ohjausjärjestelmät että toiminnanohjausjärjestelmät ja lisäksi 33 tietuetta, joissa toiminnanohjaus (organisaatiot) + ohjausjärjestelmät.

Melindassa paljon korjattavaa viitteitä 1253 + ketjut.

**Comment by mariaforsen** [comment]
Sv. 
-styrsystem (organisationer)
-styrsystem (teknik)

**Comment by mirmaid** [comment]
_Ohjausjärjestelmä tarkoittaa johtamista tukevien menettelyjen, järjestelmien, toimintatapojen ja niihin liittyvien asiakirjojen kokonaisuutta. Johtamisella ja ohjausjärjestelmillä on läheinen suhde toisiinsa. Johtamisella tarkoitetaan toimintatapoja ja menettelyjä, joilla johto pyrkii saamaan aikaan asetetut tavoitteet._ https://vm.fi/hallintopolitiikka/ohjausjarjestelmat

**Comment by mirmaid** [comment]
Varmaan ainakin ohjausjärjestelmät (toiminnanohjaus) KÄ toiminnanohjausjärjestelmät

**Comment by mirmaid** [comment]
Teknisiä ohjausjärjestelmiäkin on hyvin monenlaisia, ohjuksista ja autoista vaikka [leikkaussalin ohjausjärjestelmään](https://www.sttinfo.fi/tiedote/merivaaran-integroitu-ohjausjarjestelma-parantaa-leikkaussalityon-sujuvuutta?publisherId=4193&releaseId=1617188).

**Comment by ilona-x** [comment]
YSOssa myös:

**hallintajärjestelmät** (sv. kontrollsystem, eng. control systems) http://www.yso.fi/onto/yso/p16975
**säätöjärjestelmät** (sv. reglersystem, eng. adjustment systems) http://www.yso.fi/onto/yso/p15400

https://termipankki.fi/tepa/fi/haku/ohjausj%C3%A4rjestelm%C3%A4

WIkipedia: "Ohjausjärjestelmä eli säätöjärjestelmä"
https://fi.wikipedia.org/wiki/Ohjausj%C3%A4rjestelm%C3%A4

**Comment by ilona-x** [comment]
Alkuperäisessä ehdotuksessa on kysymys, onko tarpeen jakaa. Huomasin, että ohjaus-termin osalta tätä jakoa ei ole katsottu tarpeelliseksi, kun ohjaus (hallinta) http://www.yso.fi/onto/yso/p1911 näyttäisi kattavan nämä molemmat merkitykset.

**Comment by mariaforsen** [comment]
Myös ruotsiksi ohjausjärjestelmä on styrsystem riippumatta kontekstista.

**Comment by mirmaid** [comment]
Eli olisiko niin, että ei jaeta tätä käsitettä, mutta tehdään ohjaustermi ohjausjärjestelmät (toiminnanohjaus) KÄ toiminnanohjausjärjestelmät?

**Comment by YSO-kokous** [comment]
Tehdään seuraava:
ohjausjärjestelmät (toiminnanohjaus) KÄ toiminnanohjausjärjestelmät
Ei muita muutoksia.
