### ISSUE TITLE
unikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4997]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

unikot 

#### Ehdotettu termi ruotsiksi   

vallmor 

#### Ehdotettu termi englanniksi   

poppies 

#### exactMatch   

poppies : <http://id.loc.gov/authorities/subjects/sh85104900> 
Papaver : Wikipedia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

kasvisuku 

#### Perustelut ehdotukselle   

Tarvittu indeksoinnissa (esimerkki, ohessa) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lack, Andrew: Poppy, 978-1-78023-653-7 

**Ehdottajan nimi:** Yrjö Lindegren 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** yrjo.lindegren@hel.fi **Termiehdotus Fintossa:** [unikot](http://finto.fi/yse/fi/page/Y504997)

**Comment by mirmaid** [comment]
Kasvisuku https://laji.fi/taksoni/MX.37953?locale=fi

**Comment by mariaforsen** [comment]
Allärs: 
vallmor

**Comment by mirmaid** [comment]
Hyväksytty.
