### ISSUE TITLE
unikkokasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4998]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

unikkokasvit 

#### Ehdotettu termi ruotsiksi   

vallmoväxter 

#### exactMatch   

Papaveraceae : <http://id.loc.gov/authorities/subjects/sh85097570> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

kasviheimo 

#### Perustelut ehdotukselle   

Tarvittu indeksoinnissa (ks. oheinen) esimerkki 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lack, Andrew: Poppy, 978-1-78023-653-7 

**Ehdottajan nimi:** Yrjö Lindegren 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** yrjo.lindegren@hel.fi **Termiehdotus Fintossa:** [unikkokasvit](http://finto.fi/yse/fi/page/Y504998)

**Comment by mirmaid** [comment]
Kasviheimo https://laji.fi/taksoni/MX.37952?locale=fi#show

**Comment by mariaforsen** [comment]
Allärs:
vallmoväxter

**Comment by mirmaid** [comment]
Hyväksytty.
