### ISSUE TITLE
amatsonit (papukaijat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#4999]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

amatsonit (papukaijat) 

#### Ehdotettu termi englanniksi   

Amazon parrots 

#### Ehdotettu termi ruotsiksi   

amazonpapegojor 

#### exactMatch   

Amazon parrots : <http://id.loc.gov/authorities/subjects/sh85004134> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Käsite amatsonit on jaettava, esim.: amatsonit (papukaijat), amatsonit (mytologia) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Amatsoneja pidetään lemmikkilintuina ja niistä puhutaan alan oppaissa:  http://birds.about.com/od/breedsofbirds/tp/popularamazonspecies.htm 

**Ehdottajan nimi:** Yrjö Lindegren 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** yrjo.lindegren@hel.fi **Termiehdotus Fintossa:** [amatsonit (papukaijat)](http://finto.fi/yse/fi/page/Y504999)

**Comment by mirmaid** [comment]
Laji.fi: amazona https://laji.fi/taksoni/MX.28630?locale=fi
Wikipedia: https://fi.wikipedia.org/wiki/Amatsonit_(linnut)

**Comment by mariaforsen** [comment]
Allärs:
amazonpapegojor /ne

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
amazonpapegojor
