### ISSUE TITLE
amatsonit (mytologia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5000]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

amatsonit (mytologia) 

#### Ehdotettu termi englanniksi   

Amazons 

#### Ehdotettu termi ruotsiksi   

amasoner 

#### exactMatch   

Amazons : <http://id.loc.gov/authorities/subjects/sh85004138> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Amatsonit ovat antiikin tarustossa esiintyvä pelottava naissotureiden kansa. Legendan mukaan soturit leikkasivat toisen rintansa pois voidakseen ampua paremmin jousella. Useat Kreikan tarujen miessankarit, kuten Herakles, Theseus ja Akhilleus, kuitenkin voittivat amatsonit. Kuvaannollisesti amatsoneilla tarkoitetaan naisten asemaa aggressiivisesti ajavia tai fyysisesti voimakkaita naisia.(Wikipedia) Tarvitaanko kuvainnolliselle merkitykselle oma termi? 

#### Perustelut ehdotukselle   

Tarvitaan jaettu termi, esim. amatsonit (mytologia), amatsonit (papukaijat) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Antiikin mytologiaa käsittelevät teokset 

**Ehdottajan nimi:** Yrjö Lindegren 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** yrjo.lindegren@hel.fi **Termiehdotus Fintossa:** [amatsonit (mytologia)](http://finto.fi/yse/fi/page/Y505000)

**Comment by mirmaid** [comment]
Melindassa 6 kertaa. Kuvaannolliselle merkitykselle ei varmaankaan tarvita termiä, mytologia sopii ainakin näihin.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
amasoner 
ET amazoner
