### ISSUE TITLE
etsivätoimistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5001]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

etsivätoimistot 

#### Ehdotettu termi englanniksi   

detective agencies 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Tarvitaan etsivätoimistoja koskevien teosten indeksointiin. Pinkertonin etsivätoimistosta (ja sen historiasta) on kokoelmissamme ainakin kaksi teosta, esimerkki ohessa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

O'Hara, S. Paul: Inventing the Pinkertons or, Spies, sleuths, mercenaries, and thugs : being a story of the nation's most famous (and infamous) detective agency, 978-1-4214-2056-1 

**Ehdottajan nimi:** Yrjö Lindegren 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** yrjo.lindegren@hel.fi **Termiehdotus Fintossa:** [etsivätoimistot](http://finto.fi/yse/fi/page/Y505001)

**Comment by mirmaid** [comment]
Yksityisetsivä- ja lakitoimistot: http://www.yksityisetsiva.fi/2.0/

**Comment by mariaforsen** [comment]
Sv. detektivbyråer.

**Comment by LeKorsu** [comment]
Ysassa etsivät > joko yksityisetsivät (privatdetektiver) tai rikosetsivät (detektiver), viime mainittu ilmeisestikin poliisin yksi virkanimike. Olisiko sen vuoksi yksityisetsivätoimistot parempi ja kääntyykö ruotsiksi hyvin privatdetektivbyråer?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017). KT yksityisetsivätoimistot.

**Comment by mariaforsen** [comment]
Allärs:
detektivbyråer
