### ISSUE TITLE
Grand Tetonin kansallispuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5002]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Grand Tetonin kansallispuisto 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansallispuistot](http://www.yso.fi/onto/yso/p75) 

#### Assosiatiiviset (RT)   

[Yellowstonen kansallispuisto](http://www.yso.fi/onto/yso/p29027) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Perustelut ehdotukselle   

Kuvailen matkaopasta, joka käsittelee kyseistä kansallispuistoa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Montana & Wyoming 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [Grand Tetonin kansallispuisto](http://finto.fi/yse/fi/page/Y505002)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh2005004616.html
https://fi.wikipedia.org/wiki/Grand_Tetonin_kansallispuisto

**Comment by mariaforsen** [comment]
Allärs: 
Grand Teton nationalpark 
ET Grand Tetons nationalpark 
ET Grand Teton National Park

**Comment by mirmaid** [comment]
Hyväksytty.
