### ISSUE TITLE
Glacierin kansallispuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5003]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Glacierin kansallispuisto 

#### Ehdotettu termi englanniksi   

Glacier National Park) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansallispuistot](http://www.yso.fi/onto/yso/p75) 

#### Assosiatiiviset (RT)   

[Yellowstonen kansallispuisto](http://www.yso.fi/onto/yso/p29027) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Perustelut ehdotukselle   

Kuvailen matkaopasta, jossa käsitellään kyseistä kansallispuistoa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Montana & Wyoming 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi **Termiehdotus Fintossa:** [Glacierin kansallispuisto](http://finto.fi/yse/fi/page/Y505003)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Glacierin_kansallispuisto
http://id.loc.gov/authorities/subjects/sh2007003872.html

Samanniminen kansallispuisto on myös Kanadassa http://id.loc.gov/authorities/subjects/sh85055064.html, https://en.wikipedia.org/wiki/Glacier_National_Park_(Canada)

Sijaitsevat melko lähekkäin rajan molemmin puolin, mutta eivät muodosta yhtä kokonaisuutta (?), vaan Glacierin kansallispuisto (Yhdysvalloissa) yhdistyy Watertonin kansallispuistoon https://fi.wikipedia.org/wiki/Waterton_Glacierin_kansainv%C3%A4linen_rauhanpuisto.

**Comment by mirmaid** [comment]
Tarvitaanko tarkenne (Yhdysvallat)?

**Comment by EsaMPKK** [comment]
Tarkenne voisi olla hyvä erottamaan samannimiset kansallispuistot toisistaan.

**Comment by mirmaid** [comment]
Lisätään tarkenne (Yhdysvallat).

**Comment by mariaforsen** [comment]
Allärs: 
Glacier nationalpark (USA)
ET Glacier National Park 
ET Glaciers nationalpark
