### ISSUE TITLE
palkintotuomarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5004]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

palkintotuomarit 

#### Ehdotettu termi englanniksi   

prize judges 

#### Assosiatiiviset (RT)   

[arvostelijat](http://www.yso.fi/onto/yso/p13344) 

#### exactMatch   

LCSH : Drama festival judges; Flower show judges; Horse show judges 

#### Vaihtoehtoiset termit ja ilmaisut   

kilpailutuomarit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581) 
[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Tarkoitusta täsmentävä selite   

Muiden kuin urheilukilpailun (esimerkiksi musiikkikilpailujen ja taideteollisuusnäyttelyiden) jaettavista palkinnoista päättävä henkilö. 

#### Perustelut ehdotukselle   

Asiasana "tuomarit" viittaa oikeudenkäyttöön, "erotuomarit" urheilukilpailujen tuomareihin, "arvostelijat" (KT kriitikot) taideteosten ja taide-esitysten yleensä sanallisen arvostelun laatijoihin, mutta millä kuvata esimerkiksi musiikkikilpailujen ja taideteollisuusnäyttelyjen jaettavista palkinnoista päättäviä tuomareita. Ainakin lehdistössä ja useilla verkkosivuilla näyttää käytetyn ilmaisua "palkintotuomari". 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artikkeli, jossa listataan Viipurin taideteollisuusnäyttelyn palkintotuomarit 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [palkintotuomarit](http://finto.fi/yse/fi/page/Y505004)

**Comment by mirmaid** [comment]
Vähän hankala, nimitys vaihtelee varmaan kilpailusta toiseen. Eläinnäyttelyissä puhutaan yleensä vain tuomareista tai näyttelytuomareista, palkintotuomari kuulostaa vieraalta.

**Comment by ilona-x** [comment]
YSA:ssa urheilutuomarit = Allärsissa tävlingsdomare = kilpailutuomari.

Voisiko tuomarit jakaa:

tuomarit (oikeus?)
tuomarit (kilpailut/kilpailutoiminta?) KT urheilutuomarit

Google:
urheilutuomari 846
palkintotuomari 8 960
kilpailutuomari 3 850

Kielitoimiston sanakirja:

**tuomari**
1. oik. henkilö jolla yksin t. yhdessä tuomioistuimen muiden jäsenien kanssa on oikeus käyttää tuomiovaltaa; yleisk. myös varatuomarista, lakimiehestä. Virka-, maallikkotuomari. Käräjätuomari. Lukea tuomariksi.

2. henkilö joka toimii ratkaisijana t. arvostelijana jssak kilpailussa, kiistassa tms. Koiranäyttelyn tuomari. Makutuomari. Urh. Jalkapallo-, painituomari. Kehä-, maalituomari. Piste-, arvostelutuomari.

**Comment by mirmaid** [comment]
Jaetaan: tuomarit (oikeus) ja tuomarit (kilpailut) (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Sv. 
domare (juridik) 
domare (tävlingar) ET idrottsdomare ET sportdomare ET tävlingsdomare

**Comment by mirmaid** [comment]
Oliko siis tarkoitus korvata _urheilutuomarit_ tällä _tuomarit (kilpailut)_ -termillä?

**Comment by mariaforsen** [comment]
Varmaan urheilutuomarit voisi olla alakäsitekin.

**Comment by YSA-kokous** [comment]
urheilutuomarit KÄ tuomarit (kilpailut)
