### ISSUE TITLE
työpaikkailmoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5005]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

työpaikkailmoitukset 

#### Ehdotettu termi englanniksi   

job advertisement 

#### Ehdotettu termi ruotsiksi   

platsannons 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ilmoitukset (tiedotteet)](http://www.yso.fi/onto/yso/p38) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85070580> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 
[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Vastaavaa käsitettä ei näytä ennestään löytyvän Ysasta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://digi.kansalliskirjasto.fi/sanomalehti/binding/1196774/articles/1999601?page=8 

#### Tarkoitusta täsmentävä selite   

Ilmoitus tai mainos haettavana olevasta työpaikasta. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [työpaikkailmoitukset](http://finto.fi/yse/fi/page/Y505005)

**Comment by mirmaid** [comment]
Käytetty Melindassa 9 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
arbetsplatsannonser
ET anställningsannonser
ET platsannonser
ET jobbannonser
ET rekryteringsannonser
