### ISSUE TITLE
liukosellu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5006]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

liukosellu 

#### Ehdotettu termi englanniksi   

dissolving pulp (mainittu artikkelissa http://www.metla.fi/aikakauskirja/full/ff16/ff163181.pdf) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sellu](http://www.yso.fi/onto/yso/p6396) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[28 Metsäteollisuus. Massa- ja paperiteollisuus. Paperiteollisuus. Puuteollisuus](http://www.yso.fi/onto/yso/p26585) 

#### Perustelut ehdotukselle   

Tulevaisuuden tuote 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. ARTO, http://www.metla.fi/aikakauskirja/full/ff16/ff163181.pdf 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [liukosellu](http://finto.fi/yse/fi/page/Y505006)

**Comment by mirmaid** [comment]
Kerran Melindassa. 

http://www.biotalous.fi/liukosellu-kangas/

**Comment by mariaforsen** [comment]
Sv. dissolvingmassa

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
dissolvingmassa
