### ISSUE TITLE
sosiaalineuvonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5008]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sosiaalineuvonta 

#### Ehdotettu termi ruotsiksi   

socialrådgivning 

#### Assosiatiiviset (RT)   

[terveysneuvonta](http://www.yso.fi/onto/yso/p7094) 

#### Perustelut ehdotukselle   

Vrt. terveysneuvonta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ISBN 978-951-609-763-6 ”Ilman Nerviä en olisi hengissä” : kyselytutkimus A-klinikkasäätiön Pirkanmaan palvelualueen terveys- ja sosiaalineuvontapiste Nervin asiakkaiden hyvinvoinnista ja palveluiden käytöstä 

#### Tarkoitusta täsmentävä selite   

Helsingin kaupungin sivuilla sosiaalineuvonnasta: http://www.hel.fi/www/Helsinki/fi/sosiaali-ja-terveyspalvelut/sosiaalinen-tuki-ja-toimeentulo/toimeentulotuki/sosiaalineuvonta/ 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi

**Comment by mirmaid** [comment]
Kerran Melindassa.

http://www.hel.fi/www/Helsinki/fi/sosiaali-ja-terveyspalvelut/sosiaalinen-tuki-ja-toimeentulo/toimeentulotuki/sosiaalineuvonta/

http://www.soite.fi/sivu/sosiaalineuvonta

**Comment by AuHo22** [comment]
Myös sosiaaliohjaus-termiä käytetään (ei myöskään YSAssa) ; ST perheneuvonta, kasvatusneuvonta jne.

**Comment by LeKorsu** [comment]
Sosiaalineuvonta kuulostaa modernimmalta kuin sosiaaliohjaus. Toisaalta ysassa on sosiaaliohjaajat.

**Comment by mirmaid** [comment]
Selvitetään ero palveluohjaukseen.

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by mirmaid** [comment]
Palveluohjauksella tarkoitetaan asiakaslähtöistä sosiaali- ja terveysalan asiakastyötä, jossa vahvistetaan asiakkaan itsenäistä elämänhallintaa ja yksityistä verkostoa hyödyntämällä asiakkaan voimavaroja hänen elämänsä haastekohdissa. https://www.palveluohjaus.fi/mita-palveluohjaus-on/

https://fi.wikipedia.org/wiki/Palveluohjaus

...lienee sama asia

**Comment by YSA-kokous** [comment]
KÄ palveluohjaus
