### ISSUE TITLE
Euromaidan

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5009]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Euromaidan 

#### Perustelut ehdotukselle   

vrt. arabikevät 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ISBN 978-951-769-514-5: Three years after Euromaidan 

#### Tarkoitusta täsmentävä selite   

Euromaidan wikipediassa: https://en.wikipedia.org/wiki/Euromaidan 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi

**Comment by mirmaid** [comment]
LCSH: Ukraine |x History |y Euromaidan Protests, 2013-2014

Melindassa 4 kertaa LCSH-terminä, kerran ysa-sanana.

**Comment by LeKorsu** [comment]
Minun kehysorganisaatiossani on aina tarvetta tämänkaltaisille termeille sovitussa muodossa, joten peukku. Tarvitseeko selitystä ajan ja paikan mukaan?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
euromajdan
