### ISSUE TITLE
ilmastokokoukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5010]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmastokokoukset 

#### Ehdotettu termi englanniksi   

climate change conference 

#### Ehdotettu termi ruotsiksi   

klimatkonferenser 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kokoukset](http://www.yso.fi/onto/yso/p7500) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[14 Klimatologia. Meteorologia. Ilmatiede](http://www.yso.fi/onto/yso/p26587) 

#### Tarkoitusta täsmentävä selite   

UN Climate conference wikipediassa: https://en.wikipedia.org/wiki/United_Nations_Climate_Change_conference
- Vai kuuluuko tämä yhteisöihin? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-951-769-469-8 Paris stress test 

#### Perustelut ehdotukselle   

ilmasto + kokoukset -kombinaation sijaan 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi

**Comment by tpusa** [comment]
Kuuluu lisäksi ryhmiin: 
18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet
65 Valtio-oppi. Politiikka. Kansainvälinen politiikka

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
klimatkonferenser
klimatmöten

**Comment by mirmaid** [comment]
Pitäisköhän tämä palauttaa vielä pöydälle? LCSH:ssa kokouksena, en tiedä kannattaako ajatella että olisi laajempi? @mariaforsen 

LCSH: 111 2_ |a Conference of the Parties (United Nations Framework Convention on Climate Change)
411 	2_ |a United Nations Climate Change Conference

**Comment by tpusa** [comment]
Ysa:ssa on "huippukokoukset".

**Comment by mariaforsen** [comment]
Klimatkonferenser on kyllä muitakin kun YK:n, esim. http://www.skr.org/nyheter/kyrkorna-i-sverige-genomfor-klimatkonferens/ eli ruotsin osalta ok lisätä uutena terminä.

**Comment by mariaforsen** [comment]
Sv. klimatmöten ET klimatkonferenser
