### ISSUE TITLE
maisema-alueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5011]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maisema-alueet 

#### Ehdotettu termi ruotsiksi   

landskapsområden 

#### Ehdotettu termi englanniksi   

landscapes/valuable landscapes 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ympäristöohjelmat](http://www.yso.fi/onto/yso/p20376) 

#### Assosiatiiviset (RT)   

[Natura 2000](http://www.yso.fi/onto/yso/p20407) 
[METSO-ohjelma](http://www.yso.fi/onto/yso/p28834) 
[maisemansuojelu](http://www.yso.fi/onto/yso/p2330) 

#### Tarkoitusta täsmentävä selite   

Ympäristöhallinnon sivuilla:
http://www.ymparisto.fi/fi-FI/Luonto/Maisemat/Arvokkaat_maisemaalueet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ISBN 978-952-446-917-3 Merenkurkun saariston maailmanperintöalueen luontomatkailusuunnitelma 2011 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Perustelut ehdotukselle   

Kts. assosiatiiviset käsitteet 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi 
**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [maisema-alueet](http://finto.fi/yse/fi/page/Y505011)

**Comment by mirmaid** [comment]
YSAssa on _maisemanhoito, maisemanhoitoalueet, maisemansuojelu, kulttuurimaisema, perinnemaisena_ jne. 

Tässä kyseessä ovat valtakunnallisesti arvokkaat maisema-alueet (156). Toisaalta Suomi jaetaan kuuteen maisema-alueeseen, mikä on vähän eri merkitys.

**Comment by mirmaid** [comment]
Hyväksytty muodossa valtakunnallisesti arvokkaat maisema-alueet (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
nationellt värdefulla landskapsområden
ET landskapsområden
ET värdefulla landskapsområden av riksintresse
