### ISSUE TITLE
Valtatie 25

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5012]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Valtatie 25 

#### Ehdotettu termi ruotsiksi   

Riksväg 25 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tiet](http://www.yso.fi/onto/yso/p1210) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ISBN 978-952-314-269-5 Valtatien 25 palvelutasotarkastelu välillä valtatie 1–maantie 132 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

kts. assosiatiiviset termit 

**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan nimi:** Tatja Pusa **Termiehdotus Fintossa:** [Valtatie 25](http://finto.fi/yse/fi/page/Y505012)

**Comment by mirmaid** [comment]
Ok.

**Comment by LeKorsu** [comment]
OK, näkyyhän tuolla jo muita valtateitä olevan.

**Comment by mariaforsen** [comment]
Allärs: 
Riksväg 25
