### ISSUE TITLE
henkilöbrändäys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5013]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

henkilöbrändäys 

#### Ehdotettu termi ruotsiksi   

personligt varumärke? 

#### Ehdotettu termi englanniksi   

personal branding? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[brändäys](http://www.yso.fi/onto/yso/p25981) 

#### Assosiatiiviset (RT)   

[brändit](http://www.yso.fi/onto/yso/p23851) 

#### Vaihtoehtoiset termit ja ilmaisut   

henkilöbrändit 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Henkil%C3%B6br%C3%A4ndi
https://sv.wikipedia.org/wiki/Personligt_varum%C3%A4rke
-profiloituminen esim. LinkedLnissä jne. liittyy tähän 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

mm. Koivumäki: Markkinointijuridiikka, esipuhe: Teokseen on lisätty kokonaan uusi luku henkilöbrändäyksestä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi 
**Ehdottajan organisaatio:** btj **Termiehdotus Fintossa:** [henkilöbrändäys](http://finto.fi/yse/fi/page/Y505013)

**Comment by mirmaid** [comment]
Melindassa kerran henkilöbrändi, henkilöbrändit, henkilöbrändiviestintä.

Jos otetaan, onko parempi muodossa brändäys vai brändit?

**Comment by tpalonen** [comment]
Google fight tuntuu tukevan brändäys-muotoa. Samoin englannin kielellä branding-muoto näyttäisi yleisemmältä kuin brand.

**Comment by mariaforsen** [comment]
Ruotsiksi käytetään "personligt varumärke".

**Comment by LeKorsu** [comment]
Lehtikieli (= Sanoman arkisto) tukee useammalla osumalla henkilöbrändäys-muotoa, joskin kumpaankin tulee (toistaiseksi) varsin vähän osumia.

**Comment by mirmaid** [comment]
Hyväksytty muodossa henkilöbrändäys (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
personal branding
personbranding
personlig branding
personlig marknadsföring
personligt varumärke
fråga hanken
