### ISSUE TITLE
reliktilajit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5014]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

reliktilajit 

#### Ehdotettu termi ruotsiksi   

reliktart 

#### Alakäsitteet (RT)   

[valkokatka](http://www.yso.fi/onto/yso/p17481) 
[norppa](http://www.yso.fi/onto/yso/p9961) 

#### Assosiatiiviset (RT)   

[kasvisto](http://www.yso.fi/onto/yso/p1754) 
[eläimistö](http://www.yso.fi/onto/yso/p2026) 

#### Vaihtoehtoiset termit ja ilmaisut   

jäännelajit 

#### Tarkoitusta täsmentävä selite   

Reliktilaji tieteen termipankissa: http://tieteentermipankki.fi/wiki/Nimitys:reliktilaji
Reliktilajeja listattu tällä Aaltojen alla -hankkeen sivulla: http://www.aaltojenalla.fi/cgi-bin/bsbw/search.cgi?loc=1&7=7&lang=fin&file=Historia&mark=&tm=universal_1&tm_d=content_1&menu=menu2 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ISBN 978-952-446-800-8 Kolvananuuro ja lähialueet Natura 2000 -alueen hoito- ja käyttösuunnitelma 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarkentaisi "kasvisto" ja "eläimistö" -termejä. 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi 
**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [reliktilajit](http://finto.fi/yse/fi/page/Y505014)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Relict_%28biology%29

RT elävät fossiilit

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
reliktarter 
ET relikter (arter)
