### ISSUE TITLE
Tutkimussuunnitelma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5016]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tutkimussuunnitelma 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Perustelut ehdotukselle   

Tutkimussuunnitelman laadintaan tarvitaan ohjeita, tätä tulisi voida hakea tiedonhaussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Qualitative Research Methods in Human Geography /9780199010905 

**Ehdottajan nimi:** Laura Parikka 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** laura.parikka@uef.fi **Termiehdotus Fintossa:** [Tutkimussuunnitelma](http://finto.fi/yse/fi/page/Y505016)

**Comment by mariaforsen** [comment]
Ruotsiksi olisi forskningsplaner hyvä.

**Comment by mirmaid** [comment]
Käytetty Melindassa 13 kertaa.

**Comment by mirmaid** [comment]
Hyväksytty monikossa (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
forskningsplaner
