### ISSUE TITLE
taiteen maisterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5017]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taiteen maisterit 

#### Vaihtoehtoiset termit ja ilmaisut   

ei ole 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Tarkoitusta täsmentävä selite   

Aalto-yliopiston taiteiden ja suunnittelun korkeakoulun maisteriohjelmista valmistuneiden oppiarvo, Lapin yliopiston taiteiden tiedekunnan maisteriohjelmista valmistuneiden oppiarvo. 

#### Perustelut ehdotukselle   

Vastaavat alemman ja ylimmän tutkintoasteen oppiarvot (taiteen kandidaatit, taiteen tohtorit) löytyvät jo YSA/YSO:sta, samoin Taideyliopistossa käytössä olevat oppiarvot (kuvataiteen maisterit, musiikin maisterit) ja Aalto-yliopiston muissa korkeakouluissa käytössä olevat oppiarvot tai niitä vastaavat käsitteet (kauppatieteiden maisterit, diplomi-insinöörit (temaattinen ryhmä 78), arkkitehdit (temaattinen ryhmä 91). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Thesis design : research meets practice in art and design Master's Theses / Seliger & Hahn (opastaa konkreettisten tapausesimerkkien avulla taiteen maisterin taiteellisen tai produktiopohjaisen opinnäytteen tekemiseen), MoA-näyttelyjulkaisut, opinnäytteet (kun keskeisenä aiheena tai tutkimuskohteena ovat taiteen maistereiden tuottamat opinnäytteet, tutkinto, opinnot, jne). 

**Ehdottajan nimi:** Anni Lemiläinen 
**Ehdottajan organisaatio:** Aalto-yliopiston oppimiskeskus, kirjastopalvelut 
**Ehdottajan sähköpostiosoite:** anni.lemilainen@aalto.fi **Termiehdotus Fintossa:** [taiteen maisterit](http://finto.fi/yse/fi/page/Y505017)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by LeKorsu** [comment]
Ysan maistereiden alta puuttuu myös yhteiskuntatieteiden maisterit.

**Comment by mirmaid** [comment]
Hyväksytty molemmat (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
konstmagistrar 
magistrar i samhällsvetenskaper
