### ISSUE TITLE
viritys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5018]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[viritys](http://www.yso.fi/onto/ysa/Y104872) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö laittaa ryhmään 89 eli musiikki? Tai mahdollisesti jakaa..? 

#### Perustelut ehdotukselle   

Ruotsiksi on vastineeksi valittu stämning ja tämä on oikein musiikkimerkityksessä. Jos tällä viitataan johonkin muuhun (esim. ajoneuvojen..) termi ei enää ruotsiksi ole sama. Ks. MOT:
1 mus stämning 
2 (laitteen säätö) inställning, reglering, justering
3 (pingotus) spänning, spännande 
4 (ansan) gillrande 
5 (moottorin) trimning 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
On käytetty Melindassa moottoreista ja tietotekniikasta (voisikohan siinä merkityksessä tehdä KÄ säätö?). Eniten kuitenkin musiikista, mutta luultavasti tämä pitää jakaa.

**Comment by tpalonen** [comment]
Jos jaetaan, sopisiko sulkutarkenteiksi "viritys (musiikki)" & "viritys (tekniikka)"?

**Comment by mirmaid** [comment]
Kun viritetään radio/antenni tietylle taajuudelle, onko se sama kuin laitteen säätö vai sama kuin musiikissa? Teos: Multiband and environment insensitive handset antennas @tpalonen

**Comment by mirmaid** [comment]
viritys (musiikki tai soittimet)
viritys (moottorit) tai moottorin viritys
viritys (tietotekniikka) KÄ säätö

**Comment by tpalonen** [comment]
Laskisin radion säätämisen kyllä laitteen säädöksi. Radiossa ei säädetä laitteesta lähtevän äänisignaalin äänentaajuutta. Onhan tuon tekniikka/musiikki-jaon välillä tietty päällekkäinen alue, joten se "viritys (soittimet)" voisi olla pikkuisen parempi, jos kirja käsitteleekin musiikki-kontekstissa viriteltäviä oskillaattoreita tai muuta tekniikkaa.

**Comment by ksornova** [comment]
Itsekin kannatan tuota muotoa **viritys (soittimet)**
Musan määritelmä: Soittimen tuottamien äänten keskinäisten suhteiden säätäminen.
Käyttöohje: Termillä tarkoitetaan musiikillisten soittimien virittämistä, ei esimerkiksi elektronisten laitteiden säätämistä.

**moottorin viritys** olisi mielestäni parempi vaihtoehto, jos ratkaisu voi poiketa muista virittämiseen liittyvien termien muodoista.

**Comment by TommiViitamies** [comment]
Kannatan muotoa "viritys (soittimet)" ja MUSAn määritelmää virityksen musiikkimerkityksessä.

**Comment by mirmaid** [comment]
Jaetaan: viritys (soittimet), viritys (moottorit) ja viritys (tietotekniikka) KÄ säätö (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
stämning (instrument), trimning (motorer)
