### ISSUE TITLE
musta lista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5019]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

musta lista 

#### Ehdotettu termi englanniksi   

blacklist 

#### Tarkoitusta täsmentävä selite   

Musta lista on luettelo ei-toivotuista henkilöistä, joilta kielletään jokin palvelu tai sisäänpääsy tai joille ei tarjota töitä. Musta lista voi olla myös luettelo kielletyistä asioista. 

#### Perustelut ehdotukselle   

Yleisesti käytetty termi. https://en.wikipedia.org/wiki/Hollywood_blacklist 
´Tekstin lopussa bibliografia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

KAVIn kirjastossa on Hollywoodin mustasta listasta 61 viitettä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

**Ehdottajan nimi:** Timo Matoniemi 
**Ehdottajan organisaatio:** Kansallinen audiovisuaalinen instituuuti 
**Ehdottajan sähköpostiosoite:** timo.matoniemi@kavi.fi **Termiehdotus Fintossa:** [musta lista](http://finto.fi/yse/fi/page/Y505019)

**Comment by mirmaid** [comment]
LCSH: Blacklisting of entertainers ym.

Ei Melindassa (kerran yksikössä).

**Comment by tpusa** [comment]
Sama kuin **boikotti** tai **työmarkkinaboikotti** (jälkimmäinen ei YSAssa)? Svenska ämnesordissa on "svartlistning", jota on käytetty juuri mm. Hollywood-aiheen kuvailuun. Ohjausterminä "boikotit" ja "työmarkkinaboikotit". 
Suomeksi kai musta**t** lista**t**.

**Comment by LeKorsu** [comment]
Mustat listat voisi käydä myös esim. soittokieltoon joutuneista levyistä, ei vain henkilöistä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
svarta listor
ET svartlistning
