### ISSUE TITLE
väestötiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5020]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väestötiede](http://www.yso.fi/onto/ysa/Y100335) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tämä ei ole oikeastaan muutosehdotus vaan lisäysehdotus: ehdotus lisätä väestöryhmiin biseksuaalit ja transseksuaalit (tai transihmiset, josta on jo tehty aiemmin asiasanaehdotus) 

#### Perustelut ehdotukselle   

on jo olemassa lesbot, homot

(esim. kirja "Social work and lesbian, gay, bisexual and trans people : making a difference) 

#### Ehdottaja   

Tarja Turunen 

#### Ehdottajan sähköpostiosoite   

tarja-liisa.turunen@uef.fi

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1145

**Comment by mariaforsen** [comment]
Myös transsukupuoliset.

**Comment by AuHo22** [comment]
Transtukipisteen hlbtiq-sanastosta: "Transihminen on yleiskäsite, jolla usein kuvataan kaikkia, joiden sukupuoli-identiteetti tai sukupuolen ilmaisu joskus tai aina eroaa odotuksista sille sukupuolelle, johon heidät syntymähetkellä määriteltiin. Transihmisiin luetaan kuuluvan transvestiitit, muunsukupuoliset/transgenderit ja transsukupuoliset. Yksilö, joka voi kokea olevansa muuta kuin cis, ei välttämättä määritä itseään transihmiseksi."
Eli transihmiset ovat eri asia kuin transsukupuoliset, toimii siis yläkäsitteenä jälkimmäiselle. Ehdotan että otetaan sekä transsukupuoliset että transihmiset, ja transihmisten ST:ksi transsukupuolisten rinnalle myös transvestiitit (transvestismi jo aiemmin sanastossa).
Biseksuaalit on puolestaan selkeästi hyväksyttävä termiehdotus.

**Comment by YSA-kokous** [comment]
Otetaan biseksuaalit ja transihmiset.

**Comment by YSA-kokous** [comment]
Otetaan biseksuaalit ja transihmiset.

**Comment by mariaforsen** [comment]
Sv. 
-bisexuella 
-transpersoner ET transgenderpersoner
