### ISSUE TITLE
aatenäytelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5021]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aatenäytelmät 

#### Ehdotettu termi ruotsiksi   

idédrama 

#### Ehdotettu termi englanniksi   

problem play 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjalliset teokset](http://www.yso.fi/onto/yso/p1150) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Muutkin näytelmän lajityypit ovat omina termeinään YSAssa. Kitussa aatedraama yksikössä, ja tuo draamakin varmaan pitäisi muuttaa näytelmäksi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bibid 545297 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [aatenäytelmät](http://finto.fi/yse/fi/page/Y505021)

**Comment by mirmaid** [comment]
Kaunokissa muodossa _aatedraamat_, jota käytetty Melindassa muutaman kerran (aika jännästi...). _Aatedraama_ kerran Artossa.

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:aatedraama

**Comment by mariaforsen** [comment]
Sv.  idédrama /mot, tepa

**Comment by OutiHintikka** [comment]
Aatedraama on vakiintunut muoto! Ei saa muuttaa.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa aatedraama.

**Comment by mirmaid** [comment]
Jos viittaa näytelmiin, pitäisi kuitenkin ottaa monikko, kuten Kaunokissa.

**Comment by YSA-kokous** [comment]
aatedraamat
