### ISSUE TITLE
aateromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5022]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aateromaanit 

#### Ehdotettu termi ruotsiksi   

idéromaner 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kertomakirjallisuus](http://www.yso.fi/onto/yso/p2128) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Muitakin romaanin alalajeja on YSAssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bibid 50625 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [aateromaanit](http://finto.fi/yse/fi/page/Y505022)

**Comment by mirmaid** [comment]
Kaunokissa.

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:aateromaani

**Comment by mariaforsen** [comment]
Sv. idéromaner

**Comment by OutiHintikka** [comment]
Ok, klassinen termi! Eroaa tendenssiromaaneista.
