### ISSUE TITLE
aukko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5023]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aukko 

#### Ehdotettu termi ruotsiksi   

öppet ställe 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Ilmaisematta tai vihjauksen varaan jätetty, yleensä tulkintaan yllyttävä tekstin kohta, joka jää lukijan täydennettäväksi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton bibid1308122 

#### Perustelut ehdotukselle   

Kirjallisuudentutkimuksessa tarvittava käsite. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [aukko](http://finto.fi/yse/fi/page/Y505023)

**Comment by mirmaid** [comment]
KITOssa muodossa _avoin kohta_, joka olisi minusta parempi. Siinä muodossa muutaman kerran Artossa.

**Comment by mariaforsen** [comment]
Vaatii varmaan sulkutarkenteen tai ainakin huomautuksen.

**Comment by AuHo22** [comment]
"Semiootikko Roland Barthes käyttää kirjallisuusanalyysissaan epookki-termin semanttista johdosta, joka on suomennettu "halkeamaksi" (ks. Kirstinä). Yrjö Hosiaisluomalla (2003: 77) esiintyy kirjallisuuden sanakirjassaan hakusanana pelkkä "aukko". Se vastaa historiallisesti Roman Ingardenin termiä "epämääräisyyskohta" (Unbestimmtheitsstelle) tai Wolfgang Iserin termiä "avoin kohta" (Leerstelle). "
Itselleni tuttu ensisijaisesti Iserin ajattelusta. Jossain tuli myös vastaan "tekstuaalinen aukko". 

yo. sitaatti - http://sokl.uef.fi/verkkojulkaisut/tutkivaope/jamsa.htm

**Comment by tpusa** [comment]
Aukko (tarinat) tai aukko (kerronta)?

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa avoin kohta.

**Comment by mariaforsen** [comment]
Sv. öppet ställe ET textuell lucka
