### ISSUE TITLE
fenomenologinen kirjallisuudentutkímus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5024]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fenomenologinen kirjallisuudentutkímus 

#### Ehdotettu termi ruotsiksi   

fenomenologisk litteraturforskning 

#### Ehdotettu termi englanniksi   

phenomenological criticism 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Muutkin kirjallisuudentutkimuksen suuntaukset ovat YSAssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bibid 555886 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [fenomenologinen kirjallisuudentutkímus](http://finto.fi/yse/fi/page/Y505024)

**Comment by mirmaid** [comment]
2 kertaa Melindassa, ei Artossa. Googlella löytyy vain tämä ehdotus.

**Comment by krinay** [comment]
Melindassa ja Artossa on käytetty usein termejä kirjallisuudentutkimus + fenomenologia. Fenomenologinen kirjallisuudentutkimus sopisi suurimpaan osaan näistä.

http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:fenomenologinen_kirjallisuudentutkimus

Ks. myös esim. tämä pro gradu -tutkielma vuodelta 2010: http://hdl.handle.net/123456789/22980

**Comment by mirmaid** [comment]
Googlella löytyy vain tämä ehdotus, jos tekee haun kopioimalla ehdotetun termimuodon :laughing:. Suoraan sanoen vähän ihmettelinkin asiaa...

**Comment by AuHo22** [comment]
Ote on laajemminkin taiteitten tutkimuksessa käytössä, esim fenomenologinen tanssintutkimus tai fenomenologinen teatterintutkimus, mutta niitä lienee ehdotettava erikseen.

**Comment by OutiHintikka** [comment]
Aulin kanssa sanaa mieltä!

**Comment by mariaforsen** [comment]
Sv. fenomenologisk litteraturforskning

**Comment by OutiHintikka** [comment]
ok


________________________________
Lähettäjä: mariaforsen <notifications@github.com>
Lähetetty: 19. toukokuuta 2017 14:50
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] fenomenologinen kirjallisuudentutkímus (#5024)


Sv. fenomenologisk litteraturforskning
