### ISSUE TITLE
rautatievirkamiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5025]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rautatievirkamiehet](http://www.yso.fi/onto/ysa/Y108288) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisäys: LT virkamiehet 

#### Perustelut ehdotukselle   

Jos termi "rautatievirkamiehet" viittaa nimenomaan virkamiehiin, olisi tätä kuvastava LT-ST-suhde syytä lisätä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Lisätty LT-suhde.
