### ISSUE TITLE
lyömäsoitinmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5026]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lyömäsoitinmusiikki 

#### Ehdotettu termi englanniksi   

percussion music 

#### Ehdotettu termi ruotsiksi   

slagverksmusik 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85099763> 
Englanninkielinen Wikipedia : https://en.wikipedia.org/wiki/Category:Percussion_music 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle lyömäsoittimelle. 

#### Perustelut ehdotukselle   

Antaa mahdollisuuden käyttää täsmällistä asiasanana usean termin sijaan ("musiikki" + "lyömäsoittimet"), varsinkin jos kuvailtava teos ei käsittele lyömäsoittimia itseään. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Percussion solo literature / THomas Siwe, editor 

#### Vaihtoehtoiset termit ja ilmaisut   

perkussiomusiikki 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [lyömäsoitinmusiikki](http://finto.fi/yse/fi/page/Y505026)

**Comment by ksornova** [comment]
Samantyyppisiä termejä on varmaan tulossa lisää...

**Comment by tpalonen** [comment]
Sopisiko soitinmusiikki tämän yläkäsitteeksi?

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mirmaid** [comment]
LT musiikki vai soitinmusiikki?
RT? YSAssa on ainakin lyömäsoittimet, lyömäsoittajat

**Comment by mirmaid** [comment]
LT nyt musiikki
RT lyömäsoittimet, lyömäsoittajat

**Comment by TommiViitamies** [comment]
LT soitinmusiikki
RT lyömäsoittimet, lyömäsoittajat

**Comment by ksornova** [comment]
LT pitäisi olla kuitenkin olla laajempi termi _musiikki_ , sillä yhdessä lyömäsoitinmusiikkia käsiteltävässä kirjassa oli kuulemmani mukaan yksi luku, jossa oli myös laulaja mukana?

@jtuohini: vai muistanko väärin?
