### ISSUE TITLE
soitonopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5027]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soitonopettajat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[opettajat](http://www.yso.fi/onto/yso/p1117) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Luumu 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [soitonopettajat](http://finto.fi/yse/fi/page/Y505027)

**Comment by ksornova** [comment]
Tarkennus: ehdotus on violalaisten.

**Comment by TommiViitamies** [comment]
Kannatan. Entä: musiikinopettajat?

**Comment by ksornova** [comment]
voit tehdä uuden termiehdotuksen, jos termille on tarvettta .)

**Comment by LeKorsu** [comment]
Musiikinopettajat (jo ysassa) viittaa minun käsitemaailmassani selkeästi peruskoulu/lukio-opetukseen, kun taas soitonopettajat yksittäisen intstrumentin opettamiseen musiikkioppilaitoksissa, eli kannatan lisäystä. Ysassa on myös laulunopettajat.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
instrumentlärare
ET instrumentallärare
ET instrumentpedagoger

**Comment by mirmaid** [comment]
RT?

**Comment by jtuohini** [comment]
Kolme hyvää KT-termiä tuli vastaan tähän sopien: **instrumenttiopettajat** (https://www.jamk.fi/fi/Koulutus/Kulttuuriala/musiikkipedagogi/instrumenttiopettaja-musiikki/), **instrumenttipedagogit** (http://opinto-opas-ops.tamk.fi/index.php/fi/167/fi/55327/14MU/772/year/2014) ja **soitinpedagogit** (http://www.mutesry.com/pdf/mupeseminaari_lotta_ilomaki.pdf). Menevätkö vielä tämän pohjalta (kun käsittely on jo suljettu) vai pitääkö tehdä erillinen muutosehdotus?

**Comment by mirmaid** [comment]
Lisätty Jaakon ehdottamat KT:t.
