### ISSUE TITLE
kelluvat rakennukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5028]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kelluvat rakennukset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset](http://www.yso.fi/onto/yso/p1786) 

#### Perustelut ehdotukselle   

Aihe on esillä mm. Helsingin Kalasataman rakennushankkeen takia. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Finto-feedback 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [kelluvat rakennukset](http://finto.fi/yse/fi/page/Y505028)

**Comment by mirmaid** [comment]
Melindassa kerran _kelluvat asunnot_.

**Comment by Elmukelmu** [comment]
Olisin varmasti jo käyttänytkin, näistä kirjotellaan koko ajan. Ja kaikki ei ole asuntoja eli kelluvat rakennukset on hyvä.

**Comment by satuniininen** [comment]
Englanniksi varmaankin _floating buildings_ tai _floating houses_. Kumpaakaan ei löydy LCSH:sta.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs:
flytande byggnader
ET byggnader på vatten
ET flytande bostäder
ET flytande hus
