### ISSUE TITLE
opetusohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5029]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[opetusohjelmat](http://www.yso.fi/onto/ysa/Y97812) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Nyt löytyy opetusohjelmat RT koulutusohjelmat, opetussuunnitelmat, sekä opetusohjelmat – televisio ja opetusohjelmat – radio.
 
Kielitoimiston sanakirja:
1. radion ja television kouluohjelmista, kielikursseista yms. 
2. opetuksessa noudatettava ohjelma. Kurssin opetusohjelma. 
3. opetukseen käytettävä tietokoneohjelma. 

#### Ehdotettu muutos   

Selvennettävä 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSOssa ohjelmat on jaettu: ohjelmat (radio- tai tv-ohjelmat) ja ohjelmat (suunnitelmat). Ensimmäinen on varmaan ok tarkenne myös opetusohjelmille (tai voidaan pitää nykyinen erittely, vaikka se onkin ketjumainen). Suunnitelmat on ongelmallinen tarkenne kun sanastossa on myös termi opetussuunnitelmat, eikä esim. kansalaisopiston opetusohjelma välttämättä hahmotu niinkään suunnitelmana kuin ”tarjontana”.

**Comment by mirmaid** [comment]
opetusohjelmat (media) & opetusohjelmat (opinnot/koulutus/opetus(ala)/oppilaitokset)?

**Comment by LeKorsu** [comment]
Tuo toinen sulkutarkenne, oma suosikkini joko opinnot tai koulutus.

**Comment by mirmaid** [comment]
opetusohjelmat (media) & opetusohjelmat (oppilaitokset), jos onnistuu (YSA-kokous 7.3.2017).

**Comment by ilona-x** [comment]
Käyty läpi n. 200 Melinda-viitettä, ja tarkenteet (media) & (oppilaitokset) ovat OK joitakin viitteitä lukuun ottamatta: esim. "Työ ja oppiminen yrityksissä : ongelmista ratkaisuihin " & "Toimiva opetusohjelma peukalon imemisen lopettamiseksi koululuokassa".

Oliko tarkoitus ottaa lisäksi tuo 3. merkitys "opetukseen käytettävä tietokoneohjelma", sillä tuossa merkityksessä Melindasta löytyy melko paljon viitteitä?

Melindan perusteeella ehdotus siis olisi:
opetusohjelmat (media)
opetusohjelmat (oppilaitokset)
opetusohjelmat (tietokoneohjelmat)

**Comment by mariaforsen** [comment]
Sv. 
-undervisningsprogram (media)
-undervisningsprogram (läroanstalter)
-datorprogram för inlärning
