### ISSUE TITLE
reduktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5030]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[reduktio](http://www.yso.fi/onto/ysa/Y106349) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Ryhmät 02 ja 52 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty myös ainakin kielitieteessä.

**Comment by mirmaid** [comment]
Issue: https://github.com/NatLibFi/Finto-data/issues/777

**Comment by mariaforsen** [comment]
Allärs nyt: reduktio = reduktion (filosofi), pelkistys=reduktion (kemi). Sen lisäksi olisi ainakin reduktion (språk), reduktionen (historia)

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kielitiede:reduktio

reduktio (kielitiede), reduktio (filosofia) ja reduktio (historia)? Viimeisin on tosin sikäli vähän hassu, että "historia" ei nyt oikeastaan kerro mihin reduktio-termillä viitataan, mutta ei siinä varmaan väärinymmärryksen vaaraa silti ole.

**Comment by YSA-kokous** [comment]
Hyväksytään tarkenteet.

**Comment by mariaforsen** [comment]
Sv.
reduktion (språkvetenskap)
reduktion (filosofi)
reduktion (historia)

**Comment by mirmaid** [comment]
Ehdotettu monikkoa/selvennystä.

**Comment by mirmaid** [comment]
Nykyisessä muodossaan viittaisi yleisesti lahjoitusmaiden peruuttamiseen toimenpiteenä, monikko enemmän historiallisiin tapahtumiin https://sv.wikipedia.org/wiki/Svenska_reduktioner.

**Comment by mirmaid** [comment]
Aineistojen perusteella taipuisin ehkä itse kannattamaan kuitenkin monikkoa.

**Comment by YSA-kokous** [comment]
reduktiot (historia)
