### ISSUE TITLE
perusvoimat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5031]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

perusvoimat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Tarkoitusta täsmentävä selite   

Hiukkasfysiikan ns. standarditeorian mukaan perusvoimia on neljä. Äskettäin löytynyt uusi hiukkanen voi merkitä, että perusvoimia onkin viisi. Viidettä perusvoimaa ei vielä tunneta. 

#### Perustelut ehdotukselle   

Hiukkasfysiikan artikkeleita hankala asiasanoittaa ilman termiä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tieteen Kuvalehti 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy / Booky 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [perusvoimat](http://finto.fi/yse/fi/page/Y505031)

**Comment by mirmaid** [comment]
YSAssa on _hiukkasfysiikan standardimalli_. Standardimalli kuvaa kolme ns. perusvuorovaikutusta (kutsutaan myös perusvoimiksi) https://fi.wikipedia.org/wiki/Perusvuorovaikutus, neljäs olisi painovoima. YSAssa on painovoima KÄ _gravitaatio_, muita vuorovaikutuksia ei ole auktorisoitu. Yksi mahdollisuus olisi auktorisoida kukin erikseen, tai yhdessä perusvuorovaikutukset tms.

**Comment by mariaforsen** [comment]
Sv. fundamentala naturkrafter/fundamentala krafter? Perusvuorovaikutus=fundamental växelverkan

**Comment by satuniininen** [comment]
Kannatan muotoa _perusvuorovaikutus_, engl. fundamental interaction
https://en.wikipedia.org/wiki/Fundamental_interaction

**Comment by mirmaid** [comment]
Olettaisin että tämä pitää ottaa monikossa, vaikka taipuukin vähän kömpelösti: _Hiukkasfysiikan standardimallin kuvailemat kolme perusvuorovaikutusta ovat..._

**Comment by YSA-kokous** [comment]
Otetaan perusvuorovaikutukset.

**Comment by mariaforsen** [comment]
Sv. fundamentala krafter ET fundamental växelverkan ET fundamentala naturkrafter ET fundamentala växelverkningar
