### ISSUE TITLE
oikeusturvalautakunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5032]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oikeusturvalautakunnat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mikä on urheilun oikeusturvalautakunnan toimivalta ja vastaako se lautakunnan tarkoitusta? 

#### Perustelut ehdotukselle   

- 

**Ehdottajan nimi:** - 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [oikeusturvalautakunnat](http://finto.fi/yse/fi/page/Y505032)

**Comment by mirmaid** [comment]
Melindassa kerran Urheilun oikeusturvalautakunta kohdeyhteisönä. 

Opiskelijoiden oikeusturvalautakunta, myös joillakin oppilaitoksilla.

**Comment by mariaforsen** [comment]
Sv. rättsskyddsnämnder.

**Comment by LeKorsu** [comment]
Minä olen myös käyttänyt kohdeyhteisönä useamman kerran Urheilun oikeusturvalautakuntaa, enkä ole tuntenut tarvetta lisätä oikeusturvalautakunnat omana asiasanana, mutta en myöskään vastusta, koska silloin sitä voi käyttää monissa yhteyksissä.

**Comment by mirmaid** [comment]
Hyväksytty (YSA-kokous 7.3.2017).

**Comment by mariaforsen** [comment]
Allärs: 
rättsskyddsnämnder
