### ISSUE TITLE
bibliografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5033]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[bibliografia](http://www.yso.fi/onto/ysa/Y94862) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

YSA:ssa on sekä yksikkö että monikkomuoto termistä Bibliografia. Fennicassa niitä näkyy käytetyn ihan rinnakkain.
Onko milloinkaan tullut esille, että niistä toinen olisi ikään kuin muototermi ja toinen aihetta kuvaava? 

#### Ehdotettu muutos   

yhdistettävä tai selkeytettävä 

#### Ehdottaja   

KK 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
bibliografia KÄ _bibliografiat_

**Comment by mariaforsen** [comment]
YSOssa tulkittu: bibliografia (tieteet) ja bibliografiat (luettelot), ja sen mukaan tehty Allärsissa "bibliografi (vetenskap)" ja "bibliografier".

**Comment by mirmaid** [comment]
^ Tuo tulkinta on YSAssakin varmasti ollut taustalla, mutta termejä ei ole osattu käyttää sen mukaan.

**Comment by mirmaid** [comment]
Bibliografi (vetenskap) ei viitteitä Melindassa. Onko mahdollista poistaa YSOsta?

**Comment by mariaforsen** [comment]
On mahdollista ainakin poistaa Allärsista, ja jos kirja käsittelee bibliografia tieteenä niin kyllä yleensä pitäisi laittaa bibliografiat/bibliografier myös. Eli jäljelle jäisi vain "bibliografiat" YSAaan?

Muutenkin kannattaisi mielestäni välttää tämäntyyppisiä yksikkö- ja monikko-pareja. Aiheuttavat yleensä hämmennystä ja/tai sitä että otetaan joko molempia mukaan asiasanoina tai sitten "sattumanvaraisesti" (eikä loogisesti) laitetaan vain yksi niistä (->aiheuttaa epätäsmällisiä tiedonhakutuloksia)

**Comment by YSA-kokous** [comment]
Mikko selvittää

**Comment by MikkoAleksanteri** [comment]
Tieteenala bibliografia ei tutki (vain) bibliografioita. 

Wikipedia: 
_Bibliografia (m.kreik. βιβλιογραφία = βιβλίο + γραφία = βιβλίο + γραφή= kirja + kirjoitus, bibliographia) on joko

-     bibliografinen luettelo,
-     taito tehdä bibliografioita tai
-     tekstuaalitieteisiin kuuluva kirjoja koskeva tutkimus, jonka alalaji on esimerkiksi analyyttinen bibliografia.

[1][2]_ https://fi.wikipedia.org/wiki/Bibliografia

Tieteen termipankki: 
_**bibliografia(1)** (Tekstuaalitieteet) Teosluettelo (enumeratiivinen bibliografia), jossa luetellaan kirjoja, lehtiä, artikkeleita tai muita kirjallisia julkaisuja.
Lue koko artikkeli
**bibliografia(2)** (Tekstuaalitieteet) Tieteenala, joka tutkii kirjoja fyysisinä esineinä sekä niiden tuottamisen ja julkaisemisen tapoja.
Lue koko artikkeli_

Tekstuaalitieteiden sanasto (Suomalaisen Kirjallisuuden Seura):
**1Teosluettelo (» enumeratiivinen bibliografia), jossa luetellaan » kirjoja, lehtiä, artikkeleita tai muita kirjallisia » julkaisuja.
2Tieteenala, joka tutkii kirjoja fyysisinä esineinä sekä niiden tuottamisen ja julkaisemisen tapoja.**

Tieteenala alakäsitteet lisäksi esim.: » Analyyttinen bibliografia  » Deskriptiivinen bibliografia  » Historiallinen bibliografia  » Kirjahistoria  » Tekstuaalinen bibliografia  

Melindasta löytyy monta teosta joissa aiheena bibliografia tieteenalana.

**Comment by mirmaid** [comment]
Ehdotus: _bibliografia (tieteet)_ ja _bibliografiat_. Monikko ei tarvitse sulkutarkennetta.

**Comment by YSA-kokous** [comment]
bibliografia (tieteet) ja bibliografiat
