### ISSUE TITLE
romanikielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5035]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Romany literature 

#### Ehdotettu termi suomeksi   

romanikielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kielistä on oma terminsä YSAssa.On myös Kitun/KITOn asiasana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa asiasanaketjuja purettaessa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [romanikielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505035)

**Comment by mirmaid** [comment]
Käytetty kerran Artossa

**Comment by mariaforsen** [comment]
Sv. romsk litteratur ET litteratur på romani
