### ISSUE TITLE
katkelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5036]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

katkelmat 

#### Ehdotettu termi englanniksi   

fragments 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun & KITOn usein käytetty termi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esim. Jahrbuch für finnisch-deutsche Literaturbeziehungenissa on usein käännöspätkiä romaaneista. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [katkelmat](http://finto.fi/yse/fi/page/Y505036)

**Comment by mirmaid** [comment]
Melindassa kerran musiikkiin liittyen, Artossa käytetty runsaasti (n. 200 viitettä) muototerminä (?).

**Comment by mariaforsen** [comment]
Sv. utdrag? Fragment on jo sanastossa (eikä sitä saisi poistaa/muuttaa).

**Comment by AuHo22** [comment]
Aiemmin kuvailussa voitu käyttää termejä fragmentit (00) ja tekstit (85).

**Comment by tpusa** [comment]
Pitääkö erotella katkelmat (tekstit) ja katkelmat (musiikki)?

**Comment by siikaa** [comment]
Kaunokissa katkelmat KÄYTÄ  fragmentit (T). Katkelmat olis kivampi.

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by YSA-kokous** [comment]
Genresanastoon?

**Comment by krinay** [comment]
Termiehdotuksen tekijät (KITU-sanaston ylläpitäjät) kaipaavat termiä lähinnä muototerminä eli sen saaminen genresanastoon voisi riittää.

Kaunokissa on paitsi _fragmentit KT katkelmat_ myös _otteet_. 
Jos _katkelmat_ tuntuu hankalta, _otteet_ olisi hyvä vaihtoehto. Kielitoimiston sanakirjan mukaan otteet = "alkuperäisestä kirjallisesta kokonaisuudesta jäljennetty osa". 

Fragmentit-termissä hieman häiritsee sen assosioituminen jäännökseen eli hävinneestä kokonaisuudesta jäljelle jääneeseen osaan. Mutta kyllä sekin välttää, jos ei haluta ottaa toista merkitykseltään läheistä termiä. (Oli jäänyt aiemmin huomaamatta.)

fragmentit - fragment - fragments
otteet/katkelmat - utdrag - excerpts

Mutta mitenkähän tämä menee musiikin alalla?

**Comment by mirmaid** [comment]
Lajityyppi- ja muotosanastoon otettiin _katkelmat_ KT otteet. Tarvitaanko tätä aiheena?

**Comment by YSA-kokous** [comment]
Ei tarvita.

**Comment by mirmaid** [comment]
Palaute: _Yläkäsite on musiikki, mutta termi itsessään ei rajaudu mitenkään musiikkiin. Mihin tämä oikeastaan viittaa?_

**Comment by MUUSA-kokous** [comment]
Ehdotetaan SLM:ssä yläkäsitteen "musiikki" poistamista ja korvaamista kategorialla "Suomalainen lajityyppi- ja muotosanasto".

**Comment by mirmaid** [comment]
Poistetaan yläkäsite.
