### ISSUE TITLE
runoproosa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5037]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

runoproosa 

#### Ehdotettu termi englanniksi   

poetic prose 

#### Ehdotettu termi ruotsiksi   

poetisk prosa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Proosateksti, joka kieleltään, rytmiltään ja rakenteeltaan lähenee runoa. 

#### Perustelut ehdotukselle   

Kitun & KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton asiasanaketjujen purkamisessa, esim. Bibid 1555158 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [runoproosa](http://finto.fi/yse/fi/page/Y505037)

**Comment by mirmaid** [comment]
Ei Melindassa tai Artossa. Kirjallisuuden sanakirjassa tämä on erotettu proosarunosta, mutta eroa on kyllä aika vaikea hahmottaa. Wikipedia poetic prose > prose poetry.

**Comment by mariaforsen** [comment]
Sv. poetisk prosa ET diktprosa ok.

**Comment by AuHo22** [comment]
Kaunokissa YSAn tapaan vain proosarunot.

**Comment by YSA-kokous** [comment]
KÄ proosarunot

**Comment by mariaforsen** [comment]
Sv. poetisk prosa ANV prosadikter

**Comment by mirmaid** [comment]
Kaunokissa on erikseen runoromaanit.

**Comment by YSA-kokous** [comment]
runoproosa KÄ runoromaanit

**Comment by mariaforsen** [comment]
Sv. versromaner ET diktromaner, poetisk prosa
