### ISSUE TITLE
ensyklopedinen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5038]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ensyklopedinen 

#### Ehdotettu termi englanniksi   

encyclopedical 

#### Ehdotettu termi ruotsiksi   

ensyklopedisk 

#### Tarkoitusta täsmentävä selite   

Kaikenkattava, perinpohjainen, tietosanakirjamainen. Käsitettä on käytetty sellaisista kaunokirjallisista teoksista, jotka ovat poikkeuksellisen monipuolisia ja laaja-alaisia... Esim. Ulysses, Raamattu, Don Quijote.  (Hosiaisluoma, 2003) 

#### Perustelut ehdotukselle   

Kitun/KITON termi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [ensyklopedinen](http://finto.fi/yse/fi/page/Y505038)

**Comment by jtuohini** [comment]
Termin pitäisi mieluummin olla muodossa **ensyklopedisyys** (substantiivi adjektiivin sijaan, analogiana muiden vastaavien YSA-termien kanssa, kuten _abstraktisuus_ ja _hyödyllisyys_).

**Comment by mirmaid** [comment]
Artossa kerran _ensyklopedinen novelli_.

**Comment by krinay** [comment]
Voisiko olla muodossa ensyklopedisuus (ei siis ensyklopedisyys). Ks. esimerkiksi
Hyvönen, Jouni: Ensyklopedisuus ja Lönnrotin eeposprojekti / Jouni Hyvönen
https://arto.linneanet.fi/vwebv/holdingsInfo?searchId=505&recCount=10&recPointer=0&bibId=1430019
ja
Sivonen, Jari: Mutkia matkassa (väitöskirja)
http://melinda.kansalliskirjasto.fi/F/DU8XNT8JFCG2G934NTR8PL8JINLXBXSYM3C576BAV2EPUURP88-17396?func=full-set-set&set_number=156983&set_entry=000003&format=999

**Comment by krinay** [comment]
Ensyklopedisuus ei olisi vain kirjallisuudentukimuksen termi, vaan käyttökelpoinen muillakin aloilla, mm. kielitieteessä ja folkloristiikassa.

**Comment by mariaforsen** [comment]
Sv. encyklopedisk. Ensyklopedisuus mahdollisesti "encyklopedisk karaktär" ? Muuten mahdoton kääntää.

**Comment by AuHo22** [comment]
Tieteen termipankissa _ensyklopedinen_ -termin kohdalla viitataan Northrop Fryen kirjallisuudenteorian esitykseen Anatomy of criticism, ja sama katkelma on joissain muissakin sanastoissa selitteenä  esimerkkeineen.  Palaan teokseen itse sen joskus tenttineenä - takakannessa mm.: "simply overpowering in the originality of its main concepts". (Eikä ensyklopedinen ehkä kuitenkaan sen pääkäsitteitä. ) Eli kyseessä lähtökohtaisesti kontroversielli ajattelu? - mitä itsekin muistan.
Vrt. aiempi käsite "avoin kohta", joka on yleisesti kirjallisuudentutkimuksessa hyväksytty ja sen kohdalla ongelma ehkä vain se, millä termillä sitä kutsutaan.
Jotenkin ajattelisin, että kirjallisuuden alalla termi sopisi paremmin Kaunokkiin kuvaamaan itse kaunokirjallisen taideteoksen luonnetta eikä YSAan. Muista tieteenaloista en osaa sanoa.

**Comment by OutiHintikka** [comment]
suosittaisin muotoa: ensyklopedinen kirjallisuus. keskiaikainen kirjallisuuslaji.

**Comment by OutiHintikka** [comment]
Ks. Encyclopedic novel

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Encyclopedic_novel

**Comment by YSA-kokous** [comment]
Hyväksytään ensyklopediset romaanit.

**Comment by mariaforsen** [comment]
Sv. encyklopediska romaner
