### ISSUE TITLE
valtuustot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5040]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valtuustot 

#### Ehdotettu termi ruotsiksi   

fullmäktigeförsamlingar 

#### Ehdotettu termi englanniksi   

representative assemblies 

#### Ehdotettu yläkäsite YSOssa (LT)   

[organisaatiot (järjestelmät)](http://www.yso.fi/onto/yso/p272) 

#### exactMatch   

YSO : <http://finto.fi/yso/fi/page/p5256> 

#### Perustelut ehdotukselle   

- termi löytyy jo YSO:sta
- aineisto käsittelee kaupunginvaltuustoa, sairaanhoitopiirin valtuustoa & maakuntaliiton valtuustoa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fullmäktigeförsamlingar i ljuset av språklig växelverkan : tvåspråkighet i tre fullmäktigeförsamlingar 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi

**Comment by mirmaid** [comment]
Ok.

**Comment by mariaforsen** [comment]
Allärs: fullmäktigeförsamlingar ET fullmäktige (organ)

**Comment by mirmaid** [comment]
Hyväksytty.

**Comment by mariaforsen** [comment]
Allärs:
fullmäktigeförsamlingar
ET fullmäktige (organ)
