### ISSUE TITLE
shakuhachi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5041]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

shakuhachi 

#### Ehdotettu termi englanniksi   

shakuhachi 

#### Ehdotettu termi ruotsiksi   

shakuhachi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[huilusoittimet](http://www.yso.fi/onto/yso/p10307) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85121066> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Shakuhachi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Japanilainen päästäpuhallettava puusta tai bambusta tehty noin 55 cm pitkä huilusoitin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The shakuhachi in the European diaspora 

#### Perustelut ehdotukselle   

Nykyinen YSA-termi "huilusoittimet" on turhan epätarkka, kun shakuhachi on kuitenkin varsin yleinen; on myös huomioitu soitinnimisanastossa. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [shakuhachi](http://finto.fi/yse/fi/page/Y505041)

**Comment by mariaforsen** [comment]
Sv. shakuhachi
