### ISSUE TITLE
maaseuturomaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5043]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maaseuturomaanit 

#### Ehdotettu termi englanniksi   

provincial novels KITOssa, Hosiaisluomalla ja termipankissa rural novels, joka ehkä parempi 

#### Ehdotettu termi ruotsiksi   

bygderomaner 

#### Ehdotettu yläkäsite YSOssa (LT)   

[romaanit](http://www.yso.fi/onto/yso/p1896) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esimerkiksi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [maaseuturomaanit](http://finto.fi/yse/fi/page/Y505043)

**Comment by mirmaid** [comment]
Kaunokissa, paljon käytetty kaunokirjallisuuden kuvailussa.

**Comment by mariaforsen** [comment]
Sv. bygderomaner ET allmogeromaner ET bonderomaner
