### ISSUE TITLE
metatekstuaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5044]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metatekstuaalisuus 

#### Ehdotettu termi englanniksi   

metatextualism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tekstilähtöinen kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p28253) 

#### Alakäsitteet (RT)   

[metafiktio](http://www.yso.fi/onto/yso/p17999) 

#### Tarkoitusta täsmentävä selite   

Sanataideteoksia itse tekstiin pitäytymällä erittelevä ja tulkitseva tutkimussuuntaus, teoskeskeinen metodi. 

#### Perustelut ehdotukselle   

KITOn termi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [metatekstuaalisuus](http://finto.fi/yse/fi/page/Y505044)

**Comment by mirmaid** [comment]
3 kertaa Melindassa, 7 kertaa Artossa. 

Kirjallisuuden sanakirja: _Tekstin kommentoiva suhde toiseen tekstiin; tilanne, jossa myöhempi teksti puhuu aiemmasta tekstistä; esim. tekstikritiikki kuuluu metatekstuaalisuuden piiriin._

**Comment by mariaforsen** [comment]
Sv. metatextualitet

**Comment by AuHo22** [comment]
Myös kielitieteessä käytetty termi. Selite ei kuvaava?

**Comment by OutiHintikka** [comment]
Selite on huono! Tarvitaanko genrenä? Kuinka paljon kirjallisuutta on lopulta tutkittu metakirjallisuutena. Kirj.tutkimuksessa käytetympi termi - myös laajemmissa yhteyksissä  - on metafiktio. Sen sijaan olen kaivannut usein transtekstuaalisuutta, teoksen komentaarista/hyödyntävää suhdetta muihin taidelajeihin.
