### ISSUE TITLE
esseistiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5046]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

esseistiikka 

#### Ehdotettu termi englanniksi   

essaystic literature 

#### Alakäsitteet (RT)   

[esseet](http://www.yso.fi/onto/yso/p19188) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [esseistiikka](http://finto.fi/yse/fi/page/Y505046)

**Comment by mirmaid** [comment]
Kerran Melindassa, n. 20 kertaa Artossa.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: esseekirjallisuus

**Comment by mariaforsen** [comment]
Sv. essäistik ET essäistisk litteratur
