### ISSUE TITLE
sanataidekasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5047]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sanataidekasvatus 

#### Ehdotettu termi englanniksi   

literary art education 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taidekasvatus](http://www.yso.fi/onto/yso/p5457) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

KITOn termi, muidenkin taiteen lajien "kasvatukset"  YSA/YSOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esimerkiksi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [sanataidekasvatus](http://finto.fi/yse/fi/page/Y505047)

**Comment by mirmaid** [comment]
Ei Artossa tai Melindassa, mutta Googlella n. 1000.

**Comment by mirmaid** [comment]
Melindassa 8 kertaa _kirjallisuuskasvatus_, Google n. 1900.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/584

**Comment by mariaforsen** [comment]
Sv. Suomessa on yksi taho käyttänyt "ordkonstfostran" (ei suositeltava)

**Comment by AuHo22** [comment]
Onko sanataidekasvatuksen ja kirjallisuuskasvatuksen välillä ikäluokkaeroa? Sanataidekasvatus ihan pienille ja kirjallisuuskasvatus isommille?

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by krinay** [comment]
Sanataidekasvatuksen tavoitteena on tukea lapsen suullisen ja kirjallisen ilmaisun kehittymistä, lapsen omaa luovaa toimintaa.
 
K]irjallisuuskasvatuksen tavoitteena on ohjata kirjallisuuden pariin, innostaa ja syventää lukuharrastusta.

**Comment by YSA-kokous** [comment]
sanataidekasvatus KT kirjallisuuskasvatus, seuraava kokous

**Comment by mirmaid** [comment]
ordkonstundervisning vähän käytetympi kuin -fostran?

**Comment by mirmaid** [comment]
"sanataidekasvatus on ennen kaikkea luovaa kirjoittamista" https://tampub.uta.fi/bitstream/handle/10024/84877/gradu06949.pdf?sequence=1

**Comment by YSA-kokous** [comment]
otetaan molemmat

**Comment by mariaforsen** [comment]
Sv. 
-ordkonstfostran ET ordkonstpedagogik, ordkonstundervisning
-litteraturfostran ET litterär fostran, litteraturpedagogik
