### ISSUE TITLE
sisäistekijä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5048]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sisäistekijä 

#### Ehdotettu termi englanniksi   

implied author 

#### Ehdotettu termi ruotsiksi   

implicit författare 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Tekstistä abstrahoitava hypoteettinen tekijähahmo, teoskohtainen "kirjailijapersoona"; teoksen normisto ja ylin auktoriteetti, jonka arvomaailma vallitsee teosta. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esimerkiksi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [sisäistekijä](http://finto.fi/yse/fi/page/Y505048)

**Comment by mirmaid** [comment]
4 kertaa Melindassa, 2 kertaa Artossa.

**Comment by mariaforsen** [comment]
Sv. implicit författare ok

**Comment by AuHo22** [comment]
KT implisiittinen tekijä - vai päinvastoin

**Comment by OutiHintikka** [comment]
KT implisiittinen t., mikäli valitaan suom. muoto. Kirjallisuudentutkimuksessa käytetään kansainvälistä muotoa.

**Comment by YSA-kokous** [comment]
sisäistekijä KT implisiittinen tekijä

**Comment by mariaforsen** [comment]
Sv. implicit författare

**Comment by OutiHintikka** [comment]
onko toisaan implisiittinen kirjoittaja ruotsiksi implicit författare


kirj,tutkimuksessa kirjan kirjoittaja/kirjailija/författare ei ole sama asia, kuin implisiittinen kirjoittaja.

/outi h


________________________________
Lähettäjä: mariaforsen <notifications@github.com>
Lähetetty: 19. toukokuuta 2017 14:31
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] sisäistekijä (#5048)


Sv. implicit författare

**Comment by mariaforsen** [comment]
Kyllä, sisäistekijä/implied author= implicit författare. Lisää tietoa esim.: https://uu.diva-portal.org/smash/get/diva2:784950/FULLTEXT01.pdf
