### ISSUE TITLE
häkkilinnut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5049]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[häkkilinnut](http://www.yso.fi/onto/ysa/Y101755) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lemmikkilinnut 

#### Perustelut ehdotukselle   

Nykyajattelun mukaan lemmikkilintuja pidetään mahdollisimman vähän häkeissä, siksi "häkkilintu" on hyvin vanhahtava käsite ja sana. Lemmikkilintu olisi sopivampi ja nykyaikaisempi termi. 

#### Ehdottaja   

Anu Hytönen 

#### Ehdottajan sähköpostiosoite   

anu.hytonen@ruovesi.fi

**Comment by mariaforsen** [comment]
Sv. burfåglar > sällskapsfåglar
