### ISSUE TITLE
sisäislukija

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5050]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sisäislukija 

#### Ehdotettu termi englanniksi   

implied reader 

#### Ehdotettu termi ruotsiksi   

implicit läsare 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Tekstistä abstrahoitavissa oleva hypoteettinen lukijahahmo, vastaanottaja, jolle sisäistekijän tulkitaan osoittavan kertomuksensa.
 (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esimerkiksi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [sisäislukija](http://finto.fi/yse/fi/page/Y505050)

**Comment by mirmaid** [comment]
Kerran Melindassa, ei Artossa

**Comment by mariaforsen** [comment]
Entä implisiittinen lukija (ks. TEPA, Tieteen termipankkin jne.) onko KT?
Sv. implicit läsare ok.

**Comment by YSA-kokous** [comment]
sisäislukija KT implisiittinen lukija

**Comment by mariaforsen** [comment]
Sv. implicit läsare
