### ISSUE TITLE
sosiologinen kirjallisuudentutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5051]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sosiologinen kirjallisuudentutkimus 

#### Ehdotettu termi englanniksi   

sociological methods 

#### Ehdotettu termi ruotsiksi   

sociologisk litteraturforskning 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p1066) 

#### Tarkoitusta täsmentävä selite   

Sanataiteen suhdetta ympäröivään yhteiskuntaan tarkasteleva tutkimussuuntaus. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esimerkiksi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [sosiologinen kirjallisuudentutkimus](http://finto.fi/yse/fi/page/Y505051)

**Comment by mirmaid** [comment]
YSAssa on _kirjallisuussosiologia_.

http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:sosiologinen_kirjallisuudentutkimus: Tutkimussuuntaus, jossa yhteiskuntatieteitä hyödyntäen tarkastellaan kirjallisuuden suhdetta ympäröivään yhteiskuntaan. Käsitteitä kirjallisuussosiologia ja sosiologinen kirjallisuudentutkimus käytetään yleensä jokseenkin synonyymisesti, mutta ensin mainittuun verrattuna sosiologinen kirjallisuudentutkimus on teoskeskeisempää, kun taas kirjallisuussosiologia keskittyy kirjallisuuteen instituutiona.

**Comment by mirmaid** [comment]
Kerran Melindassa, 16 kertaa Artossa.

**Comment by mariaforsen** [comment]
Sv. sociologisk litteraturforskning ok

**Comment by OutiHintikka** [comment]
Poikkitieteellinen tutkimussuunta.  Ehkä termi on ok.

**Comment by mirmaid** [comment]
Mietin vaan tuota Tieteen termipankin tekstiä: _käsitteitä kirjallisuussosiologia ja sosiologinen kirjallisuudentutkimus käytetään yleensä jokseenkin synonyymisesti_

**Comment by OutiHintikka** [comment]
Sitten otetaan, jos otetaan,  se termi, mikä on vakiintunut kansainväliseen käyttöön. Kirjallisuussosiologia on ollut - mielestäni - pitkään aika passé.  Miellän käytön lähelle reseptiotutkimusta tai aatehistoriallista kirj. tutkimusta.


/outi


________________________________
Lähettäjä: mirmaid <notifications@github.com>
Lähetetty: 15. toukokuuta 2017 16:19
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] sosiologinen kirjallisuudentutkimus (#5051)


Mietin vaan tuota Tieteen termipankin tekstiä: käsitteitä kirjallisuussosiologia ja sosiologinen kirjallisuudentutkimus käytetään yleensä jokseenkin synonyymisesti

**Comment by YSA-kokous** [comment]
KÄ kirjallisuussosiologia

**Comment by mariaforsen** [comment]
Sv. sociologisk litteraturforskning ANV litteratursociologi

**Comment by OutiHintikka** [comment]
litteratursociologi on parempi muoto.


/outi


________________________________
Lähettäjä: mariaforsen <notifications@github.com>
Lähetetty: 19. toukokuuta 2017 14:26
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] sosiologinen kirjallisuudentutkimus (#5051)


sociologisk litteraturforskning ANV litteratursociologi

**Comment by mariaforsen** [comment]
ANV on siis lyhenne sanasta ANVÄND, tarkoitus on nimenomaan se että litteratursociologi käytetään pääterminä ja sociologisk litteraturforskning on "ET" (ersatt term) eli suomeksi KT (korvattu termi). Nämä Sv.-kommentit ovat muutenkin lähinnä Allärs-ryhmän työskentelyä varten, eli näihin ei tarvitse ottaa kantaa (näissä käytetään siis ruotsin kieltä sen takia kun ovat Allärs-ryhmää varten, ja jos nämä koetaan häiritseviksi voin myös poistaa niitä Allärs-kokouksen jälkeen).
