### ISSUE TITLE
takauma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5052]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

takauma 

#### Ehdotettu termi englanniksi   

KITO: flashback, Hosiaisluoma: flashback, recalls, retrospection, cutback, analepsis 

#### Ehdotettu termi ruotsiksi   

återblick 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakenne](http://www.yso.fi/onto/yso/p7302) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Kerronnan siirtyminen esim. romaanissa tai elokuvassa aiempiin tapahtumiin; retrospektio; analepsis. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto-luetteloinnissa, esimerkiksi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [takauma](http://finto.fi/yse/fi/page/Y505052)

**Comment by mirmaid** [comment]
Kaunokissa monikossa. Ei yksikössä Melindassa (monikossa runsaasti Kaunokki-terminä).

**Comment by mariaforsen** [comment]
Sv. återblickar ET tillbakablickar

**Comment by YSA-kokous** [comment]
Hyväksytään monikossa.
