### ISSUE TITLE
metsäteollisuustuotteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5053]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsäteollisuustuotteet 

#### Ehdotettu termi englanniksi   

forest industry products (Metsäteollisuus ry, https://www.forestindustries.fi/statistics/industry/10-Forest%20Industry/ 

#### Ehdotettu yläkäsite YSOssa (LT)   

[metsäntuotteet](http://www.yso.fi/onto/yso/p17527) 

#### Assosiatiiviset (RT)   

[sellu](http://www.yso.fi/onto/yso/p6396) 
[paperi](http://www.yso.fi/onto/yso/p8522) 
[puulevyt](http://www.yso.fi/onto/yso/p6618) 
[sahatavara](http://www.yso.fi/onto/yso/p1742) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[28 Metsäteollisuus. Massa- ja paperiteollisuus. Paperiteollisuus. Puuteollisuus](http://www.yso.fi/onto/yso/p26585) 

#### Perustelut ehdotukselle   

AFOssa, käytetty paljon, tilastotermi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arro 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [metsäteollisuustuotteet](http://finto.fi/yse/fi/page/Y505053)

**Comment by mariaforsen** [comment]
Sv. skogsindustriprodukter

**Comment by AuHo22** [comment]
RT puutuotteet (voivat olla sekä teollisuutta että käsityöläistuotantoa?)
