### ISSUE TITLE
epiteksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5054]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

epiteksti 

#### Ehdotettu termi englanniksi   

epitext 

#### Tarkoitusta täsmentävä selite   

Esimerkiksi luonnokset, käsikirjoitukset, teokseen liittyvät kirjeet, haastattelut ja arvostelut. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [epiteksti](http://finto.fi/yse/fi/page/Y505054)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5060

**Comment by krinay** [comment]
Tekstuaalitieteiden sanasto: 
Epiteksti - Sellainen parateksti, joka ei ole fyysisesti teoksen tietyn laitoksen yhteydessä, vaan liittyy siihen välillisemmin. Esimerkiksi päiväkirjamerkinnät, teokseen liittyvät haastattelut, mainokset, kirja-arviot ja niin edelleen.

Termiä epiteksti ei ole käytetty Melindassa eikä Artossa. Riittäisikö YSAn termi parateksti?

**Comment by mariaforsen** [comment]
Sv. epitext ok.

**Comment by OutiHintikka** [comment]
onko parateksti ja epiteksti sama asia?

**Comment by krinay** [comment]
Tekstuaalitieteiden sanaston (http://tekstuaalitieteidensanasto.finlit.fi:8080/search) mukaan parateksti on laajempi käsite kuin epiteksti. Parateksti voi olla periteksti tai epiteksti.

Parateksti on
"Kirjallisuudentutkija Gérard Genetten luoma käsite tekstille, joka määrittelee tai kommentoi teoksen lukutekstiä tai ohjaa sen vastaanottoa."

Epiteksti on 
"Sellainen parateksti, joka ei ole fyysisesti teoksen tietyn laitoksen yhteydessä, vaan liittyy siihen välillisemmin. Esimerkiksi päiväkirjamerkinnät, teokseen liittyvät haastattelut, mainokset, kirja-arviot ja niin edelleen."

Periteksti on
"Sellainen parateksti, joka on fyysisesti laitoksen lukutekstin yhteydessä. Esimerkiksi teoksen otsikko, teokseen painettu kirjailijan nimi, esipuhe, omisteet, viitteet, jälkisanat ja niin edelleen."

**Comment by OutiHintikka** [comment]
Jotenkin näin olen tämän mieltänyt; en vain ehtinyt tutkia.


________________________________
Lähettäjä: krinay <notifications@github.com>
Lähetetty: 16. toukokuuta 2017 14:48
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] epiteksti (#5054)


Tekstuaalitieteiden sanaston (http://tekstuaalitieteidensanasto.finlit.fi:8080/search) mukaan parateksti on laajempi käsite kuin epiteksti. Parateksti voi olla periteksti tai epiteksti.

Haku - Tekstuaalitieteiden sanasto<http://tekstuaalitieteidensanasto.finlit.fi:8080/search>
tekstuaalitieteidensanasto.finlit.fi
Hae myös määritelmäteksteistä. Näytä myös vieraskieliset. Edith – suomalaisen kirjallisuuden kriittiset editiot



Parateksti on
"Kirjallisuudentutkija Gérard Genetten luoma käsite tekstille, joka määrittelee tai kommentoi teoksen lukutekstiä tai ohjaa sen vastaanottoa."

Epiteksti on
"Sellainen parateksti, joka ei ole fyysisesti teoksen tietyn laitoksen yhteydessä, vaan liittyy siihen välillisemmin. Esimerkiksi päiväkirjamerkinnät, teokseen liittyvät haastattelut, mainokset, kirja-arviot ja niin edelleen."

Periteksti on
"Sellainen parateksti, joka on fyysisesti laitoksen lukutekstin yhteydessä. Esimerkiksi teoksen otsikko, teokseen painettu kirjailijan nimi, esipuhe, omisteet, viitteet, jälkisanat ja niin edelleen."
