### ISSUE TITLE
alaluokka, junttius, juntit, sivistymöttömyys/-mät, kouluttamattomuus/-mat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5055]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alaluokka, junttius, juntit, sivistymöttömyys/-mät, kouluttamattomuus/-mat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Juntti! :roskaväen historia 

#### Perustelut ehdotukselle   

Yhteiskuntaluokat jne. jättävät em. ilmiön vähän epämääräiseksi. 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [alaluokka, junttius, juntit, sivistymöttömyys/-mät, kouluttamattomuus/-mat](http://finto.fi/yse/fi/page/Y505055)

**Comment by mirmaid** [comment]
Melindassa kerran _alaluokka_.

**Comment by mariaforsen** [comment]
Sv. alaluokka=underklass ok. 
Juntit/junttius EI ok ruotsin osalta. 
Sivistymättömyys=obildning, sivistymättömät=obildade. 
Kouluttamattomus melko mahdotonta kääntää, kouluttamattomat=outbildade ok.

**Comment by AuHo22** [comment]
Sivistymättömyys voisi olla käyttökelpoinen termi? Kuvaa asennoitumista elämään. Vrt. voi olla ilman oppiarvoja mutta hyvin kasvatettu;  alaluokka pakenee nykypäivää - yläluokka -termiä usein tulee käytettyä historiallisemmissa yhteyksissä. Muut sanat korvanneet - eliitit, syrjäytyneet, työttömät, ja voivat olla  tilannesidonnaisia.

**Comment by Elmukelmu** [comment]
Tavallaan hassua, että YSAssa on yläluokka ja yläluokan kulttuuri, mutta ei mitään alaluokasta.

**Comment by mirmaid** [comment]
ylhäinen suomalainen asiasanasto :sunglasses:

Tässä ehkä _sivistymättömyys_ kuitenkin lähempänä haettua kuin _alaluokka_? On myös Kaunokissa, vaikka ei löydykään Melindasta.

**Comment by YSA-kokous** [comment]
Otetaan sivistymättömyys.

**Comment by mariaforsen** [comment]
Sv. obildning ET okultur
