### ISSUE TITLE
esinerunot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5056]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

esinerunot 

#### Ehdotettu termi englanniksi   

object poems 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runot](http://www.yso.fi/onto/yso/p24644) 

#### Assosiatiiviset (RT)   

[arkkiveisut](http://www.yso.fi/onto/yso/p1364) 
[balladit](http://www.yso.fi/onto/yso/p15007) 
[elegiat](http://www.yso.fi/onto/yso/p10201) 
[eläinrunot](http://www.yso.fi/onto/yso/p15329) 
[epigrammit](http://www.yso.fi/onto/yso/p14374) 

#### Tarkoitusta täsmentävä selite   

Esinerunossa pyritään kuvaamaan ja vangitsemaan mahdollisimman tarkasti jonkun ulkomaailman objektin olemus. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [esinerunot](http://finto.fi/yse/fi/page/Y505056)

**Comment by mirmaid** [comment]
http://penandthepad.com/write-object-poem-5085351.html

Ei Melindassa, kerran Artossa.

**Comment by mirmaid** [comment]
Kirjallisuuden sanakirja: _dinggedicht_

https://en.wikipedia.org/wiki/Dinggedicht

**Comment by mariaforsen** [comment]
Sv. sakdikter
