### ISSUE TITLE
anapesti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5057]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

anapesti 

#### Ehdotettu termi ruotsiksi   

anapest 

#### Ehdotettu termi englanniksi   

anapest 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Anapesti on luistava, jopa laukkaavaksi luonnehdittu runojalka. Sitä onkin usein käytetty runoissa, joissa pyritään luomaan vaikutelma nopeasta, dramaattisesta toiminnasta. (Termipankki) 

#### Perustelut ehdotukselle   

KITOn sana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [anapesti](http://finto.fi/yse/fi/page/Y505057)

**Comment by jtuohini** [comment]
Täsmällisempi selitys termille löytyisi vaikkapa suomenkielisestä Wikisanakirjasta: "runojalka, joka koostuu kahdesta lyhyestä ja yhdestä pitkästä (painollisesta) tavusta ( ⌣ ⌣ ─ )" (https://fi.wiktionary.org/wiki/anapesti). Nyt esitetty on ihan kivaa lisätietoa, mutta ei sellaisenaan riitä yksilöimään kyseistä runojalkaa.

**Comment by mirmaid** [comment]
Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. anapest
