### ISSUE TITLE
baškiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5058]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

baškiirit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansat (väestöryhmät)](http://www.yso.fi/onto/yso/p3993) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

YSA:ssa on jo termit baškiirin kieli, baškiirinkielinen kirjallisuus ja Baškiria. Melindasta löytyy 69 viitettä asiasanahaulla "baškiirit". 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

nimeke "Baškiry" https://finna.fi/Record/helka.2925954 

**Ehdottajan nimi:** Marina Ivanova 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** marina.ivanova@helsinki.fi **Termiehdotus Fintossa:** [baškiirit](http://finto.fi/yse/fi/page/Y505058)

**Comment by jtuohini** [comment]
LCSH-vastine: "Bashkir (Turkic people)"

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5225

**Comment by mariaforsen** [comment]
Sv. basjkirer
