### ISSUE TITLE
daktyyli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5059]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

daktyyli 

#### Ehdotettu termi ruotsiksi   

daktyl 

#### Ehdotettu termi englanniksi   

dactyl 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Tarkoitusta täsmentävä selite   

Kolmitavuinen aleneva runojalka, joka muodostuu yhdestä painollisesta (antiikin runojaloissa pitkästä) ja sitä seuraavista kahdesta painottomasta (antiikin runojaloissa lyhyestä) tavusta.  (Tieteen termipankki) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [daktyyli](http://finto.fi/yse/fi/page/Y505059)

**Comment by mirmaid** [comment]
Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. daktyl
