### ISSUE TITLE
epiteksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5060]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

epiteksti 

#### Ehdotettu termi ruotsiksi   

epitext 

#### Ehdotettu termi englanniksi   

epitext 

#### Tarkoitusta täsmentävä selite   

Esimerkiksi luonnokset, käsikirjoitukset, teokseen liittyvät kirjeet, haastattelut ja arvostelut. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [epiteksti](http://finto.fi/yse/fi/page/Y505060)

**Comment by mirmaid** [comment]
Ei Melindassa/Artossa. YSAan otettiin parateksti, ovatko nämä tarkemmat lajittelut tarpeellisia? Käyttö tuntuu melko vähäiseltä. Sinänsä toki ovat määriteltävissä ja sikäli ok.

**Comment by mariaforsen** [comment]
Sv. epitext
