### ISSUE TITLE
diegesis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5061]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

diegesis 

#### Ehdotettu termi ruotsiksi   

diegesis 

#### Ehdotettu termi englanniksi   

diegesis 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kerronta](http://www.yso.fi/onto/yso/p6895) 

#### Tarkoitusta täsmentävä selite   

1) puheen epäsuora esittäminen; 2) kertominen näyttämisen vastakohtana; 3) narratologiassa tarinan eli kerrottujen tapahtumien taso 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITON termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [diegesis](http://finto.fi/yse/fi/page/Y505061)

**Comment by mirmaid** [comment]
3 kertaa Melindassa:

_From Plato to Lumière : narration and monstration in literature and cinema_

_Die Auffassung des Lesers von erzählten Gesprächen in einem narrativen Text : das Beispiel Martin Walsers "Ein fliehendes Pferd"_

_Romanens formvärld : studier i prosaberättarens teknik_

Kerran Artossa:

_Kun näyttelijä katsoo silmiin._

http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:diegesis

**Comment by mirmaid** [comment]
YSAssa on _mimesis_.

**Comment by mariaforsen** [comment]
Sv. diegesis ET dieges

**Comment by OutiHintikka** [comment]
Onko liian eksakti termi; toisaalta asiaa on muuten vaikea täsmällisesti ilmaista.
