### ISSUE TITLE
travestia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5062]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

travestia 

#### Ehdotettu termi ruotsiksi   

travesti 

#### Ehdotettu termi englanniksi   

travesty 

#### Ehdotettu yläkäsite YSOssa (LT)   

[komediat](http://www.yso.fi/onto/yso/p13876) 

#### Assosiatiiviset (RT)   

[burleski](http://www.yso.fi/onto/yso/p23820) 
[parodia](http://www.yso.fi/onto/yso/p9240) 

#### Tarkoitusta täsmentävä selite   

Parodian sukuinen ivamukaelma. (Hosiaisluoma) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [travestia](http://finto.fi/yse/fi/page/Y505062)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mirmaid** [comment]
LCSH > burleski, parodia

**Comment by mariaforsen** [comment]
Sv. travesti ok.

**Comment by YSA-kokous** [comment]
KÄ burleski, parodia

**Comment by mariaforsen** [comment]
Sv. travesti ANV burlesk, parodi
