### ISSUE TITLE
konservatiivinen hoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5063]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

konservatiivinen hoito 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Vastakohta leikkaushoidolle 

#### Perustelut ehdotukselle   

Duodecim-lehden artikkeleissa olen useaan kertaan kaivannut vastinparia leikkaushoito - konservatiivinen hoito. Artikkeleissa pohdiskellaan tutkimustulosten valossa, onko parempi leikata vai valita hoitolinjaksi konservatiivinen hoito. Kun asiasanoituksessa on vain "leikkaushoito" eikä konservatiivista hoitoa, voi asiakas saada käsityksen, että artikkeli käsittelee leikkaushoitoa. Huomautuskenttään (500) olen laittanut konservatiivinen hoito 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä, Duodecim yms. lääketiet. julkaisut 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [konservatiivinen hoito](http://finto.fi/yse/fi/page/Y505063)

**Comment by mirmaid** [comment]
Lääketieteen termit: säästävillä menetelmillä annettu hoito, usein muu kuin leikkaushoito

Myös **konservatiivinen leikkaus**: 1. kasvainleikkaus jossa kasvaimen lisäksi poistetaan mahdollisimman vähän muuta kudosta (erityisesti nisän osittaispoisto rintasyövässä); vrt. radikaalileikkaus (1); 2. muu tervettä kudosta mahdollisimman paljon säästävä leikkaus, esim. amputaatio; 3. mahdollisimman pientä leikkaushaavaa käyttävä endoskooppinen leikkaus

**kajoamaton hoito**: ei-operatiivinen hoito | hoito jossa ei läpäistä ihoa eikä limakalvoa, muu kuin leikkaushoito

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mariaforsen** [comment]
Sv. konservativ behandling
