### ISSUE TITLE
home- ja kosteusvauriosairaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5064]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

home- ja kosteusvauriosairaus 

#### Vaihtoehtoiset termit ja ilmaisut   

home- ja kosteusvauriosairaudet, ympäristöherkkyys 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Diagnoosinumero R68.81 

#### Perustelut ehdotukselle   

Diagnoosi "home- ja kosteusvauriosairaus" on jo käytössä ja aiheesta ilmestyy jatkuvasti artikkeleita. Asiasanoitus on kömpelöä. Vaihtoehtoisesti voisi ottaa käyttöön käsitteen ympäristöherkkyys, mutta sen ongelmana on se, ettei käsitettä useinkaan esiinny indeksoitavassa aineistossa, joten luetteloija tai tietoa etsivä asiakas ehkä eivät osaa tuolla termillä hakea. Sen sijaan home- ja kosteusvauriot -käsite on jo tavanomainen. Luultavasti "home- ja kosteusvauriosairaudet" tai "home- ja kosteusvauriosairaus" ei kuitenkaan osasta lääkäriammattilaisten mielestä olisi "oikeaoppinen", koska lääkärikunta on asiassa kahtiajakautunut. Termipoliittisesti ympäristöherkkyys olisi sikäli parempi, vaikkakin vaikeakäyttöisemp. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

lääketiede, terveys, potilaskokemus 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [home- ja kosteusvauriosairaus](http://finto.fi/yse/fi/page/Y505064)

**Comment by mirmaid** [comment]
YSAssa on _sairas rakennus -oireyhtymä_.

**Comment by mirmaid** [comment]
Ei kumpaakaan (home- ja kosteusvauriosairaudet, ympäristöherkkyys) Melindassa.

**Comment by mariaforsen** [comment]
Englanniksi? Ruotsinnos epäselvä. Ks. https://www.thl.fi/sv/-/ymparistoyliherkkyyden-nimike-on-lisatty-icd-10-tautiluokitukseen Eli diagnoosinumero R68.81 ei kai ole virallisesti home- ja kosteusvauriosairaus-niminen ja diagnoosi voi viitata muuhunkin kuin pelkästään home- ja kosteusvaurioihin. 

"Ympäristöherkkyys on lisätty suomalaiseen ICD-10-tautiluokitukseen nimikkeellä R68.81: Jatkuva tai toistuva poikkeuksellinen herkkyys ympäristön tavanomaisille tekijöille. 

Ympäristöherkkyydeksi kutsutaan tilaa, jossa ihminen saa terveyttä haittaavia oireita tietyssä työ- tai elinympäristössä, vaikka sama ympäristö ei aiheuta oireita valtaosalle muita ihmisiä. Oireet yhdistetään mm. erilaisiin kemikaaleihin, hajusteisiin, mikrobiologisiin tekijöihin sekä sähkömagneettisiin kenttiin."

TEPA:
ympäristöyliherkkyys
en  environmental hypersensitivity

Tälle termille löytyy myös ruotsink. vastine: miljökänslighet, miljööverkänslighet, joka olisi hyvä. 

Ympäristöherkkyys http://www.kaypahoito.fi/web/kh/suositukset/suositus?id=nix02353

**Comment by ilona-x** [comment]
http://stm.fi/ymparistoherkkyydet

ympäristöherkkyys -termille saisi alakäsitteiksi:

sähköherkkyys http://finto.fi/ysa/fi/page/Y188853
monikemikaaliyliherkkyys http://finto.fi/ysa/fi/page/Y504529

**Comment by tpusa** [comment]
Entä yksinkertaisesti "homesairaudet"?

**Comment by YSA-kokous** [comment]
Otetaan ympäristöherkkyys. Home- ja kosteusvauriosairaudet, homesairaudet KÄ sairas rakennus -oireyhtymä.

**Comment by mariaforsen** [comment]
Sv. miljökänslighet ET miljööverkänslighet
