### ISSUE TITLE
laumanvartijakoirat

### ISSUE THREAD

**Issue by Elmukelmu** [Finto-ehdotus/YSE#5065]
Laumanvartijarotuiset koirat. Tähän mennessä on tullut paremman puutteessa indeksoitua YSA-sanalla paimenkoirat, vaikka eihän näitä paimennukseen käytetäkään. 

https://fi.wikipedia.org/wiki/Laumanvartija

**Comment by ilona-x** [comment]
LCSH: Livestock protection dogs
http://id.loc.gov/authorities/subjects/sh90002554.html

**Comment by mariaforsen** [comment]
Sv. boskapsvaktande hundar ET boskapsvaktare
