### ISSUE TITLE
fastighetsförvärv

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5066]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

fastighetsförvärv 

#### Perustelut ehdotukselle   

alla förvärv av fastigheter är inte köp 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fel i fastighet /Jan Elfström, Lars Erik Ashton ;  Bib.id: 010320737 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

**Ehdottajan nimi:** Disa Svenskberg 
**Ehdottajan organisaatio:** ÅAB 
**Ehdottajan sähköpostiosoite:** disa.svenskberg@abo.fi **Termiehdotus Fintossa:** [fastighetsförvärv](http://finto.fi/yse/fi/page/Y505066)

**Comment by mirmaid** [comment]
Kiinteistönsaanto. Melindassa 3 kertaa kiinteistöt -- saanto. Ei EKS:ssa.

**Comment by mariaforsen** [comment]
Lainsäädännössä myös muodossa "kiinteistön saanto", ks. http://www.finlex.fi/fi/laki/ajantasa/1995/19950540
Allärs fång=saanto.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa kiinteistön saanto.

**Comment by ilona-x** [comment]
Ämnesordssystem	 	SAO
Ämnesord	 	 	**Fastighetsförvärv**
Anmärkning	 	 	Tidigare även Fastighetsköp. Ändrat 2002-04.
Används ej	 	 	**Fastighetsköp**
                                         Jordförvärv
Överordnad term	 	 Fastighetsekonomi 
Fastighetsmarknaden 
Underordnad term	 	 Husköp 

YSAssa kiinteistönkauppa = **fastighetsköp**

MOT Ruotsi Pro förvärv = hankinta, osto
MOT Ruotsi förvärv s = hankinta, hankkiminen, kertyminen, saaminen, saanti (saaminen), saanto oik

**Comment by mariaforsen** [comment]
Sv. fastighetsförvärv

**Comment by YSA-kokous** [comment]
ok
