### ISSUE TITLE
kanavat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5067]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kanavat](http://www.yso.fi/onto/ysa/Y95803) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Alakäsitteet ja RT ovat MOTin "liikennettä t. veden johtamista varten tehty vesiväylä t. -uoma" merkityksessä, mutta Melindassa käytetty myös muisssa merkityksissä, esim. Promoting culture exchange programs to USA through personal communication channels / Emilia Hämäläinen ; Viestintäkanavien käyttö ja tiedonsaanti kansainvälisessä organisaatiossa : case: Metso Drives / Tiina Niemi ; Ilmanvaihtotuotteiden likaantuvuuden testauslaitteiston kehittäminen / Riina Alén. Eli myös MOTin merkitykset: 2. sola, käytävä, putki tms. ja 4. tie, keino, väline. 

#### Ehdotettu muutos   

Onko tarpeen rajata tai jakaa? 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Lisätään tarkenne kanavat (vesiväylät), korjataan viitteet ja tutkitaan sen jälkeen jäljellejäävät.

**Comment by YSA-kokous** [comment]
Lisätään tarkenne kanavat (vesiväylät), korjataan viitteet ja tutkitaan sen jälkeen jäljellejäävät.

**Comment by ilona-x** [comment]
Korjattu Melindaan kanavat (vesiväylät). Jäljelle jäi n. 20 viitettä. Eniten viitteitä markkinointiin liittyen ja pari viitettä talotekniikasta/rakennustekniikasta.

**markkinointikanavat** LCSH Marketing channels http://id.loc.gov/authorities/subjects/sh85081347

Lisäksi yksittäisiä viitteitä eri aiheista:

- Viestintäkanavien käyttö ja tiedonsaanti kansainvälisessä organisaatiossa
- Suoratuonti elintarvikeraaka-aineen hankintakanavana Suomen EU-jäsenyydessä
- Peroxisomal channels :the biological role of Pxmp2 protein in mouse and channel-forming activities of the glycosomal membrane from Trypanosoma brucei 
- Kanavan lisääminen ohjelmalla säädettävään kaistanpäästösuodattimeen 
- Tietoliikenteen tekniikka 
- EFR-puheen kanavakoodaus GSM-tukiasemassa

**Comment by ilona-x** [comment]
markkinointikanavat käytetty Melindassa 22 kertaa

**Comment by ilona-x** [comment]
termiehdotuksissa:
markkinointikanavat https://github.com/Finto-ehdotus/YSE/issues/1458
viestintäkanavat https://github.com/Finto-ehdotus/YSE/issues/4008
tiedonsiirtokanavat https://github.com/Finto-ehdotus/YSE/issues/2471

**Comment by mirmaid** [comment]
Otetaan _markkinointikanavat_, tutkitaan loput yksitellen.
