### ISSUE TITLE
punk rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5068]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

punk rock 

#### Ehdotettu termi ruotsiksi   

punkrock 

#### Ehdotettu termi englanniksi   

punk rock 

#### Ehdotettu yläkäsite YSOssa (LT)   

[punk](http://www.yso.fi/onto/yso/p5229) 
[rock](http://www.yso.fi/onto/yso/p1882) 

#### exactMatch   

punk rock : https://en.wikipedia.org/wiki/Punk_rock 
punk rock : https://finto.fi/musa/fi/page/p671 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

YSA:ssa termi punk, joka viittaa sekä sosiologiaan ja sosiaalipsykologiaan (60) että musiikkiin (89). Nämä on syytä erottaa toisistaan, ja se onnistuu parhaiten uudella musiikkiryhmän termillä punk rock. 

#### Tarkoitusta täsmentävä selite   

1970-luvun puolivälissä Iso-Britanniassa kehittynyt nuorison alakulttuurin suosima musiikkityyli. Punk rock oli rockin kaupallisuutta ja raskasta sovittamista vastaan noussut kapinaliike, joka ilmeni musiikissa sanoitusten suoraviivaisuutena ja kantaaottavuutena. Sävellykset ovat yleensä lyhyitä, nopeatempoisia, dynaamisesti tasaisia, 1-3 soinnulla soitettavia pienten yhtyeiden musiikkia. (MUSA) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Punk on kuollut, eläköön hardcore / [valokuvat:] Juha-Pekka Inkinen ; toimittanut Katriina Etholén 

**Ehdottajan nimi:** Tommi Viitamies 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto / Helmet 
**Ehdottajan sähköpostiosoite:** tommi.viitamies@hel.fi **Termiehdotus Fintossa:** [punk rock](http://finto.fi/yse/fi/page/Y505068)

**Comment by mariaforsen** [comment]
Sv. punkrock ok.

**Comment by ksornova** [comment]
Exact Match

Punk rock music
http://id.loc.gov/authorities/subjects/sh85109128
LT-suhteet
Alternative rock music
Punk culture

**Comment by ksornova** [comment]
samalla voisi käsitellä punkkia kulttuuri-ilmiönä:
Exact match
Punk culture
http://id.loc.gov/authorities/subjects/sh85109126

YSAssa olevaa termiä _punk_ pitäisi muokata tässä yhteydessä (http://finto.fi/ysa/fi/page/Y107653). Olisiko se sitten _punk (kulttuuri)_ vai _punk-kulttuuri_?

@mirmaid pitääkö tästä mahdollisesta muutoksesta tehdä oma issue? olisiko tosiaan järkevää käsitellä nuo samaan aikaan?

**Comment by ksornova** [comment]
Musan **määritelmä**: 1970-luvun puolivälissä Iso-Britanniassa kehittynyt nuorison alakulttuurin suosima musiikkityyli. Punk rock oli rockin kaupallisuutta ja raskasta sovittamista vastaan noussut kapinaliike, joka ilmeni musiikissa sanoitusten suoraviivaisuutena ja kantaaottavuutena. Sävellykset ovat yleensä lyhyitä, nopeatempoisia, dynaamisesti tasaisia, 1-3 soinnulla soitettavia pienten yhtyeiden musiikkia.

**Käyttöön liittyvä huomautus** lienee syytä muokata: Koska tyyli tuli uudestaan suosituksi 1990-luvulla, termin yhteydessä on aina käytettävä ajallista määrettä, esim. punk rock : Suomi : 1970-luku.

@mirmaid voihan ainakin määritelmän siirtää tässä yhteydessä ysaan?

**Comment by TommiViitamies** [comment]
_YSAssa olevaa termiä punk pitäisi muokata tässä yhteydessä (http://finto.fi/ysa/fi/page/Y107653). Olisiko se sitten punk (kulttuuri) vai punk-kulttuuri?

@mirmaid pitääkö tästä mahdollisesta muutoksesta tehdä oma issue? olisiko tosiaan järkevää käsitellä nuo samaan aikaan?_

Ehdotuksessani oli oletuksena, että "punk" säilyisi sellaisenaan kuvaamassa ilmiötä yleisesti (ryhmä 60). Jos se täsmennetään esim. muotoon "punk (kulttuuri)", rajoittaako se termin käyttöä sellaisissa yhteyksissä, jossa käsitellään punkia esim. vaatetuksessa/muodissa, tai missä tahansa muussa yhteydessä (kuten steam punk)?

**Comment by mirmaid** [comment]
Voidaan käsitellä molemmat tässä issuessa.

**Comment by YSA-kokous** [comment]
Otetaan punk rock ja punk (kulttuuri).

**Comment by mariaforsen** [comment]
Sv. 
-punkrock
-punk (kultur)
