### ISSUE TITLE
Phillipsin käyrä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5069]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Phillipsin käyrä 

#### Ehdotettu termi englanniksi   

Phillips curve 

#### exactMatch   

lcsh : Phillips curve 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Tarkoitusta täsmentävä selite   

"Käyrä, joka osoittaa työttömyysasteen ja inflaation välisen yhteyden"

lähde: http://tieteentermipankki.fi/wiki/Taloustiede:Phillipsin_k%C3%A4yr%C3%A4 

#### Perustelut ehdotukselle   

Tarve käyttää sis.kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uef.finna.fi/Record/josku.1158102 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [Phillipsin käyrä](http://finto.fi/yse/fi/page/Y505069)

**Comment by mirmaid** [comment]
3 kertaa Melindassa

**Comment by mirmaid** [comment]
Phillipsin käyrä on Alban William Phillipsin (1914–1975) vuonna 1958 esittelemä teoria, jonka mukaan työttömyys vaikuttaa inflaatioon käänteisesti. Toisin sanoen, korkean työttömyyden aikana inflaatio on matalaa ja täystyöllisyyttä kohti siirryttäessä inflaatio suurenee. 1970-luvulla stagflaatio sai ekonomistit, erityisesti Milton Friedmanin, kritisoimaan Phillipsin käyrää. Nykyään useimmat tutkijat eivät usko, että työttömyyden ja inflaation välillä olisi helposti selitettävä suhde ainakaan perinteisen Phillipsin käyrän muodossa. https://fi.wikipedia.org/wiki/Phillipsin_k%C3%A4yr%C3%A4

**Comment by mariaforsen** [comment]
Sv. Phillipskurvan
