### ISSUE TITLE
taloudenhoitajat (kodinhoito)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5070]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taloudenhoitajat (kodinhoito)](http://www.yso.fi/onto/ysa/Y133051) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään selitys tekemään selkeä ero termiin "kodinhoitajat" nähden samoin kuin lisätään RT-suhde mainittuun tai yhdistetään termit, jos ne tarkoittavat samaa asiaa. 

#### Perustelut ehdotukselle   

Tällä hetkellä "kodinhoitajat" ja "taloudenhoitajat (kodinhoito)" vaikuttaa ensisilmäyksellä tarkoittavan samaa asiaa; ruotsinkielinen termi on eriävä eli "hemvårdare" ja "hushållerskor" – jälkimmäiselle ruotsinkielinen Wikipedia antaisi myös termin "husföreståndarinna" ja vanhahtavana "husmamsell", joita kumpaakaan ei ole Allärsissa KT-muotoina, mutta "hemvårdare" taas on vastaavasti Wikipedialle tuntematon käsite. Hyvin epäselvä tilanne siis. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
En osaa sanoa onko näiden välillä RT-suhdetta, kodinhoitaja on kotipalvelutoiminnan työntekijä, taloudenhoitaja taas oli aikanaan palveluskuntaan kuuluva henkilö. 

Kielitoimiston sanakirjan mukaan kodinhoitaja = kunnan työntekijä, joka hoitaa kodin taloustyöt sairaustapauksissa tms. - Ammattinetin mukaan "Kodinhoitaja työskentelee kunnan kotipalvelussa tai yksityisessä kotipalveluyksikössä."  

taloudenhoitoja (Kielitoimiston sanakirja): yksityisen henkilön, perheen tms. kotitaloutta palkattuna hoitava nainen, taloudenhoitajatar, emännöitsijä.

Näistä saanee määritelmät, jos tarpeen.

**Comment by satuniininen** [comment]
Pidetään erillään ja lisätään määritelmät.

**Comment by mariaforsen** [comment]
Hemvårdare on ruotsiksi ok ja merkitys oikea (se että Wikipedia ei tiedä ei tarkoita ainakaan ruotsin osalta ettei ole olemassa..) Husföreståndarinna voidaan lisätä (historiallisena) korvattuna terminä.

**Comment by mirmaid** [comment]
kodinhoitajat: _Kunnan kotipalvelussa tai yksityisessä kotipalveluyksikössä työskentelevä henkilö, joka hoitaa kodin taloustöitä esim. sairaustapauksissa._

taloudenhoitajat (kodinhoito): _Kotitaloutta palkattuna hoitava henkilö._ Tai ehkä paremmin: _Kotitalouden hoidosta vastaava palveluskunnan jäsen._
