### ISSUE TITLE
heksametri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5071]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heksametri 

#### Ehdotettu termi englanniksi   

hexameter 

#### Ehdotettu termi ruotsiksi   

hexameter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Kuuden runomitan muodostava säe. 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esimerkiksi Arto-luetteloinnissa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [heksametri](http://finto.fi/yse/fi/page/Y505071)

**Comment by mirmaid** [comment]
Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. hexameter
