### ISSUE TITLE
asiakirjamallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5072]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

asiakirjamallit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Perustelut ehdotukselle   

Pitkään käytetty kombinaatiota asiakirjat + mallit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. Sujuvasti seuraavalle : metsän omistajanvaihdos, jossa 11 liitettä erilaisia aiheeseen liittyviä asiakirjamalleja. Näitä tarvitaan paljon myös esimerkiksi perinnönjaossa ja perunkirjoituksessa ja kysytään kirjastoissa jatkuvasti. 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [asiakirjamallit](http://finto.fi/yse/fi/page/Y505072)

**Comment by mirmaid** [comment]
7 kertaa Melindassa, ketjua asiakirjat -- mallit käytetty 51 kertaa.

**Comment by mariaforsen** [comment]
Sv. dokumentmallar

**Comment by satuniininen** [comment]
Engl. document templates tai model documents
