### ISSUE TITLE
WHO- Koululaistutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5073]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

WHO- Koululaistutkimus 

#### Ehdotettu termi englanniksi   

Health Behaviour in School-aged Children (HBSC) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

WHO-Koululaistutkimus on Suomessa käytetty nimitys Maailman terveysjärjestön WHO:n kanssa yhteistyössä toteutettavasta kansainvälisestä Health Behaviour in School-aged Children (HBSC) -tutkimuksesta. Jo 30 vuotta jatkuneessa HBSC-tutkimuksessa tarkastellaan monipuolisesti koululaisten koettua terveyttä, hyvinvointia ja terveystottumuksia nuorten arkisissa sosiaalisissa ympäristöissä. Tutkimuksen aineistot kerätään neljän vuoden välein - viimeksi 2014. Tutkimukseen liittyviä julkaisuja on julkaistu paljon ja julkaistaan edelleen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ng Kwok: Physical activity of adolescents with long term illnesses or disabilities in reference to ICF personal factors. Jyväskylän yliopisto 2016. Diss. 

**Ehdottajan nimi:** Anitta Pälvimäki 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** anitta.palvimaki@jyu.fi **Termiehdotus Fintossa:** [WHO- Koululaistutkimus](http://finto.fi/yse/fi/page/Y505073)

**Comment by mirmaid** [comment]
LCSH:ssa tämä on yhteisö (?)

**Comment by mirmaid** [comment]
Kirjoitettu yleensä WHO-Koululaistutkimus > WHO-koululaistutkimus?

**Comment by mariaforsen** [comment]
Sv.  Skolbarns hälsovanor (undersökning) ET WHO-skolelevsundersökning

**Comment by AuHo22** [comment]
Itse olin juuri FinTerveys-tutkimuksessa -> WHO-koululaistutkimus
