### ISSUE TITLE
tasapainoharjoittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5074]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tasapainoharjoittelu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[harjoittelu](http://www.yso.fi/onto/yso/p26412) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

mm. ikääntymiseen, kuntoutukseen ja liikuntasuoritukseen liittyvä keskeinen käsite 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Aartolahti Eeva: Long-term strength and balance training prevents mobility decline among community-dwelling people aged 75 and older. Jyväskylän yliopisto 2016. Diss. 

**Ehdottajan nimi:** Anitta Pälvimäki 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** anitta.palvimaki@jyu.fi **Termiehdotus Fintossa:** [tasapainoharjoittelu](http://finto.fi/yse/fi/page/Y505074)

**Comment by mirmaid** [comment]
Ei Melindassa eikä Liikunnan ja urheilun asiasanastossa (muuten kyllä ihan kelpo termi)

**Comment by mariaforsen** [comment]
Sv. balansträning ET balansövning
