### ISSUE TITLE
lihasaktiivisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5075]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lihasaktiivisuus 

#### Ehdotettu termi englanniksi   

muscle activity 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

liikuntasuoritukseen ja mm. ajankohtaiseen liikkumattomuus-ongelman tarkasteluun liittyvä keskeinen käsite 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tikkanen Olli: Physiological loading during normal daily life and exercise assessed with electromyography. Jyväskylän yliopisto 2014. Diss 

**Ehdottajan nimi:** Anitta Pälvimäki 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** anitta.palvimaki@jyu.fi **Termiehdotus Fintossa:** [lihasaktiivisuus](http://finto.fi/yse/fi/page/Y505075)

**Comment by mirmaid** [comment]
12 kertaa Melindassa, Googlella n. 1000.

**Comment by mirmaid** [comment]
Ei LUAssa

**Comment by mariaforsen** [comment]
Sv. muskelaktivitet
