### ISSUE TITLE
eteläarabian kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5077]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

eteläarabian kieli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Itsenäinen kieli, meillä myös materiaalia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Seemiläiset kielet 

**Ehdottajan nimi:** Mikko Hakalin 
**Ehdottajan organisaatio:** Helsingin yliopisto, Kaisa-kirjasto 
**Ehdottajan sähköpostiosoite:** mikko.hakalin@helsinki.fi **Termiehdotus Fintossa:** [eteläarabian kieli](http://finto.fi/yse/fi/page/Y505077)

**Comment by jtuohini** [comment]
LCSH-vastine: South Arabic language

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Modern_South_Arabian_languages
https://en.wikipedia.org/wiki/Old_South_Arabian

**Comment by mariaforsen** [comment]
Sv. sydarabiska språk (on kielikunta). http://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/sydarabiska-spr%C3%A5k  SAOssa tosin on "sydarabiska språket", siitä ei kuitenkaan löydy osumia googlessakaan.

**Comment by YSA-kokous** [comment]
Kysytään ehdottajalta.

**Comment by mirmaid** [comment]
Ehkä mahdollinen olisi eteläarabialaiset kielet (KT nykyeteläarabialaiset kielet)

**Comment by mariaforsen** [comment]
Sv. sydarabiska språk
