### ISSUE TITLE
luonnon tasapaino

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5078]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luonnon tasapaino](http://www.yso.fi/onto/ysa/Y97006) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko "ekologinen tasapaino" korvattu termi tälle vai erillinen käsite? 

#### Perustelut ehdotukselle   

http://tieteentermipankki.fi/wiki/Nimitys:ekologinen_tasapaino
http://eurovoc.europa.eu/drupal/?q=mt/request&view=pt&termuri=http://eurovoc.europa.eu/392459&language=fi
(Selvitän miten pitäisi paremmin kääntää "luonnon tasapaino" ruotsiksi (aikaisemmin "jämvikt i naturen")) 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
ekologinen tasapaino: Ympäristön tila, jossa eliöiden väliset suhteet ovat vakaat tai muuttuvat tasaisesti ja jossa muutokset johtuvat luonnonprosesseista.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Balance_of_nature

**Comment by PaiviLipsanen** [comment]
"Luonnon tasapaino" on näköjään otettu YSAan v. 1985. Googlaamalla sitä löytyy vain n. 200 osumaa, jotka eivät näytä liittyvän tieteellisiin aineistoihin. "Ekologinen tasapaino" taas löytyy mm. Tieteen termipankista. Käsitteet eivät tunnu täysin vastaavan toisiaan, koska esim." järven tai Lapin luonnon tasapaino" kuulostaa vähän oudolta, mutta "järven tai Lapin ekologinen tasapaino" kuulostaa asialliselta. Olisiko kieli tässä muuttunut?

**Comment by YSA-kokous** [comment]
Otetaan ekologinen tasapaino, mahdollisesti poistetaan luonnon tasapaino.

**Comment by mirmaid** [comment]
Poistetaan luonnon tasapaino, korvattavissa termillä ekologinen tasapaino & muilla termeillä.
