### ISSUE TITLE
sukupuolitutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5079]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sukupuolitutkimus](http://www.yso.fi/onto/ysa/Y127181) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

muutetaan korvatuksi asiasanaksi 

#### Perustelut ehdotukselle   

Asiasana "sukupuolitutkimus" on YSAn mukaan käytettävä termi, vaikka siinä kuitenkin lukee, että se oli käytössä vuoteen 2012 asti. "Sukupuolentutkimus" on käytettävä termi, käytössä vuodesta 2012 lähtien. Eikö "sukupuolitutkimus"-termin pitäisi silloin olla korvattu termi? 

#### Ehdottaja   

Ludvig Forsman 

#### Ehdottajan organisaatio   

Turun yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ludvig.forsman@utu.fi

**Comment by mirmaid** [comment]
Lisätty edeltäjä-seuraaja -suhde.
