### ISSUE TITLE
Wessex

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5080]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Wessex 

#### Ehdotettu termi englanniksi   

Wessex 

#### exactMatch   

Wessex : https://fi.wikipedia.org/wiki/Wessex 
Wessex : <http://explore.bl.uk/primo_library/libweb/action/display.do?tabs=moreTab&ct=display&fn=search&doc=BLL01018227601&indx=1&recIds=BLL01018227601&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&dscnt=0&vl(10130439UI0)=sub&vl(drEndMonth4)=00&vl(drStartDay4)=00&scp.scps=scope%3A%28BLCONTENT%29&tab=local_tab&dstmp=1489737465864&srt=date&mode=Advanced&vl(drEndDay4)=00&vl(1UIStartWith1)=contains&tb=t&vl(41497491UI2)=any&vl(freeText0)=Wessex&vid=BLVU1&vl(freeText2)=&vl(drEndYear4)=Year&frbg=&vl(10130438UI1)=any&vl(drStartMonth4)=00&vl(1UIStartWith2)=contains&dum=true&vl(1UIStartWith0)=contains&vl(46690061UI3)=all_items&Submit=Search&vl(drStartYear4)=Year&vl(freeText1)=> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Englannin historiaan liittyvä alueen nimi, anglosaksinen valtakunta. 

#### Perustelut ehdotukselle   

Wessexiä maantieteellisenä käsitteenä ei voi suoraan korvata nykyisillä alueiden nimillä.  Melindassa termi on jo käytössä sekä kauno- että tietokirjojen kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Goodman, Kent: Prehistoric sacred sites of Wessex, 0-9529619-1-1 

**Ehdottajan nimi:** Katri Syrjälä 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** katri.syrjala@tampere.fi **Termiehdotus Fintossa:** [Wessex](http://finto.fi/yse/fi/page/Y505080)

**Comment by mirmaid** [comment]
LCSH: Wessex (England): Here are entered works on the region that comprises Dorset, Wiltshire, Somerset, Avon, Oxfordshire, and Devon.

**Comment by mariaforsen** [comment]
Sv. Wessex
