### ISSUE TITLE
Hallstattin kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5081]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Hallstattin kulttuuri 

#### Ehdotettu termi ruotsiksi   

Hallstattkulturen 

#### Ehdotettu termi englanniksi   

Hallstatt period 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuurit (kulttuurimuodot)](http://www.yso.fi/onto/yso/p1546) 

#### Assosiatiiviset (RT)   

[rautakausi](http://www.yso.fi/onto/yso/p2558) 

#### exactMatch   

Library of Congress Subject Headings : <http://id.loc.gov/authorities/subjects/sh85058486> 
Svenska ämnesord : Hallstattkulturen 
Wikipedia : Hallstattin kulttuuri 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan arkeologisen tutkimuskirjallisuuden sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3052468 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [Hallstattin kulttuuri](http://finto.fi/yse/fi/page/Y505081)

**Comment by mariaforsen** [comment]
Sv. Hallstattkulturen
