### ISSUE TITLE
La Tènen kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5082]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

Latènekulturen 

#### Ehdotettu termi suomeksi   

La Tènen kulttuuri 

#### Ehdotettu termi englanniksi   

La Tène period 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuurit (kulttuurimuodot)](http://www.yso.fi/onto/yso/p1546) 

#### Assosiatiiviset (RT)   

[rautakausi](http://www.yso.fi/onto/yso/p2558) 

#### exactMatch   

Library of Congress Subject Headings : <http://id.loc.gov/authorities/subjects/sh85073610> 
Svenska ämnesord : Latènekulturen 
Wikipedia : La Tènen kulttuuri 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan arkeologisen tutkimuskirjallisuuden sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2866634 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [La Tènen kulttuuri](http://finto.fi/yse/fi/page/Y505082)

**Comment by mariaforsen** [comment]
Sv. Latènekulturen
