### ISSUE TITLE
kestävyysjuoksu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5083]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kestävyysjuoksu](http://www.yso.fi/onto/ysa/Y96118) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-suhde termiin kestävyyslajit 

#### Perustelut ehdotukselle   

Termi "kestävyysjuoksu" rakentuu kahdesta osiosta: juoksusta ja kestävyydestä. Tällä hetkellä termin LT-suhde huomioi näistä vain ensimmäisen. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
LT-suhde lisätty.
