### ISSUE TITLE
operaatiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5084]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[operaatiot](http://www.yso.fi/onto/ysa/Y177764) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennus termin merkitykseen (tai mahdollisesti jako)? 

#### Perustelut ehdotukselle   

On monimerkityksinen. Korvattuna terminä on sotilaalliset operaatiot, mutta ryhmä silti vain 00 (eikä 67 ollenkaan). Jos tämä viittaa nimenomaan vain sotilaallisiin operaatioihin niin voisiko ryhmäksi laittaa 67? Ruotsiksi voidaan sitten muuttaa päätermi: militära operationer. Pelkkä operationer tulkitaan ruotsiksi helposti lääketieteellisiksi, joten jonkinlainen tarkennus varmaan tarvitaan miten vain. Ks. myös MOT. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Voisi olla suomeksikin sotilaalliset operaatiot, mutta käykö tämä jos kyse on kriisinhallinnasta/rauhanturvaamisesta (peacekeeping missions)? Voidaan toki myös ottaa erikseen _rauhanturvaoperaatiot_ (on JUHOssa ja PUHOssa).

**Comment by AuHo22** [comment]
Myös sotilasoperaatiot vähän lyhyempänä muotona

**Comment by EsaMPKK** [comment]
Sotilaalliset operaatiot / operaatiot (sotatoimet) ihan mahdollisia.

**Comment by mariaforsen** [comment]
SAO:ssa on sekä militära operationer että fredsbevarande operationer. Kannatan sitä mallia.

**Comment by mirmaid** [comment]
rauhanturvaoperaatiot

sotilasoperaatiot / sotilaalliset operaatiot / operaatiot (sotatoimet) - mikä näistä?

**Comment by EsaMPKK** [comment]
Operaatiot (sotatoimet) olisi muuten looginen, mutta rakenteeltaan kovin erilainen kuin rauhanturvaoperaatiot. 

Sotilaalliset operaatiot on hankala ja muutenkin korvattu termi. 

Sotilasoperaatiot lienisi selkein?

**Comment by YSA-kokous** [comment]
rauhanturvaoperaatiot
sotilasoperaatiot
