### ISSUE TITLE
selkoaineistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5085]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

selkoaineistot 

#### Alakäsitteet (RT)   

[selkokirjat](http://www.yso.fi/onto/yso/p6190) 

#### Vaihtoehtoiset termit ja ilmaisut   

selkokieliset aineistot 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 
[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 

#### Perustelut ehdotukselle   

Otettiin Kaunokkiin 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** HYK, Kaunokki-kokous 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [selkoaineistot](http://finto.fi/yse/fi/page/Y505085)

**Comment by mariaforsen** [comment]
Sv. lättläst material  ET lättlästa publikationer ET lättlästa resurser

**Comment by satuniininen** [comment]
engl. easy-to-read publications
