### ISSUE TITLE
vaihtolämpöisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5086]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vaihtolämpöisyys](http://www.yso.fi/onto/ysa/Y103275) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon vaihtolämpöiset eläimet/lajit tms. 

#### Perustelut ehdotukselle   

Allärsissa växelvarma djur, ei ruotsinkielistä vastinetta YSAn nykyiselle muodolle, mikä aiheuttaa hankaluutta YSOssa. Vaihtolämpöisyys käytetty Melindassa 7 kertaa, 3 kertaa muotoa "vaihtolämpöiset". 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by YSA-kokous** [comment]
vaihtolämpöiset eläimet
