### ISSUE TITLE
pianomusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5087]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pianomusiikki 

#### Ehdotettu termi ruotsiksi   

pianomusik 

#### Ehdotettu termi englanniksi   

piano music 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soitinmusiikki](http://www.yso.fi/onto/yso/p1514) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85101782> 
SAO : Pianomusik 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu pianolle. 

#### Perustelut ehdotukselle   

Tarvitaan kokoavan termi kattamaan pianomusiikin eri lajit yhteen. On vaikea kuvailla aineistoa, joka käsittelee samanaikaisesti sonaatteja, sarjoja, fantasioita ym. pianolle, mutta ei pianoa, sillä termit "sävellykset"/"soolot" + "piano" ei ole yhtä täsmällinen kuin mitä tämä uusi termi olisi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Márta Grabócz: Morphologie des oeuvres pour piano de Liszt 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Vaihtoehtoiset termit ja ilmaisut   

fortepianomusiikki, vasaraklaverimusiikki 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [pianomusiikki](http://finto.fi/yse/fi/page/Y505087)

**Comment by AuHo22** [comment]
Ei ole musa-sanastossa -> yhtä lailla sitten laajennus sellomusiikki, kitaramusiikki jne.

**Comment by YSA-kokous** [comment]
Luumu valmistelee yhtenäisen ratkaisun tämäntyyppisille termeille.

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by jtuohini** [comment]
Uusittu selite: Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle pianolle tai muulle kokoonpanolle, jossa piano on keskeisessä osassa.

**Comment by asormune** [comment]
Koskeeko myös pianokonserttoja?

**Comment by jtuohini** [comment]
Asiasana **pianomusiikki** olisi siis tarkoitettu sellaisen kirjallisuuden kuvailuun, jonka aiheena on musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle pianolle tai esityskokoonpanolle, jossa piano on keskeisessä osassa. Jos kuvailtava aineisto käsittelee pelkästään pianokonserttoja, olisi syytä käyttää jotakin tarkempaa kuvailua (**konsertot** tai tulevaisuudessa ehkä _pianokonsertot_), mutta jos kyse on pianomusiikkia yleisesti käsittelevästä teoksesta, niin sitten tämä nyt ehdotettu asiasana olisi omiaan.
Analogiana nykyinen asiasana **orkesterimusiikki**: jos kirja käsittelee kaikenlaista orkesterimusiikkia, niin sitten käytetään sitä, jos pelkkiä sinfonioita, niin sitten ei.

**Comment by tpalonen** [comment]
Onko barrelhouse piano tämän alakäsite?

**Comment by jtuohini** [comment]
Ei ole, koska **barrelhouse piano** on bluesin/jazzin alalaji, kun taas **pianomusiikki** ei ota kantaa musiikinlajiin, vaan ainoastaan esityskokoonpanoon (pianomusiikki voi siis olla jazzia, bluesia, länsimaista taidemusiikkia tai jotain muuta, joskin pääasiassa aineisto, jota termillä jatkossa kuvaillaan, käsittelenee länsimaista taidemusiikkia).

**Comment by jtuohini** [comment]
Ai niin, piti kommentoida heti uudelleen jo aikaa sitten: toki **barrelhouse piano** olisi asiasanan **pianomusiikki** olisi ST, kun mainittu nimenomaisesti on pianolla esitetyn bluesin/jazzin alalaji!

**Comment by jtuohini** [comment]
Muusan päätös 28.3.2018: kannatetaan ehdotusta muodossa
 
**pianomusiikki**
Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle pianolle tai muulle kokoonpanolle, jossa piano on keskeisessä osassa.
KT fortepianomusiikki
KT vararaklaveerimusiikki
KT vararaklaverimusiikki
LT musiikki
ST barrelhouse piano

Muut vastaavat samalla periaatteella (jo vanhastaan on **kuoromusiikki**, **lyömäsoitinmusiikki**, **orkesterimusiikki**): _huilumusiikki_, _viulumusiikki_, _sellomusiikki_, _urkumusiikki_ jne.
