### ISSUE TITLE
Inari-Saariselkä (matkailukeskus)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5088]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Inari-Saariselkä (matkailukeskus) 

#### Ehdotettu termi englanniksi   

Inari-Saariselkä (tourist resort) 

#### Ehdotettu termi ruotsiksi   

Inari-Saariselkä (turistcentrum) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matkailukeskukset](http://www.yso.fi/onto/yso/p9637) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Tarkoitusta täsmentävä selite   

http://www.inarisaariselka.fi/en/ 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lähiruoasta matkailuravintoloiden valttikortti? :keittiömestareiden ja ravintolan vastuuhenkilöiden näkemyksiä lähiruoan käytöstä Levillä ja Saariselällä /Marja Uusitalo, Olli Wuori, Pasi Rikkonen, Jussi Veijola ja Tuomas Jauho. 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [Inari-Saariselkä (matkailukeskus)](http://finto.fi/yse/fi/page/Y505088)

**Comment by mirmaid** [comment]
Onkohan nämä oikeastaan yhteisöjä...

**Comment by mariaforsen** [comment]
Sv. Enare-Saariselkä (turistcentrum)

**Comment by YSA-kokous** [comment]
Auktorisoidaan yhteisönä.
