### ISSUE TITLE
jambi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5090]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jambi 

#### Ehdotettu termi englanniksi   

iamb 

#### Ehdotettu termi ruotsiksi   

jamb 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Lyhytpitkä nouseva runojalka, jossa yhtä painotonta (antiikin runojaloissa lyhyttä) tavua seuraa yksi painollinen (antiikin runojaloissa pitkä) tavu. Paino, korko tai kesto on jälkimmäisellä tavulla. Ensimmäinen tunnettu jambisäkeen käyttäjä on kreikkalainen Arkhilokhos (n. 670-620 eKr.). Jambisesta trimetristä tuli pian kreikkalaisen draaman lähes yksinomainen mitta. (Tieteen termipankki) 

#### Perustelut ehdotukselle   

Kitun/KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallsiuudentutkimuksellisen aineiston luetteloinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [jambi](http://finto.fi/yse/fi/page/Y505090)

**Comment by mirmaid** [comment]
Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. jamb
