### ISSUE TITLE
tappiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5091]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tappiot](http://www.yso.fi/onto/ysa/Y102161) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö lisätä muitakin luokkia kuin 75? Ja KT häviöt? Vai vaatiiko jopa jakoa? 

#### Perustelut ehdotukselle   

Termi on käytetty muissakin merkityksissä kuin taloustiede, varsinkin sotien/taisteluiden yhteydessä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Samoin _voitot_. Ehkä mahdollinen muutos tässäkin _voitot (talous)_ ja _voittaminen_.

**Comment by mariaforsen** [comment]
Tarvitaan myös JUHO-työssä.

**Comment by EsaMPKK** [comment]
Sodassa puhutaan tappioista, mutta sotatappiot ei mielestäni ole hyvä. Sotatieteellisessä ontologiassa pelkkä tappiot on päivänselvä, mutta yleisellä puolella pitäisi keksiä sulkutarkennus. Tappiot (sota) olisi YSA-mallinen ratkaisu, mutta pitääkö miettiä YSOa?

**Comment by YSA-kokous** [comment]
voittaminen

voitot (talous) (mahd. myös taloudelliset voitot, soveltuuko?) - tutkitaan vielä, vrt. tappiot

**Comment by YSA-kokous** [comment]
sotatappiot + määritelmä

**Comment by mirmaid** [comment]
Maanpuolustuskorkeakoulun asiantuntijan mukaan taistelutappiot olisi voinut olla parempi, kuvaavampi ja vakiintuneempi termi.

**Comment by ilona-x** [comment]
tappiot korjattu Melindaan, jäljelle jäi esim. maatalouteen liittyviä tappioita, myös kalastuksessa hylkeiden aiheuttamat tappiot, mehiläistenhoidossa mehiläisten talvitappiot 

AFOsta löytyy puintitappiot, satotappiot, varastointitappiot, varisemistappiot
