### ISSUE TITLE
kovaksikeitetty dekkari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5092]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kovaksikeitetty dekkari 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun/KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimuksellisen, sosiologisen yms.  aineiston luetteloinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kovaksikeitetty dekkari](http://finto.fi/yse/fi/page/Y505092)

**Comment by amssi** [comment]
kirjoitusvirhe, po. kovaksikeitetty

**Comment by jtuohini** [comment]
Mutta mitä ehdotettu termi tarkoittaa? Ja pitäisikö sen olla monikossa? Entä LT- ja RT-suhteet termeihin **salapoliisikirjallisuus** ja/tai **yksityisetsivät**?

**Comment by amssi** [comment]
Ehdotus lähti vahingossa ennen aikojaan. Kovaksi keitetty dekkari on realistisen rikoskertomuksen tai -romaanin muoto, jolle on ominaista lakoninen, karkeuksia ja hirtehishuumoria viljelevä dialogi sekä tapahtumien sijoittuminen rähjäiseen ympäristöön. (Tieteen termipankki). LT salapoliisikirjallisuus

**Comment by mirmaid** [comment]
Kaunokissa muodossa _kovaksikeitetty rikoskirjallisuus_

**Comment by mariaforsen** [comment]
Sv. hårdkokta deckare, hårdkokta kriminalromaner

**Comment by YSA-kokous** [comment]
KÄ kovaksikeitetty rikoskirjallisuus
