### ISSUE TITLE
julkisten alojen eläkelaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5093]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

julkisten alojen eläkelaki 

#### Ehdotettu termi ruotsiksi   

pensionslag för den offentliga sektorn 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lait (tuotokset)](http://www.yso.fi/onto/yso/p1464) 

#### Assosiatiiviset (RT)   

[kunnallinen eläkelaki](http://www.yso.fi/onto/yso/p23279) 
[valtion eläkelaki](http://www.yso.fi/onto/yso/p23587) 

#### Tarkoitusta täsmentävä selite   

"Julkisten alojen eläkelaki (81/2016) tulee voimaan 1 päivänä tammikuuta 2017.

Tällä lailla kumotaan seuraavat lait:
1) KuEL-laki;
2) Kunnallisen eläkelain voimaanpanolaki (550/2003);
3) VaEL-laki;
4) valtion eläkelain voimaanpanosta annettu laki (1296/2006); sekä
5) KiEL-laki."

lähde: http://www.finlex.fi/fi/laki/alkup/2016/20160082

http://www.finlex.fi/fi/laki/alkup/2016/20160081 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Työeläke  ISBN 978-952-5684-90-2 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [julkisten alojen eläkelaki](http://finto.fi/yse/fi/page/Y505093)

**Comment by mariaforsen** [comment]
Sv. pensionslag för den offentliga sektorn
