### ISSUE TITLE
oopperaohjaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5094]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oopperaohjaajat 

#### Ehdotettu termi ruotsiksi   

operaregissörer 

#### Ehdotettu termi englanniksi   

opera directors 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ohjaajat](http://www.yso.fi/onto/yso/p12705) 

#### Assosiatiiviset (RT)   

[oopperaohjaus](http://www.yso.fi/onto/yso/p28149) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85094911> 
DNB : <http://d-nb.info/gnd/4203173-4> 
RAMEAU : <http://data.bnf.fr/13163068/metteurs_en_scene_d_opera/> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

auktoriteettitietueissa, opperaohjaajia käsittelevässä kirjallisuudessa 

#### Perustelut ehdotukselle   

tarkempi käsite tarpeen, vrt. vastaavat käsitteet muissa sanastoissa 

**Ehdottajan nimi:** Ilkka Haataja 
**Ehdottajan organisaatio:** Taideyliopiston Sibelius-Akatemian kirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.haataja@uniarts.fi **Termiehdotus Fintossa:** [oopperaohjaajat](http://finto.fi/yse/fi/page/Y505094)

**Comment by asormune** [comment]
Sovellettaisiinko samoin operettiin, musikaaleihin, baletteihin termeillä operettiohjaajat, musikaaliohjaajat, balettiohjaajat. Sanastoissa ei taida olla termiä näyttämöohjaus/näyttämöohjaajat.

**Comment by jtuohini** [comment]
Löytyy termi **teatteriohjaajat**, jonka laajempi termi on **ohjaajat**. Oopperaohjauksesta löytyy paljonkin aineistoa, mutta onko noille muille juuri kuvailuntarvetta? "Balettiohjaajat" varmaankin olisi yhtä kuin YSA-termi **koreografit**?

Ja Ysasta löytyy termit termit **teatteriohjaus** ja sille ST-suhteinen **oopperaohjaus**.

**Comment by asormune** [comment]
Koreografi tekee koreografian, mutta ei välttämättä ole baletin (näyttämöesityksen) ohjaaja. Balettien taltioinneissa on usein (julkaisuissa) mainittu esim. video-ohjaaja. Orkesterinjohtaja (asiasana = kapellimestarit), tekijäfunktio = "johtaja" (toimintana = orkesterinjohtaminen)

**Comment by jtuohini** [comment]
Vielä jäi minua askarruttamaan tuo koreografin osuus: eikö koreografi vastaa tanssiteoksessa koko näyttämöliikehdinnästä samalla tavoin kuin teatteriohjaaja vastaa (puhe)draaman esityksessä näyttöliikehdinnästä? Jos tanssiosuus on vain osa esimerkiksi oopperaa, niin silloin koreografin rooli on toki rajoitetumpi. Mutta tähänkin liittyen edelleen pohdin, onko oikeasti aineistoja, joiden aiheena on vaikkapa musikaaliohjaaja (joka ei siis ohjaa esimerkiksi puheteatteria yms.) niin, ettei asiasana **teatteriohjaajat** kelpaa, tai balettiohjaaja (joka ei ole koreografi) jne. Toki asiaa voi teoretisoida, mutta mikä on käytännön tarve noille muille eli toivoisin esimerkkejä opuksista, joihin noin muita mahdollisia asiasanoja tarvittaisiin.

**Comment by asormune** [comment]
En suoraan miettinyt kirjallisuuden kuvailua näissä kommenteissani. Katsoin muutamia luettelointeja. Prokofjevin Romeo & Juliet (Blu-ray, State Academic Mariinsky Theatre, 2014) julkaisussa on 500-kentässä: $aTV-ohjaus: Olivier Simonnet, näyttämöohjaus: Juri Fatejev, koreografi: Leonid Lavrovski.

**Comment by mariaforsen** [comment]
Sv. operaregissörer

**Comment by OutiHintikka** [comment]
Oopperaohjaaja ja koreografi ja kapellimestari  työskentelevät yhdessä. Työtehtävät eroavat; suomessa mm. Juha Hemanus ja Kari Heiskanen on tehnyt paljon oopperaohjauksia. Koreografit tekevät oopperaan koreografian.
