### ISSUE TITLE
Hardyn avaruus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5096]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Hardyn avaruus 

#### Ehdotettu termi englanniksi   

Hardy space 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matemaattiset käsitteet](http://www.yso.fi/onto/yso/p27190) 

#### exactMatch   

LCSH : <Hardy spaces http://id.loc.gov/authorities/subjects/sh85058902.html> 

#### Tarkoitusta täsmentävä selite   

In complex analysis, the Hardy spaces (or Hardy classes) Hp are certain spaces of holomorphic functions on the unit disk or upper half plane.
In real analysis Hardy spaces are certain spaces of distributions on the real line, which are (in the sense of distributions) boundary values of the holomorphic functions of the complex Hardy spaces, and are related to the Lp spaces of functional analysis.

https://en.wikipedia.org/wiki/Hardy_space 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

On the Jacobian equation and the Hardy Space H¹ (C) /Sauli Lindberg. 

#### Vaihtoehtoiset termit ja ilmaisut   

Hardyn avaruudet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [Hardyn avaruus](http://finto.fi/yse/fi/page/Y505096)

**Comment by mirmaid** [comment]
Monikko?

**Comment by mariaforsen** [comment]
Sv. Hardy-rum

**Comment by YSA-kokous** [comment]
Hyväksytään monikossa.
