### ISSUE TITLE
Jacobin determinantit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5097]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Jacobin determinantit 

#### Ehdotettu termi englanniksi   

Jacobians, Jacobian determinants, Jacobian matrices 

#### Ehdotettu termi ruotsiksi   

Jacobian 

#### Ehdotettu yläkäsite YSOssa (LT)   

[determinantit](http://www.yso.fi/onto/yso/p11285) 

#### exactMatch   

LCSH : <Jacobians http://id.loc.gov/authorities/subjects/sh85069214> 

#### Tarkoitusta täsmentävä selite   

Jacobin matriisi on matriisi, joka kuvaa muunnoksen kahden avaruuden välillä. Jacobin matriisin determinanttia kutsutaan Jacobin (funktionaali)determinantiksi. https://fi.wikipedia.org/wiki/Jacobin_matriisi

Jacobian matrix is the matrix of all first-order partial derivatives of a vector-valued function. When the matrix is a square matrix, both the matrix and its determinant are referred to as the Jacobian in literature https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant 

#### Vaihtoehtoiset termit ja ilmaisut   

Jacobin matriisit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

On the Jacobian equation and the Hardy Space H¹ (C) /Sauli Lindberg. 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [Jacobin determinantit](http://finto.fi/yse/fi/page/Y505097)

**Comment by mirmaid** [comment]
Vai otetaanko päätermiksi Jacobin matriisit?

**Comment by mariaforsen** [comment]
Sv. Jacobimatriser ET funktionalmatriser ET Jacobian

**Comment by YSA-kokous** [comment]
Hyväksytään Jacobin matriisit.
