### ISSUE TITLE
yksineuvoisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5100]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yksineuvoisuus](http://www.yso.fi/onto/ysa/Y102100) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ yksineuvoiset kasvit 

#### Perustelut ehdotukselle   

Allärsissa termi on enkönade arter, ominaisuus-muotoista termiä ei ole olemassa ruotsiksi, mikä johtaa virheelliseen hierarkiaan YSOssa. Termiä ei ole käytetty Melindassa. Muoto yksineuvoiset lajit voisi kuitenkin olla kuvailijan kannalta hämärä, jos aineisto ei käsittele asiaa laji-näkökulmasta. 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/723

**Comment by mariaforsen** [comment]
Sv. enkönade arter > enkönade växter
