### ISSUE TITLE
laulusarjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5101]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laulusarjat 

#### Ehdotettu termi ruotsiksi   

sångcykler 

#### Ehdotettu termi englanniksi   

song cycles 

#### exactMatch   

LCSH : https://lccn.loc.gov/sh85125033 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tunbridge, Laura. The song cycle 

#### Tarkoitusta täsmentävä selite   

Musiikilliseksi kokonaisuudeksi tarkoitettu kokoelma lauluja yhdelle tai useammalle lauluäänelle soitinsäestyksen kanssa tai ilman säestystä. 

#### Perustelut ehdotukselle   

Varsinkin taidemusiikin puolella vakiintunut lajityyppi, josta myös suhteellisen runsaasti kirjallisuutta. 

**Ehdottajan nimi:** Ilkka Haataja 
**Ehdottajan organisaatio:** Taideyliopiston Sibelius-Akatemian kirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.haataja@uniarts.fi **Termiehdotus Fintossa:** [laulusarjat](http://finto.fi/yse/fi/page/Y505101)

**Comment by mariaforsen** [comment]
Sv. sångcykler
