### ISSUE TITLE
sotapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5102]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sotapelit](http://www.yso.fi/onto/ysa/Y201830) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termiin selitys ja tarpeen tullen sulkutarkennus tms. tekemään selväksi, ettei kyse ole armeijan sotapeleistä (engl. "military simulation", puhekielisesti myös "war games"), vaan harrastustoimintaan kuuluvista sota-aiheisista peleistä. ["Military simulations, also known informally as war games, are simulations in which theories of warfare can be tested and refined without the need for actual hostilities. Many professional analysts object to the term wargames as this is generally taken to be referring to the civilian hobby, thus the preference for the term simulation." (https://en.wikipedia.org/wiki/Military_simulation)] 

#### Perustelut ehdotukselle   

Tällä hetkellä PUHOn "sotapelit"- ja YSAn ja YSOn samasanainen "sotapelit"-termi tarkoittavat kahta eri asiaa, ja näiden välille pitäisi tehdä ero, etteivät sekoittuisi KOKOssa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/America's_Army

**Comment by mariaforsen** [comment]
Vai tarvitaanko siinä tapauksessa molemmat, eli jakoa? Ks. esim. Virtuaalinen taistelukenttä oppimisympäristönä : taistelun opetus upseerioppilaan näkökulmasta reserviupseerikoulun 1. komppaniassa / Heikki Lämsä-Tapio Melindassa. 

Termi "krigsspel" on Svenska ämnesordissa nimenomaan sotilaallisessa merkityksessä (huomautus: "Simulering av krigs- eller stridsförlopp i studie- eller utbildningssyfte eller för att pröva krigsplanläggning." /Nationalencyklopedin).

**Comment by EsaMPKK** [comment]
Esim. PUHO: sotapelit (sotilaskoulutus) vs. YSA-YSO: sotapelit (harrastukset). Tai molemmat molempiin.

**Comment by satuniininen** [comment]
Myös LCSH:n _War games_ on monimerkityksinen. Sen alakäsitteinä on sekä sotilaskoulutuksessa käytettäviä pelejä, esim. _AGATE (Computer war game)_ että harrastepelejä, kuten _Phoenix Command (Game)_.

**Comment by mirmaid** [comment]
Pitääkö nämä välttämättä erottaa toisistaan? Ymmärtääkseni siis tuo _America's Army_ on molempia.

**Comment by YSA-kokous** [comment]
Ei jaeta
