### ISSUE TITLE
kotiutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5104]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotiutus](http://www.yso.fi/onto/ysa/Y109918) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termin merkitys ja suhde kotiutuminen-termiin selkeytettävä. 

#### Perustelut ehdotukselle   

Käytetty yleensä sairaalasta kotiuttamisesta, mahdollista käyttää myös ainakin varojen kotiutuksesta. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
**kotiutus** Melindassa 151 kertaa, pääasiassa sairaalasta kotiutuksen kontekstissa
**kotiutuminen** 14 kertaa, sairaalasta kotiutumista ja (maahan)muuttajien kotiutumista

**Comment by mirmaid** [comment]
Allärs: hemförlovning & utskrivning = kotiutus, hemanpassning = kotiutuminen, kotoutuminen = integration (invandrare)

EHDOTUS (EN):

Kotiutuminen:
discharge (release)

Kotiutus:
demobilisation (armeijakontekstissa)
repatriation (rahaliikenne)
[myös discharge (release) ehkä tarpeen?]

**Comment by mirmaid** [comment]
Eriteltynä käsitteiden merkityksiä ja käyttöhistoriaa sisällönkuvailussa: https://docs.google.com/spreadsheets/d/1S2hd7y_bex17e5GUOVCMCE5tSclm8rPGIEauy1C3YGw/edit?usp=sharing

**Comment by mirmaid** [comment]
KOTIUTUS

Melindassa käytetty pääasiassa sosiaali- ja terveydenhuollon, mutta myös ekspatriaattien, sotalapsien, sotilaiden, muinaisjäännösten ja taideteosten yhteydessä. Keskeisenä merkityspiirteenä palauttaminen lähtöpaikkaan, toimeenpanijana joku muu kuin kohde itse. Voiko YSOn selitys olla noin abstrakti? Ei kannattane rajoittaa vain terveydenhuollon yhteyteen.

Selvä merkitysero esim.: ekspatriaatit – kotiutus <-> ekspatriaatit – kotiutuminen

KOTIUTUMINEN

Melindassa käytetty pääasiassa sosiaali- ja terveydenhuollon ja maahanmuuttajien yhteydessä. Keskeisenä merkityspiirteenä refleksiivisyys, näkökulmana toimija itse ja tapahtuma hänen kannaltaan. Eroa on kuitenkin siinä, käytetäänkö terveydenhuollon vai maahanmuuttajien yhteydessä (MOTin merkitykset 1. ja 2.):

terveydenhuollossa: vanhukset – kotiutuminen ( = kotiinpaluu) maahanmuuttajat – kotiutuminen ( = tottua olemaan jossakin, ruveta viihtymään)

Pitäisikö siis jakaa: (alla olevat esimerkkitarkenteet eivät ole YSAn termejä)
kotiutuminen (kotiinpaluu)
kotiutuminen (tottuminen olosuhteisiin) (ehdotettu myös tarkennetta sopeutuminen)

Käytetty kerran myös MOTin 3.-merkityksessä ”tulla vakiintuneeseen käyttöön, saada pysyvä jalansija, juurtua” (”innovaatioiden kotiutuminen”, käytetty myös sanoja omaksuminen, käyttöönotto, kuluttajakäyttäytyminen)

**Comment by mirmaid** [comment]
KOTOUTUMINEN

Melindassa käytetty maahanmuuttajien ja pakolaisten yhteydessä.

Selitysehdotus MOTin pohjalta: Tarkoittaa maahanmuuttajien asettumista uuteen yhteiskuntaan omat kulttuuripiirteensä säilyttäen.

kotouttaminen Allärs: integrationsfrämjande

Ehdotettu myös _kotoutuminen_ ja _kotouttaminen_ -termien yhdistämistä, sekä lisäystä _kotouttaminen (käännöstiede)_.

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/289

**Comment by mirmaid** [comment]
Ehdotettu myös termien integrointi ja integraatio yhdistämistä. https://github.com/NatLibFi/Finto-data/issues/243

Sanastossa myös _integroitu opetus_

**> näille oma issue**

**Comment by mirmaid** [comment]
Ehdotus (huomioimatta Melindaa toistaiseksi):

kotiutus (terveydenhuolto) KT kotiutuminen (terveydenhuolto)
kotiutuminen (kotiinpaluu) KÄ kotiinpaluu
kotiutuminen (sopeutuminen)
kotouttaminen (käännöstiede)
kotoutuminen KÄ kotouttaminen (tarkenne x) & kotiutuminen (sopeutuminen)

**Comment by mariaforsen** [comment]
-Mesh: potilaan kotiuttaminen (KT kotiutus) = patientutskrivning, olisiko myös tämä mahdollinen vaihtoehto?
-kotiinpaluu = hemkomst on hyvä 
-kotiutuminen (sopeutuminen) = on eräänlainen "anpassning", mutta se on jo sanastossa sopeutumisen vastineena.. Kotiutuminen googlessa näyttää olevan lähinnä sairaalakontekstia yms. Vaikeaa saada järkevä ruotsinnos. Nykyinen Allärs-vastine hemanpassning sopimation. 
-kotouttaminen (käännöstiede) = domesticering (översättning) (http://tieteentermipankki.fi/wiki/K%C3%A4%C3%A4nn%C3%B6stiede:kotouttaminen)

**Comment by mirmaid** [comment]
sanakirja: kotiutua=börja känna sig hemma > sig hemma kännande börjande :sunglasses:

**Comment by siikaa** [comment]
Ymmärsinköhän oikein? Mirjan ehdotukseen yllä viitaten: Jäisikö kotiutus-termi siis edelleen YSA:aan myös ilman (terveydenhuolto) sulkutarkennetta? Kaunokissahan tuolle terveydenhuolto tarkenteelle ei ehkä olisi niin paljon käyttöä...

**Comment by mirmaid** [comment]
Jos ylläoleva osoittautuisi jotenkin mahdolliseksi toteuttaa, _kotiutus_ jäisi YSAan vain terveydenhuollon terminä. Nythän ongelma on se, että hyvinkin monia asioita voidaan periaatteessa kotiuttaa, mutta ruotsiksi ei ole yhtä termiä jolla olisi sama merkityskenttä. Ajatukseni oli, että kun kyse on ihmisen kotiutuksesta esim. ulkomailta olisi _kotiinpaluu_ käypä termi.

**Comment by siikaa** [comment]
Kuten armeijasta kotiutus tai rintamalta. Kai sodasta palaamiseen käy kotiinpaluu mutta ehkä ei varusmiesten kotiutukseen kuitenkaan... Kaunokissa on kotiutus ja nuo kolme ruotsinkielistä Bellan termiä...jos toteutuu niin miten mahdollisesti vaikuttaa Kaunokkiin?

**Comment by mirmaid** [comment]
^ Riippuu varmaankin siitä onko Kaunokissa sama pyrkimys yksi yhteen vastaavuuteen suomen ja ruotsin välillä kuin YSA/YSOssa. Kauno-ontologiassa on kotiutus = utskrivning.

**Comment by mirmaid** [comment]
Ehdotan että ratkaistaan nyt termin _kotiutus_ kohtalo: kotiutus (terveydenhuolto) TAI potilaan kotiutus (tai jtn muuta)

Otetaan
_kotiinpaluu
kotouttaminen (käännöstiede)_

Tehdään muista avoimeksi jäävistä ongelmista selkeyden vuoksi uusi issue/issuet. Kotiutuminen/kotoutuminen ruots. vastineet tuskin selviävät huomiseksi.

**Comment by mariaforsen** [comment]
NE: Utskrivning="tidigare benämning på tvångsvis inskrivning och anställning av manskap för krigsmaktens behov" - eli aivan päinvastainen merkitys verrattuna kotiinpaluuseen yms. 

SAOssa onkin "utskrivning (militärväsen)" joka viittaa juuri siihen (eli ei pitäisi sekoittaa tähän) ja "patientutskrivning"

Kannatan ainakin: 
potilaan kotiutus/kotiuttaminen (kuten MESHissä)=patientutskrivning
kotiinpaluu=hemkomst
kotouttaminen (käännöstiede)=domesticering (översättning)

Voisiko muut "kotiutuminen" mahdollisesti ohjata muihin termeihin (ks. Melinda)? Tai jos laitetaan tarkenne (sopeutuminen), niin on varmasti mahdollista luoda jonkinlainen ratkaisu ruotsiksikin (kunhan merkitys/käyttökonteksti on selvä).

**Comment by YSA-kokous** [comment]
potilaan kotiuttaminen
kotiinpaluu
kotouttaminen (käännöstiede)
