### ISSUE TITLE
Yunnan

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5105]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Yunnan 

#### Ehdotettu termi ruotsiksi   

Yunnan 

#### Ehdotettu termi englanniksi   

Yunnan 

#### Perustelut ehdotukselle   

Kiinan maakunta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Dams and development in China : the moral economy of water and power / Bryan Tilt. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan nimi:** Eeva Henriksson 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** eeva.henriksson@helsinki.fi **Termiehdotus Fintossa:** [Yunnan](http://finto.fi/yse/fi/page/Y505105)

**Comment by jtuohini** [comment]
LCSH-vastine: Yunnan Sheng (China) [http://id.loc.gov/authorities/names/n81059860]

**Comment by mariaforsen** [comment]
Sv. Yunnan ET Yünnan
