### ISSUE TITLE
Ming-dynastia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5106]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ming-dynastia 

#### Ehdotettu termi englanniksi   

Ming dynasty, 1368-1644 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Perustelut ehdotukselle   

Kiinan historian aikakausi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

A political life in Ming China : a grand secretary and his times / John W. Dardess. 

**Ehdottajan nimi:** Eeva Henriksson 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** eeva.henriksson@helsinki.fi **Termiehdotus Fintossa:** [Ming-dynastia](http://finto.fi/yse/fi/page/Y505106)

**Comment by jtuohini** [comment]
LCSH-vastine: China--History--Ming dynasty, 1368-1644 [http://id.loc.gov/authorities/subjects/sh85024072]

**Comment by mariaforsen** [comment]
Sv. Mingdynastin
