### ISSUE TITLE
sivupersoonahäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5107]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sivupersoonahäiriöt 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Perustelut ehdotukselle   

Termiä sivupersoonat on jo ehdotettu aikaisemmin, ilmeisesti ehdotus ei mennyt läpi. Asiasana sivupersoonat löytyy jo Kaunokista, mutta tarvitsisin kyseistä asiasanaa tietokirjallisuuden kuvaamisessa. Jos ja kun tätä termiä ei voi käyttää, millä termillä pitäisi kuvata kirjaa, joka käsittelee sivupersoonia ja sivupersoonahäiriötä (dissosiatiivinen identiteettihäiriö)? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jänis ulvoo: Truddi Chasen 92 sivupersoonaa 

**Ehdottajan nimi:** Tiina Rajala 
**Ehdottajan organisaatio:** Porvoon kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** tiina.rajala@porvoo.fi **Termiehdotus Fintossa:** [sivupersoonahäiriöt](http://finto.fi/yse/fi/page/Y505107)

**Comment by mirmaid** [comment]
Lääketieteen termit: sivupersoonahäiriö: neuroottinen häiriö, josta kärsivällä henkilöllä ilmenee vähintään kaksi selvästi toisistaan eroavaa persoonallisuutta, niin että henkilön käyttäytyminen välillä muuttuu täysin. Myös FinMeSHissä.

https://fi.wikipedia.org/wiki/Dissosiatiivinen_identiteettih%C3%A4iri%C3%B6

http://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00361: Sivupersoonahäiriö (dissosiatiivinen identiteettihäiriö)

**Comment by mirmaid** [comment]
sivupersoonat https://github.com/Finto-ehdotus/YSE/issues/360

**Comment by mariaforsen** [comment]
Sv. dissociativ identitetsstörning, personlighetsklyvning, multipel personlighetsstörning.

**Comment by AuHo22** [comment]
LT dissosiaatiohäiriö

**Comment by YSA-kokous** [comment]
dissosiaatiohäiriö monikkoon, hyväksytään sivupersoonahäiriö

**Comment by mariaforsen** [comment]
Sv. 
-dissociativ störning -> dissociativa störningar 
-personlighetsklyvning ET multipel personlighetsstörning
