### ISSUE TITLE
paralipsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5109]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

paralipsi 

#### Ehdotettu termi englanniksi   

paralipsis 

#### Ehdotettu termi ruotsiksi   

paralips 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kerronta](http://www.yso.fi/onto/yso/p6895) 

#### Tarkoitusta täsmentävä selite   

Yhden tai useamman rakenne-elementin poisjättäminen tai sivuuttaminen tarinan jonkin ajanjakson kerronnasta. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimusta koskevan aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [paralipsi](http://finto.fi/yse/fi/page/Y505109)

**Comment by mirmaid** [comment]
Tieteen termipankki & Kirjallisuuden sanakirja: paralipsis

https://literarydevices.net/paralipsis/

Hups, ei ollut tarkoitus peukuttaa omaa kommenttiani...

**Comment by mirmaid** [comment]
Ei Melindassa/Artossa.

**Comment by mariaforsen** [comment]
Sv. paralips

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa paralipsis.
