### ISSUE TITLE
pentametri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5110]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pentametri 

#### Ehdotettu termi englanniksi   

pentameter 

#### Ehdotettu termi ruotsiksi   

pentameter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Tarkoitusta täsmentävä selite   

Viiteen viittaavasta nimestään huolimatta pentametri eli viisimittasäe koostuu kuudesta runojalasta, joista tosin kolmas ja kuudes ovat vaillinaisia. Pentametri rakentuu usein kahdesta puoliskosta, joissa kummassakin on kaksi daktyylia (tai spondeeta) ja lisäksi yksitavuinen runojalka. Pentametriä käytetään varsinkin elegisen distikonin jälkimmäisenä osana, ensimmäisen ollessa heksametri. Pentametriä edustaa esim. Koskenniemen runon "Hippokrene-lähteellä" (Elegioja, 1917) säe: "Sammuttaa se ei voi, kuoleva, sun janoas." Pentametri on yleinen myös silosäkeessä ja herooisessa kupletissa. (Termipankki) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimusta koskevan aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [pentametri](http://finto.fi/yse/fi/page/Y505110)

**Comment by mirmaid** [comment]
Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. pentameter
