### ISSUE TITLE
rikosromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5111]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rikosromaanit 

#### Ehdotettu termi englanniksi   

crime novels 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rikoskirjallisuus](http://www.yso.fi/onto/yso/p5088) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimusta koskevan aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [rikosromaanit](http://finto.fi/yse/fi/page/Y505111)

**Comment by mirmaid** [comment]
YSAssa ja Kaunokissa _rikoskirjallisuus_, Kaunokissa KT rikosromaanit.

**Comment by mariaforsen** [comment]
Sv. kriminalromaner = kriminalfiktion

**Comment by YSA-kokous** [comment]
KÄ rikoskirjallisuus

**Comment by mariaforsen** [comment]
Sv. kriminalromaner ANV kriminalfiktion
