### ISSUE TITLE
salapoliisiromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5112]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

detective novels 

#### Ehdotettu termi suomeksi   

salapoliisiromaanit 

#### Ehdotettu termi ruotsiksi   

detektivromaner 

#### Ehdotettu yläkäsite YSOssa (LT)   

[salapoliisikirjallisuus](http://www.yso.fi/onto/yso/p5086) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi, (joskin Kitussa yksikössä) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimusta koskevan aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [salapoliisiromaanit](http://finto.fi/yse/fi/page/Y505112)

**Comment by mirmaid** [comment]
YSAssa ja Kaunokissa muodossa _salapoliisikirjallisuus_ (Kaunokissa KT salapoliisiromaanit).

**Comment by krinay** [comment]
Melindassa on käytetty termiä salapoliisiromaanit 276 kertaa, enimmäkseen virheellisesti Kaunokki-terminä. Artossa termiä (salapoliisiromaani/t) on käytetty satoja kertoja sekä yksikösssä että monikossa.

**Comment by mariaforsen** [comment]
Sv. detektivromaner = detektivlitteratur

**Comment by YSA-kokous** [comment]
KÄ salapoliisikirjallisuus

**Comment by mariaforsen** [comment]
Sv. detektivromaner ANV detektivlitteratur
