### ISSUE TITLE
romanttinen viihdekirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5115]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

romanttinen viihdekirjallisuus 

#### Ehdotettu termi englanniksi   

romantic popular literature 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viihdekirjallisuus](http://www.yso.fi/onto/yso/p3) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimusta koskevan aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [romanttinen viihdekirjallisuus](http://finto.fi/yse/fi/page/Y505115)

**Comment by mirmaid** [comment]
Kaunokissa on _romanttinen fantasiakirjallisuus_ ja _romanttinen jännityskirjallisuus_ sekä _rakkausromaanit_. YSAssa on _rakkausromaanit_ ja _kioskikirjallisuus_.

Ei Melindassa

**Comment by mariaforsen** [comment]
Sv. romantisk populär/underhållningslitteratur? Mihin tarkalleen tämä viittaa, jos ei rakkausromaaneihin ja/tai kioskikirjallisuuteen? "Romantic popular literature"-haulla ei juuri osumia googlessa.

**Comment by siikaa** [comment]
Viihdekirjallisuus tarkoittanee jo romanttista kirjallisuutta. Ei ehkä tarpeen tämä termi?

**Comment by YSA-kokous** [comment]
KÄ viihdekirjallisuus, rakkausromaanit
