### ISSUE TITLE
trokee

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5116]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

trokee 

#### Ehdotettu termi ruotsiksi   

troke 

#### Ehdotettu termi englanniksi   

trochee 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Määritelmä kaksitavuinen laskeva runojalka, jossa painollista tavua seuraa painoton (kreikassa ja latinassa pitkä ja lyhyt) tavu
Selite Antiikin Kreikan runoudessa trokeeta on käytetty erityisesti lyriikassa ja draamassa. Kalevalamittaa voidaan luonnehtia nelipolviseksi trokeeksi.  (Termipankki) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimusta koskevan aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [trokee](http://finto.fi/yse/fi/page/Y505116)

**Comment by mirmaid** [comment]
YSAssa on kalevalamitta. Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. troké
