### ISSUE TITLE
ubuntu (filosofia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5119]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ubuntu (filosofia) 

#### Ehdotettu termi ruotsiksi   

ubuntu (filosofi) 

#### Ehdotettu termi englanniksi   

ubuntu (philosophy) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käsitteet](http://www.yso.fi/onto/yso/p2267) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2007009138> 

#### Perustelut ehdotukselle   

YSO jo tuntee käsitteen "Ubuntu" sen toisessa merkityksessä: käyttöjärjestelmät/43 Atk. Tietotekniikka. Ehdottaisin sekaannusten välttämisesksi sanaston täydentämistä termin vanhemmalla merkityksellä, mihin yhä useammin myös kirjallisuudessa törmää: Ubuntu (filosofia) 
https://en.wikipedia.org/wiki/Ubuntu_%28philosophy%29 

#### Tarkoitusta täsmentävä selite   

Wikipedia: Ubuntu tarkoittaa eettistä humaania filosofiaa uskollisuudesta ja suhteista toisiin ihmisiin. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Matti Lamminen 
**Ehdottajan organisaatio:** Helsingin yliopisto 
**Ehdottajan sähköpostiosoite:** matti.lamminen@helsinki.fi **Termiehdotus Fintossa:** [ubuntu (filosofia)](http://finto.fi/yse/fi/page/Y505119)

**Comment by mirmaid** [comment]
Muutamia kertoja Melindassa tässä merkityksessä.

https://fi.wikipedia.org/wiki/Ubuntu_%28filosofia%29

**Comment by mariaforsen** [comment]
Sv. ubuntu (filosofi)

**Comment by AuHo22** [comment]
Onko tämä nyt kuitenkin enemmän elämäntapa elämänfilosofian merkityksessä kuin varsinainen filosofinen rakennelma / tarkastelutapa perinteisessä akateemisessa merkityksessä. Eli vähän kuin hygge Tanskassa eli elämänasenne?

**Comment by tpusa** [comment]
Maailmalla (ja luultavasti pian myös meillä) ubuntu liittyy myös johtamisfilosofiaan. Lienee kuvailtavissa esim. ubuntu (filosofia) + johtaminen - termiparilla. Kts. esim. tietueet:
https://lccn.loc.gov/2016020395
https://lccn.loc.gov/2011348907

**Comment by mirmaid** [comment]
Wikipediassa tarkenne on kaikilla kielillä filosofia. Aatteet/ideologiat olisi varmaan myös oikein. 

In Southern Africa, it has come to be used as a term for a kind of humanist philosophy, ethic, or ideology, also known as Ubuntuism propagated in the Africanisation (transition to majority rule) process of these countries during the 1980s and 1990s.
