### ISSUE TITLE
työvoimahallinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5120]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työvoimahallinto](http://www.yso.fi/onto/ysa/Y99831) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin työhallinto. 

#### Perustelut ehdotukselle   

Termimuutos perustuu ministeriön nimenmuutokseen v. 1989: Työministeriö perustettiin vuonna 1970, jolloin silloinen Kulkulaitosten ja yleisten töiden ministeriö jaettiin kahtia. Kahtiajaossa syntyivät Liikenneministeriö ja Työvoimaministeriö, jonka nimi lyheni Työministeriöksi 1. kesäkuuta 1989. Työministeriöstä tuli osa työ- ja elinkeinoministeriötä vuonna 2008.

Myös muotoa työ- ja elinkeinohallinto käytetään, eikä muoto työvoimahallinto ole sekään kadonnut (esim. https://ek.fi/ajankohtaista/uutiset/2015/05/29/tyovoimahallinto-uusiksi-tarkeinta-tyon-kysynnan-ja-tarjonnan-kohtaaminen/, http://yle.fi/uutiset/3-8327023) 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
EKS:ssä on työvoimahallinto, ei työhallinto. Google: työvoimahallinto n. 8000, työhallinto n. 7300, työ- ja elinkeinohallinto n. 3700.

**Comment by mariaforsen** [comment]
TEPAssa työhallinto 5 kertaa ja kerran MOTissa (työvoimahallinto 0).  Arbetsförvaltning enemmän käytetty.

**Comment by YSA-kokous** [comment]
työhallinto
