### ISSUE TITLE
kuitupellava

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5122]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuitupellava 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pellava](http://www.yso.fi/onto/yso/p16951) 

#### Assosiatiiviset (RT)   

[kuitukasvit](http://www.yso.fi/onto/yso/p10436) 

#### exactMatch   

Kassu : https://finto.fi/kassu/fi/page/k96 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

YSAssa on öljypellava. Pellavasta on jalostettu lajikkeita oljyn ja kuidun tuotantoa varten. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arro 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kuitupellava](http://finto.fi/yse/fi/page/Y505122)

**Comment by mariaforsen** [comment]
Sv.  spånadslin

**Comment by satuniininen** [comment]
engl. fibre flax
