### ISSUE TITLE
yksityistyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5123]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yksityistyminen](http://www.yso.fi/onto/ysa/Y100417) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko huomautus tai muu selkeyttävä tekijä tarpeen? 

#### Perustelut ehdotukselle   

On ryhmässä 60 ja ruotsiksi (sekä englanniksi) sulkutarkenne "sosiologia". Melindassa käytetty myös toisessa merkityksessä (ks. yksityistäminen), esim. Uuden valtionosuusjärjestelmän vaikutukset terveydenhuollon yksityistämiskehitykseen : esimerkkinä neljä Kalajokilaakson kuntaa / Marko Peltoniemi ja Mika Punkari. Eli ihan eri merkityksessä kuin esim. Omassa huoneessa : yksityiselämän historiaa renessanssista valistukseen / toimittaneet Philippe Ariès, Georges Duby, Roger Chartier ; suomentanut Johanna Ilmakunnas (johon nyt käännökset viittaavat). 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Tarkenne on varmaankin paikallaan tässä.

**Comment by satuniininen** [comment]
sopisiko yksityistyminen (yksityiselämä) ?

**Comment by YSA-kokous** [comment]
yksityistyminen (sosiologia)
