### ISSUE TITLE
arkeobotaniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5124]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

arkeobotaniikka 

#### Ehdotettu termi englanniksi   

archaeobotany 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvitiede](http://www.yso.fi/onto/yso/p4655) 

#### Assosiatiiviset (RT)   

[arkeologia](http://www.yso.fi/onto/yso/p1265) 

#### exactMatch   

MAO : <http://www.yso.fi/onto/mao/p2104> 

#### Vaihtoehtoiset termit ja ilmaisut   

kasviarkeologia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

Arkeobotaniikka eli kasviarkeologia yhdistää kasvitiedettä, arkeologiaa ja historiaa, ja tutkii hyötykasveja sekä ihmisten ja kasvien vuorovaikutusta menneisyydessä. 
Lähde: Väitöskirja: Cloister, manor and botanic gardens in medieval and early modern Finland and Sweden An archaeobotanical approach to garden history
https://helda.helsinki.fi/handle/10138/177559 

#### Perustelut ehdotukselle   

Väitöskirjassa
https://helda.helsinki.fi/handle/10138/177559 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/177559 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [arkeobotaniikka](http://finto.fi/yse/fi/page/Y505124)

**Comment by mirmaid** [comment]
YSAssa on _paleobotaniikka_.

https://en.wikipedia.org/wiki/Paleoethnobotany
https://en.wikipedia.org/wiki/Paleobotany

**Comment by mariaforsen** [comment]
Sv. arkeobotanik

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa kasviarkeologia.

**Comment by YSA-kokous** [comment]
arkeologia myös LT
