### ISSUE TITLE
väylät -- atk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5125]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väylät -- atk](http://www.yso.fi/onto/ysa/Y106521) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

väylät -- tietotekniikka 

#### Perustelut ehdotukselle   

Atk on vanhanaikaiselta kuulostava termi. Wikipedia suosittaa tietotekniikkaa. 

#### Ehdottaja   

Anneli Korhonen 

#### Ehdottajan organisaatio   

Hämeen ammattikorkeakoulun kirjasto 

#### Ehdottajan sähköpostiosoite   

anneli.korhonen@hamk.fi

**Comment by mirmaid** [comment]
YSOssa jo muutettu.

**Comment by LeKorsu** [comment]
Eli tietotekniikka sulkutarkenteeksi ja ketjun purku? Kannatan.

**Comment by YSA-kokous** [comment]
väylät (tietotekniikka)

**Comment by mariaforsen** [comment]
Sv. bussledningar  > databussar ET bussar (datateknik)
