### ISSUE TITLE
syötävät kukat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5126]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syötävät kukat 

#### Ehdotettu termi englanniksi   

edible flowers 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kukat (koristekasvit)](http://www.yso.fi/onto/yso/p488) 

#### Assosiatiiviset (RT)   

[hyötykasvit](http://www.yso.fi/onto/yso/p438) 

#### Vaihtoehtoiset termit ja ilmaisut   

syötävät kasvit 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Edible_flower 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-951-23-6184-7 Kukkamakuja 

**Ehdottajan nimi:** Kaija Karjalainen 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** kaija.karjalainen@btj.fi **Termiehdotus Fintossa:** [syötävät kukat](http://finto.fi/yse/fi/page/Y505126)

**Comment by jtuohini** [comment]
Tarkoittaako ihmisten ruoaksi soveltuvia kukkasia vai eläinten luonnosta ravinnokseen nauttimia? Jos edellisiä, niin ehdotettu LT-suhde on harhaanjohtava, kun viitttaa koristekasveihin eli varsinaisten hyötykasvien vastakohtaan.

**Comment by mirmaid** [comment]
Tarkoittaa ihmisten syötäviä, mutta LT olisi ehkä vielä jännempi jos kyse olisi eläinten _luonnosta_ syömistä kukista :grinning:. Ihmisten ruoassa näillä varmaan tyypillisesti on tarkoituskin olla enemmän koristeina kuin makunsa takia. 

Termi ok, LT mietittävä kukka/kukat/jotain muuta.

**Comment by mariaforsen** [comment]
Sv.  ätliga blommor ET ätbara blommor

**Comment by AuHo22** [comment]
Siinä on nyt varmaankin LT ja RT -termit tarkoitettu toisin päin. Villivihannekset otettiin aiemmin, myrkkysienet on myös. Lähellä ehkä joitain maustekasveja myös. Keittiömaailman trendejä.
