### ISSUE TITLE
kimchi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5127]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kimchi 

#### Ehdotettu termi ruotsiksi   

kimchi 

#### Ehdotettu termi englanniksi   

kimchi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ruoat (ruokalajit)](http://www.yso.fi/onto/yso/p368) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85072354> 
Wikipedia : https://fi.wikipedia.org/wiki/Kimchi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pieni kimchikirja 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [kimchi](http://finto.fi/yse/fi/page/Y505127)

**Comment by jtuohini** [comment]
Pitäisikö LT-termin kuitenkin olla "pikkelssit" (tai kyseisen termin olla ainakin RT-suhteisena), kun kimchi valmistetaan pikkelöimällä?

**Comment by mariaforsen** [comment]
Sv. kimchi

**Comment by Elmukelmu** [comment]
Kimchi valmistetaan hapattamalla. Se on siis korealainen hapankaali, ei pikkelssi.
