### ISSUE TITLE
noir-kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5129]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

noir-kirjallisuus 

#### Ehdotettu termi englanniksi   

noir fiction 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kertomakirjallisuus](http://www.yso.fi/onto/yso/p2128) 

#### Tarkoitusta täsmentävä selite   

Noir fiction (or roman noir) is a literary genre closely related to hardboiled genre with a distinction that the protagonist is not a detective, but instead either a victim, a suspect, or a perpetrator. (Wikipedia) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimuksellisen aineiston kuvailussa 

**Ehdottajan organisaatio:** SKS 
**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [noir-kirjallisuus](http://finto.fi/yse/fi/page/Y505129)

**Comment by mirmaid** [comment]
Ei Kaunokissa/Melindassa, Googlellakin vain muutama viite suomeksi.

**Comment by mariaforsen** [comment]
Sv. noirlitteratur? Ei vakiintunut.

**Comment by YSA-kokous** [comment]
KÄ rikoskirjallisuus
