### ISSUE TITLE
pehmodekkarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5130]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pehmodekkarit 

#### Ehdotettu termi englanniksi   

cozy mysteries 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rikoskirjallisuus](http://www.yso.fi/onto/yso/p5088) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Tarkoitusta täsmentävä selite   

Cozy mysteries, also referred to as "cozies", are a subgenre of crime fiction in which sex and violence are downplayed or treated humorously, and the crime and detection take place in a small, socially intimate community. (Wikipedia) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimuksellisen aineiston kuvailussa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [pehmodekkarit](http://finto.fi/yse/fi/page/Y505130)

**Comment by mirmaid** [comment]
Ei Kaunokissa/Melindassa

**Comment by mariaforsen** [comment]
Sv. mysdeckare ET mjukisdeckare ET mysiga deckare
