### ISSUE TITLE
renga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5131]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

renga 

#### Ehdotettu termi ruotsiksi   

renga 

#### Ehdotettu termi englanniksi   

renga 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lyriikka](http://www.yso.fi/onto/yso/p1365) 

#### Tarkoitusta täsmentävä selite   

Renga  on japanilainen ketjurunouden muoto. Sen kirjoittamiseen osallistuu kaksi tai useampi henkilö. Renga muodostuu useammasta kahden säkeistön kokonaisuudesta, niin että ensimmäistä ja viimeistä säkeistöä lukuun ottamatta jokainen säkeistö kuuluu kahteen runoon. (Wikipedia) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimuksellisen aineiston kuvailussa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [renga](http://finto.fi/yse/fi/page/Y505131)

**Comment by amssi** [comment]
Kai tämänkin pitäisi olla monikossa, kuten tankat, vaikka yksikköä ehdotin?

**Comment by mariaforsen** [comment]
Sv. renga

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa rengat.
