### ISSUE TITLE
määräaikainen työ/määräaikaiset työsuhteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5133]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

määräaikainen työ/määräaikaiset työsuhteet 

#### Ehdotettu termi ruotsiksi   

visstidsarbete/visstidsanställningar 

#### Ehdotettu termi englanniksi   

fixed-term employment? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

#### Perustelut ehdotukselle   

Sanastossa on ennestään pätkätyö=visstidsanställning ja määräaikaisuus=tidsbegränsning. Pätkätyö on oikeastaan korttidsarbete, eikä ainakaan visstidsanställning (koska viimeksi mainittu ei välttämättä ole kovin lyhyt, vaan tarkoittaa että on päätetty milloin alkaa ja loppuu..), mutta ennen kuin teen muutoksia ruotsiksi täytyy selvittää tarkemmin miten YSAssa halutaan. 

Esim. ESK:ssa on määräaikainen työ KT pätkätyö. Fintossa TSR: määräaikainen työ, määräaikainen työsuhde, LIITO: määräaikainen työsuhde, JUHO ja TERO: määräaikaiset työsuhteet. Pätkätyö löytyy myös erillisenä pääterminä näissä sanastoissa. 

YSAn määräaikaisuus taas on 00-ryhmässä, eikä sitä voida ruotsiksi kääntää tällä termillä ellei suomeksi selkeästi määritellä että on kyse nimenomaan vain työstä/työsuhteista. 

Kielitoimiston sanakirja: pätkätyö: "määräaikaisista, lyhyistä työsuhteista, jotka us. eivät kartuta työsuhteen keston perusteella laskettavia eläke-, loma- tms. etuuksia." 

Määräaikainen työ: "Määräaikaisella työsopimuksella tarkoitetaan sellaista työsopimusta, jossa on sovittu, että sopimus on voimassa vain tietyn kalenteriajan tai että sopimus on muuten tehty kestämään vain tietyn määräaajan."

Ks. myös esim. http://www.mediesprak.fi/sprakrad.aspx?id=501#.WOY2G2clGpo 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Visstidsanställningar i Finland och Sverige ur flexicurity-perspektiv : en komparativ studie / Jenny Vestlund 

**Ehdottajan nimi:** Maria Forsén 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [määräaikainen työ/määräaikaiset työsuhteet](http://finto.fi/yse/fi/page/Y505133)

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa määräaikainen työsuhde.

**Comment by mariaforsen** [comment]
Sv. 
-visstidsanställning ET anställningsförhållande för viss tid ET tidsbegränsad anställning ET tidsbunden anställning ET tidsbundet arbetsförhållande ET visstidsarbete  

-visstidsanställning (=pätkätyö) > korttidsarbete ET kortjobb ET korttidsjobb ET snuttjobb
