### ISSUE TITLE
asessorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5134]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asessorit](http://www.yso.fi/onto/ysa/Y129626) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite pitäisi jakaa kolmeen:
asessorit (tuomiokapitulit)
hovioikeuden asessorit
asessorit (arvonimet) 

#### Perustelut ehdotukselle   

Kielitoimiston määritelmän mukaan asessori on eräs kollegiaalisen oikeus- t. hallintoviraston virkamies; tuomiokapitulin jäsen; eräs arvonimi.

Melindan 14 käyttötapausta jakautuu seuraavasti: 
tuomiokapitulin jäsen 6 kpl
hovioikeuden asessori 5 kpl
arvonimi 1 kpl
ei tietoa 2 kpl
tuomiokapitulin pappisasessoreista löytyy uuttakin aineistoa, muut käytöt aikajänteellä 1674-1939 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
Voisiko tehdä asessorit (tuomiokapitulit) KÄ pappisasessorit?

**Comment by mariaforsen** [comment]
https://evl.fi/sanasto/-/glossary/word/Asessori

**Comment by mirmaid** [comment]
Eli sittenkin asessorit (tuomiokapitulit).

**Comment by mariaforsen** [comment]
Sv.
-assessorer (domkapitel)
-hovrättsassessorer
-assessorer (hederstitlar)

**Comment by MikkoAleksanteri** [comment]
(Oikeudellisia) asessoreja on hovioikeuden lisäksi muissakin tuomioistuimissa. 

_Hovioikeudessa, hallinto-oikeudessa, markkinaoikeudessa, työtuomioistuimessa ja vakuutusoikeudessa voi olla koulutustarkoituksessa määräajaksi täytettäviä asessorin virkoja. Virkaan nimitetään kolmeksi vuodeksi._ https://oikeus.fi/tuomioistuimet/fi/index/lautakunnat/tuomarinkoulutuslautakunta/asessorinviranhaku.html

Tulisiko tämä käsite kuitenkin laajentaa näihin kaikkiin? Tarkenne esim. _asessorit (tuomioistuimet)_

**Comment by ilona-x** [comment]
asessorit on jo korjattu Melindaan
