### ISSUE TITLE
idealismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5135]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[idealismi](http://www.yso.fi/onto/ysa/Y95483) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

käsite pitäisi jakaa kahteen:
1. idealismi (filosofia) KT filosofinen idealismi, ontologinen idealismi
2. idealismi (asenteet) 

#### Perustelut ehdotukselle   

Kyseessä on kaksi eri käsitettä. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by satuniininen** [comment]
Muutama esimerkki, miten jako realisoituisi Melinda-aineistoissa :

**idealismi (filosofia)**

- The spirit of modern philosophy : an essay in the form of lectures / by Josiah Royce.
- The relevance of Romanticism : essays on German romantic philosophy / edited by Dalia Nassar.
- Mythology, madness, and laughter : subjectivity in German idealism / Markus Gabriel and Slavoj Žižek.

**idealismi (asenteet)**

- Change your life, change the world : a spiritual guide to living now / Ryuho Okawa ;
- Cultural chaos : journalism, news, and power in a globalised world / Brian McNair.
- Fidel & Che : ystävät vallankumouksessa / Simon Reid-Henry

**Comment by mariaforsen** [comment]
Sv.
-idealism (filosofi)
-idealism (attityder)
