### ISSUE TITLE
siirtymäaika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5136]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[siirtymäaika](http://www.yso.fi/onto/ysa/Y113765) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

siirtymäajat 

#### Perustelut ehdotukselle   

Asioilla voi olla useita siirtymäaikoja. 

#### Ehdottaja   

JUHO-työryhmä 

#### Ehdottajan organisaatio   

VNHY 

#### Ehdottajan sähköpostiosoite   

eeva-liisa.tuomi-kyro@okv.fi

**Comment by mirmaid** [comment]
YSAssa on paljon aika-päätteisiä termejä jotka voisivat varmaankin myös olla monikossa: _läpimenoaika, matka-aika, määräaika, puoliintumisaika, vaikutusaika, vasteaika_.

**Comment by mirmaid** [comment]
Monikossa nyt: _metsästysajat, rauhoitusajat, pula-ajat, vuodenajat, vuorokaudenajat_.

**Comment by YSA-kokous** [comment]
Tutkitaan lisää, seuraava kokous.

**Comment by ilona-x** [comment]
Melinda-viitteistä suurin osa käsittelee jonkin yksittäisen tapahtuman esim. tietyn lain voimaantulon siirtyäaikaa tai euron käyttöönoton siirtymäaikaa, joten yksikkömuoto tuntuu näissä viitteissä monikkoa paremmalta.
