### ISSUE TITLE
siirtymätalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5137]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[siirtymätalous](http://www.yso.fi/onto/ysa/Y111452) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

siirtymätaloudet 

#### Perustelut ehdotukselle   

miksi yksikössä? monikkomuoto olisi parempi. 

#### Ehdottaja   

JUHO-työryhmä 

#### Ehdottajan organisaatio   

VNHY 

#### Ehdottajan sähköpostiosoite   

eeva-liisa.tuomi-kyro@okv.fi

**Comment by mirmaid** [comment]
EKS:ssa yksikössä. 

Useimmiten monikossa "organisaatio"-tyyppisesti, mutta on mahdollista tulkita myös suunnitelmatalouden ja markkinatalouden tyyppisesti talousjärjestelmäksi: "Suomen teollisuudessa oli siirtymätalouden vaihe", "Bulgaria elää siirtymätaloudessa".

**Comment by mirmaid** [comment]
Monikossa YSAssa _kotitaloudet, laitostaloudet_ ja _suurtaloudet_.

**Comment by YSA-kokous** [comment]
Ei muutosta
