### ISSUE TITLE
strategia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5138]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[strategia](http://www.yso.fi/onto/ysa/Y104413) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

strategiat 

#### Perustelut ehdotukselle   

miksi yksikkö - monikko parempi 

#### Ehdottaja   

JUHO-työryhmä 

#### Ehdottajan organisaatio   

VNHY 

#### Ehdottajan sähköpostiosoite   

eeva-liisa.tuomi-kyro@okv.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa runsaasti myös monikossa. Sotataidon yhteydessä yksikkö tuntuu paremmalta (?), muuten monikko olisi usein vähintään yhtä hyvä kuin yksikkö.

**Comment by AuHo22** [comment]
Voidaanko strategia yksikössä jättää sotataidon yhteyteen: ks. taktiikka. Muitakin tämänkaltaisia on: teoria ja käytäntö, sen lisäksi teoriat.

**Comment by mirmaid** [comment]
^ Sitten tarvittaisiin sulkutarkenteet, tai suppeampi termi kun on kyse sotataidosta (PUHOssa on KT sotilasstrategia, mutta en tiedä sopisiko se päätermiksi).

**Comment by mariaforsen** [comment]
En lisäisi näitä ongelmallisia yksikkö+monikko-tapauksia. Siinä tapauksessa varmaan selkeämpää ottaa esim. sotilas/sotastrategia ihan erillisenä.

**Comment by EsaMPKK** [comment]
strategia (sotataito) ?!

**Comment by YSA-kokous** [comment]
strategiat, sotilasstrategia

**Comment by mariaforsen** [comment]
Sv. strategier, militärstrategi
