### ISSUE TITLE
sopimuspalkka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5139]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sopimuspalkka](http://www.yso.fi/onto/ysa/Y103851) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

sopimuspalkat 

#### Perustelut ehdotukselle   

sopimuspalkka viittaa sopimuspalkka -järjestelmään 

#### Ehdottaja   

JUHO-työryhmä 

#### Ehdottajan organisaatio   

VNHY 

#### Ehdottajan sähköpostiosoite   

eeva-liisa.tuomi-kyro@okv.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa vain kerran, silloin monikossa. Muut palkkatyypit ovat YSAssa yksikössä, samoin JUHOssa?

**Comment by YSA-kokous** [comment]
Ei muutosta
