### ISSUE TITLE
tarjouskilpailu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5140]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tarjouskilpailu](http://www.yso.fi/onto/ysa/Y113768) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarjouskilpailut 

#### Perustelut ehdotukselle   

miksi yksikkö - monikko olisi parempi 

#### Ehdottaja   

JUHO-työryhmä 

#### Ehdottajan organisaatio   

VNHY 

#### Ehdottajan sähköpostiosoite   

eeva-liisa.tuomi-kyro@okv.fi

**Comment by mirmaid** [comment]
FinMeSHissä monikko. Melindassa 3 kertaa monikossa (222 kertaa yksikössä).

EKS:ssa yksikössä.

Yksikkömuoto on ehkä aikanaan valittu koska tarjouskilpailua on ajateltu menettelynä enemmän kuin tapahtumina.

Kielitoimiston sanakirja: _menettely jossa pyydetään tarjouksia usealta tuotteen t. palvelun toimittajalta._

**Comment by YSA-kokous** [comment]
Ei muutosta
