### ISSUE TITLE
jyrsimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5141]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jyrsimet](http://www.yso.fi/onto/ysa/Y102012) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite pitäisi jakaa kahteen:
1. jyrsimet (maamuokkauskoneet)
2. jyrsimet (työstökoneet) 

#### Perustelut ehdotukselle   

Tässä on kyseessä hyvin erityyppiset laitteet

maanmuokkauskone: 
https://www.k-maatalous.fi/tuotteet/maatalouskoneet/jyrsimet/
http://www.hondapower.fi/mallisto/jyrsimet

työstökone: 
https://www.bosch-professional.com/fi/fi/jyrsimet-101334-ocs-c/ 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@gmail.com

**Comment by mariaforsen** [comment]
Sv. 
-jordfräsar ET fräsar (jordbearbetningsmaskiner) 
-fräsar (verktygsmaskiner)
