### ISSUE TITLE
TK-komppaniat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5142]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

TK-komppaniat 

#### Vaihtoehtoiset termit ja ilmaisut   

tiedotuskomppaniat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/TK-komppania 

#### Perustelut ehdotukselle   

Yleisesti tunnettu käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/julkaiseminen-kielletty 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [TK-komppaniat](http://finto.fi/yse/fi/page/Y505142)

**Comment by mirmaid** [comment]
Eikö ennemmin _tiedotuskomppaniat_?

**Comment by mariaforsen** [comment]
Sv. informationskompanier

**Comment by EsaMPKK** [comment]
TK-komppaniat on tosiaan ongelmallinen, koska TK:n K tarkoittaa jo komppaniaa. Käsitteellä tiedotuskomppaniat ei ole tällaista toisto-ongelmaa.

**Comment by satuniininen** [comment]
Engl. propaganda companies?

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa tiedotuskomppaniat.
