### ISSUE TITLE
TK-miehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5143]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

TK-miehet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/TK-komppania 

#### Perustelut ehdotukselle   

Yleisesti tunnettu käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/julkaiseminen-kielletty 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [TK-miehet](http://finto.fi/yse/fi/page/Y505143)

**Comment by jtuohini** [comment]
Ja LT-suhteiset termit olisivat varmaankin **sotilaat** ja **toimittajat**.

**Comment by mariaforsen** [comment]
Sv. "propagandasoldater"?

**Comment by AuHo22** [comment]
On tarvittu termi - tk-kuvaajista /-piirtäjistä on ollut teoksia. Tärkeämpi termi vielä kuin komppaniat.

**Comment by satuniininen** [comment]
Mitenköhön englanniksi? Members of the Propaganda Company?

**Comment by YSA-kokous** [comment]
KÄ tiedotuskomppaniat
