### ISSUE TITLE
oliivi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5144]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oliivi 

#### Ehdotettu termi englanniksi   

olive 

#### Ehdotettu termi ruotsiksi   

oliv 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hedelmät](http://www.yso.fi/onto/yso/p4647) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Vapaan indeksoinnin sana samaan tapaan kuin viikuna jne. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mirja von Knorring: Oliiviöljy 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [oliivi](http://finto.fi/yse/fi/page/Y505144)

**Comment by mariaforsen** [comment]
Sv. oliv
