### ISSUE TITLE
ohjaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5145]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ohjaus](http://www.yso.fi/onto/ysa/Y103727) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko samalla tavalla kuin YSOssa, eli: 
ohjaus (neuvominen)
ohjaus (suuntaaminen)
ohjaus (taide) 

#### Perustelut ehdotukselle   

Tällä tavalla saadaan käsitetaso esille ja ruotsiksi on eri termejä näille eri merkityksille. 
Ks. "ohjata" Kielitoimiston sanakirjassa. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: ohjata:

1. saattaa jk kulkemaan haluttuun suuntaan, pitää jk oikeassa suunnassa, säädellä jnk kulkua.
a. kulkuneuvon tms. toiminnan hallinnasta; kuljettaa. _Ohjata autoa, venettä, lentokonetta. Laivaa ohjataan peräsimellä. Ohjata auto portista sisään. Ohjata sokeaa käsipuolesta._
Mer. vastata aluksen kulusta, navigoida. _Päällikkö ohjaa alusta._
b. yl. liikkuvan esineen, virtaavan aineen tms. kulkusuunnan säätämisestä. _Liikenne ohjattiin sivutielle. Tukkeja ohjataan puomeilla. Kouru ohjaa sadevedet viemäriin. Ohjasi vanhuksen vapisevaa kättä._
Kuv. _Rahavirtojen ohjaaminen._
c. vars. tekn. säädellä, hallita jnk laitteen, järjestelmän tms. toimintaa. _Tietokoneen ohjaamat liikennevalot._ _Kauko-, tutkaohjattu_ paremmin: kauko-, tutkaohjauksinen.
Kuv. _Hänen tekojaan ohjaa kylmä järki._

2. tietä t. suuntaa näyttäen neuvoa menemään jhk, johdattaa, opastaa, johtaa, suunnata. _Airuet ohjaavat yleisön paikoilleen. Ohjasi autoilijan lähimmälle huoltamolle. Koiran vainu ohjasi sen hirven jäljille. Ohjata askeleensa jhk._
Kuv. _Yritti ohjata lapsen huomion toisaalle. Arka ja helposti ohjattavissa._

3. saattaa jk ohjeilla sujumaan halutulla tavalla, opastaa, neuvoa, johtaa. _Liikennettä ohjaava poliisi. Ohjata jkn opintoja. Ihmisten ohjaaminen terveisiin elintapoihin. Ohjattu harjoittelu._

4. suunnitella ja valmistaa näytelmä, elokuva, televisioesitys tms. esityskuntoon. _Ohjaa Tampereen teatterissa. Edvin Laineen ohjaama Tuntematon sotilas. Ohjata voimisteluesitys. Ohjasi televisiolle MM-kisat._

**Comment by mirmaid** [comment]
_Ohjaajat_ jaettiin aikaisemmin tarkenteilla _(taiteet ja media)_ sekä _(kasvatus ja opastus)_. Ainakin ensinmainittu olisi varmaankin myös tässä toimiva.

Ohjaus (neuvominen) -merkitykselle YSOn tarkenne on ehkä ainakin yksinään liian konkreettinen, ja sanastossa on jo termi _neuvonta_. Tarkenne _(kasvatus ja opastus)_ sopii osaan aineistoista, mutta _kasvatus_ ei sovellu aina (esim. _Iäkäs tyypin 2 diabeetikko kotona: opas kotihoidon ammattilaisille ja läheisille_). Yhdistelmä _(neuvonta ja opastus)_ toimisi varmaankin melko usein.

**Comment by mirmaid** [comment]
Kolmannessa merkityksessä (ruots. styrning) tarkenne (suuntaaminen) on liian konkreettinen ja suppea. Käyttötapaukset vaihtelevat esim. veneen ohjauksesta tai robotiikasta kokonaisen laitoksen tai sektorin ohjaukseen.

**Comment by mirmaid** [comment]
Tai _ohjaus (hallinta ja säätely)_ :smile:. Ellei sitten haluta vielä jakaa jotenkin _ohjaus (tekniikka)_ ja _ohjaus (hallinta/hallinto/hallinnointi...)_ - tätä on aika vähän verrattuna _(neuvonta ja opastus)_ -merkitykseen, mutta ovat kyllä vähän erityyppisiä silti keskenään.

**Comment by YSA-kokous** [comment]
ohjaus (taiteet ja media)
ohjaus (neuvonta ja opastus) 
ohjaus (tekniikka tms.)
ohjaus (hallinto/hallinnointi/organisointi tms.) 

Määritelmät

**Comment by mirmaid** [comment]
Jaettu:
ohjaus (taiteet ja media)
ohjaus (neuvonta ja opastus)
**ohjaus (hallinta), johon kuuluvat päätetyn jaon kaksi viimeistä ryhmää**

Määritelmiä ei lisätty toistaiseksi, vaikea muotoilla sellaisia jotka eivät olisi niin ympäripyöreitä etteivät tarkoita enää juuri mitään... 
ohjaus (neuvonta ja opastus): _henkilön tai ryhmän opastus ja neuvominen jossakin asiassa_
ohjaus (taiteet ja media): _taiteellisessa tai mediatuotannossa esitys- tai ohjelmakokonaisuudesta vastaaminen_
ohjaus (hallinta): _esim. laitteen, toiminnan tai kokonaisuuden hallinta tai säätely tjsp..._
**Tarvitaanko välttämättä?**

**Comment by mariaforsen** [comment]
Nyt siis ohjaus (hallinta)=styrning ja se on ruotsiksi ehdottomasti tarpeen. Määritelmiä ei tarvita ainakaan ruotsiksi.

**Comment by satuniininen** [comment]
Mielestäni pelkät sulkutarkenteet ovat riittävän selkeät.

**Comment by YSA-kokous** [comment]
Ei määritelmiä.
