### ISSUE TITLE
parantaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5146]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[parantaminen](http://www.yso.fi/onto/ysa/Y113399) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite pitäisi jakaa kahteen. Ysossa sulkutarkenteina ovat parantaminen (paremmaksi muuttaminen) ja parantaminen (terveys) 

#### Perustelut ehdotukselle   

Kielitoimiston mukaan käsitteellä on kaksi merkitystä:
1. tehdä paremmaksi, kohentaa, korjata, oikaista, elvyttää, tehostaa, uudistaa, auttaa, lisätä.
2. tehdä tervee(mmä)ksi, tervehdyttää. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
_Parantaminen (terveys)_ on varmaankin ok, vaikka samaa aihepiiriä kuvaavia sanoja on muutenkin useita. Toinen voisi ehkä olla myös _parantaminen (kehittäminen)_? Tosin se ei ihan täysin poissulje terveys-merkitystä, mutta sama ongelma on nykyisessäkin tarkenteessa.

**Comment by mariaforsen** [comment]
Parantamista tehdä paremmaksi-merkityksessä voi varmaan olla aika monenlaista, jos esim. parantaa maata tms. "fyysisempää" niin sitä ei varmaan mielletä kehittämiseksi. Minusta YSOn tarkenteet ovat selkeitä.

**Comment by mirmaid** [comment]
^ Totta (tosin löytyy _maanparannus_-termikin). Toisaalta myös terveyttä voi ajatella muutettavan paremmaksi, joten ihan täydellinen sekään tarkenne ei ole.

**Comment by mirmaid** [comment]
Melindan 50 ensimmäisen teoksen (muuta kuin rajatietoa) voimalla parannettavia ovat
urheilusuoritus
teksti
energiatehokkuus
liukoisuus
laatu
prosessi
luokkatyöskentely
suorityskyky
työssä jaksaminen
ilmanvaihto
rikolliset
kasvualusta
tuottavuus

Ihan kaikista rajatieto-kirjoistakaan ei voi sanoa käsitelläänkö terveyden parantamista vai jotain muuta elämän parantamista.

**Comment by YSA-kokous** [comment]
parantaminen (terveys)
parantaminen (paremmaksi muuttaminen)

**Comment by mariaforsen** [comment]
Sv.
-helande
-förbättring
