### ISSUE TITLE
piirustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5147]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[piirustukset](http://www.yso.fi/onto/ysa/Y103941) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite pitäisi jakaa kahteen, jotta saadaan erotettua taidepiirustukset muista piirustuksista (teknisistä yms. suunnittelupiirustuksista)

Tarkenteiksi ehdotettu:
piirustukset (tekniset)
tekniset piirustukset [huom. onko liian rajaaava?]
piirustukset (suunnittelu)

piirustukset (taide)
piirustukset (taideteokset) 

#### Perustelut ehdotukselle   

Luonteeltaan erilaisia piirustuksia, eli kyseessä kaksi eri käsitettä. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa on myös piirustus = ritning (?)

**Comment by mirmaid** [comment]
Kannattaisin ehdotusta _piirustukset (taide)_ ja _tekniset piirustukset_, jos se on mahdollinen. Miten esim. tämä kirja: _Jälke(e)ni : kestävä ja eheyttävä suunnitteluprosessi_ / Anna Kitinoja. (kumpi termi on oikea?)

**Comment by mariaforsen** [comment]
Piirustus=ritning on ruotsiksi ongelmalistalla (vaatii toimenpiteitä). Ruotsin kannalta on ritning-sanassa suunnittelu melko olennainen piirre, eli ruotsin kannalta täsmäisi hyvin jos olisi piirustukset (suunnittelu) tai (tekniset). Muuten jää ritningar-sana pois (ja sitä löytyy tietty myös esim. SAOssa). Mutta pääasia on tietty että käsite jaetaan.

**Comment by tpusa** [comment]
Toimisiko ruotsiksi "teckningar" - piirustukset (taide) ja "ritningar" - tekniset piirustukset?

**Comment by mirmaid** [comment]
http://wiki.narc.fi/portti/index.php/Piirustukset

**Comment by krinay** [comment]
Tässä on jälleen myös yksikkö/monikko-aspekti. YSAssahan on jo _tekninen piirustus_ ja sen allla kartanpiirustus, koneenpiirustus, rakennuspiirustus ja sähköpiirustus.

**Comment by mariaforsen** [comment]
Ritning="är en skalenlig teckning av ett föremål som visar dess form, proportioner och dimensioner", eli ei välttämättä aina varsinaisesti "tekninen". Voi olla myös esim. puutarhasta, esineistä, teistä jne. 

"Tekninen piirustus" viittaa kai toimintaan, sen sijaan kun monikkomuoto konkreettisiin piirustuksiin.

**Comment by satuniininen** [comment]
^ Juuri näin, yksikölliset ovat toiminta-hierarkiassa. Pitäisikö _tekninen piirustus_ muuttaa muotoon _tekninen piirtäminen_? Tai lisätä ainakin ohjaustermiksi? Ks. https://fi.wikipedia.org/wiki/Tekninen_piirt%C3%A4minen

**Comment by tpalonen** [comment]
Muidenkin *piirustus-termien käytettävän muodon voisi selkeyden vuoksi muuttaa muotoon *piirtäminen: tekninen piirustus, piirustus, elävän mallin piirustus. Muotipiirustuksen kohdalla muutos ei ehkä kuitenkaan toimisi.

**Comment by mirmaid** [comment]
Onko esim. lintukirjan piirretyt kuvat teckningar vai ritningar? Sanakirjassa lyijykynäpiirros = blyertsteckning, tussipiirustus =  tuschritning.

**Comment by mariaforsen** [comment]
Lintukirjassa ovat teckningar. Jos tuschritning niin sitten on tosiaan yleensä kyseessä jonkinlainen "malli", teknisempi piirustus, esim. rakennuksesta. Tuschteckning on "taiteellinen piirros".

**Comment by mariaforsen** [comment]
Ratkaistaanko tässä myös piirustus = teckning / ritning?

**Comment by satuniininen** [comment]
Jos tämä käsite jaetaan _piirustukset (taide)_ ja _piirustukset (tekniset)_ KÄ _tekniset piirustukset_ niin riittäisikö toiminta-hierarkian puolella _piirustus (taide)_ ja (jo olemassaoleva) _tekninen piirustus_? Mikäli ei, niin tekniikka/tekninen tuskin sopii sulkutarkenteeksi. 

Ainakin Melindassa piirustusta on käytetty myös ei-taiteellisen piirtämisen yhteydessä, eli siivottavaa tulisi joka tapauksessa.

**Comment by mariaforsen** [comment]
Mielestäni tekniset piirustukset=ritningar/tekniska ritningar voi hankaloittaa tilannetta (kuten yllä mainitsin niin ritning ei välttämättä aina mielletä "tekniseksi")

**Comment by mirmaid** [comment]
Tutkitaan mikä valitaan vaihtoehdoista _piirustukset (suunnittelu) / piirustukset (tekniset) / tekniset piirustukset_. 

_Piirustukset (taide)_ olisi ok toiselle merkitykselle?

Jos mahdollista korjataan _piirustus_ konversion jälkeen, Satun ehdotus kuulostaa hyvältä.

**Comment by ilona-x** [comment]
Tuohon toiminta-hierarkian **piirustus (taide)** ehdotukseen huomiona että sanastossa on myös **piirustustaide** http://www.yso.fi/onto/ysa/Y98124

**Comment by mirmaid** [comment]
Pannahinen :persevere:

**Comment by mirmaid** [comment]
Mutta nyt siis ratkaistava:
- Tutkitaan mikä valitaan vaihtoehdoista piirustukset (suunnittelu) / piirustukset (tekniset) / tekniset piirustukset.
- Piirustukset (taide) olisi ok toiselle merkitykselle?

**Comment by ilona-x** [comment]
Melinda-viitteiden perusteella molemmat vaihtoehdot piirrustukset (suunnittelu) ja tekniset piirustukset ovat mielestäni mahdollisia. 

YSAsta löytyy myös: mittapiirustukset ja pohjapiirustukset

YSA: tekninen piirustus ST kartanpiirustus, koneenpiirustus, rakennuspiirustus, sähköpiirustus

LCSH: Engineering drawings KT Technical drawings http://id.loc.gov/authorities/subjects/sh85043213

SAO:
Ämnesord	                Ritningar
Underordnad term	Arkitekturritningar, Byggritningar 

Esimerkkejä Melinda-viitteistä:

- Oinosenmäen observatorio : rakennussuunnittelu ja pääpiirustusten tuottaminen
- Kesähuvilan ja saunamökin suunnittelu 
- Rakentamisen piirustusmerkintöjä
- Suunnitelma puutavarahakkurin ja nosturin asennuksesta kuorma-autoon 
- Gibson Les Paul -tyylinen sähkökitara
- Suunnitteluohjeen laatiminen ja tuotantopiirustusten päivittäminen
- Tuhkakauhan suunnittelu 
- Uusi LVI-piirustuskirja
- Line, shade and shadow :the fabrication and preservation of architectural drawings
- Alvar Aalto library in Vyborg : saving a modern masterpiece
- Architectural drawing

**Comment by LeKorsu** [comment]
Piirustukset (taide) selkeä, peukku sille
Koska sanastossa on jo tekninen piirustus kannatan muotoa tekniset piirustukset, joka käy mielestäni myös kitaran ja tuhkakauhan rakentamiseen liittyviin piirustuksiin. Mutta pitäisikö silloin ohjausterminä olla piirustukset (suunnittelu) KÄ tekniset piirustukset?

**Comment by YSA-kokous** [comment]
piirustukset (taide)
tekniset piirustukset
tekninen piirustus KÄ tekninen piirtäminen

**Comment by YSA-kokous** [comment]
Jatketaan piirustus-termin ja piirustus-loppuisten termien käsittelyä konversion jälkeen.

**Comment by mariaforsen** [comment]
Sv.
-teckningar
-tekniska ritningar
-teknisk ritning (aktivitet)

**Comment by mirmaid** [comment]
_Piirustus_-käsitteestä on erillinen issue https://github.com/Finto-ehdotus/YSE/issues/7206.

_Tekninen piirtäminen_ -käsitteellä on alakäsitteenä _kartanpiirustus, koneenpiirustus, rakennuspiirustus ja sähköpiirustus._ Lisäksi sanastossa on _muotipiirustus_ ja _elävän mallin piirustus_. Onko näitä tarpeen muuttaa?

Google:
kartanpiirustus/kartanpiirtäminen n. 1200/130
koneenpiirustus/koneenpiirtäminen n. 5000/7
rakennuspiirustus/rakennuspiirtäminen n. 14800/300
sähköpiirustus/sähköpiirtäminen n. 7200/120
muotipiirustus/muotipiirtäminen n. 3700/160
elävän mallin piirustus/-piirtäminen n. 3400/25900

**Comment by tpalonen** [comment]
Piirtäminen-muoto altiksi näille (paitsi koneenpiirustus-tapauksessa, koska niin harvinainen termimuoto)?

**Comment by YSO-kokous** [comment]
Lisätään *piirtäminen-muotoiset ohjaustermit, paitsi ei koneenpiirustus-käsitteelle.
