### ISSUE TITLE
poliisiromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5148]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

police procedurals or police crime dramas (Wikipedia) 

#### Ehdotettu termi suomeksi   

poliisiromaanit 

#### Ehdotettu termi ruotsiksi   

polisromaner 

#### Ehdotettu yläkäsite YSOssa (LT)   

[romaanit](http://www.yso.fi/onto/yso/p1896) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Klassista salapoliisiromaania realistisempi rikosromaani, jossa kuvataan poliisin näkökulmasta, miten poliisitoimen ammattilainen selvittää rikoksia. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

Kitun termi, (joskin siellä yksikössä) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjallisuudentutkimuksellisen aineiston indeksoinnissa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [poliisiromaanit](http://finto.fi/yse/fi/page/Y505148)

**Comment by mirmaid** [comment]
Kaunokissa KÄ _poliisikirjallisuus_

**Comment by mariaforsen** [comment]
Sv. polisromaner

**Comment by YSA-kokous** [comment]
Otetaan muodossa poliisikirjallisuus.
