### ISSUE TITLE
trooppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5149]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

trooppi 

#### Ehdotettu termi ruotsiksi   

trop 

#### Ehdotettu termi englanniksi   

trope 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kielikuvat](http://www.yso.fi/onto/yso/p4677) 

#### Tarkoitusta täsmentävä selite   

Kuvallinen ilmaus, kielikuva, retorinen kuvio, jossa sanoja käytetään niiden kirjaimellisesta merkityksestä poikkeavalla tavalla. (Hosiaisluoma, 2003) Laajemmin: Trooppi voi tarkoittaa seuraavia:
    trooppi retoriikassa kielikuva, joka sisältää sanaleikin.
    trooppi sekä keskiajan että 1900-luvun musiikissa.
    trooppi filosofiassa partikulaarinen eli yksittäinen ominaisuuden ilmentymä.
    trooppi kirjallisuudessa kielen, rakenteen tai sisällön ilmiö, jota hyödynnetään kirjallisena keinona. (Wikipedia) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi. Ei liity pelkästään kirjallisuuteen, vaan myös kielitieteeseen (temaattinen ryhmä 85), filosofiaan (02) ja musiikkiin (89) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sisällönkuvailussa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [trooppi](http://finto.fi/yse/fi/page/Y505149)

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:trooppi

https://en.wikipedia.org/wiki/Trope_%28literature%29

Melindassa 5 kertaa monikossa, kerran yksikössä. Artossa kerran yksikössä. Jos tämä otetaan, vaatii varmaankin sulkutarkenteen ja määritelmän (ero kielikuvat-käsitteeseen).

_"Terveelistä nähdä kaiken - aineellisuutta: sen pitäisi tehdä ihminen iloiseksi ja hyväksi!" : vieraantumisen teema Joel Lehtosen Henkien taistelussa_

_Labyrintin muuttuvat maailmat : Kerronnan trooppien, sääntöjen kääntämisen ja usemman asteen maailmojen suhde Ilkka Auerin fantasiateoksessa Sysilouhien sukua_

_Femmes d’Alger dans leur appartement : analyse tropique du recueil de nouvelles par Assia Djebar_

_"Ad majorem Cthulhus gloriam" : toistuvat piirteet Boris Hurtan ja S. Albert Kivisen Cthulhu-novelleissa_

_Om troper och deras översättning i Johanna Nilssons roman Hon går genom tavlan, ut ur bilden och dess finska översättning Älä usko, älä toivo, älä rakasta_ 

_Les tropes dans deux pièces de théâtre de l’absurde : analyse rhétorique des tropes dans En attendant Godot et dans Fin de partie par Samuel Beckett_ 

_Tyttö kaunis kuin voikukka ja muita Hämärän tanssien kielikuvia_

**Comment by mariaforsen** [comment]
Sv. trop + tarkenne ok.

**Comment by OutiHintikka** [comment]
Ehdottomasti! Kirj.tutkimuksen keskeisiä käsitteitä.

**Comment by mirmaid** [comment]
En vain oikein saa selville mikä tämän suhde on kielikuvat-käsitteeseen. Tieteen termipankissa näyttäisi olevan sama asia? 

A literary trope is the use of figurative language – via word, phrase, or even an image – for artistic effect such as using a figure of speech. The word trope has also come to be used for describing commonly recurring literary and rhetorical devices, motifs or clichés in creative works. https://en.wikipedia.org/wiki/Trope_%28literature%29

**Comment by OutiHintikka** [comment]
Trooppi on kirjallisuudentutkimuksen peruskäsite ja myös tietyllä tapaa sekä tarkempi / mutta toisaalta myös laajempi.


Minut pisti proffa tutkimaan gradussani  näitä trooppeja ja se ei todellakaan tarkoittanut pelkkiä kielikuvia.


/outi


joko kohta loppuu:)


________________________________
Lähettäjä: mirmaid <notifications@github.com>
Lähetetty: 15. toukokuuta 2017 16:26
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] trooppi (#5149)


En vain oikein saa selville mikä tämän suhde on kielikuvat-käsitteeseen. Tieteen termipankissa näyttäisi olevan sama asia?

A literary trope is the use of figurative language – via word, phrase, or even an image – for artistic effect such as using a figure of speech. The word trope has also come to be used for describing commonly recurring literary and rhetorical devices, motifs or clichés in creative works. https://en.wikipedia.org/wiki/Trope_%28literature%29

Trope (literature) - Wikipedia<https://en.wikipedia.org/wiki/Trope_%28literature%29>
en.wikipedia.org
A literary trope is the use of figurative language – via word, phrase, or even an image – for artistic effect such as using a figure of speech.

**Comment by mirmaid** [comment]
^ Jos on laajempi, niin _kielikuvat_ ei voi olla LT. Silloin olisi _trooppi (kirjallisuudentutkimus)_, RT _kielikuvat_ ja kattaisi myös tuon wikipedian: _"The word trope has also come to be used for describing commonly recurring literary and rhetorical devices, motifs or clichés in creative works."_ En ole ihan varma onko tässä nyt yksi vai kaksi merkitystä ja koska monimerkityksisyyden välttäminen on varsinkin ontologiatyössä tärkeää, olen yrittänyt saada sitä yksiselitteistä määritelmää siitä mitä trooppi on ja mitä ei ole, ettei olisi toisaalta päällekkäinen jonkun muun termin kanssa tai itsessään monimerkityksinen.

**Comment by OutiHintikka** [comment]
On laajempi.


/outi


________________________________
Lähettäjä: mirmaid <notifications@github.com>
Lähetetty: 15. toukokuuta 2017 17:20
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] trooppi (#5149)


^ Jos on laajempi, niin kielikuvat ei voi olla LT. Silloin olisi trooppi (kirjallisuudentutkimus), RT kielikuvat ja kattaisi myös tuon wikipedian: "The word trope has also come to be used for describing commonly recurring literary and rhetorical devices, motifs or clichés in creative works." En ole ihan varma onko tässä nyt yksi vai kaksi merkitystä ja koska monimerkityksisyyden välttäminen on varsinkin ontologiatyössä tärkeää, olen yrittänyt saada sitä yksiselitteistä määritelmää siitä mitä trooppi on ja mitä ei ole, ettei olisi toisaalta päällekkäinen jonkun muun termin kanssa tai itsessään monimerkityksinen.

**Comment by YSA-kokous** [comment]
Seuraava kokous. Kristiina selvittää.

**Comment by krinay** [comment]
Kirjallisuudentutkijakollegani ovat sitä mieltä, että ero kielikuvien ja trooppien välillä on niin vaikeasti selitettävissä, että YSAan riittäisi varsinaiseksi asiasanaksi toinen niistä. Voisiko siis troopit (monikossa) ottaa vain ohjaustermiksi (KÄ kielikuvat)?

**Comment by YSA-kokous** [comment]
troopit (kirjallisuudentutkimus)

**Comment by mariaforsen** [comment]
Sv. troper (litteratur)
