### ISSUE TITLE
fuusio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5150]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fuusio](http://www.yso.fi/onto/ysa/Y101395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö lisätä sulkutarkenne tai mahdollisesti jakaa? 

#### Perustelut ehdotukselle   

On monimerkityksinen termi. Vastaava termi YSOssa: fuusio (ydinreaktiot). On ryhmässä 07, mutta käytetty myös esimerkiksi liikeyritysten kohdalla. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
YSAssa ja YSOssa on myös monikollinen fuusiot ryhmässä 75 (YSO fuusiot (yhteiskunnalliset tapahtumat)). Näille tarvitaan siis vain sulkutarkenteet. Ehdottaisin toiselle yläkäsitteeksi ja tarkenteeksi käsitettä _yritysjärjestelyt_ (ks. esim. https://fi.wikipedia.org/wiki/Yritysten_sulautuminen). Toisen tarkenne (ydinreaktiot) on varmaankin ok.

**Comment by YSA-kokous** [comment]
Hyväksytään tarkenteet.

**Comment by mariaforsen** [comment]
Sv.
-fusioner (företagsarrangemang)
-fusion (kärnreaktioner)
