### ISSUE TITLE
laivojen kannet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5151]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laivojen kannet 

#### Ehdotettu termi englanniksi   

(ship) decks 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elottomat objektit](http://www.yso.fi/onto/yso/p207) 

#### Assosiatiiviset (RT)   

[päällysteet](http://www.yso.fi/onto/yso/p3037) 

#### exactMatch   

Decks (naval architecture) : <http://id.loc.gov/authorities/subjects/sh95005763.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

laivankannet, alusten kannet, kannet (laivat), kannet (laivojen), kannet (alusten) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja: "aluksen päällyskate; myös muista aluksen lattiarakenteista" 

#### Perustelut ehdotukselle   

YSOssa on jo "kannet (alusten)" ja vastaava käsite olisi hyvä ottaa myös YSAan. Mietimme kuitenkin Finto-tiimin kanssa, että "kannet (alusten)" ei välttämättä ole paras mahdollinen päätermi. Genetiivimuodon sijaan termi voisi olla lähempänä luonnollista kieltä: "laivojen kannet".

http://finto.fi/yso/fi/page/p26198 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fatigue assessment of thin superstructure decks / Ingrit Lillemäe. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [laivojen kannet](http://finto.fi/yse/fi/page/Y505151)

**Comment by Elmukelmu** [comment]
Entä veneiden kannet?

**Comment by mirmaid** [comment]
vesikulkuneuvojen kannet :grinning:

Melindassa yksi viite laivankansista (veneistä ei mitään). Artossa julkaisu _Bolidt for decks anywhere_, yhtiö valmistaa laivojen, lauttojen ja veneiden kansia.

**Comment by mariaforsen** [comment]
Mahdollisesti fartygsdäck ruotsiksi.

**Comment by mirmaid** [comment]
Jos kuitenkin alusten kannet? Tuskin sitä matskua avaruusalusten kansista riesaksi asti pukkaa?

**Comment by YSA-kokous** [comment]
alusten kannet

**Comment by mariaforsen** [comment]
Sv. däck (fartyg)
