### ISSUE TITLE
julkaisujen kannet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5152]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

julkaisujen kannet 

#### Ehdotettu termi englanniksi   

covers (of publications) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elottomat objektit](http://www.yso.fi/onto/yso/p207) 

#### Assosiatiiviset (RT)   

[kansitaide](http://www.yso.fi/onto/yso/p21479) 

#### Vaihtoehtoiset termit ja ilmaisut   

kannet (julkaisut), kannet (julkaisujen) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja: "kirjaa, vihkoa tms. suojaavista päällysosista" 

#### Perustelut ehdotukselle   

YSOssa on jo "kannet (julkaisujen)" ja vastaava käsite olisi hyvä saada myös YSAan. Mietimme kuitenkin Finto-tiimin kesken, että "kannet (julkaisujen)" ei välttämättä ole paras mahdollinen päätermi. Genetiivimuodon sijaan termi voisi olla luonnollisen kielen mukainen: "julkaisujen kannet". 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Editorial design : for print and electronic media / Yolanda Zappaterra. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [julkaisujen kannet](http://finto.fi/yse/fi/page/Y505152)

**Comment by tpalonen** [comment]
Ohjaustermiksi: kannet (julkaisujen).

**Comment by YSA-kokous** [comment]
Tarvitaanko varmasti?

**Comment by mirmaid** [comment]
Lehtien kansille ei ole vielä sopivaa termiä. Onko parempi ottaa tämä laajempi _julkaisujen kannet_ -käsite, vai _kirjankannet_ ja _kannet (äänitteet)_ -käsitteiden kanssa saman tasoinen _lehdenkannet/lehtien kannet_, vai kenties _kansikuvat_?

**Comment by mariaforsen** [comment]
Ruotsiksi pärmar/omslag-problematiikka, pitänee muuttaa -> omslag (että kattaa myös muita kuin sidottuja kirjoja jne.). Myös lehden-/lehtien kannet=tidningsomslag ja kansikuvat=omslags/pärmbilder ok.

**Comment by LeKorsu** [comment]
Kannatan muotoa julkaisujen kannet jonne ohjataan kannet (äänitteet), levynkannet, kirjankannet, lehdenkannet ja kenties kansikuvatkin.

**Comment by YSA-kokous** [comment]
julkaisujen kannet
otetaan vielä keskusteluun onko tarvetta kirjankannet ja kannet (äänitteet) -käsitteille erikseen

**Comment by mariaforsen** [comment]
Bokomslag (kirjankannet) olisi ainakin ruotsin kannalta hyvä pitää (on jopa SAOssa)

**Comment by jtuohini** [comment]
Jos tarvitaan äänitteiden kansia käsittelevälle kirjallisuudelle (sitä kyllä on), niin muodoksi sitä kuvaavalle asiasanalle mieluummin _äänitteiden kannet_ kuin _kannet (äänitteet)_; kannet eivät ole äänitteitä, joten mainittu sulkutäsmenne olisi harhaanjohtava.

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: säilytetään nykyinen **kannet (äänitteet)**, mutta muutetaan se muotoon _äänitteiden kannet_, LT ehdotettu _julkaisujen kannet_.

**Comment by AuHo22** [comment]
Kirjankannet on YSA-terminä vielä uusi (2017), aiemmin käytetty paljon kansitaide + kirjataide, mutta jos muistakin kansista yhtä hyvin on termit, niin sitten kirjankansistakin, on joka tapauksessa parempi kuin julkaisujen kannet.

**Comment by mariaforsen** [comment]
sv. omslag (publikationer)
