### ISSUE TITLE
astioiden kannet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5153]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

astioiden kannet 

#### Ehdotettu termi englanniksi   

lids 

#### Ehdotettu yläkäsite YSOssa (LT)   

[säilytykseen liittyvät objektit](http://www.yso.fi/onto/yso/p5316) 

#### Assosiatiiviset (RT)   

[päällysteet](http://www.yso.fi/onto/yso/p3037) 
[astiat](http://www.yso.fi/onto/yso/p6290) 

#### exactMatch   

Caps and closures : <http://id.loc.gov/authorities/subjects/sh2004007327.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

kannet (astioiden) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja: " esineessä (yläpinnalla) olevaa aukkoa peittävä avattava levy. Kattilan kansi myös →←. Tölkin kierrekansi. Muovikansi." 

#### Perustelut ehdotukselle   

YSOssa on jo "kannet (astioiden" ja vastaava käsite olisi hyvä saada myös YSAan. Genetiivimuotoinen sulkutarkenne ei kuitenkaan paras mahdollinen, joten päätermi voisi olla muotoa "astioiden kannet". 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Biohajoavan kertakäyttökupinkannen suunnittelu Huhtamäki Oy:lle / Anni Valkola. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [astioiden kannet](http://finto.fi/yse/fi/page/Y505153)

**Comment by mariaforsen** [comment]
Ok, jos ei tarvita muunlaisista kansista kuin nimenomaan astioiden?

**Comment by mirmaid** [comment]
Osa kansista jää kuitenkin edelleen jaon ulkopuolelle, Artossa tupakka-askien kannet ja lietelantasäiliön kansi :poop:, Melindassa sillan kannet ja sylinterinkannet.

**Comment by satuniininen** [comment]
Entä kannet (sulkimet)? Tällöin käsitteen voisi myös hierarkisoida suoraan sulkimien alle.

**Comment by mariaforsen** [comment]
Kannet (sulkimet) saisi myös käännettyä järkevästi ruotsiksi: lock (tillslutare)

**Comment by YSA-kokous** [comment]
kannet (sulkimet)

**Comment by mariaforsen** [comment]
Sv. lock (tillslutare)
