### ISSUE TITLE
levynkannet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5154]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

levynkannet 

#### Ehdotettu termi ruotsiksi   

skivomslag 

#### Ehdotettu termi englanniksi   

record covers, album covers 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kannet (julkaisujen)](http://www.yso.fi/onto/yso/p26197) 

#### Assosiatiiviset (RT)   

[kansitaide](http://www.yso.fi/onto/yso/p21479) 

#### exactMatch   

Sound recordings--Album covers : <http://id.loc.gov/authorities/subjects/sh85125392.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

levyjen kannet, äänitteiden kannet, kannet (levyt/äänitteet/musiikki) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja: "äänilevyn suojuskotelo(n kansi)" 

#### Perustelut ehdotukselle   

Melindassa paljon kirjallisuutta joka käsittelee levynkansia. Finto-tiimin kanssa mietimme ensin tätä ohjaustermiksi "julkaisujen kannet"-käsitteelle (ks. https://github.com/Finto-ehdotus/YSE/issues/5152 ), mutta on kiistanalaista voiko suppeampaa termiä laittaa ohjaustermiksi ja toisaalta kirjallisuutta on sen verran, että tämän voisi varmasti ottaa omaksi käsitteekseen. Suurin osa kannet-termin kuvailukäytöstä tuntuu Melindassa liittyvän levynkansiin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cover art : eläköön vinyyli! = long live vinyl!/ tekijät: Kati Huovinmaa, Maria Tjader-Knight, Pauliina Kähärä, [kirjoittajat): Kati Huovinmaa [ja 16 muuta] 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [levynkannet](http://finto.fi/yse/fi/page/Y505154)

**Comment by ksornova** [comment]
Jos haetaan excat machia LC-termiin Sound recordings--Album covers, sitten termin pitäisi olla laajempi kuin ehdotettu _levynkannet_, esim. _äänitteiden kannet_ tai _kannet (äänitteet)_. Jos haetaan termiä nimenomaan lp- ja cd-levyjen kansitaidetta käsittelevän aineiston kuvailuun, sitten tuo _levynkannet_ on puolestäni ok (silloin suhde LC-termiin pitää olla lähes vastaava).

sen lisäksi mietin, pitäisikö tuo _LT kannet (julkaisujen)_ olla muodossa _kannet (julkaisut)_

**Comment by TommiViitamies** [comment]
Huomauttaisin, että "kansitaide" löytyy jo YSAsta. Levynkansia (ja kirjankansia?) käsittelevä kirjallisuus kai lähestyykin aihetta nimenomaan kansien "taiteellisen sisällön" näkökulmasta. Komppaan myös Katerinan ehdotusta _kannet (äänitteet)_ (tai kannet äänitteiden).

"Levy" on äänitteistä puhuttaessa käsitteenä vähintään yhtä ongelmallinen kuin englanninkielinen termi album, koska kaikki äänitteet eivät ole levyjä (eivätkä toisaalta myöskään albumeita.)

**Comment by YSA-kokous** [comment]
Kannet (äänitteet) sai eniten kannatusta.

**Comment by mariaforsen** [comment]
Sv. omslag (ljudinspelningar) ET albumomslag ET CD-omslag ET skivfodral ET skivkonvolut ET skivomslag
