### ISSUE TITLE
kirjankannet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5155]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjankannet 

#### Ehdotettu termi ruotsiksi   

bokpärmar 

#### Ehdotettu termi englanniksi   

book covers 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kannet (julkaisujen)](http://www.yso.fi/onto/yso/p26197) 

#### Assosiatiiviset (RT)   

[kansitaide](http://www.yso.fi/onto/yso/p21479) 

#### exactMatch   

Book covers : <http://id.loc.gov/authorities/subjects/sh85015613.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

kirjojen kannet, kannet (kirjojen), kannet (kirjat), kannet (kirjallisuus) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 
[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Melindassa paljon kirjallisuutta joka käsittelee kirjankansia. Finto-tiimin kanssa mietimme ensin tätä ohjaustermiksi "julkaisujen kannet"-käsitteelle (ks. https://github.com/Finto-ehdotus/YSE/issues/5152 ), mutta on kiistanalaista voiko suppeampaa termiä laittaa ohjaustermiksi ja toisaalta kirjallisuutta on sen verran, että tämän voisi varmasti ottaa omaksi käsitteekseen. Merkittävä osa kannet-termin kuvailukäytöstä tuntuu Melindassa liittyvän kirjankansiin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Minun kirjani : muistot ja ideat kauniisiin kansiin / Arne & Carlos ; valokuvat: Ragnar Hartvig ; [suomentanut Pirkko Talvio-Jaatinen] 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [kirjankannet](http://finto.fi/yse/fi/page/Y505155)

**Comment by mariaforsen** [comment]
Sv. bokomslag ET bokpärmar
