### ISSUE TITLE
ketjut (järjestelmät)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5157]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ketjut (järjestelmät) 

#### Ehdotettu termi ruotsiksi   

chains (systems) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[järjestelmät](http://www.yso.fi/onto/yso/p3358) 

#### Alakäsitteet (RT)   

[elintarvikeketjut](http://www.yso.fi/onto/yso/p25344) 
[toimitusketjut](http://www.yso.fi/onto/yso/p19415) 

#### Tarkoitusta täsmentävä selite   

toisiinsa yhteydessä olevista olioista t. vars. asioista 

#### Perustelut ehdotukselle   

Käsite on jo YSOssa ja vastaava olisi hyvä ottaa myös YSAan. Ketjut-termi on monimerkityksinen, mikä näkyy myös Melinda-kuvailussa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Uusia mahdollisuuksia bioenergian hankintalogistiikan liiketoimintamalleihin Kemi-Tornion alueella : PUULOG-hankkeessa tuotettuja tutkimustuloksia alueellista kehittämistä varten / Marita Wahlroos, Minttu Merivirta (toim.) 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [ketjut (järjestelmät)](http://finto.fi/yse/fi/page/Y505157)

**Comment by mariaforsen** [comment]
Sv. kedjor (system)
