### ISSUE TITLE
ketjut (elottomat objektit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5158]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ketjut (elottomat objektit) 

#### Ehdotettu termi englanniksi   

chains (inanimate objects) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elottomat objektit](http://www.yso.fi/onto/yso/p207) 

#### exactMatch   

Chains : <http://id.loc.gov/authorities/subjects/sh85022343> 

#### Tarkoitusta täsmentävä selite   

toisiinsa liitetyistä renkaista tms. osista koostuva nauhamainen t. köysimäinen taipuisa rakenne 

#### Vaihtoehtoiset termit ja ilmaisut   

ketjut (objektit), kettingit 

#### Perustelut ehdotukselle   

Käsite on jo YSOssa ja vastaava olisi hyvä ottaa myös YSAan. Ketjut-termi on monimerkityksinen, mikä näkyy myös Melinda-kuvailussa. Tosin antamassani aineistoesimerkissä ilmeisesti kyse pikemminkin kettingeistä kuin ketjuista. Wikipedia: " Ferraria oli aikanaan Suomen suurin naulojen valmistaja ja se valmisti myös metallilankaa, metalliverkkoja, kettinkejä, saranoita, hevosenkenkiä yms." Olisiko kettingit hyvä ohjaustermi? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ferrariasta OFAan : toimintaa kolmella vuosisadalla 1886-2015 / Arto Pietilä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 
[34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576) 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [ketjut (elottomat objektit)](http://finto.fi/yse/fi/page/Y505158)

**Comment by tpusa** [comment]
Kävisikö tähän ketjut (esineet)?

**Comment by mariaforsen** [comment]
Sv. kedjor (föremål)

**Comment by YSA-kokous** [comment]
ketjut (esineet)
