### ISSUE TITLE
sovellukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5159]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sovellukset](http://www.yso.fi/onto/ysa/Y104400) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOn puolella on tehty jako "sovellukset (käyttötavat)" ja "sovellukset (tietotekniikka)". Sama jako olisi tarpeen myös YSAn puolella. 

Tietotekniikka lienee sulkutarkenteena selkeä ja ytimekäs, mutta "käyttötapojen" tilalle pitäisi miettiä jotain napakampaa. 

Sovelluksia on Melindassa käytetty 3 328 kertaa. Ei-tietoteknisessä merkityksessä käsitettä on käytetty todella laajasti, joten käyttöyhteyksien pohjalta sulkutarkennetta on hankala määrittää. Vaihtoehtoisia sulkutarkenteita ovat ainakin
sovellukset (käyttö)
sovellukset (käytännöt)
sovellukset (soveltaminen) [meneekö liian lähelle soveltaminen-käsitettä?]
sovellukset (käytännön toteutukset) [meneekö toteutus liian lähelle tietoteknistä merkitystä?] 

#### Perustelut ehdotukselle   

sovellus Kielitoimiston mukaan
1. soveltaminen.
2. soveltamisen tulos t. kohde. Teoria ja sen käytännön sovellukset. Tuotantomenetelmän suomalainen sovellus.
3. tietotekn. tiettyä tehtävää t. tiettyjä tehtäviä toteuttamaan tarkoitettu ohjelma, joka ei liity kiinteästi järjestelmän ylläpitoon t. hallintaan.

Sanastosta löytyy "soveltaminen" omana käsitteenään, mutta merkitykset 2 ja 3 olisi syytä saada erotettua toisistaan, jotta ne nousisivat myös kuvailussa paremmin esiin. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
Ehdotetuista selkeimmältä tuntuu (käytännöt).

**Comment by mirmaid** [comment]
Olisikohan mitenkään mahdollista jättää vain tietotekniikka-merkitys, ja muissa yhteyksissä käyttää _soveltaminen_-termiä? Muuten ehkä kallistuisin kuitenkin kannattamaan muotoa _sovellukset (soveltaminen)_.

**Comment by satuniininen** [comment]
Ehdotan, että rajataan nyt aluksi pelkkään tietotekniikkaan ja katsotaan minkä verran kuvailuja jää korjausten jälkeen yli. Jos mahdollista niin ohjataan _soveltaminen_ KT _sovellukset (soveltaminen)_ tai mietitään muu ratkaisu.

**Comment by ilona-x** [comment]
Melindassa käytetty paljon merkityksessä sovellukset (soveltaminen). Helpommalta tuntuisi korjata nuo muotoon sovellukset (soveltaminen) kuin vaihtaa tilalle soveltaminen.

Melindassa käytetty: sovellukset 3974 kertaa (huom. tietotekniset sovellukset vielä mukana) & soveltaminen 465 kertaa.

Esimerkkejä Melindasta:

- Modern approaches to terminological theories and applications 
- Nanotechnology applications to telecommunications and networking 
- Time series analysis and its applications 
- Discrete mathematics and its applications
- Katsaus tuotantoteorian sovelluksiin : etäisyysfunktiot ja joustavat funktiomuodot 
- Kasvatukselliset, tekniset ja rakenteelliset sovellutukset ja kilpaurheilu
- Aerosol measurement : principles, techniques, and applications
- Engineering applications of pneumatics and hydraulics
- Mouse genetics : concepts and applications 
- Matematiikan perusteita soveltajalle
- Fuel cells : from fundamentals to applications

**Comment by mirmaid** [comment]
Tarkenteet siis
- sovellukset (tietotekniikka) TAI sovellukset (tietokoneohjelmat) TAI sovellusohjelmat
- sovellukset (soveltaminen)

**Comment by YSA-kokous** [comment]
sovellukset (soveltaminen)
sovellukset (tietokoneohjelmat) TAI sovellusohjelmat

**Comment by mirmaid** [comment]
sovellusohjelmat

**Comment by mariaforsen** [comment]
Sv.
-tillämpningar
-tillämpningsprogram
