### ISSUE TITLE
vahvistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5160]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vahvistus](http://www.yso.fi/onto/ysa/Y104770) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite on monimerkityksinen, joten se pitäisi jakaa. YSOn puolella on tehty seuraava jako:

1. vahvistus (vahventaminen) 
Tehdä vahv(emm)aksi vars. lisäämällä tai parantamalla jonkin lujuutta, kestävyyttä, vakautta, voimaa, tehoa, määrää tai muuta sellaista, vahventaa.

2. vahvistus (oikeudellinen)
Antaa jollekin toimenpiteelle, päätökselle, määräykselle tai muulle sellaiselle laillinen, täysi pätevyys, sanktioida; määrätä tai lopullisesti hyväksyä virallisesti noudatettavaksi.

Tälla jaolla Melinda-käyttö jakautuisi seuraavasti: 

1. vahvistus (vahventaminen)
rakennusten/rakenteiden vahvistaminen,itsetunnon, sosiaalisten taitojen, henkisten voimavarojen vahvistus, signaalin vahvistus

2. vahvistus (oikeudellinen) --> Mieluummin (oikeus) tai (oikeustiede)
vahvistusmenettelyt, vaalituloksen vahvistus, isyyden vahvistus 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirjan mukaan:

1. vahvistaminen. Rakennuksen perustan vahvistus.
2. vahvistava osa, rakenne, lisä tms., vahvike, vahviste. Terästä rakenteen vahvistuksena. Vihollinen toi rintamalle vahvistuksia. Pelata joukkueen vahvistuksena.
3. vahvistava tieto, lausunto, seikka, merkintä tms., varmistus, varmennus. Tietoon ei ole saatu virallista vahvistusta. Etsiä epäilylleen vahvistusta. Ajanvarauksesta tulee vahvistus sähköpostiin. Kaupanvahvistus. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
vahvistus (oikeudellinen) RT alistusmenettely?

**Comment by mirmaid** [comment]
Aika usein muoto _vahvistaminen_ sopisi viitteisiin paremmin kuin _vahvistus_. 

_Vahvistaminen (tekniikka)_ voisi ehkä olla mahdollinen ryhmittely, koska viitteissä on paljon erilaiseen rakentamiseen liittyvää aineistoa.

Toinen ryhmä on (sosiaali)psykologiaa - voisikohan rajata (?)...YSAssa myös _sosiaalinen vahvistaminen_, mikä kuitenkin kai suppeampi.

**Comment by AuHo22** [comment]
Vaihtoehdoiksi vahvistus/vahvistaminen (tekniikka) ja vahvistus (menettely) sekä vahvistus (psykologia)?
Sosiaalipsykologian alalla voi käyttää jo em. sosiaalista vahvistaminen tai voimaantuminen?

**Comment by mariaforsen** [comment]
Allärs: bekräftelse + förstärkning = vahvistus

**Comment by ilona-x** [comment]
Melinda (ilman Artoa) 85 viitettä, joista seuraavat 20 eivät ole teknistä eikä oikeudellista vahvistusta. Monissa tapauksissa vahvistus tuntuu melko tarpeettomalta termiltä kuvailun kokonaisuudessa.

- Roolileikki- ja merkkivahvistamiskokeilun aikana tapahtuneen työrauhahäiriöiden ja syrjäänvetäytyvän käyttäytymisen korjaantumisen pysyvyys 
- Omaishoitajan voimavarat ja niiden vahvistaminen hoitotyön keinoin 
- Ohjaava koulutus yksilön vahvistajana 
- Popper's theory of science : an apologia 
- Att kasta ljus över den andras existens : en begreppsbestämning av bekräftelse ur ett vårdvetenskapligt perspektiv 
- Katkaisuhoitopotilaan voimavarojen tukeminen sairaanhoitajan kuvaamana
- Hitta styrkorna : samtal som stärker medarbetarna
- Tunne- ja sosiaalisten taitojen vahvistaminen kouluyhteisössä
- 15-20-vuotiaiden nuorten toivo, sen ylläpitäminen ja vahvistaminen
- Small talk : simple ways to boost your child's speech and language development from birth 
- 5-6-vuotiaiden lasten sosioemotionaalisten taitojen vahvistaminen toiminnallisessa ryhmässä
- Minä en suostu kiusattavaksi! Jämäkkyystaitojen valmennus, 7-13 -vuotiaat
- Myönteinen tunnistaminen 
- Voi paremmin, osaa enemmän järjestötyössä! :kokemuksia ja käytänteitä työhyvinvoinnin ja osaamisen vahvistamiseen 
- Opas yksilökeskeiseen luontotoiminnan suunnitteluun :Luontoa elämään, luontoa kuntoutukseen -teemajulkaisu 2/3
- "Just det, det är helt jättetråkigt" :förstärkande ord och förled samt instämmande i finlandssvenska ungdomssamtal 
- Luontoa elämään - toimintamalleja osallisuuden ja toimintakyvyn vahvistamiseksi :Luontoa elämään, luontoa kuntoutukseen -teemajulkaisu 3/3
- At home with dyslexia :a parent's guide to supporting your child /
- Ole itsellesi armollinen :kirja hellittämisestä ja riittävyydestä  
- Rajat kuntoon! :puolensa pitämisen ja omasta hyvinvoinnista huolehtimisen taito Jämäkkyystaitojen valmennus :12-15 vuotiaat

**Comment by satuniininen** [comment]
Yllä luetellut tapaukset olisi katettavissa olemassaolevalla sanastolla, esim. _tukeminen, jaksaminen, auttaminen_, joissain tapauksissa myös _sosiaalinen vahvistaminen, voimaantuminen, assertiivisuus_. En usko, että tarvitaan omana käsitteenään erillistä vahvistus (psykologia tjsp).

Toiseen merkitykseen sopii sulkutarkenteeksi _vahvistus (tekniikka)_, toiseen _vahvistus (oikeustiede)_ tai _vahvistus (virallistaminen)_

**Comment by YSA-kokous** [comment]
vahvistus (tekniikka)
vahvistus (virallistaminen)

**Comment by mariaforsen** [comment]
Sv.
-förstärkning (teknik)
-bekräftelse (officiell) (tosin useita mahdollisia vastineita eli ei ongelmaton, ks. esim. VALTER)
