### ISSUE TITLE
lapset (perheenjäsenet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5161]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lapset (perheenjäsenet) 

#### Ehdotettu termi englanniksi   

children (family members) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[perheenjäsenet](http://www.yso.fi/onto/yso/p4927) 

#### Alakäsitteet (RT)   

[adoptiolapset](http://www.yso.fi/onto/yso/p28482) 
[aikuiset lapset](http://www.yso.fi/onto/yso/p27976) 
[ainoa lapsi](http://www.yso.fi/onto/yso/p2356) 

#### Assosiatiiviset (RT)   

[kaksoset](http://www.yso.fi/onto/yso/p9845) 
[kolmoset](http://www.yso.fi/onto/yso/p15579) 
[orvot](http://www.yso.fi/onto/yso/p6957) 
[sisarukset](http://www.yso.fi/onto/yso/p1571) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 

#### Tarkoitusta täsmentävä selite   

poika t. tytär suhteessa vanhempiinsa 

#### Perustelut ehdotukselle   

YSOssa tämä käsite jo on. Olisi hyvä ottaa vastaava myös YSAan. Lapset-termi on monimerkityksinen, mikä näkyy myös kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Puuseppä vai puutarhuri? : vanhemmuuden suorittamisesta onnellisen lapsuuden tukemiseen / Alison Gopnik ; suomentanut Veli-Pekka Ketola. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [lapset (perheenjäsenet)](http://finto.fi/yse/fi/page/Y505161)

**Comment by mariaforsen** [comment]
Sv. barn (familjemedlemmar)

**Comment by ilona-x** [comment]
Jako varmastikin tarpeen, mutta korjattavaa tietokannoissa paljon:

Fennica: lapset  x 6018
Melinda: lapset x 35193 ?
