### ISSUE TITLE
lapset (ikäryhmät)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5162]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lapset (ikäryhmät) 

#### Ehdotettu termi englanniksi   

children (age groups) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ikään liittyvä rooli](http://www.yso.fi/onto/yso/p5591) 

#### Alakäsitteet (RT)   

[erityislapset](http://www.yso.fi/onto/yso/p28565) 
[katulapset](http://www.yso.fi/onto/yso/p10733) 
[lapsinäyttelijät](http://www.yso.fi/onto/yso/p28110) 

#### Assosiatiiviset (RT)   

[adoptiolapset](http://www.yso.fi/onto/yso/p28482) 
[alaikäiset](http://www.yso.fi/onto/yso/p4400) 
[esikouluikäiset](http://www.yso.fi/onto/yso/p6911) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Biomarkers of chronic allograft injury in children after renal transplantation Jenni Miettinen. 

#### Tarkoitusta täsmentävä selite   

ihminen syntymästä murrosikään 

#### Perustelut ehdotukselle   

YSOssa on jo tämä käsite. Olisi hyvä ottaa myös YSAan. Lapset-termi on monimerkityksinen, mikä näkyy myös kuvailussa. Ks. YSOn käsite:
http://finto.fi/yso/fi/page/p4354 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [lapset (ikäryhmät)](http://finto.fi/yse/fi/page/Y505162)

**Comment by mariaforsen** [comment]
Sv. barn (åldersgrupper)
