### ISSUE TITLE
ohjelmat (suunnitelmat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5163]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ohjelmat (suunnitelmat) 

#### Ehdotettu termi englanniksi   

programmes (plans) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yhteiskunnalliset objektit](http://www.yso.fi/onto/yso/p605) 

#### Alakäsitteet (RT)   

[EU-ohjelmat](http://www.yso.fi/onto/yso/p10619) 
[alueohjelmat](http://www.yso.fi/onto/yso/p12807) 
[hallitusohjelmat](http://www.yso.fi/onto/yso/p12164) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Tarkoitusta täsmentävä selite   

toimintasuunnitelma; jnk liikkeen, yhdistyksen, puolueen tms. periaatteet ja tavoitteet 

#### Perustelut ehdotukselle   

YSOssa on jo "ohjelmat (suunnitelmat)" ja vastaava käsite olisi hyvä saada myös YSAan. Ohjelmat-termi on monimerkityksinen, mikä näkyy myös kuvailussa. Onko suunnitelmat hyvä sulkutarkenne? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

SDP:n perhepoliittinen tulevaisuusohjelma : kasvu alkaa perheestä - lapsi- ja perheystävälliseen yhteiskuntaan / [Suomen sosialidemokraattinen puolue]. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@gmail.com **Termiehdotus Fintossa:** [ohjelmat (suunnitelmat)](http://finto.fi/yse/fi/page/Y505163)

**Comment by mariaforsen** [comment]
Sv. program (planer)

**Comment by mirmaid** [comment]
_Opetusohjelmat_-käsitteelle tulossa sulkutarkenne _oppilaitokset_, koska suunnitelmat-tarkenne ei olisi sopinut - sopiikohan kaikkiin tapauksiin tälle laajemmalle käsitteelle?

_Suunnitelmat_ ei ole yläkäsite _ohjelmille_, ja olisi sellaisena ehkä vähän ongelmallinen, vrt. _opetusohjelmat_ vs. _opetussuunnitelmat_.

Onko ohjelmat (suunnitelmat) ok esim. kanta-asiakasohjelmasta käytettynä?

**Comment by satuniininen** [comment]
Kanta-asiakasohjelmien yhteyteen sopii tosiaan aika huonosti, mutta toisaalta yhdistelmä ohjelmat + kanta-asiakkaat tuottaa Melindassa vain yhden osuman. Jos tarvetta tulee jatkossa enemmän, niin kanta-asiakasohjelmat voidaan varmaan ottaaa omana käsitteenään?

**Comment by YSA-kokous** [comment]
ohjelmat (suunnitelmat)

**Comment by mariaforsen** [comment]
Sv. program (planer)

**Comment by jarmosaarikko** [comment]
EKS näyttää sisältävän mm. sektoriohjelmat, koulutusohjelmat, kulttuuriohjelmat.   
Tuo kulttuuriohjelmat näyttää olevan nyt ongelmallinen.  Kuvailtavassa aineistossa oli nuo kolme käsitettä eli kulttuuriohjelmat ei tarkoita ohjelmat (media), joka on kuintekin YSOssa  kulttuuriohjelmat -yläkäsite.  
Eli pitäisikö vielä jakaa kulttuuriohjelmat (media) ja kulttuuriohjelmat (suunnitelmat) ???  Katsotaan nyt ensin paljonko tällaisia yleensä löytyy.
