### ISSUE TITLE
ohjelmat (media)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5164]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ohjelmat (media) 

#### Ehdotettu termi englanniksi   

programmes (media) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[teokset](http://www.yso.fi/onto/yso/p2344) 

#### Alakäsitteet (RT)   

[radio-ohjelmat](http://www.yso.fi/onto/yso/p103) 
[televisio-ohjelmat](http://www.yso.fi/onto/yso/p204) 
[lastenohjelmat](http://www.yso.fi/onto/yso/p7780) 

#### Assosiatiiviset (RT)   

[ohjelmistot](http://www.yso.fi/onto/yso/p11291) 

#### Vaihtoehtoiset termit ja ilmaisut   

ohjelmat (radio- tai tv-ohjelmat) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Radiomusiikin rakennemuutos : kaupallisten radioiden musiikki 1985-2005 / Heikki Uimonen. 

#### Tarkoitusta täsmentävä selite   

radion t. television lähettämä yksittäinen esitys t. sellaisten sarja 

#### Perustelut ehdotukselle   

YSOssa on jo "ohjelmat (radio- tai tv-ohjelmat)" ja vastaava olisi hyvä saada myös YSAan. Ohjelmat-termin käyttö on monimuotoista Melindassa. YSOn nykyinen sulkutarkenne ei kuitenkaan paras mahdollinen, "ohjelmat (media)" lienee parempi.
ks. YSOn käsite: http://finto.fi/yso/fi/page/p104 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [ohjelmat (media)](http://finto.fi/yse/fi/page/Y505164)

**Comment by mariaforsen** [comment]
Sv. program (media)

**Comment by LeKorsu** [comment]
Mikä olisi toisen ohjelmat-termin sulkutarkenne? Tarvetta varmaan jakaa, nykyisiä alakäsitteitä on tosiaan monenlaisia http://finto.fi/ysa/fi/page/Y100611

**Comment by LeKorsu** [comment]
No, tuossa seuraavassa kohdassahan se onkin: ohjelmat (suunnitelmat).

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja yhdistää tähän merkitykseen muutakin kuin median: 2. esitysten t. tapahtumien kokonaisuus jssak tilaisuudessa; radion t. television lähettämä yksittäinen esitys t. sellaisten sarja; jnk taidelaitoksen tms. esitykset kokonaisuutena, ohjelmisto. _Taiteilijan ohjelma käsitti Sibeliuksen yksinlauluja. Luistelijan vapaaohjelma. Suosittu televisio-ohjelma. Ohjelmassa haastateltiin poliitikkoja. Radiosta tulee tänään hyvää ohjelmaa. Teatterin syyskauden ohjelma._ 

Toisaalta esim. "syyskauden ohjelma" tulee jo lähelle toista ohjelmat-termin merkitystä toimintasuunnitelma tms. Melindan viitteitä selatessa vastaan tuli joitakin, joissa kyse on esim. tapahtuman ohjelmasta (_Polttarikirja : näin järjestät ikimuistoisia ylläreitä ystäville_). Tällaisiin ei sovi tarkenne (media), voiko näitä niputtaa samaan kuin eu-ohjelmat, kunto-ohjelmat ja koulutusohjelmat (eli tuo toinen ohjelmat-merkitys)?

**Comment by LeKorsu** [comment]
Olisiko mahdollista, jos olisi kolme eri sulkutarkennetta:
ohjelmat (esim. tapahtumat / esitykset / suoritukset / tuotteet / tuotokset)  
ohjelmat (media)
ohjelmat (suunnitelmat)

Jos olisi tuo esitykset / tuotteet / tuotokset -sulkutarkenne [voiko käyttää tai sanaa välissä? esitykset tai tuotteet??] , siihen sopisivat noiden konserttiohjelmien lisäksi myös atk-ohjelmat, tietokoneohjelmat, ja tietokantaohjelmat, jotka eivät nykyisen ohjelmat-termin alakäsitteistä oikein sovi kumpaakaan esilläolleeseen eli mediaan tai suunnitelmiin.

Meillä on Yle arkiston omassa mediasanastossa muuten lisää alakäsiitteitä tuohon ohjelmat (media) alle, mutta en laita niitä nyt tähän, kun ei käsitellä uusia termiehdotuksia.

**Comment by mariaforsen** [comment]
Eikö myös polttarikirjan tapauksessa ole tavallaan kyse eräänlaisesta "suunnitelmasta"? Vrt. "ohjelma" Kielitoimiston sanakirjassa. Onko riski että ohjelmat (media) ja ohjelmat (esitykset tai tuotteet) alkavat mennä sekaisin, jos erotellaan tällä tavalla..?

**Comment by mirmaid** [comment]
Sitä tässä haen että onko juhlien ohjelma tai tuo Kielitoimiston sanakirjan mainitsema teatterin syyskauden ohjelma sama käsite kuin vaikka EU:n ympäristönsuojeluohjelma, kun sanakirja tosiaan niputtaa yhteen media-merkityksen kanssa.

**Comment by YSA-kokous** [comment]
ohjelmat (media)

**Comment by mariaforsen** [comment]
Sv. program (media)
