### ISSUE TITLE
faskiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5165]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

faskiat 

#### Ehdotettu termi ruotsiksi   

fascior 

#### Ehdotettu termi englanniksi   

fasciae 

#### exactMatch   

LCSH : Fasciae (Anatomy) 
Wikipedia : https://en.wikipedia.org/wiki/Fascia 

#### Tarkoitusta täsmentävä selite   

Lihaskalvolla eli fascialla tarkoitetaan ohutta sidekalvoa, joka muodostaa monimutkaisen verkoston kehossa. Fascia ympäröi ja peittää lihakset sekä kulkee myös lihasten ja muiden kudosten sisällä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fascia in sport and movement, 978-1-909141-07-0 

#### Perustelut ehdotukselle   

mm. Kongressin kirjaston asiasanana 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi **Termiehdotus Fintossa:** [faskiat](http://finto.fi/yse/fi/page/Y505165)

**Comment by mirmaid** [comment]
FinMeSHissä KÄ lihaskalvo

Lääketieteen termit: lihaskalvo: lihasta ympäröivä sidekudoskalvo
faskia: kalvo, sidekudoskalvo, peitinkalvo

**Comment by mirmaid** [comment]
Monikko olisi varmaankin parempi (myös LCSH:ssa), mutta lihaskalvot vai faskiat?

**Comment by mariaforsen** [comment]
Sv. bindvävshinnor ET fascior ET muskelfascior

**Comment by satuniininen** [comment]
Kannatan muotoa _lihaskalvot_. Se on ymmärrettävä ja yleisesti käytetty ja sopii FinMeshin mukaan myös lääketieteelliseen käyttökontekstiin. _Faskiat_, _peitinkalvot_ ja ehkä myös _sidekudoskalvot_ toki ohjaustermeiksi.

**Comment by YSA-kokous** [comment]
Hyväksytty muodossa lihaskalvot.
