### ISSUE TITLE
systemaattinen kirjallisuuskatsaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5167]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

systemaattiset kirjallisuuskatsaukset

#### Ehdotettu termi englanniksi   

systematic reviews

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Tarkoitusta täsmentävä selite   

Ks. esim.
https://oppimateriaalit.jamk.fi/yamk-kasikirja/kirjallisuuskatsaukset/
https://fi.wikipedia.org/wiki/Systemaattinen_kirjallisuuskatsaus 

#### Perustelut ehdotukselle   

Ehkä kuitenkin tarvitaan tarkempia kuvailevia termejä kuin vain pelkkä kirjallisuuskatsaukset, jotta riittävä hyöty kuvailulle tiedonhakua varten olisi olemassa, esim. meta-analyysi on asiasanana olemassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. väitöskirjat, joissa on menetelmää käytetty apuna. 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [systemaattinen kirjallisuuskatsaus](http://finto.fi/yse/fi/page/Y505167)

**Comment by jtuohini** [comment]
Termin pitäisi varmaan olla monikossa (**systemaattiset kirjallisuuskatsaukset**) ja LT-suhteen **kirjallisuuskatsaukset**.

Ehdotuksessa mainittu kuvailutarvehuomautus viittaisi lisäksi siihen, että ehdotettu termi pitäisi ottaa _Suomalaiseen lajityyppi- ja muotosanastoon_, jos halutaan kuvailla katsauksia itseään eikä vain niitä käsittelevää kirjallisuutta.

**Comment by henriyli** [comment]
Lisäsin ehdotukseen englanninkielisen termin systematic reviews ja korjasin samalla suomenkielisen termin monikkomuotoon. (https://en.wikipedia.org/wiki/Systematic_review)

**Comment by jtuohini** [comment]
Vielä tuli mieleen kysyä, onko tässä kyse nimenomaan lääketieteen näkökulmasta, jolloin sanaryhmäksi tulisi 48 ja LCSH-vastineeksi **Systematic reviews (Medical research)**.

**Comment by mirmaid** [comment]
TEROssa ja TSR-ontologiassa.

Systematic reviews are not limited to medicine and are quite common in all other sciences where data are collected, published in the literature, and an assessment of methodological quality for a precisely defined subject would be helpful. https://en.wikipedia.org/wiki/Systematic_review

**Comment by mariaforsen** [comment]
Sv. systematiska översikter, systematiska litteraturöversikter.

**Comment by AuHo22** [comment]
Ehdotin tätä ihan ensinnä tutkimusmenetelmätermiksi ja sen takia yksikössä samoin kuin meta-analyysikin on. Tilastomenetelmät on monikossa YSAssa, mutta sen alle metodologiaa eritelty yksikköön. Samalla tavoin on diskurssianalyysi, haastattelututkimus jne. näitä riittää yksikössä. En ymmärrä miksi tämänkään pitäisi olla monikossa - riittää jos kattotermi on. 567-käyttötarve pikemminkin kuin 650.

**Comment by OutiHintikka** [comment]
eikö kaikki katsaukset ole jossain määrin systemaattisia.

**Comment by YSA-kokous** [comment]
Hyväksytään monikossa.

**Comment by mariaforsen** [comment]
Sv. systematiska litteraturöversikter ET systematiska översikter

**Comment by OutiHintikka** [comment]
Itse näen systematiska översikter-termin kuvaamaan asiaa paremmin.


/outi h


________________________________
Lähettäjä: mariaforsen <notifications@github.com>
Lähetetty: 19. toukokuuta 2017 11:46
Vastaanottaja: Finto-ehdotus/YSE
Kopio: Hintikka Outi; Comment
Aihe: Re: [Finto-ehdotus/YSE] systemaattinen kirjallisuuskatsaus (#5167)


Sv.
systematiska litteraturöversikter ET systematiska översikter
