### ISSUE TITLE
interventiotutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5168]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

interventiotutkimus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Tarkoitusta täsmentävä selite   

Sosiaali- ja terveydenhuollon alueilla varsinkin käytetty tutkimusmenetelmä 

#### Perustelut ehdotukselle   

Tutkimuskirjallisuudessa vastaan tuleva 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

väitöskirjat 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [interventiotutkimus](http://finto.fi/yse/fi/page/Y505168)

**Comment by mirmaid** [comment]
Suhde toimintatutkimukseen?

**Comment by mirmaid** [comment]
16 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. interventionsforskning, interventionsundersökning

**Comment by ilona-x** [comment]
FinMeSH: interventiotutkimukset
http://www.yso.fi/onto/mesh/D016033

TERO: interventiotutkimus
http://www.yso.fi/onto/tero/D016033

**Comment by mirmaid** [comment]
Toimintatutkimus on pääosin laadullisen tutkimuksen suuntaus, jolla pyritään kehittämään kohteena olevaa organisaatiota sen toimintatapoihin vaikuttamisen kautta. -- Toimintatutkimuksessa interventiolla tarkoitetaan kohdeorganisaatiossa tehtävää muutosta, jolla pyritään avaamaan uusia näkökulmia organisaation toimintatapoihin. https://fi.wikipedia.org/wiki/Toimintatutkimus

**Comment by YSA-kokous** [comment]
Seuraava kokous (ks. TEPA).

**Comment by AuHo22** [comment]
Ainakin yo. toimintatutkimuksen määritelmä on vahvasti organisaatiokeskeinen, eli näkökulma on sitten erilainen kuin useiden sote-puolen interventiotutkimusten: "Interventiotutkimuksella viitataan tutkimusprosessiin, joka sisältää intervention suunnittelua, kehittämistä, testausta, toimeenpanoa, arviointia ja raportointia. Keskeisenä työkaluna toimivat erilaiset interventiot, joilla pyritään saamaan aikaan muutos kohdehenkilön tai -ryhmän käyttäytymisessä, terveydessä, hyvinvoinnissa tms. "
https://www10.uta.fi/opas/opetusohjelma/marjapuuro.htm?id=15423 
-mainittu erikseen interventio-, toiminta- ja arviointitutkimus - päällekkäisyyttäkin varmasti on, mutta ehkä sitten myös näkökulmaeroja?

**Comment by mirmaid** [comment]
Työsuojelusanasto: 

- interventiotutkimus: tutkimus, joka perustuu tiedonkeruumenetelmiin, joissa tutkijan puuttuminen tutkittavaan ilmiöön on menetelmän olennainen osa

- toimintatutkimus: määritelmä: tutkimus, jossa tutkija osallistuu tutkimusalan käytännön toimintaan yhteistyössä tutkittavien kanssa, huomautus: Työ aloitetaan tutkimustulosten pohjalta, minkä jälkeen tulosten paikkansapitävyys punnitaan toiminnalla ja tapahtumien kululla. Tutkimustyötä valvotaan tutkijan ja tutkittavien välisellä vuorovaikutuksella.

**Comment by mariaforsen** [comment]
Sv. interventionsforskning ET interventionsstudier ET interventionsundersökning
