### ISSUE TITLE
haavanhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5169]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

haavanhoito 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

haavanhoito on hoitotieteessä vakiintunut termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Oman kirjastomma (TAMK) tietokannasta löytyy yli 300 nimekettä, joissa suurimmassa osassa tarvittaisiin asiasanaa 'haavanhoito' https://tamk.finna.fi/Search/Results?lng=fi_FI&filter%5B%5D=building%3A%220%2FTAMK%2F%22&lookfor=haavat' 

**Ehdottajan nimi:** Seija Kivelä 
**Ehdottajan organisaatio:** Tampereen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** seija.kivela@tamk.fi **Termiehdotus Fintossa:** [haavanhoito](http://finto.fi/yse/fi/page/Y505169)

**Comment by mirmaid** [comment]
Käytetty Melindassa 5 kertaa, ketjua haavat -- hoito 89 kertaa.

**Comment by mirmaid** [comment]
Haavanhoito on ihan ok termi, mutta TERO, FinMeSH tai Lääketieteen termit eivät tunne. Lisäksi tietueissa olisi varmaan syytä käyttää myös _haavat_ + _hoito_ termejä jatkossakin.

**Comment by mariaforsen** [comment]
Sv. sårvård
