### ISSUE TITLE
uskonpuhdistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5170]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uskonpuhdistus](http://www.yso.fi/onto/ysa/Y99927) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

reformaatio 

#### Perustelut ehdotukselle   

"uskonpuhdistus" on teologiselta kannalta arveluttava ja vähintäänkin vanhentunut. Nyt vietetään reformaation merkkivuotta. Tämän aikansa eläneen alkujaankin kyseenalaisen termin voisi hyvin nyt muuttaa! 

#### Ehdottaja   

Airi Forssell 

#### Ehdottajan organisaatio   

ÅAB 

#### Ehdottajan sähköpostiosoite   

airi.forssell@abo.fi

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4727
