### ISSUE TITLE
uskonpuhdistusaika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5171]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uskonpuhdistusaika](http://www.yso.fi/onto/ysa/Y104751) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

reformaation aika 

#### Perustelut ehdotukselle   

"uskonpuhdistus" kuten myös "uskonpuhdistusaika" on teologiselta kannalta arveluttava ja vähintäänkin vanhentunut. Nyt vietetään reformaation merkkivuotta. Tämän aikansa eläneen alkujaankin kyseenalaisen termin voisi hyvin nyt muuttaa! 

#### Ehdottaja   

Airi Forssell 

#### Ehdottajan organisaatio   

ÅAB 

#### Ehdottajan sähköpostiosoite   

airi.forssell@abo.fi

**Comment by YSA-kokous** [comment]
reformaation aika
