### ISSUE TITLE
Basra

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5172]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Basra 

#### Perustelut ehdotukselle   

Kaupunki Irakissa. Kuvailen Basraan sijoittuvaa kaunokirjallista teosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://bit.ly/2oX9dhF 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Basra 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [Basra](http://finto.fi/yse/fi/page/Y505172)

**Comment by mariaforsen** [comment]
Sv. Basra
