### ISSUE TITLE
ammattiyhdistykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5173]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ammattiyhdistykset](http://www.yso.fi/onto/ysa/Y94633) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi vaihdetaan 'järjestöt'. 

#### Perustelut ehdotukselle   

Tällä hetkellä 'ammattiyhdistykset' on 'ammattiliittojen' alakäsite. Hierarkkinen suhde on kuitenkin väärin: ammattiliitto koostuu erilaisista ammattiyhdistyksistä (sen sijaan, että ammattiyhdistys olisi eräänlainen ammattiliitto). Siksi ammattiyhdistykset-käsitteen yläkäsitteeksi sopisi paremmin 'järjestöt'. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Samaa koskee ammattiliittojen suhdetta ylöspäin ammatillisiin keskusjärjestöihin. Molemmat muutettu.
