### ISSUE TITLE
artefaktit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5174]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[artefaktit](http://www.yso.fi/onto/ysa/Y161576) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi vaihdetaan 'elottomat objektit'. 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirjan mukaan artefakti on ” ihmisen tekemä esine, rakennelma tms.”. Siksi 'abstraktit objektit' tuntuu oudolta yläkäsitteeltä, 'elottomat objektit' olisi parempi. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Muutos koskee YSOa, mutta termi on myös monimerkityksinen ja vaatii selkeyttämistä. Huomautus YSAssa: _Sanalla on monia merkityksiä. 1) Artefakti tarkoittaa keinotekoista luomusta (vastakohtana luonnon muodostamalle kohteelle). 2) Lääketieteessä artefaktilla tarkoitetaan tutkimuslöydöstä, joka ei johdu tutkittavasta kohteesta vaan esimerkiksi tutkimusmenetelmän virheestä tai näytteen saastumisesta. 3) Arkeologiassa sanalla tarkoitetaan mitä tahansa ihmisen tekemää rakennelmaa tai esinettä. 4)Tietotekniikassa artefaktilla viitataan usein näkyvään tai kuultavaan virheeseen_

**Comment by mirmaid** [comment]
http://tampub.uta.fi/handle/10024/101851 (?) - FinMeSHissä LT on tutkimusmenetelmät, mikä sopisi tähän aineistoon.

Lääketieteen termit: _menetelmästä tai sen virheellisestä käytöstä aiheutunut vääristymä, esim. laboratoriotuloksen, mikroskooppivalmisteen tai röntgenkuvan virhe_

Käytetty näissä molemmissa merkityksissä, joten (lääketiede) ei sovi tarkenteeksi. Toisaalta viitteitä on vain kourallinen, joten ehkä riittäisi _löydökset + virheet_ TAI _tutkimusmenetelmät_, riippuen kummasta on kyse.

**Comment by mirmaid** [comment]
_Artefaktit_ on myös joissakin erikoisontologioissa, esim. MAOssa. Arkeologian yhteydessä se on aika päällekkäinen _muinaisesineet_ (tai esineet) -termin kanssa.

http://tieteentermipankki.fi/wiki/Arkeologia:artefakti

http://tieteentermipankki.fi/wiki/Estetiikka:artefakti

**Comment by mirmaid** [comment]
Poistetaanko (KÄ esineet) & korjataan viitteet silloin kun kyse on löydöksistä tai tutkimusmenetelmistä? Vai tarvitaanko tätä omana käsitteenään arkeologiassa tai jossain muussa yhteydessä?

**Comment by mariaforsen** [comment]
SAOssakin on artefakter ANV föremål ja ANV fornlämningar (muinaisjäännökset)

**Comment by mirmaid** [comment]
Voisi myös lisätä artefaktit (arkeologia) KÄ muinaisesineet?

**Comment by YSO-kokous** [comment]
Poistetaan artefaktit sanastosta. Lisätään seuraavat ohjaustermit:
artefaktit KÄYTÄ esineet
artefaktit (arkeologia) KÄYTÄ muinaisesineet
