### ISSUE TITLE
huoneteatterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5175]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huoneteatterit](http://www.yso.fi/onto/ysa/Y200904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'teatteritilat'. 

#### Perustelut ehdotukselle   

MAO/TAO-projektissa Teatterimuseon asiantuntijoiden mukaan oikea yläkäsite on 'teatteritilat'. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Tieteen termipankki: 1800-luvun lopulla syntynyt pienteatterimuoto. Ks. http://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:intiimiteatteri

**Comment by mirmaid** [comment]
KT intiimiteatterit? Tosin vain muutaman kerran monikossa Googlella.

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
Nojaudumme tässä Tieteen termipankkiin. Siellä teatterimuoto-merkitys on selkeästi perusteltu. Ei siis muutosta tähän käsitteeseen.
