### ISSUE TITLE
hyrrät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5176]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hyrrät](http://www.yso.fi/onto/ysa/Y171408) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'leikkikalut'. 

#### Perustelut ehdotukselle   

MAO/TAOssa on tarkempi yläkäsite 'leikkikalut' (YSOssa nyt 'elottomat objektit'). 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Wikipedia: Hyrrä on sekä lasten lelu että teknisissä sovelluksissa käytettävä laite. - Melindassa leluista.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Pitäydymme laajemmassa tulkinnassa. Vrt. myös Kielitoimiston sanakirja: "tav. kiekkomainen esine, joka pyörii vapaasti symmetria-akselilla olevan tukipisteensä ympäri".
