### ISSUE TITLE
jakkarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5177]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jakkarat](http://www.yso.fi/onto/ysa/Y185426) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'istuimet'. 

#### Perustelut ehdotukselle   

MAO/TAO-työryhmän mukaan 'istuimet' on parempi yläkäsite kuin 'tuolit', sillä esim. keittiöjakkarat eivät ole tuoleja. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Keittiöjakkarat eivät ole myöskään varsinaisia istuimia. Muutettu LT huonekalut, RT tuolit. Rahit eivät myöskään ole välttämättä ensisijaisesti istuimia, eikä lypsyjakkara taas kaiketi suorastaan huonekalu. Suo siellä vetelä täällä...
