### ISSUE TITLE
karsikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5178]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[karsikot](http://www.yso.fi/onto/ysa/Y179815) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

YSOssa käsitteellä 'karsikot' on korvattuna terminä 'karsikkopuut' ja assosiatiivinen suhde 'havupuihin'. MAOssa 'karsikot' ja 'karsikkopuut' ovat kuitenkin eri käsitteitä ('karsikkopuut' on 'karsikoiden' alakäsite). YSOn käsite viittaa myös ruotsinkielisen termin 'karsikkoträd' perusteella nimenomaan karsikkopuihin. Suosittelemme, että myös YSOssa ensisijainen termi olisi 'karsikkopuut'. 

#### Ehdotettu muutos   

Ensisijaiseksi termiksi 'karsikkopuut'; tai jos YSOon halutaan yleisempi käsite 'karsikot', sillä täytyy olla eri URI ja ruotsinkielinen vastine. Ks. perustelut. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Wikipedia: _Karsikko on perinteinen suomalainen vainajaa koskeva merkintä puussa, taikka metsä tai yksittäinen puu, jossa näitä merkintöjä on. Karsikkoa tehdessä voidaan puusta karsia oksia vainajan merkiksi._

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Tulkitaan käsite laajemmaksi kuin karsikkopuut (vrt. Wikipedia-määritelmä yllä). Muutetaan ruotsinkielinen käytettävä termi tämän mukaisesti. Poistetaan RT havupuut. Yläkäsitteeksi muistomerkit kuten MAOssa.
