### ISSUE TITLE
kaupungit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5180]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kaupungit](http://www.yso.fi/onto/ysa/Y96023) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'ihmisen määrittelemät alueet'? 

#### Perustelut ehdotukselle   

"YSOssa 'kaupungit'-käsitteen yläkäsitteenä on 'kunnat', joten alakäsite 'kaivoskaupungit' pitäisi siirtää toisen käsitteen alle. Samoin suoraan 'kunnat'-käsitteen alla on paljon erilaisia kaupunkeja, jotka eivät mielestämme sovi tähän hierarkiaan; esim. 'ystävyyskaupungit', 'pikkukaupungit' ja 'tapulikaupungit'. Ne eivät ole 'hallintoalueita' tai 'julkisyhteisöjä' (em. käsitteet ovat 'kuntien' yläkäsitteitä). Tarvitaanko 'kaupungit'-käsittettä ollenkaan hallintoalue-mielessä?

Vastaavan ongelman kohdalla MAO/TAOssa päädyimme vaihtamaan MAOn 'kaupungit'-käsitteelle yläkäsitteeksi 'ihmisen määrittelemät alueet'. Tälloin MAOn 'puutarhakaupungit', 'muinaiskaupungit', 'vapaakaupungit' jne. voidaan sijoittaa 'kaupungit'-käsitteen alle. " 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Vapaakunnat väärässä paikassa, YK kunnat. 
Kunnat RT kaupungit
Kaupungit YK ihmisen määrittämät alueet, RT hallintoalueet ja julkisyhteisöt
