### ISSUE TITLE
kuosit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5182]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuosit](http://www.yso.fi/onto/ysa/Y151308) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'fyysiset ominaisuudet'. 

#### Perustelut ehdotukselle   

Yläkäsitteenä on YSOssa nyt 'kulttuuriset objektit'. MAO/TAO-työryhmän mielestä 'kuosi' on kuitenkin ennemmin ominaisuus (vrt. käsite 'väri'.) 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by ilona-x** [comment]
YSO:n tilanne nykyään:
kuosit (pintakuviointi) http://www.yso.fi/onto/yso/p22246
YK yhteiskunnalliset objektit
