### ISSUE TITLE
kytöviljely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5183]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kytöviljely](http://www.yso.fi/onto/ysa/Y192962) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'suoviljely'. 

#### Perustelut ehdotukselle   

MAO/TAOssa käytössä tarkempi yläkäsite 'suoviljely'. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Ks. wikipediassa aivan erilainen tulkinta: _Kytöviljely oli tavallista puuttomilla kovilla mailla ja alavilla niityillä. -- Entisaikoina käytössä ollutta rahkasoiden pintakerroksen kydöttämistä ei pidetä varsinaisena kytöviljelynä._

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Pitäydymme nykyisessä tulkinnassa. Vrt. yllä mainittu Wikipedia-määritelmä sekä Helsingin yliopiston kansatieteen oppiaineen sivuilta löytyvä määritelmä: "Kytöviljelyä harjoitettiin 1600-luvulla melko yleisesti Lounais-Suomen ja Etelä-Pohjanmaan kuivilla mailla". Ks. http://www.helsinki.fi/kansatiede/histmaatalous/peltoviljely/kytojasuo.htm
Ei muutoksia.
