### ISSUE TITLE
lautanauhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5185]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lautanauhat](http://www.yso.fi/onto/ysa/Y175443) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'käsityöt (objektit)'. 

#### Perustelut ehdotukselle   

MAOssa lautanauhat siirrettiin tekstiilit-hierarkiasta käsityöt-hierarkiaan, koska 'nauhat'-käsitteen alakäsitteinä oli paljon teollisesti valmistettuja nauhoja. YSOssa lähin yläkäsite olisi 'käsityöt (objektit)'. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Aika erikoinen ratkaisu, koska nauhat-käsite ei tietenkään tarkoita pelkästään teollisesti valmistettuja nauhoja vaikka kaikki alakäsitteet olisivat sellaisia. (MAOssa nyt siis nauhat (tekstiilit) ja nauhat (tekstiilityöt)). Itse mietin käykö kuminauha tekstiiliksi vai pitäisikö nauhat siirtää pois tekstiilien alta. Kielitoimiston sanakirja: _langoista t. eräistä kuiduista teollisesti t. käsityönä tehty tuote_

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Emme näe YSOssa tarvetta eritellä teollisia ja ei-teollisia tekstiileitä. Lautanauhoille ja pirtanauhoille voidaan kuitenkin toteuttaa monihierarkia. Onko kuminauha tekstiili -problematiikan vuoksi siirrämme nauhat pykälää ylemmäksi hierarkiassa.

nauhat LT elottomat objektit
lautanauhat LT nauhat + LT käsityöt (objektit)
pirtanauhat LT nauhat + LT käsityöt (objektit)

**Comment by mirmaid** [comment]
Tämä vaatinee vielä käsittelyä, koska nauhat-termillä on ruotsiksi tarkenne _textilier_.

**Comment by mirmaid** [comment]
Lautanauhat ja pirtanauhat - ehdotus ok. 

Tutkitaan nauhat-termin käyttö.

**Comment by mariaforsen** [comment]
Sv. band (textilier) rajautuu aika lailla ykkösmerkityksen ("kapea(hko), litteä kudos t. punos, jota käytetään sitomiseen, koristeena tms") mukaan, mutta niin että koskee vain textiilimaisia nauhoja, eli ei muovisia tms. nauhoja. Kuminauhat alakäsitteenä on siis ruotsin kannalta virheellinen, ja kun yläkäsite nyt on tekstiilit, niin on kai suomeksikin.

Melindassa suurin osa oikein, mutta joitakin virheellisiä, esim. 

Virkkaa videonauhasta säihkyvä matto : säihke-villamattoon kietoutuu villalangan kaveriksi vanhojen VHS-videonauhojen tarinat

Alumiini ja alumiiniseokset. Osa 2, Muokatut tuotteet : levyt ja nauhat = Aluminium and aluminium alloys. Part 2, Wrought products : sheets, strips and plates

Viimeistelyvalssain 2:n stressometrirullan hiomalaitteen suunnittelu / Marko Dunder

Halkaisulinja 4:n paperinsyöttöprosessin kehittäminen / Sami Lukin

Nauhan laatu? : VHS-videokasetit

**Comment by mirmaid** [comment]
^ Suomeksi hierarkia voisi olla myös muunlainen ja yllämainittuihin kai sopisi ruotsiksi band, eli ongelmana on tarkenne. Toisaalta mietin, että myös side olisi ruotsiksi band ja varmaan tarkenne (textilier) olisi silloin sopiva? Vai olisiko ennemmin förband?

Jos tuo edellä mainittu ei ole ongelma ja rajaus tekstiileihin on helpoin tapa löytää vastaavuus, täytynee lisätä suomeksi sama tarkenne. Ruotsiksi siis _band_ on monimerkityksinen ja vaatii joka tapauksessa tarkenteen.

**Comment by mariaforsen** [comment]
Riippuu täysin mistä siteestä puhutaan: https://www.kielitoimistonsanakirja.fi/#/side?searchMode=all Jos kiinnitysnauhamerkityksessä niin band olisi ok, muissa tapauksissa ei, https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_50dfaf5f0d621aa94fa109e4e334e466&list_id=1&keyword=side&word=side

On vaikeaa löytää parempi tarkenne kuin textilier, kun myöskään "kiinnitys" ei taida tässä olla yhdistävä tekijä.

**Comment by YSO-kokous** [comment]
PÄÄTÖS: 
Lisätään myös suomen päätermille sulkutarkenne: nauhat (tekstiilit)
Kuminauhat siirrettäneen hierarkiassa toisaanne. YSO-ylläpito pohtii tätä.

**Comment by ilona-x** [comment]
YSOssa on termi [kumituotteet ](http://www.yso.fi/onto/yso/p12001)eli voisiko kuminauhat mennä sen alle? 
LCSH:ssa näyttää olevan rubber bands yläkäsite rubber goods.

Ja samalla voisi ehkä lisätä kumisaappaille toiseksi yläkäsitteeksi kumituotteet? 👢
