### ISSUE TITLE
yhdyskuntasuunnittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5186]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhdyskuntasuunnittelu](http://www.yso.fi/onto/ysa/Y100379) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'maankäytön suunnittelu'. 

#### Perustelut ehdotukselle   

MAO/TAOn asiantuntijaryhmän mukaan käsitteiden suhde on YSOssa väärin päin. 'Maankäytön suunnittelun' yläkäsite on 'suunnittelu', ja 'maankäytön suunnittelun' alle kuuluu sekä 'yhdyskuntasuunnittelu' että YSOn 'yhdyskuntasuunnittelun' tämänhetkiset alakäsitteet. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Tieteen termipankki: _Yhdyskuntasuunnittelu pitää sisällään kaavoituksen ja yhdyskuntateknisen suunnittelun sekä sektorikohtaisten toimintojen (asuminen, työpaikat, palvelut, liikenne jne.) sijoittelun suunnittelun. Rajatumman määritelmän mukaan yhdyskuntasuunnittelu on fyysisen maankäytön ohjausta kaavahierarkian ja muun oikeusvaikutteisen sääntelyn kautta. Laaja-alaisemmin käsitteen voidaan katsoa edellä mainitun lisäksi pitävän sisällään myös aluekehitystyön, joka ilmenee alueiden tulevaa kehitystä ohjaavina tavoitteina, strategioina ja kehittämisohjelmina._

**Comment by YSO-kokous** [comment]
Tästä on keskusteltu myös tässä issuessa: https://github.com/NatLibFi/Finto-data/issues/735

Asiassa näyttää olevan kaksi näkökantaa. Yllä mainittu Tieteen termipankin määritelmä on Suomen lakimiesyhdistyksen laatima. Ympäristöministeriön näkemys taas on linjassa nyt tehdyn ehdotuksen kanssa. Ks. http://www.ym.fi/fi-FI/Maankaytto_ja_rakentaminen/Maankayton_suunnittelun_ohjaus

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Koska nämä kaksi näkökulmaa eivät ole yhteensovitettavissa, toteutetaan maankäytön suunnittelun hierarkia neutraalisti, nojaamatta kumpaankaan näkökulmaan.

maankäytön suunnittelu LT suunnittelu + RT yhdyskuntasuunnittelu

**Comment by mirmaid** [comment]
Molempien yläkäsite nyt siis _suunnittelu kohteen mukaan_.
