### ISSUE TITLE
maljakot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5187]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maljakot](http://www.yso.fi/onto/ysa/Y149679) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'säilytysastiat'. 

#### Perustelut ehdotukselle   

Säilytysastiat on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Periaatteessa kyllä, mutta samoin sitten ainakin ruukut ja vaasit? (Entä kiulut, kannut?) Jostain syystä säilytysastioiden yläkäsite YSOssa ei ole astiat (ei edes RT-suhdetta), vaikka astiat on tulkittu muuten melko laajasti (vakat, ruukut).

Usein varmaan säilytysastia mielletään ruuan tai tavaroiden varastointiin liittyväksi esineeksi, vaikka kukkia myös tilapäisesti säilytetään maljakossa.

**Comment by ilona-x** [comment]
maljakoiden YK edelleen astiat

säilytysastioiden YK hierarkisoiva käsite säilytykseen liittyvät objektit

**Comment by mirmaid** [comment]
Säilytysastioille tuplahierarkia, ei muita muutoksia.
