### ISSUE TITLE
mineraalikuidut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5188]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mineraalikuidut](http://www.yso.fi/onto/ysa/Y169217) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'luonnonkuidut'. 

#### Perustelut ehdotukselle   

Luonnonkuidut on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Esim. TSR-ontologiasta löytyy käsite _synteettiset mineraalikuidut_.

**Comment by mirmaid** [comment]
Ennemmin RT-suhde.
