### ISSUE TITLE
nimikointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5189]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nimikointi](http://www.yso.fi/onto/ysa/Y102916) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'ompelu'. 

#### Perustelut ehdotukselle   

Ompelu on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
En rajaisi näin tiukasti.
