### ISSUE TITLE
ootraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5190]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ootraus](http://www.yso.fi/onto/ysa/Y197662) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'maalaus (pintakäsittely)'. 

#### Perustelut ehdotukselle   

MAO/TAOn asiantuntijaryhmän mukaan 'maalaus (pintakäsittely)' on oikea yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
YSAssa LT koristemaalaus, YSOssa maalaus (kuvataide). Marmorointi on samantyyppinen. Koristemaalaus ym. ovat aika lailla näiden kahden maalauksen (kuvataide ja pintakäsittely) rajalla.

**Comment by ilona-x** [comment]
Tämän yläkäsitteeksi on näköjään YSOssa jossain vaiheessa vaihdettu maalaus (pintakäsittely)
http://www.yso.fi/onto/yso/p27609
