### ISSUE TITLE
harha-aistimukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5191]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[harha-aistimukset](http://www.yso.fi/onto/ysa/Y101541) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Valittava vain yksi yläkäsite; nyt väärää moniperintää, ks. perustelut. 

#### Perustelut ehdotukselle   

Yläkäsitteinä 'aistimukset' ja 'mielenterveyshäiriöt'. Koska edellinen on 'olio' ja jälkimmäinen 'ilmiö' (eli tapahtuma ja toiminta -hierarkiassa), tästä aiheutuu YSOon väärää moniperintää. Harha-aistimukset eivät kai aina liity mielenterveyshäiriöihin? 
MAO/TAOssa 'optiset harhat' on 'biologisten ilmiöiden' alakäsitteenä, mutta vaihdamme yläkäsitteen YSOn mukaisesti kun tämä korjataan. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Tämä on jo muutettu YSOssa.
