### ISSUE TITLE
pirtanauhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5193]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pirtanauhat](http://www.yso.fi/onto/ysa/Y98137) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

MAOssa pirtanauhat siirrettiin tekstiilit-hierarkiasta käsityöt-hierarkiaan, koska 'nauhat'-käsitteen alakäsitteinä oli paljon teollisesti valmistettuja nauhoja. YSOssa lähin yläkäsite olisi 'käsityöt (objektit)'. 

#### Ehdotettu muutos   

Yläkäsitteeksi 'käsityöt (objektit)'. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Ks. lautanauhat https://github.com/Finto-ehdotus/YSE/issues/5185
