### ISSUE TITLE
portaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5194]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[portaat](http://www.yso.fi/onto/ysa/Y98203) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'rakenteet'. 

#### Perustelut ehdotukselle   

MAO/TAOn työryhmän mukaan portaat eivät välttämättä ole runkorakenteita. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Ok, mutta rakenteet-käsitteen alakäsitteenä ei vastaavia. Vähän samantyyppisiä terassit, laiturit.
