### ISSUE TITLE
pylväät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5195]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pylväät](http://www.yso.fi/onto/ysa/Y104079) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'rakennusosat'. 

#### Perustelut ehdotukselle   

Rakennusosat on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Pylväät-käsitettä on käytetty kuvailussa monissa merkityksissä, esim. sähköpylväät, eli ei aina rakennuksen osana. Toisaalta ks. esim. https://fi.wikipedia.org/wiki/Marcus_Aureliuksen_pylv%C3%A4s
