### ISSUE TITLE
raanut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5196]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[raanut](http://www.yso.fi/onto/ysa/Y102917) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'tekstiilit'. 

#### Perustelut ehdotukselle   

MAO/TAOn asiantuntijoiden mukaan raanut eivät aina ole seinätekstiilejä. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus. Lisätään RT:ksi seinätekstiilit.
