### ISSUE TITLE
rahit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5197]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rahit](http://www.yso.fi/onto/ysa/Y185509) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'istuimet'. 

#### Perustelut ehdotukselle   

MAO/TAOn asiantuntijoiden mukaan rahit eivät ole aina jakkaroita ja penkkejä. Siksi yleisempi yläkäsite 'istuimet' on parempi. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus. Poistetaan molemmat aiemmista yläkäsitteistä (jakkarat, penkit). Lisätään RT käsitteille jakkarat ja penkit.
