### ISSUE TITLE
ruukit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5198]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ruukit](http://www.yso.fi/onto/ysa/Y169340) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'teollisuusrakennukset'. 

#### Perustelut ehdotukselle   

Teollisuusrakennukset on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by jtuohini** [comment]
Ehdotetun LT **teollisuusrakennukset** -suhteen ongelmana on se, että ruukki ei ole rakennus, vaan kokonainen teollisuusalue ja -yhdyskunta, joka alueena koostuu teollisuusrakennuksista, työntekijöiden asunnoista ja erilaisista maatalousrakennuksista sekä usein myös ruukinkartanosta ja -kirkosta.

**Comment by YSO-kokous** [comment]
Päätös: 
Teollisuusrakennuksissa on edellä mainittu ongelma. Uudeksi yläkäsitteeksi näin ollen tuotantolaitokset, jolloin käsite tulkitaan organisaatioksi, ei rakennukseksi.
