### ISSUE TITLE
ryijyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5199]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ryijyt](http://www.yso.fi/onto/ysa/Y98669) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'tekstiilit'. 

#### Perustelut ehdotukselle   

MAO/TAOn asiantuntijoiden mukaan ryijyt eivät aina ole seinätekstiilejä. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus. Lisätään käsitteelle RT seinätekstiilit.
