### ISSUE TITLE
tabletit (kattaus)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5200]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tabletit (kattaus)](http://www.yso.fi/onto/ysa/Y193130) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'kodintekstiilit'. 

#### Perustelut ehdotukselle   

Kodintekstiilit on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Tabletteja voi valmistaa monesta eri materiaalista, esim. muovi, korkki. Pyytäisimme TSK:lta kommenttia: voiko "kodintekstiilit"-käsitteen ajatella viittaavan pikemmin esineen funktioon vai määrittääkö se myös valmistusmateriaalin?
