### ISSUE TITLE
vedenpitävyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5201]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vedenpitävyys](http://www.yso.fi/onto/ysa/Y165932) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'fysikaaliset ominaisuudet'. 

#### Perustelut ehdotukselle   

Fysikaaliset ominaisuudet on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Fyysisten ominaisuuksien ja fysikaalisten ominaisuuksien ero YSOssa on käsittelyn alla. Ks. https://github.com/NatLibFi/Finto-data/issues/698
