### ISSUE TITLE
vohvelikirjonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5202]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vohvelikirjonta](http://www.yso.fi/onto/ysa/Y179214) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'pistokirjonta'. 

#### Perustelut ehdotukselle   

PIstokirjonta on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
