### ISSUE TITLE
vuoat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5203]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vuoat](http://www.yso.fi/onto/ysa/Y168211) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'ruoanvalmistusastiat'. 

#### Perustelut ehdotukselle   

Ruoanvalmistusastiat on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
