### ISSUE TITLE
ystävänpäivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5204]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ystävänpäivä](http://www.yso.fi/onto/ysa/Y191960) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi 'juhlapäivät'. 

#### Perustelut ehdotukselle   

Juhlapäivät on tarkempi yläkäsite. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by YSO-kokous** [comment]
Käsitellään issuessa: https://github.com/NatLibFi/Finto-data/issues/801
