### ISSUE TITLE
digitaalikuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5205]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[digitaalikuvaus](http://www.yso.fi/onto/ysa/Y120948) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tämä käsite deprekoidaan ja luodaan uusi 'digitaalikuvaus'-käsite. 

#### Perustelut ehdotukselle   

YSOssa on alkujaan ollut käsitteet 'digitaalikuvaus (valokuvaus)', p7679, ja 'digitaalikuvaus (videokuvaus)', p7651. Sittemmin YSOa on muutettu niin, että on vain yksi 'digitaalikuvaus'-käsite. Se on kuitenkin luotu väärin, koska sillä on sama URI kuin 'digitaalikuvaus (videokuvaus)' -käsitteellä. Tällaisessa tapauksessa olisi pitänyt deprekoida molemmat vanhat käsitteet ja luoda kokonaan uusi 'digitaalikuvaus', jolla vanhat käsitteet olisi korvattu. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Käsitellään YSO-kokouksessa.
