### ISSUE TITLE
Vantaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5206]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Vantaa](http://www.yso.fi/onto/ysa/Y94474) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodoksi Vantaan kauppala, joka oli Vantaan virallinen nimi ennen sen muuttamista kauppalasta kaupungiki 

#### Perustelut ehdotukselle   

Jos YSAsta hakee termillä Vantaan kauppala, ei tule mitään viittausta mihinkään nyt jo auktorisoituna olevaan paikannimeen. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. ET Vanda köping
