### ISSUE TITLE
Waterloon taistelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5207]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Waterloon taistelu 

#### Ehdotettu termi englanniksi   

Battle of Waterloo 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taistelut](http://www.yso.fi/onto/yso/p920) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Kuvailen kaunokirjallista teosta, jossa käsitellään Waterloon taistelua. 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Waterloon_taistelu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://bit.ly/2ovsftZ 

**Ehdottajan nimi:** Petra Unkila 
**Ehdottajan sähköpostiosoite:** petra.unkila@tampere.fi 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [Waterloon taistelu](http://finto.fi/yse/fi/page/Y505207)

**Comment by jtuohini** [comment]
Pitäisikö termiin tapahtumana/sattumuksena ottaa mukaan aikamääre, siis laittaa se muotoon **Waterloon taistelu (1815)**, kun tapahtumissa muutenkin on aikamääreen lisääminen lo AACR2:n ajoista perusperiaate (vaikkakin Suomessa vain satunnaisesti noudatettu). Sisällönkuvailun asiantuntijaryhmä on uudessa oppaassaan menossa kohti kansainvälisempää linjaa, jossa vuodet tulevat mukaan. Vrt. myös Fast-vastine **Waterloo, Battle of (Belgium : 1815)** [http://id.worldcat.org/fast/1172689] ja LCSH-vastine **Waterloo, Battle of, Waterloo, Belgium, 1815** [http://id.loc.gov/authorities/subjects/sh85145739].

**Comment by mirmaid** [comment]
YSAssa vuosi on lisätty jos on useampia samannimisiä taisteluja. Muutenkin muoto Battle of Waterloo on suurelle yleisölle tunnetumpi kuin LCSH:n hankala ja toisteinen label, eikä tätä yleisesti tunnettua muotoa ole siellä edes ohjausterminä, joten toivottavasti kansainvälisempi linja ei tarkoita mitään ihan samansuuntaista :wink:

**Comment by mirmaid** [comment]
Ehdotan että hyväksytään ilman aikatarkennetta. Jos myöhemmin päätetään aikatarkenteen lisäämisestä kaikkiin vastaaviin, tehdään muutos siinä yhteydessä.

**Comment by mariaforsen** [comment]
Sv. slaget vid Waterloo
