### ISSUE TITLE
maahengitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5208]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maahengitys 

#### Ehdotettu termi englanniksi   

soil respiration 

#### Ehdotettu termi ruotsiksi   

markandning 

#### exactMatch   

LCSH : https://classificationweb.net/min/minaret?app=Auth&logic=0&style=0&F_class=&look=0&F_subdivision=&auto=1&auto=1&auto=1&mod=Search&F_heading=&count=25&F_cn=&F_keyword=soil%20respirat&cmd=goto&table=1&index=heading&fkey=Soil_20respiration&expand=1&menu=/Auto/&auto=1&time=1492500390365 
Wikipedia : https://fi.wikipedia.org/wiki/Maahengitys 
AFO : <http://finto.fi/afo/fi/page/p7679> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja: kaasujen vaihdunta maaperässä, vars. hiilidioksidin vapautuminen ilmaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://dissertationesforestales.fi/pdf/article7689.pdf 

#### Perustelut ehdotukselle   

Hiilen kierto (maaperässä) sisältää myös varastoituneen hiilen määrän, ei pelkästään maaperästä vapautuvaa hiilidioksidia. Maahengityksellä, sen määrällä ja muutoksilla on suuri merkitys ilmakehän hiilen määrään ja sitä kautta ilmastonmuutokseen 

**Ehdottajan nimi:** Laura Parikka 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** laura.parikka@uef.fi

**Comment by jtuohini** [comment]
(Puhtaasti uteliaisuudesta ihmettelin tätä asiasanaehdotusta ja huomasin samalla, että LCSH-linkki vie salasanan takana olevaan, joten tässä toimiva linkki LoC:n avoimen datan puolelta: http://id.loc.gov/authorities/subjects/sh2008009232)

**Comment by mariaforsen** [comment]
Sv. markandning
