### ISSUE TITLE
peoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5209]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

peoni 

#### Ehdotettu termi englanniksi   

paeon 

#### Ehdotettu termi ruotsiksi   

peon 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runomitat](http://www.yso.fi/onto/yso/p9439) 

#### Assosiatiiviset (RT)   

[kalevalamitta](http://www.yso.fi/onto/yso/p13851) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Tarkoitusta täsmentävä selite   

Nelitavuinen joko aleneva tai ylenevä runojalka, rytmi- tai tahtiyksikkö, joka muodostuu yhdestä pitkästä painollisesta ja kolmesta lyhyestä painottomasta tavusta, Peonisia säkeitä tavataan erityisesti antiikin kreikkalaisissa komedioissa. (Tieteen termipankki) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Luetteloinnissa ylipäätään. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [peoni](http://finto.fi/yse/fi/page/Y505209)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Paeon_%28prosody%29

Kerran Melindassa, ei Artossa.

**Comment by mirmaid** [comment]
Selkeintä varmaankin ottaa kaikki ehdotetut runomitat.

**Comment by mariaforsen** [comment]
Sv. peon
