### ISSUE TITLE
periteksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5210]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

periteksti 

#### Ehdotettu termi ruotsiksi   

peritext 

#### Ehdotettu termi englanniksi   

peritext 

#### Ehdotettu yläkäsite YSOssa (LT)   

[parateksti](http://www.yso.fi/onto/yso/p29543) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Esimerkiksi kirjailijan nimi, teoksen otsikko, mahdollinen omistuskirjoitus, esipuhe, huomautukset ja kirjan takakansiteksti. (Tieteen termipankki) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Luetteloinnissa ylipäätään. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [periteksti](http://finto.fi/yse/fi/page/Y505210)

**Comment by mirmaid** [comment]
Kerran Melindassa, ei Artossa. YSAan otettiin _parateksti_, ovatko nämä tarkemmat lajittelut tarpeellisia? Käyttö tuntuu melko vähäiseltä. Sinänsä toki ovat määriteltävissä ja sikäli ok.

**Comment by mariaforsen** [comment]
Sv. peritext

**Comment by krinay** [comment]
Riittäisikö tosiaan, että termin parateksti korvatuiksi termeiksi lisättäsiin epiteksti ja periteksti?
