### ISSUE TITLE
äänirunot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5212]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

äänirunot 

#### Ehdotettu termi englanniksi   

acoustic/sound poems 

#### Ehdotettu termi ruotsiksi   

ljuddikter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[runot](http://www.yso.fi/onto/yso/p24644) 

#### Assosiatiiviset (RT)   

[proosarunot](http://www.yso.fi/onto/yso/p5808) 
[kuvarunot](http://www.yso.fi/onto/yso/p21495) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Runousmuoto, jossa semanttisista ja syntaktisista rakenteísta riisuttua lyriikkaa yhdistellään musiikkiin ja taustaääniin. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

Kitun termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Luetteloinnissa ylipäätään. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [äänirunot](http://finto.fi/yse/fi/page/Y505212)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/%C3%84%C3%A4niruno (?). Nämä määritelmät vähän erilaisia kuin Kirjallisuuden sanakirjassa.

**Comment by mirmaid** [comment]
http://yle.fi/uutiset/3-5750952. 

http://yle.fi/vintti/yle.fi/a2/juttu79e4.html?tunnus=2761

**Comment by mirmaid** [comment]
Melindassa kerran muodossa _äänirunous_.

Artossa 2 kertaa _äänirunot_, 3 kertaa _äänirunous_.

**Comment by mariaforsen** [comment]
Sv. ljuddikter tai äänirunous=ljudpoesi (jo KAUNO/BELLAssa)

**Comment by ksornova** [comment]
Minusta äänirunon määritelmä vastaa parhaiten tätä: Ääniruno pelaa äänellä ja äänteillä. Sanojen sijaan olennaista on puheen sävy, väri ja rytmi (Ylen Vintti).

**Comment by jtuohini** [comment]
Samoilla linjoilla on LCSH termillä **Sound poetry** (KT _Sound poetry_, _Poesie sonore_, _Sonorist rhythms (Poetry)_ ja _Sound poems_): "Here are entered poems that are meant to be performed that emphasize sounds instead of semantics for their meaning. Works on poems that are meant to be performed and that are heavily stressed, metrically regular, and are characterized by improvisation, free association, and word play are entered under **Spoken word poetry**."

**Comment by ksornova** [comment]
Sound Poetry: http://id.loc.gov/authorities/subjects/sh85125383

**Comment by TommiViitamies** [comment]
Hosiaisluoman määritelmä äänirunolle on ongelmallinen: jos "lyriikkaa yhdistellään musiikkiin ja taustaääniin", se edellyttää, että kyseessä on jonkinlainen äänitallenne. Mutta ääniruno on kai kuitenkin ensisijaisesti kirjallinen tuote?

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa äänirunous KT äänirunot. Ei määritelmää.

**Comment by mariaforsen** [comment]
Sv.
ljudpoesi ET ljuddikter
