### ISSUE TITLE
naisliikunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5213]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[naisliikunta](http://www.yso.fi/onto/ysa/Y171494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko tällainen termi todella tarpeen? 

#### Perustelut ehdotukselle   

Ruotsiksi näköjään käännetty "damsport" vaikka se on synonymi termille damidrott (naisurheilu). Sanastossa myös naisvoimistelu ja naisurheilu (joille voi olla käyttöä esim. koska näissä kilpaillaan erikseen naiset ja miehet). Ne 17 osumaa Melindassa, joissa tämä termi on käytetty, ovat yleensä sellaisia tapauksia että voi yhtä hyvin tai paremmin käyttää naisurheilu tai naisvoimistelu asiasanana ja näin on tehtykin (ks. Melindaa). Tälle ei löydy hyvää käännöstä, eikä naisliikunta löydy sanastoista/sanakirjoista. Liikunta viittaa (toivottavasti) sekä naisten että miesten liikuntaan, joten eikö se riittäisi (naisurheilun ja -voimistelun lisäksi)? Googlessa vain vähän osumia ja näitä lähinnä koska on olemassa teos jonka nimi on "Naisliikunta..." 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan organisaatio   

ÅAB 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
LUAssa kerrotaan että _naisliikunta_ on otettu käyttöön 1989. Sitä ennen naisten elämä oli leppoisaa :smile:.

**Comment by mariaforsen** [comment]
Hienoa.. Olisiko nyt hyvä aika ottaa käyttöön myös "miesliikunta" :)

**Comment by mirmaid** [comment]
Korkea aika :muscle:

**Comment by YSA-kokous** [comment]
KÄ naisvoimistelu, naisurheilu

**Comment by mariaforsen** [comment]
Sv.
damsport ANV damgymnastik, damidrott
