### ISSUE TITLE
laulaja-lauluntekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5214]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[laulaja-lauluntekijät](http://www.yso.fi/onto/ysa/Y140775) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termien "laulajat" ja "säveltäjät" muutetaan RT-suhteesta LT-suhteeksi. 

#### Perustelut ehdotukselle   

Laulaja-lauluntekijät ovat sekä laulajia että säveltäjiä, joten termien suhde (RT) on nykyisellään väärä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Entä muusikot?

**Comment by jtuohini** [comment]
Termi **muusikot** on LT-suhteessa termiin **laulajat**, joten on samassa käsitepuussa jo. _À propos_, pitäisi saada sanastoon oma terminsä soittajille (pitänee siis ehdottaa). Ja Musassa myös **säveltäjät** LT **muusikot** eli samalla tavoin kuin LCSH:ssa!
