### ISSUE TITLE
media-antropologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5215]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

media-antropologia 

#### Ehdotettu termi englanniksi   

anthropology of media TAI media anthropology 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuuriantropologia](http://www.yso.fi/onto/yso/p2460) 

#### Assosiatiiviset (RT)   

[mediatutkimus](http://www.yso.fi/onto/yso/p14168) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2003004295 (mass media and anthropology )> 
Wikipedia : https://en.wikipedia.org/wiki/Anthropology_of_media 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sumiala, Johanna: Median rituaalit : johdatus media-antropologiaan (2010); englanninnos: Media and ritual : death, community, and everyday life (2013). Media anthropology / editors Eric W. Rothenbuhler, Mihai Coman (2005). Media, anthropology and public engagement / edited by Sarah Pink and Simone Abram (2015). Schulze, Holger: Intimität und Medialität : eine Anthropologie der Medien (2012). 

#### Perustelut ehdotukselle   

Kula-termi 

#### Tarkoitusta täsmentävä selite   

Wikipedia: Anthropology of media (also anthropology of mass media, media anthropology) is an area of study within social or cultural anthropology that emphasizes ethnographic studies as a means of understanding producers, audiences, and other cultural and social aspects of mass media. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [media-antropologia](http://finto.fi/yse/fi/page/Y505215)

**Comment by mirmaid** [comment]
Vain 2 viitettä Melindassa, mutta muuten vakiintunut.

**Comment by mariaforsen** [comment]
Sv. 
medieantropologi ET mediaantropologi ET mediernas antropologi

**Comment by tpusa** [comment]
Temaattinen ryhmä myös: 80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta?
