### ISSUE TITLE
arki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5216]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[arki](http://www.yso.fi/onto/ysa/Y146166) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään arki ja arkielämä ->  arki KT arkielämä 

#### Perustelut ehdotukselle   

Melindassa (tietoaineistossa):
arki 766
arkielämä 4229
arki + arkielämä 305

"Arki" on otettu sanastoon vuonna 2006. aiemmin käytössä on ollut vain "arkielämä". Onkohan taustalla ollut ajatus, ettei "arkielämä" sovi kaikkiin käyttötapauksiin? Käyttö on kuitenkin paljolti päällekkäistä eikä käsitteiden välillä näytä kuvaillun aineiston perusteella olevan juurikaan eroa. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mariaforsen** [comment]
Siinä tapauksessa laittaisin sv. vardagsliv ET vardag? "Vardagsliv" on mukana SAOssakin ja on kyllä tärkeä termi. "Vardag" voi tosin tarkoittaa vähän muutakin, nämä eivät ole ruotsiksi aivan synonymisiä, eikä yhdistäminen ole ruotsiksi ongelmatonta. 

-vardag: veckodag som inte är söndag eller helgdag och alltså normalt är arbetsdag; ibl. äv. inklusive lördagen

-vardagsliv: miten "tavallisesti" eletään, juhlan ja poikkeustapahtumien vastakohtana...

arki:
1. arkipäivä (1); muu kuin juhla-aika.
2. jokapäiväinen elämä, arkielämä, jokapäiväisyys, tavallisuus, arkipäivä 

arkielämä: tavallinen, jokapäiväinen elämä.

**Comment by mirmaid** [comment]
Näissä on ehkä sellainen ero että _arki_-termin osalta paino on olosuhteissa (päiväkotiarki, sotarintaman arki, parisuhteen arki), _arkielämä_-termissä ehkä tapakulttuurissa/kulttuurihistoriassa. 

Ero ei tosiaan näy Melindan viitteitä selatessa, koska lähes aina myös toinen sopisi. Joissakin viitteissä jompi kumpi tuntuu sopivammalta; esim. _Eksistenssin arkipäiväisyys : Martin Heidegger, avautuneisuus, päätös ja Jean-Luc Nancy_ (arki), _Wording the world : Veena Das and scenes of inheritance_ (arki), _The realism challenge : drawing and painting secrets from a modern master of hyperrealism_ (arki), _Kokemuksellisuus työelämässä organisaatioestetiikan viitekehyksessä : työntekijöiden subjektiiviset konstruktiot tehokkuudesta_ (arki).

Myös Kaunokissa on molemmat.

**Comment by YSA-kokous** [comment]
Satu selvittää.

**Comment by satuniininen** [comment]
Tässä on nyt varmaan kaksi vaihtoehtoa:

1. Yhdistetään arki KT arkielämä
2. Pidetään ennallaan, mutta laaditaan määritelmät, jotka toivottavasti auttavat erottamaan nämä toisistaan.

Itse kannatan yhdistämistä. Kuten sanottua, käsitteiden Melinda-käytössä on paljon päällekkäisyyttä, eikä niiden välinen merkitysero näy aineistojen kuvailussa. Lisäksi tuntuu epätodennäköiseltä, ettei _arkielämää_ käsittelevä aineisto käsittelisi myös _arkea_ (sen sijaan toisin päin ero on helpommin kuviteltavissa).

Huomautusten laatiminen on myöskin hankalaa, sillä käsitteiden välinen ero ei niinkään näy niiden sanakirjamerkityksistä, vaan erilaisista käyttökonteksteista.  
Esim. 
Arki: arkipäivä, muu kuin juhla-aika, arki olosuhteena (päiväkotiarki, sotarintaman arki, parisuhteen arki).
Arkielämä: arjen elämäntavat, jokapäiväinen elämä erityisesti tapakulttuurin ja/tai kulttuurihistorian konteksteissa.

**Comment by AuHo22** [comment]
Mielestäni esimerkiksi sodan arjen ja arkielämän voi hahmottaa aika eri asioina. Sodan "arki" voi olla nimeenomaan sotimista ja taisteluita, kun taas siitä erotuksena voidaan sitten kuvata arkielämää sotarintamalla silloin kuin ei olla taisteluissa. Pommitukset taas voivat olla kotirintaman arkea. 

Jos yhdistetään, niin silloin kannatan arki KÄ arkielämä, koska jälkimmäinen on mielestäni tarvitumpi ja ensimmäisessä termissä on juuri tuota moniselitteisyyttä ja käytetään myös kuvaannollisissa merkityksissä. Eli kuten yllä:

-vardagsliv: miten "tavallisesti" eletään, juhlan ja poikkeustapahtumien vastakohtana...

**Comment by YSA-kokous** [comment]
Seuraava kokous, jokin näistä vaihtoehdoista:
vain arki
vain arkielämä
molemmat erillisinä
arki ja arkielämä

**Comment by AuHo22** [comment]
Pienen kyselykierroksen jälkeen meillä sai arki hivenen enemmän kannatusta, koska on laajempi eli epämääräisempi ja voi siten käyttää useammissa yhteyksissä. Itse näen hankalana sen, että nämä lähdettäisiin määritelmin erottamaan toisistaan, vaikka molempien säilyttäminen sai yhtä lailla kannatusta.

**Comment by krinay** [comment]
Tuntuu vaikealta luopua termistä _arkielämä_. Sitä on käytetty meillä ja muualla sisällönkuvailussa paljon, everyday life -aiheista kirjallisuutta on tullut ja tulee jatkuvasti. 

Mutta tuon todettuani tunnustan kannattavani ehdotusta käsitteiden yhdistämisestä, vaikkei sanojen merkitys ihan sama olekaan. Lähellä toisiaan olevat käsitteet ovat hankalia. Senkin myönnän, että _arki_ luultavasti on _arkielämää_ monikäyttöisempi termi, vaikka sitä onkin käytetty tietoaineiston sisällönkuvailussa paljon vähemmän.

**Comment by mariaforsen** [comment]
Vaikea tilanne ruotsin osalta jos säilytetään vain arki, ei taida sitten täsmätä: "veckodag som inte är söndag eller helgdag och alltså normalt är arbetsdag; ibl. äv. inklusive lördagen" (kaikki viikon arkipäivät). Eli vardagsliv= jokapäiväinen elämä, arkielämä, jokapäiväisyys, tavallisuus, arkipäivä tippuisi pois kokonaan. Paljon aineistoja Melindassa jäisi siis ilman termiä ruotsiksi, eli kaikki sellaiset kuin esim. Living standards and changing expectations : investigating domestic necessity and environmental sustainability in an affluent society / Riikka Aro ; Vikingaliv / Dick Harrison & Kristina Ekero Eriksson ; Kohti luovaa arkea : kulttuurinen vanhustyö asiakaslähtöisyyden edistäjänä : tutkimusraportti / Laura Huhtinen-Hildén, Anna Puustelli-Pitkänen, Pia Strandman, Elina Ala-Nikkola ; Kuka keksi haarukan : arkiesineiden ihmeellinen historia / Tarja Tuulikki Laaksonen....

Olisiko mahdollinen vaihtoehto myös esim. "arkipäivät" ja "arkielämä" (ja arki poistetaan?)

**Comment by AuHo22** [comment]
Katsoin YSO:sta termien yläkäsitteitä ja mielestäni _arki_ -termi kuten sitä on käytetty, pitäisi mielestäni olla _olosuhteet_ -termin ST:nä, eikä ST:nä _kalenteriin liittyviin ajanjaksoihin_, kuten se on nyt ; _arkielämä_ LT _oleminen_ ; _arkipäivät_ LT _kalenteriin liittyvät ajanjaksot_.

Jos / kun siirrymme YSOon, niin sen hakemistopuusta, mikäli rakenne säilyy senkaltaisena, voisi löytyä kuvailuun helpotusta tämänkaltaisille merkitykseltään lähekkäin oleville termeille?

**Comment by mirmaid** [comment]
En tiedä onko varsinaista tarvetta arkipäivät-aspektille, _arki_ viittaa tosiaan enemmän olosuhteisiin kuin tiettyyn aikaan. Jos _vardag_-termillä kuvailtaisiin vain aineistoa joka käsittelee arkipäiviä, on nykytilanne siltäkin osin ongelmallinen. Edellä mainituista esimerkeistä viikinkien arkea käsittelevän kirjan kuvailisi kyllä mieluummin termillä _arkielämä_. Mutta sopiiko _vardagsliv_ jos käsitellään työelämän tai sotarintaman arkea, tai noissa mainitsemissani teoksissa?

**Comment by mariaforsen** [comment]
SAOssa on pelkkä vardagsliv, mutta Allärsissa voidaan kyllä ratkaista esim. vardag och vardagsliv, tai sitten pelkkä vardag KT vardagsliv, tarvittaessa.

Vardag-termi on myös tulkinnanvarainen, eli käytetään kyllä muustakin arkikielessä. Kyllä, puhutaan myös esim.  "vardagsliv vid fronten".

**Comment by YSA-kokous** [comment]
arki KT arkielämä
