### ISSUE TITLE
verkkokauppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5217]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkokauppa](http://www.yso.fi/onto/ysa/Y109946) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite pitäisi jakaa. YSOssa jakona on 
1. verkkokauppa (verkkoliiketoiminta)
2. verkkokaupat (WWW-sivustot)

"Verkkoliiketoiminta" lienee ihan napakka ja tarpeellinen sulkutarkenne, mutta "WWW-sivustot" kuulostaa jokseenkin vanhahtavalta, joten toisen merkityksen tarkennetta (ja sen tarpeellisuutta) olisi syytä vielä miettiä. 

Vaihtoehtoisia tarkenteita ovat esim. verkkokaupat (verkkosivustot) ja verkkokaupat (kauppapaikat). Toisaalta monikollinen muoto tuskin on vaarassa mennä sekaisin toimintaan viittavan merkityksen kanssa, joten sen voisi jättää myös kokonaan ilman sulkutarkennetta. 

#### Perustelut ehdotukselle   

Käsite on monimerkityksinen. Huomautus YSAssa: "Sanalla on kaksi merkitystä 1) Tavaroiden ja palvelujen ostaminen ja myyminen tietoverkon välityksellä. 2) WWW-sivu tai -sivusto, jonka välityksellä kauppaa käydään." 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by tpusa** [comment]
Riittäisikö 1. verkkokauppa (liiketoiminta)?
Kohtaan 2 kannatan verkkokaupat (verkkosivustot).

**Comment by mirmaid** [comment]
Monikollinen verkkokaupat ei varsinaisesti tarvitsisi sulkutarkennetta, ellei sitten olla menossa kohti käytäntöä jossa myös yksikölliset prefLabelit hyväksytään linkitetyissä ontologioissa.

Tai tietysti jos tulkitaan että se voi viitata tapahtumaan - _"tehtiin hyvät verkkokaupat eilen kun myytiin traktori huuto.netissä"_.

**Comment by YSA-kokous** [comment]
verkkokauppa (liiketoiminta)
verkkokaupat ilman tarkennetta, mikäli ontologiakehittäjien ryhmä hyväksyy ratkaisun, muuten (verkkosivustot). Mikäli ei tarkennetta, tehdään määritelmä.

**Comment by mirmaid** [comment]
Oliko varmaa että monikollinen tarvitaan? Kerran Melindassa.
