### ISSUE TITLE
marsut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5219]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[marsut](http://www.yso.fi/onto/ysa/Y105318) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

marsu (laji) 

#### Perustelut ehdotukselle   

marsu (Cavia porcellus) on laji. Marsut on suku (Cavia) tai heimo (Caviidae)
https://laji.fi/taksonomia/MX.50448?locale=fi#show
https://fi.wikipedia.org/wiki/Marsu 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
Muutetaan yksikköön?

**Comment by mariaforsen** [comment]
Sv. marsvin

**Comment by YSA-kokous** [comment]
Muutetaan yksikköön.
