### ISSUE TITLE
pelastustoimilaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5220]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pelastustoimilaki](http://www.yso.fi/onto/ysa/Y112497) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pelastuslaki 

#### Perustelut ehdotukselle   

Pelastustoimilaki on kumottu: http://www.finlex.fi/fi/laki/ajantasa/kumotut/1999/19990561 
Nykyään pelastuslaki: http://www.finlex.fi/fi/laki/ajantasa/2011/20110379 

#### Ehdottaja   

Johanna Heimonen 

#### Ehdottajan sähköpostiosoite   

johanna.heimonen@pelastusopisto.fi

**Comment by mirmaid** [comment]
Uusi laki uutena terminä ja edeltäjä-seuraaja -suhde.

**Comment by mariaforsen** [comment]
Sv. 
räddningslag

**Comment by satuniininen** [comment]
Engl. Rescue Act (samoin myös pelastustoimilaki, erotetaan toisistaan vuosiluvuilla)
