### ISSUE TITLE
siirtoväki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5221]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[siirtoväki](http://www.yso.fi/onto/ysa/Y104319) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kysyisin YSA:ssa olevan termin "evakot" vapauttamisesta käyttöön samalla tavoin kuin on Kaunokissa. Nyt evakot on kielletty, käytössä on "siirtoväki". 

#### Perustelut ehdotukselle   

On Kaunokissa. Melindassa tietoluetteloijat ovat osin merkinneet "evakot" auktorisoimattoman asiasanan kenttään Marc653. 

#### Ehdottaja   

Finto-feedback 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Halutaanko evakot-termi käyttöön siirtoväki-termin rinnalle? YSAssa ajatus on ollut, että nämä tarkoittavat niin läheisesti samaa asiaa ettei molempien sisällyttäminen sanastoon ole tarkoituksenmukaista.

Kielitoimiston sanakirja:
**siirtoväki**: sotatoimien t. alueluovutusten takia (vars. Suomessa talvi- ja jatkosodan jälkeen) kotiseudultaan muualle oman maan alueelle siirtynyt väestö.
**evakko**: 1. toiselle paikkakunnalle evakuoitu henkilö, (sota)siirtolainen.

**Comment by EsaMPKK** [comment]
Ei ole tarkoituksenmukaista ottaa toista termiä rinnalle.

**Comment by YSA-kokous** [comment]
Ei muutosta.
