### ISSUE TITLE
eläinten hyvinvointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5222]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

eläinten hyvinvointi 

#### Ehdotettu termi englanniksi   

animal welfare 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hyvinvointi (terveydellinen)](http://www.yso.fi/onto/yso/p22036) 

#### Assosiatiiviset (RT)   

[eläinsuojelu](http://www.yso.fi/onto/yso/p2778) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85005274.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Vaihtoehtoiset termit ja ilmaisut   

djurs välbefinnande 

#### Perustelut ehdotukselle   

AFOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Helkassa 53 viitteessä, Melindassa 44 viitteessä 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [eläinten hyvinvointi](http://finto.fi/yse/fi/page/Y505222)

**Comment by mirmaid** [comment]
Melinda:
eläimet -- hyvinvointi 58 kertaa
eläimet + hyvinvointi 269 kertaa

**Comment by mariaforsen** [comment]
Djurs/djurens välbefinnande olisi ruotsiksi hyvä. Allärsissa on välmående KT välbefinnande, joten ei paras mahdollinen yhdistelmä, vaikka kylläkin mahdollinen sekin jos niin päätetään.

**Comment by AuHo22** [comment]
Paljon muitakin eläinten jne. yhdistelmiä on, esim. eläinten oikeudet, eli sopii joukkoon...

**Comment by YSA-kokous** [comment]
Vaihdetaan hyvinvointi-termin ysa-ryhmä, otetaan lisäksi tämä.

**Comment by mariaforsen** [comment]
Sv.
djurs välbefinnande ET djurens välbefinnande ET djurs välfärd ET djurs välmående ET djurvälfärd
