### ISSUE TITLE
sakraalikuninkuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5223]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sakraalikuninkuus 

#### Ehdotettu termi englanniksi   

sacred kingship 

#### Assosiatiiviset (RT)   

[hallitsijat](http://www.yso.fi/onto/yso/p3001) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85072428.html (Kings and rulers--Religious aspects)> 

#### Vaihtoehtoiset termit ja ilmaisut   

sakraali kuninkuus (eng divine kingship, sacral kingdom) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Britannica: https://global.britannica.com/topic/sacred-kingship 

#### Perustelut ehdotukselle   

KULA-termi. Käytetty Melindassa 48 kertaa: 46 kertaa muodossa sakraali kuninkuus, joka on KULAssa ja kahdesti yhteenkirjoitettuna, mikä näyttää olevan tapana uudemmassa tutkimuskirjallisuudessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kings are Kallinen, Timo: Divine rulers in a secular state (2016). Salokoski, Märta: How kings are made - how kingship changes (väitöskirja, 2006). Jne. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [sakraalikuninkuus](http://finto.fi/yse/fi/page/Y505223)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Sacred_king
https://en.wikipedia.org/wiki/Imperial_cult

**Comment by mirmaid** [comment]
Mikä olisi ruotsinkielinen vastine tälle? @mariaforsen

**Comment by mariaforsen** [comment]
Sv. 
sakralt kungadöme
