### ISSUE TITLE
kalkinpoltto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5224]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kalkinpoltto 

#### Ehdotettu termi ruotsiksi   

kalkbränning 

#### Ehdotettu termi englanniksi   

limeburning (tai: lime burning, lime-burning) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[materiaalista luonti](http://www.yso.fi/onto/yso/p2697) 

#### Assosiatiiviset (RT)   

[valmistustekniikka](http://www.yso.fi/onto/yso/p22012) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Tarkoitusta täsmentävä selite   

Ks. esim. http://akp.nba.fi/wiki;kalkkiuuni 

#### Perustelut ehdotukselle   

KULAssa ja MAO-ontologiassa. Ei ole käytetty kovin usein sisällönkuvailuun Melindassa, mutta vaikea korvata muulla asiasanalla. LCSH:ssa ei ole kalkinpolttoa, mutta kylläkin kalkkiuunit, limekilns (http://id.loc.gov/authorities/subjects/sh85077007.html). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Talve, Ilmar: Suomen kansanomaisesta kalkinpoltosta. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [kalkinpoltto](http://finto.fi/yse/fi/page/Y505224)

**Comment by mariaforsen** [comment]
Sv. kalkbränning ok.
