### ISSUE TITLE
baškiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5225]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

baškiirit 

#### Ehdotettu termi englanniksi   

Bashkirs 

#### Ehdotettu yläkäsite YSOssa (LT)   

[turkkilaiset kansat](http://www.yso.fi/onto/yso/p21108) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85012074 Bashkir (Turkic people)> 
Wikipedia : https://fi.wikipedia.org/wiki/Ba%C5%A1kiirit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Baškiirit (baškiiriksi bašqortlar) ovat turkkilainen kansa, joka elää pääosin Venäjän federaatioon kuuluvassa Baškiriassa. Venäjällä baškiireja oli vuoden 2002 väestönlaskennan mukaan yhteensä 1 673 389 ja heitä asuu myös muualla entisen Neuvostoliiton alueella. Baškiirit puhuvat baškiirin kieltä, joka on läheistä sukua tataarille. Uskonnoltaan baškiirit ovat pääosin sunnimuslimeja. (Wikipedia) 

#### Perustelut ehdotukselle   

Käytetty Melindassa 71 kertaa, enimmäkseen YSA-terminä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. 8-osainen monografiasarja Baškirskoe narodnoe tvorčestvo. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [baškiirit](http://finto.fi/yse/fi/page/Y505225)

**Comment by mariaforsen** [comment]
Sv. basjkirer
