### ISSUE TITLE
kliininen tutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5226]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kliininen tutkimus](http://www.yso.fi/onto/ysa/Y111812) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Kaksi merkitystä, ruotsiksi kaksi eri termiä. Ks. https://fi.wikipedia.org/wiki/Kliininen_tutkimus 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Jaetaan:
**kliininen tutkimus (lääketieteelliset toimenpiteet)**
**kliiniset kokeet** KT kliininen tutkimus (lääkkeet ja hoitomenetelmät), kliininen lääketutkimus, kliininen tutkimustoiminta, RT kliininen farmakologia

(kliiniset kokeet on MeSHissä)

**Comment by mirmaid** [comment]
Lisätään myös määritelmät tai huomautukset merkityksestä.

**Comment by mariaforsen** [comment]
Sv. 
-klinisk undersökning (medicinska åtgärder)
-kliniska prövningar ET klinisk forskning ET kliniska studier ET läkemedelsprövningar

**Comment by YSA-kokous** [comment]
Hyväksytään jako.
