### ISSUE TITLE
valistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5227]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valistus](http://www.yso.fi/onto/ysa/Y109444) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan 

#### Perustelut ehdotukselle   

Usein käytetty myös "tiedotustoiminnasta" ja kasvatuksesta. 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
**valistus (aatteet)**
**valistustoiminta** KT valistus (tiedon jakaminen)

**Comment by mariaforsen** [comment]
Sv. 
upplysningen  
ET upplysning (idéer)

upplysningsverksamhet 
ET upplysning (verksamhet)

**Comment by YSA-kokous** [comment]
Hyväksytään.
