### ISSUE TITLE
listat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5228]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[listat](http://www.yso.fi/onto/ysa/Y96951) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsite on monimerktyksinen ja pitäisi jakaa. 

#### Perustelut ehdotukselle   

Kielitoimiston mukaan
1. kapea, pitkänomainen kappale t. rakenneosa, liuska, piena, säle, kaistale, suikale. 
2. (kirjoitettu) luettelo; paperi(liuska, -lomake tms.), jolle luettelo on kirjoitettu. 

Melindassa termiä on käytetty molemmissa merkityksissä. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mariaforsen** [comment]
Tärkeää ruotsinkin osalta: 
lister
listor

**Comment by satuniininen** [comment]
Sanastossa on jo luettelot, joten ratkaisuksi sopisi myös:

listat (rakennustarvikkeet)
listat (luettelot) KÄ luettelot

**Comment by YSA-kokous** [comment]
Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. 
lister ET lister (byggvaror)
listor ANV förteckningar
