### ISSUE TITLE
vedenotto (kasvit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5229]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vedenotto (kasvit) 

#### Ehdotettu termi englanniksi   

water absorption 

#### Assosiatiiviset (RT)   

[ravinnonotto](http://www.yso.fi/onto/yso/p16138) 

#### exactMatch   

Plants--Absorption of water : <http://id.loc.gov/authorities/subjects/sh85102840.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 
[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Perustelut ehdotukselle   

YSOssa on tehty käsitejako vedenotto-käsitteelle. Termi viittaa sekä kasvien että ihmisten vedenottoon ja nämä ovat oikeastaan kaksi eri käsitettä. Käsitejako olisi hyvä tehdä myös YSAn puolella. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Size- and age-related changes in tree structure and function / Frederick C. Meinzer, Barbara Lachenbruch, Todd E. Dawson, editors. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [vedenotto (kasvit)](http://finto.fi/yse/fi/page/Y505229)

**Comment by satuniininen** [comment]
Kannatan YSOn mukaisia sulkutarkenteita _vedenotto (vedenhankinta)_ ja _vedenotto (kasvit)_

**Comment by mariaforsen** [comment]
Sv. vattenupptagning (växter)

**Comment by YSA-kokous** [comment]
Hyväksytään jako.
