### ISSUE TITLE
vedenotto (vedenhankinta)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5230]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vedenotto (vedenhankinta) 

#### Ehdotettu termi englanniksi   

water abstraction 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käyttöönottava muuttaminen](http://www.yso.fi/onto/yso/p889) 

#### Vaihtoehtoiset termit ja ilmaisut   

vedenotto (veden käyttöönotto), vedenotto (ihmiset) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 

#### Perustelut ehdotukselle   

YSOssa on tehty käsitejako vedenotolle, joka YSAssa viittaa sekä kasvien vedenottoon että vedenkäyttöön yhteiskunnassa. Nämä olisi hyvä jakaa YSAssakin. Haasteena on tosin sopivan sulkutarkenteen valinta. Ks. käsite YSOssa:
http://finto.fi/yso/fi/page/p18957 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Raakavedenottamon suoja-alueuudistus : Littoistenjärven suoja-aluemääräysten ajanmukaistaminen / Toni Yrjänäinen. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [vedenotto (vedenhankinta)](http://finto.fi/yse/fi/page/Y505230)

**Comment by satuniininen** [comment]
Kannatan YSOn mukaisia sulkutarkenteita _vedenotto (vedenhankinta)_ ja _vedenotto (kasvit)_

**Comment by mariaforsen** [comment]
Sv. vattentäkt ET uttag av vatten ET vattenuttag

**Comment by YSA-kokous** [comment]
Hyväksytään jako.
