### ISSUE TITLE
äidinkieli (kieli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5231]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

äidinkieli (kieli) 

#### Ehdotettu termi englanniksi   

mother tongue 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kieli](http://www.yso.fi/onto/yso/p2880) 

#### Assosiatiiviset (RT)   

[kaksikielisyys](http://www.yso.fi/onto/yso/p10956) 
[monikielisyys](http://www.yso.fi/onto/yso/p6720) 
[puolikielisyys](http://www.yso.fi/onto/yso/p10958) 

#### exactMatch   

Native language : <http://id.loc.gov/authorities/subjects/sh85090170> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

YSOssa äidinkieli on jaettu kieleen ja oppiaineeseen. Käsitejako on perusteltavissa esim. kuvailukäytöllä. Näitä kahta käsitettä koskevat aineistot ovat varsin erilaisia. "Äidinkieli (kieli)" soveltuu kuvailuun, kun kirja käsittelee äidinkielen käyttöä kotona, maahanmuuttajien äidinkieltä, vieraan kielen ja äidinkielen eroja jne. "Äidinkieli (oppiaine)" taas soveltuu kuvailuun, kun käsitellään äidinkieltä opetuksessa, oppikirjoissa jne.

Nykyisin YSAssa äidinkieli-käsitteellä on yläkäsitteenä sekä oppiaineet että kieli. Kaikkia äidinkieliä ei kuitenkaan opeteta koulussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

"Mä ramastin keppyjä!" : suomalais-ranskalaisen lapsen kielivalinnat monikielisessä perheessä / Tiina Nieminen. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [äidinkieli (kieli)](http://finto.fi/yse/fi/page/Y505231)

**Comment by mariaforsen** [comment]
Jos tämä jaetaan pitäisi periaatteessa varmaan jakaa kaikki asiat, joissa järjestetään opetusta. Muistuttaa ketjutusajattelua..
