### ISSUE TITLE
äidinkieli (oppiaineet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5232]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

äidinkieli (oppiaineet) 

#### Ehdotettu termi englanniksi   

mother tongue (curriculum subjects) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oppiaineet](http://www.yso.fi/onto/yso/p5296) 

#### Assosiatiiviset (RT)   

[ainekirjoitus](http://www.yso.fi/onto/yso/p9617) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

YSOssa äidinkieli on jaettu kieleen ja oppiaineeseen. Käsitejako on perusteltavissa esim. kuvailukäytöllä. Näitä kahta käsitettä koskevat aineistot ovat varsin erilaisia. "Äidinkieli (kieli)" soveltuu kuvailuun, kun kirja käsittelee äidinkielen käyttöä kotona, maahanmuuttajien äidinkieltä, vieraan kielen ja äidinkielen eroja jne. "Äidinkieli (oppiaineet)" taas soveltuu kuvailuun, kun käsitellään äidinkieltä opetuksessa, oppikirjoissa jne.

Nykyisin YSAssa äidinkieli-käsitteellä on yläkäsitteenä sekä oppiaineet että kieli. Kaikkia äidinkieliä ei kuitenkaan opeteta koulussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ota minut tekemään : draama ja teatteri osana äidinkielen ja kirjallisuuden opetusta / toimittaneet Maria Helstola ja Ilona Ruohomäki. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [äidinkieli (oppiaineet)](http://finto.fi/yse/fi/page/Y505232)

**Comment by jtuohini** [comment]
LCSH-vastine näyttäisi tälle olevan **Native language--Study and teaching**, mikä panee miettimään tarkemmin alkuperäisen YSA-termin kahtiajakamisen mielekkyyttä, varsinkin, kun yhtenä perusteena on, että "kaikkia äidinkieliä ei kuitenkaan opeteta koulussa" (viittaako implisiittisesti suomalaiseen koulutusjärjestelmään? – ja onko seikalla edes merkitystä, koska yhtä hyvin sillä voitaisiin kumota tarve erilliselle oppiainetta kuvaavalle asiasanalle muutenkin).
 
Kaikkinensa ehdotus tuntuu viittaavan siihen, että koulumaailmassa äidinkieli tarkoittaa eri asiaa kuin muuten. Käytännön kysymys: laitetaanko Ranskassa tehdylle ranskan kielen koulukirjalle, joka on suunnattu ranskankielisille oppilaille asiasanaksi "äidinkieli (kieli)" vai "äidinkieli (oppiaineet)"? Mielestäni edellinen, kun oppikirja ei käsittele oppiainetta, vaan oppiaineessa opetettua aihetta.
 
Lisähuoli: ei kai ehdotuksen läpivienti johda tilanteeseen, että kohta on sanastossa erikseen "matematiikka (käsitteelliset tieteet)" ja "matematiikka (oppiaineet)", "algebra (matematiikka)" ja "algebra (oppiaineet)", "musiikki (esittävät taiteet)" ja "musiikki (oppiaineet)" jne? Lista nimittäin olisi loputon ja muutos vaikeuttaisi kuvailua, kun pitäisi aina miettiä, tarkoitetaanko oppiainetta vai oppiaineen sisältöä. Paremminkin asiasanasta **äidinkieli** pitäisi poistaa LT-suhde termiin **oppiaineet**; lähes mitä tahansa voidaan opettaa ja siksi lähes mikä tahansa voi olla oppiaine, mutta seikka on helpoimmin ilmaistavissa kahden termin käytöllä: (1) opetuksen kohdetta kuvastava asiasana, viittasipa se äidinkieleen (joka tietysti pitää myös kielen tarkkuudella ilmaista asiasanana, esim. **ranskan kieli**), matematiikkaan, algebraan tai musiikkiin, ja (2) termi **opetus** (tai jokin sen KT-suhteinen termi) ja/tai **oppiaineet**.
 
Paluu alkuun: LCSH:ssa on mainitun lisäksi asiasanat **Native language** (KT _Mother tongue_ ja _Vernacular language_) ja **Native language and education** (KT _Native language--Use in schools_), mutta perustasolla ei ole tehty mitään eroa äidinkielen ja sitä opettavan oppiaineryhmän välillä; opetusaspekti on ilmaistu opetukseen viittaavalla **--Study and teaching** -lisämääreellä tai tarpeen mukaan tarkemmin joko **--Study and teaching (Elementary)**, **--Study and teaching (Higher)**, **--Study and teaching (Primary)** tai **--Study and teaching (Secondary)**.

**Comment by mariaforsen** [comment]
Jos tämä jaetaan pitäisi periaatteessa varmaan jakaa kaikki asiat, joissa järjestetään opetusta. Muistuttaa ketjutusajattelua..

**Comment by YSA-kokous** [comment]
Ei jaeta.
