### ISSUE TITLE
kielelliset väestöryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5233]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kielelliset väestöryhmät](http://www.yso.fi/onto/ysa/Y101262) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termille suhde "LT väestöryhmät" 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi 

#### Perustelut ehdotukselle   

Termi viittaa selvästi yhden muuttujan perusteella määriteltyyn väestöryhmään, joten luonteva LT-termi olisi tuo ehdotettu väestöryhmät.

**Comment by mirmaid** [comment]
Lisätty LT-suhde.
