### ISSUE TITLE
k’iche’

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5234]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

k’iche’ 

#### Ehdotettu termi englanniksi   

k'iche' 

#### Ehdotettu termi ruotsiksi   

k’iche’ 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mayat](http://www.yso.fi/onto/yso/p647) 
[intiaanit](http://www.yso.fi/onto/yso/p646) 
[intiaanikielet](http://www.yso.fi/onto/yso/p6009) 

#### Vaihtoehtoiset termit ja ilmaisut   

quiché 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Tarkoitusta täsmentävä selite   

Meso-Amerikan alkuperäiskansa ja sen kieli 

#### Perustelut ehdotukselle   

täsmällisempää asiasanoitusta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

K'aslemalil - vivir : el caminar de Rigoberta Menchú Tum en el tiempo https://helka.finna.fi/Record/helka.3029281 

**Ehdottajan nimi:** Pirja Kara 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** pirja.kara@helsinki.fi **Termiehdotus Fintossa:** [k’iche’](http://finto.fi/yse/fi/page/Y505234)

**Comment by jtuohini** [comment]
Pitäisi olla kahtena eri asiasanana: (1) kansaa kuvaavana terminä **k’iche’t**, jonka LCSH-vastine olisi **Quiché Indians** [http://id.loc.gov/authorities/subjects/sh85109838], ja (2) kieltä kuvaavana terminä **k’iche’n kieli**, jonka LCSH-vastine olisi **Quiché language** [http://id.loc.gov/authorities/subjects/sh85109835].

**Comment by mariaforsen** [comment]
Sv. quiché (folk) ET kiché (folk), kichéindianer, quiché, quichéindianer
Sv. quiché (språk) ET kiché (språk), quiché
