### ISSUE TITLE
alkuruoat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5235]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[alkuruoat](http://www.yso.fi/onto/ysa/Y110007) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ST tapakset
ST mezet 

#### Ehdottaja   

Ilona Lindfors 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

ilona.lindfors@helsinki.fi 

#### Perustelut ehdotukselle   

tapakset ja mezet voisivat olla alkuruokien alakäsitteitä, vaikka toki niitä syödään muutenkin kuin alkupalana

http://id.loc.gov/authorities/subjects/sh85031937.html

**Comment by AuHo22** [comment]
Koko ajan muuttuvassa ruokakulttuurissa tuntuu vähän  vaikealta niputtaa näinkään. Voivat olla - kuten sanottu - välipaloja viinin kanssa jne. Eikös entisaikaan salaattikin ollut vain alkuruoka mutta nykyisin syödään paljon pääruokana.  Joudummeko vain ongelmiin, jos muutetaan?

**Comment by ilona-x** [comment]
LCSH:
**tapas**
BT Appetizers
BT Snack foods

**meze** 
BT Appetizers

**Comment by mirmaid** [comment]
Lisätty kompromissina RT termiin alkuruoat ja toisiinsa. Kun eivät ole aina alkuruokia, YSO ei varmaan puoltaisi LT-ST-suhdetta.
