### ISSUE TITLE
juomasuositukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5236]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

juomasuositukset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[suositukset](http://www.yso.fi/onto/yso/p7637) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Tarkoitusta täsmentävä selite   

Käytetty aiemmin ruoat - juomat - yhteensopivuus tms. ruoat - viinit - yhteensopivuus 

#### Perustelut ehdotukselle   

Helppo käyttää - harvemmin kuitenkin juomasuositukset -sanaa käytetään muissa yhteyksissä ; tällöin voinee korvata ravitsemussuositukset -sanalla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Erilaisia keittokirjoja riittää 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [juomasuositukset](http://finto.fi/yse/fi/page/Y505236)

**Comment by mirmaid** [comment]
Nyt suositusten alakäsitteinä on hoitosuositukset ja ravitsemussuositukset, jotka on enemmän sukua juomasuosituksille tässä merkityksessä: https://www.evira.fi/elintarvikkeet/terveytta-edistava-ruokavalio/juomat/juomasuositukset-ikaryhmittain/

**Comment by mariaforsen** [comment]
Sv. dryckesrekommendationer (ehdottajan merkitykseen)

**Comment by Elmukelmu** [comment]
Tälle olisi varmaan käyttöä. Pitäisikö olla myös viinisuositukset (koska niitä eniten esiintyy)?

**Comment by mirmaid** [comment]
^ Se olisi yksiselitteisempi (vaikka alkoholin saantisuositus onkin 10–30 grammaa päivässä :grinning: :wine_glass:).

**Comment by satuniininen** [comment]
LCSHsta löytyy [Food and beer pairing](http://id.loc.gov/authorities/subjects/sh2011005116) sekä [Food and wine pairing](http://id.loc.gov/authorities/subjects/sh2008004136)

**Comment by YSA-kokous** [comment]
Otetaan juomasuositukset ja viinisuositukset.

**Comment by mariaforsen** [comment]
Sv. 
-dryckesrekommendationer ET dryckrekommendationer
-vinrekommendationer
