### ISSUE TITLE
Super Mario Run (peli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5237]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Super Mario Run (peli) 

#### Ehdotettu termi ruotsiksi   

- 

#### Ehdotettu termi englanniksi   

- 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 

#### Perustelut ehdotukselle   

Pokemon Go -tyyppinen mobiilipeli, jolle oppaita luvassa enemmänkin 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sculllion: Super Mario : pelaajan kirja 978952321446 

**Ehdottajan nimi:** Kaija Karjalainen 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** kaija.karjalainen@btj.fi **Termiehdotus Fintossa:** [Super Mario Run (peli)](http://finto.fi/yse/fi/page/Y505237)

**Comment by mariaforsen** [comment]
Sv. Super Mario Run
