### ISSUE TITLE
tarinahieronta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5238]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tarinahieronta 

#### Ehdotettu termi englanniksi   

story massage 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hieronta](http://www.yso.fi/onto/yso/p7862) 

#### Vaihtoehtoiset termit ja ilmaisut   

satuhieronta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa 

#### Tarkoitusta täsmentävä selite   

Yleisemmin puhutaan satuhieronnasta, mutta tarinahieronta kattaisi paremmin myös vanhustyön ja uskontokasvatuksen kontekstit.

http://satuhieronta.fi/

Melinda: ei osumia
Google: tarinahieronta n. 19 kpl, satuhieronta 9 220 kpl, story massage 65 300 kpl 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Poland: Tarinahierontaa Raamatun äärellä 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [tarinahieronta](http://finto.fi/yse/fi/page/Y505238)

**Comment by mariaforsen** [comment]
Sv. sagomassage
