### ISSUE TITLE
kadonneet rakennukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5239]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kadonneet rakennukset 

#### Ehdotettu termi ruotsiksi   

försvunna byggnader 

#### Ehdotettu termi englanniksi   

lost buildings 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset](http://www.yso.fi/onto/yso/p1786) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh93000146> 

#### Vaihtoehtoiset termit ja ilmaisut   

hävinneet rakennukset, hävinnyt arkkitehtuuri, kadonnut arkkitehtuuri, tuhoutuneet rakennukset, tuhoutunut arkkitehtuuri 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Rakennus, joka on ollut olemassa, mutta hävinnyt joko tarkoituksellisesti purkamalla tai muusta syystä, esimerkiksi sodan tai luonnonkatastrofin seurauksena. 

#### Perustelut ehdotukselle   

Aiheesta on tehty paljon kirjoja, joiden käsittelemän tuhoutumisnäkökulman kuvailemiseksi ei YSAsta löydy tällä hetkellä täsmällistä asiasanaa ("kadonneet" viitannee ihmisiin). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lost churches of Mississippi 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@gmail.com **Termiehdotus Fintossa:** [kadonneet rakennukset](http://finto.fi/yse/fi/page/Y505239)

**Comment by jtuohini** [comment]
Ja pari KT-muotoa lisää: _puretut rakennukset_, _tuhotut rakennukset_, _tuhoutunut arkkitehtuuri_.

**Comment by AuHo22** [comment]
Kadonnut arkkitehtuuri / kadonneet rakennukset kuulostaa ensi tuntumalta parhaalta - kadonneista kaupungeista kun myös puhutaan.
Kaikkia ei ole tietoisesti tuhottu tai purettu tai vasta hoitamattomuuden jälkeen niin?
Hävinnyt arkkitehtuuri jne. sanoista pakostakin tulee mieleen arkkitehtuurikilpailuissa hävinneet ehdotukset, jotka eivät ole koskaan saavuttaneet päivänvaloa.

**Comment by mirmaid** [comment]
Näistäkö puhutte https://yle.fi/uutiset/3-9742196 :grin:

**Comment by jtuohini** [comment]
Ehkä ennemminkin arkkitehtonisilta (rakennustaiteellisilta) tai kaupunkikuvallisilta arvoiltaan huomionarvoisempia, kuten https://fi.wikipedia.org/wiki/Norrm%C3%A9nin_talo.

**Comment by mirmaid** [comment]
Tässä englanninkielinen termi on toimivampi kuin suomen "kadonnut", lost kun on myös "menetetty". Kun puhutaan vaikka Turun taudista niin _puretut rakennukset_ olisi selkein; mietin myös onko ylipäätään järkevää viitata samalla termillä sekä näihin että esim. Palmyran tuhoamiseen. Mutta jos on, niin _kadonnut arkkitehtuuri_ ehkä oma suosikkini.

**Comment by YSA-kokous** [comment]
Jätetään termiehdotukseksi.

**Comment by jtuohini** [comment]
Tarvetta on edelleen tälle asiasanalle, esimerkiksi tuossa Mirjan kannattamassa muodossa _kadonnut arkkitehtuuri_: juuri kuvailen opinnäytetyötä, joka käsittelee Laihian vuonna 1642 rakennettua ja vuonna 1809 purettua puukirkkoa ja sen seinämaalauksia...

**Comment by jtuohini** [comment]
Onkohan tämä tulossa joskus käsiteltäväksi uuemman kerran? Tarvetta aina silloin tällöin on. Kirjoitukset puretuista rakennuksista varsinkin lehdissä…

**Comment by jarmosaarikko** [comment]
"Hävinnyt asuinpaikka", "Försvunnen boplats",  "[Former dwelling place](https://beta-paikkatieto.maanmittauslaitos.fi/catalogue/v1/codelistgroups/geographic-names/codelists/placetype/items?lang=eng)",   on käytössä MML  paikannimirekisterissä yhtenä paikkatyyppinä (value" : "1999905").  

Yhteentoimivuuden vuoksi voisi käyttää samaa termiä YSOssakin.
**hävinneet asuinpaikat**  (hävinnyt asuinpaikka)
KT  -- tähän joitakin Jaakon esittämiä termejä.   
YK asuinpaikat, rakennukset -- vai onkohan kadonneella rakennuksella edelleen rakennuksen ominaisuudet?

**Comment by YSO-kokous** [comment]
### Päätös
kadonnut arkkitehtuuri OT puretut rakennukset, kadonneet rakennukset

**Comment by mariaforsen** [comment]
Sv. förlorad arkitektur HT försvunnen arkitektur, rivna byggnader, rivna hus, försvunna byggnader, förlorade byggnader
