### ISSUE TITLE
burmankielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5240]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

burmankielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

On Kaunokissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [burmankielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505240)

**Comment by mariaforsen** [comment]
Sv. burmesisk litteratur
