### ISSUE TITLE
esperantonkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5241]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

esperantonkielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Ei Kaunokissa, eikä Ysa:ssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [esperantonkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505241)

**Comment by mirmaid** [comment]
16 kertaa Melindassa

**Comment by mariaforsen** [comment]
Sv. esperantolitteratur ET litteratur på esperanto
