### ISSUE TITLE
gudžaratinkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5242]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gudžaratinkielinen kirjallisuus 

#### Perustelut ehdotukselle   

Ei Kaunokissa eikä Ysa:ssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [gudžaratinkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505242)

**Comment by mirmaid** [comment]
2 kertaa Melindassa

**Comment by mariaforsen** [comment]
Sv. gujaratisk litteratur ET gujaratilitteratur ET litteratur på gujarati
