### ISSUE TITLE
lingalankielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5243]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lingalankielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Ei Kaunokissa eikä Ysa.ssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden kuvailussa 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [lingalankielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505243)

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Lingala

**Comment by mirmaid** [comment]
Ei Melindassa
