### ISSUE TITLE
isonieriä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5245]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[isonieriä](http://www.yso.fi/onto/ysa/Y146578) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan. 
Nieriä (Salvenius alpinus) on Euroopassa esiintyvä laji. Harmaanieriä (Salvenius namaycush) ja puronieriä (Salvenius fontalis) ovat ok. Nieriä-suvun muita lajeja Pohjois-Amerikasta. 

#### Perustelut ehdotukselle   

laji.fi: Ei tunne nimeä "isonieriä". Saimaannieriä on muodossa "nieriä, Saimaan kanta".
https://laji.fi/taksoni/MX.53137?locale=fi#show
Luken sivuilta: Suomessa nieriästä on erotettu perinteisesti kaksi muotoa, iso- ja pikkunieriä, joita aikanaan pidettiin jopa eri lajeina, nykyisen käsityksen mukaan Euroopassa tavataan alkuperäisenä vain yhtä lajia. Suomen nieriävesissä tavataan useimmiten vain yhtä nieriämuotoa kerrallaan. Inarijärvestä tunnetaan kuitenkin sekä lähinnä pohjaeläimiä ja muita selkärangattomia syövä pikkunieriä (paltsarautu) että kalaravintoa käyttävä isonieriä. http://kalahavainnot.fi/kalalajitieto/nieria/ 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by PaiviLipsanen** [comment]
Tieteellisisä nimissä oli kirjoitusvirheitä. Oikeat muodot: Nieriä (Salvelinus alpinus), harmaanieriä (Salvelinus namaycush), puronieriä (Salvelinus fontinalis).

**Comment by mirmaid** [comment]
_Pikkunieriää löytyy Lapin tunturijärvistä ja puroista, kun taas isonieriää on isommissa Lapin järvissä, kuten Vuoksen vesistöissä, Orivedessä, Saimaan Pyhäselällä, Puruvedessä, Kuolimossa ja Yövedessä._ http://www.lapinkalatalouskeskus.net/hauska-tietaeae/nieriae/

Melindassa 9 kertaa isonieriä, kerran pikkunieriä (myös Yle käyttänyt muutaman kerran). Voidaan varmaan poistaa, mutta toisaalta onko haittaa, vaikka eivät olekaan itsenäisiä lajeja?

**Comment by PaiviLipsanen** [comment]
Hierarkia menisi näin 
https://laji.fi/taxon/MX.53301

lohikalat
- nieriä (Salvelinus alpinus)
- puronieriä (Salvelinus fontinalis)
- harmaanieriä (Salvelinus namaycush)

nieriä
- isonieriä
- pikkunieriä

Melindan viitteissä on näköjään asiasanana myös nieriä.

Isonieriä voi jäädä, kun hierarkia korjataan.

**Comment by mariaforsen** [comment]
En ymmärtänyt että myös pikkunieriä otetaan sanastoon. Tieteellinen nimi? Jäänee ruotsiksi ilman vastinetta, tai voidaan tarvittaessa laittaa "småröding", vaikka onkin epävirallinen termi.
