### ISSUE TITLE
stroomasolut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5246]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

stroomasolut 

#### Ehdotettu termi englanniksi   

Stromal Cells 

#### Ehdotettu yläkäsite YSOssa (LT)   

[solut](http://www.yso.fi/onto/yso/p2409) 

#### exactMatch   

MeSH : Stromal Cells 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Perustelut ehdotukselle   

Väitöskirjan kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Metabolism of polyunsaturated fatty acids in human bone marrow derived mesenchymal stromal cells, https://helda.helsinki.fi/handle/10138/182233 

#### Tarkoitusta täsmentävä selite   

Väitöskirjassa käsiteltiin "human bone marrow derived mesenchymal stromal cells (hBMSCs)", mutta riittäisikö termi stroomasolut?
MeSH: Mesenchymal Stromal Cells - Mesenkymaaliset stroomasolut (Termix)
LCSH: Mesenchymal stem cells 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [stroomasolut](http://finto.fi/yse/fi/page/Y505246)

**Comment by mariaforsen** [comment]
Sv. stromaceller
