### ISSUE TITLE
psykologiset romaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5247]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

psykologiset romaanit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Kaunokissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Dostojevskia käsittelevään esseekokoelmaan 

**Ehdottajan nimi:** BTJ 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [psykologiset romaanit](http://finto.fi/yse/fi/page/Y505247)

**Comment by mariaforsen** [comment]
Sv. psykologiska romaner
