### ISSUE TITLE
resilienssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5248]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[resilienssi](http://www.yso.fi/onto/ysa/Y182344) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu uutena Ysaan. "Politiikka-lehdessä oli hiljattain tämän käsitteen ympärille rakennettu kokonainen tutkimusartikkeli."

YSAssa on jo termi resilienssi, ryhmä 00. Huomautus: Tarkoittaa kimmoisuutta, joustavuutta, palautumis- ja uudistumiskykyä

YSOssa mappaus LCSH: Resilience (Personality trait). Melindassa käytetty monenlaisissa yhteyksissä, ei yksinomaan ihmisistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Resilienssi kuvaa yhteisöjen ja yksilöiden kykyä ylläpitää toimintakykyä muuttuvissa olosuhteissa sekä niiden valmiutta kohdata häiriöitä ja kriisejä ja palautua niistä. http://mmm.fi/documents/1410837/1923148/Ruokapoliittinen+selonteko+Ruoka2030/d576b315-41fe-4e9d-9d02-8462c5ae5895

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Resilience

**Comment by mariaforsen** [comment]
Näyttää olevan enemmän käytetty nimenomaan tässä abstraktisemmassa merkityksessä (google ja Melinda). Onko se "materiaan liittyvä" merkitys ylipäätään tarpeen (muovisanastossa TEPAssa)? Kimmoisuus ja joustavuus on myös erikseen jo YSAssa.

**Comment by mirmaid** [comment]
Ehkä ei. LCSH:n personality trait kattaa kuitenkin vain osan Melindan käytöstä, usein käytetty organisaatiosta tai yhteiskunnasta, myös ekologinen resilienssi. Ehdottaisin ainakin huomautuksen muuttamista.

**Comment by YSA-kokous** [comment]
Poistetaan huomautus.
