### ISSUE TITLE
kielellinen variaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5249]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kielellinen variaatio 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Nyt KÄ muuntelu (15 Biologia), vaihtelu (00 Yleistermit), variaatiot KÄ parafraasit (85 Kielitiede; 87 Kirjallisuus; 89 Musiikki; 90 Taide yleensä) (oik. variaatiot on KÄ muunnelmat (00))

Mutta Kielitieteen asiasanastossa: parafraasi LT semantiikka, Edelleen, Kielitieteen asiasanasto: variaatio KT kielimuoto LT sosiolingvistiikka ST lasten kieli ST miesten kieli ST tilanteinen vaihtelu ST sosiaalinen vaihtelu ST tyylillinen vaihtelu ST naisten kieli RT murteet. Olen jättänyt Helkassa kta-sanastoon, tällä hetkellä yksittäisiä termejä >260 kappaletta; ketjuissa lisää. Mikä olisi tälle hyvä YSA:n termi? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [kielellinen variaatio](http://finto.fi/yse/fi/page/Y505249)

**Comment by mirmaid** [comment]
KTOssa termi on variaatio (kielitiede). Vaihtelu-termiä käytetty runsaasti kielitieteellisessä aineistossa.

**Comment by mirmaid** [comment]
Selkeytystä vielä:

YSA:
variaatio KÄ vaihtelu (ryhmä 00), muuntelu (ryhmä 15)
variaatiot KÄ muunnelmat (ryhmä 00)

KTO:
variaatio (kielitiede) KT kielimuoto

**Comment by mirmaid** [comment]
Onko tarpeen ottaa YSAan _variaatio (kielitiede)_ tai _kielellinen variaatio_, vai riittääkö nykyinen KÄ _vaihtelu_, jota on siis myös runsaasti käytetty kielitieteen yhteydessä?

**Comment by krinay** [comment]
KULAssa (ja KULOssa) on termi muuntelu - KT variaatio, RT toisinnot. Termi toisinnot on nykyisin myös YSAssa. 

Termiä muuntelu on käytetty sisällönkuvailussa paljon KULAn tarkoittamassa merikityksessä. Folkloristiikassa sitä käytetetään, kun tutkitaan suullisen perinteen (esimerkiksi tietyn kansansadun) ajallista, alueellista, sosiaalista tms. vaihtelua.  

KULOssa muuntelun yläkäsitteenä on kulttuuriset ilmiöt, käsitteen toisinnot yläkäsite on kulttuuriset tuotokset. Molemmille käsitteille (muuntelu ja toisinnot) on tarvetta sisällönkuvailussa.

**Comment by mariaforsen** [comment]
Allärsissa vaihtelu=omväxling, eli se ei toimi kielellisestä vaihtelusta ollenkaan. Kielellinen vaihtelu=språkvariation/språklig variation olisi ruotsiksi tosi hyvä (on myös Svenska ämnesordissa). On yleensäkin hyvin vaikeaa saada "yleistermejä" kattamaan samoja (varsinkin spesifisempiä) merkityskenttiä (jos niitä "niputtaa yhteen", mieluummin kuin erittelee selkeästi - selkeä erottelu on usein edellytys oikeiden/täsmäävien vastineiden saamiseksi).

**Comment by AuHo22** [comment]
KTOssa on variaatio (kielitiede) yläkäsitteenä sosiolingvistiset ilmiöt ja sen yläpuolella vielä kielelliset ilmiöt. Jotenkin ihmettelen, että KTOssa astevaihtelun yläkäsite puolestaan on vaihtelu eikä samoin jokin kielellinen ilmiö - on myös kielellistä vaihtelua vaikka ei välttämättä sosiolingvististä. Olen samaa mieltä siitä, että termi vaihtelu on liian yleisluontoinen ja monille eri aloille haarautuva.  Kielellinen vaihtelu antaa enemmän osumia googlaamalla kuin kielellinen variaatio; toisaalta KTOssa on jo käytetty termiä variaatio (kielitiede)?

**Comment by YSA-kokous** [comment]
variaatio (kielitiede) vai kielellinen vaihtelu - kysytään Kotuksesta

**Comment by mariaforsen** [comment]
Sv. språkvariation ET språklig variation
