### ISSUE TITLE
talouseliitti, taloudellinen eliitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5251]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

talouseliitti, taloudellinen eliitti 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

Rikkaat, jotka pyrkivät ohjaamaan poliittista toimintaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Dark money : how a secretive group of billionaires is trying to buy political control in the US 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [talouseliitti, taloudellinen eliitti](http://finto.fi/yse/fi/page/Y505251)

**Comment by mirmaid** [comment]
YSAssa on _eliitit_ ja _poliittinen eliitti_. Melindassa 3 x _taloudellinen eliitti_, eliitit + talous -yhdistelmää käytetty myös. YSAssa on myös _rikkaat_.

**Comment by YSA-kokous** [comment]
taloudellinen eliitti

**Comment by mariaforsen** [comment]
Sv. ekonomisk elit ET ekonomiska eliten
