### ISSUE TITLE
ylikansallinen kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5252]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ylikansallinen kulttuuri](http://www.yso.fi/onto/ysa/Y100430) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT globaali kulttuuri 

#### Perustelut ehdotukselle   

YSOssa eng. vastine global culture 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. övernationell kultur > global kultur
