### ISSUE TITLE
kvitteni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5254]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kvitteni 

#### Ehdotettu termi englanniksi   

Quince 

#### Ehdotettu termi ruotsiksi   

kvitten 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hedelmät](http://www.yso.fi/onto/yso/p4647) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Kvitteni 
LCSH : Quince 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Water-based boundary lubrication with biomolecule additives on diamond-like carbon and stainless steel surfaces 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [kvitteni](http://finto.fi/yse/fi/page/Y505254)

**Comment by PaiviLipsanen** [comment]
kvitteni (Cydonia oblonga / laji), yläkäsite: kvittenit (Cydonia / suku), tämän yläkäsite ruusukasvit (Rosaceae / heimo). Kvitteni on sekä kasvi, että sen hedelmä.
https://fi.wikipedia.org/wiki/Kvitteni
https://finto.fi/kassu/fi/page/k53056

**Comment by mirmaid** [comment]
Hämmentävä aineisto! Tähänhän sopisi myös https://github.com/Finto-ehdotus/YSE/issues/4502 :smile:

**Comment by mariaforsen** [comment]
Sv. kvitten
