### ISSUE TITLE
kielitietoisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5255]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kielitietoisuus 

#### Ehdotettu termi ruotsiksi   

språkmedvetenhet 

#### Ehdotettu termi englanniksi   

language awareness 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Kielitietoisuus on uusissa opetussuunnitelman perusteissa (varhaiskasvatus, esiopetus, perusopetus, lukiokoulutus) keskeinen koulun/oppilaitoksen toimintakulttuurin kehittämistä ohjaava periaate 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://hyvatkaytannot.oph.fi/etusivu/ 

**Ehdottajan nimi:** Katri Kuukka 
**Ehdottajan organisaatio:** Opetushallitus 
**Ehdottajan sähköpostiosoite:** katri.kuukka@oph.fi **Termiehdotus Fintossa:** [kielitietoisuus](http://finto.fi/yse/fi/page/Y505255)

**Comment by AuHo22** [comment]
Kielellinen tietoisuus /språklig medvetenhet on YSAssa

**Comment by mirmaid** [comment]
http://www.kieliverkosto.fi/article/kieli-ja-tekstitietoisuutta-kouluun-kielitietoinen-koulu-ja-aidinkielen-ja-kirjallisuuden-opetus/

**Comment by mirmaid** [comment]
YSA: _kielellinen tietoisuus_: Tietoisuus kielellisistä käsitteistä (esimerkiksi äänne, sana, lause) ja tietoisuus kielen muodosta, kuten sen äännerakenteista, merkityksellisistä yksiköistä sekä lausekkeiden ja lauseiden rakentumisesta.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Jos otetaan, ehdottaisin muotoa _kielitietoinen opetus_. 
http://www.utu.fi/fi/sivustot/koulutus-ja-kehittamispalvelut/kulttuurinen-moninaisuus/kielitietoinen-opetus/Sivut/home.aspx

**Comment by mariaforsen** [comment]
Ruotsiksi ei ainakaan voida pitää sekä språkmedvetenhet että språklig medvetenhet, joten siinä tapauksessa kielitietoinen opetus.

**Comment by YSA-kokous** [comment]
kielitietoinen opetus

**Comment by mariaforsen** [comment]
Sv. språkmedveten undervisning ET språkligt medveten undervisning

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tätä. Julkaisu on https://journal.fi/afinlavk/issue/view/4674

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8169
