### ISSUE TITLE
numeerinen lukutaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5256]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

numeerinen lukutaito 

#### Ehdotettu yläkäsite YSOssa (LT)   

[monilukutaito](http://www.yso.fi/onto/yso/p28850) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Numeerista lukutaitoa ei pysty muuten erottelemaan muusta lukutaidosta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/matikkanalka 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [numeerinen lukutaito](http://finto.fi/yse/fi/page/Y505256)

**Comment by mirmaid** [comment]
YSAssa on myös vastaava _visuaalinen lukutaito_. Tämä voisi olla perusteltu vaikka sisältyykin monilukutaitoon, koska on selvästi erotettavissa / varmasti oma tutkimuskohteensa. Ks. myös http://www.fsd.uta.fi/menetelmaopetus/numerolukutaito/numerolukutaito_tiedonkeruu.html

Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. numerisk läskunnighet ET numerisk färdighet ET numerisk läsfärdighet
