### ISSUE TITLE
leikkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5257]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leikkaus](http://www.yso.fi/onto/ysa/Y96820) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

leikkaus (audiovisuaalinen aineisto) omaksi termikseen, tai ryhmien 45 ja 96 lisääminen 

#### Perustelut ehdotukselle   

Elokuvaleikkaus-termiä ei käytetä esim. tosi-tv:n/tv-sarjojen tms. leikkaamisesta vaan silloin puhutaan vain leikkauksesta. Editointi-termiä saatetaan käyttää myös, mutta ammattilaisten mukaan se ei ole aivan niin osuva. 

#### Ehdottaja   

KAVI 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Leena selvitti:

Leikkaus-termin 860 viitteestä noin 25 % käsittelee nimenomaan elokuvan, televisio-ohjelman, radio-ohjelman tai videon leikkaamista.

Monessa viitteessä oli ketjutus elokuva : leikkaus, vaikka ysassa olisi se oma elokuvaleikkaus-termikin, jonka nimenomaan olisi pitänyt korvata tuo ketjutettu termi. Elokuvaleikkaukselle Melindassa tuli, kun sitä muutama viikko sitten tutkin, vain kolme osumaa.

Editointi-termiäkin (690 viitettä) katselin Melindasta, ja siellä suurin osa (en laskenut niin tarkkaan kuin tuon leikkaus-termin yhteydessä) viitteistä menee myös tähän kuvan, äänen tai musiikin käsittelyyn, ja selkeästi pienempi osa viitteistä käsitteli tekstien editoimista.

Monessa viitteessä on käytetty sekä editointi että leikkaus -termiä.

**Comment by mirmaid** [comment]
Kommentoitu Ylellä:

_“Minusta suomenkielessä leikkaaminen ja editoiminen tarkoittaa aivan samaa asiaa. Erikseen käytämme sanaa koostaminen, silloin kun emme voi juurikaan puuttua taiteellisiin ratkaisuihin, sisältöön, dramaturgiaan, rakenteeseen tai rytmiin.”_

_“Leikkaus-termi tuli käyttöön Suomessa joskus 1920-30-luvulla kun filmiä konkreettisesti leikattiin. Filminleikkaus terminä voi hyvin aina 90-luvulle saakka, jolloin itse filminleikkaus työnäkin alkoi vähetä. 
Sitä ennen tapahtui kuitenkin kuvanauhan keksiminen (1950-1960-luku) ja sillä tapahtuvaa koostamista alettiin Suomessa jostain syystä kutsua (video)editoimiseksi tai montteeraamiseksi. 
Nyttemmin tietokoneella kun leikataan niin vanha termikin tuntuu käyvältä. Paljon kuitenkin käytetään myös editointi-sanaa. Esimerkiksi omat TV-uutisemme siirtyi muutama vuosi takaperin käyttämään pelkästään editoija-titteliä. Mielestäni leikkaus ja editointi tarkoittaa nykyajan ammattikielessä aivan samaa asiaa. 
Allekirjoittanut on vahvasti vanhan leikkaus/leikkaaja-termin kannattaja, olenhan aloittanut urani filmileikkaajana. Korjaankin usein toimittajan tai ohjaajan sanomiset editissä olosta, että nyt olet kylläkin leikkaamossa.”_

_“Termien eroon minä vastaisin, että alun alkaen videonauhaa editoitiin ja filmiä leikattiin. Sittemmin termejä on alettu käyttää sikin sokin. Todennäköisesti ihan jo siitä syystä, että elokuvien ja tv-ohjelmien leikkaaminen ei enää ole niin erilaista kuin ammoin, kun tekniikka ja leikkausohjelmat ovat hyvin pitkälti molemmilla aloilla sama, esim. Avidilla leikataan niin telkkariin kuin elokuviin. Tämä selitys tuli nyt kyllä mutu-tuntumalla heittäen. 
Jos aiheen perässä lähtisin googlettamaan, väittäisin, että kaikki variaatiot tulisi käytyä läpi:
leikkaus, filmileikkaus
editointi, video editointi
tv-ohjelmien leikkaus/editointi
ja englanniksi menisin hauilla editing, film editing, video editing.
Syynä tuohon haarukointiin olisi nimenomaan se, että termejä käytetään niin sekaisin. Ainut asia, josta olen tarkka on se, että minä olen ammatiltani leikkaaja, en editoija :) Ja oikeastaan, nyt kun olen noita sanoja pyöritellyt ja maistellut, väittäisin, että editointi alkaa olla terminä kuihtumaan ja kuolemaan päin, leikkaaja/leikkaaminen mennä porskuttaa.”_

**Comment by mirmaid** [comment]
Leena:
Ehdottaisin, että leikkaus-termiin voisi lisätä ryhmät 45 ja 96, koska audiovisuaalisen aineiston leikkaus on Melinda-viitteissä huomattavasti yleisempi kuin metsä- ja metalliteollisuuden leikkaukset.

Elokuvaleikkaus-termin voisi vastapainoksi poistaa, koska sitä ei juuri käytetä.

Ohjaustermi leikkaus (audiovisuaalinen aineisto) KÄYTÄ editointi olisi tietysti yksi mahdollisuus, jos halutaan ohjeistaa käyttämään vain jompaakumpaa. Käytettävään kieleen suhteutettuna se ei kuitenkaan omassa korvassani kuulosta hyvältä (johtunee tästä työpaikasta).

**Comment by mirmaid** [comment]
Ruotsiksi leikkaus on nyt YSOssa _skärning_, KT klippning, beskärning. Allärsissa kaikki kolme ovat käytettävinä termeinä. 

1 (kuosi; puvun tms) skärning [-en,-ar,-arna], tillskärning [-en,-ar,-arna], snitt [-et,=,-en]
Takissa on kaunis leikkaus/Takki on kauniisti leikattu Kappan har snygg skärning
2 (leikkaaminen) beskärning [-en,-ar,-arna]
3 lääk (leikkauksen tekeminen) operation [-en,-er,-erna]
4 geom sektion [-en,-er,-erna]
5 tekn snitt [-et,=,-en], skjuvning [-en,-ar,-arna]
leikkauspinta snittyta
6 tal (menojen vähentäminen) nedskärning [-en,-ar,-arna]
7 (elokuvan) klippning [-en,-ar,-arna]
Ohjaajan panos on tärkeä pitkän elokuvan leikkauksessa Regissörens insats är viktig i klippningen av en långfilm
8 (piirto) inskärning [-en,-ar,-arna]
9 (tieleikkaus) schakt [-en,-er,-erna]

**Comment by mirmaid** [comment]
Melindassa ainakin

- materiaalin leikkaus (paperi, metalli)
- nurmikon, puiden, pensaiden
- elokuvan, videon
- hiusten
- askartelu (paperityöt), käsityö
- talous (vähän)
- lääketieteellisenä (vähän)

**Comment by mariaforsen** [comment]
Periaatteessa on sekä klippning (materiaalin, hiusten, elokuvan/videon, askartelu - tavallisesti saksilla), skärning (vahvemman/paksumman materiaalin esim. metallityö, tietynlainen askartelu - veitsellä tms.) ja beskärning (eng. pruning, eli puiden ja pensaiden) tarpeen erillisinä termeinä ruotsiksi. Kaikki nämä ovat myös mukana Svenska ämnesordissa erillisinä päätermeinä. 

Talous on nedskärningar ja lääketiede operation jne. Eli nämä yllä olevat eivät kata niitä merkityskenttiä ollenkaan.

Hiustenleikkaus=hårklippning erillisenä terminä jo mukana.

**Comment by mirmaid** [comment]
leikkaus (hiusten), leikkaus (hiukset) KÄ hiustenleikkaus
leikkaus (talous) KÄ menoleikkaukset
leikkaus (hoito), leikkaus (lääketiede) KÄ leikkaushoito
leikkaus (puutarhanhoito/kasvit)
leikkaus (työstö)
leikkaus (käsityö/vaatteet), entä askartelu?
leikkaus (editointi)

**Comment by YSA-kokous** [comment]
leikkaus (hiusten), leikkaus (hiukset) KÄ hiustenleikkaus
leikkaus (talous) KÄ menoleikkaukset
leikkaus (hoito), leikkaus (lääketiede) KÄ leikkaushoito
leikkaus (kasvit)
leikkaus (työstö)
leikkaus (tekstiilit)
leikkaus (editointi) KT audiovisuaalinen leikkaus

**Comment by mariaforsen** [comment]
Sv.
klippning (hår) ANV hårklippning
nedskärningar ANV utgiftsnedskärningar
beskärning (växter)
skärning (bearbetning)
skärning (textilier) ET tillskärning
klippning (redigering)
