### ISSUE TITLE
elokuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5258]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elokuvaus](http://www.yso.fi/onto/ysa/Y95003) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Elokuvan jne. kuvaus pitäisi saada erotettua. 

#### Perustelut ehdotukselle   

Elokuvaus-termi ei ole toimiva (liian suppea ja vieras); pelkkää kuvaus-termiä on käytetty siinä merkityksessä myös. 

#### Ehdottaja   

YSA-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/3154

**Comment by mirmaid** [comment]
Leena selvitti:

Melinda:
**kuvaus**
Melinda: 386 viitettä, joista ainakin 85 käsitteli liikkuvan kuvan tallentamista (elokuva, tv-, video, pois jätetty vedenalainen kuvaus)
**elokuvaus**
Melinda 767 viittettä
**televisiokuvaus**
Melinda 77 viitettä
**videokuvaus** 
Melinda 633 viitettä
**trikkikuvaus**
Melinda 28 viitettä

Viitteiden määrän perusteella elokuvaus ei siis ole mikään suppea.

**Comment by mirmaid** [comment]
Leena:
Jos näitä halutaan yhdistellä, minulle tulee lähinnä mieleen, että muodostettaisiin sulkutarkenteella uusi termi, esim. kuvaus (liikkuva kuva), johon sitten ohjattaisiin elokuvaus, televisiokuvaus ja videokuvaus. Erikoistermit trikkikuvaus, vedenalainen kuvaus voisi jättää suppeammiksi termeiksi.

Vai ottaa kuvaus (liikkuva kuva) uudeksi termiksi ja kaikki jo käytössä olevat sen alle: elokuvaus, televisiokuvaus, videokuvaus?

Siitä en ole ollenkaan varma, onko tuo esimerkin sulkutarkenne paras vaihtoehto ja miten se olisi luontevinta ruotsiksi ja englanniksi.

Helpoin vaihtoehto olisi jättää kaikki ennalleen.

**Comment by satuniininen** [comment]
Kannatan Mirjan ensimmäistä ehdotusta, eli uusi termi, johon ohjataan elokuvaus, televisiokuvaus ja videokuvaus.

**Comment by LeKorsu** [comment]
Tästä on jo sen verran aikaa, että on päässyt unohtumaan, mitä olen ajanut ehdotuksillani takaa... Mutta kun nyt taas mietin tätä, niin tuo kuvaus (liikkuva kuva) jne kuulostaa sillä lailla edelleen hyvältä, että se ei ole välineriippuvainen. Toisaalta se on vähän kökkö, jos halutaan että ei käytetä ollenkaan noita erikoistermejä. Ja löytyykö sille luonnollinen vastine på svenska? 

Videokuvaus taas on yleisenä käsitteenä hyvin ymmärretty ja sopii myös erilaisen sosiaalisen median videokllippeihin, mutta sen käyttäminen pääterminä siten että elokuvaus ja televisiokuvaus ohjattaisiin sinne, ei taas sovi, koska kyse on eri asiasta (välineet osittain, taiteellinen tyyli)

Alan itse sittenkin taipua tuon jälkimmäisen ehdotuksen kannalle, koska näen tärkeänä, että elokuvaus ja televisiokuvaus säilyvät omina termeinään, eli tähän tapaan:
kuvaus (liikkuva kuva)
elokuvaus
ilmakuvaus
televisiokuvaus
trikkikuvaus
vedenalainen kuvaus 
videokuvaus

**Comment by mariaforsen** [comment]
Ruotsin kannalta tärkeää että nykyiset suppeammat termit (eli elokuvaus, ilmakuvaus, televisiokuvaus, trikkikuvaus, vedenalainen kuvaus, videokuvaus) säilyvät. Jos näiden lisäksi luodaan uutena kuvaus (liikkuva kuva) niin mikä on toisen kuvaus-termin sulkutarkenne? Ja onko todella kuvaus (liikkuva kuva) tarpeen? Täytyy myös huomioida fotografering vs. filmning (ruotsiksi ei ole mitään molempia kattavaa termiä, vaan täytyy aina "ottaa kantaa" onko kyseessä valokuva vai elokuva).

kuvaus 
1 (elokuvaaminen) filmning [-en,-ar,-arna], filminspelning [-en,-ar,-arna]
2 (valokuvaaminen) fotografering [-en,-ar,-arna]
3 (kerronta) beskrivning [-en,-ar,-arna], skildring [-en,-ar,-arna]
4 (kuvailu) framställning [-en,-ar,-arna]

**Comment by LeKorsu** [comment]
Toisen termin sulkutarkenteesta. Ysassa nyt yleistermien luokassa kuvaus ja ysossa kuvaus (luonti) / sv skildring. Siksi tuo toinen sulkutarkenne.

**Comment by OutiHintikka** [comment]
elokuvaus ja televisiokuvaus omina termeinään, vaikka kuvaajat ovat usein samoja - ainakin Suomessa

**Comment by mariaforsen** [comment]
Ruotsin kannalta hankala tilanne. Sanastossa on jo elokuvaus=filmning. Sen lisäksi pitäisi sitten laittaa filmning uudestaan ("kuvaus (liikkuva kuva)" tai jos olisi mahdollista laittaa inspelning (rörlig bild), mutta siinä tapauksessa täytyy tehdä jotain nykyiselle Allärs-termille inspelning (joka on kyllä ongelmalistalla sekin).

**Comment by LeKorsu** [comment]
Entäpä jos sulkutarkenne olisikin tallennus eikä liikkuva kuva? Sopiiko tuo inspelning siihen? Sen alla voisi sitten säilyttää erilliset elokuvaus=filmning, televisiokuvaus=? jne.

**Comment by siikaa** [comment]
Minusta myös kuvaus (liikkua kuva) voi olla kunhan nuo muut jo olemassaolevat säilyvät. Siis elokuvaus, videokuvaus jne.

**Comment by mirmaid** [comment]
Tai sitten poistetaan koko kuvaus-termi, niin elokuvan kuvaamisesta on pakko käyttää elokuvaus-termiä :triumph:.

**Comment by mariaforsen** [comment]
Kuvaus (tallennus) ei sinänsä kerro minkälaisesta kuvauksesta on kysymys, voisi periaatteessa yhtä hyvin olla skildring siinä tapauksessa, eli ongelmallista.

**Comment by YSA-kokous** [comment]
elokuvaus > sv. filminspelning
kuvaus (liikkuva kuva) = filmning
