### ISSUE TITLE
tanssihistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5259]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tanssihistoria 

#### Ehdotettu termi ruotsiksi   

danshistoria 

#### Ehdotettu termi englanniksi   

dance history 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuurihistoria](http://www.yso.fi/onto/yso/p18452) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2008102022> 

#### Vaihtoehtoiset termit ja ilmaisut   

tanssin historia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

1909–1929 : the Ballets russes at the opera 

#### Perustelut ehdotukselle   

Analogia: elokuvahistoria, musiikinhistoria, taidehistoria, teatterihistoria. (Ja huomautus koskien LT-suhdetta: muissa oleva LT historia pitäisi olla LT kulttuurihistoria, koska kyseiset elokuva jne. ovat osa kulttuuria.) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [tanssihistoria](http://finto.fi/yse/fi/page/Y505259)

**Comment by OutiHintikka** [comment]
kannatan! meillä on jo teatterihistoria ja elokuvahistoria.

**Comment by mirmaid** [comment]
Miksipä ei...melkein kaikki Melindan 7 viitettä liittyvät venäläiseen balettiin, mitenkäs kävisikö tämä myös esim. tähän teokseen: _Cultural and musical dimensions of Goa trance and early psychedelic trance in Finland: the history, translation and localization of an internationally mobile electronic dance-music scene_?

**Comment by OutiHintikka** [comment]
Ehdottomasti käy ja olisi jopa hyvä termi em. teoksen yhteydessä. Noiden viitteiden syynä on tod.näk. se, että klassista balettia on eniten tutkittu.  Itsessään termi ei mielestäni ota kantaa siihen, minkä alueen tanssihistoriaa tutkitaan.

/Outi Hintikka
BTJ

Lähettäjä: mirmaid [mailto:notifications@github.com]
Lähetetty: perjantai 22. syyskuuta 2017 13.50
Vastaanottaja: Finto-ehdotus/YSE <YSE@noreply.github.com>
Kopio: Hintikka Outi <outi.hintikka@btj.fi>; Comment <comment@noreply.github.com>
Aihe: Re: [Finto-ehdotus/YSE] tanssihistoria (#5259)


Miksipä ei...melkein kaikki Melindan 7 viitettä liittyvät venäläiseen balettiin, mitenkäs kävisikö tämä myös esim. tähän teokseen: Cultural and musical dimensions of Goa trance and early psychedelic trance in Finland: the history, translation and localization of an internationally mobile electronic dance-music scene?

**Comment by mariaforsen** [comment]
Sv. danshistoria

**Comment by mirmaid** [comment]
Elokuvahistoria, musiikinhistoria, taidehistoria, teatterihistoria, tanssihistoria LT kulttuurihistoria? Vastaavanlaisia ratkaisuja kyllä on YSOssa.

**Comment by mirmaid** [comment]
Ei lisätä suhteita.
