### ISSUE TITLE
suunnitteluvirheet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5260]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suunnitteluvirheet 

#### Ehdotettu termi ruotsiksi   

planeringsmisstag 

#### Ehdotettu termi englanniksi   

planning errors 

#### Ehdotettu yläkäsite YSOssa (LT)   

[virheet](http://www.yso.fi/onto/yso/p148) 

#### Assosiatiiviset (RT)   

[suunnittelu](http://www.yso.fi/onto/yso/p1377) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 

#### Perustelut ehdotukselle   

termiparin suunnittelu + virheet -sijaan (Melindassa tällä yhdistelmällä 16 osumaa) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suunnitteluvirheiden aiheuttamat vakavat tulipalo- ja muut suuronnettomuusriskit / Esko Kaukonen 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi 
**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suunnitteluvirheet](http://finto.fi/yse/fi/page/Y505260)

**Comment by mirmaid** [comment]
Yhdyssanamuotoa ei toistaiseksi käytetty Melindassa.

Samantyyppisiä YSAssa _mittausvirheet, ohjelmointivirheet, rakennusvirheet_.

**Comment by mariaforsen** [comment]
Sv. planeringsfel ET planeringsmisstag
