### ISSUE TITLE
puskurialueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5264]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puskurialueet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[alueet](http://www.yso.fi/onto/yso/p9978) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 

#### Perustelut ehdotukselle   

Tuulivoima-alueiden puskurialueet
Huom. ”puskurialue” saattaa esiintyä myös kemiallisena terminä (titrauksen yhteydessä). Puskurialueita voi tietysti olla muidenkin kuin tuulivoima-alueiden ympärillä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pirkanmaan maakuntakaava 2040 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [puskurialueet](http://finto.fi/yse/fi/page/Y505264)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1200

_Puskurivyöhykkeet_-muotoa käytetty 2 kertaa Melindassa. YSAssa on _suojavyöhykkeet_ ja _suoja-alueet_.

**Comment by mariaforsen** [comment]
Sv. buffertzoner/områden

**Comment by YSA-kokous** [comment]
KÄ suoja-alueet
