### ISSUE TITLE
tanssiryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5265]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssiryhmät](http://www.yso.fi/onto/ysa/Y104534) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT balettiseurueet 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi 

#### Perustelut ehdotukselle   

Balettiseurueita etsivälle ei välttämättä tule mieleen etsiä asiasanalla "tanssiryhmät".

**Comment by OutiHintikka** [comment]
KT-lisäys ok!
