### ISSUE TITLE
selviytymispelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5267]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

selviytymispelit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit](http://www.yso.fi/onto/yso/p6062) 

#### Tarkoitusta täsmentävä selite   

konsolipelit, joissa idea on jonkinlainen selviytyminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

konsolipelit 

#### Perustelut ehdotukselle   

konsolipelit, joissa idea on jonkinlainen selviytyminen, tällaisille ei nykyisellään ole hyvää genreä kuvaamaan 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

**Ehdottajan nimi:** Mari Pitkänen 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** mari.pitkanen@btj.fi **Termiehdotus Fintossa:** [selviytymispelit](http://finto.fi/yse/fi/page/Y505267)

**Comment by mariaforsen** [comment]
Sv. överlevnadsspel
