### ISSUE TITLE
konsolipelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5268]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[konsolipelit](http://www.yso.fi/onto/ysa/Y165851) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi KT-muodoksi termille "videopelit" (tai toisinpäin) 

#### Perustelut ehdotukselle   

Käsitteet "konsolipeli" ja "videopeli" tarkoittavat samaa asiaa, ks. esim. suomenkielinen Wikipedia (https://fi.wikipedia.org/wiki/Pelikonsoli ja https://fi.wikipedia.org/wiki/Videopeli) ja vastaavasti englanninkielinen Wikipedia (https://en.wikipedia.org/wiki/Console_game, https://en.wikipedia.org/wiki/Video_game ja https://en.wikipedia.org/wiki/Video_game_console): tiivistäen sanottuna pelikonsolilla pelataan konsolipelejä eli videopelejä. Vrt. myös LCSH:n termi Video games. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@gmail.com

**Comment by mirmaid** [comment]
Wikipedian mukaan: Videopelin pelaamiseen tarvitaan alusta, joka voi olla esimerkiksi henkilökohtainen tietokone, pelikonsoli, käsikonsoli tai matkapuhelin. Näin videopeli olisi oikeastaan kai lähinnä sama kuin digitaalinen peli, ja konsolipelit sekä tietokonepelit (= pc-pelit) sen alakäsitteitä?

**Comment by osma** [comment]
Komppaan @mirmaid:ia. Konsolipeli on videopeli (eli digitaalinen peli), jota pelataan pelikonsolilla.

**Comment by henriyli** [comment]
Komppaan kahta edellistä. Videopeli on laajempi käsite joka kattaa muitakin peljä kuin pelkät konsolipelit.

**Comment by YSA-kokous** [comment]
Ei muutosta. Määritelmiä olisi hyvä lisätä.
