### ISSUE TITLE
sosiaalihuoltolaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5269]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sosiaalihuoltolaki 

#### Ehdotettu termi englanniksi   

Social Welfare Act 

#### Ehdotettu termi ruotsiksi   

Socialvårdslag 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 
[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa 

#### Tarkoitusta täsmentävä selite   

http://www.finlex.fi/fi/laki/alkup/2014/20141301 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sosiaalihuoltolaki ja sosiaalinen kuntoutus :kuntakyselyn tulokset /Puromäki, Henna & Kuusio, Hannamaria & Tuusa, Matti & Karjalainen, Jarno. 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [sosiaalihuoltolaki](http://finto.fi/yse/fi/page/Y505269)

**Comment by mariaforsen** [comment]
Sv. socialvårdslag
