### ISSUE TITLE
X Factor -laulukilpailu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5270]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

X Factor -laulukilpailu 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

-merkittävä laulukilpailu; -kirjassa toinen pääteema 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Saara Aalto : no fear 

**Ehdottajan nimi:** Kaija Karjalainen 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** kaija.karjalainen@btj.fi **Termiehdotus Fintossa:** [X Factor -laulukilpailu](http://finto.fi/yse/fi/page/Y505270)

**Comment by jtuohini** [comment]
630-kentän asiaa, kun on kyse televisio-ohjelmasta, joten auktorisointi mieluummin teosnimenä kuin asiasanana. Vrt. LCSH:na käytetty **X-Factor (Television program)** ja englanninkielisen Wikipedian **The X Factor**, **X Factor (Albanian TV series)**, **The X Factor (Arabic TV series)** jne. YSA-asiasanaksi ko. ohjelmaa koskien toki **laulukilpailut**, **musiikkiohjelmat** ja **televisio-ohjelmat**, mutta onko oikeasti tarve tehdä jokaisesta ohjelmasta/ohjelmaformaatista oma asiasanansa? Jos formaattitasosta haluaisi asiasanan, niin olisiko se muotoa _X Factor -laulukilpailut_, _X Factor -televisio-ohjelmat_ vai jotakin muuta, ja jos viitattaisiin yksittäiseen maasarjaan, niin miten ensisijaisen hakutiedon muotoilu? (RDA:n mukaan, toivottavasti.)

**Comment by mirmaid** [comment]
Tämä onkin mielenkiintoinen, Euroviisut on kuitenkin LCSH:n mukaan tapahtuma, ei teos.

**Comment by jtuohini** [comment]
Eittämättä! "111 2_ |a Eurovision Song Contest" on merkitty RDA-muodoksi, mutta toisaalta " 111 2_ |a Melodifestivalen |c (Sweden)":n yhteydessä on sanottu, että "THIS 1XX FIELD CANNOT BE USED UNDER RDA UNTIL THIS RECORD HAS BEEN REVIEWED AND/OR UPDATED". Eli kumpaan itse asiassa halutaan viitata: itse kilpailuun, vai siitä "kertovaan" televisio-ohjelmaan, siis tapahtumaan vai teokseen?

**Comment by mirmaid** [comment]
Voidaan ainakin huoletta auktorisoida YSAan 150-kentässä, koska se on varmuudella väärin (ainakin angloamerikkalaisesta näkökulmasta). Ihmettelen miten näissä tv-formaattikilpailuissa edes voidaan erottaa kummasta puhutaan, ohjelma on kilpailu on ohjelma (vai voiko ajatella että voisi periaatteessa järjestää x-factor skabat ilman tv-kameroita, mutta tv-ohjelmaa ei voikein voisi kutsua x-factoriksi ilman sitä laulukilpailua...).

**Comment by mariaforsen** [comment]
Sv. The X Factor
