### ISSUE TITLE
aistimarkkinointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5271]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aistimarkkinointi 

#### Ehdotettu termi englanniksi   

sensory marketing (sensory bränding) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[markkinointi](http://www.yso.fi/onto/yso/p5878) 

#### Assosiatiiviset (RT)   

[neuromarkkinointi](http://www.yso.fi/onto/yso/p27614) 

#### exactMatch   

Sensory branding : https://en.wikipedia.org/wiki/Sensory_branding 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Audio branding: Using sound to build your brand 

#### Perustelut ehdotukselle   

täydentää markkinoinnin alakäsitteitä. 

**Ehdottajan nimi:** Henna Paajala 
**Ehdottajan sähköpostiosoite:** henna.paajala@oamk.fi **Termiehdotus Fintossa:** [aistimarkkinointi](http://finto.fi/yse/fi/page/Y505271)

**Comment by jtuohini** [comment]
Olisiko sopiva RT **mainosmusiikki**?

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mariaforsen** [comment]
Sv. sinnesmarknadsföring ET sensorisk marknadsföring
