### ISSUE TITLE
gaelinkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5272]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gaelinkielinen kirjallisuus 

#### Vaihtoehtoiset termit ja ilmaisut   

gaelin kielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Ei ole YSA:ssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siikaaho@hel.fi **Termiehdotus Fintossa:** [gaelinkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505272)

**Comment by mirmaid** [comment]
10 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. gaelisk litteratur
