### ISSUE TITLE
oromonkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5273]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oromonkielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Ei YSA:ssa. Afrikan kolmanneksi puhutuin kieli. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [oromonkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505273)

**Comment by mirmaid** [comment]
Ei Melindassa.
