### ISSUE TITLE
pandžabinkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5274]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pandžabinkielinen kirjallisuus 

#### Perustelut ehdotukselle   

Ei YSA:ssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [pandžabinkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505274)

**Comment by mirmaid** [comment]
Kerran Melindassa.
