### ISSUE TITLE
sindhinkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5276]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sindhinkielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Ei YSA:ssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [sindhinkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505276)

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. litteratur på sindhi ET sindhilitteratur ET sindhisk litteratur
