### ISSUE TITLE
viittomakielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5280]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viittomakielinen kirjallisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi: Heinähattu, Vilttitossu ja ärhäkkä koululainen 

#### Perustelut ehdotukselle   

Ensimmäinen kokonaan viitottu satukirja _Heinähattu, Vilttitossu ja ärhäkkä koululainen julkaistiin marraskuussa 2016 http://yle.fi/uutiset/3-9301337. 

**Ehdottajan nimi:** Kirsi Siika-aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [viittomakielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505280)

**Comment by jtuohini** [comment]
Pitäisikö olla lisäksi omat ST-terminsä kirjallisuudelle, joka on suomalaisella viittomakielellä, suomenruotsalaisella viittomakielellä jne? (En tarkoita, että pitäisi automaattisesti ottaa nyt sanastoon kaikki, mutta muistutukseksi, jos kuitenkin tarve kuvailla suoraan täsmällisemmin kielen mukaisesti eikä viittomakielistä kirjallisuutta yleensä käsittelevää aineistoa.)

**Comment by mirmaid** [comment]
Melindassa 2 viitettä.

**Comment by mariaforsen** [comment]
Sv. litteratur på teckenspråk ET teckenspråkig litteratur
