### ISSUE TITLE
disc jockeyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5281]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[disc jockeyt](http://www.yso.fi/onto/ysa/Y101088) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastossa on tiskijukat referenssiterminä, mietin vain voisiko tiskijukat olla se käytettävä  termi. 

#### Perustelut ehdotukselle   

Itselleni disc jockey kuulostaa tosi vanhanaikaiselta. 

#### Ehdottaja   

BTJ 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Korvattuna terminä on myös DJ:t, joka on MUSAssa erillinen asiasana:

**disc jockeyt:** Henkilö, joka soittaa äänitettyä musiikkia tanssijoille. Joissakin musiikinlajeissa disc jockeyn roolia on kehitetty itsenäisen taiteilijan suuntaan. (KT tiskijukat)

**DJ:t:** Populaarimusiikin esiintyvä taiteilija, joka käyttää esityksensä aineistona äänilevyjen soittamista, ohjelmointia, sämpläystä jne. omaperäisellä tavalla (mm. scratching, sämpläys, miksaus).

Onkohan erottelu käytännössä toimiva? Jos ero halutaan säilyttää, voisi tosiaan olla perusteltua käyttää tiskijukka-termiä?

**Comment by jtuohini** [comment]
Luumu-ryhmässä on varmasti toista mieltä olevia henkilöitä, mutta oma mielipiteeni on, että termit **disc jockeyt** ja **DJ:t** voisi yhdistää ja että auktorisoiduksi muodoksi paras olisi suomenkielisessä Wikipediassakin oleva eli jälkimmäinen (vrt. https://fi.wikipedia.org/wiki/DJ). Ero pelkkiä levyjä (ja suutaan) soittavan "disc jockeyn" ja levyjä soittaessaan samalla uutta luovan "DJ:n" välillä on vaikea hahmottaa, ja jos kyse on korostetusti uutta luovasta toimijasta, niin astutaan jo termin **säveltäjät** kattamalle alueelle.

**Comment by asormune** [comment]
Kannatan yhtä termiä, DJ:t

**Comment by mirmaid** [comment]
MUSAssa nyt DJ:t KT disc jockeyt, discjockeyt, tiskijukat. Tehdään sama muutos YSAssa.

**Comment by OutiHintikka** [comment]
Referenssitermiksi tiskijukat
