### ISSUE TITLE
bichon havanais

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5282]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[bichon havanais](http://www.yso.fi/onto/ysa/Y111784) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi havannankoira 

#### Perustelut ehdotukselle   

Nimitystä käytetään paljon, ks. esim https://fi.wikipedia.org/wiki/Havannankoira
Havannalaiset ry: Havannankoirien valiokirja 2007-2015 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by jtuohini** [comment]
Olisiko kuitenkin parempi muuttaa nykyinen **bichon havanais** ohjaustermiksi ja ottaa varsinaiseksi termiksi tuo suomenkielinen **havannankoira**? Vaikka Kennelliitto suosisikin "fiinimpää" vieraskielistä muotoa, niin näyttää googlailu tuottavan huomattavan suuren hakutulosjoukon suomenkielisellä nimityksellä. (Koirien suhteen maallikkona kommentoin.)

**Comment by asormune** [comment]
Kennelliiton käyttämä virallinen nimi = Havannankoira (Bichon havanais) http://www.kennelliitto.fi/sites/default/files/attachments/rotumaaritelmat/fci_9/9havan.pdf
