### ISSUE TITLE
päivänsanat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5283]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

päivänsanat 

#### Assosiatiiviset (RT)   

[päivänavaukset](http://www.yso.fi/onto/yso/p7469) 

#### Tarkoitusta täsmentävä selite   

Jokaiselle päivälle yl. Raamatusta otettu pieni tekstipätkä, johon selitys. Eivät ole päivänavauksia. 

#### Perustelut ehdotukselle   

24.1	Hartaus
24.11	Rukous. Hartaudenharjoitus
YKL-kaavassa 24.12  Päivänsanat. Kristilliset päivänavaukset 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

YTIMESSÄ #365 sytykettä elämään 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [päivänsanat](http://finto.fi/yse/fi/page/Y505283)

**Comment by mirmaid** [comment]
Melindassa 14 viitettä.

**Comment by mariaforsen** [comment]
Sv. ord för dagen ET dagens ord
