### ISSUE TITLE
itämerennorppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5284]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

itämerennorppa 

#### Ehdotettu termi ruotsiksi   

baltisk vikare 

#### Ehdotettu termi englanniksi   

Baltic ringed seal 

#### Ehdotettu yläkäsite YSOssa (LT)   

[norppa](http://www.yso.fi/onto/yso/p9961) 

#### Vaihtoehtoiset termit ja ilmaisut   

Pusa hispida botnica 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The Baltic Ringed Seal : an arctic seal in European waters / Antti Halkka and Petteri Tolvanen (eds.) 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [itämerennorppa](http://finto.fi/yse/fi/page/Y505284)

**Comment by mirmaid** [comment]
AFOssa. YSAssa on _norppa, saimaannorppa_ ja _laatokannorppa_.

**Comment by mariaforsen** [comment]
Sv. östersjövikare ET baltisk vikare
