### ISSUE TITLE
merkkikielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5285]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[merkkikielet](http://www.yso.fi/onto/ysa/Y97366) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ruotsiksi sama kuin viittomakieli, joten ehdotetaan muuttamista muotoon merkkijärjestelmät. Mahdollisesti osa käytöstä voitaisiin ohjata esim. termeihin "puhetta tukeva ja korvaava kommunikaatio", "bliss-kieli" tms. Tarvitaanko termi "tukiviittomat"? 

#### Perustelut ehdotukselle   

Käyttö hajanaista, ei vastaavuutta kielten välillä nykyisellään. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/744

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by tpalonen** [comment]
Merkkijärjestelmä ja merkkikieli voidaan molemmat mieltää laajemmin kuin viittaamaan pelkästään luonnollisiin kieliin. Merkkijärjestelmä sopii kuitenkin tällaiseksi laajemmaksi termiksi paremmin, koska "kieli" assosioituu vahvemmin luonnollisiin kieliin. Jos käsite viittaa muuhunkin kuin luonnollisiin kieliin (esim. pukeutumiseen tai liikennemerkkeihin) niin merkkijärjestelmä lienee parempi vaihtoehto. Tieteen termipankkikin puhuu pukeutumisesta ja bussilinjojen numeroinnista merkkijärjestelminä. Bussilinjojen numeroinnista Tieteen termipankki toteaa seuraavaa: "Kyseessä on merkkijärjestelmä, joka rajoittuu pelkkään nimeämiseen. Sen tehtävä on tuottaa merkkejä, jotka viittaavat yksinkertaisesti ja järjestelmällisesti yksittäisiin asioihin, tässä tapauksessa bussireitteihin."
http://tieteentermipankki.fi/wiki/Semiotiikka:toisen_artikulaation_taso

Sivuhuomio: Semiotiikassa erotetaan usein toisistaan kielet ja nonlingvistiset viestintäjärjestelmät. Wikipedia: "As different from linguistics, however, semiotics also studies non-linguistic sign systems."

**Comment by mariaforsen** [comment]
Ruotsiksi teckenspråk, teckensystem, ja näin olisi pitkäaikainen ongelma ratkaistu. Tukiviittomat=stödtecken olisi myös hyvä (käytetty paljon Melindassakin).

**Comment by YSA-kokous** [comment]
merkkijärjestelmät KT merkkikielet (?)
tukiviittomat
