### ISSUE TITLE
transgressio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5286]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[transgressio](http://www.yso.fi/onto/ysa/Y134702) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava esim. transgressio (geologia) KÄ rannansiirtyminen, transgressio (sulkutarkenne x). 

#### Perustelut ehdotukselle   

Eri merkitykset. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa ryhmä 00, YSOssa 11. Transgressio (geologia) olisi mahdollinen, mutta käsittääkseni tarkoittaa ainakin lähes samaa kuin rannansiirtyminen, joka on jo YSAssa. https://en.wikipedia.org/wiki/Marine_transgression

Enemmän käytetty kirjallisuudentutkimuksen terminä, Kirjasampo: _Kirjallisuuden tutkimuksen ilmaus, jolla tarkoitetaan rajojen rikkomista._ Joitakin kertoja samassa merkityksessä myös muun taiteen/kulttuurintutkimuksen/opetuksen alalla. Wikisanakirja: normin rikkominen, eettisten tai moraalisten rajojen ylittäminen

https://www.vocabulary.com/dictionary/transgression

1. the act of transgressing; the violation of a law or a duty or moral principle
2. the spreading of the sea over land as evidenced by the deposition of marine strata over terrestrial strata

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/843

**Comment by mirmaid** [comment]
Jos otetaan transgressio (geologia), pitää varmaankin ottaa myös regressio (geologia) (myös rannansiirtyminen olisi mahdollinen sulkutarkenne?).

**Comment by mariaforsen** [comment]
Eli jos otetaan transgressio (geologia) niin tämä ja regressio ovat oikeastaan alakäsitteitä termille rannansiirtyminen? 
"Beroende på strandförskjutningens riktning används två begrepp: 
Regression, havet upplevs dra sig tillbaka (landet "höjs").
Transgression, havet upplevs stiga, översvämmar tidigare torrlagda stränder."

**Comment by mirmaid** [comment]
^ Juu, rannansiirtyminen olisi siis myös mahdollinen sulkutarkenne. Omasta puolestani riittäisi kyllä myös pelkkä _rannansiirtyminen_-termi. 

LCSH: Transgression (Ethics)

Voisi tietysti rajata pois geologiaa vaihtamalla termiksi _transgressiivisuus_? Muita mahdollisia (ei kovin hyviä): _transgressio (taide), transgressio (normit)_.

**Comment by YSA-kokous** [comment]
transgressiivisuus
rannansiirtyminen riittää
