### ISSUE TITLE
huoltolaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5287]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huoltolaitokset](http://www.yso.fi/onto/ysa/Y107213) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin hoitolaitokset. 

#### Perustelut ehdotukselle   

Ruotsiksi vastineet vårdinrättningar, vårdanstalter, eli ovat synonymisia. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Lääketiede 2.0: hoitolaitos: sairaala tai muu hoitoa antava laitos

Melindan perusteella voisi minusta tehdä huoltolaitokset KÄ hoitolaitokset - hoitolaitoksella viitataan kyllä usein mukavampiin paikkoihin (esim. fysikaaliset hoitolaitokset, kylpylät) kuin ne joita on listattu huoltolaitokset-termin alakäsitteiksi. Lähinnä kuitenkin ongelmallisia ovat ehkä ne tapaukset joissa kyse on "pakkolaitoksista", esim. _Goffman: Minuuden riistäjät: tutkielma totaalisista laitoksista, Bessant etc. Violations of trust: how social and welfare institutions fail children and young people_ tai _Frangeur: Pojkar, pli och pedagogik: vanart och manligheter på Bonaanstalten 1905-1948._

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/806

**Comment by mariaforsen** [comment]
Pakkolaitoksista (enää lähinnä vankilat yms., siinä mielessä että muissa pitäisi nykyään saada oikeaa hoitoa) voisi mielestäni käyttää niiden oikeat termit, eli vankilat jne. Vaikka toki nykyään ajatellaan että vankila olisi jossain määrin myös "hoitava". Huoltolaitokset-termi oli kuitenkin hyvin vaihtelevasti käytetty, joten nykyinen tilanne miten vain ongelmallinen.

**Comment by YSA-kokous** [comment]
KÄ hoitolaitokset
