### ISSUE TITLE
laitoshuolto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5288]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[laitoshuolto](http://www.yso.fi/onto/ysa/Y96713) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Rajataan merkitykset siten, että laitoshoito viittaa kaikkien mahdollisten hoitoa tarvitsevien hoitoon ja laitoshuolto laitoksen kunnossapitoon, siivoamiseen tms. Muutetaan laitoshuollon preflabeliksi "laitoshuolto (kunnossapito) ja lisätään huomautus: "Laitoksissa tehtävä siivous- ja kunnossapitotyö." 

#### Perustelut ehdotukselle   

MOT:
1. vars. pitkäaikainen huolenpito jksta sosiaali- tms. laitoksessa.
2. laitoksissa tehtävä siivous- ja kunnossapitotyö.

Ks. Melinda ja termin suhteet. YSOon lisätty huomautus joka ei taida päteä YSAn puolella (esim. RT siivous) eikä Melindassa. Ruotsiksi vastineet ovat synonymisia (eikä ollenkaan ykkösmerkitys). 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Lääketiede 2.0: laitoshoito: ympärivuorokautinen jatkuva hoito sairaalassa tai muussa hoitolaitoksessa; vrt. avohoito

Kaikkien ihmisen huoltoa tarkoittavien korvaaminen laitoshoito-termillä voi olla hankalampaa kuin vastaava huoltolaitokset/hoitolaitokset -yhdistäminen? Esim. _Autero: Laitosnuoren tarina_ - voiko puhua laitoshoidosta huostaanotettujen nuorten kohdalla? Suomeksi hoito sopii kun kyse on potilaista tai vanhuksista, mutta terveiden nuorten kohdalla se tuntuu vähän ongelmalliselta.

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/807

**Comment by mariaforsen** [comment]
Kielitoimiston sanakirja: laitoshoito: hoito sairaala-, sosiaali- tms. laitoksessa. Eli ainakaan siinä ei tehdä eroa hoidettavien iän, hoidon tyypin tms. perusteella. Myös googlessa näyttää laitoshoito olevan hyvin runsaasti käytetty nuorten huostaanotettujen yms. kohdalla. Ks. laitoshoito + nuoret / lastensuojelu, esim. https://www.thl.fi/fi/web/lastensuojelun-kasikirja/tyoprosessi/sijaishuolto/sijaishuollon-muodot/lastensuojelulaitokset

Tarvitaan nyt myös JUHO-työssä.

**Comment by YSA-kokous** [comment]
KÄ laitoshoito
