### ISSUE TITLE
laillisuusharkinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5290]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[laillisuusharkinta](http://www.yso.fi/onto/ysa/Y102960) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

OIKO-ontologian asiantuntijatyöryhmän mukaan ensisijaisena terminä pitäisi käyttää oikeusharkintaa ja laillisuusharkinta olisi sallittu synonyymi. 

#### Ehdottaja   

Anu Ylisalmi 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

anu.ylisalmi@tsk.fi 

#### Ehdotettu muutos   

Käytettäväksi termiksi ’oikeusharkinta’ ja ohjaustermiksi ’laillisuusharkinta’

**Comment by mirmaid** [comment]
EKS: laillisuusharkinta, Googlella viitteitä saman verran. EIF: laillisuusharkinta ks. oikeusharkinta.

**Comment by YSA-kokous** [comment]
oikeusharkinta
