### ISSUE TITLE
kansainväliset sopimukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5291]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansainväliset sopimukset](http://www.yso.fi/onto/ysa/Y95827) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi ’sopimukset’ 

#### Perustelut ehdotukselle   

Oikeushallinnon ontologian (OIKO) asiantuntijatyöryhmän mukaan kansainväliset sopimukset eivät ole valtiosopimuksia, sillä kansainvälisiä sopimuksia tehdään myös (kansainvälisten) järjestöjen välillä. 

#### Ehdottaja   

Anu Ylisalmi 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

anu.ylisalmi@tsk.fi

**Comment by mirmaid** [comment]
Huomautus nyt: _Tarkoittaa valtioiden tai kansainvälisten järjestöjen välistä sopimusta. Monenvälisistä valtiosopimuksista käytä kansainväliset sopimukset_

Mihinköhän ohjeistus perustuu? Ei ole ainakaan noudatettu. EKS:ssa kansainväliset sopimukset on ohjaustermi. 

Wikipedia: **treaty:** A treaty is an agreement under international law entered into by actors in international law, namely sovereign states and international organizations. A treaty may also be known as an (international) agreement, protocol, covenant, convention, pact, or exchange of letters, among other terms. Regardless of terminology, all of these forms of agreements are, under international law, equally considered treaties and the rules are the same.

https://www.eduskunta.fi/FI/tietoaeduskunnasta/kirjasto/aineistot/kv-jarjestot/kansainvalisen-oikeuden-tietopaketti/Sivut/Valtiosopimukset.aspx

http://tieteentermipankki.fi/wiki/Oikeustiede:kansainv%C3%A4linen_velvoite

**Comment by YSA-kokous** [comment]
KÄ valtiosopimukset?

**Comment by satuniininen** [comment]
Kielitoimisto: 
**valtiosopimus** valtioiden t. kansainvälisten järjestöjen välinen sopimus. 

En tiedä onko pelkkää omaa tulkintaa, mutta _valtiosopimukset_ tuntuu sopivan huonosti silloin kun kyseessä on kansainvälisten järjestöjen välinen sopimus, vaikka sen määritelmällisesti pitäisi sopia niihinkin. Termitasolla _valtiosopimukset_ tuo mieleen ihmisoikeus- ja ilmastosopimukset sekä muut suuret ns. valtiolliset aiheet. Hankalammalta se tuntuu silloin, kun aineisto käsittelee esim. kansainvälistä tavaramerkkioikeutta, ks. https://melinda.kansalliskirjasto.fi/byid/015306189 (vai tulisiko _valtiosopimukset_ tähän asiasanaksi laisinkaan?)

Sikäli tuntuisi sallivammalta valita muoto _valtiosopimukset_ KÄ _kansainväliset sopimukset_. 
Joka tapauksessa nykyinen jako määritelmineen ei ole kestävällä pohjalla ja kaipaa muutoksia.

**Comment by mariaforsen** [comment]
Mieluummin kansainväliset sopimukset, ettei ole ongelmia käyttää vaikkei aina olisikaan valtioiden tekemistä sopimuksista kyse.

**Comment by YSO-kokous** [comment]
Säilytetään molemmat käsitteet sanastossa seuraavin muutoksin:

valtiosopimukset LT kansainväliset sopimukset
kansainväliset sopimukset (valtiosopimukset) KÄ valtiosopimukset 
Muutetaan valtiosopimusten määritelmä sopivaksi.
