### ISSUE TITLE
perunkirjoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5296]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[perunkirjoitus](http://www.yso.fi/onto/ysa/Y103918) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi ’oikeudelliset tapahtumat’ 

#### Perustelut ehdotukselle   

Oikeushallinnon ontologian (OIKO) asiantuntijatyöryhmän mukaan perunkirjoitus ei ole asiakirja vaan tapahtuma, jossa laaditaan perukirja (asiakirja). 

#### Ehdottaja   

Anu Ylisalmi 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

anu.ylisalmi@tsk.fi

**Comment by mirmaid** [comment]
Kuulostaa hyvältä, Kielitoimiston sanakirja myös: _oik. perukirjan laadinta(tilaisuus)._ Lisäksi sanastossa on myös _perukirjat_. Voisi olla myös _kohdistuva toiminta_, vrt. _perinnönjako_.
