### ISSUE TITLE
simulaatioharjoittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5303]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

simulaatioharjoittelu 

#### Ehdotettu termi englanniksi   

simulation training 

#### Ehdotettu termi ruotsiksi   

simulering praktik 

#### exactMatch   

FinMeSH : simulaatioharjoittelu 
LCSH : Simulation Training 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Vaihtoehtoiset termit ja ilmaisut   

simulaatio-oppiminen 

#### Perustelut ehdotukselle   

Simulointi on käytössä hoitotyön opetuksessa. AMK-opinnäytetöitä on tehty useita aiheeseen liittyen ja olisi hyvä täsmentää olemassa olevaa YSA:n simulointi -käsitettä. Liittyy keskeisesti opetustyöhön ja oppimiseen käytännön tasolla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi:amk-201705229532 

**Ehdottajan nimi:** Kukka-Maritta Taskinen 
**Ehdottajan organisaatio:** Savonia-ammattikorkeakoulu 
**Ehdottajan sähköpostiosoite:** kukka-maritta.taskinen@savonia.fi **Termiehdotus Fintossa:** [simulaatioharjoittelu](http://finto.fi/yse/fi/page/Y505303)

**Comment by jtuohini** [comment]
Pieni korjaus esityksen exactMatch-kohtaan: **Simulation Training** on MeSH-, ei LCSH-termi. Lähin LCSH-vastine näyttäisi olevan ketju **Medicine--Study and teaching--Simulation methods** [http://id.loc.gov/authorities/subjects/sh85083106] ynnä **Medicine**n suppeammat termit vastaavin tai tarkemmin jatkein.

**Comment by mirmaid** [comment]
On FinMeSHissä, myös kaksi alakäsitettä. 

https://www.turkuamk.fi/fi/tyoelamapalvelut/koulutushaku/simulaatiot-tyoyhteisoille/

Ei Melindassa, 6 viitettä _potilassimulaatio_.
_simulointi + harjoittelu_ 12 kertaa
_simulointi + koulutus_ 88 kertaa
_simulointi + opetus_ 138 kertaa

**Comment by mariaforsen** [comment]
Sv. simuleringsträning ET simulationsträning ET simulationsövning  ET simuleringsövning
