### ISSUE TITLE
teledemokratia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5305]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teledemokratia](http://www.yso.fi/onto/ysa/Y109847) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

päätermiksi sähköinen demokratia tai elektroninen demokratia 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Elektroninen_demokratia

Demokratiasanasto:
"Joskus käytetään myös termiä teledemokratia, jolla viitataan useimmiten 1990-luvun puolivälissä ja sitä ennen tapahtuneisiin kokeiluihin, joissa käytettiin hyväksi tietotekniikkaa ja puhelinteknologiaa."

http://www.termipankki.fi/ext/demokratiasanasto/netmot.exe?UI=figr&height=186&qfind=s%C3%A4hk%C3%B6inen%20demokratia 

#### Ehdottaja   

Ilona Lindfors 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

ilona.lindfors@helsinki.fi

**Comment by ilona-x** [comment]
termiehdotuksissa myös: elektroninen demokratia:
https://github.com/Finto-ehdotus/YSE/issues/2825

**Comment by mirmaid** [comment]
Google: e-demokratia n. 1600 (Melinda 1), elektroninen n. 350 (Melinda 1), sähköinen n. 600, digitaalinen n. 550.

**Comment by mariaforsen** [comment]
Ruotsiksi jo e-demokrati vastineena.

**Comment by YSA-kokous** [comment]
e-demokratia
