### ISSUE TITLE
häviäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5306]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[häviäminen](http://www.yso.fi/onto/ysa/Y112726) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

YSOssa häviäminen (häviön kärsiminen) ja käännetty sen mukaan (nederlag/förlorande). 
Allärs:in puolella  häviäminen + katoaminen = försvinnande 
Ks. https://github.com/NatLibFi/Finto-data/issues/223 

KS: hävitä: 
1. kadota, häipyä, haihtua, kaikota
2. kärsiä häviö, tappio, joutua häviölle, tappiolle; menettää

KS: kadota:
1. huveta t. mennä olemattomiin, hävitä.
2. häipyä t. hävitä näkyvistä, lakata näkymästä; joutua, hävitä tietymättömiin, hukkua

#### Ehdotettu muutos   

häviäminen (häviön kärsiminen) 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Tähän liittyy myös termi _tappiot_, joka on ryhmässä 75 (talous), mutta käytetty myös kärsitystä häviöstä.

**Comment by mariaforsen** [comment]
Förluster = tappiot voidaan myös käyttää kärsityistä häviöistä.

**Comment by mirmaid** [comment]
Voisiko tämä ratketa jotenkin niin, että olisi:

tappiot (talous)
tappio (häviäminen) TAI tappiot (häviöt) TAI häviäminen (tappio)

häviäminen (katoaminen) KÄ katoaminen

**Comment by EsaMPKK** [comment]
Voisi. Suosikkini noista kolmesta häviämisestä on häviäminen (tappio).

**Comment by YSA-kokous** [comment]
häviäminen (katoaminen) KÄ katoaminen
häviäminen (tappio)

tappiot (talous) (mahd. myös taloudelliset tappiot, kuten voitot) VAI tappiot (menetykset) - tutkitaan vielä, vrt. myös voitot

**Comment by YSA-kokous** [comment]
tappiot (talous), voitot (talous)
tutkitaan vielä menetys & mitä jää kuvailematta tappiot (talous) ja häviäminen (tappio) -termeillä

**Comment by ilona-x** [comment]
häviäminen korjattu Melindaan

**Comment by ilona-x** [comment]
myös tappiot korjattu Melindaan, jäljelle jäi esim. maatalouteen liittyviä tappioita, myös kalastuksessa hylkeiden aiheuttamat tappiot, mehiläistenhoidossa mehiläisten "talvitappiot"

AFOsta löytyy puintitappiot, satotappiot, varastointitappiot, varisemistappiot

**Comment by mirmaid** [comment]
^ Näistä lähinnä sadonkorjuutappiot tuntuisi kaipaavan termiä, muissa luultavasti korvattavissa muilla termeillä, esim. _kuolleisuus, hävikki_. _Puintitappiot_ ei sovi ihan kaikkiin tapauksiin.

**Comment by YSA-kokous** [comment]
Korvataan muilla termeillä (kuolleisuus, hävikki, tarvittaessa tappiot 653-kenttään tai muutetaan sopivaksi AFO-termiksi)
