### ISSUE TITLE
muuntelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5307]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muuntelu](http://www.yso.fi/onto/ysa/Y97578) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne, mahdollisesti jaetaan. 

#### Perustelut ehdotukselle   

Ruots. variation. Molemmat käytetty aika paljon muuhunkin kuin biologiseen, esim. kieleen tai musiikkiin liittyviin viitteisiin.. Ks. Melinda. Ontologian puolella lisätty tarkenne. Pitääkö jakaa tms. ? Sanastossa myös muunnelmat/variationer. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
KULAssa (ja KULOssa) on termi muuntelu - KT variaatio, RT toisinnot. Termi toisinnot on nykyisin myös YSAssa.

Termiä muuntelu on käytetty sisällönkuvailussa paljon KULAn tarkoittamassa merikityksessä. Folkloristiikassa sitä käytetetään, kun tutkitaan suullisen perinteen (esimerkiksi tietyn kansansadun) ajallista, alueellista, sosiaalista tms. vaihtelua.

KULOssa muuntelun yläkäsitteenä on kulttuuriset ilmiöt, käsitteen toisinnot yläkäsite on kulttuuriset tuotokset. Molemmille käsitteille (muuntelu ja toisinnot) on tarvetta sisällönkuvailussa.

Finto-ehdotus/YSE#5249

**Comment by mirmaid** [comment]
Voidaan varmaan lisätä tarkenne muuntelu (biologia) rajaamaan merkitystä. Toisaalta YSAssa on myös geneettinen muuntelu, onko olemassa muuta biologista muuntelua? (Ehkä: http://www02.oph.fi/etalukio/biologia/kurssi1/evoluutio.html)

Kun sanastossa on jo muunnelmat ja toisinnot, yleistermi vaihtelu, sekä vastikään lisätty variaatio (kielitiede), tarvitaanko vielä muuntelu-termiä muussa kuin biologian yhteydessä?

Eikö esim. _kansansadut - muuntelu_ voisi korvata yhdistelmällä _kansansadut - muunnelmat_?

**Comment by mirmaid** [comment]
Muuntelu (folkloristiikka) KÄ muunnelmat, toisinnot TAI muuntelu (folkloristiikka) omana käsitteenään?

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/787

**Comment by mariaforsen** [comment]
Pyrkimys on ollut välttää yksikkö/monikko-tuplia, kannatan sitä edelleen. Ainakin ruotsin osalta käy yhtä hyvin käyttää variationer kuin variation.

**Comment by mirmaid** [comment]
Näyttää siltä että usein termiä _muuntelu_ on käytetty termin _geneettinen muuntelu_ sijasta, esim. yhdistelmiä _geenit + muuntelu_ tai _evoluutio + muuntelu_. Varmasti on aineistoa myös ympäristötekijöiden aiheuttamasta muuntelusta, eikä korjaaminen pelkkien viitetietojen perusteella ole välttämättä mahdollista. Toisaalta olisi hyvä että geneettistä muuntelua käsittelevä aineisto kuvailtaisiin aina samalla termillä, onnistuuko tämä jos otetaan lisäksi _muuntelu (biologia)_?

Tässä tapauksessa olisi ehkä selkeintä ratkaista ja korjata ensin biologian osalta ja sitten tutkia jäljellejäävät viitteet.

**Comment by krinay** [comment]
Muuntelu (folkloristiikka) KÄ muunnelmat ei oikein toimi. Muunnelmista käytetään folklostiikassa termiä toisinnot. Muuntelulla tarkoitetaan sitä prosessia, jossa suullinen perinne muuttuu ja jonka aikana syntyy esimerkiksi tietystä kansansadusta tai -runosta erilaisia toisintoja. Folkloristinen muuntelu on varmaan lähempänä tuota kielitieteen variaatiota, kielellistä variaatiota.

**Comment by PaiviLipsanen** [comment]
Biologian sanakirjan (2006) mukaan "biologinen muuntelu" voidaan jakaa kolmeen luokkaan: "fenotyyppinen muuntelu" on eliön tietyn omainaisuuden koko havaittavissa oleva muuntelu. Se voi olla laadullista tai määrällistä. Määrällinen fenotyyppinen muuntelu voidaan ositella ympäristön aiheuttamaan ja geneettiseen muunteluun. Geneettinen muuntelu on puhtaasti perinnöllistä ja johtuu geeneistä ja niiden vuorovaikutuksesta. 
Tämän perusteella 
muuntelu (biologia)
alakäsite: geneettinen muuntelu

**Comment by tpalonen** [comment]
Jos muuntelu (folkloristiikka) KÄ muunnelmat on huono, olisiko muuntelu (folkloristiikka/perinne/kulttuuri) KÄ toisinnot parempi?

**Comment by mirmaid** [comment]
Sanastossa on siis myös termi _toisinnot_ (ryhmät 50, 87).

**Comment by krinay** [comment]
Folkloristiikan näkökulmasta pärjätään termeillä _variaatio (kielitiede)_ ja _toisinnot_. Folkloristit tutkivat sekä kielellistä muuntelua (prosessina) että sen tuloksena syntyviä tuotoksia eli toisintoja. Usein molempia, joskus vain jompaa kumpaa. Kielitiede on tietenkin tässä mielessä hankala tarkenne, mutta kai termillä _variaatio (kielitiede)_  tarkoitetaan kielellistä variaatiota.

**Comment by mirmaid** [comment]
Lopputulos:

- muuntelu (biologia) 

- muuntelu (tarkenne x) KÄ toisinnot, variaatio (kielitiede - tarkenne voi muuttua)
