### ISSUE TITLE
vastineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5308]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vastineet](http://www.yso.fi/onto/ysa/Y104822) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko jako/määrittely tarpeen? 

#### Perustelut ehdotukselle   

Monimerkityksinen termi ja ryhmä 00, sekä käytettykin Melindassa eri merkityksissä. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Sanavastineista osalle voisi käydä käännösvastineet. Toisaalta osassa aineistoa kyse on muusta sanaston tutkimuksesta, ei kääntämisestä.

Ehdotus: vastineet (kielitiede) omana terminään TAI KÄ vastaavuus TAI KÄ käännösvastineet (otettaisiin uutena) + vastaavuus

vastineet (oikeus/prosessioikeus)

vastineet (viestintä/media/?) http://www.jsn.fi/periaatelausumat/vastine/

**Comment by mirmaid** [comment]
Ks. tarkemmin https://github.com/NatLibFi/Finto-data/issues/819

**Comment by mariaforsen** [comment]
Tarvitaan myös JUHO-työssä

**Comment by YSA-kokous** [comment]
vastineet (viestintä)
vastineet (oikeus/prosessioikeus/?) - kysytään Tommilta
vastineet (kielitiede) KT käännösvastineet

**Comment by mariaforsen** [comment]
Sv. 
-genmäle ET bemötande (svar) 
-svaromål 
-ekvivalenter (språk) ET motsvarigheter (språk), termekvivalenter, översättningsekvivalenter, översättningsmotsvarigheter

**Comment by vthuhtala** [comment]
Määritelmät...

**Comment by mirmaid** [comment]
**vastineet (oikeus/prosessioikeus/?)** - tässä sulkutarkenne _(oikeus)_ voi olla liian epätarkka (mahdollisuus sekoittua vastineoikeuteen). Mahdollisia tarkenteita _oikeudenkäynti_ (EIF: Luvun nimi on "vastine oikeudenkäynnissä", vaikka vastine voidaan antaa myös jo esivalmistelussa; Kielitoimiston sanakirja: vastaajan oikeudenkäynnissä antama selvitys, joka sisältää hänen vaatimuksensa.) tai _prosessioikeus_?

**Comment by mirmaid** [comment]
_vastineet (prosessioikeus)_ -muoto varmistettu Tommilta
