### ISSUE TITLE
substraatti (biologia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5309]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

substraatti (biologia) 

#### Ehdotettu termi englanniksi   

substrate (biology) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[alustat](http://www.yso.fi/onto/yso/p15091) 

#### Assosiatiiviset (RT)   

[soluviljely](http://www.yso.fi/onto/yso/p9302) 

#### Vaihtoehtoiset termit ja ilmaisut   

substraatit (biologia) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

Biologiassa bakteerin tai soluviljelmän elatusalusta. 

#### Perustelut ehdotukselle   

YSOssa on jo tällainen käsite muodossa "substraatti (alustat)". Substraattia-termiä on käytetty kuvailussa kirjavasti ja tämä on yksi merkityksistä.

YSO-käsite:
http://finto.fi/yso/fi/page/p23036 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Production of oleaginous microbial biomass by reusing wastewaters / Jatta Marjakangas. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [substraatti (biologia)](http://finto.fi/yse/fi/page/Y505309)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4851

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
_Substrat är inom biologin det underlag som en växt eller ett djur lever på. Olika substrat kan vara uppbyggda av både biotiska och abiotiska beståndsdelar. Till exempel kan algtäcken på klippor (som då är algernas substrat) själva utgöra ett substrat för andra organismer, som alltså i sin tur lever ovanpå algerna._

_Vid bakterieodling i petriskålar i laboratorier är substratet ofta en agarplatta med det näringsämne som bakterierna växer i._

http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:substraatti

Jonkin verran käytetään myös kasvualusta-sanaa, joka YSAssa ja yleensä muutenkin suomeksi viljely- tai kasvatusalustaan.

**Comment by YSA-kokous** [comment]
substraatit (alustat) KÄ kasvualustat

**Comment by YSO-kokous** [comment]
Poistetaan substraatit (alustat), uudelleenohjaus ja altLabel käsitteeseen kasvualustat.
