### ISSUE TITLE
loma-asunnot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5310]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[loma-asunnot](http://www.yso.fi/onto/ysa/Y96968) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan KT-muodoksi asiasanalle "vapaa-ajan asunnot" 

#### Perustelut ehdotukselle   

Asiasanan nykyinen selitys ("Vapaa-ajan asunnoista vuoteen 2009 käytetty nimitys") antaa ymmärtää, että "loma-asunnot" ja "vapaa-ajan asunnot" tarkoittavat täsmälleen samaa asiaa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Yhdistetty YSOssa. _Loma-asunnot_-termi ei ole jäänyt pois käytöstä, vaikka viime vuosina uudempi muoto onkin ollut käytetympi.

**Comment by mariaforsen** [comment]
Sv. fritidshus ET fritidsbostäder, semesterbostäder
