### ISSUE TITLE
kesämökit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5311]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kesämökit](http://www.yso.fi/onto/ysa/Y110495) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan suhde "kesämökit RT vapaa-ajan asunnot" muotoon "kesämökit LT vapaa-ajan asunnot" 

#### Perustelut ehdotukselle   

Kaikki kesämökit ovat vapaa-ajan asuntoja (vaikka olisivatkin talviasuttavia), joten termien välisen suhteen pitäisi heijastella tätä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ok
