### ISSUE TITLE
kesämökit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5312]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kesämökit](http://www.yso.fi/onto/ysa/Y110495) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan suhde "kesämökit RT asuinrakennukset" muotoon "kesämökit LT asuinrakannukset" 

#### Perustelut ehdotukselle   

Kaikki kesämökit ovat lähtökohtaisesti asuinrakennuksia, joten termien suhteen pitäisi vastata tätä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ok
