### ISSUE TITLE
vakavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5314]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vakavuus](http://www.yso.fi/onto/ysa/Y101411) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteisiin vakaus ja/tai stabiilius 

#### Perustelut ehdotukselle   

Termejä käytetään hankalasti ristiin, vaikka merkityskentissä onkin vähän eroa: toisaalta fysiikka (esim. kulkuneuvon vakaus) tai abstraktimmin tilanteen pysyminen muuttumattomana (voi liittyä politiikkaan ja talouteen mutta myös esim. kemialliseen koostumukseen). Lääketieteessä potilaan tila voi olla stabiili, mutta sama termi voi liittyä liikkumiseen tai kivun kokemiseen. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Yhdistetään kaikki: vakavuus, vakaus KÄ _stabiilius_ (TAI vakavuus, stabiilius KÄ _vakaus_)
TAI
Jaetaan, esim. _vakaus (fysiikka)_ ja _stabiilius (muuttumattomuus)_

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/639

**Comment by jtuohini** [comment]
Lisäksi termille **vakavuus** olisi merkitys komediallisuuden/koomisuuden yms vastakohtana, mutta kyseistä näkökulmaa ei ole huomioitu sanastossa tällä hetkellä ainakaan sanaryhmien osalta. Yhdistäminen tekisi entistä vaikeammaksi ottaa tätä myöhemminkään huomioon.

**Comment by mirmaid** [comment]
Huom. myös _vakauttaminen/stabilointi_. YSOssa huomautus: _Stabilointi-termiä käytetään kemian alalla._ Ryhmä kuitenkin 00.

**Comment by mariaforsen** [comment]
Ruotsin osalta on yhdistäminen tai ainakin selkeä jako välttämätöntä. 
Nyt Allärs: 
vakaus + vakavuus + stabiilius = stabilitet
vakauttaminen = stabilisering (ekonomi och samhälle)
stabilointi = stabilisering (kemi)

**Comment by satuniininen** [comment]
Kannatan jakoa vakaus (fysiikka) ja stabiilius (muuttumattomuus)

Ja lisäksi tietysti myös vakauttaminen ja stabilointi

**Comment by mirmaid** [comment]
_Stabilointi_ tarvitsisi varmaankin suomeksikin tarkenteen. Termiä on käytetty Melindassa useimmiten rakennustekniikan yhteydessä - kai tämä on edelleen kemiaa http://www.finnsementti.fi/Tietoa-stabiloinnista-massastabilointi?

**Comment by YSA-kokous** [comment]
vakaus (fysiikka) ja stabiilius (muuttumattomuus), stabilointi (kemia), ryhmä 09

**Comment by mirmaid** [comment]
- https://fi.wikipedia.org/wiki/Mittauslaitteiden_varmentaminen, pitääkö tämä erottaa uudesta vakaus (fysiikka) -käsitteestä? (oli RT mittauslaitteet)

- vakaus (fysiikka), jätetäänkö ohjaustermi stabiilius (fysiikka) [oli stabiilius (vakaus)]?

- vakavuus KÄ vakaus (fysiikka), tarvitaanko myös KÄ stabiilius (muuttumattomuus)?

- tarvitseeko _vakauttaminen_ tarkenteen?

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Mittauslaitteiden_varmentaminen pitää ainakin ruotsin osalta erottaa. JUHOssa ratkaistiin lisäämällä: vakaus (vaakojen valvonta) http://finto.fi/juho/fi/page/p2221  Tosin Allärs: justering=säätely

Vakauttaminen="stabilisering (ekonomi och samhälle)" Allärsissa.

**Comment by satuniininen** [comment]
Nämä ovat termitasolla niin likeisiä ja helposti sekoitttuvia, että kannatan runsasta ohjaustermien ja sulkutarkenteiden käyttöä. Eli lisätään ehdotetut:
stabiilius (fysiikka) KÄ vakaus (fysiikka)  JA
vakavuus KÄ stabiilius (muuttumattomuus)

Vakauttamisella on myös englanniksi sulkutarkenne (economy and society), joten varminta lienee lisätä suomeksikin _vakauttaminen (talous ja yhteiskunta)_.

**Comment by mirmaid** [comment]
Lisäksi _vakaus (mittaus)_ tai _varmentaminen (mittaus)_ tai _mittauslaitteiden varmentaminen_

Tässä laissa tarkoitetaan...6) _varmentamisella mittauslaitteen tai -menetelmän vaatimustenmukaisuuden arvioimista ja toteamista todistettavalla tavalla_; https://www.finlex.fi/fi/laki/alkup/2011/20110707

**Comment by YSA-kokous** [comment]
vakauttaminen (talous ja yhteiskunta)
stabiilius (fysiikka) KÄ vakaus (fysiikka)
vakavuus KÄ stabiilius (muuttumattomuus)

varmentaminen (mittaus) (?)

**Comment by mirmaid** [comment]
_Mittauslaitteiden varmentaminen_ voisi kuitenkin olla yksiselitteisempi kuin _varmentaminen (mittaus)_.

**Comment by YSA-kokous** [comment]
mittauslaitteiden varmentaminen

**Comment by mariaforsen** [comment]
Sv. verifiering av mätinstrument ET justering av mätningsredskap,  justering av mätinstrument
