### ISSUE TITLE
valkoiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5315]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valkoiset](http://www.yso.fi/onto/ysa/Y118980) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsee sulkutarkenteen. 

#### Perustelut ehdotukselle   

Sanastossa myös valkoiset (kansalaissota). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSOssa tarkenne (etninen rooli). Termin huomautus on myös sikäli huono, että sanastossa on myös termi europidit. Huomautus: _Tarkoittaa valkoisen eli europidisen rodun edustajia_

**Comment by mariaforsen** [comment]
Mihin kaikkeen tämä tarkalleen viittaa? Entä valkoihoiset? Ks. KS. 
SAOssa on "vita" (LCSH: "whites")

**Comment by mirmaid** [comment]
Termiä _europidit_ on käytetty Melindassa vain kerran (ja siinäkin ehkä vähän hassu). 

LCSH: Whites: Here are entered works of a sociological nature that discuss white people as an element in the population, especially in countries where they are a minority. Works of an anthropological nature focusing on the physical features that characterize Caucasians and distinguish them from other races of mankind are entered under |a Caucasian race.

**Comment by mirmaid** [comment]
Valkoihoiset voisi olla päätermi (KT valkoiset (etniset ryhmät)?)? Lisäksi europidit KT kaukasidit (tai toisin päin).

**Comment by krinay** [comment]
Onko termille europidit (tai kaukasidit) ylipäätään tarvetta, jos sitä ei ole käytetty? Eivätkö nuo molemmat liity vanhentuneisiin rotuteorioihin?

**Comment by AuHo22** [comment]
Eikös valkoihoiset jakaudu myös useisiin etnisiin ryhmiin? Mielestäni termi valkoihoiset on riittävän selkeä, YSAssa samoin mustat ja värilliset ilman tarkenteita.
Historiallisissa aineistoissa / historiantutkimuksessa voi tulla tarvetta jo nykyajassa vanhentuneille käsitteillä- äskettäin otettiin sanastoon esim. rotuteoriat juuri em. takia.

**Comment by YSA-kokous** [comment]
valkoihoiset

**Comment by mariaforsen** [comment]
Sv. vithyade ET vita
