### ISSUE TITLE
restauraation aika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5316]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

restauraation aika 

#### Ehdotettu termi englanniksi   

restoration 

#### Ehdotettu termi ruotsiksi   

restauration 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aikakaudet](http://www.yso.fi/onto/yso/p4623) 

#### Tarkoitusta täsmentävä selite   

Restoration In English history, the re-establishment of the monarchy in 1660.  (Oxford Reference World Encyclopedia 
Published online:    2004 Current Online Version:     2014
DOI:     10.1093/acref/9780199546091.001.0001
eISBN:     9780199546091
  

https://koppa.jyu.fi/avoimet/taiku/kirjallisuuden_aikajana/renessanssi/englanti/restauraation-aika 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The facts of life : the creation of sexual knowledge in Britain, 1650-1950 Kirja Porter, Roy, kirjoittaja. ; Hall, Lesley A., kirjoittaja. Yale University Press 1995. 

#### Perustelut ehdotukselle   

Historian aikakausi etenkin Englannin historiassa. 

**Ehdottajan nimi:** Mervi Salomaa-Rauhala 
**Ehdottajan organisaatio:** Tampereen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mervi.salomaa-rauhala@uta.fi **Termiehdotus Fintossa:** [restauraation aika](http://finto.fi/yse/fi/page/Y505316)

**Comment by jtuohini** [comment]
Englannin osalta täsmällinen LCSH-vastine on ketju **Great Britain--History--Restoration, 1660-1688** [http://id.loc.gov/authorities/subjects/sh85056801], ja muiden maiden osalta muodostetaan samaan tapaan. Eli täsmällinen vastine minkä tahansa maan osalta ehdotetulle käsitteelle on **--History--Restoration, [rajavuodet]**.

**Comment by mirmaid** [comment]
Melindassa 2 viitettä.

https://fi.wikipedia.org/wiki/Englannin_restauraatio

**Comment by satuniininen** [comment]
Jos käsite rajautuu Ison-Britannian historiaan, niin voidaan sillata Great Britain--History--Restoration, 1660-1688.

**Comment by mariaforsen** [comment]
Sv. engelska restaurationen ET restaurationen
