### ISSUE TITLE
kriittinen sosiaalipsykologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5317]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kriittinen sosiaalipsykologia 

#### Ehdotettu termi englanniksi   

critical social psychology 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sosiaalipsykologia](http://www.yso.fi/onto/yso/p19035) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

Tarpeellinen ko. aihetta käsittelevän aineiston sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://melinda.kansalliskirjasto.fi/F/GFKA7N3RYETSGCGL8KL2GL6FFBNDMSC8JEAGYU2BIADMKKIT1B-01900?func=full-set-set&set_number=527542&set_entry=000001&format=999 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [kriittinen sosiaalipsykologia](http://finto.fi/yse/fi/page/Y505317)

**Comment by mirmaid** [comment]
Ei Melindassa, Googlellakin vain kourallinen viitteitä. Englanniksi ensimmäisenä viitteenä https://en.wikipedia.org/wiki/Critical_psychology _"One of critical psychology's main criticisms of conventional psychology is that it fails to consider or deliberately ignores the way power differences between social classes and groups can affect the mental and physical well-being of individuals or groups of people."_ YSAssa on _kriittinen psykologia_.

**Comment by YSA-kokous** [comment]
KÄ kriittinen psykologia?

**Comment by mirmaid** [comment]
Ei ole sama kuin kriittinen psykologia:
_Kokeellisen sosiaalipsykologian hallitessa sosiaalipsykologista tutkimusta aina 1960 ja 1970 – luvuille saakka sai kriittinen sosiaalipsykologia alkunsa, kun muun muassa Rom Harré, Henri Tajfel ja Kenneth Gergen halusivat palauttaa sosiaalisen takaisin sosiaalipsykologiaan (emt. 25). Monet ajattelivat, että laboratorion keinotekoinen maailma ei kyennyt jäljittelemään inhimillisen sosiaalisen kokemuksen monitahoisuutta (Burr 2002, 26), jolloin osaltaan näistä lähtökohdista alkoi kriittisen sosiaalipsykologian kehittyminen kokeellisen tutkimuksen vastapainoksi._ http://epublications.uef.fi/pub/urn_nbn_fi_uef-20090027/urn_nbn_fi_uef-20090027.pdf, luku 2.1

**Comment by mariaforsen** [comment]
Sv. kritisk socialpsykologi
