### ISSUE TITLE
dingo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5318]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dingo 

#### Ehdotettu termi englanniksi   

dingo 

#### Ehdotettu yläkäsite YSOssa (LT)   

[koiraeläimet](http://www.yso.fi/onto/yso/p2229) 

#### exactMatch   

LCSH : <dingo, http://id.loc.gov/authorities/subjects/sh85038069.html> 

#### Vaihtoehtoiset termit ja ilmaisut   

australianvillikoira 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kirja: The dingo debate : origins, behaviour and conservation (2015), ISBN 9781486300297 

#### Perustelut ehdotukselle   

Tarvitaan kirjan kuvailussa 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [dingo](http://finto.fi/yse/fi/page/Y505318)

**Comment by mariaforsen** [comment]
Sv. dingo
