### ISSUE TITLE
kirjailijakuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5319]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjailijakuva 

#### Ehdotettu termi englanniksi   

authorial image 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjailijat](http://www.yso.fi/onto/yso/p8970) 

#### Tarkoitusta täsmentävä selite   

synteesiä luova esitys tietyn kirjailijan tuotannon peruspiirteistä ja ominaislaadusta (Hosiaisluoma) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helkassa yli 300 kertaa asiasanana 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kirjailijakuva](http://finto.fi/yse/fi/page/Y505319)

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:kirjailijakuva

**Comment by mirmaid** [comment]
_Henkilökuvat_ on YSAssa ja Kaunokissa monikossa. Molemmat ovat myös genretermejä.

**Comment by mariaforsen** [comment]
Sv. författarporträtt ET författarprofiler

**Comment by mirmaid** [comment]
LT mielikuvat, käsitykset, imago?

**Comment by YSA-kokous** [comment]
Sama paikka kuin julkisuuskuva, ihmiskuva.
