### ISSUE TITLE
restauraatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5320]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

restauraatio 

#### Ehdotettu termi englanniksi   

Restoration 

#### Ehdotettu termi ruotsiksi   

restauration 

#### Ehdotettu yläkäsite YSOssa (LT)   

[valta](http://www.yso.fi/onto/yso/p2551) 

#### exactMatch   

W :Restauraatio (ransk. restauration) tarkoittaa aiemmin vallinneen poliittisen järjestelmän palauttamista tai syrjäytetyn hallitsijasuvun paluuta valtaan. Termi tulee myöhäislatinan verbistä restaurare ’asettaa jälleen’. : https://fi.wikipedia.org/wiki/Restauraatio 

#### Vaihtoehtoiset termit ja ilmaisut   

vallan palautus, hallitsijasuvun valtaanpaluu 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

Liittyy ehdotukseeni    restauraation aika 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

En varsinaisesti minkään tällä kertaa 

**Ehdottajan nimi:** Mervi Salomaa-Rauhala 
**Ehdottajan organisaatio:** Tampereen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mervi.salomaa-rauhala@uta.fi **Termiehdotus Fintossa:** [restauraatio](http://finto.fi/yse/fi/page/Y505320)

**Comment by jtuohini** [comment]
LCSH-vastine **Restorations, Political** [http://id.loc.gov/authorities/subjects/sh85113275]

**Comment by mirmaid** [comment]
Melindassa n. 20 viitettä, 6 näistä muodossa Meiji-restauraatio.

Jos otetaan, monikko? Toisaalta voisi myös auktorisoida kunkin tunnetun restauraation omana terminään?

**Comment by mariaforsen** [comment]
Sv. restauration (politik)

**Comment by YSA-kokous** [comment]
Auktorisoidaan kukin erikseen.

**Comment by mariaforsen** [comment]
Sv. Meijirestaurationen
