### ISSUE TITLE
toimitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5321]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

toimitukset 

#### Ehdotettu termi ruotsiksi   

redaktion 

#### Ehdotettu termi englanniksi   

ei suoraa käännöstä: newsroom 

#### exactMatch   

W : henkilökunta, tilat ja varusteet julkaisun tuottamiseksi      Juuri ennen lehden painoonmenoa toimituksessa vallitsee sähköinen tunnelma. : https://fi.wiktionary.org/wiki/toimitus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 

#### Tarkoitusta täsmentävä selite   

Heikki Kuutti: Mediasanasto. Media Doc Oy 2012 s. 201 

tv-toimitus, lehtitoimitus, radiotoimitus ; toimittajien muodostama organisaatio; paikka, jossa toimittajat tekevät työtään 

#### Perustelut ehdotukselle   

Puuttuu sanastosta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

En juuri nyt minkään 

**Ehdottajan nimi:** Mervi Salomaa-Rauhala 
**Ehdottajan organisaatio:** Tampereen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mervi.salomaa-rauhala@uta.fi **Termiehdotus Fintossa:** [toimitukset](http://finto.fi/yse/fi/page/Y505321)

**Comment by mirmaid** [comment]
Melindassa kolme kertaa merkityksessä tavaran toimitukset.

**Comment by LeKorsu** [comment]
Mediasanaston määritelmä alkaa olla jo vanhentunut, sillä ainakaan meidän talossamme ei ole enää välinekohtaisia toimituksia vaan aihekohtaisia (taloustoimitus, kotimaan toimitus, urheilutoimitus jne.).

**Comment by LeKorsu** [comment]
Jäi äskeisestä, kannatan siis käsitteen mukaanottoa, mutta mahdollista sulkutarkkenetta tai muuta määritelmää pitäisi varmaan vielä vähän miettiä.

**Comment by mirmaid** [comment]
Jos otetaan niin olisiko _toimitukset (media)_?

**Comment by mariaforsen** [comment]
Sv. redaktioner (media)
