### ISSUE TITLE
koordinaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5322]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koordinaatio](http://www.yso.fi/onto/ysa/Y175421) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Merkitys on syytä selkeyttää ja erottaa koordinointi-termistä. 

#### Perustelut ehdotukselle   

Koordinaatio ja koordinointi -termejä on käytetty ristiin. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Molemmat ryhmässä 00. Melindassa näyttää olevan molemmat käytetty sekä "keskinäisenä toimintana" (eli jotain asioita tai toimintoja koordinoidaan), että "fyysisenä" liikkeiden koordinaatio jne. Pitäisikö lisätä sulkutarkenteita, huomautus, paremmat ryhmät tms.? 
https://github.com/NatLibFi/Finto-data/issues/808

**Comment by mirmaid** [comment]
Toinen termi voisi mahdollisesti olla myös _koordinaatiokyky_. Mikäli jää muotoon koordinaatio, mahdollinen tarkenne olisi esim. (motoriikka).

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja ei erota näitä toisistaa: koordinaatio: sopusuhtainen, sujuva t. tarkoituksenmukainen yhteistoiminta; rinnastus. _Liikkeiden koordinaatio._

**Comment by mirmaid** [comment]
Koordinoinnin sulkutarkenne on hankalampi, koordinointi on lähinnä hallintaa mutta se soveltuu myös motoriikkaan. Yksi ehkä mahdollinen voisi olla _(organisointi)_?

**Comment by mariaforsen** [comment]
Tämä tarvitaan nyt myös JUHOn käännöstyössä. Kannatan yllä olevia ehdotuksia.

**Comment by YSA-kokous** [comment]
koordinaatio (motoriikka) ja koordinaatio (organisointi) KÄ koordinointi
