### ISSUE TITLE
sovitus (uskonto)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5323]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sovitus (uskonto)](http://www.yso.fi/onto/ysa/Y113239) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ratkaistava miten kuvaillaan ihmisten välinen sovitus/hyvittäminen. 

#### Perustelut ehdotukselle   

On ollut försoning Allärsissa, joka voi viitata yhtä hyvin sovitukseen ihmisen ja jumalan välillä kuin ihmisten väliseen. Käytettykin sillä tavalla Melindassa, esim. Reconciliation : restoring justice / John W. de Gruchy ; The reconciliation of peoples : challenge to the churches / ed. by Gregory Baum, Harold Wells ; Efter kriget : den svåra vägen till försoning / Johanna Mannergren Selimovic ; Voiko historiaa hyvittää? : historiallisten vääryyksien korjaaminen ja anteeksiantaminen / toimittanut Jan Löfström ; Remembering and forgetting after war : narratives of truth, justice and reconciliation in a Bosnian town / Johanna Mannergren Selimovic... 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kaunokissa on sovitus (koettaminen) ja sovitus (uskonto) kuten YSAssa, ja lisäksi hyvittäminen. 

Sekä Kaunokissa että YSAssa on myös termi _hyvitys_, jota on käytetty enimmäkseen konkreettisemmasta (vahingonkorvaus tms.), mutta joskus myös tässä merkityksessä, esim. _The age of apology : facing up to the past  / edited by Mark Gibney_; _Kolonialschuld und Entschädigung : der deutsche Völkermord an den Herero (1904-1907)  / Janntje Böhlke-Itzen_ 

Hyvitys ja hyvittäminen ovat merkitykseltään varsin lähellä toisiaan.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/827

_Sovinto_-termin huomautuksen voi kyllä poistaa, koska se liittyy vain osaan termin merkityskentästä. _Sovinto_-termiä on myös käytetty paljon kansainvälisten suhteiden jne. yhteydessä, mutta siihen ei varsinaisesti sisälly hyvittämisen merkitystä - onko se ongelma?

**Comment by mirmaid** [comment]
Jos haluttaisiin laajentaa _sovitus (uskonto)_ -termi kattamaan myös ihmisten ja valtioiden väliset suhteet, vaihdettaisiin termiksi _sovitus (hyvittäminen)_. Olisiko tämä hyvä ratkaisu, ovat kuitenkin melko erilaisia toimintoja? Ja sopisiko suomeksi uskonnon yhteyteen?

_Hyvitys_ ei ainakaan sovellu käytettäväksi kun on kyse uskonnosta (?). Allärsissa vastine on _kompensation_, mutta Bellassa _gottgörelse_ (hyvittäminen = gottgörande).

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/4806

**Comment by mariaforsen** [comment]
Sovinto=förlikning, joten ruotsin osalta se ei oikein sovi tähän ("överenskommelse i godo mellan tvistande parter särsk. vid avtalsförhandlingar el. rättslig tvist")

Myös sovinto=försoning olisi ok, mutta förlikning tarvitaan myös joten sitä ei voi poistaa. MOT:  sovinto 1 (riidan jälkeen) försoning försoningen; tehdä sovinto försonas försonades försonats; ingå försoning; erota sovinnossa skiljas som vänner 2 (sopu) sämja sämjan; samförstånd samförståndet; elää sovinnossa leva i sämja; selvittää asia sovinnossa reda upp en fråga i samförstånd 3 (työriidassa tms.) förlikning förlikningen; tehdä sovinto förlikas förliktes förlikts; ingå (träffa) förlikning med ngn; päästä sovintoon komma fram till en förlikning

**Comment by mirmaid** [comment]
Melindassa enää parikymmentä viitettä, joissa YSA-sanana _sovitus_ ilman sulkutarkennetta, muutama näistäkin olisi _(koettaminen)_ tai _(uskonto)_ -merkityksiä. Lisäksi muutamissa kyse on teoksen sovituksesta (dramatisointi) tms. 

Myös _sovittaminen_ tarvitsee sulkutarkenteen, koska käytetty (vähän) muustakin kuin musiikin sovittamisesta.

Korjataan vielä ja tutkitaan jäljellejäävä kourallinen, tarvitaanko _sovitus (hyvittäminen)_, tai muuta.

**Comment by YSA-kokous** [comment]
Mahdollisesti jaettava sovinto. Korjataan viitteet, tutkitaan voiko försoning-termin uskonnon ulkopuolella ratkaista näin.

Myös sovittaminen tarvitsee sulkutarkenteen, koska käytetty (vähän) muustakin kuin musiikin sovittamisesta.

**Comment by satuniininen** [comment]
Viitteet siivottu, jäi 17, joista

7 x sovitus yksilöiden välillä
6 x sovitus yhteiskuntasopimuksena esim. rotusorron jälkeen
3 x sovitus rikosoikeudellisena ilmiönä
1 x rajatapaus, jossa sovitus rikosoikeudellisena ilmiönä keskiajan kirkko-oikeudessa

**Comment by satuniininen** [comment]
Viitteet siivottu, jäi 17, joista

7 x sovitus yksilöiden välillä
6 x sovitus yhteiskuntasopimuksena esim. rotusorron jälkeen
3 x sovitus rikosoikeudellisena ilmiönä
1 x rajatapaus, jossa sovitus rikosoikeudellisena ilmiönä keskiajan kirkko-oikeudessa https://melinda.kansalliskirjasto.fi/byid/013269912

**Comment by mirmaid** [comment]
sovittaminen - lisätään tarkenne (musiikki)

**Comment by mirmaid** [comment]
Siirtäisin mielelläni sovinto-termin käsittelyn konversion jälkeen, jos sovitus on mahdollista ratkaista ilman sen jakamista.

**Comment by mirmaid** [comment]
Ainakin suomeksi jäljelläoleviin viitteisiin osaan sopii (tai on jo) _anteeksianto/-pyyntö, sovinto_. Osassa voi jättää pois ilman korvaajaa.

**Comment by satuniininen** [comment]
Kaikki korjattu

**Comment by YSA-kokous** [comment]
Sovinto konversion jälkeen.

**Comment by mirmaid** [comment]
_Sovinto_-käsitettä käytetty Melindassa n. 300 kertaa, enemmän muussa kuin oikeustieteen merkityksessä (tähän on lisäksi muutakin termistöä: _sovittelu_ ja _sovintomenettely_). Nyt ryhmät 00 ja 69, suhteet oikeustieteen kannalta. Voisiko englanninkielinen termi olla _reconciliation_?

**Comment by YSO-kokous** [comment]
Jaetaan käsite. Toisen käytettäväksi termiksi: sovinto (oikeustiede)

Toisen käytettävä termi kirkastunee, kun tutkitaan Melinda-käyttöä.

**Comment by mariaforsen** [comment]
Eli YSOssa olisi: sovitus (uskonto), sovinto (oikeustiede), sovinto (suhteet/sosiaalinen tms.)? 

Tämä uusi pitäisi sopia tällaisiin Melindaviitteisiin (joita on runsaasti): 
-Sodasta sovintoon / Kati Katajisto, 
-Ruotsin kirkko tunnustaa osallisuutensa saamelaisten koloniaaliseen lähetyshistoriaan : Arvio Vitboken-artikkelikokoelman ensimmäisestä osasta "Perspektiv på försoning".
-A moral theory of political reconciliation / Colleen Murphy. (tässä on nyt virheellisesti myös sovitus (uskonto) asiasanana)
-Oivaltava kohtaaminen : menetelmiä ihmissuhdetyöhön / Merja Reijonen, Tuija Strandén-Mahlamäki (toim.)

Eli sovinto käytetty toisaalta oikeusmerkityksessä (jo päätetty YSOon) ja toisaalta näihin ylläoleviin. 

Koska kyseessä voi olla sekä ihmistenvälinen että enemmän ryhmien/valtion tasolla oleva sovinto olisi ehkä "suhteet" riittävän laaja tarkenteena? Toinen vaihtoehto mahdollisesti sovinto (sosiaalinen)?

Ja englanniksi sopisi sitten reconciliation? Myös SAOssa on försoning linkattuna reconciliation-termiin.

**Comment by tpalonen** [comment]
Valtion tasolla _sovinto (sosiaalinen)_ ei ehkä toimi. En sinänsä vastusta _sovinto (suhteet)_ -muotoa, mutta ehdotan vielä uutta vaihtoehtoa: _sovinto (vuorovaikutus)_. Perusteluni on kosmeettinen: kielikorvaani jotenkin miellyttää, kun sekä päätermi että sulkutarkenne ovat verbijohdannaisia.

**Comment by mirmaid** [comment]
Täytyy myöntää, että itseltäni on ehkä hukkunut tässä matkalla ajatus siitä, mitä kahta merkitystä oikein ollaan erottamassa: _sovinto (oikeustiede)_ tuntuisi sopivan myös kansainvälisen oikeuden piiriin kuuluviin aineistoihin, joissa kyse ei ole yksityishenkilöiden riita-asiasta (esim. https://melinda.kansalliskirjasto.fi/byid/010172345), kun taas ns. toisen merkityksen pitäisi kattaa aineistot lasten tunnetaidoista kansainvälisiin ja uskontokuntien välisiin konflikteihin ja historiallisten vääryyksien myöntämiseen, mahdollisesti muuhunkin uskonnolliseen (https://melinda.kansalliskirjasto.fi/byid/006456324, https://melinda.kansalliskirjasto.fi/byid/006455474, https://melinda.kansalliskirjasto.fi/byid/006120529).

Tältä pohjalta tuntuu, että _sovinto (oikeustiede)_ on vain yksi tyyppi tätä laajempaa _sovinto_-käsitettä, eli ST. _Vuorovaikutus_-tarkenne soveltuu mihin tahansa sovintoon (paitsi ehkä sovintoon itsensä kanssa), joten se ei tunnu erottelevan varsinaisesti mitään pois. Pitäisikö perua käsitejako, tai jakaa ennemmin selkeämpiin, suppeampiin ryhmiin?

**Comment by mariaforsen** [comment]
Meillä on siis jo sovinto (oikeustiede) joka ainakin ruotsinnoksen mukaan tarkoittaa: Oik. riidan ratkaiseminen osapuolten välisellä sopimuksella. Prosessuaalinen sovinto tuomioistuimessa vireillä olevassa riita-asiassa tehty sovinto. Eli se on hyvin spesifi, ainakin ruotsin vastine förlikning. Kyllä kai siis edelleen tarvitaan ykkösmerkityksessä (Kielitoimiston sanakirja) olevaa termiä? 

Eli toistan se mitä kirjoitin aikaisemmin: Alla oleviin ei sovi (sanastossa jo oleva) förlikning=sovinto (oikeustiede):

-Sodasta sovintoon / Kati Katajisto,
-Ruotsin kirkko tunnustaa osallisuutensa saamelaisten koloniaaliseen lähetyshistoriaan : Arvio Vitboken-artikkelikokoelman ensimmäisestä osasta "Perspektiv på försoning".
-A moral theory of political reconciliation / Colleen Murphy. (tässä on nyt virheellisesti myös sovitus (uskonto) asiasanana)
-Oivaltava kohtaaminen : menetelmiä ihmissuhdetyöhön / Merja Reijonen, Tuija Strandén-Mahlamäki (toim.)

Tähän itse kannattaisin termimuotoa sovinto (suhteet) tms. Kai käyttäjälle olisi selkeää valita jos vaihtoehdot olisivat: sovinto (oikeustiede) ja sovinto (suhteet)?

**Comment by mirmaid** [comment]
^ Ei välttämättä, jos esim. tuosta julkaisusta _An introduction to transitional justice_ pitäisi kuitenkin käyttää _sovinto (suhteet)_, eikä _sovinto (oikeustiede)_ (koska siinä ei ole kyse suomalaisesta siviiliprosessista, mutta on kuitenkin kyse oikeustieteestä).

En siis toki ehdota, että sanastoon jäisi pelkkä sovinto (oikeustiede), vaan mietin, että pitäisikö kuitenkin olla vain yksi sovinto-käsite, joka kattaisi kaikki sovinnot niin erilaisissa oikeuskonteksteissa kuin muissa yhteyksissä. Nyt jako on aika hankala ja vaatisi ehkä oikeustiede-tarkenteen edelleen tarkentamista, jos erotellaan omakseen vain siviiliprosessi ja kaikki muu niputetaan yhteen (vrt. määritelmä/tarkenne, määritelmää lukematta helposti olettaisi, että käsitettä voi käyttää laajemmin kaikesta oikeuden alaan liittyvästä). Eli kuten aiemmin ehdotin, pitäisikö perua käsitejako, tai jakaa ennemmin selkeämpiin, suppeampiin ryhmiin?

**Comment by mariaforsen** [comment]
Ruotsin kannalta en tietty voi kannattaa käsitejaon peruuttamista, koska termi on eri riippuen merkityksestä. Förlikning on nimenomaan oikeustiedemerkityksen vastine, försoning taas suhdemerkityksen.

**Comment by mirmaid** [comment]
^ Entä tuo esimerkkiteos? Tulisiko siihen försoning? Eikä ole riskiä, että kukaan laittaisi förlikning? Meillähän on sanastossa myös _sovintomenettely/förlikningsförfarande_, muistelen, että ajatus oli, ettei sovinto/förlikning ole aina korvattavissa sillä, mutta jos sovinto tässä kapeassa merkityksessä säilytetään, pitäisi suomenkielisen tarkenteen varmaan olla jopa sovintomenettely tai siviiliprosessi tms.

**Comment by mariaforsen** [comment]
Riski on aina olemassa, jos kuvailija ei tutki kyseistä kirjaa tarkemmin ja/tai jos on muuten ammattitaidoton. 
Mutta miksiköhän sovintomenettely ei voisi riittää oikeustiede-merkitykselle? Eli sovinto (oikeustiede) KÄYTÄ sovintomenettely. Jolloin sovinto (suhteet)-termin vastineeksi jää försoning (relationer) (sanastossa myös försoning (religion)=sovitus (uskonto))

**Comment by ilona-x** [comment]
Melindassa käytetty sovinto-termiä 476 kertaa, joista yso-terminä 305 kertaa. Tässä esimerkkejä termeistä, joita esiintyy sovinto-termin kanssa:

sovinto + sovittelu x 140
sovinto + vaihtoehtoinen riidanratkaisu x 47
sovinto + sovintomenettely x 21
sovinto + välimiesmenettely x 32
sovinto + riita-asiat x 87
sovinto + riidat x 62
sovinto + ristiriidat x 19
sovinto + konfliktinratkaisu x 25
sovinto + rauhantyö x 11
sovinto + rauhanneuvottelut x 6
sovinto + rauhanvälitys x 3

**Comment by mirmaid** [comment]
Jos lisätään _sovinto_-käsitteelle tarkenne _(suhteet)_, sitä voi mielestäni ihan hyvin käyttää myös silloin, kun kyse on suomalaisesta siviiliprosessista (onhan siinäkin kyse sovinnosta toistensa kanssa jossakin suhteessa olevien tahojen välillä). Eli mielestäni _suhteet_ ei tarkenteena erottele suomeksi mitään merkitystä pois (tämähän ei suomeksi mene samalla tavalla sekaisin _sovituksen_ kanssa). 

Eli jos katsotaan, että _sovinto (oikeustiede)_ -merkitykseen riittää _sovintomenettely_, ei suomeksi tarvita tarkennetta _sovinto_-käsitteelle. Ruotsiksi tarkenne voi tottakai silti olla.

**Comment by mariaforsen** [comment]
Harmillista monikielisyyden kannalta, mutta kunhan sitten ohjataan käyttöä selkeästi, ettei suomeksikaan käytetä oikeusprosessista, koska jos siihen tulee försoning, sehän menee väärin. Tällä tavalla menetetään ruotsiksi myös käsitettä förlikning, joka on siis tärkeä oikeustieteellinen käsite, ks. https://termipankki.fi/tepa/fi/haku/f%C3%B6rlikning  https://id.kb.se/term/sao/F%C3%B6rlikning
https://id.kb.se/term/sao/F%C3%B6rsoning

**Comment by mirmaid** [comment]
^ Niin tosiaan. Mutta tuo _(suhteet)_ ei siis riitä estämään sitä käyttöä suomeksi kyllä mitenkään.

**Comment by mariaforsen** [comment]
Jos kuvailijalla olisi kaksi mistä valita, eli sovinto (suhteet) ja sovinto (oikeustiede) luulisi olevan selvä. Sen lisäksi tietty voisi olla huomautus, Kielitoimiston sanakirjan mukaisesti.

**Comment by mirmaid** [comment]
^ Ei valitettavasti ole ihan selvä, koska suomeksi esim. tuohon _An introduction to transitional justice_  sopisi aivan hyvin _sovinto (oikeustiede)_. Eli varmaan pitäisi olla _sovinto (sovintomenettely)_ tai _sovinto (siviiliprosessi)_.

**Comment by mirmaid** [comment]
Entä jos olisi sovinto (sovintomenettely), sovinto (siviiliprosessi) KÄ sovintomenettely ja toisena pelkkä sovinto = försoning (relationer). Sille voisi vielä laittaa sovinto (suhteet) ohjaustermiksi, jos se auttaisi?

**Comment by mariaforsen** [comment]
Sen lisäksi on sitten sovitus (uskonto)=försoning (religion), ja ongelmallista on toki että "försoning (relationer) ei välttämättä poissulje uskonnollista merkitystä. Toivottavasti kuvailija osaa kuitenkin näistä kahdesta valita oikein. 
Onko vaarana että sovinto käytetään sitten laajemmin kuin ruotsiksi? Jos suomeksi on ilman tarkennetta.

**Comment by mirmaid** [comment]
^ Pitäisikö tehdä sellainen peräti historiallinen toimenpide tässä lähes historiallisen pitkässä ja hankalassa issuessa, että toteutetaan nyt ehdotetulla tavalla, ja jonkin sovitun ajan kuluttua katsotaan, onko tilanne pysynyt Melindassa hanskassa? Jos ei, palautetaan sitten uuteen käsittelyyn? Eli jos vaikka lisään asian nyt ensi vuoden jälkimmäisen ongelmakokouksen agendalle (ja jos silloin on tullut liian vähän uutta matskua, siirretään sitten vielä seuraavalle vuodelle).

**Comment by YSO-kokous** [comment]
### Päätökset
sovintomenettely KT sovinto (sovintomenettely),  sovinto (siviiliprosessi), sovintoratkaisu 
sovinto = försoning (relationer). KT sovinto (suhteet) - ryhmät 60, 65

Tarkistetaan käsitteen käyttöä kuvaluissa uusissa tietueissa syksyllä 2022

**Comment by mariaforsen** [comment]
Ruotsiksi uusimmat tietueet näyttivät olevan ok.

**Comment by mirmaid** [comment]
^ Halutaanko vielä katsoa uudestaan myöhemmin, nyt kuitenkin vasta muutama uusi viite ratkaisun jälkeen?

**Comment by YSO-kokous** [comment]
**Päätös**

Suljetaan käsittely.
