### ISSUE TITLE
akustiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5324]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[akustiikka](http://www.yso.fi/onto/ysa/Y94563) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko jaettava? 

#### Perustelut ehdotukselle   

Jaettu YSOssa: akustiikka (erikoisala) ja akustiikka (fyysiset ominaisuudet). 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. äänioppi.
2. kaikusuhteet, kuuluvuus. _Konserttisalin akustiikka._

**Comment by mirmaid** [comment]
Kaikkia vastaavia termejä ei kuitenkaan olla jaettu, esim. dynamiikka, mekaniikka, estetiikka.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/714

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): ei vastuteta termin jakamista

**Comment by mariaforsen** [comment]
SAO: akustik, akustik (byggnader) ANV byggnadsakustik, teknisk akustik

**Comment by mirmaid** [comment]
_Acoustics is the interdisciplinary science that deals with the study of all mechanical waves in gases, liquids, and solids._ https://en.wikipedia.org/wiki/Acoustics_(disambiguation)

**Comment by mirmaid** [comment]
Melindan viitteissä merkitys 2. on selvästi yleisempi. Sopivien tarkenteiden löytäminen ei ole ihan helppoa, ainakin _(ominaisuudet)_ on liian salliva (esim. _Phonetics : a practical introduction - Acoustic properties of vowels and consonants_ lienee äänioppia). Toinen voisi olla _akustiikka (fysiikka)_, mutta se ei ole yhtä luonteva kuin _akustiikka (äänioppi)_, joka on kuitenkin luultavasti liian suppea. 

Ainakaan itselleni erottelu ei muutenkaan ole aina helppoa (esim. _The Routledge companion to sounding art; Sound : an acoulogical treatise; Features and applications of the laser-induced spark as a monopole source for acoustic impulse response measurements;  Relationships of microstructure and composition with material and macro level viscoelastic properties of trabecular bone_ - https://en.wikipedia.org/wiki/Acoustic_impedance)

**Comment by YSA-kokous** [comment]
Yhdistetään YSOssa.
