### ISSUE TITLE
sanktiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5325]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sanktiot](http://www.yso.fi/onto/ysa/Y103844) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään tai selkeytetään suhde termeihin pakotteet ja rangaistukset. 

#### Perustelut ehdotukselle   

Ruotsiksi sekä pakotteet että sanktiot = sanktioner. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Ruotsiksi tähän asti ollut: sanktioner, sanktioner (bestraffning) -merkitysero ei ollenkaan selkeä kuvailijalle ja on mahdotonta valita oikein näiden termien perusteella. Mikä on tarkka merkitysero ja miten nämä käytetään suomeksi? Ryhmät kuitenkin samat. Tähän pitäisi saada selvyyttä ennen kuin voidaan luoda tarkoituksenmukaisia sulkutarkenteita ruotsiksi. Englanniksi vastaava tilanne?

Kielitoimiston sanakirja:
**pakote:** painostuskeinona käytetty pakkotoimi; oik., sosiol. normin rikkojaan kohdistuva epämiellyttävä seuraamus, sanktio
**sanktio:** 1. oik. oikeussäännöksen noudattamista tehostava keino (tav. rangaistus), tehoste, seuraamus; kansainvälisessä oikeudessa: (taloudellinen t. pol.) pakote. _Sakko, vahingon korvaaminen ym. sanktiot. YK:n sotaa käyviin maihin kohdistamat taloudelliset sanktiot._
2. psyk., sosiol. seuraamus, esim. palkkio t. rangaistus, jonka avulla pyritään ohjaamaan yksilön käyttäytymistä.
3. oik. lain tms. vahvistaminen.

**Comment by mirmaid** [comment]
Olisiko mahdollista yhdistää: sanktiot KÄ rangaistukset, pakotteet, seuraamukset?

**Comment by mariaforsen** [comment]
Tarvitaan myös JUHO-työssä.

**Comment by ilona-x** [comment]
EKS:
pakotteet
KT sanktio

**Comment by YSA-kokous** [comment]
sanktiot KÄ rangaistukset, pakotteet, seuraamukset

**Comment by mariaforsen** [comment]
Sv. sanktioner
