### ISSUE TITLE
kotitalousoppilaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5326]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotitalousoppilaitokset](http://www.yso.fi/onto/ysa/Y96387) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin koti- ja laitostalousoppilaitokset 

#### Perustelut ehdotukselle   

Sama termi ruotsiksi 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Huomautus: Koti- ja laitostalousoppilaitoksista vuoteen 1987 käytetty nimitys
KT emäntäkoulut

1987 Asetus koti- ja laitostalousoppilaitoksista http://www.finlex.fi/fi/laki/alkup/1987/19870494

Myöhempi nimi pitää sisällään myös aikaisemman, joten muutos olisi sikäli mahdollinen. Tosin kotitalousoppilaitokset on paljon käytetympi: 93/15.

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/756

**Comment by mariaforsen** [comment]
Näiden lisäksi sanastossa myös talouskoulut=hushållskolor (ruotsin osalta hyvä huomioida)

**Comment by mariaforsen** [comment]
Tarvitaan myös JUHO-työssä.

**Comment by YSA-kokous** [comment]
koti- ja laitostalousoppilaitokset
