### ISSUE TITLE
e-äänikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5327]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

e-äänikirjat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

sähköiset äänikirjat, elektroniset äänikirjat 

#### Perustelut ehdotukselle   

Tätä termiä on käytetty ns. omana asiasanana Oulun maakuntakirjastossa, koska tällä asiasanalla asiakkaat hakevat e-äänikirjoja eli verkossa olevia äänikirjoja. Kuulin tämän yhdeltä kirjastovirkailijalta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

e-äänikirjat 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [e-äänikirjat](http://finto.fi/yse/fi/page/Y505327)

**Comment by mariaforsen** [comment]
Sv. e-ljudböcker
