### ISSUE TITLE
organologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5328]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[organologia](http://www.yso.fi/onto/ysa/Y107560) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termiin sulkutarkenne "(morfologia)" erottamaan se organologiasta soittimia tutkivana musiikintutkimuksen osa-alueena. 

#### Perustelut ehdotukselle   

Soitintutkimukselle pitäisi olla oma terminsä (on jo ehdotettu, ks. https://github.com/Finto-ehdotus/YSE/issues/3864). Sille tulisi KT-muodoksi "organologia (musiikintutkimus)" tms, jolloin nykyinen "organologia" ilman sulkutarkennetta arvattavasti vaatisi tarkenteen. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Vai pitäisikö olla _organologia (kasvitiede)_?

**Comment by mariaforsen** [comment]
Sv. organologi (botanik) 
 "Kasvimorfologia, eli muoto-oppi, tutkii lähinnä kasvien ulkomuotoa ja niiden eri osien keskinäisiä asentosuhteita. Tässä mielessä siitä käytetään myös nimityksiä organologia ja organografia."

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8310
