### ISSUE TITLE
leipäjono

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5330]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

leipäjono 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Käytetty vapaana asiasanana Melindassa. Tarve käyttää sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://epublications.uef.fi/pub/urn_isbn_978-952-61-2517-6/urn_isbn_978-952-61-2517-6.pdf 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [leipäjono](http://finto.fi/yse/fi/page/Y505330)

**Comment by jtuohini** [comment]
Pitäisikö olla monikossa? Lähin LCSH-vastine joka tapauksessa lienee **Food banks** [http://id.loc.gov/authorities/subjects/sh98002440].
Ja olisiko YSAn KT-muoto _ruokapankit_, _ruokapankkitoiminta_ tms?

**Comment by mirmaid** [comment]
Melindassa 2 viitettä (monikossa). YSAssa on _elintarvikeapu_, jota käytetty tässäkin kontekstissa runsaasti, tarvitaanko tarkempaa? Leipäjonot-termissä on vähän eri näkökulma kuin tuossa ruokapankkitoiminnassa ("koettu köyhyys"?).

**Comment by satuniininen** [comment]
Engl. vastine _food queue_ tai _bread queue_, molempia käytetään. En siltaisi _Food banks_ -käsitteeseen.

**Comment by mariaforsen** [comment]
Sv. brödkö

**Comment by YSA-kokous** [comment]
KÄ elintarvikeapu
