### ISSUE TITLE
kliiniset kokeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5331]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kliiniset kokeet](http://www.yso.fi/onto/ysa/Y214003) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Allärs-vastine pitäisi lisätä 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi 

#### Perustelut ehdotukselle   

Allärs-vastine puuttuu

**Comment by mirmaid** [comment]
On lisätty.
