### ISSUE TITLE
kompleksiyhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5332]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kompleksiyhdisteet 

#### Ehdotettu termi englanniksi   

coordination complexes 

#### Ehdotettu termi ruotsiksi   

komplex (kemi) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kemialliset yhdisteet](http://www.yso.fi/onto/yso/p324) 

#### Assosiatiiviset (RT)   

[organometalliyhdisteet](http://www.yso.fi/onto/yso/p28123) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Kompleksi_(kemia) 
LCSH : <http://id.loc.gov/authorities/subjects/sh85029365> 

#### Vaihtoehtoiset termit ja ilmaisut   

kompleksit (kemia), koordinaatiokompleksit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Tarkoitusta täsmentävä selite   

Kemiallinen yhdiste, jossa keskusatomi(-ioni) ja sen ympärillä sidoksella kiinnittyneitä ligandeja (ioneja tai molekyylejä) 

#### Perustelut ehdotukselle   

Yleinen tutkimuskohde kemiassa. Käytetään esim. väriaineissa. Melindasta löytyy termillä "kompleksiyhdisteet" jo 52 tulosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jykdok.1644098 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan organisaatio:** Jyväskylän yliopisto / Avoimen tiedon keskus 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi **Termiehdotus Fintossa:** [kompleksiyhdisteet](http://finto.fi/yse/fi/page/Y505332)

**Comment by mariaforsen** [comment]
Sv. koordinationsföreningar ET komplex (kemi) ET komplexa föreningar
