### ISSUE TITLE
monitavoiteoptimointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5333]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

monitavoiteoptimointi 

#### Ehdotettu termi englanniksi   

multi-objective optimization 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matemaattinen optimointi](http://www.yso.fi/onto/yso/p17635) 

#### Assosiatiiviset (RT)   

[pareto-tehokkuus](http://www.yso.fi/onto/yso/p28039) 

#### exactMatch   

Wikipedia : https://en.wikipedia.org/wiki/Multi-objective_optimization 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Tarkoitusta täsmentävä selite   

Matemaattisen optimoinnin tyyppi, jossa yritetään optimoida samanaikaisesti useaa kohdefunktiota. 

#### Vaihtoehtoiset termit ja ilmaisut   

pareto-optimointi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jykdok.1702296 

#### Perustelut ehdotukselle   

Kansainvälisesti hyvin paljon tutkittu matemaattisen optimoinnin tyyppi, koska sillä on runsaasti sovellusmahdollisuuksia eri aloilla. Melindassa "monitavoiteoptimointi", 31 tulosta. 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan organisaatio:** Jyväskylän yliopisto / Avoimen tiedon keskus 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi **Termiehdotus Fintossa:** [monitavoiteoptimointi](http://finto.fi/yse/fi/page/Y505333)

**Comment by mirmaid** [comment]
Melindassa n. 20 viitettä (asiasanana).

YSAssa pareto-optimointi KÄ _pareto-tehokkuus_.

**Comment by mariaforsen** [comment]
Sv. flermålsoptimering ET multiobjektiv optimering ET Pareto-optimering
