### ISSUE TITLE
endofyytit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5334]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[endofyytit](http://www.yso.fi/onto/ysa/Y151210) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan termin endofyytit määritelmä. Nykyisen määritelmän mukaan ne ovat eläimissä loisivia kasveja. En löytänyt tälle määritelmälle mitään lähdettä. Sen sijaan "endofyytit" tarkoittaa yleisesti kasvien sisällä eläviä mikro-organismeja, jotka usein ovat hyödyllisiä isäntälajeilleen. Näin ollen myös yläkäsite "loiset" ja korvatut termit "sisäloiskasvit" pitäisi vaihtaa. 

#### Perustelut ehdotukselle   

Kaikki Melindasta löytämäni julkaisut, jossa termiä "endofyytit" käytetään vaikuttavat viittaavan tähän merkitykseen:
https://fi.wikipedia.org/wiki/Endofyytti
https://en.wikipedia.org/wiki/Endophyte 

#### Ehdottaja   

Matti Rajahonka 

#### Ehdottajan organisaatio   

Jyväskylän yliopisto / Avoimen tiedon keskus 

#### Ehdottajan sähköpostiosoite   

matti-petteri.rajahonka@jyu.fi

**Comment by mirmaid** [comment]
Olisipa hauska tietää mistä tämä määritelmä tosiaan on lähtöisin...korjattu.
