### ISSUE TITLE
koettu hyvinvointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5335]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koettu hyvinvointi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Käytetty Melindassa vapaana terminä. Tarvittu sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://epublications.uef.fi/pub/urn_isbn_978-952-61-2517-6/urn_isbn_978-952-61-2517-6.pdf 

#### Tarkoitusta täsmentävä selite   

Esim. "Koettu hyvinvointi koostuu elämään
tyytyväisyydestä (itse arvioituna) sekä kahdesta
hyvinvointiin liittyvästä ”tuntemuksesta” (affect):
positiivisissa tuntemuksissa kartoitetaan itse arvioitua
onnellisuutta, iloa ja tyydytystä, negatiivisissa
surua, vihaa, pelkoa ja ahdistusta." lähde: https://www.julkari.fi/bitstream/handle/10024/104460/simpura.pdf?sequence=1 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [koettu hyvinvointi](http://finto.fi/yse/fi/page/Y505335)

**Comment by mirmaid** [comment]
Kerran Melindassa.

YSAssa on _koettu terveys_, TSR-ontologiassa lisäksi _koettu muutos_, _koettu tuloksellisuus_ ja _koettu työkyky_.

Hyvinvointi on jaettu YSOssa _hyvinvointi (terveydellinen)_ ja _hyvinvointi (taloudellinen)_.

**Comment by mariaforsen** [comment]
Sv. upplevt välbefinnande ET upplevd välfärd ET upplevt välmående
