### ISSUE TITLE
mansikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5338]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mansikka](http://www.yso.fi/onto/ysa/Y97285) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Joko muutetaan muotoon puutarhamansikka, tai mansikat, jolloin tarkoittaisi koko kasvisukua, ST ahomansikka. 

#### Perustelut ehdotukselle   

Nykyisellään merkitys epätarkka 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by PaiviLipsanen** [comment]
https://laji.fi/taxon/MX.38868

Mansikka/mansikat(marjat) voisi olla käsitteenä joka tarkoittaisi nimenomaan marjaa, eikä kasvilajia

**Comment by mirmaid** [comment]
Muiden marjojen osalta on nyt kuitenkin tehty niin, että nimi on katsottu lajin nimeksi: puolukat (suku) ST mustikka, puolukka (laji) jne.

**Comment by PaiviLipsanen** [comment]
Ehdotus:
mansikat (suku)
- ahomansikka
- puutarhamansikka
https://laji.fi/taxon/MX.38868
