### ISSUE TITLE
kirsikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5339]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kirsikka](http://www.yso.fi/onto/ysa/Y101560) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan monikkoon 

#### Perustelut ehdotukselle   

Kyseessä on Cerasus-alasuku 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by PaiviLipsanen** [comment]
hapankirsikka (Prunus cerasus) ja imeläkirsikka (Prunus avium) kuuluvat sukuun tuomet (Prunus)
https://laji.fi/taxon/MX.38933
Näiden hedelmiä kutsutaan kirsikoiksi. 
Ehdotus hierakiasta
hedelmät
- kirsikat

**Comment by mirmaid** [comment]
Wikipedian mukaan _Cerasus on ruusukasveihin lukeutuvan Prunus-suvun alasuku, johon kuuluvat varsinaiset kirsikat._ Kaikkien tieteelliset nimet ovat varmaan kuitenkin muotos Prunus xxxx. 

Ne hedelmät jotka eivät ole kasvilajeja on nyt jätetty yksikössä käsitteen hedelmät alakäsitteiksi ja niin voidaan ehkä tehdä kirsikan osalta myös. Hedelmien ja marjojen hierarkia on kyllä hankala käyttäjää ajatellen, mutta en oikein keksi millä asian voisi ratkaista, koska jakaminen lajiin ja kasvinosaan vain vaihtaa yhden ongelman toiseen...

**Comment by PaiviLipsanen** [comment]
Näköjään laji.fi:ssä Prunus-suku onkin suomeksi "luumut"

**Comment by YSA-kokous** [comment]
kirsikka LT hedelmät
