### ISSUE TITLE
gootit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5340]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[gootit](http://www.yso.fi/onto/ysa/Y101447) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö jakaa tms.? 

#### Perustelut ehdotukselle   

Käytetty Melindassa paljon myös alakultturi-merkityksessä. Esim. Goth chic : a connoisseur’s guide to dark culture / Gavin Baddeley ; edited by Paul A. Woods. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
YSAssa on myös _goottikulttuuri_.

**Comment by mirmaid** [comment]
_gootit (kansat)_

gootit (alakulttuurit) KÄ _goottikulttuuri_ TAI _gootit (osakulttuurit)_ omana asiasananaan, mutta ovat kyllä hyvin lähellä toisiaan nuo termit, ellei joku keksi parempaa tarkennetta?

**Comment by krinay** [comment]
Kannatan tuota ensimmäistä ehdotusta, siis:
gootit (alakulttuurit) KÄ goottikulttuuri

**Comment by YSA-kokous** [comment]
gootit (alakulttuurit) KÄ goottikulttuuri
gootit (kansat)

**Comment by mariaforsen** [comment]
Sv.
-gothare > gothkultur
-goter
