### ISSUE TITLE
verkkotutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5341]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

verkkotutkimus 

#### exactMatch   

Internet research : LCSH 

#### Tarkoitusta täsmentävä selite   

laadullisen ja määrällisen tutkimuksen tekeminen Internetissä
ks teos "Verkkotutkimus opinnäytetyönä : laadullisen ja määrällisen verkkotutkimuksen opas" https://uef.finna.fi/Record/josku.1100703 

#### Perustelut ehdotukselle   

Tarve asiasanalle sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://epublications.uef.fi/pub/urn_isbn_978-952-61-2229-8/urn_isbn_978-952-61-2229-8.pdf 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [verkkotutkimus](http://finto.fi/yse/fi/page/Y505341)

**Comment by mirmaid** [comment]
Ei Melindassa.

LCSH: Here are entered works on using the Internet to conduct research.

**Comment by YSA-kokous** [comment]
Lisätään määritelmä.

**Comment by mariaforsen** [comment]
Sv. internetforskning ET onlineforskning ET onlineundersökning

**Comment by mirmaid** [comment]
_Verkon välityksellä voidaan tutkia perinteistä fyysistä maailmaa, mutta toisaalta tutkimuksen kohteena voi olla itse verkkomaailma: mitä ihmiset tekevät verkossa, miten he toimivat, miten he organisoituvat ja miten heihin voidaan vaikuttaa. Kirjassa käsitellään myös verkkoliikenteen mittaamisen työkaluja (web-analytiikka)._ 
https://tahtijulkaisut.pikakirjakauppa.fi/tuote/jorma_kananen/verkkotutkimus_opinnaytetyona_laadullisen_ja_maarallisen_verkkotutkimuksen/9789518303490

http://blogs.helsinki.fi/jmatikai/files/2010/09/Verkkometodjm.pdf 

Oliko niin että tämä halutaan rajata kuten LCSH:ssa?

**Comment by mariaforsen** [comment]
Jos todella halutaan rajata niin kapeasti, vain ja ainoastaan siihen, se vaatii varmaan sulkutarkenteen (muuten käytetään sekalaisissa merkityksissä huomautuksesta huolimatta)? Ruotsiksi se voisi mahdollisesti olla "internet som metod" tms. Varma on ainakin se että pelkkä "internetforskning" tulkitaan kyllä laajasti/useassa merkityksessä, esim. näin https://blogs.abo.fi/forskarbloggen/2012/05/07/internet-forskning-vid-abo-akademi/ (=fi. kohteena itse verkkomaailma..) 
tai ehkä lähinnä erilaiset "verkkotutkimukset" (verkon kautta kerättyjä kyselyitä yms.)

**Comment by YSA-kokous** [comment]
Ei erotella merkityksiä.
