### ISSUE TITLE
karpalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5342]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[karpalo](http://www.yso.fi/onto/ysa/Y102231) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Täytyykö tarkentaa? 

#### Perustelut ehdotukselle   

Melindassa aineistoa sekä isokarpalosta (eniten), amerikankarpalosta että pikkukarpalosta. Useimmista viitteistä ei kuitenkaan käy varmuudella ilmi mikä näistä on kyseessä (todennäköisimmin isokarpalo). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by PaiviLipsanen** [comment]
Yleensä tarkoitetaan isokarpaloa, kun puhutaan karpalosta. Pikkukarpalon marjat ovat paljon pienempiä, joten niitä kerättäneen vähemmän.
http://www.luontoportti.com/suomi/fi/kukkakasvit/isokarpalo
Karpalo voisi olla omana käsitteenään marjana (molempien lajien marjana), kuten pihlajanmarja ja ruusunmarja.

**Comment by YSA-kokous** [comment]
karpalo LT marjat
