### ISSUE TITLE
ammattiopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5343]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ammattiopettajat](http://www.yso.fi/onto/ysa/Y106747) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin ammatillisten opintojen opettajat 

#### Perustelut ehdotukselle   

YSOssa yhdistetty. Huomautus: "Ammatillisten opintojen opettajista vuoteen 1994 käytetty nimitys". Suurin osa tällä termillä kuvaillusta aineistosta on kuitenkin uudempaa. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. 
-yrkeslärare (fi. ammatilliset opettajat)
-lärare i yrkesinriktade studier (fi. ammatillisten opintojen opettajat)
OBS. yrkeslärare=ammattiopettajat raderad
