### ISSUE TITLE
arabeskit (kuvataide)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5344]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

arabeskit (kuvataide) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 

#### Perustelut ehdotukselle   

Käytetty Melindassa tässä merkityksessä joitakin kertoja. Tulossa YSAan MUSAsta musiikkiterminä, molemmat tarvitsevat tarkenteen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Mirja Anttila 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [arabeskit (kuvataide)](http://finto.fi/yse/fi/page/Y505344)

**Comment by jtuohini** [comment]
LCSH-vastine tälle taidetermille on **Arabesques** [http://id.loc.gov/authorities/subjects/sh85006289]. MUSAsta periytyvälle "musiikkarabeskille" ei LCSH:ssa ole omaa asiasanaa. Toisaalta siellä on termi **Arabesk (Turkish popular music)** [http://id.loc.gov/authorities/subjects/sh2005000016], jolle taas ei löydy vastinetta suomalaisissa sanastoissa (kun ei ole tainnut olla tarvetta).

**Comment by mariaforsen** [comment]
Sv. arabesker (bildkonst)
