### ISSUE TITLE
ammattikoulutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5349]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ammattikoulutus](http://www.yso.fi/onto/ysa/Y94621) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin ammatillinen koulutus. 

#### Perustelut ehdotukselle   

Erottelu hankalaa käyttäjän kannalta. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by YSO-kokous** [comment]
YSAn huomautukset:

**ammattikoulutus:** Aiemmin ammattikoulutus tarkoitti ammattikouluastetta vastaavaa koulutusta. 2000-luvun alkupuolelta lähtien termiä ammattikoulutus on käytetty epävirallisessa tekstissä ja puhekielessä.

**ammatillinen koulutus:** Aiemmin ammatillinen koulutus -käsite kattoi kouluasteen, opistoasteen sekä ammatillisen korkea-asteen koulutuksen. 2000-luvun alkupuolelta lähtien ammatillisella koulutuksella on tarkoitettu perusopetuksen jälkeistä toisen asteen ammatillista koulutusta.

**Comment by YSO-kokous** [comment]
https://github.com/NatLibFi/Finto-data/issues/858

**Comment by mariaforsen** [comment]
Sv. yrkesutbildning ET yrkesinriktad utbildning
