### ISSUE TITLE
psykoanalyyttinen kirjallisuudentutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5350]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

psykoanalyyttinen kirjallisuudentutkimus 

#### Ehdotettu termi ruotsiksi   

psykoanalytisk litteraturforskning 

#### Ehdotettu termi englanniksi   

psychoanalytic criticism, Freudian criticism (molemmat Hosiaisluomalta) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p1066) 

#### Assosiatiiviset (RT)   

[biografinen kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p11108) 
[fenomenologinen kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p29675) 

#### Tarkoitusta täsmentävä selite   

Määritelmä: tutkimussuuntaus, jossa hyödynnetään psykoanalyyttista teoriaa kirjailijoiden ja kirjallisuuden tarkastelussa
Psykoanalyyttistä kirjallisuudentutkimusta on kehitetty erityisesti strukturalismin, feministisen kirjallisuudentutkimuksen ja jälkistrukturalismin piirissä, jossa freudilaiseen ajattelun traditioon on suhtauduttu myös kriittisesti. Tunnetuimpia suuntauksen nykytutkijoista ovat Julia Kristeva, Hélène Cixous ja Luce Irigaray. Psykoanalyyttinen traditio on keskeinen teoreettinen viitekehys myös dekonstruktiossa.
(Termipankki lähteenään Hosiaisluoma) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käytetty Artossa 15 kertaa, Helkassa 4 kertaa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [psykoanalyyttinen kirjallisuudentutkimus](http://finto.fi/yse/fi/page/Y505350)

**Comment by jtuohini** [comment]
Ehdotuksen LCSH-vastine on **Psychoanalysis and literature** [http://id.loc.gov/authorities/subjects/sh85108417], KT-muotoinaan _Literature and psychoanalysis_ ja _Psychoanalytic literary criticism_.

**Comment by mirmaid** [comment]
26 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. psykoanalytisk litteraturforskning
