### ISSUE TITLE
psykologinen kirjallisuudentutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5351]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

psykologinen kirjallisuudentutkimus 

#### Ehdotettu termi ruotsiksi   

psykologisk litteraturforskning 

#### Ehdotettu termi englanniksi   

psychological criticism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p1066) 

#### Assosiatiiviset (RT)   

[biografinen kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p11108) 
[kognitiivinen kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p10334) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Psykologista tietämystä hyödyntävä suuntaus, jossa tarkastellaan esim. sanataideteoksen ihmiskuvausta, kuten henkilöhahmojen yksiulotteisuutta vs. moniulotteisuutta, yhtenäisyyttä vs. pirstoutuneisuutta ja pysyvyyttä vs. muuttuvuutta sekä henkilöiden toiminnan motiiveja. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 5 kertaa, Helkassa 6 kertaa 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [psykologinen kirjallisuudentutkimus](http://finto.fi/yse/fi/page/Y505351)

**Comment by jtuohini** [comment]
LCSH-vastineina **Psychology and literature** [http://id.loc.gov/authorities/subjects/sh85108486] ja sille ST-suhteinen **Literature--Psychology** [http://id.loc.gov/authorities/subjects/sh85077525].

**Comment by mirmaid** [comment]
Melindassa 8 viitettä.

**Comment by mariaforsen** [comment]
Sv. psykologisk litteraturforskning
