### ISSUE TITLE
valmiudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5352]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valmiudet](http://www.yso.fi/onto/ysa/Y113478) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteen jakaminen:

valmius KT toimintavalmius
valmiudet KT yksilön valmiudet
(+ sulkutarkeet varmaankin molemmille) 

#### Perustelut ehdotukselle   

Käsitteellä voidaan viitata sekä erilaisten organisaatiotoimijoiden toimintavalmiuteen (esim. puolustusvalmius) että yksilön ominaisuuksiin (esim. oppimisvalmiudet). Olisiko nämä merkitykset syytä erottaa toisistaan? 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mariaforsen** [comment]
Jonkinlainen erottelu tarvitaan myös ruotsin osalta (beredskap vs. färdigheter). Ks. esim. MOT Finnish-Swedish ja vrt. Melinda. Ruotsin osalta kuitenkin huomioitava että sanastossa myös taidot=färdigheter.  Beredskap ei käytetä ruotsinruotsissa yksilöiden taidoista yms. (ks. esim. NE ja Rikstermbanken). 

Tarvitaan myös JUHO-työssä.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 3. monitulkintaisuuden vuoksi us. selvemmin toisin. Valmius [paremmin: kyky] itsenäiseen ajatteluun. Käytännön valmiuksia [paremmin: tietoja ja taitoja] antava kurssi. Henkilö, jolla on valmiudet toimia [paremmin: joka pystyy toimimaan] yllättävissäkin tilanteissa. Liikkeen valmius [paremmin: kyky, mahdollisuus t. halukkuus] myymiensä tuotteiden huoltoon. 

Suomeksikin usein voisi korvata yksilön ollessa kyseessä muilla termeillä, esim. _taidot, kyvykkyys, lahjakkuus._

**Comment by mirmaid** [comment]
Tämä on kyllä varsin hankala muutettava - Melindassa 460 viitettä läpikäytävää, ja vaikka jätettäisiin vain organisaation toimintavalmius, tarvitaan sulkutarkenne tai uusi termi joka sulkee yksilön kyvyt pois. Tai jos jätettäisiin toimintavalmius, ja sitä käytettäisiin myös ihmisen kyvystä toimia jossakin kontekstissa, olisiko se väärin?

Valmiudet henkilön ominaisuuksina voi usein korvata sanalla taidot, mutta ei aina, esim. _Sijaisvanhemmuudessa tarvittavien valmiuksien arviointi PRIDE-ennakkovalmennuksessa_ (tässä muuten ruotsiksi beredskap, onko virhe?). _Färdigheter_ olisi ihan suoraan sama kuin valmiudet, taidot sitten taas usein jo enemmän _kunskaper_.

_Patient suitability for short-term and long-term psychotherapy_, tässäkin _beredskap_?

**Comment by mariaforsen** [comment]
Beredskap: tillståndet att vara beredd på kommande utveckling, särsk. faror, kriser o.d. Tosin suomenruotsalaisissa teksteissä käytetään beredskap laajemminkin. Eli on väärin käytetty näissä tapauksissa. Tästä varoitetaan TEPAssakin: "beredskap (i allmänhet ej om person)"

**Comment by YSA-kokous** [comment]
Seuraava kokous, pohjustetaan.

**Comment by mirmaid** [comment]
Jos muutettaisiin mahdollisuus monikkoon kuten Kaunokissa (tosin se on YSAssa nyt filosofian terminä), olisi ehkä helpompi poistaa tämä (KÄ taidot, kyvykkyys, mahdollisuudet). 

Entä PUHO-termi _valmiustilat_ http://www.yso.fi/onto/puho/ph1361? http://www.nurmijarvi.fi/teemasivut/tilanne_paalla/valmiustilat.

**Comment by mariaforsen** [comment]
Möjligheter=mahdollisuudet olisi hyvä. "Valmiustilat" näyttää olevan käytetty eri merkityksissä googlessa, voi olla hankala kääntää ruotsiksi (beredskaptillstånd ei samassa merkityksessä kuin nurmijärven sivuilla).

**Comment by EsaMPKK** [comment]
Eri tasoiset valmiustilat eri tilanteissa.

**Comment by mirmaid** [comment]
Ylivoimaisesti suurin osa viitteistä käsittelee yksilön valmiuksia, joten ratkaistaan ja korjataan ne ensin. Ongelmana kielten hieman erilainen jako _valmiudet-taidot-tieto_ / _färdigheter-kunskap(er)_.

**Comment by AuHo22** [comment]
Myös yleistermi **edellytykset** (sv. **förutsättningar**) on YSOssa

Ks. myös https://www.kielikello.fi/-/monimerkityksinen-valmius

**Comment by mirmaid** [comment]
KÄ taidot, kyvyt, edellytykset (?)

Jos organisaatioille tarvitaan vielä jotain, otetaan jokin selkeämpi termi.

**Comment by mariaforsen** [comment]
Kannatan viimeisin ehdotus. Taidot ei ole yhtä kuin kunskaper, vaan se pitää kyllä jatkossakin olla färdigheter. Tällä tavalla kun laitetaan valmiudet KÄYTÄ taidot , kyvyt, edellytykset niin ongelma on ratkaistu. 

Jos halutaan sen lisäksi organisaatioille termi niin toimintavalmius=funktions/aktionsberedskap tms. on hyvä termi, sopisi esim. näille: https://melinda.kansalliskirjasto.fi/F/5MJNXSXFN6IVH13FKGBNXEYTT7C318DYENV47NRVVQP7UE3HQN-05856?func=find-c&ccl_term=WRD=%22toimintavalmius%22&filter_code_1=WLA&filter_request_1=

**Comment by mirmaid** [comment]
_Toimintavalmius_ vaatinee suomeksi tarkenteen, jotta sitä ei varmasti käytettäisi yksilöistä.

**Comment by YSO-kokous** [comment]
Poistetaan valmiudet-käsite. Lisätään ohjaustermit seuraavasti:
valmiudet KÄYTÄ taidot
valmiudet KÄYTÄ kyvyt
valmiudet KÄYTÄ edellytykset

Tutkitaan Melindan perkaamisen yhteydessä, sopisiko muuhun kontekstiin seuraava käsite ja termi: toimintavalmius (organisaatiot)

(Sanastossa on jo kriisivalmius.)

**Comment by ilona-x** [comment]
Korjattu Melindaan, jäljelle jäi 18 viitettä, joista osaan saattaisi sopia toimintavalmius (organisaatiot)

**Comment by mirmaid** [comment]
Näköjään _toimintavalmius_ käytetty 9 kertaa Melindassa, usein juuri pelastustoimen yhteydessä. Näissä 18 viitteessä osa näyttää tosiaan tulevan lähelle kriisivalmiuden aluetta. Johonkin yksittäiseen voisi sopia valmistautuminen, mutta kieltämättä noissa pelastustoimeen liittyvissä toimintavalmius kuulostaa hyvältä.

**Comment by mariaforsen** [comment]
Eli kyseessä tämä https://termipankki.fi/tepa/fi/haku/toimintavalmius ?

**Comment by mirmaid** [comment]
No tuolla on aika tiukkaa määritelmää, mutta ainakin vahvasti sen suuntainen 😃

**Comment by YSO-kokous** [comment]
### Päätös
otetaan sanastoon käsite toimintavalmius

**Comment by mariaforsen** [comment]
Sv. aktionsberedskap, funktionsberedskap HT insatsberedskap 
https://termipankki.fi/tepa/fi/haku/toimintavalmius
https://www.finlex.fi/sv/laki/ajantasa/2011/20110379
