### ISSUE TITLE
oppilasvalinnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5353]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oppilasvalinnat](http://www.yso.fi/onto/ysa/Y97848) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

oppilasvalinnat
http://finto.fi/ysa/fi/page/Y97848

opiskelijavalinnat
http://finto.fi/ysa/fi/page/Y97833

ASSOSIATIIVISET KÄSITTEET
    opiskelijavalinnat / oppilasvalinnat
    pääsykokeet
    yhteishaku
    yhteisvalinta

Toisen on varmaan tarkoitus olla oppilaan tekemiä valintoja opiskelun suhteen ja toisen oppilaitoksen tekemiä opiskelijoiden sisäänottovalintoja?

Muuten termit tarkoittavat ~samaa asiaa. 

#### Perustelut ehdotukselle   

Blah. 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by mirmaid** [comment]
Olettaisin että tässä on erona enemmänkin se, minkä asteen opinnoista on kyse, oppilaat itse tekevät ainevalintoja. Voiko näitä yhdistää, valintoja voidaan tehdä jo peruskouluvaiheessa?

**Comment by mariaforsen** [comment]
Ruotsiksi nämä nyt (sanastojen ja sanakirjojen mukaisesti): elevantagning, antagning av studerande. Eli mikään niistä ei ruotsiksi ainakaan viittaa oppilaiden/opiskelijoiden tekemiin valintoihin, vaan molemmat siihen että oppilas/opiskelija valitaan/pääsee johonkin kouluun. Kyllä näin näyttää olevan paljon Melindassakin. Sanat elev (oppilas) ja studerande (opiskelija) eivät kuitenkaan ainakaan ruotsiksi ole täysin synonymisia, peruskoulussa yms. käytetään elev ja korkeammassa koulutuksessa studerande. 

MOT: oppilasvalinta: oppilaiden valinta oppilaitokseen. 
opiskelijavalinta (sv. antagning av studerande, eng. student admission) osana "Koulutukseen hyväksyminen, käsite 456"

**Comment by YSA-kokous** [comment]
Ei muutosta.
