### ISSUE TITLE
Aberdeen (Yhdysvallat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5354]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Aberdeen (Yhdysvallat)](http://www.yso.fi/onto/ysa/Y166761) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisi täsmentää esim. huomautuksella 

#### Perustelut ehdotukselle   

Samannimisiä on useita, esim. Wikidatassa: https://www.wikidata.org/w/index.php?search=Aberdeen&title=Special:Search&profile=default&fulltext=1&searchToken=4xncgv7tmpi7rkmdf2rqjrti6 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by mirmaid** [comment]
Aberdeen (Washington) / Aberdeen (Washington, Yhdysvallat)?

**Comment by mirmaid** [comment]
Aberdeen (Washington (osavaltio))
