### ISSUE TITLE
Akaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5355]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Akaa](http://www.yso.fi/onto/ysa/Y106977) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisi jakaa kahtia, koska tarkoittaa sekä entistä kuntaa että nykyistä kaupunkia. 

#### Perustelut ehdotukselle   

Wikidatassa nämä ovat kaksi eri entiteettiä ja niiden välillä differentFrom-suhde. 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansallsikirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Akaa (kunta)
Akaa (kaupunki)

Korjattu Melindaan 18.10.2017
