### ISSUE TITLE
purkaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5356]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[purkaminen](http://www.yso.fi/onto/ysa/Y104052) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko kuten YSOssa: 
purkaminen (logistiikka)
purkaminen (oikeudellinen)
purkaminen (rakennusala) 

#### Perustelut ehdotukselle   

Käytetty eri merkityksissä Melindassa. Käyttäjä joka haluaa aineistoa purkamisesta rakennusalalla tuskin haluaa tieota purkamisesta oikeudellisessa merkityksessä. Ruotsiksi eri termit eri merkityksille. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Rakennusten ohella ainakin kulkuneuvojen purkaminen esiintyy useammissa viitteissä, satunnaisesti myös muita (esim. rautatien, pommin, urkujen).

Erilaisten sopimusten (työsuhde, vuokrasopimus) ohella oikeuden alaan liittyen ainakin huostaanoton ja yrityksen purkaminen.

Koodin purkaminen (?)

**Comment by satuniininen** [comment]
purkaminen (lakkauttaminen)
purkaminen (osiin)
purkaminen (kuorman) 

Ei kyllä ratkaise koodin purkamista :D

**Comment by mirmaid** [comment]
^ Vai pitäisikö olla _purkaminen (kuormat)_?

**Comment by ilona-x** [comment]
Sulkutarkenne lakkauttaminen ei tunnu kovin selkeältä kaikissa tapauksissa, osassa kyseessä enemminkin kumoaminen esim. kaupan purku, eli ottaisin mieluummin tuon vaihtoehdon **purkaminen (oikeudellinen)**.

Lisäksi voisi tehdä ohjauksen tuomion purkaminen/tuomionpurku KÄYTÄ ylimääräinen muutoksenhaku (EKS:ssa vastaava ohjaus)

**Comment by YSA-kokous** [comment]
purkaminen (oikeudellinen)
purkaminen (osiin)
purkaminen (logistiikka)

tuomion purkaminen,tuomionpurku KÄ ylimääräinen muutoksenhaku
