### ISSUE TITLE
Auschwitz

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5357]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Auschwitz](http://www.yso.fi/onto/ysa/Y144621) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisi täsmentää, tarkoitetaanko tällä keskitysleiriä vai kaupunkia (Oswiecim puolaksi). 

#### Perustelut ehdotukselle   

Wikidatassa ovat eri entiteettejä 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansallsikirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by jtuohini** [comment]
Jako menisi siis:
**110 2_ |a Konzentrationslager Auschwitz**     [tai **Auschwitz (keskitysleiri)**, **Auschwitzin keskitysleiri** tms.; joka tapauksessa X10-kentän asiaa (https://www.loc.gov/marc/bibliographic/ambiguous-headings.html)]
ja
**151 __ |a Oświęcim (Puola)**     [AACR2:n ja RDA:n mukainen muoto]
451 __ |a Auschwitz (Puola)

**Comment by mirmaid** [comment]
Sama koskee ainakin Treblinkaa.

**Comment by YSA-kokous** [comment]
Korjataan.
