### ISSUE TITLE
Tuska (festifaali)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5358]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tuska (festifaali) 

#### Assosiatiiviset (RT)   

[festivaalit](http://www.yso.fi/onto/yso/p1304) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Esim. Ruisrock on auktorisoitu sanastoon 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789520115630 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi-hintikka@btj.fi **Termiehdotus Fintossa:** [Tuska (festifaali)](http://finto.fi/yse/fi/page/Y505358)

**Comment by LeKorsu** [comment]
Samoin Ilosaarirock, joten ilman muuta Tuskakin.

**Comment by mariaforsen** [comment]
Sv. Tuska ET Tuska Open Air
