### ISSUE TITLE
kuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5359]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuva 

#### Ehdotettu termi ruotsiksi   

bild 

#### Ehdotettu termi englanniksi   

image 

#### Assosiatiiviset (RT)   

[allegoriat](http://www.yso.fi/onto/yso/p5555) 
[symbolit](http://www.yso.fi/onto/yso/p2015) 
[vertaukset](http://www.yso.fi/onto/yso/p5556) 

#### Tarkoitusta täsmentävä selite   

Runokuva; sanallinen havainnollisuus; visualisoiva ilmaisu. Runokuva on ensisijaisesti ymmärrettävä kuvana ja vasta toissijaisesti vertauskuvana. (Hosiaisluoma) "Konkreettisempi"  kuin kielikuva. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 5 kertaa, Helkassa 8 kertaa. 

**Ehdottajan nimi:** anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kuva](http://finto.fi/yse/fi/page/Y505359)

**Comment by LeKorsu** [comment]
Vaatinee selitystä ja/tai sulkutarkkennetta, ettei ruveta käyttämään kuvat-termin sijasta.

**Comment by mirmaid** [comment]
Molemmat tarvitsisivat tarkenteen. Tämän voisi ehkä ottaa muodossa _runokuvat_, määritelmä on kyllä aika epämääräinen: _ensisijaisesti ymmärrettävä kuvana ja vasta toissijaisesti vertauskuvana; "konkreettisempi" kuin kielikuva._

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by krinay** [comment]
**Runokuvat** olisi hyvä vaihtoehto yleiseen asiasanastoon. Sillä voidaan kuitata sekä tämä termiehdotus että ehdotus termistä kuvallisuus, ks. #5360.

**Comment by mariaforsen** [comment]
Runokuva=poetisk bild ok. 
Pelkkä bild ei käy tähän merkitykseen, enkä kannata ongelmallisten yksikkö/monikko-parien lisäämistä.

**Comment by YSA-kokous** [comment]
runokuvat
