### ISSUE TITLE
kuvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5360]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuvallisuus 

#### Ehdotettu termi englanniksi   

imagery 

#### Alakäsitteet (RT)   

[allegoriat](http://www.yso.fi/onto/yso/p5555) 
[symbolit](http://www.yso.fi/onto/yso/p2015) 
[vertaukset](http://www.yso.fi/onto/yso/p5556) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 9 kertaa, Helkassa 8 kertaa 

#### Tarkoitusta täsmentävä selite   

Kuvallisuuteen liittyy 3 "kuvaa": kuva = mielikuva, aistihavainto; 2 kielikuva = vertauskuvallisuus; 3 typografinen, visuaalinen kuva= tekstin asettelu 

**Ehdottajan nimi:** anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kuvallisuus](http://finto.fi/yse/fi/page/Y505360)

**Comment by jtuohini** [comment]
Jos kuvailtava aineisto käsittelee kuvallisuutta yhden tai useamman mainitun "kuvan" kannalta, eikö kuvailija mieluiten kuitenkin laittaisi täsmällisemmät asiasanat? Esimerkiksi "typografisen kuvallisuuden" osalta käyttäisi YSA-termejä **layout**, **taitto** (tarkoittaako muuten YSAssa samaa kuin edellinen?), **typografia** ja **visuaalisuus** ja lisäksi jotain, joka kytkisi tämän kaiken tekstuaaliseen sisältöön, kuten **kuvarunot**, **taiteidenvälisyys**, **visuaalinen runous** yms? Toisin sanoen: mihin tarvittaisiin tätä kovin monimerkityksiseltä vaikuttavaa uutta termiä?

**Comment by mirmaid** [comment]
Melindassa 17 viitettä.

**Comment by mariaforsen** [comment]
Vastinetta ei välttämättä löydy ruotsiksi. Visualitet olisi ollut mahdollinen vastine, mutta se on jo Allärsissa (fi. visuaalisuus). Ja jos joudutaan luomaan vastineita on erittäin tärkeää että suomenkielinen termi on yksiselitteinen ja määritelty tarkkaan.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by krinay** [comment]
Tämän voisi korvata termillä _runokuvat_, joka kattaisi myös termin/termihedotuksen _kuva_, #5359.

**Comment by AuHo22** [comment]
Käännös englanniksi imagery tarkoittaa mielestäni yhtälailla kielikuvia, joka termi jo on sanastossa. Myös kuvakieli KÄ kielikuvat. Pärjännemme nykyisillä termeillä, joita myös yllä Jaakon kommenteissa?

**Comment by OutiHintikka** [comment]
Kuvallisuus on laajempi käsite kuin yksittäinen kielikuva tms.

**Comment by YSA-kokous** [comment]
runokuvat

**Comment by mariaforsen** [comment]
Sv. poetiska bilder
