### ISSUE TITLE
subteksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5361]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

subteksti 

#### Ehdotettu termi ruotsiksi   

subtext 

#### Ehdotettu termi englanniksi   

subtext 

#### Ehdotettu yläkäsite YSOssa (LT)   

[intertekstuaalisuus](http://www.yso.fi/onto/yso/p17213) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 3 kertaa, Helkassa 2 kertaa. 

#### Tarkoitusta täsmentävä selite   

Selite Jo olemassaoleva teksti (tai tekstijoukko), joka tulee esiin uudessa tekstissä; kätketty, mutta lukijan tai kuulijan havaittavissa oleva merkitys; pohjateksti. (Tieteen termipankki) 

**Ehdottajan nimi:** anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [subteksti](http://finto.fi/yse/fi/page/Y505361)

**Comment by jtuohini** [comment]
LCSH-vastine **Subtext (Drama, novel, etc.)** [http://id.loc.gov/authorities/subjects/sh95006370].

**Comment by mirmaid** [comment]
Melindassa 29 viitettä.

**Comment by mariaforsen** [comment]
Sv. undertext (litteratur) ET subtext (litteratur)
