### ISSUE TITLE
syntyhistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5362]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syntyhistoria 

#### Ehdotettu termi englanniksi   

genesis 

#### Ehdotettu termi ruotsiksi   

uppkomsthistoria 

#### Ehdotettu yläkäsite YSOssa (LT)   

[alkuperä](http://www.yso.fi/onto/yso/p18426) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helkassa 6 kertaa, Artossa 6 kertaa (Oikeastaan yleistermi) 

**Ehdottajan nimi:** anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [syntyhistoria](http://finto.fi/yse/fi/page/Y505362)

**Comment by jtuohini** [comment]
Parempi temaattinen ryhmä olisi **_90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria_**, koska syntyhistoria voi yhtä hyvin koskea myös muita taiteenlajeja kuin kirjallisuutta.

**Comment by mirmaid** [comment]
Melindassa 26 viitettä. Käytetty eniten kirjallisuudentutkimuksen terminä, mutta muutamia kertoja myös kielen kehityksestä.

**Comment by satuniininen** [comment]
Vaatii englanniksi sulkutarkenteen, josta ilmenee käsitteen käyttökonteksti. 

Ehdotuksia otetaan mielellään vastaan!

**Comment by krinay** [comment]
Syntyhistoria (teokset) voisi toimia suomeksi, mutta ei englanniksi genesis (works (cultural objects)). :)
Entä syntyhistoria (taiteelliset teokset) - genesis (artistic works)?

**Comment by YSA-kokous** [comment]
teoksen syntyhistoria (?)

**Comment by krinay** [comment]
_Teoksen syntyhistoria_ on varmaan ihan ok, mutta hoksaavatko tiedonhakijat etsiä sitä asiasanoja etsiessään? _Syntyhistoria (taiteelliset teokset)_ voisi löytyä helpommin.

**Comment by jtuohini** [comment]
Entä lisäksi KT-muodot _taideteosten syntyhistoria_, _teosten syntyhistoria_ jne? ("Teokset" + "syntyhistoria" > tarve monikolle.)

**Comment by YSA-kokous** [comment]
syntyhistoria (teokset)

**Comment by mariaforsen** [comment]
Sv. uppkomsthistoria (verk)

**Comment by tpalonen** [comment]
YSO-kokouksessa käsittelimme tätä käsitettä. Tässä issuessa aiemmin käydyn keskustelun ja alkuehdotuksenkin pohjalta ehdotamme, että tätä ei rajata pelkästään taideteosten kontekstiin. Tätähän on käytetty Helkassa ja Melindassa enemmänkin yleisterminä. Esim. aatteella voi olla syntyhistoria.

Olisiko jokin toinen sulkutarkenne parempi tai tarvitaanko sulkutarkennetta ollenkaan? Jokin muukin ryhmä kuin 90 olisi myös hyvä, jos käsitteen merkityskenttä on laajempi.

**Comment by jtuohini** [comment]
Aatteiden syntyhistoria pitäisi paremminkin ilmaista asiasanalla **aatehistoria**; Wikipediaa lainatenkin "Aatehistoria on ihmiskunnan sivistyksen historiaa: oppia ja tutkimusta siitä, miten eri aatteet ovat syntyneet suhteessa omaan aikaansa ja ympäristöönsä."

**Comment by mirmaid** [comment]
Viitteet on jo korjattu Melindassa, joten ehdottaisin että palataan aiheeseen, jos ilmenee tarvetta laajemmalle kuvailukäytölle. Termi on toistaiseksi joka tapauksessa erittäin vähän käytetty.
