### ISSUE TITLE
luottamustaso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5364]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luottamustaso 

#### Ehdotettu termi englanniksi   

confidence level 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Tarkoitusta täsmentävä selite   

"Luottamustaso (confidence level) kertoo, millä todennäköisyydellä perusjoukkoa kuvaava tunnusluku on jollain tietyllä luottamusvälillä."
lähde: http://www.fsd.uta.fi/menetelmaopetus/paattely/paattely.html 

#### Perustelut ehdotukselle   

Tarvittu sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uef.finna.fi/Record/josku.1079676 

**Ehdottajan nimi:** Tarja Turunen 
**Ehdottajan sähköpostiosoite:** tarja-liisa.turunen@uef.fi **Termiehdotus Fintossa:** [luottamustaso](http://finto.fi/yse/fi/page/Y505364)

**Comment by jtuohini** [comment]
Ja lähin LCSH-vastine lienee **Observed confidence levels (Statistics)** [http://id.loc.gov/authorities/subjects/sh2007006298].

**Comment by mirmaid** [comment]
Ei Melindassa.

http://www.statisticshowto.com/confidence-level/

Yksikkö vai monikko?

**Comment by YSA-kokous** [comment]
luottamustasot

**Comment by mariaforsen** [comment]
Sv. konfidensnivåer ET konfidensgrader ET tillförlitlighetsgrader
