### ISSUE TITLE
kirjasodat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5365]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjasodat 

#### Ehdotettu termi englanniksi   

literary disputes 

#### Ehdotettu termi ruotsiksi   

bokkrig 

#### Ehdotettu yläkäsite YSOssa (LT)   

[riidat](http://www.yso.fi/onto/yso/p7944) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Määritelmä laajalle yhteiskuntaan levinnyt kiista, joka liittyy tiettyyn kirjaan
Selite Kirjasota edellyttää yleensä suhteellisen kehittynyttä kirjallista julkisuutta.Suomessa kirjasotia on käyty kiivaimmin 1920-30-luvulla ja 1950-60-luvulla. Yleensä niitä on esiintynyt yhteiskunnan ja kulttuurin murrosaikoina. (Tieteen termipankki) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 4 kertaa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kirjasodat](http://finto.fi/yse/fi/page/Y505365)

**Comment by amssi** [comment]
Piti oleman LT kulttuuripolitiikka, eikä riidat.
RT sensuuri

**Comment by mirmaid** [comment]
Melindassa 5 viitettä.

**Comment by mariaforsen** [comment]
Sv. litterära fejder ET bokkrig ET litterära dispyter
