### ISSUE TITLE
kirjailijavierailut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5366]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjailijavierailut 

#### Ehdotettu termi ruotsiksi   

författarbesök 

#### Ehdotettu termi englanniksi   

author visits 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yleisötilaisuudet](http://www.yso.fi/onto/yso/p2109) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 8 kertaa. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kirjailijavierailut](http://finto.fi/yse/fi/page/Y505366)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. författarbesök
