### ISSUE TITLE
kronotooppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5367]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kronotooppi 

#### Ehdotettu termi englanniksi   

chronotope 

#### Ehdotettu termi ruotsiksi   

kronotop 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aikarakenne (kerronta)](http://www.yso.fi/onto/yso/p28413) 

#### Tarkoitusta täsmentävä selite   

Ajallisten ja paikallisten suhteiden punoutuminen erottamattomaksi merkityskokonaisuudeksi; tila-aikaulottuvuus; aikapaikallisuus. (Hosiaisluoma) Käsite on keskeinen Mihail Bahtinin teoksessa Voprosy literatury i estetiki (1975, Kirjallisuuden ja estetiikan ongelmia), jossa eroteltiin romaanityyppejä toisistaan. Bahtinin romaaniteoriassa kullakin romaanigenrellä oli omanlaisensa kronotopia, ajan ja paikan yhdistelmä, josta käsin lajin maailmankuva ilmeni. Tällaisia kronotooppeja olivat Bahtinin mukaan esimerkiksi idylli, tie ja kynnys. (Termipankki) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty 5 kertaa, Helkassa 4 kertaa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kronotooppi](http://finto.fi/yse/fi/page/Y505367)

**Comment by mirmaid** [comment]
Melindassa 9 kertaa yksikössä, kerran monikossa.

**Comment by tpalonen** [comment]
Mihail Bahtin: Kirjallisuuden ja estetiikaan ongelmia:
_"Kirjallisuudessa taiteellisesti haltuunotettujen ajallisten ja paikallisten suhteiden olennaista keskinäistä sidonnaisuutta nimitämme kronotoopiksi (joka on kirjaimellisesti käännettynä "aikapaikallisuus"). - - Ymmärrämme kronotoopin kirjallisuuden muodollis-sisällölliseksi kategoriaksi (emme koskettele mulla kulttuurin alueilla esiintyvää kronotooppia). Kaunokirjallisessa kronotoopissa paikalliset ja ajalliset tunnusmerkit ovat punoutuneet toisiinsa mielekkääksi ja konkreettiseksi kokonaisuudeksi. Aika sakenee, tiivistyy ja muuttuu siinä taiteellisesti havaittavaksi; paikallisuus puolestaan voimaperäistyy, tempautuu ajanjuoksuun, juonen ja historian kulkuun. - - Kronotoopilla on kirjallisuudessa lajinominaisuuksia määräävä merkitys. Voitaneen sanoa suoraan, että lajin ja lajintunnusmerkit määrää nimenomaan kronotooppi, ja kirjallisuudessa aika on kronotoopin ratkaiseva momentti."_

**Comment by YSA-kokous** [comment]
kronotoopit

**Comment by mariaforsen** [comment]
Sv. kronotoper
