### ISSUE TITLE
rakennusperintö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5368]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakennusperintö](http://www.yso.fi/onto/ysa/Y117635) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-suhde termiin "kulttuuriperintö" 

#### Perustelut ehdotukselle   

Rakennusperintö on osa kulttuuriperintöä, mikä olisi hyvä tulla ilmi myös termien keskinäisessä suhteessa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ok
