### ISSUE TITLE
Lake Placid

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5369]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Lake Placid](http://www.yso.fi/onto/ysa/Y123965) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisi täsmentää mistä Lake Placidista on kysymys 

#### Perustelut ehdotukselle   

Samannimisiä on useita Wikidatassa/Wikipediassa, kts. https://en.wikipedia.org/wiki/Lake_Placid 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansallsikirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by mirmaid** [comment]
Riittääkö tähän Lake Placid (New York)? Lake Placid on sekä kylä (2500 as.) että järvi, ja New York luonnollisesti tässä osavaltio. LCSH ei erottele järveä ja kylää.
