### ISSUE TITLE
Hankavesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5370]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hankavesi](http://www.yso.fi/onto/ysa/Y112259) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisi jakaa, koska tarkoittaa kahta eri järveä 

#### Perustelut ehdotukselle   

Ei pysty mäppäämään kunnolla Paikannimirekisteriin (mäpätty molempiin järviin tällä hetkellä) eikä Wikidataan 

#### Ehdottaja   

Osma Suominen 

#### Ehdottajan organisaatio   

Kansallsikirjasto 

#### Ehdottajan sähköpostiosoite   

osma.suominen@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa:

Hankavesi (Hankasalmi)
Hankavesi (Ähtäri)

Korjattu Melindaan 13.10.2017
