### ISSUE TITLE
molekyylineurologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5372]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

molekyylineurologia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

On olemassa molekyylineurologian tutkimusohjelma (Biomedicum, Helsinki). Googlessa osumia 1820 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarvittu esim. Duodecimin artikkelin indeksoinnissa. Artikkeli: STAT3-geenin mutaatio aiheuttaa haiman endokriinisten solujen ennenaikaisen erilaistumisen ja vastasyntyneen diabeteksen, Duodecim 2017, 2. 

**Ehdottajan nimi:** Elina Mäkelä 
**Ehdottajan organisaatio:** BTJ Finland / Aleksi-artikkelitietokanta 
**Ehdottajan sähköpostiosoite:** elina.makela@btj.fi **Termiehdotus Fintossa:** [molekyylineurologia](http://finto.fi/yse/fi/page/Y505372)

**Comment by mirmaid** [comment]
Melindassa 3 viitettä termillä _molekyylineurobiologia_ (Google vain 2).

**Comment by mariaforsen** [comment]
Sv. molekylär neurobiologi ET molekylär neurologi
