### ISSUE TITLE
äänilevyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5373]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänilevyt](http://www.yso.fi/onto/ysa/Y100512) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termiin seuraavat KT-muodot: gramofonilevyt, EP-levyt, EP-äänilevyt, LP-levyt, LP-äänilevyt, savikiekot. 

#### Perustelut ehdotukselle   

. . 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by jtuohini** [comment]
Kauhean noloa: ei tietenkään KT-muodoiksi _EP-levyt_ (joka on jo KT-muotona termille **EP:t** [http://www.yso.fi/onto/ysa/Y214459]) eikä _EP-äänilevyt_ (jonka vastaavasti voisi lisätä KT-muodoksi kyseiselle **EP:t**-termille).

**Comment by ksornova** [comment]
eli lisätä voisi seuraavat KT-muodot: gramofonilevyt, LP-levyt, LP-äänilevyt, savikiekot.
ja jos menee samalla, EP:t-termiin voisi lisätä tuon: EP-äänilevyt

**Comment by mariaforsen** [comment]
Tämä vielä ratkaisematta/toteuttamatta: https://github.com/Finto-ehdotus/YSE/issues/5629 
Eli äänilevyt edelleen ongelmallinen monikielisyyden kannalta.

**Comment by EsaMPKK** [comment]
Savikiekot myös ammunnassa.
