### ISSUE TITLE
oopperat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5374]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oopperat](http://www.yso.fi/onto/ysa/Y97801) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT oopperateokset 

#### Perustelut ehdotukselle   

Googlaamalla löytyy noin 2 000 osumaa termille "oopperateos", ja lisäksi se on varsinaista asiasanaa määrittävässä kuvailutekstissä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by jtuohini** [comment]
Ja vielä toinenkin KT-lisäys: "oopperasävellykset".

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): kannatetaan, myös KT oopperasävellykset

**Comment by jarmosaarikko** [comment]
siis oopperat halutaan jakaa useaan osaan: oopperateokset, oopperasävellykset ja oopperaesitykset?   Koostuuko "oopperateos"  siis -sävellyksestä ja -lavastuksesta ja -esityksestä, mutta ei ole niiden yläkäsite?

**Comment by jtuohini** [comment]
Ei, vaan:

**oopperat**
   LT   sävellykset
   KT   musiikkidraamat
   KT   oopperasävellykset
   KT   oopperateokset
   ST   divertissementit
   ST   kamarioopperat
   ST   pastissioopperat
   ST   televisio-oopperat
   ST   zarzuelat
 
**oopperataide**
   LT   esittävät taiteet
   KT   ooppera
   ST   Peking-ooppera

Lisäksi on erikseen oopperaan suoraan tai välillisesti liittyvät: **ohjaukset**, **oopperaohjaus**, **produktiot** ynnä **skenografia** ja sen ST-termit
