### ISSUE TITLE
palkaton työ

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5375]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

palkaton työ 

#### Assosiatiiviset (RT)   

[orjuus](http://www.yso.fi/onto/yso/p11204) 

#### Vaihtoehtoiset termit ja ilmaisut   

ilmaistyö 

#### Tarkoitusta täsmentävä selite   

Ilmaistyö on palkatonta työtä, jossa työn palkattomuus on epäsuhdassa työntekijän osaamistasoon ja työnkuvaan nähden. Esimerkiksi teetetään itsenäisesti tehtävää asiantuntijatyötä työllistetyllä, työharjoittelijalla, työkokeilijalla tai työelämävalmennettavalla ilman korvausta. Henkilö on voinut tehdä aiemmin samaa työtä jopa samassa organoisaatiossa. Ilmiön mahdollistavat työttömyys yhdistettynä ns. tempputyöllistämiseen sekä ns. osaamisen näyttäminen. - Ei tarkoita vapaaehtoistyötä eikä kotona tehtävää työtä, . - Ilmaistyö on yhteiskunnallinen ongelma ("negatiivinen käsite"). 

#### Perustelut ehdotukselle   

Ilmiö on olemassa, joten sille pitäisi olla termi. Wittgenstein: Kieleni rajat ovat maailmani rajat. Artikkeleissa käytettään termiä ilmaistyö. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Viimeisin artikkeli oli Talouselämä-lehdessä 2017: 23 Tänään työssä -palstalla. Myös Long Play julkaisi noin 1 v sitten aiheesta artikkelin. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [palkaton työ](http://finto.fi/yse/fi/page/Y505375)

**Comment by jtuohini** [comment]
LCSH-vastine lienee **Unpaid labor** [http://id.loc.gov/authorities/subjects/sh2015001910], jonka KT-muodot ovat _Unpaid work_, _Unremunerated labor_, _Unremunerated work_ ja _Work, Unpaid_.

**Comment by mirmaid** [comment]
Melindassa 2 viitettä.

**Comment by LeKorsu** [comment]
Palkaton työ on parempi kuin ilmaistyö

**Comment by YSA-kokous** [comment]
palkaton työ, lisätään määritelmä

**Comment by mariaforsen** [comment]
Sv. oavlönat arbete ET obetalt arbete ET gratisarbete

**Comment by mirmaid** [comment]
Määritelmä: _Tarkoittaa työskentelyä harjoittelijana, työllistettynä tms. tehtävässä, josta maksettu korvaus ei ole suhteessa työn vaativuuteen._ 
Huomautus: _Termiä ei käytetä kuvailtaessa aineistoa jonka aiheena on vapaaehtoistyö tai kotityö._
