### ISSUE TITLE
Hossan kansallispuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5376]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Hossan kansallispuisto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Tarkoitusta täsmentävä selite   

YSA:ssa on vain Hossan retkeilyalue. Hossasta on hiljattain tullut kansallispuisto. 

#### Perustelut ehdotukselle   

ks. yllä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Viimeksi Kaltio 2017: 3 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [Hossan kansallispuisto](http://finto.fi/yse/fi/page/Y505376)

**Comment by mariaforsen** [comment]
Sv. Hossa nationalpark
