### ISSUE TITLE
muzak

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5377]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muzak](http://www.yso.fi/onto/ysa/Y103623) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan tämä KT-muodoksi termille "taustamusiikki". 

#### Perustelut ehdotukselle   

"Muzak" on hissimusiikin eli taustamusiikin yhden kaupallisen toimijan nimestä johdettu yleisnimi. Ysaan parhaillaan yhdistettävässä Musiikin asiasanastossa "muzak" on KT-muoto "taustamusiikille", ja Melindassakin "taustamusiikki" on huomattavasi käytetympi jopa Ysa-terminä kuin "muzak". 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Kannatan!

**Comment by mirmaid** [comment]
Kaikki taustamusiikki ei kuitenkaan ole hissimusiikkia, ks. Melindan viitteet.

**Comment by mariaforsen** [comment]
Tämä ei ole aivan ongelmatonta, ainakaan ruotsin osalta.. Muzak on tietynlainen taustamusiikki, jolla tietynlainen tarkoitus, ks. esim. Nationalencyklopedin: 
-muzak: benämning på bakgrundsmusik, som allt efter typ och orkestrering är avsedd att ha en positiv, snarast omedveten, inverkan på t.ex. uthållighet i arbete, köpvillighet och allmän trivselkänsla. 
-bakgrundsmusik:  har sedan antiken använts för att ackompanjera och ge stämning åt olika utommusikaliska aktiviteter... 
Ruotsiksi muzak on siis oikeastaan ST termille taustamusiikki.

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by ilkkahaataja** [comment]
Luumu-kokous (31.10.2017): Puollamme.
