### ISSUE TITLE
musiikkitiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5378]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkitiede](http://www.yso.fi/onto/ysa/Y101329) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termin "musiikintutkimus" KT-muodoksi. 

#### Perustelut ehdotukselle   

YSAan parhaillaan yhdistettävässä Musiikin asiasanastossa on "musiikkitiede" KÄ "musiikintutkimus". Lisäksi YSAssa on jo vanhastaan "musiikkitieteilijät" KÄ "musiikintutkijat". Kyseisellä alalla on oppikiistoja, joihin takertumisen välttämiseksi olisi neutraalimpaa puhua vain musiikintutkimuksesta (kuin ruveta miettimään, onko "etnomusikologia" "musiikkitieteen" alalaji vai sille rinnakkainen yms). Lisäksi "musiikkintutkimus" kattaisi helpommin musiikinteorian tutkimisen yms kuin tiukemmin alalla määritelty musiikkitiede. Muiksi KT-muodoiksi voisi samoin tein ottaa ainakin termit "historiallinen musiikkitiede", "systemaattinen musiikkitiede" ja "uusi musiikkitiede". 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Ruotsiksi voi olla vaikeaa yhdistää näitä tällä tavalla. Musikvetenskap ja musikforskning ovat eri asioita tai ainakin eri näkökulmista lähestytty.. SAOssakin on molemmat. Jos kuitenkin täytyy valita vain yksi se täytyisi varmasti olla musikvetenskap.

**Comment by asormune** [comment]
Jos musiikkitiede laitetaan KT muodoksi, käytetäänkö kaikesta sellaisesta musiikintutkimuksesta, jolla ei ole yksiselitteitä nimeä, termiä "musiikintutkimus". Vrt. "kognitiivinen musiikintutkimus", sillä on termi. Jos musiikkitiede termi poistetaan, on myös muutettava näiden "alalajien" määritelmät (esim. kognitiivinen musiikkitiede on tällä hetkellä:  Musiikkitieteen suuntaus, joka tutkii musiikkia kognitiotieteen näkökulmasta)

**Comment by YSA-kokous** [comment]
Ei muutosta.

**Comment by jtuohini** [comment]
Vastaus Anun (juuri huomaamaani) kommenttiin: käytettäisiin. Ja alalajien määritelmät tarkistettaisiin.
 
Ja vastaus Marialle: ruotsiksi ehdottomasti neutraalimpi olisi **musikforskning**, koska se kattaisi sekä musiikkitieteen, etnomusikologian, ns. uuden musiikkitieteen, kulttuurisen musiikintutkimuksen (siinä määrin kun sen haluaa erottaa musiikinsosiologiasta) että muuten joukkoon sopimattoman musiikkianalyysin. Ja näistä siis etnomusikologia on välillä hyvinkin vahvasti haluttu nähdä vastakohdaksi (perinteiselle) musiikkitieteelle.

Musassa oli taannoin vain yksi yhteinen termi ja se riitti. On vaikea nähdä, miksi Ysassa tarvitsisi taas jakaa nämä osin luonnottomasti kahtia. LCSH:ssakin on riittänyt yksi, **[Musicology](http://id.loc.gov/authorities/subjects/sh85089048)** (KT _Music--Research_, _Musical research_ ja _Research, Musical_), jolla ST-suhteet asiasanoihin **Ethnomusicology**, **Music archaeology**, **Music--Editing** (musiikkifilologia siis), **National socialism and musicology** ja **Sound recordings in musicology** ja RT-suhteet asiasanoihin **Music--Historiography** (musiikinhistorian historiankirjoitus) ja **Popular music--Historiography**.

**Comment by mariaforsen** [comment]
Musikvetenskap on kyllä niin vakiintunut muoto ja kaikin puolin tärkeä termi ruotsiksi (sekä paljon käytetty Melindassa) että on epäselvää voidaanko siitä luopua, siihen tosin sanaryhmämme musiikkihenkilö (Sibeliusmuseosta) saa myös ottaa kantaa jos tulee ajankohtaiseksi (voi olla että säilytetään musikvetenskap=musiikintutkimus siinä tapauksessa) Käsitteitä -tiede/-tutkimus käsitellään yleensäkin hieman eri tavalla ruotsiksi kuin suomeksi, vrt. myös muita -tutkimus/-tiede-sanoja Allärsissa (esim. informationsvetenskap=informaatiotutkimus) ja ruotsalaisia vs. suomalaisia ruotsinkielisiä sivuja (esim. "musikforskning" site:se antaa marginaalisesti tuloksia, sen sijaan musikvetenskap käytetään kaikilla yliopistoilla jne., sekä Nationalencyklopedin ohjaa myös siihen...) Musikvetenskap-termiä ei nähdä "epäneutraalina" ruotsiksi.

**Comment by mirmaid** [comment]
Myös vastaavia pareja on, esim. _kielitiede/kielentutkimus_, _työtiede/työntutkimus_. Kirjallisuustiede kuitenkin KÄ _kirjallisuudentutkimus_. 

Molemmat ovat runsaasti käytettyjä Melindassa, musiikkitiede kuitenkin selvästi enemmän (samoin Googlella).

Musiikkitiede on oppiaineen nimenä: Helsingin yliopisto, Turun yliopisto, Itä-Suomen yliopisto, Jyväskylän yliopisto. 

Jos yhdistetään, musiikintutkimus ei ehkä ole suomeksi niin suoraviivaisesti korvattavissa musiikkitiede-termillä kuin päinvastoin. Toisaalta jos _musikvetenskap_ on oikein, silloin pitäisi myös musiikkitiede sopia.

**Comment by YSA-kokous** [comment]
musiikintutkimus KT musiikkitiede

**Comment by mariaforsen** [comment]
Sv. musikforskning ET musikvetenskap
