### ISSUE TITLE
allemande

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5379]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

allemande 

#### Ehdotettu termi ruotsiksi   

allemande 

#### Ehdotettu termi englanniksi   

allemande 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssit](http://www.yso.fi/onto/yso/p3046) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85003647> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Allemande 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Vaihtoehtoiset termit ja ilmaisut   

allemanda, almain, alman, almond 

#### Tarkoitusta täsmentävä selite   

Eurooppalainen 1500-luvulla syntynyt tasajakoinen paritanssi. 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [allemande](http://finto.fi/yse/fi/page/Y505379)

**Comment by jtuohini** [comment]
Ehdotettu muoto tietysti "allemande (tanssit)" sanastossa jo olevien muiden tanssien tapaan.

**Comment by ksornova** [comment]
Kannatetaan!

**Comment by mariaforsen** [comment]
Sv. allemande (danser)
