### ISSUE TITLE
allemandet (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5380]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

allemandet (sävellykset) 

#### Ehdotettu termi ruotsiksi   

allemander 

#### Ehdotettu termi englanniksi   

allemandes 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sävellykset](http://www.yso.fi/onto/yso/p1515) 

#### Assosiatiiviset (RT)   

[tanssimusiikki](http://www.yso.fi/onto/yso/p181) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85003648> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Allemande 

#### Vaihtoehtoiset termit ja ilmaisut   

allemandat, almainit, almanit, almondit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Tarkoitusta täsmentävä selite   

Allemanden tanssimista varten sävelletty musiikki tai allemanden tanssimista varten sävellettyä musiikkia imitoiva musiikki. 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [allemandet (sävellykset)](http://finto.fi/yse/fi/page/Y505380)

**Comment by mariaforsen** [comment]
allemander (kompositioner)
