### ISSUE TITLE
piratismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5381]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[piratismi](http://www.yso.fi/onto/ysa/Y98136) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan "KT piraattituotteet", ja vastaavasti luodaan tästä poistettavasta oma terminsä ("piratismi" on ilmiö, "piraattituotteet" pääasiassa konkreettisia esineitä). 

#### Perustelut ehdotukselle   

Lisäksi Musasta Ysaan tulossa oleva käsite "bootlegit" tulisi uuden termin "piraattituotteet" ST-suhteiseksi termiksi, mikä suhde taas olisi mahdoton nykyiseen "piratistmi"-termiin. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Entä tuoteväärennökset (nyt YSAssa)? RT?

**Comment by TommiViitamies** [comment]
Bootlegit eivät ole varsinaisesti piraattituotteita termin tuoteväärennös-merkityksessä, vaan oikeudenomistajien luvatta tehtyjä "alkuperäistuotteita".

**Comment by YSA-kokous** [comment]
Otetaan piraattituotteet, lisätään määritelmät.

**Comment by ilona-x** [comment]
http://tulli.fi/henkiloasiakkaat/netista-tilaajalle/tuotevaarennokset

**Piraattikopio** on tuote, johon on luvattomasti kopioitu toisen tekijänoikeudella suojattu teos.

**Tuoteväärennös** on tuote, johon on luvattomasti liitetty toiselle kuuluva tavaramerkki tai sen jäljitelmä, tai tuote, joka luvattomasti imitoi toisen tuotteen mallioikeudella suojattua ulkomuotoa.
