### ISSUE TITLE
yksinsaapuvat (pakolais)lapset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5382]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yksinsaapuvat (pakolais)lapset 

#### Ehdotettu termi ruotsiksi   

Ensamkommande barn2 sao0 331988 

#### Ehdotettu termi englanniksi   

Unaccompanied refugee children 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

Asiaa on melko vaikea ilmaista muuten. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Psykisk ohälsa hos ensamkommande flyktingbarn 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [yksinsaapuvat (pakolais)lapset](http://finto.fi/yse/fi/page/Y505382)

**Comment by jtuohini** [comment]
LCSH-vastine sama kuin yllä termin englanninkielinen muoto eli **Unaccompanied refugee children** [http://id.loc.gov/authorities/subjects/sh2007002870].

**Comment by mirmaid** [comment]
YSAssa on _yksintulleet pakolaislapset_

**Comment by mariaforsen** [comment]
Ensamkommande flyktingbarn on jo Allärsissa.
