### ISSUE TITLE
pakohuoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5383]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pakohuoneet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit](http://www.yso.fi/onto/yso/p6062) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Google 24 100 osumaa. Viimeksi aiheesta oli Signum 2017: 2 -lehdessä, jossa pakohuone oli osa pedagogiikkaan liittyvää pelillistämistä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ks. yllä 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [pakohuoneet](http://finto.fi/yse/fi/page/Y505383)

**Comment by mirmaid** [comment]
Ei Melindassa.

https://fi.wikipedia.org/wiki/Tosiel%C3%A4m%C3%A4n_pakopeli

Pakohuonepelit on lähes yhtä yleinen kuin pakohuoneet, pakopelit tuo eniten viitteitä.

**Comment by satuniininen** [comment]
Kannatan muotoa _pakopelit_ + muut termimuodot ohjaustermeiksi.

**Comment by YSA-kokous** [comment]
pakopelit

**Comment by mariaforsen** [comment]
Sv. rymningsspel ET escape room-spel
