### ISSUE TITLE
Kempeleen vanha kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5385]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kempeleen vanha kirkko 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Museovirasto on ehdottanut Kempeleen vanhaa kirkkoa Unescon maailmanperintökohteeksi. Google "Kempeleen vanha kirkko" 1730 osumaa. YSA:ssa on mm. Haukiputaan kirkko (sama kirkkomaalari kuin Kempeleessä) ja Keuruun vanha kirkko. Ei voi laittaa pelkästään "Kempeleen kirkko", koska kirkkoja on Kempeleessä kaksi vierekkäin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Muutamia artikkeleita 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [Kempeleen vanha kirkko](http://finto.fi/yse/fi/page/Y505385)

**Comment by mariaforsen** [comment]
Sv. Kempele gamla kyrka ET gamla kyrkan i Kempele
