### ISSUE TITLE
kulttuurinen omiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5388]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kulttuurinen omiminen 

#### Vaihtoehtoiset termit ja ilmaisut   

appropriaatio, kulttuurinen appropriaatio 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Esimerkiksi saamelaiskulttuurin ulkoisten tuntomerkkien, kuten noitarumpujen ja lapinpukujen, käyttö Suomi-eksotiikan esille tuomisessa ilman, että käyttäjä tuntee saamelaisuutta ollenkaan tai pystyy tuomana esille saamelaisuuden koko kulttuurisen kuvan ihmisoikeusongelmineen. Intiaanit, saamelaiset yms. 

#### Perustelut ehdotukselle   

Olen asiasanoittanut tästä aiheesta puolen tusinaa artikkelia. Aihe tuli ajankohtaiseksi mm. videoteos Grind'in myötä. Artikkeleita löytyy hakemalla Aleksista hakusanoilla kulttuurinen omiminen, appropriaatio, lapinpuvut. Vaikea asiasanoittaa ilman tätä termiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Kannuksen kadonneet kaiut (Synteesi 2016: 4) (ks. myös yllä) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [kulttuurinen omiminen](http://finto.fi/yse/fi/page/Y505388)

**Comment by jtuohini** [comment]
"Tarkoitusta täsmentävä selite" -otsikon alla olevan mukaisesti tässä vaikuttaisi olevan kysymys siitä, jonka jo olemassa oleva YSA-termi **folklorismi** [http://www.yso.fi/onto/ysa/Y95173] kattaa; ks. esim. Tieteen termipankki http://tieteentermipankki.fi/wiki/Folkloristiikka:folklorismi.

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by krinay** [comment]
Folklorismi ei ole aivan sama asia kuin kulttuurinen appropriaatio. Folklorismilla tarkoitetaan siis perinteen ilmiöiden hyödyntämistä kaupallisesti, viihteessä tms. usein oman kulttuurin sisällä, esimerkiksi turisteille järjestetyt kansantanssiesitykset.

Kulttuurisella appropriaatiolla taas viitatataan toisen kulttuurin elementtien käyttämiseen erilaisissa tarkoituksissa. Kyse on usein valtasuhteista. Ks. esim. 
http://musiikinsuunta.fi/2017/01/omimista-lainaamista-hyvaksikayttoa/

Aiheesta käydään keskustelua ainakin kultturien tutkimuksen / kulttuurintutkimuksen ja kirjallisuudentutkimuksen piirissä, mutta en ole varma mikä termi olisi pitkäikäisin.

Jos ehdin, yritän kysellä asiantuntevammilta ihmisiltä ennen tiistaita.

**Comment by mariaforsen** [comment]
Sv. kulturell appropriering
