### ISSUE TITLE
akryylimaalaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5390]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[akryylimaalaus](http://www.yso.fi/onto/ysa/Y100619) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

HUOM.! Tämää kommentti koskee myös muita aiempia YSO:maalaustaide-käsitteen alakäsitteitä (akvarellimaalaus, ikonimaalaus jne. ks. http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp8883).

Näiden alakäsitteiden yläkäsite on muuttunut, mutta uri säilynyt samana. Eikö käsitteet olisi pitänyt deprekoida, kun yläkäsitteen muuttumisen myötä myös merkitys lienee muuttunut? 

#### Perustelut ehdotukselle   

Yläkäsitteen muuttumisen myötä myös merkitys lienee muuttunut. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
_Maalaustaide_ on ollut aikaisemmin hierarkiassa ilmiöt (YK pysyvä), joten tässä ei mielestäni ole kyse siitä että käsite olisi muuttunut, paikkaa on vain tarkistettu. _Maalaustaide_ on siirtynyt _olio_-kategoriaan ja toiminnalliset alakäsitteet (samoin kuin ilmiöt) _tapahtumat ja toiminta_ -kategoriaan.
