### ISSUE TITLE
akvatinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5391]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[akvatinta](http://www.yso.fi/onto/ysa/Y106795) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

HUOM.! Tämä kommentti koskee myös muita aiempia YSO:grafiikka-käsitteen alakäsitteitä (etsaus, kuparipiirros jne. ks.http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp2698). 

Näiden alakäsitteiden yläkäsite on muuttunut, mutta uri säilynyt samana. Eikö käsitteet olisi pitänyt deprekoida, kun yläkäsitteen muuttumisen myötä myös merkitys lienee muuttunut? 

#### Perustelut ehdotukselle   

Yläkäsitteen muuttumisen myötä myös merkitys lienee muuttunut. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
YSAssahan näillä on ollut monihierarkia. YSOssa grafiikka on kuvataiteen alakäsite taiteet-hierarkiassa, syväpaino puolestaan menetelmät-hierarkiassa, molemmat ovat yhteiskunnallisia objekteja. Onko se sitten merkityksen muutos, jos painotetaan enemmän sitä että akvatinta on menetelmä, kuin sitä että ko. menetelmän hyödyntäminen on kuvataiteen ala...
