### ISSUE TITLE
valtioliput

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5394]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valtioliput 

#### Ehdotettu yläkäsite YSOssa (LT)   

[liput](http://www.yso.fi/onto/yso/p2012) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Perustelut ehdotukselle   

MAO-työryhmän mielestä käsite olisi hyvä lisätä YSOon. Merkitys on eri kuin käsitteellä 'kansallisliput'. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Museoiden esine- ja kuva-aineistot. 

**Ehdottajan nimi:** Päivi Kouki 
**Ehdottajan organisaatio:** Sanastokeskus TSK 
**Ehdottajan sähköpostiosoite:** paivi.kouki@tsk.fi **Termiehdotus Fintossa:** [valtioliput](http://finto.fi/yse/fi/page/Y505394)

**Comment by mariaforsen** [comment]
Sv. statsflaggor
