### ISSUE TITLE
värit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5395]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[värit](http://www.yso.fi/onto/ysa/Y100352) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sulkutarkenteen "(aine)" pitäisi poistaa/vaihtaa (http://www.yso.fi/onto/yso/p2284). 

#### Perustelut ehdotukselle   

Alakäsitteistä vain "indigo" on aine, joten sulkutarkenne on hämmentävä. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Ehdotus: poistetaan yksiköllinen väri-käsite jolloin sulkutarkennetta ei tarvita. Jäisi vain värit KT väri. Otetaan uutena vedenväri.
