### ISSUE TITLE
taiteen perusopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5398]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taiteen perusopetus](http://www.yso.fi/onto/ysa/Y155112) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan, että yläkäsitteeksi vaihdetaan 'perusopetuksen' sijaan 'opetus'. 

#### Perustelut ehdotukselle   

Perusopetusta annetaan peruskouluissa, kansanopistoissa, aikuislukioissa tai muissa oppilaitoksissa. Taiteen perusopetusta taas ei järjestetä peruskouluissa, eikä se johda tutkintoon. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
YSAssa on ollutkin näin, muutettu FinnONTOssa.
