### ISSUE TITLE
lukulaitteet (skannerit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5399]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lukulaitteet (skannerit)](http://www.yso.fi/onto/ysa/Y103211) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisi tarkistaa, onko yläkäsite 'skannerit' todella laajempi käsite kuin 'lukulaitteet (skannerit)' vai onko kyseessä sama käsite. 

#### Perustelut ehdotukselle   

Skannereilla ei ole muita alakäsitteitä, joten jää epäselväksi, onko todella olemassa sellaisia skannereita, jotka eivät ole lukulaitteita. 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Olisiko parempi muuttaa tämän käytettäväksi termiksi _kuvanlukijat_, mielestäni sitä jaottelua on tässä haettu.

**Comment by mariaforsen** [comment]
Ks. TEPA: skanneri: 
laite, joka lukee kohdetta osio kerrallaan ja luo siitä digitaalisen kuvan tai kolmiulotteisen mallin tai tunnistaa koodin, huomautus: Skanneri-termiä käytetään usein myös silloin, kun tarkoitetaan kuvanlukijaa.
KS: Kuvanlukija: laite jolla muunnetaan liikkumattomia kuvia sähkömagneettisiksi merkeiksi. 
Ruotsiksi skanner ja bildläsare ovat aika lailla synonymeja.

**Comment by mirmaid** [comment]
Mun käsitykseni on siis, että olisi haluttu termi joka tarkoittaa nimenomaan laitetta, jolla muodostetaan digitaalinen kuva esim. paperisesta, erotukseksi viivakoodin-, mikrosirun- jne. lukijoista. Mutta ehkä tämä laitearsenaali on nykyään niin moninainen ettei erottelu onnistu.

**Comment by mirmaid** [comment]
Yhdistetään kaikki skannerit?

**Comment by YSA-kokous** [comment]
skannerit
