### ISSUE TITLE
kiinteistönkauppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5400]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kiinteistönkauppa](http://www.yso.fi/onto/ysa/Y96154) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan ensisijaiseksi termiksi termiä 'kiinteistökauppa'. 

#### Perustelut ehdotukselle   

Kiinteistö- ja rakentamisalan sanastossa suositetaan muotoa 'kiinteistökauppa'. http://www.tsk.fi/tsk/fi/kiinteist%C3%B6_ja_rakentamisalan_keskeinen_sanasto-1013.html 

#### Ehdottaja   

Päivi Kouki 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

paivi.kouki@tsk.fi

**Comment by mirmaid** [comment]
Käytetty muoto vaihtelee: http://www.finlex.fi/fi/laki/ajantasa/1995/19950540, https://fi.wikipedia.org/wiki/Kiinteist%C3%B6n_kauppa, http://tieteentermipankki.fi/wiki/Oikeustiede:kiinteist%C3%B6nkauppa (Tieteen termipankki ei ilmeisesti ole kokonaisuudessaan TEPAssa).

_Kiinteistökauppa_-muoto tuo eniten viitteitä Googlella.

**Comment by YSA-kokous** [comment]
kiinteistökauppa
