### ISSUE TITLE
saamelaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5401]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[saamelaiset](http://www.yso.fi/onto/ysa/Y98679) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korvattu termi "lappalaiset" voitaisiin poistaa 

#### Perustelut ehdotukselle   

Termi on loukkaava 

#### Ehdottaja   

Matias Frosterus 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

matias.frosterus@helsinki.fi

**Comment by henriyli** [comment]
https://fi.wikipedia.org/wiki/Saamelaiset#Saamelaiset_ja_lappalaiset
http://tieteentermipankki.fi/wiki/Oikeustiede:saamelainen

**Comment by jtuohini** [comment]
Ja jos joku etsii termillä _lappalaiset_ eikä löydäkään mitään? Ymmärrän, että "preflabelien" valinnassa pyritään olemaan mahdollisimman neutraaleja, mutta KT-muotojen pitäisi kattaa kaikki mahdolliset käsitteet ja termit, joilla joku todennäköisesti hakisi.

**Comment by henriyli** [comment]
Puuttuuhan meiltä monia muitakin vähemmistöjä kuvaavia termiä, joita joku saattaisi kaivata esim. _mannet_ tai se n-sana. Pitäisikö nekin lisätä tasapuolisuuden nimissä? Vaikeaa toki on sanoa, milloin tietty termi on tarpeeksi halventava poistettavaksi.

**Comment by jtuohini** [comment]
Poistaminen ja lisääminen ovat kaksi aika erilaista toimintapaa sanastotyössä, edellinen sanaston heikentämistä, toinen vahvistamista. Tällä hetkellä _lappalaiset_ on jo vain viittausmuotona (siis "älä käytä" -tyyppisenä), _mannet_ taas ei tähänkään asti ole ollut mukana enkä ole ehdottamassa sen lisäämistä (koska ei ole ollut neutraali KIRJAKIELINEN ilmaisu aiemminkaan toisin kuin _lappalaiset_). Ja rehellisesti sanottuna olen yllättynyt, että _neekerit_-KT-muotoa ei Ysassa ole, kun se kuitenkin on muinoin ollut ihan normaalia sanastoa sanomalehtiä myöten ja ilman arvovarausta (toisin kuin vaikkapa "nekrut", joka PUHEKIELISENÄ ja jo lähtökohtaisesti loukkaavaksi tarkoitettuna olisi huono KT-muodoksi). Eikö sanaston tarkoitus ole koota myös vanhentuneet termit haun piiriin, jos joskus vaikka digitoitua vanhempaa aineistoa ajetaan sanaston läpi ja pyritään annotoimaan sitä?

Jos sanastoa pyritään rakentamaan poliittisella korrektiudella vailla joustavuutta, emme voisi lopulta käyttää mistään ihmisryhmästä mitään termiä, koska aina joku kokee jonkin termin loukkaavaksi. Kunhan "preflabelit" ovat asialliset, ollaan pitkällä; "altlabelien" suhteen olisi hyvä muistaa hakumahdollisuuksien moninaisuus.

**Comment by krinay** [comment]
Kannatan yleensä poliittista korrektiutta, mutta tässä tapauksessa minusta kyse olisi hätävarjelun liiottelusta. 

Kuten edellä on todettu, on sanaa lappalaiset käytetty pitkään täysin neutraalisti. Yksi edelleen keskeisimmistä suomalaisista saamalaisten ja saamelaiskulttuurin tutkimuksisia T. I. Itkosen _Suomen lappalaiset_. Kielitoimiston sankirja sanoo näin "lappalainen nyk. tavallisemmin: saamelainen". 

Luulen, että vielä voi olla tiedonhakijoita, jotka etsivät termillä lappalaiset. Tai termillä mustalaiset. Manne-sanalla ei varmaan kukaan etsi. Tuskin neekerit-sanallakaan, sen halventava merkitys on jo niin leimallinen ja yleisesti tunnettu. Mutta en vastusta sitäkään ohjausterminä.

**Comment by YSA-kokous** [comment]
Ei muutosta.
