### ISSUE TITLE
julkiset menot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5402]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[julkiset menot](http://www.yso.fi/onto/ysa/Y101973) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nyt ohjausterminä olevat "valtion menot" ja "kunnan menot" erillisiksi käsitteiksi. 

#### Perustelut ehdotukselle   

YSAssa ja YSOssa on aiemmin ollut erillisenä käsitteinä "menot -- valtio" ja "menot -- kunnat". Nämä päätettiin kuitenkin poistaa ketjumuotoisten termien poiston yhteydessä. JUHO-ontologiassa on kuitenkin ollut ennestään käsitteet "valtion menot" ja "kuntien menot", joista on ollut linkitys näihin YSOn ketjumuotoisiin käsitteisiin. JUHOssa halutaan säilyttää kyseiset käsitteet.

Olisiko käsitteet mahdollista herättää henkiin fraasimuotoisina YSAssa ja YSOssa? 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by jtuohini** [comment]
Kuinka paljon erilaisia julkisten menojen täsmällisempiä alakäsitteitä tarvittaisiin (_kuvernementin menot_, _läänin menot_, _maakunnan menot_, _osavaltion menot_, _piirikunnan menot_ jne.)? Vai luotaisiinko sitä mukaa, kun tarve ilmenee? Ajatellen sitä, että nyt voidaan kahdella jo olemassa olevalla termillä ilmaista nämä samat – vai voidaanko?

**Comment by AuHo22** [comment]
...kuntayhtymien menot, sairaanhoitopiirien menot...YSAssa olemassa ja sosiaalimenot ja terveydenhuoltomenot

**Comment by YSA-kokous** [comment]
valtion menot, kuntien menot
