### ISSUE TITLE
valtion tulot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5403]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valtion tulot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tulot](http://www.yso.fi/onto/yso/p941) 

#### Perustelut ehdotukselle   

YSAssa ja YSOssa on aiemmin ollut "tulot -- valtio". Tämä päätettiin kuitenkin poistaa ketjumuotoisten termien poiston yhteydessä. JUHO-ontologiassa on kuitenkin ollut ennestään käsite "valtion tulot", josta on ollut linkitys tähän YSOn ketjumuotoiseen käsitteeseen. JUHOssa halutaan säilyttää kyseinen käsite.

Olisiko käsite mahdollista herättää henkiin fraasimuotoisina YSAssa ja YSOssa? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Taxes and tax-like payments / Statistics Finland. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [valtion tulot](http://finto.fi/yse/fi/page/Y505403)

**Comment by mirmaid** [comment]
12 viitettä Melindassa.

**Comment by LeKorsu** [comment]
Ei mitään erityistä vastaansanomista tällle eikä "kuntien tulot" -käsitteelle, jos nämä koetaan tärkeiksi. Kunhan ei sitten ole vain alku sille, että aletaan tarjota  "xxxx tulot" ties mistä fraaseista.

**Comment by mariaforsen** [comment]
Sv. statens inkomster ET statliga inkomster ET statsinkomster
