### ISSUE TITLE
kuntien tulot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5404]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuntien tulot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tulot](http://www.yso.fi/onto/yso/p941) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

YSAssa ja YSOssa on aiemmin ollut "tulot -- kunnat". Tämä päätettiin kuitenkin poistaa ketjumuotoisten termien poiston yhteydessä. JUHO-ontologiassa on kuitenkin ollut ennestään käsite "kuntien tulot", josta on ollut linkitys tähän YSOn ketjumuotoiseen käsitteeseen. JUHOssa halutaan säilyttää kyseinen käsite.

Olisiko käsite mahdollista herättää henkiin fraasimuotoisina YSAssa ja YSOssa? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kohti parasta kuntatalouden kehitystä? : kunta- ja palvelurakennusuudistus talouden näkökulmasta / Olavi Kallio, Pentti Meklin, Jari Tammi & Jarmo Vakkuri. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [kuntien tulot](http://finto.fi/yse/fi/page/Y505404)

**Comment by mirmaid** [comment]
11 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. kommunernas inkomster  ET kommuninkomster ET kommuners inkomster ET kommunala inkomster
