### ISSUE TITLE
sarjat (musiikki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5405]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sarjat (musiikki)](http://www.yso.fi/onto/ysa/Y206548) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon sarjat (sävellykset) 

#### Perustelut ehdotukselle   

MUSAssa tehty näin. 

#### Ehdottaja   

Luumu 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
Käsite on YSOssa sillattu kahteen LCSH-käsitteeseen
**Suite (Music)**  [= works about the suite] ja 
**Suites** [=collections of suites]

MUSAssa siltaus vain käsitteeseen **Suites**  @ksornova @jtuohini

**Comment by OutiHintikka** [comment]
Entä sarjallisuus? Ilmiönä ilmenee myös kuvataiteissa.

**Comment by asormune** [comment]
MUSAssa on termi "sarjallinen musiikki" (ohjausterminä sarjallisuus), joka on (modernin) musiikin sävellysmenetelmä. Ei liity termiin "sarjat", joka viittaa sävellystyyppiin/sävellysmuotoon.

**Comment by YSA-kokous** [comment]
sarjat (sävellykset)

**Comment by mariaforsen** [comment]
Sv. sviter (kompositioner)

**Comment by mirmaid** [comment]
Tarvitseeko tarkenteen SLM:ssä, kun sanastoon otettiin myös laulusarjat?

**Comment by MUUSA-kokous** [comment]
Tällä hetkellä ei ole tarvetta tarkenteelle SLM:ssä.
