### ISSUE TITLE
yhteisöasuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5406]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yhteisöasuminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://wiki.tut.fi/pub/Monikko/WebHome/Monikko_Loppuraportti_web.pdf, http://urn.fi/URN:ISBN:978-952-11-4710-4 

#### Tarkoitusta täsmentävä selite   

Yhteisöasumisella tarkoitetaan tavoitteellisesti ja järjestäytyneesti yhteisöllistä asumisen tapaa, jolla on seuraavat
ominaispiirteet: 1. Yhteistoiminta: Osa asumiseen liittyvästä ja vapaa-ajan toiminnasta on järjestetty yhteisesti naapureiden kanssa. 2. Yhteistilat: Asukkailla on käytössään yhteisesti hallittua ulko- ja/tai sisätilaa. 3. Yhteisöllinen organisaatio: Pyrkimys yhteisöllisyyteen on sisäänrakennettu fyysiseen (yhteistilat) ja/tai organisatoriseen (yhteistoiminta ja siihen liittyvät vastuut) rakenteeseen, ja luo siten asukkaille tiettyjä velvoitteita tai vastuita. (Lähde: https://wiki.tut.fi/pub/Monikko/WebHome/Monikko_Loppuraportti_web.pdf) 

#### Perustelut ehdotukselle   

Termi on tullut koko ajan enemmän esille ikääntyneiden asumiseen liittyvissä julkaisuissa yhtenä asumismuotona. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

**Ehdottajan nimi:** Leena Väyrynen 
**Ehdottajan sähköpostiosoite:** leena.vayrynen@karelia.fi 
**Ehdottajan organisaatio:** Karelia Ammattikorkeakoulun kirjasto **Termiehdotus Fintossa:** [yhteisöasuminen](http://finto.fi/yse/fi/page/Y505406)

**Comment by henriyli** [comment]
Löytyy jo sanastosta http://www.yso.fi/onto/ysa/Y100401.
