### ISSUE TITLE
neorealismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5407]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[neorealismi](http://www.yso.fi/onto/ysa/Y103656) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö jakaa/tarkentaa? Samoin uusrealismi. 

#### Perustelut ehdotukselle   

YSAssa taidetermeinä, mutta käytetty myös politiikka-merkityksessä. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Realismi jaettu siis (filosofia), (politiikka) ja (taide).

Uusrealismi (politiikka) KÄ neorealismi (politiikka)?

**Comment by YSA-kokous** [comment]
neorealismi (taide)
neorealismi (politiikka) KT uusrealismi (politiikka)

**Comment by mirmaid** [comment]
Tarvitaan varmaan määritelmät neorealismille ja uusrealismille taiteessa:
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:neorealismi
https://en.wikipedia.org/wiki/Italian_neorealism
https://en.wikipedia.org/wiki/Neorealism_(art)

https://fi.wikipedia.org/wiki/Uusi_realismi

**Comment by tpalonen** [comment]
HAASTEITA
Neorealismia on käytetty Melindassa varsin kirjavasti, esim. useampi viittaus venäläiseen kaunokirjallisuuteen, Kauko Lehtisen kuvataide. Wikipedian Neorealism (art) -artikkeli on varsin epämääräinen eikä anna kunnollisia eväitä järkevään käsitteiden rajaamiseen. Taiteen pikkujättiläinen (WSOY 1991) tuntee myös käsitteen Néo-Réalisme, joka on Ranskassa 1930-luvulla vaikuttanut kuvataiteen suuntaus (ei ilmeisesti mitään tekemistä Nouveau réalisme -suuntauksen kanssa; vaikuttaa perifeeriseltä suuntaukselta ja voitaneen sivuuttaa tässä kohtaa.) Lisäksi fotorealismin ja pop taiteen sisällyttäminen uusrealismin alakäsitteiksi vaikuttaa mutkien suoristamiselta.

EHDOTUS
- Ehdotus neorealismi (taide) -käsitteen määritelmäksi.
"Varsinkin Italiassa elokuvataiteessa ja kirjallisuudessa vaikuttanut suuntaus, jossa yhteiskunnallisia aiheita pyritään käsittelemään realistisesti."
Jos halutaan rajata käsite tiukemmin niin tuon "varsinkin" sanan voi ottaa pois.
- Ehdotus uusrealismi (taide) -käsitteen määritelmäksi.
"1950- ja 1960-lukujen taitteessa syntynyt taidesuuntaus, jossa hyödynnetään realistista kuvastoa, mainoskuvastoa, arkipäiväisiä esineitä tai vastaavia todellisia tai todentuntuisia elementtejä."

HUOM! Muuttaisin fotorealismi LT uusrealismi ja poptaide LT uusrealismi RT-suhteiksi. Taidesuuntauksien väliset suhteet ovat harvoin näin yksioikoisia. 
- Vrt. Wikipedian Nouveaux réalisme -artikkeli: "Contemporary of American pop art, and often conceived as its transposition in France, new realism was, along with Fluxus and other groups, one of the numerous tendencies of the avant-garde in the 1960s." Jos uusrealismi on ranskalainen versio Yhdysvalloissa syntyneestä pop artista niin nykyinen LT ei vaikuta parhaalta ratkaisulta. 
- Taiteen pikkujättiläinen: "uusrealisteihin on luettu myös joukko 50- ja 60-luvun eurooppalaisia, lähinnä ranskalaisia, kuvanveistäjiä ja maalareita, jotka dadahenkisesti liittivät teoksiinsa monenlaisia eri materiaaleja sekä esineitä ja rojua." Vrt. Wikipedian Photorealism-artikkeli "Photorealism is a genre of art that encompasses painting, drawing and other graphic media, in which an artist studies a photograph and then attempts to reproduce the image as realistically as possible in another medium." Eri lähtökohdat, eri ilmaisutapa. LT ei tässäkään liene paras ratkaisu.
