### ISSUE TITLE
nesteytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5408]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nesteytys](http://www.yso.fi/onto/ysa/Y97640) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsee tarkenteen, sekoitetaan nykymuodossa nestehoitoon tai käytetään muuten muussa kuin kemianteollisuuden merkityksessä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
nesteytyshoito, nesteytys (hoito) KÄ _nestehoito_, entä urheilijoiden ym. "nestetankkaus"

**Comment by mirmaid** [comment]
Kemian yhteydessä tilanne nyt vähän hankala: _Modellering och vidareutveckling av kondenserande luft-vatten värmeväxlare_, asiasanana kondensation, suom. nesteytys - suomeksi tässä pitäisi olla ennemmin _tiivistyminen_. Toisaalta _Dynamics and excitations of Bose-Einstein condensates_, pitäisi kai olla _kondensaatioreaktio_ (ei YSAssa).

**Comment by mariaforsen** [comment]
Nesteytys=kondensation (kemiamerkityksessä), joten on kyllä tärkeää että laitetaan tarkenne.

**Comment by mirmaid** [comment]
Varmaan pitää tiivistyminenkin jakaa/tarkentaa - ruots. kondensation siis voi olla suomeksi tiivistyminen tai nesteytys...ja betoni ei varmaan tiivisty ihan samalla tavalla kuin vesi...

**Comment by OutiHintikka** [comment]
Entä nesteytys (hoito),  nesteytys (urheilu) ?

**Comment by mariaforsen** [comment]
Voisiko juominen, nestetasapaino yms. riittää? Mot-sanastot, TEPA jne. eivät tunne n.k. nestetankkaus-merkityksessä.. Sellaista "tankkausta" ei käsitellä tällä tavalla ruotsiksi.

**Comment by mariaforsen** [comment]
KS: Tiivistyä: tulla tiivii(mmä)ksi (=komprimering)
Erik. höyrystä t. kaasusta: nesteytyä. (=kondensering=>nesteytys)

**Comment by YSA-kokous** [comment]
nesteytyshoito, nesteytys (hoito) KÄ nestehoito
nesteytys (nestetankkaus), nestetankkaus KÄ nestetasapaino

Sen jälkeen tutkitaan ja tarkennetaan nesteytys ja tiivistyminen kemian ja fysiikan alalla. (erillinen issue)

**Comment by mirmaid** [comment]
Onkohan kuitenkaan hyvä tehdä viittauksia _nesteytys (nestetankkaus), nestetankkaus KÄ nestetasapaino_? Johtaa Melindassa siihen että haku "nesteytys" tuo myös kaikki nestetasapaino-viitteet, ja toisaalta myös ohjaustermi _nestetankkaus_ voi näyttää vähän erikoiselta _nestetasapaino_-termitietueessa.

**Comment by YSA-kokous** [comment]
Ei ohjausta nesteytys (nestetankkaus), nestetankkaus KÄ nestetasapaino
