### ISSUE TITLE
rajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5409]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rajat](http://www.yso.fi/onto/ysa/Y98453) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

https://github.com/NatLibFi/Finto-data/issues/525 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
En näe pakottavaa tarvetta jakaa tätä. Rajanveto (ehheh) eri merkitysten välille on hankalaa, sillä käyttötarkoitukset ulottuvat hyvin konkreettisista hyvin abstrakteihin sekä kaikkeen siltä väliltä.

**Comment by tpalonen** [comment]
Kannatan jakamista. Raja alueellisena ja psykologisena ja sosiaalisena ei ole yksi käsite. Aiemmassa issuessa alueelliselle rajalle esitetty seuraavia käytettäviä termejä: _rajat (alueet), rajat (paikat)_. Yksi voisi olla _rajat (maantiede)_. Muulloin kaiketi enimmäkseen kyse sosiaalisista ja/tai psykologisista rajoista (esim. _"Rajat kuntoon! : puolensa pitämisen ja omasta hyvinvoinnista huolehtimisen taito"_ tai _"Rajat : taito hallita omaa elämää ja kyky sanoa kyllä ja ei"_). Sosiaalinen ja psykologinen ovat varmaankin yhdistettävissä yhdeksi käsitteeksi. Näyttäytyvät ainakin minulle jatkumona. Käytettävä termi voisi olla esim. _rajat (psykologia)_ ja ohjaustermeinä _psyykkiset rajat, sosiaaliset rajat, rajat (sosiologia)_.

Aiheeseen liittyvää musiikkia levyltä _Play That Beat Mr. Raja_:
https://www.youtube.com/watch?v=mPo9Cztrtfo

**Comment by YSO-kokous** [comment]
Ei muutoksia rajat-käsitteeseen. Rajaseudut ja raja-alueet -käsitteiden osalta pohditaan vielä tarkentavia määritelmiä / sulkutarkenteita.

**Comment by tpalonen** [comment]
Tarkentaville määritelmille ei löytynyt lähdettä.
