### ISSUE TITLE
ravitsemusterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5410]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ravitsemusterapia](http://www.yso.fi/onto/ysa/Y98551) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmä hyvin suppea. Pitäisikö ottaa erikseen ko. merkityksessä ravitsemushoito? 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Määritelmä siis: _Tarkoittaa erikoisruokavalioon perustuvaa (sairaala)hoitoa_

Tai jos tuosta vaan poistaisi tuon (sairaala)? Tämä määritelmä tuntuu kyllä paremmalta: _Ravitsemusterapia on sairauksien hoitoa ja ehkäisyä sekä terveyden edistämistä ravitsemuksen keinoin._ http://www.pkssk.fi/ravitsemusterapia

**Comment by satuniininen** [comment]
Määritelmässä pitäisi jotenkin tuoda esiin myös ero _ravintoterapiaan_.

**Comment by mariaforsen** [comment]
MOT: ravitsemusterapia lääk. = ravitsemushoito. Ainakin ruotsin osalta tulee ongelmia jos näiden lisäksi otetaan vielä lisää päätermejä. Meshissä on tosin ravitsemushoito pääterminä ja ravitsemusterapia korvattuna. Muissa sanastoissa/sanakirjoissa ei ole ravintoterapiaa.

**Comment by YSA-kokous** [comment]
Muokataan määritelmää, tutkitaan ravintoterapia.

**Comment by mariaforsen** [comment]
Ravintoterapia on käytetty 11 kertaa Melindassa. Termiä ravitsemusterapia on näköjään käytetty myös sellaisiin aineistoihin, jotka käsittelevät vaihtoehtolääkintää yms. 
MESH: 
diet therapy/ruokavaliohoito/dietterapi
nutrition therapy/ravitsemushoito/näringsterapi

Myös SAOssa dietterapi (ei nyt Allärsissa)

**Comment by mariaforsen** [comment]
Se lienee parasta, raja lääketieteellisen ja vaihtoehtohoidon välillä ei ole myöskään aina selkeä, varsinkaan näissä aineistoissa, helposti voi mennä sitten "väärälle puolelle". Jos tietää ja haluaa painottaa että kyse on vaihtoehtohoidosta, sitä voi tehdä lisäämällä termi luontaishoito, vaihtoehtolääkintä tms. Näissä käsitteissä lienee olennaisinta se että on kysymys ravinnon/ruokavalion käytöstä hoitona (ei se että onko lääketieteellisesti hyväksytty/suositeltu vai ei). Sellaista jakoa ei ainakaan tehdä ruotsiksi (vaan siitä mainitaan tarvittaessa erikseen että onko tieteellisesti tutkittu ja hyväksytty vai ei, jne.)

**Comment by satuniininen** [comment]
Yhdistäminen olisi hyvä ratkaisu siinä mielessä, että ravinnosta kirjoitetaan paljon, eikä aineiston perusteella ole aina ongelmatonta arvioida, kuinka legitiimi sen tieteellinen pohja on. Selkeästi uskomuksellisen aineiston näkökulma toki selviää muista käytetyistä asiasananoista.

**Comment by YSA-kokous** [comment]
ravitsemushoito KT ravitsemusterapia, ravintoterapia
