### ISSUE TITLE
resoluutio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5411]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[resoluutio](http://www.yso.fi/onto/ysa/Y152673) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

Käytetty myös kemian yhteydessä. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Resoluutio

Riittäisiköhän _resoluutio (kuvatekniikka)_ ja _resoluutio (kemia)_?

**Comment by satuniininen** [comment]
Melindassa YSA-asiasanana 24 kertaa, joista
20 kuvatekniikkaa
3 kemiaa
1 mysteeri (_Musiikillisen harjaantumisen ja musiikillisten elementtien erottelukyvyn yhteys englannin kielen foneettiseen erottelukykyyn 7.-luokkalaisilla suomenkielisillä nuorilla_)

**Comment by mariaforsen** [comment]
Eri vastineita ruotsiksi. Resolution (kemi) hyvin harvinainen https://www.ifm.liu.se/edu/coursescms/NKEA07/lectures/Fo-4-Stereokemi.pdf

**Comment by YSA-kokous** [comment]
resoluutio (kuvatekniikka) ja resoluutio (kemia)

**Comment by mariaforsen** [comment]
Sv.
-upplösning (optisk återgivning)
-resolution (kemi)
