### ISSUE TITLE
verkkojuttelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5412]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkojuttelu](http://www.yso.fi/onto/ysa/Y111855) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko parempaa termiä? 

#### Perustelut ehdotukselle   

Kuulostaa vanhahtavalta? 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by tpalonen** [comment]
Chattailu suositeltavaksi termiksi? Olisi vähän modernimpi. Wikipediassa esiintyy muodossa "chatti" ja "chattaily". https://fi.wikipedia.org/wiki/Chatti

**Comment by ilona-x** [comment]
http://www.tsk.fi/tsk/termitalkoot/hakemistot-267.html?page=get_id&id=ID0056&vocabulary_code=TSKTT

verkkojuttelu; nettijuttelu
mieluummin kuin: chattaus; chattailu

Lähde: Tietotekniikan termitalkoot, 2017-06-21

**Comment by YSA-kokous** [comment]
Ei muutosta.
