### ISSUE TITLE
systematiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5414]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[systematiikka](http://www.yso.fi/onto/ysa/Y104464) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

jaetaan 
systematiikka(biologia), yläkäsite biologia/biotieteet
systematiikka(?) 

#### Perustelut ehdotukselle   

Tieteen termipankin määritelmä: biologian tieteen ala, joka tutkii eliöiden sukulaisuussuhteita ja evolutiivista kehityshistoriaa 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
Hyvin vähän käytetty muuten kuin biologian alalla (alle 5 viitettä sadasta ensimmäisestä Melindassa). Myös taksonomia-termiä on satunnaisesti käytetty biologian ulkopuolella.

**Comment by mariaforsen** [comment]
Termi systematik (=systematiskt tillvägagångssätt) ei sinänsä ole pelkästään biologinen, mutta toki käytetty eniten siinä merkityksessä.

**Comment by mirmaid** [comment]
Biotieteiden laitoksen kommentti:
Taksonomia ja systematiikka eivät ole synonyymeja. Taksonomia tarkoittaa "perinteistä" tapaa tehdä eliöiden luokittelututkimusta eli se sisältää lajien, sukujen, heimojen jne. (eli taksonien) kuvaamisen ja nimeämisen ja esim. lajien sijoittamisen sukuihin yhteisten ominaisuuksien perusteella. Taksonomian voi sanoa perustuvan "silmillä nähtäviin ominaisuuksiin". Moderni systematiikka menee syvemmälle eli ei hyväksy kaikkia yhteisiä ominaisuuksia todisteeksi esim. lajien läheisestä sukulaisuudesta vaan selvittelee lajien sukulaisuuksia lähinnä DNA-aineistoon perustuen, koska DNA:ssa on usein luotettavampia signaaleja evoluutiosta kuin vaikkapa eläinten tai kasvien rakenteissa. Minusta taksonomia pitäisi käsitteenä selvästi erottaa systematiikasta. 

Biologian sanakirjassa taksonomia määritellään näin: "eliöiden tieteellinen luokittelu; biologian ala, joka sisältää sekä nykyisten että sukupuuttoon kuolleiden elöiden kuvauksen, nimeämisen ja luokittelun (ryhmittelyn)."

Systematiikka puolestaan määritellään näin: "eliöiden järjestely; tutkii eliöiden monimuotoisuutta ja välisiä suhteita, erityisesti niiltä osin kuin sillä on merkitystä taksonien fylogeneettisten (ks. fylogenia) suhteiden kannalta. Ero taksonomia-käsitteeseen on vähäinen, eräiden mielestä termit ovat synonyymeja". KOMMENTTI: Nämä "eräät" eivät ymmärrä mistä on kysymys!

**Comment by mirmaid** [comment]
Nykyiset ryhmät 15 ja 56. Jos tarkentaminen on tarpeen, ehdotan että lisätään tarkenne _(biologia)_ mutta ei jaeta, YSAsta löytyy kuitenkin lisäksi _luokitus, luokitukset, järjestelmät_ ym.

**Comment by jarmosaarikko** [comment]
Systemaattisen **teologian** menetelmää kutsutaan systemaattiseksi metodiksi. Se on luonteeltaan käsiteanalyysia, joka pyrkii paljastamaan kohteensa loogisen rakenteen, loogiset edellytykset sekä epäjohdonmukaisuudet.  -- ei liene vaaraa sekoittua "systematiikka" käsitteeseen?

**Comment by mariaforsen** [comment]
Ainakaan ruotsiksi ei ole sekoittamisen vaaraa systemaattisen teologian kanssa (ja se on erikseen sanastossa)

**Comment by YSA-kokous** [comment]
systematiikka (biologia)
