### ISSUE TITLE
systematiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5415]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[systematiikka](http://www.yso.fi/onto/ysa/Y104464) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan YSAan termi taksonomia, joka nyt korvattu systematiikalla, joka muutetaan assosiatiiviseksi. Yläkäsite biologia/biotieteet 

#### Perustelut ehdotukselle   

Tieteen termipankin määritelmä: biologian tieteenala, joka tutkii eliöiden kuvaamista, nimeämistä ja luokittelua
http://tieteentermipankki.fi/wiki/Biologia:taksonomia 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
AFOssa, paljon käytetty kuvailussa (Melinda 518). Toisaalta myös _systematiikka_-termiä on käytetty samassa merkityksessä (Melinda 2315). 

Wikipedia: In 1970 Michener et al. defined "systematic biology" and "taxonomy" (terms that are often confused and used interchangeably) in relationship to one another as follows:

 Systematic biology (hereafter called simply systematics) is the field that (a) provides scientific names for organisms, (b) describes them, (c) preserves collections of them, (d) provides classifications for the organisms, keys for their identification, and data on their distributions, (e) investigates their evolutionary histories, and (f) considers their environmental adaptations. This is a field with a long history that in recent years has experienced a notable renaissance, principally with respect to theoretical content. Part of the theoretical material has to do with evolutionary areas (topics e and f above), the rest relates especially to the problem of classification. Taxonomy is that part of Systematics concerned with topics (a) to (d) above.

Taxonomy, systematic biology, systematics, biosystematics, scientific classification, biological classification, phylogenetics: At various times in history, all these words have had overlapping, related meanings. However, in modern usage, they can all be considered synonyms of each other.

**Comment by mariaforsen** [comment]
Taxonomi olisi hyvä erillisenä terminä myös ruotsiksi. Myös SAOssa.

**Comment by mirmaid** [comment]
Biotieteiden laitoksen kommentti:
 Taksonomia ja systematiikka eivät ole synonyymeja. Taksonomia tarkoittaa "perinteistä" tapaa tehdä eliöiden luokittelututkimusta eli se sisältää lajien, sukujen, heimojen jne. (eli taksonien) kuvaamisen ja nimeämisen ja esim. lajien sijoittamisen sukuihin yhteisten ominaisuuksien perusteella. Taksonomian voi sanoa perustuvan "silmillä nähtäviin ominaisuuksiin". Moderni systematiikka menee syvemmälle eli ei hyväksy kaikkia yhteisiä ominaisuuksia todisteeksi esim. lajien läheisestä sukulaisuudesta vaan selvittelee lajien sukulaisuuksia lähinnä DNA-aineistoon perustuen, koska DNA:ssa on usein luotettavampia signaaleja evoluutiosta kuin vaikkapa eläinten tai kasvien rakenteissa. Minusta taksonomia pitäisi käsitteenä selvästi erottaa systematiikasta.

Biologian sanakirjassa taksonomia määritellään näin: "eliöiden tieteellinen luokittelu; biologian ala, joka sisältää sekä nykyisten että sukupuuttoon kuolleiden elöiden kuvauksen, nimeämisen ja luokittelun (ryhmittelyn)."

Systematiikka puolestaan määritellään näin: "eliöiden järjestely; tutkii eliöiden monimuotoisuutta ja välisiä suhteita, erityisesti niiltä osin kuin sillä on merkitystä taksonien fylogeneettisten (ks. fylogenia) suhteiden kannalta. Ero taksonomia-käsitteeseen on vähäinen, eräiden mielestä termit ovat synonyymeja". KOMMENTTI: Nämä "eräät" eivät ymmärrä mistä on kysymys!

**Comment by FinMeSHienPaimentaja** [comment]
Linkki vuodelta 2004, peruskäsitteet silti lienevät samat nykyäänkin , vaikka molekyylibiologisia menetelmiä onkin nykyään enemmän käytössä. 

http://archive.is/nItw

**Comment by mirmaid** [comment]
_Taxonomi_ on SAOssa sekä itsenäisenä, että ohjausterminä (?). Ongelmallista tässä on, että kaikissa lähteissä todetaan näiden olevan merkitykseltään hyvin likeisiä ja joidenkin mielestä synonyymejä, eikä missään anneta määritelmiä, joilla nämä voisi yksiselitteisesti erottaa toisistaan. En vastusta taksonomiaa sinänsä terminä, mutta minusta tarvittaisiin määritelmä, jolla maallikkokin pystyy ymmärtämään näiden eron, muuten niitä käytetään kuvailussa jatkuvasti sekaisin.

**Comment by mariaforsen** [comment]
Nationalencyklopedin: 
-taxonomi: vetenskapen om organismernas klassificering, dvs. beskrivning, namngivning (nomenklatur) och formell klassifikation av organismgrupper som taxonomiska enheter
-systematik: vetenskapen om organismernas släktskapsförhållanden samt deras systematiska ordnande, i vid mening vetenskapen om de processer och mönster, såväl utvecklingshistoriska som nutida, som berör organismernas mångfald, mångformighet och släktskap. 

Tieteen termipankki:
-taksonomia: Eliöiden tieteellinen luokittelu, biologian ala, joka sisältää eliöitten kuvauksen, nimeämisen ja luokittelun (ryhmittelyn) 
-systematiikka: biologian tieteen ala, joka tutkii eliöiden sukulaisuussuhteita ja evolutiivista kehityshistoriaa

**Comment by YSA-kokous** [comment]
Jarmo ja Maria laativat määritelmät

**Comment by mariaforsen** [comment]
Peda.net: "Taksonomiaan kuuluu eliöiden kuvaus, nimeäminen ja ryhmittely. Systematiikka tutkii eliöiden monimuotoisuutta ja eliöiden välisiä sukulaisuussuhteita."

**Comment by mirmaid** [comment]
Edelleen kaipaan siis määritelmää, joka erottaa nämä toisistaan. Jos sanotaan että taksonomiaan kuuluu eliöiden ryhmittely ja toisaalta systematiikka tutkii eliöiden välisiä sukulaisuussuhteita, on vaikea kyllä tavallisena kuvailijana edelleen ymmärtää missä näiden raja menee ja miten ryhmittely voisi olla mahdollista ilman sukulaisuussuhteiden tutkimista (muuten kuin ehkä ihan historiallisessa mielessä, esim. Linnén aikana).

**Comment by FinMeSHienPaimentaja** [comment]
Selventäisikö oheinen, Tieteen termipankin määritelmien kanssa linjassa oleva lainaus asiaa:

"Systematiikka on yleisnimi tieteelle, joka tutkii eliöiden sukulaisuussuhteiden, määrittelyn ja luokittelun teoreettisia ongelmia. Taksonomia on yleisnimi tieteelle, joka tutkii samojen asioiden käytännön puolta."

http://archive.is/nItw#selection-263.1-263.213

**Comment by mirmaid** [comment]
No osaisiko joku antaa esimerkin tällaisesta teoreettisesta ongelmasta ja toisaalta esimerkin siitä mikä on käytännön puoleen kuuluvaa?

En siis tosiaankaan vastusta tätä jakoa mistään periaatteellisesta syystä, vaan koska epäilen että termejä käytettäisiin sattumanvaraisesti ja päällekkäin, jos tieteenalan sisälläkin osa pitää niitä synonyymeinä.

**Comment by FinMeSHienPaimentaja** [comment]
Mielestäni taksonomiaa (käytäntöä) on esimerkiksi:
https://helka.finna.fi/Record/helka.646426

ja systematiikkaa on esimerkiksi:
https://helka.finna.fi/Record/helka.2762306

PS. Aika paljonhan noita näyttää Helkan kautta löytyvän sekä taksonomiaa että systematiikkaa ja sekä ettäkin. Jolloin "sekä että" -tapauksissa voinee ajatella, että systematiikkaan sisältyy taksonomia, jollei systematiikkaa ole vain ihan "pienesti", jolloin kyse taksonomiasta.

**Comment by FinMeSHienPaimentaja** [comment]
Tässä vielä yhtenä esimerkkinä taksonomiaa (taksonomiseen sisältöön painottunut teos vaikuttaisi olevan):

https://helka.finna.fi/Record/helka.2228308

**Comment by satuniininen** [comment]
Jos biologian sanakirjassa näiden todetaan olevan merkitykseltään erittäin likeisiä ja joissain yhteyksissä synonyymisiä, niin on iso vastuu taviskuvailijalla yrittää erottaa käsillä olevasta aineistosta, kummasta on kyse. On suuri vaara, että kuvailija tarttuu yksinkertaisesti siihen termiin, joka nimekkeessä tai sisällössä kiinnittää huomion eikä jää syvemmin arvioimaan, käsitelläänkö aineistossa teoreettista ongelmaa vai käytännön sovelluksia. 

Kumpaa vai molempia esimerkiksi tämä on: https://melinda.kansalliskirjasto.fi/byid/006779723?
Ja mikäli molempia, niin mistä kuvailija hahmottaa, missä kohtaa systematiikka päättyy ja taksonomia alkaa?

**Comment by FinMeSHienPaimentaja** [comment]
Oheinen
https://melinda.kansalliskirjasto.fi/byid/006779723

on mielestäni (fylogeneettistä) systematiikkaa eli painottuu siihen. Jolloin mahdollinen taksonominen "osuus" sisältyisi systematiikkaan.  Ks. https://www.researchgate.net/publication/320413728_Difference_Between_Taxonomy_and_Systematics

Siihen en osaa vastata, missä kohtaa ko. kirjassa systematiikka päättyy ja taksonomia alkaa, mutta miksi se pitäisi tietää niin tarkasti, jos sellaisen edes pystyisi täydellisesti määrittämään…? Entä jos ajattelisi siitä näkökulmasta, että olennaista on, että mihin kirjan sisältö kokonaisuutena painottuu. 

Tässä vielä muuan näkemys ko. kirjasta:

https://www.jstor.org/stable/41678004?seq=1#metadata_info_tab_contents

"So, cladistics does still have a theoretical relevance to modern systematics even if it is no longer widely used in practice. This distinction is particularly relevant for Phylogenetics . The book professes to be about both "the theory and practice of phylogenetic systematics" but it focuses mainly on the former and says relatively little about modern practice. 
Indeed, the book actually concentrates on the logic of phylogenetic inference in relation to systematics (as noted on p. xv), which is only part of the theory and practice. This is the book's  principal weakness, that it focuses on logical inference (which was a big issue in 1981) rather than on modern systematic practice and its current theoretical justifications..."

**Comment by mirmaid** [comment]
Nyt siis _systematiikka (biologia)_ KT taksonomia. Ehdotan, että säilytetään nykyisellään, tai jos jatkuvasti aiheuttaa harmia, muutetaan > _systematiikka ja taksonomia_.

**Comment by YSO-kokous** [comment]
Ei muutosta. Yleissanastossa riittää nykyinen (epä)tarkkuus: systematiikka (biologia) KT taksonomia.
