### ISSUE TITLE
taksonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5416]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taksonit 

#### Ehdotettu termi englanniksi   

taxonomic unit, taxon 

#### Ehdotettu termi ruotsiksi   

taxon 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luokitukset (tieto)](http://www.yso.fi/onto/yso/p1401) 

#### Assosiatiiviset (RT)   

[lajit](http://www.yso.fi/onto/yso/p2765) 

#### exactMatch   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Biologia:taksoni> 

#### Tarkoitusta täsmentävä selite   

Tieteen termipankki: biologisessa taksonomiassa johonkin kategoriaan sijoitetun eliöryhmän yleisnimi
Explanation: Taksoneita ovat kaikki biologisessa luokittelussa erotetut ja nimetyt eliöryhmät riippumatta niiden hierarkkisesta tasosta. Lajitason taksoneita ovat esim. kiiltopaju, vaivaispaju ja metsähaapa, sukutason taksoneita pajut ja haavat, heimotason taksoneita pajukasvit ja koivukasvit jne.
http://tieteentermipankki.fi/wiki/Biologia:taksoni 

#### Perustelut ehdotukselle   

Tarvitaan biologisen aineiston kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARTO,  https://doi.org/10.14214/ma.6987 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [taksonit](http://finto.fi/yse/fi/page/Y505416)

**Comment by mirmaid** [comment]
Melindassa 3 viitettä. YSAssa on taksonomia KÄ _systematiikka_.

**Comment by mariaforsen** [comment]
Sv. taxa (taxonomi) ET taxon
