### ISSUE TITLE
SUP-laudat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5417]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SUP-laudat 

#### Vaihtoehtoiset termit ja ilmaisut   

suppaus, SUP-lautailu 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

Tällä hetkellä suppausta käsittelevät sisällöt täytyy indeksoida YSAn termeillä melonta, vesiurheilu - eivät kuvaa kovin tarkasti, eikä lainelautailukaan oikein käy. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

urheilu- ja hyvinvointilehtien indeksoinnissa 

**Ehdottajan nimi:** Elina Mäkelä 
**Ehdottajan organisaatio:** BTJ Finland / Aleksi-artikkelitietokanta 
**Ehdottajan sähköpostiosoite:** elina.makela@btj.fi **Termiehdotus Fintossa:** [SUP-laudat](http://finto.fi/yse/fi/page/Y505417)

**Comment by jtuohini** [comment]
Oikeastaan tässä on kaksi termiehdotusta: vesiurheilulaji (_suppaus_, _SUP-lautailu_) ja lajissa käytetty väline (_SUP-laudat_). Edellisen LCSH-vastine on joka tapauksessa **Stand-up paddle surfing** [http://id.loc.gov/authorities/subjects/sh2008008449]. Oikeinkirjoituksen kannalta varmaan "SUP" olisi syytä olla "Sup", koska se lausutaan sanana eikä kirjaimittain (vrt. esim. Unesco ja WHO)? Ja yksi KT-muoto lisää: _suppilaudat_.

**Comment by mirmaid** [comment]
Ehdottaisin että otetaan lajinimi. Sup-lautailu kuulostaa korrekteimmalta, suppailu on käytetympi muoto.

**Comment by mariaforsen** [comment]
Sv. ståpaddling ET brädpaddling ET stå upp-paddling ET SUP-paddling

**Comment by YSA-kokous** [comment]
sup-lautailu
