### ISSUE TITLE
kirjailijain nimikkoseurat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5418]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjailijain nimikkoseurat 

#### Ehdotettu termi englanniksi   

societies dedicated to some author 

#### Ehdotettu yläkäsite YSOssa (LT)   

[järjestöt](http://www.yso.fi/onto/yso/p1393) 

#### Perustelut ehdotukselle   

KULOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Käytetty Artossa yli 30 kertaa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kirjailijain nimikkoseurat](http://finto.fi/yse/fi/page/Y505418)

**Comment by jtuohini** [comment]
Varmaan täsmällisempi LT-suhteinen termi tälle olisi **kulttuurijärjestöt**? Täsmällistä LCSH-vastinetta vastaavasti ei löydy; lähin lienee niinkin epämääräinen kuin **Literature--Societies, etc.** [http://id.loc.gov/authorities/subjects/sh85077527] ja monet tarkemmat kirjallisuuden kielen ja lajin mukaan ja tietysti myös yksittäisen kirjailijan tasolla (esim. **Shakespeare, William, 1564-1616--Societies, etc.** [http://id.loc.gov/authorities/subjects/sh85121036]).

_À propos_, LCSH:n **Authors--Societies, etc.** kattaa saman kuin YSAn **kirjailijayhdistykset**, mutta sillekin löytyy toki tarkempia, kuten **Authors, African--Societies, etc.** (monta maata kattavat kirjailijayhdistykset), **Authors, Finnish--Societies, etc.** (yhden maan kattavat) ja **Authors, Russian--Russia (Federation)--Saint Petersburg--Societies, etc.** (paikallisyhdistykset), **Poets--United States--Societies, etc.** (yhteen kirjallisuuden lajiin keskittyvät kirjailijayhdistykset) ja **Women authors, Ugandan--Societies, etc.** (yhden maan tiettyä sukupuolta edustavien kirjailijoiden yhdistykset)). [Hassua puuhaa tämä wikipedistelyä vastaava juuri ennen nukkumaanmenoa. Ihan näin selityksenä ehkä kummalliselta vaikuttavalle pilkunviilaamiselleni täällä.]

**Comment by mirmaid** [comment]
YSAssa on _nimikkoseurat_, Allärs: _sällskap som uppkallats efter någon_.

**Comment by satuniininen** [comment]
Tämä tosiaan jäisi ilman LCSH-siltausta, samoin _kirjailijayhdistykset_, sillä **Authors--Societies, etc.** ei ilmeisesti ole auktorisoitu ketju.

**Comment by krinay** [comment]
Voisiko tämän ottaa ohjaustermiksi (KÄ nimikkoseurat)?

**Comment by mariaforsen** [comment]
Nimikkoseura-termeille on vaikeaa luoda ruotsink. vastineita.

**Comment by YSA-kokous** [comment]
KÄ nimikkoseurat
