### ISSUE TITLE
koneromantiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5419]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koneromantiikka 

#### Ehdotettu termi englanniksi   

machine romanticism 

#### Ehdotettu termi ruotsiksi   

maskinromantik 

#### Ehdotettu yläkäsite YSOssa (LT)   

[futurismi](http://www.yso.fi/onto/yso/p1323) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Tulenkantajien keskuudessa 1920-luvun loppupuolella suosittu suuntaus, johon liittyi futuristista koneiden ja erityisesti nopeiden matkustusvälineiden ihailua.  (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty muutamia kertoja. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [koneromantiikka](http://finto.fi/yse/fi/page/Y505419)

**Comment by jtuohini** [comment]
Liekö lähin LCSH-vastine löydettävissä jostakin tällaisesta: **Machinery--Aesthetic aspects** [http://id.loc.gov/authorities/subjects/sh99000440] – toki sopivin jatkein, jos halutaan varata termi tarkoittamaan vain suomalaista 1920-luvun kirjallista koneromantiikkaa (tai sittenkin vain **Futurism (Literary movement)--Finland--History--20th century** kera kirjailijaryhmän yksilöivän termin **Tulenkantajat (Group of writers)** [http://id.loc.gov/authorities/subjects/sh2009005574])?

**Comment by mirmaid** [comment]
Kaunokissa. Melindassa muutama viite, joissa käytetty kaunokirjallisuuden kuvailussa. 5 viitettä Artossa.

**Comment by satuniininen** [comment]
Lähimmät LCSH-vastineet näyttävät jäävän sen verran kauas, että siltaus jää tekemättä.

**Comment by mariaforsen** [comment]
Sv. maskinromantik
