### ISSUE TITLE
luontodokumenttielokuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5420]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luontodokumenttielokuva 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Perustelut ehdotukselle   

Ysasta nyt löytyvät on luontoelokuva, on toki kattavampi sisältäen myös fiktion (tosin kuinka monta luontofiktiota on tehty?) ja lyhyempi, mutta se ei ole kovinkaan puhekielinen. Oikeastihan puhutaan luontodokkareista, ei luontoelokuvista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Katso 8/2016: Artikkeli erämään lumo -sarjasta 

**Ehdottajan nimi:** Tuomas Nolvi 
**Ehdottajan sähköpostiosoite:** tuomas.nolvi@yle.fi 
**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [luontodokumenttielokuva](http://finto.fi/yse/fi/page/Y505420)

**Comment by jtuohini** [comment]
LCSH-vastineita: **Nature films** [http://id.loc.gov/authorities/subjects/sh93008140] ("Here are entered works on nonfiction films that depict or explain the natural world and its phenomena") ja sen ST-termi **Wildlife films** [http://id.loc.gov/authorities/subjects/sh93008162] ("Here are entered works on nonfiction films about animals, insects, and plants") ynnä **Documentary films** [http://id.loc.gov/authorities/subjects/sh85088115] (Sources-kohdassa lainattu kahta määritelmää).

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1278

Melindassa _luontodokumentit_ 11 viitettä (_luontoelokuvat_ 319).

**Comment by satuniininen** [comment]
LCSH-siltaus tulisi _Nature films_ -käsitteeseen.

**Comment by mariaforsen** [comment]
Sv. naturdokumentärer

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by mariaforsen** [comment]
MOT (kielitoimiston sanakirja): luontoelokuva:  luontoa kuvaava elokuva, luontofilmi.  Luontodokumenttielokuvat ei löydy ollenkaan. Kannatan että se lisätään korvattuna terminä.

Ruotsiksi tilanne on se että naturfilmer on:  dokumentärfilm med naturen i en huvudroll. Eli ruotsiksi päätermi on miten vain naturfilmer ja korvattuna on naturdokumentärer.

**Comment by LeKorsu** [comment]
Ylen tv-aineiston arkistotietokannassa näytetään käytetyn aika sekaisin sekä luontoelokuvaa että luontodokumenttia (ei asiasanoitusta vaan vapaamuotoista kuvailua). Koska käytetyin termi (luontodokumentti) ei oikein ole sopivanmuotoinen ysaan edes monikossa, kallistun Marian korvausehdotuksen kannalle
luontodokumenttielokuvat KÄ luontoelokuvat
luontodokumentit KÄ luontoelokuvat

Ehdottaisin kuitenkin myös uuden termin luonto-ohjelmat (televisio-ohjelmat) lisäämistä.

**Comment by YSA-kokous** [comment]
KÄ luontoelokuvat, lisäksi otetaan luonto-ohjelmat

**Comment by mariaforsen** [comment]
Sv. naturprogram

**Comment by mirmaid** [comment]
Palautteen perusteella uudelleen käsiteltäväksi muutos > luontodokumentit.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa luontodokumentit, ohjaustermiksi luontodokumenttielokuvat ja luontoelokuvat.

Sanastossa lisäksi luonto-ohjelmat, mutta kokous ei nähnyt, että luonto-ohjelmat ja luontodokumentit menevät keskenään kriittisellä tavalla sekaisin.

**Comment by mariaforsen** [comment]
Sv. naturdokumentärer ET naturfilmer

**Comment by mirmaid** [comment]
Tätä ehkä pitäisi vielä pohtia. YSOssa nyt siis _luonto-ohjelmat_ ja _luontodokumentit_ (oli _luontoelokuvat_), jonka yläkäsite on _dokumenttielokuvat_. _Luonto-ohjelmat_ on otettu sanastoon siinä vaiheessa, kun toinen termi oli vielä _luontoelokuvat_. YSOssa on lisäksi _dokumenttiohjelmat_ (luonto-ohjelmat ei tällä hetkellä ole sen alakäsite). 

SLM:ään otettiin _sotadokumentit_ ja _urheiludokumentit_, joilla on nyt RT-suhde _dokumenttielokuviin_ ja _dokumenttisarjoihin_. Lisäksi _matkailuelokuvat_ ja _luontoelokuvat_ ollaan muuttamassa muotoon _matkailudokumentit_ ja _luontodokumentit_. SLM:ssä ei ole _dokumenttiohjelmat_-termiä. 

Tilanne on ehkä kuitenkin vähän sekava. Dokumentit-loppuisia termejä ei varmaan ole mahdollista tai järkevää rajata elokuviin, mutta _luonto-ohjelmat_ tarvitaan varmasti joka tapauksessa, koska ainakaan radio-ohjelmat eivät ole dokumentteja. Hierarkia pitäisi miettiä loogiseksi (yläkäsitteeksi ei elokuvat, jos ei rajaudu niin, _luontodokumenttien_ ja _luonto-ohjelmien_ suhde). _Dokumenttiohjelmat_-termille olisi ehkä tarvetta myös SLM-sanastossa.

**Comment by mirmaid** [comment]
Luontoelokuvat > luontodokumentit, lisätään luonto-ohjelmille käyttöhuomautus. 

Tutkitaan dokumenttiohjelmat-termin käyttöä Melindassa.

**Comment by mirmaid** [comment]
Seuraava kokous:
luonto-ohjelmille käyttöhuomautus
dokumenttiohjelmat-termin käyttö
radio-ohjelmat puuttuu myös

**Comment by mariaforsen** [comment]
Huom. Melindan tietueissa on näköjään vielä muoto "luontoelokuvat", ei luontodokumentit (kuten SLM:ssä ja YSO:ssa)

**Comment by mirmaid** [comment]
Luontodokumentit: suhteet ennallaan ainakin toistaiseksi. Liittyy laajemmin kuitenkin laajemmin elokuvien ja tv-ohjelmien hierarkiaan, vrt. esim. IMDb. Luonto-ohjelmille ei tässä vaiheessa käyttöhuomautusta.

Uudet issuet dokumenttiohjelmista ja radio-ohjelmista.
