### ISSUE TITLE
televisio-ohjaaja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5421]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

televisio-ohjaaja 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ohjaajat](http://www.yso.fi/onto/yso/p12705) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

ohjaaja, joka työskentelee televisiolle. vrt elokuvaohjaaja 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Katso 7/2016 artikkeli Johanna Vuoksenmaasta 

**Ehdottajan nimi:** Tuomas Nolvi 
**Ehdottajan sähköpostiosoite:** tuomas.nolvi@yle.fi 
**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [televisio-ohjaaja](http://finto.fi/yse/fi/page/Y505421)

**Comment by jtuohini** [comment]
Lähin LCSH-vastine olisi **Television producers and directors** [http://id.loc.gov/authorities/subjects/sh85133601]. Ja ehdotettu muoto varmaan tarkoitettu olemaan monikossa?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4792

**Comment by satuniininen** [comment]
LCSH-siltaus _Television producers and directors_ -käsitteeseen broaderMatch-suhteella.

**Comment by mariaforsen** [comment]
Sv. tv-regissörer
