### ISSUE TITLE
normipoikkeama

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5422]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

normipoikkeama 

#### Ehdotettu termi ruotsiksi   

anomalia 

#### Ehdotettu termi englanniksi   

anomaly,  KITOssa aberration 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjallisuuden kieli](http://www.yso.fi/onto/yso/p4678) 
[kirjallisuuden kieli](http://www.yso.fi/onto/yso/p4678) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Määritelmä poikkeaminen kielenkäytön vakiintuneista säännöistä ja kieliopin normeista; tyylilajin riitasointu; (tahallinen) tyylirikko
Selite Normipoikkeamia on äänteellisiä, kieliopillisia, lauserakenteellisia, sanastollisia ja merkitysopillisia. Kirjoittajan omintakeinen tyyli syntyy usein juuri tekstin anomalististen piirteiden ansiosta. Tahallisia normipoikkeamia on harrastettu erityisen runsaasti pakinoissa ja modernissa lyriikassa. (Termipankki) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib 138809 ja 2365443 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [normipoikkeama](http://finto.fi/yse/fi/page/Y505422)

**Comment by mirmaid** [comment]
Melindassa 2 viitettä 653-kentässä (yksikössä).

Käytetään myös kirjallisuustieteen ulkopuolella.

**Comment by mariaforsen** [comment]
Sv. anomali + tarkenne, jos viittaa vain kirjallisuuteen.

**Comment by YSA-kokous** [comment]
anomaliat (?), seuraava kokous

**Comment by mirmaid** [comment]
Hosiaisluoma: anomalia ks. normipoikkeama (Määritelmä sama kuin Tieteen termipankissa)

**Comment by krinay** [comment]
_Anomaliat_ olisi ihan hyvä. Tieteen termipankin määritelmä normipoikkeamalle/anomalialle:
"Poikkeaminen kielenkäytön vakiintuneista säännöistä ja kieliopin normeista; tyylilajin riitasointu; (tahallinen) tyylirikko"

**Comment by YSA-kokous** [comment]
anomaliat yleisterminä

**Comment by mariaforsen** [comment]
Sv. anomalier
