### ISSUE TITLE
arkkitekstuaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5424]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

arkkitekstuaalisuus 

#### Ehdotettu termi englanniksi   

architextuality 

#### Ehdotettu termi ruotsiksi   

architextualitet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tekstilähtöinen kirjallisuudentutkimus](http://www.yso.fi/onto/yso/p28253) 

#### Assosiatiiviset (RT)   

[intertekstuaalisuus](http://www.yso.fi/onto/yso/p17213) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Monille teksteille yhteisiä tyyppiominaisuuksia edustavat piirteet. Arkkitekstuaalisuudessa on kyse erityisesti yhteisten laji- ja kerrontamallien kautta muodostuvista tekstin suhteista muihin teksteihin. Esim. jokainen dekkari on arkkitekstuaalisessa suhteessa muihin dekkareihin. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib1016248 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [arkkitekstuaalisuus](http://finto.fi/yse/fi/page/Y505424)

**Comment by mirmaid** [comment]
Melindassa 2 viitettä, ei Artossa.

**Comment by mirmaid** [comment]
Monille teksteille yhteisiä tyyppiominaisuuksia edustavat tekstin piirteet. Määritelmä tulee Gérard Genetteltä. Karkeasti arkkitekstin voisi määritellä synonyyminä genrelle. Se ei ole mikään konkreettinen teksti vaan abstrakti käsite, jota voi lähestyä vain lajia ilmentävien tekstien kautta. Esimerkiksi jokainen dekkari on arkkitekstuaalisessa (ja samalla intertekstuaalisessa) suhteessa toisiin dekkareihin. https://quizlet.com/53509403/kirjallisuustiede-i-termisto-flash-cards/

Architextuality is the designation of a text as a part of a genre or genres https://en.wikipedia.org/wiki/Transtextuality#Subtypes

https://www.decodedscience.org/what-is-transtextuality-understanding-the-meaning-of-the-words-we-read/28891/2

**Comment by mariaforsen** [comment]
Sv. arketextualitet
