### ISSUE TITLE
kehyskertomus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5425]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kehyskertomus 

#### Ehdotettu termi ruotsiksi   

ramberättelse 

#### Ehdotettu termi englanniksi   

frame story 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kertomukset](http://www.yso.fi/onto/yso/p24639) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

1) kertovan proosan rakenne-elementteihin kuuluva varsinaisesta ydinkertomuksesta tai kertomussikermästä eroava taustakertomus
2) kertomus, johon on upotettu toinen kertomus (Termipankki) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib86110 

#### Perustelut ehdotukselle   

KITOn termi 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kehyskertomus](http://finto.fi/yse/fi/page/Y505425)

**Comment by mirmaid** [comment]
Kaunokissa monikossa. Melindassa 52 kertaa monikossa, 4 kertaa yksikössä.

**Comment by krinay** [comment]
Jos otetaan, monikko varmaan parempi.

**Comment by mariaforsen** [comment]
Sv. ramberättelser

**Comment by YSA-kokous** [comment]
Hyväksytään monikossa.
