### ISSUE TITLE
sisäkertomus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5426]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sisäkertomus 

#### Ehdotettu termi englanniksi   

story within a story (KITO), inner story, embedded narrative 

#### Ehdotettu termi ruotsiksi   

innesluten berättelse 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kertomukset](http://www.yso.fi/onto/yso/p24639) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Pääjuonen oheen limitetty kertomus, jolla on usein temaattisesti ja rakenteellisesti merkittävä tehtävä varsinkin romaaneissa. Sisäkertomukset ovat poikkeamia pääjuonesta ja siten omiaan hidastamaan kerrontaa, mutta niiden avulla voidaan luoda monikerroksisempi ja monivivahteisempi kuva fiktiivisestä maailmasta. (Termipankki) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib 932124 ja monta muuta 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [sisäkertomus](http://finto.fi/yse/fi/page/Y505426)

**Comment by mirmaid** [comment]
Kaunokissa monikossa. Käytetty Melindassa yksinomaan monikossa, yli 300 viitettä.

**Comment by krinay** [comment]
Monikko on varmaan hyvä tässä.

**Comment by mariaforsen** [comment]
Kauno: kärnberättelser ? Taitaa olla virheellinen..

**Comment by OutiHintikka** [comment]
Kannatan monikkoa.

**Comment by YSA-kokous** [comment]
Hyväksytään monikossa, RT mise en abyme, KT sisäkkäiskertomukset?
