### ISSUE TITLE
ääni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5427]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ääni](http://www.yso.fi/onto/ysa/Y100507) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Suomenkieliset termit käsitteille "ääni" ja "äänet" vaativat tarkennusta, jotta ne mukailevat paremmin ruotsin "ljud" ja "röst" termejä. Eli yksiköllinen "ääni" rajataan ihmisääniin ja monikollinen ääniin yleensä. 

#### Ehdotettu muutos   

Joku seuraavista vaihtoehdoista:
ääni (ihmisen ääni) / ääni (ihmisääni)
ääni (ihmiset/ihminen)
ihmisen ääni / ihmisääni 

mikäli tarvitaan myös monikolliselle muodolle sulkutarkenne erottamaan yksiköllisestä äänet-käsitteestä, ehdotetaan muotoa äänet (fysikaaliset ilmiöt) (tämä myös erottaa äänestys-merkityksestä)
#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by jtuohini** [comment]
Fysikaalisena ilmiönä pitäisi varmaan kuitenkin olla yksikössä, koska kyse on aaltoliikkeestä (eikä ole luontevaa puhua "aaltoliikkeistä"). Kun **ääni** eli väliaineessa tapahtuva **aaltoliike** (jonka **taajuus** määrää, onko kyseessä **ultraääni**, **infraääni** vai ihmisen kuultavissa oleva), tulee havaituksi kuulemalla (**kuulohavainnot**), voidaan siitä puhua myös monikossa (**äänet**), olipa kyse ihmisen (_ihmisääni_) tai jonkin muun elollisen olennon (**eläinten äänet**) tai luonnonilmiön tuottamasta äänestä (**luonnonäänet**) – tai vaikka tietokoneella tuotetusta siniaallosta tai kanttiaallosta tai **kohina**sta (mahtaako tarkoittaa YSAssa satunnaissignaalia vai onko synonyyminen valkoiselle kohinalle ja/tai vaaleanpunaiselle kohinalle?), joka tunkee ulos yhdestä tai useammasta kaiuttimesta.

YSAsta muuten puuttuu suhde termien **ääni** ja **aaltoliike** välillä! Ja **kohina** kaipaisi selityksen ja terminkäyttöohjeen.

**Comment by mariaforsen** [comment]
Ruotsin kannalta tärkeintä että erotellaan ihmisääni=röst (sitä ei voi sekoittaa termiin ljud.. ja varmasti hakijaakin kiinnostaa tuloksia nimenomaan ihmisäänistä). Jos välttämättä halutaan ottaa useita "ääniä", se on mahdollista ruotsiksikin, kunhan niiden merkitys on selkeästi eroteltu ja tarkennettu (ja niiden käyttö Melindassa selkeä ja johdonmukainen, eli ei pelkästään teoreettisesti perusteltu). 

Vrt. SAO: 
röst (LSCH voice) 
ljud (LCSH sound)

YSOssa ollut jo: ääni=röst, äänet=ljud

**Comment by satuniininen** [comment]
Muutama havainnollistava esimerkki, miten asettuisivat olemassaoleviin kuvailuihin: 

lapset - kielellinen kehitys - ihmisen ääni
lapset - kielellinen kehitys - ääni (ihmiset)
lapset - kielellinen kehitys - ääni (ihmisen)
lapset - kielellinen kehitys - ääni (ihmisen ääni)
lapset - kielellinen kehitys - ääni (ihmisääni)

opiskelijat - ihmisen ääni - ongelmat
opiskelijat - ääni (ihmiset) - ongelmat
opiskelijat - ääni (ihmisen) - ongelmat
opiskelijat - ääni (ihmisen ääni) - ongelmat
opiskelijat - ääni (ihmisääni) - ongelmat

siitepölyallergia - ihmisen ääni - äänentuotto
siitepölyallergia - ääni (ihmiset) - äänentuotto
siitepölyallergia - ääni (ihmisen) - äänentuotto
siitepölyallergia - ääni (ihmisen ääni) - äänentuotto
siitepölyallergia - ääni (ihmisääni) - äänentuotto

Itse kannatan muotoa _ääni (ihmisääni)_

**Comment by jtuohini** [comment]
Ja minusta huomattavasti selkeämpi (uusi) termi olisi _ihmisääni_ (verrattuna edellisen ehdotuksen _ääni (ihmisääni)_ -termiin). Edelleen jäisi kysymys äänestä fysikaalisena ilmiönä (**ääni**), jonka RT-suhteina olisivat **infraääni** ja **ultraääni** ja sen/niiden ruotsinnoksesta?

**Comment by jtuohini** [comment]
Niin, tai _ihmisäänet_ (tai vaihtoehtoisesti sekä _ihmiääni_ että _ihmisäänet_), riippuen siitä kumpaa tarkoiteteen, ilmiötä sinällään vai ilmiön tuotoksia!

**Comment by satuniininen** [comment]
Tämä on varmaan osittain myös makuasia, omaan silmään _ihmisääni_ näyttää kuvailuissa oudolta ja jopa harhaanjohtavalta. Vrt.

lapset - kielellinen kehitys - ihmisääni
opiskelijat - ihmisääni - ongelmat
siitepölyallergia - ihmisääni - äänentuotto

Mutta eivät sulkutarkenteetkaan toki ole ongelmattomia.

Ääntä fysikaalisena ilmiönä käsitellään täällä: https://github.com/Finto-ehdotus/YSE/issues/5428

**Comment by mirmaid** [comment]
Sellainenkin optio tuli mieleeni, että poistetaan pari vuotta sitten hyväksytty _puheääni_ ja tehdään siitä sulkutarkenne tälle :speak_no_evil:

**Comment by jtuohini** [comment]
Entä kun ihmisääneen viittaavan käsitteen sopisi kattavan puheen lisäksi laulun ym?

**Comment by mirmaid** [comment]
^ Odotinkin tätä kommenttia. Mutta voidaan ottaa lauluääni.

**Comment by mariaforsen** [comment]
Sångröst=lauluääni on myös ok, näiden lisäksi. On myös SAOssa.

**Comment by YSA-kokous** [comment]
ääni (ihmisääni)
lauluääni, puheääni
