### ISSUE TITLE
äänet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5428]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänet](http://www.yso.fi/onto/ysa/Y111175) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

mikäli tarvitaan myös monikolliselle muodolle sulkutarkenne erottamaan yksiköllisestä äänet-käsitteestä, ehdotetaan muotoa äänet (fysikaaliset ilmiöt) (tämä myös erottaa äänestys-merkityksestä)

lisäksi äänet (harha-aistimukset) KÄ harha-aistimukset

vrt. "ääni", jolle ehdotetaan jotain seuraavista vaihtoehdoista:
ääni (ihmisen ääni) / ääni (ihmisääni)
ääni (ihmiset/ihminen)
ihmisen ääni / ihmisääni 

#### Perustelut ehdotukselle   

Suomenkieliset termit käsitteille "ääni" ja "äänet" vaativat tarkennusta, jotta ne mukailevat paremmin ruotsin "ljud" ja "röst" termejä. Eli yksiköllinen "ääni" rajataan ihmisääniin ja monikollinen ääniin yleensä. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by jtuohini** [comment]
> Eli yksiköllinen "ääni" rajataan ihmisääniin ja monikollinen ääniin yleensä.

Yksikkö ja monikko pitäisi olla juuri toisinpäin: **ääni** on fysikaalinen ilmiö, **äänet** ennemminkin kuulijan kannalta merkityksellisinä aistittavia, kattaen käsitteet _ihmisääni_ (sis. _lauluääni_, _puheääni_), **eläinten äänet**, **luonnonäänet**.

**Comment by mirmaid** [comment]
^ Onko sulla @jtuohini ehdotusta paremmasta sulkutarkenteesta tälle monikolliselle kuin (fysikaaliset ilmiöt)? 

Tai sitten poistetaan monikko kokonaan, jätetään ääni (fysikaaliset ilmiöt) ST ääni (puheääni) ST lauluääni.

**Comment by jtuohini** [comment]
Mutta jos sanastoon tulee/jää vain yksi **äänet**, niin miksi tarvitsisi sulkutarkenteen? Viitaten suomenkieliseen Wikipediaan ([Ääni](https://fi.wikipedia.org/wiki/%C3%84%C3%A4ni)): **ääni** yksikössä tarkoittaisi siis fysikaalista ilmiötä (aaltoliikettä) ja **äänet** kuuloaistimuksia tajunnassa. Mikä tämän jälkimmäisen termin sulkutarkenne olisi, keksiytyy ehkä tuosta paremmin?

**Comment by YSA-kokous** [comment]
ääni/äänet (fysikaaliset ilmiöt), tutkitaan vielä yksikkö/monikko

**Comment by YSA-kokous** [comment]
Kokeillaan toimiiko ääni (fysikaaliset ilmiöt)

**Comment by satuniininen** [comment]
Sulkutarkenne _(fysikaaliset ilmiöt)_ tuntuu hieman vieraalta teoksissa, joissa ääniä käsitellään laajempina kokonaisuuksia, esim. tietyn paikan ääniympäristön näkökulmasta. Näihin on jo olemassa täsmällisempää käsitteistöä (_ääniympäristö, äänimaisema_), joten ääni/äänet on usein mukana vain "varman päälle". Samoin eläinten ääniä käsitteleviin aineistoihin on oma käsitteensä _eläinten äänet_. 

Muutenkin äänen eri aspekteihin liittyvää käsitteistöä on paljon (_melu, kuulo, äänitekniikka, äänenkäsittely, äänenvoimakkuus, äänentoisto_ jne), joten kuvailu on varmastikin kierrettävissä muilla muilla termeillä mikäli sulkutarkenne vaikuttaa aivan mahdottomalta.

**Comment by YSA-kokous** [comment]
ääni (fysikaaliset ilmiöt)
