### ISSUE TITLE
nuortensarja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5430]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nuortensarja 

#### Ehdotettu yläkäsite YSOssa (LT)   

[televisiosarjat](http://www.yso.fi/onto/yso/p25701) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

vrt. nuortenelokuvat. nuortensarjoja tehdään Suomessa yhtä paljon t. ehkä enemmänkin kuin nuortenelokuvia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Katso 4/2016: Vihräet valot - väärät bileet -nuortensarjaa käsittelvä artikkeli 

**Ehdottajan nimi:** Tuomas Nolvi 
**Ehdottajan sähköpostiosoite:** tuomas.nolvi@yle.fi 
**Ehdottajan organisaatio:** Yle Arkisto

**Comment by mirmaid** [comment]
Kaunokissa. Käytetty Melindassa 9 kertaa genrenä.

**Comment by LeKorsu** [comment]
Peukku kollegan ehdotukselle, tosin varmaankin monikkomuodossa.

**Comment by mariaforsen** [comment]
Sv. ungdomsserier
