### ISSUE TITLE
seksuaalipsykologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5432]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

seksuaalipsykologia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Perustelut ehdotukselle   

perussana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** BTJ 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [seksuaalipsykologia](http://finto.fi/yse/fi/page/Y505432)

**Comment by jtuohini** [comment]
LCSH-vastine arvattavasti **Sex (Psychology)** [http://id.loc.gov/authorities/subjects/sh85120562].

**Comment by mirmaid** [comment]
Melindassa 8 viitettä.

**Comment by mariaforsen** [comment]
Sv. sexualpsykologi
