### ISSUE TITLE
rinnakkaismaailmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5433]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rinnakkaismaailmat 

#### Ehdotettu termi englanniksi   

parallel universes 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib 1240183 (Komeron kautta toisaalle) ja pari muuta 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Parallel_universe 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [rinnakkaismaailmat](http://finto.fi/yse/fi/page/Y505433)

**Comment by mirmaid** [comment]
Kaunokissa muodossa _rinnakkaiset maailmat_ (Melinda 1066 viitettä, rinnakkaismaailmat kerran).

**Comment by mariaforsen** [comment]
Sv. parallella världar

**Comment by YSA-kokous** [comment]
Otetaan joko tämä tai Kaunokin muoto, Kaunokki-kokous.

**Comment by YSA-kokous** [comment]
rinnakkaiset maailmat

**Comment by mariaforsen** [comment]
Sv. parallella världar ET parallella universa, parallella universum
