### ISSUE TITLE
kirjoitusharrastus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5434]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjoitusharrastus 

#### Ehdotettu termi englanniksi   

amateur writing 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjoittaminen](http://www.yso.fi/onto/yso/p2512) 

#### Assosiatiiviset (RT)   

[harrastajakirjoittajat](http://www.yso.fi/onto/yso/p16076) 
[kirjoituskilpailut](http://www.yso.fi/onto/yso/p11024) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib 128667 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kirjoitusharrastus](http://finto.fi/yse/fi/page/Y505434)

**Comment by mirmaid** [comment]
Melindassa 5 viitettä. YSAssa on _harrastajakirjoittajat_, tässä muodossa löytyy _lukuharrastus, liikuntaharrastus_ ja _lintuharrastus_, monikossa _kulttuuriharrastukset_ ja _taideharrastukset_.

**Comment by mariaforsen** [comment]
Sv. amatörskrivande ET hobbyskrivande ET skrivintresse
