### ISSUE TITLE
dramatisointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5437]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dramatisointi](http://www.yso.fi/onto/ysa/Y107417) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään dramatisointi-käsitteelle toiseksi yläkäsitteeksi ’taiteellinen luonti’. 

#### Perustelut ehdotukselle   

MAOn tanssin ja teatterin asiantuntijat toivoivat dramatisointi-käsitteelle lisättäväksi toiseksi yläkäsitteeksi ’taiteellinen luonti’, koska se on luonteva yläkäsite. 

#### Ehdottaja   

Mari Suhonen 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

mari.suhonen@tsk.fi

**Comment by mirmaid** [comment]
_Taiteellinen luonti_ -käsite on poistettu.
