### ISSUE TITLE
devising

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5438]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[devising](http://www.yso.fi/onto/ysa/Y199061) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

MAOn teatterialan asiantuntijat ehdottavat devising-käsitteen (p27780) käytettäväksi termiksi muutettavaksi ”devising-teatteri”. Devising-termi viitaa kahteen käsitteeseen - sekä teatteriin että menetelmään. MAOssa asia ratkaistiin niin, että termi ”devising” viittaa nyt menetelmään ja termi ”devising-teatteri” teatteriin. 

#### Ehdotettu muutos   

Muutetaan devising-käsitteen (p27780) käytettäväksi termiksi devising-teatteri. 

#### Ehdottaja   

Mari Suhonen 

#### Ehdottajan organisaatio   

Sanastokeskus TSK 

#### Ehdottajan sähköpostiosoite   

mari.suhonen@tsk.fi

**Comment by mirmaid** [comment]
MAOssa on nyt siis sekä _devising_, LT menetelmät, RT teatteri, että _devising-teatteri_, LT teatteri. YSAssa on devising-teatteri KÄ _devising_, LT teatteri.

Melindassa 4 kertaa muodossa _devising-menetelmä_. Niissäkin kyse on teatterista. En oikein onnistunut löytämään esimerkkiä devising-menetelmän käytöstä muussa kuin teatterin yhteydessä?

**Comment by mariaforsen** [comment]
Riittäisikö yleisen sanaston puolella pelkkä devising?

**Comment by OutiHintikka** [comment]
Devising itsessään on menetelmä, joten kannatan lyhempää muotoa.

**Comment by YSA-kokous** [comment]
devising-teatteri, kysytään asiantuntijoilta (?)

**Comment by vthuhtala** [comment]
Määritelmä?

**Comment by mirmaid** [comment]
_Devising-sana tulee englannin kielestä ja on lyhenne sanaparista devising theatre, josta käytetään myös muotoa devised theatre. Sana viittaa joukkoon nykyteatterin ajattelu- ja työtapoja. Suomeksi devisingista on käytetty termiä ryhmä- ja prosessikeskeinen teatteri. Eräs tapa määritellä devising on "ne teatterin tekemisen tavat, joissa ennalta laadittua käsikirjoitusta ei ole, vaan käsikirjoitus syntyy prosessissa ryhmän synnyttämänä"._ http://oppimateriaali.wikidot.com/devising

https://en.wikipedia.org/wiki/Devised_theatre

**Comment by YSA-kokous** [comment]
Ei muutosta
