### ISSUE TITLE
omaelämäkerralliset romaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5439]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

omaelämäkerralliset romaanit 

#### Ehdotettu termi ruotsiksi   

autobiografiska romaner 

#### Ehdotettu termi englanniksi   

autobiographical novels 

#### Ehdotettu yläkäsite YSOssa (LT)   

[romaanit](http://www.yso.fi/onto/yso/p1896) 

#### Assosiatiiviset (RT)   

[elämäkertaromaanit](http://www.yso.fi/onto/yso/p17968) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Kirjoittajan omasta elämästä merkittävästi aineksia saanut romaani, jossa ei kuitenkaan ole kyse varsinaisista muistelmista. (Hosiaisluoma, Tieteen termipankkii) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib1043029, ja monta muuta. 

#### Perustelut ehdotukselle   

KITOn termi, joskin siellä yksikössä 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [omaelämäkerralliset romaanit](http://finto.fi/yse/fi/page/Y505439)

**Comment by jtuohini** [comment]
LCSH-vastine **Autobiographical fiction** [http://id.loc.gov/authorities/subjects/sh85048066].

Olisiko LT-suhteeksi täsmällisempi **elämäkertaromaanit** vai sitäkö juuri on tarkoitus vältellä (vrt. **muistelmat**, KT _omaelämäkerrat_; tässä vastaavasti olisi "muistelmalliset romaanit"). Entä mikä olisi suhde termiin **autofiktio**?

**Comment by mirmaid** [comment]
Hups, vahinkopeukku. Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5039

**Comment by krinay** [comment]
Autofiktio voisi riittää. Voisiko omaelämäkerralliset romaanit lisätä sen ohjaustermiksi?

**Comment by YSA-kokous** [comment]
KÄ autofiktio
