### ISSUE TITLE
kveenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5440]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kveenit](http://www.yso.fi/onto/ysa/Y105441) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kveenit -käsitteen ohjausterminä nyt kainulaiset. Ohjaustermin voisi poistaa tai ottaa omaksi käsitteeksi. 

#### Perustelut ehdotukselle   

Käsitteiden välinen yhteys on epäselvä. Esim. Lapponica-asiasanastossa nämä ovat erilliset käsitteet, joilla on RT-suhde. Wikipedia: "Kveenit ovat Pohjois-Norjan eli Ruijan (Finnmark) suomalaisperäistä väestöä". - - - "Kainulaiset on vanha nimitys, joka viittaa Pohjanmaan rannikkoseutujen asukkaisiin. Nimitystä ovat käyttäneet varsinkin savolaiset. Kainulaiset-nimi on tunnetuissa historiallisissa käyttöyhteyksissään ollut lähinnä eksonyymi eli vieraasta ryhmästä käytetty nimi, ei niinkään ryhmän itsestään käyttämä nimi."

Kveenit-käsitteellä on ohjausterminä myös ruijansuomalaiset. Myös tämä löytyy Lapponicasta erillisenä käsitteenä (muodossa "Ruijan suomalaiset"), mutta toisaalta se on kyseisessä sanastossa myös ohjaustermi sekä kveeneille että kainulaisille.

Note-to-self: Odotamme YSA-kokouksen päätöstä tästä asiasta, jotta tiedämme, miten linkitämme asianomaiset Lapponica-käsitteet YSOon. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Poistetaan ohjaustermi kainulaiset? Tosin wikipedia: _Viime aikoina Pohjois-Norjan nykyisien kveenien itsestään käyttämänä nimityksenä on alkanut esiintyä kainulaiset-sanasta mukailtu nimi kainu._

**Comment by krinay** [comment]
Jäisikö termi kainulaiset siis kokonaan pois sanastosta? 

Erikoissanastoissa on usein täsmällisempiä käsitteitä kuin yleisessä sanastossa on tarpeen olla. Yleisessä sanastossa ohjaustermi voi korvata erikoissanaston tarkkavivahteisen käsitteen.

Kielitoimiston sanakirja:
kainulainen
1. hist. Kainulaiset keskiaikana Pohjanlahden ja Jäämeren välisellä alueella asuneet suomalaiset.
2. vanh. kveeni.

Minusta termin kainulaiset olisi hyvä pitää sanastossa - joko ohjausterminä tai omana käsitteenä. Jos se on omanaan, se pitäisi varmaan jotenkin määritellä.

**Comment by YSA-kokous** [comment]
kainulaiset (kveenit) KÄ kveenit
