### ISSUE TITLE
kikujut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5441]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kikujut 

#### Ehdotettu termi ruotsiksi   

Kikuyu (folk) 

#### Ehdotettu termi englanniksi   

Kikuyu (African people) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[bantut](http://www.yso.fi/onto/yso/p2853) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85072307.html> 
SAO : Kikuyu (folk) 
Wikipedia : https://fi.wikipedia.org/wiki/Kikujut 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Melindassa käytetty käsite. YSAsta löytyy kikujun kieli mutta ei kansaa. 

#### Tarkoitusta täsmentävä selite   

Kenian suurin etninen ryhmä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

antropologinen tai kansatieteellinen kirjallisuus 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [kikujut](http://finto.fi/yse/fi/page/Y505441)

**Comment by mariaforsen** [comment]
Sv. kikuyu (folk)
