### ISSUE TITLE
vapaa mitta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5442]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vapaa mitta 

#### Ehdotettu termi englanniksi   

free verse 

#### Ehdotettu termi ruotsiksi   

fri vers 

#### Assosiatiiviset (RT)   

[loppusointu](http://www.yso.fi/onto/yso/p14154) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto bib1280225 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [vapaa mitta](http://finto.fi/yse/fi/page/Y505442)

**Comment by mirmaid** [comment]
Melindassa 2 viitettä. Myös Kaunokissa.

**Comment by mariaforsen** [comment]
Sv. fri vers
