### ISSUE TITLE
ansat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5443]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ansat](http://www.yso.fi/onto/ysa/Y134552) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkistus: Allärs: snaror, Bella: snaror + fällor 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

HYK, Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käytetty vain 13 kertaa YSA-terminä, näistä monet liittyvät sodankäyntiin (miina- tms. ansat?), mikä ei varmaankaan ole ruotsiksi snara eikä fälla? Löytyisikö metsästys-kontekstiin ruotsiksi jokin yksi termi, joka kattaisi erityyppiset ansat (ansapyynti tms.)? Ja löytyisikö sodankäynti-kontekstiin jokin ihan oma termi, tai tarvitaanko edes?

**Comment by mariaforsen** [comment]
Ansat=fällor (KT snaror) on hyvä ratkaisu. Fälla="fångstanordning till vilken djur lockas med föda eller doftmedel b) om listigt handlande för att oskadliggöra fiende" Eli aivan riittävä molempiin asiayhteyksiin. 


Olisiko loukut hyvä ohjaustermi? Sekin on "fälla".

**Comment by YSA-kokous** [comment]
loukut KÄ ansat
