### ISSUE TITLE
pelko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5444]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pelko](http://www.yso.fi/onto/ysa/Y111441) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkistus: Allärs: rädsla, Bella: rädsla, Kauno sv. fruktan 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

HYK, Kaunokki-kokous 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Myös YSO: fruktan. Fruktan on varmaan valittu ALLFOon sen takia ettei tarvitsisi lisätä sulkutarkennetta (koska on myös "rädslor").

**Comment by mariaforsen** [comment]
Sv. rädsla
