### ISSUE TITLE
seka-avioliitto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5445]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seka-avioliitto](http://www.yso.fi/onto/ysa/Y110443) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ monikulttuurinen avioliitto 

#### Perustelut ehdotukselle   

Yhdistetty YSOssa ja Kaunokissa. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by krinay** [comment]
Kai termiä _monikulttuurinen avioliitto_ voi käyttää myös eri uskontokuntiin kuuluvien (luterilaisten ja ortodoksien tms.) tai erikielisten (suomenkielisten ja suomenruotsalaisten tms.) välisistä avioliitoista? Termillä seka-avioliitto on kuvailtu niitäkin.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
https://evl.fi/maailmalla/ekumenia/ekumeeniset-avioliitot

**Comment by krinay** [comment]
Suomen Ekumeninen Neuvosto puhuu seka-avioliitoista:
http://www.ekumenia.fi/sen_esittaytyy/kannanottoja_ja_lausuntoja/suositukset_vihkimisesta_seka-avioliittoon/.
Samoin ainakin Helsingin juutalainen seurakunta:
https://jchelsinki.fi/fi/me/suomalaisessa_yhteiskunnassa

**Comment by krinay** [comment]
LCSH:
Intermarriage http://id.loc.gov/authorities/subjects/sh85081430.html
“Here are entered works that discuss collectively marriage between persons of different religions, religious denominations, races, and ethnic groups.”
Variants: Mixed marriage
Narrower terms: 
Interethnic marriage http://id.loc.gov/authorities/subjects/sh96009541
Interfaith marriage http://id.loc.gov/authorities/subjects/sh87002873
Interracial marriage http://id.loc.gov/authorities/subjects/sh85067499
Myös: 
Intercountry marriage http://id.loc.gov/authorities/subjects/sh85081520.html

kaksikulttuurinen avioliitto, kansainvälinen avioliitto, transnationaali avioliitto, transkulturaalinen avioliitto, ylirajainen avioliitto

**Comment by YSA-kokous** [comment]
Ei yhdistetä
