### ISSUE TITLE
Holokaustin kiistäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5446]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Holokaustin kiistäminen 

#### Ehdotettu termi englanniksi   

Holocaust denial 

#### Ehdotettu termi ruotsiksi   

Förintelseförnekelse 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh96009499> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. David Irvingin kirjat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

Useissa kirjastoissa esim. David Irvingin kirjat on jälkikäteen asiasanoitettu näin, ja huomasin että YSA:sta ei termiä löydy. 

**Ehdottajan nimi:** Harri Ollikainen 
**Ehdottajan sähköpostiosoite:** harri.ollikainen@protonmail.com **Termiehdotus Fintossa:** [Holokaustin kiistäminen](http://finto.fi/yse/fi/page/Y505446)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by satuniininen** [comment]
Löysin yhden Melindasta: Cultures of denial : comparing Holocaust and Armenian genocide denial / Maria Karlsson.

Kannatan ottamista: selkeä, vakiintunut ja ilmaisuvoimainen käsite.

**Comment by mariaforsen** [comment]
Sv. ET förintelseförnekelse ET förintelseförnekande ET förnekandet av förintelsen
