### ISSUE TITLE
vanhat talot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5447]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vanhat talot 

#### Vaihtoehtoiset termit ja ilmaisut   

kulttuurihistorialliset rakennukset 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Termi olisi löydettävyyden kannalta hyvä. "Kulttuurihistorialliset rakennukset" -termi on sinänsä ihan hyvä, mutta maallikolle ehkä vieras termi ja myös juhlavalta kuulostava. Moni tiedonhakija ei ehkä miellä, että 1950-luvulla rakennettu rintamamiestalo on kulttuurihistoriallinen rakennus (ainakin siinä mielessä, että rintamamiestalot huomioidaan kuntien kulttuuriympäristöohjelmien rakennuskantaluettelointia tehtäessä). Vertaa termit "vanhat autot" ja "vanhat moottoripyörät" - niidenkään kohdalla ei ole määritelty, mikä on "vanha". Olen toisinaan käyttänyt huomautuskentässä ilmausta "vanhat talot". Ilmaus kattaa Maalla-lehden artikkelitarjonnan aika kattavasti. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Maalla-lehti (ja muut samantyyppiset lehdet, joissa tyypillisesti vanhan talon korjannut asukas esittelee kotinsa) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [vanhat talot](http://finto.fi/yse/fi/page/Y505447)

**Comment by mirmaid** [comment]
Ei Melindassa eikä Artossa asiasanana.

**Comment by satuniininen** [comment]
Jos otetaan niin mieluummin muodossa _vanhat rakennukset_, jotta kattaisi useampia rakennustyyppejä kuin (asuin)talot.

**Comment by LeKorsu** [comment]
Kun kerran on jo vanhat autot, kirjat, metsät ja tanssit niin mikä ettei vanhat rakennuksetkin.

**Comment by YSA-kokous** [comment]
Jätetään termiehdotukseksi.

**Comment by AuHo22** [comment]
Tarvitsisin teoksessa Rakas, vanha talo : Pohjolan charmia / Frida Steiner. -> 
On nykyisin vähän samankaltainen harrastus kuin vanhat autot, ja niitä remontoidaan, sisustetaan & niissä viihdytään.
LT asuinrakennukset (erotuksena kulttuurihistoriallisiin rakennuksiin, joita eivät aina ole). Ryhmät 94 ja 91

**Comment by mirmaid** [comment]
_Vanhat talot_ käytetty 37 kertaa Melindassa. _Vanhat rakennukset_ ei käytetty, mutta on toki vähän kattavampi.

**Comment by ilona-x** [comment]
YLEllä aiheena **vanhat rakennukset** https://yle.fi/aihe/t/18-279507

**Comment by mariaforsen** [comment]
On kieltämättä vaikeaa kuvailla ilman omaa termiä, kannatan.

**Comment by mirmaid** [comment]
Vanhat rakennukset KT vanhat talot

**Comment by mariaforsen** [comment]
Sv. gamla byggnader HT äldre byggnader, gamla hus
