### ISSUE TITLE
ajoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5449]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ajoitus](http://www.yso.fi/onto/ysa/Y101911) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

YSOssa ajoitus (historia) (esim. iänmääritys) ja ajoitus (suunnittelu) 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Voisikohan ajoitus (historia) -merkitykseen riittää vain KÄ iänmääritys https://fi.wikipedia.org/wiki/I%C3%A4nm%C3%A4%C3%A4ritys?

Suunnittelu sopii usein tarkenteeksi, mutta ei ole aina aivan toimiva, esim. _Adaptation to northern conditions at flowering time genes in Arabidopsis lyrata and Arabidopsis thaliana_ tai _Jalkojen voima, iskun voima ja melonnan ajoitus nuorilla ja kokeneilla melojilla melontaergometrissa_.

**Comment by mariaforsen** [comment]
ALLFO: ajoitus (historia)=datering, ajoitus (suunnittelu)=timing Eli KS:n mukaisesti tehty:
1. määrittää jnk synty- t. esiintymisaika, iätä
2. suunnitella t. valita jnk ajankohta t. kestoaika

Datering on vaikeaa korvata "åldersbestämning:illä", ei ole aina kysymys siitä että olisi esim. jokin esine, jonka ikä halutaan tietää. Ks. myös Nationalencyklopedin. Näin todettu jo aikaisemminkin ja jako tehtiin osittain siitä syystä että datering on paljon käytetty ja tarvittu. 

Yllä mainittuihin kukka ja melonta-tapaukseen sopii melko huonosti ruotsin osalta (mutta onko tarpeen kuvailla ihan niin tarkasti...)

**Comment by mirmaid** [comment]
Wikipedian suomenkielisen _iänmääritys_-sivun ruotsinkielinen vastine on nimenomaan _datering_. "Iänmääritys eli ikäys tarkoittaa eliön, esineen tai ilmiön alkamishetken määrittämistä sen nykytilan avulla. Eri iänmäärityksen alalajeja: Elävien eliöiden iänmääritys, Historiallisten esineiden ja rakennusten iänmääritys, Fossiilien iänmääritys, Geologinen iänmääritys, Radiometrinen eli radioaktiivinen iänmääritys, Tähtitieteellinen iänmääritys, kuten kaikkeuden, tähtien ja aurinkokunnan ikä."

**Comment by mirmaid** [comment]
Ilmeisesti ruotsiksi on pakko olla eri termit elävien olentojen iänmääritykselle ja ajoitukselle? Suomeksi iänmääritys voi tarkoittaa nähtävästi kumpaa tahansa. Silloin varmaankin pitäisi jakaa _iänmääritys (ajoitus)_ (tai toisinpäin) ja iänmääritys (elävät ihmiset ja eläimet - ilmaistuna jollain järkevällä tavalla)...

**Comment by mariaforsen** [comment]
Nämä käytetään ruotsiksi eri asiayhteyksissä, tämän mukaan:
-fastställande av tillkomsttiden för någonting (datering) > keskiössä ei ole se kuinka vanha jokin asia on nyt (ei ole välttämättä olemassa enää), vaan milloin on alkanut/syntynyt...
-fastställande av åldern hos ngn eller ngt (åldersbestämning)  > keskiössä on kuinka vanha joku tai jokin nyt olemassa oleva on nyt

Erikieliset sivut Wikipediassa menevät useinkin väärin.

**Comment by ilona-x** [comment]
SAO:
Ämnesord: **Arkeologisk datering**
Anmärkning: Tidigare Datering - arkeologi. Ändrat 2007-09-13. Tidigare även Åldersbestämning. Ändrat  2017-01-13.

LCSH: Archaeological dating

Används ej: 
Datering- arkeologi
Kronologi- arkeologi
Åldersbestämning

Underordnad term : 
Optisk stimulerad luminiscensdatering 
 Termoluminiscensdatering


Ämnesord: **Åldersbedömning**

LCSH: Human beings - Age determination
Används ej: Medicinsk åldersbedömning

**Comment by mirmaid** [comment]
Arkeologiaan rajaaminen sulkisi pois osan käyttötapauksista, mutta voisi kyllä olla laajemmin _ajoitus (iänmääritys)_, jolloin tätä ei varmaankaan (?) käytettäisi elävien (tai juuri kuolleiden) olentojen iän päättelemisestä, tai sitten entinen _ajoitus (historia)_ KT iänmääritys (ajoitus) yms. ohjaustermejä - jos tarkenne historia ymmärretään varmasti niin että se kattaa kaiken alkuräjähdyksestä eteenpäin?

Toinen iänmääritys olisi kenties _iänmääritys (biologia)_, jos tämä ymmärrettäisiin niin että se tarkoittaa ko. eliön ikää syntymästä eteenpäin korkeintaan kuolemaan asti, eikä ammoin kuolleen eliön eksistenssin kestoa maapallolla?

Toinen ajoitus sitten _ajoitus (suunnittelu)_, tai _ajoitus (ajan valinta)_ tms.

**Comment by mirmaid** [comment]
Eli viimeisin ehdotus:
- ajoitus (suunnittelu) TAI ajoitus (ajan valinta)
- iänmääritys (biologia)
- ajoitus (iänmääritys) TAI ajoitus (historia) TAI ajoitus (historia ja arkeologia)

**Comment by YSA-kokous** [comment]
iänmääritys (biologia)
ajoitus (historia)
ajoitus (suunnittelu)

**Comment by mariaforsen** [comment]
Sv. 
-åldersbestämning (biologi)
-datering (historia)
-timing
