### ISSUE TITLE
berserkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5451]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

berserkit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Berserkki 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/soturit 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [berserkit](http://finto.fi/yse/fi/page/Y505451)

**Comment by mariaforsen** [comment]
Sv. bärsärkar
