### ISSUE TITLE
tugeenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5452]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tugeenit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soturit](http://www.yso.fi/onto/yso/p25022) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/soturit 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Tugeenit 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [tugeenit](http://finto.fi/yse/fi/page/Y505452)

**Comment by jtuohini** [comment]
Onkohan _soturit_ hieman liian myönteinen LT-termi tälle (ainakin Wikipedian perusteella)? Ja LCSH-vastinekin on **Thugs (Indic criminal group)** [http://id.loc.gov/authorities/subjects/sh85135093], LT-suhteinaan _Brigands and robbers--India_ ja _Criminals--India_.

**Comment by mariaforsen** [comment]
Sv. thugs ET thaggers
