### ISSUE TITLE
hyönteistalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5456]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hyönteistalous 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kotieläintalous](http://www.yso.fi/onto/yso/p8872) 
[elintarviketuotanto](http://www.yso.fi/onto/yso/p15341) 
[maataloustuotanto](http://www.yso.fi/onto/yso/p783) 

#### Tarkoitusta täsmentävä selite   

hyönteisten kasvatus kaupalliseen tarkoitukseen, lähinnä ihmisten ruoaksi 

#### Perustelut ehdotukselle   

Aleksi-tietokannassa 5 tietuetta hakusanalla: hyönteistalou
Google: 9320 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Elintarvike ja Terveys -lehti 2017: 3, artikkelikokonaisuus otsikolla Hyönteismaatalous. Kirjoittajista Lauri Jyllilän opinnäytetyön nimi on "Hyönteistalous osana suomalaista alkutuotantoa" 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** aleksi@btj.fi **Termiehdotus Fintossa:** [hyönteistalous](http://finto.fi/yse/fi/page/Y505456)

**Comment by mirmaid** [comment]
Ei Melindassa. 
https://github.com/Finto-ehdotus/YSE/issues/4395

**Comment by LeKorsu** [comment]
Sanoman arkistosta tulee 13 osumaa hyonteistalous-sanalla, Alman arkistosta alle 10. Ei vielä kovin yleinen, mutta vakiintuva termi siis.

**Comment by mariaforsen** [comment]
Ei vakiintunut ruotsiksi.

**Comment by mariaforsen** [comment]
Sv. "insektsekonomi" -> ei hyväksytty
