### ISSUE TITLE
Bronfenbrennerin ekologinen teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5457]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Bronfenbrennerin ekologinen teoria](http://www.yso.fi/onto/ysa/Y185974) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YLÄKÄSITE kasvatusteoriat
KUULUU RYHMÄÄN 37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus
--> ryhmän vaihto 

#### Perustelut ehdotukselle   

Ryhmä 37 ei liene oikea... 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by mirmaid** [comment]
Korjattu.
