### ISSUE TITLE
psykoakustiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5458]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

psykoakustiikka 

#### Ehdotettu termi ruotsiksi   

psykoakustik 

#### Ehdotettu termi englanniksi   

psychoacoustics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kuulontutkimus](http://www.yso.fi/onto/yso/p15121) 

#### Assosiatiiviset (RT)   

[äänet](http://www.yso.fi/onto/yso/p4572) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Psykoakustiikka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Systemaattinen päättely asteikkoteoriassa / Juhani Syrjälä, Pro gradu -tutkielma : Jyväskylän yliopisto, Musiikin, taiteen ja kulttuurin tutkimuksen laitos, 2017 

#### Perustelut ehdotukselle   

Psykoakustiikka (englanniksi psychoacoustics) on tieteenala, joka tutkii ihmisen kuuloa subjektiivisesti eli miltä se kuulostaa kuuntelijan mielestä. Aihetta on vaikea kuvailla YSA:n nykyisin termein. 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi **Termiehdotus Fintossa:** [psykoakustiikka](http://finto.fi/yse/fi/page/Y505458)

**Comment by jtuohini** [comment]
LCSH-vastine **Psychoacoustics** [http://id.loc.gov/authorities/subjects/sh85108410].

**Comment by mirmaid** [comment]
FinMeSHissä. Melindassa 21 viitettä.

**Comment by mariaforsen** [comment]
Sv. psykoakustik
