### ISSUE TITLE
puristelasi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5459]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puristelasi 

#### Ehdotettu termi englanniksi   

pressed glas 

#### Ehdotettu termi ruotsiksi   

pressad glas 

#### Perustelut ehdotukselle   

Puristelasi on ns. köyhän miehen kristallia. Ei oikeaa kristallia, vaan kristallin näköistä halvempaa puristelasia, jonka valmistustapa on erilainen kuin kristallin. Kristallilasi-termiä ei puristelasin yhteydessä oikein voi käyttää. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[30 Kemianteollisuus. Keraaminen teollisuus. Lasiteollisuus. Muoviteollisuus. Kumiteollisuus](http://www.yso.fi/onto/yso/p26530) 
[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi:jyu-201708133465 

#### Vaihtoehtoiset termit ja ilmaisut   

kristallilasi 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi **Termiehdotus Fintossa:** [puristelasi](http://finto.fi/yse/fi/page/Y505459)

**Comment by jtuohini** [comment]
LCSH-vastine **Pressed glass** [http://id.loc.gov/authorities/subjects/sh85106527].

_Kristallilasi_ on varmaankin tarkoitettu tässä RT-suhteiseksi, ei KT-muodoksi, kun se on jo omana YSA-terminään [http://www.yso.fi/onto/ysa/Y109609]?

**Comment by mirmaid** [comment]
Melindassa 8 viitettä. Ollut MAO-ontologiassa, mutta poistettu?

**Comment by mariaforsen** [comment]
Sv. pressglas ET pressat glas
