### ISSUE TITLE
johtomotiivi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5460]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

johtomotiivi 

#### Ehdotettu termi ruotsiksi   

ledmotiv 

#### Ehdotettu termi englanniksi   

leading motif 

#### Ehdotettu yläkäsite YSOssa (LT)   

[motiivit](http://www.yso.fi/onto/yso/p3402) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Tarkoitusta täsmentävä selite   

Toistuva keskeinen motiivi teoksessa. (Hosiaisluoma) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka bib1231396 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [johtomotiivi](http://finto.fi/yse/fi/page/Y505460)

**Comment by asormune** [comment]
Musiikissa: johtoaihe

**Comment by mirmaid** [comment]
Melindassa 3 viitettä, joissa termi _johtoaiheet_.

**Comment by mirmaid** [comment]
Ei Artossa, eikä Helkassa esimerkkiaineiston _Nuori Sillanpää: tappion ja hyvityksen johtomotiivi F.E. Sillanpään elämässä ja tuotannossa vuosina 1908-1917 sekä Jälkilause_ kuvailussa.

**Comment by mariaforsen** [comment]
MOT: johtomotiivi = johtoaihe

**Comment by OutiHintikka** [comment]
Johtomotiivi voi olla myös esine tyyliin päällystakki, seitsemän miehen saappaat jne.? Onko tämä tuolloin aihe?

**Comment by YSA-kokous** [comment]
Kristiina selvittää, seuraava kokous.

**Comment by krinay** [comment]
Kirjallisuudentutkimuksessa käytetään yleensä termiä johtomotiivi, ei termiä johtoaihe. Se on varsin keskeinen käsite kirjallisuudentutkimuksessa, vaikkei sitä toistaiseksi ole käytetty sisällönkuvailussa Melindassa tai Artossa. Jos termi otetaan, se voisi olla monikossa kuten YSA-termit motiivit, aiheet ja teemat.

**Comment by jtuohini** [comment]
Tarvitaan kenties erillinen asiasana **johtoaiheet**, jolla voi kuvailla varsinkin Richard Wagnerin oopperoissaan harrastamalleen ja muidenkin käyttämälle sävellystekniikalle, jossa eri asioille ja näyttämöhahmoille annetaan omat musiikilliset motiivinsa eli tunnistettavat sävelaiheet. [https://fi.wikipedia.org/wiki/Johtoaihe]
 
Eli ei voi tehdä suoranaista KT/KÄ-rinnastusta ehdotettujen asiasanojen **johtoaiheet** ja **johtomotiivit** välille!

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5876

**Comment by AuHo22** [comment]
Tehdään paljon kaunon kuvailua, ja keskusteltiin siitä, että aiheet, motiivit, teemat täytyy erottaa toisistaan, kuten ne ovat nytkin, muttemme välttämättä tarvitse johtomotiivit -termiä (tai muutakaan johto-alkuista termiä). Tämä siis kirjallisuuden näkökulmasta.

**Comment by YSA-kokous** [comment]
johtomotiivit (kerronta)

**Comment by mariaforsen** [comment]
Sv. ledmotiv (berättande)

**Comment by mirmaid** [comment]
Johtoaiheesta tai -motiivista voidaan puhua myös muiden taiteenlajien yhteydessä. Mitä ryhmiä laitetaan ja onko kerronta riittävän laaja tarkenne?

**Comment by AuHo22** [comment]
Johtomotiivit (kerronta) toiminee muilla alueilla paitsi ehkä musiikissa, kuvataiteessa tullee harvemmin vastaan, mutta taiteilijan kokonaistuotannosta puhuttaessa voinee nähdä läpi tuotannon kulkevana toistuvana aiheena - riittäisikö silloin pelkkä motiivit?

**Comment by jtuohini** [comment]
"Johtomotiivi"-käsitettä ei tarvita musiikissa ollenkaan! Asiasana sillä puolella on **johtoaiheet**, LT nähtävästi _sävelmotiivit_ ja RT pelkkä _motiivit_. Eli **johtomotiivit (kerronta)** on varmasti ihan hyvä asiasana kirjallisuuteen yms.

**Comment by mirmaid** [comment]
YSAan on nyt siis auktorisoitu _johtoaiheet (musiikki)_. Otetaanko lisäksi ehdotettu _johtoaiheet (kerronta)_? Entä kuvataide? Kerronta tuskin soveltuu silloin tarkenteeksi. 

Jos kuvataiteen yhteydessä riittää pelkkä _motiivit_ (mahdollisesti sekin tarkenteella varustettuna), tarvitaanko kirjallisuuden tai muun kerronnan yhteydessäkään johtomotiivit-termiä?

**Comment by AuHo22** [comment]
Alkuperäinen kysymys taisi olla se, otetaanko termi johtomotiivit aiemmasta kirjallisuudentutkimuksen sanastosta. Mielestäni johtoaiheet (kerronta) on alkuperäisestä ajatuksesta aika kauas liikkunut sanaväännös, jolle ei ole tarvetta eikä perusteita. Vrt. SKS:n maininta aiemmin: "Kirjallisuudentutkimuksessa käytetään yleensä termiä johtomotiivi, ei termiä johtoaihe".  Johtoaiheet (kerronta) tarkoittanee samaa kuin motiivit kerronnassa, eli siinä toistuvaa aihetta. BTJ:n pitkäaikaisten kuvailijoiden kanta oli aiemminkin se, että ainakin me pärjäämme edelleen ilman johtomotiivit-termiä, eli aiheet, motiivit, teemat riittävät. Mutta johtomotiivit ei ole korvattavissa johtoaiheet (kerronta)-termillä.
