### ISSUE TITLE
haasteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5466]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[haasteet](http://www.yso.fi/onto/ysa/Y169096) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa tarkenne (haastavat tilanteet) 

#### Perustelut ehdotukselle   

Sanastossa on myös haasteet (oikeustiede). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindassa muutamia viitteitä oikeustiede-merkityksessä, n. 400 kertaa haastavista asioista. _Haastavat tilanteet_-tarkenne sopii usein, mutta aina kyse ei ole tietystä tilanteesta vaan pitkäkestoisesta hankaloittavasta seikasta ehkä hyvinkin laajassa kontekstissa (hyvinvointivaltion haasteet), ja joskus haastava tilanne tuntuu vähän liioittelulta (_Tämä ei ole kirja: sähkökirjan valtavirtaistumisen haasteet_). Negatiivisesta sävystä huolimatta voisi ainakin miettiä myös vaihtoehtoja _(vaikeudet)_ tai _(ongelmat)_.

**Comment by YSA-kokous** [comment]
haasteet (ongelmat)
