### ISSUE TITLE
linssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5467]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[linssit](http://www.yso.fi/onto/ysa/Y103171) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa tarkenne (optiikka) 

#### Perustelut ehdotukselle   

Sanastossa myös linssit (hernekasvit). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by PaiviLipsanen** [comment]
linssit (suku - Lens)
linssi - rokkalinssi - kylvövirvilä (Lens culinaris)
https://fi.wikipedia.org/wiki/Kylv%C3%B6virvil%C3%A4
https://laji.fi/taxon/MX.38990

Linssin siemeniä käytetään ravintona.

Melindan viitteet käsittelevät lähinnä linssejä (optiikka). Helkassa on jonkin verran linssiä/linssejä kasveina käsittelevää aineistoa.

**Comment by YSA-kokous** [comment]
linssit (optiikka) ja linssi (hernekasvit)
