### ISSUE TITLE
kirjanpainajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5469]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kirjanpainajat](http://www.yso.fi/onto/ysa/Y105981) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsee tarkenteen 

#### Perustelut ehdotukselle   

Sanastossa myös kirjanpainaja (kaarnakuoriaiset). Ei tarkennetta myöskään YSOssa. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by YSA-kokous** [comment]
kirjanpainajat (ammatit)
