### ISSUE TITLE
energiankulutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5471]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[energiankulutus](http://www.yso.fi/onto/ysa/Y95056) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsisi tarkenteen 

#### Perustelut ehdotukselle   

Sanastossa myös energiankulutus (aineenvaihdunta). Ei tarkennetta myöskään YSOssa, vaikea löytää sopivaa. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by ilona-x** [comment]
energiankulutus (energiavarat?)
energiankulutus (energialähteet?)
energiankulutus (luonnonvarat?)

**Comment by satuniininen** [comment]
_Energiankulutus (luonnonvarat)_ olisi näistä varmaan erottelukykyisin suhteessa kaimaansa _energiankulutus (aineenvaihdunta)_. Huonoiten se sopii aineistoihin, joissa käsitellään yksittäisten sähkölaitteiden energiankulutusta, mutta näissä muutenkin pitäisi mieluummin olla _sähkönkulutus_.

**Comment by mirmaid** [comment]
Ensimmäisistä sadasta viitteestä Melindassa _energiavarat_-käsitettä oli käytetty kerran viittaamaan aineenvaihduntaan, _energialähteet_ ei kertaakaan, joten nekin ovat luultavasti melko toimivia tarkenteita.

Samoissa tietueissa nämä esiintyvät seuraavasti:
energiankulutus & luonnonvarat 167 kertaa
energiankulutus & energiavarat 123 kertaa
energiankulutus & energialähteet 454 kertaa

Yksi uusi ehdotus vielä _energiankulutus (energiateknologia)_ (Melindassa 81 kertaa samoissa viitteissä). https://fi.wikipedia.org/wiki/Energiatekniikka

**Comment by YSO-kokous** [comment]
Hyväksytään muoto "energiankulutus (energiateknologia)".
