### ISSUE TITLE
metsäohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5472]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsäohjelmat 

#### Ehdotettu termi englanniksi   

forestry programmes 

#### Ehdotettu termi ruotsiksi   

skogsprogram 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ohjelmat (suunnitelmat)](http://www.yso.fi/onto/yso/p8021) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Perustelut ehdotukselle   

AFOssa, Melindassa asiasanana 40 viitteessä. On olemassa myös alueellisia metsäohjelmia, sekä kaksi kansallista; Kansallinen metsäohjelma 2010 ja Kansallinen metsäohjelma 2015 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melindan ja Arton aineistot 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [metsäohjelmat](http://finto.fi/yse/fi/page/Y505472)

**Comment by mariaforsen** [comment]
Sv. skogsprogram
