### ISSUE TITLE
markkinat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5473]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[markkinat](http://www.yso.fi/onto/ysa/Y97293) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa markkinat (taloustiede) 

#### Perustelut ehdotukselle   

Sanastossa lisäksi markkinat (tapahtumat). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
Lisätään sulkutarkenne
