### ISSUE TITLE
mittarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5474]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mittarit](http://www.yso.fi/onto/ysa/Y97475) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa tarkenne (mittaus); LT molemmissa sanastoissa mittauslaitteet, mutta termiä käytetään myös abstraktimmassa merkityksessä. 

#### Perustelut ehdotukselle   

Sanastossa myös mittarit (perhoset). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by tpalonen** [comment]
Käsitteen merkitystä ja merkityseroa mittauslaitteet-käsitteeseen valottava huomautus voisi olla paikallaan?

**Comment by mirmaid** [comment]
http://www.fsd.uta.fi/menetelmaopetus/mittaaminen/mittaaminen.html

**Comment by mirmaid** [comment]
Oikeastaan mittarit pitäisi olla mittauslaitteiden yläkäsite?

**Comment by ilona-x** [comment]
YSAssa mittauslaitteiden ohjausterminä nyt mittarit (mittauslaitteet) eli pitäiskö tämän käsittelyssä olevan mittarit-termin kattaa vain nuo abstraktimmat mittarit? 

mittarit (tunnusluvut/indikaattorit/..?)

Kielitoimiston sanakirja:
mittari
1. itsetoimiva mittauslaite. Digitaalinen, analoginen mittari. Jäähdytysveden lämpötilan mittari. Lentokoneen mittarit. Mittarin lukeminen. Korkeus-, nopeus-, matka-, ilmanpainemittari. Ampeeri-, volttimittari. Taksamittari.
Kuv. Testit koulukypsyyden mittarina. Lapsikuolleisuus elinolojen mittarina.
2. mittaaja. Maanmittari.
3. Mittarit hentoruumiisia leveäsiipisiä perhosia, joiden toukat liikkuvat tarttumalla alustaan vuoroin etu-, vuoroin takaruumiillaan. Mänty-, tunturimittari.

**Comment by mirmaid** [comment]
^ Varmaan molemmat ratkaisut ovat mahdollisia: joko laajempi merkitys _mittarille_ jolloin _mittauslaitteet_ on alakäsite, tai tarkenteella rajaaminen. Edellä mainitun linkin takaa: _Mittarin täytyy olla kohteeseensa sopiva: kirjevaa'alla ei voida mitata henkilöiden painoja. Kunnan varallisuuden ja vanhuksista huolehtimisen arviointiin ei voida käyttää samaa mittaria._

Itselleni ei ole tullut mieleen hyvää sulkutarkennetta (indeksi/indikaattori on ehkä liian rajaava, jos tulkitaan että testi voi olla mittari, eikä vain testitulos). Siksi ehkä kallistuisin laajempaan tulkintaan.

**Comment by satuniininen** [comment]
Itse en näen _mittareiden_ ja _mittauslaitteiden_ välillä oikein minkäänlaista suhdetta. Tällä hetkellä ne ovat YSOssakin aivan eri haaroissa, _mittauslaitteet_ laitteiden alla ja _mittarit (mittaus)_ käyttöön liittyvässä roolissa samoin kuin _indikaattorit_. _Metronomit_ sen sijaan voisi siirtää pois mittarien alta ja ehkä miettiä mittarien, indikaattorien ja tunnuslukujen suhdetta toisiinsa.

Mitä sulkutarkenteeseen tulee niin epäilen että parempaa kuin (mittaus) on tuskin löydettävissä. Muotoa _mittarit (mittaus)_ on käytetty Melindassa 150 kertaa ja hyvin yhtenäisesti nimenomaan abstraktien mittareiden yhteydessä.

**Comment by YSA-kokous** [comment]
YSO: metronomit YK mittauslaitteet
