### ISSUE TITLE
paino

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5475]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[paino](http://www.yso.fi/onto/ysa/Y106876) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tällä ohjausterminä paino (fysiikka). YSOssa tarkenne (fysiikka). 

#### Perustelut ehdotukselle   

Sanastossa myös paino (kielitiede). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
Lisätään tarkenne
