### ISSUE TITLE
sinkki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5476]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sinkki](http://www.yso.fi/onto/ysa/Y98859) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa tarkenne (raskasmetallit). 

#### Perustelut ehdotukselle   

Sanastossa myös sinkki (soittimet). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
Lisätään sulkutarkenne.
