### ISSUE TITLE
itsenäistyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5477]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itsenäistyminen](http://www.yso.fi/onto/ysa/Y101898) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tällä ohjausterminä itsenäistyminen (politiikka). YSOssa tarkenne (valtiot ja yhteisöt). 

#### Perustelut ehdotukselle   

Sanastossa myös itsenäistyminen (psykologia). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Voisiko oikeastaan olla vain _itsenäistyminen (valtiot)_? Jonkin muun organisaation itsenäistyminen on kuitenkin aika eri asia.

**Comment by YSA-kokous** [comment]
itsenäistyminen (valtiot)

**Comment by mariaforsen** [comment]
Sv. självständighetsprocess (stater)
