### ISSUE TITLE
messu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5478]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[messu](http://www.yso.fi/onto/ysa/Y97371) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tällä ohjausterminä messut (jumalanpalvelus). YSOssa tarkenne (jumalanpalvelus). 

#### Perustelut ehdotukselle   

Sanastossa myös messut (musiikki). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by YSA-kokous** [comment]
messu (jumalanpalvelus)
