### ISSUE TITLE
messut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5479]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[messut](http://www.yso.fi/onto/ysa/Y103488) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tällä ohjausterminä messut (kauppa). YSOssa tarkenne (tapahtumat). 

#### Perustelut ehdotukselle   

Sanastossa lisäksi messut (musiikki). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by OutiHintikka** [comment]
Entä kristilliset messut?
Helsingin seurakunnat - Helsingin seurakunnat - Hartaudet & messut https://www.helsinginseurakunnat.fi/messut/saannollisethartaudetjamessut_0.html

**Comment by YSA-kokous** [comment]
messut (tapahtumat)
