### ISSUE TITLE
kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5480]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kieli](http://www.yso.fi/onto/ysa/Y106930) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisättävä tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös kieli (ruumiinosat) ja monikollinen kielet. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Käsitellään ensin ehdotus yksikön ja monikon yhdistämisestä https://github.com/Finto-ehdotus/YSE/issues/5842
