### ISSUE TITLE
subjekti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5481]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[subjekti](http://www.yso.fi/onto/ysa/Y103048) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjausterminä subjekti (kielitiede). YSOssa tarkenne (lauseenjäsen). 

#### Perustelut ehdotukselle   

Sanastossa myös subjekti (filosofia) ja subjekti (kirjallisuudentutkimus). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Ruotsiksi nyt tarkenne (språkvetenskap) joka on samalla tasolla kuin (filosofi) ja (litteraturvetenskap), mutta toki (satsdel) olisi tarkempi (eikö pitäisi kuitenkin olla monikossa, meidän periaatteiden mukaisesti?)

**Comment by YSA-kokous** [comment]
subjekti (lauseenjäsenet)
