### ISSUE TITLE
verkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5482]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkot](http://www.yso.fi/onto/ysa/Y102127) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa: verkot (tekniset järjestelmät) ja verkot (elottomat objektit). Ketjut jaettu YSAssa ketjut (esineet) ja ketjut (järjestelmät). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa _kalaverkot_ erikseen. Melinda 2 x verkot – kudonta. 

Toisaalta sähköverkko: toisiinsa liitetyistä sähköjohdoista ja muista sähkölaitteista muodostettu sähkön siirtoon t. jakeluun tarkoitettu kokonaisuus – osa verkoista on konkreettisempia kuin toiset, esim. vesijohtoverkot vs. tietoliikenneverkot, onko vesijohtoverkko tai sähköverkko enemmän kuin kalaverkko vai enemmän kuin tietoliikenneverkko?

**Comment by mariaforsen** [comment]
Eli nyt kai jaettu KS:n 1. ja 2.-merkitysten mukaan, mutta ovatko tarkenteet tarpeeksi selvät (molemmat kai jossain määrin "elottomia") Minusta "verkot (esineet/objektit)" ja "verkot (järjestelmät)" olisi selkeämpi käyttäjälle. Alakäsitteidenkin osalta sopisi.

**Comment by YSA-kokous** [comment]
verkot (esineet), verkot (järjestelmät)
