### ISSUE TITLE
jälkihoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5483]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jälkihoito](http://www.yso.fi/onto/ysa/Y108555) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa jälkihoito (kunnossapito) ja jälkihoito (terveyteen liittyen). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Tarvitaanko kaksi erillistä termiä/käsitettä? Ruotsiksi molemmat eftervård. Vrt. _hoito_.

**Comment by AuHo22** [comment]
Myös termi jälkikäsittely olemassa, joka on aika lähellä jälkihoito (kunnossapito) termiä.

**Comment by mariaforsen** [comment]
Ruotsin osalta ei ainakaan tarvita. Sanastossa myös jälkikäsittely=efterbehandling (se sopii esineille yms.).

**Comment by YSA-kokous** [comment]
Yhdistetään.
