### ISSUE TITLE
tunnustus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5484]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tunnustus](http://www.yso.fi/onto/ysa/Y121199) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa tunnustus (uskonto) ja tunnustus (myöntäminen). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindan viitteissä on sekä rikoksen tms. tunnustaminen (confession), että tunnustuksen antaminen/saaminen (recognition). Molempia voidaan ajatella myöntämisenä, mutta pitäisikö ne kuitenkin kuvailussa erottaa?
https://kirjasto.jyu.fi/kauppa/tuotteet/tunnustus-subjektiviteetti-ja-inhimillinen-elamanmuoto

Uskonnon yhteydessäkään kyse ei välttämättä ole uskon tunnustamisesta, vaan tunnustuksen antamisesta/saamisesta uskonnon kontekstissa (eettis-filosofisena kysymyksenä), esim. _Recognition and religion: a historical and systematic study_. Sanastossa on myös termi _uskontunnustukset_.

Ikävä kyllä näyttää siltä, että myös _tunnustuksellisuus_-sanaa on alettu käyttää muussakin kuin uskonnon yhteydessä.

**Comment by mariaforsen** [comment]
ALLFO: bekännelse (religion),  erkännande. Bekännelse voi viitata molempiin, mutta erkännande käytetään kyllä rikoksista yms. (tosin sekin voi olla monimerkityksinen, joten tarkenteen lisääminen voisi olla hyvä) 

Tunnustuksellisuus=konfessionalism, joten toivottavasti pidetään kiinni alkuperäisestä merkityksestä (uskonto)

**Comment by mirmaid** [comment]
_Uskonto_ on sikäli siis tarkenteena ongelmallinen, että uskontunnustus (confession of faith) on (mielestäni) eri käsite kuin tunnustus (recognition), mutta myös tätä jälkimmäistä voidaan käsitellä uskonnon kontekstissa. Eli jos mahdollista niin tyytyisin termiin _uskontunnustukset_ (KT tunnustus (uskonto)). 

Edelleen sen jälkeen jää rajattavaksi confession/recognition.

**Comment by mariaforsen** [comment]
Eli sanastoon jäisi: tunnustus (myöntäminen) vai pelkkä tunnustus?

**Comment by OutiHintikka** [comment]
Itse kaikesta huolimatta kannattaisin YSOn jakoa tunnustus (uskonto) ja tunnustus (myöntäminen).

**Comment by mariaforsen** [comment]
Ruotsin osalta en sekoittaisi uskonnollista hyväksymistä tähän, se vaatisi taas uuden termin.

**Comment by mirmaid** [comment]
^ Ongelma on vaan se, että tarkenteella _tunnustus (uskonto)_ se sekoittuu väistämättä...

**Comment by mirmaid** [comment]
Mutta siis jos merkityksessä _confession of faith_ ei riitä _uskontunnustukset_ niin sitten vaikka _uskon tunnustaminen_? (tätä ei siis voi automaattisesti korjata tietueisiin joissa on nyt tunnustus + uskonto)

Joissakin viitteissä sopii _valtion tunnustaminen_

**Comment by YSA-kokous** [comment]
Korjataan _valtion tunnustaminen_-viitteet.
Otetaan _uskon tunnustaminen_, siivotaan viitteet.

Loput seuraava kokous.

**Comment by satuniininen** [comment]
Korjattu seuraavat: 

tunnustus --> **uskon tunnustaminen**

tunnustus + valtiot --> **valtion tunnustaminen**
yli jäi teokset Tunnustetaanko Mussolinin hallitus ja The international politics of recognition 

aiemman osaamisen tunnustaminen osaksi opintoja --> **hyväksilukeminen**
ulkomaisen tutkinnon tunnustaminen --> **tutkintojen vastaavuus**
(näille voisi lisätä ohjaustermejä, jotta olisivat paremmin löydettävissä: tutkintojen vastaavuus KT tutkinnon tunnustaminen, tunnustus (tutkinnot) ja hyväksilukeminen KT opintojen hyväksilukeminen, ehkä jopa hyväksilukeminen RT **hyväksyminen (menettely)**)

yli jäi 107 + jokunen ketju, joissa seuraavat merkitykset:

- 46 x tunnustus/confession: rikoksen/syyllisyyden tunnustaminen, myös tosi-tv ja elämänkerrallinen tunnustaminen
 _Foucault and a politics of confession in education_ 

- 29 x tunnustus/recognition: tunnustuksen antaminen/saaminen/hakeminen, kontekstina työelämä, vähemmistöryhmien oikeudet yms
 _Identity : the demand for dignity and the politics of resentment_

- 8 x Isyyden/äitiyden tunnustaminen
_Äitiyden sääntely : Äitiyslakityöryhmän mietintö_

- 8 x tunnustus filosofisena käsitteenä
 _The philosophy of recognition :historical and contemporary perspectives
 Ihmisyyden rajat ja tunnustamisen politiikka :tunnustuksen teema Judith Butlerin filosofiassa_ 

- pari kertaa uskonnollinen hyväksyminen (religious recognition). Riittäisikö näihin hyväksyminen + jotain?
 _Recognition and religion : a historical and systematic study_ 

- muutama epäselvä tai useamman kuin yhden ylämainituista vaativa.

 


LCSH:ssa 
[Confession](http://id.loc.gov/authorities/subjects/sh85030904) --> syntien tunnustaminen
[Confession (Law)](http://id.loc.gov/authorities/subjects/sh85030912.html) --> rikoksen tunnustaminen
[Recognition (Philosophy)](http://id.loc.gov/authorities/subjects/sh92001089) --> filosofian tunnustus
[Recognition (Psychology)](http://id.loc.gov/authorities/subjects/sh85111840) --> tunnustuksen saaminen/antaminen
[Recognition (International law)](http://id.loc.gov/authorities/subjects/sh85111839) --> valtion tunnustaminen, mutta laajemmin myös hallinnon tms tunnustaminen
[Recognition (Ecumenical relations)](http://id.loc.gov/authorities/subjects/sh94008713) -->uskonnollinen hyväksyminen

**Comment by mariaforsen** [comment]
Mahdollisia vastineita ruotsiksi:

rikoksen/syyllisyyden tunnustaminen=erkännande av brott/skuld etc.

tunnustus/recognition: tunnustuksen antaminen/saaminen/hakeminen, kontekstina työelämä, vähemmistöryhmien oikeudet yms=erkännande? etc.

isyyden/äitiyden tunnustaminen=erkännande av faderskap/moderskap

tunnustus filosofisena käsitteenä
    The philosophy of recognition :historical and contemporary perspectives
    Ihmisyyden rajat ja tunnustamisen politiikka :tunnustuksen teema Judith Butlerin filosofiassa
=erkännande (filosofi)?

pari kertaa uskonnollinen hyväksyminen (religious recognition). Riittäisikö näihin hyväksyminen + jotain? mielestäni riittää!

**Comment by YSA-kokous** [comment]
tunnustus (vahvistaminen) 
tunnustaminen (filosofia)
syyllisyyden tunnustaminen
tunnustus (arvostus) KÄ arvostus

vanhemmuuden tunnustaminen/vahvistaminen, jos tarvitaan erikseen

**Comment by mariaforsen** [comment]
Sv.
-erkännande (bekräftelse)
-erkännande (filosofi) 
-erkännande av skuld ET erkännande av brott, bekännelse (skuld)
-erkänsla, erkännande (uppskattning) ANV uppskattning
-bekännelse av tro ET bekännelse (religion), bekännelse av religion
