### ISSUE TITLE
merkintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5485]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[merkintä](http://www.yso.fi/onto/ysa/Y110596) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenne (toiminta), koska sanastossa on myös monikollinen merkinnät-termi. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Sääntöjen mukainen muutos tarpeen, ellei voida yhdistää molempia muotoja? Monessa tapauksessa kävisi varmaan "merkinnät" tai muu tarkempi termi yhtä hyvin kuin merkintä, ks. Melinda.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
_Merkinnät_-muoto on ollut YSAssa vasta vuodesta 2014, ja se tosiaan soveltuisi viitteisiin usein _merkintä_-termin sijasta. Suomeksi olisi myös mahdollista muuttaa merkintä-termi yksiselitteiseen _merkitseminen_-muotoon; toisinaan _merkinnät_ ei aivan sovellu, esim. http://www.ahven.net/v2_tiedostot/186.pdf (ainakin joissakin tapauksissa voisi soveltua merkinnät-termin sijaan _merkit_).

**Comment by mariaforsen** [comment]
Ruotsin osalta taas yllä olevaan kalastusdokumenttiin sopisi sekä merkintä että merkinnät, ainakin paremmin kuin merkit=tecken.

**Comment by YSA-kokous** [comment]
merkinnät KT merkintä, merkitseminen
