### ISSUE TITLE
mallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5486]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mallit](http://www.yso.fi/onto/ysa/Y103395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty sulkutarkenne (tuotokset), koska sanastossa on myös mallit (ammatti) (YSO: mallit (ammatit)). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
_Roolimallit_ siirretty YSOssa > YK toimintaan liittyvä rooli.

**Comment by mirmaid** [comment]
Entä _mallit (mallintaminen)_?

**Comment by mirmaid** [comment]
Melindassa paljon korjattavaa, suuri osa viitteistä käsityökirjoja. Tätä ei ehkä ehditä käydä läpi ennen konversiota, onko siinä tapauksessa mahdollista poistaa tarkenne myös YSOsta konversion ajaksi ja lisätä uusi tarkenne ja korjata viitteet konversion jälkeen?

Paitsi jos saadaan automaattisesti jotain...

**Comment by ilona-x** [comment]
mallit (ammatti) käytetty Melindassa 38 kertaa, jos tarkenne poistetaan, pitää nuo varmaan myös muuttaa Melindaan muotoon "mallit"?

**Comment by mirmaid** [comment]
Voihan sitä toisaalta myös ajatella että _käsityömallitkin_ kuuluvat _mallit (mallintaminen)_ käsitteen alle. Mutta tosiaan tätä varmaan mahdollista työstää eteenpäin automatiikalla.

**Comment by YSA-kokous** [comment]
mallit (mallintaminen)
