### ISSUE TITLE
rajapinnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5487]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rajapinnat](http://www.yso.fi/onto/ysa/Y196613) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa: rajapinnat (pinnat) ja rajapinnat (tietokoneohjelmat). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by satuniininen** [comment]
Jako ja YSOn sulkutarkenteet OK

**Comment by mariaforsen** [comment]
Jako tarpeen myös ruotsin osalta: gränssnitt, gränsytor.
