### ISSUE TITLE
kaavat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5488]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kaavat](http://www.yso.fi/onto/ysa/Y95741) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa: kaavat (tieto) ja kaavat (käsityö). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Ruotsiksi eri vastineita: formler, mönster (handarbete), eli jako tarpeen.

**Comment by mirmaid** [comment]
kaavat (käsityö): edelleen tarkennettava yhdenmukaisuutta kielten välillä, koska suomeksi tämä ei kata neule- ym. töiden kuviomalleja

**Comment by mariaforsen** [comment]
Voisi periaatteessa olla mönster (sömnad) KT plaggmönster? Mutta muut tärkeät merkitykset (esim. neulonta, virkkaus, kirjonta) eivät saisi jäädä pois kokonaan (lisätäänkö sitten tarkempia termejä?) Tämä termi ei tosiaan toimi samalla tavalla ruotsiksi kuin suomeksi (vrt. esim. SAOn mönsterblad: Tecknade eller tryckta blad med mönster som användes som förebilder efter vilka  någonting kan tillverkas. Exempel omfattar klädsömnad, broderi och  mönster för snickeri och träslöjd.")

**Comment by asormune** [comment]
Yllä mainitaan: .. mönster för snickeri och träslöjd .. mutta ainakin soitinrakennuksen yhteydessä käytetään asiasanaa "tekninen piirustus". Rajataanko (vai ei) "kaavat" vain "pehmeille käsitöille".

**Comment by AuHo22** [comment]
Mielestäni _kaavat (käsityö)_ sisältävät yhtä lailla tietoa eli taas kerran saa lujasti miettiä, mitä _kaavat (tieto)_ -termillä halutaan ilmaista. Mitä ilmeisemmin ainakin alakäsitteitä tutkiessa kyseessä on luonnontieteelliset kaavat - eli voisiko tämän ilmaista selkeämmin YSOn kehityslinjausten mukaisesti vaikkapa sitten _kaavat (luonnontieteet)_, asemakaavoitus/-kaavat on sanastossa sitten jo erikseen.

"Sulkutarkenteeksi valitaan ensisijaisesti (jos mahdollista) termin yläkäsite ja noudatetaan yläkäsitteen muotoa -> esim. maantieto (oppiaineet). Jos yläkäsite ei riitä selventämään käsitteen merkitystä, valitaan tarkenteeksi aihealue, tieteenala tms.

**Comment by mirmaid** [comment]
**Uusia ehdotuksia:**

_kaavat ja mallit (käsityö)_
_kaavat (luonnontieteet)_ TAI tarkemmin _kaavat (matematiikka)_ jne.

**Comment by mariaforsen** [comment]
Kaavat (matematiikka) voi ainakin ruotsin osalta olla liian kapea (=tiettyä suhdetta, järjestystä tms. osoittava (kirjain- t. numero)merkintä.).

**Comment by YSA-kokous** [comment]
käsityömallit KT kaavat (käsityö)

Riittääkö toiseen YSAsta jo löytyvät matemaattiset kaavat, kemialliset kaavat?

**Comment by mariaforsen** [comment]
Kaavoja (sv. formler) voi ainakin ruotsiksi olla melkein millä tahansa alalla ja Melindassa onkin käytetty esim. rakennusalalla ja erilaisissa teknisissä asiayhteyksissä (johon ei käy matemaattiset tai kemialliset). 

Olisiko mahdollista pitää: "kaavat (formulat)"  
Kielitoimiston sanakirja: formula=1. kaava.

**Comment by satuniininen** [comment]
Käsityömalleista vielä: Yhdistelmää _käsityöt_ + _mallit_ on käytetty Melindassa 411 kertaa. Näihinkin voisi varmaan korjata _mallit_ --> _käsityömallit_?

**Comment by mirmaid** [comment]
YSAssa on nyt siis käsitöihin liittyen _ompelukaavat_ ja _käsityömallit_, sekä toisaalta kaavat (yhdyskuntarakenne) KÄ _kaavoitus_. 

Jäljellejääville ehdotettu: _kaavat (formulat), kaavat (tieto), kaavat (merkinnät)_

**Comment by satuniininen** [comment]
kaavat (kaaviot)?

Jos matemaattiset ja kemialliset kaavat saadaan ohjattua omiin käsitteisiinsä niin näitä tuskin jää kovin isoa joukkoa. Niihin voisi kaiken varalta lisätä vielä ohjaustermit kaavat (matematiikka) ja kaavat (kemia).

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjan mukaan kaavio = jtak kaavamaisesti, us. symbolein esittävä piirros, kaaviokuva. Alan pikkuhiljaa siedättyä tuohon _kaavat (formulat)_...

**Comment by mirmaid** [comment]
Vielä yksi: _kaavat (tieteet ja tekniikka)_

**Comment by YSA-kokous** [comment]
kaavat (tieteet ja tekniikka)
kaavat (kaavoitus) KÄ kaavoitus
