### ISSUE TITLE
subjektius

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5489]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[subjektius](http://www.yso.fi/onto/ysa/Y146244) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko eri asia kuin subjektiviteetti? YSA: Subjektiviteetilla tarkoitetaan ihmisen arvomaailmaa, arvioita omasta elämästään, tärkeitä elämänalueita jne. 

#### Perustelut ehdotukselle   

YSAssa on nyt sekä subjekti (filosofia), subjektius, subjektiviteetti, että subjektiivisuus. Ainakin Ronkainen: Ajan ja paikan merkitsemät : subjektiviteetti, tieto ja toimijuus käsittelee subjektiutta ja subjektiviteettia synonyymeinä. 

#### Ehdottaja   

Mirja 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Filosofian sanakirja?

**Comment by AuHo22** [comment]
Lieneekö eroa tieteenalojen lähestymistavoissa - subjektiviteetti käytetty perinteisesti filosofiassa (02), subjektius saanut alaa yhteiskuntatieteiden terminä, sanastoissa 00? Voiko subjektiviteetti sanaa kuitenkaan käyttää aina subjektius-sanan synonyymina?

**Comment by mariaforsen** [comment]
Ruotsin osalta myös subjektiviteetti ja subjektiivisuus aiheuttavat ongelmia. Molemmat ovat subjektivitet ja molemmat ovat luokassa 02. Käytetäänkö nyt todella näitä kaikkia johdonmukaisesti Melindassa?

**Comment by YSA-kokous** [comment]
subjektius KÄ subjektiviteetti
