### ISSUE TITLE
symbaali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5490]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[symbaali](http://www.yso.fi/onto/ysa/Y103262) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Joko [1] muutetaan muotoon "lautanen (lyömäsoitin)" ml. KT "lautaset", "symbaali" ja "symbaalit" tai [2] lisätään KT-muodot "lautanen (lyömäsoitin)", "lautaset" ja "symbaalit". 

#### Perustelut ehdotukselle   

Soitin tunnetaan nykyään paremmin nimellä "lautanen" kuin "symbaali". Ks. esim. https://fi.wikipedia.org/wiki/Lautanen_(soitin) 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa on termi _lautaset_, joka tarvitsee sulkutarkenteen jos tämä muutos toteutetaan.

**Comment by TommiViitamies** [comment]
En suuremmin kannata: ainakin populaarimusiikin kentällä puhutaan yleisemmin juurikin symbaaleista kuin lautasista (arkikielessä: pellit).

**Comment by YSA-kokous** [comment]
Ei muutosta.

**Comment by ksornova** [comment]
Sekä Otavan isossa musiikkitietosanakirjassa että Brodin Musiikkisanakirjassa suositellaan suomenkielisen _lautaset_-termin käyttöä. Palauttuu Luumu-ryhmän käsittelyyn.

**Comment by ilkkahaataja** [comment]
Luumu-kokous (31.10.2017): Kannatamme vaihtoehtoa 1: **lautanen (lyömäsoitin)**.

**Comment by YSA-kokous** [comment]
lautanen (lyömäsoittimet)
lautaset (astiat)

**Comment by mariaforsen** [comment]
Tämä ei tainnut olla ihan standardin (ja aiempien käytäntöjen) mukaista: ISO 25964-1: "their use [qualifiers] (especially in preferred terms) should be avoided if another means of resolving disambiguity can be found".
