### ISSUE TITLE
bassokitara

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5491]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[bassokitara](http://www.yso.fi/onto/ysa/Y101008) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia ja lisätään jaetuille termeille LCSH-siltaukset: (1) "akustinen bassokitara", LT "akustinen kitara"; ja (2) "sähköbasso", LT "sähkökitara"; ensimmäisen tarkaksi LCSH-vastineeksi tulee "Acoustic bass guitar" [http://id.loc.gov/authorities/subjects/sh2008002881] ja toisen "Bass guitar" [http://id.loc.gov/authorities/subjects/sh85012161]. 

#### Perustelut ehdotukselle   

Termillä viitataan nyt kahteen eri soittimeen, ja tämä ristiriita pitäisi poistaa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Allärs: akustisk basgitarr, elbas KT basgitarr ?

**Comment by TommiViitamies** [comment]
Ristiriita on olemassa, mutta aina ei ole mahdollista tehdä eroa kummasta on kyse, eikä edes tarpeen (esim. soitonoppaat)..

**Comment by YSA-kokous** [comment]
Seuraava kokous.

**Comment by ilkkahaataja** [comment]
Luumu-kokous (27.11.2017): Emme kannata termin bassokitara poistamista. Luumu tekee vastaehdotuksen.

**Comment by TommiViitamies** [comment]
Muusan (Luumun seuraajan) minulle delegoima vastaehdotus:

Uusi termi: akustinen bassokitara
LT bassokitara
RT sähköbasso
RT akustinen kitara
 
Uusi termi: sähköbasso
LT bassokitara
LT sähkösoittimet
RT akustinen bassokitara
RT sähkökitara
 
Muutokset ”bassokitaraan”:
 
pois: LT sähkösoittimet 
uusi: RT kontrabasso

**Comment by SamuVirokannas** [comment]
Tommin ehdotuksen hyvänä puolena kieltämättä olisi se, että ei tarvitsisi aina tehdä eroa sähköbasson ja akustisen bassokitaran välillä, jos esim. ei ole varmuutta, kumpi on kyseessä. Huonona puolena näen, että akustisen bassokitaran suhde akustiseen kitaraan jäisi löyhäksi (ja sähköpuolella samoin); itse miellän kyllä akustisen bassokitaran eräänlaiseksi akustiseksi kitaraksi. 

Aluksi mieltäni vaivasi myös se, että bassokitara ei tarkoittaisikaan tiettyä soitinta vaan toimisi vain yläkäsitteenä akustiselle ja sähköbassolle, ja siten pitäisi varmaankin olla monikossa bassokitarat, mikä tuntuu hiukan kömpelöltä. Toisaalta kitarakin toimii yläkäsitteenä akustisille ja sähköisille soittimille. 

Jaakon ehdotuksessa puolestaan minua miellyttää selvä jaottelu akustiseen ja sähköiseen sekä suorempi vastaavuus LOCin termeihin. (Tosin LOCista puuttuu akustisen kitaran väliporras.) 

Yritän yhdistää Jaakon ja Tommin ehdotuksia himmeliksi, jossa olisi molempien hyviä puolia - tosin hintana monimutkaisempi rakenne: 

akustinen kitara
LT kitara

--akustinen bassokitara
  LT akustinen kitara
  LT bassokitara

bassokitara 
LT kitara 
  
--sähkökitara
  LT kitara
  LT sähkösoittimet

--sähköbasso
  LT sähkökitara
  LT bassokitara

Siis kitara jakautuisi akustiseen ja sähkökitaraan, ja kummankin alla on luontevasti bassosoittimet. Akustinen bassokitara ja sähköbasso kuuluisivat lisäksi kitaran alla olevaan bassokitara-luokkaan, mikä sallisi tarpeen mukaan olla erottelematta akustista ja sähköistä toisistaan. 

Terv. Samu Virokannas
Kansalliskirjasto, Viola-tiimi

**Comment by TommiViitamies** [comment]
Samun kommentin pohjalta täsmennän omaa ehdotustani. Bassokitara "alalajeineen" on selkeämmin kitaran alakäsite (ja jokin looginen virhekin siellä ehkä poistettu):

Uusi termi: akustinen bassokitara
LT akustinen kitara
LT bassokitara
RT sähköbasso

Uusi termi: sähköbasso
LT bassokitara
LT sähkökitara
RT akustinen bassokitara

Muutokset ”bassokitaraan”:
pois: LT akustinen kitara
uusi: LT kitara
uusi: RT kontrabasso

**Comment by jtuohini** [comment]
Viime hetken huomiona: tässä ovat nyt menneet matkalla jo SEKO ja YSA hieman ristikkäin, sillä jälkimmäisessä on
 
**bassokitara**
LT _kitara_
LT _sähkösoittimet_  [joka siis poistuisi!]
[ja vastaavasti uutena tulisi RT _kontrabasso_]

**Comment by SamuVirokannas** [comment]
SEKO ja YSA eivät olleet tähänkään asti ihan yhteneväisiä. Nythän SEKO:ssa on jo eroteltu sähköbasso ja akustinen bassokitara toisistaan, joskin niin, että sähköbasso hieman oudosti ei ole kitara laisinkaan vaan suoraan näppäilysoittimen (ja sähkösoittimen) alla; bassokitara puolestaan on SEKO:ssa akustisen kitaran alla. Kun YSA:n bassokitara(t) on saatu jonkinmoiseen ojennukseen, kannattaisi tarkistaa ja yhdenmukaistaa myös SEKO:n kitaraperheen rakenne sekä sanalliset kuvaukset. 

Bassokitaran LT sähkösoittimet poistuisi, jotta bassokitara yleisesti voisi tarkoittaa sähköistä tai akustista soitinta. Sähköbassollekin yläkäsite "LT sähkösoittimet" lienee tarpeeton, koska se periytyisi sähkökitaralta.

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan	
Uusi termi: akustinen bassokitara
LT akustinen kitara
LT bassokitara
RT sähköbasso

Uusi termi: sähköbasso
LT bassokitara
LT sähkökitara
RT akustinen bassokitara

Muutokset ”bassokitaraan”:
pois: LT akustinen kitara
uusi: LT kitara

Samat muutokset myös SEKOon (lukuun ottamatta RT-suhteita)

**Comment by mariaforsen** [comment]
Sv. 
-akustisk basgitarr
-elbas
(Allärs: elbas=bassokitara >> basgitarr)
