### ISSUE TITLE
hymnit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5492]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hymnit](http://www.yso.fi/onto/ysa/Y101727) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan KT-muodoksi termille "virret". 

#### Perustelut ehdotukselle   

Termi on nykyisellään monimerkityksinen ja osin erittäin epätarkka ja tämän seurauksena epäjohdonmukaisesti käytetty. Ensisijainen merkitys on sama kuin termillä "virret", joten se on luonteva ohjauksen kohde. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Voiko näin tehdä? Melindassa 197 viitettä. Kielitoimiston sanakirja: 1. juhlallinen (kuoro)laulu. _Kansallishymni. Finlandia-hymni._ 2. ortod. kirkossa: ylistyslaulu. MUSA: _(1) Roomalaiskatolisessa liturgiassa yksinkertainen säkeistölaulu ja (2) tekstiltään hengellinen tai muuten juhlallinen sävelmä. Englannin kielessä sana "hymn" tarkoittaa virttä tai koraalia._

Mitä tehdään niille tapauksille joissa _virret_ ei sovellu?

**Comment by mariaforsen** [comment]
Ruotsin osalta en voi millään muotoa kannattaa tätä. Virret=psalmer on ensinnäkin pelkästään kristillinen laulu, ja tosiaan hymn voi yhtä hyvin viitata muunlaisiin "juhlallisiin" lauluihin, ei vain uskonnollisiin tai kristillisiin lauluihin. SAOssa on sekä hymner että psalmer erillisinä päätermeinä. Niiden välillä ei ole edes mitään suhteita. Ks. myös Nationalencyklopedin.

**Comment by OutiHintikka** [comment]
Termi on vähän ongelmallinen, sillä käsitettä käytetään myös kirjallisuudentutkimuksessa eikä tällöin ole kysymys virsistä, vaan antiikin (homeerisista) hymneistä. Myös tämä näkökulma pitäisi huomioida jotenkin.

**Comment by YSA-kokous** [comment]
Ei muutosta.
