### ISSUE TITLE
intermezzot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5493]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[intermezzot](http://www.yso.fi/onto/ysa/Y101861) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia: [1] "intermezzot (kamarioopperat)", KT "entr’actet", {Määritelmä: Pienimuotoinen italiankielinen koominen täys- tai myöhäisbarokkiooppera, jossa on kaksi tai harvemmin kolme roolia ja joka on sävelletty esitettäväksi yleensä opera serian näytösten välillä.}, summittainen LCSH-vastine "Operas" [http://id.loc.gov/authorities/subjects/sh85094914], ja [2] "intermezzot (soitinmusiikki)" tms {Määritelmä: Itsenäinen, sävyltään yleensä lyyrinen piano- tai muu soitinmusiikkiteos.}. 

#### Perustelut ehdotukselle   

Termillä tällä hetkellä kaksi selvästi toisistaan poikkeavaa merkitystä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by satuniininen** [comment]
Tarvitaan myös engl. sulkutarkenteet, esim intermezzos (operas) ja intermezzos (instrumental music) (?)
Ei siltauksia

**Comment by mariaforsen** [comment]
Allärs: intermezzon (operor), intermezzon (instrumentalmusik)

**Comment by YSA-kokous** [comment]
intermezzot (kamarioopperat) ja intermezzot (soitinmusiikki)
