### ISSUE TITLE
kielisoittimet [omana terminään]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5494]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kielisoittimet [omana terminään] 

#### Ehdotettu termi ruotsiksi   

stränginstrumenter 

#### Ehdotettu termi englanniksi   

string instruments / stringed instruments 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soittimet](http://www.yso.fi/onto/yso/p7110) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85129118> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Kielisoitin 

#### Vaihtoehtoiset termit ja ilmaisut   

kordofonit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarve omaksi termikseen hierarkian YSA-hierarkian selventämiseksi (esim. kampiliira); tuli vastaan MUSAn ja YSAn yhdistämisen tiimoilta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Tarkoitusta täsmentävä selite   

Soitimet, joissa ääni syntyy kaikukopan ylle pingotetuista kielistä. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [kielisoittimet [omana terminään]](http://finto.fi/yse/fi/page/Y505494)

**Comment by LeKorsu** [comment]
Mikä sitten jää jousisoitinten englanninkieliseksi käännökseksi, jos string instrumenteista tehdään nyt ehdotetusti kielisoittimet?

**Comment by satuniininen** [comment]
Jousisoittimet --> bowed string instruments tai bowed stringed instruments

**Comment by mariaforsen** [comment]
Sv. stränginstrument
