### ISSUE TITLE
musiikkijuhlat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5496]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkijuhlat](http://www.yso.fi/onto/ysa/Y101359) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan välihierarkioiden sanamuoto: "musiikkijuhlat instrumentin mukaan" --> "musiikkijuhlat soittimen mukaan" (instrumentti = väline, musiikki-instrumentti = soitin) tai "musiikkijuhlat esityskokoonpanon mukaan" (jotta otsikon alla jo oleva termi 'laulujuhlat' sopisi luontevammin), ja "musiikkijuhlat musiikkilajin mukaan" --> "musiikkijuhlat musiikinlajin mukaan" (mieluummin genetiivin kanssa) 

#### Perustelut ehdotukselle   

. . 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ehdotus koskee YSOa.

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan

**Comment by MUUSA-kokous** [comment]
Tehdään ehdotetut termimuutokset.

**Comment by tpalonen** [comment]
Tehty muutokset.
