### ISSUE TITLE
kokeellinen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5497]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kokeellinen musiikki 

#### Ehdotettu termi englanniksi   

experimental music 

#### Ehdotettu termi ruotsiksi   

experimentell musik 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh90001254> 

#### Perustelut ehdotukselle   

Tullut vastaan Musaa Ysaan sulautettaessa. Analogia: "kokeellinen kirjallisuus", "kokeellinen teatteri" jne. 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka pyrkii rikkomaan sävellysajankohdan konventioita käyttämällä uusia keinovaroja (totutusta poikkeavia säveljärjestelmiä, soittimia, soittotapoja jne.). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Vaihtoehtoiset termit ja ilmaisut   

avantgardemusiikki; avantgardistinen musiikki; kokeellisuus--musiikki 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi

**Comment by asormune** [comment]
jääkö termi avantgarde, entä modernismi

**Comment by jtuohini** [comment]
**Avantgarde** jäisi YSAan kaikki taiteenalat kattavana sanaryhmän 90 yleisterminä [http://www.yso.fi/onto/ysa/Y94826], samoin **modernismi** [http://www.yso.fi/onto/ysa/Y97481], joten uudella termillä päästäisiin suurempaan tarkkuuteen. Ongelma yhdistämisen taustalla on ollut se, että Musassa _kokeellinen musiikki_ on viittausmuoto **avantgarde**-termille [http://www.yso.fi/onto/musa/p493], joten on selkeintä ottaa noista tuo ongelmaton sanamuoto YSA-termiksi.

**Comment by mariaforsen** [comment]
Sv. experimentell musik ET avantgardemusik
