### ISSUE TITLE
integrointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5498]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[integrointi](http://www.yso.fi/onto/ysa/Y177666) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu yhdistämistä termiin integraatio 

#### Perustelut ehdotukselle   

Erottelu ruotsiksi hankalaa 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/243

**Comment by mirmaid** [comment]
Sanastossa on myös _integroitu opetus_.

**Comment by mirmaid** [comment]
Eriteltynä käsitteiden merkityksiä ja käyttöhistoriaa sisällönkuvailussa: https://docs.google.com/spreadsheets/d/1S2hd7y_bex17e5GUOVCMCE5tSclm8rPGIEauy1C3YGw/edit?usp=sharing

**Comment by jtuohini** [comment]
"Integrointi" on myös matematiikan termi (esim. https://fi.wikipedia.org/wiki/Integrointi), joten pitäisikö YSAan lisätä _integrointi (matematiikka)_ KÄ **integraalilaskenta** [http://www.yso.fi/onto/ysa/Y95562] tms?

**Comment by mirmaid** [comment]
Tutkitaan voidaanko _integrointi_ korvata kaikissa tapauksissa termeillä _integraatio, integroitu opetus, integraalilaskenta_ tai _yhdistäminen_.

**Comment by satuniininen** [comment]
Näillä vielä ei saada katettua kaikkia tapauksia, sillä eivät sovellu esim. seuraaviin tapauksiin:

- Osatyökykyisten integrointi organisaatioon : henkilöstöjohtamisen mahdollisuudet, haasteet ja ratkaisut: case Linnanmäki Marita Leppäkangas.
- The Hamburg Model : exemplary integration of youth into vocational education / Elina Priedulena.

Muutakin korvaavaa sanastoa löytyy runsaasti, esim. _inkluusio, kotoutuminen, työhönsijoittuminen_ jne.
Voidaan myös kyseenalaistaa, onko integraatio kaikissa tapauksissa ylipäätään niin keskeinen aspekti, että se pitää erikseen kuvailla. Monesti se on todennäköisesti lisätty vain, koska esiintyy teoksen nimessä, vaikka käsite on niin monimerkityksinen, ettei se kerro teoksen sisällöstä paljoakaan.

**Comment by YSA-kokous** [comment]
Poistetaan integrointi.
