### ISSUE TITLE
kotoutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5499]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotoutuminen](http://www.yso.fi/onto/ysa/Y172923) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

kotoutuminen, kotiutuminen ja kotoutus -termien käytön selkeyttäminen tai termien yhdistäminen 

#### Perustelut ehdotukselle   

Termit kotoutuminen, kotouttaminen ja kotiutuminen ongelmallisia: kotoutuminen-termiä käytetään maahanmuuttajista, mutta myös kotiutuminen-termiä voidaan käyttää samoissa yhteyksissä. Toisaalta kotoutuminen ja kotouttaminen ovat saman asian kaksi puolta, onko erottelu tarpeen? 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
KOTOUTUMINEN

Melindassa käytetty maahanmuuttajien ja pakolaisten yhteydessä.

Selitysehdotus MOTin pohjalta: Tarkoittaa maahanmuuttajien asettumista uuteen yhteiskuntaan omat kulttuuripiirteensä säilyttäen.

kotouttaminen Allärs: integrationsfrämjande

**Comment by mirmaid** [comment]
KOTIUTUMINEN

Melindassa käytetty pääasiassa sosiaali- ja terveydenhuollon ja maahanmuuttajien yhteydessä. Keskeisenä merkityspiirteenä refleksiivisyys, näkökulmana toimija itse ja tapahtuma hänen kannaltaan. Eroa on kuitenkin siinä, käytetäänkö terveydenhuollon vai maahanmuuttajien yhteydessä (MOTin merkitykset 1. ja 2.):

terveydenhuollossa: vanhukset – kotiutuminen ( = kotiinpaluu) maahanmuuttajat – kotiutuminen ( = tottua olemaan jossakin, ruveta viihtymään)

Pitäisikö siis jakaa: (alla olevat esimerkkitarkenteet eivät ole YSAn termejä)
kotiutuminen (kotiinpaluu)
kotiutuminen (tottuminen olosuhteisiin) (ehdotettu myös tarkennetta sopeutuminen)

Käytetty kerran myös MOTin 3.-merkityksessä ”tulla vakiintuneeseen käyttöön, saada pysyvä jalansija, juurtua” (”innovaatioiden kotiutuminen”, käytetty myös sanoja omaksuminen, käyttöönotto, kuluttajakäyttäytyminen)

**Comment by mirmaid** [comment]
Eriteltynä käsitteiden merkityksiä ja käyttöhistoriaa sisällönkuvailussa: https://docs.google.com/spreadsheets/d/1S2hd7y_bex17e5GUOVCMCE5tSclm8rPGIEauy1C3YGw/edit?usp=sharing

**Comment by mirmaid** [comment]
Alustava ehdotus (https://github.com/Finto-ehdotus/YSE/issues/5104): 
kotiutuminen (sopeutuminen) (RT kotiinpaluu)
kotoutuminen KÄ kotouttaminen (tarkenne x) & kotiutuminen (sopeutuminen)

**Comment by mariaforsen** [comment]
Eli mihin käyttökontekstiin tuo kotiutuminen (sopeutuminen) on tarkoitettu, jos on joku tietty? Viittaa siis KS:n kakkosmerkitykseen "tottua olemaan jssak, ruveta viihtymään jssak, perehtyä hyvin jhk."? Ruotsin vastine "bli hemmastadd"? (Hemanpassning=hjälpmedel och/eller ombyggnad och stora renoveringar av bostad)

**Comment by ilona-x** [comment]
Korjausten jälkeen Melindaan jäi vain 12 viitettä, joissa käytetty termiä kotiutuminen. Monessa tapauksessa kuvailu onnistuisi mielestäni ilman termiä kotiutuminen (sopeutuminen). Osassa kyseessä maahanmuuttajista, jolloin oikea termi olisi kotoutuminen, pari tapausta on keskosten/äitien kotiutumisesta sairaalasta, missä ei ole kyse sopeutumisesta vaan noihin voisi korjata termiksi potilaan kotiuttaminen. Ehdotus: ohjataan kotiutuminen (sopeutuminen) KÄYTÄ sopeutuminen. Tuon kotiutuminen (sopeutuminen) termin vaarana on, että sitä käytetään jatkossakin päällekkäin muiden kotoutumistermien kanssa.

**Comment by mirmaid** [comment]
Jos pärjätään ilman _kotiutuminen_-termiä (ehkä kotiutuminen (sopeutuminen) KÄ _sopeutuminen_), jää jäljelle vielä _kotoutuminen-kotouttaminen_ -pari, sv. _integration (invandrare)-integrationsfrämjande_. Voivatko molemmat jäädä?

**Comment by YSA-kokous** [comment]
kotoutuminen (maahanmuuttajat)
kotouttaminen (maahanmuuttajat)
