### ISSUE TITLE
viimeinen tuomio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#550]
#### Ehdotettu termi suomeksi

viimeinen tuomio
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)
#### Lähde

Lähde: Facta 2001

**Luontipäivämäärä:** 15.03.2000

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008, 13.10.2010

**Voyager-id:** 114727

**Termiehdotus Fintossa:** [viimeinen tuomio](http://finto.fi/yse/fi/page/Y314727)

**Comment by jtuohini** [comment]
Tarvetta tälle on edelleen! Teologisen tiedekunnan kirjaston asiasanaston lopettamisen yhteydessä tulee tarvetta tälle YSO:n puolella. Yms.

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/3626

**Comment by mariaforsen** [comment]
Myös SAOssa: https://id.kb.se/term/sao/Yttersta%20domen Ja LCSH: https://id.loc.gov/authorities/subjects/sh85070918.html
Kannatan!

**Comment by mirmaid** [comment]
13 viitettä Melindassa.
