### ISSUE TITLE
pelot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5500]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pelot](http://www.yso.fi/onto/ysa/Y98042) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa nyt pelko (tunteet) ja pelot (spesifiset). Onko mahdollista yhdistää yksikkö- ja monikko-muodot? Nyt päällekkäisyyttä, sekä pelko, pelot että fobiat. Ellei yhdistetä täytyy varmaan ainakin lisätä sulkutarkenteita (YSOssa on jo). 

#### Perustelut ehdotukselle   

Yksi "pelko/pelot" + fobiat riittäisi kuvailuun ja sen myötä hakutuloksetkin olisivat yhdenmukaisempia? Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5444 ja https://github.com/NatLibFi/Finto-data/issues/791 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Tunteet ovat YSAssa yksikkömuotoisia, mikä puoltaisi _pelko_-muodon säilyttämistä. Se tuntuu kuitenkin välillä melko "vahvalta" (esim. _Barns rädslor i förskolan: en studie av förskolebarns rädslor i förskolemiljö och vardag, Miksi mies pelkää naista?: ja mitä siitä seuraa_).

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5444

**Comment by mariaforsen** [comment]
Barns rädslor-kirjaan kävisi ruotsin osalta ihan hyvin pelkkä rädsla. Rädsla yksikössä ole sen vahvempaa kuin rädslor-sanaa. 

Vrt. myös SAO: rädsla (eikä rädslor ollenkaan)

Issue 5444 olisi yhdistämisen myötä ratkaistu (fruktan olisi KT termille rädsla - näin myös SAOssa).

**Comment by satuniininen** [comment]
Kannatan yhdistämistä. Omaan korvaani yksikkömuotoinen _pelko_ ei kuulosta mitenkään monikkoa vahvemmalta.

**Comment by YSA-kokous** [comment]
pelot KÄ pelko

**Comment by mariaforsen** [comment]
Sv. rädslor ANV rädsla
