### ISSUE TITLE
skandinaavinen mytologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5502]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[skandinaavinen mytologia](http://www.yso.fi/onto/ysa/Y106218) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi: mytologia http://www.yso.fi/onto/ysa/Y97593

Huom. Sama myös näille:
* antiikin mytologia http://www.yso.fi/onto/ysa/Y106221
* suomalainen mytologia http://www.yso.fi/onto/ysa/Y106207 

#### Perustelut ehdotukselle   

Nyt voi liian helposti kuvailla
650 mytologia
651 Pohjoismaat
edes huomaamatta, että termi 'skandinaavinen mytologia' on olemassa 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by jtuohini** [comment]
Ja KT-muodoksi varmaankin myös _pohjoismainen mytologia_?
 
Lähin LCSH-vastine näyttäisi olevan **Mythology, Norse** [http://id.loc.gov/authorities/subjects/sh85089413] (KT-muotoina mm. _Scandinavian mythology_).
