### ISSUE TITLE
kirjalliset suhteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5503]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjalliset suhteet 

#### Ehdotettu termi englanniksi   

literary contacts 

#### Ehdotettu termi ruotsiksi   

litterära kontakter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuurisuhteet](http://www.yso.fi/onto/yso/p5992) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artossa käytetty liki 30 kertaa, mm. bibid 1573257 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kirjalliset suhteet](http://finto.fi/yse/fi/page/Y505503)

**Comment by mirmaid** [comment]
Melindassa 14 viitettä.

Suurin osa Googlen viitteistä liittyy teokseen _Suomen ja Unkarin kirjalliset suhteet_. Muuten käytetty varsin vähän, ja kulttuurisuhteet-merkityksen lisäksi myös muissa konteksteissa.

**Comment by tpusa** [comment]
Kävisikö "kirjallisuussuhteet"?

**Comment by LeKorsu** [comment]
Eikö pelkkä kulttuurisuhteet riittäisi?

**Comment by YSA-kokous** [comment]
kirjallisuussuhteet
