### ISSUE TITLE
kiislat (suku)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5504]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kiislat (suku) 

#### exactMatch   

laji.fi : https://laji.fi/taxon/MX.27851 
Birdlife : <http://nimisto.birdlife.fi:3000/> 

#### Vaihtoehtoiset termit ja ilmaisut   

Uria 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Tarkoitusta täsmentävä selite   

Lintulaji 

#### Perustelut ehdotukselle   

Arton aineiston kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton aineiston kuvailu 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kiislat (suku)](http://finto.fi/yse/fi/page/Y505504)

**Comment by mirmaid** [comment]
Ei tarvitse tarkennetta (suku), koska samannimistä lajia ei ole.

**Comment by mariaforsen** [comment]
Sv. grisslor
