### ISSUE TITLE
etelänkiisla

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5505]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

etelänkiisla 

#### Ehdotettu termi englanniksi   

Guillemot/Common Murre 

#### exactMatch   

laji.fi : https://laji.fi/taxon/MX.27853 

#### Vaihtoehtoiset termit ja ilmaisut   

Uria aalge 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Arton aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton aineisto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [etelänkiisla](http://finto.fi/yse/fi/page/Y505505)

**Comment by mariaforsen** [comment]
Sv. sillgrissla
