### ISSUE TITLE
pohjankiisla

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5506]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pohjankiisla 

#### exactMatch   

laji.fi : https://laji.fi/taxon/MX.27852 

#### Vaihtoehtoiset termit ja ilmaisut   

Uria lomvia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Arton aineiston kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton aineisto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [pohjankiisla](http://finto.fi/yse/fi/page/Y505506)

**Comment by mariaforsen** [comment]
Sv. spetsbergsgrissla
