### ISSUE TITLE
alli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5507]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alli 

#### Ehdotettu termi englanniksi   

Long-tailed Duck/Oldsquaw 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sorsat](http://www.yso.fi/onto/yso/p8345) 

#### exactMatch   

laji.fi : https://laji.fi/taxon/MX.26427 

#### Vaihtoehtoiset termit ja ilmaisut   

Clangula hyemalis 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Arton aineiston kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton aineisto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [alli](http://finto.fi/yse/fi/page/Y505507)

**Comment by mariaforsen** [comment]
Sv. alfågel
