### ISSUE TITLE
euroopanlehtikuusi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5509]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

euroopanlehtikuusi 

#### exactMatch   

laji.fi : https://laji.fi/taxon/MX.37817 

#### Vaihtoehtoiset termit ja ilmaisut   

euroopanlehtikuusi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Arton aineiston kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton aineisto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [euroopanlehtikuusi](http://finto.fi/yse/fi/page/Y505509)

**Comment by mariaforsen** [comment]
Sv. europeisk lärk
