### ISSUE TITLE
Turkestan

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5510]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Turkestan 

#### Ehdotettu termi ruotsiksi   

Turkestan 

#### Ehdotettu termi englanniksi   

Turkestan 

#### exactMatch   

Turkestan : https://fi.wikipedia.org/wiki/Turkestan 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Melindasta löytyy useita tietueita, joissa on käytetty Turkestania YSA:n asiasanana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The arts and crafts of Turkestan, ISBN 0-500-97316-4 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [Turkestan](http://finto.fi/yse/fi/page/Y505510)

**Comment by mirmaid** [comment]
LCSH: USE Asia, Central

Melindassa 95 viitettä.
