### ISSUE TITLE
neurulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5511]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

neurulaatio 

#### Ehdotettu termi englanniksi   

neurulation 

#### Ehdotettu termi ruotsiksi   

neurulation 

#### Ehdotettu yläkäsite YSOssa (LT)   

[alkionkehitys](http://www.yso.fi/onto/yso/p7282) 

#### exactMatch   

Wikipedia : https://fi.wikipedia.org/wiki/Neurulaatio 
Wikipedia (eng) : https://en.wikipedia.org/wiki/Neurulation 
Wikipedia (swe) : https://sv.wikipedia.org/wiki/Neurulation 

#### Perustelut ehdotukselle   

Neurulaatiota on vaikea kuvailla YSA:ssa jo olevin käsittein. 

#### Tarkoitusta täsmentävä selite   

Neurulaatiolla tarkoitetaan alkionkehityksen tapahtumaa, jossa gastrulaatiossa syntyneestä ektodermistä muodostuu hermostoputki. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi:jyu-201708303608 (Häkkinen, H-M.:Investigating in vivo Cell and Tissue internalization during zebrafish neurulation) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi **Termiehdotus Fintossa:** [neurulaatio](http://finto.fi/yse/fi/page/Y505511)

**Comment by mirmaid** [comment]
Kerran Melindassa. FinMeSHissä.

**Comment by mariaforsen** [comment]
Sv. neurulation
