### ISSUE TITLE
yleiset saunat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5512]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yleiset saunat 

#### Ehdotettu termi ruotsiksi   

allmänna bastur 

#### Ehdotettu yläkäsite YSOssa (LT)   

[saunat](http://www.yso.fi/onto/yso/p6381) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Perustelut ehdotukselle   

Otettu käyttöön 2.9.2017 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Teos: Filpus: Kaupunkisaunoja 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [yleiset saunat](http://finto.fi/yse/fi/page/Y505512)

**Comment by mariaforsen** [comment]
Sv. allmänna bastur

**Comment by mariaforsen** [comment]
Sv. allmänna bastur

**Comment by jarmosaarikko** [comment]
preferredLabel: public saunas {@en}| hiddenLabel: public sauna {@en}
https://www.wikidata.org/wiki/Q11902783
