### ISSUE TITLE
musiikkiklubit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5513]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkiklubit](http://www.yso.fi/onto/ysa/Y130179) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkistetaan termin määritelmä ja muutetaan se. Lisäksi jaetaan termi kahtia tai kolmia, jos tarve. 

#### Perustelut ehdotukselle   

Tällä hetkellä sanaa "musiikkiklubi" on käytetty ainakin kolmessa eri merkityksessä: [1] (suljetuista) yhdistyksistä/järjetöistä (= sama merkitys kuin LCSH:n "Music--Societies, etc.", KT Music clubs, Musical clubs), [2] konserteista (tietynlaiseen musiikkiin keskittyvä teemailta tms) ja [3] konserttipaikoista (musiikkiravintolat tms). 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ykkösmerkitystä en Melindasta löytänyt, tosin kaikista teoksista ei ole näkemättä ihan helppo sanoa tarkalleen mitä käsitellään. Yleensä termillä viitataan ravintolaan/keikkapaikkaan, kakkosmerkityksen erottaminen tästä on itseasiassa vähän vaikeaa.

**Comment by asormune** [comment]
Keski-kannasta löytyi asiasanalla "musiikkiklubit" viite, jossa 1. tapausta on sovellettu: Suupilliklubi Piccolo : 10 aastane (Eestiläisen huuliharppukerho Piccolon 10-vuotishistoriikki). Mutta eikö ole ennemminkin kyseessä musiikin "yhdistystoiminta", joita kuvaillaan asiasanoilla "järjestöt" (musiikki) tai "järjestötoiminta" (musiikki).

**Comment by mariaforsen** [comment]
Jako kahteen on ruotsiksikin mahdollinen, mutta enemmän käytetään termiä "musikföreningar" (musiikkiyhdistykset) kun on kysymys ensimmäisestä. Viimeinen merkitys "musiikkiravintola" on ruotsiksi yleisin. Kakkosmerkitystä olisi vaikeaa kääntää.

**Comment by YSA-kokous** [comment]
Muokataan määritelmää, ei muutoksia termiin. KT keikkapaikat.

**Comment by tpalonen** [comment]
Ehdotus määritelmäksi: "Tiettyyn ohjelmasisältöön rakentuva, yleensä toistuvasti järjestettävä musiikkitapahtuma."

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): pitää tutkia vähän tarkemmin, jää seuraavaan kertaan.
tästä puhuimme, pitää kehittää:
musiikkiravintolat
KT musiikkiklubit
KT keikkapaikat
(tilana)

uusi sana musiikkiklubit (tapahtumana) -- YSE-ehdotus

**Comment by TommiViitamies** [comment]
Tämän kehittäminen nakittui Muusassa minulle. Ehdotan alkuperäisen ehdotuksen suuntaisesti, että rajataan musiikkiklubit tarkoittamaan tiettyyn ohjelmasisältöön rakentuvia, yleensä toistuvasti järjestettäviä musiikkitapahtumia (tuo Tuomaksen määritelmä olisi minusta ihan ok) ja luodaan uusi termi musiikkiravintolat (KT keikkapaikat).

**Comment by mirmaid** [comment]
Vaatii kuitenkin myös tarkenteen, eli _musiikkiklubit (tapahtumat)_ (toivottavasti sitten käytettäisiin oikein, eikä esim. musiikkiravintoloiden keikkatarjonnasta ikäänkuin olisi ketju). Onko tämä varmasti tarpeen?

**Comment by mariaforsen** [comment]
Sv. musikklubb ei ole yleensä tapahtuma, vaan lähinnä joko "kerho" tai tässä tapauksessa "paikka/organisaatio", eli olisi hyvin outoa laittaa vastineeksi "musikklubbar (evenemang)"? Musiikkiravintola=musikrestaurang ok?

**Comment by TommiViitamies** [comment]
Uusi ehdotus määritelmäksi: "Tiettyyn ohjelmasisältöön rakentuva, yleensä toistuva ja joko samassa tai eri paikoissa järjestettävä pienehkö musiikkitapahtuma."

(Jos ruotsin musikklubb-termi viittaa esim. lapsille järjetettyihin musiikkikerhoihin, niin eivät nekään minusta olisi paikkaan sidottuja. Jossain määrin niitä voidaan kai kuitenkin pitää organisaatioina (tai osana sellaisia), kuten "musiikkiklubejakin", sen lisäksi että ovat kai myös tapahtumia.)

**Comment by mirmaid** [comment]
^ Kyllä tuossa on ongelma, jos termi tarkoittaa suomeksi vaikka jonkun tietyn musiikkigenren (yleensä kai rock/edm) toistuvia "keikkatapahtumia" ja ruotsiksi musiikkikerhoja. Minkä aineiston kuvailussa tämä on olennaisen tärkeä käsite?

**Comment by asormune** [comment]
Käsitellään sekä tapahtumaa (> musiikkiklubit) että paikkaa (> keikkapaikat)
Mattlar: Stadin diskohistoria (kirja)
Rytmihäiriöitä : uuden Suomi-jazzin nousu (kirja)
Juntto: Rock'n'roll-yliopiston kasvatit : 45 Specialin tarina (kirja)
Taistelu Lutakosta (DVD)

**Comment by tpalonen** [comment]
Edeltävä kommentti sai pohtimaan, että jotenkin kuvittelisin että jonkinlainen käytännönläheinen kompromissi palvelisi tässä käyttäjää parhaiten. Jos kerran aineisto käsittelee usein sekä paikkaa että tapahtumaa, olisiko hyvä että sanastossa olisi yksi käsite, joka kattaisi molemmat merkitykset?

**Comment by MUUSA-kokous** [comment]
Tulkitaan käsite siten, että se kattaa sekä tapahtumat että paikat. Muokataan määritelmää tämän mukaisesti. YSO-kokous päättäköön sopivan yläkäsitteen. @tpalonen tekee uuden määritelmäehdotuksen.

**Comment by tpalonen** [comment]
Määritelmäehdotus: "Tiettyyn ohjelmasisältöön rakentuva, yleensä toistuva pienehkö musiikkitapahtuma tai tällaisen tapahtuman pitopaikka."
