### ISSUE TITLE
musiikkielämä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5514]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkielämä](http://www.yso.fi/onto/ysa/Y103601) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi KT-muodoksi termille "musiikinhistoria". 

#### Perustelut ehdotukselle   

Termin määritelmä viittaa siihen, että kyse on samasta asiasta kuin mitä termillä "musiikinhistoria" tarkoitetaan. Analogia: YSAssa on termit "elokuvahistoria" (mutta ei 'elokuvaelämä') ja "teatterihistoria" (mutta ei 'teatterielämä'). 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
MUSA: musiikinhistoria: _Musiikillisten ilmiöiden tarkasteleminen historiallisesta näkökulmasta, esimerkiksi musiikinhistoria : Eurooppa : 1600-luku._

_Musiikkielämä_-termin korvaaminen _musiikinhistorialla_ esim. Melindan ensimmäisessä viitteessä _Juva Rock City: festarijärjestäjän taivas ja helvetti_ tuntuu aika rohkealta vedolta.

**Comment by AuHo22** [comment]
Paljon on jonkin aikakauden säveltäjien henkilöhistoriaa, sosiaalisia suhteita jne. toimintaa kuvattu musiikkielämä + historia-ketjulla. Voisi tietysti käyttää kulttuurielämä + historia -termiä. Myös taide-elämä -termi olemassa erotuksena varsinaisesta taidehistoriasta, jossa tutkitaan nimenomaan taidetta, ei ajan taiteilijoitten elämää sen lisäksi.

**Comment by TommiViitamies** [comment]
En kannata poistoa. Viilaisin mieluummin määritelmiä.

**Comment by YSA-kokous** [comment]
Ei poisteta, RT musiikinhistoria.
