### ISSUE TITLE
Norrbottenin lääni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5515]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Norrbottenin lääni 

#### Ehdotettu termi ruotsiksi   

Norrbottens län 

#### Ehdotettu termi englanniksi   

Norrbotten County 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/names/n80045963> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Norrbottenin_l%C3%A4%C3%A4ni 
Englanninkielinen Wikipedia : https://en.wikipedia.org/wiki/Norrbotten_County 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Norrbottenin maakunta (johon nykyinen YSA-termi viitannee) kattaa vain osan Norrbottenin läänistä; kun kuvailtavana on koko lääniä käsittelevä aineisto, ei nyky-YSAsta löydy sopivaa termiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Folkmusiken i Norrbotten 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Norrbottenin lääni](http://finto.fi/yse/fi/page/Y505515)

**Comment by LeKorsu** [comment]
Onko tämä siis muutosesitys nykyiseen Norbotten-termiin?

**Comment by mariaforsen** [comment]
Norrbotten on maakunta ja Norrbottens län on lääni, tosin en tiedä tarvitaanko välttämättä molempia?

**Comment by mariaforsen** [comment]
Lääni ja maakunta eivät ole aivan sama asia, joten tämä on kyllä varmaan lisäys.
