### ISSUE TITLE
munniharppu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5516]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

munniharppu 

#### Ehdotettu termi englanniksi   

Jew's harp 

#### Ehdotettu termi ruotsiksi   

mungiga 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soittimet](http://www.yso.fi/onto/yso/p7110) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85070508> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Munniharppu 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Vaihtoehtoiset termit ja ilmaisut   

juutalainen harppu, juutalaisenharppu, märistysrauta, suuharppu 

#### Perustelut ehdotukselle   

Kyseistä soitinta kuvaavaa termiä ei ole ennestään YSAssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Eesti parmupill = Estonian Jew's harp 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [munniharppu](http://finto.fi/yse/fi/page/Y505516)

**Comment by mariaforsen** [comment]
Sv. mungiga ET munharpa ET trump
