### ISSUE TITLE
minipuutarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5517]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

minipuutarhat 

#### Ehdotettu termi englanniksi   

fairy gardens 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puutarhat](http://www.yso.fi/onto/yso/p2225) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Perustelut ehdotukselle   

Näistä on alettu kysellä. Ehkä "minipuutarha" ja "pienoismallit" ei ole paras sana; mikä olisi.
Ei tarkoiteta (vain) pienoisputarhaa ruukussa, vaan esim. pienoiskasvihuonetta pienine kasveineen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Myllyneva, Mika: Bonkei : rakenna oma pienoismaisema 

**Ehdottajan nimi:** Päivi Meriläinen 
**Ehdottajan organisaatio:** Järvenpän kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** paivi.merilainen@jarvenpaa.fi **Termiehdotus Fintossa:** [minipuutarhat](http://finto.fi/yse/fi/page/Y505517)

**Comment by jtuohini** [comment]
LCSH-vastine osittain ainakin **Gardens, Miniature** [http://id.loc.gov/authorities/subjects/sh85053143], jolla monta ST-suhdetta, mm. **Glass gardens** [http://id.loc.gov/authorities/subjects/sh85055149]?

**Comment by mirmaid** [comment]
Minipuutarha on selvästi käytetympi kuin pienoispuutarha (vaikka jälkimmäinen ehkä kuulostaisi vähän paremmalta sanastoon). YSAssa on _bonkei_, mutta se ei kai varsinaisesti ole puutarha. Tosin myös minipuutarha-sanaa käytetään melko vapaasti, myös tekokasveista.

**Comment by mariaforsen** [comment]
Sv. miniträdgårdar ET miniatyrträdgårdar

**Comment by YSA-kokous** [comment]
minipuutarhat
