### ISSUE TITLE
oheisharjoittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5518]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oheisharjoittelu 

#### Vaihtoehtoiset termit ja ilmaisut   

oheisliikunta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

Esim UKK-instituutti käyttä termiä sivuillaan. http://www.terveurheilija.fi/kymppiympyra/kehonhuoltojapalautuminen/huoltavaoheisharjoittelujamuuliikunta 

#### Tarkoitusta täsmentävä selite   

Kaikki lajiharjoittelun ulkopuolella tapahtuva harjoittelu, jonka tarkoitus on tukea varsinaisen lajin harjoittelua 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Nuoren urheilijan fyysinen harjoittelu. 

**Ehdottajan nimi:** Kukka-Maritta Taskinen 
**Ehdottajan organisaatio:** Savonia-ammattikorkeakoulu 
**Ehdottajan sähköpostiosoite:** kukka-maritta.taskinen@savonia.fi **Termiehdotus Fintossa:** [oheisharjoittelu](http://finto.fi/yse/fi/page/Y505518)

**Comment by satuniininen** [comment]
Englanniksi auxiliary training tai additional training, mutta vaatinee sulkutarkenteen.

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. mahdollisesti tilläggsträning? Vaatii siinä tapauksessa tarkenteen. Kysytään aiheen asiantuntijoilta.

**Comment by YSA-kokous** [comment]
Otetaan tämä ja lajiharjoittelu, tutkitaan vielä tarvitseeko tarkenteen.

**Comment by mariaforsen** [comment]
Sv. tilläggsträning (idrott)
