### ISSUE TITLE
Hollola -- Tiirismaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5520]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hollola -- Tiirismaa](http://www.yso.fi/onto/ysa/Y109165) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Termi/käsite kattaa nyt itse kylän, "vuoren" ja myös siellä sijaitsevan virkistysalueen. Tämä on ongelmallista yso-paikkojen linkityksen kannalta. 

#### Ehdotettu muutos   

Jaetaan useammaksi käsitteeksi tai korjataan huomautus. 

#### Ehdottaja   

Henri Ylikotila 

#### Ehdottajan sähköpostiosoite   

henri.ylikotila@helsinki.fi

**Comment by ilona-x** [comment]
Jaettu YSAssa kylä & mäki:

Hollola -- Tiirismaa 
Tiirismaa

Lisäksi lisätty YSAan Tiirismaan luonnonsuojelualue
