### ISSUE TITLE
kuljetuspalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5521]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuljetuspalvelut](http://www.yso.fi/onto/ysa/Y96469) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kaksi merktitystä/mahdollista vastinetta ruotsiksi: färdtjänster ("sosiaalipalvelu, jossa asiakkaalle tarjotaan tai maksetaan kuljetus"), transporttjänster/service (yleiset palvelut, tavaroiden jne.). Pitäisikö jakaa? Ks. myös temaattiset ryhmät ja Melinda. 

#### Perustelut ehdotukselle   

Ruotsiksi on aikaisemmin ollut vastineena vain: färdtjänst. Tämä on nimenomaan vain sosiaalipalvelu. Tarvitaan myös JUHO-työssä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Mitä kaikkea färdtjänster-kattaa? Sopiiko siihen esim. koulukyydit? Jos kyseessä on vain vammaispalvelulain ja sosiaalihuoltolain mukaiset palvelut, mikähän olisi mahdollinen tarkenne? _Sosiaalipalvelut_ voi olla liian epämääräinen.

**Comment by AuHo22** [comment]
Mielestäni kuljetuspalvelut-termin käännös ruotsiksi pitäisi olla nimenomaan tuo transporttjänster/service, eli kattaa paljon muutakin, mutta myös em. sosiaalipalvelut.

**Comment by mariaforsen** [comment]
Färdtjänst on nimenomaan sosiaalipalvelu ikääntyneille ja liikuntavammaisille yms. Mielelläni kääntäisin laajemman mukaan, mutta kaikki esim. MOTin sanakirjat, WSOYn suomi-ruotsi suursanakirja ja TEPA antoivat nimenomaan sosiaalipalvelumerkityksen, joten tarvitaan sitten YSAn sisäinen päätös että tämä viittaa kaikenlaiseen kuljetukseen. On myös paljon viranomaissivustoja jossa käytetään kuljetuspalvelut nimenomaan sosiaalipalvelumerkityksessä, joten färdtjänst-termiä ei voi kovin kevyin perustein poistaa (varsinkin kun tämä on tulossa käyttöön myös JUHOn kaltaisiin sanastoihin, jotka viranomaiset käyttävät..) Transportservice/tjänster käytetään eniten tavaroiden kuljetuksesta. 

Sen lisäksi olisi varmaan hyvä miettiä käyttäjän tarpeita; haluaako se joka on kiinnostunut nimenomaan tästä lakisääteisestä sosiaalihuollon kuljetuspalvelusta todella myös kaikenlaista aineistoa, jossa käsitellään tavarankuljetuksia yms. yleisiä kuljetuksia?

**Comment by satuniininen** [comment]
Kannatan jakamista ja ehdotan:
kuljetuspalvelut (tavaraliikenne)
kuljetuspalvelut (sosiaalihuolto)

**Comment by YSA-kokous** [comment]
kuljetuspalvelut ST vammaisten ja ikääntyneiden kuljetuspalvelut (?)

**Comment by mirmaid** [comment]
Yllä ehdotettua muotoa ei löydy ainakaan Google-haulla, jonkin verran viitteitä tulee fraasilla _vaikeavammaisten kuljetuspalvelu_. 

_Kunnan on järjestettävä vaikeavammaiselle henkilölle kohtuulliset kuljetuspalvelut niihin liittyvine saattajapalveluineen, päivätoimintaa, henkilökohtaista apua sekä palveluasuminen, jos henkilö vammansa tai sairautensa johdosta välttämättä tarvitsee palvelua suoriutuakseen tavanomaisista elämän toiminnoista._ https://www.finlex.fi/fi/laki/ajantasa/1987/19870380

**Comment by mirmaid** [comment]
_Liikkumista tukevia palveluja järjestetään henkilöille, jotka eivät kykene itsenäisesti käyttämään julkisia liikennevälineitä sairauden, vamman tai muun vastaavanlaisen toimintakykyä alentavan syyn takia ja jotka tarvitsevat palvelua asioimisen tai muun jokapäiväiseen elämään kuuluvan tarpeen vuoksi._ https://www.finlex.fi/fi/laki/alkup/2014/20141301

**Comment by mariaforsen** [comment]
Kannattaisin Sadun ehdottama kuljetuspalvelut (tavaraliikenne), kuljetuspalvelut (sosiaalihuolto)

**Comment by mirmaid** [comment]
Tekisin ehkä erillisen issuen tavaraliikenteestä, koska meillä on nyt tavarankuljetus (ja rahtaus) KÄ _kuljetus_, joten voi vaatia pohdintaa myös sen osalta. 

Kokeillaan tarkenteella _(sosiaalihuolto)_.

**Comment by tpalonen** [comment]
Sopisiko "Kuljetuspalvelut (sosiaalihuolto)" ohjaustermiksi "henkilökuljetukset" nyt kun sitä ei erikseen otettu sanastoon?
https://github.com/Finto-ehdotus/YSE/issues/5263

**Comment by ilona-x** [comment]
YSAssa myös logistiikkapalvelut

**Comment by mirmaid** [comment]
Eli voisiko olla kuljetuspalvelut (tavaraliikenne) KÄ _logistiikkapalvelut_?

**Comment by YSA-kokous** [comment]
kuljetuspalvelut (tavaraliikenne) KÄ logistiikkapalvelut
