### ISSUE TITLE
T-paidat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5522]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

T-paidat 

#### Ehdotettu termi ruotsiksi   

T-shirtar 

#### Ehdotettu termi englanniksi   

T-shirts 

#### Ehdotettu yläkäsite YSOssa (LT)   

[paidat](http://www.yso.fi/onto/yso/p22561) 

#### exactMatch   

T-shirts : LC control no.:    sh 85131768 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578) 

#### Perustelut ehdotukselle   

Termiä T-paidat on Melindassa käytetty YSA:n asiasanana aika monta kertaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Graphis T-shirt : an international compilation of the best in T-shirt design = eine internationale Zusammenstellung des besten T-shirt-designs.1 

#### Tarkoitusta täsmentävä selite   

Wikipedia: https://fi.wikipedia.org/wiki/T-paita 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [T-paidat](http://finto.fi/yse/fi/page/Y505522)

**Comment by mariaforsen** [comment]
Sv. T-tröjor ET T-shirtar ET T-skjortor
