### ISSUE TITLE
kuntoutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5523]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuntoutuminen](http://www.yso.fi/onto/ysa/Y108615) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kuntoutus KT kuntoutuminen. Onko mahdollista yhdistää nämä, kuten esim. MESHissä on tehty? 

#### Perustelut ehdotukselle   

Ruotsiksi on tällä hetkellä vastineena "habilitering", mikä on väärin. Ellei näitä voida yhdistää, laitetaan ruotsiksi mahdollisesti "rehabiliteras", koska hyväksyttäviä ratkaisuja ei oikeastaan ole. Samanlaista "passiiv-aktiivi-eroa" ei siis ruotsiksi tehdä. Habilitering taas olisi oikeastaan toinen vastine rehabilitering-termille (ks. TEPA, NE, jne.), mutta eriävällä merkityksellä. Tarvitaan myös JUHO-työssä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by jtuohini** [comment]
Nyky-YSAn termipari **kuntoutus** (KT _kuntouttaminen_) ja **kuntoutuminen** on analogialtaan sama kuin vaikkapa **opetus** (KT _opettaminen_) ja **oppiminen**, joten ainakin maallikon korvaan yhdistäminen kuulostaa aika hämmentävältä vaihtoehdolta.

**Comment by mariaforsen** [comment]
Tässä on kieltenvälinen ero, jonkinlainen kompromissi on siis tarpeen. Kuinka moni kirja muuten käsittelee kuntoutusta muttei ollenkaan kuntoutumista tai toisinpäin?

**Comment by mirmaid** [comment]
_Kuntoutus_ on paljon käytetympi ja aivan välttämätön termi, ongelmana on että on mahdollista kuntoutua myös ilman aktiivista kuntoutusta ja toisaalta näkökulma voi olla nimenomaan kuntoutumisessa potilaan kannalta. YSAssa on myös _toipuminen_ (ruotsiksi _bli återställd_) ja _parantuminen_, mutta vaatii ehkä vähän lisäselvittelyä jos halutaan poistaa _kuntoutuminen_ kokonaan.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by AuHo22** [comment]
Meillä tietokannasta löytyy 163 osumaa kuntoutuminen-haulla. Olen huomannut, että Allärsissä on jonkin verran näitä bli -muotoja, kuten yllä bli återställd,  mutta nekään ei sitten ole kovin suositeltavia?

**Comment by mirmaid** [comment]
Melindassa 245 viitettä joissa on _kuntoutuminen_, mutta ei termiä _kuntoutus_. Tutkitaan voiko kuvailla riittävän hyvin termeillä _kuntoutus, toipuminen, parantuminen_.

**Comment by YSA-kokous** [comment]
kuntoutuminen KÄ kuntoutus, toipuminen, parantuminen
