### ISSUE TITLE
lautat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5524]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lautat](http://www.yso.fi/onto/ysa/Y108755) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö jakaa tai rajata? 

#### Perustelut ehdotukselle   

On monimerkityksinen, ks. Kielitoimiston sanakirja:  
-puista tm. kelluvista esineistä koottu t. kellukkeille rakennettu lava, jota käytetään vesikuljetusvälineenä, työalustana vesillä tms.
-autoja ja rautatievaunuja tms. kuljettava erikoisrakenteinen matkustaja-alus. 
-= lossi. 
Ruotsinkielisenä vastineena on nyt "flottar", joka viittaa vain ykkösmerkitykseen. Sen lisäksi on lossit=färjor. Ykkösmerkityksessä käytetty esim.: Kon-Tiki : lautalla yli Tyynenmeren / Thor Heyerdahl ; suomentanut Oiva Talvitie.
Jos jaetaan olisi mahdollista ratkaista: flottar, färjor ja linfärjor=lossit (jos on rajoitettu vaijerilosseihin). Nykytilanteessa on siis ruotsiksi hierarkiavirhe ja vääristyneet hakutulokset. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by satuniininen** [comment]
Melinda-osumista suurin osa näyttäisi käsittelevän (matkustaja)lauttoja tai lauttaliikennettä. Jonkun verran löytyy myös ykkösmerkitystä, esim. juuri Kon-Tikiä käsittelevää aineistoa sekä _Notable boats : forty remarkable craft, forty great adventures_ ja _Saunalautan CE-hyväksyntä_.  Pitäisi siis jakaa ja mahdollisesti miettiä sulkutarkenteet. esim.
lautat (matkustaja-alukset) 
lautat (rakennelmat)

**Comment by mirmaid** [comment]
Huom. JUPOssa muodossa vesiliikennelautat.

**Comment by mariaforsen** [comment]
JUPOn muoto ei anna juuri hakutuloksia googlessa.

**Comment by YSA-kokous** [comment]
lautat (matkustaja-alukset)
lautat (rakennelmat)
