### ISSUE TITLE
keuhkolaajentuma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5525]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

keuhkolaajentuma 

#### Ehdotettu termi ruotsiksi   

lungemfysem 

#### Ehdotettu termi englanniksi   

Pulmonary Emphysema 

#### Ehdotettu yläkäsite YSOssa (LT)   

[keuhkoahtaumatauti](http://www.yso.fi/onto/yso/p11375) 

#### exactMatch   

FinMeSH : <http://finto.fi/mesh/fi/page/D011656> 
Wikipedia : https://fi.wikipedia.org/wiki/Keuhkolaajentuma 
LCSH : <http://id.loc.gov/authorities/subjects/sh85042841> 

#### Vaihtoehtoiset termit ja ilmaisut   

emfyseema 

#### Perustelut ehdotukselle   

Melinda:
keuhkolaajentuma x 2
emfyseema x 2 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Yksilöllisten alttiustekijöiden merkitys rakennustyöntekijöiden vaikean asbestoosin ja emfyseeman synnyssä 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [keuhkolaajentuma](http://finto.fi/yse/fi/page/Y505525)

**Comment by mariaforsen** [comment]
Sv. lungemfysem
