### ISSUE TITLE
keräilykorttipelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5526]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

keräilykorttipelit 

#### Ehdotettu termi ruotsiksi   

samlarkortspel 

#### Ehdotettu termi englanniksi   

collectible card games 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit välineen mukaan](http://www.yso.fi/onto/yso/p1735) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2002002380.html> 
Wikipedia : https://fi.wikipedia.org/wiki/Ker%C3%A4ilykorttipeli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Generation decks : the unofficial history of gaming phenomenon Magic: The Gathering / Titus Chalk 

#### Perustelut ehdotukselle   

Yleistyvä käsite. 

**Ehdottajan nimi:** Kirsi Siika-Aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [keräilykorttipelit](http://finto.fi/yse/fi/page/Y505526)

**Comment by mirmaid** [comment]
YSAssa on _keräilykortit_ (5 viitettä Melindassa).

**Comment by mariaforsen** [comment]
Sv. samlarkortspel
