### ISSUE TITLE
tuskaturismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5527]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tuskaturismi 

#### Ehdotettu termi englanniksi   

dark tourism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matkailu teeman mukaan](http://www.yso.fi/onto/yso/p5989) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh2013000619.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Yleistyvä ilmiö. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Thomas H. Cook : Tragic shores 

**Ehdottajan nimi:** Kirsi Siika-Aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [tuskaturismi](http://finto.fi/yse/fi/page/Y505527)

**Comment by satuniininen** [comment]
Googlessa 840 osumaa, Melindassa 0. Täällä eriteltynä myös tuskaturismin alalajeja: http://ylioppilaslehti.fi/2011/11/tuskaturismin-jaljilla/

Tästä tosiaan puhutaan enenevässä määrin, mutta mahtaako suomenkielinen termi olla vielä ihan vakiintunut? Jonkin verran käytetään myös muotoja _musta turismi_ ja _synkkä turismi_.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4333

**Comment by tpusa** [comment]
Termin vakiintumista odotellessa täälläkin. "Synkkää turismia" käytetty mm. parissa theseuksesta löytyvässä opinnäytetyössä (https://www.theseus.fi/handle/10024/79425 ja https://theseus.fi/handle/10024/99784). Wikipediassa lisäksi "tumma turismi": https://fi.wiktionary.org/wiki/tumma_turismi.

**Comment by krinay** [comment]
Termi ei tosiaan valitettavasti taida vielä olla riittävän vakiintunut. Tarvetta sille kyllä olisi. LCSH:ssa dark tourism -termi korvaa termit black tourism, grief tourism ja thanatourism.

Aihetta lähellä on myös käsite _synkkä kulttuuriperintö_ (dark heritage/difficult heritage), jota olen kaivannut YSA:an, mutta en vielä osannut ehdottaa. Mm. _Lapin synkkä kulttuuriperintö_ -projekti, 
http://blogs.helsinki.fi/lapland-dark-heritage/. 
(Tuo blogi ei ainakaan nyt avaudu, mutta ks. esim.
http://www.aka.fi/fi/akatemia/media/Ajankohtaiset-uutiset/2017/saksalaissotilaat-jattivat-jalkensa-lappiin/).

**Comment by LeKorsu** [comment]
Sotaturismia on harjoitettu jo 1800-luvulla. Muistan tehneeni tiedonhakua asiasta.  Sanomalehtien tekstiarkistoista (Sanoma ja Alma Media) tulee esiin vain muutama osuma. Rinnakkain näkyy käytetyn esim. tuskaturismia, mustaa matkailua.

Lili Wessman

Kuoleman, tuhon ja väkivallan perässä reissaaminen kasvattaa suosiotaan. Kuuluisimpien pahojen paikkojen turistimäärät paisuvat vuosi vuodelta.

Keskitysleirit, sodan ja luonnonmullistusten runtelemat alueet, kidutuskammiot, vankilat ja slummit synnyttävät matkailubisnestä. Ilmiö on niin nuori, ettei sille ole vakiintunut suomenkielistä nimeä.

Englanniksi nimillä dark tourism, black tourism ja grief tourism tunnettu termi suomentuu synkäksi ja mustaksi matkailuksi sekä suruturismiksi. Luultavimmin jokainen vähänkään maailmalla kulkenut reissaaja on harrastanut suru- ja synkistelyturismia.

Mm. Lapin Kansassa (20.1.2012) ilmestyneestä jutusta pätkä:

Pahat paikat: Tuskaturismi on kasvava matkailubisnes
--
 
 
Lili WessmanKuoleman, tuhon ja väkivallan perässä reissaaminen kasvattaa suosiotaan. Kuuluisimpien pahojen paikkojen turistimäärät paisuvat vuosi vuodelta.Keskitysleirit, sodan ja luonnonmullistusten runtelemat alueet, kidutuskammiot, vankilat ja slummit synnyttävät matkailubisnestä. Ilmiö on niin nuori, ettei sille ole vakiintunut suomenkielistä nimeä.Englanniksi nimillä dark tourism, black tourism ja grief tourism tunnettu termi suomentuu synkäksi ja mustaksi matkailuksi sekä suruturismiksi. Luultavimmin jokainen vähänkään maailmalla kulkenut reissaaja on harrastanut suru- ja synkistelyturismia.Suomalaisille tuttuja tuskaturismin kohteita ovat Auschwitz, KGB-museot, Karjalan taistelutantereet, Pompeijin rauniot, Kwai-joen silta ja tsunamialue Thaimaassa, Kambodzan kuoleman kentät ja Ground Zero New Yorkissa.Kärsimyksen tyyssijoille matkaaminen ei suinkaan ole uutta.- Joidenkin tutkijoiden mukaan ilmiön juuret ovat 1700- ja 1800-lukujen romantiikan ajassa. Jo silloin järjestettiin matkoja Waterloon taistelun tapahtumapaikalle ja Pompeijin rauniokaupunkiin, kertoo tutkija Tuomas Hovi.

**Comment by mirmaid** [comment]
Varmaan tosiaan uusi enemmänkin tutkimuskohteena kuin ilmiönä.

**Comment by mariaforsen** [comment]
Sv. mörk turism

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
musta matkailu (2720)
synkkä matkailu (1480)
tumma turismi (1450)
tuskaturismi (1170)
synkkä turismi (502)
musta turismi (226)

**Comment by LeKorsu** [comment]
Musta matkailu saa minun kollegoiltani eniten kannatusta. Ohjaustermiksi joitakin muita muotoja?

**Comment by YSA-kokous** [comment]
musta matkailu

**Comment by mariaforsen** [comment]
Sv. mörk turism ET svart turism
