### ISSUE TITLE
peippo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5529]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

peippo 

#### Ehdotettu termi englanniksi   

Chaffinch 

#### Ehdotettu yläkäsite YSOssa (LT)   

[peipot](http://www.yso.fi/onto/yso/p6158) 

#### exactMatch   

laji.fi : https://laji.fi/taxon/MX.36237 

#### Vaihtoehtoiset termit ja ilmaisut   

Fringilla coelebs 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Tarkoitusta täsmentävä selite   

Suomen yleisimpiä lintuja 

#### Perustelut ehdotukselle   

Suomen yleisimpiä lintuja 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arton aineisto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [peippo](http://finto.fi/yse/fi/page/Y505529)

**Comment by mirmaid** [comment]
Laji ja suku (Fringilla)/heimo (Fringillidae) vaativat tarkenteet.

**Comment by PaiviLipsanen** [comment]
Yläkäsite voisi olla kaikille nyt peipot-yläkäsitteen alla oleville - peipot (heimo - Fringillidae). 
Kanarialintu kuuluu sukuun keltahempot (Serinus) ja punatulkku sukuun punatulkut (Pyrrhula). 
Maailman lintujen suomenkieliset nimet - http://nimisto.birdlife.fi:3000/

**Comment by mariaforsen** [comment]
Sv. 
-bofink 
-finkar

**Comment by YSA-kokous** [comment]
peippo (laji) & peipot (heimo)
