### ISSUE TITLE
puumajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5530]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puumajat 

#### Ehdotettu termi ruotsiksi   

trädhus 

#### Ehdotettu termi englanniksi   

tree houses 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennelmat](http://www.yso.fi/onto/yso/p7539) 

#### Assosiatiiviset (RT)   

[leikkimökit](http://www.yso.fi/onto/yso/p18638) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh85137226.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Aiheesta on kirjoja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tree houses : fairy-tale castles in the air 

**Ehdottajan nimi:** Kirsi Siika-Aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [puumajat](http://finto.fi/yse/fi/page/Y505530)

**Comment by mirmaid** [comment]
Melindassa kerran kaunossa.

**Comment by ilona-x** [comment]
Melinda: 
puut + majat x 9

**Comment by mariaforsen** [comment]
SAO: trädkojor korvattuna (leikkiin tarkoitetut). Trädhus käytetään vain jos on kysymys asumiseen yms. tarkoitetusta talosta.

**Comment by mariaforsen** [comment]
Sv. trädkojor
