### ISSUE TITLE
Kombucha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5531]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kombucha 

#### Ehdotettu termi englanniksi   

Kombucha tea 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tee](http://www.yso.fi/onto/yso/p15063) 

#### exactMatch   

LCSH : <http://id.loc.gov/authorities/subjects/sh96005234.html> 
MeSH / FinMeSH : <http://finto.fi/mesh/fi/page/D000068858> 
Wikipedia : https://fi.wikipedia.org/wiki/Kombutsa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Tarkoitusta täsmentävä selite   

Juoma, joka valmistetaan sokeroidusta teestä käymisen avulla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The big book of kombucha : brewing, flavoring, and enjoying the health benefits of fermented tea 

#### Perustelut ehdotukselle   

Suosittua nykyisin, kirjoja aiheesta ilmestyy. 

**Ehdottajan nimi:** Kirsi Siika-Aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** kirsi.siika-aho@hel.fi **Termiehdotus Fintossa:** [Kombucha](http://finto.fi/yse/fi/page/Y505531)

**Comment by satuniininen** [comment]
Sanastossa on jo volgansieni (engl. kombucha), jota on käytetty Melindassa kahdesti (saman nimekkeen kaksi painosta) teoksessa, joka näyttäisi käsittelevän volgansienen ja volgansieniteen terveysvaikutuksia.

Tarvitaanko siis molempia? Todennäköisesti volgansientä käsitellään juuri teejuoman perspektiivistä, joten pidän tätä ehdotettua muotoa sinällään kyllä parempana.

**Comment by LeKorsu** [comment]
Wikipedia-artikkelissa näyttää olevan kirjoitusmuotona kombutsa, https://fi.wikipedia.org/wiki/Kombutsa, joskin artikkelissa viitataan Ysoon: Kansalliskirjaston "Yleinen suomalainen ontologia" suosittelee nimitystä volgansieni.[1]
Artikkelissa mainitaan myös japanilainen kombucha: Japanissa juotavalla kombucha-juomalla on kombutsan kanssa yhteistä vain nimi. Japanissa kombucha on merihaurasta (kombu) valmistettua uutejuomaa (cha). Teesienijuoma on saanut nimensä kombuchasta luultavimmin väärinkäsityksenä.

Väärinkäsitysten välttämiseksi tekisi mieli pitäytyä tuossa volgansienessä ja kombucha ohjaustermiksi, mutta veikkaanpa silti, että yleisessä kielenkäytössä tuo kombucha tulee olemaan valtavirtaa.

**Comment by mariaforsen** [comment]
Sv. kombucha ET tesvamp ET volgasvamp

**Comment by YSA-kokous** [comment]
volgansieni, kombutsa KÄ kombucha
