### ISSUE TITLE
epookkipuvut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5532]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

epookkipuvut 

#### Vaihtoehtoiset termit ja ilmaisut   

näyttämöpuvut 

#### Tarkoitusta täsmentävä selite   

Määritelmä varhaisemman aikakauden vaatetusta mukaileva esiintymispuku
Selite Historiallisen esikuvan mukaan tai sitä melko uskollisesti noudatellen suunniteltu esiintymispuku vailla voimakkaita fantasiaelementtejä. Kyse on historiallisen vaatetuksen representaatiosta, johon sisältyy aina myös tulkintaa.

Epookkipuvuilla on pitkä historia, johon esimerkiksi vaatetuksen ja pukeutumisen historian tutkimus on vaikuttanut. Epookkipuvun estetiikka on sitoutunut toteutusaikaansa, esimerkiksi 1950-luvulla suunniteltu renessanssipuku sisältää piirteitä aikansa kulttuurista.
Varhaisemman aikakauden vaatetusta mukailevasta esiintymispuvusta on saatettu käyttää monia erilaisia ilmauksia, kuten esimerkiksi tyylipuku, aikakausipuku, periodipuku, historiapuku, historiallinen puku, historiallinen näyttämöpuku, historiallinen teatteripuku ja historiallinen elokuvapuku. 

#### Perustelut ehdotukselle   

en ole varma miten epookkipuvut ja näyttämöpuvut eroavat toisistaan vai eroavatko 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.teatterimuseo.fi/wp-content/uploads/Unelmien_kuteita.pdf 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi

**Comment by jtuohini** [comment]
Pohdittu sanasuhde olisi varmaan:
  **epookkipuvut**
    KT  historialliset näyttämöpuvut
    KT  historialliset teatteripuvut
    jne.
    LT  näyttämöpuvut

**Comment by satuniininen** [comment]
engl. period costume

**Comment by mariaforsen** [comment]
Sv. epokdräkter
