### ISSUE TITLE
burleski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5533]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[burleski](http://www.yso.fi/onto/ysa/Y171587) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSAssa on nyt myös burleskit (sävellykset), joten tämä tarvitsee tarkenteen. Ehdotettu tarkennetta (teatteri). 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Voisi ehkä olla myös _burleski (esitystaide)_?

**Comment by mariaforsen** [comment]
Eli burleski kirjallisuudessa jätetään tässä vaiheessa pois? Voi tietty ottaa myöhemmin tarpeen tullen.

**Comment by YSA-kokous** [comment]
burleski (esitystaide)

**Comment by mariaforsen** [comment]
Allärsissa on tähän asti ollut: burlesk (stilar) (fi. tyylit) niin että on kattanut myös kirjallisuutta yms. Melindassa nyt esim.:

Cassandra, the fortune-teller : prophets, gipsies and Victorian burlesque / Laura Monrós-Gaspar ; 

Gurlesque : the new grrly, grotesque, burlesque poetics / [edited by Lara Glenum and Arielle Greenberg] ;

The Oxford book of parodies / edited by John Gross ; Parody / Simon Dentith ; 

Female trouble : Feminiinisyys ja femmeniinisyys Bettina Rheimsin ja Ellen von Unwerthin valokuvissa / Elina Suoyrjö.

Eli myös esim. kirjallisuudessa ja valokuvataiteessa käytetään tämä.

**Comment by YSA-kokous** [comment]
burleski (tyylit)
