### ISSUE TITLE
moodit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5534]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[moodit](http://www.yso.fi/onto/ysa/Y175470) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Huomautus:
Sanalla on monia merkityksiä. 1) Tapa, laatu, tapahtumisen kaavio. 2) Matematiikassa tyyppiarvo, valta-arvo. 3) Musiikissa kiinteä rytmikaava, rytmimodaali, 1100-1200-luvuilla; keskiajalla gregoriaanisen laulun piirissä kehittyneet kirkkosävellajit. 4) Kielitieteessä katso tapaluokat. 4) Kirjallisuustieteessä ja elokuvatutkimuksessa elokuvan tai kirjan kerronnan laji tai tyyli. 5) Peleissä ja varsinkin moninpeleissä pelimuoto. 6) Filosofiassa olemisen tai tapahtumisen tietty perustapa, substanssin epäitsenäinen tila tai laatu 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Melindassa vain 26 viitettä. Tarkennetaan _moodit (musiikki)_, päivitetään viitteet ja sen jälkeen ratkaistaan mitä muuta tarvitaan?

**Comment by jtuohini** [comment]
Mieluummin laittaisin muotoon **moodit (säveljärjestelmät)**, RT-suhteenaan **kirkkosävellajit**.

**Comment by tpalonen** [comment]
Mikä on moodin ja kirkkosävellajin ero? Ero olisi hyvä selittää käsitteiden huomatuksissa. Monen lähteen mukaan moodi = kirkkosävellaji. Jos käsitteet ovat hyvin likeiset, riittäisikö että olisi vain yksi käsite ja toinen termeistä ohjausterminä?

**Comment by TommiViitamies** [comment]
Moodeja on muissakin musiikkikulttuureissa kuin ns. länsimaisessa, jonka moodit ovat kirkkosävellajeja.

**Comment by tpalonen** [comment]
Kiitos vastauksesta! Tämä saattaa olla musiikkia kuvaileville selvää kauraa, mutta maalikolle olisi ehkä hyvä tehdä lisäksi huomautuksessa selväksi käsitteen ero (kirkkosävellajien lisäksi) myös sävelasteikkoon. Ainakin englanninkielinen Wikipedia käyttää mode ja scale -termejä iloisesti sekaisin.
https://en.wikipedia.org/wiki/Scale_(music)
https://en.wikipedia.org/wiki/Mode_(music)

**Comment by TommiViitamies** [comment]
Kylmiltään sanoisin tuohon, että skaalat on laajempi käsite kuin moodit. Sanallista määritelmää täytyy miettiä.

**Comment by YSA-kokous** [comment]
moodit (säveljärjestelmät)
Ero _sävelasteikot_ ja _kirkkosävellajit_ -termeihin pitäisi selkeyttää huomautuksissa.

**Comment by mariaforsen** [comment]
Sv. modus (tonsystem)

**Comment by satuniininen** [comment]
Melindasta löytyi kolme kertaa _moodit_ viittaamassa muuhun kuin säveljärjestelmiin:

- Defining the keyhole modes : the effects on the weld geometry and the molten pool behaviour in high power laser welding of stainless steels / Mikko Vänskä. **[hitsaus]**
- Dokumenttielokuvaajan ilmaisulliset keinot : kuvaajan rooli performatiivisessa dokumenttielokuvassa /Antti Ojala. **[dokumenttielokuvan moodit Bill Nicholsin mukaan]**
- Voiko lasta haastatella tosissaan? : lapsi toimittajan tietolähteenä / Esa Viippola. **[journalistinen moodimalli Mats Ekströmin mukaan]**

Lisäksi kerran ketju _moodit -- kirjallisuus_ teoksessa On literary worlds /Eric Hayot.

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): Tämä ei ole selvää kauraa, pitää miettiä uusiksi, jää seuraavaan kokoukseen

**Comment by jtuohini** [comment]
150 | __ \|a Musical intervals and scales
-- | --
__ \|a Intervals (Music)
__ \|a Modes, Musical
__ \|a Music \|x Modes
__ \|a Musical modes
__ \|a Musical scales and intervals
__ \|a Scales (Music)
__ \|w g \|a Music theory
__ \|a Musical temperament

**Comment by jtuohini** [comment]
LC control no.: | sh 85089007
-- | --
https://lccn.loc.gov/sh85089007
ML3809 Intervals : Acoustics and physics
  | ML3812 Scales : Acoustics and physics
  | MT45 Instruction
Musical intervals and scales
Intervals (Music)
  | Modes, Musical
  | Music --Modes
  | Musical modes
  | Musical scales and intervals
  | Scales (Music)
Music theory
  | Musical temperament

**Comment by ksornova** [comment]
Puhuimme tästä (vain muistiin):
moodit (sävelasteikot)
LT sävelasteikot
ST kirkkosävellajit
RT modaalisuus (sitten kun tämä tulee YSAan)

uusi termi (tehdään ehdotus): 
rytmimoodit
LT rytmioppi

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018:
 
**moodit (sävelasteikot)**
LT sävelasteikot
ST kirkkosävellajit
RT modaalisuus
