### ISSUE TITLE
albumit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5535]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[albumit](http://www.yso.fi/onto/ysa/Y127051) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava/tarkennettava. 

#### Perustelut ehdotukselle   

1. kansio. Valokuva-albumi.
2. muistokirja; kaunokirjallinen tm. tilapäisjulkaisu.
3. sarjakuvakirja, -julkaisu.
4. kaksi t. useampia äänilevyjä sisältävä kansio; useita kappaleita sisältävä äänilevy. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by asormune** [comment]
Tarvitaanko musiikkiin lainkaan? Olemassa on hierarkia ylhäältä alaspäin: tallenteet - äänitteet - äänilevyt

**Comment by mirmaid** [comment]
Käytetty paljon musiikin yhteydessä. 

Muut: 
valokuva-albumit - otetaan erikseen
muistokirjat - on jo omana terminään
leikekirjat - on jo omana terminään (toisinaan aiheena on myös päiväkirjojen koristelu)

**Comment by jaskaj** [comment]
Onko musiikin osalta tarvetta termin käytölle savikiekkoaikakauden historiallisessa merkityksessä ("kaksi t. useampia äänilevyjä sisältävä kansio")?

**Comment by tpalonen** [comment]
Riittäisikö musiikin näkökulmasta, että äänilevyt-käsitteellä olisi ohjaustermi "albumit (musiikki)" tms? 

Jos termiä tarvitaan sarjakuvan osalta niin termimuoto voisi olla "sarjakuva-albumit" ja ohjausterminä "albumit (sarjakuvat)". Sarjakuva-albumit löytyy KAUNOsta. Sarjakuvaromaanit ja sarjakuvat on jo sanastossa erikseen, mutta albumi on eri asia kuin sarjakuvaromaani. Lyhyitä Aku Ankka -sarjoja yhteen kokoava julkaisu voi olla sarjakuva-albumi, mutta ei sarjakuvaromaani.

**Comment by mariaforsen** [comment]
Äänilevyt on ollut tähän asti ruotsiksi: grammofonskivor. Albumeja musiikissa voi olla muitakin, nämä eivät ole ruotsiksi aivan sama asia. Kannatan siis albumien jakoa Mirjan ehdottamalla tavalla.

**Comment by LeKorsu** [comment]
Mikä siis olisi albumit (musiikki) oikea tarkenne, jos pelkkä musiikki ei riitä?

**Comment by YSA-kokous** [comment]
valokuva-albumit, albumit (musiikki)

**Comment by mariaforsen** [comment]
Tehdään ehdotus siitä että äänilevyt rajataan tarkoittamaan vanhempia levytyyppejä (ei esim. CD-levyjä), näin saadaan myös täsmäämään ruotsink. termin grammofonskivor kanssa.

**Comment by ilkkahaataja** [comment]
Luumu-kokous (31.10.2017): Äänitteiden osalta ehdotamme: **albumit (äänitteet)**.

**Comment by mariaforsen** [comment]
Lisäättekö Wikipedian käyttämä "musiikkialbumit" korvatuksi termiksi?

**Comment by mariaforsen** [comment]
Sv.  album (ljudupptagningar) ET album (musik), fullängdare, minialbum, musikalbum, studioalbum
