### ISSUE TITLE
kuorolaulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5536]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuorolaulu](http://www.yso.fi/onto/ysa/Y196744) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT kuorolaulaminen. MUSAn yhtyelaulaminen samoin muotoon yhtyelaulu. 

#### Perustelut ehdotukselle   

MUSAssa pääterminä kuorolaulaminen. Kuorolaulu-muoto on kuitenkin käytetympi. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Kuorolaulu / -laulaminen Melinda 64/0
Yhtyelaulu / -laulaminen 0/0; Google: 2650/8

**Comment by YSA-kokous** [comment]
kuorolaulu, yhtyelaulu

**Comment by mariaforsen** [comment]
Sv.
-körsång
-ensemblesång
