### ISSUE TITLE
pötsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5537]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pötsi 

#### Ehdotettu termi englanniksi   

rumen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ruumiinosat](http://www.yso.fi/onto/yso/p109) 

#### exactMatch   

LCSH : rumen 
AFO : https://finto.fi/afo/fi/page/p3932 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvittu esim. usean väitöskirjan kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Rapeseed oil in ruminants diet : its effect on rumen metabolism and animal performance, Milk production and physiological responses to concentrate supplementation of dairy cows grazing timothy-meadow fescue swards, Silage fermentation in relation to the feeding value with special reference to enzyme-treated grass silage, Assessment of the flow of soluble dietary non-ammonia nitrogen escaping degradation in the rumen of dairy cows fed grass silage based diets, Quality of supplementary feed protein for growing cattle 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [pötsi](http://finto.fi/yse/fi/page/Y505537)

**Comment by mariaforsen** [comment]
Sv. våm ET vom
