### ISSUE TITLE
palonestoaineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5538]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[palonestoaineet](http://www.yso.fi/onto/ysa/Y103856) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastossa nyt sekä palonestoaineet että palosuoja-aineet, onko yhdistäminen mahdollista? 

#### Perustelut ehdotukselle   

Ovat synonymejä? Ks. Kielitoimiston sanakirja, TEPA, Wikipedia jne. Ruotsin vastine ongelmallinen. Näiden välillä ei nyt ole edes RT-suhdetta. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
palosuoja-aineet KÄ _palonestoaineet_

**Comment by mariaforsen** [comment]
Sv. flamskyddsmedel
