### ISSUE TITLE
ornamentiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5539]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ornamentiikka](http://www.yso.fi/onto/ysa/Y97877) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

On myös musiikin (78) käsite 

#### Ehdottaja   

Anu Sormunen 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto 

#### Ehdottajan sähköpostiosoite   

anu.sormunen@jkl.fi 

#### Perustelut ehdotukselle   

musan sulautus ysaan

**Comment by jtuohini** [comment]
Termi pitäisi jakaa, jotta siitä olisi luontevat RT-suhteet **koristemaalaus**- ja **koloratuuri**-asiasanoihin; nyt menneet iloisesti sekaisin. Mutta lienee helposti korjattavissa.

**Comment by mirmaid** [comment]
_Ornamentiikka (musiikki)_ ja _ornamentiikka (koristetaide)_?

**Comment by jaskaj** [comment]
Kannatan musiikin osalta muotoa "ornamentiikka (musiikki)".

**Comment by YSA-kokous** [comment]
Lisätään tarkenteet, tutkitaan koristetaide vs. kuvataide.

**Comment by mirmaid** [comment]
Koristetaide on yläkäsite, joten sopinee myös tarkenteeksi (näin jo muodostettu KOKOssa).

**Comment by mariaforsen** [comment]
Sv. 
-ornamentik (musik)
-ornamentik (dekorativ konst)
