### ISSUE TITLE
karhunvatukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5540]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

karhunvatukka 

#### Ehdotettu termi ruotsiksi   

björnbär 

#### Ehdotettu termi englanniksi   

blackberry 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Karhunvatukka 
LCSH : Blackberries 

#### Tarkoitusta täsmentävä selite   

Vatukoista on muitakin lajeja YSA:ssa, mm. vadelma. 

#### Perustelut ehdotukselle   

Karhunvatukkaa on jo käytetty Melindassa YSA:n asiasanana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Proceedings of the Seventh International Rubus-Ribes Symposium 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [karhunvatukka](http://finto.fi/yse/fi/page/Y505540)

**Comment by PaiviLipsanen** [comment]
Voitaneen ottaa YSAan.
Systematiikka vaikuttaa vielä epäselvältä, en ole varma LCSH:n käännöksestä, 
Kassussa nimenä karhunvattu ja tieteellisenä nimenä Rubus Karhunvattu-Ryhmä, Björnbär-Gruppen
https://finto.fi/kassu/fi/page/k104487
Wikipediassa tieteellinen nimi on Rubus fruticosus
https://fi.wikipedia.org/wiki/Karhunvatukka
Laji.fi ei tunne näillä nimillä.

**Comment by mariaforsen** [comment]
Sv. björnbär
