### ISSUE TITLE
sauvakirkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5541]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sauvakirkot 

#### Ehdotettu termi ruotsiksi   

stavkyrkor 

#### Ehdotettu termi englanniksi   

stave churches 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puukirkot](http://www.yso.fi/onto/yso/p3649) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85127623.html> 
Svenska ämnesord : Stavkyrkor 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3086212 

#### Tarkoitusta täsmentävä selite   

Sauvakirkko on skandinaavinen varhaiskeskiaikainen puukirkkotyyppi, jossa käytettiin pystysalvosta. 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [sauvakirkot](http://finto.fi/yse/fi/page/Y505541)

**Comment by mirmaid** [comment]
MAO-ontologiassa. Melindassa 17 viitettä.

**Comment by mariaforsen** [comment]
Sv. stavkyrkor
