### ISSUE TITLE
afro

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5542]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[afro](http://www.yso.fi/onto/ysa/Y214379) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteen poistaminen tai termin muuttaminen esimerkiksi muotoon "afrikkalainen populaarimusiikki". 

#### Perustelut ehdotukselle   

Käsite on peräisin MUSAsta. Tällaista termiä ei esiinny kirjallisuudessa tai musiikillisessa diskurssissa ylipäätään. Vaikuttaa, että MUSA kehittänyt termin itse.  Esim. Otavan musiikkitietosanakirja, Grove, All Music Guide tai LCSH eivät tunne "afro"-termiä. Kielitoimiston sanakirjan ja Wikipedian mukaan "afro" on kampaustyyli. Käsitteen määritelmä YSAssa on "Yleisnimitys erilaisille afrikkalaisille maailmanmusiikkityyleille." Miten tärkeä tällainen käsite on? YSAan/YSOon ei yleisesti ole ollut tapana ottaa käsitteitä taidemuodoista maantieteellisesti rajattuna, nämähän ovat ketju-tyyppisiä termejä. Poikkeuksiakin toki on, esim. latinalaisamerikkalainen musiikki ja slaavilainen kirjallisuus. Toisaalta "afrikkalainen populaarimusiikki" on vaikeasti rajattava käsite. MUSAssa "afron" alakäsitteenä ei esim. ole "rai", vaikka rai on algerialaista (maailman)musiikkia. Musiikkikulttuurien yleisesityksissä (esim. Worlds of Music -kirja) Pohjois-Afrikka liitetäänkin yleensä arabialueen musiikkiin ja Saharan eteläpuolisten alueiden musiikkia käsitellään omana erillisenä kokonaisuutenaan. Ainakin arkikäytössä "afrikkalainen musiikki" assosioituukin usein nimenomaan Saharan eteläpuoliseen musiikkiin. Toisaalta monikaan ei varmasti luokittelisi esim. etelä-afrikkalaisten valkoihoisten tekemää musiikkia (esim. Die Antwoord) "afron" tai "afrikkalaisen populaarimusiikin" alle. En suosittele, että käsitettä kuitenkaan rajataan tai määritellään ihonvärin perusteella. Sen sijaan esim. "erityisesti Saharan eteläpuolisen Afrikan populaarimusiikin genrejä, joissa on paikallisen musiikkiperinteen elementtejä" tai jokin vastaava määritelmä voisi toimia, jos käsite halutaan säilyttää ja rajata tällä tavoin. Myös maailmanmusiikki (vrt. nykyinen "afron" määritelmä YSAssa) on sekä käsitteenä että terminä ongelmallinen, mutta sitä voidaan käsitellä toisessa yhteydessä. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by jtuohini** [comment]
**Afro**-termin Musa-sanastohistoriaa en tunne, mutta se on mielestäni selkeämpi kuin tilalle ehdotettu _afrikkalainen populaarimusiikki_: kaikki afrikkalainen populaarimusiikki ei ole afroa, joten on riski, että joku kuvailisi ihan tavallista jonkin afrikkalaisen maan "mainstream"-populaarimusiikkia ehdotetulla termillä, vaikka kyse ei olisi nimenomaisesti "afroksi" luettavaa maailmanmusiikiksi katsottua. Lisäksi termin vaihtaminen päittäin tuottaisi lisävaivaa, jonka hyödyn ilmeisyydestä en ole lainkaan varma. Termin selitys joka tapauksessa vaatii korjaamista, jotta olisi selvää, miksi se ei kata raita yms.

**Comment by tpalonen** [comment]
Väite, että afro on selkeämpi termi kuin afrikkalainen populaarimusiikki, ei yksinkertaisesti pidä paikkaansa. Termi on harhaanjohtava ja virheellinen. Aiheutuvan lisävaivan miettimisen sijaan minusta pitäisi miettiä, täyttävätkö sanastossa esiintyvät termit kirjallisuustakuun ja käyttäjätakuun. Tämän termin kohdalla ne eivät täyty, koska missään ei puhuta afrikkalaisesta musiikista käyttäen afro-termiä (ks. alkuperäisessä ehdotuksessa mainitut sanakirjaesimerkit) eikä kukaan myöskään pelkän afro-termin nähdessään tiedä, että se viittaa musiikkiin.

"Afrikkalainen populaarimusiikki" vastaisi terminä käsitteen nykyistä määritelmää. Ja sanastossahan on jo "latinalaisamerikkalainen populaarimusiikki" joka toimii tässä hyvänä vertailukohteena. Myös latinalaisessa amerikassa kuunnellaan ja tehdään ns. länsimaista populaarimusiikkia, mutta se ei ole ollut esteenä tämän käsitteen ja termin muodostamiseen. Afro-termi ja käsite on otettu määritelmästä päätellen MUSAan samassa tarkoituksessa kuin "latinalaisamerikkalainen populaarimusiikki" mutta koskien Afrikan mannerta. Termimuutos korjaisi nykyisen virheellisen ja harhaanjohtavan termin paremmin  alkuajatusta vastaavaksi.

Maailmanmusiikki-sanan käyttöä termin osana en suosittele. Sana on monessa yhteydessä todettu ongelmalliseksi ja eurosentriseksi.

**Comment by tpalonen** [comment]
Termistä vielä: vrt. myös LCSH-käsite, johon afro-käsite on linkattu: "Popular music--Africa".

**Comment by jaskaj** [comment]
MUSAn "afro"-termi on vanhahtava. Käsittääkseni sitä käytettiin Suomessa 1980-luvulla yleisterminä lähinnä länsiafrikkalaisesta populaarimusiikista (esim. Orchestra Baobab), joka oli tuolloin täällä suosiossa.

Kannatan termin poistoa, koska sille ei tuossa mainitsemassani merkityksessä ole mielestäni tarvetta.

**Comment by mariaforsen** [comment]
Termi afro tässä merkityksessä ei toimi ollenkaan ruotsiksi. On ruotsin osalta poistettava tai ainakin muutettava.

**Comment by TommiViitamies** [comment]
Kannatan termin poistamista. En kannata afrikkalainen populaarimusiikki -termiä: myös "latinalaisamerikkalainen populaarimusiikki" on ongelmallinen.

**Comment by YSA-kokous** [comment]
Poistetaan.

**Comment by mariaforsen** [comment]
Sv. afro raderad.

**Comment by mirmaid** [comment]
Laitetaanko nykyiset alakäsitteet benga, juju, makossa, mbalax, mbaqanga ja soukous suoraan maailmanmusiikin alakäsitteiksi?

**Comment by TommiViitamies** [comment]
Kyllä!
