### ISSUE TITLE
luonnonkosmetiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5543]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luonnonkosmetiikka 

#### Tarkoitusta täsmentävä selite   

Luonnonkosmetiikalla tarkoitetaan kosmetiikan tuotteita, joiden valmistuksessa on kiinnitetty erityistä huomiota ainesosien luonnolliseen alkuperään sekä siihen, miten tuotteen elinkaari vaikuttaa ihmiseen ja ympäristöön. Synteettisten, eli ihmisen valmistamien ainesosien sijaan luonnonkosmetiikassa käytetään luonnosta peräisin olevia raaka-aineita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.helsinki.fi/ruralia/julkaisut/pdf/Raportteja103.pdf 

#### Perustelut ehdotukselle   

-- 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [luonnonkosmetiikka](http://finto.fi/yse/fi/page/Y505543)

**Comment by satuniininen** [comment]
Ruralian raportissa käytetään engl. termiä natural cosmetics. LCSH:sta löytyy vain herbal cosmetics, joka on hieman eri asia.

**Comment by mirmaid** [comment]
Melindassa 2 viitettä.

https://fi.wikipedia.org/wiki/Luonnonkosmetiikka

**Comment by mariaforsen** [comment]
Sv. naturkosmetika ET naturkosmetik
