### ISSUE TITLE
koivu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5544]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koivu](http://www.yso.fi/onto/ysa/Y96273) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

muotoon koivut (suku) - Betula
YSAn hierarkiassa on tässä merkityksessä
Alakäsitteet: hieskoivu, rauduskoivu, vaivaiskoivu
Visakoivu on rauduskoivun muunnos, eli oikeaoppisesti se on rauduskoivun alakäsite 

#### Perustelut ehdotukselle   

koivut
https://laji.fi/taxon/MX.37992

visakoivu
https://laji.fi/taxon/MX.37997 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
_Visakoivun_ hierarkia korjattu.

**Comment by mirmaid** [comment]
Ehdotettu myös termiä _koivu (materiaali)_, sekä vastaavasti muita puusukuja materiaalina. Esim. kuusen ja männyn osalta yleensä aineisto käsittelee metsämäntyä tai metsäkuusta materiaalina, jolloin ongelma ei ole kovin suuri, koska näillä on ohjausterminä kuusi/mänty (laji), ja esim. Melindassa aihehaku sanalla _kuusi_ tuo viitteet, joissa asiasanana on metsäkuusi. Koivun osalta tilanne on vähän eri; mahdollinen ratkaisu olisi esim. lisätä ohjaustermi koivu kaikille koivulajeille (tyyliin koivu (rauduskoivu)). 

Pohdittavaksi jää vielä, pitäisikö yksikön tuoda myös monikolla kuvaillut viitteet? Auktorisoiminen erikseen materiaalina on kyllä mahdollista, mutta koskisi johdonmukaisesti toteutettuna hyvin suurta määrää kasvisukuja (ja lajeja?), tällä hetkellä kasveja ei ole auktorisoitu erikseen esim. ruoka-aineena.

LCSH Birches USE Birch, mutta erikseen esim. Birch bark

**Comment by mirmaid** [comment]
Muutos on mahdollista siirtää syksyyn, koska sanastossa ei ole monikollista termiä.

**Comment by mirmaid** [comment]
Sanastossa myös _lepät, lehmukset, lehtikuuset_ saman tyyppisiä (mihin yksikkömuodosta ohjataan).

**Comment by YSO-kokous** [comment]
Päätös: 
koivu KÄYTÄ koivut
koivu (rauduskoivu) KÄYTÄ rauduskoivu
