### ISSUE TITLE
mänty

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5545]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mänty](http://www.yso.fi/onto/ysa/Y97605) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muotoon männyt (suku) - Pinus
YSAn hierarkiassa on tässä merkityksessä
Alakäsitteet: mänty, kontortamänty 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.37818

Jos tarvitaan materiaalina - mänty (materiaali) 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
Mänty YSAssa KT metsämänty, joka lajinimenä laji.fi:ssä. Otetaan siis _männyt_ ja _metsämänty_ KT mänty (laji).

**Comment by mariaforsen** [comment]
Sv. tallsläktet, tall
