### ISSUE TITLE
lehtikuusi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5546]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lehtikuusi](http://www.yso.fi/onto/ysa/Y96811) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muotoon lehtikuuset (suku) - Larix
Ysassa on tässä merkityksessä
Alakäsite siperianlehtikuusi 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.37815

Jos tarvitaan materiaalina - lehtikuusi (materiaali) 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
Sulkutarkennetta ei tarvita, jos ei oteta lisäksi yksikössä materiaalina.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5508

**Comment by YSA-kokous** [comment]
lehtikuuset

**Comment by mariaforsen** [comment]
Sv. lärkar
