### ISSUE TITLE
harjoitusaineistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5547]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[harjoitusaineistot](http://www.yso.fi/onto/ysa/Y214476) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

musiikin harjoitusaineistot 

#### Perustelut ehdotukselle   

YSAn ympäristössä tarvitaan täsmentää termin merkitystä. LT oppimateriaali, sen ST:t esim. audiovisuaalinen oppimateriaali 

#### Ehdottaja   

Katerina 

#### Ehdottajan sähköpostiosoite   

katerina.sornova@helsinki.fi

**Comment by jtuohini** [comment]
Kannatetaan: ehdotettu termi **musiikin harjoitusaineistot** on yksiselitteisempi kuin pelkkä **harjoitusaineistot** eli arvattavasti pienentäisi riskiä, että termiä käytettäisiin vahingossa muussa kuin tarkoitetussa merkityksessä.

**Comment by mariaforsen** [comment]
Entä muunlaiset harjoitusaineistot (riippumatta taidemuodosta, aiheesta jne.)? Harjoituskirjat kyllä on, mutta nykyään on entistä enemmän harjoitusaineistoa/materiaalia netissä, eikä muutenkaan kirjamuodossa.

**Comment by YSA-kokous** [comment]
Seuraava kokous, selvitetään käyttöä muun kuin musiikin yhteydessä.

**Comment by ilkkahaataja** [comment]
Luumu-kokous (31.10.2017): Emme puolla. Vastaehdotus: poistetaan nykyinen määritelmä ja muutetaan termi yleistermiksi ryhmään 57.
