### ISSUE TITLE
musiikkiohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5548]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkiohjelmat](http://www.yso.fi/onto/ysa/Y97565) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

MUSAsta on tulossa "musiikkiohjelmat (televisio-ohjelmat)". tarvitaanko lisäksi "musiikkiohjelmat (radio-ohjelmat)" vai niputetäänkö kaikissa eri medioissa esitetyt musiikkiohjelmat yhteen? olisiko yksi termi muodossa "musiikkiohjelmat" vai "musiikkiohjelmat (mediat)" vai jotain ihan muuta? 

#### Perustelut ehdotukselle   

Pohdittavaksi

mediat-sulkutarkenne käytössä esim. jo käsitteessä "opetusohjelmat (media)" tai "uusinnat (media)" 

#### Ehdottaja   

Katerina 

#### Ehdottajan sähköpostiosoite   

katerina.sornova@helsinki.fi

**Comment by mirmaid** [comment]
Tarkennuksena vielä, sekä MUSAssa että YSAssa on lisäksi termi _musiikkiohjelmat_, määritelmä MUSAssa: _Nimitys joukkoviestimissä esiintyville, musiikkiin liittyville, ohjelmille._ 

Musiikkiohjelmilla ei varmaankaan ole muuta merkitystä kuin nämä mediassa esitetyt ohjelmat, joten jos yhdistetään, sulkutarkennetta ei tarvita.

**Comment by jaskaj** [comment]
Kannatan yhdistämistä ja muotoa "musiikkiohjelmat" ilman tarkennetta.

**Comment by jtuohini** [comment]
Kuitenkin pitää olla sikäli yksiselitteinen, ettei termi vahingossa sekoitu tarkoittamaan musiikkiin liittyviä tietokoneohjelmia.

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi tarvitaan varmaan tarkenne miten vain, koska musikprogram käytetään paljon myös tietokoneohjelmista yms. Näyttää olevan samankaltainen tilanne suomeksikin.

**Comment by YSA-kokous** [comment]
musiikkiohjelmat (media)

**Comment by mirmaid** [comment]
Uusi SLM-ehdotus: https://www.kiwi.fi/pages/viewpage.action?pageId=91754306

**Comment by mirmaid** [comment]
Musiikkiohjelmat-termiä ei ole SLM-sanastossa. Muusan ehdotuksessa: _LISÄTÄÄN* ??musiikkiohjelmat (televisio-ohjelmat) ja musiikkiohjelmat (radio-ohjelmat)_. https://www.kiwi.fi/pages/viewpage.action?pageId=91754306

TV/radio-jaotteluun ei varmaan kuitenkaan haluta enää palata?

**Comment by jtuohini** [comment]
Muusan kokous 4.10.2019: otetaan SLM-sanastoon pelkkä **musiikkiohjelmat**. Tarkempi voidaan ilmaista muilla termeillä (_televisio-ohjelmat_ jne).

**Comment by mariaforsen** [comment]
Yläkäsite on nyt pelkkä televisio-ohjelmat.. Entä radio tai muu media? Ja miten voidaan varmistaa ettei käytetä atk-ohjelmista? Ruotsiksi pitäisi olla tarkenne, mutta toisaalta outoa kun suomeksi ei ole.. Googlessa käytetty paljon myös ohjelmoinnista. 

YSOssa on: musiikkiohjelmat (media) ! Se olisi varmaan selkeämpi muoto myös SLM:ssä.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa SLM-termin säilyttämistä muodossa _musiikkiohjelmat_.

**Comment by mirmaid** [comment]
Lisätään käyttöhuomautus.
