### ISSUE TITLE
musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5549]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikki](http://www.yso.fi/onto/ysa/Y97560) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

musiikki: 

    Säveltaide, eli ääneen perustuva taiteen muoto. Termiä käytetään samassa merkityksessä kuin puhutaan kuvataiteista ja kaunokirjallisuudesta.

sävellykset: Luovan musiikillisen työn tuloksen nimitys. Samasta asiasta käytetään arkikielessä myös nimityksiä "teos", "sävelteos" ja "sävellysteos". 

#### Ehdotettu muutos   

Termien "musiikki" ja "sävellykset" merkitykset. Meneekö päällekkäin, tarvitaanko molemmat? Keskustelun avaus. Pohdittavaksi. 

#### Ehdottaja   

Katerina 

#### Ehdottajan sähköpostiosoite   

katerina.sornova@helsinki.fi

**Comment by asormune** [comment]
"Musiikki" termiä käyttäisin esim. sellaisen kirjan kuvailuun, joka käsittelee yleisesti eri musiikkityylejä > (musiikki - tyylit).  Sävellykset termiä en lähtisi vaihtamaan (ohjaustermejä Musassa ovat: kappaleet, musiikkiteokset, sävellysteokset, sävelteokset). Voidaanko "sävellykset" termiä käyttää myös improvisoimalla tuotetuista "musiikkiesityksistä"? Tähän kävisi termi "musiikkiteokset" (jota en siis kannattanut..) tai "musiikki - teokset - improvisointi". MUSAssa ei ole tosin ollut termiä "teokset" ja YSAssa ei ole teokset -termin alla musiikin teoksiin viittaavaa termiä. "Improvisaatiot" termi on, mutta se on mielestäni (taidemusiikin sävellysmuoto).

**Comment by mirmaid** [comment]
Musiikki-termin määritelmän jälkimmäinen lause ei ole oikein toimiva, mutta toisaalta termi (tai kumpikaan näistä termeistä) ei varsinaisesti tarvitse määritelmää, koska ne ovat täysin yleisesti tunnettuja. 

Sävellykset-termin määritelmässä mainitut sävelteos ja sävellysteos eivät ole sen arkikielisempiä kuin päätermikään. Riittäisi että ne ovat mukana ohjaustermeinä.

**Comment by YSA-kokous** [comment]
Muokataan määritelmiä yllä ehdotetun mukaisesti.

**Comment by tpalonen** [comment]
Sävellyksiä ja musiikkia tuskin käsitteinä yhdistetään, mutta tässä on keskustelua herättänyt se, että SLM:ssä ja YSAssa/YSOssa on eri nimeämiskäytännöt mitä tulee genretyyppisten käsitteiden sulkutarkenteeseen. SLM:ssä se on "(musiikki)" ja YSAssa/YSOssa "(sävellykset)", johtuen YSAn/YSOn hierarkiasta.
