### ISSUE TITLE
ihmisoikeusloukkaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5550]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ihmisoikeusloukkaukset](http://www.yso.fi/onto/ysa/Y134642) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö ihmisoikeusrikokset korvattuna terminä, tai mahdollisesti korvatuksi termiksi termille "rikos ihmisyyttä vastaan"? 

#### Perustelut ehdotukselle   

Myös ihmisoikeusrikokset on käytetty termi. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by AuHo22** [comment]
Itse näkisin suhteen RT:nä, eli rikokseen tarvitaan juridinen tunnusmerkistö, kun taas ihmisoikeusloukkauksia voi olla ilman, että esimerkiksi jonkin maan lainsäädännön / tai vaikkapa tapakulttuurin mukaisesti ne ylipäätään olisivat rikoksia.

Suhde rikos ihmisyyttä vastaan ja ihmisoikeusrikokset selvitettävä?

**Comment by mariaforsen** [comment]
Näin tulkittu myös ruotsiksi, mutta ovat kyllä tosi lähellä toisiaan..
Finlex: 
Rikos ihmisyyttä vastaan
Joka osana siviiliväestöön kohdistuvaa laajamittaista tai järjestelmällistä hyökkäystä
1) surmaa tai orjuuttaa toisen, käy hänellä kauppaa tekemällä tarjouksen, ostamalla, myymällä tai vuokraamalla taikka kiduttaa häntä tai aiheuttaa hänelle muulla tavoin suurta kärsimystä tai vaikean vamman taikka vahingoittaa vakavasti hänen terveyttään taikka tuhoaa väestöä asettamalla sitä tai sen osaa hävittäviä elinehtoja tai muulla tavoin,
2) karkottaa tai pakolla siirtää alueella laillisesti oleskelevaa väestöä,
3) vangitsee toisen tai muuten riistää häneltä vapauden kansainvälisen oikeuden perustavaa laatua olevien määräysten vastaisesti taikka aiheuttaa vapautensa menettäneen tahdonvastaisen katoamisen,
4) raiskaa toisen, orjuuttaa häntä seksuaalisesti, pakottaa hänet prostituutioon, raskauteen tai sterilisaatioon taikka harjoittaa häntä vastaan muuta vastaavaa törkeää seksuaalista väkivaltaa tai
5) harjoittaa rotuerottelua taikka vainoaa tunnistettavissa olevaa ryhmää tai yhteisöä poliittisen mielipiteen, rodun, kansallisuuden, etnisen alkuperän, kulttuurin, uskonnon tai sukupuolen perusteella taikka niihin rinnastettavilla muilla perusteilla,
on tuomittava rikoksesta ihmisyyttä vastaan vankeuteen vähintään yhdeksi vuodeksi tai elinkaudeksi.

Ihmisoikeuksia taitaa olla muitakin, ks. esim. ihmisoikeudet.net ja YK. 

Pitääkö sitten ottaa ihmisoikeusrikokset erillisenä pääterminä?

**Comment by YSA-kokous** [comment]
Kysytään vielä Eduskunnan kirjastosta

**Comment by YSA-kokous** [comment]
Lisätään KÄ-viittaus molempiin.

**Comment by mariaforsen** [comment]
Sv. 
-kränkningar av mänskliga rättigheter ET brott mot mänskliga rättigheter, kränkning av mänskliga rättigheter, människorättsbrott, människorättskränkningar 
-brott mot mänskligheten
