### ISSUE TITLE
aunuksenkarjalan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5551]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aunuksenkarjalan kieli 

#### Ehdotettu termi englanniksi   

Livvi-Karelian language 

#### Ehdotettu termi ruotsiksi   

livvi * 

#### Vaihtoehtoiset termit ja ilmaisut   

aunuksenkarjala, aunus, livvi, livvin kieli, livvinkarjala 

#### Ehdotettu yläkäsite YSOssa (LT)   

[karjalan kieli](http://www.yso.fi/onto/yso/p6932) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85094638> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Aunuksenkarjalan_kieli 

#### Tarkoitusta täsmentävä selite   

. . 

#### Perustelut ehdotukselle   

Tällä on jo oma kielikoodinsa ja kielen nimeä käytetty asiasanana, vaikka on KT-muotona YSAssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [aunuksenkarjalan kieli](http://finto.fi/yse/fi/page/Y505551)

**Comment by mirmaid** [comment]
YSAssa myös lyydin kieli KÄ _lyydiläismurteet_.

**Comment by mariaforsen** [comment]
SAO: olonetsiska (vastineena LCSH-termille olonets dialect)

**Comment by YSA-kokous** [comment]
Molemmat kieliksi.

**Comment by mariaforsen** [comment]
Sv. olonetsiska ET livvi ET onega-karelska
