### ISSUE TITLE
kalatalousalue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5552]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kalatalousalue 

#### Ehdotettu termi ruotsiksi   

fiskeriområde 

#### Ehdotettu termi englanniksi   

fishery region 

#### Tarkoitusta täsmentävä selite   

Kalatalouden hallinto-organisaatio. Mainittu nykyisessä kalastuslaissa. Kalatalousalueet aloittavat toimintansa vuonna 2019. 

#### Perustelut ehdotukselle   

Yleinen termi kalataloushallinnossa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://mmm.fi/kalastuslaki/usein-kysyttya/kalatalousalueet 

**Ehdottajan nimi:** Jukka Syrjänen 
**Ehdottajan sähköpostiosoite:** jukka.t.syrjanen@jyu.fi 
**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [kalatalousalue](http://finto.fi/yse/fi/page/Y505552)

**Comment by mirmaid** [comment]
Melindassa kerran (yksikössä).

Olisiko tällä edeltäjä-seuraaja-suhde termiin _kalastusalueet_? http://www.ahven.net/kalatalousalueet

**Comment by mariaforsen** [comment]
Sv. fiskeriområde
