### ISSUE TITLE
aikamääreet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5553]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aikamääreet 

#### Tarkoitusta täsmentävä selite   

Auktorisoidaan YSAan vuosisadat ja vuosikymmenet, kenttään 148. 

#### Perustelut ehdotukselle   

Tarvetta olisi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Mirja Anttila 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [aikamääreet](http://finto.fi/yse/fi/page/Y505553)

**Comment by mirmaid** [comment]
Mitä kaikkea tarvitaan?
- ajanlaskun alun jälkeiset vuosisadat
- 1900-luvun ja 2000-luvun vuosikymmenet
- muuta?
