### ISSUE TITLE
primaarinen sklerosoiva kolangiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5555]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

primaarinen sklerosoiva kolangiitti 

#### Ehdotettu termi englanniksi   

Primary Sclerosing Cholangitis, (PSC) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sappitaudit](http://www.yso.fi/onto/yso/p2056) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Primaarinen_sklerosoiva_kolangiitti 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Tarvitaan väitöskirjan kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/217908 

#### Tarkoitusta täsmentävä selite   

http://www.muma.fi/sairaudet_ja_elinsiirrot/maksasairaudet/maksasairaudet/primaarinen_sklerosoiva_kolangiitti 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [primaarinen sklerosoiva kolangiitti](http://finto.fi/yse/fi/page/Y505555)

**Comment by mirmaid** [comment]
FinMeSHissä _Sklerosoiva sappitietulehdus_.

**Comment by LeKorsu** [comment]
Kannatan yhdenmukaisuuden vuoksi FinMeSH-muotoa, mutta onko kyse eri taudista kun on tuo primaarinen-etuliite? Mitähän Terkko / FinMeSH-ylläpitäjät sanovat?

**Comment by mariaforsen** [comment]
Sv. skleroserande kolangit ET primär skleroserande kolangit

**Comment by YSA-kokous** [comment]
sklerosoiva sappitietulehdus
