### ISSUE TITLE
Vuosituhannet-, sadat ja -kymmenet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5556]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Vuosituhannet-, sadat ja -kymmenet 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/1700-luku : https://fi.wikipedia.org/wiki/1950-luku 

#### Perustelut ehdotukselle   

Kehitteillä oleva arkistosektorin yhteinen arkistoiaineiston hakemistopalvelu AHAA (http://www.kdk.fi/fi/kokonaisarkkitehtuuri/127-suomi/274-ahaa) hyödyntää kuvailussa Finton kautta YSO-termejä ja aikaa kuvaaville asiasanoille olisi merkittävä tarve. Ainakin vuosisadat tuhatluvulta eteenpäin ja vuosikymmenet 1700-luvulta alkaen tulisivat todelliseen tarpeeseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

AHAA-hakemistopalvelussa kuvailtava viranomais- ja yksityisarkistoaineisto. 

**Ehdottajan nimi:** Milla Eräsaari 
**Ehdottajan organisaatio:** Suomalaisen Kirjallisuuden Seura 
**Ehdottajan sähköpostiosoite:** milla.erasaari@finlit.fi **Termiehdotus Fintossa:** [Vuosituhannet-, sadat ja -kymmenet](http://finto.fi/yse/fi/page/Y505556)

**Comment by jtuohini** [comment]
Tästä olikin juuri eilen tehty termiehdotus https://github.com/Finto-ehdotus/YSE/issues/5553!

**Comment by YSA-kokous** [comment]
Käytetyimmät Melindan mukaan.

**Comment by mirmaid** [comment]
Entä sotavuodet?

**Comment by jarmosaarikko** [comment]
Kalenteriin liittyviä ajanjaksoja ovat mm. 1) numeroilla kuvatut 2) nimetyt ajanjaksot.
Esitän, että ajanjaksoja voisi kuvata nimettyinä (esim. yhteiskunnalliset ajanjaksot, kuten hallintokaudet) ja liitetään  ohjaustermiksi kyseiset vuodet (tällöin vuodet voivat viitata useaan eri nimettyyn ajanjaksoon samoilla vuosilla).   X48 kentässä MARC ohjeistus antaa 'vapaat kädet' tämän määrittelylle. 

Ruotsin sao-sanastossa käytetään 148-kentässä termejä medeltiden ja renässansen. http://www.kb.se/dokument/Verktygsladan/Svenska%20%C3%A4mnesord/Riktlinjer/Riktlinjer%20SAO.pdf   (sivulla 32) -- näillekin voidaan tarvittaessa/luultavasti myös pistää numeeriset ohjaustermit jonkin "yleisen käsityksen" mukaan?

Nimettynä terminä voisi olla "1800-luku" ja ohjausterminä "1800-1899".
Suomeksi hierarkiasta tulisi kai sotkuisempi: yläkäsitteinä pitäisi olla "vuosituhannet", "vuosisadat", "vuosikymmenet" ja "vuodet". Nämä ovat rinnakkaisia haaroja eli vuodet eivät tule vuosisatojen alle. Käyttöön otetaan aluksi vain ne, joita on käytetty tai tarvitaan kuvailussa.  Yksitäiset vuodetkin voidaan tarvittaessa jättää pois.

Aikakäsitteitä löytyy myös UDK-luokituksesta, esim. UDC summaryn yleiset ajan lisäluvut Taulukko 1g http://www.udcsummary.info/php/index.php?tag=---&lang=fi     Voikin kysyä milloin on tarpeen ilmaista aika asiasanalla ja milloin kannattaa käyttää luokitusta?

**Comment by jtuohini** [comment]
Myös Marc 21 -formaatin kenttä 045 on hyvä muistaa, ja Sisällönkuvailun asiantuntijaryhmä opastaa uudessa sisällönkuvailuohjeessankin käyttämään sitä ainakin vuotta tarkemmissa ajanmääreissä (https://www.kiwi.fi/display/ohjaus/7.+Aika)! UDK on toinen hyvä, ja sekin on oppaassa huomioitu.

**Comment by mariaforsen** [comment]
Svenska ämnesord: "Vid indexering används i första hand ämnesorden från listan Allmänna kronologiska ämnesord. Dessa återfinns på en särskild lista på Svenska ämnesords webbplats. Denna lista 
innehåller bestämda århundraden, decennier och några tidsperioder uttryckta med ord t.ex. renässansen och medeltiden. Vissa vanliga tidsperioder har ospecificerad startpunkt, t.ex. före 1500, eller ospecificerad slutpunkt, t.ex. 1945-." Ks. http://www.kb.se/katalogisering/Svenska-amnesord/Kronologiska-amnesord/
