### ISSUE TITLE
mansikat (suku - Fragaria)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5557]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mansikat (suku - Fragaria) 

#### Vaihtoehtoiset termit ja ilmaisut   

Fragaria 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ruusukasvit](http://www.yso.fi/onto/yso/p10465) 

#### Alakäsitteet (RT)   

[ahomansikka](http://www.yso.fi/onto/yso/p18109) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.38868 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan Helkan ja Arton aineistojen kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka ja Arto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [mansikat (suku - Fragaria)](http://finto.fi/yse/fi/page/Y505557)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5338

**Comment by PaiviLipsanen** [comment]
Alakäsitteenä myös puutarhamansikka

**Comment by mariaforsen** [comment]
Sv. smultronsläktet
