### ISSUE TITLE
puutarhamansikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5558]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puutarhamansikka 

#### Vaihtoehtoiset termit ja ilmaisut   

Fragaria x ananassa 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.38868 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan Helkassa ja Artossa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka ja Arto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [puutarhamansikka](http://finto.fi/yse/fi/page/Y505558)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5338

**Comment by PaiviLipsanen** [comment]
Laji.fi:ssä on tieteellisenä nimenä Fragaria ananassa

**Comment by mariaforsen** [comment]
Poistetaanko nyt sanastossa oleva "mansikka"?

**Comment by mariaforsen** [comment]
Sv. jordgubbe
