### ISSUE TITLE
mansikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5559]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mansikka](http://www.yso.fi/onto/ysa/Y97285) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mitä tällä tarkoitetaan? Onko kyse puutarhamansikasta esim. myytävinä marjoina? Melindassa näyttää olevan merkityksessä puutarhamansikka ja mansikat (suku). 

#### Perustelut ehdotukselle   

Olisi hyvä erotella merkitykset 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5338
