### ISSUE TITLE
lamentot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5560]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lamentot 

#### Ehdotettu termi englanniksi   

lamentos 

#### Ehdotettu termi ruotsiksi   

lamenton? [yksikkö on ett lamento, monikko siis?] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sävellykset](http://www.yso.fi/onto/yso/p1515) 

#### Assosiatiiviset (RT)   

[valituslaulut](http://www.yso.fi/onto/yso/p28694) 

#### Tarkoitusta täsmentävä selite   

Määritelmä: "Maallinen laulusävellys, tavallisimmin ooppera- tai kantaattiaaria, jonka teksti on aiheeltaan surullinen tai valittava ja joka musiikillisesti perustuu laskevaan basso ostinatoon." 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Perustelut ehdotukselle   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [lamentot](http://finto.fi/yse/fi/page/Y505560)

**Comment by mariaforsen** [comment]
Sv. lamenton
