### ISSUE TITLE
soijapapu (kasvilaji)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5561]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soijapapu (kasvilaji) 

#### Ehdotettu termi englanniksi   

soybean 

#### Vaihtoehtoiset termit ja ilmaisut   

Glycine max 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soijapavut](http://www.yso.fi/onto/yso/p21747) 

#### Assosiatiiviset (RT)   

[soija](http://www.yso.fi/onto/yso/p12239) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.38970 
Kassu : https://finto.fi/kassu/fi/page/k939 
LCSH : Soybean 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

YSAssa on nyt soija, mutta viittaako se enemmänkin elintarvikkeen eri muotoihin. YSAn soijapavut tarkoittanee sukua Glycine. 

#### Perustelut ehdotukselle   

Helkan ja Arton kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka ja Arto 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [soijapapu (kasvilaji)](http://finto.fi/yse/fi/page/Y505561)

**Comment by mirmaid** [comment]
Laji.fi: peltosoijapapu

**Comment by YSA-kokous** [comment]
peltosoijapapu

**Comment by mariaforsen** [comment]
Sv. sojaböna (art)
