### ISSUE TITLE
lastenkirjat (kirkonkirjat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5562]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lastenkirjat (kirkonkirjat) 

#### Ehdotettu termi ruotsiksi   

barnböcker (kyrkoböcker) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkonkirjat](http://www.yso.fi/onto/yso/p17854) 

#### Vastaava käsite muussa sanastossa   

Suomen : https://fi.wikipedia.org/wiki/Lastenkirja 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

#### Tarkoitusta täsmentävä selite   

(Muodostettavissa helposti Wikipedian pohjalta.) 

#### Perustelut ehdotukselle   

Täsmällisempi käsite kuin pelkkä "kirkonkirjat" kuvaamaan juuri näitä kyseisiä kirkonkirjoja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [lastenkirjat (kirkonkirjat)](http://finto.fi/yse/fi/page/Y505562)

**Comment by jtuohini** [comment]
Unohtui englanninkielinen vastine: **preconfirmation books** tai **preconfirmation records**.

Ja jos ehdotettu ei mene läpi omaksi asiasanakseen, niin sitten KT-muodoksi asiasanalle **kirkonkirjat**, jotta sanastoon ei jäisi ainoastaan harhaanjohtavaa (siis sukututkimusterminologian kannalta huonoa) _lastenkirjat_ KÄ **lastenkirjallisuus**.

**Comment by mirmaid** [comment]
YSAssa on rippikirjat KÄ kirkonkirjat, joten tästäkin voisi tehdä vastaavan viittauksen. Nyt ohjausterminä on myös kastekirjat.

Jos otetaan omaksi termikseen, niin varmaankin otetaan myös rippikirjat. 
Wikipedia: _Lastenkirja on nimitys eräälle kirkolliselle asiakirjaryhmälle, joka sisältyy kirkonarkiston henkilörekisteriarkistoon. Muodoltaan se on rippikirjan kaltainen ja sitä täydentävä. Lastenkirjan tehtävänä oli kontrolloida niiden lasten edistymistä kristinopintaidoissa, jotka eivät vielä olleet päässeet ripille ja näin olleen tulleet merkityiksi seurakunnan rippikirjaan muun perheen yhteyteen._

**Comment by mariaforsen** [comment]
Barnböcker ei vaikuta olevan yleinen ruotsiksi: "Barnböcker, oftast i församlingar i östra Finland (förteckning över familjens barn, som ännu inte konfirmerats)" 
Suomenkielisessä wikipediassa: "Lastenkirjat ovat tyypillisesti itäsuomalainen ilmiö." 

Onko tämä aivan tarpeen ottaa erillisenä terminä?

**Comment by YSA-kokous** [comment]
KÄ kirkonkirjat
