### ISSUE TITLE
metsätaloustilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5564]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[metsätaloustilat](http://www.yso.fi/onto/ysa/Y97429) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista yhdistää termiin metsätilat? Tai mahdollisesti vain lisätä määritelmiä? 

#### Perustelut ehdotukselle   

Onko merkittävästi eri asioita? MOT, TEPA jne. ei tunne metsätaloustilaa, eikä Google anna paljoa (lähinnä Finto..) Tarvitaan myös JUHO-työssä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by PaiviLipsanen** [comment]
Ehdotan, että metsätaloustiloista tehdään ohjaustermi. 

Tuhat tärkeää termiä - Metsäsanasto (v. 2006) tuntee vain metsätilat. Uusimmassa metsäkirjallisuudessa puhutaan metsätiloista. Metsätaloustilat on lisätty YSAan v. 1987. Melindasta löytyy sanahaulla metsätaloustil? vain 33 osumaa.

**Comment by mirmaid** [comment]
Molemmat on otettu YSAan samana päivänä, joten jotain erottelua tässä on haettu. Ehkä esim. niin että metsätilalla olisi myös peltoa ja metsätaloustila olisi keskittynyt metsätalouteen? http://www.maaseuduntulevaisuus.fi/mets%C3%A4/mets%C3%A4tila-ilman-peltoa-oli-aikaisemmin-kummajainen-luokiteltiin-rappiotilaksi-1.169330

Joka tapauksessa erottelu on epäselvä eikä näin vanhoista päätöksistä löydy taustatietoa, joten ainoa toimiva ratkaisu varmaankin yhdistää.

**Comment by YSA-kokous** [comment]
metsätaloustilat KÄ metsätilat
