### ISSUE TITLE
maito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5565]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maito](http://www.yso.fi/onto/ysa/Y97247) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nyt YSOssa on maidon alakäsitteinä esim. lampaanmaito ja äidinmaito. Pitäisi olla myös naudanmaito, maito(nauta) tms. 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Perustelut ehdotukselle   

maito-käsitettä käytetään nyt useimmin kuvaamaan juuri naudanmaitoa/lehmänmaitoa. Lampaanmaito tai äidinmaito eivät voi olla "lehmänmaidon" alakäsitteitä. 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by satuniininen** [comment]
Voidaanko rajata nykyinen _maito_ viittaamaan vain ainoastaan lehmänmaitoon? Enemmistö Melinda-kuvailuista tukisi tätä tulkintaa. Esim. _maito_ KT _naudanmaito_ LT _kotieläintuotteet_, mahdollisesti myös sulkutarkenne. 

Tällöin hierarkia menisi seuraavasti:
lampaanmaito LT kotieläintuotteet
vuohenmaito LT kotieläintuotteet
ternimaito LT kotieläintuotteet
äidinmaito LT eritteet

Kaura-, soija- yms -maidot jatkossa suoraan juomien alle.

**Comment by mariaforsen** [comment]
Siinä tapauksessa varmaan myös KT lehmänmaito

**Comment by mirmaid** [comment]
Sulkutarkenteeksi mahdollinen varmaankin vain (lehmänmaito), jos tarkenne tarvitaan - pääterminä se ei kuitenkaan olisi kovin toimiva. _Kotieläintuotteet_ on toimiva LT YSAssa, YSOssa se on määritelty _rooliksi_.

**Comment by tpalonen** [comment]
Yksi vaihtoehto olisi muuttaa nykyinen _maito_ muotoon _maito (lehmänmaito)_. Ja ottaa tämän lisäksi sanastoon käsite _maito (eritteet/tms)_, joka olisi yläkäsite yllämainituille.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Muutos on mahdollista siirtää syksyyn, koska sanastossa ei ole monikollista termiä.

**Comment by mariaforsen** [comment]
Onko todella tarvetta yleiselle "maito"-termille kun sanastossa on erikseen tarvittavat maito-termit (äidinmaito, vuohenmaito, kasvimaito) ja jos tämä maito-termi muutettaisiin muotoon lehmänmaito, kuten kai olisikin selkeintä tehdä?

**Comment by mariaforsen** [comment]
Miksi tätä ei sitten vain muuteta muotoon "lehmänmaito", sitähän se on siinä merkityksessä kuitenkin? Ja jos halutaan kattaa muita eläinten maitoja niin sitten sen lisäksi "maito (eritteet)" kuten yllä ehdotettiin. Sanastossa on toki jo myös vuohenmaito, mutta myös muita eläinten maitoja on, joten termille "maito (eritteet)" saattaa olla käyttöä.

**Comment by mirmaid** [comment]
Vähän hassu tämä on niin tai näin. Kaikki maidot ovat eritteitä, joten ko. tarkenne on periaatteessa ylimääräistä informaatiota, jonka funktio olisi ohjata käyttämään kuvailussa alakäsitteitä aina kun se on mahdollista, käytännössä tosiaan lähes aina. _Lehmänmaito_ pääterminä olisi periaatteessa oikea, mutta suomalaisessa ruokakulttuurissa ehkä liian vieraannuttava ollakseen kuvailu- ja hakukäytössä luonteva (?).

**Comment by YSO-kokous** [comment]
Otetaan sanastoon yläkäsite eläinperäisille maidoille (eli eritteille):
maito (eritteet)
Lisäksi sanastoon "maito (lehmänmaito)", tälle ohjaustermiksi lehmänmaito.
