### ISSUE TITLE
kasvinosat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5566]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kasvinosat](http://www.yso.fi/onto/ysa/Y102005) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kasvinosat-käsitteen alakäsitteinä eli suppeampina termeinä olevat yksikkömuotoiset termit monikkomuotoon. Tarkemmin sanottuna: johtosolukko, juuri, juuristo, jyvä, jälsi, kaarna, kukinto, kukka, kuori, latvus, lehti, maavarsi, mukula, mykorritsa, nila, nuppu, runko, tuohi, varsi.

Siitepölyn (joka on niin ikään kasvinosien alakäsite) jättäisin yksikköön koska se on melko selkeästi ainesana. 

#### Perustelut ehdotukselle   

Osa kasvinosat-alakäsitteistö on jo nyt monikossa (itiöt, johtojänteet, kannot, siemenet jne). Käsitteet viittaavat laskettavissa oleviin objekteihin, joten monikkomuoto olisi perusteltua kaikille. Yksikkö/monikko-asiasta on keskusteltu YSO-pohjaisten ontologioiden osalta ja päädytty siihen, että kaikki YSO-pohjaiset ontologiat noudattavat jatkossa ISO-25964 -tesaurusstandardia yksikkö/monikko-muodoissa ja kaikessa muussakin. Olisi kuitenkin absurdia, jos muiden sanastojen pohjana toimivat YSA ja YSO eivät noudattaisi samaa standardia. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by jtuohini** [comment]
Eivätkö jälsi, kaarna, nila ja tuohi ole ainesanoja? Mukulat ovat helposti laskettavissa, mutta eivät kai sentään "jälsit"/"jället", "kaarnat", "nilat", "tuohet"?

**Comment by jarmosaarikko** [comment]
**kuori** - tälle löytyy monenlaisia termejä ja osa niistä on myös raaka-aineena erilaisille tuotteille: esim. erilaisia puunkuoria ovat _kaarna_, _tuohi_ ja _korkki_.  Tässä merkityksessä yläkäsitteenä kuori voisi olla monikossa _kuoret_, mutta kasvilla on yleensä vain yksi kuori eli eikö sen pitäisi silloin olla yksikössä? YSO:ssa termin _kuori_ yläkäsitteenä on _kasvinosat_ ja alakäsitteenä _tuohi_ sekä assosiasitiivisenä käsitteenä _kaarna_, jonka ass. käsitteenä _korkki_.   Samaan aikaan  **kuori** voi myös tarkoittaa hedelmän tai pähkinän kuorta, joka on myös kasvin osa, mutta aivan eri merkityksessä.   Tässä jälkimmäisessä merkityksessä kuorella on merkittävä rooli esim. kasvin leviämisessä.

**Comment by mirmaid** [comment]
Ruumiinosat on auktorisoitu yksikössä silloin kun niitä on kehossa vain yksi (Suomenkielisen tesauruksen laatimis- ja ylläpito-ohjeet, SFS 5471). Kasvinosiin ko. standardi ei ota kantaa, mutta yksi mahdollisuus voisi olla myös auktorisoida monikossa ainakin ne kasvinosat, joita yhdessäkin kasvissa voi olla/tyypillisesti on useita (juuret, jyvät, kukinnot, kukat, lehdet, mukulat, nuput)?

**Comment by YSA-kokous** [comment]
Auktorisoidaan monikossa ne kasvinosat, joita yhdessäkin kasvissa voi olla/tyypillisesti on useita.
