### ISSUE TITLE
kesäihottuma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5567]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kesäihottuma 

#### Ehdotettu termi englanniksi   

Summer eczema 

#### Vaihtoehtoiset termit ja ilmaisut   

kutka, hankuri 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ihotaudit](http://www.yso.fi/onto/yso/p8746) 
[eläintaudit](http://www.yso.fi/onto/yso/p47) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Väitöskirjassa ja Artossa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: Phospholipids in equine summer eczema and its therapy (2017), https://helda.helsinki.fi/handle/10138/216710 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kesäihottuma](http://finto.fi/yse/fi/page/Y505567)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kes%C3%A4ihottuma

**Comment by mariaforsen** [comment]
Sv. sommarexem
