### ISSUE TITLE
fosfolipidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5568]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fosfolipidit 

#### Ehdotettu termi englanniksi   

phospholipids 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lipidit](http://www.yso.fi/onto/yso/p4799) 

#### Alakäsitteet (RT)   

[lysofosfolipidit](http://www.yso.fi/onto/yso/p27651) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Perustelut ehdotukselle   

AFOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: Phospholipids in equine summer eczema and its therapy (2017), https://helda.helsinki.fi/handle/10138/216710 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [fosfolipidit](http://finto.fi/yse/fi/page/Y505568)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh85101108

FinMeSHissä

32 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. fosfolipider
