### ISSUE TITLE
hermokasvutekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5569]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hermokasvutekijät 

#### Ehdotettu termi englanniksi   

Nerve Growth Factors 

#### Ehdotettu yläkäsite YSOssa (LT)   

[proteiinit](http://www.yso.fi/onto/yso/p4332) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : https://www.terkko.helsinki.fi/termix/?c=D12.776.467.860&language=#D12.776.467 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Väitöskirjassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: GDNF and Neurturin isoforms in an experimental model of Parkinson's disease (2017), https://helda.helsinki.fi/handle/10138/217511 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [hermokasvutekijät](http://finto.fi/yse/fi/page/Y505569)

**Comment by mirmaid** [comment]
LCSH: Nerve growth factor http://id.loc.gov/authorities/subjects/sh85090895

FinMeSH: Hermokasvutekijät ST Hermokasvutekijä

Melinda: 3 kertaa yksikössä, 10 kertaa monikossa

**Comment by mariaforsen** [comment]
Sv. nervtillväxtfaktorer

**Comment by YSA-kokous** [comment]
hermokasvutekijät
