### ISSUE TITLE
projektit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5571]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[projektit](http://www.yso.fi/onto/ysa/Y98235) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan KT-muodoksi termille "hankkeet" 

#### Perustelut ehdotukselle   

Käsitteet "hanke" ja "projekti" tarkoittavat käytännössä samaa, joten ei ole mielekästä pitää niitä erillisinä asiasanoina. Jos eivät kuitenkaan ole yhdistettävissä, pitää termeille luoda selkevät määritykset sanastoon. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Kannatan! Myös issue #5563

**Comment by YSA-kokous** [comment]
hankkeet KÄ projektit
