### ISSUE TITLE
rakennushankkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5573]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rakennushankkeet 

#### Ehdotettu termi englanniksi   

building projects TAI construction projects 

#### Ehdotettu termi ruotsiksi   

byggnarsprojekter 

#### Vaihtoehtoiset termit ja ilmaisut   

rakennusprojektit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hankkeet](http://www.yso.fi/onto/yso/p5408) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

#### Tarkoitusta täsmentävä selite   

. . 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [rakennushankkeet](http://finto.fi/yse/fi/page/Y505573)

**Comment by mirmaid** [comment]
Melindassa n. 40 kertaa.

**Comment by mariaforsen** [comment]
Sv. byggnadsprojekt, byggprojekt

**Comment by ilona-x** [comment]
rakennusprojektit Melinda x 7

Jos päätetään yhdistää hankkeet -> projektit, niin pitäiskö ottaa rakennusprojektit, vaikka onkin vähemmän käytetty muoto?
YSAssa nyt: 
kehittämishankkeet -> kehittämisprojektit
tutkimushankkeet -> tutkimusprojektit

**Comment by LeKorsu** [comment]
Hyvä kysymys, Ilona. Vaikea määritellä omaa kantaa. Sanomalehtikielessäkin (Sanoman arkisto) rakennushankkeet kolme kertaa käytetympi kuin rakennusprojektit.

**Comment by satuniininen** [comment]
Itse en näe ongelmaa siinä, että _projektit/hankkeet_- yhdistelmän alle tulisi sekä _projektit_- että _hankkeet_- päätteisiä yhdyssanoja riippumatta siitä, kumpi pääsanaksi valitaan.  Jos _rakennushankkeet_ on vakiintunut ja yleinen muoto niin se lienee luontevin valinta. Käsitetasolla tässä ei ole ristiriitaa vaikka termimuodot eroavatkin.

**Comment by YSA-kokous** [comment]
rakennushankkeet

**Comment by mariaforsen** [comment]
Sv. byggprojekt ET byggnadsprojekt
