### ISSUE TITLE
kanteleensoittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5574]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kanteleensoittajat](http://www.yso.fi/onto/ysa/Y158334) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kantelistit" 

#### Perustelut ehdotukselle   

Termiä näyttää käytetyn, joten se on syytä saada viittausmuodoksi (esim. artikkelissa "Minna Raskinen, kantelisti" teoksessa "Särmää ja sydäntä!: 50 vuotta musiikin opetusta iloksi ja ammatiksi Keski-Pohjanmaalla", s. 107–) 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ilkkahaataja** [comment]
Luumu-kokous (27.11.2017): Puollamme esitystä.
