### ISSUE TITLE
venäjänsaksalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5575]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

venäjänsaksalaiset 

#### Ehdotettu termi ruotsiksi   

Volgatyskar 

#### Ehdotettu termi englanniksi   

Russian Germans 

#### Vaihtoehtoiset termit ja ilmaisut   

Volgan saksalaiset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[saksalaiset](http://www.yso.fi/onto/yso/p20021) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85115968.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Melindan sanahaku russlanddeutsch? tuottaa 40 osumaa, venäjänsaksalaiset 10 osumaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3088533 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [venäjänsaksalaiset](http://finto.fi/yse/fi/page/Y505575)

**Comment by jtuohini** [comment]
Onko termin tarkoitus kattaa kaikki venäjänsaksalaiset vai vain volgansaksalaiset? Ruotsinkielinen viittaa nyt vain jälkimmäisiin, samoin LCSH-vastine. Jos haetaan yleisempää (ml. Pietarin ympäristön ja monien muiden Venäjän alueiden saksalaisperäinen väestö), niin sitten siltauksen pitäisi olla termiin **Germans--Russia** [http://id.loc.gov/authorities/subjects/sh96006797]. Itse kannatan laajempisisältöistä termiä tai niin, että sanastoon otettaisin sekä **venäjänsaksalaiset** että **volgansaksalaiset** omina termeinään, jälkimmäinen LT–ST-suhteessa edelliseen.

**Comment by mariaforsen** [comment]
Sv. volgatyskar, rysslandstyskar

**Comment by mariaforsen** [comment]
Sv. 
-volgatyskar
-rysslandstyskar

**Comment by YSA-kokous** [comment]
Kysytään ehdottajalta.

**Comment by jarmosaarikko** [comment]
Volgansaksalaiset on selkeämmin oma käsitteensä, kun heillä on ollut jopa oma tasavalta: https://fi.wikipedia.org/wiki/Volgan_saksalaisten_autonominen_sosialistinen_neuvostotasavalta

**Comment by mirmaid** [comment]
Ehdottajan lisäys: _Tarvitsisin käsitettä Volgan saksalaisille (volga tyskar). Venäjänsaksalaiset on varmaan hyvä nyt samalla lisätä laajempana käsitteenä._

**Comment by YSA-kokous** [comment]
Volgan saksalaiset (tutkitaan vielä muoto)
