### ISSUE TITLE
kinesiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5577]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kinesiikka 

#### Ehdotettu termi ruotsiksi   

kinesik 

#### Ehdotettu termi englanniksi   

kinesics 

#### Vaihtoehtoiset termit ja ilmaisut   

eleoppi 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Kielitiede:kinesiikka> 
Wikipedia (eng) : https://en.wikipedia.org/wiki/Kinesics 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Tarkoitusta täsmentävä selite   

Määritelmä: tutkimuksen haara, joka selvittelee kädenliikkeitä, ruumiin asentoja ja kasvojen ilmeitä
Selite: Kinesiikassa tarkkaillaan, missä määrin pelkkä elehdintä on riittävä viestintäväline ja kuinka paljolti se vain auttaa ja myötäilee kieltä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Prytkov, Andrei, Korkeakoulun opettajan kehollinen vuorovaikutus luennolla. http://urn.fi/URN:NBN:fi:jyu-201709253806 

#### Perustelut ehdotukselle   

Vastaavaa käsitettä ei YSAsta löydy. 

**Ehdottajan nimi:** Raila Salminen 
**Ehdottajan sähköpostiosoite:** raila.salminen@jyu.fi **Termiehdotus Fintossa:** [kinesiikka](http://finto.fi/yse/fi/page/Y505577)

**Comment by mirmaid** [comment]
LCSH use Body language (YSA-YSO: _ruumiinkieli_)

FinMeSH: Kinesiikka, sv. Kroppsspråk, eng. Kinesics (KT Body Language)

4 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Kinesik: studiet av hur man med kroppsrörelser förmedlar information. Kroppsspråk on jo sanastossa.

**Comment by satuniininen** [comment]
Ohjaustermiksi ruumiinkielelle? Tällöin olisi synkassa myös LCSH-linkityksen kanssa.

**Comment by YSA-kokous** [comment]
KÄ ruumiinkieli
