### ISSUE TITLE
bioreaktorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5578]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bioreaktorit 

#### Ehdotettu termi englanniksi   

bioreactors 

#### Ehdotettu termi ruotsiksi   

bioreaktorer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[reaktorit](http://www.yso.fi/onto/yso/p15278) 

#### Assosiatiiviset (RT)   

[biotekniikka](http://www.yso.fi/onto/yso/p2348) 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Biotekniikka:bioreaktori> 
MeSH-FinMeSH : https://finto.fi/mesh/fi/page/D019149 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

Tieteen termipankki:  laitteisto, joka ylläpitää suosiollisia olosuhteita jollekin biologiselle prosessille jotain tiettyä tehtävää varten 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sarjan osa: Utilization of microalgae in industrial symbiosis, focus on Finland, http://jukuri.luke.fi/bitstream/handle/10024/540187/luke-luobio_33_2017.pdf?sequence=1&isAllowed=y 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [bioreaktorit](http://finto.fi/yse/fi/page/Y505578)

**Comment by mirmaid** [comment]
15 viitettä Melindassa.

**Comment by satuniininen** [comment]
LCSH: bioreactors http://id.loc.gov/authorities/subjects/sh87005835.html

**Comment by mariaforsen** [comment]
Sv. bioreaktorer
