### ISSUE TITLE
saatavuusharkinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5579]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

saatavuusharkinta 

#### Tarkoitusta täsmentävä selite   

Yksi kiistellyimpiä aiheita työperusteiseen maahanmuuttoon liittyen on saatavuusharkinta. Se tarkoittaa, että oleskeluluvan saaminen työpaikan perusteella ei ole itsestään selvää. Viranomaiset selvittävät ensin olisiko Suomessa valmiiksi työttömiä sillä alalla, mille ulkomaalainen olisi tulossa töihin. Jos samalla alalla on valmiiksi paljon työttömiä, oleskelulupahakemus ehkä hylätään. - Lähde: https://www.maahanmuutto.net/19 

#### Perustelut ehdotukselle   

Google 15 000. - Kyseessä on eri asia kuin tarveharkinta. - Tämä liittyy ulkomaalaislakiin, olisiko oikea temaattinen ryhmä maahanmuuttopolitiikka? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. tämä: https://www.kansanuutiset.fi/artikkeli/3784742-saatavuusharkinnan-poistoesitys-kuohuttaa-ay-vakea 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu_ekmark@hotmail.com **Termiehdotus Fintossa:** [saatavuusharkinta](http://finto.fi/yse/fi/page/Y505579)

**Comment by Elmukelmu** [comment]
Saatavuusharkinnan rinnalla taidetaan kuitenkin käyttää myös tarveharkinta-sanaa (joka YSAssa jo on).

**Comment by mirmaid** [comment]
_Tarveharkinta_ on Melindassa käytetty varsin erilaisissa yhteyksissä (Tuli muuten vastaan kenties pisin näkemäni yhdyssana nimekkeessä: _Nestesilikonikumikaksikomponenttiruiskuvalun tarvekartoitus_ 🥇), ja kyllä sitä tosiaan tästä ehdotuksen aiheestakin käytetään ristiin saatavuusharkinnan kanssa.

**Comment by mariaforsen** [comment]
Tarveharkinta=behovsprövning käytetään ruotsin osalta lähinnä erilaisten (sosiaali)avustusten yhteydessä, niinkuin esim. TEPAssa käsitellään, mutta toisaalta myös yllä olevasta muodossa behovsprövning av arbetskraft (Suomessa). Saatavuusharkinta voisi ruotsiksi mahd. olla "tillgångsprövning" (Suomessa) ja tämä käsittäisi nimenomaan "työvoiman saatavuusharkinta". 

Olisiko muuten selkeämpää ottaa esim. "työvoiman saatavuusharkinta" jos otetaan jotain? Kun on hyvin spesifi asia kyseessä niin tällä tavalla olisi helpompaa välttää väärinkäsityksiä ja -käytöksiä.

**Comment by YSA-kokous** [comment]
työvoiman saatavuusharkinta

**Comment by mariaforsen** [comment]
Sv.  tillgångsprövning ET behovsprövning av arbetskraft, prövning av tillgången på arbetskraft
http://www.finlex.fi/sv/esitykset/he/2017/20170128.pdf
