### ISSUE TITLE
supramolekulaarinen kemia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5580]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

supramolekulaarinen kemia 

#### Ehdotettu termi englanniksi   

supramolecular chemistry 

#### Ehdotettu termi ruotsiksi   

supramolekylär kemi 

#### Vaihtoehtoiset termit ja ilmaisut   

supramolekyylikemia 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kemia](http://www.yso.fi/onto/yso/p1801) 

#### Assosiatiiviset (RT)   

[molekyylit](http://www.yso.fi/onto/yso/p2984) 
[orgaaninen kemia](http://www.yso.fi/onto/yso/p11902) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Supramolekulaarinen_kemia 
LCSH : https://lccn.loc.gov/sh00000385 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Tarkoitusta täsmentävä selite   

Kemian osa-alue, joka tutkii molekyyleista koostuvia rakenteita ja systeemejä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jykdok.1722774 

#### Perustelut ehdotukselle   

Melko tutkittu kemian osa-alue, jota vaikea kuvailla muilla termeillä. Melindassa haku "supramolecular" antaa 191 tulosta. 

**Ehdottajan nimi:** Matti Rajahonka 
**Ehdottajan sähköpostiosoite:** matti-petteri.rajahonka@jyu.fi 
**Ehdottajan organisaatio:** Jyväskylän yliopiston kirjasto **Termiehdotus Fintossa:** [supramolekulaarinen kemia](http://finto.fi/yse/fi/page/Y505580)

**Comment by mariaforsen** [comment]
Sv. supramolekylär kemi
