### ISSUE TITLE
sipuli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5582]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sipuli 

#### Ehdotettu termi ruotsiksi   

lök 

#### Vaihtoehtoiset termit ja ilmaisut   

Allium cepa 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sipulit](http://www.yso.fi/onto/yso/p8074) 

#### Alakäsitteet (RT)   

[vihersipuli](http://www.yso.fi/onto/yso/p17205) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.39988 
AFO : https://finto.fi/afo/fi/page/p761 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helkassa yli 30 viitteessä 

#### Perustelut ehdotukselle   

yleinen viljelykasvi 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [sipuli](http://finto.fi/yse/fi/page/Y505582)

**Comment by mirmaid** [comment]
Laji.fi: Allium cepa = ruokasipuli, voisi olla parempi jos sanastossa on lisäksi _sipulit_?

**Comment by LeKorsu** [comment]
Sipulit on, ja sen alla ruohosipuli, valkosipuli, vihersipuli.  Punasipuli puuttuu ja ties mitä muita. Salottisipuoli nyt ainakin.

**Comment by mariaforsen** [comment]
Sv. lök
