### ISSUE TITLE
sipulit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5583]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sipulit](http://www.yso.fi/onto/ysa/Y104334) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi laukat (suku - Allium), alakäsitteiksi: sipuli, ruohosipuli, valkosipuli. Vihersipuli on sipulin alakäsite.
Yläkäsitteeksi narsissikasvit
https://laji.fi/taxon/MX.39988 

#### Perustelut ehdotukselle   

sipulit-suvun nykyinen nimi on laukat https://laji.fi/taxon/MX.39988 

#### Ehdottaja   

Päivi Lipsanen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

paivi.lipsanen@helsinki.fi

**Comment by YSA-kokous** [comment]
-laukat -muodot korvatuiksi
