### ISSUE TITLE
valtakunnan metsien inventointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5586]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valtakunnan metsien inventointi 

#### Ehdotettu termi englanniksi   

National Forest Inventory (NFI) https://www.luke.fi/en/natural-resources/forest/forest-resources-and-forest-planning/ 

#### Ehdotettu termi ruotsiksi   

riksskogstaxering (RST) https://www.luke.fi/sv/om-naturresurser/skog/skogsresurser-och-skogsplanering/ 

#### Vaihtoehtoiset termit ja ilmaisut   

VMI, vmi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[metsänarviointi](http://www.yso.fi/onto/yso/p18894) 

#### Assosiatiiviset (RT)   

[metsävarat](http://www.yso.fi/onto/yso/p15460) 
[ympäristön tila](http://www.yso.fi/onto/yso/p4342) 

#### Vastaava käsite muussa sanastossa   

AFO : https://finto.fi/afo/fi/page/p5607 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Tarkoitusta täsmentävä selite   

VMI on metsien ja metsävarojen seurantajärjestelmä, joka tuottaa tietoa alueittaisista ja koko maan
metsävaroista – puuston määrästä, kasvusta ja laadusta, maankäytöstä ja metsien omistussuhteista, metsien terveydentilasta, metsien monimuotoisuudesta, metsien hiilivaroista ja niiden muutoksista,
https://www.luke.fi/tietoa-luonnonvaroista/metsa/metsavarat-ja-metsasuunnittelu/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suomen metsät 2009–2013 ja niiden kehitys 1921–2013, http://jukuri.luke.fi/bitstream/handle/10024/540537/luke-luobio_59_2017.pdf?sequence=6&isAllowed=y 

#### Perustelut ehdotukselle   

Melindassa asiasanana 124 viitteessä, Helkassa 108 viitteessä 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [valtakunnan metsien inventointi](http://finto.fi/yse/fi/page/Y505586)

**Comment by mariaforsen** [comment]
Sv. riksskogstaxering
