### ISSUE TITLE
son

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5587]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[son](http://www.yso.fi/onto/ysa/Y110862) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

son (kuubalainen musiikki) ?
son (meksikolainen musiikki) ?
tms. selkeämpi jako? 

#### Perustelut ehdotukselle   

Sanastossa on nyt sekä son että son-musiikki. Termeistä ei mielestäni käy ilmi mihin oikein viittaavat. Molemmat ovat musiikkia, joten -musiikki-lisäys toiseen ei oikein auta. Ainakin ruotsiksi on tarkoitus tehdä selkemmät termit, son (kubansk musik), son (mexikansk musik)? 
Käsitteet linkitetty: Popular music--Cuba, Folk music--Mexico. Ks. myös yläkäsitteet ja huomautus. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mariaforsen** [comment]
Tarvitaan myös Genresanasto-työssä.

**Comment by asormune** [comment]
Voisiko käyttää termejä "Son cubano" ja "Son mexicano"

**Comment by tpalonen** [comment]
Jos jokin muutos tehdään, pitäisi muuttaa myös määritelmiä. Vrt. son-käsitteen määritelmä: "Kuubalainen populaarimusiikkilaji, jonka tahtilaji on 2/4. Sonin läheinen sukulainen on salsa. Meksikossa ja muualla Väli-Amerikassa esiintyvästä sonista, joka poikkeaa rakenteeltaan ja soittimistoltaan kuubalaisesta sonista, käytetään termiä son-musiikki."

**Comment by ksornova** [comment]
son cubano
KT kuubalainen son
KT son
KT son (kuubalainen populaarimusiikki)
Määritelmä: Salsan esi-isänä pidetty kuubalainen populaarimusiikkilaji. 
Huomautus: Meksikossa ja muualla Väli-Amerikassa esiintyvästä sonista, joka poikkeaa rakenteeltaan ja soittimistoltaan kuubalaisesta sonista, käytetään termiä son mexicano.

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan termit son mexicano ja son cubano
