### ISSUE TITLE
Nižni Novgorod

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5588]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Nižni Novgorod 

#### Ehdotettu termi ruotsiksi   

Nizjnij Novgorod 

#### Ehdotettu termi englanniksi   

Nizhny Novgorod 

#### Vaihtoehtoiset termit ja ilmaisut   

Nizhni Novgorod 
Nižnij Novgorod 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n86059283> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Ni%C5%BEni_Novgorod 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Kaupunki Venäjällä. 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Нижегородская ярмарка 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Nižni Novgorod](http://finto.fi/yse/fi/page/Y505588)

**Comment by mirmaid** [comment]
Lisätty sanastoon.
