### ISSUE TITLE
heavy rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5589]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[heavy rock](http://www.yso.fi/onto/ysa/Y110284) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muuteteen nykyinen KT-muoto "heavy metal" käytettäväksi termiksi ja vastaavasti "heavy rock" KT-muodoksi joko sille tai "hard rock" -asiasanalle. 

#### Perustelut ehdotukselle   

"Heavy metal" on nykyään käytetympi ilmaisu kuin "heavy rock", ml. suomenkielinen Wikipedia-artikkeli aiheesta [https://fi.wikipedia.org/wiki/Heavy_metal]. Lisäksi termille ST-suhteiset asiasanat ovat kaikki "metal"-loppuisia. Toinen vaihtoehto voisi olla "heavy metal"- ja "heavy rock" -asiasanojen eriyttäminen toisistaan à la Wikipedia, jossa viittausmuotona on "heavy rock" KÄ "hard rock" [https://fi.wikipedia.org/wiki/Hard_rock]. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Hevikansa ottaisi tämän muutoksen hurraa-huudoilla vastaan!

**Comment by tpalonen** [comment]
Kannatan ehdotusta. Tätä puoltaa myös se, että "heavy rock"-käsitteen alakäsitteet ovat kaikki metal-päätteisiä.

**Comment by mirmaid** [comment]
Huom. myös suhde _hard rock_ -termiin, tuleeko osa heavy rockin (nyt heavy metallin) ohjaustermeistä myös tai pelkästään sen ohjaustermeiksi?

**Comment by MUUSA-kokous** [comment]
Muutetaan myös SLM:ssä muotoon heavy metal. RT hard rock sekä YSAan että SLM:ään.

**Comment by mirmaid** [comment]
Ok/SLM
