### ISSUE TITLE
orkesteritoiminta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5590]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[orkesteritoiminta](http://www.yso.fi/onto/ysa/Y100713) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite epätäsmällisenä. 

#### Perustelut ehdotukselle   

Asiasana "alueorkesteritoiminta" on selvä, mutta tätä aiemmin orkesterien muuksi musiikilliseksi toiminnaksi määritelty "orkesteritoiminta"-termiä on käytetty sangen satunnaisesti ja sekavasti. Orkesterien esiintymiset yms. voidaan ilmaista muilla YSA-termeillä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by asormune** [comment]
Fintossa on (yleiskäsite) kulttuuritoiminta, jolla alakäsitteinä alueteatteritoiminta ja orkesteritoiminta. Voisiko (poisjätettävän) orkesteritoiminnan korvata asiasanoilla "kulttuuritoiminta + orkesterit" (silloin, kun kyseessä ei ole "konserttitoiminta", joka on Finton termi)

**Comment by jtuohini** [comment]
Nimenomaan tuo kahden termin yhdistäminen olisi hyvä tapa. Samalla voisi olla täsmällisempi tarpeen mukaan, esim. "kulttuuritoiminta + kamariorkesterit" ja "kulttuuritoiminta + sinfoniaorkesterit" tai vastaavasti vaikkapa "kulttuuritoiminta + sekakuorot" jne.

**Comment by mariaforsen** [comment]
Ruotsiksi toisinpäin: "regional orkesterverksamhet" ei löydy edes googlesta, sen sijaan kun "orkesterverksamhet" on aika paljon käytetty.  Toisaalta näyttää siltä että suomenkin osalta on sama tilanne, eikö siis olisi hyvä pysyä laajemmassa/yleisesti käytetyssä muodossa?
