### ISSUE TITLE
mainstream

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5591]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mainstream](http://www.yso.fi/onto/ysa/Y214552) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi muotoon "mainstream jazz". 

#### Perustelut ehdotukselle   

Mainstream on monimerkityksinen termi, joka voi viitata melkein mihin tahansa, ei pelkästään musiikkiin eikä  pelkästään jazziin. Mainstream on mm. erään yhtyeen, erään artistin ja erään levy-yhtiön nimi. Grove-tietosanakirja ei tunne mainstream-termiä. Grove, Oxford Companion to Music ja Wikipedia käyttävät muotoa "mainstream jazz". 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by ksornova** [comment]
Kannatan muutosta!

**Comment by jtuohini** [comment]
Tulisiko sitaattilainana "**mainstream jazz**" vai sittenkin mieluummin suomeksi mukautettuna "**mainstream-jazz**" (analogiana **Chicago-jazz**, **third stream -jazz** jne)?

**Comment by asormune** [comment]
Kannatan ilmaisua "maistream-jazz"

**Comment by ksornova** [comment]
hmm. meillä on toisaalta myös "acid jazz" ja "free jazz". Soitan Kielitoimiston neuvontapuhelimeen...

**Comment by asormune** [comment]
Kannatan kielitoimiston sallimaa yhdysmerkitöntä muotoa, eli peukku pois viivallisesta.

**Comment by jtuohini** [comment]
Ja minä taas kannatan viivallista muotoa, selvyyden vuoksi (lainatakseni Katerinan Kielitoimisto-vastausta).

**Comment by YSA-kokous** [comment]
mainstream jazz
