### ISSUE TITLE
country and western

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5592]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[country and western](http://www.yso.fi/onto/ysa/Y214440) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite.

Lisäksi ehdotan, että country-käsitteelle lisätään ohjaustermeiksi "country and western" ja "country-musiikki". 

#### Perustelut ehdotukselle   

Sanastossa on erikseen käsitteet "country" ja "country and western". Näiden välinen ero on epäselvä. Grove-sanakirjassa ei ole erikseen näitä käsitteitä. Oxford Companion of Musicissa "country and western" on "country music"-käsitteen ohjaustermi. Wikipediassa "Country and western" on ohjaustermi "Country music"-artikkeliin ja suomenkielisessä Wikipediassa niin ikään "country and western" ohjaa "Country"-artikkeliin. Wikipedian mainitsee country music -termistä "frequently referred to as just country and historically country and western". 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by ksornova** [comment]
Tästä oli puhetta YSOn musa-kokouksessa. Kannatan selkeyttämistä!

**Comment by asormune** [comment]
Keski-kirjastojen kannassa lähes kaikissa "country and western" asiasanoitetuissa tietueissa on myös asiasana "country". Eli puoltaa poistoa.

**Comment by mariaforsen** [comment]
Näin tehty myös SAOssa.

**Comment by TommiViitamies** [comment]
Nämähän eivät ole täysin synonyymejä, vaan tyylillisiä ja ajallisia eroja on, kuten Wikipediastakin käy ilmi. Myös MUSAn määritelmissä on eroja, vaikka ne onkin esitetty niissä epätäsmällisesti. Ehdotan, että Muusa puisi tätä vielä.

**Comment by ksornova** [comment]
@TommiViitamies:

**Comment by ksornova** [comment]
anteeksi, yritin tehdä muuta, mutta onnistuinkin sulkemaan issuen. noh, nyt se taitaa olla taas auki...

**Comment by TommiViitamies** [comment]
Country and westernin määritelmäehdotuksen tekeminen jäi minulle. Tutkin asiaa enkä saanut oleellista eroa hahmotettua countryyn nähden. Luovun yrityksestä ja siirryn kannattamaan alkuperäistä ehdotusta.

**Comment by ksornova** [comment]
Muusa-ryhmän kokous (15.5.2018): kannatetaan ehdotusta
