### ISSUE TITLE
uuskungfutselaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5593]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uuskungfutselaisuus 

#### Ehdotettu termi ruotsiksi   

neokonfucianism 

#### Ehdotettu termi englanniksi   

Neo-Confucianism 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Uuskungfutselaisuus 
Wikipedia : https://en.wikipedia.org/wiki/Neo-Confucianism 
LCSH : <http://id.loc.gov/authorities/subjects/sh85090737.html> 
SÄO : Neokonfucianism 

#### Perustelut ehdotukselle   

Merkittävä Itä-Aasiassa vaikuttanut aatesuunta. YSA:ssa on vain kungfutselaisuus. Esim Helkassa LCSH:n Neo-Confucianism -termiä käytetty 57 kertaa. Nämä pitäisi voida kuvailla suomeksi täsmällisesti. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3018588 

**Ehdottajan nimi:** Juha Leppämäki 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** juha.leppamaki@helsinki.fi **Termiehdotus Fintossa:** [uuskungfutselaisuus](http://finto.fi/yse/fi/page/Y505593)

**Comment by mirmaid** [comment]
Melindassa 4 viitettä.

Kungfutselaisen filosofisen, uskonnollisen ja polittisen ajattelun elpynyt muoto, joka syntyi Kiinassa 800-luvun puolivälissä ja hallitsi Kiinan poliittista kulttuuria 1200-luvulta 1800-luvulle saakka. (Wikipedia)

**Comment by mariaforsen** [comment]
Sv. neokonfucianism
