### ISSUE TITLE
melodiadiktaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5594]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[melodiadiktaatit](http://www.yso.fi/onto/ysa/Y199057) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan yksikkömuotoon "melodiadiktaatti". 

#### Perustelut ehdotukselle   

Sanastossa on "diktaatti" ja "rytmidiktaatti". Yksikkömuoto yhdenmukaistaisi termejä. YSOssa melodiadiktaatit hierarkisoidaan diktaatin alle ja sitäkin kautta yksikkömuoto olisi luontevampi. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by ilkkahaataja** [comment]
Luumu-kokous (27.11.2017): Puollamme ehdotusta.
