### ISSUE TITLE
telomeerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5595]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

telomeerit 

#### Ehdotettu termi ruotsiksi   

telomerer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kromosomit](http://www.yso.fi/onto/yso/p7688) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

Telomeeri (kreikan telos (loppu) ja meros (osa)) on eukaryoottisilla eli aitotumallisilla soluilla esiintyvä DNA-jakso kromosomien päässä.  (Wikipedia) 

#### Perustelut ehdotukselle   

Täsmällinen termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pitkän ja hyvän elämän biologia : telomeerit ja terveys 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [telomeerit](http://finto.fi/yse/fi/page/Y505595)

**Comment by mirmaid** [comment]
Yksikkö vai monikko:
FinMeSH: 
Telomeeri KT telomeerit http://finto.fi/mesh/fi/page/D016615
Telomeerien lyheneminen KT telomeerin lyheneminen http://finto.fi/mesh/fi/page/D059506

LCSH: Telomere http://id.loc.gov/authorities/subjects/sh94005630

Melindassa 3 kertaa yksikössä, 4 kertaa monikossa.

**Comment by YSA-kokous** [comment]
telomeerit

**Comment by mariaforsen** [comment]
Sv. telomerer
