### ISSUE TITLE
Commodore 64

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5596]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Commodore 64 

#### Ehdotettu termi ruotsiksi   

Commodore 64 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tietokoneet](http://www.yso.fi/onto/yso/p6787) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Perustelut ehdotukselle   

Tuotemerkki 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Commodore 64 - Tasavallan tietokone 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [Commodore 64](http://finto.fi/yse/fi/page/Y505596)

**Comment by jtuohini** [comment]
Ehdotan, että asiasanaksi tälle valittaisiin mieluummin muoto _Commodore 64 -tietokone_ tms. Tuotemerkin ja mallin sisältävät nimet olisivat varmemmin yksiselitteisiä, mikäli termit sisältäisivät aina varsinaisen "asian", tässä tapauksessa maininnan siitä, että kyse on tietokoneesta. Toki "kaikki" tietävät Commodore 64:n, mutta entä jonkin harvinaisemman tapauksen kohdalla?

**Comment by asormune** [comment]
tuotemerkit on ohjaustermi, käytettävä termi = tavaramerkit. Mitenkä ohjeistus musiikin tavaramerkkeihin? Esim. on asiasanoitettu: $aFender Telecaster (tavaramerkki)$2ysa. Pitäisikö muuttaa: $aFender Telecaster -kitara (tavaramerkki)$2ysa

**Comment by jtuohini** [comment]
Lisää analogiaa: "Steinway (tavaramerkki)" vastaan "Steinway-piano" (LCSH-vastine **Steinway piano** [http://id.loc.gov/authorities/subjects/sh96008521]), "Stradivarius (tavaramerkki)" vastaan "Stradivarius-viulu" (LCSH-vastine **Stradivarius violin** [http://id.loc.gov/authorities/subjects/sh2006007757]), "Hammond (tavaramerkki)" vastaan "Hammond-urut" (LCSH-vastine **Hammond organ** [http://id.loc.gov/authorities/subjects/sh85058585]) jne. Kumpaan termin on tarkoitus viitata, tavaramerkkiin vai soittimeen?

**Comment by mirmaid** [comment]
Toisaalta epäilen että paljon useammat tietävät mikä on Commodore 64 tai Fender Telecaster, kuin mitä ovat danit tai divertikuloosi. Tarkenteiden lisäämistä olisi kyllä hyvä käsitellä yleisesti.

**Comment by mirmaid** [comment]
Käytetty 8 kertaa YSA-sanana ilman tarkennetta.

**Comment by mariaforsen** [comment]
Tarkenteita ei linjausten mukaan lisätä, ellei ole välttämätöntä sekaannusten välttämiseksi jne.
