### ISSUE TITLE
germaaninen mytologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5597]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

germaaninen mytologia 

#### Ehdotettu termi englanniksi   

Germanic mythology 

#### Ehdotettu termi ruotsiksi   

Germansk mytologi 

#### Vaihtoehtoiset termit ja ilmaisut   

mytologia - germaanit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mytologia](http://www.yso.fi/onto/yso/p7687) 

#### Vastaava käsite muussa sanastossa   

Mythology, Germanic : https://lccn.loc.gov/sh85089395 
Germaaninen mytologia : https://fi.wikipedia.org/wiki/Germaaninen_mytologia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Melindassa 7 kertaa, virheellisesti myös YSA-terminä. Asiasanaketjua (tai yhdistelmää) mytologia - germaanit on käytetty Melindassa 72 kertaa. 
YSAssa on myös suomalainen mytologia, skandinaavinen mytologia ja antiikin mytologia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Encyclopedia of Norse and Germanic folklore, mythology, and magic (2016); In prayer and laughter: essays on medieval Scandinavian and Germanic mythology, literature, and culture (2016) 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [germaaninen mytologia](http://finto.fi/yse/fi/page/Y505597)

**Comment by mariaforsen** [comment]
Sv. germansk mytologi
