### ISSUE TITLE
trimmaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5598]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[trimmaus](http://www.yso.fi/onto/ysa/Y112838) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Rajataan eläinten trimmaus-merkitykseen. 

#### Perustelut ehdotukselle   

Ks. YSO-issue: https://github.com/NatLibFi/Finto-data/issues/847 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
trimmaus (eläimet), mahdollisesti purjeiden trimmaus (?)

**Comment by YSA-kokous** [comment]
trimmaus (eläimet)
