### ISSUE TITLE
digitaalikuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5599]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[digitaalikuvaus](http://www.yso.fi/onto/ysa/Y120948) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

digitaalikuvaus, ilmakuvaus, mainoskuvaus, satelliittikuvaus, trikkikuvaus, vedenalainen kuvaus - miten huomioidaan toimivalla tavalla se, että ruotsiksi ei ole yhtä termiä valokuvaukselle ja liikkuvan kuvan kuvaamiselle? 

#### Perustelut ehdotukselle   

ruotsinkieliset vastineet ja yläkäsitteet ongelmallisia, tarvitaan johdonmukainen ratkaisu 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
ALLFO: digitaalikuvaus=digitalfotografering och -filmning

KS: ilmakuvaus: valokuvaaminen lentokoneesta, helikopterista tms., ilmavalokuvaus.
Jos kuitenkin halutaan viitata myös "elokuvaukseen" niin voidaan tehdä samalla tavalla: flygfotografering och -filmning.

Mainoskuvaus=reklamfotografering och -filmning?

KS: satelliittikuvaus: valokuvaus satelliitin avulla.  Jos kuitenkin halutaan sisällyttää myös "elokuvaus" > satellitfotografering och -filmning?

Trikkikuvaus=trickfotografering och -filmning /ALLFO

Vedenalainen kuvaus=undervattensfotografering och -filmning /ALLFO

**Comment by mirmaid** [comment]
^ Tämä olisi varmaan helpoin ratkaisu. Jos jaettaisiin suomeksi, olisi varmaankin

- digitaalivalokuvaus, ilmavalokuvaus, mainoskuvaus (valokuvaus)/mainosvalokuvaus, satelliittikuvaus (valokuvaus), trikkikuvaus (valokuvaus), vedenalainen valokuvaus 

- digitaalikuvaus (liikkuva kuva), ilmakuvaus (liikkuva kuva), mainoskuvaus (liikkuva kuva), satelliittikuvaus (liikkuva kuva), trikkikuvaus (liikkuva kuva), vedenalainen kuvaus (liikkuva kuva)

**Comment by LeKorsu** [comment]
Valokuva-asiantuntijamme mielestä yhteinen termi digitaalikuvaus, ilmakuvaus jne on (suomeksi) parempi kuin jaetut. Sitä hän rupesi miettimään, että onko digitaalikuvaus enää miten tarpeellinen, kun kaikki kuvaaminen (still tai video) on nykyään digitaalista kaiketi lukuun ottamatta eräitä elokuvaajia, jotka kuvaavat filimille. Taitaa niitä olla joitakin valokuvaajiakin, jotka vielä käyttävät kinofilmiä.

Kun samoilla laitteillakin tehdään nykyään molempia - siis lähinnä järjestelmäkameroilla kuvataan laadukasta videokuvaa - jaottelu tuntuu - edelleen suomeksi - turhalta, joten jos tuo yhdistelmä -fotografering ja -filmning ruotsiksi onnistuu, ehdotan sitä.

**Comment by YSA-kokous** [comment]
Ei muutosta
