### ISSUE TITLE
työkoirat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5600]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

työkoirat 

#### Ehdotettu termi ruotsiksi   

brukshundar? 

#### Ehdotettu termi englanniksi   

working dogs? 

#### Vaihtoehtoiset termit ja ilmaisut   

KT virkakoirat 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Luokka:Ty%C3%B6koirat
https://sporttirakki.fi/kategoria/koiratieto/tyokoirat/
Tarvitaan yläkäsite opas-, poliisi-, avustaja-, palvelus- jne.koirille kuvailua varten 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Koiran käyttäytymisen perusteet /Resi Gerritsen - myös ns. virkakoirien kouluttamisesta 

**Ehdottajan nimi:** Auli Hoffren 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.hoffren@btj.fi **Termiehdotus Fintossa:** [työkoirat](http://finto.fi/yse/fi/page/Y505600)

**Comment by FinMeSHienPaimentaja** [comment]
Selvennystä:

”Työkoiria” ovat käsittääkseni muutkin kuin ”virkakoirat”,  esim. lampaita ja poroja paimentavat koirat.

Kennelliiton sivuilla käytetään termiä ”hyötykoirat” ks. 
https://www.kennelliitto.fi/koirat/hyotykoirat

”Hyötykoiriin” sisältyvät mm. ”virkakoirat” (eli  esim. viranomaisten kuten poliisin ja tullin huumekoirat, ruumiskoirat, rahakoirat ym.) sekä ”opaskoirat” ja ”avustaja-koirat”, jotka Kennelliiton sivujen mukaan ovat ”henkilökohtaisia hyötykoiria”. 

”Palveluskoirat” on käsittääkseni lähes synonyymi ”työkoirille”/”hyötykoirille”, se voinee tarkoittaa myös palveluskoirarotuja. 

Mielestäni "lukukoirat" ja "kaverikoirat" sisältyvät käyttötarkoituksensa perusteella  myös ”hyötykoiriin”/”työkoiriin” - niistä on ihmiselle melko täsmällisesti määriteltyä hyötyä. 

rosa.venalainen@helsinki.fi

**Comment by mariaforsen** [comment]
Brukshundar=palveluskoirat nyt sanastossa. 

Kielitoimiston sanakirja:
Palveluskoira: 
1. etsintä-, opastus-, suojelu- tms. tehtäviin käytettävä koira.
2. Palveluskoirat koirarotuja jotka soveltuvat em. tehtäviin. 

Työkoira tai hyötykoira ei sanakirjassa (tai MOTissa). TEPAssa: fi palveluskoira; työkoira sv brukshund

Ruotsiksi käytetään myös "arbetshundar" ja "tjänstehundar", mutta ei juuri "nyttohundar" (hyötyjä on koirilla monenlaisia, esim. seura, joten melkein kaikki koirat olisivat sen mukaan oikeastaan "hyötykoiria")

**Comment by FinMeSHienPaimentaja** [comment]
Itsellekin tuo "hyötykoirat" on vieraampi, vaikka koiraharrastaja olen ja olen ollut jo pitkään. "Työkoirat" on vanha tuttu termi, samoin "palveluskoirat" (joka Kielitoimiston sanakirjankin mukaan painottuu "virkakoiriin", "pelastuskoiriin" tms. päin).

**Comment by satuniininen** [comment]
YSOssa on tällä hetkellä palveluskoirat = working dogs (MOT-sanakirjassa palveluskoira = working dog, TEPAssa palveluskoira; työkoira = utility dog)

Jos työkoirat otetaan uutena, niin täytynee täsmentää, miten se eroaa palveluskoirasta.

**Comment by mirmaid** [comment]
Palveluskoirat viittaa ehkä enemmän tietyissä koiraurheilun lajeissa http://www.palveluskoiraliitto.fi/lajit/palveluskoirakoelajit.html kisaaviin rotuihin https://www.virkku.net//index.cfm?frwd=Yes&template=dynamic.cfm&sivuId=7&sivualueId=6. Mulla on sellainen mielikuva että FCI 1 ryhmää olisi nimitetty aikaisemmin palveluskoiriksi, nykyään se on Lammas- ja karjakoirat. Ruotsiksi brukshundar, mutta en tiedä miten tuon englanniksi kääntäisi ja käytössä menee sekaisin työkoirien kanssa. Tähän voisi tietysti kehitellä jotain kiertotietä tyyliin palveluskoiraharrastus tms. ja työkoirat.

**Comment by YSA-kokous** [comment]
otetaan työkoirat, palveluskoirat-termille määritelmä

**Comment by mariaforsen** [comment]
Sv. arbetshundar ET tjänstehundar
