### ISSUE TITLE
hagiografiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5602]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hagiografiat 

#### Ehdotettu termi englanniksi   

hagiographies 

#### Ehdotettu termi ruotsiksi   

hagiografier 

#### Vaihtoehtoiset termit ja ilmaisut   

hagiologiat 
pyhimyselämäkerrat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elämäkerrat](http://www.yso.fi/onto/yso/p11597) 

#### Vastaava käsite muussa sanastossa   

Suomalainen Wikipedia : https://fi.wikipedia.org/wiki/Hagiografia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

Nykyinen asiasana "hagiografia" on kaksimerkityksinen, kattaen sekä hagiografioiden laatimisen että hagiografiat itsensä, eli pitäisi jakaa; nykyinen yksikkömuoto tarkoittaisi jatkossa hagiografioiden laatimista ja tämä uusi asiasana laatimisen tuotoksia. – Lisäksi termi pitäisi ottaa Suomalaiseen lajityyppi- ja muotosanastoon, jotta sitä voitaisiin käyttää kuvailtaessa pyhimyselämäkertoja (vastine LCGFT-sanastossa: "Hagiographies" [http://id.loc.gov/authorities/genreForms/gf2015026032]). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [hagiografiat](http://finto.fi/yse/fi/page/Y505602)

**Comment by mirmaid** [comment]
Jos hyväksytään, molemmat tarvitsevat tarkenteen.

**Comment by AuHo22** [comment]
Kannatan ainakin monikkomuodossa hyväksymistä ja lisäämistä genresanastoon. Kuinka paljon tarvetta oikeastaan on yksikkömuotoiselle merkitykselle eli tulleeko vastaan aineistoja, joissa itse pyhimyselämäkerran laatimista tarkastellaan? Tai voiko senkin ilmaista monikkomuodon avulla?

**Comment by mariaforsen** [comment]
Jos laittaa 650-kenttiin hagiografiat ja kirjoittaminen tms. niin eiköhän se ole aika selvää. Minusta pitäisi välttää yksikkö+monikko-muotoja silloin kun mahdollista. Samalla tavalla on myös esim. biografier KT biografi. Ruotsiksi hagiografi käytetään nimenomaan genrestä, ei niinkään niiden kirjoittamisesta/laatimisesta sinänsä. Ks. myös: http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:hagiografia "Pyhimysten elämän tutkimusta kutsutaan hagiologiaksi"

**Comment by YSA-kokous** [comment]
hagiografiat

**Comment by mariaforsen** [comment]
Sv. hagiografier
