### ISSUE TITLE
syötävät hyönteiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5605]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syötävät hyönteiset 

#### Ehdotettu termi ruotsiksi   

ätliga insekter 

#### Ehdotettu termi englanniksi   

edible insects 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85066704 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Perustelut ehdotukselle   

Sanastossa on jo käsite "syötävät kukat". Tämä on vastaava. Ajankohtainen aihe. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Insects as food and feed from production to consumption 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [syötävät hyönteiset](http://finto.fi/yse/fi/page/Y505605)

**Comment by mirmaid** [comment]
Viime kokouksessa hyväksyttiin _hyönteistalous_.

**Comment by Elmukelmu** [comment]
Hyönteisruoka, hyönteisravinto - näitä sanojakin esiintyy.

**Comment by mariaforsen** [comment]
Sv. ätbara insekter, ätliga insekter

**Comment by LeKorsu** [comment]
Pitää varmaan miettiä seuraavan issuen kanssa. Jo(i)takin pitää varmasti ottaa, on tämä tosiaan sen verran ajankohtainen asia.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Hyönteisruoka Googlella n. 23 700, syötävät hyönteiset n. 400.

**Comment by ilona-x** [comment]
Vielä yksi vaihtoehto lisää: **ruokahyönteiset** Googlella  n. 3500 osumaa esim. https://www.luke.fi/mt-ruokahyonteisten-tuotanto-on-lahdossa-lentoon/

**Comment by YSA-kokous** [comment]
hyönteisruoka

**Comment by mariaforsen** [comment]
Sv. insektsmat ET insektmat
