### ISSUE TITLE
alueohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5607]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[alueohjelmat](http://www.yso.fi/onto/ysa/Y100711) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

Käytetty radio-ohjelmista ja toisaalta alueellisista kehittämisohjelmista ym. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Näin ruotsiksikin (regionala program)

**Comment by LeKorsu** [comment]
Tarkenne-ehdotuksia: alueohjelmat (media) lienee helppo, mutta toinen jo kiperämpi?: alueohjelmat (suunnitelmat)

**Comment by YSA-kokous** [comment]
alueohjelmat (media) 
alueohjelmat (suunnitelmat)
