### ISSUE TITLE
Sherborne-liikunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5609]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Sherborne-liikunta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Moikataan varpailla 

#### Perustelut ehdotukselle   

Tässä puhutaan  Sherborne-liikunta-menetelmästä (kun taas esim. http://www.vammaisurheilu.fi/palvelut/koulutus/sherborne käyttää pelkkää Sherborne-termiä). 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [Sherborne-liikunta](http://finto.fi/yse/fi/page/Y505609)

**Comment by mariaforsen** [comment]
Sv. Sherborneövningar
