### ISSUE TITLE
eroottinen taide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5610]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

eroottinen taide 

#### Perustelut ehdotukselle   

Erotiikka on aina ollut yksi taiteen aiheista. Ysasta löytyykin asiasanat eroottinen kirjallisuus sekä eroottiset elokuvat. Mutta kun pitäisi kuvailla antiikin tai Kaukoidän eroottista kuvataidetta, niin tähän ei Ysasta löydy sopivaa termiä. Joten saisiko Ysaan uudeksi termiksi eroottinen taide? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** - 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [eroottinen taide](http://finto.fi/yse/fi/page/Y505610)

**Comment by mirmaid** [comment]
_Eroottinen kuvataide_ olisi ehkä parempi. Melindassa kuvataide + erotiikka 108 kertaa.

**Comment by rsarmaja** [comment]
Kyllä, eroottinen kuvataide on parempi kuin pelkkä eroottinen taide.

**Comment by mariaforsen** [comment]
Sv. erotisk bildkonst (tosin vain muutama osuma googlessa, mutta niin antaa myös "eroottinen kuvataide" vain 3 osumaa googlessa).

**Comment by OutiHintikka** [comment]
Taiteentutkimus ei käytä käsitettä; YSAssa eroottisuus. Voidaan tehdä esim. kuvataide/taide, eroottisuus, antiikki

**Comment by YSA-kokous** [comment]
eroottinen taide

**Comment by mariaforsen** [comment]
Sv. erotisk konst
