### ISSUE TITLE
induktiosilmukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5611]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

induktiosilmukka 

#### Ehdotettu yläkäsite YSOssa (LT)   

[apuvälineet](http://www.yso.fi/onto/yso/p9044) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Temaattinen ryhmä äänentoistoon liittyen tai kuulovammaisuuteen liittyen. 

#### Perustelut ehdotukselle   

Google 19 300. Induktiosilmukka eroaa tavanomaisesta apuvälineestä siten, että kyseessä ei ole ainoastaan vammaisella itsellään oleva apuväline, vaan julkisiin tiloihin asennettava apuväline. Liittyy tilasuunnitteluun ja rakennusmääräyksiinkin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kuulovammaisten Nappi-lehden artikkelit 

**Ehdottajan nimi:** Satu Ekmark 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** satu.ekmark@btj.fi **Termiehdotus Fintossa:** [induktiosilmukka](http://finto.fi/yse/fi/page/Y505611)

**Comment by mirmaid** [comment]
Kerran Melindassa monikossa.

https://fi.wikipedia.org/wiki/Induktiosilmukka
https://www.kuulokauppa.fi/tuotteet.html?id=4/

**Comment by mariaforsen** [comment]
Sv. hörslingor ET induktionsslingor, induktiva slingor, teleslingor

**Comment by satuniininen** [comment]
Englanniksi _induction loop_ tai _inductive loop_, kumpaakaan ei LCSH:ssa.

**Comment by YSA-kokous** [comment]
induktiosilmukat
