### ISSUE TITLE
tammi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5612]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tammi](http://www.yso.fi/onto/ysa/Y104061) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon metsätammi, ja otetaan lisäksi tammet, punatammi ja talvitammi. 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Tammi
https://laji.fi/taxon/MX.37989 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by YSA-kokous** [comment]
Myös korkkitammi
