### ISSUE TITLE
oranki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5616]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oranki](http://www.yso.fi/onto/ysa/Y105735) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan orangit (suku) ja borneonoranki tai oranki (laji). 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Orangit
https://laji.fi/taxon/MX.51112 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by tpalonen** [comment]
Kannatan ehdotusta.

Tässä pari tärkeää knoppitietoa, jotka eivät sinänsä liity ehdotettuun muutokseen juuri lainkaan:
1) _“Oranki on kaakkoisaasialainen ihmisapina (Simia satyrus). Euroopan kieliin sana tulee malaijista, jossa se on ‘metsäihminen’, orang ‘mies’ + utan ‘metsä’. Malaijissa sana ei kuitenkaan alun perin tarkoita apinaa (joka on malaijin mawas), vaan oikeaa ‘metsäihmistä’ eli viidakkoheimojen jäseniä. Pitkä nimi on nähtävästi johdonmukaisesti lyhennetty vain suomessa (etymologiaksi jää siis oikeastaan pelkkä ‘ihminen’ ilman ‘metsää’).”_ (Klaus Karttunen: Orientin etymologinen sanakirja)
2) Lisäksi malaijissa monikkomuoto muodostetaan tuplaamalla eli ihmisen monikko on _orang-orang_ ja metsäihmisen monikko _orang-orang utan_.

**Comment by YSA-kokous** [comment]
borneonoranki, orangit
