### ISSUE TITLE
isoihmisapinat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5618]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

isoihmisapinat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ihmisapinat](http://www.yso.fi/onto/yso/p3336) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh96001186> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

YSAssa on ihmisapinat. Suomenkielisessä Wikipediassa mainitaan yläheimo ihmisapinat (Hominoidea) ja heimo isot ihmisapinat (Hominidae). Melindassa on käytetty muotoa ihmisapinat (63 kertaa) ja hominidae (22 kertaa). LCSH Hominids USE FOR Great apes ja Apes USE FOR Hominoidea.
https://laji.fi/taxon/MX.50544 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Mirja Anttila 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [isoihmisapinat](http://finto.fi/yse/fi/page/Y505618)

**Comment by mariaforsen** [comment]
Sv. hominider

**Comment by PaiviLipsanen** [comment]
Laji.fi:
kädelliset
alakäsite: isoihmisapinat
https://laji.fi/taxon/MX.51110
