### ISSUE TITLE
reseptorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5620]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[reseptorit](http://www.yso.fi/onto/ysa/Y111154) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Reseptori
LCSH: Sensory receptors, Cell receptors, Nuclear receptors (Biochemistry) jne. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Lääketieteen termit: _reseptori receptor la e, receptor  n r (< re- la takaisin, vastaan + capere la ottaa kiinni, tarttua, ottaa) vastaanotin; 1. sensory receptor e, sensorisk receptor r aistinreseptori | aistinsolu tai solun osa, joka on erilaistunut reagoimaan tietyntyyppisiin ärsykkeisiin (johonkin tiettyyn energiamuotoon) ja muuntamaan ne hermoimpulsseiksi; 2. hermosolun reseptori | hermosolun kohta, johon esim. toisesta hermosolusta vapautunut välittäjäaine vaikuttaa; 3. hormonireseptori, lääkeainereseptori, kasvutekijäreseptori | solun pinnassa tai solun sisällä oleva makromolekyyli, joka sitoo ligandin (esim. hormoni- tai lääkeainemolekyylin) spesifisellä tavalla (aineen vaikuttamisen edellytys); 4. virusreseptori | solun pinnan makromolekyyli, joka sitoo viruksen spesifisellä tavalla (solun infektoitumisen edellytys)_

**Comment by mirmaid** [comment]
FinMeSH: _aistinreseptorit_ ja _solun pintareseptorit_

https://fi.wikipedia.org/wiki/Reseptori_%28biokemia%29

**Comment by FinMeSHienPaimentaja** [comment]
Käytännön asiasanoittamisen kannalta esim. jako 

reseptorit (fysiologia)
reseptorit (biokemia)

vaikuttaisi hankalalta...

Muuten lääketieteen puolella MeSH:eissä reseptori(t)-termejä on tosi paljon:

https://www.terkko.helsinki.fi/medic/?hakusanat=*reseptori&sivu=asiasanat&alisivu=lista&alkaen=0

Jos jaetaan, niin siinä tapauksessa pitäytyisin ylempänä ketjussa esitetyssä lääketieteen termien mukaisessa jaossa, mutta sekään ei ole mielestäni tarpeeksi kattava ja käyttökelpoinen.
