### ISSUE TITLE
Haaga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5622]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Haaga](http://www.yso.fi/onto/ysa/Y110183) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Huomautus: Haagan kauppala liitetty 1.1.1946 Helsinkiin. Sanastossa myös Helsinki -- Haaga 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Ehdottaja   

- 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Muutetaan muotoon Haagan kauppala KT Haaga (kauppala).

**Comment by mirmaid** [comment]
Linjaustemme mukaan edeltäjä-seuraaja-linkitys. Pitäisikö poistaa virheellinen paikkatyyppi tai muokata lähdeviitettä jotenkin?

**Comment by YSO-kokous** [comment]
Poistetaan tavattaessa paikkatietolinkki ja siihen liittyvä lähdeviittaus silloin, kun viittauksessa mainittu paikkatyyppi on väärä (esim. entisen itsenäisen kunnan tietueessa linkki nykyisen kylän tietoihin Paikkatietoalustalla).

**Comment by YSO-kokous** [comment]
Finton viikkokokouksessa päätettiin, että paikkatietolinkkiä ei poisteta, vaan muutetaan se skos:relatedMatch-linkiksi. Lähdeviittauksessa olevan väärän paikkatyypin voi poistaa. 

Ks. https://www.kiwi.fi/display/ontologiat/2020-06-02+Finto-palvelun+viikkopalaveri

**Comment by mirmaid** [comment]
Mikä on Haagan kauppalan yläkäsite, jos kaikki paikat jatkossa halutaan hierarkiaan?

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
Kirjataan linjauksiin: Entisen kunnan yläkäsitteeksi laitetaan nykyinen maakunta (tai maakunnat), jonka alueella kyseinen kunta on sijannut.

**Comment by mirmaid** [comment]
Edeltäjä-seuraaja-suhteet näkyvät Helsingin maalaiskunnan tietueessa:
rdau:P60686 (seuraaja)
rdau:P60683 (edeltäjä)

En onnistu kuitenkaan lisäämään näitä Haagan kauppalalle (ei löydy valikosta).

**Comment by mirmaid** [comment]
Tehdään RT-suhteet / YSO-paikat-kokous.
