### ISSUE TITLE
puoluepolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5623]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puoluepolitiikka](http://www.yso.fi/onto/ysa/Y118912) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään: LT politiikka 

#### Perustelut ehdotukselle   

Jos kaikki puoluepolitiikka on politiikkaa, pitäisi näitä ilmiöitä kuvaavien asiasanojen välillä vallita LT/ST-suhde. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
YSOssa onkin näin. YSAssa politiikalla ei ole alakäsitteitä, joten sama muutos koskisi suurta määrää termejä - ei ehkä kannata tehdä tässä vaiheessa.
