### ISSUE TITLE
muistojulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5624]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muistojulkaisut 

#### Ehdotettu termi ruotsiksi   

minnesskrifter / minnespublikationer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[julkaisut](http://www.yso.fi/onto/yso/p1548) 

#### Assosiatiiviset (RT)   

[juhlajulkaisut](http://www.yso.fi/onto/yso/p18076) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja:
muistojulkaisu = vars. tiedemiehen tm. huomattavan henkilön muiston kunnioittamiseksi laadittu julkaisu
juhlakirja = merkkipäivää viettävälle tutkijalle, seuralle tms. omistettu teos
(muistokirja = kirja johon kootaan muistorunoja, kiiltokuvia tms., albumi).

Wikipedia (en) (https://en.wikipedia.org/wiki/Festschrift):
"In academia, a Festschrift --- is a book honoring a respected person, especially an academic, and presented during their lifetime. ---  A comparable book presented posthumously is sometimes called a Gedenkschrift ("memorial publication"), but this term is much rarer in English." 

#### Perustelut ehdotukselle   

Tälle olisi käyttöä lähinnä genreterminä (655). Vai käytetäänkö myös "in memory of ..." -kirjoista termiä juhlajulkaisut? Jos käytetään, voisiko termin muistojulkaisut ottaa ohjaustermiksi?
LCSH:
Festschriften
Variants: Anniversary volumes, Commemorative volumes, Homage volumes, Jubilee volumes, Wedding publications 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Gedenkschrift für Mark A. Brandes (1929-2011) 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [muistojulkaisut](http://finto.fi/yse/fi/page/Y505624)

**Comment by jtuohini** [comment]
Sana "muistojulkaisu" voi helposti johtaa arkitasolla myös ajatukseen kaikenlaista muistelua ja muistoja sisältäviin muihin julkaisuihin – ja joskus voi varsinainen juhlakirjakin vahingossa muuttua muistokirjaksi (kun kohde kuolee ennen julkaisuhetkeä) –, joten voisin kuvitella, että 655-kentässä riittäisi yksi termi. Mutta sittenkin on vaikea tietää, kuinka hienojakoiselle terminologialle lopulta on tarvetta; kiinteämittaisissa kentissä kuitenkin on vain yksi merkkipaikka, jossa vaihehtoja vain kaksi: juhlajulkaisu ja ei-juhlajulkaisu, mutta se taas ei ole mikään perustu riisua 655-kentän mahdollisuuksia.

**Comment by mirmaid** [comment]
19 viitettä Melindassa

**Comment by mariaforsen** [comment]
Sv. minnesskrifter ET minnespublikationer
