### ISSUE TITLE
pastillit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5627]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pastillit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. teos Pastillin historiaa / Jukka Vesterinen, Esko Järvilä. 

#### Perustelut ehdotukselle   

Puuttuu YSAsta. Pelkkä makeiset ei riitä 

**Ehdottajan nimi:** Anneli Renfors 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** anneli.renfors@btj.fi **Termiehdotus Fintossa:** [pastillit](http://finto.fi/yse/fi/page/Y505627)

**Comment by mariaforsen** [comment]
Sv. pastiller
