### ISSUE TITLE
majoneesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5628]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

majoneesi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. kirja Ketsuppi, sinappi ja majoneesi / Bettina Snowdon, Martin Lagoda. ISBN 978-951-24-0816-0 

#### Perustelut ehdotukselle   

Puuttuu YSAsta. Kastikkeet ei kuvaava. 

**Ehdottajan nimi:** Anneli Renfors 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** anneli.renfors@btj.fi **Termiehdotus Fintossa:** [majoneesi](http://finto.fi/yse/fi/page/Y505628)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh85082435

Voisi olla myös monikossa, mutta samoin voisivat _ketsuppi, sinappi_ ja monet muut ruoka-termit.

**Comment by mariaforsen** [comment]
Sv. majonnäs
