### ISSUE TITLE
äänilevyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5629]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänilevyt](http://www.yso.fi/onto/ysa/Y100512) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista rajata niin että tämä viittaa vanhempiin levytyyppeihin (ei esim. CD-levyjä)? 

#### Perustelut ehdotukselle   

Näin saataisiin myös täsmäämään ruotsinkielisen Allärs-vastineen "grammofonskivor" kanssa. Todettu aikaisemmassa YSA-kokouksessa: #5535 
Ks. MOTin sanakirjat. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by asormune** [comment]
Olisiko yläkäsite kuitenkin "äänitteet"? MUSA:ssa termi "äänilevyt" = Äänite, jossa informaatio on jollain tekniikalla koodattu pyörivän kiekon pintaan. Eli C-kasetti ei olisi "äänilevy", mutta onko tarkoitettu, että vinyyli/savikiekko on "äänilevy"? Pitäisikö vinyylilevyille saada oma termi, niin saisi hierarkian helpommin.  Äänilevyt termiä on meillä käytetty KESKI-kannassa yli 200 tietueen kuvailuissa. Ehkä osin käytetty "yleisessä", (musiikki)äänitteen merkityksessä. Voisi tuoda hankaluutta, jos äänilevyt termi muutettaisiin tarkoittamaan vinyylilevyjä.

**Comment by mariaforsen** [comment]
Ruotsin osalta olisi ok esim: 

äänitteet=ljudupptagningar 
   ST äänilevyt=grammofonskivor
ja tarvittaessa myös äänilevyt=grammofonskivor ST vinyylilevyt=vinylskivor

**Comment by ilkkahaataja** [comment]
Luumu-kokous (27.11.2017): Kannatamme ehdotettua muutosta. Luumu laatii määritelmän. CD-äänilevyt siirretään hierarkiassa äänitteiden alle.

**Comment by YSA-kokous** [comment]
Ehdotus:
uralevyt (äänilevyt) (?)
äänilevyt korvataan tarkemmilla: savikiekot (äänilevyt), vinyylilevyt, muuta?

**Comment by TommiViitamies** [comment]
Muusan (Luumun seuraajan) minulle delegoima määritelmäehdotus:

Polyvinyylikloridista tai sellakasta valmistettu uralevy (”vinyylilevy” tai ”savikiekko”), jolle on tallennettu ääntä analogisessa muodossa.

**Comment by jtuohini** [comment]
Väliaikahuomioksi: Muusa-ryhmä käsittelee tämän kokouksessaan 13.3.2018.

**Comment by mariaforsen** [comment]
Uralevyt antaa hyvin vähän googlessa ja tulokset ovat rakentamiseen liittyvät. Ei myöskään löydy sanastoista. Hyvin epävarmaa miten voitaisiin kääntää sellaista keksittyä termiä, ainakin ruotsin osalta. Miten englanniksi?

**Comment by jtuohini** [comment]
Terminologia ruotsiksi löytyy varmaan marc-formaatin ruotsinnoksesta (merkkipaikka 007 (S)/05), suomeksi:

05 - Uran leveys tai kaltevuus
Uran leveys äänilevyssä tai uran kaltevuus äänilieriössä.

    m - Mikroura, ohut
    Yleensä koskee 16, 33 ja 45 kierroksen levyjä.
    n - Soveltumaton
    Yleensä koskee ääninauhoja ja CD-levyjä.
    s - Karhea, standardi
    Yleensä koskee rullia ja 78 kierroksen levyjä.
    u - Tuntematon
    z - Muu
    | - Ei koodattu

**Comment by jtuohini** [comment]
Tätä on nyt veivattu yhtä kovasti kuin isoisän grammaria, joten viimeinen tiivistysyritys ennen YSA-kokousta. Lopputulos, joka sulkisi CD-äänilevyt pois tästä käsitteestä, näyttäisi tältä:
 
**äänilevyt**
Polyvinyylikloridista tai sellakasta valmistettu uralevy (puhekielessä vinyylilevy tai savikiekko), jolle on tallennettu ääntä analogisessa muodossa.
  LT  äänitteet

**Comment by mariaforsen** [comment]
Formaatin käännös ei sinänsä auta jos halutaan "uralevyt" päätermiksi, mutta viimeksi kannatettu, yllä oleva ratkaisu "äänilevyt" määritelmän kera näyttää hyvältä (sv. grammofonskivor)

"05 Spår
Avser ljudskivor och ljudcylindrar.
m Mikrospår
Normalt för 16-, 33- och 45-varvsskivor. Hit även finspåriga cylindrar (160 varv per minut / 200 spår per tum).
n Ej tillämplig
Normalt för band och CD.
s Standardspår
Normalt för 78-varvsskivor. Hit även grovspåriga cylindrar (120 varv per minut / 100 spår per tum).
u Okänd spårtyp
z Annan spårtyp"
