### ISSUE TITLE
vesperit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5632]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vesperit](http://www.yso.fi/onto/ysa/Y100202) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko jaettava? 

#### Perustelut ehdotukselle   

LCSH: Vespers & Vespers (Music). YSAssa nyt LT kirkkomusiikki, Melindassa käytetty joitakin kertoja ilmeisesti merkityksessä iltajumalanpalvelus - samoissa aineistoissa tosin myös musiikki aiheena. Mahdollista myös ottaa iltajumalanpalvelus päätermiksi, KT vesperpalvelus jne. (mahd. vesperit-termille tarkenne (sävellykset)?). 

Wikipediassa vesper tarkoittaa vain jumalanpalvelusta, musiikille ei ole omaa artikkelia. https://en.wikipedia.org/wiki/Vespers#Musical_settings 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by jtuohini** [comment]
Kannatan jakamista, kun on selvästi kaksi eri asiaa, joita kuvataan. Musiikkia käsittelevän aineiston termiksi kävisi hyvin tuo ehdotettu _vesperit (sävellykset)_.

**Comment by mirmaid** [comment]
Myös _vigiliat_, MUSA: _Katolisten kirkkojen yöjumalanpalvelus ja siinä käytettävä musiikki._ Melindassa käytetty kolme kertaa yöjumalanpalveluksesta vapaana asiasanana, seitsemän kertaa musiikista. LCSH vain Vigils (Liturgy)?

**Comment by jtuohini** [comment]
Tuon jakaminen olisi myös varmaan tarpeen. Joka tapauksessa määritelmän viite yksinomaan roomalaiskatoliseen kirkkoon on harhaanjohtava. Ja tunnetuin musiikillinen vigiliakin sattuu olemaan ortodoksisen kirkon vigiliasta tekstinsä ottava, ks. [https://en.wikipedia.org/wiki/All-Night_Vigil_(Rachmaninoff)](https://en.wikipedia.org/wiki/All-Night_Vigil_(Rachmaninoff)).

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): Kannatetaan termiä vesperit (sävellykset)

**Comment by YSA-kokous** [comment]
Toisen termin muoto seuraavaan kokoukseen.

**Comment by jtuohini** [comment]
Olisiko tämä toinen yksinkertaisesti **vesperit (jumalanpalvelus)**, LT jumalanpalvelus?

**Comment by mirmaid** [comment]
vesper (jumalanpalvelus) https://github.com/Finto-ehdotus/YSE/issues/5908?

**Comment by mirmaid** [comment]
& vigiliat (sävellykset)?

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa "vigiliat"-käsitteen muuttamista muotoon "vigiliat (sävellykset)" YSAssa.
