### ISSUE TITLE
latinalaisamerikkalainen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5633]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[latinalaisamerikkalainen musiikki](http://www.yso.fi/onto/ysa/Y96783) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Asiasana poistetaan. 

#### Perustelut ehdotukselle   

Vastaavia asiasanoja ei juurikaan ole muustakaan musiikista, ei esim. "suomalainen musiikki" tai "eurooppalainen musiikki", vaan asia ilmaistaa kahden fasetin avulla: aihe ("musiikki" tai tarkempi musiikinlaji) + paikka (tässä tapauksessa "Latinalainen Amerikka" tai tarkempi maantieteellinen asiasana). 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by LeKorsu** [comment]
Muutoin ihan kannatettava, jos ei kerran ole muitakaan "maanosamusiikkeja". On kylläkin käytetty Melindassa yli 500 kertaa.

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan termin poistoa, mutta miten hoidetaan muutokset eri tietokantoihin?
