### ISSUE TITLE
pastoraalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5634]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pastoraalit](http://www.yso.fi/onto/ysa/Y110609) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä tai jaetaan. 

#### Perustelut ehdotukselle   

Tarvetta selkiyttää mihin termillä voidaan viitata. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
MUSA: _Termillä on useita eri merkityksiä keskiaikaisesta paimenlaulusta 1800-luvun "paimentunnelmaisiin" orkesteriteoksiin._

Wikipedia: _Pastoraali (< ital. pastorale) eli paimenidylli tarkoittaa paimenrunouden aiheisiin pohjautuvaa musiikkia, näytelmiä tai kuvataidetta. Nimitys on lähtöisin latinan sanasta pastor 'paimen'. Pastoraalilla tarkoitetaan myös samoissa aihepiireissä liikkuvaa maalausta._

**Comment by mirmaid** [comment]
LCSH:ssa useita vastineita, mm. Pastoral poetry, Pastoral literature, Pastoral drama, Pastoral music (Secular), Pastoral art jne.

Melindassa lähinnä kirjallisuuden yhteydessä, muutamia kertoja myös teologiassa, vaikka YSAssa on erikseen _pastoraaliteologia, pastoraalitutkinto ja pastoraalityöt_.

**Comment by asormune** [comment]
Otavan iso musiikkitietosnakirja: "pastoraali = musiikki, jota eteläitalialaiset paimenet esittivät adventtiajan pyhiinvaellusmatkallaan Roomaan, sekä taidemusiikkisävellys, joka on saanut siitä vaikutteita. Pastoraalia käytetään myös yleisenä nimityksenä musiikista, joka jollakin tavoin liittyy kirjalliseen paimenperinteeseen." Olisiko musiikissa lupa käyttää termiä, jos sävellyksen nimi sisältää "pastoraali" ilmauksen?

**Comment by mariaforsen** [comment]
NE: konstnärligt verk som beskriver eller väcker föreställningar om lantlig (herde)idyll
BET.NYANSER: a) spec. herdedikt b) spec. äv. musikstycke av fridfull, idyllisk karaktär c) om sådan miljö, stämning e.d. i verkliga livet

Jos jaetaan niin ainakin kirjallisuus ja musiikki.

**Comment by OutiHintikka** [comment]
”Wikipedia: Pastoraali (< ital. pastorale) eli paimenidylli tarkoittaa paimenrunouden aiheisiin pohjautuvaa musiikkia, näytelmiä tai kuvataidetta.” 
-myös kertomakirjallisuutta (ks. esim. What is pastoral? / Paul Alpers.)

**Comment by jtuohini** [comment]
Musiikki kuvaavaksi asiasanaksi voisi ottaa vaikkapa muodon **pastoraalisävellykset** (KT _pastoraalit (sävellykset)_)?

**Comment by asormune** [comment]
Miten (musiikin) "pastoraalit suhtautuu muihin musiikkitermeihin, esim. "nocturnet", jotka eivät ole tarkkaan musiikin muotoa tai kokoonpanoa kuvaavia termejä (vrt. sonaatit, konsertot)? YSA:ssa  "nocturnet": "1700-luvulta alkaen nimitys sävellykselle, jossa on tavoiteltu "öistä" tunnelmaa. Nocturne on yleensä lyhyehkö, kolmiosainen ja tyyliltään lyyris-ekspressiivinen karaktäärikappale"

Jos (musiikin) pastoraalit olisi "pastoraalisävellykset", olisiko nocturnet  samaan tapaan "nocturnesävellykset"?

**Comment by jtuohini** [comment]
Nocturnet eivät vaadi "nocturnesävellykset"-tyyppistä sanamuotoa, koska ei ole muita kuin musiikillisia nocturneja. Pastoraaleja taas on muitakin kuin musiikkia, enkä ole aivan varma, että _pastoraalit (sävellykset)_ olisi yksiselitteinen t.s. että sen ei luultaisi tarkoittavan pastoraalirunoihin sävellettyjä lauluja.

**Comment by jtuohini** [comment]
Jakamisesta tässä kyse! Eli kirjallisuudelle tulisi yksi asiasana ja musiikille toinen, mikä niiden täsmällinen muoto sitten olisikin.

**Comment by TommiViitamies** [comment]
"Pastoraalit (sävellykset)" olisi kai yleisen linjan mukainen muoto. Jaakon huoli sekoittumisesta _enkä ole aivan varma, että pastoraalit (sävellykset) olisi yksiselitteinen t.s. että sen ei luultaisi tarkoittavan pastoraalirunoihin sävellettyjä lauluja_ on minusta turha, ovathan nekin "pastoraalisävellyksiä".

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): ehdotetaan termiä _pastoraalimusiikki_ ja KT _pastoraalinen musiikki_

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
YSAssa myös _pastoraalinäytelmät_ omana terminään.

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:pastoraali

Yksi mahdollisuus olisi käsitellä tätä tyylisuuntana: _pastoraali_ LT _tyylit_? Silloin voisi käyttää taiteenlajista riippumatta. Ehkä tarvitsisi tuon tyylit myös tarkenteena, jos nyt joku vielä tulkitsee tämän lyhenteeksi pastoraalitutkinnosta...

**Comment by YSA-kokous** [comment]
Muutetaan pastoraalit > pastoraali (tyylit).

pastoraalimusiikki

**Comment by mirmaid** [comment]
LT ja määritelmä pastoraalimusiikille?

**Comment by mirmaid** [comment]
Jääkö paimenrunous KÄ pastoraali (tyylit), vrt. musiikki ja näytelmät?

**Comment by YSA-kokous** [comment]
paimenrunous KÄ pastoraali (tyylit)

**Comment by AuHo22** [comment]
Rokokoo tai biedermeier ovat mielestäni tyylejä, mutta kun liikutaan genreissä, niin mielestäni emme voi ohjata niitä tyyleihin, ks. pastoraali (tyylit)
Tällä hetkellä on aikamoinen kirjo sanastojen välillä termeissä pastoraalit / pastoraali (tyylit) sekä niiden ohjaustermeissä, kävipä sitten kaunokissa/kaunossa/tai ysassa, Sen lisäksi pastoraali-alkuisia termejä käytetään myös teologisissa yhteyksissä musiikin lisäksi.
Selkeyden vuoksi ehdotan, että kaunokirjallisissa termeissä palataan taaksepäin, ja nimitetään asioita niiden oikeilla nimillään: paimenrunot, paimenromaanit, paimennäytelmät (KT pastoraalinäytelmät). 
Kirjallisuudenhistoriassa näillä on kaikilla vankka perinteensä antiikista lähtien kukoistaen jälleen renessanssissa jne. On filologeja jotka voivat näitä tutkia, ja näiden mielestäni pitäisi olla sanastossa omina termeinään.

**Comment by mirmaid** [comment]
Eli lisättäisiin paimenrunous ja paimenromaanit, jolloin pastoraali (tyylit) voisi käyttää 
a) kaikista suppeampien termien lisäksi
b) kuvataiteesta ja muista taidelajeista, joilla ei vielä ole omaa paimen/pastoraali-termiä
c) pastoraali (tyylit) poistettaisiin ja sen tilalle otettaisiin vielä ainakin pastoraali (kuvataide)

**Comment by AuHo22** [comment]
C-vaihtoehto on mielestäni taiteen tutkimuksen kannalta mielekkäin. Kuvataiteessa pastoraali, ts. paimenidylli oli hyvin suosittu esimerkiksi rokokoon aikaan ; rokokoosta voi mielestäni puhua tyylisuuntana tai taidesuuntauksena, pastoraali puolestaan ei mielestäni ole tyyli- tai taidesuuntaus.

**Comment by mirmaid** [comment]
Outi Hintikka kommentoi: 
_pastoraalit on kattokäsite - ei tyyli! Tämän alal/rinnakaisajeja (on vähän makuasia) paimenrunous, paimennäytelmät (erittäin suosittu aikoinaan), paimenromaanit, idyllit ja tästä suppeampi laji: pastoraalsiet romanssit._

**Comment by mirmaid** [comment]
Nykytilanne siis:
pastoraali (tyylit)
pastoraalimusiikki
pastoraalinäytelmät

SLM:ssä vain pastoraalimusiikki

**Comment by mirmaid** [comment]
Ehdottaisin että tässä vaiheessa korjataan monikolliset pastoraalit olemassaoleviin vaihtoehtoihin ja pohditaan pastoraali (tyylit) -käsitteen jatkokäsittelyä konversion jälkeen.

**Comment by YSA-kokous** [comment]
Korjataan monikolliset pastoraalit olemassaoleviin vaihtoehtoihin ja pohditaan _pastoraali (tyylit)_ -käsitteen jatkokäsittelyä konversion jälkeen.

**Comment by satuniininen** [comment]
Ei muita muutoksia /YSO-kokous 9.12.2019

**Comment by mirmaid** [comment]
Outi: Hierarkia voisi olla

YLÄKÄSITE pastoraalit (kirjallisuus)  
ALAKÄSITE idyllit (TheokritoS), eklogit eli paimenlaulut (Vergilius), pastoraaliset romanssit (Longos) ja pastoraalinen epiikka (Milton), pastoraalinäytelmät (Tasso).

Summa summarum: pääsemme pitkälle, jos SLM-termiksi tulee: pastoraalit (kirjallisuus)

https://en.wikipedia.org/wiki/Pastoral#Pastoral_poetry

**Comment by AuHo22** [comment]
Tällä hetkellä sanastoissa on jo idyllit, sen sijaan YSOssa paimenlaulut on kansanperinteeseen kuuluvassa merkityksessä, kun taas Vergiliuksen eklogit ovat taiderunoutta (po. eklogit terminä) https://fi.wikipedia.org/wiki/Eklogi
Onko pastoraalinen romanssi tarpeellinen terminä vai voitaisiinko ohjata pastoraaliseen epiikkaan? 
https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:pastoraali
YSOssa romanssit (kirjallisuudenhistoria), SLM romanssit (musiikki)
Kattaako pastoraalinen epiikka siis myös paimenromaanit, eli siitä myös ohjaus? Pastoraaliepiikka terminä hyvä, koska se ei erottele runoelmia ja romaaneja toisistaan?

**Comment by AuHo22** [comment]
LCSH: Pastoral poetry -> DNB: Hirtendichtung ST Ekloge / Hirtenlied / Pastorelle / Schäferroman / Schäferspiel
https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4069731-9

**Comment by mirmaid** [comment]
Käytettävä termi: pastoraalit (kirjallisuus)
Ohjaustermit: paimennäytelmät, paimenromaanit, paimenrunot
Alakäsite: idyllit

Ehdottaja: KAUNO-kokous

**Comment by mirmaid** [comment]
Huom. YSO eroaa

**Comment by AuHo22** [comment]
YSOssa voisi olla myös: pastoraalit (kirjallisuus) KT paimenlaulut (paimenrunous) / paimenrunous- luokka 87

pastoraali (tyylit) -luokka 90

**Comment by mariaforsen** [comment]
SLM:ssä on nyt vain pastoraalimusiikki, riittääkö sen lisäksi pastoraalit (kirjallisuus)?

**Comment by mirmaid** [comment]
Hyväksytään KAUNOn ehdotus ja lisäksi Aulin ehdottama ohjaustermi. RT idyllit.

**Comment by mirmaid** [comment]
YSO: https://github.com/Finto-ehdotus/YSE/issues/5634#issuecomment-1311593957

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi _pastoraalit (kirjallisuus)_ käsitteille _pastoraali (tyylit)_ ja _pastoraalinäytelmät_.
