### ISSUE TITLE
marssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5635]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[marssit](http://www.yso.fi/onto/ysa/Y103428) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "marssit (sävellykset)". 

#### Perustelut ehdotukselle   

Asiasanaa näyttää käytetyn aika huolettomasti kuvaamaan myös erilaisia tilaisuuksia, jossa ihmiset marssivatt, vaikka kyse on musiikkitermistä. Täsmenne tekisi aiempaa selvemmäksi, mihin termi viittaa.

Oma asiansa on miettiä, miten vappumarssin, Jeesus-marssin tai sotilasmarssin kaltaiset joukolla liikkumisen tapa pitäisi kuvailla yleisellä tasolla eli muutenkin kuin tapahtuman nimellä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by LeKorsu** [comment]
Ysassa on paraatit ja kulkueet, voisiko tuon joukolla liikkumisen ohjata näihin termeihin?

**Comment by EsaMPKK** [comment]
Vanha kunnon Oinosen Sotilaskielen sanakirja:

"_marssi_, joukon omilla liikuntavälineillään suorittama siirtyminen: m. ilman tahtia, tahti-, paraati-, etenemis-, vetäytymis-, sivusta-, maantie-, maasto-, matka-, vartio-, suru-, sota-, pika-, yö-, päivä-, jalka-, pyörä-, auto-, hiihto-, heitto- jne m. Vrt. sotilasm."

"_sotilasmarssi_, iskevärytminen sotaväen tarkoituksiin sävelletty marssi."

**Comment by asormune** [comment]
Vappumarssi, rauhanmarssi jne. ovat ennemminkin mielenosoituksia. "Marssirytmissä" niissä ei ainakaan järjestelmällisesti liikuta.

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan

**Comment by EsaMPKK** [comment]
Sotaväen siirtymisen merkityksessä esim. marssit (siirrot)
