### ISSUE TITLE
polarisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5636]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[polarisaatio](http://www.yso.fi/onto/ysa/Y103973) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava (?) 

#### Perustelut ehdotukselle   

Käytetään nykyään paljon yhteiskuntatieteissä, myös luonnontieteissä useampia merkityksiä. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Polarization

LCSH:ssa Polarization (Social sciences) - tämä tarkkuus riittää varmasti myös meillä jos jaetaan, vaikka Wikipedia eritteleekin enemmän.

**Comment by mirmaid** [comment]
Lisäksi ainakin polarisaatio (aaltoliike) ja dielektrinen polarisaatio, mahd. solun polaarisuus, muuta?

**Comment by mariaforsen** [comment]
Sv. polarisering (samhälle), polarisation (vågrörelse?)
SAO: polarisation (optik) (LCSH: Polarization (Light))

**Comment by mirmaid** [comment]
_Polarisaatio (aaltoliike)_ kattaisi myös valon polarisaation. _Optiikka_ on myös mahdollinen tarkenne, vaikka polarisaatio ei wikipedian mukaan ole rajattu (näkyvään) valoon tai edes sähkömagneettiseen säteilyyn.

Voidaan myös siivota ensin joukosta yhteiskuntatieteet.

**Comment by YSA-kokous** [comment]
polarisaatio (yhteiskuntatieteet)

**Comment by satuniininen** [comment]
Ilman osakohteita _polarisaatio_ esiintyy Melindassa 55 kertaa. Suurin osa käsittelee polarisaatiota joko optiikan tai sähkömagnetiikan yhteydessä. Yksi väitöskirja käsittelee solun polarisaatiota.

Kannatan muotoa _polarisaatio (aaltoliike)_
Riittäisikö lääketieteen kontekstiin _solut + erilaistuminen_?

**Comment by YSA-kokous** [comment]
polarisaatio (aaltoliike)
