### ISSUE TITLE
koheesio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5637]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koheesio](http://www.yso.fi/onto/ysa/Y109369) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Rajataan kemiaan ja lisätään tarkenne. 

#### Perustelut ehdotukselle   

YSAssa on erikseen sosiaalinen koheesio sosiologian ja sidoksisuus kielitieteen yhteydessä käytettäväksi. Tarvitaan varmaankin lisäksi aluepolitiikan yhteydessä, nyt koheesiopolitiikka KÄ aluepolitiikka mutta kuvailussa tarve myös koheesio-aspektin ilmaisemiseen. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Koheesiopolitiikka=sammanhållningspolitik

**Comment by mirmaid** [comment]
Otetaan _koheesio (kemia)_, korjataan koheesio (kielitiede) > _sidoksisuus_ ja koheesio (sosiologia) > _sosiaalinen koheesio_ ja katsotaan mitä jää jäljelle?

**Comment by ilona-x** [comment]
Korjattu Melindaan. Jäljelle jäi n. 40 viitettä, joista suurin osa käsittelee EU:n koheesiota/koheesiopolitiikkaa.

YSA ohjaa nyt koheesiopolitiikka -> aluepolitiikka.

"Euroopan unionin alue- ja rakennepolitiikalla (koheesiopolitiikalla) lisätään jäsenvaltioiden taloudellista ja sosiaalista yhteenkuuluvuutta sekä vähennetään alueiden välisiä kehityseroja."
Lähde: http://tem.fi/eu-alue-ja-rakennepolitiikka

Riittäisikö kuvailussa esim. seuraavat termit:
aluepolitiikka
rakennepolitiikka
yhteenkuuluvuus
yhtenäisyys

**Comment by YSA-kokous** [comment]
koheesiopolitiikka KÄ aluepolitiikka, rakennepolitiikka
