### ISSUE TITLE
polkupyörälähetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5638]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

polkupyörälähetit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

What goes around : a London cycle courier's story / Emily Chappell 

#### Perustelut ehdotukselle   

Tarvetta. 

**Ehdottajan nimi:** Kirsi Siika-Aho 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** marjut.puominen@hel.fi **Termiehdotus Fintossa:** [polkupyörälähetit](http://finto.fi/yse/fi/page/Y505638)

**Comment by mirmaid** [comment]
Kaksi kertaa Melindassa fiktiossa.

YSAssa on _lähetit_, jota myös käytetty vain fiktiossa.

**Comment by mariaforsen** [comment]
Sv. cykelbud ET cykelkurirer

**Comment by satuniininen** [comment]
Kannatan ottamista sanastoon. Ilmeisesti kasvava ammttikunta, varmaankin Ylellä ainakin tarvetta? 

LCSH: Bicycle messengers KT bicycle couriers http://id.loc.gov/authorities/subjects/sh00006543.html
