### ISSUE TITLE
diffuusio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5639]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[diffuusio](http://www.yso.fi/onto/ysa/Y115979) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan määritelmää tai jaetaan. 

#### Perustelut ehdotukselle   

Sanalla on useita merkityksiä. 1) Molekyylien lämpöliikkeestä johtuva toistensa kanssa kosketuksissa olevien aineiden vähittäinen sekoittuminen. 2) Sosiologiassa ryhmän kulttuuripiirteiden siirtyminen toiselle ryhmälle muuttoliikkeen tms. yhteydessä, jolloin kulttuuriltaan erilaiset ryhmät joutuvat toistensa kanssa kosketuksiin. 3) Taloustieteessä fuusion vastakohta, yhtiön paloittelu kahdeksi tai useammaksi osakeyhtiöksi. 4) Diffundoituminen, leviäminen, sekaantuminen, läpitihkuminen. 5) Kemiantekniikan erotusprosessi, jossa materiaalia siirtyy faasista toiseen 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Aikaisemmin ollut YSOssa jaettu, jako purettu, ei määritelmää. 

LCSH:ssa Diffusion, Culture diffusion, Language spread, Diffusion of innovations jne. 

Diffuusio voidaan nähdä samana käsitteenä eri tieteenaloilla: https://en.wikipedia.org/wiki/Diffusion#Diffusion_in_the_context_of_different_disciplines. Erityisesti yritysjärjestelynä kuitenkin melko erityyppinen, vrt. _fuusiot (yritysjärjestelyt)_.

Usein _leviäminen_ ja _yleistyminen_ sopisivat yhtä hyvin, esim. https://jyx.jyu.fi/dspace/handle/123456789/50705

**Comment by mariaforsen** [comment]
KS: 
1. kem., fys. lämpöliikkeestä johtuva ainehiukkasten sekoittuminen toisiinsa.
2. sosiol. kulttuuripiirteiden siirtyminen ryhmältä toiselle. 

SAO: diffusion (kemia/fysiikka-merkityksessä)
Ruotsiksi ei kovin yleinen yhteiskuntatieteellisenä, vaan esim. "spridning", "bli vanligare" käytettävissä niissä tapauksissa (SAOL, SO, NE)

Riittäisikö jos ryhminä olisi kemia ja fysiikka?

**Comment by krinay** [comment]
Diffuusio on käyttökelpoinen ja tarpeellinen termi myös antropologisen ja folkloristisen aineiston kuvailussa (ryhmä 50). (Sitä on käytetty ainakin KULA-terminä; Helkassa usein 653-kentässä, johon erikoissanastojen termit harmillisesti siirrettiin jossakin konversiossa). Määritelmä 2 sopii näillekin aloille. Vrt. Tieteen termipankki (Folkloristiikka): "kulttuuriaineksen tai -kompleksin leviäminen yhteisöstä tai kulttuurista toiseen tai seudulta toiselle"; Jargon: kulttuuriantropologian oppisanasto: "kulttuurilainojen ja -piirteiden leviäminen kulttuurista toiseen maantieteellisten ja historiallisten kosketusten, esim. muuttoliikkeiden, kaupankäynnin ja sotien kautta."

**Comment by tpalonen** [comment]
Komppaan krinaytä eli en kannata rajaamista kemiaan ja fysiikkaan. Diffuusio on perustavaa laatua oleva käsite kulttuurien tutkimuksessa eikä sille löydy mitään järkevää korvaajaa sanastosta. Alan taipua käsitteen jakamisen puolelle MOTin merkityserojen innoittamana. Tuollainenhan se jako YSOssa olikin alunperin. 
Vrt. esim.
Informaation diffuusion merkitys vaikuttavuuden muodostumiseen Twitterissä / Miika Reinikainen.
Cultures and disasters : understanding cultural framings in disaster risk reduction / edited by Fred Krüger.

**Comment by tpalonen** [comment]
Kannatan edelleen käsitejakoa. YSOn aiempi käsitejako oli: diffuusio (luonnontieteelliset ilmiöt) ja diffuusio (yhteiskunnalliset ilmiöt). YSOssa ei kuitenkaan tällä hetkellä ole käsitettä luonnontieteelliset ilmiöt. Ehdotan sulkutarkenteen nimeämistä yläkäsitteen mukaisesti, jolloin lopputulos olisi jotakin tämän kaltaista:

diffuusio (fysikaaliset ilmiöt/tapahtumat)
diffuusio (yhteiskunnalliset ilmiöt/tapahtumat)

Itse olen kallellani tapahtumapuolelle, mitä hierarkisointiin tulee.

**Comment by krinay** [comment]
(Kulttuuriset ilmiöt tuntuisi jotenkin osuvammalta tarkenteelta, yhteiskunnallisessa kun on vähän turhan järjestäytynyt konnotaatio. Mutta kulttuurisia ilmiöitä ei ole taidettu käyttää tarkenteena, vaikka se on hierarkisoivana käsitteenä YSOssa. Ehkä tämä on sitä paitsi vain mielipideasia, mutua.)

**Comment by tpalonen** [comment]
Kulttuurinen-sanan käyttöä on YSOssa pyritty korvaamaan yhteiskunnallinen-sanalla, koska ovat pahasti päällekkäiset. Hierarkisoivissa käsitteissä _kulttuurinen_ viittasi YSOssa aikoinaan lähinnä taiteeseen ja taiteisiin, mutta tästä on nyttemmin luovuttu.

**Comment by mirmaid** [comment]
_Diffusion is the net movement of anything (for example, atom, ions, molecules) from a region of higher concentration to a region of lower concentration. Diffusion is driven by a gradient in concentration._

_The concept of diffusion is widely used in many fields, including physics (particle diffusion), chemistry, biology, sociology, economics, and finance (diffusion of people, ideas, and price values). The central idea of diffusion, however, is common to all of these: an object (for example, atom, idea, etc.) undergoing diffusion spreads out from a point or location at which there is a higher concentration of that object._ https://en.wikipedia.org/wiki/Diffusion

En välttämättä vastusta jakoa, mutta jos halutaan jakaa vain kahteen, jaon on oltava toisaalta hyvin selkeärajainen, toisaalta kaikki käyttötapaukset sisällyttävä.

**Comment by krinay** [comment]
Olisiko siis mahdollista jättää tilanne ennalleen? YSOssahan ei ole määritelmää ja ryhmänä on 00. Jos lisätään ryhmiä, pitäisi varmaan lisätä aika monta, mm. 07, 09, 50, 60 ja muitakin.

**Comment by mirmaid** [comment]
Jos jaetaan, _diffuusio (fysikaaliset ilmiöt)_ ja _diffuusio (yhteiskunnalliset ilmiöt)_ eivät sovellu:
- matematiikkaan
- yritysjärjestelyihin (mahdollinen esim. diffuusio (yritysjärjestelyt) KÄ yrityksen jakautuminen

_Diffuusio (yhteiskunnalliset ilmiöt)_ tuntuu melko päällekkäiseltä _leviäminen_-käsitteen kanssa. Tavallisin käyttötapaus on innovaation diffuusio, josta on kuvailussa käytetty runsaasti myös yhdistelmää _innovaatiot + leviäminen_.

**Comment by FinMeSHienPaimentaja** [comment]
Luonnontieteellistä käytöstä sen verran, että käytännössä käytetään nimenomaan vakiintunutta sanaa "diffuusio" esim. molekyylien liikkeestä laimeampaan, ei "leviäminen" yms. (vaikka esim. "leviäminen" olisikin vierasperäistä "diffuusiota" suomenkielisempi).

**Comment by mariaforsen** [comment]
SAOssa diffusion on vain luonnontieteellinen, sen sijaan SAOsta löytyy kyllä myös "innovationsspridning". Ylipäätään ruotsiksi diffusion on kyllä ensisijaisesti luonnontieteellinen.

**Comment by mirmaid** [comment]
Pitäisikö lisätä tarkenne _diffuusio (fysikaaliset ilmiöt)_ ja korjata ne viitteet, joihin se sopii, ja tutkia sen jälkeen, riittääkö jäljelle jääviin _leviäminen_ (tai mahdollisesti jokin muu tarkempi käsite)?

**Comment by krinay** [comment]
Tulisiko sotkua, jos olisi lisäksi ohjaustermi diffuusio (yhteiskunnalliset ilmiöt) KÄ leviäminen?

**Comment by mariaforsen** [comment]
Leviäminen on ryhmässä 00 Yleistermit 16 Kasvitiede 17 Eläintiede. Pitäisikö lisätä ryhmiä?

**Comment by YSO-kokous** [comment]
### Päätökset
diffuusio (fysikaaliset ilmiöt)  -- ryhmäksi vain 00 Yleiskäsitteet, poistetaan ryhmät 16,17
diffuusio (yhteiskunnalliset ilmiöt) KÄ leviäminen
