### ISSUE TITLE
soittajat [omaksi käsitteekseen]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5640]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soittajat [omaksi käsitteekseen] 

#### Ehdotettu termi ruotsiksi   

instrumentalister [omaksi käsitteekseen] 

#### Ehdotettu termi englanniksi   

instrumentalists 

#### Vaihtoehtoiset termit ja ilmaisut   

instrumentalistit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muusikot](http://www.yso.fi/onto/yso/p1644) 

#### Alakäsitteet (RT)   

[alttoviulistit](http://www.yso.fi/onto/yso/p26948) 
[viulistit](http://www.yso.fi/onto/yso/p22505) 
[cembalistit](http://www.yso.fi/onto/yso/p25916) 
[fagotistit](http://www.yso.fi/onto/yso/p18404) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh94009600> 

#### Tarkoitusta täsmentävä selite   

Muusikko, joka esittää musiikkia yhtä tai useampaa soitinta soittamalla. 

#### Perustelut ehdotukselle   

Laulajille on oma terminsä, mutta soittajille ei. Toisaalta sanastossa on omat terminsä muille saman jaon puitteissa: laulumusiikki ~ soitinmusiikki, laulaminen ~ soittaminen, lauluääni ~ soittimet. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [soittajat [omaksi käsitteekseen]](http://finto.fi/yse/fi/page/Y505640)

**Comment by pauliinaisomaki** [comment]
Kannatan.

**Comment by LeKorsu** [comment]
Miksei olemassaoleva muusikot riitä? Onko kyse ammattilaisuus/amatöörieroista. Ammattilainen on muusikko, mutta kuka tahansa, joka osaa soittaa, on soittaja?

**Comment by asormune** [comment]
Laulaja on myös "muusikko". Kun keskiasteella suoritetaan "musiikkialan perustutkinto" niin "pääsoittimena" voi olla laulu tai jokin soitin (instrumentti).

**Comment by TommiViitamies** [comment]
Muusikot vs. soittajat: kyse ei liene "ammattilaisuuden" asteesta. On mm. "amatöörimuusikoita".

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): Kannatetaan ehdotusta
