### ISSUE TITLE
kauppaluotto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5641]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kauppaluotto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Tarkoitusta täsmentävä selite   

"Kauppaluottoihin kirjataan vientisaamiset ja -ennakot sekä tuontivelat ja -ennakot. Kauppaluottoja ovat tavara- ja palvelukauppaan liittyvät kauppaluotot, kuten tilivelat, toimitusluotot (ulkomaisen myyjän myöntämät maksuaika), ostovelat sekä ulkomaiselta ostajalta saadut ennakot tekeillä olevista tai tulevista suorituksista." Wikipedia 27.10.17: https://fi.wikipedia.org/wiki/Maksutase 

#### Perustelut ehdotukselle   

Väitöskirjan tekijä käyttää englanninkielisen väitöskirjansa suomenkielisessä abstraktissa ja on itse määritellyt suomenkieliseksi asiasanaksi työlleen. Väitöstilaisuus tulossa 17.11.17, painettu väitöskirja kuvailussa, ei vielä verkkoversiota. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cross-country differences in trade credit / Marku Mättö 

**Ehdottajan nimi:** Katja Hyvärinen 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** katja.hyvarinen@uef.fi **Termiehdotus Fintossa:** [kauppaluotto](http://finto.fi/yse/fi/page/Y505641)

**Comment by mirmaid** [comment]
YSAssa on _luottokauppa_

**Comment by mariaforsen** [comment]
Sv. handelskredit

**Comment by LeKorsu** [comment]
Jos otetaan, pitäisikö laittaa sulkutarkenne, jottei sekoitu luottokauppaan: kauppaluotto (kirjanpito) tai kauppaluotto (laskentatoimi)?

**Comment by satuniininen** [comment]
LCSH: commercial credit http://id.loc.gov/authorities/subjects/sh86005993.html

**Comment by mirmaid** [comment]
_Luotot_ alakäsitteineen monikossa YSAssa.
