### ISSUE TITLE
käyttöpääoma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5642]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

käyttöpääoma 

#### Ehdotettu termi englanniksi   

working capital (?) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/K%C3%A4ytt%C3%B6p%C3%A4%C3%A4oma 

#### Perustelut ehdotukselle   

Samat kuin termiehdotuksessa "kauppaluotto" 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cross-country differences in trade credit / Markus Mättö 

**Ehdottajan nimi:** Katja Hyvärinen 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** katja.hyvarinen@uef.fi **Termiehdotus Fintossa:** [käyttöpääoma](http://finto.fi/yse/fi/page/Y505642)

**Comment by mirmaid** [comment]
JUPO ja LIITO -ontologioissa. 15 viitettä Melindassa.

http://id.loc.gov/authorities/subjects/sh85148174

Wikipedia: _Käyttöpääoma on se osa yrityksen pääomasta, joka tarvitaan päivittäisen toiminnan kattamiseen._

**Comment by mariaforsen** [comment]
Sv. rörelsekapital ET driftkapital, driftskapital
