### ISSUE TITLE
hammashuoltajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5643]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hammashuoltajat](http://www.yso.fi/onto/ysa/Y106019) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄYTÄ suuhygienistit 

#### Perustelut ehdotukselle   

Huomautus nyt: Vuodesta 2005 alkaen käytetty nimitystä suuhygienistit. Eli nykykäytäntöjen mukaan pääterminä voisi olla suuhygienistit ja korvattuna terminä hammashuoltaja. 
Ruotsiksi ongelmia -joko munhygienister (Suomessa käytetty) tai tandhygienister (Ruotsissa käytetty) pitäisi olla päätermi, ja toinen korvattuna. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Ruotsin kannalta yhdistäminen olisi hyvä ratkaisu, suomeksi kuulostaa vähän anakronistiselta kuvailla termillä _suuhygienistit_ sellaisia aineistoja kuin _Terveydenhuoltoalan opiskelijoiden tietoja, käsityksiä ja asenteita hammashuoltajan koulutuksesta ja ammatista_ (toki käytettävissä myös termi _hammashuolto_). Sanastossa lisäksi _hammashoitajat_, joka on kuitenkin eri ammattiryhmä.

**Comment by mirmaid** [comment]
Ehkä tässä voisi kuitenkin vähän väkivaltaisesti yhdistää hammashuoltajat KÄ _suuhygienistit_, ja lisätä/vaihtaa vanhempaan aineistoon termin _hammashuolto_?
