### ISSUE TITLE
rautatieasemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5644]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rautatieasemat](http://www.yso.fi/onto/ysa/Y100859) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

(1) Lisätään ryhmä 91 ja KT-muoto "asemarakennukset", tai (2) annetaan termin olla nykyisellään ja otetaan erillinen asiasana kuvaamaan asemarakennuksia, esim. "asemarakennukset" (KT "rautatieasemat (rakennukset)") tms. Asiasanan LT-suhteinen "asemat" joka tapauksessa kuuluu ryhmään 91, joten ehkä "asemarakennukset" pitäisi laittaa KT-muodoksi sille. 

#### Perustelut ehdotukselle   

Nykyisen asiasanan käyttäminen arkkitehtuurikirjassa askarruttaa: viittaako termi yksinomaan rautatieliikennepaikkaan vai sittenkin myös sellaisella sijaitsevaan rakennukseen. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Asemarakennukset käytetty 14 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. stationsbyggnader

**Comment by YSA-kokous** [comment]
Otetaan asemarakennukset.
