### ISSUE TITLE
Tuovilan museosilta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5645]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tuovilan museosilta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.doria.fi/handle/10024/96791 

#### Perustelut ehdotukselle   

Museosiltoja on auktorisoitu 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [Tuovilan museosilta](http://finto.fi/yse/fi/page/Y505645)

**Comment by mariaforsen** [comment]
Sv. Toby stenbro ET Toby museibro
