### ISSUE TITLE
Valemedia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5647]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Valemedia 

#### Vaihtoehtoiset termit ja ilmaisut   

Vastamedia, Vaihtoehtomedia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Paljon esillä. Kotuksen määritelmä: "mielipiteisiin perustuvaa, vastoin hyvää journalistista tapaa toimiva viestintäkanava, jota voidaan käyttää informaatiosodan välineenä. Tällaisten kanavien ylläpitäjät ja tukijat käyttävät niistä nimityksiä vastamedia ja vaihtoehtomedia." 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Saara Jantunen: Infosota 

**Ehdottajan nimi:** Jari Heikkinen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** jari.heikkinen@helsinki.fi **Termiehdotus Fintossa:** [Valemedia](http://finto.fi/yse/fi/page/Y505647)

**Comment by mirmaid** [comment]
https://www.kotus.fi/sanakirjat/kielitoimiston_sanakirja/uudet_sanat/vuoden_sanapoiminnot/sanapoimintoja_2016

https://fi.wikipedia.org/wiki/Valemedia

Melindassa kerran vaihtoehtomedia, mutta ei taida olla tässä negatiivisessa merkityksessä.

**Comment by mariaforsen** [comment]
Sv. fuskmedier ET falska medier, fejkmedia, fejkmedier, lögnmedia, trollmedier

**Comment by YSA-kokous** [comment]
valemedia

**Comment by ilona-x** [comment]
Pitäisikö tehdä ohjaustermi vastamedia-termistä, jotta tämä termi löytyisi helpommin? Mutta vaatisiko vastamedia-termi tarkenteen?

https://fi.wikipedia.org/wiki/Vastamedia

Esimerkiksi tätä aihetta käsittelevässä väitöskirjassa on käytetty termiä vastamedia https://urn.fi/URN:ISBN:978-952-03-2724-8

Wikipediassa myös sivu [valemedia](https://fi.wikipedia.org/wiki/Valemedia), mutta merkitys on eri kuin tällä YSO-termillä. HUOM. valemedia on nyt linkattu virheellisesti tämän wikidata-vastineeseen.

--

LCSHssa [Alternative mass media](http://id.loc.gov/authorities/subjects/sh2002001142), joka on linkattu Wikidataan [alternative media ](https://www.wikidata.org/wiki/Q192855), jonka suomenkielisenä vastineena on vastamedia

**Comment by tpalonen** [comment]
Ainakin nykyinen Wikidata-linkki on poistettava. Voisiko ohjaustermi olla _vastamedia (valemedia)_?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään yllä esitetty ehdotus.

**Comment by mariaforsen** [comment]
Sv. HT alternativa medier, alternativmedier, motmedier
