### ISSUE TITLE
valeuutinen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5648]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valeuutinen 

#### Assosiatiiviset (RT)   

[disinformaatio](http://www.yso.fi/onto/yso/p29444) 
[informaatiosodankäynti](http://www.yso.fi/onto/yso/p8874) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Paljon esillä. Liittyy toiseen ehdotukseen "valemedia". Kotuksen määritelmä: "valemedian tuottama ja välittämä uutiselta vaikuttava teksti tm. kuvaus". Wikipedian määritelmä: "harhautustarkoituksessa tehty teksti tai viesti, joka matkii ulkoisesti journalismia, mutta ei ole sitä. Valeuutinen on eräs huijauksen laji tai tahallaan levitettyä väärää tietoa, jota välitetään perinteisten viestinten tai sosiaalisen median kautta." 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Saara Jantunen: Infosota 

**Ehdottajan nimi:** Jari Heikkinen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** jari.heikkinen@helsinki.fi **Termiehdotus Fintossa:** [valeuutinen](http://finto.fi/yse/fi/page/Y505648)

**Comment by mirmaid** [comment]
Ei Melindassa

**Comment by mariaforsen** [comment]
Sv. falska nyheter ET fejknyheter,  fusknyheter, osanna nyheter

**Comment by LeKorsu** [comment]
Kannatan (monikossa).

**Comment by YSA-kokous** [comment]
valeuutiset
