### ISSUE TITLE
sähkösaostus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5649]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sähkösaostus](http://www.yso.fi/onto/ysa/Y191934) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Sähkösaostuksella voidaan viitata jätevesien puhdistuksessa tai metallien pinnoituksessa käytettävään menetelmään.

Kielivastineet menevät seuraavasti:
sähkösaostus (vedenpuhdistus) = elektrokoagulation/elektroflockning; electrocoagulation
sähkösaostus (pintakäsittely) = elektrolytisk utfällning; electrodeposition/electroplating 

#### Ehdottaja   

Satu Niininen / Yso-kokous 

#### Ehdotettu muutos   

Käsitteellä on kaksi merkitystä, joten se pitäisi jakaa ja erotella sulkutarkeiden avulla, esim.
sähkösaostus (vedenpuhdistus)
sähkösaostus (pintakäsittely) 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
Sähkösaostus (pintakäsittely) voisi olla myös _sähköpinnoitus_?

**Comment by mariaforsen** [comment]
Mahdollisesti elektrolytisk ytbeläggning siinä tapauksessa?

**Comment by YSA-kokous** [comment]
sähkösaostus (vedenpuhdistus)
sähköpinnoitus

**Comment by mariaforsen** [comment]
Sv. 
-elektrokoagulering (vattenrening) ET elektroflockning
-elektrolytisk ytbehandling, elektrolytisk ytbeläggning, elbeläggning, elektrodeposition, elmetallisering, elektroplätering, elektrolytisk utfällning
