### ISSUE TITLE
varhaiskasvatussuunnitelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5650]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

varhaiskasvatussuunnitelmat 

#### Perustelut ehdotukselle   

Varsin vakiintunut käsite varhaiskasvatuksessa. Aihetta käsittelevää kirjallisuutta on paljon. yksi termi on kuvaavampi kuin yhdistelmä varhaiskasvatus ja suunnitelmat. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

mm. Varhaiskatsomus katsomusten keskellä 

**Ehdottajan nimi:** Henna Paajala 
**Ehdottajan sähköpostiosoite:** henna.paajala@oamk.fi **Termiehdotus Fintossa:** [varhaiskasvatussuunnitelmat](http://finto.fi/yse/fi/page/Y505650)

**Comment by mirmaid** [comment]
YSAssa on _opetussuunnitelmat_ ja _HOPS_, tässä vastaavanlainen merkityskenttä?

http://www.oph.fi/saadokset_ja_ohjeet/ohjeita_koulutuksen_jarjestamiseen/varhaiskasvatuksen_jarjestaminen/lapsen_vasu
http://www.oph.fi/saadokset_ja_ohjeet/opetussuunnitelmien_ja_tutkintojen_perusteet/varhaiskasvatus/103/0/paikalliset_varhaiskasvatussuunnitelmat_otetaan_kayttoon_koko_maassa

**Comment by mariaforsen** [comment]
Sv. planer för småbarnspedagogik ET planer för småbarnsfostran
