### ISSUE TITLE
kaivosvesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5651]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaivosvesi 

#### Ehdotettu termi englanniksi   

mine water 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vesi](http://www.yso.fi/onto/yso/p3792) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85085545> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[32 Kaivosteollisuus. Kaivannaisteollisuus](http://www.yso.fi/onto/yso/p26567) 

#### Tarkoitusta täsmentävä selite   

Hankala löytää täsmällistä määritelmää, mutta joka tapauksessa kyseessä on laajempi käsite kuin kaivosten tuottamat jätevedet. Esim. miningfacts.orgin mukaan:

Mine water: refers to any surface or groundwater present at the mine site
Mining water: water which has come into contact with any mine workings
Lähde: http://www.miningfacts.org/Environment/What-are-the-water-quality-concerns-at-mines-/

Kongressista lisää täällä:
https://www.lut.fi/uutiset/-/asset_publisher/h33vOeufOQWn/content/maailman-suurin-kaivosvesikongressi-suomeen-kesalla-2017

Melinda 0, Google 2 480 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

13th international Mine Water Association Congress : Mine water & circular economy / Editors: Christian Wolkersdorfer, Lotta Sartz, Mika Sillanpää, Antti Häkkinen 

**Ehdottajan nimi:** Satu Niininen 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** satu.niininen@helsinki.fi **Termiehdotus Fintossa:** [kaivosvesi](http://finto.fi/yse/fi/page/Y505651)

**Comment by mariaforsen** [comment]
Sv. gruvvatten
