### ISSUE TITLE
country-dancet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5652]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[country-dancet](http://www.yso.fi/onto/ysa/Y108496) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään country-dancet ja kontratanssit (tanssit) 

#### Perustelut ehdotukselle   

Onko käsitteiden välillä niin merkittävää eroa, että ne on perustelua säilyttää erillisinä? Molemmat englanniksi country dances. 
vrt. LCSH: Country dancing KT Contra dancing, Contradancing, Longways dancing (Country dancing)

Huom. ei saa sekoittua käsitteeseen rivitanssit KT countrytanssit 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by ksornova** [comment]
Groven määritelmät menevät näin: 
**Country dance** = YSA country-dancet, MUSA country-dancet (tanssit)
An English dance widely popular in the 17th century. It spread to the Continent, particularly France, where it became known as the Contredanse.

**Contredanse** = kontrantanssit (tanssit)
The 18th-century French contredanse, performed by eight dancers in a square formation, was the French version of the popular English country dance, a progressive longways dance for an unlimited number of couples. The contredanse was exported back to England in the late 18th-century, where it was known as a “cotillion,” which later became the quadrille.
= LCSH: country dancing (http://id.loc.gov/authorities/subjects/sh85033454)
Earlier Established Forms: Country-dance 

Ihan vain lisäyksenä, LCSH:ssa (ja meillä) erikseen termi sävellyksille/musiikille: Country-dances (Music) = kontratanssit (sävellykset)
Here are entered collections of musical compositions containing country-dances of various types. Collections of country-dances of a single type, and individual dances, are entered under the heading for the type.

**Comment by satuniininen** [comment]
OK, eli ymmärsinkö siis oikein, että LCSH-linkitys tulisi vain kontratansseille?

**Comment by jtuohini** [comment]
LCSH-linkitys rivitanssille (countrytanssille) olisi [Line dancing](http://id.loc.gov/authorities/subjects/sh93004101).

Vertaa myös LCC-luokitus:
 
**GV1763–1767  Square dances. Quadrilles. Country dances**.  _By region or country see GV1621–1728_
  GV1763  General works
  GV1767  Call books.  _Special dances see GV1796.A–Z_
**GV1768  Line dances**

**Comment by satuniininen** [comment]
Rivitansseilla on jo kyseinen siltaus. Tarkoitin kysyä, että sillataanko LCSH:n country dancing Yson kontratanssit-käsitteeseen, mutta ei country-dancet-käsitteeseen?

**Comment by jtuohini** [comment]
LCSH:n **Country dancing** = Ysan **country-dancet** ja **kontratanssit (tanssit)**
LCSH:n yhdelle termille on meillä siis kaksi vastinetta (tehty ero englantilaisten "maalaistanssien" ja niistä jalostettujen tanssien välille)
