### ISSUE TITLE
kulmakarvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5655]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kulmakarvat 

#### Vaihtoehtoiset termit ja ilmaisut   

kulmat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

julkaisun pääteema 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kauniit kulmat 978-952-7196-28-1 

**Ehdottajan nimi:** Kaija Karjalainen 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** kaija.karjalainen@btj.fi **Termiehdotus Fintossa:** [kulmakarvat](http://finto.fi/yse/fi/page/Y505655)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh85046698

Voisi varmaan ottaa samalla kertaa myös silmäripset, http://id.loc.gov/authorities/subjects/sh85046703

Molemmat löytyvät myös FinMeSHistä.

**Comment by mariaforsen** [comment]
Sv. ögonbryn, ögonfransar
