### ISSUE TITLE
taksiliikenne

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5656]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taksiliikenne 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-314-333-3 

#### Perustelut ehdotukselle   

Tämä on ollut jonkin verran jo käytössä Melindassa. 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [taksiliikenne](http://finto.fi/yse/fi/page/Y505656)

**Comment by mirmaid** [comment]
JUHO ja JUPO -ontologioissa. 13 viitettä Melindassa.

YSAssa vain _taksit_ ja _taksinkuljettajat_

**Comment by LeKorsu** [comment]
Kannatan. Kun kerran on linja-autoliikennekin. Ja kun taksiliikenne vapautuu lakimuutoksen myötä, uskon, että kirjoittelukin lisääntyy.

**Comment by mariaforsen** [comment]
Sv. taxitrafik
