### ISSUE TITLE
yhteisliikenne

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5657]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yhteisliikenne 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-314-333-3 

#### Perustelut ehdotukselle   

Yhteisliikenne tarkoittaa sitä että tyhjälle taksiasemalle saa aina jäädä odottamaan asiakasta. Lisäksi erittäin vilkkaina aikoina usein toteutetaan täydellinen yhteisliikenne, jolloin kaikki saavat ajaa kaikkialta. http://taksari.vapaavuoro.uusisuomi.fi/viihde/132988-taksislangia En löytänyt parempaa lähdettä, mutta tuosta tarkoitus ainakin selviää. 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [yhteisliikenne](http://finto.fi/yse/fi/page/Y505657)

**Comment by mirmaid** [comment]
Vaikka tällä useimmiten tarkoitetaan taksiliikennettä, sanaa käytetään muissakin yhteyksissä erilaisista liikennemuodoista ja myös roamingista. Vaatisi varmaan tarkenteen, yhteisliikenne (taksit) tms.

**Comment by mariaforsen** [comment]
Finlex sv. samtrafik (sekin vaatii tarkenteen)

**Comment by YSA-kokous** [comment]
yhteisliikenne (taksit)

**Comment by mariaforsen** [comment]
Sv. samtrafik (taxi)
