### ISSUE TITLE
omatoimikirjastot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5658]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

omatoimikirjastot 

#### Perustelut ehdotukselle   

Omatoimikirjastoiksi kutsutaan kirjastoja, joihin on asennettu asiakkaiden omatoimikäytön mahdollistava järjestelmä. Näitä kirjastoja voit käyttää myös varsinaisten aukioloaikojen ulkopuolella.

Omatoimiaikana kirjastossa ei ole henkilökuntaa, mutta tiloja valvotaan teknisesti mm. kameroin. Yleensä omatoimikirjastossa voi lainata, palauttaa, käyttää asiakastietokoneita, lukea lehtiä ja vaikkapa työskennellä tai kokoustaa. Langaton verkko on käytettävissä. Henkilökunnan palveluajat ja omatoimisen käytön ajat kerrotaan kunkin kirjaston omilla sivuilla.

http://www.helmet.fi/fi-FI/Kirjastot_ja_palvelut/Omatoimikirjastot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.avi.fi/documents/10191/1263926/Selvitys+Suomen+yleisten+kirjastojen+omatoimipalvelujen+toteutumisesta+2015/0ae53ecd-c2ff-4088-b315-ba7b73cb7205 

#### Tarkoitusta täsmentävä selite   

Laajennettu aukiolo voisi olla yksi vaihtoehto ja kävisi muihinkin kuin kirjastoihin. 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [omatoimikirjastot](http://finto.fi/yse/fi/page/Y505658)

**Comment by pauliinaisomaki** [comment]
Kannatan ehdotusta,

**Comment by mirmaid** [comment]
Laajennettu aukiolo voi tarkoittaa muutakin kuin omatoimiaukioloa, joten se ei varmaan käy.

**Comment by satuniininen** [comment]
Englanniksi _self-service libraries_ tai _self-service hours at libraries_. Ei LCSH:ssa.

**Comment by YSA-kokous** [comment]
omatoimikirjastot

**Comment by mariaforsen** [comment]
Sv. meröppna bibliotek ET självbetjäningsbibliotek
