### ISSUE TITLE
trollaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5661]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

trollaus 

#### Ehdotettu termi ruotsiksi   

trolla 

#### Ehdotettu termi englanniksi   

online trolling 

#### Ehdotettu yläkäsite YSOssa (LT)   

[keskinäinen toiminta](http://www.yso.fi/onto/yso/p14) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2015002174> 

#### Tarkoitusta täsmentävä selite   

skapa o­reda t.ex. på inter­net (SAOL) 

#### Perustelut ehdotukselle   

keskeinen käsite tämän päivän yhteiskunnassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Yleisradion verkkosisällöt 

**Ehdottajan nimi:** Mikael Hindsberg 
**Ehdottajan organisaatio:** Yle 
**Ehdottajan sähköpostiosoite:** mikael.hindsberg@yle.fi **Termiehdotus Fintossa:** [trollaus](http://finto.fi/yse/fi/page/Y505661)

**Comment by mirmaid** [comment]
TEPAssa olisi tyrkyllä _verkkoprovosointi_, aikaisemmin ehdotettu _verkkohäiriköinti_ https://github.com/Finto-ehdotus/YSE/issues/2176. Melindassa kerran muodossa _trollaaminen_.

Wikipedia: Vanhastaan trollausta internetissä on katsottu tehdyn vailla välineellisiä päämääriä. Trollauksessa informaatiosodankäynnin käsitteenä sen sijaan on kysymys provosoinnista juuri keinona välineellisten päämärien saavuttamiseksi osana informaatiosodankäyntiä. Näin kysessä on osaksi sama, osaksi eri asia. https://fi.wikipedia.org/wiki/Trolli_(internet) https://fi.wikipedia.org/wiki/Trolli_(infosota)

**Comment by mariaforsen** [comment]
Mitä muotoa ehdotatte ruotsiksi? (Trolla on perusmuoto)

**Comment by mickhinds** [comment]
Kanske "trollande (internet)"

**Comment by YSA-kokous** [comment]
trollaus

**Comment by mariaforsen** [comment]
Sv. trollande (internet) ET internettrollande, internettrollning, nättrollande

**Comment by mickhinds** [comment]
SAOL har godkänt som andra betydelse för "trolla" att "skapa oreda på internet". Skulle därför ogärna se en förled med internet- eller nät-. Utan då hellre specificera i parentes att det syftas på den andra betydelsen som är knuten till internet.

Med den motiveringen håller jag fast vid mitt förslag "trollande (internet)".
