### ISSUE TITLE
holoseeni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5662]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

holoseeni 

#### Ehdotettu termi englanniksi   

holocene 

#### Ehdotettu termi ruotsiksi   

holocen 

#### Vaihtoehtoiset termit ja ilmaisut   

holoseeniepookki 

#### Ehdotettu yläkäsite YSOssa (LT)   

[geologiset kaudet](http://www.yso.fi/onto/yso/p3642) 

#### Vastaava käsite muussa sanastossa   

GEO - geologian sanasto : <http://dev.finto.fi/geo/fi/search?clang=fi&q=holoseeni> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85054112.html> 
SAO : <http://www.kb.se/katalogisering/Svenska-amnesord/> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Holoseeni on nykyinen geologinen aikakausi, joka alkoi ilmaston lämmetessä viimeisimmän jääkauden jälkeen noin 11 560 kalenterivuotta sitten (noin 9 600 eaa.).
https://fi.wikipedia.org/wiki/Holoseeni#Holoseenin_kaudet 

#### Perustelut ehdotukselle   

Melindan asiasanahaku holoseeni -> yli 80 osumaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3092185 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@museovirasto.fi **Termiehdotus Fintossa:** [holoseeni](http://finto.fi/yse/fi/page/Y505662)

**Comment by mirmaid** [comment]
Geologisia kausia voisi muutenkin täydentää.

**Comment by mariaforsen** [comment]
Sv. holocen
