### ISSUE TITLE
lukemistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5663]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lukemistot](http://www.yso.fi/onto/ysa/Y106541) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmä, jako tms. 

#### Perustelut ehdotukselle   

Mihin tämä tarkalleen viittaa YSAssa? 

MOT: "opiskelun tausta-aineistoksi t. viihdelukemiseksi tarkoitettu kirjallisuusotteita, helppotajuisia artikkeleita tm. erillisiä kirjoitelmia sisältävä kirja (t. lehti)"

Ruotsiksi laitettu läseböcker (textsamlingar), mikä ei ainakaan täsmää osa Melinda-aineistojen kanssa (monessa vain yksi teos, ei tekstikokoelma/antologia). Ruotsinkielinen termi on muutenkin onneton, mutta jonkinlainen kompromissi joudutaan miten vain tekemään, koska ruotsiksi tämä käsite ei toimi samalla tavalla kuin suomeksi (eikä olisi ylipäätään mukana missään sanastossa). 

Melindassa nyt käytetty sekavasti, esim.: 
Exploring ethics : an introductory anthology / edited by Steven M. Cahn 
Wuthering Heights / Emily Brontë ; adapted by Jennifer Gascoigne 
Easy Arabic reader : a three-part text for beginning students / Mahmoud Gaafar & Jane Wightwick  College writing skills with readings / John Langan 
Taikamaan lukukirja / Sinikka Raikunen, Katariina Leino ; kuvitus: JP Ahonen ...

Eli ainakin 2-3 aivan erityyppistä aineistoa. Ja näitä onkin paljon, ks. tarkemmin Melindassa. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by AuHo22** [comment]
Yleisen kirjaston ajoilta muistan sen, että lukemistoiksi kutsuttiin myös näitä ns. Easy Reader(s) -tyyppisiä vieraan kielen opiskeluun tarkoitettuja kirjoja, jotka sisälsivät usein vain yhden, mutta alkuperäistekstistä helpotetun ja sanastokommentein tms. varustetun kertomuksen. Näköjään HelMetistä edelleen löytyy paljon.

**Comment by YSA-kokous** [comment]
Kaunokki

**Comment by AuHo22** [comment]
YKL:ssä luokassa 88.2 seuraava kuvailu: Tähän myös suomen kielen opiskeluun liittyvät selityksillä tai sanastolla varustetut _lukemistot_ ja _lukukirjat_. Vastaava 89.31 ruotsin kielen kohdalla.

**Comment by mariaforsen** [comment]
Sielläkin siis text- och läseböcker, mikä ei toimi kaiken Melinda-aineiston kanssa.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/6023

**Comment by mirmaid** [comment]
SLM: KÄ viihdelukemistot ja helppolukuiset kirjat, muokataan jälkimmäisen määritelmää

**Comment by AuHo22** [comment]
Voidaanko ohjata myös KÄ lukukirjat? Joka on siis lukemiston yksi merkitys.
https://fi.wikipedia.org/wiki/Lukukirja

**Comment by YSA-kokous** [comment]
KÄ viihdelukemistot, helppolukuiset kirjat, lukukirjat. Helppolukuiset kirjat: määritelmä.

**Comment by mirmaid** [comment]
SLM: määritelmä

**Comment by mirmaid** [comment]
Määritelmä lisätty.
