### ISSUE TITLE
yksinlaulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5664]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yksinlaulu](http://www.yso.fi/onto/ysa/Y214731) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

yksinlaulu (laulaminen)? 

#### Perustelut ehdotukselle   

Sanastossa on nyt sekä yksinlaulu että yksinlaulut. Yksikkömuodolle pitänee lisätä tarkenne. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan
