### ISSUE TITLE
permakulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5665]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[permakulttuuri](http://www.yso.fi/onto/ysa/Y111198) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmä on nyt: "Tarkoittaa kokonaisvaltaista suunnittelufilosofiaa, jonka pyrkimyksenä on rakennetun ympäristön suunnittelu luontoa kunnioittaen." Voisiko määritelmään lisätä jotain maataloudesta tai viljelystä? Laajempi termi on kulttuuri. Kongressin kirjaston asiasana Permaculture koskee nimenomaan viljelyä ja sen laajemmat termit ovat Alternative agriculture ja  Agricultural ecology. Permaculture määritellään termillä "permanent agriculture". 

#### Perustelut ehdotukselle   

Permakulttuuria käsitteleviä kirjoja on useita ja ainakin uudemmissa on kysymys maataloustuotannosta. 

#### Ehdottaja   

Anneli Korhonen 

#### Ehdottajan organisaatio   

Hämeen ammattikorkeakoulun kirjasto 

#### Ehdottajan sähköpostiosoite   

anneli.korhonen@hamk.fi

**Comment by satuniininen** [comment]
https://fi.wikipedia.org/wiki/Permakulttuuri

"Permakulttuuri tarkoittaa rakennetun ympäristön suunnittelua luontoa kunnioittaen. Käsite permaculture tuli alun perin sanoista permanent agriculture, pysyvä maanviljely, mutta se on levinnyt siitä muillekin suunnittelun osa-alueille, ja nykyisin lyhenne tulkitaan perma = kestävä + kulttuuri. Permakulttuuri on kokonaisvaltainen suunnittelufilosofia, joka kattaa puutarhan, arkkitehtuurin, ekologian, jopa rahanhallinnan ja yhteisösuunnittelun."

**Comment by PaiviLipsanen** [comment]
Suomen Permakulttuuriyhdistys määrittelee asian näin:
http://www.permakulttuuri.fi/permakulttuuri.html
"Permakulttuuri on ekologiaan perustuva suunnittelumenetelmä, jonka avulla pyritään luonnon prosesseja jäljittelemällä ja niitä hyödyntämällä kehittämään kestäviä järjestelmiä, jotka täyttävät yhtä lailla yksittäisen ihmisen, ihmisyhteisöjen kuin maapallonkin tarpeita lyhyellä ja pitkällä aikavälillä. Nämä järjestelmät voivat olla esimerkiksi ruoan ja energian tuotantoon, asumiseen tai taloudellisen toiminnan organisointiin liittyviä järjestelmiä."

Saisikohan näistä muokattua sopivan määritelmän, joka mahdollistaisi linkittämisen Kongressin kirjaston sanastoon.

**Comment by satuniininen** [comment]
Käsite on jo linkitetty Kongressin kirjastoon. Yson puolelta huomautusteksti puuttuu kokonaan.

**Comment by YSA-kokous** [comment]
Poistetaan määritelmä.
