### ISSUE TITLE
Newcastle upon Tyne

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5667]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Newcastle upon Tyne 

#### Ehdotettu termi ruotsiksi   

Newcastle upon Tyne 

#### Ehdotettu termi englanniksi   

Newcastle upon Tyne 

#### Vaihtoehtoiset termit ja ilmaisut   

Newcastle 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/n81008303 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Newcastle_upon_Tyne 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Popular Music and Youth Culture / Andy Bennett 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Newcastle upon Tyne](http://finto.fi/yse/fi/page/Y505667)

**Comment by mariaforsen** [comment]
Sv. Newcastle-upon-Tyne
