### ISSUE TITLE
loisiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5668]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[loisiot](http://www.yso.fi/onto/ysa/Y164992) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa? 

#### Perustelut ehdotukselle   

Mihin tarkalleen tämä viittaa? Googlessa "loisiot" site:fi antaa 27 osumaa ja melkein kaikki liittyvät YSAan tai malarialoision (erikseen pääterminä YSAssa). Mikä tämä on latinaksi? Melindassa 3 tietuetta, joista 2 malarialoisio kyseessä ja ensimmäiselle riittäisi loiset? Ongelma ruotsiksi. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by FinMeSHienPaimentaja** [comment]
Tiedoksenne, että  (Terveysportin kautta) Lääketieteen termit
http://www.terveysportti.fi/sovellukset/sanakirjat/#/q//loisio
löytyy:

loisio
parasitus la, parasite e, parasit ‑en r yksisoluisiin alkueläimiin kuuluva loinen, esim. malarialoisio

yst.terv. Rosa Maritta Venäläinen
https://www.terkko.helsinki.fi/contact

**Comment by mirmaid** [comment]
Jos halutaan, tilalle voisi ottaa itiöeläimet https://fi.wikipedia.org/wiki/Iti%C3%B6el%C3%A4imet?

**Comment by mariaforsen** [comment]
Loiset=parasiter on myös jo sanastossa, eli sillä tavalla ei voi kääntää loisiot.

**Comment by FinMeSHienPaimentaja** [comment]
Niinpä – ”loiset” on eri asia kuin ”loisiot”.

…lisää pohdittavaa:

itiöeläimet:
https://fi.wikipedia.org/wiki/Iti%C3%B6el%C3%A4imet

alkueläimet:
https://fi.wikipedia.org/wiki/Alkuel%C3%A4imet

malarialoisio/loinen Termix:issä:
https://www.terkko.helsinki.fi/termix/?hakusanat=*loisio&lang=fi

malarialoisio/loinen MeSH-puussa:
https://meshb.nlm.nih.gov/record/ui?name=Plasmodium

(Terveysportin kautta) Lääketieteen termit
http://www.terveysportti.fi/sovellukset/sanakirjat/#/q//loisio
löytyvä:
loisio
parasitus la, parasite e, parasit  en r yksisoluisiin alkueläimiin kuuluva loinen, esim. malarialoisio

olisi ehkä ”alkueläimet” –termin kanssa synonyymisin, mutta toisaalta  termi ”alkueläimet” on erikseen ja kaikki yksisoluiset alkueläimet eivät liene loisioita – vaikka monet  /  suuri(n) osa olisikin?  Wikipedian määritelmän mukaan alkueläimet ovat  toisenvaraisia, mikä on kuitenkin merkitykseltään eri asia kuin loisiona oleminen.

rosa.venalainen@helsinki.fi

**Comment by YSA-kokous** [comment]
Poistetaan
