### ISSUE TITLE
figuurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5669]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

figuurit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Tunnetaan yleisesti. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kirjasto.jyu.fi/kauppa/tuotteet/pienoismallirakentajan-kasikirja 

**Ehdottajan nimi:** Harri Hirvi 
**Ehdottajan organisaatio:** Htväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** harri.hirvi@jyu.fi **Termiehdotus Fintossa:** [figuurit](http://finto.fi/yse/fi/page/Y505669)

**Comment by mirmaid** [comment]
Monimerkityksinen sana; _Leikkikaluihin liittyen figuuri on nukke tai koriste-esine, joka on tehty muistuttamaan tunnettua henkilöä tai kuvitteellista hahmoa. Usein figuureita valmistetaan elokuva-, televisio- ja sarjakuvahahmoista._ https://fi.wikipedia.org/wiki/Figuuri

http://www.pienoismallit.net/galleria/mallit/figuurit/ 
https://www.hobbylinna.fi/tuotteet/pienoismallit/figuurit-ja-dioraamatarvikkeet/figuurit-ja-dioraamatarvikkeet-1-16/21008/

**Comment by mariaforsen** [comment]
Vrt. myös MOT ja TEPA. Voisi mahdollisesti olla figurer (leksaker) siinä tapauksessa.

**Comment by YSA-kokous** [comment]
figuurit (pienoismallit)

**Comment by mariaforsen** [comment]
Sv. figurer (miniatyrer)
