### ISSUE TITLE
rumbat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5670]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rumbat](http://www.yso.fi/onto/ysa/Y104211) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko kuten YSOssa: rumba (tanssimusiikki) ; rumbat (latinalaistanssit) 

#### Perustelut ehdotukselle   

YSAssa vain rumbat, jolla yläkäsitteinä: 

    latinalaisamerikkalainen populaarimusiikki
    latinalaistanssit
    tanssimusiikki
    tanssit 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
On jo jaettu.
