### ISSUE TITLE
padel

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5671]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

padel 

#### Ehdotettu termi ruotsiksi   

padeltennis 

#### Ehdotettu termi englanniksi   

paddle 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Padel 

#### Perustelut ehdotukselle   

Yleinen laji Suomessa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Yle arkiston radioarkistoaineiston 

**Ehdottajan nimi:** Laura Karvinen 
**Ehdottajan organisaatio:** Yle 
**Ehdottajan sähköpostiosoite:** laura.karvinen@yle.fi **Termiehdotus Fintossa:** [padel](http://finto.fi/yse/fi/page/Y505671)

**Comment by mariaforsen** [comment]
Sv. padel ET padeltennis
