### ISSUE TITLE
vokaliisit (harjoitusaineistot)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5673]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vokaliisit (harjoitusaineistot)](http://www.yso.fi/onto/ysa/Y214810) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan käsite muotoon "vokaliisit (harjoitteet)". 

#### Perustelut ehdotukselle   

Täsmenne "harjoitteet" kuvaisi asiaa paremmin kuin nykyinen "harjoitusaineistot": yksittäinen vokaliisi on laulutekniikan osa-alueen vahvistamista varten tehty harjoituskappale (harjoite), ja vasta joukko sellaisia yhdessä (julkaistuna) olisi harjoitusaineisto. Ja huomautukseksi: kyse ei siis sanattomista lauluista varsinaisina esitettäväksi tarkoitettuina teoksina, vaan vain harjoituskappaleista; tällä toisella on sanastossa oma terminsä "vokaliisit (laulut)". -- Korjaustarve tuli vastaan MUSAn YSAan sulauttamisen ja termien samanaikaisen YSO-valmistelun yhteydessä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ilkkahaataja** [comment]
Luumu-kokous (27.11.2017): Puollamme ehdotusta.
