### ISSUE TITLE
Tampereen rantatunneli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5674]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tampereen rantatunneli 

#### Ehdotettu termi ruotsiksi   

Tammerfors strandtunnel 

#### Ehdotettu termi englanniksi   

Tampere Lakeside tunnel 

#### Vaihtoehtoiset termit ja ilmaisut   

Rantatunneli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tunnelit](http://www.yso.fi/onto/yso/p6744) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tunneli tasaiselle maalle : Tampereen Rantatunnelin lyhyt historia 

#### Tarkoitusta täsmentävä selite   

Rantatunneli on Tampereelle Näsijärven rantaan rakennettu yli 2,3 kilometriä pitkä maantietunneli 

#### Perustelut ehdotukselle   

Tarve aineiston kuvailussa 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [Tampereen rantatunneli](http://finto.fi/yse/fi/page/Y505674)

**Comment by mariaforsen** [comment]
Sv. Tammerfors strandtunnel ET Strandtunneln
