### ISSUE TITLE
Skagerrakin taistelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5675]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Skagerrakin taistelu 

#### Ehdotettu termi ruotsiksi   

Skagerrakslaget 

#### Ehdotettu termi englanniksi   

Battle of Jutland 

#### Vaihtoehtoiset termit ja ilmaisut   

Jutlandin taistelu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[meritaistelut](http://www.yso.fi/onto/yso/p4131) 

#### Vastaava käsite muussa sanastossa   

Svenska ämnesord : Skagerrakslaget 1916 
LCSH : <http://id.loc.gov/authorities/subjects/sh85071160.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

Ensimmäisen maailmansodan laajin meritaistelu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3084209 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [Skagerrakin taistelu](http://finto.fi/yse/fi/page/Y505675)

**Comment by LeKorsu** [comment]
Tuleeko tähän selitykseksi tai sulkeisiin jokin aikamääre?

**Comment by mariaforsen** [comment]
Sv. Skagerrakslaget ET Jutlandslaget ET Skagerrakslaget 1916
