### ISSUE TITLE
ulottuvuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5676]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ulottuvuus](http://www.yso.fi/onto/ysa/Y110154) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään siten, että yläkäsite on "ominaisuudet" 

#### Perustelut ehdotukselle   

Tällä hetkellä yläkäsite on varmaan vahingossa "maku (aineen ominaisuudet)" 

#### Ehdottaja   

Matti Rajahonka 

#### Ehdottajan organisaatio   

Jyväskylän yliopisto, Avoimen tiedon keskus / kirjasto 

#### Ehdottajan sähköpostiosoite   

matti-petteri.rajahonka@jyu.fi

**Comment by mirmaid** [comment]
Korjattu
