### ISSUE TITLE
melodiadiktaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5677]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[melodiadiktaatit](http://www.yso.fi/onto/ysa/Y199057) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan käsite yksikköön (melodiadiktaatit --> melodiadiktaatti). 

#### Perustelut ehdotukselle   

Vastaava rytmiä käsittelevä diktaatti on yksikössä ("rytmidiktaatti") ja LT-suhteinen termi myös ("diktaatti"), joten tämänkin olisi hyvä olla samassa linjassa. (Asia tuli esille MUSAn YSAan sulauttamistyöpajassa.) 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5594
