### ISSUE TITLE
hallintotoimi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5679]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hallintotoimi](http://www.yso.fi/onto/ysa/Y95266) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Kaksi merkitystä:

1. kunnan toimiala (vrt. sivistystoimi, pelastustoimi)
2. hallintotehtävän hoitamiseen liittyvä toiminta yksittäistapauksessa. Hallintotoimen ulkoisena muotona on tavallisesti hallintopäätös, joka sisältää ratkaisun hallintoasiassa. Hallintotoimia käytetään etenkin hallinnollisessa sääntelyssä ja valvonnassa. Myös julkisia palveluja toteutetaan hallintotoimina, joita käytetään varsinkin tosiasiallisessa hallintotoiminnassa.

YSOssa käsite on hierarkisoitu ykkösmerkityksen mukaan, Melinda-käytössä löytyy molempia. 

#### Ehdotettu muutos   

Käsite on monimerkityksinen, joten se pitää tarkentaa haluttuun merkitykseen tai jakaa useampaan. Lisäksi tämän pitäisi ehkä olla monikossa? 

#### Ehdottaja   

Satu Niininen / Yso-kokous 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mirmaid** [comment]
hallintotoimi (toimiala)
hallintotoimet (toimenpiteet) (?)

**Comment by mariaforsen** [comment]
Ruotsiksi on ollut: förvaltningsakt. 

Kielitoimiston sanakirja: Poistaa jku virasta hallintotoimin. 
Eli täsmää ruotsin vastineen kanssa.

Myös MOTissa (ja muissa sanakirjoissa), TEPAssa, Eurovocissa, IATEssa, Wikipediassa, Tieteen termipankissa ja Eduskunnan sanastossa vain tämä merkitys. Olisiko siis parempi että pidetään vain siinä merkityksessä?

Jos kaikesta huolimatta otetaan myös kunnan toimialana niin ruotsiksi ei varmaan saada vakiintunutta termiä.

**Comment by mirmaid** [comment]
Olisiko niin että ruotsiksi sanotaan vain förvaltning (förvaltningsorganisation?), suomeksi lisätään tuo -toimi tekemään eroa itse toiminnan ja sitä suorittavan tahon välille. http://www.kustavi.fi/toimi/hallintotoimi; Drottningholms slottsförvaltning | Drottningholmin linnan hallinto(toimi) http://www.sprakochfolkminnen.se/sprak/minoritetssprak/suomi-finska/ruotsalais-suomalaiset-sanastot/sanastot/2014-01-13-kuninkaallinen-hovi.html.

**Comment by YSA-kokous** [comment]
hallintotoimet
