### ISSUE TITLE
joikaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5680]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

joikaajat 

#### Ehdotettu termi ruotsiksi   

jojkare 

#### Vaihtoehtoiset termit ja ilmaisut   

englanniksi ei ole termiä. yleensä vain singer. voisi olla joik singer 

#### Vastaava käsite muussa sanastossa   

SAOL : https://svenska.se/tre/?sok=jojkare&pz=2 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Laulaja, joka esittää joikuja joikaamalla. 

#### Perustelut ehdotukselle   

YSOssa on jo joikaaminen sekä joiut.
testaan samalla ehdotuksen tekemistä ja käsittelyä.... 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kuvattaessa eisttäviä taiteilijoita, jotka esiintyvä joikaamalla.  täydentää subjekti-predikaatti-objekti ketjun ontologiassa 

**Ehdottajan nimi:** Jarmo Saarikko 
**Ehdottajan organisaatio:** KVP 
**Ehdottajan sähköpostiosoite:** jarmo.saarikko@helsinki.fi **Termiehdotus Fintossa:** [joikaajat](http://finto.fi/yse/fi/page/Y505680)

**Comment by asormune** [comment]
Tarvittaisiinko myös termi jodlaajat (jodlaus on YSA:ssa)

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan joikaajat-termin lisäämistä

**Comment by mariaforsen** [comment]
Sv. jojkare
