### ISSUE TITLE
tarhaneilikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5682]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tarhaneilikka 

#### Ehdotettu termi ruotsiksi   

trädgårdsnejlika 

#### Ehdotettu termi englanniksi   

carnation 

#### Ehdotettu yläkäsite YSOssa (LT)   

[koristekasvit](http://www.yso.fi/onto/yso/p489) 
[leikkokukat](http://www.yso.fi/onto/yso/p9265) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Tarhaneilikka 
LCSH : https://lccn.loc.gov/sh85020361 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

Tavallinen leikkokukkana käytetty neilikkalaji. 

#### Perustelut ehdotukselle   

YSAssa on muitakin vastaavia lajinimiä, esim. kurtturuusu. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Muiden muassa: Carnations and pinks for garden and greenhouse 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [tarhaneilikka](http://finto.fi/yse/fi/page/Y505682)

**Comment by PaiviLipsanen** [comment]
tarhaneilikka (Dianthus caryophyllus)
yläkäsite olisi neilikat (suku - Dianthus),
jonka yläkäsite on kohokkikasvit - heimo - on YSAssa

Assosiatiivisia käsitteitä olisivat:
koristekasvit
leikkokukat

**Comment by mirmaid** [comment]
Lisätty myös _neilikat_
