### ISSUE TITLE
fuusio (ydinreaktiot)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5683]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fuusio (ydinreaktiot)](http://www.yso.fi/onto/ysa/Y101395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muotoon "ydinfuusiot". Nykyinen päätermi ohjaustermiksi. 

#### Perustelut ehdotukselle   

Olisi sujuvampaa kieltä. Lisäksi koska kyseessä on tapahtuma niin monikkomuoto tuntuisi yksikköä luontevammalta. Asia tuli keskusteluun JUHO-työn yhteydessä. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Wikipediassa fuusioreaktio https://fi.wikipedia.org/wiki/Fuusioreaktio, Google n. 6500, ydinfuusio n. 1600. Yksikkö tuntuu tässä luontevammalta vaikka kyse onkin tapahtumasta, jollei sitten ajatella että monikko viittaa erilaisten ytimien fuusioihin erilaisine lopputuotteineen (deuterium-tritium-fuusio, hiilen fuusio). Monikko kuitenkin aika vähän käytetty (nuclear fusions < 8000, nuclear fusion > 3 000 000)

**Comment by AuHo22** [comment]
Voidaanko samalla muuttaa sujuvammalle kielelle fuusiot (yritysjärjestelyt) -> yritysfuusiot?

**Comment by YSA-kokous** [comment]
fuusioreaktio KT ydinfuusio, fuusio (ydinreaktiot)
fuusiot (yritysjärjestelyt) KÄ yritysfuusiot

**Comment by mariaforsen** [comment]
Sv. 
-fusion (kärnreaktioner) ET fusion (kärnfysik), fusionsreaktion, kärnfusion
-företagsfusioner ET fusioner (företagsarrangemang)
