### ISSUE TITLE
postivirkamiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5684]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[postivirkamiehet](http://www.yso.fi/onto/ysa/Y108285) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ammattinimikettä ei ole enää käytössä. Tätä valottava huomautus voisi olla paikallaan. Ehkä myös modernimpi ammattinimike uutena käsitteenä? Postin työpaikkasivuilla puhutaan postityöntekijöistä. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
Postityöntekijät käytetty 16 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Kannatan! SAO: postanställda (KT posttjänstemän). Tämän mallin mukaan on tehty muutkin -virkamiehet SAOssa.

**Comment by YSA-kokous** [comment]
Otetaan postityöntekijät, säilytetään myös postivirkamiehet.

**Comment by mariaforsen** [comment]
Sv. postanställda
