### ISSUE TITLE
Brexit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5686]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Brexit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[Euroopan integraatio](http://www.yso.fi/onto/yso/p18496) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

Käsittääkseni vakiintunut termi Britannian lähdölle Euroopan unionista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Europe didn't work, isbn  	978-0-300-22879-3| 

**Ehdottajan nimi:** Sini Neuvonen 
**Ehdottajan organisaatio:** Espoon kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** sini.neuvonen@espoo.fi **Termiehdotus Fintossa:** [Brexit](http://finto.fi/yse/fi/page/Y505686)

**Comment by tpalonen** [comment]
Brexitin kirjoittaminen pienellä alkukirjaimella näyttäisi yleistyneen Helsingin Sanomien, Ylen ja Aamulehden teksteissä, vaikka pientä hajontaa on. Ks.
https://www.hs.fi/aihe/brexit/
https://yle.fi/aihe/termi/yle/18-97901

Määritelmä tai huomautus voisi olla hyvä, jotta käsitteen merkitys avautuu käyttäjälle vielä 10 vuoden päästäkin.

**Comment by mariaforsen** [comment]
Sv. brexit /Nationalencyklopedin

**Comment by krinay** [comment]
Kotus:
"Sitaattilainana suomen kieleen tulleet erisnimilähtöiset lyhennesanat suositetaan kirjoittamaan ensisijaisesti pienellä alkukirjaimella. Jos kuitenkin haluaa korostaa lyhennesanan erisnimisyyttä, voi käyttää isoakin alkukirjainta:
grexit  (~ Grexit) ← Greek/Greece + exit  ’Kreikan ero euroalueesta’
brexit  (~ Brexit) ← British/Britain + exit  ’Britannian ero Euroopan unionista’
Kyseiset sanat voi siis suosituksen mukaan kirjoittaa suomessa joko isolla tai pienellä alkukirjaimella. Isoa alkukirjainta puoltaa esimerkiksi se, että ilmaus yksilöi vain tietyn valtion eron. Pienellä kirjoittava voi puolestaan ajatella, että brexit- ja grexit-sanojen -- sisältämä loppuosa exit määrittää sanan lajin, samalla tavalla kuin yhdyssanan perusosa tekee (esim. suomenpystykorva, siperianangervo). Alkukirjain vaihtelee myös kielittäin: esimerkiksi englannissa exit-tapaukset kirjoitetaan isolla, ruotsissa pienellä."

**Comment by YSA-kokous** [comment]
brexit
