### ISSUE TITLE
lisälaitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5687]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lisälaitteet](http://www.yso.fi/onto/ysa/Y107557) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nyt korvattu termi oheislaitteet -> oheislaitteet erillisenä pääterminä? 

#### Perustelut ehdotukselle   

Lisälaitteet ruotsiksi "perifera enheter", joka käy ainoastaan atk-merkityksessä. Melindassa on lisälaitteet nyt käytetty sekä atk-merkityksessä että missä tahansa esim. maatalouskoneiden yhteydessä. 

MOT: oheislaite=tietokonejärjestelmän laite, joka ei kuulu keskusyksikköön. 
Wikisanakirja: lisälaite=johonkin laitteeseen liitettävä ja sen toiminnallisuutta laajentava laite (MOTissa vain kamera esimerkkinä)

Sanastossa myös lisävarusteet ja lisätarvikkeet. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Onkohan tämä suomeksi ihan näin selkeä? Ilman määritelmiä en itse tunnistaisi oheislaitetta nimenomaan tietokoneen lisälaitteeksi. Viitteet Googlella liittyvät kyllä enimmäkseen tietotekniikkaan, vaikka eivät täysin.

**Comment by mariaforsen** [comment]
Ainakin 5 Motin sanakirjaa antaa merkityksenä nimenomaan atk oheislaitteille. Jos kuitenkin säilytetään asiat ennallaan niin täytyy miten vain vaihtaa ruotsink. vastine, koska perifera enheter on nimenomaan atk (ja jos päätermi lisälaitteet pitää kattaa myös muuta niin vastinehan ei voi viitata pelkästään atk-merkitykseen). Hankaluuksia (päällekkäisyyttä) aiheuttaa ruotsiksi varsinkin se että sanastossa on myös lisävarusteet ja lisätarvikkeet. 

-> Eli voidaan kyllä laittaa joku neutraalimpi vastine ruotsiksi ("tilläggsanordningar/apparater"?), jos tosiaan halutaan että voi viitata mihin tahansa "lisälaitteeseen"?

**Comment by mirmaid** [comment]
Jos otetaan suomeksi _oheislaitteet_, niin vaatisiko kuitenkin tarkenteen, esim. _oheislaitteet (tietotekniikka)_, että käyttö varmasti rajautuisi samalla tavalla kuin ruotsiksi? Tai vaihtoehtoisesti _tietokoneen oheislaitteet_ (FinMeSHissä)? Toki riippuu vähän siitä mitä tämä voi kattaa, vrt. 
https://www.audiokauppa.fi/epages/audiokauppa.sf/fi_FI/?ObjectPath=/Shops/20121220-11092-175030-1/Categories/Oheislaitteet_ja_tarvikkeet
http://geomachine.fi/Oheislaitteet
http://www.econetgroup.fi/econet-group/dewaco/tuotteet/lietteen-tiivistys-ja-kuivaus/oheislaitteet

**Comment by YSA-kokous** [comment]
oheislaitteet (tietotekniikka) KT tietokoneen oheislaitteet
