### ISSUE TITLE
southern rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5688]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

southern rock 

#### Ehdotettu termi englanniksi   

southern rock 

#### Perustelut ehdotukselle   

Luetteloidessani Lynyrd Skynyrdin cd-levyä havaitsin, että termi "southern rock" ei ole asiasana. Kyseessä on kuitenkin melko tärkeä ja yleinen musiikin laji. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Musiikkiaineisto, cd-levyt 

**Ehdottajan nimi:** Juha Suni 
**Ehdottajan organisaatio:** Lopen kunnankirjasto 
**Ehdottajan sähköpostiosoite:** juha.suni@loppi.fi **Termiehdotus Fintossa:** [southern rock](http://finto.fi/yse/fi/page/Y505688)

**Comment by asormune** [comment]
Rock -termillä on YSA:ssa 21 alakäsitettä, niin eiköhän siihen joukkoon vielä yksi mahdu.

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan.

**Comment by mariaforsen** [comment]
Sv. sydstatsrock ET southern rock
