### ISSUE TITLE
kadunnimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5689]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kadunnimet 

#### Ehdotettu termi ruotsiksi   

gatunamn 

#### Ehdotettu termi englanniksi   

street names 

#### Ehdotettu yläkäsite YSOssa (LT)   

[paikannimet](http://www.yso.fi/onto/yso/p10410) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85128591> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helsingin kadunnimet 2 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Termi "paikannimet" ei välttämättä ole riittävän tarkka kuvastamaan asiaa. Asia toki olisi ilmaistavissa mainitun ja "kadut"-termin yhdistelmällä, mutta toisaalta ehdotettua näyttää käytetyn Melindassa kokonaista 58 kertaa, mikä kertoo omaa kieltään ilmaisun luontevuudesta. 

#### Tarkoitusta täsmentävä selite   

. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [kadunnimet](http://finto.fi/yse/fi/page/Y505689)

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä teoksen "Från Flemingsgatan till Pehr Sommars gata : persongatunamn i Ekenäs" kuvailussa.

**Comment by tpalonen** [comment]
Ohjaustermiksi tiennimet? Esim. Kotus näkyy käyttävän kadunnimiä ja tiennimiä melko synonyymisesti. https://www.kotus.fi/ohjeet/nimistonsuunnittelun_ohjeita/kadunnimien_suunnittelu

**Comment by mariaforsen** [comment]
Maalla ei tosin ole katuja, pitäisikö kuitenkin olla vägnamn erikseen?

**Comment by mirmaid** [comment]
_Kadunnimet_ on JUPOssa. 

_Tiennimet_ käytetty Melindassa 21 kertaa, toisaalta myös _kylännimet_ käytetty 31 kertaa.

**Comment by YSA-kokous** [comment]
kadunnimet, tiennimet

**Comment by mariaforsen** [comment]
Sv. 
-gatunamn
-vägnamn
