### ISSUE TITLE
veturimiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5690]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[veturimiehet](http://www.yso.fi/onto/ysa/Y105577) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄYTÄ veturinkuljettajat 

#### Perustelut ehdotukselle   

Mihin veturimies viittaa? Ruotsin vastine lokmän (sellaista ei oikeastaan ole). Melindassa 22, esim. Veturimiehet Savonlinnassa radan tulosta näihin päiviin : Veturimiesten liiton Savonlinnan osasto / Kyösti Vatanen (toim.), Jyrki Vauhkonen (toim.). 

Wikipedia: "Veturinkuljettajat ovat järjestäytyneet miltei sataprosenttisella järjestäytymisasteella Veturimiesten Liittoon (VML), johon kuuluu pelkästään veturinkuljettajia." 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
https://www.verkkouutiset.fi/ratkaisu-kanteluun-onko-veturimiesten-liitto-nyt-veturinkuljettajien-liitto/ :steam_locomotive:
