### ISSUE TITLE
omaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5691]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[omaiset](http://www.yso.fi/onto/ysa/Y97780) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

RT-suhde asiasanaan "sukulaiset" pitäisi olla ST. Myös suhde asiasanaan "perheenjäsenet" vaatisi samalla tutkailua. 

#### Perustelut ehdotukselle   

Kaikki omaiset ovat sukulaisia, mutta kaikki sukulaiset eivät ole omaisia. Esimerkiksi Kielitoimiston sanakirjan mukaan omainen on "oman perheen jäsen, läheinen sukulainen" [http://www.kielitoimistonsanakirja.fi/omainen]. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
YSOssa on perheenjäsenet LT omaiset LT sukulaiset
