### ISSUE TITLE
tullivirkamiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5692]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tullivirkamiehet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[virkamiehet](http://www.yso.fi/onto/yso/p212) 
[tullimiehet](http://www.yso.fi/onto/yso/p10363) 

#### Perustelut ehdotukselle   

Analogia: asiasana "postivirkamiehet" 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Postivirkamies Anders Johan Cumlanderin kuolinilmoituksen "annotoinnissa" 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [tullivirkamiehet](http://finto.fi/yse/fi/page/Y505692)

**Comment by mariaforsen** [comment]
KS: tullimies: (alempi) tullivirkamies
Allärs: tulltjänstemän=tullimiehet > voidaan muuttaa

**Comment by mirmaid** [comment]
Tullimiehet LT YSAssa nyt tulliviranomaiset. Nykyinen ammattinimi olisi tullitarkastaja.

**Comment by YSA-kokous** [comment]
tullivirkamiehet, tullitarkastajat (poistetaan tullimiehet)

**Comment by mariaforsen** [comment]
Sv. 
-tulltjänstemän
-tullinspektörer ET tullkontrollörer
