### ISSUE TITLE
Treenata

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5693]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Treenata 

#### Perustelut ehdotukselle   

Olisi hyvä, jos YSA/YSO tunnistaisi treenaamiseen liittyvät termin. Se vaikuttaisi olevan hyvin yleisesti käytetty sana liittyen kuntoilun harjoittamiseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Bull vs. Vertti, Suurin pudottaja, Jutta ja puolen vuoden superdieetit (tv-ohjelmia) 

**Ehdottajan nimi:** Anne-Maria Siltanen 
**Ehdottajan sähköpostiosoite:** anne-maria.siltanen@kavi.fi **Termiehdotus Fintossa:** [Treenata](http://finto.fi/yse/fi/page/Y505693)

**Comment by mariaforsen** [comment]
Ehdotettu YSAan myös "fyysinen harjoittelu"

**Comment by YSA-kokous** [comment]
ohjaustermit
