### ISSUE TITLE
kahvittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5696]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kahvittelu 

#### Ehdotettu termi ruotsiksi   

fika 

#### Assosiatiiviset (RT)   

[seuraelämä](http://www.yso.fi/onto/yso/p7560) 
[sosiaaliset suhteet](http://www.yso.fi/onto/yso/p411) 
[sosiaaliset verkostot](http://www.yso.fi/onto/yso/p408) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Tarkoitusta täsmentävä selite   

Kahvittelu, kahvitarjoilu tai kahvinjuonti (ruots. fika) on erityisesti Suomessa ja Ruotsissa yleinen sosiaalinen instituutio, jossa kokoonnutaan juomaan kahvia sekä syömään makeita ja suolaisia leivonnaisia ja samalla keskustelemaan. Kahvittelu voi olla työnteon tai kotiaskareet keskeyttävä tauko, kotiin kutsutuille vieraille laadittava, ruokailua kevyempi tarjoilu, työpaikan tai järjestöelämän kokoustarjoilu tai pistäytyminen kahvilassa joko yksin tai isommassa seurueessa. Perinteiset tavat tarjoilla kahvia ja leivonnaisia ovat valmiiksi katettu istumapöytä pienemmälle seurueelle tai noutopöytäperiaatteeseen perustuva seisomapöytä isommalle seurueelle esimerkiksi juhlissa.[1]

Kahvittelu on enemmänkin yhdessäoloa korostava sosiaalinen tapahtuma ja virkistäytymiseen tarkoitettu tauko kuin varsinainen ruokailuhetki.[2] Pohjoismaisessa kahvikulttuurissa pelkän kahvin juonti ei kuitenkaan yleensä riitä, vaan perinteisesti kahvin kanssa tarjotaan kahvileipää (ruots. fikabröd) eli pullaa, viinereitä, kakkuja, keksejä tai pikkuleipiä. Ruokaisampi kahvitarjoilu syntyy suolaisista leivonnaisista, kuten karjalanpiirakoista, pasteijoista, voileivistä tai voileipäkakusta.

Lähde: https://fi.wikipedia.org/wiki/Kahvittelu 

#### Perustelut ehdotukselle   

Elokuvissa ja tv-ohjelmissa usein esiintyvä ilmiö, joka on vaikea kuvailla on käytössä olevin termein. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Elokuvat, tv-ohjelmat, muu kuva-aineisto 

**Ehdottajan nimi:** Jorma Junttila, Juha Piukkula 
**Ehdottajan organisaatio:** KAVI 
**Ehdottajan sähköpostiosoite:** jorma.junttila@kavi.fi **Termiehdotus Fintossa:** [kahvittelu](http://finto.fi/yse/fi/page/Y505696)

**Comment by tpalonen** [comment]
Hieman vastaavia käsitteitä YSAssa ovat mm. ruokakulttuuri, päihdekulttuuri ja alkoholikulttuuri. Tällä analogialla ehdotan päätermiksi kahvittelun sijaan muotoa **kahvikulttuuri**, joka mielestäni sopisi kahvittelua paremmin myös tietokirjallisuuden yhteyteen. Kahvittelun lisäisin ohjaustermiksi.

**Comment by krinay** [comment]
Tätä aihepiiriä käsittelevää kirjallisuutta on aiemmin sisällökuvailtu mm. termeillä kahvi + tapakulttuuri, mutta ihan hyvä, jos saadaan oma termi asialle.

**Comment by YSA-kokous** [comment]
Kahvikulttuuri KT kahvittelu

**Comment by mariaforsen** [comment]
Sv. fikakultur ET kaffekultur, fika
