### ISSUE TITLE
luolatutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5698]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luolatutkimus](http://www.yso.fi/onto/ysa/Y203845) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "luolailu" 

#### Perustelut ehdotukselle   

Näyttää olevan suhteellisen paljon käytetty ilmaisu samalle asialle 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by satuniininen** [comment]
Luolailu lienee enemmänkin retkeilyä luolissa, joten se ei aivan vertaudu speleologiaan, joka on kuitenkin ihan tutkimustoimintaa.

https://retkipaikka.fi/luolan-etsijan-abc/

**Comment by YSA-kokous** [comment]
Ei lisätä
