### ISSUE TITLE
liitolento

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5699]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liitolento](http://www.yso.fi/onto/ysa/Y103154) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana KT-muodoksi asiasanalle "purjelento" 

#### Perustelut ehdotukselle   

Purjelento harrastetaan purjelentokoneella eli liitokoneella eli purjekoneella, mikäli suomenkieliseen Wikipediaan on luottaminen [https://fi.wikipedia.org/wiki/Purjelentokone]. Mutta millä sitten harrastetaan liitolentoa eli mikä itsenäinen se sitten on? Jokin hiuksenhieno ero purjelennolla ja liitolennolla saattaa olla, mutta nähdäkseni kovin epämääräinen, etteikö lajeja voisi pitää yhden asiasanan asiana [http://nlk.fi/purjelennosta/]. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Wikipediasta ja vähän muualtakin saa sen käsityksen että liitolento on purjelennon edeltäjälaji, jossa vain kone hilattiin jollain menetelmällä ilmaan ja se liiti alas. Jos ei joku perehtyneempi vastusta niin voi ne varmaankin yhdistää.
