### ISSUE TITLE
tammi (peli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5700]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tammi (peli) 

#### Ehdotettu termi englanniksi   

draughts 

#### Ehdotettu termi ruotsiksi   

damspel 

#### Vaihtoehtoiset termit ja ilmaisut   

daamien peli 
tammipeli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lautapelit](http://www.yso.fi/onto/yso/p2758) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85022828> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Tammi_(peli) 
Suomenkielinen Wikisanakirja : https://fi.wiktionary.org/wiki/tammipeli 

#### Tarkoitusta täsmentävä selite   

. . 

#### Perustelut ehdotukselle   

Yleisesti tunnettu lautapeli, jonka nimi on homonyymi ja siksi syytä erottaa samannimisestä puusta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [tammi (peli)](http://finto.fi/yse/fi/page/Y505700)

**Comment by mirmaid** [comment]
Puulajin osalta oma ehdotus: https://github.com/Finto-ehdotus/YSE/issues/5612

Tämä ok (en kyllä ole varma onko tuo KT daamien peli ihan välttämätön :smile:)

**Comment by YSA-kokous** [comment]
tammi (pelit)

**Comment by mariaforsen** [comment]
Sv. damspel ET dam

**Comment by mirmaid** [comment]
Voisi olla myös suomeksi tammipeli?

**Comment by YSA-kokous** [comment]
tammipeli
