### ISSUE TITLE
kotihoidontuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5709]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotihoidontuki](http://www.yso.fi/onto/ysa/Y96372) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ kotihoidon tuki 

#### Perustelut ehdotukselle   

http://www.kela.fi/kotihoidontuki
https://fi.wikipedia.org/wiki/Kotihoidon_tuki 

#### Ehdottaja   

JUPO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Molemmat muodot lähes yhtä käytettyjä (Google).

**Comment by AuHo22** [comment]
"Tavallista onkin, että yhdyssana ilmaisee tällaista vakiintunutta erityismerkitystä ja sanaliitto konkreettista asiaa"
https://www.kotus.fi/nyt/kolumnit/kieli-ikkuna_(1996_2010)/yhteen_vai_erilleen
