### ISSUE TITLE
ainun kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5712]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ainun kieli 

#### Ehdotettu termi englanniksi   

Ainu language 

#### Ehdotettu termi ruotsiksi   

ainu (språk) 

#### Vaihtoehtoiset termit ja ilmaisut   

ainu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[isolaattikielet](http://www.yso.fi/onto/yso/p23251) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85002564> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Ainun_kieli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [ainun kieli](http://finto.fi/yse/fi/page/Y505712)

**Comment by mariaforsen** [comment]
Sv. ainu (språk)
Allärs: ainu=ainut > ainu (folk)
