### ISSUE TITLE
hopeatyöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5713]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hopeatyöt](http://www.yso.fi/onto/ysa/Y95420) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Miksi hopeasepäntyöt-termi on ainoastaan referenssitermi. Minulle sallittu termi hopeatyöt tuo enemminkin mieleen jonkinlaisen harrastustoiminnan. Termi ei myöskään ole yhteismitallinen kultasepäntyöt-termin kanssa. 

#### Ehdotettu muutos   

Hopeatyöt --> hopeasepäntyöt 

#### Ehdottaja   

Outi Hintikka 

#### Ehdottajan organisaatio   

BTJ Finland Oy 

#### Ehdottajan sähköpostiosoite   

outi.hintikka@btj.fi

**Comment by mirmaid** [comment]
Aineistosta osassa on kyse nimenomaan omatekoisista hopeatöistä.

**Comment by mariaforsen** [comment]
Aina ei myöskään tiedä kuka on tehnyt hopeatyön ja hopeasepäntyöt antaa hyvin vähän googlessa. MOTissa ja Kielitoimiston sankirjassa on hopeatyö, ei hopeasepäntyö.

**Comment by YSA-kokous** [comment]
Ei muutosta
