### ISSUE TITLE
kerrosviljely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5715]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kerrosviljely 

#### Ehdotettu termi englanniksi   

vertical farming 

#### Ehdotettu termi ruotsiksi   

vertikalt jordbruk 

#### Vaihtoehtoiset termit ja ilmaisut   

monikerrosviljely 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viljelymenetelmät](http://www.yso.fi/onto/yso/p593) 

#### Assosiatiiviset (RT)   

[kasvihuoneviljely](http://www.yso.fi/onto/yso/p13312) 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p5911> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Vertical_farming 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Plant factory : an indoor vertical farming system for efficient quality food production 

#### Perustelut ehdotukselle   

Viljelymenetelmä tulee yleistymään ja aihetta käsitteleviä kirjoja julkaistaan. 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [kerrosviljely](http://finto.fi/yse/fi/page/Y505715)

**Comment by mariaforsen** [comment]
Sv. vertikal odling ET vertikalodling, vertikalt jordbruk, våningsodling
