### ISSUE TITLE
ryhmäkonsertot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5717]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ryhmäkonsertot](http://www.yso.fi/onto/ysa/Y214634) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "monisolistikonsertot" 

#### Perustelut ehdotukselle   

Ainakin Suomalaisen barokkiorkesterin johtaja Antti Tikkanen nimittää teosesittelyissään ryhmäkonserttoja monisolistikonsertoiksi; tällainen muusikkopiireissä tunnettu käsite olisi hyvä saada mukaan sanastoon (sekä YSAan että Suomalaisen lajityyppi- ja muotosanastoon). 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): kannatetaan
