### ISSUE TITLE
mastiffi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5718]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mastiffi 

#### Ehdotettu termi ruotsiksi   

mastiff 

#### Ehdotettu termi englanniksi   

English Mastiff 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Mastiffi_(koirarotu)
Mastiffi on erittäin suurikokoinen koirarotu. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

BMM ISSN 2489-5466 

#### Perustelut ehdotukselle   

Ei löydy YSAsta ja meillä on lehti, jossa käsitellään sekä bullmastiffeja että mastiffeja 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [mastiffi](http://finto.fi/yse/fi/page/Y505718)

**Comment by mariaforsen** [comment]
Sv. mastiff ET engelsk mastiff
