### ISSUE TITLE
rapukannat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5719]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rapukannat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.helsinki.fi/ruralia/julkaisut/pdf/Raportteja148.pdf 

#### Perustelut ehdotukselle   

Meillä on kalakannat yms, mutta tämä puuttuu. 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [rapukannat](http://finto.fi/yse/fi/page/Y505719)

**Comment by mariaforsen** [comment]
Sv. kräftbestånd ET kräftstammar
