### ISSUE TITLE
kahvipensaat (suku)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5720]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kahvipensaat (suku) 

#### Ehdotettu termi englanniksi   

coffee https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=35189#null 

#### Vaihtoehtoiset termit ja ilmaisut   

Coffea 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matarakasvit](http://www.yso.fi/onto/yso/p12221) 

#### Assosiatiiviset (RT)   

[kahvi](http://www.yso.fi/onto/yso/p4277) 
[nautintoainekasvit](http://www.yso.fi/onto/yso/p4862) 

#### Vastaava käsite muussa sanastossa   

LCSH : Coffee 
Kassu : kahvipensaat, https://finto.fi/kassu/fi/page/k42969 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan Helkan ja Arton kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. kirja: Where the wild coffee grows : ‡b the untold story of coffee from the cloud forests of Ethiopia to your cup (2017) 

#### Tarkoitusta täsmentävä selite   

Nyt YSAssa on kahvipensas, joka ehkä tarkoittaa  sukua "kahvipensaat" tai lajia "arabiankahvi"
Suvun viljeltyjä lajeja ovat mm.
arabiankahvi (Coffea arabica), käytetty Helkassa
kongonkahvi (Coffea canephora, aikaisemmin mm. nimellä Coffea robusta)
https://fi.wikipedia.org/wiki/Kahvipensaat 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [kahvipensaat (suku)](http://finto.fi/yse/fi/page/Y505720)

**Comment by mirmaid** [comment]
Muutetaan kahvipensas > kahvipensaat

**Comment by mariaforsen** [comment]
Sv. kaffesläktet ET kaffe (växtsläkte)

**Comment by YSA-kokous** [comment]
Muutetaan
