### ISSUE TITLE
Westfalen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5721]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Westfalen 

#### Ehdotettu termi englanniksi   

Westphalia 

#### Ehdotettu termi ruotsiksi   

Westfalen 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/n80106958 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.209924 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Westfalen](http://finto.fi/yse/fi/page/Y505721)

**Comment by mirmaid** [comment]
Nykyisen osavaltion nimi on Nordrhein-Westfalen. Julkaisu käsittelee 1400-lukua.

_Previous to the formation of Westphalia as a province of Prussia and later state part of North Rhine-Westphalia, the term “Westphalia” was applied to different territories of different sizes such as a part of the ancient Duchy of Saxony, the Duchy of Westphalia or the Kingdom of Westphalia._ https://en.wikipedia.org/wiki/Westphalia
