### ISSUE TITLE
abstrakti taide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5722]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[abstrakti taide](http://www.yso.fi/onto/ysa/Y94509) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "ei-esittävä taide" ja "non-objektiivinen taide" 

#### Perustelut ehdotukselle   

Abstrakti taide tunnetaan myös näillä käsittellä (ks. osalta esim. https://fi.wikipedia.org/wiki/Abstrakti_taide), ja olisi suotavaa, että ne viitaisivat sanastossa vahvistettuun termiin. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by tpalonen** [comment]
Kannatan. Myös Kiasman sivuilta löytyvä Nykytaiteen sanasto mainitsee ei-esittävän taiteen abstraktin taiteen synonyymina. http://kiasma.fi/kokoelmat/nykytaiteen-sanasto/
