### ISSUE TITLE
Lausitz

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5728]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Lausitz 

#### Ehdotettu termi ruotsiksi   

Lausitz 

#### Ehdotettu termi englanniksi   

Lusatia 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85078952 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Lausitz 
Ruotsinkielinen Wikipedia : https://sv.wikipedia.org/wiki/Lausitz 

#### Perustelut ehdotukselle   

Tarvitaan Lausitzin eri alueet kattava termi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Lausitz](http://finto.fi/yse/fi/page/Y505728)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon. Yläkäsitteeksi Saksa ja Puola. Ei sulkutarkennetta.
