### ISSUE TITLE
laattakirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5729]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laattakirjat 

#### Ehdotettu termi englanniksi   

block books 

#### Ehdotettu termi ruotsiksi   

blockböcker 

#### Vaihtoehtoiset termit ja ilmaisut   

blokkikirjat 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[harvinaiskirjat](http://www.yso.fi/onto/yso/p6528) 

#### Assosiatiiviset (RT)   

[puupiirros](http://www.yso.fi/onto/yso/p15822) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85014903> 
Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Nimitys:laattakirja> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [laattakirjat](http://finto.fi/yse/fi/page/Y505729)

**Comment by vthuhtala** [comment]
Määritelmä...

**Comment by jtuohini** [comment]
Niin, ja tämä myös SLM-sanastoon! (Vaikka Medelplanin puuaapinen onkin kateissa, lienee kirjastoissa näköispainoksia ulkomaisista laattakirjoista.)
