### ISSUE TITLE
OMS

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5730]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[OMS](http://www.yso.fi/onto/ysa/Y112327) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

OMS (tietokoneohjelmat) 

#### Perustelut ehdotukselle   

Ristiriita yhteisönimen 'Maailman terveysjärjestö' kielletyn muodon 'OMS' kanssa (OMS ranskankielinen lyhenne). 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by mirmaid** [comment]
Melindassa yksi julkaisu vuodelta 1988. _"HutBase consists of three software layers. The lowest layer, the Object Management System (OMS), is based on the Entity-Relationship model --"_ (lainaus kokousabstraktista "A Design Data Manager", https://www.researchgate.net/scientific-contributions/6652927_Kari_Alho).

Toisaalta onko tämä ongelma kun eivät ole samassa sanastossa?

**Comment by YSA-kokous** [comment]
Poistetaan sanastosta.
