### ISSUE TITLE
kenguruhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5731]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kenguruhoito 

#### Tarkoitusta täsmentävä selite   

Kenguruhoidolla tarkoitetaan ennenaikaisesti syntyneen vauvan hoitamista suunnitelmallisesti ja säännöllisesti vaippasiltaan ihokontaktissa äidin, isän tai muun perheen määrittelemän henkilön paljaalla rinnalla tukisidoksella tuettuna. 

#### Perustelut ehdotukselle   

Vakiintunut käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hoitotiede 4/2016 :  Keskosen kenguruhoito äitien kokemana http://elektra.helsinki.fi/se/h/0786-5686/28/4/keskosen.pdf 

**Ehdottajan nimi:** Silja Ojala 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** silja.ojala@helsinki.fi **Termiehdotus Fintossa:** [kenguruhoito](http://finto.fi/yse/fi/page/Y505731)

**Comment by ilona-x** [comment]
FinMeSH: kenguruhoito http://finto.fi/mesh/fi/page/D060127

käytetty Melindassa 4 kertaa

**Comment by mariaforsen** [comment]
Sv. kängurumetoden ET känguruvård, hud-mot-hudvård, hudnära vård
