### ISSUE TITLE
värjääjät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5733]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

värjääjät 

#### Ehdotettu termi ruotsiksi   

färgare 

#### Ehdotettu termi englanniksi   

dyers 

#### Vaihtoehtoiset termit ja ilmaisut   

värjärimestarit 
värjärit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käsityöläiset](http://www.yso.fi/onto/yso/p1541) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh98002460> 

#### Perustelut ehdotukselle   

Ammattiryhmä, jonka edustajia oli Suomessa paljon ja jota käsittelevää aineistoa löytyy sitäkin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://digi.kansalliskirjasto.fi/sanomalehti/binding/882514/articles/2638628?page=4 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [värjääjät](http://finto.fi/yse/fi/page/Y505733)

**Comment by mariaforsen** [comment]
Myös SAOssa färgare.
