### ISSUE TITLE
taikasauvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5734]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taikasauvat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Peterson: Harry Potter : maaginen maailma : taikasauva-arkisto  978-952-321-548-1 

#### Perustelut ehdotukselle   

Kirja käsittelee elokuvatarpeistoa ja pelkästään H.Potter-elokuvien taikasauvoja 

**Ehdottajan nimi:** Kaija Karjalainen 
**Ehdottajan organisaatio:** BTJ Finland 
**Ehdottajan sähköpostiosoite:** kaija.karjalainen@btj.fi **Termiehdotus Fintossa:** [taikasauvat](http://finto.fi/yse/fi/page/Y505734)

**Comment by mirmaid** [comment]
Löytyy LCSH:stakin
