### ISSUE TITLE
laki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5735]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[laki](http://www.yso.fi/onto/ysa/Y161728) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ lait 

#### Perustelut ehdotukselle   

Erottelu yksikön ja monikon välillä ei ole toimiva. Käytännössä on mahdollista hakea pelkällä laki-termillä vain selaushaussa (suurin osa viitteistä normaalissa asiasanahaussa ovat tyyppiä laki julkisista hankinnoista jne.), eikä silloinkaan termiä ole käytetty nimenomaan lakia ilmiönä/järjestelmänä käsittelevistä teoksista, vaan monissa tapauksissa monikollinen termi olisi vähintään yhtä hyvä. Hakijan kannalta tilanne on epäselvä. 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Myös SAOssa on vain "lagar".

**Comment by YSA-kokous** [comment]
lait
