### ISSUE TITLE
vedenväri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5736]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vedenväri 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Vedenv%C3%A4ri 

#### Perustelut ehdotukselle   

Tähän soveltuu huonosti monikollinen värit, ehdotettu väri-termin poistoa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Laboratorioiden välinen pätevyyskoe 12/2014 : alkaliniteetti, ravinteet, pH, sähkönjohtavuus ja väri jätevesistä 

**Ehdottajan nimi:** Mirja Anttila 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [vedenväri](http://finto.fi/yse/fi/page/Y505736)

**Comment by mariaforsen** [comment]
Sv. vattnets färg ET färgtal

**Comment by mariaforsen** [comment]
Olisiko suomeksikin KT väriluku?

**Comment by mirmaid** [comment]
KT väriluku
