### ISSUE TITLE
teatteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5737]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teatteri](http://www.yso.fi/onto/ysa/Y99340) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Teatterit ja teatterit tarvitsevat tarkenteet: esim. teatteri (taiteet) ja teatterit (organisaatiot). Sama koskee pareja nukketeatteri/-teatterit ja musiikkiteatteri/-teatterit. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by jtuohini** [comment]
Eikö olisi helpointa muuttaa nykyinen termi **teatteri** muotoon **teatteritaide**, niin vältyttäisiin kielellisesti varsin kököiltä sulkutarkenteilta?

**Comment by mariaforsen** [comment]
Sanastossa myös teatterirakennukset, joten vaatiiko "teatterit" tarkennetta miten vain?

**Comment by mirmaid** [comment]
^ Vaatii joka tapauksessa. 

_Teatteritaide_ on terminä ok, mutta _nukketeatteritaide_ ja varsinkaan _musiikkiteatteritaide_ eivät taida olla vakiintuneet käyttöön samalla tavalla. Myös teatteritaiteen suhteen tilanne on sama kuin _elokuvataide_-termin kohdalla, eli termiä teatteri on käytetty laajemmin viittaamaan koko "skeneen".

**Comment by OutiHintikka** [comment]
Itselleni teatteri on taidemuoto, johon toki voidaan laittaa termin jatkoksi termi "taide". En myöskään näe ongelmallisena sitä, että nukketeatteri ja musiikkiteatteri jäisivät ilman taide-liitettä, vaikka yläkäsitteessä se olisi. Teatterit tarkoittavat  organisaatioita esim. teatteriryhmiä. Teatterirakennukset on kokonaan eri juttu.

**Comment by YSA-kokous** [comment]
nukketeatteri (taiteet)
musiikkiteatteri (taiteet)
teatteritaide
teatterit (organisaatiot)
