### ISSUE TITLE
veneluiskat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5738]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

veneluiskat 

#### Vaihtoehtoiset termit ja ilmaisut   

laskuluiskat, veneenlaskuluiskat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-314-309-8 

#### Perustelut ehdotukselle   

Veneen laskupaikka veteen. "Veneiden vesille pääsyn turvaamiseksi Pohjois-
Karjalan vesistöalueille on rakennettu eritasoisia veneenlaskuluiskia
kaikkiaan noin 100 kpl eri puolille
maakunnan järvi- ja jokialueita." 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [veneluiskat](http://finto.fi/yse/fi/page/Y505738)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Veneenlaskupaikka

**Comment by mariaforsen** [comment]
Sv. båtramper
