### ISSUE TITLE
lääkitysturvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5739]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lääkitysturvallisuus 

#### Ehdotettu termi englanniksi   

medication safety 

#### Ehdotettu yläkäsite YSOssa (LT)   

[potilasturvallisuus](http://www.yso.fi/onto/yso/p7348) 

#### Assosiatiiviset (RT)   

[lääkehoito](http://www.yso.fi/onto/yso/p10851) 

#### Tarkoitusta täsmentävä selite   

THL:n sivuilta: Potilasturvallisuuteen kuuluu hoidon turvallisuus, lääkehoidon turvallisuus sekä lääkinnällisten laitteiden laiteturvallisuus. ...  Lääkehoidon turvallisuus voidaan jakaa lääkitysturvallisuuteen ja lääketurvallisuuteen.
Lääkitysturvallisuus tarkoittaa lääkkeiden käyttöön liittyvää turvallisuutta. Se kattaa terveydenhuollossa toimivien yksilöiden ja organisaation periaatteet ja toiminnot, joiden tarkoituksena on varmistaa potilaan saaman lääkehoidon turvallisuus. Toimenpiteet lääkkeiden käyttöön liittyvien haittatapahtumien ehkäisemiseksi, välttämiseksi ja korjaamiseksi ovat osa lääkitysturvallisuutta.
https://www.thl.fi/fi/web/sote-uudistus/palvelujen-tuottaminen/potilasturvallisuus 

#### Perustelut ehdotukselle   

Dosis-lehdessä (farmasia) on ollut tänä vuonna useita artikkeleita, joiden kuvailuun käsitettä tarvittaisiin. Googlella noin 100 osumaa. Sanahaulla "lääkitysturvallis?" löytyy Artosta 47 viitettä, Melindasta 19 viitettä.
https://dosis.fi/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto ja Helka 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [lääkitysturvallisuus](http://finto.fi/yse/fi/page/Y505739)

**Comment by PaiviLipsanen** [comment]
Lääke- ja lääkitysturvallisuus

Iso osa potilaan turvallista ja asianmukaista hoitoa on lääkehoidon turvallisuus. Turvallinen lääkehoito koostuu lääketurvallisuudesta ja lääkitysturvallisuudesta.

Lääkkeen farmakologisten ominaisuuksien ja vaikutusten tunteminen on osa lääketurvallisuutta. Tämän lisäksi lääkkeen laadukas valmistusprosessi, lääkkeen pakkaaminen ja merkitseminen sekä lääkkeen tehon ja turvallisuuden arviointi kuuluvat lääketurvallisuuteen. Lääketurvallisuutta valvoo Lääkealan turvallisuus- ja kehittämiskeskus Fimea mm. myöntäessään myyntilupia ja valtakunnallisen haittavaikutusrekisterin kautta. Myös lääkkeen valmistajalla on vastuu valmisteidensa turvallisuuden seurannasta.

Lääkkeiden asianmukainen ja oikea käyttö sekä lääkehoidon toteuttaminen liittyvät puolestaan lääkitysturvallisuuteen. Lääkkeen käyttöön liittyvään turvallisuuteen kuuluvat terveydenhuollon toimintayksiköiden ja organisaatioiden toiminta, säännöt ja periaatteet. Lääkitysturvallisuutta voidaan kehittää esim. lääkkeiden käyttöön liittyvien haittatapahtuminen/poikkeamien seurannalla. Seuranta voi olla manuaalista tai seurannassa voi käyttää valtakunnallista haittatapahtumien seurantaan suunniteltua atk-työkalua, HaiPro:a. Seurannasta ei ole hyötyä ellei lääkityspoikkeamia pyritä estämään, välttämään tai korjaamaan uusilla toimintatavoilla tai ohjeistuksilla.

Lääketurvallisuus on helppo erottaa lääkitysturvallisuudesta. Lääketurvallisuus liittyy aina itse tuotteeseen tai lääkeaineeseen kun taas lääkitysturvallisuus liittyy lääkehoidon toteuttajien inhimilliseen toimintaan ja toimintayksikkökohtaisen prosessin virheettömyyteen.

http://www.kliinisenfarmasianseura.fi/kliininen-farmasia/laake-ja-laakitysturvallisuus/

Ehdotan, että otetaan YSAan sekä lääketurvallisuus (aikaisemmin tehty ehdotus) että lääkitysturvallisuus. Molempia tarvitaan farmasian aineistojen kuvailuun.

**Comment by mariaforsen** [comment]
Sv. mahdollisesti medicineringssäkerhet, säker läkemedelsbehandling (suomessa) ? Entä suomeksi "turvallinen lääkehoito"?

**Comment by mirmaid** [comment]
Näiden ero on varmaan lääkealaa/terveydenhuoltoa hyvin tunteville selvä, mutta aika hienojakoinen tavalliselle kuvailijalle.

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2225

**Comment by ilona-x** [comment]
Molemmat löytyvät Hoidokki-sanastosta
http://www.hoidokki.fi/index_fin.html
Hoidokin määritelmä lääkitysturvallisuudelle:

Lääkkeiden käyttöön liittyvä turvallisuus, joka kattaa terveydenhuollossa toimivien yksilöiden organisaation periaatteet ja toiminnot, joiden tarkoituksena on varmistaa lääkehoidon turvallisuus sekä suojata potilasta vahingoittumasta. Lääkitysturvallisuus käsittää toimenpiteitä lääkkeiden käyttöön liittyvien haittatapahtumien ehkäisemiseksi, välttämiseksi ja korjaamiseksi. (Potilas- ja lääkehoidon turvallisuussanasto. Stakes ja lääkehoidon kehittämiskeskus Rohto. Stakes, Työpapereita 28/2006)

**Comment by mariaforsen** [comment]
Sv. medicineringssäkerhet ET säker läkemedelsbehandling
