### ISSUE TITLE
teknorock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5740]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teknorock](http://www.yso.fi/onto/ysa/Y214691) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytettäväksi termiksi krautrock. Teknorock joko pois kokonaan tai ohjaustermiksi. 

#### Perustelut ehdotukselle   

Termin määritelmä on seuraava: "1970-luvulla lähinnä Saksassa kehittynyt rock-tyyli ("Krautrock"), jossa oli keskeinen asema konemaisella rytmillä ja varhaisilla syntetisaattoreilla (esimerkiksi Kraftwerk-yhtye)."

Suomenkielisessä musiikkidiskurssissa kyseistä termiä ei kuitenkaan käytetä lainkaan, eikä varsinkaan tässä merkityksessä. Esim. Google-haku osoittaa, että termi on suomalaisessa kielenkäytössä hyvin harvinainen. Suomessa käytetään nimenomaan termiä "krautrock": Soundi-lehden verkkosivuilla krautrock-termiä on käytetty 80 kertaa, Rumban sivuilla 94 kertaa. Teknorock ei esiinny kummallakaan em. sivulla kertaakaan. Myös Ylen verkkosivut käyttävät krautrock-termiä viljavasti eikä teknorock esiinny yle.fi:n leipäteksteissä kertaakaan. Yle on jopa käyttänyt kuvailuun Freebasen krautrock-termiä, vaikka heillä pääsääntöisesti käytetään kuvailussa KOKO-ontologiaa, josta tämä MUSA-termi teknorock kyllä löytyisi.
https://yle.fi/aihe/termi/freebase/m01pfpt/krautrock

Teknorock-termi herättää lähinnä aivan toisenlaisia mielleyhtymiä jonkinlaisesta technon ja rockin yhdistelmästä. Vrt. ilmeisesti tuorein kotimainen teknorock-termin Google-esiintymä vuodelta 2013 Nuorgam-nettilehdestä, jossa puhutaan Neumannista (Dingo) eikä kyse tässä tapauksessa suinkaan ole krautrockista: "Kahden devalvaatiopennin tunkkainen teknorock-soundi on alun perin Kentin peruja, mutta henkisesti enemmän velkaa Uniklubille, Hanna Pakariselle ja Happoradiolle." Krautrock on genrenä ja terminä suosittu, joten toivoisin, että asia korjataan mahdollisimman pian. Ylen Freebase-esimerkki osoittaa, että teknorock-termiä selvästi vieroksutaan, mikä on haitallista kuvailulle. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by tpalonen** [comment]
Ohjaustermi "Krautrock" on tällä hetkellä isolla kirjoitettu. Alkukirjain kannattaisi korjata pieneksi. Vrt. esim. edellä mainitut Rumba, Soundi ja Yle, jotka kirjoittavat termin pienellä.

**Comment by asormune** [comment]
Kirjasto.fi -keksusteluista 21.4.2016 (kirjoittaja: hautalintu) löytyy perusteluja asialle:
...
Teknorock on ehkä MUSA:n vanhanaikaisin käsite. Itse olen aina kutsunut tätä musiikkia krautrockiksi, enkä ole kuullut kenenkään tarkoittavan teknorockilla tuota tyyliä. MUSA:ssa sanotaan, että sanaa ”ei käytetä myöhempien aikojen teknomusiikin kuvaamiseen”, mutta oman kokemukseni mukaan termiä käytetään nykyään vain ja ainoastaan tuosta musiikista, eli teknosta vaikutteita ottaneesta rockista joka oli muodissa 1990-luvulla.

Ymmärrän miksi ”teknorockilla” on korvattu brittimedian 1970-luvulla keksimä puolirasistinen ”krautrock”-termi, mutta musiikin tekijät ja fanittajat ovat itsekin omaksuneet sen oikeaksi sanaksi kuvaamaan tätä musiikkia (Faustilla on Krautrock-niminen biisikin). Oman tietämykseni mukaan vain tuo sana välittää asiakkaille sen mitä tässä tarkoitetaan. Esim. PIKI-kirjastojen molemmissa tyyliä käsittelevissä kirjoissa tuo sana on näkyvällä paikalla: Krautrock : cosmic rock and its legacy ja Future days : Krautrock and the building of modern Germany.

Oma ongelmansa ovat ns. Berliinin koulukunnan artistit kuten Tangerine Dream ja Klaus Schulze, joista on vaikea määritellä ovatko ne "teknorockia", progressiivista rockia vai epämääräisesti määriteltyä elektronista pop(ulaari)musiikkia. Heidän uransa on alkanut krautrock-skenestä, samoin kuin Kraftwerkillä, mutta valtaosa heidän tuotannostaan on niin perinpohjaisen elektronista ja rock-perinteelle vierasta, että sen kutsuminen tekno-, kraut- tai miksikään rockiksi on kyseenalaista. Englanninkielisessä maailmassa käytetään usein termiä ”progressive electronic” ja tietyllä tapaa tämän tyylin sisällyttäminen uuteen YKL-luokkaan 78.89113 Progressiivinen rock onkin perusteltua, rock-sanasta huolimatta.
..

**Comment by tpalonen** [comment]
Itse en ole koskaan mieltänyt krautrock-termiä negatiivisenä, vaan täysin neutraalina terminä, jota kaikki kielialueesta riippumatta nykyisin käyttävät. Pieni opiskelu tosin opetti minullekin, että termi on alun alkaen ollut humoristinen, mutta kuten Wikipediassa todetaan: "West Germany's music press initially used "krautrock" as a pejorative, but the term lost its stigma after the music gained success in Britain."

Sellaisesta Tangerine Dreamin, Klaus Schulzen, Harmonian, Moebiuksen ja kumppanien syntetisaattoripohjaisesta musiikista, joka on sukua ambientille ja new age -musiikille eikä rakennu tasainen rumpubiitin varaan kuten krautrock tyypillisesti, näkee käytettävän myös termiä "Kosmische Musik". Termi on melko yleinen nykyisin englanninkielisissä verkkomedioissa, mutta on tosin aika lailla päällekkäinen krautrockin kanssa.
Ks. esim. https://daily.bandcamp.com/2017/06/28/dieter-moebius-feature/
https://thevinylfactory.com/features/the-sound-of-moderne-kosmische-musik-10-artists-pick-their-favourite-tracks/

**Comment by TommiViitamies** [comment]
Allekirjoitan sen, että teknorock on terminä vanhentunut ja ehkä alun perinkin vähintäänkin epätarkasti määritelty. Ongelmana tässä ehdotuksessa kuitenkin on mm., että sitä on tietokannoissa käytetty eri merkityksessä kuin MUSAn määritelmä linjaa, joten ehdotettu termin vaihtaminen saisi aikaan melkoista sekaannusta tietokannoissa. Parempi ratkaisu olisi ehkä: luodaan uusi termi krautrock, muodostetaan sen määritelmä soveltaen nykyistä teknorockin määritelmää ja muokataan teknorockin määritelmä termin nykykäyttöä kuvaavammaksi.

**Comment by tpalonen** [comment]
Haluan vielä jankata, koska krautrockissakin on kyse saman riffin jankkaamisesta. :) Löysin yhteensä viisi suomenkielistä Google-hittiä, joissa ei ollut kyse MUSA-asiasanasta. Eli jos tehdään, kuten viimeisin kommentti ehdottaa, ollaan hyvin lähellä tilannetta, että sanastossa on käsite ja termi (teknorock), jolla ei ole vastinetta sanaston ulkopuolisessa maailmassa. Ks. issuen alussa mainitut viittaukset kotimaiseen musiikkimediaan. Tässä ei siis täyty kirjallisuustakuu (literary warrant) kuten kontrolloidun sanaston termien yhteydessä pitäisi. Vrt. ANSI/NISO Z39.19-2010R määritelmä kirjallisuustakuulle: "Justification for the representation of a concept in an indexing language or for the selection of a preferred term, because of its _frequent occurrence in the literature._"

**Comment by TommiViitamies** [comment]
Kommentistani jäi puuttumaan teknorock-termin säilyttämisen perusteluna se, että ratkaisu olisi väliaikainen. Lopullinen ratkaisu voisi olla joko termistä luopuiminen TAI ehkä mieluummin sen korvaaminen jollain paremmalla. Esim. tällainen käsite löytyy: https://en.wikipedia.org/wiki/Electronic_rock. Vastaava suomenkielinen artikkeli https://fi.wikipedia.org/wiki/Elektroninen_rock muuten vahvistaa väitettä, että krautrock ei ole synonyymi tälle, vaan pikemminkin sen alalaji.

**Comment by tpalonen** [comment]
Muuten hyvä, mutta en suosittele krautrockin yläkäsitteeksi elektronista rockia (RT:ksi se toki sopisi), koska a) elektroninen rock on käsitteenä epämääräinen. Kaikki rockhan on elektronista. Ja b) syntetisaattorit (jotka kaiketi elektronisessa musiikissa ovat asian pihvi) eivät ole välttämätön elementti krautrockissa. Vrt. esim. Wikipedian määritelmä: "Krautrock merges elements of psychedelic rock, the avant-garde, electronic music, funk, improvisational jazz and world music styles, and expands on the type of musical explorations associated with art rock and progressive rock. Critic Simon Reynolds described the style as "where the over-reaching ambition and untethered freakitude of late '60s acid rock is checked and galvanised by a proto-punk minimalism ... music of immense scale that miraculously avoided prog-rock's bombastics.""

**Comment by TommiViitamies** [comment]
Katerinan tuossa yllä lupaama Muusan ehdotus elektronisen rockin (ent. teknorock) määritelmäksi:

1960-luvun lopulla alkunsa saanut elektronisen musiikin keinoja käyttävä rock-suuntaus.

Tommi Viitamies ja Jaska Järvilehto

**Comment by tpalonen** [comment]
Tapani muuttaa YSAssa teknorockin muotoon elektroninen rock ja ohjaustermiksi teknorock. Ja luo uuden asiasana-auktoriteetin krautrock. @tpalonen laatii krautrockille määritelmän.

**Comment by mirmaid** [comment]
^ Eli krautrockin LT:ksi päätettiin kuitenkin _elektroninen rock_? Määritelmä puuttuu vielä.

**Comment by TommiViitamies** [comment]
Ei taida olla päätetty, että krautrockin LT olisi elektroninen rock...
