### ISSUE TITLE
Napapiirin hiihto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5741]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Napapiirin hiihto 

#### Ehdotettu termi englanniksi   

Arctic Circle Ski Marathon 

#### Ehdotettu yläkäsite YSOssa (LT)   

[urheilukilpailut](http://www.yso.fi/onto/yso/p1934) 
[liikuntatapahtumat](http://www.yso.fi/onto/yso/p1963) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Napapiirin_hiihto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Napapiirin Hiihto 60 vuotta : Jokivarsilta vaaroille 1956-2016 

#### Tarkoitusta täsmentävä selite   

http://www.napapiirinhiihto.fi/ 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@gmail.com **Termiehdotus Fintossa:** [Napapiirin hiihto](http://finto.fi/yse/fi/page/Y505741)

**Comment by mariaforsen** [comment]
Sv. Napapiirin hiihto ET Polcirkelloppet
