### ISSUE TITLE
Värriön luonnonpuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5742]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Värriön luonnonpuisto 

#### Ehdotettu termi englanniksi   

Värriö Strict Nature Reserve 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/V%C3%A4rri%C3%B6n_luonnonpuisto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://julkaisut.metsa.fi/assets/pdf/lp/Csarja/c116.pdf 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [Värriön luonnonpuisto](http://finto.fi/yse/fi/page/Y505742)

**Comment by mariaforsen** [comment]
Sv. Värriö naturpark
