### ISSUE TITLE
yhteisrakentaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5743]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yhteisrakentaminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://julkaisut.valtioneuvosto.fi/handle/10024/78428 

#### Perustelut ehdotukselle   

Tätä on vaikea muuten ilmaista https://www.finlex.fi/fi/laki/alkup/2016/20160276 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [yhteisrakentaminen](http://finto.fi/yse/fi/page/Y505743)

**Comment by mirmaid** [comment]
Joskus käytetty myös ryhmärakennuttamisesta.

**Comment by mariaforsen** [comment]
Sv. sambyggnad
