### ISSUE TITLE
lasten kehitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5744]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lasten kehitys](http://www.yso.fi/onto/ysa/Y96759) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lapsen kehitys? vai kumpi? 

#### Perustelut ehdotukselle   

FinMeSh käyttää nyt termiä 'lapsen kehitys' (muuttunut 2016?), joka aiemmin oli YSAn käyttämä. Ja YSAn termi on ilmeisesti muuttunut myös 2016. Olisiko syytä tarkastella tätä uusiksi ja päivittää termi jompaan kumpaan ettei olisi kahta erilaista? Näitä ei ole kiva päivittää eessuntaassun tietokantaan. 

#### Ehdottaja   

Kukka-Maritta Taskinen 

#### Ehdottajan organisaatio   

Savonia-ammattikorkeakoulu 

#### Ehdottajan sähköpostiosoite   

kukka-maritta.taskinen@savonia.fi

**Comment by mirmaid** [comment]
YSAssa on muutoshistoriassa RDA-konversio v. 2016, mitään varsinaista päivitystä ei ole ainakaan 2001 Voyager-loadin jälkeen. FinMeSHissä tosiaan yksikkö - näissä vähän eri aspekti painottuu, mutta en osaa sanoa kumpi on parempi.

**Comment by mirmaid** [comment]
Mielipiteitä tähän?

**Comment by mariaforsen** [comment]
Allärs: "barnets utveckling", mutta SAOssa "barns utveckling" (jonka minäkin valitsisin)

**Comment by ilona-x** [comment]
Äänestäisin muotoa **"lapsen kehitys"** Googlella 110 000 osumaa (vs. "lasten kehitys" 15 100 osumaa)

**Comment by YSA-kokous** [comment]
lasten kehitys KÄ lapsen kehitys
