### ISSUE TITLE
transkribointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5745]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[transkribointi](http://www.yso.fi/onto/ysa/Y214706) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko tarpeen sulkutarkenne sekaannuksen välttämiseksi? Esim. (musiikki). 

#### Perustelut ehdotukselle   

YSAssa käsite liittyy vain musiikin alaan. Kuitenkin Kielitoimiston sanakirjan mukaan: transkriboida: 1. kiel. merkitä tarkekirjoituksella. 2. kiel. tavallisemmin: translitteroida. 3. mus. sovittaa.

Vrt. myös YSAn transkriptio (biologia) ja transkriptiot (musiikki). 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by ksornova** [comment]
Hei! Termi transkribointi kuuluu ainoastaan ryhmään 89 Musiikki. Sulkutarkenteelle ei liene tarvetta?

**Comment by jtuohini** [comment]
Ei voi olla tarvetta, kun termiin sisältyy määritelmä ja huomautus, jotka tuon ryhmän lisäksi ilmaisevat yksiselitteisesti, että liittyy vain ja ainoastaan musiikkiin. Toki termin yhteyteen voisi lisätä käyttäjää ohjaavan huomautuksen translitteroinnin yms. osalta muiden termien äärelle.

**Comment by jtuohini** [comment]
Mutta jos kuitenkin on huoli, että sanana "transkribointi" ymmärretään kaikesta huolimatta väärin, olisiko parempi vaihtaa asiasanaksi _nuotintaminen_, joka nyt on KT-muotona?

**Comment by asormune** [comment]
Tulisiko silloin myös funktiotermiin muutos?

**Comment by mariaforsen** [comment]
Allärs: transkribera (musik) voi tarkoittaa: överföra från ett slags notskrift till ett annat ; överflytta (musikstycke) från en instrumentbesättning till en annan
Nuotintaa sen sijaan olisi "förse med noter", eli merkityskenttä muuttuisi ainakin ruotsin osalta.

**Comment by asormune** [comment]
Transkribointi liittyy vahvemmin "blokkaus", eli nuotinnetaan (jollain järjestelmällä, kuulonvaraisesti) jokin sävelteos/esitys (yleensä tallenteelta). Nuotintaminen voi olla myös pelkkää "puhtaaksikirjoittamista" tai erilaiseen ulkoasuun muuttamista.

**Comment by ilonahei** [comment]
Allärsin määritelmästä muuten puuttuu juuri termin nykyään eniten käytetty merkitys, eli esitetyn musiikin tai äänitteen (kuulonvarainen) nuotintaminen.

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): emme kannata ehdotusta, ei nähdä tarpeellisena

**Comment by mariaforsen** [comment]
Allärsissa siis ei ole määritelmää.

**Comment by mirmaid** [comment]
Onko tässä suomen- ja ruotsinkielisillä termeillä erilainen kattavuus, jos suomeksi tarkoittaa myös nuotintamista mutta ruotsiksi ei?

**Comment by jtuohini** [comment]
Suomeksi tarkoittaa vain ja ainoastaan nuotintamista, ei siis "myös nuotintamista"! Esityskokoonpanon muuttaminen toiseksi kuvaillaan **[soitinnus](http://www.yso.fi/onto/ysa/Y104357)**- ja **[sovittaminen](http://www.yso.fi/onto/ysa/Y104358)**-asiasanoilla; teoksen uudelleennuotintamista yhdestä kirjoitustavasta toiseksi (esim. viivastonuottikirjoituksesta graafiseksi nuottikirjoitukseksi) taas ei ole huomioitu ollenkaan, kun tarvetta ei ole tainnut liiemmälti ilmetä.

**Comment by mirmaid** [comment]
Siinä tapauksessa ehdottamasi muutos muotoon _nuotintaminen_ (ja samoin ruotsinkielisen termin muutos) tuntuisi selkeimmältä vaihtoehdolta.

**Comment by YSA-kokous** [comment]
Palaa Muusan käsittelyyn.

**Comment by asormune** [comment]
YSAssa on nyt "transkriboinnin" tulokselle  termi transkriptiot (musiikki). Jos muutetaan termiksi nuotintaminen, tarvitaan toiminnan tulokselle uusi termi: nuotinnokset (?)

**Comment by jtuohini** [comment]
Anun nostama muoto varmaankin tarvitaan ennemmin vain SLM-terminä, koska kirjallisuuden kuvailussa luulisi riittävän itse ilmiön (nuotinnoksen laatimisen eli nuotintamisen) käsittely?

**Comment by mariaforsen** [comment]
Huom. nyt YSAssa litterointi=transkribering (språkvetenskap) ST(!) transkribointi=transkribering (musik). Tämä ei käy ainakaan ruotsiksi. Ja mihin YSAn litterointi oikein viittaa? Näin päätetty aikaisemmin kun käsite hyväksyttiin sanastoon: #4780

**Comment by tpalonen** [comment]
Otetaan tämä Muusan ja YSAn yhteiskokoukseen listalle.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7020

**Comment by YSA-kokous** [comment]
nuotintaminen KT transkribointi, RT litterointi

**Comment by mariaforsen** [comment]
Sv. transkribering (musik) ET notuppteckning
