### ISSUE TITLE
noduulit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5746]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[noduulit](http://www.yso.fi/onto/ysa/Y103533) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytettäväksi termiksi tai ohjaustermiksi nodulit. 

#### Perustelut ehdotukselle   

Google-haun perusteella noduuli on harvinainen termimuoto. Käsite viittaa YSAssa kaivannaisiin. Kuitenkin termimuoto noduli näyttää hieman yleisemmältä. Esim. Geologian tutkimuskeskus toteaa, että noduli on "pieni konkreetio tai pieni mineraalikasauma."

Huom! Noduli/noduuli tarkoittaa myös ainakin kahta muuta asiaa: lääketieteessä se tarkoittaa kyhmyä tai turpeamaa. Arkeologiassa merkitys on "työstämätön kiviraaka-ainekappale" (Tieteen termipankki). 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Tämä on vinkeä...noduli, joka on tai ei ole sama kuin konkretio, joka on tai ei ole sama kuin konkreetio :sweat_smile:...

Ehkä _nodulit (geologia)_?
