### ISSUE TITLE
riskisanat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5748]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

riskisanat 

#### Ehdotettu termi englanniksi   

false friends (alunp. ransk. faux amis) 

#### Ehdotettu termi ruotsiksi   

falska vänner 

#### Vaihtoehtoiset termit ja ilmaisut   

sekaannussanat 
petolliset ystävät 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sanat](http://www.yso.fi/onto/yso/p3291) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : Petolliset ystävät 
LCSH : ohjataan käyttämään Paronyms 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Tarkoitusta täsmentävä selite   

Kahden eri kielen sanoja tai sanontoja, jotka muistuttavat toisiaan ulkoisesti mutta tarkoittavat eri asioita. 

#### Perustelut ehdotukselle   

Melinda-haulla "false friends" ja "faux amis" tulee kymmeniä nimekkeitä, ja niistä useimmat käsittelevät riskisanoja. Täsmällistä asiasanaa ei kuitenkaan ole ollut tätä aihetta kuvaamaan. Pari kertaa riskisanaa on kuitenkin käytetty Melindassa asiasanana. Riskisana-termi esiintyy mm. tässä Kielikellon artikkelissa: http://www.kielikello.fi/index.php?mid=2&pid=11&aid=2852 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

False friends in learner corpora (ISBN 9783035108415) 

**Ehdottajan nimi:** Mikko Meriläinen 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mikko.merilainen@uef.fi **Termiehdotus Fintossa:** [riskisanat](http://finto.fi/yse/fi/page/Y505748)

**Comment by vthuhtala** [comment]
Mikä riski? Jos otetaan, niin olisiko parmpi Wikipedian vaihtoehto: sekaannussanat

**Comment by satuniininen** [comment]
Riskisanat on kielitoimiston käyttämä muoto:

**riskisana** kiel. eri kielten t. saman kielen murteiden sanoista, joilla on (lähes) sama äänne- t. kirjoitusasu mutta eri merkitys. Viron sana "piim" on suomen kielen kannalta riskisana.

**Comment by mariaforsen** [comment]
Sv. falska vänner (ord)

**Comment by YSA-kokous** [comment]
riskisanat KT sekaannussanat
