### ISSUE TITLE
käsineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5749]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[käsineet](http://www.yso.fi/onto/ysa/Y100895) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "hansikkaat" 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi 

#### Perustelut ehdotukselle   

Käsineitä nimitetään myös hansikkaiksi (ks. esim. <https://fi.wikipedia.org/wiki/K%C3%A4sine>), joten olisi suotavaa, että myös kyseisellä nimityksellä olisi mahdollista hakea näitä talvella niin kovin tarpeellisia asusteita käsittelevää aineistoa.

**Comment by mirmaid** [comment]
Entä sormikkaat? Kielitoimiston sanakirja: hansikas: _sormellinen (vars. nahka)käsine, sormikas._

Wikipedia: _Yleensä käsineellä tarkoitetaan sormikasta, jossa joka sormelle on oma osastonsa, erotuksena lapasista ja rukkasista eli kintaista, joissa vain peukalo on erillinen ja muut sormet kosketuksissa toisiinsa käsineen sisällä._

MAO-ontologiassa käsineillä on runsaasti alakäsitteitä, esim. _sormikkaat_ ja _rukkaset_. Myös YSAssa _käsineet_ ST _lapaset_.

**Comment by YSA-kokous** [comment]
KT sormikkaat, hansikkaat, ST lapaset pois tämän alta
