### ISSUE TITLE
suurennuskojeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5750]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suurennuskojeet](http://www.yso.fi/onto/ysa/Y107089) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "suurennuskoneet" 

#### Perustelut ehdotukselle   

"Suurennuskone" on suomenkielisessä Wikipediassa ensisijainena käytetty termi kyseiselle laitteelle (https://fi.wikipedia.org/wiki/Suurennuskone). 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Vaihdetaanko päätermi?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja tuntee vain suurennusko**n**een.
Melindassa vain 7 viitettä, joten nopea korjata, jos päätetään vaihtaa päätermi

**Comment by YSA-kokous** [comment]
Vaihdetaan
