### ISSUE TITLE
pintakuvanheittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5752]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pintakuvanheittimet 

#### Ehdotettu termi ruotsiksi   

episkoper 

#### Ehdotettu termi englanniksi   

opaque projectors 

#### Vaihtoehtoiset termit ja ilmaisut   

episkoopit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[projektorit](http://www.yso.fi/onto/yso/p7107) 

#### Vastaava käsite muussa sanastossa   

Englanninkielinen Wikipedia : https://en.wikipedia.org/wiki/Opaque_projector 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Tarkoitusta täsmentävä selite   

Laite, jonka avulla voidaan projisoida tasomaiset kuvat painotuotteista, piirrokset, pinnat yms. suurennettuna valkokankaalle tai muulle pystypinnalle yleisön nähtäväksi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Visuaaliset välineet / Harro Teiste // Kirjastojen audiovisuaalisen toiminnnan opas [jossa artikkelissa käytetty ensisijaisesti termiä "pintakuvanheitin"] 

#### Perustelut ehdotukselle   

Kyseistä laitetta täsmällisesti kuvaavaa käsitettä ei ole ennestään sanastossa; "projektorit" on turhan epätarkka. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [pintakuvanheittimet](http://finto.fi/yse/fi/page/Y505752)

**Comment by mirmaid** [comment]
_Episkooppi_ tuo enemmän viitteitä Googlella

**Comment by mariaforsen** [comment]
Sv. episkop ET balloptikon

**Comment by YSA-kokous** [comment]
episkoopit
