### ISSUE TITLE
itägermaaniset kielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5753]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

itägermaaniset kielet 

#### Ehdotettu termi ruotsiksi   

östgermanska språk 

#### Ehdotettu termi englanniksi   

East Germanic languages 

#### Ehdotettu yläkäsite YSOssa (LT)   

[germaaniset kielet](http://www.yso.fi/onto/yso/p3856) 

#### Alakäsitteet (RT)   

[gootin kieli](http://www.yso.fi/onto/yso/p17071) 

#### Vastaava käsite muussa sanastossa   

Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/It%C3%A4germaaniset_kielet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Martti Anhavan "Maailman kielet ja kielikunnat" -kirjassa omana ryhmänään (sis. gootti, länsigootti, itägootti, vandaali, gepidi, burgundi jne), samoin omana luokkanaan UDK:ssa (=114). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [itägermaaniset kielet](http://finto.fi/yse/fi/page/Y505753)

**Comment by mirmaid** [comment]
Ei viitteitä Melindassa. Samalla olisi varmaan syytä ottaa _länsigermaaniset kielet_, jos tämä otetaan.
