### ISSUE TITLE
ontologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5754]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ontologia](http://www.yso.fi/onto/ysa/Y97800) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "yleinen metafysiikka" 

#### Perustelut ehdotukselle   

Ainakin suomenkielisen Wikipedian (https://fi.wikipedia.org/wiki/Metafysiikka) mukaan "Yleinen metafysiikka (lat. metaphysica generalis) eli ontologia tutkii olevaa olevana, eli olevaisen perimmäistä olemusta." 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Ks. http://netn.fi/sites/www.netn.fi/files/netn021-25.pdf
_Jutilla ontologia samaistuu yleiseen metafysiikkaan, eli ontologia tutkii olevaa olevana. Muita kuvauksia
ontologialle ovat olevan kategoriat (s. 15) ja inhimillisen ymmärryksen periaatteet. Varsinkin Wolffilta lainattu jakso kuvaa parhaiten omaa käsitystäni ontologiasta: emme niinkään tarkastele olevaa, kuin sitä ymmärrystä, joka meillä olevasta on (s. 21). Tai tarvitaan vielä enemmän. Heideggeria seuraten, ei riitä että tutkimme olevaa olevana, olisi tutkittava olevaa olemisessaan. Jos Wolffin ontologiakäsityksen
siirtää olevan kategorioihin, niin emme niinkään puhu olevan kategorioista, vaan tavasta, jolla ymmärryksemme luokittelee olevaa. Taas Heideggeria seuraten, metafyysinen ajattelu kyllä tutkii olevaa
olevana, mutta ei valaise tätä ajattelua._

_Näin kuvattuna ontologia ei enää olekaan yleistä metafysiikkaa. Ero näiden välille voidaan poimia Jutin omasta tekstistä: ”Metafysiikka on tiede olevasta itsestään, olevasta olevana – ei siis olevasta sellaisena
kuin se esiintyy esimerkiksi havaintojemme kohteena tai ajatustemme tietyllä tavalla määrittelemänä.” (s. 14.)_
