### ISSUE TITLE
erityisherkkyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5755]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

erityisherkkyys 

#### Perustelut ehdotukselle   

Tätä aihetta on vaikeaa hakea tiskissä "sensitiivisyys"- lainasanalla. Termi tuntuu vakiintuneet yleiskieleen, joten se olisi perusteltua ottaa myös asiasanaksi. Katso esim. Anja Snellmanin teos Antautuminen. Viimeisimmät kirja-arvostelut puhuvat aiheesta suoraan termillä erityisherkkyys. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjojen 

**Ehdottajan nimi:** Salla Hyökki 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** salla.hyokki@tampere.fi **Termiehdotus Fintossa:** [erityisherkkyys](http://finto.fi/yse/fi/page/Y505755)

**Comment by mirmaid** [comment]
Olisiko parempi vaihtaa _sensitiivisyys_ > herkkyys? Ainakin _aistiyliherkkyys_ ja _ympäristöherkkyys_ ovat päällekkäisiä tämän erityisherkkyyden kanssa.

**Comment by ilona-x** [comment]
ehdotettu myös aiemmin:
https://github.com/Finto-ehdotus/YSE/issues/4280

**Comment by vthuhtala** [comment]
Määritelmä?

**Comment by mariaforsen** [comment]
Sv. högkänslighet

**Comment by ilona-x** [comment]
YSAssa sensitiivisyys vain psykologian ryhmässä, mutta Melindassa käytetty jonkin verran myös muissa yhteyksissä esim. mittauslaitteiden herkkyys.  Pitäisikö lisätä tarkenne (psykologia?), esim. LCSH Sensitivity (Personality trait)?

**Comment by YSA-kokous** [comment]
sensitiivisyys > herkkyys (psykologia)
