### ISSUE TITLE
leptospiroosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5756]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

leptospiroosi 

#### Ehdotettu termi englanniksi   

leptospirosis 

#### Ehdotettu termi ruotsiksi   

leptospiros 

#### Vaihtoehtoiset termit ja ilmaisut   

Weilin tauti (?) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[bakteeritaudit](http://www.yso.fi/onto/yso/p19293) 

#### Assosiatiiviset (RT)   

[eläintaudit](http://www.yso.fi/onto/yso/p47) 

#### Vastaava käsite muussa sanastossa   

MeSH-FinMeSH : <http://www.yso.fi/onto/mesh/D007922> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Evira: Leptospiroosi on Leptospira-bakteerisuvun aiheuttama kuumetauti. Tautia aiheuttaviin Leptospira-lajeihin kuuluu suuri joukko erilaisia serovareja. Tartuntaa voi esiintyä kaikilla nisäkäslajeilla, joskin tietyt serovarit ovat ominaisia tietyille eläinlajeille. Useimmat serovarit aiheuttavat myös ihmiselle vakavan oireiltaan influenssaa muistuttavan kuumetaudin.
https://www.evira.fi/elaimet/elainten-terveys-ja-elaintaudit/elaintaudit/usealle-elainlajille-yhteiset-taudit/leptospiroosi/
Weilin tauti lienee leptospiroosin muoto, ei siis tarkka synonyymi 

#### Perustelut ehdotukselle   

Sanahaku leptospir?: Artossa 16 tietueessa, Melindassa 60 tietueessa
Google leptospiroosi -> n. 200 osumaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto: Suomen eläinlääkärilehti 2017:9; Koiran leptospiroosi Suomessa ja naapurimaissa - kirjallisuuskatsaus ja kartoitus leptospiroosiepäilyistä Yliopistollisessa eläinsairaalassa 2006-2014 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [leptospiroosi](http://finto.fi/yse/fi/page/Y505756)

**Comment by FinMeSHienPaimentaja** [comment]
Terveysportin kautta Lääketieteen termit antaa:

leptospiroosi
leptospirosis la e, leptospiros ‑en r tarttuva keltatauti | eläimen virtsasta viemäriin tai vesistöön leviävän, ihohaavan kautta ihmiseen tarttuvan jonkin Leptospira interrogans ‑kannan aiheuttama (Suomessa harvinainen) infektiotauti, jossa voi esiintyä mm. aivo-, maksa-, munuais- tai sydänlihastulehduksia

leptospirosis icterohaemorrhagica icterohemorrhagic leptospirosis, Weil´s disease e, Weils sjukdom r Weilin tauti | vaikea leptospiroosi, joka voi aiheuttaa vahvan keltaisuuden (ikteruksen)

http://www.terveysportti.fi/sovellukset/sanakirjat/#/q//lte12435
