### ISSUE TITLE
luonnon analogia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5757]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luonnon analogia 

#### Ehdotettu termi englanniksi   

natural analogue 

#### Vaihtoehtoiset termit ja ilmaisut   

luonnonanalogia 

#### Perustelut ehdotukselle   

http://www.geologinenseura.fi/geologi-lehti/5-2011/kypros.pdf 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://hakku.gtk.fi/fi/reports/search?publication_id=20441 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [luonnon analogia](http://finto.fi/yse/fi/page/Y505757)

**Comment by mirmaid** [comment]
Eniten muodossa _luonnonanalogiat_.

**Comment by vthuhtala** [comment]
Maaritelmä puuttuu

**Comment by mariaforsen** [comment]
Sv. naturliga analogier ET naturanalogier

**Comment by mirmaid** [comment]
_Geologian sovelluksissa käsite analogia merkitsee inhimillisen toimenpiteen tai sen seurauksen samanlaisuutta luonnollisen geologisen ilmiön kanssa._ http://elektra.helsinki.fi/se/g/0046-5720/52/4-5/luonnona.pdf
