### ISSUE TITLE
antifeminismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5758]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

antifeminismi 

#### Ehdotettu termi ruotsiksi   

antifeminism 

#### Ehdotettu termi englanniksi   

antifeminism 

#### Assosiatiiviset (RT)   

[feminismi](http://www.yso.fi/onto/yso/p7254) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh96004456> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

Löytyy LCSH:sta, esiintyy Finnassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. https://helka.finna.fi/Record/helka.1986993 (tietueessa on käytetty YSA-käsitettä antifeminismi, mutta YSA:sta sitä ei löydy?) 

**Ehdottajan nimi:** Harri Ollikainen 
**Ehdottajan sähköpostiosoite:** harri.ollikainen@protonmail.com **Termiehdotus Fintossa:** [antifeminismi](http://finto.fi/yse/fi/page/Y505758)

**Comment by mariaforsen** [comment]
Sv. antifeminism
