### ISSUE TITLE
laki vesienhoidon ja merenhoidon järjestämisestä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5760]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laki vesienhoidon ja merenhoidon järjestämisestä 

#### Ehdotettu termi ruotsiksi   

lag om vattenvårds- och havsvårdsförvaltningen 

#### Vaihtoehtoiset termit ja ilmaisut   

vesienhoitolaki 

#### Perustelut ehdotukselle   

https://www.finlex.fi/fi/laki/ajantasa/2004/20041299 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-314-283-1 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [laki vesienhoidon ja merenhoidon järjestämisestä](http://finto.fi/yse/fi/page/Y505760)

**Comment by mariaforsen** [comment]
Sv. lag om vattenvårds- och havsvårdsförvaltningen
