### ISSUE TITLE
geologiset muodostumat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5761]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

geologiset muodostumat 

#### Perustelut ehdotukselle   

Geologisilla muodostumilla tarkoitetaan kallio- ja maaperässä olevia luonnon muodostumia ja rakenteita, jotka ovat syntyneet yleensä hyvin hitaiden erilaisten ja eri-ikäisten geologisten prosessien tuloksena. Geologisia muodostumia voidaan pitää ihmisen aikaskaalassa tarkasteltuna pysyvinä ja ainutkertaisina osina geologista kehityshistoriaa.
http://www.ymparisto.fi/geologisetmuodostumat

https://fi.wikipedia.org/wiki/Geologinen_muodostuma 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10138/156510 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [geologiset muodostumat](http://finto.fi/yse/fi/page/Y505761)

**Comment by mirmaid** [comment]
Onko sama kuin _pinnanmuodot_?

**Comment by mariaforsen** [comment]
Sv. geologiska formationer, landformer

**Comment by FinMeSHienPaimentaja** [comment]
Wikipedian mukaan on sama kuin (maan) "pinnanmuodot": "Geologinen muodostuma eli pinnanmuoto on Maapallon pintakerroksessa, kallio- tai maaperässä oleva luonnon aikaansaama muodostuma".

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by jarmosaarikko** [comment]
**Pinnanmuodot** on jo YSA.ssa. KT geologiset muodostumat, sillä sen alakäsitteet vastaavat tätä
wikipeidan määritelmä on hyvä ja kattava. (esim. tulivuoret, hiidenkirnut, dyynit, harjut jne.)  Englanniksi tuosta käytetään  "landforms"

**Comment by mariaforsen** [comment]
Myös #2043 Ruotsiksi ytform ei ole ihan sama asia kuin geologisk formation, ehkä ruotsiksi mieluummin vaihtaisimme sitten päätermiksi geologiska formationer. Mieluiten pitäisimme molemmat. 
Ks. myös http://www.ymparisto.fi/geologisetmuodostumat 
http://ykl.kirjastot.fi/fi-FI/sanat/?SearchWord=Geologiset+muodostumat

**Comment by ilona-x** [comment]
LCSH:
Formations (Geology) http://id.loc.gov/authorities/subjects/sh86003920
Landforms http://id.loc.gov/authorities/subjects/sh85074366

Melinda:
geologiset muodostumat x 1
glasifluviaaliset muodostumat x 2
geomorfologiset muodostumat x 1
periglasiaaliset muodostumat x 2
eoliset muodostumat x 1
muodostumat x 7 (kaikki viitteet geologiaa)
suprakrustiset muodostumat x 1
proterotsoiset muodostumat x 1
arkeiset muodostumat x 1
reunamuodostumat x 6
moreenimuodostumat x 2

Ehdottaisin näiden perusteella muotoa: **muodostumat (geologia)**

**Comment by FinMeSHienPaimentaja** [comment]
Muodostumat ok, se kattaa myös (pinnallisemmat) pinnanmuodot. (Minusta arkikielessä  pinnanmuodot voidaan ymmärtää pinnallisempina kuin muodostumat, olkoonkin, että Wikipedian mukaan niiden välille voitaisiin vetää yhtäläisyysmerkki).

**Comment by mariaforsen** [comment]
Sv. geologiska formationer tärkeämpi kuin nykyinen pinnanmuodot (jos täytyy valita vain yksi) ja ne eivät tosiaan ole aivan sama asia. Wikipedian väittämät eivät muutenkaan läheskään aina pidä paikkaansa.

**Comment by mariaforsen** [comment]
Sv. geologiska formationer ET formationer (geologi)
