### ISSUE TITLE
lintuvedet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5762]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lintuvedet](http://www.yso.fi/onto/ysa/Y156799) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Voisiko termit lintuvedet & lintuvesialueet yhdistää? Nyt huomautus: Nimitys käytössä vuodesta 2008 alkaen, aiemmat katso lintuvesialueet. 

#### Perustelut ehdotukselle   

Termiä lintuvesialueet käytetty Melindassa jonkin verran myös vuoden 2008 jälkeen julkaistujen teosten kuvailussa. 

#### Ehdottaja   

Ilona Lindfors 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

ilona.lindfors@helsinki.fi

**Comment by PaiviLipsanen** [comment]
AFOssa vain lintuvedet
