### ISSUE TITLE
elintarviketeollisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5766]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elintarviketeollisuus](http://www.yso.fi/onto/ysa/Y94986) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

altLabeliksi nautintoaineteollisuus @fi  njutningsmedelindustri @sv  stimulant industry @en 

#### Perustelut ehdotukselle   

käytetty Melindassa 40 kertaa.  Voisi olla omana terminään elintarviketeollisuuden linnalla, jos nautintoaineita ei voida rinnastaa elntarvikkeisiin. Tällöin osa  elintarviketeollisuuden alakäsitteistä olisi siirrettävä mukana: tupakkateollisuus,  juomateollisuus (?)    [alkoholi, kaakao, kahvi, tee, tupakka] 

#### Ehdottaja   

Jarmo Saarikko 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

jarmo.saarikko@helsinki.fi

**Comment by tpalonen** [comment]
Kannatan mieluummin nautintoaineteollisuuden ottamista sanastoon omana käsitteenään kuin lisäämistä elintarviketeollisuuden ohjaustermiksi. Ei ole ehkä tyypillisin elintarviketeollisuuden edustaja ja luulisin, että jos on tiedontarve näin spesifiin alaan niin haluttaisiin hakea omalla käsitteellä. Löytyyhän esim. juomateollisuus, makeisteollisuus ja keksiteollisuuskin omina käsitteinään.

**Comment by mariaforsen** [comment]
Sv. njutningsmedelsindustri käytetty (vähän) Suomessa

**Comment by satuniininen** [comment]
Jos otetaan niin mieluummin omanaan kuin elintarviketeollisuuden ohjausterminä, ks. tpalosen perustelu yllä.

En ehkä oikein näe tälle tarvetta, koska tarkempaa sanastoa on jo runsaasti: tupakkateollisuus, juomateollisuus, alkoholiteollisuus, panimoteollisuus jne.

**Comment by ilona-x** [comment]
Melindan viitteistä uusin vuodelta 1999
