### ISSUE TITLE
ooppera

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5767]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ooppera](http://www.yso.fi/onto/ysa/Y103771) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

oopperamusiikki (altLabel)   +  yläkäsitteen lisäys näyttämömusiikki 

#### Perustelut ehdotukselle   

- oopperamusiikki ei löydy nyt millään haulla, mutta monenlaiset muut musiikin muodot löytyvät.  
- YSO:ssa vastava oopperaa käsite on ooppera (taiteet) jonka yläkäsite on esittävät taiteet. 
- oopperamusiikin luonnollinen yläkäsite olisi näyttämömusiikki  / musiikki tarkoituksen mukaan, jonka alla on jo balettimusiikki sekä teatterimusiikki. 

#### Ehdottaja   

Jarmo Saarikko 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

jarmo.saarikko@helsinki.fi

**Comment by jtuohini** [comment]
"Oopperamusiikki" ei ole oma musiikinlajinsa siinä mielessä kuin vaikkapa rock, taidemusiikki tai edes näyttämömusiikki (joka ilmaisee musiikin käyttöyhteyden). Lisäksi YSAn asiasana **ooppera** nimenomaan ei viittaa vain musiikkiin (oopperoihin sävelteoksina), vaan koko taiteenlajiin, jossa yhdistyvät musiikki ja teatteri. Siksi "oopperamusiikki KÄ ooppera" olisi mahdoton, yhtä mahdoton kuin vaikkapa olisivat "kantaattimusiikki" tai "sonaattimusiikki" viittausmuotoina muihin YSA-asiasanoihin.

**Comment by jtuohini** [comment]
Ai niin, osuvampi KT-muoto olisi kenties _oopperataide_, joka sana löytyy googlaamallakin kohtuullisen monta kertaa (2 930 viitettä). Tai koko termin voisi vaihtaa tuoksi?

**Comment by ksornova** [comment]
Hei! YSOssa on "[ooppera (taiteet)](http://finto.fi/yso/fi/page/p13810)" ja LT esittävät taiteet

**Comment by ksornova** [comment]
Hei! YSOssa on tosiaan "[ooppera (taiteet)](http://finto.fi/yso/fi/page/p13810)" ja LT esittävät taiteet. Jos pitää valita, muutetaanko YSAssa olevaa termiä "ooppera" muotoon "ooppera (taiteet)" tai "oopperataide", ehkä jälkimmäinen tuntuisi paremmalta. Samalla voisi miettiä, onko syytä muuttaa YSOssa olevaa sirkus (taiteet) samalla kaavalla muotoon sirkustaide.

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): emme kannata ehdotusta, mutta ehdotetaan että
ooppera (taiteet) muutetaan mutooon "oopperataide"

**Comment by mirmaid** [comment]
Sanastoon jäisi siis _oopperat_ (LT sävellykset) ja _oopperataide_. Melindan viitteissä korjaus olisi tämän muutoksen jälkeen kuitenkin toisinaan _ooppera > oopperat_ paremmin kuin _ooppera > oopperataide_, usein varmaan molemmat.

**Comment by jtuohini** [comment]
Asia on juuri niin kuin Mirja kirjoittaa!
