### ISSUE TITLE
hallitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5768]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hallitukset](http://www.yso.fi/onto/ysa/Y95269) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa jaettu: hallitukset (julkinen hallinto) ja hallitukset (yhdistykset ja yritykset). Ratkaistava ristiriita sanastojen välillä ennen YSOon siirtymistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/381
https://github.com/NatLibFi/Finto-data/issues/384

**Comment by mirmaid** [comment]
hallitukset (yhdistykset ja yritykset) sv. styrelser
hallitukset (julkinen hallinto) sv. regeringar; tämän alakäsitteinä kuitenkin styrelser-päätteisiä

Ruotsiksi looginen jako olisi varmaankin valtion hallituksiin ja muihin. Tarkenteen keksiminen jälkimmäiselle on taas suomeksi vaikeaa.

Yksi (huono) vaihtoehto olisi jakaa _valtioiden hallitukset_ & _hallitukset_ ilman tarkennetta, ja yrittää ohjaustermein ja huomautuksella ohjata kuvailua. Toinen mahdollisuus on jakaa sulkutarkentein useampaan kuin kahteen, mutta on paljon organisaatiotyyppejä joilla voi olla hallitus; Kielitoimiston sanakirja: 4. yhdistyksen, yhtiön tms. toimeenpanoelin. _Osakeyhtiön, säätiön, puolueen hallitus._ Yksi mitä vielä mietin on jakaa _hallitukset (valtiot)_ ja _hallitukset (yhteisöt)_ ja toivoa että tämä jotenkin johtaisi oikeaan tulokseen vaikka jälkimmäinen tarkenne ei varsinaisesti sulje valtioita pois.

**Comment by mariaforsen** [comment]
Hierarkia myös korjattava, regeringar ei voi olla yläkäsite -styrelser-käsitteille.

**Comment by LeKorsu** [comment]
Peukku hallitukset (valtiot) ja hallitukset (yhteisöt) -vaihtoehdolle.

**Comment by YSA-kokous** [comment]
hallitukset (valtiot) ja hallitukset (yhteisöt) 
Määritelmät/käyttöhuomautukset.
