### ISSUE TITLE
puutavaranmittaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5769]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puutavaranmittaus 

#### Ehdotettu termi englanniksi   

scaling 

#### Ehdotettu termi ruotsiksi   

virkesmätning 

#### Vaihtoehtoiset termit ja ilmaisut   

timber measurement 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mittaus](http://www.yso.fi/onto/yso/p4794) 

#### Assosiatiiviset (RT)   

[metsänarviointi](http://www.yso.fi/onto/yso/p18894) 

#### Vastaava käsite muussa sanastossa   

LCSH : Forests and forestry--Measurement 
LCSH : <http://id.loc.gov/authorities/subjects/sh85050716> 

#### Perustelut ehdotukselle   

AFO-käsite:  http://www.yso.fi/onto/afo/p2545
Kts. myös Puutavaranmittaustoimikunta.  Tästä on myös Laki puutavaran mittauksesta  http://finlex.fi/fi/laki/alkup/2013/20130414   joka voisi olla yksilökäsitteenä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Käytetty Melindassa 153 kertaa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Tarkoitusta täsmentävä selite   

Tähän kuuluvat mm. hakkuukonemittaus, pinomittaus, pystymittaus 

**Ehdottajan nimi:** Jarmo Saarikko 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** jarmo.saarikko@helsinki.fi **Termiehdotus Fintossa:** [puutavaranmittaus](http://finto.fi/yse/fi/page/Y505769)

**Comment by satuniininen** [comment]
Englanniksi pelkkä **scaling** vaatii sulkutarkenteen. Voisiko mieluummin olla **log scaling**, kuten LSCH:ssa on ohjausterminä?

**Comment by mariaforsen** [comment]
Sv. virkesmätning
