### ISSUE TITLE
itsenäisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5770]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itsenäisyys](http://www.yso.fi/onto/ysa/Y95595) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa jaettu: itsenäisyys (valtiot ja yhteisöt) ja itsenäisyys (yksilöt). Ratkaistava ristiriita sanastojen välillä ennen YSOon siirtymistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5477
https://github.com/NatLibFi/Finto-data/issues/405

**Comment by mirmaid** [comment]
_Itsenäistyminen_-termi jaettu YSAssa tarkentein (psykologia) ja (valtiot). Ehdottaisin, että tässä jaettaisiin myös ainakin _itsenäisyys (valtiot)_ - voidaan myös tehdä tämä ensin ja tutkia sen jälkeen mikä soveltuu muihin tapauksiin (Melindassa 646 kertaa tietoaineistossa).

**Comment by mariaforsen** [comment]
Siinä tapauksessa sv. självständighet + tarkenne

**Comment by YSA-kokous** [comment]
itsenäisyys (valtiot)

Tutkitaan sen jälkeen muut.

**Comment by mariaforsen** [comment]
Melindassa myös paljon henkilöistä, sekä psykologinen että fyysisempikin itsenäisyys. Eikö niille sopisi itsenäisyys (yksilöt)? Näyttää olevan hyvin tarpeellinen ainakin.

**Comment by satuniininen** [comment]
Suurin osa **itsenäisyys (valtiot)** merkityksistä siivottu pois Melindasta.

Jäljelle jäävistä suurimpaan osaan sopisi **itsenäisyys (yksilöt)**. Jonkin verran käytetty myös kuvaamaan erilaisten organisaatiotoimijoiden tai valtiota pienempien alueiden itsenäisyyttä. Näissä tapauksissa voidaan ehkä  käyttää muuta sanastoa, esim, **suvereniteetti, riippumattomuus, autonomia, itsehallinto**

- Essays on auditor independence  
- Chance, order, change :the course of international law : general course on public international law  
- Towards the self-regulative university 
- The status of Hutt River Province (Western Australia) : a case study in international law  
- Keski-Pohjanmaa - suuntautumisen, yhtenäisyyden, erilaisten rajojen, alueellisen itsenäisyyden ja tunnustetun aseman ristitulessa

**Comment by mirmaid** [comment]
Onko tuo (yksilöt) paras tarkenne (muita mahdollisia varmaan myös ihmiset, henkilöt)?

**Comment by YSA-kokous** [comment]
itsenäisyys (yksilöt)
