### ISSUE TITLE
dekadenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5771]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dekadenssi](http://www.yso.fi/onto/ysa/Y117408) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa jaettu: dekadenssi (muutos) ja dekadenssi (tyylit). Ratkaistava ristiriita sanastojen välillä ennen YSOon siirtymistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Sanastossa on myös _rappio_. En löydä Melindasta muuta kuin kirjallisuuden ja taiteen yhteydessä sekä aatesuuntana (esim. _Lahti, Tuomas: Dekadenssi ja toiminta_). Onko jako tarpeellinen?

**Comment by mariaforsen** [comment]
SAOssakin vain taiteiden yhteydessä.

**Comment by AuHo22** [comment]
YSOssa dekadenssi (muutos) laitettu ao. ryhmiin - lieneekö tarvetta? Ainakin sosiologian yhteydessä voi käyttää termejä _rappio_ tai _hajoaminen_.

50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi 
60 Sosiologia. Sosiaalipsykologia 

https://sarastuslehti.com/2012/12/04/modernin-yhteiskunnan-rappio/

**Comment by krinay** [comment]
Myös kulttuurien tutkimuksen (antropologian ja perinnetieteiden) tarpeisiin riittää termi rappio. 

Kirjallisuuden suuntauksena dekadenssi on merkittävä, joten pitäisikö lisätä ryhmä 87 Kirjallisuus.

**Comment by YSA-kokous** [comment]
dekadenssi (muutos) uudelleenohjaus käsitteeseen rappio
