### ISSUE TITLE
joukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5772]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[joukot](http://www.yso.fi/onto/ysa/Y101955) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava/selkeytettävä. 

#### Perustelut ehdotukselle   

Sanastossa matemaattisena käsitteenä, mutta käytetty paljon sodankäyntiin liittyen. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by vthuhtala** [comment]
Sanastossa 'joukko-osastot' sotilaallista käyttöä varten.

'joukot' ei näy olevan missään yhteydessä käsitteeseen 'joukko-oppi'?

**Comment by mariaforsen** [comment]
Allärs: mängder, eli nimenomaan matemaattisena.

YSAssa myös: joukkueet (sotilasosastot)

**Comment by satuniininen** [comment]
Ehdotan, että lisätään sulkutarkenne, esim. _joukot (matematiikka)_ ja RT-suhde joukko-oppiin. 

Tämän jälkeen tehdään Melindassa tarvittavat korjaukset käyttäen jo olemassaolevaa sanastoa, esim:

Foreign fighters : transnational identity in civil conflicts / David Malet.
joukot --> erikoisjoukot 

Interpersonal and group behaviour / Judy Gahagan.
joukot --> ryhmät

Crowdsourcing : why the power of the crowd is driving the future of business / Jeff Howe.
joukot --> joukkoistaminen

**Comment by EsaMPKK** [comment]
Oinonen:
joukko, truppi, sotilaallisesti järjestettyjen ja johdettujen voimien yhteisnimitys.
joukko-osasto, samaa aselajia oleva [...] rykmentti, erillinen pataljoona tai patteristo, erillinen komppania tai patteri tai vastaavat.
joukkue, plutoona, tavallisesti kolmi- tai neliryhmäinen pataljoonan alayksikkö.

Kielitoimiston sanakirja:
joukko [...] vahvuudeltaan määrittelemätön sotilasosasto. [...] Tav. mon. asevoimista t. aselajeista: _Vihollisen joukot. Joukkojen huolto. Sotajoukot. Huoltojoukot. Panssari-, laskuvarjojoukot._
joukko-osasto sot. suoraan sotatoimiyhtymän alainen, aselajiltaan yhtenäinen hallinnollinen kokonaisuus. _Panssariprikaatin joukko-osastot Panssarirykmentti ja Jääkäripatteristo._
joukkue [...] sot. komppanian lähin alayksikkö. _Jääkäri-, pioneerijoukkue. Kiväärijoukkueen johtaja._

**Comment by EsaMPKK** [comment]
Tässä vielä sotilasyksiköt:
https://fi.wikipedia.org/wiki/Sotilasyksikk%C3%B6
