### ISSUE TITLE
kalvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5773]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kalvot](http://www.yso.fi/onto/ysa/Y154986) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa jaettu: kalvot (elottomat objektit) ja kalvot (orgaaniset objektit). Ratkaistava ristiriita sanastojen välillä ennen YSOon siirtymistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/405

**Comment by mirmaid** [comment]
FinMeSHissä kalvot LT kudokset - tämäkin voisi olla mahdollinen tarkenne? LCSH:ssa Membranes (Biology) ja Membranes (Technology), mutta toimiiko tämä jaottelu kun nykyään usein kyse on biotekniikasta?

Toisaalta objekti-tarkenne vie ehkä ajatukset enemmän piirtoheitin- ym. erillisiin "esineisiin" kuin pinnoitteisiin tms.

**Comment by mariaforsen** [comment]
Ruotsiksi muutettiin aikaisemman päätöksen mukaan niin että: 
-membran (tekniska objekt) -MOT:"ohuista levymäisistä esineistä t. aineista."
-membran (organiska objekt) -MOT: "elimiä ja elimistön osia peittäviä ohuita sidekudos- tm. muodostumia"
Mitään piirtoheitinkalvoihin viittaavaa ei ole mukana enää. Membran ei ole myöskään varsinaisesti "pinnoite".

**Comment by AuHo22** [comment]
Tässäkin tapauksessa mielestäni YSO:n sulkutarkenteet - ainakin näin luonnontieteellistä taustaa omaamattomalle - ovat pikemminkin sekoittavia kuin selventäviä. Yritin katsoa merkityseroja toisaalta elollisen ja elottoman luonnon ja toisaalta orgaanisen  ja epäorgaanisen välillä: 

Esim. muoveista sanottua: "Aiemmin uskottiin, että orgaanisia yhdisteitä on pelkästään organismeissa, ja tämä toimikin alkuperäisen jaon pohjana. Nykyään tämä käsitys on kuitenkin osoitettu vääräksi: tuhansia orgaanisia yhdisteitä on pystytty valmistamaan synteettisesti laboratoriossa. Esimerkiksi muovit ovat orgaanisia yhdisteitä."

Ja jos patologi tutkii kuolleen kalvoja, tekisi mieleni yhtä lailla laittaa tarkenteeksi kalvot (elottomat objektit) :)

**Comment by mirmaid** [comment]
"Orgaaninen" on tosiaan ongelmallinen tarkenne, koska se voi viitata sekä eloperäiseen että hiilipohjaiseen. Varmasti voisi ajatella esim. biohajoavan kalvon olevan orgaaninen. 

Toisaalta "objekti" ei kuvaa kovin hyvin kalvoja, joita käytetään päällystämiseen/pinnoittamiseen, esim. [tässä](http://www.vtt.fi/medialle/uutiset/vtt-kehitti-t%C3%A4ysin-kierr%C3%A4tett%C3%A4v%C3%A4n-pakkauspinnoitteen-elintarvike-ja-l%C3%A4%C3%A4kepakkauksia-varten), tai esim. teos _Kalvopinnoitettujen keittiökalusteovien olosuhde- ja rasituskestävyys_.

**Comment by mirmaid** [comment]
Joissakin viitteissä on kyse _solukalvoista_.

**Comment by satuniininen** [comment]
Ja joissain lihaskalvoista. 

Jos aloitetaan siivoamalla pois ne, jotka voidaan kuvailla olemassaolevilla, tarkemmilla käsitteillä ja katsotaan millainen setti jää jäljelle?

**Comment by ilona-x** [comment]
YSAssa myös **kalvotekniikka** http://www.yso.fi/onto/ysa/Y95797

**Comment by satuniininen** [comment]
Faskioita eli sidekudoskalvoja eli peitinkalvoja on lihasten lisäksi muidenkin kudosten ympärillä. Jos vaihdetaan käytettävä ja ohjaustermi päikseen eli faskiat KT lihaskalvot, peitinkalvot, sidekudoskalvot niin saadaan se sopimaan myös aineistoihin, jotka käsittelevät esim. jännekalvoja (mm. monelle tuttu plantaarifaskia eli jalkapohjan jännekalvon kiputila on juuri tätä sorttia).

**Comment by mirmaid** [comment]
Lääketieteen termit:
membraani: kalvo; ks. myös solukalvo, rakokalvo
faskia: kalvo, sidekudoskalvo, peitinkalvo

_kalvot (pinnoitus ja pakkaus)_? :pray:
_sikiökalvot_ erikseen?
kalvot (suodatus), kalvosuodatus KÄ _kalvotekniikka_

**Comment by ilona-x** [comment]
Tämän pitkän keskustelun ja Melinda-viitteiden tutkimisen jälkeen selkeimmältä tuntuisi ehkä kuitenkin tuo LCSH:n jako eli **kalvot (biologia)** ja **kalvot (tekniikka)**

**Comment by mirmaid** [comment]
Ja mahdollisesti tarpeen lisätä tarkenne _kalvotekniikka (erotusmenetelmät)_.

**Comment by YSA-kokous** [comment]
kalvot (biologia)
kalvotekniikka (erotusmenetelmät)

Tutkitaan jäljellejäävät suomeksi ja ruotsiksi, seuraava kokous.

**Comment by satuniininen** [comment]
Viitteet siivottu, yli jäi
54 X kalvot 
21 X kalvotekniikka

Aihepiireiltään aika sekalaista seurakuntaa, mutta silti enemmän tai vähemmän tekniikkaa:

- Adheesio muovikalvojen ja kuitupintojen välillä 
- Ikkunalasin turvakalvo säästää ihmishenkiä
- Mechanical, microstructural and barrier properties of agricultural biopolymer films and foams :a literature review
- Lavakalvotuksen optimointi
- Ristisidotut galaktoglukomannaanikalvot 
- Biopolymers :new materials for sustainable films and coatings 
- Innovative surface structures

Kannatan näille muotoa **kalvot (tekniikka)**, mutta jotenkin olisi syytä varmistaa ettei biotekniikan aineistoihin mennä laittamaan kalvot (biologia). Tähän varmaan riittäisi ohjaus esim. kalvot (biotekniikka) KÄYTÄ kalvot (tekniikka)

Lisäksi 2 x sikiökalvot. Riittäisikö kalvot (biologia)?

**Comment by mariaforsen** [comment]
Sv. 
membran (biologi)
membran (teknik)
membranteknik

**Comment by YSA-kokous** [comment]
kalvot (tekniikka)
