### ISSUE TITLE
maalaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5774]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maalaus](http://www.yso.fi/onto/ysa/Y97156) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa jaettu: maalaus (pintakäsittely) ja maalaus (taiteellinen luonti). Ratkaistava ristiriita sanastojen välillä ennen YSOon siirtymistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/384

**Comment by mirmaid** [comment]
Toisena sulkutarkenteena voisi ehkä olla myös yksinkertaisemmin _(taide)_? _Maalaustaide_ tosin löytyy myös.

**Comment by mariaforsen** [comment]
Jääkö nykyinen tarkenne kuitenkin YSOon? Ontologialinjausten mukaan tässä olisi kai syytä pitää "maalaus (taiteellinen luonti)".. https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSOn+kehityslinjaukset

**Comment by mirmaid** [comment]
Jos se jää YSOon, kannattaa myös YSAssa ottaa sama tarkenne. Se on kuitenkin YSOssa ns. hierarkisoiva käsite, ei varmaan ole vielä selvää onko se jäämässä YSOon toimintahierarkian uudistamisen jälkeen (?).

**Comment by mirmaid** [comment]
Onko _maalaus (kuvataide)_ liian rajaava?

**Comment by LeKorsu** [comment]
Kuvataide kuulostaa yleiskielisemmältä kuin taiteellinen luonti ja siten minusta paremmalta "taviskäyttäjän" näkökulmasta

**Comment by YSA-kokous** [comment]
maalaus (kuvataide)
