### ISSUE TITLE
vetäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5776]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vetäytyminen](http://www.yso.fi/onto/ysa/Y112599) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa jaettu: vetäytyminen (poistuminen) ja vetäytyminen (psykologia). Ratkaistava ristiriita sanastojen välillä ennen YSOon siirtymistä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Voitaisiin ottaa myös tarkemmin esim. _vetäytyminen (sotatoimet)_ tms. Melindassa vain n. 30 viitettä, joista suuri osa liittyy joukkojen vetäytymiseen.

Joihinkin aineistoihin sopii _sosiaalinen vetäytyminen_ (= FinMeSH, Psykologian sanakirja: _eristäytyvä persoonallisuus_), osassa taas kyse voi olla tilapäisestä (ja normaalista) vuorovaikutuksesta vetäytymisestä, tai oravanpyörästä tai (uskonnollisessa tarkoituksessa) maailmasta vetäytymisestä. Vetäytyminen-termiä ei löydy varsinaisena psykologian terminä (_introversio_ on melko lähellä).

Kerran jäätikön vetäytymisestä.

**Comment by EsaMPKK** [comment]
Yep. PUHO-SOTOssa vetäytyminen, yläkäsite sotatoimet, assosiatiivisena taktiikka.

**Comment by satuniininen** [comment]
_Vetäytyminen (sotatoimet)_ kuulostaa hyvältä ja _jäätikön vetäytymisen_ voi varmaan lisätä _deglasiaation_ ohjaustermiksi.

**Comment by satuniininen** [comment]
Meshissä on myös _Sosiaalinen eristäytyminen_, mutta se kuulostaa jo paljon vakavammalta kuin sosiaalisesta kanssakäymisestä vetäytyminen. 

Ehkä _sosiaalinen vetäytyminen_ olisi tarpeen omana käsitteenään, sillä pelkkä _introversio_ ei ihan näyttäisi riittävän kaikkiin tapauksiin, esim. **Tasapainoinen varhaiskasvatus : erilaisia tapoja suhtautua muutokseen**.

Oravanpyörästä tms vetäytymisen voisi varmaan ohjata _downshiftaukseen,_ mutta uskonnollisessa tai hengellisessä mielessä tapahtuva vetäytyminen jää silti ongelmaksi. Vai voisiko senkin mieltää sosiaaliseksi vetäytymiseksi?

**Comment by mirmaid** [comment]
^ Muuten kyllä, mutta googlaamalla sosiaalinen vetäytyminen näyttää tarkoittavan juuri sairaalloista eristäytymistä.

**Comment by YSA-kokous** [comment]
vetäytyminen (sotatoimet)
jäätikön vetäytyminen KÄ deglasiaatio
korjataan viitteet ja tutkitaan jäljelle jääviä

**Comment by satuniininen** [comment]
Siivottu, jäljellä 23 + ketjut.

Suurimpaan osaan näistä sopisi _sosiaalinen eristäytyminen_ tai sanastossa jo oleva _erakot_. Ulkopuolelle jäävät

- Leppoistamisen tekniikat 
Tässä on downshiftaus, joten se riittänee.

- Introduction to christianity 
Maailmasta vetäytymistä uskonnollisessa merkityksessä. Voiko vetäytyminen olla kovin keskeisessä roolissa näin yleisluontoisessa teoksessa? Joihinkin uskonnollisiin yhteyksiin sopinee myös mainittu _erakot_, jolla ryhminä sosiologia ja teologia.

**Comment by mirmaid** [comment]
Lisäksi silloin kun kyse on vetäytyvästä käyttäytymisestä, joka ei ole kuitenkaan sairaalloista (esim. pienet lapset), voidaan käyttää termejä _introversio_ tai _ujous_.

**Comment by YSA-kokous** [comment]
sosiaalinen eristäytyminen
