### ISSUE TITLE
siirtoheittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5777]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[siirtoheittimet](http://www.yso.fi/onto/ysa/Y100922) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "dataprojektorit" ja "datatykit" ja poistetaan edellisestä viite asiasanaan "projektorit". 

#### Perustelut ehdotukselle   

Dataprojektorin osalta ks. https://www.kielitoimistonsanakirja.fi/siirtoheitin; datatykki myös ahkerasti käytetty. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Videoprojektori
https://www.finna.fi/Record/arto.703354

**Comment by mirmaid** [comment]
_Siirtoheittimet_-termiä on käytetty Melindassa kerran. Sen merkitys tuntuu olevan aika epätarkka, sillä viitataan myös episkooppiin, mutta lähinnä kai dataprojektoria edeltäneeseen laitteeseen (esim. https://picclick.de/InFocus-Power-View-820-323134691334.html); _"Siirtoheittimiksi" on kutsuttu piirtoheittimen kanssa (piirtoheitinkalvon paikalla) käytettyjä laitteita. Niissä käytettiin jäähdytyspuhaltimella varustettua nestekidenäyttöä, mikä teki niistä edullisia; toisaalta kuvan laatu ei ollut kovin hyvä._ (Wikipedia)

Dataprojektorit voisi sen sijaan varmaankin ohjata paremmin käsitteeseen _videoprojektorit_?

**Comment by YSA-kokous** [comment]
dataprojektorit KÄ videoprojektorit
