### ISSUE TITLE
kielikurssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5779]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kielikurssit](http://www.yso.fi/onto/ysa/Y102455) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö jakaa? 

#### Perustelut ehdotukselle   

Kielen opiskelun aineistot (jotka ovat kielikursseja) / kielikurssimatkat. 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Myös _kielimatkat_. Osittain kielimatkoja ja kursseja määritellään eri tavoin, käytännössä kuitenkin nimityksiä käytetään ristiin. Voisi ehkä myös ottaa _kielikurssit ja kielimatkat_, tai kielimatkat KÄ _kielikurssit (matkat)_.

**Comment by mirmaid** [comment]
Toisessa merkityksessä ehkä _kielikurssit (oppimateriaali(t))_.

**Comment by mariaforsen** [comment]
Språkresor (kielimatkat) on kyllä ruotsiksi erillinen käsite ("resa till visst land för intensiv undervisning i landets språk"), ja sekin olisi hyvä erillisenä (löytyy myös SAOssa). Kielikurssit tapahtumina voisi olla RT.

Språkkurs-sana taas viittaa kyllä nimenomaan kurssiin, eikä kurssimateriaaliin, mutta jos halutaan molemmat merkitykset, siis sekä oppimateriaalit että kurssit (tapahtumina) voidaan varmaan laittaa toiselle "språkkursmaterial" tms. 

Sen sijaan ruotsiksi ei voida laittaa niin että språkkurs ja språkresa olisi sama asia, koska sitä ne eivät ole, esim. monet kansanopistot järjestävät kielikursseja ja niissä ei matkusteta mihinkään. Språkkurs on tavallinen ilmiö, johon kaikenikäiset osallistuvat, mutta kielimatkalle lähteminen taitaa olla harvinaisempaa (ja yleisintä nuorten keskuudessa).

**Comment by mirmaid** [comment]
Käytetty Melindassa yli 6000 kertaa, enimmäkseen muototerminä oppimateriaaleille. Näille _kielikurssit (oppimateriaalit)_ olisi ongelmaton muoto. Ulkomaille suuntautuvista kielikursseista käytetään sekä nimeä kielimatkat, että kielikurssit. Ainakin osittain nämä tarkoittavat vähän eri asioita, kielimatka on ohjatumpi kuin kielikurssi. Nämä voisi kuitenkin yhdistää joko _kielikurssit (matkat)_ TAI _kielimatkat_ KT kielikurssit (matkat).

Ongelmallisin ovat oppilaitosten järjestämät kielikurssit, pelkkä tarkenne _(kurssit)_ ei erota ulkomaille suuntautuvista.

**Comment by mariaforsen** [comment]
Sv. 
språkkurser
språkresor

**Comment by mirmaid** [comment]
Tässä kannattaisi varmaan edetä niin, että kielikurssit otetaan SLM-sanastoon ja poimitaan viitteistä ne, joissa termi pitäisi olla 655-kentässä. 

Sen jälkeen aineistoa jää melko vähän.

**Comment by mariaforsen** [comment]
Eli mitkä termit jäävät YSOon?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon "kielikurssit (oppimateriaalit)".
Lisäksi käsite "kielimatkat", ohjaustermiksi "kielikurssit (kielimatkat)".

Tarkkaillaan, tarvitseeko muuta käsitettä (laitosten järjestämät kielikurssit tms).

**Comment by AuHo22** [comment]
slm-terminä tällä hetkellä myös (erittäin hyvä) oppimateriaali -> johdonmukaisuuden takia kielikurssit (oppimateriaali)? Eli ei kai monikkoa tarvitse toistaa, kun on muutenkin kerralla selvä...

**Comment by mirmaid** [comment]
SLM: kielikurssit LT oppimateriaali

**Comment by mariaforsen** [comment]
Språkkurser fi. kielikurssit merkityksessä "järjestetty kurssi" puuttuu nyt YSOsta ja kaikkiin Melinda-viitteisiin ei sovi kielimatka- tai oppimateriaali-merkitykset.

**Comment by mirmaid** [comment]
^ Riittäisiköhän _kieltenopetus_ & _kurssit_? Ok erikseenkin, mutta en oikein keksi tarkennetta erotukseksi kielimatkoista (jotka ovat myös tällaisia kursseja, mutta vain ulkomailla järjestettyjä). 

_Kielikurssit_-käsitettä on jäljellä nyt n. 1300 viitettä Melindassa, mutta joukossa on edelleen runsaasti oppimateriaaleja ja jonkin verran kielimatkoja käsittelevää aineistoa.

**Comment by LeKorsu** [comment]
Kävisikö kielikurssit (opetus), sv språkkurser?

**Comment by AuHo22** [comment]
kielikurssit (oppilaitokset)?

**Comment by mirmaid** [comment]
Aulin ehdotus ehkä paremmin poissulkee kielimatkat (ei välttämättä ihan kokonaan, koska kyllähän nekin ovat oppilaitosten järjestämiä kursseja).

**Comment by mirmaid** [comment]
Olen nyt aika paljon jo korjannut tätä, käytännössä muuttamalla näihin tapauksiin vain kieltenopetus ja toisinaan lisäksi kurssit.

**Comment by YSO-kokous** [comment]
**Päätös**

Suljetaan.

**Comment by mariaforsen** [comment]
Sv. språkkurser (språkundervisning) ANV språkundervisning
