### ISSUE TITLE
ammattikoulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5780]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ammattikoulut](http://www.yso.fi/onto/ysa/Y94620) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin ammatilliset oppilaitokset. Samoin myös termi ammattioppilaitokset. 

#### Perustelut ehdotukselle   

Käyttäjän kannalta erottelu on hankala. Vastaava muutos on tehty termille ammattikoulutus (https://github.com/Finto-ehdotus/YSE/issues/5349). 

#### Ehdottaja   

YSO 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/857
