### ISSUE TITLE
virtuoosit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5781]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[virtuoosit](http://www.yso.fi/onto/ysa/Y140891) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Musassa virtuoosit-termin LT on "muusikot" ja termi kuuluu ryhmään 89, YSAssa  termi kuuluu ryhmään 00 Yleistermit. Ehdotan, että musa-termin käyttöalue hieman laajennetaan ja ysa-termin puolestaan rajataan esittävän taiteen piirissä esiintyvistä. 

Eli 
virtuoosit
LT taitelijat tai esittäjät
ryhmät: ainakin 89 Musiikki ja 95 Teatteri. Tanssi
määritelmä: Virtuoosi on teknisesti poikkeuksellisen taiturimainen esiintyjä, esimerkiksi soittaja tai sirkustaitelija. 

#### Perustelut ehdotukselle   

Muutosehdotus liittyy musa-termin yhdistämiseen YSAan. 

#### Ehdottaja   

Katerina Sornova 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

katerina.sornova@helsinki.fi

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): kannatetaan, LT esittäjät
