### ISSUE TITLE
säestykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5782]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[säestykset](http://www.yso.fi/onto/ysa/Y214685) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Huomautuksen ja/tai yläkäsitteen muutos? 

#### Perustelut ehdotukselle   

Määritelmä nyt: Erikseen julkaistu säestysosuus, jonka avulla harjoitellaan soolo-osuuksia, esimerkiksi Music-minus-one -tyyppiset julkaisut. Ja yläkäsite: harjoitusaineistot. Onko termin merkitys todella näin kapea? 

Melindassa näytti olevan käytetty laajemminkin (ei aina harjoitusaineistoa). Kysytään sen takia kun ruotsinkielinen termivastine on mietinnässä (voisiko olla esim. ackompanjemang (övningsmaterial) mikä ei sitten ihan sovi kaikkin Melinda-osumiin). 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by jtuohini** [comment]
Tässä herää kysymys, tarvitaanko koko nykyistä asiasanaa YSAn puolelle, vai riittäisikö, että on jatkossa vain Suomalaisessa lajityyppi- ja muotosanastossa? T.s. paljonko meillä on aineistoa, joka käsittelee erikseen julkaistuja säestysosuuksia olematta itse niitä; varsinaiset säestysjulkaisut kuvaillaan kuitenkin 655-kentässä SLM-termein.

**Comment by asormune** [comment]
Keski-kirjastojen kannasta ei löydy yhtään haulla:  text/aineistolaji + säestykset/asiasana. Nuotteja ja moniviestimiä liki tuhat. (meillä osa äänilevyn sisältävistä nuoteista on vielä toistaiseksi aineistolajiltaan moniviestimiä, korjaillaan nuoteiksi kaiken aikaa ..)

**Comment by mariaforsen** [comment]
Ruotsin osalta riittäisi ackomanjemang=säestäminen YSA/Allärsin puolella.

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): emme kannata ehdotusta, kannatetaan termin poistamista sanastosta, pidetään ainoastaan slm-sanastossa (http://urn.fi/URN:NBN:fi:au:slm:s187)
