### ISSUE TITLE
arkistolaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5783]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

arkistolaki 

#### Ehdotettu termi ruotsiksi   

arkivlag 

#### Perustelut ehdotukselle   

https://www.finlex.fi/fi/laki/ajantasa/1994/19940831 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://minedu.fi/julkaisu?pubid=URN:ISBN:978-952-263-368-2 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [arkistolaki](http://finto.fi/yse/fi/page/Y505783)

**Comment by mariaforsen** [comment]
Sv. arkivlag

**Comment by mirmaid** [comment]
Pitäisiköhän olla arkistolaki (1994), kun kumoaa samannimisen lain vuodelta 1981...

**Comment by ilona-x** [comment]
Vastaavia tapauksia muitakin, esim. kuntalaki v. 2015 kumosi kuntalain vuodelta 1995 ja alkoholilaki v. 2018 kumosi alkoholilain vuodelta 1994.

**Comment by YSA-kokous** [comment]
Ei muutosta.
