### ISSUE TITLE
käsi- ja taideteollisuusala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5784]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

käsi- ja taideteollisuusala 

#### Vaihtoehtoiset termit ja ilmaisut   

käsi- ja taideteollisuus 

#### Perustelut ehdotukselle   

Esim. Käsi- ja taideteollisuusalalla valmistat, huollat ja korjaat vaatteita, asusteita ja sisustustekstiileitä. http://www.ekami.fi/hakijalle/koulutusalat/kasi-ja-taideteollisuusala 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-263-383-5 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [käsi- ja taideteollisuusala](http://finto.fi/yse/fi/page/Y505784)

**Comment by satuniininen** [comment]
Sanastossa on jo ennestään _käsi- ja taideteollisuusoppilaitokset_, jota on käsitelty myös täällä: https://github.com/NatLibFi/Finto-data/issues/857. Samaan aihepiiriin liittyy myös https://github.com/Finto-ehdotus/YSE/issues/5780.

Oppilaitosten nimiin perustuvat toimialojen nimimitykset ovat sikäli hankalia, että oppilaitokset ovat alttiita muutoksille. _Käsiteollisuus_ ja _taideteollisuus_ ovat myös sanastossa, mutta ne eivät toki aina riitä.

**Comment by satuniininen** [comment]
Sanastossa on jo ennestään _käsi- ja taideteollisuusoppilaitokset_, jota on käsitelty myös täällä: https://github.com/NatLibFi/Finto-data/issues/857 ja https://github.com/Finto-ehdotus/YSE/issues/5780

Oppilaitosten nimiin perustuvat toimialojen nimimitykset ovat sikäli hankalia, että oppilaitokset ovat alttiita muutoksille. _Käsiteollisuus_ ja _taideteollisuus_ ovat myös sanastossa, mutta ne eivät toki aina riitä.

**Comment by mariaforsen** [comment]
Sv. hantverks- och konstindustribranschen
