### ISSUE TITLE
pursiseurat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5785]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pursiseurat 

#### Ehdotettu termi ruotsiksi   

segelsällskap 

#### Ehdotettu yläkäsite YSOssa (LT)   

[järjestöt](http://www.yso.fi/onto/yso/p1393) 

#### Perustelut ehdotukselle   

Pursiseuroja ja sitä käsittelevää kirjallisuutta on paljon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://abo.finna.fi/Record/alma.1318726 

**Ehdottajan nimi:** Hilda Ruokolainen 
**Ehdottajan organisaatio:** Åbo Akademi 
**Ehdottajan sähköpostiosoite:** hilda.ruokolainen@abo.fi **Termiehdotus Fintossa:** [pursiseurat](http://finto.fi/yse/fi/page/Y505785)

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
pursiseura = purjehdusseura
purjehdusseura = purjehduksen harrastajien seura, pursiseura. 

Kuvailussa käytetty yhdistelmää: urheiluseurat + purjehdus

https://fi.wikipedia.org/wiki/Pursiseura

**Comment by ilona-x** [comment]
Purjehdusseurojen lisäksi on myös vene(ily)seuroja, venekerhoja, moottorivenekerhoja jne.
Näiden kuvailussa käytetty yhdistelmiä veneily + järjestöt tai urheiluseurat

ks. https://fi.wikipedia.org/wiki/Luettelo_suomalaisista_pursiseuroista

**Comment by mariaforsen** [comment]
Allärs: idrottsföreningar=urheiluseurat, eli sitä yhdistelmää ei voi käyttää ruotsiksi tässä tapauksessa. Myös SAOssa:  segelsällskap, LCSH-linkitys: Yacht clubs ; Yachting - Societies, etc.

**Comment by mirmaid** [comment]
Wikipedian mukaan muuten Suomen ensimmäinen urheiluseura oli _Segelföreningen i Björneborg_...

**Comment by YSA-kokous** [comment]
Mahdollisesti myös veneilyseurat.

**Comment by satuniininen** [comment]
Veneilyseurat myös ok / YSA-kokous

**Comment by mariaforsen** [comment]
Sv. 
-segelsällskap ET segelföreningar, segelklubbar
-båtklubbar ET båtsällskap, båtföreningar
