### ISSUE TITLE
koneurakointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5786]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koneurakointi 

#### Perustelut ehdotukselle   

Koneurakointi on yleisin maaseudulla esiintyvä
yrittäjyyden toimiala. Koneurakointiyrittäjät tekevät
töitä muun muassa maatalouden, metsätalouden,
maanrakennuksen, teiden kunnossapidon,
maisemanhoidon, puuenergia- ja turvetuotannon
aloilla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10138/229372 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [koneurakointi](http://finto.fi/yse/fi/page/Y505786)

**Comment by mirmaid** [comment]
TSR-ontologiassa http://www.yso.fi/onto/tsr/p11993

**Comment by mariaforsen** [comment]
Sv. maskinentreprenad
