### ISSUE TITLE
Pyhän kolminaisuuden kirkko (Kempele)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5787]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän kolminaisuuden kirkko (Kempele) 

#### Vaihtoehtoiset termit ja ilmaisut   

Kempeleen uusi kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Assosiatiiviset (RT)   

[Kempeleen vanha kirkko](http://www.yso.fi/onto/yso/p30197) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Kirkko vihittiin käyttöön vuonna 1993. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1624752 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Pyhän kolminaisuuden kirkko (Kempele)](http://finto.fi/yse/fi/page/Y505787)

**Comment by mariaforsen** [comment]
Sv. ?
