### ISSUE TITLE
Pyhän Marian kirkko (Sastamala)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5790]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän Marian kirkko (Sastamala) 

#### Vaihtoehtoiset termit ja ilmaisut   

Sastamalan vanha kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

1400-luvun lopulla rakennettu harmaakivikirkko. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.671488 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Pyhän Marian kirkko (Sastamala)](http://finto.fi/yse/fi/page/Y505790)

**Comment by mariaforsen** [comment]
Sv. Sankta Maria kyrka (Sastamala) ET S:t Maria kyrka (Sastamala), Sastamala kyrka
