### ISSUE TITLE
Pyhän Nikolaoksen kirkko (Joensuu)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5791]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän Nikolaoksen kirkko (Joensuu) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Joensuun ortodoksisen seurakunnan pääkirkko, valmistunut 1887. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1127854 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Pyhän Nikolaoksen kirkko (Joensuu)](http://finto.fi/yse/fi/page/Y505791)

**Comment by mariaforsen** [comment]
Sv. Helige Nikolaos kyrka (Joensuu) ET Helige Nikolai kyrka, Sankt Nikolaos kyrka
