### ISSUE TITLE
uskonto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5792]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uskonto](http://www.yso.fi/onto/ysa/Y104749) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista yhdistää käsitteeseen uskonnot (tai mahdollisesti toisinpäin)? Jos ei ole, niin täytynee lisätä tarkenteita (ainakin käsitteelle uskonto), YSOssa uskonto (uskominen) ja uskonnot (opit)? 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja:  usko ja siihen liittyvä pyhyyden kokemus yleismaailmallisena ilmiönä, joka us. on muotoutunut oppijärjestelmäksi ja ilmenee erilaisina (yhteisöllisinä) tapoina ja (palvonta)menoina.

Sanastossa on myös uskonnollisuus ja usko (sekä uskontojen nimiä) - tarvitaanko sen lisäksi välttämättä uskonto (uskominen)? Uskonnolliset opit olisi myös mahdollinen termi erikseen.

Melko samankaltaiset aineistot Melindassa, riippumatta onko käytetty asiasanana uskonto, uskonnot tai molempia. Joten riittäisikö termi uskonnot aineistoihin, jotka käsittelevät uskontoja, oli se sitten yksi tietty (jolloin pitää myös laittaa sen uskonnon nimitys), useita tai uskontoja ilmiönä - niitä on kuitenkin enemmän kuin yksi ainoa. Melindassa laitettu myös uskonnot-termi vaikka käsittelee vain yhtä uskontoa, eli sellaiseen erotukseen ei ainakaan pitäisi olla tarpeen. Käyttäjä joka on kiinnostunut tästä aihealueesta joutuu nyt hakemaan molempia. 

Vrt. myös LCSH, jossa vähän erilainen käsittely (jaottelu religions, sects, cults -joka ei varmasti sovi tehdä ruotsin ja suomen osalta). 

Ks. https://github.com/NatLibFi/Finto-data/issues/536 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
LCSH: yksikkö ja monikko, monikolla huomautukset:
_Here are entered works on the major world religions. Works on religious groups whose adherents recognize special teachings or practices which fall within the normative bounds of the major world religions are entered under |a Sects. Works on groups or movements whose system of religious beliefs or practices differs significantly from the major world religions and which are often gathered around a specific deity or person are entered under |a Cults._

**Comment by AuHo22** [comment]
Uskonto-asiasanaa on perinteisesti käytetty myös oppiaineen nimenä oppikirjojen kuvailussa eli ketjuissa uskonto-lukio jne. Pitäisikö sitten olla uskonto (oppiaineet)? 
Myös termi uskonelämä on olemassa, joka on lähellä uskonto (uskominen) merkitystä?

**Comment by krinay** [comment]
Myös KULAssa oli erikseen uskonto ja uskonnot. Molemmille on ollut perusteltua käyttöä, mutta eroa on hankala määritellä lyhyesti tai tuoda esiin sulkutarkenteella. Termillä _uskonto_ on meillä kuvailtu esimerkiksi tällaisia teoksia: _Uskontoteoria_, _The scientific study of religion_, _Religion in modern times: an interpretive anthology_, _Lumous murtuu: uskonto luonnonilmiönä_. Tai voidaan tutkia vaikkapa uskonnon ja tieteen tai uskonnon ja filosofian välistä suhdetta. Jne. Yksi uskontotieteen tutkimusaihe on uskonnon alkuperäteoriat, mutta sitä varten on YSAssa oma termi. Termillä _uskonnot_ taas on kuvailtu esimerkiksi tällaisia teoksia: _Historical atlas of the religions of the world_,  _Uskonnot nykyhetken maailmassa_, _Healing and restoring: health and medicine in the world's religious traditions_. Tai teoksia joissa käsitellään vaikkapa naisten asemaa eri uskonnoissa. Minusta YSO:n tarkenteet eivät ole uskontotieteen näkökulmasta ihan osuvat, mutta on kamalan vaikea keksiä parempia. Kun uskontoa tutkitaan tieteellisesti, ei aina tutkita uskomista vaan (myös) oppijärjestelmää tai ideaa siitä - tutkimatta kuitenkaan välttämättä erityisesti tiettyjä uskontoja ja niiden oppia.

**Comment by YSA-kokous** [comment]
Uskonnot-käsitteelta poistetaan sulkutarkenne YSOssa.
Jatketaan sopivan sulkutarkenteen tai uuden termimuodon etsimistä yksikkömuodolle.

**Comment by tpalonen** [comment]
Kannatan kaikkien "uskonto sinänsä"-tyyppisten käsitteiden poistamista sanastosta. "Uskonnot" on yleiskäsite. Se ei viittaa pelkästään yksittäisiin uskontoihin, vaan myös uskontoon käsitteenä.

**Comment by AuHo22** [comment]
Uskonnot-termin ohjaustermeinä on tällä hetkellä YSAssa sekä maailmanuskonnot ja uskontokunnat, joka mielestäni kertoo sen, kuinka se poikkeaa itse uskonto-käsitteestä ja toisaalta tehnee eroa uskonnollisiin liikkeisiin. YSO:n tarkenteet ovat taas kerran huonoja :). 

Uskonto (oppiaineet) olisi mielestäni tarpeellinen, mutta itse ilmiölle tarvitaan mielestäni myös termi samaan tapaan kuin on politiikka-yleiskäsite olemassa. Tarkenteen löytäminen vain voi olla hankalaa -> 

"Uskontotieteilijä Ilkka Pyysiäisen mukaan uskonto on käsitteellistys, joka on tehty suuresta määrästä erilaisia uskomuksia, käyttäytymistaipumuksia ja kokemuksia. Erilaiset asiat nähdään uskonnollisina silloin kun ne täyttävät tietyt tulkitsijan asettamat ehdot."

**Comment by AuHo22** [comment]
uskonto (ilmiöt) ja selittävä huomautus? - Internetissä paljon viitteitä ilmiö-sanan kanssa haettuna

**Comment by mariaforsen** [comment]
Ilmiö tarkenteena ei varmaan erota tarpeeksi selkeästi monikollisesta muodosta (kaikki erilliset uskonnot voidaan myös nähdä eräänlaisina ilmiöinä).

**Comment by mirmaid** [comment]
Yksikkö on huomattavasti käytetympi kuin monikko. Ehdottaisin, että tehdään konversio YSOn tarkenteella _(uskominen)_ ja tutkitaan konversion jälkeen onko mahdollista yhdistää jotenkin muuten, esim. _uskonto ja usko_ tms. Usein voisi toimiva muutos olla uskonto > _kristinusko_.

**Comment by satuniininen** [comment]
Toimivan ja selkeän sulkutarkenteen keksiminen yksikkömuodolle on lähestulkoon mahdotonta. Näkisin tässä kaksi ratkaisuvaihtoehtoa.

Muutetaan uskonnot KÄYTÄ uskontokunnat ja jätetään yksikkö ilman sulkutarkennetta.

TAI

yhdistetään muotoon uskonto KT uskonnot
Yksikkö on monikkoa monikäyttöisempi eikä tuota omituisuuksia tietueisiin, mikäli korjaukset hoidetaan automatiikalla. Monikko sen sijaan istuu huonosti silloin, kun uskontoa on käytetty kristinuskon synonyyminä. 

Tarvittaessa voidan ottaa erikseen uskonto (oppiaineet).

**Comment by krinay** [comment]
Jos ei voida jättää sekä yksiköllistä että monikollista muotoa, kannatan jälkimmäistä noista ratkaisuehdotuksista. Vaikkakin monikollista termiä varmaan kaivataan esim. sellaisten teosten kohdalla, joissa esitellään suuria maailmanuskontoja (Maailman uskonnot, Uskonnot maailmassa jne.).

**Comment by AuHo22** [comment]
Voitaisiinko ottaa uskontokuntien lisäksi sitten maailmanuskonnot? (Tämä otettiin esimerkiksi tarvittavana hakemistosanana jokin aika sitten YKL:ään). Ja sitten tietysti uskonto (oppiaineet), jolle on tarvetta.

**Comment by YSA-kokous** [comment]
uskonto (uskominen) KT uskonto
uskonnot

**Comment by YSA-kokous** [comment]
Palataan asiaan konversion jälkeen (esim. uskonto oppiaineena).

**Comment by mariaforsen** [comment]
Sv.
religion (tro) ET religion
religioner

**Comment by mirmaid** [comment]
Entäpä _uskonto ja uskonnot_?
Voidaan myös jatkaa nykyisellä tarkenteella, joka kyllä mielestäni lähentää _uskonto_-käsitettä _usko_-käsitteeseen ja sopii huonosti opetusta tai oppimateriaaleja käsitteleviin aineistoihin.

**Comment by ilona-x** [comment]
Melinda:
uskonto (uskominen) 17 738
uskonnot  8645

**Comment by YSO-kokous** [comment]
Kannatusta sai uskonto ja uskonnot käsitteiden yhdistäminen. Suoritetaan päätös käytettävästä termistä Githubissa peukkuäänestyksellä. Seuraavia kolmea viestiä voi äänestää peukuttamalla. Valitaan eniten seuraavaan kokoukseen mennessä peukkuja saanut vaihtoehto.

**Comment by YSO-kokous** [comment]
Vaihtoehto 1)
uskonto KÄYTÄ uskonnot

**Comment by YSO-kokous** [comment]
Vaihtoehto 2)
uskonnot KÄYTÄ uskonto

**Comment by YSO-kokous** [comment]
Vaihtoehto 3)
uskonto ja uskonnot
