### ISSUE TITLE
psalmit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5793]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[psalmit](http://www.yso.fi/onto/ysa/Y128452) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia: (1) "Raamattu. Psalmit" ja (2) "psalmit (sävellykset)". 

#### Perustelut ehdotukselle   

Termi viittaa nyt kahteen eri asiaan, jotka kuitenkin liittyvät vahvasti toisiinsa. "Raamattu. Psalmit" on RDA:n mukainen nimenmuoto kyseiselle teoksen osalle, ja on ristiriitaista käyttää kuvailussa kahta eri nimitystä samasta asiasta. "Psalmit (sävellykset)" taas olisi asiasana, jolla kuvailtaisiin Raamatun psalmien teksteihin tehtyjä sävellyksiä käsitteleviä aineistoja; varsinaiset psalmisävellykset kuvailtaisiin Suomalaisen lajityyppi- ja muotosanaston termillä. Ensimmäisen LCSH-vastine on "Bible. Psalms" [http://id.loc.gov/authorities/names/n79056804] ja toisen "Psalms (Music)" [http://id.loc.gov/authorities/subjects/sh85108115]. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
termi on jaettava, ainakin "psalmit (sävellykset)" sopii minulle.

**Comment by mirmaid** [comment]
Raamattu. Psalmit pitäisi kaikkien marcin sääntöjen mukaan auktorisoidan kenttään 130, ja olisi näin ensimmäinen sanaston _YSO-teokset_ (:crystal_ball:) n. 50 nimekkeestä :expressionless:.

**Comment by mariaforsen** [comment]
Allärs: psalmer=virret, psaltarpsalmer=psalmit

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan muotoa "psalmit (sävellykset)"

**Comment by mariaforsen** [comment]
Että sanastossa olisi sekä "virret" että "psalmit (sävellykset)" erillisinä? Miten tarkalleen eroavat toisistaan? Ruotsiksi täytyy nimittäin, siinä tapauksessa, lisätä myös psalmer=virret-termille tarkenteen (käyttäjille voi olla vaikeaa ymmärtää milloin käyttää mitäkin).

**Comment by jtuohini** [comment]
Jatkoehdotus: lopputulos olisi seuraavanlainen:

YSA = Allärs = LCSH = Svenska ämnesord
**virret** = **psalmer (kyrkovisor)** tai jotain vastaavaa (ks. https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/kyrkovisa) = **Hymns** = **Psalmer**
**psalmit (sävellykset)**, KT _psalmisävellykset_ = **psalmkompositioner** tai jotain vastaavaa = **Psalms (Music)** = **Psalmer (musik)** ja **Psaltarpsalmer (musik)** Määritelmä: _Raamatun_ psalmien teksteihin tehtyjä sävellyksiä.
**psalmit (runot)** (asiasanana, ynnä **Raamattu. Psalmit** teosviitteenä) = **psaltarpsalmer** (asiasanana, ynnä **Bibeln. Psaltaren** teosviitteenä) = **Bible. Psalms**

SLM/fin = SLM/swe = LCGFT
**virret** = **psalmer (kyrkovisor)** tai jotain vastaavaa (ks. https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/kyrkovisa) = **Hymns**
**psalmit (musiikki)**, KT _psalmisävellykset_ = **psalmkompositioner** tai jotain vastaavaa = **Psalms (Music)**
**psalmit (kirjallisuus)** = **psaltarpsalmer** = (ei LCGFT-vastinetta)

**Comment by mariaforsen** [comment]
sv. psalmer (sånger)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Psalm_(disambiguation) 

Olisiko _psaltarpsalmer (musik)_ mahdollinen, eli tarkoittaisi psalmiteksteistä tehtyjä musiikkikappaleita. Suomeksikin voisi kenties olla _psalmimusiikki_...tosin onko sitten sellaista kirjallisuutta joka käsittelee tätä ainakin meillä kai aika marginaalista genreä (jos se todella on oma genrensä)?

**Comment by mariaforsen** [comment]
On varmaan mahdollinen, tavalliselle käyttäjälle kuitenkin nyt vaikeaa erotella näitä kaikkia, mutta lisätään määritelmiä.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa @jtuohini:n ehdotusta 20.6.2018, eli käytettäväksi termiksi psalmit (sävellykset).

**Comment by mirmaid** [comment]
Tämänhetkinen ehdotettu tilanne siis:

virret = psalmer (tarkenne x)
psalmit = psaltarpsalmer > psalmit (tekstit/runot) = psaltarpsalmer (texter/dikter)
psalmit (sävellykset) = psaltarpsalmer (kompositioner) (jos psalmimusiikki ei käy?)

**Comment by YSA-kokous** [comment]
virret = psalmer (tarkenne x)
psalmit = psaltarpsalmer > psalmit (tekstit) = psaltarpsalmer (bibeltexter)
psalmit (sävellykset) = psaltarpsalmer (kompositioner)
