### ISSUE TITLE
etuuskohtelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5794]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

etuuskohtelut 

#### Ehdotettu termi ruotsiksi   

förmånsbehandling 

#### Perustelut ehdotukselle   

Tarvitaan tullin tiedotteiden tilauspalvelun käyttöönottoa varten (julkishallinnon yhteinen julkaisualusta YJA, Liferay) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://tulli.fi/yritysasiakkaat/tuonti/etuuskohtelut-ja-tavaran-yleinen-alkupera 

**Ehdottajan nimi:** Pirjo Idström-Rossi 
**Ehdottajan organisaatio:** Tulli 
**Ehdottajan sähköpostiosoite:** pirjo.idstrom-rossi@tulli.fi **Termiehdotus Fintossa:** [etuuskohtelut](http://finto.fi/yse/fi/page/Y505794)

**Comment by YSA-kokous** [comment]
Tullietuudet

**Comment by mariaforsen** [comment]
Sv. tullförmåner
