### ISSUE TITLE
Helsingin vanha kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5795]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Helsingin vanha kirkko 

#### Vaihtoehtoiset termit ja ilmaisut   

Vanha kirkko (Helsinki) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Vastaava käsite muussa sanastossa   

Vanha kirkko (Helsinki) : https://fi.wikipedia.org/wiki/Vanha_kirkko_(Helsinki) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Kirkko on vihitty käyttöön 1826 ja sen on suunnitellut Carl Ludvig Engel. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1428956 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Helsingin vanha kirkko](http://finto.fi/yse/fi/page/Y505795)

**Comment by vthuhtala** [comment]
assosiatiivinen termi, tila: ehdotus
_Vanhankirkon puisto (Helsinki)_

**Comment by mariaforsen** [comment]
Sv. Helsingfors gamla kyrka ET Gamla kyrkan (Helsingfors)
