### ISSUE TITLE
tasoitustullit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5796]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tasoitustullit 

#### Assosiatiiviset (RT)   

[polkumyyntitullit](http://www.yso.fi/onto/yso/p29292) 

#### Perustelut ehdotukselle   

Tarvitaan tullin tiedotteiden tilauspalvelun käyttöönottoa varten (julkishallinnon yhteinen julkaisualusta YJA, Liferay) 

#### Tarkoitusta täsmentävä selite   

Suhde polkumyyntitulleihin selkeytettävä. Tulli käyttää yhdessä "Polkumyynti- ja tasoitustullit": http://tulli.fi/yritysasiakkaat/tuonti/polkumyynti-ja-tasoitustullit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://tulli.fi/yritysasiakkaat/tuonti/polkumyynti-ja-tasoitustullit 

**Ehdottajan nimi:** Pirjo Idström-Rossi 
**Ehdottajan organisaatio:** Tulli 
**Ehdottajan sähköpostiosoite:** pirjo.idstrom-rossi@tulli.fi **Termiehdotus Fintossa:** [tasoitustullit](http://finto.fi/yse/fi/page/Y505796)

**Comment by mirmaid** [comment]
Tämä on jo JUHO-ontologiassa (http://www.yso.fi/onto/juho/p2240) ja voidaan ottaa myös YSAan.

**Comment by mariaforsen** [comment]
Sv.  utjämningstullar
