### ISSUE TITLE
Vanha kirkkopuisto (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5797]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Vanha kirkkopuisto (Helsinki) 

#### Vaihtoehtoiset termit ja ilmaisut   

Vanhankirkon puisto (Helsinki) 
Ruttopuisto 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puistot](http://www.yso.fi/onto/yso/p3227) 

#### Vastaava käsite muussa sanastossa   

Vanha kirkkopuisto : https://fi.wikipedia.org/wiki/Vanha_kirkkopuisto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Helsingin vanhaa kirkkoa ympäröivä puisto ja historiallinen hautausmaa 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1451815 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Vanha kirkkopuisto (Helsinki)](http://finto.fi/yse/fi/page/Y505797)

**Comment by mariaforsen** [comment]
Sv. Gamla kyrkoparken (Helsingfors) ET Pestparken
