### ISSUE TITLE
tulli-ilmoittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5799]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tulli-ilmoittaminen 

#### Perustelut ehdotukselle   

Tarvitaan tullin tiedotteiden tilauspalvelun käyttöönottoa varten (julkishallinnon yhteinen julkaisualusta YJA, Liferay) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://tulli.fi/yritysasiakkaat/tulli-ilmoittaminen 

**Ehdottajan nimi:** Pirjo Idström-Rossi 
**Ehdottajan organisaatio:** Tulli 
**Ehdottajan sähköpostiosoite:** pirjo.idstrom-rossi@tulli.fi **Termiehdotus Fintossa:** [tulli-ilmoittaminen](http://finto.fi/yse/fi/page/Y505799)

**Comment by mirmaid** [comment]
YSAssa ei ole termiä ilmoittaminen, sen sijaan on erilaisia ilmoituksia. Muoto "tulli-ilmoitukset" tuo enemmän viitteitä Googlella kuin tulli-ilmoittaminen.

**Comment by mariaforsen** [comment]
Sv. tulldeklarationer ET tulldeklarering

**Comment by YSA-kokous** [comment]
Tulli-ilmoitukset? Seuraava kokous.

**Comment by ilona-x** [comment]
"Tulliselvityksen keskeinen osa on usein rajalla vaadittavan kirjallisen tai sähköisesti lähetettävän tulli-ilmoituksen täyttäminen."
https://fi.wikipedia.org/wiki/Tulliselvitys
