### ISSUE TITLE
tullinimikkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5800]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tullinimikkeet 

#### Perustelut ehdotukselle   

Tarvitaan tullin tiedotteiden tilauspalvelun käyttöönottoa varten (julkishallinnon yhteinen julkaisualusta YJA, Liferay) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://tulli.fi/henkiloasiakkaat/netista-tilaajalle/tullinimikkeet 

#### Tarkoitusta täsmentävä selite   

Suhde käsitteeseen viivakoodit (ohjaustermi tavarakoodit) selvitettävä 

**Ehdottajan nimi:** Pirjo Idström-Rossi 
**Ehdottajan organisaatio:** Tulli 
**Ehdottajan sähköpostiosoite:** pirjo.idstrom-rossi@tulli.fi **Termiehdotus Fintossa:** [tullinimikkeet](http://finto.fi/yse/fi/page/Y505800)

**Comment by mirmaid** [comment]
JUHO-ontologiassa muodossa _tullinimikkeistö_ (http://www.yso.fi/onto/juho/p2270), tullinimikkeet tuo enemmän viitteitä Googlella. Vastaavia sanastoissa vain _ammattinimikkeet, virkanimikkeet_.

YSAssa on siis nyt tavarakoodit KÄ viivakoodit. Yllä mainitulla sivulla sanoja tavarakoodi ja tullinimike käytetään synonyymeina? "Nimikkeet" ovat numerosarjoja.

**Comment by mariaforsen** [comment]
Sv. tullpositioner, tulltariffpositioner, tulltariffnummer. Tullin sivuilla pelkkä "varukod" (tavarakoodi). Eli ovatko ne oikeasti eri asioita/ovatko molemmat tarpeen erillisinä termeinä?

**Comment by ilona-x** [comment]
"Tulliselvityksessä kaikille tuotaville tai vietäville tavaroille on ilmoitettava tullinimike. Tullinimikkeestä käytetään myös nimeä tavarakoodi, tullitariffinimike tai Taric-koodi (englanniksi Commodity Code)."
Lähde: http://tulli.fi/yritysasiakkaat/tuonti/tavaran-tullinimike
ja sama ruotsiksi: http://tulli.fi/sv/foretag/import/varukod

**Comment by mariaforsen** [comment]
Sv. tullpositioner ET tulltariffnummer, tulltaxenummer, tulltariffpositioner, varukoder (tull)
