### ISSUE TITLE
valuutan muuntokurssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5802]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valuutan muuntokurssit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://tulli.fi/yritysasiakkaat/tuonti/valuutan-muuntokurssit 

#### Perustelut ehdotukselle   

Tarvitaan tullin tiedotteiden tilauspalvelun käyttöönottoa varten (julkishallinnon yhteinen julkaisualusta YJA, Liferay) 

**Ehdottajan nimi:** Pirjo Idström-Rossi 
**Ehdottajan sähköpostiosoite:** pirjo.idstrom-rossi@tulli.fi 
**Ehdottajan organisaatio:** Tulli **Termiehdotus Fintossa:** [valuutan muuntokurssit](http://finto.fi/yse/fi/page/Y505802)

**Comment by mirmaid** [comment]
Sanastoissa on nyt vain termi _valuuttakurssit_, ja tämä on kai käytännössä tiettynä aikana käytössä oleva valuuttakurssi, joten eikö se riittäisi? Jos otettaisiin erillinen termi, ainakin tässä ehdotetussa muodossa se menisi helposti sekaisin tavallisen valuuttakurssin kanssa.

**Comment by YSA-kokous** [comment]
KÄ valuuttakurssit
