### ISSUE TITLE
ngadan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5803]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ngadan kieli 

#### Ehdotettu termi englanniksi   

Ngada language 

#### Vaihtoehtoiset termit ja ilmaisut   

ngad'an kieli, ngadhan kieli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[austronesialaiset kielet](http://www.yso.fi/onto/yso/p3967) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85091658> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.108859 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [ngadan kieli](http://finto.fi/yse/fi/page/Y505803)

**Comment by mirmaid** [comment]
Mistä suomenkielinen muoto on otettu?

**Comment by mariaforsen** [comment]
Sv. ngada (språk)
