### ISSUE TITLE
sähköiset henkilökortit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5804]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sähköiset henkilökortit](http://www.yso.fi/onto/ysa/Y112433) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytettäväksi termiksi henkilökortit. 

#### Perustelut ehdotukselle   

Olemme saaneet palautetta suomi.fi:n verkkotoimitukselta. Irene Rissanen: "Olen muuttanut Suomi.fi-verkkopalvelun puolelle termiä sirullinen henkilökortti pelkäksi henkilökortiksi. Tämä sen vuoksi, että VRK on pyrkinyt tekemään pitkäjänteistä työtä sen puolesta, että nykyään ei puhuttaisi enää sirullisesta tai sähköisestä henkilökortista, vaan pelkästä henkilökortista, koska muunlaisia kuin sirullisia kortteja ei ole enää ollut pitkään aikaan olemassa. Huomasin, että ontologiasanoissa on tarjolla vain ”sähköiset henkilökortit” -termi.”

Palaute koskee KOKOa, mutta kyseessä on joka tapauksessa YSOn/YSAn käsite. Näiden lisäksi se on myös JUHOssa. Huom! YSAssa henkilökortit on myös ohjaustermi henkilötodistukset-käsitteelle. 

#### Ehdottaja   

Tuomas PAlonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/S%C3%A4hk%C3%B6inen_henkil%C3%B6kortti

Allärs: identitetskort=henkilötodistukset, mutta se voidaan kyllä periaatteessa muuttaa, jos sen lisäksi halutaan henkilökortit.

**Comment by mirmaid** [comment]
Jos termi halutaan poistaa, se voidaan varmaankin korvata kuvailussa termeillä _sähköiset asiakirjat_ ja _henkilötodistukset_. Mutta tarvitaanko sekä _henkilökortit_ että _henkilötodistukset_? Pelkkää henkilökortit-termiä ei ole juuri lainkaan käytetty Melindassa.

**Comment by mirmaid** [comment]
_An identity document (also called a piece of identification or ID, or colloquially as papers) is any document which may be used to prove a person's identity. If issued in a small, standard credit card size form, it is usually called an identity card (IC, ID card, Citizen Card), or Passport Card._ https://en.wikipedia.org/wiki/Identity_document

**Comment by YSA-kokous** [comment]
Ei muutosta

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9224
