### ISSUE TITLE
Tyrvään kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5806]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tyrvään kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Assosiatiiviset (RT)   

[Pyhän Olavin kirkko (Vammala)](http://www.yso.fi/onto/yso/p19543) 

#### Vastaava käsite muussa sanastossa   

Tyrvään kirkko : https://fi.wikipedia.org/wiki/Tyrv%C3%A4%C3%A4n_kirkko 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Vuonna 1855 valmistunut kaksitorninen tiilikirkko Sastamalassa 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1287468 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Tyrvään kirkko](http://finto.fi/yse/fi/page/Y505806)

**Comment by mariaforsen** [comment]
Sv. Tyrvis kyrka
