### ISSUE TITLE
Karkun kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5807]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Karkun kirkko 

#### Vaihtoehtoiset termit ja ilmaisut   

Kristuksen tulemisen kirkko (Sastamala) 

#### Vastaava käsite muussa sanastossa   

Karkun kirkko : https://fi.wikipedia.org/wiki/Karkun_kirkko 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Tarvitaan kuvailussa 

#### Perustelut ehdotukselle   

Vuonna 1913 valmistunut harmaakivikirkko Sastamalassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1287468 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Karkun kirkko](http://finto.fi/yse/fi/page/Y505807)

**Comment by mariaforsen** [comment]
Sv. Karkku kyrka
