### ISSUE TITLE
Sammaljoen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5808]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Sammaljoen kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Vastaava käsite muussa sanastossa   

Sammaljoen kirkko : https://fi.wikipedia.org/wiki/Sammaljoen_kirkko 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Vuonna 1924 valmistunut puukirkko Sastamalassa 

#### Perustelut ehdotukselle   

Tavitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1287468 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Sammaljoen kirkko](http://finto.fi/yse/fi/page/Y505808)

**Comment by mariaforsen** [comment]
Sv. Sammaljoki kyrka
