### ISSUE TITLE
Salokunnan kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5809]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Salokunnan kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Vastaava käsite muussa sanastossa   

Salokunnan kirkko : https://fi.wikipedia.org/wiki/Salokunnan_kirkko 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1287468 

#### Tarkoitusta täsmentävä selite   

Vuonna 1960 valmistunut kirkkorakennus Sastamalassa 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Salokunnan kirkko](http://finto.fi/yse/fi/page/Y505809)

**Comment by mariaforsen** [comment]
Sv. Salokunta kyrka
