### ISSUE TITLE
uusiutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5811]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uusiutuminen](http://www.yso.fi/onto/ysa/Y161557) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

jaettava tai tarkennettava 

#### Perustelut ehdotukselle   

Käsitteen merkitystä on tarkennettava, jotta sille saadaan täsmälliset käänösvastineet ruotsiksi ja englanniksi. 

Melindassa on tarvetta ainakin merkitykselle "uusiutuminen (lääketiede)". Aloitetaan korjaamalla lääketiedettä käsittelevät kuvailut ja arvioidaan jatko sen mukaan, mitä jää jäljelle. 

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by vthuhtala** [comment]
"uusiutuminen (lääketiede)" = regeneraatio?

**Comment by ilona-x** [comment]
FinMeSH: 
uusiutuminen KÄYTÄ relapsi
http://finto.fi/mesh/fi/page/D012008

**Comment by satuniininen** [comment]
Pääsääntöisesti käytetty tarkoittamaan juuri sairauksien uusiutumista.

**Comment by mirmaid** [comment]
Lääketieteen termit: relapsi: _uusiutuma, taudin uusiutuminen | taudinoireiden palaaminen näennäisen paranemisen jälkeen, (taudin) uudelleen paheneminen_
uusiutuma: _residiivi | (taudin) uusiutuminen, uusiminen_

**Comment by mirmaid** [comment]
Melindassa _relapsi_ 8 kertaa FinMeSH-terminä, kerran vapaana asiasanana. Myös TEROssa.

**Comment by mariaforsen** [comment]
Sv. återfall/recidiv (medicin)

**Comment by YSA-kokous** [comment]
relapsi

**Comment by ilona-x** [comment]
Melindaan korjattu uusiutuminen (lääketiede/taudit) -> relapsi 
Jäljelle jäi 22 viitettä: 
-osassa ilmeisesti kyse regeneraatiosta (KT uusiutuminen (biologia))
-lisäksi esim. yritysten/organisaatioiden/teollisuuden uusiutuminen, voisiko korvata esim. termeillä uudistukset/uudistaminen?

**Comment by mirmaid** [comment]
^ Mielestäni voi. 

_Regeneraatio_ on Tieteen termipankissa ja suomenkielisessä wikipediassa määritelty melko suppeasti. Englanninkielisessä wikipediassa: _In biology, regeneration is the process of renewal, restoration, and growth that makes genomes, cells, organisms, and ecosystems resilient to natural fluctuations or events that cause disturbance or damage._ Regeneraatiolle ekologiassa on kuitenkin myös oma artikkelinsa. Osa Melindan viitteistä käsittelee ekosysteemin uusiutumista. Myös _regeneraatio_-termiä on käytetty vastaavissa aineistoissa - ja monenlaisissa muissakin, esim. _Käytetyn voiteluöljyn regenerointilaitoksen prosessivesien karakterisointi_...

**Comment by YSA-kokous** [comment]
regeneraatio (biologia)
uusiutuminen poistetaan
korjataan viitteet ja tutkitaan tarvitaanko vielä jotain
