### ISSUE TITLE
artikulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5813]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[artikulaatio](http://www.yso.fi/onto/ysa/Y94707) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia: 1) "artikulaatio (kielitiede)" ja 2) "artikulaatio (musiikki)". Näistä ensimmäinen vastaisi YSAn nykyistä artikulaatio-asiasanaa ja jälkimmäinen MUSAn artikulaatio-asiasanan 2-merkitystä. 

#### Perustelut ehdotukselle   

Soittamisen yhteydessä artikulaatiolla tarkoitetaan muuta kuin mihin YSAn nykyinen asiasana viittaa. -- Kyseinen termiasia tullut vastaan MUSAn YSAan sulauttamisen yhteydessä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Tässä vielä Musan vanha määritelmä termille **artikulaatio (musiikki)**: Sävelten, taukojen ja rytmien erittely, ryhmittely ja painottaminen musiikillisessa ilmaisussa.

**Comment by mariaforsen** [comment]
Sv. artikulation (språk), artikulation (musik)

**Comment by YSA-kokous** [comment]
Artikulaatio (musiikki), artikulaatio (fonetiikka?)

**Comment by mirmaid** [comment]
Mikä sulkutarkenne toiselle? Vrt. myös https://github.com/Finto-ehdotus/YSE/issues/5982

**Comment by YSA-kokous** [comment]
artikulaatio (puhe)
