### ISSUE TITLE
modaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5814]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[modaalisuus](http://www.yso.fi/onto/ysa/Y105987) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia: 1) "modaalisuus (kielitiede)" ja 2) "modaalisuus (musiikki)". Ensimmäinen vastaa YSAn nykyistä asiasanaa, jälkimmäinen MUSAn asiasanaa, jotka viittaavat aivan eri asioihin. 

#### Perustelut ehdotukselle   

Asia tuli vastaan Musaa Ysaan yhdistettäessä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by asormune** [comment]
MUSAssa määritelmä: moodit = 1) Taidemusiikin teoriassa sävelsuku tai (2) rytminen kaava 1200-luvun musiikissa.
YSAssa termi: moodit (säveljärjestelmät) ; Ei (vielä?) määritelmää (huomautuksena = Modaalisista sävelasteikoista käytetään termiä sävelasteikot.)

**Comment by ksornova** [comment]
_sävelasteikot_ voisi olla termin _modaalisuus (musiikki)_ RT

**Comment by ksornova** [comment]
MUSAn termin _modaalisuus_  nykyistä määritelmää voisimme vähän muokata:
NYT: Nimitys säveltasorakenteen kirkkosävellajeista eli moodeista peräisin oleville ominaisuuksille.
Parempaa määritelmää saa siis ehdottaa

Samalla voisi miettiä termin _moodit (säveljärjestelmät)_ määritelmää:
suoraan Wikipediasta: "pysyvä musiikin rakenne kuten sävelasteikko, melodia tai pysyvä rytmikuvio. "
huomautus: Modaalisista sävelasteikoista käytetään termiä sävelasteikot.

huomautukseen? "Länsimaisessa musiikissa moodilla tarkoitetaan useimmiten keskiajalla kehitettyä asteikkojärjestelmää, ns. kirkkosävellajeja."

**Comment by asormune** [comment]
MODAALISUUS (SiBan musiikinhistoriasivustolta=:
Moodilla [modus: tapa, laatu, standardi] tarkoitetaan pysyvää, vakinaista, järjestelmän perustaksi soveltuvaa. 
Musiikissa moodit ovat useimmiten kiinteitä, pysyviä säveltasorakenteita, kuten asteikkoja tai melodisia perusmalleja ja -hahmoja, tai myös pysyviä rytmikuvioita.

**Comment by ilonahei** [comment]
Modaalisuus musiikissa ei viittaa pelkästään sävelasteikoihin vaan myös modaaliseen harmoniaan, verraten tonaaliseen harmoniaan, jonka on dominantti-toonika-jännitteet puuttuvat modaalisesta musiikista.

Wikipedian Harmonia (musiikki) -sivulla sanotaan näin: "Modaalinen harmonia on harmonian laji, jossa soinnuilla ei ole edellä mainitun kaltaista jännitteisyyttä, vaan niitä voidaan järjestellä peräkkäin hyvinkin vapaasti, kunhan soinnut ja melodia säilyttävät suhteen toisiinsa, eli melodioiden noudattelemat asteikot ovat sidoksissa harmoniaan. Modaalinen harmonia kukoisti keskiajalla ja renessanssin aikana länsimaisessa taidemusiikissa, ja sitä tavataan lukuisten maiden kansanmusiikkityyleissä. Lisäksi 1900-luvulla säveltäjät etsivät uusia harmonian käsittelyn keinoja ja käyttivät sävellystensä pohjana modaalista ajattelua."

PIKI-tietokannassa (ja varmaan muuallakin) sanaa käytetään 90-prosenttisesti jazzin yhteydessä, pitäisikö tämä huomioida?

**Comment by mariaforsen** [comment]
Sv. modalitet (språk), modalitet (musik)

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): käsitelty, mutta jää seuraavaan kertaan.
termi jaetaan kyllä: modaalisuus (musiikki), LT ja määritelmä tulee myöhemmin

**Comment by YSA-kokous** [comment]
modaalisuus (kielitiede) ja modaalisuus (musiikki)

**Comment by ilonahei** [comment]
Ehdotus modaalisuuden määritelmäksi:
Moodeihin perustuva asteikkopohjainen järjestelmä, josta puuttuvat tonaalisen harmonian kolmisointujen väliset jännitteet.

Aika kinkkinen aihe määritellä, tämä vaati aikamoista pähkäilyä.

**Comment by asormune** [comment]
Pilkunviivauspuolelle menee, mutta YSA:ssa on: asteikot (musiikki) → sävelasteikot. Pitäisikö määritelmässä käyttää  "asteikkopohjainen" ilmaisun sijaan  ilmaisua "sävelasteikkopohjainen" tai "sävelasteikoihin perustuva"

**Comment by TommiViitamies** [comment]
Ja jotta ei olisi liian helppoa, niin: kun on juuri hyväksytty myös termi rytmimoodit (https://github.com/Finto-ehdotus/YSE/issues/5929), niin pitäisikö tässä mainitut moodit erottaa määritelmässä niistä. Esim.: "Sävelmoodeihin perustuva sävelasteikkopohjainen..."

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): Modaalisiin sävelasteikkoihin perustuva järjestelmä, josta puuttuvat tonaalisen harmonian kolmisointujen väliset jännitteet.

**Comment by MUUSA-kokous** [comment]
LT säveljärjestelmät
[ks. määritelmä]

**Comment by tpalonen** [comment]
Tämä on nyt eri paikassa kuin "tonaalisuus" vaikka käsitteet ovat likeiset. Otetaan tämäkin Muusan ja YSAn yhteiskokoukseen listalle.

**Comment by YSA-kokous** [comment]
modaalisuus (musiikki) ja kromatiikka YK taiteisiin liittyvät ominaisuudet

**Comment by mirmaid** [comment]
Modaalisuus (musiikki): määritelmää muokattava, koska yläkäsite on ominaisuudet, ei järjestelmät. Entinen määritelmä _nimitys säveltasorakenteen kirkkosävellajeista eli moodeista peräisin oleville ominaisuuksille_ oli hierarkian kannalta toimiva.

Kromatiikan määritelmä nyt lähinnä toimintaa.

**Comment by tpalonen** [comment]
PÄÄTÖS:

Modaalisten sävelasteikkojen ominaisuus, jolle on ominaista tonaalisen harmonian kolmisointujen välisten jännitteiden puuttuminen.
