### ISSUE TITLE
Pyhän Jaakobin pyhiinvaellusreitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5818]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Pyhän Jaakobin pyhiinvaellusreitti 

#### Ehdotettu termi ruotsiksi   

Jakobsleden 

#### Ehdotettu termi englanniksi   

Camino de Santiago de Compostela 

#### Vaihtoehtoiset termit ja ilmaisut   

Pyhän Jaakobin tie 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Pyh%C3%A4n_Jaakobin_pyhiinvaellusreitti 
LCSH : <http://id.loc.gov/authorities/subjects/sh2010013310> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kolmen tien kulkijat 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [Pyhän Jaakobin pyhiinvaellusreitti](http://finto.fi/yse/fi/page/Y505818)

**Comment by mariaforsen** [comment]
Sv. Jakobsleden ET Compostelaleden, Sankt Jakobsleden

**Comment by ilona-x** [comment]
Tälle olisi ollut jälleen tarvetta kuvailussa: 
Druidiset sirut : Santiago de Compostela kutsuu
