### ISSUE TITLE
Viron vapaussota (1918-1920)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5820]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Viron vapaussota (1918-1920) 

#### Ehdotettu termi ruotsiksi   

Estniska frihetskriget (1918-1920) 

#### Vaihtoehtoiset termit ja ilmaisut   

Vabadussõda (1918-1920) 
Viron itsenäisyyssota (1918-1920) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sisällissodat](http://www.yso.fi/onto/yso/p15837) 

#### Vastaava käsite muussa sanastossa   

Viron vapaussota : https://fi.wikipedia.org/wiki/Viron_vapaussota 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

Sodan ensimmäisessä vaiheessa Viro taisteli Neuvosto-Venäjää vastaan. Sodan toisessa vaiheessa Viron tasavalta taisteli myös Baltian yhdistynyneen herttuakunnan Baltian Landeswehriä vastaan Pohjois-Latviassa. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.404822 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Viron vapaussota (1918-1920)](http://finto.fi/yse/fi/page/Y505820)

**Comment by mariaforsen** [comment]
Sv. Estniska frihetskriget ET Estniska frihetskriget 1918-1920, Estniska frihetskriget (1918-1920)

**Comment by mirmaid** [comment]
On jo sanastossa.
