### ISSUE TITLE
proterotsooinen kausi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5821]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[proterotsooinen kausi](http://www.yso.fi/onto/ysa/Y104007) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nykyisen jaottelun mukaan proterotsooinen kausi on ns. aioni, joka jakaantuu kolmeen maailmankauteen, nämä edelleen kausiin. YSAn prekambrinen maailmankausi puolestaan on yläaioni https://fi.wikipedia.org/wiki/Prekambri, sen voisi muuttaa yksinkertaisesti > prekambri?

tertiäärikausi-nimitys on vanhentunut https://fi.wikipedia.org/wiki/Terti%C3%A4%C3%A4rikausi 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Geologinen_ajanlasku 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Samoin myös arkeeinen kausi > aioni

Sanastosta puuttuu fanerotsooinen aioni, jonka alle tulisivat YSAn nykyiset maailmankaudet lukuunottamatta prekambria.
