### ISSUE TITLE
tarmflora

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5822]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

tarmflora 

#### Perustelut ehdotukselle   

Aktuellt i en stor mängd nyutkommen litteratur 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

som ämnesord 

**Ehdottajan nimi:** Heidi Reinikainen 
**Ehdottajan organisaatio:** Ekenäs bibliotek 
**Ehdottajan sähköpostiosoite:** heidi.reinikainen@raseborg.fi **Termiehdotus Fintossa:** [tarmflora](http://finto.fi/yse/fi/page/Y505822)

**Comment by mariaforsen** [comment]
Nationalencyklopedin, Lääketieteen termit: normalflora

**Comment by PaiviLipsanen** [comment]
Suolistomikrobisto kattaa mielestäni sekä suoliston normaalin että poikkeavan mikrobiston. Normaalifloora taas on normaalin tilanteen / terveen yksilön mikrobisto, jonka koostumusta esim. antibioottikuuri ei ole häirinnyt. Suoliston mikrobistoa/mikrobiomia tutkitaan nyt paljon. Mikrobistoon kuuluvat bakterien lisäksi myös mm. sienet ja virukset.

**Comment by YSA-kokous** [comment]
Suolistomikrobisto (KT suolistomikrobiomi?), normaalifloora

**Comment by mariaforsen** [comment]
Sv. 
-tarmflora ET tarmmikroflora
-normalflora
