### ISSUE TITLE
korvaava työ

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5823]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

korvaava työ 

#### Ehdotettu termi ruotsiksi   

ersättande arbete 

#### Vaihtoehtoiset termit ja ilmaisut   

korvaavan työn toimintamalli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[työ](http://www.yso.fi/onto/yso/p1810) 

#### Vastaava käsite muussa sanastossa   

TSR-ontologia : <http://www.yso.fi/onto/tsr/p6746> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Korvaava työ kunta-alalla : toimintatavan suunnittelu ja käyttö / 

#### Perustelut ehdotukselle   

tarve aineiston kuvailusssa 

#### Tarkoitusta täsmentävä selite   

https://www.tehy.fi/fi/apua/sairausloma/mita-korvaava-tyo
https://yle.fi/uutiset/3-9435225
https://www.keva.fi/globalassets/2-tiedostot/ta-tiedostot/esitteet-ja-julkaisut/korvaava-tyo-kunta-alalla.pdf 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [korvaava työ](http://finto.fi/yse/fi/page/Y505823)

**Comment by mariaforsen** [comment]
"Ersättande arbete" käytetään tosin myös siinä merkityksessä että esim. irtisanotulle henkilölle tarjotaan jotain muuta työtä.

**Comment by LeKorsu** [comment]
Kaipaa varmaan huomautusta, Minä tajusin vasta, mistä on kyse, kun klikkasin noita linkkejä.

**Comment by mariaforsen** [comment]
Sv. ersättande arbete
