### ISSUE TITLE
parafraasit (kirjallisuus)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5824]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[parafraasit (kirjallisuus)](http://www.yso.fi/onto/ysa/Y142589) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sulkutarkenne vaihdettava/poistettava? 

#### Perustelut ehdotukselle   

Jaettu nyt parafraasit (kirjallisuus) ja parafraasit (musiikki). Melindan viitteitä korjatessa todettiin, että on lisäksi aineistoa parafraasista kuvataiteessa, mahdollinen myös ainakin elokuvataiteessa (https://fi.wikipedia.org/wiki/Pastissi#Parafraasi). Voidaan joko jakaa ketjutusta vastaavilla sulkutarkenteillä eri taiteenlajeihin, tai yhdistää kaikki (tai mahd. säilyttää parafraasit (musiikki) alakäsitteenä yleiselle parafraasit-käsitteelle). 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mariaforsen** [comment]
Voi viitata myös esim. kuvataiteeseen, ainakin ruotsiksi. Olisiko parafraasit (teokset)/(taide) tms. mahdollinen?
SAO: parafraser (konst), parafraser (musik)

**Comment by krinay** [comment]
Tieteen termipankki: kielitiede ja käännöstiede:
"sananmukaisen ja vapaan käännöstavan välin sijoittuva kääntämisen tapa, jossa kääntäjä ilmaisee toisin sanoin alkutekstin merkityksiä"
Tieteen termipankki: kirjallisuudentutkimus:
"kaunokirjallisen tekstin osien ja sisällön esittäminen toisin sanoin, yleensä asiaproosaa käyttäen"

YSA:n termin _parafraasit (sävellykset)_ määritelmä vaikuttaa minusta hyvin samantapaiselta:
"Yhden tai useamman sävelmän muokkaaminen vapaasti muunnellen uudeksi teokseksi."

Voisiko yhdistää kaikki?

**Comment by mirmaid** [comment]
Ainakin suomeksi on aika vaikeaa ellei mahdotonta keksiä sulkutarkennetta joka kattaisi muut taiteenlajit paitsi musiikin.

**Comment by MUUSA-kokous** [comment]
Otetaan SLM:ään parafraasit (musiikki).

Otetaan tämä issue käsittelyyn YSAn ja Muusan yhteiseen linjauskokoukseen.

**Comment by YSA-kokous** [comment]
parafraasi

parafraasi + parafraasit (sävellykset)

parafraasi(t) (kirjallisuus) + parafraasit (sävellykset) + parafraasi(t) (kuvataide) + parafraasi(t) (elokuva)

parafraasi + parafraasi(t) (kirjallisuus) + parafraasit (sävellykset) + parafraasi(t) (kuvataide) + parafraasi(t) (elokuva)

**Comment by YSA-kokous** [comment]
Nykyinen jako, ja lisäksi joko pelkkä _parafraasi_ tai _parafraasit (kuvataide)_. Seuraava kokous.

**Comment by mirmaid** [comment]
parafraasit (musiikki) / SLM

**Comment by mirmaid** [comment]
Melindassa vain muutamia viitteitä jäljellä.

**Comment by satuniininen** [comment]
Jäljellä 6, joista 4 käsittelee kuvataidetta. 
2 käsittelee valokuvataidetta, molemmissa myös _mukaelmat_.

**Comment by YSA-kokous** [comment]
parafraasit (kuvataide)

**Comment by mariaforsen** [comment]
Sv. parafraser (bildkonst)
