### ISSUE TITLE
yritysketjut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5826]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yritysketjut 

#### Ehdotettu termi englanniksi   

Business Chains 

#### Vaihtoehtoiset termit ja ilmaisut   

liikeketjut 
ketjut (yritykset) 

#### Alakäsitteet (RT)   

[kauppaketjut](http://www.yso.fi/onto/yso/p18990) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

YSAssa aiemmin jaettu ketjut -> ketjut (järjestelmät) & ketjut (esineet), joista kumpikaan ei sovi n. 30 Melinda-viitteeseen, jotka käsittelevät esim. hotelliketjuja, ravintolaketjuja ja huoltoasemaketjuja.

Toinen vaihtoehto ottaa YSAan erikseen hotelliketjut, ravintolaketjut jne. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ks. Melinda 

#### Tarkoitusta täsmentävä selite   

http://st.merig.eu/index.php?id=67&L=2&tx_a21glossaryadvancedoutput_pi1[char]=y&cHash=63ada4caf6 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [yritysketjut](http://finto.fi/yse/fi/page/Y505826)

**Comment by vthuhtala** [comment]
Mikä ero: 'yritysketjut' <-> 'yritykset'

**Comment by mariaforsen** [comment]
Entä ketjuyritys? (sv. kedjeföretag)

**Comment by mariaforsen** [comment]
Sv. företagskedjor ET kedjeföretag
