### ISSUE TITLE
sinappi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5827]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sinappi](http://www.yso.fi/onto/ysa/Y109272) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

altLabel  'sinapit' 'senaper' viittaa myös  Sinapis -kasvisukuun joten se saattaa tarvita sulkutarkenteen
ehdotus:
sinapit (kastikkeet)  esim.  https://www.foodie.fi/products/962
sinapit (maustekasvit) esim. https://www.laji.fi/taxon/MX.38498,  http://finto.fi/kassu/fi/page/k31265 

#### Perustelut ehdotukselle   

monikkomuoto sinapit viitaa myös kasvisukuun, jolle tarvitaan oma käsite.  Kassussa ja laji.fi:ssä se on muotoa Sinapit ( eikä esim. sinappikasvit).  Ruotsiksi senaper. 

#### Ehdottaja   

Jarmo Saarikko 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

jarmo.saarikko@helsinki.fi

**Comment by mirmaid** [comment]
Tämä on aika ongelmallinen setti, koska sinappikasvit jakaantuvat kahteen sukuun, _Sinapis_ (sinapit) ja _Brassica_ (kaalit). Melindan viitteistä ei aineistoa näkemättä pysty kaikissa tapauksissa päättelemään kummasta on kyse, ja _sinapit_-termiä käytettäisiin todennäköisesti jatkossakin helposti väärin myös Brassica-suvun lajeista. 

Nyt _ketsuppi, sinappi_ ja _majoneesi_ mausteina ovat yksikössä, joten jos lisätään tarkenne, olisi _sinappi (mausteet)_. Yksi mahdollisuus olisi ottaa "epätieteellinen" _sinappikasvit_ viljelyä ym. käyttöä varten (kattaisi molempien sukujen lajit).

**Comment by mariaforsen** [comment]
Ruotsiksi senap "kastikkeena" on yksikössä ja kuuluukin olla (sitä ei yleensä taivuteta), mutta jos se koetaan  välttämättömäksi voidaan lisätä "(kryddor)" tarkenteena.

**Comment by PaiviLipsanen** [comment]
Jos otetaan kasvit, ehdotan hierarkiaa
ristikukkaiskasvit
- kaalit (Brassica), tosin YSAssa on jo kaalit - yläkäsite vihannekset
- sinapit (Sinapis)

Kaalien hierarkia on hiukan monimutkainen. Kaalin/vihanneskaalin (Brassica oleraceae) muunnos on keräkaali ja muita syötaviä kaalin muotoja ei laji.fi:stä löydykään. AFOn hierarkia on peräisin Viljelykasvien nimistöstä (2012) ja Kassusta.

**Comment by YSA-kokous** [comment]
sinappi (mausteet)
