### ISSUE TITLE
ikonologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5828]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ikonologia](http://www.yso.fi/onto/ysa/Y101788) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termille määritelmä, KT-muoto "tulkitseva ikonografia" ynnä RT-suhde asiasanaan "kuva-analyysi" 

#### Perustelut ehdotukselle   

Tällä hetkellä "ikonografia" ja "ikonologia" ovat käyttäjän kannalta erittäin epäselviä asiasanoja, kun kummallakaan ei ole määritelmää. Jouko Tolvasen (Taidesanakirja, s. 233) mukaan "ikonologia tarkoittaa ikonografista kuvatulkintaa, jossa on keskeisenä aatehist. rakenneanalyysi" ja Riitta Konttisen ja Liisa Laajoen (Taiteen sanakirja, s. 151) mukaan "ikonologia (tulkitseva ikonografia) pohjautuu ikonografisen analyysin tuloksiin ja pyrkii tulkitsemaan aiheen sisäistä merkitystä ja sisältöä, kuvan välittämää maailmankatsomusta". 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Nationalencyklopedin: "Termerna används idag oftast synonymt. Ikonografi var ursprungligen beteckningen på en hjälpvetenskap till historien, använd beträffande antika porträtt och mynt. Ikonologi betecknade från början en handbok, innehållande symboler och allegoriska figurer, avsedd att vara till hjälp för konstnärer..."
SAO: ikonografi KT ikonologi

**Comment by mirmaid** [comment]
LCSH:ssa vain _Iconography_
Wikipediassa pitkä artikkeli kummastakin:
https://en.wikipedia.org/wiki/Iconography
https://en.wikipedia.org/wiki/Iconology

**Comment by mirmaid** [comment]
_Toinen 1800-luvulla syntynyt tutkimussuunta on ikonografia, jonka kysymyksenasettelut pyrkivät tunnistamaan ja kartoittamaan erilaisia kuva-aiheita. Ikonografiaa eli kuva-aiheiden vertailevaa tutkimusta pidetään yhtenä kuvien tutkijoiden perustyövälineistä, jonka avulla selvitetään aiheen sopimuksenvaraisia merkityksiä traditioiden pohjalta._ https://viestintatieteet-wiki.wikispaces.com/Kuvanlukutaito

_Kolmannessa ja syvimmässä tulkinnan vaiheessa, ikonologisessa tulkinnassa, tarkastellaan, miten teoksen syntyajankohdan katsomusjärjestelmät ja aatteelliset virtaukset ilmenevät teoksessa. Tämä edellyttää tulkitsijalta laajaa tietämystä muun muassa filosofian, kirjallisuuden, uskonnon ja politiikan aloilta. Taideteos pyritään näkemään laajassa kulttuurihistoriallisessa yhteydessä, eräänlaisena aikakauden symbolina._
https://viestintatieteet-wiki.wikispaces.com/Kuvanlukutaito#Ikonologia

**Comment by mariaforsen** [comment]
Näitä ei voi varmaan kovin helposti määritellä, ainakin ruotsiksi on selkeää että eri tutkijat ovat (olleet) eri mieltä siitä mitä tämä tarkalleen on.  Ja myös ajan kanssa on merkitys vaihdellut. Tässä tapauksessa olisi varmaan hyvä että yksinkertaisesti käytettäisiin se sana mitä kuvailtavassa aineistossa käytetään.

**Comment by YSA-kokous** [comment]
Lisätään ehdotetut suhteet, ei muita muutoksia.
