### ISSUE TITLE
minimalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5829]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[minimalismi](http://www.yso.fi/onto/ysa/Y103535) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia: (1) "minimalismi" [ryhmä 90]; (2) "minimalistinen musiikki" [ryhmä 89], KT "repetitiivinen musiikki", "repetitiomusiikki" ja "toistomusiikki", LT "musiikki". (1) vastaa näistä YSAn entistä "minimalismi"-asiasanaa, (2) taas MUSAn entistä "minimalismi"-asiasanaa. 

#### Perustelut ehdotukselle   

Musasta Ysaan tuotua "minimalismi"-asiasanaa ei sinällään voi yhdistää Ysan "minimalismi"-asiasanaan, koska KT-muodot eivät vastaisi yhdistetyn käsitteen kattamaa kokonaisuutta. Niinpä minimalismi yleisenä esteettisenä käsitteenä pitäisi jättää yleiseksi, ja minimalistista musiikkia vanhastaankin tarkoittanut Musan käsite pitäisi muuttaa yksiselitteiseksi ja helpommin hahmottuvaksi; "minimalistinen musiikki" pitäisi olla ongelmaton. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. minimalism, minimalistisk musik

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: kannatetaan termin jakamista ehdotetulla tavalla.

**Comment by YSA-kokous** [comment]
Muusa: jos ohjaustermit lisätään, tarvitaanko silti erillistä termiä?

**Comment by jtuohini** [comment]
"Muusa: jos ohjaustermit lisätään, tarvitaanko silti erillistä termiä?": mitä tällä kysymyksellä tarkoitetaan? Erillistä termiä mihin? Tarvitaan yksi termi minimalismi yleistaiteellisena käsitteenä ja toinen termi minimalistiselle musiikille, sisältäen alkuperäisessä ehdotuksessa luetellut KT-muodot.

**Comment by mirmaid** [comment]
Kysyttiin siis, voiko termin _minimalistinen musiikki_ korvata lisäämällä mainitut ohjaustermit termille minimalismi.

**Comment by jtuohini** [comment]
Ei voi korvata näitä kahta erillistä käsitettä yhdellä, koska **minimalismi** koskee taidetta yleensä ja esimerkiksi _repetitiomusiikki_ ainoastaan musiikkia, siis sitä musiikkia, josta käytettäisiin asiasanaa **minimalistinen musiikki**. Repetitiomusiikki-sanasta ei voi rakentaa viittauslinkkiä suoraan minimalismiin, koska muuten asiakas saatettaisiin johtaa aineistoon, joka käsitteleekin vaikkapa arkkitehtuuria.

**Comment by MUUSA-kokous** [comment]
Siirretään tämä YSAn ja Muusan yhteisen linjauskokouksen asialistalle.

**Comment by YSA-kokous** [comment]
Minimalistinen musiikki, Muusa laatii määritelmän. LT taidemusiikki, RT minimalismi. KT minimalismi (musiikki)?

**Comment by jtuohini** [comment]
Määritelmäehdotus Muusalle: "1960-luvulla syntyneen minimalistisen tyylisuuntauksen piiriin luettava taidemusiikki, jolle on ominaista toisteisuus ja tarkoituksellisen yksinkertaistettu rytminen, melodinen ja harmoninen sävelkieli."

**Comment by mirmaid** [comment]
minimalistinen musiikki / SLM
