### ISSUE TITLE
happening

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5830]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[happening](http://www.yso.fi/onto/ysa/Y106788) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "happeningit" 

#### Perustelut ehdotukselle   

Asiasana viittaa ennemmin tapahtumiin kuin taidemuotoon sinänsä. Ks. myös suomenkielinen Wikipedia, johon on valittu monikkomuoto (https://fi.wikipedia.org/wiki/Happeningit) 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. happeningar ET happenings

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: kannatetaan ehdotusta.
