### ISSUE TITLE
elegiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5831]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elegiat](http://www.yso.fi/onto/ysa/Y101139) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan asiasana kahtia: (1) "elegiat (runot)", joka vastaisi YSAn nykyistä asiasanaa, ja (2) "elegiat (sävellykset)", joka vastaisi MUSAsta YSAan tuotua asiasanaa. (1) pysyisi siis ennallaan ja (2) kuuluisi ryhmään 89 ja sen LT olisi "sävellykset" ja RT:t "lamentot" ja "valituslaulut" ja huomautuksessa voisi mainita tuon runoelegian. 

#### Perustelut ehdotukselle   

MUSAa YSAan yhdistettäessä vastaan tullut samanmuotoinen asiasana, joilla on keskenään selvästi eri merkitys ja joita ei siksi voida yhdistää. Grove Music Onlinen mukaan musiikillinen elegia on "A setting of a poem, or an instrumental piece, lamenting the loss of someone deceased." 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Kannatan musiikin puolen termimuotoa _elegiat (sävellykset)_ ja siihen ehdotetut LT- ja RT-suhteet.

**Comment by jtuohini** [comment]
Ja vielä täydennykseksi LCSH-vastine: **elegiat (runot)** = [**Elegiac poetry**](http://id.loc.gov/authorities/subjects/sh85042473) (KT _Elegies_, _Lamentations_); musiikillisille elegioille ei vastaavaa ei ole.

**Comment by ksornova** [comment]
Muusa-kokous (6.3.2018): kannatetaan muotoa "elegiat (sävellykset)"
