### ISSUE TITLE
teemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5832]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teemat](http://www.yso.fi/onto/ysa/Y99350) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan asiasana tarpeen mukaan kahtia: (1) "teemat (kirjallisuus)", ryhmä 87 (ellei tarve huomioida temaattisuutta myös esimerkiksi elokuvissa), LCSH-vastine "Themes, motives" [http://id.loc.gov/authorities/subjects/sh87002064], ja (2) "teemat (musiikinteoria)", ryhmä 89, LT "musiikinteoria", RT "melodiat" 

#### Perustelut ehdotukselle   

Kyse kahdesta eri asiasta, joita ei välttämättä voi yhdistää yhden asiasanan alle; asia tullut vastaan MUSAa YSAan sulautettaessa. Kummankin merkitys: (1) Tieteen termipankin mukaan "kirjallisen teoksen perusajatus, joka havaitaan erilaisten motiivien toistumisen kautta ja joka synnyttää teoksen rakenteellisen ja sisällöllisen koherenssin; myös lukijan tulkinta teoksen merkityksestä". (2) Grove Music Onlinen mukaan "The musical material on which part or all of a work is based, usually having a recognizable melody and sometimes perceivable as a complete musical expression in itself, independent of the work to which it belongs" ja englanninkielisen Wikipedian mukaan "the material, usually a recognizable melody, upon which part or all of a composition is based. In forms other than the fugue, this [i.e. subject] may be known as the theme." 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Kannatan lisäystä musiikin asiasanaan.

**Comment by ilonahei** [comment]
Olisiko vielä tarkemmin osuva "teemat (musiikkianalyysi)", LT "musiikkianalyysi"? Ja itse asiassa pitäisikö "musiikkianalyysi"-termin LT olla "musiikinteoria"?

**Comment by mirmaid** [comment]
Melindan ensimmäinen viite selaushaulla teemat (ysa): _Twenty-first century musicals : from stage to screen_.

**Comment by mariaforsen** [comment]
Kyllä ainakin ruotsiksi sekä teman että ämnen ovat tärkeitä (merkitys ei ole sama), mutta "yleisteema" olisi kyllä syytä pitää hyvin laajana, esim. yllä mainittu "teemat (aiheet)", jos on aivan välttämätöntä jakaa teemaa.

**Comment by jtuohini** [comment]
Musiikista puhuttessa "teema" viittaa musiikilliseen materiaaliin, "aihe" teoksen ulkopuolelle. Joten musiikissa "teema" ei esiinny tuossa Tuomaksen mainitsemassa toisessa merkityksessä. Kirjallisuudessa vastaavasti "aihe"/"teema"-jaottelu on selkeä, mutta siis eri tavalla (ks. Tieteen termipankin määritelmä yllä). (Dylan-esimerkkikään ei koske musiikkia, vaan laululyriikkaa ja sen käsittelemiä aiheita ja/tai teemoja.)
 
Mutta mikä pitäisi musiikin puolellaasiasanan tarkenne, "musiikinteoria" vai "musiikkianalyysi"? Tässä muusalaisten arivonystyröitä tarvitaan todella, samoin kuin **musiikkianalyysi**- ja **musiikinteoria**-asiasanojen keskinäisen suhteen mahdollinen muuttamisessa!

**Comment by jtuohini** [comment]
Yksi lisähuomio vielä: YSAssa on tällä hetkellä "_tematiikka_ KÄ **aiheet**"!

**Comment by asormune** [comment]
Kuuluisiko musiikkianalyysi paremmin musiikkitieteen alle. Mutta päätimmekö jo aiemmin jotain termistä musiikkitiede??

**Comment by ilonahei** [comment]
Musiikinteoria määritellään YSAssa näin: Musiikin rakenteiden (rytmi, säveljärjestelmät, melodia, harmonia, äänenväri tms.) tutkimisen ja mallintamisen menetelmä ja esitystapa. 

Musiikkianalyysin määrittely: Musiikinteoreettinen käsite, jolla tarkoitetaan sävelteoksen teoreettista erittelyä sekä sävellyksen rakenteen ja ominaisuuksien tutkimista.

Näiden määritelmien perusteella musiikkianalyysi on mielestäni osuvampi tarkenne teemat-asiasanalle, musiikissahan teema liittyy olennaisesti _teoksen_ tutkimiseen.

Pitäisikö musiikkianalyysin ja musiikinteorian keskinäisen suhteen pohtiminen jättää seuraavaan kokoukseen?

**Comment by satuniininen** [comment]
Kannatan Tuomaksen ehdottamaa **teemat (aiheet) KÄYTÄ aiheet** ja sen lisäksi musiikkikontekstiin rajattu **teemat** + sulkutarkenne.

**Comment by jtuohini** [comment]
Olisiko sitten tuo ryhmän 89 termi _teemat (musiikkianalyysi)_? Ainakin mielestäni joko se tai _teemat (musiikinteoria)_, mutta ei _teemat (musiikki)_, joka voisi tarjota mahdollisuuden ymmärtää termillä tarkoitettavan musiikin käsittelemää aihetta. Sulkutarkenteen valinta suoraan ST/LT-suhteeseen ja sen määrittelemiseen, joten sikäli olisi hyvä pohtia sitäkin pian. Itselläni ei vahvaa kantaa, kun on osa aika sekavaa käsitejoukkoa **musiikinteoria**, **musiikintutkimus**, **musiikkianalyysi** ja **musiikkitiede**.
 
Vertailun vuoksi vielä LCSH, jossa teemalle ei yllätys kyllä ole omaa asiasanaa:

**Music theory** (_Musical theory_, _Theory of music_)
Narrower Term:  Carnatic music--Theory.
Narrower Term:  Counterpoint.
Narrower Term:  Harmony.
Narrower Term:  Hindustani music--Theory.
Narrower Term:  Melody.
Narrower Term:  Music--Philosophy and aesthetics.
Narrower Term:  **Musical analysis**.
Narrower Term:  Musical intervals and scales.
Narrower Term:  Musical meter and rhythm.
Narrower Term:  Nature and music theory
Narrower Term:  Symmetry (Music)

**Musical analysis** (_Analysis, Musical_, _Analytical guides (Music)_, _Hermeneutics (Music)_, _Music--Analysis, appreciation_, _Music--Analytical guides_, _Music analysis_)
Search also subdivision "Analysis, appreciation" under headings for forms and types of music.
Narrower Term:  Harmonic analysis (Music)
Narrower Term:  Melodic analysis.
Narrower Term:  Schenkerian analysis.
See Also:  Music appreciation.

**Musicology** (_Music--Research_, _Musical research_, _Research, Musical_)
Narrower Term:  Ethnomusicology.
Narrower Term:  Music archaeology.
Narrower Term:  Music--Editing.
Narrower Term:  National socialism and musicology
Narrower Term:  Sound recordings in musicology.
See Also:  Music--Historiography.
See Also:  Popular music--Historiography.

**Comment by ksornova** [comment]
Muusa-kokous (13.3.2018): teemat (musiikki) ja sen LT musiikkianalyysi, RT motiivi
Määritelmä: Sävellyksen perustan useammasta motiivista muodostuva, omaleimainen musiikillinen idea tai ajatus.
Käyttöhuomautus: Sävellyksen käsittelemästä aiheesta käytetään termiä aiheet (TAI JOTAIN SELLAISTA)

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by asormune** [comment]
Muutamia määritelmiä:

"Otavan iso musiikkitietosanakirja": Teema = Yksilöllinen musiikillinen aihekokonaisuus, joka on sävellyksessä keskeisessä asemassa esittelyn, kertauksen muuntelun tai kehittelyn kohteena. Teeman yksilöllisyys perustuu tavallisesti sen melodisiin ominaisuuksiin. (Käsitteiden teema, melodia ja motiivi rajat peittävät osittain toisensa...)

Musiikkisanakirja/Brodin:  Teema = Täydellinen ja omaleimainen musiikillinen ajatus, joka muodostaa sävellyksen perustan. Sanoja teema ja motiivi käytetään toisinaan samassa merkityksessä, mutta motiivi on pienempi yksikkö, kokonaisen teeman luonteenomainen pääosa. 

Suuri musiikkikirja (1959): Teema = Sävelaihe, jonka varaan sävellyksen teemallinen muodostus rakentuu.

**Comment by mirmaid** [comment]
Yksi mahdollisuus voisi ehkä olla myös teemat (kerronta) ja sitten kun se ei sovi niin aiheet? En tiedä onko mitenkään mahdollista poistaa teemaa kirjallisuustieteen terminä kokonaan.

http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:teema

**Comment by mariaforsen** [comment]
Ruotsiksi ainakin hyvin vaikeaa poistaa teemaa kirjallisuuden terminä. Ks. myös https://fi.wikipedia.org/wiki/Teema_(kirjallisuus) ja https://sv.wikipedia.org/wiki/Tema_(narratologi) Teema ei ole sama asia kuin aihe. 
"Kirjallisuudessa teema eli perusajatus tarkoittaa sitä, mitä aiheesta sanotaan. Teoksen aihe voi esimerkiksi olla murha, mutta teemoina esimerkiksi kosto, rakkaus, mustasukkaisuus, ystävyys tai petos. Teema kertoo teoksen keskeisen sanoman, eli teema kuvaa teoksen perusideaa."

**Comment by krinay** [comment]
Edellä on jo esitetty hyviä määrittelyjä kirjallisuudentutkimuksen näkökulmasta, mutta tässä vielä yksi Tieteen termipankista:
"Aihe ja teema on syytä erottaa toisistaan. Esimerkiksi Väinö Linnan Tuntemattoman sotilaan (1954) aiheena on Suomen jatkosota pienen sotilasjoukon kokemana, kun taas romaanin teemaksi saatetaan tulkita esim. sodan mielettömyys tai suomalaisen sotilaan sankarillisuus. Teoksen **aihe on yleensä suhteellisen vaivatonta määritellä** - usein se käy ainakin alustavasti ilmi jo kirjan nimestä - kun taas **teema on tulkintaa vaativa asia**." [Lihavoinnit minun]

En ihan hahmota eroa musiikin ja kirjallisuuden teemojen välillä, mutta uskon asiantuntijoita.

**Comment by YSA-kokous** [comment]
teemat (kerronta)

**Comment by mirmaid** [comment]
Otetaanpa vielä kerran tämä kokonaisuus - nyt siis löytyy

- johtoaiheet (musiikki)

- sävelmotiivit (edellisen LT)

- melodiat

- motiivit (käsittelyssä) https://github.com/Finto-ehdotus/YSE/issues/6056

- teemat

- aiheet

Onko ihan varmaa että kaikki tämä jaottelu on tarpeen musiikissa? Jos teemat jaetaan ja tarkenteeksi tulee (musiikki), on kyllä riski olemassa että sitä käytetään sanoitusten teemoista.

**Comment by jtuohini** [comment]
Musiikilliset teemat ovat ihan eri asia kuin kirjallisuuden teemat: edelliset ovat säveltäjän käyttämiä "rakennuspalikoita", jotka kuulija parhaimmillaan muistaa ja joita hyräilee (mielessään tai jopa ääneen), jälkimmäinen taas juuri sitä, minkä Kristiina Näyhö niin hyvin toi esille. Sävellyksen teemat tai teemat eivät sinällään siis liity (sävellyksen) aiheeseen (eikä sitä kuvaava termi saa suhdetta **aiheet**-asiasanaan), kun taas kirjallisuuden teemalla tai teemoilla on suora tai epäsuora yhteys kirjan käsittelemään aiheeseen (ja sitä kuvaava termi siis saa suhteen samaiseen asiasanaan).

**Comment by tpalonen** [comment]
Teemat-termin erityisyys musiikin puolella on selviö, mutta tarvitaanko todella sen lisäksi vielä motiivit, sävelmotiivit ja johtoaiheet? Helpotetaanko vai vaikeutetaanko tällä pirstaloimisella tiedonhakijan työtä?

**Comment by tpalonen** [comment]
Teemat-termin erityisyys musiikin puolella on selviö, mutta tarvitaanko todella sen lisäksi vielä motiivit, sävelmotiivit ja johtoaiheet? Helpotetaanko vai vaikeutetaanko tällä pirstaloimisella tiedonhakijan työtä?

**Comment by jtuohini** [comment]
Tarvitaan. Koko Musiikin asiasanaston "ysottaminen" perustui siihen lähtökohtaan, ettei termeistä jouduta luopumaan. Yleisemmin: hyvin rakennetun ontologian pitäisi kyetä ratkaisemaan nimenomaan tällaiset hienosyiset asiat oikeaan osuvalla hierarkisoinnilla, jossa IS A- ja PART OF -suhteet johtavat käyttäjän saamaan kaipaamaansa aihepiiriä käsittelevän aineiston sillä tarkkuudella kuin haluaa – tietysti sillä ehdolla, että hakujärjestelmä kykenee hyödyntämään ontologisoituja asiasanastoja.

**Comment by mirmaid** [comment]
Ongelmana ei ole näiden sijoittaminen YSOon. Jos ollaan yhtä mieltä siitä, että kaikkien näiden termien ottaminen sanastoon parhaalla tavalla palvelee tiedonhakijaa (eli sekä tiedonhakijat että sisällönkuvailijat osaavat niitä johdonmukaisesti käyttää, eivätkä ne ole toistensä kanssa päällekkäisiä), niin sitten ne otetaan sanastoon. 

**sävelmotiivit:** _Musiikinteoreettinen käsite, jolla tarkoitetaan pienintä musiikillisesti mielekästä sävelkulkua, aihetta tms. elementtiä. Useasta motiivista muodostuu teema._

**johtoaiheet (musiikki)** [edellisen ST]: _Ohjelmamusiikissa, oopperoissa ja muussa draamallisessa musiikissa käytettävä sävelaihe, joka symboloi tiettyä henkilöä, esinettä tai tilannetta._ [Koska tämä hierarkian perusteella on tietynlainen sävelmotiivi, ehdotan että se näkyy myös määritelmässä.]

**melodiat:** _Peräkkäisinä sävelinä etenevä sävelkulku, joka muodostaa selkeänä hahmottuvan kokonaisuuden joko yksinään, rytmisten ja/tai harmonisten osuuksien säestämänä tai osana moniäänistä (polyfonista) tekstuuria._ [Ei mitään suhdetta kahteen edelliseen, mutta kuulostaa määritelmän perusteella liittyvän läheisesti niihin, samoin kuin teemat-käsitteeseen. Koska sekä tämä, että _sävelmotiivit_ määritellään sävelkulkuna, niiden ero pitäisi selkeyttää.]

**teemat (musiikki):** _säveltäjän käyttämiä "rakennuspalikoita", jotka kuulija parhaimmillaan muistaa / the material, usually a recognizable melody, upon which part or all of a composition is based / Sävelaihe, jonka varaan sävellyksen teemallinen muodostus rakentuu._ [Määritelmäehdotusten mukaan tämä on myös sävelaihe (=sävelmotiivi) tai melodia, joten merkitysero on kuvattava selkeästi tulevassa varsinaisessa määritelmässä, jos tämäkin päätetään hyväksyä. Toisaalta _sävelmotiivit_-termin määritelmän mukaan teema muodostuu useista sävelmotiiveista.]

**Comment by YSA-kokous** [comment]
Muusa tarkentaa määritelmiä. _Teemat (musiikki)_ -termille toivotaan selkeämpää tarkennetta.

**Comment by YSA-kokous** [comment]
Teemat (musiikki) -käsitettä ei toistaiseksi hyväksytty sanastoon, koska odotellaan määritelmää ja varmuutta siitä, että tämä on erillinen ja kuvailussa tarpeellinen käsite melodioiden, sävelmotiivien ja johtoaiheiden lisäksi. Sanastoon on hyväksytty jo "teemat (kerronta)" erotukseksi tästä. Yksi mahdollisuus olisi lisätä "teemat (musiikki)" lisättäisiin ohjaustermiksi melodioille, sävelmotiiveille ja johtoaiheille; tällöin käyttäjää ohjattaisin näiden termien äärelle eikä käyttäjä käyttäisi väärin "teemat (kerronta)" käsitettä musiikin yhteydessä. Eli: onko teemat-käsite todella tarpeellinen musiikin kuvailussa erillisenä käsitteenä melodioiden, sävelmotiivien ja johtoaiheiden lisäksi vai pärjättäisiinkö näillä kolmella?

**Comment by AuHo22** [comment]
Mielestäni teemat (kerronta) ei voida hyväksyä kirjallisuuden yhteydessä, koska tällöin teema jää ikäänkuin "teoksen sisälle", kerronnan palikaksi. Teema kuitenkin syntyy teoksen tulkinnasta, kuten yllä, "**teema on tulkintaa vaativa asia**" ja ulottuu teoksen ulkopuoliseen repertoaariin. Teema (kerronta) jää lähelle motiivia, joka on kerronnassa toistuva elementti.
Rautalankaa esim.:
https://peda.net/jao/schildtin_lukio/opiskelu/kurssituops/aidinkieli/kkjt/%C3%A4i3-puul/verkko3-2/etusivu/2kl/proosa-jonna/motiivit

Tarvitaan aiheet, motiivit - nykyisin motiivit (aihelmat)  ja teemat -> po. vaikkapa teemat (kirjallisuus)

**Comment by AuHo22** [comment]
Tässä vielä Outin kiireinen lisäys asiaan minun välittämänäni:
Hosiaisluoma: "Aihe ja teema on syytä erottaa toisistaan. [--] Esimerkiksi Linnan Tuntemattoman sotilaan aiheena on Suomen jatkosota [--], kun taas romaanin teemaksi saatetaan tulkita esim. sodan mielettömyys."

**Comment by krinay** [comment]
Tarkenteeksi valittiin varmaan aikoinaan kerronta (kirjallisuuden sijasta), koska se on sallivampi. Teema on tärkeä käsite myös folkloristiikassa, mm. suullisen epiikan tutkimuksessa. Tieteen termipankki: Folkloristiikka: 
**Teema**
"Määritelmä: perinteen esityksen johtoaihe
Selite: Eeppisen (lyyrisen, draamallisen) esityksen johtoaihetta tai perusajatusta (esim. hybris-nemesis -teema, uskollisuusteema) tai läpikäyvää säiettä; voidaan myös puhua saman kansanrunoustuotteen rinnakkaisteemoista tai pää- ja sivuteemoista."

**Comment by AuHo22** [comment]
Tässä on mitä ilmeisemmin tieteenalojen välistä eroavaisuutta. Kuten selite sanookin, tässä kuvataan melko pitkälle sitä, mitä kirjallisuudentutkimuksessa käsitettäisiin motiiviksi: "Eeppisen (lyyrisen, draamallisen) esityksen johtoaihetta--tai läpikäyvää säiettä". 
Jaettavaksi sitten:
Teemat (folkloristiikka/kansanrunous) ja teemat (kirjallisuus/kaunokirjallisuus/kirjallisuudentutkimus)?

**Comment by krinay** [comment]
En usko, että on niin olennaista eroa, että tarvittaisiin kahta termiä. Myös motiiivi on folkloristiikassa hyvin keskeinen käsite. Folkloristiikan termipankista edelleen:
**Motiivi**
"Määritelmä: sisällöllinen yksikkö proosa- tai runotekstissä
Selite: Motiivin vastineena käytetään usein aihelmaa, joskus myös elementtiä tai piirrettä. Ihmesadun esine, joka alkaa vuotaa verta sen omistajan kuoltua ("life-token", elossaolomerkki), on tyypillinen motiivi. Folkloristit ovat käyttäneet motiivi-termiä löysästi. Esimerkiksi S. Thompsonin teoksessa Motif-Index of Folk Literature 'motiivi' voi tarkoittaa kertomuksen aihetta tai pääteemaa ("Creation of the Sun"), tapahtumajaksoa ("The Obstacle Flight", ihmeellistä pakoa) tai kertomusmaailman piirrettä ("joentakainen tuonela", "merenneidon lumivalkea iho"). Tämän vuoksi motiivi-termiä käytettäessä tulee määritellä sen suhde tekstikokonaisuuteen ja laajempiin sisällöllis-formaalisiin yksiköihin kuten teemaan, episodiin, perus- ja osatapahtumiin."

**Comment by AuHo22** [comment]
Niin, eli voimmeko siis tulkita suullisen epiikan olevan myös laajasti kertovaa kirjallisuutta -> teemat (kirjallisuus)?

**Comment by tpalonen** [comment]
En kannata enempää pilkkomista tälle käsitteelle ja aihepiirille, joka on jo nyt hyvin kirjava. Toisaalta en usko, että kuvailijat käyttäisivät käsitettä muussa kuin painetun (kauno)kirjallisuuden yhteydessä, jos termi olisi teemat (kirjallisuus).

Yksi vaihtoehto voisi olla: _kertomusten/kertomuksen teemat_.

Sivuhuomio: ohjaustermi tematiikka ohjaa nyt aiheet-käsitteeseen. Pitäisikö pikemminkin ohjata teemat-käsitteeseen?

**Comment by AuHo22** [comment]
Kun käy YSO-termin **kerronta**-käsitteen ala- ja assosiatiivisia käsitteitä katsomassa YSOsta, niin ne rajautuvat ns. narratologiaan, eli kerronnan eri muotojen, narratiivisten tai kerronnallisten rakenteiden sekä kertojahierarkioiden tutkimiseen. Tästäkin syystä sulkutarkenne (kerronta) on hyvin huono kuvaamaan sitä, mistä kaunokirjallisuuden teemojen tulkinnassa on oikein kysymys. Ihan kaikkia mutkia ei kuitenkaan voi vetää suoriksi.

**Comment by YSO-kokous** [comment]
Ensisijaisesti kaivataan Muusan kommenttia YSA-kokouksen kommenttiin 9.12.2019. Jos ei Muusalta tule uutta ehdotusta/selvennystä niin katsotaan, että asia on toistaiseksi käsitelty ja "teemat (musiikki)" ei oteta sanastoon.

Sanastoon jo hyväksyttyyn "teemat (kerronta)"-muotoon ei muutoksia. Asia on jo kertaalleen keskusteltu.

**Comment by jaskaj** [comment]
Muusa käsittelee asian huomisessa (14.5.2020) kokouksessa ja kommentoi sen jälkeen.

Jaska Järvilehto
puheenjohtaja
Musiikin metatiedon asiantuntijaryhmä Muusa

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa käsitteen teemat (musiikki) ottamista YSOon ja tekee aiheesta uuden ehdotuksen.

**Comment by tpalonen** [comment]
Muusa-kokouksessa todettiin myös, että uuteen ehdotukseen tulee myös määritelmä, jossa myös viittaus johtoaiheisiin/sävelmotiiveihin, että ei ole sekaannuksen vaaraa.

**Comment by AuHo22** [comment]
Ehkä teemat (kerronta) ryhmäksi täytyy kirjallisuuden 85 ja kansanperinteen 50 lisäksi ottaa sitten myös kielitiede 87?
Termin teemat (kerronta) perusteluista yllä: "Tarkenteeksi valittiin varmaan aikoinaan kerronta (kirjallisuuden sijasta), koska se on sallivampi. Teema on tärkeä käsite myös folkloristiikassa, mm. suullisen epiikan tutkimuksessa." Myös kielitieteessä:

https://trepo.tuni.fi/bitstream/handle/10024/83464/gradu05833.pdf?sequence=1&isAllowed=y
http://www.kotikielenseura.fi/virittaja/hakemistot/jutut/2008_24.pdf

**Comment by tpalonen** [comment]
Asiaa käsiteltäneen seuraavan kerran torstai-iltapäivänä 11.6.  Muusa-kokouksessa.

**Comment by AuHo22** [comment]
teemat (kielitiede) KÄ teema-reema-rakenne
teemat (kerronta) voi sitten käyttää myös elokuvataiteen yhteydessä, kuvataiteessa riittää aiheet tai motiivit (aihelmat)

**Comment by YSO-kokous** [comment]
Suositellaan teemat-käsitteelle käytettävää termiä _teemat (kerronta)_. YSO-kokous näki tämän olevan paras sulkutarkenne. Pyydetään Kauno-ryhmän vielä kommenttia tähän.

Lisäksi otetaan sanastoon _teemat (musiikki)_, mutta lisätään se sanastoon vasta kun toisen käsitteen sulkutarkenne on selvinnyt.

**Comment by YSO-kokous** [comment]
hyvåksytty

**Comment by mariaforsen** [comment]
Sv. 
-teman (musik)
-teman (berättande)
