### ISSUE TITLE
pastissioopperat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5833]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pastissioopperat 

#### Ehdotettu termi englanniksi   

pasticcio operas 

#### Ehdotettu termi ruotsiksi   

pastischoperor 

#### Vaihtoehtoiset termit ja ilmaisut   

oopperapastissit 
pastissit (oopperat) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oopperat (teokset)](http://www.yso.fi/onto/yso/p6421) 

#### Tarkoitusta täsmentävä selite   

Määritelmä: Ooppera, jonka musiikki on koottu usean säveltäjän tuotannosta. (Grove Music Onlinen mukaan pastissi(ooppera) on "[a]n opera made up of various pieces from different composers or sources and adapted to a new or existing libretto".) 

#### Perustelut ehdotukselle   

Termi tarvitaan sekä YSA (ja YSOon) että Suomalaiseen lajityyppi- ja muotosanastoon! 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [pastissioopperat](http://finto.fi/yse/fi/page/Y505833)

**Comment by ksornova** [comment]
Muusa-ryhmä (13.3.2018): kannatetaan

**Comment by mariaforsen** [comment]
Sv. pastischoperor ET operapastischer
