### ISSUE TITLE
dynamiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5834]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dynamiikka](http://www.yso.fi/onto/ysa/Y94938) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan asiasana kahtia: (1) "dynamiikka (fysiikka)" tai "dynamiikka (mekaniikka)", joka vastaisi YSAn nykyistä "dynamiikka"-asiasanaa, ja (2) "dynamiikka (musiikki)" tai "dynamiikka (musiikin tulkinta)", joka vastaisi MUSAn YSAan sulautettavaa asiasanaa. 

#### Perustelut ehdotukselle   

Nykyiset "dynamiikka"-asiasanat vaativat tarkenteen, koska ne viittaavat kahteen selvästi eri asiaan. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by asormune** [comment]
Kannattaisin "dynamiikka (musiikki)", koska säveltäjät ainakin tietyssä vaiheessa taidemusiikin kehitystä kirjoittivat (merkitsivät) dynaamisia ohjeita teokseensa. Esittäjä tuottaa sitten (oman) tulkintansa näistä esityksessään.

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: kannatetaan termin jakamista ehdotetulla tavalla.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. dynaamisuus.
2. fys. liikkeen ja sitä aiheuttavan voiman suhteita käsittelevä mekaniikan osa. _Kiinteiden kappaleiden dynamiikka. Sähködynamiikka._
3. äänen voiman vaihtelut, vaihteleva käyttö.

**Comment by mirmaid** [comment]
_Dynamiikka (mekaniikka)_ olisi mahdollinen, osattaisiinko sitä käyttää kun kyse on biomekaniikasta (_Suoritusanalyysi painonnostossa_)? Muutenkin mekaniikka-tarkennetta pitäisi rohjeta käyttää hyvin monenlaisissa yhteyksissä, jotka eivät aina välttämättä tunnu luontevilta (_Ab initio investigations of the dynamic and thermodynamic properties of atmospherically relevant strong acids_).

Osassa viitteitä mahdollinen olisi _ryhmädynamiikka_, mutta ei varmaan aina sovellu (esim. organisaatiodynamiikka)?

Mitä tehtäisiin niille kuvailuille, joissa termi esiintyy väljemmässä merkityksessä, esim. _Dynamics in quality assurance and evaluation in higher education_; _Mixed-species forests : ecology and management_; _Image analysis methods for the characterization of mitochondrial morphology and dynamics_?

Dynamiikka-termiä käytetty myös: _Move the way you feel : effects of musical features, perceived emotions, and personality on music-induced movement_ ja _The dynamics of music psychotherapy_, onhan tarkenne (musiikki) riittävän tarkka?

**Comment by YSA-kokous** [comment]
Sulkutarkenteita mietittävä vielä, palataan konversion jälkeen.

**Comment by mariaforsen** [comment]
Olisiko sitten mahdollista: 
dynamiikka (musiikki)
dynamiikka (fysiikka) -mekaniikkahan on fysiikan osa-alueita ja vastaavissa tapauksissa ollaan monesti tyydytty väljempään tarkenteeseen, tarpeeksi selkeähän se kuitenkin varmasti olisi
Ja kävisikö että abstraktimmassa merkityksessä käytetään sanastossa oleva "dynaamisuus"? Vrt. yllä mainittu Kielitoimiston sanakirjan määritelmä

**Comment by tpalonen** [comment]
Kannatan muotoa _dynamiikka (mekaniikka)_, koska _dynamiikka (fysiikka)_ -termin voi edelleen sekoittaa musiikkiin. Äänen voimakkuusvaihteluhan on fysikaalinen ilmiö.

**Comment by mirmaid** [comment]
LCSH:ssa muuten Dynamics (Music) ohjaa termiin _musiikin tulkinta_, http://id.loc.gov/authorities/subjects/sh85088799. Tarvitaanko musiikin dynamiikkaa meillä siis erikseen?

Ensimmäisten sadan viitteen joukosta löytyi yksi musiikkiaiheinen: https://melinda.kansalliskirjasto.fi/byid/013816383. Dynamiikkaa käytetty 1049 kertaa Melindassa. _Dynaamisuus_ ei näytä soveltuvan myöskään silloin, kun merkitys ei liity mekaniikkaan/fysikkaan.

**Comment by mirmaid** [comment]
LCSH Dynamics: http://id.loc.gov/authorities/subjects/sh85040316

**Comment by mariaforsen** [comment]
Dynamiikka-termin merkityskenttä on sama ruotsiksi kuin suomeksi (Kielitoimiston sk.) https://svenska.se/tre/?sok=dynamik&pz=1 Eli tuo fysiikka/mekaniikka-merkitys (ja mahdollisesti musiikki erikseen) riittää varmaan, kun dynaamisuuskin on erikseen.

**Comment by mirmaid** [comment]
Itse siis jättäisin tämän ihan nykyiselleen, myöskään LCSH:ssa ei ole tarkennetta, eikä ko. sanaston hierarkia ole estänyt ainakaan Melindassa käyttämästä myöskään sitä laajemminkin, esim. https://melinda.kansalliskirjasto.fi/byid/017413291. Mitään kielivirhettä ei myöskään seuraa, eikä musiikinkaan dynamiikka liene sen kauempana mekaniikasta kuin vaikka ekosysteemin dynamiikka. Jos ensimmäisten sadan joukossa on yksi musiikkiaineisto, sitä pitäisi kaiken kaikkiaan olla n. 10 viitettä.

Jos tarkenne laajasti tähän halutaan, niin ennemmin fysiikka, joka on vähän vähemmän outo kuin mekaniikka kaikissa niissä konteksteissa, joissa tätä ihan kaikkien mielestä varmasti saa käyttää.

**Comment by YSO-kokous** [comment]
#### Päätös
Ehdotetaan Muusalle että lisätään ohjaustermi dynamiikka (musiikki) KÄ musiikin tulkinta, TAI, jos tämä ei riitä, uusi käsite musiikin dynamiikka KT dynamiikka (musiikki). Ensimmäisten sadan viitteen joukossa Melindassa siis yksi musiikkiaiheinen, dynamiikka-käsitettä käytetty yhteensä n. 1000 kertaa.

**Comment by MUUSA-kokous** [comment]
Kannatetaan uutta käsitettä musiikin dynamiikka
KT dynamiikka (musiikki)
LT musiikin tulkinta
LCSH-vastine https://id.loc.gov/authorities/subjects/sh85088799.html

**Comment by YSO-kokous** [comment]
### Päätös
Uusi käsite:
**musiikin dynamiikka**
   KT dynamiikka (musiikki)
   LT musiikin tulkinta

**Comment by mariaforsen** [comment]
Sv. musikalisk dynamik HT musikdynamik, dynamik (musik)
