### ISSUE TITLE
suopunki / lasso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5835]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suopunki / lasso 

#### Ehdotettu termi ruotsiksi   

kasttöm / lasso 

#### Ehdotettu termi englanniksi   

lasso 

#### Ehdotettu yläkäsite YSOssa (LT)   

[köydet](http://www.yso.fi/onto/yso/p2905) 
[narut](http://www.yso.fi/onto/yso/p2904) 

#### Vastaava käsite muussa sanastossa   

lasso : <http://id.loc.gov/authorities/subjects/sh85074824> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Tarkoitusta täsmentävä selite   

Suopunki on porojen kiinniottoon käytettävä kysi, jossa on kiinnivedettävä silmukka. Lasso-termiä köytetään lähinnä pohjoisamerikalaisessa karjanhoidossa käytettävästä samankaltaisesta välineestä.. 

#### Perustelut ehdotukselle   

Aineisto käsittelee saamelaiskulttuurissa esintyvän välineen käyttöä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suopunkikoulu - saamenkielinen lasten tv-ohjelmasarja 

**Ehdottajan nimi:** Johanna Edgren 
**Ehdottajan organisaatio:** KAVI 
**Ehdottajan sähköpostiosoite:** johanna.edgren@kavi.fi **Termiehdotus Fintossa:** [suopunki / lasso](http://finto.fi/yse/fi/page/Y505835)

**Comment by mariaforsen** [comment]
Riittäisikö laajempi "lasso"? Ruotsiksi lasso/kasttöm käytetään muussakin kuin poronhoidossa. Vanhanaikainen "svopp" korvattuna terminä?

**Comment by YSA-kokous** [comment]
Ongelma ruotsiksi, seuraava kokous.

**Comment by satuniininen** [comment]
Voidaanko linjauksia joustaa siten, ettei molemmille tarvita sulkutarkennetta silloin kun ovat suorassa yläkäsite-alakäsite-suhteessa toisiinsa? Eli esim. lasso AK lasso (reindeer management) ja sama ruotsiksi.

**Comment by EsaMPKK** [comment]
Related Terms -osastoa:
https://fi.wikipedia.org/wiki/Bola

**Comment by mariaforsen** [comment]
Niin ratkaiseva muutos linjauksiin vaatisi varmaan ontologia-pienryhmän käsittelyä? Ja siinä on kyllä pidetty tärkeänä että jokainen termi on yksilöivä. Englanniksi ehkä ok, mutta ruotsiksi pitäisi varmaan keksiä joku muu ratkaisu, lasso för renar/renskötsel tms.

**Comment by mirmaid** [comment]
Ehkä sitten _lassot ja suopungit_?
