### ISSUE TITLE
postimiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5836]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[postimiehet](http://www.yso.fi/onto/ysa/Y109974) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jos ei tämä tarkoita Postimies Patea ja sitä joka soittaa aina kahdesti, olisi ehkä paikallaan ottaa joku modernimpi termi. 

#### Perustelut ehdotukselle   

- 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa on _postityöntekijät, postivirkamiehet_ ja _postiautonkuljettajat_. Voidaan varmaankin muuttaa _postimiehet > postinjakajat_? http://www.ammattinetti.fi/ammatit/detail/453_ammatti

**Comment by YSA-kokous** [comment]
postimiehet KÄ postinjakajat, postityöntekijät
