### ISSUE TITLE
heetin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5838]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heetin kieli 

#### Ehdotettu termi ruotsiksi   

hettitiska 

#### Ehdotettu termi englanniksi   

Hittite language 

#### Ehdotettu yläkäsite YSOssa (LT)   

[indoeurooppalaiset kielet](http://www.yso.fi/onto/yso/p3045) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85061276> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Heetin_kieli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.201160 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [heetin kieli](http://finto.fi/yse/fi/page/Y505838)

**Comment by mariaforsen** [comment]
Sv. hettitiska
