### ISSUE TITLE
kirjallisuuskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#584]
#### Ehdotettu termi suomeksi

kirjallisuuskasvatus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/ysa/ryhma_57)
[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 12.10.2000

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 114797

**Termiehdotus Fintossa:** [kirjallisuuskasvatus](http://finto.fi/yse/fi/page/Y314797)

**Comment by mariaforsen** [comment]
Sv. mahdollisesti litterär fostran/litteraturfostran
