### ISSUE TITLE
Kielletty kaupunki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5840]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kielletty kaupunki 

#### Ehdotettu termi englanniksi   

Forbidden City 

#### Ehdotettu termi ruotsiksi   

Förbjudna staden 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Kielletty_kaupunki 

#### Perustelut ehdotukselle   

Suosittu matkakohde, paikan arkkitehtuurista ja taiteesta julkaistu kirjallisuutta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The Palace Museum, Peking : treasures of the Forbidden City 0-8109-1477-8 

**Ehdottajan nimi:** Saijamari Pakkala 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** saijamari.pakkala@tampere.fi **Termiehdotus Fintossa:** [Kielletty kaupunki](http://finto.fi/yse/fi/page/Y505840)

**Comment by jtuohini** [comment]
LCSH-vastine [**Forbidden City (Beijing, China)**](http://id.loc.gov/authorities/subjects/sh85050448).

**Comment by mirmaid** [comment]
LCSH:ssa tämä on yhteisö.

**Comment by mariaforsen** [comment]
Sv. Förbjudna staden
