### ISSUE TITLE
maankaltaistaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5841]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maankaltaistaminen 

#### Perustelut ehdotukselle   

tieteiskirjallisuudessa yleinen termi, sekä esim Mars-tutkimuksessa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim lautapelit Gaia project sekä Terraforming Mars 

**Ehdottajan nimi:** Renni Honkanen 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** renni.honkanen@hel.fi **Termiehdotus Fintossa:** [maankaltaistaminen](http://finto.fi/yse/fi/page/Y505841)

**Comment by satuniininen** [comment]
LCSH:ssa [Planets--Environmental engineering](http://id.loc.gov/authorities/subjects/sh85102657.html), korvattuna terminä _terraforming._

**Comment by mariaforsen** [comment]
Sv. terraformning ET terraformering
