### ISSUE TITLE
kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5842]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kieli](http://www.yso.fi/onto/ysa/Y106930) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään kieli ja kielet. 

#### Perustelut ehdotukselle   

Käsitteiden eroa ei sanastossa ole selvennetty: näillä ei ole täsmentävää määritelmää YSAssa tai YSOssa. Toisaalta YSOssa niillä on myös sama yläkäsite (kulttuuriset järjestelmät), mikä ei sekään selkeytä eroa. 	Kielitoimiston sanakirja ei tee tällaista merkityseroa, vaan niputtaa YSA/YSOn merkitykset yhteen. LCSH:ssa YSAn/YSOn merkityksiä vastaa yksi käsite: ”Language and Languages”.

Merkitysero on toki mahdollista hahmottaa. Monikkomuotoinen kielet on eräänlainen hierarkkinen yläluokka yksittäisille kielen instansseille (esim. suomen kieli) tai kieliryhmille (indoeurooppalaiset kielet). Yksikkömuotoinen kieli taas tuntuu viittaavan kieleen "sinänsä", kielenkäyttöön, puhumiseen, diskurssiin jne. Kuvailukäyttö heijastelee tätä eroa siten, että yksikkömuodossa kuvaillaan aineistoa, jossa käsitellään kielenkäyttöä ("Teen talk : the language of adolescents"); monikkomuodossa, kun puhutaan yhdestä tai useammasta kielestä, monikielisyydestä jne ("The Cambridge handbook of linguistic multi-competence"). Toisaalta monikkomuotoa käytetään tyypillisesti myös kielen oppimisen yhteydessä ("Teaching English through Arts in upper secondary school").

Käsitteitä on joka tapauksessa käytetty kuvailussa paljon ristiin ja moniin tapauksiin sopisi aivan yhtä hyvin jompi kumpi tai molemmat (esim. kielen oppimisen tai yksittäistä kieltä koskevan aineiston yhteyteen sopisi mielestäni "kieli" yhtä hyvin ellei jopa paremmin kuin "kielet").

Vaikka merkitysero onkin hahmotettavissa, pidän siitä huolimatta yhdistämistä käyttäjäystävällisempänä ja tilannetta selkeyttävänä vaihtoehtona. Säilyttäisin "kieli" pääterminä ja lisäisin "kielet" ohjaustermiksi. Hierarkkisesti ajateltuna "kielet" tuntuisi ehkä paremmalta (käsitteellä on paljon alakäsitteitä), mutta kuvailu- ja tiedonhakunäkökulmasta "kieli" on mielestäni intuitiivisempi ja käyttöalaltaan kattavampi (esim. "Teen talk : the language of adolescents" yhteydessä "kielet" tuntuu oudolta). 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mariaforsen** [comment]
Myös SAOssa vain yksi "språk" (LCSH-linkitys Language and languages). Kannatan yksikkömuotoa (muissa tapauksissa olisi hyvä käyttää tarkempia termejä, kuten kieliryhmiä tai yksittäisiä kieliä, eikä pelkkä "kielet").

**Comment by satuniininen** [comment]
Kannatan yhdistämistä ja olen samaa mieltä siitä, että yksikkö on monikkoa monikäyttöisempi pääterminä. Melindan tietueisiin yksikkö näyttäisi istuvan pääsääntöisesti oikein hyvin, mutta selvästi huonoiten silloin kun kontekstina on kielen opetus tai oppiminen. 

Yksi vaihtoehto olisi tietysti noudattaa LCSH:n ratkaisua ja valita käytettäväksi termiksi **kieli ja kielet.**

**Comment by mirmaid** [comment]
Varovainen kannatus vaihtoehdolle _kieli ja kielet_.

**Comment by YSA-kokous** [comment]
Listataan esimerkkejä, joissa yksikkö on ongelmallinen.

**Comment by mirmaid** [comment]
kieli (järjestelmät) TAI kieli ja kielet

**Comment by satuniininen** [comment]
_Kieli ja kielet_ kuulostaa omaan korvaan vähemmän vieraannuttavalta kuin sulkutarkenne _(järjestelmät)_.

**Comment by YSA-kokous** [comment]
kieli ja kielet
