### ISSUE TITLE
huoneenvuokra

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5843]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huoneenvuokra](http://www.yso.fi/onto/ysa/Y101700) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi ohjaustermi: asunnonvuokra 

#### Perustelut ehdotukselle   

Sosiaalialan tiedonhallinnan sanasto, versio 3.0 (THL, 2017): asunnonvuokra. Termin huoneenvuokra merkitys onkin laaja (esim. Kielitoimiston sanakirja: huoneenvuokra=sopimussuhde joka syntyy, kun rakennus t. sen osa luovutetaan korvauksesta toisen käyttöön), joten ei varmaan olisi ainakaan haittaa tästä ohjaustermistä. Ruotsiksi vastine on nyt bostadshyra (mikä lienee ok kun huoneenvuokra viittaakin laajemmin kuin pelkästään huoneen vuokraan). 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
EKS: KT asuinhuoneiston vuokra, edelleenvuokraus, liikehuoneiston vuokra

**Comment by YSA-kokous** [comment]
KT asunnonvuokra, asuinhuoneiston vuokra, liikehuoneiston vuokra
