### ISSUE TITLE
Paljakan luonnonpuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5845]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Paljakan luonnonpuisto 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luonnonpuistot](http://www.yso.fi/onto/yso/p9492) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 

#### Perustelut ehdotukselle   

Muiden luonnonpuistojen joukkoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-446-733-9 Paljakan luonnonpuiston, Latvavaaran ja Pirunkirkon hoito- ja käyttösuunnitelma 

#### Tarkoitusta täsmentävä selite   

http://www.luontoon.fi/paljakka 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi **Termiehdotus Fintossa:** [Paljakan luonnonpuisto](http://finto.fi/yse/fi/page/Y505845)

**Comment by mariaforsen** [comment]
Sv. Paljakka naturpark
