### ISSUE TITLE
ruokajärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5846]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruokajärjestelmät 

#### Ehdotettu termi ruotsiksi   

livsmedelssystem 

#### Ehdotettu termi englanniksi   

food systems 

#### Assosiatiiviset (RT)   

[elintarvikeketjut](http://www.yso.fi/onto/yso/p25344) 
[elintarviketuotanto](http://www.yso.fi/onto/yso/p15341) 

#### Tarkoitusta täsmentävä selite   

määritelmä: http://luomu.fi/tietopankki/mita-tarkoittaa-ruokajarjestelma/ 

#### Perustelut ehdotukselle   

Googlessa > 12 000 osumaa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-951-51-0415-1 Tiedosta hyvää: Helsingin yliopisto kestävien ja tehokkaiden ruokajärjestelmien edistäjänä 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi **Termiehdotus Fintossa:** [ruokajärjestelmät](http://finto.fi/yse/fi/page/Y505846)

**Comment by mariaforsen** [comment]
Sv. livsmedelssystem ET matsystem

**Comment by vthuhtala** [comment]
Luin linkin takaa selityksen enkä siltikään ymmärtänyt mistä on kyse.

Käytetty Helkassa agifors-sanana 3 kertaa

**Comment by jarmosaarikko** [comment]
http://jukuri.luke.fi/bitstream/handle/10024/442005/mtts135.pdf?sequence=1&isAllowed=y
MÄÄRITELMIÄ
"Koska **ruokajärjestelmä käsittää sekä toimijat, että toiminnan ja toiminnan fyysisen ympäristön**, on se tutkimuskohteena hyvin monitahoinen ja vaatii eri alojen tutkimusmenetelmien yhteensovittamista."
"Tutkimuksessa paikallinen **ruokajärjestelmä** tulisikin rajata siten, että siihen **sisältyvät sekä ruoantuotantoalueet sekä ruoankulutusalueet** kaupunkikeskuksissa."

**Comment by jarmosaarikko** [comment]
Ei tässä Sitran sivussakaan ole selvää määritelmää: https://www.sitra.fi/hankkeet/alueellinen-kestava-ruokajarjestelma/#mista-on-kyse

**Comment by jarmosaarikko** [comment]
https://www.juvanlehti.fi/2017/12/15/jsp-lahtee-kehittamaan-kestavaa-ruokajarjestelmaa-kilpailulla-haetaan-uusia-kokeiluja-ja-niille-myonnetaan-rahaa/
MÄÄRITELMÄ
Järvisaimaalainen **ruokajärjestelmä** koostuu kuudesta osa-alueesta, jotka ovat kiertotaloutta ja luomutuotantoa tukevat Innovatiiviset hankinnat, ruokatuotannon sivuvirtojen hyödyntäminen, hiilijalanjälkeä pienentävät älykkäät logistiset ratkaisut, ravinteiden kierrätys, villin ruuan ja metsien sekä vesien arvostus ja tuotantojärjestelmien käyttöasteen nosto ja uusiokäyttö.

**Comment by jarmosaarikko** [comment]
http://mmm.fi/artikkeli/-/asset_publisher/kestavan-ruokajarjestelman-pilottimallin-kehittaja-on-valittu
"Pilotoitavassa **ruokajärjestelmän** mallissa ravinteet kierrätetään takaisin peltoon kasvien tarpeisiin ja erilaiset energiantuotantomahdollisuudet käytetään hyväksi. Alueellinen kestävä **ruokajärjestelmä** perustuu paikallisen ruuan kulutukseen ja arvostukseen sekä paikallisen ruokakulttuurin kehittämiseen."

**Comment by jarmosaarikko** [comment]
tämä **elintarvikejärjestelmän** kuvaus kyllä tuntuu menevän päällekkäin edellisten kanssa:
https://www.eesc.europa.eu/fi/sections-other-bodies/other/permanent-study-group-sustainable-food-systems  "Pysyvä valmisteluryhmä ”kestävämmät elintarvikejärjestelmät”" --> ryhmä liittyy ruokaturvaan.
Englanninkielisessä esitteessä tämä on käännetty "**food system**" eli sama termi kuin ruokajärjestelmässäkin.  Ovatko siis synonyymejä?

 _“To build sustainable, resilient, climate-friendly, healthy and fair **food
systems**, we have to re-think the entire supply chain and design a comprehensive food
policy - one that enhances inter-sectoral cooperation, allows operators across the food
chain (including farmers, workers and SMEs) to lead a decent life and ensures better integration
of food-related objectives and instruments”._

**Comment by mariaforsen** [comment]
Laitetaanko suomeksi KT elintarvikejärjestelmät?

#1752

**Comment by mirmaid** [comment]
^ lisätty KT
