### ISSUE TITLE
Nyírbátor

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5848]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Nyírbátor 

#### Ehdotettu termi ruotsiksi   

Nyírbátor 

#### Ehdotettu termi englanniksi   

Nyírbátor 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n82273916> 
Wikidata : https://www.wikidata.org/wiki/Q755686 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.66830 

#### Perustelut ehdotukselle   

Kyseiselle paikkakunnalle ei ole vielä käsitettä YSAssa tai YSOssa, vaikka sitä käsittelevää kirjallisuutta on julkaistu useampikin nimeke. 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Nyírbátor](http://finto.fi/yse/fi/page/Y505848)

**Comment by mirmaid** [comment]
Pieni kaupunki Unkarissa
