### ISSUE TITLE
Monimenetelmäisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5850]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Monimenetelmäisyys 

#### Vaihtoehtoiset termit ja ilmaisut   

Triangulaatio 

#### Perustelut ehdotukselle   

https://koppa.jyu.fi/avoimet/hum/menetelmapolkuja/menetelmapolku/tutkimusstrategiat/monimenetelmaisyys 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirjat ym. julkaisut 

**Ehdottajan nimi:** Marja Kokko 
**Ehdottajan organisaatio:** Jyväskylän yliopisto 
**Ehdottajan sähköpostiosoite:** marja.kokko@jyu.fi **Termiehdotus Fintossa:** [Monimenetelmäisyys](http://finto.fi/yse/fi/page/Y505850)

**Comment by jtuohini** [comment]
Miten tämä ehdotettu suhtautuu sanastossa jo olevaan [**monitieteisyys**](http://www.yso.fi/onto/ysa/Y130177)-asiasanaan, jonka KT-muotoina ovat _monitieteellinen tutkimus_ ja _monitieteellisyys_?

**Comment by satuniininen** [comment]
Sanastossa on jo [triangulaatio](https://finto.fi/ysa/en/page/Y152705?clang=fi). Lisätään monimenetelmäisyys ainakin korvatuksi termiksi?

**Comment by mariaforsen** [comment]
Vähän googlessa, ei sanastoissa. Ruotsiksi mahdollisesti ratkaistavissa "med flera/många metoder", "multimetodologi", metodologisk triangulering? Riittäisikö tosiaan lisäys korvattuna?

**Comment by AuHo22** [comment]
Esim: http://www.fsd.uta.fi/menetelmaopetus/kvali/L2_3_2_4.html  (Ja aiemmin mainitun monitieteisyyden lisäksi on vielä sanastossa poikkitieteisyys ja tieteidenvälisyys omine määritelmineen. Mutta täytyykö nämä nähdä laajempina ilmiöinä?)

Yleisesti triangulaatiossa erotetaan neljä päätyyppiä (Denzin 1978, Tuomen ja Sarajärven 2002, 141 mukaan): 
Aineistotriangulaatio – yhdessä tutkimuksessa käytetään useita eri aineistoja (haastattelut, tilastot, uudet tai arkistoaineistot jne.) tai eri tiedon kohteita (lääkärit, potilaat, omaiset jne.)

Tutkijatriangulaatio – useampi tutkija tutkii samaa ilmiötä ja on mukana joko osassa tutkimusta (esimerkiksi aineiston hankinta tai analyysi) tai koko tutkimusprosessissa.

Teoriatriangulaatio – tutkimusaineiston tulkinnassa hyödynnetään useita teoreettisia näkökulmia.

Menetelmätriangulaatio – tutkimusaineiston hankinnassa käytetään useita tiedonhankintamenetelmiä (esimerkiksi kysely ja haastattelu). (Eskola & Suoranta 1998, 69-70.)

Monimenetelmäisyys ehdottajan tarkoittamassa mielessä sopisi kaikkiin muttei ehkä niin tutkijatriangulaatioon?

**Comment by YSA-kokous** [comment]
KÄ triangulaatio
