### ISSUE TITLE
maatutkaluotaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5852]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maatutkaluotaus 

#### Ehdotettu termi englanniksi   

ground penetrating radar 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://hakku.gtk.fi/fi/reports/search?publication_id=20420 

#### Perustelut ehdotukselle   

http://www.geo-work.com/maatutkaluotaus-ja-mittaukset/ 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [maatutkaluotaus](http://finto.fi/yse/fi/page/Y505852)

**Comment by mariaforsen** [comment]
Sv. georadarundersökning ET markradarundersökning
