### ISSUE TITLE
ateriapalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5854]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ateriapalvelut](http://www.yso.fi/onto/ysa/Y100904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

vaihdetaan  yläkäsite "kotipalvelut"  yläkäsitteeseen "valmisruokateollisuus" 

#### Perustelut ehdotukselle   

ateriapalveluja (catering)  järjestetään myös lentokoneisiin ja juniin ja kokouksiin  yms., jotka eivät ole kotipalveluja 

#### Ehdottaja   

Jarmo Saarikko 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

jarmo.saarikko@helsinki.fi

**Comment by mirmaid** [comment]
YSAssa LT kotipalvelut ja _palvelut_. Oliko ruots. måltidsservice rajatumpi? YSOssa on huomautus Sosiaaliturvan sanastosta, mutta varmaan tässä on ongelma...muistelen että joskus on käsiteltykin asiaa.

**Comment by ilona-x** [comment]
Törmäsin tähän ruokapalvelut/ateriapalvelut -ongelmaan teoksen "Opas kestäviin ruokapalveluihin yleisötapahtumissa" kohdalla. Eli huomautuksen perusteella tämä on rajattu vain sosiaalipalveluihin, vaikka ohjaustermit antaisivat ymmärtää laajemmasta merkityksestä (catering, ruokapalvelut). Melindassa näyttää käytetyn muutenkin kuin sosiaalipalveluista: esim.:

- Suviseurojen ruokahuolto on hyvin suunniteltuihin prosesseihin ja satoihin vapaaehtoisiin nojautuva taidonnäyte
- Laivapöydässä syö koko Suomi
- VR osti Avecran ohjat
- Lentoyhtiöt kilpailevat herkkusuista - kumpupilvien keittiöt

**Comment by mariaforsen** [comment]
Tämä rajattiin aikaisemmin sosiaalipalveluksi ja ruotsinnos sen mukaan. Sanastossa myös pitopalvelut=catering
https://termipankki.fi/tepa/fi/haku/ateriapalvelu

**Comment by tpalonen** [comment]
Vahvistan Marian viestin eli tosiaan käsite on aiemmin ollut kahtiajaettu. Jako on päätetty aikoinaan  poistaa ja rajata käsite sosiaalipalveluksi.

YSO-kokous 14.2.2014:
Ateriapalvelut on jaettu kahtia. Toinen on suoraan palveluiden alla ja toinen sosiaalisten palveluiden alla. Onko jako tarpeellinen?

poistetaan käsite "ateriapalvelut (palvelut)", koska vastaava sisällöllisesti "pitopalvelut"
poistetaan sulkutarkenne käsitteeltä "ateriapalvelut (sosiaalipalvelut)"
(https://code.google.com/archive/p/onki-data/issues/16)

**Comment by ilona-x** [comment]
Eli jos tämä rajattu vain sosiaalipalveluihin, niin voisiko pääterminä silloin olla nykyinen KT-muoto **ateriapalvelut (sosiaalipalvelut)** ja pitäisikö KT catering poistaa ja KT ruokapalvelut lisätä tarkenne (sosiaalipalvelut)?

Noihin lentokoneen tai junan ruokapalveluihin ei taida oikein olla mitään sopivaa termiä, kun ei niitä oikein pitopalveluksikaan voi nimittää. 😃  Samoin erilaisten tapahtumien ruokapalveuita käsitteleviin aineistoihin ei myöskään taida olla sopivaa termiä vai olisiko ruokahuolto mahdollinen? https://termipankki.fi/tepa/fi/haku/ruokahuolto

**Comment by mirmaid** [comment]
Eli olisiko tässäkin toimenpiteenä edellä ehdotettu rajaus, viitteiden siivous ja jäljellejäävien tutkailu?

**Comment by mariaforsen** [comment]
Sv. matförsörjning=ruokahuolto ei kyllä käytetä tapahtumien, lentokoneiden yms. ruokapalveluista.

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi ateriapalvelut (sosiaalipalvelut) ja catering pois ohjaustermeistä. Muutetaan ohjaustermi ruokapalvelut muotoon ruokapalvelut (sosiaalipalvelut). Tutkitaan nykyinen kuvailu ja korjataan tarvittaessa päätöksen mukaisesti.

**Comment by mirmaid** [comment]
Varsin pikainen tutkailu osoittaa, että käsitettä on käytetty ainakin uudemmassa aineistossa niin paljon kaikenlaisista muista ruokapalveluista (yleisötapahtumat, koulu- ja päiväkotiruokailu ja muut vastaavat ruokalat), että yllä sovitulla korjauksella saadaan käsiteltyä vain pieni osa viitteistä. Useinhan samat suurkeittiöt tuottavat sekä vanhuspalvelun että koulujen ja päiväkotien ruuan, joten onkohan rajan vetäminen juuri tähän kohtaan edes kaikkein järkevintä?

_Pitopalvelut_ ei sovellu kuvaamaan näitä muita ruokapalveluita, sen merkitys on suomeksi hyvin rajattu nimenomaan pienehkön joukon juhlatilaisuuksiin. Varmaan sama yrittäjä voi toimia myös yleisötilaisuuksissa tms. mutta sitä ei nimitettäisi kuitenkaan pitopalveluksi. Catering on kyllä vähän laajempi, ei välttämättä juhliin liittyvä, mutta ei sekään oikein sovi esim. kouluruokailusta tms. ruokala- tai suurkeittiötoiminnasta tai Suviseurojen ruokapalveluista.

**Comment by mariaforsen** [comment]
Onko mahdollista rajata julkiseen toimintaan, eli että käy yhtä hyvin päiväkoti-, koulu-, vanhus- yms. ateriapalveluissa?

**Comment by FinMeSHienPaimentaja** [comment]
Esimerkiksi vanhusten ateriapalvelut voi olla ulkoistettuja, yksityisen puolen palveluita, joita palveluita kunnat ostavat -> yksityisten ja julkisten toimintojen rajanveto menisi hankalaksi.

**Comment by FinMeSHienPaimentaja** [comment]
Minusta ruokapalvelut kuulostaisi yleiskäsitteenä ok:lta, tosin tarkemmin puhutaan esim. vanhusten ateriapalveluista, kouluruokapalveluista, sairaalaruokapalveluista. (ym. laitosten ruokapalveluista).

Catering lienee yleisesti käytetty, mutta kun se ei ole suomea.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta _ateriapalvelut (sosiaalipalvelut)_ ja otetaan sanastoon sen sijaan _ruokapalvelut_. YSO-ylläpito pohtii poistetaanko vanha käsite käytöstä vai tehdäänkö vain käsitteen käytettävä termi.
