### ISSUE TITLE
elokuvasosiologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5855]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

elokuvasosiologia 

#### Ehdotettu termi ruotsiksi   

filmsociologi 

#### Ehdotettu termi englanniksi   

sociology of film, sociology of cinema 

#### Vaihtoehtoiset termit ja ilmaisut   

elokuvan sosiologia 
elokuvansosiologia 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85088108> 
Wikidata : https://www.wikidata.org/wiki/Q7552849 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 
[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Perustelut ehdotukselle   

Vastaavat taiteenlajikohtaiset löytyvät jo musiikille, tanssille ja teatterille. Elokuva yhtä lailla keskeinen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.957298 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [elokuvasosiologia](http://finto.fi/yse/fi/page/Y505855)

**Comment by satuniininen** [comment]
Kannatan käsitettä, mutta siltaus on ongelmallinen. Käsitteellä _Motion pictures--Social aspects_ on myös merkityksiä, joilla ei ole juurikaan tekemistä sosiologian kanssa. 

Muista vastaavista taiteenlajikohtaisista käsitteistä on sillattu vain _tanssisosiologia --> Dance--Sociological aspects_ ja yläkäsite _taidesosiologia --> Arts and society_

**Comment by mariaforsen** [comment]
Sv. filmsociologi
