### ISSUE TITLE
gandan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5856]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gandan kieli 

#### Perustelut ehdotukselle   

Aineistoa on. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Omuzimu gwa Kasooba / Edward K. N. Kawere 

**Ehdottajan nimi:** Marjut Puominen 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** marjut.puominen@hel.fi **Termiehdotus Fintossa:** [gandan kieli](http://finto.fi/yse/fi/page/Y505856)

**Comment by mariaforsen** [comment]
Sv. luganda (språk) ET ganda (språk)
