### ISSUE TITLE
gandankielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5857]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gandankielinen kirjallisuus 

#### Perustelut ehdotukselle   

Aineistoa on. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Omuzimu gwa Kasooba / Edward K. N. Kawere 

**Ehdottajan nimi:** Marjut Puominen 
**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** marjut.puominen@hel.fi **Termiehdotus Fintossa:** [gandankielinen kirjallisuus](http://finto.fi/yse/fi/page/Y505857)

**Comment by mariaforsen** [comment]
Sv. litteratur på luganda
