### ISSUE TITLE
kivi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5858]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kivi](http://www.yso.fi/onto/ysa/Y102570) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite ja siirretään ohjaustermiksi kiviaines-käsitteelle. 

#### Perustelut ehdotukselle   

Kivi-johdannaisia käsitteitä on sanastossa tarpeettoman monta. Kivi-käsitteen lisäksi kivet, kiviaines, luonnonkivi, kivilajit. Kaikkia näitä käytetään samankaltaisissa yhteyksissä kuin kivi-käsitettä kanssa ja niitä esiintyy myös samoissa tietueissa. Yhden käsitteen poistaminen selkeyttäisi tilannetta ja käsitteiden välistä merkityseroa.

Kivi ja kiviaines ovat edellä mainituista käsitteistä selkeimmin keskenään päällekkäiset. Kielitoimiston sanakirjan mukaan kiviaines on yksi kiven merkityksistä ja esim. YSOn hierarkian mukaan kivi-käsite viittaa nimenomaan kiveen materiaalina (vrt. kivet, joka viittaa yksittäisiin kiviobjekteihin). Allärsissa kivi on  ”sten (material)” ja kiviaines ”stenmaterial”.

Kuvailussa edellä listatuille käsitteille voi hahmottaa omat käyttöalansa, mutta niitä käytetään joka tapauksessa paljon ristiin. Erityisesti kivi esiintyy usein jonkin muun em. käsitteen kanssa samassa tietueessa ja kivi- ja kivet-käsitteitä on käytetty paljon keskenään ristiin samankaltaisissa konteksteissa (esim. puutarhanhoito, kiviterapia). Kiviaines-käsite kuitenkin harvemmin esiintyy päällekkäin muiden kanssa ja sen käyttö painottuu kivi- ja kivet-käsitteitä selvemmin geologiseen aineistoon. Tämän pohjalta ehdotan, että "kivi" poistetaan ja lisätään ohjaustermiksi "kiviaines"-käsitteelle. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by vthuhtala** [comment]
Jos muutos tehdään, niin sanastoon pitäisi lisätä 'kiviesineet' (masa) 
(tietokantakorjauksia 'kivi' + 'esineeet' / 'muinaisesineet' / tms.)

**Comment by YSA-kokous** [comment]
kiviesineet, kiviaines - tutkitaan (seuraava kokous)
(on myös kivitavara, kivituotteet)

**Comment by YSA-kokous** [comment]
Otetaan kiviesineet
kivi (materiaalit) vs. kiviaines (Päivi tutkii)

**Comment by ilona-x** [comment]
Kiviaines- ja luonnonkiviteollisuuden kehitysnäkymät http://urn.fi/URN:ISBN:978-952-327-048-0
määritelmä kiviainekselle s. 70

**Comment by mirmaid** [comment]
Käyttö hajoaa sen verran, että pitäisi korjata tapauskohtaisesti yhdellä tai useammalla termeistä _kivet, kiviaines, kivilajit, kiviesineet_.

**Comment by jarmosaarikko** [comment]
Geologian sanakirja:ssa ei ole "kivi" yksinään:
http://kielo.luomus.fi/uusigeo/index.php/glossary/page/5/?az=K

**Kivet**
Lajittunut kivennäismaalaji, jonka d50-menetelmällä määritetty päälajite on kivet (raekoko 60- 1000 mm), lyhenne Ki.

**Kivilaji**
Kivilaji koostuu yhtä tai useampaa mineraalilajia olevista rakeista, jotka ovat liittyneet lujasti toisiinsa; kivilajit muodostavat kallioperässä laajoja, verraten tasalaatuisia massoja.
