### ISSUE TITLE
Jász-Nagykun-Szolnok

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5859]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Jász-Nagykun-Szolnok 

#### Ehdotettu termi ruotsiksi   

Jász-Nagykun-Szolnok 

#### Ehdotettu termi englanniksi   

Jász-Nagykun-Szolnok 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n94087699> 
Wikidata : https://www.wikidata.org/wiki/Q189655 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.66833 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Jász-Nagykun-Szolnok](http://finto.fi/yse/fi/page/Y505859)

**Comment by mirmaid** [comment]
Unkarin lääni
