### ISSUE TITLE
Szabolcs-Szatmár-Bereg

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5860]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Szabolcs-Szatmár-Bereg 

#### Ehdotettu termi ruotsiksi   

Szabolcs-Szatmár-Bereg 

#### Ehdotettu termi englanniksi   

Szabolcs-Szatmár-Bereg 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n92078562> 
Wikidata : https://www.wikidata.org/wiki/Q190518 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.388412 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Szabolcs-Szatmár-Bereg](http://finto.fi/yse/fi/page/Y505860)

**Comment by mirmaid** [comment]
Unkarin lääni
