### ISSUE TITLE
Versaillesin linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5862]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Versaillesin linna](http://www.yso.fi/onto/ysa/Y159888) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde "linnat" --> "palatsit" 

#### Perustelut ehdotukselle   

Versailles'n linna on suomenkielisestä nimestään huolimatta palatsi toisin kuin esimerkiksi Hämeen linna, Olavinlinna jne. Ks. esim. englanninkielinen Wikipedia: "The Palace of Versailles (French: Château de Versailles), or simply Versailles [- -], is a royal château in Versailles in the Île-de-France region of France" [https://en.wikipedia.org/wiki/Palace_of_Versailles] ja toisaalla "The word "chateau" is a French word that has entered the English language, where its meaning is more specific than it is in French. The French word "chateau" denotes buildings as diverse as a medieval fortress, a Renaissance palace and a 19th-century country house. Care should therefore be taken when translating the French word château into English, noting the nature of the building in question. Most French châteaux are "palaces" or "country houses" and not "castles", and for these the English word "chateau" is appropriate. Sometimes the word "palace" is more appropriate. To give an outstanding example, the Château de Versailles is so called because it was located in the countryside when it was built, but it does not bear any resemblance to a castle, so it is usually known in English as the Palace of Versailles. In French where clarification is needed, the term château fort is used to describe a castle, such as Château fort de Roquetaillade." [https://en.wikipedia.org/wiki/Château] 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Korjattu.
