### ISSUE TITLE
sulkatyöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5863]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sulkatyöt 

#### Ehdotettu termi englanniksi   

Featherwork 

#### Ehdotettu termi ruotsiksi   

Fjäderarbeten 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käsityöt (objektit)](http://www.yso.fi/onto/yso/p4923) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85047534.html> 
SAO : <http://www.kb.se/katalogisering/Svenska-amnesord/> 
Wikipedia : https://en.wikipedia.org/wiki/Featherwork 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3105119 

#### Perustelut ehdotukselle   

Käsitetta tarvitaan kirjastoaineiston kuvailussa. 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@nba.fi **Termiehdotus Fintossa:** [sulkatyöt](http://finto.fi/yse/fi/page/Y505863)

**Comment by mirmaid** [comment]
MAO-ontologiassa http://www.yso.fi/onto/mao/p4498

**Comment by mariaforsen** [comment]
Sv. fjäderarbeten
