### ISSUE TITLE
puolisotilaalliset joukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5865]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puolisotilaalliset joukot 

#### Ehdotettu termi englanniksi   

paramilitary forces 

#### Ehdotettu termi ruotsiksi   

paramilitära trupper 

#### Assosiatiiviset (RT)   

[armeijat](http://www.yso.fi/onto/yso/p3884) 

#### Vastaava käsite muussa sanastossa   

LCSH: paramilitary forces : <http://id.loc.gov/authorities/subjects/sh85097857.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Vaikea kuvailla muulla termillä. Käsittääkseni erona armeijaan on se, että puolisotilaalliset joukot koostuvat siviileistä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ISBN 978-952-93-8975-9 (PDF): Organisation Todt Rovaniemellä ja muualla Lapin alueella 1941 – 1944 

#### Tarkoitusta täsmentävä selite   

"Puolisotilaallinen joukko on siviileistä koostuva, sotilaallisesti järjestynyt ja koulutettu yksikkö." https://fi.wikipedia.org/wiki/Puolisotilaalliset_joukot 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi **Termiehdotus Fintossa:** [puolisotilaalliset joukot](http://finto.fi/yse/fi/page/Y505865)

**Comment by mariaforsen** [comment]
Sv. paramilitära styrkor ET halvmilitära styrkor, halvmilitära trupper, paramilitära trupper
