### ISSUE TITLE
muoto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5866]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muoto](http://www.yso.fi/onto/ysa/Y103589) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteet "muoto" ja "muodot". Päätermiksi "muoto", ohjaustermiksi "muodot". 

#### Perustelut ehdotukselle   

Sanasto ei tee selkeää eroa käsitteiden välille. Käsitteillä ei ole määritelmiä. Molemmat kuuluvat ryhmään 00 Yleistermit. Eroa ei tehdä myöskään laajennetun termin avulla. Yksikkö-monikko-termierosta sekä YSOn yläkäsitteiden avulla voidaan päätellä, että muodot viittaa objektien fyysiseen muotoon, kun taas yksikkömuoto viittaa abstraktimmin minkä tahansa olion rakenteeseen eli muotoon laajassa merkityksessä. YSOssa ”muodot (fyysiset ominaisuudet)”-käsitteen yläkäsite on fyysiset ominaisuudet, ”muoto (rakenteellinen)”-käsitteen yläkäsite on ominaisuudet. Toisaalta ainakin itse näen niin, että abstrakti "muoto" on laajempi käsite, jonka merkityksen piiriin fyysinen "muodot" voidaan periaatteessa sisällyttää.

Joka tapauksessa käsitteitä on käytetty Melinda-kuvailussa hyvin samankaltaisesti, ellei suorastaan identtisesti. Molempia käytetään viitatessa fyysisten objektien muotoon, tyypillisimmin teknisessä/taideteollisessa suunnittelussa ja arkkitehtuurissa: vrt. "Architecture : form, space, & order" [muoto] versus "Materials, form and architecture" [muodot]. Kumpaakin käsitettä käytetään myös viitatessa muotoon abstraktissa merkityksessä, esim. taiteiden tai kielen yhteydessä: vrt. "The basic forms of cinematography : form, rhythm, colour and relativity" [muoto] versus "Music in the words : musical form and counterpoint in the twentieth century novel" [muodot].

Kuvailukäyttö osoittaa, että käsitteet olisi parempi yhdistää kuin pitää erillään. Suositan yksikkömuotoa päätermiksi. Se tuntuu paremmin kattavan sekä abstraktin että fyysisen merkityksen. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by asormune** [comment]
Musiikissa on termi: muoto-oppi (musiikki). Voisiko musiikin kuvailussa käyttää myös termiä "muoto" ?

**Comment by tpalonen** [comment]
En uskalla sanoa äänitteiden kuvailusta enkä muutenkaan antaa ohjeistusta. Mutta ainakin tuota muoto-käsitettä on käytetty jokunen kerta Melindassa musiikkia käsittelevän kirjallisuuden yhteydessä. Esim. "Form, monothematicism, variation and symmetry in Béla Bartók̕s string quartets".

**Comment by asormune** [comment]
Joo, tarkoitin musiikkikirjallisuuden kuvailua.

**Comment by jtuohini** [comment]
Mielestäni ei, koska tuo **muoto-oppi (musiikki)** -asiasana on tarkoitettu musiikillista muotoa käsittelevän ja analysoivan aineiston kuvailuun. Jos haluttaisiin nimenomaan noihin muotoihin viitata, voisi tarpeen (?) tullen ottaa sanastoon uudeksi asiasanaksi _sävellysmuodot_ tms?

**Comment by asormune** [comment]
YSAssa on termeinä sekä rytmi että rytmioppi (= Musiikinteorian osa-alue, joka käsittelee rytmiä). Sitten on sointiväri (mutta ei "sointivärioppi"). Kannattaisin muoto-opin lisäksi Jaakon edellä esittämää termiä "sävellysmuodot"

**Comment by jtuohini** [comment]
Nykyisestä **rytmi**-asiasanasta on tulossa uusi YSE ihan lähipäivinä, kun se on nykyisellään niin ongelmallinen (termi arvattavasti jaettava)!

**Comment by mirmaid** [comment]
Kannatan yhdistämistä, mutta en ole varma onko yksikkö parempi. Se sopii usein, mutta vähän huonosti silloin kun aineisto käsittelee esim. sitä miten lapsi oppii muotoja ja värejä. 

LCSH: Shape USE Shapes

**Comment by mariaforsen** [comment]
Sv. form/former (egenskaper) Ruotsiksi yksikkömuoto luontevampi. 
(SAO: form (estetik), form (filosofi))

**Comment by ilona-x** [comment]
LCSH:
Forms (Shapes) USE Shapes
Form (Aesthetics) 
Form (Logic) 
Form (Philosophy)

**Comment by jtuohini** [comment]
Anun kaipaama musiikillisten muotojen kuvailuun sopiva asiasana olisi vasta ehdotuksen asteella oleva [_sävellysmuodot_](https://github.com/Finto-ehdotus/YSE/issues/6344).

**Comment by satuniininen** [comment]
Monikollista muotoa on käytetty paljon myös ketjumaisena lisämääreenä tarkoittamaan tapaa, tyyppiä, menetelmää tjsp. Esim yhdistelmissä viestintä + muodot, poikkeava käyttäytyminen + muodot, joustavuus + muodot (=finanssihallinnon joustavuuden muodoista). Näissä tapauksissa muodot voisi korvata jollain muulla tai poistaa kokonaan.

**Comment by ilona-x** [comment]
Melindan viitteiden perusteella yksikkömuoto tuntuisi paremmalta vaihtoehdolta. 

Joissain tapauksissa monikollisen "muodot" voisi ehkä korvata YSA-termeillä kuviot (tai geometriset kuviot).

Kaunokissa vain yksikkömuoto.

**Comment by YSA-kokous** [comment]
muoto KT muodot
