### ISSUE TITLE
tekstilajit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5868]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tekstilajit](http://www.yso.fi/onto/ysa/Y136195) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT tekstityypit vai tekstityypit erillisenä terminä? 

#### Perustelut ehdotukselle   

Myös tekstityypit käytetty Melindassa. Allärsissa nyt tekstilajit=texttyper, mutta harkittiin myös textgenrer... Ks. MOT, TEPA, Wikipedia jne. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
https://www.kirjastot.fi/kysy/mika-on-teksityypin-ja-tekstilajin

**Comment by AuHo22** [comment]
http://sykaikka.wixsite.com/sykaikka/tekstityypit

Myös tekstilajeista samalla sivustolla

**Comment by satuniininen** [comment]
Kielitieteen ontologiasta löytyy [tekstityyppi](http://finto.fi/kto/fi/page/p420) ja  [genre](http://finto.fi/kto/fi/page/p422) KT tekstilajit.

**Comment by krinay** [comment]
YSAssa on siis sekä _genret_ että _tekstilajit_. Pitäiskö ero niiden välillä määritellä? _Genret_ viittaa muihinkin kuin tekstin lajeihin, mutta riittääkö se eroksi?

Jos termi _tekstityypit_ otetaan, pitäisi sekin määritellä - myös jottei se sekoittuisi kirjaintyyliin. Kielitoimiston sanakirja:
tekstityyppi
1. kirjap. kirjaintyyli. Antiikva, groteski ja muut tekstityypit.
2. kiel. Kuvaileva, kertova, perusteleva tekstityyppi.

**Comment by AuHo22** [comment]
Sekä kielitieteen että kirjallisuudentutkimuksen ontologioissa (KTO, KITO) _genret_ (monikossa)-termin RT:nä on _tekstilajit._

Genrestä Wikipedia näin:
Tyylilaji eli lajityyppi eli genre (ääntyy [genre] tai [žãr]) eli tyylisuunta (ransk. genre ’laatu, laji, suku’; genre artistique ’taidelaji’) tarkoittaa jonkin taiteenalan laatua, lajia, luokkaa, tyyppiä tai esitystapaa. 

Itse olen myös tottunut perinteisesti _genrej_ä ajattelemaan taiteiden yhteydessä, _tekstilajit_ ja _tekstityypit_ ovat sitten taas enemmän kielitieteen termejä. Ruotsinkielinen ratkaisu voisi olla: _tekstilajit_ = textgenrer ja _tekstityypit_ = texttyper? (ks. alla), ja _tekstityypit_ ja _tekstilajit__ -termeihin lisätään selventävä huomautus - ilmeisesti niitä on sen takia käytetty toisiaan korvaavasti, koska vain _tekstilajit_ on ollut sanastossa.

"Även Frandsen (1998:11) tar upp begreppsförvirringen runt begreppen texttyp och genre. 
Han skiljer på teksttype  och  tekstgenrer. Texttyper definieras klassiskt från tre olika kriterier: 
1)  den  kognitiva  operationen  som  texttypen  representerar  t.ex.  beskrivande,  berättande, 
förklarande  eller  argumenterande  2)  de  språkliga  medlen  (ett  strukturellt  kriterium)  som  är 
förbunden  med  den  kognitiva  operationen  t.ex.  bruket  av  bestämda  typer  av  verb  och 
konnektorer,  3)  den  kommunikativa  funktionen  (ett  funktionellt  kriterium)  där  avsändarens 
intention realiseras med hjälp av den kognitiva operationen och de språkliga medlen."

http://www.diva-portal.org/smash/get/diva2:770058/FULLTEXT02

**Comment by mirmaid** [comment]
_Tekstityypit_ on selkeästi määriteltävissä - sulkutarkenteen keksiminen erotukseksi kirjaintyylistä on ehkä vaikeampaa, jos se on tarpeen. Sen sijaan erottelu _tekstilajin_ ja _genren_ välillä onkin aika vaikeaa muuten kuin että katsotaan tekstilajit (=tekstigenret) genren alakäsitteeksi.

**Comment by YSA-kokous** [comment]
Otetaan tekstityypit
tekstilajit KÄ genret

**Comment by jarmosaarikko** [comment]
tarvitsemme ilmeisesti "koodistoja", joista näkyy 
mitä  tyyppejä kuuluu "tekstityyppeihin" ja toisaalta 
mitä lajeja  kuulu "tekstilajeihin".   
Sanastossa tämä voitaisiin kuvata ylä-alakäsitesuhteella.  
Mutta missä sanastossa? YSA vai  KTO kielitieteen ontologia vai KITO kirjallisuuden ontologia vai SLM laji- ja muototyyppisanasto?
