### ISSUE TITLE
ukulele

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5869]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ukulele 

#### Ehdotettu termi englanniksi   

Ukulele 

#### Ehdotettu termi ruotsiksi   

ukulele 

#### Ehdotettu yläkäsite YSOssa (LT)   

[näppäilysoittimet](http://www.yso.fi/onto/yso/p1510) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85139417> 
Wikipedia : https://fi.wikipedia.org/wiki/Ukulele 
SEKO : <http://urn.fi/urn:nbn:fi:au:seko:01158> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Opi soittamaan ukulelea 

#### Perustelut ehdotukselle   

käytetty paljon Melindassa Ysa- ja Musa-terminä (295 osumaa asiasanahaussa) 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [ukulele](http://finto.fi/yse/fi/page/Y505869)

**Comment by tpalonen** [comment]
Käsite on myöt kirjastot.fi:n toivelistalla.

**Comment by ksornova** [comment]
Muusa-kokous (13.3.2018): Kannatetaan.

**Comment by mariaforsen** [comment]
Sv. ukulele
