### ISSUE TITLE
sivupersoonahäiriö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5870]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sivupersoonahäiriö](http://www.yso.fi/onto/ysa/Y505107) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

dissosiatiivinen identiteettihäiriö 

#### Perustelut ehdotukselle   

Ehdotan asiasanan sivupersoonahäiriö korvaamista termillä dissosiatiivinen identiteettihäiriö. Sivupersoonahäiriö, eli dissosiatiivinen identiteettihäiriö (Dissociative Identity Disorder eli DID), muutettiin nykyiseen muotoonsa jo vuonna 1994, kun Yhdysvalloissa käytettävästä mielenterveyden häiriöiden luokituskäsikirjasta DSM:stä julkaistiin neljäs versio. Nykyään on käytössä DSM-5, jossa termi dissosiatiivinen identiteettihäiriö on yhä käytössä. ICD-10 käyttää termiä sivupersoonahäiriö, mutta valistuneet terveydenhuollon asiantuntijat tietävät tämän sanan auttamattoman vanhentuneeksi. Lisäksi ICD-11:n lähes valmis luonnos on jo luettavissa Internetissä, ja siinä diagnoosi on muutettu muotoon dissosiatiivinen identiteettihäiriö. ICD-11 aiotaan julkaista terveydenhuollon käyttöön tänä vuonna.

Tiivistäen: sanalla sivupersoonahäiriö viitataan nykyään tutkimuksessa ja kirjallisuudessa vain dissosiatiivisen identiteettihäiriön historiaan. Ei ole myöskään tarkoituksenmukaista niputtaa dissosiatiivista identiteettihäiriötä pelkästään dissosiaatiohäiriöt-termiin sisältyväksi, sillä dissosiaatiohäiriöt ovat keskenään erilaisia. Monet DID-potilaiden elämänkerrat käsittelevät kokemuksia, jotka ovat vain dissosiatiiviselle identiteettihäiriölle tyypillisiä.

Huomasin, että termiä sivupersoonahäiriö oli käsitelty vuoden 2017 toukokuussa. Aihe lähti liikkeelle kirjasta Jänis ulvoo - Truddi Chasen 92 sivupersoonaa, jonka alkuperäinen versio When Rabbit Howls on kirjoitettu vuonna 1987. Suomennettu versio on julkaistu vuonna 1988, ja tämän takia vanhentunut termi on siinä käytössä.

Asiasana sivupersoonahäiriö ei palvele käyttötarkoitusta, sillä nykyään kirjallisuudessa ei käytetä kyseistä sanaa kuin ohimennen. Tämän vuoksi epäilen, että dissosiatiivista identiteettihäiriötä käsittelevä materiaali on luokiteltu ja luokitellaan ainoastaan dissosiaatiohäiriöt-asiasanan alle, jolloin sivupersoonahäiriö asiasanana on vielä tarpeettomampi. Sivupersoonahäiriö-asiasanan käyttäminen edellyttäisi, että asiasanoittaja olisi tietoinen siitä, että dissosiatiivisen identiteettihäiriön vanhentunut nimi on sivupersoonahäiriö. Tämän lisäksi asiaan perehtymättömien tiedonhakua vaikeuttaa vanhentuneen termin käyttö.

Ehdotus: Käytettäväksi termiksi muutetaan dissosiatiivinen identiteettihäiriö. Sivupersoonahäiriö siirretään ohjaustermiksi. 

#### Ehdottaja   

Kaisa Erkkilä 

#### Ehdottajan sähköpostiosoite   

erkkila.kaisa@gmail.com

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5107

Muutos ok. Esim. tässä Duodecimin artikkelissa käytetään sekä yksikköä että monikkoa http://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00361 (häiriö voi ilmetä erilaisena vakavuudeltaan ja oireiltaan).
