### ISSUE TITLE
Azerbaidžan

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5873]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Azerbaidžan](http://www.yso.fi/onto/ysa/Y107663) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "Azerbaijan" 

#### Perustelut ehdotukselle   

Suomenkielisessä Wikipediassa valtion/maan ensisijaisena nimenä on Azerbaijan [https://en.wikipedia.org/wiki/Azerbaijan] 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by jtuohini** [comment]
PERUTAAN EDELLINEN! (Täysi kielisokeus iski, kun luulin lukevani suomea englanninkielisellä Wikipedia-sivulla.)
