### ISSUE TITLE
mandalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5874]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mandalat 

#### Ehdotettu termi ruotsiksi   

mandalor 

#### Tarkoitusta täsmentävä selite   

Mandala (मण्डल, sanskritia: ’ympyrä’, ’kiekkomainen esine’) on on hindulaisuudessa ja tantrisessa buddhalaisuudessa eli Vajrayana-buddhalaisuudessa symbolinen kuvio, jota käytetään pyhissä rituaaleissa ja meditoimisen apuvälineenä.[1] Mandaloita käytetään myös jainalaisuudessa. Tiibetinbuddhalaisuudessa ja joissain muissakin perinteissä mandaloiden asema on niin merkittävä, että niitä voidaan käyttää jopa kokonaisten temppelien pohjapiirustuksena. (Wikipedia) 

#### Perustelut ehdotukselle   

Tarkka, täsmätermi, joka on itse asiassa aika yleinen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789523126305 

**Ehdottajan nimi:** Outi Hintikka 
**Ehdottajan organisaatio:** BTJ Finland Oy 
**Ehdottajan sähköpostiosoite:** outi.hintikka@btj.fi **Termiehdotus Fintossa:** [mandalat](http://finto.fi/yse/fi/page/Y505874)

**Comment by mariaforsen** [comment]
Sv. mandalor
