### ISSUE TITLE
muunnelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5875]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muunnelmat](http://www.yso.fi/onto/ysa/Y103611) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan termi kahtia: (1) "muunnelmat (sävellykset)", joka vastaisi entistä MUSAn asiasanaa "muunnelmat" [http://www.yso.fi/onto/musa/p369], ja (2) "muunnelmat ([jokin sopiva yleismääre])", joka toimisi paremmin YSAn yleisterminä. 

#### Perustelut ehdotukselle   

Muunnelmat (toiselta nimeltään variaatiot) ovat tärkeä sävellysmuoto, joka ilmiönä ei ole kytköksissä YSAn asiasanan "toisinnot" tarkoittamaan asiaan.

Termi "muunnelmat" on jo samassa merkityskessä myös SLM:ssä [http://urn.fi/URN:NBN:fi:au:slm:s577] 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Musiikin osalta sopii.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5824. Mikä on muunnelman ja _parafraasin_ suhde? Entä _muunnelmat_-termin suhde termiin _muunnelmamuoto_?

Käsitellään muunnelmat muun kuin musiikin osalta tämän ratkaisun jälkeen. Joissakin Melindan viitteissä mahdollisia _variaatio (kielitiede), variaatiolaskenta_ (?). _Muuntelusta_ on erillinen issue, https://github.com/Finto-ehdotus/YSE/issues/5307.

**Comment by mariaforsen** [comment]
Sv. variationer (kompositioner)

**Comment by mirmaid** [comment]
Muusa: Ks. myös #5824. Mikä on _muunnelman_ ja _parafraasin_ suhde? Entä _muunnelmat_-termin suhde termiin _muunnelmamuoto_?

**Comment by YSA-kokous** [comment]
muunnelmat (sävellykset)

**Comment by mirmaid** [comment]
muunnelmat (musiikki) / SLM

**Comment by mirmaid** [comment]
Muulle kuin musiikille olisi termejä:
toisinnot
variaatio (kieli)
muuntelu (biologia)
variaatiolaskenta

Saadaanko kaikki kuvailtua näillä?

**Comment by YSA-kokous** [comment]
Ei tarvetta lisätä muita termejä.

**Comment by krinay** [comment]
Ehdotus:
toisinnot KT variantit (ei muita ohjaustermejä), RT variaatio (kieli)

**Comment by YSA-kokous** [comment]
toisinnot KT variantit (ei muita ohjaustermejä), RT variaatio (kieli)
parafraasit (kirjallisuus) KT muunnelmat (kirjallisuus)
