### ISSUE TITLE
johtoaiheet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5876]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

johtoaiheet 

#### Ehdotettu termi ruotsiksi   

ledmotiv (musik) 

#### Ehdotettu termi englanniksi   

leitmotif 

#### Ehdotettu yläkäsite YSOssa (LT)   

[motiivit](http://www.yso.fi/onto/yso/p3402) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85075932> 
Wikidata : https://www.wikidata.org/wiki/Q221117 

#### Tarkoitusta täsmentävä selite   

Ohjelmamusiikissa, oopperoissa ja muussa draamallisessa musiikissa käytettävä sävelaihe, joka symboloi tiettyä henkilöä, esinettä tai tilannetta. [https://fi.wikipedia.org/wiki/Johtoaihe] 

#### Perustelut ehdotukselle   

Kyseiselle asialle ei ole vanhastaan sopivaa asiasanaa. Lisäksi "aiheet", "motiivit" ja "teemat" ovat muutenkin parhaillaan osin jaettavina YSAssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2637448 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [johtoaiheet](http://finto.fi/yse/fi/page/Y505876)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5460

**Comment by ksornova** [comment]
halutaanko lisätä myös ranskankielistä "motif conducteur"? Kävisikö kt:ksi "johtomotiivit" tai "johtomotiivit (musiikki)?

**Comment by jtuohini** [comment]
Ranskankielisestä en menisi varmuuteen, kun sitä ei suomenkielisessä kirjoittelussa taideta juuri käyttää (toisin kuin tuota saksankielistä). Suomenkilinen _johtomotiivit_ olisi kyllä hyvä KT-muoto lisättäväksi, kun sitä näyttää ainakin googlaamalla löytyvän Wagneriin liittyen.

**Comment by mariaforsen** [comment]
Tarkenne (musik) tosiaan tarpeen ruotsiksi, koska käytetään myös kirjallisuudessa yms.

**Comment by krinay** [comment]
Vrt. aiempi termiehdotus: johtomotiivit
https://github.com/Finto-ehdotus/YSE/issues/5460

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
En olisi ihan varma että käyttö rajautuu musiikkiin ilman tarkennetta: https://aaltodoc.aalto.fi/handle/123456789/13986, https://kunstimuuseum.ekm.ee/fi/syndmus/neuvostoyo-raul-rajangu/, https://kavi.fi/fi/elokuva/104290-kuvanveistaja-steinerin-suuri-hurmio, http://www.rudolfsteinerkoulu.fi/arkisto/uutiset/uutinen/browse/1/article/steiner-pedagogiikan-myrskynsilmaessae/?tx_ttnews[backPid]=55&cHash=21d9234a0d298ed10e720cc3cf4425f5

**Comment by mariaforsen** [comment]
Myös Kielitoimiston sanakirja määrittelee monimerkityksisenä: 
-johtoaihe = "toistuva sävelaihe draamamusiikissa, toistuva aihelma novelleissa tms., johtoteema,-motiivi." 
-johtomotiivi "= johtoaihe"

Tarkenteen lisääminen molemmille lienee ainoa tapa varmistaa että termit käytetään johdonmukaisesti ja samalla tavalla molemmilla kielillä..

Ruotsiksi siis ledmotiv = johtoaihe + johtomotiivi, joten ruotsiksi on pakko laittaa tarkenteita miten vain.

**Comment by YSA-kokous** [comment]
johtoaiheet (musiikki)
