### ISSUE TITLE
dokumenttikamerat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5879]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dokumenttikamerat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kamerat](http://www.yso.fi/onto/yso/p6350) 

#### Vastaava käsite muussa sanastossa   

Wikipedia: Dokumenttikamera : https://fi.wikipedia.org/wiki/Dokumenttikamera 

#### Tarkoitusta täsmentävä selite   

Wikipedia: "Dokumenttikamera on papereiden ja muiden asiakirjojen tai esineiden kuvaamiseen tarkoitettu digitaalinen kamera. Dokumenttikamerasta kuva lähetetään esimerkiksi videoprojektorille näytettäväksi. 
Laitteessa on valaisimet kuvattavan kohteen valaisemiseen. Käytössä voi olla myös ns. alavalo, joka mahdollistaa kalvojen käyttämisen piirtoheittimen tapaan." 

#### Perustelut ehdotukselle   

Laite, joka käytettävissä joissakin kirjastoissa. Käsitteelle olisi käyttöä muuallakin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [dokumenttikamerat](http://finto.fi/yse/fi/page/Y505879)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5752

**Comment by mariaforsen** [comment]
Sv. dokumentkameror
