### ISSUE TITLE
kuormapyörät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5881]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuormapyörät 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pyörät](http://www.yso.fi/onto/yso/p3554) 

#### Tarkoitusta täsmentävä selite   

Pyörä, jossa on etuosassa laatikko ja jolla voi kuljettaa tavaroita. Siitä käytetään myös termejä tavarapyörä, kuljetuspyörä ja laatikkopyörä 

#### Perustelut ehdotukselle   

Erityinen pyörätyyppi. Lainattavissa joistakin kirjastoista. kirjastot.fi/suomi.fi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [kuormapyörät](http://finto.fi/yse/fi/page/Y505881)

**Comment by jtuohini** [comment]
LT-suhteeksi varmaan mieluummin **[polkupyörät](http://www.yso.fi/onto/yso/p5969)** kuin **pyörät** (jälkimmäinen ei viittaa ajoneuvoihin)?

**Comment by EsaMPKK** [comment]
Google:
kuormapyörä 5 170 osumaa
tavarapyörä 50 000
kuljetuspyörä 20 700
laatikkopyörä 9 640

**Comment by mirmaid** [comment]
Sain eniten viitteitä sanalla kuljetuspyörä, mutta se voi tarkoittaa muutakin kuin tätä polkupyörää. Tavarapyörä tuo myös runsaasti viitteitä. Terminä kuormapyörä on kyllä omaan korvaani miellyttävin.

**Comment by jarmosaarikko** [comment]
Postillahan oli oma jopomalli, joka on mielestäni tavarapyörä tai kuljetuspyörä, mutta ei sellainen laatikkopyörä, vaan tukevat taakkatelineet. Menevätkö muuten pyöräriksat tähän kategoriaan samoin kuin lasten kuljetuspyörät, joissa siis paikka lapsille. Kuljetuspyörät olisi näille kaikille yläkäsite. Pitäisi kaivaa arkistoista kuva Kiinasta, josa pyörän päälle oli kasattu 4m korkea risukasa... se olisi meillä tosin laiton..

**Comment by YSA-kokous** [comment]
kuormapyörät
