### ISSUE TITLE
lämpöprässit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5882]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lämpöprässit 

#### Tarkoitusta täsmentävä selite   

Lämpöprässillä painetaan vinyylileikkurilla leikatut kuvat kankaalle 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

#### Perustelut ehdotukselle   

Lämpöprässi asiakkaiden käytettävissä muutamissa kirjastoissa. kirjastot.fi/suomi.fi 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [lämpöprässit](http://finto.fi/yse/fi/page/Y505882)

**Comment by mariaforsen** [comment]
Sv. värmepressar

**Comment by YSA-kokous** [comment]
MAOssa prässäyslaitteet, tutkitaan vielä.

**Comment by YSA-kokous** [comment]
Otetaan lämpöprässit, onko prässäyslaitteet = puristimet. Entä prässäys, onko laajempi kuin 24, 26?

**Comment by mariaforsen** [comment]
Allärs: pressning (textilvård), joten ruotsin osalta aika rajattu.

**Comment by mirmaid** [comment]
Käytetty Melindassa useita kertoja myös kukkien prässäyksestä.

**Comment by YSA-kokous** [comment]
Jaetaan prässäys.

**Comment by mirmaid** [comment]
kasvien prässäys
prässäys (tekstiilit)

**Comment by YSA-kokous** [comment]
kasvien prässäys
prässäys (tekstiilit)

**Comment by mariaforsen** [comment]
Sv. 
växtpressning
pressning (textilvård)
