### ISSUE TITLE
vinyylileikkurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5883]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vinyylileikkurit 

#### Tarkoitusta täsmentävä selite   

Vinyylileikkurilla voit leikata yksittäisiä tarroja sekä vinyyliä kangaspainatuksia varten 

#### Perustelut ehdotukselle   

Vinyylileikkuri on asiakkaiden käytettävissä muutamissa kirjastoissa, joten tätä termiä tarvitaan kyseisen palvelun kuvailemiseen. kirjastot.fi/suomi.fi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [vinyylileikkurit](http://finto.fi/yse/fi/page/Y505883)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Vinyl_cutter

https://www.tevella.fi/kuluttajat/silhouette-cameo-3-netto

**Comment by mariaforsen** [comment]
Sv. vinylskärare ET folieskärare, vinylplotter

**Comment by YSA-kokous** [comment]
Tutkitaan vielä vinyylileikkurit/kuvioleikkurit/?

**Comment by satuniininen** [comment]
Kuvioleikkurilla tarkoitetaan yleensä ns. kuviolävistäjää, esim. http://www.fiskars.fi/tuotteet/askartelu/kuviolavistajat. 

Englanniksi tämä on vakiintunut muotoon vinyl cutter tai vinyl cutting machine (laitevalmistajan verkkosivuilta tarkastettu), joten suomeksikin vinyylileikkuri olisi luonteva. Toisaalta myös muovimattojen leikkaamiseen tarkoitettua käsikäyttöistä leikkuria voidaan kutsua vinyylileikkuriksi. Tarvitaanko siis sulkutarkenne? vinyylileikkurit (sähkölaitteet)? digitaaliset vinyylileikkurit?

**Comment by YSA-kokous** [comment]
vinyylileikkurit
