### ISSUE TITLE
paperisilppurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5885]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

paperisilppurit 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Paperisilppuri 

#### Tarkoitusta täsmentävä selite   

Paperisilppuri on laite, joka silppuaa paperia (esim. luottamuksellisia asiakirjoja, joiden ei haluta päätyvän ulkopuolisten käsiin) hyvin pieniksi palasiksi tai ohuiksi viipaleiksi niin, ettei paperilla ollutta tekstiä ole enää mahdollista lukea 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

#### Perustelut ehdotukselle   

Yleisesti käytössä oleva laite. kirjastot.fi/suomi.fi 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [paperisilppurit](http://finto.fi/yse/fi/page/Y505885)

**Comment by mariaforsen** [comment]
Sv. dokumentförstörare ET pappersförstörare

**Comment by AuHo22** [comment]
asiakirjatuhoojat KÄ paperisilppurit
