### ISSUE TITLE
poravasarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5886]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

poravasarat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[porat](http://www.yso.fi/onto/yso/p9580) 

#### Tarkoitusta täsmentävä selite   

Poravasara on betonin ja kiven poraamista varten. 

#### Perustelut ehdotukselle   

Betonin ja kiven poraamista varten on oleva laite. kirjastot.fi/suomi.fi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [poravasarat](http://finto.fi/yse/fi/page/Y505886)

**Comment by jtuohini** [comment]
Olisiko **[porakoneet](http://www.yso.fi/onto/yso/p21897)** täsmällisempi LT-suhteiseksi asiasanaksi? Luullakseni **porat** viittaa erityisesti käsiporiin, kun poravasara taas on selvästi sähkölaite.
 
Tarvitaanko lisäksi KT-suhteiseksi _iskuporakoneet_ tai se omaksi asiasanakseen?

**Comment by mariaforsen** [comment]
Sv. borrhammare, slagborrar

**Comment by LeKorsu** [comment]
Pitäisi varmaan miettiä hierarkiaa laajemmalti. Tässä yksi pähkäily, mutta pitäisikö vielä jättää ohjaustermiksi. 
Porat 
ST käsiporat
ST porakoneet ja sitten mietintää onko tarvetta vielä suppeammille (esim. iskuporakoneet, poravasarat) vai riittääkö ohjaustermi
https://www.bauhaus.fi/koneet-ja-tyokalut/koneet/porakoneet.html

**Comment by jarmosaarikko** [comment]
onko tarpeen eritellä kuvailussa erilaisia porakoneita?  Ei ehkä julkaisuissa, mutta museopuolella voi olla selvä tarve.  Minusta voisi riittää tässä vaiheessa "porakoneet". Mikäli niitä erilaisia porakoneita tarvitaan kuvailussa, niin tämän alakäsitteiksi.
