### ISSUE TITLE
roskapihdit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5887]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

roskapihdit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[työvälineet](http://www.yso.fi/onto/yso/p3761) 

#### Tarkoitusta täsmentävä selite   

Pitkävartinen työväline, jolla on helppo poimia roskia ja muita pienehköjä esineitä maasta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

#### Perustelut ehdotukselle   

Roskapihtejä on tarjolla lainattaviksi monissa kirjastoissa. 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [roskapihdit](http://finto.fi/yse/fi/page/Y505887)

**Comment by mariaforsen** [comment]
Sv. skräpplockare ET skräptänger, skräpupplockare
