### ISSUE TITLE
vesivaa'at

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5888]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vesivaa'at 

#### Ehdotettu yläkäsite YSOssa (LT)   

[työvälineet](http://www.yso.fi/onto/yso/p3761) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Vesivaaka 

#### Tarkoitusta täsmentävä selite   

Vesivaaka eli vatupassi on mittaväline, jolla voidaan määrittää kallistuskulmia. Sillä tutkitaan erityisesti, onko kappale vaaka- tai pystysuorassa. Vesivaaka perustuu nesteiden taipumukseen valua matalimpaan mahdolliseen tilaan. Yleisin sovellus on suljetun läpinäkyvän putken sisälle laitettu neste, johon on jätetty pieni ilmakupla. Putken ylimmän pinnan ollessa vaakasuora kupla asettuu putken keskelle. Jos pinta on vinossa, kupla hakeutuu sille puolelle, joka on toista korkeammalla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

#### Perustelut ehdotukselle   

Vesivaakoja on käytettävissä muutamien kirjastojen pajoissa. 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [vesivaa'at](http://finto.fi/yse/fi/page/Y505888)

**Comment by mirmaid** [comment]
MAO-ontologiassa on _vesivaa'at_.

**Comment by mariaforsen** [comment]
Sv. vattenpass

**Comment by satuniininen** [comment]
En. spirit levels, ei LCSH-siltausta (lähin vastine _leveling_)

**Comment by LeKorsu** [comment]
Vatupassista ohjaustermi
