### ISSUE TITLE
aulatilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5889]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aulatilat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tilat](http://www.yso.fi/onto/yso/p3602) 

#### Tarkoitusta täsmentävä selite   

Aulatilat 

#### Perustelut ehdotukselle   

Ohjausterminä on jo olemassa aulat se ohjaa termiin eteistilat. Mielestäni eteiset ovat eri asia kuin aulat. Aulat ovat esim. kirjastoissa olevia isompia tai pienempiä avoimia tiloja. Yleensä eteinen on erikseen ja sieltä tullaan aulaan. Aula voi olla myös muissa kuin ensimmäisessä kerroksessa eli niissä ei ainakaan käy eteistilat-käsite. Käsite voisi olla myös muodossa aulat mutta yhteinäisyyden vuoksi olisi varmaankin parempi, kun se olisi eteistilat. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [aulatilat](http://finto.fi/yse/fi/page/Y505889)

**Comment by mariaforsen** [comment]
Sv. aulor

**Comment by AuHo22** [comment]
Mielestäni yksityisasuntojen yhteydessä puhutaan edelleen eteisistä / eteistiloista myös, mutta julkisten rakennusten yhteydessä harvemmin, sitten on sisäänkäyntiä ja aulaa / aulatiloja. Eteistilat -termi ei epämääräisenä ole oma suosikkini - suhteita voisi miettiä uudelleen: eteiset - aulat / aulatilat ? - myös odotustilat termi on omanaan.

**Comment by satuniininen** [comment]
Lähin engl. vastine lienee _entrance halls_

**Comment by mirmaid** [comment]
Eli Aulin ehdotus on, että tutkitaan pitäisikö/voisiko vaihtaa eteistilat > eteiset? Melindan viitteissä eteistilat-termiä on käytetty yksityisasuntojen lisäksi esim. päiväkotien ja kuntosalien yhteydessä. Joissakin tapauksissa eteiset ja aulat varmaan on päällekkäinen (nimenomaan julkisten rakennusten osalta).

Eteis/aulatiloja käsittelevissä julkaisuissa eng. myös lounge, lobby.

**Comment by jarmosaarikko** [comment]
olen ulkomailla havainnut, että Aula on usein jonkinlainen juhlasali tai suuri sali eikä mikään eteinen. (siis englanniksi) eli sekaannuksen vaara on, jos käytettäisiin "aulat".   Kannatan "aulatilat" omana käsitteenään.

**Comment by satuniininen** [comment]
Entäpä jos muutettaisiin eteistilojen käytettävä termi muotoon **eteis- ja aulatilat**? Tällöin termivalinta olisi synkassa käsitteen kuvailukäytön kanssa, joka sisältää kaikenlaista yksityisasunnoista päiväkoteihin ja lobby design -teoksiin. Käytetty Melindassa vain 49 kertaa.

**Comment by YSA-kokous** [comment]
eteistilat > eteiset
aulat
