### ISSUE TITLE
lukulaitteet (näyttölaitteet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5890]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lukulaitteet (näyttölaitteet)](http://www.yso.fi/onto/ysa/Y201713) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

e-kirjan lukulaitteet.  Joko muutetaan tuoksi tai laitetaan synonyymiksi 

#### Ehdottaja   

Mia Nikula 

#### Ehdottajan organisaatio   

Kirjastot.fi 

#### Ehdottajan sähköpostiosoite   

mia.nikula@kirjastot.fi 

#### Perustelut ehdotukselle   

e-kirjan lukulaitteet olisi tarkempi ja kuvailevampi käsite.

**Comment by mirmaid** [comment]
Kannatan, mutta mahtaako tämä vielä lyhentyä muotoon _e-lukulaite_, jolla löytyy jo silläkin reilusti viitteitä. Helmetissä myös muodossa _e-kirjanlukulaite_.

**Comment by vthuhtala** [comment]
e-lukulaite - lyhempi parempi

Samalla lukulaitteet (skannerit) pitää poistaa, koska se on ainoa skannerit alla oleva termi. Vai onko olemassa skannereita, jotka eivät ole lukulaitteita?

**Comment by satuniininen** [comment]
Kannatan muotoa _e-lukulaitteet_.

**Comment by YSA-kokous** [comment]
e-kirjan lukulaitteet
