### ISSUE TITLE
telekopiolaitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5891]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[telekopiolaitteet](http://www.yso.fi/onto/ysa/Y106787) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

faksi tai fax 

#### Perustelut ehdotukselle   

Faksi/fax on yleisesti käytetty käsite tuosta laitteesta. Telekopiolaite on vanhahtava termi. 

#### Ehdottaja   

Mia Nikula 

#### Ehdottajan organisaatio   

Kirjastot.fi 

#### Ehdottajan sähköpostiosoite   

mia.nikula@kirjastot.fi

**Comment by mirmaid** [comment]
Toisaalta koko tekniikka alkaa jäädä historiaan, omaan korvaani nimitys ei ehkä siksi tunnu häiritsevän vanhentuneelta. Vaihtokin lienee ok.

**Comment by jarmosaarikko** [comment]
siis vaihdetaan ohjaustermi ja käytetty termi keskenään?
