### ISSUE TITLE
saumauskoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5892]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[saumauskoneet](http://www.yso.fi/onto/ysa/Y104290) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

saumurit 

#### Perustelut ehdotukselle   

Saumurit on mielestäni yleisesti käytetty muoto tuosta tekstiilikoneisiin kuuluvasta laitteesta. 

#### Ehdottaja   

Mia Nikula 

#### Ehdottajan organisaatio   

Kirjastot.fi 

#### Ehdottajan sähköpostiosoite   

mia.nikula@kirjastot.fi

**Comment by mirmaid** [comment]
Kannatan ehdotusta. Melindassa on muutamia viitteitä joissa käsitellään saumauskoneita muussa kuin tekstiiliteollisuudessa. Niiden osalta termi _saumaus_ voisi riittää, tosin senkin kattavuus on nyt melko laaja.

**Comment by mariaforsen** [comment]
Allärs: overlockmaskiner. Ruotsiksi ei ole olemassa kaikkia alueita kattavaa termiä, vaan tämä on nimenomaan tekstiiliteollisuuden.
