### ISSUE TITLE
suurentavat lukulaitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5893]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suurentavat lukulaitteet 

#### Tarkoitusta täsmentävä selite   

Näkövammaisille tarkoitettu apuväline. Käytettävissä muutamissa kirjastoissa. Liityy esteettömyyspalveluihin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

#### Perustelut ehdotukselle   

Löytyy jo termi suurennuskojeet mutta se on valokuvausvälineisiin liitetty termi eikä kuvaa riittävän hyvin kyseistä laitetta. 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [suurentavat lukulaitteet](http://finto.fi/yse/fi/page/Y505893)

**Comment by mirmaid** [comment]
Myös _(elektroniset) suurennuslaitteet_, _lukutelevisiot_ (ehkä KT-muodoiksi).
http://www.hus.fi/sairaanhoito/sairaalat/Hyks_muut_toimipisteet/silmatautien_kuntoutuspoliklinikka/apuvalineet/Sivut/default.aspx
https://www.aviris.fi/fi/etusivu/2523?q=lukutelevisio&Submit=Hae
http://www.eksote.fi/terveyspalvelut/apuvalineet/Documents/APUVA-luovutusperusteita%20ja%20toimintaohjeita.pdf

**Comment by mariaforsen** [comment]
Sv. förstorande läsapparater ET förstorande läshjälpmedel
