### ISSUE TITLE
sähkönkulutusmittarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5894]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sähkönkulutusmittarit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mittauslaitteet](http://www.yso.fi/onto/yso/p3583) 

#### Tarkoitusta täsmentävä selite   

Laite, joka mittaa yksittäisen laitteen sähkönkulutusta. Siitä käytetään myös nimitystä energiankulutusmittari mutta mielestäni parempi muoto on sähkönkulutusmittari. 

#### Perustelut ehdotukselle   

YSOssa on olemassa termit sähkönkulutus ja sähkömittarit. Sähkömittarit mittaavat asunnon /talon kokonaiskulutusta kun taas sähkönkulutusmittari mittaa yksittäisen laitteen sähkönkulutusta. Sähkönkulutusmittareita on lainattavissa monissa kirjastoissa ja energiayhtiöissä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [sähkönkulutusmittarit](http://finto.fi/yse/fi/page/Y505894)

**Comment by mariaforsen** [comment]
Sv. elförbrukningsmätare ET elenergimätare, energiförbrukningsmätare

**Comment by LeKorsu** [comment]
Googlen perusteella sähkönkulutusmittari(t) huomattavasti suositumpi: 25300 osumaa, energiankulutusmittari 6270.

**Comment by mirmaid** [comment]
Toivottavasti näitä osataan käyttää oikein...(kuvailussa siis  :smile: :electric_plug:)

**Comment by ilona-x** [comment]
Saattaa kyllä mennä sekaisin sähkömittarit ja sähkönkulutusmittarit. Esimerkiksi Tukes näyttää käyttävän sivuillaan termiä "kulutusmittari", vaikka kyse ilmeisesti näistä YSA:n sähkömittareista. :roll_eyes: 
http://www.tukes.fi/fi/Toimialat/Mittauslaitteet/Kulutusmittaukset/

**Comment by ilona-x** [comment]
Ja jotta ei olisi liian selkeää, niin lisäksi myynnissä näyttää olevan energiankulutusmittareita, jotka asennetaan sähkömittarin yhteyteen, joka mittaa koko kiinteistön sähkönkulutusta.
https://www.verkkokauppa.com/fi/product/33526/dkkcf/NORGO-langaton-energiankulutusmittari-koko-kiinteistoon

**Comment by YSA-kokous** [comment]
Yritetään suunnata käyttöä ohjaustermein ja määritelmillä.
