### ISSUE TITLE
vastamelukuulokkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5895]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vastamelukuulokkeet 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Vastamelukuuloke 

#### Tarkoitusta täsmentävä selite   

Taustamelua vähentävät kuulokkeet. Vastamelukuuloke on kuuloketyyppi, joka vähentää ympäristön äänten pääsyä korvaan tuottamalla meluun nähden vastakkaisessa vaiheessa olevan äänen, joka pyrkii kumoamaan melun. 

#### Perustelut ehdotukselle   

Jo olemassa oleva käsite kuulonsuojaimet ei riitä kuvaamaan tätä laitetta. Kuulonsuojaimet vaimentavat/hiljentävät kaiken melun mutta vastamelukuulokkeet tuottaa vastakkaissen äänen eli melunvaimennus tapahtuu ihan eri periaatteella. Vastamelukuulokkeet on käytettävissä muutamissa kirjastoissa, 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [vastamelukuulokkeet](http://finto.fi/yse/fi/page/Y505895)

**Comment by mariaforsen** [comment]
Sv. brusreducerande hörlurar
