### ISSUE TITLE
verenpainemittarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5896]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

verenpainemittarit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mittauslaitteet](http://www.yso.fi/onto/yso/p3583) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Verenpainemittari 

#### Tarkoitusta täsmentävä selite   

Verenpainemittari on mittari, jolla mitataan verenpaine. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat käsitteet (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

#### Perustelut ehdotukselle   

Mittauslaitteista löytyy jo esim. sykemittarit mutta sangen yleinen laite verenpainemittarit puuttuu. Verenpainemittareita on käytettävissä ja lainattavissa monissa kirjastoissa. Mittauslaitteet on liian yleinen käsite tälle tietylle laitteelle. 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [verenpainemittarit](http://finto.fi/yse/fi/page/Y505896)

**Comment by mirmaid** [comment]
TEROssa ja FinMeSHissä.

**Comment by mariaforsen** [comment]
Sv. blodtrycksmätare

**Comment by AuHo22** [comment]
Lehtiaineiston kuvailussa voisi olla hyödyllinen termi myös - erilaisia rannemittareita ja olkavarsimittareita voi olla vertailussa
