### ISSUE TITLE
verkkolehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5897]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkolehdet](http://www.yso.fi/onto/ysa/Y110493) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

e-lehdet 

#### Ehdottaja   

Mia Nikula 

#### Ehdottajan organisaatio   

Kirjastot.fi 

#### Ehdottajan sähköpostiosoite   

mia.nikula@kirjastot.fi 

#### Perustelut ehdotukselle   

e-lehdet käsitettä käytetään nykyään yleisesti medioissa ja kirjastoissa (mm. kirjastojen kotisivuilla). e-lehdet on jo olemassa ohjausterminä mutta ehdotan, että e-lehdet olisi varsinainen käsite.

**Comment by mariaforsen** [comment]
Allärs: elektroniska tidskrifter=verkkolehdet
Olisiko syytä lisätä KT elektroniset lehdet?

**Comment by AuHo22** [comment]
Aiemmin vaihdettiin myös sähkökirjat -> e-kirjat, eli lieneekö tässä nyt samalla tavalla kyse toisen sanan korvautumisesta yleisemmin käytetyllä...

**Comment by mirmaid** [comment]
Verkkolehdet tuo edelleen enemmän viitteitä Googlella kuin e-lehdet.

**Comment by YSA-kokous** [comment]
Ei muutosta, KT elektroniset lehdet
