### ISSUE TITLE
työvälineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5898]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työvälineet](http://www.yso.fi/onto/ysa/Y104712) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

työkalut 

#### Perustelut ehdotukselle   

Työkalut on yleisemmin käytetty sana. Monessa (fintossakin olevassa) työkalun nimessä on tuo sana, esim. käsityökalut, sähkötyökalut 

#### Ehdottaja   

Mia Nikula 

#### Ehdottajan organisaatio   

Kirjastot.fi 

#### Ehdottajan sähköpostiosoite   

mia.nikula@kirjastot.fi

**Comment by vthuhtala** [comment]
'työvälineet' on yleistermi ja sitä on käytetty myös muussa merkityksessä kuin fyysinen työkalu, esimerkiksi kirja Parempi lehtijuttu https://finna.fi/Record/alli.300521

**Comment by jarmosaarikko** [comment]
Alakäsitteinä ei ole kuitenkaan muita kuin noita fyysisiä työkaluja.  Melindassa on tosin viitattu esim. ohjelmistoihin, yms.

**Comment by mirmaid** [comment]
_Työvälineet_-termiä on käytetty paljon laajemmin kuin pelkistä työkaluista, konkreettisenakin esim. heti ensimmäisten Melinda-viitteiden joukossa neuletöiden ja askartelun yhteydessä.

**Comment by mianikula** [comment]
Mirja pyysi kommentoimaan, millaisista lainattavista työvälineistä on kyse. Tällaisista: juotoskolvi, porakone, iskuporakone, pistosaha, epäkeskohiomakone, tasohiomakone, kärkihiomakone jne. Laajin "kokoelma" löytyy Tapiolan kirjaston työkalulainaamosta: http://www.helmet.fi/fi-FI/Kirjastot_ja_palvelut/Tapiolan_kirjasto/Kirjaston_palvelut/Tyokalulainaamo(110886).

**Comment by mirmaid** [comment]
Työkalulainaamon välineisiin sopisi myös YSAn _sähkötyökalut_?

**Comment by mianikula** [comment]
Juu, Tapiolan kirjaston työkalulainaamon välineisiin sopisi myös sähkötyökalut mutta esim. Sellon kirjastossa osa työkaluista on ilman virtaa käyviä, joten siellä se ei käy.

**Comment by mirmaid** [comment]
Olisiko mahdollista käyttää siinä tilanteessa vaikka molempia: _käsityökalut, sähkötyökalut_? _Työvälineet_-termin korvaaminen _työkalut_-termillä ei oikein onnistu, joten sitten pitäisi ottaa työkalut erikseen - ei sekään tietysti mahdotonta ole (MAOssa, KULOssa ja TEROssa on).

**Comment by mianikula** [comment]
Minulle sopii oikein hyvin, että lisätään täysin uusi termi työkalut. Sitä oikeastaan alunperin halusinkin, mutta Tuomas oli kirjoittanut siihen exceliin, että voi ehdottaa termimuutosta, joten tein termimuutosehdotuksen. 
Kirkannasta tulevassa datassa on palvelulle vain yksi standardinimi eli em. tapauksessa valitaan nimeksi joko käsityökalut tai sähkötyökalut. Kirjasto voi halutessaan kirjoittaa kuvauksen kyseisestä palvelusta mutta sinne ei laiteta asiasanoja vaan se on "vapaatekstinen" kuvaus palvelusta. Osa kirkannan dataa näyttävistä sovelluksista osaa hakea myös noista kuvauskentistä (mm. kirkannan omassa julkisessa sovelluksessa eli Kirjastohakemistossa) mutta osassa haku kohdistuu vain palvelun nimeen. Noista standardinimistä muodostetaan Kirjastohakemistossa palvelulistaus, jolloin kutakin palveun nimeä klikkaamalla saa esille kaikki kirjastot, joissa kyseinen palvelu/laite on. Kirkannan dataa käytetään mm. suomi.fi-portaalissa, yksittäisen kirjaston finna-sivuilla, valtakunnalisella varaamo.fi-sivulla jne.

**Comment by YSA-kokous** [comment]
Kävisikö kuitenkin työvälineet?

**Comment by mianikula** [comment]
Käy.
