### ISSUE TITLE
digituki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5899]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

digituki 

#### Perustelut ehdotukselle   

Valtiovarainministeriön käyttämä käsite 

#### Tarkoitusta täsmentävä selite   

(Julkisten) palveluiden digitaaliseen asiointiin annettava opastus varsinkin niille, jotka eivät osaa itse käyttää digitaalisia palveluja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [digituki](http://finto.fi/yse/fi/page/Y505899)

**Comment by mirmaid** [comment]
http://vm.fi/artikkeli/-/asset_publisher/digituki-taataan-sita-tarvitseville

**Comment by mariaforsen** [comment]
Sv. digitalt stöd, "digistöd"

**Comment by vthuhtala** [comment]
Olisiko hierarkia neuvonta -> digineuvonta parempi? Termiä 'tuki' käytetty mielessä "avustus"

**Comment by LeKorsu** [comment]
Digituki ohjaustermiksi KÄ digineuvonta?

**Comment by jarmosaarikko** [comment]
YSO:ssa palvelut alakäsitteenä on "tekniset palvelut", jonka alla on **atk-tuki** <http://www.yso.fi/onto/yso/p23265>. Eikös tämä "**digituki**" ole hyvin lähessä sitä käsitettä ellei suorastaan sama (ehkä ei, kts. alla)?   YSA:ssa on "atk-tuki" ryhmässä 72 ja "tekniset palvelut" palveluiden alla ryhmässä 75.   
Neuvonta saattaisi ehkä parempi viitekehys:  edellä kuvatussa linkissä mainitaan
- _Toimintamallissa tulee kuvata muun muassa digiasioinnin ja tuen antamisen turvallisuuteen ja tietosuojalainsäädäntöön liittyviä kysymyksiä. Tässä yhteydessä tulee ratkottavaksi muun muassa toisen puolesta asioinnin ja asiointivaltuuden antamiseen liittyviä asioita._
tällöin pitäisi olla digineuvonta, mutta sitä käytetään siis vähäemmän.    

Ehdotukseni: Käytetty termi: digineuvonta   Ohjaustermi: digituki   BT:neuvonta RT atk-tuki

**Comment by ilona-x** [comment]
Digitukea antavista henkilöistä käytetään näköjään termiä digineuvoja esim. https://suomidigi.fi/digineuvoja-kotiin/. Kannattaisin siis tuota digineuvonta termiä. Tosin myös digitukihenkilö tuottaa joitain tuloksia Googlella. :smile:

**Comment by YSA-kokous** [comment]
digineuvonta

**Comment by mariaforsen** [comment]
Sv. digirådgivning ET digital rådgivning
