### ISSUE TITLE
pöytäjalkapallo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5900]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pöytäjalkapallo 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit välineen mukaan](http://www.yso.fi/onto/yso/p1735) 

#### Tarkoitusta täsmentävä selite   

Pöydällä pelattava jalkapallopeli, josta "tankoja" pyörittelemällä saadaan muoviset pelihahmot liikkumaan 

#### Perustelut ehdotukselle   

fintosta löytyy jo pöytäjääkiekko, voisiko lisätä myös pöytäjalkapallon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastojen palveluja kuvaavat termit (tallentuvat mm. suomi.fi-portaalin palvelutietovarantoon) 

**Ehdottajan nimi:** Mia Nikula 
**Ehdottajan organisaatio:** Kirjastot.fi 
**Ehdottajan sähköpostiosoite:** mia.nikula@kirjastot.fi **Termiehdotus Fintossa:** [pöytäjalkapallo](http://finto.fi/yse/fi/page/Y505900)

**Comment by mariaforsen** [comment]
Sv. bordsfotboll ET foosball, bordfotboll
