### ISSUE TITLE
varavankilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5901]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

varavankilat 

#### Perustelut ehdotukselle   

Suomen ensimmäinen ulkotyövankila perustettiin vuonna 1914 Ilmajoelle. Se toimi aluksi Ilmajoen vankisiirtolan nimellä. Päävankilan alaisissa siirtoloissa vankeja pidettiin, että he pystyisivät työskentelemään ulkoilmassa. 21.1.1919 annettiin asetus Sukevan, Ilmajoen, Konnunsuon, Lammin ja Mäntyharjun vankisiirtoloiden muodostamisesta itsenäisiksi, väliaikaisiksi varavankiloiksi. Nämä olivat Suomen ensimmäiset varavankilat. Vankeinhoitolaitoksesta annettu asetus 21.3.1925 määritteli varavankilat hallintonsa puolesta joko itsenäisiksi tai päävankilan alaisiksi. Varavankilaan sijoitettiin kyseisen asetuksen perusteella lähinnä tutkintavankeja ja vankeja kuljetuksen aikana, mutta joissain tapauksissa myös kuritushuone- ja vankeusrangaistuksista kärsiviä vankeja.
http://wiki.narc.fi/portti/index.php/Varavankilat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.senaatti.fi/app/uploads/2017/12/2015_Teppo_Vaala_Pelson-vankila.pdf 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [varavankilat](http://finto.fi/yse/fi/page/Y505901)

**Comment by mariaforsen** [comment]
Sv. reservfängelser
