### ISSUE TITLE
konventiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5904]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

konventiot 

#### Ehdotettu termi ruotsiksi   

konventioer 

#### Ehdotettu termi englanniksi   

conventions 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuuriset ilmiöt](http://www.yso.fi/onto/yso/p799) 

#### Assosiatiiviset (RT)   

[vieraannuttaminen](http://www.yso.fi/onto/yso/p24255) 

#### Tarkoitusta täsmentävä selite   

Määritelmä vakiintuneet representaation muodot, jotka liittyvät kaunokirjallisen teoksen tyyliin, lajiin, rakenteeseen tai aiheenvalintaan
Selite Kirjallisuuden konventiot ovat yleensä sidoksissa perinteeseen, kuten kirjallisuudenlajeihin ja niiden vakiintuneisiin kielellisiin käytäntöihin (esimerkiksi lyriikassa mitta, riimi, allitteraatio tai säkeenylitys ovat konventioita).
Aika ajoin konventiot koetaan vanhentuneiksi, automatisoituneiksi ja rajoittaviksi, jolloin kirjailijat pyrkivät niitä tietoisesti rikkomaan. 

#### Perustelut ehdotukselle   

KITO-termi. Melindassa käytetty pari kertaa, Artossa ei laisinkaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

En varsinaisesti minkään aineiston kuvailussa, kunhan yritän saada näitä KITO-termejä YSOon. 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [konventiot](http://finto.fi/yse/fi/page/Y505904)

**Comment by mariaforsen** [comment]
Sv. konventioner (konst)

Onko mahdollista pitää hieman laajempana (vrt. Kielitoimiston sanakirja: "vars. kansainvälinen sopimus, valtiosopimus; sovinnainen tapa, käytänne")? Eli että kattaisi konventioita muillakin aloilla kuin kirjallisuudessa, esim. elokuvassa (jossa perusmerkitys lienee samankaltainen).

**Comment by YSA-kokous** [comment]
konventiot (taiteet)

**Comment by amssi** [comment]
Hyvä!
