### ISSUE TITLE
kesuura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5905]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kesuura 

#### Ehdotettu termi ruotsiksi   

cesur 

#### Ehdotettu termi englanniksi   

caesura 

#### Assosiatiiviset (RT)   

[tauot](http://www.yso.fi/onto/yso/p26073) 

#### Tarkoitusta täsmentävä selite   

Määritelmä runosäkeen sisältämä tauko
Selite Kesuuran avulla voidaan aikaansaada rytmisesti tehokkaita vaikutuksia. Mikäli kesuuran edellä on pääpainollinen tavu, kesuuraa sanotaan maskuliiniseksi, jos painoton, feminiiniseksi. Kesuuran kohdalla on usein välimerkki, yleisimmin pilkku. Säkeeseen voi sisältyä yksi tai useampia kesuuroita tai ei ainoatakaan. Kesuurat voivat esiintyä säkeen alkupuolella, keskellä tai lopulla. Mikäli kesuura sijaitsee jokaisessa säkeessä samassa kohdassa, seurauksena on helposti monotonisuus. Kesuurat voivat olla helposti havaittavia tai vähemmän silmiinpistäviä -jälkimmäisiä kutsutaan sekundaarisiksi tauoiksi. Kesuura merkitään ǁ . Esimerkiksi Aaro Hellaakosken runon "Sairaalassa" (Runoja, 1916) säkeissä kesuurat sijoittuvat:

    Mennyt mies.ǁ Mennyt mies. 
    Näinkö sun ǁ loppui ties?    (Tieteen termipankki) 

#### Perustelut ehdotukselle   

KITOn termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

En varsinaisesti minkään aineiston kuvailussa, kunhan yritän saada nämä viimeiset KITO-termit ehdolle YSOon. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

**Ehdottajan nimi:** Anna-Maija Stenlund 
**Ehdottajan organisaatio:** SKS 
**Ehdottajan sähköpostiosoite:** anna-maija.stenlund@finlit.fi **Termiehdotus Fintossa:** [kesuura](http://finto.fi/yse/fi/page/Y505905)

**Comment by jtuohini** [comment]
Ja KT-muodoiksi varmaan synonyymit _sesuura_ ja _tahtilepo_? [https://fi.wiktionary.org/wiki/tahtilepo]
