### ISSUE TITLE
murattikasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5906]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[murattikasvit](http://www.yso.fi/onto/ysa/Y129774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

-> araliakasvit 

#### Perustelut ehdotukselle   

Allärsissa on asiasana araliaväxter; sen yhteydessä kerrotaan että vastaava YSA:n asiasana on murattikasvit, mutta AFO:ssa on asiasana araliakasvit, jonka suppeammat termit ovat huonearalia, liuska-aralia, muratit. Wikipediassakin muratit ovat araliakasvien suku. En ole kasvitieteilijä, mutta ovatko murattikasvit ja araliakasvit synonyymejä? 

#### Ehdottaja   

Anneli Korhonen 

#### Ehdottajan organisaatio   

Hämeen ammattikorkeakoulun kirjasto 

#### Ehdottajan sähköpostiosoite   

anneli.korhonen@hamk.fi

**Comment by PaiviLipsanen** [comment]
YSAssa lienee virhe, ehkä murattikasvit on heimon vanha nimi.

Araliakasvit on heimo - Araliaceae, johon kuuluuvat mm. suvut araliat (Aralia) ja muratit (Hedera) sekä 
ginsengit eli ginsengjuuret (Panax)
https://laji.fi/taxon/MX.41725
https://finto.fi/kassu/fi/page/k17357
https://fi.wikipedia.org/wiki/Araliakasvit

**Comment by mirmaid** [comment]
Täydennetään
