### ISSUE TITLE
fotoniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5907]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fotoniikka 

#### Ehdotettu termi ruotsiksi   

fotonik 

#### Ehdotettu termi englanniksi   

photonics 

#### Vaihtoehtoiset termit ja ilmaisut   

valotiede 

#### Vastaava käsite muussa sanastossa   

LCSH : Photonics 
Wikipedia : Photonics 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Perustelut ehdotukselle   

On tällä nimellä tutkimusalana Suomessakin mm. Itä-Suomen yliopistossa ja Tampereen teknillisessa yliopistossa.
http://www.tut.fi/en/research/research-fields/photonics/index.htm
https://www.uef.fi/en/web/photonics/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Quantum Optics and Nanophotonics 

**Ehdottajan nimi:** Mikko Meriläinen 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mikko.merilainen@uef.fi **Termiehdotus Fintossa:** [fotoniikka](http://finto.fi/yse/fi/page/Y505907)

**Comment by ilona-x** [comment]
Melinda: fotoniikka x 23

https://fi.wikipedia.org/wiki/Fotoniikka
