### ISSUE TITLE
vigilia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5908]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vigilia 

#### Ehdotettu termi englanniksi   

All-night vigil 

#### Ehdotettu termi ruotsiksi   

vigilia 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jumalanpalvelus](http://www.yso.fi/onto/yso/p15215) 

#### Assosiatiiviset (RT)   

[vigiliat](http://www.yso.fi/onto/yso/p16950) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85143323> 
Wikidata : https://www.wikidata.org/wiki/Q14796683 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

Ortodoksisen kirkon ehtoo- ja aamupalveluksesta sekä ensimmäisestä hetkestä koostuva (yleensä iltaisin vietettävä) juhlapalvelus, joka edeltää sunnuntain tai kirkollisen juhlapäivän liturgiaa. 

#### Perustelut ehdotukselle   

Ilmiö tarvitsee oman asiasanan, koska YSAn nykyinen "vigiliat"-asiasana viittaa vain sävellyksiin. Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5632 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [vigilia](http://finto.fi/yse/fi/page/Y505908)

**Comment by mariaforsen** [comment]
Sulkutarkenne tarvitaan varmaan molemmille. 

Sv. vigilia (gudstjänst), vigilior (kompositioner)

**Comment by mirmaid** [comment]
Voiko viitata myös muihin kuin ortodoksiseen vigiliaan?

**Comment by YSA-kokous** [comment]
vigilia (jumalanpalvelus)
