### ISSUE TITLE
organisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5909]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[organisaatio](http://www.yso.fi/onto/ysa/Y97870) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite ja lisätään ohjaustermiksi organisaatiot-käsitteelle. 

#### Perustelut ehdotukselle   

YSAssa ei ole määritelmiä, joilla organisaatiot ja organisaatio -käsitteiden merkitysero selviäisi. Käsitteillä on samat YSA-ryhmät: 71 Hallinto ja 75 Taloustieteet. Kielitoimiston sanakirja antaa organisaatiolle vain yhden merkityksen, mutta mainitsee tosin, että organisaatio tarkoittaa sekä toimintaa että sen tulosta. YSAsta kuitenkin löytyy erikseen organisointi, jonka luulisi kattavan toimintamerkityksen. YSOssa organisaatiot-käsitteen yläkäsite on yhteiskunnalliset järjestelmät, ja organisaatio-käsitteen yläkäsite yhteiskunnalliset objektit. Hierarkisointi ei kuitenkaan sekään selkeytä käsitteiden eroja. Oma tulkintani on, että monikkomuotoinen organisaatiot viittaa enemmän konkretian tasoon, yksittäisiin nimettävissä oleviin organisaatioihin; yksikkömuoto taas viittaa abstraktimmin organisaatioon yleisesti, organisaation ”ideaan”, tai organisaation ”käsitteeseen”. Minusta varsinkin ontologiassa tarve tällaiselle erilliselle yleiskäsitteelle on kyseenalainen: onhan monikkomuotoinen organisaatiot myös yleiskäsite, joka voi viitata yleisellä tasolla organisaatioihin siinä missä yksikkömuotokin.

Melinda-kuvailussa on vaikea löytää eroa käsitteiden välillä, vaan niitä on käytetty systemaattisesti ristiin. Vrt. ”Henkilöstöjohtamisen ja työkuorman hallinnan yhteys organisaatiositoutumiseen suomalaisilla palkansaajilla” [organisaatio] vs. ”Knowledge management : an introduction” [organisaatiot]. Organisaatiot-käsitettä tosin on viimeksi käytetty vuonna 2012, mutta yksiköllinen organisaatio on paljon käytetty edelleen. Tämäkin tuntuu puoltavan sitä, että kahta ei tarvita.

Yhdistäminen selkeyttäisi tilannetta ja helpottaisi niin kuvailijan kuin tiedonhakijankin työtä. Säilyttäisin monikkomuodon pääterminä, koska pidän sitä merkitykseltään laveampana ja monikäyttöisempänä. Yksikkömuoto assosioituu helpommin toimintaan viittaavaksi. Yksi vaihtoehto olisi lisätä organisaatio ohjaustermiksi organisaatiot-käsitteen lisäksi myös organisointi-käsitteelle. 

#### Ehdottaja   

Tuomas Palonen 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

tuomas.palonen@helsinki.fi

**Comment by mirmaid** [comment]
Korjauksena ylläolevaan, monikkomuotoa on käytetty myös v. 2012 jälkeen, aikaisempi tulos johtui virheestä Melindan toiminnassa.

**Comment by mirmaid** [comment]
Yksikköä on käytetty myös viittaamaan jonkin kokonaisuuden organisointitapaan: NATOn organisaatio, asevoimien organisaatio.

Tässä merkityksessä voisi ehkä käyttää myös _organisointi_-termiä, tai sitten ottaa erikseen _organisaatiorakenne_.

**Comment by mariaforsen** [comment]
Organisering=organisointi on ainakin ruotsiksi pahasti päällekkäinen "organisaatio"-termin (toimintana) kanssa. Nykytilanne aiheuttaa myös hankaluuksia käyttäjille, kannatan siispä yhdistämistä.

**Comment by satuniininen** [comment]
Kannatan myös yhdistämistä enkä välttämättä kokisi ongelmallisena monikkomuodon käyttöä myöskään näissä organisaatiorakenteeseen viittaavissa tapauksissa. Olettaisin että niissä kuitenkin käsitellään rakennetta jotenkin organisaation itsensä ja sen toiminnan kautta, jolloin toimintaa ja sen tulosta on joka tapauksessa vaikea erottaa toisistaa.
