### ISSUE TITLE
rahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5910]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rahat](http://www.yso.fi/onto/ysa/Y98439) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

On ongelmallinen yksikkö/monikko-tapaus. Sanastossa on erikseen raha, sekä kolikot>metallirahat ja setelit>setelirahat, myös valuutta yms. Ruotsiksi raha+rahat=pengar, mutta Allärsissa rahat =mynt/myntenheter. 

#### Ehdotettu muutos   

-Päätermin muutos: rahat KÄYTÄ rahayksiköt
tai 
-yhdistäminen: rahat KÄYTÄ raha / raha KÄYTÄ rahat 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by ilona-x** [comment]
Jos yhdistetään, niin yksiköllinen muoto tuntuisi paremmalta eli rahat KÄYTÄ raha.
Melinda:
rahat 368
raha 932

**Comment by mirmaid** [comment]
Monikkoa on käytetty usein kun on kyse rahalöydöistä (metallirahat ei ehkä niin luonteva tai ei tule mieleen), tai valuutoista, joka puolestaan vähän hankalasti yksikkömuotoinen.

**Comment by ilona-x** [comment]
Ei varmaan ratkaise kaikkia ongelmia, mutta voisiko muuttaa metallirahat KÄYTÄ kolikot ja samoin setelirahat KÄYTÄ setelit

Kielitoimiston sanakirja:
metalliraha = metallinen raha; paperirahan vastakohta
kolikko = metalliraha, lantti. 50 sentin kolikko. Kuparikolikko. 
paperiraha = seteli(raha)
seteli = 1. paperiraha (vars. konkreettisena esineenä). Kahdenkymmenen euron seteli. Maksoi koko kauppasumman seteleinä. 
2. maksu-, alennus- yms. lipukkeista, voucher. Taksiseteli. Lounasseteli.
