### ISSUE TITLE
tsifteteli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5912]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tsifteteli 

#### Ehdotettu termi englanniksi   

tsifteteli 

#### Vaihtoehtoiset termit ja ilmaisut   

çiftetelli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansantanssit (tanssit)](http://www.yso.fi/onto/yso/p18196) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q1422125 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1112743 

#### Tarkoitusta täsmentävä selite   

Anatolialais-balkanilainen kansantanssi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [tsifteteli](http://finto.fi/yse/fi/page/Y505912)

**Comment by mariaforsen** [comment]
Sv. tsifteteli
