### ISSUE TITLE
verenpainetauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5913]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verenpainetauti](http://www.yso.fi/onto/ysa/Y100146) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT hypertonia
Onko yhdistettävissä hypertension kanssa? 

#### Perustelut ehdotukselle   

YSAssa 
-verenpainetauti KT kohonnut verenpaine (Allärs: hypertoni)
-hypertensio KT kohonnut verenpaine, huomautus: Tarkoittaa kohonnutta verenpainetta (Allärs: hypertension)

MESHissä: verenpainetauti KT hypertensio, hypertonia, kohonnut verenpaine
TEROssa: kohonnut verenpaine KT hypertensio, hypertonia, verenpainetauti

Ainakin ruotsiksi hypertension ja hypertoni ovat synonyymejä (eli eivät saisi olla molemmat päätermeinä). Jos jopa lääketieteen auktoriteetit niputtavat nämä kohonneet verenpaineet yhteen niin varmaan yleispuolellakin riittäisi yksi? Hypotensio=hypotension, eli alhainen verenpaine on erikseen mukana. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by satuniininen** [comment]
Varovainen kannatus yhdistämiselle. Myös englanniksi näitä käytetään toistensa synonyymeinä.

**Comment by mirmaid** [comment]
Tämä varmaan tulee pöydälle niin monta kertaa että yhdistetään :sweat_smile:. Varmaan pitäisi ottaa sitten päätermiksi _kohonnut verenpaine_ kuten TEROssa? 
Lääketieteen termit: verenpainetauti par. kohonnut verenpaine, systolinen hypertensio, keuhkoverenpainetauti, raskaushypertensio.
kohonnut verenpaine: hypertensio | tila jossa verenpaine on jatkuvasti normaalia korkeampi

**Comment by jarmosaarikko** [comment]
Tässä lähdeviite termitietueeseen:
sisätautien erikoislääkäri Pertti Mustajoki: Kohonnut verenpaine (verenpainetauti).
Lääkärikirja Duodecim, 2.10.2018.
http://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_teos=&p_artikkeli=dlk00034
