### ISSUE TITLE
reflektanssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5914]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

reflektanssi 

#### Ehdotettu termi englanniksi   

reflectance 

#### Vaihtoehtoiset termit ja ilmaisut   

heijastuskyky 
heijastuvuus 
 

#### Vastaava käsite muussa sanastossa   

LSCH : <Reflectance, http://id.loc.gov/authorities/subjects/sh85112204.html> 
Tieteen termipankki : <reflektanssi, http://tieteentermipankki.fi/wiki/Fysiikka:reflektanssi> 

#### Tarkoitusta täsmentävä selite   

Tieteen termipankki: Esim. valon tai äänen heijastuvuus jostakin pinnasta. 

#### Perustelut ehdotukselle   

Tarvitaan väitöskirjan kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: Leaf optical properties and dynamics of photosynthetic activity (2018) https://helda.helsinki.fi/handle/10138/232321 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [reflektanssi](http://finto.fi/yse/fi/page/Y505914)

**Comment by mariaforsen** [comment]
Sv. reflektans ET reflektionsfaktor, reflexionsfaktor

**Comment by mirmaid** [comment]
Tämä varmaan ei ole ihan sama kuin albedo, mutta löytyisikö jostain selventävää määritelmää näistä suhteessa toisiinsa?

**Comment by ilona-x** [comment]
Tieteen termipankin määritelmä albedolle:
http://tieteentermipankki.fi/wiki/Geofysiikka:albedo
albedo
pinnasta heijastuneen säteilyn määrän suhde saapuvan säteilyn määrään

**Comment by mirmaid** [comment]
Hmm, kyllä nämä vaan synonyymeiltä vaikuttaa...

**Comment by mirmaid** [comment]
Reflektanssi on se osa tulevasta säteilystä, joka heijastuu kohteesta. Kun kohde heijastaa kaiken tulevan säteilyn, reflektanssi on 1 (100%). http://wwwi4.ymparisto.fi/i4/fin/tuotteet/Kaukokartoituksen_tietopaketti_(2004).pdf

Täysin valoa heijastava pinta on valkoinen, ja sen albedo on 1,0 tai 100 %. https://fi.wikipedia.org/wiki/Albedo

While bi-hemispherical reflectance is calculated for a single angle of incidence (i.e., for a given position of the Sun), albedo is the directional integration of reflectance over all solar angles in a given period. https://en.wikipedia.org/wiki/Albedo

:sweat: :persevere:
