### ISSUE TITLE
patologiskt samlande

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5918]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

patologiskt samlande 

#### Ehdotettu termi englanniksi   

hoarding 

#### Vastaava käsite muussa sanastossa   

hoarding; hoarding disorder (LCSH) :  

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologi](http://www.yso.fi/onto/yso/p26543) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Liane Moriarty: Andras vänner (roman) 

#### Perustelut ehdotukselle   

Ett tillstånd som 2-6% av befolkningen lider av, som bibliotekskunder kan vilja söka information eller skönlitteratur om. Diagnosen kom 2013. 

**Ehdottajan nimi:** Louise Agnesdotter 
**Ehdottajan sähköpostiosoite:** turbanpost@gmail.com **Termiehdotus Fintossa:** [patologiskt samlande](http://finto.fi/yse/fi/page/Y505918)

**Comment by mariaforsen** [comment]
YSA: hamstraus. https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk01100
Sv. även samlarsjuka, samlarsyndrom, disposofobi

**Comment by YSA-kokous** [comment]
KÄ hamstraus
