### ISSUE TITLE
årtal (1800-talet, 1890-talet, 2000-talet, etc.)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5919]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

årtal (1800-talet, 1890-talet, 2000-talet, etc.) 

#### Ehdotettu termi suomeksi   

vuosiluvut (1800-luku, 1890-luku, 2000-luku, jne.) 

#### Perustelut ehdotukselle   

Ifråga om äldre material är det ibland svårt att ange en exakt datering. Ifråga om t.ex. bilder kunde det vara fint att kunna söka fram t.ex alla foton från 1890-talet för att kunna se gemensamma drag, olikheter, förändringar i teknik mm., det här även om materialet skulle ha en exakt datering 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Bilder, föremål 

**Ehdottajan nimi:** Johanna Lindblom 
**Ehdottajan sähköpostiosoite:** johanna.m.lindblom@abo.fi **Termiehdotus Fintossa:** [årtal (1800-talet, 1890-talet, 2000-talet, etc.)](http://finto.fi/yse/fi/page/Y505919)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5556
