### ISSUE TITLE
inkamusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5920]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[inkamusiikki](http://www.yso.fi/onto/ysa/Y214504) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

poistetaan termiä 

#### Perustelut ehdotukselle   

termin nykyinen määritelmä: "Etelä-Amerikan intiaanien ja espanjalaisten perinnemusiikkien sulautumana syntynyt musiikin laji etupäässä Andien alueella. Inkamusiikille tyypillisiä soittimia ovat erilaiset panhuilut, kitarat ja harput. Inkamusiikki on tyylillisesti usein populaari- ja perinnemusiikin sekoitusta."

Grovessa "Inca Music" on  määritelty näin: "Music of the Pre-Columbian culture of the Central Andean area of South America". Groven määritelmää vastaa tuo LCSH:n termi: http://id.loc.gov/authorities/subjects/sh85064729 

Groven määritelmää vastaava menisi meillä "perinnemusiikki" + "inkat" ja tuo meidän "inkamusiikki" tarkoittaisi kaupallisempaa musiikkia, kansanmusiikin ja populaarimusiikin sekoitusta, samalla tavoin kuin "mustalaismusiikki".

inkamusiikki-termin sijasta voisi kuvailla termeillä "maailmanmusiikki" ja [maantieteellinen termi/valtion tai alueen nimi]

Ja terveisiä vielä YSOn ylläpidosta, jos ei päädytä termin poistamiseen: termin LT:ssa ja määritemässä+huomautuksessa on ristiriita: LT perinnemusiikki, mutta huomautuksessa sanotaan, ettei saa kuvailla perinnemusiikkia. 

#### Ehdottaja   

Katerina Sornova 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

katerina.sornova@helsinki.fi

**Comment by jtuohini** [comment]
Molempi parempi – tai pahempi:

**inkamusiikki**
LT  maailmanmusiikki

terminä mahdollistaisi sellaisen aineiston kuvailun, joka käsittelee tätä nimenomaista maailmanmusiikin lajia, olivatpa esittäjät sitten Saksassa tai Suomessa. Pelkkä asiasana **maailmanmusiikki** + maantieteellinen lisämääre ei ehkä tekisi riittäävää eroa muihin maailmanmusiikin lajeihin? Vai olisiko edes tarve?

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: säilytetään termi, LT maailmanmusiikki + viihdemusiikki
