### ISSUE TITLE
aerogeelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5921]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aerogeelit 

#### Ehdotettu termi englanniksi   

aerogels 

#### Ehdotettu yläkäsite YSOssa (LT)   

[geelit](http://www.yso.fi/onto/yso/p12973) 

#### Vastaava käsite muussa sanastossa   

LSCH : <Aerogels, http://id.loc.gov/authorities/subjects/sh97003177.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Tarkoitusta täsmentävä selite   

Aerogeelit ovat erittäin huokoisia ja kevyitä kiinteitä materiaaleja, jotka valmistetaan korvaamalla geelin nestefaasi ilmalla siten, että kolmiulotteinen polymeeriverkosto säilyy myös kuivassa materiaalissa.
https://helda.helsinki.fi/handle/10138/232202 

#### Perustelut ehdotukselle   

Tarvitaan väitöskirjan kuvailuun.
Melinda - sanahaku: aeroge? -> 177 osumaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: Novel functional materials from upgraded biopolymers : polysaccharide aerogels, https://helda.helsinki.fi/handle/10138/232202 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [aerogeelit](http://finto.fi/yse/fi/page/Y505921)

**Comment by mariaforsen** [comment]
Sv. aerogeler ET aerogel
