### ISSUE TITLE
Xiben kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5922]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Xiben kieli 

#### Ehdotettu termi ruotsiksi   

Sipe (språk) 

#### Ehdotettu termi englanniksi   

Xibe language 

#### Vaihtoehtoiset termit ja ilmaisut   

Sibe, Sibin, Sibo, Xibo, Hibe 

#### Vastaava käsite muussa sanastossa   

Xiben kieli (Wikipedia) : https://fi.wikipedia.org/wiki/Xiben_kieli 

#### Perustelut ehdotukselle   

Uhanalainen tunguusikieli
Kielen nimi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2655215 (tämä jo kuvailtu mutta tarvitaan myös jatkossa) 

**Ehdottajan nimi:** Eeva Henriksson 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** eeva.henriksson@helsinki.fi **Termiehdotus Fintossa:** [Xiben kieli](http://finto.fi/yse/fi/page/Y505922)

**Comment by tpalonen** [comment]
Pitäisi kirjoittaa pienellä alkukirjaimella.

**Comment by jtuohini** [comment]
Jaakko Anhava (Maailman kielet ja kielikunnat, s. 147): "Xibo e. sibo on mantšun viimeinen elävä murre". Onko Anhava kuitenkin tärkeämpi auktoriteetti asiasanan muodon valinnassa kuin suomenkielinen Wikipedia?

**Comment by mirmaid** [comment]
Myös Lexvossa Xiben kieli http://finto.fi/lexvo/fi/page/sjo. Xibon kieli tai sibon kieli ei tuo viitteitä Googlella.

**Comment by mariaforsen** [comment]
Sv. sibe (språk) ET xibo, xibe 
http://spraktidningen.se/artiklar/2013/09/kejsarens-glomda-sprak
