### ISSUE TITLE
rikostutkijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5924]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rikostutkijat 

#### Vaihtoehtoiset termit ja ilmaisut   

rikosetsivät? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

#### Perustelut ehdotukselle   

Ovatko rikosetsivät ja rikostutkijat sama asia? Melindasta löytyy tällä hetkellä 160 tietuetta (kaikki kaunokirjallisuutta), joissa on käytetty asiasanaa rikostutkijat. Sitä ei kuitenkaan löydy Fintosta. Saisiko rikostutkijat Fintoon uudeksi käsitteeksi tai viittaustermiksi rikosetsiviin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Dekkarit 

**Ehdottajan nimi:** Katri Syrjälä 
**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto 
**Ehdottajan sähköpostiosoite:** katri.syrjala@tampere.fi **Termiehdotus Fintossa:** [rikostutkijat](http://finto.fi/yse/fi/page/Y505924)

**Comment by mariaforsen** [comment]
Sv. brottsutredare ANVÄND detektiver? detektiv="civilklädd polisman eller privatperson som utför undersökningar för att utreda brottmål"

**Comment by LeKorsu** [comment]
ohjaustermiksi: rikostutkijat KÄ rikosetsivät (on jo ysassa)
