### ISSUE TITLE
ongelmalapset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5925]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ongelmalapset](http://www.yso.fi/onto/ysa/Y97795) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan termin poistoa sanastosta tai sen muuttamista ohjaustermiksi. Ongelmalapset-termin sijaan voitaisiin esimerkiksi käyttää jo YSA:sta löytyvää termiä erityislapset. 

#### Perustelut ehdotukselle   

Termi on vanhanaikainen ja leimaava. 

#### Ehdottaja   

Petra Peltokangas 

#### Ehdottajan organisaatio   

BTJ Finland 

#### Ehdottajan sähköpostiosoite   

petra.peltokangas@btj.fi

**Comment by jtuohini** [comment]
Eikö "erityislapset" ole epätarkka ilmaisu? Täysin maallikkona "ongelmalapset" (mahdollisesta leimaavuudestaan huolimatta) tuntuu viittaavan ilmiöön, joka on ymmärrettävissä heti sanan nähdessään, kun taas "erityislapset" voi viitata yhtä hyvin poikkeuksellisen lahjakkaisiin (ongelmattomiin) lapsiin kuin vaikkapa psyykkistä tai jotakin muuta hoitoa vaativiin lapsiin, ml. käytöshäiriöiset.

**Comment by petrapel** [comment]
Mitä tarkoitetaan käsitteellä ongelmalapset? Käsite itsessään on epämääräinen, eikä kerro, minkälaisesta lapsen “ongelmasta” on kyse. Ongelmalapset-termi on vanhanaikaista sanastoa, eikä kuulu nykykieleen. Sen sijaan erityispedagogiikan alalla puhutaan nykypäivänä lapsista, joilla on erityisen tuen tarve, erityislapsista tai haasteellisesti käyttäytyvistä lapsista. Haasteellisen käyttäytymisen syyt voivat olla moninaisia, eivätkä ne välttämättä ole lapsesta itsestään johtuvia. Nykyaikaisen ajattelutavan mukaan ei ole olemassa ongelmalapsia, vaan tulisi ennemmin puhua ongelmakäyttäytymisestä.

Erityislapset on vakiintunut käsite erityispedagogiikan alalla, ja sillä tarkoitetaan lapsia, joilla on jokin erityisen tuen tarve. Erityislapset-käsite löytyy jo YSA:sta (Allärsissa barn med särskilda behov), ja sen lähikäsitteitä ovat erityinen tuki, erityiskasvatus ja erityispäivähoito.

**Comment by SamuVirokannas** [comment]
Lapseni koulussa on erityislapsia, siis lapsia, joilla on erityisen tuen tarve - mikä on toki varsin tavallista. Kyllä minä kohottelisin kulmakarvojani, jos esim. opettaja puhuisi sen sijaan ongelmalapsista. 

Erityislapset on toki jossain määrin epätarkka ilmaisu, mutta se johtuu siitä, että käsite kattaa niin suuren kirjon tarkemmin määriteltäviä ilmiöitä. Pikainen Google-hakukin tukee termin vaihtoa: ongelmalapset-sanaa käytetään ensinnäkin näistä kahdesta nykyisin jo reilusti vähemmän, ja lisäksi se esiintyy pikemminkin maallikoiden keskustelupalstoilla, kun taas asiantuntijapuheenvuoroissa ja virallisemmissa yhteyksissä sen sijaan puhutaan erityislapsista.

**Comment by mirmaid** [comment]
Löytyy myös _ongelmanuoret_ ja _ongelmaperheet_

**Comment by AuHo22** [comment]
Fennicassa ei _ongelmaperheet_ ole käytetty kertaakaan, ja ongelmanuoret -termi voitaisiin ehkä yhtä hyvin korvata vastineiksi erityisnuoret, murrosikä, käyttäytymishäiriöt jne.

**Comment by mariaforsen** [comment]
Jos ongelmalapset poistetaan niin pitäisi varmaan ongelmanuoretkin poistaa. Svenska ämnesordissa problembarn, mutta kritiikkiä kyllä esiintyy, esim. https://muep.mau.se/bitstream/handle/2043/19040/Examensarbete%20f%C3%B6rskoll%C3%A4rarutbildningen.pdf?sequence=2&isAllowed=y

**Comment by ilona-x** [comment]
FinMeSH: 
ongelmakäyttäytyminen http://finto.fi/mesh/fi/page/D000066553
käytöshäiriöt (KT käyttäytymishäiriöt, käyttäytymisongelmat) http://finto.fi/mesh/fi/page/D019955

**Comment by satuniininen** [comment]
Jonkin verran puhutaan myös moniongelmaisista nuorista/perheistä/asiakkaista jne. (Googlessa yli 36 000 osumaa). YSAan otettu muodossa _moniongelmaisuus._

_Ongelmakäyttäyminen_ olisi kuitenkin neutraalimpi ja vähemmän osoitteleva.

**Comment by mirmaid** [comment]
_Ongelmakäyttäytymistä_ mietin itsekin ja se olisi helpommin lisättävissä _ongelmalapset/-nuoret_ -termien tilalle (ei kyllä ehkä _ongelmaperheisiin_) kuin _käyttäytymishäiriöt_, mutta nämä kaksi olisivat kyllä sitten kovin päällekkäisiä.

Lääketieteen termit: käytöshäiriö: _(lasten ja nuorten) toistuva ja itsepintainen uhmakas, epäsosiaalinen tai aggressiivinen käyttäytyminen, joka rikkoo ikätason mukaisia käytösnormeja_

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/971

**Comment by YSA-kokous** [comment]
Poistetaan ongelmalapset, ongelmanuoret ja ongelmaperheet. Tutkitaan vielä tarvitaanko/löytyykö sopiva korvaava termi.

**Comment by mirmaid** [comment]
_Ongelmakäyttäytyminen_ otettu sanastoon.

**Comment by jtuohini** [comment]
Hyvä, mutta kuka käy lisäämässä taannehtivasti sen niihin tietueisiin, jotka käsittelivät esimerkiksi nuorten ongelmakäyttäytymistä ja joka aiemmin on ilmaisu asiasanalla "ongelmanuoret"? Ja tämä asia siis koskee siis kaikkia erilaisia tapauksia, joissa asiasana poistuu tai asiasanojen ST–LT-suhde muuttuu radikaalisti vaikkapa RT:ksi. Tämä on mielestäni asia, joka pitää huomioida YSAsta YSOon -konversiossa, ei siis vain tämän yksittäisen asiasanan osalta vaan yleisenä periaatteena.
