### ISSUE TITLE
kuulutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5927]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuulutukset](http://www.yso.fi/onto/ysa/Y112366) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko?
-kuulutus/kuulutukset (avioliitto) = lysning/ar
-kuulutukset (julkiset tms.) = kungörelser ..tai KÄYTÄ julistukset ?
-kuulutukset (kaiuttimet tms.?) = (högtalar)utrop

#### Perustelut ehdotukselle   

Käytetty eri merkityksissä Melindassa:
-Sound systems : design and optimization : modern techniques and tools for sound system design and alignment / Bob McCarthy. (sv. utrop, EI kungörelser, lysningar)
-Akaan seurakunnan kuulutettujen luettelot vuosilta 1810-1830. (sv. lysningar)
-Virallisen lehden kuulutusopas / [laatijat: Arja-Hannele Lilja, Raija Kääpä]. (sv. kungörelser)

Kielitoimiston sanakirja:
-1. kuuluttaminen. Tulosten kuulutus.
2. julkinen tiedoksianto. Etsintäkuulutus. Kuulutus pakkohuutokaupasta. Julkaista kuulutus sanomalehdessä.
Erik. aik. lakisääteisestä avioliittoaikomuksen julkisesta tiedoksiannosta avioliiton esteettömyyden toteamiseksi. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Mahdollinen myös: _avioliittokuulutukset_. Toisaalta historiallisesti kirkoissa on kuulutettu muutakin, ovatko kaikki "lysningar"?

**Comment by mariaforsen** [comment]
Ei, lysning on nimenomaan vain avioliittokuulutus.

**Comment by mirmaid** [comment]
avioliittokuulutukset KT kuulutukset (avioliitto)

Melindassa on aineistoa myös muista _kirkonkuulutuksista_, joten ehkä tämä termi tarvittaisiin lisäksi?

_Kungörelser_ voisi olla _julkiset kuulutukset_, mutta termi on harmillisen epämääräinen ja menisi mahdollisesti sekaisin muiden merkitysten kanssa. Toisaalta nämä myös oikeastaan ovat samaa asiaa kuin kirkonkuulutukset, tiedottamisen tapa vain on muuttunut. Auttaisiko jos olisi tarkenteella (hallinto)? https://fi.wikipedia.org/wiki/Kuulutus

Viimeisin merkitys voisi ehkä olla kuulutus/kuuluttaminen/kuulutukset (äänitekniikka)

**Comment by YSA-kokous** [comment]
viralliset kuulutukset KT julkiset kuulutukset, viranomaiskuulutukset
avioliittokuulutukset KT kuulutukset (avioliitto)
korjataan viitteet ja päätetään jäljellejäävien osalta mikä on sopivin muoto

**Comment by jarmosaarikko** [comment]
Kannatan Sadun ehdotusta "**äänikuulutukset**"  kaiutinjärjestelmistä annettaville ilmoituksille. Tämä kattaa kaikki busseissa ja junissa sekä asemilla ja urheilu yms. tilaisuuksissa annettuja ilmoituksia käsittelevät aineistot.  
Kattaisiko tämä myös "**hätäkuulutukset**", jotka ovat esimerkiksi viranomaisten väestöhälyttimien kautta annettuja ilmoituksia?

**Comment by mariaforsen** [comment]
Äänikuulutus sanana näyttää olevan hyvin vähän käytetty. Ruotsiksi voisi siinä tapauksessa kuitenkin olla mahdollista laittaa ljudutrop (myös hyvin vähän käytetty).

**Comment by satuniininen** [comment]
Entä _kuulutukset (äänitiedotteet)_ tai _kuulutukset (äänentoisto)_

**Comment by YSA-kokous** [comment]
äänikuulutukset
