### ISSUE TITLE
elokuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5928]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elokuva](http://www.yso.fi/onto/ysa/Y94995) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "elokuvataide" 

#### Perustelut ehdotukselle   

Nykyistä asiasanaa "elokuva" on käytetty huomattavan paljon (suorastaan mekaanisesti) asiasanan "elokuvat" rinnalla, arvattavasti siksi, että kuvailijat eivät ole hahmottaneet sen viittaavan nimenomaan taidemuotoon eikä kyseisen taidemuodon piirissä luotuihin teoksiin, vaikka asiasanan KT-muotona on "elokuvataide". Muoto "elokuvataide" ei jättäisi epäselväksi, mihin asiasana täsmällisesti viittaa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: elokuva 2. elokuvataide, -teollisuus, -ala. _Elokuvan alkuajat, uusi aalto. Elokuvan ilmaisukeinot. Chaplin ja Keaton, elokuvan ylittämättömät koomikot._ 

Suuressa osassa käyttötapauksista elokuvataide olisi varmaankin ihan ok, mutta termiä on käytetty laajemmin kuten Kielitoimiston sanakirjakin määrittelee. Toki YSAssa on jo runsaasti muutakin termistöä, esim. _elokuva-ala, elokuvateollisuus_. Korjattaessa pitäisi kuitenkin luultavasti tehdä _elokuva_ > _elokuvataide + elokuvat_.
