### ISSUE TITLE
rytmimoodit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5929]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rytmimoodit 

#### Ehdotettu termi englanniksi   

rhythmic modes 

#### Vaihtoehtoiset termit ja ilmaisut   

modaalirytmiikka 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rytmiikka](http://www.yso.fi/onto/yso/p25262) 

#### Tarkoitusta täsmentävä selite   

Groven mukaan "a medieval concept of rhythm in which the value and relative duration of each note is determined by its position within a larger rhythmic series, or mode, consisting of a patterned succession of long and short values" [https://doi.org/10.1093/gmo/9781561592630.article.23337]
Ks. myös Musiikinhistoriaa verkossa -sivusto [http://muhi.siba.fi/xwiki/bin/view/Muhi/View?id=kesk_arsantiqua3] 

#### Perustelut ehdotukselle   

Asiasanan "moodit" jakamisen yhteydessä vastaan tuli tarve erottaa kaksi musiikillista moodia, jotka kumpikin oli merkitty MUSA-asiasanastossa asiasanan "moodit" määritelmään. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [rytmimoodit](http://finto.fi/yse/fi/page/Y505929)

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Sv. modalrytmik ET rytmmodus, modus (musik)
