### ISSUE TITLE
Tuovila (Mustasaari)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5930]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Tuovila (Mustasaari) 

#### Ehdotettu termi ruotsiksi   

Toby (Korsholm) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Tuovila 

#### Perustelut ehdotukselle   

Kylässä sijaitsee mm. Tuovilan museosilta http://www.yso.fi/onto/ysa/Y505645 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ysa 

**Ehdottajan nimi:** Jarmo Saarikko 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** jarmo.saarikko@helsinki.fi **Termiehdotus Fintossa:** [Tuovila (Mustasaari)](http://finto.fi/yse/fi/page/Y505930)

**Comment by satuniininen** [comment]
Tuovilan museosiltaa käytetty Melindassa kerran, maantieteellisenä asiasanana Mustasaari.

**Comment by ilona-x** [comment]
Mustasaari - Tuovila lisätty YSA:an
