### ISSUE TITLE
hevosmatkailu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5931]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hevosmatkailu 

#### Perustelut ehdotukselle   

Hevosmatkailussa hevosta käytetään osana matkailutuotetta: hevonen on olennainen osa matkailuaktiviteettia ja matkailuelämyksen tuottamista. Hevosmatkailun ohjelmapalvelu tuotetaan luonnossa ja/tai rakennetussa ympäristössä ympäristövastuullisesti. Hevosmatkailu voi olla monelle seutukunnalle vetovoimatekijä ja kuntien näkyvyyden ja tunnettuuden lisääjä. 
http://www.hippolis.fi/hevosetjakunta/hevosmatkailu/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.visitfinland.fi/studies/kansallinen-hevosmatkailututkimus-2009/ 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [hevosmatkailu](http://finto.fi/yse/fi/page/Y505931)

**Comment by mariaforsen** [comment]
Sv. hästturism
