### ISSUE TITLE
ketjutanssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5932]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ketjutanssit 

#### Ehdotettu termi englanniksi   

chain dances 

#### Ehdotettu termi ruotsiksi   

kedjedanser 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssit](http://www.yso.fi/onto/yso/p3046) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

Sanastossa ei ole kyseisille tansseille ennestään sopivaa asiasanaa. 

#### Tarkoitusta täsmentävä selite   

(Nimityksistä ks. esim. http://tanssi.dy.fi/Tanssiohjeet – huomaa, että ketju- ja piiritanssit eritelty toisin kuin Wikipediassa!) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.628734 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [ketjutanssit](http://finto.fi/yse/fi/page/Y505932)

**Comment by SamuVirokannas** [comment]
Kannatan: kätevä yleistermi ketjumuodossa tanssittaville tansseille riippumatta niiden historiallisesta tai kulttuurisesta kontekstista. 

Käytännössä ketju voi olla myös suljettu piiri, mutta tähän ei varmaankaan tarvitse sanastossa ottaa kantaa. 

Periaatteessa engl. termi voisi olla myös line dance, kuten LoC:n etnografisessa sanastossa http://id.loc.gov/vocabulary/ethnographicTerms/afset010579.html, "A dance without partners executed in either a straight or curving line, or a semi-circle". Se voi kuitenkin liian helposti sekaantua country-rivitanssiin, joten chain dances on parempi. (Esim. Färsaarten perinteistä tanssia kutustaan englanniksi yleensä nimellä Faroese chain dance, ei .F... line dance.) 

Jaakon viittaamassa historiallisten tanssien wikissä tanssi.dy.fi tanssit luokitellaan ensisijaisesti historiallisen tyyppinsä tai alkuperäislähteidensä mukaan ja vain toissijaisesti muodostelman mukaan.

**Comment by mariaforsen** [comment]
Sv. KT långdanser?

**Comment by mirmaid** [comment]
2 viitettä Melindassa.
