### ISSUE TITLE
launeddas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5933]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

launeddas 

#### Ehdotettu termi englanniksi   

launeddas 

#### Ehdotettu termi ruotsiksi   

launedda 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansansoittimet](http://www.yso.fi/onto/yso/p7134) 
[lehdykkäsoittimet](http://www.yso.fi/onto/yso/p29882) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh99000730> 
Seko : <http://urn.fi/urn:nbn:fi:au:seko:00584> 

#### Tarkoitusta täsmentävä selite   

"Launedda (även kallad trippelklarinett eller trippelpipa) är ett folkligt träblåsinstrument från södra Sardinien, möjligen av asiatiskt ursprung." [https://sv.wikipedia.org/wiki/Launedda]

"Triple idioglot clarinet of southern Sardinia. It is of ancient origin and the etymology of its name is uncertain. It has cane pipes of different lengths: the tumbu (longest), in several sections, is the bass drone, sounding the tonic; the mancosa (medium) gives the middle register and is bound to the tumbu at an angle; the separate mancosedda (smallest) plays the highest notes." [https://doi.org/10.1093/gmo/9781561592630.article.L2255667] 

#### Perustelut ehdotukselle   

Kyseistä soitinta käsittelevää kirjallisuutta on julkaistu useampikin nimeke, mutta niiden kuvailemiseksi ei sanastossa ole vielä asianmukaista asiasanaa (löytyy jo Sekosta). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.628734 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [launeddas](http://finto.fi/yse/fi/page/Y505933)

**Comment by jtuohini** [comment]
Muusa-ryhmän päätös 28.3.2018: kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Sv. launeddas ET launedda
