### ISSUE TITLE
Amarna (Egypti)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5934]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Amarna (Egypti) 

#### Ehdotettu termi ruotsiksi   

El-Amarna (Egypten) 

#### Ehdotettu termi englanniksi   

Amarna (Egypt) 

#### Vaihtoehtoiset termit ja ilmaisut   

Akhetatena (Egypti) 
Akhetatona (Egypti) 
El-Amarnaa (Egypti) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh86003874> 
Wikidata : https://www.wikidata.org/wiki/Q5736 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2881958 ja useita muita 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [Amarna (Egypti)](http://finto.fi/yse/fi/page/Y505934)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Akhetaten

**Comment by mirmaid** [comment]
Miten auktorisoidaan (muinaiskaupunki/nykyinen kylä/arkeologinen kohde).

**Comment by mirmaid** [comment]
Amarna is the modern Arabic name for the site of the ancient Egyptian city of Akhetaten, capital of the country under the reign of Akhenaten (1353-1336 BCE). The site is officially known as Tell el-Amarna, so-named for the Beni Amran tribe who were living in the area when it was discovered. https://www.ancient.eu/Amarna/

Toisaalta käytetään paikan nimen mukaisia ilmauksia amarna letters/amarna-kirjeet, amarna art, amarna period https://en.wikipedia.org/wiki/Amarna_Period / amarna-kausi https://fi.wikipedia.org/wiki/Amarna-kausi.

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Amaran. Käytetyin termi (ks. esim. Wikipedian eri kielet, joissa suomi lähes ainoa poikkeus). Ohjaustermeiksi Akhetaten, El-Amarna, Akhetaton.
