### ISSUE TITLE
kaunis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5936]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kaunis](http://www.yso.fi/onto/ysa/Y106355) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan itsenäisenä asiasanana ja vastaavasti lisätään KT-muodoksi asiasanalle "kauneus". 

#### Perustelut ehdotukselle   

YSAssa nyt olevat asiasanat "kauneus" ja "kaunis" ovat kumpikin aiheryhmässä 02 ilman minkäänlaista määritelmää tai käyttöohjetta. Kumpikin käsite liittyy estetiikkaan, mutta kuvastavasti suomenkielinen estetiikkaa käsittelevä Wikipedia-artikkeli ei kertaakaan käytä sanaa "kaunis" substantiivina, vaan aina sanaa "kauneus". 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Ruotsiksikin vastine on ollut "det sköna", olisi hyvä poistaa. Vastaavia olisi tosin siinä tapauksessa muitakin: paha (pahuus), pyhä (pyhyys), hyvä (hyvyys), ylevä (>ylevyys?) jne.

Myös standardi suosittelee ettei käytetä tällaisia, ks. ISO 25964-1 6.3.2 Adjectives (ja ruotsin osalta myös 6.3.5.1)

**Comment by YSA-kokous** [comment]
kaunis KÄ kauneus
