### ISSUE TITLE
kansantalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5938]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansantalous](http://www.yso.fi/onto/ysa/Y95877) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: yhteiskuntatalous ? 

#### Perustelut ehdotukselle   

Onko tämä ok (eli ettei tarvitse lisätä erillisenä terminä)?

Allärs: samhällsekonomi=kansantalous

Kielitoimiston sanakirja: kansantalous=maan julkisen talouden ja yksityisten talousyksiköiden toiminta kokonaisuutena; myös kansantaloustieteestä. 

Käytetty Melindassa. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Joissakin vanhemmissa oppikirjoissa sanaa on käytetty ilmeisesti kattoterminä kansantaloudelle ja yhteiskuntatiedolle (?). Tierakennushankkeissa sanaa on käytetty paljon kustannuslaskelmissa.
