### ISSUE TITLE
erfaren

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5939]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

erfaren 

#### Ehdotettu termi englanniksi   

experienced 

#### Ehdotettu termi suomeksi   

kokenut 

#### Vaihtoehtoiset termit ja ilmaisut   

förfaren, ärrad 

#### Tarkoitusta täsmentävä selite   

som har långvarigt utövande av ngn (praktisk) verksamhet bakom sig vanl. på ngt spec. område (Nationalencyklopedin) 

#### Perustelut ehdotukselle   

Erfaren är en egenskap. 
Erfarenheter däremot (som finns i tesaurusen) är händelser man varit med om. Inte samma sak tycker jag. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pro gradu: Styrelsesammansättningar - Har styrelsemedlemmarnas ålder och erfarenhet ett samband med bolagens innovation? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofi](http://www.yso.fi/onto/yso/p26545) 
[55 Psykologi](http://www.yso.fi/onto/yso/p26543) 

**Ehdottajan nimi:** Anne Granberg 
**Ehdottajan sähköpostiosoite:** anne.granberg@hanken.fi **Termiehdotus Fintossa:** [erfaren](http://finto.fi/yse/fi/page/Y505939)

**Comment by mirmaid** [comment]
Ehkä mahdollinen muodossa _kokeneisuus_ (ei Melindassa), tai yksikössä _kokemus_ (Melindassa 18 kertaa ysa-sanana, yht. noin 80 kertaa asiasanana). Yksikkö-monikko-parina tarvittaisiin sulkutarkenne ainakin yksikkömuotoiselle.

**Comment by mariaforsen** [comment]
Sv. erfarenhet (egenskaper)

**Comment by YSA-kokous** [comment]
kokeneisuus KT kokemus
