### ISSUE TITLE
Kumtähdenkenttä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5940]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kumtähdenkenttä 

#### Ehdotettu termi ruotsiksi   

Gumtäkts äng 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puistot](http://www.yso.fi/onto/yso/p3227) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kumtähdenkenttä : puistohistoriallinen selvitys 

#### Tarkoitusta täsmentävä selite   

puistoalue Helsingin Toukolassa 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [Kumtähdenkenttä](http://finto.fi/yse/fi/page/Y505940)

**Comment by YSA-kokous** [comment]
Tarkistetaan vielä muoto.
