### ISSUE TITLE
Kasvinsuojeluaineet, termi nyt vain ohjausterminä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5941]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kasvinsuojeluaineet, termi nyt vain ohjausterminä 

#### Ehdotettu termi ruotsiksi   

Växtskyddsmedel 

#### Ehdotettu termi englanniksi   

Plant protection products 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kemikaalit](http://www.yso.fi/onto/yso/p7757) 

#### Alakäsitteet (RT)   

[aine](http://www.yso.fi/onto/yso/p1433) 

#### Assosiatiiviset (RT)   

[torjunta-aineet](http://www.yso.fi/onto/yso/p10441) 

#### Vastaava käsite muussa sanastossa   

KOKO, kasvinsuojeluaineet : https://finto.fi/koko/fi/page/p77848 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Perustelut ehdotukselle   

Tukes uudistaa tukes.fi-verkkosivunsa ja ottaa uudessa verkkosivustossa ontologiat käyttöön. Tässä yhteydessä olisi tarve saada nykyisin ohjausterminä YSOssa oleva kasvinsuojeluaineet omaksi alakäsitteeksi, ei pelkästään ohjaavaksi termiksi. Tällä hetkellä YSOssa kasvinsuojeluaineet on ohjaustermi torjunta-aineille. Tukesissa kasvinsuojeluaineet ymmärretään tarkemmin, sillä myös biosidit ovat torjunta-aineita.

Tukesissa kasvinsuojeluaineilla tarkoitetaan valmisteita, joita käytetään:
-	suojelemaan kasveja tai kasvituotteita kasvintuhoojalta (tuhoeläinten ja kasvitautien torjunta-aineet) 
-	tuhoamaan haitallisia kasveja tai kasvin osia tai estämään kasvien haitallista kasvua (rikkakasvien torjunta-aineet)
-	vaikuttamaan kasvien elintoimintoihin muulla tavoin kuin ravinteina (kasvunsääteet)
-	vaikuttamaan kasvituotteiden säilyvyyteen, jollei näihin aineisiin ja valmisteisiin sovelleta elintarvikelisäaineita koskevia erityissäännöksiä.
Lisätietoa: http://www.tukes.fi/fi/Toimialat/Kemikaalit-biosidit-ja-kasvinsuojeluaineet/Kasvinsuojeluaineet/ . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Uusi tukes.fi julkaistaan toukokuussa 2018, joten sen sisältö ei vielä ole julkinen. Tietosisällöltään vastaava paketti on nykyisillä verkkosivuilla http://www.tukes.fi/fi/Toimialat/Kemikaalit-biosidit-ja-kasvinsuojeluaineet/Kasvinsuojeluaineet/ . 

**Ehdottajan nimi:** Mervi Savela ja Mirva Kipinoinen 
**Ehdottajan organisaatio:** Turvallisuus- ja kemikaalivirasto (Tukes) 
**Ehdottajan sähköpostiosoite:** mirva.kipinoinen@tukes.fi **Termiehdotus Fintossa:** [Kasvinsuojeluaineet, termi nyt vain ohjausterminä](http://finto.fi/yse/fi/page/Y505941)

**Comment by mariaforsen** [comment]
Myös SAOssa sekä bekämpningsmedel että växtskyddsmedel.

**Comment by YSA-kokous** [comment]
Seuraava kokous
