### ISSUE TITLE
nesteytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5942]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nesteytys](http://www.yso.fi/onto/ysa/Y97640) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selkeytettävä termien "nesteytys" ja "tiivistyminen" käyttöä yhdenmukaiseksi kielten välillä. Nesteytys sv. kondensation, usein oikea vastine ruotsinkieliselle olisi kuitenkin tiivistyminen tai kondensaatio/kondensaatioreaktio. Tiivistyminen sv. komprimering. 

#### Perustelut ehdotukselle   

Nykytilanne johtaa virheisiin kuvailussa 

#### Ehdottaja   

Mirja Anttila 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by mirmaid** [comment]
Nesteytys = nestehoito käsitelty issuessa https://github.com/Finto-ehdotus/YSE/issues/5408.

**Comment by mirmaid** [comment]
Ainakin kaasun yhteydessä suomeksi nesteytys, ruots. förvätskning (eng. liquefaction). Joko nesteytys (tarkenne x), tai rajataan kaikilla kielillä kaasun nesteytykseen. YSAssa on jo _nestekaasu_ ja _nesteytetty maakaasu_, joten käsitteen tarpeellisuus ei ehkä suuren suuri.

**Comment by mirmaid** [comment]
_tiivistyminen (kondensaatio)_

Lisäksi käytetty lähinnä maaperän (viljelymaan) tiivistymisestä (ruots. markpackning), mutta myös esim. tienrakennuksen yhteydessä, kun tiivistyminen on taas toivottava asia. Lisäksi betonista, asfaltista. 

_Kondensaatioreaktio_ ja _Bose-Einstein kondensaatio_ olisi syytä pitää erillään, mutta ainakin jälkimmäisen yhteydessä tiivistyminen (kondensaatio) varmaan tuntuu sopivalta...

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/156

**Comment by mariaforsen** [comment]
SAO: kondensation (=över­gång från gas­form till vätska)
förvätskning "kallas de kemiska processer, då en råvara är antingen fast eller gasformig, och produkten (vanligen kemikalier eller drivmedel) som fås är vätskeformig."

**Comment by jarmosaarikko** [comment]
"maaperän tiivistyminen"  "markpackning" (sv)  voisi lisätä erillisenä käsitteenä ja muuhun tiivistymiseen  RT viittaus?
LC "soil compaction" http://id.loc.gov/authorities/subjects/sh98001290
Agrovoc: "soil compaction" http://aims.fao.org/aos/agrovoc/c_7163

**Comment by YSA-kokous** [comment]
tiivistyminen (kondensaatio)
kondensaatioreaktiot
kaasun nesteytys - tutkitaan riittääkö nestekaasu, jos ei, tehdään uusi ehdotus
maaperän tiivistyminen ym. - tutkitaan
Bosen-Einsteinen kondensaatio, Mirja tutkii
myös tiivistys ja eristys tutkittava

**Comment by satuniininen** [comment]
Maaperän tiivistyminen on Wikipediassa jaettu seuraavasti:

"For soil compaction in agriculture, see **soil compaction (agriculture)**, for natural compaction on a geologic scale, see **compaction (geology);** for consolidation near the surface, see **consolidation (soil)**. In **geotechnical engineering**, soil compaction is the process in which a stress applied to a soil causes densification as air is displaced from the pores between the soil grains."

**Compaction (geology)** viittaa tiivistymiseen sedimentologian kontekstissa ja **consolidation (soil)** maanpinnan tiivistymiseen, eli siihen joka saa esim. Pisan tornin kallelleen. Ei-toivottua tiivistymistä pääsääntöisesti tämäkin, mutta ei liity maanviljelyyn. Näitä käyttöyhteyksiä tiivistymiselle ei Melindasta löytynyt.

Asiasanaa **tiivistyminen** on käytetty maanviljelyn merkityksessä ja asiasanaa **tiivistys** geotekniikan merkityksessä (esim. Louhepenkereen syvätiivistys / Mikko Heikura). Nämä voisi erottaa omiksi asiasanoikseen sulkutarkenteilla. Pari osumaa käsittelevät tiivistymistä urheilukentän nurmipeitteen kasvuolosuhteiden kannalta, joten tarkenne voisi olla maanviljelyä laajempi. 

eli esim:
tiivistyminen (kasvuolosuhteet) TAI
tiivistyminen (viljelymaa)

tiivistys (maarakentaminen) TAI
tiivistys (geotekniikka)

@mariaforsen miltä tämä näyttäisi ruotsin kannalta? Onko tiivistyminen maarakentamisen yhteydessä myös markpackning?

**Comment by mariaforsen** [comment]
Ok. Markpackning on viljelyyn liittyvä termi ja aina "negatiivista", eli ei käytetä maarakentamisen yhteydessä.

**Comment by satuniininen** [comment]
Saisikohan sementin ja betonin tiivistymisen sisällytettyä tuohon maarakentamisen merkitykseen? Kyse on kuitenkin periaatteessa samasta asiasta eli ilman poistamisesta massasta, jotta siitä tulee tiiviimpi. Myös englannin vastineet sopisivat:
betonin tiivistyminen = concrete compaction tai consolidation
asfaltin tiivistyminen = asphalt concrete compaction tai consolidation

**Comment by mirmaid** [comment]
Päätetään:
tiivistyminen (kasvuolosuhteet) TAI
tiivistyminen (viljelymaa)

tiivistys (maarakentaminen) TAI
tiivistys (geotekniikka)

Jos jälkimmäiseen merkitykseen yhdistetään myös betoni ym. pitäisikö sulkutarkenteen olla jotain niinkin laajaa kuin esim. _(aineen)_?

Siirretään vielä avoimiksi jäävät (tiivistys/eristys) uuteen issueen.

**Comment by jarmosaarikko** [comment]
Käyisikö jälkimmäiseen tiivistys (tekniikka)   -- siis ilman geo alkuliitettä?

**Comment by YSA-kokous** [comment]
tiivistyminen (kasvuolosuhteet)

tiivistys (maarakentaminen) TAI tiivistys (geotekniikka) - tutkitaan vielä

Siirretään vielä avoimiksi jäävät (tiivistys/eristys) uuteen issueen.

**Comment by mirmaid** [comment]
kaasun nesteytys - tutkitaan riittääkö nestekaasu, jos ei, tehdään uusi ehdotus
Bosen-Einsteinin kondensaatio, Mirja tutkii
tiivistys (maarakentaminen) TAI tiivistys (geotekniikka) - tutkitaan vielä

**Comment by satuniininen** [comment]
Melinda-kuvailuja, jossa aiheena massan tai aineksen mutta ei viljelymaan tiivistyminen: 

- Asfalttipäällysteiden tutkimusohjelma ASTO 1987-1992, Asfalttimassan tiivistettävyys
- Kalliomurskeiden tiivistyminen ja hienoneminen 
- Itsetiivistyvät betonit 
- Uusioasfalttimassan tiivistyminen 
- Hiekkapintaisten pallokenttien pinnan materiaali- ja jousto-ominaisuudet.

_Tiivistys (aineen)_ kuulostaa muuten hyvältä, mutta meneekö sekaisin kondensaation ja ehkä jopa eristämisen kanssa?

Entä _tiivistys (kiinteyttäminen)_ tai _tiivistys (lujittaminen)_?

**Comment by satuniininen** [comment]
Korjattu tiivistyminen (kasvuolosuhteet) ja tiivistyminen (kondensaatio), yli jäi 14. 

Loput käsittelevät pääasiassa asfaltin, sementin tai maarakentamisen tiivistystä. Lisäksi muutama yksittäinen  hajatapaus, joissa merkitys jää epäselväksi tai mikään ehdotetuista ei sovi (esim. kondensoitunut kromatiini teoksessa _From DNA sequence to chromatin organization : the fundamental role of genomic long-range correlations_.) Näissa tapauksissa voidaan käyttää korvaavaa sanastoa.

Kannatan muotoa **tiivistys (lujittaminen)**

**Comment by YSA-kokous** [comment]
tiivistys (lujittaminen)

**Comment by mariaforsen** [comment]
Sv.
-kondensation ET förvätskning =tiivistyminen (kondensaatio)
-markpackning =tiivistyminen (kasvuolosuhteet)  
-komprimering (förstärkning) ET kompaktering, packning =tiivistys (lujittaminen)

**Comment by satuniininen** [comment]
Nesteytyksestä siivottu myös _nestekaasu_ ja _nesteytetty maakaasu_.

Jäljellä 5, joista 2 käsittelee Bosen-Einsteinin kondensaatiota ja 3 biomassan nesteytystä (liquefaction).
