### ISSUE TITLE
gammakuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5943]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[gammakuvaus](http://www.yso.fi/onto/ysa/Y106911) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: isotooppikuvaus? Vai päätermin vaihto?

#### Perustelut ehdotukselle   

Mesh:issä isotooppikuvaus on päätermi. Englanninkieliset ja ruotsinkieliset vastineet myös eri kuin YSOssa. Ks. myös Lääketieteen termit yms. sanastoja. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Lääketieteen termit: gammakuvaus:  isotooppikuvantaminen, skintigrafia | kudokseen siirtyneen radionuklidin lähettämään gammasäteilyyn (→säteily) perustuva elimen tai elimistön kuvantaminen

FinMeSH: gammakuvaus KÄ isotooppitutkimus

https://fi.wikipedia.org/wiki/Gammakuvaus

**Comment by YSA-kokous** [comment]
gammakuvaus KT isotooppikuvaus, isotooppitutkimus
