### ISSUE TITLE
kazakit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5944]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kazakit 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Kazakit 

#### Tarkoitusta täsmentävä selite   

kansa 

#### Perustelut ehdotukselle   

YSA:ssa on jo maa Kazakstan ja kazakin kieli eli kazakki, mutta kansaa tarkoittavaa termiä ei löydy. Termiä "kazakit" on kuitenkin käytetty aineiston kuvailussa ainakin yli 60 kertaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://melinda.kansalliskirjasto.fi/F/HL7QYU14GGA7P3KFGQ2C56PDHLD1XIM2KKR52XADX8NJ5R9GA4-03563?func=full-set-set&set_number=026557&set_entry=000001&format=999 

**Ehdottajan nimi:** Margarita Tapanainen-Bukovski 
**Ehdottajan sähköpostiosoite:** margarita-tapanainen-bukovski@helsinki.fi **Termiehdotus Fintossa:** [kazakit](http://finto.fi/yse/fi/page/Y505944)

**Comment by mariaforsen** [comment]
Sv. kazaker
