### ISSUE TITLE
avotyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5945]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[avotyö](http://www.yso.fi/onto/ysa/Y127054) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelläänkö tarkemmin/muutetaanko nykyinen huomautus: "Avotyö voi tarkoittaa kahta asiaa. 1) Avotyö on vammaisten henkilöiden huoltosuhteeseen perustuvaa työtä normaaleilla työpaikoilla. 2) Avotyö tarkoittaa lastensuojelun ja perhetukikeskusten piirissä tehtävää työtä" Vai onko itse termi muutettavissa selkeämmäksi? 

#### Perustelut ehdotukselle   

Nykysääntöjen mukaan termi ei saa olla monimerkityksinen. Tämä termi ei löydy sanakirjoista, laista tms. Sanastossa on myös tuettu työllistyminen, suojatyö yms. Vähän käytetty Melindassa. Termi nykymuodossan näyttää harhaanjohtavalta. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Käytetty Melindassa lähes yksinomaan 1-merkityksessä. Muutetaan ainakin määritelmää, myös termin voisi mahdollisesti muuttaa muotoon _avotyötoiminta_? Ilmeisesti tämä on loppumassa lähitulevaisuudessa: https://motiivilehti.fi/2016/moitittu-kehitysvammaisten-avotyotoiminta-saattaa-viimein-loppua/

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi on kyllä sulkutarkenne tarpeen (tai termin muutos), koska itse termiä voi muuten helposti käyttää aivan väärin.

**Comment by YSA-kokous** [comment]
KÄ työtoiminta, kuntouttava työtoiminta
