### ISSUE TITLE
asennot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5946]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asennot](http://www.yso.fi/onto/ysa/Y113373) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelläänkö/rajataanko kehon ja ruumiinosien, eli fyysisiin asentoihin? Esim. vaihtamalla temaattista ryhmää ja huomautuksella? 

#### Perustelut ehdotukselle   

Ruotsinkielinen vastine kroppsställningar. Kielitoimiston sanakirjassa jaettu kahteen, ehdotus ykkösmerkityksen mukaan:  ruumiin t. sen osan t. osien (hetkellinen) sijaintitapa. Melindassa käytetty melkein vain tässä merkityksessä, paitsi esim. "KBS-3H complementary studies 2008-2010" ja "Leaf orientation and the spectral reflectance of field crops / Xiaochen Zou". 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Ruotsinkielinen vastine on kyllä melko veikeä jos kyse on ydinjätekapselista...

**Comment by mirmaid** [comment]
Rajataan suomeksi

**Comment by mirmaid** [comment]
FinMeSH: asento KÄ ruumiinasento http://www.yso.fi/onto/mesh/D011187

**Comment by YSA-kokous** [comment]
asennot (ruumiinasennot)
