### ISSUE TITLE
kasvatusyhteistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5947]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kasvatusyhteistyö 

#### Vaihtoehtoiset termit ja ilmaisut   

kasvatuskumppanuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Tarkoitusta täsmentävä selite   

Kasvatuskumppanuus vaihtui kasvatusyhteistyöksi uuden vasun myötä. 

#### Perustelut ehdotukselle   

2016: kasvatusyhteistyö http://www.oph.fi/download/179349_varhaiskasvatussuunnitelman_perusteet_2016.pdf 
2005: kasvatuskumppanuus http://www.julkari.fi/handle/10024/77129 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Useita opinnäytetöitä tekeillä + esimerkiksi haku Melindasta "kasvatusyhteistyö" 

**Ehdottajan nimi:** Anne Mikkanen 
**Ehdottajan sähköpostiosoite:** anne.mikkanen@savonia.fi 
**Ehdottajan organisaatio:** Savonia-amk **Termiehdotus Fintossa:** [kasvatusyhteistyö](http://finto.fi/yse/fi/page/Y505947)

**Comment by mirmaid** [comment]
YSAssa siis on termi _kasvatuskumppanuus_: Tarkoittaa kasvatustyöntekijöiden ja vanhempien välistä tasavertaista kasvatusyhteistyötä, jossa luodaan puitteet lapsen kasvulle, kehitykselle ja oppimiselle

**Comment by mariaforsen** [comment]
Sv. fostringssamarbete

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Kun puhutaan kasvatuskumppanuudesta, ajatellaan että sekä vanhemmilla että kasvattajilla on olennaista tietoa lapsesta ja että heillä on yhteisiä tavoitteita lapsen varhaiskasvatuksessa. Kasvatuskumppanuus edellyttää vuorovaikutusta, joka on vastavuoroista, jatkuvaa ja sitoutunutta. Vanhempien asiantuntijuus ja tieto nähdään tärkeänä. Suomessa kumppanuus on nähty tasa-arvoisena kommunikointina kasvattajien ja vanhempien välillä ja vanhempien asiantuntijuutena heidän lastaan koskevissa asioissa. Tämä on toki haastanut perinteisen suomalaisen varhaiskasvatuksen, joka on nojannut asiantuntijuuteen ja ammatilliseen tietoon. (Karila, 2006, 92–94; Alasuutari 2010, 150.) 

Uusi valtakunnallinen varhaiskasvatussuunnitelma, Varhaiskasvatussuunnitelman perusteet 2016, puhuu kuitenkin kasvatuskumppanuus-termin tilalla varhaiskasvatuksessa tapahtuvasta kasvatusyhteistyöstä. Muutoksen taustalla saattavat olla muuttuneet ajatukset kasvatuskumppanuudesta ja yhteistyöstä, joita muun muassa Onnismaan (2010) on kuvannut. Kasvatuskumppanuuden ajatellaan pohjaavan vapaaehtoisuuteen ja sen ajatellaan olevan melko intiimi termi kuvaamaan vanhemman ja kasvattajan suhdetta, jota voidaan pitkälti ajatella asiakkaan ja julkisen palvelun tarjoajan välisenä suhteen. Kasvatusyhteistyö-termiä voidaan puolestaan pitää toiminnallisena käsitteenä. Siinä keskeisenä on yhteistyösuhteessa olevien yhteinen tavoite ja tekeminen. (Onnismaa 2010, 256.)

Vaikka yhteistyöstä käytettävä termi on uuteen Valtakunnalliseen varhaiskasvatussuunnitelmaan muuttunut ja yhteistyöstä on kirjoitettu siinä hieman eri tyyliin kuin aikaisemmin, on asian sisältö pitkälti pysynyt samana. Uudessa suunnitelmassa puhutaan konkreettisista yhteistyötilanteista ja yhteistyön monista muodoista, kuten päivittäisistä keskusteluista, lapsen varhaiskasvatussuunnitelma keskusteluista tai keskusteluista suunniteltaessa lapsen erityistä tukea. Uudessa suunnitelmassa puhutaan myös vahvemmin vanhempien osallisuudesta toiminnan ja tavoitteiden suunnitteluun sekä lasten vanhempien keskinäisestä verkostoitumisesta. (Varhaiskasvatussuunnitelman perusteet 2016, 33.)

https://jyx.jyu.fi/bitstream/handle/123456789/56795/URN%3aNBN%3afi%3ajyu-201801181271.pdf?sequence=1&isAllowed=y
