### ISSUE TITLE
harjoitusmenetelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5949]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

harjoitusmenetelmät 

#### Ehdotettu termi ruotsiksi   

träningsmetoder

#### Ehdotettu termi englanniksi   

exercise methods? 

#### Vaihtoehtoiset termit ja ilmaisut   

Sv. KT övningsmetoder 

#### Ehdotettu yläkäsite YSOssa (LT)   

[menetelmät](http://www.yso.fi/onto/yso/p1913) 

#### Assosiatiiviset (RT)   

[harjoitukset](http://www.yso.fi/onto/yso/p13335) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 
[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Perustelut ehdotukselle   

On jo YSOssa ja todettu YSO-kokouksessa että olisi hyvä lisätä YSAankin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melindassa esim. Therapeutic exercise : foundations and techniques / Carolyn Kisner, Lynn Allen Colby 

**Ehdottajan nimi:** Maria Forsén 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [harjoitusmenetelmät](http://finto.fi/yse/fi/page/Y505949)

**Comment by mariaforsen** [comment]
Sv. ?
nu i Allärs träningsmetoder=valmennusmenetelmät > coachningsmetoder, metoder för träning av andra...?

träna=metodiskt försöka förbättra sin färdighet i (ngt) genom särskilt anpassade övningar spec. i sportsammanhang men äv. allmännare 
öva=metodiskt försöka förbättra sin färdighet i (ngt) genom särskilt anpassade (upprepade) aktiviteter vanl. i fråga om intellektuell el. motorisk färdighet e.d. 
SAOL träningsmetod (ej övningsmetod)

jfr Allärs coachning=valmennus
