### ISSUE TITLE
täyttö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5950]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[täyttö](http://www.yso.fi/onto/ysa/Y111156) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan? 

#### Perustelut ehdotukselle   

YSO-kokous ehdottaa poistoa. Termi on käytetty vähän ja sekavasti Melindassa. Vaikea kääntää ellei määritellä tarkasti minkälaisesta "täytöstä" on kysymys. Nykyään sanastossa on myös erikseen "eläinten täyttäminen". 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Myös _virantäyttö_ erikseen sanastossa

**Comment by mirmaid** [comment]
Muuten Melindassa käytetty muutamia kertoja pakkausten täytöstä elintarviketeollisuudessa, sekä viisi kertaa kun aiheena pohjarakennus (rakennusten perustukset). Jälkimmäisessä merkityksessä mahdollinen olisi myös _täyttötyöt_.

**Comment by YSA-kokous** [comment]
poistetaan täyttö
täyttö (eläimet) KÄ eläinten täyttäminen
täyttötyöt (?)
