### ISSUE TITLE
traditio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5953]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[traditio](http://www.yso.fi/onto/ysa/Y104643) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö lisätä määritelmiä, tarkenteita, tai mahdollisesti yhdistää (perinne)? 

#### Perustelut ehdotukselle   

Sanastossa myös perinne. Ruotsiksi (ja englanniksi) molemmat ovat "tradition". Nykyiset ruotsinkieliset vastineet eivät toimi, mutta jotta saadaan paremmat/selkeämmät vastineet täytyy varmistaa miten nämä on tarkoitus käyttää suomen osalta. Molemmilla on KT perinteet ja sama ryhmä, eli 50.

Myös perimätieto olisi oikeastaan tradition ruotsiksi (nyt virheellinen "hävd").

Kielitoimiston sanakirja:

perinne: peritty tapa, käytänne t. tieto, perimä-, perinnäistapa t. -tieto, traditio.
Erik. kansan muistitiedon varassa säilyttämästä henkisestä kulttuurista.

traditio: perinne, perimätieto, perinnäistapa; usein noudatettu tapa.

perimätieto: sukupolvelta toiselle suullisesti periytynyt tieto, perinne, traditio

#849 

#### Ehdottaja   

YSO-kokous 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by krinay** [comment]
Kannatan termien yhdistämistä: perinne KT traditio.
