### ISSUE TITLE
kasvien lisäys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5954]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kasvien lisäys 

#### Ehdotettu termi ruotsiksi   

växtförökning ET förökning av växter

#### Vaihtoehtoiset termit ja ilmaisut   

lisäys (kasvit) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luonti](http://www.yso.fi/onto/yso/p465) 

#### Perustelut ehdotukselle   

YSO-kokous ehdottaa lisäys-termin käsittelyn yhteydessä. Melindassa runsaasti aineistoa.
Ks. https://github.com/NatLibFi/Finto-data/issues/914

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Suomalaiset perinneperennat / [tekstit: Erja Rappe, Ella Räty ja Maija Stenman]. 

**Ehdottajan nimi:** Maria Forsén 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [kasvien lisäys](http://finto.fi/yse/fi/page/Y505954)

**Comment by ilona-x** [comment]
AFO: kasvien lisäys https://finto.fi/afo/fi/page/p1565

ST kasvullinen lisäys http://finto.fi/ysa/fi/page/Y123609 (vrt. AFO)
