### ISSUE TITLE
lisäys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5955]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lisäys](http://www.yso.fi/onto/ysa/Y112561) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa? Vai pitääkö jakaa, määritellä tarkemmin tms. 

#### Perustelut ehdotukselle   

Ks. https://github.com/NatLibFi/Finto-data/issues/914
Lisäys on monimerkityksinen termi. Muunkieliset vastineet riippuvat merkityksestä. 
Sanastoon on nyt ehdotettu erikseen "kasvien lisäys". 

Kielitoimiston sanakirja: lisäys:
-lisääminen. Fluorin lisäys veteen. (sv. tillsättning, tillägg)
-lisääntyminen, kasvu. Kalakannan viimeaikainen lisäys. (sv. tillväxt..? förökning..?)
-lisäämisen t. lisääntymisen tulos, lisätty t. lisääntynyt määrä. (sv. ökning)

Melindassa suurin osa aineistosta käsitteli kasvien lisäystä.

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mariaforsen** [comment]
Ks. Melinda, nyt esim.
-Energiasäästötarkastelu pientalossa / Mikko Moilanen.
-Laajentamissuunnitelma lypsykarjatilalle : case Kekkonen / Hanna Kekkonen, Jarkko Kekkonen.
-Vuoden 2004 alun alkoholiolojen muutokset Suomessa myyntitilastojen ja lehdistökirjoittelun valossa / Thomas Karlsson ... [ja muita] ; Köp nu! : 25 steg som garanterat ökar din försäljning / Krister Maxe. (sv. ökning sopii)
-Val201-peptidin vaikutus eturauhassyöpäsoluissa / Ilpo Rajala, Jouko Roukala, Ida Smith. (sv. ökning ok?)
-Selvitys uusiutuvan energian lisäämisen kustannuksista ja edistämiskeinoista. ; Liikkuva ja hyvinvoiva Suomi 2010-luvulla : ehdotus kansalliseksi liikuntaohjelmaksi julkisen ohjauksen näkökulmasta. (sv. ökning?)
-Semantiikka ja pragmatiikka Asterixin suomennoksessa ja ruotsinnoksessa / Maire Kosonen. ; Elintarvikkeiden täydentäminen raudalla : mallinnettu saanti suomalaisilla aikuisilla / [Susanna Raulio]. (sv. olisi lähinnä tillägg/tillsättning, ökning ei sovi ollenkaan!)

Eli:
-Kun lisätään jotain "uutta" johonkin toiseen/vanhaan/olemassa olevaan (esim. fluorin lisäys veteen)= tillsättning/tillägg
-Kun joku olemassa oleva asia laajenee/tulee lisää sitä samaa ainetta/asiaa tms.=ökning
-Kun kasvit/eläimet lisääntyvät (riippumatta onko se ihminen joka toiminnallaan antaa siihen edellytykset, esim. perennojen lisäys)=förökning (nyt förökning=lisääntyminen=uusien eliöyksilöiden syntymisestä saman lajin vanhemmista yksilöistä) 

Ruotsin osalta puuttuu siis nyt lähinnä tillägg/tillsättning. Olisiko mahdollista jotenkin lisätä sanastoon "lisääminen"=sv. tillsättning/tillägg?

**Comment by mirmaid** [comment]
Joissakin tapauksissa mahdollisesti korvattavissa myös termillä _laajentaminen_.

Usein kuvailussa ketjutustyyppinen täytesana joka ei ole haun kannalta olennainen. Joissakin tapauksissa parempi muoto olisi ehkä _lisäykset_ (kirjallisuus/kielitieteen aineistoissa).

**Comment by ilona-x** [comment]
Korjattu Melindaan lisäys (kasvit) -> kasvien lisäys
Jäljelle jäi 15 viitettä, joista melkein kaikista lisäys-termin voisi mielestäni melko huoletta poistaa. 
Esimerkkejä lisäyksistä:
palvelut + lisäys
tilat + lisäys
rauta + lisäys + elintarvikkeet
alkoholijuomat + myynti + kulutus + lisäys
lahopuut + lisäys
uusiutuvat energialähteet + lisäys
liikunta + lisäys
eristeet + lisäys

**Comment by YSA-kokous** [comment]
poistetaan lisäys, tutkitaan käännös- ja kirjallisuustieteen viitteet
