### ISSUE TITLE
elimistö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5956]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elimistö](http://www.yso.fi/onto/ysa/Y111797) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: elinjärjestelmä 

#### Perustelut ehdotukselle   

Englanninkielinen vastine YSOssa "organ system" ja nyt muokataan myös ruotsiksi > "organsystem"? Esim. Lääketieteen termeissä on elinjärjestelmä synonyyminä. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by satuniininen** [comment]
Meshissä ei ole _elinjärjestelmää_, mutta siellä lienee erilainen lähestymistapa muutenkin, sillä _elimistö_ ohjautuu _ihmiskehoon_
