### ISSUE TITLE
kirkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5957]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kirkot](http://www.yso.fi/onto/ysa/Y96239) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

poistetaan ja ohjataan kirkko KT kirkot
(lisäksi tarvittaessa esim. kirkkokunnat KT kirkot) 

#### Perustelut ehdotukselle   

kirkko Melindassa 2073 kertaa
kirkot Melindassa 953 kertaa

Samantyyppinen tapaus kuin taannoinen seurakunta / seurakunnat, joka päädyttiin yhdistämään.
Käsitteet menevät herkästi sekaisin ja kuvailukäyttö on ollut polveilevaa. Melindassa monikollista muotoa on käytetty paljon tarkoittamaan todennäköisesti kirkkorakennusta, esim. teoksessa _Kenen tekemää alttaritaidetta? : vuosina 2000-2010 rakennettujen luterilaisten kirkkojen taiteilijavalintojen tarkastelua._
Niissä tapauksissa yksiköllinen kirkko kuulostaa vieraalta, mutta muutoin monikollisen korvaaminen yksiköllisellä voisi toimia.

Esim.
Katso ihmistä : näkökulmia kristilliseen ihmiskäsitykseen
650 kristinusko
650 ihmiskuva
650 kirkot --> kirkko

Uskon silta Suomenlahden yli : suomalaisten kirkolliset yhteydet Viroon vuosina 1918-1939
650 kirkot --> kirkko
650 kansainväliset suhteet
650 heimoaate
650 evankelis-luterilainen kirkko

Ecumenical attack against racism :  the anti-racist programme of the World Council of Churches, 1968-1974
650 ekumenia
650 kirkot --> kirkko
650 kansainväliset järjestöt
650 rasismi 

#### Ehdottaja   

Satu Niininen / Yso-kokous 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by jtuohini** [comment]
Eittämättä asiasanaa **kirkot** on käytetty Melindassa ja paikallistietokannoissa pilvin pimein asiasanan **kirkkorakennukset** sijaan, mutta korjaukseksi ei kelpaa yksikön korvaaminen monikolla, vaan kertakaikkiaan väärien asiasanojen vaihtaminen oikeaksi. Sekaannuksen yksi syy voi piillä asiasanoissa **kivikirkot**, **puukirkot** ja **tuomiokirkot**, joissa ei ole selkeyttävää "rakennukset"-loppuosaa.
 
Sen sijaan analogia sanaparien "kirkko" ~ "kirkot" (oikeammin "kirkkokunnat") ja "seurakunta" ~ "seurakunnat" välillä ei ole paras mahdollinen: "kirkko" on eräällä tavoin jakamaton kokonaisuus, vaikka koostuukin kirkkokunnista (ks. suomenkielisen Wikipedian Kirkko-artikkelin laajin merkitys). Vastine löytyisi kenties osuvammin sanaparista "uskonto" ~ "uskonnot" ("uskontokunnat").

**Comment by mirmaid** [comment]
LCSH
Church
Churches USE Church buildings
Christian denominations USE Christian sects (names of individual sects, e.g. Catholic Church)

**Comment by jtuohini** [comment]
Jatkaakseni vielä Mirjan LCSH-kommenttia:
 
YSA-asiasana = LCSH-asiasana
**kirkko** ja **kirkko-oppi** = [**Church**](http://id.loc.gov/authorities/subjects/sh85025502), KT _Ecclesiastical theology_, _Ecclesiology_ ja _Theology, Ecclesiastical_
**kirkkorakennukset**, KT _kirkot--rakennukset_ = [**Church buildings**](http://id.loc.gov/authorities/subjects/sh85025854), KT _Churches_
**kirkot**, KT _kirkkokunnat_ = [**Christian sects**](http://id.loc.gov/authorities/subjects/sh85025193), KT _Christian denominations_, _Denominations, Christian_ ja _Sects, Christian_

**Comment by mariaforsen** [comment]
Kirkko ja erikseen kirkkokunnat voisi olla toimiva ratkaisu. Termiä "kyrkan" (YSA: kirkko) on käytetty Melindassa nyt varsinkin Suomen ev. lut kirkosta, joten ei kyllä tällaisenaan toimi (sen sijaan kun olisi käytetty "teologisena": "c) spec. om gemenskapen av alla kristna" /NE)

**Comment by mariaforsen** [comment]
Eli selveyden vuoksi, mihin jäljelle jäävä "kirkko" viittaisi? Kielitoimiston neljäs vaihtoehto: 
4. kristillisten seurakuntien muodostama, uskontunnustuksen t. opinkäsitysten yhdistämä kokonaisuus; myös koko kristikunnasta ? Gummerus new Finnish dictionary: 3 kristittyjen yhteisö, kristikunta 4 tunnustuksellisesti erottuva kristillinen uskonyhteisö, siihen liittyvät laitokset ja työntekijät ? Olisi varmaan hyvä lisätä määritelmä tässä tapauksessa. 
Ratkaisu, jossa kristikunnat (kyrkosamfund) erikseen voisi olla toimiva, mutta vaatisi ehkä "käyttöohjeita".

**Comment by satuniininen** [comment]
Melindassa käytetty monikollista _kirkot_-käsitettä noin 1000 kertaa. Kävin näistä läpi 100 ensimmäistä sillä silmällä, että voisiko kirkot korvata joko _kirkko_-, _kirkkorakennukset_- tai _kirkkokunnat_-käsitteellä.

43 tietueeseen sopii kirkkorakennnukset
32 tietueeseen sopii kirkkokunnat
16 tietueeseen sopii kirkko
  9 tietuetta jäi yli, osa siksi, että tietueessa oli tietoa saatavilla hyvin niukasti ja ratkaisu olisi vaatinut lisäselvittelyä.

Muutama rajatapaus:

**Kirkkokahvit on ollu aina : 50 vuotta suomalaista seurakuntatyötä Sydneyssä / Riitta Niemi.**

- Tähän ei hirveän hyvin sovi näistä mikään, mutta _luterilaiset kirkot + seurakunnat_ ehkä riittäisi?

**Songs of Seoul : an ethnography of voice and voicing in Christian South Korea / Nicholas Harkness.**

- Riittäisikö kirkkomusiikki?

**Verkkosivujen käyttäjätutkimus : Kuopion hiippakunta / Tuomas Airaksinen.**

- tähänkin ehkä riittäisi hiippakunnat (+ seurakunnat)

**Kalmistosta kirkkoon : Hattulan Pyhän Ristin kirkko tapaustutkimuksena / Erika Kare.**

- Tämä tuntui hankalalta, koska mielsin että siinä käsitellään laajempaa kokonaisuutta kuin kirkkorakennusta. Toisaalta kyseinen kirkko on jo sanastossa, joten aineisto kyllä sinällään on löydettävissä.

**Comment by mirmaid** [comment]
^ Tästä voisi päätellä että tarvitaan kuitenkin termit _kirkkokunnat_, jos monikollinen poistetaan?

**Comment by jtuohini** [comment]
Ei varmaan siis poistettaisi, vaan nykyinen **kirkot**, KT _kirkkokunnat_ muutettaisin päinvastoin eli **kirkkokunnat**, KT _kirkot_? Ja siis termiä kyllä tarvitaan siihen aineistoon, joka käsittelee useaa eri kirkko(kunta)a yhtä aikaa eikä halua listata jokaista erikseen.

**Comment by YSA-kokous** [comment]
kirkot KÄ kirkkokunnat

**Comment by mariaforsen** [comment]
Eikö jäljelle olevalle kirkko-termille lisätä tarkennetta (eikä huomautusta tai määritelmää)? Voiko se johtaa siihen että sitä käytetään miten sattuu? Varsinkin jos käyttäjä ei ole perillä tesaurus-säännöistä jne.

**Comment by jtuohini** [comment]
Voisi ehkä harkita asiasanojen **kirkko** ja **kirkko-oppi** yhdistämistä (vrt. LCSH)? Vai meneekö liian kerettiläiseksi?

**Comment by mirmaid** [comment]
Mikähän voisi olla mahdollinen tarkenne? YSOn _(ilmiöt)_ saattaa kyllä hämmentää käyttäjää.

**Comment by mariaforsen** [comment]
En kannata kirkon ja kirkko-opin yhdistämistä. Kirkko-oppi=ecklesiologi.

**Comment by jtuohini** [comment]
Entäpä _kirkko_ KÄ _**kristikunta**_?

**Comment by mirmaid** [comment]
_Kirkko_-termiä on käytetty Melindassa lähes 5000 kertaa ja lisäksi se on useissa KOKOn erikoisontologioissa, joten poistaminen ei ole ihan pikku juttu. Korvaaminen nyt ehdotetuilla vastineilla ei liene mahdollista sekään. Todennäköisemmin sopiva vastine olisi jokin tietty kirkkokunta, mutta läpikäynti olisi sen verran suuri urakka että se ei välttämättä ole toteutettavissa esim. ennen ysa-yso-konversiota.

**Comment by LeKorsu** [comment]
Tieteen termipankkiin viitaten tarkenne-ehdotus: kirkko (organisaatio)

**Comment by tpalonen** [comment]
Kirkko (organisaatio) ei terminä minusta riitä erottamaan käsitettä kirkkokunnista. Pikemminkin tuntuu synonyymilta.

**Comment by satuniininen** [comment]
Yksikölliselle kirkolle olisi runsaasti tarvetta aineistoissa, jotka käsittelevät esim. kirkon ja valtion tai kirkon ja yhteiskunnan välistä suhdetta. 
LCSH ja SAO ratkaisseen tämän problematiikan ottamalla ison määrän erillisiä käsitteitä _church and state, church and industry, church and mass media_ jne. Näitä on todella paljon, joten sille tielle tuskin halutaan lähteä. 

Kuten sanottua, (organisaatiot) ei riitä erottamaan käsitettä kirkkokunnista ja (ilmiöt) lienee käyttäjälle vieraannuttava. Muita vaihtoehtoja olisi ainakin: 

kirkko (yhteisö)
kirkko (uskonnollinen yhteisö)
kirkko (kristittyjen yhteisö)
kirkko (kristikunta)

**Comment by mariaforsen** [comment]
Koska sanastossa on myös kirkkokunnat (KT kirkot) kannatan yllä olevista vaihtoehdoista kirkko (kristikunta), muuten on hyvin vaikeaa erotella, ruotsiksi ainakin (koska kirkkokunnat=kyrkosamfund).

**Comment by YSA-kokous** [comment]
kirkko (instituutio)

**Comment by mariaforsen** [comment]
Sv. kyrkan (institution)
