### ISSUE TITLE
päänahka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5959]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[päänahka](http://www.yso.fi/onto/ysa/Y171521) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: hiuspohja? 

#### Perustelut ehdotukselle   

Allärs nyt hårbotten=päänahka, päätetään tämän jälkeen onko se ok. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by PaiviLipsanen** [comment]
päänahka on FinMeSHissä, Scalp, Hårbotten
https://finto.fi/mesh/fi/page/D012535
