### ISSUE TITLE
merikaapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5960]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

merikaapelit 

#### Ehdotettu termi ruotsiksi   

undervattenskabel, havskabel? 

#### Ehdotettu termi englanniksi   

sea cable, subaqueous cable, submarine cable, submarine line 

#### Perustelut ehdotukselle   

YSAssa on maakaapelit, valokaapelit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Teknistaloudellinen selvitys Koillisväylän merikaapelin toteutumisedellytyksistä http://urn.fi/URN:ISBN:978-952-243-466-1 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Merikaapeli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576) 
[41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536) 
[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi **Termiehdotus Fintossa:** [merikaapelit](http://finto.fi/yse/fi/page/Y505960)

**Comment by mariaforsen** [comment]
Sv. sjökablar ET havskablar, marinkablar, underhavskablar, undervattenskablar

**Comment by satuniininen** [comment]
LCSH:ssa [Cables, Submarine](http://id.loc.gov/authorities/subjects/sh85018581.html)
