### ISSUE TITLE
virkailijavaihto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5961]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[virkailijavaihto](http://www.yso.fi/onto/ysa/Y104706) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaanko? 

#### Perustelut ehdotukselle   

Ei sanakirjoissa/sanastoissa, Googlessa vain vähän, Melinda 13, Eduskunnan sanastossa ei ollenkaan, mutta kyllä virkamiesvaihto KÄYTÄ henkilövaihto. Jos jostain syystä halutaan säilyttää niin se vaatii jonkinlainen tarkenne ruotsiksi, ja siinä tapauksessa täytyy olla selvää mihin tarkalleen viittaa ja miten eroaa virkamiesvaihdolta (myös sanastossa). 
Ks. https://github.com/NatLibFi/Finto-data/issues/850 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
_Virkamiesvaihto tarkoittaa valtionhallinnon työntekijän lyhytaikaista työskentelyä ulkomailla, omalla hallinnonalalla._ 

_Virkamiesvaihto_ käytetty 5 kertaa Melindassa.

**Comment by ilona-x** [comment]
Melindan luvut päivitettynä (Arton viitteistä tullut lisäosumia näille): 

virkailijavaihto x 20 (aineistossa mm. asianajajia, opettajia, kirjastohenkilöstöä, virkamiehiä)
virkamiesvaihto x 14 (mm. virkamiehiä, poliiseja, tuomareita)
henkilövaihto x 90 (mm. opettajia, sairaanhoitajia, palomiehiä)

Ehdotus: poistetaan ainakin virkailijavaihto (ohjataan KÄ henkilövaihto?) 
Kielitoimiston sanakirja: **virkailija** julkisyhteisöjen alemmista virkamiehistä ja toimihenkilöistä; myös yksityisen palveluksessa olevista toimihenkilöistä. Kunnan virkailija. Lähetystö-, posti-, pankki-, vakuutus-, tulli-, verovirkailija.

**Comment by YSA-kokous** [comment]
virkailijavaihto, virkamiesvaihto KÄ henkilövaihto
