### ISSUE TITLE
järvisimpukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5962]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[järvisimpukka](http://www.yso.fi/onto/ysa/Y123513) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

päätermiksi pikkujärvisimpukka 

#### Perustelut ehdotukselle   

Olisin tarvinnut aineiston kuvailussa termiä isojärvisimpukka, ja huomasin, että tämä YSA:n termi järvisimpukka tarkoittaa ilmeisesti pikkujärvisimpukkaa (Allärs: allmän dammussla, YSO eng: Anodonta anatina, duck mussel) ja Melindan aineistotkin näyttävät käsittelevän pikkujärvisimpukkaa. 
Laji.fi: pikkujärvisimpukka https://laji.fi/taxon/MX.212404 

#### Ehdottaja   

Ilona Lindfors 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

ilona.lindfors@helsinki.fi

**Comment by ilona-x** [comment]
isojärvisimpukka #5963
