### ISSUE TITLE
isojärvisimpukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5963]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

isojärvisimpukka 

#### Ehdotettu termi ruotsiksi   

större dammussla 

#### Ehdotettu termi englanniksi   

swan mussel 

#### Vaihtoehtoiset termit ja ilmaisut   

Anodonta cygnea 

#### Ehdotettu yläkäsite YSOssa (LT)   

[simpukat](http://www.yso.fi/onto/yso/p1480) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Isoj%C3%A4rvisimpukka 

#### Tarkoitusta täsmentävä selite   

Laji.fi: https://laji.fi/taxon/MX.212405 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lippajärven isojärvisimpukkapopulaatioiden koko, rakenne ja simpukoiden suodattaman veden määrä 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [isojärvisimpukka](http://finto.fi/yse/fi/page/Y505963)

**Comment by mariaforsen** [comment]
Sv. större dammussla ET stor dammussla
