### ISSUE TITLE
urkumusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5964]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

urkumusiikki 

#### Ehdotettu termi ruotsiksi   

orgelmusik 

#### Ehdotettu termi englanniksi   

organ music 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85095468> 
Wikidata : https://www.wikidata.org/wiki/Q2003283 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu yksille tai useammille uruille tai muulle kokoonpanolle, jossa urut ovat keskeisessä osassa. 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1997818 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [urkumusiikki](http://finto.fi/yse/fi/page/Y505964)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan
