### ISSUE TITLE
viulumusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5965]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viulumusiikki 

#### Ehdotettu termi ruotsiksi   

violinmusik 

#### Ehdotettu termi englanniksi   

violin music 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85143607> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1222001 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle viululle tai muulle kokoonpanolle, jossa viulu on keskeisessä osassa. 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [viulumusiikki](http://finto.fi/yse/fi/page/Y505965)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan
