### ISSUE TITLE
Savonjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5966]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Savonjoki](http://www.yso.fi/onto/ysa/Y113089) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

OT Vimpelinjoki 

#### Perustelut ehdotukselle   

Savonjoesta käytetään myös nimitystä Vimpelinjoki.
https://fi.wikipedia.org/wiki/Savonjoki
(Tämä kävi ilmi aineistossa 978-952-314-608-2 Vimpelinjoen tulvasuojelu ja kunnostus -hankkeen velvoitetarkkailu : väliraportti) 

#### Ehdottaja   

Tatja Pusa 

#### Ehdottajan sähköpostiosoite   

tatja.pusa@helsinki.fi

**Comment by mirmaid** [comment]
Lisätty
