### ISSUE TITLE
kielioppikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5967]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kielioppikirjat 

#### Perustelut ehdotukselle   

Ehdotettu alunperin muodossa kieliopit: ”YSA:sta löytyy jo kielioppi, mutta se viittaa kielen rakenteeseen. Ehdottamani termi "kieliopit" viittaisi julkaisutyyppiin, eli jonkin kielen rakenteen deskriptiiviseen (tai preskriptiiviseen) kuvaukseen. Koska kielioppi-genreen voi sisältyä myös esimerkiksi vähemmän tunnettujen kielten rakenteiden ensimmäisiä kuvauksia, jotka eivät ole suunnattu kielen opiskelijoille vaan esimerkiksi kielitypologeille, oppikirja-termi ei mielestäni kata tätä julkaisutyyppiä.” kielioppi - kieliopit -pari löytyy myös kta:sta. 
Muodossa kielioppikirjat erottuisi kuitenkin paremmin yksiköllisestä kielioppi-termistä. On genretermi, mutta kielioppikirjoja voidaan myös tutkia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan nimi:** Mirja Anttila 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [kielioppikirjat](http://finto.fi/yse/fi/page/Y505967)

**Comment by mariaforsen** [comment]
Sv. grammatikböcker

**Comment by mirmaid** [comment]
^ juu, muuten olisi "kielten oppikirjat".
