### ISSUE TITLE
asetelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5968]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asetelmat](http://www.yso.fi/onto/ysa/Y100862) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

asetelmat --> asetelmat (kuvataide) 

#### Perustelut ehdotukselle   

Ruotsiksi _stilleben_ ja englanniksi _still lives_. Melindassa sekä kuvataiteeseen liittyviä aineistoja että esim. kukka-asetelmista kertovia aineistoja, joille _stilleben_ ei sovi.
Esim.

- Tee inspiroivat asetelmat : rakkaat aarteet kauniisti näytille / Geraldine James ; suomennos: Sakari Hyrkkö.
- Flower arrangements : over 35 modern designs for simple floral table decorations / Julie Collins & Tina Parkes.

Jos käsite rajataan kuvataiteiden merkitykseen, voidaan muut käyttötapaukset ohjata esim. 
asetelmat (asettelu)  KÄYTÄ sommittelu 

#### Ehdottaja   

Satu Niininen / Yso-kokous 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mariaforsen** [comment]
YSAssa kukkien asettelu=blomsterarrangemang /Allärs

**Comment by YSA-kokous** [comment]
asetelmat (kuvataide)
