### ISSUE TITLE
urkujen rekisteröinti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5969]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

urkujen rekisteröinti 

#### Ehdotettu termi englanniksi   

organ registration 

#### Ehdotettu termi ruotsiksi   

orgelregistrering 

#### Vaihtoehtoiset termit ja ilmaisut   

urkurekisteröinti 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikin tulkinta](http://www.yso.fi/onto/yso/p29842) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85095460> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

MUSAn vanha asiasana "rekisteröinti" kattaa nimenomaan tämän merkityksen, ja YSAssa vanhastaan olevan samanmuotoinen asiasana tarkoittaa muuta, joten pitää ottaa itsenäisenä asiasanana tämä. 

#### Tarkoitusta täsmentävä selite   

Urkujen äänikertojen valinta säveltäjän tai sovittajan antamien rekisteröintiohjeiden tai soittajan oman mielen mukaan. Kyseessä siis urkumusiikin tulkinnan keskeinen osa-alue. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1477022 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [urkujen rekisteröinti](http://finto.fi/yse/fi/page/Y505969)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan	
KT rekisteröinti (urut)
KT rekistreeraus
Määritelmä: Urkujen äänikertojen valinta säveltäjän tai sovittajan antamien rekisteröintiohjeiden tai soittajan oman mielen mukaan.
