### ISSUE TITLE
anthemit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5970]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

anthemit 

#### Ehdotettu termi englanniksi   

anthems 

#### Ehdotettu termi ruotsiksi   

anthemer (?) 

#### Vaihtoehtoiset termit ja ilmaisut   

full anthems 
verse anthems 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sävellykset](http://www.yso.fi/onto/yso/p1515) 

#### Assosiatiiviset (RT)   

[hengellinen musiikki](http://www.yso.fi/onto/yso/p8500) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85005524> 
Wikidata : https://www.wikidata.org/wiki/Q541947 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Grove Music Online: "A choral setting of a religious or moral text in English, generally designed for liturgical performance. - - His [Byrd's] full anthems -- many of these were intended for devotional use in the home rather than in the liturgy." [https://doi.org/10.1093/gmo/9781561592630.article.00998] 

#### Perustelut ehdotukselle   

Tarvitaan sekä YSAan että SLM:ään; kyseisille teoksille ei ole vanhastaan sopivaa asiasanaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1575278 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [anthemit](http://finto.fi/yse/fi/page/Y505970)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan, määritelmä lisätään, myös SLM-sanastoon

**Comment by mirmaid** [comment]
https://www.youtube.com/watch?v=iB8xGaXhtnk

**Comment by mariaforsen** [comment]
Sv. anthems (SAO)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Anthem

Suomeksikin käytetty laajemmin kuin Groven määritelmän merkityksessä, en sitten tiedä tulisiko kuvailussa sekaannuksia.

**Comment by jtuohini** [comment]
Groven artikkeliin pohjautuva ehdotus määritelmäksi: "Englanninkielinen, tekstiltään uskonnollinen tai moraalinen kuorosävellys, joka on sävelletty joko osaksi anglikaanisen kirkon liturgiaa tai yksityistä hartaudenharjoitusta varten."

**Comment by ksornova** [comment]
Muusa (15.5.2018): määritelmä ok
