### ISSUE TITLE
neumit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5972]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[neumit](http://www.yso.fi/onto/ysa/Y140809) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "neumikirjoitus", KT "neumit". 

#### Perustelut ehdotukselle   

Nykyinen asiasana on harhaanjohtaja kuvatakseen nuottikirjoitustapaa; analogia: "mensuraalinuottikirjoitus", "tabulatuurinuottikirjoitus". 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by SamuVirokannas** [comment]
Olisiko tarpeen lisätä ohjaustermiksi myös neuminotaatio?

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan
KT neuminotaatio

**Comment by mariaforsen** [comment]
Sv. neumskrift ET neumer, neumnotation
