### ISSUE TITLE
oodit (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5973]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oodit (sävellykset) 

#### Ehdotettu termi englanniksi   

odes (compositions) 

#### Ehdotettu termi ruotsiksi   

oder (kompositioner 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sävellykset](http://www.yso.fi/onto/yso/p1515) 

#### Assosiatiiviset (RT)   

[laulumusiikki](http://www.yso.fi/onto/yso/p769) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Tarkoitusta täsmentävä selite   

Grove Music Online: "In the 17th and 18th centuries a cantata-like form called ‘ode’ was cultivated as a form of panegyric to the English monarch, and it eventually also became a standard part of the annual celebrations of St Cecilia’s Day. Neither these odes nor subsequent musical ‘odes’ have any relation to the form or metres of classical models, although most share a tendency to celebrate particular events, places or men, as did most Greek odes. - - The ode hardly lends itself to precise definition as a musical genre in the 19th and 20th centuries. That is partly because poets themselves have not always been discriminating in their use of the term (there is no obvious reason, for example, why Keats’s To a Nightingale should be called an ode while Shelley’s To a Skylark is not), and also because during that period there was no unbroken tradition like that of the English court ode." [https://doi.org/10.1093/gmo/9781561592630.article.50067] 

#### Perustelut ehdotukselle   

Kyseessä MUSA-asiasanaston vanha asiasana [http://www.yso.fi/onto/musa/p66180], jota ei ole voitu suoraan sulauttaa YSAn nykyiseen, erisisältöiseen "oodit"-asiasanaan 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [oodit (sävellykset)](http://finto.fi/yse/fi/page/Y505973)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan

**Comment by mariaforsen** [comment]
Sv. oden (kompositioner)
