### ISSUE TITLE
oodit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5974]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oodit](http://www.yso.fi/onto/ysa/Y103770) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "oodit (runot)" 

#### Perustelut ehdotukselle   

Ks. https://github.com/Finto-ehdotus/YSE/issues/5973 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan termin muuttamista

**Comment by mariaforsen** [comment]
Sv. oden (dikter)
