### ISSUE TITLE
seuratanssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5976]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seuratanssit](http://www.yso.fi/onto/ysa/Y104311) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi muotoon "seuratanssi". 

#### Perustelut ehdotukselle   

Asiasana viittaa seuratanssiin ennemmin (sosiaalisena) ilmiönä kuin tämän ilmiön parissa tanssittuihin yksittäisiin tansseihin, jotka voidaan kuvailla sanastossa jo olevilla tanssilajeja kuvaavilla "tanssit"-asiasanan [http://www.yso.fi/onto/ysa/Y99309] alakäsitteillä. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjassa kuitenkin: seuraelämässä ja huvitilaisuuksissa tanssittavia tansseja. _Tango, valssi ym. seuratanssit._ 

Myös yksikköä käytetään: https://tanssija.wordpress.com/2010/01/28/mita-on-seuratanssi/, http://www.sekahaku.net/tanssitietoa/seuratanssi-terveysliikuntaa, https://www.tanssit.fi/seuratanssin-sm-kisat-24-3-2018-hotelli-tallukassa/
