### ISSUE TITLE
klaveeri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5977]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[klaveeri](http://www.yso.fi/onto/ysa/Y109295) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "klaveerisoittimet" (vaihtoehtoisesti "klaverisoittimet") tai vielä mieluummin täsmällisemmäksi "kielikosketinsoittimet" 

#### Perustelut ehdotukselle   

Yksiköstä huolimatta kyseessä ei ole yksittäinen soitintyyppi, vaan laajempi soitinperhe, johon kuuluvat kaikki sellaiset kosketinsoittimet, joissa ääni syntyy kielen värähtelystä (cembalo, klavikordi, piano ja tangenttipiano alalajeineen). Englanniksi ryhmän nimenä on tieteellisessä kirjoittelussa 'stringed keyboard instrument' ja saksaksi 'besaitete Tasteninstrumente' ja 'Saitenklaviere'. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by asormune** [comment]
Kannatan termiä klaveerisoittimet

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan termiä klaveerisoittimet
KT klaverisoittimet ja KT kielikosketinsoittimet

**Comment by mariaforsen** [comment]
Sv. klaverinstrument
