### ISSUE TITLE
balladit (kansanlaulut)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5978]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

balladit (kansanlaulut) 

#### Ehdotettu termi ruotsiksi   

ballader (folksånger) 

#### Ehdotettu termi englanniksi   

ballads (folk songs) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansanlaulut](http://www.yso.fi/onto/yso/p2842) 

#### Assosiatiiviset (RT)   

[balladit](http://www.yso.fi/onto/yso/p15007) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85011228> 

#### Tarkoitusta täsmentävä selite   

Grove Music Online: "Term used for a short popular or traditional song that normally frames a narrative element." [https://doi.org/10.1093/gmo/9781561592630.article.01879] 

#### Perustelut ehdotukselle   

Nykyinen YSA-asiasana kattaa useita eri asioita, joista kaikista kuitenkin käytetään (puhekielessä) yhtä ja samaa balladi-sanaa. — Vastine SLM-sanastoa, jossa nyt "balladit (musiikki)" [http://urn.fi/URN:NBN:fi:au:slm:s437], ajatellen LCGFT:ssa "Ballads" [http://id.loc.gov/authorities/genreForms/gf2014026648] 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.362662 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [balladit (kansanlaulut)](http://finto.fi/yse/fi/page/Y505978)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan muotoa balladit (kansanlaulut)
lisäksi KT kansanballadit

**Comment by mariaforsen** [comment]
Sv. ballader (folkvisor)

**Comment by mariaforsen** [comment]
Sv. ballader (folkvisor)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5979 palautettu Muusan käsittelyyn

**Comment by mirmaid** [comment]
Toteutettu balladit (laulut). Lisätäänkö ohjaustermi kansanballadit ja RT kansanlaulut (YSO/SLM)?

**Comment by krinay** [comment]
Voisiko myös lisätä ryhmän 50?

**Comment by mirmaid** [comment]
^ ok

**Comment by mirmaid** [comment]
Tuleeko tälle Muusalta määritelmä?

**Comment by MUUSA-kokous** [comment]
Määritelmä: "Kertova kansanlaulun laji".

**Comment by mirmaid** [comment]
Määritelmä olikin jo lisätty issueen https://github.com/Finto-ehdotus/YSE/issues/5979. Toteutettu sanastoihin sen mukaan.
