### ISSUE TITLE
balladit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5979]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[balladit](http://www.yso.fi/onto/ysa/Y101000) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "balladit (runot)" ja poistetaan RT "kansanlaulut" (korvataan myöhemmin RT "balladit (kansanlaulut)", jos se vastaavasti tulee hyväksytyksi YSAan) 

#### Perustelut ehdotukselle   

Nykyinen YSA-asiasana viittaa useaan asiaan (kuten YSAan yhdistetty osin vastaava asiasanahirvitys [http://www.yso.fi/onto/musa/p393]); kansanballadien osalta ks. https://github.com/Finto-ehdotus/YSE/issues/5978 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by jtuohini** [comment]
SLM-sanastossa on jo [**balladit (kirjallisuus)**](http://urn.fi/URN:NBN:fi:au:slm:s437_1).

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan ryhmän 89 poisottamista ja nykyisen RT:n "kansanlaulut" korvaamista RT:llä  "balladit (kansanlaulut)"

**Comment by krinay** [comment]
Ymmärsinkö oikein, että YSAan tulisi ehdotuksen mukaan kaksi termiä: balladit (kirjallisuus) ja balladit (kansanlaulut)? Ovatko termit tosiaan merkitykseltään niin erilaisia, että kahdelle termille on tarvetta? Aika usein pitäisi sisällönkuvailussa varmaan käyttää molempia termejä.

Kielitoimiston sanakirja:
balladi  "määrätyyppinen kertovasisältöinen laulu t. (kansan)runo. Ritariballadi. "
balladirunous "eeppisen t. lyyrisen kansanrunouden ja taiderunouden lajista, joka kuvaa us. traagisia ihmiskohtaloita. Suomen keskiaikainen balladirunous. Romantiikan ja uusromantiikan balladirunous."

Ks. myös Tieteen termipankki:
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:balladi
http://tieteentermipankki.fi/wiki/Folkloristiikka:balladi
LCSH: http://id.loc.gov/authorities/subjects/sh85011228.html

**Comment by jtuohini** [comment]
Myöhemmin tulisi vielä jokin termi, jolla kuvailla soitinmusiikin piiriin kuuluvia balladeja.
 
Tietysti yksi tapa olisi jättää termi **balladit** viittaamaan tekstipuoleen ja ilmaista kahden termin yhdistelmällä, millaisesta balladista on kyse: esim. **balladit** + **kansanlaulut** tai **balladit** + **rekilaulut** tai **balladit** + **yksinlaulut** tai **balladit** + **orkesterilaulut** jne. (kumpikin termi siis omassa 650/655-kentässään sen mukaan, onko kyse balladeista vai sitä käsittelevästä aineistosta). Jäljelle jäisi sitten enää soitinmusiikkipuoli, jossa ei olisi tuota nykyisen termin yhteyttä runouteen.

**Comment by YSA-kokous** [comment]
Palaa Muusan käsittelyyn.

**Comment by tpalonen** [comment]
Sekoitan vielä soppaa sen verran, että MUSAn balladit-termin Melinda-käyttöä silmäillessä huomaa, että merkittävä osa kuvailusta liittyy pop/rock-balladeihin, joita ei tässä keskustelussa ole vielä lainkaan huomioitu.
Esim. "Pop ballads : 16 famous songs. 2 / arranged by Carsten Gerlitz."

**Comment by MUUSA-kokous** [comment]
Muusa pohtii vielä tätä. Ongelmana on edellisen keskustelun lisäksi se, että taidemusiikissa balladit voi olla sekä laulettua että instrumentaalimusiikkia.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Power_ballad - _voimaballadit_ (?)

**Comment by YSA-kokous** [comment]
Seuraava kokous
Kristiina ja Muusa-ryhmä selvittävät tahoillaan.

**Comment by tpalonen** [comment]
Ysa-Muusa-kokouksessa oltiin jo lähellä ratkaisua.
_balladit (soitinmusiikki)_ JA _balladit (laulut)_
Tässä ratkaisussa _balladit (laulut)_ sisältäisi taidemusiikin lauletut balladit ja popmusiikin balladit. Instrumentaaliset pop-balladit ovat marginaalinen ilmiö, ei tarvitse problematisoida sen puolesta. Ratkaisematta tässä ehdotuksessa vielä jäi, voitaisiinko perinteentutkimuksen puolella pärjätä tällä "balladit (laulut)"-käsitteellä olettaen että kaikkia tyydyttävä termimuoto löytyisi; perinteentutkimuksessa ollaan kiinnostuneita erityisesti laulujen lyriikkapuolesta. Vai tarvittaisiinko vielä kolmas käsite, esim. balladit (kansanlaulut)/balladirunous tms.

**Comment by krinay** [comment]
Balladit (laulut) sopii kyllä myös perinteentutkimuksen puolelle, mutta vielä pitää selvittää kirjallisuudentutkimuksen näkökulma.

Olisiko tämä liikaa:
balladit (soitinmusiikki)
balladit (laulut) - (sis. kansanlaulut, taidelaulut ja pop-balladit yms.)
balladit (kirjallisuus) - (sis. nimeltä tunnettujen kirjailijoiden runomuotoiset taideballadit ja tarvittaessa balladeina pidettävät proosateoksetkin, esim. Timo K. Mukan _Maa on syntinen laulu: balladi_, ks. http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:balladi)

**Comment by tpalonen** [comment]
Em. ehdotukseen viitaten, jos aineisto käsittelisi kansanlaulua lyriikkana, tekstinä, esim. _Elinan surma_, niin kumpaa silloin pitäisi käyttää kuvailussa, balladit (laulut) vai balladit (kirjallisuus)? Onko rajanveto selvä? @krinay

**Comment by krinay** [comment]
Kansanlaulun tekstiä tutkivan aineiston yhteydessä käyttäisin kyllä asiasanaa balladit (laulut). Myös sanat sisältyvät lauluun.

Mutta ei rajanveto taida olla selvä. Balladit (sanataide) ei taitaisi olla sen parempi? Tieteen termipankissa käytetään selitystekstissä yhdyssanoja kansanballadit ja taideballadit, mutta kumpikaan niistä ei liene vakiintunut käyttöön sellaisenaan.

En tiedä, onko ylipäätään välttämätöntä erottaa toisistaan balladit (laulut) ja balladit (kirjallisuus/sanataide tms.). Ehkä kontekstin saa esille muulla kuvailulla. Mutta en keksi niille yhteistä tarkennetta erottamaan ne soitinmusiikin balladeista.
@tpalonen

**Comment by jtuohini** [comment]
Ongelma liittyy osin termihierarkiaan: "balladit (laulut) LT laulut" (balladit ovat yhdenlaisia lauluja) ei stemmaa ollenkaan, jos olisi kirjallisuuden ja musiikin kattava yhteinen termi.

**Comment by jtuohini** [comment]
Ja vastaukseksi Tuomakselle: hyvinkin näkisin jonkun käyttävän yhdistelmää _balladit (laulut)_ ja _laululyriikka_: kyse tietynlaisten laulujen sanoituksesta, ei niinkään ei-musiikillisista balladeista, johon taas miellän tuon _balladit (kirjallisuus)_ -asiasanan viittaavan.

**Comment by tpalonen** [comment]
PÄÄTÖS:
Muusa kannattaa, että YSOssa olisi erillinen käsite, joka viittaa balladeihin soitinmusiikkina taidemusiikin kontekstissa. Tälle ehdotetaan termiksi "balladit (soitinmusiikki)" ja LT:ksi sävellykset ja RT:ksi soitinmusiikki ja taidemusiikki. Toisessa balladit-käsitteessä tällöin yhdistyisi kansanlaulujen, populaarimusiikin sekä taidemusiikin laulua sisältävien balladien merkitys. Balladit (kirjallisuus) -käsitteen tarpeellisuuteen emme ota kantaa. Todettiin, että pop-balladeja ei ole tällä erää tarve erottaa omaksi käsitteekseen, koska pop-balladit saattavat esim. pohjata kansalauluballadeihin tai olla muutoin niiden kaltaisia eli käsitteet kansalauluballadit ja popballadit ovat jossain määrin päällekkäiset. Asiaan voidaan palata, jos esim. käyttäjät kaipaavat erillistä popballadit-käsitettä.

**Comment by krinay** [comment]
Balladit (kirjallisuus) lienee tarpeellinen sisällönkuvailtaessa tutkimusta, joka käsittelee taideballadeja, esimerkiksi tiettyjä Eino Leinon, Larin-Kyöstin, Hellaakosken tai Aale Tynnin runoja tai Aino Kallaksen proosaballadeja. Tai vaikka Satu Grünthalin väitöskirjaa _Välkkyvä sillan kalvo: suomalaisten kaunokirjallisten balladien motiivit_.

Laulujen ja kaunokirjallisten balladien välistä eroa on joskus hankala hahmottaa, mutta taidan silti kallistua kannattamaan kaikkien kolmen käsitteen ottamista:
balladit (kirjallisuus) tai balladit (kaunokirjallisuus)
balladit (laulut)
balladit (soitinmusiikki).

**Comment by YSA-kokous** [comment]
balladit (kirjallisuus)
balladit (laulut)
balladit (soitinmusiikki)

**Comment by mariaforsen** [comment]
Sv. 
ballader (litteratur)
ballader (sånger) ET ballader (vokalmusik) 
ballader (instrumentalmusik)

**Comment by tpalonen** [comment]
Ehdotus määritelmäksi käsitteelle _balladit (laulut)_: "Musiikkikappale, jossa on keskeistä kerronnallinen sisältö tai sentimentaalinen tunnelma."

**Comment by tpalonen** [comment]
Ehdotus määritelmäksi käsitteelle _balladit (soitinmusiikki)_, laatinut @jtuohini : "”Länsimaisen taidemusiikin piiriin kuuluva yhdelle tai useammalle soittimelle, yleensä pianolle tai orkesterille, sävelletty luonteeltaan kertova teos.”

**Comment by jtuohini** [comment]
"Musiikkikappale" on hieman halveeraavan kuuloinen verrattuna "sävellys"-sanaan. Vaan olisiko lauluballadeille yksinkertaisempi kerrassaan "Laulu, jossa keskeistä on kerronnallinen sisältö tai sentimentaalinen tunnelma."

**Comment by asormune** [comment]
Aiemmin tuolla ylempänä on sovittu, että lauletut popballadit menevät termin "balladit (laulut)" alle. Meneekö sinne myös (laulettu) jazzballadi? Entä instrumentaaliset jazzballadit. Jaakko on määritelmässään rajannut käsitteen "balladit (soitinmusiikki)" vain taidemusiikkiin.

**Comment by tpalonen** [comment]
Joo, musiikkikappale-sanan voisi toki vaihtaa. Kannattaisin sävellystä sen korvaajana (koska balladit voivat olla myös instrumentaaleja ja laulu taas antaa ymmärtää että sisältää laulamista), ja näin ollen  määritelmä olisi: "Sävellys, jossa keskeistä on kerronnallinen sisältö tai sentimentaalinen tunnelma."

**Comment by tpalonen** [comment]
balladit (soitinmusiikin) rajaus taidemusiikkiin tuli esiin jo aiemmissa kokouksissa, ei niinkään määritelmän laatimisvaiheessa. Jazzbaladien pitäisi minun tulkintani mukaan sisältyä tuohon "balladit (laulut)"-käsitteeseen. Siteeraan aiempaa kommenttiani tässä ketjussa, joka on siis Muusa-ryhmän kokousmuistiinpano: "Todettiin, että pop-balladeja ei ole tällä erää tarve erottaa omaksi käsitteekseen, koska pop-balladit saattavat esim. pohjata kansalauluballadeihin tai olla muutoin niiden kaltaisia eli käsitteet kansalauluballadit ja popballadit ovat jossain määrin päällekkäiset. Asiaan voidaan palata, jos esim. käyttäjät kaipaavat erillistä popballadit-käsitettä."

**Comment by krinay** [comment]
> 
> 
> Joo, musiikkikappale-sanan voisi toki vaihtaa. Kannattaisin sävellystä sen korvaajana (koska balladit voivat olla myös instrumentaaleja ja laulu taas antaa ymmärtää että sisältää laulamista), ja näin ollen määritelmä olisi: "Sävellys, jossa keskeistä on kerronnallinen sisältö tai sentimentaalinen tunnelma."

Kannatan Jaakon ehdotusta ("Laulu, jossa keskeistä on kerronnallinen sisältö tai sentimentaalinen tunnelma."). Mm. kansanballadit istuvat siihen paremmin.

**Comment by mirmaid** [comment]
SLM samoin kuin YSO.

**Comment by mirmaid** [comment]
balladit (laulut): onko lopullinen määritelmä _Laulu, jossa keskeistä on kerronnallinen sisältö tai sentimentaalinen tunnelma._ (YSO & SLM)

Onko SLM-termin LCGFT-vastine http://id.loc.gov/authorities/genreForms/gf2014026648?

**Comment by tpalonen** [comment]
Homma lähes taputeltu, mutta Muusan kanta kaivattaisiin vielä seuraaviin ohjaustermiehdotuksiin, jotka toivottavasti selventäisivät omalta osaltaan käsitteiden merkityseroa:

taideballadit KÄYTÄ balladit (kirjallisuus)
kansanballadit KÄYTÄ balladit (laulut)
pop-balladit KÄYTÄ balladit (laulut)
rock-balladit KÄYTÄ balladit (laulut)

**Comment by MUUSA-kokous** [comment]
Muusan ehdottama muutos määritelmään: "Laulu, joka on tyypillisesti sentimentaalinen ja kerronnallinen."

Muusa kannattaa ohjaustermiehdotuksia.

**Comment by mirmaid** [comment]
Entä LCGFT-vastine?

**Comment by mirmaid** [comment]
_Balladit (kirjallisuus)_: suhteet ja määritelmä yhdenmukaistettava YSO-SLM. LCGFT ja LCSH -vastineet vielä tarkistettava. LT runot/tarkista. Ei linkitystä.

_Balladit (soitinmusiikki)_: muutokset toteutettu.
_Balladit (laulut)_: muutokset toteutettu tämän issuen mukaan, LCGFT ja LCSH -vastineet vielä tarkistettava. http://id.loc.gov/authorities/genreForms/gf2014026648.html - määritelmältään suppeampi, tehdäänkö linkitys? - ExactMatch ok.
