### ISSUE TITLE
intonaatiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5980]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

intonaatiot 

#### Ehdotettu termi englanniksi   

intonations 

#### Ehdotettu termi ruotsiksi   

intonationer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[laulut](http://www.yso.fi/onto/yso/p2371) 

#### Assosiatiiviset (RT)   

[gregoriaaninen laulu](http://www.yso.fi/onto/yso/p6553) 

#### Tarkoitusta täsmentävä selite   

Grove Music Online: "In plainchant, the initial melodic phrase usually sung solo by the priest or cantor before the other voices enter." [https://doi.org/10.1093/gmo/9781561592630.article.13868] 

#### Perustelut ehdotukselle   

Kyseessä on YSAaan sulautetun MUSAn "intonaatio"-asiananan kattamista merkityksistä neljäs, jolle ei löydy parempaakaan vastinetta. – Sama tarvitaan myös SLM-sanastoon! 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [intonaatiot](http://finto.fi/yse/fi/page/Y505980)

**Comment by tpalonen** [comment]
Onko todella tarvetta näin spesifiselle käsitteelle? Melindan tietueista yksikään "intonaatio (musa)":lla kuvailluista ei tuntunut viittaavan tähän merkitykseen.

**Comment by jtuohini** [comment]
Ehkä enemmän tarvetta SLM:n puolella: on valtava määrä kirkkomusiikkia sisältäviä äänitteitä, joissa näitä intonaatioita löytyy (tunnetuimpana "Deus in adiotorium meum intende", josta pari varianttia esimerkiksi: tutuimpana [säestyksettä](https://www.youtube.com/watch?v=nWgD2SUHCxY), [urkusäestyksellä](https://www.youtube.com/watch?v=n4F-OL_WfFo), [hieman harvinaisemmalla melodialla](https://www.youtube.com/watch?v=__-u82_8Ld8)).

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan termin ottamista SLM-sanastoon, ei YSAan

**Comment by mariaforsen** [comment]
Sv.  intonationer (sånger) -tämä tarkenne jos tosiaan viittaa vain laulettuihin intonaatioihin (ei uruilla tms.)

**Comment by mirmaid** [comment]
Samoin suomeksi. Toisaalta jos on (suuria määriä) aineistoja joiden kuvailussa tarvitaan tiettyä lajityyppitermiä, kuulostaa siltä että ko. termin pitäisi olla tarpeen myös aiheena. Jos taas ko. genren ollessa tutkimuskohteena käytettäisiin jotain muuta termiä (?), eikö sama riitä myös genreksi?

**Comment by tpalonen** [comment]
Muusa siis ei kannata tämän ottamista YSAan. Enkä itsekään kannata.

**Comment by YSA-kokous** [comment]
Genresanasto

**Comment by jtuohini** [comment]
Ja määritelmä voisi olla suomeksi (jälleen Grovea hyödyntäen): "Kanttorin tai papin laulama lyhyt sävelmä, joka edeltää laajempaa, yleensä kuorolle sävellettyä vokaaliteosta."

**Comment by jtuohini** [comment]
Nuo intonaatiot ovat aika vakiintuneita, ja nimenomaan gregoriaanistyyppistä laulua, joten ainakaan koraalialkusoitot yms. eivät sovi tuolla kuvailtavaksi. Mutta jos ja kun joku soittaa uruilla intonaatiosävelmän... Toisaalta: jos termin LT-suhteena on _laulut_ tms, niin ei pitäisi tulla sen suhteen määrittelyongelmaa (vrt. joku soittaa uruilla jonkin satunnaisen laulun: kuvailtaisiinko se SLM-termillä _laulut_ vai _soolot_?).

**Comment by mirmaid** [comment]
Jaakko: Voisihan siinä olla sulkutarkennekin, esim. intonaatiot (kirkkomusiikki)

**Comment by mirmaid** [comment]
Saisiko tähän vielä Muusan päätöksen, lisätäänkö SLM-sanastoon ja millä tarkenteella?

MUSAn alkuperäinen määritelmä: intonaatio: (4) katolisessa liturgiassa kanttorin laulama sävellyksen alku.

Jaakon määritelmä: "Kanttorin tai papin laulama lyhyt sävelmä, joka edeltää laajempaa, yleensä kuorolle sävellettyä vokaaliteosta."

Ehdotettuja tarkenteita _(laulut), (kirkkomusiikki)_.

**Comment by jtuohini** [comment]
Muusa-kokous 4.10.2019: päätettiin ottaa SLM-sanastoon muodossa **intonaatiot (kirkkomusiikki)**, LT _kirkkomusiikki_ ja _laulut_. Määritelmä "Laulettu lyhyt soolosävelmä, joka edeltää laajempaa, yleensä kuorolle sävellettyä kirkollista vokaaliteosta."
