### ISSUE TITLE
intonaatio (musiikki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5981]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

intonaatio (musiikki) 

#### Ehdotettu termi ruotsiksi   

intonation (musik) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2001006375> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Grove Music Online: "The treatment of musical pitch in performance. It is usually thought of as the acoustical and artistic accuracy of pitch in singing or playing, but it has an indispensable role in musical expression through the deliberate inflection of pitch to shade and colour melody, to create excitement or tension, or as a means of characterizing a particular repertory or style of performance." [https://doi.org/10.1093/gmo/9781561592630.article.53762] 

#### Perustelut ehdotukselle   

Kyseessä on YSAaan sulautetun MUSAn "intonaatio"-asiananan kattamista merkityksistä ensimmäinen, jolle ei löydy parempaakaan vastinetta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [intonaatio (musiikki)](http://finto.fi/yse/fi/page/Y505981)

**Comment by ksornova** [comment]
Tarkenne "musiikki" on varmaan ihan hyvä, mutta lisäykseksi voisi harkita myös "sävelkorkeus" tai "säveltaso" LC:n tapaan.

**Comment by asormune** [comment]
Pitäisikö ohjaustermiksi ottaa vielä "sävelpuhtaus":
Foneettisena käsitteenä intonaatio tarkoittaa puhemelodiaa, mutta musiikissa intonaatio viittaa säveltasojen valintaan.  On kysymys sävelpuhtaudesta, kuitenkin sillä varauksella, ettei yksiselitteistä puhtautta ole olemassa. Intonaatio on myös musikaalinen valinta (http://www2.siba.fi/intonaatio/index.php?id=4&la=fi)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan
KT sävelpuhtaus
