### ISSUE TITLE
intonaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5982]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[intonaatio](http://www.yso.fi/onto/ysa/Y95569) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "intonaatio (aksentti)" tai "intonaatio (kielitiede)" 

#### Perustelut ehdotukselle   

Nykyinen YSA-asiasana tarvinnee sulkutarkenteen tms, jahka MUSAsta tulevat monimerkityksisen intonaatio-sanan tarkoittamat muut asiasanat päätyvät sanastoon, ks. https://github.com/Finto-ehdotus/YSE/issues/5980 ja https://github.com/Finto-ehdotus/YSE/issues/5981. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by ksornova** [comment]
Harkita voi myös muotoa "intonaatio (fonetiikka)"?

**Comment by tpalonen** [comment]
Jos toinen käsite on "intonaatio (musiikki)" niin eikö tähän riittäisi sulkutarkenteeksi **"intonaatio (puhe)"**? Olisi varmaankin riittävän selkeä tekemään eron musiikki-käsitteeseen ja intuitiivisempi kuin kielitiede tai fonetiikka.

**Comment by YSA-kokous** [comment]
intonaatio (puhe)
