### ISSUE TITLE
sävelmotiivit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5983]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sävelmotiivit 

#### Ehdotettu termi englanniksi   

musical motifs 

#### Ehdotettu termi ruotsiksi   

tonmotiv 

#### Vaihtoehtoiset termit ja ilmaisut   

musical motives [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikkianalyysi](http://www.yso.fi/onto/yso/p19623) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q908349 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Grove Music Online: "A short musical idea, melodic, harmonic, rhythmic, or any combination of these three. A motif may be of any size, and is most commonly regarded as the shortest subdivision of a theme or phrase that still maintains its identity as an idea. It is most often thought of in melodic terms, and it is this aspect of motif that is connoted by the term ‘figure’." [https://doi.org/10.1093/gmo/9781561592630.article.19221] 

#### Perustelut ehdotukselle   

Vastaa YSAan sulautetun MUSAn "motiivit"-asiasanaa [http://www.yso.fi/onto/musa/p444], jota ei voi yhdistää YSAn nykyiseen, monimerkityksiseen "motiivit"-asiasanaan [http://www.yso.fi/onto/ysa/Y97511]. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [sävelmotiivit](http://finto.fi/yse/fi/page/Y505983)

**Comment by asormune** [comment]
"musical motif/motives" = musical idea, melodic, harmonic, rhythmic, or any combination of these. Eikö tämä ole laajempi termi kuin "sävelmotiivit". Olisiko suomenkieliseksi termiksi parempi: "motiivi (musiikki)" tai "motiivit (musiikki)"?

**Comment by jtuohini** [comment]
_Motiivit (musiikki)_ -muotoisen asiasanan ottaminen tarkoittaisi, että YSAn nykyinen [**motiivit**](http://www.yso.fi/onto/ysa/Y97511)-asiasana vaatisi myös sulkutarkenteen ja mahdollisen jakamisen useammaksi (motiivi krjallisuudessa, rikoksen motiivi jne). "Sävelmotiivi"-sanaa näyttää joka tapauksessa käytetyn tarkoittamaan kaikenlaisia musiikillisia motiiveteja, olipa kyse harmonisista tai rytmisistä (kaikki kuitenkin lopulta on säveliä, siis musiikkia eli säveltaidetta).

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan ehdotusta
sävelmotiivit
KT motiivit (musiikki)
LT musiikkianalyysi
määritelmä: Musiikinteoreettinen käsite, jolla tarkoitetaan pienintä musiikillisesti mielekästä sävelkulkua, aihetta tms elementtiä. Useasta motiivista muodostuu teema.

YSO-hierarkkiaa voisi pohtia myöhemmin

**Comment by mariaforsen** [comment]
melodiska motiv ET motiv (musik), tonmotiv
