### ISSUE TITLE
goottirock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5984]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

goottirock 

#### Ehdotettu termi ruotsiksi   

goth rock 

#### Ehdotettu termi englanniksi   

goth rock (tai gothic rock music) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[punk rock](http://www.yso.fi/onto/yso/p29762) 
[punk rock](http://www.yso.fi/onto/yso/p29762) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2002002865.html  termi: Gothic rock music> 
Wikipedia : https://fi.wikipedia.org/wiki/Goottirock 
BnF, Ranskan kansalliskirjasto : <http://data.bnf.fr/13509063/rock_gothique/> 
kungl. biblioteket : <http://www.kb.se/katalogisering/Svenska-amnesord/ -> hakusana goth rock> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Harlots of Beyond -yhtyeen äänitteet. Suomalaisista yhtyeistä myös mm. Musta Paraati -yhtyeen kuvailuun goottirock olisi informatiivisempi kuin pelkkä rock. 

#### Tarkoitusta täsmentävä selite   

Yläkäsitteeksi sopisi punk rock, koska historiallisesti goottirock kehittyi punkista ja sitä luonnehditaan post-punk -tyyliksi. Vaihtoehtoisesti yläkäsite voisi olla myös rock. Musiikillisesti goottirock on yhtäältä omaleimaisempaa kuin geneerinen rock ja toisaalta monisyisempää ja kokeilevampaa kuin perus-punk. Goottirock määrittyy kuitenkin ennen kaikkea sanoituksen aihepiirien kautta (introspektiivisyys, kauhuromantiikan aiheet, synkkyys - vrt. punk rockin ulospäin suuntautunut kantaaottavuus ja aggressiivisuus). 

#### Perustelut ehdotukselle   

YSA:ssa gothic metal on yksi heavy rockin ohjaustermeistä, mutta (kaikki) goottirock ei ole heviä. YSA tuntee kyllä goottikulttuurin, mutta musiikille ei ole vielä omaa termiään. Hakusanalla goottirock tulee Finnassa 326 osumaa. 

**Ehdottajan nimi:** Samu Virokannas 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** samu.virokannas@helsinki.fi **Termiehdotus Fintossa:** [goottirock](http://finto.fi/yse/fi/page/Y505984)

**Comment by ksornova** [comment]
Muusa-ryhmä (20.4.2018): kannatetaan (sekä YSAan että SLM-sanastoon) 
RT goottikulttuuri
btw: goottikulttuurin KT:ksi myös gootit (osakulttuurit)
