### ISSUE TITLE
sfäärien harmonia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5986]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sfäärien harmonia 

#### Ehdotettu termi ruotsiksi   

sfärernas harmoni 

#### Ehdotettu termi englanniksi   

cosmic harmony, harmony of the spheres, music of the spheres, musica universalis, universal music 

#### Vaihtoehtoiset termit ja ilmaisut   

maailmankaikkeuden harmonia, sfäärien musiikki 

#### Ehdotettu yläkäsite YSOssa (LT)   

[harmonia](http://www.yso.fi/onto/yso/p15612) 
[musiikkifilosofia](http://www.yso.fi/onto/yso/p19358) 
[pythagoralaisuus](http://www.yso.fi/onto/yso/p16636) 

#### Assosiatiiviset (RT)   

[kosmologia](http://www.yso.fi/onto/yso/p7160) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85058969> 
SAO : Sfärernas harmoni 
Wikidata : https://www.wikidata.org/wiki/Q1478979 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Kyseiselle oppihistoriallisesti tärkeälle ja paljonkin tutkitulle juonteelle ei löydy ennestään sopivaa asiasanaa, eikä asiasanoja yhdistämälläkään saa riittävää osumatarkkuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3063152 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [sfäärien harmonia](http://finto.fi/yse/fi/page/Y505986)

**Comment by tpalonen** [comment]
Note-to-self: YSOn puolella yläkäsitteeksi sopinee parhaiten harmonia, tai ehkä mahdollisesti "teoriat (tuotokset)". Musiikkifilosofia ja pythagoralaisuus sopisivat RT:ksi.
