### ISSUE TITLE
siunaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5987]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[siunaukset](http://www.yso.fi/onto/ysa/Y121191) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetäänkö?  KÄYTÄ siunaus tai KT siunaus 

#### Perustelut ehdotukselle   

Käytetty suhteellisen vähän Melindassa ja suurimmassa osassa tapaukisista olisi "siunaus" ok (siunaus toimintana on myös kirjallisten siunausten ydin ja tarkoitus). 

Termi voi periaatteessa tarkoittaa myös "Jumalan suoma hyvyys, armo, varjelus, menestys tms.", mutta ei juuri käytetty Melindassa tässä merkityksessä ja vaatisi siinä tapauksessa kolmas (sulkutarkenteellinen) termi. 

Monikkomuoto sen sijaan ei toimi kaikissa tapauksissa, esim.: Parisuhdelain seuraukset kirkossa : piispainkokouksen selvitys kirkolliskokoukselle 2010 / Suomen evankelis-luterilaisen kirkon piispainkokous. 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Melindan ensimmäinen viite _Siunaus vai kirous: sinä valitset_ on juuri tätä "Jumalan suoma hyvyys, armo, varjelus, menestys tms." -merkitystä? Samoin _Abraham, blessing and the nations_.

**Comment by mirmaid** [comment]
Voisiko monikolta poistaa tarkenteen YSOssa tässä vaiheessa (merkitys on silti epämääräinen, mutta "tuotokset" ei myöskään erottele järkevällä tavalla). Yksikön ja monikon mahdolliseen yhdistämiseen voisi palata konversion jälkeen.

**Comment by YSA-kokous** [comment]
Poistetaan siunaukset-termin tarkenne YSOssa (?), seuraava kokous.
siunaus KÄ siunaaminen

**Comment by YSA-kokous** [comment]
Poistetaan siunaukset-termin tarkenne YSOssa. Jatketaan käsittelyä konversion jälkeen.

**Comment by mirmaid** [comment]
Käsittelyssä siis _siunaukset_: onko mahdollista yhdistää käsitteeseen _siunaaminen_, vai jääkö omana käsitteenään? Pitääkö merkitys "Jumalan suoma hyvyys, armo, varjelus, menestys tms" erottaa ihmisen tuottamista tai toimittamista "toivotuksista"?

Jos nämä yhdistetään, käytettäisiin mahdollisesti _siunaaminen_-käsitettä myös silloin, kun Jumala on siunannut.

**Comment by krinay** [comment]
https://melinda.kansalliskirjasto.fi/byid/009363085

LCSH:
Blessing and cursing http://id.loc.gov/authorities/subjects/sh85014846
Benediction http://id.loc.gov/authorities/subjects/sh85013121

**Comment by YSO-kokous** [comment]
Ei muutosta.
