### ISSUE TITLE
Kulutustavarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5988]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kulutustavarat 

#### Ehdotettu termi englanniksi   

Consumer commodities 

#### Ehdotettu termi ruotsiksi   

konsumtionsvaror 

#### Vastaava käsite muussa sanastossa   

Ohjaava käsite kulutustavarat YSOssa : https://finto.fi/yso/fi/search?clang=fi&q=kulutustavarat 
Wikipedia : https://fi.wikipedia.org/wiki/Kulutustavara 

#### Tarkoitusta täsmentävä selite   

Tuote/tavara, joka on tarkoitettu kuluttajien käyttöön. 

#### Perustelut ehdotukselle   

Tukes uudistaa tukes.fi-verkkosivunsa ja ottaa uudessa verkkosivustossa ontologiat käyttöön. Tässä yhteydessä olisi tarve saada nykyisin ohjausterminä YSOssa oleva kulutustavarat omaksi käsitteeksi, ei pelkästään ohjaavaksi termiksi. Tällä hetkellä YSOssa kulutustavarat on ohjaustermi hyödykkeille. Tukesissa hyödykkeillä ymmärretään, että ne voivat kattaa myös kuluttajille tarjottavia palveluja, ei siis vain tavaroita/tuotteita. Kulutustavaroihin viitataan myös kuluttajaturvallisuuslainsäädännössä.

Lisätietoa Tukesin nykyisillä verkkosivuilla (http://www.tukes.fi/fi/Toimialat/Kuluttajaturvallisuus/Kulutustavarat/):
"Kuluttajaturvallisuuslainsäädännön nojalla valvotaan mm. seuraavien tuotteiden turvallisuutta:
kuluttajakäyttöön ja urheiluun tarkoitetut henkilönsuojaimet (esim. kypärä ja heijastin) 
kuluttajakäyttöön tarkoitetut koneet (esim. ruohonleikkuri ja sähkötyökalut) 
lelut, lastenhoitotarvikkeet ja lapsiin vetoavat tuotteet 
Palovaaraa aiheuttavat tuotteet (esim. kynttilätuotteet, tulitikut ja tupakansytyttimet) 
Yleiset kulutustavarat (esim. urheiluvälineet, kylpytynnyrit, huonekalut, kaihtimet, tekstiilit ja tikkaat) "

Tukesissa kasvinsuojeluaineilla tarkoitetaan valmisteita, joita käytetään:
-	suojelemaan kasveja tai kasvituotteita kasvintuhoojalta (tuhoeläinten ja kasvitautien torjunta-aineet) 
-	tuhoamaan haitallisia kasveja tai kasvin osia tai estämään kasvien haitallista kasvua (rikkakasvien torjunta-aineet)
-	vaikuttamaan kasvien elintoimintoihin muulla tavoin kuin ravinteina (kasvunsääteet)
-	vaikuttamaan kasvituotteiden säilyvyyteen, jollei näihin aineisiin ja valmisteisiin sovelleta elintarvikelisäaineita koskevia erityissäännöksiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Uusi tukes.fi julkaistaan toukokuussa 2018, joten sen sisältö ei vielä ole julkinen. Tietosisällöltään vastaava paketti on nykyisillä verkkosivuilla http://www.tukes.fi/fi/Toimialat/Kuluttajaturvallisuus/Kulutustavarat/ . 

**Ehdottajan nimi:** Mirva Kipinoinen 
**Ehdottajan organisaatio:** Turvallisuus- ja kemikaalivirasto (Tukes) 
**Ehdottajan sähköpostiosoite:** mirva.kipinoinen@tukes.fi **Termiehdotus Fintossa:** [Kulutustavarat](http://finto.fi/yse/fi/page/Y505988)

**Comment by mariaforsen** [comment]
Kulutushyödykkeet>konsumtionsnyttigheter? (käytetty Suomessa)

**Comment by mirmaid** [comment]
https://www.finlex.fi/fi/laki/ajantasa/2011/20110920
