### ISSUE TITLE
Biosidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5989]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Biosidit 

#### Ehdotettu termi ruotsiksi   

Biocider 

#### Ehdotettu termi englanniksi   

Biocides 

#### Vastaava käsite muussa sanastossa   

TERO: biosidit : https://finto.fi/tero/fi/page/TTL248 
Wikipedia : https://fi.wikipedia.org/wiki/Biosidi 

#### Perustelut ehdotukselle   

Tukes uudistaa tukes.fi-verkkosivunsa ja ottaa uudessa verkkosivustossa ontologiat käyttöön. Tässä yhteydessä olisi tarve saada nykyisin ohjausterminä YSOssa oleva biosidit omaksi alakäsitteeksi, ei pelkästään ohjaavaksi termiksi. Tällä hetkellä YSOssa biosidit on ohjaustermi torjunta-aineille ja ympäristömyrkyille. Lainsäädännössä biosidit ymmärretään laajemmin: Biosidit ovat kemiallisia aineita, valmisteita tai pieneliöitä, joiden tarkoitus on tuhota, torjua tai tehdä haitattomaksi haitallisia eliöitä, estää niiden vaikutusta tai rajoittaa niiden esiintymistä. Biosideja ovat esimerkiksi ihon ja pintojen desinfiointiaineet, jyrsijämyrkyt, hyönteismyrkyt ja hyönteiskarkotteet, teollisuudessa ja teollisuustuotteissa käytettävät säilytysaineet,  puunsuoja-aineet sekä alusten kiinnittymisenestoaineet. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Uusi tukes.fi julkaistaan huhtikuussa 2018, joten sen sisältö ei vielä ole julkinen. Tietosisällöltään vastaava paketti on nykyisillä verkkosivuilla http://www.tukes.fi/fi/Toimialat/Kemikaalit-biosidit-ja-kasvinsuojeluaineet/Biosidit/ . 

**Ehdottajan nimi:** Kaarina Repo ja Mirva Kipinoinen 
**Ehdottajan organisaatio:** Turvallisuus- ja kemikaalivirasto (Tukes) 
**Ehdottajan sähköpostiosoite:** mirva.kipinoinen@tukes.fi **Termiehdotus Fintossa:** [Biosidit](http://finto.fi/yse/fi/page/Y505989)

**Comment by mirmaid** [comment]
Kuuluu varmaankin tähän ehdotukseen:
Tukesissa kasvinsuojeluaineilla tarkoitetaan valmisteita, joita käytetään:

- 

    suojelemaan kasveja tai kasvituotteita kasvintuhoojalta (tuhoeläinten ja kasvitautien torjunta-aineet)
    tuhoamaan haitallisia kasveja tai kasvin osia tai estämään kasvien haitallista kasvua (rikkakasvien torjunta-aineet)
    vaikuttamaan kasvien elintoimintoihin muulla tavoin kuin ravinteina (kasvunsääteet)
    vaikuttamaan kasvituotteiden säilyvyyteen, jollei näihin aineisiin ja valmisteisiin sovelleta elintarvikelisäaineita koskevia erityissäännöksiä.

**Comment by mariaforsen** [comment]
SAO: biocider

**Comment by YSA-kokous** [comment]
Seuraava kokous
