### ISSUE TITLE
yhteistuotanto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#599]
#### Ehdotettu termi suomeksi

yhteistuotanto
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)

**Luontipäivämäärä:** 13.10.2000

**Muokkauspäivämäärä:** 9.7.2001, 9.4.2002, 20.8.2004, 16.12.2008

**Voyager-id:** 114826

**Termiehdotus Fintossa:** [yhteistuotanto](http://finto.fi/yse/fi/page/Y314826)

**Comment by henriyli** [comment]
YSAan 11.11.2011: http://www.yso.fi/onto/ysa/Y182393
