### ISSUE TITLE
baptistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5990]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

baptistit 

#### Ehdotettu termi ruotsiksi   

baptister 

#### Ehdotettu termi englanniksi   

baptists 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kristityt](http://www.yso.fi/onto/yso/p6991) 

#### Assosiatiiviset (RT)   

[baptismi](http://www.yso.fi/onto/yso/p5042) 

#### Vastaava käsite muussa sanastossa   

LCSH : Baptists 
Svenska ämnesord : Baptister 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

On käytetty Melindassa. Myös muita vastaavia on jo sanastossa, esim. luterilaiset. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

En bit av Guds rike vid Riks-8:an : Oravais Baptistförsamling 80 år : "Ett centralt beläget verksamhetsfält" / sammanställd av Margareta Smith-Edström. 

**Ehdottajan nimi:** Maria Forsén 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [baptistit](http://finto.fi/yse/fi/page/Y505990)

**Comment by jtuohini** [comment]
Hierarkialtaan parempi LT-suhde olisi asiasanaan [**protestantit**](http://www.yso.fi/onto/ysa/Y127057), koska baptismi on osa protestantismia ja siis kaikki baptistit ovat protestantteja. ("Baptismi on protestanttisen reformaation pohjalta vuonna 1609 syntynyt kristillinen kirkkokunta." [https://fi.wikipedia.org/wiki/Baptismi])
