### ISSUE TITLE
uusnorja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5991]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uusnorja 

#### Ehdotettu termi ruotsiksi   

nynorska 

#### Ehdotettu termi englanniksi   

New Norwegian? 

#### Vaihtoehtoiset termit ja ilmaisut   

nykynorja 
nynorsk 

#### Ehdotettu yläkäsite YSOssa (LT)   

[norjan kieli](http://www.yso.fi/onto/yso/p3978) 

#### Vastaava käsite muussa sanastossa   

Svenska ämnesord : nynorsk 
LCSH : Norwegian language (Nynorsk) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Melindassa käytetty. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Nynorsk på nytt : ei idébok for studentar og lærarar / Norunn Askeland, Cecilie Falck-Ytter. 

**Ehdottajan nimi:** Maria Forsén 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [uusnorja](http://finto.fi/yse/fi/page/Y505991)

**Comment by ilona-x** [comment]
"Norjassa ei ole yhtä yhtenäistä kirjakieltä, vaan kaksi virallista kielimuotoa, kirjanorja eli bokmål ja uusnorja eli nynorsk." https://fi.wikipedia.org/wiki/Norjan_kieli

Jos tämä otetaan YSAan, otetaanko myös kirjanorja (bokmål) vai tulisiko se YSAsta löytyvän "norjan kielen" KT-muodoksi? LCSH:ssa ja SAO:ssa keskenään erilaiset ratkaisut: 

LCSH:
**Norwegian language**
KT Bokmål
KT Riksmål
http://id.loc.gov/authorities/subjects/sh85092722
LT Scandinavian languages

**Norwegian language (Nynorsk)**
http://id.loc.gov/authorities/subjects/sh85092723
LT Scandinavian languages

SAO: 
**Norska språket**
ST	  	  	
**Bokmål (norska)**
Norska som andraspråk
**Nynorsk**
Riksmål (norska)

**Comment by YSA-kokous** [comment]
Otetaan molemmat.
