### ISSUE TITLE
metodistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5993]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metodistit 

#### Ehdotettu termi ruotsiksi   

metodister 

#### Ehdotettu termi englanniksi   

Methodists 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kristityt](http://www.yso.fi/onto/yso/p6991) 

#### Assosiatiiviset (RT)   

[metodismi](http://www.yso.fi/onto/yso/p14597) 

#### Vastaava käsite muussa sanastossa   

LCSH : Methodists 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Käytetty Melindassa. Muitakin vastaavia on jo sanastossa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Borgå svenska metodistförsamling 100 år : 1907-2007 / [... arbetsgrupp: Mats Blomberg ... ja muita]. 

**Ehdottajan nimi:** Maria Forsén 
**Ehdottajan sähköpostiosoite:** maria.forsen@abo.fi **Termiehdotus Fintossa:** [metodistit](http://finto.fi/yse/fi/page/Y505993)

**Comment by jtuohini** [comment]
Hierarkialtaan parempi LT-suhde olisi asiasanaan [**protestantit**](http://www.yso.fi/onto/ysa/Y127057), koska metodismi on osa protestantismia ja siis kaikki metodistit ovat protestantteja. ("Methodism or the Methodist movement is a group of historically related denominations of Protestant Christianity which derive their inspiration from the life and teachings of John Wesley, an Anglican minister in England." [https://en.wikipedia.org/wiki/Methodism])
