### ISSUE TITLE
jatkuva sortuma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5994]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jatkuva sortuma 

#### Ehdotettu termi englanniksi   

progressive collapse 

#### Perustelut ehdotukselle   

Rakennustekniikan jatko-opiskelijan ehdottama käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://tut.finna.fi/Record/tutcat.256351 

**Ehdottajan nimi:** Harri Ollikainen 
**Ehdottajan sähköpostiosoite:** harri.ollikainen@tut.fi **Termiehdotus Fintossa:** [jatkuva sortuma](http://finto.fi/yse/fi/page/Y505994)

**Comment by mirmaid** [comment]
_Jatkuva sortuma käsitteenä tarkoittaa paikallisesta rakenteen kantavuuden menetyksestä syntyvää, ketjureaktiomaista kantavien rakenteiden pettämistä.Jatkuva sortuma voi syntyä kun yksittäinen rakenteen osa vaurioituu, myötää tai menettää stabiliteettinsa. Yhden rakenteen pettäessä täytyy muiden rakenteiden pystyä vastaanottamaan kuorma, jonka pettäneen rakenteen oli suunniteltu kantavan. Mikäli muita rakenteita ei ole suunniteltu tällainen yllättävä tilanne huomioon ottaen, syntyy jatkuva sortuma, jossa sortuminen jatkuu rakenteelta toisella kunnes rakennus on kokonaan sortunut tai sortuminen pysähtyy rakenteeseen, joka pystyy kuormat kannattelemaan._ http://www.theseus.fi/bitstream/handle/10024/90768/Jatkuva_sortuma_betonirakenteissa.pdf?sequence=1&isAllowed=y

**Comment by mariaforsen** [comment]
Sv. fortskridande ras
http://www.rikstermbanken.se/rtb/visaTermpost.html?id=160908
