### ISSUE TITLE
Pyhän Urhon päivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5995]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän Urhon päivä 

#### Ehdotettu termi englanniksi   

Saint Urho's Day 

#### Vaihtoehtoiset termit ja ilmaisut   

St Urho's Day 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vuotuisjuhlat](http://www.yso.fi/onto/yso/p1080) 

#### Assosiatiiviset (RT)   

[amerikansuomalaiset](http://www.yso.fi/onto/yso/p5280) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Pyh%C3%A4_Urho
https://en.wikipedia.org/wiki/Saint_Urho
http://www.sainturho.com/
https://kansallisbiografia.fi/kansallisbiografia/henkilo/9632 

#### Perustelut ehdotukselle   

KULO-termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Useita artikkeleja sekä mm. kirja Pyhä Urho: fakeloresta folkloreksi = St Urho: from fakelore to folklore / toimittaneet Anne Heimo, Tuomas Hovi & Maria Vasenkari (Turun yliopisto, 2012) 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [Pyhän Urhon päivä](http://finto.fi/yse/fi/page/Y505995)

**Comment by mariaforsen** [comment]
Sv. Sankt Urhos dag
