### ISSUE TITLE
sillankannet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5997]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sillankannet 

#### Ehdotettu termi englanniksi   

Bridge floors 

#### Vaihtoehtoiset termit ja ilmaisut   

sillan kannet 
Bridge decks 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85016839> 
Wikipedia : https://en.wikipedia.org/wiki/Deck_(bridge) 

#### Perustelut ehdotukselle   

kannet jaettu aiemmin (mm. alusten kannet, kannet (sulkimet)), Melinda-korjauksia tehdessä tuli vastaan yksi viite sillankansista 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sillanrakentamisen yleiset laatuvaatimukset : kannen pintarakenteet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

**Ehdottajan nimi:** Ilona Lindfors 
**Ehdottajan organisaatio:** Kansalliskirjasto 
**Ehdottajan sähköpostiosoite:** ilona.lindfors@helsinki.fi **Termiehdotus Fintossa:** [sillankannet](http://finto.fi/yse/fi/page/Y505997)

**Comment by mariaforsen** [comment]
Sv. brobanor ET brodäck, brolock, farbaneplattor
