### ISSUE TITLE
energiaoikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5998]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

energiaoikeus 

#### Ehdotettu termi ruotsiksi   

energirätt 

#### Ehdotettu termi englanniksi   

energy law 

#### Assosiatiiviset (RT)   

[ympäristöoikeus](http://www.yso.fi/onto/yso/p5971) 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Oikeustiede:energiaoikeus> 
Wikipedia : https://en.wikipedia.org/wiki/Energy_law 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Tarkoitusta täsmentävä selite   

Energian – esimerkiksi öljyn, kaasun tai tuulivoiman – tuottamisen, käyttämisen ja vaihdannan sääntelyä sekä energianlähteiden hyödyntämiseen liittyviä oikeuksia ja velvollisuuksia tutkiva oikeudenala. 

#### Perustelut ehdotukselle   

Ilmastonmuutoksen ja globalisaation myötä energiaoikeus kasvattanee merkitystään tulevaisuudessa. Jo nyt tieteenalalta julkaistaan paljon kirjallisuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.elgaronline.com/view/9781788112246/9781788112246.xml 

**Ehdottajan nimi:** Mikko Meriläinen 
**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** mikko.merilainen@uef.fi **Termiehdotus Fintossa:** [energiaoikeus](http://finto.fi/yse/fi/page/Y505998)

**Comment by mariaforsen** [comment]
Sv. energirätt
