### ISSUE TITLE
Ljudbok

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#5999]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

Ljudbok 

#### Ehdotettu termi suomeksi   

Äänikirja 

#### Ehdotettu termi englanniksi   

Audiobook 

#### Vaihtoehtoiset termit ja ilmaisut   

Talbok 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[81 Bibliotek. Arkiv. Informationstjänst. Museer. Utställningar](http://www.yso.fi/onto/yso/p26572) 

#### Perustelut ehdotukselle   

Vanligt ord som används i stor utsträckning. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

format 

**Ehdottajan nimi:** Mikael 
**Ehdottajan sähköpostiosoite:** mikael_gros@hotmail.com

**Comment by mariaforsen** [comment]
Finns redan i Allärs (denna typ av termer är i plural i enlighet med tesaurusstandarden): 
http://finto.fi/allars/sv/page/Y36156
http://finto.fi/allars/sv/page/Y39997
