### ISSUE TITLE
aikarahtaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6]
#### Ehdotettu termi suomeksi

aikarahtaus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)
#### Käsitteen määritelmä

Tarkoittaa menettelyä, jossa varustamo asettaa aluksen (usein miehistöineen) toisen varustamon tai valtion käytettäväksi

**Luontipäivämäärä:** 22.06.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 113823

**Termiehdotus Fintossa:** [aikarahtaus](http://finto.fi/yse/fi/page/Y313823)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
