### ISSUE TITLE
jumalantuomio[t]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6001]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jumalantuomio[t] 

#### Ehdotettu termi ruotsiksi   

gudsdom[ar] 

#### Ehdotettu termi englanniksi   

ordeal[s] 

#### Vaihtoehtoiset termit ja ilmaisut   

koetusoikeus 
gudomlig prövning, ordal 
trial by ordeal 

#### Assosiatiiviset (RT)   

[oikeuskäytäntö](http://www.yso.fi/onto/yso/p1703) 
[oikeushistoria](http://www.yso.fi/onto/yso/p7480) 

#### Vastaava käsite muussa sanastossa   

LCSH : <ordeal: http://id.loc.gov/authorities/subjects/sh85095346> 
SAO : Gudsdomar 
Wikisanakirja : https://fi.wiktionary.org/wiki/jumalantuomio 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Tarkoitusta täsmentävä selite   

Jargon: kutttuuriantropologian englanti-suomi oppisanasto:
Trial by ordel = koetusoikeus. Syyllisyyden tai syyttömyyden selvittäminen erityisten, usein kivuliaiden, koetusten avulla.
Ordeal = koetus. Lain käyttöön liittyvä fyysinen koe, joka todistaa syyllisuuden tai syyttömyyden. 

#### Perustelut ehdotukselle   

KULO-käsite. 
Käytetty sisällönkuvailussa vain muutamia kertoja, mutta hankala korvata muulla termillä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Griffiths, J. Gwyn: The divine verdict: a study of divine judgement in the ancient religions 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [jumalantuomio[t]](http://finto.fi/yse/fi/page/Y506001)

**Comment by AuHo22** [comment]
Vähemmän aihetta tuntevalle ja kristillisessä kulttuurissa kasvaneelle pakostakin tulee mieleen viimeinen tuomio tai tuomiopäivä..

**Comment by mirmaid** [comment]
Koetusoikeus olisi hyvä termi, mutta ei tuo viitteitä Googlella. Ehkä _jumalantuomio (oikeushistoria)_?

**Comment by mariaforsen** [comment]
Sv. gudsdomar ET gudomliga prövningar, ordal, ordalier

**Comment by YSA-kokous** [comment]
jumalantuomio (oikeuskulttuuri)
