### ISSUE TITLE
etiäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6002]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

etiäiset 

#### Ehdotettu termi englanniksi   

ominous beings 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yliluonnolliset olennot](http://www.yso.fi/onto/yso/p796) 

#### Assosiatiiviset (RT)   

[enteet](http://www.yso.fi/onto/yso/p6087) 

#### Vastaava käsite muussa sanastossa   

Lapponica : <http://urn.fi/URN:NBN:fi:au:lapponica:L192> 
Wikipedia : https://fi.wikipedia.org/wiki/Eti%C3%A4inen 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston sanakirja:
1. kansanperinteessä: ihmisen haamumainen kaksoisolento, jonka ilmestyminen yl. edeltää hänen saapumistaan.
2. yl. ennakkoaavistuksesta tms. Sai etiäisen veikkausvoitosta. Vääräksi osoittautunut etiäinen. 

#### Perustelut ehdotukselle   

KULA/KULO-käsite (Kielitoimiston sanakirjan 1. merkityksessä). Myös Lapponica-sanastossa.

Löytyyköhän tälle ruotsinkielistä vastinetta? SAOssa on prekognition ja siihen viittaavina ohjaustermeinä fjärrskåderi, fjärrskådning ja varsel (förebud). YSA-termi enteet on ruotsiksi varsel. LCSH:ssa on precognition.

Nuo englannin- ja ruotsinkieliset termit eivät siis ihan vastaa KULO-käsitettä, jolla on tarkoitettu nimenomaan yliluonnollista olentoa. Mutta toisaalta KULA-termiä on käytetty sisällönkuvailussa vain vähän. Pitäisikö siis väljentää käsitteen merkitystä, jotta muunkieliset termit olisi helpompi löytää? Silloin voisi lisätä ohjaustermiksi ennakkoaavistukset. Mitähän Lapponica-sanaston saamenkielinen termi 
ovdasaččat mahtaa tarkalleen ottaen tarkoittaa?

Toinen mahdollisuus olisi ottaa etiäiset vain ohjaustermiksi (KÄ enteet, yliluonnolliset olennot). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Harjumaa, Pentti: Aaveriekkoja: lappilaisia mystisiä tarinoita ja kummituksia. Lisäksi lähinnä artikkeliaineistoa. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [etiäiset](http://finto.fi/yse/fi/page/Y506002)

**Comment by mariaforsen** [comment]
Yllä olevat ruotsinkieliset termit tosiaan vastaavat kakkosmerkitystä. Ohjaus KÄYTÄ enteet, yliluonnolliset olennot kuulostaa hyvältä ratkaisulta. 

(Ruotsiksi käytetään tietyissä asiayhteyksissä sanaa "dubbelgångare" jos kysymyksessä on kaksoisolento liitettynä etiäisiin, kuten tässä käsitellään: https://fi.wikipedia.org/wiki/Kaksoisolento mutta sekään ei toimi ratkaisuna tässä asiassa)

**Comment by mirmaid** [comment]
Itselleni tuttu laajemmassa merkityksessä - voi olla myös ykkösmerkityksen kaltainen, mutta viitaten koko tapahtumaan, ei vain tähän henkiolentoon (josta olen joskus kuullut myös puhuttavan "edelläkävijänä").

**Comment by YSA-kokous** [comment]
KÄ enteet, yliluonnolliset olennot
