### ISSUE TITLE
mikkelinpäivä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6003]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikkelinpäivä 

#### Ehdotettu termi englanniksi   

Michaelmas 

#### Ehdotettu termi ruotsiksi   

mikaelidagen 

#### Vaihtoehtoiset termit ja ilmaisut   

mikonpäivä 
Mikon päivä 
mikkeli 
eng: Archangel Michael's Day 
ruotsi: mickelsmäss 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vuotuisjuhlat](http://www.yso.fi/onto/yso/p1080) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh91005295> 
SAO : Mickelsmässa 
Wikipedia : https://fi.wikipedia.org/wiki/Mikkelinp%C3%A4iv%C3%A4 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

http://neba.finlit.fi/juhlat/kekri/mikkeli.html:
"Syyskuun lopussa vietetty Mikkelin päivä eli arkkienkeli Mikaelin muistopäivä aloitti talonpojan kalenterissa syksyn. Se kuului kekrin ohella suomalaisen agraariyhteisön merkittävimpiin juhliin, ja monilla alueilla sitä on pidetty sadonkorjuun ja syystöiden päätepisteenä. Mikkeliä juhlittiin alun perin syyskuun 29. päivänä (kalenterissa edelleen Mikon nimipäivä), mutta vuoden 1772 pyhäuudistuksessa se siirrettiin seuraavalle sunnuntaille, jossa se on vielä nykyäänkin. -- Nykyaikana mikkelinä vietetään kirkoissa Enkelien päivää, johon liittyy usein myös lasten ja pyhäkoulutyön juhla. Mikkelinpäivän liturginen väri on valkoinen kuten joulun ja pääsiäisenkin." 

#### Perustelut ehdotukselle   

KULO- ja MAO-käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Suuri perinnekirja: suomalaista juhlaperinnettä ennen ja nyt / toimittanut Satu Aalto . 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [mikkelinpäivä](http://finto.fi/yse/fi/page/Y506003)

**Comment by mariaforsen** [comment]
Sv. ET helige Mikaels dag
