### ISSUE TITLE
väki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6004]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

väki 

#### Ehdotettu termi englanniksi   

mana 

#### Vaihtoehtoiset termit ja ilmaisut   

mana 

#### Ehdotettu yläkäsite YSOssa (LT)   

[uskonnolliset käsitykset](http://www.yso.fi/onto/yso/p26368) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85080331> 
Wikipedia : https://fi.wikipedia.org/wiki/V%C3%A4ki_(mytologia) 
Wikipedia : https://fi.wikipedia.org/wiki/Mana_(voima) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Tieteen termipankki, folkloristiikka: 
väki = "esineen, olion tai ilmiön erityinen supranormaali voima". Vieruskäsite: mana.
Kielitoimiston sanakirja:
väki = myt. jnk paikan kuvitellut haltiaolennot; jhk liittyväksi kuviteltu persoonaton voima, mana. Metsän, veden, hiiden väki.
mana = myt. jumalissa, ihmisissä, eläimissä ja esineissä piileväksi uskottu persoonaton yliluonnollinen voima,väki. 

#### Perustelut ehdotukselle   

KULO-käsitteet: väki ja mana. Ehdotamme jompaakumpaa tai molempia.

Väki ja mana tarkoittavat kutakuinkin samaa asiaa, mutta termit ovat alkujaan peräisin eri kulttuureista. Väki on suomalaisen kansanuskon sana. Mana on alunperin malaijilais-polynesialainen termi, jota käytetään nykyisin myös muiden kulttuurien yhteydessä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Lahti, Emmi: Tietäjiä, taikojia, hautausmaita: taikuus Suomessa 1700-luvun jälkipuoliskolla. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [väki](http://finto.fi/yse/fi/page/Y506004)

**Comment by mariaforsen** [comment]
Sv. mana
väki="andar" mutta nämä ovat jo Allärsissa =henget.. Muita ehdotuksia? Muuten voi olla melko mahdotonta kääntää.

**Comment by AuHo22** [comment]
Väki-sanan yhteyteen lisäisin mielellään sulkutarkenteen väki (mytologia) kuten wikipediassa, ihan sekaannusten välttämiseksi.

**Comment by vthuhtala** [comment]
Olisiko parempi vain käyttää termiä 'mana' sekaannusten välttämiseksi? KT väki

**Comment by YSA-kokous** [comment]
väki (mytologia)
mana

**Comment by mariaforsen** [comment]
Sv. 
-väki + anmärkning: "Det finns ingen motsvarande svensk term." ?
-mana
