### ISSUE TITLE
radioaakkoset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6005]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

radioaakkoset 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Merikarhun aakkoset :kaikki merenkulun viesteistä 

#### Perustelut ehdotukselle   

- 

**Ehdottajan nimi:** BTJ 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [radioaakkoset](http://finto.fi/yse/fi/page/Y506005)

**Comment by mariaforsen** [comment]
Sv. bokstaveringsalfabet ET bokstavering, radioalfabet 

Entä tavausaakkoset yms. vaihtoehtoiset muodot  https://www.kielikello.fi/-/aakkosnimet-eli-tavausaakkoset Tavausaakkonen myös Kielitoimiston sanakirjassa (ei radioaakkoset)

**Comment by LeKorsu** [comment]
Kannatan joko aakkosnimet tai tavausaakkoset, ja sitten toinen sekä radioaakkoset korvatuiksi termeiksi.
