### ISSUE TITLE
monikulttuurisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6006]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[monikulttuurisuus](http://www.yso.fi/onto/ysa/Y108419) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT kulttuuripluralismi 

#### Perustelut ehdotukselle   

Termiehdotusta kulttuuripluralismista ei ole aikoinaan hyväksytty ilmeisesti sen takia, että merkitys on lähellä monikulttuurisuutta. Aivan samaa asiaa termit eivät tarkoita, mutta lienevät niin lähellä toisiaan, ettei molempia tarvita sanastoon. Ohjaustermi on tarpeen, koska kulttuuripluralismista on ainestoa, eikä aina tule heti mieleen etsiä sitä monikulttuurisuus-termillä. Ks. https://github.com/Finto-ehdotus/YSE/issues/4515 

#### Ehdottaja   

Kristiina Näyhö 

#### Ehdottajan organisaatio   

SKS:n kirjasto 

#### Ehdottajan sähköpostiosoite   

kristiina.nayho@finlit.fi

**Comment by mariaforsen** [comment]
Sv. kulturpluralism
