### ISSUE TITLE
matemaattinen antropologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6007]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matemaattinen antropologia 

#### Ehdotettu termi englanniksi   

mathematical anthropology 

#### Ehdotettu termi ruotsiksi   

matematisk antropologi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[antropologia](http://www.yso.fi/onto/yso/p1560) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85082119> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

KULA/KULO-käsite.

Termiä ei ole käytetty paljon sisällönkuvailussa, aineistoa on lähinnä 1970- ja 1980-luvuilta, mutta termi on ihan selvä eikä varmasti aiheuta sekaannuksia YSAssa. LCSH:ssa on mathematical anthropology. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

New trends in mathematical anthropology / edited by Gisèle De Meur (1986) 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [matemaattinen antropologia](http://finto.fi/yse/fi/page/Y506007)

**Comment by mariaforsen** [comment]
Ei näytä olevan googlessa suomeksi tai ruotsiksi, onko mahdollisesti muita muotoja?

**Comment by YSA-kokous** [comment]
etnomatematiikka? Kristiina selvittää.

**Comment by krinay** [comment]
_Matemaattinen antropologia_ (LCSH http://id.loc.gov/authorities/subjects/sh85082119) ja _etnomatematiikka_ (LCSH http://id.loc.gov/authorities/subjects/sh85082181) ovat eri käsitteitä. Matemaattisella antropologialla tarkoitetaan antropologiaa (antropologista tutkimusta), jossa käytetään matemaattisia tutkimusmenetelmiä. Etnomatematiikassa matematiikka nähdään kulttuurisessa kontekstissaan, kulttuurisidonnaisena, eri kulttuureissa voidaan tuottaa erilaista matemaattista tietoa.

Jos _matemaattista antropologiaa_ ei hyväksytä, sen voi varmaan korvata sisällönkuvailussa termeillä antropologia + matemaattiset menetelmät. Viitteitä on Melindassa alle kymmenen.

_Etnomatematiikka_ vaikuttaisi ihan hyödyllisestä asiasanalta. Sitä lienee hankalampi korvata muilla termeillä. Omassa oraganisaatiossani ei siitä aiheesta juurikaan ole kirjallisuutta, joten en taida sitä kuitenkaan ehdottaa. :D

**Comment by mariaforsen** [comment]
SAO:ssakin on etnomatematik, LCSH-linkitys Ethnomathematics

**Comment by YSA-kokous** [comment]
etnomatematiikka
