### ISSUE TITLE
kristillinen kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6009]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kristillinen kulttuuri 

#### Ehdotettu termi ruotsiksi   

kristen kultur 

#### Ehdotettu termi englanniksi   

Christian culture 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuurit (kulttuurimuodot)](http://www.yso.fi/onto/yso/p1546) 

#### Vastaava käsite muussa sanastossa   

LCSH (Christianity and culture) : <http://id.loc.gov/authorities/subjects/sh85025240> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

KULA/KULO-käsite
YSAssa on islamilainen kulttuuri. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Termiä ei toistaiseksi ole käytetty sisällönkuvailussa paljon. Joitakin artikkeleja sillä on kuvailtu Artossa. 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [kristillinen kulttuuri](http://finto.fi/yse/fi/page/Y506009)

**Comment by jtuohini** [comment]
Ehdotuksen LCSH-vastine ei viittaa ihan samaan asia kuin ehdotettu asiasana **kristillinen kulttuuri**, vaan on ns. laaja-alainen termi, jolla kuvaillaan kahden eri ilmiön keskinäistä vuorovaikutusta, tässä tapauksessa kristinuskon ja kulttuurin suhdetta eri näkökulmista. Mutta käynee nb-tyyppisenä sanasuhteena.
