### ISSUE TITLE
funktioanalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6010]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[funktioanalyysi](http://www.yso.fi/onto/ysa/Y101390) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava tai ohjattava?

#### Perustelut ehdotukselle   

Huomautus on nyt: "Perinteen käyttöyhteyksiä selvittävä analyysimenetelmä." Melindassa käytetty lähinnä muissa merkityksissä. Esim. 
-Vanhusneuvoston funktioita jäljittämässä : tutkimus maaseutumaisten kuntien vanhusneuvostoista / Anu Leinonen.
-J.S. Bachin koraalien analyysi sävelluokkien esiintymisjärjestyksen valossa / Anne Hätönen.
-Satunnaisprosessit : funktionaalianalyyttiset konseptit / Väinö Jalava.

Huom. Sanastossa myös funktionaalianalyysi

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mariaforsen** [comment]
funktioanalyysi (matematiikka)=funktionsanalys (matematik) KÄYTÄ/ANVÄND funktionaalianalyysi=funktionalanalys?

**Comment by mirmaid** [comment]
Musiikissa onkin jo viittaus _sointuanalyysiin_. Olisiko sitten vielä _funktioanalyysi (folkloristiikka)_? Miten laaja tämä oikeastaan on, sopisiko jopa tuohon Vanhusneuvosto-teokseen? Ja onko folkloristiikka tarkenteena liian rajaava?

**Comment by satuniininen** [comment]
Käytetty Melindassa 72 kertaa, joista kirkas enemmistö viittaa matematiikan funktionaalianalyysiin. Kun matematiikan ja musiikin kuvailut jättää pois laskuista, jää 16 kuvailua, joiden aihepiirit ulottuvat aivan laidasta laitaan, esim. taloustiede, tuotannonsuunnittelu, sosiologia, antropologia, arkeologia, uskontotiede, nimistöntutkimus, diskurssianalyysi jne.

Antropologian ja arkeologian yhteydessä varmaankin tarkoitetaan juuri folkloristiikan funktioanalyysia mutta tällöin sulkutarkenteen pitäisi tosiaan olla laveampi. Joka tapauksessa yli jää joukko kuvailuja, joissa funktioanalyysiä käytetään yleisterminä.

Tarvitaanko folkloristiikan merkitystä omana käsitteenään, vai riittäisikö ohjaus funktioanalyysi (matematiikka) KÄYTÄ funktionaalianalyysi ja pelkän funktioanalyysin muutos 00-termiksi?

**Comment by YSA-kokous** [comment]
funktioanalyysi (matematiikka) KÄYTÄ funktionaalianalyysi 
funktioanalyysi: ryhmä 56, poistetaan määritelmä
