### ISSUE TITLE
Latvian vapaussota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6013]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Latvian vapaussota](http://www.yso.fi/onto/ysa/Y176445) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ohjaustermiksi 'vapaussota' 

#### Perustelut ehdotukselle   

Termi 'vapaussota' ohjaa Suomen kansalaissotaan, vaikka käytetty myös muussa merkityksesä 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by EsaMPKK** [comment]
Sotatyyppinä ongelmallinen: vaikea vetää rajaa kapinaliikkeiden ja vapaussodan välille.

**Comment by vthuhtala** [comment]
Se, oliko kyseessä vapaussota vai kapina riippuu voittajasta...
