### ISSUE TITLE
sisällissodat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6016]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sisällissodat](http://www.yso.fi/onto/ysa/Y104339) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan alakäsitteet Espanjan sisällissota, kansalaissota, Syyrian sisällissota, Venäjän sisällissota ja Ydysvaltain sisällissota 

#### Perustelut ehdotukselle   

Em. alakäsitteillä on kaksi yläkäsitettä: 'sisällissodat' ja 'sodat' -- MUTTA 'sisällissodat' on alakäsite termille 'sodat' 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by jtuohini** [comment]
Ehkä mieluummin noista alakäsitteistä kannattaisi poistaa yläkäsitteen yläkäsite **sota**, jotta hierarkia olisi hedelmällisempi; kaikki mainitut ovat sotia ja vielä täsmällisemmin sisällissotia.

**Comment by mirmaid** [comment]
YSOssa tuplahierarkiaa ei ole. Tämäntyyppisiä päivityksiä ei kannata enää tässä vaiheessa tehdä YSAn puolella, YSAssa on vanhastaan paljon vastaavanlaisia tuplahierarkioita.
