### ISSUE TITLE
laulava vallankumous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6017]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laulava vallankumous 

#### Ehdotettu termi ruotsiksi   

Den sjungande revolutionen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vallankumoukset](http://www.yso.fi/onto/yso/p15786) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Laulava_vallankumous 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Tarkoitusta täsmentävä selite   

Wikipedia: Laulava vallankumous tarkoittaa vuosien 1987-1990 tapahtumia, jotka johtivat Viron, Latvian ja Liettuan jälleenitsenäistymiseen. Liikkeen nimi johtuu suurista laulujuhlista, jotka saivat neuvostovastaisen sisällön. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. Käytetty Helkassa 85 kertaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1748929 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [laulava vallankumous](http://finto.fi/yse/fi/page/Y506017)

**Comment by LeKorsu** [comment]
Pitäisikö  myös neilikkavallankumous ottaa sanastoon nyt samalla, vai sitten vasta kun on kysyntää?
sv nejlikerevolutionen, en carnation revolution (vai Carnation Revolution)

**Comment by mariaforsen** [comment]
Sv. 
-sjungande revolutionen ET den sjungande revolutionen
-nejlikerevolutionen ET Nejlikrevolutionen

**Comment by YSA-kokous** [comment]
Otetaan molemmat.
