### ISSUE TITLE
kysyntäjousto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6018]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kysyntäjousto 

#### Ehdotettu termi englanniksi   

demand response 

#### Vaihtoehtoiset termit ja ilmaisut   

kysyntävaste, sähkön kysynnän jousto 

#### Vastaava käsite muussa sanastossa   

Tieteen Termipankki : <http://tieteentermipankki.fi/wiki/Clean_Energy_Research:demand_response> 

#### Tarkoitusta täsmentävä selite   

Sähkön kuluttajien reagoiminen sähkönhinnan ja –saatavuuden vaihteluun muuttamalla kulutuskäyttäytymistään. 

#### Perustelut ehdotukselle   

Puuttuu Fintosta, keskeinen energiamarkkinoiden käsite. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://energia.fi/ajankohtaista_ja_materiaalipankki/materiaalipankki/kysynnan_jousto_-_suomeen_soveltuvat_kaytannon_ratkaisut_ja_vaikutukset_verkkoyhtioille_-_sahkotutkimuspoolin_julkaisu.html 

**Ehdottajan nimi:** Sanna Tuomela 
**Ehdottajan organisaatio:** Oulun yliopisto 
**Ehdottajan sähköpostiosoite:** sanna.tuomela@oulu.fi **Termiehdotus Fintossa:** [kysyntäjousto](http://finto.fi/yse/fi/page/Y506018)

**Comment by mirmaid** [comment]
Melindassa käytetty laajemmin, netissä lähes yksinomaan sähkömarkkinoista.

_Kysyntäjousto tarkoittaa sitä, että kysyntä muuttuu tarjonnan mukaan, eikä päinvastoin niin kuin markkinat yleensä toimivat. Esimerkiksi, jos paratiisisaarelle lähtee rajattu joukko seuralaisia niin ei kannata ruveta ronkeliksi, vaan nauttia tarjolla olevasta seurasta. Sähkömarkkinoilla kysyntäjousto tarkoittaa sitä että sähköä pitäisi kuluttaa silloin kun sitä tuotetaan. Tuulivoimala tuottaa sähköä silloin kun tuulee ja aurinkovoimala silloin kun paistaa, ja sähköenergian varastoiminen toista kulutushetkeä varten on aina häviöllistä._ https://www.insinoorinpaivakirja.fi/tag/kysyntajousto/

**Comment by mariaforsen** [comment]
Sv. ET efterfrågeelasticitet /Rikstermbanken, ca 2420, efterfrågeflexibilitet /IATE, Rikstermbanken, ca 8260 
Hankala jos pitää rajoittaa vain sähköön, perusmerkitys taitaa kuitenkin olla sama, MOTissa ja TEPAssa pelkkä kysyntäjousto.

**Comment by YSA-kokous** [comment]
kysyntäjousto (KT kysynnän jousto?), yleisterminä + energia-ala

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/Taloustiede:jousto_(kysynn%C3%A4n)
jousto (kysynnän)
Määritelmä 1) Kysynnän hintajousto on kysytyn määrän suhteellinen muutos jaettuna hyödykkeen oman hinnan suhteellisella muutoksella. (2) Vastaavasti kysynnän tulojousto on kysytyn määrän suhteellinen muutos jaettuna tulojen suhteellisella muutoksella.

Tämä merkitys onkin jo YSAssa: hintajousto http://finto.fi/ysa/fi/page/Y136087
Lisäksi YSAssa joustot, jonka ryhminä 75 & 00  http://finto.fi/ysa/fi/page/Y136088

**Comment by mirmaid** [comment]
Tarvittu taas: Consequences of demand-side interventions on the operation efficiency of future energy systems

**Comment by mirmaid** [comment]
Ei ehkä ihan sama asia kuin kysynnän hintajousto:
_Taloustieteessä kysynnän hintajoustolla tarkoitetaan sitä, että tuotteen hinnan noustessa sen kysyntä vähenee. -- kysyntäjousto on mahdollista ilman kuluttajan jatkuvaa päätöksentekoa -- Sähköä tarjotaan entistä enemmän palvelupakettina, jossa yhtenä osana on sähkönkäytön optimointi markkinahintaa vastaan ilman, että kuluttajan tarvitsee siitä huolehtia tai että se haittaisi normaalia elämää. Palvelun tuottaja vastaa sähkönkäytön ajoittamisesta siten, että se kerää hyötyä pienistäkin sähkömarkkinoiden hintaeroista, joihin reagoimiseen tavallisen kuluttajan ei kannattaisi nähdä vaivaa._ https://www.linkedin.com/pulse/kysynt%C3%A4jousto-mit%C3%A4-se-ville-karttunen/

**Comment by YSO-kokous** [comment]
Tutkittaneen lisää.

**Comment by mariaforsen** [comment]
https://www.rikstermbanken.se/rtb/visaTermpost.html?id=262873
Priselasticitet: Visar på hur efterfrågan förändrar sig när man ändrar priset.

https://www.rikstermbanken.se/rtb/visaTermpost.html?id=182567 "
Efterfrågeelasticitet: Den procentuella förändringen i kvantitet delat med den procentuella förändringen i pris

**Comment by mirmaid** [comment]
Taas: https://www.oulu.fi/yliopisto/node/192602

**Comment by mirmaid** [comment]
Nyt YSOn _hintajousto_-käsitteessä on yhdistetty kysynnän hintajousto ja tarjonnan hintajousto, ongelma? Kysynnän hintajousto = kysynnän muutos suhteessa tuotteen hinnan muutokseen; tarjonnan hintajousto = tuotteen (tms.) tarjonnan muutos suhteessa hinnan muutokseen.

Sähkön kulutukseen liittyen uutena ehdotuksena _(sähkön) kulutusjousto_. Ehkä vähän paremmin kuvaa tarkasteltavaa ilmiötä kuin kysyntäjousto.

**Comment by YSO-kokous** [comment]
Hyväksytään sähkön kysyntäjousto KT sähkön kulutusjousto

**Comment by mariaforsen** [comment]
Sv. efterfrågeflexibilitet (elektricitet) 
https://termipankki.fi/tepa/fi/haku/kysynt%C3%A4jousto  https://termipankki.fi/tepa/fi/haku/kulutusjousto
