### ISSUE TITLE
jatkokaudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6020]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jatkokaudet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ajanjaksot](http://www.yso.fi/onto/yso/p4035) 

#### Perustelut ehdotukselle   

löytyy hesarista 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

hesarin kuvailussa 

**Ehdottajan nimi:** Mikko Lappalainen 
**Ehdottajan sähköpostiosoite:** mikko.lappalainen@helsinki.fi

**Comment by mirmaid** [comment]
Testi
