### ISSUE TITLE
puuhakirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6021]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puuhakirjat](http://www.yso.fi/onto/ysa/Y127169) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ohjaustermi tehtäväkirjat 

#### Perustelut ehdotukselle   

Nyt tehtäväkirjat KÄ harjoituskirjat. Aikuisille suunnatuissa aineistoissa myös ajanvietteeksi tarkoitettuja tehtäväkirjoja, joiden avulla ei "harjoitella" mitään. 

#### Ehdottaja   

Fennica-sisku 

#### Ehdottajan sähköpostiosoite   

mirja.anttila@helsinki.fi

**Comment by AuHo22** [comment]
Tehtäväkirjat -termi on kuitenkin laajempi, ja tässä yksi käyttötavoista, eli ehdotetaanko termejä kohta uudelleen, jos luovutaan sekä työ- että tehtäväkirjoista - tuntuuko ohjaus elämäntaito-oppaisiin kaukaa haetulta?

http://www.ts.fi/teemat/3782514/Aikuisten+tehtavakirjat+ovat+nyt+suosittuja+itsetutkiskelun+valineita++tassa+9+erilaista+katsahdusta+sisimpaan

https://www.epressi.com/tiedotteet/kustannustoiminta/uutuuskirja-my-way-on-tehtavakirja-oman-elaman-kasikirjoitukseen.html

**Comment by mirmaid** [comment]
puuhakirjojen LT lastenkirjallisuus, pitäisikö se muuttaa RT:ksi jos aikuisillakin on puuhakirjoja?
