### ISSUE TITLE
lukemistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6023]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lukemistot](http://www.yso.fi/onto/ysa/Y106541) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSAn puolella lisätään ja YSOn puolella vaihdetaan LT-suhteeksi "kokoomateokset" 

#### Perustelut ehdotukselle   

Lukemistot ovat kokoomateoksia, joten termien suhteen pitäisi heijastaa tätä seikkaa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mirmaid** [comment]
Termi on todettu genresanastossa ongelmalliseksi. Kielitoimiston sanakirja: opiskelun tausta-aineistoksi t. viihdelukemiseksi tarkoitettu kirjallisuusotteita, helppotajuisia artikkeleita tm. erillisiä kirjoitelmia sisältävä kirja (t. lehti). _Oheislukemisto. Ajanvietelukemisto._ Ruotsiksi nyt _läseböcker (textsamlingar)_. Käytetty Melindassa myös yksittäisten romaanien helppolukuisista versioista.

**Comment by mirmaid** [comment]
_Lukemistot_ on poistettu.
