### ISSUE TITLE
pastoraalimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6024]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pastoraalimusiikki 

#### Ehdotettu termi englanniksi   

pastoral music 

#### Ehdotettu termi ruotsiksi   

pastoralmusik 

#### Vaihtoehtoiset termit ja ilmaisut   

pastoraalit (sävellykset) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85098583> 
Wikidata : https://www.wikidata.org/wiki/Q1472271 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

YSAn nykyinen asiasana pastoraalit vaatii jakamisen (ks. https://github.com/Finto-ehdotus/YSE/issues/5634); käsilläoleva ehdotus kattaa käsittelyn selkeyttämiseksi musiikilliset pastoraalisävellykset ja pastoraalimusiikin yleensä. 

#### Tarkoitusta täsmentävä selite   

Grove Music Onlinessa yleisesti "A [- -] musical genre that depicts the characters and scenes of rural life or is expressive of its atmosphere. The term has been used in musical titles as both an adjective (Beethoven’s Pastoral Symphony) and a noun (Franck’s Pastorale) and may be used both ways in referring to the type in general." Ja edelleen barokin sävelmotiivien osalta "[- -] many of the pastoral motifs later popularized by Corelli. These motifs include lilting melodies in triple time (here 3/2, later usually 6/8 or 12/8) mainly in conjunct motion, prominent use of parallel 3rds, drone basses and symmetrical phrases ( ex.1). Such features are prominent in the music-making of Italian shepherds (pifferari), who have been recorded playing the shawm (piffero) and bagpipe (zampogna) at Christmas in towns since the 19th century ( ex.2); it has been reasonably suggested that this music may have been cultivated in the 17th century and that it was being imitated in these and later pastorals." Ja vielä edelleen romantiikan ajan ulkomusiikillisen aihekuvauksen osalta "The picturesque and idyllic motifs of Nature already adopted in some 18th-century music (see above) and unconnected with the Christmas pastoral tradition, such as motifs suggesting running water or hunting scenes in the forest, came to permeate much of the music [- -]" [https://doi.org/10.1093/gmo/9781561592630.article.40091] 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [pastoraalimusiikki](http://finto.fi/yse/fi/page/Y506024)

**Comment by jtuohini** [comment]
Ja toinenkin KT-muoto: "pastoraalinen musiikki"

**Comment by mariaforsen** [comment]
Muutama osuma googlessa.. Epävarmaa voidaanko ruotsiksi laittaa täysin vastaavassa muodossa, vai olisiko sitten mahdollista pitää ruotsiksi pastoraler (musik).

**Comment by tpalonen** [comment]
En vastusta ehdotusta, mutta jatkossa pyrkisin välttämään tällaista taidealakohtaista erittelyä, jos vain mahdollista. Pastoraalidraamat on jo sanastossa joten tämän aiheen osalta erittelyä on jo tehty aiemminkin. Kuitenkin jatkossa suosittaisin yhtä yhteistä kaikki taidemuodot sallivaa käsitettä silloin kun se on mahdollista eikä aiheuta suuria ongelmia, varsinkin jos käsite viittaa taiteen teemoihin abstraktilla/semanttisella tasolla.

**Comment by YSA-kokous** [comment]
Pyydetään vielä tarkennusta ehdottajalta.

**Comment by tpalonen** [comment]
Tämä lienee jo ratkennut? Ks. https://github.com/Finto-ehdotus/YSE/issues/5634
