### ISSUE TITLE
käsityömallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6025]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[käsityömallit](http://www.yso.fi/onto/ysa/Y216663) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Asiasana kaavat (käsityöt) ohjaa käyttämään termiä käsityömallit. Käsityömallit ja vaatteiden kaavat olisi mielestäni erotettava toisistaan. 

#### Perustelut ehdotukselle   

Vaatteiden kaavat on vakiintunut käsite. Käsityömallit on liian laaja. 

#### Ehdottaja   

Anneli Korhonen 

#### Ehdottajan organisaatio   

Hämeen ammattikorkeakoulun kirjasto 

#### Ehdottajan sähköpostiosoite   

anneli.korhonen@hamk.fi

**Comment by mariaforsen** [comment]
Sv. klädmönster on myös Svenska ämnesord:issa (linkitetty LCSH: Dressmaking - Patterns)
Käsityömallit=handarbetsmodeller/mönster? Jos näin, niin olisi hyvä saada vaatteiden kaavat=klädmönster erikseen.

**Comment by AuHo22** [comment]
ompelukaavat?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5488

**Comment by mirmaid** [comment]
Aikaisempi ratkaisu _kaavat (käsityö)_ olisi suomeksi kattanut nimenomaan ompelukaavat, mutta vastaava ruotsinkielinen _mönster (handarbete)_ oli laajempi, ja suomenkielistä laajennettiin sitä vastaavaksi. Jos tarkempi jako on kuitenkin toivottu, voidaan varmaan ottaa _ompelukaavat_ KT kaavat (käsityö)?
