### ISSUE TITLE
elämänpuu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6026]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

elämänpuu 

#### Ehdotettu termi ruotsiksi   

livets träd 

#### Ehdotettu termi englanniksi   

tree of life 

#### Vaihtoehtoiset termit ja ilmaisut   

elämän puu 

#### Vastaava käsite muussa sanastossa   

LCSH tree of life : <http://id.loc.gov/authorities/subjects/sh85137229> 
Wikipedia : https://fi.wikipedia.org/wiki/El%C3%A4m%C3%A4n_puu 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Tree_of_life

Vrt. termiehdotus: maailmanpuu 

#### Perustelut ehdotukselle   

KULA/KULO-käsite

Vain kymmenen Melinda-viitettä, osa saman kirjan eri painoksia, mutta aineistoa on Melindassa paljon enemmän. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Harva, Uno: Elämänpuu 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [elämänpuu](http://finto.fi/yse/fi/page/Y506026)

**Comment by krinay** [comment]
Vrt. https://github.com/Finto-ehdotus/YSE/issues/6027

**Comment by mariaforsen** [comment]
Sv. livets träd ET livsträd
