### ISSUE TITLE
maailmanpuu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6027]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maailmanpuu 

#### Ehdotettu termi ruotsiksi   

världsträd 

#### Ehdotettu termi englanniksi   

world tree 

#### Vaihtoehtoiset termit ja ilmaisut   

kosminen puu 
cosmic tree 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Maailmanpuu 
Wikipedia (eng) : https://en.wikipedia.org/wiki/World_tree 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

KULA/KULO-käsite

Vain 13 Melinda-viitettä, mutta aineistoa on paljon enemmän.

Vrt. termiehdotus elämänpuu https://github.com/Finto-ehdotus/YSE/issues/6026 
(Elämänpuu-termillä tulee paljon enemmän Google-osumia, mutta suomalais-ugrilaisen ja skandinaavisen mytologian kannalta maailmanpuu on keskeisempi käsite. Jos päätetään ottaa vain toinen näistä ehdotuksista, lienee kuitenkin valittava termi elämänpuu. Aivan samasta käsitteestä ei siis kuitenkaan ole kyse.) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Butterworth, E. A. S.:  The tree at the navel of the earth 

**Ehdottajan nimi:** Kristiina Näyhö 
**Ehdottajan organisaatio:** SKS:n kirjasto 
**Ehdottajan sähköpostiosoite:** kristiina.nayho@finlit.fi **Termiehdotus Fintossa:** [maailmanpuu](http://finto.fi/yse/fi/page/Y506027)

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kasvitiede:maailmanpuu

**Comment by YSA-kokous** [comment]
Määritelmät ja huomautukset myös toisen termin käytöstä.
