### ISSUE TITLE
Haarajoen museosilta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6030]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Haarajoen museosilta 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Haarajoen_museosilta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-314-634-1 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [Haarajoen museosilta](http://finto.fi/yse/fi/page/Y506030)

**Comment by mariaforsen** [comment]
Sv. Haarajoki bro ET Haarajoki museibro
