### ISSUE TITLE
uskomusjärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6031]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uskomusjärjestelmät 

#### Ehdotettu termi englanniksi   

belief systems 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yhteiskunnalliset järjestelmät](http://www.yso.fi/onto/yso/p250) 

#### Alakäsitteet (RT)   

[okkultismi](http://www.yso.fi/onto/yso/p530) 
[magia](http://www.yso.fi/onto/yso/p6089) 
[mystiikka](http://www.yso.fi/onto/yso/p5405) 
[noituus](http://www.yso.fi/onto/yso/p7777) 
[astrologia](http://www.yso.fi/onto/yso/p7027) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

"A belief system is a set of mutually supportive beliefs." https://en.wikipedia.org/wiki/Belief#Systems 

#### Perustelut ehdotukselle   

Yleinen ja käyttökelpoinen käsite humanistisissa tieteissä, varsinkin kun puhutaan järjestelmistä, joita ei varsinaisesti voi nimittää uskonnoiksi, mutta jotka kuitenkin pohjautuvat joukkoon uskomuksia. Samalla käsite toimii kokoavana yläkäsitteenä sellaisille käsitteille kuin magia, mystiikka ja noituus, joille on vaikea löytää sopivaa yläkäsitettä nykyisestä hierarkiasta. "Uskonnot (opit)" sopisi niin ikään tälle alakäsitteeksi, ainakin YSOn puolella. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Stealing fire from heaven : the rise of modern Western magic / Nevill Drury. 

**Ehdottajan nimi:** Tuomas Palonen 
**Ehdottajan organisaatio:** KK 
**Ehdottajan sähköpostiosoite:** tuomas.palonen@helsinki.fi **Termiehdotus Fintossa:** [uskomusjärjestelmät](http://finto.fi/yse/fi/page/Y506031)

**Comment by SamuVirokannas** [comment]
Aivan, kirjoitin hätiköiden - sotkin mystiikan yleisesti ja uskontojen mystiikkaa painottavat suuntaukset. Mystiikka ei sovi suoraan uskonnot-käsitteen alle. Sufilaisuus - joka lienee toistaiseksi ainoa ns. mystinen uskontosuuntaus Ysossa - on nyt ihan loogisesti sekä mystiikan että islamin alakäsite (tietyn uskonnon tietynlainen suuntaus). Samaa mallia olisi varmaan hyvä soveltaa muihinkin uskontojen mystiikkasuuntauksiin, kun niitä mahdollisesti joskus lisätään Ysoon. 

Uskomusjärjestelmien ehdotetut alakäsitteet ovat nykyisin joko rajatiedon (esim. okkultismi) tai uskonnollisten tuotosten (mystiikka, noituus) alakäsitteinä. Ehdottaisin tällaista ratkaisua: 
- Mystiikka olisi sekä uskomusjärjestelmien että uskonnollisten tuotosten alakäsitteenä. 
- Okkultismi ym. pysyisivät rajatiedon alla, ja rajatieto olisi uskomusjärjestelmien alakäsite. 
- Uskomusjärjestelmät voisi kaikitenkin olla rajatiedon ainoa yläkäsite (kulttuuristen objektien sijaan). 
- Uskomusjärjestelmien yläkäsitteeksi kulttuuriset järjestelmät. 

Noituudesta en ole ihan varma. Kuuluisiko se pelkästään uskomusjärjestelmiin vai lisäksi uskonnollisiin tuotoksiin?

**Comment by mariaforsen** [comment]
Sv. trossystem ET trosuppfattningar
