### ISSUE TITLE
Aarnikotkan metsän luonnonsuojelualue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6034]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Aarnikotkan metsän luonnonsuojelualue 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luonnonsuojelualueet](http://www.yso.fi/onto/yso/p1371) 

#### Vastaava käsite muussa sanastossa   

MML Paikannimet : <http://paikkatiedot.fi/so/1000772/10892816> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1885157 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Aarnikotkan metsän luonnonsuojelualue](http://finto.fi/yse/fi/page/Y506034)

**Comment by mariaforsen** [comment]
Sv. Aarnikotka skogs naturskyddsområde
