### ISSUE TITLE
abenakit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6036]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

abenakit 

#### Ehdotettu termi englanniksi   

Abenaki Indians 

#### Ehdotettu yläkäsite YSOssa (LT)   

[intiaanit](http://www.yso.fi/onto/yso/p646) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Abenakit 
LCSH : https://lccn.loc.gov/sh85000176 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Tarkoitusta täsmentävä selite   

Kanadan Québecissä sekä Yhdysvaltojen Mainessa ja Vermontissa asuva intiaanikansa. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2109927 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [abenakit](http://finto.fi/yse/fi/page/Y506036)

**Comment by mariaforsen** [comment]
Sv. abenakis ET abenaker
