### ISSUE TITLE
abbasidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6038]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

abbasidit 

#### Ehdotettu termi englanniksi   

Abbasids 

#### Vaihtoehtoiset termit ja ilmaisut   

Abbasidien dynastia 
Bagdadin kalifit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kalifit](http://www.yso.fi/onto/yso/p29154) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85000061 
Wikipedia : https://fi.wikipedia.org/wiki/Abbasidit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

Sunnidynastia, joka hallitsi arabien valtakuntaa 750-1258.  Tämän jälkeen hallitsivat vielä Kairossa nimellisesti kalifeina vuoteen 1517 saakka. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa.
HUOM. Edeltänyt dynastia, omaijadit, on laitettu: 52 historia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2367865 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [abbasidit](http://finto.fi/yse/fi/page/Y506038)

**Comment by mariaforsen** [comment]
Sv. abbasider ET abbasiddynastin
