### ISSUE TITLE
aasialaisamerikkalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6040]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aasialaisamerikkalaiset 

#### Ehdotettu termi englanniksi   

Asian Americans 

#### Ehdotettu yläkäsite YSOssa (LT)   

[amerikkalaiset](http://www.yso.fi/onto/yso/p5189) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85008644 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 
[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2111140 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [aasialaisamerikkalaiset](http://finto.fi/yse/fi/page/Y506040)

**Comment by jtuohini** [comment]
Tässä tapauksessa mielestäni osuvampi asiasanaksi olisi _yhdysvaltainaasialaiset_ (analogiana **ruotsinsuomalaiset**, **suomenruotsalaiset**, **venäjänsuomalaiset**, **kanadansuomalaiset**), ja jos epätarkempi riittäisi (kattaen muutkin Amerikan valtiot kuin Yhdysvallat), niin silloin _amerikanaasialaiset_.

**Comment by mirmaid** [comment]
Kaikki ehdotetut muodot hyvin vähän käytettyjä.

**Comment by krinay** [comment]
_Amerikansuomalainen_ on jostakin syystä määritelty Kielitoimiston sanakirjassa näin: "Pohjois-Amerikassa asuva suomalainen; näille tyypillinen, näitä koskeva." 

En tiedä, tarkoittaisiko _amerikanaasialainenkin_ näin ollen lähinnä Pohjois-Amerikan aasialaisia vai ovatko amerikansuomalaiset vain meillä vakiintunut poikkeus. (YSA:n termi kanadansuomalaiset olisi muuten vähän turha, jos lähtökohdaksi otettaisiin tämä Kielitoimiston määritelmä.)

Joka tapauksessa _amerikanaasialaiset_ vaikuttaa minusta suomen kielessä luontevammalta muodolta kuin _aasialaisamerikkalaiset_ tai _yhdysvaltainaasialaiset_. En muista nähneeni kirjallisuudessa tai muuten yleisessä käytössä yhdysvaltain-alkuisia termejä näissä yhteyksissä. Kuvailuahan voi täydentää maan nimellä.

**Comment by mariaforsen** [comment]
Sv. asiat-amerikaner

**Comment by YSA-kokous** [comment]
amerikanaasialaiset
