### ISSUE TITLE
naturalismi (taide)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6041]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[naturalismi (taide)](http://www.yso.fi/onto/ysa/Y103650) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pikemminkin lisäys: naturalismi (kirjallisuus) 

#### Perustelut ehdotukselle   

KITOssa pelkkä naturalismi, koska ennen voitiin  ketjuttaa naturalismi x-kenttään  
naturalismi (taide) ei sisällä sanataidetta, vaikka termi on yhtä tärkeä kirjallisuudessa kuin taiteessa 

#### Ehdottaja   

Anna-Maija Stenlund 

#### Ehdottajan organisaatio   

SKS 

#### Ehdottajan sähköpostiosoite   

anna-maija.stenlund@finlit.fi

**Comment by mirmaid** [comment]
Usein varmaan mielletään että taide = kuvataide. Tarkoitus on kuitenkin kattaa kaikki taiteenlajit. Termillä on myös ryhmä 87.

**Comment by YSA-kokous** [comment]
Ei muutosta
