### ISSUE TITLE
audionomit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6042]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

audionomit 

#### Perustelut ehdotukselle   

Audionomi on hoitotyön, kuulo- ja tasapainotutkimusten ja kuulon kuntoutuksen asiantuntija. https://fi.wikipedia.org/wiki/Audionomi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://minedu.fi/julkaisu?pubid=URN:ISBN:978-952-263-244-9 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [audionomit](http://finto.fi/yse/fi/page/Y506042)

**Comment by mariaforsen** [comment]
Sv. audionomer
