### ISSUE TITLE
homot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6045]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[homot](http://www.yso.fi/onto/ysa/Y191767) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään asiasanalle KT-muoto "homomiehet" 

#### Perustelut ehdotukselle   

Asiasana "homoseksuaalit" kattaa sekä homo(miehe)t että lesbot, joten homot-asiasanalle voitaisiin hyvin lisätä ehdotettu KT-muoto, sitä kun käytetään muuten paljon. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by jtuohini** [comment]
Ai niin, ja lisäksi tarvittaisiin LT-muodoksi [**miehet**](http://www.yso.fi/onto/ysa/Y97441), koska kaikki homo(miehe)t ovat miehiä.

**Comment by satuniininen** [comment]
Sukupuoli- ja seksuaali-identiteettien määrittäminen ei ole näin mustavalkoista. Ehdotettu ratkaisu sulkee ulkopuolelleen kaikki sukupuolivähemmistöihin kuuluvat, jotka eivät sovi mies-nais-jaotteluun, esim. transihmiset, sukupuolettomat, intersukupuoliset jne.

**Comment by jtuohini** [comment]
Nyt en käsitä: YSAssa on asiasana [**homoseksuaalit**](http://www.yso.fi/onto/ysa/Y152574), joka kattaa kaikki yksistään samansukupuolista vetovoitaa, olipa se romanttista tai eroottista/seksuaalista, omaavat henkilöt, jos oikein ymmärrän. Sen alatermeinä ovat **homot** ja **lesbot**. Jos näistä edellinen ei viittaa homoksuaalisiin miehiin eikä jälkimmäinen homoseksuaalisiin naisiin, niin mihin sitten? Ja jos käsitemaailma on mahdottoman liukuva, ettei näitä voida määritellä, niin sitten ei tällaisia suppeampia asiasanoja pitäisi edes olla sanastossa. Ja edelleen: jos ihminen on sukupuoleton, niin eihän voi olla homoseksuaali, koska koko käsite homoseksuaalisuus palaa sukupuolen määrittämiseen: "Homoseksuaalisuus (kreikan sanasta ὁμός ’sama’ ja latinan sanasta sexus ’sukupuoli’) tarkoittaa seksuaalista suuntautumista, jossa yksilön seksuaalinen kiinnostus, romanttiset ajatukset, tunteet tai molemmat kohdistuvat pelkästään tai ensisijaisesti hänen omaan sukupuoleensa." [https://fi.wikipedia.org/wiki/Homoseksuaalisuus]
 
Wikipediassa on myös seuraavat määritelmät: "Lesbo on naispuolinen homoseksuaali eli nainen, joka kokee seksuaalista tai tunnepohjaista vetovoimaa ainoastaan naisiin" [https://fi.wikipedia.org/wiki/Lesbo] ja "Sanaa homo merkityksessä homoseksuaali käytetään enimmäkseen miehistä" [https://fi.wikipedia.org/wiki/Homoseksuaalisuus].

**Comment by satuniininen** [comment]
Tarkoitan sitä, ettei sanaston tarvitse tällaisilla hierarkiaratkaisuilla ottaa kantaa siihen, voiko esim. intersukupuoliseksi itsensä määrittävällä henkilölllä olla homoseksuaalinen seksuaali-identiteetti. Varsinkin kun käsitteellä on jo LT-suhde eikä muutos ole tarpeellinen.

**Comment by jtuohini** [comment]
LT-suhde nimenomaan puuttuu! Siis **homot** LT _miehet_ ja **lesbot** LT _naiset_ – siis sillä ehdolla, että asiasana homot viittaa homoseksuaalisiin miehiin ja asiasana lesbot homoseksuaalisiin naisiin. Niiden, jotka eivät ole tai eivät koe olevansa miehiä tai naisia, sukupuolinen suuntaus voitaisiin kuvailla tuolla **homoseksuaalit**-asiasanalla, sehän ei sinällään viittaa sukupuolisuutta kuvaaviin asiasanoihin. Muussa tapauksessa en näe mitään idea kolmen erillisen asiasanan olemassaoloon sanastossa, koska juuri tuo sukupuolisuus on ainoa erottava tekijä näiden termien kesken.

**Comment by satuniininen** [comment]
LT-suhde löytyy YSOn puolelta eli _homot - homoseksuaalit - väestöryhmään liittyvä rooli jne_. 

_Naisten_ ja _miesten_ yläkäsitteenä on _sukupuoleen liittyvä rooli._

**Comment by jtuohini** [comment]
Mutta nuo alkujaan kaipaamani asiasanasuhteet puuttuvat ihan samalla tavalla YSOnkin puolelta! Jos **homot** viittaa homomiehiin, niiin miksei asiasanalla ole kyseistä KT-muotoa ja miksei sillä ole LT-suhdetta **miehet**-asiasanaan?

**Comment by jtuohini** [comment]
Tulipa tämä "homot"-termi vastaan, kun pykään Sisällönkuvailuoppaaseen 13. lukuun yhtä esimerkkiä ja rupesin pohtimaan taas tätä "miehet"-yläkäsitteen puutetta. Ja huomaan, että ehdotus näyttää menneen läpi 4.9.2018 – lähes päivälleen vuosi sitten –, mutta YSOn puolella ei siis suhdetta vielä näy…

**Comment by mirmaid** [comment]
YSA-kokouksessa on hyväksytty ohjaustermi homomiehet. YSA-kokouksissa ei yleensä käsitelty hierarkiaratkaisuja (varsinkaan YSOn osalta) - YSOssahan ehdotettu hierarkia olisi vähän ongelmallinen kuten Satu kirjoittaakin, koska miehet-käsitteen yläkäsite on sukupuoleen liittyvä rooli, mutta homo ei ole ensisijaisesti sukupuolikategoria. Koska tätä yläkäsitettä ei välttämättä mihinkään tarvita, pääsemme siis helpommalla jos emme sitä lisää.
