### ISSUE TITLE
lesbot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6046]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lesbot](http://www.yso.fi/onto/ysa/Y191768) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään asiasanalle LT-muoto "naiset" [http://www.yso.fi/onto/ysa/Y97617] 

#### Perustelut ehdotukselle   

Kaikki lesbot ovat naisia, mikä seikka olisi syytä tulla ilmi asiasanaston sanasuhteissa (ontologinen 'is a' -suhdevaatimus täyttyy). 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by satuniininen** [comment]
Sukupuoli- ja seksuaali-identiteettien määrittäminen ei ole näin mustavalkoista. Ehdotettu ratkaisu sulkee ulkopuolelleen kaikki sukupuolivähemmistöihin kuuluvat, jotka eivät sovi mies-nais-jaotteluun, esim. transihmiset, sukupuolettomat, intersukupuoliset jne.
