### ISSUE TITLE
trotskilaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6049]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

trotskilaisuus 

#### Ehdotettu termi ruotsiksi   

trotskism 

#### Ehdotettu termi englanniksi   

Trotskyism 

#### Vaihtoehtoiset termit ja ilmaisut   

trotskismi 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85029120> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

Yleinen käsite 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1465677 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [trotskilaisuus](http://finto.fi/yse/fi/page/Y506049)

**Comment by mirmaid** [comment]
31 viitettä Melindassa. LCSH: Use Communism
