### ISSUE TITLE
kantilaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6050]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kantilaisuus 

#### Ehdotettu termi ruotsiksi   

? 

#### Ehdotettu termi englanniksi   

Kantianism 

#### Vastaava käsite muussa sanastossa   

http://id.loc.gov/authorities/subjects/sh86007023 :  

#### Tarkoitusta täsmentävä selite   

Ks. https://fi.wikipedia.org/wiki/Kantilaisuus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

Hegeliläisyys, leninismi, marxismi, platonismi.... 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.431323 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [kantilaisuus](http://finto.fi/yse/fi/page/Y506050)

**Comment by mirmaid** [comment]
51 viitettä Melindassa

**Comment by mariaforsen** [comment]
Sv. kantianism
