### ISSUE TITLE
verkkodemokratia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6051]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkodemokratia](http://www.yso.fi/onto/ysa/Y177848) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT e-demokratia
mutta: e-demokratia http://finto.fi/ysa/fi/page/Y109847 

#### Perustelut ehdotukselle   

Termi ei voi olla yhtä aikaa sallittu ja kielletty! 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by ilona-x** [comment]
Tämä tilanne taisi syntyä, kun teledemokratia muutettiin muotoon e-demokratia https://github.com/Finto-ehdotus/YSE/issues/5305. Eli pitäisikö yhdistää verkkodemokratia ja e-demokratia?
Molemmilla paljon samoja ohjaustermejä:
http://finto.fi/ysa/fi/page/Y177848
http://finto.fi/ysa/fi/page/Y109847

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Elektroninen_demokratia
https://sv.wikipedia.org/wiki/E-demokrati

**Comment by YSA-kokous** [comment]
verkkodemokratia KÄ e-demokratia
