### ISSUE TITLE
nuoret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6052]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nuoret](http://www.yso.fi/onto/ysa/Y97685) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT: teini-ikäiset
mutta: teini-ikäiset http://finto.fi/ysa/fi/page/Y97542 

#### Perustelut ehdotukselle   

Termi ei voi olla yhtä aikaa sallittu ja kielletty! 

#### Ehdottaja   

Ville Huhtala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

ville.huhtala@helsinki.fi

**Comment by mirmaid** [comment]
Ohjaustermi poistettu.
