### ISSUE TITLE
lajiliitot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6053]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lajiliitot 

#### Perustelut ehdotukselle   

Kansainväliset ja kansalliset lajiliitot vastaavat oman lajinsa toiminnasta, kehittämisestä ja säännöistä.
https://www.suek.fi/en/kansainvaliset-ja-kansalliset-lajiliitot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.urheilututkimukset.fi/web/julkaisut/7089/ 

**Ehdottajan nimi:** Heidi Ronkainen 
**Ehdottajan sähköpostiosoite:** heidi.ronkainen@helsinki.fi **Termiehdotus Fintossa:** [lajiliitot](http://finto.fi/yse/fi/page/Y506053)

**Comment by mariaforsen** [comment]
Sv. grenförbund
