### ISSUE TITLE
motiivit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6056]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[motiivit](http://www.yso.fi/onto/ysa/Y97511) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko? 
-motiivit (teokset/aiheet tms.) 
-motiivit (vaikuttimet, syyt tms.) 

#### Perustelut ehdotukselle   

On monimerkityksinen termi ja nyt ryhmissä: 00, 87, 89, 90. 
KS: 1. vaikutin, syy, peruste. 2. (taideteoksen) aihe, aihelma
Melindassa käytetty molemmissa merkityksissä.
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5983 

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by ksornova** [comment]
Hei, musiikkiin liittyvät motiiveiista ks. [sävelmotiivit ](https://github.com/Finto-ehdotus/YSE/issues/5983)

**Comment by satuniininen** [comment]
Tai motiivit (aiheet) + vaikuttimet KT motiivit (vaikuttimet)

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:motiivi

**Comment by mirmaid** [comment]
motiivit (taide)?

**Comment by YSA-kokous** [comment]
motiivit (aihelmat)
vaikuttimet KT motiivit (vaikuttimet) TAI motiivit (vaikuttimet)

**Comment by ilona-x** [comment]
Kannattaisin muotoa motiivit (vaikuttimet)

motiivi: toiminnan sisäinen peruste tai vaikutin
http://tieteentermipankki.fi/wiki/Filosofia:motiivi

**Comment by YSA-kokous** [comment]
motiivit (vaikuttimet)
motiivit (aihelmat)

**Comment by mariaforsen** [comment]
Sv. 
motiv (orsaker)
motiv (ämnen)
