### ISSUE TITLE
yhteisjulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6058]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yhteisjulkaisut 

#### Ehdotettu termi englanniksi   

co-publishing 

#### Ehdotettu termi ruotsiksi   

sampublikationer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[julkaisut](http://www.yso.fi/onto/yso/p1548) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 
[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 

#### Perustelut ehdotukselle   

En keksi täsmällistä kiertoilmaisua. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suomen kansainvälinen yhteisjulkaiseminen http://urn.fi/URN:ISBN:978-952-263-097-1 ; International co-publishing in Finland http://urn.fi/URN:ISBN:978-952-263-133-6 

**Ehdottajan nimi:** Tatja Pusa 
**Ehdottajan sähköpostiosoite:** tatja.pusa@helsinki.fi **Termiehdotus Fintossa:** [yhteisjulkaisut](http://finto.fi/yse/fi/page/Y506058)

**Comment by mirmaid** [comment]
Käytetään myös ainakin rahoista ja postimerkeistä, mutta ei varmaan kuvailunäkökulmasta tuota ongelmaa?
