### ISSUE TITLE
Zavidovo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6061]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Zavidovo 

#### Ehdotettu termi ruotsiksi   

Zavidovo 

#### Ehdotettu termi englanniksi   

Zavidovo 

#### Perustelut ehdotukselle   

Politiikantutkimuksen ja poliittisen historian kannalta merkittävä venäläinen paikkakunta. Siellä käytiin aikanaan Suomen ja Neuvostoliiton välsiä neuvotteluja, joista vuodettiin tiedotusvälineille. Ks. esim.https://fi.wikipedia.org/wiki/Zavidovo-vuoto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.476721 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Zavidovo](http://finto.fi/yse/fi/page/Y506061)

**Comment by mirmaid** [comment]
Käytetty yleensä 653-kentässä muodossa _Zavidovo_ tai _Zavidovo-vuoto_. Voidaan auktorisoida, mutta lisätäänkö tarkenne, ja onko se (Konakovon piiri) vai (Tverin alue)?

**Comment by YSO-kokous** [comment]
Ehdotetaan YSO-kokoukselle: 
auktorisoidaan YSO-paikkojen sijaan YSOon muodossa "Zavidovo-vuoto" ja yläkäsitteeksi tietovuodot. Aineistot näissä tapauksissa liittynevät enemmän tietovuotoon, eivätkä niinkään paikkaan.

**Comment by mariaforsen** [comment]
Sv. Zavidovoaffären ET  Zavidovoläckan
https://www.uppslagsverket.fi/sv/sok/view-103684-Zavidovoaffaeren

**Comment by jarmosaarikko** [comment]
Yläkäsite: http://www.yso.fi/onto/yso/p24839  tietovuodot

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa "Zavidovo-vuoto" ja yläkäsitteeksi tietovuodot.
