### ISSUE TITLE
agentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6062]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[agentit](http://www.yso.fi/onto/ysa/Y110494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

poistetaan assosiatiivinen käsite "kaksoisagentit".  Jätetään vain vakoilijoiden alakäsitteeksi.    Agentit-käsitteelle olisi  ehkä hyvä lisätä skos:scopeNote -kenttä, jossa ilmaistaan rajaus mitä tässä kohtaa agenteilla tarkoitetaan. 

#### Perustelut ehdotukselle   

agentit (vakoilijat) on ohjausterminä termille "vakoilijat".  Agentit kuvaa tässä tapauksessä  vielä kahdenlaisia agentteja tietokoneohjelmien agentteja sekä muutosagentteja. Muutosagentit -termi löytyy YSE-ehdotuksena ja sen voisi ehkä lisätä omaksi käsitteekseen erotuksena noista tietokoneagenteista. 

#### Ehdottaja   

Jarmo Saarikko 

#### Ehdottajan organisaatio   

KK 

#### Ehdottajan sähköpostiosoite   

jarmo.saarikko@helsinki.fi

**Comment by jarmosaarikko** [comment]
Muutosagentit - [https://github.com/Finto-ehdotus/YSE/issues/1893] 
Esimerkiksi  "intelligent agents", "agent-based dss"   [https://fennica.linneanet.fi/vwebv/holdingsInfo?searchId=1955&recCount=10&recPointer=5&bibId=955531]

**Comment by jarmosaarikko** [comment]
Tämän issuen voi sulkea, sillä tätä käsitelläänkin jo aikaisemmassa issuessa  #4794
