### ISSUE TITLE
Törmäsjärvi (Tornionjoki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6063]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Törmäsjärvi (Tornionjoki) 

#### Vastaava käsite muussa sanastossa   

Järviwiki : https://www.jarviwiki.fi/wiki/T%C3%B6rm%C3%A4sj%C3%A4rvi 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa
Törmäsjärvi (Tornionjoki) <-> Törmäsjärvi (Kemijoki)
Huom. Tavallisesti käytetty maakuntaa erottimena, mutta molemmat järvet sijaisevat Lapin maakunnassa...
Mitä sanoo Maanmittauslaitoksen paikannimirekisteri? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1858171 

#### Tarkoitusta täsmentävä selite   

Järvi Ylitorniolla 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Törmäsjärvi (Tornionjoki)](http://finto.fi/yse/fi/page/Y506063)

**Comment by ilona-x** [comment]
Kyseinen järvi sijaitsee Ylitornion kunnassa, joten auktorisoin sen YSAan muodossa Törmäsjärvi (Ylitornio).
Toinen Lapin Törmäsjärvistä sijaitsee Posion kunnassa, ja se on nyt auktorisoitu muodossa Törmäsjärvi (Posio)
