### ISSUE TITLE
Törmäsjärvi (Kemijoki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6064]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Törmäsjärvi (Kemijoki) 

#### Vastaava käsite muussa sanastossa   

Järviwiki : https://www.jarviwiki.fi/wiki/T%C3%B6rm%C3%A4sj%C3%A4rvi 

#### Tarkoitusta täsmentävä selite   

Järvi Posiolla 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa
Törmäsjärvi (Tornionjoki) <-> Törmäsjärvi (Kemijoki)
Huom. Tavallisesti käytetty maakuntaa erottimena, mutta molemmat järvet sijaisevat Lapin maakunnassa...
Mitä sanoo Maanmittauslaitoksen paikannimirekisteri? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1858171 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Törmäsjärvi (Kemijoki)](http://finto.fi/yse/fi/page/Y506064)

**Comment by ilona-x** [comment]
Auktorisoitu Ysaan muodossa Törmäsjärvi (Posio)
