### ISSUE TITLE
Halhin-Golin taistelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6065]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Halhin-Golin taistelut 

#### Ehdotettu termi ruotsiksi   

Slaget om Chalchin-Gol 

#### Ehdotettu termi englanniksi   

Battles of Khalkhin Gol 

#### Perustelut ehdotukselle   

Melindassa on käytetty tätä termiä jo neljä kertaa ilman, että tämä kuluisi virallisesti YSA:an. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kansalliskirjasto.finna.fi/Record/helka.3139181 

**Ehdottajan nimi:** Victoria Kurkina 
**Ehdottajan sähköpostiosoite:** victoria.kurkina@helsinki.fi **Termiehdotus Fintossa:** [Halhin-Golin taistelut](http://finto.fi/yse/fi/page/Y506065)

**Comment by mariaforsen** [comment]
Sv. slaget om Chalchin-Gol ET slaget vid Chalchin-Gol
