### ISSUE TITLE
Indiana (osavaltio)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6071]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Indiana (osavaltio) 

#### Ehdotettu termi englanniksi   

Indiana 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/n79022925 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Indiana (osavaltio)](http://finto.fi/yse/fi/page/Y506071)

**Comment by vthuhtala** [comment]
Yläkäsite 'Yhdysvallat'
