### ISSUE TITLE
Missouri (osavaltio)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6076]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Missouri (osavaltio) 

#### Ehdotettu termi englanniksi   

Missouri 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/n79029210 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Missouri (osavaltio)](http://finto.fi/yse/fi/page/Y506076)

**Comment by mirmaid** [comment]
Osavaltio ja samanniminen joki.

**Comment by mirmaid** [comment]
Lisätään tarkenne.
