### ISSUE TITLE
Nevada (osavaltio)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6078]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Nevada (osavaltio) 

#### Ehdotettu termi englanniksi   

Nevada 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/n79072716 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Nevada (osavaltio)](http://finto.fi/yse/fi/page/Y506078)

**Comment by mirmaid** [comment]
Millä periaatteella osavaltioille lisätään jatkossa tarkenteita?
