### ISSUE TITLE
robottiaseet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6084]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[robottiaseet](http://www.yso.fi/onto/ysa/Y200847) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT autonomiset aseet, autonomiset asejärjestelmät

Tai vaihtoehtoisesti päätermin muutos. Kyseessä on paljolti sama käsite, mutta _robottiaseet_ on nimityksenä kansankielisempi. 

#### Perustelut ehdotukselle   

Myös näitä termimuotoja käytetään, eivätkä ne tällä hetkellä ohjaudu mihinkään. 

Esim. http://formin.finland.fi/public/default.aspx?contentid=318336

Asia nousi esiin kuvailtaessa teosta _Autonomous weapons systems and international humanitarian law : ‘out of the loop’?_ / Jarna Petman.

#### Ehdottaja   

Satu Niininen 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

satu.niininen@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. robotvapen

**Comment by EsaMPKK** [comment]
Hyvä pitää kansankielinen ilmaus pääterminä ja lisätä nuo KT:t.

**Comment by YSA-kokous** [comment]
Esa selvittää, seuraava kokous

**Comment by EsaMPKK** [comment]
Kysyin asiantuntijalta, jonka mielestä robottiaseet (tai robottiasejärjestelmät) on hyvin käyttökelpoinen.

Kun tähän vielä tuli tuo robottiasejärjestelmät, se voisi olla vaikkapa KT.

**Comment by YSA-kokous** [comment]
KT autonomiset aseet, autonomiset asejärjestelmät
