### ISSUE TITLE
Helgö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6085]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Helgö 

#### Ehdotettu termi ruotsiksi   

Helgö 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://sv.wikipedia.org/wiki/Helg%C3%B6 

#### Perustelut ehdotukselle   

Melindassa on paljon Helgötä käsittelevää arkeologista kirjallisuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helgö revisited : a new look at the excavated evidence for Helgö, central Sweden / by Helen Clarke and Kristina Lamm. 

#### Tarkoitusta täsmentävä selite   

Saari Mälarenissa, Tukholman läänissä. Helgölla sijaitsee tunnettu muinaisjäännösalue. 

**Ehdottajan nimi:** Hannele Dahl 
**Ehdottajan organisaatio:** Museoviraston kirjasto 
**Ehdottajan sähköpostiosoite:** hannele.dahl@museovirasto.fi **Termiehdotus Fintossa:** [Helgö](http://finto.fi/yse/fi/page/Y506085)

**Comment by YSO-kokous** [comment]
Ks. https://github.com/Finto-ehdotus/YSE/issues/6306

**Comment by mirmaid** [comment]
Helgö (Ekerö)
