### ISSUE TITLE
androidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6086]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

androidit 

#### Ehdotettu termi ruotsiksi   

androider 

#### Ehdotettu termi englanniksi   

androids 

#### Ehdotettu yläkäsite YSOssa (LT)   

[robotit](http://www.yso.fi/onto/yso/p2619) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85004921 
Wikipedia : https://fi.wikipedia.org/wiki/Androidi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Tarkoitusta täsmentävä selite   

Androidi on ihmistä muistuttava robotti. 

#### Perustelut ehdotukselle   

Ihmisen muotoiset robotit ovat nykyisin paljon esillä. Pelkkä robotti ei riitä kuvaamaan androideja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Living with robots 

**Ehdottajan nimi:** Anneli Korhonen 
**Ehdottajan organisaatio:** Hämeen ammattikorkeakoulun kirjasto 
**Ehdottajan sähköpostiosoite:** anneli.korhonen@hamk.fi **Termiehdotus Fintossa:** [androidit](http://finto.fi/yse/fi/page/Y506086)

**Comment by mirmaid** [comment]
Kaunokissa, Melindassa tietoaineistossa 2 kertaa.
