### ISSUE TITLE
roudaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6087]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

roudaus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Roudarit: vastuun ja kamojen kantoa jo vuodesta 1965 

#### Perustelut ehdotukselle   

Myös roudarit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan nimi:** BTJ 
**Ehdottajan sähköpostiosoite:** mirja.anttila@helsinki.fi **Termiehdotus Fintossa:** [roudaus](http://finto.fi/yse/fi/page/Y506087)

**Comment by tpalonen** [comment]
LYHYESTI
Ehdotan: käytettävä termi **roudarit**, ohjaustermi **roudaus**

PITKÄSTI
Itse kuvittelisin mutu-tuntumalta ja em. kirjaa vielä näkemättä, että roudarit olisi yleisesti tarpeellisempi käsite ja tulokulma kuin roudaus ajatellen potentiaalista tiedontarvetta ja sitä mihin aiheeseen kirjallisuus todennäköisemmin keskittyy. Pidän todennäköisempänä, että kirjoitetaan roudareista henkilökuvia tai anekdootteja, miten he ovat edenneet urallaan, minkälainen heidän suhteensa on artistiin jne (tästä näkee joskus kirjoitettavan rock-lehdissä) kuin että kirjoitettaisiin "persoonattomasti" roudaamisesta toimintana, roudausoppaita, roudauksen sosiologisesta näkökulmasta tms. Toisaalta kirjoittamisen aiheena voi toki olla "roudauskulttuuri" ja siihen liittyvä lore, mutta siinäkin minusta roudarit voisi olla ihan sopiva: luulisi että tällaisissa tarinoissa aina mainitaan mistä roudarista tai vähintäänkin minkä artistin roudarista oli kyse. Ja tuskin ainakaan tarvitsee kahta eri käsitettä (roudarit, roudaus) näin spesifistä aiheesta.

**Comment by mariaforsen** [comment]
Sv. roadies ET roadare, roudare
