### ISSUE TITLE
argentiinalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6089]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

argentiinalaiset 

#### Ehdotettu termi englanniksi   

Argentines 

#### Ehdotettu yläkäsite YSOssa (LT)   

[latinalaisamerikkalaiset](http://www.yso.fi/onto/yso/p7711) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85007098 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2260592 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [argentiinalaiset](http://finto.fi/yse/fi/page/Y506089)

**Comment by mariaforsen** [comment]
Sv. argentinare
