### ISSUE TITLE
aimarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6090]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aimarat 

#### Vaihtoehtoiset termit ja ilmaisut   

aymarat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[intiaanit](http://www.yso.fi/onto/yso/p646) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85010615 
Wikipedia : https://fi.wikipedia.org/wiki/Aimarat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Andeilla elävä kansa. Aimaroita asuu Bolivian, Perun, Pohjois-Chilen ja Pohjois-Argentiinan alueella. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.459568 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [aimarat](http://finto.fi/yse/fi/page/Y506090)

**Comment by mariaforsen** [comment]
Sv. aymara (folk)
