### ISSUE TITLE
Barbie-nuket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6091]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Barbie-nuket 

#### Ehdotettu termi englanniksi   

Barbie dolls 

#### Ehdotettu yläkäsite YSOssa (LT)   

[nuket](http://www.yso.fi/onto/yso/p4588) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85011802 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.853839 

**Ehdottajan nimi:** Ville Huhtala 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** ville.huhtala@helsinki.fi **Termiehdotus Fintossa:** [Barbie-nuket](http://finto.fi/yse/fi/page/Y506091)

**Comment by mariaforsen** [comment]
Sv. barbiedockor
