### ISSUE TITLE
orkesterimuusikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6102]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

orkesterimuusikot 

#### Ehdotettu termi ruotsiksi   

orkestermusiker 

#### Assosiatiiviset (RT)   

[esittäjät](http://www.yso.fi/onto/yso/p1289) 

#### Perustelut ehdotukselle   

Orkesterimuusikot ovat selkeä ammattiryhmä. Muusikot -alakäsitteenä on muita ammattiryhmiä kuten tanssimuusikot, teatterimuusikot ja kirkkomuusikot. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finna.fi/Record/eepos.177948 

**Ehdottajan nimi:** Pauliina Isomäki 
**Ehdottajan organisaatio:** Turun ammattikorkeakoulu 
**Ehdottajan sähköpostiosoite:** pauliina.isomaki@turkuamk.fi **Termiehdotus Fintossa:** [orkesterimuusikot](http://finto.fi/yse/fi/page/Y506102)

**Comment by ksornova** [comment]
Muusa-ryhmän kokous (15.5.2018): kannatetaan. LT muusikot

**Comment by tpalonen** [comment]
Tanssiorkesterissa soittavat muusikot eivät liene orkesterimuusikoita? Ts. tanssimuusikot eivät liene orkesterimuusikkojen alakäsite?
