### ISSUE TITLE
vedostus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6108]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vedostus](http://www.yso.fi/onto/ysa/Y101455) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko:
-vedostus (paino?)
-vedostus (valokuvaus) 

#### Perustelut ehdotukselle   

Todettu YSO-kokouksessa. On monimerkityksinen ja ainakin ruotsiksi eri termejä eri merkityksille (nykyinen vastine ei sovi Melinda-tietueisiin). Eng. nyt "printing (graphics and photography)". 

Vrt. esim. Graafisen alan sanasto: 
Vedostus="Tekstin, kuvan, sivun tai koko painoarkin kopiointi tai erillinen tulostaminen tarkistusta varten."
Ja valokuvaussanasto:
Vedostus="Valokuvan valmistaminen valokuvapaperille. Vedostuksen vaiheita ovat 
paperin  valotus,  kehitys,  keskeytys  ja  kiinnitys  sekä  lopuksi  pesu." 

Melindassa ainakin kaksi eri tyyppiä esim.:
-Mustavalkokuvaus ja työnkulku / Markku Saiha.
-Syväpaino : metalligrafiikan uudet ja perinteiset menetelmät / Tuula Lehtinen.

#### Ehdottaja   

Maria Forsén 

#### Ehdottajan sähköpostiosoite   

maria.forsen@abo.fi

**Comment by mirmaid** [comment]
Esim. https://melinda.kansalliskirjasto.fi/byid/006533240

**Comment by ilona-x** [comment]
Vaihtoehtoiset vedostusmenetelmät valokuvauksessa ja taidegrafiikassa
http://urn.fi/URN:NBN:fi:amk-201003062974

**Comment by ilona-x** [comment]
- **vedostus (valokuvaus/valokuvat?)**
- **vedostus (taidegrafiikka?)** -Painolevyltä taiteilija vedostaa varsinaisen teoksen paperille tai muulle alustalle.  https://fi.wikipedia.org/wiki/Taidegrafiikka
- **vedostus (kirjapaino?)** -Tekstin, kuvan, sivun tai koko painoarkin tulostaminen tarkistusta varten.

vedostus (digitaalikuvaus) KÄYTÄ tulostus

**Comment by ilona-x** [comment]
**vedostus (taidegrafiikka)**

"Taidegrafiikka on yleisnimitys menetelmille, joissa erilaisilta painolevyiltä vedostetaan kuva paperille tai muulle materiaalille." 

"Taidegrafiikan menetelmät jaetaan perinteisesti neljään eri ryhmään sen mukaan, mihin osaan laatasta painoväri jää ja miltä se siirtyy painettaessa paperiin. Taidegrafiikan menetelmien pääryhmät ovat: kohopaino-, syväpaino-, ja laakapainomenetelmät sekä serigrafia. Pääperiaatteena on, että jokainen vedos on itsenäinen taideteos. Taidegrafiikka ei jäljennä olemassa olevaa taideteosta."

Lähde: https://www.taidegraafikot.fi/suomen-taidegraafikot-ry/taidegrafiikka/

YSAssa on **kohopaino**, **syväpaino**, **laakapaino** & **serigrafia**
lisäksi YSAssa taidegrafiikka KÄYTÄ **grafiikka**

Esimerkkejä Melidasta:

- I'm fine : taiteellinen tutkimus variaatioiden vedostamisesta ja kertomus surutyöstä taiteen tekemisen prosessissa
- Syväpaino : metalligrafiikan uudet ja perinteiset menetelmät 
- Taidelitografia : kivipiirros, offsetlitografia
- Intaglio : acrylic-resist etching collagraphy engraving drypoint mezzotint : the complete safety-first system for creative printmaking

**Comment by ilona-x** [comment]
**vedostus (valokuvaus/valokuvat?)**

Valokuvan valmistaminen valokuvapaperille. Vedostuksen vaiheita ovat paperin valotus, kehitys, keskeytys ja kiinnitys sekä lopuksi pesu. Vedos voidaan myös sävyttää. Lopuksi vedos kuivataan kuivurilla tai jätetään ilmavaan paikkaan kuivumaan.

lähde: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&ved=2ahUKEwio5eW3jNnhAhUKxYsKHdr1B24QFjAHegQIBxAC&url=https%3A%2F%2Fwww.valokuvataiteenmuseo.fi%2Fsites%2Fdefault%2Ffiles%2Finline-attachments%2F2017-04%2Fpimio_sanasto_su_mv_02092015.pdf&usg=AOvVaw0Knkk41CvjFM0mEtggVw9E

Esimerkkejä Melindasta:

- The book of alternative photographic processes 
- Photographic possibilities :the expressive use of equipment, ideas, materials, and processes 
- The wet collodion plate :16 steps to making the plates 
- Raw-työnkulku 
- A return to craft 
- Vedostuksen hurma

**Comment by ilona-x** [comment]
**vedostus (kirjapaino)**

"Tekstin, kuvan, sivun tai koko painoarkin tulostaminen tarkistusta varten."
Lähde: https://www.graafinen.com/tietopankki/sanasto/

Esimerkkejä Melindasta: 

- Varmennettu etävedostus.
- Canon Concerto Stockholm.
- Vastaako asiakasvedos sopimusvedosta?
- Sisältövedostusta vai väritarkkaa vai sopimusvedostusta? :vedoksella on rooli laadunvalvonnassa

**Comment by ilona-x** [comment]
Lisäksi Melindassa viitteitä, joihin sopisi mahdollisesti useampi vaihtoehto:

- Valosta :vaihtoehtoiset vedostusmenetelmät valokuvauksessa ja taidegrafiikassa 
- Portfolio :taidegrafiikkaa ja käsintehtyä paperitaidetta, dokumentaatiovalokuvia muinaistaiteesta, vaihtoehtoisia vedostusmenetelmiä = Printmaking and hand made paper art, documentation photographs of ancient art, alternative printing processes 
- The last layer :new methods in digital printing for photography, fine art and mixed media

Myös tietueita, joista vedostuksen voisi poistaa, ilman suurempaa haittaa, esimerkiksi:

- Omat kuvat kirjaksi : Koti & Tyyli testasi kolme kuvakirjapalvelua
- Omat valokuvat kirjaksi :Kuvatkirjaksi.fi A4 Select.
- Omat valokuvat isoina seinälle :näin teetät valokuvistasi tauluja ja julisteita.

**Comment by YSA-kokous** [comment]
vedostus (valokuvaus)
vedostus (kirjapaino)
vedostus (taidegrafiikka)

**Comment by mariaforsen** [comment]
Sv.
-framkallning och utskrift av fotografier
-provtryckning (boktryck) ET avdragning (kontrolltryckning)
-tryckning (konstgrafik) ET avdragning (konstgrafik)
