### ISSUE TITLE
metsästyssignaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6110]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsästyssignaalit 

#### Ehdotettu termi englanniksi   

hunting signals 

#### Ehdotettu termi ruotsiksi   

jaktsignaler 

#### Ehdotettu yläkäsite YSOssa (LT)   

[signaalit](http://www.yso.fi/onto/yso/p25766) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[23 Erätalous. Kalastus. Metsästys](http://www.yso.fi/onto/yso/p26561) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2640394 

#### Tarkoitusta täsmentävä selite   

"Jaktsignaler används för att leda jaktsällskapets rörelser, underrätta kamraterna om jaktens gång och vilket djurslag som drivs samt för att kalla in hundarna." [https://sv.wikipedia.org/wiki/Jakthorn] 

#### Perustelut ehdotukselle   

Riittävän osuvaa termiä ei ole vanhastaan sanastoissa, ja lisäksi tarvitaan sekä YSA/YSO:n että SLM:n puolella 

**Ehdottajan nimi:** Jaakko Tuohiniemi 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** jaakko.tuohiniemi@helsinki.fi **Termiehdotus Fintossa:** [metsästyssignaalit](http://finto.fi/yse/fi/page/Y506110)

**Comment by mirmaid** [comment]
Kerran Melindassa (merkitty slm-sanastoon), Googlellakin vain kourallinen viitteitä.

**Comment by asormune** [comment]
Kuuluuko termi 89 Musiikki -ryhmään lainkaan?

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa käsitteen ottamista sekä SLM:ään että YSAAn.
