### ISSUE TITLE
Emajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6111]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Emajoki 

#### Ehdotettu termi ruotsiksi   

Emajõgi 

#### Ehdotettu termi englanniksi   

Emajõgi 

#### Vaihtoehtoiset termit ja ilmaisut   

Viroksi Emajõgi 
 
 

#### Perustelut ehdotukselle   

Helkassa useita Emajokea käsitteleviä julkaisuja. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Emaj%C3%B5gi
Suomen kieleen on no.  vakiintunut muoto Emajoki. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2429129 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Emajoki](http://finto.fi/yse/fi/page/Y506111)

**Comment by mirmaid** [comment]
Jokien yläkäsitteet (Viro/Tartumaa)?
