### ISSUE TITLE
Itä-Virumaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6118]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Itä-Virumaa 

#### Ehdotettu termi ruotsiksi   

Östra Wierland 

#### Ehdotettu termi englanniksi   

Ida-Virumaa 

#### Vaihtoehtoiset termit ja ilmaisut   

Englanniksi Ida-Virumaa County 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n93018860> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Ida-Viru_maakond 

#### Perustelut ehdotukselle   

Kannattanee valita suomeksi muoto 'Itä-Virumaa' eikä 'Ida-Virumaa', koska se on kieleemme vakiintunut. Itä-Virumaa ei ole varsinainen maakunta vaan no. hallinnollinen yksikkö. Historiallinen Virumaan maakunta on jaettu hallinnollisesti kahti itäiseksi ja läntiseksi Virumaaksi. Vaikka itse Virumaa on historiallinen käsite, käytetään sitä yleisesti maan itäosasta puhuttaessa. Helkasta löytyy 30 tietuetta, joista löytyvät  merkkijonot 'Itä-Virumaa' tai 'Ida-Virumaa'. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1233669 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Itä-Virumaa](http://finto.fi/yse/fi/page/Y506118)

**Comment by paivalai** [comment]
Jäi pois: LSCH ei tunne termiä 'Ida-Viru County', vaan pelkän Ida-Virumaan.
