### ISSUE TITLE
Põlvamaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6121]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Põlvamaa 

#### Ehdotettu termi ruotsiksi   

Põlvamaa 

#### Ehdotettu termi englanniksi   

Põlvamaa 

#### Vaihtoehtoiset termit ja ilmaisut   

Englanniksi Põlva county - LCSH tosin tuntee vain termin 'Põlvamaa' 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/no2002034393> 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/P%C3%B5lva_maakond 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Yksi Viron maakunnista. Hallinnollisena yksikkönä sen virallinen nimi on 'Põlva maakond', mutta jo kaikki aiemmat YSA:sta löytyvät Viron maakunnat ovat sanastossa omilla maantieteellisillä nimillään ilman maakond-tarkennusta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1718879 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Põlvamaa](http://finto.fi/yse/fi/page/Y506121)

**Comment by paivalai** [comment]
Unohtui: Helkasta köyty 18 tietuetta, joissa on merkkijono Põlvamaa-alkuinen.
