### ISSUE TITLE
Gammalsvenskby

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6127]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Gammalsvenskby 

#### Ehdotettu termi ruotsiksi   

Gammalsvenskby 

#### Ehdotettu termi englanniksi   

Gammalsvenskby 

#### Vaihtoehtoiset termit ja ilmaisut   

LCSH: Staroshvedsʹke (Ukraine) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n82077937> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://sv.wikipedia.org/wiki/Gammalsvenskby 

#### Perustelut ehdotukselle   

Aikoinaan vironruotsalaisten 1700-luvulla nykyisen Ukrainan alueelle perustama kylä, jossa edelleenkin puhutaan jonkin verran Ruotsia. Helkasta löytyy kolme tietuetta, joissa se on asiasanana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1912820 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Gammalsvenskby](http://finto.fi/yse/fi/page/Y506127)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa Gammalsvenskby. Sulkutarkennetta ei tarvita, koska viittaa historialliseen paikkaan eikä samannimistä käsitettä ole sanastossa (eikä myöskään esim. Wikipediassa). Yläkäsitteeksi Ukraina.
