### ISSUE TITLE
soolot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6130]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[soolot](http://www.yso.fi/onto/ysa/Y104367) 

#### Tila   

Käsittelyssä 

#### Ehdottaja   

Katerina Sornova 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdottajan sähköpostiosoite   

katerina.sornova@helsinki.fi 

#### Ehdotettu muutos   

muutetaan muotoon "soolosävellykset" (tällä hetkellä KT) 

#### Perustelut ehdotukselle   

selkeyttää termin tarkoitusta. YSO-ryhmän ehdotus

**Comment by asormune** [comment]
Meillä on asiasanoitettu esim. jazz-soolojen transkriptioita sisältäviä nuotteja "soolot" asiasanalla. Onko tarkoitus poistaa kokonaan termi "soolot", vai voisiko sitä käyttää improvisoidun musiikin yhteydessä?
Termi "soolosävellykset" ei mielestäni ole hyvä kuvaamaan "improvisoitua sooloa".

**Comment by ilonahei** [comment]
YSA:n puolella soolosävellykset on varmasti hyvä ja selkeyttävä muutos. Nuottijulkaisuissa soolot-termiä on käytetty tosiaan muissakin merkityksissä, kuten nuo transkriboidut soolot ja myös yhdelle soittimelle sovitetut sävelmät. SLM:ssä pitäisi nekin ottaa huomioon.

**Comment by jtuohini** [comment]
Yhdelle esittäjälle tehty teos voidaan jatkossa kuvailla osakentän 382 |s arvolla "1", jolloin kentässä 655 ilmaistaisiin vain teoksen muoto (mikäli se on määriteltävissä) ja/tai musiikinlaji. Nythän asiasanalla **soolot** (jatkossa **soolosävellykset**?) on kuvailtu muut kuin sonaatit, sarjat jne. Tarve erottelulle on lisäksi erilainen 650- ja 655-kentissä?

**Comment by MUUSA-kokous** [comment]
Alkuperäinen ehdotus hyväksytty.
SLM:ssä säilytetään muoto _soolot_.

**Comment by MUUSA-kokous** [comment]
Ks. https://github.com/Finto-ehdotus/YSE/issues/6476
_"Muusan ehdotus:
Luodaan YSAan ja SLM:ään uusi käsite "soolo-osuudet", tälle ohjaustermiksi "soolot (soolo-osuudet)".
Muutetaan YSAan ja SLM:ään "soolot" käsitteen käytettävä termi muotoon "soolosävellykset", tälle ohjaustermiksi "soolot (soolosävellykset)"."_
