### ISSUE TITLE
Kingisepp

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6135]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kingisepp 

#### Ehdotettu termi ruotsiksi   

Kingisepp 

#### Ehdotettu termi englanniksi   

Kingisepp 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/no2012124792> 

#### Perustelut ehdotukselle   

Kaupunki Venäjällä muutaman kymmen kilometriä Narvasta itään. Sai vuonna 1922 uuden nimen 'Kingisepp' virolaisen kommunistin mukaan. Aiemmin nimi oli venäjäksi Jamburg (HUOM.! Siperiassa on nykyään myös Jamburg) ja viroksi Jaama. Helkassa Kingisepp voisi olla olla yhdessä tietuessa asiasanana. Assosiatiivisena käsitteenä YSA:ssa voisi siis olla Jaama, ja miksei Jamburgikin, vrt. Leningrad -- Pietari). 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Kingissepp 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.967520 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Kingisepp](http://finto.fi/yse/fi/page/Y506135)

**Comment by mirmaid** [comment]
Ulkomaisista paikoista auktorisoidaan kaupungit ja valtiot, kotimaisista kylät ja sitä suuremmat paikat. Muita paikkoja auktorisoidaan, jos paikkakäsitteelle on toistuva tarve kuvailussa. https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSO-paikat

**Comment by mirmaid** [comment]
Sanastossa on Jaama KT Kingisepp.
