### ISSUE TITLE
orkesteriharjoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6138]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[orkesteriharjoitukset](http://www.yso.fi/onto/ysa/Y214817) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "orkesterisoiton harjoitusaineistot" tai "orkesterisoittoharjoitteet" tms, englanninnoksenaan "exercises for orchestral playing", ja otetaan se myös SLM:ään. Jos termillä ei kuitenkaan katsota olevan tarvetta YSAn/YSOn puolella, pidetään se vain SLM:ssä ja poistetaan edellisestä. 

#### Perustelut ehdotukselle   

Termin pitää olla sanamuodoltn riittävän yksiselitteinen, ettei se vahingossakaan sekoitu tarkoittamaan harjoituksia, siis niitä tilanteita, jossa harjoitellaan yhdessä orkesterisoittoa. 

#### Ehdottaja   

Jaakko Tuohiniemi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Ehdottajan sähköpostiosoite   

jaakko.tuohiniemi@helsinki.fi

**Comment by mariaforsen** [comment]
Sv. ? kysytään Sibeliusmuseon asiantuntijoilta

**Comment by ilonahei** [comment]
Pelkkä harjoitusaineistot ei mitenkään riitä. Kyseessä on aivan tietyntyyppinen aineisto, jota käytetään orkesteriteosten harjoitteluun ja orkesterin koesoittoihin valmistautumiseen, ja se eroaa merkittävästi muusta nuottimuodossa julkaistujen harjoitusaineistojen massasta.

**Comment by MUUSA-kokous** [comment]
Muusa ehdottaa: poistetaan sanastosta orkesteriharjoitukset. Harjoitusaineistot on riittävä Muusan näkökulmasta YSAn puolella.

SLM:ään otetaan orkesterisoiton harjoitusaineistot. KT-muodoksi orkesterisoittoharjoitteet. Poimitaan määritelmä YSAn nykyisestä orkesteriharjoitukset-käsitteestä.

**Comment by satuniininen** [comment]
Osaisiko Muusa ehdottaa engl. vastinetta orkesterisoiton harjoitusaineistoille?

**Comment by asormune** [comment]
Kävisikö: Orchestral excerpts (ja Orchestra studies)
Kongressin auktoriteeteissa on mm:
LCCN Permalink: | https://lccn.loc.gov/sh85011846
150 | __ \|a Baritone (Musical instrument) \|v Orchestral excerpts
450 |__ \|w nne \|a Baritone (Musical instrument) \|v Orchestra studies

**Comment by jtuohini** [comment]
http://id.loc.gov/authorities/subjects/sh99001699

**Comment by MUUSA-kokous** [comment]
Käsitteelle ei löydy suoraa englanninkielistä vastinetta.

**Comment by jtuohini** [comment]
Tai siis ei löytynyt suoraa siltausvastinetta LCGFT:stä, mutta LCSH:hon viitaten englanninkielinen termi muuten olisi tuo Anun linkittämä "orchestra studies"! (Itse ymmärsin Sadun kysymyksen tarkoittavan siltausvastinetta, ja nyt tuli mieleen, josko tarkoittaisi vai käännösvastinetta.)

**Comment by satuniininen** [comment]
Käännösvastinetta tarkoitin, pitääpä yrittää jatkossa muotoillla vähemmän ympäripyöreästi. Vaikka toki siltausvastineenkin saa aina antaa kaupan päälle, jos sellainen sattuu löytymään.

**Comment by mirmaid** [comment]
orkesterisoiton harjoitusaineistot / SLM

**Comment by mariaforsen** [comment]
Sv. övningsmaterial för orkesterspel
