### ISSUE TITLE
Jumindan taistelu -- 1941

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6141]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Jumindan taistelu -- 1941 

#### Ehdotettu termi ruotsiksi   

slaget vid Juminda -- 1941 (?) 

#### Ehdotettu termi englanniksi   

Battle of Juminda -- 1941 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taistelut](http://www.yso.fi/onto/yso/p920) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Tarkoitusta täsmentävä selite   

https://ems.elnet.ee/   ----    (Juminda miinilahing) 

#### Perustelut ehdotukselle   

Vaihtoehtoinen ehdotus aiemmin lähettämälleni Jumindan niemelle.Juminda ts. Jumindan niemi (vir. Juminda poolsaar) on Viron pohjoisrannikolla oleva niemi.Helkasta löytyy yksi tietue, jossa sitä on käytetty asiasanana. Helkasta löytyvä kirja käsittelee Jumindan meritaistelua 1941, joten se toki voisi olla asiasanavaihtoetona, 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2033323 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Jumindan taistelu -- 1941](http://finto.fi/yse/fi/page/Y506141)

**Comment by mirmaid** [comment]
Google englanniksi jkvr Juminda sea battle, muutaman kerran Juminda mine battle, suomeksi muutama yksittäinen Jumindan (meri)taistelu tai Jumindan miinataistelu. 

https://fi.wikipedia.org/wiki/Tallinnan_evakuointi
