### ISSUE TITLE
Kadriorg

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6142]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kadriorg 

#### Ehdotettu termi ruotsiksi   

Kadriorg 

#### Ehdotettu termi englanniksi   

Kadriorg 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh93002866> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Kadriorg 

#### Perustelut ehdotukselle   

Kadriorg on Tallinnan kaupunginosa. Helkasta löytyy 15 tietuetta, joissa se on asiasanana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1519836 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Kadriorg](http://finto.fi/yse/fi/page/Y506142)

**Comment by paivalai** [comment]
HUOM! Yläkäsite on Tallinna.

**Comment by paivalai** [comment]
Lisätarkennus: Kadriorg on asuinalue Kesklinnan kaupunginosassa, mutta hierarkia on kuitenkin Tallinna > Kadriorg (vrt. Helsinki > Jollas).
