### ISSUE TITLE
Endla järv

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6154]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Endla järv 

#### Ehdotettu termi ruotsiksi   

Endla järv 

#### Ehdotettu termi englanniksi   

Endla järv 

#### Vaihtoehtoiset termit ja ilmaisut   

Endlajärvi 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Endla_j%C3%A4rv 

#### Perustelut ehdotukselle   

Endla järv on Jõgevamaalla sijaitseva järvi. Yhdessä Helkan tietueessa se on asiasanana, tosin pelkkänä Endlana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1777789 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Endla järv](http://finto.fi/yse/fi/page/Y506154)

**Comment by paivalai** [comment]
Sittenkin parempi ehdottaa no. suomenkielistä muotoa Endlajärvi 651-kenttään.

**Comment by mirmaid** [comment]
Endla voi tarkoittaa myös kylää tai luonnonsuojelualuetta. Endla järv on Viron 18. suurin järvi (2,9 km2). 2 viitettä Melindassa, toinen liittyy selvästi järveen.

https://www2.maaturism.ee/index.php?id=kannattaa-katsoa&sid=252

**Comment by YSO-kokous** [comment]
Selvitetään Kotukselta, mikä olisi suositeltava termi suomeksi ja ruotsiksi. @tpalonen

**Comment by YSO-kokous** [comment]
Kotuksen vastauksen perusteella nimi olisi suomeksi Endla järv, koska muuta muotoa ei ole vakiintunut suomeksi:

_perusohjeen mukaan ulkomaiden paikannimistä käytetään alkuperäiskielisiä nimiä, jos suomeksi tai ruotsiksi ei ole käytössä vakiintunutta sovinnaisnimeä eli eksonyymiä. Viron paikannimistä käytössä olevat suomenkieliset eksonyymit on lueteltu ohjepankin ohjeessa Viron paikannimet: suomeen mukautettu vai vironkielinen nimiasu? (http://www.kielitoimistonohjepankki.fi/haku/viro/ohje/514) ja ne löytyvät myös julkaisustamme Eksonyymit (http://kaino.kotus.fi/eksonyymit/index.php?a=etusivu). Ruotsinkieliset vakiintuneet eksonyymit on lueteltu verkkosivuillamme (https://www.sprakinstitutet.fi/sv/sprakhjalp/namnhjalp/ortnamn/svenska_ortnamn_i_estland)._

_Käännöstä Endlan järvi on käytetty joillakin Viron suomenkielisillä matkailusivustoilla, mutta se ei kuitenkaan ole vakiintunut ilmaus. Lauseyhteydessä vironkielisten nimien loppuosat on joskus luontevaa kääntää suomeksi, esimerkiksi Soutelimme Ahjajoella ( < Ahjajõgi). Ontologiassa on kuitenkin hyvä käyttää aina vironkielistä nimeä kirjoitusasuineen silloin, kun paikasta ei ole käytössä yllä mainituissa julkaisussa esiintyvää eksonyymiä (siis esimerkiksi Endla järv)._
