### ISSUE TITLE
sotatulokkaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6162]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sotatulokkaat 

#### Ehdotettu termi englanniksi   

polemochores 

#### Ehdotettu termi ruotsiksi   

krigstidsinkomlingar 

#### Vaihtoehtoiset termit ja ilmaisut   

polemokorit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tulokaslajit](http://www.yso.fi/onto/yso/p2994) 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Nimitys:sotatulokas> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

Tulokas (kasvi), joka on saapunut alueelle sotajoukkojen mukana 

#### Perustelut ehdotukselle   

Tarvitaan Artossa, 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Artikkeli - esim. Lutukka 2018:1. Tähtipoimulehti sotatulokkaana Suomussalmella - ensimmäinen tieto lajista Venäjän ulkopuolelta 

**Ehdottajan nimi:** Päivi Lipsanen 
**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto 
**Ehdottajan sähköpostiosoite:** paivi.lipsanen@helsinki.fi **Termiehdotus Fintossa:** [sotatulokkaat](http://finto.fi/yse/fi/page/Y506162)

**Comment by mirmaid** [comment]
Googlella niukasti sekä suomeksi että englanniksi.

**Comment by mariaforsen** [comment]
Sv. polemokorer
