### ISSUE TITLE
minitalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6163]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

minitalot 

#### Ehdotettu termi englanniksi   

tiny home 

#### Ehdotettu termi ruotsiksi   

litet hem 

#### Vaihtoehtoiset termit ja ilmaisut   

pikkutalot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-1-78249-357-0  Inspiring tiny homes : ‡b creative living on land, on the water, and on wheels / ‡c Gill Heriz. 

#### Perustelut ehdotukselle   

Kaupunkipientalot tai pientalot ei kuvaile asiaa tarpeeksi hyvin. Pikkutalot voisi olla vaihtoehtoinen asiasana. 

**Ehdottajan nimi:** Auli Kaartinen 
**Ehdottajan organisaatio:** BTJ 
**Ehdottajan sähköpostiosoite:** auli.kaartinen@kolumbus.fi **Termiehdotus Fintossa:** [minitalot](http://finto.fi/yse/fi/page/Y506163)

**Comment by satuniininen** [comment]
Näistä kirjoitetaan paljon ja _tiny home_ sekä _tiny house_ ovat englanninkielessä jo varsin vakiintuneita  ilmaisuja, mutta mahtaako suomenkielinen nimitys vielä elää? 

Lisäksi pitää miettiä halutaanko tällä kattaa pelkästään minikokoiset talot vai myös miniasunnot, kuten esim. nämä https://www.sato.fi/fi/usein-kysyttya-vuokra-asunnot/studiokoti
Itse mieluiten valitsisin mahdollisimman sallivan termin, sillä pienet neliöt tuntuvat olevan kovasti pinnalla ja erilaisia toteutuksia varmasti vielä nähdään.

**Comment by mirmaid** [comment]
Myös minikodit, mutta käytetään ainakin lehtijutuissa myös ihan normaalikokoisista yksiöistä ja kaksioista.

**Comment by YSA-kokous** [comment]
miniasunnot KT minitalot, minikodit

**Comment by mariaforsen** [comment]
Sv. minibostäder ET minihus, minihem
