### ISSUE TITLE
Albun kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6164]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Albun kartano 

#### Ehdotettu termi ruotsiksi   

Albu gård 

#### Ehdotettu termi englanniksi   

Albu mansion 

#### Vaihtoehtoiset termit ja ilmaisut   

kartanot & Albu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Albu_m%C3%B5is 

#### Perustelut ehdotukselle   

Albu mõis on Järvamaalla sijaitseva kartano. Sen rakennusta käsitteleviä kirjoja Helkasta löytyy yksi. Siinä on asiasanoituksena toistaiseksi pelkkä paikkakunnan nimi Albu. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1717089 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Albun kartano](http://finto.fi/yse/fi/page/Y506164)

**Comment by paivalai** [comment]
Englanninkielinen muoto: Albu Manor ei siis Mansion

**Comment by mirmaid** [comment]
Melindassa kerran muodossa _kartanot - Albu_.

**Comment by mirmaid** [comment]
Ulkomaisia kartanoita ei auktorisoida YSAan.
