### ISSUE TITLE
Nõmme

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6167]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Nõmme 

#### Ehdotettu termi ruotsiksi   

Nõmme 

#### Ehdotettu termi englanniksi   

Nõmme 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n2013066392> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2052025 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Nõmme on Tallinnan kaupunginosa (Nõmme linnaosa), jossa sijaitsee myös samanniminen asuinalue. Suomessa Nõmme-käsitteellä kuitenkin tarkoitetaan koko kaupunginosaa. Helkasta löytyy 16 tietuetta, joissa Nõmmeä on käytetty asiasanana. 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalainen@helsinki.fi **Termiehdotus Fintossa:** [Nõmme](http://finto.fi/yse/fi/page/Y506167)

**Comment by paivalai** [comment]
Tarkennus:
Hierarkia siis Tallinna > Nõmme (fin), Tallinn > Nõmme (swe), Tallinn > Nõmme (eng).
