### ISSUE TITLE
Helsinki -- Huopalahti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6176]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Helsinki -- Huopalahti](http://www.yso.fi/onto/ysa/Y110774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan Helsinki -- Huopalahti 

#### Perustelut ehdotukselle   

Huopalahti on Karttapaikan mukaan vain rautatieliikennepaikka, joka sijaitsee Etelä-Haagan kaupunginosassa. https://fi.wikipedia.org/wiki/Huopalahden_rautatieasema  YSAssa on myös Huopalahti, joka viittaa v. 1946 Helsinkiin liitettyyn entiseen kuntaan, https://fi.wikipedia.org/wiki/Huopalahti.

Melindasta löytyy 3 viitettä, joissa käytetty ketjua Helsinki -- Huopalahti:

Veistoksia Viiripuistoon
Helsinki -- Huopalahti -- Viiripuisto (ysa)

Hoplaks församlings historia 1917-1947
seurakuntahistoriat -- Helsinki -- Huopalahti (ysa)

Huopalahden seurakunnan historia 1917-1947
seurakuntahistoriat -- Helsinki -- Huopalahti (ysa)
Helsinki -- Huopalahti -- historia (ysa) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Poistetaan ja korjataan viitteet.
