### ISSUE TITLE
Kaali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6178]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kaali 

#### Ehdotettu termi ruotsiksi   

Kaali 

#### Ehdotettu termi englanniksi   

Kaali 

#### Vaihtoehtoiset termit ja ilmaisut   

Kaalin kraatteri 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Kaali_kraater 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.674881 

#### Perustelut ehdotukselle   

Saarenmaalla Kaalin kylässä oleva kuuluisa meteoriitin aikaansaama kraatteri. Helkassa on kaksi tietuetta, jossa ko. Kaali on maantietieteelisenä asiasanana. Kraatteria on kutsuttu myös Kaalinjärveksi (Kaali järv). Sitäkin on käytetty kahdessa tietueessa maantieteelisenä asiasanana. 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalalainen@helsinki.fi **Termiehdotus Fintossa:** [Kaali](http://finto.fi/yse/fi/page/Y506178)

**Comment by paivalai** [comment]
Virolainen YSA eli EMS kehottaa käyttämään nominatiivin monikossa termiä 'Kaali meteririidikraatrid'. Se myös korvaa termin 'Kaali järv' eli Kaalijärven.

**Comment by mirmaid** [comment]
Kaalin kraatteri / Kaalin kraatterit (?). KT Kaalijärvi
https://www.wikidata.org/wiki/Q595341

**Comment by mirmaid** [comment]
Liittyy linjauksiin ulkomaisten luonnonmaantieteellisten paikkojen hierarkiasta (YK Viro/Saarenmaa).
