### ISSUE TITLE
Koipsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6179]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Koipsi 

#### Ehdotettu termi ruotsiksi   

Koipsi 

#### Ehdotettu termi englanniksi   

Koipsi 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ (viitataan Saaremaalla olevaan samaninimiseen saareen) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Koipsi_saar 

#### Perustelut ehdotukselle   

Koipsi on Harjumaahan kuuluva Suomenlahden saari. On maantieteelisenä asiasanana kahdessa Helkan tietueessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1464514 

**Ehdottajan nimi:** Ilkka Päiväläinen 
**Ehdottajan organisaatio:** HY:n pääkirjasto 
**Ehdottajan sähköpostiosoite:** ilkka.paivalalainen@helsinki.fi **Termiehdotus Fintossa:** [Koipsi](http://finto.fi/yse/fi/page/Y506179)

**Comment by paivalai** [comment]
Korjaus: EMS tunnistaa Harjumaahan kuuluvana saarena. Kehottaa käyttämään muotoa 'Koipsi saar' eli Koipsin saari.
