### ISSUE TITLE
suurlakko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6199]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suurlakko](http://www.yso.fi/onto/ysa/Y105353) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö määritellä tarkemmin esim. "suurlakko 1905" tms.? 

#### Perustelut ehdotukselle   

Huomautus on, mutta sana itsessään ei kerro mistä suurlakosta on kysymys. 
Käytetty Melindassa myös muista suurlakoista kuin vuoden 1905 Suomessa ja Venäjällä tapahtuneesta, esim.
-Vuoden 1956 yleislakko Helsingissä ja lakon näkyminen Helsingin kunnallispolitiikassa / Liisa Mikkola.
-Marraskuun suurlakko 1917 Helsingissä / Matti Rantala.
-The point of no return : the strike which broke the British in Ulster / Robert Fisk. 

#### Ehdottajan organisaatio   

ÅAB

**Comment by mirmaid** [comment]
Olisiko:
suurlakko (1905)
marraskuun suurlakko (1917)

**Comment by ilona-x** [comment]
onnistuin näköjään tekemään tästä samasta aiheesta tällä viikolla uudet ehdotukset :flushed:  : 
https://github.com/Finto-ehdotus/YSE/issues/6732
https://github.com/Finto-ehdotus/YSE/issues/6733

**Comment by YSA-kokous** [comment]
suurlakko (1905)
marraskuun suurlakko (1917)

tutkitaan vielä käytettävät termit
