### ISSUE TITLE
Väike väin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6204]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi ruotsiksi   

Lillsund 

#### Ehdotettu termi suomeksi   

Väike väin 

#### Ehdotettu termi englanniksi   

Väike Väin Straits 

#### Vaihtoehtoiset termit ja ilmaisut   

Väike väin -salmi 
Väike väinin salmi 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/V%C3%A4ike_v%C3%A4in 

#### Perustelut ehdotukselle   

Väike väin on salmi, joka erottaa Saarenmaan ja Muhun toisistaan. Helkassa on yksi tietue, jossa se on asiasanana muodossa 'Väike väin -salmi'. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1833504 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Väike väin](http://finto.fi/yse/fi/page/Y506204)

**Comment by paivalai** [comment]
Peruutetaan ehdotus. Tietue on poistettu HELKAsta.
t. Ehdottaja
