### ISSUE TITLE
Viljandin rovastikunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6206]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Viljandin rovastikunta 

#### Ehdotettu termi ruotsiksi   

Viljandi prosteri 

#### Ehdotettu termi englanniksi   

Viljandi Deanery (?) 

#### Vaihtoehtoiset termit ja ilmaisut   

Viljandi 
rovastikunnat / prosterier / Church districts? parishes? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[evankelis-luterilainen kirkko](http://www.yso.fi/onto/yso/p11817) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.945014 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Viljandi_praostkond 

#### Perustelut ehdotukselle   

Helkassa on yksi tietue, jossa asianasana on nyt kentässä 651 Viljandin rovastikunta. Riittäisikö pelkkä Viljandi ja jo olemassaoleva asiasana 'rovastikunnat' kentässä 650? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Viljandin rovastikunta](http://finto.fi/yse/fi/page/Y506206)

**Comment by paivalai** [comment]
'Viljandin rovastikunta' on nyt 610-kentässä.

**Comment by paivalai** [comment]
Perutaan tämä ehdotus.
Tietueessa nyt 650_7 rovastikunnat & 651_7 Viljandi.

t. Ehdottaja
