### ISSUE TITLE
Lasnamäki (vai olisiko muoto Lasnamäki jo vakiintunut suomen kieleen?)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6208]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Lasnamäki (vai olisiko muoto Lasnamäki jo vakiintunut suomen kieleen?) 

#### Ehdotettu termi ruotsiksi   

Lasnamäe 

#### Ehdotettu termi englanniksi   

Lasnamäe 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n2002099801> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1598246 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Lasnam%C3%A4e 

#### Perustelut ehdotukselle   

Lasmäe (Lasnamäki) on Tallinnan kaupunginosa. Helkassa on kolme tietuetta, joissa se on maantieteellisenä asiasanana. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Lasnamäki (vai olisiko muoto Lasnamäki jo vakiintunut suomen kieleen?)](http://finto.fi/yse/fi/page/Y506208)

**Comment by paivalai** [comment]
Tarkennus:
Hierarkia siis Tallinna > Lasnamäe, Tallinn > Lasnamäe (swe), Tallinn >Lasnamäe (eng).
