### ISSUE TITLE
uudelleenfilmatisointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6209]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uudelleenfilmatisointi 

#### Ehdotettu termi englanniksi   

film remakes 

#### Ehdotettu termi ruotsiksi   

refilmatisering (?) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[filmatisointi](http://www.yso.fi/onto/yso/p16945) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Tarkoitusta täsmentävä selite   

Uudelleenfilmatisointi tarkoittaa uudempaa versiota aikaisemmin julkaistusta elokuvasta (wikipedia) 

#### Perustelut ehdotukselle   

Uudelleenfilmatisointeja on tehty "aina", mutta etenkin viime vuosina uudelleenfilmatisoinnit ovat olleet muoti-ilmiö - tämä on alkanut näkyä myös elokuva-alan tutkimuskirjallisuudessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Film remakes and franchises / Daniel Herbert  ja  Transnational film remakes / edited by Iain Robert Smith and Constantine Verevis. 

**Ehdottajan organisaatio:** Tampereen yliopiston kirjasto **Termiehdotus Fintossa:** [uudelleenfilmatisointi](http://finto.fi/yse/fi/page/Y506209)

**Comment by mariaforsen** [comment]
Sv. nyfilmatiseringar

**Comment by satuniininen** [comment]
Tämän pitäisi varmaan olla monikossa, mikäli halutaan viitata varsinaisiin teoksiin. _Filmatisointi_ on yksikössä, mutta se viitanneekin enemmän filmatisoinnin prosessiin kuin sen lopputulokseen.

**Comment by YSA-kokous** [comment]
uudelleenfilmatisoinnit
