### ISSUE TITLE
muinaisvenäjä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6217]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muinaisvenäjä 

#### Vaihtoehtoiset termit ja ilmaisut   

muinaisvenäjän kieli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaiskielet](http://www.yso.fi/onto/yso/p10326) 

#### Alakäsitteet (RT)   

[itäslaavilaiset kielet](http://www.yso.fi/onto/yso/p28759) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Muinaisven%C3%A4j%C3%A4 
LCSH : https://lccn.loc.gov/sh85115972 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Tarkoitusta täsmentävä selite   

Kielimuoto, josta noin tuhannen vuoden aikana ovat kehittyneet itäslaavilaiset kielet. Se on itäslaavien ikivanha kieli, joka alkoi suullisesti kehittyä noin 500-luvulla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.819774 

**Termiehdotus Fintossa:** [muinaisvenäjä](http://finto.fi/yse/fi/page/Y506217)

**Comment by mariaforsen** [comment]
Sv. fornöstslaviska ET fornryska

Onko se tämä: http://finto.fi/lexvo/fi/page/orv ?

"Fornöstslaviska (ibland kallat fornryska – att inte sammanblandas med de senare dotterdialekterna fornryska och fornrutenska)" /WP

**Comment by mirmaid** [comment]
^ Niin luulisin. Suomenkielisessä wikipediassa virheellisesti nrn.
