### ISSUE TITLE
Piikkiö Päivät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6222]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Piikkiö Päivät 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tapahtumat](http://www.yso.fi/onto/yso/p2108) 

#### Perustelut ehdotukselle   

Tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jokaiselle kaikkea : Piikkiö päivät 30 vuotta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Tarkoitusta täsmentävä selite   

http://www.piikkiopaivat.fi/ 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Piikkiö Päivät](http://finto.fi/yse/fi/page/Y506222)

**Comment by mariaforsen** [comment]
Sv. Pikisdagarna?
