### ISSUE TITLE
Narvajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6237]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Narvajoki 

#### Ehdotettu termi ruotsiksi   

Narva flod 

#### Ehdotettu termi englanniksi   

Narva River 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Narva_j%C3%B5gi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1461606 

#### Perustelut ehdotukselle   

Narvajoki on Viron ja Venäjän välinen rajajoki. Helkassa on kolme tietuetta, joissa se on asiasanana. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Narvajoki](http://finto.fi/yse/fi/page/Y506237)

**Comment by mirmaid** [comment]
Wikipedia, Wikidata: _Narvanjoki_. Melindassa 6 x _Narvajoki_. Merkitäänkö ulkomaisille joille yläkäsitteitä?

Auktorisoitu muodossa Narvanjoki
