### ISSUE TITLE
Kõpun majakka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6238]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kõpun majakka 

#### Ehdotettu termi ruotsiksi   

Kõpu fyr 

#### Ehdotettu termi englanniksi   

Kõpu Lighthouse 

#### Ehdotettu yläkäsite YSOssa (LT)   

[majakat](http://www.yso.fi/onto/yso/p523) 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1143704 

#### Perustelut ehdotukselle   

Kõpu on sekä paikkakunta Vilndin maakunnassa että Hiidenmaalla olevan majakan (Kõpu tuletorn) nimi. Helkassa on kaksi tietuetta, joissa,Kõpu on maantieteellisena asiasanana ja kummankin teokset käsittelevät no, majakkaa. 'Kõpun majakka' -asiasana kannattaneekin lisätä YSAa, sillä Hiidenmaalla toinenkin samannimien paikkakunta lähellä majakkaa, jossa puolestaan on tunnettu tuulimylly.  Lisäksi Viljandimaalla on myös oma Kõpunsa, josta pitää luoda oma maantieteelinen asiasanansa. 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/K%C3%B5pu_tuletorn 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Kõpun majakka](http://finto.fi/yse/fi/page/Y506238)

**Comment by YSA-kokous** [comment]
Suomalaisiakaan majakkarakennuksia ei ole auktorisoitu YSAan/YSOon.
