### ISSUE TITLE
Käsmu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6242]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Käsmu 

#### Ehdotettu termi ruotsiksi   

Käsmu 

#### Ehdotettu termi englanniksi   

Käsmu 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n2002099802> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1685537 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/K%C3%A4smu 

#### Perustelut ehdotukselle   

Käsmu on kylä Länsi-Virumaan maakunnassa. Se kuuluu viime vuodesta alkaen Haljalan kuntaan, Aiemmin se oli osa Vihulan kuntaa. Helkassa on kolme tietuetta, joissa sitä on käytetty maantieteelisenä asiasanana. Käsmu sijaitsee Lahemaan kansallispuiston alueella. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Käsmu](http://finto.fi/yse/fi/page/Y506242)

**Comment by paivalai** [comment]
Vielä tarkennukseksi: tämä on siis maantieteellisen asiasanan ehdotus eikä siis pelkkä concept. Kaavakkeesta oli jäänyt se alun perin määrittelemättä.

t. Ehdottaja
