### ISSUE TITLE
Matsalun kansallispuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6243]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Matsalun kansallispuisto 

#### Ehdotettu termi ruotsiksi   

Matsalu nationalpark 

#### Ehdotettu termi englanniksi   

Matsalu National Park 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh89000852.html> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.260389 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Matsalu_rahvuspark 

#### Perustelut ehdotukselle   

Matsalu on Länsi-Virossa sijaitseva kansallispuisto. Matsalu löytyy maantieteellisenä asiasanana 13 Helkan tietueesta. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Matsalun kansallispuisto](http://finto.fi/yse/fi/page/Y506243)

**Comment by vthuhtala** [comment]
Käytetty Helkassa 20 kertaa. YSAan, kiitos!
