### ISSUE TITLE
Naissaari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6249]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Naissaari 

#### Ehdotettu termi ruotsiksi   

Nargö 

#### Ehdotettu termi englanniksi   

Naissaar 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh87003229> 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Naissaar 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1953180 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Naissaari sijaitsee Suomenlahdella. Se kuuluu Harjumaan maakunnassa sijaitsevaan Viimsin kuntaan. Helkassa se  maantieteellisenä asiasanana 14 tietuetueessa. Naissaari on vakiintunut nimimuoto suomen kielessä. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Naissaari](http://finto.fi/yse/fi/page/Y506249)

**Comment by paivalai** [comment]
Unohtui: kyseessä siis maantieteellinen asiasanaehdotus.
