### ISSUE TITLE
Pajun taistelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6256]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pajun taistelu 

#### Ehdotettu termi ruotsiksi   

striden vid Paju 

#### Ehdotettu termi englanniksi   

Battle of Paju 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taistelut](http://www.yso.fi/onto/yso/p920) 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2482706 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Paju_lahing 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Pajun taistelu tapahtui vuonna 1919 Etelä-Virossa Valgamaalla. Nimensä se on saanut Pajun kartanosta. ja se oli osaa Virron vapaussotaa. Helkassa on yksi tätä taistelu käsittelevä teos, jossa maantieteelisenä asiasanana on Paju. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Pajun taistelu](http://finto.fi/yse/fi/page/Y506256)

**Comment by mariaforsen** [comment]
Sv. slaget vid Paju
