### ISSUE TITLE
Pohjois-Tartumaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6258]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Pohjois-Tartumaa 

#### Ehdotettu termi ruotsiksi   

Norra Tartumaa 

#### Ehdotettu termi englanniksi   

Northern Tartumaa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Pohjois-Tartumaa on maantieteellisenä asiasanana yhdessä Helkan tietueessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.211163 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Pohjois-Tartumaa](http://finto.fi/yse/fi/page/Y506258)

**Comment by paivalai** [comment]
PERUTAAN TÄMÄ EHDOTUS. Pelkkä Tartumaa saa riittää.

t. Ehdottaja
