### ISSUE TITLE
Kadrina

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6265]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kadrina 

#### Ehdotettu termi ruotsiksi   

Kadrina 

#### Ehdotettu termi englanniksi   

Kadrina 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n2002097432> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Kadrina_vald 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1563041 

#### Perustelut ehdotukselle   

Kadrina Länsi-Virumaalla sijaitseva kunta, jolla on samanniminen keskus. Asiasanaksi kuitenkin koko kuntaa tarkoittava. Kuvailuesimerkkinä olevan kirjan nimekkeessä on mm. Kadrina kihelkond. Se oli alueellinen kirkollishallinnollinen yksikkö, mutta siitä ei kannata luoda omaa asiasanaa. Pelkkä maantieteellinen asiasana 'Kadrina' riittää. 

**Ehdottajan organisaatio:** HY **Termiehdotus Fintossa:** [Kadrina](http://finto.fi/yse/fi/page/Y506265)

**Comment by mirmaid** [comment]
Ulkomaisista paikoista auktorisoidaan kaupungit ja valtiot, kotimaisista kylät ja sitä suuremmat paikat. Muita paikkoja auktorisoidaan, jos paikkakäsitteelle on toistuva tarve kuvailussa. https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSO-paikat
