### ISSUE TITLE
skeittipunk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6270]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

skeittipunk 

#### Ehdotettu termi ruotsiksi   

skatepunk 

#### Ehdotettu termi englanniksi   

skate punk 

#### Vaihtoehtoiset termit ja ilmaisut   

skate punk 
skatepunk 

#### Ehdotettu yläkäsite YSOssa (LT)   

[punk rock](http://www.yso.fi/onto/yso/p29762) 

#### Assosiatiiviset (RT)   

[hardcore punk](http://www.yso.fi/onto/yso/p29637) 

#### Vastaava käsite muussa sanastossa   

Library of Congress : <http://id.loc.gov/authorities/subjects/sh2015002123.html> 
Allmusic : https://www.allmusic.com/style/skatepunk-ma0000011954 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Skeittipunk syntyi alun perin jo 1980-luvulla Yhdysvalloissa, jolloin se oli hardcorea. Bändit kuten Black Flag, Suicidal Tendencies ja JFA olivat skeittareiden suosiossa, ja osa jopa skeittasi itse. Toisaalta jo tuolloin myös melodisempi hardcore Descendentsin ja Bad Religionin johdolla luettiin myös skeittipunkiksi. 1990-luvulla skeittipunkiksi vakiintui hillittömän nopea, mutta samalla melodinen punk, jonka pioneereja ovat jo 1980-luvulla aloittaneet Descendents, Bad Religion sekä Nofx. Viimeistään 2000-luvulta lähtien skeittipun-kia on alettu rinnastaa myös usein pop punkiin, ja niissä onkin paljon yhtäläisyyksiä. 

#### Perustelut ehdotukselle   

Skeittipunk on pysyvä, tunnistettava punkin alagenre. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://outi.finna.fi/Record/outi.1932403 

**Termiehdotus Fintossa:** [skeittipunk](http://finto.fi/yse/fi/page/Y506270)

**Comment by asormune** [comment]
Hyvät perustelut, pakko peukuttaa. YSAssa on mm. "psychobilly", jonka yläkäsite on "rock". Pitäisikö se liittää myös punk rock -käsitteeseen. Onkohan muitakin vastaavia?

**Comment by VelluMarjoniemi** [comment]
Kiitos. Olen miettinyt itsekin tuota psychobillya, se on kieltämättä hieman hankala tapaus. Osa psychobillybändeistä (Horrorpops, The Cramps) on enemmän punkiin kallellaan, ja osa (Nekromantix, Reverend Horton Heat) enemmän rockabillyyn. Kuitenkin, kun kyseessä on melko lailla puhdas sekoitus tyylejä (lähinnä painotukset vaihtelevat) jättäisin itse ehkä sen tuonne rockin alle missä se onkin. Tai ainakaan minä en osaa sanoa onko genre pääpiirteissään enemmän punkvaikutteista rockabillya vai rockabillyvaikutteista punkia.

Mutta voisikohan sitä liittää punkiin, ja myös rockabillyyn, lisäämällä assosiatiivisiin käsitteisiin punk rockin ja rockabillyn? Vai onko tällainen ollut tapana?

**Comment by TommiViitamies** [comment]
En kannata (= "vastustan"). Termi on "mahdoton" määritellä riittävän tarkasti erotuksena ylätermistä punk rock.

**Comment by VelluMarjoniemi** [comment]
Kiitos kommentista @TommiViitamies, rohkenen kuitenkin olla eri mieltä. Mielestäni termi on mahdollista määritellä, ja yritänpä tehdä niin.

Skeittipunkin tyypillisimmät piirteet ovat mielestäni seuraavat: kitaristeja on kaksi, joista toinen sahaa viitossoinnuilla todella, todella nopeaa, ja toinen soittaa melodioita yleensä niin sanotuilla oktaavisoinnuilla. Basisti komppaa, rumpali takoo forbidden beatia (ei "virallinen" termi, mutta eipä sellaista taida olla), ja laulaja ainakin yrittää laulaa. Tempo on järjettömän nopea. Kaikkia yksittäisiä elementtejä löytyy toki myös perinteisestä punk rockista, mutta kun ne yhdistää, on tuloksena selkeästi skeittipunkia. 

Ehkä klassisin esimerkki tyypillisestä skeittipunk-biisistä on Nofx:n Linoleum. Jo kappaleen introssa on kaikkea: toinen kitaristi sahaa viitossoinnuilla, toinen vetää oktaavisoinnuin, basisti komppaa linjassa ja rumpali soittaa forbiddenia. Tempo on melkoinen. Tuossa biisiin YouTube-linkki: https://www.youtube.com/watch?v=6axOY4PBusk

Tuoreempi esimerkki on kuluvana vuonna ilmestynyt Satanic Surfersin kappale Catch My Breath. Tässä rikotaan jo hieman sääntöjä (on kitarasooloa, hevikohtaa, teknistä soittoa), mutta ydin on selkeää skeittipunkkia: tempo on lähes järjetön, rumpukomppi on perinteinen, basso komppaa, oktaavisointuja käytetään, laulaja laulaa. Linkki kappaleeseen:
https://www.youtube.com/watch?v=1ePpudbsrxI

Koska säännöt on siis tehty rikottaviksi, löytyy skeittipunklevyiltä melko usein myös ska punkia, tai jopa reggaeta - joko kokonainen kappale tai kohta biisissä. Näillä temmot ovat luonnollisesti hitaat, kitaristit käyttävät kaikkia kuutta kieltä, basisti soittaa kuviota (jos osaa) ja rumpali vaihtelee komppia. 
Hieman toisin soitettuna kyseiset piirteet löytyvät myös usein ns. perinteisestä punk rockista, erotuksena skeittipunkiin. Punk rock on usein myös ikään kuin rokkaavampaa - se elää ja hengittää. Siis, temmot vaihtelevat (sekä biisien sisällä että levyn tasolla biisien välillä), basisti elävöittää soittoa, kitaristit eivät soita ranteitaan tuhoavalla nopeudella (ainakaan koko aikaa). Skeittipunk-albumit puolestaan ovat tyypillisesti alusta loppuun nopeaa paahtoa, poislukien mahdolliset ska punk -osiot. Varsinkin rumpukomppi on lähes muuttumaton, korkeintaan yksittäisiä lepotaukoja saatetaan pitää.

Rohkenen myös väittää, että kun kelle tahansa vähänkään punkia kuuntelevalle sanotaan että "se on skeittipunkia", tiedetään heti mistä puhutaan. Mielestäni skeittipunk on siis nimenomaan musiikillisesti kuvaava termi, ja sen pystyy kuuntelemalla erottamaan punk rockista.

**Comment by tpalonen** [comment]
Kannatan käsitteen ottamista sanastoon. Termi on yleisesti käytössä.  Skeittipunk (esiintyy myös muodossa skedepunk) on melko selkeästi määrittyvä punkin alalaji, sisältää joukon erityispiirteitä, jotka yhdessä erottavat sen muista punkin alalajeista sekä ns. valtavirta-punkista. Nopea tempo ja melodisuus (ja tyypillisesti myös ska-vaikutteet) ovat leimaavia piirteitä kuten myös nimensä mukaisesti yhteydet skeittauskulttuuriin.

**Comment by MUUSA-kokous** [comment]
Alkuperäinen ehdotus hyväksytty.
Termi lisätään myös SLM:ään.

**Comment by TommiViitamies** [comment]
Koska taisin olla poissa kokouksesta, jossa tämä hyväksyttiin, enkä päässyt ennen kokoustakaan kommentoimaan, kommentoin nyt kuitenkin jälkijättöisesti:

Toki termi on yleisesti käytössä, sekä kyseistä alakulttuuria että sen yhteyteen kytkeytyvää musiikkia tarkoitettaessa. Musiikki-ilmiön tyylillinen kirjo on kuitenkin niin laaja - mikä ilmenee ylläolevista kuvailuyrityksistäkin - että termin määritteleminen sanastoon tyhjentävästi nimenomaan musiikkina on "haasteellista". (Termin laajempi merkitys kokonaisena alakulttuurina on ehkä asia erikseen.) Jonkun se määritelmä on kuitenkin rustattava, nyt kun termi on hyväksytty. Vapaaehtoisia löytynee termin puoltajista?

**Comment by tpalonen** [comment]
Jollei kukaan muu halua niin voisin itse pohtia tuota määritelmää. Kyseinen genre on minulle suhteellisen tuttu.

**Comment by VelluMarjoniemi** [comment]
Ai niin, meinasi muilta kiireiltä unohtua tämän asian kommentointi, mutta hienoa että termi ensinnäkin hyväksyttiin, ja että määritelmällekin löytyy pohdintaa. Jo alkuperäisessä ehdotuksessa laittamani määritelmä on myös täysin vapaasti käytettävissä, mikäli sen hyödylliseksi koette.

**Comment by VelluMarjoniemi** [comment]
Voisiko tuohon @tpalonen määritelmään lisätä vielä tyypillisiä yhtyeitä? Esim. Nofx, Millencolin ja Pennywise, jotka ovat mielestäni nimenomaan oppikirjaesimerkkejä.
