### ISSUE TITLE
Rocca al Mare

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6275]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Rocca al Mare 

#### Ehdotettu termi ruotsiksi   

Rocca al Mare 

#### Ehdotettu termi englanniksi   

Rocca al Mare 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1153801 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Rocca al Mare on asuinalue Tallinnan Haaberstin kaupungisosassa. Siellä sijaitsee mm. Tallinnan Seurasaari eli Rocca al Maren  ulkoilmamuseo. Rocca al Mare on maantieteellisenö asiasanana kolmessa Helkan tietueessa. 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Rocca_al_Mare 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Rocca al Mare](http://finto.fi/yse/fi/page/Y506275)

**Comment by paivalai** [comment]
Pitänee kai ketjuttaa: Tallinna $z Rocca al Mare.
