### ISSUE TITLE
erityisnuoret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6276]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

erityisnuoret 

#### Ehdotettu termi ruotsiksi   

ungdomar med särskilda behov 

#### Ehdotettu termi englanniksi   

young people with special needs? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[nuoret](http://www.yso.fi/onto/yso/p11617) 

#### Perustelut ehdotukselle   

http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1124751&dswid=-6239 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 
[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Tarkoitusta täsmentävä selite   

Korvaamaan tai RT ongelmanuoret -termille 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. muutosehdotukset: ongelmalapset 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [erityisnuoret](http://finto.fi/yse/fi/page/Y506276)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5925

**Comment by mariaforsen** [comment]
Sv. ungdomar med särskilda behov ET ungdomar med specialbehov
