### ISSUE TITLE
Saadjärven kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6278]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Saadjärven kartano 

#### Ehdotettu termi ruotsiksi   

Saadjärve herrgård 

#### Ehdotettu termi englanniksi   

Saadjärve Manor 

#### Ehdotettu yläkäsite YSOssa (LT)   

[asuinrakennukset](http://www.yso.fi/onto/yso/p2074) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2010013861> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2186128 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Saadj%C3%A4rve_m%C3%B5is 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Kartano sijaitsee Tartumaan makunnassa Tartun kunnan Saadjärven kylässä. Helkassa on yksi tieutue, jossa se on asiasanana. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Saadjärven kartano](http://finto.fi/yse/fi/page/Y506278)

**Comment by mariaforsen** [comment]
Ruotsiksi on ollut periaatteena ettei "keksitä" ruotsinkielisiä nimiä, ellei sellaisia ole jo käytössä.

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mirmaid** [comment]
Ulkomaisia kartanoita ei auktorisoida YSAan.
