### ISSUE TITLE
luolaleijonat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6282]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luolaleijonat 

#### Ehdotettu termi ruotsiksi   

grottlejon 

#### Ehdotettu termi englanniksi   

cave lion 

#### Vaihtoehtoiset termit ja ilmaisut   

Panthera spelaea 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaiseläimet](http://www.yso.fi/onto/yso/p2919) 

#### Assosiatiiviset (RT)   

[mammutit](http://www.yso.fi/onto/yso/p15003) 

#### Vastaava käsite muussa sanastossa   

Luolaleijona : https://fi.wikipedia.org/wiki/Luolaleijona 
Panthera spelaea : https://en.wikipedia.org/wiki/Panthera_spelaea 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan kirjastoaineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Die Tierknochenfunde der mittelpaläolithischen Jägerstation von Salzgitter-Lebenstedt 

**Termiehdotus Fintossa:** [luolaleijonat](http://finto.fi/yse/fi/page/Y506282)

**Comment by mirmaid** [comment]
Lajinimi, otetaan yksikössä.
