### ISSUE TITLE
arovisentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6283]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

arovisentit 

#### Ehdotettu termi ruotsiksi   

stäppbison 

#### Ehdotettu termi englanniksi   

steppe bison 

#### Vaihtoehtoiset termit ja ilmaisut   

tasankobiisoni tai arobiisoni 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaiseläimet](http://www.yso.fi/onto/yso/p2919) 

#### Assosiatiiviset (RT)   

[mammutit](http://www.yso.fi/onto/yso/p15003) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Arovisentti 
Wikipedia : https://en.wikipedia.org/wiki/Steppe_bison 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan kirjastoaineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Die Tierknochenfunde der mittelpaläolithischen Jägerstation von Salzgitter-Lebenstedt 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [arovisentit](http://finto.fi/yse/fi/page/Y506283)

**Comment by mirmaid** [comment]
Lajinimi, otetaan yksikössä.
