### ISSUE TITLE
eläinornamentiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6287]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

eläinornamentiikka 

#### Ehdotettu termi ruotsiksi   

djurornamentik 

#### Ehdotettu termi englanniksi   

Decoration and ornament--Animal forms 

#### Ehdotettu yläkäsite YSOssa (LT)   

[koristetaide](http://www.yso.fi/onto/yso/p8853) 

#### Vastaava käsite muussa sanastossa   

Svenska ämnesord : djurornamentik 
LCSH : <http://id.loc.gov/authorities/subjects/sh85036230.html> 

#### Perustelut ehdotukselle   

Tarvitaan kirjastoaineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2822993 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [eläinornamentiikka](http://finto.fi/yse/fi/page/Y506287)

**Comment by mirmaid** [comment]
MAO/TAOssa, Melindassa 37 kertaa (lähinnä masa-terminä).

**Comment by mirmaid** [comment]
MAO/TAOssa myös _kasviornamentiikka_.
