### ISSUE TITLE
dagerrotypia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6288]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dagerrotypia 

#### Ehdotettu termi ruotsiksi   

Daguerreotypi 

#### Ehdotettu termi englanniksi   

Daguerreotype 

#### Vaihtoehtoiset termit ja ilmaisut   

dagerrotyyppi tai daguerrotypia 

#### Ehdotettu yläkäsite YSOssa (LT)   

[valokuvaus tekniikan mukaan](http://www.yso.fi/onto/yso/p7680) 

#### Vastaava käsite muussa sanastossa   

Svenska ämnesord : <http://www.kb.se/katalogisering/Svenska-amnesord/> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85035408.html> 
Wikipedia : https://fi.wikipedia.org/wiki/Dagerrotypia 

#### Perustelut ehdotukselle   

Tarvitaan kirjastoaineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2365259 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [dagerrotypia](http://finto.fi/yse/fi/page/Y506288)

**Comment by mirmaid** [comment]
Metatietosanastossa ja VALO-ontologiassa, 7 viitettä Melindassa & 3 kertaa muodossa daguerrotypia.

**Comment by mariaforsen** [comment]
Sv. daguerreotypi ET dagerrotypi, daguerrotypi
