### ISSUE TITLE
Palmsen kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6298]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Palmsen kartano 

#### Ehdotettu termi ruotsiksi   

Palmse herrgård 

#### Ehdotettu termi englanniksi   

Palmse Manor 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Palmse_m%C3%B5is 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1994574 

#### Perustelut ehdotukselle   

Palmsen kartanoi sijaitsee Länsi-Virumaan maakunnas Haljalan kunnassa. Siitä on Helkassa yksi viite. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Palmsen kartano](http://finto.fi/yse/fi/page/Y506298)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mirmaid** [comment]
Ulkomaisia kartanoita ei auktorisoida YSAan.
