### ISSUE TITLE
Peipsimaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6300]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Peipsimaa 

#### Ehdotettu termi ruotsiksi   

Området  kring Peipus 

#### Ehdotettu termi englanniksi   

Peipsi Area 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Peipsij%C3%A4rvi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Peipsimaa on Peipsijärven Viron puoleisella rannalla sijaitseva suurenla osin vemnäläisten vanhauskoisten asuttama alue. Maantieteellisen asiasanan ohella tietueessa on hyvä olla tarkennuksena jo YSAsta löytyvä 'kulttuurialueet'. Helkassa on kolme tietuetta, joissa on maantieteellisenä asiasanana 'Peipsimaa'. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2131997 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Peipsimaa](http://finto.fi/yse/fi/page/Y506300)

**Comment by mirmaid** [comment]
http://visitpeipsi.com/en/
http://www.peipsimaa.ee/en

**Comment by YSO-kokous** [comment]
Selvitetään, löytyykö ruotsin vastinetta. Jos kyllä, otetaan sanastoon. @mariaforsen

**Comment by mariaforsen** [comment]
Sv. Peipsimaa

**Comment by YSO-kokous** [comment]
Otetaan sanastoon.
