### ISSUE TITLE
Ensimmäinen Saksan-Tanskan sota (1848-1851)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6302]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ensimmäinen Saksan-Tanskan sota (1848-1851) 

#### Ehdotettu termi englanniksi   

Schleswig-Holstein War, 1848-1850 

#### Vaihtoehtoiset termit ja ilmaisut   

1. Saksan-Tanskan sota (1848-1851) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sodat (tapahtumat)](http://www.yso.fi/onto/yso/p1271) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85118185 
Wikipedia : https://fi.wikipedia.org/wiki/Ensimm%C3%A4inen_Saksan%E2%80%93Tanskan_sota 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

Ensimmäinen Saksan-Tanskan sota käytiin vuosina 1848-1851. Sota päättyi Schleswigin ja Holsteinin herttuakuntien siirtymiseen Tanskan hallintaan. 

#### Perustelut ehdotukselle   

Ehdotettu termiksi myös 'Toinen Saksan-Tanskan sota (1864)', joten samalla voisi lisätä tämän ensimmäisen... 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

x 

**Termiehdotus Fintossa:** [Ensimmäinen Saksan-Tanskan sota (1848-1851)](http://finto.fi/yse/fi/page/Y506302)

**Comment by vthuhtala** [comment]
sao: Slesvig-holsteinska kriget 1848-1850

**Comment by mirmaid** [comment]
_Ensimmäinen Saksan-Tanskan sota_ varmaankin uniikki ilman sulkutarkennettakin.

**Comment by mariaforsen** [comment]
Sv. slesvig-holsteinska kriget ET dansk-tyska kriget 1848-1850, slesvig-holsteinska kriget 1848-1850, slesvigska kriget, slesvigska treårskriget, slesvigska krigen
