### ISSUE TITLE
Pärlijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6303]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Pärlijoki 

#### Ehdotettu termi ruotsiksi   

Pärlijõgi 

#### Ehdotettu termi englanniksi   

Pärlijõgi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://sv.wikipedia.org/wiki/P%C3%A4rlij%C3%B5gi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1586106 

#### Perustelut ehdotukselle   

Pärlijõgi virtaa sekä Virossa että Latviassa.Se löytyy maantieteellisenä asiasanan yhdessä Helkan tietueessa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Pärlijoki](http://finto.fi/yse/fi/page/Y506303)

**Comment by mirmaid** [comment]
Jokien yläkäsitteet?
