### ISSUE TITLE
Toinen Saksan-Tanskan sota (1864)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6304]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Toinen Saksan-Tanskan sota (1864) 

#### Ehdotettu termi englanniksi   

Schleswig-Holstein War, 1864 

#### Vaihtoehtoiset termit ja ilmaisut   

2. Saksan-Tanskan sota (1864) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sodat (tapahtumat)](http://www.yso.fi/onto/yso/p1271) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85118186 
Wikipedia : https://fi.wikipedia.org/wiki/Toinen_Saksan%E2%80%93Tanskan_sota 
sao : Dansk-tyska kriget 1864 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

Vuonna 1864 käyty sota, jonka hävittyään Tanska joutui luovuttamaan Preussille ja Itävallalle Schleswig-Holsteinin alueen. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3056039 

**Termiehdotus Fintossa:** [Toinen Saksan-Tanskan sota (1864)](http://finto.fi/yse/fi/page/Y506304)

**Comment by mariaforsen** [comment]
Sv. dansk-tyska kriget (1864) ET andra dansk-tyska kriget, andra slesvigska kriget, slesvigska krigen
