### ISSUE TITLE
Prangli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6306]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Prangli 

#### Ehdotettu termi englanniksi   

Prangli 

#### Ehdotettu termi ruotsiksi   

Vrangö 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1435762 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Prangli 

#### Perustelut ehdotukselle   

Prangli on Viron pohjoisrannikolla sijaitseva saari. Kuuluu Harjumaan maakunnan Viimasin kuntaan. Se on maantieteellisenä asiasanana kolmessa Helkan tietueessa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Prangli](http://finto.fi/yse/fi/page/Y506306)

**Comment by mirmaid** [comment]
Saarten tarkenteet (itsenäinen kunta vs. kuntaan kuuluva saari)? (Prangli, Aksi, Aegnan saari, Osmussaari, Koipsi, Rammu, Pakrin saaret)

**Comment by YSO-kokous** [comment]
PÄÄTETTY
Jos ulkomainen saari on itsenäinen kunta tai tätä suurempi hallinnollinen yksikkö, ei laiteta sulkutarkennetta, paitsi jos sanastossa on toinen samanniminen käsite. 

KESKUSTELTAVAKSI
Pienempiä saaria (eli saaria, jotka eivät ole itsenäisiä kuntia tai tätä suurempia hallinnollisia yksikköjä) koskien on kaksi päätettävää seikkaa, joissa kummassakin kaksi vaihtoehtoa. 

Ensinnäkin, kumpi vaihtoehdoista valitaan:
1) Sulkutarkennetta ei lisätä, paitsi jos sanastossa on toinen samanniminen käsite.
2) Sulkutarkenne lisätään aina (vrt. Suomen kaupunginosat)

Toiseksi, mikäli sulkutarkenne lisätään, kumpi alla olevista valitaan sulkutarkenteeksi:
1) paikkatyyppi, eli tässä tapauksessa _(saari)_
2) kunta tai alue, johon saari kuuluu

Ks. myös: https://github.com/Finto-ehdotus/YSE/issues/6085

**Comment by MikkoAleksanteri** [comment]
PÄÄTÖS FINTO-palaverissa 30.6.2020:

Kysymys 1:
Sulkutarkenne lisätään, jos on ylipäätään olemassa samanniminen toinen paikka.

Kysymys 2:
Sulkutarkenteeksi kunta tai alue, johon saari kuuluu
