### ISSUE TITLE
teollisuusperintö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6308]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

teollisuusperintö 

#### Ehdotettu termi ruotsiksi   

Industriminnen 

#### Ehdotettu termi englanniksi   

Industrial heritage 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuuriperintö](http://www.yso.fi/onto/yso/p8475) 

#### Vastaava käsite muussa sanastossa   

Svenska ämnesord : Industriminnen 
Wikipedia : https://en.wikipedia.org/wiki/Industrial_heritage 
MAO-käsite : <http://www.yso.fi/onto/mao/p4138> 

#### Tarkoitusta täsmentävä selite   

[Teollisuusperintöön] ... kuuluvat kaikki teolliseen tuotantoon ja työhön liittyvät ilmiöt. Näkyvintä teollisuusperintöä ovat tehdasrakennukset ja asuinalueet, jotka muodostavat kokonaisia teollisuusympäristöjä. Sitä ovat myös koneet ja työtavat sekä teollisesti valmistetut tuotteet, joita me kaikki käytämme päivittäin. Satamat, rautatiet ja muu infrastruktuuri ovat aina liittyneet teollisuuteen, ja siten ne ovat myös teollisuusperintöä.
http://www.teops.fi/ 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3029010 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [teollisuusperintö](http://finto.fi/yse/fi/page/Y506308)

**Comment by mirmaid** [comment]
Melindassa 122 kertaa (yleensä masa-terminä).

**Comment by mariaforsen** [comment]
Sv. industriarv ET industriminnen
