### ISSUE TITLE
Sangasten

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6309]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Sangasten 

#### Ehdotettu termi ruotsiksi   

Sangaste 

#### Ehdotettu termi englanniksi   

Sangaste 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n82068278> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1532402 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Sangaste_m%C3%B5is 

#### Perustelut ehdotukselle   

Sangaste on 'alevik'  eli (pien)kauppla tai taajama  Valgaman maakunnan Otepään kunnassa. Siellä sijaitsee Sangasten kartano, jota käsitteleviä teoksia Helkassa on viisi. Kaikissa on maantieteellisenä asiasanana Sangaste. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Sangasten](http://finto.fi/yse/fi/page/Y506309)

**Comment by paivalai** [comment]
Korjaus: suomenkielinen muoto 'Sangaste'
