### ISSUE TITLE
Sangasten linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6310]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Sangasten linna 

#### Ehdotettu termi ruotsiksi   

Sangasten loss 

#### Ehdotettu termi englanniksi   

Sangaste Castle 

#### Ehdotettu yläkäsite YSOssa (LT)   

[linnat](http://www.yso.fi/onto/yso/p6790) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Nykyään Valgamaan Otepään kunnassa sijaitseva Sangasten kartanoalue on tunnettu Sangasten linnastaan. Helkassa on viisi tietuetta, joissa Sangaste on maantieteelllisenä asiananana.Kaikki niistä löytyvät teokset käsittelevät no. Sangasten kartanoaluetta, sen omistanutta sukua sekä itse linnaa. 650-kenttää olisi hyvä saada uudeksi asiasanaksi  'Sangasten linna'. 

#### Tarkoitusta täsmentävä selite   

https://www.puhkaeestis.ee/et/sangaste-loss 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1532402 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Sangasten linna](http://finto.fi/yse/fi/page/Y506310)

**Comment by mirmaid** [comment]
Melindassa 2 kertaa Sangasten linna, kerran ysa-terminä, kerran yhteisönä. 4 kertaa Sangasten kartano.

**Comment by mariaforsen** [comment]
Sv. Sangaste slott
