### ISSUE TITLE
Taageperan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6311]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Taageperan kartano 

#### Ehdotettu termi ruotsiksi   

Taagepera herrgård 

#### Ehdotettu termi englanniksi   

Taagepera Manor 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Taagepera_m%C3%B5is 

#### Perustelut ehdotukselle   

Taageperan kartano sijaitsee Valgamaalla Tõrvan kunnassa. Helkasta löytyy yksi tietue, joka käsittelee Taageperassa olevaa kartanoa. Sen tietueessa on maantieteellisenä asiasananana 'Taagepera'. Englanniksi kartano löytyy verkosta muodoissa 'Taagepera Castle, 'Taagepera Mansion' ja 'Taagepera Manor'. Makuasia, minkä niistä valitsisi, tähän ehdotukseen, mutta olkoon 'Manor', koska kirja näyttää kertovan ei vain itse rakennuksesta vaan koko kartanosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2934873 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Taageperan kartano](http://finto.fi/yse/fi/page/Y506311)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mirmaid** [comment]
Ulkomaisia kartanoita ei auktorisoida YSAan.
