### ISSUE TITLE
liikuntaseurat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6315]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liikuntaseurat](http://www.yso.fi/onto/ysa/Y110587) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin urheiluseurat? Samoin ehkä myös liikuntajärjestöt? 

#### Perustelut ehdotukselle   

Jako tuskin toimii käytännössä loogisesti. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Allärsissa on ollut: gymnastik- och idrottsföreningar, idrottsföreningar, mikä ei tietenkään toimi. Yhdistämisen jälkeen olisi (kuten pitää): idrottsföreningar

**Comment by ilona-x** [comment]
Oliko tässä siis ajatuksena yhdistää liikuntaseurat&urheiluseurat&liikuntajärjestöt yhdeksi termiksi vai yhdistää liikuntaseurat&urheiluseurat ja lisäksi liikuntajärjestöt & urheilujärjestöt?

**Comment by mirmaid** [comment]
yhdistää: 

- liikuntaseurat & urheiluseurat

- liikuntajärjestöt & urheilujärjestöt

**Comment by YSA-kokous** [comment]
urheilu- ja liikuntaseurat
urheilu- ja liikuntajärjestöt

**Comment by mariaforsen** [comment]
Sv. 
-sport- och idrottsföreningar ET sport- och idrottssällskap, idrotts- och sportföreningar, idrotts- och sportsällskap
-sport- och idrottsorganisationer ET idrotts- och sportorganisationer
