### ISSUE TITLE
Sangasten kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6317]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Sangaste Manor 

#### Ehdotettu termi suomeksi   

Sangasten kartano 

#### Ehdotettu termi ruotsiksi   

Sangaste herrgård 

#### Vastaava käsite muussa sanastossa   

EMS : https://ems.elnet.ee/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

https://et.wikipedia.org/wiki/Sangaste_loss 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2236815 

#### Perustelut ehdotukselle   

Olisi kai hyvä luoda YSAan Sangasten linnalle ks. viittaus. On hieman epäselvää, mitä Helkassa olevat Sangaste-aiheiset kirjat tarkalleen ottaen käsittelevät. Koko kartanon historiaa vai kuinka paljon niissä keskitytään itse päärakennukseen ja sen historiaan, 

**Ehdottajan organisaatio:** HY **Termiehdotus Fintossa:** [Sangasten kartano](http://finto.fi/yse/fi/page/Y506317)

**Comment by mirmaid** [comment]
4 viitettä Melindassa

**Comment by mirmaid** [comment]
KÄ Sangasten linna
