### ISSUE TITLE
iyengarjooga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6318]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

iyengarjooga 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jooga](http://www.yso.fi/onto/yso/p3111) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 
[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

joogan laji jota en muutenkaan osaa kuvata kuin täsmällisellä nimellä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Aalto, Jutta: Anatomia & kehotietoisuus 9789529399925 

**Ehdottajan organisaatio:** BTJ Finland **Termiehdotus Fintossa:** [iyengarjooga](http://finto.fi/yse/fi/page/Y506318)

**Comment by mariaforsen** [comment]
Sv. iyengaryoga
