### ISSUE TITLE
viittausindeksi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6322]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viittausindeksi 

#### Ehdotettu termi englanniksi   

citation index 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Tarkoitusta täsmentävä selite   

Viittausindeksi (engl. citation index) on virallinen tilasto joka selvittää, kuinka paljon tiedeartikkeleihin viitataan toisista tiedeartikkeleista. Indeksi mittaa vain vertaisarvioitujen tiedejulkaisujen viittauksia. https://fi.wikipedia.org/wiki/Viittausindeksi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-263-132-9 Report from the Finnish Citation Index Working Group II ; http://urn.fi/URN:ISBN:978-952-263-132-9 

#### Perustelut ehdotukselle   

Tarpeen täsmällisen sisällönkuvailun tuottamiseksi. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [viittausindeksi](http://finto.fi/yse/fi/page/Y506322)

**Comment by mariaforsen** [comment]
Sv. citeringsindex ET citeringsdatabaser, citationsindex

**Comment by mirmaid** [comment]
Monikko?
