### ISSUE TITLE
Hirvijärven tekojärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6324]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Hirvijärven tekojärvi 

#### Vaihtoehtoiset termit ja ilmaisut   

Hirvijärven tekoallas 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tekoaltaat](http://www.yso.fi/onto/yso/p3810) 

#### Vastaava käsite muussa sanastossa   

Järviwiki : <http://www.jarviwiki.fi/wiki/Hirvij%C3%A4rven_tekoj%C3%A4rvi_(44.092.2.001)#> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1434530 

**Termiehdotus Fintossa:** [Hirvijärven tekojärvi](http://finto.fi/yse/fi/page/Y506324)

**Comment by mirmaid** [comment]
Hirvijärvi (Etelä-Pohjanmaa): päätermi vaihdettu > Hirvijärven tekojärvi
