### ISSUE TITLE
Vääksyn kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6325]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Vääksyn kartano 

#### Vaihtoehtoiset termit ja ilmaisut   

Växiö 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/V%C3%A4%C3%A4ksyn_kartano 

#### Tarkoitusta täsmentävä selite   

1500-luvulla perustettu Kangasalla sijaitseva kartano. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.463960 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

**Termiehdotus Fintossa:** [Vääksyn kartano](http://finto.fi/yse/fi/page/Y506325)

**Comment by mariaforsen** [comment]
Sv. Växiö gård ET Wäxiö gård
