### ISSUE TITLE
kammat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6326]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kammat 

#### Ehdotettu termi ruotsiksi   

kammar 

#### Ehdotettu termi englanniksi   

combs 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elottomat objektit](http://www.yso.fi/onto/yso/p207) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85028828.html> 
Svenska ämnesord : Kammar 
Wikipedia : https://fi.wikipedia.org/wiki/Kampa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3052364 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa. 

#### Tarkoitusta täsmentävä selite   

Hiustenhoitoväline tai hiuskoriste. Yksi vanhimmista arkeologien löytämistä työkaluista. (wikipedia) 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [kammat](http://finto.fi/yse/fi/page/Y506326)

**Comment by mirmaid** [comment]
MAO/TAOssa, 24 kertaa Melindassa (lähinnä masa-terminä).
