### ISSUE TITLE
hakassit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6328]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hakassit 

#### Ehdotettu termi englanniksi   

Khakas people 

#### Ehdotettu yläkäsite YSOssa (LT)   

[turkkilaiset kansat](http://www.yso.fi/onto/yso/p21108) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Hakassit 
Wikipedia (en) : https://en.wikipedia.org/wiki/Khakas_people 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Turkkilais-tataarilainen kansa Etelä-Siperiassa sijaitsevassa Hakassian tasavallassa Venäjällä. Hakasseja on noin 80 000. 

#### Perustelut ehdotukselle   

YSA-terminä Helkassa 35 kertaa. Melindassa 33 kertaa YSA- tai muuna asiasanana. Myös uutta aineistoa. YSAssa on jo hakassin kieli ja hakassinkielinen kirjallisuus. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Singing story, healing drum : shamans and storytellers of Turkic Siberia / Kira Van Deusen. 

**Ehdottajan organisaatio:** SKS:n kirjasto **Termiehdotus Fintossa:** [hakassit](http://finto.fi/yse/fi/page/Y506328)

**Comment by mariaforsen** [comment]
Sv. chakasser
