### ISSUE TITLE
gandat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6329]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gandat 

#### Ehdotettu termi englanniksi   

Ganda (African people) 

#### Vaihtoehtoiset termit ja ilmaisut   

bagandat, wagandat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[bantut](http://www.yso.fi/onto/yso/p2853) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85053006> 
Wikipedia : https://fi.wikipedia.org/wiki/Gandat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Ugandan suurin yksittäinen etninen ryhmä. Gandat puhuvat nigeriläis-kongolaisiin kieliin kuuluvaa gandaa. Gandat hallitsivat aikanaan Ugandalle nimensä antanutta Bugandan kuningaskuntaa Victorianjärven luoteisrannalla. 
Gandat polveutuivat bantuista, jotka alkoivat muuttaa Keski-Afrikasta Itä-Afrikkaan 1000-luvun paikkeilla. (LCSH:ssa BT Bantu-speaking peoples) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Native marriage in Buganda / Lucy Philip Mair 

#### Perustelut ehdotukselle   

YSAssa on jo gandan kieli ja gandankielinen kirjallisuus. 

**Ehdottajan organisaatio:** SKS:n kirjasto **Termiehdotus Fintossa:** [gandat](http://finto.fi/yse/fi/page/Y506329)

**Comment by mariaforsen** [comment]
Sv. ganda (folk) ET baganda (folk)
