### ISSUE TITLE
osaamisperusteisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6330]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

osaamisperusteisuus 

#### Perustelut ehdotukselle   

Erittäin ajankohtainen termi esim. https://www.oph.fi/kehittamishankkeet/valtionavustushankkeet/osaamisperusteisuus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.oamk.fi/epooki/index.php?cID=1295 

**Ehdottajan organisaatio:** Oulun ammattikorkeakoulu **Termiehdotus Fintossa:** [osaamisperusteisuus](http://finto.fi/yse/fi/page/Y506330)

**Comment by mirmaid** [comment]
Melindassa 5 kertaa _osaamisperustaisuus_, kerran _osaamisperusteinen koulutusohjelma_ ja kerran _osaamisperusteinen työtodistus_.

**Comment by mirmaid** [comment]
Osaamisperusteisen koulutuksen ytimen muodostavat opiskelijan tavoittelemaa osaamista tietoina, taitoina ja asenteina kuvaavat osaamistavoitteet. Opiskelija kehittää osaamistaan suhteessa niihin. Kun tavoiteltava osaaminen on saavutettu, se osoitetaan erilaisin tehtävin ja tunnustetaan opintopisteinä. https://blogi.oamk.fi/2018/02/09/osaamisperusteinen-koulutus-on-paluuta-vanhaan/

**Comment by mariaforsen** [comment]
Sv. kompetensbasering http://www03.oph.fi/sanasto/alaluokka2_1_1_r.asp

**Comment by rkokko** [comment]
Koska käytetään paljon  myös osaamisperust_a_isuus termiä, niin olisi tärkeä virallistaa osaamisperusteisuus termi (tai sitten jompikumpi).

**Comment by satuniininen** [comment]
Tarvitaan taas: 
https://kansalaisopistojenliitto.fi/wp-content/uploads/2022/02/2022_pikaopas_kansalaisopiston_opettajalle.pdf
https://kansalaisopistojenliitto.fi/wp-content/uploads/2022/03/2022_kohti_osaamisperusteisuutta_suuntaviivoja_kansalaisopiston_johdolle_ja_yllapitajalle.pdf

**Comment by ilona-x** [comment]
fi        osaamisperusteisuus
sv       ~ kompetensbaserat lärande n

määritelmä
pedagogista toimintaa ohjaava periaate, jonka mukaan koulutuksessa (1) tärkeintä on se, että oppija saavuttaa hänelle tavoitteeksi asetetun osaamisen, ei se, millä tavoin ja minkä ajan kuluessa osaaminen on hankittu

huomautus
Osaamisperusteisen pedagogiikan mukaan koulutuksessa (1) ei pyritä opiskelemaan tiettyjä oppiaineita ja suorittamaan vakiomäärää opintoja, vaan tärkeintä on, että oppijalle tavoitteeksi asetettu osaaminen tulee koulutuksen (2) aikana hankittua. Lähtökohtana on oppijan aikaisemmin hankittu tutkinnon kannalta olennainen osaaminen, jonka päälle kerrytetään tarvittavin osin uutta osaamista. Oppijat voivat saavuttaa osaamisensa erilaisissa oppimisympäristöissä (ei esimerkiksi pelkästään oppilaitoksessa), keskenään eri tavoin ja eri tahdissa.
Ammatillinen osaaminen on kokonaisuus, joka muodostuu ammatissa tarvittavista tiedoista ja taidoista ja niiden soveltamisesta käytännön työtehtäviin.

Lähde: Opetus- ja koulutussanasto, 2. laitos (OKM, 2021:10) https://termipankki.fi/tepa/fi/haku/osaamisperustaisuus

**Comment by mirmaid** [comment]
Jotenkin _osaamisperusteinen opetus/pedagogiikka_ tuntuisi paljon selkeämmältä termimuodolta (?). On vaan hirveän vähän käytettyjä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _osaamisperusteinen opetus_, ohjaustermiksi _osaamisperusteisuus (opetus)_.

**Comment by mariaforsen** [comment]
Sv. kompetensbaserad undervisning HT kompetensbaserat lärande https://www.psykologiguiden.se/psykologilexikon/?Lookup=CBT

https://termipankki.fi/tepa/fi/haku/kompetensbaserat%20l%C3%A4rande

Ks. myös https://en.wikipedia.org/wiki/Competency-based_learning ja competency-based teaching
