### ISSUE TITLE
Cesvaine

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6331]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Cesvaine 

#### Ehdotettu termi ruotsiksi   

Cesvaine 

#### Ehdotettu termi englanniksi   

Cesvaine 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n2007058116> 

#### Tarkoitusta täsmentävä selite   

Cesvaine on kaupunki Latviassa. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. Löytyy 651-kentästä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1650401 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Cesvaine](http://finto.fi/yse/fi/page/Y506331)

**Comment by paivalai** [comment]
Maantieteellinen käsite.
