### ISSUE TITLE
Cēsis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6332]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Cēsis 

#### Ehdotettu termi ruotsiksi   

Cēsis 

#### Ehdotettu termi englanniksi   

Cēsis 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n85058631> 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. Löytyy 651-kentästä. 

#### Tarkoitusta täsmentävä selite   

Cēsis on kaupunki Latviassa (https://lv.wikipedia.org/wiki/C%C4%93sis). 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2648034 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Cēsis](http://finto.fi/yse/fi/page/Y506332)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6477
