### ISSUE TITLE
palokunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6333]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[palokunnat](http://www.yso.fi/onto/ysa/Y97980) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ohjausterminä nykyisin vapaapalokunnat, joka on kuitenkin selkeästi oma käsitteensä ja alatermi palokunnat-termille 

#### Perustelut ehdotukselle   

esim. VPK-historiikki: Kouki, Timo: Viinikellarilla palaa (Virolahden vapaapalokunnan historiikki) jne.
Myös kotimaisten kielten tutkimuslaitoksen sanakirjassa omanaan. KT vapaaehtoiset palokunnat. 

#### Ehdottajan organisaatio   

BTJ

**Comment by ilona-x** [comment]
LCSH: Volunteer fire departments http://id.loc.gov/authorities/subjects/sh2002002820
