### ISSUE TITLE
Väinäjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6334]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Väinäjoki 

#### Ehdotettu termi ruotsiksi   

Daugava 

#### Ehdotettu termi englanniksi   

Daugava 

#### Vaihtoehtoiset termit ja ilmaisut   

suom. Daugava, eng. Western Dvina 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh90005158> 

#### Tarkoitusta täsmentävä selite   

Väinäjoki on Valko-Venäjällä alkava Latvian läpi virtaava joki ( 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. Löytyy 651-kentästä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.5562 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Väinäjoki](http://finto.fi/yse/fi/page/Y506334)

**Comment by paivalai** [comment]
Korjaus: maantieteellinen käsite.
