### ISSUE TITLE
Daugavpils

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6335]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Daugavpils 

#### Ehdotettu termi ruotsiksi   

Daugavpils 

#### Ehdotettu termi englanniksi   

Daugavpils 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n81004993> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1907819 

#### Tarkoitusta täsmentävä selite   

Daugavpils on kaupunki Latviassa (https://fi.wikipedia.org/wiki/Daugavpils) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. Löytyy 651-kentästä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Daugavpils](http://finto.fi/yse/fi/page/Y506335)

**Comment by paivalai** [comment]
Lisäys: joskus näkee käytettävän myös muotoa 'Väinänlinna', mutta se lienee ollut enemminkin käytössä menneinä aikoina.
