### ISSUE TITLE
Rundālen linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6337]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Rundālen linna 

#### Ehdotettu termi englanniksi   

Rundāle Palace 

#### Ehdotettu termi ruotsiksi   

Rundāles pils 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n88620872.htm> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1028969 

#### Tarkoitusta täsmentävä selite   

Rundālen linna sijaitsee Latviassa (https://fi.wikipedia.org/wiki/Rund%C4%81les_pils). 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. Löytyy 651-kentästä. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Rundālen linna](http://finto.fi/yse/fi/page/Y506337)

**Comment by paivalai** [comment]
Korjaus: löytyy siis 650-kentästä.

**Comment by mirmaid** [comment]
LCSH: Rundāles pils muzejs

**Comment by mirmaid** [comment]
Ei Melindassa (on Helkassa)

**Comment by mariaforsen** [comment]
Sv. Rundale slott ET Rundāles pils
