### ISSUE TITLE
Gaujan kansallispuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6338]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Gaujan kansallispuisto 

#### Ehdotettu termi ruotsiksi   

Gauja nationalpark 

#### Ehdotettu termi englanniksi   

Gauja National Park 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85053537.html> 
Wikipedia : (https://fi.wikipedia.org/wiki/Gaujan_kansallispuisto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1636353 

#### Perustelut ehdotukselle   

Tarvitaan sisällönluvailussa. Löytyy 650-kentästä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Tarkoitusta täsmentävä selite   

Gaujan kansallispuisto sijaitsee Latviassa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Gaujan kansallispuisto](http://finto.fi/yse/fi/page/Y506338)

**Comment by mariaforsen** [comment]
Sv. Gauja nationalpark ET Gaujas nationalpark
