### ISSUE TITLE
Ķemerin kylpylähotelli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6343]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ķemerin kylpylähotelli 

#### Ehdotettu termi englanniksi   

Ķemeri Spa 

#### Ehdotettu termi ruotsiksi   

Ķemeris badhotell 

#### Vaihtoehtoiset termit ja ilmaisut   

Kemerin kylpylähotelli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1635385 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Tarkoitusta täsmentävä selite   

Ķemerin kylpylä on Jūrmalassa Latviassa sijaitseva kylpylähotelli. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 650-krntässä. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Ķemerin kylpylähotelli](http://finto.fi/yse/fi/page/Y506343)

**Comment by jtuohini** [comment]
Pitäisikö auktorisoitu muoto kuitenkin olla alkukielellä, kysehän on yhteisöstä – ja vielä siltä osin kuuluu X10-kenttään, ei 650:een.

**Comment by mirmaid** [comment]
Tietueessa lukee _Kemeri kylpylä_

**Comment by mirmaid** [comment]
Vain erityisen merkittäviä ulkomaisia rakennuksia auktorisoidaan YSAan.
