### ISSUE TITLE
sävellysmuodot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6344]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sävellysmuodot 

#### Ehdotettu termi englanniksi   

musical forms 

#### Vaihtoehtoiset termit ja ilmaisut   

sävellysmuoto 

#### Alakäsitteet (RT)   

[sonaattimuoto](http://www.yso.fi/onto/yso/p7248) 

#### Assosiatiiviset (RT)   

[muoto-oppi (musiikki)](http://www.yso.fi/onto/yso/p12941) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85088959> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Perustelut ehdotukselle   

Olisi parempi LT-suhde "rondomuodolle" ja muille YSOon vasta tulossa oleville asiasanoille kuin nykyinen "muoto (rakenteellinen)". Asia tuli vastaan Musa–Yso-kokouksessa 4.6.2018. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [sävellysmuodot](http://finto.fi/yse/fi/page/Y506344)

**Comment by MUUSA-kokous** [comment]
Alkuperäinen ehdotus hyväksytty.
ST:ksi muunnelmamuoto, sonaattimuoto ja rondomuoto.

**Comment by mariaforsen** [comment]
Sv. kompositionsformer
