### ISSUE TITLE
Latgallia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6346]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Latgallia 

#### Ehdotettu termi ruotsiksi   

Lettgallen 

#### Ehdotettu termi englanniksi   

Latgale 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n84095698> 
Wikipedia : https://fi.wikipedia.org/wiki/Latgallia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.723789 

#### Tarkoitusta täsmentävä selite   

Latgale on yksi Latvian kulttuurialueista ja historiallisista maakunnista. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailuun 651-kenttään. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Latgallia](http://finto.fi/yse/fi/page/Y506346)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa Latgallia, ohjaustermiksi Latgale. Latgallia on alueen suomenkielinen nimimuoto. Yläkäsitteeksi Latvia.
