### ISSUE TITLE
muunsukupuolisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6347]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muunsukupuolisuus 

#### Perustelut ehdotukselle   

Hei, äsken aineistoa käsitellessäni vastaani tuli kirja, jossa asiasanana on sukupuoli-identiteetti ja homoseksuaalisuus, mutta kirjan päähenkilö on muunsukupuolinen. Asiasanoitus ei siis oikeastaan kuvaa kirjan sisältöä. Olisikohan YSAan ja kaunokkiin mahdollisuus saada asiasanaksi muunsukupuolisuus? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** - **Termiehdotus Fintossa:** [muunsukupuolisuus](http://finto.fi/yse/fi/page/Y506347)

**Comment by ilona-x** [comment]
LCSH: 
Gender nonconformity http://id.loc.gov/authorities/subjects/sh2007003716
Gender-nonconforming people http://id.loc.gov/authorities/subjects/sh2017004882

**Comment by mariaforsen** [comment]
Sv. intergender ET genderqueer, icke-binaritet, icke-binära personer
