### ISSUE TITLE
Sārnate

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6349]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Sārnate 

#### Ehdotettu termi ruotsiksi   

Sārnate 

#### Ehdotettu termi englanniksi   

Sārnate 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2010001774> 
Wikipedia : https://fi.wikipedia.org/wiki/S%C4%81rnaten_suoasuinpaikka 

#### Tarkoitusta täsmentävä selite   

Sārnate on paikkakunnan (kylään ja sen lähellä virtaavan joen) nimi Latviassa. Se on myös arkeologinen kohde. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 651-kenttään. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2130684 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Sārnate](http://finto.fi/yse/fi/page/Y506349)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa Sārnate (Užava). Käsite viittaa kylään (ja voidaan käyttää myös arkeologisesta kohteesta).
