### ISSUE TITLE
Zemgale

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6350]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Zemgale 

#### Ehdotettu termi ruotsiksi   

Semgallen 

#### Ehdotettu termi englanniksi   

Semigallia 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2007006955> 
Wikipedia : https://fi.wikipedia.org/wiki/Zemgale 

#### Tarkoitusta täsmentävä selite   

Zemgale on kulttuurihistoriallinen ja historiallinen alue Latviassa. 

#### Perustelut ehdotukselle   

Tarvitaan sisällökuvailun 651-kentässä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2182956 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Zemgale](http://finto.fi/yse/fi/page/Y506350)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa Semigallia, ohjaustermiksi Zemgale. Semigallia on alueen suomenkielinen nimimuoto. Yläkäsitteeksi Latvia, RT:ksi Liettua. Vrt. Wikipedia: "Joskus siihen luetaan myös Liettuan puolisia alueita."
