### ISSUE TITLE
Hanhijärvi--Mikkeli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6353]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Hanhijärvi--Mikkeli 

#### Tarkoitusta täsmentävä selite   

Järvi Mikkelissä. 

#### Perustelut ehdotukselle   

Tarpeen julkaisun kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hanhijärven valuma-alueen vedenlaatu- ja kuormitusselvitys, http://urn.fi/URN:ISBN:978-952-314-683-9 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Hanhijärvi--Mikkeli](http://finto.fi/yse/fi/page/Y506353)

**Comment by ilona-x** [comment]
Lisätty YSAan Hanhijärvi (Mikkeli)
