### ISSUE TITLE
Latin rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6354]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Latin rock](http://www.yso.fi/onto/ysa/Y214541) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi muotoon "latinorock" ja siirretään nykyinen KT-muodoksi 

#### Perustelut ehdotukselle   

"Latin rock" on sitaattilaina, "latinorock" taas suomenkielinen muoto, jota mm. Yleisradio näyttää käyttävän [https://yle.fi/uutiset/18-49741] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by SamuVirokannas** [comment]
Kyllä latinorock on parempaa suomea. Tuosta tuli mieleen, olisiko tarvetta myös käsitteelle latinopop (tai vaihtoehtoisesti latino-pop)? Vai onko se käytännössä liian vaikea erottaa latinorockista? Myös latinojazz-käsitettä viljellään jonkin verran eri keskusteluissa ja tiedotusvälineissä.

**Comment by TommiViitamies** [comment]
Latinorock saattaa olla "parempaa suomea", mutta vastustan silti ehdotusta: latin rock on vakiintunut ilmaisu, joka viittaa tiettyyn tyyliin, ei mihin tahansa "latinorockiin". Tästä syystä vastustaisin myös latinopop-tyyppistä termiä, jos sellaista tulisi ehdotus; kyse on ilmeisesti (enimmäkseen) espanjankielisestä popista/viihteestä, jota tehdään Latinalaisessa Amerikassa. Sellaisia tyylillisiä tunnusmerkkejä ei ole, joita ei voitaisi ilmaista olemassa olevin termein. (Latin jazz saattaisi saada kannatukseni: afrokuubalainen jazz ei kata kaikkea "latin jazzia".)

**Comment by tpalonen** [comment]
Varovainen ääni "latin rock"-muodolle. Sen verran kuitenkin kumartaisin suomenkielen oikeinkirjoitussääntöjä kohden, että pienellä alkukirjaimella suosittaisin termin kirjoitettavan.

**Comment by MUUSA-kokous** [comment]
Alkuperäinen ehdotus hylätty.
Alkukirjain muutetaan pieneksi. KT:ksi latinorock
