### ISSUE TITLE
transvestismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6355]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[transvestismi](http://www.yso.fi/onto/ysa/Y106614) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nyt termi "ristiinpukeutuminen" ohjaa termiin "transvestismi". Haluaisin erottaa "ristiinpuketumisen" omaksi asiasanakseen, 

#### Perustelut ehdotukselle   

Elokuvassa ristiinpukeutuminen toimii komedian keinona, ei suoranaisesti seksuaali- tai sukupuoli-identiteettiin liittyvänä teemana. Komedian keinona ristiinpukeutuminen on käytössä muun muassa elokuvissa Kaksi vanhaa tukkijätkää (1954), Pekka ja Pätkä puistotäteinä (1955), Rakas lurjus (1955), Tyttö lähtee kasarmiin (1956), Pekka ja Pätkä sammakkomiehinä (1957), Virtaset ja Lahtiset (1959) ja Isaskar Keturin ihmeelliset seikkailut (1960). Myöhemmin ristiinpukeutumiselle perustuvaa komiikkaa nähdään myös muun muassa Uuno Turhapuro- ja Vääpeli Körmy –elokuvissa. Kyse on siis kansankomedialle tyypillisestä komedian keinosta, jonka taustalla on usein väärinkäsitys ja käytännöllinen tarve. 

#### Ehdottajan organisaatio   

Kansallinen audiovisuaalinen instituutti

**Comment by mariaforsen** [comment]
Myös SAO:ssa erikseen: crossdressing, LCSH-linkitys: Cross-dressing

**Comment by mirmaid** [comment]
LCSH:ssa _transvestism_ on ohjaustermi _cross-dressing_-termille (samoin transvestites > cross-dressers). Erottelu on kyllä mahdollista tehdä, mutta ilman tarkennetta _ristiinpukeutuminen_-termiä voisi käyttää laajemmin (ja päällekkäin transvestismin kanssa).

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:ristiinpukeutuminen

**Comment by YSA-kokous** [comment]
ristiinpukeutuminen (esittävät taiteet)

**Comment by jarmosaarikko** [comment]
http://transtukipiste.fi/transvestisuus/
**Transvestisuus** on ihmisillä monimuotoista ja voi kehittyä eri tavoin ja palvella erilaisia psykologisia ja sosiaalisia tehtäviä. (4). 

http://transtukipiste.fi/hlbtiq-sanasto/
**Transvestisuus.** 
Transvestisuus tarkoittaa, että henkilö tuntee ainakin ajoittain tarvetta ilmaista eläytymällä, pukeutumalla tai laittautumalla toista (binääristä) sukupuolta kuin mikä hänelle on syntymässä määritelty. **Transvestiitti** on usein tyytyväinen syntymässä määriteltyyn sukupuoleensa eikä hänellä ole tarvetta juridisiin muutoksiin ja/tai lääketieteellisiin korjauksiin sukupuolen suhteen. Monelle transvestiitille on tärkeää, että hänet kohdataan siinä sukupuolessa, jota hän kulloinkin ilmentää.
