### ISSUE TITLE
metsäjooga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6357]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsäjooga 

#### Ehdotettu termi ruotsiksi   

skog yoga 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-951-24-1120-7 Metsäjooga / Mia Jokineva 

#### Perustelut ehdotukselle   

Ysassa on muitakin joogan alalajeja 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [metsäjooga](http://finto.fi/yse/fi/page/Y506357)

**Comment by mariaforsen** [comment]
Sv. skogsyoga
