### ISSUE TITLE
Zvejniekin kalmisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6359]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Zvejniekin kalmisto 

#### Ehdotettu termi englanniksi   

Zvejnieki Burial Ground 

#### Ehdotettu termi ruotsiksi   

Zvejnieki gravfält 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh90005218> 
Wikipedia : https://fi.wikipedia.org/wiki/Zvejniekin_kalmisto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

Zvejniekin kalmisto on Vecaten kunnassa Latviassa sijaitse muinaishauta-alue, jossa on tehhty kaivauksia, 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 650-kenttään. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2012400 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Zvejniekin kalmisto](http://finto.fi/yse/fi/page/Y506359)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa Zvejniekin kalmisto. Näyttää vakiintuneen ja kirjallisuutta on eri kielillä Melindassakin. (vrt. Ajantan luolat)
