### ISSUE TITLE
Turaidan linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6361]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Turaidan linna 

#### Ehdotettu termi englanniksi   

Turaida Castle 

#### Ehdotettu termi ruotsiksi   

Turaida slott 

#### Ehdotettu yläkäsite YSOssa (LT)   

[linnat](http://www.yso.fi/onto/yso/p6790) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2008000439> 
Wikipedia : https://fi.wikipedia.org/wiki/Turaidan_linna 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2165650 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Latviassa Siguldassa sijaitseva Turaidan linna on Kalparitariston rakentamana. Alunperin sen paikalla oli liiviläisten linnoitus. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailuun 650-kenttään. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Turaidan linna](http://finto.fi/yse/fi/page/Y506361)

**Comment by mirmaid** [comment]
2 viitettä Melindassa
