### ISSUE TITLE
Lokstenen linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6364]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Lokstenen linna 

#### Ehdotettu termi ruotsiksi   

Lokstene borg 

#### Ehdotettu termi englanniksi   

Lokstene Castle 

#### Ehdotettu yläkäsite YSOssa (LT)   

[linnat](http://www.yso.fi/onto/yso/p6790) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://et.wikipedia.org/wiki/Loksti%C5%86i_vasallilinnus 

#### Tarkoitusta täsmentävä selite   

Lokstenen linna sijaitsee Latviassa Klintainen kunnassa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa kenttää 650. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1132170 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Lokstenen linna](http://finto.fi/yse/fi/page/Y506364)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mirmaid** [comment]
Vain erityisen merkittäviä ulkomaisia rakennuksia auktorisoidaan YSAan.
