### ISSUE TITLE
Lubāns-järvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6367]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Lubāns-järvi 

#### Ehdotettu termi ruotsiksi   

Lubāns sjö 

#### Ehdotettu termi englanniksi   

Lubāns Lake 

#### Vaihtoehtoiset termit ja ilmaisut   

Lubānsin järvi, Lubānsjärvi, Lubāns (järvi) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2001007039> 
Wikipedia : https://en.wikipedia.org/wiki/Lake_Lub%C4%81ns 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa kenttään 651. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Lubāns on Latvian suurin järvi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1636287 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Lubāns-järvi](http://finto.fi/yse/fi/page/Y506367)

**Comment by YSA-kokous** [comment]
Auktorisoitu muodossa Lubāns. Ulkomaisten järvien yläkäsitteet?
