### ISSUE TITLE
Holmsund (Ruotsi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6377]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Holmsund (Ruotsi) 

#### Ehdotettu termi ruotsiksi   

Holmsund (Sverige) 

#### Ehdotettu termi englanniksi   

Holmsund (Sweden) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n92012128> 
Wikidata : https://www.wikidata.org/wiki/Q388953 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.485099 

#### Perustelut ehdotukselle   

Kyseistä paikkakuntaa ei ole vielä ennestään YSAssa eikä YSOssa 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Holmsund (Ruotsi)](http://finto.fi/yse/fi/page/Y506377)

**Comment by mirmaid** [comment]
Taajama Uumajan kunnassa. Holmsund on kuitenkin aikaisemmin ollut itsenäinen kunta, joten linjauksemme mukaan se ei tarvitse tarkennetta. Samanniminen kylä löytyy kuitenkin Norjasta, eli lisätäänkö tarkenne (Ruotsi)?

**Comment by YSO-kokous** [comment]
Otetaan muodossa Holmsund, sulkutarkennetta ei tarvita. Viittaa Ruotsin taajamaan.
