### ISSUE TITLE
yhteiskuntatieteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6380]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhteiskuntatieteet](http://www.yso.fi/onto/ysa/Y100394) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: yhteiskuntatutkimus (tai mahdollisesti erillisenä uutena terminä) ? 

#### Perustelut ehdotukselle   

On käytetty Melindassakin melko paljon (sv. samhällsforskning)

**Comment by mirmaid** [comment]
https://www10.uta.fi/opas/koulutus.htm?opsId=165&uiLang=fi&lang=fi&lvv=2018&koulid=473

**Comment by YSA-kokous** [comment]
Ohjaustermi
