### ISSUE TITLE
GARCH-mallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6381]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

GARCH-mallit 

#### Ehdotettu termi ruotsiksi   

GARCH-modeller 

#### Ehdotettu termi englanniksi   

GARCH models 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mallit (tuotokset)](http://www.yso.fi/onto/yso/p510) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARIMA- ja Garch-mallit sekä mallin sovittaminen osakeaineistoon / Laura Lizana Bister 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

**Termiehdotus Fintossa:** [GARCH-mallit](http://finto.fi/yse/fi/page/Y506381)

**Comment by mirmaid** [comment]
LCSH: GARCH model

**Comment by mirmaid** [comment]
Melindassa 4 kertaa yksikössä, 2 kertaa monikossa. Ehkä kuitenkin monikko, mallista on variaatioita.
