### ISSUE TITLE
Trakain linna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6382]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Trakain linna 

#### Ehdotettu termi ruotsiksi   

Trakai slott 

#### Ehdotettu termi englanniksi   

Trakai Island Castle 

#### Ehdotettu yläkäsite YSOssa (LT)   

[linnat](http://www.yso.fi/onto/yso/p6790) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh00010159.html> 
Wikipedia : https://fi.wikipedia.org/wiki/Trakain_linna 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.595203 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Trakain linna sijaitsee samannimisen kaupungin edustalla Galvė-nimisellä järvellä olevalla saarella. Tarkalleen ottaen se on 'Trakain saarilinna', mutta suomeksi riittänee pelkkä 'linna'. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Trakain linna](http://finto.fi/yse/fi/page/Y506382)

**Comment by paivalai** [comment]
Muutetaan 651-kenttään laitettavaksi maantieteelliseksi asiasanaksi.

**Comment by mirmaid** [comment]
Auktorisoitu _Trakai_.
