### ISSUE TITLE
kansalaissota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6392]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansalaissota](http://www.yso.fi/onto/ysa/Y104966) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

prefLabel muotoon "sisällissota" tai "Suomen sisällissota" 

#### Perustelut ehdotukselle   

sisällissota lienee tapahtumasta nykyisin suosittu (neutraali) termi 

#### Ehdottajan organisaatio   

Kansalliskirjasto/Mikko Lappalainen

**Comment by EsaMPKK** [comment]
Suomen sisällissota olisi selkeä.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kansalaissota_(yleistermi)

**Comment by mirmaid** [comment]
YSAssa on jo _sisällissodat_, joten ehdotetuista vaihtoehdoista vain _Suomen sisällissota_ on mahdollinen.

**Comment by mariaforsen** [comment]
Allärs jo nyt: finska inbördeskriget

**Comment by mirmaid** [comment]
Voiko termeille _punaiset_ ja _valkoiset_ jäädä tarkenne (kansalaissota)?

**Comment by YSA-kokous** [comment]
Muutetaan tarkenteet.
