### ISSUE TITLE
kansalaispalkka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6406]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansalaispalkka](http://www.yso.fi/onto/ysa/Y95836) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Kansalaispalkka on vanha, jo 70-luvulla esitelty termi. nykyään perustulo on vakiintuneempi termi sekä tutkimuksessa että mediassa. Näin suositteli tutkimusprofessori Olli Kangas, Suomen perustulohankkeen vetäjä 
Miska Simanainen, tutkija, perustulohanke: mielestäni noissa [perustulo/kansalaispalkka] ei ole olennaista merkityseroa, koska niitä on käytetty molempia eri merkityksissä, myös päällekkäisissä. Ajallinen ero on ainakin olennainen mielestäni eli käsittääkseni perustulo on uudempi termi suomenkielessä. 

#### Ehdotettu muutos   

perustulo lisätään sanastoon

**Comment by mariaforsen** [comment]
SAO: medborgarlön, korvattuna basinkomst, grundinkomst

**Comment by satuniininen** [comment]
Eli siis tällä hetkellä sanastossa kansalaispalkka KT perustulo. Vaihdetaanko toisin päin?
