### ISSUE TITLE
adoptiotuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6410]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

adoptiotuki 

#### Perustelut ehdotukselle   

http://www.kela.fi/adoptiotuki 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [adoptiotuki](http://finto.fi/yse/fi/page/Y506410)

**Comment by mariaforsen** [comment]
Sv. adoptionsbidrag ET adoptionsstöd
