### ISSUE TITLE
lastenhoidon tuet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6411]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lastenhoidon tuet 

#### Perustelut ehdotukselle   

http://www.kela.fi/lastenhoidon-tuet
Lisäksi puuttuvat alakäsitteet:
Joustava hoitoraha http://www.kela.fi/joustava-hoitoraha 
Osittainen hoitoraha http://www.kela.fi/osittainen-hoitoraha 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [lastenhoidon tuet](http://finto.fi/yse/fi/page/Y506411)

**Comment by ilona-x** [comment]
ehdotuksissa myös: osittainen hoitoraha #6500

**Comment by mariaforsen** [comment]
Sv. barnavårdsstöd

**Comment by mirmaid** [comment]
_joustava hoitoraha_ jäi käsittelemättä

**Comment by YSA-kokous** [comment]
joustava hoitoraha

**Comment by mariaforsen** [comment]
Sv.  flexibel vårdpenning
