### ISSUE TITLE
Jumindan meritaistelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6414]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Jumindan meritaistelu 

#### Ehdotettu termi ruotsiksi   

Jumindas slaget 

#### Ehdotettu termi englanniksi   

Sjöslaget vid Juminda 

#### Vaihtoehtoiset termit ja ilmaisut   

Juminda Naval Battle 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Tallinnan_evakuointi 

#### Tarkoitusta täsmentävä selite   

Jumindan meritaistelu tapahtui 1941 Tallinnaa evakuoitaessa, 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailuun. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2033323 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Jumindan meritaistelu](http://finto.fi/yse/fi/page/Y506414)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6141

**Comment by mariaforsen** [comment]
Nämä muodot hyvin vähän googlessa, muita muotoja/tapoja käsitellä asiaa?

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by ilona-x** [comment]
EMS http://ems.elnet.ee/: 
Juminda miinilahing, 1941
Battle of Juminda, 1941

**Comment by EsaMPKK** [comment]
Jumindan miinasulku löytyy kirjallisuudesta.

**Comment by YSA-kokous** [comment]
Jumindan miinasulku

**Comment by mariaforsen** [comment]
Sv. Juminda minspärr ET Juminda minblockad,  Juminda-barriären
