### ISSUE TITLE
resurssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6416]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[resurssit](http://www.yso.fi/onto/ysa/Y104172) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

No ei oikein perhetyössä voi puhua resursseista eli voimavarat-asiasana olisi tarpeen esim. perheen voimavarat. 

#### Perustelut ehdotukselle   

-

**Comment by satuniininen** [comment]
Ei ole tällaisenaan käännettävissä myöskään englanniksi. Vaatii ainakin täsmällisemmän rajauksen.

_Resurssit_-asiasanaa on käytetty melko runsaasti myös yksilön (henkisiä) voimavaroja kuvaavassa käytössä, esim. _Autismi asuu meillä : äidin kokemukset sopeutumisesta lapsen autismidiagnoosin jälkeen_  ja _Elämänlaadun ja elämän merkityksellisyyden kokemisen yhteydet työttömien työkykyyn_ .

Lisäksi sanastossa on runsaasti täsmällisempää käsitteistöä, kuten _henkinen hyvinvointi, stressinhallinta, sosiaaliset taidot, toimeentulo, henkinen pääoma, sosiaalinen pääoma_ jne.
_Voimavarat_ (samoin kuin _resurssit_) mieltyy ehkä enemmän kattokäsitteeksi, sillä aihepiiriä voi lähestyä niin monesta näkökulmasta.

**Comment by YSA-kokous** [comment]
Ei muutosta
