### ISSUE TITLE
hyväksyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6417]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hyväksyminen](http://www.yso.fi/onto/ysa/Y112816) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista jakaa tms.? Esim. hyväksyminen (psykologia), hyväksyminen (menettely)

#### Perustelut ehdotukselle   

Allärs: acceptans + godkännande = hyväksyminen 

Melindassa käytetty kahdella eri tapaa, esim.: 
-Parempaa kohti : voi hyvin sairaudesta huolimatta / Helena Hallenberg.
-Lattiamallisen LVI-keskuksen tuotehyväksyttäminen : Tulvari EK-1000 / Esa Karhumaa.

**Comment by satuniininen** [comment]
Entä jako hyväksyminen (psykologia) + hyväksyntämenettely KT hyväksyntä (tarkastus)?

esim:
http://julkaisut.valtioneuvosto.fi/handle/10024/78551
http://www.ym.fi/fi-FI/Maankaytto_ja_rakentaminen/Rakentamisen_ohjaus/Rakennustuotteiden_tuotehyvaksynta/Kansalliset_hyvaksyntamenettelyt
https://www.stuk.fi/-/tarkastuslaitosten-hyvaksyntamenettely-muuttuu

**Comment by mariaforsen** [comment]
Sv. acceptans, godkännandeförfarande

**Comment by mirmaid** [comment]
EKS: hyväksymismenettely, samtyckesförfarandet

**Comment by YSA-kokous** [comment]
hyväksyminen (psykologia)
hyväksyminen (menettely) KT hyväksyntä (tarkastus)
