### ISSUE TITLE
länsimaiset kulttuurivaikutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6418]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

länsimaiset kulttuurivaikutukset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [länsimaiset kulttuurivaikutukset](http://finto.fi/yse/fi/page/Y506418)

**Comment by tpalonen** [comment]
Käsite muistuttaa auktorisoitua asiasanaketjua: kulttuurivaikutukset - länsimaat. Nämä löytyvät sanastosta jo erillisinä. Kulttuuri-imperialismi ei sen sijaan ole sanastossa ja se olisi ehdotetun käsitteen merkityksen kanssa osittain päällekkäinen, esiintyy Melindassa kolmesti. LCSH:sta kulttuuri-imperialismia ei löydy, mutta sen sijaan löytyy Western influences ja sen erilaisia ketjujohdannaisia.

**Comment by YSA-kokous** [comment]
kulttuuri-imperialismi
