### ISSUE TITLE
Pirita

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6420]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Pirita 

#### Ehdotettu termi ruotsiksi   

Pirita 

#### Ehdotettu termi englanniksi   

Pirita 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n81066648> 
Wikipedia : https://fi.wikipedia.org/wiki/Pirita 

#### Tarkoitusta täsmentävä selite   

Pirita on Tallinnan kaupunginosa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2409028 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Pirita](http://finto.fi/yse/fi/page/Y506420)

**Comment by paivalai** [comment]
Tarkennus:
Hierarkia siis Tallinna > Pirita (fin), Tallinn > Pirita (swe), Tallinn > Pirita (eng).
