### ISSUE TITLE
sämplääjät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6422]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sämplääjät](http://www.yso.fi/onto/ysa/Y214689) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite. 

#### Perustelut ehdotukselle   

Käsitteelle on vaikea kuvitella tarvetta kuvailussa. Harvinainen termi, jonka merkityskin on epäselvä. Viitataanko sämpleri-laitteen käyttäjään vai sämplejä musiikissaan toteutustavasta riippumatta käyttävään artistiin? Samplerin käyttäjästä ei elektronisen musiikin puolella puhuta käyttämällä tällaista termiä. Sampleria ei yleensä käytetä yksinään, vaan sen hyödyntäminen on vain yksi osa musiikintekoprosessia. Tuntuu oudolta, että tälle laitteelle/työvaiheelle pitää olla oma tekijäkäsitteensä. Eihän sanastossa ole muutenkaan vastaavia: rumpukoneen käyttäjä, efektipedaalin käyttäjä tai vaikkapa monistuskoneen käyttäjä.

Lisäksi tämä on ongelma englannin kielen kannalta, koska sampleri ja samplaaja ilmaistaan englanniksi samalla termillä. 

#### Ehdottajan organisaatio   

KK

**Comment by TommiViitamies** [comment]
Kannatan.

**Comment by ksornova** [comment]
Pitäisikö kuitenkin termi saada Metatietosanastoon, jos sille olisi käyttöä esim. toimijoiden kuvailussa?

**Comment by tpalonen** [comment]
Vaikea kuvitella tilannetta, jossa tälle olisi käyttöä toimijoiden kuvailussa. Termi ei ole yleistynyt. Minun tietooni on harvinaista, että esityskokoonpanossa olisi soittaja, joka vastaisi vain ja ainoastaan sämplerin käytöstä ja että hänestä käytettäisiin nimeä sämplääjä.

**Comment by MUUSA-kokous** [comment]
Alkuperäinen ehdotus hyväksytty.
