### ISSUE TITLE
maailmanmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6423]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maailmanmusiikki](http://www.yso.fi/onto/ysa/Y107796) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään tämän alakäsitteet toisaalle. Korvataan tarvittaessa nämä suhteet RT-suhteilla. 

#### Perustelut ehdotukselle   

Maailmanmusiikki on sekä käsitteenä että luokittelun välineenä eurosentrinen ja kyseenalainen. Se on kuitenkin laajalti käytössä, joten sen olemassaolo sanastossa on toki sitä kautta perusteltua. Hierarkiaa korjaamalla saataisiin kuitenkin tietyille ei-länsimaalaisille populaarimusiikin genreille tasavertainen kohtelu vastaavien länsimaisten genrejen kanssa. Toisaalta hierarkia on tällä hetkellä ristiriitainen: tietyt ei-länsimaiset (eli "eksoottiset") populaarimusiikin genret ovat tällä hetkellä maailmanmusiikki-käsitteen alakäsitteitä, toiset vastaavat taas muualla hierarkiassa. Esim. afrikkalaiset genret mbalax, mbaqanga ja soukous ovat maailmanmusiikin alla, mutta niin ikään afrikkalaiset highlife ja rai ovat populaarimusiikin alla. Tämän epäsuhdankin vuoksi olisi parempi, että alakäsitteet siirrettäisiin kokonaisuudessaan muualle (esim. populaarimusiikin alle) ja tarvittaessa korvattaisiin RT-suhteella.

Maailmanmusiikki-käsitteeseen liittyvästä kritiikistä ks. esim.
https://en.wikipedia.org/wiki/World_music#Criticisms
https://www.theguardian.com/music/musicblog/2012/mar/22/world-music-outdated-offensive 

#### Ehdottajan organisaatio   

KK

**Comment by asormune** [comment]
Kannatan maailmanmusiikin genrejä populaarimusiikin alle. Pitäisikö maailmanmusiikin määritelmää viilata? "Eksoottisempien" genrejen suhde perinnemusiikkiin on aina ollut, ainakin minulle, vaikeaa työmaata. Myös jako kansanmusiikki vs perinnemusiikki lyö monesti tyhjää. Monesti päätyy asiasanoittamaan "varmuuden vuoksi" useammilla (rinnakkaisilla) termeillä. Hyvien määritelmien teko on haastavaa..

**Comment by MUUSA-kokous** [comment]
Alkuperäinen ehdotus hyväksytty.
Alatermit siirretään myös SLM:stä.

**Comment by mirmaid** [comment]
Eli siirretäänkö kaikki alakäsitteet populaarimusiikin alle?

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa, että maailmanmusiikin nykyiset alakäsitteet siirretään populaarimusiikki-käsitteen alle. Lisätään näille kuitenkin RT maailmanmusiikki.
