### ISSUE TITLE
unihalvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6426]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

unihalvaus 

#### Ehdotettu termi ruotsiksi   

sömnparalys, sömnförlamning 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Selkeä termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789522914521 Outojen kokemusten psykologia 

**Ehdottajan organisaatio:** Outi Hintikka, BTJ **Termiehdotus Fintossa:** [unihalvaus](http://finto.fi/yse/fi/page/Y506426)

**Comment by ilona-x** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D020188
LCSH: http://id.loc.gov/authorities/subjects/sh85123409
https://fi.wikipedia.org/wiki/Unihalvaus

**Comment by mariaforsen** [comment]
Sv. sömnparalys ET sömnförlamning
