### ISSUE TITLE
verkkourkinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6427]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkourkinta](http://www.yso.fi/onto/ysa/Y146395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

verkkohuijaus omaksi termikseen 

#### Perustelut ehdotukselle   

YSAssa verkkohuijaus on referenssiterminä; käytettävä termiä verkkourkinta. Ihmettelen ratkaisua, sillä mielestäni nämä eivät ole koskaan olleet sama asia. Teos, jonka yhteydessä asiaa pohdin: 9789522029034 Tarinoita toiselta puolelta :verkkohuijareiden metsästäjät kertovat / Riku Salmivuori. 

#### Ehdottajan organisaatio   

Outi Hintikka, BTJ

**Comment by ilona-x** [comment]
YSA: verkkourkinta KT phishing, verkkohuijaus http://finto.fi/ysa/fi/page/Y146395

LCSH: Internet fraud http://id.loc.gov/authorities/subjects/sh98004235.html
BT Computer crimes
NT Internet auction fraud, Phishing

**Comment by mariaforsen** [comment]
Sv. nätbedrägeri, internetbedrägeri
Myös https://fi.wikipedia.org/wiki/Internethuijaus 
Ruotsiksikin nämä ovat eri asioita ja SAOssa tietysti molemmat erikseen: nätbedrägeri (=verkkohuijaus) ST nätfiske (=verkkourkinta)

**Comment by mirmaid** [comment]
Muistelen että aikaisemmin olisi todettu rikoksen olevan petos näissä rahahuijauksissa? Tietoverkkorikoksiin liittyvää termistöä on jo aika paljon, mutta voidaan kyllä vielä miettiä pitäisikö tämä kuitenkin lisätä. Ei Melindassa.

**Comment by satuniininen** [comment]
Minusta tähän riittäisi tietoverkkorikokset + rikosnimike esim. petokset. 

Kuten Mirja totesi, tämän aihepiirin termejä on otettu sanastoon viime vuosina paljon. Osa näistä termeistä jää todennäköisesti hyvin lyhytikäisiksi, joten ehkä tässä vaiheessa ei kannata ottaa käyttöön kaikkea mahdollista.

**Comment by YSA-kokous** [comment]
Ei muutosta.
