### ISSUE TITLE
roudarit, roudaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6430]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

roudarit, roudaus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

ammattinimeke 

#### Perustelut ehdotukselle   

Sähköpostikeskusteluhistoriassani lukee, että termi olisi hyväksytty. En löytänyt sanastosta, joten siksi näin pyydetty. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Roudarit :vastuun ja kamojen kantoa jo vuodesta 1965 

**Ehdottajan organisaatio:** Outi Hintikka, BTJ **Termiehdotus Fintossa:** [roudarit, roudaus](http://finto.fi/yse/fi/page/Y506430)

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6087
