### ISSUE TITLE
öljyliuske

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6431]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

öljyliuske 

#### Ehdotettu termi ruotsiksi   

oljeskiffer 

#### Ehdotettu termi englanniksi   

Oil-shale 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85094361> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 
[32 Kaivosteollisuus. Kaivannaisteollisuus](http://www.yso.fi/onto/yso/p26567) 

#### Tarkoitusta täsmentävä selite   

Öljyliuske on kai virallinen nimi, mutta Viron kautta mineraali tunnetaan paremmin palavanakivenä. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.152549 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [öljyliuske](http://finto.fi/yse/fi/page/Y506431)

**Comment by mirmaid** [comment]
YSAssa on _liuskeöljy_, Melindassa öljyliuske 20 viitettä, palavakivi 13.

**Comment by satuniininen** [comment]
LCSH:ssa on molemmat shale oils ja oil-shales
