### ISSUE TITLE
Ukrainan kriisi, Ukrainan sota, Donbassin sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6432]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ukrainan kriisi, Ukrainan sota, Donbassin sota 

#### Tarkoitusta täsmentävä selite   

Itä-Ukrainan sota (myös Ukrainan kriisi, Ukrainan sota[4] tai Donbassin sota) on huhtikuussa vuonna 2014 alkanut Ukrainan hallituksen ja Venäjän tukemien joukkojen, kapinallisten tai separatistien välinen aseellinen yhteenotto Itä-Ukrainassa. (Wikipedia) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789525412215 Karhu: Viimeinen luoti 

#### Perustelut ehdotukselle   

Tarvitaan yksi valittu termi, jossa mukana seite 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

**Ehdottajan organisaatio:** Outi Hintikka, BTJ **Termiehdotus Fintossa:** [Ukrainan kriisi, Ukrainan sota, Donbassin sota](http://finto.fi/yse/fi/page/Y506432)

**Comment by mirmaid** [comment]
_Ukrainan kriisi_ Melindassa 5 kertaa.

https://fi.wikipedia.org/wiki/It%C3%A4-Ukrainan_sota
