### ISSUE TITLE
kuntoiluvälineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6437]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuntoiluvälineet](http://www.yso.fi/onto/ysa/Y96554) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: harjoitteluvälineet 

#### Perustelut ehdotukselle   

Ruotsiksi muutetaan kuntoiluvälineet = träningsredskap jos tämä pätee. 

#### Ehdottajan organisaatio   

Allärs

**Comment by mirmaid** [comment]
Harjoittelu on kyllä laajempi kuin kuntoilu, esim. https://www.huippupelaaja.fi/category/103/jaakiekko. Usein olisi ok ja suomeksi ei käytettäisi väärin vaikka olisikin tämä ohjaustermi, mutta virheitä voisi tulla jos tehtäisiin ruotsiksi ja suomenkielinen vastine lisättäisiin automaattisesti.

Ehkä tässä pitäisi ennemmin yhdistää/vaihtaa termejä, jos ruotsiksi ei ole hyvää vastinetta kuntoilulle?

**Comment by mariaforsen** [comment]
Kuntoilu on ymmärtääkseni korvattu termi kuntoliikunnalle ja se on kyllä ok ruotsiksi. Kyseessä on nyt lähinnä se että kuntoiluvälineet on ollut motionsredskap. Oikeastaan käytetään ruotsiksi yleensä termiä träningsredskap kun puhutaan siitä, mistä puhutaan kun käytetään termiä kuntoiluvälineet. Mutta jos on mahdollista että otetaan harjoitteluvälineet erillisenä pääterminä, niin sitten ei välttämättä voida tehdä tätä, muuten haluttua, muutosta.

**Comment by YSA-kokous** [comment]
Muutos Allärsissa
