### ISSUE TITLE
dokumenttidraamat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6438]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dokumenttidraamat](http://www.yso.fi/onto/ysa/Y111964) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi korvattu termi: todellisuuspohjaiset elokuvat 

#### Perustelut ehdotukselle   

Näin Suomalainen lajityyppi- ja muotosanastossa. Jos termin määritelmä (YSAssa): "Tarkoittaa fiktiivistä elokuvaa, joka pohjautuu todellisiin tapahtumiin " oikeasti pätee, niin vaihdetaan päätermi ruotsiksi > verklighetsbaserade filmer. 

#### Ehdottajan organisaatio   

Allärs

**Comment by LeKorsu** [comment]
Kyselin tv-arkistoaineistokollegoiden mielipidettä ja sain palautetta, että parempi olisi käyttää preflabelina todellisuuspohjaiset elokuvat kuin dokumenttidraamat, joka vaarassa sekoittua draamadokumentteihin huomautuksesta huolimatta

**Comment by YSA-kokous** [comment]
Kaunokki, SLM

**Comment by YSA-kokous** [comment]
todellisuuspohjaiset elokuvat
