### ISSUE TITLE
teoreettinen fysiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6439]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

teoreettinen fysiikka 

#### Ehdotettu termi ruotsiksi   

teoretisk fysik 

#### Ehdotettu termi englanniksi   

theoretical physics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fysiikka](http://www.yso.fi/onto/yso/p900) 

#### Vastaava käsite muussa sanastossa   

SAO : Teoretisk fysik 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Perustelut ehdotukselle   

Käytetty Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   
Compendium of theoretical physics / Armin Wachter, Henning Hoeber.
The road to reality : a complete guide to the laws of the universe / Roger Penrose.
Spatially dependent parton distribution functions and hard processes in nuclear collisions / by Ilkka Helenius. 

**Termiehdotus Fintossa:** [teoreettinen fysiikka](http://finto.fi/yse/fi/page/Y506439)

**Comment by mirmaid** [comment]
Käytetty Melindassa ysa-terminä yli 30 kertaa. YSAssa on _teoreettinen filosofia_ (ja _käytännöllinen filosofia_).
