### ISSUE TITLE
ehdokasasettelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#644]
#### Ehdotettu termi suomeksi

ehdokasasettelu
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)

**Luontipäivämäärä:** 12.09.2001

**Muokkauspäivämäärä:** 12.9.2001, 16.12.2008

**Voyager-id:** 115146

**Termiehdotus Fintossa:** [ehdokasasettelu](http://finto.fi/yse/fi/page/Y315146)

**Comment by henriyli** [comment]
YSAan 12.12.2003: http://www.yso.fi/onto/ysa/Y128396
