### ISSUE TITLE
Piritan luostari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6441]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Piritan luostari 

#### Ehdotettu termi ruotsiksi   

Birgittaklostret, Tallinn 

#### Ehdotettu termi englanniksi   

Pirita convent 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luostarit](http://www.yso.fi/onto/yso/p816) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n84203479> 
Wikipedia : https://fi.wikipedia.org/wiki/Piritan_luostari 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Piritan luostari sijaitsee Tallinnassa. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2951180 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Piritan luostari](http://finto.fi/yse/fi/page/Y506441)

**Comment by mariaforsen** [comment]
Sv. Pirita kloster ET Birgittaklostret (Tallinn)
