### ISSUE TITLE
Piritajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6442]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Piritajoki 

#### Ehdotettu termi ruotsiksi   

Pirita jõgi 

#### Ehdotettu termi englanniksi   

Pirita (river) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85102437> 
Wikipedia : https://fi.wikipedia.org/wiki/Pirita_j%C3%B5gi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Ehdotettu muoto on Piritajoki, vaikka esim. Wikipedia tarjoaa joen suomessa käytettäväksi nimeksi 'Pirita jõgi'. Joki virtaa Virossa Harjumaalla laskien Suomenlahteen Piritan kaupunginosassa. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1437218 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Piritajoki](http://finto.fi/yse/fi/page/Y506442)

**Comment by mirmaid** [comment]
Jokien yläkäsitteet (Viro/Harjumaa?)

**Comment by mirmaid** [comment]
Vuoristojen yläkäsitteet?

**Comment by YSO-kokous** [comment]
Ulkomaalaisten jokien osalta yläkäsitteeksi merkitään se maa tai ne maat, joiden alueella kyseinen joki virtaa. Samaa sääntöä voisi soveltaa myös vuoristoihin, järviin, vuoriin ja muihin vastaaviin.

Todettiin, että olisi käyttäjäystävällistä, että kaikki joet ym on hierarkisoitu samalla tarkkuustasolla.
