### ISSUE TITLE
Kalamaja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6444]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kalamaja 

#### Ehdotettu termi ruotsiksi   

Kalamaja 

#### Ehdotettu termi englanniksi   

Kalamaja 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n97119789> 
Wikipedia : https://fi.wikipedia.org/wiki/Kalamaja_(Tallinnan_asuinalue) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Kalamaja on Tallnnan kaupunginosa. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2660659 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Kalamaja](http://finto.fi/yse/fi/page/Y506444)

**Comment by paivalai** [comment]
Lisätarkennus: Kalamaja on siis asuinalue Põhja-Tallinn -nimisessä kaupunginosassa. Mutta hierarkia ei ole Tallinna > Põhja-Tallinn > Kalamaja. Vrt. Helsinki > Jollas, josta Laajasalo jätetty välistä pois.
