### ISSUE TITLE
Petserinmaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6451]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Petserinmaa 

#### Ehdotettu termi englanniksi   

Petseri County 

#### Ehdotettu termi ruotsiksi   

Petseri (?) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n93096696> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Petserinmaa oli maakunta Virossa vuosina 1920-1940. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2062676 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Petserinmaa](http://finto.fi/yse/fi/page/Y506451)

**Comment by mirmaid** [comment]
Voiko tehdä KÄ Setumaa? https://fi.wikipedia.org/wiki/Petserinmaa, https://fi.wikipedia.org/wiki/Setumaa

**Comment by YSO-kokous** [comment]
Petserinmaa KÄYTÄ Setumaa

**Comment by ilona-x** [comment]
https://ems.elnet.ee/index.php
Petseri maakond Petseri County   
Use:Setumaa Setumaa
