### ISSUE TITLE
rahoitussuunnittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6461]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rahoitussuunnittelu 

#### Ehdotettu termi ruotsiksi   

finansiell planering 

#### Ehdotettu termi englanniksi   

financial planning 

#### Ehdotettu yläkäsite YSOssa (LT)   

[suunnittelu](http://www.yso.fi/onto/yso/p1377) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Tarkoitusta täsmentävä selite   

Määritelmä esim: https://www.yrittajat.fi/yrittajan-abc/taloushallinto-ja-maksut/rahoitussuunnittelu-316381 

#### Perustelut ehdotukselle   

Käytetty Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Modeller för finansiell planering och analys / Jan Greve ; Fundamentals of financial management / James C. Van Horne, John M. Wachowicz, jr. 

**Termiehdotus Fintossa:** [rahoitussuunnittelu](http://finto.fi/yse/fi/page/Y506461)

**Comment by mirmaid** [comment]
4 viitettä Melindassa. Termi on JUHO-ontologiassa, lisäksi rahoitussuunnitelma(t) joissakin ontologioissa.

Yhdistelmää _rahoitus_ & _suunnittelu_ Melindassa runsaasti.

**Comment by mirmaid** [comment]
Sanastossa on _taloussuunnittelu_, joka on englanniksi financial planning. LIITOssa on _rahoitussuunnitelma_ = financing plan, fnansieringsplan.

**Comment by mariaforsen** [comment]
Sv. finansiell planering ET finansplanering, finansieringsplanering
