### ISSUE TITLE
industriell organisation

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6462]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

toimialan taloustiede? 

#### Ehdotettu termi ruotsiksi   

industriell organisation 

#### Ehdotettu termi englanniksi   

industrial organization 

#### Vastaava käsite muussa sanastossa   

SAO : industriell organisation 
LCSH : Industrial organization 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Toimialan_taloustiede
https://en.wikipedia.org/wiki/Industrial_organization 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Använts i Melinda (på svenska 92 gånger). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

T.ex. Introduction to industrial organization / Luís M.B. Cabral ; Industrial organization : theory and practice / Don E. Waldman, Elizabeth J. Jensen ; Ambitioner att förändra och artefakters verkan : gränsskapande och stabiliserande praktiker på produktionsgolvet / Gun-Britt Wärvik. 

**Termiehdotus Fintossa:** [industriell organisation](http://finto.fi/yse/fi/page/Y506462)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.
http://taloustieteellinenseura.fi/mita-on-mikrotaloustiede/
