### ISSUE TITLE
kompetensutveckling

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6463]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

kompetensutveckling 

#### Ehdotettu termi suomeksi   

osaamisen/pätevyyden kehittäminen? 

#### Ehdotettu termi englanniksi   

competence development? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[utveckling (verksamhet)](http://www.yso.fi/onto/yso/p4230) 

#### Assosiatiiviset (RT)   

[kompetens](http://www.yso.fi/onto/yso/p24064) 
[kompetensbehov](http://www.yso.fi/onto/yso/p22583) 
[fortbildning](http://www.yso.fi/onto/yso/p6266) 

#### Vastaava käsite muussa sanastossa   

SAO : kompetensutveckling 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Förvaltning. Organisationsforskning. Offentlig förvaltning](http://www.yso.fi/onto/yso/p26524) 
[78 Arbetsliv. Arbetarskydd. Företagshälsovård](http://www.yso.fi/onto/yso/p26525) 

#### Tarkoitusta täsmentävä selite   

Rikstermbanken: "Utveckling i arbetet utifrån verksamheten och de egna behoven, genom alltifrån utbildningar och studiebesök till arbetsrotation och nätverk" 

#### Perustelut ehdotukselle   

Använts i Melinda (på svenska 115 ggr.) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

T.ex. Att utveckla professionell expertis : en bok om kunskap och lärande / Gunilla Avby ; Utveckla eller köpa kompetens : avlasta, komplettera, möjliggöra, förändra / Jörgen Hansson ;  	Human Resource Development : att utveckla medarbetare och organisationer / Peter Nilsson, Andreas Wallo, Dan Rönnqvist, Bo Davidson ; Lifelong learning travels : single actors’ perception and talk of lifelong learning in a specific organizational context / Annica Isacsson. 

**Termiehdotus Fintossa:** [kompetensutveckling](http://finto.fi/yse/fi/page/Y506463)

**Comment by mirmaid** [comment]
LIITOssa ja TSR-ontologiassa on _osaamisen kehittäminen_. Melindassa 19 viitettä (joissakin esiintyy vaihtelevassa muodossa, esim. ammatillisen osaamisen kehittäminen). Usein voisi yhtä hyvin kuvailla termillä _osaamisen johtaminen_.

**Comment by mirmaid** [comment]
_Osaaminen - kehittäminen_ Melindassa ketjuna 131 kertaa.

**Comment by EsaMPKK** [comment]
osaamisen kehittäminen

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by jarmosaarikko** [comment]
https://www.kt.fi/henkilostojohtaminen/osaamisen-johtaminen
**Osaamisen johtaminen** on osa strategista henkilöstöjohtamista
**Osaamisen kehittäminen** on suunnitelmallista osaamisen ylläpitämistä ja päivittämistä tulevaisuuden tarpeita varten. Se on myös poistuvan osaamistarpeen korvaamista tarvittavalla osaamisella ja täysin uuden osaamisen hankkimista. Osaamisen kehittäminen perustuu tietoon, jota osaamisen ennakoinnilla on hankittu tulevaisuuden osaamistarpeista.
Joni Ruohomäen gradussa (SeAMK, 2016, sivu 6) nämä on määritelty näin:
**Osaamisen johtaminen** 
Osaamisen johtamisessa tärkeintä on organisaatiossa toimivien yksilöiden osaamisen _tason parantaminen ja vaaliminen sekä sen tehokas hyödyntäminen_. Sen tarkoituksena on toiminta- ja kilpailukyvyn varmistaminen ja vahvistaminen osaamispohjan avulla.
**Osaamisen kehittäminen** 
Osaamisen kehittämisessä organisaation yksilöiden osaamisia kehitetään ja uudistetaan _haluttuun suuntaan_. Tärkeänä osana sitä toimii osaamisten _tunnistaminen_ ja niiden vertaaminen tulevaisuuden tarpeisiin.
http://www.theseus.fi/handle/10024/119124

**Comment by YSA-kokous** [comment]
osaamisen kehittäminen
