### ISSUE TITLE
spänning (känslotillstånd)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6464]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jännitys (tunnetilat) 

#### Ehdotettu termi ruotsiksi   

spänning (känslotillstånd) 

#### Ehdotettu termi englanniksi   

tension..? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologi](http://www.yso.fi/onto/yso/p26543) 

#### Tarkoitusta täsmentävä selite   

"Känsla av både (viss) rädsla eller nervositet och lust" 

#### Perustelut ehdotukselle   

Använd i Melinda. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Effects of emotional excitement on cardiovascular regulation / Olli-Pekka Piira ; Nuorten pelot ja jännitykset : nuorten antamia merkityksiä peloille ja jännitykselle internet-keskusteluissa / Tiina Ojala. 

**Termiehdotus Fintossa:** [spänning (känslotillstånd)](http://finto.fi/yse/fi/page/Y506464)

**Comment by tarjaturunen** [comment]
Kannatan tätä asiasanaksi. Englanninkielinen termi "excitement". Kuvailussa teoksessa: Emotions, everyday life and sociology"

**Comment by mirmaid** [comment]
KÄ _jännittäminen_?

**Comment by mariaforsen** [comment]
Ainakaan ruotsiksi ei ole sama kuin spändhet=jäänittäminen=nervousness

**Comment by YSA-kokous** [comment]
KÄ jännittäminen
