### ISSUE TITLE
EU-direktiivit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6465]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

EU-direktiivit 

#### Ehdotettu termi ruotsiksi   

EU-direkti v

#### Ehdotettu termi englanniksi   

European Union directives 

#### Vaihtoehtoiset termit ja ilmaisut   

Europeiska unionens direktiv, Euroopan unionin direktiivit, EU:n direktiivit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[direktiivit](http://www.yso.fi/onto/yso/p10768) 

#### Assosiatiiviset (RT)   

[EU-oikeus](http://www.yso.fi/onto/yso/p20733) 

#### Vastaava käsite muussa sanastossa   

JUPO : EU:n direktiivit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Tarkempi termi kuin direktiivit, hakija voi olla kiinnostunut nimenomaan näistä, eikä mistä tahansa toimintaohjeista, suuntaviivoista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

EU ja käyrät kurkut : tosiasioita urbaanilegendojen sijaan / [teksti: Schuman-seuran työryhmä: Allan Rosas, Kimmo Elo, Anna Eskola, Tuomas Mikkola, Ilkka Nousiainen ja Ossi Tuusvuori] ; [toimittaja: Ossi Tuusvuori] ; [kuvitus: Mika Rantanen]. 

**Termiehdotus Fintossa:** [EU-direktiivit](http://finto.fi/yse/fi/page/Y506465)

**Comment by mirmaid** [comment]
_Direktiivit_ kyllä yleensä viittaa nimenomaan näihin EU-direktiiveihin, _toimintaohjeet_-termi löytyy myös sanastosta erikseen.

**Comment by mariaforsen** [comment]
Jos näin niin pitäisikö muuttaa päätermi selkeämmäksi? Nyt ei ole myöskään suhteita mihinkään EU-termeihin.

**Comment by YSA-kokous** [comment]
Seuraava kokous: EU-direktiivit?

**Comment by YSA-kokous** [comment]
EU-direktiivit KT direktiivit, EY-direktiivit

**Comment by mariaforsen** [comment]
Eli laitetaan (Melindassa) EU-direktiv/EU-direktiivit myös niille vanhoille aineistoille, joissa on käytetty "direktiivit", vaikka siihen aikaan ei ollut varsinaista EU:ta?
