### ISSUE TITLE
sovellettu matematiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6466]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sovellettu matematiikka 

#### Ehdotettu termi ruotsiksi   

tillämpad matematik 

#### Ehdotettu termi englanniksi   

applied mathematics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matematiikka](http://www.yso.fi/onto/yso/p3160) 

#### Vastaava käsite muussa sanastossa   

SAO : tillämpad matematik 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Sovellettu_matematiikka
https://en.wikipedia.org/wiki/Applied_mathematics 

#### Perustelut ehdotukselle   

Käytetty Melindassa (ainakin Allärs-terminä) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. CSC report on scientific computing 2001-2003 / [Sirpa] Kotila ... [ja muita] (eds.). 

**Termiehdotus Fintossa:** [sovellettu matematiikka](http://finto.fi/yse/fi/page/Y506466)

**Comment by mirmaid** [comment]
Käytetty Melindassa ysa-terminä 34 kertaa (+ muutamia ketjuja).
