### ISSUE TITLE
markkina-analyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6468]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

markkina-analyysi

#### Ehdotettu termi ruotsiksi   

marknadsanalys 

#### Ehdotettu termi englanniksi   

market analysis 

#### Ehdotettu yläkäsite YSOssa (LT)   

[analyysi](http://www.yso.fi/onto/yso/p6851) 

#### Assosiatiiviset (RT)   

[segmentointi](http://www.yso.fi/onto/yso/p18246) 

#### Vastaava käsite muussa sanastossa   

SAO : marknadsanalys 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Market_analysis 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Käytetty Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Market analysis of shipping MBA programs / Essi Kärpijoki ; Tehokas markkina-analyysi / Leila Lotti ; Fastighetsvärdering och marknadsanalys / Fredrik Brunes ;  Företagets omvärldsradar : omvärldsanalys och fläckiga ugglor / Hans Hedin, Björn Sandström. 

**Termiehdotus Fintossa:** [markkina-analyysi](http://finto.fi/yse/fi/page/Y506468)

**Comment by mirmaid** [comment]
Melindassa 6 kertaa ysa-terminä. KÄ _markkinatutkimus_?

**Comment by YSA-kokous** [comment]
KÄ markkinatutkimus?

**Comment by ilona-x** [comment]
https://sv.wikipedia.org/wiki/Marknadsanalys
https://sv.wikipedia.org/wiki/Marknadsunders%C3%B6kning

https://en.wikipedia.org/wiki/Market_analysis
https://en.wikipedia.org/wiki/Market_research

https://simplicable.com/new/market-analysis-vs-market-research

**Comment by ilona-x** [comment]
EuroVoc: markkina-analyysi KÄYTÄ **markkinatutkimus** http://eurovoc.europa.eu/895

**Comment by YSA-kokous** [comment]
KÄ markkinatutkimus
