### ISSUE TITLE
marknadsplanering

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6469]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

markkinointisuunnittelu 

#### Ehdotettu termi ruotsiksi   

marknadsplanering 

#### Ehdotettu termi englanniksi   

marketing planning? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[planering](http://www.yso.fi/onto/yso/p1377) 

#### Assosiatiiviset (RT)   

[marknadsföring](http://www.yso.fi/onto/yso/p5878) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Använd i Melinda. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Essential guide to marketing planning / Marian Burk Wood ; Marknadsplanen : praktisk handledning för marknadsplanerare / Andberg & Eliasson ; Marknadsföring i teori och praktik / Mats Magnusson, Håkan Forssblad. 

**Termiehdotus Fintossa:** [marknadsplanering](http://finto.fi/yse/fi/page/Y506469)

**Comment by mirmaid** [comment]
Myös https://github.com/Finto-ehdotus/YSE/issues/1305

**Comment by mirmaid** [comment]
_Markkinointisuunnittelu_ Melindassa ysa-terminä 6 kertaa. Yhdistelmää _markkinointi_ & _suunnittelu_ yli 2000 kertaa, ketjuna 308 kertaa.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by satuniininen** [comment]
Sanaliitto _markkinoinnin suunnittelu_ tuottaa Googlessa tuplasti enemmän osumia kuin  _markkinointisuunnittelu_ (joskin molemmissa osumat ovat pääasiassa työpaikkailmoituksia ja alan yritysten esittelyjä erilaisissa yrityshakemistoissa jne, eli melko köykäistä tavaraa).

Suomeksi tämä ei ole ehkä ihan yhtä vakiintunut omaksi käsitteekseen kuin ruotsiksi. Ihan käyttökelponen käsite kuitenkin ja sanastosta löytyy jo vastaavia, esim. _maaseudun suunnittelu._

**Comment by YSA-kokous** [comment]
markkinoinnin suunnittelu
