### ISSUE TITLE
organisationsstruktur

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6471]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

organisaatiorakenne 

#### Ehdotettu termi ruotsiksi   

organisationsstruktur 

#### Ehdotettu termi englanniksi   

organizational structure 

#### Ehdotettu yläkäsite YSOssa (LT)   

[struktur](http://www.yso.fi/onto/yso/p7302) 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Organizational_structure 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Förvaltning. Organisationsforskning. Offentlig förvaltning](http://www.yso.fi/onto/yso/p26524) 
[75 Ekonomi. Nationalekonomi. Företagsekonomi. Handel](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Använd i Melinda. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Intern kommunikation i multinationella företag : populära teman, nya aspekter och samband mellan dessa / Janine Saari ; Organization structures : theory and design, analysis and prescription / Helmy H. Baligh ; Merenkulkulaitoksen organisaatiouudistus : seurantatyöryhmän loppuraportti ; Rajavartiolaitoksen henkilöstön osallistuminen siviilikriisinhallintaan / Matias Kauppinen ; 

**Termiehdotus Fintossa:** [organisationsstruktur](http://finto.fi/yse/fi/page/Y506471)

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5909

**Comment by mirmaid** [comment]
LIITO-ontologiassa, 14 viitettä Melindassa.
