### ISSUE TITLE
halli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6473]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[halli](http://www.yso.fi/onto/ysa/Y101494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Päätermin muutos > halli (hylkeet) tai mahdollisesti harmaahylje 
Myös hallit > hallit (rakennukset)? 

#### Perustelut ehdotukselle   

Sana "halli" on monimerkityksinen. YSOssa ratkaistu yllä olevalla tavalla. Tässä tapauksessa monikkomuotokaan ei ole selkeä, koska "hallit" voi yhtä hyvin viitata useampaan rakennukseen kuin useampaan hylkeeseen.

**Comment by mirmaid** [comment]
Käytetty Melindassa kerran virheellisesti. Jos tällä viitattaisiin rakennuksiin, termi olisi monikossa, lisäksi ryhmä on eläintiede, yläkäsite hylkeet, mutta toki pieni virheen mahdollisuus jää.

**Comment by YSA-kokous** [comment]
halli (hylkeet)
