### ISSUE TITLE
tic-liikkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6474]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tic-liikkeet 

#### Ehdotettu termi ruotsiksi   

tics? 

#### Tarkoitusta täsmentävä selite   

Wikipedia: "Tic-liike eli hermovärve tarkoittaa nykimisoiretta tai lihasnyintää, joka esiintyy tahdosta riippumatta jatkuvasti toistuvina lyhyinä liikesarjoina etenkin kasvojen, kaulan ja hartioiden lihaksissa." 

#### Perustelut ehdotukselle   

Tarvitaan kirja-aineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Åsa-Caroline Salomonsson: Flörten 

**Termiehdotus Fintossa:** [tic-liikkeet](http://finto.fi/yse/fi/page/Y506474)

**Comment by ilona-x** [comment]
FinMeSH: tic-liikkeet KÄYTÄ nykimisoireet http://finto.fi/mesh/fi/page/D020323
LCSH: Tic disorders http://id.loc.gov/authorities/subjects/sh85135241

**Comment by mirmaid** [comment]
Lisäksi näköjään FinMeSHissä ja TEROssa on nykimishäiriöt.

**Comment by mariaforsen** [comment]
Sv. tick ET tics

**Comment by YSA-kokous** [comment]
nykimisoireet
