### ISSUE TITLE
modulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6475]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[modulaatio](http://www.yso.fi/onto/ysa/Y214576) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

modulaatio (musiikki) 

#### Perustelut ehdotukselle   

Modulaatio on monimerkityksinen termi ja Melindassa käytetty myös muissa merkityksissä. Ruotsiksi ja englanniksi lisätty tarkenteita.

**Comment by MUUSA-kokous** [comment]
Muutetaan muotoon "modulaatio (musiikki)".
