### ISSUE TITLE
soolo-osuudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6476]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soolo-osuudet 

#### Vaihtoehtoiset termit ja ilmaisut   

soolot 

#### Tarkoitusta täsmentävä selite   

Sävellykseen sisältyvä solistinen osuus yksittäiselle laulajalle tai soittajalle (ks. myös https://fi.wikipedia.org/wiki/Soolo) 

#### Perustelut ehdotukselle   

Nykyinen asiasana "soolot" (KT "soolosävellykset") kattaa ainoastaan yhdelle esittäjälle tehdyt teokset, joten soolo-osuuksien kuvailuun tarvitaan uusi asiasana (todettu Muusa-ryhmän kokouksessa 20.6.2018). – Onko tarvetta huomioida muiden alojen soolot (esim. tanssitaide)? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [soolo-osuudet](http://finto.fi/yse/fi/page/Y506476)

**Comment by MUUSA-kokous** [comment]
Muusan ehdotus: 
Luodaan YSAan ja SLM:ään uusi käsite "soolo-osuudet", tälle ohjaustermiksi "soolot (soolo-osuudet)". 
Muutetaan YSAan ja SLM:ään "soolot" käsitteen käytettävä termi muotoon "soolosävellykset", tälle ohjaustermiksi "soolot (soolosävellykset)".

**Comment by YSA-kokous** [comment]
– Onko tarvetta huomioida muiden alojen soolot (esim. tanssitaide)?

**Comment by mirmaid** [comment]
Melindassa soolot-termiä on käytetty myös tanssin yhteydessä, erityisesti tanssiarvosteluissa. Myös termiä soolo-osuudet voidaan käyttää tanssista puhuttaessa.

**Comment by YSA-kokous** [comment]
soolo-osuudet

**Comment by mariaforsen** [comment]
Sv.  solopartier
