### ISSUE TITLE
Kaugurmuižan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6481]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kaugurmuižan kartano 

#### Ehdotettu termi ruotsiksi   

Kaugurmuižan herrgård 

#### Ehdotettu termi englanniksi   

Kaugurmuiža Manor 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://lv.wikipedia.org/wiki/Kauguru_nemieri 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1537021 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Kaugurmuiža oli kartano Latviassa Kaugurin kunnassa. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Kaugurmuižan kartano](http://finto.fi/yse/fi/page/Y506481)

**Comment by mirmaid** [comment]
YSAssa on runsaasti kotimaisia kartanoita. Lisäksi on auktorisoitu kotimaisia ja joitakin ulkomaisia linnoja ja palatseja, luostareita, kirkkorakennuksia ja muita julkisia rakennuksia (myös merkittäviä ulkomaisia rakennuksia). 

Ehdotus: sovitaan näiden muuttamisesta yhteisöiksi toimijakuvailun kanssa. Toimijakuvailu päättää jatkossa rakennusten auktorisoinnista.

**Comment by mariaforsen** [comment]
Toivotaan että toimijakuvailu lisää myös ruotsinkielisiä muotoja.

**Comment by mirmaid** [comment]
Kerran Melindassa muodossa Kaugurmuiža

**Comment by mirmaid** [comment]
Ulkomaisia kartanoita ei auktorisoida YSAan.
