### ISSUE TITLE
Klaipeda

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6483]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Klaipeda](http://www.yso.fi/onto/ysa/Y110147) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Katso myös -kenttään 451 voisi laittaa Memel'in. 

#### Perustelut ehdotukselle   

Memel olii pitkään käytössä ennen kuin nimimuodoksi vakiintui Klaipėda. Kaupungin nimi on edelleenkin saksaksi no. Memel. Helkassa on vielä nytkin kaksi tietuetta, joissa YSAn 651-kentässä on Klaipedan tilalla Memel. Poistan Memelit. 

#### Ehdottajan organisaatio   

HY:n pääkirjasto

**Comment by mirmaid** [comment]
Ohjaustermi lisätty.
