### ISSUE TITLE
Kansainyhteisö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6487]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kansainyhteisö 

#### Ehdotettu termi ruotsiksi   

Samväldet 

#### Ehdotettu termi englanniksi   

Commonwealth 

#### Vaihtoehtoiset termit ja ilmaisut   

Brittiläinen kansainyhteisö 
Commonwealth of Nations 
Brittiska samväldet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansainväliset järjestöt](http://www.yso.fi/onto/yso/p17837) 

#### Vastaava käsite muussa sanastossa   

Commonwealth countries : <http://id.loc.gov/authorities/subjects/sh85029004> 

#### Perustelut ehdotukselle   

Käytetty ysa-terminä Melindassa, yli 200 osumaa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Tarkoitusta täsmentävä selite   

Britannian ja sen entisten alusmaiden ja territorioiden muodostama yhteisö 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The empire project : the rise and fall of the British world-system, 1830-1970 / John Darwin. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Kansainyhteisö](http://finto.fi/yse/fi/page/Y506487)

**Comment by mariaforsen** [comment]
SAO: Brittiska samväldet ET Engelska samväldet, Samväldesländerna, mutta jos viitataan nykytilanteeseen niin Samväldet

**Comment by YSA-kokous** [comment]
Yhteisö?

**Comment by mirmaid** [comment]
Lisätään Suomalaiset yhteisönimet -sanastoon http://finto.fi/cn/fi/
