### ISSUE TITLE
tieteiskirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6488]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tieteiskirjallisuus](http://www.yso.fi/onto/ysa/Y99504) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Nykyisin käytössä vain tieteiskirjallisuus, -elokuvat ja -sarjat. Scifi käsitteenä sisältäisi kuitenkin esim roolipelit, lautapelit, konsolipelit yms joissa noita ei voida nyt käyttää 

#### Ehdotettu muutos   

scifi ohjaustermistä varsinaiseksi termiksi 

#### Ehdottajan organisaatio   

Helsingin kaupunginkirjasto

**Comment by mirmaid** [comment]
Tämä muutos koskisi varmaankin myös Kaunokkia ja SLM-sanastoa. Ajatus on ollut esillä aikaisemminkin.

**Comment by YSA-kokous** [comment]
Kaunokki

**Comment by mirmaid** [comment]
Ehdotettu vaihtoehtoisesti termiä _scifipelit_ (_scifi-pelit, science fiction -pelit_) pelien kuvailuun.

**Comment by mirmaid** [comment]
scifipelit/SLM

**Comment by mariaforsen** [comment]
Sv. science fiction-spel ET scifispel
