### ISSUE TITLE
johdannaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6491]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

johdannaiset 

#### Ehdotettu termi englanniksi   

derivatives 

#### Ehdotettu termi ruotsiksi   

derivat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Ysossa on johdannaismarkkinat. Kun on tarpeen käsitellä johdannaisia tarkemmin, tarvittaisiin termi "johdannaiset" (on vakiintunut ja yleinen). 

#### Tarkoitusta täsmentävä selite   

Tilastokeskusken sivuilla: "Johdannaiset ovat rahoitusinstrumentteja, joiden hinta määräytyy jonkin toisen hyödykkeen arvon perusteella." 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Talousaineisto (rahoitusmarkkinat) 

**Termiehdotus Fintossa:** [johdannaiset](http://finto.fi/yse/fi/page/Y506491)

**Comment by mirmaid** [comment]
Jos otetaan, vaatii tarkenteen.

**Comment by mariaforsen** [comment]
Sv. derivat (ekonomi) ET derivatinstrument

**Comment by YSA-kokous** [comment]
+ tarkenne

**Comment by mirmaid** [comment]
johdannaiset (arvopaperit) KT johdannaissopimukset (voisi olla myös toisin päin)
LT arvopaperit
ST optiot, termiinit
RT johdannaismarkkinat

**Comment by YSA-kokous** [comment]
johdannaiset (arvopaperit)
