### ISSUE TITLE
konstruktivismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6493]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[konstruktivismi](http://www.yso.fi/onto/ysa/Y96318) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko:
konstruktivismi (tyylit)
konstruktivismi (filosofia)
konstruktivistinen opetus / konstruktivistinen oppimisteoria / konstruktivismi (oppimisteoria) 

#### Perustelut ehdotukselle   

Monimerkityksinen termi, käytetty useassa eri merkityksessä. 
YSO-issue #920

**Comment by ilona-x** [comment]
http://id.loc.gov/search/?q=cs:http://id.loc.gov/authorities/subjects&q=constructivism

**Comment by mariaforsen** [comment]
Myös SAOssa jaettu:
Konstruktivism (filosofi)
Konstruktiv matematik 
Konstruktivism (pedagogik)
Konstruktivism (psykologi)
Konstruktivism (konst) 
Konstruktivism (arkitektur)
Mutta YSOn aikaisempien ratkaisujen perusteella voisi varmaan yhdistää ainakin arkkitehtuuri ja taide (tyylit?)

**Comment by mirmaid** [comment]
Wikipediassa _konstruktivismi (taide)_ sisältää myös arkkitehtuurin, mutta jos pelätään sillä tarkenteella rajautuvan kuvataiteeseen, myös _(tyyli)_ varmasti sopii tähän. Tämä kokonaisuus erottuu selkeimmin muusta.

Psykologia ja kasvatustiede liittyvät läheisesti toisiinsa, mutta voi olla hankala yhdistää. Toisaalta myös filosofia tulee hyvin lähelle näitä.

**Comment by AuHo22** [comment]
Kannatan konstruktivismi (taide)/(taiteet) vs. (tyylit)

**Comment by mirmaid** [comment]
> Kannatan konstruktivismi (taide)/(taiteet) vs. (tyylit)

Eli mieluummin tarkenteeksi (taide) kuin (tyylit)? Ja se sisältäisi myös arkkitehtuurin?

**Comment by YSO-kokous** [comment]
Hyväksytään konstruktivismi (taide)

**Comment by mirmaid** [comment]
Viitteistä vain melko pieni osa taidetta ja arkkitehtuuria, helposti erotettavia settejä siivottu pois.

**Comment by mirmaid** [comment]
Jatketaanko > konstruktivismi (pedagogiikka)?
https://en.wikipedia.org/wiki/Constructivism_(philosophy_of_education)#Social_constructivism
https://fi.wikipedia.org/wiki/Konstruktivismi_(oppimisteoria)
https://sv.wikipedia.org/wiki/Konstruktivism_(pedagogik)

**Comment by YSO-kokous** [comment]
### Päätökset
siivotaan seuraavaksi konstruktivisimi --> konstruktivismi (pedagogiikka)

**Comment by mirmaid** [comment]
1316/Melinda

**Comment by mirmaid** [comment]
Jäljellä 588. Mitä seuraavaksi?

**Comment by mariaforsen** [comment]
Pitäisikö lisätä vielä ainakin:
konstruktivism (filosofi)
konstruktivism (psykologi)

Näyttää olevan aineistoa Melindassa. Nämä (ja vielä muitakin) myös LCSH:ssa ja SAOssa.

**Comment by mirmaid** [comment]
Nämä on kyllä harmillisen päällekkäisiä silloin kun ei puhuta taiteesta, eikä yhtä hiuksenhienoon (ketjumaiseen) jaotteluun varmaan kuitenkaan haluta mennä kuin LCSH:ssa tai wikipediassa. En tiedä toimisiko joku _konstruktivismi (yhteiskuntatieteet)_. Filosofia varmaan on erotettavissa, tuo psykologia on todella päällekkäinen pedagogiikan ja sosiaalisen konstruktivismin kanssa.

**Comment by YSO-kokous** [comment]
#### Päätös
Lisätään käsite konstruktivismi (filosofia)

**Comment by mirmaid** [comment]
Kävin tätä jonkun verran läpi, melkein tuntuu että jakopäätös oli kyllä virhe. Mutta ehkä sitten konstruktivismi (psykologia) myös, vaikka nämä alkaa olla melkoista ketjutusta. Tuntuu hankalalta käyttää (filosofia)-tarkennetta yhtä reippaalla otteella kuin sitä esim. englanninkielisessä maailmassa ilmeisesti sovelletaan...😟

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _konstruktivismi (psykologia)_.

**Comment by mariaforsen** [comment]
Sv. konstruktivism (psykologi)

**Comment by mirmaid** [comment]
Tämän voisi varmaan poistaa - vaikka jako on osittain hyvin ongelmallinen, en ainakaan haluaisi näitä yhtään enempää. Konstruktivismi (taide) -käsitteessä voisi ehkä jotenkin (ainakin huomautuksella) huomioida myös konstruktivismin venäläisessä kirjallisuudessa.

Sosiaalisessa konstruktivismissa voisi olla konstruktivismi-alkuinen ohjaustermi, konstruktivismi (sosiaalinen) tms.

Lähes kaikki viitteet on jo Melindassa korjattu.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
konstruktivismi (kirjallisuus) KÄYTÄ konstruktivismi (taide)
konstruktivismi (sosiaalinen) KÄYTÄ sosiaalinen konstruktivismi

**Comment by mariaforsen** [comment]
Varmaan termi konstruktivismi poistuu?
