### ISSUE TITLE
saumat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6495]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[saumat](http://www.yso.fi/onto/ysa/Y104288) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko? 
saumat ja liitokset? (sv. fogar)
saumat (tekstiili) (sv. sömmar) 

#### Perustelut ehdotukselle   

Monimerkityksinen, ks. MOT. 
YSO-issue https://github.com/NatLibFi/Finto-data/issues/864

**Comment by satuniininen** [comment]
Tietueet pääasiassa rakentamista/remontointia ja tekstiilityötä. 

Muita käyttötapauksia löytyi vain hammaslääketieteen väitöskirja _Leakage and permeability control in dentistry : the key for success_. _Saumat ja liitokset_ varmaankin sopisi tähän muuten, mutta allärs-terminä on _sömmar_ eikä _fogar_.

Voidaan myös yrittää kiertää kuvailussa esim. _hammasimplantit + kiinnitys + tiiviys_

**Comment by mirmaid** [comment]
Eli ehdotettu:
- saumat (tekstiilit) [ysa 26]
- saumat ja liitokset [ysa 28, 34, 37]

**Comment by YSA-kokous** [comment]
saumat (tekstiilit)
Tutkitaan vielä saumat ja liitokset, seuraava kokous

**Comment by ilona-x** [comment]
saumat (tekstiilit) korjattu Melindaan 

Pitäisikö myös **saumaus** jakaa kahtia, kun silläkin näyttää olevan 2 ruotsivastinetta fogning & fållning?

**Comment by mirmaid** [comment]
_Fållning_ näyttäisi olevan ohjaustermi (?), mutta jos se liittyy ompeluun, tässä on kyllä ongelma. Itselleni _saumaus_-muoto ei kuulosta käsityö-yhteyteen sopivalta, mutta @satuniininen osaa varmaan sanoa paremmin miten on. Ryhmänä on kyllä myös 26. Tosin eikö siihen riittäisi _saumat (tekstiilit)_?

**Comment by mirmaid** [comment]
Pelkkä saumat KÄ _liitokset_ olisi yksi mahdollisuus, mutta sopii huonosti esim. laattojen saumoista ym. kosteiden tilojen saumoista. Varmistan nyt vielä että nämä ovat siis ruotsiksi myös _fogar_?

**Comment by ilona-x** [comment]
Vaihtoehtoina siis:
**saumat ja liitokset**
tai 
saumat KÄ **liitokset**

Melindan tutkimisen jälkeen kannattaisin näistä vaihtoehdoista edelleen yhdistelmätermiä "saumat ja liitokset" sv. fogar. 

lisäksi YSAssa:
**saumaus** sv. fogning 
**liittäminen** sv. sammanfogning

Melindassa: 
saumat 154
liitokset 897
molemmat 30

Kielitoimiston sanakirja:

**liitos**
kohta jossa t. tapa jolla jnk kokonaisuuden osat on liitetty t. liittyvät yhteen, liittymäkohta, **sauma**. Liimattu, hitsattu liitos. Vesijohdon, ratakiskojen liitokset. Pontti, sinkkaus ym. puuliitokset. Aueta liitoksistaan. 

**sauma**
1. kahden reunan **liitos(kohta)**.
a. kankaiden, nahkojen, muovien, levyjen yms. **liitoksista**. Takin, kenkien saumat. Koneella ommeltu sauma. Edestakais-, katesauma. Peltikaton saumat. Hitsi-, kuuma-, valusauma. Ratketa, irrota saumoistaan.
b. rakenneosien välinen rako (joka us. täytetään tiivistys- t. sideaineella). Sillan liikuntasaumat. Rakennuslevyjen saumat. Saumoistaan vuotava vene. Saumojen paikkaaminen, tiivistäminen.

**Comment by mariaforsen** [comment]
Kyllä, fogar on yleisin termi sillekin (skarvar toinen mahdollinen). Eli fogar=saumat ja liitokset tms. olisi hyvä.

**Comment by YSA-kokous** [comment]
saumat ja liitokset

**Comment by mirmaid** [comment]
_Saumaus_: tarvitaanko tarkenne? Saumauskoneet (tekstiilikoneet) KÄ saumurit.

**Comment by YSO-kokous** [comment]
Ei muutoksia.
