### ISSUE TITLE
sosiaalisen valinnan teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6499]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sosiaalisen valinnan teoria 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Tarkoitusta täsmentävä selite   

Arrow’n merkittävin taloustieteellinen tutkimus liittyy sosiaaliseen valintateoriaan ja yleiseen taloudelliseen tasapainoteoriaan.[3] Arrow’n tutkimukset ovat vaikuttaneet merkittävästi myös informaation taloustieteen ja endogeenisen talouskasvun teorian kehitykseen. https://fi.wikipedia.org/wiki/Kenneth_Arrow 

#### Perustelut ehdotukselle   

Asiaa hankala muuten täsmällisesti ilmaista 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ajatus : Suomen Filosofisen Yhdistyksen vuosikirja; 74; tässä yksi artikkeli 

**Ehdottajan organisaatio:** Outi Hintikka, BTJ **Termiehdotus Fintossa:** [sosiaalisen valinnan teoria](http://finto.fi/yse/fi/page/Y506499)

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. social choice theory?  teorin om kollektiva val? ET kollektiva val, public choice, social choice?

http://lup.lub.lu.se/luur/download?func=downloadFile&recordOId=1553968&fileOId=1647197

**Comment by ilona-x** [comment]
LCSH: Social choice?  http://id.loc.gov/authorities/subjects/sh85123920.html
SAO: Teorin om kollektiva val?

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Julkisen_valinnan_teoria

**Comment by YSA-kokous** [comment]
julkisen valinnan teoria

**Comment by mariaforsen** [comment]
Sv. public choice ET public choice-skolan, politikens ekonomiska teori, teorin om kollektiva val
