### ISSUE TITLE
osittainen hoitoraha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6500]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

osittainen hoitoraha 

#### Tarkoitusta täsmentävä selite   

Kotihoidontukea, yksityisen hoidon tukea ja osittaista hoitorahaa kutsutaan yhteisnimityksellä lastenhoidon tuet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10138/38606 

#### Perustelut ehdotukselle   

Kotihoidontuki ja yksityisen hoidon tuki löytyvät, tämä puuttuu. 

**Termiehdotus Fintossa:** [osittainen hoitoraha](http://finto.fi/yse/fi/page/Y506500)

**Comment by mariaforsen** [comment]
Sv. partiell vårdpenning
