### ISSUE TITLE
välirauha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6503]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[välirauha](http://www.yso.fi/onto/ysa/Y100349) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö määritelmä? 

#### Perustelut ehdotukselle   

Välirauha voi tarkoittaa (Kielitoimiston s.):  
1. väliaikainen rauha ennen lopullisen rauhan solmimista. 
2. talvi- ja jatkosodan välinen kausi. 

Nyt ei ole määritelmää tms., joka kertoisi mihin tämä viittaa. Ruotsiksi eri termejä eri merkityksille.

**Comment by jtuohini** [comment]
Olisi varmaan parempi pitää yleiskäsitteenä? Minkä maan/maiden välirauhasta ja milloin on kuvailussa kyse, voidaan ilmaista muillakin keinoin. Vastaavia tältä osin ovat asiasanat _rauhanaika_, _sota-aika_, _vuosisadan vaihde_, _vuosituhannen vaihde_.

**Comment by mariaforsen** [comment]
Allärs tähän asti: tiden efter Moskvafreden.

**Comment by mirmaid** [comment]
^ Ja suomeksikin lähes yksinomaan siinä merkityksessä käytetty.

**Comment by EsaMPKK** [comment]
...ja muihin käyttöyhteyksiin sopii aselepo.

**Comment by YSA-kokous** [comment]
Lisätään määritelmä.
