### ISSUE TITLE
tikarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6505]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tikarit 

#### Ehdotettu termi englanniksi   

daggers 

#### Ehdotettu termi ruotsiksi   

dolkar 

#### Ehdotettu yläkäsite YSOssa (LT)   

[teräaseet](http://www.yso.fi/onto/yso/p19125) 

#### Vastaava käsite muussa sanastossa   

daggers : <http://id.loc.gov/authorities/subjects/sh85035397> 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Die Kunst der Waffen : Der mittelalterliche Dolch 

**Ehdottajan organisaatio:** Kansalliskirjasto / Satu Niininen **Termiehdotus Fintossa:** [tikarit](http://finto.fi/yse/fi/page/Y506505)

**Comment by mariaforsen** [comment]
Sv. dolkar ET stickertar
