### ISSUE TITLE
kokoukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6507]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kokoukset](http://www.yso.fi/onto/ysa/Y96279) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korvattu termi konferenssit päätermiksi? 

#### Perustelut ehdotukselle   

Allärs: konferenser + möten = kokoukset
Molemmat termit tärkeät ruotsiksi, eikä möte ole sama kuin konferens. 
Wikipedia: "Konferenssi on tapahtuma, joka on yleensä järjestetty koulutusta, kollegoiden tapaamista tai valikoidusta liiketoiminta-aiheesta keskustelemista varten." https://fi.wikipedia.org/wiki/Konferenssi
Kielitoimiston s. konferenssi: (kansainvälinen) kokous, neuvottelu, kongressi. Geneven konferenssi. 
SAO: konferenser (linkitetty LCSH Congresses and conventions)
SAOL: större samman­komst för över­läggningar och informations­utbyte NE: sammankomst för formell diskussion av vissa sakfrågor; ofta som förberedelse inför fortsatt behandling, spec. om större sammankomst med föredrag i bestämda ämnen

**Comment by YSA-kokous** [comment]
Konferenssit (KT kokoukset (konferenssit))
