### ISSUE TITLE
musiikkiarkeologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6509]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

musiikkiarkeologia 

#### Ehdotettu termi ruotsiksi   

musikarkeologi 

#### Ehdotettu termi englanniksi   

music archaeology 

#### Vaihtoehtoiset termit ja ilmaisut   

arkeomusikologia 

#### Ehdotettu yläkäsite YSOssa (LT)   

[arkeologia](http://www.yso.fi/onto/yso/p1265) 
[musiikintutkimus](http://www.yso.fi/onto/yso/p21685) 

#### Assosiatiiviset (RT)   

[soitintutkimus](http://www.yso.fi/onto/yso/p35531) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh86001404> 
Wikidata : https://www.wikidata.org/wiki/Q3621488 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2219689 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [musiikkiarkeologia](http://finto.fi/yse/fi/page/Y506509)

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa käsitteen ottamista YSAan yllä mainituilla spekseillä.
