### ISSUE TITLE
integroitu opetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6511]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[integroitu opetus](http://www.yso.fi/onto/ysa/Y106732) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö tarkentaa? 

#### Perustelut ehdotukselle   

Nyt käytetään useammantyyppisestä integroinnista, voiko tulkita väljästi vai rajataanko? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Voi tarkoittaa oppilas/opiskelijaryhmien integroimista, esim. erityistä tukea tarvitsevat oppilaat tai jokin muu erityisryhmä mukana perusopetuksen luokassa (tai jopa avoimen korkeakoulun opiskelijat mukana tutkinto-opetuksessa), tai eri oppiaineiden yhdistämistä opetuksessa.

_Integroitu opetus tarkoittaa sitä, että kunnallista peruskoulua käyville saamelaisoppilaille annetaan joissakin oppiaineissa muutama oppitunti saamen kielen ja kulttuurin opetusta. Opetuksen antaminen merkitsee saamelaiskulttuurin opetuksen tukemista muuallakin kuin saamelaiskouluissa._ http://senc.hum.helsinki.fi/wiki/Integroitu_opetus

_...tietotekniikkaa yritettiin 1990-luvulla opettaa muiden aineiden yhteydessä. Integroitu opetus epäonnistui, koska vastuu tietotekniikan opetuksesta oli jaettu koulun kaikkien opettajien kesken eli vastuussa ei ollut kukaan._ https://www.tieke.fi/pages/viewpage.action?pageId=33685847

**Comment by mariaforsen** [comment]
Aika vaikea rajata, se vaatisi varmaan sulkutarkenteenkin, tai se pitäisi oikeastaan jakaa. En kannata.

**Comment by YSA-kokous** [comment]
oppiaineintegraatio (?)

**Comment by mariaforsen** [comment]
Sv. ämnesintegration?

**Comment by mirmaid** [comment]
Oppiaineintegraatio esim. https://helda.helsinki.fi/handle/10138/318126

**Comment by mirmaid** [comment]
integroitu opetus (opetusryhmät)
integroitu opetus (oppiaineet)

**Comment by YSO-kokous** [comment]
#### Päätös
Tehdään Mirjan ehdotuksen mukaisesti:
integroitu opetus (opetusryhmät)
integroitu opetus (oppiaineet)

**Comment by mariaforsen** [comment]
Sv. 
-integrerad undervisning (undervisningsgrupper)
-integrerad undervisning (läroämnen)
