### ISSUE TITLE
Maailmanopettaja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6512]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Maailmanopettaja 

#### Ehdotettu termi ruotsiksi   

Världslärare 

#### Ehdotettu termi englanniksi   

World Teacher 

#### Ehdotettu yläkäsite YSOssa (LT)   

[teosofia](http://www.yso.fi/onto/yso/p10026) 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/Maitreya_(buddhalaisuus) 
https://fi.wikipedia.org/wiki/Maitreya_(henkil%C3%B6) 
https://en.wikipedia.org/wiki/Maitreya 
<http://theosophy.ph/encyclo/index.php?title=World_Teacher> 

#### Tarkoitusta täsmentävä selite   

Teosofisessa katsannossa Maailmanopettaja on uskontojen ulkopuolelta tuleva hahmo, joka toimii uuden aikakauden opettajana koko ihmiskunnalle. 

#### Perustelut ehdotukselle   

Suomeksi on julkaistu ainakin vuodesta 1928 pitäen kirjoja, jotka käsittelevät joko yksinomaan taikka osittain Maailmanopettajaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjavälitykseen viety uutuuskirjan asiasanat 

**Ehdottajan organisaatio:** Kirjan kustantaja **Termiehdotus Fintossa:** [Maailmanopettaja](http://finto.fi/yse/fi/page/Y506512)

**Comment by YSA-kokous** [comment]
Seuraava: Tuomas ja Maria laativat määritelmän.

**Comment by YSA-kokous** [comment]
maailmanopettaja
