### ISSUE TITLE
akanin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6514]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

akanin kieli 

#### Perustelut ehdotukselle   

Aineistoa on. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Me Tumi Kenkan  / Francis Abeku Arthur, Martha Ackom 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [akanin kieli](http://finto.fi/yse/fi/page/Y506514)

**Comment by mariaforsen** [comment]
Sv. akan (språk)
