### ISSUE TITLE
twin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6515]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

twin kieli 

#### Perustelut ehdotukselle   

Aineistoa on. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kwesi's family    / Tosin Coker 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [twin kieli](http://finto.fi/yse/fi/page/Y506515)

**Comment by mirmaid** [comment]
Sama kuin akanin kieli?

**Comment by mariaforsen** [comment]
Sv. twi (språk)

**Comment by ilona-x** [comment]
Molemmilla kielillä näyttäisi olevan omat kielikoodit.
https://en.wikipedia.org/wiki/Twi
https://en.wikipedia.org/wiki/Akan_language
