### ISSUE TITLE
vertaileva psykologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6516]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vertaileva psykologia 

#### Ehdotettu termi ruotsiksi   

jämförande psykologi 

#### Ehdotettu termi englanniksi   

Psychology, Comparative 

#### Ehdotettu yläkäsite YSOssa (LT)   

[psykologia](http://www.yso.fi/onto/yso/p1632) 

#### Vastaava käsite muussa sanastossa   

MeSH/FinMeSH : <http://www.yso.fi/onto/mesh/D011587> 
LSCH : Psychology, Comparative 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Perustelut ehdotukselle   

Tarve käyttää sisällönkuvailussa. Käytetty sis. kuvailussa Melindassa jo ks. https://melinda.kansalliskirjasto.fi/F/EGABG2BEYIIMCU58UH59R2FLMK83QR2BC3FRVH8ACJ9R2D947E-13521?func=short 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The gap : the science of what separates us from other animals / Thomas Suddendorf. 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [vertaileva psykologia](http://finto.fi/yse/fi/page/Y506516)

**Comment by mirmaid** [comment]
6 viitettä Melindassa. Suomeksi erittäin vähän tuloksia Googlella?

**Comment by mariaforsen** [comment]
SAO: Jämförande psykologi ET komparativ psykologi

**Comment by YSA-kokous** [comment]
Tarkistetaan vielä
