### ISSUE TITLE
tabla

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6517]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tabla 

#### Ehdotettu termi ruotsiksi   

tabla 

#### Ehdotettu termi englanniksi   

tabla 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rummut](http://www.yso.fi/onto/yso/p19062) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85131789> 
Wikidata : https://www.wikidata.org/wiki/Q213100 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3010960 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [tabla](http://finto.fi/yse/fi/page/Y506517)

**Comment by asormune** [comment]
SEKOssa termi on kirjoitettu: tablā

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa käsitteen ottamista YSAan muodossa "tabla". Ohjaustermiksi "tablā".
