### ISSUE TITLE
panseksuaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6518]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

panseksuaalisuus 

#### Tarkoitusta täsmentävä selite   

Setan sateenkaarisanasto määrittelee sen näin: Panseksuaali eli panseksuaalinen ihminen tuntee seksuaalista tai/ja emotionaalista vetoa kaikkia sukupuolia olevia ihmisiä kohtaan. Kiinnostuksen kohteen sukupuolella ei ole heille merkitystä. Monet panseksuaalit kokevat, että termi vapauttaa luokittelemasta seksuaalisen kiinnostuksen kohteita sukupuolen mukaan. Termit panseksuaalisuus ja biseksuaalisuus ovat osittain päällekkäisiä. https://seta.fi/sateenkaarisanasto/ 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [panseksuaalisuus](http://finto.fi/yse/fi/page/Y506518)

**Comment by mariaforsen** [comment]
Sv. pansexualitet
