### ISSUE TITLE
kirjatyöntekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6520]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjatyöntekijät 

#### Vaihtoehtoiset termit ja ilmaisut   

kirjaltajat 

#### Perustelut ehdotukselle   

Molempia käytetty kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [kirjatyöntekijät](http://finto.fi/yse/fi/page/Y506520)

**Comment by mirmaid** [comment]
Melindassa 64 kertaa kirjatyöntekijät, 8 kertaa kirjaltajat.

**Comment by mariaforsen** [comment]
Sv. bokarbetare ET typografer
