### ISSUE TITLE
Pohjola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6523]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pohjola](http://www.yso.fi/onto/ysa/Y127164) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan tai tarkennetaan 

#### Perustelut ehdotukselle   

Allärsissa Norden, myös Pohjoismaat = Norden. Sanastossa myös Pohjois-Eurooppa. Tarvitaanko tätä, ja mihin tarkalleen viittaa?

**Comment by jtuohini** [comment]
Toisaalta pitäisi myös miettiä käsitteen _Skandinavia_ ottamista omaksi asiasanakseen. Nyt se on KT-muoto asiasanalle **Pohjoismaat**, vaikka Pohjoismaat on ennemmin _Fennoskandia_ – jota ei koko sanastossa ole edes KT-muotona! On paljonkin aineistoa, joka käsittelee nimenomaan Skandinaviaa; toki niissä tapauksessa voidaan kuvailla käyttämällä täsmällisiä valtioiden nimiä ja jättää maantieteellinen kokonaisuus kokonaan ilmaisematta.

**Comment by mariaforsen** [comment]
Kielitoimiston sanakirja:
 1. pohjoiset seudut; vrt. pohjoinen
2. vars. erisn.
a. = Pohjoismaat; ks. pohjoismaa. Pohjolan sotilasstrateginen asema.
b. paikannimi Kalevalassa. Louhi, Pohjolan emäntä. 

Eli ei voi viitata 2a-merkitykseen, eikä varmaan ole 2b, ja 1 on liian epämääräinen.

**Comment by mirmaid** [comment]
Onko haittaa, jos tämä poistetaan ja käytettäväksi jää vain _Pohjois-Eurooppa_ ja _Pohjoismaat_?

**Comment by mirmaid** [comment]
Käytetty Melindassa 241 kertaa, usein epämääräinen pohjoinen alue, tai kun kyseessä on varhaisempi historia (_Pohjoismaat_ tuntuisi anakronistiselta?). Onko korvattavissa muilla maantieteellisillä termeillä?

**Comment by ilona-x** [comment]
Melindan tutkimisen jälkeen vaikuttaisi siltä, että Pohjolan korvaaminen muilla termeillä onnistuu. Monissa tapauksissa Pohjola-termiä on käytetty silloin, kun se on esiintynyt teoksen nimekkeessä.

**Comment by YSA-kokous** [comment]
Poistetaan, korvataan kuvailussa sopivalla termillä. Ei ohjaustermiksi.
