### ISSUE TITLE
Arvidsjaurin kunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6524]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Arvidsjaurin kunta 

#### Ehdotettu termi ruotsiksi   

Arvidsjaurs kommun 

#### Ehdotettu termi englanniksi   

Arvidsjaur Municipality 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n2002124549> 
Wikidata : https://www.wikidata.org/wiki/Q499404 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Kunta Pohjoispohjan läänissä (ei tule sekoittaa kunnassa olevaan samannimiseen kylään). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1036957 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Arvidsjaurin kunta](http://finto.fi/yse/fi/page/Y506524)

**Comment by mirmaid** [comment]
Nykyinen kunta ja taajama samassa kunnassa, https://fi.wikipedia.org/wiki/Arvidsjaurin_kunta, https://fi.wikipedia.org/wiki/Arvidsjaur.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa Arvidsjaur. Sanastossa ei ole yleensä eroteltu kuntaa ja siihen sisältyvää samannimistä kylää.
