### ISSUE TITLE
pähkinäpensaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6525]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pähkinäpensaat 

#### Vaihtoehtoiset termit ja ilmaisut   

Corylus 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

**Termiehdotus Fintossa:** [pähkinäpensaat](http://finto.fi/yse/fi/page/Y506525)

**Comment by mariaforsen** [comment]
Sv. hasslar (släkte) ET hasselsläktet
