### ISSUE TITLE
euroopanpähkinäpensas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6526]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

euroopanpähkinäpensas 

#### Vaihtoehtoiset termit ja ilmaisut   

pähkinäpensas (laji) 
Corylus Avellana 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [euroopanpähkinäpensas](http://finto.fi/yse/fi/page/Y506526)

**Comment by mariaforsen** [comment]
Sv. hassel ET vanlig hassel

**Comment by PaiviLipsanen** [comment]
Laji.fi:
koivukasvit (heimo-Betulaceae)
- koivut (suku-Betula), nyt YSAssa koivu
  - hieskoivu (Betula pubescens )
  - rauduskoivu (Betula pendula)
  - vaivaiskoivu (Betula nana)
- lepät (suku-Alnus), nyt YSAssa leppä
  - harmaaleppä (Alnus incana)
  - tervaleppä (Alnus glutinosa
- pähkinäpensaat (suku-Corylus)
  - euroopanpähkinäpensas (laji-Corylus avellana)
https://laji.fi/taxon/MX.37991
