### ISSUE TITLE
leppä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6527]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leppä](http://www.yso.fi/onto/ysa/Y103105) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Monikkoon, koska kyseessä on suku (ST harmaaleppä, tervaleppä) 

#### Perustelut ehdotukselle   

-

**Comment by mariaforsen** [comment]
Sv. alar
