### ISSUE TITLE
kuuset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6529]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuuset 

#### Vaihtoehtoiset termit ja ilmaisut   

Picea 

#### Perustelut ehdotukselle   

Kasvisuku puuttuu sanastosta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [kuuset](http://finto.fi/yse/fi/page/Y506529)

**Comment by mariaforsen** [comment]
sv. granar (släkte), gransläktet

**Comment by YSA-kokous** [comment]
KT suomukuuset
