### ISSUE TITLE
inho

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#653]
#### Ehdotettu termi suomeksi

inho
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)

**Luontipäivämäärä:** 12.09.2001

**Muokkauspäivämäärä:** 12.9.2001, 16.12.2008

**Voyager-id:** 115161

**Termiehdotus Fintossa:** [inho](http://finto.fi/yse/fi/page/Y315161)

**Comment by henriyli** [comment]
YSAan 29.11.2004, http://www.yso.fi/onto/ysa/Y134643
