### ISSUE TITLE
tilhi (laji)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6530]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tilhi (laji) 

#### Vaihtoehtoiset termit ja ilmaisut   

Bombycilla garrulus 

#### Perustelut ehdotukselle   

YSAssa nyt tilhet, joka on sekä suvun että heimon nimi. Aineistot käsittelevät täkäläistä tilheä, joten yksikkö on luontevin ja vapaan indeksoinnin terminä sitä on myös käytetty. Tilhet voisi muuttaa kuten vastaava peipot, eli sulkutarkenteella (heimo). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [tilhi (laji)](http://finto.fi/yse/fi/page/Y506530)

**Comment by mirmaid** [comment]
Samoin voisi tehdä myös rautiainen/rautiaiset.

**Comment by mirmaid** [comment]
Vaihtoehtoisesti mahdollista jättää sanastoon pelkkä yksikkö.

**Comment by mirmaid** [comment]
Tähän samaan vielä _leppälintu_: YSAssa on sekä yksikkö, että monikko (olisi suku Phoenicurus, laji.fi:ssä ei suomenk. nimeä suvulle, wikipediassa leppälinnut). Käytetty vain kerran monikossa, silloinkin aiheena on leppälintu-laji. Joko siis tarkenteet (suku) ja (laji), tai poistetaan monikko ja otetaan sen sijaan yksikkö.

**Comment by jarmosaarikko** [comment]
leppälinnut-suvusta on havaittu säännöllisesti kahta lajia Suomessa leppälintu ja mustaleppälintu.

laji.fi:ssä  on tilhet on heimo  _Bombycillidae_ , jossa on yksi suku _Bombycilla_, jossa kolme lajia
AFO:ssa  on suku ja laji:
- tilhet  http://www.yso.fi/onto/afo/p3898 
- tilhi Bombycilla garrulus http://www.yso.fi/onto/afo/p5507

Ehdotus lisätään AFO:n mukaan ilman sulkutarkennetta: tilhi KT Bombycilla garrulus LT tilhet

**Comment by mariaforsen** [comment]
Sv. sidensvans (även sidensvansar>?)
