### ISSUE TITLE
marssilaulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6531]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

marssilaulut 

#### Ehdotettu termi englanniksi   

marching songs 

#### Ehdotettu termi ruotsiksi   

marschsånger 

#### Ehdotettu yläkäsite YSOssa (LT)   

[laulut](http://www.yso.fi/onto/yso/p2371) 
[marssit](http://www.yso.fi/onto/yso/p16228) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2004003811> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarvitaan sekä YSAan että SLM-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1977038 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [marssilaulut](http://finto.fi/yse/fi/page/Y506531)

**Comment by mirmaid** [comment]
Ok SLM
