### ISSUE TITLE
Norrbotten

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6532]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Norrbotten](http://www.yso.fi/onto/ysa/Y105886) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi muotoon "Norrbottenin maakunta" 

#### Perustelut ehdotukselle   

Sanastossa on erikseen myös "Norrbottenin lääni". Olisi selkeämpää, että kumpikin termi olisi muodoltaan samanlainen. Muussa tapauksessa hakumuotoon pitäisi lisätä RDA:n vaatima tarkenne. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätään maakunnille sulkutarkenne (maakunta), läänit genetiivimuotoon (ohjaustermiksi sulkutarkenteellinen muoto).

**Comment by mirmaid** [comment]
Ei muutosta.
