### ISSUE TITLE
ilmiölähtöinen oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6533]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmiölähtöinen oppiminen 

#### Ehdotettu termi englanniksi   

phenomenal learning 

#### Ehdotettu termi ruotsiksi   

fenomenellt lärande 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-951-37-7308-3 Phenomenal learning from Finland /  Kirsti Lonka. 

#### Perustelut ehdotukselle   

Ysassa on muitakin oppimisen alakäsitteitä 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [ilmiölähtöinen oppiminen](http://finto.fi/yse/fi/page/Y506533)

**Comment by ilona-x** [comment]
ehdotettu aiemmin: ilmiöpohjainen oppiminen #4467

**Comment by mirmaid** [comment]
Melindassa 3 kertaa ilmiölähtöinen o. & ilmiöpohjainen o., 2 kertaa ilmiöoppiminen, kerran ilmiölähtöisyys.

**Comment by mariaforsen** [comment]
Ruotsinkielinen ehdotus ei ole käytössä, mutta joillakin suomalaisilla sivuilla on käytetty "fenomenbaserat lärande" tai "fenomenbaserad inlärning".
