### ISSUE TITLE
aurinkojäähdytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6535]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aurinkojäähdytys 

#### Ehdotettu termi englanniksi   

solar cooling 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jäähdytys](http://www.yso.fi/onto/yso/p2528) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[19 Energia. Polttoaineet](http://www.yso.fi/onto/yso/p26566) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. Sanastossa on jo aurinkolämmitys. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Solar heating and cooling in Northern and Central Europe :pilot plants in Finland and Germany : Finnish-German joint research project within the European SET-plan strategy / 

**Ehdottajan organisaatio:** Kansalliskirjasto / Satu Niininen **Termiehdotus Fintossa:** [aurinkojäähdytys](http://finto.fi/yse/fi/page/Y506535)

**Comment by mariaforsen** [comment]
Sv. solkylning
