### ISSUE TITLE
rahanlyönti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6537]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rahanlyönti 

#### Ehdotettu termi englanniksi   

mint 

#### Ehdotettu termi ruotsiksi   

myntprägling 

#### Vaihtoehtoiset termit ja ilmaisut   

rahan valmistaminen 
rahan painaminen (setelit) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Rahanly%C3%B6nti 

#### Tarkoitusta täsmentävä selite   

Rahanlyönti on kolikoiden valmistamista metallista.(Wikipedia) 

#### Perustelut ehdotukselle   

Tarvitaan numismaattisen aineiston tarkempaan kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarvitaan numismaattisen aineiston, erityisesti rahan, kolikoiden ja seteleiden historiasta ja valmistuksesta kertovan aineiston kuvailuun, jota on Kansallismuseon rahakammion kirjastossa runsaasti. 

**Ehdottajan organisaatio:** Kansallismuseo / Museovirasto **Termiehdotus Fintossa:** [rahanlyönti](http://finto.fi/yse/fi/page/Y506537)

**Comment by mirmaid** [comment]
4 viitettä Melindassa, kerran rahanvalmistus. Yhdistelmiä _raha(t)_ & _valmistus_ käytetty joitakin kymmeniä kertoja.

**Comment by mariaforsen** [comment]
Sv. mynttillverkning ET myntframställning, myntning, myntprägling

**Comment by YSA-kokous** [comment]
Selvitellään

**Comment by ilona-x** [comment]
SAO:ssa myös sedeltillverkning (KT sedelpressning KT sedlar- tillverkning)

**Comment by mariaforsen** [comment]
Onko asiasanan määritelmä "..kolikoiden valmistamista metallista." vai onko tarkoitus viitata myös setelien valmistukseen? Jos viittaa sekä kolikoiden että setelien valmistukseen vastine on ruotsiksi mynt- och sedeltillverkning (jos vain kolikoiden>mynttillverkning)

**Comment by mirmaid** [comment]
Mielestäni vain kolikoita lyödään, seteleitä painetaan.

**Comment by mariaforsen** [comment]
Korvattuna on kuitenkin "rahan valmistaminen", joka olisi sitten varmaan laajempi termi (olisi parempi ettei korvattuina ole yleensä laajempia termejä, vaan mieluummin toisin päin, eli suppeampi korvattuna?)

**Comment by YSA-kokous** [comment]
Määritellään kolikoiden valmistukseksi, ohjaustermi pois.
