### ISSUE TITLE
rasva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6539]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rasva](http://www.yso.fi/onto/ysa/Y131537) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin rasvat 

#### Perustelut ehdotukselle   

Näiden erottaminen toisistaan käyttäjälle loogisella tavalla on haastavaa. YSOssa tarkenne (ravintoaineet), mutta se ei vastaa rasva-termin kuvailukäyttöä. Sanastossa myös rasvapitoisuus ja rasvakudokset.

**Comment by mariaforsen** [comment]
SAO: fetter
