### ISSUE TITLE
kultakolikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6541]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kultakolikot 

#### Ehdotettu termi englanniksi   

gold coins 

#### Vastaava käsite muussa sanastossa   

Wikisanakirja : https://fi.wiktionary.org/wiki/kultakolikko 

#### Tarkoitusta täsmentävä selite   

Kolikko, joka on kultaa. 

#### Perustelut ehdotukselle   

Tarvitaan numismaattisen aineiston tarkempaan kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarvitaan numismaattisen aineiston, erityisesti rahan ja kolikoiden historiasta kertovan aineiston kuvailuun, jota on Kansallismuseon rahakammion kirjastossa runsaasti. 

**Termiehdotus Fintossa:** [kultakolikot](http://finto.fi/yse/fi/page/Y506541)

**Comment by mirmaid** [comment]
Melindassa kerran _kultarahat_

**Comment by mariaforsen** [comment]
Sv. guldmynt ET guldpengar

**Comment by satuniininen** [comment]
Mieluummin muodossa _kultarahat_.

**Comment by YSA-kokous** [comment]
kultarahat
