### ISSUE TITLE
helmitaulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6542]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

helmitaulut 

#### Ehdotettu termi englanniksi   

abacus 

#### Ehdotettu termi ruotsiksi   

kulram, abakus 

#### Vastaava käsite muussa sanastossa   

Wikisanakirja : https://fi.wiktionary.org/wiki/helmitaulu 

#### Tarkoitusta täsmentävä selite   

Laskemisen apuväline, jossa rei’itettyjä helmiä voidaan liu’uttaa tankoja pitkin. (Wikisanakirja) 

#### Perustelut ehdotukselle   

Tarvitaan helmitauluista kertovan aineiston kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarvitaan helmitauluista kertovan aineiston kuvailuun. 

**Ehdottajan organisaatio:** Kansallismuseo / Museovirasto **Termiehdotus Fintossa:** [helmitaulut](http://finto.fi/yse/fi/page/Y506542)

**Comment by mirmaid** [comment]
MAO-ontologiassa, kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. kulramar ET abakuser
