### ISSUE TITLE
paperirahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6543]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

paperirahat 

#### Ehdotettu termi englanniksi   

paper money 

#### Ehdotettu termi ruotsiksi   

sedlar 

#### Vaihtoehtoiset termit ja ilmaisut   

setelit 

#### Vastaava käsite muussa sanastossa   

Wikisanakirja : https://fi.wiktionary.org/wiki/paperiraha 

#### Tarkoitusta täsmentävä selite   

Käteinen, joka on paperimuotoista; erotuksena kolikoista; seteli (Wikisanakirja) 

#### Perustelut ehdotukselle   

Käsite metallirahat (kolikot) löytyy jo. Setelirahat olisi tarpeellinen lisäys numismaattisen aineiston kuvaamiseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarvitaan numismaattisen aineiston, erityisesti paperirahoista kertovan aineiston kuvailuun, jota on Kansallismuseon rahakammion kirjastossa runsaasti. 

**Ehdottajan organisaatio:** Kansallismuseo / Museovirasto **Termiehdotus Fintossa:** [paperirahat](http://finto.fi/yse/fi/page/Y506543)

**Comment by ilona-x** [comment]
YSA:ssa on jo setelirahat KT setelit http://finto.fi/ysa/fi/page/Y98792

**Comment by mirmaid** [comment]
Ohjaustermiksi?

**Comment by mariaforsen** [comment]
Allärs jo: sedlar=setelirahat.

**Comment by YSA-kokous** [comment]
KÄ setelirahat
