### ISSUE TITLE
rakenteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6544]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakenteet](http://www.yso.fi/onto/ysa/Y98493) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkenteiden lisääminen 

#### Perustelut ehdotukselle   

Sanastossa on sekä rakenne, että rakenteet. Molemmat otettu v. 1986 ja molempia käytetty vähän vajaat 1800 kertaa. Monikkoa käytetty ennen kaikkea rakennustekniikan aineistoissa, joten ainakin yksi kokonaisuus olisi rakenteet (rakennustekniikka/rakentaminen tms.).

**Comment by mirmaid** [comment]
Voisi aloittaa tämän purkamisen rakennustekniikan viitteistä, ja katsoa sen jälkeen mitä jää jäljelle, onko jossain määrin yhdistettävissä yksikköön ja löytyykö muita selkeitä ryhmiä joille voi muodostaa tarkemman termin.

**Comment by LeKorsu** [comment]
Pohdiskeluja:
rakenteet (rakentaminen) sv konstruktioner (byggande)??
rakenne (kielitiede) sv struktur (lingvistik)

**Comment by YSA-kokous** [comment]
rakenteet (rakentaminen)

**Comment by mirmaid** [comment]
Muuta kuin rakentamiseen liittyvää on hyvin vähän...

**Comment by mirmaid** [comment]
_Rakenne_ voidaan ratkaista konversion jälkeen?

**Comment by mariaforsen** [comment]
Sanastossa on myös rakennelmat=konstruktioner (byggnader)

**Comment by mirmaid** [comment]
_Rakenteet_ ja _rakennelmat_ on kyllä suomeksi eri asioita.

**Comment by ilona-x** [comment]
rakenteet siivottu Melindasta, suurin osa muotoon rakenteet (rakentaminen), joitakin muotoon organisaatiorakenne

Muutamat jäljelle jääneet muutettu muotoon rakenne ja jätetty odottamaan konversion jälkeistä ratkaisua tuon termin osalta.

**Comment by mariaforsen** [comment]
Allärsin osalta väliaikaisesti ratkaistu rakenteet vs. rakennelmat niin että:
rakenteet (rakentaminen)= konstruktioner (byggnad)
rakennelmat = enklare byggnader (yksinkertaiset...) tosin laissa konstruktioner ja rakennussanastossa anläggningar, mutta Melinda-käyttö ja tämä sanastotilanne puhuu muun ratkaisun puolesta. Hankala tapaus.

**Comment by mariaforsen** [comment]
Eli termi rakenne=struktur on vielä ratkaisematta. Auttaisiko tarkenteen lisääminen: rakenne (ominaisuudet)? Ominaisuudet on yläkäsite tälle ja mielestäni se erottaisi termistä rakenteet (rakentaminen)=konstruktioner (byggnad).

Termin rakennelmat alakäsitteistä ainakin teltat ja öljynporauslautat pitäisi siirtää muualle (hierarkiavirhe yllä olevan määritelmän mukaan)

**Comment by mirmaid** [comment]
_Rakennelmille_ voisi olla parasta tehdä erillinen issue? Erottaako _konstruktioner (byggnad)_ tämän rakenteet-käsitteen varmasti rakennelmista? 

Tarvitseeko rakenne-tarkenteen? Onko sitä edes mahdollista käyttää väärin?

**Comment by mariaforsen** [comment]
Jos ei tiedä meidän yksikkö/monikko-säännöistä niin eikö se ole ihan mahdollista käyttää väärin, ks. Kielitoimiston sanakirjan 2. merkitys. 

Vastauksena yllä olevaan kysymykseen niin kyllä konstruktioner (byggnad) on eri asia kuin enklare byggnader (fi. rakennelmat). Onko suomeksikin yhtä selvä ero nyt? Ks. Kielitoimiston sanakirja rakennelma, rakenne

Tässä on tärkeitä taustatietoja liittyen rakennelmiin, mutta toki voidaan uusikin issue tehdä. Tämä on kuitenkin ollut todella pitkään ongelmalistalla (ja aikaisemmin kehotettiin laittamaan enklare byggnader) joten toivottavasti voidaan silti melko pian käsitellä.

**Comment by mirmaid** [comment]
^ Mietin vaan että jos joku kuvailisi esim. jotain tien pohjarakenteita tai betonielementtirakenteita käsittelevää aineistoa, niin siinä olisi mielestäni mahdollista käyttää _rakenteet (rakentaminen)_ -käsitteen lisäksi tai sijasta _rakenne_ (tai _rakenne (ominaisuudet)_) -käsitettä, jolloin viittaus olisi sitten enemmän sen rakennattavan kokonaisuuden rakenteelliseen olemukseen. 

_Ominaisuudet_ sopii varmaan aina, mutta tarkentaako se oikeastaan merkitystä millään lailla?

**Comment by YSO-kokous** [comment]
Muutetaan käytettäväksi muodoksi "rakenne (ominaisuudet)". Tästä äänestettiin:

rakenne (ominaisuudet) 4
rakenne 3

Keskustelua herätti se, että tällainen suhteellisen kosmeettinen muutos tuottaisi lisätyötä tietokannoissa. Enemmistö kuitenkin äänesti sulkutarkenteen lisäämistä.
