### ISSUE TITLE
aihetunniste

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6545]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aihetunniste 

#### Ehdotettu termi englanniksi   

hashtag 

#### Ehdotettu termi ruotsiksi   

hashtagg 

#### Vaihtoehtoiset termit ja ilmaisut   

aihesana 
hashtag 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tunnisteet](http://www.yso.fi/onto/yso/p12492) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Aihetunniste 
TEPA-termipankki : <http://www.tsk.fi/tepa/fi/haku/aihetunniste> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

#### Tarkoitusta täsmentävä selite   

Aihetunniste (engl. hashtag, suomeksi myös avainsana) on kokonaisuus, joka muodostetaan ristikkomerkillä (#) ja sitä seuraavalla sanalla tai merkkijonolla. Metatietotunnisteisiin kuuluva aihetunniste helpottaa viestintää, sen avulla viestit ohjautuvat oikeaan paikkaan ja sen avulla voi hakea tiettyyn aiheeseen liittyviä viestejä. Aihetunnisteen perimmäinen tarkoitus on saattaa saman aihealueen viestit yhteen, jotta tiedonhakijan olisi helpompi tarkastella ja yhdistellä tietoja. Sosiaalisen median sovelluksissa, kuten Twitterissä, käyttäjä voi muodostaa hashtagin tagaamalla viestin sisältöä kuvailevan sanan tai fraasin, esim. “Kevään 2015 #eduskuntavaalit". 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Virolainen, Mia, Kaapattu hashtag? (artikkeli julkaisussa: Twitter viestintänä, 978-951-768-615-0) 

#### Perustelut ehdotukselle   

Fintosta ei löydy muuta asiasanaa, jolla aihetta voisi kuvailla. 

**Ehdottajan organisaatio:** Avoimen tiedon keskus, kirjasto, Jyväskylän yliopisto **Termiehdotus Fintossa:** [aihetunniste](http://finto.fi/yse/fi/page/Y506545)

**Comment by jarmosaarikko** [comment]
Tämä on myös Tepassa: http://www.tsk.fi/tepa/fi/haku/hashtag

**Comment by mirmaid** [comment]
Monikkoon kuten _avainsanat_ vai yksikköön kuten _ISBN_?

**Comment by krinay** [comment]
Kannatan monikkomuotoa.

**Comment by satuniininen** [comment]
LCSH:ssa [Hashtags (Metadata)](http://id.loc.gov/authorities/subjects/sh2017005172.html)

**Comment by YSA-kokous** [comment]
monikko

**Comment by mariaforsen** [comment]
Sv. hashtaggar ET fyrkantstaggar, hashtags
