### ISSUE TITLE
isyysloma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6549]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[isyysloma](http://www.yso.fi/onto/ysa/Y95585) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ isyysvapaa. Samoin äitiysloma KÄ äitiysvapaa. 

#### Perustelut ehdotukselle   

Yhdistetty YSOssa, ei tarvetta eri termeille.

**Comment by mirmaid** [comment]
Samoin varmaankin myös vanhempainloma.

**Comment by mariaforsen** [comment]
Kannatan. Ruotsiksi föräldraledighet = vanhempainloma + vanhempainvapaa

**Comment by YSA-kokous** [comment]
vanhempainvapaa
