### ISSUE TITLE
köllinimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6550]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[köllinimet](http://www.yso.fi/onto/ysa/Y151313) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selvennetään mitä eroa lisänimet-termiin 

#### Perustelut ehdotukselle   

https://www.kielikello.fi/-/peitenimia-ja-niiden-kayttajia: miehistä perinnettä, yleensä kaksiosaisia...käytännössä näyttää kuitenkin ettei näillä ole selvää eroa?

**Comment by mariaforsen** [comment]
Lisänimet=sv. binamn: särskiljande, namnliknande uttryck som används i stället för eller tillsammans med förnamn för att beskriva viss person, ex. Harald Hårfagre
Köllinimet=sv. öknamn: namn som används mer eller mindre nedsättande, oftast om person. 
Nämä ovat siis ruotsiksi eri asioita. Vastaavalla tavalla kuin Kielitoimiston sanakirja käsittelee: kölli= haukkuma-, liikanimi  VS. lisänimi = liikanimi. Pietari I sai lisänimen Suuri.

**Comment by krinay** [comment]
Suomen kielessä varmaankin ihan sama ero kuin ruotsissa.

Kölliperinne on kiusoittelufolklorea, naapurihuumoria, josta ovat kirjoittaneet ainakin suomen kielen tutkijat ja folkloristit, esim. Kirsti Mäkinen: Lollot ja kollot: suomalaista naapurihuumoria. Mäkinen määrittelee kirjassa suomalaisesta aineistosta 10 erilaista köllityyppiä. 

Esimerkkejä kölleistä: Lapuan laiskat, Ylistaron ylpiät, Loimaan lollot, torniton kirkko (Vähäkyrö), kierrekaulat (kaavilaiset), Paitanuija (Kurikka), kaukaa komea (kyröläinen).

**Comment by mirmaid** [comment]
Tästä artikkelista https://www.kielikello.fi/-/peitenimia-ja-niiden-kayttajia sain sen käsityksen, että köllinimi ei välttämättä olisi (ainakaan selkeästi) negatiivinen. 

Kielitoimiston sanakirjassa
**köllinimi**: haukkuma-, liikanimi.
**liikanimi**: nimi jota käytetään varsinaisen t. oikean nimen ohella t. sijasta, lisänimi; lempinimi, haukkumanimi, kölli.

**Comment by mirmaid** [comment]
Onko _pilkkanimet_ mahdollinen ohjaustermi köllinimille? https://github.com/Finto-ehdotus/YSE/issues/1852

**Comment by krinay** [comment]
_Pilkkanimet_ voisi minusta hyvin laittaa ohjaustermiksi köllinimille. Mutta pitäisikö sen ohjata myös termiin _lisänimet_? (Voiko ohjaustermi ohjata saman hierarkian ylä- ja alakäsitteeseen?)

**Comment by YSA-kokous** [comment]
Ei muutosta.

**Comment by ilona-x** [comment]
lisäys: köllinimet RT kiusoitteluperinne
