### ISSUE TITLE
tölkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6552]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tölkit](http://www.yso.fi/onto/ysa/Y151400) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ purkit 

#### Perustelut ehdotukselle   

Molemmat =burkar. Nyt kuitenkin tölkit=konservburkar, sehän on oikeastaan säilyketölkit/purkit, mutta sitä ei ole suomeksi mukana edes korvattuna, eikä se täsmää Melindan kanssa. Olisiko yhdistäminen (purkit ja tölkit) tai tarkempi määrittely (jolloin voidaan luoda tarkenteita tms.) mahdollisia ratkaisuja?

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/917

**Comment by YSA-kokous** [comment]
Purkit säilyy entisellään, KT tölkit. Tölkit poistetaan, tilalle juomatölkit KT tölkit.
