### ISSUE TITLE
vaihdettavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6553]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaihdettavuus 

#### Perustelut ehdotukselle   

On jo YSOssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [vaihdettavuus](http://finto.fi/yse/fi/page/Y506553)

**Comment by mariaforsen** [comment]
Sv. utbytbarhet
