### ISSUE TITLE
koetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6554]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koetus](http://www.yso.fi/onto/ysa/Y102597) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko mitenkään mahdollista poistaa (kuten standardin mukaan voi tehdä jos aiheuttaa kohtuuttomia ongelmia kääntämiseen, sekä jos sana ei ole aivan välttämättä tarpeen)? Kysymys on kuitenkin eräänlaisesta testaamisesta ja/tai kontrolli, tarkistus yms. Ks. MOT, TEPA jne. 

#### Perustelut ehdotukselle   

Vanha ja vaikeasti ratkaistava ongelma ruotsin osalta. On ollut "kontroll (fysik)", se ei ole käytännössä toimiva ratkaisu ja sanastossa on myös kontrolli=kontroll, eikä siihen voi lisätä tarkennetta (niinkuin säännöt tietysti vaatisivat).

**Comment by mirmaid** [comment]
Voisi tutkia onko korvattavissa termeillä _aineenkoetus_ tai _testaus_.

**Comment by YSA-kokous** [comment]
KÄ aineenkoetus, testaus
