### ISSUE TITLE
kulttuurintutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6556]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kulttuurintutkimus](http://www.yso.fi/onto/ysa/Y106237) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään kulttuurintutkimus ja kulttuurien tutkimus tai selkeytetään näiden välistä eroa termejä muuttamalla. 

#### Perustelut ehdotukselle   

Termit ovat varsin lähellä toisiaan ja niiden merkityserot eivät välttämättä avaudu asiaan vihkiytymättömälle kuvailjalle tai tiedonhakijalle. Tämä näkyy myös Melinda-kuvailussa, jossa niitä on käytetty aika paljon päällekkäin. Termit/käsitteet ovat ongelmia myös kielivastineiden kannalta.

Wikipedian mukaan kulttuurintutkimus on "monitieteistä ja ensisijaisesti länsimaisen nykykulttuurin tutkimukseen keskittyvää humanistis-yhteiskuntatieteellistä tutkimusta". Ongelmallisempi näistä kahdesta on kulttuurien tutkimus, joka on vahvasti Helsingin yliopistoon linkittyvä termi. HY:ssä on toiminut aiemmin Kulttuurien tutkimuksen laitos. Laitosta ei enää ole, mutta nimitys elää edelleen nykyisessä HY:n rakenteessa erilaisia oppiaineita (esim. arkeologia, Afrikan tutkimus) yhteen niputtavana kokonaisuutena, "tieteenalana". Englanniksi tämä on HY:n sivuilla pelkästään "Cultures" ja ruotsiksi "Kultur". Muissa kotimaisissa yliopistoissa tämän nimistä laitosta ei ole, esim. Itä-Suomen yliopistossa melko lailla vastaava kokonaisuus on nimeltään kulttuurintutkimus. Ks. tarkemmin: https://www.helsinki.fi/fi/humanistinen-tiedekunta/tutkimus/tieteenalat/kulttuurien-tutkimus

Toisaalta esim. Itä-Suomen yliopisto ei selvästikään rajaa kulttuurintutkimusta pelkästään länsimaiseen nykykulttuurin, koska sen alle lasketaan myös kulttuuriantropologia ja etnomusikologia. Englanninkielinen Wikipedia rajaa cultural studies (=kulttuurintutkimus) -käsitteen kylläkin nykykulttuurin tutkimukseen, mutta ei pelkästään länsimaisen kulttuurin tutkimukseen. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by krinay** [comment]
Onkohan tähän ehdotukseen tullut kommentteja muualta? Kerätäänhän ne tähän? Asia on hankala, hienoa, jos siihen nyt saadaan jonkilainen toistaiseksi useimpia tyydyttävä ratkaisu.

Termi _kulttuurien tutkimus_ on otettu YSAan aikoinaan samasta syystä kuin sitä on käytetty Helsingin ja Turun yliopistoissa eli kattotermiksi tietyille toisiaan lähellä oleville oppiaineille. Yliopistollisten oppiaineiden nimet ovat haasteellisia - laitosten nimistä puhumattakaan. Eri maiden yliopistoissa ja jopa Suomen sisällä on käytössä eri nimiä paitsi tästä yläkäsitteestä myös sen alla olevista aloista. Tämä seikka itse asiassa vain lisää tarvetta jonkinlaiselle yläkäsitteelle. Keinotekoinenkin termi on joskus parempi kuin ei mitään. Ja täytyy pitää mielessä, että YSA ja YSO eivät ole tieteenalojen termipankkeja vaan käytännön apuvälineitä sisällönkuvailuun.

Meillä SKS:n kirjastossa tehtiin vuonna 2002 muutamille alan asiantuntijoille kysely tähän aihepiiriin liittyen. Pohdimme silloin, mikä olisi kuvaavin ja täsmällisin nimitys kirjaston silloisen etnologisen osaston edustamille aloille. Ks. yhteenveto kyselyn tuloksista: http://neba.finlit.fi/kirjasto/servaali/200202.htm. Tuolloin siis useimmat asiantuntijoista pitivät parhaan termiä _kulttuurien tutkimus_. Olisi mielenkiintoista kuulla, mitä mieltä näiden alojen edustajat nykyisin ovat.

**Comment by mariaforsen** [comment]
Ruotsiksi nyt kulturforskning ja kulturvetenskap, eli virheellinen vastaavuus. Monikielisen työn kannalta on tärkeää että jokaisella päätermillä on tietty merkitys ja että jokaisella "merkityksellä" on vain yksi päätermi. Jos on epäselvää miten nämä todellisuudessa eroavat toisistaan ja miten ne kuuluisi käyttää, niin silloin on vaikeaaa luoda oikeita vastineita.

**Comment by mirmaid** [comment]
_Kulttuurien tutkimus_ -termiä on käytetty Melindassa vain 138 kertaa, _kulttuurintutkimus_ lähes 4000 kertaa.

Voisiko teoksen _Askel kulttuurien tutkimukseen_ http://www.utupub.fi/handle/10024/135172 kuvailla asiasanalla _kulttuurintutkimus_? Jos ei, onko muuta vaihtoehtoa kuin luetella yksittäiset aineet (mikä täytyy joka tapauksessa tehdä, ja on ko. teoksen kuvailussa tehtykin)? 

Ks. myös https://www.helsinki.fi/fi/kulttuurien-tutkimuksen-kandiohjelma-humanististen-tieteiden-kandidaatti-ja-filosofian-maisteri-3-v-2-v/1.2.246.562.17.66610708852, ruotsiksi https://www.helsinki.fi/sv/kandidatprogrammet-i-kulturforskning-kandidat-i-humanistiska-vetenskaper-och-filosofie-magister-3-ar-2-ar/1.2.246.562.17.66610708852

**Comment by LeKorsu** [comment]
Jäisikö kulttuurintutkimus siis edelleen omaksi termiksi nykyisine määrittelyinen [(nyky)kulttuurin tutkimusta] tuon Mirjan ehdotuksen rinnalle?
Termien yhdistäminen olisi kaltaiselleni tämän tieteenalan maallikolle yksinkertaisin ratkaisu ja kulttuuriantropologiaa opiskellut kollega komppaa:  "Kulttuuriantropologian opinnotkin alkoivat "kulttuuri" -sanan määrittelyllä, ja että on hyvin monenlaisia määritelmiä. Laajimpien "kulttuuri" -määritelmien mukaan "kulttuuri" kattaa kaiken missä ihminen on ollut mukana (suhteessa luontoon), esim tekemisen kautta mutta myös ajattelutavat, uskomukset, arvostukset, taide, kirjallisuus ym ovat kulttuurin osatekijöitä. 
Kannatan kulttuurien tutkimus -asiasanan sulauttamista kulttuurintutkimus -asiasanaan, koska "kulttuuri" itsessään voidaan ajatella noin laajasti.  Kulttuurien tutkimus asiasana jotenkin epämääräinen. Miettii vaan että minkä kulttuurien."
