### ISSUE TITLE
Weimarin tasavalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6557]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Weimarin tasavalta](http://www.yso.fi/onto/ysa/Y159117) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään käsite YSO-paikoista varsinaisen YSOn puolelle. 

#### Perustelut ehdotukselle   

Kyseessä ei ole maantieteellisesti määritelty alue, vaan historiallinen ajanjakso (Saksa vuosina 1919–1933). Analogioina "autonomian aika" ja "ruotsin vallan aika", jotka nekin liittyvät vain yksittäisen valtion historiaan ajanjaksoa kuvaavina termeinä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSOn puolella on _kolmas valtakunta_, http://www.yso.fi/onto/yso/p10793. Tässä muodossa _Weimarin tasavalta_ kuitenkin viittaa mielestäni paikkaan, parempi termi YSOn puolella olisi _Weimarin tasavallan aika_. Wikidatan mukaan Weimarin tasavalta on _historical period_ ja _historical country_.

**Comment by YSO-kokous** [comment]
Paikkakäsitteen sijaan sopisi paremmin aikakausikäsitteeksi. Muodoksi _Weimarin tasavallan aika_ ja ohjaustermiksi _Weimarin tasavalta_. Päätettäväksi YSO-kokoukseen.

**Comment by AuHo22** [comment]
Saksan kansalliskirjaston sanastoissa Weimarin tasavalta (Weimarer Republik) samoin kuin Drittes Reich ovat epookkien kuvauksia, Pyhä saksalais-roomalainen valtakunta taasen on paikkakäsite:

https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4011882-4

Esim. (Weimarer Republik)  Verwendungshinweis: Epochenbezeichnung; weitere Eintragung mit Deutschland und Geschichte 1918-1933.

https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4065109-5

https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&reset=true&referrerPosition=8&referrerResultId=dritte+and+reich%26any&query=idn%3D040130215

Weimarin tasavalta on kuitenkin itsenäistä Saksaa, ei toisen vallan alaisuudessa elämistä tms. kuten autonomian aika Suomessa tai Ruotsin vallan aika tai neuvostovallan aika - eli saivarrellen joku muu maa eläisi Weimarin tasavallan alaisuudessa? Saksaa jonkin verran tuntevana kannatan muotoa Weimarin tasavalta  - tai otammeko myös muodon kolmannen valtakunnan aika, jolle ehkä olisi enemmän tilausta?

**Comment by mariaforsen** [comment]
SAOssa kronologisena asiasanana: "1918-1933 (Weimarrepubliken, Tyskland)"

**Comment by YSO-kokous** [comment]
Siirretään YSOon, jossa käsitellään samoin kuin "kolmas valtakunta".
Weimarin tasavalta KT Weimarin tasavallan aika
kolmas valtakunta KT  kolmannen valtakunnan aika
Voidaan lisätä määritelmä, josta näkyvät vuodet 1918-1933.
Kolmas valtakunta voi tarvita tarkenteen, joka viittaa 1900-luvun kolmanteen valtakuntaan.

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Saksan_valtakunta
