### ISSUE TITLE
koskikara

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6558]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koskikara 

#### Ehdotettu termi englanniksi   

White-throated Dipper 

#### Vaihtoehtoiset termit ja ilmaisut   

Cinclus cinclus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[varpuslinnut](http://www.yso.fi/onto/yso/p1909) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.32625 
Maailman lintujen suomenkieliset nimet : <http://nimisto.birdlife.fi:3000/> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

ARTOssa kymmeniä kertoja 

#### Tarkoitusta täsmentävä selite   

Maailman lintujen suomenkieliset nimet - tietokannassa yläkäsitteinä on mainittu koskikarat (suku - Cinclus), koskikarat (heimo - Cinclidae). Laji.fi-tietokannassa ei ole näiden suomenkielisiä käännöksiä. YSAssa on varpuslintujen alla heimoja ja niiden alla lajeja. Ehkä tässäkin voisi ottaa YSAan lajin ja yläkäsitteeksi heimon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARTO 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto / Päivi Lipsanen **Termiehdotus Fintossa:** [koskikara](http://finto.fi/yse/fi/page/Y506558)

**Comment by mariaforsen** [comment]
Sv. strömstare
