### ISSUE TITLE
pesimälinnusto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6559]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pesimälinnusto 

#### Ehdotettu termi englanniksi   

breeding birds 

#### Ehdotettu yläkäsite YSOssa (LT)   

[linnusto](http://www.yso.fi/onto/yso/p16308) 

#### Assosiatiiviset (RT)   

[linnut](http://www.yso.fi/onto/yso/p3363) 
[lintukannat](http://www.yso.fi/onto/yso/p21389) 

#### Vastaava käsite muussa sanastossa   

AFO : https://finto.fi/afo/fi/page/p7633 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Sekä ARTOssa että Melindassa kymmenissä tietueissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ARTO ja Melinda 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto / Päivi Lipsanen **Termiehdotus Fintossa:** [pesimälinnusto](http://finto.fi/yse/fi/page/Y506559)

**Comment by mariaforsen** [comment]
Sv. häckfåglar ET häckande fåglar, häckande fågelbestånd, häckande fågelfauna, häckfågelbestånd, häckfågelfauna

**Comment by mariaforsen** [comment]
Onko KT pesimälinnut?

**Comment by mirmaid** [comment]
KT lisätty
