### ISSUE TITLE
uurnakenttäkulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6560]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uurnakenttäkulttuuri 

#### Ehdotettu termi englanniksi   

Urnfield culture 

#### Ehdotettu termi ruotsiksi   

urnefältskulturen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuurit (kulttuurimuodot)](http://www.yso.fi/onto/yso/p1546) 

#### Assosiatiiviset (RT)   

[pronssikausi](http://www.yso.fi/onto/yso/p4625) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85141431.html> 
Wikipedia : https://fi.wikipedia.org/wiki/Uurnakentt%C3%A4kulttuuri 
SAO : Urnefältskulturen 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Urnenfelderzeitliche Gräber aus Neubau/Hörsching / Martina Reitberger-Klimesch 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [uurnakenttäkulttuuri](http://finto.fi/yse/fi/page/Y506560)

**Comment by mirmaid** [comment]
13 viitettä Melindassa.
