### ISSUE TITLE
Alatskivi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6580]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Alatskivi 

#### Ehdotettu termi ruotsiksi   

Alatskivi 

#### Ehdotettu termi englanniksi   

Alatskivi 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Alatskivi_Parish 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna-test.fi/Record/helka.2648484 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 

#### Tarkoitusta täsmentävä selite   

Alatskivi on entinen kunta Tartumaalla Virossa. Viime vuodesta alaken se on ollut osa uutta Peipsiäären kunttaa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Alatskivi](http://finto.fi/yse/fi/page/Y506580)

**Comment by paivalai** [comment]
Tietueesta jäi puuttumaan 'Yläkäsite YSOssa (LT)'. Se on Viro.
