### ISSUE TITLE
Lennuk (purjevene)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6591]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Lennuk (purjevene) 

#### Ehdotettu termi ruotsiksi   

Lennuk (segelfartyg) 

#### Ehdotettu termi englanniksi   

Lennuk (sailing vessel) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[veneet](http://www.yso.fi/onto/yso/p7491) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://et.wikipedia.org/wiki/Lennuk_(purjekas) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

Lennuk oli purjevene, joka teki 1999-2001 maailmanympärimatkan. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1739295 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Lennuk (purjevene)](http://finto.fi/yse/fi/page/Y506591)

**Comment by mirmaid** [comment]
Ehdotus: yksittäiset alukset auktorisoidaan yhteisöinä, jos tarpeen. Toimijakuvailu päättää mitä auktorisoidaan.

**Comment by mariaforsen** [comment]
Toivottavasti auktorisoidaan myös ruotsinkielisiä vastineita siellä.

**Comment by mirmaid** [comment]
Suomalaiset yhteisönimet -sanastoon auktorisoidaan ensisijaisesti suomalaisia laivoja ja veneitä.
