### ISSUE TITLE
Raadi mõis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6594]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Raadi mõis 

#### Ehdotettu termi ruotsiksi   

Raadi herrgård 

#### Ehdotettu termi englanniksi   

Raadi manor 

#### Vaihtoehtoiset termit ja ilmaisut   

Kielletyksi 'Raadin kartano' 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2018000981> 
Wikipedia : https://en.wikipedia.org/wiki/Raadi_Manor 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Tartossa sijaitseva kartano. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2886719 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Raadi mõis](http://finto.fi/yse/fi/page/Y506594)

**Comment by tpalonen** [comment]
_Raadi mõis_ on vironkielinen ilmaus. Suosittelen suomen kielen käytettäväksi termiksi Raadin kartanoa.
Vrt.
https://fi.wikipedia.org/wiki/Raadin_kartano
https://www.visitestonia.com/fi/raadin-kartano
