### ISSUE TITLE
Muuga --- Länsi-Virumaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6596]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Muuga --- Länsi-Virumaa 

#### Ehdotettu termi ruotsiksi   

Muuga --- Lääne-Virumaa 

#### Ehdotettu termi englanniksi   

Muuga --- Lääne Viru County 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Muuga,_L%C3%A4%C3%A4ne-Viru_County 

#### Tarkoitusta täsmentävä selite   

Ko. Muuga on Länsi-Virumaalla Virossa sijaitseva kylä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1344164 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Muuga --- Länsi-Virumaa](http://finto.fi/yse/fi/page/Y506596)

**Comment by mirmaid** [comment]
Käytetty kuvailussa tässä merkityksessä vain kaksi kertaa, useammin Muugan satamasta (korj. > 653 Muugan satama). Varmaankin syytä silti auktorisoida selkeyden vuoksi.
