### ISSUE TITLE
Pohjois-Amerikan vapaussota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6597]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pohjois-Amerikan vapaussota](http://www.yso.fi/onto/ysa/Y112484) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Käytetty Melindassa.
SAO: Amerikanska revolutionen se Nordamerikanska frihetskriget 

#### Ehdotettu muutos   

Uusi KT amerikan vallankumous

**Comment by mirmaid** [comment]
Wikipediassa erotettu
https://en.wikipedia.org/wiki/American_Revolution
https://en.wikipedia.org/wiki/American_Revolutionary_War

**Comment by YSA-kokous** [comment]
Otetaanko erikseen?
