### ISSUE TITLE
hävikkiruoka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6600]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hävikkiruoka 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ruoka (aine)](http://www.yso.fi/onto/yso/p3670) 

#### Assosiatiiviset (RT)   

[jätteiden hyötykäyttö](http://www.yso.fi/onto/yso/p2180) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Tarkoitusta täsmentävä selite   

Ei viittaa ruokahävikkiin tai -jätteeseen, vaan ravintolalta tai elintarvikeliikkeeltä käyttämättä jääneseen mutta täysin syöntikelpoiseen ruokaan, jota voidaan tarjota asiakkaille edulliseen hintaan. 

#### Perustelut ehdotukselle   

Hävikkiruoka on nouseva ilmiö etenkin kaupungeissa ja yhteisöissä, joissa ravinnon ympäristö- ja eettisyysasiat huomioidaan vakavasti. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Käsite olisi tarpeellinen Suomi.fi-palvelutietovarannossa, josta se on rajattomasti erilaisten palvelujen käytössä. 

**Ehdottajan organisaatio:** Väestörekisterikeskus **Termiehdotus Fintossa:** [hävikkiruoka](http://finto.fi/yse/fi/page/Y506600)

**Comment by mariaforsen** [comment]
Sv. överbliven mat?

**Comment by mirmaid** [comment]
Ei Melindassa. Vaikka tällä voidaankin viitata nimenomaan ruokahävikin estämiseen, kuvailukäyttö olisi luultavasti melko päällekkäistä.

**Comment by satuniininen** [comment]
Melinda: 
ruokahävikki + hyödyntäminen 20 kpl 
ruokahävikki + hyötykäyttö 7 kpl

Samaa mieltä että _ruokahävikki_ ja _hävikkiruoka_ ovat liian lähellä toisiaan. Jos tämä halutaan omaksi käsitteekseen niin se olisi syytä muotoilla selkeämmäksi, esim. _hävikkiruoan hyödyntäminen_ vrt. https://fi.wikipedia.org/wiki/H%C3%A4vikkiruoan_hy%C3%B6dynt%C3%A4minen

Itse näkisin että riittävä tarkkuus saavutetaan yhdistämällä _ruokahävikki_ muihin käsitetteisiin.
