### ISSUE TITLE
maisemapuutarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6604]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maisemapuutarhat 

#### Ehdotettu termi englanniksi   

landscape gardens 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puistot](http://www.yso.fi/onto/yso/p3227) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Yhteinen nimittäjä erilaisille maisemapuutarhoille, joiden alajina mm. englantinen puisto. Termisuhteet yllä mainitun lisäksi siis: ST "englantilaiset puistot" [https://github.com/Finto-ehdotus/YSE/issues/6603] ja ST "muotopuutarhat" [https://github.com/Finto-ehdotus/YSE/issues/1462] 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [maisemapuutarhat](http://finto.fi/yse/fi/page/Y506604)

**Comment by mariaforsen** [comment]
Sv. landskapsträdgårdar

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Maisemapuutarha

**Comment by mirmaid** [comment]
2 viitettä Melindassa

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1694
