### ISSUE TITLE
tierummut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6606]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tierummut 

#### Vaihtoehtoiset termit ja ilmaisut   

rumpuputket 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.doria.fi/bitstream/handle/10024/121390/lts_2015-18_978-952-317-078-0.pdf?sequence=1 

#### Perustelut ehdotukselle   

esim. sadevesiputket teiden alla 

**Termiehdotus Fintossa:** [tierummut](http://finto.fi/yse/fi/page/Y506606)

**Comment by ilona-x** [comment]
aiemmin ehdotettuja: 
rumpurakenteet https://github.com/Finto-ehdotus/YSE/issues/4487
siltarummut https://github.com/Finto-ehdotus/YSE/issues/4488

**Comment by mariaforsen** [comment]
Sv. vägtrummor

**Comment by YSA-kokous** [comment]
rumpurakenteet

**Comment by mariaforsen** [comment]
Sv. trumkonstruktioner
