### ISSUE TITLE
pikarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6608]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pikarit 

#### Ehdotettu termi ruotsiksi   

bägare 

#### Ehdotettu yläkäsite YSOssa (LT)   

[juoma-astiat](http://www.yso.fi/onto/yso/p20891) 
[metalliesineet](http://www.yso.fi/onto/yso/p8496) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 
[34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576) 
[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Tarkoitusta täsmentävä selite   

Metallinen korvaton juoma-astia [https://www.kielitoimistonsanakirja.fi/pikari] 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Finländska silverbägare : konst och historia 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [pikarit](http://finto.fi/yse/fi/page/Y506608)

**Comment by mirmaid** [comment]
MAO-ontologiassa, 6 viitettä Melindassa.
