### ISSUE TITLE
nanait

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6609]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nanait 

#### Ehdotettu termi englanniksi   

Nanai people (vai Nanais vai Nanai (people)?) 

#### Vaihtoehtoiset termit ja ilmaisut   

goldit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansat (väestöryhmät)](http://www.yso.fi/onto/yso/p3993) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85055778> 
Wikipedia : https://fi.wikipedia.org/wiki/Nanait 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Melindassa 25 viitettä, Artossa 10. YSAssa on jo nanain kieli ja nanainkielinen kirjallisuus. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. kirja Nanai shamanic culture in indigenous discourse / Tatiana Bulgakova (2013) ja artikkeli Temenos-lehden uusimmassa numerossa. 

#### Tarkoitusta täsmentävä selite   

"Nanait (aikaisemmin myös goldit) ovat kansa Habarovskin aluepiirissä Venäjän Kaukoidässä Amurin alajuoksun ympäristössä Ohotanmeren rannalla. Heitä asuu myös Ussurin ja Girinin varsilla sekä Koillis-Kiinassa Sungarin varsilla. Vuoden 2002 tilaston mukaan nanaita oli Venäjällä 12 160. Lisäksi Kiinan puolella asui vuoden 1990 väestönlaskennan mukaan 4 245. Nanait puhuvat pohjois-tunguusilaisiin kieliin kuuluvaa nanain (eli goldin) kieltä. Nanait harjoittavat kalastusta ja metsästystä." -- Wikipedia

Ks. myös Nanai people: https://en.wikipedia.org/wiki/Nanai_people

LCSH:n termi Nanai (Asian people): 
Border terms: Ethnology-China; Ethnology-Russia (Federation); Manchus.
Narrower terms: Hezhen (Chinese people)
Closely Matching Concepts from Other Schemes: Nanaï (peuple de Sibérie) 

**Ehdottajan organisaatio:** SKS:n kirjasto **Termiehdotus Fintossa:** [nanait](http://finto.fi/yse/fi/page/Y506609)

**Comment by mariaforsen** [comment]
Sv. nanajer ET golder
