### ISSUE TITLE
urkujen julkisivut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6610]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

urkujen julkisivut 

#### Ehdotettu termi ruotsiksi   

orgelfasader 

#### Ehdotettu termi englanniksi   

organ facades 

#### Vaihtoehtoiset termit ja ilmaisut   

urkufasadit 
organ prospects [eng] 
 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[julkisivut](http://www.yso.fi/onto/yso/p15728) 
[urut](http://www.yso.fi/onto/yso/p16092) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2861534 ja useita muita 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Urkujen näkyvä osa, joka voi olla osa soittimen soivaa rakennetta tai yksinomaan rakennustaiteellinen elementti varsinaisen soittimen edessä. 

#### Perustelut ehdotukselle   

Aiheesta kirjallisuutta, mutta sopiva asiasana puuttuu. Irtosanat "urut" ja "julkisivut" eivät tuota täsmällistä osumaa, ks. esim. alla oleva kirja, joka käsittelee julkisten rakennusten sisätilojen ja urkufasadien suhdetta – ei urkujen sisätiloja tai julkisten rakennusten julkisivuja! 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [urkujen julkisivut](http://finto.fi/yse/fi/page/Y506610)

**Comment by jarmosaarikko** [comment]
"urkufasadit" on käytetty Melindassa kerran:
https://melinda.kansalliskirjasto.fi/byid/000556845 Alttarikaapista osaksi arkkitehtonista kokonaisuutta : urkufasadin, sen suunnittelun ja rakentamisen historiaa ja nykypäivää / Sirkku Leppäranta.

Tuo voisi olla koostumussuhteisena myös urun osa kuten urkupillit ja -pillistöt ja koskettimet sekä polkimet. Urkujen pillistöt voivat myös olla sijoitettuna hajalleen moneen eri kohtaan, jotka muodostavat sitten tuon visuaalisen "ulkoasun" tai "julkisivun"
Urkujen osistakin löytyy julkaisuja: esim. https://melinda.kansalliskirjasto.fi/byid/011381475 Tuomiokirkon urkupillit.
Käykö julkisivut (kt fasadit)  yläkäsitteeksi, kun se on "ihmisen määrittämä paikka" käsitteen alla?  -- ei liity vain kirkkoihin, kun urkuja on myös konserttisaleissa.

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa käsitteen "urkujen julkisivut" ottamista YSAan. Ohjaustermiksi "urkufasadit".
