### ISSUE TITLE
kellotornit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6611]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kellotornit](http://www.yso.fi/onto/ysa/Y200895) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "campanilet"', "kampanilet" ja "kampaniilit". 

#### Perustelut ehdotukselle   

Kaikkia näitä on käytetty suomenkielisessä kirjallisuudessa, joten ne olisi hyvä saada hakujen piiriin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. klockstaplar ET kampaniler, klocktorn
