### ISSUE TITLE
kääpiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6614]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kääpiöt](http://www.yso.fi/onto/ysa/Y152623) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termiin lisättävä käyttöhuomautus! 

#### Perustelut ehdotukselle   

Nyt asiasanalla "kääpiöt" on kuvailtu valokuvia, joissa näkyy lyhytkasvuisia ihmisiä – vaikka asiasanan LT-suhteet ("satuolennot", "taruolennot" ja "yliluonnolliset olennot") viittaavat muihin kuin todellisiin henkilöihin. Ja nämä valokuvat näkyvät siis Fintossa esimerkkeinä asiasanan käytöstä, olipa se virheetöntä tai virheellistä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Voisi lisätä myös sulkutarkenteen, mutta mikähän se olisi? Taruolennot?

**Comment by satuniininen** [comment]
Heh, Melindassa käytetty myös aineistosta _Valkoiset kääpiöt puhdasta hiiltä : yötaivaan aidot timantit_.

Sulkutarkenne (taruolennot) lienee paras ratkaisu.

**Comment by mirmaid** [comment]
Itseasiassa mietin tätä tutkaillessa, pitäisikö ottaa myös _kääpiötähdet_. Jotenkin sympaattinen on "musta kääpiö": _täysin loppuunpalanut valkoinen kääpiö_  :tired_face: :star2: https://fi.wikipedia.org/wiki/K%C3%A4%C3%A4pi%C3%B6t%C3%A4hti

**Comment by mariaforsen** [comment]
Kannatan kääpiötähdet-ehdotusta (myös SAOssa ja linkitetty LCSH-termiin Dwarf stars)

**Comment by YSA-kokous** [comment]
kääpiöt (taruolennot) ja kääpiötähdet KT kääpiöt (tähdet)
