### ISSUE TITLE
Fagervik

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6617]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Fagervik](http://www.yso.fi/onto/ysa/Y116493) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termi jaetaan kahdeksi: 1) paikkakuntaa (kylää) kuvaavaksi, esim. "Inkoo -- Fagervik" tai RDA:n mukainen "Fagervik (Inkoo, Suomi)", ja 2) kyseisessä kylässä sijaitsevaa kartonoa kuvaavaksi, esim. "Fagervikin kartano". Analogia: "Helsinki -- Munkkiniemi" ~ "Munkkiniemen kartano". 

#### Perustelut ehdotukselle   

Kuvailussa on tarvetta erillisille termeille! 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
YSA:ssa on jo molemmat muodot:
kylä: Inkoo -- Fagervik http://finto.fi/ysa/fi/page/Y130215
kartano: Fagervik KT Fagervikin kartano http://finto.fi/ysa/fi/page/Y116493

**Comment by jtuohini** [comment]
Tietystikään en löytänyt tuota "Inkoo -- Fagervik" -muotoa hakemalla pelkällä 'Fagervik'-sanalla… Mutta voisiko tuon kartanon kattavan asiasanan silti muuttaa yksiselitteiseen muotoon (_Fagervikin kartano_) tai lisätä siihen huomautuksen, että samannimisestä kylästä käytetään sitä-ja-sitä asiasanaa?

**Comment by YSA-kokous** [comment]
Fagervikin kartano
