### ISSUE TITLE
pienoisveistokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6618]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pienoisveistokset](http://www.yso.fi/onto/ysa/Y189758) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "statyetit" 

#### Perustelut ehdotukselle   

Hieman vanhahtava nimitys, mutta kun kerran on käytetty, niin viittaus olisi hyvä saada (lähteenä: Arja Forsmanin "Kreikkalaiset terrakottastatyetit") 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. statyetter
