### ISSUE TITLE
Best Fiends (peli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6619]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Best Fiends (peli) 

#### Ehdotettu termi ruotsiksi   

Best Fiends 

#### Ehdotettu termi englanniksi   

Best Fiends 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mobiilipelit](http://www.yso.fi/onto/yso/p15342) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

tarvitaan aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The world of best fiends 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Best Fiends (peli)](http://finto.fi/yse/fi/page/Y506619)

**Comment by mariaforsen** [comment]
Onko muitakin Best Fiendsejä kuin pelejä? Vai minkä takia sulkutarkenne?
