### ISSUE TITLE
Pyhän Nikolaoksen tsasouna (Suomussalmi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6622]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän Nikolaoksen tsasouna (Suomussalmi) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tsasounat](http://www.yso.fi/onto/yso/p15991) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kuivajärven rukoushuoneen ikonostaasi, osana Martha Neiglick-Platonoffin tuotantoa 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Pyhän Nikolaoksen tsasouna (Suomussalmi)](http://finto.fi/yse/fi/page/Y506622)

**Comment by jtuohini** [comment]
Ja KT-muodoksi toki tuo _Kuivajärven rukoushuone_.

**Comment by mariaforsen** [comment]
Sv. Pyhän Nikolaoksen tsasouna (Suomussalmi)
