### ISSUE TITLE
kattokruunut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6623]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kattokruunut 

#### Ehdotettu termi ruotsiksi   

ljuskronor 

#### Ehdotettu termi englanniksi   

chandeliers 

#### Vaihtoehtoiset termit ja ilmaisut   

kristallikruunut 
kynttiläkruunut 

#### Ehdotettu yläkäsite YSOssa (LT)   

[valaisimet](http://www.yso.fi/onto/yso/p2099) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85022496> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suomen messinkiset kynttiläkruunut ja niiden yläfiguurit 1400-luvulta 1700-luvun loppuun 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kattokruunut](http://finto.fi/yse/fi/page/Y506623)

**Comment by mirmaid** [comment]
MAO-ontologiassa, 5 viitettä Melindassa.
