### ISSUE TITLE
Lahti -- Kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6624]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Lahti -- Kartano 

#### Ehdotettu termi ruotsiksi   

Lahtis -- Kartano [?] 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q11870201 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hj. Åberg: Lahden kartano 

#### Tarkoitusta täsmentävä selite   

Kaupunginosa Lahdessa; saanut nimensä "Lahden kartanosta", nykyisestä "Fellmanin kartanosta". 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Lahti -- Kartano](http://finto.fi/yse/fi/page/Y506624)

**Comment by ilona-x** [comment]
Lisätty YSAan Lahti -- Kartano.
