### ISSUE TITLE
Fellmanin kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6625]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Fellmanin kartano 

#### Ehdotettu termi ruotsiksi   

Fellmanska huset 

#### Ehdotettu termi englanniksi   

Lahti Manor 

#### Vaihtoehtoiset termit ja ilmaisut   

Lahden kaurtano 
Lahtis gård 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q5479146 

#### Tarkoitusta täsmentävä selite   

Kartano Lahden Kartanon kaupunginosassa. 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hj. Åberg: Lahden kartano 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Fellmanin kartano](http://finto.fi/yse/fi/page/Y506625)

**Comment by mariaforsen** [comment]
Sv. Lahtis gård
