### ISSUE TITLE
estetismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6626]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[estetismi](http://www.yso.fi/onto/ysa/Y179744) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko kaksi merkitystä? 

#### Perustelut ehdotukselle   

Huomautus: Sanalla on kaksi merkitystä. 1) Yksipuolisesti esteettiseen suhtautumiseen ja nautiskeluun pohjautuva elämänkatsomus. 2) Taiteen suuntaus, joka keskittyy siihen, että taide on olemassa pelkästään sen kauneuden takia, ja että taiteen ei tarvitse palvella poliittista, didaktista tai muuta tarkoitusta

Jaettu YSOssa

**Comment by mirmaid** [comment]
YSOssa _estetismi (aatteet)_ ja _estetismi (tyylit)_. 11 viitettä Melindassa, yhdessä (luultavasti) ensimmäisessä merkityksessä.

**Comment by mariaforsen** [comment]
SAO: esteticism (litteratur), esteticism (konst), mutta NE:ssä aatteet-merkityksessä (onko pohjimmiltaan kyse melkein samasta asiasta, mutta sovellettuna eri alueilla..?)

**Comment by tpalonen** [comment]
Käytännön kannalta näyttäisivät ehkä olevan riittävän lähellä toisiaan, että voisi säilyttää yhdessä.

**Comment by YSA-kokous** [comment]
Ei muutosta.
