### ISSUE TITLE
portaalit (arkkitehtuuri)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6628]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

portaalit (arkkitehtuuri) 

#### Ehdotettu termi ruotsiksi   

portaler (arkitektur) 

#### Ehdotettu termi englanniksi   

portals 

#### Ehdotettu yläkäsite YSOssa (LT)   

[arkkitehtuuri](http://www.yso.fi/onto/yso/p8025) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85039070> 
Wikidata : https://www.wikidata.org/wiki/Q854429 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tiilen käytöstä Suomen keskiaikaisten kirkkojen portaaleissa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [portaalit (arkkitehtuuri)](http://finto.fi/yse/fi/page/Y506628)

**Comment by mirmaid** [comment]
MAO-ontologiassa, Melindan viitteet näyttävät liittyvän tietotekniikkaan silloinkin kun tarkenne puuttuu.
