### ISSUE TITLE
kvanttitietokoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#663]
#### Ehdotettu termi suomeksi

kvanttitietokoneet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/ysa/ryhma_43)

**Luontipäivämäärä:** 12.09.2001

**Muokkauspäivämäärä:** 12.9.2001, 16.12.2008

**Voyager-id:** 115179

**Termiehdotus Fintossa:** [kvanttitietokoneet](http://finto.fi/yse/fi/page/Y315179)

**Comment by marajaho** [comment]
Nostaisin tällaisen hyvin vanhan ehdotuksen uudestaan käsiteltäväksi:
https://fi.wikipedia.org/wiki/Kvanttitietokone

Ehkä on lähempänä realisoitumista, kuin vuosituhannen alussa.

Englanniksi "quantum computers" ja ruotsiksi "kvantdatorn"

Melindasta löytyy aiheesta ainakin englanninkielellä.

Matti R.
JYU

**Comment by mirmaid** [comment]
Melindassa 4 viitettä.

LCSH: Quantum computers
SAO: kvantdatorer

https://fi.wikipedia.org/wiki/Kvanttitietokone

**Comment by mariaforsen** [comment]
Sv. kvantdatorer

**Comment by vilkkier** [comment]
Uudelleen käsiteltäväksi. Kvanttitietokoneista on julkaisuja. Itselläni "Control of heat in superconducting microwave circuits". Tekstistä: "Kvanttitietokoneilla voitaneen tulevaisuudessa ratkaista monia nykyisille tietokoneille mahdottomia tehtäviä, mistä olisi merkittävästi hyötyä esimerkiksi uusien lääkkeiden ja kestävien materiaalien kehityksessä. Siten kvanttiteknologioiden kehittämisellä tulee olemaan kauaskantoisia vaikutuksia monilla yhteiskunnan osa-alueilla." Googlella löytyi jotain 47 000 osumaa. Wikipediassakin on artikkeli.

**Comment by ilona-x** [comment]
Mitähän tälle on aikanaan tapahtunut, kun näyttäisi jo saaneen hyväksytty-labelin. 👀 Termille olisi ollut käyttöä väitöskirjan "Heat transport in superconducting quantum circuits " kuvailussa.

**Comment by vilkkier** [comment]
Hei!

Luulin että se vain siirtyi seuraavaan kokoukseen?

t. Kiti


Lähettäjä: Ilona <notifications@github.com>
Lähetetty: 9. kesäkuutata 2020 15:39
Vastaanottaja: Finto-ehdotus/YSE <YSE@noreply.github.com>
Kopio: Vilkki-Eriksson, Kiti A K <kiti.vilkki-eriksson@helsinki.fi>; Comment <comment@noreply.github.com>
Aihe: Re: [Finto-ehdotus/YSE] kvanttitietokoneet (#663)


Mitähän tälle on aikanaan tapahtunut, kun näyttäisi jo saaneen hyväksytty-labelin. 👀 Termille olisi ollut käyttöä väitöskirjan "Heat transport in superconducting quantum circuits " kuvailussa.

**Comment by mirmaid** [comment]
Ei kyllä käsitystä mitä v. 2017 on tapahtunut :monocle_face:. Nyt Melindassa 49 viitettä (Arto lienee loadattu tuon 2017 lukeman jälkeen).

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
