### ISSUE TITLE
bakeliitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6631]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bakeliitti 

#### Ehdotettu termi englanniksi   

bakelite 

#### Ehdotettu termi ruotsiksi   

bakelit 

#### Vaihtoehtoiset termit ja ilmaisut   

baekelite [eng] 
polyoxybenzylmethyleneglycolanhydride [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kertamuovi](http://www.yso.fi/onto/yso/p12289) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85011072> 
Wikidata : https://www.wikidata.org/wiki/Q146578 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Bakeliitti ja moderni muotokieli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[30 Kemianteollisuus. Keraaminen teollisuus. Lasiteollisuus. Muoviteollisuus. Kumiteollisuus](http://www.yso.fi/onto/yso/p26530) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [bakeliitti](http://finto.fi/yse/fi/page/Y506631)

**Comment by mirmaid** [comment]
MAO-ontologiassa, 7 viitettä Melindassa.
