### ISSUE TITLE
pueblointiaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6632]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pueblointiaanit 

#### Ehdotettu termi englanniksi   

Pueblo Indians 

#### Ehdotettu termi ruotsiksi   

Puebloindianer 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85108902> 
Wikidata : https://www.wikidata.org/wiki/Q852431 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jatkuvuus ja muutos pueblointiaanien keramiikkaperinteessä 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [pueblointiaanit](http://finto.fi/yse/fi/page/Y506632)

**Comment by jarmosaarikko** [comment]
LT intiaanit 
yksikään LOC käsitteen alakäsitteistä ei löydy meiltä intiaanit alakäsitteinä

**Comment by mirmaid** [comment]
Wikipediassa pueblo-kulttuuri, Melindassa 35 viitettä pueblointiaanit.

**Comment by krinay** [comment]
Melindassa lisäksi asiasana _pueblot_ 31 kertaa. Kannatan termimuotoa _pueblointiaanit_.
