### ISSUE TITLE
kasvotutkielmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6634]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kasvotutkielmat 

#### Ehdotettu termi englanniksi   

tronies 

#### Ehdotettu termi ruotsiksi   

tronier 

#### Vaihtoehtoiset termit ja ilmaisut   

troniet 

#### Assosiatiiviset (RT)   

[muotokuvat](http://www.yso.fi/onto/yso/p5600) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q1433099 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Das Tronie : Muster, Studie und Meisterwerk : die Genese einer Gattung der Malerei vom 15. Jahrhundert bis zu Rembrandt 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kasvotutkielmat](http://finto.fi/yse/fi/page/Y506634)

**Comment by jtuohini** [comment]
Ja LT-muodoksi "maalaukset" ja toiseksi RT-muodoksi "luonnokset" (tipahtivat jostain syystä pois, vaikka lomakkeella olivatkin)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by YSA-kokous** [comment]
Kumpi päätermiksi?

**Comment by MikkoAleksanteri** [comment]
suomenkielisessä Wikipediassa "Tronie": https://fi.wikipedia.org/wiki/Tronie

**Comment by jtuohini** [comment]
Museoissa ainakin käytetään ilmaisua "kasvotutkielma", ks. https://www.finna.fi/Search/Results?lookfor=kasvotutkielma&type=AllFields (306 osumaa) ja https://www.finna.fi/Search/Results?lookfor=tronie*&type=AllFields (12 osumaa)
