### ISSUE TITLE
nikotiinituotteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6635]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nikotiinituotteet 

#### Ehdotettu termi ruotsiksi   

nikotinprodukter 

#### Ehdotettu termi englanniksi   

nicotin products 

#### Ehdotettu yläkäsite YSOssa (LT)   

[nikotiini](http://www.yso.fi/onto/yso/p4846) 

#### Alakäsitteet (RT)   

[nuuska](http://www.yso.fi/onto/yso/p10020) 
[sähkösavukkeet](http://www.yso.fi/onto/yso/p26462) 

#### Assosiatiiviset (RT)   

[riippuvuus](http://www.yso.fi/onto/yso/p9414) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Kuluttajille tarkoitetut nikotiinia sisältävät tuotteet; ei teollisuuteen yms tarkoitetut nikotiinia sisältävät aineet 

#### Perustelut ehdotukselle   

Nikotiinia on useissa erilaisissa tupakka- ja savuketuotteissa. Kattotermi näille voisi olla paikallaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Käsite olisi tarpeellinen Suomi.fi-palvelutietovarannossa, josta se on rajattomasti erilaisten palvelujen käytössä. 

**Ehdottajan organisaatio:** Väestörekisterikeskus **Termiehdotus Fintossa:** [nikotiinituotteet](http://finto.fi/yse/fi/page/Y506635)

**Comment by mirmaid** [comment]
Ei Melindassa, Google n. 10000

**Comment by ilona-x** [comment]
YSA:an otettu v. 2016 tupakkatuotteet http://finto.fi/ysa/fi/page/Y207778

**Comment by YSA-kokous** [comment]
Kysytään ehdottajalta
