### ISSUE TITLE
metsäsuhde

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6636]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsäsuhde 

#### Perustelut ehdotukselle   

Luontosuhde meillä on, mutta "Metsä erityisenä luonnon- ja kulttuuriympäristönä erottaa metsäsuhteen selkeästi luontosuhteesta" 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://issuu.com/luston_julkaisuja/docs/metsasuhteiden_kentta 

**Termiehdotus Fintossa:** [metsäsuhde](http://finto.fi/yse/fi/page/Y506636)

**Comment by jarmosaarikko** [comment]
LT luontosuhde

**Comment by mirmaid** [comment]
Kolme kertaa Melindassa vähän eri variaatioina. _Luontosuhde_ & _metsät_ yhdistelmää on runsaasti, ketjuna 19 kertaa.

**Comment by EsaMPKK** [comment]
Googlessa 8900 osumaa.

**Comment by mariaforsen** [comment]
Mikä tämä mahtaa olla englanniksi? Voi olla vaikeaa kääntää ruotsiksi. Kun painaa googletulokset loppuun asti ilmenee että osumia on n. 117.

**Comment by satuniininen** [comment]
Englanniksi käytetään ainakin muotoja _relation to forests_  ja _human-forest relationship_. 

Hieman vierastan tälle tarkkuustasolle menevää käsitteistöä, kun saman voisi ilmaista myös yhdistelmällä luontosuhde + metsät.

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tässä: https://lusto.fi/wp-content/uploads/2022/12/Lusto-Vuosilusto14.pdf

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. skogsrelation HT relation till skog, förhållande till skog, skogsförhållande
jfr https://finto.fi/yso/fi/page/p16315
https://mmm.fi/sv/vardesattning-av-skog
https://www.kansalliskirjasto.fi/sv/nyheter/finna-gratulerar-100-ariga-finland
https://valtioneuvosto.fi/sv/-//1410837/suomalaisten-suhde-metsaan-on-moninainen-uusi-metsasuhdemenetelma-auttaa-ymmartamaan-erilaisia-arvostuksia
https://www.finlit.fi/sites/default/files/mediafiles/arkisto-_ja_kirjastopalvelut/metsasuhde_sv_0.pdf
