### ISSUE TITLE
taiteenopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6638]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taiteenopettajat 

#### Ehdotettu termi englanniksi   

art teachers 

#### Ehdotettu termi ruotsiksi   

konstlärare 

#### Vaihtoehtoiset termit ja ilmaisut   

piirustuksenopettajat 
kuvaamataidonopettajat 
maalauksenopettajat 
kuvaamataiteenopettajat 
taideopettajat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[opettajat](http://www.yso.fi/onto/yso/p1117) 

#### Assosiatiiviset (RT)   

[taiteen perusopetus](http://www.yso.fi/onto/yso/p21985) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85008085> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Keisarillisen Aleksanterin-yliopiston piirustuksenopettajan virantäyttö vuosina 1829 ja 1830 : virkanimityksen perusteet / Marjut Huttunen 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [taiteenopettajat](http://finto.fi/yse/fi/page/Y506638)

**Comment by mirmaid** [comment]
YSAssa on nyt _kuvataideopettajat_.

**Comment by YSA-kokous** [comment]
Ei muutosta
