### ISSUE TITLE
liturgiset asut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6639]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

liturgiset asut 

#### Ehdotettu termi englanniksi   

vestments 

#### Vaihtoehtoiset termit ja ilmaisut   

liturginen vaatetus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[asusteet](http://www.yso.fi/onto/yso/p10459) 

#### Assosiatiiviset (RT)   

[virkapuvut](http://www.yso.fi/onto/yso/p14726) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85025774> 
Wikidata : https://www.wikidata.org/wiki/Q6501052 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ortodoksisesta liturgisesta puvustosta / Erika Hyyryläinen 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [liturgiset asut](http://finto.fi/yse/fi/page/Y506639)

**Comment by jarmosaarikko** [comment]
kyllä tämä kai on ihan varteenotettava asiasana. Näitä olisi kai kasukat, stolat, liperit, hiipat jne.  joita ei ole YSAssa

**Comment by mirmaid** [comment]
MAO-ontologiassa muodossa _liturgiset vaatteet_, 8 viitettä Melindassa (kerran liturgiset asut).

**Comment by mariaforsen** [comment]
Kannatan ruotsin osalta liturgiset vaatteet=liturgiska kläder. https://sv.wikipedia.org/wiki/Liturgiska_kl%C3%A4der

**Comment by YSA-kokous** [comment]
liturgiset vaatteet
