### ISSUE TITLE
Helsinki -- Taka-Töölö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6641]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Helsinki -- Taka-Töölö 

#### Ehdotettu termi ruotsiksi   

Helsingfors -- Bortre Tölö 

#### Ehdotettu termi englanniksi   

Helsinki -- Taka-Töölö 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q3514122 

#### Tarkoitusta täsmentävä selite   

Helsingin 14. kaupunginosa. 

#### Perustelut ehdotukselle   

On virallinen kaupunginosa ja täsmällisempi kuin sen ja 13. kaupunginosan kattava "Helsinki -- Töölö", josta toki tulisi LT-muoto. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Helsinki -- Taka-Töölö](http://finto.fi/yse/fi/page/Y506641)

**Comment by mirmaid** [comment]
Taka-Töölö käytetty Melindassa kolme kertaa, Etu-Töölö yhdeksän kertaa (Töölö (Helsinki) 324 kertaa).

**Comment by YSO-kokous** [comment]
Otetaan sanastoon Taka-Töölö ja Etu-Töölö. Yläkäsitteeksi Töölö.
