### ISSUE TITLE
Ajanta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6642]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ajanta 

#### Ehdotettu termi ruotsiksi   

Ajanta 

#### Ehdotettu termi englanniksi   

Ajanta 

#### Vaihtoehtoiset termit ja ilmaisut   

Adzanta 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n81059920> 
Suomenkielinen Wikipedia : https://fi.wikipedia.org/wiki/Ajanta 

#### Tarkoitusta täsmentävä selite   

Kylä Maharashtran osavaltiossa Intiassa 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Adzantan luola yhden Bodhisattva-fresko / Leena Iitiä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Ajanta](http://finto.fi/yse/fi/page/Y506642)

**Comment by jtuohini** [comment]
Pari teosta lisää, jotka käsittelevät nimenomaan kyseistä paikkaa, ei laajemmalti lääniä tai osavaltiota tai koko valtiota:

- https://helka.finna.fi/Record/helka.1427792
- https://helka.finna.fi/Record/helka.2757859
- https://helka.finna.fi/Record/helka.2162408
- https://helka.finna.fi/Record/helka.796346
- https://helka.finna.fi/Record/helka.1022312
- https://helka.finna.fi/Record/helka.505452
- https://helka.finna.fi/Record/helka.910904

jne.

Kyse ei siitä, onko paikkakunnalla maailmanperintökohde vai ei, vaan siitä, että paikkakuntaa käsittelevää aineistoa pitäisi pystyä kuvailemaan täsmällisesti.

**Comment by mirmaid** [comment]
LCSH: Ajanta (India) & Ajanta Caves (India)

_The Ajanta Caves are 30 (approximately) rock-cut Buddhist cave monuments which date from the 2nd century BCE to about 480 CE in Aurangabad district of Maharashtra state of India._ https://en.wikipedia.org/wiki/Ajanta_Caves

**Comment by YSO-kokous** [comment]
Otetaan YSO-paikkoihin muodossa Ajantan luolat. Ohjaustermiksi Ajanta. Kuvailu on käsitellyt luolia, ei niinkään Ajantan kylää.

**Comment by jtuohini** [comment]
Ja toiseksi ohjaustermiksi varmaan _Adzantan luolat_, jota muotoa suomeksi myös käytetään (ks. alkuperäisessä ehdotuksessa mainittu teos)?
