### ISSUE TITLE
opettajanoppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6644]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

opettajanoppaat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Tarkoitusta täsmentävä selite   

Opettajan käyttööön tarkoitettu opas. Tarvitaan SLM-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2920155 

#### Perustelut ehdotukselle   

.. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [opettajanoppaat](http://finto.fi/yse/fi/page/Y506644)

**Comment by mariaforsen** [comment]
Lärarhandledningar (opetusoppaat) onkin jo sanastossa ja se on sama asia.

**Comment by YSA-kokous** [comment]
KÄ opetusoppaat

**Comment by mirmaid** [comment]
Opetusoppaat myös SLM-sanastoon.
