### ISSUE TITLE
alakoululaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6645]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alakoululaiset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[koululaiset](http://www.yso.fi/onto/yso/p16485) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Tarvitaan kohderyhmän määrittelyyn (kenttä 385), varsinkin oppikirjojen kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2915562 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [alakoululaiset](http://finto.fi/yse/fi/page/Y506645)

**Comment by mariaforsen** [comment]
Sv. lågstadieelever
