### ISSUE TITLE
yläkoululaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6646]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yläkoululaiset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[koululaiset](http://www.yso.fi/onto/yso/p16485) 

#### Perustelut ehdotukselle   

Tarvitaan kohderyhmän määrittelyyn (kenttä 385), varsinkin oppikirjojen kuvailussa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2389946 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [yläkoululaiset](http://finto.fi/yse/fi/page/Y506646)

**Comment by mariaforsen** [comment]
Sv. högstadieelever
