### ISSUE TITLE
kalamajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6649]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kalamajat 

#### Ehdotettu termi englanniksi   

fishing huts 

#### Ehdotettu termi ruotsiksi   

fiskestugor 

#### Vaihtoehtoiset termit ja ilmaisut   

kalastusmajat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[majat](http://www.yso.fi/onto/yso/p2254) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2010008142> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[23 Erätalous. Kalastus. Metsästys](http://www.yso.fi/onto/yso/p26561) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kalamajat taidehistoriallisena turkimuskohteena / Tuija Mikkonen 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kalamajat](http://finto.fi/yse/fi/page/Y506649)

**Comment by mariaforsen** [comment]
Sv. fiskarstugor ET fiskarkojor, fiskestugor, fiskekojor
