### ISSUE TITLE
työssäoppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6650]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työssäoppiminen](http://www.yso.fi/onto/ysa/Y111678) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

työpaikalla kouluttautuminen 

#### Perustelut ehdotukselle   

Laki ammatillisesta koulutuksesta tuli voimaan 1.1.2018 ja sen myötä työssäoppimisesta tuli työpaikalla kouluttautumista, kouluttautuminen löytyi kyllä sanahausta. Opinnäytetyöni käsittelee aihetta.

**Comment by mariaforsen** [comment]
Kielitoimiston sanakirja: työssäoppiminen=toisen asteen ammatilliseen koulutukseen kuuluva opiskelun osa, joka järjestetään työtehtävissä alan työpaikassa. Onko se edelleen sama asia siinä tapauksessa? Tämä uusi ehdotettu muoto ei löydy googlesta. Millä nimellä se sitten kutstutaan yllä mainitussa laissa?

**Comment by ilona-x** [comment]
https://www.finlex.fi/fi/laki/alkup/2017/20170531
Lain 8-luvun otsikko:
fin Työpaikalla järjestettävä koulutus
swe Utbildning som ordnas på en arbetsplats


https://minedu.fi/tyopaikalla-oppiminen

**Comment by YSA-kokous** [comment]
työpaikalla kouluttautuminen, työpaikalla oppiminen KÄ työssäoppiminen
