### ISSUE TITLE
vaikea kulttuuriperintö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6652]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaikea kulttuuriperintö 

#### Ehdotettu termi englanniksi   

difficult heritage 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuuriperintö](http://www.yso.fi/onto/yso/p8475) 

#### Vastaava käsite muussa sanastossa   

KEKO : <http://finto.fi/keko/fi/page/p117> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Kestävän kehityksen ontologian määritelmä ja huomautus:
Historiaan liittyvä sellainen aineellinen ja aineeton kulttuuriperintö, joka ei sovi yksioikoisesti niiden ryhmien identiteettiin, joiden menneisyyteen tai historiaan kulttuuriperintö liittyy ...
Vaikea kulttuuriperintö synnyttää usein positiivisten mielikuvien sijasta negatiivisesti värittyneitä mielikuvia. Vaikeaa kulttuuriperintöä ovat esimerkiksi sotien tapahtumat. 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3155322 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [vaikea kulttuuriperintö](http://finto.fi/yse/fi/page/Y506652)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5527

**Comment by krinay** [comment]
Ohjaustermiksi synkkä kulttuuriperintö (dark heritage)?
