### ISSUE TITLE
äänentallennus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6653]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänentallennus](http://www.yso.fi/onto/ysa/Y100504) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan käytettäväksi asiasanaksi muoto "äänittäminen" ja nykyinen muoto KT:ksi. 

#### Perustelut ehdotukselle   

YSO:n musiikkitermikokouksessa todettiin, että nykyinen asiasana "äänentallennus" kuulostaa vieraannuttavalta verrattuna arkikielisempään "äänittäminen"-muotoon. Samalla termipari muuttuisi nykyistä loogisemmaksi: "äänittäminen" (KT "äänentallennus", "äänitys") viittaisi prosessiin itseensä ja "äänitteet" (KT äänitallenteet) prosessiin lopputulokseen. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa ehdotusta YSAan.

**Comment by LeKorsu** [comment]
Kannatan. Äänittäminen sopii myös muuhun kuin musiikin äänittämiseen. En näe ongelmaa esim. Äänityön kivijalka -teoksen äänentallennuksen muuttamisesta äänittämiseksi. Ammattinimikekin on äänittäjä, ei äänentallentaja.
