### ISSUE TITLE
äänitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6654]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänitykset](http://www.yso.fi/onto/ysa/Y214742) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan asiasanana tai muutetaan se yksiselitteiseen muotoon, esim. "äänityssessiot". 

#### Perustelut ehdotukselle   

Asiasanan nykyinen käyttöohje "Termiä voi käyttää myös konkreettisista äänitysprosessien tuotteista, varsinkin yksittäisen artistin tietylle levymerkille tekemistä äänityksistä koottuja kokoelmia indeksoitaessa, esimerkiksi Complete Sun Recordings. Termiä voi käyttää myös yksittäisestä sävellyksestä tehtyjä versioita sisältävän kokoomajulkaisun yhteydessä." ei ole linjassa asiasanan itsensä kanssa. Olisiko "musiikkiesitysten versiot" tai vastaava parempi korvike? (Näennäinen) ristiriita asiasanaan "äänitteet" pitäisi myös saada ratkaistua. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilonahei** [comment]
En kannata poistamista, koska termiä on käytetty paljon, ja enimmäkseen juuri "äänityssessiot"-merkityksessä.

**Comment by asormune** [comment]
Kannatan "äänityssessioille" termiä. Mutta myös "musiikkiesitysten versiot" merkityksessä on "äänityksiä" käytetty. Jonkinverran on käytetty ennemminkin kuvaamaan äänentallennusta, eli tarkennettava.

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa käytettävän termin muuttamista muotoon YSAssa "äänityssessiot" siten että "äänitykset" ei jäisi myöskään ohjaustermiksi. Pohdimme myös, että ohjaustermiksi voisi lisätä "studiosessiot", mutta jäimme miettimään, voiko tämän sekoittaa esim. valokuvaamiseen tai johonkin muuhun - tähän kaipaisimme YSA-kokouksen kantaa. Muusa ei siis vaadi "studiosessiot"-ohjaustermin lisäämistä.

**Comment by LeKorsu** [comment]
Musaeksperttikollegoitteni kommentteja tässä: äänityssessiot sopii populaarimusiikin puolelle, mutta kuulostaa vieraalta taidemusiikin kohdalla.  Sinfoniaorkesteri ei istu äänityssessiossa vaan äänittämässä. Musiikkiesitysten versiot kuulostaa keinotekoiselta. 
Oma kanta: Jos tarkoitus on yhdellä ja samalla termillä kuvata eri musiikinaloja, olemassaoleva äänitykset on parempi kuin ehdotettu äänityssessiot.

**Comment by mariaforsen** [comment]
Ongelma on kuitenkin se että "äänitykset" on monimerkityksinen termi (ja sitä ei saisi sekoittaa äänitteet-termiin). Eli jos "äänitykset" jää se pitäisi sitten selkeyttää tarkenteella, joka erottaisi sitä äänite-merkityksestä.
Ks. Kielitoimiston sanakirja: äänitys=äänittäminen; sen tulos, äänite.
