### ISSUE TITLE
niloottiset kansat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6655]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

niloottiset kansat 

#### Ehdotettu termi englanniksi   

Nilotic peoples 

#### Vaihtoehtoiset termit ja ilmaisut   

nilootit (eng Nilotes) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansat (väestöryhmät)](http://www.yso.fi/onto/yso/p3993) 

#### Alakäsitteet (RT)   

[maasait](http://www.yso.fi/onto/yso/p16087) 

#### Vastaava käsite muussa sanastossa   

LCSH : <Nilotic peoples: http://id.loc.gov/authorities/subjects/sh85091963> 
Wikipedia : Nilootit: https://fi.wikipedia.org/wiki/Nilootit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Wikipedia:
"Nilootit on yhteisnimitys lukuisille Afrikan koillisosasta, Niilijoen seudulta lähtöisin oleville kansoille, joiden pääasiallinen asuma-alue sijaitsee tätä nykyä Sudanin, Etelä-Sudanin, Kenian, Ugandan Somalian, Egyptin ja Eritrean maiden alueella. Vanhastaan niloottien on katsottu polveutuvan seemiläisistä tai haamilaisista, ja heidän on katsottu olevan ruumiinrakenteeltaan pitkiä ja hoikkia. He puhuvat nilosaharalaisia kieliä. Tunnettuja niloottikansoja ovat mm. dinkat, kalenjinit, luot, maasait, nuerit, himat ja turkanat.
1900-luvun lopussa nilootteja oli noin seitsemän miljoonaa." 

#### Perustelut ehdotukselle   

Käytetty Melindassa YSA-terminä 5 kertaa, lisäksi käytetty termiä nilootit 7 kertaa.
YSA:ssa on termi niloottiset kielet. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Animism of the Nilotics and discourses of Islamic fundamentalism in Sudan (2010), 

**Ehdottajan organisaatio:** SKS:n kirjasto **Termiehdotus Fintossa:** [niloottiset kansat](http://finto.fi/yse/fi/page/Y506655)

**Comment by mariaforsen** [comment]
Sv. nilotiska folk ET niloter
