### ISSUE TITLE
hausat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6656]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hausat 

#### Ehdotettu termi englanniksi   

Hausa 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansat (väestöryhmät)](http://www.yso.fi/onto/yso/p3993) 

#### Vastaava käsite muussa sanastossa   

LCSH : <Hausa (African people): http://id.loc.gov/authorities/subjects/sh85059316> 
Wikipedia : hausat: https://fi.wikipedia.org/wiki/Hausat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Wikipedia:
"Hausat ovat Länsi-Afrikan suurin etninen ryhmä. Suurin osa heistä asuu Hausamaana tunnetulla alueella, joka ulottuu Pohjois-Nigeriasta Saharan autiomaalle pohjoisessa, Tšadjärvelle idässä ja Nigerjoelle etelässä. Hausoja asuu myös ympäri muuta Afrikkaa kauppiaina. Hausat puhuvat afroaasialaisiin kieliin kuuluvaa hausan kieltä, jota osataan Länsi-Afrikassa laajalti johtuen hausojen historiallisesta merkityksestä kauppiaina.Kä" 

#### Perustelut ehdotukselle   

Käytetty asiasanana Melindassa 12 kertaa.
YSAssa on termi hausan kieli. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Gender and citizenship : Hausa women's political identity from the caliphate to the protectorate (2006) 

**Ehdottajan organisaatio:** SKS:n kirjasto **Termiehdotus Fintossa:** [hausat](http://finto.fi/yse/fi/page/Y506656)

**Comment by mariaforsen** [comment]
Sv. hausa (folk)
