### ISSUE TITLE
altto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6657]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[altto](http://www.yso.fi/onto/ysa/Y214389) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotus koskee kaikkia äänialakäsitteitä: altto, baritoni, basso, kontratenori, mezzosopraano, sopraano, tenori. Näille termeille olisi hyvä lisätä sulkutarkenne (äänialat). 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

Sulkutarkenteen avulla eivät mene sekaisin laulajakäsitteiden kanssa. YSOn puolella tällainen sulkutarkenne on jo näille lisätty.

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa ehdotusta. YSAan.
