### ISSUE TITLE
punarinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6658]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

punarinta 

#### Ehdotettu termi ruotsiksi   

rödhake 

#### Ehdotettu termi englanniksi   

european robin 

#### Ehdotettu yläkäsite YSOssa (LT)   

[siepot](http://www.yso.fi/onto/yso/p1155) 

#### Vastaava käsite muussa sanastossa   

LCSH : European robin 
Svenska ämnesord : Rödhake 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Käytetty Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Syksyn seuralainen. 

**Termiehdotus Fintossa:** [punarinta](http://finto.fi/yse/fi/page/Y506658)

**Comment by PaiviLipsanen** [comment]
Tieteellinen nimi: Erithacus rubecula 
Erithacus-suvulla ei ole suomenkielistä nimeä
Yläkäsite: siepot (heimo - Muscicapidae)
https://laji.fi/taxon/MX.32800
