### ISSUE TITLE
ratapenkereet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6659]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ratapenkereet 

#### Ehdotettu termi ruotsiksi   

banvallar 

#### Ehdotettu termi englanniksi   

railway beds 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Perustelut ehdotukselle   

Toistuvasti tarpeen Liikenneviraston julkaisujen kuvailussa. Yhdistelmän rautatiet + pengerrykset tilalle. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ratapenkereen leveys ja luiskakaltevuus, http://urn.fi/URN:ISBN:978-952-255-298-3 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ratapenkereet](http://finto.fi/yse/fi/page/Y506659)

**Comment by ilona-x** [comment]
YSA:ssa on pengerrykset http://www.yso.fi/onto/ysa/Y103341 

Melinda:
ratapenkereet x 1
penkereet x 12
tien penkereet x 6
siltapenkereet x 1
rantapenkereet x 3

**Comment by mariaforsen** [comment]
Pengerrykset=terassering ei käy ruotsin osalta tähän, se on aivan eri asia.  Tosin tutkittava mihin kaikkeen tarkalleen pengerrykset viittaa YSAssa (kielitoimiston mukaan useampia merkityksiä...) ja harkittava onko nykyinen vastine paras mahdollinen. 

MOT: pengerrys: 
1 (pengertäminen) terrassering [-en], (vallitus) invallning, indämning
2 (valli) vall [-en, -ar], (vars yhd) -bank [-en, -ar], (pato) fördämning [-en, -ar]

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by ilona-x** [comment]
**pengerrys**
1. pengertäminen. Puutarhan ojitus ja pengerrys.
2. keinotekoinen penger. 

**penger**
1. jyrkähkö törmä t. reuna; myös rinteessä olevasta (kapeahkosta) tasanteesta; vrt. penkka, pengermä, terassi. Jyrkkä penger. Hiekkapenger. Rantapenger. Rinteessä on penkereitä. Istua ojan penkereellä pientareella.
2. maasta, kivestä tms. tehty t. syntynyt tasaharjainen valli, pato; tie- ja vesirakennustekniikassa: pitkänomainen maa- t. kivitäyte, jonka päälle tie t. rautatie rakennetaan. Viljelysmaiden kuivaamiseksi rakennetut penkereet. Radan penger, ratapenger. Penkereen harja, luiskat.

**Comment by ilona-x** [comment]
LCSH: Embankments http://id.loc.gov/authorities/subjects/sh85042664
SAO: Invallning

Melinda: terassering (allars) x 3

**Comment by YSA-kokous** [comment]
ratapenkereet? Mahd. muuta suppeampaa...pengerrykset (viherrakentaminen)?

**Comment by ilona-x** [comment]
Melindassa pengerrykset käytetty 155 kertaa + ketjut, joista seuraavissa merkityksissä:
**pengerrykset (viherrakentaminen)** Melinda: 64/155
**ratapenkereet** Melinda: 14/155

pengerrykset (maarakennus?) -tarvitaanko erikseen & onko selkeästi eri asia kuin viherrakentamisen pengerrykset vai riittäisikö yksi pengerrykset (maarakennus), joka kattaisi myös viherrakentamisen?

pengerrykset (tienrakennus?) / tienpenkereet

pengerrysalueet?
https://www.ely-keskus.fi/web/tulvatpohjanmaa/tulvavaroituspalvelu

Alla esimerkkejä Melinda-viitteistä:

tienrakennus, tiepenkereet + sillat:

- Tiepenkereiden ja -leikkausten suunnittelu :tien pohjarakenteiden suunnitteluohjeet.
- Tiepenkereen holvautuminen.Loppuraportti 
- Maanvarainen tiepenger savikolla :suunnitteluohje.
- Tienrakennustöiden yleiset laatuvaatimukset ja työselitykset.Penger- ja kerrosrakenteet.
- Tiepenkereiden vetolujitteiden toiminta käyttötilassa
- Tiepenkereen siirtymärakenteet pehmeiköllä.
- Uusien tietyyppien ulkonäkötarkastelut :S12 Pääteiden parantamisratkaisut.
- TYLT-kansio /Tienrakennustöiden yleiset laatuvaatimukset ja työselitykset 
- Inverkan av vägbankar på vattenmiljön 
- Lounais-Suomen rannikon tiepengerinventointi 
- Geovahvisteet tiepenkereen leventämisessä pehmeiköllä
- Reunaympäristön pehmentäminen :suunnittelun vaiheistus ja sisältö : suunnitteluvaiheen ohjaus
- Reunaympäristön pehmentäminen :invedntoinnin työohje : suunnitteluvaiheen ohjaus.
- Kokeellisia tutkimuksia kevytsorabetonirakenteiden kantavuudesta ja rasituskestävyydestä
- Paalulaattarakenteiden suunnittelu
- Louhepenkereen syvätiivistys 
- Massanvaihdon suunnittelu :tien pohjarakenteiden suunnitteluohjeet.
- Haarajoen koepenkereen painumalaskentakilpailu :loppuraportti.
- Haarajoen koepenger :maaperän lujittumistutkimus 
- Geovahvisteiden toiminta harvennetun syvästabiloinnin varaisessa tiepenkereessä
- Modelling of anisotropic behaviour of clays :test embankment in Murro, Seinäjoki, Finland 
- Stabiloidun kevytsoran käyttösovellutuksia tierakenteissa
- Teräsverkon käyttö penkereen lujitteena 
- Syvästabiloinnin koerakennuskohde Helsingissä 
- Pengerlaatat.
- Pengerpaalutus.
- Hännilänsalmen sillan tulopenkereiden rakentaminen 
- Pengertiet nopeuttavat rantojen umpeenkasvua :pienet virtausaukot eivät riitä.
- Мосты Ленинграда :очерки истории и архитектуры мостов Петербурга, Петрограда, Ленинграда

maarakennus

- Simulation of a test embankment on a clay foundation according to critical state models 
- Uusi innovaatio kantamattomien maiden stabilointiin.
- Synteettiset geovahvisteet :suunnittelu ja rakentaminen
- Undrained shear strength of Finnish clays for stability analyses of embankments 
- Vakuumikonsolidointi - potkua esirakentamiseen.
- Infrarakentaminen. Osa 3, Maanleikkaus ja -siirto.
- Geotekninen suunnittelu :eurokoodin EN 1997-1 suunnitteluohje.
- Teräksisten geovahvisteiden suunnittelu 
- Ground engineering.
- Maarakennus

vesistöt, tulvat, vesirakennus:

- Kyrönjoen yläosan vesistötöiden vaikutus ja Kyrönjoen tila vuosina 1975-2003 
- Kokemäen ja Loimijoen tulvasuojelu etenee :viimeinen suuri vesistöhanke.
- Kyrönjoen tulvasota 
- Raumanjuopan ruoppauksen vesistövaikutuksista 
- Vesirakenteiden suunnittelu
- Hollantilaiset lopettivat taistelun luontoa vastaan : nyt annetaan maata takaisin merelle
- Patojen muuttama maa.
- Embanked floodplains in the Netherlands :geomorphological evolution over various time scales 
- Kalajärven altaan säännöstelyn ja Seinäjoen keskiosan pengerrysten vaikutukset Seinäjoessa vuosina 1986 - 1997 
- Porin tulvat -selvityksellä varaudutaan suurtulviin :muun muassa tulvapenkereiden mitoitus tarkistetaan.

Epäselviä tai monta vaihtoehtoa:

- maarakennus/viherrakennus?: Ground bioengineering techniques :for slope protection and erosion control 
- tienrakennus/viherrakennus?: Siilinjärven ohitustien soramonttuun maisemoinnilla vihreyttä.
- A shoshonitic dyke in Lohja, southern Finland
- Landslides in cold regions in the context of climate change (viherrakennus?)
- Sateenkorjuu. (viherrakennus?)
- Riippuvat puutarhat katosivat :Babylonin ihmeestä ei ole saatu todisteita (viherrakennus?)
- Assessment of aquatic pollution, remedial measures and juridical obligations of an acid sulphate soil area in western Finland. 
- Soil erosion and soil-moisture conservation under old terracing system in the Palestinian Central Mountains. (pengerviljely on YSAssa)
- Nipunpudotuspaikkojen suunnittelu- ja maastotutkimusohjeet  (tienrakennus?)
- Economic evaluation of a soil conservation project in Machakos district, Kenya :a minor field study 
- Water harvesting for improved agricultural production 
- Suomalainen kylmän ilmaston rakennustekniikka 2 :kunnallistekniikka ja maa- ja vesirakentaminen.
- Masonry walls 
- Naturnahe Vegetation im Naturschutzgebiet "Unterer Inn" und seiner Umgebung :eine vegetationskundlich-ökologische Studie zu den Folgen des Staustufenbaus 
- Terrassernas budskap :hur historien började i Västnyland 
- Stenarna talar?.
- Yyterin puutarhassa riiputaan Aatamin ja vähän Eevankin asussa.

**Comment by mirmaid** [comment]
Mietin tässä sellaistakin ratkaisua, että poistettaisiin _vallit_, jolloin pengerrykset voisi olla ruotsiksi _vallar_. _Vallit_ Melindassa vain 10 kertaa. Tämä toki onnistuu vain jos kaikki pengerrykset voidaan ruotsiksi lukea valleiksi?

**Comment by mariaforsen** [comment]
Ehkä jollain tasolla ainakin on mahdollista ajatella että olisivat vallar. Ja vallit olisi sitten KT? Taitaa olla mahdotonta löytää tyydyttävää ratkaisua. 

Ainakin "rinteessä olevasta (kapeahkosta) tasanteesta" on ehdottomasti terrass, ei vall. Se voisi tosin olla myös avsatser=tasanteet, mutta nekin ovat ongelmallisia monimerkityksisiä termejä.

**Comment by YSA-kokous** [comment]
Pohdintaa: Suomeksi "vallit ja pengerrykset" tms? Tai poistetaan pengerrykset ja otetaan tarpeen mukaan tarkempia käsitteitä?

**Comment by mariaforsen** [comment]
Kannatan tarkempia termejä (ja "pengerrykset"-termin poistamista), se lienee ainoa tapa ratkaista tämä kieliversioiden kannalta mahdollisimman korrektisti

**Comment by mirmaid** [comment]
Tosiaan niitä tarkempia termejä on yritetty löytää, mutta ovat melko hankalia rajata. Yksi mahdollinen on ehdotettu _viherrakentaminen_, mutta se kattaa vain osan erilaisista penkereistä/pengerryksistä. _Maarakentaminen_ taas kattaa tavallaan kaikki pengerrykset. _Ratapenkereet_ ja _tienpenkereet_ kattavat niin ikään vain pienen osan käytöstä.

**Comment by mirmaid** [comment]
Ehdotan vielä jotakin sen tyyppistä kuin esim. _penkereet ja vallit_. Lisäksi on mahdollista ottaa _ratapenkeet_ ja _tienpenkereet_ omina termeinään, mutta en keksi mitään tapaa jakaa kaikkia näiden lisäksi mahdollisia penkereitä tarkempiin termeihin (vrt. Ilonan listaus). 

Jos hyväksytään, että osa jää ulkopuolelle (653-kenttään) ja tarkkaa jakoa pidetään välttämättömänä, seuraavat ovat mahdollisia (?):

pengerrykset (viherrakentaminen/viher- ja piharakentaminen):
Ainakin lähes kaikki pengertäminen on jonkinlaista maarakennusta, joten se ei riitä rajaamaan merkitystä. En ole piharakentamisesta ollenkaan perillä, mutta itse ymmärtäisin esim. siinä yhteydessä pengerryksen viittaavan sekä pengertämällä aikaansaatuun tasaiseen alaan rinteessä (johon voi vaikka laittaa istutuksen), että siihen viistoon reunukseen kahden tason välillä, joka voi olla esim. kivetty. Eli vaikka viherrakentaminen olisikin erotettavissa tarkenteelta muusta pengertämisestä, aivan ruotsinkielen mukainen erottelu tasaisen alan ja "penkan" välillä ei kuitenkaan sisältyisi termiin _pengerrykset (viherrakentaminen)_.  Jos siis kuitenkin pidetään välttämättömänä tätä tarkempaa jaottelua, on ruotsinkielinen vastine valittava niin, että ei rajata jompaan kumpaan (?). Mietin myös, onko ongelmallista, että kaikki tähän kategoriaan kuuluva ei välttämättä pidä sisällään mitään "vihreää" (esim. kivimuurin rakentaminen, pihakiveykset). Jotkut ovat myös hieman rajatapauksia, kuuluvatko lainkaan tähän (esim. rinnetontin tukimuurit).

Pengerrykset/penkereet (vesirakennus) on mahdollinen rajaus.

Ongelmallisinta tarkan jaon osalta ovat harvinaisemmat tapaukset, esim. eroosiosuojaus tai muinaisjäännökset, jotka eivät sovi näihin neljään ryhmään.

Mahtaako tämä aineisto https://melinda.kansalliskirjasto.fi/byid/012404723 käsitellä ratapenkereitä vai viherrakentamisen penkereitä :slightly_smiling_face:?

**Comment by ilona-x** [comment]
Mielestäni viherrakentaminen kattaa puutarhoihin/pihoihin tehdyt kiveykset ja muurit:

"fi     viherrakentaminen
sv     grönbyggande n

määritelmä
maarakentaminen, jossa rakennetun ympäristön viimeistelyyn käytetään istutuksia"
Lähde:  Ympäristösanasto (TSK 27, 1998)

Melinda-esimerkki lienee jotain tällaista? 😃  https://raitiotieallianssi.fi/tiedotteet/raitiotie-alkaa-vihertaa-tampereelle-maailman-pohjoisimpia-nurmiratoja/ Tosin en ymmärrä miksi siinä on käytetty termiä "pengerrykset", mutta artikkeleiden kuvailu nyt on välillä ollut melko omintakeista.

Eli pengerrykset (viherrakentaminen) voisi ohjata pengerrykset (maarakennus). Jos näihin tarkempiin termeihin päädytään.

**Comment by YSO-kokous** [comment]
Sanastosta poistetaan vallit.
Pengerrykset muutetaan muotoon penkereet ja vallit. Ohjaustermiksi sekä penkereet että vallit.
Otetaan sanastoon lisäksi ratapenkereet, jolle ohjaustermiksi penkereet (ratapenkereet).
Otetaan sanastoon lisäksi tiepenkereet, jolle ohjaustermiksi penkereet (tiepenkereet).

Ratapenkereet haluttiin erityisesti omana käsitteenään, myös tienpenkereet. Muihin tapauksiin riittänee penkereet ja vallit -käsite.
