### ISSUE TITLE
natriumformiaatti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6660]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

natriumformiaatti 

#### Ehdotettu termi englanniksi   

sodium formate 

#### Ehdotettu termi ruotsiksi   

natriumformiat 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Natriumformiaatti 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://julkaisut.liikennevirasto.fi/pdf8/lts_2016-05_kaliumformiaatin_kayton_web.pdf 

**Termiehdotus Fintossa:** [natriumformiaatti](http://finto.fi/yse/fi/page/Y506660)

**Comment by mariaforsen** [comment]
Sv. natriumformiat ET natriummetanoat
