### ISSUE TITLE
Haapavesi Folk Music Festival

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6661]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Haapavesi Folk Music Festival 

#### Ehdotettu termi ruotsiksi   

Haapavesi Folk Music Festival 

#### Ehdotettu termi englanniksi   

Haapavesi Folk Music Festival 

#### Vaihtoehtoiset termit ja ilmaisut   

Haapavesi Folk 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikkijuhlat](http://www.yso.fi/onto/yso/p1482) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Haapavesi_Folk_Music_Festival 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Folkit! : Haapavesi Folk Music Festival juhlakirja 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Haapavesi Folk Music Festival](http://finto.fi/yse/fi/page/Y506661)

**Comment by MUUSA-kokous** [comment]
Muusa puoltaa käsitteen ottamista YSAan.

**Comment by mariaforsen** [comment]
Sv. Haapavesi Folk Music Festival ET Haapavesi folkmusikfestival
