### ISSUE TITLE
moduulit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6662]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[moduulit](http://www.yso.fi/onto/ysa/Y103546) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään moduulit KÄYTÄ modulaarisuus, ohjaustermeiksi moduulit ja mahdollisesti moduulirakenteet.
Käydään läpi moduulit-käsitteellä kuvaillut ja ohjataan ne --> modulaarisuus tai moduulirakentaminen. Sen jälkeen mietitään ratkaisu ylijääville. Tarkistetaan samalla hierarkia ja ryhmät. 

#### Perustelut ehdotukselle   

YSAssa tällä on  ryhmät 00, 37 ja 91. YSOssa vain 37 ja 91, YK tekniset objektit (abstraktit objektit). Melindassa käyttö on kuitenkin paljon laajempaa, kuin mitä hierarkia ja ryhmät antavat ymmärtää. Lisäksi moduulit ja modulaarisuus esiintyvät hyvin samantyyppisissä aineistoissa ja eikä kuvailukäytön pohjalta voi tehdä selvää eroa niiden välille. Näiden lisäksi sanastoon on erotettu moduulirakentaminen omaksi täsmällisemmäksi käsitteekseen.

Melindassa: 
moduulit 150 kertaa
modulaarisuus 41 kertaa
moduulirakentaminen 9 kertaa
moduulit + modulaarisuus 12 kertaa 

#### Ehdottajan organisaatio   

Kansalliskirjasto / Satu

**Comment by EsaMPKK** [comment]
Panssaroitu modulaarinen ajoneuvo:
http://www.reservilainen.fi/uutiset/patria_amv_vaivihkaa_vientimenestykseksi

**Comment by YSA-kokous** [comment]
moduulit KÄYTÄ modulaarisuus
