### ISSUE TITLE
suitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6663]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suitit 

#### Ehdotettu termi englanniksi   

Suiti 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Suitit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaneiston sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3159945 

#### Tarkoitusta täsmentävä selite   

Latviassa asuva etninen ryhmä. Suitien kulttuurialue lisättiin Unescon aineettoman kulttuuriperinnön luetteloon vuonna 2009. 
https://www.suitunovads.lv/en/Who_are_Suiti/ 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [suitit](http://finto.fi/yse/fi/page/Y506663)

**Comment by mariaforsen** [comment]
Sv. suiti
