### ISSUE TITLE
Pyhäjärvi -- Pirkanmaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6665]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pyhäjärvi -- Pirkanmaa](http://www.yso.fi/onto/ysa/Y105829) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pyhäjärvi (järvi) -- Pirkanmaa 

#### Perustelut ehdotukselle   

Haku *pyhäjärvi* tuottaa Finto-YSAssa 40 osumaa. Sulkutarkenteella arvonta kaupungin ja vesistönimen välillä helpompaa, varsinkin kun osassa Pyhäjärviä on jo käytetty sulkutarkennetta (järvi) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
lisätty YSAan sulkutarkenne järvi
