### ISSUE TITLE
Pyhäjärvi -- Pohjois-Karjala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6666]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pyhäjärvi -- Pohjois-Karjala](http://www.yso.fi/onto/ysa/Y109150) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Haku *pyhäjärvi* tuottaa Finto-YSAssa 40 osumaa. Sulkutarkenteella arvonta kaupungin ja vesistönimen välillä helpompaa, varsinkin kun osassa Pyhäjärviä on jo käytetty sulkutarkennetta (järvi) 

#### Ehdotettu muutos   

Pyhäjärvi (järvi) -- Pohjois-Karjala 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
lisätty tarkenne järvi
