### ISSUE TITLE
forskningspublikationer

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6668]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

forskningspublikationer 

#### Ehdotettu termi suomeksi   

tutkimusjulkaisut 

#### Ehdotettu yläkäsite YSOssa (LT)   

[publikationer](http://www.yso.fi/onto/yso/p1548) 

#### Perustelut ehdotukselle   

Termen behövs för att beskriva bl.a. universitets publikationsarkiv. De befintliga Allärs-termerna "forskningsrapporter" och "forskningsresultat" känns inte helt rätt utan snarare som underordnade eller möjligen relaterade. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://abo.finna.fi/Browse/Database ;;;; t.ex. http://www.diva-portal.org; https://www.base-search.net/; https://jyx.jyu.fi/; https://aaltodoc.aalto.fi/; https://helda.helsinki.fi 

#### Tarkoitusta täsmentävä selite   

Innehållet i bl.a. univeristets/akademiska organisationers publikationsarkiv. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Vetenskap. Forskning](http://www.yso.fi/onto/yso/p26544) 

**Termiehdotus Fintossa:** [forskningspublikationer](http://finto.fi/yse/fi/page/Y506668)

**Comment by mirmaid** [comment]
Tutkimusraportit ok SLM. Julkaisuarkistot (?) Seuraava kokous.

**Comment by mirmaid** [comment]
Julkaisuarkistot ok / SLM. Lisätään YSAn määritelmä YSOon ja SLM:ään.
