### ISSUE TITLE
kiteytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6669]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kiteytys](http://www.yso.fi/onto/ysa/Y96243) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään termiin kiteytyminen 

#### Perustelut ehdotukselle   

Käytetty samankaltaisissa aineistoissa, käännösongelma. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/922

**Comment by ilona-x** [comment]
FinMeSH: **kristallisaatio** KT kiteyttäminen http://www.yso.fi/onto/mesh/D003460

**Comment by YSA-kokous** [comment]
kristallisaatio
