### ISSUE TITLE
väsyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6670]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väsyminen](http://www.yso.fi/onto/ysa/Y104908) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne tai muutetaan ohjaustermiksi. 

#### Perustelut ehdotukselle   

Ryhmä nyt 07 (fysiikka). Käytetty runsaasti myös ihmisen väsymisestä. Sanastossa on lisäksi väsymys, sekä väsymiskokeet ja väsymislujuus. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/911
