### ISSUE TITLE
veturinkuljettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6671]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[veturinkuljettajat](http://www.yso.fi/onto/ysa/Y105577) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään asiasanaan "veturinkuljettajat" 

#### Perustelut ehdotukselle   

YSO:ssa on nyt kaksi "veturinkuljettajat"-asiasanaa, http://www.yso.fi/onto/yso/p10454 ja http://www.yso.fi/onto/yso/p20422, kumpikin erilaisin sanasuhtein, mikä ei liene tarkoitus. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto (Jaakko Tuohiniemi)

**Comment by mirmaid** [comment]
Korjattu
