### ISSUE TITLE
satunnaistetut kontrolloidut tutkimukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6672]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

satunnaistetut kontrolloidut tutkimukset 

#### Ehdotettu termi englanniksi   

randomised controlled trials 

#### Ehdotettu termi ruotsiksi   

randomiserade kliniska prövningar 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tutkimusmenetelmät](http://www.yso.fi/onto/yso/p415) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Randomized_controlled_trial 
KOKO-Ontologia : <http://www.yso.fi/onto/koko/p57844> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tutkimukset, jossa kyseistä metodia käytetään, aiheesta kertovat teokset 

#### Perustelut ehdotukselle   

Termille ei löydy mitään vastaavaa yläkäsitettä, jolla aiheesta kertovaa teosta voitaisiin kuvailla. Menetelmä käytössä yleisesti lääketieteessä ja yhteiskuntatieteissä. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [satunnaistetut kontrolloidut tutkimukset](http://finto.fi/yse/fi/page/Y506672)

**Comment by vthuhtala** [comment]
'satunnaistetut kontrolloidut tutkimukset' termistä saa sen kuvan, että kyseessä on jonkin ulkopuolisen (esim. rahoittaja) tekemä tarkistus tutkimuksen laadusta. Mitä vikaa on wikpedian suommennoksessa termille 'Randomized controlled trial' = 'Satunnaistettu vertailukoe' https://fi.wikipedia.org/wiki/Satunnaistettu_vertailukoe ?

**Comment by ilona-x** [comment]
FinMeSH: **Satunnaistetut kontrolloidut tutkimukset**  http://finto.fi/mesh/fi/page/D016449
Tieteen termipankki: **satunnaistettu vertailukoe | satunnaistettu vertaileva koe** http://tieteentermipankki.fi/wiki/Epidemiologia:satunnaistettu_vertailukoe
