### ISSUE TITLE
evankeliumi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6673]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[evankeliumi](http://www.yso.fi/onto/ysa/Y112803) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

evankeliumi (sanoma)
Myös evankeliumit > evankeliumit (kirjat)?
Ruotsiksi evangelium (budskap), evangelier (böcker) 

#### Perustelut ehdotukselle   

Merkitys pitää selventää (ontologiasääntöjen mukaisesti), voidaan muuten käyttää väärin. 

Kielitoimiston sk. 
1. usk.
a. sanoma Jeesuksesta ihmiskunnan pelastajana. Saarnata evankeliumia.
b. kukin Uuden testamentin neljästä ensimmäisestä kirjasta; evankeliumiteksti. Markuksen evankeliumi. Jouluevankeliumi.

**Comment by mirmaid** [comment]
LCSH: (130) Bible. Gospels

**Comment by YSA-kokous** [comment]
evankeliumi (sanoma)
