### ISSUE TITLE
antologiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6674]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[antologiat](http://www.yso.fi/onto/ysa/Y100785) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-sanastoa koskien: Muutetaan termin määritelmä, jotta sen käyttö ei rajoitu yksinomaan kaunokirjallisuuteen. 

#### Perustelut ehdotukselle   

Monien nuottijulkaisujen ja äänitteiden osalta on luontevampaa käyttää termiä "antologiat" kuin "kokoomateokset", esim. 'Music of the Bach Family: an Anthology', 'Masterpieces of Music Before 1750: an Anthology of Musical Examples from Gregorian Chant to J.S. Bach', 'Ethiopian Christian Liturgical Chant: an Anthology' ja 'Eesti rahvamuusika antoloogia'. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Koskee myös YSAa.

**Comment by krinay** [comment]
Kuka määrittelee termin ja miten?

Jos määritelmä on tarpeeksi väljä, voisiko termiä käyttää (esim. yhdyssanan osana) myös ainesjulkaisuista, ks. https://github.com/Finto-ehdotus/YSE/issues/6035. Perinneantologiat = folklore anthologies?

Perinteiset sanakirjamääritelmät ovat kyllä aika rajaavia:
Tieteen termipankki (Kirjallisuudentutkimus): "kirjoitusvalikoima, johon sisältyy tekstejä useilta kirjoittajilta"
Kielitoimiston sanakirja: "valikoima usean kirjailijan tuotantoa, vars. runoja, runovalikoima"
Nykysuomen sanakirja: "kokoelma kaunokirjallisuudesta valittuja näytteitä, vars. runoja; runovalikoima"
Suomen kielen sanakirja (Otava, 1981): "kokoelma kirjallisia näytteitä".

**Comment by MUUSA-kokous** [comment]
Ehdotus: antologiat LT kokoomateokset. Antologiat ovat yhdenlaisia kokoomateoksia.

Lisäksi ehdotetaan muutosta kokoomateokset-käsitteeseen siten, että merkitykseen sisällytetään myös musiikilliset kokoomateokset. Määritelmäehdotus kokoomateoksiin: "Yhden tai useamman tekijän useita teoksia sisältävä kokonaisuus."

**Comment by mirmaid** [comment]
Hierarkia SLM:ssä ok. Entinen määritelmä ok.

**Comment by mirmaid** [comment]
YSAssa määritelmä muutettava, YSOssa hierarkia muutettava (YK kirjalliset teokset)?

**Comment by YSA-kokous** [comment]
antologiat: valikoima usean tekijän teoksia (?)

**Comment by mirmaid** [comment]
Muutokset _kokoomateokset_-termiin toteutettu. Tarvitaanko _antologiat_-termiin vielä muutoksia? Nyt YSOssa ei määritelmää, yläkäsite _kirjalliset teokset_. SLM:ssä määritelmä: _Useamman kuin yhden kirjailijan kaunokirjallisista teksteistä koostuva valikoima._ (LT _kokoomateokset_, tämän voisi lisätä YSOssakin toiseksi yläkäsitteeksi.)

**Comment by YSA-kokous** [comment]
Sama määritelmä molemmissa.
