### ISSUE TITLE
kehityshäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6677]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kehityshäiriöt](http://www.yso.fi/onto/ysa/Y96041) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Ruotsiksi kehitysvamma + kehitysvammaisuus + kehityshäiriö = utvecklingsstörning, joten muutoksia vaaditaan.

Kirja-aineistossa käsitettä kehitysvammat on käytetty 122 kertaa. Se ei paria poikkeusta lukuunottamatta esiinny kuvailussa yksin, vaan mukana on aina kehitysvammaiset, kehitysvammaisuus, kehityshäiriöt tai vammaa täsmällisemmin kuvaava termi, kuten puhehäiriöt, oppimisvaikeudet, Downin oireyhtymä (poikkeuksena esim. Avoterveydenhuollon lastenneurologiaa / Sillanpää Matti, johon kehityshäiriöt varmasti riittäisi).

Kehitysvammaisuus löytyy 1129 kertaa, mutta yli puolessa tietueista on mukana myös kehitysvammaiset.

Käsitteet toki erovat toisistaan siinä mielessä, että ne korostavat kehitysvammojen eri aspekteja  Kehitysvammaisuus on yksilön ominaisuus mutta kehitysvammat sopii myös kuvailuihin, jossa käsitellään vamman yksittäistä osa-aluetta irrallaan vammaisesta yksilöstä. Kehityshäiriöiden suhteessa näihin kahteen tarkemmin esim. tässä: http://verneri.net/yleis/kehityshairio-ja-kehitysvammaisuus

Käytännössä näin hienojakoinen erottelu ei kuitenkaan todeudu, sillä aineistoissa ja niiden kuvailuissa käyttö on päällekkäistä. Tässä vielä lukuja Melindasta:

kehitysvammat 122 kpl
kehitysvammaisuus 1129 kpl
kehitysvammat + kehitysvammaisuus 65 kpl
kehitysvammat + kehitysvammaiset 72 kpl
kehitysvammaisuus + kehitysvammaiset 649 kpl

Terossa kehitysvammaisuus KT kehityshäiriöt, kehitysvammat
FinMeshissä kehitysvammaisuus KT kehitysvammat, ei kehityshäiriöitä myöskään omana terminään. 

#### Ehdotettu muutos   

poistetaan kehitysvammat ja kehitysvammaisuus ja ohjataan molemmat kehityshäiriöihin 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
kehitysvammat - psykiska utvecklingsstörningar
kehityshäiriöt - utvecklingsstörningar
kehitysvammaiset - personer med utvecklingsstörning
kehitysvammaisuus - utvecklingsstörning

**Comment by mirmaid** [comment]
Lääketieteen termit:

kehitysvammainen: _henkilö jonka (etenkin älyllinen) kehitys tai henkinen toiminta on estynyt tai häiriintynyt synnynnäisen tai kehitysiässä saadun sairauden, vian tai vamman vuoksi_

kehityshäiriö: _1. sikiökaudella tai lapsuusiässä tapahtunut jonkin elinjärjestelmän kehityksen häiriintyminen (esim. dysplasia (1), hermostoputken sulkeutumishäiriö); 2. taitojen taikka psyykkisen tai psykososiaalisen kehityksen häiriintyminen; vrt. kehityspoikkeama, kehitysviivästymä_

**Comment by mirmaid** [comment]
Ainakin _kehitysvammaisuus_ vaikuttaisi olevan korvattavissa termeillä _kehitysvammaiset_ ja/tai _kehitysvammat_, muut muutokset hankalampia (?).

Googlella valtavasti viitteitä muodolla _utvecklingsstörda_, joka on Allärsissa ohjaustermi?

**Comment by YSA-kokous** [comment]
kehitysvammaisuus KÄ kehitysvammaiset, kehitysvammat

**Comment by mirmaid** [comment]
Jäljellä:
kehitysvammaiset
kehitysvammat
kehityshäiriöt

Termiä _kehitysvammat_ on käytetty Melindassa 1519 kertaa ja termiä _kehityshäiriöt_ 1344 kertaa. Vain 205 kertaa termit ovat samassa tietueessa.

**Comment by mirmaid** [comment]
Tässä vielä ylempänä linkattu verneri.netin teksti:

**Mikä ero on kehityshäiriöllä ja kehitysvammaisuudella?**

Kehityshäiriö on yläkäsite kaikille synnynnäisille tai kehitysiässä ilmeneville lapsen kehityksen poikkeavuuksille. Yleensä tällä käsitteellä viitataan rakenteellisiin tai neurologisiin vaurioihin, ei niinkään psykososiaalisen kehityksen ongelmiin. Ongelmia voi olla motoriikassa, puheen kehityksessä, tarkkaavuudessa ja käyttäytymisen säätelyssä sekä informaation käsittelyssä ja oppimisessa. Kehitysvammaisuus on kehityshäiriön alalaji, yksi monista kehityshäiriön muodoista.

Lääketieteellisessä diagnostiikassa puhutaan mm. sellaisista oireyhtymistä kuin monimuotoiset kehityshäiriöt (kielellisen kehityksen, oppimiskyvyn ja motoriikan kehityksen häiriöt yhtä aikaa), laaja-alaiset kehityshäiriöt (autismin kirjon kehityshäiriöt) ja hyperkineettiset häiriöt (tarkkaavuus- ja ylivilkkaushäiriö). **Kehitysvammaisuus tulee sitten tämän luettelon jatkoksi. Sillä viitataan kehityshäiriöön, jonka keskeinen tunnusmerkki on vamma oppimisen ja ymmärtämisen alueella ja vaikeus oppia ja ylläpitää elämässä tarvittavia taitoja.**

**Comment by mariaforsen** [comment]
Sv. nyt siis utvecklingsstörningar=kehityshäiriöt ja psykiska utvecklingsstörningar=kehitysvammat. 

Pitääkö tämä kieltenvälinen linkitys paikkaansa? https://sv.wikipedia.org/wiki/Intellektuell_funktionsneds%C3%A4ttning Eli "Kehitysvammaiseksi ei kuitenkaan luokitella henkilöä, jolla on toimintarajoitteita ainoastaan motoriikassa tai vuorovaikutuksessa, vaan kehitysvammaisuudella viitataan heikkolahjaisuutta suurempiin puutteisiin ymmärtämiskyvyssä ja muussa älyllisessä suoriutumisessa." 

https://www.psykologiguiden.se/psykologilexikon/?Lookup=psykisk%20utvecklingsst%C3%B6rning

Huom YSOssa nyt eng. developmental disabilities, se ei kai ole sama asia? Ja sanastossa myös developmental disorders=kehityshäiriöt Wikipediassa kehitysvamma: https://en.wikipedia.org/wiki/Intellectual_disability Ruotsinnos riippuu varmaan myös englannin termistä...

**Comment by YSO-kokous** [comment]
Tehdään määritelmät käyttäen inspiraationa verneri-netin tekstejä. Muutetaan ruotsin vastineet Marian edellä esittämällä tavalla. Tutkitaan ja korjataan tarvittaessa englannin kielen vastineet.
