### ISSUE TITLE
hengelliset laulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6678]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hengelliset laulut](http://www.yso.fi/onto/ysa/Y95328) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmää muutettava. Tai vaihtoehtoisesti termiä muutettava, jos halutaan rajata merkitystä. 

#### Perustelut ehdotukselle   

Määritelmä "Kristillisten uskontokuntien ei-liturgiseen lauluperinteeseen kuuluva teos." on liian rajaava. Ainakaan ruotsin kielen kannalta tätä ei voida rajata pelkästään kristilliseen eikä pelkästään ei-liturgiseen lauluperinteeseen. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Andliga sånger on tärkeä termi (ja siinä ei oteta kantaa onko kyseessä kristillinen vai jonkun muun uskonnon/suunnan laulu kyseessä). Kannatan määritelmän poistamista. 

SAO: andliga sånger och visor LCSH linkitys: sacred songs  
"Hit litteratur om andliga sånger och visor. För sångböcker och sångtexter används genre/formtermen Andliga sånger och visor"

**Comment by mirmaid** [comment]
Voisiko sitten olla pelkästään _kristilliset laulut_?

**Comment by MUUSA-kokous** [comment]
Muusa päätyi kannattamaan termimuotoa, jossa olisi sulkutarkenne. Näin termi olisi lähempänä luonnollista kieltä: "hengelliset laulut (kristinusko/kristillisyys/tms)

**Comment by satuniininen** [comment]
entä kristilliset laulut KT hengelliset laulut (kristinusko)?

**Comment by jtuohini** [comment]
Valitettavasti ei onnistu, kun nimenomaan "hengelliset laulut" on yleisesti tunnistettu käsite.

**Comment by LeKorsu** [comment]
Kannatan "hengellisten laulujen" säilyttämistä, koska se tosiaan on yleisesti tunnistettu ja tuttu käsite mutta palaan alkuperäiseen ja Marian ehdotukseen: miksi pelkkä määritelmän poistaminen ei riitä?

**Comment by YSA-kokous** [comment]
hengelliset laulut (kristinusko)

**Comment by mirmaid** [comment]
Muutettu/YSO.

**Comment by asormune** [comment]
Muuttuuko myös SLM termi?

**Comment by mirmaid** [comment]
hengelliset laulut (kristinusko) / SLM
