### ISSUE TITLE
eloelektroniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6679]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[eloelektroniikka](http://www.yso.fi/onto/ysa/Y214457) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihtoehto 1a) Poistetaan käsite
Vaihtoehto 1b) Poistetaan käsite ja lisätään eloelektroniikka ohjaustermiksi äänenkäsittely-käsitteelle ja/tai elektroakustinen musiikki -käsitteelle.
Vaihtoehto 2) Muutetaan eloelektroniikka muotoon äänenkäsittelylaitteet. LT:ksi laitteet. Muokataan määritelmää sopivammaksi.
Vaihtoehto 3) Ei poisteta käsitettä eikä muuteta termiä. Muokataan määritelmää sopivammaksi. LT:ksi laitteet. 

#### Perustelut ehdotukselle   

Käsite ja termi ovat epäselviä. Tarkoitetaanko termillä tiettyä musiikkia vai tekniikkaa? Ensimmäiseen tulkintaan viittaa LT elektroakustinen musiikki, toiseen tulkintaan määritelmä "Elektronisia äänentuottamis- ja muokkaamisvälineitä hyödyntävä esitystekniikka". Termi on jäänyt hyvin vähälle käytölle verrattuna siihen, miten yleistä "elektronisia äänentuottamis- ja muokkaamisvälineitä hyödyntävä esitystekniikka" missä tahansa musiikinlajissa nykyään on. Termin käyttö näyttää rajautuneen lähinnä tiettyihin kotimaisiin jazzin ja modernin klassisen musiikin toimijoihin. Toisin sanoen iso osa kentästä ei tunne termiä tai vieroksuu sitä. Yleisemmin tämän tapaisissa yhteyksissä puhutaan elektroakustisesta musiikista, äänitaiteesta, kokeellisesta musiikista, äänenkäsittelystä tai tietyistä äänenkäsittelylaitteista niiden omilla nimillä.

Mikäli termi halutaan säilyttää, kannattaa ainakin LT muuttaa ja määritelmää tarkentaa. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by asormune** [comment]
Esim. CD-julkaisussa (2016) Pietilä, Esa: Times and spaces on käytetty eloelektroniikka -termiä. Luokkana 78.89224, eli jazzia. Yhtenä asiasanaketjuna eloelektroniikka - jazz. YSA:ssa elektroakustinen musiikki -termi on rajattu vain taidemusiikkiin, populaarimusiikin yhteydessä on käytettävä termiä elektroninen populaarimusiikki. Jääkö tällöin akustisesti ja elektronisesti tuotetun musiikin "yhdistelmä" vaille ilmaisua? Onko "elektroninen poulaarimusiikki" termiä käytettävä vain ja pelkästään "koneellisesti tuotetusta" musiikista?

**Comment by jaskaj** [comment]
Ymmärtääkseni termi "elektroninen populaarimusiikki" on aikoinaan otettu käyttöön "synthesizer greatest" -tyyppisten kokoelmien kuvailua varten, eli termillä on tarkoitettu nimenomaan "koneellisesti tuotettua" musiikkia.

**Comment by tpalonen** [comment]
Sivuhuomiona: elektroakustinen musiikki osoittaa hyvin taidemusiikin ja populaarimusiikin välisen rajan vanhanaikaisuuden ja keinotekoisuuden. Kentät menevät tässä vahvasti päällekkäin. Täysin samankuuloista ja samoilla tekniikoilla tehtyä musiikkia tehdään molemmissa. Populaarimusiikin kokeellisen laidan tekijän erottaa taidemusiikin tekijästä ainoastaan se, mikä koulu on käyty. Esimerkkinä vaikkapa kotimaiset Jan Anderzen (Tomutonttu) ja Marja Ahti (Tsembla), joiden musiikki on elektroakustista musiikkia par excellence, mutta ei kaiketi voida laskea taidemusiikiksi, koska eivät ole opiskelleet säveltämistä.

**Comment by MUUSA-kokous** [comment]
Yläkäsitteeksi sähkösoittimet. Eloelektroniikka otettaneen myös SEKOon.

**Comment by mariaforsen** [comment]
Sv. live-elektronik
