### ISSUE TITLE
havaijinkitara

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6680]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[havaijinkitara](http://www.yso.fi/onto/ysa/Y214480) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutos määritelmään tai yläkäsitesuhteeseen tai käsitteen poistaminen 

#### Perustelut ehdotukselle   

Määritelmä: "Havaijilla 1880-luvulla syntynyt kitaran soittotyyli (sylissä, metallitangolla tai putkella kielillä liu'uttaen), jonka seurauksena alettiin valmistaa erityisesti tähän tarkoitukseen soveltuvia kitaroita."
Määritelmän mukaan tämä ei siis ole tietyntyyppinen kitara vaan tietyntyyppinen kitaran soittotyyli. Jos näin niin yläkäsite kitara on väärä. Termi viitannee kuitenkin kitaraan, ei soittotyyliin (vrt. slide-kitara joka viittaa soittotyyliin).

Toisaalta: onko käsitteelle ylipäätään tarvetta YSAssa kun slide-kitara kuitenkin löytyy myös? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by asormune** [comment]
Tarvitaanko ehkä kuitenkin, molemmat (tyyli ja soitin)?

CD-julkaisuun (Proper Records, 2008) "Steelin' it  : the steel guitar story" liittyy oheinen kuvaus (Aksentti / Matti Laipio)

Havaiji on vaikuttanut yllättävän paljon musiikkiin muualla  maailmassa. Bluesissa yleinen kitaran kielten liutteluun perustuva  slide-tekniikka omaksuttiin 1900-luvun vaihteen tienoilla kierteleviltä  havaijilaisilta muusikoilta. Vielä enemmän Havaijin vaikutus on tuntunut  kantrimusiikissa, sillä tässä genressä yleinen soitin, steel-guitar on syntynyt  havaijilaisvaikutteista. Havaijilaiset kitaristit keksivät joskus 1800-luvulla  nostaa kitaran kieliä ja ryhtyä soittamaan sitä poikittain liutellen teräspalaa  kitaran kieliä pitkin. Tuloksena kitarasta lähtevät äänet pitenivät ja niiden  sävy muuttui naukuvaksi. Havaijilaismusiikista tuli muoti-ilmiö ja sikäläiset  soittajat kiertelivät ympäri maailmaa. Blues-kitaristien lisäksi  havaijilaissoittajia ryhtyivät matkimaan monet muutkin soittajat. 1930-luvulla  syntyi sähköistetty sylissä pidettävä ns. lap steel -kitara, jonka seuraava  kehitysaste oli telineelle rakennettu soitin. varsinainen steel guitar. Sen  soitto-ominaisuuksia laajennettiin muun muassa pedaaleilla. Steel tuli soittimen  nimeen siitä, että kielten liutteluun käytettiin vasemmassa kädessä olevaa  teräspalaa. Steel guitarin käyttö yleistyi aluksi kantrimusiikin yhdessä  1930-1940-lukujen valtasuuntauksessa, western swingissä, jossa soittimen  pioneerihahmoina olivat muun muassa Bob Dunn, Noel Boggs ja Leon McAuliffe.  Western swingistä steel guitar siirtyi nopeasti myös muuhunkin kantriin ja jo  1950-luvun alussa useimmissa kantriyhtyeissä steel guitar oli jo mukana.  Properin boksi esittelee jokseenkin kattavasti ensimmäisellä levyllään alan  havaijilaisia mestareita ja heistä vaikutteita saaneita muusikkoja. Loput kolme  levyä kartoittavat tämän soittimen leviämistä kantrimusiikissa. Mukana on  western swingiä reilun levyllisen verran. Tämän suuntauksen parhaat steelistit  ovatkin hyvin edustettuina. Suositeltava boksi, jonka oheisvihkonen on  asiantuntevasti tehty.
--

**Comment by asormune** [comment]
Tulipas kopioitu teksti isolla, en osannut editin kautta vaihtaa fonttia. Mutta näkyypä ainakin..

**Comment by tpalonen** [comment]
Havaijinkitara on steel-kitaraa huomattavasti marginaalisempi termi, ja sävyltään historiallisempi kuin steel-kitara. Esim. Soundin verkkosivuilla steel-kitara termiä käytetty yli sata kertaa, havaijinkitara-termiä nolla kertaa. Soundin käyttötapauksissa steel-kitarakin usein viittaa itse kitaraan, ei pelkästään soittotekniikkaan. "Useammin levyllä kuitenkin pohditaan rakkauden olemusta pehmeän steel-kitaran kaiun kietoutuessa mietteliään melodian ympärille."

Tämän perusteella olisin valmis poistamaa havaijinkitaran ja lisäämään sen ohjaustermiksi steel-kitaralle.

**Comment by MUUSA-kokous** [comment]
Ovat eri käsitteitä. Ei muita muutoksia kuin että lisätään steel-kitaran ja havaijinkitaran välille RT.

**Comment by tpalonen** [comment]
Muutin havaijinkitaran määritelmää. Aiemmin määritelmän mukaan havaijinkitara oli soittotyyli. Muutin nyt tällaiseksi: "Havaijilla 1880-luvulla kehitetyn soittotyylin (sylissä, metallitangolla tai putkella kielillä liu'uttaen) seurauksena syntynyt tähän tarkoitukseen soveltuva kitara."
