### ISSUE TITLE
kontratanssit (tanssit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6681]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kontratanssit (tanssit)](http://www.yso.fi/onto/ysa/Y214784) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termi yksikkömuotoon. 

#### Perustelut ehdotukselle   

Kuten muutkin tanssit, vrt.  itämainen tanssi, jazztanssi, kansantanssi jne. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
Viittaa useaan erilliseen tanssiin, analogiana [heittolajit](http://www.yso.fi/onto/yso/p892), joka on monikossa, mutta jonka alla olevat lajit ovat yksikössä.

**Comment by YSA-kokous** [comment]
Ei muutosta.
