### ISSUE TITLE
mustalaismusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6682]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mustalaismusiikki](http://www.yso.fi/onto/ysa/Y97573) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutos määritelmään. 

#### Perustelut ehdotukselle   

mustalaismusiikki
Nykyinen määritelmä: "Erityisesti Keski-Euroopassa elävien romanien tulkitsema perinteinen viihdemusiikki, jossa viululla ja cimbalomilla on keskeinen rooli." Ruotsin vastine ei täsmää noin kapean määritelmän mukaan, mutta toisaalta ruotsin vastine pitää kyllä olla zigenar/romsk musik, eli voidaanko olla määrittelemättä noin kapeasti suomeksi? Muualla ei näytä olevan määritelty tuolla tavalla. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by MUUSA-kokous** [comment]
Käsite viittaa tiettyyn Keski-Euroopassa syntyneeseen genreen, ei romanien soittamaan musiikkiin yleisesti. Vaikkakin sitä on käytetty kuvailussa laajemmin (ts. väärin). Määritelmää muokataan siten, että "perinteinen" jätetään pois sekaannuksen välttämiseksi. Samoin määritelmästä pitäisi käydä ilmi että tämä ei ole pelkästään romanien soittamaa musiikkia, vaan tyyli tai genrekäsite. Mustalaismusiikkia voi soittaa kuka tahansa.

Pohdittiin termin muuttamista muotoon keskieurooppalainen mustalaismusiikki tai keskieurooppalaistyylinen mustalaismusiikki, mutta tämä ei saanut toistaiseksi riittävästi kannatusta.

**Comment by mariaforsen** [comment]
Sanakirjat ja yleinen käyttö määrittelee kuitenkin mustalaismusiikka laajemmalla tavalla (esim. Kielitoim. s. "romanien perinteinen laulu- ja soitinmusiikki"...) eli näissä tapauksissa kun halutaan poiketa yleismääritelmästä voi olla hyvin vaikeaa saada kieliversiot (ja kuvailu) yhteensopiviksi. Ruotsiksi pitänee jättää sitten tilanne ennalleen, mutta se tarkoittaa kyllä sitä että kuvailukäyttö tulee olemaan toinen kuin yllä oleva haluttu kapeampi tapa. Huomautuskaan ei varmaan estä kuvailijaa käyttämästä termiä siinä merkityksessä kuin se sanakirjoissa, yleiskielessä jne. on.

**Comment by YSO-kokous** [comment]
YSA-kokouksessa koettiin ongelmalliseksi se, että määritelmässä (ja termissä) puhutaan Keski-Euroopasta. Kuulemma tällaista samaa musiikkia on syntynyt samoihin aikoihin myös esim. Ranskassa ja Venäjällä, ei pelkästään Unkarissa. Pitäisi tarkistaa, onko todella näin, onko näissä kaikissa kyse samasta genrestä, ja vaikka olisikin, onko se ongelma.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Gypsy_style
https://en.wikipedia.org/wiki/Romani_music

**Comment by tpalonen** [comment]
Tuo Wikipedian Gypsy style oli nimenomaan se, mitä tässä nyt haetaan. Jos keski-eurooppalainen mustalaismusiikki on liian rajaava niin miten olisi **eurooppalainen mustalaismusiikki**?
Määritelmäehdotus: "Musiikkityyli, jossa viululla ja cimbalomilla on keskeinen rooli ja jossa on tyypillisesti unkarilaisen, romanialaisen tai venäläisen kansanmusiikin elementtejä."

**Comment by mirmaid** [comment]
Nyt termillä on huomautus: _Romanien omasta perinnemusiikista käytetään termiä perinnemusiikki._ Perinnemusiikilla on alakäsitteitä - jos romanien perinnemusiikki halutaan erottaa mustalaismusiikista, olisi helpompaa lisätä ohjaustermejä, jos olisi olemassa myös erillinen termi romanien perinnemusiikille. 

Mutta toisaalta wikipediassa https://sv.wikipedia.org/wiki/Zigenarmusik on vastineena englanninkieliselle sivulle https://en.wikipedia.org/wiki/Romani_music.

**Comment by YSA-kokous** [comment]
Tuomas selvittää ja tekee ehdotuksen.

**Comment by tpalonen** [comment]
Olen konsultoinut alan tutkijoita Risto Blomsteria ja Kai Åbergiä. Mitään yksiselitteistä voittajaehdokasta ei tullut. Todettiin, että termiä "mustalaismusiikki" on käytetty myös perinnemusiikin yhteydessä, romanien muistinvaraisesti oppimista lauluista. Termiä "mustalainen" on pyritty tutkimuksessa välttämään 90-luvusta lähtien.

Gypsy style -musiikin yhteydessä mainittiin, että tästä on käytetty termejä ”zigenarmusik”, ”viihteellinen romanimusiikki”, ”kansainvälinen mustalaismusiikki”, ”eurooppalainen mustalaismusiikki” ja ”eurooppalainen romanimusiikki”.

Näillä perustein kannattaisin "mustalainen"-sanan hylkäämistä ja käytettäväksi termiksi **"viihteellinen romanimusiikki"**. Viihteellinen lienee parempi ja tarkentavampi etuliite kuin eurooppalainen.

**Comment by mariaforsen** [comment]
Mikä tämä olisi englanniksi? Ja ruotsiksi? Ei löydy googlesta, joten minulle hieman epäselvää mitä tarkalleen nyt haetaan ja kääntäminen saattaa olla vaikeaa.

**Comment by MUUSA-kokous** [comment]
Viihteellinen romanimusiikki ei liene yleisesti käytetty termi.

Muusan ehdotus: "romanimusiikki (viihdemusiikki)".

Sama muutos SLM:ään.

**Comment by YSA-kokous** [comment]
Hyväksytään termimuutos Muusan ehdottamassa muodossa.
Lisätään ohjaustermiksi "viihteellinen romanimusiikki."
Muusalta toivotaan tähän vielä määritelmää, jotta tätä ei sekoitettaisi romanien perinnemusiikkiin. Muusan määritelmää ei tarvitse enää hyväksyttää YSO-kokouksen kautta.

**Comment by mariaforsen** [comment]
Sv. romsk musik (underhållningsmusik) ET zigenarmusik, zigensk musik (underhållningsmusik)

**Comment by MUUSA-kokous** [comment]
Määritelmä: "Musiikkityyli, jossa viululla ja cimbalomilla on keskeinen rooli ja jossa on tyypillisesti unkarilaisen, romanialaisen tai venäläisen kansanmusiikin elementtejä".

**Comment by mirmaid** [comment]
Termimuutos myös SLM:ään.

**Comment by asormune** [comment]
Milloin nämä saataisiin myös Fintoon?

**Comment by mirmaid** [comment]
Hyväksytty/SLM
