### ISSUE TITLE
folkmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6683]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[folkmusiikki](http://www.yso.fi/onto/ysa/Y95175) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Määritelmä: "Alkuperältään angloamerikkalainen, perinnemusiikin tyyleihin ja sävelmiin nojautuva akustisen musiikin tyylilaji, joka syntyi 1950-luvun puolivälissä ja kukoisti erityisesti 1960-luvun alkupuolella myös Yhdysvaltojen ulkopuolella." Määritelmä antaa folkmusiikista turhan historiallisen kuvan. Genre on suosittu edelleen. Toisaalta folk-levyillä voi olla mukana myös sähkösoittimia. Akustisuus on ehkä ideaali, mutta harvoin toteutuu täydellisenä.

Määritelmä voisi olla alkuperäisestä muokattuna: "Alkuperältään angloamerikkalainen, 50-luvun puolivälissä syntynyt perinnemusiikista vaikutteita hakeva tyylilaji, jossa akustisilla soittimilla on yleensä keskeinen rooli."

PS. Jos muutosehdotus koskee musiikkiaiheisen käsitteen määritelmää, tarvitseeko asiaa viedä YSA-kokoukseen asti? 

#### Ehdotettu muutos   

Muutos määritelmään. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by asormune** [comment]
Ehdotettuun määritelmään laittaisin "50-luvun" tilalle "1950-luvun"

**Comment by MUUSA-kokous** [comment]
Määritelmä muutetaan muotoon:
"Alkuperältään Yhdysvalloissa ja Isossa-Britanniassa, 1950-luvun puolivälissä syntynyt perinnemusiikista vaikutteita hakeva populaarimusiikin tyylilaji, jossa akustisilla soittimilla on yleensä keskeinen rooli."

**Comment by mariaforsen** [comment]
Sv. nuvarande "folkrock (akustisk)" ok?
