### ISSUE TITLE
kuori

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6685]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuori](http://www.yso.fi/onto/ysa/Y102834) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kuoren nykyinen LT on kasvinosat. Käsitettä on kuitenkin käytetty kuvailussa laajemmin. Yleisin merkitys on puunkuori, mutta käsitettä on käytetty esim. merkityksessä munan kuori ja kotilon kuori. 

Rajataan _kuori_ kattamaan kaikki orgaaniset kuoret, jolloin ruotsin vastine _skal_ saadaan täsmämään.

Muutetaan samalla _kaarna_ muotoon **kaarna KÄ puunkuori**, jotta saadaan puunkuorta käsittelevät aineistot erotettua omaksi kokonaisuudekseen. Puunkuorta ei voi ottaa sanastoon omana käsitteenään, sillä ruotsiksi kaarna + puunkuori = bark. 

#### Perustelut ehdotukselle   

Tarvitaan täsmennyksiä, jotta kieliversiot vastaavat toisiaan ja kuvailukäyttö on yhtenäistä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
Sivuhuomioksi kuori kirkkoarkkitehtuurissa (vaikkei olekaan sanastossa, jos olisi, niin olisi muodossa _kuorit_)

**Comment by mariaforsen** [comment]
Kyllä ruotsiksi skal käy myös munankuoresta ja kotilon kuoresta, sekä myös esim. puhelimien kuorista, eli ruotsin takia ei ole pakko rajata orgaaniseen. 

Sen sijaan kyllä puunkuori on oltava samassa käsitteessä kuin kaarna, koska ne ovat tosiaan =bark.

**Comment by mirmaid** [comment]
Ensimmäiset 50 viitettä:
- puun kuori (selvästi eniten); joko tietyn lajin tai yleisesti, paljon aineistoa kuoren käytöstä rehuna
- perunan, hedelmien, kauran, soijapavun
- munien
- simpukan, etanan
- leivän
- siitepölyn
- viruksen
- maankuori (on sanastossa erikseen)

**Comment by mirmaid** [comment]
Kaarna = puunkuori olisi ongelmallinen ratkaisu, koska (suomeksi) kaarna on puun ulkokuori ja myös nila ja mahdollisesti jälsi voidaan vähän vaihtelevasti laskea kuuluviksi kuoreen.

**Comment by tpalonen** [comment]
Eikö puunkuori olisi silti ihan käypä käsite ja kaarna-merkitys sisältyisi siihen?

**Comment by YSO-kokous** [comment]
Muutetaan kaarna-käsitteen käytettäväksi termiksi puunkuori, ohjaustermiksi kaarna JA "kuori (puunkuori)".

Käydään kuori-kuvailu läpi. Korjataan puunkuoreksi näin soveltuvat. Tutkitaan, tarvitaanko jäljelle jääville oma kuori-tyyppinen käsitteensä.

**Comment by mirmaid** [comment]
Jäljelle jäi 37 viitettä, joissa siis

- perunan, hedelmien, kauran, soijapavun

- munien

- simpukan, etanan ymv.

- leivän, makkaran

- siitepölyn

- joitakin kertoja rakennustekniikan yhteydessä (ei pelkästään kirkoista), jossa kuori=skal varmasti väärin

**Comment by mariaforsen** [comment]
Sv. skal käy tosi laajasti (merkitys: "(hårt) tunt skyddande hölje"), mutta ei toki kirkon kuoreen, se pitäisi varmaan ottaa erikseen (=sv. kor)

**Comment by ilona-x** [comment]
munankuoret ehdotettu aiemmin https://github.com/Finto-ehdotus/YSE/issues/4414

FinMeSH: 
munankuori http://www.yso.fi/onto/mesh/D004528
eläinten kuoret http://www.yso.fi/onto/mesh/D060105

**Comment by jtuohini** [comment]
Sivuhuomautus: suomeksikin kirkon kuori taipuu eri tavoin kuin nuo muut perusmuodossaan samannäköiset sanat, ei siis _kuori_, _kuoret_ vaan _kuori_, _kuorit_ (ja siitä edelleen _kuorissa_, _kuoriin_, _kuoreissa_, _kuoreihin_).

**Comment by mirmaid** [comment]
Eli kuori ei ehkä sovi:
https://melinda.kansalliskirjasto.fi/byid/006788730
https://melinda.kansalliskirjasto.fi/byid/000688621
https://melinda.kansalliskirjasto.fi/byid/011634419 
https://melinda.kansalliskirjasto.fi/byid/003073010

http://www.opeoy.fi/kuorirakenteet/

**Comment by FinMeSHienPaimentaja** [comment]
kuoret (biologia) tai kuoret (eliöt): kasvien osat, eläinten osat, munankuoret?
virusten kuoret /viruskuoret [sisältyisi kuoret (biologia)]
kuorit (rakennukset) tai (rakennusten osat)?
makkaran kuoret, leivän kuori <-> kuoret yleiskäsitteenä?

**Comment by jtuohini** [comment]
Miten olisi _kuorit (arkkitehtuuri)_? Kuori ei ole itsessään rakennus, eikä YSO:ssa ole "rakennusten osat" -asiasanaa. Pääryhmän 91 (jonka alle tämä ainakin menisi) taas on nimeltään Arkkitehtuuri.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon kuorit (arkkitehtuuri).
Säilytetään kuori-käsite sellaisenaan ilman sulkutarkennetta.
Lisätään kuori-käsitteelle käyttöhuomautus: Puunkuorista käytä puunkuori

Keskustelua: Äänestettiin kuori-käsitteen säilyttämisestä vs. eri merkitysten ottamisesta (esim. munankuori) erillisinä käsitteinään : kaikki kannattivat kuori-käsitteen säilyttämistä sellaisenaan. Sivuhuomio: arkkitehtuuri-yhteydessä kuori-käsitettä ei toistaiseksi ole käytetty kirkkojen yhteydessä, vaan rakennuksen katteena tms.

**Comment by jtuohini** [comment]
Itse asiassa Melindassa on pari artkikelia, joissa on käsitelty kirkkojen kuoreja, mutta tieto oli 653-kentässä.
