### ISSUE TITLE
Hietamäki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6686]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hietamäki](http://www.yso.fi/onto/ysa/Y156086) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Hietamäki (Inkeri/Venäjä) 

#### Perustelut ehdotukselle   

YSAssa on nyt vain yksi Hietamäki ja se viittaa näköjään inkeriläiseen Hietamäkeen. Suomessakin on Hietamäki-nimisiä kyliä ainakin Mynämäellä ja Pieksämäellä. Tarkenne olisi tarpeen.

**Comment by mirmaid** [comment]
Wikipedia: Hietamäki (Inkeri). Paikkatyyppinä erityistapaus, joten voinee saada tarkenteen eri periaatteilla kuin kaupungit (tai toisaalta kylät).

**Comment by mirmaid** [comment]
Hietamäki (Inkeri) (RT Inkeri)
