### ISSUE TITLE
vanhentuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6688]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vanhentuminen](http://www.yso.fi/onto/ysa/Y104803) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään sulkutarkenne. Esim. "vanhentuminen (oikeus)". Lisätään vanheneminen-käsitteelle sulkutarkenne, esim. "vanheneminen (ikääntyminen)". 

#### Perustelut ehdotukselle   

Vanhentuminen-käsite viittaa oikeudelliseen vanhentumiseen (esim. velan vanhentuminen). Termi menee kuitenkin helposti sekaisin vanheneminen-termin kanssa, joka myös löytyy sanastosta. Melindassa vanhentuminen-käsitettä on käytetty muussakin kuin oikeudellisessa merkityksessä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Sanastossa on myös _ikääntyminen_.

**Comment by ilona-x** [comment]
FinMeSH: ikääntyminen KT vanheneminen http://www.yso.fi/onto/mesh/D000375

**Comment by mirmaid** [comment]
Jonkin verran myös muun kuin ihmisen vanhenemisesta, esim. _East Asian paintings : materials, structures and deterioration mechanisms_

**Comment by YSA-kokous** [comment]
vanhentuminen (oikeus)

**Comment by AuHo22** [comment]
Itselleni tuli hivenen koomisiakin assosiaatioista tästä (oikeus) sulkutarkenteesta, joka on varmaankin ihan ok joissain yhteyksissä kuten tuomarit (oikeus). On kuitenkin vaihtoehtoisesti käytetty tuota (oikeustiede) tarkennetta, joka mielestäni sopisi paremmin: haasteet (oikeustiede), kiinnitys (oikeustiede). 
Ihmisoikeudetkin ovat oikeutta, ja sanotaankin että joissain kulttuureissa esim. naisella on oikeus vanhentua eri tavalla kuin toisissa.

**Comment by mariaforsen** [comment]
Sv. preskription ok?

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi "vanhentuminen (oikeustiede)".
