### ISSUE TITLE
väsyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6689]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väsyminen](http://www.yso.fi/onto/ysa/Y104908) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään sulkutarkenne. Esim. (fysiikka) tai (aineen).
Lisätään käyttöhuomautus, esim.: "Ihmisen psyykkisen tai fyysisen väsymisen yhteydessä ks. väsymys." 

#### Perustelut ehdotukselle   

Viittaa aineen väsymiseen. Kuuluu ryhmään 7 Fysiikka, ja RT:nä rasitus. YSOn puolella käsitteellä on määritelmä: "kiinteästä kappaleesta: murtua jatkuvan tärinän, taivuttelun tms. liikkeen johdosta". Käsite menee kuitenkin helposti sekaisin ihmisen väsymiseen viittaavan väsymys-käsitteen kanssa. Melindassa käsitettä on käytetty enemmän merkityksessä ihmisen väsymys. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Löytyy vielä _rasitus_, jos siitä on apua noissa edellä mainituissa?

**Comment by mirmaid** [comment]
Mahdollinen myös _väsyminen (tekniikka)_?

**Comment by satuniininen** [comment]
_Rasitus_ ja _kuormitus_ riittäisivät lihasten väsymisen yhteyteen.

**Comment by YSA-kokous** [comment]
väsyminen (aineen/materiaalin/tekniikka)?

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/V%C3%A4syminen_(materiaalin)

**Comment by mirmaid** [comment]
LCSH: Materials |x Fatigue

YSOssa on myös _väsymislujuus_.

_Väsyminen (materiaalitekniikka)_?

**Comment by mariaforsen** [comment]
Sv. materialutmattning? https://sv.wikipedia.org/wiki/Materialutmattning = https://fi.wikipedia.org/wiki/V%C3%A4syminen_(materiaalin) 
Myös "materiaalin väsyminen"

Huom. Melindassa pahoja virheitä (ruotsin vastineella), korjataan siis mahdollisimman pian.

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi väsyminen (materiaalitekniikka).
