### ISSUE TITLE
keskittyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6690]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keskittyminen](http://www.yso.fi/onto/ysa/Y106382) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Käsite liittyy kaupan tms. keskittymiseen. YSA-ryhmänä 75 Taloustieteet. RT:nä monopolit, oligopoli, yritysfuusiot. Käsite menee kuitenkin helposti sekaisin termin muiden merkityksen kanssa, esim. ihmisen keskittyminen. Melindassa käsitettä on käytetty paljon mindfulness-kontekstissa yms.

Käsitteellä on käyttöhuomautus, mutta Melinda-kuvailu osoittaa, että pelkkä käyttöhuomautus ei selvästikään ole riittävä ohjaamaan käsitteen käyttöä kuvailussa. 

#### Ehdotettu muutos   

Lisätään sulkutarkenne. Esim. "keskittyminen (talous)". 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by satuniininen** [comment]
Melindassa käytetty myös alueellisen keskittymisen yhteydessä, esim. teollisuuden keskittyminen seutukuntiin ja asutuksen keskittyminen kaupunkeihin. Pitäisikö tämäkin käyttöyhteys erottaa omaksi käsitteekseen, esim. keskittyminen (aluekehitys)?

Jos halutaan, että yksi keskittyminen kattaa myös alueellisen ulottuvuuden, niin sulkutarkenne (talous) ei varmaankaan ole tarpeeksi selkeä. 

Lisäksi Melindassa varallisuuden keskittyminen (ehkä ohjattavissa KÄ tuloerot?)

**Comment by ilona-x** [comment]
Voisiko "asutuksen keskittyminen kaupunkeihin"-tapauksissa käyttää termiä kaupungistuminen? http://finto.fi/ysa/fi/page/Y96022

**Comment by ilona-x** [comment]
Joo, huomasin saman, kun tätä tarkemmin tutkiskelin. Miten tässä menee ruotsin/englannin vastineet, eli onko mahdollista kattaa molemmat (taloudellinen&alueellinen) merkitykset yhdellä sulkutarkenteellisella keskittymisellä? 

LCSH: Industrial concentration http://id.loc.gov/authorities/subjects/sh85065846

**Comment by mariaforsen** [comment]
Sv. koncentration + tarkenne

**Comment by mirmaid** [comment]
vrt. myös keskitys

**Comment by mirmaid** [comment]
Suurin osa viitteistä näyttää liittyvän keskittymiskykyyn. Jos otetaan erikseen

keskittyminen (talous)
keskittyminen (aluekehitys)

Helpointa ehkä ensin siivota pois keskittymiskyky ja katsoa miten paljon viitteitä jää.

_Keskityksen_ osalta usein parempi termimuoto olisi _keskittäminen_.

**Comment by tpalonen** [comment]
Voitaisiinko lisätä myös keskittymiskyvylle jokin ohjaustermi?
keskittyminen (psykologia/tms) KÄYTÄ keskittymiskyky

**Comment by YSO-kokous** [comment]
Muutetaan keskitys muotoon keskittäminen, ohjaustermiksi keskitys.
Siivotaan keskittyminen-tietueista pois keskittymiskykyyn viittaavat, eli keskittyminen korvataan näissä keskittymiskyvyllä.
Lisätään ohjaustermi: keskittyminen (psykologia) KÄYTÄ keskittymiskyky

Taustaa: Palveluiden yms yhteydessä keskittäminen olisi parempi termi tietueissa kuin keskittyminen. Tutkitaan keskittyminen-käsitteen käyttöä, korjataan tietueissa

**Comment by ilona-x** [comment]
Keskittymiskykyyn viittaavat siivottu Melindassa pois, jäljelle jäi 797 viitettä.

Tässä aiemmin mainittujen käyttötapausten lisäksi Melindassa on paljon viitteitä median/joukkoviestinten omistuksen keskittymisestä. SAOssa tämä näyttää olevan erikseen:
Ämnesord 	  	Mediekoncentration
LCSH 	  	  	Mass media - Ownership

Ja SAOssa tämän lisäksi vielä:
Ämnesord 	  	Mediekonvergens
LCSH 	  	  	Convergence (Telecommunication)

-- 
https://en.wikipedia.org/wiki/Concentration_of_media_ownership
https://sv.wikipedia.org/wiki/Mediekonvergens
https://fi.wikipedia.org/wiki/Mediakonvergenssi

**Comment by ilona-x** [comment]
Melindassa myös muutamia viitteitä vallan keskittymisestä.

Lisäksi vielä huomiona, että yritysten osalta näyttäisi olevan sekä omistajuuden keskittymistä että yritysten sijainnin alueellista keskittymistä. Osaan viitteistä kävisi aiemmin ehdotettu yrityskeskittymät https://github.com/Finto-ehdotus/YSE/issues/2676, joka löytyy myös JUHOsta: http://www.yso.fi/onto/juho/p87

**Comment by ilona-x** [comment]
Ja vielä LCSH:
Industrial concentration    http://id.loc.gov/authorities/subjects/sh85065846
KT    Combinations, Industrial
KT    Concentration, Industrial
**KT    Economic concentration**

Oligopolies http://id.loc.gov/authorities/subjects/sh85094604
**KT Economic concentration**

--
oligopoli on YSOssa http://www.yso.fi/onto/yso/p9190

**Comment by mirmaid** [comment]
_Mediakonvergenssia_ on aikaisemmin ehdotettu, https://github.com/Finto-ehdotus/YSE/issues/1534. Toisaalta YSOssa on _konvergenssi_, eikä mediakonvergenssilla (kai) tavallisesti viitata omistajuuden keskittymiseen yhden mediatyypin sisällä.

**Comment by ilona-x** [comment]
Mediakonvergenssi tuli vastaan tuolla eng. wikipedia-artikkelissa: "Concentration of media ownership (also known as media consolidation or media convergence) "

**Comment by mirmaid** [comment]
Suomenkielisessä wikipediassa puhutaan myös taloudellisesta konvergenssista, mutta sain sen vaikutelman, että tästä puhuttaisiin vain jos useampia mediatyyppejä yhdistyy fuusion tms. kautta.

**Comment by mirmaid** [comment]
Kävisikö osalle jäljellejääneistä _alueellinen keskittyminen_ (KT keskittyminen (aluekehitys))?

**Comment by mirmaid** [comment]
Ja voiko osa olla _keskittyminen (talous)_ KT omistuksen keskittyminen tjsp (ml. media-ala)?

**Comment by mirmaid** [comment]
Jos ylläolevat hyväksytään, korjataan taas eteenpäin ja jatketaan sen jälkeen?

**Comment by tpalonen** [comment]
Btw, keskittäminen myös urheilutermi (futis) ja puolustustermi (tykistö). Ongelma?

**Comment by mariaforsen** [comment]
Tässä oli kai kysymys termistä keskittyminen. Sanastossa on myös keskittäminen KT sentralisaatio=centralisering.

**Comment by LeKorsu** [comment]
> Ja SAOssa tämän lisäksi vielä:
> Ämnesord Mediekonvergens
> LCSH Convergence (Telecommunication)

Mediakonvergenssi tarkoittaa kyllä muuta kuin median omistuksen keskittymistä, en sotkisi sitä tähän. Se tarkoittaa teknologian, viestinnän ja sisältöjen yhteyttä.
https://www.britannica.com/topic/media-convergence

**Comment by mirmaid** [comment]
Nyt päätetään siis osittaisista ratkaisuista:

- alueellinen keskittyminen (KT keskittyminen (aluekehitys)

- keskittyminen (talous) KT omistuksen keskittyminen

**Comment by YSO-kokous** [comment]
Hyväksytään Mirjan viimeisin ehdotus.

**Comment by mariaforsen** [comment]
Sv. 
-regional koncentration ET regional koncentrering
-koncentration (ekonomi) ET ekonomisk koncentration, ägarkoncentration

**Comment by mariaforsen** [comment]
Eli pelkkä keskittyminen poistetaan? Nyt sanastossa on sekä keskittyminen että keskittyminen (talous) =ei sallittua

**Comment by mirmaid** [comment]
Suurin osa viitteistä (oli >800) oli korjattavissa _keskittyminen (talous)_ tai _alueellinen keskittyminen_. 

Jäljellä olevista jonkin verran _vallan keskittymistä_ (usein yhteydessä omistuksen keskittymiseen).

Lisäksi _varallisuuden keskittyminen_, korjataanko nämäkin > _keskittyminen (talous)_? On kuitenkin vähän eri kuin esim. yritysfuusiot, mutta toisaalta aika läheinen omistuksen keskittymiselle...(esim. https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4oma_2000-luvulla). Ks. myös https://melinda.kansalliskirjasto.fi/byid/002616255

**Comment by mirmaid** [comment]
Joitakin kertoja myös toimintojen keskittyminen julkisella sektorilla, esim. https://melinda.kansalliskirjasto.fi/byid/013175724, https://melinda.kansalliskirjasto.fi/byid/013092630, https://melinda.kansalliskirjasto.fi/byid/002268165 (?) - näissä ehkä keskittäminen?

**Comment by mirmaid** [comment]
Työpaikkojen keskittyminen isoille yrityksille, alueellisten työmarkkinoiden keskittyminen: https://melinda.kansalliskirjasto.fi/byid/013035577.

**Comment by mirmaid** [comment]
Keskittyminen johonkin tiettyyn, fokusointi: https://melinda.kansalliskirjasto.fi/byid/005794504, https://melinda.kansalliskirjasto.fi/byid/013537974

**Comment by mariaforsen** [comment]
Kyllä, centralisering=keskittäminen sopii yllä oleviin, paitsi fokusointi-tapauksiin. Ruotsiksi fokusoinnista käytettäisiin fokusering jonka fi-vastine on kohdentaminen YSOssa (!)

**Comment by YSO-kokous** [comment]
### Päätökset äänestyksen jälkeen
Ei oteta sanastoon "varallisuuden keskittyminen" omana käsitteenään, vaan käytetään keskittyminen (talous) tai rikastuminen, tuloerot jne.
Otetaan sanastoon "vallan keskittyminen" omana käsitteenään.
Poistetaan käsite "keskittyminen".

**Comment by mariaforsen** [comment]
Sv. maktkoncentration

Huom! Kielitoimiston sanakirjassa löytyy myös termi "vallankeskitys"
