### ISSUE TITLE
lääkekorvaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6692]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lääkekorvaukset 

#### Ehdotettu termi ruotsiksi   

läkemedelsersättningar 

#### Ehdotettu termi englanniksi   

reimbursements for medicine expenses 

#### Ehdotettu yläkäsite YSOssa (LT)   

[korvaukset](http://www.yso.fi/onto/yso/p4223) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Lääkekorvauksia on maksettu jo pitkään ja se on vakiintunut termi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kelan tilastot ja tutkimukset. 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [lääkekorvaukset](http://finto.fi/yse/fi/page/Y506692)

**Comment by ilona-x** [comment]
lääkekorvaukset on jo YSA:ssa: http://finto.fi/ysa/fi/page/Y195017
