### ISSUE TITLE
matkakorvaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6693]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matkakorvaukset 

#### Ehdotettu termi ruotsiksi   

reseersättningar 

#### Ehdotettu termi englanniksi   

reimbursement for travel 

#### Ehdotettu yläkäsite YSOssa (LT)   

[korvaukset](http://www.yso.fi/onto/yso/p4223) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Sairausvakuutuksesta maksetaan matkakorvauksia terveydenhuoltokäynneistä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10250/7931 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [matkakorvaukset](http://finto.fi/yse/fi/page/Y506693)

**Comment by tpusa** [comment]
Kaivataan Kelan julkaisun http://urn.fi/URN:NBN:fi-fe201803095747 (Sairausvakuutuksen matkakorvausten alueelliset erot) kuvailussa.

**Comment by mirmaid** [comment]
7 viitettä Melindassa monikossa. EKS:ssa yksikössä, 16 viitettä Melindassa.
