### ISSUE TITLE
vatsastapuhuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6694]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vatsastapuhuminen 

#### Ehdotettu termi ruotsiksi   

buktaleri (eller ventrilokvism) 

#### Ehdotettu termi englanniksi   

ventriloquism (or ventriloquy) 

#### Vaihtoehtoiset termit ja ilmaisut   

ventrilokvismi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lasten tv-ohjelmat, jossa on vatsastapuhuva mies karhukäsinukkensa kanssa: Petteri-eno, Onnenpäivän vitsi sekä Päivän vinkki. 

#### Perustelut ehdotukselle   

. 

**Ehdottajan organisaatio:** KAVI **Termiehdotus Fintossa:** [vatsastapuhuminen](http://finto.fi/yse/fi/page/Y506694)

**Comment by ilona-x** [comment]
LCSH: Ventriloquism http://id.loc.gov/authorities/subjects/sh85142757
SAO: Buktaleri
