### ISSUE TITLE
poikatutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6695]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

poikatutkimus 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Antti Kivijärvi, Tuija Huuki & Harry Lunabba (toim.): Poikatutkimus 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [poikatutkimus](http://finto.fi/yse/fi/page/Y506695)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2633
