### ISSUE TITLE
arvo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6696]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[arvo](http://www.yso.fi/onto/ysa/Y116055) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään arvo-käsitteelle sulkutarkenne, esim. talous. Lisätään myös arvot-käsitteelle sulkutarkenne, esim. etiikka/moraali/filosofia/käsitykset. Lisätään molemmille käyttöhuomautus, jossa viittaus toiseen käsitteeseen. 

#### Perustelut ehdotukselle   

Käsitteiden välinen merkitysero ei välity termien avulla, varsinkin kun ajatellaan YSOn lisääntyvää käyttöä kirjastokentän ulkopuolella. Käsitteillä ei myöskään ole määritelmää tai huomautusta, josta ero ilmenisi. Melindassa on käytetty käsitteitä jonkin verran väärin tai ristiin: esim. "Asiakasarvoa luova HRM pk-yrityksissä" kuvailtu käsitteellä arvot ja toisaalta "'Meidän pitää muistaa ne arvot, joilla me tehdään se homma' : arvojen merkitys suomalaisessa pankkiorganisaatiossa" kuvailtu käsitteellä arvo. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
arvo
1. se minkä perusteella jtak pidetään merkityksellisenä, hyvänä, arvokkaana tms., merkitys, kantavuus. Mainos-, uutisarvo. Tunnearvo. Arvonsa säilyttävä keksintö. Vain tosiasioilla on pysyvä arvo.
2. us. mon. arvokas, merkitsevä asia. Elämän tärkeimmät arvot. Kauneus-, kulttuuriarvo. Korvaamattomia taidearvoja. Kaikkien arvojen uudelleenarviointi.
3. kunnia, arvokkuus, arvovalta, vaikutusvalta. Ihmisarvo. Arvonsa tunteva. Olla arka arvostaan. Jkn arvon mukainen, arvolle sopiva. Arvoa alentava, loukkaava. Arvossa pidetty [= arvostettu] taiteilija, koulu. Isänmaallisuus oli taas arvossaan. Asettaa t. kohottaa jku, jk oikeaan arvoonsa. Hänen arvonsa on noussut silmissäni. Antaa arvoa toisten mielipiteille kunnioittaa, arvostaa toisten mielipiteitä. Jättää loukkaus omaan arvoonsa sivuuttaa merkityksettömänä, harkitsemattomana, mielettömänä tms.
4. arvoaste; arvonimi, titteli. Oppiarvo. Tohtorinarvo. Sotilasarvoltaan kersantti. Saada kauppaneuvoksen arvo.
5. käypä hinta. Maatilan, irtaimiston arvo. Rahan arvo eli ostovoima. Kauppa-arvo. Nimellisarvo. Auton jälleenmyyntiarvo. Osakkeiden arvo nousee, laskee, pienenee, suurenee. Taulu myytiin alle todellisen arvonsa. Tavaroita 50 euron arvosta.
6. suureen t. luvun suuruus, numero, luku. Liki-, maksimiarvo. Itseisarvo. Mittarin asteikosta luetut arvot. Yhtälön x:n arvot.
7. Arvon us. iron. arvoisa, kunnioitettava. Kas, arvon herrat suvaitsevat lopulta saapua! 

https://www.kielitoimistonsanakirja.fi/#/arvo

**Comment by ilona-x** [comment]
YSO:

**arvo**  
ST liikearvo
ST lisäarvo
ST maanarvo
ST markkina-arvo
ST rahanarvo
ST ravintoarvo
ST tunnearvo
ST verotusarvo

Jos YSOn arvo-käsitteen on tarkoitus viitata merkitykseen 5, pitäisi alakäsitteet tunnearvo ja ravintoarvo siirtää muualle.

**arvot**
ST ihmisarvo
ST itseisarvo (filosofia)
ST luontoarvot
ST tasa-arvo
ST ympäristöarvot

**Comment by ilona-x** [comment]
YSOssa: arvofilosofia (engl. axiology) http://www.yso.fi/onto/yso/p13228
LSCH: values KT Axiology KT Worth http://id.loc.gov/authorities/subjects/sh85141939

arvo | arvofilosofia https://tieteentermipankki.fi/wiki/Filosofia:arvo

**Comment by ilona-x** [comment]
LCSHssa ei tarkenteita vaan huomautukset: 

**Value**
Here are entered works on the economic theory of value. Works on moral and esthetic values, etc. are entered under [Values.]

**Values**
Here are entered works on moral and esthetic values, etc. Works on the economic theory of value are entered under [Value.]

**Comment by mariaforsen** [comment]
Ruotsiksi vähän erilainen käsitejako siinä mielessä että myös arvot (mielipiteet/henkilökohtaiset) = värderingar. Tämä myös SAOssa ja linkattuna LCSH values Mutta tässä voisi varmaan olla korvattuna värderingar, jos pitää olla vähän laajempi merkitys. 

Entä arvo (numeerinen) jos pitää kattaa muutakin kuin taloutta?

**Comment by ilona-x** [comment]
Eli olisiko tämän alkuperäisen ehdotuksen tarkoituksena, että  jatkossa **arvo** -käsite kattaisi Kielitoimiston sanakirjan merkityksen 5 ja **arvot** merkitykset 1 ja 2?

**Comment by ilona-x** [comment]
fi      arvo
en      value

määritelmä
1. saatujen hyötyjen ja menetettyjen uhrausten erotus
2. hinta kerrottuna määrällä: esimerkiksi tuotannon ja myynnin arvo

selite
Arvo muodostuu hyötyjen ja uhrausten suhteesta. Hyötyjen vastineena tyypillisimpiä uhrauksia ovat raha, etsimiseen liittyvät kustannukset ja psyykkiset kustannukset. Arvo koetaan subjektiivisesti ja eri tavalla eri toimialakonteksteissa.
Luokitus: taloustiede
	  
Lähde: Tieteen termipankki 17.01.2020, Taloustiede:arvo
http://tieteentermipankki.fi/wiki/Taloustiede:arvo

**Comment by ilona-x** [comment]
YSOsssa myös 
**arvostus** http://www.yso.fi/onto/yso/p15140
**arvottaminen** http://www.yso.fi/onto/yso/p15139 
https://tieteentermipankki.fi/wiki/Filosofia:arvottaminen
**arvonmääritys** http://www.yso.fi/onto/yso/p9877

**Comment by ilona-x** [comment]
sanastoon ehdotettu aiemmin myös arvokkuus https://github.com/Finto-ehdotus/YSE/issues/3834

**Comment by mirmaid** [comment]
Ainakin alun perin on varmaan yksiköllisen _arvo_-termin merkityksen ajateltu kattavan rahallisen arvon lisäksi muunkinlainen "tärkeys", esim. tunnearvo, kulttuuriperintöarvo (eli suunnilleen ruotsin "värde"). 
Arvot sitten taas suunnilleen merkitys 2. Eli tyyliin "yrityksen arvo" vs. "yrityksen arvot". 

Riittäisiköhän yksikön erottamiseen sitten kuitenkin _(ominaisuudet)_? 

Monikon osalta ehkä _(etiikka)_, mutta vaatii vielä Melindan tutkimista. Välillä etiikka tarkenteena on vähän vieraannuttava (esim. arvot terveyskäyttäytymisen perustana, lapsen kasvatus, eri sukupolvien arvot, nuorten metsänomistajien arvot). 

_Arvot_-termiä käytetty kuvailussa n. 14000 kertaa. Virheellisiä näistä on ensimmäisen sadan perusteella n. 5%. Takautuva korjaaminen ei välttämättä onnistu suuren määrän takia, koska näin likeisissä käsitteissä on vaikea löytää kovin runsaasti selkeästi jompaan kumpaan merkitykseen viittaavia muita asiasanoja (esim. yrityksiä käsittelevässä aineistossa kyse on hyvin usein yrityksen arvoista ja vain toisinaan arvonluonnista).

**Comment by mirmaid** [comment]
"Toivoisimme, jos keruuta jatkatte, että vähitellen oppisitte  erottamaan tuon täysin arvottoman aineksen hyvästä ja kunnollisesta"  : Suomalaisen Kirjallisuuden Seuran Kansanrunousarkisto  perinnepoliittisena ja perinnettä arvottavana toimijana vuosina  1934-1939 https://melinda.kansalliskirjasto.fi/byid/005691289

Oikein olisi varmaan (ainakin) _arvo_, jos tarkastellaan sitä, mitä on pidetty arvokkaana kansanperinteenä - mahdollisesti myös tieteenalan _arvoja_ on voitu tutkia. Osattaisiinko kuvailla oikein, jos käytettävissä on _arvo (ominaisuudet)_ ja _arvot (etiikka)_?

**Comment by krinay** [comment]
Kamalan hankalaa. Tuon yllä olevan opinnäytetyön voisi varmaan asiasanoittaa myös termeillä _arvottaminen_ ja/tai _arvostus_. 

Jotenkin tuntuu, että tarkenteet pikemminkin sekoittavat kuin selventävät. 

Onko muu kuin selvästi rahaan ja talouteen liittyvä arvo yleensä subjektiivista eli arvostusta? Eli riittäisivätkö _arvo (talous)_, _arvot (etiikka/moraali)_ , _arvostus_, _arvottaminen_, _merkitys (tärkeys)_ jne. sekä näiden suppeammat termit. En tosin tiedä, minne ne _tunnearvo_ ja _kulttuuriperintöarvo_ tms. sijoittuisivat. Hohhoijaa.

**Comment by mirmaid** [comment]
En kovin mielelläni lähtisi supistamaan _arvo_-käsitteen merkityskenttää, koska käsitettä on käytetty niin paljon, että takautuva siivoaminen näyttää mahdottomalta, eikä tässä mielestäni ole myöskään ongelmaa kielten välillä. Jos muut ette koe, että _arvo (ominaisuudet) / värde (egenskaper)_ on edelleen niin epäselvä, että sitä käytettäisiin myös merkityksessä _arvot/värderingar_?

Suurempi ongelma mielestäni on sopivan tarkenteen löytäminen _arvot/värden_ -käsitteelle.

**Comment by mirmaid** [comment]
Molempien käsitteiden osalta virheellistä käyttöä on erittäin vähän (< 5%), huolimatta siitä, että käsitteillä ei ole ollut tarkenteita tai määritelmiä. Niiden merkitys näyttää siis hahmottuvan yleisesti varsin johdonmukaisesti - myös alkuperäisessä esimerkkiaineistossa _Meidän pitää muistaa ne arvot, joilla me tehdään se homma: arvojen merkitys suomalaisessa pankkiorganisaatiossa_ on virheellisen _arvo_-käsitteen lisäksi oikein _arvot_, ja _arvo_-käsitteen käyttö johtunee siitä, että tekijä on merkinnyt sen avainsanaksi julkaisuun, jonka tiivistelmässä myös mainitaan yhdeksi aiheeksi arvon käsitteen määrittely. 

Linjaus sulkutarkenteista on tällä hetkellä: **Kun samasta termistä on sekä yksikkö- että monikkomuotoinen käsite ontologiassa, lisätään käsitteille sulkutarkenteet, mikäli ne selventävät käsitteiden eroa.** https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSOn+kehityslinjaukset. Eli löydämmekö tarkenteet, jotka selventävät enemmän kuin sekoittavat?

_Arvo (talous)_ sopii toki suureen osaan niistä viitteistä, jotka nyt on kuvailtu yksikkömuotoisella termillä, ei kuitenkaan kaikkiin, eikä kaikkien osalta varmuudella (esim. _The invention of rare books: private interest and public memory, 1600-1840_, https://melinda.kansalliskirjasto.fi/byid/013191721; entä _The value of social media for small and medium sized enterprises: a case study in Kenya_, https://melinda.kansalliskirjasto.fi/byid/014449473). Mahdollinen korvaaja osassa viitteistä olisi _merkitys (tärkeys)_. Korjattavaa on Melindassa reilut 1000, tässä tuskin on mahdollista automatisoida korjausta. 

Toinen mahdollisuus on _arvo (ominaisuudet) / värde (egenskaper)_.

Monikolliselle mahdolliset tarkennevaihtoehdot _(etiikka)_ tai _(käsitykset)_ soveltuvat hieman vaihtelevasti (esim. organisaation arvoista puhuttaessa käsitykset ei oikein toimi, etiikka taas tuntuu toisinaan melko suppealta, esim. edellä mainitsemani arvot terveyskäyttäytymisen perustana jne.).

Olen miettinyt myös mahdollisuutta jättää molemmat ilman tarkennetta, lisätä määritelmät ja ohjaustermeiksi muotoja, joita nyt on pohdittu mahdollisina sulkutarkenteellisinä päätermeinä (esim. arvo (talous) KÄ arvo, arvot (etiikka) KÄ arvot).

**Comment by krinay** [comment]
`Olen miettinyt myös mahdollisuutta jättää molemmat ilman tarkennetta, lisätä määritelmät ja ohjaustermeiksi muotoja, joita nyt on pohdittu mahdollisina sulkutarkenteellisinä päätermeinä (esim. arvo (talous) KÄ arvo, arvot (etiikka) KÄ arvot).
`
Kannatan tätä ajatusta.

**Comment by mariaforsen** [comment]
Minusta ilman tarkenteita jättäminen sotii ontologiaperiaatteita vastaan, en siis näe vaihtoehtona, sellaista ratkaisua ei ole tietääkseni ennenkään tehty. Tuo sääntö ymmärtääkseni viittasi siihen tosiasiaan että joissakin tapauksissa monikkomuoto on jo itsessään selvä eikä tarkenne siis selvennä, esimerkiksi leikki vaatii tarkenteen (tai termin muutos>leikkiminen) mutta leikit on yksiselitteinen, kivi epäselvä mutta kivet yksiselitteinen, bibliografia epäselvä mutta bibliografiat yksiselitteinen jne. 

Ruotsin osalta voisi olla: värde (egenskaper/ekonomi), värden (värderingar/uppfattningar) eli suomeksi arvo (ominaisuudet/talous), arvot (käsitykset tms.)

**Comment by mirmaid** [comment]
_Arvot_ käytetty siis >14000 kertaa, eli "korjataan" kaikki siihen muotoon, joka tulee valituksi. _Arvo_ (1085) mahdollista käydä läpi.

**Comment by YSO-kokous** [comment]
**PÄÄTÖKSET ÄÄNESTYKSEN JÄLKEEN**
arvo (talous)  KÄYTÄ arvo (ominaisuudet)
arvot (etiikka) KÄYTÄ arvot (käsitykset)

**Comment by mariaforsen** [comment]
Sv. 
värde ANVÄND värde (egenskaper)
värden ANVÄND värderingar (uppfattningar) HT värden (uppfattningar)
