### ISSUE TITLE
merkitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6697]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[merkitykset](http://www.yso.fi/onto/ysa/Y97364) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään merkitykset-käsitteelle sulkutarkenne, esim. kieli/kielitiede. Lisätään myös sulkutarkenne käsitteelle merkitys, esim. arvo/tärkeys/merkityksellisyys/filosofia. Lisätään myös käyttöhuomautukset kummallekin käsitteelle, joihin viittaus toiseen käsitteeseen. 

#### Perustelut ehdotukselle   

Käsitteiden merkitysero ei käy ilmi termistä, varsinkin kun ajatellaan sanaston käyttöä kirjastokentän ulkopuolella. Käsitteillä ei myöskään ole määritelmää tai huomautusta, josta ero selviäisi. Käsitteitä onkin käytetty Melindassa paljon väärin, erityisesti merkitykset-käsitettä, jota tuntuu käytetyn enemmän väärin kuin oikein, vrt. "Depression and the self : meaning, control and authenticity", "Onnellisuuksien oivaltaja : mitä tiede kertoo onnesta?" "Elämän tarkoitus ja vakava sairaus : ALS-tautiin sairastuneen eksistentiaalinen prosessi" Ja niin edelleen. Paljon väärinkäyttöä, joskin edellä mainittua vähemmän, on myös merkitys-käsitteellä, esim. "Kulttuurisanoja läheltä ja kaukaa", Tip of the tongue : reflections on language and meaning".

Käsitteiden merkityskentät ovat jatkumo, niissä on päällekkäisyyttä, esimerkiksi kaikki kielifilosofinen kirjallisuus voisi sijoittua tälle yhteisalueelle. Toisaalta, merkitys-käsitettä ei voi suositella kenenkään tiedonhakijan käytettäväksi, ainakaan yksinään. Silti molemmat ovat kuvailussa niin suosittuja käsitteitä ja merkitysero on sinänsä helposti hahmotettavissa, edellyttäen että on selkeät sulkutarkenteet, että yhdistämistä ei voitane pitää vaihtoehtona. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by satuniininen** [comment]
Kielitoimiston antaa kaksi merkitystä (ehhee):

1. se mitä jk tarkoittaa, ilmaisee, esittää, symboloi; sanan t. ilmauksen informaatiosisältö; yl. sisältö, olemus. 
2. arvo, tärkeys. 

Onko _(kieli)/(kielitiede)_ riittävä sulkutarkenne vai pitäisikö käsitteen kattaa myös mahdollisten ei-kielellisten symbolien merkitys? Vai onko tämä liian kaukaa haettua?

Monikolliseen _(filosofia)_ ei tunnu tarpeeksi erottelukykyiseltä suhteessa kielitoimiston ensimmäisen merkityksen loppuosaan _yl. sisältö, olemus._ Vaikka toisaalta ehdottajan mainitsemaa harmaata aluetta tulee joka tapauksessa jäämään. 

_merkitys (arvo)_ tai _merkitys (tärkeys)_ noudattelisi kielitoimiston määritelmää.

**Comment by mirmaid** [comment]
Näitä on käytetty aika paljon ristiin, korjattavaa paljon.

**Comment by mariaforsen** [comment]
Sv. mening vs. betydelse (mening ANV meningsfullhet?). Esim. livets mening=elämän tarkoitus, livets betydelse eri asia.
Merkitys (kieli)=betydelse (språk)

**Comment by mirmaid** [comment]
Onko (kieli/kielitiede) parempi kuin (semantiikka)?

**Comment by mirmaid** [comment]
Myös (merkityksellisyys) voisi olla tarkenne. Arvo, tärkeys ja merkityksellisyys sopivat aineistosta riippuen hieman vaihdellen, esim. työn merkitystä ihmiselle käsittelevissä julkaisuissa mikä tahansa olisi suunnilleen yhtä onnistunut. Kun tarkastellaan esim. koulutuksen merkitystä yhteiskunnan tasolla, (merkityksellisyys) ei ole toimiva, mutta (arvo) ja (tärkeys) ovat mahdollisia, ensimmäinen ehkä hieman parempi. Lapsen lukemisen merkitystä käsittelevässä aineistossa (tärkeys) olisi ehkä kaikkein lähinnä. Elämänfilosofian, psykologian ja ns. harmaan alueen (esim. jään merkitys ihmiselle) aineistoissa usein jollain tavalla sopisi joko merkitys (merkityksellisyys) tai pelkkä merkityksellisyys.

Mahdollista myös (sikäli kuin onnistuu ruotsiksi) ottaa joko merkitys (arvo) tai merkitys (tärkeys) ja lisäksi merkityksellisyys, jos näyttää että se olisi usein toimivampi kuin merkitys (+tarkenne).

**Comment by mirmaid** [comment]
Mutta olisiko lukemisen merkitys (lapsen kehitykselle) tai koulutuksen merkitys yhteiskunnassa ruotsiksi mening/meningsfullhet? Oma korvani sanoo että olisivat ruotsiksi ennemmin betydelse (tai esim. roll). 

Jos ruotsiksi _meningsfullhet = merkityksellisyys_, olisi ehkä parempi ottaa suomeksikin joko se, tai esim. _merkitys (psykologia)_, ja kuvailla muut tapaukset muilla termeillä (arvo, vaikutukset, tms.)?

**Comment by mariaforsen** [comment]
Yllä mainitut lukemisen tai koulutuksen merkitys... ovat nimenomaan betydelse.
Toisaalta meningsfullhet on mielekkyys ja se on myös jo sanastossa... Muita mening-termejä ei varmaan tarvita?

**Comment by mirmaid** [comment]
Ehdotus kaiken tämän jälkeen:

merkitykset KÄ merkitys :woman_cartwheeling:

**Comment by AuHo22** [comment]
Merkitykset -asiasanaa on paljon  käytetty yleisten kirjastojen aineistoissa juuri sen takia (YSAssa ryhmässä **00 Yleistermit** ryhmän 85 Kielitieteen lisäksi), ettei ole ollut ns. "merkityksellisyys" tms. -termiä. Ks. kommentti yllä:  "Elämänfilosofian, psykologian ja ns. harmaan alueen (esim. jään merkitys ihmiselle) aineistoissa usein jollain tavalla sopisi joko merkitys (merkityksellisyys) tai pelkkä merkityksellisyys".
Kyse ei siis ole sanan varsinaisesta väärinkäytöstä kuten yllä asia ilmaistaan, vaan operoimisesta olemassaolevilla käsitteillä. Mielestäni jokin vastaava käsite kuitenkin tarvitaan.

**Comment by YSA-kokous** [comment]
merkitykset (semantiikka)
merkitys (tärkeys)
merkityksellisyys KÄ mielekkyys
