### ISSUE TITLE
baletti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6698]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[baletti](http://www.yso.fi/onto/ysa/Y94851) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteillä baletti ja baletit on YSOssa sulkutarkenteina (taidelajit) ja (teokset). Tarkenteet tarvitaan myös YSAan.

Vastaavissa tapauksissa on aiemmin vältytty sulkutarkenteelta muuttamalla päätermiä esim. teatteri --> teatteritaide, ooppera --> oopperataide, mutta se ei taida tässä tapauksessa onnistua. 

#### Ehdottajan organisaatio   

YSO 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
YSOssa käytetty sekä tarkennetta _(taidelajit)_ että _(taiteet)_.

**Comment by YSA-kokous** [comment]
baletti (taiteet) ja baletit (teokset)
