### ISSUE TITLE
ihminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6699]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ihminen](http://www.yso.fi/onto/ysa/Y95490) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

yhdistetään ihmiset KT ihminen

Sanastossa on tällä hetkellä **ihminen** ja **ihmiset**. Yksikkö-monikko-parit vaativat sulkutarkenteet, mutta tässä tapauksessa niiden keksiminen saattaa olla hankalaa. Lisäksi käsitteitä on käytetty kuvailussa paljolti päällekkäin. 

#### Perustelut ehdotukselle   

Käyttökerrat Melindassa:

ihminen 4 959
ihmiset 191
molemmat yhdessä ~78 (huom. ei selaushakuhaku)

Monikollinen esiintyy pääsääntöisesti aineistoissa, joissa ihmistä käsitellään ryhmänä yksilöitä ja näkökulmana on ihmisyys sosiaalisena tai yhteiskunnallisena roolina, esim:

Myyr York : Humans of Myyr York
650 asukkaat
650 ihmiset
650 kaupungit
650 valokuvat
650 henkilövalokuvaus

sota ja mielenrauha
650 sota
650 ihmiset
650 sota |x kokemukset
650 psyykkiset vaikutukset

Yksiköllinen esiintyy aineistoissa, joissa näkökulma on enemmän luonnontieteellinen, erityisesti biologinen, lääketieteellinen tai filosofinen. Yhdistämisen myötä monikon käyttö laajenisi myös aineistoihin, kuten _Matka sydämeen : kaikki kehomme tärkeimmästä elimestä; Sapiens : Ihmisen lyhyt historia; Eläin ja ihminen : mikä meitä yhdistää?_

Sanastosta löytyy myös **henkilöt.** 

#### Ehdottajan organisaatio   

YSO

**Comment by jtuohini** [comment]
Ihminen yksikössä viitannee ihmiseen biologisena lajina, monikossa taas nimettäviin henkilöihin yksittäin tai joukolla. Siis aika eri asiasta kyse ja tuntuu yhdistäminen arveluttavalta.

**Comment by satuniininen** [comment]
^ Periaatteessa varmaan näin, mutta kuvailukäyttö on ollut hyvin päällekkäistä.

**Comment by jtuohini** [comment]
Täydennykseksi: en tarkoittanut, että **ihmiset**-asiasanalla kuvailtaisiin samaa kuin **henkilöt**-asiasanalla, vaan että nämä termit ovat samassa hierarkiapuussa, edellinen laajempana (= joukko henkilöitä, esim. kohortin tapaan yms), jälkimmäinen suppeampana (= yksilö). _À propos_, pitäisikö sanastoon lisätä asiasanalle **henkilöt** KT-muoto _yksilöt_? (Taidankin heti tehdä ehdotuksen.)

**Comment by mirmaid** [comment]
Ehdotan että yhdistetään ihmiset KÄ _ihminen_. Viimeisten kahden vuoden aikana _ihminen_-termiä on käytetty Melindassa 802 kertaa, monikkoa 57 kertaa. Monikkoa on kaiken kaikkiaan käytetty 1132 kertaa. Joissakin tapauksissa se ei ole kovin tyylikkäästi korvattavissa yksiköllä, näissä kuvailuissa koko termi on usein kuitenkin tarpeeton (esim. sota - kokemukset - ihmiset). Jos monikolliset on tarpeen käydä yksitellen läpi, ehdotan että siirretään yhdistäminen konversion jälkeen tehtäväksi.

**Comment by YSA-kokous** [comment]
ihmiset KÄ ihminen

**Comment by mariaforsen** [comment]
Sv. människan ET människa, människor
