### ISSUE TITLE
taide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6700]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taide](http://www.yso.fi/onto/ysa/Y99223) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite ja lisätään taide ohjaustermiksi käsitteelle taiteet. 

#### Perustelut ehdotukselle   

Käsitteiden taide ja taiteet välillä ei ole selvää merkityseroa eikä sanasto selvennä eroa millään tavallisen tiedonhakijan ymmärtämällä tavalla. Määritelmiä ja huomautuksia ei ole eikä ero selviä termeistä. Molemmilla on sama YSA-ryhmä. Pragmaattisesti ajateltuna yhden käsitteen merkitys kattaa toisen: taide yleisesti on yhtä kuin kaikki taiteet ja toisinpäin. Luulisi olevan harvinaista, että kirja käsittelee taidetta yleisellä tasolla nimeämättä lainkaan yksittäisiä taidelajeja tai poimimatta esimerkkejä. Vaikka tällaista esiintyisikin, yhden käsitteen luulisi riittävän. Käsitejaolla on YSAssa ja YSOssa ollut tietty hierarkisoiva tehtävä, mutta tämä voidaan korvata muulla tavoin.

Melindassa käsitteitä on käytetty hyvin samanlaisissa konteksteissa. On vaikea nähdä selkeää eroa käyttökonteksteissa. Niitä on käytetty myös paljon yhdessä.

Ehdotan, että "taiteet" olisi yhdistetyn käsitteen käytettävä termi ja "taide" ohjaustermi. Monikkomuoto tuntuu yleispätevämmältä, vaikka yksikkömuoto saattaakin tuntua joskus sopivammalta ainakin jos aineistossa käytetään yksikkömuotoa. Taide yksikössä yhdistyy herkästi kuvataiteisiin.

Vrt. myös kielet vs kieli, johon on ehdotettu vastaavaa muutosta. https://github.com/Finto-ehdotus/YSE/issues/5842

Vrt. LCSH:sta löytyy Art ja Arts, mutta Art on rajattu visuaalisiin taiteisiin, joka löytyy YSAsta erikseen.
"Art: Here are entered general works on the visual arts. Works on the arts in general, including the visual arts, literature, and the performing arts, are entered under." 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
Paremminkin pitäisi laittaa toisinpäin eli _taiteet_ KÄ **taide**, jos termitä väkisin halutaan yhdistää. Vastakohta taiteelle kuvailun yhteydessä on paremminkin viihde – joka ei mitenkään vastaavasti voisi olla muodossa "*viihteet", siis sanaparissa 'taide' ~ 'viihde'. Ja asiasana **taiteet** voitaisiin ehkä muuttaa muotoon _taiteenlajit_, sitähän se varsinaisesti tarkoittaa.

**Comment by mariaforsen** [comment]
Sv. taiteet=konstarter, taide=konst.

**Comment by mirmaid** [comment]
Nyt YSOssa _tiede_ + _tieteenalat_, _tanssi_ + _tanssilajit_, kulttuurit KÄ _kulttuuri_, _kieli ja kielet_.

**Comment by mariaforsen** [comment]
Ruotsiksi onkin ollut aina: konst=taide, konstarter=taiteet (oikeastaan taidelajit). Eikö olisi syytä tehdä vastaavalla tavalla kuin muissa vastaavissa tapauksissa tehtiin eli taide, taidelajit?

**Comment by jtuohini** [comment]
Olisiko ennemmin _taiteenlajit_ kuin _taidelajit_? Kielitoimiston sanakirjasta löytyvät molemmat, mutta jälkimmäinen silti särähtää korvaani. [https://www.kielitoimistonsanakirja.fi/taiteenlaji]

**Comment by mirmaid** [comment]
Ilmeisesti suosituin vaihtoehto olisi taiteet KÄ _taiteenlajit_?

**Comment by tpalonen** [comment]
Google fight:
taidelaji 33900 vs. taiteenlaji 83300
Voittaja: taiteenlaji

**Comment by YSO-kokous** [comment]
Muutetaan taiteet muotoon taiteenlajit. Ohjaustermiksi taiteet, ja taidelajit.
