### ISSUE TITLE
koulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6701]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koulu](http://www.yso.fi/onto/ysa/Y96395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään koulut KT koulu 

#### Perustelut ehdotukselle   

Molempia on käytetty paljon, muttei ihan johdonmukaisesti. Esiintyvät usein myös yhdessä samoissa tietueissa. YSOssa on käytössä sulkutarkenteet koulu (ilmiöt) ja koulut (oppilaitokset), mutta etenkin yksiköllinen muoto on hankala rajata ja sulkutarkenne voi tuntua hieman vieraannuttavalta. Yksiköllistä muotoa on käytetty 
esim. puhuttaessa koulun ja kodin välisestä kasvatuskumppanuudesta tai koulutoimen lainsäädännöstä, mutta näihinkin voisi sopia joko monikollinen termimuoto tai täsmällisempi käsite, esim. koulutoimi tai kouluhallinto. 
Sanastossa on myös koululaitos, koulunkäynti, koulurakennukset jne. 

#### Ehdottajan organisaatio   

YSO

**Comment by satuniininen** [comment]
Koulu ja koululaitos ovat varmasti merkitykseltään hyvin likeisiä. Koululaitos kuitenkin kuulostaisi monissa yhteyksissä liian viralliselta, ja tuottaisi esim. seuraavanlaisia kuvailuja:  

- _Yläkoululaisten koulu-uupumus :koulu-uupumuksen muutokset, sukupuolierot ja yhteydet akateemisiin taitoihin sekä itsetuntoon_
koululaitos + koululaiset + uupumus

- _Classroom matters :research with children as entanglement_ 
koululaitos + luokat + opetustilat

- _A  brief introduction to a philosophy of music and music education as social praxis_ 
musiikkikasvatus + koululaitos +musiikkifilosofia

Näihin monikollinen koulut sen sijaan sopisi varsin mallikkaasti.

**Comment by jtuohini** [comment]
Noista ensimmäisessä selvästikin _koululaitos_-asiasanana pitäisikin olla _koulunkäynti_. Pitäisikö toisessa vastaavasti olla _koulut_? Kolmannessa ei _koululaitos_ kuulosta mahdottomalta, jos kyse on musiikinopetuksesta osana järjestettyä perusopetusta yms. Muutoin siinä varmaan turha.

**Comment by ilona-x** [comment]
Melinda:
koulu 8990
koulut 7106

Kielitoimiston sanakirja:
koulu
1. **(alempi) opetus-, oppilaitos.** Maamme koulut. Yksityinen, valtion koulu. Koulun opettajat, oppilaat. Koulun oppimäärä. Esi-, perus-, ammatti-, korkeakoulu. Musiikkikoulu. Pyrkiä, päästä kouluun.
2. eräissä yhdyssanoissa kurssimuotoisesta opetuksesta. Pyhä-, rippikoulu. Uimakoulu.
3. koulurakennus, -talo, -huoneisto. Koulu on torin laidassa. Koulun piha. Viipalekoulu. Kokous koululla.
4. **kouluopetus, -opiskelu, -työ; koulunkäynti.** Koulu alkaa, päättyy. Lauantaisin ei ole koulua. Olla poissa koulusta. Käydä koulua olla oppilaana koulussa. Käydä koulu läpi, loppuun. Koulua, kouluja käynyt oppinut, sivistynyt. Jättää koulunsa kesken. Pitää koulua opettaa koulussa; harjoittaa yksityistä koulutoimintaa.
Kuv. Sotaväki, miesten koulu. Kokemuksen kova koulu. Elämän koulu myös →←. Harjoittelupaikka oli hyvä koulu tulevaa varten.
5. **koululaitos, -järjestelmä.** Koulun uudistaminen.
6. vars. mus.
a. järjestelmällinen oppikurssi; sellaisen sisältävä oppikirja(sarja). Kitara-, viulukoulu.
b. koulutus; koulutuksen tuottama taito. Viulistin mainio koulu kävi ilmi jo ensi tahdeista.
7. koulukunta. Rafaelin, Düsseldorfin koulu. Italialainen laulukoulu. Vanhan koulun romaani. Runoilija-, maalarikoulu. 

Jos nämä yhdistetään niin helpointa olisi korjata nyt käytetyt **koulu-asiasanat muotoon koulut**. Jos halutaan korjata tietueet siten, että koulu korvataan välillä termillä koulunkäynti ja muilla sopivilla termeillä, niin olisiko mahdollista siirtää tämä yhdistämis-/korjausurakka konversion jälkeiseen aikaan? Ohjaukset voisi tehdä useampaan vaihtoehtoon eli **koulu KÄYTÄ koulut, koulu KÄYTÄ koulunkäynti, koulu KÄYTÄ koululaitos.**

Melinda-viitteiden perusteella paras korvaava vaihtoehto voi mainittujen koulut, koulunkäynti & koululaitos -termien lisäksi olla myös jokin muu esim. alakoulu, yläkoulu, peruskoulu, kansakoulu, perusopetus, opetus, koulutus, kasvatusyhteistyö jne.

**Comment by YSA-kokous** [comment]
koulu KÄ koulut, koulunkäynti, koululaitos
