### ISSUE TITLE
tanssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6703]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssit](http://www.yso.fi/onto/ysa/Y99309) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite. Lisätään tanssi-käsitteelle ohjaustermi tanssi. Siirretään poistuvan käsitteen alakäsitteet jäljelle jäävän alle. 

#### Perustelut ehdotukselle   

Tanssi ja tanssit käsitteille on vaikea hahmottaa selkeää merkityseroa. Käsitteillä ei ole määritelmiä, huomautuksia tai sulkutarkenteita. Alakäsitteistä voi päätellä, että monikkomuoto edustaa tanssilajeja ja yksikkömuoto tanssia "yleensä". On kuitenkin vaikea nähdä, että tässä olisi kyse kahdesta eri käsitteestä, korkeintaan kahdesta käyttökontekstista. Melinda-kuvailukin osoittaa, että näitä on käytetty varsin samalla tavalla, monesti myös yhdessä. Monesti kuvailuun sopisi yhtä hyvin kumpi tahansa. Yksikkömuoto on monikkomuotoa paljon käytetympi.

Käytettyyden ja intuitiisivuuden vuoksi kannatan, että yksikkömuoto jäisi käytettäväksi termiksi.

ps. Pohdintaa herättää tässä yhteydessä myös tesaurusstandardin terminmuodostuskäytäntö. SFS 5471 -standardissa mainittu poikkeus, jonka mukaan ainesanaa kuvaavat ryhmäkäsitteet ("juustot" edustaa juustolajeja, "metallit" edustaa metalleja) nimetään yksikön sijaan monikkomuotoon, on ongelmallinen ja tuottaa sanastoon hajontaa. Onko tällaisen poikkeuksen noudattaminen ontologiakontekstissa edelleen järkevää? Nykykäyttäjät tuntevat entistä vähemmän tesaurusstandardeja ja niissä mainittuja poikkeuksia. Periaatteessahan mistä tahansa yksikkömuotoisesta termistä voi tällä periaatteella muodostaa ryhmäkäsitteen: afrotanssit edustaa eri afrotanssilajeja, agilityt erilaisia agilitylajeja. Tällainen tuskin kuitenkaan palvelee käyttäjää. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Täydennys ehdotukseen: "Siirretään poistuvan käsitteen alakäsitteet jäljelle jäävän alle."

**Comment by jtuohini** [comment]
Nykyinen **tanssi**-asiasana voitaisiin muuttaa muoto _tanssiminen_ tms. Nykyinen asiasana **tanssit** taas voitaisiin muuttaa muotoon _tanssilajit_. Tällöin asiasanat itsessään kertoisivat jo huomattavasti paremmin, mihin niillä pyritään viittaamaan.

**Comment by mirmaid** [comment]
Jos monikkomuoto poistetaan, vaihdetaanko yksikkömuotoisten alakäsitteiden tarkenne muotoon _(tanssi)_ ja siirretäänkö kaikki alakäsitteet (myös monikkomuotoiset) _tanssin_ alle?

**Comment by mirmaid** [comment]
Omaan korvaani _tanssi_ tuntuu miellyttävämmältä kuin _tanssiminen_ taidelajista puhuttaessa (esim. teatteritaide - tanssi(minen) - taiteidenvälisyys; vähän erilainen sävy on myös yhdistelmillä tanssi + opetus ja tanssiminen + opetus).

**Comment by jtuohini** [comment]
Jos **tanssit** muutettaisiin muotoon _tanssilajit_, niin ainakin niissä tapauksissa tarkenne olisi selvä. Muilta osin minun on kovin vaikea nähdä, miten sellainen asia tai ilmiö kuin tanssit/tanssilajit voitaisiin yhtäkkiä heittää sanastosta pois, tyytyen pelkkään tanssiin/tanssimiseen yleensä.

**Comment by mirmaid** [comment]
_Tanssit_-termiä on käytetty tanssilajien ohella jonkin verran tansseista tapahtumina (_Riihitanssien hämärästä häiden iloiseen hoijakkaan : nurkkatanssit nuorten seurustelumuotona 1800-luvun lopun ja 1900-luvun alun Etelä-Pohjanmaalla_). Lisäksi toisinaan väljemmin, esim. [_Täpinää tassuihin : materiaalia alle kouluikäisten tanssi- ja leikkikasvatukseen_](https://www.booky.fi/tuote/anu_kokkonen/tapinaa_tassuihin_materiaalia_alle_kouluikaisten_tanssi/9789529919260), _Tanssi tavallasi : rytmejä liikuntahetkiin_. Tämäntyyppisissä aineistoissa riittäisi varmaankin _tanssi_. _Tanssit_ tai _tanssilajit_ tuntuisi nimenomaan tanssioppaissa toimivammalta kuin pelkkä _tanssi_. LCSH:ssa kuitenkin Dances USE Dance.

Olisiko ongelma, jos sanastossa olisi _tanssi_ ja _tanssilajit_ KT tanssit?

**Comment by YSA-kokous** [comment]
tanssit KÄ tanssi ja tanssilajit

**Comment by mirmaid** [comment]
Entä nykyisen _tanssilajit_-käsitteen alakäsitteiden tarkenteet?

**Comment by tpalonen** [comment]
Tanssilajit-käsitteen alakäsitteille sulkutarkenteeksi (tanssilajit)?

**Comment by YSO-kokous** [comment]
Ei tehdä muutoksia. Käytettävien termien muutos aiheuttaisi paljon tekemistä tietokannoissa.
