### ISSUE TITLE
James Bond -elokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6705]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

James Bond -elokuvat 

#### Ehdotettu termi ruotsiksi   

James Bond-filmer 

#### Ehdotettu termi englanniksi   

James Bond films 

#### Vaihtoehtoiset termit ja ilmaisut   

James Bond -filmit 
Bond-elokuvat 
Bond-filmit 
Bond-filmer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elokuvat](http://www.yso.fi/onto/yso/p1235) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85069330> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Quantifying the emotional tone of James Bond films / Rose Ann Kozinski 

#### Perustelut ehdotukselle   

Tarvitaan jokin sopiva kattotermi Bond-elokuville, ettei tarvitse listata kaikkia yksitellen 630-kentissä (vrt. https://helka.finna.fi/Record/helka.2405789), jos tarkastelu on yksittäisten elokuvan osalta vähäistä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [James Bond -elokuvat](http://finto.fi/yse/fi/page/Y506705)

**Comment by jtuohini** [comment]
Tämä olisi syytä ottaa takaisin käsiteltäväksi, analogisena jo hyväksytty [**Star Wars -elokuvat**](http://www.yso.fi/onto/yso/p39921) ja vasta ehdotuksen asteella oleva [**Pekka ja Pätkä -elokuvat**](https://github.com/Finto-ehdotus/YSE/issues/12800). Kuvailutarve nimittäin ei ole kadonnut mihinkään, ks. esim. https://melinda.kansalliskirjasto.fi/byid/018124159, https://melinda.kansalliskirjasto.fi/byid/017634243 ja https://melinda.kansalliskirjasto.fi/byid/007038785.

**Comment by mariaforsen** [comment]
Myös SAOssa: https://id.kb.se/term/sao/James%20Bond-filmer
Sv. James Bond-filmer HT Bondfilmer, Bond-filmer

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
