### ISSUE TITLE
lautatarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6707]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lautatarhat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[logistiikka](http://www.yso.fi/onto/yso/p9140) 
[sahatavara](http://www.yso.fi/onto/yso/p1742) 

#### Perustelut ehdotukselle   

Suosittu asiasana/aihe mikä tallennuttu kuvailemaan kuvaa Finnassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.finna.fi/Search/Results?lookfor=%22lautatarhat%22&type=Subject&dfApplied=1&limit=20 

**Ehdottajan organisaatio:** Mikkelin Taidemuseo / TYP **Termiehdotus Fintossa:** [lautatarhat](http://finto.fi/yse/fi/page/Y506707)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _sahatavaran kuivatus- ja varastointialue, us. sahatavaroineen._

**Comment by mariaforsen** [comment]
Sv. brädgårdar
