### ISSUE TITLE
mellanåldersböcker

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6708]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

mellanåldersböcker 

#### Ehdotettu termi suomeksi   

varhaisnuorten kirjallisuus

#### Ehdotettu termi englanniksi   

pre-teens literature

#### Vaihtoehtoiset termit ja ilmaisut   

barnlitteratur / ungdomslitteratur 

#### Ehdotettu yläkäsite YSOssa (LT)   

[litteratur](http://www.yso.fi/onto/yso/p8113) 

#### Tarkoitusta täsmentävä selite   

Litteratur som riktar sig till barn i åldern 9-12år 

#### Perustelut ehdotukselle   

Genreämnesordet används i Sverige (Libris) och hjälper till att klassificera böcker som riktar sig just till målgruppen "lite äldre lågstadiebarn" 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://haku.helmet.fi/iii/encore/record/C__Rb2354791__Sangerborn__P0%2C5__O-date__U__X0?lang=fin&suite=cobalt 

**Ehdottajan organisaatio:** Helsingfors stadsbibliotek, enheten för material och metadata **Termiehdotus Fintossa:** [mellanåldersböcker](http://finto.fi/yse/fi/page/Y506708)

**Comment by jtuohini** [comment]
Varmaan tarvetta termille olisi siis (myös) SLM-sanastoon? Kohderyhmäkentässä tuon pystyisi kaunokirjallisuuden osalta ilmaisemaan jo nykyisellään ("385 __ |m Ikä |n age |a varhaisnuoret |2 ysa"), myös vuosien tarkkuudella ("521 1_ |a 009-012").

**Comment by mirmaid** [comment]
Varhaisnuoruudelle löytyy hyvin erilaisia ikähaarukoita (7-14, 11-16).

**Comment by mariaforsen** [comment]
Onko tarpeeksi selkeä?

**Comment by mirmaid** [comment]
Ei SLM-sanastoon.

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7819

**Comment by AuHo22** [comment]
Yllä: "_Varmaan tarvetta termille olisi siis (myös) SLM-sanastoon? Kohderyhmäkentässä tuon pystyisi kaunokirjallisuuden osalta ilmaisemaan jo nykyisellään ("385 __ |m Ikä |n age |a varhaisnuoret |2 ysa"), myös vuosien tarkkuudella ("521 1_ |a 009-012")."_

Valitettavasti nykyjärjestelmissä yo. vaihtoehdot toimivat huonosti ja mahdollisesti hyvin pitkään. Esim. Finna-näytöissä ei 385-termi näy välttämättä ollenkaan, vaikka sillä voi kuitenkin hakea. Toinen asiaan liittyvä ongelma on sekoittuminen asiasanakäyttöön, eli vasta Melindan komentohaussa Boolen logiikan avulla kykeni rajaamaan asiasanakäytön pois kohderyhmähausta. Ehkä kirjastojen virkailijapäätteillä voi päästä samaan tulokseen, mutta on otettava huomioon asiakkaiden etähakujen yleistyminen samoin kuin omatoimikirjastot, jolloin henkilökuntaa ei ole paikalla / ei välttämättä ole kykyä monimutkaisempiin hakuihin.

Libriksessä käytetty yli 11 000 kertaa genreterminä, ja Kirjastopalvelussa on jatkuvasti lisääntynyttä käyttöä vastaavissa aineistoissa. Kyse on tiedon näkyvyydestä / saavutettavuudesta. Kirjastopalvelussa ei koettu hankalana ikäkauden kategorisoimista, vaan otetaan termi käyttöön viime kädessä local-tunnisteen avulla, jos kokous ei lämpene slm-termille. Tällöin termi saadaan kirjastojen tietokantoihin, mutta tippuu sitten Melindasta pois. Toisaalta SLM-termin puolestaan voi tulevaisuudessa konvertoida 385-kenttään?

"_En näe “ikäkauden rajaamista” ongelmana. Miksi olisi tarpeen rajata ikävuodet - eihän sitä tehdä vastaavassa “nuorten aikuisten kirjat” -termissäkään.
Kyseessä sis.kuvailijan mutu, tarkkaa vuosirajausta ei voitane tehdäkään. Itse kuitenkin pitäisin aika osuvana tuota 9-12 (ehkä -13). 14-16 on selkeästi jo nuoriso-osastoa_."

**Comment by ilona-x** [comment]
https://id.kb.se/term/barngf/Mellan%C3%A5ldersb%C3%B6cker
