### ISSUE TITLE
superkondensaattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6709]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Supercapacitors 

#### Ehdotettu termi suomeksi   

superkondensaattorit 

#### Ehdotettu termi ruotsiksi   

suprakondensatorer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kondensaattorit](http://www.yso.fi/onto/yso/p11972) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2007002091> 
wikipedia : https://fi.wikipedia.org/wiki/Superkondensaattori 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Printed supercapacitors for energy harvesting applications 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Tarkoitusta täsmentävä selite   

https://yle.fi/uutiset/3-10420070 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [superkondensaattorit](http://finto.fi/yse/fi/page/Y506709)

**Comment by mariaforsen** [comment]
Sv. superkondensatorer ET suprakondensatorer
