### ISSUE TITLE
matkaketjut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6711]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matkaketjut 

#### Ehdotettu termi ruotsiksi   

resekedjor 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matkat](http://www.yso.fi/onto/yso/p366) 

#### Tarkoitusta täsmentävä selite   

"Matkaketju on matka, joka on tehty vähintään kahdella kulkuneuvolla. Esimerkiksi osa matkasta on tehty linja-autolla ja osa taksilla." https://www.kela.fi/matkakorvaus-kulkuneuvo 

#### Perustelut ehdotukselle   

Toistuvasti tarpeen Liikenneviraston julkaisujen kuvailussa.
Pelkkä matkat -termi ei aina riitä kuvaamaan esim. vaihtamista kulkuneuvosta toiseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-255-412-3 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [matkaketjut](http://finto.fi/yse/fi/page/Y506711)

**Comment by mirmaid** [comment]
https://www.vr.fi/cs/vr/fi/mika-on-matkaketju
