### ISSUE TITLE
Merikappeli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6712]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Merikappeli 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Merikappeli 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Merikappeli 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Merikappeli](http://finto.fi/yse/fi/page/Y506712)

**Comment by mariaforsen** [comment]
Sv. Havskapellet (Obbnäs) ET Merikappeli, Havskapellet
