### ISSUE TITLE
sumerinkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6715]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sumerinkielinen kirjallisuus 

#### Ehdotettu termi englanniksi   

Sumerian literature 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjallisuus](http://www.yso.fi/onto/yso/p8113) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85130415> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 

#### Perustelut ehdotukselle   

käytetty Melindassa 24 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Women's writing of ancient Mesopotamia 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sumerinkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y506715)

**Comment by mariaforsen** [comment]
Sv. sumerisk litteratur
