### ISSUE TITLE
uhanalaiset luontotyypit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6716]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uhanalaiset luontotyypit 

#### Ehdotettu termi englanniksi   

endangered habitat types 

#### Ehdotettu termi ruotsiksi   

hotade naturtyper 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luontotyypit](http://www.yso.fi/onto/yso/p20751) 

#### Assosiatiiviset (RT)   

[uhanalaiset biotoopit](http://www.yso.fi/onto/yso/p557) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Tarkoitusta täsmentävä selite   

Käsite "uhanalainen luontotyyppi" ... on otettu laajasti käyttöön uutena työkaluna luonnonsuojelua ja luonnon monimuotoisuuden tilan parantamista tukevissa hankkeissa. 
Ensimmäinen arviointi valmistui v. 2008, toinen arviointi tehdään v. 2016-2018
Lähde: Kokko ym.: Suoluontotyyppien uhanalaisuuden arviointi. Suo 2018:1, s.13-17 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arto 

#### Perustelut ehdotukselle   

YSAssa on muitakin "uhanalaiset"-käsitteitä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto / Päivi Lipsanen **Termiehdotus Fintossa:** [uhanalaiset luontotyypit](http://finto.fi/yse/fi/page/Y506716)

**Comment by mirmaid** [comment]
Meneekö sekaisin _uhanalaiset biotoopit_ -termin kanssa? Biotooppi ja luontotyyppi ovat molemmat YSAssa, mutta usein ne esitetään synonyymeinä (esim. Ympäristösanasto, Wikipedia).

**Comment by mariaforsen** [comment]
Uhanalaiset luontotyypit paljon enemmän käytetty (google)?

**Comment by YSA-kokous** [comment]
Päivi: uhanalaiset biotoopit KÄ uhanalaiset luontotyypit?

**Comment by YSA-kokous** [comment]
Hyväksytään uhanalaiset biotoopit KÄYTÄ uhanalaiset luontotyypit.

Päivi: Viranomaiset käyttävät luontotyyppi-termiä.

**Comment by mariaforsen** [comment]
Sv. hotade naturtyper ET hotade biotoper
