### ISSUE TITLE
henkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6718]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[henkilöt](http://www.yso.fi/onto/ysa/Y112553) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "ihmisyksilöt" ja "yksilöt" 

#### Perustelut ehdotukselle   

Yksilö on yhtä kuin ihmisyksilö eli henkilö 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Yksilö voi viitata muihinkin kuin ihmisiin. En kannata muotoa "yksilöt" ohjaustermiksi.

**Comment by YSA-kokous** [comment]
Ei muutosta.

**Comment by jtuohini** [comment]
Tuomaksen kommentti otti kantaa ehdotetuista KT-muodoista vain yksilöön, ei ihmisyksilöön. Mitä sen ottamisen suhteen, vai vastustiko YSA-kokous todella sitäkin?
