### ISSUE TITLE
totuuselokuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6720]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

totuuselokuva 

#### Ehdotettu termi englanniksi   

cinéma vérité 

#### Vaihtoehtoiset termit ja ilmaisut   

direct cinema [eng] 
truth cinema [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elokuva (taiteet)](http://www.yso.fi/onto/yso/p16327) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh00008573> 
Wikidata : https://www.wikidata.org/wiki/Q1092621 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.457616 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [totuuselokuva](http://finto.fi/yse/fi/page/Y506720)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Cin%C3%A9ma_v%C3%A9rit%C3%A9

Kerran Melindassa

**Comment by mariaforsen** [comment]
Sv. cinéma-vérité
