### ISSUE TITLE
muinaisjäännökset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6721]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muinaisjäännökset](http://www.yso.fi/onto/ysa/Y97519) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

kiinteät muinaisjäännökset on nyt ohjaustermi YSAssa ja YSOssa. Ehdotan, että kiinteät muinaisjäännökset olisi muinaisjäännökset käsitteen alakäsite. 

#### Perustelut ehdotukselle   

Kiinteä muinaisjäännös on muinaismuistolain (295/1963) tarkoittamaksi muinaismuistoksi tulkittu ja lain suojaama arkeologinen kohde, termiä muinaisjäännös käytetään myös yksittäisistä rakenteista tai kiinteän muinaisjäännöksen osista (ks. Tieteen termipankki).
 … Kiinteä muinaisjäännös viittaa vain MML:n tarkoittamiin ja rauhoittamiin kohteisiin (ks. Enqvist: Suojellut muistot : Arkeologisen perinnön hallinnan kieli, käsitteet ja ideologia, 2016)

Käsitettä kiinteät muinaisjäännökset on Helka-tietokannassa käytetty 100 bib-tietueessa (masa-käsitteenä) 

#### Ehdottajan organisaatio   

Museoviraston kirjasto

**Comment by mirmaid** [comment]
https://www.stat.fi/meta/kas/kmuinaisjaannos.html
https://www.finlex.fi/fi/laki/ajantasa/1963/19630295

**Comment by mariaforsen** [comment]
Sv. fasta fornlämningar
