### ISSUE TITLE
elokuvaleikkaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6730]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

elokuvaleikkaajat 

#### Ehdotettu termi englanniksi   

motion picture editors 

#### Ehdotettu termi ruotsiksi   

filmklippare 

#### Vaihtoehtoiset termit ja ilmaisut   

redigerare (redigerare) [swe] 
leikkaajat (elokuva) TAI VASTAAVALLA SULKUTARKENTEELLA 
film editors [eng] 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85088041> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1476776 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [elokuvaleikkaajat](http://finto.fi/yse/fi/page/Y506730)

**Comment by YSA-kokous** [comment]
Tutkitaan, leikkaajat (media)

**Comment by LeKorsu** [comment]
Keskustelin muutaman meidän talon leikkaajan kanssa. Heidän mukaansa leikkaaja on varsinainen ammattinimike, vaikka elokuvaleikkaajan kokemusta onkin mahdollisuus korostaa termissä. Pelkällä teatterielokuvan leikkaamisella ei moni leikkaaja Suomessa itseään päätoimisesti elätä. Ehdotukseni onkin:
leikkaajat (media)
elokuvaleikkaajat KÄ leikkaajat (media).
Perusteluina lähinnä se, että eiköhän yksi ammattinimike riitä.

**Comment by LeKorsu** [comment]
Tai pitäisikö sulkutarkenteen olla (elokuva ja media), jos/kun elokuva on taiteenlaji eikä tiedotusväline?

**Comment by YSA-kokous** [comment]
leikkaajat (elokuva ja media)
elokuvaleikkaajat KÄ leikkaajat (elokuva ja media)

**Comment by mariaforsen** [comment]
Sv. klippare (film och media) ET filmklippare
