### ISSUE TITLE
soittolistat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6736]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soittolistat 

#### Ehdotettu termi englanniksi   

playlists 

#### Ehdotettu termi ruotsiksi   

låtlistor 

#### Assosiatiiviset (RT)   

[diskografiat](http://www.yso.fi/onto/yso/p9079) 

#### Vastaava käsite muussa sanastossa   

LCSH ("broader match" -tyyppisenä) : <http://id.loc.gov/authorities/subjects/sh2008109811> 
Wikidata : https://www.wikidata.org/wiki/Q1569406 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Sanastossa ei ole vanhastaan täsmälleen osuvaa käsitettä tämän aika paljon arjessa käytetyn sijaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2258567 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [soittolistat](http://finto.fi/yse/fi/page/Y506736)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa soittolistojen ottamista sanastoon. Käsite viittaa periaatteessa kahteen asiaan (radion soittolistat ja Spotify-tyyppiset soittolistat), mutta rajanveto näiden välillä on hankalaa ja siksi kannatamme, että otetaan tässä vaiheessa vain yksi soittolistat-käsite, joka kattaa molemmat merkitykset.
