### ISSUE TITLE
matkakorvaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6740]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matkakorvaukset 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10138/228351 

#### Perustelut ehdotukselle   

tämä olisi selkeä ja käytetty termi, nyt matkat, korvaukset, matkakustannukset 

**Termiehdotus Fintossa:** [matkakorvaukset](http://finto.fi/yse/fi/page/Y506740)

**Comment by ilona-x** [comment]
aiempi ehdotus matkakorvaukset: https://github.com/Finto-ehdotus/YSE/issues/6693
