### ISSUE TITLE
tulosmanipulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6741]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tulosmanipulaatio 

#### Ehdotettu termi ruotsiksi   

matchfixning 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vedonlyönti](http://www.yso.fi/onto/yso/p5571) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Littorin & Svenungsson: Matchfixarna, https://www.lindelows.se/nyheter/matchfixarna 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa, pelkkä korruptio ei tunnu riittävän tarkalta. 

**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [tulosmanipulaatio](http://finto.fi/yse/fi/page/Y506741)

**Comment by mirmaid** [comment]
KT sopupelit

_Sopupelit_ käytetty Melindassa 2 kertaa, _tulosmanipulaatio_ kerran, mutta aivan eri merkityksessä. Google-haulla tuloksista suurin osa on urheilua, ja tulosmanipulaatio on sopupelit-termiä monikäyttöisempi, mutta vaatiiko kuitenkin tarkenteen?

**Comment by mariaforsen** [comment]
Entä resultatmanipulering?

**Comment by YSA-kokous** [comment]
tulosmanipulaatio (urheilu)
