### ISSUE TITLE
Välivuokraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6745]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Välivuokraus 

#### Ehdotettu termi englanniksi   

forward rental 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Välivuokraus on uudenlainen menetelmä, jota käytetään asunnottomuustyössä. Välivuokraus on merkattu valtiollisen  asunnottomuuden ennaltaehkäisy (AUNE) -ohjelmaan yhdeksi menetelmäksi. Välivuokrauksesta julkaistaan painettu opas 10/2018, sekä verkkojulkaisu ympäristöministeriön sivuilta jaettavaksi. 

#### Tarkoitusta täsmentävä selite   

Välivuokrauksessa organisaatio tai muu toimija vuokraa eteenpäin asuntoa, jonka on vuokrannut omiin nimiinsä. Välivuokraus mahdollistaa vuokralla asumisen henkilölle, joka ei itse pysty hankkimaan itselleen asuntoa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Välivuokra-asuttamisen opas 

**Ehdottajan organisaatio:** ViaDia Pirkanmaa **Termiehdotus Fintossa:** [Välivuokraus](http://finto.fi/yse/fi/page/Y506745)

**Comment by mirmaid** [comment]
Myös _jälleenvuokraus_. Ei Melindassa.

**Comment by YSA-kokous** [comment]
Seuraava kokous, kumpi muoto vakiintuu

**Comment by mariaforsen** [comment]
MOTissa ja TEPAssa jälleenvuokraus-sanoja. Fintossa OIKO-ontologiassa jälleenvuokraus. Ei välivuokrausta.

**Comment by ilona-x** [comment]
"Välivuokra-asuttamisessa vuokralaista ja vuokranantajaa velvoittaa laki asuinhuoneiston vuokrauksesta. Laissa (L481/1995) käytetään käsitteitä jälleenvuokraussuhde ja ensivuokrasuhde. Jälleenvuokraussuhde syntyy, kun ensivuokralainen eli vuokranantajalta huoneiston vuokrannut vuokraa koko huoneiston omalle vuokralaiselleen."
Lähde: Välivuokra-asuttamisen opas https://asuntoensin.fi/assets/files/2018/10/Valivuokra_asuttamisen_opas.pdf

**Comment by YSA-kokous** [comment]
jälleenvuokraus

**Comment by mariaforsen** [comment]
Sv. andrahandsuthyrning ET uthyrning i andra hand, återuthyrning
