### ISSUE TITLE
salakauppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6746]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[salakauppa](http://www.yso.fi/onto/ysa/Y104257) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT laiton kauppa 

#### Perustelut ehdotukselle   

http://eurovoc.europa.eu/drupal/?q=request&uri=http://eurovoc.europa.eu/387171 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. svart handel, illegal handel, olaga handel...?
