### ISSUE TITLE
kansallisteatterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6748]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kansallisteatterit 

#### Ehdotettu termi ruotsiksi   

nationalteatrar 

#### Ehdotettu termi englanniksi   

national theatres 

#### Ehdotettu yläkäsite YSOssa (LT)   

[teatterit (organisaatiot)](http://www.yso.fi/onto/yso/p3203) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

Oma teatterityyppistä, jolle ei ennestään ole täsmälllistä asiasanaa, vaikka osalle muita vastaavia on jo oma asiasanansa ("kaupunginteatterit", "ylioppilasteatterit" jne). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.133130 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kansallisteatterit](http://finto.fi/yse/fi/page/Y506748)

**Comment by mirmaid** [comment]
4 viitettä Melindassa (keskeisenä aiheena kolmessa on Suomen kansallisteatteri, mutta termi lienee silti ok).
