### ISSUE TITLE
vankilateatterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6749]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vankilateatterit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Tarkoitusta täsmentävä selite   

(...) Vankilateatteriprojekteissa vangit käsikirjoittavat ja esittävät näytelmän ammattiteatterissa aidolle yleisölle. Apunaan heillä on ammattilaisohjaaja ja tuotantotiimi. Yhteisöllisyyden ja luottamuksen kokemukset olivat kannustaneet ja velvoittaneet osallistujia esityksen valmistamisen eri vaiheissa ja mahdollistaneet onnistumisen kokemuksen. (...)

https://www.rikosseuraamus.fi/fi/index/ajankohtaista/tiedotteetjauutiset/Tiedotteetjauutiset2018/09/vankilateatterivahvistaavapaudessatarvittaviataitoja.html 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3164860 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [vankilateatterit](http://finto.fi/yse/fi/page/Y506749)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

LCSH: Prison theater

**Comment by YSA-kokous** [comment]
vankilateatteri
