### ISSUE TITLE
kotisirkka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6750]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kotisirkka 

#### Ehdotettu termi ruotsiksi   

hussyrsa 

#### Ehdotettu termi englanniksi   

house cricket 

#### Vaihtoehtoiset termit ja ilmaisut   

Acheta domestica 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sirkat](http://www.yso.fi/onto/yso/p26661) 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/Kotisirkka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Käytetty Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Heinäsirkat ja hepokatit liikkuvat hyppien : samaan suorasiipisten hyönteislahkoon kuuluvat lähisukulaiset pystyvät lentämäänkin vaikka liikkuvat useimmiten hyppien. 

**Termiehdotus Fintossa:** [kotisirkka](http://finto.fi/yse/fi/page/Y506750)

**Comment by PaiviLipsanen** [comment]
https://laji.fi/taxon/MX.43193
