### ISSUE TITLE
abortti (eläimet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6751]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

abortti (eläimet) 

#### Ehdotettu termi ruotsiksi   

abort (kastning) 

#### Ehdotettu termi englanniksi   

Abortion in animals 

#### Vaihtoehtoiset termit ja ilmaisut   

luominen 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lisääntyminen](http://www.yso.fi/onto/yso/p5683) 

#### Vastaava käsite muussa sanastossa   

AFO : https://finto.fi/afo/fi/page/p5836 
LCSH : <http://id.loc.gov/authorities/subjects/sh85000210.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Alkiokuolema tarkoittaa tiineyden keskeytymistä 42 päivän kuluessa munasolun hedelmöittymisestä. Abortista puhutaan, kun tarkoitetaan ennenaikaisen, itsenäiseen elämään kykenemättömän sikiön syntymistä, mikä tapahtuu tiineyden 42.–260. vuorokauden aikana. Termi luominen kattaa alkiokuoleman ja abortin. Tämän aikajakson jälkeen tiineyden päättyessä ennenaikaisesti puhutaan ennenaikaisesta syntymästä. Täysiaikainen vasikka voi syntyä myös kuolleena tai kuolla pian syntymän jälkeen (neonataalikuolema) (Aho, 1994). https://helda.helsinki.fi/handle/10138/157075
Evira: Naudan luominen
Abortilla eli luomisella tarkoitetaan ennenaikaista synnytystä, joka johtaa elinkelvottoman sikiön syntymään. Luomisen syyt voidaan jaotella tartunnallisiin ja ei-tartunnallisiin. 

#### Perustelut ehdotukselle   

Ihmisellä abortti on lääketieteellinen toimenpide. Eläimellä abortti on lisääntymishäiriö. Evira ja uudempi kirjallisuus näyttää käyttävän enemmän enemmän abortti- kuin luominen-käsitettä. YSAssa riittänee abortti. Ainakin tuotantoeläinten aborteista löytyy tietoa esim. Eviran sivuilta (nauta, lammas, vuohi, hevonen) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto / Päivi Lipsanen **Termiehdotus Fintossa:** [abortti (eläimet)](http://finto.fi/yse/fi/page/Y506751)

**Comment by mirmaid** [comment]
Kissoille ja koirille abortti voidaan myös tarkoituksella tehdä lääkkeellisesti. AFOssa on myös _lisääntymishäiriöt_, olisiko se tarpeellinen termi myös YSAssa? Käytetty tosin vain kerran ysa-terminä ja 78 kertaa (ml. Arto) Agriforest-terminä.

**Comment by mirmaid** [comment]
Lääketieteen termit: abortti: 1. keskenmeno (myös spontaani abortti), 2. raskaudenkeskeytys

**Comment by mariaforsen** [comment]
Sv. kastning (abort)? /NE

**Comment by YSA-kokous** [comment]
Seuraava kokous 
abortti (luominen), abortti (lisääntymishäiriöt)

**Comment by mirmaid** [comment]
Ratkaisuvaihtoehtoja:

1. otetaan sanastoon _lisääntymishäiriöt_, ei muutoksia _abortti_-käsitteeseen (YK lääketieteelliset toimenpiteet ei välttämättä estä käyttämästä myös luomisesta)

2. muutetaan _abortti_ > _abortti (raskaudenkeskeytys)_ TAI _abortti (lääketieteelliset toimenpiteet)_ ja otetaan sanastoon lisäksi jokin seuraavista:
- lisääntymishäiriöt
- abortti (luominen) TAI abortti (lisääntymishäiriöt) 
- luominen (lisääntymishäiriöt), jolloin _luominen_ muutetaan > _luominen (uskonto)_

**Comment by mariaforsen** [comment]
Mitä kaikkea halutaan tällä uudella asiasanalla kattaa? Onko turhankin tarkka yleissanastoon? Riittäisikö lisääntymishäiriöt? Minusta ei ainakaan kannata sekoittaa abortti luominen-sanaan (mukaan vain korvattuna terminä)

https://fi.wikipedia.org/wiki/Luominen_(biologia)

Sv. reproduktionsstörningar ET fortplantningsstörningar

**Comment by YSO-kokous** [comment]
Otetaan sanastoon lisääntymishäiriöt. Jätetään abortti sanastoon ilman sulkutarkennetta.

Taustaa: AFOssa luominen-käsitettä ei ole juurikaan käytetty, vaikka löytyy sanastosta. Eviran sivuillakin puhutaan abortista tässä yhteydessä, ei luomisesta. Luominen olisi tästä syystä huono käytettävä termi.
