### ISSUE TITLE
ketogeeninen ruokavalio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6752]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ketogeeninen ruokavalio 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781936303946 

#### Perustelut ehdotukselle   

Tarvetta olisi. LC:ssä ketogenic diet. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [ketogeeninen ruokavalio](http://finto.fi/yse/fi/page/Y506752)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ketogeeninen_ruokavalio
https://www.hs.fi/ruoka/art-2000005835173.html
