### ISSUE TITLE
melodraamat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6753]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

melodraamat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The bridges of Madison County 

#### Perustelut ehdotukselle   

Genresanastoon 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [melodraamat](http://finto.fi/yse/fi/page/Y506753)

**Comment by asormune** [comment]
Ihan asian vierestä, voisiko Fintossa "sanastot-osioon lisätä lyhenteen SLM kohtaan "Suomalainen lajityyppi- ja muotosanasto" ? Entä milloin MUSA-CILLA voitaisiin poistaa (taide ja kulttuuri) sanastoista? (Tai piilottaa ...)
