### ISSUE TITLE
sarjakuvataiteilijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6757]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sarjakuvataiteilijat](http://www.yso.fi/onto/ysa/Y149741) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

sarjakuvantekijät 

#### Perustelut ehdotukselle   

Metatietosanastossa on vain sarjakuvantekijä, jota käytetään suhdeterminä.
Asiasanana on kuitenkin sarjakuvataiteilijat.
Jos julkaisu sisältää tietoa sekä sarjakuvan kirjoittajista että piirtäjistä eikä niitä haluta erottaa, olisi termi sarjakuvantekijät parempi. Kirjoittaja ei kai välttämättä ole taiteilija?
Joka tapauksessa olisi hyvä, jos termit olisivat yhteneväisiä YSAssa ja Metatietosanastossa. 

#### Ehdottajan organisaatio   

Suomen Kirjastopalvelu Oy

**Comment by AnneliRe** [comment]
Ehdottajana siis Anneli Renfors / Suomen Kirjastopalvelu Oy

**Comment by jtuohini** [comment]
Metatietosanaston suhdetermillä ei välttämättä ole mitään tekemistä YSA-asiasanan kanssa, esimerkkeinä vaikkapa "oppiarvon myöntävä yhteisö" Metatietosanastossa vastaan "ammattikorkeakoulut", "yliopistot" jne. YSAssa ja erilliset "valokuvaaja" ja "valokuvaaja (ekspressio)" Metatietosanastossa vastaan "paparazzit, "lehtikuvaajat" ja "valokuvaajat" YSAssa.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _sarjakuvataiteilija = sarjakuvapiirtäjä._

**Comment by jtuohini** [comment]
Hups, näyttää MTS:ssä olevan myös [laulaja-lauluntekijä](http://urn.fi/URN:NBN:fi:au:mts:m3283), mutta sitäpä ei voi käyttää RDA:n mukaisissa tietueissa 100-kentässä, koska ekspression tekijä (tämän termin osalta siis laulaja) ei voi olla olla kyseisessä kentässä toisin kuin teoksen tekijä (säveltäjä). Laulaja-lauluntekijä MTS:ssä on siis terminä vähintään arveluttava RDA:n kannalta, kun on samanaikaisesti teoksen ja ekspression tekijä.

**Comment by mariaforsen** [comment]
Ruotsin osalta en kannata termiä "sarjankuvantekijä" (hankala kääntää)

**Comment by jtuohini** [comment]
Määritelmä RDAn liitteessä I.2.1: "**kirjoittaja**: Toimija, joka on vastuussa pääasiassa tekstimuotoisen teoksen luomisesta riippumatta teoksen mediatyypistä (esim. painettu, puhuttu, digitaalinen tai kosketeltava teksti) tai lajityypistä (esim. runo, romaani, käsikirjoitus, blogi). Käytetään myös toimijoista, jotka ovat luoneet uuden teoksen mukailemalla, uudelleen kirjoittamalla tai sovittamalla toisen teoksen tekijän teoksia, mikäli muokkaaminen on selvästi muuttanut alkuperäisen teoksen luonnetta tai sisältöä, tai ilmaisuväline on muuttunut. "

Aika kauniisti kai sarjakuvan tekstiosuuden luoneen henkilön suhde kuvailtavaan aineistoon tuohon uppoaisi. Tarkempina ovat **kokousten raportoija**, **käsikirjoittaja** (koskien ainakin elokuvia), **libretisti** (oopperoita yms) ja **sanoittaja** (lauluja). Ei ole siis erikseen runoilijaa, romaanin kirjoittajaa tai montaa muutakaan.

**Comment by YSA-kokous** [comment]
Ei muutosta
