### ISSUE TITLE
häly

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6758]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

häly 

#### Ehdotettu termi englanniksi   

noise 

#### Vaihtoehtoiset termit ja ilmaisut   

noise 

#### Ehdotettu yläkäsite YSOssa (LT)   

[äänet](http://www.yso.fi/onto/yso/p4572) 

#### Perustelut ehdotukselle   

Viime aikoina on julkaistu useita kirjoja, jotka käsittelevät hälyn käyttöä musiikissa. Asiasanastosta en löydä sopivaa termiä. Ongelmana hälyn kohdalla on se, että englanninkielinen noise-termi on hälyäänen lisäksi myös musiikkigenre. Ja varmasti usein vaikkakaan ei aina kirja, joka käsittelee hälyä musiikissa, käsittelee myös noise-genreä. Vaihtoehtona on siis ottaa yksi käsite joka jotenkin kattaisi molemmat näkökulmat tai kaksi käsitettä, jotta tulisi molemmat näkökulmat katettua. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hälyjen taide / Luigi Russolo 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [häly](http://finto.fi/yse/fi/page/Y506758)

**Comment by jaskaj** [comment]
Termi tarvinnee musiikin yhteydessä tarkenteen, esim. häly (musiikki) tai hälymusiikki.

Tieteen termipankissa on termille häly annettu seuraavat tarkenteet: häly (Sosiaalipsykologia), häly (Kielitiede) ja häly (Ilmatiede): http://tieteentermipankki.fi/wiki/Nimitys:h%C3%A4ly

Tieteen termipankissa on lisäksi termi hälymusiikki: http://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:h%C3%A4lymusiikki

Noise-genreä en lähtisi suomentamaan "hälyksi" tai "hälymusiikiksi". Ns. hälymusiikki liittyy taidemusiikin perinteeseen. Noise puolestaan genrenä on selkeämmin populaarimusiikin perinteeseen kuuluva ilmiö.

**Comment by tpalonen** [comment]
Samaan tapaan kuin eloelektroniikka-keskustelussa kommentoin, tässäkin taidemusiikin ja populaarimusiikin ero osoittautuu vanhanaikaiseksi ja keinotekoiseksi. Kentät menevät päällekkäin, musiikki on muodoltaan ja estetiikaltaan hyvin läheistä ellei identtistä, ja ainoa todellisuudessa erottava tekijä on koulutustausta. Voitaisiinko tällaisesta elitismistä jo päästä eroon? Tarkoitan, että sellaisia linjauksia, joissa tämäntyyppisiä termejä ohjeistetaan käyttämään vain taidemusiikkiin, voisi oikaista.

Suosittaisin käytettäväksi termiksi muotoa **häly (musiikki)** ja ohjaustermiksi **noise**.

**Comment by MUUSA-kokous** [comment]
Otetaan sanastoon **hälymusiikki**, suomenkieliseksi ohjaustermiksi **noise**. Yläkäsitteeksi **kokeellinen musiikki**.

Otettaneen myös SLM:ään.

**Comment by mariaforsen** [comment]
Sv. noise ET oljudsmusik

**Comment by tpalonen** [comment]
Muun muassa Wikipedian perusteella pitäisin noisea hyvänä ruotsinnoksena. Taidemusiikin kontekstissa keskeinen teos Luigi Russolon "Hälyjen taide" on näköjään ruotsiksi "Oljudens konst".

**Comment by mirmaid** [comment]
Ok SLM
