### ISSUE TITLE
hylkäys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6759]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hylkäys](http://www.yso.fi/onto/ysa/Y171407) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

On monimerkityksinen termi ja käytetty eri merkityksissä Melindassa, esim. 
-Kelan työkyvyttömyyseläkkeiden hylkäykset ja niiden vakuutuspiirikohtainen vaihtelu / Riitta Huurinainen.
-Kiinan kadotetut tyttäret / Xinran ; englannin kielestä suomentanut Taina Wallin.
-Avioero suomalaisen miehen kokemana : ero ja erosta toipuminen prosessina / Jari Koskela.
-Pienarkitusprosessissa syntyvän kokonaishylyn vähentäminen / Kari Harjuniemi.
jne.
Allärs: avslag (eli sopii vain osaan..) 

#### Ehdottajan organisaatio   

YSO-kokous 

#### Ehdotettu muutos   

Tarkennus tai jako?

**Comment by YSA-kokous** [comment]
hylkäys (jättäminen)
hylkäyspäätökset

**Comment by mariaforsen** [comment]
Sv. 
-övergivande
-avslagsbeslut ET avslag
