### ISSUE TITLE
tiivistys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6761]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tiivistys](http://www.yso.fi/onto/ysa/Y99541) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selkeytettävä suhde termiin eristys (tekniikka). 

#### Perustelut ehdotukselle   

https://github.com/Finto-ehdotus/YSE/issues/5942 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Kannatan yhdistämistä/KÄ-ratkaisua. Muuten täytyy ruotsiksi myös lisätä tarkenteita.

**Comment by YSA-kokous** [comment]
KÄ tiivisteet, eristys
