### ISSUE TITLE
malaijit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6763]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

malaijit 

#### Ehdotettu termi englanniksi   

Malays 

#### Ehdotettu termi ruotsiksi   

malajer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansat (väestöryhmät)](http://www.yso.fi/onto/yso/p3993) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Malaijit 
LCSH : <http://id.loc.gov/authorities/subjects/sh85080106.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Minorities' communication apprehension and conflict : an investigation of Kurds in Iran and Malays in Singapore 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [malaijit](http://finto.fi/yse/fi/page/Y506763)

**Comment by mariaforsen** [comment]
Sv. malajer ET malajer (folk)
