### ISSUE TITLE
naamiointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6764]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[naamiointi](http://www.yso.fi/onto/ysa/Y106339) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selvennetään/tarkennetaan? 

#### Perustelut ehdotukselle   

Käytetty vaihtelevasti Melindassa, esim. "Second World War British military camouflage : designing deception / Isla Forsyth", ja toisaalta myös: "Villit värit : kasvomaalauksia lapsille". Ruotsiksi "kamouflage", ei sovi esim. viimeksi mainittuun. 

Huom. sanastossa on myös esim. maskeeraus=maskering erikseen. 

#### Ehdottajan organisaatio   

YSO-kokous

**Comment by mirmaid** [comment]
naamiointi (kasvomaalaus) KÄ kasvomaalaus
naamiointi (maskeeraus) KÄ maskeeraus
naamiointi (suojaus) / naamiointi (sotatekniikka)

**Comment by mariaforsen** [comment]
Sv. kamouflage=naamiointi (suojaus) eli kamouflage käytetään sekä eläinten että ihmisten kohdalla, eläimet suojautuvat muiden hyökkäyksiltä (ei pelkällä värillä vaan esim. muodollakin yms.) ja ihmiset vihollisen...  Toisaalta sanastossa on jo mimikry ja suojaväri, joten ehkä ruotsiksi tämä vaatii selkeämpi tarkenne jos tämä pitää viitata vain sotaan.

**Comment by mirmaid** [comment]
ks. myös _naamioituminen_

**Comment by LeKorsu** [comment]
Minusta naamiointi (suojaus) parempi kuin naamiointi (sotatekniikka), eikö se kävisi myös eläimistä. Tuon II m-sodan esimerkkikirjassa lienee muuten kyse siitä (kirjaa tuntematta), miten on luotu puusta ym. materiaaleista lentokoneita ja muita sotavälineitä harhauttaakseen saksalaisten ilmatiedustelua etenkin Normandian maihinnousun alla, eikä sotilaiden naamioitumisesta.

**Comment by mirmaid** [comment]
Mahdollinen myös _naamiointi (kätkeminen)_. Mutta tätä ei siis voi käyttää eläimistä, koska _naamiointi_-muoto viittaa siihen että joku naamioi eläimen tai eläin naamioi pesänsä, ei siihen että eläimellä on suojaväri.

**Comment by mirmaid** [comment]
Kielivastineiden yhdenmukaisen käytön takia rajaaminen vain sotatekniikkaan olisi toimiva ratkaisu. Muissa yhteyksissä käytettäväksi jää edelleen muuta termistöä, esim. _naamioituminen, suojaus, suojaväri ja mimikry_. Suuri osa Melindan viitteistä on teatteriin liittyviä.

**Comment by YSA-kokous** [comment]
naamiointi (sotatekniikka)
naamiointi (kasvomaalaus) KÄ kasvomaalaus
naamiointi (maskeeraus) KÄ maskeeraus
