### ISSUE TITLE
palomaitohorsma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6766]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

palomaitohorsma 

#### Ehdotettu termi ruotsiksi   

mjölke 

#### Ehdotettu termi englanniksi   

Epilobium angustifolium 

#### Vaihtoehtoiset termit ja ilmaisut   

maitohorsma 

#### Ehdotettu yläkäsite YSOssa (LT)   

[horsmakasvit](http://www.yso.fi/onto/yso/p5153) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Maitohorsma 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Oligomeric ellagitannins of Epilobium angustifolium : quantification and bioactivity assessment 

#### Perustelut ehdotukselle   

maitohorsma käytetty Melindassa 28 kertaa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [palomaitohorsma](http://finto.fi/yse/fi/page/Y506766)

**Comment by mariaforsen** [comment]
Sv. mjölke (växter) ET skogsbloss, mjölkört, rallarros, duntrav, brudfackla

**Comment by PaiviLipsanen** [comment]
Näköjään sekä tieteellinen että suomenkielinen nimi on muuttunut. Laji on siirretty toiseen sukuun.
maitohorsma -> palomaitohorsma
Epilobium angustifolium -> Chamaenerion angustifolium
https://laji.fi/taxon/MX.39088
