### ISSUE TITLE
buhurt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6767]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

buhurt 

#### Perustelut ehdotukselle   

http://mcsf.fi/fi/buhurt-laijna/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Eurooppalaiset historialliset kamppailutaidot Suomessa  ISBN 978-952-67440-6-3 

#### Tarkoitusta täsmentävä selite   

Suomessa laji tunnetaan nimellä buhurt tai Medieval Combat Sport, lyhennettynä MCS. Laji on ottelua historiallisissa haarniskoissa ja tylpillä teräsaseilla. 

**Termiehdotus Fintossa:** [buhurt](http://finto.fi/yse/fi/page/Y506767)

**Comment by mariaforsen** [comment]
Sv. buhurt, medieval combat sports...? Muita englanninkielisiä synonymeja joista voisi saada apua ruotsinnokseen, onko "medieval armored combat" sama asia? Historisk europeisk kampkonst?
