### ISSUE TITLE
historian elävöittäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6768]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

historian elävöittäminen 

#### Ehdotettu termi englanniksi   

historical reenactment 

#### Ehdotettu termi ruotsiksi   

historiskt återskapande 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Eurooppalaiset historialliset kamppailutaidot Suomessa  ISBN 978-952-67440-6-3 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Historian_el%C3%A4v%C3%B6itt%C3%A4minen 

#### Tarkoitusta täsmentävä selite   

Historian harrastamista, jossa pyritään luomaan tavoitellun aikakauden ympäristö mahdollisimman todenmukaisena ja ”ennallistamaan” kohteena olevan aikakauden elämä sellaisena kuin se on ollut. 

**Termiehdotus Fintossa:** [historian elävöittäminen](http://finto.fi/yse/fi/page/Y506768)

**Comment by mirmaid** [comment]
MAO-ontologiassa. Ei Melindassa, Googlella n. 75 viitettä.

**Comment by LeKorsu** [comment]
Jättäisin vielä termiehdotukseksi.

**Comment by mariaforsen** [comment]
Sv. historiskt återskapande ET levande historia
