### ISSUE TITLE
itsensä paljastaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6769]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

itsensä paljastaminen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sukupuolinen häirintä](http://www.yso.fi/onto/yso/p5385) 

#### Perustelut ehdotukselle   

Ei ole oikein vastaavaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789515246097 Miksi miehet vilauttelevat / Caroline Hainer. 

**Ehdottajan organisaatio:** Suomen Kirjastopalvelu Oy / Anneli Renfors **Termiehdotus Fintossa:** [itsensä paljastaminen](http://finto.fi/yse/fi/page/Y506769)

**Comment by satuniininen** [comment]
Sanastossa on [ekshibitionismi](http://www.yso.fi/onto/ysa/Y133606).

**Comment by mirmaid** [comment]
Ks. myös http://finto.fi/mesh/fi/page/D005084

**Comment by jtuohini** [comment]
Sadun mainitsemaan **ekshibitionismi**-asiasanaan voisi kyllä ottaa KT:ksi ainakin muodot _itseänsäpaljastaminen_, joka löytyy Kielitietoimiston sanakirjasta [https://www.kielitoimistonsanakirja.fi/itsensäpaljastaminen], ja _itsensäpaljastelu_, joka vastaavasti löytyy Wikisanakirjasta  [https://fi.wiktionary.org/wiki/itsens%C3%A4paljastelu].

**Comment by YSA-kokous** [comment]
KÄ ekshibitionismi
