### ISSUE TITLE
Canada

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6770]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Canada](http://www.yso.fi/onto/allars/Y32202) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Ruotsiksi yleisesti käytetty termi maalle on Kanada, ei Canada. https://sv.wikipedia.org/wiki/Kanada. Olemme saaneet tästä paljon palautetta kirjastoilta. YKL:n ruotsinkielinen termi on Kanada 

#### Ehdotettu muutos   

YSOn/Allärsin ruotsinkielinen termi on Canada po. Kanada 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mariaforsen** [comment]
Aikaisemmin Allärsiin on valittu käytettävä muoto Nationalencyklopedin päätermin (eli Canada) mukaan. Monen muun auktoriteetin mukaan parempi muoto on nykyään kuitenkin Kanada, harkitaan muutosta ruotsinkielisessä sanastoryhmässä. Ks. esim. https://www.sprakbruk.fi/-/kanadensare-i-kanada
