### ISSUE TITLE
alustatalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6772]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alustatalous 

#### Ehdotettu termi englanniksi   

platform economy 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Alustatalous 

#### Perustelut ehdotukselle   

Esiintyy enenevissä määrin kuvailtavissa aineistoissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. Lauslahti, Mattila & Seppälä: Älykäs sopimus - Miten blockchain muuttaa sopimuskäytäntöjä? http://urn.fi/URN:NBN:fi-fe201803094208 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [alustatalous](http://finto.fi/yse/fi/page/Y506772)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6793

**Comment by mirmaid** [comment]
Kerran Melindassa
