### ISSUE TITLE
lohkoketju

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6773]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lohkoketju 

#### Ehdotettu termi englanniksi   

blockchain 

#### Ehdotettu termi ruotsiksi   

blockkedja 

#### Assosiatiiviset (RT)   

[tietokannat](http://www.yso.fi/onto/yso/p3056) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Lohkoketju 

#### Perustelut ehdotukselle   

Tarpeen aineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.etla.fi/julkaisut/alykas-sopimus-miten-blockchain-muuttaa-sopimuskaytantoja/

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lohkoketju](http://finto.fi/yse/fi/page/Y506773)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6801

**Comment by mirmaid** [comment]
Melindassa 8 kertaa yksikössä, 9 kertaa monikossa, 2 kertaa lohkoketjutekniikka.

**Comment by YSA-kokous** [comment]
lohkoketjut

**Comment by mariaforsen** [comment]
Sv. blockkedjor
