### ISSUE TITLE
elinviljely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6774]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

elinviljely 

#### Ehdotettu termi englanniksi   

organ culture 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viljely](http://www.yso.fi/onto/yso/p5098) 

#### Assosiatiiviset (RT)   

[kudosviljely](http://www.yso.fi/onto/yso/p18040) 
[soluviljely](http://www.yso.fi/onto/yso/p9302) 

#### Vastaava käsite muussa sanastossa   

LCSH : Organ culture: http://id.loc.gov/authorities/subjects/sh85095588 

MESH:  elinviljelymenetelmät: http://www.yso.fi/onto/mesh/D009924

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Novel culture and organoid technologies to study mammalian kidney development /Ulla Saarela. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [elinviljely](http://finto.fi/yse/fi/page/Y506774)

**Comment by mirmaid** [comment]
Lääketieteen termit: _elinten, niiden osien tai kudosten kasvatus elimistön ulkopuolella ravintoliuoksessa siten, että kudosten erilaistumisaste ja toiminta säilyvät jonkin aikaa_

**Comment by mariaforsen** [comment]
Sv. organkultur ET organodling
