### ISSUE TITLE
liikkuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6775]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liikkuminen](http://www.yso.fi/onto/ysa/Y111347) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Suomeksi liikkuminen on merkitykseltään laaja, Melindassa yli 1100 viitettä. Käytetty sekä ihmisen/ihmisten siirtymisestä paikasta toiseen, että fyysisestä liikkumisesta (liikunta, motoriikka, performanssi). 

Allärs: motionering
ALLFO: rörelse, mutta myös liike = rörelse (fenomen)

Eli YSOssa tulkittu laajempana kuin pelkkänä ihmisten fyysinen liikkuminen omin voimin jne., johon "motionering" viittaa? 

Melindassa nyt esim.
-The assessment and reduction of motion artifact in dry contact biopotential electrodes / Alper Cömert.
-Actor movement : expression of the physical being : a movement handbook for actors / Vanessa Ewan and Debbie Green.
-Liikunta kansalaisten elämänkulussa : tulkintoja liikkumisesta ja liikunnanedistämisestä / Hannu Itkonen ja Kati Kauravaara (toim.). 

#### Ehdotettu muutos   

Vaatii tarkentamista, jotta saadaan täsmälliset kielivastineet ruotsiksi ja englanniksi. Osittain voidaan ohjata muihin olemassaoleviin käsitteisiin.

#### Ehdottajan organisaatio   

YSO

**Comment by satuniininen** [comment]
huomioitava myös: 
liike
liikkeet
liikunta

Liikunnan alakäsitteet käytävä läpi.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6877

**Comment by mirmaid** [comment]
Nyt siis konversiossa
motionering > rörelse [liikkuminen]
rörelse > rörelse (fenomen) [liike]

Tilanne on kuitenkin mahdollista siivota myös konversion jälkeen. Vaatii aika monen termin yhteisen selvittelyn.

**Comment by mirmaid** [comment]
Yksi mahdollinen etenemissuunta:
liikkuminen (liikunta) KÄ liikunta (+ tarvittaessa motoriikka, motoriset taidot, liikkeet)
liikkuminen (fyysinen aktiivisuus) KÄ fyysinen aktiivisuus
liikkuminen (liike) KÄ liike
liikkuminen (liikkeet) KÄ liikkeet (?)
liikkuminen (liikkuvuus) KÄ liikkuvuus
liikkuminen (siirtyminen) KÄ liikkuvuus, matkustaminen, kulkutavat (+ tarvittaessa esim. joukkoliikenne, liikenneyhteydet, kaupunkiliikenne)
:woman_juggling:

**Comment by YSA-kokous** [comment]
liikkuminen (liikunta) KÄ liikunta (+ tarvittaessa motoriikka, motoriset taidot, liikkeet)
liikkuminen (fyysinen aktiivisuus) KÄ fyysinen aktiivisuus
liikkuminen (liike) KÄ liike
liikkuminen (liikkeet) KÄ liikkeet
liikkuminen (liikkuvuus) KÄ liikkuvuus
liikkuminen (siirtyminen) KÄ liikkuvuus, matkustaminen, kulkutavat (+ tarvittaessa esim. joukkoliikenne, liikenneyhteydet, kaupunkiliikenne)
