### ISSUE TITLE
vapautuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6777]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vapautuminen](http://www.yso.fi/onto/ysa/Y112012) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Monimerkityksinen termi eikä ruotsiksi löydy yhtä termiä, joka soveltuisi kaikissa käyttötilanteissa. Myös _vapautus_ on ongelmallinen. Sanastossa on kuitenkin runsaasti korvaavia ja osin myös täsmällisempiä käsitteitä, joilla _vapautus_ ja _vapautuminen_ voitaisiin monin paikoin korvata.

Esim.

-  _emansipaatio, vapaus, itsenäistyminen (psykologia)_ sopivat tiettyihin käyttöyhteyksiin.
- Myös _vapautuksen teologia_
- sääntelystä vapautuminen --> _deregulaatio_
- vankilasta vapautuminen --> _vapautuneet vangit_ (ei kuitenkaan sovi silloin kun vapaudutaan muusta vankeudesta kuin vankilasta?)
- orjuudesta vapautuminen --> _vapautuneet orjat_

Jos siivotaan ensin nämä pois, ja katsotaan olisiko yhtenäiset kielivastineet löydettävissä jäljelle jääneelle setille. 

#### Perustelut ehdotukselle   

Melindan 100 ensimmäistä viitettä:

- estoista, täydellisyyden tavoittelusta, menneisyyden painolastista, pelosta, riippuvuudesta, demonista (elämäntaito, psykologia, uskonto); myös "tajunnan vapautuminen huumeiden ansiosta"
- myös kollektiivisesti jostain normista tms. esim. The Pathologies of Individual Freedom, naisten vapautuminen (jälkimmäistä voi pitää myös yhteiskuntakehityksenä ja onkin osa sitä, mutta "vapautuja" ei ole yhteiskunta)
- konkreettisemmin sorrosta, vielä konkreettisemmin orjuudesta tai vankeudesta (myös muusta kuin vankilasta). Tämän ja ensimmäisen kohdan väliltä lienee vapautuminen jostain liikkeestä tai ryhmästä.
- yhteiskuntakehitys (koko yhteiskunnan muuttuminen vapaammaksi)
- sääntelystä vapautuminen, esim. kannabiksen käytön vapautuminen, markkinoiden vapautuminen, lehdistökirjoittelun vapautuminen Neuvostoliitossa (tätä voi varmaan pitää yhtä lailla sääntelystä vapautumisena tai yhteiskuntakehityksenä, mutta "vapautuja" ei ole koko yhteiskunta)
- lääkkeen vapautuminen elimistöön, kasvihuonekaasun vapautuminen järvestä, typen vapautuminen maaperästä. 

Sanastossa myös vapautus, jota käytetty seuraavasti:

- konkreettisesti vankeudesta, myös muusta kuin vankilasta
- sorrosta, orjuudesta tms., usein vapautuksen teologia
- asevelvollisuudesta tms. velvoitteesta (esim. työnantajan vapauttaminen sosiaaliturvamaksusta); vapautus munkkilupauksesta
- sääntelystä (matkustuskielto, sähkömarkkinat)
- pyydetyn kalan vapautus, eläimen vapautus luontoon. Myös eläimen vapautus samaan tapaan vankeudesta kuin ihmisen (suoranaisesta eläinrääkkäyksestä tai huonoista oloista). 

#### Ehdottajan organisaatio   

YSO

**Comment by mariaforsen** [comment]
Melindan 100 ensimmäistä viitettä:

    estoista, täydellisyyden tavoittelusta, menneisyyden painolastista, pelosta, riippuvuudesta, demonista (elämäntaito, psykologia, uskonto); myös "tajunnan vapautuminen huumeiden ansiosta" 
tähän voisi sopia frigörelse, befrielse

    myös kollektiivisesti jostain normista tms. esim. The Pathologies of Individual Freedom, naisten vapautuminen (jälkimmäistä voi pitää myös yhteiskuntakehityksenä ja onkin osa sitä, mutta "vapautuja" ei ole yhteiskunta) 
jos kyseessä naisten vapautuminen patriarkaalisesta järjestelmästä jne: emancipation

    konkreettisemmin sorrosta, vielä konkreettisemmin orjuudesta tai vankeudesta (myös muusta kuin vankilasta). Tämän ja ensimmäisen kohdan väliltä lienee vapautuminen jostain liikkeestä tai ryhmästä. 
jos fyysisestä vankeudesta: frigivning (on myös SAOssa) ..onko mahdollista että sanastossa olisi yksi termi tälle: vaputuminen/vapautus + tarkenne (fyysisestä vankeudesta/vankeudesta) tms.? tämä olisi frigivning 

    yhteiskuntakehitys (koko yhteiskunnan muuttuminen vapaammaksi)
"bli friare" vaikeaa kuvailla yhdellä termillä ruotsiksi, eikö yhtä hyvin voisi asiasanoina olla yhteiskuntakehitys + vapaus?

    sääntelystä vapautuminen, esim. kannabiksen käytön vapautuminen, markkinoiden vapautuminen, lehdistökirjoittelun vapautuminen Neuvostoliitossa (tätä voi varmaan pitää yhtä lailla sääntelystä vapautumisena tai yhteiskuntakehityksenä, mutta "vapautuja" ei ole koko yhteiskunta) 
ruotsiksi voisi olla avreglering (vapautuminen säännöstelystä..) mutta tämä on jo sanastossa ja fi. deregulaatio

    lääkkeen vapautuminen elimistöön, kasvihuonekaasun vapautuminen järvestä, typen vapautuminen maaperästä. 
onko mahdollista käyttää tarkempia/osuvampia fysikaalisia termejä? mahdollisesti "frigöring (av ämne)" tms.

**Comment by mirmaid** [comment]
Tämän kanssa askarrellaan varmaan vuosikausia, mutta jos yksi selkeä tarve on vankeudesta vapautuminen, onko parempi että siihen sisältyy vain selkeästi vankilasta vapautuminen, vai myös esim. vapautuminen panttivankina olosta tai jonkin henkilön tai ryhmän vankinaan pitämän ihmisen vapaaksi pääsy?

Sanastossa on myös _vapautuneet vangit_.

**Comment by ilona-x** [comment]
Voisi myös ottaa mahdollisesti tuon FinMeSHistäkin löytyvän **lääkkeen vapautuminen**? http://www.yso.fi/onto/mesh/D065546

**Comment by mirmaid** [comment]
Uskaltaisikohan ensimmäiseen kohtaan ottaa _vapautuminen (psykologia)_? Ei käy ihan kaikkeen kyllä. Ehkä sitä voisi tutkailla ainakin.

**Comment by ilona-x** [comment]
Ehdotuksessa:

> "Sanastossa on kuitenkin runsaasti korvaavia ja osin myös täsmällisempiä käsitteitä, joilla vapautus ja vapautuminen voitaisiin monin paikoin korvata.
> Esim.
>     emansipaatio, vapaus, itsenäistyminen (psykologia) sopivat tiettyihin käyttöyhteyksiin.
>     Myös vapautuksen teologia
>     sääntelystä vapautuminen --> deregulaatio
>     vankilasta vapautuminen --> vapautuneet vangit (ei kuitenkaan sovi silloin kun vapaudutaan muusta vankeudesta kuin vankilasta?)
>     orjuudesta vapautuminen --> vapautuneet orjat
> 
> Jos siivotaan ensin nämä pois, ja katsotaan olisiko yhtenäiset kielivastineet löydettävissä jäljelle jääneelle setille."

Tuota Melindan siivousta ei ole varmaankaan vielä tehty, tai ainakaan siitä ei ole mainintaa tässä issuessa?

**Comment by mirmaid** [comment]
^ Ei, pitäisi ensin päättää halutaanko näin tehdä. Toisaalta jos korjaus ratkaisee vain osan jostain setistä (esim. _vapautuneet vangit_ ei sovikaan kaikkeen aineistoon jossa aihetta käsitellään vaan halutaan nimenomaan kuvailla vapautumisen prosessiin liittyviä asioita), tulee tilanteesta entistä sekavampi jos sitten kuitenkin päädytään lisäksi ottamaan "vankeudesta vapautuminen" sen jälkeen kun osa viitteistä on korjattu.

**Comment by mirmaid** [comment]
Vangit: suureen osaan viitteistä sopii _vapautuneet vangit_, mutta jonkin verran löytyy varsinkin artikkeliaineistoa, jossa aiheena on vapautumiseen valmistautuminen (esim. _Kohti puolimatkankotia : Oulun vankilassa aloittaa ensi viikolla toimintansa uusi vapauttamisyksikkö : sen kodinomaisissa huoneissa vangit totuttelevat lähestyvään vapauteen vähitellen_).

Eli ratkaistaan nyt otetaanko erikseen _vankilasta vapautuminen_ (seuraa päällekkäisyyttä), vai korjataanko mahdollisuuksien mukaan _vapautuneet vangit_ (jonkin verran viitteitä, joihin ei sovellu, vaan käytettävä esim. vangit & muita soveltuvia termejä, mahdollisesti _vapaus_).

**Comment by mirmaid** [comment]
Otetaan _lääkkeen vapautuminen_. 

Jatketaan tämän ja ylläolevan korjauksen jälkeen muita käyttötapauksia.

**Comment by mariaforsen** [comment]
Sv. läkemedelsfrisättning
Pitäisikö myös ohjata "vapautuminen (emansipaatio)" KÄYTÄ emansipaatio
Olisiko vapauttaminen selkeämpi terminä kuin vapautus? Ei tosin ratkaise kaikkia käännösongelmia..

**Comment by mirmaid** [comment]
^ Tuossa vankien tapauksessa vai laajemmin kaikkeen?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi: vapautuminen (emansipaatio) KÄYTÄ emansipaatio
Otetaan sanastoon lääkkeen vapautuminen.
Poistetaan vapautuminen sanastosta, kun korjattavat kuvailut on korjattu.

Korjataan Menlinda-kuvailuihin vankila-kontekstissa vapautuminen käsitteellä vapautuneet vangit (tai vapaus), kun soveltuu.
Korjataan orja-kontekstissa vapautuminen käsitteellä vapautuneilla orjat (tai vapaus), kun soveltuu.
Monissa tapauksissa vapautumisen korvaajaksi kelvannee vapaus.

**Comment by mariaforsen** [comment]
Eli vapautuminen poistuu ja vapautus sekä yllä mainitut uudet termit jäävät? 

Melindassa vapautus on käytetty myös esim. aukiolojen vapautuksesta, ja sellaiseen ei kyllä tuo ruotsinnos befrielse sovi (befrielse liittyy yleensä ihmisiin tai muuhun elävään "toimijaan"), mutta muuten se on paljon vähemmän ongelmallinen kuin vapautuminen.

**Comment by jarmosaarikko** [comment]
aukioloaikojen vapautus KÄYTÄ deregulaatio
Melindan tilanne 29.10.
476 | vapautuminen (yso/fin) - [Asteri-termitietue]
120 | vapautus (yso/fin) - [Asteri-termitietue]

**Comment by AuHo22** [comment]
_estoista, täydellisyyden tavoittelusta, menneisyyden painolastista, pelosta, riippuvuudesta, demonista (elämäntaito, psykologia, uskonto)_-> riiippuvuuksien yhteyksissä on usein käytetty myös toipuminen, selviytyminen -termejä, miksei yhtä hyvin psykologisten mekanismien yhteydessä, tai sitten on paljon kaikkea muita termejä joita voi soveltaa, esim.
Vastuullinen ihmisyys : vapautuminen kriiseistä luovaan muutokseen / Kirsi Mäkinen.

**Comment by mirmaid** [comment]
Tehty sovitut korjaukset, miten jatketaan? Mihin kaikkeen sopii esim. emansipaatio tai deregulaatio?

**Comment by YSO-kokous** [comment]
**PÄÄTÖKSET**
Korjataan aineistosta soveltuvasti vapautuminen -> emansipaatio  sekä vapautuminen -> deregulaatio

Lisätään ohjaustermit:
vapautuminen eriarvoisuudesta KÄYTÄ emansipaatio
vapautuminen holhouksesta KÄYTÄ emansipaatio
vapautuminen sääntelystä KÄYTÄ deregulaatio
normien purkaminen KÄYTÄ deregulaatio

Lisätään emansipaatiolla määritelmä: https://tieteentermipankki.fi/wiki/Filosofia:emansipaatio
**Määritelmä** sivistyksellinen, sosiaalinen, poliittinen ja oikeudellinen vapautuminen tai vapauttaminen alaikäisyydestä, holhouksesta, sorrosta, orjuudesta ja epäitsenäisyyden tilasta
**Selite** Emansipaatio on lyhyesti vapautumista holhouksesta tai eriarvoisuudesta, ja sen tavoitteena on tasa-arvon saavuttaminen.

**Comment by mirmaid** [comment]
296/Melinda

**Comment by ilona-x** [comment]
> **PÄÄTÖKSET**
> Korjataan aineistosta soveltuvasti vapautuminen -> emansipaatio sekä vapautuminen -> deregulaatio

Nämä korjattu Melindaan. Jäljelle jäi 142 viitettä.

**Comment by ilona-x** [comment]
Melindassa:
n. 15/142 YSOlla kuvailtua kaunokirjallisuutta

n. 30/142 talouden, kaupan, markkinoiden, kilpailun vapautumista (mihin kaikkeen käy vapaakauppa, ja kävisikö vielä joihinkin deregulaatio?)
n. 9/142 seksuaalisuuden/seksuaalisen käyttäytymisen vapautumista (LCSH: Sexual freedom http://id.loc.gov/authorities/subjects/sh2006004255)
n. 5/142 riippuvuudesta vapautumista (näihin varmaan kävisi toipuminen/selviytyminen)
n. 7/142 pelosta vapautumista (lisäksi yksittäisiä viitteitä mm. häpeästä, kärsimyksestä, perfektionismista, vihasta, ajattelusta, syyllisyydentunteesta, tahdosta, harhoista, menneisyydestä, jännittämisestä vapautumista)
n. 5/142 demoneista vapautumista

**Comment by ilona-x** [comment]
riittäisikö näihin päästöt tmv.? Tämäntyyppisiä aineistoja on varmaan enemmänkin, mutta kaikkien kuvailussa ei ole käytetty termiä vapautuminen 🤔 

- The effect of viral size class enrichments on microbial communities in marine systems 
- Typen vapautuminen kasvinjätteestä ja maaperästä.
- Ravinteiden vapautuminen Laajalahden ja Seurasaarenselän sedimentistä
- Lake-atmosphere greenhouse gas exchange in relation to atmospheric forcing and lake biogeochemistry

**Comment by ilona-x** [comment]
sekalaisia, joihin ei oikein kävisi vapaus:

- Regulation of dopamine release in the forebrain by alpha2-adrenoceptors and NMDA glutamate receptors :
- Aromin vapautuminen amorfisesta hiilihydraattimatriista 
- Enhancement and characterization of films for barrier and release applications

**Comment by mirmaid** [comment]
_Hyväksyminen (psykologia)_ sopii varmaan myös joihinkin vapautumisoppaisiin, mutta esim. pelkoon ei ihan täysin käy mikään näistä olemassaolevista. Tietysti voi sitten jossain tapauksissa laittaa 653-kenttään vapautuminen.

**Comment by ilona-x** [comment]
riittäisikö noihin pelosta, häpeästä, ahdistuksesta ym. vapautumiseen esimerkiksi itsekasvatus, elämäntaito, asennemuutos?

**Comment by mirmaid** [comment]
^ Osaan käy tosiaan hyväksyminen tai toipuminen myös.

**Comment by mariaforsen** [comment]
Kyllä, vapautuminen "täyteasiasanana" ei mielestäni tuo lisäarvoa nyt Melindassa oleviin tietueisiin. Mitä tulee kaikenlaisten "aineiden vapautumiseen" niin termi pitäisi olla tarkempi, jotta saataisiin vastaavia termejä.

**Comment by YSO-kokous** [comment]
### Päätös
poistetaan käsite vapautuminen.  Korvataan kuvailussa muilla soveltuvilla termeillä.

**Comment by mariaforsen** [comment]
Lisätäänkö ohjaus termiin "vapautus"? Ks. https://www.kielitoimistonsanakirja.fi/#/vapautus?searchMode=all
