### ISSUE TITLE
kukat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6778]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kukat](http://www.yso.fi/onto/ysa/Y102781) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jompi kumpi näistä kukista on tupla:
kukat   http://finto.fi/ysa/fi/page/Y102781
kukat   http://finto.fi/ysa/fi/page/Y103079 

#### Perustelut ehdotukselle   

Ei tuplia? 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
YSAssa on nyt: kukat, kukat (kasvinosat) >> kukat (kasvit), kukat (kasvinosat) ?
