### ISSUE TITLE
lehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6779]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lehdet](http://www.yso.fi/onto/ysa/Y102265) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lehdet (kasvinosat)
KT lehdet 

#### Perustelut ehdotukselle   

Myös ohjausterminä käytetty "lehdet", mikä on kiellettyä:
lehdet → aikakauslehdet
lehdet → lehdistö
lehdet → sanomalehdet 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. blad (växtdelar)
