### ISSUE TITLE
malaijin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6781]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

malaijin kieli 

#### Ehdotettu termi ruotsiksi   

malajiska språket 

#### Ehdotettu termi englanniksi   

Malay language 

#### Ehdotettu yläkäsite YSOssa (LT)   

[indonesialaiset kielet](http://www.yso.fi/onto/yso/p1678) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Malaijin_kieli 
LCSH : <http://id.loc.gov/authorities/subjects/sh85080066> 
SAO : Malajiska språket 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Tarkoitusta täsmentävä selite   

Huom. Allärsissä nyt indonesiska språk KT malajiska 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suomi-englanti-malaiji kuvasanakirja 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [malaijin kieli](http://finto.fi/yse/fi/page/Y506781)

**Comment by mariaforsen** [comment]
Sv. malajiska ET malajsiska, malaysiska, malajiska språket
