### ISSUE TITLE
energian kerääminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6783]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

energy harvesting 

#### Ehdotettu termi suomeksi   

energian kerääminen 

#### Vaihtoehtoiset termit ja ilmaisut   

energiankeruu 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2010001757> 
Wikipedia : https://fi.wikipedia.org/wiki/Energian_ker%C3%A4%C3%A4minen 

#### Perustelut ehdotukselle   

tarve väitöskirjojen kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Energy harvesting from walking using piezoelectric cymbal and diaphragm type structures 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [energian kerääminen](http://finto.fi/yse/fi/page/Y506783)

**Comment by mariaforsen** [comment]
Sv. energiskörd ET energiskördande, energisamlande
