### ISSUE TITLE
uni (kulttuuriset ilmiöt)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6784]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uni (kulttuuriset ilmiöt) 

#### Perustelut ehdotukselle   

Toivoisin että "uni (biologiset ilmiöt)" rinnalle lisättäisiin myös uni (kulttuuriset ilmiöt), tai vaihtoehtoisesti esim. nukkumisjärjestelyt (kulttuuriset ilmiöt) tai jokin vastaava termi, joka ottaa huomioon että nukkuminen on paitsi biologinen, myös kulttuurinen ja  sosiaalinen ilmiö, jota säätelevät erilaiset historialliset ja kulttuuriset seikat.
Nukkumisen kulttuurisia aspekteja on tutkittu 2000-luvulla paljonkin mm. historiassa ja sosiologiassa, mutta tutkimuksen linkittäminen ontologiaan ei toimi täysin, kun listattuna löytyy uni/nukkuminen ainoastaan biologisena ilmiönä. 
Kiitos! 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. http://www.lauranissin.fi/roman-sleep/ 

**Termiehdotus Fintossa:** [uni (kulttuuriset ilmiöt)](http://finto.fi/yse/fi/page/Y506784)

**Comment by mirmaid** [comment]
YSAssa on nyt _uni_ KT nukkuminen ja _unet_. YSOssa näille on lisätty sulkutarkenteet _uni (biologiset ilmiöt)_ ja _unet (mentaaliset objektit)_. Mielestäni monikko ei tässä tarvitse tarkennetta, koska monikkomuodon merkitys on kyllä varsin yksiselitteinen. 

Yksi mahdollisuus on muuttaa yksikkömuodon tarkenne _uni (nukkuminen)_, mutta se ei ehkä sovellu niin hyvin jos unta käsitellään nimenomaan biologian kannalta (esim. unen vaiheet). Toinen vaihtoehto on ottaa erikseen _nukkuminen_ tai ehdotettu _nukkumisjärjestelyt_.

**Comment by mariaforsen** [comment]
Sv. sömn=uni -riippumatta tutkitaanko kulttuurisesta tai biologisesta näkökulmasta (samasta asiasta on käsitetasolla kuitenkin kyse). En kannata jakoa, eli uuden käsitteen "nukkuminen" ottamista. Monesti tutkitaan unta myös kokonaisuutena, joten tällainen jako aiheuttaisi varmasti ongelmia käyttäjille. 

Parempi vaihtoehto on minusta tarkenteen muuttamista niin että "uni" käy riippumatta millä tieteenallalla tutkitaan, eli esim. "uni (nukkuminen)" olisi hyvä.

**Comment by mirmaid** [comment]
Uni (lepotila)?

**Comment by YSA-kokous** [comment]
uni (lepotila)
