### ISSUE TITLE
kirjastot (tietotekniikka)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6788]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjastot (tietotekniikka) 

#### Ehdotettu termi englanniksi   

Library (computing) 

#### Ehdotettu termi ruotsiksi   

Programbibliotek 

#### Vaihtoehtoiset termit ja ilmaisut   

ohjelmointikirjastot 
koodikirjastot 
 

#### Vastaava käsite muussa sanastossa   

kirjasto (tietotekniikka) : https://fi.wikipedia.org/wiki/Kirjasto_(tietotekniikka) 

#### Tarkoitusta täsmentävä selite   

Ohjelmointiin liittyvä käsite. Ohjelmoinnissa apuna käytetään työkaluna kirjastoja, jotka ovat esim. luokkien, olioiden, tai ohjelmien kokoelmia. Esimerkiksi Java Class Library, Boost, 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Learning React Native : building native mobile apps with JavaScript 

#### Perustelut ehdotukselle   

Ohjelmointiin liittyvässä kirjallisuudessa saatetaan käsitellä erilaisia ohjelmistokirjastoja. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [kirjastot (tietotekniikka)](http://finto.fi/yse/fi/page/Y506788)

**Comment by mirmaid** [comment]
LCSH: Libraries (Computer program subroutines)

Entä _ohjelmistokirjastot_ päätermiksi?

**Comment by mariaforsen** [comment]
Myös "kirjastot"-termille pitää laittaa tarkenne jos ehdotetussa muodossa otetaan, eli ei varmaan kannata.

**Comment by YSA-kokous** [comment]
Ohjelmistokirjastot
