### ISSUE TITLE
sopupelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#679]
#### Ehdotettu termi suomeksi

sopupelit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[97 Liikunta. Urheilu](http://www.yso.fi/onto/ysa/ryhma_97)
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/ysa/ryhma_98)

**Luontipäivämäärä:** 14.09.2001

**Muokkauspäivämäärä:** 14.9.2001, 17.1.2002, 16.12.2008

**Voyager-id:** 115275

**Termiehdotus Fintossa:** [sopupelit](http://finto.fi/yse/fi/page/Y315275)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6741
