### ISSUE TITLE
tabletit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6790]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tabletit](http://www.yso.fi/onto/ysa/Y156859) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tabletit (valmisteet tms.) 

#### Perustelut ehdotukselle   

Sanastossa on myös tabletit (kattaus), joten tämä termi vaatii tarkenteen.

**Comment by mirmaid** [comment]
Valmisteet on ehkä liian laaja (?): _(teollisesti) valmistettu tuote_

**Comment by satuniininen** [comment]
entä tabletit (puristeet)?

**Comment by YSA-kokous** [comment]
tabletit (puristeet)

**Comment by mariaforsen** [comment]
Sv. tabletter (preparat)
