### ISSUE TITLE
alustatalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6793]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alustatalous 

#### Ehdotettu termi englanniksi   

platform economy 

#### Ehdotettu yläkäsite YSOssa (LT)   

[talous](http://www.yso.fi/onto/yso/p2555) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Alustatalous 

#### Perustelut ehdotukselle   

Kuvailutarve. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The next phase in the digital revolution, http://urn.fi/URN:NBN:fi-fe201803094213 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [alustatalous](http://finto.fi/yse/fi/page/Y506793)

**Comment by mariaforsen** [comment]
Sv. plattformsekonomi
