### ISSUE TITLE
mikroaggressiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6795]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikroaggressiot 

#### Ehdotettu termi englanniksi   

Microaggressions 

#### Vastaava käsite muussa sanastossa   

LCSH : Microaggressions 
Wikipedia : https://fi.wikipedia.org/wiki/Mikroaggressio 
Wikipedia : https://en.wikipedia.org/wiki/Microaggression 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Tarkoitusta täsmentävä selite   

Mikroaggressio on usein tahaton ja huomaamaton loukkaava kommentti tai teko, joka kohdistuu vähemmistöryhmään tai sen edustajaan ja joka vahvistaa tätä ryhmää kohti tunnettuja stereotypioita. (Wikipedia) 

#### Perustelut ehdotukselle   

Käsite tulee esille mm. syrjintää ja traumoja käsittelevässä tutkimuksessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Microaggressions and traumatic stress : theory, research, and clinical treatment / Kevin L. Nadal. 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [mikroaggressiot](http://finto.fi/yse/fi/page/Y506795)

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by mariaforsen** [comment]
Sv. mikroaggressioner
https://www.psykologiguiden.se/psykologilexikon/?Lookup=mikroaggression
https://sv.wikipedia.org/wiki/Mikroaggression

**Comment by mirmaid** [comment]
Tässä olisi voinut käyttää: https://aaltodoc.aalto.fi/handle/123456789/118002

The second paper shows how microaggressions, as a resulting practice of hetero- and homonormativity, affect the identity work of a gay employee and their organizational belonging. The paper discusses the difficulty of reacting to discursive violence and theorizes the emergence of microaggressions as symbolic materializations of iterative gendered norms and assumptions.

**Comment by ilona-x** [comment]
FinMeSH:
mikroaggressio KT mikroaggressiot
http://www.yso.fi/onto/mesh/D000088828

**Comment by mirmaid** [comment]
Nyt 4 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
