### ISSUE TITLE
asuinpainanteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6796]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

asuinpainanteet 

#### Ehdotettu termi englanniksi   

Housepits 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaisjäännökset](http://www.yso.fi/onto/yso/p5340) 
[asuinpaikat](http://www.yso.fi/onto/yso/p14303) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85102482.html> 
SAO : Grophus 
<http://www.avoinmuseo.fi/kivikaudenkyla/asuinpainanteet.shtml> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa. Melindassa asuinpainanteet haulla 30 viitettä (masa). LSSHn ja SAOn käsitteet eivät ole täysin vastaavia vaan viittaavat kuoppa-asumuksiin (myös masa-termi). Melindassa kuitenkin käytetty enemmän asuinpainanne kuin kuoppa-asumus käsitettä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2271526 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [asuinpainanteet](http://finto.fi/yse/fi/page/Y506796)

**Comment by YSA-kokous** [comment]
Kysytään Museovirastosta

**Comment by YSA-kokous** [comment]
asuinpainanteet

**Comment by mariaforsen** [comment]
Sv. husgropar
