### ISSUE TITLE
klassikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6797]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[klassikot](http://www.yso.fi/onto/ysa/Y114798) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaanko ryhmiksi ainakin 87 ja muita taiteiden ryhmiä? 
Pitäisikö rajata taiteisiin tai mahdollisesti jakaa?

#### Perustelut ehdotukselle   

Klassikko on monimerkityksinen termi, ks. Kielitoimiston sanakirja.

**Comment by mirmaid** [comment]
Käytetty ennen kaikkea kirjallisuudesta joten sen voisi lisätä, muuten hyvin laajasti esim. automerkit, suosikkiruokalajit.

**Comment by krinay** [comment]
YSAssa onkin ryhmä 87, YSOssa vain 00.

**Comment by YSA-kokous** [comment]
Ei muuta muutosta.
