### ISSUE TITLE
yhteiskuntakuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6798]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhteiskuntakuvaus](http://www.yso.fi/onto/ysa/Y104916) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö ryhmä 87? 

#### Perustelut ehdotukselle   

Melindassa käytetty paljon kirjallisuudessa. Muilla vastaavilla, kuten ajankuvaus, henkilökuvaus, luonnonkuvaus jne. -termeillä on ryhmänä 87. 

Ruotsinkielinen vastine on samhällsskildring, joka on ennen kaikkea kirjallisuuden käsite.

**Comment by mirmaid** [comment]
Käytetty erittäin paljon tietoaineistossa (kun kuvataan jonkin maan tai aikakauden yhteiskunnallisia oloja), toki jonkin verran (mutta paljon vähemmän) siitä, miten yhteiskuntaa kuvataan kaunokirjallisuudessa (vrt. miljöökuvaus, ajankuvaus). Onko ongelma, jos näissä käytetään samaa termiä?

**Comment by YSO-kokous** [comment]
Lisätään käsitteelle ryhmä 87. Rohkaistaan käyttämään kuvailussa vain silloin, kun aineisto käsittelee yhteiskuntakuvausta, ei yhteiskunnallisia oloja sinänsä.

Pohdittavaksi, pitäisikö ehdottaa SLM:ään käsitettä yhteiskuntakuvaukset.

**Comment by mariaforsen** [comment]
ALLFO: yhteiskuntakuvaus=samhällsskildring eli lähinnä kirjallisuus-merkityksessä

**Comment by AuHo22** [comment]
Monografia-aineiston UDK-luokituskaavio:
308 | Sosiografia. Yhteiskuntakuvaus

Myös supistettu UDK:
308 Sosiografia. Yhteiskuntakuvaus (sekä kvalitatiivinen että kvantitatiivinen)
sv. Sociografi. Beskrivande studier av samhället (både kvalitativt och kvantitativt)

Käytetty nimenomaan tietoaineiston kuvailun yhteydessä, kaunokirjallisuuden yhteydessä yleisempi ajankuvaus, sv. tidsskildring

**Comment by jtuohini** [comment]
_Yhteiskuntakuvaukset_ ei hyväksytty SLM-sanastoon: keinotekoinen termi, SLM:stä löytyy jo mm. [**yhteiskunnalliset romaanit**](url). Tietoaineistoa ei ole jaoteltu eikä haluta jaotella aiheenmukaisilla SLM-termeillä (kyse ei teoksen muodosta tai lajityypistä).

**Comment by jtuohini** [comment]
LCSH-siltaus YSO-asiasanalle kirjallisuudentutkimuksen osalta: [**Manners and customs in literature**](http://id.loc.gov/authorities/subjects/sh94006146) (taustalla _Ceremonies_, _Folkways_, _Social life and customs_, _Traditions_, _Usages_ yms. KÄ **Manners and customs**) ja erityisesti [**Social history in literature**](http://id.loc.gov/authorities/subjects/sh97006677) (taustalla _Descriptive sociology_ ja _Social conditions_ KÄ **Social history**). Lisäksi mainittujen ST-suhteiset, esim. [**Moral conditions in literature**](http://id.loc.gov/authorities/subjects/sh94006684) ja [**Social problems in literature**](http://id.loc.gov/authorities/subjects/sh85123990).

**Comment by AuHo22** [comment]
Valokuvauksen kuvateosten (tietoteokset) yhteydessä yleisesti käytetään samantyyppisesti kuvailevia termejä - luonnonvalokuvaus, dokumenttivalokuvaus, henkilövalokuvaus, mustavalkoinen valokuvaus - silloinkin, kun kuvataan itse tuotosta, eikä vain valokuvauksen aktia tai tekniikkaa tms.

Esim. Fennicassa nimekkeet:
Suomen luonnon lumo  = The enchanting nature of Finland = Zauberhafte Natur Finnlands ;
Suomalainen pastoraali ;
Occideia

**Comment by AuHo22** [comment]
Lapsikuvaukset otettiin SLM-sanastoon, myös nuorisokuvaukset olisi hyvä ottaa, eikä särje kielikorvaa, ja termille on vastaavankaltaista tarvetta. Samoin kansankuvaukset - muut eivät sitten tunnu kovinkaan luonnollisilta tai ovat muutoin kuvattavissa.

**Comment by mariaforsen** [comment]
-kuvaukset ongelmallisia monikielisyyden kannalta, ellei määritellä tarkemmin minkälainen kuvaus on kyseessä (ruotsiksi eri termit eri merkityksille)
https://www.kielitoimistonsanakirja.fi/#/lapsikuvaus?searchMode=all
https://www.kielitoimistonsanakirja.fi/#/kuvaus?searchMode=all
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_5444870fb8deab1cc7bdd8eaaa7f1d0c&list_id=1&keyword=kuvaus&word=kuvaus

**Comment by mirmaid** [comment]
Yhteiskuntakuvaukset (romaanit) KÄ yhteiskunnalliset romaanit

**Comment by mirmaid** [comment]
Vastaavia muita yso-käsitteitä (luonnonkuvaus, henkilökuvaus) ei ole käytetty genremäisesti tämän tapaan (siis esim. aineistoissa joissa käsitellään jonkin alueen luontoa tai jotain henkilöä). YSOn osalta aiemmassa keskustelussa sovittiin, että ei rohkaistaisi enää tämänkään termin genrekäyttöön, vaan pohditaan otetaanko merkitykseltään vastaava termi genresanastoon. Termiä käytetään jatkuvasti genretyyppisesti edelleen.

**Comment by mariaforsen** [comment]
Henkilökuvaus ja luonnonkuvaus ovat myös sv. -skildring ALLFOssa.

**Comment by mariaforsen** [comment]
Onko tässä nyt siis kyse siitä että otetaanko nuorisokuvaukset ja kansankuvaukset uusina SLM-termeinä, vai mistä? Sv. siinä tapauksessa ungdomsskildringar ja folkskildringar (aivan ok termejä).

SAOssa on muuten kyllä genreterminä samhällsskildringar, mutta siinä taas ei ole samhällsromaner-termiä (periaatteessa suppeampi termi) https://id.kb.se/term/saogf/Samh%C3%A4llsskildringar
"Genre/formterm för skönlitteratur.
Verk som skildrar de sociala och politiska förhållandea i ett land eller i en region."

**Comment by mirmaid** [comment]
Ei lisätä genretermiä, rajataan tarkenteella YSOssa (esim. yhteiskuntakuvaus (taiteet)) tai jokin muu ratkaisu.

**Comment by mariaforsen** [comment]
Sv. samhällsskildring viittaa lähinnä kirjallisuuteen: "litterär skildring av förhållandena i ett samhälle"
https://id.kb.se/term/saogf/Samh%C3%A4llsskildringar

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
Päätermiksi: yhteiskuntakuvaus (taiteet)
Ohjaustermeiksi: yhteiskuntakuvaus (elokuva), yhteiskuntakuvaus (kirjallisuus). 
Mahdollisesti muita taidemuotoja sulkutarkenteiksi.

YSO-ylläpito miettii, onko käyttöhuomautus tarpeen. Esim. "Käytetään aineistoissa, joissa käsitellään yhteiskuntakuvausta kirjallisuudessa tai muussa taiteessa."

Taustaa: Aiempi päätös oli: "Rohkaistaan käyttämään kuvailussa vain silloin, kun aineisto käsittelee yhteiskuntakuvausta, ei yhteiskunnallisia oloja sinänsä". Ajatus tässä oli, että kuvailukäyttö rajautuisi tapauksiin, joissa tutkitaan teosten yhteiskuntakuvausta, mutta ei käytettäisi fiktioaineistosta tai tietokirjallisuudesta, joka on genremäisesti yhteiskunnan kuvausta ("A cultural guide to the United States", "Contemporary France" jne).

Nyt tehdyllä päätöksellä on tarkoitus selventää käyttäjille käsitteen käyttöä. (taiteet)-sulkutarkenteen myötä kuvailukäyttö toivottavasti korjaantuu.
