### ISSUE TITLE
eksistenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6800]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[eksistenssi](http://www.yso.fi/onto/ysa/Y103753) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Oleminen-muotoa käytetty 40 kertaa Melindassa, tarvitaanko erikseen? 

#### Perustelut ehdotukselle   

On myös YSOssa 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSA-kokous** [comment]
Poistetaan oleminen.

**Comment by mariaforsen** [comment]
Eikö tämä asia ole nyt loppuunkäsitelty ja suljettavissa?
