### ISSUE TITLE
poppelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6802]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

poppelit 

#### Ehdotettu termi englanniksi   

Poplar 

#### Vaihtoehtoiset termit ja ilmaisut   

Populus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pajukasvit](http://www.yso.fi/onto/yso/p12549) 

#### Alakäsitteet (RT)   

[haapa](http://www.yso.fi/onto/yso/p18892) 
[hybridihaapa](http://www.yso.fi/onto/yso/p21477) 

#### Vastaava käsite muussa sanastossa   

LCSH : Poplar 
laji.fi : https://laji.fi/taxon/MX.38589 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

Tarvitaan kasvisuvun nimenä 

#### Perustelut ehdotukselle   

Tarvitaan kasvisuvun nimenä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto / Päivi Lipsanen **Termiehdotus Fintossa:** [poppelit](http://finto.fi/yse/fi/page/Y506802)

**Comment by mariaforsen** [comment]
Sv. popplar
