### ISSUE TITLE
uskonnolliset laulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6805]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uskonnolliset laulut 

#### Ehdotettu termi ruotsiksi   

religiösa sånger 

#### Ehdotettu termi englanniksi   

religious songs 

#### Ehdotettu yläkäsite YSOssa (LT)   

[laulut](http://www.yso.fi/onto/yso/p2371) 
[uskonnollinen musiikki](http://www.yso.fi/onto/yso/p28101) 

#### Alakäsitteet (RT)   

[hengelliset laulut](http://www.yso.fi/onto/yso/p8501) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Sovittu Muusa-ryhmän kokouksessa 22.11.2018 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [uskonnolliset laulut](http://finto.fi/yse/fi/page/Y506805)

**Comment by mariaforsen** [comment]
Sv. religiösa sånger ET religiösa visor

**Comment by mirmaid** [comment]
Ehdotettu myös SLM-sanastoon, https://www.kiwi.fi/display/muusa/Valmiit
