### ISSUE TITLE
pedal steel -kitara

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6806]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pedal steel -kitara 

#### Ehdotettu termi englanniksi   

pedal steel guitar 

#### Ehdotettu termi ruotsiksi   

pedal steel guitar 

#### Ehdotettu yläkäsite YSOssa (LT)   

[steel-kitara](http://www.yso.fi/onto/yso/p30117) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q587027 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2037952 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [pedal steel -kitara](http://finto.fi/yse/fi/page/Y506806)

**Comment by mariaforsen** [comment]
Sv. pedal steel guitar ET pedal steel-gitarr
