### ISSUE TITLE
steampunk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6807]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

steampunk 

#### Ehdotettu termi ruotsiksi   

steampunk 

#### Ehdotettu termi englanniksi   

steampunk 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tieteiskirjallisuus](http://www.yso.fi/onto/yso/p15527) 

#### Assosiatiiviset (RT)   

[kyberpunk](http://www.yso.fi/onto/yso/p15528) 

#### Perustelut ehdotukselle   

Tieteiskirjallisuudenalalaji, lötyy Kaunokista jo. YSAsta löytyy kuitenkin jo kyberpunk, joten steampunk-termin lisääminen olisi myös ihan loogista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The illustrated world of Mortal engines ; isbn 978-1-4071-8678-8 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [steampunk](http://finto.fi/yse/fi/page/Y506807)

**Comment by jtuohini** [comment]
Ainakin tuon mainitun aineiston kuvailun kannalta termiä kaivattaisiin YSAakin enemmän SLM-sanastoon? Jos siis jatkossa on tarkoitus kuvailla sillä kyberpunk-kirjallisuutta itseään eikä kyberpunk-kirjallisuutta käsittelevää aineistoa?

**Comment by mariaforsen** [comment]
Sv. steampunk ET ångpunk

**Comment by mirmaid** [comment]
On jo SLM-sanastossa.
