### ISSUE TITLE
crwth

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6808]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

crwth 

#### Ehdotettu termi ruotsiksi   

crwth 

#### Ehdotettu termi englanniksi   

crwth 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lyyrasoittimet](http://www.yso.fi/onto/yso/p13911) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85034328> 
Wikidata : https://www.wikidata.org/wiki/Q766461 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.463486 

#### Perustelut ehdotukselle   

Kyseinen soitin on jo SEKOssa, mutta sitä käsittelevän kirjallisuuden kuvailuun tarvittava vastaava termi puuttuu YSAsta 

#### Tarkoitusta täsmentävä selite   

"Crwth (chorus, crot, crowd) [- -] a plucked and, from about the 11th century, a bowed lyre." [https://doi.org/10.1093/gmo/9781561592630.article.52977] 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [crwth](http://finto.fi/yse/fi/page/Y506808)

**Comment by mariaforsen** [comment]
Sv. crwth
