### ISSUE TITLE
maanpeite

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6809]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maanpeite 

#### Ehdotettu termi englanniksi   

land cover 

#### Assosiatiiviset (RT)   

[maankäyttö](http://www.yso.fi/onto/yso/p6713) 

#### Vastaava käsite muussa sanastossa   

PTO : <http://paikkatiedot.fi/def/1001001/p212> 
LCSH : <http://id.loc.gov/authorities/subjects/sh2010009654> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda x 4 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Application of satellite image time series and texture information in land cover characterization and burned area detection 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [maanpeite](http://finto.fi/yse/fi/page/Y506809)

**Comment by mariaforsen** [comment]
Sv. marktäcke?

**Comment by YSA-kokous** [comment]
Seuraava kokous, tarvitsee sulkutarkenteen.

**Comment by jarmosaarikko** [comment]
maanpeite | land cover | landtäcke --- HUOM! ILMAN SULKUTARKENTEITA
http://inspire.ec.europa.eu/theme/lc -- INSPIREn määritelmät
Maanpeite
Määritelmä: Maapallon pinnan fysikaalinen ja biologinen peite, mukaan luettuina keinotekoiset peitteet, maatalousalueet, metsät, (osaksi) luonnontilassa olevat alueet, kosteikot ja vesistöt. (edited)
Landtäcke
Definition: Fysiskt och biologiskt landtäcke på jordytan, inbegripet artificiella ytor, jordbruksmark, skogar, (delvis) naturliga områden, våtmarker, vattenförekomster. 
Land cover
Definition: Physical and biological cover of the earth's surface including artificial surfaces, agricultural areas, forests, (semi-)natural areas, wetlands, water bodies.

**Comment by satuniininen** [comment]
maanpeite (alueet)
maanpeite (maan käyttö)
maanpeite (alueiden käyttö)
maanpeite (paikkatieto)
maanpeite (ekosysteemitilinpito)

**Comment by YSA-kokous** [comment]
maanpeite

**Comment by mariaforsen** [comment]
Sv. landtäcke ET marktäcke
