### ISSUE TITLE
lähdejulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6810]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lähdejulkaisut (SLM)

#### Ehdotettu termi ruotsiksi   

källpublikationer 

#### Ehdotettu termi englanniksi   

collections of documents, records, etc. TAI JOTAIN PAREMPAA 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85061227> 

#### Perustelut ehdotukselle   

Tarvitaan SLM-sanastoon, jotta voidaan kuvailla varsinaisia lähdejulkaisuja, siis julkaisuja, joihin on koottu pääasiassa kirjallisia lähteitä näköispainoksina tai vielä useammin puhtaaksikirjoitettuina ja mahdollisin kommentaarein varustettuna. – Ks. myös esim. https://www.kansalliskirjasto.fi/fi/kokoelmat/lahdejulkaisut 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3172146 

#### Tarkoitusta täsmentävä selite   

Julkaisu, johon on koottu historiallisia lähteitä tietyin perustein (ajan, kielen, paikan, aiheen yms. mukaan valikoituna), esim. Finlands medeltidsurkunder. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [lähdejulkaisut](http://finto.fi/yse/fi/page/Y506810)

**Comment by jtuohini** [comment]
Ja YSAn puolella pitäisi harkita, onko _lähdejulkaisut_ KÄ **lähdeaineisto** oikea viittaussuhde ensinkään, edellinen kun kattaa julkaisut, jälkimmäiset aineiston yleisesti, niin kirjalliset kuin kirjoittamattomat.

**Comment by mirmaid** [comment]
SLM:ään hyväksytty _lähdejulkaisut_ (RT aineskokoelmat)

**Comment by LeKorsu** [comment]
Minä taas olen miettinyt tarvetta käsitteelle lähteet (henkilöt), sisäpiirilähteet tms, joita media-alalla käytetään ja tarvitaan, mutten ole saanut aikaiseksi tehtyä siitä termiehdotusta.

**Comment by mirmaid** [comment]
SLM: määritelmä

**Comment by YSA-kokous** [comment]
Ei muutosta YSAssa
