### ISSUE TITLE
vajaakuntoiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6811]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vajaakuntoiset](http://www.yso.fi/onto/ysa/Y99973) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastossa on myös työrajoitteiset, vammaiset, osatyökykyiset jne. Onko kaikki oltava erillisinä käsitteinä? 

#### Perustelut ehdotukselle   

Varsinkin termi "vajaakuntoinen" on monelta taholta ja moneen kertaan jo pidemmän aikaa kritisoitu leimaavuuden jne. takia. Ruotsiksi on miltei mahdotonta keksiä vastineita kaikille näille, suunnilleen samaa asiaa tarkoittaville, termeille. 

Ks. esim. TEPA
https://www.julkari.fi/bitstream/handle/10024/134946/Tukea%20ty%C3%B6h%C3%B6n%20paluuseen%20ja%20ty%C3%B6ss%C3%A4%20jatkamiseen.pdf?sequence=1
https://kuntoutusportti.fi/vammaisuus-toimintakyky-ja-identiteetti/
https://www.kotus.fi/nyt/kotus-blogi/teravasti_kotus-blogin_lukijoiden_keskustelunavauksia/tyokyvyton_tyorajoitteinen_vajaatyokykyinen.10644.blog

**Comment by mirmaid** [comment]
Myös _työrajoitteiset_-termi on saanut kritiikkiä. _Vajaakuntoiset_ on varmaankin perusteltua poistaa, mutta se ei ole tietueissa korvattavissa yhdellä termillä. Voiko odottaa syksyyn?

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by ilona-x** [comment]
https://iate.europa.eu/entry/result/820356/all

**Comment by mirmaid** [comment]
^ 2. vajaakuntoinen henkilö: "vajaakuntoisella [tarkoitetaan] työnhakijana ollutta työntekijää, jonka mahdollisuudet saada sopivaa työtä, säilyttää työ tai edetä työssä ovat huomattavasti vähentyneet asianmukaisesti todetun vamman, sairauden tai vajavuuden takia;"

**Comment by mariaforsen** [comment]
Eikö se sitten ole työrajoitteinen? Ruotsiksi tosiaan vaikeaa löytää vastineita kaikille näille melkein samaa tarkoittaville sanoille.

**Comment by mirmaid** [comment]
Sosiaaliturvan sanasto suosittelee _vajaakuntoinen_-termiä _työrajoitteisen_ sijasta.

**Comment by mariaforsen** [comment]
Sosiaaliturvan sanasto näyttää kuitenkin olevan vuodelta 1996, onko tilanne mahdollisesti muuttunut?

Pääasia kuitenkin että nämä saadaan jotenkin yhdistettyä... Ks. esim. https://yhteisomedia.fi/vammaisuus-toimintakyky-ja-identiteetti/ "Viimeisin yritys vajaakuntoinen-sanan hävittämiseksi on Suomen vammaispoliittisen ohjelman (2010-2015) ehdotus nro 79: Luovutaan vammaisten osalta vajaakuntoinen termin käytöstä. Termi on leimaava, eikä kuvaa nykyaikaista käsitystä vammaisten henkilöiden työkykyisyydestä." ja https://valtioneuvosto.fi/documents/2308875/2395511/VAMPOloppuraportti 

Riittäisikö YSOssa olevat "osatyökykyiset" ja "vaikeasti työllistettävät", ainoat täysin hyväksytyt ei-leimaavat termit näistä, ja tarvitaanko edes YSOssa sen tarkempia? 

Melindassa käytetty paljon nimenomaan vammaisista, joten ei voida myöskään sanoa että termi on ok kunhan ei käytetä vammaisista (se ei olisi muutenkaan kovin korrekti ratkaisu..)

**Comment by mirmaid** [comment]
Myöskään vaikeasti työllistettävät -termiä ei pidetä enää neutraalina: [Sotete-sanasto](http://www.tsk.fi/tepa/fi/haku/vaikeasti%20ty%C3%B6llistett%C3%A4v%C3%A4%20henkil%C3%B6)

Lakitekstissä **vaikeasti työllistyvä** määritellään kuitenkin vain työttymyyden keston kautta: _työmarkkinatukeen oikeutettua työtöntä työnhakijaa, joka on saanut työmarkkinatukea työttömyytensä perusteella vähintään 500 päivältä tai jonka oikeus työttömyyspäivärahaan on päättynyt työttömyysturvalain 6 luvun 7 tai 9 §:ssä tarkoitetun enimmäisajan johdosta_; https://www.finlex.fi/fi/laki/alkup/2005/20051216

**Comment by mirmaid** [comment]
_Osatyökykyiset_ on terminä ongelmaton, mutta ei varmaan suoraan vaihdettavissa esim. _vajaakuntoiset_-termin tilalle viitteissä. ([Sotete-sanasto](http://www.tsk.fi/tepa/fi/haku/osaty%C3%B6kykyinen%20henkil%C3%B6))

**Comment by mirmaid** [comment]
Ehdotuksia
- vaikeasti työllistettävät > vaikeasti työllistyvät (Sotete-sanaston "heikossa työmarkkina-asemassa olevat henkilöt" ei ehkä ihan ihanteellinen YSOon)
- vajaakuntoiset KÄ osatyökykyiset, viitteissä korvattava joko tällä termillä, tai vaikeasti työllistyvät tai vain työkyky, työllistyminen? (esim. vammaisten osalta)
- työrajoitteiset samoin?

**Comment by YSO-kokous** [comment]
Hyväksyttiin Mirjan edellä esittämät ehdotukset:
- vaikeasti työllistettävät > vaikeasti työllistyvät (Sotete-sanaston "heikossa työmarkkina-asemassa olevat henkilöt" ei ehkä ihan ihanteellinen YSOon)
- vajaakuntoiset KÄ osatyökykyiset, viitteissä korvattava joko tällä termillä, tai vaikeasti työllistyvät tai vain työkyky, työllistyminen? (esim. vammaisten osalta)
- työrajoitteiset samoin
