### ISSUE TITLE
tahdonilmaisu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6812]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tahdonilmaisu](http://www.yso.fi/onto/ysa/Y203918) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään sulkutarkenne. Esim. "tahdonilmaisu (oikeus)". Lisätään tarvittaessa käyttöhuomautus, jossa tarkennetaan käsitteen käyttöalaa. 

#### Perustelut ehdotukselle   

Käsite otettu oikeudellisessa merkityksessä sanastoon. Wiki: "Sellaista tahdonilmaisua, jolla perustetaan, muutetaan, siirretään tai kumotaan oikeuksia ja velvollisuuksia, nimitetään oikeustoimeksi." Varomattomat voisivat käyttää tätä kuitenkin yleiskielisessä merkityksessä, esim. uhmaikäisen tahdonilmaisun yhteydessä. 

#### Ehdottajan organisaatio   

Kansallikirjasto

**Comment by ilona-x** [comment]
Melindassa 45 viitettä, väärinkäyttötapauksia ei havaittu :smile:

**Comment by YSA-kokous** [comment]
Ei muutosta.
