### ISSUE TITLE
bambarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6813]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bambarat 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Bambara 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9780241293522 9789173432207 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [bambarat](http://finto.fi/yse/fi/page/Y506813)

**Comment by mariaforsen** [comment]
Sv. bambara (folk)
