### ISSUE TITLE
bambaran kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6814]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bambaran kieli 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Bambara 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9780241293522  9789173432207 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [bambaran kieli](http://finto.fi/yse/fi/page/Y506814)

**Comment by mariaforsen** [comment]
Sv. bambara (språk)
