### ISSUE TITLE
modernit nomadit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6816]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

modernit nomadit 

#### Ehdotettu termi ruotsiksi   

moderna nomader 

#### Ehdotettu termi englanniksi   

modern nomads 

#### Vaihtoehtoiset termit ja ilmaisut   

liikkuva elämäntapa 
moderni nomadismi 
travellerit 

#### Vastaava käsite muussa sanastossa   

nomads : <http://id.loc.gov/authorities/subjects/sh85092204.html> 

#### Perustelut ehdotukselle   

Modernit nomadit/liikkuva elämäntapa olisi kattotermi kuvaamaan ihmisiä, jotka matkustavat. He joko tekevät töitä koko ajan (esim. matkabloggaus), pysähtyvät hetkeksi töihin jonnekin kerätäkseen rahaa tai ovat heikosti toimeen tulevia, jotka liikkuvat löytääkseen työmahdollisuuksia eri puolilta. Jotkut vain matkustavat. YSAn termi paimentolaisuus kuvaa vain asian perinteistä muotoa. Liikkuva työ/kausityö/epätyypillinen työ puolestaan eivät riitä kuvaamaan tätä käsitettä, jossa modernilla vaeltelulla on ratkaiseva rooli, ja työ on vain sivuseikka. Haluaisin, että termi olisi tällainen laajempi, joka käsittäisi työn ja ei-työn.

LCSH nomads on yläkäsite, jonka alapuolella on herders. Sanastoa voisi ehkä kehittää myös siihen suuntaan? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Degrowth in Tourism, Global nomads and extreme mobilities, Tourism ethics... 

**Ehdottajan organisaatio:** Åbo Akademi **Termiehdotus Fintossa:** [modernit nomadit](http://finto.fi/yse/fi/page/Y506816)

**Comment by mirmaid** [comment]
Melindassa 2 kertaa _travellerit_.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by satuniininen** [comment]
_Diginomadit_ tuntuu olevan käytetyin ja vakiintunein muoto, mutta se ei toki ihan tavoita ehdottajan hakemaa merkitystä. LC:ssä _nomads_ kattaa tämänkin merkityksen, mutta meille mieluummin oma käsitteensä.

**Comment by YSA-kokous** [comment]
diginomadit

**Comment by mariaforsen** [comment]
Sv. digitala nomader ET diginomader
