### ISSUE TITLE
megatrendit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6820]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

megatrendit 

#### Ehdotettu termi ruotsiksi   

megatrender 

#### Ehdotettu termi englanniksi   

megatrends 

#### Assosiatiiviset (RT)   

[trendit](http://www.yso.fi/onto/yso/p10137) 

#### Perustelut ehdotukselle   

esim. https://www.sitra.fi/tulevaisuussanasto/megatrendi/
Tulevaisuudentutkimuksen ja yleisten yhteiskuntatieteiden alueilla hyvinkin tarpeellinen, joissa näitä ilmiöitä  tutkitaan. 

#### Tarkoitusta täsmentävä selite   

Megatrendi on yleinen kehitysuunta tai laaja muutosten kaari, joka tapahtuu maailmanlaajuisesti.[1] Megatrendi on makrotason ilmiö, jolla odotetaan olevan suuria ja pitkäaikaisia vaikutuksia yhteiskunnassa.[2] Kaupungistuminen ja digitalisaatio ovat tällä hetkellä eräitä megatrendejä. (Wikipedia) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mitä tapahtuu huomenna tulevaisuudelle? / Jukka Manninen kertoo viidestä vallitsevasta megatrendistä 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [megatrendit](http://finto.fi/yse/fi/page/Y506820)

**Comment by satuniininen** [comment]
Tälle olisi kyllä käyttöä.

**Comment by mirmaid** [comment]
15 viitettä Melindassa.
