### ISSUE TITLE
hybridivaikuttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6821]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hybridivaikuttaminen 

#### Ehdotettu termi ruotsiksi   

hybridpåverkan 

#### Ehdotettu termi englanniksi   

hybrid operations 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.fiia.fi/julkaisu/hybridivaikuttaminen-ja-demokratian-resilienssi 

#### Perustelut ehdotukselle   

poliittisesti motivoitunut suunnitelmallinen toiminta, jolla pyritään saavuttamaan omat tavoitteet erilaisia, toisiaan täydentäviä keinoja käyttäen ja kohteen heikkouksia hyödyntäen
http://www.tsk.fi/tepa/fi/haku/hybridivaikuttaminen 

**Termiehdotus Fintossa:** [hybridivaikuttaminen](http://finto.fi/yse/fi/page/Y506821)

**Comment by ilona-x** [comment]
"Hybridivaikuttaminen merkitsee keinovalikoimaa, jolla pyritään monella eri suunnalla horjuttamaan toista osapuolta. Informaatiosodankäynti, kyberhyökkäykset ja tunnustuksettomat sotilaalliset operaatiot ovat tällaisia keinoja. Hybridin voi määritellä sodan ja rauhan väliin jääväksi harmaaksi alueeksi. Pyrkimyksenä on ohittaa toisen osapuolen itsemääräämisoikeus, useimmiten kuitenkin ilman suoraa voimankäyttöä."
Lähde: https://www.helsinki.fi/fi/uutiset/talous-yhteiskunta/hybridivaikuttaminen-on-harmaa-alue-sodan-ja-rauhan-valissa-miten-silta-voi-suojautua

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by satuniininen** [comment]
Sanastossa on jo  _informaatiosodankäynti, hybridisota, verkkohyökkäykset_ ja _kybersodankäynti._ Eikö tässä ole päällekkäisyyden vaara?

**Comment by EsaMPKK** [comment]
On tosiaan.

**Comment by EsaMPKK** [comment]
Tuossa kuvailtavassa julkaisussa:
 Esimerkkejä liukumasta hybridisodasta kohti hybridivaikuttamista: Hybridisota: sijaisjoukoin sekä -taistelijoin suoritetut rajoitetut alueelliset sotilaalliset kampanjat, joiden tavoite on usein identiteettipoliittinen/taktinen, ei välttämättä perinteinen alueen hallintaan pyrkivä operaatio; separatististen liikkeiden tukeminen ja kansalaisten väkivaltaisuuksien lietsominen esimerkiksi etnisiä jännitteitä tai identiteettipolitiikkaa hyödyntämällä; kyberhyökkäykset sekä aggressiivinen tiedustelu. Hybridivaikuttaminen: riippuvuussuhteiden rakentaminen kriittisen infrastruktuurin monimuotoisuutta hallitsemalla/vähentämällä/kontrolloimalla; vaikuttaminen demokratian keskeisiin instituutioihin, kuten esimerkiksi vaaleihin ja hallintoon em. keinoin; taloudelliset vaikutuskeinot, voivat olla pehmeitä tai kovia, sijoitusrahalla houkuttelusta organisoidun rikollisuuden kautta valtiolähtöiseen sanktiopolitiikkaan; disinformaatiokampanjat ja pyrkimys hallita mediatilaa; ulkopoliittinen vaikuttaminen ja muut pehmeän vallan keinot, ml. liittolaispolitiikan koheesion heikentäminen.

**Comment by YSA-kokous** [comment]
Tutkitaan kokonaisuus syksyllä 2019

**Comment by mariaforsen** [comment]
Hybridpåverkan vain Suomessa?

**Comment by AuHo22** [comment]
Myös käytettyjä termejä: hybridihäirintä ja hybridiuhat. 
Ks. myös aiempi informaatiovaikuttaminen-keskustelu #4396

**Comment by mariaforsen** [comment]
https://intermin.fi/eu2019fi/ohjelma/hybridiuhat 
http://www.tsk.fi/tepa/sv/s%C3%B6k/hybridiuhka
http://www.rikstermbanken.se/rtb/visaTermpost.html?id=261905

Näistä (hybridiuhka=)hybridhot on se mitä käytetään myös Ruotsissa.

**Comment by tpalonen** [comment]
Google fight:

hybridivaikuttaminen 7890
hybridiuhat 5050
hybridiuhka 2020
hybridihäirintä 241

Vrt.
hybridisota 8180
hybridisodat 1710
hybridisodankäynti 2920

**Comment by mirmaid** [comment]
Marian viimeinen linkki on aika kuvaava - termejä käytetään kyllä paljon, mutta hybridi-sanan merkitys jää epämääräiseksi ja ainakin itsestäni tuntuu, että kyse ei kovin selkeästi ole mistään täysin uudenlaisesta vaikuttamisen muodosta (onhan aikaisemminkin historiassa käytetty monenlaisia painostamisen ja propagandan keinoja samanaikaisesti, eikä vain suoraa sodankäyntiä).

**Comment by ilona-x** [comment]
fi        hybridivaikuttaminen
sv       hybridpåverkan
en      hybrid operations pl

määritelmä
poliittisesti motivoitunut suunnitelmallinen toiminta, jolla pyritään saavuttamaan omat tavoitteet erilaisia, toisiaan täydentäviä keinoja käyttäen ja kohteen heikkouksia hyödyntäen
huomautus
Hybridivaikuttamisen keinot voivat olla esimerkiksi taloudellisia, poliittisia tai sotilaallisia. Keinoja voidaan käyttää samanaikaisesti tai siten, että ne seuraavat toisiaan.
Hybridivaikuttamista tehdään esimerkiksi informaatio-, kyber-, fyysisten ja taloudellisten operaatioiden avulla.
Hybridivaikuttamisen takana voi olla joko valtiollinen tai ei-valtiollinen toimija.
Vrt. informaatiovaikuttaminen.
Käsitekaavio: Informaatioon ja tietojärjestelmiin kohdistuvat uhkat.
Lähde:	  	
Kyberturvallisuuden sanasto (TSK 52, 2018)
	  

fi        hybridivaikuttaminen
sv       hybridpåverkan
en      hybrid influencing
määritelmä
toiminta, jolla pyritään erilaisia, toisiaan täydentäviä keinoja käyttäen ja kohteen heikkouksia hyödyntäen saavuttamaan omat tavoitteet
huomautus
Hybridivaikuttamisen keinot voivat olla esimerkiksi taloudellisia, poliittisia tai sotilaallisia. Hybridivaikuttamisessa voidaan käyttää myös teknologiaa ja sosiaalista mediaa. Keinoja voidaan käyttää samanaikaisesti tai siten, että ne seuraavat toisiaan.
Hybridivaikuttamista voi olla vaikea tunnistaa.
Vrt. informaatiovaikuttaminen.
Lähde: 	
Kokonaisturvallisuuden sanasto (TSK 50, 2017)

**Comment by ilona-x** [comment]
fi        informaatiovaikuttaminen
sv       informationspåverkan
en      information operations pl (1); influencing through information
määritelmä
toiminta, jossa informaatiota tuottamalla, muokkaamalla tai sen saatavuutta rajoittamalla muutetaan kohteen käsityksiä tai toimintaa informaatio- ja mielipideympäristön kautta
huomautus
Informaatiovaikuttamista on monentasoista ja sitä voidaan tehdä esimerkiksi informaatio-operaatioiden avulla.
Vrt. hybridivaikuttaminen.
Englanninkielisten termien käyttö ei ole vakiintunut. Anglosaksisessa maailmassa myös informaatiovaikuttamisesta käytetään laajasti termejä "information warfare" ja "information war", mutta Suomessa pyritään yleensä tekemään ero sodankäynnin ja vaikuttamisen välillä.
Käsitekaavio: Informaatioon ja tietojärjestelmiin kohdistuvat uhkat.

Lähde  Kyberturvallisuuden sanasto (TSK 52, 2018)

**Comment by YSO-kokous** [comment]
Tutkitaan edelleen. Kuinka moni tämän aihealueen käsite tarvittaisiin sanastoon, ts. mitkä merkitykset olisivat sanaston osalta tarpeellisia eriteltäväksi toisistaan? Mitkä olisivat näiden käsitteiden käytettävät termit?

**Comment by AuHo22** [comment]
https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/161512/VNK_11_2019_Informaatiovaikuttamisen%20vastaaminen_web.pdf
fi. informaatiovaikuttaminen
sv. informationspåverkan
eng. information influence activities

**Comment by ilona-x** [comment]
JUHOon näyttää kesän aikana ilmestyneen:
**hybridivaikuttaminen**  http://www.yso.fi/onto/juho/p14088
**hybridiuhat** http://www.yso.fi/onto/juho/p14109
**informaatiovaikuttaminen** http://www.yso.fi/onto/juho/p14111

**Comment by mirmaid** [comment]
Melindassa kerran hybridivaikuttaminen, hybridiuhat 0 (hybridisota 95).

**Comment by tpalonen** [comment]
LCSH:sta löytyy ainakin nämä viisi:

- _Hybrid warfare_: https://id.loc.gov/authorities/subjects/sh2016001601.html
- _Information warfare_: https://id.loc.gov/authorities/subjects/sh95005481.html
- _Network-centric operations (Military science)_ jonka ohjastermejä ovat _Net-centric operations (Military science), Net-centric warfare, Netcentric warfare, Network-based defense, Network-centric warfare, Network-enabled capability (Military science)_: https://id.loc.gov/authorities/subjects/sh2009009407.html
- _Information warfare (International law)_: https://id.loc.gov/authorities/subjects/sh2002002082.html
- _Cyberterrorism_, jonka ohjaustermejä ovat _Attacks on computers, Computer attacks, Cyber attacks, Cyber terrorism, Cyber war, Cyberwarfare, Electronic terrorism (Cyberterrorism)_: https://id.loc.gov/authorities/subjects/sh00001974.html

Elikkäs: LCSH ainakin niputtaa cyberhyökkäykset ja cybersodankäynnin yhteen. YSOssa verkkohyökkäykset (ohjaustermi: cyberhyökkäykset) ja cybersodankäynti on erikseen. Periaatteessa YSOn molemmat käsitteet voisi linkata tähän LCSH-käsitteeseen. Nyt on linkattu vain verkkohyökkäykset.

**Comment by mirmaid** [comment]
^ _Kybersodankäynti_ 128 kertaa Melindassa. Ehdotatko yhdistämistä vai vain molempien linkitystä samaan vastineeseen?

**Comment by FinMeSHienPaimentaja** [comment]
Hybridi-sanan taustaa (ja miten kreikkaa äidinkielenään osaava ymmärtää hybridi-sanan - mikä ei tarkoita sitä, etteikö puheena olevat termit voi olla merkityksiltään paljonkin kreik. käsitteistä eroavia):


positiivinen molemminpuolinen:

αμφιθέατρο amphitheater
αμφίβιο amphibium


negatiivinen molemminpuolinen:

kirous ύβρις hybris (vanha kreikka substantiivi) βρίσιμο (nykykreikka)

https://en.wikipedia.org/wiki/Hybristophilia
https://www.theoi.com/Daimon/Hybris.html

υβρίδιο hybridium
υβριδικό hybrid (adjektiivi) 
hybridiauto (polttoaine+sähköauto), hybridisota (armeja+kybersota)

-> "hybridivaikuttaminen" olisi merkitykseltään monitahoista (monesta suunnasta), pahantahtoista vaikuttamista

**Comment by FinMeSHienPaimentaja** [comment]
Hieman kyber/cyper- sanojen taustaa:



κυβένηση cybernesis government



κυβερνοχώρος cyberspace

https://www.techopedia.com/definition/2493/cyberspace



cybernetics 

https://en.wikipedia.org/wiki/Cybernetics

_The word cybernetics comes from Greek κυβερνητική (kybernētikḗ), meaning "governance", i.e., all that are pertinent to κυβερνάω (kybernáō), the latter meaning "to steer, navigate or govern", hence κυβέρνησις (kybérnēsis), meaning "government", is the government while κυβερνήτης (kybernḗtēs) is the governor or "helmsperson" of the "ship"._



"cyperhyökkäykset", "kyberhyökkäykset", "cypersodankäynti", "kybersodankäynti":
tietokonesota, tietokonehyökkäykset, verkkohyökkäykset, virtuaalisota

<-> hallitaan / pyritään (tietokone)verkkojen ja/tai tietokoneiden hallintaan hyökkäys- ja/tai sotakontekstissa.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: **hybridisota**: aseellisen sodankäynnin ja eril. aseettomien vaikutuskeinojen yhdistelmästä. _Propaganda ja verkkohyökkäykset hybridisodan välineinä._

**Comment by mirmaid** [comment]
> LCSH ainakin niputtaa cyberhyökkäykset ja cybersodankäynnin yhteen. YSOssa verkkohyökkäykset (ohjaustermi: cyberhyökkäykset) ja cybersodankäynti on erikseen. Periaatteessa YSOn molemmat käsitteet voisi linkata tähän LCSH-käsitteeseen. Nyt on linkattu vain verkkohyökkäykset.

Linkataanko molemmat samaan? _Verkkohyökkäykset_-käsitettä ei varmasti haluta poistaa, mutta säilytetäänkö _kybersodankäynti_ edelleen YSOssa? Käytetty 128 kertaa. Ei SOTOssa.

**Comment by mirmaid** [comment]
_Hybridivaikuttaminen_ kerran Melindassa. Omasta puolestani riittää tässä vaiheessa _hybridisota_ ja _vaikuttaminen_.

**Comment by mariaforsen** [comment]
Kyberturvallisuuden sanasto (TSK): hybridivaikuttaminen
sv hybridpåverkan
en hybrid operations pl
määritelmä: poliittisesti motivoitunut suunnitelmallinen toiminta, jolla pyritään saavuttamaan omat tavoitteet erilaisia, toisiaan täydentäviä keinoja käyttäen ja kohteen heikkouksia hyödyntäen
huomautus: Hybridivaikuttamisen keinot voivat olla esimerkiksi taloudellisia, poliittisia tai sotilaallisia. Keinoja
voidaan käyttää samanaikaisesti tai siten, että ne seuraavat toisiaan.
Hybridivaikuttamista tehdään esimerkiksi informaatio-, kyber-, fyysisten ja taloudellisten operaatioiden avulla.
Hybridivaikuttamisen takana voi olla joko valtiollinen tai ei-valtiollinen toimija.
Vrt. informaatiovaikuttaminen.

**Comment by YSO-kokous** [comment]
### Päätökset äänestyksen jälkeen
Otetaan sanastoon hybridivaikuttaminen
Määritelmät: https://termipankki.fi/tepa/fi/haku/hybridivaikuttaminen

**Comment by mirmaid** [comment]
Heti tämän päätöksen jälkeen törmäsin uutisointiin, jossa termiä _hybridisota_ käytetään ristiin _hybridivaikuttamisen_ kanssa: _Euroopan unioni on syyttänyt Valko-Venäjää tuhansien Lähi-idästä ja Afrikasta kotoisin olevien siirtolaisten ohjaamisesta EU:n alueelle. EU:n mukaan kyseessä on hybridisodan muoto, jonka tarkoituksena on kostaa länsimaille, koska ne ovat asettaneet pakotteita Valko-Venäjälle ihmisoikeusrikkomusten takia._ https://yle.fi/uutiset/3-12178523

_Itäinen siirtolaisreitti on Knausin mukaan harvinaisen vaikea, koska EU:lla on vastassa diktaattorin ottein Valko-Venäjää hallitseva johtaja, joka ei kaihda oman kansan kiduttamista tai siirtolaisten lähettämistä hengenvaaraan osana hybridivaikuttamista._ https://yle.fi/uutiset/3-12180931

_Hybridisota_-termiä on käytetty laajemminkin Valko-Venäjän toiminnasta EU:ta kohtaan.

**Comment by AuHo22** [comment]
Mielestäni määritelmät kuitenkin pitävät hybridisotaa sekä tavanomaisten että epätavanomaisten keinojen yhdistelmänä:

Esim. https://fi.wikipedia.org/wiki/Hybridisodank%C3%A4ynti
 Hybridisodankäynnin konseptissa sulautuu yhteen suora ja epäsuora sotataidollinen lähtökohta. Vastaavalla voidaan myös todeta, että hybridisodankäynti sulauttaa tavanomaisen ja epätavanomaisen sodankäynnin menetelmän, jne.
Tai:
https://puolustusvoimat.fi/documents/1951253/2815786/PVTUTKL_TUTKIMUSKATSAUS_2015_1.pdf/a3742642-42ff-4644-ab8f-6eba7cd56a6e

Mediassa on yhtä lailla viime aikoina käytetty termejä hybridivaikuttaminen tai hybridihyökkäys, ja samalla tavalla voi miettiä eroa kybersodankäynnin ja kyberhyökkäyksen KÄYTÄ verkkohyökkäykset (YSO jälkimmäisen kohdalla) välillä. Kyseessä lienee ns. aste-erot. Mielestäni molemmat termit tarvitaan. Valkovenäläiset aseistetut joukot ovat olleet kuljettamassa siirtolaisia rajalle, mutta onko siinä kuitenkaan vielä kyse tavanomaisista sodankäynnin keinoista, jota varsinainen hybridisota edellyttäisi? Pitäisin tällä hetkellä molemmat termit sanastossa ennen kuin vakiintumista suuntaan tai toiseen on selkeästi nähtävissä. Poliittisessa retoriikassa on perinteisesti käytetty kovenevia sanakäänteitä.
