### ISSUE TITLE
kuvakivet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6825]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuvakivet 

#### Ehdotettu termi ruotsiksi   

bildstenar 

#### Vaihtoehtoiset termit ja ilmaisut   

kirjokivet 

#### Vastaava käsite muussa sanastossa   

LCSH ("broader match" -tyyppisenä) : <http://id.loc.gov/authorities/subjects/sh85127907> 
Wikidata : https://www.wikidata.org/wiki/Q602202 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3156692 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 
[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kuvakivet](http://finto.fi/yse/fi/page/Y506825)

**Comment by satuniininen** [comment]
Engl. picture stones, broadMatch _Stele (Archaeology)_ OK
