### ISSUE TITLE
laatukuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6826]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[laatukuvat](http://www.yso.fi/onto/ysa/Y102948) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "genremaalaukset" 

#### Perustelut ehdotukselle   

Synonyymiset käsitteet on aina hyvä saada KT-muodoiksi. Ehdotetun KT-muodon lähde: https://fi.wikipedia.org/wiki/Laatukuva (ja muita) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSA-kokous** [comment]
Lisäksi genrekuvamaalaukset

**Comment by mariaforsen** [comment]
Sv. genremålningar
