### ISSUE TITLE
absurdi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6827]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[absurdi](http://www.yso.fi/onto/ysa/Y113129) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mikä on tämän suhde käsitteeseen absurdismi? Tarvitaanko molempia vai voisiko käsitteet yhdistää? 

#### Perustelut ehdotukselle   

Käsitteet ovat päällekkäisiä ja niitä on vaikea erottaa toisistaan. 

#### Ehdottajan organisaatio   

KK / YSO

**Comment by jtuohini** [comment]
Ja KT-muodoksi lisäksi _absurdius_.

**Comment by AuHo22** [comment]
absurdi KT absurdismi, absurdius
Absurdi on myös kaunokirjallisuuden kuvailussa tarvittava käsite.

**Comment by jtuohini** [comment]
Ja KT:ksi myös ruotsin kieleen palautuva _absurditeetti_ [https://www.sprakochfolkminnen.se/sprak/minoritetssprak/suomi-finska/kielivinkki/kielivinkki/2013-10-11-absurditeetti-vai-absurdius-.html].
 
Niin, ja tässäkin varmaan mieluummin substantiivi kuin adjektiivi varsinaiseksi asiasanaksi!

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi nimenomaan "absurdism" pääterminä (EI det absurda). 

https://fi.wikipedia.org/wiki/Absurdismi
https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:absurdismi

**Comment by mirmaid** [comment]
LCSH Absurd (Philosophy) http://id.loc.gov/authorities/subjects/sh85000261

**Comment by mirmaid** [comment]
Melindassa _absurdi_ 332 kertaa, _absurdismi_ 207 kertaa, vain 19 kertaa samassa viitteessä. Suuri osa näistä on kaunokki/kauno -termejä.

**Comment by mirmaid** [comment]
Voiko käsitettä _absurdismi_ käyttää aineistoista, joiden käsittelemä ilmiö sijoittuu aikaan ennen absurdismin syntyä tyylisuuntana/filosofiana? Esim. _Die Erfahrung mit dem Nichts und dem Unsinn : poetologische, fast schon postmoderne Experimente im Mittelalter_ tai _Politics and anti-realism in Athenian old comedy : the art of the impossible_. Entä esim. _Absurdin suurvalta : elämää neuvostojärjestelmässä_?

**Comment by AuHo22** [comment]
Tarkkoja jos ollaan, niin absurdilla voidaan kuvata ihan mitä tahansa ilmiötä samalla tavalla kuin kuvataan groteskin tai satiirin käsitteiden avulla aikakaudesta riippumatta ja tällöin sillä tarkoitetaan tyylikeinoa / ilmaisun keinoa - absurdismi puolestaan viittaa kokonaiseen tyylisuuntaukseen, ks. esim. https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:absurdismi
Tähän liittynee laaja terminologinen käyttö kaunokirjallisuuden yhteydessä.

**Comment by YSO-kokous** [comment]
Ei tarvetta muutoksille. Molemmilla käsitteillä oma merkityksensä ja absurdi on vakiintunut käyttöön, vaikka onkin adjektiivi.
