### ISSUE TITLE
arvostelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6828]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[arvostelmat](http://www.yso.fi/onto/ysa/Y169065) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteen merkitystä on täsmennettävä. 

#### Perustelut ehdotukselle   

Sanalla on kaksi merkitystä: 1) Arvostelu. 2) Logiikassa väite, joka voi olla tosi tai epätosi. 
https://github.com/NatLibFi/Finto-data/issues/853 

#### Ehdottajan organisaatio   

KK/YSO

**Comment by mirmaid** [comment]
Ruotsiksi _propositioner (logik)_.

**Comment by mirmaid** [comment]
Filosofian sanakirja?

**Comment by mariaforsen** [comment]
Ja sanastossa on arvostelut erikseen, joten sitä ei toivottavasti huomioida tässä. 

Onko muuten koko termi tarpeen? Ks. Melinda

Entä tämä: http://tieteentermipankki.fi/wiki/Estetiikka:esteettinen_arvostelma

Entä väitteet/väittämät olisiko se ok käyttää merkityksessä "väite, joka voi olla tosi tai epätosi."?
Ks. TEPA 

SAO: proposition (filosofi) LCSH-linkitys proposition (logic)

**Comment by AuHo22** [comment]
arvostelmat (filosofia)?

**Comment by YSA-kokous** [comment]
propositiot (logiikka) KT arvostelmat (logiikka)
