### ISSUE TITLE
koulumatkatuet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6829]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koulumatkatuet 

#### Ehdotettu termi ruotsiksi   

stöd för skolresor 

#### Ehdotettu termi englanniksi   

school transport subsidies 

#### Ehdotettu yläkäsite YSOssa (LT)   

[opintotuki](http://www.yso.fi/onto/yso/p5435) 

#### Vastaava käsite muussa sanastossa   

koulumatkatuet :  
JUPO :  

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Sosiaaliturvaan liittyvä sanasto on YSA:ssa puutteellinen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi Kelan opintoetuustilastossa http://urn.fi/URN:NBN:fi-fe2018102938993 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [koulumatkatuet](http://finto.fi/yse/fi/page/Y506829)

**Comment by mirmaid** [comment]
Ei Melindassa

**Comment by ilona-x** [comment]
Melinda: koulumatkat + tukimuodot x 7

https://www.kela.fi/koulumatkatuki

**Comment by mariaforsen** [comment]
Sv. skolresestöd https://www.kela.fi/web/sv/skolresestod?inheritRedirect=true ET stöd för skolresor

**Comment by YSA-kokous** [comment]
koulumatkatuki
