### ISSUE TITLE
aikuiskoulutustuet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6830]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aikuiskoulutustuet 

#### Ehdotettu termi ruotsiksi   

vuxenutbildningsstöd 

#### Ehdotettu termi englanniksi   

adult education allowances 

#### Ehdotettu yläkäsite YSOssa (LT)   

[opintotuki](http://www.yso.fi/onto/yso/p5435) 

#### Vastaava käsite muussa sanastossa   

JUPO : aikuiskoulutustuet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Sosiaaliturvaan ja etuuksiin liittyvää sanastoa pitäisi täydentää YSA:ssa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi Kelan opintoetuustilastossa http://urn.fi/URN:NBN:fi-fe2018102938993 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [aikuiskoulutustuet](http://finto.fi/yse/fi/page/Y506830)

**Comment by mirmaid** [comment]
Ei Melindassa

**Comment by YSA-kokous** [comment]
Tutkitaan vielä kokonaisuus

**Comment by ilona-x** [comment]
JUPOSSA; opintoetuudet-termin alakäsitteinä aikuiskoulutustuet & aikuisopintorahat 
http://www.yso.fi/onto/jupo/p2583

**Comment by ilona-x** [comment]
fi        aikuiskoulutustuki

palkattomalle opintovapaalle jäävälle, omaehtoiseen ammattitaidon kehittämistä ja ylläpitoa koskevaan koulutukseen osallistuvalle aikuisopiskelijalle myönnettävä opintoetuus

Lähde: Sosiaalialan tiedonhallinnan sanasto, versio 5.0 (THL, 2019)
http://www.tsk.fi/tepa/fi/haku/aikuiskoulutustuki

"Aikuisopintorahaa ei enää ole. Mainittu aikuiskoulutustuki korvasi sen."
Lähde: https://kysykelasta.kela.fi/viewtopic.php?t=1378

**Comment by YSA-kokous** [comment]
aikuiskoulutustuki
