### ISSUE TITLE
opintotuki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6831]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[opintotuki](http://www.yso.fi/onto/ysa/Y97825) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

opintoetuudet 

#### Perustelut ehdotukselle   

opintotuki on muuttunut viime vuosina monipuolisemmaksi etuuspaketiksi, jota opintoetuudet sanana kuvaa paremmin 

#### Ehdottajan organisaatio   

Kela

**Comment by mirmaid** [comment]
Pitäisikö tämän olla mieluummin yläkäsite, kun sanastossa on kuitenkin _opintoapurahat, opintolainat_ ja _opintosetelit_?

**Comment by ilona-x** [comment]
JUPO: opintoetuudet http://www.yso.fi/onto/jupo/p2583 alakäsitteenä mm. opintotuki http://www.yso.fi/onto/jupo/p267

**Comment by ilona-x** [comment]
http://www.tsk.fi/tepa/fi/haku/opintoetuus

**Comment by mariaforsen** [comment]
Sv. studieförmåner /Finsk-svensk utbildningsordlista

**Comment by YSO-kokous** [comment]
Otetaan sanastoon opintoetuudet. Säilytetään opintotuki. Opintotuki ja vastaavat käsitteet opintoetuudet-käsitteen alakäsitteeksi.
