### ISSUE TITLE
tunnustuskirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6833]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tunnustuskirjat](http://www.yso.fi/onto/ysa/Y99648) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi mukaan SLM-sanastoon 

#### Perustelut ehdotukselle   

Keskeinen uskonnollisen kirjallisuuden muoto/lajityyppi, meikäläisittäin tunnetuimpana Augsburgin tunnustus. Ja kyseessä siis ihan asia kuin "tunnustuskirjallisuus", joka on KT-muotona termille "muistelmat". 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
tunnustuskirjat + sulkutarkenne, kysytään ehdottajalta

**Comment by jtuohini** [comment]
Tarvetta on edelleen, ks. esim. https://melinda.kansalliskirjasto.fi/byid/018690236.

**Comment by mariaforsen** [comment]
Sv. bekännelseskrifter, YSOssa eng. Books of Concord?

**Comment by mirmaid** [comment]
Hyväksytty muodossa tunnustuskirjat (teologinen kirjallisuus).
