### ISSUE TITLE
oppimisanalytiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6839]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oppimisanalytiikka 

#### Ehdotettu termi englanniksi   

learning analytics 

#### Ehdotettu termi ruotsiksi   

läräandeanalytik 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Tarkoitusta täsmentävä selite   

Vuonna 2011 järjestetyssä ensimmäisessä oppimisanalytiikkaa käsittelevässä konferenssi (International Conference on Learning Analytics (LAK 2011) se määriteltiin näin: ”Oppimisanalytiikalla tarkoitetaan oppijoista ja heidän toimintaympäristöstä kerättävää tietoa, mittaamista, analysointia ja 
raportointia, jonka pohjalta yritetään ymmärtää ja optimoida oppimista ja oppimisympäristöjä.” (Lähde: Vainio, Leena. Oppimisanalytiikan Askeleet Kouluissa. [Hämeenlinna]: Suomen eOppimiskeskus ry, 2018. ) 

#### Perustelut ehdotukselle   

Uusi, kehittyvä tapa kehittää opetusta erityisesti verkkoympäristössä. Käsitteelle on vaikea löytää vastinetta vanhastaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://poluttamo.files.wordpress.com/2018/11/oppimisanalytiikan-askeleet-kouluissa-2018.pdf; https://poluttamo.fi/2017/08/02/oppimisanalytiikka-tulee-oletko-valmis/ 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [oppimisanalytiikka](http://finto.fi/yse/fi/page/Y506839)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Learning_analytics

**Comment by leen989** [comment]
Kannatan sanan lisäämistä. Käytetty usein OKM:n julkaisuissa ja hankkeissa.

**Comment by mirmaid** [comment]
Nyt 4 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. lärandeanalytik HT inlärningsanalytik, lärandeanalys, inlärningsanalys
https://termipankki.fi/tepa/fi/haku/oppimisanalytiikka
https://www.abo.fi/centret-for-livslangt-larande/pedagogik-och-lararfortbildning/larandeanalytik/
https://oahanke.fi/sv/
https://www.finna.fi/Record/aoe.2935
https://okm.fi/julkaisu?pubid=URN:ISBN:978-952-263-735-2

**Comment by YSO-kokous** [comment]
#### Päätös
Jää edelleen termiehdotukseksi

**Comment by ilona-x** [comment]
Tälle olisi ollut käyttöä väitöskirjan "[Higher education students’ perspectives on learning analytics use as support for academic paths](https://urn.fi/URN:ISBN:9789526238920)" kuvailussa.

--

Tepa:
https://termipankki.fi/tepa/fi/haku/oppimisanalytiikka

--

Oppimisanalytiikan tutkimusinstituutti (Turku Research Institute for Learning Analytics)  https://www.oppimisanalytiikka.fi/

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
