### ISSUE TITLE
essentialismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6840]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

essentialismi 

#### Ehdotettu termi englanniksi   

Essentialism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[filosofia](http://www.yso.fi/onto/yso/p1056) 

#### Vastaava käsite muussa sanastossa   

LCSH : Essentialism (Philosophy) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

Tätä on jo käytetty Melindassa joko YSAn asiasanana tai vapaana hakusanana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/N6J9HFD8XP35YKLJ6I6CA3AQ39IRDHNHS8XTHGXLD1KR4SP619-05578?func=full-set-set&set_number=037364&set_entry=000001&format=999 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [essentialismi](http://finto.fi/yse/fi/page/Y506840)

**Comment by ilona-x** [comment]
SAO: Essentialism (filosofi) Används ej Essens (filosofi)
LCSH: Essentialism (Philosophy) Earlier Established Forms: Essence (Philosophy)

YSAssa essentia KÄYTÄ olemus (en. essence (philosophy) & sv. väsen (filosofi))
http://www.yso.fi/onto/ysa/Y103754

"I svensk filosofi används företrädesvis "väsen", då det i många andra språk talas om essens." https://sv.wikipedia.org/wiki/Essens

https://tieteentermipankki.fi/wiki/Filosofia:essentialismi
https://tieteentermipankki.fi/wiki/Filosofia:olemus

**Comment by YSA-kokous** [comment]
olemus KÄ essentialismi?

**Comment by mariaforsen** [comment]
Sv. essentialism
