### ISSUE TITLE
mikroagressio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6841]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikroagressio 

#### Ehdotettu termi englanniksi   

microaggression 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aggressiot](http://www.yso.fi/onto/yso/p3483) 

#### Vastaava käsite muussa sanastossa   

LCSH : Microaggressions 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Tarkoitusta täsmentävä selite   

"Mikroaggressio on usein tahaton ja huomaamaton loukkaava kommentti tai teko, joka kohdistuu vähemmistöryhmään tai sen edustajaan ja joka vahvistaa tätä ryhmää kohti tunnettuja stereotypioita"

https://fi.wikipedia.org/wiki/Mikroaggressio 

#### Perustelut ehdotukselle   

Tarvittu sisällönkuvailussa.
Käytetty vapaana hakusanana Melindassa jo. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Microaggression theory : |b influence and implications

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6795

**Comment by satuniininen** [comment]
Melindassa kerran monikossa, ei kertaakaan yksikössä. Ei Meshissä.

Edellisen kerran käsitelty 12/2018. Tilanne ei ainakaan Melindassa ole sen jälkeen muuttunut mihinkään suuntaan.

**Comment by mariaforsen** [comment]
Sv. mikroaggressioner https://www.psykologiguiden.se/psykologilexikon/?Lookup=mikroaggression
