### ISSUE TITLE
katse

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6846]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[katse](http://www.yso.fi/onto/ysa/Y189662) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi katsominen. 

#### Perustelut ehdotukselle   

Käsite on ehkä otettu alunperin sanastoon spesifisemmässä merkityksessä (eng. gaze; miehen/naisen katse), mutta Melinda-käyttö paljastaa, että sitä on käytetty yleisesti ja yleiskielisesti muissakin katsomiseen liittyvissä yhteyksissä. Ohjaustermi vastaisi tätä käyttöä paremmin.

Vrt.
"Katson - mitä näen?: katsomisen tavan muuttuminen omaelämäkerrallisen valokuvatyöskentelyn aikana"
"Eyes on the road : eye movements and the visual control of locomotion in curve driving"
"The effect of eye contact on arousal and attention : a psychophysiological perspective" 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSA-kokous** [comment]
Tutkitaan, mahdollisesti jaettava.

**Comment by mirmaid** [comment]
LCSH: Gaze (BT Visual perception); Gaze in art; Gaze in literature. Lisäksi _Eye contact_, joka sopisi useisiin Melindankin viitteisiin.

**Comment by mariaforsen** [comment]
Ruotsiksi blick ja se on ihan ok sellaisenaan.

**Comment by YSA-kokous** [comment]
Lisätään ohjaustermi:
katsominen KÄYTÄ katse
Pohditaan englannin osalta, otetaanko lisää ohjaustermejä, looking, watching, viewing tms.

Pohdittavaksi: otetaanko katsekontakti omana käsitteenään.

**Comment by tpalonen** [comment]
En laittanut ohjaustermiksi looking, watching tai viewing, koska kaikki nämä ovat niin kovin monimerkityksisiä eivätkä muutenkaan viittaa tarkasti siihen, mihin käsitettä aineistossa on käytetty. Eye contact ja eye movement sopisivat aineiston valossa hyvin ohjaustermeiksi, mutta en nyt laittanut niitäkään, kun tilanne lienee se, että siihen merkitykseen on mahdollisesti tulossa uusi käsite.

**Comment by tpalonen** [comment]
Lisäsin englannin ohjaustermeiksi: glance, watching (gaze), looking (gaze), eye direction ja direction of the eyes.

Eye contact ja eye movement  voisivat sopia aineiston valossa ohjaustermeiksi, mutta en laittanut niitä, kun tilanne lienee se, että siihen merkitykseen on mahdollisesti tulossa uusi käsite.
