### ISSUE TITLE
ilmastostrategiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6855]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmastostrategiat 

#### Ehdotettu termi ruotsiksi   

klimatstrategier 

#### Ehdotettu termi englanniksi   

climate strategies 

#### Vaihtoehtoiset termit ja ilmaisut   

ilmastostrategia 

#### Ehdotettu yläkäsite YSOssa (LT)   

[strategiat](http://www.yso.fi/onto/yso/p4632) 

#### Assosiatiiviset (RT)   

[ilmastonsuojelu](http://www.yso.fi/onto/yso/p22405) 

#### Tarkoitusta täsmentävä selite   

Mm. yrityksillä, kaupungeilla ym. on nykyään omat ilmastostrategiansa. 

#### Perustelut ehdotukselle   

Yhdistelmän ilmasto + strategiat sijaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ilmastonmuutos ja kansalaisosallistuminen, http://urn.fi/URN:ISBN:978-951-563-705-5 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[14 Klimatologia. Meteorologia. Ilmatiede](http://www.yso.fi/onto/yso/p26587) 
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ilmastostrategiat](http://finto.fi/yse/fi/page/Y506855)

**Comment by ilona-x** [comment]
Toimiva linkki esimerkkijulkaisuun: https://www.sitra.fi/julkaisut/ilmastonmuutos-ja-kansalaisosallistuminen/

Melinda: ilmastostrategia x 6 & ilmastostrategiat x 1
