### ISSUE TITLE
tombeaut [SLM + YSA]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6856]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tombeaut [SLM + YSA] 

#### Ehdotettu termi englanniksi   

tombeaux 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soitinmusiikki](http://www.yso.fi/onto/yso/p1514) 
[sävellykset](http://www.yso.fi/onto/yso/p1515) 

#### Assosiatiiviset (RT)   

[surumusiikki](http://www.yso.fi/onto/yso/p16784) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q15991004 

#### Tarkoitusta täsmentävä selite   

"An instrumental piece or group of pieces, in the character of a lament, commemorating the death of some person, usually real but occasionally imaginary." [https://doi.org/10.1093/gmo/9781561592630.article.28084] 

#### Perustelut ehdotukselle   

Kyseiselle sävellystyypille ei ennestään ole täsmällistä termiä. Tarvitaan erityisesti SLM-sanastoon. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tombeau pour Mr. de Sainte Colombe / Marin Marais 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [tombeaut [SLM + YSA]](http://finto.fi/yse/fi/page/Y506856)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ottamista sekä SLM:ään että YSAan/YSOon.

**Comment by jtuohini** [comment]
Ja määritelmän suomennos (Grovessa olevan mukaan): "Luonteeltaan vaikeroiva tai valittava soitinsävellys, joka on tehty todellisen tai poikkeustapauksessa fiktiivisen henkilön kuoleman johdosta"

**Comment by mirmaid** [comment]
Hyväksytty/SLM

**Comment by mariaforsen** [comment]
Sv. tombeauer
