### ISSUE TITLE
Uusikirkko Vpl.

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6861]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Uusikirkko Vpl.](http://www.yso.fi/onto/ysa/Y94464) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan ruotsinkielisestä vastineesta ("Nykyrko -- Viborgs län") lääniin viittaava osio. 

#### Perustelut ehdotukselle   

Asiasana ei ole vaarassa sekoittua Uusikirkko Tl:ään, joka on ruotsiksi "Nykyrka", ei "Nykyrko". Toinen vaihtoehto olisi muuttaa lääni tarkenteeksi: "Nykyrko (Viborgs län)". 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
On olemassa muitakin "Nykyrka", joten lääniin viittaavaa osiota ei kannata poistaa. Ks. myös https://sv.wikipedia.org/wiki/Nykyrka
