### ISSUE TITLE
Wadeye (N.T.)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6862]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Wadeye (N.T.) 

#### Ehdotettu termi ruotsiksi   

Wadeye (N.T.) 

#### Ehdotettu termi englanniksi   

Wadeye (N.T.) 

#### Perustelut ehdotukselle   

RDA:n mukaiset nimenmuodot (luvut 16.2.2.9 ja 16.2.2.12 + jälkimmäisen yhteydessä oleva SKL ynnä liite B.11) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Keepsakes and surrogates : hijacking music technology at Wadeye (Northwest Australia) / Linda Barwick 

#### Tarkoitusta täsmentävä selite   

Paikkakunta Australian Pohjoisterritoriossa 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Wadeye (N.T.)](http://finto.fi/yse/fi/page/Y506862)

**Comment by mirmaid** [comment]
Ei ole muita samannimisiä kaupunkeja.
