### ISSUE TITLE
ekologinen kompensaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6863]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ekologinen kompensaatio 

#### Ehdotettu termi ruotsiksi   

ekologisk kompensation 

#### Ehdotettu termi englanniksi   

ecological compensation 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luonnonsuojelu](http://www.yso.fi/onto/yso/p11) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ekologiset kompensaatiot Suomen rannikolla ja merialueilla https://helda.helsinki.fi/handle/10138/246849 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Tarkoitusta täsmentävä selite   

"Ekologisella kompensaatiolla tarkoitetaan luontoympäristöä vahingoittavan hankkeen tai toiminnan aiheuttamien ekologisten haittojen hyvittämistä elinympäristöjä ennallistamalla tai suojelutoiminnalla. Ekologinen kompensaatio muistuttaa ‘saastuttaja maksaa’ -periaatetta, missä saastuttaja korvaa aiheuttamansa vahingon. Ekologisessa kompensaatiossa luontoa heikentävä taho hyvittää aiheuttamansa heikennyksen." 
Lähde: http://www.ym.fi/fi-FI/Luonto/Tuore_kasikirja_tukemaan_luontoon_kohdis(44887) 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [ekologinen kompensaatio](http://finto.fi/yse/fi/page/Y506863)

**Comment by ilona-x** [comment]
Englanniksi **biodiversity offsetting**? https://en.wikipedia.org/wiki/Biodiversity_offsetting
ko. termiä käytetty teoksessa: Luontotyyppien soveltuminen ekologiseen kompensaatioon Suomessa (Applicability of biodiversity offsetting to habitat types in Finland)

YSA:ssa on kompensaatio KÄYTÄ kompensointi http://finto.fi/ysa/fi/page/Y148312

**Comment by mirmaid** [comment]
4 viitettä Melindassa.
