### ISSUE TITLE
feministinen taloustiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6865]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

feministinen taloustiede 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [feministinen taloustiede](http://finto.fi/yse/fi/page/Y506865)

**Comment by satuniininen** [comment]
LCSH:ssa Feminist economics http://id.loc.gov/authorities/subjects/sh95004310

Ihan relevantti lisä muiden taloustieteen koulukuntien jatkoksi.

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. feministisk ekonomi
