### ISSUE TITLE
liiketoimintaekosysteemi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6866]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

liiketoimintaekosysteemi 

#### Vaihtoehtoiset termit ja ilmaisut   

liiketoiminnan ekosysteemi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[liiketoiminta](http://www.yso.fi/onto/yso/p2439) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Tarkoitusta täsmentävä selite   

https://www.sitra.fi/tulevaisuussanasto/liiketoimintaekosysteemi/ 

#### Perustelut ehdotukselle   

Termiyhdistelmän "liiketoiminta + ekosysteemi" sijaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arvoa ainekierroista, http://urn.fi/URN:ISBN:978-951-563-855-7 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [liiketoimintaekosysteemi](http://finto.fi/yse/fi/page/Y506866)

**Comment by ilona-x** [comment]
Toimiva linkki esimerkkijulkaisuun: https://www.sitra.fi/julkaisut/arvoa-ainekierroista/

Melinda: liiketoimintaekosysteemi x 6

**Comment by satuniininen** [comment]
Business ecosystems ei LCSH:ssa

**Comment by mariaforsen** [comment]
Sv. affärsverksamhetsekosystem /finlex, affärsekosystem
