### ISSUE TITLE
asuntosijoittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6867]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

asuntosijoittaminen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sijoitustoiminta](http://www.yso.fi/onto/yso/p4321) 

#### Assosiatiiviset (RT)   

[asuntokauppa](http://www.yso.fi/onto/yso/p20824) 
[vuokranantajat](http://www.yso.fi/onto/yso/p25330) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Perustelut ehdotukselle   

Finto-palaute: "Ehdotan asiasanoiksi: asuntosijoittaminen, asuntosijoittaja(t). Näillä sanoilla opiskelijat etsivät julkaisuja, ja myös pankit käyttävät kyseisiä termejä."

Käsitettä ei hieman yllättäen löydy mistään Finton sanastosta, edes ohjausterminä. Muutama Melinda-hitti löytyy. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Näillä sanoilla opiskelijat etsivät julkaisuja, ja myös pankit käyttävät kyseisiä termejä. 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [asuntosijoittaminen](http://finto.fi/yse/fi/page/Y506867)

**Comment by ilona-x** [comment]
YSAssa sijoitustoiminnan http://www.yso.fi/onto/ysa/Y117654 alakäsitteinä tällä hetkellä vain eettinen sijoittaminen & pääomasijoittaminen eli YSAssa ei ole tällä hetkellä vastaavia sijoittamisen alakäsitteitä esim. osakesijoittaminen

**Comment by mirmaid** [comment]
7 viitettä Melindassa.

**Comment by ilona-x** [comment]
Melinda: 
asunnot & sijoitustoiminta x 64
kiinteistöt & sijoitustoiminta x 65

**Comment by YSA-kokous** [comment]
Tutkittava osakesäästäminen? Seuraava kokous. Myös kiinteistösijoittaminen.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: osakesäästäminen: _rahojen sijoittaminen osakkeisiin säästämistarkoituksessa_.

**Comment by mirmaid** [comment]
https://www.osakeliitto.fi/osakesaastajat/
https://fi.wikipedia.org/wiki/Osakesijoittaminen

**Comment by mirmaid** [comment]
Taloussanasto?

**Comment by tpalonen** [comment]
Osakesäästäminen ja osakesijoittaminen eri asioita. Osakesäästäminen ottaa kantaa, miksi sijoitetaan, osakesijoittaminen ei.

Miten kävi itse asuntosijoittaminen-käsitteen kanssa?

**Comment by mirmaid** [comment]
^ Ei päätetty vielä.

**Comment by YSA-kokous** [comment]
Hyväksytään kiinteistösijoittaminen ja tämän lisäksi erillinen käsite asuntosijoittaminen. YSO-ryhmä miettii näiden välistä suhdetta (LT? RT?).

Lisäksi muutetaan osakesäästäminen muotoon osakesijoittaminen, ohjaustermiksi osakesäästäminen. Nämä riittävässä määrin samamerkityksiset, osakesijoittaminen enemmän nykypäivän kieltä.

**Comment by mariaforsen** [comment]
Sv. 
-fastighetsinvestering ET fastighetsplacering
-bostadsinvestering ET bostadsplacering
