### ISSUE TITLE
Jangtse

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6869]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Jangtse 

#### Ehdotettu termi ruotsiksi   

Yangtze 

#### Ehdotettu termi englanniksi   

Yangtze 

#### Vastaava käsite muussa sanastossa   

Jangtse : <http://kaino.kotus.fi/eksonyymit/index.php?a=tietue&id=692&ex=Jangtse> 
Jangtse : https://fi.wikipedia.org/wiki/Jangtse 

#### Perustelut ehdotukselle   

Aasian pisin joki, maailman kolmanneksi pisin joki. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cong zhijie guanzhi dao minzhu xieshang 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Jangtse](http://finto.fi/yse/fi/page/Y506869)

**Comment by mirmaid** [comment]
Ulkomaisten jokien yläkäsitteet? (kokonaan Kiinan alueella)

**Comment by mirmaid** [comment]
Yläkäsitteeksi valtio, jos kokonaisuudessaan yhden valtion alueella. Muut tapauskohtaisesti.
