### ISSUE TITLE
kulttuuri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6870]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kulttuuri](http://www.yso.fi/onto/ysa/Y96481) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

sulkutarkenteiden lisääminen käsitteille kulttuuri ja kulttuurit 

#### Perustelut ehdotukselle   

Käsitteitä on käytetty jonkin verran ristiin, joten tarvitaan sulkutarkenteet erottamaan ne toisistaan. YSOssa on jo käytössä muodot kulttuuri (toimintatavat) ja kulttuurit (kulttuurimuodot). 

Vaihtoehtoisest käsitteet voidaan myös yhdistää ja ottaa yksikkömuoto käytettäväksi termiksi. Yksikkö- ja monikkomuodon välillä on merkitysero, muttei se aina käy ilmi kuvailtavasta aineistosta. 

#### Ehdottajan organisaatio   

KK / YSO

**Comment by mirmaid** [comment]
kulttuurit YSAan 1987 (selaus 1912)
kulttuuri YSAan 1989 (selaus 16664)
LCSH: Culture

**Comment by mirmaid** [comment]
Monikko:
eri kulttuurit suhteessa toisiinsa tai johonkin ilmiöön: 
_Understanding intercultural communication : negotiating a grammar of culture
Kulttuurinen moninaisuus peruskoulun suomi toisena kielenä -oppikirjoissa
Ilmastonmuutos ja sen vaikutukset arktisella alueella
Vienan vesistöt ja kulttuurit vuorovaikutuksessa
World dance cultures : from ritual to spectacle
The Atlas of Beauty : women of the world in 500 portraits_

kulttuurit kokonaisuutena ja historiallisena jatkumona:
_Sivilisaation loppu
Maailmanhistoria muutamassa minuutissa
Through the ages : A new story of civilization
Nojatuolimatkailua perikadon maisemissa
Kohti suurta romahdusta: Guillaume Fayen ”Convergence of Catastrophes”_

tietty kulttuuri tai kulttuurit esim. arkeologian tai kulttuurihistorian tutkimuskohteena: 
_1177 B.C. : the year civilization collapsed
Northern European prehistory, from above
Akkulturation im Mittelalter
Silla : Korea’s golden kingdom_

**Comment by mirmaid** [comment]
Toimivan tarkenteen lisääminen yksikölle tuntuu melko mahdottomalta, joten vaihtoehdoksi jäänee monikon korvaaminen muilla termeillä. 
MAOssa on _arkeologiset kulttuurit_, joka kattaisi osan viimeisen ryhmän tapauksista. Muuten pitäisi käyttää yksikköä ja lisäksi muita termejä (toki usein on käytettykin _kulttuurit_-termin ohella esim. _kulttuurierot_ ym.). Keskimmäisen ryhmän osalta kuvailtaisiin varmaankin yhdistelmällä _kulttuuri-sivilisaatio-yhteiskuntakehitys-länsimainen kulttuuri_.

**Comment by YSA-kokous** [comment]
arkeologiset kulttuurit
kulttuurit KÄ kulttuuri
