### ISSUE TITLE
hydrofobisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6874]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hydrofobisuus 

#### Ehdotettu termi englanniksi   

hydrophobicity 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:978-952-317-397-2 

#### Perustelut ehdotukselle   

vettähylkivä https://fi.wikipedia.org/wiki/Hydrofobinen 

**Termiehdotus Fintossa:** [hydrofobisuus](http://finto.fi/yse/fi/page/Y506874)

**Comment by jtuohini** [comment]
KT-muodoksi varmaan "vettähylkivyys" – ellei koko termiksi tuollainen suomenkielinen olisi itsestäänselvemmin ymmärettävä (ja ettei vahingossakaan sekoittuisi hydrofobiaan, kumpaa sillä sitten halutaankin tarkoittaa, raivotautia tai vesikammoa).

**Comment by ilona-x** [comment]
Melinda: hydrofobisuus x 7

LCSH: 
Hydrophobic surfaces http://id.loc.gov/authorities/subjects/sh90003785
Water repellents http://id.loc.gov/authorities/subjects/sh85145611

**Comment by YSA-kokous** [comment]
Tutkitaan

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Ilmatiede:vett%C3%A4_hylkiv%C3%A4

MAO/TAO: vettähylkivyys http://www.yso.fi/onto/tao/p982

**Comment by mirmaid** [comment]
Google:
vettähylkivyys 1100
hydrofobisuus 1600 (Melinda 7)
vedenhylkivyys 1800 (Melinda 5)

**Comment by jtuohini** [comment]
Ja mitähän noista kolmesta mahtaa suosittaa Kielitoimisto…

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjasta löytyy vain _vettähylkivä_.

**Comment by mariaforsen** [comment]
Sv. hydrofobicitet ET hydrofobitet, vattenavstötning

**Comment by YSA-kokous** [comment]
vettähylkivyys
