### ISSUE TITLE
kootut teokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6875]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kootut teokset](http://www.yso.fi/onto/ysa/Y102673) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan SLM-sanastoon 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSAssa, onko käytetty genreterminä?

**Comment by mirmaid** [comment]
Hyväksytty / SLM. Lisätään määritelmä: Aineisto, joka sisältää tai jonka on tarkoitus sisältää yhden tekijän kaikki teokset. Aineistoja, jotka ovat julkaisuhetkellä täydellisiä, pidetään koottuina teoksina.
Kokoomateokset: Kokoelma yhden tai useamman tekijän teoksia. ST kootut teokset.
