### ISSUE TITLE
liike

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6877]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liike](http://www.yso.fi/onto/ysa/Y103126) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Käsitteet _liike_ ja _liikkeet_ ovat päällekkäisiä aineistoissa, jotka käsittelevät kehon liikettä/liikkeitä esim. tanssin, näyttelijäntyön tai muun kehollisen ilmaisun yhteydessä. 
Lisäksi yksiköllistä muotoa on käytetty elottomien kappalaiden liikkeen kuvailuun.
Monikollista on käytetty todella paljon liikeharjoitteita sisältävien aineistojen kuvailussa. 

esim:
**Liikkeet** 
Tie tasapainoon : viiden viikon joogaohjelma pelottomuuteen 
300 lihaskuntoliikettä : Sportyplanner 
Clinical kinesiology and anatomy 
Ruotuun taipumaton : tutkimusmatka tanssin improvisatorisen opettamisen oppimiseen /

**Liike**
The physical actor : contact improvisation from studio to stage
Movements of interweaving : dance and corporeality in times of travel and migration /
Measurements and applications of mechanical motion in the quantum limit / Erno Damskägg.
Materials that move : smart materials, intelligent design 

#### Ehdotettu muutos   

Yhdistetään _liikkeet_ KÄYTÄ _liike_
Lisätään ohjaus _liikkeet (harjoitukset)_ KÄYTÄ _harjoitukset_ (Esimerkiksi teoksen 300 lihaskuntoliikettä kuvailussa on jo käsitteet _harjoitukset, lihaskunto, kuntoliikunta. Liikkeet_ tuskin tuo tähän erityistä lisäarvoa.) 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Tämän ei pitäisi olla konversiolle ongelma, koska sekä yksiköllä että monikolla on YSO-vastine, joten jos helppoa yhdistämisratkaisua ei löydy, voidaan myös siirtää?

**Comment by mariaforsen** [comment]
Ruotsiksi nyt (ei toimiva): liike=rörelse (fenomen), liikeet=rörelser (motorik)
Alkuperäinen ehdotus olisi hyvä. Ryhminä olisi sitten 07 ja 97 vai?

Jos tarvitaan tämän lisäksi liikesarjat=rörelseserier sekin on mahdollista lisätä? Melindassa näyttäisi olevan jonkin verran sitä.

**Comment by ilona-x** [comment]
Melinda-viitteiden perusteella muutos liikkeet -> liike näyttäisi olevan ok. Monissa tietueissa jo nyt paljon muutakin termistöä:

liike 
liikkuvuus
harjoitukset
harjoitteet
harjoittelu
tekniikat
motoriikka

Alkuperäisessä ehdotuksessa olevien ohjaustermien lisäksi voisi olla **liikkeet (harjoitteet) KÄYTÄ harjoitteet** (sv. träningsmoment, eng. physical exercises)

Yksi mahdollinen termi voisi olla harjoitusliikkeet? Vai pitäisikö ohjata harjoitusliikkeet KÄYTÄ harjoitukset, harjoitteet.

**Comment by mirmaid** [comment]
_Harjoitukset_ on ruotsiksi _övningar_, soveltuuko?

**Comment by mirmaid** [comment]
_Harjoitteet_ käytetty tyypillisimmin kyllä liikkumisesta/liikunnasta, mutta myös hyvin monenlaisesta muusta harjoittelusta (puhe, muisti, teatteri...). Onko tämä ongelmatonta?

**Comment by mirmaid** [comment]
Monissa urheiluun liittyvissä viitteissä _harjoitteet_ tms. tuntuisi kuvaavammalta korvaajalta kuin _liike_ (esim. _Traditional tae kwon do technique patterns_ tai _Military cross-training: treenaa kuin erikoisjoukoissa_). Omaan korvaani _liike_ yksikössä viittaa enemmän liikkumiseen tai liikkuvuuteen, kuin tiettyihin suoritettaviin liikeharjoituksiin.

Myös motorisen kehityksen yhteydessä kyse on varmaan enemmän tiettyjen liikkeiden oppimisesta tai kyvystä suorittaa niitä, kuin kyvystä yleisesti liikkeeseen, mutta ehkä niissä riittävät motoriikka-termit.

**Comment by mariaforsen** [comment]
Sanastossa on jo övningar=harjoitukset.

**Comment by mariaforsen** [comment]
Harjoitteet=träningsmoment on siis jo sanastossa.

**Comment by mariaforsen** [comment]
Harjoitteet=träningsmoment voidaan myös käyttää ruotsin osalta. 
Kannatan alkuperäisen ratkaisun toteuttamista (nykyinen päällekkäisyys on ollut jo todella pitkään ongelmana)

**Comment by mirmaid** [comment]
^ Käykö tuo _träningsmoment_ siis myös noista puhe- tai muistiharjoitteista yms.?

**Comment by mariaforsen** [comment]
Kyllä käy, vaikka useimmiten onkin urheilusta tms. kyse.

**Comment by FinMeSHienPaimentaja** [comment]
Mikä ero on "harjoituksilla" ja "harjoitteilla"...? Minusta "harjoitteet" kuulostaa jotenkin vanhahtavalta....Entä "liikeharjoittelu"?

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta liikkeet. Tehdään seuraavat ohjaustermit:
liikkeet KÄYTÄ liike.
liikkeet (harjoitteet) KÄYTÄ harjoitteet
liikkeet (motoriikka) KÄYTÄ motoriikka

Tehdään Melinda-korjauksia liikkeet-käsitteelle päätöksen mukaisesti.
