### ISSUE TITLE
Syyttäjälaitos

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6878]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Syyttäjälaitos 

#### Ehdotettu termi ruotsiksi   

Åklagarmyndigheten 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 
[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

#### Perustelut ehdotukselle   

Syyttäjälaitoksen organisaatio uudistuu 1.10.2019. Keskusviraston uusi nimi on Syyttäjälaitos, ja se muodostuu syyttäjäalueista. Kihlakunnansyyttäjän nimike muuttuu aluesyyttäjäksi. Tiedote: https://oikeusministerio.fi/artikkeli/-/asset_publisher/syyttajalaitos-organisoidaan-yhdeksi-virastoksi-lokakuun-2019-alusta?_101_INSTANCE_0tW6d2FGlU8O_languageId=fi_FI 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. tiedotteiden ja muiden verkkoaineistojen 

**Ehdottajan organisaatio:** oikeusministeriö

**Comment by mirmaid** [comment]
Lisätty Suomalaiset yhteisönimet -sanastoon, http://urn.fi/URN:NBN:fi:au:cn:226926A.
