### ISSUE TITLE
neuropsykiatrinen kuntoutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6879]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

neuropsykiatrinen kuntoutus 

#### Tarkoitusta täsmentävä selite   

neuropsykiatrinen kuntoutus tarkoittaa sitä, että kuntoutetaan potilaita tai asiakkaita, joilla on neuropsykiatrisia häiriöitä, esim. ADHD tai autismikirjon häiriö. Kuntoutus itsessään voi sisältää vaikkapa neuropsykologista kuntoutusta, joka taas on vaikkapa tiedollisten toimintojen (tarkkaavaisuuden, keskittymisen, muistin ja oppimisen, jne) harjaannuttamista muun arkitoimintakyvyn tukemisen ohella. Tavallisimmin neuropsykologista kuntoutusta tarvitaan aivovamman tai muun aivotoiminnan häiriön kuntouttamiseen. 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [neuropsykiatrinen kuntoutus](http://finto.fi/yse/fi/page/Y506879)

**Comment by ilona-x** [comment]
YSAssa on neuropsykiatrinen valmennus  (yläkäsite psykiatrinen kuntoutus) http://www.yso.fi/onto/ysa/Y189742

**Comment by mirmaid** [comment]
^ Ehdottajan mukaan ei ole sama asia, unohdin lisätä kommentin tähän. Liittyisikö johonkin tällaiseen https://kysykelasta.kela.fi/viewtopic.php?f=46&t=44021

**Comment by mirmaid** [comment]
http://www.sosionova.fi/palvelumme/neuropsykiatrinen-kuntoutus/

http://www.kto-vs.fi/palvelut/kuntoutuspalvelut/nepsy/Sivut/default.aspx
http://www.kto-vs.fi/palvelut/kuntoutuspalvelut/nepsy-valmennus/Sivut/default.aspx

**Comment by YSA-kokous** [comment]
neuropsykologinen kuntoutus? Tutkitaan.

**Comment by ilona-x** [comment]
https://www.kela.fi/neuropsykologinen-kuntoutus

**Comment by mariaforsen** [comment]
Sv. neuropsykologisk rehabilitering ET neuropsykiatrisk rehabilitering

**Comment by YSA-kokous** [comment]
neuropsykologinen kuntoutus
