### ISSUE TITLE
Nintendo-pelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6880]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Nintendo-pelit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

NES atlas 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [Nintendo-pelit](http://finto.fi/yse/fi/page/Y506880)

**Comment by mariaforsen** [comment]
Sv. Nintendospel ET Nintendo-spel
