### ISSUE TITLE
amerikanbulldoggi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6881]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

amerikanbulldoggi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [amerikanbulldoggi](http://finto.fi/yse/fi/page/Y506881)

**Comment by mariaforsen** [comment]
Sv. american bulldog ET amerikansk bulldogg
