### ISSUE TITLE
gagauzit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6882]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gagauzit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [gagauzit](http://finto.fi/yse/fi/page/Y506882)

**Comment by mariaforsen** [comment]
Sv. gagauzer
