### ISSUE TITLE
sarmatismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6883]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarmatismi 

#### Vaihtoehtoiset termit ja ilmaisut   

sarmatialaisuus 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sarmatismi](http://finto.fi/yse/fi/page/Y506883)

**Comment by satuniininen** [comment]
https://fi.wikipedia.org/wiki/Puolan_kirjallisuus#Barokki_ja_sarmatismi
"Sarmatialaisuudella tarkoitettiin käsitystä Puolasta idän ja lännen välissä olevana välittäjänä, ei suinkaan lännen etuvartiona. Sarmatialaisuus korosti Puolan yhteyttä muun muassa vanhaan liittolaiseen Turkkiin ja Puolan ja Liettuan kaksoismonarkian luonnetta monikansallisena valtiona, johon mahtui myös itäisiä kansoja ja kulttuuripiirteitä."

https://en.wikipedia.org/wiki/Sarmatism

Ei LCSH:ssa

**Comment by mirmaid** [comment]
Kerran Melindassa

**Comment by YSA-kokous** [comment]
sarmatialaisuus

**Comment by mariaforsen** [comment]
Sv. sarmatism ET sarmatstil
