### ISSUE TITLE
teutonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6884]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

teutonit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [teutonit](http://finto.fi/yse/fi/page/Y506884)

**Comment by mirmaid** [comment]
6 viitettä Melindassa. 
https://fi.wikipedia.org/wiki/Teutonit

**Comment by mariaforsen** [comment]
Sv. teutoner
