### ISSUE TITLE
slovakialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6885]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

slovakialaiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [slovakialaiset](http://finto.fi/yse/fi/page/Y506885)

**Comment by YSA-kokous** [comment]
vs. slovakit?

**Comment by mariaforsen** [comment]
Ruotsiksi taitaa olla vain slovaker. Onko suomeksi oikeasti kaksi eri termiä?

**Comment by mirmaid** [comment]
Nyt siis sanastossa _tšekit, slovakit_ ja _tšekkoslovakialaiset_. Jos otettaisiin erikseen _slovakialaiset_ niin pitäisi varmaan ottaa myös _tšekkiläiset_ erikseen.

**Comment by mirmaid** [comment]
Wikipedia: _Slovakit on slaavilainen kansa, jonka jäsenet puhuvat länsislaavilaisiin kieliin kuuluvaa slovakin kieltä. Suurin osa slovakeista on katolilaisia. Historiallisia slovakkivähemmistöjä asuu muun muassa Tšekissä, Unkarissa ja Serbiassa, lisäksi slovakkisiirtolaisia asuu Kanadassa ja Yhdysvalloissa._ 

https://fi.wiktionary.org/wiki/slovakialainen#Suomi

Näiden käyttö kuvailussa johdonmukaisesti olisi kyllä haastavaa.

**Comment by ilona-x** [comment]
samankaltaisia myös esim.:
kroaatit & kroatialaiset  YSOssa kroaatit https://fi.wikipedia.org/wiki/Kroaatit
albaanit & albanialaiset YSOssa albaanit KT albanialaiset https://fi.wikipedia.org/wiki/Albaanit
bulgaarit & bulgarialaiset YSOssa bulgarialaiset https://fi.wikipedia.org/wiki/Bulgarialaiset

**Comment by YSA-kokous** [comment]
KÄ slovakit
