### ISSUE TITLE
bosnialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6886]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bosnialaiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [bosnialaiset](http://finto.fi/yse/fi/page/Y506886)

**Comment by mariaforsen** [comment]
Sv. bosnier
