### ISSUE TITLE
tšekit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6887]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tšekit 

#### Vaihtoehtoiset termit ja ilmaisut   

tšekkiläiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tšekit](http://finto.fi/yse/fi/page/Y506887)

**Comment by mariaforsen** [comment]
Sv. tjecker
