### ISSUE TITLE
tšekkoslovakialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6888]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tšekkoslovakialaiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tšekkoslovakialaiset](http://finto.fi/yse/fi/page/Y506888)

**Comment by mariaforsen** [comment]
Sv. tjeckoslovaker
