### ISSUE TITLE
mikrovaltiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6889]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikrovaltiot 

#### Ehdotettu termi ruotsiksi   

mikronationer 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Mikrovaltio 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mikronationer: på besök i hemgjorda länder 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [mikrovaltiot](http://finto.fi/yse/fi/page/Y506889)

**Comment by mirmaid** [comment]
Ei saisi sekoittua _pienet valtiot_ -termiin.

4 viitettä Melindassa.

**Comment by LeKorsu** [comment]
Tarvitsee varmaan selityksen liittyen juuri tuohon Mirjan kommenttiin.

**Comment by YSA-kokous** [comment]
mikrovaltiot (tarkenne x)

**Comment by satuniininen** [comment]
mikrovaltiot (tunnustamattomat) KT tunnustamattomat mikrovaltiot (?)

**Comment by mariaforsen** [comment]
Sv. mikronationer ET skenstater
