### ISSUE TITLE
paljasjalkajuoksu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6890]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

paljasjalkajuoksu 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paljain jaloin lenkille 

**Ehdottajan organisaatio:** BTJ **Termiehdotus Fintossa:** [paljasjalkajuoksu](http://finto.fi/yse/fi/page/Y506890)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. barfotalöpning
