### ISSUE TITLE
länsislaavit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6891]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

länsislaavit 

#### Perustelut ehdotukselle   

Lisäksi itäslaavit ja eteläslaavit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Religion und Gesellschaft im nördlichen westslawischen Raum 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [länsislaavit](http://finto.fi/yse/fi/page/Y506891)

**Comment by mirmaid** [comment]
Kaikkia käytetty Melindassa.

https://fi.wikipedia.org/wiki/L%C3%A4nsislaavit
https://fi.wikipedia.org/wiki/It%C3%A4slaavit
https://fi.wikipedia.org/wiki/Etel%C3%A4slaavit

LCSH: Slavs, Southern jne.

**Comment by mariaforsen** [comment]
Sv. västslaver, östslaver, sydslaver
