### ISSUE TITLE
Sointula

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6892]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Sointula](http://www.yso.fi/onto/ysa/Y94416) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Matti Kurikan perustama sosialistinen siirtokunta Vancouverin lähellä sijaitsevalla Malcolm Islandin saarella 1900-luvun alussa; nykyään paikannimi. 

#### Ehdotettu muutos   

Muutetaan paikannimeksi Sointula (Kanada) ja/tai auktorisoidaan yhteisönä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSA-kokous** [comment]
Molemmat.
