### ISSUE TITLE
kirjallisuusvienti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6894]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjallisuusvienti 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [kirjallisuusvienti](http://finto.fi/yse/fi/page/Y506894)

**Comment by ilona-x** [comment]
YSAssa on kulttuurivienti http://www.yso.fi/onto/ysa/Y171464

Melindassa: 
kirjallisuusvienti 0 osumaa 
kulttuurivienti + kirjallisuus 39 viitettä
vienti + kirjallisuus 54 viitettä
vienti + kulttuurivienti + kirjallisuus 21 viitettä

**Comment by LeKorsu** [comment]
Kannatan erillisen kirjallisuusvienti-termin mukaanottoa. Pitäisi harkita myös musiikkivienti-termiä.

**Comment by mariaforsen** [comment]
Sv. litteraturexport
