### ISSUE TITLE
täydennetty todellisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6895]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[täydennetty todellisuus](http://www.yso.fi/onto/ysa/Y177836) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätty todellisuus päätermiksi 

#### Perustelut ehdotukselle   

vakiintuneempi

**Comment by mirmaid** [comment]
Täydennetty todellisuus -muoto on valittu Tietotekniikan termitalkoiden suosituksen mukaan, http://www.tsk.fi/tepa/fi/haku/t%C3%A4ydennetty%20todellisuus. Lisätty todellisuus on yleistynyt käytössä ohi suositellun. Termimuodon ongelmallisuudesta esim. https://www.kielikello.fi/-/lisaa-todellisuutta-.
