### ISSUE TITLE
ilmastonmuutokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6896]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ilmastonmuutokset](http://www.yso.fi/onto/ysa/Y95530) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ilmastonmuutokset -> ilmastonmuutos. Ilmasto (nykydiskurssissa) ymmärretään pääsääntöisesti yhtenä huolenaihetta aiheuttavana kokonaisuutena. Ilmastossa eittämättä tapahtuu monenlaisia muutoksia, mutta olletenkin asia mielletään paremmin yksikkönä, ilmastonmuutos. Jos haluaa kuvata pienempiä yksittäisiä muutoksia ilmastossa, voinee käyttää sanaparia ilmasto; muutos (+ ehkä muutoslajin tarkenne). Ehdotan siis ilmastonmuutokset-sanan muuttamista yksikkömuotoon. 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
Termin muodosta on keskusteltu aikaisemminkin. Ilmastohistorian kannalta yksikkökin on ongelmallinen ratkaisu, ja myös puhuttaessa tämän hetken tilanteesta verrataan usein esim. aikaisempiin lämpenemiskausiin.

**Comment by YSA-kokous** [comment]
Määritelmä/huomautus.

**Comment by mirmaid** [comment]
LCSH myös Climate change USE Climatic changes. Sanastossa kuitenkin erikseen _Global warming_ ja _Greenhouse effect, Atmospheric_. YSOssa _ilmaston lämpeneminen_ on ohjaustermi ilmastonmuutokset ja kasvihuoneilmiö -termeille. 

SAO myös _Global uppvärmning, Växthuseffekten, Klimatförändringar_

_Ilmastonmuutokset_ käytetty Melindassa yli 9000 kertaa, joten mahdollisen uuden termin lisäämisen ei olisi ihan triviaalia. Ja termi käsittää toki myös nykyisen lämpenemisen.

**Comment by mirmaid** [comment]
Ilmastonmuutos:
Merkittävä pitkän aikavälin muutos globaalissa tai paikallisessa ilmastossa. (Wikipedia)
Sääolojen yleisen luonteen muuttuminen pitkällä aikavälillä. (Tieteen termipankki)

**Comment by mariaforsen** [comment]
Eikö nykytilanne riitä.. Jos jotain uutta/erillistä halutaan se olisi varmaan ilmaston lämpeneminen? https://fi.wikipedia.org/wiki/Ilmaston_l%C3%A4mpeneminen ~sv. global uppvärmning=global warming

**Comment by YSO-kokous** [comment]
Valitaan määritelmäksi Mirjan yllä siteeraama Wikipedia-määritelmä.
