### ISSUE TITLE
kuntoutustarveselvitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6897]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuntoutustarveselvitys 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [kuntoutustarveselvitys](http://finto.fi/yse/fi/page/Y506897)

**Comment by mirmaid** [comment]
1.	Kuntoutustarveselvitys 
2.	Ammatillinen kuntoutustutkimus  

Lähteitä ja selityksiä 
https://www.kela.fi/ajankohtaista-henkiloasiakkaat/-/asset_publisher/kg5xtoqDw6Wf/content/id/2214671 
https://www.kela.fi/kuntoutusselvitys 

Tulevassa tutkimuksessa todetaan tiivistelmässä:
”Kelan ammatillinen kuntoutusselvitys yhdistää kuntoutustarveselvityksen ja kuntoutustutkimuksen, jotka olivat aiemmin erillisiä palveluita.”

**Comment by YSA-kokous** [comment]
KÄ kuntoutustutkimus?

**Comment by YSA-kokous** [comment]
KÄ kuntoutustutkimus
