### ISSUE TITLE
tulokaslajit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6898]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tulokaslajit](http://www.yso.fi/onto/ysa/Y112955) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmä liian suppea? 

#### Perustelut ehdotukselle   

Alakäsitteenä muinaistulokkaat 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Muinaistulokas – arkeofyytti
Definition tulokas, joka on saapunut alueelle jo kauan sitten, ennen kasvitieteilijöiden tarkkailua ja muistiinpanoja
Explanation Suomessa muinaistulokkaiksi katsotaan tulokkaat, jotka ovat saapuneet ennen 1600-lukua.
BS2001, FN2004, SLT2006 
http://tieteentermipankki.fi/wiki/Kasvitiede:muinaistulokas
(sivua muokattu viimeksi v. 2014)
Huom. Googlaamalla löytyneiden viitteiden perusteella näyttää, että voi olla kyse tulokaslajeista tai vieraslajeista. Muinaistulokkaat ovat kasveja, joten YSA-luokka olisi vain 16 kasvitiede, yläkäsite kasvit ja assosiatiiviset käsitteet tulokaslajit ja vieraslajit.

Ehdotus:
Tulokaslaji
Eliölaji, joka on itse levinnyt alueelle parin viime vuosikymmenen aikana (kursivoidun voisi ehkä YSAsta poistaa)
Tulokaslajit ovat levinneet ihmisestä riippumatta. Ne ovat tavallisesti lähtöisin lähialueilta ja pyrkivät asuttamaan samankaltaisia habitaatteja kuin alkuperäisillä esiintymisalueillaan. Usein tuulet ovat tärkeitä kuljettajia tulokaslajeille. Ilmaston lämpenemisen seurauksena esim. eteläisiä perhoslajeja alkaa yhä runsaammin esiintyä pohjoisemmassa. Tulokaslaji voi asuttaa uuden alueen joko pysyvästi tai tilapäisesti. Suomessa villisika ja merimetso ovat esimerkkejä tulokaslajeista.
BS2014, Vieraslajistrategia 2012 
http://tieteentermipankki.fi/wiki/Biologia:tulokaslaji
Ehdotus:
vieraslaji
Ihmisen uudelle alueelle joko aktiivisesti tai passiivisesti tuoma eliölaji. Suomessa minkki, täplärapu, komealupiini ja ovat esimerkkejä haitallisista vieraslajeista.
BS2014, Vieraslajistrategia 2012 
http://tieteentermipankki.fi/wiki/Biologia:vieraslaji

**Comment by mirmaid** [comment]
Alla alkuperäiset tekstit Tieteen termipankista. Nämä ovat uusimmat määritelmät Biologian sanakirjasta ja sen täydennyksistä v. 2014. YSAssa olevat linkit ympäristö.fi-sivuille eivät enää toimi.
tulokaslaji
Definition laji, joka on itse levinnyt maahamme parin viime vuosikymmenen aikana
Explanation Erottelu vieraslajin ja tulokaslajin välillä ei aina ole yksiselitteisen helppoa. 
Vieraslajit ovat tulleet ihmisen toiminnan tuloksena. Tulokaslajit ovat levinneet ihmisestä riippumatta. Tulokaslaji on tavallisesti lähtöisin lähialueilta ja pyrkii asuttamaan samankaltaisia habitaatteja kuin alkuperäisillä esiintymisalueillaan. Usein tuulet ovat tärkeitä kuljettajia tulokaslajeille. Ilmaston lämpenemisen seurauksena mm. eteläisiä lajeja alkaa yhä runsaammin esiintyä Suomessa pohjoisten lajien vastaavasti taantuessa. Tämä on havaittavissa mm. perhosfaunan muutoksina. Tulokaslaji voi asuttaa uuden alueen joko pysyvästi tai tilapäisesti. 
Villisika ja merimetso ovat esimerkkejä tulokaslajeista. Aikaisemmin tulokaslajia on käytetty (ja vieläkin käytetään) vieraslajin synonyyminä.
BS2014, Vieraslajistrategia 2012 
http://tieteentermipankki.fi/wiki/Biologia:tulokaslaji

vieraslaji
Definition ihmisen uudelle alueelle joko aktiivisesti tai passiivisesti tuoma eliölaji
Explanation Suuri osa ihmisen hyväksikäyttämistä lajeista, kuten kotieläimet ja viljelykasvit, on kuljetettu laajoille alueille maapallolla ja ne ovat osoittautuneet yleensä ihmisen kannalta hyödyllisiksi. Sen sijaan niiden vaikutus alkuperäislajistoon on ollut kaksijakoista. Monet vieraslajit eivät ole kyenneet levittäytymään luontoon mikäli ihmisen suora vaikutus niiden ylläpitoon päättyy. Mutta toisaalta hyvin monet ovat villiytyneinä kyenneet leviämään ympäristöön ja muodostuneet kohtalokkaiksi alueen alkuperäislajistolle joko kilpailemalla, saalistamalla, risteytymällä, levittämällä tauteja tai muuttamalla alkuperäislajien elinympäristöjä. Tällaisia haitallisia vieraslajeja ovat olleet mm. minkki varsinkin saariston lintuyhdyskunnissa, täplärapu jonka Eurooppaan tuoma rapurutto on monin paikoin tuhonnut alkuperäiset jokirapukannat. Laivojen painolastivesien mukana Itämereen on tullut runsaasti painolastikasveja.Puutarhoista karannut lupiini on levinnyt laajoille alueille hävittäen tieltään monimuotoisen ketokasvillisuuden. Nykyään mm. lainsäädännöllä pyritään tarkoin kontrolloimaan tai estämään uusien lajien maahantuontia.
BS2014, Vieraslajistrategia 2012 
http://tieteentermipankki.fi/wiki/Nimitys:vieraslaji

**Comment by mirmaid** [comment]
**Tulokaslajit:** 
YSOssa käsitteellä ei ole määritelmää. YSA: _Tulokaslajilla tarkoitetaan maahamme äskettäin (viimeisen vuosisadan aikana) levinnyttä eliölajia. Osa tulokaslajeista on sellaisia, joiden levinneisyysalue on lähialueilta luontaisesti laajenemassa. Leviämistä saattavat edesauttaa lämpöoloiltaan suotuisat ajanjaksot ja sopivat tuulet._

Wikipedia: _Tulokaslaji on eliölaji, joka on levinnyt uudelle alueelle omin avuin, ihmisestä riippumatta._
Tieteen termipankki: _laji, joka on itse levinnyt maahamme parin viime vuosikymmenen aikana_

Tässä mielestäni Wikipedian määritelmä on paras.

**Comment by mirmaid** [comment]
**Vieraslajit:**
YSO: _Vieraslajiksi kutsutaan sellaista luontoon levinnyttä tulokaslajia, joka ei alun perin ole kuulunut ekosysteemiin eikä olisi pystynyt sinne omin neuvoin leviämään. Vieraslaji on ylittänyt luontaiset leviämisesteet, kuten mantereen, meren tai vuoriston, ihmisen tietoisella tai tahattomalla myötävaikutuksella._ (Lähde ilmeisesti Suomen kansallinen vieraslajistrategia)

Wikipedia: _Vieraslaji on eliölaji, joka ei esiinny tarkasteltavalla alueella alkuperäisenä, vaan ihmisen sinne joko tahattomasti tai tahallisesti siirtämänä kantana._
Tieteen termipankki: _ihmisen uudelle alueelle joko aktiivisesti tai passiivisesti tuoma eliölaji_

**Comment by mirmaid** [comment]
**Muinaistulokkaat:**
YSO: Kasvilaji, joka on tullut alueelle jo varhain, ajankohtana josta ei ole olemassa kasvitieteellistä havaintotietoa. (Lähteenä Tieteen termipankki, jossa nykyinen muotoilu: _tulokas, joka on saapunut alueelle jo kauan sitten, ennen kasvitieteilijöiden tarkkailua ja muistiinpanoja_)

**Comment by mirmaid** [comment]
Vaikuttaa siltä, että _tulokaslajin_ määritelmää on tarkennettu niin, että se tarkoittaa vain ilman ihmisen myötävaikutusta alueelle levinneitä lajeja, joten _vieraslajit, muinaistulokkaat, uustulokkaat ja sotatulokkaat_ eivät voi olla sen alakäsitteitä. (YSOn vieraslajin määritelmä löytyi samassa muodossa muualtakin, alkuperäistä sivua ei enää ole.)

**Comment by mariaforsen** [comment]
ALLFO tulokaslajit=nya arter, joten hyvin leveä merkityskenttä kyllä. Ruotsin osalta Kielitoimiston määritelmä: "tulokaslaji jllek alueelle n. viimeisen sadan vuoden aikana levinnyt eliölaji" on toimivin. Tämän aihealueen käsitteet eivät taida toimia aivan samalla tavalla kielten välillä.

Wikipediassa vieraslaji = https://sv.wikipedia.org/wiki/Introducerad_art
 "Introducerad art är en art som lever utanför sitt ursprungliga utbredningsområde och som har hamnat där på grund av människans medvetna eller omedvetna inblandning. Introducerade arter som skadar ekosystemet de introducerats till, som har negativa effekter på jordbruk och dylikt, eller påverkar hälsan negativt hos djur och människor, kallas invasiv art."

Toisaalta Suomessa näin: https://mmm.fi/sv/frammande_arter ja http://finlex.fi/sv/laki/alkup/2015/20151709

Suomeksi ei näytä olevan samanlaista erottelua haitallisuuden perusteella (sv. invasiv art) vaan se on sitten "haitallinen vieraslaji"? Ks. myös https://en.wikipedia.org/wiki/Invasive_species

Tämän kaiken perusteella voisi olla: 
vieraslajit=främmande arter/introducerade arter (eli ihmisen vaikutuksesta tulleet)
tulokaslajit= ? mahd. invandrade arter? /wsoy  (ei ihmisen vaikutuksesta vai riippumatta siitä?)

Tällainen erottelu ei tosin taida olla ihan selvä/yksiselitteinen suomeksikaan, ks. esim. TEPA 

Ja Fintossa näyttää olevan sekaannusta fi vs. eng, ks. http://finto.fi/fi/search?clang=fi&q=tulokaslaji&vocabs= eli nyt eng =haitalliset vieraslajit?

**Comment by mirmaid** [comment]
Ehdotus: siirretään _tulokaslajit_-käsitteen alakäsitteet sen rinnakkaiskäsitteiksi. Määritellään _tulokaslajit_ Wikipedian mukaan: _Tulokaslaji on eliölaji, joka on levinnyt uudelle alueelle omin avuin, ihmisestä riippumatta._ Ei oteta kantaa siihen, milloin tulokaslaji on alueelle levinnyt.

TAI: Jätetään hierarkia nykyiselleen, poistetaan _tulokaslajin_ määritelmä.

**Comment by YSO-kokous** [comment]
Siirretään tulokaslajit-käsitteen alakäsitteet sen rinnakkaiskäsitteiksi. Määritellään tulokaslajit Wikipedian mukaan: _Tulokaslaji on eliölaji, joka on levinnyt uudelle alueelle omin avuin, ihmisestä riippumatta._ Ei oteta kantaa siihen, milloin tulokaslaji on alueelle levinnyt.

Ruotsiksi edelleen hankala, mutta kehitetään jotain em. päätökseen sopivaa.
