### ISSUE TITLE
taivas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6899]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taivas](http://www.yso.fi/onto/ysa/Y104516) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Tarvitsisi käyttää taivas -termiä muussakin kuin uskonnon yhteydessä: Taiteilijoiden taivaat meteorologin silmin / Seija Paasonen
Sääilmiöt ja sen alakäsitteet kuvaavat teoksen sisältöä, mutta taivas olisi myös hyvä termi, 

#### Ehdotettu muutos   

Lisätään ryhmiä / jaetaan

**Comment by satuniininen** [comment]
Joitakin kertoja on näköjään käytettykin ei-uskonnollisessa merkityksessä. YSOssa taivas on uskonnollisten tuotosten alla, joten ryhmien lisääminen ei riitä vaan käsite pitäisi jakaa. 

taivas (uskonto) TAI taivas (kristinusko)?
taivas (ilmakehä)?

**Comment by YSA-kokous** [comment]
taivas (uskonto)
taivas (ilmakehä/taivaankansi/avaruus?) - tutkitaan

**Comment by mirmaid** [comment]
Miten uskonnon _taivas_-käsite suhteutuu _paratiisiin_?

**Comment by mariaforsen** [comment]
Niitä ei ainakaan pidä sekoittaa keskenään, mutta RT-suhde käsitteeseen taivas (uskonto) (ja Jumalan valtakunta) on hyvä olla. Paratiisilla voi olla eri merkityksiä myös johon taivas ei sovi, esim. Vanhan testamentin paratiisi tai tuleva paratiisi maan päällä (joidenkin uskontojen mukaan). Ks. myös esim. https://fi.wikipedia.org/wiki/Paratiisi

**Comment by tpalonen** [comment]
Melindasta löytyi mm. tällaista:
- Peter Wohlleben: Weather detective : rediscovering nature’s secret signs
- Dave White: Sea & sky in acrylics : techniques & inspiration
- Korkea taivas [toimittaneet: Yrjö Sepänmaa, Liisa Heikkilä-Palo ja Virpi Kaukio]. "Korkea taivas perustuu vuonna 2009 järjestetyn Taivaan ja avaruuden estetiikka -konferenssin sisältöön. Ympäristöestetiikan kokonaisvaltaisessa hengessä teoksen artikkeleissa kohtaavat käsitykset taivaasta niin uskonnollisena ja mytologisena mielikuvana, fysikaalisena ilmakehänä ja avaruutena kuin kuvattuna ja kuviteltuna taivaana."
- Seija Paasonen: Taiteilijoiden taivaat : meteorologin silmin.

Minusta kaikkiin näihin sopisi termimuoto **"taivas (ilmakehä)"**. Avaruus on mielestäni sulkutarkenteena harhaanjohtava. Vrt. Wikipedia: "Avaruus on tähtitieteessä pääosin tyhjiön muodostama osa maailmankaikkeutta Maan ilmakehän ulkopuolella." Esim. sään ja meteorologian kohdalla (avaruus)-sulkutarkenne saattaisi näyttää oudolta. Meteorologiahan tutkii nimenomaan ilmakehää, ei sen ulkopuolista maailmankaikkeutta. Taivaankansi sen sijaan omasta mielestäni a) tårta på tårta, b) kielenkäytössä harvinainen,  c) suutuntumaltaan ylätyylinen/runollinen ja d) sisältää myös uskonnollis-mytologisia vivahteita (Ilmarinen takoi taivaankannen jne), joista piti kai sulkutarkenteen avulla päästä eroon.

**Comment by YSO-kokous** [comment]
Valitaan käytettäväksi termiksi "taivas (ilmakehä)".
