### ISSUE TITLE
ajopelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6900]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ajopelit](http://www.yso.fi/onto/ysa/Y185575) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Kun tämä kuuluu vielä ryhmään, jossa mm. matkailu, niin ei ole ihme, että tätä termiä on käytetty kuvailemaan mm. kaikenlaisia yleisesti käytettyä luonnollisen kielen "ajopeli" mukaisia kohteita esim. hevosvoimalla liikkuvaa pika-ajuria. Kun termiä "ajopeli" käytetään luonnollisessa kielessä hyvin yleisesti kahdessa eri merkityksessä. Tätä kannattaisi selkiyttää jotenkin termin kuvailussa, tai vaihtoehtoisesti lisätä ajopeli molemmissa merkityksissä sanastoon, tms. Nyt riski, että aiheuttaa tulevaisuudessakin hyvin helposti virheellistä kuvailua. ks. Finnasta löytyvät aineistot, jotka käyttävät termiä: http://finto.fi/ysa/fi/page/Y185575 

#### Ehdotettu muutos   

Selkeytettävä

**Comment by mirmaid** [comment]
Melindassa lähes 100% genreterminä, ei virheellistä käyttöä (toki tuo toinenkin merkitys sopii myös näissä aineistoissa :smile:). 

Mutta muita käyttäjätahoja ajatellen olisiko sitten _ajopelit (digitaaliset pelit)_ ja ajopelit (ajoneuvot) KÄ _ajoneuvot_?

**Comment by YSA-kokous** [comment]
ajopelit (digitaaliset pelit) ja ajopelit (ajoneuvot) KÄ ajoneuvot
