### ISSUE TITLE
dungaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6901]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dungaanit 

#### Vastaava käsite muussa sanastossa   

Dungaanit : https://fi.wikipedia.org/wiki/Dungaanit 

#### Perustelut ehdotukselle   

termia on käytetty Melindassa, puuttuu YSA:sta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finna.fi/Record/helka.3148556 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [dungaanit](http://finto.fi/yse/fi/page/Y506901)

**Comment by mariaforsen** [comment]
Sv. dunganer ET tunganer
