### ISSUE TITLE
kehopositiivisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6902]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kehopositiivisuus 

#### Ehdotettu termi englanniksi   

body positivity 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aatteet](http://www.yso.fi/onto/yso/p220) 

#### Assosiatiiviset (RT)   

[ruumiinkuva](http://www.yso.fi/onto/yso/p11168) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Wikipedia: "Body positivity is a social movement rooted in the belief that all human beings should have a positive body image, and be accepting of their own bodies as well as the bodies of others." 

#### Perustelut ehdotukselle   

Yle on ehdottanut käsitettä. Yle on käyttänyt sitä jo paljon omien sisältöjensä kuvailussa.
ks. https://yle.fi/aihe/termi/yle/18-262177 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Body positive : understanding and improving body image in science and practice / edited by Elizabeth A. Daniels, Meghan M. Gillen, Charlotte H. Markey. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kehopositiivisuus](http://finto.fi/yse/fi/page/Y506902)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. kroppspositivism ET kroppspositivitet
