### ISSUE TITLE
mihrab

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6903]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mihrab 

#### Ehdotettu termi ruotsiksi   

mihrab 

#### Ehdotettu termi englanniksi   

mihrab 

#### Tarkoitusta täsmentävä selite   

Mihrab (arab. ألمحراب‎) on moskeijan seinään rakennettu syvennys, joka osoittaa rukoussuunnan. https://fi.wikipedia.org/wiki/Mihrab 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Javanese mosque mihrabs & syncretic Islamic ornament 

#### Perustelut ehdotukselle   

Julkaisussa tarkastellaan Jaavalaisen mihrabin ornamentiikkaa. 

**Termiehdotus Fintossa:** [mihrab](http://finto.fi/yse/fi/page/Y506903)

**Comment by tpalonen** [comment]
Monikkoon varmaankin?

**Comment by YSA-kokous** [comment]
mihrabit

**Comment by mariaforsen** [comment]
Sv. mihraber
