### ISSUE TITLE
posetiivarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6905]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

posetiivarit 

#### Ehdotettu termi englanniksi   

organ grinders 

#### Vaihtoehtoiset termit ja ilmaisut   

posetiivinsoittajat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[esittäjät](http://www.yso.fi/onto/yso/p1289) 

#### Vastaava käsite muussa sanastossa   

Organ grinders : <http://id.loc.gov/authorities/subjects/sh85011936> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Merkillinen Mirtelli : "näillä seuduin liikkui eräs posetiivari" /Markku Karvonen. Julkaisija: Suomen posetiivarit ry 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [posetiivarit](http://finto.fi/yse/fi/page/Y506905)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. LT kuitenkin soittajat, RT katusoittajat

**Comment by mariaforsen** [comment]
Sv. positivhalare ET positivspelare
