### ISSUE TITLE
subjektiviteetti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6908]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[subjektiviteetti](http://www.yso.fi/onto/ysa/Y99035) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite ja ohjataan _subjektiviteetti_ KÄ _subjekti (filosofia)_ ja _subjektiviteetti_ KÄ _subjektiivisuus_ 

#### Perustelut ehdotukselle   

Subjektiivisuus ja subjektiviteetti on vaikea erottaa toisistaan varsinkin eri kieliversioissa eikä subjektiviteetille löydy tyhjentävää määritelmää, jonka perusteella sulkutarkenteita voisi laatia. Myös Melinda-käyttö sekavaa ja päällekkäistä. 

#### Ehdottajan organisaatio   

KK/YSO

**Comment by YSA-kokous** [comment]
subjektiviteetti KÄ subjekti (filosofia) ja subjektiivisuus
