### ISSUE TITLE
sairaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6909]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sairaus](http://www.yso.fi/onto/ysa/Y106000) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Käsitteellä tarkoitetaan sairaana olemista, mutta se tulkitaan herkästi _taudit_ -käsitteen synonyymiksi. Ruotsiksi sjukdom (tillstånd) = sairaus ja sjukdomar = taudit, eli tilanne on käyttäjälle hyvin epäselvä. 

#### Ehdotettu muutos   

Tarvitaan sulkutarkenne tai muu selkeyttävä ratkaisu.

Vaihtoehtoja on ainakin kaksi:

1. selventävä ja taudeista erottava lisämääre, esim.

- sairaus (tila)
- sairaus (olotila)
- sairaus (sairastaminen)
- sairaus ja sairastaminen

2. yhdistäminen sairaus + taudit

- sairaus KT taudit (näin Meshissä)

Käytetty Melindassa 2110 kertaa, usein terveyden tai terveydentilan vastakohtana. Näkökulmia on useita kokemuksellisuudesta terveyssosiologiaan ja kaikkeen siltä väliltä. 

#### Ehdottajan organisaatio   

KK / YSO

**Comment by mirmaid** [comment]
Melindassa sairaus 3066 viitettä, taudit 8032 viitettä. 

Lääketieteen termit
**sairaus:** psyyken tai elimistön rakenteen tai toiminnan poikkeavuus, joka aiheuttaa tilapäistä tai pysyvää haittaa, vajaatoimintoja tai vammaisuutta (tauti sekä siihen liittyvät tunteet ja reaktiot)
**tauti:** sairaus | määritettävissä oleva, eri ihmisissä samantapaisin oirein tai löydöksin ilmenevä sairaus

**Comment by mirmaid** [comment]
_Sairaudet_ on ehkä terminä sallivampi kuin _taudit_, ja sopisi ainakin monissa tapauksissa niihin viitteisiin, joissa nyt on käytetty yksiköllistä _sairaus_-termiä. Siinäkin toki monikko muuttaa näkökulman terveyden vastakohdasta siihen, että kyse on tietystä tai useista eriteltävissä olevista sairauksista. Usein _vammaisuus, vanheneminen_  tai _kokemukset_ -termien parina.

Esim.  
_Patients as art : forty thousand years of medical history in drawings, paintings and sculpture
Sairas sisko ja vaiettu veli : vertaisopas erityisen sisaruuden kohtaamiseen
The psychological and social impact of illness and disability_

Muutetaan sairaus, taudit > _sairaudet_?
Lisätään tarkenne _sairaus (sairastaminen)_?

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet. Käytettäväksi termiksi sairaudet, ohjaustermiksi taudit.
