### ISSUE TITLE
lohkoketju

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6910]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lohkoketju 

#### Ehdotettu termi englanniksi   

blockchain 

#### Ehdotettu termi ruotsiksi   

blockkedja 

#### Perustelut ehdotukselle   

Lohkoketjun rakenne. Pääketju (musta) sisältää pisimmän ketjun lohkoja, ja se alkaa "alkulohkosta" (Genesis block, vihreä) päättyen nykyiseen lohkoon. Orpolohkot ja -haarat (Orphan block, violetti) ovat viallisia lohkoja ja ne esiintyvät pääketjun ulkopuolella.
Lohkoketju on tekniikka, jolla toisilleen vieraat toimijat voivat yhdessä tuottaa ja ylläpitää tietokantoja hajautetusti.  https://fi.wikipedia.org/wiki/Lohkoketju 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Industrial blockchain platforms : an exercise in use case development in the energy industry

**Comment by ilona-x** [comment]
hyväksytty sanastoon muodossa lohkoketjut (YSA-kokous 11.12.2018) https://github.com/Finto-ehdotus/YSE/issues/6773
