### ISSUE TITLE
karvasolut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6911]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

karvasolut 

#### Ehdotettu termi ruotsiksi   

hårceller 

#### Ehdotettu termi englanniksi   

Hair cells 

#### Ehdotettu yläkäsite YSOssa (LT)   

[reseptorit](http://www.yso.fi/onto/yso/p9031) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh95005808> 
Wikipedia : https://en.wikipedia.org/wiki/Hair_cell 

#### Tarkoitusta täsmentävä selite   

https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=ltt01505 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Postmitotic state of a cell as a challenge for regeneration inner ear as a model 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [karvasolut](http://finto.fi/yse/fi/page/Y506911)

**Comment by mirmaid** [comment]
Lääketieteen termit: _1. sisäkorvan kuulo-, liike- ja tasapainoreseptorien aistinsolu, jossa ärsykkeenä toimii erikoistuneisiin karvoihin kohdistuva liike-energia; 2. makureseptorisolu jossa on pitkiä makuhuokoseen tunkeutuvia mikrovilluksia; 3. eräs valkosolutyyppi, jossa on useita solulimaulokkeita; vrt. pilosyytti, karvasoluleukemia (→ leukemia)_

**Comment by mirmaid** [comment]
FinMeSH: _kuuloaistin karvasolut_ ja _sisäkorvan karvasolut_. Sikäli kuin käsitän, molemmat sijaitsevat kyllä sisäkorvassa, mutta jälkimmäinen viittaa tasapainoelimen karvasoluihin ja kuuloaistin karvasolut puolestaan sijaitsevat simpukassa.

**Comment by YSA-kokous** [comment]
sisäkorvan karvasolut

**Comment by mariaforsen** [comment]
Sv. innerörats hårceller ET hårceller, sinneshår, hörselhår
