### ISSUE TITLE
ympäristötilastotiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6913]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ympäristötilastotiede 

#### Ehdotettu termi englanniksi   

environmental statistics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tilastotiede](http://www.yso.fi/onto/yso/p3591) 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Environmental_statistics
"Environment statistics is the application of statistical methods to environmental science. It covers procedures for dealing with questions concerning both the natural environment in its undisturbed state and the interaction of humanity with the environment. Thus weather, climate, air and water quality are included, as are studies of plant and animal populations." 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ympäristötilastotieteen perusteet /Hoffrén 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 
[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [ympäristötilastotiede](http://finto.fi/yse/fi/page/Y506913)

**Comment by mariaforsen** [comment]
Sv. miljöstatistik (vetenskaper)
