### ISSUE TITLE
visuaalinen ilmaisu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6915]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[visuaalinen ilmaisu](http://www.yso.fi/onto/ysa/Y184965) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termin suhde asiasanaan "kuvallinen ilmaisu" pitäisi tehdä selväksi. 

#### Perustelut ehdotukselle   

Nyt termit tuntuvat viittaavan yhteen ja samaan asiaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
_Kuvallinen ilmaisu_ on paljon vanhempi ja käytetympi. _Visuaalisella ilmaisulla_ on varmaankin tavoiteltu jotain laajempaa, mutta Melindan kuvailuissa sopisi tavallisesti silti yhtä hyvin _kuvallinen ilmaisu_. Silloin kun ei sovi, voisi ehkä riittää yleisemmin _visuaalisuus_ tms.

**Comment by satuniininen** [comment]
Olisiko näiden yhdistäminen mahdollista ruotsin kannalta (bildspråk & visuell framställning)?  @mariaforsen

**Comment by YSA-kokous** [comment]
visuaalinen ilmaisu KÄ kuvallinen ilmaisu

**Comment by mariaforsen** [comment]
Sv.
bildspråk ET språkliga bilder, bildliga uttryck
visuell framställning
