### ISSUE TITLE
espanjanmastiffi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6916]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

espanjanmastiffi 

#### Ehdotettu termi ruotsiksi   

spansk mastiff 

#### Ehdotettu termi englanniksi   

spanish mastiff 

#### Vaihtoehtoiset termit ja ilmaisut   

mastin español 

#### Ehdotettu yläkäsite YSOssa (LT)   

[molossityyppiset koirat](http://www.yso.fi/onto/yso/p10135) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Käsikirja Espanjanmastiffista työkoirana 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [espanjanmastiffi](http://finto.fi/yse/fi/page/Y506916)

**Comment by mariaforsen** [comment]
Sv. mastín español ET spansk mastiff
