### ISSUE TITLE
hydrogeokemia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6919]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hydrogeokemia 

#### Ehdotettu termi englanniksi   

hydrogeochemistry 

#### Perustelut ehdotukselle   

The chemistry of ground and surface waters, particularly the relationship between the chemical characteristics and quality of waters and the areal and regional geology 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Modelling hydrogeochemical evolution for the Olkiluoto KBS-3H safety case  ISBN 978-951-652-258-9 

**Termiehdotus Fintossa:** [hydrogeokemia](http://finto.fi/yse/fi/page/Y506919)

**Comment by ilona-x** [comment]
hydrogeokemia KÄYTÄ **vesikemia**? http://www.yso.fi/onto/ysa/Y107246
YSAssa myös **geokemia** http://www.yso.fi/onto/ysa/Y95214

LCSH: 
**Water chemistry** 
KT Aquatic chemistry, Chemical hydrology, Hydrochemistry, Hydrogeochemistry, Natural water chemistry
LT Geochemistry, Hydrology

**Comment by YSA-kokous** [comment]
hydrogeokemia KÄYTÄ vesikemia?

**Comment by mirmaid** [comment]
**Hydrogeologia:** _Maanpinnan alaista vettä, sen esiintymistä, liikkumista, geokemiaa ja sen suhdetta geologiseen ympäristöön tutkiva tiede._ (Geologia.fi); _maanalaisia vesiä käsittelevä geologian ala_ (Tieteen termipankki)

**Geohydrologia:** _Maanalaisia vesiä (maavesiä ja pohjavesiä) käsittelevä hydrologian ala._ (Tieteen termipankki)

Wikipedia: _Geohydrologia tai hydrogeologia on luonnontiede, joka tutkii pohjavettä eli veden liikkeitä huokoisessa maaperässä_

**Comment by mirmaid** [comment]
**Geokemia:** _Geokemia tutkii maapallon kemiaa. Geokemiassa selvitetään eri alkuaineiden jakautumista ja kiertoa maapallon kivi-, vesi- ja ilmakehän sekä elollisen luonnon välillä._ (Wikipedia)

**Hydrogeochemistry:** _The chemistry of ground and surface waters, particularly the relationship between the chemical characteristics and quality of waters and the areal and regional geology._ (Wiktionary)

https://www.geow.uni-heidelberg.de/researchgroups/hydrogeo/
http://www.destress-h2020.eu/en/Best-Practices/Geochemistry-and-Hydrochemistry/

**Comment by mariaforsen** [comment]
Sv. hydrogeokemi
