### ISSUE TITLE
giguet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6920]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

giguet 

#### Ehdotettu termi ruotsiksi   

giguer (?) 

#### Ehdotettu termi englanniksi   

gigues 

#### Vaihtoehtoiset termit ja ilmaisut   

gigas [eng] 
gigat [fin] 
jigit [fin] 
jigs [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sävellykset](http://www.yso.fi/onto/yso/p1515) 

#### Assosiatiiviset (RT)   

[tanssimusiikki](http://www.yso.fi/onto/yso/p181) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85070528> 
LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026881> 
Wikidata : https://www.wikidata.org/wiki/Q567915 
Wikidata : https://www.wikidata.org/wiki/Q1079270 

#### Perustelut ehdotukselle   

Tarvitaan sekä YSA:ssa että SLM:ssä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Gigue (from suite no. 1 for unaccompanied violoncello) / Johann Sebastian Bach 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [giguet](http://finto.fi/yse/fi/page/Y506920)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. YSAan ja SLM:ään.

**Comment by mirmaid** [comment]
Hyväksytty/SLM

**Comment by mariaforsen** [comment]
ET gigor

**Comment by mariaforsen** [comment]
ET gigor (kompositioner)
