### ISSUE TITLE
aktigrafia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6921]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aktigrafia 

#### Ehdotettu termi ruotsiksi   

aktigrafi 

#### Ehdotettu termi englanniksi   

Actigraphy 

#### Vaihtoehtoiset termit ja ilmaisut   

liikeaktiviteettirekisteröinti 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh95007216> 
FinMeSH : <http://www.yso.fi/onto/mesh/D056044> 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Actigraphy in evaluation and follow up of physical functioning of older adults 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Actigraphy 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aktigrafia](http://finto.fi/yse/fi/page/Y506921)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.
