### ISSUE TITLE
koulutusalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6923]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koulutusalat](http://www.yso.fi/onto/ysa/Y130155) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan yksikköön. 

#### Perustelut ehdotukselle   

Finto-palaute: "Miksi käsite on monikossa? muut (samantapaiset) alat näyttävät pääasiassa olevan yksikkömuodossa, paitsi esim. tekniset tai humanistiset alat, mutta ne ovatkin vähän eri tyyppisiä käsitteitä. Kuuluuko koulutusalat olla tässä (LT toimialat) vai pitääkö käsitteen olla yksikkömuodossa?" 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
_Koulutusala_ tarkoittaa siis alaa jota opiskelee tai on opiskellut, johon on saanut koulutuksen, esim. _Koulutusalan yhteys yliopisto-opiskelijoiden poliittiseen orientaatioon_. Se ei siis ole vastaava kuin esim. _opetusala_.

**Comment by YSA-kokous** [comment]
Käyttöhuomautus?

**Comment by tpalonen** [comment]
Ehdotus.
skos:scopeNote: "Käytetään mistä tahansa alasta, jota opiskellaan tai on opiskeltu. Opetusalalla toimivien työntekijöiden toimialaan viitattaessa käytetään käsitettä opetusala."
