### ISSUE TITLE
miksaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6925]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[miksaukset](http://www.yso.fi/onto/ysa/Y214573) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uudelleenmiksaukset päätermiksi? 

#### Perustelut ehdotukselle   

vrt. SLM 

#### Ehdottajan organisaatio   

Muusa

**Comment by mirmaid** [comment]
Sanastossa on lisäksi _miksaus_

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin muuttamista muotoon uudelleenmiksaukset.

**Comment by mariaforsen** [comment]
Sv. remixer ET remixar
