### ISSUE TITLE
lehtorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6930]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lehtorit](http://www.yso.fi/onto/ysa/Y96816) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa: lehtorit (opettajat) ja lehtorit (kirkon työntekijät). Jaettava/selkeytettävä myös YSAssa? 

#### Perustelut ehdotukselle   

Konversio-ongelma 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
1. koulun, ammattioppilaitosten ja korkeakoulujen eräiden opettajien virkanimike. _Äidinkielen lehtori. Historian, musiikin lehtori myös →←._
2. lut. seurakunnan palveluksessa oleva naisteologi, jota ei ole vihitty papiksi. _Seurakuntalehtori._ 

Varmaan korjattavissa suureksi osaksi automaattisesti Melindassa.

**Comment by YSA-kokous** [comment]
lehtorit (opettajat)
lehtorit (kirkon työntekijät)
