### ISSUE TITLE
tekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6931]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tekniikka](http://www.yso.fi/onto/ysa/Y99356) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa: tekniikka (laitteet), tekniikka (menetelmät) ja tekniikka (tieteet). Ratkaistava, säilytetäänkö jako sellaisenaan, vai tehdäänkö siihen muutoksia. 

#### Perustelut ehdotukselle   

Konversio-ongelma 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/611

**Comment by satuniininen** [comment]
Sekä tekniikka tieteenä että tekniikka laitteina ovat hyvin lähellä _teknologia_-käsitettä. Muutenkin _tekniikka (laitteet)_ tuntuu vanhahtavalta merkitykseltä sillä useat sen YSO-alakäsitteistä ovat kai tänä päivänä enemmän softaa kuin varsinaisia laitteita (esim. _huipputekniikka, ohjelmistotekniikka, toimistotekniikka_).

Tekniikka menetelmänä on paljon käytetty ja ilmeisen tarvittu käsite. Käyttötarkoitus olisi selkeämpi, mikäli käsite olisi monikossa.

Paljon käytetty myös viittamaan toimialaan, mutta tähän tarkoitukseen on jo _tekniset alat_.

**Comment by satuniininen** [comment]
Ehdotus:

**tekniikat** KT tekniikka (menetelmät)
Melindan 20 ensimmäisestä viitteesta 11 on tätä merkitykstä, esim:

- Neulojan käsikirja : 300 pintaneulemallia 
- Acting excercises for non-traditional staging : Michael Chekhov reimagined / Anjalee Deshpande Hutchinson.
- Kiehtova kurkkulaulu / Sauli Heikkilä.

JA 

**teknologia** KT tekniikka (tieteet), teknologia (laitteet) TAI **tekniikka ja teknologia**
Melindan 20 ensimmäisestä viitteesta 9 on tätä merkitykstä, esim:

- Tekniikan laskutaito
- Hållbar utveckling : teknik, samhälle och livskvalitet / Håkan Gulliksson, Ulf Holmgren.
- Koneen soturit : hissiyrityksen menestyksen rakentajat / Saara Hilpinen, Eeva Kotioja.
- Koululaisen insinöörikirja / konsultti: Carol Vorderman ; konsultit: Emily Hunt, Carol Vorderman ; suomennos: Jari Sahlgren.
- Suomen kaivostoiminnan toimialakatsaus 2017 / Jouko Karinen, Antti Peronius, Rauno Toppila.
- Word-image interaction in technical translation : students translating an illustrated text / Anne Ketola.
- Suomessa selviytymisen historiaa : kivikaudelta keskiajalle ja 1900-luvun alkuun / Ulla Koskinen.

Jos halutaan säilyttää tekniikka ja teknologia omina käsitteinään, on yksikölliselle tekniikalle lisättävä sulkutarkenne, joka estää sen käytön menetelmät-merkityksessä.

**Comment by LeKorsu** [comment]
Kannatan tekniikat KT tekniikka (menetelmät)
Jos tekniikka (tieteet) korvataan teknologialla, pitääkö silloin muuttaa myös kaikki ne yhdyssana- ja sanaliittotermit, joissa tekniikka on jälkimmäinen osa:  esim. jäähdytystekniikka, langaton tekniikka? [Ei varmastikaan ennen konversiota, mutta onko ylipäätänsä tarpeen]
Ruotsiksi olisi ilmeisesti helppoa, kun tekniikka tieteenalana sanakirjassa teknologi

**Comment by mirmaid** [comment]
:woman_mechanic:

**Comment by YSA-kokous** [comment]
tekniikat KT tekniikka (menetelmät)
teknologia KT tekniikka (tieteet), tekniikka (laitteet)
