### ISSUE TITLE
formalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6932]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[formalismi](http://www.yso.fi/onto/ysa/Y101377) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettu YSOssa: formalismi (aatteet) ja formalismi (tyylit). Puretaanko jako, vai jaetaanko myös YSAssa? 

#### Perustelut ehdotukselle   

Konversio-ongelma 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
YSAssa realismi(t), illusionismi ja naturalismi jaettu vastaavasti, tarkenteena (taide) ja joko (filosofia) tai (politiikka). Tämäntyyppiset jaot ovat käytännössä ongelmallisia.

YSAssa on myös _venäläinen formalismi_.

**Comment by mirmaid** [comment]
Wikipedia: Formalismi (lat. formalis 'muodollinen') on taiteessa, kirjallisuudessa, kritiikissä tai filosofiassa suuntaus, tutkimuksen ala tai tarkastelutapa, joka painottaa muotoa sisällön tai merkityksen sijaan.

**Comment by mirmaid** [comment]
Jonkin verran käytetty myös matematiikan yhteydessä, jolloin ehkä tarkenne _(filosofia)_ tuntuu rajaavalta, vaikka kyse onkin matematiikan filosofiasta.

**Comment by YSA-kokous** [comment]
Yhdistetään YSOssa

**Comment by tpalonen** [comment]
formalismi YK aatteet + RT antiformalismi
ryhmät 02, 87, 90
venäläinen formalismi YK formalismi
