### ISSUE TITLE
kirskulinnut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6934]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kirskulinnut](http://www.yso.fi/onto/ysa/Y102550) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄ kiitäjälinnut 

#### Perustelut ehdotukselle   

Konversio-ongelma 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
YSO-vastineet puuttuvat.
