### ISSUE TITLE
tietokannat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6935]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietokannat](http://www.yso.fi/onto/ysa/Y99512) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termi myös SLM-sanastoon. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Perustelut ehdotukselle   

Tarvitaan tietokantojen kuvailuun

**Comment by mirmaid** [comment]
Hyväksytty/SLM
