### ISSUE TITLE
Lokan tekojärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6936]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Lokan tekojärvi 

#### Ehdotettu termi ruotsiksi   

Lokka bassäng 

#### Ehdotettu termi englanniksi   

Lokka Reservoir 

#### Vaihtoehtoiset termit ja ilmaisut   

Lokan allas 
Lokan tekoallas 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tekoaltaat](http://www.yso.fi/onto/yso/p3810) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Lokan_tekoj%C3%A4rvi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[13 Hydrologia](http://www.yso.fi/onto/yso/p26580) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2241292 

#### Perustelut ehdotukselle   

Kylän ja tekojärven erottaminen toisistaan 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Lokan tekojärvi](http://finto.fi/yse/fi/page/Y506936)

**Comment by mirmaid** [comment]
_Vuotos_ on sanastossa, ei paikkana. LCSH: 151: Williston Lake (B.C.) (BT Lakes); 151: Kariba, Lake (Zambia and Zimbabwe) (BT Lakes & Reservoirs)
