### ISSUE TITLE
atonaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6940]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[atonaalisuus](http://www.yso.fi/onto/ysa/Y100911) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mikä on käsitteen suhde säveljärjestelmiin? RT vai yläkäsitesuhde vai ei mitään? Vrt. tonaalisuus, modaalisuus. Muusa-ryhmä päätti laittaa modaalisuuden säveljärjestelmiin. 

#### Perustelut ehdotukselle   

Ks. modaalisuus. https://github.com/Finto-ehdotus/YSE/issues/5814
Tämä issue on syytä käsitellä YSAn ja Muusan yhteiskokouksessa. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
_tonaalisuus_ nyt siis YSOssa LT taiteisiin liittyvät ominaisuudet, RT säveljärjestelmät

**Comment by YSA-kokous** [comment]
modaalisuus (musiikki) ja kromatiikka YK taiteisiin liittyvät ominaisuudet
