### ISSUE TITLE
isonuottiset nuottijulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6942]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[isonuottiset nuottijulkaisut](http://www.yso.fi/onto/ysa/Y214509) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastooon. 

#### Perustelut ehdotukselle   

SLM-sanastossa on jo termi isotekstiset kirjat. Isonuottiset nuottijulkaisut on yhtä lailla tärkeä. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin ottamista myös SLM:ään. Määritelmä YSAsta.

**Comment by mirmaid** [comment]
Ok/SLM
