### ISSUE TITLE
lauluntekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6943]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lauluntekijät 

#### Ehdotettu termi englanniksi   

songwriters 

#### Ehdotettu yläkäsite YSOssa (LT)   

[säveltäjät](http://www.yso.fi/onto/yso/p2353) 
[sanoittajat](http://www.yso.fi/onto/yso/p7375) 

#### Assosiatiiviset (RT)   

[laulaja-lauluntekijät](http://www.yso.fi/onto/yso/p2351) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Toimijakuvailussa tätä tarvitaan erityisesti, termi on otettu Metatietosanastoon. Muusa voisi pohtia, tarvitaanko termiä YSAssa/YSOssa, 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Miten lauluni syntyvät? 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lauluntekijät](http://finto.fi/yse/fi/page/Y506943)

**Comment by MUUSA-kokous** [comment]
Muusa ei kannata toistaiseksi termin ottamista YSAan.

**Comment by mariaforsen** [comment]
Tarvittu Melindassa, esim. Taikurin apulainen / Yari. Jos on tarkoitus että näistä käytettäisiin sanoittajat ja säveltäjät -termejä, niin pitäisikö niihin tehdä jonkinlaista ohjausta?

**Comment by mirmaid** [comment]
Tähän olisi hyvä saada Muusan kommentti.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ohjaustermin _lauluntekijät_ lisäämistä termeille _sanoittajat_ ja _säveltäjät._

**Comment by AuHo22** [comment]
Tässä on näköjään sama kaksiulotteisuus kuin termissä sarjakuvantekijä, jota käytetään yhtä lailla sarjakuvan kirjoittajasta ja kuvittajasta, mutta ei erikseen, mts: _Liittää teoksen toimijaan, joka on vastuussa sarjakuvan kuvallisesta ja/tai kirjallisesta ilmaisusta_. Lienee eri tavoin vakiintunut käytäntö, jonka historiaa en tunne.
Eikö kuitenkin metatietosanastossa laulaja-lauluntekijän LT pitäisi olla myös sanoittaja ehdotetun ohjauksen mukaisesti? nyk. laulaja + säveltäjä

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Lisätään ohjaustermi _lauluntekijät_ ehdotuksen mukaisesti.
