### ISSUE TITLE
elektroakustinen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6944]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elektroakustinen musiikki](http://www.yso.fi/onto/ysa/Y101140) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mietittävä tämän määritelmä ja suhde elektroniseen musiikkiin sekä taide/populaari-jakoon uudelleen. Nyt määritelmän mukaan tämä on taidemusiikkia ja ohjausterminä elektroninen musiikki. Elektroninen musiikki ei kuitenkaan missään nimessä ole taidemusiikkia. Suurin osa esim. kirjastoasiakkaista ei ajattele Stockhausenia tai Varesea, kun ovat kiiinnostuneet hakemaan elektronista musiikkia.

Määritelmää koskien lainaan keskustelua eloelektroniikka-issuesta: "elektroakustinen musiikki osoittaa hyvin taidemusiikin ja populaarimusiikin välisen rajan vanhanaikaisuuden ja keinotekoisuuden. Kentät menevät tässä vahvasti päällekkäin. Täysin samankuuloista ja samoilla tekniikoilla tehtyä musiikkia tehdään molemmissa. Taidemusiikin ja populaarimusiikin kokeellisen laidan tekijän erottaa ainoastaan se, mikä koulu on käyty. Esimerkkinä vaikkapa kotimaiset Jan Anderzen (Tomutonttu) ja Marja Ahti (Tsembla), joiden musiikki on muodollisin seikoin määriteltynä elektroakustista musiikkia par excellence, mutta ei laskea taidemusiikiksi, koska eivät ole opiskelleet säveltämistä korkeakoulutasolla."
Ts. määritelläänkö genret tekijöiden taustan perusteella vai musiikillisen sisällön perusteella? Vrt. naisrock, naisten klassinen musiikki? 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

Ks ed

**Comment by asormune** [comment]
Voisiko siirtää ohjausterminä olevan "elektroninen musiikki" yleistermiksi niitä tapauksia varten, joita ei tarkemmin pysty yksiselitteisesti luokittelemaan tai jakamaan taide- tai populaarimusiikkiin. Elektroakustinen alatermiksi ja muita termejä sieltä elektronisen populaarimusiikin alta. Vai meneekö hierarkia risukoksi?

**Comment by MUUSA-kokous** [comment]
Muusa ei kannata muutoksia tälle termille.

**Comment by mirmaid** [comment]
Vähintäänkin pitäisi mielestäni ohjaustermejä muuttaa:
elektroninen musiikki (taidemusiikki) KÄ elektroakustinen musiikki
elektroninen musiikki (populaarimusiikki) KÄ elektroninen populaarimusiikki

**Comment by tpalonen** [comment]
Eikös usealla käsitteellä voi olla sama ohjaustermi?

**Comment by YSA-kokous** [comment]
Lisätään elektroninen musiikki KÄ elektroninen populaarimusiikki, elektroninen tanssimusiikki
