### ISSUE TITLE
folk metal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6945]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[folk metal](http://www.yso.fi/onto/ysa/Y208934) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös slm-sanastossa 

#### Perustelut ehdotukselle   

Heavy rockin alalaji, joka on jostain syystä jäänyt pois slm-sanastosta? 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. Sekä YSAan että SLM:ään. Määritelmä: "Kansanmusiikkivaikutteinen heavy metalin tyylilaji". LT heavy metal.

**Comment by mirmaid** [comment]
Ok/SLM
