### ISSUE TITLE
varaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6946]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

varaanit 

#### Ehdotettu termi englanniksi   

monitor lizards 

#### Ehdotettu termi ruotsiksi   

varaner 

#### Ehdotettu yläkäsite YSOssa (LT)   

[liskot](http://www.yso.fi/onto/yso/p11766) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85086857> 
Wikipedia : https://fi.wikipedia.org/wiki/Varaanit 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa, käytetty Melindassa 17 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Phylogeny and taxonomy of the Pacific monitor lizards (Squamata: Varanus: Euprepiosaurus) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [varaanit](http://finto.fi/yse/fi/page/Y506946)

**Comment by mariaforsen** [comment]
Sv. varaner ET goannaödlor
