### ISSUE TITLE
erikoisprosessit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6947]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[erikoisprosessit](http://www.yso.fi/onto/ysa/Y101281) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytetympi muoto (esim. EIF) olisi erityisprosessit. Tämä joko ohjaustermiksi tai päätermiksi. 

#### Perustelut ehdotukselle   

http://tieteentermipankki.fi/wiki/Oikeustiede:erityisprosessi/laajempi_kuvaus 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSA-kokous** [comment]
KÄ erityisprosessit
