### ISSUE TITLE
pelikasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6948]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pelikasvatus 

#### Ehdotettu termi ruotsiksi   

spelfostran 

#### Ehdotettu termi englanniksi   

game education 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Pelikasvatus 

#### Tarkoitusta täsmentävä selite   

Pelikasvatus on pelien ja niihin liittyvien ilmiöiden ymmärtämistä edistävää toimintaa, jonka kohderyhmänä on koko väestö. Pelikasvatuksen tavoitteena on pelilukutaidon edistäminen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pelikasvattajan käsikirjat (http://www.pelikasvatus.fi/kasikirja ja http://www.pelikasvatus.fi/kasikirja2) 

#### Perustelut ehdotukselle   

Pelikasvatusta on tehty Suomessa tavoitteellisesti vuodesta 2011. Pelikasvatus-termi auttaa kasvatustyötä tekeviä toimijoita validoimaan tekemänsä työn. Pelikasvatus asettuu laajemman kasvatuksen käsitteen alle samalla tavalla kuin sanastosta löytyvät mediakasvatus, elokuvakasvatus ja televisiokasvatus. 

**Ehdottajan organisaatio:** Kansallinen audiovisuaalinen instituutti **Termiehdotus Fintossa:** [pelikasvatus](http://finto.fi/yse/fi/page/Y506948)

**Comment by mirmaid** [comment]
Ei Melindassa
