### ISSUE TITLE
tyreotropiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6950]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tyreotropiini 

#### Ehdotettu termi englanniksi   

Thyrotropin 

#### Ehdotettu termi ruotsiksi   

tyreotropin 

#### Vaihtoehtoiset termit ja ilmaisut   

kilpirauhasta stimuloiva hormoni 
tyrotropiini 
TSH 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hormonit](http://www.yso.fi/onto/yso/p2589) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D013972> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85135180> 
Wikipedia : https://fi.wikipedia.org/wiki/Tyreotropiini 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Thyroid-stimulating hormone : reference range and relation to cardiovascular risk 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tyreotropiini](http://finto.fi/yse/fi/page/Y506950)

**Comment by mariaforsen** [comment]
Sv. tyreotropin /mesh ET tyreotropt hormon, tyreoideastimulerande hormon, sköldkörtelstimulerande hormon
