### ISSUE TITLE
indie popmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6952]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

indie popmusiikki 

#### Ehdotettu termi ruotsiksi   

indiepopmusik 

#### Ehdotettu termi englanniksi   

indie pop music 

#### Vaihtoehtoiset termit ja ilmaisut   

indie pop 

#### Vastaava käsite muussa sanastossa   

LCSH : indie pop music 

#### Tarkoitusta täsmentävä selite   

Määritelmä Wikipediassa: Indie pop (also typeset as indie-pop or indiepop) is a music genre and subculture that combines guitar pop with DIY ethic in opposition to the style and tone of mainstream pop music.  It originated from British post-punk in the late 1970s and subsequently generated a thriving fanzine, label, and club and gig circuit. Compared to its counterpart, indie rock, the genre is more melodic, less abrasive, and relatively angst-free. In later years, the definition of indie pop has bifurcated to also mean bands from unrelated DIY scenes/movements with pop leanings. 

#### Perustelut ehdotukselle   

Tarvitaan sekä YSA/YSO-käsitteeksi, että SLM-sanastoon kuvailemaan indie pop -artistien ja yhtyeiden musiikkia. Tyyliltään eivät ole rockia, joten indie rock -sanan käyttäminen ei ole soveltuvaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://en.wikipedia.org/wiki/List_of_indie_pop_artists 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [indie popmusiikki](http://finto.fi/yse/fi/page/Y506952)

**Comment by tpalonen** [comment]
Jos otetaan sanastoon niin mieluummin muodossa "indie pop". Toisaalta tästä käytetään kotimaassa myös muotoa "indiepop". Ehdotettu "indie popmusiikki" sotii ainakin omaa kielioppikorvaani/-silmääni vastaan ja toisaalta sitä ei käytetä kentällä tuossa muodossa, vaan puhutaan yksinkertaisesti indie popista (tai indiepopista). Google-haulla "indie popmusiikki" ei tule yhtään tarkkaa hakutulosta. Sen sijaan muodot "indie pop" ja "indiepop" ovat laajalti käytössä esim. Ylellä, Rumbassa ja Soundissa.

Yle on jo ottanut oman "indie pop"-asiasanan käyttöön, koska sitä ei ole aiemmin ollut YSOssa/KOKOssa. Aika suosittu asiasana heillä itse asiassa:
https://yle.fi/aihe/termi/yle/18-130745/indie-pop

Yle, Rumba ja Soundi näkyvät käyttävän "indie pop" ja "indiepop" muotoja ristiin toimittajien omista mieltymyksistä riippuen. Tunnen hyvin kenttää (esim. toimittajia) ja voin tarvittaessa järjestää kyselyn yhteen- vs. erikseenkirjoituksesta.

Vrt. indie rock on YSOssa erikseen kirjoitetussa muodossa.

**Comment by JohPa** [comment]
Omaan korvaanikin indie pop  tai indiepop olisi parempi muoto. Syy, miksi laitoin ehdotukseen indie popmusiikki on se, että popmusiikki on YSA -sana ja myös LCSH:ssa sana on pitkässä muodossa ja epäilin, että tästä saattaisi nousta häly :). Mielelläni hyväksyn lyhyemmän muodon, jos se saa kannatusta.

**Comment by asormune** [comment]
Kannatan termiä "indie pop" ; vrt. esim. "garage rock"

**Comment by tpalonen** [comment]
Joukkoistin yhteen vai erikseen -kysymyksen toimittajakentälle. Vastauksia tuli kymmeneltä musiikkiin erikoistuneelta ammattitoimittajalta, jotka kirjoittavat Helsingin Sanomiin / Soundiin / Rumbaan / Aamulehteen, osa heistä lisäksi tietokirjailijoita. Äänet menivät seuraavasti:

indie pop: 1 ääni
indiepop: 9 ääntä

Tällä perusteella suosittelisin käytettäväksi termiksi muotoa **indiepop**.
Myös Kielitoimiston sanakirjan näkemys puoltaa yhteen kirjoittamista: _indie- [indie- t. indi-] yhdyssanan alkuosana: viittaamassa valtavirrasta poikkeaviin, riippumattomiin kulttuuri- tm. suuntauksiin (indierock, indie-elokuva)._

**Comment by YSA-kokous** [comment]
indiepop KT indie pop
indierock KT indie rock

**Comment by mirmaid** [comment]
Määritelmä tulossa vielä.

**Comment by tpalonen** [comment]
Määritelmäehdotus:
"Indierockille läheinen tyylilaji, joka alun perin liittyi punkin myötä syntyneeseen tee se itse -eetokseen ja itsenäisiin levy-yhtiöihin. Äänimaisemaltaan indiepop on indierockiin ja punkiin verrattuna rauhallisempi ja vähemmän aggressiivinen."

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa määritelmää. LT popmusiikki, RT indierock. Myös SLM:ään, jossa indie rock muutetaan yhteenkirjoitettuun muotoon "indierock".

**Comment by mirmaid** [comment]
Ok/SLM

**Comment by mariaforsen** [comment]
Sv. indiepop ET indie, indiepopmusik
