### ISSUE TITLE
konteksti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6953]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[konteksti](http://www.yso.fi/onto/ysa/Y102666) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ryhmä:
50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia 

#### Ehdottajan organisaatio   

SKS 

#### Perustelut ehdotukselle   

Perinneaineistojen kuvailussa käsite 'konteksti' on keskeinen ja paljon käytetty sekä arkisto- että kirjastosektorilla. Myös assosiatiivinen käsite 'kontekstianalyysi' on luultavasti tullut YSAan perinnetieteiden kautta.

**Comment by mirmaid** [comment]
Vai jopa 00? Termiä on käytetty hyvin laajasti eri yhteyksissä.

**Comment by YSA-kokous** [comment]
Lisätään ryhmät
