### ISSUE TITLE
nukketaiteilija

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6954]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nukketaiteilija 

#### Ehdotettu termi englanniksi   

doll artist / dollmaker 

#### Vaihtoehtoiset termit ja ilmaisut   

nukentekijä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-5483-25-3 Eevaliisan nuket 

#### Perustelut ehdotukselle   

Nukketaiteilijoille, nukentekijöille ei ole olemassa kunnon asiasanoja. On vain nuket, nukketeatteri ja taiteilijat. Nukketaiteilija/nukentekijä ei välttämättä liity mitenkään nukketeatteriin. Toisaalta myös nukketeatterin tekijöille pitäisi olla omat asiasanansa. 

**Ehdottajan organisaatio:** Suomen Kirjastopalvelu Oy **Termiehdotus Fintossa:** [nukketaiteilija](http://finto.fi/yse/fi/page/Y506954)

**Comment by jtuohini** [comment]
Ehkä mieluummin muodoksi _nukentekijät_, koska taiteilija-sanalla on aika paljon vaativampi kaiku ja koska tuo ensimmäinen kattaisi arvattavasti paremmin myös esimerkiksi kansankulttuurin piirissä toimivat tekijät jne.
LCSH-vastine: [Dollmakers](http://id.loc.gov/authorities/subjects/sh85038871).

**Comment by ilona-x** [comment]
Melinda: nukentekijät x 3 & nukketaiteilijat x 16

**Comment by YSA-kokous** [comment]
Tutkitaan, seuraava kokous

**Comment by satuniininen** [comment]
_Nukketaiteilijat_ näyttää olevan se termi, jota eniten käytetään, ja se viittaa pääsääntöisesti nimenomaan nukentekijöihin, ei muihin nukkeammatteihin. Jos halutaan varmistaa, ettei sitä käytetä virheellisesti nukketeatterin yhteydessä niin voidaan ottaa molemmat:

nukketaiteilijat (nukentekijät) KT nukketaiteilijat
nukketeatteritaiteilijat KT nukketaiteilijat (nukketeatteri)

**Comment by jtuohini** [comment]
Lisäksi pitää huomata mahdollinen asiasana _nukettajat_, joka terminä löytyy sekä Tieteen termipankista [http://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:nukettaja] että Metatietosanastosta [http://urn.fi/URN:NBN:fi:au:mts:m1476]. Toisin sanoen: mitä ehdotettu toinen asiasana _nukketeatteritaiteilijat_ tarkoittaisi verrattuna tuohon _nukettajat_-sanaan.

**Comment by mirmaid** [comment]
Tieteen termipankki: nukettaja: _Käännöslaina englannin ilmauksesta a puppeteer. Englanninkielinen ilmaus kontekstualisoi tarkoitteensa täsmällisesti – kyseessä on nimenomaan teatterinuken käyttäjä – toisin kuin käännöslaina, jonka ilmaisema merkitys ei ole selvä suurimmalle osalle suomen kielen käyttäjistä. Koska ilmaukset eivät sisällöllisesti vastaa toisiaan, Andrianovin (2015) tutkimuksessa nukettaja-termiä ei käytetä, vaan se on korvattu verbistä to animate (animoida) johdetulla substantiivilla animoija._

**Comment by YSA-kokous** [comment]
Nukketaiteilijat KT nukentekijät

**Comment by mariaforsen** [comment]
Sv. dockkonstnärer ET dockmakare
