### ISSUE TITLE
nimikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6956]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nimikirjat](http://www.yso.fi/onto/ysa/Y123635) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

onko poistettavissa? 

#### Perustelut ehdotukselle   

Sanastossa on matrikkelit= sv. matriklar ja nimikrjat= sv. matriklar. Nimikirjat on käytetty vain vähän ja näköjään virheellisestikin? Eli kirjoista, joissa listataan esim. henkilönimiä yms. Ks. Melinda.

**Comment by mirmaid** [comment]
https://www.finlex.fi/fi/laki/ajantasa/1989/19891010

**Comment by mirmaid** [comment]
Näistä voisi siivota pois hakemistot ja matrikkelit. Jäljelle jää kourallinen viitteitä, joiden ongelma on, että suomeksi niitä nimikirjoja ei nimitetä matrikkeleiksi...

**Comment by ilona-x** [comment]
siivottu Melinda-viitteet, jäljelle jäi 8 viitettä

EKS: 
matrikkelit KÄYTÄ **henkilöhakemistot** sv. personregister
**nimikirja** sv. matrikel

**Comment by mirmaid** [comment]
Ehdotus:
nimikirjat (henkilöstöhallinto)
matriklar (personaladministration) 
matriklar (personregister) (=matrikkelit)

**Comment by mirmaid** [comment]
_Matrikkelit_ on lähes poikkeuksetta tietueessa lajityyppitermi, joten EKS:n ratkaisu toimisi varmaan YSAssakin. _Nimikirjat_ ei toki aineiston vähäisen määrän takia ole välttämätön termi.  

Poistetaan _nimikirjat_, siirretään termi tietueissa 653-kenttään ja jatketaan _matrikkelit_-termin käsittelyä syksyllä?

**Comment by YSA-kokous** [comment]
Poistetaan nimikirjat, siirretään termi tietueissa 653-kenttään ja jatketaan matrikkelit-termin käsittelyä syksyllä.

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7600

**Comment by mirmaid** [comment]
YSOssa nyt siis _matrikkelit_ ja _henkilöhakemistot_, SLM:ssä _matrikkelit_.

Vastaavasti EKS:ssa _henkilöhakemistot_ KT matrikkelit, sekä _nimikirja_.

Nimikirja-asetuksen https://www.finlex.fi/fi/laki/ajantasa/1989/19891322 mukaisista nimikirjoista ei (käsittääkseni) suomeksi käytetä nimitystä matrikkeli, mutta ruotsiksi ne ovat matriklar. _Nimikirjat_-käsite poistettiin YSOsta tämän kieliongelman ja aineiston vähäisen määrän takia. Onko tarpeen pitää YSOssa sekä _matrikkelit_ että _henkilöhakemistot_? SLM:ssä _matrikkelit_ on varmaankin ok.

Myös YSO-käsitettä _matrikkelit_ on käytetty ennen kaikkea muototerminä, mutta Melindassa on myös aineistoa, jossa matrikkelit on aiheena (esimerkiksi historiantutkimuksen lähteistä tai matrikkelin laadinnasta kertovat julkaisut). Onko tällöin tarpeellinen erillään vai meneekö sekaisin _henkilöhakemistot_-käsitteen kanssa?

**Comment by YSO-kokous** [comment]
Päätös: Ei muutoksia matrikkelit-käsitteeseen.
