### ISSUE TITLE
sukupuolisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6957]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sukupuolisuus](http://www.yso.fi/onto/ysa/Y164217) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko yhdistettävissä (seksuaalisuus)? 

#### Perustelut ehdotukselle   

sukupuolisuus = sv. sexualitet, seksuaalisuus= sv. sexualitet Onko käyttö Melindassa johdonmukainen? Ellei ole yhdistettävissä niin onko mahdollista määrittää seksuaalisuus huomautuksella? Ks. Motin sanakirjat (käsitellään lähinnä synonymisina)

**Comment by YSA-kokous** [comment]
sukupuolen moninaisuus?

**Comment by mirmaid** [comment]
_Sukupuolen moninaisuus_ kerran Melindassa. 

Onko muutettavissa: sukupuolisuus > _sukupuolen moninaisuus, sukupuoli-identiteetti, sukupuoliroolit, sukupuolivähemmistöt_ tai _sukupuoli_?

**Comment by YSA-kokous** [comment]
sukupuolen moninaisuus
poistetaan sukupuolisuus (KÄ sukupuoli-identiteetti, sukupuoli, sukupuolen moninaisuus)

**Comment by mariaforsen** [comment]
Sv. könsmångfald ET mångfald av kön
