### ISSUE TITLE
peseytymistilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6959]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[peseytymistilat](http://www.yso.fi/onto/ysa/Y98097) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko yhdistettävissä (pesutilat)? 

#### Perustelut ehdotukselle   

Pesutilat + peseytymistilat = tvättrum. Allfossa on aikaisemmin ratkaistu: tvättrum (personhygien), tvättrum (rengöring). Melindassa näyttää kuitenkin olevan käytetty sekalaisesti ja molemmat kylpyhuoneista yms.

**Comment by mirmaid** [comment]
On varmaan yhdistettävissä?

**Comment by ilona-x** [comment]
Melinda: pesutilat x 224 & peseytymistilat x 355

YSAssa nyt: pesutuvat KÄYTÄ pesutilat, jos yhdistetään niin pitäisikö ottaa erikseen pesutuvat?

Melindassa joitakin viitteitä: 
- Miten taltuttaa pesutuvan väärinkäyttäjä?.
- Energiatehokas ja nopea pyykinkuivaus parantaa pesutuvan käyttöastetta.

ehdotus: 
pesutilat KÄYTÄ **peseytymistilat**
pesutilat KÄYTÄ **pesutuvat**

tai jos ei haluta erikseen pesutupia niin sitten
peseytymistilat KÄYTÄ pesutilat
pesutuvat KÄYTÄ pesutilat

**Comment by YSA-kokous** [comment]
pesutilat
pesutuvat jos näyttää olevan tarpeen
