### ISSUE TITLE
televisiomusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6960]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[televisiomusiikki](http://www.yso.fi/onto/ysa/Y214692) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Tarvitaan televisiomusiikkia sisältävien nuottien ja äänitteiden kuvailuun. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. YSAan RT tuotantomusiikki.

**Comment by mirmaid** [comment]
Ok/SLM
