### ISSUE TITLE
pienpainatteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6962]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pienpainatteet](http://www.yso.fi/onto/ysa/Y101970) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan pienpainatteiden kuvailuun 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. småtryck

**Comment by mirmaid** [comment]
Mahdollisesti hierarkisoiva yläkäsite.

**Comment by AuHo22** [comment]
Tarvitaanko siis hierarkisoivat yläkäsitteet pienpainatteet, kuva/-t/kuva-aineisto ja esineet? 

Esim. https://www.kansalliskirjasto.fi/fi/kokoelmat/kansalliskokoelman-pienpainatekokoelma

Marc21-formaatin kuvailu tietueen tyypistä, jolla siis erotellaan erityyppisiä aineistoja (06 nimiössä):
k - Kuva
Sisältää esimerkiksi kaaviot, kollaasit, tietokonegrafiikat, piirrokset, kopioiden alkuperäiskappaleet, sana- tai kuvakortit, maalaukset, valokuvanegatiivit, valokuvat, kuvat, valokuva-CD:t, postikortit, julisteet, tulosteet, opintomonisteet, tekniset piirustukset, valokuvajäljitelmät, ja kopiot tai jäljitelmät kaikista edellä mainituista.
r - Esine
Sisältää keinotekoiset esineet kuten mallit, dioraamat, pelit ja palapelit, simulaatiot, veistokset ja muut kolmiulotteiset taideteokset ja niiden jäljennökset, näyttelyesineet, koneet, vaatteet, lelut ja käsityöt, sekä luonnolliset kappaleet kuten mikroskooppipreparaatit.

**Comment by AuHo22** [comment]
Kirjastoissa esinetason kuvailua lähinnä  nidetiedoissa eli kappaleita kuvailtaessa, ei liene siis sovi hierarkisoivaksi käsitteeksi eikä ole tarpeellinen (?)

**Comment by AuHo22** [comment]
Kumean tarkennus: https://wiki.helsinki.fi/display/rdasovellusohje/Pelit#Pelit-Tallennetyyppi

Fyysiset pelit (lautapelit, korttipelit), kuvaillaan esineinä (VM, tietueen nimiö 000/06 = r).

Kortit: onko kyseessä esine vai kuva?
Jos korteilla pelataan, eikä mukana ole pelilautaa, kyseessä on korttipeli (000/06=r).
Jos kortteja ei käytetä pelaamiseen, kyseessä on kuva (000/06=k).
