### ISSUE TITLE
toisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6963]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toisto](http://www.yso.fi/onto/ysa/Y111861) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaanko määritelmä? 

#### Perustelut ehdotukselle   

Melindassa toisto on virheellisesti käytetty myös esim. äänentoistosta. Se ei ainakaan täsmää ruotsin osalta (upprepning) ja sillehän on oma terminsä.

**Comment by satuniininen** [comment]
Ainakin sanastossa jo olemassaoleville, tarkemmille käsitteille voisi lisätä ohjaustermejä esim:
toisto (äänen) KÄ äänentoisto
toisto (kuvantoisto) KÄ kuvantoisto
toisto (suoratoisto) KÄ suoratoisto

Myös määritelmä toki mahdollinen, mutta yleiskäsitteille niitä on usein tuskaisen hankala muotoilla.

**Comment by mirmaid** [comment]
Jos lisäisi yllä ehdotetut ohjaustermit ja _toistoon_ myös esim. ohjaustermit _toisto (kertaus)_, _toisto (uusiminen)_? Jonkin verran virheellistä käyttöä, mutta hyvän sulkutarkenteen löytäminen päätermille vähän hankalaa koska sitä on kuitenkin mahdollista käyttää hyvin erilaisissa yhteyksissä.
