### ISSUE TITLE
todistukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6964]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[todistukset](http://www.yso.fi/onto/ysa/Y112373) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista rajata tarkemmin tai esim. lisätä koulutodistukset (skolbetyg) uutena terminä? 

#### Perustelut ehdotukselle   

Allärs: betyg + intyg = todistukset.

**Comment by satuniininen** [comment]
Koulutodistukset olisivat hyvä lisä myös en-vastineiden kannalta.

**Comment by mirmaid** [comment]
Voidaan lisätä, mutta jos _todistukset_-termiä ei saa käyttää niistä se tarvitsee tarkenteen.

**Comment by ilona-x** [comment]
todistukset-termiä käytetty Melindassa monenlaisista todistuksista, joten ruotsi-vastineita taitaa olla enemmän kuin nuo kaksi, tässä muutamia esimerkkejä:

- Proofs from the book (todistukset + matematiikka)
- From findings to statistics (kuolemansyyt + todistukset)
- Taloyhtiön kuntotodistus tulossa pilottikäyttöön
- Uusi veroilmoitus vaatii tarkkuutta 
- Tarkista taideteoksen taustatiedot (aitous + todistukset)
- Sanna vittnesmål och mänskliga ord (filosofia + todistajat + todistukset)
- Asiantuntijatodistelun ongelmakohtia  (oikeudenkäynti + todistukset) YSA:ssa on **todistelu**
- Valtuutetun taloudellisen toimijan sudenkuopat : AEO-itsearviointi esimerkkiyrityksessä  (AEO-todistus)

http://www.tsk.fi/tepa/fi/haku/todistus
https://tieteentermipankki.fi/wiki/Kasvatustieteet:todistukset
https://tieteentermipankki.fi/wiki/Filosofia:todistus

liittyviä YSA-termejä:
**sertifikaatit** http://www.yso.fi/onto/ysa/Y118940
**päättötodistukset** http://www.yso.fi/onto/ysa/Y164203
lisäksi todistukset-käsitteellä paljon alakäsitteitä: http://www.yso.fi/onto/ysa/Y112373

Voisiko yksi mahdollisuus poistaa "todistukset" ja ottaa tilalle tarvittavat tarkemmat termit ja ohjata osassa tapauksista käyttämään muita sanastossa jo olevia käsitteitä, vai tulisiko tarkkoja termejä liikaa?

Tässä ehdotuksia mahdollisista lisäyksistä Melindan perusteella:

- **papintodistukset** https://fi.wikipedia.org/wiki/Papintodistus YSAssa on henkilötodistukset + virkatodistukset
- **pätevyystodistukset tai todistukset (pätevyyden)** (erilaiset ammatilliset ym. pätevyydet, YSAssa on pätevyys)
- **koulutodistukset**? (miten toimii eri kouluasteilla, peruskoulu, lukio, ammatillinen koulutus jne.)
- **tutkintotodistukset** YSAssa on tutkinnot
- **matemaattinen todistus?** https://fi.wikipedia.org/wiki/Matemaattinen_todistus

**Comment by ilona-x** [comment]
Melindassa osumia 73+ketjut:
34/73 **koulutodistukset**
6/73 **tutkintotodistukset**
4/73 kuolemansyyt + todistukset (YSAssa on kuolintodistukset, mutta onko sama asia)
3/73 matemaattinen todistus
2/73 matkailu + lääkkeet + todistukset
1/73 papintodistus
1/73 mainetodistus https://fi.wikipedia.org/wiki/Mainetodistus

sekalaisia:
- Ennen oli erilaista: pari asiapaperinäytettä siitä.
- Passi huippusalaisille maailman markkinoille on uusi laki kansainvälisistä tietoturvallisuusvelvoitteista.
- Europassilla osaaminen näkyväksi.
- Saksan malli: nuorisotyön vapaaehtoisille rakannettiin ohjaajakortti.
- Vesilaitosten työntekijöiltä vaaditaan pian pätevyystodistus.
- Ergonominen potilassiirto.
- Kansainvälinen laskuvarjohyppääjän todistus.
- Venekaupan paperisota.
jne.

**Comment by YSA-kokous** [comment]
koulutodistukset
poistetaan todistukset
mahdollisesti vielä muuta, seuraava kokous

**Comment by mirmaid** [comment]
Pitikö ottaa myös _tutkintotodistukset_?

**Comment by ilona-x** [comment]
Mielestäni oli tarkoitus ottaa myös tutkintotodistukset.

**Comment by ilona-x** [comment]
Siivottu Melindasta koulutodistukset ja tutkintotodistukset, jäljelle jäi reilu 20 viitettä, joista pari käsittelee matemaattista todistusta.

Olisiko mahdollista ottaa erikseen **todistukset (todistavat asiakirjat)**, joka voisi olla yläkäsitteenä näille muille todistuksille? https://fi.wikipedia.org/wiki/Todistus

Tai jos päätetään poistaa todistukset niin sitten voisi olla tarpeen esimerkiksi pätevyystodistukset.

**Comment by LeKorsu** [comment]
Eikö "todistukset (asiakirjat)" riitä todistavien asiakirjojen sijasta?
Todistukset (tuomioistuimet tai oikeus) KÄ todistajanlausunnot [näitä ei tainnut olla Melinda-aineistossa]
Entä tarvitaanko edelleen päättötodistukset, jos on uutena koulutodistukset ja tutkintotodistukset? Melindassa 6 viitettä päättötodistuksella.

**Comment by YSA-kokous** [comment]
todistukset (asiakirjat)
todistukset (koulu) KÄ koulutodistukset
