### ISSUE TITLE
sulhaset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6965]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sulhaset](http://www.yso.fi/onto/ysa/Y123627) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelläänkö? 

#### Perustelut ehdotukselle   

Viittaako vain tähän: "häissä myös juuri vihitty mies, sulhasmies" (=brudgum)? Ks. MOT: "myös kihloissa oleva mies vars. kihlattunsa kannalta" (=fästman) 

Allärs: brudgummar + fästmän

**Comment by mariaforsen** [comment]
Samanlainen tapaus: morsiamet ("kihlattu nainen; häissä myös juuri vihitty nainen")

**Comment by mirmaid** [comment]
Käytetty molemmissa merkityksissä varsinkin naisista, mutta varmaankin korvattavissa muilla termeillä (?), jos halutaan rajata hääjuhlaan.

**Comment by mirmaid** [comment]
Ainakin osittain muuhun kuin häihin liittyviä _morsiamet_-termin käyttötapauksia:

_Hindunaisen osa on paha 
Mail order brides in modern America : a critical analysis of trafficked brides in public perception
Vulnerability and the art of protection : embodiment and health care in Moroccan households
Hellien tunteiden kirja_ (Plutarkhos) (?)
_Morsiuslahja : wälttämättömän tarpeellisia neuvoja vastanaineille ja naimisiin aikoville naisille
Lapsensynnyttäjien ja morsianten kirkkoonotto_

**Comment by mirmaid** [comment]
Jos termimuoto olisi _morsiamet (häät)_, sopisiko tämä myös kun kyse on perinteestä joka ei suoranaisesti liity hääjuhlaan (esim. myötäjäiset, neitsyys)?

**Comment by krinay** [comment]
Perinnetieteellisissä tutkimuksissa tarkastellaan usein/useimmiten morsiamia sekä kihlausaikana että hääjuhlassa: naisen asemaa, rooleja ja tehtäviä, rituaaleja jne. Jos siis halutaan ottaa termi _morsiamet (häät)_, tarvittaisiin toinen termi kihlatulle.

**Comment by YSA-kokous** [comment]
Yhdistetään ruotsiksi
