### ISSUE TITLE
aleutit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6966]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[aleutit](http://www.yso.fi/onto/ysa/Y176369) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

aleutit (kansa) 

#### Perustelut ehdotukselle   

On olemassa myös Aleutit (saaristo)
-> laitettu ehdotukseksi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
_Aleutit (saaristo)_ on lisätty YSAan. Maantieteellisenä nimenä Aleutit on myös vuoristo, tosin samaa geologista muodostumaa kuin saaristo, joten en osaa sanoa onko tarkenne miten tarpeellinen. Kansa ja saaristo ovat siis jatkossa eri sanastoissa ja toinen kirjoitetaan isolla, tarvitaanko tarkenne?

**Comment by YSA-kokous** [comment]
aleutit (kansat)
