### ISSUE TITLE
ratkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6968]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ratkaisut](http://www.yso.fi/onto/ysa/Y104143) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ratkaisut (päätökset), ratkaisut (ongelmat) tms. jako...? Ellei tarkempi määritelmä riitä? 

#### Perustelut ehdotukselle   

Allärs: avgöranden + lösningar (problem).
Ks. Kielitoimiston sanakirja.
Käytetty Melindassa eri merkityksissä.

**Comment by satuniininen** [comment]
_Ratkaisut (päätökset)_ kuulostaa selkeältä, mutta toinen merkitys on hankala. 

Melindassa _ratkaisut_ ovat hyvin monenkirjava joukko. Erilaisten tehtävien/yhtälöiden/harjoitusten ratkaisut ovat selkeä ja sinänsä konkreettinen setti. Lisäksi on kuitenkin paljon muuta esim. ratkaisuja erilaisiin (yhteiskunnan/työelämän/arjen) haasteisiin.  Näille kaikille on hankalaa keksiä yhdistävää sulkutarkennetta, joskin osassa tietueista _ratkaisut_ on joko korvattavissa muulla käsitteistöllä kuten _ongelmanratkaisu, konfliktinratkaisu_, joissain tapauksissa myös _sovellukset (käyttötavat)_. Paljon myös erilaisia myynti-, palvelu- ja markkinointiratkaisuja, mutta näissä _ratkaisut_ voinee pudottaa kokonaan pois.

Ehdottaisin sulkutarkenteeksi jotain seuraavista:

- ratkaisut (vastaukset)
- ratkaisut (ongelmanratkaisut)
- ratkaisut (lopputulokset) [meneekö sekaisin _ratkaisut (päätökset)_ kanssa?]

**Comment by mirmaid** [comment]
Kuinkahan usein myös tapauksissa ratkaisut (päätökset) riittäisi _päätökset_?

**Comment by ilona-x** [comment]
EKS: 
tuomiot KT päätös, tuomioistuimen ratkaisu

**Comment by YSA-kokous** [comment]
Tutkitaan vielä, tarvitaanko _ratkaisut_-termiä, tai ainakaan molempia merkityksiä.

**Comment by satuniininen** [comment]
EKS:n tulkinnan perusteella _päätökset_ ja _ratkaisut (päätökset)_ vaikuttavat hyvin päällekkäisiltä. 
YSOlla kuvailtava aineisto on kuitenkin EKS:ää laaja-alaisempaa, joten käsitteen olisi hyvä kattaa muutkin kuin tuomioistuinten tekemät ratkaisut, jolloin _tuomiot_ ei sovi käytettäväksi termiksi.
esim:
_Johdannaissopimusten tarkastamista koskevat TILA:n ratkaisut_ [TILA = Tilintarkastuslautakunta]
_Harkittua? : avauksia sosiaaliturvan harkintavallan tutkimukseen_ [= ratkaisut sosiaalietuuden myöntämisestä]

Toisaalta päätökset ei sopisi aineistoon _Vertaissovittelu sovittelijan silmin : kokemuksia ja näkemyksiä vertaissovittelijana toimimisesta peruskoulussa_, joskin tähän _ratkaisut (päätökset)_ sopii ihan yhtä huonosti. Tietueessa on jo _sovittelu, vaihtoehtoinen riidanratkaisu_ ja paljon muuta.

Kannatan muotoa **päätökset KT ratkaisut (päätökset)**

**Comment by mariaforsen** [comment]
Sv. 
avgöranden ANV beslut
lösningar (svar)

**Comment by YSA-kokous** [comment]
ratkaisut (päätökset) KÄ päätökset
ratkaisut (vastaukset)
