### ISSUE TITLE
elektroninen tanssimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6969]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elektroninen tanssimusiikki](http://www.yso.fi/onto/ysa/Y214456) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan EDM-äänitteiden ja nuottien kuvailuun. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin lisäämistä SLM:ään. KT elektroninen musiikki (sekä YSAan että SLM:ään).

**Comment by mirmaid** [comment]
Ok/SLM
