### ISSUE TITLE
hengellinen viihdemusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6970]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hengellinen viihdemusiikki](http://www.yso.fi/onto/ysa/Y214493) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Tarvitaan hengellisen viihdemusiikin äänitteiden ja nuottien kuvailuun. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin lisäämistä SLM:ään. Suhteet YSAsta.

**Comment by mirmaid** [comment]
Ok/SLM

**Comment by mirmaid** [comment]
LCSH-vastine YSOssa http://id.loc.gov/authorities/subjects/sh86002542, samoin termillä ylistysmusiikki. SLM:n osalta saatiin palautetta, että vastine ei sovi ainakaan ExactMatchiksi hengelliselle viihdemusiikille (ei kuulosta kyllä että sopisi myöskään ylistysmusiikille). Millä tarkkuudella vastineita halutaan antaa SLM:ssä?

**Comment by jtuohini** [comment]
Muusan kokous 4.10.2019: emme ota kantaa asiaan tässä vaiheessa.

**Comment by mirmaid** [comment]
Viime kokouksessa sovittu: _tässä vaiheessa tehdään exactMatchejä, käsitellään kokouksessa muunlaiset siltausehdotukset ja luodaan niiden myötä linjaukset_

**Comment by mirmaid** [comment]
Ei linkitystä.
