### ISSUE TITLE
kausijulkaisu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6971]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kausijulkaisu 

#### Perustelut ehdotukselle   

Ehdotus koskee slm-sanastoa. Kausijulkaisut-termi löytyy Ysasta, mutta ei slm:stä. Pitäisikö olla lajityyppi/genre vai onko tarkoituksella jätetty pois? (ehdotuksesta puuttuu t-koska lomake ei mene läpi monikkomuotoisena) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kausijulkaisujen 

**Ehdottajan organisaatio:** Oamk **Termiehdotus Fintossa:** [kausijulkaisu](http://finto.fi/yse/fi/page/Y506971)

**Comment by jtuohini** [comment]
Tästä on jo tehty YSE (https://github.com/Finto-ehdotus/YSE/issues/6955)!
