### ISSUE TITLE
soveltava sosiaalipsykologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6972]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soveltava sosiaalipsykologia 

#### Ehdotettu termi englanniksi   

applied social psychology 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sosiaalipsykologia](http://www.yso.fi/onto/yso/p19035) 

#### Alakäsitteet (RT)   

[soveltavat tieteet](http://www.yso.fi/onto/yso/p5075) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

Soveltava sosiaalipsykologia -vapaata asiasanaa on käytetty Melindassa useasti. Tarvittu myös tämän kirjan sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/JGKA24A7YS2RDLTF8Q9LJ2G8JUYV8X4ULFC6BP22E85VNIM41X-00339?func=full-set-set&set_number=010739&set_entry=000001&format=999 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [soveltava sosiaalipsykologia](http://finto.fi/yse/fi/page/Y506972)

**Comment by tarjaturunen** [comment]
Tälle YSO termille edelleen tarvetta.

**Comment by mariaforsen** [comment]
Sv. tillämpad socialpsykologi

**Comment by mirmaid** [comment]
Google-viitteet joko: https://www.booky.fi/tuote/jukka_valkonen/kuntoutus_tarinat_ja_soveltava_sosiaalipsykologia/9789525017403 tai joitakin Tampereen yliopiston kursseja.

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

**Comment by mirmaid** [comment]
_Applied Social Psychology combines the science of social psychology with the practical application of solving social problems that exist in the real world._ https://www.cambridge.org/highereducation/books/applied-social-psychology/C5C0D45ED30EE4549AF74DAC7C60A136

**Comment by mirmaid** [comment]
Sanastossa on _soveltava antropologia, soveltava kielitiede_ ja _soveltava psykologia_. 

Ks. myös https://github.com/Finto-ehdotus/YSE/issues/7843

**Comment by YSO-kokous** [comment]
Ei saanut kannatusta eli ei oteta toistaiseksi YSOon.

**Comment by tarjaturunen** [comment]
Ehdotan edelleen, että soveltava sosiaalipsykologia lisättäisiin YSOon koska 1) siellä on jo aiemmin hyväksyttynä soveltava antropologia, soveltava kielitiede ja soveltava psykologia, 2) termiä tarvitaan sisällönkuvailussa, 3) suomenkielisen käsitteen/termin vakiinnuttamiseksi. Kysymys: millainen kannatus edellytetään olevan ehdotetulla YSO termillä, että se hyväksytään YSOon? Voisiko YSO ehdotusten kannattamismahdollisuutta laajentaa myös kuvailun tekijöiden suuntaan?

**Comment by mirmaid** [comment]
Edelliseen kommenttina, tänne ehdotusjärjestelmään ovat tervetulleita kaikki kiinnostuneet kannattamaan kommentein ja peukuin ehdotuksia. Kokouksissa päätökset tehdään osallistujien enemmistön kannan mukaan; suurin osa YSO-sanastokokouksen tiimistä tekee sisällönkuvailua jossakin kirjastossa tai muussa organisaatiossa. 

Näissä "soveltava/sovellettu tiede x" -yhdistelmissä on pohdituttanut se, millainen ero oikeastaan on kyseessä päätieteenalaan, ts. miten soveltava sosiaalipsykologia eroaa pelkästä sosiaalipsykologiasta, kun käyttö ei vaikuta olevan kovin laajaa eikä selkeitä erottelevia määritelmiä löydy. Jos soveltava sosiaalipsykologia pyrkii ratkomaan "todellisia ongelmia", voidaanko kuitenkaan sanoa, ettei pelkkä sosiaalipsykologiakin pyrkisi usein samaan?

Alkuperäisen ehdotuksen aineistolinkki ei toimi, mutta toki linkit erotteleviin määritelmiin tai aineistoihin, joiden kuvailussa termiä tarvitaan auttavat jatkokäsittelyssä.

**Comment by tarjaturunen** [comment]
Onko tämä termiehdotus hyväksytty?
Tarvetta tälle asiasanalle on. 
https://melinda.kansalliskirjasto.fi/byid/017639926
