### ISSUE TITLE
perhe

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6973]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[perhe](http://www.yso.fi/onto/ysa/Y98048) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään perhe ja perheet, ja ohjataan perhe KÄ perheet TAI perheet KÄ perhe 

#### Perustelut ehdotukselle   

Käsitteet ovat merkitykseltään lähekkäisiä ja niitä käytetään kuvailussa usein päällekkäin. YSOssa käytössä sulkutarkenteet perhe (ilmiöt) ja perheet (ryhmät).

Melindassa perhe 6723 kertaa ja perheet 7693.

Yksiköllinen muoto sopisi monikollista paremmin silloin, kun aiheena on esim. työn ja perheen yhdistäminen (joskin näitä tapauksia varten on myös perhe-elämä) tai perhe yhteiskunnallis-historiallisena instituutiona (esim. Suomessa selviytymisen historiaa : kivikaudelta keskiajalle ja 1900-luvun alkuun / Ulla Koskinen.)

Monikollista puoltaa se, että myös eri perhetyyppien käsitteistö on monikossa (sateenkaariperheet, lapsiperheet jne.) Myös suvut monikossa. LCSH:ssa vain monikko. 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Jos valitaan monikko, voisi miettiä _perhe-elämä_-termin lisäämistä tietueisiin joissakin tapauksissa (esim. jos työ ja perhe ovat peräkkäisinä asiasanoina tietueessa?).

**Comment by YSA-kokous** [comment]
perhe KÄ perheet
