### ISSUE TITLE
pientareet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6975]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pientareet](http://www.yso.fi/onto/ysa/Y140829) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko jaettavissa tarkempiin: ojan-, pellon-, tienpientareet? 

#### Perustelut ehdotukselle   

Allärs: dikesrenar, vägrenar, åkerrenar.
Kai nämä ovat kuitenkin tavallaan eri käsitteitä ja hakija joka on kiinnostunut tienpientareista ei välttämättä ole kiinnostunut ojan tai pellon pientareista (yleensä eivät liity toisiinsa).

**Comment by mirmaid** [comment]
Onko ruotsiksi ongelmallista yhdistää renar + tarkenne? Jakokin onnistuu kyllä. Aika usein näitä käsitellään aineistoissa biotooppeina, myös samoissa aineistoissa sekä tien- että pellonpientareet hyönteisten elinympäristöinä tms.

**Comment by mariaforsen** [comment]
On  nimenomaan hieman ongelmallista, yleensä ei voi käyttää pelkkä "renar" tässä merkityksessä (vaikka se periaatteessa on olemassa), vaan aina yhdistettynä esim. väg-, åker- jne. Joten käyttäjä varmaan ihmettelee mihin tämä "renar (områden)" viittaa, esim. porojen alueita? Ks. esim. Nationalencyklopedin: "(vanl. i sms.) kant vid väg eller åker e.d." Toinen mahdollinen ratkaisu voisi olla "dikesrenar, vägrenar och åkerrenar" (vain hätätapauksessa)

**Comment by mirmaid** [comment]
Ja _renskötselområden_ on sekin jo olemassa :smile:

**Comment by YSA-kokous** [comment]
tienpientareet
pellonpientareet
jos tarpeen, ojanpientareet
