### ISSUE TITLE
perintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6976]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[perintä](http://www.yso.fi/onto/ysa/Y104739) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko jaettavissa? Esim. perintä (maksut ja verot), perintä (velat) 

#### Perustelut ehdotukselle   

Allärs: indrivning + uppbörd
Ruotsiksi eri termit riippuen merkityksestä (pakkokeinona indrivning, mutta uppbörd jos on kyse tavallisesta maksujen perimisestä tai verojen)
Vrt. https://fi.wikipedia.org/wiki/Perint%C3%A4

**Comment by mirmaid** [comment]
EKS: perintä = indrivning
Wikipedia: inkasso, perintätoimistot Allärsissa _inkassobyråer_

**Comment by ilona-x** [comment]
SAO:
- indrivning 
- uppbörd se Skatteuppbörd

YSAssa **veronkanto** sv. skatteuppbörd
verotukseen liittyen YSAssa on myös **ennakkoperintä** sv. förskottsuppbörd

Jäin vielä miettimään, mitä tarkoittaa "tavallinen maksujen perintä"? Onko kyseessä kuitenkin indrivning, jos esim. perintätoimisto perii maksamatonta lehtitilausmaksua?

JUPO: **saatavien perintä** http://www.yso.fi/onto/jupo/p935

Melinda: 
uppbörd x 20
indrivning x 71
uppbörd & indrivning x 12

Lag om säkerställande av indrivningen av skatter och avgifter https://finlex.fi/sv/laki/ajantasa/1973/19730395
Eli silloin kun veroja peritään ulosoton kautta on kyseessä indrivning?

**Comment by mariaforsen** [comment]
Näin on, pakkokeinoa indrivning eli jos jotain on jäänyt maksamatta. Uppbörd jos vain peritään maksua normaalisti (ei ole maksamattomia laskuja yms.)

**Comment by ilona-x** [comment]
OK, nyt selkiytyi minulle nuo merkitykset.

Kävin läpi 100 Melinda-viitettä ja niistä vain muutamassa ei ollut aiheena saatavien perintä (indrivning)
Tässä listaa:

- Tienkäyttömaksujärjestelmät :esiselvitys
- Ennakonpidätys 2008 
- EU-vero-oikeus :välitön verotus  (näitä EU-verotus teoksia oli useampia, mutta näistä vaikea sanoa, mistä perinnästä kyse)
- Valtiontuet 

Lisäksi katsoin läpi nuo Melinda-viitteet joissa käytetty Allärs-termiä uppbörd mutta ei termiä indrivning:

1. Perintälain muutokset ja niiden vaikutukset OK-Perintä Oy:n liiketoimintaan / Heli Leikkola.
2. Perintälain muutosten vaikutukset / Wasima Muhebullah.
3. Yksityishenkilön luotonanto- ja perintäprosessin hoito Haminan seudun osuuspankissa / Jaana Pousi.
4. Pakkokeinot ja saatavien perintä / Essi Rikalainen, Tero Uitto.
5. Verosaatavien perinnän tehokkuus.
6. Kirjanpidon, perinnän ja markkinoinnin kehitysnäkökulmia : case: Yksityinen hammaslääkäriasema / Taimi Syrjäkari.
7. Verosaatavien perintä.

Vaikuttaisi siltä, että muissa paitsi nro 7 pitäisi olla ennemminkin indrivning.

Eli pärjättäisiinkö vain yhdellä perintä-termillä, jonka ruotsivastine olisi indrivning?
Ja suomeksi muodoksi ehkä **saatavien perintä**?

**Comment by YSA-kokous** [comment]
saatavien perintä
