### ISSUE TITLE
jnanajooga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6979]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jnanajooga 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jnana yoga: the path of knowledge 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [jnanajooga](http://finto.fi/yse/fi/page/Y506979)

**Comment by ilona-x** [comment]
LCSH: Yoga, Jñāna http://id.loc.gov/authorities/subjects/sh85149180

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Jnana_yoga

**Comment by mariaforsen** [comment]
Sv. jnanayoga ET jnana yoga
