### ISSUE TITLE
raja-arvot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6980]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[raja-arvot](http://www.yso.fi/onto/ysa/Y104122) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteille _raja-arvo_ ja _raja-arvot_ tarvitaan sulkutarkenteet. Käsitteitä on vaikea erottaa toisistaan ja ne viittaavat täysin eri asioihin.

Esimerkiksi **raja-arvot (työsuojelu)** ja **raja-arvo (matematiikka)** 

#### Perustelut ehdotukselle   

Tällä hetkellä merkitysero ilmenee vain temaattisesta ryhmästä ja suhteista muihin käsitteisiin:
raja-arvo 04 Matematiikka. Tilastotiede
raja-arvot 00 Yleistermit

MOTin mukaan merkitykset ovat
a. työsuojelussa. Työhygieeninen raja-arvo melun, kemiallisen altistuksen tms. suurin sallittu arvo.
b. mat. suure jota toinen, muuttuva suure lähenee rajattomasti. 

Mot siis määrittää monikollisen olevan työsuojelun käsite, mutta Melindassa sitä on käytetty myös muissa merkityksissä, esim. teokset _Savustettujen liha- ja kalatuotteiden PAH-pitoisuusvaatimukset kiristyvät_ ja _3 naista, sama BMI : kuka on tervein?_. Näissä oikeampi käsite olisi ehkä _enimmäispitoisuudet_ tai _viitearvot_. 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Tarkenne _(matematiikka)_ on hyvä yksikölle, monikolle ehdottaisin jotain sen tyyppistä kuin _(rajoitukset)_. _Raja-arvot, viitearvot, ohjearvot_ on kyllä hankala kokonaisuus.

**Comment by YSA-kokous** [comment]
raja-arvo (matematiikka)
raja-arvot (rajoitukset)
