### ISSUE TITLE
risti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6981]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[risti](http://www.yso.fi/onto/ysa/Y113202) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteet _risti_ ja _ristit_ on joko yhdistettävä tai erotettava toisistaan sulkutarkenteella/termimuutoksella. 

Ysossa risti (symbolit) ja ristit (objektit) 

#### Perustelut ehdotukselle   

Tällä hetkellä kuvailu on Melindassa hyvin sekalaista. Yksiköllistä ristiä on käytetty runsaasti myös objektimaisten ristien kuvailuun, etenkin silloin, kun kyseessä on vain yksi esim. tietyn nimetyn kirkon risti. Myös useita kuvailuja, joissa aiheena ruoka-aineallergiat. 

Tarvitaanko yksiköllistä _ristiä_ omana käsitteenään teologisen aineiston kuvailussa? Jos tarvitaan, niin mitä kaikkea sen tulisi kattaa? Osassa aineistoa _ristin_ voisi korvata ottamalla sanastoon _ristin teologian_, mutta se tuskin kattaa kaikkia tapauksia. YSOn sulkutarkenteet auttavat hahmottamaan käsitteiden välistä eroa, mutta rajanveto voi olla hankalaa, sillä toki konkreettinenkin risti on esineen lisäksi myös symboli. 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Lääketieteen termit: **ristiallergia**: _allergia jonka oireet laukaisee varsinaisen allergeenin lisäksi jokin muu allergeeni, esim. koivuallergikon raa´an porkkanan syömisestä saamat oireet_ 

FinMeSH: KÄ _ristireaktiot_

**Comment by mirmaid** [comment]
Tässä vielä yksi mahdollisuus: https://fi.wikipedia.org/wiki/Kristinuskon_risti

**Comment by YSA-kokous** [comment]
ristireaktiot
risti KÄ ristit
