### ISSUE TITLE
fysioterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6983]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fysioterapia](http://www.yso.fi/onto/ysa/Y101400) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "lääkitysvoimistelu" 

#### Perustelut ehdotukselle   

Fysioterapian aiempi suomenkielinen nimitys oli lääkitysvoimistelu, joka olisi syytä saada viittausmuodoksi varsinkin vanhemman aineiston kuvailua helpottamaan. 

#### Ehdottajan organisaatio   

he

**Comment by LeKorsu** [comment]
Onko tämä lääkitysvoimistelu sama kuin lääkintävoimistelu, joka on sanastossa fysikaalisen hoidon alla, joka puolestaan on fysioterapian alakäsite? Vai tarkoittavatko (ovatko tarkoittaneet) lääkintävoimistelu ja lääkitysvoimistelu todellakin eri asiaa?

**Comment by YSA-kokous** [comment]
Tutkitaan.

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja: 
lääkintävoimistelu vanh. fysioterapia

FinMeSH:
fysioterapia erikoisalana KT lääkintävoimistelu erikoisalana http://www.yso.fi/onto/mesh/D026761

**Comment by YSA-kokous** [comment]
Yhdistetään, KÄ fysioterapia.
