### ISSUE TITLE
(kuva)taidearvostelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6985]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

(kuva)taidearvostelut 

#### Ehdotettu termi ruotsiksi   

ks. ysa/allärs 

#### Ehdotettu termi englanniksi   

art reviews 

#### Ehdotettu yläkäsite YSOssa (LT)   

[arvostelut (tuotokset)](http://www.yso.fi/onto/yso/p6612) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 
[90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581) 

#### Perustelut ehdotukselle   

SLM-sanastossa ei ole vieä tätä YSAssa jo olevaa taidearvostelut-termiä. Termillä voidaan kuvata niitä kuvataiteen aloja, jotka jäävät kapeamman näyttelyarvostelut -termin ulkopuolelle: ympäristötaide, maataide, julkisten rakennusten, vaikkapa Lastenklinikan, taiteen arviointi (KT kuvataidearvostelut)
Näyttelyarvostelut puolestaan voivat kuvata terminä muitakin aloja (TM:n autonäyttelyt, harrastajien koiranäyttelyt jne. voivat kai myös saada arvostelun leimaa..) eli jälkimmäinen ei ole niinkään yksiselitteinen terminä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä - lehtiaineistoa, myös artikkelikokoelmissa voinee tulla vastaan. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [(kuva)taidearvostelut](http://finto.fi/yse/fi/page/Y506985)

**Comment by mirmaid** [comment]
Seuraava kokous, tutkitaan YSA-termin käyttöä.

**Comment by mirmaid** [comment]
näyttelyarvostelut, kuvataidearvostelut KÄ taidearvostelut

**Comment by mirmaid** [comment]
Ohjaustermi myös YSOon?

**Comment by tpalonen** [comment]
..tai "näyttelyarvostelut (taide)" KÄ taidearvostelut?

**Comment by YSA-kokous** [comment]
näyttelyarvostelut (taide) KÄ taidearvostelut
