### ISSUE TITLE
jalustat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6986]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jalustat](http://www.yso.fi/onto/ysa/Y142523) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Allärs: socklar + stativ + piedestaler
Nykyinen vastine ei täsmää Melindan-käytön mukaan. 
Ks. MOT. 

#### Ehdotettu muutos   

Onko määriteltävissä? Tai mahdollisesti jaettavissa?

**Comment by mirmaid** [comment]
Mahdollisia esim. _jalustat (lisävarusteet) / jalustat (apuvälineet) / laitejalustat_. Toisessa merkityksessä käytetty huomattavasti vähemmän, jos tarvitaan, ehkä jotain sellaista kuin _jalustat (tukirakenteet)_.

**Comment by ilona-x** [comment]
Melinda x 69 + ketjut
47/69 kamerat, videokamerat, kaukoputket, kiikarit
7/69 aseet
1/69 kaiuttimet

3/69 patsaat, veistokset, muistomerkit
2/69 postilaatikot
2/69 sahaus (sahapukit)
1/69 purjeet
1/69 mastot
1/69 vuolukiviuuni
1/69 kasvit/pihaveistos
1/69 mallinuket

**Comment by mirmaid** [comment]
- _jalustat (lisävarusteet) / jalustat (apuvälineet) / laitejalustat_?

Viitteiden korjaamisen jälkeen päätetään, tarvitaanko _jalustat (tukirakenteet)_.

**Comment by YSA-kokous** [comment]
jalustat (lisävarusteet)
