### ISSUE TITLE
kaivosjätteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6987]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaivosjätteet 

#### Ehdotettu termi englanniksi   

extractive waste 

#### Ehdotettu termi ruotsiksi   

gruvavfall 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jätteet](http://www.yso.fi/onto/yso/p2360) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 

#### Perustelut ehdotukselle   

Termiyhdistelmän kaivostoiminta/kaivosteollisuus + jätteet tilalle. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Improving the environmental properties, utilisation potential and long-term prediction of mining wastes, http://urn.fi/URN:ISBN:978-952-217-398-0 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kaivosjätteet](http://finto.fi/yse/fi/page/Y506987)

**Comment by ilona-x** [comment]
yläkäsite teollisuusjätteet? http://www.yso.fi/onto/ysa/Y99414
https://fi.wikipedia.org/wiki/Teollisuusj%C3%A4te

**Comment by mirmaid** [comment]
2 viitettä Melindassa.
