### ISSUE TITLE
hankaussoittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6988]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hankaussoittimet](http://www.yso.fi/onto/ysa/Y101527) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa/muita muotoja? 

#### Perustelut ehdotukselle   

Ei löydy googlesta, sanakirjoista tms. Ei ole käytetty Melindassa. Onko tämän oltava sanastossa? Ja mikä se sitten tarkalleen on? Onko muita (käytettyjä) termimuotoja tälle ilmiölle? 
Ruotsinnos epäselvä.

**Comment by SamuVirokannas** [comment]
Mm. Kongressin kirjaston Medium of Performance Thesaurus for Music (LCMPT) tuntee termin friction instrument http://id.loc.gov/authorities/performanceMediums/mp2013015274.html (vaikkakaan sitä ei ole subject headings -osiossa) ja Wikipedia suppeamman termin friction idiophone https://en.wikipedia.org/wiki/Friction_idiophone. Finnassa termiä hankaussoittimet on käytetty muutaman kerran.

Hankaussoittimia ovat esim. lasiharmonikka, neulaviulu, (jousella soitettava) saha ja kitkarumpu sekä pyykkilaudan tapaiset soittimet. Sekossa ne tosin on luokiteltu hiukan epätarkasti lyömäsoittimiksi, tai jotkut suoraan soitin-pääluokan alle. Periaatteessa hankaussoittimet olisi myös jousisoittimien yläkäsite kielisoitinten lisäksi (kuten LCMPT:ssä). Käsitettä venyttämällä ehkä myös levysoitinta skrätsäykseen käytettynä voisi pitää hankaussoittimena.

Kyllä minusta hankaussoittimet-termin säilyttämiselle olisi perusteita. Kenties sitä alettaisiin käyttää hitusen enemmän, jos Ysassa sen alla olisi esimerkkeinä konkreettisia soittimia antamassa osviittaa siitä, millaisia soittimia termi tarkoittaa.

**Comment by tmoisio** [comment]
Sachsin ja von Hornbostelin soitinluokituksen Timo Leisiön suomennoksessa (Musiikki 1-4, 1974) käytetään termejä kitkaidiofoni ja kitkarumpu. Kitkarumpu löytyy myös SEKOsta (mutta hankaussoitinta ei). Mikäli käsitteelle nähdään edelleen tarvetta YSAssa, voisi harkita termin muuttamista muotoon kitkasoittimet. Ainakin SEKOssa tarve on ilmeinen. Sen alle menisivät sitten ainakin kitkarumpu ja erilaiset kitkaidiofonit.

**Comment by SamuVirokannas** [comment]
Leisiö antaa ruotsinkielisiksi termeiksi friktionsidiofon ja friktionstrumma. Näitä mukaillen friktionsinstrument voisi olla käypä hankaussoittimien ruotsinnos. Friktionsinstrument-termiä jonkin verran käytetäänkin, ks. esim. maininta sivulla http://www.musiksok.se/INSTRUME/u_membranofoner.html. 

Edellä mainitsin pyykkilaudan esimerkkinä hankaussoittimista, mutta ei se kuulukaan samaan ryhmään, vaikka soittajan kädenliike onkin hankaava: ääni ei synny soittimen värähtelystä kuten esim. lasiharmonikassa vaan raaputtamalla tuotetusta soittimeen kohdistuvien pikku iskujen sarjasta. Hankaussoittimet-termin muuttaminen kitkasoittimiksi toisi tämän eron hieman selvemmin esille. (Pyykkilauta, guiro, räikkä ym. ovat tarkemmin hammasidiofoneja, jotka Sachsin & von H:n luokituksessa kuuluvat kuvaavasti "välillisesti lyötäviin idiofoneihin" ja siltä kannalta ovat eräänlaisia lyömäsoittimia.) 

Sachs & von H. luokittavat kitkarummut kalvon perusteella membranofonien alle, erilleen kitkaidiofoneista, mutta kitkarumpu olisi luontevaa sijoittaa Tapanin ehdotuksen mukaisesti kitkasoittimiin. Tai toki samalla myös kalvosoittimiin, jos Ysaan haluttaisiin sellainen luokka. (Sekossa sen sijaan on jo entuudestaan kalvosoittimet, joten kaksoisluokitus olisi mielekäs; nyt kitkarumpu on Sekossa rummun alla, mutta rumpu on kuitenkin määritelty lyömäsoittimeksi, mitä kitkarumpu ei periaatteessa ole.)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin säilyttämistä. KT:ksi kitkasoittimet.

**Comment by YSA-kokous** [comment]
KT kitkasoittimet
