### ISSUE TITLE
asuntolat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6989]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asuntolat](http://www.yso.fi/onto/ysa/Y100890) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko tarkemmin määriteltävissä/jaettavissa? 

#### Perustelut ehdotukselle   

Allärs: internat + härbärgen, mutta oikeastaan olisi muitakin vastineita näiden lisäksi, riippuen merkityksestä. Ellei yllä oleva ehdotus onnistu on harkittava luovempia ratkaisuja Allärsin puolella (esim. "bostäder för vissa grupper" tms.)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: huoneisto t. asuinrakennus, jossa jhk ryhmään, yhteisöön, laitokseen tms. kuuluvat henkilöt saavat asua. _Sairaanhoitajien asuntola. Oppilasasuntola._ 

Käytetty sekä pitkäaikaisempaan, että tilapäiseen majoitukseen tarkoitetuista tiloista. (opiskelijat, turvapaikanhakijat, asunnottomat)

**Comment by ilona-x** [comment]
YSAssa erikseen oppilasasuntolat (elevhem)

**Comment by mirmaid** [comment]
Ratkaistaan konversion jälkeen.

**Comment by mariaforsen** [comment]
Tämä voi siis ruotsiksi liittyä useamman eri ryhmän "koteihin" ja niille on eri sanoja rippuen merkityksestä. 

Pitäisikö muuten olla käyttöohjaus: asuntolat (oppilaat) KÄYTÄ oppilasasuntolat? Saataisiin ainakin se ongelma poissuljettua.

Olisiko mahdollista eritellä myös personalbostäder/asuntolat (henkilökunnan) tai henkilökunnan asuntolat?

Voisiko erikseen olla myös asuntolat (sosiaalipalvelut/huolto tms.)= härbärgen tms.

Tällä tavalla saataisiin ainakin tärkeimmät merkityserot esille? Käyttäjä joka hakee tietoa asuntoloista esim. kodittomille jne. tuskin haluavat kirjallisuutta henkilökunnan tai oppilaiden asuntoloista...

Ks. myös TEPA

**Comment by ilona-x** [comment]
YSOssa nyt personalbostäder = työsuhdeasunnot http://www.yso.fi/onto/yso/p254

**Comment by mirmaid** [comment]
Melindassa:

- kehitysvammaiset
- turvapaikanhakijat
- asunnottomat
- mielenterveyskuntoutujat
- opiskelijat (voiko käyttää oppilasasuntolat tai riittääkö opiskelija-asunnot?)

**Comment by YSO-kokous** [comment]
Poistetaan käsite asuntolat. Tähän liittyvää käsitteistöä sanastossa paljon ja asuntolat itse tarpeettoman monialainen.

Lisätään ohjaustermejä:
asuntolat (opiskelijat) KÄYTÄ opiskelija-asunnot
asuntolat KÄYTÄ palveluasunnot
asuntolat KÄYTÄ asumispalvelut
asuntolat KÄYTÄ tuettu asuminen
asuntolat (yömajat) KÄYTÄ yömajat
