### ISSUE TITLE
makedonialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6992]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

makedonialaiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [makedonialaiset](http://finto.fi/yse/fi/page/Y506992)

**Comment by vthuhtala** [comment]
Käytetty Helkassa 23 kertaa. YSAan, kiitos!

**Comment by mariaforsen** [comment]
Sv. makedonier
