### ISSUE TITLE
montenegrolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6993]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

montenegrolaiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [montenegrolaiset](http://finto.fi/yse/fi/page/Y506993)

**Comment by mariaforsen** [comment]
Sv. montenegriner
