### ISSUE TITLE
Ljubljana

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6996]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ljubljana 

#### Ehdotettu termi ruotsiksi   

Ljubljana 

#### Ehdotettu termi englanniksi   

Ljubljana 

#### Vastaava käsite muussa sanastossa   

LOC : <http://id.loc.gov/bfentities/providers/79462cb0e6060852bafa21789c3862e6> 
Wikipedia : https://fi.wikipedia.org/wiki/Ljubljana 

#### Tarkoitusta täsmentävä selite   

Ljubljana on Slovenian pääkaupunki. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna-test.fi/Record/helka.1681775 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

**Ehdottajan organisaatio:** Helsingin yliopiston pääkirjasto **Termiehdotus Fintossa:** [Ljubljana](http://finto.fi/yse/fi/page/Y506996)

**Comment by jtuohini** [comment]
LCSH-linkki korjattuna: http://id.loc.gov/authorities/names/n50052801
Helka-linkki korjattuna: https://helka.finna.fi/Record/helka.1486067
 
(Kollegan puolesta pikaisesti)

**Comment by paivalai** [comment]
Unohtui: YSA/YSO temaattinen ryhmä: 11.
