### ISSUE TITLE
tutkimusmetriikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#6999]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tutkimusmetriikka 

#### Ehdotettu termi englanniksi   

research metrics 

#### Vaihtoehtoiset termit ja ilmaisut   

julkaisumetriikka 
metriikka 
tutkimuksen ja tietellisen julkaisutoiminnan mittarit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tutkimustoiminta](http://www.yso.fi/onto/yso/p2040) 
[tieteellinen julkaisutoiminta](http://www.yso.fi/onto/yso/p10480) 
[informatiikka](http://www.yso.fi/onto/yso/p3712) 

#### Alakäsitteet (RT)   

[bibliometriikka](http://www.yso.fi/onto/yso/p6597) 
[altmetriikka](http://www.yso.fi/onto/yso/p29513) 
[viiteanalyysi](http://www.yso.fi/onto/yso/p6193) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[82 Kustannustoiminta. Julkaisutoiminta. Kirjapainoala](http://www.yso.fi/onto/yso/p26563) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 
[81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/yso/p26572) 

#### Perustelut ehdotukselle   

Metriikka on alkanut viimeaikoina tarkoittaa muutakin kuin runomittaoppia. Esim. Vastuullinen metriikka -sivusto (https://www.vastuullinentiede.fi/fi) käyttää termiä metriikka. Leidenin manifestin käännöksessä http://yliopistokirjastot.fi/leidenin-manifesti/ käytetään systemaattisesti rinnan sanoja metriikka ja tutkimusmetriikka. Rinnalla näytään käytettävän vielä julkaisumetriikka-termiä (ks. esim. https://wiki.eduuni.fi/display/csctuha/Vastuullisen+julkaisumetriikan+kick-off+24.8.2018?preview=/75735680/75736090/TSV_avointiede_koordinaatiomalli_150818.pdf). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://blogs.uef.fi/ueflibrary/ 

**Termiehdotus Fintossa:** [tutkimusmetriikka](http://finto.fi/yse/fi/page/Y506999)

**Comment by YSA-kokous** [comment]
Tutkitaan, seuraava kokous

**Comment by mirmaid** [comment]
Englanninkielisen ja suomenkielisen Wikipedian määrittelyt bibliometriikalle eroavat, mutta on vähän epäselvää mikä olisi tutkimusmetriikan ja bibliometriikan ero, jos jälkimmäinen määritellään kuten englanninkielisessä artikkelissa.

**Comment by mariaforsen** [comment]
Metriikka on kyllä aivan eri asia ja se onkin jo sanastossa.

**Comment by YSA-kokous** [comment]
KÄ bibliometriikka
