### ISSUE TITLE
kuurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7000]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuurit 

#### Ehdotettu termi englanniksi   

Kuronians 

#### Ehdotettu termi ruotsiksi   

kurer 

#### Vaihtoehtoiset termit ja ilmaisut   

Curonians (eng) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[baltit](http://www.yso.fi/onto/yso/p7754) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2005003164.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Historiallinen balttilainen heimo/kansa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3189525 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa. 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [kuurit](http://finto.fi/yse/fi/page/Y507000)

**Comment by LeKorsu** [comment]
Tarvinnee jonkun selitteen, ettei käytetä lääkekuureista =)

**Comment by YSA-kokous** [comment]
kuurit (baltit?)

**Comment by mariaforsen** [comment]
Sv. kurer (folk)
