### ISSUE TITLE
musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7001]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikki](http://www.yso.fi/onto/ysa/Y97560) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi mukaan SLM-sanastoon ja liitetään sen ST-suhteiksi sanastossa jo olevat "kansanmusiikki", "perinnemusiikki", "populaarimusiikki" jne. 

#### Perustelut ehdotukselle   

Tarvitaan jokin yleistermi kuvaamaan aineistoa, joka sisältää useita musiikinlajeja, joita ei kuvailtaessa kuitenkaan syystä tai toisesta haluta (resurssipula tms) eritellä täsmällisemmin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin lisäämistä SLM:ään. ST perinnemusiikki, populaarimusiikki, taidemusiikki.

**Comment by mirmaid** [comment]
Tämä on lisätty ja mainitut ovat sen alla, mutta niiden ohella suoraan musiikin alla on paljon muutakin termistöä. Haluaako Muusa vielä tarkentaa hierarkiaa jotenkin?

**Comment by MUUSA-kokous** [comment]
Muusa laatii suunnitelman hierarkisoinnista.

**Comment by mirmaid** [comment]
Onko musiikin alakäsitejoukko nyt valmis? Suoria alakäsitteitä 112, haluaako Muusa katsoa, saako joitakin vielä tarkempiin hierarkioihin?

Linkitetäänkö http://id.loc.gov/authorities/genreForms/gf2014026952? Onko vastaavuus exact vai close match (ks. määritelmä)?

**Comment by MUUSA-kokous** [comment]
Hierarkisointia tarkastellaan edelleen.
LC-vastaavuus on exact match.

**Comment by mirmaid** [comment]
Miten pitkään tätä issueta pidetään vielä auki?
