### ISSUE TITLE
eroaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7003]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[eroaminen](http://www.yso.fi/onto/ysa/Y110768) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

Käytetty eniten parisuhteesta eroamisesta (myös paljon aineistoa vanhempien erosta lasten kannalta), runsaasti myös uskonnollisesta tai muusta yhteisöstä eroamisesta. Lisäksi jonkin verran EU:sta tai EMUsta eroaminen, vähän: työstä irtisanoutuminen, eroaminen virasta. Näitä ei voi kuvailla ruotsiksi samalla termillä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Huom. myös _poistuma_ (Allärs avgång). 

Kielitoimiston sanakirja: jstak poistuva määrä. _Asuntojen poistuma. Henkilökunnan vuotuinen poistuma. Luonnollinen poistuma_. Onko vastine oikein, avgång = ero (eroaminen), haihtuminen, lähtö, poistuminen?

**Comment by mirmaid** [comment]
Konversio on mahdollista teknisesti toteuttaa _eroaminen / utträde_, mutta tuottaa runsaasti virheellisiä ruotsinkielisiä termejä tietueisiin.

Melindassa 1053 viitettä.

**Comment by mariaforsen** [comment]
Utträde oli muistaakseni ikävä kompromissi joka tehtiin aikaisemmin YSO-työssä kun ei haluttu eritellä suomeksi: https://github.com/NatLibFi/Finto-data/issues/275 

Itse kannattaisin tietty edelleen tarkempaa jakoa tms. ruotsin kannalta, mutta entä suomen kannalta? Avioero, avoero jne. on jo sanastossa. Tietty jäljelle jäisi sitten " parisuhteesta eroaminen"? Onko mahdollista ohjata jotenkin?

Avgång= 
1 (plan­enlig) av­färd från utgångs­punkt särsk. av kollektiva transport­medel 
2 från­trädande av tjänst eller upp­drag 
3 bort­gående av gas, vätska, energi e.d.
Poistuma monesti oikeastaan minskning, mutta sehän on jo vastineena muille. Pelkkä poistuma ei ole helppoa ratkaista, eri termi riippuen mistä kysymys. Avgång lienee eräänlainen kompromissi, mutta vaatisi kyllä oikeastaan tarkenteen.

**Comment by mirmaid** [comment]
- _eroaminen (ihmissuhteet) / eroaminen (parisuhde) / eroaminen parisuhteesta_? Vrt. esim. [Lapsi ei halua erota](https://melinda.kansalliskirjasto.fi/byid/013603058) 
- eroaminen yhteisöstä
- Euroopan unionista eroaminen (EKS)

Mahdollisesti vielä muuta, jos tarvitaan (käsitellään viimeisessä konversiokokouksessa).

**Comment by YSA-kokous** [comment]
eroaminen (ihmissuhteet)
eroaminen yhteisöstä
Euroopan unionista eroaminen

**Comment by ilona-x** [comment]
Tarvitaan varmastikin eroaminen (työstä/virasta tmv.) KT irtisanoutuminen (työstä/virasta)
Esimerkkejä Melindasta: 

- Eroava liikenneministeri Matti Aura: "En pettynyt politiikkaan"
- Miksi skandaali ei kaada suomalaista poliitikkoa?

Entä mikä termi sopii, kun koko hallitus tai EU-komissio eroaa?

- Poliittinen yhdentyminen jäänyt taloudesta jälkeen  :komission ero kasvattaa EU:n uudistuspaineita

**Comment by ilona-x** [comment]
tarvitaanko eroahdistus? Melindassa käytetty eroaminen:

- Sairaanhoitajan keinot vastata kaksivuotiaan ripulieristyksessä hoidettavan lapsen eroahdistukseen 
- Separation anxiety in children and adolescents 

eroahdistus Melinda x 24

FinMeSH: http://www.yso.fi/onto/mesh/D001010

**Comment by jarmosaarikko** [comment]
ysa:ssa on myös  **kirkosta eroaminen**  http://www.yso.fi/onto/yso/p3935

**Comment by mirmaid** [comment]
eroaminen tehtävästä?

**Comment by mariaforsen** [comment]
Sv. avgång från uppdrag?

**Comment by YSA-kokous** [comment]
eroahdistus
eroaminen tehtävästä KT irtisanoutuminen, eroaminen virasta, tehtävästä eroaminen

eroaminen yhteisöstä, tarkistetaan ryhmät

**Comment by mariaforsen** [comment]
Sv. 
-separationsångest
-avgång från uppdrag
-utträde
-avslutande av relation ET avslutande av förhållande 
-utträde ur Europeiska unionen 
 felaktigt "lämna Europeiska unionen" i EKS
