### ISSUE TITLE
ajurit (tietokoneohjelmat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7004]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ajurit (tietokoneohjelmat)](http://www.yso.fi/onto/ysa/Y177630) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "laiteajurit" tai ainakin lisätään KT-muodoksi 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Laiteajuri
Tarvitaan myös asiasana "ajurit" (KT "pika-ajurit"), jolla kuvailla taksia edeltäneitä ajureita 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by osma** [comment]
Kuulostaa järkevältä. Mahdollisia altLabeleita: laitteistoajurit, laiteohjaimet

**Comment by YSA-kokous** [comment]
laiteajurit

**Comment by ilona-x** [comment]
YSA:ssa kuljettajat & hevosajoneuvot

https://www.hel.fi/hel2/kaumuseo/arkisto/ratikkasivut/vuokraajurit.htm
hevosajurit, vuokra-ajurit, vossikat

**Comment by mirmaid** [comment]
11 kertaa tässä merkityksessä Melindassa.

**Comment by mirmaid** [comment]
Mikä termi otetaan? Kaikki varmaan ok...itse tykkään vossikasta :slightly_smiling_face:

https://fi.wikipedia.org/wiki/Vossikka

Kielitoimiston sanakirja: vossikka: maksusta kyydittäviä kuljettava hevosajoneuvo ajureineen; tällaisen ajuri, vuokra-ajuri; issikka, isvossikka.

**Comment by mariaforsen** [comment]
Sv. hyrkuskar=vuokra-ajurit. Epäselvää miten käännettäisiin vossikat (droska viittaa ajoneuvoon, hyrkusk taas kuljettajaan..)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa hevosajurit. Ohjaustermiksi vossikat ja vuokra-ajurit.
