### ISSUE TITLE
lennättimenhoitajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7005]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lennättimenhoitajat 

#### Ehdotettu termi englanniksi   

telegraphists 

#### Ehdotettu termi ruotsiksi   

telegrafister 

#### Vaihtoehtoiset termit ja ilmaisut   

telegrafistit [fin] 
telegraphers [eng] 
telegraph operators [eng] 
sähköttäjät [fin] 
lennättäjät [fin] 
lennätinvirkamiehet [fin] 
lennätinpäälliköt [fin] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[työntekijät](http://www.yso.fi/onto/yso/p1075) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85133352> 
Wikidata : https://www.wikidata.org/wiki/Q2024200 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 

#### Perustelut ehdotukselle   

Tarvetta aineiston kuvailussa, varsinkin vanhemman aineiston osalta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Suomen lennätinosaston ensimmäinen päällikkö Otto Gustaf Nyberg ja naissähköttäjäkysymys / Väinö Heles; Lennättäjä : Suomen lennätinvirkamiesliiton kuukausjulkaisu. 

**Ehdottajan organisaatio:** (Helsingin yliopiston kirjasto) **Termiehdotus Fintossa:** [lennättimenhoitajat](http://finto.fi/yse/fi/page/Y507005)

**Comment by YSA-kokous** [comment]
Tutkitaan (YSAssa on radiosähköttäjät)

**Comment by ilona-x** [comment]
LCSHssa sekä Radio operators että Telegraphers

Kielitoimiston sanakirja: 
**radiosähköttäjä** radioviestintää ja siihen käytettäviä laitteita hoitava henkilö laivassa, puolustusvoimien viestintäverkossa tms., radisti

**Comment by mariaforsen** [comment]
Muissa sanastoissa (MTS, TERO) on "sähköttäjä/t"

**Comment by mirmaid** [comment]
Eli sähköttäjät KT lennättimenhoitajat, ST radiosähköttäjät?

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa sähköttäjät, lisätään muut variantit ohjaustermeiksi. (myös lennätinvirkailijat)
