### ISSUE TITLE
kognitiivinen dissonanssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7006]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kognitiivinen dissonanssi 

#### Ehdotettu termi ruotsiksi   

Kognitiv dissonans 

#### Ehdotettu termi englanniksi   

Cognitive dissonance 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kognitio](http://www.yso.fi/onto/yso/p642) 

#### Vastaava käsite muussa sanastossa   

Kognitiivinen dissonanssi : https://fi.wikipedia.org/wiki/Kognitiivinen_dissonanssi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa psykologiaan liittyvässä aineistossa. Myös esimerkiksi rokotovastaisuusuutta tms. käsittelevään kirjallisuuteen sopiva. 

#### Tarkoitusta täsmentävä selite   

Psykologian termi, jolla tarkoitetaan kahden ristiriitaisen kognition kokemista samanaikaisesti. Klassinen esimerkki on tarina ketusta ja pihlajanmarjoista. Kettu kokee kognitiivisen dissonanssin, kun hän haluaa pihlajanmarjoja, mutta ymmärtää, ettei voi saada niitä. Tällöin hän toteaa: "Happamia", jolla kettu pyrkii hälventämään kognitiivisen dissonanssin tunteen, väittämällä itselleen, ettei alunperinkään halunnut marjoja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

What we think about when we try not to think about global warming : toward a new psychology of climate action / Per Espen Stoknes. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [kognitiivinen dissonanssi](http://finto.fi/yse/fi/page/Y507006)

**Comment by ilona-x** [comment]
Melinda: 9 viitettä

FinMeSH: kognitiivinen dissonanssi http://www.yso.fi/onto/mesh/D003073 
SAO: Kognitiv dissonans
LCSH: Cognitive dissonance http://id.loc.gov/authorities/subjects/sh85027753
