### ISSUE TITLE
spekulatiivinen fiktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7007]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[spekulatiivinen fiktio](http://www.yso.fi/onto/ysa/Y200892) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan SLM:ään. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mirmaid** [comment]
Ok/SLM
