### ISSUE TITLE
elämäntapa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7008]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elämäntapa](http://www.yso.fi/onto/ysa/Y95044) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

allars: kaksi vastinetta:
levnadssätt http://finto.fi/allars/fi/page/Y21919?clang=sv
livsstil http://finto.fi/allars/fi/page/Y22014?clang=sv 

#### Perustelut ehdotukselle   

Pitäisi olla vain yksi...? 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Sanastossa lisäksi _elintavat / levnadsvanor_. Allärs-termillä _levnadssätt_ on kaksi YSO-vastinetta, levnadsvanor ja livsstil.

**Comment by mariaforsen** [comment]
Allfossa on selkeämpi ratkaisu tähän vanhaan ongelmaan, eli tarkoitus on ollut että Allfon myötä tilanne paranee. Allärsin puolella on kuitenkin sallittua olla kaksi vastinetta (ja molemmat ovat paljon käytettyjä Melindassa)

**Comment by mirmaid** [comment]
Korjattu Allärsissa.
