### ISSUE TITLE
tietokannat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7009]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietokannat](http://www.yso.fi/onto/ysa/Y99512) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan tietokantojen kuvailuun 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6935
