### ISSUE TITLE
kootut teokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7010]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kootut teokset](http://www.yso.fi/onto/ysa/Y102673) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan koottujen teosten kuvailuun 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6875
