### ISSUE TITLE
kansallisbibliografiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7011]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansallisbibliografiat](http://www.yso.fi/onto/ysa/Y95840) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan kansallisbibliografioiden kuvailuun 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Aineistoesimerkkejä?

**Comment by jtuohini** [comment]
Esimerkkejä:
https://melinda.kansalliskirjasto.fi/byid/006813326
https://melinda.kansalliskirjasto.fi/byid/003040262
https://melinda.kansalliskirjasto.fi/byid/009966923
