### ISSUE TITLE
artikkelit (julkaisut)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7012]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[artikkelit (julkaisut)](http://www.yso.fi/onto/ysa/Y94706) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan artikkelien kuvailussa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mariaforsen** [comment]
Onko SLM:n puolella tarvetta sulkutarkenteeseen?
