### ISSUE TITLE
ruumissaarnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7014]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ruumissaarnat](http://www.yso.fi/onto/ysa/Y111079) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan ruumissaarnojen kuvailussa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM
