### ISSUE TITLE
almanakat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7015]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[almanakat](http://www.yso.fi/onto/ysa/Y94586) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan almanakkojen kuvailuun 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM
