### ISSUE TITLE
exlibrikset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7016]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[exlibrikset](http://www.yso.fi/onto/ysa/Y95148) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan exlibristen kuvailussa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Teosesimerkkejä?

**Comment by jtuohini** [comment]
Esimerkkejä:
https://finna.fi/Record/vaski.590543
https://finna.fi/Record/raami.urn:nbn:fi-aalto:w_http%253A%252F%252Fwww.profium.com%252Ftaikarchivedobject%252F56A21D54-9075-9490-FB50-8AB53DE3832B
ja monta muuta Finnasta löytyvää, joissa termi laitettu vahingossa asiasanaksi, vaikka kyse on nimenomaan exlibriksistä itsestään, ei niitä käsittelevästä aineistosta

**Comment by AuHo22** [comment]
Näköjään SLM-terminologiaan on tällä hetkellä selkeästi istuutunut sen kaltainen termi kuten kuvastot, jotka luettelonomaisesti ehkä kuvaavat tämänkaltaisia ikäänkuin "koottuja leikkeitä" tai kuvia ja jolla on lähtökohtansa painettuun muotoon saatetussa aineistossa ; YSOssa on myös senkaltaisia termejä kuten kuvakokoelmat (tai leikekokoelmat), jotka voisivat kuvata myös elektronisesti säilytettäviä aineistoja.
Mielestäni määrittävä "muoto" tässä on kuva exlibriksestä ja samalla tavalla voidaan kuvia koota monesta muustakin asiasta - voiko exlibrikset olla myöskään lajityyppi tiukassa merkityksessä? Ja meillä on myös kuvastoja / luetteloita rahoista, mitaleista jne.
Kuuluisa alan pioneeriteos exlibriksistä kuvailtu kb:ssä luettelot-genren avulla:
https://kansalliskirjasto.finna.fi/Record/fikka.3616098

**Comment by mirmaid** [comment]
Ja jos aineisto sisältää valokuvia postikorteista, onko sen genre valokuvat, postikortit vai molemmat? Entä jos se sisältää valokuvia maalauksista tai seinävaatteista? Hieman samaa rajanvetoa myös esim. Melindan id 009935777 - lajityyppi vs. aihe.

**Comment by jtuohini** [comment]
Näissä siis kyse kappaleista (yksittäisistä niteistä), joihin on liimattu exlibris, ei siis kirjoista joissa on kuvia exlibriksistä! Siis kuvailun kohteena exlibrikset itsessään.

**Comment by jtuohini** [comment]
Ja mitä tulee aineistoon, jossa on faksimilejäljenöksiä valokuvapostikorteista, niin mielestäni aineiston lajityypiksi/muodoksi tulisi silloin _postikortit_ (ei _valokuvat_!) ja _kuvateokset_ yms. Jos taas aineisto koostuu painamalla reprotuista valokuvista, niin lajityypiksi/muodoksi laittaisin _valokuvat_ ja _kuvateokset_.

**Comment by mirmaid** [comment]
En suoraan sanoen tiedä millainen olisi faksimilejäljennös postikortista, mutta tarkoitin kirjaa, jossa on valokuvia postikorteista (joiden kuva voi olla piirros, valokuva, mitä vaan). Jos tämän lajityyppi on valokuvat/kuvateokset, sama koskee myös exlibriksiä. Vähän vaan pelkään, että kaikki kuvailijat eivät huomaa, että exlibrikset-genreä saa käyttää vain jos aineisto on kokoelma irrotettuja exlibriksiä. (Vai tarkoittaako kappale, johon on liimattu exlibris, että exlibrikset-genreä käytettäisiin kirjoista, joissa on mukana exlibris (eikä exlibristen kokoelmista)??

**Comment by jtuohini** [comment]
Jos on kyse kuvateoksesta, joka esittelee exlibriksiä (näköispainoksina t.s. valokuvina exlibriksistä), niin miksei voisi olla 655:ssäkin? Jos on yksittäinen kirja, johon on liimattu exlibris, niin silloin kyse olisi RDA:n näkökulmasta kappaleen kuvailusta ja 655-kenttään pitäisi liittää |5-osakenttä kertomaan, että tieto exlibriksestä ei koske manifestaatiota itseään (siis manifestaation kaikkia kappaleita).
 
Sama postikorttien osalta: viitaako termi postikorttiin esineenä vai voiko siitä tehdyt valokuvat (näköispainokset) kuvailla samalla? Vaatinee keskustelua ja selkeät käyttöohjeet sanastoon. Ei ole helppoa tämä.

**Comment by mirmaid** [comment]
Hyväksytty/SLM. Lisätään huomautus: Termillä kuvaillaan ainoastaan konkreettisia exlibriksiä. Exlibriksiä esittelevistä kuvateoksista käytetään SLM-termiä kuvateokset, kuvastot tms. ja YSO-asiasanaa exlibrikset.

**Comment by AuHo22** [comment]
Tuli jossain vastaan tämä marc21-formaatin kuvailu tietueen tyypistä, jolla siis erotellaan erityyppisiä aineistoja (06 nimiössä):
k - Kuva
Sisältää esimerkiksi kaaviot, kollaasit, tietokonegrafiikat, piirrokset, kopioiden alkuperäiskappaleet, sana- tai kuvakortit, maalaukset, valokuvanegatiivit, valokuvat, kuvat, valokuva-CD:t, postikortit, julisteet, tulosteet, opintomonisteet, tekniset piirustukset, valokuvajäljitelmät, ja kopiot tai jäljitelmät kaikista edellä mainituista.
r - Esine
Sisältää keinotekoiset esineet kuten mallit, dioraamat, pelit ja palapelit, simulaatiot, veistokset ja muut kolmiulotteiset taideteokset ja niiden jäljennökset, näyttelyesineet, koneet, vaatteet, lelut ja käsityöt, sekä luonnolliset kappaleet kuten mikroskooppipreparaatit.

Eli ensimmäiseen vaihtoehtoon kuuluvat siis nuo SLM:n yksittäiset postikortit ja julisteet ja mitä ilmeisemmin exlibrikset, varmaankin myös keskustelun alla olevat työpiirustukset, jälkimmäisessä on esim. slm-termi palapelit. Eli voisiko tätä jaottelua hyödyntää hierarkisoivia käsitteitä määriteltäessa? Opintomonisteet tietenkin vähän ihmetyttää jne.
