### ISSUE TITLE
synodaaliväitöskirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7017]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[synodaaliväitöskirjat](http://www.yso.fi/onto/ysa/Y118763) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan synodaaliväitöskirjojen kuvailussa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM. Hierarkia korjattava YSOssa.
