### ISSUE TITLE
kuolinilmoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7019]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuolinilmoitukset](http://www.yso.fi/onto/ysa/Y146225) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan kuolinilmoitusten kuvailussa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Teosesimerkkejä?

**Comment by jtuohini** [comment]
Esimerkkejä:
https://digi.kansalliskirjasto.fi/aikakausi/binding/1736733/articles/3232679 ja lähes kolmetuhatta vastaavaa
(tällaisethan eivät käsittele kuolinilmoituksia, vaan ovat niitä, ja jos KK:n digipalvelussa joskus saadaan SLM mukaan sanastovalikoimaan nimenomaan muotoa kuvaavien termien lähteeksi, niin tarvetta on)
