### ISSUE TITLE
transkriptiot (musiikki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7020]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[transkriptiot (musiikki)](http://www.yso.fi/onto/ysa/Y204025) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "nuotinnokset" sekä YSAan että SLM:ään (jälkimmäisessä päätermi muodossa "transkriptiot" ilman sulkutarkennetta) 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSA-kokous** [comment]
nuotinnokset KT transkriptiot (musiikki)

**Comment by mariaforsen** [comment]
Sv. transkriptioner (musik) ET notuppteckningar
