### ISSUE TITLE
inrōt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7021]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

inrōt 

#### Ehdotettu termi englanniksi   

inros 

#### Ehdotettu termi ruotsiksi   

inroer 

#### Vaihtoehtoiset termit ja ilmaisut   

inrōer [swe] 
inrōs [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lakkatyöt](http://www.yso.fi/onto/yso/p20521) 
[kotelot (säilytykseen liittyvät objektit)](http://www.yso.fi/onto/yso/p5928) 
[laukut](http://www.yso.fi/onto/yso/p2602) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85066552> 
Wikidata : https://www.wikidata.org/wiki/Q557164 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Perustelut ehdotukselle   

Nykyiset asiasanat eivät riittävän yksiselitteisiä nimenomaan inrōja käsittelevän aineiston kuvailemiseen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1582654 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [inrōt](http://finto.fi/yse/fi/page/Y507021)

**Comment by jtuohini** [comment]
Ja suomeksi näyttää käytetyn myös ilman tuota O:n päällä olevaa pituusmerkkiä, joten muodoksi mieluummin yksinkertaisempi **inrot** ja aiemmin ehdotettu KT:ksi.
