### ISSUE TITLE
sanoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7023]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sanoitukset](http://www.yso.fi/onto/ysa/Y98732) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi SLM-sanastoon. 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto 

#### Perustelut ehdotukselle   

Kuvailu sanoituksille ilman musiikkia.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin lisäämistä SLM:ään. Suhteet: LT kaunokirjallisuus, ST rocklyriikka.

**Comment by mirmaid** [comment]
Entä suhde laululyriikkaan?

**Comment by YSA-kokous** [comment]
Muusa: YSA?

**Comment by tpalonen** [comment]
YSA-kokouksessa sai kannatusta muutosehdotus, että laululyriikka poistettaisiin ja siitä tehtäisiin ohjaustermi sanoitukset-käsitteelle. Kannattaako Muusa tällaista muutosta YSAan/YSOon?

**Comment by tpalonen** [comment]
Muusalaisilta ei ole tullut kommenttia tähän. Itse kannatan viime YSA-kokouksen ehdotusta, laululyriikka KÄ sanoitukset. Esim. MUSA-asiasanan laululyriikka käyttö Melindassa oli sellainen että voitaisiin hyvin korvata sanoitukset-käsitteellä.

**Comment by YSA-kokous** [comment]
laululyriikka KÄ sanoitukset
