### ISSUE TITLE
moraalikato

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7025]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

moraalikato 

#### Ehdotettu termi englanniksi   

moral hazard 

#### Perustelut ehdotukselle   

taloustieteiden teoriassa yleinen ja vanha termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

taloustieteellisen 

**Termiehdotus Fintossa:** [moraalikato](http://finto.fi/yse/fi/page/Y507025)

**Comment by jtuohini** [comment]
Termille olisi varmaan hyvä saada myös selitys ja käyttöohje, etteivät kaltaiseni taloustieteen suhteen maallikot vahingossa käyttäisi sitä jossain ihan muussa merkityksessä, kun kuulostaa enemmän etiikan termiltä kuin taloustieteeseen liittyvältä.

**Comment by ilona-x** [comment]
Melinda: 4 viitettä

LCSH: Moral hazard http://id.loc.gov/authorities/subjects/sh2003006445

https://fi.wikipedia.org/wiki/Moraalikato

http://tieteentermipankki.fi/wiki/Taloustiede:moraalikato

**Comment by YSA-kokous** [comment]
moraalikato (taloustiede)

**Comment by mariaforsen** [comment]
Sv. moralisk risk (ekonomi)
