### ISSUE TITLE
rahan kiertonopeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7026]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rahan kiertonopeus 

#### Ehdotettu termi englanniksi   

velocity of money 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

taloustiede 

#### Perustelut ehdotukselle   

taloustieteessä vakiintunut vanha asia 

**Termiehdotus Fintossa:** [rahan kiertonopeus](http://finto.fi/yse/fi/page/Y507026)

**Comment by ilona-x** [comment]
LCSH: Circular velocity of money http://id.loc.gov/authorities/subjects/sh85026070

https://fi.wikipedia.org/wiki/Rahan_kiertonopeus

**Comment by mirmaid** [comment]
Ei Melindassa

**Comment by mariaforsen** [comment]
Sv. pengars omlopphastighet ET penningmändgens omloppshastighet
