### ISSUE TITLE
rationaaliset odotukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7027]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rationaaliset odotukset 

#### Ehdotettu termi englanniksi   

rational expectations 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

taloustiede 

#### Perustelut ehdotukselle   

Erittäin vakiintunut termi taloustieteissä 

**Termiehdotus Fintossa:** [rationaaliset odotukset](http://finto.fi/yse/fi/page/Y507027)

**Comment by ilona-x** [comment]
LCSH: Rational expectations (Economic theory)  http://id.loc.gov/authorities/subjects/sh85111518

https://en.wikipedia.org/wiki/Rational_expectations

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

http://tieteentermipankki.fi/wiki/Taloustiede:rationaaliset_odotukset

**Comment by YSA-kokous** [comment]
rationaaliset odotukset (taloustiede)

**Comment by mariaforsen** [comment]
Sv. rationella förväntningar (ekonomi)
