### ISSUE TITLE
sukupuolitutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7028]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sukupuolitutkimus](http://www.yso.fi/onto/ysa/Y127181) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan termi itsenäisenä asiasanana ja muutetaan se KT-muodoksi asiasanalle "sukupuolentutkimus" 

#### Perustelut ehdotukselle   

Kyseessä saman asian kaksi eri nimitystä, erona vain satunnainen rajavuosi 2012 ("Vuodesta 2012 alkaen käytetty nimitystä sukupuolentutkimus.") 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Vaihtuu yso-konversiossa.
