### ISSUE TITLE
sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7030]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sota](http://www.yso.fi/onto/ysa/Y98985) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

sodankäynti KT sota (nyt sota KT sodankäynti)

Tai vaihtoehtoisesti lisätään sulkutarkenne sota (toiminta) 

#### Perustelut ehdotukselle   

Käsitteiden _sota_ ja _sodat_ välistä eroa en selvennettävä. Ysossa tällä hetkellä _sota (toiminta)_ ja _sodat (tapahtumat)_.

Melindassa sotaa on käytetty melko väljästi  tarkoittamaan sekä sodankäyntiä että sotaa jonkinlaisena abstraktina ilmiönä, ks. esim. _Sounds of war : aesthetics, emotions and Chechnya / Susanna Hast._ Jälkimmäisen tyyppisiin tapauksiin sodankäynti sopii hieman heikommin, joskin samaa pätee myös sulkutarkenteelliseen muotoon. _Sodankäynti_ käytettävänä terminä poistaisi sulkutarkenteidne tarpeen myös monikolliselta muodolta. 

#### Ehdottajan organisaatio   

KK / YSO

**Comment by mirmaid** [comment]
Ehdotan samalla, että YSOssa poistetaan tarkenne _sodat_-käsitteeltä.

Tietueissa varmaankin _sota_-termi pitäisi korvata varmuuden vuoksi sekä _sodankäynti_ että _sodat_ -termeillä, joihin molempiin yksikkömuoto lisättäisiin ohjaustermiksi?

**Comment by YSA-kokous** [comment]
sota KÄ sodankäynti, sodat
YSOssa poistetaan tarkenne sodat-käsitteeltä
Tietueissa sota-termi korvataan sekä sodankäynti että sodat -termeillä
