### ISSUE TITLE
live-äänitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7032]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

live-äänitykset 

#### Ehdotettu termi ruotsiksi   

liveinspelningar 

#### Ehdotettu termi englanniksi   

live sound recordings 

#### Vaihtoehtoiset termit ja ilmaisut   

konserttitaltioinnit 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2011026368> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Tarkoitusta täsmentävä selite   

SLM-sanastoon: Äänitteet yleisön läsnä ollessa pääasiassa tosiaikaisesti tallennetuista konserteista, teatteriesityksistä ja muista samankaltaisista esityksistä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/4BIVQQAXMB8XFCV49BRH2S3UQ9AABEGNU27KSVCB7TNJX1XLEM-01922?func=full-set-set&set_number=044580&set_entry=000001&format=999 

#### Perustelut ehdotukselle   

Tarvitaan live-äänitteiden kuvailuun. 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [live-äänitykset](http://finto.fi/yse/fi/page/Y507032)

**Comment by asormune** [comment]
Täsmennyksessä: "Äänitteet yleisön läsnä ollessa pääasiassa tosiaikaisesti tallennetuista konserteista, teatteriesityksistä ja muista samankaltaisista esityksistä". Kysymys: Onko äänen lisäksi myös kuvan sisältävän esityksen (teatteriesitys, konsertti) (video)taltiointi "live-äänitys" vai "live-taltiointi" tai jotain muuta..

**Comment by ilkkahaataja** [comment]
Ehdotuksena esitysten kuvatallenteiden SLM-yläkäsitteeksi "kuvatallenteet esityksistä". Kuvailussa käytettäisiin lisäksi esitetyn teoksen genreä.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa käsitteen lisäämistä ainakin SLM:ään muodossa "liveäänitteet".

**Comment by mirmaid** [comment]
liveäänitteet ok / SLM

**Comment by mirmaid** [comment]
Lisää LCGFT-linkki

**Comment by mariaforsen** [comment]
Sv. liveinspelningar (produkter)
