### ISSUE TITLE
metsänhoitajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7034]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[metsänhoitajat](http://www.yso.fi/onto/ysa/Y97408) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Englanninkielinen vastine pitäisi arvattavasti olla ennemmin "foresters" 

#### Perustelut ehdotukselle   

Nykyinen englanninnos vaikuttaa keinotekoiselta ainakin googlaamisen perusteella. Katso myös https://www.wikidata.org/wiki/Q3738699, joka arvattavasti kannattaisi sillata termin Wikidata-vastineeksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by satuniininen** [comment]
Nykyiseen vastineeseen on päädytty sillä perusteella, että se on täsmällisempi. Myös AFO-ontogian käyttämä muoto on _forest officers_, ohjaustermeinään  _Graduate Foresters_ ja _Masters of Science in Forestry_. Kielitoimiston sanakirjan mukaan metsänhoitaja on _metsäalan korkeakoulututkinnon suorittanut henkilö_. Yhdysvaltalaisessa konteksissa käsitettä _forester_ käytetään huomattavasti väljemmässä merkityksessä.

**Comment by satuniininen** [comment]
Lisätty ohjaustermit _foresters_ ja _graduate foresters_ sekä siltaus http://id.loc.gov/authorities/subjects/sh85050686
