### ISSUE TITLE
puolesta asiointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7035]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puolesta asiointi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Valtakirjaan perustuva puolesta-asiointi, sähköinen tapa asioida terveydenhuollossa 

#### Perustelut ehdotukselle   

- 

**Termiehdotus Fintossa:** [puolesta asiointi](http://finto.fi/yse/fi/page/Y507035)

**Comment by ilona-x** [comment]
käytössä näyttää olevan ainakin muodot:
toisen henkilön puolesta asiointi
puolesta asiointi
toisen puolesta asiointi / asiointi toisen puolesta

https://www.suomi.fi/ohjeet-ja-tuki/tietoa-valtuuksista/toisen-henkilon-puolesta-asiointi

https://thl.fi/fi/web/tiedonhallinta-sosiaali-ja-terveysalalla/kanta-palvelut/yhteisesti-kaytettavat-kanta-palvelut/puolesta-asiointi

https://www.kanta.fi/asiointi-toisen-puolesta

**Comment by LeKorsu** [comment]
Asiointi toisen puolesta kuulostaa minun korvaani parhaimmalta vaihtoehdolta.

**Comment by YSA-kokous** [comment]
puolesta-asiointi

**Comment by mariaforsen** [comment]
Sv. uträttande av ärenden för någon annan
