### ISSUE TITLE
toiminnalliset häiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7037]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

toiminnalliset häiriöt 

#### Ehdotettu termi ruotsiksi   

funktionella störningar 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

#### Perustelut ehdotukselle   

https://stm.fi/documents/1271139/7832492/Toiminnallisten+h%C3%A4iri%C3%B6iden+hoidon+j%C3%A4rjest%C3%A4minen+luonnos+120417.pdf 
http://www.potilaanlaakarilehti.fi/uutiset/toiminnallisten-hairioiden-hoito-saa-vauhtia/ 
https://valtioneuvosto.fi/artikkeli/-/asset_publisher/1271139/suositus-toiminnallisten-hairioiden-hoidon-jarjestamisesta-lausunnolle 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [toiminnalliset häiriöt](http://finto.fi/yse/fi/page/Y507037)

**Comment by mirmaid** [comment]
Lääketieteen termit: _häiriö jossa elimen tai elinjärjestelmän toiminta on poikkeavaa ilman rakenteellista poikkeavuutta_; tässä merkityksessä _toiminnallinen somaattinen oireyhtymä_.

https://en.wikipedia.org/wiki/Medically_unexplained_physical_symptoms

**Comment by YSA-kokous** [comment]
toiminnallinen somaattinen oireyhtymä KT toiminnalliset häiriöt

**Comment by mariaforsen** [comment]
Sv. funktionella somatiska syndrom ET  funktionella störningar

**Comment by mariaforsen** [comment]
Liittyykö myös tähän: https://en.wikipedia.org/wiki/Functional_symptom ?
