### ISSUE TITLE
suomenvenäläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7039]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suomenvenäläiset 

#### Ehdotettu termi englanniksi   

Russian Finns 

#### Ehdotettu termi ruotsiksi   

finlandsryssar 

#### Ehdotettu yläkäsite YSOssa (LT)   

[suomalaiset](http://www.yso.fi/onto/yso/p3180) 
[venäläiset](http://www.yso.fi/onto/yso/p1208) 
[venäjänkieliset](http://www.yso.fi/onto/yso/p11619) 
[kielelliset vähemmistöt](http://www.yso.fi/onto/yso/p9309) 
[etniset vähemmistöt](http://www.yso.fi/onto/yso/p5739) 

#### Vastaava käsite muussa sanastossa   

LCSH : Russians--Finland. 
Wikidata : https://www.wikidata.org/wiki/Q1071514 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1164137 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [suomenvenäläiset](http://finto.fi/yse/fi/page/Y507039)

**Comment by mirmaid** [comment]
YSAssa on _suomensaksalaiset_.

7 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. ryssar i Finland ET finlandsryssar
