### ISSUE TITLE
henkinen hyvinvointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7043]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[henkinen hyvinvointi](http://www.yso.fi/onto/ysa/Y95347) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

psyykkinen terveys omaksi asiasanakseen 

#### Perustelut ehdotukselle   

YSAssa ovat termit psyykkinen hyvinvointi, psyykkinen terveys referenssitermeinä ja käytettävänä terminä henkinen hyvinvointi. Olisin kuitenkin kaivannut nimenomaan termiä psyykkinen terveys teokseen  LET ME NOT BE MAD : a story of unravelling minds. 
Termi olisi myös muussa teoriapainotteisessa aineistossa relevantti. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mirmaid** [comment]
Psyykkinen terveys on YSAssa ohjausterminä myös _mielenterveys_-termille.

**Comment by YSA-kokous** [comment]
Ei muutosta.
