### ISSUE TITLE
kauhupelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7045]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kauhupelit](http://www.yso.fi/onto/ysa/Y380120) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarvitaan myös slm sanastoon 

#### Perustelut ehdotukselle   

tarvitaan myös slm sanastoon 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by jtuohini** [comment]
Viittaako tämä mihin tahansa kauhupeliin vai nimenomaisesti lautapeliin, tietokonepeliin tms?

**Comment by mirmaid** [comment]
Hyväksytty/SLM
