### ISSUE TITLE
entistäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7048]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[entistäminen](http://www.yso.fi/onto/ysa/Y95075) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Restaurointi on nyt ohjaustermi YSAssa ja YSOssa. Ehdotan, että restaurointi olisi entistäminen ja konservointi käsitteiden yläkäsite. 

#### Perustelut ehdotukselle   

Helka-tietokannassa restaurointikäsitettä on käytetty 52 bib-tietueessa (masa-asiasanana).
MAO/TAO ontologiassa restaurointi on määritelty seuraavasti:
kohteen aiemmat rakennustavat huomioon ottava ja sen kulttuurihistoriallisen arvon säilyttävä korjaus, johon voi sisältyä konservoivia, rekonstruoivia ja entistäviä toimenpiteitä. 

#### Ehdottajan organisaatio   

Museoviraston kirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja: 
**restaurointi** - entistäminen, entisöinti. Rakennuksen restaurointi. 

http://www.tsk.fi/tepa/fi/haku/restaurointi
http://www.tsk.fi/tepa/fi/haku/entist%C3%A4minen

**Comment by mariaforsen** [comment]
Ruotsiksi hankala ratkaista siinä tapauksessa. Nyt entistäminen=restaurering, eikä muita sanoja oikein ole ruotsiksi (remontti=renovering)

**Comment by mirmaid** [comment]
_Kiinteistöliiketoiminnan sanaston_ ja _Kiinteistönpidon sanaston_ mukaan siis _entistäminen_ on laajempi käsite ja _restaurointi_ yksi entistämisen tyyppi. MAOssa puolestaan restaurointi määritellään suunnilleen samoin kuin Kiinteistöliiketoiminnan sanastossa entistäminen, mutta MAOn entistämisen ja restauroinnin määritelmät eivät juuri eroa toisistaan.

Kiinteistöliiketoiminnan sanasto: **entistäminen**: _korjausrakentaminen, jossa päätarkoitus on palauttaa tai säilyttää kohteen kulttuurihistoriallisia ja rakennustaiteellisia arvoja_ _Entistäminen voidaan jakaa restaurointiin, rekonstruointiin ja konservointiin._
**restaurointi**: _entistäminen (1), jossa kohde palautetaan aiempaan asuun poistamalla myöhemmin tehtyjä lisäyksiä ja täydentämällä heikentyneitä tai muutettuja osia_ 

MAO: **entistäminen**: _korjaus, jossa päätarkoitus on palauttaa tai säilyttää kohteen kulttuurihistoriallisia arvoja_
**restaurointi**: _kohteen aiemmat rakennustavat huomioon ottava ja sen kulttuurihistoriallisen arvon säilyttävä korjaus, johon voi sisältyä konservoivia, rekonstruoivia ja entistäviä toimenpiteitä._

**Comment by mariaforsen** [comment]
Lisää termejä ei ainakaan ole mahdollista luoda ruotsiksi, nykyisellään jo vaikeaa ja määritelmät näyttävät tosiaan vaihtelevan.

**Comment by mariaforsen** [comment]
Kielitoimiston sanakirja: 
restaurointi: entistäminen, entisöinti
entistää: palauttaa t. korjata entiselleen, restauroida 
Yleisssanastossa eli YSOssa nykyinen ratkaisu lienee hyvä ja MAO/TAOssa voi sitten olla tarkemmin eroteltuna?

**Comment by YSO-kokous** [comment]
Ei tehdä muutoksia. Käsitteet vahvasti päällekkäiset keskustelun valossa, joten ei tarvetta lisäkäsitteille.
