### ISSUE TITLE
adressit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7049]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[adressit](http://www.yso.fi/onto/ysa/Y111232) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätäänkö huomautus, jaetaanko tms. selvennys? 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja: 1. onnentoivotukseen, vainajan muiston kunnioittamiseen tms. käytettävä painate 2. useiden henkilöiden allekirjoittama julkilausuma. Ruotsinnos riippuu merkityksestä.

Melindassa käytetty eniten "julkilausumista", mutta myös muutama kerta ykkösmerkityksessä. 

Huom. nyt ryhmässä 00

**Comment by satuniininen** [comment]
Sopisiko _adressit (vetoomukset) + suruadressit_?

**Comment by mariaforsen** [comment]
Sv. 
-adresser (petitioner)
-kondoleansadresser ET sorgeadresser 
https://www.kotus.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/2008/skicka_en_adress

**Comment by YSA-kokous** [comment]
adressit (vetoomukset)
suruadressit
