### ISSUE TITLE
allemandet (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7050]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[allemandet (sävellykset)](http://www.yso.fi/onto/ysa/Y505380) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon muodossa "allemandet" 

#### Perustelut ehdotukselle   

Allemandeja on varsin paljon ja niitä pitäisi pystyä kuvailemaan asianmukaisesti oma itsenään, ei vain aiheena 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin lisäämistä SLM:ään. Ohjaustermit YSAsta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
