### ISSUE TITLE
liittymät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7051]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liittymät](http://www.yso.fi/onto/ysa/Y96936) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko esim. liikenne vs. tekniikka tms.? 

#### Perustelut ehdotukselle   

Monimerkityksinen ja käytetty Melindassa paljon ainakin liikenne- ja tekniikka/internet-merkityksessä
Ruotsiksi täytyy luoda selkeämpi sulkutarkenne tälle, koska sanastossa on myös liitännät=anslutningar.

**Comment by mirmaid** [comment]
_liittymät (liikenne)_ varmaankin ok

Kielitoimiston sanakirja: _teleyrityksen ja tilaajan välinen sopimus siitä, että tilaajan päätelaite kytketään televerkkoon._ Tässä ehkä tekniikka-tarkenne olisi liian rajaava ja toisaalta liian laaja, koska sen voisi tulkita sopivan myös ainakin jos on kyse kunnallistekniikasta. Ehkä jotain sellaista kuin _(viestintä)_ tai _(tietoliikenne)_...

Kielitoimiston sanakirjassa on vielä erikseen: teletekn. _televerkkoon kuuluva piste, jossa on liitäntä telepäätelaitetta varten._ - tätä ei ehkä tarpeen huomioida? 

On varmaan korjattavissa suurelta osin automaattisesti, mutta käytetty jonkin verran muissakin yhteyksissä kuin nämä kaksi.

**Comment by satuniininen** [comment]
Muita käyttöyhteyksiä ja selkeitä virheitä voisi ensin siivota pois käsin ja loput hoitaa automatiikan kautta. 
Esim:
_Liittymisohje kunnalliseen vesi- ja jätevesiverkostoon_ [liittymät --> liittyminen]
_KDK:n asiakasliittymä avaa monia mahdollisuuksia_ [liittymät --> käyttöliittymät]

**Comment by ilona-x** [comment]
JUPO:
liittymät 
ST internetliittymät,     puhelinliittymät,     vesijohtoliittymät,     viemäriliittymät

LIIKO: 
**liittymät (liikennealueet)** http://www.yso.fi/onto/mero/m9667
ST eritasoliittymät,     kiertoliittymät,     liikennevaloliittymät,     suuntaisliittymät,     tasoliittymät
RT rampit (liikenneväylät)

**Comment by YSA-kokous** [comment]
liittymät (liikenne)
liittymät (tietoliikenne)
