### ISSUE TITLE
lastenohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7052]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lastenohjelmat](http://www.yso.fi/onto/ysa/Y103019) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan myös SLM sanastoon 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
