### ISSUE TITLE
henkilötietolaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7053]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[henkilötietolaki](http://www.yso.fi/onto/ysa/Y113085) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tietosuojalaki on YSAssa ja YSOssa ohjaustermi. Käytettävä termi on henkilötietolaki. Ehdotan tietosuojalakia uudeksi käsitteeksi.
Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa, ks. esim:
https://helka.finna.fi/Record/helka.3180149 

#### Perustelut ehdotukselle   

Henkilötietolaki ja laki tietosuojalautakunnasta ja tietosuojavaltuutetusta kumottiin 1.1.2019, kun uusi tietosuojalaki tuli voimaan. 
https://tietosuoja.fi/henkilotietolaki
https://helka.finna.fi/Record/helka.3180149 

#### Ehdottajan organisaatio   

Museoviraston kirjasto

**Comment by mariaforsen** [comment]
Sv. dataskyddslag
