### ISSUE TITLE
halkoisjalkaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7055]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[halkoisjalkaiset](http://www.yso.fi/onto/ysa/Y158271) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.70240?showTree=true
"Massiäyriäiset, vanhalta nimeltään halkoisjalkaiset ovat keskimäärin parin sentin pituisia kuoriäyriäisiä." 

#### Ehdotettu muutos   

massiäyriäiset KT halkoisjalkaiset 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Englanniksi nyt Mysidacea mutta eikö tässä tarkoiteta Mysida?
Ks. myös https://fi.wikipedia.org/wiki/Massi%C3%A4yri%C3%A4iset

**Comment by mirmaid** [comment]
Englanninkielinen nimi varmaankin täältä: https://tieteentermipankki.fi/wiki/El%C3%A4intiede:halkoisjalkaiset, ilmeisesti vanhentunut: https://en.wikipedia.org/wiki/Mysidacea

**Comment by PaiviLipsanen** [comment]
https://laji.fi/taxon/MX.70240 - Mysida (lahko)
