### ISSUE TITLE
katusoittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7056]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[katusoittajat](http://www.yso.fi/onto/ysa/Y156773) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan LT-suhde "muusikot" --> "soittajat" 

#### Perustelut ehdotukselle   

Posetiivi on soitin, joten sillä musiikkia esittävät henkilöt ovat soittajia, eivät muusikoita yleensä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by JohPa** [comment]
Wikipedian määritelmä katusoittajalle: "Katusoittaja on katuesiintyjä, joka soittaa julkisella paikalla, kuten kadulla tai torilla jotakin soitinta, yleensä vapaaehtoista maksua vastaan; katusoittajan vieressä saattaa olla esimerkiksi hattu tai soitinkotelo, johon ihmiset voivat laittaa rahaa. Toiset antavat rahaa vain jos pitää musiikista, toiset tavan vuoksi. Muun muassa Helsingissä voi katusoittajia löytää keskustasta ja metroasemilta. Toiset katusoittajat vain soittavat ja kiittävät lahjoituksista, mutta osa myös laulaa jotain tunnettua kappaletta soittaessaan. Aihealueena saattaa olla esimerkiksi poplaulut. "

Onko jokin syy rajoittaa katusoittajat -termin käyttö pelkästään posetiivin soittajiin tai soittajiin yleensä? Katusoittaja voi myös laulaa, eli eikö "muusikot" ole silloin oikeampi?

**Comment by jtuohini** [comment]
Muusan kokous 4.10.2019: tehdään uusi YSE, jossa varsinainen asiasana muuteteen muotoon _katumuusikot_. Nykyinen LT-suhde pidetään ennallaan.
