### ISSUE TITLE
tuotantomusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7058]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tuotantomusiikki](http://www.yso.fi/onto/ysa/Y504784) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
SLM-työryhmä toivoo esimerkkejä aineistoista, joiden kuvailussa tätä lajityyppitermiä on tarvittu.

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4784

**Comment by jtuohini** [comment]
Muusan kokous 4.10.2019: Muusa kannattaa termin ottamista SLM-sanastoon. Esimerkki tulossa Helmetistä.

**Comment by TommiViitamies** [comment]
Esimerkki: https://kirjtuo1.helmet.fi/record=b2234558~S9*fin
