### ISSUE TITLE
kansanmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7059]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansanmusiikki](http://www.yso.fi/onto/ysa/Y95864) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan itsenäisenä asiasanana ja muutetaan KT-muodoksi asiasanalle "perinnemusiikki" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by asormune** [comment]
Lipsahti eilen vähän ohi, miksi kansanmusiikki -termi poistetaan. Vaikka määrittely ja erottelu perinnemusiikki vs kansanmusiikki ovatkin vaikeita. Suomessa ylin kouluttaja on Sibelius-Akatemian kansanmusiikin osasto. Moni muukin oppilaitos käyttää koulutustensa yhteydessa nimenomaan termiä kansanmusiikki. On kansanmusiikki-instituutti, Suomen Kansanmusiikkiliitto, Kansanmusiikki (Kansanmusiikin aikakauslehti) jne.

**Comment by jtuohini** [comment]
Muusan kokous 4.10.2019: ei poisteta termiä, mutta lisätään/päivitetään _kansanmusiikki_- ja _perinnemusikki_-termien määritelmät sekä YSOssa että SLM:ssä.

**Comment by mirmaid** [comment]
Saadaanhan nämä uudet määritelmät Muusalta?

**Comment by krinay** [comment]
Hyvien (= erottelevien ja yksiselitteisten) määritelmien laatiminen on varmasti vaikeaa, ehkä mahdotontakin - toivottavasti Muusa osoittaa tämän arvelun vääräksi. :-) MUSAn määritelmät (http://www.yso.fi/onto/musa/p190 ja http://www.yso.fi/onto/musa/p191) vaatisivat työstämistä. 

Jos hyviä määritelmiä ei löydy, voitaisiinko vielä jatkaa epämääräistä käyttöä eli valita kuvailussa aineistosta nouseva termi ja käyttää tiedonhaussa varan vuoksi molempia termejä? Ikävä tilanne, mutta vaihtoehto on minusta vielä hankalampi.  En siis kannata kansanmusiikin poistamista (ainakaan vielä). Termiä käytetään todella paljon paitsi alan sisällä (edellä mainittujen organisaatioiden lisäksi mm. Kansanmusiikin & Kansantanssin Edistämiskeskus KEK, Kaustisen kansanmusiikkijuhlat, SLS:n Finlands svenska folkmusikinstitut jne.), myös yleisessä kielenkäytössä: Google-osumia 1 020 000 (perinnemusiikilla 155 000). Melindassa kansanmusiikki on asiasanana 15829 kertaa, perinnemusiikki vielä useammin, 21281 kertaa, molemmat yhdessä 5609 kertaa.

LCSH:ssa on Folk music (Variants: Ethnic music, Traditional music). 
http://id.loc.gov/authorities/subjects/sh85049843

**Comment by YSA-kokous** [comment]
Odotetaan Muusan määritelmäehdotusta. Toivottiin, että määritelmästä poistuu viittaus aitouteen.

**Comment by MUUSA-kokous** [comment]
Muusa pohtii kansanmusiikin ja perinnemusiikin suhdetta tarkemmin. Palataan siis asiaan...

**Comment by MUUSA-kokous** [comment]
Muusa valmistelee määritelmiä _kansanmusiikille_ ja _perinnemusiikille_.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin _kansanmusiikki_ säilyttämistä, mutta termin _perinnemusiikki_ muuttamista sille ohjaustermiksi. Perinnemusiikin alakäsitteet siirrettäisiin kansanmusiikin alle.

Sama SLM:ään.

Määritelmä:
Tietyn yhteisön kansanperinnettä edustava tai siihen pohjautuva musiikki.

**Comment by tpalonen** [comment]
Perusteita Muusan kannalle:
Termejä käytetty rinnakkaisesti. Merkitysero vaikea ellei mahdoton määritellä. Muusan ehdottama ratkaisu vastaa LCSH:n folk music -käsitettä ja selkeyttää täten linkitystä. Muusa-kokouksen enemmistö kannatti käytettäväksi termiksi muotoa _kansanmusiikki_.

**Comment by krinay** [comment]
Joudun vielä vähän hämmentämään tätä soppaa:
Pitäsikö/voisiko jotenkin selventää _kansanmusiikin_ ja _maailmanmusiikin_ välistä merkityseroa? 

Onko _maailmanmusiikin_ määritelmä YSOssa edelleen hyvä suhteessa _kansanmusiikin_ uuteen määritelmään? Siis nämä: 
maailmanmusiikki: "Musiikki, jossa on yhdistelty länsimaisen populaarimusiikin ja (yleensä) Euroopan ulkopuolisten alueiden perinnemusiikin piirteitä"; 
kansanmusiikki: "Tietyn yhteisön kansanperinnettä edustava tai siihen pohjautuva musiikki."

Maailmanmusiikin ohjausterminä on mm. _nykykansanmusiikki_.

Ovatko kaikki _kansanmusiikin_ ja _maailmanmusiikin_  alakäsitteet oikeissa paikoissa, jos perinnemusiikin alakäsitteet siirtyvät kansanmusiikin alle?

**Comment by tpalonen** [comment]
Ehdotan, että maailmanmusiikkia koskeva keskustelu käydään maailmanmusiikki-issuessa (https://github.com/Finto-ehdotus/YSE/issues/6423). Minusta ensisijaisesti olisi hyvä saada pitkään vireillä olleeseen kansanmusiikki/perinnemusiikki-kysymykseen ratkaisu ja käsitellä maailmanmusiikki tästä erillään.

**Comment by krinay** [comment]
Ok, en tajunnut, että maailmanmusiikilla on oma issuensa. Olen samaa mieltä siitä, että sitä koskeva keskustelu kannattaa pääosin käydä erikseen. Mietin vain tuota maailmanmusiikin ohjaustermiä _nykykansanmusiikki_ suhteessa kansanmusiikille ehdotettuun uuteen määritelmään. Onko kaikki "nykykansanmusiikki" edelleen maailmanmusiikkia eikä kansanmusiikkia?

**Comment by tpalonen** [comment]
Ehkä yksinkertaisinta olisi lisätä nykykansanmusiikki (ja neo-kansanmusiikki) ohjaustermiksi myös kansanmusiikille. Lisäksi poistaisin nykykansamusiikki ja neo-kansanmusiikki-ohjaustermit maailmanmusiikilta. Maailmanmusiikki on ongelmallinen termi, joten minusta olisi parempi että käyttäjää ohjattaisiin käyttämään muita termejä.

Yksi vaihtoehto olisi ottaa nykykansanmusiikki sanastoon omana käsitteenä, mutta tässä ongelmana olisi vahva päällekkäisyys kansanmusiikki-käsitteen kanssa.

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan päätös: perinnemusiikki KÄYTÄ kansanmusiikki.
Muusan kommenttia odotetaan nykykansanmusiikista ja maailmanmusiikista.

**Comment by MUUSA-kokous** [comment]
Muusa laatii uuden määritelmän maailmanmusiikille ja miettii vielä nykykansanmusiikin ja maailmanmusiikin suhdetta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
Hierarkia: SLM:ssä _perinnemusiikin_ alakäsitteenä ollut _inkamusiikki_ on YSOssa _viihdemusiikin_ alakäsite, ja _arabialainen musiikki_ on suoraan _musiikin_ alla. Tehdäänkö näin myös SLM:ssä?

**Comment by jtuohini** [comment]
Inkamusiikin ainakin siirtäisin samalla tavalla kuin on nyt YSO:ssa (oli iso kädenvääntö aikanaan siellä, jos oikein muistan).

**Comment by jaskaj** [comment]
Ehdotus: Nykykansanmusiikki-termi ohjaustermiksi kansanmusiikki-termille.
Perustelu: Kansanmusiikki-termin määritelmä kattaa myös nykykansanmusiikki-ilmiön.

Ehdotus: Maailmanmusiikki-termi ohjaustermiksi kansanmusiikki-termille.
Perustelu: Kansanmusiikki-termin määritelmä kattaa myös maailmanmusiikki-ilmiön.

**Comment by jaskaj** [comment]
Ehdotus määritelmäksi (maailmanmusiikki):

Eri musiikkikulttuurien piirteitä yhdistelevä populaarimusiikki.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa maailmanmusiikin määritelmäehdotusta.
Kannatetaan myös nykykansanmusiikkia ohjaustermiksi kansanmusiikille. Ehdotetaan neo-kansanmusiikkia pois maailmanmusiikin ohjausterminä.
Lisätään myös SLM:ssä assosiatiivisiksi käsitteiksi samat, mitä on jo YSOssa.

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.
