### ISSUE TITLE
muistojulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7060]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muistojulkaisut](http://www.yso.fi/onto/ysa/Y505624) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotus koskee SLM-sanastoa. Ehdotan käsitteen lisäämistä lajityyppi- ja muotosanastoon. 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston lajityypin merkitsemiseen. 

#### Ehdottajan organisaatio   

Museoviraston kirjasto

**Comment by mirmaid** [comment]
Esimerkkiteoksia, joissa halutaan käyttää?

**Comment by AuHo22** [comment]
Pitäisi ehkä huomautuksella erottaa historiikkityyppisestä muistojulkaisukäytöstä, esim. Käytetään henkilöiden yhteydessä, käytä muuten historiikit, tms.
https://www.antikvariaatti.net/tuotteet/691076
https://www.antikvariaatti.net/tuotteet/133958

**Comment by mirmaid** [comment]
Hyväksytty/SLM
