### ISSUE TITLE
uzbekin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7073]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uzbekin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [uzbekin kieli](http://finto.fi/yse/fi/page/Y507073)

**Comment by satuniininen** [comment]
Tarvitaan myös teoksessa _Suomi englanti uzbekki kuvasanakirja_ /Tuomas Kilpi.

**Comment by mariaforsen** [comment]
Sv. uzbekiska ET uzbekiska språket
