### ISSUE TITLE
muinaisturkin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7074]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muinaisturkin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [muinaisturkin kieli](http://finto.fi/yse/fi/page/Y507074)

**Comment by ilona-x** [comment]
LCSH: Old Turkic language (KT Old Uighur language) http://id.loc.gov/authorities/subjects/sh85094570
https://en.wikipedia.org/wiki/Old_Turkic_language

http://finto.fi/lexvo/fi/page/otk
https://fi.wikipedia.org/wiki/Muinaisuiguurin_kieli

**Comment by mirmaid** [comment]
Ok, mutta kumpi termi - Lexvossa ja wikipediassa muinaisuiguurin kieli, Melindassa muinaisturkin kieli.

**Comment by AuHo22** [comment]
Esim. Aulis J. Joki: Maailman kielet (otsikolla Altailaiset kielet):

 "Täältä (Baikalin eteläpuolelta) on löydetty muinaisturkkilaisia piirtokirjoituksia, vanhimmat 700-luvun alkupuoliskolta. Muinaisturkin jatkaja oli uiguuri (so. muinaisuiguuri) - tämänkielisiä buddhalaisia ja manikealaisia tekstejä tunnetaan 1300-luvulle asti. 
Wikipediassa erotetaan Old Turkish proper ja vanhan uiguurin kärikirjoitukset:
https://en.wikipedia.org/wiki/Old_Turkic_language
https://en.wikipedia.org/wiki/Old_Turkic_script

The sources of Old Turkic are divided into two corpora:
the 7th to 10th century Orkhon inscriptions in Mongolia and the Yenisey basin (Orkhon Turkic, or Old Turkic proper).
9th to 13th century Uyghur manuscripts from Xinjiang (Old Uyghur), in various scripts including Brahmi, the Manichaean, Syriac and Uyghur alphabets, treating religious (Buddhist, Manichaean and Nestorian), legal, literary, folkloric and astrologic material as well as personal correspondence.

The Old Turkic manuscripts, of which there are none earlier than the 9th century, were found in present-day Xinjiang and represent Old Uyghur, a different Turkic dialect from the one represented in the Old Turkic inscriptions in the Orkhon valley and elsewhere.

Uiguurin kielen ei välttämättä uskota pohjautuneen muinaisuiguurin kieleen, eli sekaannuksen välttämiseksi pitäisin parempana terminä muinaisturkkia.

**Comment by mariaforsen** [comment]
Sv. fornturkiska ET fornuiguriska

Nationalencyklopedin: "Fornuiguriskan, en variant av fornturkiskan (se turkspråk), är dokumenterad i östturkestanska handskrifter med religiöst (buddhistiskt, manikeiskt och nestorianskt) innehåll."

**Comment by YSA-kokous** [comment]
muinaisturkki
