### ISSUE TITLE
tekstiilihistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7076]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tekstiilihistoria 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [tekstiilihistoria](http://finto.fi/yse/fi/page/Y507076)

**Comment by ilona-x** [comment]
MAO/TAO: tekstiilihistoria http://www.yso.fi/onto/tao/p2144

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/History_of_clothing_and_textiles

**Comment by mariaforsen** [comment]
Sv. textilhistoria
