### ISSUE TITLE
evenkin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7078]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

evenkin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [evenkin kieli](http://finto.fi/yse/fi/page/Y507078)

**Comment by mariaforsen** [comment]
Sv. evenki (språk)
