### ISSUE TITLE
vuorimarin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7080]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vuorimarin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [vuorimarin kieli](http://finto.fi/yse/fi/page/Y507080)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Vuorimarin_kieli

**Comment by mariaforsen** [comment]
Sv. västmariska

**Comment by jtuohini** [comment]
Tarvitaan edelleen! Käytetty Melindassa 85 kertaa.

KT _länsimarin kieli_, _tšeremissin kieli_, LT **marin kieli**

**Comment by jtuohini** [comment]
+ KT _länsimarin kieli_, _tšeremissin kieli_, LT **marin kieli**

**Comment by upuura** [comment]
Käsite tarvitaan. Lisäksi tarvitaan rinnakkaiskäsitteeksi niittymarin kieli (itämari).

**Comment by mariaforsen** [comment]
Sv. östmariska

**Comment by mirmaid** [comment]
Vastaava kuin _karjalan kieli_ - jos myös alakäsitteet ovat omia kieliään, niin onko olemassa myös _marin kieli_ (tai karjalan kieli)?

**Comment by upuura** [comment]
Kyllä. Aivan vastaavalla tavalla  _karjalan kielen_ alle kuuluu vähintäänkin livvin- eli aunuksenkarjala ja varsinaiskarjala. Lisäksi lyydin kieli tavallisesti luetaan karjalan murteisiin. Marin kieli (tai marilaiskielet) on samalla tavalla siis yläkäsite vuorimarille ja niittymarille.

**Comment by jarmosaarikko** [comment]
Wikidata [marin kielet](http://www.wikidata.org/entity/Q973685) - https://fi.wikipedia.org/wiki/Marin_kieli
- http://www.wikidata.org/entity/Q1776032  vuorimarin kieli | västmariska | Hill Mari KT Western Mari 
- http://www.wikidata.org/entity/Q3906614 niittymarin kieli | itämari; Meadow Mari KT Meadow-Eastern Mari, Eastern Mari

**Comment by mirmaid** [comment]
^ Ok, eli marin kieli ja karjalan kieli ovat _makrokieliä_.
