### ISSUE TITLE
tšuktšin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7082]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tšuktšin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [tšuktšin kieli](http://finto.fi/yse/fi/page/Y507082)

**Comment by mariaforsen** [comment]
Sv. tjuktjiska
