### ISSUE TITLE
Edo-kausi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7083]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Edo-kausi 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [Edo-kausi](http://finto.fi/yse/fi/page/Y507083)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Edo-kausi

LCSH: Edo period, Japan, 1600-1868 http://id.loc.gov/authorities/subjects/sh00009506

**Comment by mariaforsen** [comment]
Sv. Edoperioden
