### ISSUE TITLE
kuosittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7086]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuosittelu 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [kuosittelu](http://finto.fi/yse/fi/page/Y507086)

**Comment by ilona-x** [comment]
MAO/TAO: kuosittelu http://www.yso.fi/onto/tao/p303

http://ompelu.info/vaateompelu/kuosittelu/

Melinda: kuosittelu x 151

**Comment by mariaforsen** [comment]
Sv. ?

**Comment by ilona-x** [comment]
fi      kuosittelu
sv      riktning; utformning
en      shaping

Lähde: Vaatetussanaluettelo (TSK 8, 1985) http://www.tsk.fi/tepa/fi/haku/kuosittelu

**Comment by tpalonen** [comment]
Toivottavasti ei viittaa tähän:

**kuosit**
kuosi, (päihteillä saavutettu) olotila, kunto, kondis
_Huh huh että mä olin kuoseissa niissä bileissä!_ 
(Lähde: Urbaani sanakirja)
https://urbaanisanakirja.com/word/kuosit/
