### ISSUE TITLE
koptilaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7089]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koptilaisuus 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [koptilaisuus](http://finto.fi/yse/fi/page/Y507089)

**Comment by mirmaid** [comment]
Sanastossa on _koptilainen kirkko_ ja _koptit_.

**Comment by mariaforsen** [comment]
Voisi varmaan olla ohjaustermi.

**Comment by YSA-kokous** [comment]
KÄ koptilainen kirkko ja koptit
