### ISSUE TITLE
tekstiili- ja vaatetustekniika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7090]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tekstiili- ja vaatetustekniika 

#### Vaihtoehtoiset termit ja ilmaisut   

vaatetustekniikka 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [tekstiili- ja vaatetustekniika](http://finto.fi/yse/fi/page/Y507090)

**Comment by ilona-x** [comment]
MAO/TAO: 
vaatetustekniikka http://www.yso.fi/onto/tao/p58

JUPO: 
tekstiilitekniikan koulutus http://www.yso.fi/onto/jupo/p2428
vaatetustekniikan koulutus http://www.yso.fi/onto/jupo/p2085
tekstiili- ja vaatetustekniikan koulutus http://www.yso.fi/onto/jupo/p2580

**Comment by mariaforsen** [comment]
Sv. 
-textilteknik
-beklädnadsteknik ET konfektionssteknik

**Comment by mirmaid** [comment]
Ei Melindassa. _Tekstiilitekniikka_-termiä käytetty 11 kertaa, _vaatetustekniikka_-termiä käytetty runsaasti sekä vapaana asiasanana, että ktta/taika -terminä (Käsi- ja taideteollisuuden asiasanasto,Taideteollisuuden asiasanasto).

YSOssa on _vaatetusteknikot_, _tekstiili- ja vaatetusteollisuus_

**Comment by mirmaid** [comment]
[Tekstiilitekniikka puoltanee ehkä paikkaansa myös erillisenä](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=8&cad=rja&uact=8&ved=2ahUKEwig-a35i_3kAhVnpYsKHegYCBUQFjAHegQIBxAC&url=https%3A%2F%2Fwww.eduskunta.fi%2Fpdf%2FKK%2B327%2F2010&usg=AOvVaw2dTzMz3VriaEOXeD1CzWVq)

http://www.tekstiililehti.fi/fi/puheenvuoro/henna+vuorisalo+ja+maria+anko/

**Comment by YSA-kokous** [comment]
Molemmat erikseen
