### ISSUE TITLE
mantšun kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7092]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mantšun kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [mantšun kieli](http://finto.fi/yse/fi/page/Y507092)

**Comment by mariaforsen** [comment]
Sv. manchu (språk) ET manchuiska
