### ISSUE TITLE
samarialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7094]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

samarialaiset 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [samarialaiset](http://finto.fi/yse/fi/page/Y507094)

**Comment by ilona-x** [comment]
LCSH: Samaritans http://id.loc.gov/authorities/subjects/sh85116998
https://fi.wikipedia.org/wiki/Samarialaiset

**Comment by mirmaid** [comment]
N. 60 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. samaritaner ET samarier, samariter
