### ISSUE TITLE
pronssikautiset kulttuurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7096]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pronssikautiset kulttuurit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [pronssikautiset kulttuurit](http://finto.fi/yse/fi/page/Y507096)

**Comment by ilona-x** [comment]
MAO/TAO: http://www.yso.fi/onto/mao/p6571

**Comment by tpalonen** [comment]
Näyttää minun silmiini auktorisoidulta ketjulta. Pärjättäisiinkö kuvailussa, jos yhden yhdyskäsitteen sijaan kuvailtaisiinkin kahdella käsitteellä: pronssikausi JA kulttuuri?

**Comment by mirmaid** [comment]
YSOssa on _kivikautiset kulttuurit_ ja _arkeologiset kulttuurit_.

**Comment by mariaforsen** [comment]
Sv. bronsålderskulturer
