### ISSUE TITLE
Qing-dynastia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7097]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Qing-dynastia 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [Qing-dynastia](http://finto.fi/yse/fi/page/Y507097)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Qing-dynastia

**Comment by mariaforsen** [comment]
Sv. Qingdynastin
