### ISSUE TITLE
rautakautiset kulttuurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7098]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rautakautiset kulttuurit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [rautakautiset kulttuurit](http://finto.fi/yse/fi/page/Y507098)

**Comment by mirmaid** [comment]
53 viitettä Melindassa.

Ei MAO-ontologiassa.

**Comment by mariaforsen** [comment]
Sv. järnålderskulturer
