### ISSUE TITLE
tadžikin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7099]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tadžikin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [tadžikin kieli](http://finto.fi/yse/fi/page/Y507099)

**Comment by mariaforsen** [comment]
Sv. tadzjikiska ET tadzjikiska språket
