### ISSUE TITLE
maailmankirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7102]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maailmankirjallisuus 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [maailmankirjallisuus](http://finto.fi/yse/fi/page/Y507102)

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:maailmankirjallisuus

SAO: Litteratur KT Världslitteratur
LCSH: Literature KT World literature

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _arvostettu (kauno)kirjallisuus, jonka vaikutus ulottuu yli kieli- ja kansallisuusrajojen._ 

86 viitettä Melindassa

Ei KITOssa

**Comment by YSA-kokous** [comment]
KÄ kirjallisuus
