### ISSUE TITLE
rabbiininen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7104]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rabbiininen kirjallisuus 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [rabbiininen kirjallisuus](http://finto.fi/yse/fi/page/Y507104)

**Comment by mirmaid** [comment]
Teologian asiasanastossa, käytetty Melindassa runsaasti (130 x ilman sanastotunnusta, 117 x ttka).

LCSH: Rabbinical literature

**Comment by mariaforsen** [comment]
Sv. rabbinsk litteratur ET rabbinisk litteratur https://sv.wikipedia.org/wiki/Rabbinsk_litteratur
