### ISSUE TITLE
sarmaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7105]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarmaatit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [sarmaatit](http://finto.fi/yse/fi/page/Y507105)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Sarmaatit
LCSH: Sarmatians http://id.loc.gov/authorities/subjects/sh85117569

**Comment by mirmaid** [comment]
KT sarmatialaiset?

**Comment by mariaforsen** [comment]
Sv. sarmater
