### ISSUE TITLE
tokaariset kielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7106]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tokaariset kielet 

#### Vaihtoehtoiset termit ja ilmaisut   

tokaarin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [tokaariset kielet](http://finto.fi/yse/fi/page/Y507106)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Tokaarilaiset_kielet
LCSH: Tokharian language http://id.loc.gov/authorities/subjects/sh85135845

**Comment by mirmaid** [comment]
Maailman kielet ja kielikunnat: **tokaari**: jotkut puhuvat kirjoitusten löytöpaikkojen sijainnin mukaan itä- ja länsitokaarista, mutta kyseessä voi olla ajallinenkin ero. 

The documents record three closely related languages, called Tocharian A (also East Tocharian, Agnean, or Turfanian), Tocharian B (West Tocharian or Kuchean), and Tocharian C (Kroränian, Krorainic, or Lolanisch). https://en.wikipedia.org/wiki/Tocharian_languages

Melinda: kerran tokaarilaiset kielet, 39 x tokaarin kieli.

**Comment by mariaforsen** [comment]
Sv. tokhariska språk

**Comment by YSA-kokous** [comment]
tokaarilaiset kielet
