### ISSUE TITLE
avestan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7107]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

avestan kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [avestan kieli](http://finto.fi/yse/fi/page/Y507107)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Avestan_kieli

LCSH: Avestan language http://id.loc.gov/authorities/subjects/sh85010527

http://lexvo.org/id/iso639-3/ave

**Comment by mirmaid** [comment]
Huom. suhde muinais- ja keskipersiaan ja ohjaustermit

**Comment by mariaforsen** [comment]
Sv. avestiska ET avestiska språket
