### ISSUE TITLE
evenin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7109]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

evenin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [evenin kieli](http://finto.fi/yse/fi/page/Y507109)

**Comment by mariaforsen** [comment]
Sv. even (språk) ET evenska, lamutiska
