### ISSUE TITLE
itäslaavit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7110]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

itäslaavit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

#### Perustelut ehdotukselle   

a

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/6891
