### ISSUE TITLE
muinaispreussin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7111]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muinaispreussin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [muinaispreussin kieli](http://finto.fi/yse/fi/page/Y507111)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Muinaispreussin_kieli

LCSH: Prussian language (KT Old Prussian language) http://id.loc.gov/authorities/subjects/sh85108100

http://lexvo.org/id/iso639-3/prg

**Comment by AuHo22** [comment]
muinaispreussi (KT muinaispreussin kieli)

**Comment by mariaforsen** [comment]
Sv. fornpreussiska ET prusiska, preussiska, fornpreussiska språket
