### ISSUE TITLE
kantaslaavi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7115]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kantaslaavi 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [kantaslaavi](http://finto.fi/yse/fi/page/Y507115)

**Comment by ilona-x** [comment]
LCSH Proto-Slavic language http://id.loc.gov/authorities/subjects/sh85107765

https://fi.wikipedia.org/wiki/Slaavilainen_kantakieli

**Comment by mariaforsen** [comment]
Sv. urslaviska ET protoslaviska https://sv.wikipedia.org/wiki/Urslaviska
