### ISSUE TITLE
sandinistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7117]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sandinistit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [sandinistit](http://finto.fi/yse/fi/page/Y507117)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Sandinistit
LC:ssa yhteisö: Frente Sandinista de Liberación Nacional http://id.loc.gov/authorities/names/n50000584

**Comment by mirmaid** [comment]
31 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. sandinister ET FSLN, sandinisterna
