### ISSUE TITLE
ketšuan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7118]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ketšuan kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [ketšuan kieli](http://finto.fi/yse/fi/page/Y507118)

**Comment by mariaforsen** [comment]
Sv. quechua (språk) ET inkaspråket, keshwa (språk), kichwa (språk), qheshwa (språk), quichua (språk)
