### ISSUE TITLE
palynologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7119]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

palynologia 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [palynologia](http://finto.fi/yse/fi/page/Y507119)

**Comment by ilona-x** [comment]
YSO: siitepölyanalyysi http://www.yso.fi/onto/yso/p20619 (linkattu LCSH Palynology)

https://tieteentermipankki.fi/wiki/Kasvitiede:siitep%C3%B6lytutkimus

https://fi.wikipedia.org/wiki/Palynologia

**Comment by mariaforsen** [comment]
Sv. palynologi /SAO

**Comment by mirmaid** [comment]
Englanninkielinen Wikipedia määrittelee laajemmin kuin suomen- ja ruotsinkieliset. Erittäin päällekkäinen kuitenkin käytännössä _siitepölyanalyysin_ kanssa.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mariaforsen** [comment]
Molemmat SAOssakin. Nationalencyklopedin: "pollenanalys, analysmetod inom palynologin vilken omfattar artbestämning och frekvensberäkning av växters pollen". Eli palynologia on se koko tiede, eli laajempi termi. Onko kieliero, sillä tavalla että suomeksi siitepölytutkimus voi viitata sekä menetelmään että koko tieteeseen ja sen takia päällekkäisyyttä suomen osalta?

**Comment by mirmaid** [comment]
Päivi tutkii.

**Comment by YSA-kokous** [comment]
Tutkitaan Melinda-kuvailua: onko tapauksia, joihin palynologian lisäksi ei sovi siitepölyanalyysi. Käytetty Melindassa 91 kertaa. Siitepölyanalyysi on jo YSOssa.

**Comment by jarmosaarikko** [comment]
botaniikan näkökulmasta löytyy kirjallisuutta, jossa käsitellään siitepölyä ja sen rakennetta eikä niinkään siitepölyanalyysiä...  esim. https://melinda.kansalliskirjasto.fi/byid/001390548 ja https://melinda.kansalliskirjasto.fi/byid/002131618
tämä puoltaisi käyttämään palynologiaa omana käsitteenään.

**Comment by mirmaid** [comment]
Ongelma on siinä, että jos molemmat ovat sanastossa, käytettäisiin _palynologiaa_ mahdollisesti myös silloin, kun aineisto käsittelee _siitepölyanalyysia_. Siitepölytutkimus olisi ehkä vielä selkeämmin koko tieteenalan kattava termi. Yksi mahdollisuus on toki ottaa _palynologia_ erikseen, mutta ohjata käyttöä lisäämällä _siitepölyanalyysille_ KT palynologia (siitepölyanalyysi).

**Comment by PaiviLipsanen** [comment]
https://termipankki.fi/tepa/fi/haku/palynologia
Tämän mukaan palynologia = siitepölytutkimus, tutkitaan siitepölyä yleisesti
Siitepölyanalyysi olisi eri asia/menetelmä, jota käytetään esim. arkeologiassa, rikostutkinnassa ym.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon palynologia, silloin kun viitataan muuhun kuin siitepölyanalyysiin.
Lisäksi lisätään ohjaustermi:
palynologia (siitepölyanalyysi) KÄYTÄ siitepölyanalyysi
