### ISSUE TITLE
korjakit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7126]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

korjakit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [korjakit](http://finto.fi/yse/fi/page/Y507126)

**Comment by mariaforsen** [comment]
Sv. korjaker
