### ISSUE TITLE
luostarielämä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7127]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luostarielämä 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [luostarielämä](http://finto.fi/yse/fi/page/Y507127)

**Comment by mirmaid** [comment]
29 viitettä Melindassa. Usein tietueesta puuttuu termi _luostarit_...

**Comment by mariaforsen** [comment]
Sv. klosterliv (myös SAOssa)
