### ISSUE TITLE
persialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7128]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

persialaiset 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [persialaiset](http://finto.fi/yse/fi/page/Y507128)

**Comment by ilona-x** [comment]
LCSH: Iranians KT Persians
SAO: Iranier KT Perser (etnisk grupp)

**Comment by mirmaid** [comment]
44 viitettä Melindassa

Ks. myös https://en.wikipedia.org/wiki/Name_of_Iran

YSOssa on _persialainen_, joka on kissarotu.

**Comment by LeKorsu** [comment]
Riittäisikö persialaiset ohjaustermiksi ysossa jo oleville iranilaisille, vai halutaanko tämä nimenomaan historiallisena kansana? Tarvitseeko silloin määritelmän, milloin persialaisista on tullut iranilaisia =0

**Comment by YSA-kokous** [comment]
KÄ iranilaiset
