### ISSUE TITLE
Troijan sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7129]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Troijan sota 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [Troijan sota](http://finto.fi/yse/fi/page/Y507129)

**Comment by vthuhtala** [comment]
Melindassa asiasanahaulla 'Troijan sota' 73 osumaa

**Comment by mariaforsen** [comment]
Sv. trojanska kriget
