### ISSUE TITLE
avaarit (muinainen kansa)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7131]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

avaarit (muinainen kansa) 

#### Vaihtoehtoiset termit ja ilmaisut   

avaarit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [avaarit (muinainen kansa)](http://finto.fi/yse/fi/page/Y507131)

**Comment by mirmaid** [comment]
26 viitettä Melindassa, suurin osa käsittelee muinaiskansaa. Avaarit ovat myös nykyinen kansa Kaukasiassa. LCSH:ssa vain Avars, Wikipedia: Pannonian Avars, Avars (Caucasus).

**Comment by mariaforsen** [comment]
Sv. avarer (forntidsfolk)
