### ISSUE TITLE
khmerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7132]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

khmerit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [khmerit](http://finto.fi/yse/fi/page/Y507132)

**Comment by mariaforsen** [comment]
Sv. khmerer
