### ISSUE TITLE
Kronan (laiva)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7133]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kronan (laiva) 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [Kronan (laiva)](http://finto.fi/yse/fi/page/Y507133)

**Comment by mirmaid** [comment]
Suomalaiset yhteisönimet -sanastoon auktorisoidaan ensisijaisesti suomalaisia laivoja ja veneitä.
