### ISSUE TITLE
Estonia (laiva)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7135]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Estonia (laiva) 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [Estonia (laiva)](http://finto.fi/yse/fi/page/Y507135)

**Comment by mirmaid** [comment]
Auktorisoitu Suomalaiset yhteisönimet -sanastoon, http://urn.fi/URN:NBN:fi:au:cn:234129A
