### ISSUE TITLE
langobardit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7138]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

langobardit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [langobardit](http://finto.fi/yse/fi/page/Y507138)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Langobardit

LCSH: http://id.loc.gov/authorities/subjects/sh85078180

**Comment by mariaforsen** [comment]
Sv. langobarder ET longobarder
