### ISSUE TITLE
mayakielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7139]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mayakielet 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [mayakielet](http://finto.fi/yse/fi/page/Y507139)

**Comment by ilona-x** [comment]
LCSH: Mayan languages http://id.loc.gov/authorities/subjects/sh85082405

https://fi.wikipedia.org/wiki/Mayakielet

**Comment by mariaforsen** [comment]
Sv. mayaspråk ET mayanska språk
