### ISSUE TITLE
glagoliittinen kirjaimisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7140]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

glagoliittinen kirjaimisto 

#### Vaihtoehtoiset termit ja ilmaisut   

glagolica 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [glagoliittinen kirjaimisto](http://finto.fi/yse/fi/page/Y507140)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Glagoliittinen_kirjaimisto

**Comment by mirmaid** [comment]
Olisiko tämä _kyrillisen kirjaimiston_ alakäsite vai RT?

2 viitettä Melindassa

LCSH: Glagolitic alphabet

**Comment by vthuhtala** [comment]
Melindassa 'glagolica'
- asiasanahaussa 28 osumaa
- sanahaussa 31 osumaa

**Comment by mariaforsen** [comment]
Sv. glagolitiska alfabetet ET glagolitisk skrift
