### ISSUE TITLE
druusit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7142]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

druusit 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [druusit](http://finto.fi/yse/fi/page/Y507142)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Druusit

LCSH Druzes http://id.loc.gov/authorities/subjects/sh85039793

**Comment by mirmaid** [comment]
28 viitettä Melindassa, kerran _druusilaisuus_.

**Comment by mariaforsen** [comment]
Sv. druser
