### ISSUE TITLE
muinaispersian kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7144]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muinaispersian kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [muinaispersian kieli](http://finto.fi/yse/fi/page/Y507144)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Muinaispersian_kieli

LCSH: Old Persian language http://id.loc.gov/authorities/subjects/sh85094559

http://lexvo.org/id/iso639-3/peo

**Comment by AuHo22** [comment]
Pitäisikö tässä nyt kuitenkin olla johdonmukainen  YSOon jo aiemmin otettujen kielimuotojen kanssa, esimerkkinä ohjaustermi- ja käytettävä asiasanapari: muinaiskreikan kieli -> muinaiskreikka. Samoin on muinaisranska, muinaisnorja jne. -> so. muinaispersia
Sama tietenkin koskisi toista hyväksyttävissä olevaa ehdotusta muinaispreussin kieltä -> muinaispreussi

**Comment by mariaforsen** [comment]
Sv. fornpersiska
