### ISSUE TITLE
nahuatlin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7145]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nahuatlin kieli 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [nahuatlin kieli](http://finto.fi/yse/fi/page/Y507145)

**Comment by mariaforsen** [comment]
Sv. nahuatl (språk) ET aztekiska
