### ISSUE TITLE
udehen kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7146]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

udehen kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

#### Perustelut ehdotukselle   

a 

**Termiehdotus Fintossa:** [udehen kieli](http://finto.fi/yse/fi/page/Y507146)

**Comment by mariaforsen** [comment]
Sv. udehe (språk) ET udihe (språk)
