### ISSUE TITLE
altailaiset kansat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7147]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

altailaiset kansat 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [altailaiset kansat](http://finto.fi/yse/fi/page/Y507147)

**Comment by ilona-x** [comment]
LCSH: Altaic peoples KT Altaians http://id.loc.gov/authorities/subjects/sh00006226

https://fi.wikipedia.org/wiki/Altailaiset

Melinda: 
altailaiset kansat x 32
altailaiset x 7

**Comment by mariaforsen** [comment]
Sv. altaiska folk ET altajer
