### ISSUE TITLE
dakotat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7148]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dakotat 

#### Perustelut ehdotukselle   

a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

a 

**Termiehdotus Fintossa:** [dakotat](http://finto.fi/yse/fi/page/Y507148)

**Comment by mariaforsen** [comment]
Sv. dakota (folk) ET dakotaindianer
