### ISSUE TITLE
ennustaminen (okkultismi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7150]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ennustaminen (okkultismi)](http://www.yso.fi/onto/ysa/Y95068) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan sulkutarkenteeksi jotain vähemmän pahaenteistä, kuten _ennustaminen (taikausko)_ 

#### Perustelut ehdotukselle   

_(okkultismi)_ istuu huonosti aineistoihin, joissa on käsitellään ennustamista viihteen tai lasten leikkiperinteen kannalta. 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
_Auralla_ tarkenteena _(rajatieto)_, mutta sekin on ehkä vähän liikaa noista lasten jutuista?

**Comment by mariaforsen** [comment]
Itse en näe ongelmaa tässä. Vaikka se tehdään "leikkinä" se perustuu edelleen okkultismiin (=salatiede, salaoppien harjoittaminen) ja rajatietoon (=paranormaaleja asioita koskevista teorioista). Taikausko sen sijaan kuulostaa aika tuomitsevalta, jos kyseessä on kirjoja joissa tämä käsitellään tosissaan (kuten varmaan yleensä on). Vaikka okkultismi on esim. kristillisissä piireissä käsitelty pahaenteisenä sen ei pitäisi mielestäni vaikuttaa tähän. https://fi.wikipedia.org/wiki/Okkultismi

**Comment by YSA-kokous** [comment]
ennustaminen (magia)
