### ISSUE TITLE
maatalousrakennukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7152]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maatalousrakennukset](http://www.yso.fi/onto/ysa/Y97217) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "talousrakennukset" 

#### Perustelut ehdotukselle   

Kyseistä ilmausta käytetään myös, esim. opinnäytetyö: Wiurilan talousrakennukset / Kirsti Kairinen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Talousrakennukset voivat olla muitakin kuin maatalousrakennuksia esim.:
https://www.stat.fi/meta/luokitukset/rakennus/001-2018-07-12/1911.html

**Comment by mariaforsen** [comment]
SAOssa on erikseen ekonomibyggnader (talousrakennukset)

**Comment by PaiviLipsanen** [comment]
talousrakennus: taloudenpidossa tarvittava rakennus, ulkorakennus. Navetta, lato ym. talousrakennukset. Maatilan talousrakennukset. Sairaalan talousrakennus. 
https://www.kielitoimistonsanakirja.fi/

**Comment by YSA-kokous** [comment]
Mahdollisesti omana terminään, seuraava kokous.

**Comment by ilona-x** [comment]
tässä vielä maatalousrakennukset tuolta Tilastokeskuksen rakennusluokituksesta:
http://www.stat.fi/meta/luokitukset/rakennus/001-2018-07-12/14.html
14 Maatalousrakennukset ja eläinsuojat

Rakennukset, jotka on tarkoitettu maatalouden käyttöön, eläinten suojiksi tai pienimuotoisen metsä- tai kalatalouden käyttöön. Maatalousrakennuksia ja eläinsuojia ovat kotieläinrakennukset ja muut maatalousrakennukset.

Ja talousrakennukset:'
1911 Talousrakennukset

Muut rakennukset, jotka palvelevat asuin- tai vapaa-ajan asuinrakennuksia tai jotka ovat väliaikaisia. Talousrakennuksia ovat esimerkiksi asuin- ja vapaa-ajan asuinrakennuksiin kuuluvat vajat, pyöräsuojat ja autotallit sekä työmaiden tilapäiset henkilöstö- ja sosiaalitilarakennukset.
http://www.stat.fi/meta/luokitukset/rakennus/001-2018-07-12/1911.html

**Comment by ilona-x** [comment]
MAO/TAO: talousrakennukset KT ulkorakennukset http://www.yso.fi/onto/mao/p282

**Comment by YSA-kokous** [comment]
Otetaan uusi käsite sanastoon:
talousrakennukset KT ulkorakennukset (ST maatalousrakennukset)

**Comment by mariaforsen** [comment]
Mutta maatalousrakennukset on jo sanastossa ja pitääkin olla, ei kai tarkoitus ollut lisätä se korvattuna mihinkään.

**Comment by mariaforsen** [comment]
Sv. ekonomibyggnader ET uthusbyggnader
