### ISSUE TITLE
keramiikkataiteilijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7153]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keramiikkataiteilijat](http://www.yso.fi/onto/ysa/Y96087) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään toiseksi KT-muodoksi "taidekeraamikot" 

#### Perustelut ehdotukselle   

Ilmausta käytetään, joten se olisi hyvä saada ohjausmuodoksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. konstkeramiker
