### ISSUE TITLE
virsikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7155]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[virsikirjat](http://www.yso.fi/onto/ysa/Y100282) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "käsivirsikirjat" 

#### Perustelut ehdotukselle   

Suhteellisen harvinainen nimitys, mutta silti käytössä (esim. ISBN 951-618-224-0 vuodelta 1998) ja perusteltavissa KT-muodoksi sekä YSOon että SLM:ään. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätty YSO ja SLM.
