### ISSUE TITLE
kirkkolaivat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7156]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirkkolaivat 

#### Ehdotettu termi ruotsiksi   

votivskepp 

#### Ehdotettu termi englanniksi   

votive ships 

#### Vaihtoehtoiset termit ja ilmaisut   

votiivilaivat [fin] 
kyrkskepp [swe] 
church ships [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pienoismallit](http://www.yso.fi/onto/yso/p17521) 
[votiivit](http://www.yso.fi/onto/yso/p12724) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q4405227 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirkkolaivoista ja kirkkolaivatraditiosta / Mirja Kanerva 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kirkkolaivat](http://finto.fi/yse/fi/page/Y507156)

**Comment by mirmaid** [comment]
9 viitettä Melindassa. Onko yksiselitteinen? https://fi.wikipedia.org/wiki/Laiva_(arkkitehtuuri), https://www.finlandiakirja.fi/fi/niilo-m-mattila-kirkkolaiva-1-3-277249.html

**Comment by mariaforsen** [comment]
RT varmaan votiivit siinä tapauksessa.

**Comment by tpalonen** [comment]
Kannatan votiivilaivaa käytettäväksi termiksi niin ei mene sekaisin tuon arkkitehtonisen laivan kanssa.

**Comment by YSA-kokous** [comment]
votiivilaivat
