### ISSUE TITLE
hyperavaruuden teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7157]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hyperavaruuden teoria](http://www.yso.fi/onto/ysa/Y110155) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa? Onko muita sanamuotoja ilmiölle?

#### Perustelut ehdotukselle   

Ei ole käytetty Googlessa kertaakaan muualla kuin YSA-terminä. Mihin tämä oikeastaan viittaa? Scifissä puhutaan kyllä hyperavaruudesta, mutta tällä ei viitata siihen? Ei ole ruotsiksi sopivaa vastinetta, paitsi jos kyseessä on yksinkertaisesti hyperavaruus scifimielessä niin silloin "hyperrymd".

**Comment by mirmaid** [comment]
Termi on peräisin Michio Kakun kirjasta _Hyperavaruus_: "Tämä kirja käsittelee _hyperavaruuden teoria_ -nimistä tieteellistä vallankumousta". Termin lähteeksi Kaku antaa Heinz Pagelsin teoksen _Perfect symmetry: the search for the beginning of time_ (s. 324). Englanniksi _hyperspace theory_ tuo kyllä viitteitä Googlella, mutta varmaan tässä riittäisi myös _säieteoria_?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1452

**Comment by YSA-kokous** [comment]
Poistetaan, KÄ säieteoria.
