### ISSUE TITLE
leikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7159]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leikki](http://www.yso.fi/onto/ysa/Y96823) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastossa myös leikit, onko yhdistettävissä? Muuten täytynee luoda tarkenne leikille. Ks. YSO

#### Perustelut ehdotukselle   

Voidanko käyttää "leikit" myös silloin kun "leikki" on käytetty?

**Comment by mirmaid** [comment]
Mahdollisia varmaan sekä leikki KÄ _leikit_, että leikki KÄ _leikkiminen_. Tai _leikki (leikkiminen)_. Yksikkö kuulostaa ehkä paremmalta silloin kun puhutaan esim. nimenomaan vapaasta leikistä (esim. varhaiskasvatuksessa).

**Comment by YSA-kokous** [comment]
leikit
leikkiminen KT leikki (leikkiminen)
