### ISSUE TITLE
taudinkestävyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7160]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taudinkestävyys](http://www.yso.fi/onto/ysa/Y104553) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa KÄYTÄ resistenssi tai selvennettävissä esim. "taudinkestävyys (kasvit)" tms.? Jos tämä viittaa vain kasveihin? Muita ratkaisuja..? 

#### Perustelut ehdotukselle   

Ruotsiksi resistens=resistenssi+taudinkestävyys. Taudinkestävyys löytyy melko huonosti sanastoista. Jos tarkoitus on viitata kasvien taudinkestävyyteen niin Melindassa käytetty väärin, koska siellä on kuvailtu myös ihmisten vastustuskykyä (resistenssi) käsitteleviä teoksia paljon. Ruotsiksi voisi olla myös "sjukdomsresistens", mutta sekin vaatii tarkenteen, joten on ensin saatava selville mihin kaikkeen viittaa suomeksi. Huom. ryhmä 22, mutta se ei näytä pätevän Melindassa, eikä sekään ratkaise onko tämä vain kasveihin viittaava, vai mahdollisesti myös eläimiin..?

**Comment by mirmaid** [comment]
YSAn lisäksi termi on AFOssa ja HKLJ-luokituksessa viittausterminä kasvien lisäksi eläimiin. AFOssa on sekä taudinkestävyys että resistenssi. _Resistenssi_ on niin laajamerkityksinen termi, että ymmärrän tarpeen omalle termille kasvien taudinkestävyyden suhteen, mutta virheellistä käyttöä on paljon. YSAssa ja AFOssa on lisäksi _tuholaiskestävyys_ omana terminään.

**Comment by YSA-kokous** [comment]
Päivi tutkii, seuraava kokous.

**Comment by mirmaid** [comment]
YSOssa nyt siis:
- resistens (medicin) = resistenssi
- resistens (biologi) = taudinkestävyys
- skadedjursresistens = tuholaiskestävyys

**Comment by ilona-x** [comment]
YSA: 
**resistenssi** KT vastustuskyky
**immuniteetti** KT vastustuskyky

FinMeSH: 
**lääkeresistenssi** KT resistenssi http://www.yso.fi/onto/mesh/D004351
**immuniteetti** KT vastustuskyky http://www.yso.fi/onto/mesh/D007109
**sairauden vastustuskyky** http://www.yso.fi/onto/mesh/D060467

**Comment by PaiviLipsanen** [comment]
AFOn "taudinkestävyys" tarkoittaa nimenomaan kasvien taudinkestävyyttä. Googlaamalla "taudinkestävyys" tulee vain tähän liittyviä osumia. Melindassa on siis käytetty asiasanaa väärin lääketieteen yhteydessä. 
AFOn "tuholaiskestävyys" tarkoittaa myös nimenomaan kasvien tuholaiskestävyyttä. Tässä ei näytä olevan ongelmaa Melindassa.

**Comment by mirmaid** [comment]
Ehdotan, että lisätään nyt tarkenne _(kasvit)_, korjataan viitteet ja tutkitaan konversion jälkeen tarkemmin _resistenssi_-termin käyttöä. Ruotsiksi sillä on siis tarkenne _(medicin)_, käyttö suomeksi laajempaa. Mahdollista myös tehdä ruotsiksi _sjukdomsresistens (växter)_ ja poistaa tarkenne _resistens_-termiltä?

**Comment by mariaforsen** [comment]
Näin voidaan tehdä joo (tai "växters sjukdomsresistens")! Otetaan pois (medicin)

**Comment by YSA-kokous** [comment]
taudinkestävyys (kasvit)
