### ISSUE TITLE
dunkaanin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7163]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dunkaanin kieli 

#### Perustelut ehdotukselle   

.. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3192737 

**Ehdottajan organisaatio:** Helsingin yliopisto **Termiehdotus Fintossa:** [dunkaanin kieli](http://finto.fi/yse/fi/page/Y507163)

**Comment by mariaforsen** [comment]
Sv. dunganska ET dunganska språket
