### ISSUE TITLE
bežtan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7164]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bežtan kieli 

#### Perustelut ehdotukselle   

.. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3192765 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [bežtan kieli](http://finto.fi/yse/fi/page/Y507164)

**Comment by mariaforsen** [comment]
Sv. bezhta
