### ISSUE TITLE
alkoholi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7165]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[alkoholi](http://www.yso.fi/onto/ysa/Y94573) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenne (nautintoaineet) ja monikolle tarkenne (yhdisteet). Ovatko nämä tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by ilona-x** [comment]
alkoholit (orgaaniset yhdisteet)? 

Kielitoimiston sanakirja: **nautintoaine** yleisesti käytettäviä virkistäviä t. huumaavasti t. kiihottavasti vaikuttavia aineita. Nautintoaineita ovat mm. kahvi, tee, tupakka ja **alkoholijuomat**. 

Tuo alkoholi (nautintoaineet) kuulostaa jotenkin liian positiiviselta. Pitäisikö olla ennemminkin **alkoholi (päihteet)** kun sanastosta löytyy kuitenkin erikseen alkoholijuomat?

**Comment by YSA-kokous** [comment]
alkoholi (päihteet) jos soveltuu kuvailuissa
alkoholit (yhdisteet)

**Comment by satuniininen** [comment]
50 ensimmäisestä viittestä 37 käsitteli alkoholia ensisijaisesti päihteenä tai ongelmana (nuorten päihteiden käyttö, alkoholikuolemat, addiktion psykologia, sikiövauriot, vaikutukset terveyteen jne).
Muita näkökulmia oli alkoholipolitiikka (=myynti- ja anniskelurajoitukset), tullit & vientirajoitukset sekä erilaiset alkoholinkäyttöä tai alkoholikulttuuria käsittelelevät julkaisut, joissa näkökulma oli päihdekäyttöä laajempi. Juomatapoja käsitteleviin aineistoihin sanastossa on myös _alkoholijuomat_.

Kannatan muotoa **alkoholi (päihteet)**

**Comment by YSA-kokous** [comment]
alkoholi (päihteet)
