### ISSUE TITLE
arvostelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7166]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[arvostelut](http://www.yso.fi/onto/ysa/Y94716) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet arvostelu (toiminta) ja arvostelut (tuotokset). Ovatko nämä tarkenteet ok vai vaihdetaanko? 

#### Perustelut ehdotukselle   

Konversio

**Comment by YSA-kokous** [comment]
arvostelut
arvostelu (toiminta)
