### ISSUE TITLE
asemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7167]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asemat](http://www.yso.fi/onto/ysa/Y100855) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenne (paikat). YSOssa on myös yksiköllinen asema (yhteiskunnalliset ominaisuudet), joka on hierarkisoiva käsite. Onko tarkenne monikolle tarpeen/toimiva? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Käytetty Melindassa kerran siinä merkityksessä, johon yksikkö viittaa. Muuten käytetty myös muista kuin liikenteen asemista (rajavartioasemat, katsastusasemat, ruokinta-asemat). Jos haluttaisiin rajata liikenteeseen, tarkenteen pitää olla tarkempi kuin _(paikat)_.

**Comment by ilona-x** [comment]
Melindassa tosiaan käytetty monenlaisista asemista. Liikenteen asemien osalta näyttäisi siltä, että monissa tapauksissa tietueissa olisi riittänyt jokin tarkemmista asematyypeistä (**linja-autoasemat, rautatieasemat, lentoasemat, metroasemat**), osassa asemat-termin tilalla olisi pitänyt olla **asemarakennukset**, ja joissakin tapauksissa olisi riittänyt **matkakeskukset** tai **terminaalit**. 

Eli liikenteen asemien osalta jäin miettimään, onko tämä asemat kovin tarpeellinen termi, toki kätevä niissä tapauksissa, joissa käsitellään useamman tyyppisiä asemia, mutta toisaalta monissa tapauksissa kuvailut olisivat olleet osuvampia, jos olisi valittu tarkempi termi. :thinking: 

YSAssa olevia asemia:
http://finto.fi/ysa/fi/search?clang=fi&q=*asemat

**Comment by YSA-kokous** [comment]
Mahdollisesti poistetaan. Seuraava kokous.

Mahdollinen myös _asemat (liikennepaikat)_

**Comment by ilona-x** [comment]
asemat (liikennealueet)?

**Comment by ilona-x** [comment]
asemat (liikennepaikat/liikennealueet?) olisi tarpeen esim. seuraavissa Melinda-viitteissä:

- Asemanseutuhankkeiden hankehallinnan yleiskuvaus :solmupaikkojen kehittäminen osana liikennejärjestelmätyötä ja asemanseutujen suunnittelua
- Liityntäpysäköinnin kehittäminen pääkaupunkiseudulla.
- Lähtöpiste ja määränpää :lähteminen, saapuminen ja viestinvälitys paikkoina 
- Esteetön valaistus parantaa asemien ja muun joukkoliikenneympäristön käytettävyyttä.
- Esteetön valaistus ja selkeät kontrastit asema-alueilla
- Lähdön ja saapumisen paikat =Platser för ankomst och avfärd
- Seudullisen joukkoliikenteen toimintaedellytysten kehittämissuunnitelma 2009 
- Helsingin sosioekonominen erilaistuminen - tapauksena asemanseudut

Melindassa lisäksi muutama viite, joissa kyse **mittausasemista**:

- Kokonaisleijuma Espoossa, Kauniaisissa ja Vantaalla
- Toimintamallitarkastelu : jatkuvatoimiset vedenlaatuasemat

YSAssa on havaintoasemat, voidaanko ohjata mittausasemat KÄ havaintoasemat?
AFOssa on mittausasemat http://www.yso.fi/onto/afo/p518


Melindassa myös paljon sekalaisia asemia:

- Sjöbevakarna retirerar från havsbandet  (**merivartioasemat**)
- Avoimen yliopisto-opiskelun motiivit, **asema** ja merkitys opiskelijan elämässä
- Isokin navetta voi olla vähätöinen (**ruokinta-asemat**)
- Opetusvesiprosessin PC-valvomon ja **prosessiaseman** konfigurointi sekä dokumentointi 
- **Katsastusaseman** perustaminen 
- Khiam -raportti jättää vastaamatta keskeisiin kysymyksiin (**YK-asema**)
- Rauhaan pakottamisen, rauhan turvaamisen ja aseettoman sotilastarkkailun rajat hämärtymässä? :Khiamin **YK-asema** tuhoutui sodassa suoran hyökkäyksen tuloksena
- Panic station  (lautapeli)
- Hyytävä kuolema kintereillä (epävarma, ehkä **havaintoasemat**?)
- Galileon signaaleja Kuusamoon : Egnos Rims -**satelliittimaa-asema** parantaa ilmailun paikannustarkkuutta

**Comment by mirmaid** [comment]
Entä asemat (joukkoliikenne)?

**Comment by YSA-kokous** [comment]
mittausasemat KÄ havaintoasemat
asemat (joukkoliikenne)

**Comment by mirmaid** [comment]
Tarkenne (joukkoliikenne) osoittautui ongelmalliseksi lähemmin tutkittuna, joten päädyttiin jättämään YSOn nykyinen tarkenne (paikat). Varmistetaan vielä konversion jälkeen, onko tämä lopullinen tarkenne.

**Comment by mirmaid** [comment]
Nykyisellään siis käytettävissä sekä Kielitoimiston sanakirjan 1. että 2. merkityksistä (paitsi 2b):

1. määrälinjalla liikennöivien kulkuneuvojen pääte- t. pysähdyspaikka, vars. rautatieasema. _Pasilan (rautatie)asema. Linja-auto-, metro-, lentoasema. Tavara-asema. Lähtö-, pääteasema. Juna seisoo asemalla, saapuu asemalle._
2. erillinen virantoimitus-, tutkimus- tms. paikka. _Luotsi-, poliisiasema. Avaruus-, havaintoasema. Paloasema. Tutka-asema._
Erik.
a. radio-, televisioasema. _Lyhytaaltoasema. Ohjelma radioitiin kaikkien asemien kautta._
b. _tietotekn. Työasema._

**Comment by mirmaid** [comment]
YSOssa yläkäsitteenä _liikennealueet_, mutta alakäsitteenä _tutka-asemat_. Jos halutaan säilyttää laajassa merkityksessä, on syytä nostaa ylöspäin hierarkiassa.

Ehdotettu esim.
asemat (liikennealueet/liikennepaikat/liikenne)
poistetaan (otetaan tilalle asemanseudut?)
asema-alueet

**Comment by YSO-kokous** [comment]
Tarkennetaan käsitteen merkitys liikenteeseen soveltuvaksi. Tälle käytettäväksi termiksi **asemat (liikenne)**. Siirretään tutka-asemat toisaanne, kenties myös luotsiasemat.
Lisättäneen liikenneasemat-käsitteelle tarkentava määritelmä.

Keskustelu polveili sulkutarkenteen valinnan osalta. Asemanseudut, asema-alueet, liikenne olivat vaihtoehtoina. Sanastossa myös liikenneasemat.
