### ISSUE TITLE
bretonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7168]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[bretonit](http://www.yso.fi/onto/ysa/Y118931) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenne (eurooppalaiset), yksikölle bretoni (koirat). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by YSA-kokous** [comment]
bretoni (koirat)
bretonit (eurooppalaiset)

**Comment by mirmaid** [comment]
bretoni (koira) - yläkäsite on yksikkömuotoinen
bretonit (kansat) - ei aiheuta pohdintaa siitä, pitäisikö käyttää vain Euroopassa asuvista bretoneista
