### ISSUE TITLE
etiketti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7169]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[etiketti](http://www.yso.fi/onto/ysa/Y95126) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet etiketti (tapakulttuuri) ja etiketit (tuotokset). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Tuote-etiketti

**Comment by YSA-kokous** [comment]
etiketti (tapakulttuuri)
tuote-etiketit

**Comment by mariaforsen** [comment]
Sv.
-etikett (seder och bruk)
-produktetiketter
