### ISSUE TITLE
hallinto-oikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7170]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hallinto-oikeus](http://www.yso.fi/onto/ysa/Y95260) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet hallinto-oikeus (erikoisalat) ja hallinto-oikeudet (tuomioistuimet). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Hallinto-oikeuden yläkäsite on _julkisoikeus_.

**Comment by YSA-kokous** [comment]
hallinto-oikeudet
hallinto-oikeus (oikeudenala) (Tommi?)

**Comment by mariaforsen** [comment]
Sv. förvaltningsrätt (rättsområde)
