### ISSUE TITLE
henget

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7171]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[henget](http://www.yso.fi/onto/ysa/Y175349) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet henget (yliluonnolliset oliot) (LT yliluonnolliset olennot!) ja henki (filosofian käsitteet). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Eikö riittäisi _henki (filosofia)_?

**Comment by YSA-kokous** [comment]
henget
henki (filosofia)

**Comment by mariaforsen** [comment]
Sv. ande (filosofi)
