### ISSUE TITLE
itku

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7172]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itku](http://www.yso.fi/onto/ysa/Y101895) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet itku (viestintä) ja itkut (tuotokset). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Mahd. myös _itku (itkeminen)_?

**Comment by krinay** [comment]
Kannatan muotoa _itku (itkeminen)_ - vaikka ehkä yksin itkeskeleväkin viestii...
Itkut (tuotokset) tuntuu vähän hassulta, mutta parempaa tarkennetta taitaa olla vaikea keksiä. Itkut (itkuvirret) ei varmaan ole hyvä, kun on nimenomaan haluttu korvata vanha termi itkuvirret nykyään käytetyllä termillä itkut.

**Comment by YSA-kokous** [comment]
itkeminen
itkut
