### ISSUE TITLE
julistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7173]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[julistus](http://www.yso.fi/onto/ysa/Y164094) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet julistus (toiminta) ja julistukset (tuotokset). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Mahd. myös _julistus (julistaminen)_?

**Comment by YSA-kokous** [comment]
julistukset
julistaminen KT julistus
