### ISSUE TITLE
kaiverrus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7174]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kaiverrus](http://www.yso.fi/onto/ysa/Y102095) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet kaiverrus (toiminta) ja kaiverrukset (tuotokset). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Mahd. myös _kaiverrus (kaivertaminen)_?

**Comment by YSA-kokous** [comment]
kaiverrukset
kaiverrus (kaivertaminen) TAI kaivertaminen TAI kaiverrus (toiminta) (mikä soveltuu parhaiten viitteissä)

**Comment by satuniininen** [comment]
_Kaivertaminen_ näyttäisi istuvan viitteisiin ilman ongelmia.

**Comment by YSA-kokous** [comment]
kaivertaminen
