### ISSUE TITLE
kansa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7175]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansa](http://www.yso.fi/onto/ysa/Y95810) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet kansa (ilmiöt) ja kansat (väestöryhmät). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Mihin kielitoimiston sanakirjan neljästä merkityksistä kansa (ilmiöt) on tarkoitus viitata? 
Allärs: folket=kansa ("Folket betyder i olika sammanhang detsamma som ”folkets breda massa”, till skillnad från olika ”eliter”.") Eli hieman epäselvää kuinka hyvin vastine täsmää.

**Comment by mirmaid** [comment]
^ Ainakin tuossa merkityksessä yksikköä käytetty, eikä silloin ole korvattavissa monikolla. Eli Kielitoimiston sanakirja: 3. maalaisväestö, työväki, alemmat yhteiskuntaluokat, rahvas. _Tavallinen kansa. Kansan syvät rivit. Suoraan kansan keskuudesta noussut poliitikko._ Toisaalta käytetty myös ns. "kansan ideasta", jolloin usein käsitellään nationalismia, kansallista identitettiä jne. Näissä yhteyksissä mahd. korvattavissa muilla termeillä?

**Comment by ilona-x** [comment]
Olisiko kansa poistettavissa kokonaan tai ainakin rajattavissa yhteen monista merkityksistä, useissa viitteissä muuta aihetta kuvaavaa termistöä runsaasti, jolloin "kansa" tuntuu hieman täytesanalta kuvailussa.

Esimerkkejä Melinda-viitteistä:

- Culture shock! :a survival guide to customes and etiquette: Cuba 
- Ethnosymbolism and the dynamics of identity 
- Sodan henki :kaunis ja ruma talvisota 
- Explaining traditions :folk behavior in modern culture 
- Furstar och folk i Åbo 1812 
- Aidaton maanpäällinen taivas :Gerrard Winstanleyn englantilaisuus ja ehdotus kansakunnasta 1600-luvun puolenvälin Englannissa 
- Hyvinvointivaltion loppu? : vallanpitäjät, kansa ja vastavuoroisuus  
- Kansa äänessä :tekstityypit, retoriikka ja kulttuurinen tieto Kansanradiossa 
- Kansallisesta historiasta unohtunut säätykonflikti :kansallinen identiteetti, kansakoulu ja lukutaidon oppiminen 1800-luvun Suomessa.
- Kansanmusiikki liikkeessä.
- Explaining traditions :folk behavior in modern culture
- The idea of the people :  the right of self-determination, nationalism and the legitimacy of international law
- Myytit, uskomukset ja kansa : johdanto moderniin nationalismiin Suomessa 1809-1918


YSAsta löytyvää  termistöä:

- väestö ST kantaväestö, kaupunkiväestö, maaseutuväestö
- työläiset
- työväenluokka
- kansat
- kansalaiset
- kansallisuus
- asukkaat
- kansanelämä
- kansantavat
- kansankulttuuri
- kansanluonne
- kansanperinne
- kansallinen identiteetti

jne.

**Comment by LeKorsu** [comment]
kansa (rahvas) / folk (vanligt folk)???

**Comment by mariaforsen** [comment]
Ruotsiksi kansa on perinteisesti ollut folket, ja se lienee selkeä ruotsin osalta?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**kansa**
1. kulttuuriltaan ja us. myös hallinnoltaan ja kieleltään yhteen kuuluva ihmisryhmä; jnk valtion väestö. Suomen kansa. Germaaniset kansat. Itsenäinen kansa. Kulttuuri-, paimentolaiskansa. Koko kansan asia.
Erik. valtaa pitävien vastakohtana. Kansa nousi kapinaan.
2. jnk seudun asukkaat, asujaimisto, väki. Saariston kansa.
3. maalaisväestö, työväki, alemmat yhteiskuntaluokat, rahvas. Tavallinen kansa. Kansan syvät rivit. Suoraan kansan keskuudesta noussut poliitikko.
4. epälukuinen, suuri ihmisjoukko, väki, yleisö, ihmiset. Kirkko-, hääkansa. Tori oli kansaa mustanaan. Kansaan menevää musiikkia. Karttuisa on kansan käsi [ks. karttuisa] SP. Vanha kansa entisajan ihmiset, vanha ikäpolvi. 


http://tieteentermipankki.fi/wiki/Folkloristiikka:kansa
http://tieteentermipankki.fi/wiki/Kielitiede:kansa

http://tieteentermipankki.fi/wiki/Kielitiede:rahvas
http://tieteentermipankki.fi/wiki/Kulttuurintutkimus:rahvas

**Comment by krinay** [comment]
En kannata (eli vastustan 😉) yksiköllisen muodon poistamista. Se on ihan keskeinen käsite perinnetieteissä, vaikkakaan sen määritelmä ei ole selvä vaan vaihtelee eri aikoina ja eri tutkimuksissa/tutkijoilla. Määritelmää pohditaan tutkimuksissa usein.

**Comment by YSA-kokous** [comment]
kansa (kansanihmiset)
kansat

**Comment by mariaforsen** [comment]
Sv. 
folket 
folk
