### ISSUE TITLE
kansantanssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7176]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansantanssi](http://www.yso.fi/onto/ysa/Y117545) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet kansantanssi (taidelajit) ja kansantanssit (tanssit). Onko jako tarpeen / ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Kannatan yhdistämistä.

**Comment by mirmaid** [comment]
MUSAssa on _kansantanssit_. Kontratanssit nyt _kontratanssit (sävellykset)_? Lisäksi MUSAssa _latinalaistanssit_ ja _vanhat tanssit_, jotka YSAssa ilman tarkennetta, sekä _seuratanssit_ joka muutettiin YSAssa yksikköön.

**Comment by krinay** [comment]
Yksikkö- ja monikkomuodoille lienee periaatteessa samantapainen tarve kuin tanssin ja tanssien kohdalla. Ehkä käytännössä pärjättäisiin pelkällä monikolla. Harrastaako/opetteleeko/opiskeleeko ihminen kansantanssia vai kansantansseja?

**Comment by tpalonen** [comment]
Muusalaisilta ei ole tullut kommenttia tähän. Itse annan henkkoht ääneni käsitteiden yhdistämiselle.

**Comment by YSA-kokous** [comment]
kansantanssit KT kansantanssi
