### ISSUE TITLE
kilpailu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7177]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kilpailu](http://www.yso.fi/onto/ysa/Y96163) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet kilpailu (toiminta) ja kilpailut (tapahtumat). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
kilpailu (toiminta)
kilpailut

**Comment by mariaforsen** [comment]
Monikolliselta termiltä on jo poistettu tarkenne, kuten pitääkin, koska sitä ei voi varmaan ymmärtää väärin. 
Huom. konkurrens/kilpailua esiintyy myös esim. luonnossa, onko sille olemassa joku toinen termi?

**Comment by mirmaid** [comment]
Ks. myös https://github.com/NatLibFi/Finto-data/issues/969

**Comment by ilona-x** [comment]
YSOssa myös **kilpailutoiminta** http://www.yso.fi/onto/yso/p25281

**Comment by AuHo22** [comment]
_Huom. konkurrens/kilpailua esiintyy myös esim. luonnossa, onko sille olemassa joku toinen termi?_ -> luonnonvalinta?

**Comment by mirmaid** [comment]
Käytetty Melindassa n. 8000 kertaa. Toiminta-tarkenne ei siis tosiaan rajaa juuri millään tavalla, toki kilpailu on aina jonkinlaista toimintaa olipa sitten kyse taloudesta, luonnosta tai urheilusta. Tarkenne on nyt tarkoitettu erottelemaan tapahtuma-merkityksestä: kilpailu (toiminta) vs. kilpailut, kisat, mutta on vähän epäselvää, auttaako siihenkään: eukonkantokilpailuja käsittelevä aineisto olisi ok kuvailla käsitteillä kilpailut ja kilpailutoiminta, mutta ei kilpailu (toiminta).

Mahdollista siis lisätä tarkenne (talous) ja lähteä korjaamaan tuota 8000 settiä, mutta esim. tässä https://melinda.kansalliskirjasto.fi/byid/012258436 kyse on kyllä kilpailusta ihan kuten yrityksilläkin, (talous) vaan ei oikein toimi. 

https://melinda.kansalliskirjasto.fi/byid/011561306
https://melinda.kansalliskirjasto.fi/byid/011854447
https://melinda.kansalliskirjasto.fi/byid/009593472

Myös esim. https://melinda.kansalliskirjasto.fi/byid/009584847

**Comment by mariaforsen** [comment]
Kysymykselläni tarkoitin muuten että pitäisikö mahdollisesti lisätä ryhmiä kilpailu (toiminta)-termille, koska ainakin ruotsiksi tuo konkurrens käytetään varmaan helposti esim. eläinmaailmastakin. 

Hyvä että sanastossa on myös kilpailutoiminta joka viittaa sitten toivottavasti siihen että osallistutaan kilpailuihin jne. Käsitteenmuodostus ruotsiksi toimii nimittäin tässä tapauksessa niin että konkurrens käy kyllä kaikenlaisesta kilpailemisesta, mutta ei kilpailuihin osallistumisesta yms. vaan sille on sana tävling/tävlande. 

Eli tilanne on oikeastaan aika ok, paitsi että mahdollisesti tarvitaan uusi ohjaustermi: kilpailu (kilpailuihin osallistuminen) KÄYTÄ kilpailutoiminta ja/tai kilpailut?

**Comment by mirmaid** [comment]
Mun mielestäni suomeksi _kilpailu (toiminta)_ ei välttämättä rajaa pois kilpailuihin osallistumista, koska sen mieltää jopa enemmän olevan toimintaa kuin jonkun eläinten tai yritysten välisen kilpailun. Ja termit _kilpailutoiminta_ ja _kilpailu (toiminta)_ eivät tunnu ihan hirveän selkeästi viittaavan eri asioihin. 

Toiminta-tarkenne siis tuntuu enemmänkin sekoittavan kuin selkeyttävän merkitystä. Ruotsiksihan tässä on eri termit, joten tilanne on ihan erilainen. On kyllä todella hankala keksiä toimivaa tarkennetta, joka kattaisi kerralla kaiken, sekä talouden, että luonnossa tapahtuvan kilpailun, että vaikka sitten oppilaitosten välisen paremmuuskilpailun.

**Comment by mirmaid** [comment]
Onko muuten silloin kun puhutaan yliopistojen keskinäisestä kilpailusta (esim. houkuttelevina opiskelu- tai työpaikkoina, tai jossain "parhaat yliopistot" -listauksissa) termi ruotsiksi konkurrens (ei tävling)?

**Comment by mirmaid** [comment]
Jos kaikki konkurrens-merkityksen kilpailu halutaan pitää yhdessä (eli talous, luonto jne.), mutta rajata pois tävling-merkitys, tulee itselleni mieleen mahdollisina tarkenneyritelminä kilpailu (ilmiöt) tai kilpailu (prosessi). Ensimmäisessä on se vika, että sekään ei ehkä poissulje täysin ihmisten keskinäistä kilpailua, ja jälkimmäisessä se, että se saattaa kyllä poissulkea ihan kaiken olemalla niin epäselvä 😁.

**Comment by YSO-kokous** [comment]
**PÄÄTÖKSET**
Yhdistetään klpailutoiminta ja kilpailut, sitten poistetaan kilpailutoiminta 
Vaihdetaan sulkutarkenne:
kilpailu (toiminta) -> kilpailu (talous), poistetaan ohjaustermi "reilu peli"

**Comment by jtuohini** [comment]
Huomioksi myös kilpailu luonnossa: https://github.com/Finto-ehdotus/YSE/issues/10094!

**Comment by mirmaid** [comment]
Joudun harmi kyllä avaamaan tämän uudestaan. Melindassa on runsaasti aineistoa, johon ei sovi kilpailu (talous) (ainakaan aika lailla venyttämättä merkitystä), kilpailu (biologia) tai kilpailut. Korjattu nyt niin, että jäljelläolevista 100 ensimmäistä on viitteitä, joissa mikään vaihtoehdoista ei tuntunut ongelmattomalta.

**Comment by mirmaid** [comment]
Esimerkkejä ongelmatapauksista:

- [Population wars](https://melinda.kansalliskirjasto.fi/byid/013781680) - kilpailu (biologia) ihmisen yhteydessä? Entä laajemmin kilpailu resursseista, samaa jatkumoa...
- kilpailu liikunnassa/urheilussa, kun kyse ei ole nimenomaan kilpailuista? Esim. koululiikunnan yhteydessä toisinaan ok (_Kilpailu tappaa koululiikunnan_), mutta toisinaan sopii huonommin (_Kilpailullisuus koululiikunnassa kuudes- ja kahdeksasluokkalaisten kokemana_). Vrt. myös esim. https://melinda.kansalliskirjasto.fi/byid/007035282
- kilpailu esim. sotealalla ja media-alalla julkisen ja kaupallisen toiminnan välillä
- yliopistojen kilpailu rahoituksesta tai opiskelijoista tai keskinäisestä paremmuudesta

**Comment by mirmaid** [comment]
Tarvittaisiin siis

- uusi termi kattamaan tämä merkitys kilpailusta/kilpailullisuudesta laajemmin yhteiskunnassa JA/TAI
- tarkenne, joka sisällyttää kaupalliseen kilpailuun myös muuta kuin kilpailun yritystoiminnassa

**Comment by mirmaid** [comment]
Tarkenne (talous ja yhteiskunta) haukkaisi isomman setin kuin pelkkä (talous).

Toisaalta jos konkurrens käy laajasti myös ihmisten väliseen paremmuusmittelöön, ei tätä oikeastaan olisi tarvinnut jakaa ollenkaan, vaan tarkenteen olisi voinut lisätä käsitteelle kilpailut (kilpailut (tapahtumat) KT kilpailutoiminta)...

**Comment by mariaforsen** [comment]
Kuten aikaisemmin olenkin kirjoittanut _"konkurrens käy kyllä kaikenlaisesta kilpailemisesta, mutta ei kilpailuihin osallistumisesta yms. vaan sille on sana tävling/tävlande."_

Aiemmin mainitut tapaukset toimivat siis ruotsiksi seuraavalla tavalla:

-[Population wars](https://melinda.kansalliskirjasto.fi/byid/013781680) - kilpailu (biologia) ihmisen yhteydessä? --Entä laajemmin kilpailu resursseista, samaa jatkumoa... sv. konkurrens
-kilpailu liikunnassa/urheilussa, kun kyse ei ole nimenomaan kilpailuista? Esim. koululiikunnan yhteydessä toisinaan ok (Kilpailu tappaa koululiikunnan) mutta toisinaan sopii huonommin (Kilpailullisuus koululiikunnassa kuudes- ja kahdeksasluokkalaisten kokemana). Vrt. myös esim. -https://melinda.kansalliskirjasto.fi/byid/007035282 yleensä sv. konkurrens, mutta riippuu aineistosta jos joskus oikeasti onkin kilpailuista kyse...
-kilpailu esim. sotealalla ja media-alalla julkisen ja kaupallisen toiminnan välillä sv. konkurrens
-yliopistojen kilpailu rahoituksesta tai opiskelijoista tai keskinäisestä paremmuudesta sv. konkurrens

"Onko muuten silloin kun puhutaan yliopistojen keskinäisestä kilpailusta (esim. houkuttelevina opiskelu- tai työpaikkoina, tai jossain "parhaat yliopistot" -listauksissa) termi ruotsiksi konkurrens (ei tävling)?" Vastaus: sv. 
konkurrens on silloin oikea

Aikaisemmin ehdotettu kilpailu (ilmiö) + huomautus = konkurrens voisi olla ok ruotsin kannalta ainakin. Jos olisi sitten jonkinlainen ohjauskin, esim. kilpailu (kilpailuihin osallistuminen)  KÄYTÄ x

**Comment by mirmaid** [comment]
Tämä on kyllä malliesimerkki siitä, että päätetään jako liian nopeasti. Pitää jatkossa miettiä miten näitä korjauksia saisi paremmin testattua jo ennen kuin jakoja tehdään (vaikka jossain excelissä). _Kilpailu (ilmiö)_ ei erottele biologiasta tai taloudesta, eli jos jako säilytetään, tarvitaan edelleen tarkempia tarkenteita, tai sitten perutaan ja ajetaan tarkenteen poisto tai muutos nyt korjatuille n. 6000 viitteelle + korjaamattomille _kilpailut (toiminta)_ -käsitteille.

_(Ilmiö)_ on mahdollinen tarkenne jos ajatellaan, että on parempi tarkentaa yksikkö kuin monikko. Eli joko _kilpailu (ilmiö)_ vs. _kilpailut_, tai _kilpailu_ vs. _kilpailut (tapahtumat)_.

**Comment by mariaforsen** [comment]
Eli olisiko sitten "kilpailu (kilpailuihin osallistuminen)" KÄYTÄ kilpailut vai? Tämä kysymys on ruotsin kannalta melko ratkaiseva, koska "kilpailu (ilmiö)" olisi varmaankin konkurrens. Eli _ei_ tävling, ja onhan se tärkeää ettei sitä suomeksikaan sitten käytetä siitä kilpailuihin osallistumisesta.

**Comment by mirmaid** [comment]
^ Jotain tuon tyyppistä, ehkä jopa kilpailu (urheilukilpailut) KÄ kilpailut.

**Comment by mirmaid** [comment]
Ehdotan vielä ohjaustermejä
kilpailu (kilpailuissa) KÄ kilpailut
kilpailu (urheilukilpailuissa) KÄ kilpailut

Kilpailu (ilmiö) on siis mahdollinen kyllä suomeksi, mutta "ilmiö" on tarkenteena niin salliva, että se kyllä kattaa myös kilpailuissa kilpailemisen. Toki se on hiukan vieraannuttava noin ylipäätään ja voi herättää kuvailijan epäilykset.

**Comment by mirmaid** [comment]
Eli ratkaistaan nyt, kumpi:

A) 
kilpailut (tapahtumat) KT kilpailu (kilpailuissa), kilpailu (urheilukilpailuissa) sv. tävlingar
kilpailu KT kilpailu (ilmiö) sv. konkurrens

B)
kilpailut sv. tävlingar
kilpailu (ilmiö) sv. konkurrens

Voitte äänestää jo etukäteen, a = yläpeukku, b = alapeukku.

**Comment by mirmaid** [comment]
Jatkoksi varmistus: poistetaan varmaankin kilpailu (biologia) ja kilpailu (talous) myös vaihtoehdossa B?

**Comment by mariaforsen** [comment]
Pelkkä "kilpailu" ei varmaan voi olla pääterminä (ontologiaperiaatteiden vastainen)?
B-vaihtoehto on linjausten mukaan ok ja käyttäjille selkeämpi, eli kannatan sitä.

**Comment by mirmaid** [comment]
^ Mun mielestäni tätä nimenomaan tarkistettiin, että linjaukset eivät suoraan kiellä jättämästä ilman tarkennetta, vaan olennaista on merkityksen selkeys. YSOn omissa kehityslinjauksissa: _Kun samasta termistä on sekä yksikkö- että monikkomuotoinen käsite ontologiassa, lisätään käsitteille sulkutarkenteet, mikäli ne selventävät käsitteiden eroa. Lisäksi lisätään selventävä huomautus kummallekin käsitteelle_. 

En siis olisi tätä muuten ehdottanut. Siitä en ole varma, onko tämä ainoa tapaus jossa tarkenne olisi vain monikolla. Mutta siis oma ajatukseni on, että sellainen tarkenne kuin (ilmiö) ei välttämättä selvennä tuon yksikkömuotoisen termin merkitystä, vaan sen funktio olisi lähinnä herättää huomiota siihen, että ko. termissä on jotain outoa, mitä mallissa A on yritetty tehdä toisella tavalla. 

Kumpikaan näistä ei ole ihanteellinen ratkaisu, mutta koska tilanne on ollut pitkään kesken, olisi hyvä saada jonkinlainen ratkaisu, vaikka sitten huono. Voi olla, että malli B vähän paremmin poissulkee kilpailu-termin käytön ruotsin "tävlande"-sanan vastineena, mutta ei sekään toki täysin.

**Comment by YSO-kokous** [comment]
**Päätös**

Valitaan yllä esitetty vaihtoehto:

B)
kilpailut sv. tävlingar
kilpailu (ilmiö) sv. konkurrens

Ehdotetut ohjaustermit. Poistetaan _kilpailu (biologia)_ ja _kilpailu (talous)_, lisätään ohjaustermeiksi.
