### ISSUE TITLE
Kuu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7178]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuu](http://www.yso.fi/onto/ysa/Y109627) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet Kuu (Maan) ja kuut (taivaankappaleet). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
LCSH: 151 Moon; 150 Moons USE Satellites

**Comment by mirmaid** [comment]
Siirto paikkakäsitteeksi YSO-paikat-sanastoon koskisi myös planeettoja, aurinkoa, Linnunrataa sekä mahdollisesti avaruutta ja maailmankaikkeutta (entä multiversumia?).

**Comment by YSA-kokous** [comment]
Kuu (Maan)
kuut
