### ISSUE TITLE
käsityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7179]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[käsityö](http://www.yso.fi/onto/ysa/Y96656) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet käsityö (toiminta) ja käsityöt (objektit). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by satuniininen** [comment]
En pidä monikon sulkutarkennetta tarpeellisena. Käyttö näyttää varsin yhtenäiseltä, monikolla on kuvailtu pääsääntöisesti käsityöohjeita.

**Comment by YSA-kokous** [comment]
käsityöt 
käsityö (toiminta)
