### ISSUE TITLE
luokitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7180]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luokitus](http://www.yso.fi/onto/ysa/Y96999) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet luokitus (toiminta) ja luokitukset (tieto). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Mielestäni luokitukset (tieto) on selkeä ja jopa selkeämpi ilman tarkennetta. Monikossa se voi tuskin viitata mihinkään muuhun, mitä se siinä tapauksessa olisi?

**Comment by mirmaid** [comment]
Nykyisen hierarkian perusteella pitäisi olla _luokitus (sisällönkuvailu)_, mutta käytetty toki laajemmin. Mahd. myös esim. _luokitus (luokittelu)_, mutta soveltuu vaihtelevasti. Voidaan myös pitää YSOn nykyinen tarkenne ja tutkia myöhemmin vaatiiko muutoksia.

**Comment by YSA-kokous** [comment]
luokitukset
luokitus (toiminta)

**Comment by mirmaid** [comment]
Hierarkia?

**Comment by mariaforsen** [comment]
Sv. 
-klassifikationer
-klassifikation (verksamhet)

**Comment by mariaforsen** [comment]
Mielestäni nykyinen yläkäsite sisällönkuvailu on liian kapea, vrt. esim. https://termipankki.fi/tepa/fi/haku/luokitus Olisiko kuvailu tai kohdistuva toiminta parempi?
https://finto.fi/yso/fi/page/p38217

Luokitukset voisi olla YK yhteiskunnalliset objektit, missä on muita vastaavia, esim. indeksit, ks. https://finto.fi/yso/fi/page/p605

**Comment by mirmaid** [comment]
Nyt kun katsoo, niin lukuun ottamatta kirjastoja koskevia aineistoja, myös muoto _luokittelu_ sopisi. Tosin voi johtua siitäkin, ettei tunne kunkin alan termikäytäntöjä, mutta usein myös nimekkeissä puhutaan luokittelusta.

**Comment by jarmosaarikko** [comment]
luokitus (tominta) on siis verbi  KT luokittaminen, luokittelu, luokitus=  -- mutta nuo suluissa olevat lienevät substantiivejä?
substantiiveja YSOssa: luokitusjärjestelmät. luokituskaavat, luokat

KOTUS: [luokitus](https://www.kielitoimistonsanakirja.fi/#/luokitus) = [luokittelu](https://www.kielitoimistonsanakirja.fi/#/luokittelu)
TAIVUTUS: (rinn. luokittelu), luokittaminen; sen tulos, luokkajako, luokat, klassifikaatio.   esim. Puutavaran luokitus. Kuntien kalleusluokitus.   -- tässä luokitus näyttää substantiivilta!??

**Comment by fantsby-m** [comment]
Tuossa luokitukset-termissä ei ole YSOssa tarkennetta (tieto), toisin kuin muutosehdotuksessa lukee, vaan yläkäsite tieto?

**Comment by YSO-kokous** [comment]
YSO-ylläpitoryhmä pohtii onko tarvetta vaihtaa "luokitus (toiminta)" sulkutarkenteettomaan muotoon esim. "luokittelu" KT luokittaminen, luokitus.   Yläkäsite vaihdetaan pois sisällönkuvailusta
