### ISSUE TITLE
maatalousmaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7181]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maatalousmaa](http://www.yso.fi/onto/ysa/Y97213) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet maatalousmaa (alueet) ja maatalousmaat (valtiot). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Melindan käytön perusteella _maatalousmaat_-termin voisi poistaa.

**Comment by YSA-kokous** [comment]
Poistetaan maatalousmaat, yksikkö ei tarvitse tarkennetta.
