### ISSUE TITLE
muisti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7182]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muisti](http://www.yso.fi/onto/ysa/Y97523) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet muisti (kognitio) ja muistit (tietotekniikka). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by YSA-kokous** [comment]
muisti (kognitio)
muistit (tietotekniikka)
