### ISSUE TITLE
oikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7183]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oikeus](http://www.yso.fi/onto/ysa/Y103742) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet oikeus (oikeudenala) ja oikeudet (edut). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Jos on pelkkä "oikeudet" on riski olemassa että joku tulkitsee sitä tuomioistuimina yms.? Sen takia tarkenne on kai tässä tapauksessa tarpeen.

**Comment by YSA-kokous** [comment]
oikeus (oikeudenala)
oikeudet (edut)

**Comment by mirmaid** [comment]
(edut)-tarkenne kuulostaa vähän oudolta joidenkin alakäsitteiden kannalta (ihmisoikeudet, perusoikeudet jne. mutta myös anniskeluoikeudet)

**Comment by mirmaid** [comment]
Kävin läpi 200 ensimmäistä Melindan selaushaun n. 7900 _oikeudet_-viitteestä. Sikäli kuin nimekkeestä ja muista asiasanoista ym. voi päätellä, oikeudet ei esiintynyt tuomioistuin-merkityksessä. Sen sijaan (edut) tarkenteen lisääminen viitteissä, joissa aineisto käsitteli esim. rikoksen uhrin oikeuksia tuntui sen verran huonosti sopivalta, että ehdottaisin sulkutarkenteen sijasta (tarvittaessa) määritelmää ja mahdollisesti ohjaustermejä tähän ja muihin käsitteisiin tarpeen mukaan.

**Comment by YSA-kokous** [comment]
oikeudet ilman tarkennetta + soveltuvat ohjaustermit
