### ISSUE TITLE
ontologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7184]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ontologia](http://www.yso.fi/onto/ysa/Y97800) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet ontologia (filosofia) ja ontologiat (tiedonhallinta). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by satuniininen** [comment]
Kannatan sulkutarkennetta myös monikolliselle.

**Comment by YSA-kokous** [comment]
ontologia (filosofia)
ontologiat (tiedonhallinta)
