### ISSUE TITLE
paikallishistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7185]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[paikallishistoria](http://www.yso.fi/onto/ysa/Y106152) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet paikallishistoria (erikoisalat) ja paikallishistoriat (historiikit). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Entä _paikallishistoria (historia)_ tai _paikallishistoria (tieteet)_?

**Comment by krinay** [comment]
Kannatan mieluummin vaihtoehtoa _paikallishistoria (historia)_ kuin tarkennetta tieteet. Voiko termiä käyttää yleisemmässäkin merkityksessä kuin tieteenä tai erikoisalana? Vrt. Kielitoimiston sanakirjan esimerkki "Hyvä paikallishistorian tuntemus." En tiedä, onko sellaiselle tarvetta kuvailussa, mutta periaatteessa.

**Comment by YSA-kokous** [comment]
paikallishistoria (historia)
paikallishistoriat (historiikit)
