### ISSUE TITLE
pakkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7186]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pakkaus](http://www.yso.fi/onto/ysa/Y97942) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet pakkaus (toiminta) ja pakkaukset (objektit). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Tässä tapauksessa monikko on kai selkeä ilmankin tarkennetta, koska monikossa ei voi viitata muuhun kuin objekteihin?

**Comment by mirmaid** [comment]
_Pakkaus (toiminta)_ vai _pakkaus (pakkaaminen)_?

**Comment by ilona-x** [comment]
Voisiko olla **pakkaaminen** KT pakkaus (pakkaaminen)?

**Comment by YSA-kokous** [comment]
pakkaaminen KT pakkaus
pakkaukset

**Comment by mirmaid** [comment]
Pitäisikö pakkaus tietotekniikan yhteydessä erottaa? Vrt. myös kompressio (ryhmät 07 ja 43).

**Comment by ilona-x** [comment]
eli silloin olisi kyseessä https://fi.wikipedia.org/wiki/Tiedonpakkaus
LCSH: Data compression (Computer science) http://id.loc.gov/authorities/subjects/sh85035850

**Comment by mariaforsen** [comment]
Ruotsiksi se olisi datakomprimering/kompression
https://sv.wikipedia.org/wiki/Datakompression 
http://finto.fi/mesh/sv/page/D044962 (suomeksi tiedon pakkaus)
Eli joo se olisi hyvä erillisenä käsitteenä tai ainakin erotettuna "pakkaaminen" käsitteestä.

**Comment by mariaforsen** [comment]
Sv. edelleen
-packande
-förpackningar

**Comment by mirmaid** [comment]
Riittääkö _tiedonpakkaus_ KT pakkaus (tietotekniikka), kompressio (tietotekniikka)? Ei tarkennetta _pakkaaminen_-käsitteelle?

_Kompressiolta_ poistettaisiin ryhmä 43 (ja lisättäisiin 48), ehkä myös RT pakkaaminen? Vaatiiko muuta käsittelyä?

**Comment by tpalonen** [comment]
Anteeksi että sekoitan pakkaa. Mihin kaikkeen tuon kompressio-käsitteen olisi tarkoitus jatkossa soveltua? Kompressio on myös musiikkialalla käytetty termi ja viittaa siellä kahteen eri käsitteeseen:

1) Ensimmäinen merkitys on alisteinen tiedonpakkaus-käsitteelle (ks. https://en.wikipedia.org/wiki/Data_compression#Audio), eli audiodataa pakataan digitaalisesti pienempään muotoon kuten esim. mp3-tiedostoiksi. On siis tiedonpakkaus-käsitteen alatyyppi.
2) Toinen merkitys liittyy audiosignaalin käsittelyyn, tyypillisesti osana musiikin miksaus-/masterointiprosessia (ks. https://en.wikipedia.org/wiki/Dynamic_range_compression). Siinä audiosignaalin dynamiikkaa tasapäistetään eli hiljaisia "signaalikuoppia" ja voimakkaita "signaalihuippuja" tuodaan samalle volyymitasolle. Tästä vastaavaa laitetta kutsutaan kompressoriksi.

Melindasta kävi ilmi, että kompressio-käsitettä on käytetty muutama kerta musiikkiaineiston kuvailussa ja käyttö jakautuu suurin piirtein fifty-sixty näiden kahden merkityksen kesken. Sitä on käytetty myös videosignaalin yhteydessä, jossa yhteydessä kyse on käsittääkseni tiedonpakkauksesta pienempään kokoon (vrt. mp3). Tämä kompressio-ongelma olisi hyvä käsitellä vielä Muusa-ryhmän kanssa eli a) ovatko molemmat merkitykset tarpeellisia musiikkiaineiston kuvailussa ja b) jos kyllä, mikä olisi sopiva termi? 

Oma mielipiteeni: Optimaalista olisi, että YSOssa olisi vain yksi tiedonpakkaus-käsite, joka kattaisi myös audio- ja videodatan pakkaamisen. Dynaaminen kompressointi on kuitenkin asia erikseen eikä voida sisällyttää tiedonpakkaus-käsitteeseen.

Näissä Melinda-tietueissa käytetty kompressio-käsitettä äänisignaalin dynamiikkaan liittyen:
Bobby Owinsky: The mixing engineer’s handbook
Jaakko Vastapuu: Ensimmäiset 30 millisekuntia : alukkeet ja niiden muokkaus nykypäivän populaarimusiikin miksauksessa.

**Comment by YSO-kokous** [comment]
Odotetaan Muusan kantaa. Käsitellään sitten.

**Comment by MUUSA-kokous** [comment]
1. Tiedonpakkaus OK audiodatan pakkaamisessa.

2. Sopiva termi voisi olla "dynaaminen kompressointi".

**Comment by YSO-kokous** [comment]
Otetaan sanastoon käsite "tiedonpakkaus".
Tehdään uusi käsite-ehdotus "dynaaminen kompressointi".

**Comment by YSO-kokous** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7829

**Comment by mirmaid** [comment]
_Tiedonpakkaus_ lisätty, kesken vielä _kompressio_-käsitteen osalta.

**Comment by mirmaid** [comment]
_Kompressio_ on nyt ryhmissä 07 ja 43, mutta jälkimmäinen olisi varmaan nyt = _tiedonpakkaus_? Käytetty runsaasti tässä merkityksessä (korjattu nyt muotoon tiedonpakkaus), muuten useimmiten lääketieteen tai urheilun yhteydessä. Usein sopisi _kompressiovaatteet_, mutta löytyisikö jotain tarkennetta, joka sopisi sekä hoitoon, että urheiluun?

**Comment by mariaforsen** [comment]
Riittäisikö ohjaus kompressio (data tms.) KÄYTÄ tiedonpakkaus?

**Comment by tpalonen** [comment]
kompressio (vaatteet) KÄYTÄ kompressiovaatteet?
kompressio (urheiluvaatteet) KÄYTÄ kompressiovaatteet?

**Comment by ilona-x** [comment]
Näyttäisi tosiaan, että Melindan perusteella tarve olisi lähinnä painehoitoon liittyvissä aineistoissa ja toisaalta urheiluvaatteisiin liittyvissä aineistoissa.

FinMeSH: 
**painesidokset** http://www.yso.fi/onto/mesh/D058128
KT kompressiosidokset
KT kompressiosidos
KT painesidos

**puristussukat** http://www.yso.fi/onto/mesh/D053828
KT antiemboliasukat
KT antiemboliasukka
KT hoitosukat
KT hoitosukka
KT puristussukka
KT tukisukat
KT tukisukka

**Comment by ilona-x** [comment]
Eli nähdäkseni pelkälle "kompressio"-termille ei sellaisenaan olisi enää tarvetta, ainakaan Melindan perusteella, jos otettaisiin sopivat tarkemmat termit.

Pari kompressio-termillä kuvailtua aineistoa oli sellaisia, joissa korvaaminen onnistui termillä puristus.

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Compression_garment#Sportswear
https://en.wikipedia.org/wiki/Compression_stockings

**Comment by ilona-x** [comment]
Lääkinnällisessä käyttötarkoituksessa käytetään näköjään myös termiä **painevaatteet**. (esim. https://fi.wikipedia.org/wiki/Lymed)

**Comment by mirmaid** [comment]
Mutta ilmeisesti mitään yhtä termiä, joka kattaisi sekä varsinaisen hoidon, että urheilussa käytetyt kompressiovaatteet, ei löydy?

**Comment by ilona-x** [comment]
Lähinnä ongelma on se, että kompressiovaatteet ei sovi kaikkiin kompressio-viitteisiin, vaan tarvittaisiin ainakin tuo meshin painesidokset. Pari esimerkkiä Melindasta: 

- Kompressiosidos vähentää rintasyöpäpotilaan yläraajaturvotusta.
- Kroonisten haavojen hoito perusterveydenhuollossa 

Eli riittäisiköhän:
kompressiovaatteet KT painevaatteet
painesidokset

vai tarvitaanko erikseen vielä termi sukille vai laitetaanko KÄYTÄ kompressiovaatteet?

**Comment by mariaforsen** [comment]
Sv.
-kompressionskläder ET kompressionsstrumpor
-tryckförband  https://www.kielitoimistonsanakirja.fi/#/paineside
tryckbehandling, kompressionsbehandling

**Comment by tpalonen** [comment]
En kannata erillistä termiä sukille.

**Comment by mirmaid** [comment]
Yksi mahdollinen olisi _kompressiohoito_ kattamaan sekä sidokset että vaatteet kun kyse on lääketieteellisestä aineistosta. [Täällä](https://melinda.kansalliskirjasto.fi/byid/013470478) käytetty myös kompressiotuotteet, kompressiosidonta.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon kompressiovaatteet, ohjaustermiksi painevaatteet.
Otetaan sanastoon kompressiohoito.
