### ISSUE TITLE
pigmentti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7187]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pigmentti](http://www.yso.fi/onto/ysa/Y106705) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet pigmentti (biologia) ja pigmentit (materiaalit). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Ruotsiksi pigment (kemi), tehdään muutos > pigment (material) ?

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Pigmentti

**Comment by satuniininen** [comment]
Kielitoimiston sanakirja: 
1. biol. elävissä soluissa tav. pieninä jyväsinä esiintyvä väriaine.
2. maal. maalien, muovien, kosmeettisten aineiden ym. värjäykseen käytettäviä jauheita. Väripigmentti. 

väripigmentit ?
pigmentit (värjäys) ?
pigmentit (värijauheet) ?

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Biological_pigment - tosin suomenkielinen muoto varmaan yksiselitteinen, eikä sekoitu kasveista saataviin pigmentteihin.

_Pigmentit (värijauheet)_ olisi tarkin (ja sulkisi pois Vantablackin, joka ei ole pigmentti). Toisaalta _(värjäys)_ on ehkä sallivampi, ellei sitten vie ajatuksia liikaa käsityöhön?
https://en.wikipedia.org/wiki/Lake_pigment

**Comment by YSA-kokous** [comment]
pigmentti (biologia)
pigmentit (värijauheet)
