### ISSUE TITLE
poisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7188]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[poisto](http://www.yso.fi/onto/ysa/Y108757) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet poisto (muuttaminen) ja poistot (taloudelliset tuotokset). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Ruotsiksi poistot=avdrag -tärkeää siis että se todella viittaa talousasiaan (tai sitten > muu vastine). Itse asiassa jos tällä viitataan laskentatoimessa käytettävään termiin niin oikeampi vastine olisi varmaan avskrivningar? Avdrag on muutenkin monimerkityksinen.

**Comment by mirmaid** [comment]
Entä poisto > _poistaminen_?

**Comment by satuniininen** [comment]
poisto > poistaminen kuulostaisi luontevammalta kuin poisto (muuttaminen). 

Melindan mukaan eniten poistetaan ruumiinosia (hampaat, luomet, kasvaimet), tapetti- tai maalipintaa sekä epäpuhtauksia ilmasta/vedestä.

**Comment by mirmaid** [comment]
Lisäksi _poistot (talous)_ ja _kokoelmapoistot_?

**Comment by YSA-kokous** [comment]
poistaminen
poistot (talous)
kokoelmapoistot KT poistot (kokoelmatyö)

**Comment by mariaforsen** [comment]
Sv.
-borttagning
-avskrivningar (ekonomi) ET avdrag 
-utmönstringar ur samlingar ET gallringar
