### ISSUE TITLE
puhe

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7189]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puhe](http://www.yso.fi/onto/ysa/Y98278) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet puhe (ilmiöt) ja puheet (tuotokset). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Puhe (ilmiö) ei näytä kovin selkeältä, ks. Kielitoimiston sanakirja -se voisi varmaan yhtä viitata johonkin muuhun merkitykseen kuin ensimmäiseen? Toisaalta, mihin tällä oikein halutaan viitata, onko tässä kyseessä puhekyky?

https://fi.wikipedia.org/wiki/Puhe

**Comment by mirmaid** [comment]
_Puhe (puhuminen)_ ja _puheet_ ilman tarkennetta?

**Comment by YSA-kokous** [comment]
puhe (puhuminen) 
puheet ilman tarkennetta
