### ISSUE TITLE
puu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7190]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puu](http://www.yso.fi/onto/ysa/Y98331) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet puu (luonnonmateriaalit) ja puut (kasvit). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by YSA-kokous** [comment]
puu (luonnonmateriaalit)
puut (kasvit)
