### ISSUE TITLE
pyhä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7191]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pyhä](http://www.yso.fi/onto/ysa/Y112585) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet pyhä (uskonnolliset käsitteet) ja pyhät (pyhimykset). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Huomautus _pyhät_-termin yhteydessä: _Pyhimysten nimitys ortodoksisessa kirkossa_

**Comment by mirmaid** [comment]
pyhät KÄ pyhimykset?

Tosin ortodoksisen kirkon piirissä ilmeisesti hyvin tarkkaa, että nimitys on pyhä, ei pyhimys. Mahd. myös _pyhät (ortodoksinen kirkko)_ tai _pyhät (pyhimykset)_ tai jopa _pyhimykset ja pyhät_?

**Comment by mirmaid** [comment]
Tarvitaanko sekä pyhä että pyhyys? Tutkitaan konversion jälkeen.

**Comment by YSA-kokous** [comment]
pyhä (uskonnolliset käsitteet) 
pyhimykset ja pyhät

**Comment by mariaforsen** [comment]
Sv. 
-det heliga
-helgon

**Comment by mariaforsen** [comment]
Myös "pyhä" merkityksessä "ortodoksinen pyhimys" on uskonnollinen käsite.

**Comment by krinay** [comment]
Jos ei säilytetä molempia (pyhä ja pyhyys), kannatan termin pyhä säilyttämistä. Ainakin uskontotieteilijät käyttävät sitä yleisemmin, ks. esim.
https://melinda.kansalliskirjasto.fi/byid/000836436
https://melinda.kansalliskirjasto.fi/byid/002342252
https://melinda.kansalliskirjasto.fi/byid/003063471

 (Ortodoksisen kirkon pyhimystä merkitsevä pyhä on uskonnollinen käsite, mutta asiasanastossa se olisi monikossa. En näe suurta ongelmaa tarkenteissa.)

**Comment by mirmaid** [comment]
Niissä tietueissa, joissa on nyt käytetty termiä _pyhyys_ (mutta ei pyhä), ei muoto _pyhä (uskonnolliset käsitteet)_ välttämättä tuntuisi luontevalta (jos ei pohdita nimenomaan pyhän käsitettä).
https://melinda.kansalliskirjasto.fi/byid/013194422
https://melinda.kansalliskirjasto.fi/byid/009376930

**Comment by mariaforsen** [comment]
Siis ongelma on mielestäni se että "uskonnolliset käsitteet" ei ole tarpeeksi erotteleva, koska myös "pyhimykset" on uskonnollinen käsite. Ontologialinjausten mukaan tarkenne pitää olle erotteleva ja sillä tavalla että myös tavallinen käyttäjä joka ei ole perehtynyt sen enempää meidän periaatteisiin ymmärtää eron.

**Comment by mariaforsen** [comment]
Käytännön syistä pyhyys pääterminä palvelisi varmaan paremmin ja laajemmin kuin pyhä, ja haittaa siitä ratkaisusta ei kai olisi kun pyhä olisi kuitenkin korvattuna mukana. Vaikea kuvitella mikä tietue olisi sellainen että "pyhä" käytettäisiin, mutta siihen ei sopisi "pyhyys"? Sen sijaan tapauksia joissa "pyhä" ei sovi aivan varmasti on. Kaikissa yllä mainituissa tietueissakin pyhyys olisi aivan hyvä käyttää asiasanana (riippumatta siitä onko kirjan nimekkeessä mainittu "pyhä" tai ei).

**Comment by tpalonen** [comment]
Kannatan pyhyys-muotoa. Miten olisi lisäksi seuraavat ohjaustermit?

pyhä (pyhyys) KÄYTÄ pyhyys
pyhät (pyhimykset) KÄYTÄ pyhimykset ja pyhät

**Comment by mirmaid** [comment]
Nyt on jo ohjaustermi pyhät KÄ pyhimykset ja pyhät

**Comment by krinay** [comment]
Hankalaa! Tarkistin useita suomen kielen sanakirjoja. Pyhä löytyi jokaisesta, mutta pyhyys varsinaisena hakusanana vain osasta. Jäi vaikutelma (mutu), että pyhä on ikään kuin perusmuoto, selitteissä käytetään myös sanaa pyhyys. Samanlainen vaikutelma syntyy aihetta käsittelevää uskontotieteellistä ja perinnetieteellistä kirjallisuutta selaillessa (ks. aiemmat esimerkit). Myös Heikki Palvan ’Raamatun tietosanastossa’ on hakusanana vain pyhä, ei pyhyys.

Pikaisella Melindan selailulla en saanut sellaista käsitystä, että pyhyys olisi laajemmin käyttökelpoinen termi kuin pyhä. Tämä mutu kuitenkin vain tietueissa olevan tiedon perusteella, ehkä itse teoksissa on muita aspekteja.

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet pyhä ja pyhyys. Käytettäväksi termiksi valittiin äänestyksellä pyhyys. Ohjaustermiksi "pyhä (pyhyys)" tai pelkkä "pyhä". YSO-ylläpito päättää ohjaustermin.
