### ISSUE TITLE
radio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7192]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[radio](http://www.yso.fi/onto/ysa/Y98412) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet radio (joukkoviestimet) ja radiot (laitteet). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Televisiot samoin.

**Comment by mariaforsen** [comment]
Radiot ja televisiot selkeät ilmankin tarkennetta?

**Comment by LeKorsu** [comment]
Tarkenne monikkomuodossa olisi turvallisempi vaihtoehto. Jäin miettimään, että kuinka moni ei-kirjastoammattilainen voisi käyttää radio (joukkoviestimet) myös laitteista?

**Comment by YSA-kokous** [comment]
radio (joukkoviestimet), televisio (joukkoviestimet)
radiot (laitteet), televisiot (laitteet)
