### ISSUE TITLE
rakuuna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7193]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakuuna](http://www.yso.fi/onto/ysa/Y112509) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet rakuuna (maustekasvit) ja rakuunat (sotilaat). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Rakuunan taksonominen yläkäsite on _marunat_, eli rakuunat monikossa ei voi viitata kasveihin (paitsi kasviyksilöihin, mutta se olisi sisällönkuvailussa aika outo käyttötapa). Monikkoa ei ole Melindassa käytetty kertaakaan kasveista.

**Comment by YSA-kokous** [comment]
rakuuna (maustekasvit)
rakuunat (sotilaat)

**Comment by mariaforsen** [comment]
Sv.
-dragon (kryddväxter)
-dragoner (soldater)
