### ISSUE TITLE
ruoka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7194]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ruoka](http://www.yso.fi/onto/ysa/Y104151) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet ruoka (aine) ja ruoat (ruokalajit). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Ruoat=maträtter. Voisiko ruoat jopa olla KÄYTÄ ruokalajit?
https://fi.wikipedia.org/wiki/Ruokalaji
https://fi.wikipedia.org/wiki/Ruoka

**Comment by mirmaid** [comment]
^ Kuulostaisi hyvältä, mutta viitteissä toisinaan paremmin ruoat > ruoka.

**Comment by YSA-kokous** [comment]
ruoat KÄ ruokalajit
ruoka ilman tarkennetta
