### ISSUE TITLE
sirkus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7195]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sirkus](http://www.yso.fi/onto/ysa/Y106383) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet sirkus (taiteet) ja sirkukset (organisaatiot). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by krinay** [comment]
Voisiko olla ilman tarkenteita sirkustaide ja sirkukset.

**Comment by YSA-kokous** [comment]
sirkustaide ja sirkukset

**Comment by mariaforsen** [comment]
Sv.
-cirkus (konstarter)
-cirkusar
