### ISSUE TITLE
suola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7196]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suola](http://www.yso.fi/onto/ysa/Y103478) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet suola (mausteet) ja suolat (yhdisteet). Ovatko tarkenteet ok? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
https://github.com/NatLibFi/Finto-data/issues/967
Mauste on kai merkitykseltään liian kapea tarkenne.

**Comment by mirmaid** [comment]
Siinä tapauksessa käykö päätermiksi _ruokasuola_? Ei kyllä sovi kaikkiin viitteisiin, kuten ei myöskään _suola (mausteet)_. Tavallista ruokasuolaa käytetään laajasti ja ruoanvalmistuksessa/-tuotannossa voidaan käyttää suoloja, joita ei nimitetä ruokasuolaksi tai jotka poikkeavat siitä koostumukseltaan, (esim. _Valion Valsa-maitosuola tähyää isoille markkinoille_). Voiko näitä yhdistää vain suola KÄ _suolat_? Tai sitten _suolat_ ja _ruokasuola_, jolloin käyttö kyllä jossain määrin hajoaa?

**Comment by ilona-x** [comment]
suola (natriumkloridi) KT ruokasuola :smiley:

**Comment by YSA-kokous** [comment]
suola KÄ suolat
