### ISSUE TITLE
suutarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7197]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suutarit](http://www.yso.fi/onto/ysa/Y101921) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenne (käsityöläiset). Sanastossa myös suutari, jonka tarkenne on YSAssa (kala), YSOssa (särkikalat). 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Tarkenne särkikalat on YSOn periaatteiden mukainen, niitä emme kai muuta, ellemme muuta YSO-periaatetta ensin? 

"...sulkutarkenteeksi valitaan ensisijaisesti (jos mahdollista) termin yläkäsite ja noudatetaan yläkäsitteen muotoa -> esim. maantieto (oppiaineet). Jos yläkäsite ei riitä selventämään käsitteen merkitystä, valitaan tarkenteeksi aihealue, tieteenala tms."  
/https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSOn+kehityslinjaukset

**Comment by mirmaid** [comment]
YSOssa _kutojat_-käsitteellä on tarkenne _(ammatti)_ (YSAssa itseasiassa monikko!), yläkäsite _käsityöläiset_. _Sepät_-käsitteellä ei ole lainkaan tarkennetta vaikka sanastossa on myös _sepät (kovakuoriaiset)_.

**Comment by YSA-kokous** [comment]
suutari (särkikalat)
suutarit (ammatit), sepät (ammatit)

**Comment by mirmaid** [comment]
suutari (kala) > suutari (särkikalat) muutos päivittyy konversiossa
