### ISSUE TITLE
teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7198]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teoria](http://www.yso.fi/onto/ysa/Y108217) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet teoria (abstraktit objektit) ja teoriat (tuotokset). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Onko mahdollista että myös teoriat "tuotoksina" nähdään "abstrakteina objekteina"? Ymmärtääkö kuka tahansa kuvailija mitä näillä tarkenteilla haetaan? Onko sekä yksikkö että monikko-muoto aivan välttämättömiä? 

Ks. myös Kielitoimiston sanakirjaa -näillä tarkenteilla ei varmaan haeta siinä olevaa merkitysjakoa? 

Ks. myös MOT Gummerus New Finnish Dictionary, jos näillä haetaan siinä olevaa jakoa: 1 asian tai ilmiön (tieteellisesti) perusteltu selitys 2 käytännön vastakohdasta, niin silloin olisi varmaan selkeämpää laittaa teoria (käytännön vastakohta), teoriat (tuotokset)..?

**Comment by mirmaid** [comment]
Yhdistetään teoria KÄ _teoriat_, tarvittaessa otetaan _teoriaopinnot_ TAI _teoriaopetus_?

**Comment by YSA-kokous** [comment]
teoria KÄ teoriat
teoriaopetus (tai teoriaopinnot), jos tarvitaan
