### ISSUE TITLE
tiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7199]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tiede](http://www.yso.fi/onto/ysa/Y99459) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet tiede (ilmiöt) ja tieteet (erikoisalat). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
"Tieteet (erikoisalat)" ei kai ole selkeämpi kuin "tieteet"? (Ks. YSO-linjaukset: "HUOM! jos preflabel on yksilöivä, sulkutarkenne ei välttämätön erityisesti jos se ei selvennä käsitteen merkitystä"

MOT Gummerus Uusi suomen kielen sanakirja: tiede=järjestelmällinen ja kriittinen eri alojen ilmiöiden tutkiminen ja tästä tutkimuksesta saatujen yleispätevien tietojen kokonaisuus" -onko tarkoitus että tiede viittaa "tutkimiseen" ja tieteet "tietojen kokonaisuuksiin"? Molemmat tarpeen erillisinä termeinä?

**Comment by mirmaid** [comment]
LCSH: Sciences USE Science

**Comment by ilona-x** [comment]
Nyt KT-muotona tieteenalat, voisiko sen ottaa päätermiksi?

taide & taiteet YSOssa ilman tarkenteita, voisiko tieteen osalta olla sama ratkaisu?

taide & taiteet - ehdotettu yhdistämistä, käsittely siirretty konversion jälkeen https://github.com/Finto-ehdotus/YSE/issues/6700

**Comment by mariaforsen** [comment]
Sv. 
-vetenskap
-vetenskapsgrenar ET vetenskapsområden, discipliner, akademiska discipliner

**Comment by tpalonen** [comment]
Kannatan yhdistämistä. Jos selkeitä sulkutarkenteita ei löydetä niin se on minusta vahva signaali yhdistämisen puolesta. Kuten olen toisaalla sanonut, en kannata tällaisia linnunpelättimet vs linnunpelätin sinänsä -tyyppisiä kahtiajakoja sanastossa.

**Comment by ilona-x** [comment]
Melindassa: 
tieteet 711 + ketjut
tiede 4640 + ketjut

LCSH:n tiedejako on näköjään hieman erilainen kuin YSA/YSOssa, sillä siellä ohjataan natural science USE science http://id.loc.gov/authorities/subjects/sh85118553, joten esim. Humanities tai Library science ei tietenkään ole Sciencen alakäsitteinä. :smile:

**Comment by YSA-kokous** [comment]
tiede
tieteenalat KT tieteet
