### ISSUE TITLE
unet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7200]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[unet](http://www.yso.fi/onto/ysa/Y99887) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenne (mentaaliset objektit). Onko tarkenne tarpeen/hyvä? Sanastossa myös uni (lepotila). 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Onko tarkenne tarpeen monikkomuodolle? Entä unet (unennäkö)?

**Comment by mirmaid** [comment]
Monikkoa näyttäisi käytetyn johdonmukaisesti, suomeksi monikon käyttäminen viittaamaan kokoavasti erilaisiin unen vaiheisiin tai "nukkumisiin" ei ole kovin luontevaa (vrt. lasten päiväunet/lasten unet), joten tarkenne ei mielestäni tarpeellinen. Jos se kuitenkin halutaan, Marian ehdotus on parempi kuin nykyinen.

**Comment by YSA-kokous** [comment]
Ei tarkennetta
