### ISSUE TITLE
valo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7201]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valo](http://www.yso.fi/onto/ysa/Y100526) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet valo (sähkömagneettinen säteily) ja valot (tekniset objektit). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mariaforsen** [comment]
Allärs ljuskällor=valot

**Comment by mirmaid** [comment]
YSAssa myös _valaisimet_ ja _valaistus_. Lisäksi runsaasti muuta termistöä. Olisiko yhdistäminen mahdollista? Yksikön tarkenne ei ehkä tunnu aina toimivalta, esim. _Qualities of light : interfacing lightscapes in Eino Leino, Hella Wuolijoki, and Arvid Mörne_.

**Comment by ilona-x** [comment]
Olisiko yhdistäminen siis valo KÄYTÄ valot vai toisinpäin?

Jos valo poistuu, tuntuisi fysiikan alan teosten kuvailu jäljelle jäävillä termeillä hankalalta.
Ja jos taas valot poistuisi, niin mikä termi tulisi tilalle esimerkiksi autojen ja muiden kulkuneuvojen valoja käsitteleviin viitteisiin?

Voisiko olla valo (säteily) tai valo (fysiikka) ja monikko valot (valonlähteet)?

LCSH:ssa ja SAOssa näyttää olevan erikseen Ljus i konsten / Light in arts ja LCSH:ssa vielä Light and darkness in literature

**Comment by satuniininen** [comment]
Entä jos yhdistetään valot ja valaisimet. Tällöin yksikkö ei välttämättä vaatisi sulkutarkennetta. Eli käytettäviksi termeiksi tulisivat **valo** sekä **valot ja valaisimet**.

**Comment by mirmaid** [comment]
Valot KÄ _valo_ oli mun ajatukseni, lisäksi _valaisimet, lamput_ jne. _Valot ja valaisimet_ on kyllä sekin ok, tosin auton merkkivalot, ajovalot ym. on aika kaukana valaisinten muotoilua käsittelevästä, mutta toki myös lamput käy niihin molempiin.

**Comment by YSA-kokous** [comment]
valot KÄ valo
