### ISSUE TITLE
valtio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7202]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valtio](http://www.yso.fi/onto/ysa/Y100008) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet valtio (julkisyhteisöt) ja valtiot (alueelliset kokonaisuudet). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
Entä toimisikohan _valtio (valtio-oppi)_? Ja monikko ilman tarkennetta?

**Comment by LeKorsu** [comment]
Valtio (julkisyhteisöt) vaikuttaa silmissäni ja ajatuksissani selkeämmältä kuin valtio (valtio-oppi). Monikkoon ei mielestäni välttämättä tarvita tarkennetta.

**Comment by mirmaid** [comment]
valtio (valtio-oppi) jos soveltuu kuvailujen perusteella

**Comment by satuniininen** [comment]
Näyttää siltä, että osaan viitteistä sopisi sulkutarkenteeksi paremmin julkisyhteisöt (_Kunta työllisyydenhoitajana : työpakosta kokeiluihin_) ja osaan valtio-oppi (_Does war make states? : investigations of Charles Tilly’s historical sociology_). Jakauman määristä on vaikea sanoa mitään varmaa, sillä tietueita on hulppeat 8310 kpl. 

Sopisiko yleisluontoisempi sulkutarkenne, joka kattaisi molemmat merkitykset? esim:
valtio (hallinnolliset järjestelmät) TAI
valtio (hallinnolliset kokonaisuudet)

Näissä heikkoutena on se, että toki myös alueet ovat hallinnollisia kokonaisuuksia. Ehdotukset toimisivat parhaiten, mikäli myös monikolla olisi sulkutarkenne, esim _valtiot (alueelliset kokonaisuudet)_ vs _valtio (hallinnolliset kokonaisuudet)_.

**Comment by YSA-kokous** [comment]
valtio (instituutio)

**Comment by mariaforsen** [comment]
Sv. 
-staten  
-stater
