### ISSUE TITLE
yksikkö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7203]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yksikkö](http://www.yso.fi/onto/ysa/Y104519) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa lisätty tarkenteet yksikkö (kielelliset objektit) ja yksiköt (organisaatiot). Ovatko tarkenteet ok? Onko monikon tarkenne tarpeen? 

#### Perustelut ehdotukselle   

Konversio

**Comment by mirmaid** [comment]
YSOssa on käytetty 18 kertaa tarkennetta _(kielitiede)_, ja vain tämän yhden kerran tarkennetta _(kielelliset objektit)_.

_(Organisaatiot)_ ei sovellu aina, käytetty myös Kielitoimiston sanakirjan merkityksessä 1. suureen mittana käytettävä sovittu arvo, mitta(yksikkö).

**Comment by mirmaid** [comment]
Toimintayksiköt?

**Comment by ilona-x** [comment]
Suurimpaan osaan Melinda-viitteitä (yhteensä 114 viitettä + ketjut) kävisi tarkenteeksi organisaatiot. Ainoastaan seuraavat ovat tuota "suureen mittana käytettävä sovittu arvo, mitta(yksikkö)."-merkitystä:

- Storheter och enheter : akustiska och optiska subjektiva och objektiva storheter och enheter 
- Kaavasto : matematiikan, fysiikan, mekaniikan ja lujuusopin peruskaavoja 
- Kemian laskut laboratoriossa
- HbA1C:n yksikkö muuttuu - oletko valmis?
- Technical pocket guide 
- Yksikön muuttuessa pienempään pilkku siirtyy oikealle - vai siirtyykö?

Voisiko näissä korvata YSAsta löytyvällä **mittayksiköt**-termillä? http://www.yso.fi/onto/ysa/Y103538


Ja vielä yksi viite, johon ei käy organisaatiot-tarkenne:

- Kuljetusyksikön käyttöönoton vaikutukset paperivarastoon 

LIIKO: **kuljetusyksiköt**  http://www.yso.fi/onto/mero/m9102

**Comment by YSA-kokous** [comment]
yksikkö (kielitiede)
yksiköt (organisaatiot)
