### ISSUE TITLE
julisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7204]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[julisteet](http://www.yso.fi/onto/ysa/Y101967) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termi myös slm-sanastoon (en pystynyt ehdottamaan slm-sanastoon "Ehdota uutta käsitettä" -linkin kautta, koska termi on YSO/YSA-termi). Samalla voisi laittaa mainokset, posterit?
On teoksen muoto. 

#### Perustelut ehdotukselle   

Kirjastoissa kuvaillaan myös mainosjulistetia, ks. esim. https://eepos.finna.fi/Record/eepos.2291755#details 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7018

**Comment by mirmaid** [comment]
Julisteet ok / SLM:
