### ISSUE TITLE
queer-elokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7205]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

queer-elokuvat 

#### Ehdotettu termi ruotsiksi   

queerfilmer? 

#### Ehdotettu termi englanniksi   

queer films? 

#### Vaihtoehtoiset termit ja ilmaisut   

sateenkaarielokuvat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elokuvat](http://www.yso.fi/onto/yso/p1235) 

#### Vastaava käsite muussa sanastossa   

British library : queer film 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Tarkoitusta täsmentävä selite   

vrt. queer-kirjallisuus 

#### Perustelut ehdotukselle   

Tarvitaan myös (varsinkin) slm:ssä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Call me by your name (elokuvan perustuu samannimiseen kirjaan, jonka kuvailussa on käytetty asiasanaa queer-kirjallisuus), sateenkaariperheistä kertovat elokuvat (esim. The kids are all right.) 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [queer-elokuvat](http://finto.fi/yse/fi/page/Y507205)

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
