### ISSUE TITLE
piirustus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7206]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[piirustus](http://www.yso.fi/onto/ysa/Y98123) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selvennettävä/jaettava 

#### Perustelut ehdotukselle   

Viittaa piirtämiseen? Onko se sitten selkeämpi muoto? Tosin sekin on ruotsin osalta ongelmallinen, koska ruotsiksi piirustus=teckning (taiteelliset yms.) vs. ritning (suunnittelu ja teknisempi). 

Vrt. https://github.com/Finto-ehdotus/YSE/issues/5147

**Comment by mariaforsen** [comment]
Sanastossa nyt muutosten jälkeen myös piirustukset (taide) + tekniset piirustukset. Olisiko syytä tehdä vastaavalla tavalla tämän kohdalla: 
-piirtäminen/piirustus (taide)=teckning (konstnärlig aktivitet)
-tekninen piirtäminen/tekninen piirustus (toiminta) -on jo sanastossa mutta muodossa "tekninen piirustus".

Sanastossa on tosin myös piirustustaide, miten se sitten eroaisi piirustus (taide)-termistä..?

**Comment by AuHo22** [comment]
Piirustustaide (teckningskonst) on jo eri asia, ja esimerkiksi näyttelyjulkaisuja taidenäyttelyistä kuvaillaan, joissa esitellään tunnettujen taiteilijoiden piirroksia. Mielestäni se täytyy kyetä erottamaan piirustusharrastuksesta, joihin sitten on jo ihan piirustusoppaita.

**Comment by mirmaid** [comment]
_Piirtäminen (taide)_ olisi varmaan selkein?

**Comment by YSO-kokous** [comment]
Päätettiin ottaa käytettäväksi termimuodoksi "piirtäminen (taide)". Ohjaustermiksi "piirustus (taide)".
