### ISSUE TITLE
jätelämpö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7207]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jätelämpö](http://www.yso.fi/onto/ysa/Y95696) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

voisiko yhdistää jätelämpö & hukkalämpö?
hukkalämpö KT jätelämpö
Melinda: 
jätelämpö x 61
hukkalämpö x 100 

#### Perustelut ehdotukselle   

http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:hukkal%C3%A4mp%C3%B6
http://www.tsk.fi/tepa/fi/haku/j%C3%A4tel%C3%A4mp%C3%B6
http://www.tsk.fi/tepa/fi/haku/hukkal%C3%A4mp%C3%B6

YSAssa näiden lisäksi lämpöhäviö
http://www.tsk.fi/tepa/fi/haku/l%C3%A4mp%C3%B6h%C3%A4vi%C3%B6 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 

jätelämpö: tekn. _Voimalan jätelämmön käyttö kaukolämmitykseen._
hukkalämpö: hukkaan menevä lämpö.

**Comment by ilona-x** [comment]
**fi jätelämpö : sv spillvärme : en waste heat**

määritelmä
tähdelämpö, jota ei voi tai kannata hyödyntää

huomautus
Hyödyntämisen esteenä voi olla esimerkiksi liian alhainen lämpötila tai se, että lämpö on sitoutunut liian likaiseen aineeseen.

**fi        hukkalämpö**

määritelmä
tähdelämpö, joka voidaan ottaa talteen

**fi tähdelämpö : sv restvärme : en residual heat**

määritelmä
lämpöenergian käytössä hyödyntämättä jäänyt lämpö

huomautus
Tähdelämpöä on esimerkiksi ilmanvaihdon poistoilmaan sitoutunut lämpö.

Lähde: Energiasanasto (TSK 16, **1989**)

**Comment by mariaforsen** [comment]
Yllä olevassa lienee virhe? Kielitoimiston sanakirja näyttää loogisemmalta. 
Hukkalämpö=spillvärme
Sv. spillvärme, värmespill > muutos/yhdistäminen tarvitaan

**Comment by ilona-x** [comment]
hukkalämpö KT jätelämpö olisi varmaan turvallisempi valinta, sillä Melindassa jätelämpöä on käytetty myös jätteiden hyödyntämistä energiantuotannossa käsittelevisssä viitteissä 🙄 :

- Waste-to-energy : advanced cycles and new design concepts for efficient power plants
- Garderobi : harkitse, korjaa & kierrätä.
- Waste to energy conversion technology

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet.
jätelämpö KÄYTÄ hukkalämpö

**Comment by mariaforsen** [comment]
Entä tähdelämpö, olisiko se KT? https://termipankki.fi/tepa/fi/haku/restv%C3%A4rme
