### ISSUE TITLE
instrumentaali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7210]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

instrumentaali 

#### Ehdotettu termi englanniksi   

Instrumental case 

#### Ehdotettu termi ruotsiksi   

Instrumentalis 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/Instrumentaali :  

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Tarkoitusta täsmentävä selite   

Wikipedia: Instrumentaali on sijamuoto, joka ilmaisee, että substantiivi on väline, jolla subjekti suorittaa tekemisen. Substantiivi voi olla joko konkreettinen esine tai abstrakti käsite.

Esimerkiksi latinan lauseessa librum stylo scripsi substantiivin taivutus ilmaisee sen instrumentaalisuuden – nominatiivi stylus muuttuu ablatiiviksi stylo. Koska suomen kielessä ei ole instrumentaalia, se käännetään usein käyttämällä adessiivia: Kirjoitin kirjan kynällä.

Instrumentaalia käytetään ainakin muinaisenglannissa, georgiassa, sanskritissa, tamilissa sekä useissa balttilaisissa ja slaavilaisissa kielissä. Unkarin kielessä sijamuodon nimi on instrumentaali-komitatiivi. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa eikä termiä löydy kielitieteen asiasanastostakaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Prolatiivi ja instrumentaali : suomen -(i)tse ja -teitse kieliopin ja leksikon välimailla (ARTO, bib-id 2519345) 

**Ehdottajan organisaatio:** HY:n kirjasto **Termiehdotus Fintossa:** [instrumentaali](http://finto.fi/yse/fi/page/Y507210)

**Comment by mirmaid** [comment]
6 viitettä Melindassa. Onko mahdollista sekoittua soitinmusiikkiin?

**Comment by mariaforsen** [comment]
Sv. instrumentalis

**Comment by tpalonen** [comment]
Tämä on kyllä helppo sekoittaa instrumentaalimusiikkiin. Sulkutarkenne olisi hyvä. Olisiko esim. "instrumentaali (sijamuodot/kieli/kielitiede)"?

**Comment by YSA-kokous** [comment]
instrumentaali (sijamuodot)
