### ISSUE TITLE
suojelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7211]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suojelu](http://www.yso.fi/onto/ysa/Y107075) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastossa myös suojaus, miten nämä eroavat tarkalleen? 

#### Perustelut ehdotukselle   

Ruotsiksi tarvitaan selvempiä tarkenteita, mutta sitä varten täytyy tietää mihin tarkalleen viittaa.
Nyt skyddande, skydd (åtgärder) 
Ks. ryhmät.

**Comment by jarmosaarikko** [comment]
Suojaus lienee eräänlainen käsittely (vaatii yleensä jonkun välineen)  ja suojelu eräänlaista turvaamista (vaatii yleensä päätöksiä ei aina käsin kosketeltavaa)? Molempien tavoitteena olomuodon tai -tilan säilytys.   
Suojaus käsitteellä saisi mielellään olla  olla RT suojaimet

**Comment by YSO-kokous** [comment]
Käsitellään myöhemmässä kokouksessa. Kartotetaan esimerkkejä suojauksen ja suojelun tapauksista, joissa ei ole tarkempaa käsitettä tarjolla (rakennussuojelu, luonnonsuojelu tms). Mietitään tämän pohjalta, löytyisikö ruotsiksi sulkutarkennetta, joka selventäisi näissä tapauksissa.

**Comment by ilona-x** [comment]
Päätetty kartoittaa tilannetta ilmeisesti Melindasta. Näitä molempia on käytetty todella paljon, joten kattavan kuvan saaminen on työlästä.

Melinda:
suojaus x 2275
suojelu x 6733

**Comment by ilona-x** [comment]
Melinda-komentohaku lausekkeella + valittuna Fraasihakuna **Kyllä** :
WSU=suojelu NOT (WSU=luonnonsuojelu OR rakennussuojelu OR metsiensuojelu OR soidensuojelu OR ympäristönsuojelu OR eläinsuojelu OR kasvinsuojelu OR metsänsuojelu OR ilmansuojelu OR maisemansuojelu OR meriensuojelu OR rakennussuojelu OR vesiensuojelu OR työsuojelu OR eläimistön suojelu OR lajiensuojelu OR väestönsuojelu OR todistajansuojelu OR lastensuojelu) NOT WSU=kaunokirjallisuus NOT WSU=jännityskirjallisuus

Tulosjoukossa mukana edelleen fiktioaineistoa ja sellaisia viitteitä, joissa suojelu ei ole YSO-terminä, mutta tuosta on vähän helpompi selata käyttöä, jossa ei ole käytetty tarkempia termejä. Viitteissä on paljon sellaisia, joihin olisi tarjolla tarkempi termi.

Joitain käyttötapauksia, joihin ei ole tarkempaat termiä tarjolla:
suojelu + kulttuuriperintö = 891 viitettä (YSOssa on kyllä näihin mahdollisesti sopiva **kulttuurihistorialliset suojelukohteet**)

- https://tieteentermipankki.fi/wiki/Oikeustiede:kulttuuriperint%C3%B6_ja_sen_suojelu
- SAO: Kulturarvsskydd https://id.kb.se/term/sao/Kulturarvsskydd

suojelu + muinaisjäännökset = 379 viitettä

suojelu + pakolaiset = 101 viitettä
suojelu + turvapaikanhakijat = 87 viitettä

suojelu + siviiliväestö = 61 viitettä

- SAO: Skydd av civilbefolkning  https://id.kb.se/term/sao/Skydd%20av%20civilbefolkning


---

sekalaisia suojelu-termin käyttötapauksia: 

Jumala huolehtii / David Wilkerson ; [kääntäjä: Irmeli Helin].
https://melinda.kansalliskirjasto.fi/byid/000212088

Suojelu on paras oppi koiralle ja ihmiselle ; käännös: Taru Klén.
https://melinda.kansalliskirjasto.fi/byid/012606298

On the protection of foreign investment in Finland / Antti Kahri ; revised by Patrick Lindgren.
https://melinda.kansalliskirjasto.fi/byid/001026883

Ohjeet historiallisesti arvokkaiden urkujen suojelusta / [Kirkon urkutoimikunnan suojeluohjetyöryhmä].
https://melinda.kansalliskirjasto.fi/byid/001886326

Wettlauf mit der Zeit : Bestandserhaltung in wissenschaftlichen Bibliotheken / red.: Andreas Mälck, Leonhard Penzold.
https://melinda.kansalliskirjasto.fi/byid/000184733

**Comment by ilona-x** [comment]
**suojaus**-termiä käytetty Melindassa paljon ja hyvin erilaisissa yhteyksissä.

Melinda: 
suojaus + tietosuoja = 375 viitettä
suojaus + tietoturva = 532 viitettä
suojaus + salaus = 132 viitettä
suojaus + salakirjoitus = 60 viitettä
suojaus + kryptografia = 54 viitettä

suojaus + aurinko = 144 viitettä
suojaus + ultraviolettisäteily = 116 viitettä

suojaus + ukkossuojaus = 40 viitettä

-----

suojaus-termin käyttötapauksia:

- Suojarekisteröinnistä turvaa arvokkaille käyttötavaroille.
- AMKA-verkon sulakesuojaus ja näiden käytännön ratkaisuja.
- Aurinkosuojaus : aurinkosuojauksen suunnittelu kestävän kehityksen mukaisiin rakennuksiin 
- ISPS-koden; Åsikter om skyddskraven på finska fartyg och deras inverkan på arbetsbördan
- Tś̆ernobyl tänään.
- Voiteita ja muuta suojausta. (pakkanen)
- Merirosvoja näkyvissä! :ruoka-apua ei saada perille Somaliaan : EU:n sotalaivat suojaavat avustuskuljetuksia merirosvoilta, mutta maissa odottavat uudet varkaat.
- Formal and informal mechanisms for knowledge protection and sharing
- Suojaa vaurioilta. (Koristekasvien talvisuojaus)
- Sähköä ja suojaa : Magellan ToughCase -suojakotelo.
- Antaa paistaa! :markiisit 
- Värdefulla plantor kan behöva skydd. (taimet)
- Paloturvallisuus rakennuksen korjaustyön aikana : rikosten ja vuotovahinkojen torjunta 
- Säteilytaso alemmaksi maalilla.
- Radonremontti parantaa sisäilman.
- Lattiat kuntoon säännöllisellä siivouksella.
- Vain timantit ovat ikuisia : tiilikaton huolto.
- Näe kesä paremmin. (aurinkolasit, silmät, suojaus)
- Puutuotteiden ja -rakenteiden kemiallinen suojaus ja suojauksen markkinapotentiaali  (tietueessa myös palosuojaus)
- Varmista, että talosi selviää kaatosateista.
- Onko vaatteesi suojattu?. (Tekstiilituholaisilta suojautuminen.)
- Nimisuoja käyttöön laadukkaille pohjoisen porotuotteille.
- Sähköä katkoitta : ups-laitteet. (ylijännitesuojat ; tietueessa myös ukkossuojaus)
- Sjöfartsskyddsföreskrifter : ISPS-koden och anslutande lagstiftning 
- Käsikirja rakennusten sähköasennuksista

**Comment by ilona-x** [comment]
Olisikohan tätäkin mahdollista lähteä edistämään korjaamalla viitteitä siitä huolimatta, että korjattavat setit ovat suuria. 🤔  

Ainakin suojelu-setissä vaikuttaisi olevan paljon sellaista, johon olisi mahdollista saada suojelu-termin tilalle tarkempi termi.

Ja jos halutaan, niin SAOsta löytyvät kultturiperinnön suojelu (kulturarvsskydd) ja siviiliväestön suojelu (skydd av civilbefolkning) voisivat olla mahdollisia uusia termejä? Tai sitten tuo siviiliväestön suojelu mahdollisesti ohjaustermiksi väestönsuojelulle?

**Comment by mariaforsen** [comment]
Siviiliväestön suojelu olisi varmaan ohjaustermi väestönsuojelulle, muuten ne olisivat varmaan aika päällekkäisiä.

**Comment by mariaforsen** [comment]
Eikö siviiliväestön suojelu ole aika päälläkkäinen väestönsuojelun kanssa? Kultturiperinnön suojelu voisi kyllä olla hyvä erillisenä käsitteenä.

**Comment by mirmaid** [comment]
Suojelun tai suojauksen poistaminen ei ratkaise vielä ongelmaa, jos ei molempia poisteta (9008 viitettä :sweat:), jos jompikumpi jää, jäljellejäävä suomenkielinen termi tulisi kaikkiin tietueisiin, ja suomeksi tosiaan muinaisjäännöksen suojelu ja suojaus ovat kaksi eri toimenpidettä.

Eli pitäisi joko yhdistää suomeksi "suojelu ja suojaus", tai jakaa ruotsiksi tarkenteilla, tai sitten tosiaan poistaa molemmat. Toki siis voidaan tehdä niinkin, että korjataan ensin pois kaikki, mille on olemassa tarkempi termi, ja sitten vasta mietitään jäljellejäävän setin valossa, mitä tarkenteita voisi käyttää ruotsiksi, mutta ehkä voisi ensin yrittää vielä löytää tarkenteita ylläolevan selvityksen pohjalta.

**Comment by mirmaid** [comment]
**Suojelussa** siis pyritään päätöksin ja sopimuksin takaamaan jonkin (eläinlajin, muinaisjäännöksen, maiseman, väestön) säilyminen, turvallisuus tai hyvinvointi. 

**Suojauksessa** taas pyritään jollakin välineellä, aineella tai tekniikalla estämään jonkin vahingoittuminen tai varastaminen.

**Comment by mariaforsen** [comment]
Olisiko yksi vaihtoehto myös ettei poistettaisi molempia vaan jätettäisiin suojelu KT suojaus? Suojeluhan on paljon enemmän käytetty (6784) ja suojaus 2273. Noin laajoilla merkityskentillä lienee mahdotonta keksiä mahdollisia tarkenteita ruotsiksi?

**Comment by mirmaid** [comment]
^ Mutta ei kyllä käy samoissa yhteyksissä, esim. nyt koneeni ilmoittaa, että netti on "yhdistetty, suojattu", mutta ei kyllä voisi olla "suojeltu" :slightly_smiling_face: (silloin mun nettiyhteydestäni olisi tehty jokin suojelupäätös).

**Comment by YSO-kokous** [comment]
PÄÄTÖS
pidetään molemmat käsitteet, mutta etsitään tarkemmin rajaavia sulkutarkenteita osajoukoille.

**Comment by mirmaid** [comment]
Kävisiköhän ainakin osaan _suojaus_-aineistoa jokin "tekniikka" -tyyppinen tarkenne? Ja jos olisi ruotsiksi vastaava niin saataisiinko jonkinlainen setti katettua sillä?

Laitan nyt tähän muistiin, vaikka en ehdi tarkemmin tutkia, että jotain "turvaaminen" -tyyppistä voisi ehkä funtsia _suojelulle_. Suomeksihan se ei varsinaisesti tarkennetta edes tarvitse, mutta jos halutaan ohjata käyttöä tarkempiin termeihin ja jättää pelkkä suojelu niille tapauksille, joissa mikään muu ei käy.

**Comment by mariaforsen** [comment]
Miten suojelu voi jäädä ilman mitään määrittelyä, eli miten luodaan sitten toimiva sulkutarkenne ruotsiksi? Kannatan kyllä tekniikka tms. ja turvaaminen -vaihtoehtoa. Ruotsiksi voisi ajatella: skydd/skyddande (mot något, eli suojaus jotakin vastaan) ja skydd/skyddande (tryggande, eli suojelu merkityksessä turvaaminen)

**Comment by mirmaid** [comment]
Tosiaan suomeksi _suojelu_ ei mene samalla tavalla sekaisin _suojaus_-käsitteen kanssa kuin ruotsiksi, eli jos ruotsiksi olisi tarkenne, suomeksi voisi ehkä olla myös ilman. Eikä _suojauskaan_, mutta ruotsiksi tarkenteet pitää löytää, ja jos ruotsinkielinen tarkenne on esim. vähän suppeampi kuin suomenkielisen termin kattavuus (tai jos halutaan ohjata suomeksi käyttöä tarkempiin termeihin), niin sitten pitää lisätä suomeksikin.

**Comment by mirmaid** [comment]
Ehdotus suojaus-käsitteelle:

- korjataan kaikki ihon aurinkosuojausta käsittelevät aineistot > auringonsuoja-aineet
- lisätään suojaukselle tarkenne (tekniikka), ja korjataan siihen kaikki helpot viitteet (tietotekniikka, sähköala, rakentaminen, asetekniikka)
- lisäksi tarvittaisiin ohjaustermi, jolla myös vähemmän tekninen aineisto tulisi tämän piiriin. Eli kun kyse on vaikkapa veneen talvisuojauksesta peittämällä, sitä ei välttämättä mielletä kovin teknisenä. Löytyykö ehdotuksia? _Suojaus (suojavarustein)_ -tapaan, mutta mielellään vähän vielä parempi, kun ei sitä pressuakaan välttämättä arvaa "suojavarusteeksi"...

**Comment by mariaforsen** [comment]
Jos asia on kuten yllä mainittu: 

"Suojelussa siis pyritään päätöksin ja sopimuksin takaamaan jonkin (eläinlajin, muinaisjäännöksen, maiseman, väestön) säilyminen, turvallisuus tai hyvinvointi.

Suojauksessa taas pyritään jollakin välineellä, aineella tai tekniikalla estämään jonkin vahingoittuminen tai varastaminen."

..Niin voisiko olla 1) skydd/skyddande (beslut och överenskommelser) ja 2) skydd/skyddande (med fysiska medel)? Tms. Eli ensimmäinen päätöksin ja sopimuksin suojaaminen, ja toinen fyysisin tavoin/välinein suojaaminen.

**Comment by mirmaid** [comment]
Uusi ehdotus **suojaus**-käsitteelle:

suojaus (käsittely) TAI suojaus (tekniikka), toinen ohjaustermiksi

Ilonan [listasta](https://github.com/Finto-ehdotus/YSE/issues/7211#issuecomment-956167685) nimisuoja, suojarekisteröinti ja silmien suojaus jäisivät ulkopuolelle, ja jos tarkenne olisi (tekniikka), varmaankin myös muutama muu.

Sitten pitäisi löytää ruotsinkielinen tarkennevastine, joka - jos se siis ei ole teknik - poissulkee päätöksenteon. En siis tiedä käykö _behandling_ tässä.

**Comment by mirmaid** [comment]
Huom. ei mennä tässä mutulla (siitä on aiemmin ollut aika hankalia seurauksia), eli oikeasti mietittehän miten mahdollinen tarkenne sopii listattuihin (tai Melindan) viitteisiin.

**Comment by mariaforsen** [comment]
Behandling ei tosiaan käy, voi olla myös kuvannollinen eli jonkun asian käsittely jne. Teknik varmaan parempi, mutta ei sekään kaikille viitteille sovi, esim. Nuoren mielenterveyden suojaus ja haavoittuvuus : yhdeksäsluokkalaisten käsityksiä mielenterveydestä ja sen kokemisesta. Ja mikä tarkenne skyddande-termille (fi. suojelu)?

**Comment by mirmaid** [comment]
^ Jos sen päättäisi seuraavaksi. Tämä on niin iso pala purtavaksi, ettei oikein kapasiteettini riitä edistää koko pottia kerralla.

Tekniikka ei käy kaikkeen toki suomeksikaan. Tuossa esimerkissä ei ole kuvailussa kumpaakaan, olisi kiinnostavaa nähdä miten tekijä käyttää tuota suojaus-sanaa tekstissä. Ehkä vähän samaan tapaan kuin Ilonan viitteissä "EU:n sotalaivat suojaavat avustuskuljetuksia merirosvoilta, mutta maissa odottavat uudet varkaat", eli vähän tuollaisena "taktisena". Mutta tuon tyyppinen jäisi suomeksi kummankin tarkenteen ulottumattomiin (tai sotalaiva-esimerkissä voisi ehkä tekniikka sopia, mutta käsittely ei). Molempiin kävisi mielestäni suojelu, vaikka tuossa mielenterveys-kontekstissa kumpikaan ei olisi luonteva, ennemmin tulisi mieleen joku "edistäminen", jos nyt mikään sellainen tuntuisi tarpeelliselta.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _suojaus (tekniikka)_ KT _suojaus (käsittely)_. Jatketaan työstöä ensi kerralla.

**Comment by mirmaid** [comment]
Siirtyisikö kasvinsuojelu ja tulvasuojelu suojaus (tekniikka) -käsitteen alle? Mutta metsänsuojelu jäisi suojelun alle. 

Sitten pitäisi muodostaa suojelulle tarkenne, jolla rajattaisiin sen käyttö aineistoihin, joissa ei ole kyse mistään teknisestä, ja joista suomeksi käytettäisiin suojelu (ei suojaus). Yksi mahdollisuus tietysti olisi myös joku suojelu (tekniset toimenpiteet) KÄ suojaus (tekniikka) ja se, että löydettäisiin soveltuva ruotsinkielinen tarkenne tai termimuoto, jota ei voi käyttää teknisemmästä (&fyysisemmästä) suojauksesta.

**Comment by mariaforsen** [comment]
Voisiko olla:
-skydd/skyddande (teknik) -suojaus (tekniikka)
-skydd/skyddande (värnande) -suojelu 

https://www.sanakirja.fi/custom/fi-en-sv/v%C3%A4rna
Värnande (vaaliminen, varjelu, puolustaminen..) erottaa fyysisestä/teknisestä ja näyttää sopivan Melinda-viitteisiin (muutama sata katsottu)

Ehdotettu myös beskyddande, mutta se sopii melkein vain henkilöistä ja tietyissä tapauksissa, eli ei yleensä sovi nykyisille Melinda-viitteille (n. 7000). Melindatapauksia joissa myös beskydd toimisi:
-Protecting against child-killing demons: uterus amulets in the Late Antique and Byzantine magical world 
-Ilmoittaja - petturi vai sankari?
-Introduction to executive protection 
-Missä turvasaaren kirjailijat? : Hailuotoon alettiin puuhata turvaresidenssiä kirjailijoille vuoden 2014 lopussa
-Vårdares uppfattningar om att vaka över och beskydda patienten 
-"Karjalan naisrauha" on 700 vuoden takaa
-Lapsen suojelu : viranomaisten ja muiden toimijoiden välisenä yhteistyönä : käsikirja arjen toimintaan 
-Turvatoimet pettivät totaalisesti : maahanmuuttaja huijasi härskisti pääministeriä. (?)
-Suojassa / Erkki Jokinen (hartauskirja)
-Uusi laki suojelee todistajaa! : hengenvaarassa oleville luodaan uusi identiteetti : todistajansuojeluohjelma antaa turvaa oikeudessa pelkäävälle todistajalle.
-Rikoksen uhrin asemaan parannusta

**Comment by mirmaid** [comment]
^ Ilman muuta, jos se tuntuu sopivan noihin missä suojellaan jotakin esim. sopimuksin. Värna taitaa olla sana, jonka kuulen nyt ensimmäistä kertaa 🙂.

**Comment by YSO-kokous** [comment]
PÄÄTÖS
Ruotsiksi ehdotetut tarkenteet.
Tarkistetaan onko metsänsuojelu käytetty kasvisuojelu-merkityksessä ja tarvitseeko se tarkenteen.

**Comment by mariaforsen** [comment]
Sv.
skydd (åtgärder) > skyddande (teknik) -fi. suojaus (tekniikka)
-skyddande > skyddande (värnande) -fi. suojelu 

-skyddande tydligare än skydd, som kan syfta på föremål/utrustning, https://svenska.se/tre/?sok=skydd&pz=1 jfr https://svenska.se/tre/?sok=skyddande&pz=1
-suojaimet=skyddsutrustning skilt i allfo, HT skydd (utrustning)
-https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_0b6149549d1ad56978fa571fd33058bd&list_id=1&keyword=suojelu&word=suojelu
-https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_6b3ef6f07385d5c7138c06efbe791733&list_id=1&keyword=suojaus&word=suojaus
-https://termipankki.fi/tepa/fi/haku/suojelu
-https://termipankki.fi/tepa/fi/haku/suojaus
-https://www.rikstermbanken.se/search?q=skydd&s=termer
-se suojelu vs. suojaus i Melinda

**Comment by mirmaid** [comment]
Avoinna vielä: _Tarkistetaan onko metsänsuojelu käytetty kasvisuojelu-merkityksessä ja tarvitseeko se tarkenteen_.

**Comment by mariaforsen** [comment]
Issue tehty (nyt virheellistä kuvailua): https://github.com/Finto-ehdotus/YSE/issues/13230
