### ISSUE TITLE
kehityskertomukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7213]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kehityskertomukset 

#### Ehdotettu termi ruotsiksi   

utvecklingsberättelser 

#### Assosiatiiviset (RT)   

[kehitysromaanit](http://www.yso.fi/onto/yso/p12951) 
[psykologiset romaanit](http://www.yso.fi/onto/yso/p29681) 

#### Perustelut ehdotukselle   

Tarvitaan kaunokirjallisuuden kuvailussa genreterminä. Kirjastopalvelussa käytetty 504 kertaa kuvailussa tähän mennessä kaunokki-käsitteenä ja käytetään jatkuvasti. On eri asia kuin kehitysromaanit, koska voivat olla novelleja. Voivat myös esiintyä yhtenä juonikuviona romaanissa, vrt. esim. rakkauskertomukset: romaani voi sisältää myös rakkauskertomuksen olematta kuitenkaan päägenreltään rakkausromaani. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käytetty esim. Henryk Sienkiewicz: Erämaan halki 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [kehityskertomukset](http://finto.fi/yse/fi/page/Y507213)

**Comment by mirmaid** [comment]
Kaunokki-kokous. Mahdollinen myös _kasvutarinat_.
