### ISSUE TITLE
meänkielinen kirjallisuus ja kveeninkielinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7214]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

meänkielinen kirjallisuus ja kveeninkielinen kirjallisuus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjallisuus](http://www.yso.fi/onto/yso/p8113) 

#### Perustelut ehdotukselle   

YKL-kokous taipumassa siirtämään meän kielen ja kveenin kielen suomen kielen murreluokista itämerensuomalaisten kielten luokkaan eli itsenäiseksi kieleksi Pohjois-Suomen kirjastoista tulleen toiveen mukaisesti. Tällöin tarvitaan alueiden kaunokirjallisuutta kuvaamaan em. termit. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Bengt Pohjasen tuotanto jne. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [meänkielinen kirjallisuus ja kveeninkielinen kirjallisuus](http://finto.fi/yse/fi/page/Y507214)

**Comment by mariaforsen** [comment]
Sv. 
litteratur på meänkieli ET meänkielilitteratur, tornedalsfinsk litteratur
kvänsk litteratur ET litteratur på kvänska
