### ISSUE TITLE
Blenheim (pommikoneet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7215]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Blenheim (pommikoneet) 

#### Ehdotettu termi ruotsiksi   

Blenheim (bombplan) 

#### Ehdotettu termi englanniksi   

Blenheim (bombers) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pommikoneet](http://www.yso.fi/onto/yso/p3106) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85014837> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Blenheim Suomessa / Igor Kopiloff. 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [Blenheim (pommikoneet)](http://finto.fi/yse/fi/page/Y507215)

**Comment by mirmaid** [comment]
Tarkenne? Vrt. _MiG (lentokoneet)_.

**Comment by YSA-kokous** [comment]
Blenheim (lentokoneet)

**Comment by mariaforsen** [comment]
Sv. Blenheim (flygplan)
