### ISSUE TITLE
syömäpuikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7218]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syömäpuikot 

#### Ehdotettu termi englanniksi   

chopsticks 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Museokokoelmat 

#### Perustelut ehdotukselle   

Yleisesti käytetty ruokailuväline, niin Suomessa kuin maailmalla. 

**Ehdottajan organisaatio:** Museovirasto **Termiehdotus Fintossa:** [syömäpuikot](http://finto.fi/yse/fi/page/Y507218)

**Comment by ilona-x** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh88007029

**Comment by mariaforsen** [comment]
Sv. ätpinnar
