### ISSUE TITLE
parkkilaivat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7219]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

parkkilaivat 

#### Ehdotettu termi ruotsiksi   

barkskepp 

#### Ehdotettu termi englanniksi   

Barks (Sailing ships) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[purjelaivat](http://www.yso.fi/onto/yso/p20211) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh91001077.html> 
Wkipedia : https://fi.wikipedia.org/wiki/Parkki 
MERO : <http://finto.fi/liiko/fi/page/m9271> 
MAO : <http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp5404> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

3–5 mastoinen purjealus, jonka perämastossa on puomi- ja huippupurje, muissa mastoissa raakapurjeet
(https://fi.wiktionary.org/wiki/parkkilaiva) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2107938 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [parkkilaivat](http://finto.fi/yse/fi/page/Y507219)

**Comment by mariaforsen** [comment]
Sv. barkskepp ET barkar, barker
