### ISSUE TITLE
ihmisuhrit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#722]
#### Ehdotettu termi suomeksi

ihmisuhrit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/ysa/ryhma_50)
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/ysa/ryhma_53)

**Luontipäivämäärä:** 01.03.2002

**Muokkauspäivämäärä:** 1.3.2002, 16.12.2008

**Voyager-id:** 117941

**Termiehdotus Fintossa:** [ihmisuhrit](http://finto.fi/yse/fi/page/Y317941)

**Comment by mirmaid** [comment]
Tätä olisi voinut käyttää väitöskirjassa _Människooffer i myt och minne : En studie av offerpraktiker i fornnordisk religion utifrån källtexter och arkeologiskt material_ https://www.doria.fi/handle/10024/178514?locale=lfi

**Comment by mirmaid** [comment]
Tarkenne ehkä tarpeen? _Ihmisuhrit (uskonto)_?

**Comment by jarmosaarikko** [comment]
LCSH  [Human sacrifice](http://id.loc.gov/authorities/subjects/sh85116392) 
Wikidata ihmisuhri, människooffer, human sacrifice, http://www.wikidata.org/entity/Q119094
- https://fi.wikipedia.org/wiki/Ihmisuhri
- https://sv.wikipedia.org/wiki/M%C3%A4nniskooffer
- https://en.wikipedia.org/wiki/Human_sacrifice

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/find?q=m%C3%A4nniskooffer

**Comment by AuHo22** [comment]
_Tarkenne ehkä tarpeen? Ihmisuhrit (uskonto)?_ -> Tarkoitetaanko tässä ns. muinaisuskontojen ihmisuhreja vai voidaanko tämä ymmärtää myös nykyisten uskontojen hengellisen ja muun väkivallan uhrien kautta - niissä yhteyksissä on voitu käyttää uhrit-termiä -> ihmisuhrit (muinaisuskonnot/muinaisusko)?

**Comment by mariaforsen** [comment]
Mielestäni termi on selkeä ilman tarkennetta.

**Comment by AuHo22** [comment]
Suomen kielessä voi kuitenkin tarkoittaa yhtä hyvin myös sodan ihmisuhreja.

**Comment by mirmaid** [comment]
^ Juuri näin. Sen sijaan _ihmisuhrit (uskonto)_ ei varmaan tulkittaisi tarkoittavan "uskonnon uhreja". Varmaan kyse kyllä on aina jonkinlaisesta muinaisuskosta, mutta vähän mietin miten sen ajateltaisiin rajautuvan.

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Ihmisuhri -artikkeli viittaa myös siihen, että ei kuitenkaan välttämättä ole menneen maailmankaan ilmiö -> ihmisuhrit (rituaalit)?
Uhrit (uskonto) ohjaustermi on näköjään olemassa -> uhrilahjat / uhraaminen

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään muodossa ihmisuhrit (uskonto)

**Comment by mariaforsen** [comment]
Sv. människooffer HT mänskooffer
