### ISSUE TITLE
kuunarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7220]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuunarit 

#### Ehdotettu termi ruotsiksi   

Skonerter 

#### Ehdotettu termi englanniksi   

schooners 

#### Ehdotettu yläkäsite YSOssa (LT)   

[purjelaivat](http://www.yso.fi/onto/yso/p20211) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85118481.html> 
SAO : Skonerter 
MERO : <http://finto.fi/liiko/fi/page/m9253> 
MAO : <http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp293> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

Purjealus, jossa etummainen masto on saman mittainen tai lyhempi kuin taempi tai taemmat, ja jossa on pääasiassa pitkittäistakila, vaikka etummaisessa mastossa voi olla myös raakapurje.
(https://fi.wiktionary.org/wiki/kuunari) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2000610 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [kuunarit](http://finto.fi/yse/fi/page/Y507220)

**Comment by mariaforsen** [comment]
Sv. skonerter ET skonare, skonarfartyg, slätskonare
