### ISSUE TITLE
klipperit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7221]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

klipperit 

#### Ehdotettu termi ruotsiksi   

klipperskepp 

#### Ehdotettu termi englanniksi   

Clipper ships 

#### Ehdotettu yläkäsite YSOssa (LT)   

[purjelaivat](http://www.yso.fi/onto/yso/p20211) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85027082.html> 
MERO : <http://finto.fi/liiko/fi/page/m9240> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

Klipperi on puinen kapearunkoinen purjelaiva. Klipperissä on useimmiten kolme mastoa, jossa kaikissa on täysitakila eli raaka- ja haruspurjeet. Lisäksi taaimmissa mastossa on kahvelipurje. Klipperit olivat pieniä ja aikansa nopeimpia rahtialuksia (https://fi.wikipedia.org/wiki/Klipperi) 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2173364 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [klipperit](http://finto.fi/yse/fi/page/Y507221)

**Comment by mirmaid** [comment]
17 viitettä Melindassa. Tarvitseeko tarkenteen?

**Comment by mariaforsen** [comment]
Sv. klipperskepp ET klipprar
