### ISSUE TITLE
fregatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7222]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fregatit 

#### Ehdotettu termi englanniksi   

frigates 

#### Ehdotettu termi ruotsiksi   

fregatter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[purjelaivat](http://www.yso.fi/onto/yso/p20211) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85052023.html> 
SAO : fregatter 
MERO : <http://finto.fi/liiko/fi/page/m9217> 
MAO : <http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp3541> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2107965 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa 

#### Tarkoitusta täsmentävä selite   

Purjealuksena fregatti tarkoittaa vähintään kolmimastoista alusta, jossa on raakapurjeet kaikissa mastoissa. Synonyymi fregattitakilaiselle alukselle on täystakiloitu laiva. 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [fregatit](http://finto.fi/yse/fi/page/Y507222)

**Comment by mirmaid** [comment]
Halutaanko tämä rajata purjealuksiin?

**Comment by LeKorsu** [comment]
Voiko tosiaan käyttää samaa sekä purjealuksista että nykyaikaisista sotalaivoista vai vaatiiko sulkutarkenteen?

Sitaatti HS 21.9.19: "Kiinnostava kysymys on myös se, miksi Puolustusvoimat puhuu vähätellen korveteista vaikka alukset ovat nyt paljastuneet luokkaa isommiksi sotalaivoiksi? Pohjanmaa-luokan alukset kun eivät ole korvetti-luokan aluksia vaan ne kuuluvat uppoumansa perusteella isompaan alusluokkaan eli fregatteihin."

**Comment by YSA-kokous** [comment]
fregatit (purjelaivat)

**Comment by mariaforsen** [comment]
Sv. fregatter (segelfartyg)
