### ISSUE TITLE
nekrologit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7223]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nekrologit](http://www.yso.fi/onto/ysa/Y103578) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvetta on: tällä hetkellä Melindassa käytetty 655-kentässä yli sata kertaa. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
