### ISSUE TITLE
hautaröykkiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7224]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hautaröykkiöt 

#### Ehdotettu termi ruotsiksi   

gravrösen 

#### Vaihtoehtoiset termit ja ilmaisut   

hautarauniot 
röykkiöhaudat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaishaudat](http://www.yso.fi/onto/yso/p5714) 

#### Alakäsitteet (RT)   

[hiidenkiukaat](http://www.yso.fi/onto/yso/p5842) 

#### Vastaava käsite muussa sanastossa   

SAO : gravrösen 
Arkeologisen kulttuuriperinnön opas : <http://akp.nba.fi/wiki;hautar%C3%B6ykki%C3%B6> 
MAO : <http://finto.fi/maotao/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fmao%2Fp9263> 

#### Tarkoitusta täsmentävä selite   

pääasiassa kivistä kasattu hautarakenne, joka erottuu selvästi ympäröivästä maastosta.
... Pronssikautisista röykkiöistä puhuttaessa tarkoitetaan yleensä nk. läntisen pronssikulttuurin piiriin kuuluvia, rannikkoalueilla sijaitsevia hautaröykkiöitä ( (vrt. sisämaan lapinrauniot). Etenkin pronssikautisia hautaröykkiöitä on kutsuttu myös hautaraunioksi). Lisäksi eri alueilla niille on annettu kansanomaisia nimiä kuten hiidenkiuas, vare tai kruunu  (Arkeologisen kulttuuriperinnön opas, Museovirasto) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3026573 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisällönkuvailussa 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [hautaröykkiöt](http://finto.fi/yse/fi/page/Y507224)

**Comment by vaisate** [comment]
Erittäin oleellinen lisäys myös Musketissa tarpeellisten arkeologisten asiasanojen kirjon laajentamiseksi.

**Comment by mirmaid** [comment]
YSOssa on _hiidenkiukaat_, YK _muinaishaudat_. Melindassa 45 x hiidenkiukaat, 15 x lapinrauniot, 16 x hautaröykkiöt. MAOssa on nämä kaikki, mutta käsitteiden määritelmät eivät sulje toisiaan pois. 

**hiidenkiukaat:** pronssikautinen hautaröykkiö rannikolla, vare, kruunu
**lapinrauniot:** järven rannalle kalliopohjalle ja näkyvälle paikalle kivistä rakennettu hautaröykkiö
**hautaröykkiöt:** pääasiassa kivistä kasattu hautarakenne, joka erottuu selvästi ympäröivästä maastosta

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/R%C3%B6ykki%C3%B6hauta

**Comment by mirmaid** [comment]
_Vaikka nämä "hiidenkiukaat" eli lounaismurteilla "vareet" yhdistetään yleensä rannikon asutukseen, on varhaismetallikaudelle ajoittuvia hautaröykkiöitä löydetty myös sisämaasta. Niitä on 1700-luvulta lähtien kutsuttu "lapinraunioiksi", koska niiden rakentajien ajateltiin olleen lappalaisia (saamelaisia). Hiidenkiukaita ja lapinraunioita on kuitenkin vaikea erottaa toisistaan. -- Hiidenkiukaiden ja lapinraunioiden välinen ero on häilyvä, joskin sisämaan lapinrauniot ovat yleensä rannikon hautaröykkiöitä pienempiä. Oikeastaan ei voidakaan esittää selkeää kriteeriä, jolla nämä kaksi traditiota voitaisiin erottaa toisistaan. Terminologia lapinraunioiden ja hiidenkiukaiden välillä on horjuvaa, ja joskus samaa sisämaan muinaisjäännöstä voidaan kutsua joko lapinraunioksi tai hiidenkiukaaksi. Todennäköisesti selvää eroa hiidenkiukaiden ja lapinraunioiden välillä ei muinoinkaan ollut: ihmiset ja kulttuurivaikutteet liikkuivat moneen suuntaan, minkä vuoksi eri alueiden väestöt saattoivat tehdä samankaltaisia hautarakennelmia._ (Mika Lavento: Muinaisuutemme jäljet)

**Comment by mariaforsen** [comment]
Ainakin hautaröykkiöt/gravrösen olisi hyvä neutraalina terminä (käy myös Ruotsissa ja muualla maailmalla, toisin kuin nämä muut aluelliset termit)

**Comment by YSA-kokous** [comment]
Otetaan sanastoon hautaröykkiöt, ohjaustermiksi hiidenkiukaat JA lapinrauniot.
Poistetaan sanastosta hiidenkiukaat.

**Comment by mariaforsen** [comment]
Sv. gravrösen ET jättekast (gravrösen), rösen 
https://www.uppslagsverket.fi/sv/sok/view-103684-Jaettekast
