### ISSUE TITLE
rakkauselokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7226]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakkauselokuvat](http://www.yso.fi/onto/ysa/Y110479) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi romanttiset elokuvat. 

#### Perustelut ehdotukselle   

Käsite on tällä nimellä Wikidatassa ja YSOn käsite on linkattu siihen Wikidata-linkityksen yhteydessä. Wikidatassa englanninkielinen vastine on sama kuin YSOssa: romance film(s). 
https://www.wikidata.org/wiki/Q1054574
Samasta syystä ruotsin ohjaustermeiksi voisi harkita näitä: romantikfilmer, romantiska filmer. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
romanttiset elokuvat KÄ rakkauselokuvat, romanttiset komediat, romanttiset draamat
