### ISSUE TITLE
naissankarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7227]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[naissankarit](http://www.yso.fi/onto/ysa/Y152647) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava tai selkeytettävä merkitys. Tällä on nyt kaksi merkitystä: a) casanovat, b) naispuoliset sankarit 

#### Perustelut ehdotukselle   

Casanova-merkitys tuntuu tämän termin yhteydessä jo hieman vanhentuneelta. Suurin osa viime vuosien Melinda-käytöstä liittyy naispuolisiin sankareihin, ei casanoviin. "naistenmiehet" voisi olla parempi käytettävä termi. Jos naispuolisille sankareille tarvitaan oma käsitteensä, niin käytettävä termi voisi olla "naispuoliset sankarit" (tai "sankarittaret"). 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by AuHo22** [comment]
Naistenmiehet voisi olla parempi korvaamaan naissankarit-termiä joka valitettavasti on monitulkintainen. 
Naistenmiehiä – Casanovasta Rosvo Roopeen  http://www.minervakustannus.fi/kirjat/kirja.php?kirja=92

**Comment by mariaforsen** [comment]
Sv. kvinnotjusare, eli nimenomaan vain naistenmiesten merkityksessä.

**Comment by YSO-kokous** [comment]
Muutetaan muotoon naistenmiehet, ohjaustermiksi naissankarit.
Lisätään myös ohjaustermi:
sankarittaret KÄYTÄ sankarit
