### ISSUE TITLE
vastaanotto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7228]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vastaanotto 

#### Perustelut ehdotukselle   

Aiemmin YSA-kokouksessa https://github.com/Finto-ehdotus/YSE/issues/4789 päätettiin ottaa seuraavat vastaanotto-termit:
tavaran vastaanotto
reseptio KT vastaanotto (suhtautuminen)
vastaanottotoiminta

Melinda-viitteiden korjaamisen yhteydessä tuli selväksi, että tarvitaan jokin termi ihmisten vastaanottoa varten. Paljon aineistoja maahanmuuttajien vastaanotosta ja lisäksi esimerkiksi hotellien vastaanottotoimintaa käsitteleviä aineistoja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melinda 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vastaanotto](http://finto.fi/yse/fi/page/Y507228)

**Comment by mirmaid** [comment]
vastaanotto (maahanmuuttajat)
aulapalvelut

**Comment by LeKorsu** [comment]
Mitenkäs kaunon vastaanotto (fyysinen)?

**Comment by mariaforsen** [comment]
Vastaanotto (maahanmuuttajat) voisi olla ruotsiksi "mottagning/mottagande av flyktingar" tms.

**Comment by YSA-kokous** [comment]
vastaanotto (pakolaiset)
aulapalvelut

Palataan vastaanottotoiminta-termiin konversion jälkeen.

**Comment by mariaforsen** [comment]
Sv.
-flyktingmottagande ET mottagning av flyktingar
-receptionstjänster ET aulatjänster

**Comment by FinMeSHienPaimentaja** [comment]
Entä lääkärin vastaanotto?

**Comment by mariaforsen** [comment]
Sitä varten on ainakin "vastaanottotoiminta" (huomautus: Toimintaa, jossa terveydenhuollon, sosiaalityön tms. asiantuntijat ottavat vastaan asiakkaita.)

**Comment by ilona-x** [comment]
YSA-kokous commented on 24 Apr 2019

> vastaanotto (pakolaiset)
> aulapalvelut
> 
> Palataan vastaanottotoiminta-termiin konversion jälkeen.

Eli onko tässä issuessa tarkoitus käsitellä nyt termiä **vastaanottotoiminta**?

**Comment by ilona-x** [comment]
Olikohan tarkoitus pohtia, onko vastaaottotoiminta paras termimuoto. Vastaanotto-termillä oli kuvailtu joitakin terveydenhuoltoa käsitteleviä aineistoja, joihin vastaanottotoiminta ei tunnu sopivalta termiltä. Toisaalta taas ei ehkä haluta, että sanastossa on sekä vastaanottotoiminta että vastaanotto (terveydenhuolto).

Tässä nuo vastaanotto-termillä kuvaillut Melinda-viitteet, joihin vastaaonttotoiminta ei tunnu täysin sopivalta:

- Tulohaastattelutilanne - pohja hoitosuhteelle : potilaan näkökulma 
- Suljetun osaston vastaanottotilanteen kokeminen vastentahtoisesti hoidossa olleiden psykiatristen potilaiden tarpeiden kannalt
- Sydäninfarktipotilaiden tiedonsaanti : ensimmäiseen sydäninfarktiin sairastuneiden potilaiden arviointia tiedonsaannista Länsi-Pohjan keskussairaalan teho-osastolla 
- Potilaan kokemuksia vastaanottamisesta psykiatriselle osastolle 

Aiemmassa vastaanotto-issuessa on avattu vastaanottotoiminta-termin historiaa: https://github.com/Finto-ehdotus/YSE/issues/4789

**Comment by AuHo22** [comment]
Vastaanottotoiminta-termin määritelmä nykyisin: "Toimintaa, jossa terveydenhuollon, sosiaalityön tms. asiantuntijat ottavat vastaan asiakkaita."
Yo. tapauksissa kai monessa on ns. potilaan näkökulma otettu esille eli vastaanottotoiminta + kokemukset (+potilaat)
Yhdellä termillä ei ehkä saada asiaa kuvattuakaan?

**Comment by mirmaid** [comment]
Ongelma oli ainakin myös siinä, että vastaanottotoimintaakin oli käytetty väärin, esim. https://melinda.kansalliskirjasto.fi/byid/009597046 (tavaran vastaanotto) tai https://melinda.kansalliskirjasto.fi/byid/013355625 (pakolaiset).

**Comment by mirmaid** [comment]
Käytetty Melindassa seuraavissa yhteyksissä (yht. 72 kertaa):

- terveydenhuolto, ml. psykologin vastaanotto
- eläinlääkäri
- filosofin vastaanotto (psykologin tapaan)

**Comment by mirmaid** [comment]
Yksi mahdollisuus on edelleen lisätä ohjaustermejä, koska virheellistä käyttöä ei ole kovin paljon.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermejä tavaran vastaanotto ja vastaanotto (pakolaiset) -käsitteille.
