### ISSUE TITLE
regaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7229]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

regaalit 

#### Ehdotettu termi ruotsiksi   

riksregalier 

#### Ehdotettu termi englanniksi   

regalia 

#### Vaihtoehtoiset termit ja ilmaisut   

kruununjalokivet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[korut](http://www.yso.fi/onto/yso/p10789) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85112334.html> 
SAO : Riksregalier 
Wikidata : https://www.wikidata.org/wiki/Q119814 

#### Tarkoitusta täsmentävä selite   

Hallitsijan valtaa kuvaavat arvoesineet 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1763655 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston sisälllönkuvailussa. 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [regaalit](http://finto.fi/yse/fi/page/Y507229)

**Comment by jtuohini** [comment]
Mieluummin muodossa **kruununjalokivet**, joka aukeaa helpommin tavalliselle käyttäjälle kuin _regaalit_ – joka lisäksi viittaa myös soittimeen (regaaliin eli regaaliurkuihin).

**Comment by mirmaid** [comment]
MAOssa muodossa _kruununjalokivet_.

**Comment by mariaforsen** [comment]
Sv. kronjuveler ET regalier

**Comment by LeKorsu** [comment]
Ohjaustermi regaaleista?

**Comment by YSA-kokous** [comment]
Kruununjalokivet
