### ISSUE TITLE
Jussi-palkinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7230]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Jussi-palkinto 

#### Ehdotettu termi ruotsiksi   

Jussipris 

#### Ehdotettu termi englanniksi   

Jussi Award 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Tarkoitusta täsmentävä selite   

Vrt. Finlandia-palkinto, Nobelin palkinto 

#### Perustelut ehdotukselle   

Jussi-palkittujen elokuvien DVD- ym. tallenteiden sekä palkintoja ja palkittuja käsittelevien artikkeleiden ja kirjojen asiaisanoitukseen. Olisi hyvä olla myös metatietosanastosta, kuten Finlandia-palkintokin on. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi Tyhjiö-elokuvan DVD-tallenne. 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [Jussi-palkinto](http://finto.fi/yse/fi/page/Y507230)

**Comment by mariaforsen** [comment]
Sv. Jussistatyetten ET Jussipriset, Jussi (filmpris)
