### ISSUE TITLE
ympärileikkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7231]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ympärileikkaus](http://www.yso.fi/onto/ysa/Y106236) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan tämän tilalle kaksi käsitettä, "miesten ympärileikkaus" ja "naisten ympärileikkaus" (tai "naisen sukupuolielinten silpominen"). Molemmille tarvittaessa ohjaustermiksi ympärileikkaus. Vanha "ympärileikkaus"-käsite voidaan poistaa. 

#### Perustelut ehdotukselle   

Käytetty Melindassa molemmista, erityisesti naisten ympärileikkauksesta. Englannin käännös YSOssa (cimrcumcision) viittaa vain miehen ympärileikkaukseen. Tiedonhakija todennäköisesti kiinnostunut vain toisesta tyypistä, ei molemmista. MeSHissä ovat erikseen. Samoin Wikipediassa. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
Naisten osalta mieluummin _suku(puoli)elinten silpominen_, kun ettei käytettäisi turhaan kaunistelevaa kiertoilmaisua.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4421

**Comment by mirmaid** [comment]
Sexpon asiantuntija Eeva Matsuuken mukaan poikien ei-lääketieteellisiä ympärileikkauksia tulisi kutsua silpomisiksi kuten tyttöjenkin kohdalla tehdään.
https://www.hs.fi/kotimaa/art-2000002535201.html

**Comment by jtuohini** [comment]
Kaunistelevat kiertoilmaisut siis pois tältäkin osin pois!

**Comment by mariaforsen** [comment]
Ruotsiksi ei ainakaan tehdä sellaista "yhtäläisyysmerkkiä" (ja miespuolisten osaltahan syy saattaa olla lääketieteellinenkin, joten eihän sellaista termiä voi siitä käyttää). Taitaa yleinen kielenkäyttö suomeksikin olla eri kuin sexpon sen yhden asiantuntijan... (Jos hänen mukaansa tehtäisiin se vaatisi sitten kolme eri päätermiä ja olisi muutenkin aika raju kannanotto YSOlta esim. juutalaisten ympärileikkauksiin)

Ks. myös MESH http://finto.fi/mesh/fi/search?clang=sv&q=omsk%C3%A4relse

**Comment by mirmaid** [comment]
Vähän sellainen aihepiiri, että kaikki ratkaisut ottavat jollain lailla kantaa. On mahdollista myös ottaa erikseen _lääketieteellinen ympärileikkaus_. Jos päätetään, että poikien ei-lääketieteellistäkään ympärileikkausta ei pidetä silpomisena, halutaanko nämä kaksi pitää yhdessä? Onko termi _miesten ympärileikkaus_ (vaikka suoritetaan ei-lääketieteellisenä yleensä pienille pojille) vai _peniksen ympärileikkaus_? Itse koen sukupuoleen perustuvan jaon hieman ongelmallisena, mutta ratkaisu voidaan toki perustella esim. sillä, että poikien ei-lääketieteellinen ympärileikkaus ei ole meilläkään toistaiseksi kielletty. _Suomessa alaikäisten poikien ei-lääketieteellistä ympärileikkausta ei ole toistaiseksi lailla kielletty, mutta sen katsotaan loukkaavan lapsen koskemattomuutta ja itsemääräämisoikeutta._ https://thl.fi/fi/web/maahanmuutto-ja-kulttuurinen-moninaisuus/maahanmuutto-ja-hyvinvointi/maahanmuuttajien-seksuaali-ja-lisaantymisterveys/poikien-ei-laaketieteellinen-ymparileikkaus

Ympärileikkaus (tytöt) KÄ _sukupuolielinten silpominen_ on termitasolla helpompi (ei kylläkään estä käyttämästä pojista).

**Comment by YSO-kokous** [comment]
Jaetaan kahtia. Keskustelu polveili sen osalta, tehdäänkö käsitejako sukupuolen vai kulttuuri/lääketiede-jaon mukaan. Ensinnäkin päätettiin ottaa sanastoon käsite muodossa:
**ympärileikkaus (miehet)**

Toisen käsitteen osalta äänestettiin:
sukupuolielinten silpominen (naiset) 3
ympärileikkaus (naiset) 3
**sukupuolielinten silpominen [ilman sulkutarkennetta]** 5

Jälkimmäiselle ohjaustermiksi ympärileikkaus (naiset). Tälle käsitteelle ei lisätä määritelmää eikä käyttöhuomautusta. Periaatteessa tätä käsitettä on siis mahdollista käyttää kuvailussa myös miesten ympärileikkauksen kohdalla, silloin kun toimenpide ei johdu lääketieteellisistä syistä.
