### ISSUE TITLE
domra

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7232]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

domra 

#### Ehdotettu termi ruotsiksi   

domra 

#### Ehdotettu termi englanniksi   

domra 

#### Ehdotettu yläkäsite YSOssa (LT)   

[näppäilysoittimet](http://www.yso.fi/onto/yso/p1510) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2012002051> 
Wikidata : https://www.wikidata.org/wiki/Q941492 

#### Perustelut ehdotukselle   

Finnasta löytyy kuvia domrasta, mutta niissä virheellisesti asiasanana balalaikka. Kuvia hallinnoiviin museoihin mennyt korjauspyyntö päivittää virheelliset metatiedot – paha korjata asiasana oikeaksi, jos sopivaa ei sanastossa… 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.finna.fi/Record/musketti.M012:HK19670603:30509 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [domra](http://finto.fi/yse/fi/page/Y507232)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
