### ISSUE TITLE
diabeettinen retinopatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7233]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

diabeettinen retinopatia 

#### Ehdotettu termi ruotsiksi   

diabetisk näthinnesjukdom 

#### Ehdotettu termi englanniksi   

Diabetic Retinopathy 

#### Vaihtoehtoiset termit ja ilmaisut   

diabeteksen silmäsairaus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[retinopatia](http://www.yso.fi/onto/yso/p19356) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D003930> 
Wikipedia : https://fi.wikipedia.org/wiki/Diabeettinen_retinopatia 
LCSH : <http://id.loc.gov/authorities/subjects/sh85037472> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mechanisms of cell invasion and fibrovascular complications in cancer and diabetic retinopathy 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00826 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [diabeettinen retinopatia](http://finto.fi/yse/fi/page/Y507233)

**Comment by mariaforsen** [comment]
Sv. diabetesretinopati ET diabetisk näthinnesjukdom, näthinnesjukdom vid diabetes
