### ISSUE TITLE
retinopatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7234]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[retinopatia](http://www.yso.fi/onto/ysa/Y98572) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT verkkokalvon sairaudet (tai vaihtoehtoisesti päätermiksi verkkokalvon sairaudet kuten FinMeSHissä) 

#### Perustelut ehdotukselle   

FinMeSH:
retinopatia, retinopatiat KÄYTÄ verkkokalvon sairaudet
http://www.yso.fi/onto/mesh/D012164

Lääketieteen sanasto:
retinopatia
verkkokalvosairaus, verkkokalvotauti

Retinopatia haku Googlella tuottaa tulokseksi lähinnä diabeettista retinopatiaa https://github.com/Finto-ehdotus/YSE/issues/7233 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Lääketieteen termit: verkkokalvosairaus ks. retinopatia (varmaankin tämän mukaan valittu päätermi)

**Comment by ilona-x** [comment]
Melinda: 
retinopatia x 135
retinopatia + diabetes x 114

**Comment by YSA-kokous** [comment]
verkkokalvon sairaudet KT retinopatia

**Comment by mariaforsen** [comment]
Sv. näthinnesjukdomar ET retinopati
