### ISSUE TITLE
Fidzi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7235]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Fidzi 

#### Ehdotettu termi englanniksi   

Fidzi 

#### Vastaava käsite muussa sanastossa   

Fidzi : https://fi.wikipedia.org/wiki/Fid%C5%BEi 

#### Perustelut ehdotukselle   

Puuttuu YSOsta, ulkomaisia kokoelmia luetteloitaessa tarvitaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fidziläinen museoesine 

**Ehdottajan organisaatio:** Kansallismuseo **Termiehdotus Fintossa:** [Fidzi](http://finto.fi/yse/fi/page/Y507235)

**Comment by mirmaid** [comment]
Lisätty ohjaustermi ilman diakriittiä http://www.yso.fi/onto/ysa/Y109282
