### ISSUE TITLE
Uusi Guinea

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7236]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Uusi Guinea 

#### Ehdotettu termi ruotsiksi   

Nya Guinea 

#### Ehdotettu termi englanniksi   

New Guinea 

#### Vastaava käsite muussa sanastossa   

Uusi Guinea : https://fi.wikipedia.org/wiki/Uusi-Guinea 

#### Perustelut ehdotukselle   

Tarvitaan museokokoelmien luetteloinnissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vertailevat kokoelmat 

**Ehdottajan organisaatio:** Kansallismuseo **Termiehdotus Fintossa:** [Uusi Guinea](http://finto.fi/yse/fi/page/Y507236)

**Comment by mirmaid** [comment]
On sanastossa, http://www.yso.fi/onto/yso/p108110
