### ISSUE TITLE
Kiribati

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7239]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kiribati 

#### Vastaava käsite muussa sanastossa   

Kiribati : https://fi.wikipedia.org/wiki/Kiribati 

#### Perustelut ehdotukselle   

Tarvitaan museokokoelmien luetteloinnissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vertailevat kokoelmat 

**Ehdottajan organisaatio:** Kansallismuseo **Termiehdotus Fintossa:** [Kiribati](http://finto.fi/yse/fi/page/Y507239)

**Comment by mirmaid** [comment]
On sanastossa, http://www.yso.fi/onto/yso/p109300
