### ISSUE TITLE
karoliinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7243]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[karoliinit](http://www.yso.fi/onto/ysa/Y105057) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Karoliinit 

#### Perustelut ehdotukselle   

karoliini täytyisi olla YSO-paikat-ontologiassa sillä se on paikka, jota tarvitaan museoaineiston kuvailussa. https://fi.wikipedia.org/wiki/Karoliinit 

#### Ehdottajan organisaatio   

Kansallismuseo

**Comment by mariaforsen** [comment]
YSAn ja Allärsin "karoliinit" ei viittaa yllä olevaan paikkaan. Ks. yläkäsite "sotilaat".

**Comment by jtuohini** [comment]
Varmaankaan ei ole tarkoitus nykyistä _karoliinit_-asiasanaa muuttaa miksikään muuksi, varsinkaan paikannimeksi, vaan ottaa YSOon uutena paikannimeneä **Karoliini** sopivine tarkenteineen – tarkenteineen, ettei sekottuisi samannimiseen kieleen [https://fi.wikipedia.org/wiki/Karoliini]?

**Comment by jtuohini** [comment]
Ja paikka varmaankin on Karoliinit, ei Karoliini, kuten ehdotuksessa on mainittu?

**Comment by mirmaid** [comment]
Karoliinien saaristo
