### ISSUE TITLE
syvästabilointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7248]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syvästabilointi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:978-952-317-552-5 

#### Perustelut ehdotukselle   

https://www.yit.ee/fi/infrastruktuuripalvelut/infrastruktuurin-rakentaminen/betonirakenne-ja-geotekniset-rakennustyot/maaperan-vahvistus/syvastabilointi 

#### Tarkoitusta täsmentävä selite   

Syvästabilointi on pohjanvahvistusmenetelmä, jossa savi-, siltti-, lieju-, tai turvekerros lujitetaan kantavaksi rakennepohjaksi sekoittamalla siihen sideainetta. 

**Termiehdotus Fintossa:** [syvästabilointi](http://finto.fi/yse/fi/page/Y507248)

**Comment by mirmaid** [comment]
YK stabilointi (kemia)

**Comment by mariaforsen** [comment]
Sv. djupstabilisering
