### ISSUE TITLE
merenkulku

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7250]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[merenkulku](http://www.yso.fi/onto/ysa/Y97340) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään tämä ja meriliikenne yhdeksi käsitteeksi. 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirjan määritelmät:
meriliikenne: laivaliikenne meritse, merenkulku
merenkulku: meri-, laivaliikenne
Melindaa nopeasti silmätessäni en huomannut suurtakaan eroa asiasanojen käytössä. Niitä oli käytetty myös samoissa tietueissa. 

#### Ehdottajan organisaatio   

KK

**Comment by ilona-x** [comment]
Melinda:
merenkulku  12717
meriliikenne  2083
laivaliikenne 2358
merenkulku + meriliikenne 1008
meriliikenne + laivaliikenne 324
merenkulku + laivaliikenne 614

SAO: 
Båttrafik (KT sjötrafik, KT fartygstrafik)
Sjöfart (linkattu LCSH Shipping)

YSO: merenkulku KT merenkulkuala (sv. sjöfart) http://www.yso.fi/onto/yso/p2049 linkattu LCSH Navigation)
YSO: laivaliikenne http://www.yso.fi/onto/yso/p1918 linkattu LCSH Shipping

YSOssa lisäksi sisävesiliikenne (vrt. meriliikenne)

**Comment by tpalonen** [comment]
LIIKOssa vain meriliikenne, ei merenkulkua.

**Comment by YSA-kokous** [comment]
Ei muutosta.
