### ISSUE TITLE
mustat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7252]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mustat](http://www.yso.fi/onto/ysa/Y107261) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "tummaihoiset". 

#### Ehdottajan organisaatio   

KK / YSO 

#### Perustelut ehdotukselle   

Suositaan mieluummin neutraalimpaa muotoa.

**Comment by AuHo22** [comment]
Pitäisikö sitten laittaa sekä KT mustat ja KT värilliset
https://fi.wikipedia.org/wiki/V%C3%A4rilliset

**Comment by YSA-kokous** [comment]
Ei muutosta.

**Comment by mirmaid** [comment]
Lisätäänkö tummaihoiset ja värilliset ohjaustermeiksi?
