### ISSUE TITLE
verkkonäkyvyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7253]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkonäkyvyys](http://www.yso.fi/onto/ysa/Y177849) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Digitaalinen jalanjälki (ohjaustermi) on eri asia kuin verkkonäkyvyys, pitäisi olla omana käsitteenään, ei verkkonäkyvyys-termin ohjausterminä. 

#### Perustelut ehdotukselle   

Ks. esim. http://jyuemba.blog.jyu.fi/2016/05/mika-on-digitaalinen-jalanjalki.html 
Jokainen kansalainen jättää päivittäin oman digitaalisen jalanjälkensä - huomaamatta - lukuisiin eri järjestelmiin.

tai: https://www.theseus.fi/handle/10024/123131
Digitaalinen jalanjälki koostuu sekä aktiivisista osista, kuten käyttäjän itsensä jakamasta sisällöstä esimerkiksi sosiaalisessa mediassa, että passiivisista osista, joita ovat esimerkiksi käyttäjän laitteelle tallentuviin evästeisiin tallennetut tiedot tai erilaisten palveluiden rekisteritiedot.

Esim. teos: Sähköiset todisteet rikosprosessissa 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mariaforsen** [comment]
Kannatan. Ainakin ruotsin osalta ovat eri asioita. 
https://sv.wikipedia.org/wiki/Elektroniskt_fotsp%C3%A5r

**Comment by mirmaid** [comment]
Eivät kuitenkaan kovin selkeästi eri asioita: https://sometaduuniin.fi/digitaaliset-urataidot-verkkonakyvyys/, https://jml.kapsi.fi/jussi/2011/04/06/digitaalinen-jalanjalki-isokangas-vassinen/, https://urbaanisanakirja.com/word/verkkonakyvyys/

**Comment by ilona-x** [comment]
**digijalanjälki** https://www.mediataitokoulu.fi/index.php?option=com_content&view=article&id=610:digijalanjalki&catid=11:tehtavat&Itemid=388&lang=fi
**digijälki** https://yle.fi/uutiset/3-6895858

https://en.wikipedia.org/wiki/Digital_footprint

**Comment by mariaforsen** [comment]
Ruotsiksi näitä ei varmaan kannattaisi käyttää ristiin, niin erilainen merkitys ja käyttö (ja sen takia ei lisätty ohjausterminä ruotsiksi).

**Comment by ilona-x** [comment]
Tämä on kyllä hankala tapaus. Verkkonäkyvyys näyttää olevan käytetty lähinnä (digitaalisen) markkinoinnin yhteydessä. Mutta markkinointiin liittyvissä hakutuloksissa näkyy myös tuota digitaalinen jalanjälki -termiä.  Esimerkiksi tämä alunperin v. 2010 ilmestynyt teos: https://shop.almatalent.fi/digitaalinen-jalanjalki-pokkari .

Ongelmalliselta tuntuisi kuitenkin puhua verkkonäkyvyydestä yhteyksissä, joissa puhutaan yksilön verkkoon jättämistä jäljistä, ja siitä miten tätä kertyvää dataa käytetään, ja tähän liittyvistä tietosuoja/yksilönsuoja-asioista. Esim. https://www.sitra.fi/hankkeet/digijalki/

____

verkkonäkyvyys https://www.kielitoimistonsanakirja.fi/#/verkkon%C3%A4kyvyys?searchMode=all
näkyminen tietoverkossa.
Yrityksen verkkonäkyvyys.

**Comment by ilona-x** [comment]
https://www.oph.fi/fi/oppimateriaali/sina-paatat/13-17-vuotiaat/digitaaliset-jaljet
https://www.oph.fi/sv/laromedel/sina-paatat/13-17-vuotiaat/digitala-spar

**Comment by mariaforsen** [comment]
Eli digitaalinen jalanjälki erikseen ja voisiko sitten varmuuden vuoksi tehdä myös "digitaalinen jalanjälki (markkinointi/verkkonäkyvyys)" KÄYTÄ verkkonäkvyys?
Ja verkkonäkyvyydelle pitäisi varmaan lisätä ryhmä 80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta. Sen sijaan digitaalinen jalanjälki voisi olla ryhmässä 45 ja 69.

**Comment by mirmaid** [comment]
Jos nämä on molemmat, ehdottomasti kannattaa lisätä nuo ohjaustermit, vaikka _digitaalinen jalanjälki (verkkonäkyvyys)_ on kyllä taas hyvin lähellä [tätä merkitystä](https://www.mediataitokoulu.fi/index.php?option=com_content&view=article&id=610:digijalanjalki&catid=11:tehtavat&Itemid=388&lang=fi) (tai merkityksiä). Jos aineisto tutkisi esim. yläkouluikäisten itsestään verkossa luomaa tai heistä muodostuvaa kuvaa, kumpaa näistä käytettäisiin (vai ei kumpaakaan)?

Sitten on vielä _digitaalinen jäämistö_.

**Comment by ilona-x** [comment]
Verkkonäkyvyydestä on käytetty englanniksi myös termiä online presence (verkkoläsnäolo, verkkopresenssi 😬 ; sv. digital närvaro)
https://en.wikipedia.org/wiki/Online_presence_management

**Comment by mirmaid** [comment]
Mitä tehdään tälle? _Digitaalinen jalanjälki_ -termiä ei ole käytetty Melindassa. _Verkkonäkyvyys_-aineisto näyttää ainakin valtaosin olevan markkinointia yms. tarkoituksellista näkyvyyden hakemista (tai sen tutkimista). Joukossa on joitakin aineistoja, joissa kyse on _verkkovalvonnasta_ ja joitakin, joihin ehkä sopisi digitaalinen jalanjälki, riippuen nyt vähän siitä mihin näiden kahden käsitteen raja tosiaan sitten asettuisi. Koska myös tämä artikkeli https://en.wikipedia.org/wiki/Digital_footprint mielestäni sisältää molemmat näkökulmat, pitäisi ehkä digitaalinen jalanjälki -käsitteelle lisätä jopa tarkenne (tietoturva?), jos se halutaan ottaa erikseen.

Vaihtoehtoja:
- lisätään ohjaustermiin tarkenne, esim. (markkinointi)
- poistetaan ohjaustermi
- otetaan myös digitaalinen jalanjälki omana käsitteenään (sulkutarkenteella?) (ja lisäksi ohjaustermi verkkonäkyvyyteen) 
- ei tehdä mitään

**Comment by mirmaid** [comment]
_On the other hand, others can reap the benefits by profiting off their digital footprint as social media influencers. Furthermore, employers use a candidate's digital footprint for online vetting and assessing fit due to its reduced cost and accessibility. Between two equal candidates, a candidate with a positive digital footprint may have an advantage. As technology usage becomes more widespread, even children generate larger digital footprints with potential positive and negative consequences such as college admissions. Since it is hard not to have a digital footprint, it is in one's best interest to create a positive one._ https://en.wikipedia.org/wiki/Digital_footprint

**Comment by mariaforsen** [comment]
Kannatan digitaalinen jalanjälki erillisenä terminä (ruotsiksi ja kai englanniksikin nämä käsitellään eri asioina, eikä samaa termiä voi käyttää molemmista asioista). Ohjaustermin lisäys olisi myös hyvä. Se ettei tehdä mitään ei varmaan ole vaihtoehto monikielisyyden kannalta, koska jos käytetään termiä verkkonäkyvyys digitaalisesta jalanjäljestä niin tietueeseen tulee ainakin ruotsiksi väärä termi.

**Comment by YSO-kokous** [comment]
### Päätös
verkkonäkyvyys KT digitaalinen jalanjälki (verkkonäkyvyys)
digitaalinen jalanjälki (tietosuoja)
