### ISSUE TITLE
geovahvisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7255]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

geovahvisteet 

#### Vaihtoehtoiset termit ja ilmaisut   

geolujitteet, geosynteetit 

#### Tarkoitusta täsmentävä selite   

Geovahvisteet eli geolujitteet on tarkoitettu ensisijaisesti parantamaan maarakenteen lujuusominaisuuksia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:978-952-317-585-3 

#### Perustelut ehdotukselle   

https://julkaisut.vayla.fi/pdf9/diat_2012_geolujitekoulutus_web.pdf 

**Termiehdotus Fintossa:** [geovahvisteet](http://finto.fi/yse/fi/page/Y507255)

**Comment by mirmaid** [comment]
7 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. geosynteter ET geoförstärkningar, geoarmeringar

**Comment by mirmaid** [comment]
Jos ruotsinkielinen termi on _geosynteter_, niin onkohan se laajempi? Mahdollista kyllä ottaa se suomeksikin päätermiksi. https://geosynt.files.wordpress.com/2010/09/geosynteetti-juttu.pdf

**Comment by ilona-x** [comment]
https://www.syke.fi/download/noname/%7B5903968F-2B4E-4BEA-BC45-099C7D210D36%7D/117935
s. 32, taulukko 8
geosynteetit = geovahvisteet, geotekstiilit, jne.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa geosynteetit.
