### ISSUE TITLE
avainviulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7256]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

avainviulu 

#### Ehdotettu termi ruotsiksi   

nyckelharpa 

#### Ehdotettu termi englanniksi   

keyed fiddle 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jousisoittimet](http://www.yso.fi/onto/yso/p14229) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85072122> 
Wikidata : https://www.wikidata.org/wiki/Q182718 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.205403 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [avainviulu](http://finto.fi/yse/fi/page/Y507256)

**Comment by mariaforsen** [comment]
Tarvitaan kuvailussa.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by mariaforsen** [comment]
Sv. nyckelharpa ET nyckelfiol
