### ISSUE TITLE
tajunnanvirta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7257]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tajunnanvirta](http://www.yso.fi/onto/ysa/Y107429) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM: medvetandeström-litteratur > medvetandeström 

#### Perustelut ehdotukselle   

medvetandeström-litteratur låter väldigt illa. Eftersom man genom att använda 655 redan visar att det är fråga om ett genreord, förstår jag inte varför man måste göra våld på språket och ta in termer som inte används någon annanstans. Medvetandeström i fält 650 skulle vara tema, i fält 655 genre. Om jag förstått rätt fungerar t.ex. biografier på samma sätt?

**Comment by mirmaid** [comment]
medvetandeström (litteratur)

Tarkenne lisätty erotukseksi esim. elokuvista, koska suomenkielinen termi rajautuu kirjallisuuteen.
