### ISSUE TITLE
big bandit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7258]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[big bandit](http://www.yso.fi/onto/ysa/Y101016) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SEKO-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan SEKO-sanastoon big band -musiikin kuvailuun (nuotit ja äänitteet). 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by jtuohini** [comment]
Arvattavasti perusmuodossa **big band**, LT-suhteenaan _orkesteri_.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
