### ISSUE TITLE
vartalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7259]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vartalo](http://www.yso.fi/onto/ysa/Y110250) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termin määritelmä pitää muuttaa ja ruotsinnos sen mukaan? 

#### Perustelut ehdotukselle   

YSOn määritelmä on: Ihmisruumiin keskeinen osa, johon kaula ja raajat liittyvät. Ja sen mukaan on ruotsinnos tehty. Tämä ei kuitenkaan näytä täsmäävän Melinda-käytön mukaan, vaan siellä näyttää olevan käytetty lähinnä kehon synonyyminä. Tämä termi onkin monimerkityksinen, ks. MOT. YSOn määritelmä ja ruotsinnos ei siis nyt täsmää käytön kanssa.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 1. anat. selkärankaisten ruumiinosa, johon kaula, raajat ja häntä t. pyrstö liittyvät; ihmisruumiin osa, johon pää, kaula ja raajat liittyvät t. koko ruumis päätä lukuun ottamatta.

Ongelma siis ruotsinkielisen termin osalta siinä, kuuluvatko raajat vartaloon vai eivät.

**Comment by mariaforsen** [comment]
?

**Comment by tpalonen** [comment]
Hieman ristiriitainen tuo Kielitoimiston sanakirjan määritelmä. Ensin sanotaan, että se on ruumiinosa, johon raajat liittyvät ja sitten sanotaan, että raajat sisältyvät siihen.

**Comment by ilona-x** [comment]
FinMeSH: 
**vartalo**  
ST lantio
ST rintakehä
ST selkä
ST vatsa
http://www.yso.fi/onto/mesh/D060726

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjassa siis esitetään kaksi vaihtoehtoa - joko niin että raajat eivät kuulu, tai sitten kuuluvat. Suomeksi vartalo voi viitata molempiin.

**Comment by mariaforsen** [comment]
Raajat eivät kuulu nykyiseen ruotsinnokseen (tai muihin mahdollisiin käännöksiin). Mahdoton kääntää oikein ellei ole selkeä merkitys.

**Comment by mariaforsen** [comment]
Jos "koko ruumis päätä lukuun ottamatta" niin ruotsiksi "hela kroppen utom huvudet" Eli olisi varmaan hyvä pysytellä nykyisessä määritelmässä ja lisätä tarkenne? Ja ohjata "vartalo (keho)" (korjaus: vertalo (ruumis)) KÄYTÄ ruumis. Ellei poisto ole mahdollinen...

**Comment by mirmaid** [comment]
Nyt on siis keho KÄ _ruumis, vartalo_.

**Comment by mariaforsen** [comment]
Joo eli vartalo (ruumis) KÄYTÄ ruumis? Että saadaan se "kokovartalo-merkitys" pois tältä termiltä. 

Ja lisätään tarkenne: vartalo (torso) ? Se olisi sitten selkeä ja vastaisi myös Meshin termiä ja muita kieliversioita. Tai mahdollisesti vartalo KÄYTÄ torso?
https://fi.wikipedia.org/wiki/Torso

Tarkoitus ei kai ainakaan ole pitää synonymina (koko) keholle/ruumiille, koska sittenhän ollaan taas samassa ongelmassa kuin oltiin niiden kahden yhdistämisessä (sv. keho=kropp, ruumis=kropp, vartalo=kropp jos EI torso-merkityksessä )

**Comment by mirmaid** [comment]
_Torso_ viittaa suomeksi lähinnä veistoksiin. Melindassa käytetty osittain viitteissä joihin sopisi myös _ruumis_, (esim. _Trans power : own your gender_), osittain vartalotyypeistä tai vartalon esteettisistä ominaisuuksista (_Fat : a cultural history of the stuff of life; Sixpackpakko!_ ) tai anatomian aineistoissa (_Tuki- ja liikuntaelimistön anatomia : opiskelukirja_).

Käytetty Melindassa 398 kertaa. Riittäisikö muissa kuin anatomia yhteydessä _ruumis, ruumiinkuva, ulkonäkö, vartalotyypit_? Anatomian aineistoja on melko pieni osuus käytöstä, osassa niistäkin _ruumis_ olisi mahdollinen.

Jos termi olisi _vartalo (ruumiinosat)_, miellettäisiinkö se kuten ruotsin _bål (kroppen)_?

**Comment by YSO-kokous** [comment]
Yhdistetään ruumis ja vartalo, käytettäväksi termiksi ruumis. Ohjaustermiksi keho JA vartalo. Merkitys viittaa ihmisen koko ruumiiseen raajoineen ja ulokkeineen.
