### ISSUE TITLE
bioala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7260]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[bioala](http://www.yso.fi/onto/ysa/Y175319) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Päätermiksi biotekniikan ala? Vai uutena ohjausterminä? 

#### Perustelut ehdotukselle   

Ks. https://github.com/NatLibFi/Finto-data/issues/937

**Comment by ilona-x** [comment]
Bioala otettu sanastoon v. 2010 ilmeisesti tämän julkaisun kuvailua varten:
http://urn.fi/URN:ISBN:978-952-257-079-6

Tarvitaanko erillisenä tämä ala-päätteinen termi, jos viittaa vain biotekniikan alaan? Biotekniikka on jo sanastossa http://www.yso.fi/onto/ysa/Y94882 . Melinda-viitteiden perusteella kuvailussa välillä kyse myös biotaloudesta tai biolääketieteestä. 

Melinda x 17:

- Tuhannen taalan paikka : Biopankeissa kasvaa investointeja Suomeen (Arto) **biopankit**
- Täsmäeliöt työssään. (Arto) **biologinen torjunta**
- Biotalouden koulutus tähyää tulevaisuuteen. (Arto) **biotalous**
- Life support : biocapital and the new history of outsourced labor / Kalindi Vora. **biotekniikka**
- Suomen metsäsektori monipuolistuu ja uudistuu. (Arto) **biotalous**
- Suomen geenitutkimuksella on käsissään kilpailuvaltti : kantaväestömme yhtenäinen geeniperimä tarjoaisi huimia mahdollisuuksia lääketieteen kehittämiseen. (Arto) **biopankit**, **biotekniikka**
- Bioala nousee. (Arto) **biopankit**
- Biojalostukseen liittyvien teknologiatrendien tarkastelu patenttitilastojen valossa / Pekka Salmi. **biojalostamot**
- Solutasolta systeemi-innovaatioihin : bio- ja liiketoimintaosaaminen Turun ammattikorkeakoulussa / Niina Punelpuro. **biotekniikka**
- Paperitekniikan koulutus muuntuu tulevaisuuden tarpeisiin. (Arto) **biotalous** ym.
- The biobased economy : biofuels, materials and chemicals in the post-oil era **biotalous** ym.
- Työvoiman ja koulutuksen tarvetutkimus 2009 : yhteenveto bio- ja lääkealan työnantajahaastatteluista **biotekniikka**, **biotieteet**, **biotalous**
- Turku ja Karolinska tutkivat yhdessä syöpälääkkeitä. (Arto) **biotekniikka**, **biolääketiede**
- Geeni (Arto) **geenitekniikka**

**Comment by mariaforsen** [comment]
Sv. bioteknikbranschen, eli aika tarkka että mihin tämä oikeasti viittaa..? Ruotsiksi ei ole mahdollista laittaa epämääräistä vastinetta (biobranschen) koska se viittaa taas ihan eri asiaan (elokuvateatteriin..)

**Comment by mirmaid** [comment]
Tarkempiakin termejä on, mutta bioalasta kuitenkin kirjoitetaan paljon, joten en tiedä voiko sitä suorastaan poistaa. Sanastossa on myös muita merkitykseltään laajahkoja bio-alkuisia termejä (_biotalous, biotieteet, bioetiikka, bio-oikeus, bioteollisuus_). Biotekniikka-ala kattaisi varmaankin lähes kaiken mihin bioala viittaa?

Ruotsiksikin biobranschen näkyy käytettävän tässä merkityksessä silloin tällöin, mutta tarkenne toki olisi välttämätön.
https://svenska.yle.fi/artikel/2007/09/12/biobranschen-i-abo-gar-framat
https://miljo-utveckling.se/biobranschen-bildar-global-organisation/

**Comment by ilona-x** [comment]
"Bioalan käsitteellä ei taida olla yksiselitteistä määritelmää, mutta sen voitaneen katsoa olevan biotekniikkaa ja biotieteitä hyödyntävää tuotannollista toimintaa."
Lähde: https://www.finbio.net/ajankohtaiset/blogit/226-bioasioiden-tuntemus-osaksi-yleissivistystae

Edelleen kannattaisin tämän poistamista, kun käyttö on ollut kuitenkin vähäistä (17 viitettä Melindassa, joista 9 viitettä artikkeliaineistoa, ja termi otettu sanastoon v. 2010). Lisäksi suurimmassa osassa viitteitä näihin olisi ollut osuvampikin termi tarjolla, ja monissa tietueissa on jo tämän lisäksi paljon muita bio-alkuisia termejä. Tai jos poistaminen ei ole mahdollista, niin kannatan tämän termin rajaamista biotekniikkaan, eli muutettaisiin bioala -> biotekniikka-ala tmv. (sanastossa on siis jo biotekniikka).

**Comment by FinMeSHienPaimentaja** [comment]
"Biotekniikka" on  eri asia kuin "bioala", "biotekniikka" on / viittaa menetelmiin, "bioala" taas (tieteen)alat. (Tai jos puheena  "biotekniikan ala", se olisi vaan yksi monista "bioalan" alla olevista aloista...)

Pitäisin "bioala"-termin, olkoonkin, että vähän hämärä. Toisaalta maailma tuskin kaatuu, vaikka se poistettaisiinkin ja parempi toki käyttää tarkempia termejä (jos vaan mahdollista).

**Comment by mirmaid** [comment]
Edellä ehdotettu siis

- tilanteen säilyttämistä ennallaan

- bioala-käsitteen poistamista

- bioala-käsitteen poistamista ja uuden biotekniikka-ala -käsitteen ottamista sen tilalle

Mikähän näistä saisi eniten kannatusta?

**Comment by FinMeSHienPaimentaja** [comment]
Poistoa puoltaisi se, että käyttö on vähäistä ja tarkempiakin termejä tarjolla.

**Comment by YSO-kokous** [comment]
Poistetaan käsite. Vähän käytetty käsite ja merkitys epäselvä.
