### ISSUE TITLE
Mustinmäki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7261]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Mustinmäki 

#### Vastaava käsite muussa sanastossa   

Mustinmäen verkkosivut : https://www.mustinmaki.net/ 

#### Perustelut ehdotukselle   

Tarvitaan museokokoelmien luetteloinnissa. Kyseessä esine, joka on Mustinmäki-kylästä, joka sijaitsee Leppävirralla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kansatieteelliset kokoelmat 

**Ehdottajan organisaatio:** Kansallismuseo **Termiehdotus Fintossa:** [Mustinmäki](http://finto.fi/yse/fi/page/Y507261)

**Comment by ilona-x** [comment]
http://paikkatiedot.fi/so/1000772/10221704
