### ISSUE TITLE
yhteistoiminta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7262]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhteistoiminta](http://www.yso.fi/onto/ysa/Y100397) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko tarkemmin määriteltävissä? Esim. "työnantajan ja henkilöstön välistä jatkuvaa vuorovaikutusta ja neuvottelua asioista, jotka vaikuttavat henkilöstön asemaan" ? 

#### Perustelut ehdotukselle   

Ruotsiksi täytyy luoda tarkenne tms. (samarbete på arbetsplatsen?) Sitä varten täytyy tietää mihin tarkalleen tämä viittaa. Sanastossa myös yhteistoimintamenettely ja yhteistyö.

**Comment by ilona-x** [comment]
Käytetty Melindassa 1573 kertaa + ketjut. Muutamia esimerkkejä:

- Yhteistoimintamallit aliurakoinnissa
- Työelämän lait 2018 
- Vlasovin armeija : Stalinin sotilaat Suomen palveluksessa
- Koulun kerhotoiminta edistämässä valmistavan luokan oppilaiden integroitumista
- Seurakunnat terästävät yhteistyötä
- Distributed situation awareness : theory, measurement, and application to teamwork
- Bicycles and plants : designing for conviviality and meaningful social relations through collaborative services
- Diskuteerausta Impivaarassa : selvitys yhteistoiminnan tilasta ja kehittämistarpeista työpaikoilla
- Ensimmäinen vuosi Satakunnassa : kiintiöpakolaisten ja viranomaisten kokemuksia kotoutumisesta Harjavallan, Huittisten ja Ulvilan kaupungeissa : kuntien yhteistoimintamalli pakolaisten kotouttamiseksi -hankkeen raportti
- Collaborative practitioners, collaborative schools 


Olisko yhteistoiminta-termi mahdollista poistaa, ja ohjata käyttämään muuta termistöä, esim. yhteistyö, kumppanuus, yhteistoimintamenettely, työpaikkademokratia?

http://www.tsk.fi/tepa/fi/haku/yhteistoiminta

**Comment by mariaforsen** [comment]
Toivottavasti. Ei ole mahdollista saada oikeaa vastinetta jos merkityksiä on noin paljon.

**Comment by AuHo22** [comment]
Ymmärrän ongelman, mutta kysymyksessä on kuitenkin käyttökelpoinen käsite. Yritysdemokratia tai työpaikkademokratia -käsitteet tuntuvat jotenkin jäävän ikäänkuin menneeseen maailmaan. Yhteistyömenettely terminä ei ole huono, mutta ohjaustermeineen ja yleisessä ajattelussa viittaa yleensä ns. irtisanomis- ja muihin tuotannontehostamistoimiin.
https://fi.wikipedia.org/wiki/Ty%C3%B6paikkademokratia :
"Esimerkiksi Mannevuo on huomauttanut, että tosiasiassa yhteistoimintamenettely on käytännössä muodostunut tehostamis- ja irtisanomistoimenpiteeksi"

Termiä henkilöstöedustus ei ole olemassa, keinotekoiselta kuulostaa puhua työnantajat + työntekijät + yhteistyö? Yhteistoiminnassa on myös lain pakottavuutta, yhteistyössä ei. 
Termiä on myös käytetty sotatilanteiden yhteydessä eri tavoin, mutta toisaalta on sotilaallinen yhteistyö, -apu, kollaboraattorit jne. vivahteineen.

Työelämäkontekstissa on kuitenkin sen verran olennainen käsite, että vaikealta tuntuisi poistaa - voisiko toimia jonkin tarkenteen kanssa?

**Comment by ilona-x** [comment]
Jos tätä ei haluta poistaa niin vaatii tosiaan jonkin tarkenteen, kun pelkkä YSOssa oleva huomautus "Käsitettä käytetään vain työpaikka-, virasto- ja yritysdemokratian yhteydessä; muulloin käytä termiä yhteistyö." ei ole estänyt tämän virheellistä käyttöä.

yhteistoiminta (työpaikkademokratia)?

**Comment by AuHo22** [comment]
yhteistoiminta (työpaikat)?

**Comment by mirmaid** [comment]
Yhteistoimintalaki kuitenkin käsittelee _yhteistoimintamenettelyä_ laajassa merkityksessä, joten oikeastaan ko. termillä pitäisi voida kuvailla muutakin kuin työvoiman vähentämiseen liittyvää toimintaa. https://www.finlex.fi/fi/laki/alkup/2007/20070334

**Comment by ilona-x** [comment]
"Yhteistoimintamenettelyn piiriin kuuluu monia keskeisiä asioita työpaikalla. Tällaisia ovat esimerkiksi henkilöstön asemaan vaikuttavat olennaiset muutokset työtehtävissä, työmenetelmissä ja siirrot tehtävästä toiseen sekä työaikajärjestelyt, kun ne aiheutuvat yrityksen tai sen osan lopettamisesta, siirtämisestä, laajentamisesta tai supistamisesta, tuotevalikoimien tai palvelujen muutoksista, yrityksen tai sen osan lopettamisesta, vuokratyövoiman käyttöä koskevat periaatteet, henkilöstösuunnitelma ja koulutustavoitteet."
Lähde: https://tem.fi/yt-lain-ydinkohdat

"Yhteistoimintalaki ei ole vain irtisanomislaki
Julkisuudessa irtisanomiset saavat usein korostetun aseman, ja ehkä siksi yhteistoimintaneuvottelut usein mielletään vain irtisanomisneuvotteluiksi. "
Lähde: https://tem.fi/neuvotteluvelvollisuus (Linkin takana paljon esimerkkejä yhteistoiminnassa käseiteltävistä asioista)

**Comment by AuHo22** [comment]
YSO:ssa on irtisanominen (voi tarkoittaa yhden henkilön irtisanomista) ja lomautus - pitäisikö olla termi kuten työvoiman vähentäminen? Kun ei voida kuvata yt-neuvotteluilla -

**Comment by YSO-kokous** [comment]
Poistetaan yhteistoiminta. Lisätään yhteistoiminta (työpaikkademokratia) ohjaustermiksi käsitteelle yhteistoimintamenettely.
Lisätään yhteistoiminta (yhteistyö) ohjaustermi käsitteelle yhteistyö.

Tehdään erillinen ehdotus työvoiman vähentämisestä.
