### ISSUE TITLE
rahoitusala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7263]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rahoitusala](http://www.yso.fi/onto/ysa/Y169088) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄYTÄ finanssiala tai toisinpäin, jos ovat yhdistettävissä? 

#### Perustelut ehdotukselle   

Ks. esim. http://www.finanssialalle.fi/opintomateriaalit/tulevaisuuden-finanssiala/tulevaisuuden-pankki/lopputulema.html  https://www.studentum.fi/tietoa-tyoelamasta/tyoelamatietoa-ammattialoista/rahoitusala-13207  http://www.finanssiala.fi/finanssialasta/Sivut/default.aspx

**Comment by mariaforsen** [comment]
Molemmat eng. financial sector

**Comment by mirmaid** [comment]
Päätermiksi varmaan mieluummin _rahoitusala_?

**Comment by mirmaid** [comment]
Rahoitusala tarjoaa pankki-, vakuutus- ja sijoituspalveluja. https://www.studentum.fi/tietoa-tyoelamasta/tyoelamatietoa-ammattialoista/rahoitusala-13207

**Comment by tpalonen** [comment]
IATE (https://iate.europa.eu) esittää rahoitusalan ja finanssialan synonyymeinä.

**Comment by ilona-x** [comment]
Mutta tuolla IATEssa on tuo yllä mainitsemani huomautus eli eivät olisi tuon mukaan täysin sama asia:

> rahoitusala
> Note: Suppeampi merkitys, joka ei kata esim. vakuutusalaa.

**Comment by ilona-x** [comment]
Finannsiala ry;n sivuilla puhutaan ainakin erikseen rahoitusalasta ja vakuutusalasta esim.:

- Koulutus-sivulla puhutaan erikseen rahoitusalasta & vakuutusalasta https://www.finanssiala.fi/finanssialasta/finanssialan-koulutus

- Rahoitusalan TES & Vakuutusalan TES erikseen: https://www.finanssiala.fi/materiaalipankki/tyoehtosopimukset/Sivut/default.aspx

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet (vrt. ruotsi ja englanti). Päätermin valinnasta (rahoitusala vs finanssiala) äänestettiin. Rahoitusala sai enemmän ääniä. Päätermiksi rahoitusala, ohjaustermiksi finanssiala. Vakuutusalalle myös ohjaustermiksi finanssiala.

**Comment by ilona-x** [comment]
Entä **pankkiala** http://www.yso.fi/onto/yso/p15487?
Ollut YSAssa finanssialan alakäsite, mutta YSOssa YK toimialat
