### ISSUE TITLE
taseet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7265]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taseet](http://www.yso.fi/onto/ysa/Y99329) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nykyiset alakäsitteet siirrettävä muualle? Jos tämä viittaa talouteen. 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja: taseet =kirjanpitotileistä määrävälein laadittava (senhetkisen tilitilanteen osoittava) kaksipuolinen laskelma, bilanssi Laajemmin Kauppa-, maksu-, vaihtotase. Matkailutase. Myös Gummerus: yrityksen rahoitusasema tilinpäätöshetkellä
Ruotsiksi eri termi riippuen merkityksestä, nyt talousryhmän mukaan eli balansräkningar.

**Comment by mariaforsen** [comment]
https://www.talousverkko.fi/mika-on-tase-ja-mita-se-kertoo/
https://fi.wikipedia.org/wiki/Tase
https://sv.wikipedia.org/wiki/Balansr%C3%A4kning

**Comment by mirmaid** [comment]
Jäisikö alakäsitteiksi _maksutase_ ja _matkustustase_?

**Comment by ilona-x** [comment]
**matkustustase** :

> "Matkustustase kuvaa tarkastelun kohteena olevan maan kansainvälisten matkailutulojen ja -menojen suhdetta. Matkustustase on positiivinen, jos maassa käyneiden ulkomaisten matkailijoiden tuomat tulot ovat suuremmat kuin maan asukkaiden kulutus ulkomaanmatkoilla. Tase on negatiivinen, jos menot ovat suuremmat kuin tulot."
Lähde: https://www.businessfinland.fi/suomalaisille-asiakkaille/palvelut/matkailun-edistaminen/tutkimukset-ja-tilastot/matkustustase

----
fi      **maksutase**
en      balance of payments
määritelmä
Kansantalouden ja muiden maiden väliset liiketoimet kuvattuna tietyn ajanjakson kuluessa. Maksutaseesta ilmenevät maan tavat saada ja menettää ulkomaista valuuttaa. Maksutase jakaantuu useisiin alatileihin. Näistä keskeisiä ovat kauppatase, vaihtotase, perustase ja yleistase. Ks. kauppatase, vaihtotase, perustase, yleistase.
	  
Lähde: Tieteen termipankki 08.12.2020 https://tieteentermipankki.fi/wiki/Taloustiede:maksutase

**Comment by ilona-x** [comment]
Jos taseet olisi jatkossa vain yrityksen kirjanpitoon liittyvä käsite, niin varmaan maksutase ja matkustustase pitäisi myös siirtää muualle. 🤔 

MOT Ruotsin tekniikka ja kauppa; ru-su
balansräkning
tase, omaisuustase, tasetili

MOT Ruotsin tekniikka ja kauppa; su-ru
tase
balans, balansräkning

**Comment by mirmaid** [comment]
^ Onkohan taseet-termiä käytetty vain yrityksistä?

**Comment by ilona-x** [comment]
Melindasta 100 uusinta viitettä, joista 2 muuta kuin kirjanpitoa ja yritysten/organisaatioiden taseita. 
1 x kasvihuonekaasutase (siirretty 653)
1 x sähkötasehallinta

100 vanhimman viitteen joukossa oli enemmän hajontaa, esim. kansantalouden tilinpitoon liittyviä viitteitä, mutta suurin osa vanhemmistakin viitteistä käsitteli kuitenkin kirjanpitoa ja yritysten ja yhteisöjen taseita.

**Comment by mariaforsen** [comment]
Ruotsin kannalta ei tosiaan ole mahdollista pitää "taseet" jonkinlaisena yleisterminä, vaan on saatava tarkempi merkitys, eli liiketalous/kirjanpito =balansräkningar
https://termipankki.fi/tepa/fi/haku/tase

Tähän liittyen niin YSOssa tasapaino=balans on vain ryhmässä 07 ja 48, mutta Melindassa käytetty myös paljon laajemmin (issue tehty)

**Comment by YSO-kokous** [comment]
Lisätään tarkenne taseet (kirjanpito).  Kaikki alakäsitteet siirtyvä muualle. 
Tarvittaessa lisätään ohjaustermejä.
