### ISSUE TITLE
mongoloidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7266]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mongoloidit](http://www.yso.fi/onto/ysa/Y97486) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan? 

#### Perustelut ehdotukselle   

Huomautuksena nyt: "Vanhentunut nimitys henkilöstä, jolla on Downin oireyhtymä. Ei suositella käyttäväksi" Eli aika hämmentävä tilanne, saako tätä edes käyttää asiasanana, ja onko se sitten korrektia että tällaisia sanoja näkyy asiakkaillekin jne.

**Comment by YSA-kokous** [comment]
Poistetaan.
