### ISSUE TITLE
SLM / kasvutarinat / kehityskertomukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7267]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM / kasvutarinat / kehityskertomukset 

#### Perustelut ehdotukselle   

http://www.koulukino.fi/kasvukertomus
"Kehityskertomus ja kasvutarina ovat usein käytettyjä määritelmiä, kun puhutaan elokuvien ja romaanien ja muiden tarinoiden henkilöiden/hahmojen kasvusta ja kehityksestä tarinan aikana."

https://peda.net/p/RailiK/%C3%A4i1-10t-kivr/kleg

https://en.wikipedia.org/wiki/Bildungsroman
There are many variations and subgenres of Bildungsroman that focus on the growth of an individual. An Entwicklungsroman ("development novel") is a story of general growth rather than self-cultivation. An Erziehungsroman ("education novel") focuses on training and formal schooling,[18] while a Künstlerroman ("artist novel") is about the development of an artist and shows a growth of the self.[19] Furthermore, some memoirs and published journals can be regarded as Bildungsroman although being predominantly factual (e.g. "The Dharma Bums" by Jack Kerouac or The Motorcycle Diaries by Ernesto "Che" Guevara).[20] The term is also more loosely used to describe coming-of-age films and related works in other genres. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Romaanien kuvailussa, joihin sisältyy henkilön kehityskertomus / kasvutarina ja jotka eivät kuitenkaan ole kehitysromaaneja. Ks.ed. "The term is also more loosely used to describe coming-of-age films and related works in other genres." 

**Ehdottajan organisaatio:** Kirjastopalvelu

**Comment by mirmaid** [comment]
Keskustellaan Kaunokki-kokouksessa (erityisesti miten kirjallisuuden kuvailussa nämä erottuvat toisistaan).

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7213

**Comment by mirmaid** [comment]
Kehityskertomukset (romaanit) KÄ kehitysromaanit / SLM

**Comment by mirmaid** [comment]
YSOssa vain _kehitysromaanit_, lisätäänkö myös _kehityskertomukset_ ja ohjaustermi SLM:n mukaan?

**Comment by YSA-kokous** [comment]
Hyväksytään kehityskertomukset, ohjaustermi SLM:n mukaan.

**Comment by mariaforsen** [comment]
Sv. utvecklingsberättelser 
http://finto.fi/slm/fi/page/s1341
