### ISSUE TITLE
roséviini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7268]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

roséviini 

#### Ehdotettu termi ruotsiksi   

rosévin 

#### Ehdotettu termi englanniksi   

rosé 

#### Vastaava käsite muussa sanastossa   

LCSH : Rosé wines 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. Sanastossa on jo esimerkiksi termit omenaviini ja portviini. Samoin puuttuvat termit punaviini ja valkoviini tulisi myös lisätä sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vad vore livet utan rosé? 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [roséviini](http://finto.fi/yse/fi/page/Y507268)

**Comment by mirmaid** [comment]
Yksikkö vai monikko? Vrt. _viinit_-käsitteen alakäsitteet.

**Comment by YSA-kokous** [comment]
Kaikki yksikössä, samoin muut viinit-käsitteen alakäsitteet yksikköön.
