### ISSUE TITLE
mehiläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7270]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mehiläiset](http://www.yso.fi/onto/ysa/Y97327) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

hunajamehiläiset KT mehiläiset, Apis? 

#### Perustelut ehdotukselle   

Mihin tämä viittaa? YSOssa lat. muoto Apis mellifera, mutta sehän viittaa tarhamehiläiseen? https://fi.wikipedia.org/wiki/Tarhamehil%C3%A4inen Ks. myös https://laji.fi/taxon/MX.204771?locale=fi#show Onko oikeastaan sellaista kuin "mehiläiset"? Ei ainakaan Laji.fissä.

**Comment by mirmaid** [comment]
Ja sitten vielä maijamehiläiset, ovatko he tarhamehiläisiä vai hunajamehiläisiä :honeybee: :thinking:

**Comment by mariaforsen** [comment]
Tarhamehiläinen=honungsbi/tambi hyvä ja tarpeellinen päätermi

**Comment by mirmaid** [comment]
^ Hunajamehiläiset olisi siis suku Apis, ruotsiksi honungsbin, eli varmaan sv. päätermiksi hyvä tuo tambi jos myös hunajamehiläiset otetaan erikseen (ja tarvitseeko silti tarkenteen (släkt)?).

**Comment by mariaforsen** [comment]
Joo vaatii tarkenteen siinä tapauksessa.

**Comment by YSA-kokous** [comment]
tarhamehiläinen
