### ISSUE TITLE
toimittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7271]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toimittajat](http://www.yso.fi/onto/ysa/Y99577) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pitäisikö lisätä tarkenne esim. toimittajat (media)

TSR-ontologiassa toimittajat (media) ja toimittajat (tuotteen) 

#### Perustelut ehdotukselle   

Käytetty myös tavaran-, palvelu- ja järjestelmäntoimittajista (YSAssa on erikseen tavarantoimittajat)

Esimerkkejä Melindasta:
Loginet : toimittajayhteistyö tilausohjautuvissa toimitusketjuissa
Järjestelmätoimittajuus teknologiateollisuudessa : toimialan rakenne, strategiset ryhmät ja kannattavuus 
Alihankkijasta järjestelmätoimittajaksi - mahdollisuus kasvaa ja menestyä 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Pitäisikö lisätä "toimittajat (tuotteen)" KÄYTÄ tavarantoimittajat?

**Comment by YSA-kokous** [comment]
toimittajat (media)
