### ISSUE TITLE
halogeenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7272]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[halogeenit](http://www.yso.fi/onto/ysa/Y106896) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarvitseeko tarkenteen esim. halogeenit (alkuaineet) ja lisäksi halogeenilamput/-valot? 

#### Perustelut ehdotukselle   

käytetty Melindassa myös merkityksessä halogeenivalot esim.:
Satasen valoremontti : halogeeni- ja ksenonvalojen kunnostus.
Ledit haastavat halogeenit
Kohdevalot ovat nopeat asentaa 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
_Halogeenilamput_ sopisi muiden lamppujen seuraksi, mutta riittäisikö ohjaus halogeenit (lamput) KÄ halogeenilamput? Sinänsähän tuo _halogeenit_ ei ole väärin halogeenilamppujenkaan yhteydessä.

**Comment by YSA-kokous** [comment]
Halogeenilamput KT halogeenit (lamput)
