### ISSUE TITLE
biosentrismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7273]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

biosentrismi 

#### Ehdotettu termi englanniksi   

biocentrism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[filosofia](http://www.yso.fi/onto/yso/p1056) 
[ympäristöfilosofia](http://www.yso.fi/onto/yso/p7952) 

#### Alakäsitteet (RT)   

[ympäristöetiikka](http://www.yso.fi/onto/yso/p11283) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Tarkoitusta täsmentävä selite   

https://tieteentermipankki.fi/wiki/Filosofia:biosentrismi
"Definition näkemys, joka antaa kaikille eläville olioille jonkinlaisen moraalisen arvon ja oikeutuksen olemassaoloon sekä palauttaa ihmisen yhdeksi eläinlajiksi muiden joukkoon ja muista riippuvaksi
Explanation Etiikassa biosentrimi merkitsee näkemystä, joka asettaa elävän luonnon ja sen hyvän etiikan lähtökohdaksi. Samalla katsotaan, että kaikilla elävillä olioilla on jonkinlainen moraalinen arvo." 

#### Perustelut ehdotukselle   

Tarvittu sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/HRVKBE5C7B9ELTVS7Q8MR7YH7V256K479D346J64HBU4TRMB8A-01529?func=full-set-set&set_number=022281&set_entry=000001&format=999 

**Termiehdotus Fintossa:** [biosentrismi](http://finto.fi/yse/fi/page/Y507273)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. biocentrism

**Comment by LeKorsu** [comment]
Sanoman arkistosta yksi osuma 20 vuoden takaa.
