### ISSUE TITLE
sähköisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7274]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sähköisyys](http://www.yso.fi/onto/ysa/Y99148) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa tai KÄYTÄ sähkövaraus, staattinen sähkö jne? 

#### Perustelut ehdotukselle   

Ei löydy määritelmää sanastoista ja sanakirjoista, olisiko sen sijaan (sanastossa jo oleva) sähkövaraus ammattimaisempi termi? Ja joissakin tietueissa mieluummin staattinen sähkö? Vrt. myös ruotsiksi ja englanniksi.

**Comment by mirmaid** [comment]
Välillä näyttäisi sopivan myös _sähkönjohtavuus_ tai ihan vaan _sähkö_.

**Comment by YSA-kokous** [comment]
Poistetaan.
