### ISSUE TITLE
imppaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7276]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

imppaus 

#### Ehdotettu termi ruotsiksi   

sniffning 

#### Ehdotettu termi englanniksi   

Inhalant Abuse 

#### Vaihtoehtoiset termit ja ilmaisut   

liuotinaineiden haitallinen käyttö 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D058545> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85124743> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Adolescent substance use and risk of psychosis in the Northern Finland Birth Cohort 1986 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [imppaus](http://finto.fi/yse/fi/page/Y507276)

**Comment by mirmaid** [comment]
3 viitettä Melindassa, yksi käsittelee hevosia, joten vaatii ehkä tarkenteen?

**Comment by LeKorsu** [comment]
Imppaus on Kaunossa, siellä ruotsinkielisenä terminä sniffande.

**Comment by tpalonen** [comment]
Ohjaustermiksi imppaaminen? Entäpä ohjaustermeiksi myös liiman haistelu ja bensan haistelu (näillä tulee kumpaisellakin 400+ Google-hittejä)?

**Comment by YSA-kokous** [comment]
Imppaus (päihteet)

**Comment by mariaforsen** [comment]
Kaunon ruotsinkielinen vastine kannattaisi muuttaa > sniffning /SAO
