### ISSUE TITLE
Vepsä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7278]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Vepsä](http://www.yso.fi/onto/ysa/Y111676) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös merkityksessä Vepsä (Turku) 

#### Perustelut ehdotukselle   

Käytetty myös tässä merkityksessä Melindassa, esim. "Tall Ships’ Races Turussa 23. - 26.7."

**Comment by mirmaid** [comment]
Turun saari lisätty. Toinen tarvitsee tarkenteen (Venäjä?), mahdollinen myös > Vepsänmaa.

**Comment by mirmaid** [comment]
Vepsänmaa
