### ISSUE TITLE
Reykjavik

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7279]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Reykjavik 

#### Ehdotettu termi ruotsiksi   

Reykjavik 

#### Ehdotettu termi englanniksi   

Reykjavik 

#### Perustelut ehdotukselle   

Tarvitaan sekä tieto- että kaunoaineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Arnaldur Indriðason: Skuggor över Reykjavik 

**Ehdottajan organisaatio:** Kirjastopalvelu

**Comment by ilona-x** [comment]
Tämä on YSAssa/YSO-paikoissa:  http://www.yso.fi/onto/ysa/Y109865
