### ISSUE TITLE
atsuleenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7282]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

atsuleenit 

#### Ehdotettu termi ruotsiksi   

azulener 

#### Ehdotettu termi englanniksi   

azulenes 

#### Ehdotettu yläkäsite YSOssa (LT)   

[PAH-yhdisteet](http://www.yso.fi/onto/yso/p10718) 
[aromaattiset hiilivedyt](http://www.yso.fi/onto/yso/p23503) 

#### Vastaava käsite muussa sanastossa   

MeSH : https://finto.fi/mesh/fi/page/D052176 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Synthesis of azulene-based compounds for targeting orexin receptors /Teppo O. Leino. 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [atsuleenit](http://finto.fi/yse/fi/page/Y507282)

**Comment by mirmaid** [comment]
Yksikkö vai monikko?
