### ISSUE TITLE
Steiner-koulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7285]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Steiner-koulut](http://www.yso.fi/onto/ysa/Y94419) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Oikea kirjoitusasu on "steinerkoulut". 

#### Perustelut ehdotukselle   

Ks. esim. Kielitoimiston sanakirja. 

#### Ehdottajan organisaatio   

Sanastokeskus

**Comment by AuHo22** [comment]
Kielitoimiston sanakirjan mukaan myös steinerpedagogiikka - YSOssa ohjaussuhteet tällä hetkellä toisinpäin.
