### ISSUE TITLE
kulttuurihistorialliset rakennukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7287]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kulttuurihistorialliset rakennukset](http://www.yso.fi/onto/ysa/Y96490) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ensisijaiseksi termiksi "kulttuurihistoriallisesti merkittävät rakennukset". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mielestä "kulttuurihistorialliset rakennukset" on huono termi, koska periaatteessa kaikki rakennukset liittyvät kulttuurihistoriaan. Sen sijaan vain osa on kulttuurihistoriallisesti merkittäviä. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Google
kulttuurihistorialliset rakennukset 5140 kertaa
kulttuurihistoriallisesti merkittävät rakennukset 863 kertaa

**Comment by ilona-x** [comment]
Tähän vielä lisäyksenä, että nykyinen KT-muoto "kulttuurihistoriallisesti arvokkaat rakennukset" tuo Googlella 2080 osumaa

**Comment by YSA-kokous** [comment]
KT kulttuurihistoriallisesti merkittävät rakennukset
