### ISSUE TITLE
rivitalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7288]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rivitalot](http://www.yso.fi/onto/ysa/Y98613) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "asuinrakennukset". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan rivitalot eivät ole pientaloja. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by ilona-x** [comment]
"pientaloja, joissa on tehty jako omakoti-, pari- ja rivitaloihin"

Lähde: http://www.terminfo.fi/sisalto/rakennusluokitus-on-uudistettu-556.html

"011 Pientalot
Tavanomaisia tila- ja varusteratkaisuja sisältävät asuinrakennukset, joissa on korkeintaan yksi kerros tai, jos kerroksia on enemmän, asuinhuoneistot eivät yleensä ole osittainkaan päällekkäin. Pientaloissa asuintilana on asuinhuoneisto. **Pientaloja ovat omakotitalot, paritalot ja rivitalot.**"

Lähde: http://www.stat.fi/meta/luokitukset/rakennus/001-2018-07-12/011.html

**Comment by mirmaid** [comment]
Englanninkieliset vastineet tälle ja alakäsitteille tarkistettava.
