### ISSUE TITLE
asumukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7289]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asumukset](http://www.yso.fi/onto/ysa/Y110313) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi yläkäsite. 

#### Perustelut ehdotukselle   

"Rakennukset" ei ole sopiva yläkäsite, koska asumukset-käsitteen alakäsitteet (iglut, kodat, kammit, jurtat) eivät ole rakennuksia. MAO/TAOssa yläkäsitteenä on "ihmisen määrittämät paikat". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjan määritelmät tukevat nykyistä hierarkiaa.
