### ISSUE TITLE
autiotuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7290]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[autiotuvat](http://www.yso.fi/onto/ysa/Y100942) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsite "ulkoilumajat" poistetaan. 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan autiotuvat eivät ole ulkoilumajoja. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _lepo- ja yöpymismaja erämaassa, autiomaja._

**Comment by mirmaid** [comment]
RT ulkoilumajat
