### ISSUE TITLE
suojelukohteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7291]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suojelukohteet](http://www.yso.fi/onto/ysa/Y99072) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "muu rooli". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan suojelukohteet eivät aina liity paikkoihin. Siksi "paikkaan liittyvä rooli" ei ole hyvä yläkäsite. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Muutettu.
