### ISSUE TITLE
taidehistorioitsijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7292]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taidehistorioitsijat](http://www.yso.fi/onto/ysa/Y110995) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "tutkijat". 

#### Perustelut ehdotukselle   

"Tutkijat" on tarkempi yläkäsite kuin nykyinen "ammatit". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Siirretään päin vastoin folkloristit pois.
