### ISSUE TITLE
empire

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7293]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[empire](http://www.yso.fi/onto/ysa/Y101242) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "uusklassismi". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan empire on eräs uusklassismin muoto. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Korjattu.
