### ISSUE TITLE
kustavilainen tyyli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7294]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kustavilainen tyyli](http://www.yso.fi/onto/ysa/Y102851) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan kustavilainen tyyli on eräs uusklassismin muoto. 

#### Ehdotettu muutos   

Yläkäsitteeksi "uusklassismi". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Korjattu.
