### ISSUE TITLE
leikkimökit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7295]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leikkimökit](http://www.yso.fi/onto/ysa/Y103078) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "rakennukset". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan leikkimökit ovat rakennuksia, ei rakennelmia. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
On jo korjattu.
