### ISSUE TITLE
basse danse

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7296]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

basse danse 

#### Ehdotettu termi ruotsiksi   

basse danse 

#### Ehdotettu termi englanniksi   

basse danse 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85012180> 
Wikidata : https://www.wikidata.org/wiki/Q810479 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.636286 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [basse danse](http://finto.fi/yse/fi/page/Y507296)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.
