### ISSUE TITLE
tuuliviirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7297]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tuuliviirit](http://www.yso.fi/onto/ysa/Y104691) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsite on vaihdettava. Ehdotan yläkäsitteeksi "mittauslaitteet". 

#### Perustelut ehdotukselle   

Tuuliviirit-käsitteen yläkäsite on tällä hetkellä "viirit", jonka yläkäsite on "symbolit". Vaikuttaa siltä, että "viirit" viittaa kapeisiin lippuihin, joten se ei sovi "tuuliviirien" yläkäsitteeksi. Lisäksi tuuliviirit eivät ole symboleja. Museoviraston ontologiatyöryhmä ehdottaa yläkäsitteeksi "mittauslaitteet". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
YK esineet
