### ISSUE TITLE
paliskunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7298]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[paliskunnat](http://www.yso.fi/onto/ysa/Y118893) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Virheellisesti kaksi yläkäsitettä; toinen on poistettava. 

#### Perustelut ehdotukselle   

Termi "paliskunnat" voi viitata joko organisaatioon tai alueeseen. Tietty käsite ei kuitenkaan voi olla yhtä aikaa sekä organisaatio että alue. Täytyy valita, kumpi merkitys YSOon halutaan, tai luoda käsitteet "paliskunnat (organisaatiot)" ja "paliskunnat (alueet)". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Poistettu toinen yläkäsite.
