### ISSUE TITLE
branle

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7299]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

branle 

#### Ehdotettu termi ruotsiksi   

branle 

#### Ehdotettu termi englanniksi   

branle 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q898742 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.636286 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [branle](http://finto.fi/yse/fi/page/Y507299)

**Comment by mirmaid** [comment]
Kerran Melindassa
