### ISSUE TITLE
embleemit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7301]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[embleemit](http://www.yso.fi/onto/ysa/Y109906) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käsitteillä "embleemit" ja "symbolit" tulisi olla sama yläkäsite; nyt edellisen yläkäsite on "merkit" ja jälkimmäisen "tieto". 

#### Perustelut ehdotukselle   

Koska embleemit ja symbolit rinnastuvat toisiinsa, niillä pitäisi olla sama yläkäsite. Museoviraston ontologiatyöryhmän mielestä "tieto" on hyvä yläkäsite myös käsitteelle "embleemit". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mariaforsen** [comment]
Tieto on sv. kunskap YSOssa, eli tieto=kunskap olisi ainakin ruotsiksi aivan virheellinen yläkäsite termille embleemit=emblem. 

YSOssa on myös data= sv. data ja informaatio= sv. information, joten tieto pitänee olla jatkossakin sv. kunskap.

**Comment by mirmaid** [comment]
Tieto-käsitteen alakäsitteitä ollaan käymässä läpi YSOn ylläpitoryhmässä, ks. https://github.com/NatLibFi/Finto-data/issues/859. Hierarkia tulee todennäköisesti muuttumaan, mutta tällä hetkellä ei katsottu, että symbolit soveltuisivat merkit-käsitteen alakäsitteeksi, koska symbolit-käsite voidaan tulkita myös abstraktimmin. Embleemit sen sijaan sopii merkit-käsitteen alakäsitteeksi ongelmattomammin.
