### ISSUE TITLE
jakkarat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7302]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jakkarat](http://www.yso.fi/onto/ysa/Y185426) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkempi yläkäsite "istuimet". 

#### Perustelut ehdotukselle   

Jakkarat ovat istuimia, aivan kuten rahit, penkit ja tuolit. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Tästä on jo päätös: https://github.com/Finto-ehdotus/YSE/issues/5177, https://github.com/Finto-ehdotus/YSE/issues/5197.

**Comment by mirmaid** [comment]
Ei muutoksia.
