### ISSUE TITLE
gaillarde

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7303]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gaillarde 

#### Ehdotettu termi ruotsiksi   

galliard 

#### Ehdotettu termi englanniksi   

galliard 

#### Vaihtoehtoiset termit ja ilmaisut   

galliarda [fin] 
gagliarda [fin] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2011000870> 
Wikidata : https://www.wikidata.org/wiki/Q288824 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.636286 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [gaillarde](http://finto.fi/yse/fi/page/Y507303)

**Comment by mirmaid** [comment]
Kerran Melindassa
