### ISSUE TITLE
courante

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7304]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

courante 

#### Ehdotettu termi ruotsiksi   

courante 

#### Ehdotettu termi englanniksi   

courante 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q664056 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.636286 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [courante](http://finto.fi/yse/fi/page/Y507304)

**Comment by mirmaid** [comment]
Kerran Melindassa
