### ISSUE TITLE
volta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7306]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

volta 

#### Ehdotettu termi ruotsiksi   

volta 

#### Ehdotettu termi englanniksi   

lavolta 

#### Vaihtoehtoiset termit ja ilmaisut   

la volta [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q664056 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.636286 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [volta](http://finto.fi/yse/fi/page/Y507306)

**Comment by mirmaid** [comment]
Kerran Melindassa. Ehdotettuja tanssien nimiä käytetty tietueessa muodossa _volta (tanssit)_ jne. Tanssilajit on auktorisoitu sulkutarkenteella aina kun vastaava termi on auktorisoitu myös sävellyksenä.

**Comment by YSA-kokous** [comment]
Ei tarkennetta
