### ISSUE TITLE
kansallismaisema

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7307]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansallismaisema](http://www.yso.fi/onto/ysa/Y113384) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "kulttuurimaisema". 

#### Perustelut ehdotukselle   

Kulttuurimaisema on tarkempi yläkäsite. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Onko tosiaan näin? Varmaan monelle ensimmäisenä tulee mieleen Koli, lisäksi esim. Saaristomeri, Pallastunturit, https://fi.wikipedia.org/wiki/Suomen_kansallismaisemat.

**Comment by mirmaid** [comment]
Ei muutosta.
