### ISSUE TITLE
kolmiomittaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7308]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kolmiomittaus](http://www.yso.fi/onto/ysa/Y96289) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "mittausmenetelmät". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan kolmiomittaus on menetelmä ennemmin kuin mittausta toimintana. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Mittausmenetelmillä ei ole tällä hetkellä alakäsitteitä ja mittauksen alla on muita vastaavia. Monihierarkia ei ole mahdollinen.
