### ISSUE TITLE
perustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7309]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[perustukset](http://www.yso.fi/onto/ysa/Y98090) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "rakenteet". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan perustukset eivät ole rakennusosia. MAO/TAOssa yläkäsitteiksi valittiin "rakennusten osat" ja "rakenteet". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Paalut YK elottomat objektit RT perustukset. Ei muita muutoksia.
