### ISSUE TITLE
hallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7310]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hallit](http://www.yso.fi/onto/ysa/Y131380) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Joko sulkutarkenne "(tilat)" ja assosiatiiviset suhteet täytyy poistaa tai yläkäsiteeksi täytyy vaihtaa "tilat". 

#### Perustelut ehdotukselle   

Ristiriitaa sulkutarkenteessa ja yläkäsitteessä. Halli rakennuksena (esim. kuplahalli) on eri käsite kuin halli tilana (esim. eteishalli). Nyt sulkutarkenne ja assosiatiiviset suhteet (aulat ja huoneet) viittaavat tilaan, mutta yläkäsite on silti rakennukset. Käsitteen merkitys jää epäselväksi. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 1. suuripinta-alainen matalahko (teollisuus-, myymälä-, urheilutiloja tms. sisältävä) rakennus; avara (keskus)tila julkisissa rakennuksissa, sali. 2. eteiseen liittyvä t. eteisen tapainen, tav. ikkunaton huonetila asuinhuoneistoissa.

Meilläpä lapsuudenkodissa halli oli yläkerrassa tila portaikon jälkeen, josta kuljettiin makuuhuoneisiin, vintille ja parvekkeelle. Ikkunat oli myös.

**Comment by mariaforsen** [comment]
Sama tilanne ruotsiksi.

**Comment by ilona-x** [comment]
Suurin osa Melinda-viitteistä käsittelee hallirakennuksia, mutta löytyy myös muutamia viitteitä hallitiloista esim.:

- New lobbies & waiting rooms 
- Das Piano nobile :eine abendländische Raumkategorie 

LCSH:ssa Entrance halls, joka linkattu YSO-käsitteisiin aulat & eteiset.

Riittäisikö hallit (rakennukset) ja hallit (tilat) KÄYTÄ aulat, eteiset?

**Comment by YSA-kokous** [comment]
hallit (rakennukset) ja hallit (tilat) KÄYTÄ aulat, eteiset
