### ISSUE TITLE
devising

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7311]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[devising](http://www.yso.fi/onto/ysa/Y199061) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi menetelmät? 

#### Perustelut ehdotukselle   

Ks. esim. http://oppimateriaali.wikidot.com/devising: "teatterin tekemisen tavat, joissa ennalta laadittua käsikirjoitusta ei ole" - eli devising näyttäisi olevan menetelmä. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5438

**Comment by mirmaid** [comment]
Ei muutosta.
