### ISSUE TITLE
esikaupungit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7312]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[esikaupungit](http://www.yso.fi/onto/ysa/Y101307) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "ihmisen määrittämät alueet". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan esikaupungit eivät ole kaupunginosia. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Ehdotukselle kaivattiin perusteluja.
