### ISSUE TITLE
lähiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7313]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lähiöt](http://www.yso.fi/onto/ysa/Y100714) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "ihmisen määrittämät alueet". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan lähiöt eivät ole kaupunginosia. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Tälle muutosehdotukselle kaivattiin perusteluja.
