### ISSUE TITLE
huoneteatterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7314]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huoneteatterit](http://www.yso.fi/onto/ysa/Y200904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "tilat". 

#### Perustelut ehdotukselle   

Vaikka on olemassa mm. Jyväskylän Huoneteatteri, huoneteatteri viittaa terminä ensisijaisesti esitystilaan (ks. esim. Kielitoimiston sanakirja). 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Tästä on tehty päätös kertaalleen, ks. https://github.com/Finto-ehdotus/YSE/issues/5175

**Comment by mirmaid** [comment]
Ei muutosta aikaisempaan päätökseen.
