### ISSUE TITLE
kertaustyylit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7315]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kertaustyylit](http://www.yso.fi/onto/ysa/Y101124) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Päätermiksi "historismi". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan "historismi" on nykyään yleisemmin käytetty nimitys tälle käsitteelle. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
_Näitä tyylejä kutsutaan joskus myös yhteisnimikkeellä historismi, sillä kertaustyylit olivat hyvin historiatietoisia, ja niiden tyyli-ihanteet perustuivat aiempina aikakausina vallinneisiin tyylisuuntiin_ https://fi.wikipedia.org/wiki/Kertaustyylit

YSOssa historismi on kuitenkin olemassa eri merkityksessä, YSOn määritelmä: _näkemys, jonka mukaan historian kulkua eivät ohjaa mitkään ikuiset lait tai historian "lopussa" toteutuva päämäärä, vaan kutakin aikakautta määräävät sen oma luonne ja sen omat sisäiset lainalaisuudet._

Tieteen termipankki: _1. näkemys, jonka mukaan kulttuuri on historiallisen kehityksen tulosta, eikä inhimillistä todellisuutta voi ymmärtää irrallaan historiasta
2. näkemys, jonka mukaan on olemassa erityisiä historian kehityslakeja, joiden puitteissa inhimillinen ja yhteiskunnallinen kehitys väistämättä tapahtuu_

**Comment by mariaforsen** [comment]
Voisi olla ruotsiksi historicism (arkitektur)?

**Comment by tpalonen** [comment]
Rajautuuko pelkästään arkkitehtuuriin? Enkku-Wikipediassa otsikkona "Historicism (art)" ja sanotaan, että on yleistä erityisesti arkkitehtuurissa, mutta ei kuitenkaan sanota, että rajautuisi siihen. 
https://en.wikipedia.org/wiki/Historicism_(art)

**Comment by YSA-kokous** [comment]
KT historismi (arkkitehtuuri)

**Comment by mariaforsen** [comment]
Sanastossa nyt myös sekä historismi että historisismi

**Comment by mirmaid** [comment]
^ Ilmeisesti Spectrum tietokeskuksen mukaan nämä ovat kaksi päinvastaista näkemystä :slightly_smiling_face:

**Comment by mariaforsen** [comment]
https://tieteentermipankki.fi/wiki/Historia:historisismi
https://sv.wikipedia.org/wiki/Historism

**Comment by mirmaid** [comment]
Onko näitä kuitenkaan tarpeen yhdistää, jos ovat erotettavissa? Määritelmät voisi perustaa Tieteen termipankkiin Spectrumin sijaan.

https://sv.wikipedia.org/wiki/Historicism_(filosofi_och_historia)

**Comment by YSO-kokous** [comment]
Säilytetään molemmat. Tarkistetaan määritelmät suhteessa Tieteen termipankkiin.
