### ISSUE TITLE
koristemaalarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7316]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koristemaalarit](http://www.yso.fi/onto/ysa/Y150712) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsiteeksi "maalarit", ehkä myös "käsityöläiset". 

#### Perustelut ehdotukselle   

Koristemaalari ei ole kuvataiteilija, vaan erilaisiin pintakäsittelytöihin erikoistunut maalari. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
Korjattu.
