### ISSUE TITLE
väestöongelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7318]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väestöongelmat](http://www.yso.fi/onto/ysa/Y100331) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan KT-muoto liikakansoitus käytettäväksi termiksi tai otetaan se omaksi käsitteekseen. 

#### Perustelut ehdotukselle   

Tällä hetkellä sanastossa väestöongelmat KT liikakansoitus, mutta onko tämä paras mahdolllinen ratkaisu. Väestöongelmat on terminä jokseenkin epämääräinen (ensimmäiset google-osumat Fintoa ja Yle.fi aihetermejä)

Melindassa tätä on käytetty paljon liikakansoituksen mutta myös nälänhätien yhteydessä. Nälänhädille on kuitenkin ollemassa tarkempikin termi, liikakansoitukselle ei (väestönkasvu ei määrity yhtä selkeästi ongelmaksi).

Tarve nousi esille YSO-wikidata-linkitysten yhteydessä. 

#### Ehdottajan organisaatio   

KK

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:liikakansoitus

**Comment by mariaforsen** [comment]
Tarvitaan kyllä nimenomaan överbefolkning=liikakansoitus. Myös SAOssa (befolkningsproblem ei)
Väestöongelmat on itse asiassa käytetty ihan vastakkaisessa merkityksessäkin, eli hyvin epämääräinen termi.

**Comment by ilona-x** [comment]
YSOssa myös **väestökato** (sv. folkminskning, eng. depopulation) http://www.yso.fi/onto/yso/p2952 kuvaamaan tuota vastakkaista tilannetta, mutta sitä ei ole kaikissa tapauksissa käytetty. Olisiko väestökadolle mahdollista lisätä ohjaustermejä, jotta tuota uskallettaisiin käyttää kun väestökato kuulostaa ehkä vähän hurjalta? 😃 

fi        väestökato ; väestön väheneminen ; väkiluvun pieneneminen 
sv       avfolkning 
en      depopulation ; population decline 
https://termipankki.fi/tepa/fi/haku/v%C3%A4est%C3%B6kato

**Comment by mirmaid** [comment]
Ehdotetut lisäykset ovat ok, mutta poistetaanko siis _väestöongelmat_? Ei ole korvattavissa suoraan _liikakansoitus_-käsitteellä Melindassa, mutta jos poistetaan, viitteet on käytävä läpi, koska ainakin niissä tapauksissa keskeinen termi jäisi pois.

**Comment by AuHo22** [comment]
Väestöongelmat on tarpeellinen laajempi termi kokoamaan eri ilmiöitä. Engl. po. population issues?
http://www.vbgraphics.com/Quaker/Publications/ECO-PDFs/QEB4-6-population.pdf

**Comment by mariaforsen** [comment]
Minäkin kannatan laajempana terminä väestöongelmat.

**Comment by ilona-x** [comment]
alkuperäinen ehdotus:

> **Vaihdetaan KT-muoto liikakansoitus käytettäväksi termiksi tai otetaan se omaksi käsitteekseen.**


Eli siis oltaisiinko nyt ottamassa omaksi käsitteekseen tuo liikakansoitus?  Ja YSOssa olisi sitten väestöongelmat, väestökato ja uutena terminä liikakansoitus?

**Comment by AuHo22** [comment]
Omana terminään tarpeellinen -> liikakansoitus

**Comment by YSO-kokous** [comment]
Otetaan sanastoon liikakansoitus. Jätetään sanastoon myös väestöongelmat. Korjataan mahdollisuuksien puitteissa nykyistä väestöongelmat-kuvailua lisäämällä tarvittaessa liikakansoitus-käsite.
