### ISSUE TITLE
tunnusvärit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7319]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tunnusvärit](http://www.yso.fi/onto/ysa/Y104666) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "fyysiset ominaisuudet". 

#### Perustelut ehdotukselle   

Tunnusvärit eivät ole väriaineita. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/803

**Comment by mirmaid** [comment]
Väri ja värit (aine) on yhdistetty, tarkenne on poistettu.
