### ISSUE TITLE
suojaväri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7320]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suojaväri](http://www.yso.fi/onto/ysa/Y200779) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi vain "fyysiset ominaisuudet" (eli "värit" poistetaan). 

#### Perustelut ehdotukselle   

Suojavärit eivät ole väriaineita. 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/803

**Comment by mirmaid** [comment]
Väri ja värit (aine) on yhdistetty, tarkenne on poistettu.
