### ISSUE TITLE
makulointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7321]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

makulointi 

#### Ehdotettu termi ruotsiksi   

makulering 

#### Perustelut ehdotukselle   

Tv ohjelma joka käsittelee Tuomas Timosen makulointiin menevän kirjan tuhoamista silppurin sijasta taiteilijoiden käsissä erinäisenä taideprojektina. Ohjelma problematisoi kustantamoiden makulointikäytäntöjä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirjastotarinoita: Erään kirjan elinkaari 

**Ehdottajan organisaatio:** Kansallinen audiovisuaalinen instituutti **Termiehdotus Fintossa:** [makulointi](http://finto.fi/yse/fi/page/Y507321)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

Kielitoimiston sanakirja: tehdä makulatuuriksi; tehdä (painotuote) mitättömäksi, mitätöntää, mitätöidä. _Makuloida painoarkit. Makuloidut veromerkit._ 

Tässä siis vähän eri merkityksessä (myymättä jääneen painoksen hävittäminen).

**Comment by mariaforsen** [comment]
Eivätkö nämä merkitykset ole tarpeeksi lähellä toisiaan että voisi hyväksyä termin sellaisenaan yleisessä merkityksessä?
