### ISSUE TITLE
marmorointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7322]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[marmorointi](http://www.yso.fi/onto/ysa/Y107357) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi "maalaus (pintakäsittely)". 

#### Perustelut ehdotukselle   

Museoviraston ontologiatyöryhmän mukaan marmorointi on nimenomaan pintakäsittelyä eikä varsinaisesti liity kuvataiteeseen, joten "maalaus (pintakäsittely)" on parempi yläkäsite kuin "maalaus (kuvataide)". 

#### Ehdottajan organisaatio   

Sanastokeskus/Museovirasto

**Comment by satuniininen** [comment]
Melindassa tätä on eniten käytetty (taide)käsitöiden ja askartelun yhteydessä, esim.
[Taidekäsityö](https://melinda.kansalliskirjasto.fi/byid/006257000)[
Marmorering och ådring : förlagor för dekorationsmålning](https://melinda.kansalliskirjasto.fi/byid/006544366)
[Paperitöiden iso ideakirja : paperista kaikkea kivaa itselle ja lahjaksi ](https://melinda.kansalliskirjasto.fi/byid/000312325)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5190

**Comment by mirmaid** [comment]
Marmorointi, ootraus YK maalaus (pintakäsittely), RT koristemaalaus.
