### ISSUE TITLE
Käännösiskelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7323]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Käänösioskelmä 

#### Ehdotettu termi ruotsiksi   

Översatt schlager 

#### Ehdotettu termi englanniksi   

Translated schlager music 

#### Tarkoitusta täsmentävä selite   

Ulkomaisen iskelmäkappaleen suomenkielinen versio. 

#### Perustelut ehdotukselle   

Tämä olisi hyödyllinen kuvailemaan ohjelmaa Iskelmä-Suomi, jossa monessa jaksossa todetataan monta kertaa että suomalaiset iskelmät varsinkin 50-, 60- ja 70-luvuilla olivat pääosassa juuri käännösiskelmiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Iskelmä-Suomi - TV-sarja vuodelta 2013 

**Ehdottajan organisaatio:** Kansallinen audiovisuaalinen instituutti **Termiehdotus Fintossa:** [Käänösioskelmä](http://finto.fi/yse/fi/page/Y507323)

**Comment by jtuohini** [comment]
Varmaankin monikossa (_käännösiskelmät_). RT-muodoksi ehkä _cover-versiot_? LT-muodoiksi _iskelmät_ ja _käännökset_.

**Comment by jtuohini** [comment]
Aika vahva lähde Marian ruotsinkieliselle muodolle: https://litteraturbanken.se/%C3%B6vers%C3%A4ttarlexikon/artiklar/Schlager%C3%B6vers%C3%A4ttning

**Comment by tpalonen** [comment]
Olisiko RT sanoitukset myös käypä?

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

Selite voisi olla väljempi: "Iskelmän käännösversio".

LT iskelmät, käännökset, sanoitukset
RT cover-versiot

**Comment by YSA-kokous** [comment]
Hyväksytään Muusan edellä ehdottamalla tavalla. Sanoitukset ei tosin tässä käyne yläkäsitteeksi, YSO-ryhmä pohtii tältä osin.

**Comment by jtuohini** [comment]
LT-suhde sanoituksiin olikin lajiltaan _part of_ -tyyppinen: kaikki käännösiskelmät sisältävät sanoituksen, joka on käännetty. Kyse ei siis _is a_ -suhteesta.
