### ISSUE TITLE
sankarivainajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7325]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sankarivainajat](http://www.yso.fi/onto/ysa/Y102072) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan KT-muoto "sankarivainajat" englannin- ja ruotsinkielisistä viittauksista. 

#### Perustelut ehdotukselle   

Kyseisellä sanalla tuskin etsitään englanniksi tai ruotsiksi, ja suomeksi viittausmuoto sanastossa jo ennestään on. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Poistettu.
