### ISSUE TITLE
mikrosimulointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7326]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikrosimulointi 

#### Ehdotettu termi englanniksi   

microsimulation 

#### Ehdotettu termi ruotsiksi   

mikrosimulering 

#### Perustelut ehdotukselle   

Tarkennus simulointi-käsitteelle. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Microsimulation, http://urn.fi/URN:NBN:fi-fe2016061321503 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Mikrosimulointi 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mikrosimulointi](http://finto.fi/yse/fi/page/Y507326)

**Comment by LeKorsu** [comment]
Melinda x 10
Google + 16400
Sanoman arkisto x 6

**Comment by ilona-x** [comment]
Toimiva linkki esimerkkiaineistoon: http://hdl.handle.net/10138/38871 "Microsimulation. Statistical methodology and assessment of uncertainty"

LCSH: Statistical matching (KT Microsimulation modeling (Statistics))  http://id.loc.gov/authorities/subjects/sh2002004458
TERO: mikrosimulointi http://www.yso.fi/onto/tero/t255
