### ISSUE TITLE
hengelliset lastenlaulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7328]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hengelliset lastenlaulut](http://www.yso.fi/onto/ysa/Y214494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

tarvetta on 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto

**Comment by jtuohini** [comment]
LT hengelliset laulut
LT lastenlaulut

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
