### ISSUE TITLE
sävelasteikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7329]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sävelasteikot](http://www.yso.fi/onto/ysa/Y200894) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

soitonoppaiden (nuotit) kuvailu 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto

**Comment by MUUSA-kokous** [comment]
Muusa ei kannata termin lisäämistä SLM:ään. Soitonoppaiden kuvailussa voi käyttää vastaavaa YSO-termiä.
