### ISSUE TITLE
bagassi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7331]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bagassi 

#### Ehdotettu termi ruotsiksi   

bagasse 

#### Ehdotettu termi englanniksi   

sugarcane bagasse 

#### Vaihtoehtoiset termit ja ilmaisut   

sokeriruokojäte 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hydrotropic process for green biorefinery applications, http://urn.fi/URN:ISBN:978-952-12-3663-1 

#### Perustelut ehdotukselle   

Puuttuu sanastosta. 

#### Tarkoitusta täsmentävä selite   

Käytetään raaka-aineena. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [bagassi](http://finto.fi/yse/fi/page/Y507331)

**Comment by mirmaid** [comment]
Ei Melindassa.

https://en.wikipedia.org/wiki/Bagasse

**Comment by mariaforsen** [comment]
Sv. bagass

**Comment by ilona-x** [comment]
https://tilastokeskus.fi/meta/luokitukset/cpa/001-2015/10.81.html
