### ISSUE TITLE
viherryttäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7332]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viherryttäminen 

#### Vaihtoehtoiset termit ja ilmaisut   

viherrytys 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viljelymenetelmät](http://www.yso.fi/onto/yso/p593) 
[viljelymenetelmät](http://www.yso.fi/onto/yso/p593) 

#### Alakäsitteet (RT)   

[nurmiviljely](http://www.yso.fi/onto/yso/p2668) 
[viljely](http://www.yso.fi/onto/yso/p5098) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Tarkoitusta täsmentävä selite   

https://etela-pohjanmaa.proagria.fi/sites/default/files/attachment/viherryttaminen_ja_pysyvat_nurmet_2017.pdf 

#### Perustelut ehdotukselle   

Tarve sis.kuvailussa. Käytetty vapaana asiasanana Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/696DRBLN8C6B725KJVTFDQQYJ9JGP22N63M9HXECVF45LB9DNL-00032?func=full-set-set&set_number=297993&set_entry=000002&format=999 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [viherryttäminen](http://finto.fi/yse/fi/page/Y507332)

**Comment by ilona-x** [comment]
fi        viherryttäminen 
sv       förgröning ; miljöanpassning 
en      greening 
Lähde: http://www.tsk.fi/tepa/fi/haku/viherrytt%C3%A4minen

https://en.wikipedia.org/wiki/Greening

https://www.ruokavirasto.fi/viljelijat/tuet-ja-rahoitus/viherryttamistuki/

**Comment by mirmaid** [comment]
6 viitettä Melindassa

**Comment by LeKorsu** [comment]
55 osumaa Sanoman arkistossa

**Comment by mariaforsen** [comment]
Siinä tapauksessa förgröning (nimenomaan viljelyyn liittyvä), eli aika eri asia kuin tämä https://en.wikipedia.org/wiki/Greening

**Comment by ilona-x** [comment]
Mikä ihmeen viherryttäminen? Maatalousviidakon lyhyt sanakirja https://yle.fi/uutiset/3-6705772

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Maanviljelyyn rajattuna olisi varmaankin _viherryttäminen (maanviljely)_.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa viherryttäminen (maanviljely).

**Comment by mariaforsen** [comment]
Sv. förgröning
https://www.ruokavirasto.fi/sv/odlare/stod-och-finansiering/forgroningsstod/
