### ISSUE TITLE
fantasia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7333]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fantasia](http://www.yso.fi/onto/ysa/Y113919) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista rajata huomautuksella? Esim. "taiteiden ja kirjallisuuden genre/tyyli" tms. 

#### Perustelut ehdotukselle   

Ruotsiksi pitää lisätä tarkenne (fantasi (genre/stil...)), mutta ensin täytyy varmistaa että viitataan samaan asiaan, ja Melindassa on käytetty myös muissa merkityksissä. Ja sanakirjoissa määritellään:
-MOT Dictionary of Contemporary Finnish
fantasia: mielikuvitus, kuvitteellisuus; kuvitelma. Taiteellinen fantasia. Sairaan oudot fantasiat.
Mus. improvisoidun luonteinen vapaamuotoinen sävellys. 
-MOT Gummerus New Finnish Dictionary
fantasia: 1 (luova) mielikuvitus Fantasiakirjallisuus. 2 epätodellinen kuvitelma Hänen mielessään liikkui kaikenlaisia fantasioita. 3 mus. eräänlainen vapaamuotoinen sävellys

**Comment by mirmaid** [comment]
Scifissä ei ole ollenkaan kaikkien aineistojen yhteistä genretermiä, ja myös fantasian osalta on olemassa vastaavat suppeammat.

**Comment by AuHo22** [comment]
Sulkutarkenteen avulla? vrt. burleski (tyylit) & burleskit (sävellykset) -> fantasia (tyylit) & fantasiat (sävellykset)

**Comment by mirmaid** [comment]
Mutta olisiko loogisempaa ratkaista fantasia ja scifi keskenään samalla tavalla, eli joko kummallekin vain elokuvat/kirjallisuus/pelit/sarjat -käsitteet tai sitten molemmille (vain/myös) laajempi?

**Comment by AuHo22** [comment]
Kaunokirjallisuuden kuvailussa on joka tapauksessa tyylinä tarpeellinen, eli voidaanko sitten kuitenkin säilyttää Kauno-sanastossa tyylinä, esim. Melinda 015291583

**Comment by mariaforsen** [comment]
Molemmat ratkaisut käy ruotsin osalta, pääasia että tarkennetaan ja saadaan mahdollisimman pian korjattua. 
SAOssa on https://id.kb.se/term/saogf/Fantasy https://id.kb.se/term/sao/Fantasy%20%28litteratur%29 ja https://id.kb.se/term/saogf/Fantasyfilmer

**Comment by mirmaid** [comment]
Ainakin KAUNO/SLM-ryhmät voisivat myös käsitellä tätä, ehkä myös fiktioaineistoryhmä. Jos otetaan sekä yhteinen laaja genre (fantasia, scifi), että suppeammat, miten johdonmukaisena pysyy kuvailu?

_Kyberpunk_ ja _steampunk_ ovat nyt _spekulatiivisen fiktion_ alla - jos päätetään ottaa _fantasia_ ja _scifi_, eikö tämä olisi niille luontevampi paikka kuin _tyylit_? Silloin fantasian tarkenne voisi olla (fiktio)?

**Comment by mariaforsen** [comment]
Tarkoitus oli kommentoida, tarkenne voi varmaan olla fiktio riippumatta yläkäsitteestä, jos se koetaan toimivimmaksi. Ruotsin osalta YK fiktio olisi myös ok.

**Comment by YSO-kokous** [comment]
Odotetaan kauno- ja fiktioryhmien ratkaisua. Jos jää sanastoon, tarkenne on (fiktio).

**Comment by mirmaid** [comment]
KAUNO-ryhmä kannattaa muotoa _fantasia (fiktio)_. Mielestäni ryhmä yleisesti kannatti sekä fantasialle, että scifille laajempia lajityyppien yhteisiä termejä, mutta en muista tätä varmasti (?).

**Comment by AuHo22** [comment]
Meidän Kauno-ryhmäläiseltä tuli kommentti:
Kauno ryhmä päätti näin:
YSO:lle fantasia (fiktio). KAUNO: poistetaan fantasia

sitä on käytetty kaunoaineistossa kuvaamaan nimenomaan mielikuvitusta eikä genrenä, joten poistettiin Kaunosta.

-> Eli ilmeisesti ei tarvita tyylinäkään, tietysti on muita termejä sitten, kuten esim. surrealismi jne., joita voi tarvittaessa käyttää tyyliä kuvatessa.

**Comment by YSO-kokous** [comment]
Jatketaan tutkimista mm. kuvataiteen osalta.

**Comment by mirmaid** [comment]
Esim. tällaisia aineistoja yhdistelmällä _fantasia & kuvataide_:
https://melinda.kansalliskirjasto.fi/byid/005991484
https://melinda.kansalliskirjasto.fi/byid/010014489
https://melinda.kansalliskirjasto.fi/byid/007185258
https://melinda.kansalliskirjasto.fi/byid/010033053
https://melinda.kansalliskirjasto.fi/byid/006097927

**Comment by ilona-x** [comment]
Olisiko fantasiataide mahdollinen termimuoto? https://fi.wikipedia.org/wiki/Fantasiataide
Vai ovatko LCSH-termi "Fantasy in art" ja joissakin Mirjan listaamissa viitteissä mainittu "Fantasy art" kaksi eri asiaa 🤔 

Ja näköjään wikipediasta löytyi myös englanninkielinen artikkeli:  https://en.wikipedia.org/wiki/Fantastic_art

**Comment by AuHo22** [comment]
Fantasy art vs. fantastic art
http://www.all-art.org/history659_fantastic1.html

**Comment by jarmosaarikko** [comment]
edellisesti poimittuna:

> _Fantasy has been an integral part of art since its beginnings, but has been particularly important in mannerism, romantic art, symbolism and surrealism. **fantastic art** celebrates fantasy, imagination, dreamworlds, the grotesque, visions and other-worldliness. With symbolism, it shares its choice of themes such as mythology, occultism and mysticism._

> _In French, the genre is called le fantastique, in English it is sometimes referred to as visionary art, grotesque art or mannerist art._

> _Fantastic art should not be confused with **fantasy art**, which is the domain of science-fiction and fantasy illustrators_

**Comment by jarmosaarikko** [comment]
fantastic art --> kuvitteellinen taide, fantastisk konst  ??
fantasy art --> fantasiataide,  fantasikonst  ??
- Näissä olisi ehkä hyvä olla selventävä käyttöhuomautus.

**Comment by mirmaid** [comment]
Tyylien alla on nyt sulkutarkenteina (taide), (tyylit) ja (runous). Fantasialle (tyylit) sopii mielestäni vähän huonosti, koska fantasia-genre liittyy enemmän teoksen aihepiiriin kuin sen tyylilajiin, enkä osaa sanoa, erottelisiko se myöskään täysin musiikista. Tyylit-tarkenne on toistaiseksi burleskilla, verismillä ja pastoraalilla. 

Fantasian lisäksi myös scifi ja steampunk ovat ymmärrettävissä vähän laajemminkin kuin fiktio(kertomusten) genrenä. Scifin osalta "fiktio" on toisaalta mukana termissäkin. Myös science fiction -taide (science fiction art) -termejä käytetään kuvataiteesta. Voiko ajatella, että fiktio-tarkenne kattaisi myös kuvataiteen: fantasia (fiktio) KT fantasiataide? Fantasia (kuvataide) tms. on toki mahdollinen myös erikseen, mutta kattaisivatko scifi ja steampunk kuitenkin myös kuvataiteen (ja vaatteet ym.)?

**Comment by mariaforsen** [comment]
Sv-termeinä ei voi olla yllä ehdotetut fantastisk konst tai fantasikonst. Fantasiataide olisi fantasykonst jos viitataan tosiaan fantasyyn genrenä (eli tolkien jne.) Toiselle merkitykselle mahdollisesti "imaginär konst" tms., tutkittava lisää (jos on pakko sekin ottaa).

**Comment by AuHo22** [comment]
Alunperin kai oli kyse löytää vastine kirjallisuuden kuvailulle silloin, kun fantasia toimii yhtenä (tyyli)elementtinä teoksessa, mutta kyse ei ole varsinaisesta fantasiakirjallisuudesta sisällöllisesti? Ja onko tässä nyt kuvataiteen kohdalla vähän samanlainen erottelu, eli: _fantasy art, which is the domain of science-fiction and fantasy illustrators_, jossa varsinaisesti ollaan ns. oikean fantasiafiktion puolella, kun taas sitten, jos halutaan sanoa fantasia (kuvataide), niin silloin fantasia toimii kuvauksen elementtinä kuten esim. Boschilla, joka kuvaa raamatullista aiheita fantasiankin avulla, mutta en aihetta kutsuisi fantasiaksi (pikemminkin allegoria) -> _Fantasy has been an integral part of art since its beginnings, but has been particularly important in mannerism, romantic art, symbolism and surrealism. fantastic art celebrates fantasy, imagination, dreamworlds, the grotesque, visions and other-worldliness. With symbolism, it shares its choice of themes such as mythology, occultism and mysticism._

**Comment by mirmaid** [comment]
Vielä hiukan tarkentelua - sanastoon on siis (käsittääkseni) haluttu käsite, joka merkitykseltään erottuu _fantasioista (mielikuvitus)_ ja _musiikista (fantasioiksi nimitetyistä sävellyksistä)_, mutta kattaa _**kaiken muun**_ (fantasiakirjallisuuden, -elokuvat, -sarjat, -pelit, sekä _**mahdollisesti** kuvataiteen_ - en osaa sanoa kattaako se vain fantasiafiktioon liittyvän kuvataiteen, vai myös fantastisia elementtejä sisältävän kuvataiteen - ja _fantasia-elementit_ myös muissa ilmenemismuodoissa (voiko olla esim. joku cosplay).

Tälle pitäisi siis saada tarkenne, siinä laajuudessa kuin työryhmä sen haluaa olevan käytössä (eli jos esim. _steampunk_ kattaa kaikki genret, maalaustaiteen ja pukeutumisen, täydellisenä ja elementteinä, niin varmaankin fantasian olisi selkeintä olla yhtä laaja).

**Comment by YSO-kokous** [comment]
PÄÄTÖS 
käsite ei rajaudu pelkästään fiktioon tai kirjallisuuteen eikä muihin taiteisiin, vaan kattaa myös pukeutumisen ym.
fantasia (tyylit) - sv: fantasy, en: fantasy (style)
fantasia (taide) KÄYTÄ fantasia (tyylit)
fantasy (imagination)  KÄYTÄ  mielikuvitus

**Comment by mirmaid** [comment]
Fantasiat: lisätään tarkenne (musiikki). Ei muita muutoksia.
