### ISSUE TITLE
esittely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7334]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[esittely](http://www.yso.fi/onto/ysa/Y109682) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastossa on myös monikollinen termi, joten ainakin yksikölle tarvitaan sulkutarkenne. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Esittely on ryhmässä "71 Hallinto. Organisaatiotutkimus. Julkinen hallinto" ja ruotsinnos sen mukaisesti föredragning. Olisiko mahdollista lisätä tarkenne (päätöksenteko/menettely) tms. ? Sillä tavalla varmistetaan myös että kyseessä on sama käsite eri kielillä, eli ". valmistellun asian esittäminen päätöksentekijän ratkaistavaksi; tällainen tilaisuus." /Kielitoimiston sanakirja. Ks. myös http://www.tsk.fi/tepa/fi/haku/esittely ja https://tieteentermipankki.fi/wiki/Oikeustiede:esittely

Monikollinen termi esittelyt sen sijaan on ryhmässä "00 Yleistermit" ja RT:nä on demonstraatiot, se viittaa siis eri asiaan ja vastinekin on sen mukaisesti presentationer.

**Comment by ilona-x** [comment]
YSOn esittely-termiä on käytetty Melindassa kaikesta mahdollisesta esittelystä, esim.:

- Catwalk kuvaruudulla : tapaustutkimus vaatemalliston suunnittelusta ja multimedian käytettävyydestä sen esittelyssä
- Oman kotiseudun luonnonkukat tutuiksi :Kiimingin Koitelissa retki tarjosi myös oivan annoksen paikallishistoriaa ja geologiaa 
- Pölkkysaviraknetaminen tutuksi Järvikylällä 
- KM listaa markkinoiden uudet tuotantopanokset. Kiinnostavat uutuudet.
- Jouluraitti huurusti ikkunat :Kankaanpääntien vanhat talot kiinnostivat 
- Mäyräkoira on yksi monipuolisimmista  roduista.
- Hunajan esittelijän muistio.

Moniin sopisi korvaajaksi esittelyt tai sitten termin voi jättää kokonaan pois.

**Comment by mirmaid** [comment]
Tämän otsikon äärellä jälleen mykistyy äidinkielensä hienoudesta:

_Henkilöstöpalvelualallla toimivan rekrytointikonsultin työhön liittyvän työnhakijasta tehtävän esittelytekstin kirjoittamisen ohjeistus : toimintatutkimuksellisella otteella tehty tutkimus rekrytointikonsultin työn kehittämiseksi_

**Comment by mirmaid** [comment]
Toisinaan korvattavissa myös > _esittelijät_. Jonkin verran käytetty muototermin tapaan, aineistossa esitellään jotakin (ei käsitellä aiheena esittelyä).

**Comment by YSO-kokous** [comment]
Poistetaan YSOsta esittely.

**Comment by mirmaid** [comment]
YSOn ylläpitoryhmä päätti palauttaa tämän vielä uudelleen käsiteltäväksi. Onko tarpeen säilyttää alkuperäisessä merkityksessä ja lisätä tarkenne?

**Comment by mariaforsen** [comment]
Kannatan säilyttämistä muodossa esittely (hallinto, päätöksenteko tms.) = föredragning
https://termipankki.fi/tepa/fi/haku/esittely 

Melindassa esim. Esittely- ja kokousmenettelyohjeet. ; Hallintoasiain esittely / Ilpo Luoto ; Kunnan hallintomenettely / Heikki Harjula, Riitta Laakso ; Kokouskäytäntö / Kari Lunnas... Näille ei siis voi laittaa "esittelyt" tms. asiasanaksi, koska se viittaa eri asiaan. 

YSO-termi esittelyt voi sitten jatkossakin viitata yleiseen esittelemiseen.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8889

**Comment by mirmaid** [comment]
Esittely (päätöksenteko/päätöksentekomenettely/hallinto)?
