### ISSUE TITLE
sijoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7335]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sijoitus](http://www.yso.fi/onto/ysa/Y107074) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsisi tarkenteen 

#### Perustelut ehdotukselle   

Tätä käytetään paljon kuvailtaessa sijoitustoimintaa käsittelevää aineistoa. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Sanastossa lisäksi monikollinen _sijoitukset_.

**Comment by mariaforsen** [comment]
MOT Gummerus New Finnish Dictionary antaa kolme (relevanttia) merkitystä sijoitukselle, pitäisikö ainakin ne huomioida? Talousmerkityksessä on ainakin niin eri merkitys että tarvitaan varmaan tarkenne.

**Comment by ilona-x** [comment]
YSOssa siis nyt:
sijoitus http://www.yso.fi/onto/yso/p6567
sijoittuminen http://www.yso.fi/onto/yso/p22292
sijainti http://www.yso.fi/onto/yso/p1467
sijoitustoiminta KT sijoitus (varainhoito) http://www.yso.fi/onto/yso/p4321
sijoitukset http://www.yso.fi/onto/yso/p4319

---

Kielitoimiston sanakirja:
https://www.kielitoimistonsanakirja.fi/#/sijoitus?searchMode=all
sijoitus
1. sijoittaminen.
Tavaroiden sijoitus paikoilleen.
Urh.
vrt. sijoittaa 1. erik. b.
Ratkaisi [tenniksessä] erän tarkoilla sijoituksillaan.
2. tapa jolla jk on sijoitettu; sijainti.
Keittiön kalusteiden huono sijoitus hankaloittaa taloustöitä.
3. jhk sijoitettu rahamäärä tm. omaisuus.
Liikkeen ulkomaiset sijoitukset.
4. vars. urh. sijoittuminen; asema kilpailussa.
Loppusijoitus.

**Comment by mirmaid** [comment]
Käytetty n. 1300 kertaa Melindassa, mutta ainakin uudemmista viitteistä niin suuri osa liittyy sijoitustoimintaan, että on vaikea poimia joukosta viitteitä, joissa olisi oikeasti tarvittu _sijoitus_-käsitettä. Ainakin joihinkin niistäkin sopisi _sijainti_.

**Comment by ilona-x** [comment]
Melindassa näyttää olevan myös todella paljon (ydin)jätteen loppusijoitusta käsittelevää aineistoa, joka on kuvailtu sijoitus -termillä. Loppusijoitus otettu sanastoon vasta v. 2011, mikä selittää asian.

**Comment by mirmaid** [comment]
^ Pitäisikö taas alkaa kuoria pois näitä, joille on olemassa toinenkin termi?

**Comment by mirmaid** [comment]
Vielä vähän lukuja:
sijoitustoiminta x 2001
sijoitus x 1333
sijoitukset x 3970

**Comment by YSO-kokous** [comment]
**PÄÄTÖS**
Korjataan  Melindassa sijoitus-termillä kuvatusta aineistosta pois sijoitustoimintaan ja ydinjätteen loppusijoitukseen sekä viitteet, joihin riittää sijainti.
Katsotaan tämän jälkeen löytyykö jäljellä oleville sopiva sulkutarkenne vai onko käsite kokonaan poistettavissa

**Comment by mirmaid** [comment]
1334/Melinda

**Comment by mirmaid** [comment]
Jäljellä 265.

Sijainti sopii hyvin, kun on kyse virastojen, laitosten tai rakennusten sijoittamisesta (nämä korjattu). Melko paljon on aineistoa myös huonekalujen, kodinkoneiden ym. sijoittelusta, joissa se sopii huonommin.

Esim.
_Ongelma : leijuvat huonekalut
Hyvä paikka kauttimelle : kaiuttimien sijoitus 
Säätöä ja sijoittelua : tee itse kotiteatteri
Kodinkoneiden sijoittaminen keittiöön
Kodin roskat järjestykseen : hyvää biojäteastiaa ei vieläkään löydy, vaikka vaihtoehtoja jätevaunuiksi on paljon_

Loppusijoitus korjattu niihin viitteisiin, joissa on kyse ydinjätteestä. Soveltunee ainakin osittain myös muuhun jätehuoltoon, mutta sopiiko kaikkeen? Näihin ei ainakaan suomeksi sovi sijainti. 

Esim.
_Tredjepartsadgang til transportnett og lagringsområder for CO₂ : implementering av Europaparlaments- og rådsdirektiv om geologisk lagring av CO₂ i norsk rett
Lannan käyttö Venäjällä uhkaa Suomenlahtea 
Kombikoulun rakennushanke : pilaantuneiden maiden poisto
Ylijäämämaiden sijoitusalueet ja alueiden jälkikäyttö uuden Oulun alueella
Hitura hakee rikastushiekalle paikkaa : vaihtoehdot kyläläisten syyniin
Jätteen termisen käsittelyn tuhkien ja kuonien käsittely- ja sijoitusmahdollisuudet_

Lisäksi aineistoa lasten sijoituksesta, johon ehkä riittää sijaishuolto ym. termistö.

Jonkin verran maahanmuuttajien sijoituksesta.

Aika runsaastikin aineistoa koirien sijoituksesta (liittyen koirien jalostukseen, vastaavaa myös kissoilla, mutta tästä ei vielä aineistoa).

Jonkin verran erilaista muuta ihmisten sijoittamista (työelämässä, vanhustenhuollossa).

Esim.
_Naisten linnasta miesten sekaan 
Determinants of institutional care at older ages in Finland_

**Comment by ilona-x** [comment]
> Loppusijoitus korjattu niihin viitteisiin, joissa on kyse ydinjätteestä. Soveltunee ainakin osittain myös muuhun jätehuoltoon, mutta sopiiko kaikkeen? Näihin ei ainakaan suomeksi sovi sijainti.

loppusijoitus-termi taitaa olla aika vahvasti sidoksissa ydinjätteeseen 

Voisiko jätehuoltoa  & ylijäämämaita käsitteleviin viitteisiin sopia jokin näiden kaltainen termi:
LIIKO: maa-ainesten sijoitusalueet KT läjitysalueet http://www.yso.fi/onto/mero/m10019
GEO: jätteiden sijoituspaikat http://www.yso.fi/onto/gtk/GTK2015ID1347

--

> Tredjepartsadgang til transportnett og lagringsområder for CO₂ : implementering av Europaparlaments- og rådsdirektiv om geologisk lagring av CO₂ i norsk rett

sopisiko tuohon viitteeseen esim. varastointi?

**Comment by ilona-x** [comment]
<s>
> Lannan käyttö Venäjällä uhkaa Suomenlahtea

https://melinda.kansalliskirjasto.fi/byid/013537683
" Koska peltoviljelyalueet ja karjankasvatusalueet **sijaitsevat** Venäjällä etäällä toisistaan, syntyy pohjoisessa valtavia varastoja lantaa, joiden levitys länsimaisten ohjeiden mukaan pelloille aiheuttaisi liikalannoituksen ja merkittävän huuhtoutumisriskin. Kirjoittajat uskovat tulevaisuudessa tulevan kannattavaksi varastoidun lannan kuljetukset etelän viljelyalueille. "

Tuohon taitaisi sopia sijainti. Kuvailua voisi parantaa muilla termeillä, sillä kuvailusta puuttuu kokonaan esim. huuhtoutuminen -termi</s>

**Comment by ilona-x** [comment]
> Kodin roskat järjestykseen : hyvää biojäteastiaa ei vieläkään löydy, vaikka vaihtoehtoja jätevaunuiksi on paljon
https://melinda.kansalliskirjasto.fi/byid/013506627

Luin tämän Helsingin sanomien artikkelin. Lyhyessä jutussa on yksi lause, jossa puhutaan sijoittamisesta: 
"KAIKKI VAUNUT ovat yhdessä tasossa, vaikka kahteen tasoon sijoitettu vaunu säästäisi tilaa."

Eli esim. tässä tapauksessa termin voisi varmasti poistaa ilman että kuvailu siitä kärsisi.

--

Osaan kalusteiden sijoittelua käsitteleviin aineistoihin riittäisi ehkä sisustussuunnittelu? Esim. artikkeli "Oikea kalustesijoittelu saa tilan toimimaan" kuvailussa on vain termit sisustus & sisustussuunnittelu.

**Comment by mirmaid** [comment]
^^ Kuvailusta päättelin, että sijoitus viittasi kuitenkin siihen, mihin lanta sijoitetaan. Mutta ei toki tämä asia tuohon aineistoon kaadu :poop:.

**Comment by ilona-x** [comment]
OK, niin näköjään onkin. Tuon pääsinkin lukemaan, kun on Hesarin kirjoitus: 
"SUOMESSA ja muualla EU:n alueella lantaa ei saa käsitellä jätteenä vaan se on levitettävä pelloille. Luoteis-Venäjällä valtaosa lannasta sen sijaan sijoitetaan jätteenä käytöstä poistetuille pelloille, lietealtaisiin ja laittomiin säilytyspaikkoihin, koska viljelykäytössä olevaa peltoalaa ei ole riittävästi lantamäärään nähden."

Eli kyse tosiaan jätteen sijoittamisesta.

**Comment by mirmaid** [comment]
Melindassa loppusijoitus (sanahaku) & jätteet (asiasana) tuo 4 viitettä, joissa on kyse muusta kuin ydinjätteestä, ja ongelmajätteet samoin yksi viite. 

Näköjään kuitenkin voidaan tulkita myös laajemmin: https://www.stat.fi/meta/kas/loppusijoitus.html
https://www.hsy.fi/ymparistotieto/avoindata/avoin-data---sivut/paakaupunkiseudulla-syntyneen-jatteen-hyodyntaminen-ja-loppusijoitus-toimialoittain/

**Comment by fantsby-m** [comment]
Mahtaisikohan noihin kaiuttimien, kodinkoneiden ym. sijoittamiseen sopia vain _paikka_?

**Comment by mariaforsen** [comment]
Olisiko syytä pitää sanastossa myös:
sijoitus (paikka) = placering (plats)
sijoitus/sijoittaminen (sosiaalihuolto) = placering (socialvård) ks. https://termipankki.fi/tepa/fi/haku/sijoitus : "toimenpide, jolla henkilön hoito, kasvatus ja muu huolenpito siirtyy määräaikaisesti, toistaiseksi tai pysyvästi sosiaalipalvelujen järjestäjälle tai yksityishenkilölle"

**Comment by mirmaid** [comment]
^ Osa niistä, joihin sopisi sijoitus (paikka), tuli jo korjattua > sijainti. Käytännössähän se sopisi melkein kaikkiin jäljelläoleviin paremmin tai huonommin (ja myös ydinjätteeseen).

**Comment by YSO-kokous** [comment]
### Päätös
Otetaan sanastoon sijoitus (paikka)  
- esim. huonekalujen, jätteiden, ihmisten sijoittaminen johonkin paikkaan.

**Comment by mirmaid** [comment]
Sijoitus (paikka) sopii hyvin monenlaisiin (kaiuttimet tai jätteet sijoitetaan johonkin paikkaan, mutta niin myös vaikka pakolaiset). Sijoitetut lapset saadaan käsiteltyä muilla termeillä, varmaan ainoa joukko mikä vielä jää ovat sijoitettavat eläimet, koska niiden (samoin kuin lasten) kohdalla olennaista ei ole fyysinen paikka, vaan se, kuka huolehtii. Jos nyt oikein venyttää niin kyllä senkin voi ajatella epämääräisenä paikkana, mutta vähän hassu viba siinä on (esim. https://melinda.kansalliskirjasto.fi/byid/012883764 - ikäänkuin koira olisi sijoitettu "Raisioon", eikä "Möttöselle"). Kovin paljon näitä ei määrällisesti ole.

**Comment by FinMeSHienPaimentaja** [comment]
Tuntumani on, että koirien jalostuksessa koirien "sijoitus" on aika yleistäkin toimintaa, mutta toinen juttu on tosiaan ko. termin tarve kuvailussa: https://yle.fi/aihe/artikkeli/2014/12/02/sijoituskoira-opettaa-koiran-hyvaa-hoitoa-kun-kaikki-menee-hyvin

**Comment by mariaforsen** [comment]
Onko enää vaihtoehtona että lapsen sijoitus ja koiran sijoitus otettaisiin erillisinä käsitteinä? Molemmilla aika tarkka merkitys, jossa paikka ei ole olennainen?
https://www.hankikoira.fi/koiran-hankinta/mika-on-sijoituskoira "Koiran omistus säilyy myyjällä, kunnes sopimuksen ehdot on täytetty. Ostaja on koiran haltija siihen asti, kunnes omistusoikeus siirtyy ostajalle"
https://termipankki.fi/tepa/fi/haku/sijoitus "toimenpide, jolla henkilön hoito, kasvatus ja muu huolenpito siirtyy määräaikaisesti, toistaiseksi tai pysyvästi sosiaalipalvelujen järjestäjälle tai yksityishenkilölle"

**Comment by mirmaid** [comment]
Lapsille ei varmaan termiä tarvita, koska sanastossa on _sijoitetut lapset_ (ym.). Muitakin eläimiä kuin koiria sijoitetaan, vaikka Melindassa ei taida olla aineistoa. Sitten on sekä kasvattajan sijoittamia eläimiä, että sijaiskotiin tilapäisesti majoitettuja löytöeläimiä, esim. https://melinda.kansalliskirjasto.fi/byid/013474995.

**Comment by jarmosaarikko** [comment]
Voisiko sitten olla eri käsitteenä "**sijoituseläimet**"  -- kasvattajan sijoittamat ja myös kai opaskoirakoulutukseen menevät pennut yms. 
YSOssa on jo samantapaisia: "heitteille jätetyt eläimet" sekä "löytöeläimet".

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta. Tarvittaessa käytetään vapaana avainsanana.

**Comment by mirmaid** [comment]
Päätös poistamisesta vielä.
