### ISSUE TITLE
akateeminen vapaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7337]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

akateeminen vapaus 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85000300> 

#### Perustelut ehdotukselle   

Melindasta löytyykin jo useampia tietueita, missä termi näkyvillä - "muu asiasana", sekä 650/-4, että 653/-0 kenttiä käytetty. YSA-ehdotus vain jäänyt aiemmin piippuun!? Kyseessä tietenkin on vakiintunut ilmaisu, millä viitataan ns. akatemian kaikkien toimintojen riippumattomuuteen (tutkimus, opetus, taloudellinen asema, srateginen taso mukaanlukien tms.) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** HYK **Termiehdotus Fintossa:** [akateeminen vapaus](http://finto.fi/yse/fi/page/Y507337)

**Comment by mirmaid** [comment]
22 viitettä Melindassa. (Ei ole aikaisemmin ehdotettu sanastoon.)

Yhdistelmiä _yliopistot/tiede/tutkimus & vapaus_ käytetty jonkin verran.

**Comment by mariaforsen** [comment]
Sv. akademisk frihet (on SAOssa) 
https://sv.wikipedia.org/wiki/Akademisk_frihet

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by AuHo22** [comment]
tieteen vapaus?
ks. esim. https://www.professoriliitto.fi/?x23370=498329
https://tieteentermipankki.fi/wiki/Oikeustiede:tieteen_vapaus_(perusoikeutena)

Jotta ei sotkeutuisi opiskelijoiden akateemiseen vapauteen, jolla on oma merkityksensä.

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi käytettävä termi on kyllä akademisk frihet ja näin on myös SAOssa=LCSH academic freedom. Nämähän ovat hyvin vakiintuneita termejä, toisin kuin tieteen vapaus. Eikö opiskelijoiden akateeminen vapaus loppujen lopuksi liity samaan ilmiöön? Onko todella tarpeen rajata, ja jos on niin olisiko se parempi tehdä tarkenteella, esim. akateeminen vapaus (tiede) tms.? Ruotsiksi ei ainakaan näytä olevan mitään "erillistä" opiskelijoiden akateemista vapautta.

**Comment by AuHo22** [comment]
Valitettavasti suomen kielessä asia on vähän monimutkaisempi kuin muunkieliset määritelmät, eli vahvaa monitulkintaisuutta on, tästä tynkäartikkelistakin jo havaittavissa:
https://fi.wikipedia.org/wiki/Akateeminen_vapaus

Googlaamalla tieteen vapaus antaa yli puoli miljoonaa osumaa, akateeminen vapaus 155 000, ja 
Itselleni ainakaan ei termi tieteen vapaus aiheuta ymmärrysongelmia, ja käännöksinä voivat toimia nuo yllämainitut, kun kerran tuntuvat olevan yksiselitteisiä omissa kulttuureissaan. Tarkenteiden avulla voi sitten tietenkin myös hoitaa asian? akateeminen vapaus (opiskelu) ja akateeminen vapaus (?) Itse puollan edelleen tieteen vapaus -termiä.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa "akateeminen vapaus", ohjaustermiksi "tieteen vapaus".

Hajontaa ryhmän kesken. Enemmistö kannatti muotoa "akateeminen vapaus". Termi "akateeminen vapaus" hajoaa suomen kielessä merkitykseen opiskelun vapaudesta ja toisaalta tieteen tekemisen, opetuksen vapaudesta. Jälkimmäisessä merkityksessä käytetään myös termiä tieteen vapaus. Kun nyt valittiin muoto "akateemien vapaus", katetaan molemmat merkitykset.  Ruotsin kielessä molemmista merkityksistä käytetään termiä "akademisk frihet".
