### ISSUE TITLE
progressiivinen metalli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7338]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

progressiivinen metalli 

#### Ehdotettu termi englanniksi   

progressive metal 

#### Ehdotettu termi ruotsiksi   

progressiv metal 

#### Vaihtoehtoiset termit ja ilmaisut   

progressivinen metal 
proge metal 

#### Tarkoitusta täsmentävä selite   

Progressiivinen metalli on progressiivisen rockin raskaampi muoto. Se eroaa muusta metallimusiikista monimutkaisten rumpukomppien ja tahtilajien osalta. Tyypillistä "progemetallille" on myös futuristinen soundimaailma lukuisine kitaraefekteineen ja kosketinsoitinsaundeineen. Laulu on vahvasti eläytyvää ja voi hetkessä vaihdella herkästä tulkinnasta matalaan murinaan. Lisäksi kappalerakenteet eivät ole tyypillisen suoraviivaisia vaan "kehittyviä". (Wikipedia) 

#### Perustelut ehdotukselle   

Tarvitaan sekä YSO:n että SLM-sanastoon progressivisen metallimusiikin kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Progressiivisen metallimusiikin kuvailu 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [progressiivinen metalli](http://finto.fi/yse/fi/page/Y507338)

**Comment by jtuohini** [comment]
LT heavy metal
LT progressiivinen rock

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM
