### ISSUE TITLE
puheohjelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7339]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puheohjelmat](http://www.yso.fi/onto/ysa/Y103732) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista yhdistää keskusteluohjelmiin tai määritellä tarkemmin miten tämä eroaa keskusteluohjelmista? 

#### Perustelut ehdotukselle   

Wikipediassa käsitellään synonymeinä  ja Melindassa molempia on käytetty sekä radio- että tv-ohjelmiin. Mutta ruotsiksi on ollut puheohjelmat=talprogram (eli vain radio) ja keskusteluohjelmat=pratshower (voi olla sekä radio- että tv). Eli merkitykset nyt sekavat ja mietitään ratkaisua ruotsiksi.

https://fi.wikipedia.org/wiki/Keskusteluohjelma

**Comment by mirmaid** [comment]
Puheohjelma-sanaa käytetään sitten vielä tietokoneohjelmista tms. jotka puhuvat tekstiä, tosin Melindassa ei taida olla tässä merkityksessä. 

Onkohan Leenalla mielipidettä tähän?

**Comment by LeKorsu** [comment]
Selvittelen asiaa. Historiallinen tausta radio- ja tv-ohjelmien osalta on varmasti välineellinen: radiossa on puheohjelmia, joista osa voi olla keskusteluohjelmia (monta osallistujaa) tai yksittäisiä esitelmiä / monologeja eli puheohjelmia (niitä on nytkin, esim. Jari Sarasvuo).  Ylellä oli aikoinaan Puheohjelmien osastokin.

Television puolella on aina puhuttu keskusteluohjelmista. Mutta selvittelen lisää tuolta toimitusten ja ohjelmaluokittelun puolelta.

**Comment by LeKorsu** [comment]
Eipä tuolta toimituksista tullut sen tarkempaa määritelmää kuin että puheohjelmat on laajempi kattokäsite ja sen alla on keskusteluohjelmat, joiden määritelmä on tosiaan se, että äänessä on vähintään kaksi ihmistä.

Puheohjelmat-käsitettä on käytetty nimenomaan radion (audion) puolella.

**Comment by mariaforsen** [comment]
Hankalaa. Ja miten puheohjelmat voi olla kattokäsite jos se on, kuten onkin, vain radion/audion puolella, koska keksusteluohjelmathan ovat kyllä muutakin (tv jne.).

**Comment by LeKorsu** [comment]
Ehdotan: puheohjelmat KÄ keskusteluohjelmat

**Comment by mirmaid** [comment]
Kuulostaa siltä että käyttö olisi kuitenkin melko johdonmukaista molemmilla kielillä? Ja nythän näillä ei ole hierarkkista suhdetta. Ehkä tilanne kumpuaa yksinkertaisesti siitä, että ei tehdä sellaisia puheohjelmia, joissa joku puhuisi yksinään tv:ssä.

**Comment by LeKorsu** [comment]
Jotta saataisiin tämä issue viimein suljetuksi kannatan alkuperäistä ehdotusta eli yhdistämistä puheohjelmat KÄ keskusteluohjelmat.

**Comment by AuHo22** [comment]
Itselleni tuli heti mieleen vastakkainasettelu radion puheohjelmat vs. radion musiikkiohjelmat. Ei voi mielestäni yhdistää - voiko olla puheohjelmat (radio)?
https://areena.yle.fi/audio/1-3621762
- Mikä on musiikki- ja puheohjelmien suhde? Onko Yle Radio 1 ensisijaisesti musiikki- ja musiikkiin liittyvien ohjelmien kanava? Vaikutelmani on, että etenkin iltaisin on mahdollista kuunnella lähes pelkästään musiikkia. Kuuntelin sunnuntai-iltana radiota eri kanavilta. Ainoastaan Radio Dei tuotti puheohjelmaa ja Yle Puhe urheiluselostuksen, mikä lienee puheohjelma sekin. Miksi kiinnostavat yhteiskunnalliset ohjelmat on sijoitettu pääosin keskipäivään – siis päivätyöläisen työaikaan? --
Onko Radio 1 ensisijaisesti musiikki- vai puhekanava? Oikeastaan ei kumpaakaan vaan kulttuurin, asiapuheen ja musiikin kanava.

**Comment by mirmaid** [comment]
Mielestäni siis nykytilanteessakaan ei ole ongelmaa: puheohjelmat/talprogram = radio, yksi tai useampi puhuu, keskusteluohjelmat = tv tai radio, useampi ihminen keskustelee. Toki siis radion keskusteluohjelmaa voi nimittää vain puheohjelmaksi, jos sitä verrataan musiikkiohjelmaan, eikä ole olennaista että käydään keskustelua, mutta ei tässä siltikään kai tapahdu virhettä (ei kai olisi väärin ruotsiksikaan sanoa radion keskusteluohjelmasta että se on talprogram?). 

Jos tarkenteen lisääminen (radio) tuntuu helpottavan se on varmaan mahdollista, mutta se ei ratkaise ylläolevaa tilannetta. Enkä oikein tiedä tuoko se varsinaisesti lisäarvoa muutenkaan, kun on hyvin vaikea keksiä milloin käytettäisiin puheohjelmat-termiä televisiosta - ja jos käytettäisiin niin olisiko se edes väärin.

**Comment by mariaforsen** [comment]
Kyllä ruotsiksi talprogram on väärin jos on radion keskusteluohjelmasta kyse.

**Comment by FinMeSHienPaimentaja** [comment]
Intuitiivisesti tuo on mielestäni aika selvä: puheohjelmassa (yleensä radion puolella) vähintään yksi henkilö puhuu, keskusteluohjelmissa vähintään kaksi henkilöä keskustelee (joko radiossa tai televisiossa). Jolloin puheohjelmat olisi yläkäsite...Mutta voisi olla rinnakkaisetkin...

**Comment by mariaforsen** [comment]
Talprogram ei ainakaan yleensä käytettäisi näistä.

**Comment by ilona-x** [comment]
Hankala tapaus tämä puheohjelma-keskusteluohjelma-musiikkiohjelma. Mihin kategoriaan menisi esimerkiksi YLE Radio Suomen Kutsuvieras -ohjelmasarja. 🤔 
"Kutsuvieras on radiosarja, jossa tunnetut suomalaiset puhuvat itseään koskettavasta teemasta valitsemansa musiikin kera."
https://yle.fi/aihe/artikkeli/2020/06/08/mista-puhuisit-jos-sinulle-tarjottaisiin-radiossa-tunti-aikaa-kutsuvieras-tulee

**Comment by mirmaid** [comment]
^ Ehkä se jossain radio-ohjelmien luokittelussa voisi olla sekä puheohjelma että musiikkiohjelma, en tosin yhtään tunne kriteereitä :slightly_smiling_face:. Mutta epäilen, että olisi siis ongelma jos poistaisimme puheohjelmat, jolloin radiossa olisi vain musiikkiohjelmia ja keskusteluohjelmia.

**Comment by AuHo22** [comment]
su. puheohjelmat / puhe- ja keskusteluohjelmat, sv. talprogram och pratshower (?)
Jos mediaa haluaa tarkentaa, voi lisätä uuden asiasanan?

**Comment by LeKorsu** [comment]
> ^ Ehkä se jossain radio-ohjelmien luokittelussa voisi olla sekä puheohjelma että musiikkiohjelma, en tosin yhtään tunne kriteereitä 🙂. Mutta epäilen, että olisi siis ongelma jos poistaisimme puheohjelmat, jolloin radiossa olisi vain musiikkiohjelmia ja keskusteluohjelmia.

Kyllä olisi ongelma, koska podcastien myötä on entistä enemmän monologipuhetta, vaikka podcasteja on toki myös ainakin kahden puhujan toimesta. Ja jos  mahdollista sulkutarkennetta miettii, audio on nykyisin parempi kuin radio, koska podcasteja julkaistaan ennen kaikkea verkossa.

Ratkeaisiko tämä viimein, jos laitetaan määritelmäksi jotain tähän suuntaan: 
puheohjelmat: audio(podcast)- tai radio-ohjelma, joka ei sisällä musiikkia. Puhujia/osallistujia voi olla yksi tai useampi.

Tarvitseeko keskusteluohjelmat määritelmää?

**Comment by mariaforsen** [comment]
Kannatan yllä olevaa tapaa määritellä puheohjelmat. Pitää miettiä mikä ruotsinkielinen termi sopii parhaiten keskusteluohjelmille, määritelmä auttaisi siihenkin. 
https://fi.wikipedia.org/wiki/Keskusteluohjelma

**Comment by LeKorsu** [comment]
Viime hetken sekoittamiskommentti. Kyselin vielä keskiviikkoiltapäivänä kommentteja Areenan audiotoimituksesta. He eivät käytä puheohjelmaa ohjelman lajityyppinä vaan asia[ohjelma] ja tarkempi sisältötermi kuten tiede / historia jne.. Monologipodcastit ovat "filosofista puhetta".
Toisaalta siellä (Areenassa siis) on kuitenkin kategoria "Podcastit ja puheohjelmat".
Minkähänlainen on Kavin tarve puheohjelmille?

Sveriges Radio ei ainakaan netissä käytä sanaa talprogram, pratshow'lla tuli kahdeksan osumaa, Sveriges Televisionin puolella 54 osumaa (siis site:svt.se)

**Comment by YSO-kokous** [comment]
Tehdään seuraava käytettävän termin muutos: podcast-lähetys muotoon podcastit.

Korjataan Melindassa puheohjelmat-kuvailu, korjataan näihin keskusteluohjelmat (tai podcastit) silloin kun sopii. Mietitään tämän jälkeen tarvitaanko sanastossa erikseen puheohjelmat. Pohdittiin käsitteiden yhdistämistä "puhe- ja keskusteluohjelmat" tai puheohjelmien rajaamista radioon tai audioon: "puheohjelmat (radio/audio)", kuitenkin tässä jäi epäselväksi rajanveto radiossa puheohjelman ja keskusteluohjelman välillä, ts. onko radio-ohjelma, jossa on monta puhujaa, edelleen nimeltään puheohjelma.

**Comment by mirmaid** [comment]
Laitetaan vielä yksi esimerkki: https://areena.yle.fi/audio/1-1596497
https://melinda.kansalliskirjasto.fi/byid/013610460

Olin alkamassa korjata tietueita, mutta toisaalta jäin miettimään, kannattaako korjata pois puheohjelmat-käsitettä, jos se kuitenkin jää yllä olevan tyyppisiin - nehän ovat hyvin saman tyyppisiä kuin podcastit, joissa termiä on myös käytetty.

**Comment by mariaforsen** [comment]
Aivan, Sommarprat ei ole keskusteluohjelma, vaan "puheohjelma" jossa yksi puhuja.

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet "puhe- ja keskusteluohjelmat"  KT puheohjelmat, keskusteluohjelmat
