### ISSUE TITLE
Sofia Magdalenan kirkko (Lohtaja)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7340]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Sofia Magdalenan kirkko (Lohtaja) 

#### Ehdotettu termi ruotsiksi   

Sofia Magdalena kyrka (Lohteå) 

#### Ehdotettu termi englanniksi   

Church of Sofia Magdalena (Lohtaja) 

#### Vaihtoehtoiset termit ja ilmaisut   

Lohtajan kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 
[puurakennukset](http://www.yso.fi/onto/yso/p3650) 

#### Assosiatiiviset (RT)   

[puukirkot](http://www.yso.fi/onto/yso/p3649) 

#### Perustelut ehdotukselle   

Lohtajan seurakunnan, joka on vuodesta 2009 lähtien ollut osa Kokkolan seurakuntayhtymää, kirkon sisämaalauksen ja alttaritaulun teki oululainen kirkkomaalari Mikael Toppelius vuosina 1770-1776. Kun maalaustyö oli valmistunut, kirkko sai Kustaa III:n puolison mukaan nimeksi Sofia Magdalena. Perusteluna myös se, että 1700-luvulla rakennettujen puukirkkojen määrä on Suomessa viime aikoina vähennyt. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lohtajan kirkko 250 vuotta 

**Ehdottajan organisaatio:** Kokkolan kaupunginkirjasto **Termiehdotus Fintossa:** [Sofia Magdalenan kirkko (Lohtaja)](http://finto.fi/yse/fi/page/Y507340)

**Comment by mariaforsen** [comment]
Sv. Lochteå kyrka ET Sophia Magdalena kyrka (Lochteå)
