### ISSUE TITLE
toimintaterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7342]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toimintaterapia](http://www.yso.fi/onto/ysa/Y99569) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Palaute alun perin TERO-ontologiaan: ihmettelen sitä, että toimintaterapian yläkäsite on psykoterapia. Kyseessä on hyvin erilaiset kuntoutusmuodot, vrt. psykoterapia ja puheterapia. 
Arbetsterapi on nyt käytettävä termi työterapialle ja ohjaustermi toimintaterapialle? 

#### Perustelut ehdotukselle   

-

**Comment by ilona-x** [comment]
FinMeSH: toimintaterapia LT kuntoutus http://www.yso.fi/onto/mesh/D009788

**Comment by mirmaid** [comment]
Pitäisikö myös muita siirtää? Lääketieteen termit: toimintaterapia: _hoitomuotoja joissa pyritään esim. luovien toimintamuotojen ja arkipäiväisten askareiden opettelun avulla kehittämään potilaan toimintakykyä (esim. taideterapia, tanssi- ja liikuntaterapia, musiikkiterapia, askarteluterapia)_.

psykoterapia: _1. psykologisin menetelmin toteutettu psyykkisten sairauksien ja häiriöiden hoito_

Toisaalta FinMeSHissä psykoterapian alakäsitteenä on esim. _aromaterapia_, kun taas Lääketieteen termit: aromaterapia: _kasveista tehtyjen öljyjen ja uutteiden kokemusperäinen käyttö sairauksien hoitoon; ks. myös uskomuslääkintä_

**Comment by mariaforsen** [comment]
Ruotsissa käytetään termiä arbetsterapi, suomessa ergoterapi, sen takia arbetsterapi on myös ohjaustermi sille. 

Kannatan siirtoa, psykoterapia liian kapea yläkäsite.

**Comment by mirmaid** [comment]
Myös työterapian yläkäsite psykoterapia (THL).

**Comment by tpalonen** [comment]
Nämä psykoterapian alakäsitteet siirtäisin myös:

feministinen radikaaliterapia > hoitomenetelmät
hypnoterapia > hoitomenetelmät
kiinnipitoterapia > hoitomenetelmät
musiikkiterapia > hoitomenetelmät
luovuusterapia > hoitomenetelmät
psykoanalyysi > psykiatria [vrt. MeSH]
puutarhaterapia > hoitomenetelmät
sosioterapia > hoitomenetelmät
taideterapia > hoitomenetelmät
transaktioanalyysi > teoriat
valokuvaterapia > hoitomenetelmä

Ja näistä löytyi niin vähän määritelmiä, että en osaa sanoa, mihin parhaiten kuuluisivat. En löytänyt lähdettä, jossa näitä olisi sanottu psykoterapian muodoksi. Riittääkö tämä perusteeksi siirtää ne hoitomenetelmien puolelle?

työterapia
verkostoterapia
vuorovaikutusterapia

**Comment by YSO-kokous** [comment]
Siirretään toimintaterapia > hoitomenetelmät. Lisäksi hyväksytään Tuomaksen tekemät muutosehdotukset ja myöskin työterapia, verkostoterapia, vuorovaikutus terapia > hoitomenetelmät

**Comment by mirmaid** [comment]
YSOn ylläpito päätyi jättämään transaktioanalyysin psykoterapian alle. Psykoanalyysin paikkaa pohditaan vielä.
