### ISSUE TITLE
alkoholisairaudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7343]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[alkoholisairaudet](http://www.yso.fi/onto/ysa/Y175301) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Päätermiksi alkoholin aiheuttamat sairaudet 

#### Perustelut ehdotukselle   

http://www.yso.fi/onto/mesh/D020751

**Comment by mirmaid** [comment]
MeSH-termi on selkeämpi, mutta YSO-termi on myös yleisesti käytetty (Google n. 12000/3000).

**Comment by AuHo22** [comment]
Duodecim (Terveyskirjasto) käyttää termiä alkoholisairaudet - ei ole minusta monitulkintainen vaan yleisesti kielitajuun hyväksytty.

**Comment by YSA-kokous** [comment]
Ei muutosta.

**Comment by mirmaid** [comment]
Lisätty ohjaustermiksi.
