### ISSUE TITLE
media-arkistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7344]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

media-arkistot 

#### Ehdotettu termi ruotsiksi   

mediearkiv 

#### Ehdotettu termi englanniksi   

media archives 

#### Ehdotettu yläkäsite YSOssa (LT)   

[arkistot](http://www.yso.fi/onto/yso/p2336) 

#### Alakäsitteet (RT)   

[ääniarkistot](http://www.yso.fi/onto/yso/p19521) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 
[81 Kirjastot. Arkistot. Tietopalvelu. Museot. Näyttelyt](http://www.yso.fi/onto/yso/p26572) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa ja yhteikäsitettä eri media-aineistojen  (teksti, videokuva, ääni) arkistoille 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Changing sceneries changing roles, part VIII : selected papers from the FIAT/IFTA media management seminar Lugano 8th-9th June 2017 

**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [media-arkistot](http://finto.fi/yse/fi/page/Y507344)

**Comment by LeKorsu** [comment]
Kommentoin omaa ehdotustani. Kuva-arkistotkin on alakäsite, http://www.yso.fi/onto/yso/p17135, mutta tarkoitetaanko tällä valokuva-arkistoja vai videokuva-arkistoja. Pitäisi minun mielestäni eritellä.

**Comment by mirmaid** [comment]
Mikä tämän suhde on ohjelma-arkistoihin?

**Comment by LeKorsu** [comment]
En muistanut koko ohjelma-arkistoja. Mutta sanoma- ja aikakauslehtien julkaisu/tekstiarkistot eivät ole ohjelma-arkistoja, mutta voisivat mennä media-arkistojen alle.  Tekstiarkistot-termiä ei ole Ysossa, eikä nämä taas sovi julkaisuarkistot-termin määritelmään.  (Alman lehtien arkiston nimi oli muuten aikoinaan Media-arkisto).

Tai sitten "lehtiarkistot" tarkoittamaan jatkuvien julkaisujen arkistoja, jolloin media-arkistot voidaan unohtaa.

Mutta kaipaan edelleen myös määritelmää kuva-arkistoille: voidaanko sitä käyttää sekä valokuva- että videokuva-arkistojen kanssa.

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by YSA-kokous** [comment]
Käsitellään seuraavassa kokouksessa.

**Comment by LeKorsu** [comment]
Asiaa nyt pidemmän aikaa pähkäiltyäni ja kollegoitten kanssa keskusteltuani, vedän pois tämän media-arkistot-termiehdotuksen. Tuskin kaipaamme arkistojen alle mitään välihierarkiaa, vaan pitää yrittää kehitellä täsmällisempi termiehdotus aikakaus- ja sanomalehtien tekstiarkistoille.

Kävisikö lehtiarkistot sekä vanhoista leikearkistoista että nykyisistä sähköisistä arkistoista? 
Vai pitäisikö ottaa erikseen leikearkistot että jokin muu tyyliin [sähköiset] lehtiarkistot / tekstiarkistot. Tekstiarkisto voi toki  tarkoittaa muutakin kuin lehtitekstiä.

Lisäksi kaipaisin edelleen kommentteja ja kannanottoja siitä, että sisältääkö kuva-arkistot teidän mielestänne sekä still-kuvaa että videokuvaa, ja jos kyllä pitäisikö siihen lisätä huomautus?

**Comment by YSO-kokous** [comment]
Media-arkistot-käsitteelle ei tarvetta, mutta lehtiarkistot-käsite tarvittaisiin.

Otetaan sanastoon lehtiarkistot. Voi viitata sekä sähköiseen että painettujen lehtien arkistoon. Ohjaustermiksi leikearkistot.

**Comment by mariaforsen** [comment]
Sv. tidningsarkiv ET urklippsarkiv
