### ISSUE TITLE
suoratoistopalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7345]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suoratoistopalvelut 

#### Ehdotettu termi englanniksi   

streaming services 

#### Ehdotettu termi ruotsiksi   

streamingstjänster 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sähköinen viestintä](http://www.yso.fi/onto/yso/p5444) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa yleiskäsitettä suoratoistopalveluille kuten Netflix, HBO, Viaplay jne. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kopu, Pauli: Media televison jälkeen, isbn 978-952-351-158-3 

**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [suoratoistopalvelut](http://finto.fi/yse/fi/page/Y507345)

**Comment by ilona-x** [comment]
YSOssa on suoratoisto http://www.yso.fi/onto/yso/p25409

**Comment by mirmaid** [comment]
2 kertaa Melindassa

**Comment by mariaforsen** [comment]
Sv. streamingtjänster ET streamingstjänster, streamingservice
