### ISSUE TITLE
Jõgevamaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7346]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Jõgevamaa 

#### Ehdotettu termi englanniksi   

Jõgeva County 

#### Ehdotettu termi ruotsiksi   

Jõgevamaa 

#### Vastaava käsite muussa sanastossa   

http://id.loc.gov/resources/instances/2622911.html : https://fi.wikipedia.org/wiki/J%C3%B5gevamaa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2649412 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Jõgevamaa](http://finto.fi/yse/fi/page/Y507346)

**Comment by mirmaid** [comment]
On sanastossa, http://www.yso.fi/onto/yso/p506116
