### ISSUE TITLE
Viljandin piiri (hallintoalue)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7353]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Viljandin piiri (hallintoalue) 

#### Ehdotettu termi ruotsiksi   

Viljandi distrikt 

#### Ehdotettu termi englanniksi   

Viljandi district 

#### Vastaava käsite muussa sanastossa   

https://et.wikipedia.org/wiki/Viljandi_rajoon :  

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Rajoon oli neuvostomiehityksen aikainen hallintoalue. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.1777872 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Viljandin piiri (hallintoalue)](http://finto.fi/yse/fi/page/Y507353)

**Comment by paivalai** [comment]
Tarkennus: 'piirikunta'olisi sittenkin parempi vaihtoehto kuin 'piiri' (hallintoalue).

t. Ehdottaja

**Comment by mirmaid** [comment]
Melindassa 10 viitettä kartta-aineistoihin, vuosilta 1912-1915. Tuolloin alue oli vielä Liivinmaan kuvernementtia. Helkassa on kolme viitettä, joissa aineisto käsittelee neuvostoaikaa.

**Comment by mirmaid** [comment]
KÄ Viljandimaa, ks. ems.
