### ISSUE TITLE
sankarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7354]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sankarit](http://www.yso.fi/onto/ysa/Y111516) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ohjaustermiksi 
"sankarittaret"@fi, "sankaritar"@fi,   
"hjältinnor"@sv, "hjältinna"@sv, 
"heroines"@en, "heroine"@en

TAI luodaan erillinen käsite:"sankarittaret"
LCSH:ssa  Women heroes" on Heroes käsitteen alakäsitteenä.  Tällä perusteella "sankarittaret" voitaisiin määritellä YSO:ssa myös omaksi käsitteekseen "sankarit -käsitteen alakäsitteenä. 

#### Perustelut ehdotukselle   

Kirjallisuudessa käsitellään nasia sankarina. Tälle ei ole tällä hetkellä termiä sanastossa ja  valitettavasti käsite "naissankari" on tässä tapauksessa lähellä, mutta täysin harhaanjohtava eli "naissankarit" ovat miehiä, jotka liehittelevät tai huijaavat naisia.

Wikidatassa tehty samoin: https://www.wikidata.org/wiki/Q162244
eli termit hero ja heroine ovat masculine ja feminine muotoina samalle käsitteelle

LCSH:ssa käsitteet ovat erikseen:
LCSH: "Heroes" http://id.loc.gov/authorities/subjects/sh85060430
BT "Persons" -- YSO:ssa  "sankarit" YK on "toimintaan liittyvä rooli"
Alakäsitteenä on 
LCSH "Women heroes" http://id.loc.gov/authorities/subjects/sh96003498
Works on the principal female characters of literary works are entered under [Heroines in literature.]
LCSH: "Heroines in literature" http://id.loc.gov/authorities/subjects/sh85060448
Earlier Established Form: "Heroines" 

#### Ehdottajan organisaatio   

Kansalliskirjasto / js

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7227

**Comment by YSA-kokous** [comment]
Ei muutosta.
