### ISSUE TITLE
nimien tunnistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7355]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nimien tunnistus 

#### Ehdotettu termi englanniksi   

named entity recognition 

#### Ehdotettu termi ruotsiksi   

namn erkännande? 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Named-entity_recognition 

#### Perustelut ehdotukselle   

Käytännön tarve ja ei näytä löytyvän mistään sanastosta vaikka oleellinen osa tekstintunnistuksen, tekoälytekniikoita kun työskennellään tekstin parissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.finna.fi/Record/alli.626677 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [nimien tunnistus](http://finto.fi/yse/fi/page/Y507355)

**Comment by LeKorsu** [comment]
Jos otetaan, pitäisikö ottaa yhdyssanana  niin kuin tekstintunnistus ja kasvontunnistus ovat. Mutta nimentunnistus vai nimientunnistus?

**Comment by mirmaid** [comment]
Ei Melindassa, Googlella kerran nimientunnistus, nimien tunnistus n. 340 kertaa (20 jos poistetaan samankaltaiset tulokset). Nimentunnistus n. 100.

**Comment by AuHo22** [comment]
Tutkimusmenetelmänä käytämme nimentunnistukseksi (Named-entity recognition, NER) kutsuttua analyysia, jonka toteutamme FiNER-työkalulla.
http://www.ennenjanyt.net/2019/08/kekkonen-euroviisut-ja-helsinki-kansallinen-audiovisuaalinen-perinto-ner-analyysin-tunnistamana/

Clemens Neudecker Alankomaiden kansalliskirjastosta keskittyi nimentunnistukseen. NER tunnistaa auktorisoituja henkilönimiä, organisaatioita ja paikkoja
https://blogs.helsinki.fi/digikirjasto/2014/08/21/uutisia-digitaalisia-vanhoja-ja-uusia-iflan-sanomalehtijaoston-kokous-genevessa-2/

**Comment by mariaforsen** [comment]
Sv. namnigenkänning ET namnigenkännande
