### ISSUE TITLE
huhmar / mortteli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7356]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

huhmar / mortteli 

#### Ehdotettu termi ruotsiksi   

mortel 

#### Ehdotettu termi englanniksi   

mortar 

#### Vaihtoehtoiset termit ja ilmaisut   

huhmare 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Huhmareen (esinekokoelmat museossa) 

#### Perustelut ehdotukselle   

Yleisyys. 

**Ehdottajan organisaatio:** Museovirasto **Termiehdotus Fintossa:** [huhmar / mortteli](http://finto.fi/yse/fi/page/Y507356)

**Comment by LeKorsu** [comment]
Varmaankin monikossa kumpi sitten otetaankaan, huhmaret vai morttelit. Henkilökohtaisesti mortteli on tutumpi sana.

**Comment by mirmaid** [comment]
MAOssa on huhmaret, http://www.yso.fi/onto/mao/p312

**Comment by mariaforsen** [comment]
Sv. mortlar

**Comment by YSA-kokous** [comment]
Huhmaret
