### ISSUE TITLE
latgallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7358]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

latgallit 

#### Ehdotettu termi ruotsiksi   

latgaller 

#### Ehdotettu termi englanniksi   

latgallians 

#### Ehdotettu yläkäsite YSOssa (LT)   

[latvialaiset](http://www.yso.fi/onto/yso/p315) 

#### Vastaava käsite muussa sanastossa   

https://en.wikipedia.org/wiki/Krimulda_Castle : https://fi.wikipedia.org/wiki/Latgallit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Tarkoitusta täsmentävä selite   

Latvian itäisimmässä maakunnassa Latgalliassa asuva latvian kielen murretta/omaa kieltään puhuva väestö. 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2017270 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [latgallit](http://finto.fi/yse/fi/page/Y507358)

**Comment by mirmaid** [comment]
LCSH: Latgals
