### ISSUE TITLE
datatalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7359]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

datatalous 

#### Ehdotettu termi englanniksi   

data economy 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Datatalous 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kilpailun ja kuluttajansuojan kysymyksiä datataloudessa 978-952-6684-56-7 

#### Tarkoitusta täsmentävä selite   

Datatalous on talous, jossa eri markkinatoimijat työskentelevät yhteisessä ympäristössä datan saannin ja käytettävyyden varmistamiseksi sekä hyödyntävät dataa ja luovat sen pohjalta uusia sovelluksia ja palveluita.[ 

**Termiehdotus Fintossa:** [datatalous](http://finto.fi/yse/fi/page/Y507359)

**Comment by ilona-x** [comment]
Melinda x 0

http://www.tsk.fi/tepa/fi/haku/datatalous

fi        datatalous
en      data economy
määritelmä
datan hyödyntämiseen perustuva tietotalouden osa
huomautus
Datataloudessa dataa hyödynnetään palvelujen, tuotteiden ja liiketoimintojen kehittämisessä.
Datatalous on syntynyt, kun datan laajamittainen kerääminen, säilyttäminen ja siirtäminen on tullut teknisesti ja taloudellisesti mahdolliseksi.
Esimerkiksi hakukonemainonta ja siitä saatavat tulot ovat datataloutta.
**Joskus data- ja tietotaloutta käytetään toistensa synonyymeinä.**
Lähde:  Tietotekniikan termitalkoot, 2016-11-11

YSOssa on tietotalous http://www.yso.fi/onto/yso/p21281

**Comment by HeidiRonkainen** [comment]
Tarvitsisin taas: https://www.sitra.fi/en/publications/roadmap-fair-data-economy/
Vai pitäisikö laittaa ohjaustermiksi tietotaloudelle?

**Comment by HeidiRonkainen** [comment]
Tähänkin voisi käyttää: https://www.etla.fi/julkaisut/data-markets-in-making-the-role-of-technology-giants/

**Comment by satuniininen** [comment]
Taas tarvittaisiin: https://www.sitra.fi/julkaisut/pelissa-euroopan-datatalouden-tulevaisuus/

**Comment by satuniininen** [comment]
Ja taas: https://www.sitra.fi/julkaisut/yhteistyolla-reiluun-datatalouteen/

**Comment by ilona-x** [comment]
tähän väitöskirjaan olisi tarvittu: http://urn.fi/URN:ISBN:978-951-29-8002-4

**Comment by ilona-x** [comment]
tälle olisi ollut taas käyttöä: Datapohjaisen arvonluonnin strategiset vaihtoehdot http://urn.fi/URN:ISBN:978-952-327-667-3

**Comment by mariaforsen** [comment]
https://www.sitra.fi/sv/ordbok/dataekonomi/
Tätä ei voi/saa ruotsiksi sekoittaa tietotalouteen (kunskapsekonomi).

**Comment by AuHo22** [comment]
Myös tilastokeskus ottaa kantaa ->
https://www.stat.fi/tup/julkaisut/tiedostot/julkaisuluettelo/ywrp2_201900_2019_21518_net.pdf

**Comment by LeKorsu** [comment]
Hankala. Voin kuvitella itsenikin sekoittamassa tietotalouden ja datatalouden. Vaikuttaa siltä, että datataloutta tullaan tarvitsemaan sanastossa, koska käyttö näyttää lisääntyvän, mutta millainen huomautus, kun tuossa Aulin linkkaamassa Tilastokeskuksen julkaisuussakin sanotaan, että määrittely vielä kesken. Onko tämä ongelmakokouksen issue?

**Comment by mirmaid** [comment]
Tepan määritelmässä tietotalouden _osa_.

**Comment by mariaforsen** [comment]
Sv. dataekonomi OT datadriven ekonomi
