### ISSUE TITLE
myyräekinokokki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7360]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

myyräekinokokki 

#### Ehdotettu termi ruotsiksi   

rävens dvärgbandmask 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10138/303527 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Myyr%C3%A4ekinokokki
Myyräekinokokki (Echinococcus multilocularis) on enimmäkseen koiraeläinten ohutsuolessa elävä, parin millimetrin pituinen[1] heisimato. 

**Termiehdotus Fintossa:** [myyräekinokokki](http://finto.fi/yse/fi/page/Y507360)

**Comment by ilona-x** [comment]
FinMeSH: Echinococcus multilocularis http://www.yso.fi/onto/mesh/D048210

Melinda: 
Echinococcus multilocularis x 18
myyräekinokokki x 6

**Comment by mirmaid** [comment]
Sanastossa on _ekinokokkoosi_

**Comment by YSA-kokous** [comment]
KÄ ekinokokkoosi
