### ISSUE TITLE
Pariisin ilmastosopimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7361]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pariisin ilmastosopimus 

#### Perustelut ehdotukselle   

Pariisin ilmastosopimus on 12. joulukuuta 2015 hyväksytty kansainvälinen sopimus, jonka tavoitteena on ilmastonmuutoksen pysäyttäminen.
https://fi.wikipedia.org/wiki/Pariisin_ilmastosopimus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.sitra.fi/julkaisut/1o5-asteen-elamantavat/ 

**Termiehdotus Fintossa:** [Pariisin ilmastosopimus](http://finto.fi/yse/fi/page/Y507361)

**Comment by mariaforsen** [comment]
Sv. Parisavtalet (klimatavtal) ET klimatavtalet i/från Paris

**Comment by LeKorsu** [comment]
Ylen meta-apissa ruotsinkielinen termi on Parisavtalet
