### ISSUE TITLE
aksoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7364]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aksoni 

#### Ehdotettu termi englanniksi   

axon 

#### Ehdotettu termi ruotsiksi   

axon 

#### Vaihtoehtoiset termit ja ilmaisut   

viejähaarake 
hermosyy 

#### Perustelut ehdotukselle   

Viejähaarake eli aksoni tai hermosyy on hermosolun eli neuronin osa, joita on vain yksi neuronia kohti

https://fi.wikipedia.org/wiki/Viej%C3%A4haarake 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cellular and molecular mechanisms of striatal pathway development 978-952-93-9475-3 

**Termiehdotus Fintossa:** [aksoni](http://finto.fi/yse/fi/page/Y507364)

**Comment by ilona-x** [comment]
FinMeSH: aksonit http://www.yso.fi/onto/mesh/D001369
LCSH: Axons http://id.loc.gov/authorities/subjects/sh85010598

**Comment by mariaforsen** [comment]
Sv. axoner ET nervcellsutskott, nervtrådar
