### ISSUE TITLE
luuttumusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7368]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luuttumusiikki 

#### Ehdotettu termi ruotsiksi   

lutmusik 

#### Ehdotettu termi englanniksi   

lute music 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85078980> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2095005 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle luutulle tai muulle kokoonpanolle, jossa luuttu on keskeisessä osassa. 

#### Perustelut ehdotukselle   

Sanastossa ei ole ennestään täsmällistä termiä luuttumusiikkia käsittelevän aineiston kuvailemiseen. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [luuttumusiikki](http://finto.fi/yse/fi/page/Y507368)

**Comment by jtuohini** [comment]
LT musiikki

**Comment by LeKorsu** [comment]
Pitäisikö sitten lisätä myös kitaramusiikki, en löydä sitäkään ysosta. (Enkä torvi-, huilu- tai puhallinmusiikki-termiä.)

**Comment by jtuohini** [comment]
Näitä muita ollaan lisäämässä _en masse_. Ja kyse näissä siis musiikkia käsittelevän aineiston kuvailemisesta, ei luuttu- yms. musiikin itsensä kuvailemisesta; esityskokoonpano merkitään SEKO-termein esityskokoonpanokenttään ja nämä ovat asiasanoja.

**Comment by tpalonen** [comment]
YSOssa lisäksi jo entuudestaan _pianomusiikki, urkumusiikki, viulumusiikki_.

**Comment by mariaforsen** [comment]
Eli kaikki eri soittimien musiikit lisätään?

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. Muita vastaavia voidaan lisätä tarpeen mukaan.

**Comment by YSA-kokous** [comment]
Hyväksytään käsite sanastoon.
