### ISSUE TITLE
sairaalamuusikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7369]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sairaalamuusikot 

#### Vaihtoehtoiset termit ja ilmaisut   

yhteisömuusikot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Musiikkihyvinvointia!  978-952-216-712-5 

#### Perustelut ehdotukselle   

http://www.turkuamk.fi/fi/tyoelamapalvelut/koulutushaku/yhteisomuusikon-erikoistumiskoulutus-muusikkona-sa/ 

**Termiehdotus Fintossa:** [sairaalamuusikot](http://finto.fi/yse/fi/page/Y507369)

**Comment by jtuohini** [comment]
Riittäisikö kuvailuun yhdistelmä _musiikkiterapia_ + _muusikot_ alatermeineen?

**Comment by asormune** [comment]
Kaikki sairaalamuusikot eivät välttämättä ole (koulutettuja) musiikkiterapeutteja, tai tee tuota tehtävää tiukasti terapianäkökulmasta. Kannattaisin sairaalamuusikot termiä.

**Comment by jtuohini** [comment]
En ehdottanutkaan, että käytettäisiin _musiikkiterapeutit_-termiä kuvaamaan kyseisten muusikoiden ymmärtääkseni terapeuttista työtä, vaan termiä _musiikkiterapia_. (Vai onko kyse jostakin epäterapeuttisesta viihdystystoiminnasta vain?) Tällöin voitaisiin muusikon tarkempi laji, olipa soittaja, laulaja, laulaja-lauluntekijä tms. ilmaista ilman, että aina pitäisi laittaa tuo sairaalamuusikot lisäksi. Mutta kyseinen sairaalamuusikkoilmiö on minulle täysin vieras, joten siksi tässä ihmettelen, mistä on edes lopulta kysymys. Eli kaipaisin termille hyvää määritelmää.

**Comment by mariaforsen** [comment]
Näillehän on oma koulutusohjelmakin http://www.turkuamk.fi/fi/tyoelamapalvelut/koulutushaku/yhteisomuusikon-erikoistumiskoulutus-muusikkona-sa/ Ehkä muusikot + sairaalat/hoitolaitokset jne. käy myös? 
https://aamuset.fi/artikkeli/1612634200/Sairaalamuusikko+soittaa+aplodeja+odottamatta

**Comment by asormune** [comment]
Olisko tarve molemmille: sairaalamuusikot ja yhteisömuusikot?

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin "yhteisömuusikot" ottamista YSOon.

LT muusikot, ohjaajat (kasvatus ja opastus)
RT musiikkiterapeutit
KT sairaalamuusikot

**Comment by mariaforsen** [comment]
Sv. samfundsmusiker

**Comment by YSA-kokous** [comment]
Koulutusohjelman nimi kaikissa opinahjoissa (Turun AMK, Metropolia, Jkylä) yhteisömuusikko. Valitaan tämä käytettäväksi termiksi. Hyväksytään Muusan ehdotukset, tosin YSO-ryhmä pohtii vielä yläkäsitettä.

_LT muusikot, ohjaajat (kasvatus ja opastus)
RT musiikkiterapeutit
KT sairaalamuusikot_
