### ISSUE TITLE
ikonografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7370]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ikonografia](http://www.yso.fi/onto/ysa/Y95505) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lavennetaan termin selitys kattamaan myös muu kuvataide kuin pelkkä maalaustaide. 

#### Perustelut ehdotukselle   

"Ikonografia tutkii taideteosten aiheita, ideoita ja merkitystä." [https://fi.wikipedia.org/wiki/Ikonografia] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSAssa termillä ei ole määritelmää. Jos nyt oikein ymmärrän, niin ikonografia ei välttämättä rajaudu edes taiteeseen. Ks. myös issue https://github.com/Finto-ehdotus/YSE/issues/5828

**Comment by YSA-kokous** [comment]
Poistetaan määritelmä.
