### ISSUE TITLE
SLM: ohjelmistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7371]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM: ohjelmistot 

#### Tarkoitusta täsmentävä selite   

MUSA: Solistin, yhtyeen tms. esityksiin sisältyvät sävellykset ("repertuaari"). Yhdistettynä termeihin alkeistaso ja keskitaso termiä käytetään ilmaisemaan yleisen ohjelmiston soveltuvuutta, esimerkiksi ohjelmistot : piano : alkeistaso. 

#### Perustelut ehdotukselle   

Termi tarvittaisiin myös SLM-sanastoon. Termi oli MUSA-sanastossa ja sitä on käytetty laajasti nuottiaineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

O'Neill, John: The saxophone method : repertoire. 1 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [SLM: ohjelmistot](http://finto.fi/yse/fi/page/Y507371)

**Comment by jtuohini** [comment]
Eikö jatkossa riittäisi kuvailussa
   382 01 |a piano |n 1 |s 1 |2 seko
   521 8_ |a Taso: alkeistaso.
   655 _7 |a kokoomateokset |2 slm/fin
Kaikki nuotit ovat aina jollain tasolla ohjelmistoa, ja _kokoomateokset_-käsite kuvastaisi, että kyseessä on nimenomaan joukko yhteen koottuja sävellyksiä?

**Comment by asormune** [comment]
Peukutin molempia. Tosin, kun ei enää ketjuteta, Jaakon ehdotus puoltaisi paikkaansa. Jos määritelmä  on: Solistin, yhtyeen tms. esityksiin sisältyvät sävellykset ("repertuaari"), niin eikös tämä tarkoita nimenomaan jonkun artistin ohjelmistoa, eikä ylipäätään kokoelmia jollekin kokoonpanolle, ja mahdollisesti jossain vaikeusasteessa.
