### ISSUE TITLE
matkasekit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7372]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matkasekit 

#### Ehdotettu termi ruotsiksi   

resechecker 

#### Ehdotettu termi englanniksi   

Travelers' checks 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sekit](http://www.yso.fi/onto/yso/p12319) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Matkasekki 
LCSH : <http://id.loc.gov/authorities/subjects/sh85137174> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Catalogue of travellers cheques of the world 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Termiehdotus Fintossa:** [matkasekit](http://finto.fi/yse/fi/page/Y507372)

**Comment by mariaforsen** [comment]
Sv. resecheckar ET resechecker

**Comment by LeKorsu** [comment]
Tarvitaanko ohjaustermiä matkashekit KÄ matkasekit?
