### ISSUE TITLE
miesurheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7377]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

miesurheilu 

#### Ehdotettu termi ruotsiksi   

herridrott 

#### Ehdotettu termi englanniksi   

men's sports 

#### Ehdotettu yläkäsite YSOssa (LT)   

[urheilu](http://www.yso.fi/onto/yso/p965) 

#### Assosiatiiviset (RT)   

[naisurheilu](http://www.yso.fi/onto/yso/p20071) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Tarkoitusta täsmentävä selite   

Viittaa miesten joukkoeeseen tai kilpailuun urheilulajissa, jossa miehet ja naiset kilpailevat erikseen. 

#### Perustelut ehdotukselle   

Koska termi naisurheilu on käytössä, olisi hyvä olla myös rinnakkaistermi miesurheilu. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. "Urheiluelämää"-tv-ohjelman jakso "Kun jääkiekkounelma toteutuu"  https://rtva.kavi.fi/program/details/program/31296762 

**Ehdottajan organisaatio:** Kansallinen audiovisuaalinen instituutti **Termiehdotus Fintossa:** [miesurheilu](http://finto.fi/yse/fi/page/Y507377)

**Comment by mirmaid** [comment]
Ei Melindassa

**Comment by mirmaid** [comment]
https://blogit.utu.fi/asla/tag/miesurheilu/

**Comment by YSA-kokous** [comment]
Poistetaanko naisurheilu? Seuraava kokous.

**Comment by mirmaid** [comment]
_Naisurheilu_-termiä käytetty Melindassa 220 kertaa, josta n. 80 artikkeliviitteitä. Usein tietueesta puuttui asiasana _naiset_.

Jos poistetaan, pitäisi korvata tietueissa termeillä _naiset_ & _urheilu_.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta _naisurheilu_ enemmistöäänin.
