### ISSUE TITLE
väkivalta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7378]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väkivalta](http://www.yso.fi/onto/ysa/Y100345) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjausterminä fyysinen väkivalta, jonka lisäämistä erikseen ehdotettu. 

#### Perustelut ehdotukselle   

Henkinen väkivalta on sanastossa.

**Comment by mirmaid** [comment]
Käytetty Melindassa 21 kertaa. Ongelmana tässä se, että suuri(n?) osa _väkivalta_-termillä kuvaillusta aineistosta käsittelee fyysistä väkivaltaa, ja varmaan jatkossakin helposti käytettäisiin pelkkää väkivalta-termiä.

**Comment by YSA-kokous** [comment]
Ei muutosta.
