### ISSUE TITLE
interstitiaaliset keuhkosairaudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7379]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

interstitiaaliset keuhkosairaudet 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D017563> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Rheumatoid arthritis-associated interstitial lung disease 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [interstitiaaliset keuhkosairaudet](http://finto.fi/yse/fi/page/Y507379)

**Comment by mariaforsen** [comment]
Sv. interstitiella lungsjukdomar
