### ISSUE TITLE
ketjumurtoluvut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7380]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ketjumurtoluvut 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.oulu.fi/yliopisto/node/52423 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ketjumurtoluvut](http://finto.fi/yse/fi/page/Y507380)

**Comment by mariaforsen** [comment]
Sv. kedjebråk
