### ISSUE TITLE
Ruuskasen talo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7382]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ruuskasen talo 

#### Vaihtoehtoiset termit ja ilmaisut   

Ruuskasen palatsi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Ruuskasen_talo 

#### Perustelut ehdotukselle   

Ruuskasen talo (tunnetaan myös palatsina) on yksi Tampereen Hämeenkadun vanhoista taloista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tammerkoski-lehden artikkelien kuvailu, esim.: Ruuskasen palatsi kertoo historiaa / Kyllikki Helenius. 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [Ruuskasen talo](http://finto.fi/yse/fi/page/Y507382)

**Comment by mariaforsen** [comment]
Sv. Ruuskanens hus
