### ISSUE TITLE
pimekrolimuusi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7383]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pimekrolimuusi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/012224132 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [pimekrolimuusi](http://finto.fi/yse/fi/page/Y507383)

**Comment by mariaforsen** [comment]
Sv. pimekrolimus
