### ISSUE TITLE
nukkekodin kalusteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7384]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nukkekodin kalusteet 

#### Perustelut ehdotukselle   

Sanastossa on Nukenhuonekalut sekä Nukkekodit, mutta nukenhuonekaluilla tarkoitetaan myös isompia leikkikaluja, esimerkiksi 10-50 cm pitkiä sänkyjä ja vastaavan kokoluokan muita leluhuonekaluja. Niitäkin on museokokoelmissa usein paljon, kuten nukkekodin kalusteitakin. Olisi tarpeen pystyä erottelemaan nämä haussa. 

#### Tarkoitusta täsmentävä selite   

nukketalojen kalusteet ja muu sisustustarpeisto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

museoesineiden kuvailussa 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [nukkekodin kalusteet](http://finto.fi/yse/fi/page/Y507384)

**Comment by mirmaid** [comment]
Nukenhuonekalut löytyy siis MAO-ontologiasta, http://www.yso.fi/onto/mao/p2116.

**Comment by jtuohini** [comment]
Olisiko parempi muoto _nukkekodinkalusteet_, _nukkekotien kalusteet_ tai _nukkekotikalusteet_? Erikseen kirjoitettuna ehdotettu viittaa yksittäisen, puheena jo olevan nukkekodin kalusteisiin. Mutta mikä tahansa muodoksi otettaneenkin, niin kaikki muut toki KT-muodoiksi!

**Comment by LeKorsu** [comment]
Peukku nukkekotikalusteille.

**Comment by mirmaid** [comment]
Googlella aivan ylivoimaisesti eniten erikseen kirjoitettuna.

**Comment by mariaforsen** [comment]
Sv. dockhusmöbler

**Comment by ilona-x** [comment]
LCSH: Miniature furniture http://id.loc.gov/authorities/subjects/sh85085661
ST Doll furniture
ST Miniature chairs

minikalusteet & minihuonekalut tuottavat jonkinverran osumia Googlella

**Comment by LeKorsu** [comment]
Automaattista sisällönkuvailua mm. mediataloille tuottavalla Leikillä on käsitteenä nukkekotikalusteet ja englanninkielisenä vastineena miniature furniture

**Comment by jtuohini** [comment]
Linkitys LCSH:n jo mainittuun asianaan **Miniature furniture** ei sikäli ole oikein, että kyseinen termi kattaa myös huonekalujen pienoismallit. Nukkekotien kalusteiksi tarkoitettuja varten on ihan oma asiasanansa, ilona-x:n myös mainitsema [**Doll furniture**](http://id.loc.gov/authorities/subjects/sh85038854.html).

**Comment by YSA-kokous** [comment]
Nukkekodin kalusteet
