### ISSUE TITLE
riippumattomien komponenttien analyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7387]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

riippumattomien komponenttien analyysi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/012238514 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [riippumattomien komponenttien analyysi](http://finto.fi/yse/fi/page/Y507387)

**Comment by satuniininen** [comment]
LCSH:ssa [Independent component analysis](http://id.loc.gov/authorities/subjects/sh2011000546)

**Comment by mariaforsen** [comment]
Sv. oberoende komponentanalys ET analys av oberoende komponenter
