### ISSUE TITLE
harmonichord

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7388]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

harmonichord 

#### Ehdotettu termi ruotsiksi   

harmonichord 

#### Ehdotettu termi englanniksi   

harmonichord 

#### Vastaava käsite muussa sanastossa   

LCMPT : <http://id.loc.gov/authorities/performanceMediums/mp2019015004> 

#### Perustelut ehdotukselle   

SEKO-sanastoon: tarvitaan musiikin esityskokoonpanon kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Weber, Carl Maria von. Adagio und Rondo, J115, F-duuri. 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [harmonichord](http://finto.fi/yse/fi/page/Y507388)

**Comment by jtuohini** [comment]
LT kosketinsoitin

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
