### ISSUE TITLE
lähiöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7390]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lähiöt](http://www.yso.fi/onto/ysa/Y100714) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT–ST-suhde asiasanaan "asuinalueet". 

#### Perustelut ehdotukselle   

Kaikki lähiöt ovat asuinalueita, joten termien välillä pitäisi vallita LT–ST-hierarkia. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7313

**Comment by mirmaid** [comment]
Lisätty.
