### ISSUE TITLE
kuljetusproteiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7391]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuljetusproteiinit 

#### Vaihtoehtoiset termit ja ilmaisut   

kuljettajaproteiinit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[proteiinit](http://www.yso.fi/onto/yso/p4332) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D002352> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85020470> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/012209330 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kuljetusproteiinit](http://finto.fi/yse/fi/page/Y507391)

**Comment by mariaforsen** [comment]
Sv. bärarproteiner ET transportproteiner
