### ISSUE TITLE
proteoglykaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7393]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

proteoglykaanit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[proteiinit](http://www.yso.fi/onto/yso/p4332) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85107683> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/011644355 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [proteoglykaanit](http://finto.fi/yse/fi/page/Y507393)

**Comment by mariaforsen** [comment]
Sv. proteoglykaner
