### ISSUE TITLE
käsikirjoittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7394]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[käsikirjoittajat](http://www.yso.fi/onto/ysa/Y108556) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ryhmäksi 96 Valokuvaus, Elokuva. 

#### Perustelut ehdotukselle   

Tuli vastaan Wikidata-linkityksen yhteydessä. Wikipedian mukaan "käsikirjoittaja tekee käsikirjoituksen eli suunnitelman siitä, millainen elokuvasta, näytelmästä tai muusta vastaavasta tuotannosta tulee." Melinda-kuvailua silmäillessä suurin osa kuvaillusta aineistosta liittyy elokuvaan. Kun YSA-ryhmänä on ainoastaan 87 Kirjallisuus niin herää kysymys, että eikö tämä liitykään elokuviin. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by LeKorsu** [comment]
Myös ryhmän 80 Viestintä. Tiedonvälitys. Joukkoviestintä voisi lisätä samalla.

**Comment by mirmaid** [comment]
Termillä _käsikirjoitukset_ on ryhmät 82 (Kustannustoiminta. Julkaisutoiminta. Kirjapainoala) ja 87, termillä _käsikirjoittaminen_ 80 (Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta) ja 87. Käsikirjoittamista on siis pidetty ensisijaisesti kirjallisuuden alaan kuuluvana, teatteri, elokuva jne. sitten tuottavat käsikirjoituksesta esityksen. Mutta epäjohdonmukaisuutta on, kuten tuo 80-ryhmä osoittaa.

**Comment by YSA-kokous** [comment]
Yhdenmukaistetaan ryhmiä.
