### ISSUE TITLE
varhaismoderni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7396]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

varhaismoderni 

#### Ehdotettu termi englanniksi   

early modern period 

#### Ehdotettu termi ruotsiksi   

tidigmoderna tiden 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Varhaismoderni

Varhaismoderni aika eli varhainen uusi aika 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://blogs.uta.fi/trivium/2015/02/ 

**Termiehdotus Fintossa:** [varhaismoderni](http://finto.fi/yse/fi/page/Y507396)

**Comment by jtuohini** [comment]
Mieluummin muotoon _varhaismoderni aika_. Pelkkä "varhaismoderni" on adjektiivi, eivätkä sellaiset sovellu kovin hyvin asiasanoiksi.

**Comment by vthuhtala** [comment]
Selitykseen vuosiluvut

**Comment by AuHo22** [comment]
https://tieteentermipankki.fi/wiki/Historia:uusi_aika
https://tieteentermipankki.fi/wiki/Arkeologia:uusi_aika
https://fi.wikipedia.org/wiki/Uusi_aika

varhaismoderni aika / uusi aika / uusin aika -jaottelu ja eronteko?
YSOssa uuden ajan alku

**Comment by mariaforsen** [comment]
YSOssa on tosiaan jo uuden ajan alku=tidigmodern tid, eli tämä ehdotus olisi uusi ohjaustermi.

**Comment by YSA-kokous** [comment]
varhaismoderni aika KÄ uuden ajan alku
