### ISSUE TITLE
autoritarismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7398]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

autoritarismi 

#### Ehdotettu termi englanniksi   

authoritarianism 

#### Ehdotettu termi ruotsiksi   

auktoritarianism 

#### Vaihtoehtoiset termit ja ilmaisut   

autoritaariset valtiot 
autoritaariset hallinnot 
autoritaarinen yhteiskunta 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85009788 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Autoritarismi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Environmentalism under authoritarian regimes isbn 978-1-138-54328-7 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 

**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [autoritarismi](http://finto.fi/yse/fi/page/Y507398)

**Comment by mirmaid** [comment]
Sanastossa on _autoritaarisuus_, jonka yläkäsitteena on persoonallisuuden piirteet, mutta sitä on käytetty runsaasti myös tässä merkityksessä.

**Comment by mariaforsen** [comment]
Sanastossa oleva autoritaarisuus on luokassa Psykologia ja sen mukaan ruotsiksi: auktoritär personlighet. On kuitenkin mahdollista tehdä muutos tähän jos halutaan myös politiikan yms. merkityksessä. Ks. https://www.psykologiguiden.se/psykologilexikon/?Lookup=auktoritarianism%2C+auktorit%C3%A4rianism%2C+auktoritarism

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. ihmisestä: muita hallitsemaan ja määräilemään pyrkivä. _Autoritaarinen isä, persoonallisuus._
2. pol. keskitetysti johdettu, vars. yhden henkilön ratkaisuvallan alainen. _Autoritaarinen järjestelmä, yhteiskunta._ 

Melindan viitteissä autoritaarisuus parisuhteessa, vanhemmuudessa, työyhteisössä, uskonnollisessa liikkeessä, ääriliikkeessä, valtiossa.

**Comment by YSA-kokous** [comment]
KÄ autoritaarisuus, kielivastineet ja hierarkia korjattava
