### ISSUE TITLE
kylmähoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7402]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kylmähoito](http://www.yso.fi/onto/ysa/Y167128) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi tai käytettäväksi termiksi huippukylmähoito. 

#### Perustelut ehdotukselle   

Mihin käsite viittaa: jääpusseihin vai kylmähuoneisiin vai molempiin? Suomenkielinen ohjaustermi (kryohoito) ja ruotsin ja englannin vastineet antaisivat ymmärtää, että käsitteeseen sisältyisi kylmähuonehoidon merkitys. Tarkin vastine tälle suomen kielessä lienee huippukylmähoito. Pelkkä kylmähoito ilman huippu-etuliitettä viittaa (huippukylmähoidon lisäksi) kylmäpusseihin ja kylmägeeleihin.

Ks. https://fi.wikipedia.org/wiki/Huippukylm%C3%A4hoito 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
FinMeSH: kylmähoito http://finto.fi/mesh/fi/page/D017679

**Comment by mirmaid** [comment]
Lääketieteen termit: _1. sairauden tai vamman paikallishoito kylmyyden avulla (esim. jääpussilla); vrt. jäädytyskirurgia; 2. ks. pakkaskammiohoito_

jäädytyskirurgia: _ihon tai sisäelimen muutoksen käsittely tai tuhoaminen esim. nestemäisellä typellä tai hiilihappojäällä tai jäädyttämällä erityisellä laitteella; vrt. etanoli-injektiohoito, kauterisaatio, kylmähoito, termokoagulaatio_

pakkaskammiohoito: _huippukylmähoito, superkylmähoito | lyhytaikainen (1–3 minuuttia) altistaminen erittäin kylmälle ilmalle (–110 ○C) erityisessä pakkaskammiossa niveltulehdusten tai ihottumien, esim. psoriaasin, hoitona_

**Comment by mariaforsen** [comment]
Ruotsiksi frysbehandling, mesh kryoterapi, muutos mahdollinen (myös kylbehandling=kylmäkäsittely sanastossa)? ET kryobehandling?

Frysbehandling=jäädytyshoito ks. https://www.vaasankeskussairaala.fi/potilaille/hoito-ja-tutkimukset/erikoisalat/ihotaudit2/jaadytyshoito/ Jos tarkoitus on kattaa näitä kaikkia pitäisi varmaan lisätä KT "jäädytyshoito"

**Comment by YSA-kokous** [comment]
Selvitetään

**Comment by mirmaid** [comment]
68 viitettä Melindassa, käytetty molemmissa merkityksissä, lisäksi esim. kylmävesihoidosta.

**Comment by YSO-kokous** [comment]
Päätettiin ottaa jäädytyskirurgia erillisenä käsitteenä. Kylmähoito kattaa jatkossakin pakkaskammiohoidon ja kylmäpussihoidon merkitykset. Kylmähoidolle ohjaustermiksi huippukylmähoito ja muita tarpeellisia YSO-ylläpidon harkinnan mukaisesti. Päätös tehtiin äänestyksellä.

Taustaa: Kylmäpussihoidosta ja pakkaskammiohoidosta käytetään molemmista termiä kylmähoito. MeSHissä nämä merkitykset on yhdistetty käsitteeksi kylmähoito. Jäädytyskirurgia on käsitteistä ehkä selkeimmin erillinen.

**Comment by tpalonen** [comment]
MeSHin osalta termisekaannusta. Mirja tutkii vielä.

**Comment by ilona-x** [comment]
**Cryotherapy
Kryoterapi**
https://mesh.kib.ki.se/term/D017679/cryotherapy

Svensk definition
En behandlingsform som innebär bruk av lokal eller allmän nedkylning i terapeutiskt syfte. Selektiv förstörelse av vävnad genom nedfrysning är fryskirurgi.

Engelsk definition
A form of therapy consisting in the local or general use of cold. The selective destruction of tissue by extreme cold or freezing is CRYOSURGERY. (McGraw-Hill Dictionary of Scientific and Technical Terms, 4th ed)

**Cryosurgery
Fryskirurgi**
https://mesh.kib.ki.se/term/D003452/cryosurgery

Svensk definition
Nedfrysning som kirurgisk teknik för att förstöra eller avlägsna vävnad.

Engelsk definition
The use of freezing as a special surgical technique to destroy or excise tissue.

**Comment by mirmaid** [comment]
FinMeSH kylmähoidolla ohjausterminä esim. nestetyppikryohoito. Tämä olisi kuitenkin jäädytyskirurgiaa.

**Comment by mirmaid** [comment]
Lääketieteen termit: kryokirurgia: ihon tai sisäelimen muutoksen käsittely tai tuhoaminen esim. nestemäisellä typellä tai hiilihappojäällä tai jäädyttämällä erityisellä laitteella; vrt. etanoli-injektiohoito, kauterisaatio, kylmähoito, termokoagulaatio. 

Löytyy myös kryokoagulaatio, jonka käsittäisin myös kryokirurgiaksi, vaikka FinMeSHissä tämäkin ohjaa kylmähoitoon. Mielestäni voidaan FinMeSHistä välittämättä tehdä ehdotettu jako.

**Comment by FinMeSHienPaimentaja** [comment]
"Kylmähoito" MeSH:in mukaan:

"Cryotherapy"

Scope Note

A form of therapy consisting in the local or general use of cold. The selective destruction of tissue by extreme cold or freezing is CRYOSURGERY. (McGraw-Hill Dictionary of Scientific and Technical Terms, 4th ed).

https://meshb.nlm.nih.gov/record/ui?ui=D017679

"Kylmähoito" lääketieteen termit Terveysportin kautta: 

kylmähoito

cryotherapia la, cryotherapy e, kryoterapi ‑n r (< kryos kr kylmyys + therapeia kr hoito) 1. sairauden tai vamman paikallishoito kylmyyden avulla (esim. jääpussilla); vrt. jäädytyskirurgia; 2. ks. pakkaskammiohoito

https://www.terveysportti.fi/sovellukset/sanakirjat/#/q//lte11844

"Huippukylmähoito" eli "pakkaskammiohoito" sisältyy siis "kylmähoitoon", jollei sitä haluta omana terminään.

Joo, FinMeSH:eissä on wanhoina synonyymeina (väärin) esim. nestetyppikylmähoidot, jotka on jäädytyskirurgiaa. (Korjataan ensin vuoden sanastopäivityksessä).

**Comment by YSO-kokous** [comment]
Pitäydytään edellisen YSO-kokouksen päätöksessä eli otetaan "jäädytyskirurgia erillisenä käsitteenä. Kylmähoito kattaa jatkossakin pakkaskammiohoidon ja kylmäpussihoidon merkitykset. Kylmähoidolle ohjaustermiksi huippukylmähoito ja muita tarpeellisia YSO-ylläpidon harkinnan mukaisesti."

YSOn ylläpito miettii sopivat ohjaustermit.
