### ISSUE TITLE
Matalajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7403]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Matalajärvi](http://www.yso.fi/onto/ysa/Y153835) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitää jakaa tai ainakin lisätä tarkenne 

#### Perustelut ehdotukselle   

Käytetty väärästä Matalajärvestä Melindassa. Ks. myös Paikkatietoikkunaa, Matalajärviä on monessa paikassa.

**Comment by mirmaid** [comment]
Matalajärvi (Espoo). Epäselvää, mitä järveä/paikkaa Melindan kahdessa muussa viitteessä tarkoitetaan.
