### ISSUE TITLE
quechua (folk)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7406]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

quechua (folk) 

#### Ehdotettu termi englanniksi   

quechua indians 

#### Vaihtoehtoiset termit ja ilmaisut   

kichwa (folk) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[indianer](http://www.yso.fi/onto/yso/p646) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q134936 
LCSH : Quechua Indians 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Folktradition. Traditionsforskning. Kulturantropologi. Ockultism](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Tarvitaan Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Indians of the Andes :Aymaras and Quechuas 

**Termiehdotus Fintossa:** [quechua (folk)](http://finto.fi/yse/fi/page/Y507406)

**Comment by mirmaid** [comment]
ketšuat (?)

_Quechua people or Quecha people, may refer to any of the indigenous people of South America who speak the Quechua languages, which originated among the indigenous people of Peru._

**Comment by krinay** [comment]
Kannatan kirjoitusasua _ketšuat_, se vastaa kielestä suomeksi käytettävää termiä (ketšua). Ohjaustermiksi suomeksikin quechuat?
