### ISSUE TITLE
Suomenlinna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7408]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Suomenlinna](http://www.yso.fi/onto/ysa/Y94425) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSOssa on nyt siis linnoitusta tarkoittava Suomenlinna, ja YSO-paikoissa kaupunginosaa tarkoittava Suomenlinna (Helsinki). Tarvitaanko tähän selkeytystä? Wikipedia: Suomenlinna & Suomenlinna (kaupunginosa). 

#### Perustelut ehdotukselle   

Aikaisemmin YSAssa paikkatermi oli muotoa Helsinki -- Suomenlinna. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. Sveaborg (sjöfästningar) =yläkäsite, Sveaborg (stadsdel)

**Comment by YSA-kokous** [comment]
Suomenlinnan merilinnoitus?

**Comment by mirmaid** [comment]
https://www.myhelsinki.fi/fi/n%C3%A4e-ja-koe/n%C3%A4ht%C3%A4vyydet/suomenlinnan-merilinnoitus
https://www.myhelsinki.fi/sv/se-och-g%C3%B6ra/sev%C3%A4rdheter/sveaborgs-sj%C3%B6f%C3%A4stning
https://www.maailmanperinto.fi/suomenlinnan-merilinnoitus/
https://www.hel.fi/helsinki/fi/kaupunki-ja-hallinto/osallistu-ja-vaikuta/ota-yhteytta/hae-yhteystietoja/toimipistekuvaus?id=20909

**Comment by mirmaid** [comment]
Suomenlinnan merilinnoitus KT Suomenlinna (merilinnoitus)
