### ISSUE TITLE
kovalevyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7410]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kovalevyt](http://www.yso.fi/onto/ysa/Y96428) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sekoittuu kiintolevyihin 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Kova_kuitulevy

http://www.tsk.fi/tepa/fi/haku/kovalevy

**Comment by mariaforsen** [comment]
ALLFO: hårda träfiberskivor

**Comment by YSA-kokous** [comment]
kovakuitulevyt
