### ISSUE TITLE
Sarek

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7411]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Sarek 

#### Ehdotettu termi ruotsiksi   

Sarek 

#### Ehdotettu termi englanniksi   

Sarek 

#### Vastaava käsite muussa sanastossa   

SAO : Sarek 

#### Perustelut ehdotukselle   

Tarvittu Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Min bästa fjällfärd 

**Termiehdotus Fintossa:** [Sarek](http://finto.fi/yse/fi/page/Y507411)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Sarek

**Comment by YSA-kokous** [comment]
Kansallispuisto
