### ISSUE TITLE
Abisko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7412]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Abisko 

#### Ehdotettu termi ruotsiksi   

Abisko 

#### Ehdotettu termi englanniksi   

Abisko 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Abisko 
SAO : Abisko 

#### Perustelut ehdotukselle   

Tarvittu Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

På fjälltur :Kebnekaise och Abisko : turbeskrivningar 

**Termiehdotus Fintossa:** [Abisko](http://finto.fi/yse/fi/page/Y507412)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Abiskon_kansallispuisto (?)

**Comment by AuHo22** [comment]
Kungsleden on myös terminä 
https://fi.wikipedia.org/wiki/Kungsleden

**Comment by mariaforsen** [comment]
Melindan perusteella "Abisko" olisi eniten tarvittu/käytetty.

Sv. Abisko (Kiruna), Abisko nationalpark

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Abisko

**Comment by YSA-kokous** [comment]
Paikkatermi ja kansallispuisto.
