### ISSUE TITLE
juhlajulkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7413]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[juhlajulkaisut](http://www.yso.fi/onto/ysa/Y95647) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

? 

#### Perustelut ehdotukselle   

YSO-kokouksessa todettua että juhlajulkaisut kattavat suomeksi kaikki julkaisutyypit, ja tämän alle olisi haluttu esim. juhlajulkaisulevyt (tribuutit). Ruotsiksi kuitenkin "festskrifter" eli vain kirjallinen aineisto.

Kuitenkin huomioitava että festskrifter on erittäin tärkeä ja paljon käytetty termi (myös MDO, Genre jne.) Jos todella halutaan muutoksia yksi mahdollinen ratkaisu on ottaa juhlakirjat=festskrifter ja luoda juhlajulkaisuille vastineeksi "jubileumspublikationer" (myös publikation tosin yleensä viittaa kirjalliseen tuotteeseen..) Koska sitä ei kuitenkaan juuri käytetä (vaan festskrifter) olisi sitten tärkeää ohjata myös suomeksi käyttämään tarkempi termi juhlakirjat aina kun aineisto koskee niitä (muuten vaarana on se että suomeksi käytetään jatkossakin lähinnä juhlajulkaisut, mutta ruotsiksi käytetään aina festskrifter). Jos tehdään muutoksia tähän, se vaatii myös laajoja korjauksia tietokantoihin.

Luetteloinnissa käytettäisiin varmaan miten vain edelleen juhlajulkaisut=festskrifter (ks. MARC21 esim. 008: https://www.kansalliskirjasto.fi/extra/marc21/bib/008.htm)

**Comment by mirmaid** [comment]
Käytetty varmaankin lähes yksinomaan genreterminä, mutta mahdollinen muutos kannattaa tehdä samalla tavalla molempiin sanastoihin. Käytetty myös äänitteistä, mutta erittäin vähän verrattuna kirjoihin.

**Comment by YSO-kokous** [comment]
Tribuutit-käsitteelle ohjaustermi juhlajulkaisut (levyt) JA juhlajulkaisulevyt. Ei muita muutoksia. Tribuutit ei voi olla juhlajulkaisujen alakäsite ruotsin kielen vastineen vuoksi.
