### ISSUE TITLE
vanhukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7414]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vanhukset](http://www.yso.fi/onto/ysa/Y100063) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄYTÄ ikääntyneet tai tarkka määrittely milloin/mistä käytetään termiä vanhukset ja milloin/mistä ikääntyneet 

#### Perustelut ehdotukselle   

Miten nämä eroavat toisistaan? Eli tarvitaan tarkkoja määritelmiä niin että voidaan ruotsiksi luoda tarkenteita: äldre (?), äldre (?). Jos suomeksi todella halutaan pitää nämä molemmat sanastossa? Ruotsiksi näiden kohdalla on nyt vakava virhe: åldringar, äldre = sama asia

https://www.theseus.fi/bitstream/handle/10024/117860/Laakso_Martta_Leinonen_Heini_2016_11_25.pdf.pdf?sequence=1

Huom. sanastossa myös ikääntyminen=åldrande ja vanheneminen=bli gammal (ongelmallinen)

**Comment by satuniininen** [comment]
Ovat todellakin pahasti päällekkäisiä, Melindassa on yli 7000 tietueeseen laitettu molemmat.

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7209

**Comment by mirmaid** [comment]
[Opinnäytetyö aiheesta](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwjv79Hm-KbgAhWMiKYKHS6DDB0QFjACegQIBxAC&url=https%3A%2F%2Fwww.theseus.fi%2Fbitstream%2Fhandle%2F10024%2F117860%2FLaakso_Martta_Leinonen_Heini_2016_11_25.pdf.pdf%3Fsequence%3D1&usg=AOvVaw3Gku72e5iURFvwAX-FITB8)

_Kaikki sukupolvet kuvailivat ikään-tynyttä ja ikäihmistä aktiiviseksi ja hyväkuntoiseksi. Näiden käsitteiden merkittävä eroavaisuus on se, että ikääntyneen voidaan olettaa olevan työelämässä, kun taas ikäihmisen oletetaan olevan eläkkeellä. Kaikki sukupolvet kokevat seniorin aktiivista arkea eläväksi yksilöksi. Vanhus taas koetaan yleisesti toimintakyvyl-tään heikoksi ja käsitteenä viimeiseksi ikääntymistä kuvaavaksi vaiheeksi._

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/964

**Comment by mirmaid** [comment]
Tässä vielä yksi linkki: https://yle.fi/uutiset/3-7513924

Mutta siis joko yhdistetään > _ikääntyneet_ (kaikki yli 65-vuotiaat) tai keksitään jokin määritelmät _vanhukset_-termille, jolloin sitä voisi halutessa käyttää ikääntyneen alakäsitteenä. Voiko siis ruotsiksi ajatella että jo 65-vuotias on _åldring_?

**Comment by ilona-x** [comment]
FinMeSHin jaottelu:
aikuinen
-nuoret aikuiset
-keski-ikäiset
-**vanhukset KT ikääntyneet, iäkkäät, ikäihmiset**
--heiveröiset vanhukset
--yli 80-vuotiaat iäkkäät

**Comment by mariaforsen** [comment]
Ruotsiksi suositeltava/asiallinen termi on siis äldre, åldring pitäisi olla korvattuna (ks. myös SAO, Rikstermbanken). Ruotsin osalta ainoa järkevä ratkaisu olisi siis yhdistäminen. 

Meshin jaottelu ei varmaan sovi yleissanastoon.

**Comment by mirmaid** [comment]
Ikääntyminen=åldrande ja vanheneminen=bli gammal -ongelma on helpointa käsitellä erillisessä issuessa.

**Comment by mirmaid** [comment]
Mielenkiintoinen tähän aihepiiriin liittyvä aineisto, https://melinda.kansalliskirjasto.fi/byid/016651308 ("younger old and older old").

**Comment by ilona-x** [comment]
Nämä ovat kyllä tosiaan aika päällekkäiset, kuten Satu tuolla aiemmin mainitsi niin Melindassa on yli 7000 viitettä, joissa on molemmat termit. Koitin hakea Melindasta tietueita, joissa esiintyy vain toinen näistä. Haku ikääntyneet yso NOT vanhukset NOT ikääntyvät työntekijät tuottaa 1060 viitettä ja vanhukset yso NOT ikääntyneet 9765 viitettä. Toki ikääntyneet on otettu sanastoon vasta vuonna 1999.

Mikäli nämä päädytään yhdistämään olen vanhusten kannalla. Jos vanhukset tuntuu jonkin aineiston kohdalla huonolta termiltä, voisi näissä monissa käyttää termiä ikääntyminen (joskus myös ikääntyvät työntekijät, eläkeläiset). Eli vanhukset on ongelma puhuttaessa yli 65-vuotiaista hyväkuntoisista ihmisistä. Mutta missä vaiheesssa sitten ihminen muuttuu vanhukseksi. Kyllähän jotkut yli 80-vuotiaatkin ovat vielä hyväkuntoisia ja mukana työelämässä.:smile:  Eli väkisinkin on paljon aineistoja, joihin täytyy laittaa nämä molemmat termit, kun ei ole olemassa selkeitä ikärajoja tai muuta tarkkaa määritelmää siitä, kuka on ikääntynyt ja kuka vanhus. Kielitoimiston sanakirjan määritelmän mukaan vanhuus = keski-ikää seuraava ihmisen viimeinen ikäkausi.

**Comment by ilona-x** [comment]
Kolmas ikä : Uusi näkökulma väestön vanhenemiseen https://helda.helsinki.fi/handle/10224/4042

TSR-ontologiassa kolmas ikä http://www.yso.fi/onto/tsr/p12227
Ehdotettu myös YSOon: https://github.com/Finto-ehdotus/YSE/issues/4043

**Comment by ilona-x** [comment]
TEROssa: 
**iäkkäät (65-79 vuotta)**  
KT ikäihmiset
KT ikääntyneet
KT vanhukset
http://www.yso.fi/onto/tero/D000368

Tämän lisäksi TEROssa myös vanhukset: http://www.yso.fi/onto/tero/p2434

JUPO:
ikäihmiset
KT seniorit
KT vanhukset
http://www.yso.fi/onto/jupo/p760

**Comment by LeKorsu** [comment]
Tietää isoa muutostyötä Melindaan, mutta en oikein näe muuta järkevää ratkaisua kuin yrittää ikätarkenteella selventää asiaa
iäkkäät (65- vuotta) sv äldre (65- år) KT vanhukset (vaikka Ilona onkin vanhukset-termin kannalla)
Toinen vaihtoehto voisi olla Jupon ikäihmiset (65- vuotta)

**Comment by ilona-x** [comment]
https://www.terveyskyla.fi/ikatalo/ik%C3%A4%C3%A4ntyneelle/ik%C3%A4-ja-arki/ik%C3%A4%C3%A4ntynyt-i%C3%A4k%C3%A4s-vai-vanha

**Comment by YSO-kokous** [comment]
Yhdistetään ikääntyneet ja vanhukset. Käytettäväksi termiksi ikääntyneet, ohjaustermiksi vanhukset JA iäkkäät. Perustelu käytettävälle termille: Ikääntyneet on ollut sanastossa jo pitkään ja käytetty paljon. Muut termit ongelmallisempia kuin ikääntyneet.

Keskustelu: Tyypillisesti kun kuvaillaan käsitteellä ikääntyneet, kuvaillaan samalla myös käsitteellä vanhukset. Ovat siis vahvasti päällekkäiset. Sosiaalialan sanastossa suositeltu termi "iäkkäät". Kaikki ihmiset ikääntyvät (vrt. ikääntyneet), joten iäkäs indikoi paremmin, että on saavutettu jo tietty ikä. Iäkäs on kuitenkin määritelty Sosiaalialan sanastossa ja laissa kunnoltaan heikentyneeksi. Ikääntyneet-käsitteellä ei tällaista kuntoon liittyvää merkitystä ja määrityksenä sen sijaan (terveyskyla.fi:n mukaan), että on oikeus vanhuuseläkkeeseen.
