### ISSUE TITLE
hajotus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7415]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hajotus](http://www.yso.fi/onto/ysa/Y113596) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaikuttaa olevan käytetty melkein vain biologisena/kemiallisena. Tämä merkitys on myös ruotsin vastineella sönderdelning. Voisiko määritellä käytettäväksi näin, eikä esim. "hallituksen hajotuksessa"? 

#### Perustelut ehdotukselle   

-

**Comment by mariaforsen** [comment]
Auttaisiko esim. huomautuksen lisääminen: "Jakaa yksinkertaisemmiksi yhdisteiksi tai alkuaineiksi" /Kielitoimiston sanakirja

**Comment by mirmaid** [comment]
Määritelmä ei varmaan estä käyttämästä väärin, mutta tähänkin asti tosiaan melkein aina kyseessä kemia tai biokemia - hallitukseen, joukkoihin tms. liittyviä viitteitä on muutamia. Kemia olisi tarkenteena varmaankin riittävän laaja, mutta voisi aiheuttaa ongelmia jos nähtäisiin kovin teknisenä.

**Comment by LeKorsu** [comment]
Hajotus (hajottaminen) on kuitenkin käytössä oleva termi valtiotieteissä. Pitäisikö sitten ottaa ysoon eks:n asiasana "eduskunnan hajottaminen", jos hajotus halutaan rajata biologiaan? (Hallituksen hajoaminen tai hallituksen hajottaminen -asiasanoja ei eks:ssä näytä olevan.)

**Comment by YSO-kokous** [comment]
Käsitettä käytetty kuvailussa varsin vähän vääriin eli ei tarvetta suurille muutoksille. Lisätään tälle määritelmä, esim. Kielitoimiston sanakirjasta inspiraatiota hakien.

Lisäksi: lisätään "parlamentin hajottaminen" käsitteelle ohjaustermit: eduskunnan hajottaminen, hajottaminen (eduskunta/parlamentti)
