### ISSUE TITLE
sitoutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7416]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sitoutuminen](http://www.yso.fi/onto/ysa/Y110828) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava/tarkennettava? 

#### Perustelut ehdotukselle   

Käytetty jonkin verran (ehkä n. 5-10% viitteistä) kemian kontekstissa (usein esim. lääkeaineista).

**Comment by mirmaid** [comment]
https://github.com/NatLibFi/Finto-data/issues/943

**Comment by mariaforsen** [comment]
Kemia-merkityksessä olisi sv. bindning, mutta se on jo vastineena sidonta-termille: https://finto.fi/yso/fi/page/p12174?clang=sv
Ks. myös http://tieteentermipankki.fi/wiki/Mikrobiologia:sidonta
http://www.tsk.fi/tepa/fi/haku/sidonta

**Comment by mariaforsen** [comment]
MOT Finnish-Swedish; Finnish-Swedish: sitoutuminen 
1 (sitoumus) förpliktelse [-n,-r,-rna] -eli nyt YSOssa
2 (tehtäväksi ottaminen) åtagande [-t,-n,-na]
3 kem bindning [-en,-ar,-arna] -nyt YSOssa vastineena sidonta-termille
4 oik ingående av förbindelse/förpliktelse [-t,-,-]

Eli sekä sitoutuminen että sidonta ovat nyt hyvin ongelmallisia käännösten kannalta, se että nämä ovat ryhmässä 00 vaikeuttaa.

**Comment by mirmaid** [comment]
_Use of melanin binding as drug delivery strategy to the posterior eye segment_ - ainakin englanninkielinen _committing oneself_ on ehkä hiukan vinkeä tässä lääkeaineesta käytettynä, mutta ilmeisesti _förbindelse_ on ok?

**Comment by mariaforsen** [comment]
Ei taida olla? Jos tässä oli jostain kemiallisesta kyse. 
https://svenska.se/tre/?sok=f%C3%B6rbindelse&pz=1

**Comment by mirmaid** [comment]
Tuota kemiaa on siis melko pieni osa viitteistä ja sitä voisi ehkä yrittää jotenkin ohjata pois tästä, mutta onhan tuo förbindelse muuten yhtä kattava kuin sitoutuminen? Suurin osa viitteistä liittyy siihen, että henkilö sitoutuu johonkin toimintaan tai yhteisöön, esim. työhön tai hoitoon. Mietin vaan kun tuossa sanakirjassa on tuo oik...

**Comment by mariaforsen** [comment]
Joo ei ole samanlaista merkityskenttää/käyttöä näillä varmaankaan, ainoa tapa saada sama merkityskenttä on tällaisissa tapauksissa että tarkentaa molemmilla kielillä.

**Comment by mirmaid** [comment]
Käytetty Melindassa 1574 kertaa. Lähes yksinomaan siis merkityksessä "ihmisen sitoutuminen johonkin yhteisöön tai toimintaan" (esim. ihmissuhteeseen, sairauden hoitoon tai vaikka tietyn brändin tuotteisiin). Mikä tämä siis olisi ruotsiksi? Nyt vastine on siis _förbindelse (=yhteys, sitoumus?)_, pitäisikö olla oikeastaan "binda sig"?

**Comment by mirmaid** [comment]
Joukossa on siis kourallinen viitteitä, joissa sitoutuminen viittaa biokemialliseen tapahtumaan. Tätä voisi yrittää ohjata pois, mutta sanastossa on vain _kemialliset sidokset_, joka ei varmaan toimi kovin hyvin, ja _sidonta_. 

MeSHissä on _proteiineihin sitoutuminen_.

Esim. kemia/biokemia (400 ensimmäistä viitettä)

_Vanadiinin(IV) sitoutuminen maa-ainekseen ja siihen vaikuttavat tekijät
[Non-labelled surface sensitive techniques as platforms for pharmaceutical nanotechnology research](https://helda.helsinki.fi/handle/10138/40262)
Prediction of 3D structure and ligand-binding properties : ABC transporters and flavodiiron proteins from Synechocystis sp. strain PCC 6803
Effect of ligand-binding on protein function
Pathogenetic mechanisms and genotype-phenotype correlations in nemaline myopathies and related disorders caused by mutations in the tropomyosin genes and nebulin
Binding affinity and mechanism of polymer-DNA polyplexes for gene delivery
Retention of orthophosphate, arsenate and arsenite onto the surface of aluminum or iron oxide-coated light expanded clay aggregates (LECAs) : a study of sorption mechanisms and anion competition
The alpha[sub]2C-adrenoceptor as a neuropsychiatric drug target : PET studies in human subjects
Oreksiini-A:n kaksi vaihtoehtoist sitoutumistapaa OX1-reseptoriin 
Interaction of adenosine A2A receptor with intracellular proteins calmodulin and α-actinin 1
Structural bioinformatics tools for the comparison and classification of protein interactions
Phylogenetic and receptor binding site analysis of coxsackievirus A9
Use of melanin binding as drug delivery strategy to the posterior eye segment_

**Comment by mirmaid** [comment]
^ Osaisiko esim. Rosa sanoa kuinka suuri osa edellisistä olisi mahdollista kuvailla termillä _proteiineihin sitoutuminen_?

**Comment by mariaforsen** [comment]
Binda sig sopisi ehkä joissakin tapauksissa, mutta on myös vähän hämärämerkityksinen termi, ehkä mieluummin förbinda sig tai förbindelse (binda sig)? Vaikea saada yksi termi joka kattaa yllä mainittu merkityskenttää ruotsiksi, joten mitään täydellistä vastinetta ei varmaan löydy. 
Ks. myös https://termipankki.fi/tepa/fi/haku/sitoutua
https://svenska.se/so/?id=106877&pz=5 "binda sig=oåterkalleligt förplikta sig"
https://svenska.se/tre/?sok=f%C3%B6rbinda+sig&pz=1 "förbinda sig=ge bindande löfte om viss handling eller dylikt"

**Comment by FinMeSHienPaimentaja** [comment]
> ^ Osaisiko esim. Rosa sanoa kuinka suuri osa edellisistä olisi mahdollista kuvailla termillä _proteiineihin sitoutuminen_?

Noista em. esimerkeistä mielestäni kahteen sopisi "proteiineihin sitoutuminen", kolmeen ei sovi, kahdeksan on sellaisia, joista ei voi sanoa suoralta kädeltä tarkemmin lukematta, mistä on kyse (proteiinien interaktiot ei ole välttämättä sama kuin proteiinien sitoutuminen; reseptori-jutuissa voi olla myös olennaisempaa jonkin sortin viestintä solu- ja molekyylitasolla kuin varsinainen proteiineihin sitoutuminen sinänsä; vaikka reseptorit ovatkin/olisivatkin proteiineja, sitoutumisissa reseptorien sokeriosat tms. ovat kuitenkin aika usein olennaisimpia). 

Kallistuisin sille kannalle, että olisi tarpeen myös pelkkä "sitoutuminen" biokemiaan '(ja kemiaan) liittyen. Olen joskus saanut asiasanoittaessa harmaita hiuksia miettiessäni, onko kyseessä nimenomaan proteiineihin sitoutuminen vai ensisijaisesti jotain muuta (sitoutumista) eli onko oikein vai väärin käyttää "proteiineihin sitoutuminen".

**Comment by FinMeSHienPaimentaja** [comment]
Vertailun vuoksi ei tosin näytä MeSH:eissäkään olevan kaipaamaani "sitoutuminen" termiä. Alla termit, jotka haettu merkkijonolla "*sitout":

+  Albumin-Bound Paclitaxel  albumiiniin sitoutunut paklitakseli
+  Binding Sites  sitoutumispaikat
+  Binding Sites, Antibody  vasta-aineiden sitoutumispaikat
+  Binding, Competitive  kilpaileva sitoutuminen
+  Complement Fixation Tests  komplementinsitoutumiskokeet
+  Dentin-Bonding Agents  hammasluuhun sitoutuvat aineet
+  Diazepam Binding Inhibitor  diatsepaamin sitoutumisen estäjä
+  GPI-Linked Proteins  GPI:hin sitoutuvat proteiinit
+  Heparin-binding EGF-like Growth Factor  hepariinia sitova EGF:n kaltainen kasvutekijä
+  Inducible T-Cell Co-Stimulator Ligand  T-soluja indusoivaan kostimulaattoriin sitoutuva ligandi
+  Internal Ribosome Entry Sites  sisäiset ribosomien sitoutumiskohdat
+  Lipid Droplet Associated Proteins  lipidipisaroihin sitoutuneet proteiinit
+  Lipid-Linked Proteins  lipideihin sitoutuneet proteiinit
+  Medication Adherence  lääkitykseen sitoutuminen
+  Origin Recognition Complex  DNA:n replikaation aloituskohdan tunnistava proteiinikompleksi
+  Protein Binding  proteiineihin sitoutuminen
+  Regulatory Factor X Transcription Factors  säätelytekijä X:ään sitoutuvat transkriptiotekijät
+  RNA Cap-Binding Proteins  mRNA:n 5'-päähän sitoutuvat proteiinit
+  Treatment Adherence and Compliance  hoitoon sitoutuminen ja hoitomyöntyväisyys
+  Work Engagement  työhön sitoutuminen

**Comment by YSO-kokous** [comment]
**PÄÄTÖS**
Etsitään kuvaillun aineiston perusteella soveltuva tarkenne yhteisöön, toimintaan, jne. sitoutumiselle.
Kemiallisessa merkityksessä:  sitoutuminen (kemia)  KT sitoutuminen (biokemia), sitoutuminen (lääkkeet)

**Comment by jarmosaarikko** [comment]
https://fi.wiktionary.org/wiki/sitoutuminen
vakaumuksellinen paneutuminen johonkin asiaan, usein myös suullisen tai kirjallisen sitoumuksen tekeminen
Vaikeiden asioiden loppuunviemien edellyttää sitoutumista.

**Comment by mirmaid** [comment]
100 ensimmäistä viitettä: ihmisen tai organisaation sitoutuminen hoitoon, ihmissuhteeseen, työpaikkaan, joukkueeseen, brändiin, johonkin toimintaan, sopimuksen noudattamiseen.

Eli tarkenne, joka kattaa nämä, mutta poissulkee kemian.

**Comment by mariaforsen** [comment]
Ja ruotsiksi laitetaan jokin mahdollisimman vastaava (vaikkakin luonnoton) termi, esim. "förbinda sig  (personer tms.)"?

**Comment by mirmaid** [comment]
^ Mitä ilmaisua ruotsiksi luontevasti käytettäisiin hoitoon sitoutumisesta tai työhön sitoutumisesta? Varmaan näitä ilmiöitä kuitenkin tutkitaan kielestä riippumatta?

Ihmiset/henkilöt tarkenteena poissulkisi organisaatiotyyppiset toimijat, esim. valtioiden sitoutuminen kansainvälisten sopimusten noudattamiseen.

**Comment by ilona-x** [comment]
termejä muista sanastoista:

TSR:
organisaatioon sitoutuminen
henkilöstön sitoutuminen

FinMeSH:
lääkitykseen sitoutuminen
hoitoon sitoutuminen ja hoitomyöntyväisyys
työhön sitoutuminen

**Comment by mariaforsen** [comment]
Ruotsiksi käytetään vastaavissa tapauksissa esim. förbinda sig, engagera sig, åta sig, förplikta sig. Meshissä -följsamhet.

**Comment by mirmaid** [comment]
Sitoutuminen (toiminta)?

**Comment by mariaforsen** [comment]
Onko siinä silti riski että käytetään myös 3. merkityksestä: https://www.kielitoimistonsanakirja.fi/#/sitoutua?searchMode=all ? Jos sekin voidaan nähdä jonkinlaisena toimintana?

**Comment by mirmaid** [comment]
^ Varmaan pieni. Mutta ilman tarkennettakin tätä väärää käyttöä on hyvin hyvin vähän, ja jos vaihtoehtoina on sitoutuminen (toiminta) ja sitoutuminen (kemia), voisi ajatella että sen jälkeen on vielä entistä vähemmän. Ei ole kuitenkaan kovin luontevaa ajatella, että jokin aine tai vaikka esimerkissä mainittu pääoma suorittaisi toimintaa.

**Comment by mirmaid** [comment]
Ehdotukseni on siis _sitoutuminen (toiminta)_, vaikka pieni riski virheelliseen käyttöön jääkin. Tämän parempaa ei nyt irtoa...

**Comment by mariaforsen** [comment]
Ja tarkoitus oli kattaa nämä? :
1.ryhtyä jnk aatteen, pol. ryhmittymän tms. aktiiviseksi kannattajaksi
2.antaa sitoumus, lupautua t. luvata sitovasti. 
Ruotsiksi on tosiaan useita termejä, riippuen asiayhteydestä, mutta (för)binda sig olisi varmaan vaihtoehdoista neutraalein.

**Comment by mirmaid** [comment]
^ No varmaan aina ei kysymys ole mistään muodollisesta sitoumuksen antamisesta, esim. jos potilas sitoutuu hoitoon, niin hän suhtautuu siihen vakavasti eikä esim. skippaa kontrollikäyntejä tai jätä lääkkeitä ottamatta. Ja sitoutua voi paitsi ihminen, myös organisaatiotoimija, esim. tyyliin _valtiot sitoutuivat noudattamaan ilmastosopimuksen päästövähennysvaatimuksia_.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään sulkutarkenne _sitoutuminen (toiminta)_.

**Comment by mariaforsen** [comment]
Sv.  förbinda sig HT binda sig
