### ISSUE TITLE
romantiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7417]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[romantiikka](http://www.yso.fi/onto/ysa/Y101311) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaanko romanttisuus/romantiikka myös toisessa merkityksessä? 

#### Perustelut ehdotukselle   

MOT Gummerus Uusi suomen kielen sanakirja:
1 taiteessa ja kirjallisuudessa suuntaus, joka korostaa muodon asemesta sisältöä, mm. tunnetta, mielikuvitusta, outoja paikkoja ja aikoja, uskonnollisuutta ja kansallistunnetta
2 romanttisuus, romanttinen asenne, unelmointi, hempeä tunnelmallisuus, ihanteet, tunneperäinen rakkaus"

Allärs: romantiken ("kulturströmning som genomsyrade västerländskt tänkande och skapande från slutet av 1700-talet till mitten av 1800-talet") Mahtaako olla paras mahdollinen vastaavuus.. Toisaalta, onko suomeksi tarpeeksi selkeä?

**Comment by AuHo22** [comment]
Voisi miettiä, haluaisiko suuntausta kuvata vastaavalla tavalla kuin valistusta: valistuksen aika -> romantiikan aika - kattokäsite, jonka lisäksi on jo olemassa selkeät varhais-, myöhäis-, kansallis- ja uusromantiikka YSO-sanoina. Tämä voisi selkeyttää ainakin ykköskohtaa. Vieläkin selkeämpää ja yleisempää tuntuu olevan viittaus romantiikan aikakauteen -> romantiikan aikakausi

**Comment by YSA-kokous** [comment]
Todettiin, että termin tarkentaminen tarpeen. Ehdolla olisivat ainakin: _romantiikka (tyylit) / romantiikka (taiteet) / romantiikka (suuntaukset) / romantiikan aika_
Päätetään seuraavassa kokouksessa.

**Comment by mariaforsen** [comment]
Tämä on jäänyt vielä päättämättä. 
https://github.com/NatLibFi/Finto-data/issues/929

Näyttää siltä että lähinnä romantiikka (suuntaukset) olisi tarpeeksi laaja tarkenne (Melindassa). Romantiikan aika ei käy kaikille Melinda-viitteille. 

Tosiaan jonkin verran aineistoa myös toisesta merkityksestä...

**Comment by tpalonen** [comment]
Kannatan muotoa romantiikka (suuntaukset). Sopii paremmin kuin (tyylit) esim. näihin:
- Unohdettu ihmisyys : ihmisen kehityksen edellytyksiä ja ilmentymiä historiassa François Guizot’n sivilisaatioajattelussa vuosilta 1828-1829 / Meri Fager
- Transplanting the metaphysical organ : German Romanticism between Leibniz and Marx / Leif Weatherby.

Ja paremmin kuin romantiikan aika esim. näihin:
- Rock and romanticism : post-punk, goth, and metal as dark romanticisms / James Rovira, editor.
- Mishima Yukion kirjallisuuskäsitys: dialogi Nihon rōmanhan kanssa. / Rajala, Terttu,

Jos sanastoon otetaan rakkaussuhteisiin tms viittaava käsite niin voisiko käytettävä termi olla _romanttisuus_? Vrt. pari poimintaa romantiikan Melinda-kuvailusta:
- Love around us : the role of love in education, parenting and romantic relationships / Kaarina Määttä & Satu Uusiautti (eds.)
- Osmo Kontula: Mielen seksuaalisuus: matka kiihottumisen alkulähteille

**Comment by mirmaid** [comment]
Melindassa yli 3000 viitettä, ensimmäisten sadan joukossa (melko nopeasti selattuna) ehkä viisi, joiden voisi melko varmasti sanoa käsittelevän romantiikkaa rakkaussuhteessa (tai sen fiktiivisessä kuvauksessa). Onko tarkenteen lisäämisestä kovasti hyötyä, kun takautuva korjaaminen näyttää melko mahdottomalta? 

_Suuntaukset_-tarkenne on hyvin salliva, eihän se ole liian salliva?

**Comment by AuHo22** [comment]
Itse en kaunokirjallisuuden kuvailunkaan yhteydessä ole tarvinnut romanttisuus-termiä. On ikäänkuin luonteenpiirre yo. merkityksessä? Romanssit (ihmissuhteet) on olemassa, samoin ihastus ja muita tunteet ST termejä sekä haaveet KÄ unelmat / toiveet jne.

Kannatan romantiikan aika / romantiikka (suuntaukset) jälkimmäinen historiallisessa merkityksessä. Romantiikka ei rajoittunut ainoastaan taiteeseen, sen takia tyylit-tarkenne ei välttämättä ole paras, esim. Jenan romantiikka. Kyse on myös laajemmasta aatehistoriallisesta virtauksesta, johon liittyi taiteilijoiden lisäksi ajattelijoita, myös vallankumouksellisuutta, kansallismielisyyttä  jne.
Pushkinin koottuihin olisin toivonut voivani käyttää romantiikan aika -käsitettä, koskapa oli romantiikan ajan runoilija, mutta tuotannossaan rakensi jo siltaa realismiin. Useinkin taiteilijat ehtivät tuotannossaan uusiutua, joskin toisaalta on sitten tiettyä suuntauksia esitteleviä kuvataidenäyttelyjä.

**Comment by YSO-kokous** [comment]
Lisätään käsitteelle ohjaustermiksi romantiikan aika, romantiikka (taide) ja romantiikka (tyylit). Säilytetään käytettävä termi ilman sulkutarkennetta. Ei oteta uutta käsitettä romanttisuus-merkityksessä. Hyvin vähän käytetty tässä merkityksessä.
