### ISSUE TITLE
orkideat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7420]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[orkideat](http://www.yso.fi/onto/ysa/Y108694) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selvennys termin merkitykseen. 

#### Perustelut ehdotukselle   

Mihin tällä termillä viitataan? Onko tämä tieteellisesti täsmällinen termi ja mikä latinankielinen vastine sillä on? Sanastossa myös kämmekkäkasvit. 
Ruotsiksi "orkideer (tropiska växter)", joka viittaisi siihen että tällä haetaan niitä orkideoita mitä voi kaupasta ostaa jne. Melindakäyttö ei aina täsmää. 
Ks. myös https://fi.wikipedia.org/wiki/K%C3%A4mmekk%C3%A4kasvit

**Comment by mirmaid** [comment]
Eli pitäisikö lisätä _orkideat (koristekasvit)_, orkideat (kämmekkäkasvit) KÄ kämmekkäkasvit? Käytetty Melindassa yli 300 kertaa.

**Comment by ilona-x** [comment]
LCSH: Orchids KT Orchidaceae linkattu YSOssa nyt orkideoihin (engl. Orchids) eikä kämmekkäkasveihin (engl. Orchidaceae), pitäisikö vaihtaa? http://id.loc.gov/authorities/subjects/sh85095334

**Comment by ilona-x** [comment]
eli orkideat (koristekasvit) viittaisi esim. perhoskämmeköihin? https://fi.wikipedia.org/wiki/Perhosk%C3%A4mmek%C3%A4t

**Comment by PaiviLipsanen** [comment]
Trooppisia, usein koristekasveinakin viljeltyjä kämmekkäkasveja kutsutaan myös orkideoiksi. 
https://fi.wikipedia.org/wiki/K%C3%A4mmekk%C3%A4kasvit

kämmekkäkasvit
ALAKÄSITE orkideat (koristekasvit)?

**Comment by YSA-kokous** [comment]
orkideat (koristekasvit)
