### ISSUE TITLE
äänimaisema

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7423]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänimaisema](http://www.yso.fi/onto/ysa/Y108842) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muusa on ehdottanut termiä lisättäväksi SLM-sanastoon monikossa, https://www.kiwi.fi/pages/viewpage.action?pageId=91754306. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Muusa

**Comment by mirmaid** [comment]
SLM-työryhmä toivoo esimerkkejä aineistoista, joiden kuvailussa tätä lajityyppitermiä on tarvittu.

**Comment by jtuohini** [comment]
Esimerkiksi

- https://finna.fi/Record/kirkes.431578
- https://finna.fi/Record/satakirjastot.35086

**Comment by MUUSA-kokous** [comment]
Esimerkit OK.

**Comment by mirmaid** [comment]
Sanastossa on _taustamusiikki_ ja _rentoutusmusiikki_. Tulisiko tämä kaikille luonnonääniä sisältäville äänitteille? Kumpaan esim. temppelikellot ja yhdistelmät?
https://www.amazon.com/Japanese-Soundscapes-Meditation-Lifestyle-Restorative/dp/B06X9NFB4T
https://www.amazon.com/Japanese-Temple-Bells-Fire-Offerings/dp/B00ADELCHI/ref=sr_1_1?dchild=1&keywords=japanese+temple+bells&qid=1586845693&s=dmusic&sr=1-1
https://www.amazon.com/Piano-Sea-Classics-Blended-Natural/dp/B0757B9JWW/ref=sr_1_1?dchild=1&keywords=sea+sounds+piano&qid=1586845752&s=dmusic&sr=1-1

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Ljudlandskap

**Comment by AuHo22** [comment]
Muusan muistiossa näköjään tällä hetkellä äänimaisemille sama vastine LC:ssä kuin ympäristömusiikille SLM:ssä - ovatko nämä kaksi samaa vai kuinka eri asiaa? 
YSO pelkkä soundscape(s)

Soundscapes (Music) (en)
Library of Congress Genre/Form Terms

**Comment by mirmaid** [comment]
Selvitettävä suhde ympäristömusiikkiin, radiofoniaan ja äänitaiteeseen. Jos kaikki ovat eri käsitteitä, tarvitaan määritelmät. 
Lisäksi tarvittaisiin termi linnunlaulua tms. luonnonääniä sisältäville äänitteille. 
Myös suhde rentoutus- ja taustamusiikkiin olisi hyvä selkeyttää.

**Comment by tpalonen** [comment]
Ongelma koskenee enemmän SLM:ää kuin YSOa? Äänitejulkaisuihin en ota kantaa, mutta näin yleiskielen näkökulmasta äänimaisemalla on suhteellisen selkeä merkitysero muihin mainittuihin käsitteisiin ja sen olemassaololla ainakin YSOssa on täten peruste. Äänimaisema on määritelty Wikipediassa mielestäni aika hyvin: "melun, musiikin, luonnon äänten, ihmisen tai teknologian äänten kokonaisuus, jossa kulloinkin olemme". Äänimaiseman käsite määrittyy siis enemmän vastaanottajan näkökulmasta ts. koettuna. Äänitaiteessa ja ympäristömusiikissa korostuu enemmän tarkoituksellisuus ja tuottajan/esittäjän näkökulma. Äänimaisema voi syntyä a) luonnollisesti tai jonkin toiminnan sivutuotteena tai olla b) (ainakin suurelta osin) tietoisen työn tulosta. Ensimmäinen merkitys tulee lähelle melua ja luonnonääniä, jälkimmäinen merkitys tulee lähelle äänitaidetta ja ympäristömusiikkia, mutta vaikka äänet olisi tietoisesti tuotettu (esim. yleisö keskustelee, yleisö aplodeeraa) niin tarkoituksena ei kuitenkaan ole välttämättä tuottaa taidetta tai musiikkia.

Luulisin, että käsitteiden eroja selventävät määritelmät olisi suhteellisen helppo tuottaa.
YSOssa on jo luonnonäänet ja eläinten äänet. Sopisivatko nämä myös SLM:ään? Lintujen äänet lienee tosin äänitepuolella yleisempi kuin muut eläinten äänet. Omasta levyhyllystäni kylläkin löytyy esim. neuvostoliittolainen kalojen ääniä sisältävä äänilevy.

**Comment by tpalonen** [comment]
YSOn käsitteen huomautus siirrettiin määritelmäksi pienin muutoksin. Lisättiin ryhmä 89 musiikki. Tiedoksi @mariaforsen

**Comment by MUUSA-kokous** [comment]
Suhde rentoutus- ja taustamusiikkiin on enintään assosiatiivinen.
Esillä olevien käsitteiden määritelmät voidaan ottaa YSOsta myös SLM:ään.
Tehdään SLM-ehdotus käsitteille luonnonäänet ja eläinten äänet.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
YSOn määritelmä: _"Se, miten ääniympäristöä ymmärretään, tulkitaan ja tuotetaan."_ Tämä ei kyllä mielestäni kovin hyvin sovellu kuvaamaan äänitallennetta. 

Huom. myös Aulin kommentti edellä, LCGFT-vastine ei varmaankaan voi olla sama kuin ympäristömusiikilla, jos tarkoittavat eri asioita. Ympäristömusiikin määritelmä YSOssa: _Tietyssä tilassa soimaan sävelletty teos. Ympäristömusiikkiin voidaan liittää musiikin lisäksi myös muita ääniä, visuaalisuutta ja multimediaa._ LCSH-vastine on Sound sculpture, mutta termiä ei ole LCGFT:ssä.

LCSH:ssa on myös Soundscapes (Music), se ei ole äänimaiseman vastine YSOssa, mutta vaikuttaakin rajatummalta.

Eli Muusa ei kannata äänimaisemat-termille mitään suhteita toisiin termeihin SLM:ssä?

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa määritelmän pitämistä ennallaan YSOssa.
Ehdotetaan YSO-käsitteelle sulkutarkennetta _(ilmiöt)_.
Ehdotetaan YSOon uutta käsitettä _äänimaisemateokset_ ja SLM:n äänimaisemat-käsite muutettavaksi muotoon _äänimaisemateokset_.

**Comment by mirmaid** [comment]
Toivotaan Muusalta määritelmää, joka rajaisi äänimaisemat suhteessa edellä mainittuihin likeisiiin käsitteisiin.

**Comment by AuHo22** [comment]
https://muhi.uniarts.fi/1900_aanimaisema/

**Comment by jaskaj** [comment]
Ehdotuksia määritelmiksi Muusan sanastokokoukseen 26.3.2021:

**äänimaisema (YSO)**
https://finto.fi/yso/fi/page/p1715

Vanha määritelmä:
Se, miten ääniympäristöä ymmärretään, tulkitaan ja tuotetaan.

Uusi määritelmä:
Kuunteluun perustuva sosiokulttuurinen käsitys ääniympäristöstä.


**äänimaisemateokset (YSO, SLM)**

Ehdotus määritelmäksi:
Luonnollisen tai keinotekoisesti tuotetun äänimaiseman pohjalta luodut musiikkiteokset.

LCSH: http://id.loc.gov/authorities/subjects/sh2002011301
Soundscapes (Music)
Here are entered musical compositions that consist of natural or synthetic sounds from specific locations, sometimes manipulated electronically.

LCGFT: http://id.loc.gov/authorities/genreForms/gf2014027107
Soundscapes (Music)
Musical compositions that consist of natural or synthetic sounds from specific locations that are sometimes manipulated electronically.


**ympäristömusiikki (YSO, SLM)**
https://finto.fi/yso/fi/page/p30116
https://finto.fi/slm/fi/page/s689

Vanha määritelmä:
Tietyssä tilassa soimaan sävelletty teos. Ympäristömusiikkiin voidaan liittää musiikin lisäksi myös muita ääniä, visuaalisuutta ja multimediaa.

Uusi määritelmä:
Tietyssä paikassa soimaan sävelletty musiikkiteos.

Huom! SLM-termillä nyt siltaus LCGFT-termiin Soundscapes (music): http://id.loc.gov/authorities/genreForms/gf2014027107

**Comment by AuHo22** [comment]
äänimaisemateokset (YSO, SLM) -> slm-terminä äänimaisemateokset varmastikin ihan ok, mutta yso-termiksi sopisi paremmin äänimaisemataide? vrt. esim. oopperat/oopperataide

**Comment by MUUSA-kokous** [comment]
**äänimaisema**: Muokattu määritelmäehdotus:  "Kuunteluun perustuva käsitys ääniympäristöstä".
RT äänimaisemateokset
Muusa ei kannata muotoa "äänimaisemataide".

**äänimaisemateokset** 
LT musiikki
RT äänimaisema

**ympäristömusiikki**
LT musiikki
RT taustamusiikki

Muut määritelmäehdotukset OK.

**Comment by mirmaid** [comment]
Ympäristömusiikki: lisätään määritelmä. Otetaan sanastoon äänimaisemateokset ehdotetulla määritelmällä.

**Comment by mirmaid** [comment]
Tuleeko RT-suhteita äänimaisema/-teokset RT ympäristömusiikki, radiofonia, taustamusiikki, rentoutusmusiikki, äänitaide, luonnonäänet (sen mukaan mitä kummassakin sanastossa on)?

Otetaanko LCGFT-linkitys pois ympäristömusiikilta, vai onko se näiden molempien closeMatch?

**Comment by mariaforsen** [comment]
Sv. soundscapeverk HT soundscape, soundscape-verk, ljudlandskap (verk)

**Comment by MUUSA-kokous** [comment]
RT-suhteiden lisääminen OK.

Ei poisteta LCGFT-linkitystä.

_äänimaisemat_ on edelleen SLM:ssä. Pitäisi kai poistaa.

**Comment by mirmaid** [comment]
Muutetaanko _äänimaiseman_ määritelmä YSOssa?

Muusan ehdotus edellä: "Kuunteluun perustuva käsitys ääniympäristöstä".

Nyt: Se, miten ääniympäristöä ymmärretään, tulkitaan ja tuotetaan.

**Comment by mirmaid** [comment]
Ilmeisesti tarkoitus lisätä myös YSOon äänimaisemateokset? Ks. Jaskan ja Muusan kommentit edellä. YSOssa nyt vain äänimaisema.

SLM: http://urn.fi/URN:NBN:fi:au:slm:s1440

**Comment by mirmaid** [comment]
_Ympäristömusiikin_ määritelmän muutos YSOssa? Ks. edellä

Eli SLM nyt: Tietyssä paikassa soimaan sävelletty musiikkiteos.

YSO nyt: Tietyssä tilassa soimaan sävelletty teos. Ympäristömusiikkiin voidaan liittää musiikin lisäksi myös muita ääniä, visuaalisuutta ja multimediaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään. Yhdistetään Muusan määritelmä ja nykyinen määritelmä. 

Otetaan _äänimaisemateokset_ uutena käsitteenä. 

Muutetaan _ympäristömusiikin_ määritelmä Muusan mukaiseksi.

**Comment by mariaforsen** [comment]
Sv. soundscapeverk HT ljudlandskap (verk), soundscape, soundscape-verk 
https://finto.fi/slm/fi/page/s1440?clang=sv
