### ISSUE TITLE
äänitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7424]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[äänitteet](http://www.yso.fi/onto/ysa/Y100515) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muusa on ehdottanut termiä lisättäväksi SLM-sanastoon, https://www.kiwi.fi/pages/viewpage.action?pageId=91754306. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Muusa

**Comment by mirmaid** [comment]
Ehdotus: _LISÄTÄÄN (2018), kirjataan, että käytetään vain ääritapauksessa_

**Comment by mirmaid** [comment]
Yllä ehdotettu käyttöhuomautus ei välttämättä rajaisi toivotulla tavalla.

**Comment by MUUSA-kokous** [comment]
Käyttöhuomautus: "Käytetään vain, jos soveltuvaa täsmällisempää termiä ei ole käytettävissä".

**Comment by mirmaid** [comment]
Seuraava kokous.

**Comment by mariaforsen** [comment]
Äänitteiden alakäsitteet YSOssa ovat:
[albumit (äänitteet)](https://finto.fi/yso/fi/page/p37733) 
[bootlegit](https://finto.fi/yso/fi/page/p29924)
[CD-äänilevyt](https://finto.fi/yso/fi/page/p17543)
[EP:t](https://finto.fi/yso/fi/page/p29782)
[historialliset äänitykset](https://finto.fi/yso/fi/page/p29983)
[liveäänitteet](https://finto.fi/yso/fi/page/p38517) SLM:ssä
[singlet](https://finto.fi/yso/fi/page/p29941)
[studioäänitteet](https://finto.fi/yso/fi/page/p39014) SLM:ssä
[äänikasetit](https://finto.fi/yso/fi/page/p12688)
[äänikirjat](https://finto.fi/yso/fi/page/p25071) SLM:ssä
[äänilehdet](https://finto.fi/yso/fi/page/p15836) SLM:ssä
[äänilevyt](https://finto.fi/yso/fi/page/p17544)

SLM:ssä ei siis hirveästi ole näitä, onko tarkoitus vielä ottaa jotain tarkempia äänite-tyyppejä, vai onko tarkoitus että kaikista muista käytetään "äänitteet"?

**Comment by mirmaid** [comment]
Hyväksytty /SLM.
ST yllämainitut 4 + kenttätallenteet, säestykset, Muusan ehdottama käyttöhuomautus, LCGFT Sound recordings.

**Comment by mirmaid** [comment]
Säestykset, liveäänitteet nyt LT musiikki, vaihdetaanko vai molemmat? Onko hierarkian idea musiikin osalta, että aina kuvaillaan joko äänitettä tai nuottijulkaisua, ja tämän alle tulevat ne, jotka voivat olla vain äänitteitä, ne, jotka voivat olla molempia ovat musiikin alla?

**Comment by mariaforsen** [comment]
Sv. ljudupptagningar (ei lisätä tarkennetta, kuten YSOssa, koska SLM:ssä ei ole sekaannuksen vaaraa)

**Comment by MUUSA-kokous** [comment]
säestykset
LT musiikki
LT äänitteet

liveäänitteet
LT äänitteet

**Comment by mirmaid** [comment]
^ Hierarkiapohdintaa varten huomio, tässäkin siis on kai kysymys monihierarkiasta, jos säestys voi olla äänite, mutta ei välttämättä ole (vaikka se olisikin aina musiikkia).
