### ISSUE TITLE
tanssilaulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7426]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssilaulut](http://www.yso.fi/onto/ysa/Y206818) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu myös SLM-sanastoon / KULA 

#### Perustelut ehdotukselle   

-

**Comment by mariaforsen** [comment]
Sv. danssånger/låtar

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT kansanlaulut
