### ISSUE TITLE
valituslaulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7427]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valituslaulut](http://www.yso.fi/onto/ysa/Y206831) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu myös SLM-sanastoon / KULA 

#### Perustelut ehdotukselle   

-

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT kansanlaulut
ST itkut

**Comment by jtuohini** [comment]
Mikä olisi suhde SLM-termiin [**lamentaatiot**](http://urn.fi/URN:NBN:fi:au:slm:s361), arvatttavasti LT–ST?

**Comment by mirmaid** [comment]
lamentaatiot LT valituslaulut (myös YSO)
