### ISSUE TITLE
faktorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7433]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[faktorit](http://www.yso.fi/onto/ysa/Y109347) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitseeko tarkenteen? 

#### Perustelut ehdotukselle   

27 viitettä Melindassa, 2 kertaa käytetty virheellisesti. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
faktorit: 2. _kirjapainon t. latomon tekninen johtaja._

**Comment by mirmaid** [comment]
https://melinda.kansalliskirjasto.fi/byid/013787262
https://melinda.kansalliskirjasto.fi/byid/002053056

**Comment by LeKorsu** [comment]
Ruotsinkielisessä on tarkenne (yrken)

**Comment by YSA-kokous** [comment]
faktorit (ammatit)
