### ISSUE TITLE
zikavirusinfektio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7435]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

zikavirusinfektio 

#### Ehdotettu termi ruotsiksi   

zikavirusinfektion 

#### Ehdotettu termi englanniksi   

Zika Virus Infection 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tartuntataudit](http://www.yso.fi/onto/yso/p1804) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D000071243> 
LCSH : <http://id.loc.gov/authorities/subjects/sh2016001078> 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Emergence of dengue and Zika virus 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [zikavirusinfektio](http://finto.fi/yse/fi/page/Y507435)

**Comment by mariaforsen** [comment]
Sv.  zikavirusinfektion ET zikafeber
