### ISSUE TITLE
infektiotaudit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7436]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[infektiotaudit](http://www.yso.fi/onto/ysa/Y121070) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

infektiotaudit KÄYTÄ tartuntataudit? 

#### Perustelut ehdotukselle   

FinMeSHissä infektiotaudit KÄYTÄ tartuntataudit, jonka yläkäsitteenä on infektio (KT tartunta KT infektiot)
http://www.yso.fi/onto/mesh/D003141
YSOssa infektiotaudit ST tartuntataudit 
ja YSOssa lisäksi infektiot (KT infektio KT tartunta) http://www.yso.fi/onto/yso/p7316

https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00569

https://fi.wikipedia.org/wiki/Tartuntatauti 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSA-kokous** [comment]
KÄ tartuntataudit

**Comment by mariaforsen** [comment]
Sv. ANV smittsamma sjukdomar
