### ISSUE TITLE
primitivismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7437]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[primitivismi](http://www.yso.fi/onto/ysa/Y152662) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitseeko tarkenteen, jotta käytetään vain taiteesta? 

#### Perustelut ehdotukselle   

Melinda-käyttö, esim. https://melinda.kansalliskirjasto.fi/byid/013160964 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
LCSH-linkit nyt sekä Primitivism, että Primitivism in art ja Primitivism in literature.

https://fi.wikipedia.org/wiki/Primitivismi
https://fi.wikipedia.org/wiki/Anarkoprimitivismi

**Comment by AuHo22** [comment]
Vrt. minimalismi (elämäntapa) ja minimalismi taiteen alalla? Pitäisikö tehdä ero samalla tavalla? Nykyisin enemmän teoksia elämäntavasta kuin taiteen alasta, mutta vain yksi termi.

**Comment by mariaforsen** [comment]
Sv. primitivism (stilar), viittaa muuten helposti muuhunkin, mutta toistaalta onko aivan tarpeen erotella jokaisen aihealueen mukaan? Ks. https://sv.wikipedia.org/wiki/Primitivism Käytetään ainakin ruotsiksi monella alueella, esim. psykologiassa, pedagogiikassa, patologiassa, filosofiassa, taiteessa, kirjallisuudessa jne.

**Comment by YSA-kokous** [comment]
Lisätään ryhmäksi 50. Ei muita muutoksia.

**Comment by mariaforsen** [comment]
Eli tämä tarkoittaa että eng. ja sv. termit pitäisi muuttaa: primitivism (art) >> primitivism, primitivism (stilar) >> primitivism ?
