### ISSUE TITLE
julkisuuden henkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7438]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[julkisuuden henkilöt](http://www.yso.fi/onto/ysa/Y109342) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT julkiset henkilöt 

#### Perustelut ehdotukselle   

Käytetty Melindassa

**Comment by mirmaid** [comment]
Eduskunnan kirjaston mukaan ok.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
