### ISSUE TITLE
propaganda

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7439]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[propaganda](http://www.yso.fi/onto/ysa/Y103409) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT propagandaelokuvat 

#### Perustelut ehdotukselle   

On olemassa oleva genre, ks. esim. Wikipedia ja SAO genre

**Comment by YSA-kokous** [comment]
Ei ohjaustermiksi.
