### ISSUE TITLE
Viipurinlahden taistelu (1944)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7440]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Viipurinlahden taistelu (1944) 

#### Perustelut ehdotukselle   

2 viitettä Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Viipurinlahden taistelu (1944)](http://finto.fi/yse/fi/page/Y507440)

**Comment by AuHo22** [comment]
Heräsi kysymys että kannattaisiko samalla ottaa Viipurinlahden taistelu (1940), jota voidaan kohta kuitenkin kysäistä ja näin helpottaa kuvailutyötä?
https://fi.wikipedia.org/wiki/Viipurinlahden_taistelu_(1940)

**Comment by mariaforsen** [comment]
Sv. slaget vid Viborgska viken (1944)
