### ISSUE TITLE
lääkintämiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7441]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lääkintämiehet 

#### Perustelut ehdotukselle   

kirjaston sisällökuvailutarve 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

lääkintämiehen sotamuistelmat 

**Ehdottajan organisaatio:** Lapuan kaup. kirjasto **Termiehdotus Fintossa:** [lääkintämiehet](http://finto.fi/yse/fi/page/Y507441)

**Comment by ilona-x** [comment]
SOTOssa http://www.yso.fi/onto/soto/p2012
https://fi.wikipedia.org/wiki/L%C3%A4%C3%A4kint%C3%A4mies

Melinda x 5

**Comment by mariaforsen** [comment]
Sv. sjukvårdsmän ET sjukvårdssoldater, sanitärer 
https://varusmies.fi/sv/tjanstgoringsuppgifter-och-platser/-/services/16
https://www.sprakinstitutet.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/2007/barberare_brandsoldater_och_sanitarer

**Comment by LeKorsu** [comment]
Mietin löytyisikö sukupuolineutraalimpaa termiä, kun myös naiset voivat kouluttautua lääkintämiehiksi, mutta lääkintämies näyttää oleva puolustusvoimien käyttämä myös tänä päivänä
https://varusmies.fi/palvelustehtavat-ja-paikat/-/services/16
