### ISSUE TITLE
tiloroni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7443]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tiloroni 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D013994> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Inhalable antifibrotic compounds - Development of a formulation method and formulation of antifibrotic small molecule tilorone as inhalable dry powder 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tiloroni](http://finto.fi/yse/fi/page/Y507443)

**Comment by mariaforsen** [comment]
Sv. tiloron
