### ISSUE TITLE
sytokromi P-450 -entsyymijärjestelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7444]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sytokromi P-450 -entsyymijärjestelmä 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D003577> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/014426087 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sytokromi P-450 -entsyymijärjestelmä](http://finto.fi/yse/fi/page/Y507444)

**Comment by mariaforsen** [comment]
Sv. cytokrom P450-enzymsystemet ET cytokrom P-450
