### ISSUE TITLE
kallonsisäinen sinustromboosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7445]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kallonsisäinen sinustromboosi 

#### Ehdotettu termi englanniksi   

Sinus Thrombosis, Intracranial 

#### Ehdotettu termi ruotsiksi   

Sinustrombos, intrakraniell 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aivoverenkiertohäiriöt](http://www.yso.fi/onto/yso/p1710) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D012851> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cerebral venous thrombosis : clinical characteristics and factors affecting outcome 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kallonsisäinen sinustromboosi](http://finto.fi/yse/fi/page/Y507445)

**Comment by mariaforsen** [comment]
Entä sinustromboosi? 
Sv. sinustrombos

**Comment by mirmaid** [comment]
Oma suosikkini on kovakalvon veriviemärien hyytymätukos :frowning:

**Comment by YSA-kokous** [comment]
Sinustromboosi
