### ISSUE TITLE
Laitilan kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7446]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Laitilan kirkko 

#### Vaihtoehtoiset termit ja ilmaisut   

Pyhän Mikaelin kirkko (Laitila) 
Laitilan Pyhän Mikaelin kirkko 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tukiainen / Laitilan kirkot kuvissa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Laitilan kirkko](http://finto.fi/yse/fi/page/Y507446)

**Comment by mariaforsen** [comment]
Sv. Letala kyrka et St. Mikaels kyrka (Letala)
