### ISSUE TITLE
Keminmaan vanha kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7447]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Keminmaan vanha kirkko 

#### Vaihtoehtoiset termit ja ilmaisut   

Pyhän Mikaelin kirkko (Keminmaa) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kemin maaseurakunta : Pyhän Mikaelin kirkko 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Keminmaan vanha kirkko](http://finto.fi/yse/fi/page/Y507447)

**Comment by mariaforsen** [comment]
Sv. Keminmaa gamla kyrka ET Heliga Mikaels kyrka (Keminmaa), St. Mikaels kyrka (Keminmaa)
