### ISSUE TITLE
turvallisuuspoliisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7449]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[turvallisuuspoliisi](http://www.yso.fi/onto/ysa/Y109714) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan päätermiksi suojelupoliisi. 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Suojelupoliisi 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
**turvallisuuspoliisi:** _useissa maissa valtiollisesta turvallisuudesta huolehtiva poliisiorganisaatio._
**suojelupoliisi:** _poliisiorganisaation osa, jonka tehtävänä on lähinnä paljastaa valtakunnan itsenäisyyttä t. laillista yhteiskuntajärjestystä vastaan kohdistuvat hankkeet._

**Comment by mirmaid** [comment]
_Suojelupoliisi_ on auktorisoitu myös yhteisönä.

**Comment by LeKorsu** [comment]
En kannata, turvallisuuspoliisi on parempi yleiskäsitteenä, Suojelupoliisi riittää yhteisöterminä.

**Comment by AuHo22** [comment]
Yhteisötermeinä myös KGB, NKVD, CIA ja Stasi

**Comment by YSA-kokous** [comment]
Ei muutosta.
