### ISSUE TITLE
Kaustisen moukarikarnevaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7450]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kaustisen moukarikarnevaalit 

#### Vaihtoehtoiset termit ja ilmaisut   

Moukarikarnevaalit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[liikuntatapahtumat](http://www.yso.fi/onto/yso/p1963) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

20 karnevaalivuotta Kaustisella 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Tarkoitusta täsmentävä selite   

http://team.jopox.fi/moukarikarnevaalit/ 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Kaustisen moukarikarnevaalit](http://finto.fi/yse/fi/page/Y507450)

**Comment by mariaforsen** [comment]
Sv. Släggkarnevalen i Kaustby
