### ISSUE TITLE
orkesterimuusikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7453]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[orkesterimuusikot](http://www.yso.fi/onto/ysa/Y506102) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde nykyistä täsmällisemmäksi: "muusikot" --> "soittajat" 

#### Perustelut ehdotukselle   

Kaikki orkesterimuusikot ovat soittajia, eivät laulajia, joten hierarkkisesti oikeampi LT-suhde on "soittajat" 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by mirmaid** [comment]
Korjattu.
