### ISSUE TITLE
säeromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7454]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

säeromaanit 

#### Ehdotettu termi englanniksi   

verse novel 

#### Vaihtoehtoiset termit ja ilmaisut   

jaeromaani? 

#### Tarkoitusta täsmentävä selite   

Sarjallinen kokonaisuus, jossa yksittäiset runot ja säkeet luovat fragmentaarista tarinallisuutta.. runouden ja proosan piirteitä yhdistelevä teos. 
 Proosamaisten, kertovien runojen yhdistämä tarinakokonaisuus. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirsti Kuronen: Merikki (2019), Kirsti Kuronen: Pönttö (2017), Sarah Cross: Yksi (2018) 

#### Perustelut ehdotukselle   

Kirjan kyseistä ominaispiirrettä ei voi kuvailla muutoin 

**Termiehdotus Fintossa:** [säeromaanit](http://finto.fi/yse/fi/page/Y507454)

**Comment by AuHo22** [comment]
SLM-ehdotus siis tämä

**Comment by mirmaid** [comment]
Onko erotettavissa _runoromaanista_? [Tämän sivun](http://marjatankirjat.blogspot.com/2018/08/saekirja-mika-se-on.html) mukaan englanniksi _verse novel_, https://en.wikipedia.org/wiki/Verse_novel.

**Comment by AuHo22** [comment]
https://ingridsundberg.com/2011/06/05/exploring-the-verse-novel/
https://fontanalib.wordpress.com/2018/04/25/the-rise-of-the-verse-novel-celebrating-national-poetry-month/

**Comment by mariaforsen** [comment]
http://www.janolehti.fi/no8/kirsti-kuronen.htm
https://agnesbokblogg.blogspot.com/2021/04/prosalyrik.html
http://umu.diva-portal.org/smash/get/diva2:1756535/FULLTEXT01.pdf
Ruotsiksi käytetty myös "prosalyrik", mutta ei vastaa samalla tavalla (on todella vanha kirjallisuuden muoto)
