### ISSUE TITLE
kromatiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7455]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kromatiikka](http://www.yso.fi/onto/ysa/Y214534) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmä kaipaa hienosäätöä. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Yläkäsite on ominaisuudet, mutta määritelmä: "Diatoniseen, kokosävelaskelista ja kahdesta puolisävelaskeleesta muodostettuun asteikkoon kuulumattomien, mutta siitä johdettujen, kromaattisten sävelten **käyttäminen** musiikillisen ilmaisun jännitteistämiseksi ja värittämiseksi.

**Comment by tpalonen** [comment]
Mitenkäs olisi?

"Diatoniseen, kokosävelaskelista ja kahdesta puolisävelaskeleesta muodostettuun asteikkoon kuulumattomien, mutta siitä johdettujen, kromaattisten sävelten **esiintyminen musiikissa** ilmaisun jännitteistämiseksi ja värittämiseksi."

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa määritelmäehdotusta.

**Comment by YSA-kokous** [comment]
Hyväksytään em. määritelmän muutosehdotus.
