### ISSUE TITLE
SLM Perhe-elokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7456]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM Perhe-elokuvat 

#### Ehdotettu termi ruotsiksi   

familjefilmer 

#### Perustelut ehdotukselle   

Tarvitaan erikseen termi näille koko perheen elokuville, joihin pelkkä lastenelokuvat tuntuu liian suppealta, kun ajatuksena on, että näitä voi katsoa koko perhe. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Yksin kotona elokuvat ovat tällaisia ja uudemmista esimerkkeinä monet piirretyt esim. Leijonakuningas. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [SLM Perhe-elokuvat](http://finto.fi/yse/fi/page/Y507456)

**Comment by jtuohini** [comment]
Miten ehdotettu termi suhtautuisi kohderyhmäkenttään 385? Tulisiko siis aina
385 __ |m Muu |n soc |a lapsiperheet |2 yso/fin
655 _7 |a perhe-elokuvat |2 yso/fin
t.s. olisiko kyseessä aina elokuva, jonka kohderyhmä on yhdestä tai useammasta vanhemmasta ja yhdestä tai useammasta lapsesta koostuva perhe? (Mielestäni ei, mutta tämä siis hajahuomioksi.)

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa perhe-elokuvat, ohjaustermiksi koko perheen elokuvat. RT lastenelokuvat.
