### ISSUE TITLE
nuorisotyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7458]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nuorisotyö](http://www.yso.fi/onto/ysa/Y97698) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi korvattu termi: nuorisotoiminta (tai mahdollisesti uutena omana terminä)
SV: ungdomsverksamhet 

#### Perustelut ehdotukselle   

käytetty Melindassa

**Comment by tpalonen** [comment]
JUHOssa nuorisotyö ja nuorisotoiminta erikseen.

**Comment by YSA-kokous** [comment]
Seuraava kokous. Ei sovellu ohjaustermiksi.

**Comment by mirmaid** [comment]
Melindassa 48 kertaa lähinnä artikkeliaineistossa. Toisinaan käytetty _nuorisotyö_-merkityksessä, yleisimmin urheiluseurojen nuorisotoiminnasta - usein unohtunut asiasana _nuoret_ :worried:.

**Comment by YSO-kokous** [comment]
Ei hyväksytä ehdotusta.
