### ISSUE TITLE
omaelämäkerrallinen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#746]
#### Ehdotettu termi suomeksi

omaelämäkerrallinen kirjallisuus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[87 Kirjallisuus](http://www.yso.fi/onto/ysa/ryhma_87)

**Luontipäivämäärä:** 04.03.2002

**Muokkauspäivämäärä:** 6.4.2005, 30.4.2003, 4.3.2002, 16.12.2008

**Voyager-id:** 118020

**Termiehdotus Fintossa:** [omaelämäkerrallinen kirjallisuus](http://finto.fi/yse/fi/page/Y318020)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5439 - jääkö tämä ehdotus?

Viime kokouksessa päätettiin tehdä viittaus omaelämäkerralliset romaanit KÄ autofiktio.

**Comment by mariaforsen** [comment]
Sv. självbiografisk litteratur, memoarlitteratur

**Comment by YSA-kokous** [comment]
KÄ-viittaukset
