### ISSUE TITLE
vuosiloma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7460]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vuosiloma](http://www.yso.fi/onto/ysa/Y100318) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korvattu termi kesäloma tarvitaan erillisenä terminä 

#### Perustelut ehdotukselle   

On eri käsite kuin työelämässä esiintyvä vuosiloma (=työntekijälle työstä vuosittain annettava palkallinen loma /kielitoimiston sanakirja) Sama ongelma ruotsiksi. Koululaisilla ei ole palkallista lomaa, eikä heidän lomiin muutenkaan sovelleta samankaltaisia ehtoja. Koululaisten lomasta ei myöskään, luonnollisesti, käytetä termiä vuosiloma/semester. Tällä hetkellä ei ole mahdollista hakea erikseen aineistoa esim. koululaisten kesälomien pituudesta jne.

**Comment by ilona-x** [comment]
YSO:ssa on jo loma http://www.yso.fi/onto/yso/p9882 ja lisäksi lomailu & kesänvietto
Melinda: koululaiset + loma = 31 viitettä

**Comment by AuHo22** [comment]
Jos otetaan, niin sitten varmaan tarvittaisiin syysloma ja talvilomakin omina termeinään?

**Comment by YSA-kokous** [comment]
kesäloma KÄ loma

**Comment by mariaforsen** [comment]
Varmaan myös joululoma, syysloma KÄYTÄ loma?

**Comment by mirmaid** [comment]
Lisätty ehdotetut.
