### ISSUE TITLE
kuluttajakäyttäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7461]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuluttajakäyttäytyminen](http://www.yso.fi/onto/ysa/Y96511) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT ostoskäyttäytyminen (tai uutena erillisenä terminä)
SV: köpbeteende 

#### Perustelut ehdotukselle   

Käytetty Melindassa

**Comment by mirmaid** [comment]
Lisätty myös _ostokäyttäytyminen_.
