### ISSUE TITLE
maailmankuva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7462]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maailmankuva](http://www.yso.fi/onto/ysa/Y97139) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT maailmankäsitys 

#### Perustelut ehdotukselle   

Tarvitaan haussa. Ks. MOT

**Comment by tpalonen** [comment]
Wikipediassa maailmankäsitys on redirect-termi (so. ohjaustermi) Maailmankuva-artikkeliin.
