### ISSUE TITLE
suolat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7463]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suolat](http://www.yso.fi/onto/ysa/Y104436) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korvattu termi natriumkloridi? 

#### Perustelut ehdotukselle   

Käytetään myös terminä, varsinkin kemian alalla

**Comment by ilona-x** [comment]
YSOssa nyt suolat-käsitteen alakäsitteenä esim. kloridit, joka olisi ilmeisesti natriumkloridin yläkäsite

https://github.com/Finto-ehdotus/YSE/issues/7196
