### ISSUE TITLE
tansanialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7464]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tansanialaiset 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden 

#### Perustelut ehdotukselle   

Puuttuu Afrikan kansallisuuksista. 

**Termiehdotus Fintossa:** [tansanialaiset](http://finto.fi/yse/fi/page/Y507464)

**Comment by mariaforsen** [comment]
Sv. tanzanier
