### ISSUE TITLE
postcrossing

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7466]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

postcrossing 

#### Tarkoitusta täsmentävä selite   

Harrastuksen idea on: "lähetä postikortti ja vastaanota postikortti takaisin satunnaiselta henkilöltä jossain päin maailmaa!"
Sen jäsenet, tunnetaan myös nimellä postcrossers, lähettävät postikortteja muille jäsenille ja vastaanottavat postikortteja takaisin muilta satunnaisilta jäseniltä. Mistä postikortit tulevat, on aina yllätys. 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [postcrossing](http://finto.fi/yse/fi/page/Y507466)

**Comment by AuHo22** [comment]
YSOssa myös bookcrossing ja kiertokirjeet
