### ISSUE TITLE
ulkustauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7468]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ulkustauti](http://www.yso.fi/onto/ysa/Y106109) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT peptinen haava
tai peptinen haava päätermiksi

ja lisäksi mahahaavan ja pohjukaissuolihaavan voisi siirtää tämän alakäsitteiksi, nyt RT-suhde 

#### Perustelut ehdotukselle   

FinMeSH: 
peptinen haava KT ulkustauti 
ST mahahaava 
ST pohjukaissuolen haava 
http://www.yso.fi/onto/mesh/D010437 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
ja vielä yksi ST ulkustaudille: refluksitauti, jonka LT on nyt ruoansulatuselinten taudit

**Comment by mariaforsen** [comment]
Sv. ulkussjukdom > peptiskt sår ET peptiskt ulkus
