### ISSUE TITLE
markkinoinnin suunnittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7470]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[markkinoinnin suunnittelu](http://www.yso.fi/onto/ysa/Y506469) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT markkinointi/markkinastrategiat (tai mahdollisesti uutena erillisenä terminä)? 
SV marknads(förings)strategier? 

#### Perustelut ehdotukselle   

Käytetty Melindassa

**Comment by mirmaid** [comment]
_Markkinointistrategiat_ käytetty 26 kertaa Melindassa (_markkinoinnin suunnittelu_ 95 kertaa, vain kerran samassa tietueessa). _Yritysstrategiat_ ja _markkintointi_ 882 kertaa samassa tietueessa, _strategiat_ ja _markkinointi_ 1672, _strategiat_ ja _markkinoinnin suunnittelu_ 17.

**Comment by mariaforsen** [comment]
Olisiko sitten syytä ottaa uutena?

**Comment by YSA-kokous** [comment]
Ei hyväksytty ehdotusta. Perusteena sille, että ei oteta uutta käsitettä on aiemmat kuvailukäytännöt eli _markkinointi_ ja _strategiat_ käsitteiden yhteiskäytön yleisyys. Markkinointistrategian nähtiin viittaavan eri asiaan kuin markkinoinnin suunnittelun ja siksi ei hyväksytty ohjaustermiksi.
