### ISSUE TITLE
funktionalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7472]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[funktionalismi](http://www.yso.fi/onto/ysa/Y95189) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ohjaustermeiksi "funkkis" ja "funkis" 

#### Perustelut ehdotukselle   

yleisesti käytössä olevat termit käsitteelle. Kielitoimiston sanakirja: "funkis39 (rinn. funkkis)
1. funktionalismi." 

#### Ehdottajan organisaatio   

KK

**Comment by krinay** [comment]
Jos funktionalismilla tarkoitetaan tässä vain arkkitehtuurin ja taideteollisuuden tyyliä, pitäisikö poistaa ryhmä 56 Tiede. Tutkimus? Tai jakaa käsite kahdeksi?

Termiä funktionalismi on käytetty myös esimerkiksi antropologian tutkimussuuntauksesesta. (YSAssa sillä ei ole LT- tai muita suhteita). Ks. esim.
https://helka.finna.fi/Record/helka.385895
https://helka.finna.fi/Record/helka.1005583

**Comment by tpalonen** [comment]
Varovainen peukku (littipeukku?) käsitteen jakamiselle. Tosin Wikipediakin osoittaa, että termiä on käytetty monella alalla: https://en.wikipedia.org/wiki/Functionalism

**Comment by YSA-kokous** [comment]
Ohjaustermit hyväksytty.

**Comment by AuHo22** [comment]
#4648 
aiempi keskustelu asiasta

**Comment by YSO-kokous** [comment]
Käsiteltiin YSO-kokouksessa, mutta ei nähty tarvetta muutoksille jo aiemmin päätettyyn.
