### ISSUE TITLE
terveyspalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7473]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[terveyspalvelut](http://www.yso.fi/onto/ysa/Y99446) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT terveydenhuoltopalvelut 

#### Perustelut ehdotukselle   

Käytetty synonymi.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

Keskusteltiin myös mahdollisesta ohjaustermistä terveydenhoitopalvelut, tätä ei hyväksytty.
