### ISSUE TITLE
ruutuaika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7475]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruutuaika 

#### Ehdotettu termi ruotsiksi   

skärmtid 

#### Ehdotettu termi englanniksi   

screen time 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. Termi on jo hyväksytty KAUNO-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kamenetz, Anya: Sopiva ruutuaika 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [ruutuaika](http://finto.fi/yse/fi/page/Y507475)

**Comment by mariaforsen** [comment]
Sv. skärmtid https://sv.wikipedia.org/wiki/Sk%C3%A4rmtid

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
