### ISSUE TITLE
säeromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7476]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

säeromaanit 

#### Ehdotettu termi englanniksi   

novels in verse 

#### Vastaava käsite muussa sanastossa   

verse novel : https://en.wikipedia.org/wiki/Verse_novel 
novels in verse : <http://id.loc.gov/authorities/subjects/sh2002009675.html> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Yksi / Sarah Crossan, Merikki / Kirsti Kuronen 

#### Perustelut ehdotukselle   

Etenkin nuortenkirjallisuudessa nousussa oleva kirjallisuuden lajityyppi. Ehdotus koskee SLM-sanastoa. Hesarin juttu genrestä: https://www.hs.fi/kulttuuri/art-2000005677376.html 

#### Tarkoitusta täsmentävä selite   

Säeromaanissa teksti jaetaan säkeisiin runon tapaan. Kirjoittajan fokus on jäntevässä kerronnassa, mutta ilman perinteisen nuortenromaanin juonivetoisuutta. Sisäiset tapahtumat ja mielenliikkeet ovat keskiössä. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [säeromaanit](http://finto.fi/yse/fi/page/Y507476)

**Comment by mirmaid** [comment]
YSOssa ja SLM:ssä on termit _runoromaanit_ ja _proosarunot_, joista tämä genre pitäisi pystyä erottamaan.

Itselläni lainassa juuri _One_, joten katsotaan :slightly_smiling_face:

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7454

**Comment by marjutpu** [comment]
Välitän Kauno-ryhmäläisen kommentin: Runoromaanit ja proosarunot ovat yleensä kielellisesti kokeilevaa, haastavaksi miellettyä aikuisten kaunokirjallisuutta. Ensin mainitussa on nähdäkseni kyse kertomuksen rakenteen ottavasta, kielellisesti runon tavoin etenevästä tekstistä. Esimerkkejä: Maria Matinmikko - Kolkka, Maaria Päivinen: Silja ja Mai. Proosarunoteos taas on selkeämmin yksittäisiä runoja, jotka on sijoiteltu eri sivuille ja tekstin asettelu on proosamainen. Säeromaani taas on pääasiassa nuortenkirjallisuuden alalaji, joka on helppolukuisempi ja sisältää vähemmän kielellisiä kokeiluja kuin runoromaani tai proosaruno.

**Comment by mirmaid** [comment]
KÄ runoromaanit? Seuraava kokous.

**Comment by mirmaid** [comment]
https://ingridsundberg.com/2011/06/05/exploring-the-verse-novel/
https://fontanalib.wordpress.com/2018/04/25/the-rise-of-the-verse-novel-celebrating-national-poetry-month/

**Comment by mariaforsen** [comment]
Sv. ? diktromaner?

**Comment by YSA-kokous** [comment]
Vaikuttaa päällekkäiseltä runoromaanien kanssa. Hyväksytään ohjaustermiksi runoromaaneille eli:
säeromaanit KÄYTÄ runoromaanit.
