### ISSUE TITLE
elämänhistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7478]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elämänhistoria](http://www.yso.fi/onto/ysa/Y116065) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ryhmä 50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi. 

#### Perustelut ehdotukselle   

Käsite on tärkeä folkloristisen tutkimuksen kannalta. Ks. 
http://tieteentermipankki.fi/wiki/Folkloristiikka:el%C3%A4m%C3%A4nhistoria.

(YSAn huomautus "Tarkoittaa historiantutkimuksen osa-aluetta" ei ole folkloristiikan näkökulmasta osuva, mutta YSOssa huomautusta ei olekaan.) 

#### Ehdottajan organisaatio   

SKS:n kirjasto

**Comment by mariaforsen** [comment]
On muutenkin käytetty laajemmin kuin YSAn huomautus, eli hyvä ettei ole YSOssa.

**Comment by YSA-kokous** [comment]
Lisätään ryhmä 50.
