### ISSUE TITLE
katusoittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7479]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[katusoittajat](http://www.yso.fi/onto/ysa/Y156773) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "katumuusikot". 

#### Perustelut ehdotukselle   

"Katumuusikot" pitää sisällään sekä katusoittajat että -laulajat ja kattaisi kuvailussa kummatkin; ks. Muusan päätös koskien YSE-ehdotusta https://github.com/Finto-ehdotus/YSE/issues/7056 

#### Ehdottajan organisaatio   

Musiikin metatiedon asiantuntijaryhmä

**Comment by YSA-kokous** [comment]
Hyväksytään muutos. Käytettäväksi termiksi katumuusikot. Ohjaustermeiksi katusoittajat JA katulaulajat.
