### ISSUE TITLE
suunnistuskartat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7480]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suunnistuskartat 

#### Ehdotettu termi englanniksi   

orienteering maps 

#### Ehdotettu termi ruotsiksi   

orienteringskartor 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Suunnistusta varten laaditut kartat. Tarvitaan sekä yso- että slm-termiksi. 

#### Perustelut ehdotukselle   

Suunnistuskartat eroavat esimerkiksi tavallisista maastokartoista tarkempina ja yksityiskohtaisempina. Ks: https://fi.wikipedia.org/wiki/Suunnistus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

$aSuunnistuskartta :$bSuolijärvi Tampere : 1:7500 / 5 m.$pKiintorastit 2019. 

**Termiehdotus Fintossa:** [suunnistuskartat](http://finto.fi/yse/fi/page/Y507480)

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
