### ISSUE TITLE
slm/fin legot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7481]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

slm/fin legot 

#### Ehdotettu termi ruotsiksi   

slm/swe legobitar 

#### Ehdotettu yläkäsite YSOssa (LT)   

[leikkikalut](http://www.yso.fi/onto/yso/p8148) 

#### Assosiatiiviset (RT)   

[rakennuspalikat](http://www.yso.fi/onto/yso/p12163) 

#### Perustelut ehdotukselle   

Tarvitaan slm-termiksi. Kyseessä moniviestin, johon liittyy lego-osuus. Pelit ja palapelit ei käy. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

LEGO Harry Potter. Rakenna oma seikkailu. ISBN 978-952-321-897-0 

**Ehdottajan organisaatio:** Kirjastopalvelu

**Comment by AnneliRe** [comment]
Liian hätäinen tämä ehdotukseni, voi poistaa.
