### ISSUE TITLE
tietopalvelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7482]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietopalvelu](http://www.yso.fi/onto/ysa/Y99528) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

englanninkieliseksi termiksi myös reference work 

#### Perustelut ehdotukselle   

Käytin Ysoa etsiessäni englanninkielistä termiä tietopalvelulle ja hakiessani lähteitä information services -termillä, huomasin vasta pitkän ajan kuluttua, että monissa aiheeseen liittyvissä tutkimuksissa käytetään termiä reference work.

**Comment by mirmaid** [comment]
Varmaankin tarkenteella varustettuna, esim. _reference work (information service)_. Reference works voisi olla ohjaustermi _reference books_ -käsitteelle.

**Comment by YSA-kokous** [comment]
Hyväksytään Mirjan ehdottamat.
