### ISSUE TITLE
aritmetiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7483]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[aritmetiikka](http://www.yso.fi/onto/ysa/Y100811) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "laskento" 

#### Perustelut ehdotukselle   

Aritmetiikasta on Suomessa käytetty myös nimitystä laskento [https://www.kielitoimistonsanakirja.fi/laskento], joten se olisi hyvä saada asiasanan KT-muodoksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: vanh. _alkeisaritmetiikka koulujen oppiaineena_.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
