### ISSUE TITLE
rohingyat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7484]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rohingyat 

#### Ehdotettu termi ruotsiksi   

rohingyer 

#### Ehdotettu termi englanniksi   

Rohingya people 

#### Vaihtoehtoiset termit ja ilmaisut   

rohingat 
 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh98003834> 
Wikidata : <http://www.wikidata.org/entity/Q464529> 
Wikipedia : Rohingya people 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston mukaan sekä 'rohingyat' että 'rohingat' ovat hyväksyttäviä muotoja. Käytännössä ensimmäinen lienee käytetympi. http://www.kielitoimistonohjepankki.fi/ohje/705 

#### Perustelut ehdotukselle   

Tästä vainotusta kansanryhmästä on uutisoitu paljon jo parin vuoden ajan. Aiheesta ilmestynee lähitulevaisuudessa myös lisääntyvässä määrin kirjallisuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/016576027 

**Ehdottajan organisaatio:** Turun kaupunginkirjasto **Termiehdotus Fintossa:** [rohingyat](http://finto.fi/yse/fi/page/Y507484)

**Comment by jtuohini** [comment]
Kielitoimiston ehdotuksessakin viitatun ohjepankin tekstin lukemisen perusteella kannattaisin mieluummin "suomalaisempaa" muotoa; kirjastot ovat erinomaisessa asemassa voidessaan pyrkiä suosimaan suomen kieleen mahdollisimman hyvin istuvia muotoja erilaisten sitaattilainojen sijaan.

**Comment by mirmaid** [comment]
Melindassa 3 kertaa rohingyat, 4 kertaa rohingat, Google 15300/1850.

https://fi.wikipedia.org/wiki/Rohingyat

**Comment by YSA-kokous** [comment]
Otetaan muodossa rohingat, ohjaustermiksi rohingyat. Käytettävä termimuoto äänestettiin.
