### ISSUE TITLE
wolofin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7486]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

wolofin kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781507801178 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [wolofin kieli](http://finto.fi/yse/fi/page/Y507486)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Wolofin_kieli
http://lexvo.org/id/iso639-3/wol

**Comment by mariaforsen** [comment]
Sv. wolof (språk)
