### ISSUE TITLE
šonan kieli (shonan)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7487]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

šonan kieli (shonan) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781500423131 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [šonan kieli (shonan)](http://finto.fi/yse/fi/page/Y507487)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/%C5%A0onan_kieli
http://finto.fi/lexvo/fi/page/sna

**Comment by mariaforsen** [comment]
Sv. shona (språk)
