### ISSUE TITLE
vain kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7488]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vain kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781092219617 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [vain kieli](http://finto.fi/yse/fi/page/Y507488)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Vain_kieli
http://finto.fi/lexvo/fi/page/vai

**Comment by mariaforsen** [comment]
Sv. vai (språk)
