### ISSUE TITLE
igbon kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7489]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

igbon kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781495414220 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjato **Termiehdotus Fintossa:** [igbon kieli](http://finto.fi/yse/fi/page/Y507489)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Igbon_kieli
http://finto.fi/lexvo/fi/page/ibo

**Comment by tpalonen** [comment]
Suosittaisin suomenkieliseksi käytettäväksi termiksi igbon kieli ja ohjaustermiksi ibon kieli. Suomessa toimii mm. Ndi-Igbo community in Finland (NCF) /Ndi-Igbo Yhdyskunta Suomessa (NYS) ry. Myös Lexvossa ja suomenkielisessä Wikipediassa muodossa igbo.

**Comment by mariaforsen** [comment]
Sv. igbo (språk) ET ibo (språk)
