### ISSUE TITLE
bemban kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7490]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bemban kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781717533227 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [bemban kieli](http://finto.fi/yse/fi/page/Y507490)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Bemba
http://finto.fi/lexvo/fi/page/bem

**Comment by mariaforsen** [comment]
Sv. bemba (språk)
