### ISSUE TITLE
luwo tai jur kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7491]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luwo tai jur kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781494824396 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [luwo tai jur kieli](http://finto.fi/yse/fi/page/Y507491)

**Comment by mirmaid** [comment]
http://lexvo.org/id/iso639-3/lwo
https://en.wikipedia.org/wiki/Jur_language
LCSH: Lwo language http://id.loc.gov/authorities/subjects/sh85079066

https://www.amazon.com/Luwo-Childrens-Dictionary-Luwo-English-English-Luwo/dp/1494824396

**Comment by mirmaid** [comment]
Suomeksi luwon kieli (?) (kerran Melindassa tässä muodossa)

**Comment by tpalonen** [comment]
Tässä pitää olla tarkkana, etteivät mene kielet ja kansat sekaisin esim. linkityksen suhteen. Jos ymmärsin oikein, Wikipedian mukaan luwo-kieltä puhuu luo-kansa. Luwo-kansa taas ei puhu luwon kieltä, vaan he puhuvat luo-kieltä eli dhulo-kieltä eli lwo-kieltä. Luwo-kielestä käytetään myös muotoja jur ja luo. Ja tämän lisäksi Kamerunissa on puhuttu vielä kieltä, jonka nimi on myös luo, mutta sillä ei ole näiden kahden em. kanssa tekemistä.

**Comment by mariaforsen** [comment]
Eli mistä kielestä on nyt kysymys, ei tämä? https://fi.wikipedia.org/wiki/Luon_kieli

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa luwon kieli.

**Comment by mariaforsen** [comment]
Mikä kielikoodi siis tällä kielellä on? Että tiedetään mihin tämä "luwon kieli" (ei juuri googlessa) viittaa ja käännetään oikein. 

Sv. luo (språk)? /SAO

**Comment by mirmaid** [comment]
lwo http://lexvo.org/id/iso639-3/lwo
