### ISSUE TITLE
njandžan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7492]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

njandžan kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781511759922 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [njandžan kieli](http://finto.fi/yse/fi/page/Y507492)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Njand%C5%BEan_kieli
http://finto.fi/lexvo/fi/page/nya

**Comment by mariaforsen** [comment]
Sv. chinyanja (språk) ET chewa, chichewa, nyanja (språk)
