### ISSUE TITLE
gan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7493]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gan kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781482007756 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [gan kieli](http://finto.fi/yse/fi/page/Y507493)

**Comment by mariaforsen** [comment]
Sv. ga (språk) ET gã (språk), ga-adangme (språk)
