### ISSUE TITLE
fulanin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7494]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fulanin kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781792826979 

#### Perustelut ehdotukselle   

Aineistoa on. 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [fulanin kieli](http://finto.fi/yse/fi/page/Y507494)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Fulani
http://finto.fi/lexvo/fi/page/ful

**Comment by mariaforsen** [comment]
Sv. fulani (språk) ET fula (språk), fulbe (språk), fulfulde (språk), peul (språk)
