### ISSUE TITLE
mridangam

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7495]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mridangam 

#### Ehdotettu termi ruotsiksi   

mridangam 

#### Ehdotettu termi englanniksi   

mridanga 

#### Vaihtoehtoiset termit ja ilmaisut   

khol 
mirdang 
pakhawaj 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lyömäsoittimet](http://www.yso.fi/onto/yso/p441) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85088214> 
Wikidata : https://www.wikidata.org/wiki/Q744831 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2317785 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [mridangam](http://finto.fi/yse/fi/page/Y507495)

**Comment by mariaforsen** [comment]
Sv. mrdanga ET mridangam, mridanga, mrudangam, khol

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

Myös SEKOon.

**Comment by YSA-kokous** [comment]
Käsite hyväksytään sanastoon.
