### ISSUE TITLE
ilmastokasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7496]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmastokasvatus 

#### Perustelut ehdotukselle   

Käytössä kasvatusalalla 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [ilmastokasvatus](http://finto.fi/yse/fi/page/Y507496)

**Comment by mirmaid** [comment]
Kerran Melindassa; Google > 4000

https://openilmasto-opas.fi/ilmastokasvatus/

**Comment by mariaforsen** [comment]
Sv. klimatfostran ET klimatpedagogik
https://lararensklimatguide.fi/?s=klimatfostran

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus. LT ympäristökasvatus?
