### ISSUE TITLE
rapsodiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7497]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rapsodiat](http://www.yso.fi/onto/ysa/Y104138) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon ja lisätään sille sekä YSOssa että SLM:ssä RT-suhde termeihin "balladit (soitinmusiikki)" ja "sinfoniset runot" 

#### Perustelut ehdotukselle   

"With the orchestral ballade in particular, the distinction between the ballade and its related forms, the rhapsody and the symphonic poem, appears slight." [https://www.oxfordmusiconline.com/grovemusic/view/10.1093/gmo/9781561592630.001.0001/omo-9781561592630-e-0000001885?rskey=pF0gCp] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Rapsodiat on jo SLM-sanastossa http://urn.fi/URN:NBN:fi:au:slm:s489
