### ISSUE TITLE
sokraattinen menetelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7498]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sokraattinen menetelmä 

#### Ehdotettu termi englanniksi   

socratic method 

#### Vaihtoehtoiset termit ja ilmaisut   

socratic dialogue 
sokraattinen metodi 
socraattinen dialogi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[filosofia](http://www.yso.fi/onto/yso/p1056) 
[psykoterapia](http://www.yso.fi/onto/yso/p2587) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 
[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Tarkoitusta täsmentävä selite   

"Sokraattinen metodi tai sokraattinen dialogi on Sokrateen käyttämä filosofinen menetelmä, jossa hän esittää kysymyksiä, joiden kautta keskustelukumppani huomaa itse oman ajattelunsa hämäryyden ja ristiriitaisuuden." http://tieteentermipankki.fi/wiki/Filosofia:sokraattinen_metodi 

#### Perustelut ehdotukselle   

Tarvittu sisällönkuvailussa. On käytetty vapaana avainsanana Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/43HDUSP7F5HCKLVYUT7MHLUJ9V4XH6VHTEFIQ1SA5UAFFP1MA1-01191?func=full-set-set&set_number=552854&set_entry=000001&format=999 

**Termiehdotus Fintossa:** [sokraattinen menetelmä](http://finto.fi/yse/fi/page/Y507498)

**Comment by mirmaid** [comment]
Melindassa 2 kertaa sokraattinen menetelmä, 3 kertaa sokraattinen metodi, kerran sokraattinen dialogi.

**Comment by mirmaid** [comment]
LCSH Socratic method > Questioning

https://fi.wikipedia.org/wiki/Sokraattinen_menetelm%C3%A4

**Comment by mariaforsen** [comment]
Sv. sokratisk metod ET sokratiska samtal, sokratisk debatt, sokratisk dialog
https://sv.wikipedia.org/wiki/Sokratisk_metod

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa sokraattinen menetelmä, ohjaustermeiksi sokraattinen metodi ja sokraattinen dialogi.
