### ISSUE TITLE
ruskea rasva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7499]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruskea rasva 

#### Ehdotettu termi ruotsiksi   

brun fettvävnad 

#### Ehdotettu termi englanniksi   

Brown adipose tissue 

#### Vaihtoehtoiset termit ja ilmaisut   

ruskea rasvakudos 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rasvakudokset](http://www.yso.fi/onto/yso/p24382) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85017245> 
FinMeSH : <http://www.yso.fi/onto/mesh/D002001> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Multimodality imaging of brown adipose tissue 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ruskea rasva](http://finto.fi/yse/fi/page/Y507499)

**Comment by mariaforsen** [comment]
Sv. brun fettvävnad ET brunt fett
