### ISSUE TITLE
palkkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7500]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[palkkaus](http://www.yso.fi/onto/ysa/Y97973) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermit:
palkkaus (palkkaaminen) & palkkaaminen KÄYTÄ työhönotto (sv. anställning, engl. hiring)

Tarvitseeko termi palkkaus tarkenteen, esim. palkkaus (palkkataso)? Käytetty jonkinverran väärin Melindassa esim. http://melinda.kansalliskirjasto.fi/byid/009336814 

#### Perustelut ehdotukselle   

palkkaus
1. palkkaaminen.
2. palkka, palkat. Taulukon mukaan määräytyvä palkkaus. 

JUPOSSA palkkaaminen (sv. anställning, engl. hiring) http://www.yso.fi/onto/jupo/p1137 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
ALLFO: avlöning=palkkaus eli liittyy joo palkkaan, ei työhönottoon. Joten nämä ohjaukset olisivat varmaan tarpeen.

**Comment by YSA-kokous** [comment]
Ëhdotetut ohjaustermit lisätään. Palkkaus-termin osalta mietitään asiaa uudelleen seuraavassa kokouksessa. Ks. myös ansiotaso.

**Comment by ilona-x** [comment]
Olisiko palkkaus mahdollisesti poistettavissa ja korvattavissa esimerkiksi termeillä palkat & ansiotaso? 

Kielitoimiston sanakirja:
palkkaus
1    palkkaaminen.
2    palkka, palkat. Taulukon mukaan määräytyvä palkkaus.

Termipankki:
https://termipankki.fi/tepa/fi/haku/palkkaus

**Comment by ilona-x** [comment]
Palkkaus-termiä käytetty Melindassa 2596 kertaa.

palkat & palkkaus x 993
ansiotaso & palkkaus x 210
ansiotaso & palkat & palkkaus x 158

**Comment by mariaforsen** [comment]
Kannatan yhdistämistä eli palkkaus KÄYTÄ palkat, ansiotaso. Myös ruotsin kannalta avlöning=palkkaus on päällekkäinen näiden kanssa, eli nykyinen tilanne on oikeastaan virheellinen.

**Comment by mirmaid** [comment]
Varmaan käytännössä siis palkkaus > palkat viitteissä, mahd. haarukoitaisiin pois rekrytointi.

**Comment by YSO-kokous** [comment]
### Päätökset
Poistetaan "palkkaus" sanastosta ja lisätään ohjaustesrmiksi palkkaus KÄYTÄ palkat, ansiotaso.

>Huom. korjattu 24.1. poistettava käsite on palkkaus eikä palkat
