### ISSUE TITLE
maailmanmestaruussarja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7501]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maailmanmestaruussarja 

#### Vaihtoehtoiset termit ja ilmaisut   

Grand Prix -sarja 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789524723039 Kohonen: MP Grand Prix : ratamoottoripyöräilyn Grand Prix -sarjan historia... 

#### Perustelut ehdotukselle   

Julkaisu kertoo noin 70 vuoden ajalta ko. moottoriurheilusarjan kilpailuista ja sarjasta. Vastaavia on esim formula1, enduron ja ralliautoilun GP-sarjat 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [maailmanmestaruussarja](http://finto.fi/yse/fi/page/Y507501)

**Comment by jtuohini** [comment]
Vastaavista vrt. esim. LCSH:n [FIA Formula One World Championship](http://id.loc.gov/authorities/names/nb2012002495) ja [Grand Prix de Monaco (Automobile race)](http://id.loc.gov/authorities/names/n2015027169), jotka on auktorisoitu Marc 21 -formaatin mukaisesti käytettäväksi X11-kentissä, ei 650-kentässä.

**Comment by mirmaid** [comment]
Ymmärrän ehdotuksen niin, että haluttaisiin kattokäsitettä erilaisille maailmanmestaruus/GP-sarjoille?

LCSHssa on yleiskäsitteinä _Grand Prix motorcycle racing_ ja _Grand Prix racing_, jälkimmäisen alakäsitteina myös eri maiden kilpailuja. YSOssa on _Formula 1 -luokka_ ja _NASCAR-sarja_.

**Comment by mariaforsen** [comment]
Jos tämä halutaan rajata autourheiluun se vaatinee tarkenteen, koska grand prix/maailmanmestaruussarja käytetään myös muissa lajeissa.

**Comment by YSA-kokous** [comment]
Hyväksytään käsite muodossa MotoGP. Ei nähty tarvetta yleiskäsitteelle maailmanmestaruussarjat.

**Comment by mariaforsen** [comment]
Sv. MotoGP ET grand prix....
https://sv.wikipedia.org/wiki/MotoGP
