### ISSUE TITLE
julkaisun laadinnan oppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7502]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[julkaisun laadinnan oppaat](http://www.yso.fi/onto/ysa/Y95653) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM:ään 

#### Perustelut ehdotukselle   

Tarvitaan Melindassa, näitä on paljon. 

#### Ehdottajan organisaatio   

ÅAB

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
Tämähän olikin jo sanastossa :slightly_smiling_face:
