### ISSUE TITLE
Flickr

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7503]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Flickr 

#### Perustelut ehdotukselle   

Flickr on valokuvien ja videoiden jakamiseen erikoistunut yhteisöpalvelusivusto
https://fi.wikipedia.org/wiki/Flickr 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The use of social media in the Finnish Parliament Elections 2011 ISBN 978-952-10-8251-1 

**Termiehdotus Fintossa:** [Flickr](http://finto.fi/yse/fi/page/Y507503)

**Comment by mirmaid** [comment]
LCSH:ssa tämä on teos (samoin Twitter, LinkedIn ja Facebook, Instagram on puolestaan yhteisö).

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mariaforsen** [comment]
Sv. Flickr
