### ISSUE TITLE
pohjavesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7504]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pohjavesi](http://www.yso.fi/onto/ysa/Y98154) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT pohjavedet 

#### Perustelut ehdotukselle   

Käytetty Melindassa monta kertaa

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

Lisätään myös ohjaustermi:
pintavedet KÄYTÄ pintavesi
