### ISSUE TITLE
filmatisointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7505]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[filmatisointi](http://www.yso.fi/onto/ysa/Y107091) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCSH-asiasanaan "Film adaptations" [http://id.loc.gov/authorities/subjects/sh85048224] 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSA-kokous** [comment]
YSO-ryhmä pohtii tätä.
