### ISSUE TITLE
narkomaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7506]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[narkomaanit](http://www.yso.fi/onto/ysa/Y101714) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ohjaustermiksi myös huumeiden käyttäjät? 

#### Perustelut ehdotukselle   

FinMeSH: huumeiden käyttäjät KT narkomaanit
http://www.yso.fi/onto/mesh/D055030 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
