### ISSUE TITLE
Somalian sisällissota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7507]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Somalian sisällissota 

#### Ehdotettu termi englanniksi   

Somali Civil War 

#### Ehdotettu termi ruotsiksi   

Inbördeskriget i Somalia 

#### Vaihtoehtoiset termit ja ilmaisut   

Somalian sota 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Somalian_sota_2006%E2%80%93
https://fi.wikipedia.org/wiki/Somalian_sis%C3%A4llissota 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Haweenka! :Naiset Somalian sodassa ja rauhassa ISBN 978-952-67816-1-7 

**Termiehdotus Fintossa:** [Somalian sisällissota](http://finto.fi/yse/fi/page/Y507507)

**Comment by mirmaid** [comment]
Somalian sisällissota KT Somalian sota (?)

**Comment by mariaforsen** [comment]
Sv. inbördeskriget i Somalia ET somaliska inbördeskriget

**Comment by YSA-kokous** [comment]
Hyväksytään ohjaustermiksi:
Somalian sota KÄYTÄ Somalian sisällissota
