### ISSUE TITLE
Chișinău

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7509]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Chișinău](http://www.yso.fi/onto/ysa/Y234821) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään entinen nimi skos:altLabel  "Kishinev@fi" 

#### Perustelut ehdotukselle   

käytetty Melindassa yli 30 kertaa 

#### Ehdottajan organisaatio   

Kansalliskirjasto/Finto/js

**Comment by mirmaid** [comment]
Lisätty.
