### ISSUE TITLE
pitkätsiimat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#751]
#### Ehdotettu termi suomeksi

pitkätsiimat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[23 Erätalous. Kalastus. Metsästys](http://www.yso.fi/onto/ysa/ryhma_23)
#### Lähde

Lähde: Kalatalousalan asiasanasto

**Luontipäivämäärä:** 04.03.2002

**Muokkauspäivämäärä:** 4.3.2002, 16.12.2008

**Voyager-id:** 118036

**Termiehdotus Fintossa:** [pitkätsiimat](http://finto.fi/yse/fi/page/Y318036)

**Comment by henriyli** [comment]
Otettu YSAan 27.5.2013: http://www.yso.fi/onto/ysa/Y192910
