### ISSUE TITLE
forensinen lingvistiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7511]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

forensinen lingvistiikka 

#### Ehdotettu termi englanniksi   

Forensic linguistics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kielitiede](http://www.yso.fi/onto/yso/p1631) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kielestä kiinni  9789525940572 

#### Perustelut ehdotukselle   

Oma kielentutkimuksensa laji, mikä keskittyy rikostutkintaan. Termin luoja Jan Svartvik (1986). 

**Ehdottajan organisaatio:** Kirjastopalvelu, OH **Termiehdotus Fintossa:** [forensinen lingvistiikka](http://finto.fi/yse/fi/page/Y507511)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Forensinen_kielentutkimus

Huom. YSOssa oikeuslingvistiikka, joka linkattu LCSH Forensic linguistics 
http://www.yso.fi/onto/yso/p20638

"Kielentutkimuksessa puhutaan forensisesta lingvistiikasta, koska termi oikeuslingvistiikka on vakiintunut muunlaiseen käyttöön. Oikeuslingvistisestä tutkimuksesta tulee forensista lingvistiikkaa, kun tutkimusta käytetään esitutkinnassa tai tuomioistuimessa." Lähde: https://www.kielikello.fi/-/verbaaliset-sormenjaljet-kielentutkimus-huijausten-ja-rikosten-tutkinnassa

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Oikeuslingvistiikka

Forensinen lingvistiikka on soveltavan kielitieteen haara, joka voidaan lukea osaksi oikeuslingvistiikkaa tai sen lähialaksi. http://tieteentermipankki.fi/wiki/Oikeustiede:oikeuslingvistiikka

https://en.wikipedia.org/wiki/Forensic_linguistics

**Comment by mariaforsen** [comment]
https://www.sprakbruk.fi/-/verbala-fingeravtryck-lingvistisk-sakkunskap-i-brottsutredningar
" Sådant arbete kallas rättslingvistik eller forensisk lingvistik."
Myös tämän mukaan se olisi sama asia: https://docplayer.se/5384966-Rattslingvistik-_-lingvistik-i-juridikens-tjanst-institutionen-for-lingvistik-och-filologi-vt-2004.html
Ja tässä http://www.hittaskola.se/index.php/BrowseSchoolProgram/index/696714/44492
Todella monessa sivussa se käsitellään samana asiana. Kieliero?

**Comment by YSA-kokous** [comment]
Varsin päällekkäinen oikeuslingvistiikan kanssa. Muissa kielissä näitä ei välttämättä edes erotella. Otetaan ohjaustermiksi:
forensinen lingvistiikka KÄYTÄ oikeuslingvistiikka
