### ISSUE TITLE
Kivitalo (Fiskars)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7512]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kivitalo (Fiskars) 

#### Ehdotettu termi ruotsiksi   

Stenhuset 

#### Vaihtoehtoiset termit ja ilmaisut   

Kivimuuri 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Stenhuset: Fiskars Corps de Logis 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Kivitalo (Fiskars)](http://finto.fi/yse/fi/page/Y507512)

**Comment by mariaforsen** [comment]
Sv. Stenhuset (Fiskars) ET Stenhuset, Stenmuren (Fiskars)
