### ISSUE TITLE
kuosit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7516]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuosit](http://www.yso.fi/onto/ysa/Y151308) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritellään käsite, jotta kuvailijalle ja tiedonhakijalle olisi selvä, mihin (kaikkeen) se viittaa. 

#### Perustelut ehdotukselle   

Suomenkielisen Wikipedian mukaan "Kuosi on esineelle, etenkin vaatekappaleelle, ominainen muoto, malli tai tyyli. Kuosiksi voidaan myös kutsua vaatteiden tai tekstiilien koristekuviota, esimerkiksi kukkakuosi tai kašmirkuosi." YSO ei ota kantaa, kumpaan "kuosit"-asiasana viittaa. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
1. esineelle, vars. yksittäiselle vaatekappaleelle ominainen, tav. muodin mukainen muoto t. asu, malli; muoti, ryhti, tyyli. _Puvun, kengän kuosi. Kuosinsa menettänyt vaate._

2. koristekuvio, -malli; tekst. kutomalla, neulomalla t. painamalla tehtyjen kuvioiden kokonaisuus; kudotun t. neulotun tuotteen muu kuin sileä pintarakenne. _Geometriset kuosit. Kukka-, ruutu-, kašmirkuosi. Värikkäät painokuosit._ 

Jos rajataan 2. merkitykseen, mikähän olisi mahdollinen tarkenne (sekä kuvio että pintarakenne)?

**Comment by mariaforsen** [comment]
ALLFO: textilmönster, eli rajattu tekstiileihin. Voisi olla mönster (figurer)? Pintarakenteesta sitä ei varmaan käytetä ruotsiksi.

**Comment by satuniininen** [comment]
Melindassa tätä on pääasiassa käytetty tekstiilien (paino)kuoseista, jonkin verran myös laajemmin esim. https://melinda.kansalliskirjasto.fi/byid/006010710

_Kuosit (pintakuviot)_ tai _kuosit (pintakuviointi)_ kattaisi myös pintarakenteen, mutta jos sitä ei ruotsiksi käytetä ja halutaan tiukempi rajaus nimenomaan tekstiileihin niin ehkä _tekstiilikuosit_? Sitä ei ehkä kovin herkästi käyttäisi ykkösmerkityksestä.

**Comment by AuHo22** [comment]
Textilmönster / tekstiilikuosit selventää eroa käsityömalleihin / handarbetsmodeller KT mönster, handarbetsmönster, mönster (handarbete)

**Comment by YSO-kokous** [comment]
Muutetaan käytettävä termi muotoon _kuosit (pintakuviointi)_. Ohjaustermiksi _tekstiilikuosit_. Käsite kattaa myös esim. tapettien kuosit.
