### ISSUE TITLE
muutos

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7517]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muutos](http://www.yso.fi/onto/ysa/Y106377) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT muutokset? 

#### Perustelut ehdotukselle   

Käytetty paljon

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
