### ISSUE TITLE
pirkkalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7518]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pirkkalaiset 

#### Ehdotettu termi ruotsiksi   

birckarlar 

#### Vaihtoehtoiset termit ja ilmaisut   

pirkanmiehet 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Pirkkalaiset 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Birckarlien ja kveenien jalanjäljissä 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [pirkkalaiset](http://finto.fi/yse/fi/page/Y507518)

**Comment by mirmaid** [comment]
Lapponica-sanastossa: http://urn.fi/URN:NBN:fi:au:lapponica:L420

Käytetty Melindassa 26 kertaa.

**Comment by mariaforsen** [comment]
Sv. birkarlar ET birckarlar

**Comment by mariaforsen** [comment]
Vaatii tarkenteen suomeksi? https://www.kielikello.fi/-/karjalaiset-ja-pirkkalaiset

**Comment by YSA-kokous** [comment]
Vaatii sulkutarkenteen. Tutkitaan sopiva tarkenne, esim. historia, muinaiskansat, pirkanmiehet. Huom! pirkanmiehet on myös kuoro.

**Comment by krinay** [comment]
Olisiko _pirkkalaiset (birckarlar)_ ihan mahdoton? 
Ks. http://senc.hum.helsinki.fi/wiki/Pirkkalaiset#tab=suomi
"Suomenkielinen käsite pirkkalainen (pirkkalaiset) syntyi ja otettiin käyttöön vasta 1800-luvun alussa, kun Suomen historiasta alettiin kirjoittaa suomen kielellä. Tällöin ruotsinkielisissä asiakirjoissa yksinomaisesti esiintyvä käsite birckarlar käännettiin "pirkkalaisiksi". Koska nimitys on vahvasti vakiintunut suomen kieleen, sitä voidaan käyttää, kunhan muistetaan, ettei se ole alkuperäinen nimi, joka edellyttäisi heidän olevan peräisin ja saaneen nimensä Satakunnan Pirkkalan pitäjästä. Nimitystä pirkkalainen ei ole koskaan tavattu siis elävästä kansanperinteestä ja -kielestä."

**Comment by mirmaid** [comment]
Myös muotoa _pirkkamiehet_ käytetty. Tai sitten _pirkkalaiset (historia)_ ja määritelmä.

**Comment by YSO-kokous** [comment]
Äänestettiin käytettävästä termistä:
pirkkalaiset (birkarlar) 2
pirkkamiehet 0
pirkkalaiset (historia) 3
Käytettäväksi termiksi pirkkalaiset (historia) ja lisätään määritelmä.
