### ISSUE TITLE
luontaishoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7519]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luontaishoito](http://www.yso.fi/onto/ysa/Y97033) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT luonnonlääketiede 

#### Perustelut ehdotukselle   

Käytetty Melindassa ja muutenkin.

**Comment by YSA-kokous** [comment]
Tutkitaan vielä. Sanastossa myös kansanlääkintä, luonnonparannus jne. Ks. ohjaustermi luonnonlääkintä.
Kristiina Näyhö tutkii.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

**Comment by krinay** [comment]
Ehdotus: Yhdistetään luonnonparannus ja luontaishoito, lisätään ehdotetun ohjaustermin (luonnonlääketiede) lisäksi ohjaustermit luontaislääketiede ja luontaislääkintä. Siis:
luontaishoito KT luonnonlääketiede, luonnonlääkintä, luonnonparannus, luontaislääketiede, luontaislääkintä, vaihtoehtohoidot.

Kielitoimiston sanakirja:
**luonnonlääkintä** eril. luonnonparannusmenetelmien käyttö
**luonnonparannus** luontaishoito
**luontaishoito** sairauksien ja muiden häiriötilojen lääkkeetön hoito ruokavalion, liikunnan, kylpyjen, hieronnan tms. avulla. Luontaishoitoja antava parantola.

https://fi.wikipedia.org/wiki/Luontaisl%C3%A4%C3%A4kint%C3%A4 

Melindassa asiasanana (Google-osumia):
luonnonparannus 926 (3130)
luontaishoito 1221 (192 000)
luonnonparannus + luontaishoito 373
+
luonnonlääketiede 9 (15 600)
luonnonlääkintä 48 (4440)
luontaislääketiede: Google-osumia 6520

**Comment by krinay** [comment]
YSOssa on lisäksi (Melindassa asiasanana / Google-osumia):
**kansanlääkintä** (2032 / 28 000) KT etnomedisiina, kansanparannus, kansanparannustaito
**vaihtoehtolääkintä** (2090 / 6530) KT funktionaalinen lääketiede, luonnonlääkintä, luontaislääketiede, toiminnallinen lääketiede, uskomuslääkintä, vaihtoehtohoidot, vaihtoehtoinen lääketiede, vaihtoehtoiset hoitomuodot, vaihtoehtolääketiede.
+ 
fytoterapia (281 / 70 600) KT kasvilääkintä; yrttilääkintä

Vaihtoehtolääkinnälle voisi ehkä samalla lisätä ohjaustermit täydentävä lääketiede ja CAM-hoidot.

Taustaa:
Funktionaalisen lääketieteen yhdistys http://www.fms.fi/  
Kansanlääkintäseura ry http://www.kansanlaakintaseura.fi/  
Luonnonlääketieteen keskusliitto LKL ry. https://www.lkl.fi/ 
Katsaus suomalaiseen CAM-tutkimukseen  https://doi.org/10.23990/sa.74424 

Wikipedia: 
kansanparannus https://fi.wikipedia.org/wiki/Kansanparannus 
luontaislääkintä  https://fi.wikipedia.org/wiki/Luontaisl%C3%A4%C3%A4kint%C3%A4 
uskomuslääkintä https://fi.wikipedia.org/wiki/Uskomusl%C3%A4%C3%A4kint%C3%A4

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus yhdistämisestä.
Käytettäväksi termiksi luontaishoito. Ohjaustermeiksi: luonnonlääketiede, luonnonlääkintä, luonnonparannus, luontaislääketiede, luontaislääkintä, vaihtoehtohoidot.

**Comment by mariaforsen** [comment]
Sv. naturläkekonst
