### ISSUE TITLE
tuloksellisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7520]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tuloksellisuus](http://www.yso.fi/onto/ysa/Y109437) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT tuloksekkuus 

#### Perustelut ehdotukselle   

On synonymi.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
