### ISSUE TITLE
videoidut tanssiesitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7521]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

videoidut tanssiesitykset 

#### Ehdotettu termi ruotsiksi   

filmade dansföreställningar 

#### Ehdotettu termi englanniksi   

filmed dance 

#### Vastaava käsite muussa sanastossa   

LCGFT : Filmed dance 
saogf : Filmade dansföreställningar 

#### Perustelut ehdotukselle   

SLM-sanastoon. Tarvitaan videoitujen tanssiesitysten kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Do animals cry / choreography Meg Stuart 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [videoidut tanssiesitykset](http://finto.fi/yse/fi/page/Y507521)

**Comment by AuHo22** [comment]
videoidut esitykset + tanssiteokset (YSO-termi)?
