### ISSUE TITLE
Videotaide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7523]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Videotaide 

#### Ehdotettu termi ruotsiksi   

Videokonst 

#### Ehdotettu termi englanniksi   

Video art 

#### Vastaava käsite muussa sanastossa   

LCSH : Video art 
Saogf : Videokonst 

#### Perustelut ehdotukselle   

SLM-sanastoon. Tarvitaan videotaiteen kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Video works 1970-1999 /  William Wegman 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [Videotaide](http://finto.fi/yse/fi/page/Y507523)

**Comment by ilona-x** [comment]
videotaide on jo YSOssa http://www.yso.fi/onto/yso/p11955

**Comment by mirmaid** [comment]
Sanastossa on termi _videoelokuvat_, miten nämä eroaisivat toisistaan?

**Comment by mirmaid** [comment]
videotaideteokset KT videoteokset

Poistetaan videoelokuvat.

**Comment by mirmaid** [comment]
Poistetaanko _videoelokuvat_ myös YSOsta?

**Comment by YSO-kokous** [comment]
Jätetään videoelokuvat YSOon.
