### ISSUE TITLE
punajalkahaukka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7524]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

punajalkahaukka 

#### Ehdotettu termi ruotsiksi   

aftonfalk 

#### Ehdotettu termi englanniksi   

red-footed falcon 

#### Vaihtoehtoiset termit ja ilmaisut   

Falco vespertinus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[haukat](http://www.yso.fi/onto/yso/p5791) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Punajalkahaukka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Perustelut ehdotukselle   

Käytetty Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Nuoren nuoli- ja punajalkahaukan määrittämisestä 

**Termiehdotus Fintossa:** [punajalkahaukka](http://finto.fi/yse/fi/page/Y507524)

**Comment by PaiviLipsanen** [comment]
Yläkäsite on jalohaukat
Hierarkia: linnut - jalohaukkalinnut - jalohaukat (heimo) - jalohaukat (suku) - punajalkahaukka (Falco vesperinus)
https://laji.fi/taxon/MX.26805

Vertailun vuoksi:
Hierarkia: linnut - päiväpetolinnut - haukat (heimo) - lintuhaukat (suku) - kanahaukka (Accipiter gentilis)
https://laji.fi/taxon/MX.26647
