### ISSUE TITLE
tunnelinrakennus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7526]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tunnelinrakennus](http://www.yso.fi/onto/ysa/Y99645) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT tunnelirakentaminen, tunnelirakennus 

#### Perustelut ehdotukselle   

Synonymi

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
