### ISSUE TITLE
tietokonetomografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7530]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietokonetomografia](http://www.yso.fi/onto/ysa/Y136196) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermit TT-kuvaus ja CT-kuvaus 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Tietokonekerroskuvaus
http://www.yso.fi/onto/mesh/D014057 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. ET CT, DT

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
