### ISSUE TITLE
meriteknologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7532]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

meriteknologia 

#### Perustelut ehdotukselle   

Meritekniikka toimii laivojen rakennuksen, ohjaamisen ja ylläpidon kentällä. Meri-insinöörit vastaavat laivojen koneista ja järjestelmistä, ja tietävätkin valtavasti esimerkiksi erilaisista moottoreista, kaasuturbiineista, sähkölaitteista ja hydraulisista laitteista. https://www.masterstudies.fi/Maisteri/Meritekniikka/
Arktinen meriteknologia on mereen liittyvää teknologiaa merellä, ilmassa, meren alla tai maalla. Teknologia liittyy etenkin kaasun- ja öljyntuotantoon ja kaivostoimintaan sekä ravinnoksi kelpaavien luonnonvarojen hyödyntämiseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-99539-3-6  Koillisväylä ja arktisen meriteknologian kehittämistarpeet Suomessa 

#### Tarkoitusta täsmentävä selite   

Pitäisikö olla oma käsitteensä vai ohjaustermi meritekniikalle? 

**Termiehdotus Fintossa:** [meriteknologia](http://finto.fi/yse/fi/page/Y507532)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjan mukaan _meritekniikka_: merenpohjan luonnonvarojen etsimisessä ja hyödyntämisessä käytettävä tekniikka.

**Comment by mirmaid** [comment]
Tuskin mahdollista pitää erillään (ilman tarkenteita), ks. esim. https://www.sttinfo.fi/tiedote/aalto-yliopisto-ja-meriteollisuus-ry-tiivistavat-tutkimusyhteistyota?publisherId=37936456&releaseId=43750053

**Comment by mariaforsen** [comment]
Käytetäänkö johdonmukaisesti muutenkaan..? Ruotsiksi ei ainakaan näytä siltä. Odottaisin.
havsteknologi ANV havsteknik

**Comment by YSA-kokous** [comment]
Hyväksytään ohjaustermiksi.
meriteknologia KÄYTÄ meritekniikka
