### ISSUE TITLE
raita

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7533]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

raita 

#### Ehdotettu termi ruotsiksi   

sälg 

#### Ehdotettu termi englanniksi   

goat wlllow 

#### Vaihtoehtoiset termit ja ilmaisut   

Salix caprea 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puulajit](http://www.yso.fi/onto/yso/p13848) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Raita 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Käytetty Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sälg : livets viktigaste frukost / text Bengt Ehnström ; illustrationer Martin Holmer. 

**Termiehdotus Fintossa:** [raita](http://finto.fi/yse/fi/page/Y507533)

**Comment by mirmaid** [comment]
raita (pajukasvit) (?), myös esim. https://fi.wikipedia.org/wiki/Raita_(ruoka)

**Comment by PaiviLipsanen** [comment]
Raita kuuluu pajujen sukuun
pajut (Salix)
alakäsite: raita (Salix caprea)
https://laji.fi/taxon/MX.38563

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa "raita (pajut)", yläkäsitteeksi pajut.
