### ISSUE TITLE
Graal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7535]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Graal](http://www.yso.fi/onto/ysa/Y147393) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään asiasanalle KT-muoto "Graalin malja" tai muutetaan asiasana itsessään kyseiseen muotoon. Lisäksi vaihdetaan asiasanan LT-muoto "uskontoon liittyvät abstraktit objektit" --> "ehtoollisastiat". 

#### Perustelut ehdotukselle   

Graal ilman malja-määrettä voitaisiin ymmärtävän viittaavan myös Graalin linnaan. Lisäksi Graalin malja on ehtoollisastia – ottamatta kantaa sen (epä)historiallisuuteen –, ei abstraksi objekti, kuten esimerkiksi aneet, armo ja henkimaailma. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSA-kokous** [comment]
Hyväksytään ohjaustermi Graalin malja. Ei muita muutoksia. Graal-käsite on merkitykseltään epäselvä ja siksi yläkäsite uskontoon liittyvät abstraktit objektit on sopivan kattava.
