### ISSUE TITLE
elektrokatalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7536]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

elektrokatalyysi 

#### Ehdotettu termi englanniksi   

Electrocatalysis 

#### Ehdotettu termi ruotsiksi   

elektrokatalys 

#### Ehdotettu yläkäsite YSOssa (LT)   

[katalyysi](http://www.yso.fi/onto/yso/p8704) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh97006565> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hydrogen evolution reaction on carbon nanotubes : insights from electronic structure theory / 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 
[30 Kemianteollisuus. Keraaminen teollisuus. Lasiteollisuus. Muoviteollisuus. Kumiteollisuus](http://www.yso.fi/onto/yso/p26530) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [elektrokatalyysi](http://finto.fi/yse/fi/page/Y507536)

**Comment by YSA-kokous** [comment]
Hyväksytään.
