### ISSUE TITLE
tulehdukselliset suolistosairaudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7538]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Inflammatory bowel diseases 

#### Ehdotettu termi suomeksi   

tulehdukselliset suolistosairaudet 

#### Ehdotettu termi ruotsiksi   

inflammatoriska tarmsjukdomar 

#### Vaihtoehtoiset termit ja ilmaisut   

IBD 

#### Ehdotettu yläkäsite YSOssa (LT)   

[suoliston taudit](http://www.yso.fi/onto/yso/p4707) 

#### Alakäsitteet (RT)   

[haavainen koliitti](http://www.yso.fi/onto/yso/p22574) 
[Crohnin tauti](http://www.yso.fi/onto/yso/p23556) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh90000009> 
FinMeSH : <http://www.yso.fi/onto/mesh/D015212> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tekemätöntä työtä, näkymättömiä kustannuksia : selvitys tulehduksellisia suolistosairauksia ja reumasairauksia sairastavien työ- ja toimintakyvystä sekä niiden menetyksestä aiheutuvista kustannuksista 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tulehdukselliset suolistosairaudet](http://finto.fi/yse/fi/page/Y507538)

**Comment by mirmaid** [comment]
Myös _Oral cobalamin supplementation in dogs_

**Comment by mariaforsen** [comment]
Sv. inflammatoriska tarmsjukdomar ET IBD
