### ISSUE TITLE
joulukuuset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7540]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[joulukuuset](http://www.yso.fi/onto/ysa/Y101956) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "joulupuut" 

#### Perustelut ehdotukselle   

"Joulukuusi eli joulupuu on jouluna tavallisesti sisällä pidettävä koristeltu puu, joka Suomessa on yleensä kuusi." [https://fi.wikipedia.org/wiki/Joulukuusi] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus, mutta lisätään samalla määritelmä, koska se selittää ohjaustermin.
