### ISSUE TITLE
kustannusjohtajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7541]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kustannusjohtajat](http://www.yso.fi/onto/ysa/Y105388) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT kustannuspäälliköt (tai uutena terminä) 

#### Perustelut ehdotukselle   

Tavallisempi nimitys?

**Comment by mirmaid** [comment]
12800/16200

**Comment by YSA-kokous** [comment]
Esim. Otavassa on kustannusjohtaja, joka on kustannuspäällikön esimies. Tässä varmasti yrityskohtaisia eroja. Jää selvitettäväksi seuraavaan kokoukseen, otetaanko ohjaustermiksi vai erillisenä.

**Comment by mirmaid** [comment]
http://kustantaminen.fi/pages/3/kustantamon-tehtavat/
https://www.marmai.fi/uutiset/otava-myllaa-organisaatiotaan/dd6c7643-cc39-3b11-ac5d-a4b593252324
https://otava.fi/kustantamo/kaunokirjallisuus/

Ylläolevien sivujen perusteella kustannusjohtajalla voidaan viitata suuren osaston (tai kustantamon) johtajaan, jonka alaisena toimii kustannuspäälliköitä.

**Comment by ilona-x** [comment]
^Vastaava varmaankin myyntijohtajat & myyntipäälliköt 
"Myyntipäällikkö tai myyntijohtaja johtaa yrityksen myyntiosaston toimintaa." http://www.ammattinetti.fi/ammatit/detail/2158e7da0a6534460093ed89916b51ab

http://www.kysy.fi/kysymys/mita-eroa-on-paallikolla-ja-johtajalla

**Comment by YSO-kokous** [comment]
Kaikki kustannuspäälliköt eivät ole kustannusjohtajia. Tässä on organisaatiokohtaisia eroja, monessa organisaatiossa on molempia.

Päätös: otetaan kustannuspäälliköt sanastoon erillisenä käsitteenä.

**Comment by mariaforsen** [comment]
Sv. förlagschefer
