### ISSUE TITLE
kuntajohtajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7542]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuntajohtajat](http://www.yso.fi/onto/ysa/Y111992) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa ja KÄYTÄ kunnanjohtajat? 

#### Perustelut ehdotukselle   

Muoto kuntajohtaja ei löydy sanastoista/sanakirjoista. EKSissä taas on korvattuna kunnanjohtajat.

**Comment by ilona-x** [comment]
EKS: 
Asiasana: kuntajohtajat 
Korvaa termin: kunnanjohtajat

**Comment by YSA-kokous** [comment]
Lisätään kuntajohtajat ohjaustermiksi kunnanjohtajille.
Poistetaan kuntajohtajat. Korjataan hierarkiaa: kaupunginjohtajat LT kunnanjohtajat, kauppalanjohtajat LT kunnanjohtajat.
