### ISSUE TITLE
itsekasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7543]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itsekasvatus](http://www.yso.fi/onto/ysa/Y95592) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT henkilökohtainen kehitys? 

#### Perustelut ehdotukselle   

Korvattuna on jo "itsensä kehittäminen" joka lienee synonymi tälle ehdotukselle. Käytetty Melindassa. Olisivatko nämä oikeastaan parempia päätermeinä kuin "itsekasvatus"? Google: "henkilökohtainen kehitys"=616 000 osumaa, "itsekasvatus"=7 260 osumaa, "itsensä kehittäminen"=90 700 osumaa.

**Comment by mirmaid** [comment]
YSOssa on myös esim. _henkinen kasvu_ (KT henkinen kehitys (elämäntaito)), johon tämä ohjaustermi voisi viitata?

**Comment by mariaforsen** [comment]
Ruotsin osalta olisi kyllä personlig utveckling/henkilökohtainen kehitys KÄYTÄ självutveckling/itsekasvatus, ei henkinen kasvu/andlig tillväxt -eli ongelma saattaa tulla siinä tapauksessa... Ja eikö itsensä kehittäminen ole aika lähellä henkilökohtainen kehitys/kehittäminen?

**Comment by mirmaid** [comment]
^ Henkilökohtainen kehitys on ehkä enemmän "kehittymistä" kuin "kehittämistä". Tässä on vähän hankala ero tosiaan kielten välillä, kun utveckling ei mitenkään välttämättä ole jotain mitä ihminen aktiivisesti tekee itselleen tai jollekin muulle.

**Comment by YSA-kokous** [comment]
Käsitellään seuraavassa kokouksessa. Termien synonyymiys herätti keskustelua: viittaavatko termit samaan vai eri asiaan?

**Comment by mirmaid** [comment]
Mitä oikeastaan on _andlig tillväxt_? Jos tarkoittaa _processen att bli mer och mer lik Jesus Kristus_, niin ei varmaan oikea vastine ole suomeksi _henkinen kasvu_ (=psyykkinen kasvu, muuttuminen psyykkisesti kypsemmäksi, ainakin näin minä ymmärrän).

**Comment by mirmaid** [comment]
Sanastossa on myös _uskonnollinen kehitys_. Joka tapauksessa suomeksi _henkinen kasvu_ ei rajaudu uskontoon tai spiritualiteettiin, vaan voi olla ihan tavallista kypsemmäksi ja aikuisemmaksi muuttumista. En varmaan itse tulisi edes käyttäneeksi sitä uskonnollisessa yhteydessä, paitsi jos kyse on muuttumisesta psyykkisesti kypsemmäksi jossain uskonnollisessa viitekehyksessä - en siis pelkästä kehittymisestä "paremmaksi uskossa".

**Comment by mariaforsen** [comment]
Andlig tillväxt ei rajaudu kristinuskoon. Tosin "andlig utveckling" olisi ehkä parempi (fi. henkinen kehitys)

**Comment by FinMeSHienPaimentaja** [comment]
Nuo muut puheena olevat ovat mielestäni melko lailla samaa tarkoittavia, paitsi "henkinen kasvu"...nooh, henkisempi juttu :D. Vaikka saattaa liittyäkin itsensä kehittämiseen ja kehittymiseen.

**Comment by mirmaid** [comment]
Sopiiko seuraaviin myös _andlig tillväxt_:
Selviytymisopas elämän kriiseihin https://melinda.kansalliskirjasto.fi/byid/016714047
The Routledge international handbook of critical positive psychology https://melinda.kansalliskirjasto.fi/byid/011115657
The psychology of grief https://melinda.kansalliskirjasto.fi/byid/012195136
Annetaan nuorten haahuilla https://melinda.kansalliskirjasto.fi/byid/015354261

**Comment by mirmaid** [comment]
Jos _itsekasvatus_ jää ennalleen, on ratkaistava vielä ohjaustermi: henkilökohtainen kehitys KÄ henkinen kasvu JA itsekasvatus?

Mietin vielä, että eikö _personlig utveckling_ (entä _självutveckling_?) ole jotain, mitä ihmiselle ihan luonnostaan tapahtuu esim. ikävuosien 13 ja 23 välillä? Ja eikö ole ongelma, jos tällaisessa tilanteessa kuvailuun tulisi _itsekasvatus_ (joka mielestäni enemmän vastaa KT-muotoa _självfostran_)? Harva teini kasvattaa itseään...

**Comment by mariaforsen** [comment]
Personlig utveckling ei millään tavalla rajaudu nuoriin ja se tehdään tietoisesti, eli ei tapahdu itsestään/luonnostaan, määritellään esim. näin "Utveckling av personliga egenskaper som förhållningssätt, reaktionsmönster, attityder, värderingar, livssyn och sätt att tänka och handla. " /Psykologilexikon
Ks. myös https://www.psykologiguiden.se/psykologilexikon/?Lookup=sj%C3%A4lvutveckling ja https://www.psykologiguiden.se/psykologilexikon/?Lookup=andlig%20utveckling

**Comment by mirmaid** [comment]
^ En siis tarkoittanut, että se rajautuisi nuoriin. Mutta jos personlig utveckling on = kehittäminen (=aktiivista, kuten fostran), eli "henkilö tietoisesti kasvattaa itsestään paremman ihmisen", niin sitten varmaan itsekasvatus vastineena on ok. Utveckling voi kuitenkin muissa yhteyksissä olla (ja usein on) = kehittyminen, joten oletin, että tässäkin on mahdollista kehittyä myös ilman tietoista ponnistelua.

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä henkilökohtainen kehitys. Ei ole sama asia kuin itsekasvatus. Suomen kielessä henkilökohtainen kehitys on enemmän passiivinen ja epäselvempi. Viittaa enemmän sellaiseen kehitykseen, joka ei ole itse tietoisesti edistettyä itsensä kehittämistä tai itsekasvatusta, ja voi toisaalta liittyä esim. urakehitykseen työelämässä tms.

Ruotsin vastinetta mietitään tämän pohjalta.
