### ISSUE TITLE
mielikuvaharjoittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7544]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mielikuvaharjoittelu](http://www.yso.fi/onto/ysa/Y113019) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT visualisointi (psykologia)? 

#### Perustelut ehdotukselle   

On ymmärtääkseni synonymi, ks. google ja esim. wikipedia. Sanastossa tosin myös visualisointi toisessa merkityksessä (eli tarkenne on tarpeen)

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
