### ISSUE TITLE
valtimonkovettumistauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7545]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valtimonkovettumistauti](http://www.yso.fi/onto/ysa/Y100007) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT valtimotauti 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
FinMeSH > ateroskleroosi, valtimonkovettumistauti (edellinen kuitenkin jälkimmäisen alakäsite)
https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00095

**Comment by YSA-kokous** [comment]
Hyväksytään seuraavat ohjaustermit:
valtimotauti KÄYTÄ valtimonkovettumistauti
valtimotauti KÄYTÄ ateroskleroosi
