### ISSUE TITLE
Västerås

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7546]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Västerås 

#### Ehdotettu termi ruotsiksi   

Västerås 

#### Ehdotettu termi englanniksi   

Västerås 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q34550 

#### Perustelut ehdotukselle   

Käytetty Melinda-kuvailussa yli 100 kertaa. Erotuttava Lahden kaupunginosasta. 

#### Tarkoitusta täsmentävä selite   

Västerås on sekä kaupunki Ruotsissa Västmanlandin läänissä että kaupunginosa Lahdessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/GEDXM9K3MQB8F6U2TIXRETJ6CJAQEEL2I7MA824KK8AR4LFS7D-01084?func=short-0&set_number=041471 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Västerås](http://finto.fi/yse/fi/page/Y507546)

**Comment by mirmaid** [comment]
Lahden kaupunginosa muutettu muotoon _Vesterås_.
