### ISSUE TITLE
työperäinen altistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7548]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

työperäinen altistus 

#### Ehdotettu termi ruotsiksi   

yrkesmässig exponering 

#### Ehdotettu termi englanniksi   

Occupational Exposure 

#### Ehdotettu yläkäsite YSOssa (LT)   

[altistuminen](http://www.yso.fi/onto/yso/p12853) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D016273> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Occupational exposure and risk of bladder cancer 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [työperäinen altistus](http://finto.fi/yse/fi/page/Y507548)

**Comment by mirmaid** [comment]
36 kertaa Melindassa.

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mariaforsen** [comment]
Sv. yrkesmässig exponering ET yrkesexponering, arbetsrelaterad exponering, arbetsexponering
