### ISSUE TITLE
ammattitaudit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7550]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ammattitaudit](http://www.yso.fi/onto/ysa/Y94632) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

FinMeSH: 
ammattitaudit KT työperäiset sairaudet http://www.yso.fi/onto/mesh/D009784

https://www.ttl.fi/tyontekija/ammattitaudit/

Melinda:
ammattitaudit x 1375
työperäiset sairaudet x 1056
työperäiset sairaudet & ammattitaudit x 589 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdotettu muutos   

Voisiko ammattitaudit ja työperäiset sairaudet yhdistää?

**Comment by mariaforsen** [comment]
Myös SAOssa yrkessjukdomar ET arbetsrelaterade sjukdomar, arbetssjukdomar

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa ammattitaudit, ohjaustermiksi työperäiset sairaudet. Ammattitaudit sai äänestyksessä enemmän ääniä.

**Comment by mariaforsen** [comment]
Nämä ovat jo sanastossa, eli työperäiset sairaudet poistetaan ja laitetaan ohjaustermiksi?
