### ISSUE TITLE
androgeeniantagonistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7551]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

androgeeniantagonistit 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D000726> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/012619676 

**Termiehdotus Fintossa:** [androgeeniantagonistit](http://finto.fi/yse/fi/page/Y507551)

**Comment by mirmaid** [comment]
LCSH: Antiandrogens, http://id.loc.gov/authorities/subjects/sh85005628
Lääketieteen termit: antiandrogeeni: _mieshormonien vastavaikuttaja | androgeenien vaikutusta estävä tai vähentävä (lääke)aine_

2 viitettä Melindassa, Google 69 androgeeniantagonistit/1390 antiandrogeenit.

**Comment by mariaforsen** [comment]
Sv.  antiandrogener ET androgenblockerare, androgenantagonister

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa antiandrogeeniksi, ohjaustermiksi androgeeniantagonistit.
