### ISSUE TITLE
taliini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7552]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taliini 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D016608> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/014439854 

**Termiehdotus Fintossa:** [taliini](http://finto.fi/yse/fi/page/Y507552)

**Comment by mirmaid** [comment]
Lääketieteen termit: _solujen keskinäisissä liitoskohdissa runsaina esiintyviä molekyylejä, jotka aktivoivat →kindliinejä_

**Comment by mariaforsen** [comment]
Sv. talin
