### ISSUE TITLE
salapoliisikirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7553]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[salapoliisikirjallisuus](http://www.yso.fi/onto/ysa/Y107447) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT dekkarikirjallisuus? 

#### Perustelut ehdotukselle   

On Melindassa. Dekkarit on jo korvattuna.

**Comment by ilona-x** [comment]
https://www.kirjasampo.fi/fi/genre/j%C3%A4nnityskirjallisuus

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus. Lisäksi otetaan seuraavat ohjaustermit:

dekkarikirjallisuus KÄYTÄ salapoliisikirjallisuus
dekkarikirjallisuus KÄYTÄ rikoskirjallisuus
dekkarit KÄYTÄ rikoskirjallisuus

Todettiin, että dekkarit ei sovi ohjaustermiksi jännityskirjallisuudelle.

Korjataan ohjaustermit samalla tavalla myös SLM:ssä. (Ks. jännityskirjallisuus)

**Comment by mirmaid** [comment]
Myös KÄ poliisikirjallisuus (molemmat sanastot)
