### ISSUE TITLE
hyppyhäntäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7554]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hyppyhäntäiset 

#### Ehdotettu termi ruotsiksi   

hoppstjärtar 

#### Ehdotettu termi englanniksi   

Springtails 

#### Vaihtoehtoiset termit ja ilmaisut   

Collembola 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hyönteiset](http://www.yso.fi/onto/yso/p1983) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Hyppyh%C3%A4nt%C3%A4iset 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Tarvitaan Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lämpötilan ja kosteuden vaihtelun vaikutus hyppyhäntäisten (Collembola) ja petopunkkien (Mesostigmata) populaatioihin ja diversiteettiin / Sanna-Maria Hänninen. 

**Termiehdotus Fintossa:** [hyppyhäntäiset](http://finto.fi/yse/fi/page/Y507554)

**Comment by PaiviLipsanen** [comment]
Yläkäsite:  niveljalkaiset 
https://laji.fi/taxon/MX.70219
