### ISSUE TITLE
rahoitusinstrumentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7555]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rahoitusinstrumentit 

#### Perustelut ehdotukselle   

Ollut käytössä Helecon sanastossa ja käytetty rahoituksen hyllyluokan kirjoissa tarpeen mukaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Aalto-yliopiston kirjasto **Termiehdotus Fintossa:** [rahoitusinstrumentit](http://finto.fi/yse/fi/page/Y507555)

**Comment by ilona-x** [comment]
LIITO: rahoitusväline KT rahoitusinstrumentti http://www.yso.fi/onto/liito/p13368

rahoitusvälineet ehdotettu aiemmin https://github.com/Finto-ehdotus/YSE/issues/3261

**Comment by mirmaid** [comment]
Melindassa 2 kertaa _rahoitusvälineet_, 21 kertaa _rahoitusinstrumentit_.

**Comment by mirmaid** [comment]
LCSH: Financial instruments http://id.loc.gov/authorities/subjects/sh91002259

**Comment by mirmaid** [comment]
Ero _arvopaperit_-käsitteeseen vähän epäselvä, https://en.wikipedia.org/wiki/Security_(finance).

**Comment by mirmaid** [comment]
https://www.finlex.fi/fi/laki/ajantasa/2012/20120747#O1L1P14

**Comment by mariaforsen** [comment]
Sv. finansiella instrument ET finansinstrument, finansieringsinstrument

Pankki- ja rahoitussanasto / Bank- och finansterminologi (TSK), 2014-10-03: 
"väline, jota liikkeeseenlaskija käyttää varojen hankkimiseen
huomautus
Sijoittajan näkökulmasta rahoitusväline on sijoituskohde. Rahoitusvälineitä ovat erilaiset arvopaperit (1) sekä johdannaissopimukset. Sijoittajille liiketoimintana tarjottavista rahoitusvälineistä säädetään sijoituspalvelulaissa"

**Comment by YSA-kokous** [comment]
Otetaan muodossa rahoitusvälineet (vrt. laki). Ohjaustermiksi rahoitusinstrumentit.
Pohditaan hierarkiaa YSO-kokouksessa. Tutkitaan johdannaiset-käsitteen sulkutarkennetta.
