### ISSUE TITLE
semait

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7556]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

semait 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/016597036 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [semait](http://finto.fi/yse/fi/page/Y507556)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Semai_people
LCSH: Senoi http://id.loc.gov/authorities/subjects/sh85120032
https://fi.wikipedia.org/wiki/Senoit

**Comment by mirmaid** [comment]
Melindassa 2 kertaa monikossa, 3 kertaa yksikössä.

_Senoit_ kerran monikossa, kerran yksikössä.

**Comment by mariaforsen** [comment]
Sv. 
-semai (folk) 
-senoi (folk)

**Comment by YSA-kokous** [comment]
Otetaan sanastoon erikseen:
semait
senoit
