### ISSUE TITLE
semain kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7557]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

semain kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/016597036 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [semain kieli](http://finto.fi/yse/fi/page/Y507557)

**Comment by mirmaid** [comment]
http://lexvo.org/id/iso639-3/sea

**Comment by mirmaid** [comment]
LCSH: Semai language http://id.loc.gov/authorities/subjects/sh90006164

Suomeksi? Muilla kielillä semai, joten _semain kieli_ lienee ok?

**Comment by mariaforsen** [comment]
Sv. semai (språk)

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
