### ISSUE TITLE
digitaaliset osaamismerkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7561]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

digitaaliset osaamismerkit 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Digitaaliset_osaamismerkit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/015277603 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [digitaaliset osaamismerkit](http://finto.fi/yse/fi/page/Y507561)

**Comment by mirmaid** [comment]
Kerran Melindassa, Google n. 2800.

**Comment by mariaforsen** [comment]
Sv. digital badges? digitala diplom/medaljer/utmärkelser/kunskapsmärken..? https://www.diva-portal.org/smash/get/diva2:1111968/FULLTEXT01.pdf

**Comment by YSA-kokous** [comment]
Jatketaan seuraavassa kokouksessa. On käytössä myös pelkkä _osaamismerkit_ viitattaessa digitaalisiin osaamismerkkeihin.

**Comment by krinay** [comment]
https://sites.google.com/edu.hel.fi/osaamismerkki/

**Comment by mariaforsen** [comment]
Sv. kompetensmärken? (fi)

**Comment by mirmaid** [comment]
Osaamismerkit KT digitaaliset osaamismerkit?

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermi: digitaaliset osaamismerkit KÄYTÄ osaamismerkit.

**Comment by mariaforsen** [comment]
Sv. kompetensmärken
