### ISSUE TITLE
grafiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7562]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

grafiitti 

#### Ehdotettu termi ruotsiksi   

grafit 

#### Ehdotettu termi englanniksi   

graphite 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Grafiitti 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Käytetty Melindassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Theoretical studies on adsorption of water on graphite surface / Henna Ruuska 

**Termiehdotus Fintossa:** [grafiitti](http://finto.fi/yse/fi/page/Y507562)

**Comment by mirmaid** [comment]
LCSH: Graphite http://id.loc.gov/authorities/subjects/sh85056487

19 kertaa Melindassa
