### ISSUE TITLE
valikoiva puhumattomuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7564]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valikoiva puhumattomuus 

#### Ehdotettu termi ruotsiksi   

selektiv mutism 

#### Ehdotettu termi englanniksi   

selective mutism 

#### Vaihtoehtoiset termit ja ilmaisut   

selektiivinen mutismi 

#### Vastaava käsite muussa sanastossa   

LCSH : selective mutism 

#### Tarkoitusta täsmentävä selite   

Sosiaalisen vuorovaikutuksen häiriö, jossa henkilö osoittaa normaalia kielellistä kyvykkyyttä joissakin tilanteissa mutta on johdonmukaisesti puhumatta toisissa tilanteissa. 

#### Perustelut ehdotukselle   

YSA/YSO temaattinen ryhmä: 48,85 (en saanut lomaketta toimimaan kunnolla missään selaimessa)
Ehdotuksissa huomasin myös mutismin; tämä termi olisi tärkeä erottamaan juuri tämän osan ilmiöstä, jossa puhumattomuus on valikoivaa ja johtuu yleensä sosiaalisten tilanteiden pelosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pratlust och talängslan - om selektiv mutism 

**Ehdottajan organisaatio:** Åbo Akademi **Termiehdotus Fintossa:** [valikoiva puhumattomuus](http://finto.fi/yse/fi/page/Y507564)

**Comment by ilona-x** [comment]
FinMeSH: puhumattomuus KT valikoiva puhumattomuus http://www.yso.fi/onto/mesh/D009155

**Comment by ilona-x** [comment]
mutismi #7560

**Comment by mirmaid** [comment]
Lääketieteen termit: _elektiivinen mutismi, selektiivinen mutismi | lähinnä lapsilla ja nuorilla esiintyvä mielenterveyshäiriö, jolle on ominaista itsepintainen kieltäytyminen puhumasta yhdessä tai useammassa sosiaalisessa tilanteessa, vaikka kyky puhua ja ymmärtää puhetta on normaali_

mutismi: _puhumattomuus, mykkyys; vrt. kuuromykkyys_ 
akineettinen mutismi: _(usein aivokasvaimesta tai ‑vauriosta johtuva) kyvyttömyys liikkua ja puhua tahdonalaisesti_ 

https://fi.wikipedia.org/wiki/Mutismi

**Comment by mirmaid** [comment]
YSOssa on _puhekyvyttömyys_.

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa valikoiva puhumattomuus. Ohjaustermi selektiivinen mutismi.
