### ISSUE TITLE
atomivoimamikroskopia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7565]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

atomivoimamikroskopia 

#### Ehdotettu termi ruotsiksi   

atomkraftmikroskopi 

#### Ehdotettu termi englanniksi   

Atomic force microscopy 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mikroskopia](http://www.yso.fi/onto/yso/p16290) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D018625> 
LCSH : <http://id.loc.gov/authorities/subjects/sh94008704> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 
[09 Kemia](http://www.yso.fi/onto/yso/p26531) 
[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

http://www.solunetti.fi/fi/solubiologia/atomivoimamikroskopia/2/ 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda x 6 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Structural and dynamic properties of the solid-liquid interfaces studied by Molecular Dynamics simulations 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [atomivoimamikroskopia](http://finto.fi/yse/fi/page/Y507565)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/1580

**Comment by mirmaid** [comment]
GEO-ontologiassa: http://www.yso.fi/onto/gtk/GTK2015ID298

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa atomivoimamikroskopia.

**Comment by mariaforsen** [comment]
Sv. atomkraftsmikroskopi ET atomkraftmikroskopi
