### ISSUE TITLE
sydänlihastulehdus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7566]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sydänlihastulehdus 

#### Vastaava käsite muussa sanastossa   

FinMeSH : sydänlihastulehdus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/013421869 

#### Perustelut ehdotukselle   

- 

**Termiehdotus Fintossa:** [sydänlihastulehdus](http://finto.fi/yse/fi/page/Y507566)

**Comment by mirmaid** [comment]
LCSH: Myocarditis http://id.loc.gov/authorities/subjects/sh85089246

Melindassa 23 kertaa yksikössä, 2 kertaa monikossa.

**Comment by mariaforsen** [comment]
Sv. hjärtmuskelinflammation ET myokardit
