### ISSUE TITLE
spirokeetat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7567]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

spirokeetat 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/014338533 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [spirokeetat](http://finto.fi/yse/fi/page/Y507567)

**Comment by mirmaid** [comment]
FiMeSH: http://www.yso.fi/onto/mesh/D013142
LCSH: Spirochaeta http://id.loc.gov/authorities/subjects/sh88023340

**Comment by mirmaid** [comment]
Spirokeetat (Spirochaetes) ovat pitkänomaisia spiraalimaisia gramnegatiivisia bakteereita. https://fi.wikipedia.org/wiki/Spirokeetat

**Comment by mariaforsen** [comment]
Sv. spiroketer
