### ISSUE TITLE
fibriini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7568]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fibriini 

#### Perustelut ehdotukselle   

Ja samalla fibrinolyysi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/014338511 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [fibriini](http://finto.fi/yse/fi/page/Y507568)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D005337; http://www.yso.fi/onto/mesh/D005342
LCSH: Fibrin http://id.loc.gov/authorities/subjects/sh85048029, Fibrinolysis http://id.loc.gov/authorities/subjects/sh85048032

**Comment by mirmaid** [comment]
Fibriini on verihyytymän tukirankona toimiva säikeinen valkuaisaine, jota syntyy fibrinogeenista trombiinin vaikutuksesta. http://www.solunetti.fi/fi/patologia/fibriini/

3 kertaa Melindassa

**Comment by mirmaid** [comment]
Fibrinolyysi: verihyytymän liukenemiseen johtava fibriinin pilkkoutuminen joko veressä ja kudoksissa olevan entsyymin tai bakteerien tuottamien entsyymien avulla. https://www.terveyskirjasto.fi/terveysportti/tk.koti?p_teos=&p_artikkeli=ltt00852

4 kertaa Melindassa

**Comment by mariaforsen** [comment]
Sv.
-fibrin
-fibrinolys
