### ISSUE TITLE
matkailudokumentit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7570]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matkailudokumentit 

#### Perustelut ehdotukselle   

Ehdotettu SLM-sanastoon muutosta matkailuelokuvat  > matkailudokumentit. YSOssa ei toistaiseksi kumpaakaan termiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [matkailudokumentit](http://finto.fi/yse/fi/page/Y507570)

**Comment by mariaforsen** [comment]
Sv. turistfilmer > resefilmer

**Comment by YSA-kokous** [comment]
Jää termiehdotukseksi. Ei saanut huomattavaa kannatusta kokouksessa. Riittää, että on SLM:ssä.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/5420

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8652#issuecomment-816713382
- liitän tämän termin dokumenttiin, mikäli fiktiivinen niin käytetään road moviet, ei siis tarvi matkailudokumentteja -Samaa mieltä -Sopii minulle, jos päätetään näin niin road movie määritelmää pitää varmaan tarkentaa -> Käytetään (fiktiivisistä) elokuvista, joissa keskeisen kerronnan rakenteen muodostaa matkustaminen usein symbolisesti esitettynä pakenemisena yhteiskunnallisista sidonnaisuuksista vapaaseen elämään.
-> RAJATAANKO SIIS DOKUMENTTIELOKUVIIN

_- Selvitetään termin lopullinen muoto ja rajaus_

**Comment by mirmaid** [comment]
Otetaan matkailudokumentit, poistetaan matkailuelokuvat.

**Comment by mariaforsen** [comment]
Sv. resedokumentärer
