### ISSUE TITLE
lastenmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7574]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lastenmusiikki](http://www.yso.fi/onto/ysa/Y103017) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään käsite SLM sanastoon.  Siirretään SLM:ssä käsite "lastenlaulut" tämän alakäsitteeksi. 

#### Perustelut ehdotukselle   

Käytetty Melindassa muototerminä yli 800 kertaa.
SLM:ssä on jo monta muuta lasten- alkusta käsitettä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto  /  Finto / js

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Lastenlauluille lisäksi LT laulut

**Comment by mirmaid** [comment]
Ehdotuksen "yli 800 kertaa" viitannee siihen, että _lastenmusiikki_-termi esiintyy ilman sanastotunnusta, lajityyppi-kentässä se esiintyy 13 kertaa, mutta varmasti suurin osa myös ysoksi merkityistä lastenmusiikki-termeistä olisi oikeastaan lajityyppiä kuvaavia (yhteensä > 2000). Vähän yli puolessa kaikista lastenmusiikki-viitteistä on myös termi _lastenlaulut_ (jota yhteensä Melindassa lähes 13000 kertaa). Kun hakee niitä lastenmusiikki-termillä kuvailtuja aineistoja, joissa ei ole lastenlaulut-termiä (rajattuna musiikkiaineistoon) tulosjoukossa on lähinnä lasten soitonopetukseen tarkoitettuja aineistoja ja lastenlauluja.
