### ISSUE TITLE
kielennäytteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7579]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kielennäytteet](http://www.yso.fi/onto/ysa/Y102450) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään SLM sanastoon
skeema: Monografioiden lajityyppi- ja muototermit ??? 

#### Perustelut ehdotukselle   

alakäsitteeksi sopiva "murrenäytteet" on käytetty melindassa yli 200 kertaa. Voidaan käyttää sen asemesta myös "kielennäytteet", joka sopii useampiin tapauksiin. Tämä koskee siis aineistoja, jotka koostuvat näistä näytteistä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto / FInto / js

**Comment by mirmaid** [comment]
Tutkitaan lisää

**Comment by mariaforsen** [comment]
Sv. dialektprov (murrenäytteet)

**Comment by AuHo22** [comment]
Omaan korvaani paremmalta kuulostaisi kielinäyte vs. kielennäyte (kielen näyte) siis monikossa. Ei myöskään murteennäyte, vaan murrenäyte.

**Comment by mirmaid** [comment]
kielennäytteet KT kielinäytteet, ST murrenäytteet

**Comment by mirmaid** [comment]
Ohjaustermi myös YSOon, lisätäänkö murrenäytteet?

**Comment by YSO-kokous** [comment]
Otetaan YSOon erillisenä käsitteenä murrenäytteet.

**Comment by mariaforsen** [comment]
Sv. dialektprov
