### ISSUE TITLE
partituurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7581]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[partituurit](http://www.yso.fi/onto/ysa/Y103887) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään SLM sanastoon
skeema: Monografioiden lajityyppi- ja muototermit 

#### Perustelut ehdotukselle   

Käytetty Melindassa muototerminä yli 150 kertaa 

#### Ehdottajan organisaatio   

Kansalliskirjasto / Finto / js

**Comment by MUUSA-kokous** [comment]
Jätetään hautumaan muiden nuottiaineiston muototermien kanssa.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
Määritelmä:
Sellaisen nuottiaineiston muoto, joka koostuu graafisesta, symbolisesta tai sanallisesta nuottikirjoituksesta, ja johon sisältyy kokoonpanon kaikkien stemmojen sisältö. Nuottiaineistosta, joka edustaa teosta yhdelle soittimelle tai yhdelle soittajalle, käytetään termiä soolonuotti.
