### ISSUE TITLE
munanjohtimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7584]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

munanjohtimet 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Chlamydia trachomatis and reproductive health 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [munanjohtimet](http://finto.fi/yse/fi/page/Y507584)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D005187
LCSH: Fallopian tubes http://id.loc.gov/authorities/subjects/sh85046977

Kerran Melindassa

**Comment by mariaforsen** [comment]
Sv. äggledare
