### ISSUE TITLE
matalapaineglaukooma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7585]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matalapaineglaukooma 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Deep sclerectomy 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [matalapaineglaukooma](http://finto.fi/yse/fi/page/Y507585)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D057066

Ei Melindassa

**Comment by mirmaid** [comment]
Lääketieteen termit: _matalapaineglaukooma, normaalipaineglaukooma | tila jossa on glaukoomalle ominaisia papilli- ja näkökenttämuutoksia, vaikka paine ei ylitä turvallisena pidettyä tasoa_

**Comment by mariaforsen** [comment]
Sv. lågtrycksglaukom ET normaltrycksglaukom
