### ISSUE TITLE
tiaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7587]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tiaiset](http://www.yso.fi/onto/ysa/Y104593) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tiaiset (heimo) - Paridae

Ehkä riittää YSOssa, että lajit ovat heimon alakäsitteitä. 
YSOsta puuttuvat seuraavat Suomessa esiintyvät heimoon kuuluvat lajit: 
- viitatiainen - Poecile palustris 
- töyhtötiainen - Lophophanes cristatus 

#### Perustelut ehdotukselle   

Heimoon kuuluvat mm. suvut, joiden lajeista YSOssa on nyt:
- hömötiaiset - Poecile, johon kuuluvat lajit hömötiainen - Poecile montanus ja lapintiainen - Poecile cinctus 
- kuusitiaiset - Periparus, johon kuuluu laji kuusitiainen - Periparus ater
- sinitiaiset - Cyanistes, johon kuuluu laji sinitiainen - Cyanistes caeruleus
- talitiaiset - Pardus, johon kuuluu talitiainen - Pardus major
https://laji.fi/taxon/MX.34530 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan uusina termeinä ainakin viitatiainen ja töyhtötiainen (käytetty Melindassa)

**Comment by mirmaid** [comment]
LCSH-vastine pitäisi varmaan olla Paridae? Muuten ei mielestäni tarvita muutosta, koska tiaiset on vain heimon nimi. (& lisätään puuttuvat lajit)

**Comment by YSA-kokous** [comment]
Otetaan sanastoon viitatiainen ja töyhtötiainen. Korjataan tiaiset-käsitteen linkitys.

**Comment by mariaforsen** [comment]
Sv. 
-entita
-tofsmes
