### ISSUE TITLE
kuolevaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7588]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuolevaisuus](http://www.yso.fi/onto/ysa/Y189699) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö tarkentaa suomi/ruotsi? 

#### Perustelut ehdotukselle   

Ei pysy nykyisellään selkeästi erillään kuolleisuus-termistä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Olisiko se sitten kuolevaisuus (filosofia)/dödlighet (filosofi)? On nyt siinä ryhmässä. Termille kuolleisuus voisi muuten varmaan lisätä KT mortaliteetti? On Kielit. sanak.

**Comment by YSA-kokous** [comment]
Muutetaan muotoon "kuolvaisuus (filosofia)", tälle ohjaustermiksi "kuolevaisuus (uskonto)".
Lisäksi: mortaliteetti KÄYTÄ kuolleisuus.
