### ISSUE TITLE
piileväanalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7589]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

piileväanalyysi 

#### Ehdotettu termi ruotsiksi   

kiselalganalys 

#### Ehdotettu termi englanniksi   

diatom analysis 

#### Ehdotettu yläkäsite YSOssa (LT)   

[analyysimenetelmät](http://www.yso.fi/onto/yso/p6085) 

#### Assosiatiiviset (RT)   

[siitepölyanalyysi](http://www.yso.fi/onto/yso/p20619) 

#### Perustelut ehdotukselle   

Vastaava biologinen iänmääritysmenetelmä siitepölyanalyysi on jo YSOssa
eng. termin lähde:  https://doi.org/10.1016/0305-4403(88)90057-X 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 
[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. 003353493 Melindassa aiheena 38 kertaa. 

**Ehdottajan organisaatio:** Kansalliskirjasto / Finto **Termiehdotus Fintossa:** [piileväanalyysi](http://finto.fi/yse/fi/page/Y507589)

**Comment by mirmaid** [comment]
MAO-ontologiassa http://www.yso.fi/onto/mao/p4807

**Comment by mariaforsen** [comment]
Sv. diatoméanalys ET kiselalganalys

**Comment by YSA-kokous** [comment]
Hyväksytään.
