### ISSUE TITLE
subwooferit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#759]
#### Ehdotettu termi suomeksi

subwooferit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/ysa/ryhma_45)
#### Lähde

Lähde: http://carelia.scp.fi/~it96jule/kaiutin/docs/subwoofer.htm
#### Käsitteen määritelmä

Kokoäänialueen kaiuttimien lisäksi on saatavissa niin sanottuja subwoofereita eli lisäbassoja. Niiden tarkoitus on toistaa vain matalimpia ääniä

**Luontipäivämäärä:** 04.03.2002

**Muokkauspäivämäärä:** 4.3.2002, 16.12.2008

**Voyager-id:** 118068

**Termiehdotus Fintossa:** [subwooferit](http://finto.fi/yse/fi/page/Y318068)

**Comment by henriyli** [comment]
Käsite on lisätty YSAan 4.6.2014: http://www.yso.fi/onto/ysa/Y199009
