### ISSUE TITLE
elinikäinen oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7590]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elinikäinen oppiminen](http://www.yso.fi/onto/ysa/Y111184) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

> jatkuva oppiminen 

#### Perustelut ehdotukselle   

Palaute: Etsiskelin asiasanoja opinnäytetyöhöni ja kiinnitin huomiota, että jatkuva oppiminen on ohjaustermi Elinikäiseen oppimiseen. Viime vuosina tässä on kuitenkin tapahtunut käsitteen muutos siten, että jatkuva oppiminen on käytettävä termi ja elinikäistä oppimista pitäisi välttää. Tämä muutos onkin nähtävillä tutkimuskirjallisuudessa ja muun muassa eri ministeriöiden selvityksissä. Onko asiasanaan tulossa muutos, joka ottaisi tämän muutoksen huomioon?

**Comment by mirmaid** [comment]
https://minedu.fi/jatkuva-oppiminen

Google 61500/87300

**Comment by mariaforsen** [comment]
Sv. kontinuerligt lärande? 
SAO: livslångt lärande

**Comment by YSA-kokous** [comment]
Ei koettu tarvetta muutokselle.
