### ISSUE TITLE
fisteli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7591]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fisteli 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Surgical treatment of Crohn's disease 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [fisteli](http://finto.fi/yse/fi/page/Y507591)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D005402
LCSH: Fistula: http://id.loc.gov/authorities/subjects/sh85048892
https://fi.wikipedia.org/wiki/Fisteli

Melindassa 11 kertaa yksikössä, 2 kertaa monikossa.

**Comment by mariaforsen** [comment]
Sv. fistel

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
