### ISSUE TITLE
tamoxifeeni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7592]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tamoxifeeni 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Seven shades of tamoxifen resistance 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tamoxifeeni](http://finto.fi/yse/fi/page/Y507592)

**Comment by mirmaid** [comment]
LCSH: Tamoxifen: http://id.loc.gov/authorities/subjects/sh85132219
FinMeSH: tamoksifeeni http://www.yso.fi/onto/mesh/D013629
https://fi.wikipedia.org/wiki/Tamoksifeeni

7 viitettä Melindassa (tamoksifeeni)

**Comment by mirmaid** [comment]
tamoksifeeni KT tamoxifeeni

**Comment by mariaforsen** [comment]
Sv. tamoxifen
