### ISSUE TITLE
munuaisaltaan laajentuma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7593]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

munuaisaltaan laajentuma 

#### Vastaava käsite muussa sanastossa   

FinMeSH : pyelektasia 

#### Perustelut ehdotukselle   

Lisäksi ureteroseele 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Prenatally detected hydronephrosis 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [munuaisaltaan laajentuma](http://finto.fi/yse/fi/page/Y507593)

**Comment by mirmaid** [comment]
FinMeSH: ureteroseele http://www.yso.fi/onto/mesh/D014518
LCSH: Ureterocele http://id.loc.gov/authorities/subjects/sh85141371

**Comment by mirmaid** [comment]
FinMeSH: pyelektasia http://www.yso.fi/onto/mesh/D058536

Googella ei juuri suomenkielisiä viitteitä tällä muodolla, _munuaisaltaan laajentuma_ > 2000 tulosta.

**Comment by mariaforsen** [comment]
Sv.
-urinledarbråck
-pyelektasi

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa munuaisaltaan laajentuma. Ohjaustermeiksi ureteroseele ja pyelektasia.

**Comment by ilona-x** [comment]
Kyseessä kuitenkin ilmeisesti 2 erillistä ehdotusta. Mielestäni nämä ehdotukset, joissa monta termiä samassa ehdotuksessa, ovat hiukan hankalia, kun aina ei tiedä, onko kyse ehdotetun päätermin ohjaustermistä vai onko samaan ehdotukseen yhdistetty useampia erillisiä käsite-ehdotuksia.

Eli siis ureteroseele ei ole ehdotetun termin ohjaustermi.

**Comment by mariaforsen** [comment]
Sv. 
-urinledarbråck ET uretärbråck =ureteroseele/virtsanjohtimen laajentuma/virtsanjohdinlaajentuma
-pyelektasi =pyelektasia/munuaisaltaan laajentuma

**Comment by mirmaid** [comment]
Erikseen siis 

- ureteroseele
- munuaisaltaan laajentuma
