### ISSUE TITLE
vaskuliitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7594]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaskuliitit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Anca-assosiated vasculitis 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vaskuliitit](http://finto.fi/yse/fi/page/Y507594)

**Comment by mirmaid** [comment]
FinMeSH: verisuonitulehdus http://www.yso.fi/onto/mesh/D014657
LCSH: Vasculitis http://id.loc.gov/authorities/subjects/sh85142363
https://fi.wikipedia.org/wiki/Vaskuliitti

Melindassa 29 kertaa vaskuliitti, 25 kertaa verisuonitulehdus

**Comment by mariaforsen** [comment]
Sv. kärlinflammation, vaskulit, blodkärlsinflammation

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa vaskuliitit, ohjaustermiksi verisuonitulehdus. Vaskuliitti käytetympi muoto kuin verisuonitulehdus.

**Comment by mariaforsen** [comment]
Sv. vaskuliter ET kärlinflammationer, blodkärlsinflammationer
