### ISSUE TITLE
kloprostenoli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7595]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kloprostenoli 

#### Ehdotettu termi englanniksi   

cloprostenol 

#### Perustelut ehdotukselle   

Kloprostenoli (C22H29ClO6) on prostaglandiinianalogeihin kuuluva orgaaninen yhdiste. Yhdistettä käytetään eläinlääketieteessä sekä hedelmättömyyden hoitamiseen että tiineyden keskeyttämiseen.
https://fi.wikipedia.org/wiki/Kloprostenoli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-10-6646-7 

**Termiehdotus Fintossa:** [kloprostenoli](http://finto.fi/yse/fi/page/Y507595)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D003008

**Comment by mariaforsen** [comment]
Sv. kloprostenol
