### ISSUE TITLE
ulkoisvaikutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7596]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ulkoisvaikutukset 

#### Ehdotettu termi englanniksi   

externality 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vaikutukset](http://www.yso.fi/onto/yso/p795) 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : <http://tieteentermipankki.fi/wiki/Taloustiede:ulkoisvaikutus> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Tarkoitusta täsmentävä selite   

Definition: Tuotannon tai kulutuksen (kielteinen eli negatiivinen tai myönteinen eli positiivinen) sivuvaikutus, josta ei suoriteta maksua. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Agricultural goods and bads: Essays on agriculture and environmental externalitieshttps://helda.helsinki.fi/handle/10138/305627 

#### Perustelut ehdotukselle   

Tarvitaan väitöskirjan kuvailuun 

**Termiehdotus Fintossa:** [ulkoisvaikutukset](http://finto.fi/yse/fi/page/Y507596)

**Comment by mirmaid** [comment]
Melindassa 12 kertaa monikossa, 6 kertaa yksikössä.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ulkoisvaikutus

**Comment by mariaforsen** [comment]
Sv. externa effekter ET externaliteter

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
