### ISSUE TITLE
afro

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7597]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

afro 

#### Ehdotettu termi ruotsiksi   

afro 

#### Tarkoitusta täsmentävä selite   

Yleisnimitys erilaisille afrikkalaisille maailmanmusiikkityyleille 

#### Perustelut ehdotukselle   

Tarvitaan SLM-sanastoon. Termi on ollut Musassa. Termin alakäsitteet benga, juju, makossa, mbalax, mbaqanga, soukous ovat jo SLM-sanastossa, mutta myös tälle yleisemmälle termille on tarvetta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarkemmin määrittelemättömän tai sekasisältöisen afrikkalaisen maailmanmusiikin kuvailuun, esim. Angelique Kidjo. 

**Ehdottajan organisaatio:** Kirjastopalvelu

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5542

**Comment by mariaforsen** [comment]
Ei taida olla korrektia käyttää sellaista nimitystä ja tapaa lajitella noita tyylejä. Vanhentunut ja syystä poistettu.

**Comment by YSA-kokous** [comment]
Asia on kertaalleen jo käsitelty. Käsite on päätetty poistaa sanastosta. Ei tarvetta tehdä muutoksia eli ei oteta käsitettä sanastoon. Ks. https://github.com/Finto-ehdotus/YSE/issues/5542
