### ISSUE TITLE
korva-, nenä- ja kurkkutautioppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7598]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[korva-, nenä- ja kurkkutautioppi](http://www.yso.fi/onto/ysa/Y102707) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT rinologia, otologia, laryngologia 

#### Perustelut ehdotukselle   

Merkityksiltään sama

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
