### ISSUE TITLE
Kubanin alue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7599]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kubanin alue 

#### Ehdotettu termi ruotsiksi   

Kuban 

#### Ehdotettu termi englanniksi   

Kuban 

#### Vaihtoehtoiset termit ja ilmaisut   

Kubanin oblasti 
Kubanskaâ oblast’ 

#### Vastaava käsite muussa sanastossa   

wikidata : https://www.wikidata.org/wiki/Q10555398 
LCSH : <http://id.loc.gov/authorities/subjects/sh2004003133> 

#### Tarkoitusta täsmentävä selite   

Alue Etelä-Venäjällä 

#### Perustelut ehdotukselle   

Esiintyy Melindassa >10 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/F/4HKGGHE4VNK36VF3XBP4LUPVFRKK85FDLR3RV9EULHT54ET1UA-00800?func=find-acc&acc_sequence=020003487 

**Ehdottajan organisaatio:** Kansalliskirjasto / Finto **Termiehdotus Fintossa:** [Kubanin alue](http://finto.fi/yse/fi/page/Y507599)

**Comment by mirmaid** [comment]
Käytetty Melindassa sekä _Kuban_, että _Kubanin alue_. Wikipedia: _Kuban (alue)_. Venäjällä on myös samanniminen joki.

YSOssa on joitakin x:n alue -tyyppisiä Venäjän alakäsitteitä, mutta ne vastaavat nykyisiä Venäjän alueita (oblast). Myös Kuban on ollut vastaava alue keisarikunnan aikana, nykyään se vastaa Krasnodarin aluepiiriä ja joitakin sen lähialueita. https://en.wikipedia.org/wiki/Kuban

**Comment by ilona-x** [comment]
LCSH: Kubanʹ (Russia : Region) http://id.loc.gov/authorities/subjects/sh2004003133
Tuon perusteella ehkä sitten Kuban (alue), vaikka aluetta ei kai olekaan käytetty aiemmin sulkutarkenteena, niin eroaisi paremmin noista nykyisistä oblasteista.

**Comment by mirmaid** [comment]
Kubanin alue KT Kuban (alue) ja määritelmä.

**Comment by YSO-kokous** [comment]
PÄÄTÖS: YSO-kokous kannattaa mirmaidin ehdotusta.
