### ISSUE TITLE
todellisuuspohjaiset televisiosarjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7601]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

todellisuuspohjaiset televisiosarjat 

#### Ehdotettu termi ruotsiksi   

verklighetsbaserade tv-serier 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

#### Tarkoitusta täsmentävä selite   

Fiktiivinen televisiosarja, joka pohjautuu todellisiin tapahtumiin. 

#### Perustelut ehdotukselle   

Vrt. 'todellisuuspohjaiset elokuvat' ja 'todellisuuspohjaiset teokset' 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi HBO:n minisarja Chernobyl (2019) ja kotimainen sarja Invisible heroes (2019) (jos jälkimmäinen ilmestyy DVD:nä). 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [todellisuuspohjaiset televisiosarjat](http://finto.fi/yse/fi/page/Y507601)

**Comment by mirmaid** [comment]
Myös SLM

**Comment by YSA-kokous** [comment]
Odotetaan SLM:n kantaa ja toimitaan sen mukaan.

**Comment by mirmaid** [comment]
KAUNO-ryhmä kannattaa hyväksymistä.

**Comment by mirmaid** [comment]
todellisuuspohjaiset sarjat YK televisiosarjat

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
