### ISSUE TITLE
taiteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7602]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taiteet](http://www.yso.fi/onto/ysa/Y156860) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termiltä puuttuu ryhmän numero ja nimi! 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätty.
