### ISSUE TITLE
urpiainen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7603]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

urpiainen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

013293076 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [urpiainen](http://finto.fi/yse/fi/page/Y507603)

**Comment by mirmaid** [comment]
pikkukäpylintu, kirjosiipikäpylintu (013288975, 013289011)
taviokuurna (013289007)
isokäpylintu (013316545 &urpiainen)

**Comment by mariaforsen** [comment]
Sv. 
-gråsiska
-mindre korsnäbb
-bändelkorsnäbb
-tallbit
-större korsnäbb

**Comment by PaiviLipsanen** [comment]
yläkäsite: peipot (heimo)
https://laji.fi/taxon/MX.36351
