### ISSUE TITLE
hypertrofinen kardiomyopatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7605]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hypertrofinen kardiomyopatia 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Alterations in myocardial function and electrocardiology in hypertrophic cardiomyopathy 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hypertrofinen kardiomyopatia](http://finto.fi/yse/fi/page/Y507605)

**Comment by mariaforsen** [comment]
Sv. hypertrofisk kardiomyopati ET HCM
