### ISSUE TITLE
tau-proteiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7606]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tau-proteiinit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tau pathology : secretion and internalization as the key for understanding protein propagation 

**Termiehdotus Fintossa:** [tau-proteiinit](http://finto.fi/yse/fi/page/Y507606)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D016875
https://fi.wikipedia.org/wiki/Tau_(proteiini)

**Comment by mariaforsen** [comment]
Sv. tau-proteiner ET tauproteiner
