### ISSUE TITLE
pääkaupunkiseutu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7607]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pääkaupunkiseutu](http://www.yso.fi/onto/ysa/Y98385) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana monikkoon. 

#### Perustelut ehdotukselle   

Kyse ei ole maantieteellisestä termistä, joka viittaisi nimenomaan Suomen pääkaupunkiseutuun (se on sanastossa erikseen: "Helsingin seutu" [https://finto.fi/yso-paikat/fi/page/p192353]), vaan yleistermistä. Vastaavat muut termit ovat monikossa, esim. "kaupunkiseudut" [https://finto.fi/yso/fi/page/p6390] ja "syrjäseudut" [http://www.yso.fi/onto/yso/p7142]. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Helsingin seutu otettu sanastoon v. 2013

**Comment by mariaforsen** [comment]
Sv. huvudstadsregioner, huvudstadsområden

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4kaupunkiseutu

https://fi.wikipedia.org/wiki/Helsingin_seutu

**Comment by YSA-kokous** [comment]
Tutkitaan lisää. Melindassa käytetty paljon, jokunen näistä viittaa muuhunkin kuin Suomen pääkaupunkiseutuun. Pohdittavaksi: YSO-paikkoihin YSOn sijaan?

**Comment by ilona-x** [comment]
Pääkaupunkiseutu, Suur-Helsinki ja Helsingin seutu http://www.kielitoimistonohjepankki.fi/ohje/403

**Comment by jtuohini** [comment]
Termi monikkoon, koska se viittaa useisiin pääkaupunkiseutuihin ja on siksi yleistermi. Analogia: [kaupunkiseudut]([url](http://www.yso.fi/onto/yso/p6390)).

**Comment by jtuohini** [comment]
Ei YSO-paikkoihin, jos asiasanan on tarkoitus toimia nimenomaan asiasanana ja viitata pääkaupunkiseutuihin yleensä. Jos tarkoitus on käyttää termiä puhtaasti paikanmäärenä, viitaten vain Helsingin seutuun, niin sitten koko _pääkaupunkiseutu_-asiasana pois sanastosta ja sama isolla kirjoitettuna KT-muodoksi _Helsingin seutu_ -asiasanalle.

**Comment by ilona-x** [comment]
Tässä vielä lainauksia tuosta yllä linkkaamastani Kielitoimiston ohjepankista:

"Ilmaus **pääkaupunkiseutu** voidaan rajata kaikkein täsmällisimmin vaikka se ei ole erisnimi, vaan kirjoitetaan pienellä alkukirjaimella. Kuntaliitossa ja muissa **virallisissa** kunnallisissa yhteyksissä pääkaupunkiseutu käsittää **neljä kaupunkia, Helsingin, Espoon, Kauniaisen ja Vantaan**."

"Ilmaus **Helsingin seutu** voi olla yleiskielessä väljempi kuin pääkaupunkiseutu. **Viranomaiskielessä** silläkin on tarkka tarkoite. Jos esim. tilastoissa esiintyy Helsingin seutu, mukaan on laskettu **Helsingin kaupungin lisäksi 11 kuntaa, nimittäin Espoo, Kauniainen, Vantaa, Kirkkonummi, Vihti, Nurmijärvi, Tuusula, Kerava, Järvenpää, Hyvinkää ja Sipoo.** "

**Comment by jtuohini** [comment]
Mutta mistä voi päätellä, että YSO-termi on varattu tarkoittamaan samaa kuin mihin Kielitoimiston ohjepankki viittaa? Ruotsin pääkaupunkiseutu? Suur-Lontoo? Seikka pitäisi ilmaista sanastossa itsessään.

**Comment by mariaforsen** [comment]
Jos todella halutaan pitää "pääkaupunkiseutu" sanastossa ja rajata sen vain suomeen siihen pitäisi varmaan lisätä (Suomi) tai (Helsinki). Muutenhan se voi tosiaankin viitata mihin tahansa, huom. YSOssahan termit ovat myös ruotsiksi ja englanniksi.

**Comment by LeKorsu** [comment]
Kävisikö muista kuin Suomen pääkaupunkiseudusta uutena terminä metropolialueet, vaikka ohjaustermi on metropolit KÄ suurkaupungit? Se ei tarkkaan ottaen tarkoita samaa kuin nimenomaan ulkomaiset pääkaupunkiseudut, eli metropolialueet voi olla muitakin kuin pääkaupunkiseutuja. Tällöin voitaisiin pitää pääkaupunkiseutu (Suomi) yksikössä.

Jos yllämainittu ei saa kannatusta (esim. koska kaikki pääkaupungit eivät ole suurkaupunkeja), peukku Marian ehdotukselle sulkutarkenteesta.

**Comment by ilona-x** [comment]
metropolialueet on YSOssa http://www.yso.fi/onto/yso/p24768
Myös yhdistelmä pääkaupungit & kaupunkiseudut voisi olla joissain tapauksissa riitävä

**Comment by YSO-kokous** [comment]
Muutetaan termimuodoksi "pääkaupunkiseutu (Suomi)". Jätetään käsite YSOon eli ei YSO-paikkoihin, koska ei ole erisnimi.
