### ISSUE TITLE
forró

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7608]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

forró 

#### Ehdotettu termi ruotsiksi   

forró 

#### Ehdotettu termi englanniksi   

forró 

#### Vaihtoehtoiset termit ja ilmaisut   

forro 

#### Vastaava käsite muussa sanastossa   

wikidata : https://www.wikidata.org/wiki/Q586110 
LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026812> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

koillisbrasilialainen musiikkityyli 

#### Perustelut ehdotukselle   

Ehdotetaan lisättäväksi SLM genresanastoon   vrt. LCGFT
käytetty Melindassa 8 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

melinda.kansalliskirjasto.fi/byid/015328874 

**Ehdottajan organisaatio:** Kansalliskirjasto / Finto **Termiehdotus Fintossa:** [forró](http://finto.fi/yse/fi/page/Y507608)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT latinalaisamerikkalainen populaarimusiikki; tanssimusiikki

**Comment by YSO-kokous** [comment]
Otetaan käsite myös YSOon.
