### ISSUE TITLE
conga (tanssit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7609]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[conga (tanssit)](http://www.yso.fi/onto/ysa/Y214769) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ehdotetaan lisättäväksi SLM sanastoon muodossa "congat"
YK "latinalaisamerikkalainen populaarimusiikki" http://urn.fi/URN:NBN:fi:au:slm:s1007
vrt "conga"  http://urn.fi/urn:nbn:fi:au:seko:00238
vrt "conga (tanssit)" yso: 

#### Perustelut ehdotukselle   

melinda.kansalliskirjasto.fi/byid/015328973 

#### Ehdottajan organisaatio   

Kansalliskirjasto / Finto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa yksikössä: _conga_.

**Comment by mirmaid** [comment]
YK latinalaisamerikkalainen populaarimusiikki, tanssimusiikki
Muusa laatii määritelmän.

**Comment by jtuohini** [comment]
LCGFT-siltaus: [**Conga music**](http://id.loc.gov/authorities/subjects/sh88006161)

**Comment by mirmaid** [comment]
YSOon? (Ylläoleva linkki LCSH, ei löydy LCGFT:stä)

**Comment by YSO-kokous** [comment]
Tarkennus: YSOn kannalta ehdotus koskee siis congaa musiikkityylinä, ei tanssina. YSOssa on jo "conga (tanssit)". YSOssa on myös congarumpu. Näin ollen musiikkityylille tarvittaisiin varmaankin sulkutarkenne. Odotetaan vielä Muusan kommenttia tähän.

**Comment by MUUSA-kokous** [comment]
Sulkutarkenne YSOon: conga (musiikki).
Määritelmä: Kuubasta lähtöisin oleva musiikkityyli

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.

**Comment by mariaforsen** [comment]
Sv. conga (musik)
