### ISSUE TITLE
aivojen syvien osien sähköstimulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7613]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aivojen syvien osien sähköstimulaatio 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Deep brain stimulation of the subthalamic nucleus... 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aivojen syvien osien sähköstimulaatio](http://finto.fi/yse/fi/page/Y507613)

**Comment by mirmaid** [comment]
FinMeSH: aivojen syvien osien sähköstimulaatio, http://www.yso.fi/onto/mesh/D046690

**Comment by mirmaid** [comment]
Melindassa 8 x syväaivostimulaatio, kerran syväaivostimulaatiohoito, 4 x aivojen syvien osien sähköstimulaatio, 4 x DBS

**Comment by mirmaid** [comment]
Google: 2580/240/1150
DBS-hoito 787
https://fi.wikipedia.org/wiki/DBS-hoito

**Comment by mariaforsen** [comment]
Sv. djup hjärnstimulering ET DBS-behandling

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa syväaivostimulaatio, koska on käyttäjäystävällinen. _Ohjaustermeiksi aivojen syvien osien sähköstimulaatio, syväaivostimulaatiohoito_ ja _DBS-hoito_.
