### ISSUE TITLE
satamapäälliköt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7614]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

satamapäälliköt 

#### Ehdotettu termi ruotsiksi   

hamnkaptener 

#### Ehdotettu termi englanniksi   

harbourmasters 

#### Vaihtoehtoiset termit ja ilmaisut   

satamakapteenit 
satamamestarit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[merikapteenit](http://www.yso.fi/onto/yso/p12082) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85058833> 
Wikidata : https://www.wikidata.org/wiki/Q1489454 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

Kyseisen ammatin edustajien toimijakuvailusta ja heitä käsittelevän aineiston kuvailusta puuttuu tämä täsmällinen termi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://digi.kansalliskirjasto.fi/sanomalehti/binding/1756005/articles/78436876?page=5 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [satamapäälliköt](http://finto.fi/yse/fi/page/Y507614)

**Comment by mirmaid** [comment]
Kerran Melindassa, Google > 4000

**Comment by mariaforsen** [comment]
Sv. hamnkaptener ET hamnchefer

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus. Tutkitaan vielä yläkäsitettä.
