### ISSUE TITLE
akaasia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7615]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[akaasia](http://www.yso.fi/onto/ysa/Y123304) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Monikko? 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Akaasiat 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by PaiviLipsanen** [comment]
Acacia (suku) - akaasiat
https://finto.fi/kassu/fi/page/k988
pajuakaasia (Acacia longifolia)
https://laji.fi/taxon/MX.4985853
On myös olemassa 
Robinia (suku) - valeakaasiat
valkovaleakaasia (Robinia pseudoacacia)

**Comment by YSA-kokous** [comment]
Muutetaan muotoon akaasiat, otetaan ohjaustermiksi akasiat. Tällä tavalla kirjoitettiin aiemmin.
