### ISSUE TITLE
skandium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7616]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

skandium 

#### Perustelut ehdotukselle   

& bauksiitti 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Metal(IV) phosphate based functional materials for selectively harvesting rare-earth elements from bauxite residue 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [skandium](http://finto.fi/yse/fi/page/Y507616)

**Comment by mirmaid** [comment]
+ neodyymi ja dysprosium (väitöskirja Junhua Xu)

**Comment by mirmaid** [comment]
LCSH: Scandium, Neodymium, Dysprosium, Bauxite

**Comment by mariaforsen** [comment]
Sv. 
-skandium
-neodym
-dysprosium
-bauxit
