### ISSUE TITLE
Pakolaisten oikeusasemaa koskeva yleissopimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7617]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pakolaisten oikeusasemaa koskeva yleissopimus](http://www.yso.fi/onto/ysa/Y183940) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mielellään muodossa: Pakolaisten oikeusasemaa koskeva yleissopimus (1951)

Vähintään kuitenkin seliteteksti, tässä Wikipediasta muokattu: Yhdistyneiden kansakuntien vuonna 1951 laatima sopimus pakolaisten oikeudellisesta asemasta. 

#### Perustelut ehdotukselle   

On olemassa myös muita sopimuksia, tarvitaan jotain erottamaan muista 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSA-kokous** [comment]
Ei koettu tarvetta muutoksille.
