### ISSUE TITLE
Yleissopimus lapsen oikeuksista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7618]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Yleissopimus lapsen oikeuksista](http://www.yso.fi/onto/ysa/Y106180) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mielellään muodossa: Yleissopimus lapsen oikeuksista (1989)

Tarvitaan kuitenkin jonkilainen selitys, tässä Wikipediasta muokattu: Yhdistyneiden kansakuntien vuonna 1989 tekemä sopimus alle 18-vuotiaiden ihmisten täysimääräisten ihmisoikeuksien takaamiseksi. 

#### Perustelut ehdotukselle   

On olemassa muitakin sopimuksia, täytyy pystyä erottamaan muista 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Onko siis muita samannimisiä sopimuksia?

**Comment by YSA-kokous** [comment]
Tietoomme ei ole muita yleissopimuksia lapsen oikeuksista. Ei muutosta.
