### ISSUE TITLE
tiiviin aineen fysiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7619]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tiiviin aineen fysiikka 

#### Perustelut ehdotukselle   

+ kvantti-informaatio TAI kvantti-informaatioteoria
+ holografinen periaate
+ lomittuminen https://fi.wikipedia.org/wiki/Lomittuminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Holographic aspects of quantum information theory and condensed matter theory 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tiiviin aineen fysiikka](http://finto.fi/yse/fi/page/Y507619)

**Comment by mirmaid** [comment]
LCSH: Quantum entanglement, Condensed matter

**Comment by mariaforsen** [comment]
Sv. kondenserade materiens fysik ET kondenserad materiefysik

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
