### ISSUE TITLE
neutriino-oskillaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7621]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

neutriino-oskillaatio 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Neutrino_oscillation 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Neutrino masses and oscillations in theories beyond the standard model 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [neutriino-oskillaatio](http://finto.fi/yse/fi/page/Y507621)

**Comment by mirmaid** [comment]
Myös _Numerical studies on neutrino oscillation physics in long baseline experiments_

**Comment by mariaforsen** [comment]
Sv. neutrinooscillation

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
