### ISSUE TITLE
vesihöyry

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7622]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vesihöyry 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Modelling of arctic stratospheric ozone and water vapour and their changes 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vesihöyry](http://finto.fi/yse/fi/page/Y507622)

**Comment by mirmaid** [comment]
LCSH: Water vapor, Atmospheric
24 kertaa Melindassa

**Comment by mariaforsen** [comment]
Sv. vattenånga

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mirmaid** [comment]
Tutkitaan vielä höyry/kaasut.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus taas.
