### ISSUE TITLE
polaaripyörre

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7623]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

polaaripyörre 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Modelling of arctic stratospheric ozone and water vapour and their changes 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [polaaripyörre](http://finto.fi/yse/fi/page/Y507623)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Napapy%C3%B6rre
LCSH: Polar vortex
Melindassa 2 x napapyörre, kerran polaaripyörre.

**Comment by mariaforsen** [comment]
Sv. polarvirvel

**Comment by YSA-kokous** [comment]
Hyväksytään muodossa napapyörre. Termivariantit lähes yhtä suosittuja. Wikipediassa muodossa napapyörre. Ohjaustermiksi polaaripyörre.
