### ISSUE TITLE
tyynyjäkälät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7624]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tyynyjäkälät 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lost before found? On systematics and conservation of lichen genus Micarea Fr. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tyynyjäkälät](http://finto.fi/yse/fi/page/Y507624)

**Comment by mariaforsen** [comment]
Sv. dynlavar

**Comment by PaiviLipsanen** [comment]
https://laji.fi/taxon/MX.67037
