### ISSUE TITLE
termohydrauliikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7625]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

termohydrauliikka 

#### Vastaava käsite muussa sanastossa   

LCSH : Thermal hydraulics 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Thermal_hydraulics 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Modelling of JET and ITER reactor relevant plasma neutron source for neutronics calculation chain 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [termohydrauliikka](http://finto.fi/yse/fi/page/Y507625)

**Comment by mariaforsen** [comment]
Sv. termohydraulik

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
