### ISSUE TITLE
kvasihiukkaset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7627]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kvasihiukkaset 

#### Perustelut ehdotukselle   

+ vahva vuorovaikutus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Quasiparticle properties of nonequilibrium gluon plasma 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kvasihiukkaset](http://finto.fi/yse/fi/page/Y507627)

**Comment by mirmaid** [comment]
plasmonit

**Comment by mirmaid** [comment]
Myös Jet shape modification in Pb-Pb collisions at sqrt(sNN) = 2.76 TeV using two-particle correlations

- kvarkki-gluoni plasma?

**Comment by mirmaid** [comment]
Omana terminään siis myös _vahva vuorovaikutus_.

**Comment by mariaforsen** [comment]
Sv. 
-stark växelverkan 
-plasmoner 
-kvasipartiklar

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
