### ISSUE TITLE
vedenkestävyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7630]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vedenkestävyys 

#### Ehdotettu termi englanniksi   

water resistance 

#### Perustelut ehdotukselle   

Kestävyys-termin alakäsitteitä on muitakin vastaavia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pakkausmateriaalien vedenkestävyys. Julkaisu Cellulose nanopapers with improved preparation time, mechanical properties, and water resistance /Jatin Sethi. (978-952-62-2153-) 

**Ehdottajan organisaatio:** Kansalliskirjasto - kb **Termiehdotus Fintossa:** [vedenkestävyys](http://finto.fi/yse/fi/page/Y507630)

**Comment by mirmaid** [comment]
Sanastossa on _kosteudenkestävyys, vedenpitävyys_ ja _vettähylkivyys_.

**Comment by mariaforsen** [comment]
Sv. vattentålighet, vattenfasthet..? Näitä käytetään kyllä varmaan eri kontekstissa kuin vedenpitävyys/vattentäthet.

**Comment by YSA-kokous** [comment]
Ei erilliseksi käsitteeksi. Läheistä sanastoa jo YSOssa. Lisätään ohjaustermit:
vedenkestävyys KÄYTÄ kosteudenkestävyys
vedenkestävyys KÄYTÄ vedenpitävyys
