### ISSUE TITLE
Kanta-Häme

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7632]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kanta-Häme](http://www.yso.fi/onto/ysa/Y111261) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ohjaustermiksi "Lounais-Häme" 

#### Perustelut ehdotukselle   

Käytetty Melindassa yli 600 kertaa. 
Ohjausterminä myös Etelä-Häme. 
TAI tehdään uusi käsite  Lounais-Häme  RT Häme, Kanta-Häme, Päijät-Häme  
closeMatch  https://www.wikidata.org/wiki/Q11876298 

#### Ehdottajan organisaatio   

Kansalliskirjasto / Finto

**Comment by mirmaid** [comment]
Paljon käytetty Melindassa. https://fi.wikipedia.org/wiki/Lounais-H%C3%A4me

**Comment by YSO-kokous** [comment]
Otetaan Lounais-Häme erillisenä käsitteenä sanastoon.
