### ISSUE TITLE
fokusoidut ionisuihkut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7633]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Focused ion beams 

#### Ehdotettu termi suomeksi   

fokusoidut ionisuihkut 

#### Ehdotettu termi ruotsiksi   

fokuserad jonstråle 

#### Vaihtoehtoiset termit ja ilmaisut   

FIB 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2004007286> 
wikipedia : https://en.wikipedia.org/wiki/Focused_ion_beam 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Combining focused ion beam patterning and atomic layer deposition for nanofabrication 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa

Melinda: fokusoitu ionisuihkutekniikka x 1 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 
[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [fokusoidut ionisuihkut](http://finto.fi/yse/fi/page/Y507633)

**Comment by mariaforsen** [comment]
Sv. fokuserade jonstrålar

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mirmaid** [comment]
https://www.tekniikkatalous.fi/uutiset/maailman-pienin-aalto-maljakko-synnytti-elektroniikkaan-uuden-tuotantometodin/36818c17-223f-3421-931c-08533938fef6

Päätermiksi mahdollinen myös kohdistettu ionisuihku (KT myös suunnattu ionisuihku). Kaikkia vaihtoehtoja googlella vain muutaman kerran.
