### ISSUE TITLE
pneumokokki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7636]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pneumokokki](http://www.yso.fi/onto/ysa/Y112027) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi streptokokit? 

#### Perustelut ehdotukselle   

FinMeSH: pneumokokki LT streptokokki http://www.yso.fi/onto/mesh/D013296 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Korjattu.
