### ISSUE TITLE
sukaskärpäset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7637]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sukaskärpäset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pollination networks of the high arctic 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sukaskärpäset](http://finto.fi/yse/fi/page/Y507637)

**Comment by mirmaid** [comment]
& lapinvuokko

**Comment by mirmaid** [comment]
Laji.fi Muscidae & tunturilapinvuokko

**Comment by mariaforsen** [comment]
Sv. egentliga flugor (Muscidae) & fjällsippa

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
Otetaan sanastoon myös käsite lapinvuokko.

**Comment by mariaforsen** [comment]
Sv. 
-egentliga flugor 
-fjällsippa
