### ISSUE TITLE
SLM/fin sanaselityspelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7638]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM/fin sanaselityspelit 

#### Vaihtoehtoiset termit ja ilmaisut   

selityspelit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit](http://www.yso.fi/onto/yso/p6062) 

#### Assosiatiiviset (RT)   

[seurapelit](http://www.yso.fi/onto/yso/p28086) 

#### Perustelut ehdotukselle   

Alias-sarjan eri pelit, myös Pictionary 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Alias-sarjan eri pelit, myös Pictionary 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [SLM/fin sanaselityspelit](http://finto.fi/yse/fi/page/Y507638)

**Comment by mariaforsen** [comment]
Sv. ordförklaringsspel

**Comment by YSO-kokous** [comment]
Hyväksytään myös YSOon.
