### ISSUE TITLE
toimistotyöntekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7640]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toimistotyöntekijät](http://www.yso.fi/onto/ysa/Y104631) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kanslistit" 

#### Perustelut ehdotukselle   

"Kanslisti" on erittäin tavanomainen ilmaus, josta ei tällä hetkellä ole mitään viittausta sen sijaan käytettävään asiasanaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _kansliassa, virastossa tms. toimistotöitä tekevä (toimi)henkilö_

**Comment by YSA-kokous** [comment]
Hyväksytään ehdotus.
