### ISSUE TITLE
Akujärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7641]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Akujärvi 

#### Perustelut ehdotukselle   

Järvi ja kylä Inarin kunnassa, Ivalon koillispuolella. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallislehtiviitteiden tekemisessä Artoon. 

**Ehdottajan organisaatio:** Rovaniemen kaupunginkirjasto, Lappi-osasto **Termiehdotus Fintossa:** [Akujärvi](http://finto.fi/yse/fi/page/Y507641)

**Comment by mirmaid** [comment]
Kylä auktorisoitu. Inarin kunnan alueella on useampia Akujärvi-nimisiä järviä, joten jos järven nimeä tarvitaan erikseen (aineisto käsittelee nimenomaan järveä), pitää auktorisoida tarkempi nimi.
