### ISSUE TITLE
Intiantiikeri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7642]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Intiantiikeri 

#### Ehdotettu termi ruotsiksi   

Bengalisk tiger 

#### Ehdotettu termi englanniksi   

Bengal tiger 

#### Vaihtoehtoiset termit ja ilmaisut   

Panthera tigris tigris, bengalintiikeri 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kissaeläimet](http://www.yso.fi/onto/yso/p864) 

#### Assosiatiiviset (RT)   

[amurintiikeri](http://www.yso.fi/onto/yso/p25578) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : Intiantiikeri 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Amurintiikeri on YSO:ssa ja Intiantiikeri on yleisin tiikerin alalaji. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

MTV3 ohjelma "Say what", osa 2  	https://rtva.kavi.fi/program/details/program/26595707 

**Ehdottajan organisaatio:** KAVI **Termiehdotus Fintossa:** [Intiantiikeri](http://finto.fi/yse/fi/page/Y507642)

**Comment by mariaforsen** [comment]
Sv. bengalisk tiger ET indisk tiger, kungstiger
