### ISSUE TITLE
Helsingin keskuspuisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7644]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Helsingin keskuspuisto 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

An integrative perspective on visitor spatial behaviour in urban green spaces 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Helsingin keskuspuisto](http://finto.fi/yse/fi/page/Y507644)

**Comment by mariaforsen** [comment]
Sv. Helsingfors centralpark
