### ISSUE TITLE
väylänpito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7645]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väylänpito](http://www.yso.fi/onto/ysa/Y156879) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

> vesiväylänpito, jos on tarkoitus rajata tähän 

#### Perustelut ehdotukselle   

tienpito ja radanpito erikseen, ruotsiksi farledsunderhåll 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Muutetaan muotoon vesiväylänpito, ohjaustermiksi väylänpito.
