### ISSUE TITLE
MIMO-tekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7646]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

MIMO-tekniikka 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/MIMO 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Analysis and mitigation of channel non-reciprocity in TDD MIMO systems 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [MIMO-tekniikka](http://finto.fi/yse/fi/page/Y507646)

**Comment by mariaforsen** [comment]
Sv. MIMO-teknik ET mimoteknik

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
