### ISSUE TITLE
aktiivimalli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7647]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aktiivimalli 

#### Perustelut ehdotukselle   

Vai jokohan tämä on poistuva käsite..

https://fi.wikipedia.org/wiki/Aktiivimalli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi-fe2019111838538 

**Termiehdotus Fintossa:** [aktiivimalli](http://finto.fi/yse/fi/page/Y507647)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytää sanastoon muodossa aktiivimalli. Enemmistö kannatti sanastoon ottamista.
