### ISSUE TITLE
kuvaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7648]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuvaajat](http://www.yso.fi/onto/ysa/Y116100) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritellään tms.? 

#### Perustelut ehdotukselle   

Eng. nyt cameramen. Mutta Melindassa käytetty muustakin.. Pitäisi muuttaa ruotsiksi (skildrare>), mutta se on mahdotonta ellei tiedetä mihin tarkalleen viittaa... Huom. että valokuvaajat on erikseen, joten olisiko tämä mahdollista määritellä nimenomaan elokuviin liittyväksi? Myös MTS:ssä. Ks. myös https://fi.wikipedia.org/wiki/Kameraoperaattori ja https://en.wikipedia.org/wiki/Camera_operator Nämä pitäisi varmaan olla ainakin KT jos eng. cameramen on oikea vastine.

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
kuvaaja 
1) vrt. kuvata. Televisiokuvaaja. Pentti Haanpää maaseudun ihmisten kuvaajana.
2) mat. funktiota vastaava käyrä graafisessa esityksessä. 

2. merkitystäkin käytetty Melindassa ainakin: http://melinda.kansalliskirjasto.fi/byid/015511312

**Comment by ilona-x** [comment]
YSOssa nyt kuvaus (liikkuva kuva), voisiko tämä olla kuvaajat (liikkuva kuva)? Melinda-viitteistä suurin osa käsittelee elokuvan kuvaajia, lisäksi tv-kuvaajia, videokuvaajia. Joissain tapauksissa käytetty valokuvaajia käsittelevissä viitteissä valokuvaajat termin lisäksi. Joissain tapauksissa saattaa olla käytetty kaikkien kuvaajien kattoterminä (sis. valokuvaajat), mutta tuossa merkitysessä ei kovin monessa viitteessä, ja niissä tapauksissa voisi korvata yhdistelmällä valokuvaajat ja kuvaajat (liikkuva kuva). 

Tuota kielitoimiston sanakirjan 2. merkitystä löytyi vain 4 viitettä (yhteensä kuvaajat käytetty 229 kertaa).

- Many points make a point :data and graphs : student book 
- The Chicago guide to writing about numbers 
- Kuvaaja-oppimateriaali 
- Lukiolaisten graafisten esitysten tulkinta- ja tuottamistaidot 

Tarvitaanko kuvaajat tässä toisessa merkityksessä, vai riittäisikö muut sanastosta löytyvät termit? Kuvaaja näyttäisi olevan englanniksi graph ja sanastossa on jo graafit = graphs, mutta se näyttäisi olevan YSOssa vain matemaattisena käsitteenä https://fi.wikipedia.org/wiki/Graafi. Tosin Melindassa näyttäisi käytetyn myös toisessa merkityksessä.

**Comment by mariaforsen** [comment]
Ruotsiksi mat. merkityksessä: grafisk representant, mutta se on hyvin vähän käytetty, ei tarvita ruotsin osalta. 

Ratkaisu kuvaajat (liikkuva kuva) olisi varmaan filmfotograf..? Sanakirjat antaa myös "elokuvaajat", se olisi sitten korvattuna? Entä olisiko myös filmaaja korvattuna? (Kielitoimiston sanakirja)

**Comment by jarmosaarikko** [comment]
Entä kuvaajat (ammatti)  yläkäsitteeksi?
--  valokuvaajat, lehtikuvaajat, paparazzit, ovat jo YSO:ssa 
wikpediassa kuvaaja = elokuvaaja  en: cinematographer https://fi.wikipedia.org/wiki/Kuvaaja
kuvaaja F.S.C.    (F.S.C. – Suomen Elokuvaajien Yhdistys)

Ehdotus: lisätään alakäsitteeksi **elokuvaajat**    KT filmaajat, kuvaajat
-- filmfotograf@sv,  
-- cinematographer@en  http://id.loc.gov/authorities/subjects/sh85026013
-- https://www.wikidata.org/wiki/Q222344

Voiko lisätä lisätä ohjaustermiksi:
funktiot  KT  "funktion kuvaajat"  https://fi.wikipedia.org/wiki/Funktio#Funktion_kuvaaja

**Comment by mariaforsen** [comment]
Kuvaajat (ammatti) ei ratkaise ongelmaa, sekin voi edelleen viitata eri asioihin, ja siten se ei ole myöskään käännettävissä.

**Comment by LeKorsu** [comment]
Meidän firman sisäisestä puhelinluettelosta löytyy nykyää hyvin vähän "kuvaajia". Meillä on nykyään enemmän "kuvaaja-leikkaajia" sekä mediatoimittajia, joiden tehtäviin kuuluu myös kuvaaminen, leikkaaminen ja äänittäminen.
Ruotsinkielisten ohjelmien lopputeksteissä (esim. Spotlight) kuvauksesta näkyy käytetyn "fotograf", vaikka on kyse videokuvauksesta (liikkuvasta kuvasta).

**Comment by AuHo22** [comment]
Kuvaajat (elokuvaus) olisi mielestäni parempi kuin kuvaajat (liikkuva kuva) Videokuvauskin on elävää kuvaa, "elokuvaa".

**Comment by mirmaid** [comment]
_Leikkaajat_ on nyt tarkenteella _(elokuva ja media)_, mutta toki sekaantumisen vaaraa valokuvapuoleen ei siinä ole (pieni se tosin on tässäkin).

**Comment by mariaforsen** [comment]
filmfotograf=elokuvaaja http://www.ammattinetti.fi/ammatit/detail/163_ammatti
http://finto.fi/mts/sv/page/m1617?clang=fi

**Comment by YSO-kokous** [comment]
Tutkitaan asiaa vielä. @LeKorsu selvittää vielä Yleltä ja Kavilta terminologiaa. Tutkitaan myös Melinda-käyttöä vielä.

Pohdittiin otettavaksi sanastoon kaksi käsitettä: Nähtiin periaatteessa tarve sekä a) cinematographerille eli elokuvaajalle (ruotsiksi filmfotograf), joka on kuvauksen taiteellinen johtaja esim. elokuvaproduktioissa eikä tyypillisesti käytä itse kameraa että b) kameramiehelle / kameraoperaattorille / kameraoperatöörille, joka käyttää itse liikuvan kuvan kameraa. Huom! Metatietosanastossa on kameraoperaattorit. Kameraoperaattori nähtiin toisaalta viittaavan enemmän studio-oloissa järeämmän videokameran käyttäjään ja toimii huonommin, kun on kyseessä esim. uutiskuvaaja, joka kuvaa pienellä kameralla videokuvaa.

**Comment by LeKorsu** [comment]
Konsultointi Kavin kirjastonhoitajan ja tutun kuvaaja-leikkaajan kanssa: Molempien näkemys on, että kuvaaja ja kameramies kannattaa erottaa käsitteinä toisistaan, vaikka asia ei olekaan täysin yksiselitteinen

"Näkemykseni on että suomenkielessä kuvaajalla tarkoitetaan juuri sellaista henkilöä, joka vastaa kuvaamisen ilmaisullisesta puolesta. Kameramies taas vastaa lähinnä teknisestä toteutuksesta, kameran käsittelystä. Jotta tilanne ei olisi näin selkeä tai mustavalkoinen, niin monissa tapauksissa nämä menevät myös päällekäin. Pienimuotoisissa tuotannoissa, esimerkiksi meillä uutisssa kuvaaja ja kameramies ovat käytännössä sama henkilö, kun puhutaan kentällä tapahtuvasta kuvaamisesta. Studiossa tai monikameratuotannoissa taas voidaan käyttää kameramiehiä uutisissakin." (Yle)

"Puhtaasti elokuva-alan näkökulmasta pitäisin tosiaan (elo)kuvaajat sekä kameramiehet käsitteellisesti erillään, koska tehtävien luonteet ovat sen verran erilaisia. Kameramies ja kameraoperaattorikin lienevät taas jo rahtusen verran toisistaan poikkeavia."(Kavi)

Ehdotuksenpoikasta
kuvaajat (elokuva ja media)
sv filmfotografer  
en cinematographers
Kuvaaja vastaa elokuvan / tv-ohjelman taiteellisesta (ilmaisullisesta) puolesta .

Kameramiehet / kameraoperaattorit
odotan vielä  Ylen suunnasta tarkennusta siihen, ovatko nämä miten synonyymeja ja kumpi olisi yleisempi. Kavin kirjastonhoitajan kommentissa mainitaan että olisivat vähän eri asia. Wikipedia-artikkeli kameramiehistä sanoo, että käytetään toisinaan nimitystä kameraoperaattori. Kameraoperaattori-artikkelissa puolestaan sanotaan näin: "Kameraoperaattori (myös kameraoperatööri ja apulaiskuvaaja) on elokuva- ja televisio-alan ammattinimike kameran käyttäjälle."
Englanninkielinen Wikipedia:: A camera operator, or depending on the context cameraman or camerawoman, is a professional operator of a film camera or video camera as part of a film crew. The term "cameraman" does not imply that a male is performing the task.

Kysymys lienee myös siitä, otammeko saman termin kuin mikä jo on metatietosanastossa eli kameraoperaattorit ja haluammeko välttää -mies-loppuisia ammattinimityksiä?

**Comment by LeKorsu** [comment]
Tässä viimein kommenttia Ylen studiotuotannon esihenkilöltä. Laitan koko viestin ensiksi tähän ja tuolla lopussa omia kommenttejani

"Yleisradiossa meillä on otettu sukupuolineutraalit nimikkeet käyttöön muutamia vuosia sitten ja nimikkeet ovat vuosin saatossa osin vaihtuneet. Teknisen kehityksen myötä työnkuvat laajenevat jatkuvasti ja nimikkeet elävät vähän sen myötä. 

Kuvaaja (Ylellä puhutaan usein myös yksikamerakuvaajasta / "1-kamerakuvaaja" silloin kun on kyseessä dokumenttikuvaaja tai uutiskuvaaja, joka tekee kuvasuunnittelun pitkälti paikan päällä ja olosuhteisiin ja tapahtumiin mukautuen). Osa kuvaajista toimii kaikissa kuvaajan tehtävissä sekä lisäksi voi työskennellä kuvaussuunnittelijana tai kameraoperaattorina.
- Kuvaaja-leikkaaja on nimikkeenä lähinnä tyuövuorosuunnittelua varten erotuksena kuvaajasta, joka pelkästään kuvaa. Kuvaaja-leikkaajat toimivat erityisesti nopeissa uutistilanteissa keikoilla ulkomailla sekä tapahtumissa, joista tulee saada nopeasti valmis uutisjuttu lähetykseen. Eli kuvaaja-leikkaaja sekä kuvaa että leikkaa jo lokaatiossa valmiin insertin tai sen osan. 
- Uutis- ja ajankohtaiskuvaaja (käytetään lähinnä vuorosuunnittelussa yhtiön sisällä erotuksena dokumentaristeihin) toimii uutis- ja ajankohtaistoimituksessa ja kuvaa pääasiassa uutisia ja ajankohtaisinserttejä ja hallitsee kuvaamisen lisäksi erilaiset uutissuorien lähettämiseenvälineet (reppulähettimet, mobiilikuvaamisen ja lähettämisen jne.) ja niiden käytön.
- Dokumenttikuvaaja työskentelee Design ja Tuotanto -osastolla ja kuvaa pääasiassa dokumentteja. Voi toimia myös kuvaussuunnittelijana.

Kuvaussuunnittelija (Ylen kuvaussuunnittelija vastannee elokuvatuotannon kuvaajaa?) toimii pääasiassa tv-draamaelokuvien ja -sarjojen ja tai monikameratuotantojen kuvaussuunnittelijana. Hän suunnittelee kaikki kuvat ennalta (piirtää story boardin kuva kuvalta) yhdessä ohjaajan kanssa. Hän vastaa tuotannon / ohjelman valaisusta (valaisijat tekevät käytännön työn hänen ohjeistuksessa), visuaalisesta tyylistä sekä kuvakerronnasta. Hän voi operoida itse joissain tilanteissa myös kamerassa mutta useimmiten hänellä on kamera-assistentti apujoukkoineen draamassa. Monikameratuotannoissa sekä studio- (UMK, makasiiniohjelmat jne.) että ulkotuotannoissa (esim. oopperan televisiointi ja hiihdon maailman cup) varsinaisen kameratyön tekevät kameraoperaattorit kuvaussuunnittelijan ohjeiden, kuvasuunnitelman  ja kamerapaikkasuunnitelman mukaan.  

Kameraoperaattori (entinen kameramies) toimii monikameratuotannon kameratehtävissä (mm. peruskameratyö, stedicam, slow motion kamera, graana ym.) ja tai draamatuotannon kamera-assistenttina. Voi toimia myös kuvaajana."

Eli tämän pohjalta jatkan ehdotustani.  
Edelleen
kuvaajat (elokuva ja media)
sv filmfotografer
en cinematographers
Kuvaaja vastaa elokuvan / tv-ohjelman taiteellisesta (ilmaisullisesta) puolesta .
lisäys: kuvaussuunnittelijat KÄ kuvaajat

kameraoperaattorit
sv kameraoperatörer (?)
en cameraoperators
Tarvitseeko selitystä? On kameran käyttäjä

Nämä kaksi riittänevät yso-käytäntöön. Ei sinne varmaankaan yksittäisen firman monia ammattinimikkeitä tarvitse lisätä.

**Comment by mariaforsen** [comment]
En tosin ole varma voidaanko laittaa filmfotografer = kuvaajat (elokuva ja media), koska filmfotograf pätee vain elokuviin?

**Comment by YSO-kokous** [comment]
Lisätään tarkenne ja uudet käännökset: 
**kuvaajat (elokuva ja media)**
sv filmfotografer
en cinematographers  (LCSH http://id.loc.gov/authorities/subjects/sh85026013)
Huomautus: Kuvaaja vastaa elokuvan, tv-ohjelman tai videon taiteellisesta (ilmaisullisesta) puolesta.
KT elokuvaajat
Lisätään ohjaustermi: kuvaussuunnittelijat KÄ kuvaajat (elokuva ja media)

**Lisätään käsite:** 
**kameraoperaattorit**,
sv kameraoperatörer,
en cameraoperators (LCSH  http://id.loc.gov/authorities/subjects/sh2002011142)
KT kameramiehet, cameramen

**Comment by ilona-x** [comment]
"Sana "kuvaaja" käsittää erilaisia ammatteja, joiden työalueet voidaan jakaa seuraavasti:

1   Kuvatoimittajan työ uutis- ja ajankohtaiskuvauksissa
2   Taiteellinen kuvaus filmi- ja videotuotannossa

Seuraavassa esittelemme ainoastaan jälkimmäisen ryhmän toimenkuvan."

Lähde: http://elokuvantaju.uiah.fi/oppimateriaali/tuotanto/artikkelit/toimenkuva_kuvaaja.jsp
