### ISSUE TITLE
sydänlihassolut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7649]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sydänlihassolut 

#### Ehdotettu termi ruotsiksi   

hjärtmuskelceller 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lihassolut](http://www.yso.fi/onto/yso/p25540) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D032383> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Modelling arrhythmias and drug responses in CPVT patient-specific hiPSC-derived cardiomyocytes 

#### Perustelut ehdotukselle   

Melinda: 
sydänlihassolu x 2
sydänlihassolut x 8
kardiomyosyytit x 2 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sydänlihassolut](http://finto.fi/yse/fi/page/Y507649)

**Comment by mariaforsen** [comment]
Sv. ET hjärtmyocyter

**Comment by mirmaid** [comment]
_Regulation of the load-induced response in heart_
