### ISSUE TITLE
liposomit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7650]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

liposomit 

#### Ehdotettu termi englanniksi   

liposome 

#### Ehdotettu termi ruotsiksi   

liposom 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Liposomi

Liposomi on rasvamaisista lipidimolekyyleistä koostuva kupla eli rasvarakkula, jonka pinnalla on kaksi lipidimolekyylikerrosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-0098-6 

**Termiehdotus Fintossa:** [liposomit](http://finto.fi/yse/fi/page/Y507650)

**Comment by HeidiRonkainen** [comment]
yläkäsitteeksi lääkkeenkantajat https://finto.fi/mesh/fi/page/D004337

**Comment by mirmaid** [comment]
Myös _Photothermal Liposomal Drug Delivery Systems: Physicochemical Aspects in Particle Characterization and Drug Release from Light-Sensitive Drug Carriers_

**Comment by mariaforsen** [comment]
Sv. liposomer
