### ISSUE TITLE
puhelinkeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7651]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puhelinkeskukset](http://www.yso.fi/onto/ysa/Y98287) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT puhelinvaihteet? 

#### Perustelut ehdotukselle   

Synonymi tai lähes synonymi? https://fi.wikipedia.org/wiki/Puhelinkeskus

**Comment by YSO-kokous** [comment]
Puhelinkeskus hieman laajempi käsite. Viitannevat kuitenkin riittävässä määrin samaan käsitteeseen. 

PÄÄTÖS: Lisätään toistaiseksi puhelinkeskuksille ohjaustermiksi puhelinvaihteet. Tarkkaillaan ja palataan asiaan tarvittaessa.
