### ISSUE TITLE
Paleh (Venäjä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7652]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Paleh (Venäjä) 

#### Ehdotettu termi ruotsiksi   

Paleh (Ryssland) 

#### Ehdotettu termi englanniksi   

Palekh (Russia) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/names/n80150435> 
Wikidata : https://www.wikidata.org/wiki/Q1010115 

#### Perustelut ehdotukselle   

Tarvetta kuvailussa (Venäjä liian epätarkka, kun kyse paikallisesta taideilmiöstä) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Palehin lakkaminiatyyrit / Angelina Karpov 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Paleh (Venäjä)](http://finto.fi/yse/fi/page/Y507652)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Palekh

Ns. kaupunkityppinen taajama. Ei tarkennetta? Linjausta voisi vielä selkeyttää - milloin tarkennetta ei tarvita.

**Comment by mirmaid** [comment]
_Urban-type settlement is an official designation for a semi-urban settlement (or a former town), used in several Eastern European countries. The term was historically used in Bulgaria, Poland, and the Soviet Union, and remains in use today in 10 of the post-Soviet states._ https://en.wikipedia.org/wiki/Urban-type_settlement

**Comment by YSO-kokous** [comment]
Palehille ei laiteta sulkutarkennetta, koska vertautuu kuntaan tai kaupunkiin. Ks. edellinen kommentti. Linjaukset sulkutarkenteiden lisäämisestä olivat epätarkat. Niihin tehtiin seuraava lisäys:
_"Kaikille kuntaa, kaupunkia tai vastaavaa paikkatyyppiä pienemmille (hallinnollisesti epäitsenäisille) asutuille paikoille (esim. kylät, kaupunginosat) lisätään aina sulkutarkenne."_
https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSO-paikat
