### ISSUE TITLE
kauramaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7653]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kauramaito 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [kauramaito](http://finto.fi/yse/fi/page/Y507653)

**Comment by mariaforsen** [comment]
Joko tämä ja myös muita kasvimaitoja erikseen (riisi, soija, manteli, kookos jne.) tai sitten kasvimaidot? https://fi.wikipedia.org/wiki/Kasvimaito KT kasviperäiset maidot

**Comment by tpalonen** [comment]
Vaikka puhekielessä kauramaito on yleinen niin kotimaisten valmistajien tuotteet ja maahantuodut suomennetut tuotenimet taitavat kaikki olla muotoa kaurajuoma.

Fazer (Yosa): kaurajuoma
Kaslink (Aito): kaurajuoma
Valio (Oddlygood): kaurajuoma
Juustoportti: kaurajuoma
Planti: kaurajuoma
Pohjolan meijeri (Oattis): kaurajuoma
Rainbow: kaurajuoma
Pirkka: kaurajuoma
Kotimaista: kaurajuoma
Oatly: kaurajuoma
Alpro: kaurajuoma

Suosittelen muotoa **kaurajuoma** ja ohjaustermiksi kauramaito.

**Comment by ilona-x** [comment]
https://www.kielikello.fi/-/kauramaito-ja-kaurajuoma

**Comment by YSA-kokous** [comment]
Otetaan sanastoon kasvimaito. Tälle ohjaustermiksi kasviperäiset maidot. Jäädään seuraamaan, tarvitaanko muita käsitteitä.

**Comment by mariaforsen** [comment]
Sv. växtmjölk ET växtbaserad mjölk, vegansk mjölk, vegetabilisk mjölk

**Comment by YSO-kokous** [comment]
Päätettiin YSO-ylläpidossa ottaa sanastoon kuitenkin monikkomuodossa eli kasvismaidot. Syy: vrt. esim. mehut, viinit.
