### ISSUE TITLE
pienoisveistokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7655]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pienoisveistokset](http://www.yso.fi/onto/ysa/Y189758) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "figuriinit (pienoisveistokset)" tai tehdään tästä oma asiasanansa 

#### Perustelut ehdotukselle   

Figuriini-käsitettä käytetään myös määrätynlaisista pienoisveistoksista [https://fi.wikipedia.org/wiki/Figuriini] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _pieni (ihmisaiheinen) patsas_. Käytetään mielestäni melko laajasti, joten ei ehkä kannata ottaa erillisenä käsitteenä.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi muodossa figuriinit. Ilman sulkutarkennetta. Tuskin mahdollista sekoittaa johonkin muuhun käsitteeseen..
