### ISSUE TITLE
Kumlingen tauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7656]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kumlingen tauti](http://www.yso.fi/onto/ysa/Y108329) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KÄYTÄ puutiaisaivotulehdus? 

#### Perustelut ehdotukselle   

Ovat synonymejä, Kumlingen tauti on entinen nimitys. Ks. MESH https://fi.wikipedia.org/wiki/Puutiaisaivotulehdus jne.

**Comment by AuHo22** [comment]
KT puutiaisaivokuume
https://www.rokote.fi/rokotteilla-ehkaistavat-taudit/puutiaisaivotulehdus/

**Comment by PaiviLipsanen** [comment]
https://thl.fi/fi/web/infektiotaudit-ja-rokotukset/taudit-ja-torjunta/taudit-ja-taudinaiheuttajat-a-o/puutiaisaivotulehdus

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit Terveysportin kautta haettaessa tulee juurikin "puutiaisaivotulehdus":

https://www.terveysportti.fi/sovellukset/sanakirjat/#/q/113/kumlingen%20tauti

puutiaisaivotulehdus encephalitis per ixodes la, tick-borne encephalitis, Kumlinge disease e, fästingburen encefalit, Kumlingesjukan r (lyh. TBE) puutiaisaivokuume, puutiaisenkefaliitti, punkkienkefaliitti, Kumlingen tauti | puutiaisen levittämä, arboviruksen aiheuttama, Suomessa etenkin Ahvenanmaalla ja Turun saaristossa ja paikoin muuallakin esiintyvä virustauti, jonka ensimmäisessä vaiheessa voi esiintyä yleisoireita ja toisessa vaiheessa keskushermostotulehduksen oireita; ks. myös Kumlinge-virus
