### ISSUE TITLE
belgianpaimenkoira

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7657]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[belgianpaimenkoira](http://www.yso.fi/onto/ysa/Y149029) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT: groenendael, tervureninpaimenkoira/tervueren, laekeninpaimenkoira/laekenois, mecheleninpaimenkoira/malinois TAI mahdollisesti nämä erillisinä uusina termeinä. 

#### Perustelut ehdotukselle   

"Belgianpaimenkoira (ransk. Berger belge, hol. Belgische herder) on belgialainen paimenkoirarotu, joka jakautuu neljään muunnokseen lähinnä karvapeitteen ja värin perusteella: groenendael (pitkäkarvainen musta), laekenois (karkeakarvainen), malinois (lyhytkarvainen) ja tervueren (pitkäkarvainen punaruskea, joskus myös hiekanharmaa)."  /https://fi.wikipedia.org/wiki/Belgianpaimenkoira

**Comment by YSA-kokous** [comment]
Otetaan sanastoon muodossa belgianpaimenkoirat. Ja lisäksi tälle alakäsitteiksi seuraavat: groenendael, laekenois, malinois ja tervueren.

**Comment by mariaforsen** [comment]
Sv. belgiska vallhundar
-groenendael
-laekenois
-malinois
-tervueren
