### ISSUE TITLE
Liuksialan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7658]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Liuksialan kartano 

#### Ehdotettu termi ruotsiksi   

Liuksiala gård 

#### Ehdotettu termi englanniksi   

Liuksiala manor 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Liuksialan_kartano 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kolme kartanoa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Liuksialan kartano](http://finto.fi/yse/fi/page/Y507658)

**Comment by mariaforsen** [comment]
Sv. ET Liuxiala gård
