### ISSUE TITLE
Suuremõisan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7660]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Suuremõisan kartano 

#### Vaihtoehtoiset termit ja ilmaisut   

Hiiu-Suuremõisa mõis 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://et.wikipedia.org/wiki/Hiiu-Suurem%C3%B5isa_m%C3%B5is 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kolme kartanoa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Suuremõisan kartano](http://finto.fi/yse/fi/page/Y507660)

**Comment by mariaforsen** [comment]
Sv. Suuremõisa slott  https://www.visitestonia.com/sv/suuremoisa-slott ET Suuremõisa herrgård

**Comment by mirmaid** [comment]
Suomeksi enemmän käytetty muoto on Suuremõisan kartano, vaikka ylläolevalla sivulla myös suomeksi Suuremõisan linna. 

Auktorisoidaanko myös ulkomaisia kartanoita? Sanastossa on _Monrepos_.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
