### ISSUE TITLE
happipoltto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7662]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

happipoltto 

#### Tarkoitusta täsmentävä selite   

Happipoltto on yksi hiilidioksidin talteenottotekniikoista, joita voidaan soveltaa polttovoimalaitoksiin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Niva, Laura: Self-optimizing control of oxy-combustion in circulating fluidized bed boilers 

#### Perustelut ehdotukselle   

Niva, Laura: Self-optimizing control of oxy-combustion in circulating fluidized bed boilers 

**Termiehdotus Fintossa:** [happipoltto](http://finto.fi/yse/fi/page/Y507662)

**Comment by mariaforsen** [comment]
https://en.wikipedia.org/wiki/Oxy-fuel_combustion_process
Sv. syrgasförbränning

**Comment by mirmaid** [comment]
Happipoltto (oxy-combustion)
Happipoltossa polttoaine poltetaan kattilassa tai turbiinissa puhtaan hapen avulla. https://ilmasto-opas.fi/fi/ilmastonmuutos/hillinta/-/artikkeli/fd626ba3-8099-40e4-af75-94124d1f5c7f/hiilidioksidin-talteenotto-ja-varastointi.html

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
