### ISSUE TITLE
raportit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7664]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[raportit](http://www.yso.fi/onto/ysa/Y104137) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi teokset tai yhteiskunnalliset objektit 

#### Perustelut ehdotukselle   

YSOn ylläpito on saanut palautetta Sanastokeskus TSK:lta. "Kaikki raportit eivät ole julkaisuja, joten 'julkaisut' on huono yläkäsite."
Vrt. television uutisraportit yms.

Mikäli julkaisut siirretään esim. teosten alle, ongelmaksi tulee englannin termi: esim. "reports (works)" ei selventäisi käyttäjälle käsitteen merkitystä. 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Onko tarkenne välttämätön englanniksi?

**Comment by tpalonen** [comment]
Reports on käytettävänä terminä YSOssa kolmella käsitteellä, kaikissa on sulkutarkenne: mietinnöt, raportt ja selonteot. _mietinnöt / reports (memorandums)_ lienee näistä selkeimmin erotettavissa, mutta selonteot ja raportit on haastavampi. Mikä ylipäätään on näiden käsitteiden merkitysero? Tuntuvat muodostavan jatkumon ja päällekkäisyyttä on paljon. Kielitoimiston sanakirjan mukaan raportti on _"tiedotus, tiedote, tiedonanto, selonteko, tilannekatsaus"_.

Vaihdan selonteot vastineeksi _accounts (reports)_ ja raportit vastineeksi _reports (communication)_, mutta eivät nuokaan kovin luontevilta tunnu. Minusta selonteot ja raportit käsitteiden yhdistämistä voisi vielä miettiä.

**Comment by mirmaid** [comment]
Entä jos olisi vain reports = raportit ja lisäksi accounts (reports) ja joko reports (memorandums) tai memorandums (reports)? Englanniksihan saa olla kaksi samaakin termiä, joten on kai mahdollista myös olla sekä sulkutarkenteeton että tarkenteellinen? Communication-tarkenne on niin laaja, että ei mielestäni poissulje mietintöjä tai selontekojakaan. Ja varmaan ne voisi nähdä raporttien alatyyppeinä.

**Comment by tpalonen** [comment]
Muutan raportit muotoon _reports_ eli otan sulkutarkenteen pois. Ja reports (memodandums) muotoon _memorandums (reports)_. Ja muistiot-käsitteen englannin vastineelle lisään sulkutarkenteen _memorandums (memos)_. Huh, aikamoinen sotku. On toki sallittua, että englanniksi on usealla käsitteellä sama käytettävä termi, mutta pyrin välttämään sitä.
