### ISSUE TITLE
uudelleenkääntäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7665]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uudelleenkääntäminen 

#### Ehdotettu termi englanniksi   

retranslation 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kääntäminen](http://www.yso.fi/onto/yso/p9586) 

#### Vastaava käsite muussa sanastossa   

https://en.wikipedia.org/wiki/Retranslation :  

#### Perustelut ehdotukselle   

Aihetta koskevaa kirjallisuutta julkaistaan enenevässä määrin. Toimintana uudelleenkääntäminen poikkeaa ensimmäisen käännöksen teosta, koska edeltävä käännös antaa mallin, jonka uusi käännös vanhentaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Koskinen & Paloposki: Sata kirjaa, tuhat suomennosta – Kaunokirjallisuuden uudelleenkääntäminen 

#### Tarkoitusta täsmentävä selite   

Wikipedian mukaan: Retranslation refers to the action of "translating a work that has previously been translated into the same language" or to the text itself that was retranslated. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [uudelleenkääntäminen](http://finto.fi/yse/fi/page/Y507665)

**Comment by mariaforsen** [comment]
Sv. nyöversättning ET återöversättning

**Comment by mirmaid** [comment]
22 kertaa Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
