### ISSUE TITLE
viola d'amore

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7668]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[viola d'amore](http://www.yso.fi/onto/ysa/Y214726) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "lemmenviulu" 

#### Perustelut ehdotukselle   

Soittimesta käytetään myös sen suomenkielistä nimenmuotoa "lemmenviulu", josta olisi syytä saada viittausmuoto. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
