### ISSUE TITLE
soittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7669]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[soittimet](http://www.yso.fi/onto/ysa/Y98908) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-muoto "elottomat objektit" --> "välineet" 

#### Perustelut ehdotukselle   

Soittimet ovat musiikin esittämisessä käytettyjä välineitä. Vrt. esim. ruotsin "musikinstrument" ja englannin "musical instrument", jotka kumpikin kielivät soittimien välineellisyydestä 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
