### ISSUE TITLE
fortepiano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7670]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fortepiano](http://www.yso.fi/onto/ysa/Y109516) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde "kosketinsoittimet" --> "piano" 

#### Perustelut ehdotukselle   

Fortepiano on yhdenlainen piano, puurunkoinen sellainen erotuksena nykypianosta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
