### ISSUE TITLE
joiut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7671]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[joiut](http://www.yso.fi/onto/ysa/Y101941) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan joikuäänitteiden kuvailussa. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mirmaid** [comment]
On jo sanastossa.
