### ISSUE TITLE
Genuine Progress Indicator

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7673]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Genuine Progress Indicator](http://www.yso.fi/onto/ysa/Y166459) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan käytettäväksi termiksi nyt ohjausterminä oleva aidon kehityksen mittari muodossa aidon kehityksen indikaattori. 

#### Perustelut ehdotukselle   

https://www.eduskunta.fi/FI/tietoaeduskunnasta/julkaisut/Documents/tuvj_8+2019.pdf 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Aidon_kehityksen_mittari

Suomenkieliset muodot suunnilleen yhtä käytettyjä.

**Comment by ilona-x** [comment]
http://www.tsk.fi/tepa/fi/haku/aidon%20kehityksen%20indikaattori

**Comment by tpalonen** [comment]
Ääni mittarille, koska minusta parempaa suomea.

**Comment by mirmaid** [comment]
Aidon kehityksen mittari KT aidon kehityksen indikaattori?
