### ISSUE TITLE
puupiirros

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7674]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puupiirros](http://www.yso.fi/onto/ysa/Y98346) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "puupiirräntä" 

#### Perustelut ehdotukselle   

Kyseinen sanamuoto esiintyy mm. Japanilainen puupiirräntä -kirjassa [https://melinda.kansalliskirjasto.fi/byid/016668669], siis todellakin otsikossa, joten on käytetty ilmaus ja vaatisi tulla huomioiduksi sanastossa. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermi.
