### ISSUE TITLE
lahjoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7676]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lahjoitukset](http://www.yso.fi/onto/ysa/Y102956) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Opin juuri tänään että 'koha' tarkoittaa maorinkielellä lahjaa tai lahjoitusta. Pitäisikö tähän laittaa skos:prefLabel "koha"@mi, on kuitenkin oleellinen tieto kirjastojärjestelmien osalta, nyt kun kirjastokortitkaan ei enää toimi missä sattuu. 

#### Perustelut ehdotukselle   

Ihan itse wikipediasta tarkistin testatakseni että tämä ehdotusjärkkä toimii. 

#### Ehdottajan organisaatio   

Testi

**Comment by mirmaid** [comment]
:gift:
