### ISSUE TITLE
epäasiallinen kohtelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7677]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

epäasiallinen kohtelu 

#### Ehdotettu termi ruotsiksi   

osakligt bemötande 

#### Ehdotettu termi englanniksi   

inappropriate treatment 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kohtelu](http://www.yso.fi/onto/yso/p27806) 

#### Assosiatiiviset (RT)   

[häirintä](http://www.yso.fi/onto/yso/p11442) 
[työpaikkakiusaaminen](http://www.yso.fi/onto/yso/p69) 

#### Vastaava käsite muussa sanastossa   

TSR : epäasiallinen kohtelu työssä <http://www.yso.fi/onto/tsr/p13029> 
TERO : epäasiallinen kohtelu <http://www.yso.fi/onto/tero/TTL839> 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda x 2 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sopuisasti stadissa : epäasiallisen kohtelun ja häirinnän ehkäisy ja käsittely 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [epäasiallinen kohtelu](http://finto.fi/yse/fi/page/Y507677)

**Comment by ilona-x** [comment]
kaikki RT-ehdotukset eivät näköjään tulleet läpi 
eli vielä RT työsyrjintä

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
