### ISSUE TITLE
henkilökohtainen budjetti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7678]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

henkilökohtainen budjetti 

#### Perustelut ehdotukselle   

Menee helposti sekaisin henkilökohtaisen talouden kanssa? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.sitra.fi/julkaisut/henkilokohtainen-budjetti-ajattelu-ja-toimintatapana/ 

#### Tarkoitusta täsmentävä selite   

Henkilökohtainen budjetti on rahasumma, jonka ihminen voi käyttää sovittujen reunaehtojen mukaan palvelujen ja arjessa hyvinvointia ja toimintakykyä edistävän toiminnan järjestämiseen omaehtoisesti. Budjetin käyttäjän tai hänen valtuuttamansa henkilön tulisi pystyä seuraamaan budjetin toteutumista.
https://www.tukiliitto.fi/tuki-ja-neuvot/palveluiden-jarjestaminen/henkilokohtainen-budjetti/ 

**Termiehdotus Fintossa:** [henkilökohtainen budjetti](http://finto.fi/yse/fi/page/Y507678)

**Comment by mariaforsen** [comment]
Sv. personlig budget (socialservice)

**Comment by YSO-kokous** [comment]
Tutkitaan ja käsitellään seuraavassa kokouksessa. Jos otetaan, tarkenne voisi olla hyvä, että ei mene sekaisin henkilökohtaisen talouden kanssa.

**Comment by ilona-x** [comment]
" Hanke kehitti henkilökohtaiseen budjetointiin (HB) perustuvaa sote-palvelujen järjestämismallia vuosina 2016-2019. 

Henkilökohtaisen budjetoinnin (HB) malli

- tarjoaa asiakkaalle valinnanvapautta sosiaali- ja terveyspalveluissa
- tukee oman elämänpolun, osallisuuden ja sosiaalisen kansalaisuuden rakentumista.
- vahvistaa asiakaslähtöistä ja osallistavaa työskentelykulttuuria.
- ottaa asiakkaan mukaan kehittämiseen."

Lähde: http://henkilokohtainenbudjetointi.fi/

**Comment by mirmaid** [comment]
Kerran Melindassa v. 2014. Toisaalta tämä vaikuttaa liittyvän vahvasti sote-uudistuksen valinnanvapauteen, joten olisiko hyvä jättää vielä seurattaviin?

**Comment by YSO-kokous** [comment]
Jätetään termiehdotukseksi. Liittyy sote-uudistuksen terminologiaan. Epäselvää, tarvitaanko käsitettä laajemmin.

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tätä: http://urn.fi/URN:NBN:fi-fe2021101150548
Toisaalta, olisiko henkilökohtainen budjetointi parempi:

Henkilökohtaisella budjetilla tarkoitetaan budjettia, joka voi olla esimerkiksi euromääräinen, ja jolla asiakas voi hankkia henkilökohtaisen budjetoinnin piiriin kuuluvia palveluita.

Henkilökohtaisella budjetoinnilla tarkoitetaan avun, tuen ja järjestämisen tapaa, jossa henkilö on itse keskiössä omia palvelutarpeitaan vastaavan kokonaisuuden suunnittelussa, valinnassa ja toteuttamisessa (Sosiaali- ja terveysministeriö 2020).

**Comment by mirmaid** [comment]
Onko kyse aina vammaispalvelusta ja pitäisikö sen olla tarkenteena? Kannattaisin ehkä budjetointi-muotoa.

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään tarkenteella muodossa henkilökohtainen budjetointi (sosiaalipalvelut)
