### ISSUE TITLE
juurikääpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7679]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[juurikääpä](http://www.yso.fi/onto/ysa/Y95674) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

juurikäävät (suku Heterobasidion)
yläkäsite: kantasienet
alakäsite: männynjuurikääpä (Heterobasidion annosum)
alakäsite: kuusenjuurikääpä (Heterobasidion parviporum)
https://laji.fi/taxon/MX.204960 

#### Perustelut ehdotukselle   

Tarvittu jo vuosia useiden väitöskirjojen kuvailuun, esim.
Heterobasidion – conifer pathosystem: Host mycobiome and evaluation of potential resistance markers
https://helda.helsinki.fi/handle/10138/305842 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. Heterobasidion, basidiesvampar, rotticka, Heterobasidion parviporum
