### ISSUE TITLE
sanaristikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7680]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sanaristikot](http://www.yso.fi/onto/ysa/Y98725) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään SLM-sanastoon. 

#### Perustelut ehdotukselle   

SLM:ssä on ristikkolehdet, mutta se ei sovellu kirjoihin, esim. ISBN 9789512412969. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mirmaid** [comment]
ristikkolehdet > sanaristikot

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet.
ristikkolehdet KÄYTÄ sanaristikot
