### ISSUE TITLE
rakennusyritykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7681]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rakennusyritykset 

#### Perustelut ehdotukselle   

YSOssa on muutamia yritystyyppejä kuten hoivayritykset ja matkailuyritykset. Ehdottaisin joko otettavaksi rakennusyritykset tai KÄ rakennusteollisuus (mutta onko sama?) Näyttää olevan KOKOssa TSR-käsitteenä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cultural practices in the project based construction companies :its impact on information system implementation /Paskaran Brahman. 

**Ehdottajan organisaatio:** Kansallisbibliografia **Termiehdotus Fintossa:** [rakennusyritykset](http://finto.fi/yse/fi/page/Y507681)

**Comment by mariaforsen** [comment]
Sv. byggföretag ET byggnadsföretag

**Comment by ilona-x** [comment]
YSOssa on rakennusliikkeet (sv. byggnadsfirmor, en. building companies)

Melinda:
rakennusyritys x 2
rakennusyritykset x 10
rakennusala + yritykset 522

Kielitoimiston sanakirja:
rakennusliike = rakennusurakointia harjoittava liike
rakennusyhtiö = rakennusurakointia harjoittava yhtiö

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi eli
rakennusyritykset KÄYTÄ rakennusliikkeet
