### ISSUE TITLE
poropaimentolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7682]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

poropaimentolaiset 

#### Ehdotettu termi ruotsiksi   

ren-nomader 

#### Ehdotettu termi englanniksi   

reindeer herders 

#### Ehdotettu yläkäsite YSOssa (LT)   

[paimentolaiset](http://www.yso.fi/onto/yso/p16015) 

#### Vastaava käsite muussa sanastossa   

Reindeer herders (Library of Congress) : <http://id.loc.gov/authorities/subjects/sh96003858> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Arktisen ja Siperian alueen paimentolaisuutta. 

#### Perustelut ehdotukselle   

Olisi tärkeä erottaa pohjoisen alueen paimentolaiset omaksi ryhmäkseen, sillä YSA:ssa paimentolaisten alakäsitteenä on jo "beduiinit", joka ei kuvaa arktisen alueen paimentolaisuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3298327 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [poropaimentolaiset](http://finto.fi/yse/fi/page/Y507682)

**Comment by mariaforsen** [comment]
Sv. rennomader

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

41 kertaa _paimentolaiset + poronhoito_.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
