### ISSUE TITLE
ahvenanmaanlammas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7684]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ahvenanmaanlammas 

#### Ehdotettu termi englanniksi   

Åland sheep 

#### Ehdotettu termi ruotsiksi   

ålandsfåret 

#### Vaihtoehtoiset termit ja ilmaisut   

saaristolammas 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lammas](http://www.yso.fi/onto/yso/p8426) 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p7584> 

#### Perustelut ehdotukselle   

Melinda x 14 (+ 12 x AFO-terminä) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melinda 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ahvenanmaanlammas](http://finto.fi/yse/fi/page/Y507684)

**Comment by mariaforsen** [comment]
Sv. Ålandsfår
