### ISSUE TITLE
kurpat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7685]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kurpat](http://www.yso.fi/onto/ysa/Y107196) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään tarkenne suku/heimo ja lisätään toinen merkitys? 

#### Perustelut ehdotukselle   

kurpat Gallinago: https://laji.fi/taxon/MX.27657 vai kurpat Scolopacidae https://laji.fi/taxon/MX.27601 ?
Eng. nyt Scolopacidae, mutta sv. beckasiner=Gallinago

**Comment by mirmaid** [comment]
Käytetty ainakin laajemmassa merkityksessä. Ovatko molemmat tarpeen? Mahdollista toki ottaa sekä kurpat (heimo) että kurpat (suku).

**Comment by PaiviLipsanen** [comment]
YSOssa nyt:
kurpat  (heimo - Scolopacidae) https://laji.fi/taxon/MX.27601
heinäkurppa - Gallinago media (suku - kurpat)
taivaanvuohi - Gallinago gallinago (suku - kurpat)
lehtokurppa - Scolopax rusticola (suku - lehtokurpat)
kuovi - Numenius arquata (suku - kuovit)
rantakurvi - Xenus cinereus (suvulla ei suomenkielistä nimeä)
sirrit (suku - Calidris)
suokukko - Calidris pugnax

YSOon tarvitaan ainakin heimo. Kaikki lajit menevät heimon alle.

**Comment by mirmaid** [comment]
Säilytetään merkityksessä heimo? Ei mielestäni tarvitse tarkennetta, koska heimo kattaa myös suvun.

**Comment by mariaforsen** [comment]
Mutta termithän voivat olla ihan eri, eri kielillä, joten onhan se tärkeää että tietää mihin viittaa. Itse kannatan heimomerkitystä (sv. snäppor, Scolopacidae)

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa _kurpat_, ks. mirmaid-kommentti yllä. Englannin ja ruotsin termit heimon nimen mukaan.
