### ISSUE TITLE
joustot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7687]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[joustot](http://www.yso.fi/onto/ysa/Y136088) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaatii tarkennusta 

#### Perustelut ehdotukselle   

Ruotsiksi nyt elasticitet (talouskäsite), mutta se ei täsmää täysin Melindassa, koska siellä tämä on käytetty myös esim. työelämän joustoista. Siihen taas olisi ruotsiksi oikein käyttää flexibilitet=joustavuus (myös YSOssa) tai joissakin tapauksissa mahdollisesti joustotyö (myös YSOssa). Voidaanko määritellä joustot taloudelliseksi käsitteeksi? Nyt ryhmissä 00 ja 75.

**Comment by mariaforsen** [comment]
MOT Gummerus Uusi suomen kielen sanakirja: 1) joustaminen, joustavuus 2) tal. suureen muuttuminen toisen suureen muuttuessaminen toisen suureen muuttuessa 

https://fi.wikipedia.org/wiki/Jousto 

Kannatan tarkenteen lisäämistä sekä ruotsiksi että suomeksi.

**Comment by AuHo22** [comment]
Voisiko olla oma terminsä palkkajousto, vrt. joustotyö -> Työ jossa työajan ja työskentelypaikan voi valita yksilöllisesti.

**Comment by mirmaid** [comment]
^ Tämä: https://fi.wikipedia.org/wiki/Palkkajousto?

**Comment by mirmaid** [comment]
Joustotyöaika on työaikamalli, jossa työntekijä itse päättää työajastaan sekä työntekopaikastaan ja työnantaja puolestaan määrittelee tehtävät ja niitä koskevat tavoitteet sekä kokonaisaikataulun. https://www.erto.fi/tyosuhdeopas/tyoaika/joustotyoeaika

https://www.suomi.fi/yritykselle/tyonantajuus/tyoyhteison-hyvinvointi/opas/joustava-tyopaikka/tyoaikajoustot

**Comment by mirmaid** [comment]
Melindassa 139 viitettä, joista suurin osa työhön liittyvää, lähinnä nimenomaan työnantajan joustavuudesta (toisinaan myös työntekijän, https://melinda.kansalliskirjasto.fi/byid/013887309). Riittäisikö näihin _joustotyö_ ja _joustavuus_?

Myös mahd. _palkkajousto_ menisi kai _joustot (talous)_ -käsitteen alle (tai ehkä jopa _hintajouston_ alle)?

**Comment by YSO-kokous** [comment]
### Päätökset
Lisätään tarkenne: joustot (talous) 
Lisätään joustavuus KT joustot (joustavuus)
