### ISSUE TITLE
luteinisoiva hormoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7689]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luteinisoiva hormoni 

#### Ehdotettu termi englanniksi   

luteinizing hormone 

#### Ehdotettu termi ruotsiksi   

luteiniserande hormon 

#### Vaihtoehtoiset termit ja ilmaisut   

lutropiini, LH 

#### Perustelut ehdotukselle   

Luteinisoiva hormoni eli lutropiini (lyh. LH) on aivolisäkkeen etulohkosta erittyvä hormoni, joka stimuloi munasolujen irtoamista.https://fi.wikipedia.org/wiki/Luteinisoiva_hormoni 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1601-7 

**Termiehdotus Fintossa:** [luteinisoiva hormoni](http://finto.fi/yse/fi/page/Y507689)

**Comment by mariaforsen** [comment]
Sv. ET lutropin
