### ISSUE TITLE
follikkelia stimuloiva hormoni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7690]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

follikkelia stimuloiva hormoni 

#### Ehdotettu termi englanniksi   

follicle-stimulating hormone 

#### Ehdotettu termi ruotsiksi   

follikelstimulerande hormon 

#### Vaihtoehtoiset termit ja ilmaisut   

follitropiini, FSH 

#### Perustelut ehdotukselle   

FSH eli follikkelia stimuloiva hormoni tai follitropiini on aivolisäkkeen etulohkon hormoni
https://fi.wikipedia.org/wiki/FSH 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1601-7 

**Termiehdotus Fintossa:** [follikkelia stimuloiva hormoni](http://finto.fi/yse/fi/page/Y507690)

**Comment by mariaforsen** [comment]
Sv. follikelstimulerande hormon ET FSH, follitropin

**Comment by ilona-x** [comment]
FinMeSH: **follitropiini** KT follikkelia stimuloiva hormoni KT FSH http://www.yso.fi/onto/mesh/D005640

**Comment by mirmaid** [comment]
Pitempi muoto on käytetympi Googlella.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa follikkelia stimuloiva hormoni, ohjaustermiksi follitropiini.
