### ISSUE TITLE
metsätilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7691]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[metsätilat](http://www.yso.fi/onto/ysa/Y103355) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT metsäkiinteistöt? 

#### Perustelut ehdotukselle   

Sv. skogsfastigheter parempi päätermi? 
Vrt. AFO metsäkiinteistöt (fi) → metsätilat (fi)

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi metsäkiinteistö.
Ruotsin ylläpito miettii, otetaanko skogsfastigheter käytettäväksi termiksi vai ohjaustermiksi.
Termit viittaavat samaan käsitteeseen tai ainakin käsitteet ovat hyvin läheiset.

**Comment by mariaforsen** [comment]
Sv. skogsfastigheter
