### ISSUE TITLE
naamioituminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7692]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[naamioituminen](http://www.yso.fi/onto/ysa/Y131497) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa tai tarkennettavissa tarkenteella (ja 00-ryhmän poistolla)? 

#### Perustelut ehdotukselle   

Sv. nyt förklädning, se ei toimi jos kyseessä on eläinten naamioituminen tai sotaan liittyvä naamioituminen (kamouflage). Vrt. myös aiempi käsitelty naamiointi. 
Sanastossa siis myös naamiointi (sotatekniikka), maskeeraus, mimikry...

**Comment by jarmosaarikko** [comment]
minusta *naamioituminen* voisi muuttaa termiksi 
**naamiointi** 
RT **maskeeraus** 

NT **naamiointi (sotatekniikka)**   KT **maastoutuminen** en: Camouflage (Military science) http://id.loc.gov/authorities/subjects/sh85019165
---- RT **suojaväri**

 NT **naamiointi (biologia)** KT **mimikry**   en: **Camouflage (Biology)** http://id.loc.gov/authorities/subjects/sh85019164
---- RT **suojaväri**
---- RT **varoitusväri**

**Comment by mariaforsen** [comment]
Pääterminä ei voi olla naamiointi ilman tarkennetta, kun sanastossa on myös kaksi muuta "naamiointi"-termiä. Yllä ehdotettu ratkaisu ei siis ole mahdollinen. Ja saadaksemme käännös täytyy olla tarkka merkitys. 

Melindassa ei näytä juuri olevan sellaisia viitteitä (käytetty vain 78 kertaa, lähinnä artikkeleille), joihin ei voi käyttää muita jo YSOssa olevia termejä, eli naamiointi (sotatekniikka), maskeeraus, mimikry, maastopuvut, naamiot, naamiaispuvut, naamiaiset jne. Termi naamioituminen ei siis anna mitään lisäarvoa, lähinnä käytetään sekavasti. 

Jos halutaan jotain sopivaa myös tälle: https://melinda.kansalliskirjasto.fi/F/6G347S41A2H13JR3D397EUJP21VQM24H7GL4LBRT4KICPQXUXI-01698?func=full-set-set&set_number=047600&set_entry=000001&format=999 se voisi olla "valepuvut" tms.

**Comment by ilona-x** [comment]
Jarmon ehdotukseen kommenttina, että naamiointi on jo käsitelty aiemmin ja korjaukset tehty sen perusteella. https://github.com/Finto-ehdotus/YSE/issues/6764 Eli ei avata sitä mielellään uudelleen. 🔐 😃

**Comment by marjutpu** [comment]
Termiä 'naamioituminen' käytetään jonkun verran fiktiossa, erityisesti lastenkirjallisuudessa.

**Comment by EsaMPKK** [comment]
Voisi tämän ottaa vaikka pois sekoittamasta.

**Comment by AuHo22** [comment]
Sanastossa on termi suojautuminen sv. skyddsåtgärder ryhmissä eläintiede, sodankäynti ja palotoimi ; on lähellä ko. merkityksiä - naamioituminen (eläimet) on suojautumista, voisi toimia ohjausterminäkin?
Kamouflage (djur) -> skyddsåtgärder?

**Comment by mirmaid** [comment]
Onko tuo _åtgärder_ vähän kummallinen eläimistä?

**Comment by mariaforsen** [comment]
Skyddsåtgärder _ei_ voi liittyä eläimiin, eli joko se pitäisi poistaa siitä ryhmästä tai sitten pitäisi keksiä toisenlaisen termin, esim. "skydda sig"? Tosin näitä skydd-termejä on jo tosi paljon. Sanastossahan on muuten myös mimikry.

**Comment by mirmaid** [comment]
Poistetaan _naamioituminen_, korvataan kuvailussa muilla soveltuvilla käsitteillä.

_Suojautuminen_ vaatinee erillisen käsittelyn, koska ruotsinkielinen termi taitaa olla nyt tarkempi kuin suomenkielinen (myös ihmisistä käytettynä?).

**Comment by mariaforsen** [comment]
Näin on, siinä mielessä että skyddsåtgärder käy kyllä muissa ryhmissä, mutta ei 17.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta naamioituminen. Tehdään erillinen issue tapauksesta suojatuminen.
