### ISSUE TITLE
verhoilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7693]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verhoilu](http://www.yso.fi/onto/ysa/Y100149) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista rajata huonekaluverhoiluun, eli pääterminä huonekaluverhoilu tai verhoilu (huonekalut)? 

#### Perustelut ehdotukselle   

Sv. on möbeltapetsering. Melindassa on käytetty jonkin verran muustakin kuin huonekalujen verhoilusta.

**Comment by ilona-x** [comment]
YSOssa myös **verhoukset** KT seinäverhoukset (sv. beklädnader KT väggbeklädnader, eng. cladding (construction) http://www.yso.fi/onto/yso/p3036

**Comment by ilona-x** [comment]
Käyty läpi Melindasta 100 viitettä, joista suurin osa käsitteli erilaisten huonekalujen verhoilua. Lisäksi löytyi:
autot
kaiuttimet
veneet
ruumisarkut
lentokoneet
seinät (ulkoseinät & sisäseinät)
katot
patjat

Jos muutetaan verhoilu (huonekalut) muotoon, riittäisikö näihin muihin käyttötapauksiin esim. verhoukset, päällystys?

**Comment by mirmaid** [comment]
_Verhoukset_ ei varmaan käy kovin laajasti: Kielitoimiston sanakirja. 2. päällyste, peite. _Seinän tiiliverhous. Rakennuksen ulko- ja sisäverhous._

**Comment by ilona-x** [comment]
Hankala tapaus tämä, kun autojenkin osalta verhoillaan ainakin istuimia, ovia ja kattoja.

**Comment by mariaforsen** [comment]
Verhoukset=beklädnader käy ruotsin osalta laajasti.

**Comment by mirmaid** [comment]
Olisiko auton istuimien verhoilu beklädnad vai tapetsering? Mitä kaikkea pitäisi sisältyä _verhoukset/beklädnader_-käsitteeseen?

Menisikö kaiuttimien verhoilu vielä huonekaluverhoilun alle? Tai jos tarkenne ei olisi huonekalut vaan kalusteet, niin olisiko se vielä sallivampi? Auton penkkejä nyt tuskin kalusteiksikaan pystyy ajattelemaan, entä miten laajasti ruotsin möbel käy?

**Comment by mariaforsen** [comment]
Se olisi beklädnad. Ruotsin möbel on kyllä aika rajattu merkitykseltään https://svenska.se/tre/?sok=m%C3%B6bel&pz=1

**Comment by mariaforsen** [comment]
Poikkeuksellisesti kyllä möbeltapetsering on ok, mutta näin on myös beklädnad.

**Comment by mirmaid** [comment]
Sanakirjan mukaan verhoilija = tapetserare, mutta tapetsering on vain tapetointi. Verhoilu = överdragning, beklädning, överklädning. 

Ymmärränkö nyt oikein, että toivottu lopputulos:

- huonekaluverhoilu/möbeltapetsering = käytetään kun kyse on rakennusten kalusteista

- verhoukset/beklädnader = käytetään kulkuvälineiden kalusteista ja ulko- ja sisäpinnoista, esineistä, jotka eivät ole selkeästi huonekaluja ja rakennusten ulko- ja sisäseinistä (paitsi tapetoinnista). Mikään ei myöskään estä käyttämästä verhoukset/beklädnader **myös** huonekaluista?

**Comment by mariaforsen** [comment]
Yllä oleva ratkaisu on ruotsin osalta ok.

**Comment by mirmaid** [comment]
Vielä esimerkkiaineisto:
https://melinda.kansalliskirjasto.fi/byid/013821421
- verhoilijat = tapetserare oikein?
- verhoilu = möbeltapetsering korjattava > beklädnader, koska kyse on _ajoneuvojen_ istuimista?

**Comment by mirmaid** [comment]
https://melinda.kansalliskirjasto.fi/byid/013446144

Tähän käy varmaan möbeltapetsering, mutta miten istuu suomeksi jos kyseessä pihakalusteet?

**Comment by mirmaid** [comment]
Samoissa aineistoissa usein sekä huonekalujen, että muun (patjat, tyynyt, veneiden sisäkalustus jne.) verhoilua. Näihin tulisi sekä _huonekaluverhoilu_, että _verhoukset_, mutta pitäisikö _verhoukset_-käsitettä käyttää myös huonekalujen yhteydessä huonekaluverhoilun ohella, koska muu vastaava verhoilu yksinään kuvailtaisiin vain _verhoukset_-käsitteellä?

**Comment by ilona-x** [comment]
> 
> 
> https://melinda.kansalliskirjasto.fi/byid/013446144
> 
> Tähän käy varmaan möbeltapetsering, mutta miten istuu suomeksi jos kyseessä pihakalusteet?

Voikohan tuota ylipäänsä ajatella verhoiluna, jos vain kansituolin kangas vaihdetaan räsymatoksi. https://www.meillakotona.fi/artikkelit/nain-vaihdat-paallisen-kansituoliin . Kyse ehkä enemmänkin tuunauksesta.

**Comment by mariaforsen** [comment]
Kyllä, verhoilijat=tapetserare on ok. Näin termit määritellään ruotsiksi (ks. esim. svenska.se) Tapetserare: "person som yrkesmässigt stoppar och klär möbler och sätter upp gardiner och draperier"  

Ja kyllä edelleen kannatan että termit olisi: verhoukset=beklädnader, huonekaluverhoilu=möbeltapetsering.

**Comment by mirmaid** [comment]
^^ Joissakin muissakin tapauksissa mietin _huonekalut_-käsitteen rajautumista suomeksi - aineistoja on esim. julkisten tilojen kalusteiden verhoilusta (lentokentän kalusteet eivät ehkä enää olisi huonekaluja, mutta entä möbler...). _Kalusteverhoilu_ on kuitenkin paljon vähemmän käytetty kuin _huonekaluverhoilu_.

**Comment by mariaforsen** [comment]
Sana möbel ei sinänsä ota kantaa siihen että onko niitä julkisissa tiloissa vai ihmisten kodeissa.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon huonekaluverhoilu. Ohjaustermiksi: verhoilu (kalusteet).
Verhoilu-käsite poistetaan sanastosta.
Lisätään seuraava ohjaustermi: verhoilut (verhoukset) KÄYTÄ verhoukset.

Keskustelua: Veneiden kaluston verhoilun kannalta huonekaluverhoilu-käsite/termi ei ole ruotsin näkökulmasta kovin sovelias, mutta tilanne on kuitenkin parempi kuin se, että sanastossa ei ole tällaista käsitettä ollenkaan.
