### ISSUE TITLE
hevosurheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7695]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hevosurheilu](http://www.yso.fi/onto/ysa/Y95363) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT ratsastusurheilu tai KÄYTÄ ratsastus? 

#### Perustelut ehdotukselle   

Ks. esim. https://fi.wikipedia.org/wiki/Ratsastus

**Comment by mirmaid** [comment]
Eli varmaankin ratsastusurheilu KÄ ratsastus?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi: ratsastusurheilu KÄYTÄ ratsastus
