### ISSUE TITLE
mikrobilääkkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7696]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mikrobilääkkeet](http://www.yso.fi/onto/ysa/Y109903) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT antimikrobiset lääkkeet 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Mikrobil%C3%A4%C3%A4ke

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
