### ISSUE TITLE
Bourbon-restauraatio (Ranska)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7697]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Bourbon-restauraatio (Ranska) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Histoire de la restauration et des causes qui ont amené la chute de la branche ainée des Bourbons 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Bourbon-restauraatio (Ranska)](http://finto.fi/yse/fi/page/Y507697)

**Comment by mariaforsen** [comment]
Sv. Bourbonska restaurationen (Frankrike)  ET Bourbonrestaurationen

**Comment by LeKorsu** [comment]
Tarvitseeko selitettä/huomautusta esim. vuosilukuja, jota tämä koskee?

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa Bourbon-restauraatio (Ranska).
