### ISSUE TITLE
yleislakko (1956)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7698]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yleislakko (1956) 

#### Vaihtoehtoiset termit ja ilmaisut   

vuoden 1956 yleislakko 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [yleislakko (1956)](http://finto.fi/yse/fi/page/Y507698)

**Comment by mariaforsen** [comment]
Sv. generalstrejken 1956 ET storstrejken 1956

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa yleislakko 1956. Muutetaan myös yleislakko (1917) tähän sulkutarkenteettomaan muotoon. Enemmistö kannatti tätä kirjoitustapaa.

**Comment by mirmaid** [comment]
Entä suurlakko (1905)?
