### ISSUE TITLE
taajaväkiset yhdyskunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7699]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taajaväkiset yhdyskunnat 

#### Ehdotettu termi ruotsiksi   

municipalsamhällen 

#### Vaihtoehtoiset termit ja ilmaisut   

taajaväkiset maalaisyhdyskunnat 

#### Assosiatiiviset (RT)   

[kuntamuodot](http://www.yso.fi/onto/yso/p10051) 
[maalaiskunnat](http://www.yso.fi/onto/yso/p12993) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q348884 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.2363989 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

#### Perustelut ehdotukselle   

Sanastossa ei ole ennestään kyseistä ilmiötä vastaavaa asiasanaa. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [taajaväkiset yhdyskunnat](http://finto.fi/yse/fi/page/Y507699)

**Comment by mariaforsen** [comment]
Sv. samhällen med sammanträngd befolkning ET municipalsamhällen
https://www.uppslagsverket.fi/sv/sok/view-103684-SamhaelleMedSammantraengdBefolkning
https://sv.wikipedia.org/wiki/Municipalsamh%C3%A4lle

**Comment by mirmaid** [comment]
Ei Melindassa.

https://fi.wikipedia.org/wiki/Taajav%C3%A4kinen_yhdyskunta

**Comment by LeKorsu** [comment]
Eikö tähän vanhaan teokseen kävisi asiasanaksi taajamat? En kannata taajaväkiset yhdyskunnat -termin ottamista ysoon sekoittamaan, kun niitä ei enää ole lainsäädännöllisesti olemassa. Tai korkeintaan ohjaustermiksi taajamille.

**Comment by YSO-kokous** [comment]
Otetaan taajaväkiset yhdyskunnat ohjaustermiksi käsitteelle taajamat.

**Comment by jtuohini** [comment]
Jos lisätään _taajaväkiset yhdyskunnat_ KÄ **taajamat**, niin ehdottomasti tarvitaan rinnalle myös viittaus KÄ **kuntamuodot**. Keskeistä taajaväkiselle yhdyskunnalle on sen erityinen hallinnollinen asema, joten viittaus kuntamuotoihin on lähes tärkeämpi kuin taajamiin. Se seikka, että Suomen nykylainsäädäntö ei tunne enää taajaväkisiä yhdyskuntia ei mielestäni käy perusteeksi sivuuttaa ilmiötä 'menneen talven lumena': pelkästään Kansalliskirjaston Digi-palvelussa fraasihaku kyseisellä käsitteellä tuottaa 28 486 osumaa.
