### ISSUE TITLE
tähystys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7700]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tähystys](http://www.yso.fi/onto/ysa/Y104720) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selventävä sulkutarkenne, esim. (lääketieteelliset toimenpiteet) tai (lääketiede). Tai selventävä käyttöhuomautus, jossa linkki tiedusteluun tai muuhun vastaavaan puolustusalan käsitteeseen. 

#### Perustelut ehdotukselle   

Finnan kuva-aineistossa tähystystä käytetty systemaattisesti eri merkityksessä kuin mihin se on YSAssa/YSOssa tarkoitettu, ts. tähystykseen tiedustelutoimintana. Melindassa tosin kuvailukäyttö vastaa YSAn/YSOn tarkoitettua merkitystä.

Ks. YSOn tähystys-käsitteen Finna-ikkuna:
http://www.yso.fi/onto/yso/p1036 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Tärkeä huomio, ruotsinkielinen termi sopii todellakin vain lääketiede-merkitykseen ja Finna-kuvat ovat nyt täysin sopimattomat. Pitäisikö ohjata myös: tähystys (tiedustelu) KÄYTÄ tiedustelu?

**Comment by mirmaid** [comment]
FinMeSHissä päätermi on _endoskopia_.

**Comment by tpalonen** [comment]
SOTOssa käsite tähystystiedustelu.
http://www.yso.fi/onto/soto/p1094

**Comment by mirmaid** [comment]
_Tähystystiedustelu_ olisi ok käsite (pelkkä _tiedustelu_ on vähän laaja), mutta ei näytä tarpeelliselta toistaiseksi Melinda-käytön valossa.

**Comment by mariaforsen** [comment]
Ruotsiksi jo spaning=tiedustelu (myös tähystys tässä merkityksessä on spaning)

**Comment by YSO-kokous** [comment]
Tähystys-käsitteen käytettäväksi termiksi endoskopia.
Lisäksi seuraavat ohjaustermit:
tähystys (endoskopia) KÄ endoskopia
tähystys (tiedustelu) KÄ tiedustelu
