### ISSUE TITLE
miniatyyrit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7701]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[miniatyyrit](http://www.yso.fi/onto/ysa/Y102502) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "miniatyyrimaalaukset" 

#### Perustelut ehdotukselle   

Nykyinen asiasana viittaa miniatyyrimaalauksiin (LT maalaukset), mutta sitä on käytetty virheellisesti myös muiden pienoisasioiden kuvailuun (ks. esim. https://melinda.kansalliskirjasto.fi/byid/015357620, https://melinda.kansalliskirjasto.fi/byid/009368836 ja https://melinda.kansalliskirjasto.fi/byid/012211479), arvattavasti koska asiasana ei sisällä kovin tarpeellista osiota 'maalaukset'. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Käsite on ryhmissä: 
00 Yleistermit
92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto
94 Taideteollisuus. Sisustustaide
Joten käsite on tuskin tarkoitettu vain maalausmerkitykseen. Jos haluttaisiin nyt rajata pelkästään siihen se vaatisi kyllä käsitteen jakamista ja Melindakorjauksia, koska termi on käytetty paljon muusta kuin maalauksista.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 1. pienoismaalaus, -kuva, pienois(koriste-)esine.

**Comment by mirmaid** [comment]
Vähän epäjohdonmukainen tämä on, koska yläkäsite jo YSAssa _maalaukset_. Toki aikaisemmin toisinaan tehty hierarkia "tyypillisen tapauksen" mukaan.

**Comment by mirmaid** [comment]
Voisi olla _miniatyyrimaalaukset_ ja _miniatyyriesineet_, mutta käytetty myös ainakin miniatyyritekstiileistä. Korjattavaa paljon, eikä tietueesta aina selviä onko kyse maalauksista vai jostain muusta.

**Comment by tpalonen** [comment]
Käytetty aika paljon muustakin kuin maalauksista, esim. erilaisista käsitöistä kuten neuletöistä, veistoksista, installaatioista (esim. kuvataiteilija Frank Kunertin miniatyyri-installaatiot: https://www.frank-kunert.de/de/galerie/). Lisäksi myös lautapelifiguureista ja jopa minidekkarista.

_Miniatyyriesineet_ voisi sopia näihin muihin tapauksiin hyvin (paitsi minidekkareihin).

**Comment by mirmaid** [comment]
^ Entä ne tekstiilit?

**Comment by mirmaid** [comment]
Toisaalta **esine** ei kyllä ihan välttämättä poissulje maalauksiakaan...

**Comment by YSO-kokous** [comment]
Jätetään miniatyyrit nykyiseen muotoonsa. Muutetaan sen hierarkiaa niin että kattaa muutakin kuin maalaukset.
