### ISSUE TITLE
luonnehäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7702]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luonnehäiriöt](http://www.yso.fi/onto/ysa/Y97005) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

olisiko mahdollista yhdistää personallisuushäiriöt & luonnehäiriöt? 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja: luonnehäiriö vars. aik. persoonallisuushäiriöstä. 

https://www.britannica.com/science/personality-disorder

Melinda:
luonnehäiriöt 270
persoonallisuushäiriöt 854
luonnehäiriöt + persoonallisuushäiriöt  154 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi ok.

**Comment by mirmaid** [comment]
Eli luonnehäiriöt KÄ persoonallisuushäiriöt.

**Comment by YSO-kokous** [comment]
Poistetaan luonnehäiriöt ja lisätään ohjaustermi: luonnehäiriöt KÄ persoonallisuushäiriöt.
