### ISSUE TITLE
muste

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7704]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muste 

#### Ehdotettu termi ruotsiksi   

bläck 

#### Ehdotettu termi englanniksi   

ink 

#### Ehdotettu yläkäsite YSOssa (LT)   

[väriaineet](http://www.yso.fi/onto/yso/p2176) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85066453.html> 
Svenska ämnesord : https://id.kb.se/term/sao/Bl%C3%A4ck 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3299441 

#### Tarkoitusta täsmentävä selite   

Kirjoittamisessa, kirjoittimissa, värjäämisessä yms käytetty neste, joka sisältää väriaineita. 

#### Perustelut ehdotukselle   

Käsite puuttuu YSOsta 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [muste](http://finto.fi/yse/fi/page/Y507704)

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
