### ISSUE TITLE
indium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7705]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

indium 

#### Ehdotettu termi englanniksi   

Indium 

#### Ehdotettu termi ruotsiksi   

indium 

#### Ehdotettu yläkäsite YSOssa (LT)   

[metallit](http://www.yso.fi/onto/yso/p3097) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Indium 
LCSH : <http://id.loc.gov/authorities/subjects/sh85065672> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Techno-economic assessment of the process for recovery of indium, germanium and tin from alloys obtained as byproducts of zink production 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda x 17 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [indium](http://finto.fi/yse/fi/page/Y507705)

**Comment by mirmaid** [comment]
Myös _Thermodynamic Properties of WEEE-based minor elements in copper smelting processes_
