### ISSUE TITLE
nokkoset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7706]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nokkoset](http://www.yso.fi/onto/ysa/Y97665) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

kt aitonokkoset 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.37983 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. nässlor, nässelsläktet

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
