### ISSUE TITLE
juurikääpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7707]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[juurikääpä](http://www.yso.fi/onto/ysa/Y95674) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

juurikäävät (Heterobasidion)
https://laji.fi/taxon/MX.204960 

#### Perustelut ehdotukselle   

Tätä ja alakäsitteitä on tarvittu ja käytett jo vuosia 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. rottickor

**Comment by mirmaid** [comment]
AFOssa on _juurikäävät, kuusenjuurikääpä_ ja _männynjuurikääpä_.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7679

**Comment by mirmaid** [comment]
Muutetaan monikkoon ja otetaan mainitut alakäsitteet sanastoon.
