### ISSUE TITLE
sokerideittailu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7708]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sokerideittailu 

#### Ehdotettu termi ruotsiksi   

sugardejting 

#### Ehdotettu termi englanniksi   

sugar dating 

#### Perustelut ehdotukselle   

Sokerideittailun rajanveto on häilyvä, onko se vastikkeellista seurustelua, silkkaa hyväksikäyttöä vaiko prostituution harmaalle alueelle menevää toimintaa? Assosiatiivisen käsitteen hankalasta määrittelystä huolimatta sokerideittailu tapauksessa lähivuosina noussut ilmiö, jonka myös Kotus on vuonna 2017 ottanut sanatietokantaansa  https://www.kotus.fi/sanakirjat/kielitoimiston_sanakirja/uudet_sanat/vuoden_sanapoiminnot/sanapoimintoja_2017 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi kotimainen tv-sarja Kiiltokuvia (2014), A-studion jakso Seksikauppaa sokerilla (2018). 

**Ehdottajan organisaatio:** KAVI **Termiehdotus Fintossa:** [sokerideittailu](http://finto.fi/yse/fi/page/Y507708)

**Comment by mariaforsen** [comment]
Sv. sockerdejting ET sugardejting, sockerdejtning, sockerdating

**Comment by mirmaid** [comment]
Sokerideittailulla tarkoitetaan sitä, että yleensä varakkaampi ja vanhempi henkilö maksaa nuoremmalle henkilölle tämän seurasta ja yleensä myös seksistä. https://www.metropoli.net/lifestyle/parisuhteet/suomalaistutkimus-onko-sokerideittailu-hyvaksikayttoa-nuorten-aikuisten-mielesta-ei-ole/

_– Prostituutiostahan sokerideittailussa on kyse ja vieläpä hyvin perinteisessä mielessä. Asiaa saa toki kutsua eri nimillä, mutta huolestuttavaa on, jos suhteen luonne hämärtyy sokeridiilien osapuolille perusteettomasti epäselvän ilmaisun takia. Tilanne voi altistaa kumman tahansa osapuolen hyväksikäytölle, Hänninen sanoo._

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa sokerideittailu.

Termin korrektius herätti keskustelua ja myös käsitteen suhde prostituutioon. Onko kyseessä prostituution alalaji vai ei? Ilmiön todettiin kuitenkin olevan olemassa ja hyväksyttiin sanastoon.
