### ISSUE TITLE
kevytjunat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7709]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kevytjunat](http://www.yso.fi/onto/ysa/Y166276) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi RT-suhde: pikaraitiotiet 

#### Perustelut ehdotukselle   

Liittyvät ainakin Wikipedian kieliversioiden mukaan toisiinsa. Ks. https://fi.wikipedia.org/wiki/Pikaraitiotie
https://en.wikipedia.org/wiki/Light_rail
YSO eng. light rails=kevytjunat
YSO eng. light rail=pikaraitiotiet 
"Kevytjunat" hyvin vähän googlessa. Olisiko parempia päätermejä? Ruotsinnos selvitettävänä.

**Comment by ilona-x** [comment]
TEPA: 
fi        kevytjuna ★★☆☆; kevytraide ★★☆☆; pikaraitiotie ★★☆☆; pikaraitiovaunu ★★☆☆
sv       snabbspårväg ★★★★
en      light rail ★★★☆
http://www.tsk.fi/tepa/fi/haku/kevytjuna

"Light rail on perinteisen raitiovaunun moderni, parannettu versio. Sitä voidaan kutsua suomeksi esimerkiksi pikaraitiovaunuksi tai kevytjunaksi "
Lähde: https://www.hs.fi/kaupunki/art-2000003978440.html

Melinda: 
kevytjunat x 1 (otettu sanastoon v. 2009)
pikaraitiotiet x 1 (otettu sanastoon v. 2014)

**Comment by mirmaid** [comment]
Vaihdetaanko kevytjunat KÄ pikaraitiovaunut? Käytetty kerran Melindassa (pikaraitiotiet ei kertaakaan).

**Comment by mirmaid** [comment]
Pikaraitiotien perusominaisuus on, että se voi kulkea monenlaisilla kulkuväylillä:
- omalla, muusta liikenteestä eristetyllä väylällä tunnelissa tai eritasossa kuten metro
- erillisellä, muusta liikenteestä riippumattomalla ratalinjauksella kuten paikallisjuna
- omalla kaistallaan katutilassa kuten raitiovaunu
- raitiokävelykadulla kuten raitiovaunu
- muun liikenteen kanssa samalla kaistalla kuten raitiovaunu tai linja-auto (yleensä pyritään minimoimaan)
- muun rautatieliikenteen kanssa samalla raiteella, jos käytössä on _duoraitiovaunukalusto_

Googlella suosituin termi on _pikaraitiotiet_. YSOssa on lisäksi _kevytjunat_, mutta se ei näytä vakiintuneen käyttöön, vaan käytetympiä ovat _pikaraitiovaunut_ ja _duoraitiovaunut_, joista jälkimmäinen siis eroa tavallisesta pikaraitiovaunusta sikäli, että pystyy kulkemaan myös rautatiellä. 

Termistö on ehkä edelleen vähän vakiintumatonta, mutta kevytjunat ei taida olla yleistymässä käyttöön (vaikka olisi hyvä vastine _light rail_ -termille).

**Comment by LeKorsu** [comment]
Turvaudun jälleen kerran Sanoman arkistoon tutkiessani median käyttämää kieltä: kevytjuna 3 osumaa, pikaraitiotie 731 ja pikaraitiovaunu 91 osumaa. Peukku Mirjan ehdotukselle kevytjunien korvaamisesta pikaraitiovaunuilla.

**Comment by tpalonen** [comment]
Lainaus duoraitiovaunut-issuesta (https://github.com/Finto-ehdotus/YSE/issues/8042):

_Muutetaan käsitteen kevytjunat käytettäväksi termiksi pikaraitiovaunut. Lisätään ohjaustermi kevytjunat KÄYTÄ pikaraitiovaunut sekä duoraitiovaunut KÄYTÄ pikaraitiovaunut._
