### ISSUE TITLE
sanomalehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7710]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sanomalehdet](http://www.yso.fi/onto/ysa/Y98733) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko mahdollista siirtää nykyiset alakäsitteet joko kausijulkaisujen tai mahdollisesti aikakauslehtien alle? 

#### Perustelut ehdotukselle   

Ainakin ruotsiksi on nyt hierarkiavirhe. Dagstidningar=sanomalehti="päivittäin t. monta kertaa viikossa ilmestyvä..." /KS 
Kausijulkaisujen alla on jo esim. sensaatiolehdet, joten ei liene iso ongelma siirtää nämä:

    aluelehdet
    ilmaisjakelulehdet
    puoluelehdet
    sitoutumattomat lehdet
    työväenlehdet

**Comment by mirmaid** [comment]
YK kausijulkaisut (SLM)

**Comment by mirmaid** [comment]
Toteutettu myös YSOssa.
