### ISSUE TITLE
myllyhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7711]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[myllyhoito](http://www.yso.fi/onto/ysa/Y108204) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi RT Minnesota-malli 

#### Perustelut ehdotukselle   

On yleensä sama asia.
Jos pitää olla erikseen (Suomessa tapa soveltaa Minnesota-mallia ja eng. ja sv. ei käännettävissä =myllhoito)

**Comment by mirmaid** [comment]
Melindassa _myllyhoito_ 46 kertaa, _Minnesota-malli_ 36 kertaa. Ei yleensä yhdessä. Kirjoihin rajattuna Minnesota-malli on vähän käytetympi.

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet. Tutkitaan terminologiaa ja päätetään käytettävä termi sen perusteella. Vaihtoehtoina Minnesota-hoito, myllyhoito ja Minnesota-malli.

**Comment by tpalonen** [comment]
Kaikkia edellä mainittuja muotoja esiintyy. Syy siihen, miksi yksi muoto ei ole vakiintunut yli muiden lienee se, että termejä esiintyy alan organisaatioiden nimissä: Myllyhoitoyhdistys, Päijät-Hämeen Myllyhoitoklinikka, Minnesota-hoito Oy. Organisaatiot luonnollisestikin puhuvat omasta toiminnastaan oman nimensä mukaisesti. Google-haun perusteella myllyhoito on hieman yleisempi nimitys kuin Minnesota-hoito (kun hausta poistetaan "Minnesota-hoito Oy"-tulokset). Myllyhoitoyhdistys on perustettu vuonna 1983 (https://myllyhoitoyhdistys.fi/fi/yhdistys/#visio). Keskeiseksi toimijaksi mainittu Kalliola-konserni on harjoittanut myllyhoitoa vuodesta 1982 (https://www.kalliola.fi/tekijaksi-kalliolaan/). Minnesota-hoito Oy on perustettu vuonna 1992 (https://fi.wikipedia.org/wiki/Minnesota-malli). Myllyhoito lienee tästä päätellen ollut terminä pitempään käytössä. Näistä syistä suosittelen käytettäväksi termiksi muotoa **myllyhoito** ja muut ohjaustermiksi.

**Comment by YSO-kokous** [comment]
Hyväksytään tpalonen-ehdotuksen mukaisesti.
