### ISSUE TITLE
ohjelmointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7712]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ohjelmointi](http://www.yso.fi/onto/ysa/Y97740) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT tietokoneohjelmointi, koodaaminen 

#### Perustelut ehdotukselle   

Ovat synonymejä

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotetut ohjaustermit.
