### ISSUE TITLE
Tenonlaakso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7713]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Tenonlaakso 

#### Ehdotettu termi ruotsiksi   

Tana älvdal 

#### Vaihtoehtoiset termit ja ilmaisut   

Tenonjokilaakso 
Tenojoen laakso 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tenonlaakson maisemanhoito- ja käyttösuunnitelma 

#### Perustelut ehdotukselle   

Melinda:
Tenojokilaakso x 5
Tenonlaakso x 3 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Tenonlaakso](http://finto.fi/yse/fi/page/Y507713)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon Tenojokilaakso, ohjaustermeiksi Tenonjokilaakso,Tenonlaakso ja Tenolaakso.
