### ISSUE TITLE
tunnistusmerkintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7714]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tunnistusmerkintä 

#### Tarkoitusta täsmentävä selite   

Vähän epämääräinen käsite, mutta kyseessä kissojen ja koirien tunnistusmerkintä. Myös termejä mikrosirut ja tatuointi (miksei tatuoinnit?) voisi laajentaa käsittämään nämä eläinten tunnistemerkinnät.
Eläinten merkintä kyllä löytyy, mutta ei oikein näihin sovi. 

#### Perustelut ehdotukselle   

https://www.kennelliitto.fi/koiran-omistaminen/koiran-tunnistusmerkinta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.elaintieto.fi/wp-content/uploads/2016/02/merkint%C3%A4_rekisteriselvitys_200315.pdf 

**Termiehdotus Fintossa:** [tunnistusmerkintä](http://finto.fi/yse/fi/page/Y507714)

**Comment by mariaforsen** [comment]
Tatuointi-termiä ei sovi sekoittaa eläinten tunnistusmerkintään. Tunnistusmerkintä sellaisenaan on hyvä ja tärkeä termi, kannatetaan. Googlessa yli 23 000. KT myös sirutus

Sv. id-märkning? https://sv.wikipedia.org/wiki/ID-m%C3%A4rkning_av_djur

**Comment by mirmaid** [comment]
Kerran Melindassa yksikössä, kerran monikossa. 
Onko termimuoto riittävän yksiselitteinen? Googlella rajautuu kyllä lähes täysin (lemmikki)eläimiin.

**Comment by krinay** [comment]
Pitäisikö jotenkin tuoda esille tämän käsitteen suhde tai ero eläinten merkintään, joka on jo YSOssa (ST pannoitus, rengastus)? Onko niin, että tunnistusmerkintä koskee lemmikkieläimiä ja eläinten merkintä muita eli tuotantoeläimiä ja luonnossa vapaana eläviä eläimiä? Vai onko käsitteillä hierarkkinen suhde toisiinsa? 

(Voisiko samalla lisätä eläinten merkinnän alakäsitteeksi tai korvatuksi käsitteeksi korvamerkinnän? Tai oikeastaan tarvetta olisi joskus ollut termille korvamerkit.)

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa tunnistusmerkintä (lemmikkieläimet). Yläkäsitteeksi eläinten merkintä.

**Comment by mariaforsen** [comment]
Sv. id-märkning (sällskapsdjur) ET id-märkning av sällskapsdjur

**Comment by mirmaid** [comment]
Käsittelemättä jäi vielä korvamerkintä/korvamerkit.

**Comment by mirmaid** [comment]
_Korvamerkit_ on AFOssa ja MAOssa ja sitä on käytetty runsaasti Melindassa, joten ehdotan, että otetaan se sanastoon.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon myös korvamerkit.
