### ISSUE TITLE
kirkonkirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7715]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kirkonkirjat](http://www.yso.fi/onto/ysa/Y96237) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään suomenkieliset KT-muodot "seurakuntien pääkirjat", "kuolleiden ja haudattujen luettelot", "vihittyjen luettelot" ja ruotsinkielinen KT-muoto "husförhörslängder" 

#### Perustelut ehdotukselle   

Kyseisiä termejä käytetään sukututkimuksessa ja ne olisi syytä saada viittausmuodoiksi, ruotsinkielisen osalta lähteenä https://sv.wikipedia.org/wiki/Husförhörslängd 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään kaikki ehdotetut ohjaustermit.
