### ISSUE TITLE
jättisolumyokardiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7716]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jättisolumyokardiitti 

#### Ehdotettu termi englanniksi   

giant cell myocarditis 

#### Perustelut ehdotukselle   

Jättisolumyokardiitti (giant cell myocarditis) on vakava sydämen tulehduksellinen sairaus. https://sydan.fi/fact/jattisolumyokardiitti/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1769-4 

**Termiehdotus Fintossa:** [jättisolumyokardiitti](http://finto.fi/yse/fi/page/Y507716)

**Comment by mariaforsen** [comment]
Sv. jättecellsmyokardit

**Comment by mirmaid** [comment]
Lääketieteen termit: jättisoluinen sydänlihastulehdus: _jättisolumyokardiitti | sydänlihastulehdus jonka yhteydessä tulehtuneessa sydänlihaskudoksessa on jättisoluja_.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
