### ISSUE TITLE
koraalialkusoitot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7717]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koraalialkusoitot](http://www.yso.fi/onto/ysa/Y214530) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Joko (1) lisätään KT-muoto "koraalipreludit" sekä YSOn että SLM:n puolelle tai (2) luodaan uusi asiasana ja lajityyppi-/muototermi "koraapreludit", josta on RT-suhde "koraalialkusoitot"-asiasanaan ja -lajityyppi-/muototermiin. 

#### Perustelut ehdotukselle   

Kyseinen nimitys on yleisessä käytössä, esim. Google yksistään suomeksi 370 osumaa haulla "koraalipreludi". 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by asormune** [comment]
Suositaanko suomalaista vai kansainvälistä nimitystä (alkusoitot/preludit)? Sanastossahan on termi alkusoitot (oopperat, orkesterimusiikki ..). Soitinmusiikissa (piano yms.) preludiksi nimetyt sävellykset on ylennsä kuvailtu termillä preludit. Eli ehkä ei yhtenäistäminen onnistu... Jos vaivaa säästetään, niin valitsisin vaihtoehdon nro 1.

**Comment by jaskaj** [comment]
Kannatan vaihtoehtoa 1.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta 1.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus 1.
