### ISSUE TITLE
syndekaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7718]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syndekaanit 

#### Vaihtoehtoiset termit ja ilmaisut   

syndecan-3 

#### Perustelut ehdotukselle   

En löytänyt tästä juurikaan tietoa, oliisko tuo syndecan-3 kuitenkin ainoa syndekaani?
https://finto.fi/mesh/fi/page/D053667
https://en.wikipedia.org/wiki/Syndecan-3 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1116-6 

**Termiehdotus Fintossa:** [syndekaanit](http://finto.fi/yse/fi/page/Y507718)

**Comment by mariaforsen** [comment]
Sv. syndekaner
On muitakin https://en.wikipedia.org/wiki/Syndecan_1

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
