### ISSUE TITLE
kansalliskomiteat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7719]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kansalliskomiteat 

#### Perustelut ehdotukselle   

https://www.academies.fi/kansalliskomiteoille/tieteenalakohtaiset-kansalliskomiteat/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.academies.fi/wp-content/uploads/2015/09/Arviointiraportti2015.pdf 

**Termiehdotus Fintossa:** [kansalliskomiteat](http://finto.fi/yse/fi/page/Y507719)

**Comment by HeidiRonkainen** [comment]
Selitys jäi pois:: Kansalliskomiteat ovat tietyn tieteenalan tai aihepiirin ympärille syntyneitä organisaatioita, jotka yhdistävät suomalaiset tutkijat omien alojensa kansainvälisiin tieteellisiin kattojärjestöihin.

**Comment by mariaforsen** [comment]
Sv. nationalkommittéer (vetenskaper)
https://www.kva.se/sv/om-oss/organistation/nationalkommitteer

**Comment by mirmaid** [comment]
https://www.academies.fi/kansalliskomiteoille/kansalliskomiteat-historiaa-ja-taustoja/

Jos halutaan rajata, tarvitsisi ehkä tarkenteen tai muun termimuodon (tieteenalojen kansalliskomiteat tms.)?

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa _kansalliskomiteat (tieteet)_.
