### ISSUE TITLE
taiteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7720]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taiteet](http://www.yso.fi/onto/ysa/Y156860) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "taiteenlajit" 

#### Perustelut ehdotukselle   

"Taiteenlaji" on paljon käytetty ilmaus, joten se pitäisi saada viittausmuodoksi seikasta käytettävään asiasanaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Tai muutetaan taiteet > taiteenlajit

**Comment by ilona-x** [comment]
YSO-kokous 6.2.2020: Muutetaan taiteet muotoon taiteenlajit. Ohjaustermiksi taiteet, ja taidelajit.

https://github.com/Finto-ehdotus/YSE/issues/6700
