### ISSUE TITLE
synaptinen plastisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7721]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

synaptinen plastisuus 

#### Ehdotettu termi englanniksi   

synaptic plasticity 

#### Ehdotettu termi ruotsiksi   

synaptisk plasticitet 

#### Perustelut ehdotukselle   

In neuroscience, synaptic plasticity is the ability of synapses to strengthen or weaken over time, in response to increases or decreases in their activity.
https://en.wikipedia.org/wiki/Synaptic_plasticity 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1397-9 

**Termiehdotus Fintossa:** [synaptinen plastisuus](http://finto.fi/yse/fi/page/Y507721)

**Comment by YSO-kokous** [comment]
Tarkistetaan kävisikö seuraava:
synaptinen plastisuus KÄYTÄ neuroplastisuus

**Comment by ilona-x** [comment]
FinMeSH: hermoston muovattavuus KT neuronaalinen plastisiteetti KT Synaptic Plasticity http://www.yso.fi/onto/mesh/D009473

**Comment by mirmaid** [comment]
Lääketieteen termit: 
**hermoston muovautuvuus** keskushermoston muovautuvuus, neuroplastisuus | keskushermoston kyky muuttaa synapsiyhteyksiä ja toimintaansa oppimisen yhteydessä tai ärsykkeiden tai vamman seurauksena
**synaptinen muovautuvuus** synaptinen plastisuus | synapsien kyky sopeutua muuttuneeseen tilanteeseen mm. lukumäärän tai toiminnan lisääntymisellä tai vähenemisellä (hermoston muovautuvuuden tärkein osatekijä)

**Comment by YSO-kokous** [comment]
Tehdään ohjaustermi:
synaptinen plastisuus KÄYTÄ neuroplastisuus
