### ISSUE TITLE
matrikkelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7722]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[matrikkelit](http://www.yso.fi/onto/ysa/Y97324) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "henkilömatrikkelit" sekä SLM:n että YSOn puolella 

#### Perustelut ehdotukselle   

Nimitystä "henkilömatrikkeli" käytetään sekä verkossa että itse julkaisuissa, joten siitä olisi hyvä saada viittausmuoto sanastoihin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Ok/SLM

**Comment by mariaforsen** [comment]
Sv. ET personmatriklar

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
