### ISSUE TITLE
vaalioikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7723]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaalioikeus 

#### Ehdotettu termi ruotsiksi   

valrätt 

#### Assosiatiiviset (RT)   

[vaalikelpoisuus](http://www.yso.fi/onto/yso/p9795) 
[äänioikeus](http://www.yso.fi/onto/yso/p9796) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Vaalioikeus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 

#### Perustelut ehdotukselle   

Tai KÄYTÄ vaalikelpoisuus, äänioikeus ?
Ks. TEPA, https://fi.wikipedia.org/wiki/Vaalioikeus, http://tieteentermipankki.fi/wiki/Oikeustiede:vaalioikeus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Muodollinen vaalioikeus, sen käyttäminen ja oikeussuoja. 

**Termiehdotus Fintossa:** [vaalioikeus](http://finto.fi/yse/fi/page/Y507723)

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi eli
vaalikoikeus KÄYTÄ vaalikelpoisuus
vaalioikeus KÄYTÄ äänioikeus
