### ISSUE TITLE
sovitukset (musikki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7724]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sovitukset (musikki) 

#### Ehdotettu termi ruotsiksi   

arrangeringar (musik) 

#### Ehdotettu termi englanniksi   

arrangements (music) 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014027203> 

#### Tarkoitusta täsmentävä selite   

"Sävellystä muokkaamalla esitettäväksi toisella kokoonpanolla tai toisen musiikkityylin mukaisesti" (kts. YSO-käsite "sovittaminen (musiikki)") luotuja objekteja sisältävän aineiston kuvailuun. 

#### Perustelut ehdotukselle   

SLM-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/015512455 

**Ehdottajan organisaatio:** Taideyliopisto **Termiehdotus Fintossa:** [sovitukset (musikki)](http://finto.fi/yse/fi/page/Y507724)

**Comment by asormune** [comment]
Korjaisin tarkenteesta termin: musikki > musiikki

**Comment by mirmaid** [comment]
Jos sanastoon jää myös laajempi sovitukset, tämän termin pitäisi olla _musiikkisovitukset_.

**Comment by mirmaid** [comment]
sovitukset > sovitukset (musiikki)

**Comment by mariaforsen** [comment]
Sv. bearbetningar > arrangeringar (musik)?

**Comment by mirmaid** [comment]
Ottaisiko Muusa kantaa myös termin suhteisiin (yläkäsite, RT-suhteet, ohjaustermit)?

**Comment by LeKorsu** [comment]
Jääkö olemassaoleva sovitukset ilman tarkennetta vai lisätäänkö sinne perään kirjallisuus, niin kuin nyt ovat ryhmät kirjallisuus ja musiikki?

**Comment by mariaforsen** [comment]
Yllä oleva koski ymmärtääkseni SLM (YSOssa edelleen yleismerkityksessä)

**Comment by krinay** [comment]
Mitä sovitukset tarkoittaa yleismerkityksessä? Yläkäsitteenä YSOssa on _teokset_ ja RT:inä _dramatisointi_ sekä _filmatisointi_, jolla puolestaan ohjaustermeinä _elokuva-adaptaatiot_, _elokuvasovitukset_, _filmatisoinnit_.

**Comment by YSO-kokous** [comment]
Sanastossa on jo "sovitukset", joka kattaa myös muut taiteet kuin musiikin. Muusa käsittelee tätä vielä ja laatii ehdotuksen.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa käsitteen _sovitukset (musiikki)_ ottamista YSOon.
LT musiikilliset objektit
RT cover-versiot
RT sovittaminen (musiikki)

**Comment by mariaforsen** [comment]
Siinä tapauksessa tarvitaan tarkenne nykyiselle sovitukset. Mutta onko todella ok jakaa sovitukset (musiikki) vs. kaikki muut sovitukset?

**Comment by mirmaid** [comment]
SLM: ohjaustermit pois, RT vain parafraasit (musiikki)

**Comment by mirmaid** [comment]
Ennen kuin tällaista jakoa voidaan toteuttaa, on ratkaistava miten kaikki muut sovituksia käsittelevät aineistot kuvailtaisiin. 

Musiikkisovitusten lisäksi näytelmäsovitukset on yleinen aihe (käyty läpi vain 50 ensimmäistä Melindan viitettä). Jos käytettäväksi käsitteeksi riittää _dramatisointi_, sille on lisättävä ohjaustermit _näyttämö-/näytelmäsovitukset_. Jos käsitellään kirjallisuudesta tehtyjä sovituksia, tämä on varmaankin ok, mutta entä onko myös elokuvan näyttämösovitus dramatisointi? https://melinda.kansalliskirjasto.fi/byid/013646985, https://melinda.kansalliskirjasto.fi/byid/011502416. 
Entä onko antiikin näytelmän sovittaminen nykyteatteriin myös vain dramatisointi? https://melinda.kansalliskirjasto.fi/byid/011421974 
Tai yleisemmin näytelmien versiointi? https://melinda.kansalliskirjasto.fi/byid/010855255

Dramatisointi: _näytelmäksi tai muuksi draamalliseksi esitykseksi sovittaminen_. https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:dramatisointi

_Kun alkujaan muuta genreä, esimerkiksi runoutta tai proosaa oleva materiaali järjestetään draamaksi tai esitykseksi, puhutaan materiaalin ”dramatisoinnista”. Usein esimerkiksi romaaneja dramatisoidaan elokuvakäsikirjoituksiksi tai näytelmiksi. Silti myös draamaksi kirjoitetun tekstin yhteydessä puhutaan usein dramatisoinnista, kun draamateksti tulkitaan esitykseksi. Kun valmista draamatekstiä (esimerkiksi ajallisesti vanhaa tekstiä) toimitetaan uutta esittämistä varten, puhutaan usein ”sovittamisesta”._ https://fi.wikipedia.org/wiki/Dramaturgia - Tämän perusteella antiikin näytelmien, Shakespearen jne. uusista näyttämöversioista tai elokuvista tehdyistä näytelmäversioista ei voi käyttää käsitettä _dramatisointi_. Mutta jos otetaan käsitteitä _sovitukset (elokuva), sovitukset (teatteri)_ ollaan tavallaan palaamassa ketjutukseen (?).

_Filmatisoinneista_ on myös runsaasti aineistoa. Kirjallisuudesta tai näytelmästä tehdyt elokuvat ovat varmasti filmatisointeja, mutta onko pelistä tehty elokuva filmatisointi? https://melinda.kansalliskirjasto.fi/byid/013995203, https://fi.wikipedia.org/wiki/Assassin%E2%80%99s_Creed_(elokuva) Entä onko pelistä tehty animaatioelokuva filmatisointi, vai jokin muu johdannaisteos?

Tulee mieleen myös näytellyt versiot animaatioelokuvista, esim. Disney-klassikoista - ne eivät varmaankaan voi olla _filmatisointeja_, mutta mitä ne sitten ovat, jos eivät _sovituksia_? 
Filmatisointi: _elokuvallistaminen, elokuvan tekeminen toiseen lajiin kuuluvan teoksen pohjalta_. http://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:filmatisointi

Entä mitä ovat tanssiteosten sovitukset: https://melinda.kansalliskirjasto.fi/byid/015273245

Osassa viitteitä on vaikea sanoa minkälaisista sovituksista on kyse, esim. https://melinda.kansalliskirjasto.fi/byid/015293107: _Intermedia is about the existence of combinatorial possibilities and hybridity leading to heterogeneity and complexity. The volume embraces this plurality and explores multiple historical origins and possible futures. Theories of “high” and “low” culture are examined and debated. A variety of cases that expand and reshape the debate on the operative workings of intermedia in diverse media forms and artistic genres including comic art, costume design, film, music, mythical narrative, new media, painting, poetry, television, textile art and game design are elaborated and discussed._

Entä tämä: https://kirjatkertovat.blogspot.com/2020/03/maria-laakso-taltuta-klassikko.html

**Comment by YSO-kokous** [comment]
Jos sanastoon otettaisiin "sovitukset (näytelmät)" yms niin palattaisiin ketjutustyyppisiin ratkaisuihin. Tähän ei haluta mennä. YSO-kokouksen toive on, että Muusan jäsenet tutustuvat ongelmaan yleissanaston kokonaisuuden näkökulmasta. Ks. mirmaid-kommentti edellä.

YSO-kokous suosittelee edelleen, että YSOssa olisi vain pelkkä yleismerkityksinen sovitukset. SLM:ssähän "sovitukset (musiikki)" jo joka tapauksessa on.

**Comment by MUUSA-kokous** [comment]
Muusa luopuu kannastaan käsitteen sovitukset (musiikki) ottamisesta YSOon.

**Comment by YSO-kokous** [comment]
Muusan päätös otettiin YSO-kokouksessa ilolla vastaan. Ei muutoksia YSOssa.
