### ISSUE TITLE
eheys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7725]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[eheys](http://www.yso.fi/onto/ysa/Y171375) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

onko määriteltävissä/jaettavissa? 

#### Perustelut ehdotukselle   

On monimerkityksinen https://fi.wikipedia.org/wiki/Eheys, ks. myös TEPA, http://finto.fi/tt/fi/page/t28 ja Melinda
Käännökset epäselvät.

**Comment by mirmaid** [comment]
Käytetty vain 20 kertaa Melindassa, onkohan välttämätön käsite?

**Comment by mariaforsen** [comment]
Ainakin "psyykkisessä" merkityksessä voidaan varmaan yhtä hyvin käyttää muita käsitteitä, esim. henkinen hyvinvointi jne. Ei näytä olevan välttämätön, ainakaan Melindan perusteella. Ja on tosiaan vaikea kääntää.

**Comment by YSO-kokous** [comment]
Poistetaan käsite "eheys".
