### ISSUE TITLE
sarabandet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7726]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarabandet 

#### Ehdotettu termi englanniksi   

sarabandes 

#### Ehdotettu termi ruotsiksi   

sarabander 

#### Vastaava käsite muussa sanastossa   

Sarabandes (Music) : <http://id.loc.gov/authorities/genreForms/gf2014027071> 

#### Tarkoitusta täsmentävä selite   

SLM-sanastoon. "Sarabande (ital. sarabanda, esp. zarabanda) on hidas kolmijakoinen tanssi, jonka ominaispiirteenä on toisen ja kolmannen iskun sitominen yhteen. Tästä syntyy tanssin erityispiirteinen rytmi, jossa vuorottelevat neljäsosa- ja puolinuotit. Sarabande on yksi barokkisarjan osista." Wikipedia 

#### Perustelut ehdotukselle   

Tarvitaan sarabande-aineiston kuvailuun. Termi on Sävellystyyppien nimet -luettelossa: http://urn.fi/URN:NBN:fi:au:mts:m1970,  ja se on käytössä musiikkiteoksen ensisijaisena nimekkeenä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/007250082 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [sarabandet](http://finto.fi/yse/fi/page/Y507726)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
RT tanssimusiikki
Myös YSOon tarvittaessa.

**Comment by mirmaid** [comment]
Hyväksytty/SLM

**Comment by YSO-kokous** [comment]
Hyväksytään myös YSOon.

**Comment by mirmaid** [comment]
Tuleeko tälle YSOon tarkenne (sävellykset)? Entä vastaava tanssi? https://fi.wikipedia.org/wiki/Sarabande vrt. muut sävellykset-käsitteen alakäsitteet.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa tarkennetta (sävellykset).

**Comment by mirmaid** [comment]
Entä vastaava tanssi? https://fi.wikipedia.org/wiki/Sarabande. Käytetty kerran Melindassa tanssista.

**Comment by jtuohini** [comment]
Mirjan kommenttiin liittyen: https://github.com/Finto-ehdotus/YSE/issues/8245
