### ISSUE TITLE
huilumusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7727]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

huilumusiikki 

#### Ehdotettu termi englanniksi   

flute music 

#### Ehdotettu termi ruotsiksi   

flöjtmusik 

#### Perustelut ehdotukselle   

Tarvitaan huilumusikkia käsittelevän aineiston kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000594983 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle huilulle tai muulle kokoonpanolle, jossa huilu on keskeisessä osassa. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [huilumusiikki](http://finto.fi/yse/fi/page/Y507727)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT soitinmusiikki

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus. Yläkäsitteeksi puhallinmusiikki.
