### ISSUE TITLE
työnopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7728]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työnopetus](http://www.yso.fi/onto/ysa/Y99783) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

onko poistettavissa tai määriteltävissä? 

#### Perustelut ehdotukselle   

Miten eroaa (myös sanastossa olevasta) perehdyttämisestä, toisaalta työssäoppimisesta yms? Ks. myös Finlex, on osittain käytetty eri merkityksestä (perehdyttämisestä) Melindassa. 
(Jos Finlex-merkitys niin ruotsinnos voisi olla arbetsundervisning, mutta jos perehdyttämisestä niin jonkinlainen "inskolning"? + tarkenne, toisaalta se on sitten virhe koska synonymi on jo sanastossa)

**Comment by mariaforsen** [comment]
Finlex-merkitys viitannee (ammatti)kouluissa tapahtuvaan opetukseen, esim. "lehtorin (työnopetus merimiesaineissa) virkaa,  lehtorin (ravitsemispalvelujen työnopetus) virkaa" jne. 

Sanakirjoista en löydä työnopetusta ollenkaan, paitsi tämä https://termipankki.fi/tepa/fi/haku/ty%C3%B6nopetus jossa se on nimenomaan opetusmerkityksessä (undervisning)

Kielitoimiston sanakirja: työssäoppiminen=toisen asteen ammatilliseen koulutukseen kuuluva opiskelun osa, joka järjestetään työtehtävissä alan työpaikassa. 

Perehdyttäminen: https://termipankki.fi/tepa/fi/haku/perehdytt%C3%A4minen

**Comment by ilona-x** [comment]
"Pe­reh­dyt­tä­mi­sel­lä tar­koi­te­taan kaik­kia nii­tä toi­men­pi­tei­tä, joi­den avul­la uusi työn­te­ki­jä op­pii tuntemaan työpaikkansa, sen ta­vat, ih­mi­set ja työ­hön­sä liit­ty­vät odo­tuk­set.

Työn­o­pas­tuk­seen kuu­lu­vat kaik­ki ne asi­at, jot­ka liit­ty­vät itse työn te­ke­mi­seen. Näi­tä ovat esi­mer­kik­si työ­ko­ko­nai­suus sekä se, mis­tä osis­ta ja vai­heis­ta työ koos­tuu sekä mitä tie­toa ja osaa­mis­ta työ edel­lyt­tää."

Lähde: https://ttk.fi/koulutus_ja_kehittaminen/julkaisut/digijulkaisut/perehdyttaminen_ja_tyonopastus_-_ennakoivaa_tyosuojelua

**Comment by tpalonen** [comment]
Eivät mielestäni ole täysiä synonyymeja. Työnopetus liittyy nimenomaan työn opetukseen. Perehdytystä voi antaa muuhunkin kuin työhön (perehdytys tietotekniikkaan senioreille tms), ja toisaalta työkontekstissa se voi kohdistua vain johonkin työkaluun, työtehtävään tms, kun taas työnopetus keskittynee työntekemiseen kokonaivaltaisemmin.

Käytetty kylläkin paljon kuvailussa päällekkäin. Vrt myös YSOn huomautus työnohjaus -käsitteessä: "Tarkoittaa työntekijöiden ohjausta työhön liittyvien ongelmien ratkaisemiseksi. Työn opastuksen yhteydessä käytä käsitettä työnopetus ja/tai perehdyttäminen."

**Comment by mirmaid** [comment]
Onkohan tuota _työnohjaus_-käsitettä käytetty huomautuksen linjaamalla tavalla...muutenkin määritelmä on vähän suppea, vaikka ehkä tuo esiin toiminnan keskeisen tarkoituksen. 

Voisiko ruotsinkielisen termin muuttaa TEPAn mukaiseksi? Onko siinäkin tapauksessa päällekkäisyys iso ongelma? Ja rajautuuko tuo undervisning ehdottomasti **oppilaitoksessa** annettavaan opetukseen?

**Comment by ilona-x** [comment]
JUHOssa näköjään yhdistetty näin: työnopetus KÄ **perehdytys**. http://www.yso.fi/onto/juho/p2754 Lisäksi JUHOssa myös **työnohjaus** http://www.yso.fi/onto/juho/p10995

**Comment by ilona-x** [comment]
> 
> 
> "Pe­reh­dyt­tä­mi­sel­lä tar­koi­te­taan kaik­kia nii­tä toi­men­pi­tei­tä, joi­den avul­la uusi työn­te­ki­jä op­pii tuntemaan työpaikkansa, sen ta­vat, ih­mi­set ja työ­hön­sä liit­ty­vät odo­tuk­set.
> 
> Työn­o­pas­tuk­seen kuu­lu­vat kaik­ki ne asi­at, jot­ka liit­ty­vät itse työn te­ke­mi­seen. Näi­tä ovat esi­mer­kik­si työ­ko­ko­nai­suus sekä se, mis­tä osis­ta ja vai­heis­ta työ koos­tuu sekä mitä tie­toa ja osaa­mis­ta työ edel­lyt­tää."
> 
> Lähde: https://ttk.fi/koulutus_ja_kehittaminen/julkaisut/digijulkaisut/perehdyttaminen_ja_tyonopastus_-_ennakoivaa_tyosuojelua

Tuossa näköjään onkin **työnopastus** eikä **työnopetus**. YSOssa työnopastus ohjaa KÄYTÄ perehdyttäminen.

****

Melinda: 
työnopetus 710
työnopetus + perehdyttäminen 367
työnopetus + työssäoppiminen 80
työnopetus + työnohjaus 97

**Comment by mariaforsen** [comment]
Kyllä, olisin taipuvainen laittamaan TEPAn arbetsundervisning vastineeksi jos ei tästä päästä eroon. Käytössä tosin rajautuu kyllä aika varmasti oppilaitoksiin, eli kieltenvälinen vastaavuus kärsii, ellei suomeksi rajata "perehdytys"-merkitystä pois. 

Ainakin ruotsin osalta olisi JUHOn tekemä ratkaisu paras, eli ettei työnopetusta olisi erillisenä pääterminä. Mielestäni tämän termin (työnopetus) google-käyttö ja "olemattomuus" sanakirjoissa, sekä Melinda-käytön päällekkäisyys puhuisi myös vahvasti tämän puolesta.

**Comment by mirmaid** [comment]
_Perehdyttäminen_ ei kuitenkaan sovi niihin aineistoihin, joissa kyse on nimenomaan ammatillisesta opetuksesta, joten ehkä tarkenne olisi parempi ratkaisu? Siis onhan tuossa nyt yli 300 Melinda-viitettä, joissa ei ole perehdyttäminen-käsitettä (toki niistäkin osa voi olla virheellisiä).

**Comment by YSO-kokous** [comment]
Lisätään seuraava ohjaustermi: työnopetus (perehdyttäminen) KÄYTÄ perehdyttäminen.
Säilytetään työnopetus-käsite toistaiseksi sanastosta.

Poistetaan Melinda-kuvailusta työnopetus kaikesta missä on perehdyttäminen ja kaikesta missä on työnohjaus.
Käsitellään jäljelle jäävä kuvailu pohtimalla, sopisiko tietueisiin paremmin perhdyttäminen tai työnohjaus. Tämän jälkeen pohditaan vielä, mitä tehdään työnopetus-käsitteelle: esim. työnopetus (ammatillinen koulutus)?

**Comment by mirmaid** [comment]
Työnohjauksen huomautusta varmaan muokattava jos rajataan työnopetusta: http://www.yso.fi/onto/yso/p297.

**Comment by mariaforsen** [comment]
Näin pitää tehdä kyllä, jos lisätään tarkenne (ammatillinen koulutus)

**Comment by ilona-x** [comment]
Melindaa selatessa tuli vastaan vielä yksi tähän settiin mahdollisesti liittyvä YSO-termi: 
**käytännön opetus** http://www.yso.fi/onto/yso/p10227

**Comment by ilona-x** [comment]
Uusimpien Melinda-viitteiden perusteella työnopetus (ammatillinen koulutus) ei olisi tarpeellinen, vaan työnopetus olisi näissä korvattavissa/korjattavissa muilla termeillä, perehdytys, työssäoppiminen, ohjaus (neuvonta ja opastus) jne. Noin 100 tuoreimman viitteen joukosta löytyi varmuudella yksi, johon olisi ollut sopiva työnopetus (ammatillinen koulutus).

Vanhimmissa viitteissä, joissa on käytetty työnopetus -termiä,  löytyy muutamia, joissa työnopetus (ammatillinen koulutus) voisi olla käyttökelpoinen:

- Työnopetusoppi / Erkki Mielonen
- Begriff der Arbeitsschule /von Georg Kerschensteiner.
- Työnopetuksen teoriaa ja käytäntöä.1 osa / O. K. Kyöstiö.
- Vastuunalainen työnjohtaja alaistensa työnopettajana ja aikuiskasvattajana :kasvatussosiologista tarkastelua 
- Perustamme työluokan : ohjekirja ammattikoulujen ja kansalaiskoulujen opettajille 
- Opetustoiminnan taustaa ja työnopetus Hirvaan metsäkonekoulussa 

Melindassa työnopetus on käytetty 328 kertaa, joten työnopetus (ammatillinen koulutus) kattaisi näistä vain murto-osan.

**Comment by YSO-kokous** [comment]
Poistetaan "työnopetus". Korvaavia termejä  esim. työnohjaus, perehdytys, käytännön opetus
