### ISSUE TITLE
interjektiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7729]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[interjektiot](http://www.yso.fi/onto/ysa/Y101860) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT huudahdussanat 

#### Perustelut ehdotukselle   

On synonymi. Ks. esim. http://tieteentermipankki.fi/wiki/Nimitys:huudahdussana

**Comment by mariaforsen** [comment]
Sv. ET utropsord

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
