### ISSUE TITLE
akryyli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7730]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[akryyli](http://www.yso.fi/onto/ysa/Y106692) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT polymetyylimetakrylaatti 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Akryyli

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermi.
