### ISSUE TITLE
sarjakuvaelämäkerrat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7731]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarjakuvaelämäkerrat 

#### Ehdotettu termi englanniksi   

biographical comics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sarjakuvat](http://www.yso.fi/onto/yso/p1148) 

#### Vastaava käsite muussa sanastossa   

OCoLC : biographical comics 

#### Tarkoitusta täsmentävä selite   

Sarjakuvamuotoiset elämäkerrat, jotka sisältönsä puolesta voidaan sijoittaa tietokirjahyllyyn. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi Jim Ottavianin Feynman (978-1-59643-827-9) ja Guy Delislen sarjakuvat (Merkintöjä Burmasta ym.) 

#### Perustelut ehdotukselle   

Tietokirjallisuutta sarjakuvamuodossa ilmestyy paljon, eikä kaikkea voi pitää 'opetussarjakuvana'. Olisi myös hyvä jos slm:ssä olisi suomenkielinen vastine termille 'graphic nonfiction', sille en kylläkään keksinyt ehdotettavaa termiä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [sarjakuvaelämäkerrat](http://finto.fi/yse/fi/page/Y507731)

**Comment by ilkkahaataja** [comment]
SLM-sanastossa varmaan myös tällä nyt ehdotetulla olisi eniten käyttöä. Kuinkahan vakiintuneesta termistä on kysymys? Termi "elämäkertasarjakuvat" sopisi muiden sarjakuvan alalajien joukkoon, jotka ovat lähes järjestään sarjakuva-loppuisia (vrt. myös "elämäkertaelokuvat"). Samaa mieltä "graphic nonfiction" termin suomenkielisen vastineen tarpeesta SLM-sanastossa.

**Comment by AuHo22** [comment]
Tietosarjakuvat muotoa löytyy.

**Comment by mirmaid** [comment]
elämäkertasarjakuvat KT elämäkerralliset sarjakuvat, sarjakuvaelämäkerrat

**Comment by mariaforsen** [comment]
Sv. biografiska serier https://seriewikin.serieframjandet.se/index.php/Biografiska_serier

**Comment by YSO-kokous** [comment]
Otetaan käsite sanastoon. Tutkitaan, mikä termeistä on sopivin/vakiintunein.
