### ISSUE TITLE
Ei-fiktiiviset sarjakuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7732]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ei-fiktiiviset sarjakuvat 

#### Ehdotettu termi englanniksi   

Nonfiction comics ; Graphic non-fiction 

#### Ehdotettu termi ruotsiksi   

Icke-fiktiva tecknade serier 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026453> 

#### Tarkoitusta täsmentävä selite   

SLM-sanastoon. "Comics that are intended to be educational or informational or that present facts or true accounts." (LCGFT) 

#### Perustelut ehdotukselle   

Tarvitaan SLM-sanastoon ei-fiktiivisten sarjakuvien yläkäsitteeksi ja käytettäväksi ei-fiktiivisistä sarjakuvista, jotka eivät edusta mitään sanastoon kuuluvista alalajeista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/010007845 

**Ehdottajan organisaatio:** Taideyliopisto **Termiehdotus Fintossa:** [Ei-fiktiiviset sarjakuvat](http://finto.fi/yse/fi/page/Y507732)

**Comment by mirmaid** [comment]
Seuraava kokous

**Comment by mariaforsen** [comment]
Ei juuri google-osumia suomeksi tai ruotsiksi. Entä tietosarjakuvat?

**Comment by mirmaid** [comment]
^ Parempi termi ja meidän alalla varmaan ihan käytetty, mutta silläkin hyvin vähän Google-viitteitä.

**Comment by LeKorsu** [comment]
En kannata ei-fiktiivinen-alkuista, se kuulostaa niin suoralta käännökseltä englanniksi. Muutoinkin näyttäisivät "ei-"-alkuiset olevan ohjaustermeinä, esim. ei-fiktiivinen romaani KÄ dokumenttiromaanit, ei-esittävä taide KÄ abstrakti taide. 

Dokumenttisarjakuvat?

**Comment by YSO-kokous** [comment]
Tutkitaan vielä, mikä olisi vakiintunein termi.

**Comment by tpalonen** [comment]
Tiedustelin asiaa Sarjainfolta, mutta sieltä ei osattu tarjota yhtä suositeltavaa termiä: "Kysymys on vähän visainen." Koska mitään vakiintunutta termiä ei tunnu olevan niin suosittelisin itse termiä **tietosarjakuva**, joka täälläkin on jo mainittu. Se on parempaa suomea kuin ei-fiktiivinen ja minusta myös laajemmin käytettävissä kuin dokumenttisarjakuva. Sarjakuva voi perustua faktoihin tai yhdistellä faktaa ja fiktiota, mutta ei välttämättä ole dokumentaarinen, ainakaan jos dokumentaarisuudella tarkoitetaan "mahdollisimman totuudenmukaista" (https://mediataidekasvattaa.fi/oppimateriaalit/kuka-kertoo/dokumentaarinen-elokuva/). Toisaalta strippimittaisen tietopohjaisen sarjakuvan nimittäminen dokumentaariseksi saattaisi myös tuntua vähän oudolta. Esim. Liv Strömquistin sarjakuvat perustuvat paljolti faktoihin ja tutkimustietoon ja ovat hieman esseemäisiä (https://fi.wikipedia.org/wiki/Liv_Str%C3%B6mquist) ja suosittu xkcd-verkkosarjakuva on vahvasti tietopohjainen (https://xkcd.com/). Voisin kutsua kumpaakin näistä tietosarjakuvaksi, mutta en ehkä niinkään dokumenttisarjakuvaksi.


Dokumenttisarjakuvat ja ei-fiktiiviset sarjakuvat voisivat sopia ohjaustermeiksi.

**Comment by tpalonen** [comment]
Pari lisäesimerkkiä faktoihin perustuvasta / faktoja hyödyntävästä sarjakuvasta aiheesta kiinnostuneille:
https://www.drawnandquarterly.com/department-mind-blowing-theories
https://www.dailycartoonist.com/index.php/2020/01/23/patrick-reynolds-has-historical-flashbacks/

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa tietosarjakuvat, ohjaustermiksi dokumenttisarjakuvat ja ei-fiktiiviset sarjakuvat.

**Comment by mariaforsen** [comment]
Sv. faktaserier (tecknade serier) ET dokumentära tecknade serier https://seriewikin.serieframjandet.se/index.php/Faktaserier

**Comment by mirmaid** [comment]
Hyväksytty/YSO.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
