### ISSUE TITLE
loppuunmyyty

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7733]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

loppuunmyyty 

#### Ehdotettu termi ruotsiksi   

utgången 

#### Ehdotettu termi englanniksi   

out of print 

#### Vaihtoehtoiset termit ja ilmaisut   

loppuunmyyty kirja 
utgången bok 
out of print book 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirjat](http://www.yso.fi/onto/yso/p156) 

#### Assosiatiiviset (RT)   

[painokset](http://www.yso.fi/onto/yso/p26771) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85096133> 
wikidata : https://www.wikidata.org/wiki/Q3831846 
wikidata : https://www.wikidata.org/wiki/Q655681 
LCSH : <http://id.loc.gov/authorities/subjects/sh2003000508.html> 

#### Perustelut ehdotukselle   

Ehdotetaan Metatietosanastoon -- 

#### Tarkoitusta täsmentävä selite   

Painos loppu kustantajalta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vastaavan tiedon paikka Marcissa kenttä 366 $e   https://www.kiwi.fi/pages/viewpage.action?pageId=51282054#id-3XXFyysisenkuvailunjne.kent%C3%A4t-366  Paikka:  myös Manifestaatio/Jakelutiedot 

**Ehdottajan organisaatio:** kansalliskirjasto **Termiehdotus Fintossa:** [loppuunmyyty](http://finto.fi/yse/fi/page/Y507733)

**Comment by jtuohini** [comment]
En kannata termin ottamista SLM-sanastoon, koska tietyn painoksen loppuminen kustantajalta ei ole teoksen, ekspression eikä edes manifestaation pysyvä ominaisuus eikä siksi kuulu SLM-sanastoon. Siltausehdotuskin johtaa LCSH-asiasanastoon, ei Kongressin kirjaston lajityyppi- ja muotosanastoon (LCGFT); kyseisellä asiasanalla on tarkoitus kuvailla aineistoa, jonka aiheena ovat loppuunmyydyt kirjat ym.
 
Marc 21 -formaatissa näyttää olevan paikka tämän tiedon ilmaisemiselle, osakenttä 366 |c (https://www.loc.gov/marc/bibliographic/bd366.html).

**Comment by mariaforsen** [comment]
Sv. utgången/slutsåld
