### ISSUE TITLE
kestävyysurheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7734]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kestävyysurheilu 

#### Ehdotettu termi englanniksi   

endurance sport 

#### Vaihtoehtoiset termit ja ilmaisut   

kestävyysliikunta 

#### Ehdotettu yläkäsite YSOssa (LT)   

[urheilulajit](http://www.yso.fi/onto/yso/p894) 

#### Alakäsitteet (RT)   

[kestävyysjuoksu](http://www.yso.fi/onto/yso/p2711) 
[triathlon](http://www.yso.fi/onto/yso/p17107) 
[pyöräily](http://www.yso.fi/onto/yso/p10409) 
[maastopyöräily](http://www.yso.fi/onto/yso/p11650) 
[hiihto](http://www.yso.fi/onto/yso/p11094) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

#### Tarkoitusta täsmentävä selite   

yksilölajit, joissa suoritukset ovat pitkäkestoisia ja teho submaksimaalisella tasolla (https://medical-dictionary.thefreedictionary.com/Endurance+Sport) 

#### Perustelut ehdotukselle   

Asiasanastossa on mm. satuliikunta ja Sherborne-liikunta (anteeksi mikä -borne?), mutta ei vielä kestävyysurheilua vaikka tämän suosio kasvaa jatkuvasti :) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

syventävien opintojen tutkielma 

**Ehdottajan organisaatio:** Itä-Suomen yliopisto (opiskelija) **Termiehdotus Fintossa:** [kestävyysurheilu](http://finto.fi/yse/fi/page/Y507734)

**Comment by mariaforsen** [comment]
Sanastossa on ennestään kestävyyslajit, pitäisikö yhdistää jotenkin?

**Comment by tiiabo** [comment]
'Kestävyyslajit' on kieltämättä aika lähellä oleva käsite 'kestävyysurheilu':n kanssa. Jos näille pitäisi keskinäinen suhde jäsentää, niin näkisin, että kestävyysurheilua harrastetaan ja ne lajit, mitä siihen sisältyy, ovat kestävyyslajeja. Vaikkakaan ilmaisut "Harrastan kestävyyslajeja" / "Harrastan kestävyysurheilua" eivät juuri sisällöltään taida erota.

**Comment by YSO-kokous** [comment]
Otetaan ohjaustermiksi eli kestävyysurheilu KÄYTÄ kestävyyslajit.
