### ISSUE TITLE
soul jazz

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7735]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soul jazz 

#### Ehdotettu termi englanniksi   

soul jazz 

#### Ehdotettu termi ruotsiksi   

soul jazz 

#### Tarkoitusta täsmentävä selite   

Jazz-musiikin tyylisuunta, joka on omaksunut vahvoja vaikutteita soulista, rhythm and bluesista ja gospelista. Kokoonpanot ovat pienehköjä, usein kolme tai neljä soittajaa. Aiemmin jazziin kuulumattomat urut ovat yleinen soitin soul jazzissa.

Tyylille tyypillisiä ovat edeltävää jazzia useammin käytetyt hieman monotoniset, tanssimaiset rytmit ja selkeät melodiat. Soul jazzin lähin sukulainen jazzin kentällä on hard bop, joka on ottanut vaikutteita samoista populaarimusiikin tyyleistä.  (Wikipedia) 

#### Perustelut ehdotukselle   

Tarvitaan ainakin SLM-sanastoon soul jazzin äänitteiden ja nuottien kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jukka Eskola Soul Trio 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [soul jazz](http://finto.fi/yse/fi/page/Y507735)

**Comment by asormune** [comment]
Sanastossa on soulblues, niin miksikä ei myös soul jazz. Kirjoitettaisiinko yhteen vai erikseen?

**Comment by tpalonen** [comment]
Kirjoittaisin yhteen.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa yhteenkirjoitettuna.
LT jazz
RT soul jazz
RT soul
Tarvittaessa myös YSOon.

**Comment by mariaforsen** [comment]
Sv. soul jazz ET souljazz

**Comment by mirmaid** [comment]
souljazz KT soul jazz

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by YSO-kokous** [comment]
Hyväksytään yhteenkirjoitettuna. Soul jazz ohjaustermiksi.
