### ISSUE TITLE
Laki saatavien perinnästä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7736]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Laki saatavien perinnästä 

#### Perustelut ehdotukselle   

https://www.finlex.fi/fi/laki/ajantasa/1999/19990513?search%5Btype%5D=pika&search%5Bpika%5D=laki%20perinn%C3%A4st%C3%A4 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Laki saatavien perinnästä](http://finto.fi/yse/fi/page/Y507736)

**Comment by mariaforsen** [comment]
Sv. lag om indrivning av fordringar
