### ISSUE TITLE
kielentutkimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7737]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kielentutkimus](http://www.yso.fi/onto/ysa/Y161697) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään asiasanalle käyttöohje tai yhdistetään se asiasanan "kielitiede" kanssa. 

#### Perustelut ehdotukselle   

Asiasanat "kielentutkimus" ja "kielitiedet" ovat YSOssa rinnakkaistermejä, mutta niiden merkityseroa ei ole ilmaistu eikä termien käyttöä koskevia ohjetta annettu, mistä seuraa helposti sekaannusta. Google-haku sanalla kielentutkimus tuntuu viittaavan samaan kuin kielitiede. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi språkvetenskap, språkforskning, eli ei aivan sama asia. Myös SAOssa on molemmat.

**Comment by ilona-x** [comment]
Tieteen termipankissa: 
kielitiede | lingvistiikka | kielentutkimus 
http://tieteentermipankki.fi/wiki/Kielitiede:kielitiede

YSOssa samankaltainen tapaus: kirjallisuustiede KÄYTÄ kirjallisuudentutkimus

**Comment by mirmaid** [comment]
Melindassa kielitiede 19701 viitettä, kielentutkimus 1990 viitettä.

**Comment by mirmaid** [comment]
Myös musiikkitiede yhdistettiin > KÄ musiikintutkimus.

**Comment by YSO-kokous** [comment]
Selvitetään vielä Melindassa miten paljon "kielentutkimus" olisi korvattavissa termillä käsitteellä "kielitiede", silloin kun se on yksinään. Jos suurimpaan osaan käy kielitiede, niin voidaan yhdistää. 
onko kielentutkimusta, joka ei ole kielitiedettä? 
Palataan seuraavassa kokouksessa.

**Comment by mirmaid** [comment]
_Kielitiede_ otettu YSAan -87, _kielentutkimus_ 2008.

**Comment by mirmaid** [comment]
Melindassa on 1234 viitettä, joissa on _kielentutkimus_, mutta ei kielitiedettä. Osassa kielentutkimus viittaa nimenomaan käytännön tutkimustyöhön, usein kielenkäytön tutkimukseen. 

Esim. 
https://melinda.kansalliskirjasto.fi/byid/013392688
https://melinda.kansalliskirjasto.fi/byid/008912157

Viimeisten kahden vuoden aika kielentutkimusta on käytetty ilman kielitiede-termiä 20 kertaa. Usein se olisi vaihdettavissa > kielitiede, mutta silloin kun kyseessä on nimenomaan itse tutkimiseen liittyvä puoli, tai tutkimuskohteena on kielenkäyttö tai sanasto (eikä kielen rakenne, kielioppi), kielentutkimus soveltuu ehkä paremmin. 

Esim.
https://melinda.kansalliskirjasto.fi/byid/018059497
https://melinda.kansalliskirjasto.fi/byid/017992624
https://melinda.kansalliskirjasto.fi/byid/017553737
https://melinda.kansalliskirjasto.fi/byid/017445826
https://melinda.kansalliskirjasto.fi/byid/017422639
https://melinda.kansalliskirjasto.fi/byid/017419280

**Comment by mirmaid** [comment]
Sanastossa on muuten myös metsätieteet + metsäntutkimus, työtiede + työntutkimus.

**Comment by AuHo22** [comment]
kirjallisuustiede KÄ kirjallisuudentutkimus

**Comment by mirmaid** [comment]
^ Näin on muistaakseni ollut koko ajan.

**Comment by YSO-kokous** [comment]
### Päätös äänestyksen jälkeen
Ei muutosta. Säilytetään erillisinä käsitteinä kielitiede ja kielentutkimus.
Voidaan lisätä määritelmä tai käyttöhuomautus molemmille, josta selviää näiden ero.
