### ISSUE TITLE
sähköhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7738]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sähköhoito](http://www.yso.fi/onto/ysa/Y104476) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko vai määritelläänkö? 

#### Perustelut ehdotukselle   

Kaksi eri merkitystä: http://finto.fi/mesh/fi/page/?uri=D004599 ja http://finto.fi/mesh/fi/page/D004565
Eng. on nyt electrotherapy (toinen merkitys on electroconvulsive therapy).

**Comment by mariaforsen** [comment]
Ruotsiksikin siis eri termejä näille eri merkityksille.

**Comment by mirmaid** [comment]
Käytetty molemmissa merkityksissä.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon sähköärsytyshoito ja sähköshokkihoito. Molemmille ohjaustermiksi sähköhoito. Poistetaan sähköhoito.
