### ISSUE TITLE
afrikanöljypalmu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7739]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

afrikanöljypalmu 

#### Ehdotettu termi englanniksi   

Oil palm 

#### Vaihtoehtoiset termit ja ilmaisut   

Elaeis guineensis 
öljypalmu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[öljypalmut](http://www.yso.fi/onto/yso/p21273) 

#### Assosiatiiviset (RT)   

[palmuöljy](http://www.yso.fi/onto/yso/p20869) 

#### Vastaava käsite muussa sanastossa   

afrikanöljypalmu : https://laji.fi/taxon/MX.5009495 
Oil palm : <http://id.loc.gov/authorities/subjects/sh85094341.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [afrikanöljypalmu](http://finto.fi/yse/fi/page/Y507739)

**Comment by mariaforsen** [comment]
Sv. oljepalm ET afrikansk oljepalm
