### ISSUE TITLE
öljypalmut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7740]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[öljypalmut](http://www.yso.fi/onto/ysa/Y158868) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

öljypalmut (suku Elaeis) 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.5008972
Elaeis http://id.loc.gov/authorities/subjects/sh88000873.html 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv.  oljepalmssläktet ET oljepalmer

**Comment by mirmaid** [comment]
Ehdotus ilmeisesti ohjaustermistä?

**Comment by YSO-kokous** [comment]
Lisätään öljypalmuille ohjaustermiksi Elaeis.
