### ISSUE TITLE
vihkiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7742]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vihkiminen](http://www.yso.fi/onto/ysa/Y104859) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö määritelmä tai mahdollisesti tarkenne? 

#### Perustelut ehdotukselle   

On monimerkityksinen termi ja Melindassa käytetty jonkin verran myös muusta kuin häiden vihkimisestä. Sv. ja eng. taas viittaavat vain siihen.

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

vihkiä
1. papista tms. viranomaisesta: vahvistaa avioliitto määrämuotoja noudattaen. Vihkiä nuoret avioliittoon. Pari vihittiin kirkossa, maistraatissa. Suorittaa vihkiminen. Kirkollinen vihkiminen. Siviilivihkiminen. Vihittävät asettuvat vihkijän eteen morsian sulhasen vasemmalle puolelle. Eilen vihitty nuoripari.
2. asettaa jku t. jk juhlallisin menoin määräarvoon t. tehtävään; vrt. promovoida. Vihkiä papiksi, piispaksi, nunnaksi. Promootiossa vihityt maisterit, tohtorit. Pyrkijä vihitään määrämenoin veljeskunnan jäseneksi. Vihkiä kirkko, silta, tehdas (tarkoitukseensa). Järjestön lipun vihkiminen.
Ylät. Kuolemaan vihityt uhrit.
3. perehdyttää, tutustuttaa. Vihki oppilaansa maalaustaiteen salaisuuksiin.

**Comment by ilona-x** [comment]
KAUNOssa vihkiminen KT avioliittoon vihkiminen, jonka voisi ottaa YSOon päätermiksi? 

YSOssa erikseen pappisvihkimys & piispanvihkimys.

Käyty läpi Melindasta 100 viitettä. Suurin osa käsitteli avioliittoon vihkimistä, jonkin verran piispan- & pappisvihkimystä. Lisäksi vihittiin seuraavia/seuraaviin:

- koulurakennukset
- Saimaan kanava
- diakonit
- kirjastorakennukset
- salaseurat
- kirkkorakennukset
- tuulivoimalat

**Comment by jarmosaarikko** [comment]
Mieluummin "vihkiminen" pääterminä  ja sen alla erikseen alakäsitteenä muut vihkimiset: "avioliittoon vihkiminen", "siviilivihkiminen", tämän alle. Takautuva korjaaminen lienee kuitenkin vaivalloista? Muilla kielillä enemmän vaihtoehtoja?

**vihkiminen** - KT "vihkimys" - invigning@sv,  inauguration@en, KT commissioning@en   paikan tai esineen ym.s vihkiminen menisivät tänne?

RT initiaatiot LT siirtymäriitit  (tämä lienee sama kuin "vihkiminen salaisuuteen")

NT:  **avioliittoon vihkiminen@fi**, - vigsel@sv KT "kyrklig vigsel"@sv - "solemnizing a marriage"@en 
NT:  **siviilivihkiminen**, "borgerlig vigsel"@sv, "civil marriage ceremony"@en
tarvittaessa:
NT  **ordinaatio** KT virkaan vihkiminen  - ordination@sv - ordination@en, consecration@en
   RT pappisvihkimys 
   RT piispanvihkimys

**Comment by ilona-x** [comment]
Jos sanastoon jää vihkiminen ilman tarkennetta, sitä käytettäisiin sellaisissakin tapauksissa, joissa tulisi käyttää tarkempaa käsitettä kuten avioliittoon vihkiminen.

Itse en koe kovin tarpeellisena kuvailussa tuota rakennusten ym. käyttöönoton yhteydessä tapahtuvaa "vihkimistä".

**Comment by mariaforsen** [comment]
Ruotsin osalta ei voida tehdä niin että vihkiminen olisi invigning, vaan vihkiminen yläkäsitteenä täytyisi sitten olla "vigande/vigning. (Invigning~"formaali avaaminen", yleensä rakennuksen, paikan tms.) Erityisen tärkeää on ettei sekoiteta avioliittoon vihkimistä muiden kanssa, se menisi sitten ruotsin osalta väärin. Kannatan siis että ainakin "avioliittoon vihkiminen" otetaan erillisenä.

Ruotsin osalta:
    koulurakennukset invigning
    Saimaan kanava invigning
    diakonit vigning
    kirjastorakennukset invigning
    salaseurat invigning > invigningsrit > initiation (jo YSOssa)
    kirkkorakennukset invigning
    tuulivoimalat invigning

**Comment by tpalonen** [comment]
vihkiminen (käyttöönotto/avajaiset) KÄYTÄ käyttöönotto/avajaiset ?

**Comment by mirmaid** [comment]
^ En tiedä onko välttämättä tarpeellinen ohjaus. Itse saattaisin viitteitä korjatessa siirtää ennemmin 653-kenttään _vihkiminen_-termin niissä tapauksissa, joissa aiheena on nimenomaan vihkimisjuhlallisuudet, käyttöönotto on kuitenkin paljon laajempi käsite ja avajaiset ei myöskään aina sovellu (esim. Några anteckningar till frågan om Åbo domkyrkas invigning).

**Comment by YSO-kokous** [comment]
Otetaan avioliittoon vihkiminen sanastoon. Poistetaan vihkiminen yleismerkityksessä.
