### ISSUE TITLE
sotilaalliset järjestöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7743]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sotilaalliset järjestöt](http://www.yso.fi/onto/ysa/Y99002) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko yhdistettävissä hierarkisoivan termin "sotilaalliset organisaatiot" kanssa? 

#### Perustelut ehdotukselle   

Ovat synonymisiä ja vaikka toinen onkin hierarkisoiva, niin linjausten mukaan ei varmaan molempia pidetä? Ruotsiksi nyt militära organisationer ja militärorganisationer=sama asia. 
Kielitoimiston sanakirja: järjestö=henkilöiden t. yhteisöjen määrätarkoitusta varten perustama yhteenliittymä, organisaatio. Ks. myös Melinda (järjestö=förening ei ole mahdollinen).

**Comment by mirmaid** [comment]
Vähän hankala, koska suomeksi kaikki organisaatiot eivät ole järjestöjä. Kattaako _militärorganisationer_ myös esim. armeijat tai kaukopartiot?

**Comment by mariaforsen** [comment]
Organisation=större, sam­ordnad grupp med viss mål­sättning
(förening=organiserad grupp med viss välbestämd verksamhet vanligen på lokal nivå)
Eli nämä menevät aika lailla tämän mukaan: 
järjestö=henkilöiden t. yhteisöjen määrätarkoitusta varten perustama yhteenliittymä, organisaatio

Ruotsiksi siis olennaista oli tässä se että näitä molempia ei voi olla, koska ne ovat aika lailla synonymisia (se että valitaanko militärorganisationer vai militära organisationer päätermiksi on toissijainen asia). Ainakin Kielitoimiston sanakirjan mukaan tilanne olisi suomenkin osalta samankaltainen? Jos ei kuitenkaan ole niin olisiko silti mahdollista säilyttää vain laajempi termi? Muuten täytynee jotenkin määritellä nämä suomeksi sillä tavalla että saadaan ruotsiksi vastineita jotka eivät ainakaan ole synonymisia keskenään.

**Comment by tpalonen** [comment]
En yhdistäisi. Järjestö-merkitys huomattavasti kapeampi.

**Comment by mariaforsen** [comment]
Eli olisiko järjestö=förening siinä tapauksessa? Ongelmallista siis edelleen se että näin ei kuitenkaan ole käytetty Melindassa. Ja sanakirjat eivät näytä tietävän tästä kapeudesta mitään.

**Comment by mirmaid** [comment]
Yhdistys/järjestö/organisaatio -ongelma on kyllä hankala, kun ne rajautuvat vähän eri tavoilla suomeksi ja ruotsiksi.

_Järjestö_ on siis Kielitoimiston sanakirjan mukaan _henkilöiden t. yhteisöjen määrätarkoitusta varten perustama yhteenliittymä, organisaatio_. Ruotsiksi se on _organisation_, mutta suomeksi tuossa on kuitenkin keskeistä tuo henkilöiden tai yhteisöjen perustama, ei siis esim. valtion organisaatio. Suomeksi puolustusvoimat tai sen osakokonaisuudet eivät olisi järjestöjä, mutta kylläkin organisaatioita.

**Comment by mariaforsen** [comment]
Sen takia ajattelen että ratkaisu olisi tässä tapauksessa pitää se laajempi termi (yksi mahdollinen ratkaisu monikielisessä sanastossa tällaisen ongelman kohdalla). Mutta ellei sitä haluta niin tarvitaan muita ideoita?

**Comment by mirmaid** [comment]
_Sotilaalliset järjestöt_ on ollut sanastossa v. 1986 asti, joten sen korvaaminen alun perin hierarkisoivaksi tarkoitetulla käsitteellä vaatii ainakin vielä Melindan tutkimista, koska silloin tuo järjestö-merkitys jäisi pois. 

Varmistan nyt vielä että _militärorganisationer_ siis tosiaan kattaa myös esim. Suomen armeijan kokonaisuutena, tai sen ilmavoimat ja yhtä lailla esim. insinööriupseeriliiton tai yksittäisen Lotta Svärd -osaston?

**Comment by mariaforsen** [comment]
Olennaista on siis se että ruotsiksi ei ole mitään väliä sillä onko termi muodossa militärorganisationer tai militära organisationer, käsite on sama. Tähän tarvitaan siis ratkaisua mahdollisimman pian.

**Comment by mirmaid** [comment]
^ Mutta suomenkielisen termin kannalta on myös olennaista, mitä kaikkea ruotsinkielinen vastine kattaa. Tämä on hankala muutos nimenomaan tuon yhdistys/järjestö/organisaatio -termistön vähän erilaisen kielellisen kattavuuden takia - sotilaallinen organisaatio kuulostaa suomeksi jo hyvin "sotaisalta", jos kyse on maanpuolustustyöhön liittyvistä yhdistyksistä.

**Comment by mariaforsen** [comment]
Ruotsin kannalta voidaan siis yhtä hyvin valita sotilaalliset järjestöt pääterminä, jos suomeksi koetaan että sotilaalliset organisaatiot on liian "sotaisa". 

Huom. termi **sotilaalliset organisaatiot** ei ole ollut olemassa YSAssa, vaan tosiaan YSOn puolella lisätty hierarkisoivana terminä. Sitä ei ole siis myöskään käytetty Melindassa.

**Comment by ilona-x** [comment]
sotilaalliset järjestöt on käytetty Melindassa 222 kertaa, viitteistä monissa näyttäisi olevan kyseessä melko "sotaisat" järjestöt. Ja viitteistä  64 on sellaisia, joissa on myös asiasana **maanpuolustusjärjestöt**, ja nähdäkseni näissä tapauksissa sotillaalliset järjestöt ei ole tarpeellinen ja osittain jopa virheellinen.

**Comment by mirmaid** [comment]
Tässä yhdistämisessä on siis seuraavat ongelmat:

- _sotilaalliset järjestöt_ ei suomeksi sovi yläkäsitteeksi samoille käsitteille kuin sotilaalliset organisaatiot, koska esim. armeijat tai puolustusvoimat eivät ole järjestöjä
- jos sotilaalliset järjestöt poistetaan ja _sotilaalliset organisaatiot_ -käsitteestä tehdään kuvailukäsite, sen kattavuus on ihan toisenlainen, eikä tuota järjestö-aspektia saa enää esiin. Mutta jos se ei ole tarpeellinen niissä 158:ssa aineistossa, joissa ei ole _maanpuolustusjärjestöt_-käsitettä, niin sitten muutos näin päin on mahdollinen.

**Comment by ilona-x** [comment]
Selasin läpi reilu 60 sellaista viitettä, jossa käytetty sotilaalliset järjestöt mutta ei maanpuolustusjärjestöt, ja keräsin niistä kohdeyhteisöjä tai jos yhteisö oli mainittu muissa kuvailutiedoissa. Tässä listaa:

Suomalainen SS-pataljoona
Hizbollah
Suomen kommunistinen puolue
Pasdaran
SS (järjestö)
Pohjois-Atlantin liitto.
Waffen-SS.
Wiking-divisioona.
Hamas.
IRA
Great Britain. Army

Ilmatorjuntaupseeriyhdistys.
Savonlinnan seudun suojeluskuntien ja Lotta Svärd -osastot
JR 9 kilta 
Pohjois-Karjalan prikaatin kilta 
Pirkanmaan sotilaspiirien perinneyhdistys.
Savon sotilasperinneyhdistys Porrassalmi

**Comment by YSO-kokous** [comment]
"sotilaalliset järjestöt" KÄ sotilaalliset organisaatiot sekä maanpuolustusjärjestöt
"sotilaalliset organisaatiot" muutetaan hierarkkisesta kuvailukäsitteeksi
