### ISSUE TITLE
syntymäpituus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7744]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syntymäpituus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1385-6 

#### Perustelut ehdotukselle   

On syntymäpaino, mutta tämänkin tarvitsisin. 

**Termiehdotus Fintossa:** [syntymäpituus](http://finto.fi/yse/fi/page/Y507744)

**Comment by mariaforsen** [comment]
Sv. födelselängd

**Comment by ilona-x** [comment]
FinMeSHissä vain syntymäpaino

LCSH: 
Birth size http://id.loc.gov/authorities/subjects/sh85014388
ST Birth weight

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
