### ISSUE TITLE
valvominen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7745]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valvominen](http://www.yso.fi/onto/ysa/Y156872) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytettävä termi muotoon "valvominen (hereilläolo)" tai "valvominen (valveillaolo)". 

#### Perustelut ehdotukselle   

Termin perusteella saattaa mennä merkitykseltään sekaisin valvonta-käsitteen kanssa. Toisaalta valvonta-terminkin voi tulkita viittaavan valveillaoloon, joten sulkutarkennetta voisi harkita siihenkin? Mikäli valvominen-käsitteelle lisätään sulkutarkenne, valvonta-käsitteelle voisi joka tapauksessa lisätä ohjaustermiksi myös valvominen-muodon sopivalla sulkutarkenteella varustettuna.

Nykysuomen sanakirjan (1980, WSOY) mukaan hereilläolo ja valveillaolo voidaan kirjoittaa joko yhteen tai erikseen. 

#### Ehdottajan organisaatio   

KK

**Comment by ilona-x** [comment]
FinMeSH: hereilläolo KT valveillaolo http://www.yso.fi/onto/mesh/D014851

**Comment by LeKorsu** [comment]
Ysossa on jo ohjaustermnä valvominen (tarkkailu) KÄ valvonta. Tarvitaanko sittenkään toiselle valvomiselle tarkennetta?

**Comment by mirmaid** [comment]
Yleensä aineistoissa, joissa käsitellään unettomuutta, univajetta ja väsymystä. Valvotaan esim. pienten lasten takia tai koska ei pysty nukahtamaan, eli pääasia ei niinkään ole hereilläolo sinänsä vaan se, ettei voi nukkua riittävästi. Koko käsite on näissä aineistoissa ehkä vähän ylimääräinen lisä. Toisaalta esim. tämän tyyppisissä tuntuu ehkä jossain määrin tarpeelliselta https://melinda.kansalliskirjasto.fi/byid/013168384, samoin tässä https://melinda.kansalliskirjasto.fi/byid/013945578 tai tässä https://melinda.kansalliskirjasto.fi/byid/005598733.

Melindassa ei ole käytetty valvonta-merkityksessä.

**Comment by YSO-kokous** [comment]
Poistetaan valvominen YSOsta. Löytyy korvaavia käsitteitä (univaje, unettomuus) ja toisaalta voidaan sekoittaa valvonta-käsitteeseen.
