### ISSUE TITLE
mielenosoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7746]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mielenosoitukset](http://www.yso.fi/onto/ysa/Y102185) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ohjaustermiksi mielenilmaukset. 

#### Perustelut ehdotukselle   

Ehdotus tullut suomi.fi:n kehitystiimiltä. Mielenilmaus yleistynyt viime aikoina lähisynonyymiksi mielenosoitusten kanssa. Esim. Yle ja Helsingin Sanomat käyttävät nykyisin usein samassa jutussa näitä kahta sanaa rinnan synonyymeina. Toisaalta mielenilmaus voisi olla ohjaustermi myös seuraaville: protestit, vastustus, vastarinta. 

#### Ehdottajan organisaatio   

KK

**Comment by YSO-kokous** [comment]
Hyväksytään: mielenilmaukset KÄYTÄ mielenosoitukset.
