### ISSUE TITLE
vainajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7747]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vainajat](http://www.yso.fi/onto/ysa/Y106231) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan käytettäväksi termiksi kuolleet ja ohjaustermiksi vainajat. 

#### Perustelut ehdotukselle   

Käsite tulee näin monikäyttöisemmäksi. Nyt rajautuu termistä johtuen paljolti uskontoon ja kansanperinteeseen, kuolleeseen lähimmäisenä, mutta käyttö yleisemmin merkityksessä 'kuollut ihminen' voisi olla laajempaakin. Joissakin kuvailukonteksteissa "vainajat" ei tunnu sopivalta kuvailun tai tiedonhaun kannalta, esim. onnettomuudessa kuolleet, henkirikoksen uhrit, jne.

Ohjaustermiksi suomi.fi-tiimi ehdottanut myös "menehtyneet". 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Varmaan ok, sanastossa on myös _vainajaolennot_. Arkeologian yhteydessä usein _vainajat_ tuntuu paremmalta muodolta kuin _kuolleet_ (jossa ehkä hiukan sellainen hassu sävy, ikäänkuin olisi mahdollista löytää kaivauksissa myös eläviä). Sopii kuitenkin paremmin kuin vainajat onnettomuuksien uhreista ym.

**Comment by krinay** [comment]
Vainajat kuuluu YSOssa nyt vain ryhmiin 50 ja 53, mikä myös on voinut ohjata käyttöä.

Vainajaolennot kuuluu sekin ryhmiin 50 ja 53. Vainajainpalvonta on vain ryhmässä 53, voisiko sille samalla lisätä ryhmän 50?

**Comment by YSO-kokous** [comment]
Muutetaan käytettäväksi termiksi kuolleet, ja ohjaustermiksi vainajat.
