### ISSUE TITLE
lukiokoulutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7748]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lukiokoulutus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[toisen asteen koulutus](http://www.yso.fi/onto/yso/p3387) 

#### Assosiatiiviset (RT)   

[lukio](http://www.yso.fi/onto/yso/p7401) 
[yleissivistävä koulutus](http://www.yso.fi/onto/yso/p12690) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

suomi.fi-tiimi ehdotti tätä ohjaustermiksi lukio-käsitteelle. Mietittiin kuitenkin, että soveltuisi ehkä paremmin sanastoon omana käsitteenään. Lukio ja lukiokoulutus ovat eri käsitteitä. Sanastosta löytyvät myös mm. ammatillinen koulutus, perusasteen koulutus ja korkea-asteen koulutus.

Lukiokoulutus Melindassa asiasanana 35 kertaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kouluvaikutus ja tuloksellisuusrahoitus lukiokoulutuksessa / Laura Ansala, Jenni Pääkkönen. 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [lukiokoulutus](http://finto.fi/yse/fi/page/Y507748)

**Comment by mariaforsen** [comment]
Sv. gymnasieutbildning

**Comment by LeKorsu** [comment]
On jo toisen asteen koulutus http://www.yso.fi/onto/yso/p3387
Toisen asteen koulutus sisältää lukiokoulutuksen ja ammatilliset perustutkinnot. Nimitys käytössä vuodesta 1995 lähtien, aiemmat katso keskiasteen koulutus.

**Comment by YSO-kokous** [comment]
Lisätään lukiokoulutus ohjaustermiksi käsitteelle lukio.

Lukiota ja lukiokoulutusta käytettäisiin varmasti päällekkäin, jos olisivat sanastossa erikseen.
