### ISSUE TITLE
meemit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7749]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[meemit](http://www.yso.fi/onto/ysa/Y113164) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja:
meemi
1. kulttuurissa ilmeneviä piirteitä (esim. tapoja, taitoja ja asenteita), joiden katsotaan välittyvän yhteisöltä t. yksilöltä toiselle vars. jäljittelyn kautta, "kulttuurigeeni".
2. sosiaalisessa mediassa jaettavista viesteistä, jotka perustuvat jnk pysyvän idean muunteluun. 

Melindassa käytetty molemmissa merkityksissä 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdotettu muutos   

Pitäisikö tämä jakaa tai rajata tarkenteella?

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Internetilmi%C3%B6
https://www.helsinki.fi/fi/unitube/video/4930a625-bf1c-42bc-866a-e3ed0fa64163

**Comment by mirmaid** [comment]
Onko jakaminen tarpeen? Toinen voisi olla _internetmeemit_, toiselle vähän vaikea keksiä poissulkevaa tarkennetta/muotoa. 

_In 2013, Richard Dawkins characterized an Internet meme as one deliberately altered by human creativity, distinguished from Dawkins's original idea involving mutation "by random change and a form of Darwinian selection"._ https://en.wikipedia.org/wiki/Meme#Internet_culture - kuitenkin esim. Wikipedia-sivut listaavat nettimeemit meemien alatyyppinä. Vrt. myös esim. Keep calm and carry on -versiot.

**Comment by krinay** [comment]
Meemit (kulttuurievoluutio) ja meemit (internet) tai internetmeemit voisi olla yksi mahdollinen tapa jakaa. Mutta en pidä jakamista tarpeellisena (vielä) tässä vaiheessa.

**Comment by YSO-kokous** [comment]
Poistetaan meemit-käsitteen määritelmä, koska hieman harhaanjohtava ("Meemejä ovat kaikki asiat, jotka yksilö on oppinut toisilta").
Lisätään meemit-käsitteelle ohjaustermi internetmeemit tai internet-meemit.
