### ISSUE TITLE
anatoksiini-a

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7751]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

anatoksiini-a 

#### Ehdotettu termi englanniksi   

anatoxin-a 

#### Perustelut ehdotukselle   

Anatoxin-a, also known as Very Fast Death Factor (VFDF), is a secondary, bicyclic amine alkaloid and cyanotoxin with acute neurotoxicity. 
https://en.wikipedia.org/wiki/Anatoxin-a 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1509-6 

**Termiehdotus Fintossa:** [anatoksiini-a](http://finto.fi/yse/fi/page/Y507751)

**Comment by mariaforsen** [comment]
Sv. anatoxin-a

**Comment by ilona-x** [comment]
FinMeSH: toksoidit KT anatoksiinit http://www.yso.fi/onto/mesh/D014121

**Comment by mirmaid** [comment]
Lääketieteen termit: toksoidi: anatoksiini | _esim. formaldehydillä ja kuumentamalla käsitelty (bakteeri)toksiini, joka on menettänyt myrkyllisyytensä, mutta aiheuttaa vielä rokotteena immuniteetin syntymisen_.

http://tieteentermipankki.fi/wiki/Nimitys:toksoidi

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa anatoksiini-a.
