### ISSUE TITLE
leppäkertut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7752]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leppäkertut](http://www.yso.fi/onto/ysa/Y106587) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

leppäkertut -> leppäpirkot (heimo Coccinellidae) 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.194260 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. nyckelpigor

**Comment by mirmaid** [comment]
Onko tässäkin sama ongelma kuin valkohäntäkauriilla, ettei kyse oikeasti ole kerttujen vaan pirkkojen heimosta :speak_no_evil: (haen takkini)...

**Comment by YSO-kokous** [comment]
Lisätään leppäpirkot ohjaustermiksi leppäkertuille. Leppäkertut on yleisempi termi.
