### ISSUE TITLE
talirauhaset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7753]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

talirauhaset 

#### Ehdotettu termi ruotsiksi   

talgkörtel 

#### Ehdotettu termi englanniksi   

sebaceous gland 

#### Perustelut ehdotukselle   

Talirauhanen (lat. glandula sebacea) on talia erittävä usein karvan juurituppeen avautuva verinahassa sijaitseva ihon rauhanen.
https://fi.wikipedia.org/wiki/Talirauhanen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1464-8 

**Termiehdotus Fintossa:** [talirauhaset](http://finto.fi/yse/fi/page/Y507753)

**Comment by mariaforsen** [comment]
Sv. talgkörtlar

**Comment by ilona-x** [comment]
FinMeSH: 
talirauhaset http://www.yso.fi/onto/mesh/D012627
LT avorauhaset
