### ISSUE TITLE
potyvirukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7754]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

potyvirukset 

#### Ehdotettu termi englanniksi   

potyvirus 

#### Perustelut ehdotukselle   

Potyvirus is a genus of viruses in the family Potyviridae. Plants serve as natural hosts.

https://en.wikipedia.org/wiki/Potyvirus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1250-7 

**Termiehdotus Fintossa:** [potyvirukset](http://finto.fi/yse/fi/page/Y507754)

**Comment by mariaforsen** [comment]
Sv. potyvirus 
https://www.dyntaxa.se/Taxon/Info/6034930?changeRoot=True

**Comment by ilona-x** [comment]
FinMeSH: Potyvirus http://www.yso.fi/onto/mesh/D017800

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
