### ISSUE TITLE
RNA-interferenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7755]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

RNA-interferenssi 

#### Ehdotettu termi englanniksi   

RNA interference 

#### Ehdotettu termi ruotsiksi   

RNA-interferens 

#### Vaihtoehtoiset termit ja ilmaisut   

RNAi 

#### Perustelut ehdotukselle   

RNA-interferenssi (lyhenne RNAi) on solubiologiassa tunnettu mekanismi, joka hiljentää tietyn geenin ilmenemisen eliön ilmiasussa (geeniekspressio). 
https://fi.wikipedia.org/wiki/RNA-interferenssi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1250-7 

**Termiehdotus Fintossa:** [RNA-interferenssi](http://finto.fi/yse/fi/page/Y507755)

**Comment by mirmaid** [comment]
LCSH: RNA interference http://id.loc.gov/authorities/subjects/sh2015001314

FinMeSH http://www.yso.fi/onto/mesh/D034622

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
