### ISSUE TITLE
leggingsit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7756]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

leggingsit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vaatteet](http://www.yso.fi/onto/yso/p3594) 
[housut](http://www.yso.fi/onto/yso/p17896) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578) 

#### Perustelut ehdotukselle   

Vakiintunut nimitys tietynlaisille housuille. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ompelukaavojen kuvailussa. 

**Ehdottajan organisaatio:** Yleinen kirjasto **Termiehdotus Fintossa:** [leggingsit](http://finto.fi/yse/fi/page/Y507756)

**Comment by mariaforsen** [comment]
Sv. leggings

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa leggingsit.
