### ISSUE TITLE
hupparit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7757]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hupparit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vaatteet](http://www.yso.fi/onto/yso/p3594) 

#### Assosiatiiviset (RT)   

[takit](http://www.yso.fi/onto/yso/p11547) 
[puserot](http://www.yso.fi/onto/yso/p22716) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578) 

#### Tarkoitusta täsmentävä selite   

Yleensä collegekankaasta valmistettu hupullinen takki tai pusero. Vapaa-ajan asuste, joskin on nykyään tavallinen myös esim. oppilaitoksissa ja joillakin työaloilla. 

#### Perustelut ehdotukselle   

Takit tai puserot eivät aivan sovi kuvaamaan hupparia, koska huppari voi olla joko takki tai pusero. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ompelukaavojen kuvailussa. 

**Termiehdotus Fintossa:** [hupparit](http://finto.fi/yse/fi/page/Y507757)

**Comment by mariaforsen** [comment]
Sv. munkjackor ET munktröjor, huvjackor, huppare

**Comment by ilona-x** [comment]
MAO/TAO: hupparit http://www.yso.fi/onto/mao/p7584

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa hupparit.
