### ISSUE TITLE
sepät (ammatit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7758]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sepät (ammatit)](http://www.yso.fi/onto/ysa/Y104299) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "rautasepät" 

#### Perustelut ehdotukselle   

Esiintyy ammattinimityksenä (ks. esim. http://digi.narc.fi/digi/view.ka?kuid=74677170, rivi [3]) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. ET järnsmeder

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
