### ISSUE TITLE
palvelinkeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7759]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[palvelinkeskukset](http://www.yso.fi/onto/ysa/Y191908) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään KT datakeskukset 

#### Perustelut ehdotukselle   

http://www.tsk.fi/tepa/fi/haku/datakeskus
https://fi.wikipedia.org/wiki/Datakeskus 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Suhde atk-keskuksiin? Ruotsiksi se on datacentraler

**Comment by ilona-x** [comment]
Enpä huomannut tuollaista atk-keskusta. 🤓 Atk-keskukset Käytetty Melindassa vain 16 kertaa, vanhemmissa viitteissä näyttäisi olevan kyse korkeakoulujen IT-palveluita tarjoavasta yksiköstä tai yritysten tietohallinto/IT-osastoista. Kahdessa uusimmassa viitteessä atk-keskuksia näyttää olevan käytetty palvelinkeskuksista. Olisko atk-keskukset mahdollista poistaa tai jos halutaan säilyttää niin ainakin tuo atk-alkuosa pitäisi päivittää. 

Esim. Helsingin yliopiston atk-keskus on nykyään Helsingin yliopiston tietotekniikkakeskus.

http://finto.fi/cn/fi/search?clang=fi&q=*atk-keskus*

**Comment by mirmaid** [comment]
Eiköhän selvitä ilman atk-keskuksia.

**Comment by YSO-kokous** [comment]
Poistetaan atk-keskukset sanastosta.
