### ISSUE TITLE
hypohidroottinen ektodermaalinen dysplasia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7761]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hypohidroottinen ektodermaalinen dysplasia 

#### Ehdotettu termi englanniksi   

hypohidrotic ectodermal dysplasia .. 

#### Vaihtoehtoiset termit ja ilmaisut   

ektodermaalinen dysplasia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-0570-7 

#### Perustelut ehdotukselle   

Perinnöllinen sairaus, johon kuuluu ektodermaalisten rakenteiden epämuodostumat (iho, hiukset, hampaat ja hikirauhaset).
https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=orp01758&p_teos=orp

https://en.wikipedia.org/wiki/Hypohidrotic_ectodermal_dysplasia

https://fi.wikipedia.org/wiki/Ektodermaalinen_dysplasia 

**Termiehdotus Fintossa:** [hypohidroottinen ektodermaalinen dysplasia](http://finto.fi/yse/fi/page/Y507761)

**Comment by mariaforsen** [comment]
Sv. hypohidrotisk ektodermal dysplasi

**Comment by mirmaid** [comment]
FinMeSH KÄ ektodermaalinen dysplasia

_ED can be classified by inheritance (autosomal dominant, autosomal recessive and X-linked) or by which structures are involved (hair, teeth, nails and/or sweat glands)._ https://en.wikipedia.org/wiki/Ectodermal_dysplasia
_Hypohidrotic ectodermal dysplasia is the most common form of ectodermal dysplasia in humans._

**Comment by ilona-x** [comment]
https://www.terveyskyla.fi/harvinaissairaudet/tietoa/tautiryhm%C3%A4t/ihosairaudet/sairaudet/ektodermaaliset-dysplasiat

**Comment by YSO-kokous** [comment]
Otetaan sanastoon laajempi käsite, muodossa ektodermaaliset dysplasiat, ohjaustermiksi hypohidroottinen ektodermaalinen dysplasia.

**Comment by mariaforsen** [comment]
Sv. ektodermala dysplasier ET hypohidrotisk ektodermal dysplasi
