### ISSUE TITLE
puuvilla

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7763]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puuvilla](http://www.yso.fi/onto/ysa/Y102773) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

puuvillat (suku Gossypium)
Pitäisikö olla myös puuvilla (luonnonmateriaalit)? 

#### Perustelut ehdotukselle   

Puuvillat (Gossypium) on malvakasvien suku, jonka neljää lajia viljellään puuvillan tuottamiseksi. Teksasinpuuvilla (Gossypium hirsitium) on tärkein puuvillalajeista edustaen noin 90 % kaikesta viljellystä puuvillasta.
https://fi.wikipedia.org/wiki/Puuvillat
https://laji.fi/taxon/MX.5008982 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. bomull, bomullssläktet, bomull (naturmaterial)

**Comment by mirmaid** [comment]
Sanastossa on
hamppu / hamppukasvit
bambu (materiaali) / bambut (heinäkasvit)

**Comment by mirmaid** [comment]
Jos jaetaan, myös monikko tarvitsee tarkenteen.

LCSH: https://id.loc.gov/authorities/subjects/sh85033302.html

**Comment by mirmaid** [comment]
Ensimmäisten sadan viitteen joukossa ei ollut aineistoja, joissa olisi nimenomaan käsitelty puuvillakasveja (paitsi ehkä tämä: https://melinda.kansalliskirjasto.fi/byid/013513326) - puuvillan tuotantoa kyllä pelloilta alkaen, mutta näkökulma ei ollut kasvitieteellinen vaan enemmän näissä pinnalla ovat työvoima-, ympäristö- jne. kysymykset. Jako on toki mahdollista tehdä, mutta kumpaa oikeastaan haluttaisiin käytettävän kun kyse on em. teemoista?

Esim.
[Trade, reputation, and child labor in twentieth-century Egypt](https://melinda.kansalliskirjasto.fi/byid/003742426)
[Mistä puuvilla tulee? Puuvilla voi nostaa Sambian maaseudun köyhyydestä, sanovat yritysjohtajat. Monet viljelijät ovat eri mieltä   ](https://melinda.kansalliskirjasto.fi/byid/013708360)
[Central Asian waters : social, economic, environmental and governance puzzle](https://melinda.kansalliskirjasto.fi/byid/003948629)
[Luomu rynnistää puuvillapelloilla : ekologisuus vauhdittaa myyntiä, viljelijä säästää tuotantokuluissa](https://melinda.kansalliskirjasto.fi/byid/013116657)

Tässä on vähän ehkä riskinä se, että usein pitäisi käyttää molempia, mutta kuvailija ehkä tyytyisi jompaan kumpaan (?)

**Comment by LeKorsu** [comment]
Eli jos erotellaan, olisiko jotenkin näin bambuja mukaellen:
puuvillat (malvakasvit)
puuvilla (materiaali)

**Comment by mariaforsen** [comment]
Ruotsiksi vastaavasti: 
-bomullssläktet tai bomull (malvaväxter)
-bomull (material)

**Comment by mirmaid** [comment]
Jos jaetaan, niin hakijan pitäisi kai ymmärtää, että etsiessään tietoa puuvillantuotannon eettisistä aspekteista, on käytettävä termiä puuvilla (materiaali) silloin kun etsitään tietoa työstä tehtaissa tms. ja puuvillat (malvakasvit) kun etsitään tietoa työoloista pelloilla...

**Comment by YSO-kokous** [comment]
### Päätös
Äänestyksen jälkeen päätettiin, ettei tehdä muutoksia käsitteeseen.
