### ISSUE TITLE
Ylinen Alposjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7764]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ylinen Alposjärvi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Järvi Pellon kunnassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kaavoitusjulkaisut, hydrologia, maantiede 

**Ehdottajan organisaatio:** Rovaniemen kaupunginkirjasto/maakuntakokoelma **Termiehdotus Fintossa:** [Ylinen Alposjärvi](http://finto.fi/yse/fi/page/Y507764)

**Comment by ilona-x** [comment]
http://paikkatiedot.fi/so/1000772/10403810
