### ISSUE TITLE
historiallinen totuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7767]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

historiallinen totuus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Linden: Sodan ja talouden Suomet 

#### Perustelut ehdotukselle   

Usein tutkitaan esim. Raamatun historiallista totuutta, Käsiteltävänäni olevassa teoksessa "Käsite kuvaa sitä, mikä poliittinen kysymys nousee aikalaistietoudessa keskeiseen asemaan. 
Käytetty kyllä asiasanaa historiatietoisuus ja ajan kuva. Tämän kirjan indeksoinnissa ei sittenkään olisi hyvä käyttää tuota historiallinen totuus  -termiä, mutta miten kuvaisitte tuota Raamattu -casea? 

**Ehdottajan organisaatio:** Kb **Termiehdotus Fintossa:** [historiallinen totuus](http://finto.fi/yse/fi/page/Y507767)

**Comment by jtuohini** [comment]
_Raamatun_ historiallista totuutta/uskottavuutta / historiallisuutta käsittelevän aineiston kuvailussa voisi kenties käyttää ainakin YSO-asiasanoja [**kirjalliset lähteet**](http://www.yso.fi/onto/yso/p17515), [**luotettavuus**](http://www.yso.fi/onto/yso/p1629), [**lähdekritiikki**](http://www.yso.fi/onto/yso/p14440)?
 
Mutta muuten tuohon ehdotukseen liittyen: mikä olisi sen suhde YSOssa jo olevaan [**historiapolitiikka**](http://www.yso.fi/onto/yso/p25226)-asiasanaan? Ks. myös esim. ["Historiapolitiikasta ja menneisyydenhallinnasta kiinnostuneet"](https://agricolaverkko.fi/keskustelu/viewtopic.php?t=5801) -keskustelu.

**Comment by mariaforsen** [comment]
Sv. historisk sanning

**Comment by krinay** [comment]
YSOssa on jo:
historiapolitiikka KT historian käyttö, historiankäyttö, menneisyyspolitiikka
historiakulttuuri KT historian käyttö, historiankäyttö
historiankäsitys
historiatietoisuus
(ja historianfilosofia ym.)
sekä mm. totuus, totuudellisuus, totuudenkaltaisuus.

**Comment by YSO-kokous** [comment]
Historiapolitiikka käy ehdotuksessa mainitun aineiston kuvailuun.

Tutkitaan vielä, onko tarvetta käsitteelle, joka viittaa Raamatun ja vastaavien totuudellisuuteen/historiallisuuteen. Sopisiko "totuudellisuus" tällaiseen kontekstiin?

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Raamatullinen_arkeologia
https://fi.wikipedia.org/wiki/Raamatun_historiallisuus

On olemassa termi raamatunhistoria, joka on tällä hetkellä ryhmässä 53 - voisiko ajatella laajennettavan historia-ryhmään 52, jolloin sen avulla voidaan kuvata muutakin kuin uskonnollista kontekstia?

**Comment by YSO-kokous** [comment]
Ei oteta käsitettä sanastoon. Jätetään termiehdotukseksi.

Pohdittavaksi, lisätäänkö raamatunhistoria-käsitteelle ryhmä 52 Historia.

**Comment by mariaforsen** [comment]
Ruotsiksi käytettävä termi olisi lähinnä historicitet (det att vara historiskt sann eller verklig ⟨i vetenskapl. sammanhang⟩) Ks. myös https://sv.wikipedia.org/wiki/Historicitet = historiallisuus
Vrt. https://sv.wikipedia.org/wiki/Jesu_historicitet = https://fi.wikipedia.org/wiki/Jeesuksen_historiallisuus

**Comment by AuHo22** [comment]
http://www.helsinki.fi/teol/pro/emo/tutkimuksen/miksi3.html
Tämä ehkä raamatunhistoriaa -?

Suomeksi näkee myös ilmaisua _historiallinen luotettavuus_

esim. https://apowiki.fi/wiki/Raamatun_historiallinen_luotettavuus
https://historianjeesus.fi/tutkimusmenetelmista/muotokritiikki-ja-jeesus-tutkimus/muotokritiikki-ja-evankeliumien-historiallinen-luotettavuus/

**Comment by mirmaid** [comment]
> On olemassa termi raamatunhistoria, joka on tällä hetkellä ryhmässä 53 - voisiko ajatella laajennettavan historia-ryhmään 52, jolloin sen avulla voidaan kuvata muutakin kuin uskonnollista kontekstia?

Eli voiko raamatunhistoria-käsitettä käyttää aineistossa, jossa itse Raamatun historiallisuutta pohditaan? Ja pitäisikö tätä varten lisätä luokka 52?

**Comment by mirmaid** [comment]
_Historiallisuus_-termin suhteen olen vähän epävarma, rajautuisiko se yhtä tarkasti kuin historicitet - suomeksi voisi ehkä ymmärtää myös tarkoittavan historiallista merkittävyyttä tai historiaan (menneisyyteen) sijoittumista?

Halutaanko kuitenkin ottaa nyt _historiallisuus_ tai _historiallinen luotettavuus_, vai jätetäänkö toistaiseksi termiehdotukseksi?

**Comment by mariaforsen** [comment]
Kannatan historiallisuus=historicitet + huomautus ettei sekoiteta yllä mainittuun "historialliseen merkittävyyteen", tai historiallinen totuus=historisk sanning

Raamatunhistoria=biblisk historia en välttämättä käyttäisi ollenkaan tässä yhteydessä, vaan lähinnä historiasta sellaisena kuin se kuvaillaan raamatussa. Toki jos aineistossa sitten verrataan historia kuten kuvaillaan raamatussa vs. historia sellaisena kuin tieteellisesti on näytetty niin sitten tietty ok.

**Comment by YSO-kokous** [comment]
otetaan sanastoon **historiallisuus** = historicitet = historicity  KT historiallinen totuus = historisk sanning, historiallinen paikkanaspitävyys, historisiteetti
