### ISSUE TITLE
solumigraatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7768]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

solumigraatio 

#### Vaihtoehtoiset termit ja ilmaisut   

soluvaellus 

#### Perustelut ehdotukselle   

http://www.solunetti.fi/fi/solubiologia/liikkuminen/2/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Expression of Alternative Oxidase Influences Cell Migration 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [solumigraatio](http://finto.fi/yse/fi/page/Y507768)

**Comment by mariaforsen** [comment]
Sv. cellmigration ET cellvandring

**Comment by mirmaid** [comment]
LCSH: Cell migration

https://en.wikipedia.org/wiki/Cell_migration

Sekä _soluvaellus_ että _solumigraatio_ -muotoa on käytetty kerran Melindassa. Itselleni soluvaellus on tuttu termi varmaan jostain koulun biologiasta, mutta hyvin vähän löytyy Googlella.

**Comment by mirmaid** [comment]
http://www.yso.fi/onto/mesh/D054262
https://fi.wikipedia.org/wiki/Gastrulaatio

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa solumigraatio, ohjaustermiksi soluvaellus.
