### ISSUE TITLE
Unari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7769]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Unari 

#### Perustelut ehdotukselle   

Suurehko järvi Sodankylän kunnan lounaisosassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

kaavoitusraportit, maantiede, paikallishistoria 

**Ehdottajan organisaatio:** Rovaniemen kaupunginkirjasto, maakuntakokoelma. **Termiehdotus Fintossa:** [Unari](http://finto.fi/yse/fi/page/Y507769)

**Comment by mirmaid** [comment]
Tarvitseeko tarkenteen? Sanastossa myös Unarin Luusua, KT Unari.

**Comment by ilona-x** [comment]
Varmaan tarkenne olisi tarpeen, ettei vahingossa käytetä kylästä.

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi: Unari, ohjaustermiksi Unari (järvi).
Muutetaan Unarin Luusuan ohjaustermi muotoon: Unari (kylä).
