### ISSUE TITLE
homeostaasi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7771]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

homeostaasi 

#### Ehdotettu termi ruotsiksi   

homeostas 

#### Ehdotettu termi englanniksi   

homeostasis 

#### Perustelut ehdotukselle   

Homeostaasi on tietyn systeemin sisällä vallitseva tasapaino. Termiä käytetään tavallisesti biologiassa tarkoitettaessa elimistön tai pienemmän systeemin tasapainoa. 
https://fi.wikipedia.org/wiki/Homeostaasi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1210-1 

**Termiehdotus Fintossa:** [homeostaasi](http://finto.fi/yse/fi/page/Y507771)

**Comment by ilona-x** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D006706

**Comment by mirmaid** [comment]
Melindassa 21 kertaa (finmesh).

**Comment by mirmaid** [comment]
Suomenkielisessä Wikipediassa vähän erikoinen kuvavalinta.

**Comment by mirmaid** [comment]
Lääketieteen termit: homeostaasi: homeostasia | 1. (laaja merkitys:) järjestelmän (esim. eliön) ylläpitämä sisäinen tasapaino; vrt. allostaasi; 2. (suppea merkitys:) fysiologinen homeostasia | elimistön sisäinen tasapaino (esim. kudosnesteen ja lämpötilan pysyminen jatkuvasti samanlaisena) fysiologisten ja biokemiallisten negatiivisten palautejärjestelmien avulla

**Comment by mirmaid** [comment]
homeostaasi: elimistön sisäinen tasapaino, fysiologinen homeostasia (veren ja kudosnesteen pysyminen jatkuvasti samanlaisena fysiologisten ja biokemiallisten palautejärjestelmien avulla) https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=ltt01170

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Biologia:homeostasia

LCSH: Homeostasis: http://id.loc.gov/authorities/subjects/sh85061731

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa homeostaasi, ohjaustermiksi homeostasia.
