### ISSUE TITLE
apoplasti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7772]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

apoplasti 

#### Ehdotettu termi englanniksi   

apoplast 

#### Perustelut ehdotukselle   

kasvisolukon soluvälien ja seinähuokosten muodostama kokonaisuus, jossa aineet kulkeutuvat diffuusion välityksellä passiivisesti
http://tieteentermipankki.fi/wiki/Kasvitiede:apoplasti 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1210-1 

**Termiehdotus Fintossa:** [apoplasti](http://finto.fi/yse/fi/page/Y507772)

**Comment by mariaforsen** [comment]
Sv. apoplast

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Apoplast

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
