### ISSUE TITLE
shakkinappulat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7773]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

shakkinappulat 

#### Ehdotettu termi englanniksi   

chessmen 

#### Ehdotettu termi ruotsiksi   

schackpjäser 

#### Vaihtoehtoiset termit ja ilmaisut   

shakkipelinappulat [fin] 
chess men [eng] 
chess pieces [eng] 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85023135> 
Wikidata : https://www.wikidata.org/wiki/Q82274058 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Aihetta käsittelevän aineiston kuvailuun ei ole vanhastaan sopivaa asiasanaa, ei edes "pelinappulat" tai "pelivälineet", jollainen olisi myös käynyt ehdistettynä pelin tyyppiä kuvaavaan asiasanaan (tässä tapauksessa "shakki"). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.159772 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [shakkinappulat](http://finto.fi/yse/fi/page/Y507773)

**Comment by LeKorsu** [comment]
Museoala voisi myös tykätä tästä - samoin kuin pelinappuloista.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon kaksi käsitettä:
shakkinappulat
pelinappulat

**Comment by mariaforsen** [comment]
Sv.
-schackpjäser
-spelpjäser ET spelknappar, spelfigurer, spelbrickor
