### ISSUE TITLE
Mälkölä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7774]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Mälkölä 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mälkölä mielessäin 

**Termiehdotus Fintossa:** [Mälkölä](http://finto.fi/yse/fi/page/Y507774)

**Comment by mirmaid** [comment]
Siis Mälkölä mielessä :-)
