### ISSUE TITLE
rakennushallinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7775]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakennushallinto](http://www.yso.fi/onto/ysa/Y98466) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi yläkäsite: hallinnonalat 

#### Perustelut ehdotukselle   

Parempi yläkäsite kuin nykyinen valtiovarainhallinto
Myös: https://github.com/NatLibFi/Finto-data/issues/959

**Comment by mirmaid** [comment]
YSOssa on lisäksi kaavoitus- ja rakennushallinto http://www.yso.fi/onto/yso/p13952 ympäristöhallinnon alakäsitteenä. Molemmat ovat olleet sanastossa aivan YSAn alkuajoista asti, joten todennäköisesti ne ovat viitanneet silloin eri asioihin, olisiko ensimmäinen liittynyt nimenomaan Rakennushallituksen toimintaan https://fi.wikipedia.org/wiki/Rakennushallitus.

**Comment by ilona-x** [comment]
**kaavoitus- ja rakennushallinto** on  käytety Melindassa vain 18 kertaa, ja suurin osa näyttää liittyvän Ympäristöministeriön julkaisemiin "Kaavoitus- ja rakennustoimen seuranta" -julkaisuihin: esim. v. 1989 julkaisu: http://hdl.handle.net/10138/304878

**Comment by YSO-kokous** [comment]
Poistetaan kaavoitus- ja rakennushallinto. Säilytetään rakennushallinto. YSO-ylläpito tarkistaa käsitteen hierarkian ja tutkii suhteen kiinteistöhallintoon sekä uudelleenohjauskäsitteen kaavoitus- ja rakennushallinto -käsittelle. Selvitetään, mitä käsitteitä käytetään nykyisin kaavoitus- ja rakennushallinnon alasta.

**Comment by ilona-x** [comment]
rakennushallinto (LT valtiovarainhallinto) on siis ilmeisesti peruja siitä, että  Valtionvarainministeriön alaisuudessa on toiminut Rakennushallitus (1936-1995):

"Rakennushallitus oli keskusvirasto, jonka **tehtäviin kuului huolehtia julkisten rakennusten suunnittelusta sekä valvoa yleisesti julkisen rakennuskannan kuntoa ja ylläpitoa.** 

Rakennushallitus lakkautettiin vuonna 1995, jolloin valtion kiinteistö- ja rakennusomaisuuden hallinta jaettiin viidelletoista valtion kiinteistöyksikölle. Niistä Valtion kiinteistölaitoksen vastuulle osoitettiin pääosa valtion rakennuksista, kun taas muut kiinteistöyksiköt (esimerkiksi vankeinhoitolaitos, tasavallan presidentin kanslia ja puolustushallinto) vastasivat kiinteistö- ja rakennusomaisuuden hallinnasta vain oman toimialansa osalta. Vuonna 2001 Valtion kiinteistölaitoksen nimi muuttui Senaatti-kiinteistöiksi."
Lähde: http://wiki.narc.fi/portti/index.php/Rakennushallitus

"Rakennushallitus oli virasto, joka vastasi joulukuusta 1936 vuoteen 1994 **rakennustoimeen liittyneistä tehtävistä**. Virasto oli alun perin jaettu rakennusosastoon, suunnitteluosastoon sekä ns. lisättyyn rakennushallitukseen. Suunnitteluosaston tehtävänä oli mm. uudisrakennusten ja muutostöiden suunnittelu sekä kaupunkien ja kauppaloiden rakennustoimintaa koskeneiden asioiden käsittely. Rakennusosaston vastuulla olivat mm. uudisrakennus-, muutos- ja korjaussuunnitelmiin kuuluneiden työselitysten ja kustannusarvioiden tarkastaminen sekä rakennushallinnon alaan kuuluneiden rakennustöiden ylin valvonta. Lisätyn rakennushallituksen vastuulla olivat kaikki kustannusarvioiltaan suuret valtion huonerakennusten uudisrakennus-, muutos- ja korjaustöiden suunnitelmat. Tämä koski myös kuntien ja yhteisöjen rakennussuunnitelmia, mikäli niihin oli oikeus saada valtionapua. **Rakennushallitus vastasi siis valtion rakennusten suunnittelusta ja rakentamisesta sekä valtion rakennusvalvonnasta**. "
Lähde: http://wiki.narc.fi/portti/index.php/Rakennushallituksen_piirustukset

--

Ympäristöministeriössä on ollut **kaavoitus- ja rakennusosasto** https://termipankki.fi/tepa/fi/haku/kaavoitus-%20ja%20rakennusosasto,  jonka nykyvastine saattaisi olla **Rakennetun ympäristön osasto** https://www.ym.fi/fi-FI/Ministerio/Organisaatio/Rakennetun_ympariston_osasto

**Comment by ilona-x** [comment]
**ympäristöhallinto**  
ALAKÄSITTEET
    asuntohallinto
    kaavoitus- ja rakennushallinto
    vesihallinto
    vesi- ja ympäristöhallinto
    ympäristönsuojeluhallinto

Jos kaavoitus- ja rakennushallinto poistetaan pitäisi varmaan tehdä ohjaus ympäristöhallintoon.

Näissä hallinnonaloissa on muitakin vanhentuneita kuin nämä tämän issuen 2 tapausta. Esimerkiksi asuntohallinto taitaa olla vastaava, sillä aiemmin on ollut Asuntohallitus, joka on lakkautettu v. 1993, https://fi.wikipedia.org/wiki/Asuntohallitus

Googlaamalla esimerkiksi rakennushallintoa ja asuntohallintoa löytyy lähinnä vain vanhoja aineistoja.

Jäin miettimään, että pitäisikö näitä kuitenkin jättää sanastoon historiallisina käsitteinä, kun kuitenkin Melindastakin löytyy viitteitä, joissa käsitellään juuri näitä. Tosin rakennushallintoa näyttää käytetyn muustakin kuin tuosta valtionvarainministeriön alaisesta toiminnasta. 

Ja mitä enemmän tuota rakennushallinto -termiä on tuijottanut, niin aloin miettiä, viittaako tuo alkuosa "rakennus" rakennuksiin vai rakentamiseen. 🤔 😄

**Comment by ilona-x** [comment]
Eli sanastossa on näköjään:
ympäristöhallinto (Luotu 1.1.1987)
vesihallinto (Luotu 9.12.2002)
vesi- ja ympäristöhallinto  (Luotu 1.1.1987)
🤯 

vesihallinto http://www.yso.fi/onto/yso/p19381
HUOMAUTUS
Nimitys käytössä v. 1970-1986. Vesihallinto muuttuui vuonna 1986 vesi- ja ympäristöhallinnoksi, jolloin vesihallitus lakkautettiin ja perustettiin vesi- ja ympäristöhallitus.

vesi- ja ympäristöhallinto http://www.yso.fi/onto/yso/p19380
HUOMAUTUS
Nimitys käytössä v. 1986-1995. Vesi- ja ympäristöhallinnon edeltäjä oli vesihallinto (1970-1986). Vesi- ja ympäristöhallinto sulautui ympäristöhallintoon ja maa- ja metsätaloushallintoon vuonna 1995, jolloin vesi- ja ympäristähallitus lakkautettiin ja sen tehtävät siirrettiin suurimmaksi osaksi Suomen ympäristökeskukselle.

--
Eli jos näitä "vanhentuneita" hallinnonaloja jätettäisiin sanastoon, pitäisi niille tehdä huomautukset tuohon vesi- ja ympäristöhallinnon tyyliin. Vaikka kyllähän tuo tietenkin hämmentää, kun sanastossa on monta samalta vaikuttavaa termiä. 🤔

**Comment by mirmaid** [comment]
https://www.suomi.fi/viranomaiselle/asuminen-ja-rakentaminen1/kiinteistohallinto

**Comment by mirmaid** [comment]
Mielestäni vanhentuneitakaan hallinnonaloja ei tarvitse poistaa sanastosta, mutta yhdistelmämuotoiset tuntuvat viittaavan nimenomaan tiettyyn virastoon ja ovat siksi ongelmallisempia ja myös käytössä hankalampia. Poistaisin siis molemmat yhdistelmäalat.

**Comment by ilona-x** [comment]
rakennushallinto tarvitsisi varmaankin tarkenteen, jos sen halutaan viittaavan vain kiinteistöjen hallintaan, kun Melindassa sitä näyttää käytetyn myös rakentamisen yhteydessä esimerkiksi:

- Rakentamisen säännöt ja päätöksenteko - kuka päättää ja millä perusteella.
- Rakentamisen ohjaus alueellisissa ympäristökeskuksissa.
- Rakennussuunnittelu Venäjällä ja rakennuslupakäytäntö Pietarissa 
- Rakentamisen ohjauksen tavoitteet 

Eli ilmeisesti alunperin YSOn rakennushallinto on viitannut valtionvarainhallinnon alla kiinteistöhallintoon (+ valtion/julkisten rakennusten rakentamiseen) ja ympäristöministeriön kaavoitus- ja rakennushallinto on ollut sitä muuhun rakentamiseen liittyvää rakennushallintoa.

**Comment by mirmaid** [comment]
^ Haittaako, jos sille jää vähän laajempi merkitys?

**Comment by mariaforsen** [comment]
Kannatan laajempaa merkitystä.

**Comment by YSO-kokous** [comment]
Poisteaan "kaavoitus- ja rakennushallinto" sekä "vesi- ja ympäristöhallinto", 
Jätetään erilliset vesihallinto, ympäristöhallinto ja rakennushallinto.
