### ISSUE TITLE
tasavallat (valtiot)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7776]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tasavallat (valtiot)](http://www.yso.fi/onto/ysa/Y110604) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkenne on ylimääräinen > tasavallat? 

#### Perustelut ehdotukselle   

Tasavallat lienee selkeä sellaisenaan, tarkenne valtiot ei anna olennaista lisäinformaatiota, vaan lähinnä hämmentää. Nykyisten linjausten mukaan tarkenne lisätään vain jos on tarpeen ja muilta vastaavilta monikkomuodoilta on jo poistettu tarkenteet.

**Comment by YSO-kokous** [comment]
Poistetaan käsitteeltä sulkutarkenne.
