### ISSUE TITLE
käytösoppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7779]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[käytösoppaat](http://www.yso.fi/onto/ysa/Y96672) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "etikettioppaat" sekä SLM:ään että YSOon. 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Ok/SLM

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
