### ISSUE TITLE
albumi / musiikkiäänite / äänilevy / tms [MTS]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7780]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

albumi / musiikkiäänite / äänilevy / tms [MTS] 

#### Tarkoitusta täsmentävä selite   

Useita sävellyksiä sisältävä äänitejulkaisu 

#### Perustelut ehdotukselle   

Tarvitaan 630-kenttään teoksen ensisijaisen hakutiedon lisäelementtinä erotukseksi samankaltaisesta muusta hakutiedosta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

My bonnie (albumi : 1962) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [albumi / musiikkiäänite / äänilevy / tms [MTS]](http://finto.fi/yse/fi/page/Y507780)

**Comment by tpalonen** [comment]
Kannatan käytettäväksi termiksi _albumit (musiikki)_. Luulisin, että tiedonhakija lähtee todennäköisemmin liikkeelle albumi-sanasta kuin musiikki-sanasta etsiessään albumeja/äänilevyjä. Äänilevyä en laittaisi käytettäväksi termiksi. Digitaalinen albumi tai kasetti ei liene äänilevy. Ja äänite-sana ei ainakaan Kielitoimiston sanakirjan määritelmän mukaan ("äänitetty tallenne, joka sisältää puhetta, musiikkia tms. ääntä, äänitallenne. _Konsertista tehty äänite. Musiikki-, puheäänite._") rajaudu pelkästään julkaistuihin äänitteisiin, vaan voi olla myös julkaisematon tallenne.

**Comment by MUUSA-kokous** [comment]
Muusa ei vastusta Metatietosanastoon vietyä termiä _musiikkialbumi_. Muusa toivoo, että Metatietosanaston musiikkitermiehdotukset tuotaisiin jatkossa myös Muusan käsittelyyn.
