### ISSUE TITLE
Horstmann-tekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7781]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Horstmann-tekniikka 

#### Ehdotettu termi englanniksi   

Horstmann Technique 

#### Ehdotettu termi ruotsiksi   

Horstmanntekniken 

#### Vaihtoehtoiset termit ja ilmaisut   

Horstmann-terapia 
Horstmann-menetelmä 
Horstmann-hoito 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hoitomenetelmät](http://www.yso.fi/onto/yso/p392) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Horstmann järjestelmä : filosofiasta käytäntöön 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Horstmann-tekniikka](http://finto.fi/yse/fi/page/Y507781)

**Comment by mirmaid** [comment]
Onhan näitä...

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
