### ISSUE TITLE
homesienet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7783]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[homesienet](http://www.yso.fi/onto/ysa/Y101669) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT homeet 

#### Perustelut ehdotukselle   

-

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
