### ISSUE TITLE
hydraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7784]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hydraus 

#### Vaihtoehtoiset termit ja ilmaisut   

vedytys 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Hydraus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Carbon Catalysts in Biofuel Production: from Furfural to 2-Methylfuran 

**Termiehdotus Fintossa:** [hydraus](http://finto.fi/yse/fi/page/Y507784)

**Comment by mariaforsen** [comment]
Sv. hydrogenering ET hydrering

**Comment by ilona-x** [comment]
LCSH: Hydrogenation http://id.loc.gov/authorities/subjects/sh85063436

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
