### ISSUE TITLE
Korouoman luonnonsuojelualue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7788]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Korouoman luonnonsuojelualue 

#### Vaihtoehtoiset termit ja ilmaisut   

Korouoman rotkolaakso, Korouoma 

#### Perustelut ehdotukselle   

Korouoma on Posion kunnassa sijaitseva rotkolaakso ja luonnonsuojelualue. 
https://www.luontoon.fi/korouoma
https://fi.wikipedia.org/wiki/Korouoma 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://julkaisut.metsa.fi/julkaisut/show/2404 

**Termiehdotus Fintossa:** [Korouoman luonnonsuojelualue](http://finto.fi/yse/fi/page/Y507788)

**Comment by mariaforsen** [comment]
Sv. Korouoma naturskyddsområde
