### ISSUE TITLE
Mari (kaupunki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7789]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Mari (kaupunki) 

#### Ehdotettu termi englanniksi   

Mari (Extinct city) 

#### Ehdotettu termi ruotsiksi   

Mari (stad) 

#### Vastaava käsite muussa sanastossa   

LCSH : Mari (Extinct city) <http://id.loc.gov/authorities/subjects/sh85081066> 
Wikipedia : https://fi.wikipedia.org/wiki/Mari_(kaupunki) 

#### Perustelut ehdotukselle   

Melindassa nyt jonkinverran (konversion tuottamia?) virheellisiä viitteitä, joissa tarkoitettu muinaista Marin kaupunkia: https://fi.wikipedia.org/wiki/Mari_(kaupunki), mutta nyt terminä on http://www.yso.fi/onto/yso/p113116, joka viittaa Marin tasavaltaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Prophets and prophecy in the ancient Near East 

#### Tarkoitusta täsmentävä selite   

Mari (nykyinen Tell Hariri) oli merkittävä kaupunki muinaisessa Mesopotamiassa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Mari (kaupunki)](http://finto.fi/yse/fi/page/Y507789)

**Comment by mirmaid** [comment]
vrt. Amarna, tämä myös LCSH:ssa Mari.

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Mari (kaupunki). Yläkäsitteeksi Syyria, RT Mesopotamia. Ohjaustermiksi Tell Hariri.
Muutetaan Mari (http://www.yso.fi/onto/yso/p113116) muotoon Marin tasavalta, ohjaustermiksi Marinmaan tasavalta.
