### ISSUE TITLE
itsejärjestäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7790]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

itsejärjestäytyminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.aalto.fi/sites/g/files/flghsv161/files/2019-08/press_release_alessandra_griffo.pdf 

#### Perustelut ehdotukselle   

Usein esim. materiaalitekniikan väitöskirjoissa 

**Termiehdotus Fintossa:** [itsejärjestäytyminen](http://finto.fi/yse/fi/page/Y507790)

**Comment by mariaforsen** [comment]
eng. self assembly? https://en.wikipedia.org/wiki/Self-assembly

**Comment by ilona-x** [comment]
LCSH: Self-assembly (Chemistry) http://id.loc.gov/authorities/subjects/sh00005345

http://www.tsk.fi/tepa/fi/haku/self%20assembly
spontaani yhdistyminen?

**Comment by YSO-kokous** [comment]
Ei hyväksytty sanastoon.

**Comment by mirmaid** [comment]
https://trepo.tuni.fi/handle/10024/124923

**Comment by YSO-kokous** [comment]
### Päätös
jää edelleen termiehdotukseksi

**Comment by mirmaid** [comment]
Taas: https://aaltodoc.aalto.fi/handle/123456789/101929

Myös "itsejärjestyminen".

**Comment by YSO-kokous** [comment]
### Päätös
voidaan harkita tarkenteellisena. Ei lisätty vielä.

**Comment by ilona-x** [comment]
taas väitöskirja:  http://urn.fi/URN:ISBN:978-952-64-0629-9

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _itsejärjestäytyminen (kemia)_. Tutkitaan aineistoista, onko _kemia_ riittävän laaja.

**Comment by mariaforsen** [comment]
Sv. self-assembly (kemi) HT självmontering (kemi)
https://termipankki.fi/tepa/fi/haku/self%20assembly
https://liu.se/artikel/materialvetenskap
https://www.aalto.fi/sv/forskning-och-konst/finansiering-via-advanced-grant-fran-erc
https://www.kth.se/profile/karalius?l=sv
