### ISSUE TITLE
kilpailukykysopimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7791]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kilpailukykysopimus 

#### Vaihtoehtoiset termit ja ilmaisut   

kiky-sopimus 

#### Perustelut ehdotukselle   

Kilpailukykysopimus (kiky-sopimus) on kesällä 2016 solmittu työehtosopimus, jonka avulla pyrittiin parantamaan Suomen talouden kilpailukykyä ja työllisyyttä. 
https://fi.wikipedia.org/wiki/Kilpailukykysopimus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.etla.fi/julkaisut/tyoaika-tyollisyys-ja-kilpailukyky/ 

**Termiehdotus Fintossa:** [kilpailukykysopimus](http://finto.fi/yse/fi/page/Y507791)

**Comment by mariaforsen** [comment]
Sv. konkurrenskraftsavtalet

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksyttiin sanastoon. Hyväksymisestä äänestettiin: 5 kannatti ottamista sanastoon, 4 vastusti. Ohjaustermiksi kiky-sopimus.
