### ISSUE TITLE
terveysteknologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7797]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

terveysteknologia 

#### Perustelut ehdotukselle   

Olisiko ok terveysteknologia KÄ hyvinvointiteknologia? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

MAD :designing social comparison features in health behaviour change technological interventions /Vasiliki Mylonopoulou. 

**Ehdottajan organisaatio:** Kb **Termiehdotus Fintossa:** [terveysteknologia](http://finto.fi/yse/fi/page/Y507797)

**Comment by mariaforsen** [comment]
Sv. hälsoteknologi
Google: "terveysteknologia" anta paljon enemmän tuloksia ja on myös esim. TEPAssa

**Comment by LeKorsu** [comment]
Lehtikielessä (lähde: Sanoman arkisto) terveysteknologia 518 osumaa, hyvinvointiteknologia 213 osumaa.

**Comment by ilona-x** [comment]
TEROssa: terveysteknologia http://www.yso.fi/onto/tero/TNR1937

**Comment by ilona-x** [comment]
http://www.tsk.fi/tepa/fi/haku/hyvinvointiteknologia

**Comment by YSO-kokous** [comment]
Hyvinvointiteknologia on jo sanastossa. Muutetaan käytettäväksi termiksi terveysteknologia, jos kuvailukäytön valossa tämä on ok. Muussa tapauksessa mietitään ratkaisua (ehkä molemmat omaksi käsitteekseen).

**Comment by ilona-x** [comment]
"On tärkeää, että lääkinnällisiä laitteita (l. terveysteknologiaa) ei sekoiteta hyvinvointiteknologiaan. Hyvinvointiteknologiaa ei ole tarkoitettu pääasialliseen lääketieteelliseen käyttöön eikä sitä ohjata lainsäädännöllä."
Lähde: https://www.sailab.fi/content/uploads/2019/09/mitaterveysteknologiaon_opas.pdf

**Comment by AuHo22** [comment]
Tuore oppikirja (Sosiaali- ja terveydenhuollon järjestelmä, 2020) näin: Hyvinvointiteknologia tarkoittaa tietoteknisiä ja teknisiä ratkaisuja, joilla ylläpidetään tai parannetaan ihmisten elämänlaatua, hyvinvointia, terveyttä ja toimintakykyä sekä työssä että vapaa-ajalla. Hyvinvointiteknologian hyödyntäminen hoito- ja palveluketjuissa ... -> lähtökohtina palvelujen saumattomuus, asiakaslähtöisyys ja kansalaisten omahoidon tukeminen. 
Terveysteknologialla tarkoitetaan tällä hetkellä lääketieteelliseen käyttötarkoitukseen tarkoitettuja ja in vitro-diagnostiikkaan tarkoitettuja lääkinnällisiä laitteita -> esim. verenpainemittarit, stetoskoopit tai haavanhoidon ja hammashoidon välineet samoin kuin syövänhoitoon tai kuvantamiseen käytettävä huipputeknologia, keinohaimat tai sydäntahdistimet (monia samansuuntaisia määritelmiä)

**Comment by LeKorsu** [comment]
Terveysteknologia omana käsitteenään selityksen kera, vaikkapa tuosta kirjasta, jota Auli siteeraa.

**Comment by mirmaid** [comment]
Ilmeisesti tosiaan molemmat syytä olla erikseen.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon uutena käsitteenä terveysteknologia.

**Comment by mariaforsen** [comment]
Mikä on tämän suhde "lääketieteellinen tekniikka"-termiin (myös YSOssa)?

**Comment by mirmaid** [comment]
Palaute: _Olen käyttänyt opparissani asiasanana käsitettä terveysteknologia, joka on synonyymi hyvinvointiteknologialle -- sitä käytetään yleisesti yhtä lailla kuin samaa tarkoittavaa hyvinvointiteknologiaakin. Itse valitsin työssäni käytettäväksi terveysteknologian, koska työni toimeksiantajakin käyttää sitä._

**Comment by YSO-kokous** [comment]
Tutkitaan lääketieteellinen tekniikka -käsitteen merkitys ja mahdollisesti korjataan hierarkiaa (nyt sairaalatekniikan alakäsite). Tutkitaan voidaanko tehdä seuraavat ohjaustermit:
terveysteknologia KÄYTÄ hyvinvointiteknologia
terveysteknologia KÄYTÄ lääketieteellinen tekniikka

**Comment by ilona-x** [comment]
YSOn lääketieteellinen tekniikka linkattu LCSH Medical technology, jonka KT Health technology http://id.loc.gov/authorities/subjects/sh85083046

**Comment by mirmaid** [comment]
Ainakin Wikipedia käsittelee lääketieteellisen tekniikan hyvin laajana: https://fi.wikipedia.org/wiki/L%C3%A4%C3%A4ketieteellinen_tekniikka. Riittäisikö silti nuo ylläolevat ohjaukset ja lääketieteellisen tekniikan siirto pois sairaalatekniikan alta?

**Comment by ilona-x** [comment]
Itselle lääketieteellinen tekniikka -termi tuo mieleen, että kyseessä on yksi tekiikan ala enemmin kuin laitteet. Tuohon suuntaan viittaisi ehkä myös lääketieteellisen tekniikan RT lääketieteellinen fysiikka.

**Comment by YSO-kokous** [comment]
Tehdään seuraavat muutokset:
lääketieteellinen tekniikka YK teknologia
terveysteknologia KÄYTÄ hyvinvointiteknologia
terveysteknologia KÄYTÄ lääketieteellinen tekniikka
YSO-ylläpito pohtii siirretäänkö sairaalatekniikka lääketieteellisen tekniikan alle.

Keskustelua hyvinvointiteknologian ja terveysteknologian erosta. Yleisesti ottaen hyvinvointi on laajempi termi kuin terveys. Hyvinvointiteknologia on kuluttajille suunnattuja tuotteita. Terveysteknologia on säännellympää ja vaatii CE-merkinnän. Ikäteknologian sanaston (TEPA-termipankki) määritelmä hyvinvointiteknologialle: "teknologia, jonka tavoitteena on edistää ja ylläpitää terveyttä, hyvinvointia tai itsenäistä suoriutumista; huomautus: Hyvinvointiteknologian laitteita ovat esimerkiksi askelmittarit, sykemittarit, unenlaatua mittaavat anturit ja hierovat tuolit. Myös sosiaalista vuorovaikutusta helpottavat laitteet ja palvelut, kuten videopuhelin ja palvelu-tv, ovat hyvinvointiteknologiaa."
