### ISSUE TITLE
kunnallispoliitikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7799]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kunnallispoliitikot](http://www.yso.fi/onto/ysa/Y112071) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään asiasanalle kuvaus ja käyttöohje. 

#### Perustelut ehdotukselle   

Tämän ja "kunnanvaltuutetut"-asiasanan merkitysero ja käyttötarkoitus eivät tällä hetkellä ilmene sanastosta, joten niiden käyttö saattaa olla horjuvaa. Termien välillä ei myöskään ole sanastossa edes RT-suhdetta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Suhde voisi (tai pitäisi) varmaan olla hierarkkinen, kaikki kunnanvaltuutetut ovat kunnallispoliitikkoja. Kunnallispoliitikkoja ovat sitten valtuutettujen lisäksi kaikki muut kuntapolitiikkaan osallistuvat henkilöt. Käyttö on varmasti jossain määrin epäjohdonmukaista, mutta voiko sitä estää kun molemmat käsitteet ovat kuitenkin tarpeellisia?

**Comment by YSO-kokous** [comment]
Kysytään Helsingin yliopiston kirjastolta: Sopisiko, että kunnanvaltuutettujen yläkäsitteeksi kunnallispoliitikot? Selventänee käsitteiden suhdetta.

**Comment by jtuohini** [comment]
Tässä HYK:ssä yhteiskuntatieteiden sisällönkuvailua tekevän Ilkka Päiväläisen kommentti: "[- -] jäin miettimään, olisiko kunnanvaltuutettu kunnallispolitiikon synonyymi. Keitä oikeastaan ovat kunnallispolitiikot varmojen nakkien eli kunnanvaltuutettujen lisäksi? Lautakuntien jäsenet? Palkatut puolueperusteiset virkamiehet kuten kunnanjohtajat ja opetustoimenjohtajat jne. Ei kai mikään laki pysty määrittelemään käsitteen sisältöä aivan tarkalleen? Päätöksentekoon osallistuminenkaan ei riitä, koska jonkun kulmakunnan asukkaiden puolestapuhuja saattaa ns. virallisen politiikanharjoittamisen ulkopuolella pyrkiä vaikuttamaan asioihin, ja sekuin on kunnallispolitiikkaa."

**Comment by jtuohini** [comment]
Äskeinen oli siis Ilkka Päiväläiseltä tullut kommentti (kunnia sille, jolle kunnia kuuluu).

**Comment by jtuohini** [comment]
Ilkan kommentin pohjalta peukutan YSO-kokouksen ehdotusta suhteeksi: **kunnallispoliitikot** ST **kunnanvaltuutetut** ts. 'kaikki kunnanvaltuutetut ovat kunnallispoliitikkoja, mutta kaikki kunnallispoliitikot eivät ole kunnanvaltuutettuja'.

**Comment by LeKorsu** [comment]
Hämmennän soppaa vielä sillä, että olisiko kuntapoliitikot  nykyisin modernimpi kuin kunnallispoliitikot? Kunnallisvaalit kun on nykään kuntavaalit ja kunnallisvaltuustot kuntavaltuustot. Mutta siis kuntapoliitikot ohjaa vielä kunnallispoliitikkoihin ja kuntapolitiikka kunnallispolitiikkaan.

**Comment by YSO-kokous** [comment]
Jätetään kunnallispoliitikot käytettäväksi termiksi, niukka enemmistö kannatti termin säilyttämistä käytettävänä terminä.
