### ISSUE TITLE
ekomusikologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7800]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ekomusikologia 

#### Vaihtoehtoiset termit ja ilmaisut   

ekokriittinen musiikintutkimus 

#### Perustelut ehdotukselle   

"Ekomusikologia on ympäristökriisien motivoima kriittisen musiikintutkimuksen osa-alue, joka tutkii musiikkia ja äänellistä kulttuuria ihmisen ympäristö- ja luontosuhteen indikaattorina pyrkimyksenään ihmisen arvojen ja toiminnan muuttaminen ympäristön kannalta kestävämpään suuntaan.”
https://alusta.uta.fi/2013/05/14/ymparistonsuojelua-musiikin-avulla/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-29-7894-6 

**Termiehdotus Fintossa:** [ekomusikologia](http://finto.fi/yse/fi/page/Y507800)

**Comment by mariaforsen** [comment]
Sv. ekomusikologi ET ekokritisk musikforskning

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT musiikintutkimus
RT ekologia

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
