### ISSUE TITLE
stressisäikeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7803]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

stressisäikeet 

#### Vaihtoehtoiset termit ja ilmaisut   

aktomyosiinisäikeet 

#### Perustelut ehdotukselle   

Stressisäikeet pitävät yllä solun muotoa. http://www.solunetti.fi/fi/solubiologia/stressisaikeet/2/
https://www.helsinki.fi/fi/uutiset/elamantieteet/helsingin-yliopiston-tutkijat-saivat-selville-miten-solut-reagoivat-lahiymparistonsa-mekaanisiin-muutoksiin 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-5391-3 

**Termiehdotus Fintossa:** [stressisäikeet](http://finto.fi/yse/fi/page/Y507803)

**Comment by mariaforsen** [comment]
Sv. stressfilament? /solunetti

**Comment by HeidiRonkainen** [comment]
Entä Aktomyosiini-kimppu tai pelkkä aktomyosiini?
Aktomyosiini = aktiinista ja myosiinista koostuva valkuaisainekompleksi, jonka aktiini- ja myosiinisäikeiden keskinäiseen liikkeeseen lihassolun supistuminen perustuu
https://www.jyu.fi/sport/fi/opiskelu/opiskelijan-ohjeet/opiskelun-tueksi/liikuntabiologian-sanasto

Väitöskirjassa http://urn.fi/URN:ISBN:978-951-51-3734-0 "aktomyosiini-kimput, joita kutsutaan ventraaleiksi stressisäikeiksi"

**Comment by mirmaid** [comment]
FinMeSHissä on aktomyosiini http://www.yso.fi/onto/mesh/D000205 ja stressisyyt http://www.yso.fi/onto/mesh/D022502.

**Comment by mirmaid** [comment]
Stress fibers are contractile actin bundles found in non-muscle cells (?) https://en.wikipedia.org/wiki/Stress_fiber

**Comment by YSO-kokous** [comment]
Otetaan sanastoon aktomyosiini.

Stressisyiden ja stressisäikeiden termistö ja merkitysero epäselvä.

**Comment by mariaforsen** [comment]
Sv. aktomyosin
