### ISSUE TITLE
sensoriverkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7805]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sensoriverkot](http://www.yso.fi/onto/ysa/Y171540) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään KT anturiverkot 

#### Perustelut ehdotukselle   

https://tieteentermipankki.fi/wiki/Nimitys:anturiverkko 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
