### ISSUE TITLE
dasatinibi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7806]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dasatinibi 

#### Ehdotettu termi englanniksi   

dasatinib 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-2117-2 

#### Perustelut ehdotukselle   

Dasatinibi (C22H26SN7ClO2) on heterosyklinen orgaaninen yhdiste. https://fi.wikipedia.org/wiki/Dasatinibi 

**Termiehdotus Fintossa:** [dasatinibi](http://finto.fi/yse/fi/page/Y507806)

**Comment by mariaforsen** [comment]
Sv. dasatinib
