### ISSUE TITLE
aggressiivinen fibromatoosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7808]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aggressiivinen fibromatoosi 

#### Ehdotettu termi ruotsiksi   

aggressiv fibromatos 

#### Ehdotettu termi englanniksi   

Fibromatosis, Aggressive 

#### Vaihtoehtoiset termit ja ilmaisut   

Desmoids 
desmoidit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvaimet](http://www.yso.fi/onto/yso/p2299) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D018222> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Desmoid tumor : oncological management and prognostic biomarkers 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aggressiivinen fibromatoosi](http://finto.fi/yse/fi/page/Y507808)

**Comment by mirmaid** [comment]
Lääketieteen termit: **desmoidi:** aggressiivinen fibromatoosi | lihaskalvosta alkunsa saava, mikroskooppiselta rakenteeltaan fibrosarkoomaa muistuttava hyvänlaatuinen mutta herkästi uusiutuva sidekudosmuodostuma, vrt. **fibromatoosi:** fibroomien esiintyminen; sidekudoksen kiinteä, epäselvärajainen liikakasvu

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa aggressiivinen fibromatoosi, ohjaustermiksi desmoidi.

**Comment by mariaforsen** [comment]
Sv. ET desmoid
