### ISSUE TITLE
markkinat (tapahtumat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7809]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[markkinat (tapahtumat)](http://www.yso.fi/onto/ysa/Y172946) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan asiasanan englanninkielinen muoto --> "fairs and markets" tms ja lisätään sille siltaus LCSH-sanastoon asiasanoihin "Fairs" ja "Markets" 

#### Perustelut ehdotukselle   

* https://en.wikipedia.org/wiki/Fair
* http://id.loc.gov/authorities/subjects/sh85046910 (LCSH-asiasana "Fairs"
* http://id.loc.gov/authorities/subjects/sh85081355 (LCSH-asiasana "Markets") 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
YSOn ylläpito pohtii tätä. @tpalonen

**Comment by tpalonen** [comment]
Vaihdettiin englannin käytettäväksi termiksi "fairs and markets" ja linkit ehdotettuihin.
