### ISSUE TITLE
hiilinanoputket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7810]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hiilinanoputket 

#### Ehdotettu termi englanniksi   

carbon nanotubes 

#### Ehdotettu termi ruotsiksi   

kolnanotuber 

#### Ehdotettu yläkäsite YSOssa (LT)   

[nanoputket](http://www.yso.fi/onto/yso/p25661) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2013002061> 
FinMeSH : <http://www.yso.fi/onto/mesh/D037742> 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa, Melinda x 14 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Electrical conductivity of functionalised carbon nanotube networks 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 
[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hiilinanoputket](http://finto.fi/yse/fi/page/Y507810)

**Comment by satuniininen** [comment]
Sanastossa on jo nanoputket, jota on käytetty Meindassa 78 kertaa pääasiassa hiilinanoputkien yhteydessä

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

Hiilinanoputket yleisin nanoputkien tyyppi. MeSHissä ja LCSH:ssa on molemmat erikseen.
