### ISSUE TITLE
hammasplakki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7811]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hammasplakki 

#### Vastaava käsite muussa sanastossa   

<http://www.yso.fi/onto/mesh/D003773> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Structural and interfacial adhesion elements of indirect fiber-reinforsed composite 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hammasplakki](http://finto.fi/yse/fi/page/Y507811)

**Comment by mariaforsen** [comment]
Sv. tandplack ET plack (tänder)
