### ISSUE TITLE
kaviokuume

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7813]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaviokuume 

#### Ehdotettu termi ruotsiksi   

fång 

#### Ehdotettu termi englanniksi   

laminitis 

#### Vaihtoehtoiset termit ja ilmaisut   

laminiitti 

#### Perustelut ehdotukselle   

Kaviokuume (laminiitti) on hevosen sairaus, jossa kavion uloimman kerroksen, sarveiskavion, ja sen sisäpuolella olevan martokavion välinen sälekerros (lamina) tulehtuu. 
https://fi.wikipedia.org/wiki/Kaviokuume 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-2123-3 

**Termiehdotus Fintossa:** [kaviokuume](http://finto.fi/yse/fi/page/Y507813)

**Comment by mariaforsen** [comment]
Sv. fång (sjukdomar)

**Comment by mirmaid** [comment]
LCSH: Laminitis
