### ISSUE TITLE
aortan aneurysma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7814]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aortan aneurysma 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Outcomes after ascending aortic surgery 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aortan aneurysma](http://finto.fi/yse/fi/page/Y507814)

**Comment by mariaforsen** [comment]
Sv. aortabråck ET aortaaneurysm
