### ISSUE TITLE
ahtaus (tiivis tunnelma)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7818]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ahtaus (tiivis tunnelma) 

#### Perustelut ehdotukselle   

https://github.com/Finto-ehdotus/YSE/issues/7515 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ahtaus (tiivis tunnelma)](http://finto.fi/yse/fi/page/Y507818)

**Comment by mariaforsen** [comment]
Vai olisiko tarkenteena ok vähemmän tarkka (ominaisuudet) tms.? Kyseessä voi kai olla enemmän kuin pelkkä "tunnelma"

**Comment by mirmaid** [comment]
Sopivaa tarkennetta/termimuotoa sopii mielellään ehdottaa, alkuperäinen on vain kuvaamassa sitä mistä on kyse vs. _ahtaustyö_. 

_Ahtaus (ominaisuus) / ahtaus (tilat) / tilanahtaus_ tms.

**Comment by satuniininen** [comment]
Kannatan muotoa tilanahtaus KT ahtaus

**Comment by ilona-x** [comment]
ahtaus-termiä käytetty esim. koirien kuonon ahtaudesta, koira + ahtaus haku tuottaa Melindassa 7 viitettä. Jos termillä halutaan kattaa myös tämä näkökulma, olisi ehkä ahtaus (ominaisuudet) toimivin vaihtoehto. 🤔

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa "ahtaus (ominaisuudet)".

**Comment by mariaforsen** [comment]
Sv. trånghet ET trängsel
