### ISSUE TITLE
pemfigoidi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7820]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pemfigoidi 

#### Vaihtoehtoiset termit ja ilmaisut   

rakkulainen pemfigoidi KÄ pemfigoidi 

#### Tarkoitusta täsmentävä selite   

Pemfigoidi (lat. pemphigoides, ”pemfiguksen kaltainen”) on autoimmuunitauteihin kuuluva sairaus. Sitä tunnetaan neljä eri tyyppiä. Niille on ominaista rakkuloiden muodostuminen, kun autoimmuunivaste kohdistuu epiteelisolujen tyvikalvoon. Suomessa tavataan parisataa uutta tapausta vuodessa. 

#### Perustelut ehdotukselle   

taudin nimi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Drugs, dermatitis herpetiformis and celiac disease as risk factors for bullous pemphigoid in Finland /Outi Varpuluoma. 

**Ehdottajan organisaatio:** KB **Termiehdotus Fintossa:** [pemfigoidi](http://finto.fi/yse/fi/page/Y507820)

**Comment by mariaforsen** [comment]
Sv. pemfigoider

**Comment by mirmaid** [comment]
Lääketieteen termit: pemfigoidi: _autoimmuunisairauksiin kuuluvia tai syöpien →paraneoplastisena ihoilmiönä syntyviä ihon ja limakalvojen rakkulatauteja, joille on ominaista orvaskeden irtoaminen ja orvaskeden tyvikalvon aineosiin kohdistuvien vasta-aineiden esiintyminen; vrt. pemfigus._

pemfigus: 1. (ihon) rakkulatauti | ihon ja limakalvojen autoimmuunisairauksia, joissa epiteelisolujen tai orvaskeden keratinosyyttien →akantolyysi aiheuttaa rakkuloita ja haavapintoja; vrt. pemfigoidi; 2. pemphigus vulgaris

pemphigus vulgaris: tavallinen pemfigus | vakavin pemfigusmuoto, jossa esiintyy limakalvorikkoumien lisäksi pään, ylävartalon ja raajojen laajoja, verestäviä, rupeutuvia haavapintoja

**Comment by mirmaid** [comment]
FinMeSH: pemfigus http://www.yso.fi/onto/mesh/D010392

**Comment by mirmaid** [comment]
Pemfigoidi: https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00594
Pemfigus: https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00595

**Comment by mirmaid** [comment]
Myös _Alterations of Immune System Function in Frontotemporal Lobar Degeneration_

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa pemfigoidit.
