### ISSUE TITLE
umpilisäketulehdus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7821]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[umpilisäketulehdus](http://www.yso.fi/onto/ysa/Y146927) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT umpilisäkkeen tulehdus 

#### Perustelut ehdotukselle   

FinMeSH: umpilisäkkeen tulehdus http://www.yso.fi/onto/mesh/D001064 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
