### ISSUE TITLE
influenssa B -virus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7822]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

influenssa B -virus 

#### Ehdotettu termi englanniksi   

influenza B virus 

#### Ehdotettu termi ruotsiksi   

influensavirus typ B 

#### Perustelut ehdotukselle   

A on jo. 
https://en.wikipedia.org/wiki/Influenza_B_virus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-1925-4 

**Termiehdotus Fintossa:** [influenssa B -virus](http://finto.fi/yse/fi/page/Y507822)

**Comment by mariaforsen** [comment]
Sv. influensa B-virus ET B-influensavirus
