### ISSUE TITLE
erikoisbibliografiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7823]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[erikoisbibliografiat](http://www.yso.fi/onto/ysa/Y101279) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään selitys ja käyttöohje niin YSOn kuin SLM:n puolella 

#### Perustelut ehdotukselle   

Termin merkitys ja käyttötapa ovat tällä hetkellä täysin epäselvät, mikä ei liene tarkoituksenmukaista. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Laaditaan määritelmä (ja mahdollisesti käyttöhuomautus) konsultoimalla Helsingin yliopiston kirjastoa.

**Comment by jtuohini** [comment]
Wikipediassa on seuraavanlainen listaus: "Bibliografioita käytetään työvälineenä muun muassa kirjastoissa ja tutkimuksissa. Myös viestinnän ammattilaiset käyttävät työssään bibliografioita. Bibliografioita on esimerkiksi sisällön mukaan tehtyjä, kuten yleisbibliografiat, aihebibliografiat, erikoisbibliografiat ja henkilöbibliografiat, tai erikoisbibliografioita, kuten akateemisten julkaisujen bibliografiat, aikakauslehtiluettelot, aikakauslehti- tai sanomalehti-indeksit, tai henkilöbibliografioita, jotka ovat tietyn henkilön kirjoituksien ja tuotannon luetteloja." [https://fi.wikipedia.org/wiki/Bibliografia] – Erikoisbibliografia oudosti toistettu tuossa listassa.
 
Mutta määritelmän peruskysymys kuuluu siis: mikä tekee bibliografiasta erikoisbibliografian? Jos määritelmä on hyvä, olisi termin käyttökin nykyistä helpompaa, nimenomaan sen suhteen, valitako 655-kenttään _bibliografiat_ vai _erikoisbibliografiat_.

**Comment by mirmaid** [comment]
Kyse ”bibliografiat” versus ”erikoisbibliografiat” -ongelmasta. Tiivistettynä: mikä tekee bibliografiasta erikoisbibliografian?

**Comment by AuHo22** [comment]
YKL 01.5 Erikoisalojen luettelot
Tähän bibliografiset julkaisut, jotka koskevat pääluokkaan 0 kuuluvia erikoisaloja -- Tähän ja alaluokkiin erikoisalojen bibliografiset julkaisut julkaisun ja sen kohteiden materiaalityypistä riippumatta -- (jne. myöhempi teksti). 
Googlaamalla näyttäisi siltä, että erikoisbibliografia-termiä käytetään myös merkityksessä aihebibliografiat, so. merkityksessä erikoisalan bibliografia. Pitäisi erotella selkeästi toisistaan - aihebibliografiat-termiä ei tällä hetkellä ole, vaatii selvittelyä.

**Comment by mirmaid** [comment]
Laaditaan linjaus yhdessä YKL-ryhmän kanssa.

**Comment by ilona-x** [comment]
Esimerkkejä SKS:n julkaisemista henkilö- ja erikoisbibliografioista:
https://www.finlit.fi/fi/kirjasto/kokoelmat-ja-tiedonlahteet/sksn-kirjaston-julkaisemia-bibliografioita

**Comment by ilona-x** [comment]
UDK:n erikoisbibliografiat-luokka https://finto.fi/udcs/fi/page/014760

**Comment by jtuohini** [comment]
Ja vertailun vuoksi UDK:n jaottelu: http://udcdata.info/014750

**Comment by ilona-x** [comment]
"Erikoisbibliografiat rajoittuvat tiettyyn muodolliseen kategoriaan, esim. akateemisiin julkaisuihin  (mm. väitöskirjoihin), salanimellä julkaistuihin julkaisuihin, aikakauslehtiartikkeleihin. Erikoisbibliografiat luetteloivat tietyllä aihealueella julkaistua kirjallisuutta. Niitä on esiintyy lähinnä kirjastojen käsikirjastoissa. Jos haluaa tutustua johonkin uuteen asiaan tai aihealueeseen ja löytää tuoreen aihetta käsittelevän bibliografian, on erinomaiset mahdollisuudet jatkotiedonhakuun. Erikoisbibliografiat ilmestyvät usein erillisinä julkaisuina tai omina tietokantoinaan, mutta lyhyitä hyödyllisiä bibliografioita sisältyy usein aihealueen kurssikirjoihin tai tietosanakirjoihin. Väitöskirjojen lähdeluetteloita pidetään usein aiheensa kattavina bibliografioina, joskin väitöskirjan aihe voi olla hyvinkin rajattu. Painetut bibliografiat ovat yhä tärkeitä monilla humanistisilla tieteenaloilla, oikeustieteessä ja yhteiskuntatieteissä, mutta ehkä vähemmän luonnontieteissä. Bibliografisia erikoistietokantoja aikakauslehtiartikkeliviitteineen käytetään kaikilla tieteenaloilla. Esimerkki erikoisbibliografiasta: Suomen historiallinen bibliografia=Finsk historisk bibliografi / H:ki - Suomen historiallinen seura. Tämä bibliografia on ilmestynyt monessa osassa ja kattaa tällä hetkellä ajanjankson 1544 - 1990; nykyään tiedot sisältyvät myös artikkelitietokanta ARTOon."

Lähde: https://web.archive.org/web/20160425231632/http://oppimateriaalit.internetix.fi/fi/avoimet/0viestinta/informaatiotutkimus/po3/bibliografiat

**Comment by mirmaid** [comment]
Jaakko laatii määritelmäehdotukset, käsitellään seuraavassa kokouksessa.

**Comment by jtuohini** [comment]
Ei tarkkoja määritelmiä, mutta suuntaa-antavia, mitä milläkin SLM-termillä suunnilleen tarkoitettaisiin:
**bibliografiat** = mikä tahansa kirjallisuusluettelo; ST-suhteisina termeinä:

- **_aihebibliografiat_** = tiettyä aihetta käsittelevän kirjallisuuden luettelo
- **aluebibliografiat** = tietyllä alueella julkaistun kirjallisuuden luettelo
- **erikoisbibliografiat** = tietyntyyppisen kirjallisuuden (esim. artikkelit, vain fragmentaarisina säilyneet tekstit, pergamentille painetut kirjat, pienpainatteet, pistekirjat, sensuroitu kirjallisuus, väitöskirjat) luettelo
- **henkilöbibliografiat** = yksittäisen henkilön kirjallisen tuotannon kattava luettelo (vrt. **teosluettelot**)
- **kansallisbibliografiat** = yksittäisen maan tai valtion kirjallisuuden luettelo (rajaus ja painotus vaihtelee maittain)

**Comment by AuHo22** [comment]
Esim. regional bibliography (Wikidata)
Bibliography that records literature about a specific region
tai
https://svkpk.cz/en/pro-verejnost/prezencni-sluzby/regionalni-bibliografie/ 
-> tarkennus: tiettyä aluetta käsittelevän kirjallisuuden luettelo tms.?

**Comment by jtuohini** [comment]
Jos "paikallisbibliografia" tarkoittaisi SLM:ssä tiettyä paikkaa käsittelevän aineiston bibliografiaa, olisi se sama asia kuin mikä tahansa muu "aihebibliografia" ja siten itsenäisenä terminä turha.

**Comment by AuHo22** [comment]
Aiemmin keskusteltiin siitä, että henkilöbibliografiat yhtä hyvin on omanlaisensa aihebibliografia - aiheena henkilön tuotanto - myös sen kaksinaiskäyttö tuli tuolloin esille eli kysymys siitä, sisältyykö määritelmään sen lisäksi hänestä kirjoitettujan teosten luetteloa? Nykyinen paikallisbibliografian määritelmä uhkaa tehdä vaikkapa Kuopion kaupungin kirjastoluettelosta paikallisbibliografian, kun varsinaisesti paikallisbibliografialla kuitenkin tarkoitettaneen heidän alueellista maakuntakokoelmaansa / sen luetteloa. Lisäesimerkkejä:

https://www.bu.uni.wroc.pl/en/e-sources/databases-alphabetical-order/bibliography_region
https://www.wlb-stuttgart.de/en/literature-search/baden-wuerttemberg/landesbibliographie/

**Comment by jtuohini** [comment]
Kuopion kaupungin kirjastoluettelo on mielestäni SLM:n näkökulmasta kokoelmaluettelo ([**kokoelmaluettelot**](http://urn.fi/URN:NBN:fi:au:slm:s1335)) ja tietokanta ([**tietokannat**](http://urn.fi/URN:NBN:fi:au:slm:s1311)), ei bibliografia ensinkään.

Paikallisbibliografia voi toki olla tietokantamuotoinen, mutta aika harvoja tietokantoja Melinda-kontekstissa yleensäkään on kuvailtu omina tietueinaan.

Vai oliko kommentissa kyse painetusta kokoelmaluettelosta, joka olisi painotuksensa vuoksi myös paikallisbibliografia? (Kokoelmaluettelo kattaa jonkin organisaation tai jonkun henkilön kokoelmat, bibliografia taas ei ota välttämättä ota kantaa, mistä aineiston saa käsiinsä.)

**Comment by jtuohini** [comment]
Yksi tärkeä huomio mielestäni on, miten 655 + muut 6XX-kentät suhtautuvat toisiinsa:

Jos 655:ssä on _aihebibliografiat_ ja 600:ssa vaikkapa kirjailijan nimi, kattaisi kuvailtu bibliografia kyseistä kirjailijaa käsittelevän kirjallisuuden, ja jos 655:ssä olisikin _henkilöbibliografiat_ ja 600:ssa samainen kirjailija, kattaisi tällä tavoin kuvailtu bibliografia kyseisen kirjailijan tuotannon, ei häntä käsittelevää kirjallisuutta.

Vastaava logiikka myös kaikissa yhdistelmissä:

- 600 = mainitun henkilön tuotanto ~ kyseistä henkilöä käsittelevä aineisto ~ kyseisen henkilön tuotantoa käsittelevä aineisto
- 648 = tiettynä aikana luotu aineisto ~ kyseistä aikaa käsittelevä aineisto
- 651 = tietyssä paikassa luotu aineisto ~ kyseistä paikkaa käsittelevä aineisto

Tätä eroa ei voi tehdä, jos 655:ssa käytettävät termit ovat epätarkkoja. LCSH:ssa vastaavaa ongelmaa ei juuri ole, kun ketjuilla ja muilla keinoin voidaan ilmaista tiedonhaun kannalta näkökulmat sangen yksiselitteisesti, ks. [**Bibliography**](http://id.loc.gov/authorities/subjects/sh85013838). Suomessa pitäisi ehdottomasti päästä edes jossain määrin samaan.

**Comment by AuHo22** [comment]
"_kansallisbibliografiat = yksittäisen maan tai valtion kirjallisuuden luettelo (rajaus ja painotus vaihtelee maittain)"_ -> tässä lienee sitten myös kyse pikemminkin kokoelmaluettelosta eikä bibliografiasta? Muistan ajan, jolloin yliopistokirjastot olivat kiinnostuneet ns. kokoelmakartoista eli kuvailemaan kokonaisia kokoelmia, joihin tämän kaltaiset termit sopisivat, mutta lieneekö niille enää tarvetta?

**Comment by jtuohini** [comment]
Kansallisbibliografiat eivät sikäli ole kokoelmaluetteloita, että ne pyrkivät usein antamaan kattavan kuvan tietyn maan kirjallisuudesta, olipa luettelossa mainittua kirjallisuus tallella jossain tai kadonnutta. Kaikissa maissa ei edes ole kansalliskirjastoa tms, vaikka kansallisbibliografia olisikin laadittuna. Edelleen olen sitä mieltä, että bibliografia on kirjallisuusluettelo (yleensä) ja kokoelmaluettelo asia erikseen. Kansallisbibliografia voi olla kumpaakin yhtä aikaa, riippuen sisältääkö se bibliografialle ominaisten viitetietojen lisäksi viitatun aineiston saatavuustiedot.

**Comment by AuHo22** [comment]
Em. SKS:n henkilöbibliografioihin on sisällytetty ko. henkilön tuotannosta kirjoitettuja arvosteluja, haastettelujakin. Myös henkilöbibliografioiden tekijä: https://www.vartija-lehti.fi/henkilobibliografioiden-laatimisesta-ja-merkityksesta/
(Henkilö)Bibliografia käsittää esipuheen lisäksi luettelon Vikströmin teoksista ja niiden arvosteluista, kirjoituksista erilaisissa kokoomateoksissa sekä aikakaus- ja sanomalehdissä, hänen laatimistaan kirja-arvosteluista, piispan tai arkkipiispan viran hoitamiseen kuuluvista julkaisuista sekä julkaistuista puheista ja haastatteluista.

**Comment by AuHo22** [comment]
Saksankielinen wikipedia:
**Fachbibliografien** verzeichnen Literatur zu einem bestimmten Fach (beispielsweise zur Geschichtswissenschaft) oder zu einem Teilgebiet des Faches (beispielsweise zur antiken Geschichte).
**Spezialbibliografien** verzeichnen Fachliteratur zu bestimmten, enger definierten Themen eines Faches.
**Personalbibliografien** verzeichnen **Texte einer von einer bestimmten Person (subjektive Personalbibliografie)** bzw. **über eine bestimmte Person (objektive Personalbibliografie)**.
It.
**Bibliografia specializzata o tematica**: elenco di libri e documenti che riguardano una determinata disciplina, per esempio la letteratura classica jne.

Eli näissä määritelmissä on aihe- ja erikoisbibliografia hyvinkin pitkälle yhtäläistetty. Sen lisäksi saksal. määritelmässä erotetaan kahdenlainen henkilöbibliografia.

**Comment by AuHo22** [comment]
Palataksemme alkuperäiseen lähtökohtaan eli määritelmän tarpeeseen erikoisbibliografialle ehdotan:
-muitten bibliografioiden määritelmät jätetään pois tässä vaiheessa, hajonta on suuri siinä kuinka niitä määritellään
-erikoisbibliografian määritelmä ymmärretään laajasti: siihen sisällytetään aihebibliografian määritelmä ja KT-ohjaus ; näin termiä on käytetty vaikkapa esimerkkinä olleen SKS:n sivuilla, ja yo. määritelmissä (Ilona-x, AuHo22)

**Comment by jtuohini** [comment]
Mielestäni kaikki eri bibliografiatyypit pitää ratkaista yhtenä kokonaisuutena. Muuten käyttö jatkuu yhtä sekavana kuin tähänkin asti. Ja jokaisen bibliografiatyypin pitää olla aidosti muista erottuva, jotta on perusteita ottaa/pitää ne sanastossa ja jotta niitä oikeasti voidaan tulevaisuudessa käyttää täsmälliseen tiedonhakuun.

**Comment by AuHo22** [comment]
En tiedä kuinka pitkälle yleissanastossa ylipäätään on tarkoituksenmukaista "hallita todellisuutta", tai sitten joutuu tarkkuuden takia - tai sen takia ettei asioita poissuljeta kokonaan, ottamaan uusiakin termejä, mielestäni tarvitaan sitten jo objektiiviset henkilöbibliografiat sekä subjektiiviset henkilöbibliografiat, ellei henkilöbibliografiat-määritelmääkään haluta nähdä laajasti?

**Comment by mirmaid** [comment]
Teosluettelot vaatii määritelmän (vai tarkenteen?) ollakseen yksiselitteinen.

Henkilöbibliografiat: rajataan tarkoittamaan bibliografioita, joissa henkilö on aiheena TAI jätetään kokonaan pois TAI käytetään myös kirjailijoiden teosluetteloista, jolloin lisätään KT teosluettelot (kirjailijat).

**Comment by AuHo22** [comment]
YKL 01.4 Henkilöbibliografiat

Käyttöhuomautus: 
Tähän kaikki henkilöbibliografiat bibliografian ja sen kohteiden materiaalityypistä riippumatta Tiettyä henkilöä tai henkilöryhmää koskevien julkaisujen luettelot ja valikoimaluettelot Tietyn henkilön tai henkilöryhmän julkaisemien teosten tai kirjoitusten luettelot ja valikoimaluettelot Tähän myös säveltäjien ja taiteilijoiden teosluettelot, esim. sävellysluettelot ja filmografiat Tähän myös äänitteitä tai kuvatallenteita sisältävät henkilöbibliografiat Anonyymi- ja pseudonyymiluettelot

**Comment by mirmaid** [comment]
**aluebibliografiat**
o kysymys: kumpaa tällä tarkoitetaan Tamperetta käsittelevä kirjallisuus vai Tampereella julkaistu/luotu kirjallisuus?
o Melindassa termiä on käytetty molemmista merkityksistä
o rajataan merkitykseen ”tietyllä alueella julkaistun kirjallisuuden luettelo”
1. aluebibliografiat (julkaisualue)
2. aluebibliografiat (aihe) KÄYTÄ aihebibliografiat

**erikoisbibliografiat**
o ehdotus käytettäväksi termiksi: ”aineistotyypin erikoisbibliografiat” tai ”tietyntyyppisten teosten bibliografiat” (UDKssa käytetty tätä muotoa)
o nyt erikoisbibliografiat-termiä on käytetty myös aihebibliografioista
o erikoisbibliografiat (tietystä aiheesta) KÄYTÄ aihebibliografiat

**aihebibliografiat**
o tätä termiä ei ole nyt SLM-sanastossa
o toivottiin, että aihebibliografiat otettaisiin SLM-termiksi
o määritelmä: ”tiettyä aihetta käsittelevän kirjallisuuden luettelo”

**henkilöbibliografiat**
o rajataan henkilöbibliografiat-termin käyttöä yksittäisen henkilön kirjallisen tuotannon kattavaan luetteloon:
1. henkilöbibliografiat (kirjoittajan teosluettelot)
2. henkilöbibliografiat (aihe) KÄYTÄ aihebibliografiat

**Comment by AuHo22** [comment]
Kommentti: aluebibliografiat -> rajataan merkitykseen ”tietyllä alueella julkaistun kirjallisuuden luettelo” esim. Melinda id 018224708 Pirkanmaalaisen kaunokirjallisuuden käännöksiä / laatinut Maarit Helen-> tietueessa kuitenkin taitaa olla kyse tietyllä alueella luoduista teoksista, jotka on voitu niputtaa aluebibliografiaksi, .-> Epäilenpä että julkaisutoiminta on kuitenkin tapahtunut yleisemmin vieraitten maitten julkaisukeskuksissa eikä aluebibliografiat (julkaisualueella). 

-aluebibliografiat (aihe) KÄYTÄ aihebibliografiat on mielestäni keinotekoinen ottaen huomioon sen pitkän tradition, kuinka aluebibliografioita on käytetty kuvailussa sekä kuinka sitä myös edelleen määritellään.

Itse taipuisin edelleen käyttämään vain yhtä termiä ja asiasanoituksesta sitten olisi käytävä esille, kummasta määritelmästä  on puhe, esim. käännökset / kaunokirjallisuus / kirjailijat / Pirkanmaa
tai
toinen tapaus esim. Melinda-id: 012597797 Satakunnan bibliografia. 2, Satakuntaa ja satakuntalaisia koskeva kirjallisuus vuodesta 1971 vuoteen 1985, ja tässä on kyse pitkästä traditiosta kuvailla aineisto 

Usein voi olla myös kyse molemmista tapauksista?
https://agricolaverkko.fi/review/keski-suomen-kootut/

**Comment by AuHo22** [comment]
YSO: paikallisbibliografiat KÄ aluebibliografiat
YKL: 01.3 Paikallisbibliografiat
Tähän yleiset paikallis- ja aluebibliografiat bibliografian ja sen kohteiden materiaalityypistä riippumatta Tiettyä paikkakuntaa tai aluetta koskevien julkaisujen luettelot ja valikoimaluettelot
https://www.makupalat.fi/fi/k/all/hae/?search_api_views_fulltext=aluebibliografiat
tai
https://fi.wikisource.org/wiki/Luokka:Paikallishistorian_bibliografiat

**Comment by mirmaid** [comment]
^^ Ei varmaan tarkoitus ollut rajata noin tiukasti, julkaistu-sanan tilalle voi vaihtaa jonkun paremman, mutta "luodun" on aika kömpelö. Jos aluebibliografiat-termiä saa käyttää molemmissa merkityksissä, niin sitten ei toki tarvita mitään huomautusta.

**Comment by mirmaid** [comment]
Jos ehdotetut jaottelut eivät saa kannatusta (ja sekin on ihan ymmärrettävää), ehdottaisin melkein, että poistetaan _erikoisbibliografiatkin_, tai ainakin annetaan sille jokin perusteltu rajaus. Ilman määritelmää mikä tahansa bibliografia voidaan käsittää jollain tavalla "erikoiseksi". Vähän myös epäilen, että valinta termien bibliografiat ja erikoisbibliografiat välillä on kuvailussa enemmän tai vähemmän satunnaista.

Esim. tämä https://melinda.kansalliskirjasto.fi/byid/017976091 on epäilemättä erikoisbibliografia (tietty käyttötarkoitus), mutta en silti tiedä tuoko kuvailuun mitään lisäarvoa se, että ei ole käytetty termiä bibliografiat (ja löytyisikö kirja jopa paremmin sillä). Jos joku haluaa tutkia yleisesti erikoisbibliografioita aiheesta kuin aiheesta niin sitten ehkä, mutta haluaako tosiaan...

**Comment by AuHo22** [comment]
Informaatiotutkimuksen sivut (Forsmanin määritelmä?) yllä:
_"Erikoisbibliografiat rajoittuvat tiettyyn muodolliseen kategoriaan, esim.-- Erikoisbibliografiat luetteloivat tietyllä aihealueella julkaistua kirjallisuutta._"
->LT erikoisbibliografiat ST aihebibliografiat

Samassa tekstissä ylempänä:
_Erikoisbibliografiat ovat luetteloita, jotka luetteloivat julkaisuja tiettyjen formaalisten perusteiden mukaan, esim. akateemisten julkaisujen bibliografiat, aikakauslehtiluettelot, aikakauslehti- tai sanomalehti-indeksit._
-> erikoisbibliografiat (tietystä aiheesta) KÄYTÄ aihebibliografiat
 
UDC 016 Erikoisbibliografiat
-ohjaustermein:
Bibliografiat, erikoisalojen 
Special subject bibliographies
Ämnesbibliografier. Fackbibliografier

**Comment by mirmaid** [comment]
Eli ns. pelkillä bibliografioilla ei ole mitään "formaalisia perusteita", vai pelkkiä bibliografioita ei ole olemassakaan? Eikö tällä perusteella myös henkilö- ja aluebibliografiat ole erikoisbibliografioiden alakäsitteitä?

**Comment by AuHo22** [comment]
Niitähän on yritetty ajaa aihebibliografioiksi, eli sitten kai olisivat jopa aihebibliografioidenkin alakäsitteitä?

**Comment by mariaforsen** [comment]
Yllä mainituista löytyy SAOsta vain: 
-bibliografier
-ST ämnesbibliografier
-ST nationalbibliografier

**Comment by mirmaid** [comment]
Henkilöbibliografiat: lisätään Jaakon määritelmä, ei muutosta termiin.

Aluebibliografiat: tietyllä alueella luotu ja/tai tiettyä aluetta käsittele aineisto.

Aihebibliografiat: Tiettyä aihetta (henkilöä, tieteenalaa tms.) käsittelevän kirjallisuuden luettelo.

**Comment by mirmaid** [comment]
Erikoisbibliografiat: seuraava kokous. Tarvitaan selkeä, muut vaihtoehdot poissulkeva määritelmä ja termimuoto. Muuten ehdotetaan poistettavaksi.

**Comment by mirmaid** [comment]
Muilla kuin erikoisbibliografiat-käsitteellä on nyt siis määritelmä. Ratkaistaan siis:
a) poistetaanko erikoisbibliografiat
b) saadaanko sille määritelmä
c) kuka pystyy laatimaan määritelmän, joka olisi selkeä suhteessa muihin bibliografiat-käsitteisiin

**Comment by AuHo22** [comment]
Kaikki eivät tainneet olla tyytyväisiä poistoonkaan, eli voisiko seuraava sitten olla rajaava määritelmä? (Ilonan linkistä)
->
_Erikoisbibliografiat ovat luetteloita, jotka luetteloivat julkaisuja tiettyjen formaalisten perusteiden  mukaan, esim. akateemisten julkaisujen bibliografiat, aikakauslehtiluettelot, aikakauslehti- tai sanomalehti-indeksit._  Eikö tämä olisi melko yhteneväinen Jaakon määritelmän kanssa, joista muokattavissa -> _Tietyntyyppisen kirjallisuuden (esim. artikkelit, vain fragmentaarisina säilyneet tekstit, pergamentille painetut kirjat, pienpainatteet, pistekirjat, sensuroitu kirjallisuus, väitöskirjat) luettelo_.
Ja lisäksi huomautukseen -> Tiettyä aihealuetta käsittelevistä bibliografioista KÄYTÄ termiä aihebibliografiat.

**Comment by mirmaid** [comment]
Erikoisbibliografiat (aihebibliografiat) KÄ aihebibliografiat

Määritelmä
Tietyntyyppisen kirjallisuuden (esim. kausijulkaisut, vain fragmentaarisina säilyneet tekstit, pergamentille painetut kirjat, pienpainatteet, pistekirjat, sensuroitu kirjallisuus, väitöskirjat) luettelo.
