### ISSUE TITLE
kinyarwandan kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7824]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kinyarwandan kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781496097316 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [kinyarwandan kieli](http://finto.fi/yse/fi/page/Y507824)

**Comment by mariaforsen** [comment]
Sv. rwanda (språk) ET kinyarwanda (språk), runyarwanda (språk), rwanda-rundi (språk)

**Comment by mirmaid** [comment]
ruandan kieli KT kinyarwandan kieli
