### ISSUE TITLE
uutisvälitys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7825]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uutisvälitys](http://www.yso.fi/onto/ysa/Y99948) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "uutisten välitys" 

#### Perustelut ehdotukselle   

Kyseinen ilmaus on käytössä ja tarkoittaa samaan, joten olisi hyvä saada viittausmuodoksi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
