### ISSUE TITLE
koetin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7826]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koetin 

#### Vaihtoehtoiset termit ja ilmaisut   

sondi 

#### Vastaava käsite muussa sanastossa   

Kielikello : https://www.kielikello.fi/-/koettaa-ja-koittaa 

#### Tarkoitusta täsmentävä selite   

Kielikello: "jonkin tunnusteluun käytettävä puikko, sondi". 

#### Perustelut ehdotukselle   

Hammaslääkärin ja lääkärin työväline. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Museokokoelman luetteloinnissa 

**Ehdottajan organisaatio:** Museovirasto **Termiehdotus Fintossa:** [koetin](http://finto.fi/yse/fi/page/Y507826)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: lääk. putkimaisten elinten tms. tunnusteluun käytettävä puikko, sondi. 

Lääketieteen termit: koetin: 1. sondi | pitkänomainen usein käyrä jäykkä instrumentti, jota käytetään mm. tiehytaukkojen ja fistelien tutkimiseen; 2. ks. geenikoetin: geenitunnistin | esim. radioaktiivisesti merkitty, emäsjärjestykseltään tunnettu RNA- tai DNA-jakso, jonka avulla nukleiinihappoja voidaan tunnistaa →hybridisaation (2) perusteella (koetin pariutuu vastinjaksonsa kanssa, minkä jälkeen hybridit tunnistetaan koettimen radioaktiivisen leiman avulla)

_Koetin on molekyylibiologiassa yksijuosteinen DNA- tai RNA-jakso, jolla on komplementaarinen emäsjärjestys etsityn geenin tai DNA-jakson kanssa ja voi siten pariutua tämän DNA-jakson kanssa emäsparisääntöä noudattaen._ https://fi.wikipedia.org/wiki/Koetin

http://tieteentermipankki.fi/wiki/Mikrobiologia:koetin

**Comment by mirmaid** [comment]
Ehkä selkeämpää ottaa _sondit_? Molempia käytetään myös muussa kuin lääketieteen yhteydessä.

**Comment by mariaforsen** [comment]
Sondit on jo mutta voisiko laajentaa muilla ryhmillä kuin 11? Koetin=sond ruotsiksi.

**Comment by mirmaid** [comment]
^ Tosiaan. Ja KT koettimet.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa sondit, ohjaustermiksi koettimet. Ryhmäksi ainakin 48.

**Comment by mariaforsen** [comment]
Todettiin siis että sondit on jo YSOssa mutta lisätään ohjaustermi ja ryhmiä.
