### ISSUE TITLE
sähköpiano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7827]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sähköpiano 

#### Ehdotettu termi ruotsiksi   

elpiano 

#### Ehdotettu termi englanniksi   

electronic piano 

#### Vaihtoehtoiset termit ja ilmaisut   

electric piano [eng] 
elektrisk piano [swe] 
e-piano [fin] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[piano](http://www.yso.fi/onto/yso/p11690) 
[sähkösoittimet](http://www.yso.fi/onto/yso/p618) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85042367> 
Wikidata : https://www.wikidata.org/wiki/Q1136507 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarvetta kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.finna.fi/Record/muistaja_nurmijarvi.M011-68227 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [sähköpiano](http://finto.fi/yse/fi/page/Y507827)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus. Yläkäsitteeksi piano ja sähkösoittimet.

**Comment by tpalonen** [comment]
Viittaako käsite akustisen pianon soundia simuloivaan sähköiseen pianoon (electronic piano) vai Wurlitzer electric piano / Rhodes-tyyppiseen kosketinsoittimeen (electric piano), jonka soundi sijoittuu enemmän sähköurun ja akustisen pianon välimaastoon? Teknisesti nämä on toteutettu eri tavalla. Vaikuttaa käsitteen englannin vastineeseen ja linkitykseen. Sitten on vielä digitaalinen piano, joka niin ikään pyrkii simuloimaan akustisen pianon soundia, mutta on eri teknologiaa kuin edellä mainitut.

https://en.wikipedia.org/wiki/Electric_piano
https://en.wikipedia.org/wiki/Electronic_piano
https://en.wikipedia.org/wiki/Digital_piano

**Comment by tpalonen** [comment]
Muusa-kokouksessa todettiin, että käsite viittaa Wurlitzer/Rhodes-tyyppisiin soittimiin (https://en.wikipedia.org/wiki/Electric_piano). Vastineet ja linkkaus sen mukaan.

**Comment by tpalonen** [comment]
Muusa-väen kanssa todettiin vielä, että piano ei ole sopiva yläkäsite, koska kuten edellä mainitaan käsite viittaa Wurlitzer/Rhodes-tyyppisiin electric piano -soittimiin, jotka eivät varsinaisesti ole pianoja (vrt. sähköurut). Käsitteeltä poistettiin yläkäsite piano ja lisättiin yläkäsite kosketinsoittimet.
