### ISSUE TITLE
dynaaminen kompressointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7829]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dynaaminen kompressointi 

#### Ehdotettu termi englanniksi   

dynamic range compression 

#### Vaihtoehtoiset termit ja ilmaisut   

kompressointi (äänenkäsittely) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[äänenkäsittely](http://www.yso.fi/onto/yso/p2910) 

#### Assosiatiiviset (RT)   

[masterointi](http://www.yso.fi/onto/yso/p29960) 
[äänitekniikka](http://www.yso.fi/onto/yso/p1141) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jaakko Vastapuu: Ensimmäiset 30 millisekuntia : alukkeet ja niiden muokkaus nykypäivän populaarimusiikin miksauksessa. 

#### Perustelut ehdotukselle   

Kompressio-käsitettä käytetty muutamaan otteeseen kyseisessä merkityksessä.
Ks. https://github.com/Finto-ehdotus/YSE/issues/7186 

#### Tarkoitusta täsmentävä selite   

Merkitys liittyy audiosignaalin käsittelyyn, tyypillisesti osana musiikin miksaus-/masterointiprosessia (ks. https://en.wikipedia.org/wiki/Dynamic_range_compression). Siinä audiosignaalin dynamiikkaa tasapäistetään eli hiljaisia "signaalikuoppia" ja voimakkaita "signaalihuippuja" tuodaan samalle volyymitasolle. Tästä vastaavaa laitetta kutsutaan kompressoriksi. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[45 Tietoliikennetekniikka. Teletekniikka. Viestintätekniikka. Äänitekniikka](http://www.yso.fi/onto/yso/p26542) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [dynaaminen kompressointi](http://finto.fi/yse/fi/page/Y507829)

**Comment by mariaforsen** [comment]
Sv. dynamisk kompression (ljudbehandling) ET DRC, dynamisk områdeskomprimering, kompression (ljudbehandling), dynamisk komprimering (ljudbehandling)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.

**Comment by tpalonen** [comment]
Pakkaus-issuessa (https://github.com/Finto-ehdotus/YSE/issues/7186) todettu, että kompressio-käsitettä on käytetty Melinda-kuvailussa myös merkityksessä dynaaminen kompressointi. Ks. oma kommenttini issuessa Feb 3, 2020.

**Comment by tpalonen** [comment]
Ehdotus määritelmäksi:
_Äänisignaalin äänenvoimakkuuden vaihtelun tasaaminen tähän tehtävään tarkoitetun kompressorin avulla_

Lisäksi mielestäni käyttöhuomautus olisi tässä paikallaan:
_Audio- tai muun datan pakkaamisesta pienempään tiedostokokoon käytetään käsitettä tiedonpakkaus._

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa määritelmäehdotusta hieman muokattuna:
_Äänisignaalin voimakkuuden vaihtelun tasaaminen tähän tehtävään tarkoitetun laitteen tai ohjelmiston avulla._

Käyttöhuomautus OK.
