### ISSUE TITLE
kasvivirukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7830]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kasvivirukset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Interactions of potyviral protein HCPro with host methionine cycle enzymes and scaffolding protein VARICOSE in potato virus A infection 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kasvivirukset](http://finto.fi/yse/fi/page/Y507830)

**Comment by ilona-x** [comment]
FinMeSHissä: **kasvien virukset** KT kasvivirukset http://www.yso.fi/onto/mesh/D010942

**Comment by mirmaid** [comment]
LCSH: Plant viruses

**Comment by mariaforsen** [comment]
Sv. växtvirus

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa kasvivirukset, ohjaustermiksi kasvien virukset.
