### ISSUE TITLE
ilmaraot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7831]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmaraot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Phytohormone-related crosstalk in pathogen and stomatal responses in Arabidopsis thaliana 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ilmaraot](http://finto.fi/yse/fi/page/Y507831)

**Comment by ilona-x** [comment]
fi        ilmarako
sv       klyvöppning
en      stoma

määritelmä
yhteyttämiseen ja hengittämiseen tarvittava pieni aukko putkilokasvien vihreissä osissa tai aitosammalten itiöpesäkkeen tyviosan päällysketossa
Lähde: http://tieteentermipankki.fi/wiki/Kasvitiede:ilmarako

Tarvitsee tarkenteen, sillä esim. kielitoimiston sanakirjan mukaan:
ilmarako - Seinälevyjen välinen ilmarako. 

Myös Tepasta löytyy muussa kuin kasvitieteen merkityksessä: http://www.tsk.fi/tepa/fi/haku/ilmarako

**Comment by mirmaid** [comment]
ilmaraot (kasvinosat)?

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa ilmaraot (kasvinosat).

**Comment by mariaforsen** [comment]
Sv. klyvöppningar ET stomata
