### ISSUE TITLE
Runsaan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7832]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Runsaan kartano 

#### Ehdotettu termi englanniksi   

Runsas manor 

#### Vaihtoehtoiset termit ja ilmaisut   

Runsas (kartano) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Runsas : kartano Ylöjärven Lempiäniemessä 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Runsaan kartano](http://finto.fi/yse/fi/page/Y507832)

**Comment by mariaforsen** [comment]
Sv. Runsaan kartano
