### ISSUE TITLE
tulistimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7833]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tulistimet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Computational Fluid Dynamics Modeling and Mathematical Optimization of Recovery Boilers 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tulistimet](http://finto.fi/yse/fi/page/Y507833)

**Comment by mirmaid** [comment]
Myös tulipesät

**Comment by mirmaid** [comment]
_Tulistin on höyrykattilakomponentti, jolla höyrystimessä höyrystetty vesihöyry lämmitetään energialähteen lämpöenergialla höyrystymislämpötilaa korkeampaan lämpötilaan. Tulistinta käytetään voimalaitoksien ja höyryveturien höyrykattiloissa._ https://fi.wikipedia.org/wiki/Tulistin

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
tulistin: tekn. höyrykattilan osa, jossa höyry tulistuu.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Tulipes%C3%A4 - eiköhän näille kuitenkin riitä yksi käsite?

**Comment by mariaforsen** [comment]
Sv. överhettare

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
