### ISSUE TITLE
latin pop

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7834]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

latin pop 

#### Ehdotettu termi ruotsiksi   

latin pop 

#### Ehdotettu termi englanniksi   

latin pop 

#### Vastaava käsite muussa sanastossa   

LCSH : latin pop (music) 
Wikipedia (eng) : latin pop 

#### Tarkoitusta täsmentävä selite   

Popmusiikkia, jossa on piirteitä ja vaikutteita Latinalaisesta Amerikasta sekä usein ainakin osittain espanjankieliset sanoitukset. 

#### Perustelut ehdotukselle   

Lisäys ainakin SLM-sanastoon. Latinalaisamerikkalaisesta popista on tullut oma ilmiönsä suositussa popmuusiikissa. Pelkän "popmusiikki"-käsitteen käyttö ei tunnu riittävältä, varsinkin kun latin poppia edustavissa kappaleissa on usein tyylillisiä eroja perinteiseen popmusiikkiin. Lisäksi termi sopisi mainiosti "latin rock" -käsitteen rinnalle, ja myös esimerkiksi Grammy-gaalassa on oma osuutensa "latin pop"-kategorialle. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Luis Fonsi - Vida, lisäksi muita artisteja: Alejandro Sanz, Shakira, Ricky Martin, Demi Lovato, Selena Gomez, Thalía, Enrique Iglesias, Jennifer Lopez, Pitbull jne. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [latin pop](http://finto.fi/yse/fi/page/Y507834)

**Comment by mariaforsen** [comment]
Sv. latinopop

**Comment by LeKorsu** [comment]
Ohjaustermikiksi latinopop? Google-haku rajattuna site:fi tuottaa 5030 osumaa latinopopilla ja 1810 osumaa "latin popilla"

**Comment by tpalonen** [comment]
Kirjoittaisin mieluummin yhteen.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa yhteenkirjoitettuna.
LT popmusiikki
Muusa tutkii vierasperäisten sanaliittojen ja yhdyssanojen kokonaisuutta laajemmin ja laatii aiheesta kooste-ehdotuksen.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by tpalonen** [comment]
Musiikkitoimittajille tekemässäni kyselyssä selkeä enemmistö kannatti muotoa _latin pop_ eli erikseen kirjoitettuna. Ks. https://github.com/Finto-ehdotus/YSE/issues/8126

**Comment by LeKorsu** [comment]
Minun musiikkikollegani puolestaan liputtivat o:llisen latinopopin puolesta, mutta onko "latino" poliittisesti korrekti nykypäivänä?

**Comment by tpalonen** [comment]
Ylellä (yle.fi) näyttäisi näköjään olevan suosiossa latinopop-muoto, tosin enimmäkseen Svenska Ylen puolella. Jos taas hakee hs.fi:stä niin "latinopop" tuottaa 5 hakutulosta, mutta "latin pop" ei yhtään järkevää tulosta. Samoin rumba.fi:ssä "latinopop"-muoto näyttäisi yleisemmältä kuin muut.

"Latin pop"-muoto kuitenkin näyttää olevan suositumpi kuin "latinpop"-muoto, kuten edellä mainittu kyselynikin osoitti.

**Comment by YSO-kokous** [comment]
Odotetaan vielä Muusan kantaa uuden keskustelun valossa.

**Comment by MUUSA-kokous** [comment]
Muusa pitäytyy aiemmassa kannassaan.

**Comment by YSO-kokous** [comment]
Toteutetaan Muusan kannan mukaan.
