### ISSUE TITLE
hardcore punk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7836]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hardcore punk](http://www.yso.fi/onto/ysa/Y504977) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan äänitteiden ja nuottien kuvailussa 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by tpalonen** [comment]
Ohjaustermiksi hcpunk/hc punk/hc-punk? YSOssa ohjausterminä hc punk.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT punk rock
RT hc punk
