### ISSUE TITLE
mento

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7837]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mento](http://www.yso.fi/onto/ysa/Y214566) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan äänitteiden ja nuottien kuvailussa. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT latinalaisamerikkalainen populaarimusiikki
RT calypso
