### ISSUE TITLE
henkilökortit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#784]
#### Ehdotettu termi suomeksi

henkilökortit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/ysa/ryhma_69)

**Luontipäivämäärä:** 06.05.2002

**Muokkauspäivämäärä:** 6.5.2002, 16.12.2008

**Voyager-id:** 119058

**Termiehdotus Fintossa:** [henkilökortit](http://finto.fi/yse/fi/page/Y319058)

**Comment by mariaforsen** [comment]
Sanastossa on jo henkilötodistukset.

**Comment by YSA-kokous** [comment]
KÄ henkilötodistukset

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9224
