### ISSUE TITLE
Augustini Ferberi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7840]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Augustini Ferberi 

#### Ehdotettu termi ruotsiksi   

Augustini Ferberi 

#### Vaihtoehtoiset termit ja ilmaisut   

Augustinum Ferberum 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yhteisöt](http://www.yso.fi/onto/yso/p3835) 

#### Tarkoitusta täsmentävä selite   

Kustantaja Saksassa 1600-luvulla 

#### Perustelut ehdotukselle   

Tarvitaan ruotsin ajan aineiston kuvailussa, koska on kustantajanimenä muutamassa teoksessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finna.fi/Record/fikka.1892198 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Augustini Ferberi](http://finto.fi/yse/fi/page/Y507840)

**Comment by jtuohini** [comment]
Ei kai tämä kuulu 650-kentässä käytettävään sanastoon ensinkään, vaan 110/610/710-kentän asioihin? YSOssa on toki jo nytkin joukko yhteisöjä, vaikka pääasiassa ovatkin auktorisoitu _Suomalaiset yhteisönimet_ -sanastoon.
