### ISSUE TITLE
maanmittaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7844]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maanmittaus](http://www.yso.fi/onto/ysa/Y97177) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

onko maanmittaustekniikka sama kuin maanmittaus? jos on, voiko lisätä KT:n? 

#### Perustelut ehdotukselle   

toimijoiden kuvailussa on usein käytetty toimialana termmiä maanmittaustekniikka. Ks. esim. https://www.metropolia.fi/haku/koulutustarjonta-nuoret-tekniikka-ja-liikenne/maanmittaustekniikka/ 

#### Ehdottajan organisaatio   

KK Toimijakuvailupalvelu

**Comment by mariaforsen** [comment]
Sv. ET lantmäteriteknik

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
