### ISSUE TITLE
sarjakuvataide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7845]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarjakuvataide 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taiteet](http://www.yso.fi/onto/yso/p20653) 
[kuvataide](http://www.yso.fi/onto/yso/p2739) 

#### Assosiatiiviset (RT)   

[sarjakuvat](http://www.yso.fi/onto/yso/p1148) 

#### Perustelut ehdotukselle   

Tarvitaan toimijoiden kuvailussa. Sarjakuvataiteesta ks. https://sarjakuvakeskus.fi/blogi/235-sarjakuva-yhdeksas-taide. Olisiko vastaava tapaus oopperat vrs. oopperataide. Sarjakuvat näkisin siis muototerminä, sarjakuvataide olisi laajempi käsitteenä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://katjalouhio.com/comic.html 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/yso/p26581) 
[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 

**Ehdottajan organisaatio:** KK Toimijakuvailupalvelu **Termiehdotus Fintossa:** [sarjakuvataide](http://finto.fi/yse/fi/page/Y507845)

**Comment by mirmaid** [comment]
5 viitettä Melindassa (4 artikkeliviitteitä). Googlella runsaasti.

**Comment by mariaforsen** [comment]
Sv. seriekonst ET tecknad seriekonst

**Comment by mirmaid** [comment]
Sanastossa on _sarjakuvataiteilijat_.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
