### ISSUE TITLE
metsäojitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7846]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsäojitus 

#### Ehdotettu termi englanniksi   

forest drainage 

#### Ehdotettu termi ruotsiksi   

skogsdikning 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ojitus](http://www.yso.fi/onto/yso/p7367) 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p3388> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Perustelut ehdotukselle   

Melindassa 366 tietueessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [metsäojitus](http://finto.fi/yse/fi/page/Y507846)

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mariaforsen** [comment]
Sv. skogsdikning ET skogsdränering
