### ISSUE TITLE
kunnostusojitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7847]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kunnostusojitus 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p2425> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Tarkoitusta täsmentävä selite   

Metsäojitus, jolla kunnostetaan alueen vesitaloutta ojanperkauksen, täydennysojituksen tai uusintaojituksen avulla. Lähde: Suomalais-venäläinen metsäsanakirja, 2008.
Yläkäsite: metsäojitus 

#### Perustelut ehdotukselle   

Melindassa asiasanana 98 tietueessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kunnostusojitus](http://finto.fi/yse/fi/page/Y507847)

**Comment by mariaforsen** [comment]
Sv. iståndsättningsdikning

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
