### ISSUE TITLE
keinoalkuiset lisääntymismenetelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7848]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keinoalkuiset lisääntymismenetelmät](http://www.yso.fi/onto/ysa/Y113632) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan tai vaihdetaan päätermiä? 

#### Perustelut ehdotukselle   

Hyvin vähän googlessa (lähinnä YSA/YSO-asiasanana). Käännökset ongelmalliset. Sanastossa myös hedelmöityshoidot, keinohedelmöitys, keinosiemennys jne. 

#### Ehdottajan organisaatio   

YSO-kokous

**Comment by mirmaid** [comment]
Tämän voisi mielestäni poistaa. Päätermi voisi olla monikossa (https://www.finlex.fi/fi/laki/alkup/2006/20061237), toisaalta yksikkö enemmän käytetty Googlella.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta keinoalkuiset lisääntymismenetelmät. Lisätään tämä ohjaustermiksi käsitteelle hedelmöityshoito. Uudelleenohjaus tähän.
Lisätään hedelmöityshoito-käsitteelle ohjaustermi hedelmöityshoidot.

**Comment by mariaforsen** [comment]
Sv. assisterad befruktning http://www.tsk.fi/tepa/fi/haku/hedelm%C3%B6ityshoito https://www.finlex.fi/sv/laki/alkup/2006/20061237 https://sv.wikipedia.org/wiki/Assisterad_befruktning SAO ET assisterad reproduktion, konstgjord befruktning, fertilitetsbehandling
