### ISSUE TITLE
elintarviketekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7849]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elintarviketekniikka](http://www.yso.fi/onto/ysa/Y142487) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT:n lisäys: elintarviketeknologia 

#### Perustelut ehdotukselle   

elintarviketeknologia-termiä käytetään paljon toimijoiden kuvailussa 

#### Ehdottajan organisaatio   

KK Toimijakuvailupalvelu

**Comment by mariaforsen** [comment]
Sv. ET livsmedelsteknologi

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
