### ISSUE TITLE
lomittuminen (kvanttimekaniikka) (tms.)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7850]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lomittuminen (kvanttimekaniikka) (tms.) 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Lomittuminen 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Holographic aspects of quantum information theory and condensed matter theory 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lomittuminen (kvanttimekaniikka) (tms.)](http://finto.fi/yse/fi/page/Y507850)

**Comment by mirmaid** [comment]
LCSH: Quantum entanglement

**Comment by mariaforsen** [comment]
Sv. kvantsammanflätning https://sv.wikipedia.org/wiki/Kvantsammanfl%C3%A4tning

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa lomittuminen (kvanttimekaniikka).
