### ISSUE TITLE
holografinen periaate

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7851]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

holografinen periaate 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Holographic aspects of quantum information theory and condensed matter theory 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [holografinen periaate](http://finto.fi/yse/fi/page/Y507851)

**Comment by mariaforsen** [comment]
Sv. holografiska principen ET holografisk princip

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
