### ISSUE TITLE
kvantti-informaatio / kvantti-informaatioteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7852]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kvantti-informaatio / kvantti-informaatioteoria 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Holographic aspects of quantum information theory and condensed matter theory 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kvantti-informaatio / kvantti-informaatioteoria](http://finto.fi/yse/fi/page/Y507852)

**Comment by mariaforsen** [comment]
Sv. kvantinformation ET kvantinformationsteori

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa kvantti-informaatio.
