### ISSUE TITLE
kvarkki-gluoniplasma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7853]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kvarkki-gluoniplasma 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Kvarkki-gluoniplasma 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Quasiparticle properties of nonequilibrium gluon plasma 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kvarkki-gluoniplasma](http://finto.fi/yse/fi/page/Y507853)

**Comment by mariaforsen** [comment]
Sv. kvark-gluonplasma ET kvarkgluonplasma

**Comment by ilona-x** [comment]
LCSH: Quark-gluon plasma http://id.loc.gov/authorities/subjects/sh90002092

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
