### ISSUE TITLE
puunkäyttö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7854]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puunkäyttö 

#### Ehdotettu termi englanniksi   

wood use 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käyttö käyttökohteen mukaan](http://www.yso.fi/onto/yso/p191) 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p5960> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Perustelut ehdotukselle   

Melindassa asiasanana 443 viitteessä, googlaamalla löytyy runsaasti aineistoa, esim. 25.4.2019 - Sahateollisuuden puunkäyttö puolestaan lisääntyi kolmella prosentilla 27 miljoonaan kuutiometriin.
https://stat.luke.fi/suomen-mets%C3%A4tilastot-2019-2019_fi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [puunkäyttö](http://finto.fi/yse/fi/page/Y507854)

**Comment by mariaforsen** [comment]
Sv. virkesförbrukning ET träförbrukning, virkesanvändning, virkesbruk

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
