### ISSUE TITLE
tietoverkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7855]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietoverkot](http://www.yso.fi/onto/ysa/Y111682) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT:n lisäys: tietoverkkotekniikka 

#### Perustelut ehdotukselle   

termiä tietoverkkotekniikka on käytetty paljon henkilöiden kuvailussa. voinee ajatella, että tietoverkot on vastaava käsite? 

#### Ehdottajan organisaatio   

KK Toimijakuvailupalvelu

**Comment by ilona-x** [comment]
ehdotettu myös erillisenä terminä https://github.com/Finto-ehdotus/YSE/issues/7935

**Comment by YSO-kokous** [comment]
Hyväksytään: 
tietoverkkotekniikka KÄYTÄ tietoverkot
