### ISSUE TITLE
puhallinmusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7857]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puhallinmusiikki 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soitinmusiikki](http://www.yso.fi/onto/yso/p1514) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

tarvitaan toimijoiden kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http: 

**Ehdottajan organisaatio:** KK Toimijakuvailupalvelu **Termiehdotus Fintossa:** [puhallinmusiikki](http://finto.fi/yse/fi/page/Y507857)

**Comment by jtuohini** [comment]
LCSH-vastine **[Wind instrument music](http://id.loc.gov/authorities/subjects/sh85146860)**.

**Comment by mariaforsen** [comment]
Sv. blåsmusik

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT soitinmusiikki

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
