### ISSUE TITLE
Saari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7858]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Saari](http://www.yso.fi/onto/ysa/Y107970) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termi muotoon "Saari (Parikkala)". 

#### Perustelut ehdotukselle   

Saari yksistään harhaanjohtava, varsinkin kun muilla vastaavilla paikoilla on sulkutarkenne. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
YSO-paikkojen kehityslinjausten mukaan: "Kunnille, jotka ovat kuntaliitoksen myötä muuttuneet kyliksi toisen kunnan alueella, luodaan uusi paikkakäsite. Näiden välille tehdään linkitys, jonka tyyppi on edeltäjä-seuraaja." https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSO-paikat
YSA:n aikana ei ole toimittu tällä tavoin, joten sanastossa on tällä hetkellä paljon entisiä kuntia, jotka ovat nykyään kyliä/taajamia toisen kunnan alueella. 

Tässä tapauksessa pitäisi siis luoda uusi käsite: Saari (Parikkala) ja poistaa Saari-käsitteeltä virheellinen yläkäsite Parikkala.

**Comment by ilona-x** [comment]
Huom. PNRssä Parikkalassa vain Saari tyyppitieto: rautatieliikennepaikka, johon myös YSO-paikkojen Saari tällä hetkellä linkkaa. Onkohan sittenkään tarpeen tehdä Saari (Parikkala)? Sen sijaan löytyy kyllä **Saarenkylä (Parikkala)** http://paikkatiedot.fi/so/1000772/10686989 https://kylat.ekarjala.fi/parikkalankylat/saarenkyla/

Saaren kunnan keskustaajama (nykyään kylä Parikkalassa) on ollut nimeltään Akonpohja. https://fi.wikipedia.org/wiki/Akonpohja

**Comment by YSO-kokous** [comment]
PÄÄTÖS: Lisätään linjauksiin: Entisille Suomen kunnille lisätään sulkutarkenne (kunta) silloin, kun on se on mahdollista sekoittaa johonkin muuhun paikkaan, esim. samannimiseen kylään.

Tiedoksi @MikkoAleksanteri
