### ISSUE TITLE
j-pussi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7859]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

j-pussi 

#### Ehdotettu termi englanniksi   

j-pouch 

#### Perustelut ehdotukselle   

http://finnilco.fi/tietoa/j-pussi/
 IPAA-leikkauksessa paksu- ja peräsuoli poistetaan, mutta lantiopohjan lihakset, peräaukko ja sen sulkijalihakset säilytetään. Toimenpiteessä ohutsuolen loppuosasta muodostetaan yleensä J:n muotoinen säiliö, ns. J-pussi, joka yhdistetään peräaukkoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://finnilco.fi/wp-content/uploads/2017/06/Avanneopas-nettiversio.pdf 

**Termiehdotus Fintossa:** [j-pussi](http://finto.fi/yse/fi/page/Y507859)

**Comment by ilona-x** [comment]
FinMeSH: säästävä proktokolektomia KT J-pouch http://www.yso.fi/onto/mesh/D016737
LCSH: Restorative proctocolectomy KT J-pouch http://id.loc.gov/authorities/subjects/sh92005596

**Comment by mariaforsen** [comment]
Sv. ileoanal reservoar  ET j-påse, IPAA-kirurgi
https://mesh.kib.ki.se/term/D016737/proctocolectomy-restorative

**Comment by mirmaid** [comment]
MeSHin termiä jonkin verran käytetympi on _IPAA-leikkaus_.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa IPAA-leikkaus, ohjaustermeiksi säästävä proktokolektomia ja j-pussi tai j-pussileikkaus tai vastaava.
