### ISSUE TITLE
anaali-inkontinenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7860]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

anaali-inkontinenssi 

#### Vaihtoehtoiset termit ja ilmaisut   

ulosteen pidätyskyvyttömyys 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://finnilco.fi/wp-content/uploads/2017/06/Avanneopas-nettiversio.pdf 

#### Perustelut ehdotukselle   

http://finnilco.fi/tietoa/anaali-inkontinenssi/
Anaali-inkontinenssilla tarkoitetaan juoksevan ja/tai kiinteän ulosteen tai suolikaasujen pidätyskyvyttömyyttä. 

**Termiehdotus Fintossa:** [anaali-inkontinenssi](http://finto.fi/yse/fi/page/Y507860)

**Comment by ilona-x** [comment]
FinMeSH: ulosteinkontinenssi KT anaali-inkontinenssi http://www.yso.fi/onto/mesh/D005242

**Comment by mariaforsen** [comment]
Sv. avföringsinkontinens ET analinkontinens, fekalinkontinens

**Comment by mirmaid** [comment]
MeSHin muoto & ohjaustermejä?

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa ulosteinkontinenssi, ohjaustermiksi anaali-inkontinenssi.
