### ISSUE TITLE
Gaussiset prosessit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7861]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Gaussiset prosessit 

#### Tarkoitusta täsmentävä selite   

Gaussiset prosessit (GP) ovat yksi keskeisimpiä epäparametrisiä bayesiläisiä menetelmiä. 
Gaussin prosessi on tilastotieteellinen malli, joka käsittää äärettömän jakauman sattumanvaraisia funktioita, jotka kuitenkin kaikki kulkevat
(sallitun kohinan rajoissa) annettujen datapisteiden läpi ja tottelevat samaa kovarianssifunktiota. 

#### Perustelut ehdotukselle   

matemaattisia malleja on otettu. Kuvailtavassa julkaisussa käytetty englanninkielistä termiä gaussian processes. Väittelijän tiivistelmässä 'gaussiset prosessit' 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Remes: Modelling non-stationary functions with Gaussian processes 

**Ehdottajan organisaatio:** kb **Termiehdotus Fintossa:** [Gaussiset prosessit](http://finto.fi/yse/fi/page/Y507861)

**Comment by ilona-x** [comment]
LCSH: Gaussian processes http://id.loc.gov/authorities/subjects/sh85053558 

LT stokastiset prosessit?

**Comment by mariaforsen** [comment]
Sv. Gaussiska processer

**Comment by mirmaid** [comment]
Kerran Melindassa, lisäksi kerran muodossa _Gaussin prosessit_. Googlella hyvin vähän viitteitä suomeksi (kumpikin muoto).

https://en.wikipedia.org/wiki/Gaussian_process

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa gaussiset prosessit, ohjaustermiksi Gaussin prosessit.

**Comment by mirmaid** [comment]
Myös https://helda.helsinki.fi/handle/10138/299415
