### ISSUE TITLE
Nenonpelto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7862]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Nenonpelto 

#### Ehdotettu termi ruotsiksi   

Nenonpelto 

#### Ehdotettu termi englanniksi   

Nenonpelto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://digi.kansalliskirjasto.fi/teos/binding/1928250?page=1 

#### Perustelut ehdotukselle   

Paikkakunta, jolla am. teoksessa on merkitty julkaisupaikaksi. 

**Ehdottajan organisaatio:** KK-Tutki-DH **Termiehdotus Fintossa:** [Nenonpelto](http://finto.fi/yse/fi/page/Y507862)

**Comment by ilona-x** [comment]
Nenonpelto (Pieksämäki) http://paikkatiedot.fi/so/1000772/10881098
