### ISSUE TITLE
perhe-etuudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7863]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

perhe-etuudet 

#### Ehdotettu termi ruotsiksi   

familjeförmåner 

#### Ehdotettu termi englanniksi   

family benefits 

#### Vaihtoehtoiset termit ja ilmaisut   

lapsiperhe-etuudet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sosiaalietuudet](http://www.yso.fi/onto/yso/p2302) 

#### Alakäsitteet (RT)   

[äitiysavustukset](http://www.yso.fi/onto/yso/p13412) 
[äitiysraha](http://www.yso.fi/onto/yso/p9410) 
[äitiyspakkaukset](http://www.yso.fi/onto/yso/p16938) 
[isyysvapaa](http://www.yso.fi/onto/yso/p7721) 
[isyysraha](http://www.yso.fi/onto/yso/p9408) 
[vanhempainvapaa](http://www.yso.fi/onto/yso/p8664) 
[vanhempainraha](http://www.yso.fi/onto/yso/p9409) 
[lapsilisät](http://www.yso.fi/onto/yso/p15426) 
[lastenhoidon tuet](http://www.yso.fi/onto/yso/p38157) 
[kotihoidon tuki](http://www.yso.fi/onto/yso/p2301) 
[yksityisen hoidon tuki](http://www.yso.fi/onto/yso/p27312) 
[joustava hoitoraha](http://www.yso.fi/onto/yso/p38282) 
[adoptiotuki](http://www.yso.fi/onto/yso/p38196) 
[elatustuki](http://www.yso.fi/onto/yso/p15745) 

#### Assosiatiiviset (RT)   

[sosiaaliturva](http://www.yso.fi/onto/yso/p3285) 
[sosiaalivakuutus](http://www.yso.fi/onto/yso/p3090) 
[äidit](http://www.yso.fi/onto/yso/p12279) 
[isät](http://www.yso.fi/onto/yso/p11063) 
[hoitovapaa](http://www.yso.fi/onto/yso/p9625) 
[lastenhoito](http://www.yso.fi/onto/yso/p5515) 
[elatus](http://www.yso.fi/onto/yso/p97) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Perustelut ehdotukselle   

Merkittävä kelan etuusryhmä 

#### Tarkoitusta täsmentävä selite   

Kelan terminologinen sanasto, 5. laitos   
Määritelmä:  
perheeseen syntyvästä tai adoptoitavasta lapsesta tai lapsen hoidosta aiheutuvien kulujen korvaamiseksi maksettava etuus
Käyttöesimerkki:
Perhe-etuuksia ovat esimerkiksi äitiysavustus, adoptiotuki, lapsilisä, elatustuki (1), lastenhoidon tuet ja vanhempainpäivärahat.; Oikeus moniin perhe-etuuksiin ratkaistaan asumiseen perustuvan sosiaaliturvalainsäädännön soveltamisesta annetun lain (1573/1993) mukaan. Esimerkiksi äitiysavustus on asumiseen perustuva etuus. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/299186 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [perhe-etuudet](http://finto.fi/yse/fi/page/Y507863)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
