### ISSUE TITLE
kuntoutusraha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7864]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuntoutusraha 

#### Ehdotettu termi ruotsiksi   

rehabiliteringspenning (eri asia kuin kuntoutustuki rehabiliteringsstöd) 

#### Ehdotettu termi englanniksi   

Rehabilitation allowance 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sosiaalietuudet](http://www.yso.fi/onto/yso/p2302) 

#### Assosiatiiviset (RT)   

[kuntoutus](http://www.yso.fi/onto/yso/p3320) 
[sopeutumisvalmennus](http://www.yso.fi/onto/yso/p5108) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Tarkoitusta täsmentävä selite   

Kelan terminologinen sanasto, 5. laitos   
Määritelmä:  
kuntoutujan toimeentulon turvaamiseksi maksettava päiväraha
Käyttöesimerkki:
Kuntoutusrahan maksaminen perustuu yleensä kuntoutuspäätökseen. Kuntoutusrahaa voidaan maksaa myös oppisopimuskoulutuksen ja sopeutumisvalmennuskurssin ajalta sekä 16–19-vuotiaan nuoren tehostetun kuntoutuksen ajalta.; Kuntoutusrahaa maksetaan omavastuuaikaa lukuun ottamatta kuntoutukseen osallistumisen ajalta jokaiselta arkipäivältä, jolloin työssä käyvä kuntoutuja on estynyt tekemästä työtään. Kuntoutujan katsotaan olevan estynyt työstään niinä päivinä, joina kuntoutus matkoineen edellyttää vähintään neljä tuntia kestävää työstä poissaoloa tai jona kuntoutus muutoin tosiasiallisesti estää kuntoutujaa tekemästä työtä ja saamasta toimeentuloa kyseiseltä päivältä. Kuntoutusraha maksetaan jälkikäteen kuntoutuksen toteuduttua.; Kuntoutusraha määräytyy pääsääntöisesti sairauspäivärahan tavoin. Ammatillisen kuntoutuksen ajalta kuntoutusrahan määrä päivältä on kuitenkin 75 prosenttia kuntoutujan työtulon kolmassadasosasta. Kuntoutusraha on kuntoutuksen aikana ensisijainen etuus sairauspäivärahaan.; Kuntoutusraha maksetaan kuntoutujan työnantajalle niiltä päiviltä, joilta työnantaja maksaa kuntoutujalle palkkaa, ja se maksetaan työnantajalle tämän maksamaa palkkaa vastaavalta osalta. 

#### Perustelut ehdotukselle   

Kelan etuus. On eri asia kuin kuntoutustuki (rehabiliteringspenning toinen käännös yso), joka on luonteeltaan 
määräaikainen työkyvyttömyyseläke 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi-fe2019082024784 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [kuntoutusraha](http://finto.fi/yse/fi/page/Y507864)

**Comment by mirmaid** [comment]
Eli erottavana tekijänä on kuntoutettavan työkykyisyys?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
