### ISSUE TITLE
vanhempainyhdistykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7866]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vanhempainyhdistykset 

#### Ehdotettu termi ruotsiksi   

föräldraföreningar 

#### Ehdotettu termi englanniksi   

parents' associations 

#### Ehdotettu yläkäsite YSOssa (LT)   

[järjestöt](http://www.yso.fi/onto/yso/p1393) 

#### Vastaava käsite muussa sanastossa   

JUPO : <http://www.yso.fi/onto/jupo/p1493> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 
[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Melinda x 5 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tack för musiken : föräldraföreningen Con Amores antologi om musikundervisningen i Ekenäs 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vanhempainyhdistykset](http://finto.fi/yse/fi/page/Y507866)

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
