### ISSUE TITLE
potkupyörät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7868]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

potkupyörät 

#### Ehdotettu termi ruotsiksi   

springcyklar 

#### Ehdotettu termi englanniksi   

balance bikes 

#### Tarkoitusta täsmentävä selite   

Potkupyörä (juoksupyörä) on polkupyörän edeltäjä. Siinä istutaan satulassa ohjaten ajoneuvoa, mutta liike-energia ei välity jaloista pyöriin polkimien kautta, vaan siten, että ajaja potkii jaloilla lisää vauhtia. Nykyään potkupyöriä valmistetaan lähinnä pikkulapsille pyöräilyn opetteluun. Potkupyörällä voi opetella tasapainon pitämistä. (Wikipedia: https://fi.wikipedia.org/wiki/Potkupy%C3%B6r%C3%A4) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ring ring : rohkeasti pyörän selkään (9789523413634) 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [potkupyörät](http://finto.fi/yse/fi/page/Y507868)

**Comment by mariaforsen** [comment]
Sekaantumisen riski, tarvitaanko tarkenne? Myös potkulautoja/kick-bikejä myydään potkupyörä-nimellä, esim. https://www.matkavaruste.fi/p46528-kickbike-fat-max-potkupyora-fi.html ja https://www.on24.fi/kauneustuotteet/polkupy%c3%b6r%c3%a4t/potkulaudat/134741?gclid=CjwKCAiA-vLyBRBWEiwAzOkGVPZSADK2H3NZ8jxDpi5tmSGaaJMpSuxPKZmuvgZoFxdhNKQot96q7xoCMocQAvD_BwE

**Comment by mirmaid** [comment]
_Lasten potkupyörät_?

**Comment by YSO-kokous** [comment]
Otetaan kaksi käsitettä:
lasten potkupyörät
kickbiket

Ja seuraavat ohjaustermit:
potkupyörät (kickbiket) KÄYTÄ kickbiket
potkupyörät (lapset) KÄYTÄ potkupyörät

**Comment by mariaforsen** [comment]
Sv. 
-springcyklar ET balanscyklar
-kickbikes
