### ISSUE TITLE
musiikkiterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7871]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkiterapia](http://www.yso.fi/onto/ysa/Y97569) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "lauluterapia" ja "hengitys- ja ääniterapia" 

#### Perustelut ehdotukselle   

https://digi.kansalliskirjasto.fi/sanomalehti/binding/1101370?page=16: "hengitys- ja ääniterapia eli lauluterapia" 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. ET sångterapi

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
RT musiikkiterapeutit

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus ja Muusan ehdottama RT.
