### ISSUE TITLE
MRSP

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7872]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

MRSP 

#### Perustelut ehdotukselle   

https://evidensia.fi/hoitovinkit/antibiooteille-vastustuskykyinen-bakteeri-koiralla-mika-mrsp/
Metisilliini resistentti Staphylococcus pseudintermedius eli MRSP on sama bakteeri, mutta se on muuntunut siten, että se on vastustuskykyinen b-laktaamiryhmän antibiootteja vastaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-3468-4 

**Termiehdotus Fintossa:** [MRSP](http://finto.fi/yse/fi/page/Y507872)

**Comment by mariaforsen** [comment]
Sv. MRSP

**Comment by mirmaid** [comment]
http://tieteentermipankki.fi/wiki/Mikrobiologia:MRSP

Sanastossa on _MRSA_.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
