### ISSUE TITLE
Muonion kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7873]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Muonion kirkko 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Muonion kirkko 200 vuotta 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Muonion kirkko](http://finto.fi/yse/fi/page/Y507873)

**Comment by mariaforsen** [comment]
Sv. Muonio kyrka
