### ISSUE TITLE
verkon viipalointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7874]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

verkon viipalointi 

#### Perustelut ehdotukselle   

https://www.dna.fi/yrityksille/blogi/-/blogs/5g-ssa-voit-viipaloida-yritysverkkosi-mita-se-kaytannossa-tarkoittaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Virtual network slice planning 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [verkon viipalointi](http://finto.fi/yse/fi/page/Y507874)

**Comment by mariaforsen** [comment]
Sv. nätverksskivning

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/5G_network_slicing

**Comment by YSO-kokous** [comment]
Hyväksytään käsite.
