### ISSUE TITLE
SLM / metafiktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7875]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM / metafiktio 

#### Ehdotettu termi englanniksi   

metafiction 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden slm-terminä 

#### Perustelut ehdotukselle   

Tällä hetkellä termi on Kauno-sanastossa, vaikka kuuluisi SLM-termiksi ; Kaunoon paremmin sopiva termi olisi vaikkapa metafiktiivisyys, kun kuvataan kerronnan keinoja silloin kun koko teosta ei välttämättä voisi kutsua metafiktion edustajaksi, vrt. 650 satiiri / 655 satiirit

Esim. https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:metafiktio 

#### Tarkoitusta täsmentävä selite   

Määritelmä 1) omaa sepitteellisyyttään korostava fiktio; 2) kaunokirjallinen teos, jossa kerronnallisin keinoin kiinnitetään lukijan huomio fiktiivisen esityksen laatimiseen, lukemiseen tai teoksen rakenteeseen (Tieteen termipankki) 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [SLM / metafiktio](http://finto.fi/yse/fi/page/Y507875)

**Comment by AuHo22** [comment]
Voisin ehdottaa vaihtoehtoisesti slm-termiksi postmodernit romaanit -termiä:
ks. esim. https://www.oulu.fi/sites/default/files/content/Romaanin%20historiaa%208.pdf
mm. Postmodernille ominaisia piirteitä: Keskeistä tekstuaalisuus, metafiktio ja intertekstuaalisuus.

**Comment by mirmaid** [comment]
Kauno-työryhmän käsittelyyn.

**Comment by mirmaid** [comment]
Metafiktio hyväksytään, Kauno-ryhmä laatii määritelmän.

**Comment by mirmaid** [comment]
YSOssa nyt: _Oman sepitteellisyytensä tiedostava, refleksiivinen fiktio._ - Onko riittävän selkeä?

**Comment by ghost** [comment]
KAUNO-ryhmän ehdotus määritelmäksi: _Omaa sepitteellisyyttään korostava fiktio, jossa kerronnallisin keinoin kiinnitetään lukijan huomio fiktiivisen esityksen laatimiseen, lukemiseen tai teoksen rakenteeseen_.  (Lähde: Hosiaisluoma)

**Comment by mirmaid** [comment]
Hyväksytään määritelmä.

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Kannatan myös YSOon. https://id.kb.se/term/sao/Metafiktion

**Comment by YSO-kokous** [comment]
Hyväksyttiin ehdotettu määritelmä.
