### ISSUE TITLE
eSIM

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7877]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

eSIM 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Evolution of mobile ecosystem for the internet of things 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [eSIM](http://finto.fi/yse/fi/page/Y507877)

**Comment by mariaforsen** [comment]
Sv. e-SIM, e-sim..? https://it-ord.idg.se/ord/esim/

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/ESIM

**Comment by ilona-x** [comment]
"Mikä on eSIM?
Elektroninen SIM on laitteisiin sisäänrakennettu, sähköinen SIM-kortti eli pieni mikrosiru. Laitteeseen ei siis tarvitse enää asentaa perinteistä muovista SIM-korttia."
Lähde: https://www.telia.fi/kauppa/liittymat/e-sim/artikkeli/eSIM-usein-kysytyt-kysymykset-newsroom

YSOssa SIM-kortit KÄYTÄ toimikortit http://www.yso.fi/onto/yso/p11633

**Comment by YSO-kokous** [comment]
Jätetään toistaiseksi termiehdotukseksi.
