### ISSUE TITLE
digitaalinen kaksonen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7878]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

digitaalinen kaksonen 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Simulation-based Digital Twins of Industrial Process Plants: A Semi-AutomaticImplementation Approach 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [digitaalinen kaksonen](http://finto.fi/yse/fi/page/Y507878)

**Comment by LeKorsu** [comment]
Piti googlata, mitä tämä tarkoittaa: https://fi.wikipedia.org/wiki/Digitaalinen_kaksonen
En löytänyt, että olisi (vielä) LCSH:ssa.

**Comment by mariaforsen** [comment]
Sv. digital tvilling https://it-ord.idg.se/ord/digital-tvilling/

**Comment by YSO-kokous** [comment]
Jätetään toistaiseksi termiehdotukseksi. Tarkkaillaan tilannetta.

**Comment by ilona-x** [comment]
Väitöskirjan "Methods for lifecycle support of hydraulically actuated mobile working machines using IoT and digital twin concepts" kuvailussa olisi ollut tälle tarve. Mutta ei varmaan kannata näin nopeasti kannata ottaa termiä uudelleen käsittelyyn.

**Comment by ilona-x** [comment]
olisi ollut tarpeen tämän väitöksen kuvailuun: API-based Digital Twins - Architecture for Building Modular Digital Twins Following Microservices Architectural Style  http://urn.fi/URN:ISBN:978-952-64-0594-0

**Comment by ilona-x** [comment]
IATE2
fi        digikaksonen;
digitaalinen kaksonen
sv       digital tvilling
en      digital twin
	  
Lähde: IATE 02.02.2022, Euroopan unioni (3580437)
https://termipankki.fi/tepa/fi/haku/digitaalinen%20kaksonen

**Comment by ilona-x** [comment]
taas olisi ollut käyttöä väitöskirjan kuvailussa: Discovering the Digital Twin Web http://urn.fi/URN:ISBN:978-952-64-0621-3

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
