### ISSUE TITLE
GRACILE-oireyhtymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7879]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

GRACILE-oireyhtymä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Interventions to improve mitochondrial function in a mouse model of GRACILE syndrome, a complex III disorder 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [GRACILE-oireyhtymä](http://finto.fi/yse/fi/page/Y507879)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/GRACILE-oireyhtym%C3%A4

**Comment by mariaforsen** [comment]
Sv. GRACILE-syndrom

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
