### ISSUE TITLE
vaihtoehtoinen oksidaasi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7880]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaihtoehtoinen oksidaasi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Interventions to improve mitochondrial function in a mouse model of GRACILE syndrome, a complex III disorder 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vaihtoehtoinen oksidaasi](http://finto.fi/yse/fi/page/Y507880)

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Alternative_oxidase

**Comment by mirmaid** [comment]
https://www.sttinfo.fi/tiedote/merielaimen-tuottama-vaihtoehtoinen-oksidaasi-taistelee-verenmyrkytysta-vastaan?publisherId=3747&releaseId=51746004

https://www.terveyskirjasto.fi/terveysportti/uutissorvi_uusi.uutissivu?p_uutis_id=18268&p_palsta_id=23

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
