### ISSUE TITLE
ihmisen parechovirus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7881]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ihmisen parechovirus](http://www.yso.fi/onto/ysa/Y201677) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT Parechovirus A 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Parechovirus 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Lääketieteen termit: parechovirus: _ryhmä pikornaviruksia, jotka aiheuttavat jossakin elämänvaiheessa lähes kaikille ihmisille infektion, joka voi olla oireeton tai johon liittyy useimmiten vähäisiä ruuansulatuskanavan tai hengitysteiden oireita, harvoin sydänlihaksen tai aivokudoksen tulehduksia._

FinMeSH: http://www.yso.fi/onto/mesh/D030061

**Comment by ilona-x** [comment]
https://talk.ictvonline.org/ictv-reports/ictv_online_report/positive-sense-rna-viruses/picornavirales/w/picornaviridae/693/genus-parechovirus

YSOssa Ljungan-virus KT Parechovirus B

**Comment by YSO-kokous** [comment]
Tutkitaan kuvailukäyttöä. Parechovirus A ja parechovirus B ovat myös käytössä ja ihmisen parechovirus lienee jo vanhentunut. Katsotaan kuvaillun aineiston perusteella, mikä käytettävä termi olisi paras.
