### ISSUE TITLE
sylkirauhassyöpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7882]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sylkirauhassyöpä 

#### Ehdotettu termi ruotsiksi   

spottkörtelcancer 

#### Ehdotettu termi englanniksi   

salivary gland tumour 

#### Perustelut ehdotukselle   

OIkeastaan adenokystinen sylkirauhassyöpä olisi se mitä tarvitsen, mutta tämä kattaisi kaikki kolme (Mukoepidermoidikarsinooma, adenokystinen karsinooma ja asinussolukarsinooma) tyyppiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-3728-9 

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Sylkirauhassy%C3%B6p%C3%A4
Sylkirauhassyöpä on sylkirauhasista alkunsa saava syöpäsairaus. 

**Termiehdotus Fintossa:** [sylkirauhassyöpä](http://finto.fi/yse/fi/page/Y507882)

**Comment by mirmaid** [comment]
FinMeSHissä KÄ _sylkirauhasten kasvaimet_, joka myös YSOssa. Wikipedia: _Useimmat sylkirauhaskasvaimet ovat hyvänlaatuisia, ja syöpä on harvinainen._ Eli otetaanko erikseen?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
