### ISSUE TITLE
toll:in kaltaiset reseptorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7883]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

toll:in kaltaiset reseptorit 

#### Ehdotettu termi englanniksi   

toll-like receptors 

#### Ehdotettu termi ruotsiksi   

toll-like receptors 

#### Vaihtoehtoiset termit ja ilmaisut   

TLR 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-3728-9 

#### Perustelut ehdotukselle   

Löytyy Meshistä
Toll-like receptors (TLRs) are a class of proteins that play a key role in the innate immune system.
https://en.wikipedia.org/wiki/Toll-like_receptor 

**Termiehdotus Fintossa:** [toll:in kaltaiset reseptorit](http://finto.fi/yse/fi/page/Y507883)

**Comment by mariaforsen** [comment]
Sv. toll-liknande receptorer /mesh ET toll-receptorer, toll-lika receptorer
