### ISSUE TITLE
mikrovalmistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7884]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikrovalmistus 

#### Ehdotettu termi englanniksi   

Microfabrication 

#### Ehdotettu termi ruotsiksi   

mikrofabrikation 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh96011316> 
Wikipedia : Mikrofabrikation 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Material and process engineering for cost-effective silicon technologies 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mikrovalmistus](http://finto.fi/yse/fi/page/Y507884)

**Comment by mirmaid** [comment]
Googlella aika paljon mikroaaltouunin käyttöön liittyviä tuloksia, mutta tuskin sekoittuu kuvailussa (?). Sanastossa toki on jo _mikrotekniikka, mikromekaniikka, mikrofluidistiikka_ ja _mikroelektroniikka_.

**Comment by mariaforsen** [comment]
Sv. mikrofabrikation ET mikrotillverkning

**Comment by YSO-kokous** [comment]
Ei hyväksytty ehdotusta. Jää seurattavaksi.

Sanastossa läheisiä käsitteitä: mikrotekniikka, mikromekaniikka, mikrofluidistiikka ja mikroelektroniikka. Toisaalta mikrovalmistus-termi viittaa usein mikroaaltouuniin.

**Comment by mirmaid** [comment]
Taas tarvittu: https://helda.helsinki.fi/handle/10138/308673

**Comment by ilona-x** [comment]
FinMeSH: mikroteknologia KT Microfabrication http://www.yso.fi/onto/mesh/D055616

YSOssa mikroteknologia KÄYTÄ mikrotekniikka. Eli Meshin mukaisesti voisi tehdä ohjauksen mikrovalmistus KÄYTÄ mikrotekniikka?
LCSHssa toki molemmat Microtechnology & Microfabrication

**Comment by ilona-x** [comment]
tämän väitöskirjan kuvailussa olisi myös voinut käyttää: Atomic layer deposition in fabrication of micro- and nanodevices  http://urn.fi/URN:ISBN:978-952-64-0128-7

**Comment by mirmaid** [comment]
Wikipedian artikkelit aiheista ovat melko päällekkäisiä, mutta voidaan ajatella, että _mikrotekniikka_ viittaa tieteenalaan, _mikrovalmistus_ taas tuotantoon. Toisaalta on mahdollista myös kuvailla mikrotekniikka & tarkempi valmistusmenetelmä.

**Comment by mirmaid** [comment]
_Mikrovalmistus_ on nyt kolmella käsitteellä sulkutarkenteena, joten pitäisikö ottaa myös ihan itsenään?
