### ISSUE TITLE
ei-alkoholiperäinen rasvamaksasairaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7885]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ei-alkoholiperäinen rasvamaksasairaus 

#### Ehdotettu termi englanniksi   

non-alcoholic fatty liver disease 

#### Vaihtoehtoiset termit ja ilmaisut   

ei-alkoholiperäinen rasvamaksatauti (NAFLD), ei-alkoholiperäinen rasvamaksa 

#### Perustelut ehdotukselle   

Ei-alkoholiperäinen rasvamaksa (eng. non-alcoholic fatty liver disease, NAFLD) on sairaus, jossa maksaan kertyy suuripisaraista rasvaa. 
https://fi.wikipedia.org/wiki/Ei-alkoholiper%C3%A4inen_rasvamaksa
https://gi.org/topics/fatty-liver-disease-nafld/
https://www.kaypahoito.fi/hoi50123 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-3824-8 

**Termiehdotus Fintossa:** [ei-alkoholiperäinen rasvamaksasairaus](http://finto.fi/yse/fi/page/Y507885)

**Comment by mariaforsen** [comment]
Sv. icke alkoholbetingad fettlever
