### ISSUE TITLE
suomi vieraana kielenä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7886]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suomi vieraana kielenä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://hdl.handle.net/10138/231475 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Suomi_toisena_ja_vieraana_kielen%C3%A4#Suomi_vieraana_kielen%C3%A4
Suomen kieltä opetetaan muuallakin kuin Suomessa. 
Käytetty paljon Melindassa. 

**Termiehdotus Fintossa:** [suomi vieraana kielenä](http://finto.fi/yse/fi/page/Y507886)

**Comment by mirmaid** [comment]
68 viitettä Melindassa. Sanastossa on _suomi toisena kielenä_ ja _ruotsi toisena kielenä_.

**Comment by mariaforsen** [comment]
Sv. finska som främmande språk

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
