### ISSUE TITLE
informaatiografiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7887]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[informaatiografiikka](http://www.yso.fi/onto/ysa/Y179779) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytettäväksi termiksi infografiikka. 

#### Perustelut ehdotukselle   

Finto on saanut palautetta, että miksi sanastossa ei ole infografiikkaa. Infografiikka onkin paljon käytetympi termi kuin informaatiografiikka. Google-haussa infografiikalla tulee 101000 tulosta ja infografiikalla 3750 tulosta. Wikipedia-sivun otsikko on "Infografiikka". Alan yritykset puhuvat infografiikasta.

Googlailun perusteella ruotsin kielen kannalta on sama tilanne eli käytettävän termin vaihto lienee kannattavaa myös ruotsiksi.

RT:ksi graafinen esitys? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. infografik ET informationsgrafik

**Comment by mirmaid** [comment]
Itse en saanut ihan noin suurta eroa hakutuloksissa (n. 80000/23000). Aina ei toki käyttöön vakiintuneita lyhennemuotoja ole tarpeen vaihtaa päätermiksi, tässä tapauksessa kuitenkin myös IATEssa infografiikka.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
