### ISSUE TITLE
kielletty esine / kielletty objekti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7890]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kielletty esine / kielletty objekti 

#### Ehdotettu termi ruotsiksi   

förbjudet föremål 

#### Ehdotettu termi englanniksi   

forbidden object 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vankilamuseon esinekokoelma 

#### Perustelut ehdotukselle   

Kyseinen käsite olisi tarpeellinen Vankilamuseon kokoelmiin kuuluvien erilaisten vankilassa kiellettyjen objektien asiasanoituksessa. 

**Ehdottajan organisaatio:** Kansallismuseo / Museovirasto **Termiehdotus Fintossa:** [kielletty esine / kielletty objekti](http://finto.fi/yse/fi/page/Y507890)

**Comment by mirmaid** [comment]
Myös esim. lentokoneessa ja tapahtumissa

**Comment by LeKorsu** [comment]
Monikossa?

**Comment by mariaforsen** [comment]
Sv. förbjudna föremål ET förbjudna objekt, förbjudna saker

**Comment by YSO-kokous** [comment]
Äänestettiin käytettävästä termistä.

Kielletyt tavarat 3
Kielletyt esineet 7

Päätös: käytettäväksi termiksi kielletyt esineet, ohjaustermiksi kielletyt tavarat ja kielletyt objektit.
Järjestyslaki puhuu kielletyistä esineistä. Finnair: "esineitä koskevat rajoitukset".
