### ISSUE TITLE
krautrock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7891]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[krautrock](http://www.yso.fi/onto/ysa/Y218841) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan äänitteiden ja nuottien kuvailussa 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT rock
RT elektroninen rock
RT progressiivinen rock
RT psykedeelinen rock
