### ISSUE TITLE
elektroninen rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7892]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elektroninen rock](http://www.yso.fi/onto/ysa/Y214691) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan äänitteiden ja nuottien kuvailussa 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
LT elektroninen populaarimusiikki
LT rock
RT krautrock
