### ISSUE TITLE
rakennelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7893]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakennelmat](http://www.yso.fi/onto/ysa/Y118932) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

rakennelmat = enklare byggnader (yksinkertaiset...) tosin laissa konstruktioner ja rakennussanastossa anläggningar, mutta Melinda-käyttö ja tämä sanastotilanne puhuu muun ratkaisun puolesta. Hankala tapaus. 

#### Ehdotettu muutos   

Kaipaa selkeytystä sekä käytettävien termien, että hierarkian osalta.

**Comment by mirmaid** [comment]
Taustaa https://github.com/Finto-ehdotus/YSE/issues/6544

**Comment by mirmaid** [comment]
Käytetty Melindassa n. 200 kertaa - termi ei kuitenkaan kerro juuri mitään siitä millaisia rakennelmia tarkoitetaan, joten se tuntuu melko tarpeettomalta kuvailussa (mitä hakijan ajatellaan hakevan hakusanalla rakennelmat?). Esim. pihasuunnittelu + rakennelmat (paljon aineistoa jossa _piharakentaminen_-termin olettaisi kertovan huomattavasti enemmän kuin rakennelmat).

**Comment by mariaforsen** [comment]
Olisiko siis mahdollista poistaa? Se olisi parasta myös ruotsin kannalta.

**Comment by AuHo22** [comment]
Meillä termi on ollut hyödyllinen lastenkirjallisuudessa - on legopalikoilla rakentamista ja muuta pikku-insiöörien touhuilua. Samoin peleissä luodaan erilaisia rakennelmiä.

**Comment by YSO-kokous** [comment]
Päätettiin poistaa rakennelmat-käsite. Sijoitetaan alakäsitteet tapauskohtaisesti. Merkitykseltään epäselvä käsite ja käytetty Melindassa hyvin monessa merkitykessä. Enemmistön kannatti käsitteen poistamista.

Tutkitaan, voidaanko sanastoon ottaa jokin korvaava käsite arkeologisessa merkityksessä.

**Comment by ilona-x** [comment]
Tieteen termipankki:
rakennus | rakennelma | rakenne
http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:rakennus

**Comment by krinay** [comment]
Helkassa ja Melindassa on arkeologisen aineiston kuvailussa käytetty asiasanaa _rakennelmat_ vain harvoin. Suppeammilla termeillä varmasti pärjätään. 

Kysyn asiantuntevammilta tahoilta mielipidettä suhteessa hierarkoihin ja MAOn rakennelmat-termiin.

**Comment by krinay** [comment]
Museoviraston kirjastosta kerrottiin, että MAOn käsitteitä pohditaan Museovirastossa parhaillaan arkeologian näkökulmasta SuALT-projektiin liittyen. Ja kirjastoaineistojen osalta:
"Kirjaston sisällönkuvailussa tullaan kyllä toimeen ilman rakennelmat-käsitettä, ja voidaan käyttää suppeampia termejä  (tosin esim aidat käsite tuntuu nimenomaan rakennelmalta, eikä paikalta. Esimerkiksi esiintymislava näyttää YSOssa olevan fyysinen objekti, kun taas kasvilava on ihmisen määrittämä paikka, kun intuitiivisesti sijoittaisin käsitteet ehkä päinvastoin). YSOn paikkahierarkiaa ollaan ilmeisesti kuitenkin nyt miettimässä uusiksi? En ole seurannut tätä kehitystyötä,  ja kun rakennelmat on tuolla paikkahierarkiassa, eikä fyysisissä kokonaisuuksissa tai fyysisissä objekteissa, niin en varsinkaan MAOn osalta osaa sanoa kuinka tärkeä käsite se on museopuolella ja arkeologeille."
