### ISSUE TITLE
farmakognosia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7894]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[farmakognosia](http://www.yso.fi/onto/ysa/Y113027) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT:n lisäys: farmaseuttinen biologia 

#### Perustelut ehdotukselle   

Ote wikipediasta: Farmaseuttinen biologia (aikaisemmin farmakognosia) tutkii luonnonaineiden käyttöä lääkkeinä. (ks. tarkemmin https://fi.wikipedia.org/wiki/Farmasia) 

#### Ehdottajan organisaatio   

KK Toimijakuvailupalvelu

**Comment by mariaforsen** [comment]
Sv. ET farmaceutisk biologi

**Comment by mirmaid** [comment]
Nykyinen päätermi ei näytä olevan vanhentunut ainakaan muilla kielillä?

**Comment by YSO-kokous** [comment]
Hyväksytään farmaseuttinen biologia ohjaustermiksi.
