### ISSUE TITLE
sähkömekaniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7896]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sähkömekaniikka 

#### Ehdotettu termi englanniksi   

Electromechanics 

#### Ehdotettu termi ruotsiksi   

elektromekanik 

#### Assosiatiiviset (RT)   

[sähkötekniikka](http://www.yso.fi/onto/yso/p1585) 
[konetekniikka](http://www.yso.fi/onto/yso/p20255) 

#### Vastaava käsite muussa sanastossa   

sähkömekaniikka : https://fi.wikipedia.org/wiki/S%C3%A4hk%C3%B6mekaniikka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536) 
[34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576) 

#### Tarkoitusta täsmentävä selite   

Sähkömekaniikka käsittelee ja yhdistää sähkötekniikan ja konetekniikan prosesseja sekä niihin liittyviä laitteita ja komponentteja. (WIkipedian artikkeli) 

#### Perustelut ehdotukselle   

käytetään usein toimijoiden kuvailussa (toimialana) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. sähkömekaniikkaa käsittelevien väitöskirjoissa 

**Ehdottajan organisaatio:** KK Toimijakuvailupalvelu **Termiehdotus Fintossa:** [sähkömekaniikka](http://finto.fi/yse/fi/page/Y507896)

**Comment by mirmaid** [comment]
11 viitettä Melindassa, ei LCSH:ssa. Voi olla käytännössä vaikea erottaa sähkötekniikasta.

**Comment by YSO-kokous** [comment]
Käsitteiden välinen ero ei selkeä (sähkömekaniikka ja sähkötekniikka), tuntuvat olevan hyvin lähellä toisiaan aineiston kuvailun kannalta.

Tutkitaan vielä, otetaanko sähkömekaniikka sähkötekniikan ohjaustermiksi.

**Comment by ilona-x** [comment]
Liittyyköhän YSOssa jo oleva mekatroniikka http://www.yso.fi/onto/yso/p5181 jotenkin tähän. 🤔 

Wikipedia: "Many people treat mechatronics as a modern buzzword synonymous with automation, robotics and electromechanical engineering."
https://en.wikipedia.org/wiki/Mechatronics

HUOM. Tuo moderni muotisana mekatroniikka on ollut YSAssa/YSOssa jo vuodesta 1986! 💡 😃

**Comment by mirmaid** [comment]
_Mekatroniikassa suunnittelun kohteena on laite tai tuote, jossa yhdistetään konetekniikkaa ja elektroniikkaa. Esimerkiksi proteesi, johon on yhdistetty elektroniikkaa, on mekatroniikan alueella. Sähkömekaniikassa kysymys on sähköisten ja mekaanisten systeemeiden vuorovaikutuksesta. Sähkömekaniikan alueella ovat esimerkiksi energiamuuntimet, joissa esimerkiksi mekaaninen energia muuttuu sähköiseksi energiaksi._

**Comment by ilona-x** [comment]
https://www.machinedesign.com/automation-iiot/article/21835460/whats-the-difference-between-mechatronics-and-electromechanics

**Comment by YSO-kokous** [comment]
Otetaan sanastoon sähkömekaniikka. Tarkistetaan käsitteen suhteet sähkötekniikkaan, mekatroniikkaan ja konetekniikkaan.

Taustaa: Sähkömekaniikka ei tutkimuksen valossa ole sama asia kuin mekatroniikka, sähkötekniikka ja konetekniikka, vaikkakin erot ovat hienovaraisia. Kokouksessa pohdittiin, osaako sanaston käyttäjä käyttää käsitteitä, jos sähkömekaniikkakin otetaan sanastoon. Käsitteen ottaminen sanastoon sai kuitenkin kannatusta.
