### ISSUE TITLE
Saharan eteläpuolinen Afrikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7897]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Saharan eteläpuolinen Afrikka](http://www.yso.fi/onto/ysa/Y235025) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "Musta Afrikka" 

#### Perustelut ehdotukselle   

Termi nykyään harvemmin käytetty, mutta esiintyy jonkin verran. Kun sille on jo maantieteellinen vastineensa sanastossa, niin viittausmuodo olisi hyvä lisätä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. ET Svarta Afrika

**Comment by mirmaid** [comment]
Onko korrekti? https://trepo.tuni.fi/handle/10024/105721, https://trepo.tuni.fi/bitstream/handle/10024/99820/GRADU-1475226627.pdf?sequence=1&isAllowed=y s. 88-89

**Comment by tpalonen** [comment]
Tarviiko näin vanhahtavaa termiä ottaa sanastoon? Käytettävä termi on itsensä selittävä.

**Comment by YSO-kokous** [comment]
Ei hyväksytä ehdotusta. Tarve jäi epäselväksi. Lisäksi termi vanhentunut.
