### ISSUE TITLE
rap

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7898]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rap](http://www.yso.fi/onto/ysa/Y107364) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT:n lisäys: rapmusiikki, rap-musiikki, räppi 

#### Perustelut ehdotukselle   

ohjaustermien lisäyksestä ei ole koskaan haittaa... 

#### Ehdottajan organisaatio   

KK Toimijakuvailupalvelu

**Comment by mariaforsen** [comment]
Sv. ET rapmusik, rap-musik

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
Samat KT:t SLM:ään.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
