### ISSUE TITLE
kasvainoppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7901]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kasvainoppi](http://www.yso.fi/onto/ysa/Y106917) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan päätermiksi onkologia. 

#### Perustelut ehdotukselle   

Kasvainoppi on vanhahtava. 

#### Ehdottajan organisaatio   

HYK

**Comment by ilona-x** [comment]
FinMeSH: onkologia KT kasvainoppi http://www.yso.fi/onto/mesh/D008495

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
