### ISSUE TITLE
afarin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7902]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

afarin kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781981613526 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [afarin kieli](http://finto.fi/yse/fi/page/Y507902)

**Comment by mariaforsen** [comment]
Sv. afar (språk) ET afariska
