### ISSUE TITLE
luluanluban kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7903]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luluanluban kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781791633769 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [luluanluban kieli](http://finto.fi/yse/fi/page/Y507903)

**Comment by mirmaid** [comment]
Lexvo: luban kieli, Wikipedia, Tieteen termipankki: luluanluba. 
https://www.wikiwand.com/fi/Katanganluba 

luluanluban kieli KT luban kieli

**Comment by mariaforsen** [comment]
Sv. luba-kasai ET luluanluba
https://en.wikipedia.org/wiki/Luba-Kasai_language
