### ISSUE TITLE
vatinoksaani

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7904]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vatinoksaani 

#### Ehdotettu termi englanniksi   

vatinoxan 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

https://www.helsinki.fi/fi/uutiset/terveys/uusi-laakemolekyyli-parantaa-koirien-rauhoitusten-ja-nukutusten-turvallisuutta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Interaction of alpha-2-adrenoceptor agonists and vatinoxan, a peripherally acting alpha-2-adrenoceptor antagonist, in horses 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vatinoksaani](http://finto.fi/yse/fi/page/Y507904)

**Comment by mirmaid** [comment]
YK lääkeaineet

**Comment by mariaforsen** [comment]
Sv. vatinoxan
