### ISSUE TITLE
jättiputket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7905]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jättiputket](http://www.yso.fi/onto/ysa/Y172712) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Riittääkö tarkemmat käsitteet? 

#### Perustelut ehdotukselle   

Epäselvä tieteellinen nimi/englanniksi/ruotsiksi. Näitä on kai 
armenianjättiputki (H. sosnowskyi)
kaukasianjättiputki (H. mantegazzianum)
persianjättiputki (H. persicum) 
Mutta englanniksi viitataan nyt mantegazzianumiin ja ruotsiksi myös eri tavalla (muutetaan). Onko tämä "arkinen" suomenkielinen tapa niputtaa näitä? Vrt. wikipedian erikieliset versiot, Dyntaxa, laji.fi jne. Laji.fin mukaan tämä/"jättiputkiryhmä" onkin "epämuodollinen ryhmä".

**Comment by mirmaid** [comment]
_Jättiputket_ lienee yhteisnimenä kuitenkin tarpeellinen, yleensähän kyse on näiden torjunnasta yleisesti. _Kaukasianjättiputki ja persianjättiputki on tuotu Suomeen alun perin koristekasveiksi. Näitä kahta on erittäin vaikea erottaa toisistaan, ja niitä kutsutaan usein yhteisnimellä jättiputki._ Tarkempia toki myös mahdollista lisätä.

**Comment by ilona-x** [comment]
https://vieraslajit.fi/lajit/MX.41695/show
Jättiputkiryhmä (Heracleum persicum -ryhmä)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon seuraavat käsitteet:
armenianjättiputki
kaukasianjättiputki

**Comment by mariaforsen** [comment]
Sv. 
-bredloka
-jätteloka (art) ET jättebjörnloka
