### ISSUE TITLE
implantit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7906]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[implantit](http://www.yso.fi/onto/ysa/Y108273) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pitäisikö lisätä RT proteesit? 

#### Perustelut ehdotukselle   

FinMeSH: proteesit ja istutteet http://www.yso.fi/onto/mesh/D019736 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Hyväksytään ehdotus.
