### ISSUE TITLE
liikenneasemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7907]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liikenneasemat](http://www.yso.fi/onto/ysa/Y182285) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko tarvetta yhdistää: KÄYTÄ huoltamot (tai > huoltoasemat) 

#### Perustelut ehdotukselle   

Käytetään synonymeina. Ks. https://fi.wikipedia.org/wiki/Huoltoasema 

#### Ehdottajan organisaatio   

YSO-kokous

**Comment by ilona-x** [comment]
YSOssa näiden lisäksi myös **jakeluasemat** http://www.yso.fi/onto/yso/p24132

"Tässä asetuksessa tarkoitetaan:
1) jakeluasemalla sellaista paikkaa jakelulaitteineen, nestemäisen polttoaineen säiliöineen ja mahdollisine huolto- ja pesuhalleineen sekä muine rakennuksineen, jossa polttoainetta myydään tai luovutetaan pääasiassa moottoriajoneuvojen tai moottoriveneiden polttoaineeksi;

2) jakelupisteellä erillisenä tai muun liiketoiminnan yhteydessä toimivaa, kooltaan ja 
säiliötilavuudeltaan jakeluasemaa pienempää nestemäisten polttoaineiden jakelupaikkaa;
... "

Lähde: http://www.finlex.fi/fi/laki/alkup/2010/20100444

**Comment by mirmaid** [comment]
Ja _jakeluasemaa_ käytetään (ainakin jossain yhteyksissä) yläkäsitteenä.

**Comment by AuHo22** [comment]
Huoltoasemat yleisempi ja selkeämpi kuin huoltamot -

Kielitoimiston sanakirja: **huoltamo** = huoltoliike. Televisiohuoltamo. Erik. vars. liike, jossa huolletaan moottoriajoneuvoja ja myydään polttoainetta, huoltoasema (sekä)
**jakelu­asema**: Öljy-yhtiön huolto- ja jakeluasemat.

YSOssa olevan määritelmän mukaan **liikenneasemat** -> po. jakeluasemat, mutta käännökset ovat laajempia merkityksiltään traffic stations (sw. trafikstationer) vrt. jakeluasemat, eng fuel stations, sw distributionsstationer? 

Jakeluasemat käytetään näköjään viranomais-, lakikielessä.

**Comment by mirmaid** [comment]
Wikisanakirja:
huoltoasema
1. (vanhahtava) liike josta saa autoihin varaosia ja huoltopalveluja sekä polttoainetta
2. liike, jonka yhteydessä on polttoaineiden myynti, liikenneasema

**Comment by mirmaid** [comment]
Riittäisikö pelkkä _huoltoasemat_ KT jakeluasemat, liikenneasemat, huoltamot. Sanastossa on lisäksi _korjaamot_. Tälle voisi lisätä ohjaustermiksi autokorjaamot, jota on jonkin verran käytetty lähinnä artikkeliaineistossa.

**Comment by YSO-kokous** [comment]
Hyväksytään mirmaid-ehdotus edellä, ml. autokorjaamot ohjaustermiksi korjaamoille.
