### ISSUE TITLE
Creative Commons -lisenssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7912]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Creative Commons -lisenssit 

#### Vaihtoehtoiset termit ja ilmaisut   

Creative Commons, CC-lisenssit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Avoin sisältö : käytännön opas Creative Commons -lisenssien käyttämiseen ISBN 978-952-93-8673-4 

#### Perustelut ehdotukselle   

Suomessa Creative Commons -lisenssit ovat olleet julkishallinnon standardilisenssejä vuodesta 2014. Creative Commons -lisenssijärjestelmä koostuu neljästä eri ehdosta, joista johdetaan kuusi erilaista päälisenssiä. CC-lisenssien lähtökohtana on, että kaikilla on oikeus tehdä teoksesta kopioita, esittää ja näyttää teos julkisesti, levittää ja välittää teosta eteenpäin sekä tehdä siitä johdannaisteoksia. Näitä perusoikeuksia voidaan rajoittaa käyttämällä erilaisia ehtoja. https://fi.wikipedia.org/wiki/Creative_Commons 

**Termiehdotus Fintossa:** [Creative Commons -lisenssit](http://finto.fi/yse/fi/page/Y507912)

**Comment by mirmaid** [comment]
LCNAF: Creative Commons (Organization)

Melindassa joko vapaana asiasanana tai yhteisönä n. 15 kertaa. Tuntuisi vähän hassulta kuvailla itse lisenssejä yhteisönimellä? Olisiko tämä vähän vastaava kuin sanastosta löytyvä _ISO-standardit_?

**Comment by tpalonen** [comment]
Riittäisikö käytettäväksi termiksi pelkkä Creative Commons niin käsitettä voisi käyttää vähän laajemmin?

**Comment by mirmaid** [comment]
Silloin se pitäisi nähdäkseni auktorisoida yhteisönä?

**Comment by mariaforsen** [comment]
Sv. Creative Commons-licenser ET CC-licenser
Yhteisöt ovat valitettavasti yksikieliset, kannatan YSO-terminä.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon Creative Commons -lisenssit.
