### ISSUE TITLE
isotooppianalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7914]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

isotooppianalyysi 

#### Ehdotettu termi englanniksi   

isotope analysis 

#### Ehdotettu termi ruotsiksi   

isotopanalys 

#### Vaihtoehtoiset termit ja ilmaisut   

stabiili-isotooppianalyysi 
isotooppimääritys 
stabiili-isotooppimääritys 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[analyysimenetelmät](http://www.yso.fi/onto/yso/p6085) 

#### Assosiatiiviset (RT)   

[isotoopit](http://www.yso.fi/onto/yso/p6387) 
[isotooppigeologia](http://www.yso.fi/onto/yso/p27531) 
[ajoitus (historia)](http://www.yso.fi/onto/yso/p7804) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Isotope_analysis 
MAO : <http://www.yso.fi/onto/mao/p8233> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Perustelut ehdotukselle   

Analyysimenetelmä / kokoelma analyysimenetelmiä, joka tutkii aineiden isotooppikoostumusta.Käytetään monilla tieteenaloilla jonkin aineen alkuperän ja historian tutkimiseen. Esim. historialliset esineet, muinaisjäänteistä pääteltävät ruokavaliot, muuttolintujen pesimä ja talvehtimisalueet, ekosysteemien ravintoverkot, geologinen iänmääritys jne. Finna löytää haulla isotooppianalyysi OR "isotope analysis" 169 tulosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finna.fi/Record/jyx.123456789_67019 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [isotooppianalyysi](http://finto.fi/yse/fi/page/Y507914)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

LCSH:ssa on Radiochemical analysis ja Isotope dilution analysis, mutta ei tätä. Sen sijaan on Stable isotopes in ecological research ja useita vastaavia.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
