### ISSUE TITLE
dynaamiset systeemit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7915]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dynaamiset systeemit 

#### Ehdotettu termi ruotsiksi   

dynamiska system 

#### Ehdotettu termi englanniksi   

dynamical systems 

#### Ehdotettu yläkäsite YSOssa (LT)   

[matematiikka](http://www.yso.fi/onto/yso/p3160) 
[matemaattiset mallit](http://www.yso.fi/onto/yso/p11401) 

#### Assosiatiiviset (RT)   

[systeemiteoria](http://www.yso.fi/onto/yso/p13479) 
[kaaosteoria](http://www.yso.fi/onto/yso/p6339) 
[dynamiikka](http://www.yso.fi/onto/yso/p4095) 
[bifurkaatio](http://www.yso.fi/onto/yso/p29101) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Dynamical_system 
MSC2010 : https://mathscinet.ams.org/msc/msc2010.html?t=37-XX&btn=Current 
Wikipedia : https://fi.wikipedia.org/wiki/Dynaaminen_systeemi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Perustelut ehdotukselle   

Matemaattinen malli järjestelmälle, jossa piste liikkuu avaruudessa ajan funktiona. Lisäksi nimitys matematiikan osa-alueelle, joka tutkii tällaisia järjestelmiä. Käytetään paljon soveltavassa matematiikassa. Finnasta löytyy haulla "dynaamiset systeemit" OR "dynamical systems" peräti 1382 julkaisua 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jykdok.1542699 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [dynaamiset systeemit](http://finto.fi/yse/fi/page/Y507915)

**Comment by mirmaid** [comment]
Melindassa _dynaamiset systeemit_ aiheena n. 20 kertaa.

LCSH:ssa Hybrid systems (= Hybrid dynamic systems), mutta ei laajempaa käsitettä.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
