### ISSUE TITLE
attraktorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7916]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

attraktorit 

#### Ehdotettu termi ruotsiksi   

attraktorer 

#### Ehdotettu termi englanniksi   

attractors 

#### Ehdotettu yläkäsite YSOssa (LT)   

[joukot (matematiikka)](http://www.yso.fi/onto/yso/p12530) 

#### Assosiatiiviset (RT)   

[kaaosteoria](http://www.yso.fi/onto/yso/p6339) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Attractor 
Wikipedia : https://fi.wikipedia.org/wiki/Attraktori 
LCSH : <http://id.loc.gov/authorities/subjects/sh97005887.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Perustelut ehdotukselle   

Joukko, jota kohti dynaaminen systeemi kehittyy. Assosiatiiviseksi käsitteeksi siis myös "dynaamiset systeemit". Finnassa haku attraktorit OR attractors antaa 413 tulosta, joista suuri osaa käsittelee juuri tätä aihetta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finna.fi/Record/jykdok.1804966 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [attraktorit](http://finto.fi/yse/fi/page/Y507916)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
