### ISSUE TITLE
kausivaihtelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7917]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kausivaihtelut](http://www.yso.fi/onto/ysa/Y109364) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ainakin ryhmiin:
13 Hydrologia
14 Klimatologia. Meteorologia. Ilmatiede
15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia
61 Väestötiede. Demografia

Uusi assosiatiivinen käsite: aikasarjat 

#### Perustelut ehdotukselle   

Samaa asiasanaa voi varmaan käyttää myös muussa kuin taloustieteellisessä yhteydessä. Tämä olisi hyvä ilmaista liittämällä se useampaan ryhmään 

#### Ehdottajan organisaatio   

Jyväskylän yliopisto

**Comment by ilona-x** [comment]
Kausivaihtelu
Kausivaihtelu on aikasarjan vuoden sisäistä vaihtelua, joka toistuu kutakuinkin säännöllisenä. Kausivaihtelua voivat aiheuttaa mm. lämpötila, sademäärä, pyhäpäivät, sesongit ja lomat.
Lähde: https://www.stat.fi/meta/kas/kausivaihtelu.html

kausivaihtelu | vuodenaikavaihtelu
http://tieteentermipankki.fi/wiki/Epidemiologia:kausivaihtelu

**Comment by YSO-kokous** [comment]
Laitetaan käsitteelle ryhmäksi pelkästään 00 Yleistermit.
