### ISSUE TITLE
spin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7918]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

spin 

#### Ehdotettu termi ruotsiksi   

spinn 

#### Ehdotettu termi englanniksi   

spin 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fysikaaliset ilmiöt](http://www.yso.fi/onto/yso/p949) 

#### Assosiatiiviset (RT)   

[kvanttimekaniikka](http://www.yso.fi/onto/yso/p5563) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Spin_(physics) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Perustelut ehdotukselle   

Hiukkasten ja atomiydinten kvanttimekaaninen ominaisuus, "sisäinen pyörimismäärä". Fysiikan perussanastoa, esiintyy paljon kvanttimekaniikassa, hiukkas- ja ydinfysiikassa ja tiiviin aineen fysiikassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jyx.123456789_63375 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [spin](http://finto.fi/yse/fi/page/Y507918)

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/T%C3%A4htitiede:spin

**Comment by tpalonen** [comment]
Tarvinnee sulkutarkenteen, ainakin englanniksi. Ehkä myös suomeksi? (fysikaaliset ominaisuudet)?
Ks. https://en.wikipedia.org/wiki/Spin

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon suomeksi muodossa spin, englanninkielessä sulkutarkenne tarpeen mukaan.

**Comment by mariaforsen** [comment]
Sv. spinn (kvantfysik)
