### ISSUE TITLE
optinen litografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7919]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

optinen litografia 

#### Ehdotettu termi ruotsiksi   

mikrolitografi 

#### Ehdotettu termi englanniksi   

photolithography 

#### Vaihtoehtoiset termit ja ilmaisut   

optical lithography 

#### Ehdotettu yläkäsite YSOssa (LT)   

[menetelmät](http://www.yso.fi/onto/yso/p1913) 

#### Assosiatiiviset (RT)   

[puolijohdetekniikka](http://www.yso.fi/onto/yso/p11465) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Optinen_litografia 
LCSH : <http://id.loc.gov/authorities/subjects/sh85101379.html> 
Wikipedia : https://en.wikipedia.org/wiki/Photolithography 

#### Tarkoitusta täsmentävä selite   

Puolijohdeteollisuuden valmistusmenetelmä. 

#### Perustelut ehdotukselle   

Standardivalmistusmenetelmä nykyisessä puolijohdeteollisuudessa. Nimetty taidegrafiikan litografian mukaan, mutta tätä asiasanaa ei kannata laittaa litografian alakäsitteeksi. Litografia ei edes ole kovin hyvä analogia tämän menetelmän prosessivaiheille. "optinen litografia" OR photolithography antaa Finnassa 77 tulosta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finna.fi/Record/jykdok.1859611 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [optinen litografia](http://finto.fi/yse/fi/page/Y507919)

**Comment by jtuohini** [comment]
Vaatisi varmasti jonkin sulkutarkenteen, ettei sekoittuisi puheena olleestikin painomenetelmään (vrt. UDK-luokka [776 _Fotolitografia / optinen litografia / valolitografia. Laakapainolevyjen valmistaminen valokuvaustekniikalla_](http://udcdata.info/065836))

**Comment by mirmaid** [comment]
Olisiko _optinen litografia (mikrotekniikka)_ mahdollinen?

**Comment by mariaforsen** [comment]
Sv. optisk litografi

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
