### ISSUE TITLE
heterosykliset yhdisteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7920]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heterosykliset yhdisteet 

#### Ehdotettu termi ruotsiksi   

heterocykliska föreningar 

#### Ehdotettu termi englanniksi   

heterocyclic compound 

#### Vaihtoehtoiset termit ja ilmaisut   

heterosyklit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kemialliset yhdisteet](http://www.yso.fi/onto/yso/p324) 

#### Alakäsitteet (RT)   

[atsolit](http://www.yso.fi/onto/yso/p27765) 
[furaanit](http://www.yso.fi/onto/yso/p7657) 

#### Assosiatiiviset (RT)   

[alkaloidit](http://www.yso.fi/onto/yso/p11306) 
[nukleiinihapot](http://www.yso.fi/onto/yso/p10072) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85060525.html> 
Wikipedia : https://fi.wikipedia.org/wiki/Heterosyklinen_yhdiste 

#### Tarkoitusta täsmentävä selite   

Rengasrakenteinen kemiallinen yhdiste, jonka renkaassa on vähintään kahta eri alkuainetta. 

#### Perustelut ehdotukselle   

Yleinen luokka kemiallisia yhdisteitä, esim. suuri osa lääkeaineista kuuluu näihin. Alakäsitteitä ja assosiatiivisiä käsitteitä voisi löytyä enemmänkin, jos etsisi vielä lisää 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jykdok.2009203 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [heterosykliset yhdisteet](http://finto.fi/yse/fi/page/Y507920)

**Comment by mirmaid** [comment]
Myös FinMeSH: http://www.yso.fi/onto/mesh/D006571 (46 viitettä Melindassa).
