### ISSUE TITLE
juhlarahat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7921]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[juhlarahat](http://www.yso.fi/onto/ysa/Y95649) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan LT-suhde "raha" --> "metallirahat" 

#### Perustelut ehdotukselle   

Juhlarahat ovat kolikoita, eivät niinkään erityinen rahan laji. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Hyväksytään ehdotus.
