### ISSUE TITLE
räätälöinti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7922]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[räätälöinti](http://www.yso.fi/onto/ysa/Y142566) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä tai mahdollisesti jaetaan? 

#### Perustelut ehdotukselle   

Ruotsiksi vastine on ollut skrädderiarbete, mutta suurin osa Melindaosumista eivät liity siihen, eli vaatteiden valmistukseen. Merkitys pitää olla selkeä että voidaan valita parempi vastine. 
Ks. esim. Kielitoimiston sanakirja räätälöidä: vaatteiden valmistamisesta, erik. suunnitella ja toteuttaa yksilöllisesti

**Comment by mariaforsen** [comment]
Muutama ompeluun liittyvä: 
-Construction for fashion design / Anette Fischer and Kiran Gobin.
-Skrädderikonstens teori. 1, lllustrerad lärobok i skräddareyrket för handtverksskolor och nybörjare i allmänhet / af O. Olander. myös osa 2 ja osa 3
-Skräddarlexikon / Ragnar Börkman.
-Menʼs 17th & 18th century costume, cut & fashion : patterns for menʼs costumes / R.I. Davis.
-Menswear : business to style / Michael R. Londrigan.
-Pattern cutting for men’s costume / Elizabeth Friendship.
-Skräddaren, sömmerskan och modet : arbetsmetoder och arbetsdelning i tillverkningen av kvinnlig dräkt 1770-1830 / Pernilla Rasmussen ; [teckningar: Kirsten Toftegaard].
-Fabrics and pattern cutting : fabric, form and flat pattern cutting / Winifred Aldrich ; book design, photography and computer graphics by James Aldrich.

Entä missä merkityksessä tämä: Tailoring : a step-by-step guide to creating beautiful customized garments.

Pitäisi varmaan jakaa jos halutaan huomioida myös historiallista näkökulmaa.. Pitäisihän se ainakin jollain tavalla olla mukana myös "vaatteiden valmistus"-merkityksessä, esim. onko mahdollista tehdä ohjaus räätälöinti (ompelu) KÄYTÄ vaateteollisuus tms. (sanastossa ei ole vaatteiden valmistusta), ellei haluta pääterminä?

**Comment by tpalonen** [comment]
Varovainen ääni jakamiselle. Ehdotukseni käytettäviksi termeiksi:

_räätälöinti (kustomointi)
räätälöinti (vaatteet/räätälintyö)_

Vaatteen valmistus tms ei mielestäni tarpeeksi kattava sulkutarkenne. Vrt. Wiki: "Vaatturi eli räätäli (vanhentuneelta nimitykseltään kraatari) on käsityöläinen, joka tekee ammatikseen vaatteita ja tarvittaessa uudistaa ja korjaa niitä."

**Comment by mirmaid** [comment]
Toinen termi voisi myös olla vain _kustomointi_. Sitä käytetään myös vaatteiden valmistuksen yhteydessä: _Opinnäytetyön tuloksena on yksi perusviitta, jota voi kustomoida kahteen eri linjaan: rock ja boheemi._

Näköjään löytyy myös _massaräätälöinti_, joka hassua kyllä tuli vastaan nimenomaan vaatevalmistusalaa käsittelevässä aineistossa. Massakustomointi näyttää olevan vähemmän käytetty.

En ole varma, onko _räätälintyö_-merkitys tarpeen. Viitteitä on vain kourallinen ja osaan niistäkin sopii _kustomointi_ (joka saattaa esim. esiintyä nimekkeessä). Osassa voisi käyttää käsitettä _räätälit_. Muutakin vaatteiden valmistuksen termistöä löytyy (ja on käytetty tietueissa). _Räätälintyö_-termi eroaisi selkeämmin kustoimointi-merkityksestä kuin _räätälöinti (vaatteet)_ (vastaavia on sanastossa _peltityö, levytyö_).

**Comment by tpalonen** [comment]
Kustomointi olisi kyllä yksiselitteisempi. Siirryn kannattamaan sitä. En vastusta räätälöinti/räätälintyö/vaatturintyö-käsitteen ottamista sanastoon.

**Comment by ilona-x** [comment]
"Räätälöinti

**Räätälöinti, kohdentaminen, kustomointi ja personointi** ovat käsitteitä, joita käytetään eri aloilla tarkoittamaan kutakuinkin samaa asiaa. Yleisesti kyse on yksilöiden välisten erojen huomioimisesta ja näiden erojen ottamisesta huomioon esitettäessä tai tarjottaessa eri asioita erilaisille ihmisille. Internetissä eri ihmiset voisivat esimerkiksi saada näkyviinsä erilaisen käyttöliittymän tai erilaisia sisältöjä. Terveystiedon räätälöinnissä yksilöstä pyritään ensin selvittämään tärkeitä tietoja. Sen jälkeen näihin tietoihin perustuen, hänelle valikoidaan ja esitetään terveystietoa, jonka katsotaan olevan hänelle henkilökohtaisesti merkitsevää ja häntä kiinnostavaa. Räätälöinti voi koskea siis niin tiedon sisältöä, kuin myös tiedon esitystapaa, ja jopa käytettävää kanavaa. Räätälöinnin tarkoituksena on tehdä tiedon tulkitsemisesta, ymmärtämisestä ja tietoon luottamisesta vastaanottajalle helpompaa. Yleensä terveystiedon räätälöinnistä puhuttaessa tarkoitetaan tietokoneella tuotettua räätälöintiä. Esimerkiksi räätälöintiä hyödyntävällä painonhallintasivustolla käyvä henkilö saa, ainakin osittain, erilaisen tietopaketin tai terveysviestin kuin toinen painonhallintasivulla vieraileva. (Enwald 2013)."
Lähde: https://www.oulu.fi/gasel/esiselvitys_k%C3%A4sitteet


YSOssa on:
personointi http://www.yso.fi/onto/yso/p21894
kohdentaminen http://www.yso.fi/onto/yso/p1032
massaräätälöinti KT massakustomointi http://www.yso.fi/onto/yso/p18600
lokalisointi http://www.yso.fi/onto/yso/p4883

**Comment by mirmaid** [comment]
Jos jotain halutaan yhdistää, kokisin ehkä kustomoinnin sopivan laajemmin kuin personoinnin?

**Comment by YSO-kokous** [comment]
Muutetaan räätälöinti muotoon kustomointi, ohjaustermiksi räätälöinti. Ei oteta räätälintyötä tai vastaavaa sanastoon.
