### ISSUE TITLE
reseptorit (biokemia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7923]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

reseptorit (biokemia) 

#### Ehdotettu termi englanniksi   

receptors (biochemistry) 

#### Ehdotettu termi ruotsiksi   

receptorer (biokemi) 

#### Vaihtoehtoiset termit ja ilmaisut   

reseptoriproteiinit 
receptorproteiner 
receptor proteins 

#### Ehdotettu yläkäsite YSOssa (LT)   

[proteiinit](http://www.yso.fi/onto/yso/p4332) 

#### Assosiatiiviset (RT)   

[soluviestintä](http://www.yso.fi/onto/yso/p28740) 
[solukalvot](http://www.yso.fi/onto/yso/p2410) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85021665.html> 
Wikipedia : https://en.wikipedia.org/wiki/Receptor_(biochemistry) 
Wikipedia : https://fi.wikipedia.org/wiki/Reseptori_(biokemia) 
Tieteen termipankki : https://tieteentermipankki.fi/wiki/Mikrobiologia:reseptori 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://jyu.finna.fi/Record/jyx.123456789_62775 

#### Perustelut ehdotukselle   

YSOssa reseptori tarkoittaa jo aistinsolua. Tämä soluviestintään osallistuvaa solun omaa proteiinia tarkoittava merkitys tuntuu olevan jopa käytetympi, joten tämäkin pitäisi lisätä 

#### Tarkoitusta täsmentävä selite   

Tieteen termipankki: Vastaanottaja, solun pinnan valkuaisainemolekyyli, joka sitoo tiettyä ainetta. 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [reseptorit (biokemia)](http://finto.fi/yse/fi/page/Y507923)

**Comment by mirmaid** [comment]
Tämä onkin roikkunut jo pitkään listalla: https://github.com/Finto-ehdotus/YSE/issues/5620

Varmaankin ehdotettu _reseptorit (biokemia)_ on parempi kuin MeSHin _solun pintareseptorit_, koska MeSHissä myös _solulima- ja tumareseptorit_.

Voisi lisätä myös määritelmän.

**Comment by mirmaid** [comment]
YSOn toinen _reseptorit_-käsite tarvitsee myös joko tarkenteen tai uuden termimuodon. Ehdottaisin muotoa _aistinreseptorit_: reseptori: vastaanotin 1. aistinreseptori; aistinsolu tai solun osa, joka on erilaistunut reagoimaan tietyntyyppisiin ärsykkeisiin (johonkin tiettyyn energiamuotoon) ja muuntamaan ne hermoimpulsseiksi https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=ltt02910, https://fi.wikipedia.org/wiki/Aistinreseptori

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon reseptorit (biokemia).
Muutetaan nykyinen reseptorit-käsitteen käytettäväksi termiksi aistinreseptorit.

**Comment by mariaforsen** [comment]
Sv. 
-receptorer (biokemi)
-sinnesceller ET sensoriska receptorer, sinnesreceptorer, receptorceller,  neuroreceptorer, sensoriska receptorceller
