### ISSUE TITLE
ikääntyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7926]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ikääntyminen](http://www.yso.fi/onto/ysa/Y105559) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen vanheneminen tai selkeytetään eroa. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

HYK

**Comment by ilona-x** [comment]
FinMeSH: ikääntyminen KT vanheneminen http://www.yso.fi/onto/mesh/D000375

Kielitoimiston sanakirja: 

vanhentua

1. tulla vanh(emm)aksi, vanh(emm)alta vaikuttavaksi, vanh(emm)an näköiseksi.
Väestön vanhentuminen.
Vanhentua ennen aikojaan.
Hän on paljon vanhentunut sitten viime näkemän.
Leik.
Siinä hommassa ei kauan vanhennuttu viivytelty.
2. tulla vanhanaikaiseksi, jäädä ajastaan jälkeen.
Nopeasti vanhentuva nuorisomuoti.
Vanhentunut käsitys.
Vanhentuneen lainsäädännön uudistaminen.
3. tulla määräajan umpeen kulumisen vuoksi pätemättömäksi.
Kuukaudessa vanhentuva matkalippu.
Oik.
Vanhentuminen lainmukaisen määräajan laiminlyömisestä johtuva tietyn oikeuden menetys.
Saatavien vanhentuminen.
Vanhentunut rikos.


ikääntyä

vanhentua, vanheta, tulla iäkkääksi.
Tasaantui ikääntyessään.
Väestön ikääntyminen.

**Comment by mariaforsen** [comment]
Kannatan yhdistämistä! Sanastossa on nyt vakava virhe ainakin ruotsin osalta, sekä "åldrande" että "bli gammal" -nämä ovat synonymeja, tai ainakaan ei ole mahdollista käyttää selkeästi eri tavalla kuvailussa. 
Vanhentuminen (oikeusmerkityksessä) on erikseen sanastossa. 

Samanlainen yhdistäminen tehtiin jo onnistuneesti termien vanhukset ja ikääntyneet kohdalla.

**Comment by ilona-x** [comment]
tullut vastaan muutama tilanne, jossa olisi tarvinnut termiä, jota voisi käyttää materiaalin vanhenemisesta https://fi.wikipedia.org/wiki/Vanheneminen_(materiaalin)

**Comment by mariaforsen** [comment]
Sellaiseen (materiaalin) vanhenemiseen tarvittaisiin varmaan ihan erillinen termi? https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/%C3%A5ldring

**Comment by AuHo22** [comment]
Ikääntyminen nykyisin ryhmässä 61 Väestötiede, ja vanheneminen 48 ja 55 -> yhtä hyvin ikääntymiseen liittyvät muutokset voivat olla psykologisia ja lääketieteellisiä. 
Voiko vanheneminen olla sitten yleistermi, vrt. monet muut muutos-termin alla olevat vastaavat käsitteet?

**Comment by mirmaid** [comment]
Ikääntyminen sopii käytettäväksi ihmisistä (ja ehkä jotenkuten eläimistä: https://melinda.kansalliskirjasto.fi/byid/013679649, entä https://melinda.kansalliskirjasto.fi/byid/006088748?) ja varmaan sen osalta onkin yhdistettävissä. 

Suurin osa viitteistä näyttää käsittelevän ihmisen vanhenemista (jonkin verran muita eläimiä), vastaan tuli:
https://melinda.kansalliskirjasto.fi/byid/006645788 - keräyspaperin vanheneminen
https://melinda.kansalliskirjasto.fi/byid/005990610 - räjähdysaineiden vanheneminen

**Comment by mariaforsen** [comment]
Åldrande käytetään ensisijaisesti elävistä olennoista, mutta ainakin joidenkin määritelmien mukaan käy myös muista (aineista, materiaaleista jne.). Ks. https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/%C3%A5ldrande

**Comment by mirmaid** [comment]
^ Suomeksi _ikääntyminen_ ei kyllä käy tapauksessa "keräyspaperin ikääntyminen".

**Comment by ilona-x** [comment]
> 
> 
> tullut vastaan muutama tilanne, jossa olisi tarvinnut termiä, jota voisi käyttää materiaalin vanhenemisesta https://fi.wikipedia.org/wiki/Vanheneminen_(materiaalin)

Voisiko olla erikseen **vanheneminen (materiaalitekniikka / materiaalin)**? Tämä kävisi tuohon keräyspaperitapaukseen.

**Comment by YSO-kokous** [comment]
### Päätökset
yhdistetään käsitteet:  ikääntyminen KT vanheneminen
