### ISSUE TITLE
kodittomat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7927]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kodittomat](http://www.yso.fi/onto/ysa/Y123570) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen asunnottomat tai selkeytetään eroa. Huom. myös kodittomuus - asunnottomuus. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

HYK

**Comment by satuniininen** [comment]
Melindassa:
kodittomat 233 kpl
asunnottomat 384 kpl
kodittomat + asunnottomat 121 kpl

kodittomuus 336 kpl
asunnottomuus 879 kpl
kodittomuus + asunnottomuus 185 kpl

**Comment by mariaforsen** [comment]
SAOssa vain hemlösa (kodittomat), bostadslösa (asunnottomat) korvattuna.

**Comment by mirmaid** [comment]
_Asunnottomat/asunnottomuus_ enemmän käytetty, mutta sopii huonosti jos kyse on kodittomista lapsista. Sanastossa on kuitenkin myös _katulapset_.

Esim. https://melinda.kansalliskirjasto.fi/byid/005723651

**Comment by YSO-kokous** [comment]
Vaihdetaan päätermit: 
asunnottomat KT kodittomat 
asunnottomuus KT kodittomuus
