### ISSUE TITLE
amnesia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7928]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[amnesia](http://www.yso.fi/onto/ysa/Y116474) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen muistinmenetys tai selkeytetään eroa. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

HYK

**Comment by ilona-x** [comment]
FinMeSH: 
amnesia http://www.yso.fi/onto/mesh/D000647
KT    muistamattomuus
KT    muistikatko
KT    muistinmenetys
KT    muistittomuus

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termeissä (Terveysportti):

amnesia

amnesia la, amnesia e, amnesi ‑n r (< a- kr ei + mnesis kr muisti) muistinmenetys, muistittomuus, muistamattomuus | mm. aivovammaan, ennenaikaiseen vanhenemiseen, runsaaseen alkoholinkäyttöön ja dementiaan liittyvä yleisoire; vrt. muisti, amnestinen oireyhtymä, hypomnesia, dementia, muistisairaus, paramnesia

"Amnesia" ja "muistinmenetys" tarkoittavat siis samaa. YSO:ssa kallistuisin suomenkielisemmän "muistinmenetyksen" kannalle (vaikka olenkin kreikan kielen fanittaja :D).

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet. Käytettäväksi termiksi muistinmenetys, ohjaustermiksi amnesia. Käytettävästä termistä äänestettiin: mustiinmenetys 8 ääntä, amnesia 2.
