### ISSUE TITLE
lastentarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7929]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lastentarhat](http://www.yso.fi/onto/ysa/Y104088) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen päiväkodit tai selkeytetään eroa. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

HYK

**Comment by LeKorsu** [comment]
En kannata yhdistämistä tuon  käyttöhuomautuksessa mainitun historiallisen kontekstin vuoksi ja yritän tässä ajatella laajemmin tekstiaineistojen ulkopuolelle, esim. valokuvia. Siksi pidän tärkeänä, että sana lastentarhat säilyisi sanastossa.

**Comment by mariaforsen** [comment]
Millä tavalla valokuva-aineistot ovat tässä eri asia?

**Comment by LeKorsu** [comment]
Enemmän kuin mikään rationaalinen perustelu tämä taitaa olla oma päänsisäinen vinouma, joka jotenkin mieltää, että tekstiaineistoissa olisi helpompi yhdistää modernimpi termi historialliseen termiin kuin kuva-aineistoissa =).

**Comment by ilona-x** [comment]
Itse kannattaisin näiden yhdistämistä, kun näissä tämänkaltaisissa tapauksissa välillä saattaa lipsahtaa vanhentunut termi uusiinkin aineistoihin. Vastaava YSOsta löytyvä tapaus esim. mielisairaalat & psykiatriset sairaalat.

**Comment by tpalonen** [comment]
Kannatan yhdistämistä.

**Comment by mariaforsen** [comment]
Minäkin kannatan yhdistämistä.

**Comment by satuniininen** [comment]
Kannatan yhdistämistä
