### ISSUE TITLE
itseluottamus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7930]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itseluottamus](http://www.yso.fi/onto/ysa/Y95593) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaanko erikseen sekä itseluottamus että itsetunto? 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

HYK

**Comment by ilona-x** [comment]
Myös LCSHssa molemmat:
Self-esteem http://id.loc.gov/authorities/subjects/sh85119793
Self-confidence http://id.loc.gov/authorities/subjects/sh85119715

https://fi.wikipedia.org/wiki/Itseluottamus
https://fi.wikipedia.org/wiki/Itsetunto

**Comment by mariaforsen** [comment]
Myös SAOssa molemmat.

**Comment by YSO-kokous** [comment]
Tarvitaan YSOssa molemmat, ks. kommentit edellä.
