### ISSUE TITLE
luu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7931]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luu](http://www.yso.fi/onto/ysa/Y172941) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö olla monikossa? 

#### Perustelut ehdotukselle   

Ehkä tarkoittaa luuta materiaalina? Ysassa on myös ”luusto” ja ”luukudokset”. MeSH-termiä ”Bone and Bones” vastaa määritelmän mukaan parhaiten ysa-termi ”luukudokset”, mutta se kuulostaa mielestäni vähän hassulta ja tosi harvoin missään vastaan tulleelta. 

#### Ehdottajan organisaatio   

HYK

**Comment by jarmosaarikko** [comment]
YSO:sta löytyy "norsunluu" YK luonnonmateriaalit  RT luutyöt
pelkkä "luu" pitäisi varmaan olla tuon norsunluun rinnalla tai siirtää norsunluu sen alakäsitteeksi. 

nyt on luu YK luukudokset mikä pitäisi muuttaa.
Melindan 195 "luu" YSO-termistä  18 käsittelee luuta materiaalina ja loput  luustoa ja luukudosta, luufossiileja, luiden korjausta jne.    Mielestäni yläkäsitteeksi voisi vaihtaa "luonnonmateraalit", mutta tällöin olisi korjattava Melindassa em. tietueisiin "luusto" tai "luukudos".    
"luut" voisi olla ohjausterminä käsitteelle "luusto". 
Huom! Samalla pitäisi poistaa assosiaatio "luusto" osa kokonaisuutta "luu".  joka muutenkin kuulostaa hassulta.

Finnassa aiheena "luusto" 2245 kertaa ja "luu" 10034 kertaa.  Esineitä, joissa "luu" on 1099 kpl. Luulöydöt 697 ja luutyöt 581 kertaa.  puoltaisi luu omana käsitteenään luonnonmateriaalit alla mutta tuottaisi paljon virheosumia, kun suurin osa osumista käsitteleekin luita lääketieteen kannalta..

**Comment by mariaforsen** [comment]
Ruotsiksi on ollut ben (benvävnader) =luu. Jos halutaan että tämä viittaa vain materiaaliin, niin päätermi pitää muuttaa.

**Comment by tpalonen** [comment]
MAOssa on "luu (materiaalit)". http://www.yso.fi/onto/mao/p6229
Riittäisikö kuitenkin yleissanastoon yksi käsite, jota voisi käyttää luuaineksesta sekä biologian että esim. käsitöiden yhteydessä?

**Comment by mirmaid** [comment]
Lääketieteen termit:
**luu**: 1. ks. luukudos; 2. pääasiallisesti luukudoksesta muodostunut elin, yksittäinen luu
**luukudos**: luu | tukikudoksen laji, jonka soluväliaineeseen on kiteytynyt runsaasti kalsiumhydroksiapatiittia; ks. myös hammasluu

**Comment by mirmaid** [comment]
Kannatan luusto partOf luu -suhteen poistoa. Onko luu YK luukudokset -suhde ok? Käytännössä YSOssa luu ja luukudokset ovat Lääketieteen termien näkökulmasta synonyymeja, koska luu ei viittaa yksittäisiin luihin. Toisaalta luukudoksia on erilaisia, joten luukudokset-termi puoltaa myös paikkaansa.

**Comment by YSO-kokous** [comment]
Poistetaan partOf luu & tutkitaan vielä luu ja luukudokset -käsitteiden yhdistämistä.

**Comment by mariaforsen** [comment]
YSOssa nyt:
luu=ben (benvävnader)
luusto=benstomme
luukudokset=benvävnader
(jalat=ben (extremiteter))
Eli ruotsiksi täytyy olla tarkenne ben=luu-termillä, ja nykytilanne että on sekä "benvävnader" että "ben (benvävnader)" on sekava/päällekkäinen.

**Comment by jarmosaarikko** [comment]
luu (luonnonmateriaalit) on silti eri käsite kuin elävä luu  eli luukudos. Mielestäni sanastossa pitäisi olla molemmat

**Comment by mariaforsen** [comment]
Jos halutaan luu materiaalina niin tarvitaan tosiaan ihan uutta käsitettä tai selkeä muutos luu > luu (materiaalit) tms. jotta voidaan tehdä samanlainen rajaus myös ruotsiksi.

**Comment by mirmaid** [comment]
Sanastossa on _luulöydöt_ ja _luutyöt_, joten en näe tarvetta luu-käsitteelle muussa kuin lääketieteen yhteydessä. Ohjaustermejä voisi ehkä lisätä (luut (arkeologia) KÄ luulöydöt yms.).

_Luu_ (yleisesti luuaines) ja _luukudokset_ (kuoriluu, hohkaluu) on ollut omassa käytössä aika toimiva termipari, mutta jos nämä pitää yhdistää, niin ehkä sitten otetaan esim. nuo MeSHistä löytyvät kudostyypit erikseen.

**Comment by YSO-kokous** [comment]
### Päätökset
luu KT luukudokset  ST kuoriluu, hohkaluu
luu (käsityöt) KÄ luutyöt
luu (arkeologia) KÄ luulöydöt
