### ISSUE TITLE
sosiaalinen oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7932]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sosiaalinen oppiminen](http://www.yso.fi/onto/ysa/Y98951) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään myös ryhmään: 17 Eläintiede 

#### Perustelut ehdotukselle   

Sosiaalisen oppimisen (social learning) käsitettä käytetään myös, kun tutkitaan eläinten käyttäytymistä etologiassa ja vertailevassa psykologiassa. https://en.wikipedia.org/wiki/Social_learning_in_animals

Eläinten sosiaalisen oppimisen tutkimus jakaa samoja perusperiaatteita Banduran sosiaalisen oppimisen teorian kanssa, kuten matkimisen/jäljittelyn keskeinen asema oppimisessa. Voisikohan samaa asiasanaa siis ohjata käyttämään myös eläinten käyttäytymisen tapauksessa, vai tarvitaanko erillinen asiasana? Finnasta löytyy joitakin esimerkkejä joissa tätä asiasanaa on jo käytetty eläinten käyttäytymisen yhteydessä, esim. https://finna.fi/Record/utu.9911940005405971

Jos ei tarvita uutta asiasanaa, niin "sosiaalinen oppiminen" olisi hyvä lisätä myös luokkaan 17 Eläintiede. 

#### Ehdottajan organisaatio   

Jyväskylän yliopisto

**Comment by YSO-kokous** [comment]
Lisätään ryhmä 17, ei muita muutoksia.
