### ISSUE TITLE
Kytölä (Lahti)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7933]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kytölä (Lahti) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Alue Alasenjärven "takana" 

**Ehdottajan organisaatio:** Kansalliskirjasto

**Comment by mirmaid** [comment]
Myös Pesäkallio (Lahti) ja Viuha (Lahti)
