### ISSUE TITLE
solunulkoiset vesikkelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7934]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

solunulkoiset vesikkelit 

#### Ehdotettu termi englanniksi   

extracellular vesicles 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Solunulkoiset_vesikkelit
Solunulkoiset vesikkelit (extracellular vesicles, EV), mukaan lukien eksosomit, mikrovesikkelit ja apoptoottiset kappaleet ovat solujen tuottamia kalvorakkuloita, joita on löydetty ja eristetty useista lähteistä, kuten veren plasmasta, virtsasta ja soluviljelmien kasvatusnesteestä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Extracellular vesicles : prospects in prostate cancer biomarker discovery and drug delivery  ISBN 978-951-51-2964-2 

**Termiehdotus Fintossa:** [solunulkoiset vesikkelit](http://finto.fi/yse/fi/page/Y507934)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

FinMeSH: ekstrasellulaariset vesikkelit. Ehdotettu muoto on käytetympi Googlella.

**Comment by mariaforsen** [comment]
Sv. extracellulära vesiklar

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
