### ISSUE TITLE
tietoverkkotekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7935]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tietoverkkotekniikka 

#### Ehdotettu termi englanniksi   

networking technology 

#### Tarkoitusta täsmentävä selite   

Aalto-yliopiston Sähkötekniikan korkeakoulun Tietoliikenne- ja tietoverkkotekniikan laitokselta (Department of Communications and Networking) voi valmistua tohtoriksi tietoverkkotekniikan alalta. Laitoksen kotisivu löytyy osoitteesta https://www.aalto.fi/fi/tietoliikenne-ja-tietoverkkotekniikan-laitos-comnet 

#### Perustelut ehdotukselle   

Aalto-yliopistosta valmistuu joka vuosi useita väitöskirjoja tältä alalta. Teen väittelijöistä auktoriteettitietueet Asteri-tietokantaan ja väittelijän alaa on vaikea kuvailla, kun sopiva termi puuttuu YSOsta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-60-8928-7, tietoja väitöskirjan alasta: https://www.aalto.fi/fi/tapahtumat/vaitos-tietoverkkotekniikan-alalta-di-saba-ahsan 

**Ehdottajan organisaatio:** Aalto-yliopisto **Termiehdotus Fintossa:** [tietoverkkotekniikka](http://finto.fi/yse/fi/page/Y507935)

**Comment by mirmaid** [comment]
Sanastossa on _tietoliikennetekniikka_.

_Tietoliikennetekniikka (myös teletekniikka) on tietotekniikkaan liittyvä aihealue, joka käsittelee tietoliikenteeseen tarkoitettujen verkkojen tekniikoita, suunnittelua ja ylläpitoa._ https://fi.wikipedia.org/wiki/Tietoliikennetekniikka

**Comment by mariaforsen** [comment]
Sv. datanätverksteknik

**Comment by YSO-kokous** [comment]
Hyväksytään:
tietoverkkotekniikka KÄYTÄ tietoliikennetekniikka
