### ISSUE TITLE
tietojärjestelmätiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7936]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tietojärjestelmätiede 

#### Ehdotettu termi englanniksi   

information systems science (oppiaineen englanninkielinen nimi Aalto-yliopistossa ja Turun yliopistossa) / information systems (oppiaineen nimi Åbo Akademissa) 

#### Tarkoitusta täsmentävä selite   

Määritelmä löytyy esim. täältä: https://www.jyu.fi/it/fi/ohjeita-opiskelijalle/muiden-tiedekuntien-opiskelijoille/tietojarjestelmatiede 

#### Perustelut ehdotukselle   

Tästä aineesta valmistuu väitöskirjoja Åbo Akademista, Turun yliopistosta, Jyväskylän yliopistosta, Vaasan yliopistosta ja Aalto-yliopistosta. Itse teen Aalto-yliopiston väittelijöistä auktoriteettitietueita ja tarvitsen tätä käsitettä kuvaamaan henkilön toiminta-alaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. Bikesh Raj Upretin auktoriteettitietue Asterissa 

**Ehdottajan organisaatio:** Aalto-yliopisto **Termiehdotus Fintossa:** [tietojärjestelmätiede](http://finto.fi/yse/fi/page/Y507936)

**Comment by mirmaid** [comment]
16 viitettä Melindassa.

YSOssa on _tietojenkäsittelytieteet_. _Tietojenkäsittelytiede, myös tietojenkäsittelyoppi, on tieteenala, joka tutkii tietotekniikkaan ja sen käyttöön liittyviä kysymyksiä, muun muassa tiedon tallennusta, prosessointia, esittämistä ja siirtämistä. Vain hieman yleistäen tietojenkäsittelytiede tutkii sitä, mitä ylimalkaan voidaan laskea ja miten se käy parhaiten päinsä käytettävissä olevien resurssien puitteissa._ https://fi.wikipedia.org/wiki/Tietojenk%C3%A4sittelytiede

_Tietojärjestelmätiede (engl. information systems) on tieteenala, joka tarkastelee tietojärjestelmien kehittämistä, sovelluksia, käyttöä, johtamista ja vaikutuksia eri konteksteissa. 
Tieto- ja viestintäteknologioiden nopean kehityksen myötä tietojärjestelmätiede keskittyy nykyään lähes pelkästään tarkastelemaan tietokoneita ja muita elektronisia medioita tietojenkäsittelyn välineinä. Kuitenkin tulee huomata, että tietojärjestelmätiede ei ole sidottu pelkästään tietokoneisiin, vaan käsittää myös manuaaliset metodit tiedon tallentamiseen, organisoimiseen, etsimiseen ja jakamiseen._ https://fi.wikipedia.org/wiki/Tietoj%C3%A4rjestelm%C3%A4tiede

https://fi.wikipedia.org/wiki/Tietoj%C3%A4rjestelm%C3%A4tiede - englanninkielinen vastine on Business informatics (?)

**Comment by osma** [comment]
Tietojärjestelmätiede on soveltavampi ja käytännönläheisempi, tietojenkäsittelytiede teoreettisempi ja abstraktimpi suuntaus. Olisin valmis hyväksymään tietojärjestelmätieteen tietojenkäsittelytiete(id)en alakäsitteeksi, mutta varmaan joku on tästä eri mieltä...

**Comment by osma** [comment]
Itse kun aikaanaan suoritin tietojenkäsittelytieteen opintoja HY:llä, osa kursseista käsitteli tietojärjestelmiä (tietokannat, käytettävyys ym) mutta sitten oli paljon muutakin, esimerkiksi laskennan teoriaa, algoritmeja ja tietorakenteita.

**Comment by ilona-x** [comment]
Treen yo:lla taas opiskeltiin aikanaan Tietojenkäsittelytieteiden laitoksella tietojenkäsittelyoppia, ja osa kursseista käsitteli tietojärjestelmiä. 🤓

**Comment by mariaforsen** [comment]
Sv. systemvetenskap ET informationssystem (vetenskaper)

**Comment by ilona-x** [comment]
"Systemvetenskap (eng. information systems) är den tvärvetenskapliga studien av informationssystem inklusive människor och verksamhetsprocesser, i synnerhet affärssystem och andra administrativa system."
https://sv.wikipedia.org/wiki/Systemvetenskap

**Comment by YSO-kokous** [comment]
Otetaan sanastoon. Yläkäsitteeksi tietojenkäsittelytieteet.

**Comment by mariaforsen** [comment]
Eng. information systems (science) ?
