### ISSUE TITLE
Yleissopimus vammaisten henkilöiden oikeuksista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7937]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Yleissopimus vammaisten henkilöiden oikeuksista](http://www.yso.fi/onto/ysa/Y166456) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT vammaissopimus 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
