### ISSUE TITLE
biotuotetekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7938]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

biotuotetekniikka 

#### Ehdotettu termi ruotsiksi   

bioproduktteknologi (ks. https://www.finlex.fi/sv/laki/alkup/2009/20091164) 

#### Ehdotettu termi englanniksi   

bioproduct technology 

#### Vastaava käsite muussa sanastossa   

Wikipedia : biotuotetekniikka 

#### Tarkoitusta täsmentävä selite   

Biotuotetekniikka tutkii ja kehittää uusiutuvista materiaaleista eli biomassasta kestäviä tuotantoratkaisuja teollisuuden tarpeisiin (Wikipedia) 

#### Perustelut ehdotukselle   

Useiden ammattikorkeakoulujen ohella biotuotetekniikkaa voi opiskella Tampereen yliopistossa ja Aalto-yliopistossa. Alalta voi myös valmistua tohtoriksi. Tarvitsen käsitettä tehdessäni Aalto-yliopiston väittelijöistä auktoriteettitietueita Asteri-tietokantaan, väittelijöiden toiminta-alan kuvaamiseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. näiden henkilöiden Asteri-tietueet: Jukkola, Annamari; Lucenius, Jessica, Phiri, Josphat 

**Ehdottajan organisaatio:** Aalto-yliopisto **Termiehdotus Fintossa:** [biotuotetekniikka](http://finto.fi/yse/fi/page/Y507938)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

Suhde _biotekniikkaan_? https://www.aalto.fi/fi/biotuotteiden-ja-biotekniikan-laitos

**Comment by ilona-x** [comment]
"Bioproducts engineering or bioprocess engineering refers to engineering of bio-products from renewable bioresources. "
https://en.wikipedia.org/wiki/Bioproducts_engineering

"Bioprocess engineering, also biochemical engineering, is a specialization of chemical engineering or Biological engineering,"
https://en.wikipedia.org/wiki/Bioprocess_engineering

**Comment by mirmaid** [comment]
_Biotechnology is a broad area of biology, involving the use of living systems and organisms to develop or make products. Depending on the tools and applications, it often overlaps with related scientific fields. In the late 20th and early 21st centuries, biotechnology has expanded to include new and diverse sciences, such as genomics, recombinant gene techniques, applied immunology, and development of pharmaceutical therapies and diagnostic tests._ https://en.wikipedia.org/wiki/Biotechnology

Esim. lääketieteen osalta _biotekniikka_ ei (välttämättä) ole tuotteiden kehittämistä, mutta olettaisin _biotuotetekniikan_ kuitenkin sisältyvän biotekniikkaan. Lähinnä mietin, tulisiko tarkempaa termiä käytettyä kovinkaan paljon tilanteissa, joissa sitä ei mainita näkyvästi aineistossa.

**Comment by mariaforsen** [comment]
Bioproduktteknik/teknologi vain vähän ja Suomessa. Eikö voi käyttää  biotekniikka + tuotteet?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi:
biotuotetekniikka KÄYTÄ biotekniikka

Biotuotetekniikka vahvasti päällekkäinen biotekniikan kanssa.
