### ISSUE TITLE
ferritiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7939]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ferritiini 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Markers of iron metabolism and adipose tissue dysfunction in metabolic syndrome and in association with lipoprotein particle size and concentration 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ferritiini](http://finto.fi/yse/fi/page/Y507939)

**Comment by ilona-x** [comment]
FinMeSH: ferritiini http://www.yso.fi/onto/mesh/D005293
LCSH: Ferritin http://id.loc.gov/authorities/subjects/sh85047870

**Comment by mariaforsen** [comment]
Sv. ferritin
