### ISSUE TITLE
erytropoietiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7940]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

erytropoietiini 

#### Vaihtoehtoiset termit ja ilmaisut   

erytropoetiini (?) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Markers of iron metabolism and adipose tissue dysfunction in metabolic syndrome and in association with lipoprotein particle size and concentration 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [erytropoietiini](http://finto.fi/yse/fi/page/Y507940)

**Comment by mirmaid** [comment]
Myös _Post-translational prolyl 4-hydroxylation_

**Comment by mariaforsen** [comment]
Sv. erytropoietin ET erytropoetin, epo

**Comment by LeKorsu** [comment]
KT epo(hormoni)?
