### ISSUE TITLE
verkkokalvon pigmenttiepiteeli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7942]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

verkkokalvon pigmenttiepiteeli 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Inflammasome signaling and its regulation in human retinal pigment epithelial cells with dysfunctional intracellular clearance 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [verkkokalvon pigmenttiepiteeli](http://finto.fi/yse/fi/page/Y507942)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D055213 (2 viitettä Melindassa)

Lääketieteen termit: verkkokalvon pigmenttiepiteelisolu: _silmän verkkokalvon →pigmenttiepiteelin valoaistinsoluja ravitsevia ja huoltavia soluja_

**Comment by mariaforsen** [comment]
Sv. näthinnans pigmentepitel

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
