### ISSUE TITLE
alfalinoleenihappo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7943]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alfalinoleenihappo 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

ish and camelina sativa oil – effects on fatty acid composition of blood lipid fractions, lipoprotein subclasses and pro- and anti-atherogenic lipoprotein functions 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [alfalinoleenihappo](http://finto.fi/yse/fi/page/Y507943)

**Comment by mirmaid** [comment]
Ehkä myös camelinaöljy ja ruistankio.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Alfalinoleenihappo

FinMeSH: alfa-linoleenihappo, http://www.yso.fi/onto/mesh/D017962

**Comment by mirmaid** [comment]
_Ruistankio_ on Kassussa, http://www.yso.fi/onto/kassu/k51565
https://laji.fi/taxon/MX.38444

N. 40 viitettä Melindassa.

**Comment by mirmaid** [comment]
https://www3.uef.fi/-/camelinaoljy-paransi-veren-rasva-arvoja

**Comment by mariaforsen** [comment]
Sv. 
-oljedådra
-camelinaolja
-alfa-linolensyra ET alfalinolensyra

**Comment by ilona-x** [comment]
Eli tässä issuessa siis 3 erillistä ehdotusta: **alfalinoleenihappo**, **ruistankio** ja **camelinaöljy**.

**alpha-linolenic acid** https://www.wikidata.org/wiki/Q256502
LCSH: vain laajempi termi Linolenic acids http://id.loc.gov/authorities/subjects/sh92003722

**Camelina sativa** https://www.wikidata.org/wiki/Q163958
LCSH: sativa http://id.loc.gov/authorities/subjects/sh2008000808

**Camelina oil** https://www.wikidata.org/wiki/Q496049

**Comment by mirmaid** [comment]
Tässä tapauksessa sen verran tiiviisti nivoutuvat yhteen, ettei tuntunut järkevältä lähteä jokaisesta täyttämään erillistä lomaketta.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon:
_ruistankio_ [ohjaustermiksi _kitupellava_]
_camelinaöljy_
_alfalinoleenihappo_ [ei väliviivalla]
