### ISSUE TITLE
kiinnipitoterapia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7944]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kiinnipitoterapia](http://www.yso.fi/onto/ysa/Y107305) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

> kiinnipito / kiinnipitäminen 

#### Perustelut ehdotukselle   

https://thl.fi/fi/web/lastensuojelun-kasikirja/tyoprosessi/sijaishuolto/rajoitukset-sijaishuollossa/kiinnipitaminen 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by LeKorsu** [comment]
Tarvitseeko jonkin tarkenteen, ettei tätä aleta käyttää poliisin toiminnan yhteydessä?

**Comment by ilona-x** [comment]
Tai jääkiekon yhteydessä 😄 🏒 
fi        kiinnipitäminen <jääkiekko>
sv       fasthållning <ishockey>
en      holding
Källa: Finsk-svensk-finsk idrottsordlista (Forskningscentralen för de inhemska språken, 2005)
https://termipankki.fi/tepa/sv/s%C3%B6k/kiinnipit%C3%A4minen

**Comment by ilona-x** [comment]
hoidollinen kiinnipitäminen (psykiatria) https://fi.wikipedia.org/wiki/Hoidollinen_kiinnipit%C3%A4minen_(psykiatria)

**Comment by YSO-kokous** [comment]
Otetaan käytettäväksi termiksi hoidollinen kiinnipitäminen, ohjaustermiksi kiinnipitoterapia.

**Comment by mariaforsen** [comment]
Nämä ovat kyllä aika eri asioita, siis holdingterapi/kiinnipitoterapia ja hoidollinen kiinnipito. Melindassa on nyt esim. Pieni halauskirja ja Holdingterapian tutkimus- ja kehittämishankkeen raportti vuodelta 1993  kuvailtu tällä asiasanalla. Jos näihin tietueisiin tulee sen sijaan termi hoidollinen kiinnipito, se taitaa olla virheellistä tietoa.

**Comment by mirmaid** [comment]
Käyttö ei ole ihan johdonmukaisesti erillään, esim. _Tästä lapsen rajoittamiseen liittyvästä fyysisestä kosketuksesta  olen  kuullut  puhuttavan päiväkodeissa  hyvin  monella  eri  termillä  kuten  holding,  terapeuttinen  kiinnipito,  sylihoito,  holding-terapia  ja  rajoittaminen._ https://jyx.jyu.fi/bitstream/handle/123456789/43391/1/URN%3ANBN%3Afi%3Ajyu-201405121695.pdf

Hoidollinen kiinnipito on käännetty aineistoissa eng. therapeutic holding.

On myös mahdollista jättää ohjaustermi pois? (Ja toki myös ottaa holding-terapia erikseen, jos tarvetta.)

**Comment by mariaforsen** [comment]
Kannatan erilläänpitoa.

**Comment by ilona-x** [comment]
^Jos päätetään ottaa sanastoon molemmat, niin Melinda-korjausten kannalta kätevintä varmaan palauttaa olemassa oleva termi muotoon kiinnipitoterapia, niin ei tarvitse korjata tietueita. YSOssa siis oli alunperin kiinnipitoterapia, joka viimeksi muutettiin muotoon hoidollinen kiinnipitäminen.

**Comment by mirmaid** [comment]
Olisiko parempi kuitenkin ottaa toinen muodossa _holding-terapia_, jos menisi edes vähän vähemmän sekaisin? Tosin kun viitteitä katsoo niin ei ihan helppoa aina erotella. Toisaalta sellainen sylissäpito mitä täällä ehkä harrastetaan on toivottavasti erilaista kuin varsinainen holding-terapia, jossa lasta pakotetaan olemaan sylissä/aloillaan ym. että ei ehkä niinkään ole hyvä...

**Comment by ilona-x** [comment]
"The common form of attachment therapy is holding therapy, in which a child is firmly held (or lain upon) by therapists or parents."
https://en.wikipedia.org/wiki/Attachment_therapy

**Comment by mirmaid** [comment]
^ Tuo just kuulostaa melko kyseenalaiselta ja onkin kai saanut laajaa kritiikkiä. Esim. _Pieni halauskirja_ tuskin liittyy mitenkään varsinaiseen holding-terapiaankaan.

Ehdotan että otetaan _hoidollinen kiinnipitäminen_ ilman ohjaustermejä, korjataan viitteet ja katsotaan mitä jää jäljelle.

**Comment by mariaforsen** [comment]
Pieni halauskirja ei liity mihinkään noista. 
Hoidollinen kiinnipitäminen=fasthållning (vård) on eri asia kuin holdingterapi. https://www.psykologiguiden.se/psykologilexikon/?Lookup=holding Kannatan siis nykyisen KTn poistamista (ja ottamista erillään JOS Melindassa on aineistoa holdingterapiasta), ja myös uuden ohjaustermin ottamista: kiinnipitäminen (hoito).

**Comment by mirmaid** [comment]
Tarkennus siis aikaisempaan: poistetaan _hoidollinen kiinnipitäminen_ -käsitteeltä nykyinen ohjaustermi ja lisätään Marian ehdottama kiinnipitäminen (hoito). Ei oteta tässä vaiheessa muuta, jos ei tarvetta ilmene viitteitä korjatessa.

**Comment by YSO-kokous** [comment]
Poistetaan käsitteeltä ohjaustermi kiinnipitoterapia. Otetaan uudeksi ohjaustermiksi kiinnipitäminen (hoito).
