### ISSUE TITLE
gliasolulinjaperäinen hermokasvutekijä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7945]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gliasolulinjaperäinen hermokasvutekijä 

#### Ehdotettu termi englanniksi   

glial cell line-derived neurotrophic factor 

#### Vaihtoehtoiset termit ja ilmaisut   

GDNF 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Glial_cell_line-derived_neurotrophic_factor
Glial cell-derived neurotrophic factor (GDNF) is a protein that, in humans, is encoded by the GDNF gene.[5] GDNF is a small protein that potently promotes the survival of many types of neurons. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-3950-4 

**Termiehdotus Fintossa:** [gliasolulinjaperäinen hermokasvutekijä](http://finto.fi/yse/fi/page/Y507945)

**Comment by mirmaid** [comment]
FinMeSH: gliasolulinjasta peräisin oleva neurotrooppinen tekijä, http://www.yso.fi/onto/mesh/D051100 (3 viitettä Melindassa)

Googlella enemmän ehdotettua muotoa.

**Comment by ilona-x** [comment]
YSOssa on hermokasvutekijät http://www.yso.fi/onto/yso/p37764, jolla ei ole vielä alakäsitteitä. Hermokasvutekijät myös FinMeSHissä http://www.yso.fi/onto/mesh/D009414

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa gliasolulinjaperäinen hermokasvutekijä.

**Comment by mariaforsen** [comment]
Sv. GDNF ET gliacell-deriverad nervtillväxtfaktor
