### ISSUE TITLE
Atrium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7946]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Atrium](http://www.yso.fi/onto/ysa/Y175528) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne tai ainakin määritelmä 

#### Perustelut ehdotukselle   

On monimerkityksinen ja käytetty myös muissa merkityksissä kuin Atrium (Turku). Englanniksi ja ruotsiksi jo tarkenteita.

**Comment by ilona-x** [comment]
YSAssa ollut huomautus: "Arkkitehti Erik Bryggmanin suunnittelema asuin- ja liiketalo Turussa"

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi "Atrium (Turku)".
