### ISSUE TITLE
Fontellin talo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7947]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Fontellin talo](http://www.yso.fi/onto/ysa/Y174332) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä 

#### Perustelut ehdotukselle   

Myös Pietarsaaressa oli "Fontellin talo". Ruotsiksi on tarkenne (Villmanstrand).

**Comment by ilona-x** [comment]
YSAssa ollut huomautus: "Kulttuurihistoriallinen rakennus Lappeenrannassa; keisari Aleksanteri III ja keisarinna Maria Fedorovna majoitettiin taloon Lappeenrannan vierailuillaan 1885 ja 1891. Talon kunnostuksen toteutti tuolloin arkkitehti Jac. Ahrenberg. Alkuperäinen talo tuhoutui tulipalossa 1929. Paikalle valmistui 1930 Lars Sonckin suunnittelema rakennus"

**Comment by YSO-kokous** [comment]
Muutetaan muotoon "Fontellin talo (Lappeenranta)".
