### ISSUE TITLE
piccolohuilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7950]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[piccolohuilu](http://www.yso.fi/onto/ysa/Y101687) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termiksi "piccolo". 

#### Perustelut ehdotukselle   

YSO-ontologian termi on ristiriidassa SEKO-sanaston termin kanssa: http://urn.fi/urn:nbn:fi:au:seko:00767

KÄYTETTÄVÄ TERMI (SEKO)
piccolo

OHJAUSTERMIT (SEKO)
flauto piccolo
kleine Flöte
ottavino (huilu)
petite flûte
piccolaflöjt
piccolohuilu
picc (piccolo)
pikkolohuilu 

#### Ehdottajan organisaatio   

Helsingin Konservatorio

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by jtuohini** [comment]
Yson puolella termille tarvittaneen määritelmä, ettei vain käy niin, että sanastoon laitetaan automaattisesti viittaus monikkomuodosta (_piccolot_ KÄ **piccolo**) ja joku haluaakin kuvailla vaikkapa valokuvaa, joka esittää hotellipoikaa. [https://www.kielitoimistonsanakirja.fi/#/pikkolo]
 
Lisäksi melkein ehdottaisiin, että muutetaankin sekä Ysossa että Sekossa soitinta kuvaava termi Kielitoimiston suosittelemaan yksiselitteiseen muotoon _**pikkolohuilu**_ [https://www.kielitoimistonsanakirja.fi/#/pikkolohuilu].

**Comment by asormune** [comment]
Seko:ssa on jo termit pikkolotrumpetti, pikkoloviulu, pikkolobanjo, niin olisi samassa linjassa.

**Comment by MUUSA-kokous** [comment]
Muusa peruu aiemman kantansa ja jättää asian tässä vaiheessa hautumaan.

**Comment by YSO-kokous** [comment]
Ei muutoksia.
