### ISSUE TITLE
Jyväskylän suojeluskuntatalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7951]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Jyväskylän suojeluskuntatalo](http://www.yso.fi/onto/ysa/Y109333) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Valtiontalo (Jyväskylä) tai korvattuna terminä 

#### Perustelut ehdotukselle   

Nykyinen nimi Valtiontalo
https://fi.wikipedia.org/wiki/Valtiontalo

**Comment by YSO-kokous** [comment]
Muutetaan nimi muotoon Valtiontalo (Jyväskylä).
