### ISSUE TITLE
Kiimingin kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7952]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kiimingin kirkko 

#### Perustelut ehdotukselle   

Tarvitaan eri teosten kuvailussa, puuttuu tällä hetkellä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kulttuurijuttuja Pohjois-Suomesta / Kari Holma. 

**Ehdottajan organisaatio:** Oulu kaupungin kirjasto **Termiehdotus Fintossa:** [Kiimingin kirkko](http://finto.fi/yse/fi/page/Y507952)

**Comment by mariaforsen** [comment]
Sv. Kiminge kyrka
