### ISSUE TITLE
Ylikiimingin kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7953]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ylikiimingin kirkko 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa, puuttuu tällä hetkellä Ysosta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mm. Kulttuurijuttuja Pohjois-Suomesta / Kari Holma. 

**Ehdottajan organisaatio:** Oulun kaupungin kirjasto **Termiehdotus Fintossa:** [Ylikiimingin kirkko](http://finto.fi/yse/fi/page/Y507953)

**Comment by mariaforsen** [comment]
Sv. Överkiminge kyrka ET Ylikiiminki kyrka
