### ISSUE TITLE
Kuhlefeltska huset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7954]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuhlefeltska huset](http://www.yso.fi/onto/ysa/Y191529) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetäänkö, KÄYTÄ Villa Boström? 

#### Perustelut ehdotukselle   

Samalla talolla ei varmaan pidä olla kaksi eri termiä YSOssa. Lisätäänkö myös määritelmä: "Talo Pietarsaaressa" tms., koska myös Uudellamaalla näyttää olevan "Kuhlefeltska huset".

**Comment by ilona-x** [comment]
YSA:n puolella ollut määritelmä "Kulttuurihistoriallinen asuinrakennus Pietarsaaressa. Talon nimi oli alunperin omistajaperheen mukaan Kuhlefeltska huset, mutta vaihtui 1980-luvun alussa Villa Boströmiksi"

**Comment by YSO-kokous** [comment]
Yhdistetään. Käytettävä termi Villa Boström.
