### ISSUE TITLE
Pikkuparlamentti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7955]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pikkuparlamentti](http://www.yso.fi/onto/ysa/Y164971) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä tai tarkenne 

#### Perustelut ehdotukselle   

Käytetty myös muusta kuin rakennuksesta

**Comment by ilona-x** [comment]
YSAssa ollut määritelmä "Eduskuntatalon v. 2004 valmistunut lisärakennus"

**Comment by YSO-kokous** [comment]
Muutetaan muotoon "Pikkuparlamentti (Eduskuntatalo)"
