### ISSUE TITLE
vapaaehtoistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7957]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vapaaehtoistyö](http://www.yso.fi/onto/ysa/Y100079) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisättäisiin synonyymiksi vapaaehtoistoiminta 

#### Perustelut ehdotukselle   

Helsingin kaupunki on linjannut, että vapaaehtoistyöstä käytetään sanaa vapaaehtoistoiminta. Vapaaehtoistoimintaa ei nimenomaan haluta sekoittaa työntekoon, sillä vapaaehtoiset saattavat tehdä yhteistyötä kaupungin henkilökunnan kanssa, mutta pyrkimyksenä on selvästi erottaa työntekijöiden vastuut ja sitoutuminen vapaaehtoisten mahdollisuudesta valita itse omat tehtävät, vastuut ja ajankohta vapaaehtoisena toimimiseen.
Olemme parhaillaan tekemässä uutta vapaaehtoistoiminnan sivustoa, joka aukeaa tähän osoitteeseen https://vapaaehtoistoiminta.hel.fi/. Tässä vaiheessa siis vasta etusivu on julki.  
Tarvitsisimme myös sanan lisäämisen YSO:n sanastoon, jotta LinkedEvents alusta, joka käyttää YSO:n sanastoa, toimisi meidän tarpeisiimme sopivalla tavalla. 

#### Ehdottajan organisaatio   

Helsingin kaupunki

**Comment by ilona-x** [comment]
vapaaehtoistoiminta näyttää jo olevan vapaaehtoistyön ohjausterminä http://www.yso.fi/onto/yso/p3050

**Comment by tpalonen** [comment]
te-palvelu.fi puhuu vapaaehtoistyöstä, ei vapaaehtoistoiminnasta:
https://www.te-palvelut.fi/te/fi/tyonhakijalle/jos_jaat_tyottomaksi/tyottomyysturva/vapaaehtoistyo_talkootyo/index.html
kela.fi-sivulla (poislukien kysykelasta.kela.fi) vapaaehtoistyö esiintyy 49 kertaa, vapaaehtoistoiminta 6 kertaa.
https://www.te-palvelut.fi/te/fi/tyonhakijalle/jos_jaat_tyottomaksi/tyottomyysturva/vapaaehtoistyo_talkootyo/index.html

**Comment by YSO-kokous** [comment]
Ei muutoksia.
