### ISSUE TITLE
Ritarihuone

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7958]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Ritarihuone](http://www.yso.fi/onto/ysa/Y110647) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko? 

#### Perustelut ehdotukselle   

Voi viitata myös Ruotsin Ritarihuoneeseen, ks. esim. https://www.riddarhuset.se/sprak/suomi/ ja on myös käytetty Melindassa tässä merkityksessä. Huom. YSO myös ruotsiksi

**Comment by jtuohini** [comment]
Lisäksi pitää tehdä selväksi, viitataanko rakennuksiin vai yhteisöihin, joiden tarpeisiin kyseiset rakennukset ovat alkujaan tehdyt.

**Comment by mirmaid** [comment]
Auktorisoitu myös yhteisönä. Voisiko rakennus olla vain _Ritarihuone (Helsinki)_?
