### ISSUE TITLE
Sandbergin talo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7959]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Sandbergin talo](http://www.yso.fi/onto/ysa/Y187155) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö tarkenne? 

#### Perustelut ehdotukselle   

Ruotsiksi ja englanniksi on jo tarkenne. On mahdollista sekoittaa, esim. Turussa on myös "Sandbergin talo" https://aamuset.fi/artikkeli/1613836476/Sandbergin+talo+oppilasvoimin+entiseen+loistoonsa

**Comment by LeKorsu** [comment]
Juu, tarkennetta kehiin myös suomenkieliseen: Sandbergin talo (Tampere).

**Comment by ilona-x** [comment]
YSAssa ollut huomautus "Kulttuurihistoriallinen uusrenessanssityylinen liiketalo Tampereeen Keskustorilla. Talon suunnitteli kaupunginarkkitehti F. L. Calonius ja se valmistui 1882, siipirakennukset 1891 ja 1897", jota ei ole YSOssa
