### ISSUE TITLE
Satulinna

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7961]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Satulinna](http://www.yso.fi/onto/ysa/Y148833) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaanko? 

#### Perustelut ehdotukselle   

Melindassa käytetty myös esim. Espoossa olevasta "Satulinnasta"

**Comment by ilona-x** [comment]
YSAssa ollut huomautus "Hyvinvointikeskus, hotelli, ravintola ja kokouspaikka Hirvensalmella"

**Comment by YSO-kokous** [comment]
Käytettävä termi "Satulinna (Hirvensalmi)".
