### ISSUE TITLE
evankeliumit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7962]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[evankeliumit](http://www.yso.fi/onto/ysa/Y95146) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Melindassa ja paikallistietokannoissa on pilvin pimein evankeliumikäännöksiä, joihin on laitettu asiasanaksi "evankeliumit", vaikka tieto kuuluisi 655-kenttään ja siten SLM:ään. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Onko _evankeliumit_ kuitenkaan varsinainen lajityyppi?

**Comment by AuHo22** [comment]
Myöskään psalmit (tekstit) ei ole SLM-sanastossa, vaikka niitä julkaistaan itsenäisesti / valikoimina? Ja sama koskee apokryfejä.

**Comment by mirmaid** [comment]
Seuraava kokous.

**Comment by jtuohini** [comment]
"Evankeliumit (kreikaksi ευαγγελιον, euangelion, suomeksi ”ilosanoma” tai ”hyvä sanoma”) ovat Jeesuksen opetuksista, teoista, kuolemasta ja tyhjän haudan löytymisestä kertovia kirjoja." [https://fi.wikipedia.org/wiki/Evankeliumit] Samalla sivulla on listattu joukko evankeliumeja, joita sisältävien julkaisujen metatietoihin olisi luonteva laittaa 655-kenttään termi **_evankeliumit_** – paljon ennemmin kuin 650-kenttään, joissa termiä nyt on käytetty!

**Comment by mirmaid** [comment]
Evankeliumit, pyhät kirjat, apokryfit, psalmit (tekstit) / SLM.

**Comment by mirmaid** [comment]
Psalmit (tekstit) LCGFT-linkitys?
http://id.loc.gov/authorities/genreForms/gf2015026079
http://id.loc.gov/authorities/genreForms/gf2015026080

https://github.com/Finto-ehdotus/YSE/issues/5793

**Comment by jtuohini** [comment]
Tätä psalmiasiaa pitää varmaan miettiä erikseen: onko tarvetta psalmisävellyksiä kuvaavalle SLM-termille ja viitataanko psalmirunojen osalta psalmikokoelmiin eli psalttareihin vai vain yksittäisiin psalmeihin?

**Comment by mirmaid** [comment]
Psalmit (tekstit) LT uskonnolliset runot sekä YSOssa että SLM:ssä. RT pyhät kirjat.

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/genreForms/gf2015026079

**Comment by mirmaid** [comment]
Linkitys: http://id.loc.gov/authorities/genreForms/gf2015026079 (exact)
