### ISSUE TITLE
Turun vanha akatemiatalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7963]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Turun vanha akatemiatalo](http://www.yso.fi/onto/ysa/Y105699) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetäänkö KÄYTÄ Turun akatemiatalo ja poistetaan huomautus? 

#### Perustelut ehdotukselle   

Sanastossa myös Turun akatemiatalo. Huomautus:  Ks. Turun akatemiatalo. Sama kuin Turun akatemiatalo.

**Comment by YSO-kokous** [comment]
Yhdistetään. Käytettäväksi termiksi Turun akatemiatalo.
