### ISSUE TITLE
Tampereen taistelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7965]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tampereen taistelu 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tampereen taisteluista Pälkäneelle ja Hauholle 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Tampereen taistelu](http://finto.fi/yse/fi/page/Y507965)

**Comment by mariaforsen** [comment]
Sv. slaget om Tammerfors ET striden om Tammerfors

**Comment by LeKorsu** [comment]
Tarvitaanko ohjaustermiksi KT Tampereen valtaus?

**Comment by EsaMPKK** [comment]
> Tarvitaanko ohjaustermiksi KT Tampereen valtaus?

Voi lisätä, ohjarit selkiyttää aina.
