### ISSUE TITLE
tulipesät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7966]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tulipesät 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Computational Fluid Dynamics Modeling and Mathematical Optimization of Recovery Boilers 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tulipesät](http://finto.fi/yse/fi/page/Y507966)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja:
tulipesä: lieden, kiukaan tms. tila, jossa polttoaine palaa.

https://fi.wikipedia.org/wiki/Tulipes%C3%A4 - eiköhän näille kuitenkin riitä yksi käsite?

**Comment by mirmaid** [comment]
tulipesä=härd...

**Comment by YSO-kokous** [comment]
Hyväksytään käsite sanastoon.
Ei nähty tarvetta erottaa eri tyyppisiä tulipesiä toisistaan.

**Comment by mariaforsen** [comment]
Sv.  härdar

**Comment by mirmaid** [comment]
Diversity of soapstones
