### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7968]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Matrix 

#### Ehdotettu termi englanniksi   

The Matrix 

#### Ehdotettu termi ruotsiksi   

Matrix 

#### Vaihtoehtoiset termit ja ilmaisut   

Matrix-elokuva 

#### Vastaava käsite muussa sanastossa   

Matrix (Film) : https://portal.dnb.de/opac.htm?method=simpleSearch&cqlMode=true&query=nid%3D4780840-8 

#### Perustelut ehdotukselle   

Yksi maailman suosituimmista tieteiselokuvista, jolla on ollut merkittävä vaikutus populaarikulttuuriin maailmanlaajuisesti. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://authenticvegan.org/publishing/books/literary-arts/literary-arts-eng/seraph-an-extended-collection-of-poems/ 

#### Tarkoitusta täsmentävä selite   

Yhdysvaltalainen elokuva-trilogia (1999-2003), joka koostuu osista: The Matrix, The Matrix Reloaded, The Matrix Revolutions. 

**Ehdottajan organisaatio:** Authentic Vegan, Consulting and Publishing

**Comment by mirmaid** [comment]
YSOon ei auktorisoida yksittäisiä teoksia.
