### ISSUE TITLE
polaritonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7969]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

polaritonit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Surface Plasmons in Raman Sensing and Physical Nanophotonics 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [polaritonit](http://finto.fi/yse/fi/page/Y507969)

**Comment by mirmaid** [comment]
LCSH: Polaritons, http://id.loc.gov/authorities/subjects/sh85104144
https://en.wikipedia.org/wiki/Polariton
https://en.wikipedia.org/wiki/Surface_plasmon_polariton

**Comment by mariaforsen** [comment]
Sv. polaritoner

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
