### ISSUE TITLE
pintaplasmonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7970]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pintaplasmonit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Surface Plasmons in Raman Sensing and Physical Nanophotonics 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [pintaplasmonit](http://finto.fi/yse/fi/page/Y507970)

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

https://en.wikipedia.org/wiki/Surface_plasmon

LCSH: Surface plasmon resonance, http://id.loc.gov/authorities/subjects/sh2003004761

**Comment by mariaforsen** [comment]
Sv. ytplasmoner

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
