### ISSUE TITLE
valopulssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7973]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valopulssit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Novel Coatings for Tools, Instruments and Probes 

#### Perustelut ehdotukselle   

ja/tai laserpulssit 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [valopulssit](http://finto.fi/yse/fi/page/Y507973)

**Comment by mirmaid** [comment]
Myös _Coherence of pulsed light: theory, modeling..._ https://www3.uef.fi/ajassa/vaitostiedotteet/-/asset_publisher/g2ss1EfgtZyc/content/pulssitettu-valo-mahdollistaa-tulevaisuuden-teknologioita

**Comment by mirmaid** [comment]
Laserpulssit Melindassa 4 kertaa. 

LCSH: Laser pulses, Ultrashort http://id.loc.gov/authorities/subjects/sh85074782

https://en.wikipedia.org/wiki/Ultrashort_pulse

**Comment by mirmaid** [comment]
Päädyn ehkä itse kannattamaan termiä _laserpulssit_; _Ultrashort pulses are generally defined as laser pulses with durations in the scale of femtoseconds to a few of tens of picoseconds._ https://www.sciencedirect.com/topics/materials-science/ultrashort-pulse

**Comment by YSO-kokous** [comment]
Otetaan sanastoon _laserpulssit_.

**Comment by mariaforsen** [comment]
Sv. laserpulser ET ultrakorta laserpulser
