### ISSUE TITLE
nanopainatuslitografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7974]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nanopainatuslitografia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Advanced photonics with polymer waveguides 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [nanopainatuslitografia](http://finto.fi/yse/fi/page/Y507974)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Nanopainatuslitografia

LCSH: Nanoimprint lithography, http://id.loc.gov/authorities/subjects/sh2013001239
Löytyy myös laajempi Nanolithography, mutta tällä ei löydy suomeksi oikein mitään. Ruotsinkielinen wikipedia käsittelee nämä synonyymeina: https://sv.wikipedia.org/wiki/Nanolitografi. Englanninkielisessä wikipediassa on esitelty neljä nanolitografian tekniikkaa, joista yksi on nanopainatuslitografia. https://en.wikipedia.org/wiki/Nanolithography#Important_techniques

Melindassa kerran _nanolitografia_.

**Comment by mariaforsen** [comment]
Sv. nanolitografi ET nanotrycklitografi
https://en.wikipedia.org/wiki/Nanolithography
 https://sv.wikipedia.org/wiki/Nanolitografi

**Comment by YSO-kokous** [comment]
Nanolitografia on laajempi merkitykseltään ja siten laajakäyttöisempi. Ohjaustermiksi nanopainatuslitografia.
