### ISSUE TITLE
funktioavaruudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7975]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

funktioavaruudet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

On linear operators and their applications in complex function spaces of the unit disc 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [funktioavaruudet](http://finto.fi/yse/fi/page/Y507975)

**Comment by mirmaid** [comment]
11 viitettä Melindassa. 

LCSH: Function spaces, http://id.loc.gov/authorities/subjects/sh85052310

https://fi.wikipedia.org/wiki/Funktioavaruus

**Comment by mariaforsen** [comment]
Sv. funktionsrum

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
