### ISSUE TITLE
suosittelujärjestelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7976]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suosittelujärjestelmät](http://www.yso.fi/onto/ysa/Y203863) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT suosittelijajärjestelmät 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
