### ISSUE TITLE
infrapunaspektroskopia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7978]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

infrapunaspektroskopia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Infrared and nuclear magnetic resonance spectroscopic methods for salivary analysis 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [infrapunaspektroskopia](http://finto.fi/yse/fi/page/Y507978)

**Comment by mirmaid** [comment]
Sanastossa on tämän alakäsite, _lähi-infrapunaspektroskopia_.

LCSH: Infrared spectroscopy, http://id.loc.gov/authorities/subjects/sh85066329

_Infrapunaspektroskopia voidaan jakaa alueisiin käytetyn infrapunasäteilyalueen perusteella. Lähi-infrapunaspektroskopiassa käytetään aallonpituusaluetta 0,78–2,5 μm (aaltoluvut 12 800–4 000 cm-1), keskialueen infrapunaspektroskopiassa käytetään aallonpituuksia 2,5–50 μm (aaltoluvut 4 000–200 cm-1) ja kaukoinfrapunaspektroskopiassa käytetään aallonpituusaluetta 50–1 000 μm (aaltoluvut 200–10 cm-1). Yleisimmin käytetään keskialueen infrapunaspektroskopiaa._ https://fi.wikipedia.org/wiki/Infrapunaspektroskopia

18 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. infrarödspektroskopi ET IR-spektroskopi

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
