### ISSUE TITLE
otsa-ohimolohkorappeumat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7980]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[otsa-ohimolohkorappeumat](http://www.yso.fi/onto/ysa/Y178707) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT frontotemporaalilohkon rappeuma, frontotemporaalinen degeneraatio 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
MeSHissä käsitteen käytettävä termi _frontotemporaalilohkon rappeuma_, ohjaustermeinään _otsa- ja ohimolohkojen rappeutuminen_ sekä _otsa-ohimolohkorappeuma_.
http://www.yso.fi/onto/mesh/D057174

Myös _frontotemporaalinen degeneraatio_ Googlen perusteella melko yleinen termi.

**Comment by mirmaid** [comment]
^ Huomattavasti käytetympi kuin MeSHin päätermi.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotetut ohjaustermit.
