### ISSUE TITLE
ilmiölähtöinen oppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7981]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmiölähtöinen oppiminen 

#### Ehdotettu termi englanniksi   

Phenomenon Based Learning (PhenoBL) 

#### Ehdotettu termi ruotsiksi   

fenomenbaserat lärande 

#### Vaihtoehtoiset termit ja ilmaisut   

ilmiöoppiminen 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oppiminen](http://www.yso.fi/onto/yso/p2945) 

#### Assosiatiiviset (RT)   

[opetus](http://www.yso.fi/onto/yso/p2630) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Käytetty uudessa tutkimuksessa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi:jyu-202003032256 

**Ehdottajan organisaatio:** JYK **Termiehdotus Fintossa:** [ilmiölähtöinen oppiminen](http://finto.fi/yse/fi/page/Y507981)

**Comment by ilona-x** [comment]
aiemmat ehdotukset:
ilmiölähtöinen oppiminen https://github.com/Finto-ehdotus/YSE/issues/6533
ilmiöpohjainen oppiminen https://github.com/Finto-ehdotus/YSE/issues/4467

**Comment by mirmaid** [comment]
Melinda
ilmiölähtöinen oppiminen x 3
ilmiöpohjainen oppiminen x 4
ilmiöpohjainen opetus x 3
ilmiöoppiminen x 2

Googlella eniten viitteitä termillä _ilmiöoppiminen_, toiseksi eniten _ilmiöpohjainen oppiminen_.

https://fi.wikipedia.org/wiki/Ilmi%C3%B6pohjainen_oppiminen
https://www.oph.fi/fi/koulutus-ja-tutkinnot/ilmiomainen-ilmiomaista-ilmiomaisesti

**Comment by mariaforsen** [comment]
Joillakin suomalaisilla sivuilla käytetty "fenomenbaserat lärande" tai "fenomenbaserad inlärning"

**Comment by LeKorsu** [comment]
Kai tämä pitää ottaa, kun aikoinaan on otettu "ongelmalähtöinen oppiminen".  Lehtikielessä (lähteenä jälleen Sanoman arkisto) on ilmiöoppiminen käytetympi kuin ilmiölähtöinen oppiminen, mutta jonkin verran on myös ilmiöopetusta.

Mietin vaan, että mikä on seuraava ilmiölähtöinen asia, jota ehdotetaan, "ilmiölähteinen suunnittelu"??

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa ilmiöoppiminen. Googlen mukaan suosituin termimuoto. Opetushallitus puhuu myös ilmiöoppimisesta. Ohjaustermeiksi ilmiölähtöinen oppiminen ja ilmiöpohjainen oppiminen, sekä vastaavat *opetus-loppuiset.

**Comment by mariaforsen** [comment]
Sv. fenomenbaserat lärande ET fenomenbaserad inlärning, fenomeninlärning
