### ISSUE TITLE
endometriumablaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7982]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

endometriumablaatio 

#### Ehdotettu termi englanniksi   

endometrial ablation 

#### Vaihtoehtoiset termit ja ilmaisut   

kohdun limakalvon poisto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-3622-0 

#### Perustelut ehdotukselle   

Endometrial ablation is a surgical procedure that is used to remove (ablate) or destroy the endometrial lining of the uterus in women who have heavy menstrual bleeding. 
https://en.wikipedia.org/wiki/Endometrial_ablation 

**Termiehdotus Fintossa:** [endometriumablaatio](http://finto.fi/yse/fi/page/Y507982)

**Comment by mirmaid** [comment]
FinMeSH: kohdun limakalvon poistomenetelmät, http://www.yso.fi/onto/mesh/D055356 (2 viitettä Melindassa)

**Comment by mirmaid** [comment]
KT termoablaatio, endometriumin ablaatio (Googlella käytetyin muoto on termoablaatio, mutta se ei kata vanhempia menetelmiä)

**Comment by mariaforsen** [comment]
Sv. endometrieablation
