### ISSUE TITLE
humalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7985]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[humalat](http://www.yso.fi/onto/ysa/Y123455) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Laji.fi: suvun nimi on köynnöshumalat (Humulus), muutetaan käytettävä termi tai otetaan ohjaustermiksi 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.37978 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Kassussa tämä on humalat, Wikipediassa samoin humalat. Köynnöshumalat ohjaustermiksi?
http://www.yso.fi/onto/kassu/k52156
https://fi.wikipedia.org/wiki/Humalat
