### ISSUE TITLE
SLM / varhaisnuorten kirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7987]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM / varhaisnuorten kirjat 

#### Ehdotettu termi ruotsiksi   

sv. mellanåldersböcker 

#### Ehdotettu termi englanniksi   

middle-grade fiction 

#### Tarkoitusta täsmentävä selite   

"At the lower end of the age spectrum, fiction targeted to readers age 8-12 is referred to as middle-grade fiction" mm. Wikipedia ; "preteens" myös 

#### Perustelut ehdotukselle   

Myös nuorten aikuisten kirjat olemassa vastaavana ikäkausien välissä olevana terminä: Käytetään teoksista, jotka on tarkoitettu aikuistuville nuorille (SLM) - hyvinkin laajalti käytössä esimerkiksi Libriksen kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kaunokirjallisuuden kuvailussa ; nyt käytetty 385 varhaisnuoret 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [SLM / varhaisnuorten kirjat](http://finto.fi/yse/fi/page/Y507987)

**Comment by ilona-x** [comment]
aiemmat ehdotukset:
https://github.com/Finto-ehdotus/YSE/issues/7819
https://github.com/Finto-ehdotus/YSE/issues/6708

**Comment by AuHo22** [comment]
Kuvailussa hankaluus esiintyy siten, että jos tämänkaltaista termiä ei ole, niin joutuu joko valitsemaan lastenkirjallisuus- tai nuortenkirjallisuustermin välillä tai sitten käyttämään molempia ja sen lisäksi sitten vielä 385-kenttää. 
Mitä ilmeisemmin nuorten aikuisten kirjat -termi on aikoinaan otettu sanastoon tämän kaltaisen problematiikan takia. 
Aina voi olla rajanveto-ongelmia ikäkausien välillä, mutta hyvin selkeästi on myös ns. varhaisnuorille suunnattuja teoksia, itselleni tämä on tullut vastaan vahvasti englanninkielisen aineiston kohdalla, ja ruotsalainen aineisto on näköjään toinen vastaava, kun termikin on olemassa. 
Myös nuorten aikuisten kirjat -termin kanssa tarpeen vaatiessa käytetään myös nuortenkirjallisuus-termiä, mutta ei välttämättä. Eli varhaisnuorten kirjat -termi vastaavasti voi saada tuekseen joko nuortenkirjallisuus tai lastenkirjallisuus-termin riippuen mihin suuntaan se kallistuu.

**Comment by mirmaid** [comment]
Kauno-työryhmän käsittelyyn.

**Comment by ghost** [comment]
KAUNO-ryhmä keskusteli termistä, mutta ei lyönyt kantaansa vielä lukkoon. Ongelmalllisuudestaan huolimatta termille selvästi on tilausta, koska se nousee esiin uudestaan ja uudestaan, joten asiaa kannattaa pohtia. KAUNO-ryhmälle tullut viesti: Ruotsissa "mellanåldersböcker" on käytössä kohderyhmän 9-12 kirjoille, esim.  
https://haku.helmet.fi/iii/encore/record/C__Rb2442619
https://armas.btj.fi/request.php?id=f55f7189859e3777&pid=9789132211911&qtype=b

**Comment by mirmaid** [comment]
Jää termiehdotukseksi / SLM. Tarvittaessa kohderyhmän voi merkitä kenttään 385.

**Comment by AuHo22** [comment]
Mellanåldersböcker-issuessa sanottua: _"Varmaan tarvetta termille olisi siis (myös) SLM-sanastoon? Kohderyhmäkentässä tuon pystyisi kaunokirjallisuuden osalta ilmaisemaan jo nykyisellään ("385 __ |m Ikä |n age |a varhaisnuoret |2 ysa"), myös vuosien tarkkuudella ("521 1 |a 009-012")."_

Valitettavasti nykyjärjestelmissä yo. vaihtoehdot toimivat huonosti ja mahdollisesti hyvin pitkään. Esim. Finna-näytöissä ei 385-termi näy välttämättä ollenkaan, vaikka sillä voi kuitenkin hakea. Toinen asiaan liittyvä ongelma on sekoittuminen asiasanakäyttöön, eli vasta Melindan komentohaussa Boolen logiikan avulla kykeni rajaamaan asiasanakäytön pois kohderyhmähausta. Ehkä kirjastojen virkailijapäätteillä voi päästä samaan tulokseen, mutta on otettava huomioon asiakkaiden etähakujen yleistyminen samoin kuin omatoimikirjastot, jolloin henkilökuntaa ei ole paikalla / ei välttämättä ole kykyä monimutkaisempiin hakuihin.

Libriksessä käytetty yli 11 000 kertaa genreterminä, ja Kirjastopalvelussa on jatkuvasti lisääntynyttä käyttöä vastaavissa aineistoissa. Kyse on tiedon näkyvyydestä / saavutettavuudesta. Kirjastopalvelussa ei koettu hankalana ikäkauden kategorisoimista, vaan otetaan termi käyttöön viime kädessä local-tunnisteen avulla, jos kokous ei lämpene slm-termille. Tällöin termi saadaan kirjastojen tietokantoihin, mutta tippuu sitten Melindasta pois. Toisaalta SLM-termin puolestaan voi tulevaisuudessa konvertoida 385-kenttään?

_"En näe “ikäkauden rajaamista” ongelmana. Miksi olisi tarpeen rajata ikävuodet - eihän sitä tehdä vastaavassa “nuorten aikuisten kirjat” -termissäkään.
Kyseessä sis.kuvailijan mutu, tarkkaa vuosirajausta ei voitane tehdäkään. Itse kuitenkin pitäisin aika osuvana tuota 9-12 (ehkä -13). 14-16 on selkeästi jo nuoriso-osastoa."_

**Comment by ilona-x** [comment]
https://id.kb.se/term/barngf/Mellan%C3%A5ldersb%C3%B6cker

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
Tarkoittaa n. 9-12-vuotiaille suunnattuja kirjoja.
