### ISSUE TITLE
solumallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7990]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

solumallit 

#### Ehdotettu termi englanniksi   

cell models 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mallit (mallintaminen)](http://www.yso.fi/onto/yso/p510) 

#### Assosiatiiviset (RT)   

[koe-eläinmallit](http://www.yso.fi/onto/yso/p28104) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 
[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

"Lääkekehitys kaipaa nykyistä toimivampia solumalleja paremman tehokkuuden ja taloudellisuuden saavuttamiseksi. Nykyiset yksinkertaiset solumallit jäljittelevät huonosti solujen luonnollista ympäristöä ihmiskehossa, ja käytössä olevat eläinkokeet ovat epäeettisiä ja jäljittelevät heikosti ihmiskehoa."
https://helda.helsinki.fi/handle/10138/307177 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

farmasian väitöskirja: Specific Cell – Biomaterial Interactions for In Vivo-Like In Vitro Tissue Models from Human Pluripotent Stem Cells 

#### Perustelut ehdotukselle   

Google: n. 100 tulosta 

**Termiehdotus Fintossa:** [solumallit](http://finto.fi/yse/fi/page/Y507990)

**Comment by ilona-x** [comment]
Tarvittaisiin myös tähän väitöskirjaan: Alternative electrode materials for prototyping cell model-specific microelectrode arrays

**Comment by mirmaid** [comment]
7 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. cellmodeller ET cellulära modeller

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
