### ISSUE TITLE
cembalomusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7991]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

cembalomusiikki 

#### Ehdotettu termi ruotsiksi   

cembalomusik 

#### Ehdotettu termi englanniksi   

harpsichord music 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soitinmusiikki](http://www.yso.fi/onto/yso/p1514) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85059061> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle cembalolle tai muulle kokoonpanolle, jossa cembalo on keskeisessä osassa. 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.finna.fi/Record/helka.3323836 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [cembalomusiikki](http://finto.fi/yse/fi/page/Y507991)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
