### ISSUE TITLE
sitaatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7992]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sitaatit](http://www.yso.fi/onto/ysa/Y106870) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "lainaukset" 

#### Perustelut ehdotukselle   

Vastine löytyy Kielitoimiston sanakirjasta, eikä edes viittausmuotona vaan varsinaisena käsitteenä [https://www.kielitoimistonsanakirja.fi/lainaus] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
