### ISSUE TITLE
hackathonit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7993]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hackathonit 

#### Ehdotettu termi englanniksi   

hackathons 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tapahtumat](http://www.yso.fi/onto/yso/p2108) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Hackathon 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Avaimet avoimen datan hackathoniin : opas korkeakouluille ja kehittäjille 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hackathonit](http://finto.fi/yse/fi/page/Y507993)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. hackaton ET hackathon, hackmaraton
https://svenska.se/tre/?sok=hackaton&pz=1

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
