### ISSUE TITLE
transkriptomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7994]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

transkriptomi 

#### Ehdotettu termi englanniksi   

transcriptome 

#### Ehdotettu termi ruotsiksi   

transkripton 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elolliset fyysiset kokonaisuudet](http://www.yso.fi/onto/yso/p6944) 

#### Assosiatiiviset (RT)   

[perimä](http://www.yso.fi/onto/yso/p8862) 
[RNA](http://www.yso.fi/onto/yso/p7689) 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : transkriptomi https://tieteentermipankki.fi/wiki/Biologia:transkriptomi 
MeSH / FinMeSH : https://finto.fi/mesh/fi/page/D059467 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

Definition: solun, kudoksen, elimen tai organismin kaikkien RNA-molekyylien muodostama kokonaisuus
Tieteen termipankki 
https://tieteentermipankki.fi/wiki/Biologia:transkriptomi 

#### Perustelut ehdotukselle   

Tarvittiin väitöskirjan kuvailuun 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: Genomics and transcriptomics of 'Candidatus Liberibacter solanacearum' and its interaction with its host plant Daucus carota subsp. sativus https://helda.helsinki.fi/handle/10138/305496 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [transkriptomi](http://finto.fi/yse/fi/page/Y507994)

**Comment by mirmaid** [comment]
10 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. transkriptom https://mesh.kib.ki.se/term/D059467/transcriptome

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
