### ISSUE TITLE
suolinkaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7995]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suolinkaiset](http://www.yso.fi/onto/ysa/Y198823) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yksikköön, koska laji:
suolinkainen ((Ascaris lumbricoides) 

#### Perustelut ehdotukselle   

https://finto.fi/mesh/fi/page/D017164
https://fi.wikipedia.org/wiki/Suolinkainen
http://id.loc.gov/authorities/subjects/sh85008530.html 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Puuttuu laji.fi kannasta.  Wikidatassa  https://www.wikidata.org/wiki/Q468771
