### ISSUE TITLE
autofagia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7996]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

autofagia 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Proteostasis in retinal pigment epithelial cells: Relevance to age-related macular degeneration 

**Termiehdotus Fintossa:** [autofagia](http://finto.fi/yse/fi/page/Y507996)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D001343

https://fi.wikipedia.org/wiki/Autofagosytoosi

Melindassa _autofagia_ 6 kertaa, _autofagosytoosi_ 5 kertaa. Googlella edellinen on käytetympi.

**Comment by jarmosaarikko** [comment]
**autofagia**  en: auto**phagia** voi tarkoittaa myös "itsensä pureminen"  tai itsepurenta   LT  itsetuhokäyttäytyminen
en: self biting  -- samantapainen  ongelma kuin itsensä viiltely http://www.yso.fi/onto/yso/p23920
en: "self mutilation"  
On kai niin harvinainen, ettei tarvitse olla itsetuhokäyttäytymisen ohjausterminä?`
Huom! esiintyy myös eläimillä

**Comment by mariaforsen** [comment]
Sv. autofagi ET autofagocytos

**Comment by YSO-kokous** [comment]
Otetaan sanastoon autofagia, ohjaustermiksi autofagosytoosi.
