### ISSUE TITLE
geenikuljettimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7997]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

geenikuljettimet 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Gene Therapy of Atherosclerosis and Familial Hypercholesterolemia: Efficacy and Safety of Liver Gene Therapy with Lentivirus and Adeno-associated Virus 

**Termiehdotus Fintossa:** [geenikuljettimet](http://finto.fi/yse/fi/page/Y507997)

**Comment by mirmaid** [comment]
Geenitekniikassa käytettävä rakenne, jolla haluttu geeni voidaan kuljettaa solun sisään ja joko liittää solun perimään tai saada ilmentymään solussa ilman integroitumista. http://tieteentermipankki.fi/wiki/Nimitys:geenikuljetin

Mahdollista ehkä myös KÄ vektorit (biologia); https://fi.wikipedia.org/wiki/Vektori_(biologia)

Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. gentransportörer? hyvin vähän käytetty..käytetäänkö yleensä kuitenkin vektori-sanaa näistä?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi:
geenikuljettimet KÄYTÄ vektorit (biologia)
