### ISSUE TITLE
veri-aivoeste

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#7998]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

veri-aivoeste 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pharmacokinetic concepts in drug delivery to the brain via transporter-mediated prodrug approach 

**Termiehdotus Fintossa:** [veri-aivoeste](http://finto.fi/yse/fi/page/Y507998)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D001812

**Comment by mariaforsen** [comment]
Sv. blod-hjärnbarriär

**Comment by tpalonen** [comment]
Käytetään myös termiä aivo-verieste. Ohjaustermiksi? Ks. https://fi.wikipedia.org/wiki/Veri-aivoeste
