### ISSUE TITLE
saarivaltiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#800]
#### Ehdotettu termi suomeksi

saarivaltiot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)

**Luontipäivämäärä:** 07.05.2002

**Muokkauspäivämäärä:** 7.5.2002, 16.12.2008

**Voyager-id:** 119103

**Termiehdotus Fintossa:** [saarivaltiot](http://finto.fi/yse/fi/page/Y319103)

**Comment by ilona-x** [comment]
Tälle termille olisi ollut käyttöä väitöskirjan "[Statehood, statelessness, and continuity in a climate-changed world : A worst-case scenario analysis](https://urn.fi/URN:ISBN:978-952-12-4328-8)" kuvailussa

--

Melinda x 20

--

https://fi.wikipedia.org/wiki/Saarivaltio

--

Saarivaltio-aihe YLEllä: https://yle.fi/t/18-146528/fi

**Comment by mariaforsen** [comment]
Sv. östater HT öriken (fi. saarivaltakunta), önationer
https://sv.wikipedia.org/wiki/%C3%96stat
https://svenska.se/tre/?sok=%C3%B6riken&pz=1
https://www.consilium.europa.eu/sv/press/press-releases/2024/05/07/council-conclusions-on-small-island-developing-states-sids/
https://www.abo.fi/nyheter/doktorsavhandling-om-juridiska-pafoljder-for-stater-som-hotas-av-den-stigande-havsnivan/
jfr https://www.sanakirja.fi/custom/all/%C3%B6rike

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
