### ISSUE TITLE
munuaisaltaan syöpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8000]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

munuaisaltaan syöpä 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Occupational exposures and risk of kidney and renal pelvis cancer in the Nordic countries 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [munuaisaltaan syöpä](http://finto.fi/yse/fi/page/Y508000)

**Comment by mirmaid** [comment]
Munuaisaltaan syöpä ei ole sama sairaus kuin munuaissyöpä. Munuaisaltaan syöpä kuuluu virtsateiden syöpiin ja hoidetaan niiden tavoin. https://www.kaikkisyovasta.fi/tietoa-syovasta/syopataudit/munuaissyopa/

Lähes kaikki uroteelin syövät sijaitsevat virtsarakossa. Munuaisaltaan, virtsanjohtimen ja virtsaputken syövät ovat harvinaisia. https://www.kaikkisyovasta.fi/tietoa-syovasta/syopataudit/virtsarakon-syopa/

Sijaintinsa perusteella virtsatiesyöpä voidaan jakaa ylävirtsateiden (munuaisallas tai virtsanjohdin) ja virtsarakon syöpään. Tämä jako perustuu anatomiaan, biologisesti kyseessä on sama sairaus. https://virtsarakonsyopa.fi/yleista-virtsarakon-ja-virtsateiden-syovasta/

https://www.stat.fi/meta/luokitukset/kuolinsyyt/081-1998/c00-c97.html, ICD C65 = Malignant neoplasm of renal pelvis

Lääketieteen termit: munuaisaltaan uroteelikarsinooma

**Comment by mariaforsen** [comment]
Sv. njurbäckencancer

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa munuaisaltaan syöpä.
