### ISSUE TITLE
jälkikäyttö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8001]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jälkikäyttö](http://www.yso.fi/onto/ysa/Y185610) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Sanalla on useita merkityksiä. 1) Tuotannosta poistetun alueen uusi käyttömuoto, esimerkiksi turvetuotannosta poistetun alueen metsittäminen. 2) Moottorien yhteydessä raskaan kuormituksen jälkeen tyhjäkäynnillä suoritettava moottorin jäähdytyskäyttö 

#### Ehdotettu muutos   

Tarkennetaan? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Myös tällaisia merkityksiä: https://www.sanasto.fi/kirjallisuuden-jalkikaytto/ Olisiko huomautus yksinkertaisesti poistettavissa?

**Comment by mirmaid** [comment]
Käytetty Melindassa vain 6 kertaa, kaikki merkityksessä 1. Mielestäni huomautuksen poisto riittää.

**Comment by mirmaid** [comment]
Tarvitaankohan tälle sittenkin tarkenne, ettei sekoitu uusiokäyttöön...

**Comment by ilona-x** [comment]
Jos erottavan tarkenteen keksiminen ei onnistu, niin olisiko jälkikäyttö mahdollista poistaa, kun käyttö on ollut vähäistä, ja viitteisiin löytyisi mahdollisesti muuta sopivaa termistöä (ennallistaminen, metsitys, jälkihoito jne.)
http://turveinfo.fi/turve/turvetuotanto/turvetuotantoalueiden-jalkikaytto/

Edellisen käsittelyn jälkeen Melindaan on tosiaan ilmestynyt kaksi uutta viitettä, joissa on käytetty jälkikäyttö-termiä, vaikka toisessa pitäisi varmaankin olla uudelleenkäyttö ja toisessa uusiokäyttö.

- Olutpanimon tontti - paikallinen vai globaali kysymys? = Är bryggeritomten en lokal eller en global fråga? https://melinda.kansalliskirjasto.fi/byid/016962587

- Cirkulär ekonomi i textilindustrin : en studie om återvinning inom den finländska modebranschen https://melinda.kansalliskirjasto.fi/byid/016794470

**Comment by mariaforsen** [comment]
Ei löydy TEPAsta, ei Kielitoimiston sanakirjasta tms. Googlessa näytti olevan eniten moottorin jäähdytyskäyttö-merkityksessä ja sitten toisaalta turvealueiden jälkikäytöstä, eli ehkä poisto olisi ihan mahdollinen ratkaisu? Tai mahdollisesti tarkemman termin hyväksyminen?

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan käsite.
