### ISSUE TITLE
galliumarsenidi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8002]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

galliumarsenidi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Development of Semiconductor Nanowire Materials for Electronic and Photonic Applications 

#### Perustelut ehdotukselle   

- 

**Termiehdotus Fintossa:** [galliumarsenidi](http://finto.fi/yse/fi/page/Y508002)

**Comment by mirmaid** [comment]
LCSH: Gallium arsenide

**Comment by mariaforsen** [comment]
Sv. galliumarsenid
