### ISSUE TITLE
douppaus (puolijohdetekniikka)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8003]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

douppaus (puolijohdetekniikka) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Development of Semiconductor Nanowire Materials for Electronic and Photonics Applications 

**Termiehdotus Fintossa:** [douppaus (puolijohdetekniikka)](http://finto.fi/yse/fi/page/Y508003)

**Comment by mirmaid** [comment]
LCSH: Semiconductor doping, http://id.loc.gov/authorities/subjects/sh85119890

https://fi.wikipedia.org/wiki/Douppaus

Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. dopning (mikroteknik)/(halvledarteknik)

**Comment by LeKorsu** [comment]
Tarvitaanko ohjausterminä douppaus (urheilu/lääketiede) KÄ doping?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon. Tutkitaan vielä, laitetaanko sulkutarkenteeksi mikrotekniikka vai puolijohdintekniikka..
Lisätään myös ohjaustermi:
douppaus (urheilu) KÄYTÄ doping

**Comment by ilona-x** [comment]
http://tieteentermipankki.fi/wiki/Fysiikka:douppaus
