### ISSUE TITLE
sirkuspedagogiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8004]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sirkuspedagogiikka 

#### Ehdotettu termi ruotsiksi   

circuspedagogik 

#### Ehdotettu termi englanniksi   

circus pedagogy 

#### Vaihtoehtoiset termit ja ilmaisut   

sirkuksen pedagogiikka 

#### Perustelut ehdotukselle   

Sirkus on muutakin kuin temppuja ja akrobatiaa, tämän hetken asiasanat eivät kata riittävästi sirkuksen alaa. Myös sirkuksta opetetaan ja lajin pedagogiikkaa kehitetään, minkä takia termin käyttö lisääntyy. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Maisteritason opinnäytetyöni. Aiheeni keskittyy nimenomaan sirkuspedagogiiikkaan. 

**Ehdottajan organisaatio:** Taideyliopiston Teatterikorkeakoulu **Termiehdotus Fintossa:** [sirkuspedagogiikka](http://finto.fi/yse/fi/page/Y508004)

**Comment by mirmaid** [comment]
Kerran Melindassa, 58 viitettä Googlella (kun poistetaan samankaltaiset tulokset). Erilaisia pedagogiikkoja on YSOssa n. 30.

**Comment by mariaforsen** [comment]
Sv. cirkuspedagogik

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
