### ISSUE TITLE
puupolttoaineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8005]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puupolttoaineet 

#### Ehdotettu termi ruotsiksi   

träbaserade bränslen 

#### Ehdotettu termi englanniksi   

wood fuels 

#### Assosiatiiviset (RT)   

[energiapuu](http://www.yso.fi/onto/yso/p6168) 

#### Vastaava käsite muussa sanastossa   

Tilastokeskus : https://www.stat.fi/meta/kas/puupolttoaineet.html 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[19 Energia. Polttoaineet](http://www.yso.fi/onto/yso/p26566) 

#### Tarkoitusta täsmentävä selite   

Tilastokeskus:
Sisältää seuraavat polttoaineluokituksen luokat
- Halot, rangat ja pilkkeet (3111)
- Kokopuu- tai rankahake (3112)
- Metsätähdehake tai -murske (3113)
- Kuori (3121)
- Sahanpuru, kutterilastut ym. purut (3122)
- Puutähdehake tai -murske (3123)
- Erittelemätön teollisuuden puutähde (3128)
- Muu teollisuuden puutähde (3129)
- Puunjalostusteollisuuden jäteliemet (3130)
- Muut puunjalostusteollisuuden sivu- ja jätetuotteet (3140)
- Kierrätyspuu (3150)
- Puupelletit ja -briketit (3160). 

#### Perustelut ehdotukselle   

Melindassa asiasanana 477 tietueessa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [puupolttoaineet](http://finto.fi/yse/fi/page/Y508005)

**Comment by ilona-x** [comment]
YSO:
**energiapuu** (engl. Fuelwood) http://www.yso.fi/onto/yso/p6168

LCSH:
**Fuelwood** http://id.loc.gov/authorities/subjects/sh85052228
KT Cordwood
KT Energy wood, Forest
KT Firewood
KT Forest energy wood
KT Forest fuel
KT Fuel wood
KT Wood as fuel
KT **Wood fuel**
KT **Woodfuel**

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. trädbränslen ET träbränslen, träbaserade bränslen, trädbaserade bränslen
