### ISSUE TITLE
rehuntuotanto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8006]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rehuntuotanto 

#### Ehdotettu termi englanniksi   

feed production, fodder production 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tuotanto tuotteen mukaan](http://www.yso.fi/onto/yso/p6116) 

#### Assosiatiiviset (RT)   

[rehut](http://www.yso.fi/onto/yso/p3267) 

#### Vastaava käsite muussa sanastossa   

AFO : https://finto.fi/afo/fi/page/p1997 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Perustelut ehdotukselle   

Melindassa asiasanana 183 tietueessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, Arto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [rehuntuotanto](http://finto.fi/yse/fi/page/Y508006)

**Comment by mariaforsen** [comment]
Sv. foderproduktion ET fodertillverkning

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
