### ISSUE TITLE
Ala-Lemu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8007]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Ala-Lemu](http://www.yso.fi/onto/ysa/Y94082) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

poistetaan maininta kylästä huomautuksesta 
lisätään KT Ala-Lemun kartano tai vaihdetaan päätermi 

#### Perustelut ehdotukselle   

Kyliä ei YSOssa ja tarkempi termi mahdollinen

**Comment by LeKorsu** [comment]
Suuri enemmistö kartanoista näyttäisi olevan sanaliittomuodossa "N:n kartano", joskin joitakin poikkeuksia on (ainakin Kirjola, Königstedt, Sundsberg [tästä huomautus, että päärakennus on purettu]). Kannattaisin tämän perusteella päätermin muuttamista Ala-Lemun kartanoksi.

Pitäisikö myös Königstedt muuttaa Königstedtin kartanoksi (nyt ohjaa siis toisinpäin)? Noista kahdesta muusta en osaa sanoa (wikipedia Kirjolasta: Kylän päätilaa on kutsuttu Kirjolan kartanoksi sen kokonsa vuoksi. )

**Comment by mirmaid** [comment]
Kirjolasta on myös erillinen ehdotus. Muut voitaisiin mielestäni muuttaa.
