### ISSUE TITLE
vesitekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8008]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vesitekniikka 

#### Ehdotettu termi ruotsiksi   

vattenteknik 

#### Ehdotettu termi englanniksi   

water engineering 

#### Vaihtoehtoiset termit ja ilmaisut   

vesi- ja ympäristötekniikka 

#### Vastaava käsite muussa sanastossa   

Tieteen termipankki : https://www.tieteentermipankki.fi/wiki/Nimitys:vesitekniikka 

#### Perustelut ehdotukselle   

Ympäristöteknologia- termi löytyy YSOsta, mutta vesitekniikka ei. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tarvitsen termiä tehdessäni auktoriteettitietueita Aalto-yliopiston ko. alalta väitelleistä henkilöistä. 

#### Tarkoitusta täsmentävä selite   

Vesi-ja ympäristötekniikka on opetus- ja tutkimusalana yliopistoissa ja ammattikorkeakouluissa. 

**Ehdottajan organisaatio:** Aalto-yliopisto **Termiehdotus Fintossa:** [vesitekniikka](http://finto.fi/yse/fi/page/Y508008)

**Comment by mirmaid** [comment]
14 viitettä Melindassa, suhde LVI-tekniikkaan? Onko sama asia? Tai yhdistelmä LVI- ja ympäristötekniikkaa?

**Comment by mirmaid** [comment]
https://www.aalto.fi/fi/rakennetun-ympariston-laitos/vesi-ja-ymparistotekniikka
https://www.turkuamk.fi/fi/tutkimus-kehitys-ja-innovaatiot/tutkimusryhmat/vesi-ja-ymparistotekniikka/

**Comment by ilona-x** [comment]
vesirakennustekniikka | vesitekniikka | vesirakennus

hydraulic engineering | englanti |  
water engineering | englanti |  
vattenteknik | ruotsi |  
hydroteknik | ruotsi |  
vattenbyggnad | ruotsi
Lähde: https://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:vesirakennustekniikka

fi        vesitekniikka
sv       vattenbyggnadsteknik; vattenteknik
en      hydraulic engineering; water engineering
Lähde: https://termipankki.fi/tepa/fi/haku/vesitekniikka

LIITO: vesirakennustekniikka http://www.yso.fi/onto/liito/p13085

YSO: vesirakennus (eng. hydraulic engineering) http://www.yso.fi/onto/yso/p3449

**Comment by LeKorsu** [comment]
Menisikö ihan metsään vesitekniikka KÄ vesirakennus? Melindassa yli 1600 osumaa vesirakennuksella. Tosin silloin pitäisi varmaan vesirakennukseen lisätä assosiatiivisia käsitteitä (vedenpuhdistus, vesijohtoverkot jne.
Vesitekniikka tosin kuulostaa modernimmalta, mutta sekoittuuko jos ovat molemmat omina? Mutuna vesitekniikka kuulostaa isommalta struktuurilta kuin LVI-tekniikka, mutta googlaamalla saan ensimmäiseksi osumaksi Suomen vesitekniikka -nimisen yrityksen, joka mainostaa itseään täyden palvelun lvi-talona, joten se mutu ei kantanut kovin pitkälle.

**Comment by ilona-x** [comment]
Samalla kannalla tuosta LVI-tekniikasta Leenan kanssa. Mielestäni LVI-tekniikka on rakennuksiin liittyvää, kun taas vesi- ja ympäristötekniikassa on kyse vesihuollosta ja vesirakentamisesesta.

Kielitoimiston sanakirja:
LVI-tekniikka 
tekn. lämmitys-, vesijohto- ja ilmastointitekniikka.

**Comment by YSO-kokous** [comment]
Otetaan vesitekniikka ohjaustermiksi vesirakennus-käsitteelle. Pohditaan, tarvitaanko lisää assosiatiivisia suhteita vesirakenunkselle. Nykyisin assosiatiivisena esim. kalatiet. Voitaisiin lisätä RT esim. vedenpuhdistus, vesijohtoverkko.

YSO-ylläpito pohtii vielä näitä:
vesitekniikka KÄYTÄ ympäristötekniikka?
vesitekniikka KÄYTÄ LVI-tekniikka?
