### ISSUE TITLE
Saksan-Ranskan sota (1870-1871)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8011]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Saksan-Ranskan sota (1870-1871) 

#### Ehdotettu termi ruotsiksi   

Fransk-tyska kriget 

#### Ehdotettu termi englanniksi   

Franco-Prussian War 

#### Vastaava käsite muussa sanastossa   

LCSH : Franco-Prussian War, 1870-1871 
SAO : Fransk-tyska kriget 1870-1871 

#### Perustelut ehdotukselle   

Tarvittava termi historia-aineistoa varten, myös kaunokirjallisuudessa ajankuvauksissa tulee paljon vastaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kuvaelmia (ranskalaissaksalaisesta sodasta) ja kertomuksia / Alphonse Daudet 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Saksan-Ranskan sota (1870-1871)](http://finto.fi/yse/fi/page/Y508011)

**Comment by LeKorsu** [comment]
Tarvitseeko ohjaustermejä?
KT Ranskan-Preussin sota 
KT vuoden 1870 sota

**Comment by EsaMPKK** [comment]
> Tarvitseeko ohjaustermejä?
> KT Ranskan-Preussin sota
> KT vuoden 1870 sota

Tarvii ja selkiyttää.

**Comment by mariaforsen** [comment]
Sv. fransk-tyska kriget (1870-1871) ET fransk-tyska kriget, tysk-franska kriget
