### ISSUE TITLE
koulukuljetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8012]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koulukuljetus](http://www.yso.fi/onto/ysa/Y117570) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermiksi koulukyyti 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/#/koulukyyti 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
