### ISSUE TITLE
Kiiskilä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8013]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kiiskilä](http://www.yso.fi/onto/ysa/Y116495) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kiiskilän kartano 

#### Perustelut ehdotukselle   

Kiiskilä on monimerkityksinen nimi, ks. https://fi.wikipedia.org/wiki/Kiiskil%C3%A4 ja https://fi.wikipedia.org/wiki/Kiiskil%C3%A4n_kartano

**Comment by YSO-kokous** [comment]
Muutetaan muotoon Kiiskilän kartano.
