### ISSUE TITLE
sairaankuljetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8014]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sairaankuljetus](http://www.yso.fi/onto/ysa/Y98704) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermeiksi potilaskuljetus & ambulanssikuljetus 

#### Perustelut ehdotukselle   

http://www.yso.fi/onto/mesh/D014187 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotetut ohjaustermit.
