### ISSUE TITLE
Koneturvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8015]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Koneturvallisuus 

#### Ehdotettu termi englanniksi   

Safety of machinery 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Koneturvallisuus 

#### Perustelut ehdotukselle   

YSO:sta puuttuu sana 'koneturvallisuus'.
Koneturvallisuus on keskeinen käsite, josta on jopa omat standardinsa:
https://www.sfs.fi/files/63/Koneturvallisuus_SFS_esite_web.pdf 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Standardit 

**Ehdottajan organisaatio:** Tampereen ammattikorkeakoulu **Termiehdotus Fintossa:** [Koneturvallisuus](http://finto.fi/yse/fi/page/Y508015)

**Comment by mirmaid** [comment]
AFOssa, JUHOssa, TEROssa ja TSR-ontologiassa. 26 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. maskinsäkerhet

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
