### ISSUE TITLE
kiviaines

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8016]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kiviaines](http://www.yso.fi/onto/ysa/Y96249) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Paikkatieto-ontologiaa kehittävä työryhmä pohti YSOn ratkaisua, jonka mukaan käsitteet maa-aines ja kiviaines ovat samalla hierarkiatasolla. Työryhmämme pohti, eikö käsitteen kiviaines tulisi olla käsitteen maa-aines yläkäsite. Eli esim. kalliomurske, sepeli ja hiekka ovat kiviaineksia, jotka puolestaan ovat yhdentyyppisiä maa-aineksia. Kiviainesten lisäksi maa-aineksiin kuuluu esim. multa. Tosin lienee mahdollista, että käsitteiden maa-aines ja kiviaines välisten suhteiden hahmottaminen riippuu siitä, keneltä asiantuntijalta kysyy...? 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

PTO

**Comment by mirmaid** [comment]
Ehdotuksen mukaisesti vaikuttaisi olevan ennemminkin niin, että kiviaines olisi maa-aineksen alakäsite. Toisaalta geologia.fi: _Maa-aines on kallioperän päälle kerrostunutta irtainta kiviainesta_ - näin määritellen maa-aines ei kattaisi kaikkea kiviainesta? Tämän perusteella en muuttaisi nykyistä hierarkiaratkaisua.

**Comment by FinMeSHienPaimentaja** [comment]
Mielestäni ensisijaisesti olisi parempi olla samalla hierarkia-tasolla. 

Maa-ainekset ovat syntyneet kivi-aineksista, kun kivi-aineksiin on sekoittunut eloperäistä ainesta (rautalangasta väännettynä). Maa-ainekset sisältävät enemmän tai vähemmän kiviainesta (kivennäisiä) ja eloperäistä ainesta, ks. esim. louhikko, liejusavi. 

Ks. https://fi.wikipedia.org/wiki/Maalaji

"Maalajiluokitus tarkoittaa **maa-aineksen** luokittelemista eri maalajeiksi, eri maalajien määrittelyä ja maalajien luokittelua eri maalajiryhmiin."

Tai vaihtoehtoisesti kiviaines ylempänä, maa-aines kiviaineksen alla.

**Comment by YSO-kokous** [comment]
Ei muutosta hierarkiaan. Ks kommentit edellä.
