### ISSUE TITLE
attribuutio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8019]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[attribuutio](http://www.yso.fi/onto/ysa/Y109808) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan huomautus: Sanalla on useita merkityksiä. 1) Tarkoittaa ominaisuuden tai asian kytkemistä tiettyyn syyhyn, henkilöön tai seikkaan. 2) Tarkoittaa teoksen määrittämistä tietyn tekijän tai koulukunnan tuotteeksi
Tai jaetaan käsite eri merkityksiin? 

#### Perustelut ehdotukselle   

Tällaisia huomautuksia ei saa olla ontologiassa. 

#### Ehdottajan organisaatio   

YSO

**Comment by mariaforsen** [comment]
Käytetty Melindassa molemmissa (ja ehkä muissakin?) merkityksissä.

**Comment by mirmaid** [comment]
Kannattaisin huomautuksen poistoa. Mielestäni mainitut merkitykset ovat hyvin likeisiä.

**Comment by YSO-kokous** [comment]
Poistetaan huomautus. Ei muita muutoksia.
