### ISSUE TITLE
taidelaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#802]
#### Ehdotettu termi suomeksi

taidelaitokset
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[90 Taide yleensä. Taidesuuntaukset ja -tyylit. Taidehistoria](http://www.yso.fi/onto/ysa/ryhma_90)

**Luontipäivämäärä:** 07.05.2002

**Muokkauspäivämäärä:** 7.5.2002, 7.5.2002, 3.10.2006, 7.2.2008, 16.12.2008

**Voyager-id:** 119108

**Termiehdotus Fintossa:** [taidelaitokset](http://finto.fi/yse/fi/page/Y319108)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin tätä julkaisuun https://www.cupore.fi/fi/julkaisut/cuporen-julkaisut/taide-ja-kulttuurilaitokset-osana-jyvaeskylaen-kehitystae-ja-hyvinvointia

**Comment by ilona-x** [comment]
Melinda x 9

**Comment by jarmosaarikko** [comment]
MOT vastineet: konstinstitutioner, art institutions, artistic institutions
Wikidata: [taideinstuutio](http://www.wikidata.org/entity/Q20897549), konstinstitution, art institution  
KT taidejärjestö 
YK kulttuurilaitos

Wikipediassa Taideinstituutti --> Muotoiluinstituutti (LABin muotoiluinstituutti) - yksittäinen organisaatio

**Comment by annamarj** [comment]
"Taidelaitokset" on aika yleisessä käytössä (mm. OKM).

**Comment by mariaforsen** [comment]
Sv. konstinstitutioner

**Comment by jarmosaarikko** [comment]
kts. https://github.com/Finto-ehdotus/YSE/issues/9781 taideyhteisöt

**Comment by YSO-kokous** [comment]
#### Päätös
lisätään ohjaustermiksi taidelaitokset KÄYTÄ kulttuurilaitokset
