### ISSUE TITLE
lihavuusleikkaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8023]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lihavuusleikkaukset 

#### Ehdotettu termi englanniksi   

Bariatric Surgery 

#### Ehdotettu termi ruotsiksi   

Fetmakirurgi 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D050110> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda x 2 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The effect of bariatric surgery on adipose tissue energy metabolism in type 2 diabetes 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lihavuusleikkaukset](http://finto.fi/yse/fi/page/Y508023)

**Comment by mariaforsen** [comment]
Sv. fetmaoperationer ET fetmakirurgi, bariatrisk kirurgi, metabol kirurgi, obesitaskirurgi, överviktsoperationer

KT laihdutusleikkaukset? Ks https://www.kielitoimistonsanakirja.fi/#/laihdutusleikkaus?source=suggestion
