### ISSUE TITLE
instituutiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8025]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[instituutiot](http://www.yso.fi/onto/ysa/Y98961) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään huomautus merkityksestä? 

#### Perustelut ehdotukselle   

Ks. kielitoimiston sanakirja: tapaan t. oikeussäännöksiin perustuva sosiol., pol. t. uskonnollinen elämänmuoto, tapajärjestelmä, (yhteiskunnallinen) laitos. Englanniksi on jo huomautus (mutta onko tämä käytetty vain siinä merkityksessä?) Vrt. Melinda.

**Comment by tpalonen** [comment]
Englannin huomautus johtuu siitä, että sanastossa on myös laitokset, joka kääntyy englanniksi niin ikään termillä institutions. Käsitettä on siis täytynyt englanniksi täsmentää.

**Comment by mariaforsen** [comment]
Ja näin täytyy siis myös ruotsiksi tehdä, mutta onhan se tärkeää että termi määritellään samalla tavalla kaikilla kolmella kielellä, muuten termi käytetään väärin kuvailussa.

**Comment by YSO-kokous** [comment]
Ei nähty tarvetta muutoksille suomen kielellä, mutta YSOn ylläpito pohtii yläkäsitettä uudelleen (nykyinen yläkäsite on organisaatiot). Ruotsiksi tehtäneen käsitteen merkitystä tarkentavia muutoksia. Englannin käytettävää termiä lisäksi mietittäneen.
