### ISSUE TITLE
kauppakeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8027]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kauppakeskukset](http://www.yso.fi/onto/ysa/Y118837) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään tai määritellään "kaupankäynnin keskuspaikka" tms. 

#### Perustelut ehdotukselle   

Sanastossa on nyt sekä ostoskeskukset että kauppakeskukset. Ks. Kielitoimiston sanakirja ja Melinda (ei osattu erottaa ostoskeskuksista, ymmärrettävistä syistä). Joko ne pitäisi olla selvästi eri asioita (eli kauppakeskus kaupankäynnin keskuspaikkana, 2. merkitys sanakirjassa) tai sitten ne pitäisi yhdistää. Englanniksi ja ruotsiksi ei suomenkielisten nykyhuomautusten mukaista erottelua.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Shopping_mall
https://en.wikipedia.org/wiki/Strip_mall

**Comment by EsaMPKK** [comment]
> https://en.wikipedia.org/wiki/Shopping_mall
> https://en.wikipedia.org/wiki/Strip_mall

Nuo ovat tosiaan kauppakeskus ja ostari.

**Comment by tpalonen** [comment]
Käsitteille voi merkityseron kyllä tehdä, kuten Wikipedia-linkit osoittavat. Wikipedian mukaan "Ostoskeskuksiksi kutsutaan etupäässä 1960–1980-luvuilla rakennettuja, yhdessä kerroksessa olevia keskittymiä etenkin tuohon aikaan rakennetuissa lähiöissä." 

Esimerkiksi Helsingin uusia kauppakeskuksia (Redi, Mall of Tripla, Easton, Hertsi) näkyy nimitettävän varsin systemaattisesti kauppakeskuksiksi. Hertsistä tosin käytetään myös nimitystä _lähipalvelukeskus_, ilmeisesti siksi, koska siellä on liiketilojen lisäksi myös kirjasto ja nuorisotilat.

**Comment by YSO-kokous** [comment]
Säilytetään käsitteet erillään. Täydennetään määritelmiä (ks. esim. Wikipedia) siten, että ilmaistaan että kauppakeskus on (yleensä) kooltaan suurempi kuin ostoskeskus. Erillään pitämisestä vs. yhdistämisestä äänestettiin: erillään pitäminen sai 8 ääntä, yhdistäminen 3 ääntä.

**Comment by ilona-x** [comment]
Kauppakeskusyhdistyksen sivuilta löytyy määritelmiä pinta-alasta ym.:
https://www.kauppakeskusyhdistys.fi/toimiala-ja-markkinat.html
