### ISSUE TITLE
nziman kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8028]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nziman kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781986179300 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [nziman kieli](http://finto.fi/yse/fi/page/Y508028)

**Comment by jtuohini** [comment]
LCSH-siltaus: **[Nzima language](http://id.loc.gov/authorities/subjects/sh85093556)**

**Comment by mariaforsen** [comment]
Sv. nzima https://www.kb.se/katalogisering/Formathandboken/Sprakkoder/Sprakkoder/
https://en.wikipedia.org/wiki/Nzema_language
