### ISSUE TITLE
korvaushoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8029]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[korvaushoito](http://www.yso.fi/onto/ysa/Y113624) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan huomautus tai mahdollisesti jaetaan 

#### Perustelut ehdotukselle   

Kaksimerkityksinen huomautus.

**Comment by ilona-x** [comment]
YSOssa myös tarkempia termejä:
entsyymikorvaushoito
hormonihoito KT hormonikorvaushoito
nikotiinikorvaushoito

FinMeSHissä vain tarkempia termejä:
entsyymikorvaushoito
hormonikorvaushoito ST estrogeenikorvaushoito
mitokondriaalinen korvaushoito
munuaisten korvaushoidot
opiaattikorvaushoito

**Comment by jarmosaarikko** [comment]
Entä jos vain muuttaisi huomatusta laveammaksi: (vai olisiko se skos:definition)
Tarkoittaa vajaatoiminnan tai erilaisten riippuvuuksien vieroitus-, korvaus- ja ylläpitohoitoa

Eikö hormonihoito pitäisi siirtää tämän käsitteen alakäsitteeksi?

**Comment by mariaforsen** [comment]
Ruotsiksi eri termejä riippuen merkityksestä.

**Comment by FinMeSHienPaimentaja** [comment]
Kaikki hormonihoito ei ole hormonikorvaushoitoa, ks. esim. 

https://www.hus.fi/sairaanhoito/sairaanhoitopalvelut/syopataudit/syopapotilaan-hoitopolut/rintasyopapotilaan_hoitopolku/hormonihoito/Sivut/default.aspx

**Comment by YSO-kokous** [comment]
Otetaan sanastoon opiaattikorvaushoito. Korjataan Melindan viitteet YSOn tarkempiin termeihin. Katsotaan mitä tämän jälkeen jää jäljelle.

**Comment by ilona-x** [comment]
Korjattu Melindaan ne, joille löytyi tarkempi YSO-termi. Jäljelle jäi vain 9 viitettä.

-  FVIII  prophylaxis in children with severe haemophilia A : a nationwide survey  of outcome and costs in Finland / Kaisa Vepsäläinen.  **(Hyytymistekijäkorvaushoito)** + saman julkaisun verkkoversio
-  Hemofilian hoidon edistysaskelia : kallis harvinaistauti vaatii keskitettyä hoitoa / Elina Armstrong ja Riitta Lassila. **(Hyytymistekijäkorvaushoito)**
- Antikoagulaatio  jatkuvassa munuaisten korvaushoidossa : daltepariini-infuusion ja  sitraatti-kalsiumptekniikan vertailu / Elisa Uljas ... [et al.].  Uljas, Elisa. **(munuaisten korvaushoito)**
- Renal replacement therapy in the critically ill / Suvi Vaara.  **(munuaisten korvaushoito)**
- Parathyroid hormone as an outcome indicator in old age / Mikko Björkman.  **(D-vitamiinikorvaushoito)**
- Synnytykseen liittyvä massiivinen verenvuoto / Jouni Ahonen, Susanna Sainio, Päivi Pakarinen.  Ahonen, Jouni. **(korvaushoito (nestetäyttö, verituotteet ja hyytymistekijävalmisteet))** 
- Albumiinin käyttö tehohoidossa / Ville Pettilä, Esko Ruokonen.  Pettilä, Ville.   **(albumiinikorvaushoito)**
- **Verenvuotojen korvaushoito** / Jukka Vaahersalo ; ohjaaja Tom Silfvast.  Vaahersalo, Jukka. Helsinki : Helsingin yliopisto, 2002.  

--

FinMeSH: munuaisten korvaushoidot (alakäsitteet:  hemodialyysi & munuaisensiirto) http://www.yso.fi/onto/mesh/D017582

**Comment by mirmaid** [comment]
Ruotsiksi opiaattikorvaushoito = opiatsubstitutionsbehandling, nikotiinikorvaushoito = nikotinersättningsbehandling? Eli raja ei ole YSOn huomautuksen mukainen?

Munuaisten korvaushoito KÄ dialyysihoito?

**Comment by mariaforsen** [comment]
Ruotsiksi käytetään sekä substitutions- että ersättnings- näissä merkityksissä. 
Esimerkiksi näin:
https://mesh.kib.ki.se/term/D058850/opiate-substitution-treatment
https://mesh.kib.ki.se/term/D020249/hormone-replacement-therapy
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/substitutionsterapi
Ja sekä nikotinersättning että nikotinsubstitution...

**Comment by mirmaid** [comment]
^ Olisiko siis kuitenkin ollut mahdollista pitää myös yleinen _korvaushoito_, kun tapauksia voi olla aika monenlaisia (vrt. Ilonan listaus, hajoaa jo noin pienessä määrässä). Vai laitetaanko muissa vain _hoito_ & 653 korvaushoito?

**Comment by ilona-x** [comment]
En haluaisi jättää yleistä korvaushoitoa sanastoon. Mielestäni useammassa viitteessä korvaushoito-termin poisjääminen ei heikentäisi kuvailua juurikaan. Esimerkikiksi noissa munuaisten korvaushoito -tapauksissa  riittäisi varmasti tietueissa jo oleva "dialyysihoito". Hemofilian osalta riittäisi varmaan pelkkä "hoito". Ja tuo verenvuotojen korvaushoito kuulostaa hassulta, kun kyseessä luultavimmin verensiirto (joka on myös tietueessa asiasanana). Synnytys-aiheisessa artikkelissa voisi olla verensiirto, nestehoito. D-vitamiinia käsittelevän väitöskirjan osalta termiä on käytetty vain e-version kuvailussa, painetun osalta ei ole koettu tarpeelliseksi.

Lähinnä näiden tarpeellisuus epäilyttää, kun kyse kuitenkin lääketieteestä eikä MeSHistä löydy vastaavia termejä, lukuun ottamatta tuota "munuaisten korvaushoidot".

Mielestäni suurempi haitta olisi, että jos sanastossa on myös korvaushoito sitä käytettäisiin varmasti niissäkin tapauksissa, joissa olisi tarjolla tarkempi termi, joka taas saattaisi jäädä laittamatta.

**Comment by mirmaid** [comment]
^ Näinhän se on. Luin eilen verenvuodon korvaushoidosta ja se oli kyllä moninainen prosessi, joka sisälsi paljon muutakin kuin verensiirron, mm. hyytymistekijöiden korvaushoitoa. Mutta toki ilmankin pärjätään, mietin vaan, tuleeko kuitenkin yhä enemmän erilaisten puutosten tai elimiston toimintahäiriöiden korvaushoitoja sitä mukaa mitä enemmän ihmisen rakenneosia pystytään keinotekoisesti korvaamaan.

**Comment by FinMeSHienPaimentaja** [comment]
"Korvaushoito"-termiä ei kannattane pitää sanastossa, sillä edellytyksellä, että löytyy tarkempiakin termejä. Eli komppaan Ilonaa. Sitä paitsi vähän hassulta kuulostaa, josko 'kaiken mahdollisen' kanssa tulisi se "korvaushoito" - mielestäni riittää esim. "albumiinit" ja "hoito".

**Comment by FinMeSHienPaimentaja** [comment]
Vielä MeSH-termeistä ja FinMeSH:eistä:
korvaushoitoja löytyy mm. 

Continuous Renal Replacement Therapy  jatkuva munuaisten korvaushoito  
Enzyme Replacement Therapy  entsyymikorvaushoito   
Estrogen Replacement Therapy  estrogeenikorvaushoito  
Hormone Replacement Therapy  hormonikorvaushoito  
Hybrid Renal Replacement Therapy  hybridi munuaiskorvaushoito  
Intermittent Renal Replacement Therapy  jaksoittainen munuaiskorvaushoito  
Mitochondrial Replacement Therapy  mitokondriaalinen korvaushoito
Opiate Substitution Treatment  opiaattikorvaushoito
Renal Replacement Therapy  munuaisten korvaushoidot

"munuaisten korvaushoidot" kuulostaa keinotekoiselta, miksei voi olla "munuaisdialyysi" tms.? Koska "hemodialyysi", "munuaisdialyysi" on eri termi (tarkempi), joka  on "munuaisten korvaushoidot" alla:

https://meshb.nlm.nih.gov/record/ui?name=Renal%20Replacement%20Therapy

Käytännön asiasanoitustyössä "munuaisdialyysi" on näppituntumani mukaan kuitenkin se, jota (ainakin lääketieteen puolella) eniten tarvitaan näistä munuaisten korvaushoidoista.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta korvaushoito. Korjataan jäljellä olevat viitteet tapauskohtaisesti.
