### ISSUE TITLE
spatiaalinen analyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8033]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[spatiaalinen analyysi](http://www.yso.fi/onto/ysa/Y206667) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Paikkatieto-ontologiatyöryhmän puolesta antaisin palautetta YSOssa olevasta käsitteestä "spatiaalinen analyysi". Tälle käsitteelle olisi hyvä lisätä vähintään altLabeliksi, mutta ehkä jopa prefLabeliksi, "paikkatietoanalyysi". 

#### Perustelut ehdotukselle   

Ainakin Maanmittauslaitos ja muut paikkatietoalan organisaatiot käyttävät vakiintuneesti suomeksi termiä paikkatietoanalyysi.

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/paikkatietoanalyysi

**Comment by LeKorsu** [comment]
Peukku paikkatietoanalyysin muuttamisesta prefLabeliksi.

**Comment by EsaMPKK** [comment]
> Peukku paikkatietoanalyysin muuttamisesta prefLabeliksi.

Peukku peukulle.

**Comment by YSO-kokous** [comment]
Hyväksytään. Päätermiksi paikkatietoanalyysi ja entinen päätermi ohjaustermiksi.
