### ISSUE TITLE
laivanrakentajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8035]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laivanrakentajat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kun meiltä laiva lähtee ulos, ni siittä voi olla kaikki ylpeitä 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [laivanrakentajat](http://finto.fi/yse/fi/page/Y508035)

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. skeppsbyggare ET fartygsbyggare

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
