### ISSUE TITLE
oikeustaju

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8037]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oikeustaju](http://www.yso.fi/onto/ysa/Y113760) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT: oikeuskäsitys, oikeudentunto 

#### Perustelut ehdotukselle   

Ovat melko synonymisiä, ks. Kielitoimiston sanakirja

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
