### ISSUE TITLE
perkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8038]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[perkaus](http://www.yso.fi/onto/ysa/Y195162) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne vai jaetaanko? 

#### Perustelut ehdotukselle   

Käytetty myös muusta kuin kalan perkauksesta, ks. Melinda. Tarkenne tarvitaan jos todella rajataan vain siihen?

**Comment by LeKorsu** [comment]
Finnan kuvista fintossa näkyy tosiaan olevan ainakin taimikon(metsän)perkausta, ojanperkausta ja kalanperkausta. Metsäpuolella perkauksen voisi kenties ohjata harvennukseen, vai ovatko ne kaksi eri asiaa?

**Comment by ilona-x** [comment]
YSOssa erikseen joenperkaus KT koskenperkaus http://www.yso.fi/onto/yso/p9711

**Comment by mariaforsen** [comment]
Ruotsiksi on mahdollista niputtaa perkaus merkityksessä "puhdistaminen", mutta ei "metsänperkauksia" yms. samaan termiin kuin sienten, kalojen jne.

YSOssa on jo röjning=raivaus ja gallring=harvennus joten niitä merkityksiä ei tarvita, vaan voidaan ohjata korvatulla termillä.

**Comment by PaiviLipsanen** [comment]
Taimikon perkaus ja raivaus näyttäisivät tarkoittavan samaa alla olevassa tekstissä. (Metsänhoidon suositukset - Tapion julkaisuja)

Taimikon **varhaisperkaus**
Varhaisperkaus on taimikonhoidon tärkein työlaji. Siinä nuoresta taimikosta poistetaan kasvatettavien taimien kehittymistä haittaavaa lehtipuustoa. Varhaisperkauksen voidaan toteuttaa täys- tai reikäperkauksena. Täysperkauksessa taimikosta poistetaan pääsääntöisesti kaikki lehtipuuvesakko lukuun ottamatta puita, jotka säästetään monimuotoisuuden turvaamiseksi. Siemensyntyisiä lehtipuutaimia voidaan jättää taimikkoa täydentämään. Reikäperkauksessa poistetaan kilpaileva kasvusto vähintään metrin säteellä kasvatettavien taimien ympäriltä. Välialueilta poistetaan lisäksi selvästi etukasvuiset puut.
Lehtipuut vesovat **raivauksen** jälkeen. Vesomisen voimakkuus riippuu muun muassa kasvupaikan viljavuudesta, kosteudesta ja raivausajankohdasta. Vesomista voidaan vähentää, jos perkaus tehdään
keskikesällä. Ajankohtaa tärkeämpi on kuitenkin se, että varhaisperkaus tulee tehdyksi. Voimakkaasti
vesoittuvissa taimikoissa varhaisperkaus voidaan joutua tekemään jopa kahteen kertaan.
Kitkemällä poistettavat taimet maasta juurineen, voidaan tehokkaasti estää varhaisperkauksen jälkeinen vesominen. Koneellisesta kitkennästä on hyviä kokemuksia kivennäismailla. Kasvatettava taimikko saa riittävästi etumatkaa kitkennän jälkeen syntyviin puihin nähden. Kitkentä on taloudellisesti perusteltu, jos sillä voidaan välttää taimikonharvennus, jolloin kitkentää seuraava toimenpide on ensiharvennus.
Lähde: Metsänhoidon suositukset - Tapion julkaisuja, s. 137
https://www.metsanhoitosuositukset.fi/wp-content/uploads/2019/09/Metsanhoidon_suositukset_Tapio_2019_verkko_1.2.pdf

**Comment by YSO-kokous** [comment]
Hyväksytään tpalonen-ehdottamat ohjaustermit edellä. Lisäksi muutetaan perkaus muotoon perkaus (elintarvikkeet). Ohjaustermiksi kalan perkaus.
