### ISSUE TITLE
laulusarjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8039]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[laulusarjat](http://www.yso.fi/onto/ysa/Y505101) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Laulusarjojen kuvailua varten olisi hyvä olla tämä käytettävissä, kun "sarjat" mieltyy helposti yksinomaan soitinmusiikiksi (cembalosarjoiksi, orkesterisarjoiksi yms) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja LCGFT-siltaus ehdotetulle SLM-termille: **[Song cycles](http://id.loc.gov/authorities/genreForms/gf2014027101)**

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. Määritelmä YSOsta.
LT laulumusiikki

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
