### ISSUE TITLE
organisatoriset tekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8040]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

organisatoriset tekijät 

#### Ehdotettu termi ruotsiksi   

organisatoriska  faktorer 

#### Ehdotettu termi englanniksi   

organisational factors 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vaikutukseen liittyvä rooli](http://www.yso.fi/onto/yso/p2833) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Inhimilliset  ja  organisatoriset  tekijät  –  Eurooppalaisen  lainsäädännön   vaatimukset   rautatietoimintojen   turvallisuusjohtamisessa. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Tarkoitusta täsmentävä selite   

Railway Safety & Standard Boardin (RSSB) määritelmän mukaan inhimillisillä ja organisatorisilla tekijöillä (Human and Organisational Factors, HOF) tarkoitetaan kaikkia ihmisiin liittyviä tekijöitä, jotka tulee ottaa huomioon järjestelmän tai or-ganisaation  koko  elinkaaren  aikaisen  turvallisuuden  varmistamiseksi.  (Under-standing   Human   Factors...   2008,   RSSB)   Euroopan   unionin   rautatieviraston      (European Union Agency for Railways, ERA) määritelmän mukaan inhimillisillä ja organisatorisilla tekijöillä puolestaan tarkoitetaan kaikkia niitä ihmisen piirteitä ja  organisaation  aspekteja,  jotka  tulee  huomioida  systeemin  tai  organisaation  elinikäisen  turvallisuuden  ja  tehokkuuden  varmistamiseksi.  (Safety  manage-ment system requirements... 2018, ERA) 

**Ehdottajan organisaatio:** kk **Termiehdotus Fintossa:** [organisatoriset tekijät](http://finto.fi/yse/fi/page/Y508040)

**Comment by mirmaid** [comment]
2 viitettä Melindassa, 93 Googlella (jos poistetaan samankaltaiset tulokset).

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa organisatoriset tekijät, ohjaustermiksi organisaatiotekijät.

**Comment by mariaforsen** [comment]
Sv. organisatoriska faktorer ET organisationsfaktorer
