### ISSUE TITLE
Timbaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8041]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Timbaalit 

#### Ehdotettu termi englanniksi   

Timbales 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

LP-levyt 

#### Perustelut ehdotukselle   

Puuttuu YSAsta (lisäksi puuttuu muita melko yleisiä lyömäsoittimia esim. Bongorummut, Cajon ja  Djembe.) 

**Termiehdotus Fintossa:** [Timbaalit](http://finto.fi/yse/fi/page/Y508041)

**Comment by jtuohini** [comment]
Jos tarve on siis äänitteen kuvailussa, jossa kyseistä soitinta käytetään eikä soitinta käsittelevän kirjallisuuden kuvailussa, niin termi kuuluu Seko-sanastoon, ei Ysoon. Muut mainitut soitintermit Sekossa jo ovatkin: [**bongorummut**](http://urn.fi/urn:nbn:fi:au:seko:00148), [**cajón**](http://urn.fi/urn:nbn:fi:au:seko:00181) ja [**djembe**](http://urn.fi/urn:nbn:fi:au:seko:00281).

**Comment by jtuohini** [comment]
Ja LCMPT-siltaus: **[timbales criollos](http://id.loc.gov/authorities/performanceMediums/mp2013015732)**

**Comment by mariaforsen** [comment]
Sv. timbales

**Comment by YSO-kokous** [comment]
Käsite sopisi SEKOn lisäksi myös YSOon. Odotetaan kuitenkin Muusan kantaa vielä tähän.

**Comment by MUUSA-kokous** [comment]
SEKOssa on timbales. Muusa kannattaa samaa muotoa YSOssa. Ohjaustermiksi timbaalit.

**Comment by jtuohini** [comment]
Olisiko sittenkin parempi molemmissa käytettäväksi muodoksi ehdotuksen _**timbaalit**_, varsinkin kun suomenkielinen wikipedia pitää sitä muotoa ensisijaisena (itse asiassa ainoana) [https://fi.wikipedia.org/wiki/Timbaalit] ja Wikidata myös [https://www.wikidata.org/wiki/Q379248]. LCMPT-siltaus varmaan lisätään Sekoon?

**Comment by tpalonen** [comment]
Timbaalin merkitys suomisanakirja.fi:n mukaan on "korkeareunaisessa vuoassa (vesihauteessa) kypsennetty mureke". Google-haku tuottaa lähinnä ruokia hakutulokseksi.
https://www.suomisanakirja.fi/timbaali

Timbales näyttäisi olevan yleisempi nimitys soittimelle suomeksi. Esim. Soitin-Laineessa, Vantaan musiikissa, Tampereen musiikissa ja Thomannin suomenkielisessä verkkokaupassa soittimen nimi on timbales (tai timbalesit). Timbaalit muotoa taas käyttävät ainakin discoland.fi ja gear4music.fi.
https://www.soitinlaine.fi/timbales-ja-telineet
https://www.vantaanmusiikki.fi/timbales
https://www.tampereenmusiikki.fi/verkkokauppa/haku/timbales
https://www.soitinlaine.fi/rummut/lyomasoittimet-world-percussion/timbales-ja-telineet
https://www.thomann.de/fi/timbalesit.html

**Comment by MUUSA-kokous** [comment]
Muusa pitäytyy aiemmassa kannassaan.

**Comment by mirmaid** [comment]
Ruoan nimi muuten tulee rummusta, https://en.wikipedia.org/wiki/Timbale_(food).

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa timbales, ohjaustermeiksi timbaalit ja timbalesit.
