### ISSUE TITLE
duoraitiovaunut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8042]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

duoraitiovaunut 

#### Ehdotettu termi englanniksi   

tram-trains 

#### Ehdotettu termi ruotsiksi   

duospårvagn 

#### Vaihtoehtoiset termit ja ilmaisut   

duoraitioliikenne 
duoraitiotie 

#### Ehdotettu yläkäsite YSOssa (LT)   

[maakulkuneuvot](http://www.yso.fi/onto/yso/p4379) 

#### Assosiatiiviset (RT)   

[pikaraitiotiet](http://www.yso.fi/onto/yso/p28052) 
[kevytjunat](https://finto.fi/yso/fi/page/p21572)

#### Tarkoitusta täsmentävä selite   

https://fi.wikipedia.org/wiki/Duoraitiovaunu 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Duoraitioliikenteen mahdollisuudet Suomessa :junaratikka lainsäädännön ja tekniikan näkökulmasta /Jouni Kiviniitty. 

**Ehdottajan organisaatio:** kk **Termiehdotus Fintossa:** [duoraitiovaunut](http://finto.fi/yse/fi/page/Y508042)

**Comment by satuniininen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7709

**Comment by mirmaid** [comment]
Koska eroaa tavallisesta pikaraitiovaunusta siinä, että pystyy kulkemaan myös rautatiellä, tämä voidaan ottaa myös erikseen (tai jos halutaan, ohjaustermiksi _kevytjunat/pikaraitiovaunut_-käsitteelle).

**Comment by YSO-kokous** [comment]
Muutetaan käsitteen kevytjunat käytettäväksi termiksi pikaraitiovaunut. Lisätään ohjaustermi kevytjunat KÄYTÄ pikaraitiovaunut sekä duoraitiovaunut KÄYTÄ pikaraitiovaunut.
