### ISSUE TITLE
sosiaaliset yritykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8043]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sosiaaliset yritykset](http://www.yso.fi/onto/ysa/Y112004) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT yhteiskunnalliset yritykset 

#### Perustelut ehdotukselle   

https://www.lut.fi/uutiset/-/asset_publisher/h33vOeufOQWn/content/yhteiskunnallisia-ongelmia-ratkovat-yritykset-kasvavat-muita-vauhdikkaammin-laman-aikana 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by LeKorsu** [comment]
Tämän TEM:n julkaisun mukaan (https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/162094/TEM_2020_10.pdf) sosiaaliset yritykset ja yhteiskunnalliset yritykset eivät ole täysin sama asia (määritelmiä, s. 13): 

"Selvitystehtävän taustana toimivat seuraavat keskeiset määritelmät: Ensinnäkin yhteiskunnalliset yritykset (social enterprise) on määritelty kuuluvan osaksi yhteisötaloutta
(social economy) ja yhteisötalouden yrityksiä (social economy enterprise). Yhteisötalouteen
kuuluu osuuskuntia, keskinäisiä yhteisöjä, voittoa tavoittelemattomia yhdistyksiä, säätiöitä
ja yhteiskunnallisia yrityksiä. Sosiaaliset yritykset3 (work integration social enterprise), jotka
pyrkivät integroimaan heikossa asemassa olevia henkilöitä työmarkkinoille, voivat olla
yhteiskunnallisia yrityksiä."

Tuo 3 tarkoittaa alahuomautusta, jossa viitataan Lakiin sosiaalista yrityksistä:   "Laki sosiaalisista yrityksistä (1351/2003)edellyttää sosiaalisilta yrityksiltä työntekomahdollisuuksia erityisesti
henkilöille, joiden vamma tai sairaus vaikeuttaa työllistymistä tai tietyin edellytyksin pitkään työttömänä olleille. Sosiaalinen yritys on työ- ja elinkeinoministeriön ylläpitämään sosiaalisten yritysten rekisteriin merkitty elinkeinotoimintaa harjoittava yhteisö, säätiö tai muu elinkeinonharjoittaja, joka on merkitty kaupparekisteriin ja joka tuottaa liiketaloudellisin periaattein hyödykkeitä. Palveluksessa olevista työntekijöistä (työllistettyjen osuus) on oltava
vähintään 30 prosenttia henkilöitä, joiden vamma tai sairaus vaikeuttaa työllistymistä, tai näiden ja muiden laissa mainittujen heikossa työmarkkina-asemassa olevien yhteenlaskettu osuus on vähintään 30 prosenttia."

**Comment by ilona-x** [comment]
YSOssa:
sosiaalinen yrittäjyys KÄYTÄ **yhteiskunnallinen yrittäjyys** http://www.yso.fi/onto/yso/p24434
sosiaalinen yrittäjyys KÄYTÄ **sosiaaliset yritykset** http://www.yso.fi/onto/yso/p11851

http://tieteentermipankki.fi/wiki/Kasvatustieteet:sosiaalinen_yritt%C3%A4jyys

**Comment by YSO-kokous** [comment]
Ei muutoksia. Ks. keskustelu yllä.
