### ISSUE TITLE
solmut (liikenne)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8044]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

solmut (liikenne) 

#### Ehdotettu termi englanniksi   

traffic nodes 

#### Ehdotettu termi ruotsiksi   

knutpunkter 

#### Vaihtoehtoiset termit ja ilmaisut   

solmupisteet 
solmupaikat 

#### Assosiatiiviset (RT)   

[matkaketjut](http://www.yso.fi/onto/yso/p38278) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

Esiintyy paljon Väyläviraston julkaisuissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://julkaisut.vayla.fi/pdf12/vj_2019-09_valtakunnalliset_liikenteelliset_web.pdf 

#### Tarkoitusta täsmentävä selite   

Solmulla tarkoitetaan kaupunkia tai toiminnallista kaupunkiseutua. Kaupunkiseutujen välinen väyläverkko yhdistää solmuja. Solmussa on henkilö- ja tavaraliikenteen solmupisteitä. Solmu on merkittävä joko henkilö- tai tavaraliikenteen tai molempien kannalta. 
https://www.sitowise.com/fi/uutishuone/ajankohtaista/liikenteelliset-solmut-ja-niiden-merkitys 

**Termiehdotus Fintossa:** [solmut (liikenne)](http://finto.fi/yse/fi/page/Y508044)

**Comment by mirmaid** [comment]
Vaatisi kai tarkenteen lisäämistä myös toiselle _solmut_-käsitteelle...solmu on siis kaupunki ja solmupiste kaupungissa sijaitseva liikenteen terminaali (?).

**Comment by ilona-x** [comment]
PTOssa näyttää olevan tuo ehdotuksen selitetekstissä mainittu liikennesolmupiste http://paikkatiedot.fi/def/1001002/p644

**Comment by mariaforsen** [comment]
PTOn transportknude on virheellinen. Vaatii tarkenteita tms. myös ruotsiksi, jos ylipäätään on tarpeen ja tarpeeksi selkeä.

**Comment by YSO-kokous** [comment]
Selvitetään selkeämpää termiä, esim. solmukohdat tai liikenteen solmukohdat. Jatketaan seuraavassa kokouksessa. @satuniininen

**Comment by EsaMPKK** [comment]
> Selvitetään selkeämpää termiä, esim. solmukohdat tai liikenteen solmukohdat. Jatketaan seuraavassa kokouksessa. @satuniininen

Juu liikenteen solmukohdat 🙋

**Comment by LeKorsu** [comment]
Liikenteen solmukohdat kuulostaa korvissani yleiskielisemmältä kuin liikennesolmupiste/pisteet.

**Comment by YSO-kokous** [comment]
Liikenteen solmukohdat on terminä salliva ja sai eniten kannatusta, termiä käytetty monen tasoisissa solmukohdissa (kaupunginosa, kaupunki). Ohjaustermeiksi solmut (liikenne) ja solmupisteet ja liikennesolmupisteet.

**Comment by mariaforsen** [comment]
Sv. trafikknutpunkter ET knutpunkter, trafikens knutpunkter
