### ISSUE TITLE
soitinrakennus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8045]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[soitinrakennus](http://www.yso.fi/onto/ysa/Y98904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT soitinvalmistus 

#### Perustelut ehdotukselle   

Synonymi, ks. huomautus

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
