### ISSUE TITLE
sopimuksellisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8046]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sopimuksellisuus](http://www.yso.fi/onto/ysa/Y149754) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT sopimuksenmukaisuus? 

#### Perustelut ehdotukselle   

Olisiko uusi KT sopimuksenmukaisuus ok?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**sopimuksellinen**
sopimukseen perustuva, sopimus-.
Kauppasuhteiden sopimuksellinen pohja.

**Comment by YSO-kokous** [comment]
Tutkitaan vielä. Kantoja esitettiin puolesta ja vastaan (mietittiin, viittaavatko termit samaan asiaan). Seuraava kokous.

**Comment by ilona-x** [comment]
Käytetty Melindassa 26 kertaa.

sopimuksellisuus otettu sanastoon v. 2006 ilmeisesti v. 2006 ilmestyneen julkaisiun "Sopimuksellisuus maaseutupolitiikassa" http://urn.fi/URN:ISBN:952-487-021-5 perusteella.

sopimuksellisuus liittyy myös ulkoistamiseen, esim. gradu : Sopimuksellisuus ja ulkoistaminen terveydenhuollon palvelutuotannossa http://urn.fi/urn:nbn:fi:uef-20110469

Ja vielä yksi julkaisu, jossa määritelty sopimuksellisuutta: Sopimuksellisuus, talous ja johtaminen: New Public Management sopimusohjauksessa ja julkisten organisaatioiden sopimustenhallinnassa http://urn.fi/URN:NBN:fi-fe2018053125042

Näiden perusteella olisin sillä kannalla, että sopimuksenmukaisuus ja sopimuksellisuus eivät ole sama asia.
https://termipankki.fi/tepa/fi/haku/sopimuksen%20mukainen
Esim. kauppalaissa tavaran sopimuksenmukaisuus: https://www.finlex.fi/fi/laki/ajantasa/1987/19870355#V14

Olisin kaivannut ehdotukseen esimerkkiaineistoa, jonka perusteella KT-muotoehdotus on tehty.

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä. Tutkitaan, onko käytetty johdonmukaisesti kuvailussa ja mikä on oikea vastine ruotsiksi. Ehkä tarvittaneen myös huomautus, jos jää tähän muotoon.

**Comment by ilona-x** [comment]
Käytetty kuvailussa pääosin julkaisuissa, joissa sopimuksellisuutta käsitellään uuden julkisjohtamisen (new public management), julkisen sektorin ja ulkoistamisen yhteydessä. Englanniksi tästä näyttää Melindasta löytyvissä aineistoissa käytetyn esim. termejä contracting ja contractualisation. Jossain myös contracting out, mutta toisaalla tämä contracting out (ulkoistaminen) ja contracting (sopimuksellisuus) oli erotettu toisistaan.

Joidenkin viitteiden osalta ei ole mahdollista päätellä, mikä on ollut käyttötarve. Osassa vaikuttaisi olevan mahdollista korvata termillä "sopimukset". Yhdessä väitöskirjassa oli kehitelty eläkkeelle siirtymiseen ja työssä jatkamiseen liittyvä "sopimuksellisuuden kehä", ja tässä kuvailussa oli käytetty termiä sopimuksellisuus. Lienee poistettavissa tuosta yhteydestä, jos katsotaan tarpeelliseksi jotain rajata tätä termin käyttöä.

Viitteitä, joissa olisi tarvittu alunperin ehdotettua "sopimuksenmukaisuus"-termiä ei tullut vastaan näissä "sopimuksellisuus"-termillä kuvailluissa.

Yhdessä viitteessä sopimuksellisuus käytetty mahdollisesti tarkoitettaessa sopimusperusteisuutta/sopimukseen perustuvaa.

**Comment by YSO-kokous** [comment]
Vaihdetaan käytettäväksi termiksi sopimusperusteisuus, jos se soveltuu myös uuden julkisjohtamisen piiriin.
