### ISSUE TITLE
helppokäyttöisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8047]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

helppokäyttöisyys 

#### Ehdotettu termi ruotsiksi   

lätthanterlighet 

#### Ehdotettu termi englanniksi   

ease of use 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käytettävyys](http://www.yso.fi/onto/yso/p3785) 

#### Vastaava käsite muussa sanastossa   

TSR : <http://www.yso.fi/onto/tsr/p11535> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sähköisten terveyspalveluiden koettu hyödyllisyys ja koettu helppokäyttöisyys : potilaiden ja lääkäreiden arviot vaikutuksista / 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[00 Yleistermit](http://www.yso.fi/onto/yso/p26556) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [helppokäyttöisyys](http://finto.fi/yse/fi/page/Y508047)

**Comment by mirmaid** [comment]
3 viitettä Melindassa. Voisiko olla jopa KÄ _käytettävyys_?

**Comment by ilona-x** [comment]
käytettävyys
en   usability
määritelmä
ominaisuus, joka ilmentää sitä, miten järjestelmä, laite, ohjelma tai palvelu soveltuu suunniteltuun tarkoitukseen tietylle kohderyhmälle
huomautus
Hyvän käytettävyyden vastakohta on huono käytettävyys tai epäsopivuus.
Tähän käsitteeseen viitataan joissakin yhteyksissä myös yleiskielen ilmauksilla käyttökelpoisuus, käyttöönsoveltuvuus, helppokäyttöisyys ja käyttäjäystävällisyys.
Lähde: Tietotekniikan termitalkoot, 2002-06-03

**Comment by YSO-kokous** [comment]
Otetaan ohjaustermiksi:
helppokäyttöisyys KÄYTÄ käytettävyys
käyttäystävällisyys KÄYTÄ käytettävyys
