### ISSUE TITLE
suomettuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8048]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suomettuminen](http://www.yso.fi/onto/ysa/Y110287) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan huomautus paremmaksi, myös sillä tavalla että toimii yleismerkityksessä, eli ei ainoastaan Suomi-Neuvostoliitto-kontekstissa 

#### Perustelut ehdotukselle   

Termin merkitys on laajempi, englanninkielisen huomautuksen mukaisesti. Ks. https://fi.wikipedia.org/wiki/Suomettuminen

**Comment by mirmaid** [comment]
YSAssa ei huomautusta, onko tarpeen?

**Comment by AuHo22** [comment]
Toiminee ilman huomautusta ; vrt. balkanisoituminen myös irronnut alkuperäisestä yhteydestä (ei YSO-termi)

**Comment by YSO-kokous** [comment]
Poistetaan huomautus suomettuminen-käsitteeltä.
