### ISSUE TITLE
oikeusvarmuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8049]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oikeusvarmuus](http://www.yso.fi/onto/ysa/Y117617) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Termejä ja Wikidata-linkitystä pohdittava. 

#### Perustelut ehdotukselle   

IATEn mukaan oikeusvarmuuden vastineena ei pidä käyttää englanniksi legal security, vaan legal certainty tai certainty of law. Lisäksi YSOn Wikidata-linkityksessä tuli vastaan ongelma oikeusvarmuuden ja oikeusturvan välillä. Wikidatassa löytyy kohde https://www.wikidata.org/wiki/Q1068288 (due process), jossa ruotsin vastineena rättssäkerhet eli oikeusvarmuus, mutta kohteen englanninkielinen termi due process taas on IATEn mukaan suomeksi oikeudenmukainen menettely. Lisäksi 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Oikeustiede:oikeusvarmuus_(oikeusteoria)
https://tieteentermipankki.fi/wiki/Nimitys:oikeusturva

EKSsissä http://www.eduskunta.fi/kirjasto/EKS/:

Asiasana: 		        **oikeusvarmuus**
Asiasana ruotsiksi:	        rättssäkerhet
Asiasana englanniksi:	legal security

Asiasana:		                **oikeusturva**
Korvaa termin:		oikeussuoja
Asiasana ruotsiksi:	        rättsskydd
Asiasana englanniksi:	legal protection, legal safeguards, legal safety


MOT Pro Englanti; englanti-suomi:

due process s (myös due process of law) oik
oikeusturva

oikeusturva
protection of law, legal protection

oikeusvarmuus oik
legal security

**Comment by AuHo22** [comment]
https://vnk.fi/documents/10616/3457861/Valtioneuvoston+ohjes%C3%A4%C3%A4nt%C3%B6+%28VNOS%29+-sanasto+%28fi-en%29

**oikeusturva**
1. legal protection
2. legal security
3. due process
Esim. 2 taata yksilölle oikeusturva
Example 2: to guarantee legal security for the individual
Määritelmä 3: oikeusturva; oikea menettely; puolueeton oikeudenkäynti
Definition 3: rule that the forms of law must be followed correctly [Dictionary of Law]
Huom. ks. myös oikeusvarmuus

**oikeusvarmuus**
legal certainty; certainty of law
Määritelmä: Yhteisön oikeudessa oikeusvarmuuden periaate merkitsee oikeusjärjestyksen
ennakoitavuutta ja pysyvyyttä. Siitä ei ole määrätty primaarioikeudessa, vaan se
perustuu yhteisöjen tuomioistuimen oikeuskäytäntöön. Oikeusvarmuus toteutuu
seuraavien, yksityiskohtaisempien periaatteiden kautta: taannehtivien oikeusvaikutusten kielto, oikeutettujen odotusten suoja, saavutettujen etujen suoja, määräaikojen laskeminen ja ymmärrettävän kielen vaatimus. [TIS-termipankki]

**Comment by mirmaid** [comment]
Eli oikeusvarmuus eng. > legal certainty tai certainty of law

Due process: ei aiheuttane toimenpiteitä? Rättssäkerhet on nyt wikidatassa vastineena näille molemmille käsitteille.

**Comment by YSO-kokous** [comment]
Legal certainty on hyvä englannin vastine tälle. Ei muita muutoksia.
