### ISSUE TITLE
biomassa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8050]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[biomassa](http://www.yso.fi/onto/ysa/Y94877) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan käsite kahdeksi. 

#### Perustelut ehdotukselle   

Termillä on kaksi eri merkitystä.
Ks. https://en.wikipedia.org/wiki/Biomass
Ja: https://en.wikipedia.org/wiki/Biomass_(ecology) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Nimitys:biomassa

Suomenkielisessä wikipediassa molemmat merkitykset on käsitelty samassa artikkelissa: https://fi.wikipedia.org/wiki/Biomassa

**Comment by FinMeSHienPaimentaja** [comment]
Energia-näkökulma: "bioenergia" on jo YSO:ssa
https://finto.fi/yso/fi/page/p6167

**Comment by jarmosaarikko** [comment]
Jos ja kun tarvitaan erilliset käsitteet, niin  niihin tarvitaan tarkenne ja mielellään määritelmä:
-  **biomassa (biologia)**   
-- Jonkin populaation tai alueen elävän aineksen kokonaismäärä tietyllä hetkellä, ilmaistaan joko tuore- tai kuivapainona (BS) - Lähde: Tieteen termipankki, . 
- esim.  **biomassa (luonnonvarat)** tai biomassa (energialähteet)   RT  bioenergia, biotekniikka
--  Eloperäinen (orgaaninen) materiaali tai aines, joka syntyy pieneliöiden, kasvien tai eläinten kasvaessa.  - Lähde: Tieteen termipankki.

**Comment by mirmaid** [comment]
Ainakaan _biomassa (luonnonvarat)_ ei taida erotella toivotulla tavalla. Silloin kun biomassaa tarkastellaan raaka-aineena, ei välttämättä ole kyse energiantuotannosta (esim. https://jukuri.luke.fi/handle/10024/545917), joten tarkenteen pitäisi olla laajempi, esim. _biomassa (teollisuus)_ tai _biomassa (raaka-aineet)_.

**Comment by mirmaid** [comment]
Wikipediassa toisen merkityksen tarkenne on ekologia: https://en.wikipedia.org/wiki/Biomass_(ecology).

**Comment by mirmaid** [comment]
Käytetty Melindassa n. 1600 kertaa.

**Comment by YSO-kokous** [comment]
Biomassa (ekologia) ja biomassa (teollisuus).
