### ISSUE TITLE
dryadit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8051]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dryadit 

#### Ehdotettu termi englanniksi   

dryads 

#### Ehdotettu termi ruotsiksi   

dryader 

#### Vaihtoehtoiset termit ja ilmaisut   

puunyfmit [fin] 
trädnymfer [swe] 
tree nymphs [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[nymfit](http://www.yso.fi/onto/yso/p26052) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85039814> 
Wikidata : https://www.wikidata.org/wiki/Q202474 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa; riittävän tarkkaa asiasanaa ei ole vanhastaan YSOssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sibeliuksen Dryadit ym. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [dryadit](http://finto.fi/yse/fi/page/Y508051)

**Comment by mirmaid** [comment]
3 viitettä Melindassa (merkitty Kaunokiksi).

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
