### ISSUE TITLE
kognitiiviset harhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8052]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kognitiiviset harhat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Heuristics and biases in organizing – Conceptual tools for examinations of cognitive biases in organizational routines 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kognitiiviset harhat](http://finto.fi/yse/fi/page/Y508052)

**Comment by mirmaid** [comment]
Kognitiivinen vinouma, -harha, -värittymä tai -vääristymä (engl. cognitive bias) on psykologinen käsite, jolla tarkoitetaan ihmisillä esiintyviä taipumuksia hahmottaa ja painottaa havaintojaan, tulkintojaan ja informaatiota tietyillä tavoin. https://fi.wikipedia.org/wiki/Kognitiivinen_vinouma

Melindassa kerran _kognitiiviset vinoumat_.

**Comment by mariaforsen** [comment]
Sv. kognitiva biaser
https://www.psykologiguiden.se/psykologilexikon/?Lookup=kognitiv+bias

**Comment by LeKorsu** [comment]
Finmeshissä kognitiiviset häiriöt http://www.yso.fi/onto/mesh/D003072. Tämä on ilmeisesti eri asia (cognition disorders, kognitiva störningar)

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa kognitiiviset vinoumat, ohjaustermiksi kognitiiviset harhat. Vinoumat lienee selkeämpi termi.
