### ISSUE TITLE
jäännösjännitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8053]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jäännösjännitykset 

#### Ehdotettu termi englanniksi   

Residual stresses 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85113138> 
Wikipedia : https://fi.wikipedia.org/wiki/J%C3%A4%C3%A4nn%C3%B6sj%C3%A4nnitys 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Residual stress, microstructure and cracking characteristics of flame cut thick steel plates 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda:
jäännnösjännitykset x 4
jäännösjännitys x 3 

#### Tarkoitusta täsmentävä selite   

http://www.tsk.fi/tepa/fi/haku/j%C3%A4%C3%A4nn%C3%B6sj%C3%A4nnitys 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [jäännösjännitykset](http://finto.fi/yse/fi/page/Y508053)

**Comment by mirmaid** [comment]
Jäännösjännitykset ovat materiaalin sisäisiä jännityksiä, jotka syntyvät materiaaliin mekaanisessa ja/tai termisessä muokkauksessa, kuten hitsauksen tai valssauksen yhteydessä. https://fi.wikipedia.org/wiki/J%C3%A4%C3%A4nn%C3%B6sj%C3%A4nnitys

**Comment by mariaforsen** [comment]
Sv. restspänningar ET egenspänningar 
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/restsp%C3%A4nning

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
