### ISSUE TITLE
denjongken kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8054]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

denjongken kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

A descriptive grammar of Denjongke (Sikkimese Bhutia) 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [denjongken kieli](http://finto.fi/yse/fi/page/Y508054)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Sikkimese_language

**Comment by mariaforsen** [comment]
Sv. sikkimesiska ET dranjongke

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Suomenkielinen muoto denjongken kieli. Englannin termi Sikkimese language viittaa samaan kieleen.
