### ISSUE TITLE
hydrogeelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8056]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hydrogeelit 

#### Ehdotettu termi ruotsiksi   

hydrogeler 

#### Ehdotettu termi englanniksi   

Hydrogels 

#### Ehdotettu yläkäsite YSOssa (LT)   

[geelit](http://www.yso.fi/onto/yso/p12973) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D020100> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Development and Characterization of Gellan Gum Based Hydrogels for Soft Tissue Engineering Applications 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda:
hydrogeelit x 2
hydrogeeli x 5 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hydrogeelit](http://finto.fi/yse/fi/page/Y508056)

**Comment by mirmaid** [comment]
LCSH: Hydrogels USE Colloids, http://id.loc.gov/authorities/subjects/sh85028453
