### ISSUE TITLE
televalvonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8057]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[televalvonta](http://www.yso.fi/onto/ysa/Y113217) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Huomautus poistetaan tai korjataan 

#### Perustelut ehdotukselle   

Käsitteellä ei saa olla useita merkityksiä

**Comment by ilona-x** [comment]
YSOssa siis näin:
HUOMAUTUS
Tarkoittaa 1) tapahtumien tai tilanteiden automaattista havaintaa ja tiedon välittämistä niistä televiestintää käyttäen 
2) tunnistustietojen hankkimista tietoverkossa lähetetyistä viesteistä

LÄHDE
Lähde: Valtiovarainministeriön tietoturvasanasto

**Comment by tpalonen** [comment]
Poistetaan huomautus.

**Comment by ilona-x** [comment]
Huomasin, että televalvonnalla on ohjaustermit: elektroninen valvonta, sähköinen valvonta, telekuuntelu
Eli onko kuitenkin ongelma, että tällä 2 merkitystä?

Ohjaustermeistä telekuuntelu viittaa siis tuohon merkitykseen 2) tunnistustietojen hankkimista tietoverkossa lähetetyistä viesteistä
ja  ohjaustermit elektroninen valvonta & sähköinen valvonta ilmeisesti tuohon 1) merkityksen. 

https://fi.wikipedia.org/wiki/Televalvonta

Sähköinen/elektroninen valvonta tuo Googlella esimerkiksi tällaisia tuloksia:
Työn elektroninen valvonta Suomessa https://www.julkari.fi/handle/10024/134952
Rangaistusjärjestelmä Sähköinen valvonta https://www.krits.fi/2018/02/sahkoinen-valvonta/

YSOssa tähän settiin mahdollisesti myös liittyvä etävalvonta KÄ etäseuranta

**Comment by ilona-x** [comment]
JUPOssa:
**telepakkokeinot** http://www.yso.fi/onto/jupo/p272
HUOMAUTUS
Kohteelta salaa suoritettavia pakkokeinoja kuten telekuuntelu ja -valvonta sekä tekninen kuuntelu, joiden käytöä valvoo eduskunnan oikeusasiamies

**telekuuntelu** http://www.yso.fi/onto/jupo/p269

**Comment by FinMeSHienPaimentaja** [comment]
Googlaamalla löytyy myös 1) merkityksessä "etävalvonta"-sanan käyttöä paljon, esim. kiinteistön etävalvonta.

**Comment by mariaforsen** [comment]
Huom. Sanastossa on jo kaukovalvonta https://finto.fi/yso/fi/page/?uri=p6926 =eng. telemonitoring 
https://termipankki.fi/tepa/fi/haku/kaukovalvonta
https://termipankki.fi/tepa/fi/haku/et%C3%A4valvonta

**Comment by mirmaid** [comment]
_Televalvonta_ ja _telekuuntelu_ ovat ilmeisesti tarkkaan ottaen eri asioita, [https://www.minilex.fi/a/telekuuntelu-televalvonta-ja-tekninen-tarkkailu](https://www.minilex.fi/a/telekuuntelu-televalvonta-ja-tekninen-tarkkailu).

Googlella nimenomaan televalvonta-termin käyttö näyttäisi olevan johdonmukaisesti merkityksessä 2. Melindassa käytössä on horjuvuutta, pitäisikö esim. [tässäkin](https://helda.helsinki.fi/bitstream/handle/10138/152499/TTA_114_Danielsson_M_kip___2012.pdf?sequence=1&isAllowed=y) puhua ennemmin _etäseurannasta_? _Valvontarangaistus_ on myös sanastossa.

**Comment by mirmaid** [comment]
EKS-sanastossa laajemmin: KT elektroninen valvonta, kameravalvonta, optinen valvonta, tekninen tarkkailu, telekuuntelu, tv-valvonta, videovalvonta

**Comment by mirmaid** [comment]
Käytetty Melindassa melko paljon aineistoissa, joissa eng. _surveillance_ - merkitys kyllä silloin laajempi kuin pelkkä suomalaisen lainsäädännön mukainen rikostutkinta, vaikka sekin sisältyy. 

Jos halutaan vain rajata pois [tämän](https://melinda.kansalliskirjasto.fi/byid/002511656) tyyppiset aineistot, riittäisikö ohjaustermien poisto tai tarkenteen lisääminen niille?

**Comment by mirmaid** [comment]
Jos _kaukovalvonta_ ja _etäseuranta_ nähdään synonyymeina, tehdään erillinen issue niiden yhdistämisestä.

**Comment by ilona-x** [comment]
Voisiko elektroninen valvonta & sähköinen valvonta (+mahdolliset tarkenteet) ohjata kaikkiin näihin: televalvonta, kaukovalvonta, etäseuranta ja mahdollisesti myös kameravalvonta?

**Comment by YSO-kokous** [comment]
Poistetaan ohjaustermit televalvonnalta. Elektroninen valvonta, sähköinen valvonta KÄ kaukovalvonta, etäseuranta, kameravalvonta. 

Vaihdetaan mahdollisesti päätermiksi telepakkokeinot, tutkitaan kuitenkin suhde tekniseen tarkkailuun.

**Comment by ilona-x** [comment]
> **Telekuuntelulla** tarkoitetaan rikoksesta epäillyn hallussa olevaan tai käyttämään teleliittymään (mm. matkapuhelin), sähköpostiosoitteeseen tai laitteeseen tulevan, ja hänen siitä lähettämänsä viestin kuuntelua, ja tallentamista salaa viestin sisällön selvittämiseksi.
> 
> **Televalvonnassa** taas on kysymys salassa pidettävien tunnistamistietojen (mm. puhelinnumerot) hankkimisesta viesteistä, jotka on lähetetty epäillyn hallussa olevasta tai käyttämästä liittymästä, osoitteesta tai laitteesta ja vastaanotettu tällaiseen. Tietoja voidaan saada myös matkaviestimen sijainnista. Televalvonnassa liittymä voidaan myös tilapäisesti sulkea. Asianomistajan suostumuksella televalvonta voidaan kohdistaa myös asianomistajan hallussa olevaan tai käyttämään liittymään.
> 
> **Tekninen tarkkailu** tapahtuu kuuntelemalla, katselemalla tai seuraamalla teknisin apuvälinein rikoksesta epäiltyä.

Lähde: https://oikeus.fi/tuomioistuimet/fi/index/asiat/rikosasiat/pakkokeinot.html

**Comment by mariaforsen** [comment]
Eli tarvittaisiin vielä telekuuntelu=teleavlyssning erillisenä sanastoon. 
https://oikeus.fi/tuomioistuimet/sv/index/malocharenden/brottmal/tvangsmedel.html

**Comment by YSO-kokous** [comment]
Televalvonnan päätermi ei muutu.
Otetaan sanastoon "telekuuntelu"
Korjataan "salakuuntelun" hierarkia ja RT suhteet niin, että merkitys rajautuu rikoksiin

Tutkitaan salakuuntelun käyttö Melindassa ja tarvittaessa lisätään sulkutarkenne
esim. salakuuntelu (rikokset)  tai salakuuntelu (laiton toiminta) vrt. salakatselu

**Comment by mariaforsen** [comment]
Joskus on rikoksen, vakoilun jne. raja häilyvä, olisiko mahdollista antaa olla siinä muodossa kuin nyt on? Melindassahan se on käytetty sekä selkeistä rikoksista että sellaisesta valtion, yrityksen jne. toiminnasta mistä ei tule seuraamuksia kenellekään.

**Comment by mirmaid** [comment]
^ Salakuuntelun termi siis? Edelleen kun katsoo Melindaa on aika vaikea hahmottaa, mihin pitäisi tulla _televalvonta_, mihin _telekuuntelu_, mihin _tekninen tarkkailu_ ja mihin _salakuuntelu_. Vaikka siis jättäisi etäseurannan pois. 

Esim. https://melinda.kansalliskirjasto.fi/byid/017433853

**Comment by mariaforsen** [comment]
Tarkoitin salakuuntelu joo. Mielestäni niillä muilla on kyllä aika selkeät rajaukset, eikä niitä varmaan käyttäisi (eikä varmaan pitäisikään käyttää) ellei aineistoissa mainita niitä. 

Etäseuranta käytetään kai lähinnä sairaanhoidon yhteydessä, siltä näyttää ainakin googlessa (ja ruotsin vastine sen mukainen) Jos valvontaan liittyy, niin termi olisi ruotsiksi lähinnä -övervakning tms.. Pitääköhän tutkia tarkemmin, kun suomeksi on nyt useita ohjaustermejä jotka viittaavat muihin konteksteihin.

**Comment by mirmaid** [comment]
Etäseuranta tms. ei ole mun mielestäni tosiaan ongelma, vaan nuo epämääräisen vakoilu ym. tarkkailu -aineistot.

**Comment by mirmaid** [comment]
Salakuuntelu: https://fi.wikipedia.org/wiki/Salakuuntelu

Eli, rajataanko salakuuntelu rikoksiin vai jätetäänkö mahdollisuus käyttää vakoilun ja vastaavan puolihämäräbisneksen yhteydessäkin?

**Comment by mariaforsen** [comment]
Jättäisin mahdollisuus käyttää myös vakoilun yms. yhteydessä.

**Comment by YSO-kokous** [comment]
### Päätös
Jätetään salakuuntelu ilman tarkennetta. 
Hierarkiassa ei rajata pelkästään rikoksiin, sillä erottelu vaikeaa ja eri maissa erilaiset lainsäädännöt toiminnan rikollisuudesta.
