### ISSUE TITLE
lestadiolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8059]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lestadiolaiset 

#### Ehdotettu termi ruotsiksi   

læstadianer 

#### Ehdotettu termi englanniksi   

Laestadians 

#### Vaihtoehtoiset termit ja ilmaisut   

[tarpeen tullen lestadiolaisuuden eri suuntausten edustajia kuvaavia termejä, esim. rauhansanalaiset ja vanhoillislestadiolaiset] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luterilaiset](http://www.yso.fi/onto/yso/p28213) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

Lestadiolaisen herätysliikkeen minkä tahansa suuntauksen jäsen 

#### Perustelut ehdotukselle   

Sanastossa ei ole ennestään riittävän tarkkaa määritelmää 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/003162197 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [lestadiolaiset](http://finto.fi/yse/fi/page/Y508059)

**Comment by mirmaid** [comment]
Viime syksynä jätettiin termiehdotukseksi _rukoilevaiset_, https://github.com/Finto-ehdotus/YSE/issues/7149. Termiä on käytetty n. 50 kertaa Melindassa, 11 kertaa merkitty Kaunokki-termiksi.

**Comment by YSO-kokous** [comment]
Sanastoon ottamisesta äänestettiin. Äänet menivät tasan 6-6. Jätetään toistaiseksi termiehdotukseksi. Vrt. rukoilevaiset-päätös. Jos tämä otettaisiin, pitäisi ottaa myös monia muita vastaavia.

**Comment by mariaforsen** [comment]
Lestadiolaiset käytetty jo 66 kertaa Melindassa, ja millä voidaan perustella että sanastossa on muita vastaavia kristillisten suuntien jäseniä? Viimeksi tuli vastaan "Lestadiolainen ja katolinen: näkökulmia Pohjolan kristillisyyteen". Katoliset on jo sanastossa, mutta lestadiolaiset ei, kuvailu jää puuttelliseksi. Kannatan että ainakin kaikki nämä jo paljon käytetyt asiasanat auktorisoidaan, auktorisoimalla saadaan auktorisoidun ja linkitetyn datan hyödyt talteen.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _lestadiolaiset_.

**Comment by mariaforsen** [comment]
Sv. læstadianer HT laestadianer,, lestadianer
https://id.kb.se/term/sao/Laestadianer
https://svenska.se/tre/?sok=laestadian&pz=1
sök/?t=uppslagsverk&q=laestadian
https://evl.fi/ordlista/-/glossary/word/Laestadianism
https://sv.wikipedia.org/wiki/L%C3%A6stadianer
