### ISSUE TITLE
katedraler

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8060]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

katedraalit 

#### Ehdotettu termi ruotsiksi   

katedraler 

#### Ehdotettu termi englanniksi   

cathedrals 

#### Perustelut ehdotukselle   

Domkyrka/Tuomiokirkko on lähinnä pohjoismainen luterilainen termi, muissa maissa ja kristillisissä uskonnoissa käytetään sanaa katedral/katedraali kun puhutaan hiippakunnan pääkirkosta. Esimerkiksi Uspenskin katedraali Helsingissä ei ole tuomiokirkko, eikä Pariisin Notre Dame. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://museot.finna.fi/Record/musketti_lahti.M44:LHMVHMLV15284:60, https://museot.finna.fi/Search/Results?lookfor=notre+dame&type=AllFields 

**Ehdottajan organisaatio:** Åbo Akademis bibliotek **Termiehdotus Fintossa:** [katedraler](http://finto.fi/yse/fi/page/Y508060)

**Comment by jtuohini** [comment]
Olisiko paras vaihtoehto luoda yhteiskäsite **_katedraalit ja tuomiokirkot_** samaan tapaan kuin on **pyhimykset ja pyhät**, joka kattaa sekä itäisten että läntisten kirkkojen keskenään vastaavat ilmiöt (ynnä muut/muita uskontoja samoin tein). Kyseessähän on joka tapauksessa yksi ja sama asia, jolla sattuu olemaan kaksi eri nimeä, ei kaksi selvästi toisistaan erotettavaa asiaa.

Lisäesimerkkejä koskien jakoa katedraalien ja tuomiokirkkojen välillä, joka siis ei mene edes kirkkokunnittain. Esim. roomalaiskatoliset Kölnin tuomiokirkko, Milanon katedraali = Milanon tuomiokirkko, Reimsin katedraali = Reimsin tuomiokirkko, Pyhän Tapanin tuomiokirkko (ennemmin kuin katedraali), Pyhän Vituksen (metropolinen) katedraali (ennemmin kuin tuomiokirkko), Méxicon katedraali = Méxicon tuomiokirkko, koptilainen Kairon katedraali (ennemmin kuin tuomiokirkko), anglikaaniset St Paulin katedraali (ennemmin kuin tuomiokirkko) ja Southwarkin katedraali = Southwarkin tuomiokirkko, jne. jne. jne.

Ks. myös https://fi.wikipedia.org/wiki/Luettelo_katedraaleista_ja_tuomiokirkoista

**Comment by YSO-kokous** [comment]
Hyväksytään jtuohinin ehdotus eli käytettäväksi termiksi _katedraalit ja tuomiokirkot_ ja ohjaustermeiksi _katedraalit_ ja _tuomiokirkot._

**Comment by mariaforsen** [comment]
Sv. katedraler och domkyrkor, domkyrkor och katedraler
