### ISSUE TITLE
valtion tulo- ja menoarviot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8062]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valtion tulo- ja menoarviot](http://www.yso.fi/onto/ysa/Y100016) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko poistettavissa? Ja KÄYTÄ valtion talousarviot 

#### Perustelut ehdotukselle   

Nykyään käytetään termiä valtion talousarviot ja huomautuskin on: Valtion talousarvioista vuoteen 1992 käytetty nimitys. {@fi} Ruotsiksi vanha on ollut "statsbudgeten" ja uusikin on "statsbudgeter" (sama asia). Vakava ongelma siis, ontologiassa ei saa olla samaa tarkoittavia termejä erillisinä, ja ainakin ruotsin osalta ainoa mahdollinen ratkaisu olisi poistaa vanhempi. 
Kielitoimiston sanakirja: talousarvio= tulo- ja menoarvio, budjetti.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
