### ISSUE TITLE
puhaltimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8063]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puhaltimet](http://www.yso.fi/onto/ysa/Y98275) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään käytettävään termiin sulkutarkenne erotukseksi puhallinsoittimista, esim. "puhaltimet (laitteet)". 

#### Perustelut ehdotukselle   

Puhallin on yleisesti käytetty synonyymi puhallinsoittimelle. Puhaltimet-käsitettä on käytetty Melindassa myös puhallinsoittimista. Esim.
Musiikin aakkoset / Carla Magnan ja Gabriella Solari
Ist die sogenannte Mozartsche Bläserkonzertante KV 297b/Anh. I,9 echt? / Martin Staehelin.
Lampun henki = Genie in the lamp : vaskiseitsikolle = for brass septet / Antti Kleemola. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Melindan virheet lienee hyvä myös tältä osin korjata?

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus. Lisätään tarkenne.
