### ISSUE TITLE
sammalpunkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8064]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sammalpunkit 

#### Perustelut ehdotukselle   

Pahamaineisten puutiaisten vuoksi punkkeja pidetään usein haittaeläiminä, mutta valtaosa Suomen 1500 punkkilajista on kuitenkin hyödyllisiä. Tällaisia ovat maaperässä elävät ja hajottajina toimivat mikroskooppisen pienet sammalpunkit. Niiden toiminta takaa maaperän ravinteiden biokemiallisen kierron ja siten kasvien ravinteiden saannin. Etenkin pohjoisen havumetsävyöhykkeen metsissä sammalpunkit ovat erityisen tärkeitä, sillä ne ovat Kaikkiaan Suomesta tunnetaan 350 sammalpunkkilajia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hidden diversity of moss mites (Acari: Oribatida) unveiled with ecological and genetic approach / Riikka A. Elo. 

**Ehdottajan organisaatio:** KB **Termiehdotus Fintossa:** [sammalpunkit](http://finto.fi/yse/fi/page/Y508064)

**Comment by mariaforsen** [comment]
Eli lat. Oribatida? Se on ruotsiksi hornkvalster, joka jo on YSOssa = kuoripunkit =eng. Oribatida
http://luomus.fi/fi/maaperaelaimet -onko kuoripunkit ja sammalpunkit sama asia?

**Comment by ilona-x** [comment]
Laji.fi sammalpunkit https://laji.fi/taxon/MX.202834 Tieteellinen nimi Oribatida

"sammalpunkit eli kuoripunkit (Oribatida)" https://www.syke.fi/download/noname/%7B69C95D6C-53E6-4581-9BE9-B2F4A2E51269%7D/37679

**Comment by YSO-kokous** [comment]
Muutetaan kuoripunkit-käsitteen käytettäväksi termiksi sammalpunkit, ohjaustermiksi kuoripunkit.
