### ISSUE TITLE
yövirtsaaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8065]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yövirtsaaminen 

#### Vaihtoehtoiset termit ja ilmaisut   

nokturia 
yövirtsaisuus 

#### Vastaava käsite muussa sanastossa   

<http://www.yso.fi/onto/mesh/D053158> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Course and Consequences of Nocturia 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [yövirtsaaminen](http://finto.fi/yse/fi/page/Y508065)

**Comment by mirmaid** [comment]
Sanastossa olikin jo _nykturia_, http://www.yso.fi/onto/yso/p23541, eli lisätään ohjaustermejä. Tosin voisi olla myös perusteltua vaihtaa päätermiä, kaikki kolme muuta muotoa ovat enemmän käytettyjä Googlella. Nykturia on _Lääketieteen termien_ muoto.

**Comment by LeKorsu** [comment]
Kannatan  päätemin vaihtamista helpommin ymmärrettävään muotoon. Yövirtsaamisella tulee vähän enemmän googleosumia kuin finmesh-muodolla yövirtsaus

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi yövirtsaaminen.
Ohjaustermiksi nokturia, yövirtsaisuus ja nykturia.
