### ISSUE TITLE
vankilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8066]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vankilat](http://www.yso.fi/onto/ysa/Y100072) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kuritushuoneet" (ei yksikössä) 

#### Perustelut ehdotukselle   

Vankilan vanha nimitys, josta olisi hyvä viitata aiheen kattamaan nykykäsitteeseen (kuritushuone yksikössä viittaisi kuritushuonerangaistukseen, eikä siitä ole tässä kysymys) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Ehdotus hyväksytään.
