### ISSUE TITLE
maaefektialukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8067]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maaefektialukset 

#### Ehdotettu termi englanniksi   

ground-effect vehicles 

#### Ehdotettu termi ruotsiksi   

markeffektfarkoster 

#### Vaihtoehtoiset termit ja ilmaisut   

ekranoplanit 
patosiipialukset 
patosiipikoneet 
pintaliitäjät 
WIG:t 
WIG-alukset 
ekranoplaner [swe] 
GEVs [eng] 
wing-in-ground-effect machines [eng] 
ekranoplans [eng] 
ground-effect crafts [eng] 
wingships [eng] 
pintaliitäjät [fin] 
sea skimmers [eng] 
flarecrafts [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ilmakulkuneuvot](http://www.yso.fi/onto/yso/p1054) 
[vesikulkuneuvot](http://www.yso.fi/onto/yso/p7082) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh97007627> 
Wikidata : https://www.wikidata.org/wiki/Q309398 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

Käytetty Melindassa 4 kertaa (lisäksi aineistoa, jota ei ole osattu kuvailla tällä) 

#### Tarkoitusta täsmentävä selite   

Lentokonetta muistuttava vesikulkuneuvo, joka lentää joitakin metrejä vedenpinnan (tai harvemmin maanpinnan) yläpuolella käyttäen hyväkseen aerodynaamisen maavaikutuksen antamaa nostetta. [https://fi.wikipedia.org/wiki/Maaefektialus] 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [maaefektialukset](http://finto.fi/yse/fi/page/Y508067)

**Comment by jtuohini** [comment]
Lisäksi englanninkieliset KT-muodot "ekranoplanes", "wing-in-ground effect crafts" ja "wingships" (kaikki löytyvät Melinda-aineiston nimekkeistä ja huomautuskentistä)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon, käytettäväksi termiksi maaefektialukset.
