### ISSUE TITLE
Williamsin oireyhtymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8068]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Williamsin oireyhtymä 

#### Vastaava käsite muussa sanastossa   

<http://www.yso.fi/onto/mesh/D018980> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ikääntyminen ja kehitysvammaisuus - kognitiiviset muutokset Williamsin, fragile X- ja Downin oireyhtymissä 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Williamsin oireyhtymä](http://finto.fi/yse/fi/page/Y508068)

**Comment by mariaforsen** [comment]
Sv. Williams syndrom
https://finto.fi/mesh/sv/page/D018980
