### ISSUE TITLE
jättiläiskalmari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8069]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jättiläiskalmari 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The Giant Squid: Imagining and Encountering the Unknown from the 1760s to the 1890s 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [jättiläiskalmari](http://finto.fi/yse/fi/page/Y508069)

**Comment by mariaforsen** [comment]
Taitaa oikeastaan olla heimo: Architeuthidae =jättiläiskalmarit
https://fi.wikipedia.org/wiki/J%C3%A4ttil%C3%A4iskalmarit
Sv. jättebläckfisk

**Comment by PaiviLipsanen** [comment]
Jättiläiskalmarit (Architeuthidae) ovat kalmarien lahkoon kuuluvia mustekaloja, jotka ovat kolossikalmarin jälkeen maailman toiseksi suurikokoisimpia selkärangattomia eläimiä. Jättiläiskalmarien heimossa on vain yksi suku, Architeuthis, mutta lajien lukumäärä on epäselvä. Suvun tunnetuin ja mahdollisesti ainoa laji on jättiläiskalmari (Architeuthis dux).
Lähde: Yllä mainittu wikisivu.

**Comment by mirmaid** [comment]
^ Juuri tästä syystä ajattelin, että lajin nimi riittäisi. Teos jossa sitä tarvittiin käsitteli jättiläiskalmariin liittyvää mytologiaa.

**Comment by YSO-kokous** [comment]
Otetaan jättiläiskalmari yksikössä, viitaten lajiin. Vrt, "Suvun tunnetuin ja mahdollisesti ainoa laji on jättiläiskalmari (Architeuthis dux)."
