### ISSUE TITLE
perhe- ja yhteisölääketiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8070]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[perhe- ja yhteisölääketiede](http://www.yso.fi/onto/ysa/Y111226) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ohjaustermeiksi:
KT perhelääketiede
KT yhteisölääketiede 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

FinMeShissä erilliset termit, jotka olisi hyvä lisätä ohjaustermeiksi YSOn yhdistelmätermille
http://www.yso.fi/onto/mesh/D005194
http://www.yso.fi/onto/mesh/D003154

**Comment by YSO-kokous** [comment]
Ehdotus hyväksytään.
