### ISSUE TITLE
pianopartituurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8072]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pianopartituurit](http://www.yso.fi/onto/ysa/Y214610) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan huomautus? 

#### Perustelut ehdotukselle   

Huomautuksessa kehoitetaan käyttämään termiä kuoropartituuri, mutta sitä ei ole sanastossa.

**Comment by MUUSA-kokous** [comment]
Laaditaan uusi ehdotus käsitteelle _kuoropartituurit._

**Comment by MUUSA-kokous** [comment]
Perutaan ehdotuksen laatiminen käsitteelle _kuoropartituurit_.

Sen sijaan Muusa kannattaa kuoropartituuriin viittaavan huomautuksen poistamista.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotetusti.
