### ISSUE TITLE
välirahoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8074]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

välirahoitus 

#### Vaihtoehtoiset termit ja ilmaisut   

mezzanine-rahoitus 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Mezzanine Financing: A Comparison between the Finnish and International Financial Market Regulation 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [välirahoitus](http://finto.fi/yse/fi/page/Y508074)

**Comment by mirmaid** [comment]
Välirahoitus eli mezzanine tarkoittaa yritysrahoituksessa vieraan pääoman muotoista rahoitusta, jossa on kuitenkin oman pääoman piirteitä. https://pankkiasiat.fi/mezzanine

https://www.investopedia.com/terms/m/mezzaninefinancing.asp
https://en.wikipedia.org/wiki/Mezzanine_capital
https://sv.wikipedia.org/wiki/Mezzaninkapital

Ei Melindassa.

**Comment by LeKorsu** [comment]
Sanoman arkistosta tulee 56 osumaa välirahoituksella, google 5630.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa välirahoitus, ohjaustermiksi mezzanine-rahoitus.

**Comment by mariaforsen** [comment]
Sv. mezzaninfinansiering ET mezzaninefinansiering, mellanfinansiering
