### ISSUE TITLE
piraijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8075]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

piraijat 

#### Ehdotettu termi ruotsiksi   

pirayor 

#### Perustelut ehdotukselle   

Tarvittaisiin piraijoista kertovan kirjan kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fatta grejen med pirayor 9789178817542 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [piraijat](http://finto.fi/yse/fi/page/Y508075)

**Comment by jtuohini** [comment]
"Nimellä piraijat on suomalaisessa kalanimistössä viitattu yhtäältä koko Serrasalmidae-heimoon (alaheimoon), toisaalta nimellä on yleisemmin ja etenkin muissa kielissä viitattu ahtaammassa mielessä vain viiteen lihanahneeseen sukuun Catoprion, Pristobrycon, Pygocentrus, Pygopristis ja Serrasalmus (tribus Piranha) [- -]" (https://fi.wikipedia.org/wiki/Piraijat)
 
Kumpaa tarkoitettaisiin ja kumpaan asiasanaan siis tulisi LCSH-siltaus: **[Characidae](http://id.loc.gov/authorities/subjects/sh85022613)** vai **[Piranhas](http://id.loc.gov/authorities/subjects/sh85102427)**?

**Comment by tpalonen** [comment]
Harmi, että piraija-tyyppisten lajien vanhempi suomenkielinen nimitys _sahalohi_ ei enää ole käytössä. Ehkä YSO voisi elvyttää tämän komean termin? Ks. http://runeberg.org/tieto/8/0274.html

**Comment by mirmaid** [comment]
Epäselvyyttä käsitteen kattavuudesta näyttäisi olevan myös laajemmin kuin suomenkielessä, vrt. esim. englanninkielinen wikipedia https://en.wikipedia.org/wiki/Piranha#Taxonomy_and_evolution. 

Mahdollista varmaan esim. tehdä linkitys suppeampaan merkitykseen, joka lienee yleisessä käytössä tavallisempi tulkinta - laajempikin on toki perusteltavissa.

https://www.adlibris.com/fi/kirja/fatta-grejen-med-pirayor-9789178817542

2 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Piraija-tyyppinen lajisto taksonomialtaan ja termistöltään epäselvä. Hyväksytään sanastoon, otetaan yleistajuisemmassa eli suppeammassa merkityksessä. YSO-ylläpito miettii LCSH-linkityksen ja englannin vastineen.
