### ISSUE TITLE
magnesiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8076]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

magnesiitti 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Diversity of soapstones: Classification and thermal behavior 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [magnesiitti](http://finto.fi/yse/fi/page/Y508076)

**Comment by jtuohini** [comment]
LCSH-siltaus: **[Magnesite](http://id.loc.gov/authorities/subjects/sh85079650)**?

**Comment by mariaforsen** [comment]
Sv. magnesit
