### ISSUE TITLE
galaksijoukot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8077]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

galaksijoukot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Evolution of dwarf galaxies in the Fornax cluster 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [galaksijoukot](http://finto.fi/yse/fi/page/Y508077)

**Comment by mirmaid** [comment]
LCSH: Galaxies - Clusters, http://id.loc.gov/authorities/subjects/sh85052764

https://fi.wikipedia.org/wiki/Galaksijoukko

_Kymmeniä tai satoja galakseja sisältävä järjestelmä, jonka läpimitta on useita kymmeniä miljoonia valovuosia._ http://tieteentermipankki.fi/wiki/T%C3%A4htitiede:galaksijoukko

4 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. galaxhopar

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
