### ISSUE TITLE
kääpiögalaksit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8078]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kääpiögalaksit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Evolution of dwarf galaxies in the Fornax cluster 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kääpiögalaksit](http://finto.fi/yse/fi/page/Y508078)

**Comment by mirmaid** [comment]
LCSH: Dwarf galaxies, http://id.loc.gov/authorities/subjects/sh85040180

_Pienikokoinen galaksi, joita on hyvin runsaasti, mutta joita on vaikea havaita kaukaisista galaksijoukoista._ http://tieteentermipankki.fi/wiki/T%C3%A4htitiede:k%C3%A4%C3%A4pi%C3%B6galaksi

https://fi.wikipedia.org/wiki/K%C3%A4%C3%A4pi%C3%B6galaksi

Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. dvärggalaxer

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
