### ISSUE TITLE
serenatat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8080]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[serenatat](http://www.yso.fi/onto/ysa/Y504573) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan termi myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Tarvitaan serenatoja sisältävien nuottijulkaisujen ja äänitteiden kuvailuun 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja LCGFT-siltaus tälle ehdotetulle SLM-termille: **[Serenatas](http://id.loc.gov/authorities/genreForms/gf2014027084)**.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
