### ISSUE TITLE
disputation (händelse)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8082]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

väitöstilaisuus 

#### Ehdotettu termi ruotsiksi   

disputation (händelse) 

#### Ehdotettu termi englanniksi   

thesis defence 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Perustelut ehdotukselle   

Ordet saknas i ALLFO/YSO. 
På svenska finns begreppet disputation (fi väittely), men i betydelsen dispyt/debatt. De är inte samma sak som ett officiellt disputationstillfälle vid ett universitet med alla därtillhörande byråkratiska krumelurer och opponentens och respondentens och kustosens närvaro etc. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fotografier från ett disputationstillfälle 

**Ehdottajan organisaatio:** Åbo Akademis bibliotek **Termiehdotus Fintossa:** [disputation (händelse)](http://finto.fi/yse/fi/page/Y508082)

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa väitöstilaisuudet. ALLFO-ylläpito miettii ruotsinkielisen muodon sulkutarkenteineen.

**Comment by mariaforsen** [comment]
Sv. disputationer (tillställningar) ET disputationstillfällen
