### ISSUE TITLE
lintuhaukat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8083]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lintuhaukat 

#### Ehdotettu termi ruotsiksi   

(egentliga) hökar 

#### Vaihtoehtoiset termit ja ilmaisut   

Accipiter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[petolinnut](http://www.yso.fi/onto/yso/p8680) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Lintuhaukat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

YSO-kokouksessa todettu
https://laji.fi/sv/taxon/MX.26603 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lintuhaukoista 

**Termiehdotus Fintossa:** [lintuhaukat](http://finto.fi/yse/fi/page/Y508083)

**Comment by PaiviLipsanen** [comment]
Yläkäsite:
haukat (heimo - Accipitridae)

Alakäsitteet:
kanahaukka
varpushaukka

**Comment by mariaforsen** [comment]
Sv. egentliga hökar? 
hökar=accipitrinae https://sv.wikipedia.org/wiki/H%C3%B6kar
