### ISSUE TITLE
mielenterveyshäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8084]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mielenterveyshäiriöt](http://www.yso.fi/onto/ysa/Y106581) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ohjaustermiksi mielisairaudet. 

#### Perustelut ehdotukselle   

Mielisairaudet on nyt ohjaustermi ainoastaan psykoosit-käsitteelle. Sen lisäksi mielisairaudet sopisi ohjaustermiksi mielenterveyshäiriöille. 

Mielisairaus ja mielenterveyshäiriö ovat lähisynonyymeja (ks. esim. IATE). Mielisairaus-termin käyttö lienee vähenemään päin (vrt. mielisairaala) ja tilalla/rinnalla käytetään termejä psyykkinen sairaus tai psykiatrinen sairaus (ks. esim. https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00148). Psyykkiset sairaudet ja psykiatriset sairaudet ovat molemmat ohjaustermejä mielenterveyshäiriöt-käsitteelle. Tuntuukin hieman puolittaiselta, että mielisairaudet ohjaa tällä hetkellä ainoastaan psykoosit-käsitteeseen. Mielisairaus ja psykoosi eivät tarkoita täsmälleen samaa asiaa. Psykoosin määritelmiä: "psykoosilla tarkoitetaan tajunnan ja kokemuksen tilaa, joissa ihminen ei erota oman mielensä tuottamia aistimuksia ulkoisesta todellisuudesta" (Suomen mielenterveys ry), "psykoosilla tarkoitetaan todellisuudentajun vakavaa häiriintymistä" (THL), "The word psychosis is used to describe conditions that affect the mind, where there has been some loss of contact with reality" (NIMH). Vrt. myös THL: "Psykoosioireet voivat johtua myös päihteiden käytöstä tai ruumiillisesta sairaudesta, kuten dementiasta." Skitsofrenia, joka on psykoottisia oireita sisältävistä sairauksista (so. mielisairauksista) yleisin, on esim. MeSHin ja ja Suomen mielenterveys ry:n mukaan mielenterveyshäiriö (ks. https://mieli.fi/fi/mielenterveys/mielenterveyden-h%C3%A4iri%C3%B6t/skitsofrenia). 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Ehdotus hyväksytään. Säilytetään myös mielisairaudet KÄYTÄ psykoosit.
