### ISSUE TITLE
Kulttuurihyvinvointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8085]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kulttuurihyvinvointi 

#### Ehdotettu termi ruotsiksi   

Kultur och hälsa 

#### Ehdotettu termi englanniksi   

Arts and Health; Creative Wellbeing 

#### Vaihtoehtoiset termit ja ilmaisut   

Taiteen ja kulttuurin yhteys terveyteen ja hyvinvointiin; taiteesta ja kulttuurista hyvinvointia; arts, health and wellbeing 

#### Tarkoitusta täsmentävä selite   

Kulttuurihyvinvointi tarkoittaa 1. yksilön tai yhteisön kokemuksia taiteen ja kulttuurin yhteyksistä omaan tai toisten terveyteen ja hyvinvointiin, 2. ilmiötä, että taiteella ja kulttuurilla on yhteyksiä terveyteen ja hyvinvointiin, 3. alaa, joka tutkii, kehittää ja kouluttaa tähän liittyvää osaamista ja toimintatapoja. 

#### Perustelut ehdotukselle   

Kulttuurihyvinvointi on hyvänä yhdyssanana jo vakiintunut alan tutkimus- koulutus- ja kehittämistyöhön sekä alaan liittyvään päätöksentekoon. 
Ks. esim. OKM 2020: https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/162052/OKM_2020_13.pdf?sequence=1&isAllowed=y ; 
Taiteen edistämiskeskus 2020: https://www.taike.fi/fi/taidetoimii 
STM 2019: http://julkaisut.valtioneuvosto.fi/handle/10024/161547 
Kuntaliitto 2019: https://www.kuntaliitto.fi/opetus-ja-kulttuuri/kunnan-kulttuuritoiminta/kulttuuri-hyvinvointipalveluna-kulttuurihyvinvointi
Esim. Pirkanmaan sairaanhoitopiiri 2017: https://www.tampere.fi/tiedostot/p/gS5Dfh9gp/pirkanmaan_kulttuurihyvinvointisuunnitelma.pdf 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Alan opinnäytetöissä, alan tutkimustyössä, alan ammattijulkaisuissa, kulttuurihyvinvointialan alueellisessa ja valtakunnallisessa kehittämistyössä, kulttuurihyvinvointisuunnitelmatyöhön, sairaahoitopiirien toimenpidesuosituksiin 

**Ehdottajan organisaatio:** Turun ammattikorkeakoulu **Termiehdotus Fintossa:** [Kulttuurihyvinvointi](http://finto.fi/yse/fi/page/Y508085)

**Comment by mirmaid** [comment]
Kerran Melindassa, 74 viitettä Googlella (kun samankaltaiset tulokset on poistettu). 

Hyvinvoinnin edistäminen kulttuurin avulla on kulttuuripolitiikan yksi tavoite, jota varten on kehittynyt erityisesti viime vuosina erilaisia toimintamuotoja. Tässä käytetään siitä vakiin-tumassa olevaa käsitettä kulttuurihyvinvointi. Kulttuurihyvinvointi on kulttuuripoliittisena tavoitteena poikkileikkaava. Sillä tarkoitetaan yleisesti "yksilöllisesti tai yhteisöllisesti jaettua kokemusta siitä, että kulttuuri ja taide lisäävät hyvinvointia tai ovat yhteydessä siihen". https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/162052/OKM_2020_13.pdf?sequence=1&isAllowed=y

Kulttuurihyvinvoinnilla tarkoitetaan kulttuurin ja taiteen mahdollisuuksia edistää terveyttä ja hyvinvointia. Taide ja kulttuuri luovat jo itsessään hyvinvointia ja mielekästä elämää. Toisaalta niitä voidaan käyttää myös tavoitteellisesti edistämään hyvinvointia. Kulttuurihyvinvoinnin toteuttamisessa korostuu taide- ja kulttuuritoimijoiden ammattimainen ja pitkäjänteinen yh-teistyö muiden toimialojen kanssa. https://www.tampere.fi/tiedostot/p/gS5Dfh9gp/pirkanmaan_kulttuurihyvinvointisuunnitelma.pdf

YSOssa on _fyysinen hyvinvointi, henkinen hyvinvointi, koettu hyvinvointi_ ja _työhyvinvointi_.

**Comment by mariaforsen** [comment]
Ruotsinkielinen termi ei voi olla "kultur och hälsa". Kulturhälsa, kulturvälmående..? (ei vakiintuneita)

**Comment by LeKorsu** [comment]
Voisin lyödä vetoa jostakin, että nyt Melindassa oleva gradu ei tule jäämään ainoaksi opinnäytteeksi aiheesta, joten kannatan mukaanottamista jo nyt.

**Comment by YSO-kokous** [comment]
Käsitteen ottaminen sanastoon ei saanut kokouksessa riittävää kannatusta. Termi ei näytä (vielä) olevan yleisesti käytössä. Seurataan kuitenkin tilannetta ja palataan asiaan, mikäli termi näyttää hieman yleistyvän.

ps. Hyvin laadittu ehdotus keräsi kylläkin kokouksessa kiitosta.

**Comment by arosenlo** [comment]
Finna tuotti useampia hakutuloksia. 11 eritasoista opinnäytetyötä, joissa aihepiirinä kulttuurihyvinvointi. Ruotsinkielinen vastine voisi olla kulturvälbefinnande tai kulturvälmående, joskin Ruotsissa tyypillisesti käytössä kultur och hälsa.

Kulttuurihyvinvointi on terminä Suomeesa suhteellisen uusi, sen juuret ulottuvat vuosiin 2012-2013, jolloin termi kehitettiin Turun seudulla Turun kulttuuripääkaupunkivuoden 2011 jälkimainingeissa. Vuoden yksi slogan oli "Kulttuuri tekee hyvää". Viime vuosien eli ehkä vuosien 2017-2020 aikana se on alkanut vakiintua käyttöön laajemmin eri puolilla Suomea. 

Ruotsissa kulttuurihyvinvoinnin ilmiö on vanhempi ja vakiintuneempi. Mutta vastaavaa termiä ei tosiaan ruotsin kielessä ole. Ruotsiksi puhutaan kultur och hälsa ja se on vakiintunut termi pohjoismaisesti. Maailmalla englanninkielisissä maissa vakiintunut termi on arts and health tai culture, health and wellbeing. Jonkun verran näkee myös creative wellbeing -termiä. Suomessa käytetty pitkää ilmaisua taiteesta ja kulttuurista hyvinvointia, joka on melko kömpelö kulttuurihyvinvointiin verrattuna.

**Comment by ElinaMirvaKaarina** [comment]
Kulttuurihyvinvointi -termin vakiinnuttaminen asiasanastoon on erittäin ajankohtaista ja tärkeää. Termi on jo suhteellisen vakiintunut ja se on käytössä alan tutkimus-, koulutus- ja kehittämistyössä sekä päätöksenteossa. Kehittyvä ja kasvava kulttuurihyvinvoinnin toimiala ja kulttuurihyvinvointi osana ihmisen kokonaisvaltaista hyvinvointia tulee tunnistaa myös kielen tasolla.

**Comment by mirmaid** [comment]
Tuli vastaan teoksessa _Tietoa, taitoa ja teknologiaa - kehittämispolkuja sosiaali- ja terveysalalla_.

**Comment by mariaforsen** [comment]
Sv. kulturell välfärd 
https://stm.fi/sv/-/kulttuurihyvinvoinnilla-vahva-jalansija-suomessa

**Comment by jarmosaarikko** [comment]
**Kulttuurihyvinvointi** (cultural well-being) on YAMK tutkinnon alana sekä [Turun  ammattikorkeakoulussa](https://www.turkuamk.fi/fi/tutkinnot-ja-opiskelu/tutkinnot/kulttuurialan-ylempi-amk-tutkinto-kulttuurihyvinvo/) että [XAMK](https://opinto-opas.xamk.fi/index.php/fi/2676/fi/285553/KUKV21KY_90/year/2020)issa eli oli varsin perusteltua ottaa sanastoon, sillä eiköhän näistä tulle opinnäytteitäkin.
