### ISSUE TITLE
Pinterest

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8086]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pinterest 

#### Perustelut ehdotukselle   

Tarvittu myös Snapchat, TikTok. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Somemarkkinoinnin työkirja 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Pinterest](http://finto.fi/yse/fi/page/Y508086)

**Comment by mirmaid** [comment]
LCSH:ssa vastaavat ovat nyt kaikki teosauktoriteetteja 130-kentässä.

**Comment by YSO-kokous** [comment]
Hyväksytään Pinterest, Snapchat ja TikTok sanastoon riippumatta LCSH:n ratkaisusta, koska vastaavia on jo sanastossa.
