### ISSUE TITLE
fotosfääri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8087]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fotosfääri 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Spatial-temporal structure and distribution of the solar photospheric magnetic field 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [fotosfääri](http://finto.fi/yse/fi/page/Y508087)

**Comment by mirmaid** [comment]
Fotosfääri on tähden (tai auringon) pintakerros. https://fi.wikipedia.org/wiki/Fotosf%C3%A4%C3%A4ri, https://en.wikipedia.org/wiki/Photosphere

LCSH: Solar photosphere, http://id.loc.gov/authorities/subjects/sh85124530

Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. fotosfär
SAO: fotosfären

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
