### ISSUE TITLE
osteoklastit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8088]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

osteoklastit 

#### Vastaava käsite muussa sanastossa   

<http://www.yso.fi/onto/mesh/D010010> 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Osteopontin and osteoclasts in rheumatoid arthritis and osteoarthritis 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [osteoklastit](http://finto.fi/yse/fi/page/Y508088)

**Comment by mariaforsen** [comment]
Sv. osteoklaster
