### ISSUE TITLE
osteopontiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8089]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

osteopontiini 

#### Vastaava käsite muussa sanastossa   

<http://www.yso.fi/onto/mesh/D053495> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Osteopontin and osteoclasts in rheumatoid arthritis and osteoarthritis 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [osteopontiini](http://finto.fi/yse/fi/page/Y508089)

**Comment by mariaforsen** [comment]
Sv. osteopontin
