### ISSUE TITLE
alttoviulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8090]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[alttoviulu](http://www.yso.fi/onto/ysa/Y100703) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT viola 

#### Perustelut ehdotukselle   

Ovat synonymejä, ks. Kielitoimiston sanakirja.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
