### ISSUE TITLE
trubaduurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8091]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[trubaduurit](http://www.yso.fi/onto/ysa/Y111641) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan? 

#### Perustelut ehdotukselle   

Käytetty paljon myös toisessa merkityksessä, ks. Melinda.

**Comment by mirmaid** [comment]
1. hist. varhaiskeskiajan eteläranskalaisia laulurunoilijoita.
2. laulelmien esittäjä.

**Comment by mariaforsen** [comment]
https://fi.wiktionary.org/wiki/trubaduuri
NE: vissångare som ackompanjerar sig själv på stränginstrument och vanl. själv skriver visor
SAOssa: trubadurer LCSH-linkitys: Troubadours

**Comment by LeKorsu** [comment]
Trubadurix oli kyllä Pohjois-Galliasta, joten onko määritelmä virheellinen? (heko heko, vitsi)

**Comment by tpalonen** [comment]
RT laulaja-lauluntekijät kieltämättä assosioituu enemmän Kielitoimiston sanakirjan kakkosmerkitykseen. Sen voisi ainakin poistaa?

Ehdottaisin tätä Muusan pohdittavaksi. Onko toiselle merkitykselle aidosti tarvetta? Sanastossa on mm. katumuusikot ja laulaja-lauluntekijät. Populaarimusiikista puhuttaessa termillä halutaan ehkä herättää tiettyjä mielikuvia, mutta en tiedä onko käsite merkitykseltään kovin selvä.

**Comment by YSO-kokous** [comment]
Odotamme Muusan kantaa tähän.

**Comment by MUUSA-kokous** [comment]
Muusa ei kannata käsitteen jakamista. RT laulaja-lauluntekijät voidaan poistaa.

**Comment by YSO-kokous** [comment]
Käykö Muusalle, jos lisätään sulkutarkenne _trubaduurit (keskiaika)_? Vähentäisi käsitteen virheellistä käyttöä.

**Comment by MUUSA-kokous** [comment]
Muusa hyväksyy sulkutarkenteen.
