### ISSUE TITLE
sahanpuru

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8092]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sahanpuru 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Activated carbon from renewable resource 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sahanpuru](http://finto.fi/yse/fi/page/Y508092)

**Comment by mirmaid** [comment]
AFOssa: http://www.yso.fi/onto/afo/p3546

50 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. sågspån

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
