### ISSUE TITLE
Pariisin Notre-Damen katedraali

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8095]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pariisin Notre-Damen katedraali 

#### Ehdotettu termi ruotsiksi   

Notre-Dame de Paris 

#### Ehdotettu termi englanniksi   

Notre-Dame de Paris 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Tarvitaan katedraalin palon yhteydessä tehdyn Kansalliskirjaston verkkokeräyksen kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/016780832 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Pariisin Notre-Damen katedraali](http://finto.fi/yse/fi/page/Y508095)

**Comment by mirmaid** [comment]
LCSH: Notre-Dame de Paris (Cathedral) (yhteisönä, 110)
Wikipedia, wikidata: Notre-Damen katedraali. _Useat muutkin Ranskan katedraalit ja kirkot on nimetty samalla Notre-Dame-nimellä._ https://fi.wikipedia.org/wiki/Notre-%E2%80%8BDamen_katedraali

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon Notre-Damen katedraali (Pariisi). Ohjaustermeiksi Notre Damen katedraali (Pariisi) ja Pariisin Notre-Damen katedraali.

**Comment by mariaforsen** [comment]
Sv.  Notre Dame-katedralen (Paris) ET Notre-Dame de Paris, Notre-Dame (Paris)
