### ISSUE TITLE
radioresurssien hallinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8096]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

radioresurssien hallinta 

#### Vastaava käsite muussa sanastossa   

https://en.wikipedia.org/wiki/Radio_resource_management 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Radio resource management in device-to-device and vehicle-to-vehicle communication in 5G networks and beyond 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [radioresurssien hallinta](http://finto.fi/yse/fi/page/Y508096)

**Comment by mirmaid** [comment]
9 viitettä Melindassa.

Matkaviestinsanasto: _Matkaviestinjärjestelmän toimintokokonaisuus, jonka avulla hallitaan matkaviestinnän tarvitsemien radioyhteyksien muodostaminen, ylläpitäminen ja purkaminen._ 
https://termipankki.fi/tepa/fi/haku/radio%20resource%20management

LCSH: Radio resource management (Wireless communications), http://id.loc.gov/authorities/subjects/sh2008004985

**Comment by mariaforsen** [comment]
Sv.  radioresurshantering ET administration av radioresurser, hantering av radioresurser

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
