### ISSUE TITLE
materiaalijalanjälki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8097]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

materiaalijalanjälki 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The metabolism of socio-economic systems 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [materiaalijalanjälki](http://finto.fi/yse/fi/page/Y508097)

**Comment by mirmaid** [comment]
Materiaalijalanjälki on tapa mitata tai laskea kaikki ne luonnonvarat, joita kulutuksemme tarvitsee. https://www.sitra.fi/artikkelit/materiaalijalanjalki-kertoo-luonnonvarojen-kokonaiskayton/

Sanastossa on _ekologinen jalanjälki, hiilijalanjälki_ ja _vesijalanjälki_.

2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. materialavtryck ET materialfotspår

**Comment by YSO-kokous** [comment]
Mirja etsii englanninkielisen vastineen ja määritelmän käsitteelle ja kirjaa ne tähän issueen. Käsitellään vielä seuraavassa kokouksessa.

**Comment by AuHo22** [comment]
Materiaalijalanjälkien laskennassa käytettävää menetelmää kutsutaan MIPS-menetelmäksi. MIPS (Material Input per Service Unit) on ekotehokkuuden mittari, jonka avulla lasketaan, kuinka paljon luonnonvaroja on kulunut jonkin tuotteen tai palvelun koko elinkaaren aikana.
YSOssa jo MIPS

**Comment by mirmaid** [comment]
Eng. material footprint (esim. https://ec.europa.eu/eurostat/statistics-explained/index.php/Material_flow_accounts_statistics_-_material_footprints)

Materiaalijalanjälki on luonnonvarojen kokonaiskulutuksen mittari. MIPS on sille läheinen käsite, mutta kun MIPS mittaa tuotteen tai palvelun tuotannon vaikutusta, materiaalijalanjäljen lähtökohtana on kulutus: henkilön, kotitalouden tai valtion koko kulutuksen vaatimien luonnonvarojen kokonaismäärä. Valtion tai muun talousyksikön materiaalijalanjälkeen ei oikein voi viitata käsitteellä MIPS, koska valtio tms. ei ole "service".

**Comment by AuHo22** [comment]
Materiaalijalanjälki lienee tarvittava käsite, eli toin MIPS-käsitteen esille sen takia.

**Comment by YSO-kokous** [comment]
hyväksytään materaalijalanjälki ja sille lisätään määritelmä
