### ISSUE TITLE
rubidium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8098]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rubidium 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Interpretation and relativistic simulation of selected electronic transitions 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [rubidium](http://finto.fi/yse/fi/page/Y508098)

**Comment by mariaforsen** [comment]
Sv. rubidium
