### ISSUE TITLE
keinosiemennys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8099]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keinosiemennys](http://www.yso.fi/onto/ysa/Y96058) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan/selkeytetään ihmisen vs. eläinten 

#### Perustelut ehdotukselle   

Ovat eri asioita, eläinten kohdalla ei "hoitoa". Voisi olla keinosiemennys + tarkenne tai huomautus, joka viittaisi eläimiin ja inseminaatio(hoito) tms. + tarkenne ja huomautus, joka viittaisi ihmisiin. Ks. Kielitoimiston sanakirja, wikipedia jne.

**Comment by ilona-x** [comment]
https://www.terveyskyla.fi/naistalo/lis%C3%A4%C3%A4ntymisterveys/lapsettomuus/lapsettomuushoidot/inseminaatiohoito-(keinosiemennys)

http://tieteentermipankki.fi/wiki/El%C3%A4intiede:keinosiitos

**Comment by mariaforsen** [comment]
Sv. insemination (djur), inseminationsbehandling

**Comment by LeKorsu** [comment]
HS 21.12.19: 
"Joonas Laitinen HS Hedelmöityshoidot yleistyivät Suomessa vuosien 2017 ja 2018 välillä, kertoo Terveyden ja hyvinvoinnin laitos (THL). Vuonna 2017 aloitettiin noin 12700 hedelmöityshoitoa. Vuoden 2018 ennakkotietojen mukaan määrä kasvoi viime vuonna noin 9 prosenttia.
Hoidoista noin 73 prosenttia on koeputkihedelmöityshoitoja. Loput ovat niin sanottuja inseminaatiohoitoja, joilla tarkoitetaan siittiöiden ruiskuttamista kohtuonteloon.
Vuonna 2017 kaikista Suomessa syntyneistä vauvoista arviolta noin 4,8 prosenttia syntyi keinohedelmöityksen avulla. Kaikkiaan hedelmöityshoidon avulla syntyi 2336 vauvaa.
Vuonna 2017 kaikista hedelmöityshoidoista hieman yli 18 prosenttia eteni lapsen syntymään. Koeputkihedelmöityshoidoista lapsen syntymään eteni 20,5 prosenttia. Inseminaatiohoidoissa osuus oli 10,5 prosenttia."

Ehdotukseni:
hedelmöityshoidon alle koeputkihedelmöityksen rinnalle inseminaatiohoito.
Ja jos tarvitaan tarkennetta keinosiemennykselle (eläimet / eläinlääketiede)

Nyt ysossa keinohedelmöitys ohjaa koeputkihedelmöitykseen mutta tuon yllä olevan Hesarin uutisen perusteella voisi tulkita keinohedelmöitys = hedelmöityshoito, koska  on muitakin muotoja kuin koeputkihedelmöitys

Jos inseminaatiohoito ei kuulosta hyvältä, vaihtoehtoisesti:
keinosiemennys (ihmiset) KÄ keinohedelmöitys
Keinohedelmöityksen ohjaus koeputkihedelmöitykseen pitäisi tässäkin tapauksessa purkaa. 

Edit 8.6.20
Nythän inseminaatio ohjaa keinosiemennykseen, pitäisikö sillekin tehdä jotain, jos inseminaatiohoito otetaan käytettäväksi termiksi?

**Comment by YSO-kokous** [comment]
Sanastoon seuraavat:
- keinosiemennys (ihmiset), ohjaustermiksi inseminaatiohoito, yläkäsitteeksi hedelmöityshoito
- keinosiemennys (eläimet)

Edit. päätermiksi inseminaatiohoito (KT keinosiemennys (ihmiset))
