### ISSUE TITLE
avaruusoliot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8100]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

avaruusoliot 

#### Vaihtoehtoiset termit ja ilmaisut   

avaruusolennot 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ennustettu muoto 

#### Perustelut ehdotukselle   

https://www.suomalainen.com/products/ennustettu-muoto 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [avaruusoliot](http://finto.fi/yse/fi/page/Y508100)

**Comment by mirmaid** [comment]
KAUNOssa on avaruusolennot (avaruusoliot varmaan hyvä lisätä ohjaustermiksi?). 

YSOssa on _maapallon ulkopuolinen elämä, vieraat sivilisaatiot_ ja _humanoidit_.

**Comment by mariaforsen** [comment]
Kun YSOssa jo on humanoidit (=kuviteltu ihmistä muistuttava avaruusolento) niin varmasti otetaan myös avaruusoliot/olennot?
Sv. rymdvarelser (on myös SAOssa)

**Comment by tpalonen** [comment]
Hyvin paljon päällekkäinen humanoidien kanssa. Tarvitaanko molempia? Humanoidit-käsitettä käytetty kuvailussa vain hyvin vähän muussa kuin avaruusolento/-olio-merkityksessä. Avaruusolento on avaruusoliota hieman käytetympi termi Googlen perusteella ja humanoidia monikäyttöisempi, koska avaruusolento voi olla muutakin kuin ihmismäinen. Ehdottaisin humanoidit-käsitteen muuttamista muotoon avaruusolennot. Humanoidit ja avaruusoliot ohjaustermiksi.

**Comment by mariaforsen** [comment]
Kannatan että selkeytetään joo ja mieluummin pääterminä avaruusolennot (pääterminä humanoidit ja KT avaruusolennot ei ole ok ratkaisu). Sen lisäksi humanoidit-termi on nyt jo ongelmallinen koska se voi olla mikä vain "ihmistä muistuttava" esim. robotti jne. Ks. https://fi.wikipedia.org/wiki/Humanoidi

**Comment by YSO-kokous** [comment]
Vaihdetaan humanoidit-käsitteen käytettäväksi termiksi avaruusolennot. Avaruusoliot ja humanoidit ohjaustermeiksi.

**Comment by mariaforsen** [comment]
Sv. rymdvarelser ET utomjordingar
