### ISSUE TITLE
luonnonvakiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8101]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luonnonvakiot 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/Luonnonvakio 

#### Perustelut ehdotukselle   

https://www.suomalainen.com/products/luonnon-luonto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Luonnon luonto 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [luonnonvakiot](http://finto.fi/yse/fi/page/Y508101)

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

LCSH: Physical constants

**Comment by mariaforsen** [comment]
Sv. naturkonstanter ET fysikaliska konstanter

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
