### ISSUE TITLE
aineopetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8104]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aineenopetus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.gaudeamus.fi/wp-content/uploads/2019/12/9789523450653_Sisallys.pdf 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [aineenopetus](http://finto.fi/yse/fi/page/Y508104)

**Comment by mirmaid** [comment]
_Aineopetus_ 36 viitettä Melindassa.
_Aineenopetus_ 4 viitettä Melindassa, joissa kielipainotteinen/vieraskielinen/kaksikielinen aineenopetus.

Sanastossa on _ainedidaktiikka_, mutta ehdottaja kokee sen liian täsmällisenä. 
Kielitoimiston sanakirja: didaktiikka: _opetukseen liittyviä kysymyksiä käsittelevä kasvatustieteen osa._ _Didaktiikka on opettajan työtä (erityisesti opetussuunnitelmia, niihin perustuvaa suunnittelua, opetusta ja oppilaiden tavoiteltua oppimista ja sen arviointia) tutkiva ja kehittämään pyrkivä tiede._ http://www.edu.helsinki.fi/bio/didaktiikka/didaktiikka-kehitys/didaktiikka.htm

Varmaan ero on olemassa, jos ei tutkita nimenomaan didaktisia kysymyksiä, vaan laajemmin esim. jonkin aineen tai aineiden opetusta esim. Suomessa tai alakoulussa, mutta toisaalta silloin luultavasti käytettäisiin myös yhdistelmää oppiaine x & opetus. Toisaalta on myös mahdollista, että _aineopetus_-käsitettä käytettäisiin _ainedidaktiikan_ sijasta myös silloin, kun kyse on didaktiikasta.

**Comment by mariaforsen** [comment]
Sv. ämnesundervisning

**Comment by ilona-x** [comment]
Ehdotettu myös aiemmin **aineopetus** https://github.com/Finto-ehdotus/YSE/issues/600

fi        **aineenopetus**
määritelmä
tiettyyn oppiaineeseen liittyvä, kyseiseen oppiaineeseen pätevöityneen aineenopettajan antama opetus (1)
huomautus
Perusopetuksessa aineenopetusta on pääosin vuosiluokilla 7–9; tätä alemmilla vuosiluokilla lähes kaikkien oppiaineiden opetusta (1) antaa luokanopettaja. Lukiokoulutuksessa kaikkien oppiaineiden opetus (1) on aineenopetusta.

Lähde:  Opetus- ja koulutussanasto, 1. laitos (OKM, 2018:22)
https://termipankki.fi/tepa/fi/haku/aineenopetus

YSOssa myös **aineenopettajat** http://www.yso.fi/onto/yso/p4071

**Comment by YSO-kokous** [comment]
Ei koettu aineopetus/aineen opetus -käsitettä tarpeelliseksi erillisenä käsitteenä. Olisi kuitenkin hyvä, että termi on sanastossa. Päätettiin seuraavista:

aineopetus KÄYTÄ ainedidaktiikka
aineenopetus KÄYTÄ ainedidaktiikka
aineopetus KÄYTÄ opetus
aineenopetus KÄYTÄ opetus

Keskustelua: Ainedidaktiikka on spesifimpi käsite kuin aineopetus (ainedidaktiikka liittynee enemmän kyseisen aineen opillisiin kysymyksiin, aineopetus käytäntöön). Jos otetaan sanastoon niin riski, että käytetään ainedidaktiikan kanssa ristiin, kun aineopetus on yleiskielisempi. Ongelmana voisi olla myös, miten jatkossa kuvailtaisiin esim. matematiikan opetus: matematiikka + opetus vai matematiikka + aineopetus.
