### ISSUE TITLE
pastoraaliteologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8106]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pastoraaliteologia](http://www.yso.fi/onto/ysa/Y144982) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT pastoraalityö 

#### Perustelut ehdotukselle   

YSOssa on termi pastoraalityöt - tarvittaisiinko lisäksi ohjaustermiä pastoraalityö KÄ pastoraaliteologia, jos on sama asia.
https://opiskelijablogiblog.wordpress.com/2016/12/04/pastoraalityo/ 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by leinon** [comment]
YSO-termit ”pastoraalityöt” ja ”pastoraaliteologia” ovat eri asioita. Pastoraalityö on opinnäyte, joka koski vakinaista papinvirkaa hakevia, ja myöhemmin myös lehtorin virkaa hakevia, 1800-luvun loppupuolelta 1970-luvun alkupuolelle. Pastoraalitöitä säilytetään tuomiokapituleissa. Huom. myös teos ”Pastoraalitöiden bibliografia” Finnassa: https://www.finna.fi/Search/Results?lookfor=Pastoraalit%C3%B6iden+bibliografia&type=AllFields

Pastoraaliteologia sitä vastoin on käytännöllisen teologian osa-alue.
Helsingin yliopiston teologisen tiedekunnan kotisivuilta: https://www.helsinki.fi/fi/teologinen-tiedekunta/tutkimus/tieteenalat-ja-tutkijat/kaytannollinen-teologia 
”Pastoraaliteologia on käytännöllisen teologian osa-alue, joka tutkii yksilöiden tai ryhmien kohtaamisen kokemuksia. Siihen sisältyy käytännöllisen teologian perinteisistä tutkimuskohteista sielunhoidon, diakonian, jumalanpalveluselämän ja spiritualiteetin tutkimusta. Alan uusimmassa tutkimuksessa korostuvat rituaalit, kehollisuus ja konteksti osana elettyä uskonnollisuutta.  Tutkimuksen lähtökohtana on usein yksilön tai yhteisön kokema muutos, jonka seurauksena käynnistyy prosessi, missä haetaan selityksiä tai merkityksiä tapahtuneelle. Teoreettisilta lähtökohdiltaan oppiaine on poikkitieteellinen.”

**Comment by mirmaid** [comment]
Ehdotuksen linkin takana käytetään yksiköllistä sanaa _pastoraalityö_ synonyymina _pastoraaliteologialle_. Tarkoitus ei siis ole yhdistää näitä, vaan ohjata pastoraalityö-sanalla myös pastoraaliteologiaan.

_Toisella tunnilla käsittelimme pastoraalityön raamatullisia perusteita. -- Pastoraalityö on nuori tieteenala, joka syntyi 1800- luvun lopulla, mutta alkoi vahvisttumaan erityisesti 2.maailmansodan jälkeen._

**Comment by YSO-kokous** [comment]
Ehdotettu ohjaustermi on ok.
