### ISSUE TITLE
ennakkoratkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8107]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ennakkoratkaisut](http://www.yso.fi/onto/ysa/Y130055) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava? 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Ennakkoratkaisu 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
ennakko­ratkaisu
oik.
1. viranomaisen jstak asiasta ennakolta antama ratkaisu, joka sitoo sen antajaa asiaa uudelleen käsiteltäessä.
Korkeimman oikeuden Euroopan unionin tuomioistuimelta pyytämä ennakkoratkaisu.
Keskusverolautakunnan antama ennakkoratkaisu.

2. ennakkopäätös.

**Comment by mariaforsen** [comment]
Sanastossa on jo myös ennakkopäätökset (prejudikaatit), eli siinä merkityksessä ei varmasti tarvita tätä termiä. 
https://finto.fi/yso/fi/search?clang=fi&anylang=on&q=prejudikat
Eikö riittäisi että ohjataan käyttöä mahdollisimman johdonmukaiseksi tai lisätään huomautus?

**Comment by mirmaid** [comment]
Eli ennakkopäätös: _oik. tav. ylimmän oikeusasteen päätös, jota käytetään ohjeena ratkaistaessa muita samanlaisia oikeuskysymyksiä, prejudikaatti._ (wikipediassa myös tästä käytetään sekä nimitystä ennakkopäätös, että ennakkoratkaisu)

YSOssa ennakkoratkaisut-käsitteellä on huomautus: Käytetään lähinnä EY-oikeuden yhteydessä. Wikipedia: https://fi.wikipedia.org/wiki/Ennakkoratkaisu:

- Ennakkopäätös, prejudikaatti
- Ennakkoratkaisu (verotus), Suomen verohallinnon tekemä päätös verotuksesta säännöstulkinnan ennakoimiseksi
- Ennakkoratkaisu (EU), Euroopan Unionin tuomioistuimen tekemä päätös ennakkoratkaisupyynnön perusteella

EKS: 
ennakkoratkaisu: KT Euroopan yhteisöjen tuomioistuimen ennakkoratkaisumenettely
ennakkotieto: ennakkotieto verotuksessa, Keskusverolautakunnan ennakkoratkaisu

**Comment by mirmaid** [comment]
Pikaisesti katsoen näyttää siltä, että sekä _ennakkoratkaisut_ että _ennakkopäätökset_ -käsitteitä on käytetty eri merkityksissä, esim. ennakkopäätökset: https://melinda.kansalliskirjasto.fi/byid/015349124.

**Comment by YSO-kokous** [comment]
ennakkoratkaisut (EU-oikeus)
ennakkopäätökset (prejudikaatit)

ennakkoratkaisut (verotus) - suhde ennakkotietoihin?

**Comment by ilona-x** [comment]
https://www.veropro.fi/ennakkoratkaisu-ja-ennakkotieto/huomioitavaa.html

**Comment by ilona-x** [comment]
EKS:
Asiasana:	**ennakkotieto**	
Korvaa termin:	ennakkotieto verotuksessa, Keskusverolautakunnan ennakkoratkaisu

Asiasana ruotsiksi:	förhandsbesked
Asiasana englanniksi:	advance ruling

**Comment by ilona-x** [comment]
Verosanasto (c) valtioneuvoston kanslia 2002 https://mot.kielikone.fi/mot/valter/: 

**ennakkotieto**
 
Määritelmä:	  	
veroviraston ennalta antama kannanotto siihen, miten se tulee verotusta toimittaessaan ratkaisemaan verovelvollisen hakemuksessaan tarkoittaman tulo- tai varallisuusverotusta koskevan asian
	  
Selite:	  	
Ennakkotieto sitoo verovirastoa, jos verovelvollinen niin vaatii. Ennakkotietoon ei voi hakea muutosta (vrt. ennakkoratkaisu).
	  
**förhandsbesked** 
	 
Määritelmä:
av skatteverk på förhand givet ställningstagande till frågan hur skatteverket kommer att avgöra en sådan fråga gällande inkomst- eller förmögenhetsbeskattningen som den skattskyldige nämner i sin ansökan då skatteverket verkställer beskattningen
	  
Selite:
Ett förhandsbesked är bindande för skatteverket om den skattskyldige så kräver. Ändring av förhandsbesked kan inte sökas (jfr förhandsavgörande).

----

**ennakkoratkaisu**
	  
Määritelmä:
sitova ratkaisu, jonka toimivaltainen viranomainen antaa hakemuksesta ennen veron määräämistä tai suorittamista hakijan tai lain tulkinnan kannalta tärkeästä asiasta
	  
Selite:
Eri verolajeissa toimivaltaisia viranomaisia ovat keskusverolautakunta, verovirasto, Tullihallitus ja Ajoneuvohallintokeskus. Ennakkoratkaisuun voi hakea muutosta (vrt. ennakkotieto).
	  
	  	
**förhandsavgörande**
	  
Määritelmä:
bindande avgörande som behörig myndighet på ansökan utfärdar i ärende som är viktigt för sökanden, eller för lagtolkningen, innan skatt påförs eller betalas
	  
Selite:
Behöriga myndigheter inom olika skatteslag är centralskattenämnden, skatteverk, Tullstyrelsen och Fordonsförvaltningscentralen. Ändring av förhandsavgörande får sökas (jfr förhandsbesked).

**Comment by mariaforsen** [comment]
YSOssa ennakkotiedot on ryhmässä 00, eli ei voida olettaa että on pelkästään verotuksesta kyse (förhandsbesked)

ennakkopäätökset (prejudikaatit)=prejudikat
ennakkoratkaisut (verotus)=förhandsavgöranden (skatt)
ennakkoratkaisut (EU-oikeus)=förhandsavgöranden (EU-rätt)

ennakkotiedot=förhandsuppgifter -00 Yleistermit
ennakkotiedot/tieto=förhandsbesked

**Comment by YSO-kokous** [comment]
oli ennestään: ennakkoratkaisut (EU-oikeus)=förhandsavgöranden (EU-rätt)
Uusi käsite: ennakkoratkaisut (verotus)=förhandsavgöranden (skatt)

Tehdään tarvittaessa erillinen issue ennakkotiedot -käsitteestä:
