### ISSUE TITLE
suojat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8109]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suojat](http://www.yso.fi/onto/ysa/Y107564) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennettava 

#### Perustelut ehdotukselle   

ruotsiksi skydd (objekt), yläkäsite ihmisen määrittämät paikat. Käytetty Melindassa lähinnä esineistä ja rakennuksista, mutta myös muutamia kertoja esim. eläinten suojapaikoista. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Ok, kunhan nämä erotetaan kuukautissuojista ja sateenvarjoista...  Eläintensuojatkin lienevät yleensä ihmisen tekemiä rakennelmia...  kuten [sateensuojat](https://www.kielitoimistonsanakirja.fi/#/sateensuoja) "_sateelta suojaava paikka. Sateensuojaksi rakennettu katos. Olla sateensuojassa._"

**Comment by mirmaid** [comment]
Käytetty Melindassa n. 200 kertaa. Sanastossa on muuten myös _suojarakenteet_. Työsuojelusanastossa tosin määritelty melko suppeasti. https://termipankki.fi/tepa/fi/haku/suojarakenne. Itselleni kyllä tuntuisi ihan luontevalta myös esim. tässä https://melinda.kansalliskirjasto.fi/byid/014012851.

_Suojarakenteet_ on käytetty Melindassa vain 23 kertaa, mutta melko väljästi. Ks. myös https://yle.fi/aihe/t/18-90462

**Comment by mirmaid** [comment]
Toisinaan riittäisi _kotelot (suojukset)_, mutta myös aineistoa suojuksista, jotka eivät ole koteloita vaan esim. tekstiilejä. https://melinda.kansalliskirjasto.fi/byid/014001915

**Comment by ilona-x** [comment]
YSOssa on erikseen:
eläinsuojat
kuukautissuojat
väestönsuojat
venesuojat KÄYTÄ venevajat

**Comment by mirmaid** [comment]
Toisinaan myös _suojaimet_ sopii.

**Comment by mirmaid** [comment]
Lähinnä näillä erilaisille askartelu/käsityö-aineistoille, joissa tehdään suojuksia erilaisille rikkoutuville tai teräville esineille tarvittaisiin varmaan jotain termiä, mutta _suojukset_ on taas hyvin laaja ja soveltuu sitten paljon isompiinkin asioihin (päällekkäinen tuon _suojarakenteet_ kanssa osittain).

Ovatko kännykän kuoret muuten koteloita? :thinking:

**Comment by YSO-kokous** [comment]
Yritetään jaotella Melindan viitteitä erilaisiin pienempiin ryhmiin.

**Comment by ilona-x** [comment]
Melindassa paljon viitteitä, joissa askarreltu/ommeltu erilaisia suojuksia:
lasipurkin suojus, kirveen suojus nahasta, viinipullon suojus, virkatut kukkaruukun suojukset, patjan irtopäällinen, ompelukoneen huppu

Näihin kuvailuun voisi mahdollisesti sopia tämänkaltainen termi:
MAO: **suojatekstiilit**: http://www.yso.fi/onto/mao/p844

**Comment by ilona-x** [comment]
toinen ryhmä näyttäisi olevan askartelu/metallityöt/puutyöt, tähän tapaan:

ilmalämpöpumpun suojakotelolle 
Nopeasti koottava peiteteline.
patterinsuoja
lämpöpatterille suoja
Muovisten parvekelaatikkojen suojaksi rakennettava värikäs kehys laudoista.
Metallinen potkurirauta (potkurisuoja)
Metallilevystä työstetty vesipostin taustaseinäke suojaa talon julkisivua.
Jätesäiliön, roskiksen, ristikollinen suojarakennelma

Näistä osaan voisi sopia YSOsta löytyvä kotelot (suojukset). 🤔

**Comment by ilona-x** [comment]
sitten on vähän isompia rakennuksia/rakennelmia/katoksia:

Niksinurkka:Nimimerkki A. V. Pudasjärveltä lähestyi yhdistystä hyväksi kokemallaan räkkäsuoja idealla.
Opinnäytteen produktio-osana Jurmon saaren luontopolkujen varteen sijoitettavien pysähdys- ja levähdyspaikkojen suunnittelu.
Ride-In-suoja :kulkupelit näppärästi turvaan.
Hyvin hoidettu nauta viihtyy kylmässäkin.

Tähän osioon sopivia termejä löytyy YSOsta:

katokset http://www.yso.fi/onto/yso/p11773
ST autokatokset

eläinsuojat http://www.yso.fi/onto/yso/p7035
venevajat (KT venesuojat) http://www.yso.fi/onto/yso/p25152

**Comment by ilona-x** [comment]
Sitten on erilaisiaa verhoja/näkösuojia:
Kangasovi veneen kajuutan kulkuaukkoon,
Suojakangas terassin kaiteiden sivuilla suojaa tuulelta ; valmistusohjeet.
Erilaisia näkösuojia ikkunaan.

**Comment by ilona-x** [comment]
Sitten joitakin suojapeitteitä:

Suojapeite haukkuu hintansa kylmällä ja sateella.
Pakkassuoja tai minikasvihuone oksista ja hallaharsosta.

--
Olisiko YSOn peitteet http://www.yso.fi/onto/yso/p3236 käytettävissä näihin?

**Comment by ilona-x** [comment]
Ja sitten tietenkin se Tsernobyl: :atom: 

Tsernobyl saa kaarevan arkun.
Pikakatsaus Tshernobylin nykypäivään /
Nytt skal över Tjernobyl.

**Comment by ilona-x** [comment]
Ja paljon muuta sekalaista. 😵 

Riekon Lagopus lagopus ja kiirunan Lagopus mutus lumisuojista 
Greenhouses and shelter structures for tropical regions 
Overshoe, talvikalossi, joka vedetään varsinaisen kengän päälle.
Riemua vai riesaa rättikatosta?. (vene)
Koneturvallisuus : suojukset : kiinteiden ja avattavien suojusten suunnittelun ja rakenteen yleiset periaatteet

**Comment by YSO-kokous** [comment]
poistetaan käsite "suojat".
