### ISSUE TITLE
Mannerheim-ristin ritarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8110]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Mannerheim-ristin ritarit](http://www.yso.fi/onto/ysa/Y94286) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan LT–ST-suhde asiasanaan "ritarikunnat" RT-suhteeksi 

#### Perustelut ehdotukselle   

Mannerheim-ristin ritarit eivät ole yhdenlaisia ritarikuntia, joten nykyinen termien välinen suhde vaatii hieman rukkaamista 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
LT arvoon liittyvä rooli

**Comment by jtuohini** [comment]
Ja lisäksi varmaan LT **sotilaat**, koska Mannerheim-ristejä on myönnetty vain sotilaille t.s. kaikki Mannerheim-ristin ritarit ovat sotilaita.
