### ISSUE TITLE
henkilöhistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8111]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[henkilöhistoria](http://www.yso.fi/onto/ysa/Y95335) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCSH-asiasanaan "Biography" [http://id.loc.gov/authorities/subjects/sh85014152] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto 

#### Perustelut ehdotukselle   

Erittäin keskeinen käsite sekä suomalaisessa että LCSH-sanastoa käyttävässä kuvailussa, joten siltaus voisi olla jatkossa hyödyksi

**Comment by tpalonen** [comment]
Tutkitaan ja tehdään linkitys tarvittaessa.

**Comment by ilona-x** [comment]
http://id.loc.gov/authorities/subjects/sh85014152 linkattu nyt ysoon elämäkerrat-käsitteeseen

**Comment by mirmaid** [comment]
Tätä voisi vielä pohtia laajemmin, miten halutaan toimivan kuvailussa.

**Comment by mariaforsen** [comment]
On käyetty esim. kirjoista missä on paljon tietoja eri henkilöiden elämänhistoriasta. https://www.kielitoimistonsanakirja.fi/#/henkil%C3%B6historia?searchMode=all
https://fi.wikipedia.org/wiki/Henkil%C3%B6historia
https://www.sls.fi/sv/utgivning/kategori/biografier-och-personhistoria
https://www.sls.fi/sv/utgivning/kategori/biografier-och-personhistoria
Ja näin myös ruotsiksi.

**Comment by mirmaid** [comment]
Ohjaustermien perusteella _Biography_ voisi olla linkitettynä näihin molempiin ja myös _muistelmat_-käsitteeseen. En kyllä osaa sanoa, miten LCSH-käsite haluttaisiin tietueessa kääntää YSOksi. _Elämäkerrat_ ja _muistelmat_ voisi nähdä narrower match -tyyppisinä, mutta _henkilöhistoria_ on close match. Toisaalta meidän kuvailukäyttö sille on silti suppeampaa (?).

**Comment by jarmosaarikko** [comment]
MOT English antaa henkilöhistorian vastineeksi "**personal history**" jota voisi käyttää tässä käsitteessä.

LCSH ilmeisesti käyttää muotoa "personal narrative", jota ei taida olla siellä ole erillisenä käsitteenä.  
- LCSH "personal narrative" http://id.loc.gov/authorities/subjects/sh85100101  -- **Reference record only; not a valid heading.**
- YSOssa tämä on käännösvastineena käsitteessä "**kokemuskerronta**".

**Comment by krinay** [comment]
Ymmärrän alkuperäisen ehdotuksen eli ajatuksen linkityksestä henkilöhistoria/Biography. (= MOT English biography-sanan 2. merkitys.)

Vastaisivatko _elämäkerrat_ ja _muistelmat_ paremmin termiä _Biographies_, jota ei ole LCSH:ssa, vaan vain LC:n genreterminä.

(Termillä _kokemuskerronta_ / _henkilökohtainen kerronta_ viitataan kerronnan lajiin eli se on eri käsite, ks. Personal narratives: https://id.loc.gov/vocabulary/ethnographicTerms/afset013505.html.)

**Comment by mirmaid** [comment]
^ Varmaan tosiaan, tai niin, että jos on LCSH Biography, niin meillä tulisi mahdollisesti SLM elämäkerrat (osassa tapauksista siis), ei niinkään YSO elämäkerrat...

**Comment by jtuohini** [comment]
Siis jos LCSH:ssa on **Biography** joko itsenäisenä LCSH-asiasana tai ketjun osana (esim. **Composers--Finland--Biography**), tulee meillä aina **henkilöhistoria** YSO-asiasanana 650-kenttään. Tuleeko meillä tuon YSO-asiasanan lisäksi **elämäkerrat** tai **muistelmat** SLM-terminä 655-kenttään, pitää ratkaista tapauskohtaisesti.

LCGFT:n **Biographies** taas vastaa SLM:n **elämäkerrat**-termiä ja sille ST-suhteinen **Autobiographies** meilläkin samalla tavoin ST-suhteista **muistelmat**-termiä.

**Comment by mirmaid** [comment]
LCSH:ssa kuitenkin ohjaustermeinä myös biographies, life histories ja memoirs.

**Comment by mirmaid** [comment]
Tämä on siis kysymys LCSH:n ja LCGFT:n suhteesta genretermien osalta, ja soveltuvista linkityksistä YSOon ja SLM:ään. SLM:n osalta tilanne on varmaan suhteellisen selvä, mutta YSOn osalta on herättänyt pohdintaa, miten linkitetään YSO-käsite, jota LCSH:ssa käytetään genremäisesti. Jaakon esimerkin Biography olisi toki ok käännettynä henkilöhistoriaksi (ja yleisestikin näin, jos sitä tyypillisesti ei käytetä genretermien Biographies tai Autobiographies sijasta), koska tilanne on aika sama (eli kyse voi olla aineistosta, joka sisältää henkilöhistoriaa, tai aineistosta, jossa sitä tarkastellaan tutkimusalana).
