### ISSUE TITLE
Neuvosto-Karjala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8113]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Neuvosto-Karjala](http://www.yso.fi/onto/ysa/Y105072) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCNAF/LCSH-termiin "Karelʹskai︠a︡ A.S.S.R. (R.S.F.S.R.)" [http://id.loc.gov/authorities/names/n81022401] 

#### Perustelut ehdotukselle   

Tämäkin meikäläisittäin sen verran keskeinen paikannimi/yhteisönnimi, että siltauksen olisi hyvä olla kunnossa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
YSO-paikat-sanastolla ei toistaiseksi ole kongressin kirjaston sanastoihin linkitystä. Asiaa voidaan pohtia laajemmin. Ei kuitenkaan tehdä yksittäisiä linkityksiä toistaiseksi.
