### ISSUE TITLE
sorsat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8114]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sorsat](http://www.yso.fi/onto/ysa/Y105183) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

muotoon sorsat (heimo - Anatidae) 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.26264
Nyt tieteellinen nimi viittaa sukuun sorsat - Anas, josta tulossa ehdotus. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Tutkitaan.

**Comment by mariaforsen** [comment]
Ruotsinkielinen vastine tähän asti "änder"=Anatinae 
https://www.dyntaxa.se/Taxon/Info/1016772?changeRoot=True

Anatidae=änder, gäss och svanar https://www.dyntaxa.se/Taxon/Info/2002065?changeRoot=True
Anas=Anas
