### ISSUE TITLE
sorsat (suku)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8115]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sorsat (suku) 

#### Vaihtoehtoiset termit ja ilmaisut   

Anas 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sorsat](http://www.yso.fi/onto/yso/p8345) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.26357 
LCSH : <http://id.loc.gov/authorities/subjects/sh85004818.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

Suku sisältää Suomessa yleiset YSOssa olevat lajit: heinäsorsa ja tavi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, artikkeliaineisto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [sorsat (suku)](http://finto.fi/yse/fi/page/Y508115)

**Comment by mariaforsen** [comment]
Sv. Anas?

**Comment by mirmaid** [comment]
YSOssa on nyt siis sorsat = Anas, änder. Laji.fi:ssä on tätä vastaava https://laji.fi/taxon/MX.26357 (tässä ehdotettu), ja heimo Anatidae https://laji.fi/taxon/MX.26264.

Melindassa käytetty laajemmin kuin suku-merkityksessä - toisaalta sanastossa on myös _sorsalinnut_, johon ei kuulu muita Suomessa tavattavia heimoja kuin sorsat, https://laji.fi/taxon/MX.26257. 

Suuri osa viitteistä liittyy sorsastukseen ja linturuokiin, varsinkin jälkimmäisessä _sorsat (suku_) tai _sorsat (heimo)_ sopii huonosti, jos halutaan kuvailla tarkemmin kuin termillä _riistalinnut_.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8114

**Comment by jarmosaarikko** [comment]
YSOn [sorsalinnut](http://www.yso.fi/onto/yso/p14859) on **lahko** _Anseriformes_ https://laji.fi/taxon/MX.26257
YSOn [sorsat](http://www.yso.fi/onto/yso/p8345)-käsitteen alla on nyt puolisukeltajasorsia, sukeltajasorsia ja hanhia.
Se onkin tässä tapauksessa **heimo** _Anatidae_  https://laji.fi/taxon/MX.26264

sorsat (suku)  _Anas_   käsittää vain puolisukeltajasorsia.  https://laji.fi/taxon/MX.26357  joten YSOn hierarkiassa tämä sijoittuisia puolisukeltajasorsien alle. Minusta tämä käsite on tarpeeton YSOn nykyisessä hierarkiassa.  Samalla pitäisi tosin tarkemmin lisätä  nykyisen "sorsat" käsitteen määrittelyyn, että se on heimo!

Näitä eläinkäsitteiden määrittelyä helpottaisi huomattavasti, jos mukana olisi taksonin tieteellinen nimi aina, kun se on mahdollista!

**Comment by YSO-kokous** [comment]
Muutetaan YSOn sorsat käytettävä termi muotoon _sorsat (suku)_. Ohjaustermiksi otettaneen Anas. Ei muita muutoksia/lisäyksiä.

Kielissä eroa sen mukaan, mille taksonille on olemassa yleiskielen nimitys ja mille ei: sorsat (suku) (latinaksi Anas) on ruotsin kannalta ongelmallinen. Anatinae-käsitteelle taas ei ole suomeksi termiä. Päädyttiin nyt kuitenkin kompromissina tähän ratkaisuun. Ruotsiksi käsitteellä käytettäneen latinankielistä nimeä.
