### ISSUE TITLE
isokoskelo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8116]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[isokoskelo](http://www.yso.fi/onto/ysa/Y106179) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yläkäsitteeksi: koskelot 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.26442 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Hyväksytään ehdotus.
