### ISSUE TITLE
sorsat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8117]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sorsat](http://www.yso.fi/onto/ysa/Y105183) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan/siirretään alakäsitteet sukeltajasorsat ja puolisukeltajasorsat. 

#### Perustelut ehdotukselle   

Näitä ei ole laji.fi:ssä ja viittavat enemmänkin lintujen käyttäytymiseen kuin eläinsystematiikkaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Nimityksillä viitataan kuitenkin sorsiin, joten se on luontevin paikka niille hierarkiassa. Myöskään eläimet-käsitteen alla ei ole sopivaa ryhmää, johon nämä käsitteet voisi sijoittaa.
