### ISSUE TITLE
haapana

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8118]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[haapana](http://www.yso.fi/onto/ysa/Y203513) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tieteellinen nimi muuttunut: Mareca penelope 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.26360 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Lisätään ohjaustermiksi: Mareca penelope
