### ISSUE TITLE
heinätavi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8119]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[heinätavi](http://www.yso.fi/onto/ysa/Y504962) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tieteellinen nimi muuttunut: Spatula querquedula 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.26388 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Lisätään Spatula querquedula ohjaustermiksi.
