### ISSUE TITLE
harmaahanhet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8120]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

harmaahanhet 

#### Vaihtoehtoiset termit ja ilmaisut   

Anser 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sorsat](http://www.yso.fi/onto/yso/p8345) 

#### Alakäsitteet (RT)   

[merihanhi](http://www.yso.fi/onto/yso/p19646) 
[kiljuhanhi](http://www.yso.fi/onto/yso/p15981) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.26285/taxonomy 
LCSH : <http://id.loc.gov/authorities/subjects/sh89005362.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

hanhet-käsitettä ei ole laji.fi:ssä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, artikkeliaineisto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [harmaahanhet](http://finto.fi/yse/fi/page/Y508120)

**Comment by mariaforsen** [comment]
Sv. ansergäss /NE ET Anser

**Comment by mirmaid** [comment]
Eli pitäisikö oikeastaan muuttaa hanhet > harmaahanhet?

**Comment by mirmaid** [comment]
Laji.fi: https://laji.fi/taxon/MX.5013225 - Harmaa-/kirjohanhi (hanhilaji) – Anser/Branta?

Wikipedia: Hanhet (Anserinae) on sorsien (Anatidae) heimon alaheimo. https://fi.wikipedia.org/wiki/Hanhet vrt. https://laji.fi/taxon/MX.206961: tämän alla on tribus Anserini https://laji.fi/taxon/MX.206961 ja sen alla yllä mainittu Anser/Branta-lajiryhmä.

Tavallinen tallaaja varmaan mieltäisi hanhien olevan tuo lajiryhmä, eli Anserinae-suku ilman joutsenia (Anserini-tribus, joka tuntuu olevan sama asia kuin Anser/Branta-lajiryhmä, ainakaan Laji.fi ei mainitse siihen kuuluvan muuta).

**Comment by mariaforsen** [comment]
Anserinae=gäss och svanar
Anser/Branta=gäss https://www.dyntaxa.se/Taxon/SearchResult/2000891?search=Anser%2FBranta eli en kannata sen ottamista YSOon ainakaan siinä sekavassa muodossa ("Harmaa-/kirjohanhi (hanhilaji")

**Comment by mirmaid** [comment]
^ Ei toki siinä muodossa. Vaikuttaa siltä, että sekä tuo anser/branta, että anserini ovat kuitenkin merkitykseltään sama kuin YSOn _hanhet_, eli harmaahanhet + kirjohanhet. Eli jos Laji.fi:ssäkin on tällainen lajiryhmä/tribus, niin en tiedä miksi YSOssa ei voisi olla sitä vastaava _hanhet_.

**Comment by YSO-kokous** [comment]
Otetaan YSOon hanhet-käsitteelle kaksi alakäsitettä: kirjohanhet ja harmaahanhet.

**Comment by mariaforsen** [comment]
Sv. 
-brantagäss
-ansergäss
