### ISSUE TITLE
kirjohanhet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8121]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirjohanhet 

#### Vaihtoehtoiset termit ja ilmaisut   

Branta 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sorsat](http://www.yso.fi/onto/yso/p8345) 

#### Alakäsitteet (RT)   

[valkoposkihanhi](http://www.yso.fi/onto/yso/p23701) 

#### Vastaava käsite muussa sanastossa   

laji.fi : https://laji.fi/taxon/MX.26296 
LCSH : <http://id.loc.gov/authorities/subjects/sh85016424.html> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

hanhet-käsitettä ei ole laji.fi:ssä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helka, artikkeliaineisto 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kirjohanhet](http://finto.fi/yse/fi/page/Y508121)

**Comment by mariaforsen** [comment]
Sv. brantagäss

**Comment by mirmaid** [comment]
Eli pitäisikö oikeastaan muuttaa hanhet > kirjohanhet?

**Comment by mariaforsen** [comment]
Muitakin hanhia tietysti on, joten en tiedä voiko noin suoranaisesti muuttaa, olisiko parempi lisätä?

**Comment by jarmosaarikko** [comment]
Jos "**hanhet**" muutetaan, niin sitten pitäisi olla molemmat: **harmaahanhet** ([Anser](http://www.yso.fi/onto/yso/p405)) kts. 
 #8120  ja **kirjohanhet** ([Branta](http://tun.fi/MX.26296))
[laji.fi](https://laji.fi/) ei sisällä "hanhet" käsitettä, mutta YSOn käsitettä vastaava yhdistelmä on kuvattu nimellä: **harmaa-/kirjohanhi** tai "**hanhilaji**" (_Anser/Branta_) http://tun.fi/MX.5013225  -- kuten Mirja onkin todennut tuolla toisessa issuessa.

**Comment by YSO-kokous** [comment]
Otetaan YSOon hanhet-käsitteelle kaksi alakäsitettä: kirjohanhet ja harmaahanhet.
