### ISSUE TITLE
tikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8124]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tikat](http://www.yso.fi/onto/ysa/Y99542) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tikat (heimo - Picidae) 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.30331
Sukuja: 
käpytikat - käpytikka, valkoselkätikka, pikkutikka
kirjotikat - pohjantikka
palokärjet - palokärki 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Entä chicken tikka?
https://en.wikipedia.org/wiki/Chicken_tikka

**Comment by tpalonen** [comment]
Toivotaan lisäkommenttia ehdottajalta: mitä muutosta tarkalleen ottaen kaivataan.
