### ISSUE TITLE
lokit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8125]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lokit](http://www.yso.fi/onto/ysa/Y107197) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lokit (heimo - Laridae) 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.27732
sukuja:
lokit (Larus) - harmaalokki, kalalokki, selkälokki
sirolokit (Chroicocephalus) - naurulokki 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Olen eri mieltä. Tekisin muutoksen seuraavasti, sillä "Laridae" -heimo sisältää mm. lokit (Larinae), tiirat (Sterninae), saksinokat.  Tämä on hankala ryhmä, kun tieteilijätkään eivät nimeä tasoja loogisesti.
Heimo Laridae olisi suomeksi mieluummin  esim. "lokkilinnut", 
mutta  finbif antaa tälle nimeksi "lokit".
fi: lokkilinnut  KT Laridae   BT rantalinnut
sv: måsfoglar 
en:  "Laridae" http://id.loc.gov/authorities/subjects/sh85074717
wd: "Laridae" https://en.wikipedia.org/wiki/Laridae

"lokit"  KT "Larinae" https://laji.fi/taxon/MX.207062 (ei suomenkielistä nimeä) 
sv: "måsar och trutar"
en: "gulls" http://id.loc.gov/authorities/subjects/sh85057898  KT seagulls, Larinae
Wikidata https://fi.wikipedia.org/wiki/Lokit_(alaheimo)  (Larinae)

**Comment by jarmosaarikko** [comment]
YSOn hierarkia voisi mennä siis seuraavasti:
- rantalinnut KT Charadriiformes (lahko)
- - **lokkilinnut**  KT **Laridae** (heimo)    sv: **måsfoglar**  en: **gulls and tern**s
- - - **lokit**  KT **Larinae** (alaheimo)   sv: **måsar och trutar**  en: **gulls**
- - - - harmaalokki 
- - - - kalalokki 
- - - - naurulokki
- - - - selkälokki 
- - - **tiirat** KT **Sterninae**  sv: **tärnor** en: **terns**  
- - - - kalatiira
- - - - lapintiira
- - - - räyskä

**Comment by tpalonen** [comment]
Lokit ei YSOssa ole sama asia kuin Laridae. Tutkitaan vielä asiaa.

**Comment by mariaforsen** [comment]
Tarkennettava mihin latinankieliseen nimitykseen "lokit" YSOssa viittaa, että saadaan oikea ruotsinkielinen vastine.

**Comment by jarmosaarikko** [comment]
Alakäsitteiden perusteella YSOn **lokit** olisi sama kuin tuo mainitsemani "**Larinae**" (alaheimo) ja ruotsiksi "**måsar och trutar**".    
Lajitietokeskuksessa alaheimolla  on vain tieteellinen nimi. Siellä "lokit" on terminä yhtä taksonomista tasoa ylempänä eli "Laridae" (heimo), joka on käytännössä sama kuin "lokit ja tiirat" (ja vähän muitakin).  
YSOn hierarkia hyppää suoraan lahkosta alaheimoon.

**Comment by mirmaid** [comment]
Kannatan Jarmon ehdotusta lokit = Larinae. Tämä olisi yleistajuista, koska tiirat varmasti keskimäärin mielletään omaksi ryhmäkseen, kun taas sirolokkeihin kuuluvat naurulokit lokeiksi.

**Comment by jarmosaarikko** [comment]
Birdlife Finlandin nimistötoimikunnan edustajan ehdotus ratkaisuksi:

> Ehdotan, että siellä, missä on sekaantumisen riski, perään lisätään sulkeissa sana heimo tai suku, esim. lokit (heimo) tai lokit (suku). 
> Missään nimessä ei kannata käyttää loppuliitettä -linnut, sillä sitä on käytetty vain kuvaamaan **lahkojen** nimiä (esim. kuikkalinnut Gaviiformes).
> Suomenkielisessä nimistössä lajien lisäksi on nimetty lahkot, heimot ja suvut, joissa on vähintään kaksi lajia. 
> Muita taksonitasoja (esim. ylä- ja alaheimot) ei ole nimetty suomeksi. Jos niitä tarvitaan, ehdotan taksonitasoa lisättävksi sulkeisiin - esim. Laroidea (yläheimo).
> [Laji.fi](https://laji.fi/taxon/MX.37580/taxonomy?showTree=true) seuraa lintujen suomenkielisten nimien osalta Birdlifen nimistötoimikunnan listaa, mutta tieteellisten nimien osalta [Howard & Moorea](https://www.aviansystematics.org/4th-edition-checklist). - [Laridae](https://www.aviansystematics.org/4th-edition-checklist?viewfamilies=61)

kts. myös 
- https://www.birdlife.fi/lintutieto/maailman-lintulajien-suomenkieliset-nimet/
-  https://birdlife.se/tk/svenska-namn-pa-varldens-faglar/

**Comment by mirmaid** [comment]
Lisätty huomautus lokit-käsitteelle: _Nimitystä lokit käytetään yleiskielessä lähinnä Larinae-alaheimon linnuista. Taksonomiassa nimitystä voidaan käyttää myös koko Laridae-heimosta._

Ei oteta lokkilinnut-käsitettä erikseen, koska sopivaa suomenkielistä vastinetta ei löydy, ja kuvailussa käytettäisiin luultavasti kuitenkin mieluummin lokit-käsitettä. Se ei myöskään ole aineistoissa väärin, vaan ainoastaan kattavuudeltaan suppeampi kuin koko Laridae-heimo.
