### ISSUE TITLE
garage rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8126]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[garage rock](http://www.yso.fi/onto/ysa/Y141509) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan käytettävä termi alla olevissa tapauksissa seuraavasti:
folk rock > folkrock
garage rock > garagerock
glam rock > glamrock
punk rock > punkrock
hardcore punk > hardcorepunk
hip hop > hiphop
drum 'n' bass > drum'n'bass
bossa nova > bossanova 

#### Perustelut ehdotukselle   

Musiikin genrenimien yhteen- tai erikseenkirjoituksesta on käyty keskustelua. Pitäisikö nämä kirjoittaa systemaattisesti yhteen vai erikseen? Minkälaista kirjoitusasua suomalaisessa mediassa suositaan? Tuomas Palonen teki kyselyn YSOn musiikkigenrejen kirjoitusasuista kotimaisille musiikkitoimittajille. Kyselyyn osallistuivat Janne Flinkkilä (creat.fi), Laura Friman (Yle, Radio Helsinki), Jukka Hätinen (Rumba), Antti Lähde (kulttuuritoimitus.fi), Mikko Meriläinen (Soundi), Matti Riekki (Inferno) ja Marko Ylitalo (Helsingin Sanomat). Pisteytin kirjoitusasut sen mukaan, mitä asua kukin toimittaja kannatti. Alla tulokset. Kuten näkyy, hajontaa on eikä mitään vedenpitävää sääntöä voi muodostaa (paitsi ehkä sen, että metallin alalajit näytetään kirjoitettavan poikkeuksetta erikseen).

country rock 4 / countryrock 3 (tai kantrirock 1)
folk rock 3 / folkrock 4 
garage rock 2 / garagerock 5 
glam rock 3 / glamrock 4
gospel rock 3 / gospelrock 4
hard rock 4 / hardrock 3
heavy metal 5 / heavymetal
indie rock 3 / indierock 4
indie pop 2 / indiepop 5
latin rock 5 / latinrock 1 (tai latinorock 1)
punk rock 3 / punkrock 4
hardcore punk 2 / hardcorepunk 5
rock and roll 6 / rockandroll (tai rock'n'roll 1)
southern rock 6 / southernrock
black metal 6 / blackmetal
death metal 6 / deathmetal
doom metal 6 / doommetal
folk metal 6 / folkmetal
speed metal 6 / speedmetal
thrash metal 6 / trashmetal
hip hop 2 / hiphop 4
rhythm and blues (tai rhythm & blues) 6 / rhythmandblues
rock steady 1 / rocksteady 4
western swing 6 / westernswing
drum 'n' bass 1 / drum'n'bass 5
bossa nova 2 / bossanova 4
latin pop 5 / latinpop 1 (tai latinopop 1)
son mexicano 4 / sonmexicano 1

Janne Flinkkilä:
"Vastaan yleisellä tasolla yhteisesti näihin kaikkiin: silloin kun genrenimitys on molempine osineen vakiintunut osaksi suomenkielistä ilmaisua, sanat kirjoitetaan suomen kieliopin mukaisesti yhteen. Tämä on mielestäni kuitenkin vahvasti kontekstisidonnainen asia: esimerkiksi musiikin erikoismedian kohderyhmälle ilmaisut vakiintuvat nopeammin ja laajemmalta alalta kuin ns. suurelle yleisölle. Lähestyisin aihetta siis sen mukaan, kenelle kirjoitetaan. Kuitenkin sikäli loogisesti, että media määrittelee tyylikirjan, jossa linja päätetään ja sitä noudatetaan johdonmukaisesti. Tätä linjaa on toki paikallaan ajoittain tarkistaa."

Kielitoimisto ei tunnu tarjoavan tähän mitään yksiselitteistä ohjetta:
"Kirjoitustapa on kuitenkin sanakohtainen: osa moniosaisista vierasperäisistä ilmauksista kirjoitetaan yhteen myös ilman yhdysmerkkiä, osa erikseen sanaliitoiksi."
http://www.kielitoimistonohjepankki.fi/ohje/83 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Harmikseni huomasin, että muutama YSOn jazz- ja blues-genre jäi kyselystä pois. Pahoittelut!

**Comment by tpalonen** [comment]
Latin popin osalta nostettiin Githubissa keskusteluun vielä muoto _latinopop_, joka näyttääkin verkkohaun perusteella suositummalta muodolta kotimaisessa mediassa kuin _latin pop_.
https://github.com/Finto-ehdotus/YSE/issues/7834

**Comment by MUUSA-kokous** [comment]
Muusa ei kannata termien muuttamista, mutta vaihtoehtoiset muodot on syytä lisätä ohjaustermeiksi. Sama SLM:ään.

**Comment by mirmaid** [comment]
Lisätään ohjaustermit / SLM.
