### ISSUE TITLE
GIF

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8127]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

GIF 

#### Ehdotettu termi englanniksi   

GIF 

#### Ehdotettu termi ruotsiksi   

GIF 

#### Vaihtoehtoiset termit ja ilmaisut   

GIF-tiedosto 
Graphics Interchange Format 

#### Perustelut ehdotukselle   

GIF (lyhenne sanoista Graphics Interchange Format) on yleisesti käytössä oleva häviötön bittikarttagrafiikan tallennusformaatti. https://fi.wikipedia.org/wiki/GIF 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.aslongaspossible.com/images/As_long_as_possible_publication_2018.pdf 

**Termiehdotus Fintossa:** [GIF](http://finto.fi/yse/fi/page/Y508127)

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
