### ISSUE TITLE
johanniitat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8128]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[johanniitat](http://www.yso.fi/onto/ysa/Y111685) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCSH/LCNAF-termiin Knights of Malta [http://id.loc.gov/authorities/names/n79114238] 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Tutkitaan ja lisätään linkki tarvittaessa.
