### ISSUE TITLE
teodikea

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8131]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teodikea](http://www.yso.fi/onto/ysa/Y111859) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään KT teodikean ongelma 

#### Perustelut ehdotukselle   

http://tieteentermipankki.fi/wiki/Filosofia:teodikean_ongelma 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
