### ISSUE TITLE
temaattiset luettelot (musiikki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8132]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[temaattiset luettelot (musiikki)](http://www.yso.fi/onto/ysa/Y214694) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan SLM 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto 

#### Perustelut ehdotukselle   

Esim. Ryom, Peter: Antonio Vivaldi : thematisch-systematisches Verzeichnis seiner Werke (RV)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. LT kuten YSOssa.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
