### ISSUE TITLE
nokisienet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8133]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nokisienet 

#### Perustelut ehdotukselle   

Myös 
härmäsienet
jauhiot
pöhösienet
tuhkiosienet
ruostesienet
juuriosienet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789515157447 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [nokisienet](http://finto.fi/yse/fi/page/Y508133)

**Comment by mariaforsen** [comment]
Sv. sotsvampar ET Ustilaginomycotina
