### ISSUE TITLE
Ilmoitinlaitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8134]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ilmoitinlaitteet 

#### Perustelut ehdotukselle   

Hätäkeskuslaitoksen tuottamissa palveluissa ilmoitinlaitteet ovat palo- ja rikosilmoitilaitteet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

YJA-verkkosivu 

#### Tarkoitusta täsmentävä selite   

paloilmoitinlaitteet, rikosilmoitinlaitteet 

**Ehdottajan organisaatio:** Hätäkeskuslaitos **Termiehdotus Fintossa:** [Ilmoitinlaitteet](http://finto.fi/yse/fi/page/Y508134)

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/ilmoitinlaitteisto
fi        valvontalaitteisto
ei: ilmoitin; ilmoitinlaitteisto; ilmoituslaitteisto
sv       entralutrustning
määritelmä
ilmoitusjärjestelmään kuuluva laitteisto, joka havaitsee valvontakohteessa tapahtuvan muutoksen, laitteiston teknisen vian, häiriön tai käyttövirheen sekä lähettää havainnosta ilmoituksen ilmoituksensiirtojärjestelmään
huomautus
Valvontalaitteistoon kuuluu mm. sähkölähteet, käyttölaite, ohjain, ohituslaitteet, ilmaisimet, ja ilmoitinkeskus.
Lähde: Rikosilmoitussanasto (TSK 21, 1993)

https://termipankki.fi/tepa/fi/haku/paloilmoitin
fi        paloilmoitin
mieluummin kuin: paloilmoituslaitteisto
sv       brandlarmanläggning
en      fire alarm system; fire alarm installation

määritelmä
laitteisto, joka antaa automaattisesti ja välittömästi ilmoituksen alkavasta palosta tai laitteiston toimintavalmiutta vaarantavista vioista sekä paikallisesti että hätäkeskukseen
huomautus
**Paloilmoitin muodostuu ilmoitinkeskuksesta, teholähteestä, paloilmaisimista, paloilmoituspainikkeista, palohälyttimistä ja automaattisesta ilmoituksensiirtojärjestelmästä.** Paloilmoittimessa pitää olla vähintään kaksi toisistaan riippumatonta teholähdettä, kuten sähköverkko ja akusto.
Käsitekaavio: Paloilmoittimia ja lähikäsitteitä.
Lähde:  Palo- ja pelastussanasto (TSK 33, 2006)	


https://termipankki.fi/tepa/fi/haku/rikosilmoitinlaitteisto
fi        rikosilmoituslaitteisto
ei: rikosilmoitinlaitteisto; rikosilmaisinlaitteisto
sv       brottslarmanläggning; inbrottslarmanläggning
määritelmä
rikosilmoitusjärjestelmään kuuluva valvontalaitteisto
Lähde: Rikosilmoitussanasto (TSK 21, 1993)

--

YSOssa on:
paloilmoituslaitteistot 
paloilmaisimet 
ilmaisimet
valvontalaitteet
varoituslaitteet 
hälyttimet
palohälyttimet
hälytysjärjestelmät
valvontajärjestelmät

**Comment by mirmaid** [comment]
Melindassa muutamia kertoja _rikosilmoitinjärjestelmät_ tai _rikosilmoitusjärjestelmät_.

**Comment by YSO-kokous** [comment]
Tutkitaan sopivia ohjaustermisuhteita. Tutkitaan vielä rikosilmoitinjärjestelmät tai rikosilmoitinlaitteet, otetaanko jokin tällainen erillisenä sanastoon.

**Comment by AuHo22** [comment]
YSOssa myös: turvajärjestelmät KT turvallisuusjärjestelmät

**Comment by mirmaid** [comment]
Olisiko:

- paloilmoitinlaitteet KÄ paloilmoituslaitteistot (https://fi.wikipedia.org/wiki/Automaattinen_paloilmoitin, https://112.fi/palo-ja-rikosilmoitinlaitteet)
- rikosilmoitinlaitteet KÄ hälytysjärjestelmät, turvajärjestelmät

**Comment by YSO-kokous** [comment]
Hyväksytään:
paloilmoitinlaitteet KÄ paloilmoituslaitteistot 
rikosilmoitinlaitteet KÄ hälytysjärjestelmät, turvajärjestelmät
