### ISSUE TITLE
hätäpuhelimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8135]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hätäpuhelimet](http://www.yso.fi/onto/ysa/Y101763) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

hätänumero 

#### Perustelut ehdotukselle   

Nykyisin ei puhuta hätäpuhelimista, koska hätäilmoituksen voi tehdä usealla eri tavalla, jolloin puhutaan virallisesti hätänumerosta (esim. tekstiviesti tai 112 Suomi sovelluksen kautta soitettu puhelu). Huomatkaa, euroopassa vain yksi hätänumero (monikkomuodon ongelma) 

#### Ehdottajan organisaatio   

Hätäkeskuslaitos

**Comment by ilona-x** [comment]
Hätäpuhelin taitaa tarkoittaa eri asiaa kuin hätänumero/hätäkeskus. Hätäpuhelimia näyttäisi olevan ainakin tunneleissa, liikennevälineissä ja hisseissä.

fi        hätäpuhelin
sv       hjälptelefon /SE/; nödtelefon /FI/
määritelmä
yleiseen käyttöön tarkoitettu maksuton puhelin, josta on suora yhteys hälytyskeskukseen
Lähde: Rikosilmoitussanasto (TSK 21, 1993)
https://termipankki.fi/tepa/fi/haku/h%C3%A4t%C3%A4puhelin

--

"Metrovaunuissa ja lähijunissa on hätäpuhelin/ sos-puhelin, jolla saa tarvittaessa yhteyden suoraan kuljettajaan."
"Asemilla, ratatunnelissa ja yhdyskäytävissä on hätäpuhelimia, joilla saat yhteyden junaliikenteen tekniseen valvomoon."
https://www.hsl.fi/asiakaspalvelu/nain-kaytat-joukkoliikennetta/turvallisuusohjeita

**Comment by mirmaid** [comment]
Hätäpuhelut KÄ hätäilmoitukset, hätänumero KÄ hätäkeskukset?

Hätäpuhelimet-termiä käytetty yleensä hätäpuheluista tai turvapuhelimista.

**Comment by mariaforsen** [comment]
Hätäpuhelimet=nödtelefoner on siis edelleen tarpeen YSOssa. https://sv.wikipedia.org/wiki/N%C3%B6dtelefon

**Comment by mirmaid** [comment]
Viitteissä, joissa termiä on käytetty merenkulkuun liittyen, on kyse todennäköisesti tapauskohtaisesti erilaisista laitteista, toisinaan oikeista hätäpuhelimista (satamassa), toisinaan veneen tai laivan hätäilmoituslaitteistosta, joka ei välttämättä ole erillinen puhelin. Osman kommentti: _en usko että on olemassa yhtä tiettyä laitetta, vaan se voi olla esim. satelliittipuhelin, tavallinen VHF-radio tai vaikka vanha Nokia jota käytetään tarvittaessa hätäviestin lähettämiseen._

**Comment by mirmaid** [comment]
Ehdotan että tehdään ohjaukset:

- hätäpuhelut KÄ hätäilmoitukset
- hätänumero KÄ hätäkeskukset
- hätäpuhelimet (turvapuhelimet/ikääntyneet) KÄ turvapuhelimet

Korjataan viitteet ja katsotaan tarvitaanko vielä jotain.

**Comment by fantsby-m** [comment]
Vaikka EU:ssa periaatteessa on yksi hätänumero (112) on Euroopassa käytössä lukuisia eri hätänumeroita, sekä EU:n sisällä että ulkopuolella: https://en.wikipedia.org/wiki/List_of_emergency_telephone_numbers#Europe.
Ja Euroopan ulkopuolella kirjo on vielä suurempi.

-> joten ehdotan että otetaan monikkomuoto ohjaustermiin _hätänumerot_.

**Comment by YSO-kokous** [comment]
Hyväksytään:
hätäpuhelimet - ei muutosta toistaiseksi. 
hätäpuhelut KÄ hätäilmoitukset
hätänumerot KÄ hätäkeskukset
hätäpuhelimet (turvapuhelimet) KÄ turvapuhelimet
Mietittävä tarvitaanko turvapuhelimet -käsitteelle tarkenne.

**Comment by mirmaid** [comment]
Korjataan hätäpuhelimet-termillä kuvaillut viitteet ja katsotaan tarvitaanko hätäpuhelimet-termiä, sekä tarvitseeko se tarkenteen, jotta ei jatkossa käytettäisi väärin.

**Comment by ilona-x** [comment]
Korjattu Melindasta hätäpuhelimet-termillä kuvaillut hätäilmoituksia ja hätäkeskuksia käsittelevät aineistot. Suurin osa jäljelle jääneistä viitteistä liittyy tuohon keskustelussa aiemmin mainittuun merenkulkuun

**Comment by mirmaid** [comment]
https://raja.fi/hatailmoitukset-ja-meriradioliikenne. Kävisikö merenkulkuunkin (ja myös muihin vastaaviin jäjelläoleviin) oikeastaan hätäilmoitukset?
