### ISSUE TITLE
paprika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8136]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

paprika 

#### Ehdotettu termi ruotsiksi   

paprika 

#### Ehdotettu termi englanniksi   

bell pepper 

#### Vaihtoehtoiset termit ja ilmaisut   

ruokapaprika, vihannespaprika, Capsicum annuum 

#### Ehdotettu yläkäsite YSOssa (LT)   

[paprikat](http://www.yso.fi/onto/yso/p7255) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Paprika 
SAO : paprika 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Tarkoitusta täsmentävä selite   

Viittaa lajiin 

#### Perustelut ehdotukselle   

Sanastossa on nyt vain paprikat sukuna. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paprikasta 

**Termiehdotus Fintossa:** [paprika](http://finto.fi/yse/fi/page/Y508136)

**Comment by mirmaid** [comment]
Kassussa päätermi on _vihannespaprika_, voisiko olla samoin YSOssa?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa paprika (laji), ohjaustermeiksi vihannespaprika ja ruokapaprika.
Muutetaan paprikat muotoon paprikat (suku).

**Comment by mariaforsen** [comment]
Sv. paprika (art) ET spanskpeppar
-paprikor > spanskpepparsläktet
