### ISSUE TITLE
paloilmoituslaitteistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8138]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[paloilmoituslaitteistot](http://www.yso.fi/onto/ysa/Y122032) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

joko muutos tai lisäys ilmoitinlaitteet 

#### Ehdottajan organisaatio   

finto-posti / VNK 

#### Perustelut ehdotukselle   

Hätäkeskuslaitos tuottaa kansalaisille ilmoitinlaitepalvelun, johon kuuluvat niin rikosilmoitin- kuin paloilmoitinlaitteet, kutsutaan virallisesti ilmoitinlaitteiksi (nämä siis valtion tuottamat palvelut HÄKE:n kautta, ei yksityisten firmojen)

**Comment by tpalonen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8134
