### ISSUE TITLE
hätäpuhelimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8139]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hätäpuhelimet](http://www.yso.fi/onto/ysa/Y101763) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

muutetaan muotoon hätänumero 

#### Perustelut ehdotukselle   

Nykysin ei puhuta hätäpuhelimista, koska hätäilmoituksen voi tehdä usealla eri tavalla, jolloin puhutaan virallisesti hätänumerosta (esim. tekstiviesti tai 112 Suomi sovelluksen kautta soitettu puhelu) 

#### Ehdottajan organisaatio   

finto-posti / VNK

**Comment by tpalonen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8135
