### ISSUE TITLE
Valtimon Pyhän Kolminaisuuden kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8140]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Valtimon Pyhän Kolminaisuuden kirkko 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Valtimon Pyhän Kolminaisuuden Kirkko 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Valtimon Pyhän Kolminaisuuden kirkko](http://finto.fi/yse/fi/page/Y508140)

**Comment by mariaforsen** [comment]
Sv. Valtimo heliga treenighetskyrka? Valtimon Pyhän Kolminaisuuden kirkko?

**Comment by LeKorsu** [comment]
Edellä on termiehdotus jossa samannimisen kirkon paikkakunta on sulkeissa: Pyhän kolminaisuuden kirkko (Lahti) ja nyt on Valtimon Pyhän Kolminaisuuden kirkko. Pitäisikö näissä olla yhtenäistä johdonmukaisuutta eli jompikumpi muoto molempiin?

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Valtimon Pyhän Kolminaisuuden kirkko, koska seurakunta käyttää tätä muotoa. Ohjaustermiksi Pyhän Kolminaisuuden kirkko (Valtimo).
