### ISSUE TITLE
Pyhän Kolminaisuuden Kirkko (Lahti)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8141]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän Kolminaisuuden Kirkko (Lahti) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lahden Pyhän kolminaisuuden kirkko saanut uuden ilmeen 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Pyhän Kolminaisuuden Kirkko (Lahti)](http://finto.fi/yse/fi/page/Y508141)

**Comment by mariaforsen** [comment]
Sv. Heliga Treenighetens kyrka (Lahtis)
