### ISSUE TITLE
Laajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8142]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Laajoki](http://www.yso.fi/onto/ysa/Y110961) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan tarkennusta 

#### Perustelut ehdotukselle   

Mihin tämä viittaa, kylään? Sanastossa on myös Laajoki (Mynämäki). Sekä kylä että joki ovat molemmat Mynämäellä. 
https://kartta.paikkatietoikkuna.fi/?lang=fi

**Comment by mirmaid** [comment]
Vastaava kuin https://github.com/Finto-ehdotus/YSE/issues/8144, mutta joille ei ole annettu tarkenteita. Toisaalta joki-kunta/kaupunki -pareissa on käytetty tyyppitarkenteita (esim. Isojoki). Laajoki on joki Mynämäen ja Pöytyän kuntien alueella.

**Comment by ilona-x** [comment]
Joo, näitä tulee vastaan säännöllisesti. YSAssa/Voyagerissa muodon perusteella pystyi päättelemään, onko kyseessä kylä `151 ‡a  kunta ‡z "kylän nimi"` vai joki `151 ‡a "joen nimi" `, mutta nyt Fintossa ja Asterissa nämä ovat kyllä tosiaan hämmentäviä. YSA-aikana joille ja järville taidettiin antaa tarkenne vain, jos sanastossa oli useampi samanniminen.

**Comment by YSO-kokous** [comment]
Päätös tämän käsitteen kohdalla vaatii muutoksia muihinkin käsitteisiin. Kerätään vastaavia esimerkkejä ja pohditaan päätöstä näiden valossa. Esim. Tarvasjoki.
Vrt. myös https://github.com/Finto-ehdotus/YSE/issues/8144

**Comment by ilona-x** [comment]
Näitä tehty nyt kahdella tapaa, kummassakaan tapauksessa Suomessa ei ole muita samannimisiä jokia/järviä/kyliä) :

1) kylä: Tarvasjoki **(Lieto)**
joki: Tarvasjoki **(joki)**
entinen kunta: Tarvasjoki **(kunta)**

2) kylä: Tottijärvi **(Nokia : kylä)**
järvi: Tottijärvi **(Nokia : järvi)**
entinen kunta: **Tottijärvi (kunta)**

Nykylinjausten mukaan vaihtoehto 1) on tapa, jolla ohjataan tekemään, eli joelle riittäisi tarkenteeksi pelkkä, joki, kun muita samannimisiä jokia ei ole Suomessa ja kylille puolestaan on sovittu tarkenteeksi kunta. Mutta onko label Tarvasjoki (Lieto) riittävän selkeä kertomaan että kyse kylästä eikä joesta?

Tapa 2 puolestaan on malliltaan sama kuin jos Suomessa olisi useampia Tottirjävi-nimisiä järviä, mutta näitä siis ei ole, eli tämä on nykylinjausten mukaan väärin. Tässä tapauksessa labelit ovat kuitenkin yksiselitteiset, eikä järvestä tulisi vahingossakaan käytettyä kylän käsitettä.

Miten ohjeistetaan tekemään tämänkaltaiset jatkossa?

**Comment by ilona-x** [comment]
Lisäksi YSO-paikoissa on myös tapauksia, joissa järvellä ei ole tarkennetta, vaikka Suomessa on useampia samannimisiä järviä. 
Esim:  Hiisijärviä on muuallakin kuin Ristijärvellä, mutta Ristijärven Hiisijärvi on ainoa YSO-paikoissa oleva Hiisijärvi.
järvi: Hiisijärvi  http://www.yso.fi/onto/yso/p111469
kylä: Hiisijärvi (Ristijärvi)

**Comment by YSO-kokous** [comment]
Päätös ks. https://github.com/Finto-ehdotus/YSE/issues/8144

**Comment by mariaforsen** [comment]
Pitää toteuttaa myös tämän osalta, sekä korjata Laajoki (Mynämäki)-termin huomautus

**Comment by ilona-x** [comment]
Tarkenteet muutettu ja huomautukset korjattu.
Laajoki (joki)
Laajoki (Mynämäki : kylä)

**Comment by mirmaid** [comment]
Linjauksissa nyt siis molemmille tulee sekä tyyppitarkenne, että paikkatarkenne. Näin ei kuitenkaan ole aina tehty. Halutaanko me ihan varmasti että paikkatarkenne lisätään myös silloin, kun muita samannimisiä vesistöjä ei ole? Esim. Tarvasjoki ja tämä Laajoki.

**Comment by mirmaid** [comment]
Tarkennetaan tätä linjauksiin, tyyppitarkenne riittää, kun muita samannimisiä vesistöjä ei ole.
