### ISSUE TITLE
Degerby

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8143]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Degerby](http://www.yso.fi/onto/ysa/Y110168) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan 

#### Perustelut ehdotukselle   

Sanastossa myös Degerby (Inkoo)

**Comment by mirmaid** [comment]
Degerby on siis entisen itsenäisen kunnan nimi.

**Comment by mirmaid** [comment]
Degerby (kunta)

**Comment by YSO-kokous** [comment]
Ks. https://github.com/Finto-ehdotus/YSE/issues/7858

**Comment by mirmaid** [comment]
Huom. Lisätään edeltäjä-seuraaja.
