### ISSUE TITLE
Syvänsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8144]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Syvänsi](http://www.yso.fi/onto/ysa/Y122770) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Syvänsi (Pieksämäki)

**Comment by mirmaid** [comment]
Eli oikeastaan molemmat pitäisi korjata >
Syvänsi (Pieksämäki : järvi)
Syvänsi (Pieksämäki : kylä)

Tosin Suomessa ei ole toista Syvänsi-nimistä järveä, joten pelkkä tarkenne (järvi) riittäisi erottamaan kylästä. Vrt. linjaukset.

**Comment by YSO-kokous** [comment]
Tehdään seuraavasti: Syvänsi (Pieksämäki : järvi) ja Syvänsi (Pieksämäki : kylä).
Laajoki ja Tarvasjoki ynnä vastaavat vastaavasti.
