### ISSUE TITLE
bevasitsumabi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8145]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bevasitsumabi 

#### Ehdotettu termi englanniksi   

Bevacizumab 

#### Ehdotettu termi ruotsiksi   

Bevacizumab 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Bevasitsumabi 
FinMeSH : <http://www.yso.fi/onto/mesh/D000068258> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa, Melinda x 10 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Metastatic breast cancer : efficacy of bevacizumab-based chemotherapy and prognostic factors 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [bevasitsumabi](http://finto.fi/yse/fi/page/Y508145)

**Comment by mariaforsen** [comment]
Sv. ET Avastin
