### ISSUE TITLE
seurat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8147]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seurat](http://www.yso.fi/onto/ysa/Y104310) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "hartauskokoukset" ja "konventikkelit" 

#### Perustelut ehdotukselle   

Seurat tunnetaan myös näillä nimityksillä; jälkimmäinen keskeinen varsinkin konventikkeliplakaatin historiallisen merkitykselliseen takia. Määritelmästä ks. esim. http://runeberg.org/tieto/4/0697.html ja https://fi.wikipedia.org/wiki/Pietismi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Melindassa käytetty näköjään paljon myös muussa merkityksessä kuin "uskonnolliset tilaisuudet". metsästysseurat, sukututkimusseurat, voimisteluseurat jne. Pitäisikö päätermi vaihtaa sulkutarkenteelliseksi kun nyt ohjausterminä on seurat (uskonnolliset tilaisuudet)?

**Comment by mariaforsen** [comment]
ALLFO bönemöten=seurat, joten ruotsiksi on ennestäänkin ollut selvää että mistään muusta ei voi käyttää. Tärkeää siis että suomeksikin on selvää, muuten tulee vakavia virheitä asiasanoitukseen. Ryhmä onkin 53.

**Comment by YSO-kokous** [comment]
Muutetaan päätermi muotoon "seurat (uskonnolliset tilaisuudet)".
Hyväksytään ehdotetut ohjaustermit.
