### ISSUE TITLE
valkohai

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8148]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valkohai 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [valkohai](http://finto.fi/yse/fi/page/Y508148)

**Comment by mariaforsen** [comment]
Sv. vithaj

**Comment by tpalonen** [comment]
Fun fact: "The great white shark was originally considered the apex predator of the ocean; however, the killer whale has proved to be a predator of the shark" 
https://en.wikipedia.org/wiki/Apex_predator#/media/File:Comparison_of_size_of_orca_and_great_white_shark.svg
https://en.wikipedia.org/wiki/Apex_predator
