### ISSUE TITLE
Partalan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8149]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Partalan kartano 

#### Vaihtoehtoiset termit ja ilmaisut   

Partalan kuninkaankartano 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Partalan kartano](http://finto.fi/yse/fi/page/Y508149)

**Comment by mariaforsen** [comment]
Sv. Partala kungsgård ET Partala gård
