### ISSUE TITLE
unikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8150]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[unikirjat](http://www.yso.fi/onto/ysa/Y208713) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään unikirat myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Varsinaiset unikirjat olisi hyvä voida erottaa unikirjoja käsittelevistä tutkimuksista yms.

**Comment by AuHo22** [comment]
Itselleni tuli mieleen lasten kirjatkin, joissa käsitellään nukkumaan menemistä / nukuttamista: 
https://otava.fi/kirjat/hurjan-hauska-unikirja/
Mutta en harrasta itse unien tulkintaa eli jollekulle tämä voi olla hyvinkin selkeä asia?

**Comment by mirmaid** [comment]
Ei hyväksytty / SLM. Pitäisikö poistaa myös YSOsta?

**Comment by AuHo22** [comment]
15.92 Unikirjat -> Ennusunet Unien tulkinta _okkultismin_ kannalta (selite)

**Comment by krinay** [comment]
Harmillista, ettei termiä hyväksytty SLM-sanastoon. Sille olisi käyttöä nimenomaan genreterminä. On unikirjoista tutkimuskirjallisuuttakin, mutta tarve asiasanalle on varmasti vähäisempi.  
https://melinda.kansalliskirjasto.fi/byid/001383665
https://melinda.kansalliskirjasto.fi/byid/013184014   

Mauri Kunnas muuten leikkii em. _Hurjan hauskassa unikirjassa_ nimenomaan unikirjoilla, samaan tapaan kuin on kirjoittanut _Koirien Kalevalan_ ja  _Seitsemän koiraveljestä_.

**Comment by mariaforsen** [comment]
En kannata poistoa YSOsta! Käytetty Melindassa myös nimenomaan aineistosta jossa tutkitaan unikirjoja. Esim: 
-Den nordiska drömboken 1641-1991 : traditionslinjer och nyskapande
-Egyptistä Pohjolan perukoille : vanhat suomalaiset unikirjat
-Drömmar och kultur : drömböcker och drömtolkning / Annikki Kaivola-Bregenhøj och Ulf Palmenfelt
-Reading Russian fortunes : print culture, gender, and divination in Russia from 1765 / Faith Wigzell.

**Comment by krinay** [comment]
Samaa mieltä, kyllä YSO-termillekin on tarvetta. Mutta jotta unikirjojen tutkijat löytäisivät tutkimusaineistonsa, olisi tarvetta myös SLM-termille.

**Comment by AuHo22** [comment]
Näin yleissanastossa jälleen eri kirjastosektoreiden tarpeiden yhteensovittaminen voi osoittautua vaikeaksi, eli lastenkirjallisuuden unikirjojen (siinäkin kyse unen saamisesta) tai nukahtamiseen / unihäiriöiden hoitoon  tarkoitettujen unikirjojen merkitysten erottaminen  tutkimuskäytöstä - esim.
https://www.eranova.fi/category/159/unikirjat
Tatun ja Patun outo unikirja / Lasten unikirja : hyvää yötä! jne.

Monelle taholle harova termi tarvitsisi jo tarkenteita - ehkä sen takia SLM-kokous luopui termistä - YSO-terminä asiaa voi tarkentaa muiden asiasanojen avulla, SLM-terminä tämä ei onnistu.
Melindasta löysin uusimman osuman (osasinkohan hakea oikein?) haulla unikirjat vuodelta 2013 ; HelMetistä löysin 2 osumaa, yhden venäjänkielisen 2010-luvulta ja toisen suomenkielisen 40-luvulta - tämäntyyppisen käytön sijaan unihäiriöiden tutkimus ja hoito alkaa olla terveydenhoidon valtavirtaa nykyisin (ei unien tulkinta), ja voi mielestäni miettiä, mikä olisi termin järkevää nykykäyttöä, kun historialliset kontekstit muuttuvat?

**Comment by mirmaid** [comment]
Sanastossa on myös _unien tulkinta_, joka varmasti tulee - tai pitäisi tulla - asiasanaksi jokaiseen unikirjaan ja unikirjoja tutkivaan kirjaan. Jos lisäksi tarvitaan unikirjat, sille voisi olla tarkenteena (unien tulkinta), mutta onhan se ehkä vähän päällekkäistä kuvailla _unien tulkinta_ & _unikirjat (unien tulkinta)_.

**Comment by krinay** [comment]
Muutama kommentti vielä, vaikka tyydyn tietenkin siihenkin ratkaisuun, että termi poistetaan. Ilmankin varmasti pärjätään.

Unikirjat ovat hyvin vanha kirjallisuuden laji, josta esimerkiksi historian- ja kulttuurintutkijat ovat viime vuosina kiinnostuneet. 
Lyhyt esittely lajin varhaisesta historiasta: http://www.glossa.fi/wp/?page_id=123.

YSOon termi on ilmeisesti tullut vasta vuonna 2016, mikä kai osaltaan selittää Helmet-osumien pientä määrää. Termeillä _unet_ ja _unien tulkinta_ löytyy Helmetistä paljon unikirjojakin.

Minusta nimenomaan SLM-terminä unikirjat olisi varsin yksiselitteinen. En näe kovin suurta vaaraa sille, että uni-aiheisia lastenkirjoja tai unihäiriöiden tutkimusta pidettäisiin genrenä.

**Comment by mirmaid** [comment]
Hyväksytty/SLM. Lisätään määritelmä.
