### ISSUE TITLE
Kirjola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8151]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kirjola](http://www.yso.fi/onto/ysa/Y108369) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan? 

#### Perustelut ehdotukselle   

On myös samannimisiä kyliä, https://fi.wikipedia.org/wiki/Kirjola ja samannimisiä taloja kuudella eri paikkakunnalla (ks. Paikkatietoikkuna)

**Comment by mirmaid** [comment]
Kirjolan kartano (Halikko)?

**Comment by mariaforsen** [comment]
Kirjola on näköjään käytetty enemmän Johanneksen Kirjolan kartanosta, tarvitaan varmaan molempia.

**Comment by mirmaid** [comment]
^ Ok.

**Comment by YSO-kokous** [comment]
Kirjola muutetaan Kirjolan kartano (Halikko). Lisätään sanastoon Johanneksen Kirjolan kartano parhaalla mahdollisella termimuodolla varustettuna.
