### ISSUE TITLE
sanantunnistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8152]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sanantunnistus 

#### Ehdotettu termi englanniksi   

Word recognition 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tunnistaminen](http://www.yso.fi/onto/yso/p8265) 

#### Vastaava käsite muussa sanastossa   

TSR : <http://www.yso.fi/onto/tsr/p9278> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85148114> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Processing of subword information in the human brain 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa, Melinda x 8 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sanantunnistus](http://finto.fi/yse/fi/page/Y508152)

**Comment by mirmaid** [comment]
Ajattelin ensin, että tämä liittyy tekstintunnistukseen ja Googlella jonkin verran käytettykin tietotekniikan yhteydessä. Onko sekaantumisen vaaraa? Voi kyllä esim. lisätä sanantunnistus (tietotekniikka) KÄ tekstintunnistus.

**Comment by tpalonen** [comment]
sanantunnistus (kognitio)?

**Comment by YSO-kokous** [comment]
Käsitellään hahmontunnistus, kasvontunnistus, sanantunnistus ja mahdollisesti muut vastaavat yhteisesti. Pitääkö käsitteet jakaa atk/ihmis-merkityksiin vai mitä tehdään?

**Comment by ilona-x** [comment]
LCSH:ssa näköjään kasvontunnistus jaoteltu:
**Face perception**
Variants
    Face recognition (Psychology)
    Facial perception
    Facial recognition (Psychology)
    Recognition, Facial (Psychology)

**Human face recognition (Computer science)**
Variants
    Face recognition, Human (Computer science)
    Facial pattern recognition (Computer science)

Mutta hahmontunnistus on näin eli LT-ST-suhde:

**Pattern perception**
Narrower Terms
    **Optical pattern recognition** (jonka alakäsite Human face recognition (Computer science))

Itse en ole innokas jakamaan näitä kahtia.

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8190

**Comment by mariaforsen** [comment]
Sv. 
-ansiktsigenkänning (kognition) https://www.psykologiguiden.se/psykologilexikon/?Lookup=ansiktsigenk%C3%A4nning
-ansiktsigenkänning (teknik)
-ordigenkänning (kognition) ?

**Comment by ilona-x** [comment]
Jos erotetaan "ihmismerkitys" näistä eri tunnistamisista niin liittyvätkö sitten havaitsemiseen (eng perception ). Esimerkiksi tuo pattern perception on LCSHssa perception-käsitteen alakäsite.

YSOssa hierarkia nyt näin:

**havaitseminen**
    sosiaalinen havaitseminen
    spatiaalinen havaitseminen


**tunnistaminen**
    etätunnistus
    hahmontunnistus (jaettava?)
    identifiointi
    kasvontunnistus (jaettava?)
    liikkeentunnistus (jaettava?)
    nimien tunnistus
    puheentunnistus (jaettava?)
    tekstintunnistus

**Comment by mirmaid** [comment]
Kasvontunnistus (psykologia) ja kasvontunnistus (tietotekniikka)?

Liikkeentunnistusta käytetty Melindassa vain tekniikan yhteydessä, lukuunottamatta tätä https://jyx.jyu.fi/handle/123456789/59909#, mutta onkohan tämä oikeastaan liikkeentunnistusta? 

Puheentunnistus/puheen tunnistaminen/puheen havaitseminen - tuntuu olevan varsin vähän käytetty suomeksi muuten kuin tekniikan yhteydessä. 

Sanantunnistus (psykologia)?
