### ISSUE TITLE
kiipeilytelineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8153]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kiipeilytelineet 

#### Perustelut ehdotukselle   

Kaupunkivalokuvia luetteloidessani tulee jatkuvasti vastaan kuvia kerrostalopihojen leikkipaikoista, joihin liittyviä termejä puuttuu Fintosta useita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

valokuvat 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [kiipeilytelineet](http://finto.fi/yse/fi/page/Y508153)

**Comment by mirmaid** [comment]
Melindassa kolme kertaa monikossa ja kolme kertaa yksikössä.

**Comment by mariaforsen** [comment]
Sv. klätterställningar

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
