### ISSUE TITLE
hiekkalaatikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8154]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hiekkalaatikot 

#### Perustelut ehdotukselle   

Kaupunkivalokuvia luetteloidessani tulee jatkuvasti vastaan kuvia kerrostalopihojen leikkipaikoista, joihin liittyviä termejä puuttuu Fintosta useita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

valokuvat 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [hiekkalaatikot](http://finto.fi/yse/fi/page/Y508154)

**Comment by ilona-x** [comment]
Tarvitseeko tarkenteen? 🐱 

Kielitoimiston sanakirja:
hiekka­laatikko
Lapset leikkivät hiekkalaatikossa.
Kissan hiekkalaatikko.

**Comment by mirmaid** [comment]
Melindassa 8 kertaa monikossa, kolme kertaa yksikössä. Ei kissojen hiekkalaatikoista :slightly_smiling_face:.

**Comment by mariaforsen** [comment]
Sv. sandlådor

**Comment by tpalonen** [comment]
RT leikkipuistot, leikkipaikat?

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
