### ISSUE TITLE
liukumäet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8155]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

liukumäet 

#### Perustelut ehdotukselle   

Kaupunkivalokuvia luetteloidessani tulee jatkuvasti vastaan kuvia kerrostalopihojen leikkipaikoista, joihin liittyviä termejä puuttuu Fintosta useita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

valokuvat 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [liukumäet](http://finto.fi/yse/fi/page/Y508155)

**Comment by ilona-x** [comment]
Ehdotettu myös aiemmin: https://github.com/Finto-ehdotus/YSE/issues/2746

**Comment by mirmaid** [comment]
Hyväksyttiin KAUNOon. Käytetty kolme kertaa Melindassa (& kerran yksikössä), kerran kelkkamäestä: https://melinda.kansalliskirjasto.fi/byid/014321902.

**Comment by mariaforsen** [comment]
Sv.  rutschbanor ET rutschkanor

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
