### ISSUE TITLE
polkuautot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8156]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

polkuautot 

#### Perustelut ehdotukselle   

Kaupunkivalokuvia luetteloidessani tulee jatkuvasti vastaan kuvia kerrostalopihojen leikkipaikoista, joihin liittyviä termejä puuttuu Fintosta useita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

valokuvat 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [polkuautot](http://finto.fi/yse/fi/page/Y508156)

**Comment by mirmaid** [comment]
Melindassa 4 kertaa monikossa, kerran yksikössä. Jännä kyllä polkuautot-käsitettä ei löydy mistään Finton sanastosta, mutta JUPOsta löytyy _polkuautokoulut_ :smile:.

**Comment by mariaforsen** [comment]
Sv. trampbilar

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
