### ISSUE TITLE
stemmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8157]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

stemmat 

#### Ehdotettu termi englanniksi   

Parts (Music) 

#### Ehdotettu termi ruotsiksi   

stämmor 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026986> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarvitaan SLM-sanastoon nuottiaineiston muodon kuvailuun. 

#### Tarkoitusta täsmentävä selite   

Sellaisen nuottiaineiston muoto, joka sisältää nuotit yhdelle tai useammalle, mutta ei kaikille esittäjille (esimerkiksi viulukonserton viulustemma tai orkesteriteoksen harppustemma). (Metatietosanasto) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uniarts.finna.fi/Record/arsca.223575 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [stemmat](http://finto.fi/yse/fi/page/Y508157)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by YSO-kokous** [comment]
Otetaan stemmat myös YSOon.

**Comment by tpalonen** [comment]
Käsite rajattaneen/määriteltäneen YSOssa eri tavalla kuin SLM:ssä? Kysymys liittyy yläkäsitteeseen ja määritelmään. SLM:ssä stemma on nuottijulkaisu ja määritelmä on "Sellaisen nuottiaineiston muoto, joka sisältää nuotit yhdelle tai useammalle, mutta ei kaikille esittäjille (esimerkiksi viulukonserton viulustemma tai orkesteriteoksen harppustemma)." YSOn puolella kuitenkin olisi varmasti tarvetta käyttää käsitettä laajemmin. Esim. pop-puolella stemmassa ei ole lainkaan olennaista nuotintaminen, vaan stemma on tietyn soittajan tai laulajan osuus sävellyksessä. Tyypillisesti stemmaa ei ole nuotinnettu, vaan se on muistinvarainen, soittajan vapaasti muunneltavissa tai esityshetkessä improvisoitu tms.

**Comment by MUUSA-kokous** [comment]
Kannatetaan edellistä kommenttia.

**Comment by MUUSA-kokous** [comment]
Määritelmäehdotus tpalosen kommentin perusteella: "Tietyn soittajan tai laulajan osuus teoksessa".
