### ISSUE TITLE
partituurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8158]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[partituurit](http://www.yso.fi/onto/ysa/Y103887) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Tarvitaan nuottiaineiston muodon kuvailuun. 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta, ks. https://github.com/Finto-ehdotus/YSE/issues/7581.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
