### ISSUE TITLE
pienoispartituurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8159]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pienoispartituurit](http://www.yso.fi/onto/ysa/Y185564) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Tarvitaan nuottiaineiston muodon kuvailuun. 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
Määritelmä:
Pienennetyssä muodossa julkaistu partituuri, jota ei ole ensisijaisesti tarkoitettu esityskäyttöön.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
