### ISSUE TITLE
pianopartituurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8160]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pianopartituurit](http://www.yso.fi/onto/ysa/Y214610) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Tarvitaan nuottiaineiston muodon kuvailuun. 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
Määritelmä:
Partituuri, jossa säestävän orkesterin tai yhtyeen osuus on korvattu pianosäestyksellä.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
