### ISSUE TITLE
soolonuotit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8161]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

soolonuotit 

#### Ehdotettu termi ruotsiksi   

solostämmor 

#### Tarkoitusta täsmentävä selite   

Nuottiaineisto, joka sisältää yhdelle soittimelle tai yhdelle esittäjälle tarkoitetun musiikkiteoksen nuotinnoksen (esimerkiksi Beethovenin Für Elise (pianolle), Messiaenin Le banquet céleste (uruille), Xenakiksen Pléïades (lyömäsoittimille) ja Debussyn Syrinx (huilulle)) (Metatietosanasto) 

#### Perustelut ehdotukselle   

SLM-sanastoon. Tarvitaan nuottiaineiston muodon kuvailuun. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uniarts.finna.fi/Record/arsca.57197 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [soolonuotit](http://finto.fi/yse/fi/page/Y508161)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
Määritelmästä esimerkit pois.

**Comment by mirmaid** [comment]
Hyväksytty/SLM, ei tässä vaiheessa ehdolle YSOon.

**Comment by mariaforsen** [comment]
Sv. solonoter ET solostämmor
