### ISSUE TITLE
kuoropartituurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8162]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuoropartituurit 

#### Ehdotettu termi ruotsiksi   

körpartitur 

#### Ehdotettu termi englanniksi   

chorus scores 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026715> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

Kuoron harjoituskäyttöön tarkoitettu, kuorolle ja soittimille, mahdollisesti myös solistisille lauluäänille sävelletyn teoksen partituuri, jossa kuoroäänet on merkitty omille viivastoilleen, ja josta soitinsäestys on joko jätetty kokonaan pois tai sisällytetty osittain ja pelkistetysti kosketinsoittimelle tai muille sointusoittimille sovitettuna. Jos soitinsäestys on merkitty täydellisenä, käytetään termiä partituuri. Jos teos on alun perin sävelletty säestyksettömälle kuorolle, käytetään termiä partituuri. (Metatietosanasto) 

#### Perustelut ehdotukselle   

SLM-sanastoon. Tarvitaan nuottiaineiston muodon kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uniarts.finna.fi/Record/arsca.263904 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [kuoropartituurit](http://finto.fi/yse/fi/page/Y508162)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM, ei tässä vaiheessa ehdolle YSOon.

**Comment by mirmaid** [comment]
Pitäisikö sittenkin ottaa YSOon, kun on myös muut partituurin alakäsitteet? Jos ei oteta, YSOsta on syytä poistaa pianopartituurit-käsitteen huomautus.

**Comment by MUUSA-kokous** [comment]
Ei kannateta lisäämistä YSOon, koska ei löydy aiheesta kirjoitettua kirjallisuutta. Poistetaan huomautus pianopartituureista.

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.
