### ISSUE TITLE
eurytmia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8166]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[eurytmia](http://www.yso.fi/onto/ysa/Y95141) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "eurytmiataide" sekä tutkitaan LT-suhteen oikeellisuus 

#### Perustelut ehdotukselle   

"Eurythmy is an expressive movement art [- -]. Primarily a performance art, it is also used in education, especially in Waldorf schools, and – as part of anthroposophic medicine – for claimed therapeutic purposes." (https://en.wikipedia.org/wiki/Eurythmy)
"Eurytmia [- -] on liiketaidemuoto" (https://fi.wikipedia.org/wiki/Eurytmia)
"Eurytmia on liikuntataiteen muoto [- -]. Eurytmia on myös näyttämötaidetta ja siitä on kehitetty terapeuttinen muoto." (https://snellman-korkeakoulu.fi/koulutus/eurytmiataiteen-opinnot/) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
LT taiteenlajit

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
