### ISSUE TITLE
peristyylipuutarhat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8167]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

peristyylipuutarhat 

#### Ehdotettu termi englanniksi   

peristyle gardens 

#### Vaihtoehtoiset termit ja ilmaisut   

peristyyli 

#### Perustelut ehdotukselle   

Pylväiden ympäröimä puutarha. Ehkä voisi ottaa pelkän peristyylin, jos olisi laajemmin käyttöä
https://fi.wikipedia.org/wiki/Peristyyli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-4432-4 

**Termiehdotus Fintossa:** [peristyylipuutarhat](http://finto.fi/yse/fi/page/Y508167)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Hyvin vähän googlessa muodossa peristyylipuutarha/t, mieluummin muodossa peristyyli. Ei ollut aina varsinaisesti puutarha. 
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/peristyl

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa peristyylit, ohjaustermiksi peristyylipuutarhat.

**Comment by mariaforsen** [comment]
Sv. peristyler ET peristylträdgårdar
