### ISSUE TITLE
kenttä-äänitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8168]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kenttä-äänitykset 

#### Ehdotettu termi englanniksi   

field recordings 

#### Vaihtoehtoiset termit ja ilmaisut   

kenttä-äänitteet 
kenttätallenteet 
kenttänauhoitukset 
äänitykset (kenttä-äänitteet/-äänitykset) 
äänitteet (kenttä-äänitteet/-äänitykset) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tallenteet](http://www.yso.fi/onto/yso/p1999) 

#### Assosiatiiviset (RT)   

[perinteenkeruu](http://www.yso.fi/onto/yso/p28620) 
[äänittäminen](http://www.yso.fi/onto/yso/p1139) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh98004808> 
Wikidata : https://www.wikidata.org/wiki/Q360982 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

National phonography : field recording, sound archiving, and producing the nation in music / Tom Western. 

#### Tarkoitusta täsmentävä selite   

Käytettävä termi voi olla myös kenttä-äänitteet. Riippuu käsitteen rajauksesta. 

#### Perustelut ehdotukselle   

Käsite ja tarve sille lienee selkeä. Olennainen käsite esim. etnomusikologiassa. Muusa-kokous kannattaa käsitteen ottamista sanastoon. Mikäli käsite päätetään ottaa, pitää vielä keskustella rajaamisesta, sillä käsite on monialainen. Mihin käsite rajataan? Julkaistuihin äänitteisiin? Taltioituihin tuotoksiin yleisemmin? Pelkkään äänittämiseen vai myös videointiin (vrt. LCSH)? Musiikin tallentamiseen? Minkä tahansa äänen (ja kuvan) tallentamiseen? Wikipedian mukaan kenttä-äänityksiä tehdään mm. etnomusikologian ja bioakustiikan alalla sekä osana taiteellista työskentelyä (musique concréte, kuunnelmat). Googlen mukaan termi on yleinen myös elokuvatuotannossa. Samaa käsitettä voisi varmasti soveltaa näihin kaikkiin, ellei haluta rajata tarkemmin. Sivuhuomio: esim. folkloristiikassa ja kielitieteessä perinteen ja murrenäytteiden tallentaminen on yleistä, mutta lyhyen silmäyksen perusteella näillä aloilla ei puhuta kenttä-äänityksistä, vaan yleisemmin äänitteistä, äänityksistä ja nauhoitteista (Kotus, SKS).

LCSHn määritelmä: "recordings of sounds or images made outside a controlled studio environment or professional performance venue that are generally unedited and typically made with portable equipment." 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [kenttä-äänitykset](http://finto.fi/yse/fi/page/Y508168)

**Comment by MUUSA-kokous** [comment]
Muusa ehdottaa termiä muodossa _kenttätallenteet_. _Kenttä-äänitykset_ ohjaustermiksi sille. Määritelmät tulevat myöhemmin.

Myös SLM:ään.

**Comment by tpalonen** [comment]
Taustaa: Muusa-kokouksessa pohdittiin, että kenttätallenteet olisi kenttä-äänityksiä monikäyttöisempi. Määritelmään voi tarvittaessa hakea inspiraatiota ehdotuksessa mainitusta LCSH-linkistä.

**Comment by mariaforsen** [comment]
Sv. fältinspelningar ET fältupptagningar

**Comment by mirmaid** [comment]
_Mikäli käsite päätetään ottaa, pitää vielä keskustella rajaamisesta, sillä käsite on monialainen._ - Eikö tämä keskustelu olisi hyvä käydä _ennen_ kuin käsite päätetään ottaa? Varsinkin, jos käyttö vaihtelee eri tieteenaloilla, vrt. ehdotuksen sivuhuomio: _esim. folkloristiikassa ja kielitieteessä perinteen ja murrenäytteiden tallentaminen on yleistä, mutta lyhyen silmäyksen perusteella näillä aloilla ei puhuta kenttä-äänityksistä, vaan yleisemmin äänitteistä, äänityksistä ja nauhoitteista_.

**Comment by tpalonen** [comment]
No sikäli Muusa jo otti kantaa rajaukseen, että kun termi olisi kenttätallenteet niin käsite sisältäisi sekä ääni- että kuvatallentamisen. Ihan käytännön kannalta itse suosittaisin, että käsite olisi riittävän monikäyttöinen ja monialainen ja sisältäisi musiikin tallentamisen lisäksi myös muunlaisen taltiomisen.

**Comment by krinay** [comment]
Tähän asti on varmaan käytetty erilaisia yhdistelmiä: kenttätyö + tallenteet, kenttätyö + äänitteet, kenttätyö + äänittäminen tms., mutta kenttätallenteet on varmaan ihan hyvä termi, jos sitä ei rajata tiettyyn käyttöön.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa kenttätallenteet, ohjaustermiksi kenttä-äänitykset.

**Comment by mirmaid** [comment]
Kenttätallenteet, ohjaustermiksi kenttä-äänitykset / SLM.

**Comment by mirmaid** [comment]
Määritelmä puuttuu vielä.

**Comment by jaskaj** [comment]
Ehdotus määritelmäksi:

Audiovisuaalisen tallentamisen laji jossa tallentajan vaikutus kohteeseen on minimaalinen ja joka pyrkii tallentamaan kohteen tämän autenttisessa ympäristössä.

**Comment by tpalonen** [comment]
Muuttaisin määritelmää hieman. Käsitehän on _kenttätallenteet_ ja ehdotettu määritelmä sopisi paremmin, jos käsite olisi _kenttätallentaminen_ tms. Toisaalta, jos käsitettä käytetään myös esim. elokuva-alan tai kuunnelmien yhteydessä, mikä kaiketi olisi suotavaa, niin en tiedä onko ehdotettu määritelmä liian rajaava: autenttisuus ja minimaalinen vaikuttaminen ei ehkä noissa konteksteissa olennaista. Itse näkisin, että olennaista on, että ollaan tallentamassa studio-olosuhteiden ulkopuolella. Wikipedian audiotallentamiseen liittyvässä artikkelissa näin määritelläänkin: "Field recording is the term used for an audio recording produced outside a recording studio." (https://en.wikipedia.org/wiki/Field_recording)

**Comment by jaskaj** [comment]
Uusi ehdotus määritelmäksi:

Muualla kuin studiossa tai muussa kontrolloidussa esitystilanteessa tehdyt audiovisuaaliset tallenteet.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa määritelmäehdotusta.

**Comment by AuHo22** [comment]
audiovisuaalinen = kuuloon ja näköön perustuva / sekä auditiivisia että visuaalisia elementtejä sisältävä
Tämänhetkiset ohjaustermit YSOssa: 
    kenttänauhoitukset
    kenttä-äänitteet
    kenttä-äänitykset
    äänitteet (kenttätallenteet)
    äänitykset (kenttätallenteet)

Eli ei välttämättä ole audiovisuaalinen vaan voi olla pelkkä äänite. Onko ristiriitaa ehdotetun huomautuksen kanssa tai po. ?
"Muualla kuin studiossa tai muussa kontrolloidussa esitystilanteessa tehdyt audiovisuaaliset tallenteet tai kenttä-äänitykset."
tms. Voiko olla myös "kenttäkuvausta" ilman ääntä, esim. historiallisissa arkistofilmeissä jonkinlaista havainnoivaa etnografista dokumenttielokuvausta ilman ääntä?

**Comment by jaskaj** [comment]
Kyllä mykkäelokuvakaudellakin tehtiin kenttätallenteita. Jos termi "audiovisuaalinen" on ongelmallinen niin jätetään se pois määritelmästä.

Korjattu ehdotus määritelmäksi: Muualla kuin studiossa tai muussa kontrolloidussa esitystilanteessa tehdyt tallenteet.

**Comment by mirmaid** [comment]
Hyväksytään viimeisin määritelmäehdotus.

**Comment by YSO-kokous** [comment]
Hyväksytään  viimeisin määritelmäehdotus.
