### ISSUE TITLE
Kielitietoisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8169]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kielitietoisuus 

#### Perustelut ehdotukselle   

Käsitettä käytetään kasvatusalan koulutuksissa ja se esiintyy esim. Opetushallituksen ja Kieliverkoston sivuilla. "Kielitietoinen opetus"-käsite löytyy YSA:n listalta.
(En valitettavasti osaa vastata muihin sarakkeisiin. Edellä mainitut tahot varmasti osaavat auttaa.) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kielen kehityykseen liittyvän aineiston kuvailuun. 

**Ehdottajan organisaatio:** Ihan vaan tavalliinen varhaiskasvatuksen opettaja. **Termiehdotus Fintossa:** [Kielitietoisuus](http://finto.fi/yse/fi/page/Y508169)

**Comment by tpalonen** [comment]
Kielitietoisuus lienee kielellisen tietoisuuden synonyymi. Ohjaustermiksi kielelliselle tietoisuudelle? Vrt.
http://www.solki.jyu.fi/kielistakiinni/docs/kielitietoisuusd3.htm
https://hyplus.helsinki.fi/lasten-kielellisten-valmiuksien-tukeminen-ja-kielitietoisuus/

**Comment by mirmaid** [comment]
_Kielitietoinen opetus_ otettiin nimenomaan siinä muodossa, jotta pystytään erottamaan toisistaan _kielellinen tietoisuus_ ja opetus- ja kasvatusalan uusi painopistealue _kielitietoisuus_. Kielitietoinen opetus -termimuoto soveltuu kuitenkin huonommin varhaiskasvatukseen ja ilmeisesti myös tässä julkaisussa https://journal.fi/afinlavk/issue/view/4674 on tarvittu laajemmin soveltuvaa termimuotoa.

_Kielellisellä tietoisuudella tarkoitetaan kehityksen kuluessa erotettavaa kielellistä toimintaa, joka tapahtuu ikävuosien neljä ja kahdeksan välillä. Tällöin lapsi alkaa kiinnittää huomiota kielen rakenteisiin ja operoida niillä; hän pitää kielen systeemejä ajattelun kohteena eikä pelkästään kiinnitä huomiota kielen ymmärtämiseen ja lauseiden tuottamiseen. Kielellinen tietoisuus edellyttää oman kontrollin mukanaoloa, kun normaali kielenkäyttöprosessi on automaattinen._ http://sokl.uef.fi/verkkojulkaisut/esiopetus/Norko.htm

_Kielitietoisessa varhaiskasvatuksessa ja koulussa jokainen aikuinen ymmärtää kielen merkityksen oppimisessa ja kaikessa arjen toiminnassa._ https://www.avoin.jyu.fi/fi/blogit/mika-ihmeen-kielitietoisuus

**Comment by mirmaid** [comment]
Nyt vasta huomaan, että ehdottaja on tarvinnut termiä kielen kehitykseen liittyvän aineiston kuvailuun, joten voi olla että tässä tapauksessa kielellinen tietoisuus voisi sopia. Toisaalta kyse voi olla myös siitä, että kasvattajien kielitietoisuudella tuetaan lasten kielen kehitystä...

Täältä voisi vielä tutkia määritelmiä https://journal.fi/afinlavk/issue/view/4674, jos nämä sittenkin ovat käsiteltävissä yhtenä käsitteenä.

**Comment by mariaforsen** [comment]
Ainakin ruotsin osalta jo nyt sanastossa oleva språklig medvetenhet/kielellinen tietoisuus riittää.

**Comment by mirmaid** [comment]
Kysyin asiaa vielä ylempänä mainitun blogikirjoituksen kirjoittajalta, ja hän kartoitti näkemyksiä Soveltavan kielentutkimuksen keskuksessa Jyväskylän yliopistossa:

Kielitietoisuus ansaitsisi tulla mukaan sanastoon.
Kielitietoisuuden määritelmissä on paljon vaihtelua, osin mm. tutkimusalaankin liittyen. Osa kiinnittyy kapeammin ”tietoon” tai ”tietoisuuteen” kielestä ja sen merkityksistä sekä käytöstä, osa on laveampia. Ehkä jotenkin seuraavaan tapaan näitä määritelmiä voisi pyrkiä tiivistämään (ohessa prof. Tarja Nikula-Jäntin ja minun sanoittamana):
 

- 'kielellinen tietoisuus' sitoutuu enemmän itse kieleen -> tietoa, tiedostumista kielestä (kirjallisuudessa usein lapsuusiän kielelliseen ja kognitiiviseen kehityksen yhteydessä, mutta ei koske vain tätä ikävaihetta) 

- 'kielitietoisuus' puolestaan voi viitata myös kielen funktioihin/tehtäviin, ts. siihen, missä kaikessa kielellä on merkitystä ja miten kieli huomioidaan osana toimintaa (mm. kielitietoinen pedagogiikka, mutta ei pelkästään tämä) 

Edellisen ajattelun varaan rakentuvat mielestäni myös voimassa olevat opetussuunnitelman perusteet, joissa painotetaan kielitietoiseen kouluun liittyen esim. kielen ja sisältöjen erottamattomuutta, kaikkien opettajien vastuuta kielitietoisina toimijoina ja kieli-identiteetin sekä monikielisyyden tukemista.
 
Tällainen, sekin yhdestä näkökulmasta kirjoitettu ja nykyhetken näkökulmasta hieman suppea määritelmä löytyy yhdestä julkaisustamme: Kielitietoisuus = tietoisuutta kielen monitahoisesta luonteesta: ymmärrystä siitä, kuinka kielellä rakennetaan merkityksiä sekä kuinka kielen puhujien kulttuuriset taustat kietoutuvat kielenkäyttöön (Honko & Mustonen 2018: Tunne kieli. Helsinki: Finn Lectura, s. 456) 
 
Opettajat ja opettajaopiskelijat mielsivät aineistossamme (Honko & Skinnari) kielitietoisuuden hyvinkin laveasti. Tämän linkin kautta pääsee artikkeliin ja siihen liittyvään liitteeseen, jossa on huoneentaulumaisesti koottu näkökulmia kielitietoisuuteen: https://www.kieliverkosto.fi/fi/journals/kieli-koulutus-ja-yhteiskunta-joulukuu-2020/opettajien-ja-opettajaopiskelijoiden-kasityksia-kielesta-ja-kielitietoisuudesta

**Comment by mariaforsen** [comment]
En näe miten nämä käytännössä osattaisiin käyttää johdonmukaisesti.

**Comment by YSO-kokous** [comment]
hyväksytään kielitietoinen opetus KÄ kielitietoinen opetus ja kasvatus
