### ISSUE TITLE
ngoreme

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8170]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ngoreme 

#### Perustelut ehdotukselle   

Ngurimi (Ngoreme) is a Bantu language of Tanzania. https://en.wikipedia.org/wiki/Ngoreme_language 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-4678-6 

**Termiehdotus Fintossa:** [ngoreme](http://finto.fi/yse/fi/page/Y508170)

**Comment by mariaforsen** [comment]
Sv. ngoreme (språk)
