### ISSUE TITLE
ikoma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8171]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ikoma 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-4678-6 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Ikoma_language 

**Termiehdotus Fintossa:** [ikoma](http://finto.fi/yse/fi/page/Y508171)

**Comment by mariaforsen** [comment]
Sv. ikoma (språk) ET nata, isenye

**Comment by mirmaid** [comment]
Isenje ja sen lähisukukielet ikoma ja nata luetaan tavallisesti yhden kielen (JE45) murteiksi. Kielissä on korkea leksikaalinen yhteneväisyys, mutta niiden välillä on kuitenkin merkittäviä, erityisesti fonologisia ja tonologisia, eroja. Ikoman ja natan vokaalijärjestelmät on aiemmin kuvattu, mutta isenjestä tällaista tutkimusta ei ole aikaisemmin tehty. https://helda.helsinki.fi/handle/10138/160466

**Comment by mirmaid** [comment]
Kenttätöissä keräämämme aineiston pohjalta laadimme vertailevan kieliopillisen kuvauksen neljästä kielestä: ikoma, nata, isenye sekä ngoreme, jotka ovat kaikki uhanalaisia. https://www.helsinki.fi/fi/opiskelijaksi/koulutusohjelmat/kielten-maisteriohjelma/tutkimus

**Comment by mirmaid** [comment]
– Mitä kieltä puhut?
– No, kotona Mugumussa äitini puhui minulle ikomaa ja isäni isenjeä. Kavereiden kanssa puhuin myös ngoremea ja nataa. https://koneensaatio.fi/kymmenten-kielten-kirjo/
