### ISSUE TITLE
alumiinioksidi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8173]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alumiinioksidi 

#### Ehdotettu termi englanniksi   

Aluminium oxide 

#### Ehdotettu termi ruotsiksi   

aluminiumoxid 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oksidit](http://www.yso.fi/onto/yso/p2803) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Alumiinioksidi 
TSR : alumiinioksidit 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa, Melinda x 9 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Low-temperature plasma-enhanced atomic layer deposition of silicon dioxide and aluminum oxide 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [alumiinioksidi](http://finto.fi/yse/fi/page/Y508173)

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85004029
