### ISSUE TITLE
Banachin avaruudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8174]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Banachin avaruudet 

#### Ehdotettu termi englanniksi   

Banach spaces 

#### Vaihtoehtoiset termit ja ilmaisut   

Banach-avaruudet 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85011441> 
wikipedia : https://fi.wikipedia.org/wiki/Banachin_avaruus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Metric compactification of Banach spaces 

#### Perustelut ehdotukselle   

Melinda:
Banachin avaruudet x 12
Banachin avaruus x 5
Banach-avaruudet x 2 
Banach-avaruus x 1 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Banachin avaruudet](http://finto.fi/yse/fi/page/Y508174)

**Comment by mariaforsen** [comment]
Sv. Banachrum
