### ISSUE TITLE
tensidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8178]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tensidit 

#### Ehdotettu termi englanniksi   

surfactants 

#### Vaihtoehtoiset termit ja ilmaisut   

Surface active agents 
pinta-aktiiviset aineet 

#### Vastaava käsite muussa sanastossa   

LCSH Surface active agents : <http://id.loc.gov/authorities/subjects/sh85130716> 
wikipedia : https://fi.wikipedia.org/wiki/Tensidi 
AFO pinta-aktiiviset aineet : <http://www.yso.fi/onto/afo/p145> 
FinMeSH pinta-aktiiviset aineet : <http://www.yso.fi/onto/mesh/D013501> 

#### Tarkoitusta täsmentävä selite   

SAOssa sekä Ytaktiva ämnen että Tensider

https://tieteentermipankki.fi/wiki/Nimitys:pinta-aktiivinen_aine 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Interfacial stabilization of multiphase systems with (ligno)cellulosic (nano)materials and surfactants 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tensidit](http://finto.fi/yse/fi/page/Y508178)

**Comment by mirmaid** [comment]
Melindassa 9 kertaa muodossa _tensidit_. _Pinta-aktiiviset aineet_ käytetty 10 kertaa Agriforest-terminä ja 42 kertaa vapaana avainsanana, lisäksi 5 kertaa yksikössä.

Kumpi muoto valitaan?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa pinta-aktiiviset aineet, ohjaustermiksi tensidit.

**Comment by mariaforsen** [comment]
Sv. ytaktiva ämnen ET tensider
