### ISSUE TITLE
kevytyrittäjyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8179]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kevytyrittäjyys 

#### Ehdotettu yläkäsite YSOssa (LT)   

[yrittäjyys](http://www.yso.fi/onto/yso/p1182) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Yleisesti käytössä sivutoimisesta yrittäjyydestä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sekki & Härkönen: Kevytyrittäjyys 

**Ehdottajan organisaatio:** Pyhtään kunnankirjasto **Termiehdotus Fintossa:** [kevytyrittäjyys](http://finto.fi/yse/fi/page/Y508179)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Kevytyritt%C3%A4jyys

Kielitoimiston sanakirja:  **kevyt­yrittäjyys**
yritystoiminnan kaltaisesta työstä, jonka harjoittaja ulkoistaa kirjanpidon ym. erilliselle palveluntarjoajalle.

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
? kevytyrittäjät="lättföretagare"
egenanställning ET lättföretagande
https://sv.wikipedia.org/wiki/Egenanst%C3%A4llning

**Comment by ilona-x** [comment]
http://kaino.kotus.fi/www/ordlistor/fackterm.html

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa kevytyrittäjyys ja lisätään määritelmä.
