### ISSUE TITLE
interludit (musiikki) TAI välisoitot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8181]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

interludit (musiikki) TAI välisoitot 

#### Ehdotettu termi englanniksi   

interludes (music) 

#### Ehdotettu termi ruotsiksi   

interludier 

#### Ehdotettu yläkäsite YSOssa (LT)   

[soitinmusiikki](http://www.yso.fi/onto/yso/p1514) 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026876.html> 
LCSH : <http://id.loc.gov/authorities/subjects/sh2001002582> 
Wikidata : https://www.wikidata.org/wiki/Q11032406 
SAO : https://id.kb.se/term/sao/Mellanspel%20%28musik%29 

#### Perustelut ehdotukselle   

Tarvitaan sekä YSOon että SLM-sanastoon 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sonatas and interludes / John Cage 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [interludit (musiikki) TAI välisoitot](http://finto.fi/yse/fi/page/Y508181)

**Comment by MUUSA-kokous** [comment]
Muusa pohtii asiaa vielä.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa molempia käsitteitä lisättäväksi sanastoihin.

_Interludit_
Määritelmä: Lyhyt itsenäinen soitinmusiikkiteos
LT _taidemusiikki_
LCGFT-vastine: Intermezzos (Instrumental music)

_Välisoitot_
Määritelmä: Laajemman teoksen osien välissä esitettävä orkesterimusiikkiosuus
LT YSOssa _sävellykset_, SLM:ssä _musiikki_
YSOssa poistetaan ohjaustermi _välisoitot_ termiltä _ritornellot_.
LCGFT- ja LCSH-vastine: Interludes (Music)

**Comment by ilona-x** [comment]
SLM / hyväksytään välisoitot & interludit

välisoitot myös YSOon?

**Comment by mirmaid** [comment]
Lisätty SLM:ssä LCGFT-linkit nyt Close matcheinä. Kai _intermezzot (soitinmusiikki)_ -termillä pitäisi myös olla LCGFT-vastine: http://id.loc.gov/authorities/genreForms/gf2019026036? Ja lisäksi määritelmä? Nyt on vähän vaikea tulkita, mitä eroa on _interludit_ ja _intermezzot (soitinmusiikki)_ -termeillä.

Onko termeillä _interludit_ ja _välisoitot_, sekä termeillä _interludit_ ja _intermezzot (soitinmusiikki)_ RT-suhteet toisiinsa?

**Comment by YSO-kokous** [comment]
Hyväksytään  KÄ välisoitot.

**Comment by mariaforsen** [comment]
Sv. mellanspel (musik) /SAO

**Comment by mirmaid** [comment]
Muusalta kannanotto tähän: https://github.com/Finto-ehdotus/YSE/issues/8181#issuecomment-902469594

**Comment by MUUSA-kokous** [comment]
Intermezzot (soitinmusiikki) -termin LCGFT-vastine OK: http://id.loc.gov/authorities/genreForms/gf2019026036
Määritelmä: Lyhyt itsenäinen soitinmusiikkiteos, jonka säveltäjä on nimennyt intermezzoksi.

Interludit RT intermezzot (soitinmusiikki) ja päinvastoin.

**Comment by mirmaid** [comment]
^ Tämän mukaan.

**Comment by mirmaid** [comment]
Onko nyt siis tosiaan ok, että YSOssa interludit on ohjaustermi välisoitoille, mutta SLM:ssä on molemmat erikseen, eikä niillä ole edes RT-suhdetta?

**Comment by MUUSA-kokous** [comment]
YSO
välisoitot
Muutetaan KT interludit (musiikki) -> interludit (välisoitot)

SLM:ssä ei tarvetta muutoksille.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan ohjaustermi muotoon _interludit (välisoitot)_.
