### ISSUE TITLE
intronit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8182]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

intronit 

#### Ehdotettu termi englanniksi   

introns 

#### Perustelut ehdotukselle   

Introni on geenin osa, joka ei koodaa proteiinia ja kuuluu siten tilke-DNA:han.  https://fi.wikipedia.org/wiki/Introni 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-4699-1 

**Termiehdotus Fintossa:** [intronit](http://finto.fi/yse/fi/page/Y508182)

**Comment by ilona-x** [comment]
FinMeSH: intronit http://www.yso.fi/onto/mesh/D007438
LCSH: introns http://id.loc.gov/authorities/subjects/sh90004139

**Comment by mariaforsen** [comment]
Sv. introner
