### ISSUE TITLE
sukupuolittaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8184]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sukupuolittaminen 

#### Perustelut ehdotukselle   

Sanastossa on sukupuolittuminen, tämä joko ohjaustermiksi (tai mahd. termin vaihto) tai erikseen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/294719 

**Termiehdotus Fintossa:** [sukupuolittaminen](http://finto.fi/yse/fi/page/Y508184)

**Comment by mirmaid** [comment]
Muotoa _sukupuolittaminen_ käytetty 2 kertaa Melindassa.

**Comment by mariaforsen** [comment]
YSOssa on ollut sukupuolittuminen=sexualisering (=fi. seksuaalistuminen, seksualisointi tms.), eli siinä on ollut ainakin tämän suhteen erimerkityksinen vastine? Tarvitaanko sekin merkitys YSOon?

Tässä haetaan varmaan könsuppdelning/indelning tms. eli sukupuolen perusteella erottelu yms. 

Miten nämä kaksi menevät englanniksi?

**Comment by krinay** [comment]
YSOn _sukupuolittuminen_ on englanniksi _gendered processes_, RT:t miesvaltaisuus, naisvaltaisuus, sukupuolirakenne.

THL:n Tasa-arvosanastossa (https://thl.fi/fi/web/sukupuolten-tasa-arvo/sukupuoli/tasa-arvosanasto) on termi _sukupuolistunut_: "Sukupuolistuneella tai sukupuolittuneella tarkoitetaan esimerkiksi ilmiötä tai asiaa, joka vaikuttaa eri tavoin eri sukupuoliin. Käsitteillä on vivahde-ero. Sukupuolistunut kuvaa ilmiötä prosessina, kun taas sukupuolittunut viittaa ilmiön tai asian lopputulokseen. "

**Comment by mirmaid** [comment]
Ero aktiivisen ja passiivisen muodon välillä ei varmaankaan ole mahdollista ilmaista ruotsinkielisissä termimuodoissa? Esim. lelun sukupuolittaminen puhumalla tyttöjen tai poikien leluista vs. lelun sukupuolittuminen eli määrittyminen tietyssä kulttuurissa perinteisesti ensisijaisesti jomman kumman sukupuolen leluksi. https://www.mtvuutiset.fi/artikkeli/otatko-tyton-vai-pojan-lelun-jenkeissa-on-kayty-taistoon-sukupuolittuneita-lastenaterioita-vastaan/7190148#gs.gcsg5o 

Sikäli kuin pidetään vain yksi termi, passiivinen muoto on ehkä helpommin kaikkiin yhteyksiin soveltuva (eli KT sukupuolittaminen)?

**Comment by YSO-kokous** [comment]
Lisätään seuraava ohjaustermi:
sukupuolittaminen KÄYTÄ sukupuolittuminen

Sukupuolittuminen-käsitteen kielivastineet on syytä tarkistaa. Tutkittaneen myös muotoa sukupuolittuneisuus mahdollisena pääterminä (nyt ohjaustermi sukupuolittumiselle).

**Comment by mirmaid** [comment]
Halutaanko tätä muuttaa siis muotoon sukupuolittuneisuus? Suomeksi on siinä muodossa mielestäni käytettävissä hyvin samaan tapaan kuin sukupuolittuminen (eli tavallaan sukupuolittumisen tulos).

**Comment by AuHo22** [comment]
Kielitoimiston sanakirja **sukupuolittua:**
_käydä ominaiseksi toiselle sukupuolelle; kohdistua voittopuolisesti toiseen sukupuoleen._
Esimerkkeineen:
_Väkivallan sukupuolittuminen.
Sukupuolittuneet kielen ilmaukset._

Itse kannatan olemassaolevaa muotoa ja näyttäisi olevan yleisempikin.

**Comment by YSO-kokous** [comment]
Ei muutoksia. sukupuolittuneisuus voi olla ohjausterminä
