### ISSUE TITLE
muistomitalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8188]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muistomitalit](http://www.yso.fi/onto/ysa/Y101965) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "jetonit" ja "muistojetonit" (ja vastaavasti ruotsiksi "jetoner") 

#### Perustelut ehdotukselle   

"Jetoni on yhtä kuin muistomitali." [https://www.kolikot.com/artikkelit/numismaattinen-sanasto]
Muistojetoni-nimitys taas löytyy satunnaisemmin, mutta tulee vastaan silloin tällöin verkko-osumanakin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Jetong

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi muistojetonit, mutta ei jetonit.
Muistomitali ja jetoni eivät tarkoita samaa asiaa, Jetoni on laajempi käsite.
Ks. https://sv.wikipedia.org/wiki/Jetong ja https://en.wikipedia.org/wiki/Jeton
