### ISSUE TITLE
hahmontunnistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8190]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hahmontunnistus](http://www.yso.fi/onto/ysa/Y95237) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tälle voisi lisätä englanninkielisiä KT-muotoja: object recognition; object detection; object-class detection 

#### Perustelut ehdotukselle   

hahmontunnistus
en   pattern recognition; object recognition; object detection; object-class detection
määritelmä
toiminta, jossa ohjelma tai laite erottaa datasta merkityksellisiä kokonaisuuksia
huomautus
Esimerkiksi kasvojen havaitseminen on visuaalista hahmontunnistusta.
Lähde: Tietotekniikan termitalkoot, 2017-10-09
http://www.tsk.fi/tsk/termitalkoot/hakemistot-267.html?page=get_id&id=ID503&vocabulary_code=TSKTT 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Anteeksi, että sekoitan pakkaa, mutta käsitettä ei ole käytetty pelkästään atk-kontekstissa. Esiintyy esim. 12 kertaa kognition kanssa samassa tietueessa, esim. The Oxford handbook of cognitive psychology / edited by Daniel Reisberg.
Esiintyy niin ikään 12 kertaa psykologian kanssa samassa tietueessa, esim. The Oxford handbook of face perception / edited by Andrew J. Calder, Gillian Rhodes, Mark H. Johnson and James V. Haxby.

Vrt. kasvontunnistus, joka esiintyy mm. em. Oxford hadbook of face perception -kirjassa. 
Vrt. myös sanantunnistus.

**Comment by YSO-kokous** [comment]
Tutkitaan, tarkennetaanko/laajennetaanko merkitystä. Nykyinen ryhmä ja RT:t rajaavat merkitystä vain atk-kontekstiin. Tutkittava, käytetäänkö hahmontunnistusta psykologiassa laajemmin (ei pelkästään Melinda-kuvailussa).

**Comment by ilona-x** [comment]
FinMeSH: visuaalinen hahmontunnistus, jonka alakäsitteenä kasvontunnistus http://www.yso.fi/onto/mesh/D010364
YSOssa kasvontunnistuksen ryhmä 00, eli eikö samalla perusteella tätä hahmontunnistusta voisi käyttää sekä ihmisen että koneen toiminnasta?

**Comment by MikkoAleksanteri** [comment]
En kannata koneiden tekemän hahmontunnistuksen (teknologia: https://en.wikipedia.org/wiki/Object_detection) ja ihmisten mielen prosessin (kognitiivinen prosessi: https://en.wikipedia.org/wiki/Pattern_recognition_(psychology)) yhdistämistä.

**Comment by ilona-x** [comment]
fi        hahmontunnistus
en      pattern recognition; object recognition; object detection; object-class detection
määritelmä
toiminta, jossa ohjelma tai laite erottaa datasta merkityksellisiä kokonaisuuksia
huomautus
Esimerkiksi kasvojen havaitseminen on visuaalista hahmontunnistusta.
Lähde:  	Tietotekniikan termitalkoot, 2017-10-09
	  
automaattisesti kootut käsitesuhteet
Hierarkkinen alakäsite: **kasvojen havaitseminen**

Tietotekniikan termitalkoiden mukaan pitäisi siis olla 
fi        **kasvojen havaitseminen**
mieluummin kuin: kasvojentunnistus (2)

**Comment by FinMeSHienPaimentaja** [comment]
MeSH:eihin on tullut ihan uusi termi "Automated Facial Recognition", jolle ei edes ole vielä FinMeSH-käännöstä.

_Scope Note
Electronic identification of a human based on attributes of the face._

https://meshb.nlm.nih.gov/record/ui?ui=D000086762

On myös edelleen ihmisen havainnointiin liittyvä "Facial Recognition"

_Scope Note
Ability to identify an individual from their facial features._

https://meshb.nlm.nih.gov/record/ui?ui=D000066499


***


MeSH-termi "Pattern Recognition, Automated"

_Annotation
not physiological: physiol pattern recognition is PATTERN RECOGNITION, PHYSIOLOGICAL
Scope Note
In INFORMATION RETRIEVAL, machine-sensing or identification of visible patterns (shapes, forms, and configurations). (Harrod's Librarians' Glossary, 7th ed)_

https://meshb.nlm.nih.gov/record/ui?name=Pattern%20Recognition,%20Automated

FinMeSH priona näyttää olevan "automatisoitu hahmontunnistus"

ja vastaava ihmisen havainnointiin liittyvä MeSH-termi:

Pattern Recognition, Physiological

_Scope Note
The analysis of a critical number of sensory stimuli or facts (the pattern) by physiological processes such as vision (PATTERN RECOGNITION, VISUAL), touch, or hearing._

https://meshb.nlm.nih.gov/record/ui?ui=D046709

FinMeSH:inä näyttää olevan "fysiologinen hahmottaminen"

**Comment by mirmaid** [comment]
Hahmontunnistus (tietotekniikka) ja hahmontunnistus (psykologia)?

**Comment by mariaforsen** [comment]
Sv. mönsterigenkänning

**Comment by YSO-kokous** [comment]
hyväksytään hahmontunnistus (tietotekniikka) ja hahmontunnistus (psykologia)

**Comment by mariaforsen** [comment]
Sv. 
-mönsterigenkänning (teknik)
-mönsterigenkänning (psykologi) ET mönsterigenkännande (psykologi) 

https://finto.fi/mesh/fi/page/D010364?clang=sv 
https://termipankki.fi/tepa/fi/haku/hahmontunnistus
https://sv.wikipedia.org/wiki/M%C3%B6nsterigenk%C3%A4nning
https://www.psykologiguiden.se/psykologilexikon/?Lookup=m%C3%B6nsterigenk%C3%A4nning

Onko KT visuaalinen hahmontunnistus? https://finto.fi/mesh/fi/page/D010364 ja/tai https://finto.fi/mesh/fi/page/D046709 ?
