### ISSUE TITLE
ilmavaivat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8191]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ilmavaivat](http://www.yso.fi/onto/ysa/Y156764) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermeiksi: pieru(t)  (on Kaunossa) sekä  flatus@en (on MESHissä) 

#### Perustelut ehdotukselle   

Finnan kautta löytyy muutakin kuin tieteellistä kirjallista materiaalia 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Lisätään ehdotetut ohjaustermit.
