### ISSUE TITLE
hallitukset (valtiot)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8193]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hallitukset (valtiot)](http://www.yso.fi/onto/ysa/Y95269) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT valtioneuvostot 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
EKSissä molemmat:
hallitukset 
valtioneuvosto

Suomalaisissa yhteisönimissä:
Suomi. Valtioneuvosto http://urn.fi/URN:NBN:fi:au:cn:31166A

SAO:
Ministrar KT Statsråd 

JUHO:
hallitukset (valtiot)
ST valtioneuvosto http://www.yso.fi/onto/juho/p1584

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä.

Valtioneuvosto rajautuu yleensä Suomen kontekstiin. Tässä yhteydessä voisi käyttää Suomalaisten yhteisönimien:
Suomi. Valtioneuvosto http://urn.fi/URN:NBN:fi:au:cn:31166A
Valtioneuvosto ja hallitus eivät myöskään ole täysin sama asia: https://peda.net/p/simo.veistola/e1syy/yhteiskuntaoppi2/iii-valtio/13-valtioneuvosto
