### ISSUE TITLE
meskaliini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8194]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

meskaliini 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.salakirjat.net/product/347/sielunkoynnos---henkimatkoja-unohdettuun-tietoisuuteen 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [meskaliini](http://finto.fi/yse/fi/page/Y508194)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Meskaliini
FinMeSH: meskaliini http://www.yso.fi/onto/mesh/D008635
LCSH: Mescaline http://id.loc.gov/authorities/subjects/sh85083910

**Comment by mariaforsen** [comment]
Sv. meskalin
