### ISSUE TITLE
ayahuasca

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8195]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ayahuasca 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.salakirjat.net/product/347/sielunkoynnos---henkimatkoja-unohdettuun-tietoisuuteen 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [ayahuasca](http://finto.fi/yse/fi/page/Y508195)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ayahuasca
http://id.loc.gov/authorities/subjects/sh85010604

12 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. ayahuasca

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
