### ISSUE TITLE
Turun romantiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8196]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Turun romantiikka 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Turun_romantiikka 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.sammakko.com/tuote/jukka-sarjala-turun-romantiikka/ 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Turun romantiikka](http://finto.fi/yse/fi/page/Y508196)

**Comment by ilona-x** [comment]
^huom. yhteisönimissä: Turun Romantiikka (yhtye) http://urn.fi/URN:NBN:fi:au:cn:225699A

**Comment by mirmaid** [comment]
Melindassa n. 15 kertaa tässä merkityksessä.

**Comment by mariaforsen** [comment]
Sv. Åboromantiken /SAO

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
