### ISSUE TITLE
ortognatia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8198]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ortognatia](http://www.yso.fi/onto/ysa/Y149704) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT korjaava suu- ja leukakirurgia
KT ortognaattinen kirurgia 

#### Perustelut ehdotukselle   

http://www.yso.fi/onto/mesh/D057909
FinMeSHissä pääterminä korjaava suu- ja leukakirurgia 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Menisin samalla päätermillä kuin FinMeSH.

**Comment by YSO-kokous** [comment]
Otetaan päätermiksi korjaava suu- ja leukakirurgia.
Lisätään ohjaustermeiksi ortognaattinen kirurgia ja ortognatia.

YSOn ylläpito tutkinee käsitteen suhdetta suukirurgiaan ja leukakirurgiaan.

**Comment by mariaforsen** [comment]
Sv. ortognatisk kirurgi /mesh
