### ISSUE TITLE
älyvaatteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8201]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[älyvaatteet](http://www.yso.fi/onto/ysa/Y165940) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

voisiko vaihtaa päätermiksi puettava teknologia, jota voisi käyttää laajemmin kuin termiä älyvaatteet? 

#### Perustelut ehdotukselle   

fi        puettava laite
sv       kroppsnära apparat
en      wearable device
määritelmä
mobiililaite, jonka käyttäjä voi pukea päälleen
huomautus
Puettava laite voi olla esimerkiksi älyvaate, kuten urheiluvaate, joka mittaa käyttäjän lihasten toimintaa ja sydämen sykettä ja lähettää siitä tietoa toiseen laitteeseen, esimerkiksi älypuhelimeen. Myös älykello ja aktiivisuusranneke ovat puettavia laitteita.
Käsitekaavio: Mobiililaitteet.
Lähde:
	  	
Mobiilisanasto – Matkaviestinsanaston (TSK 29) täydennysosa (TSK 48, 2015)
https://termipankki.fi/tepa/fi/haku/%C3%A4lyvaate

LCSH:
Wearable technology
http://id.loc.gov/authorities/subjects/sh2015001347

LCSHssa erikseen Smart materials, jolla ST Electronic textiles 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
ehdotettu aiemmin puettava tekniikka https://github.com/Finto-ehdotus/YSE/issues/1636

**Comment by mirmaid** [comment]
Melindassa 3 kertaa _puettava teknologia_, kerran _puettava elektroniikka_.

**Comment by mariaforsen** [comment]
Kroppsnära apparater ei juuri käytetty.
Onko sama kuin tämä (kroppsnära teknik):
https://mesh.kib.ki.se/term/D000076251/wearable-electronic-devices

**Comment by YSO-kokous** [comment]
Jatkotutkitaan.

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Puettava_tietokone

**Comment by ilona-x** [comment]
"Wearable technology eller kroppsnära teknik, ibland bärbar teknik är datorbaserad teknik inbyggd i bärbara produkter såsom kläder och accessoarer vilka bärs på kroppen." Lähde: https://sv.wikipedia.org/wiki/Wearable_technology

**Comment by FinMeSHienPaimentaja** [comment]
Laitteet/vaatteet, joita puetaan päälle, on eri asia asia kuin puettava teknologia/tekniikka (mikä on sinänsä hassusti, koska eihän teknologiaa/tekniikkaa pueta päälle).

**Comment by FinMeSHienPaimentaja** [comment]
Miten olisi "älyvaateteknologia"? Laajempi "älymateriaaliteknologia"? (ks. netti...)

**Comment by ilona-x** [comment]
Tein ehdotuksen alunperin siksi, että älyvaatteet-termin ohjaustermit puettava teknologia & puettava tietotekniikka ovat mielestäni laajempia kuin älyvaatteet,.

Jos tätä ei haluta ottaa omana käsitteenään, niin voisiko puettava teknologia/puettava tietotekniikka ohjata myös muihin jo YSOsta löytyviin termeihin kuten älytekniikka, älytuotteet, älykellot, hyvinvointiteknologia, niin kuvailija ei tulisi automaattisesti valinneeksi älyvaatteet -termiä silloin kun kyse on jostain muusta kuin vaatteista.

--
https://www.mikrobitti.fi/aiheet/puettava-teknologia 27 artikkelia
https://www.mikrobitti.fi/aiheet/alyvaatteet 1 artikkeli

--
puettava tietokone https://yle.fi/aihe/t/18-140404
älyvaatteet https://yle.fi/aihe/t/18-89198

**Comment by mirmaid** [comment]
Ainakin noiden Mikrobitin artikkelien perusteella _puettava teknologia_ kuulostaisi ihan perustellulta.

**Comment by mariaforsen** [comment]
Sv. kroppsnära teknik ET bärbar teknik, kroppsburna datorer https://sv.wikipedia.org/wiki/Wear
https://sv.wikipedia.org/wiki/Wearable_computer
https://it-ord.idg.se/ord/kroppsburen-dator/
