### ISSUE TITLE
Valkjärvi (Hamina)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8203]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Valkjärvi (Hamina) 

#### Perustelut ehdotukselle   

https://www.jarviwiki.fi/wiki/Valkj%C3%A4rvi_(12.004.1.007) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.kymijoenvesijaymparisto.fi/wp-content/uploads/2020/01/Merkj%C3%A4rven_yleissuunnitelma3.pdf 

**Termiehdotus Fintossa:** [Valkjärvi (Hamina)](http://finto.fi/yse/fi/page/Y508203)

**Comment by mirmaid** [comment]
Haminan kunnan alueella on kolme Valkjärvi-nimistä järveä. Tässä tarkoitettu on selkeästi suurin, mutta jos tarkempi tarkenne halutaan lisätä, ehkä mahdollinen olisi lähin kylä = Valkjärvi (Hamina, Metsäkylä). Kokonaan Valkjärvi ei sijaitse Metsäkylän kylässä, Järviwiki: _Valkjärvi sijaitsee Haminassa, Metsäkylän ja Kannusjärven alueella_. Toinen mahdollinen on _Vehkajoen vesistö_, koska muut kaksi järveä eivät kuulu ko. vesistöalueeseen, mutta käyttäjälle tämän varmistaminen on ehkä vähän hankalampaa.

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Valkjärvi (Hamina, Metsäkylä). Tarkentava määritelmä, esim. "Valkjärvi sijaitsee Haminassa, Metsäkylän ja Kannusjärven alueella, Vehkajoen vesistössä."
