### ISSUE TITLE
Luomajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8205]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Luomajärvi 

#### Vaihtoehtoiset termit ja ilmaisut   

Luomijärvi 

#### Perustelut ehdotukselle   

http://www.jarviwiki.fi/wiki/Luomaj%C3%A4rvi_(12.005.1.004) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.kymijoenvesijaymparisto.fi/wp-content/uploads/2020/01/Luomij%C3%A4rven_yleissuunnitelma3.pdf 

**Termiehdotus Fintossa:** [Luomajärvi](http://finto.fi/yse/fi/page/Y508205)

**Comment by mirmaid** [comment]
Auktorisoitu nimellä Luomijärvi (Paikkatietoalustan mukaan).
