### ISSUE TITLE
savimaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8208]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

savimaat 

#### Ehdotettu termi englanniksi   

Clay soils 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kivennäismaat](http://www.yso.fi/onto/yso/p16619) 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p4437> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85026874> 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Evaluation of the preconsolidation stress and deformation characteristics of Finnish clays based on piezocone testing 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [savimaat](http://finto.fi/yse/fi/page/Y508208)

**Comment by mirmaid** [comment]
Käytetty runsaasti Agriforest-terminä ja jonkin verran myös vapaana avainsanana.

**Comment by mariaforsen** [comment]
Sv. lerjordar

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
