### ISSUE TITLE
taidekauppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8210]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taidekauppa](http://www.yso.fi/onto/ysa/Y99229) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi taidemarkkinat tai taidemarkkinat omaksi käsitteekseen. 

#### Perustelut ehdotukselle   

Taidemarkkinat on käytetty Melindassa 8 kertaa, osassa näistä mukana taidekauppa. Taidekauppa on Wikidatassa englanniksi art market, saksaksi Kunstmarkt. Google-hitit: taidekauppa 24500, taidemarkkinat 12300. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Sanastossa vastaavia _musiikkimarkkinat_ (ei termiä musiikkikauppa), _asuntomarkkinat, kiinteistömarkkinat, puumarkkinat_.

**Comment by YSO-kokous** [comment]
Lisätään taidekauppa-käsitteelle ohjaustermiksi taidemarkkinat.
