### ISSUE TITLE
Musta-Ruhmas (ja muita)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8214]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Musta-Ruhmas (ja muita) 

#### Perustelut ehdotukselle   

Musta-Ruhmas
https://www.jarviwiki.fi/wiki/Musta-Ruhmas_(14.126.1.001)

Raajärvi
https://www.jarviwiki.fi/wiki/Raaj%C3%A4rvi_(14.945.1.010)

Vilajoki
https://fi.wikipedia.org/wiki/Vilajoki

Saaramaanjärvi
https://www.jarviwiki.fi/wiki/Saaramaanj%C3%A4rvi_(13.003.1.005)

Kyynelmyksenjärvi
https://www.jarviwiki.fi/wiki/Kyynelmyksenj%C3%A4rvi_(13.003.1.006)

Savonkaita 
https://www.jarviwiki.fi/wiki/Savonkaita_(04.127.1.057)

Riitjärvi
https://www.jarviwiki.fi/wiki/Riitj%C3%A4rvi_(04.127.1.058) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Useita julkaisuja http://www.kymijoenvesijaymparisto.fi/julkaisut/ 

**Termiehdotus Fintossa:** [Musta-Ruhmas (ja muita)](http://finto.fi/yse/fi/page/Y508214)

**Comment by mirmaid** [comment]
Vilajoki http://paikkatiedot.fi/so/1000772/10246272

Tämä sivujoki on myös Paikkatietoalustalla Vilajoki, http://paikkatiedot.fi/so/1000772/10246085, wikipedia:  _Ylämaan kirkonkylän kohdalla jokeen yhtyy lännestä jokihaara Harattalanjoki-Pyörteenjoki-Marjukkainjoki_.

Lisäksi Lappeenrannasta löytyy kolmas pienempi joki, joka on myös nimeltään Vilajoki.

Miten merkitään yläkäsite joelle, joka virtaa sekä Suomessa että Venäjällä?

**Comment by ilona-x** [comment]
> Miten merkitään yläkäsite joelle, joka virtaa sekä Suomessa että Venäjällä?

Jos tähän saadaan ratkaisu, niin Koitajoki on vastaava tapaus, ja sillä ei ole ollenkaan yläkäsitettä. http://www.yso.fi/onto/yso/p105080

**Comment by YSO-kokous** [comment]
Vilajoki: yläkäsitteeksi Lappeenranta ja Venäjä. Ei sulkutarkennetta.
