### ISSUE TITLE
teemat (musiikki)

### ISSUE THREAD

**Issue by MUUSA-kokous** [Finto-ehdotus/YSE#8216]
**Ehdotuksen tyyppi**
Uusi ehdotus

**Ehdotettu termi suomeksi**
teemat (musiikki)

**Tarkoitusta täsmentävä selite**
Sävelmotiiveista koostuva yksilöllinen musiikillinen, usein melodinen kokonaisuus, joka on sävellyksessä keskeisessä asemassa esittelyn, kertauksen, muuntelun tai kehittelyn kohteena. Ohjelmamusiikissa, oopperoissa ja muussa draamallisessa musiikissa teema voi toimia johtoaiheena.

**Tila**
Käsittelyssä

**Ehdotettu muutos**
Luodaan uusi käsite musiikillisille teemoille.

**Perustelut ehdotukselle**
Asiaa käsitelty issuessa https://github.com/Finto-ehdotus/YSE/issues/5832.

**Ehdottaja**
Muusa-ryhmä

**Ehdottajan sähköpostiosoite**
muusa-posti@helsinki.fi**Termiehdotus Fintossa:** [teemat (musiikki)](http://finto.fi/yse/fi/page/Y508216)

**Comment by YSO-kokous** [comment]
Suositellaan teemat-käsitteelle (https://github.com/Finto-ehdotus/YSE/issues/5832) käytettävää termiä _teemat (kerronta)_. YSO-kokous näki tämän olevan paras sulkutarkenne. Pyydetään Kauno-ryhmän vielä kommenttia tähän.

Lisäksi otetaan sanastoon _teemat (musiikki)_, mutta lisätään se sanastoon vasta kun toisen käsitteen sulkutarkenne on selvinnyt.

**Comment by ghost** [comment]
KAUNO-ryhmä kannattaa termiä teemat (kerronta) tietoaineiston kuvailussa. KAUNO-ontologiassa termi pysyy ennallaan ilman tarkennetta.

**Comment by YSO-kokous** [comment]
Hyväksytty teemat (kerronta) ja teemat (musiikki).    Teemat (kerronta) ryhmät ainakin 50, 80, 90.
