### ISSUE TITLE
kutusoraikko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8219]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kutusoraikko 

#### Vaihtoehtoiset termit ja ilmaisut   

soraistus, soraistaminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.kymijoenvesijaymparisto.fi/wp-content/uploads/2014/05/ilmasiltaraportti_2016.pdf 

#### Perustelut ehdotukselle   

Lohikalojen elinolosuhteita voidaan parantaa uomaa soraistamalla. Näin saadaan monipuolistettua uoman virtausolosuhteita ja lisättyä lohikalojen kutupaikoiksi soveltuvia alueita. Kutusoraikko kannattaa tehdä alueelle, jossa veden virtausnopeus on riittävä. Virtaus pitää soraikon puhtaana ja mahdollistaa hapekkaan veden vaihtuvuuden soraikossa. Soran levittäminen kannattaa tehdä kiveämisen yhteydessä. Tällöin kutualueita ja uoman virtausolosuhteita saadaan parhaiten muokattua niin, että sora pysyy paikallaan.

Kutusoraksi soveltuu seulottu luonnonsora, jonka raekoko on 8-50 mm väliltä. Sorakerroksen paksuus tulee olla 10-20 cm. Soran sijoittamisessa on otettava huomioon, että se ei saa jäädä kuivilleen alivirtaamienkaan aikana, eikä jäätyä talviaikaan pohjaa myöten. Kutualueiden lähellä tulee aina olla kivikkoa tai muita suojapaikkoja, jotta kutukalat saavat levätä ja kuoriutuvat poikaset saavat suojaa.
https://www.ymparisto.fi/fi-fi/vesi/vesistojen_kunnostus/Pienvesien_kunnostus/Purojen_kunnostus/Kunnostuksen_toteutus/Toimenpiteita_purojen_kunnostamiseen 

**Termiehdotus Fintossa:** [kutusoraikko](http://finto.fi/yse/fi/page/Y508219)

**Comment by mirmaid** [comment]
Ei Melindassa. AFOssa ja JUHOssa on _kutupaikat_.

**Comment by mariaforsen** [comment]
Yleiseen ontologiaan ehdottomasti muodossa kutupaikat(=lekplatser+tarkenne)

**Comment by ilona-x** [comment]
Tieteen termipankki:
**kutupaikka** http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:kutupaikka
**kutualue** http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:kutualue

**Comment by mirmaid** [comment]
Kutupaikat KT kutualueet?

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermi: kutualueet KÄYTÄ kutupaikat.

**Comment by mariaforsen** [comment]
Myös koko termi "kutupaikat" hyväksyttiin uutena terminä.

**Comment by mariaforsen** [comment]
Sv. lekplatser (fisk och groddjur) ET lekområden (fisk och groddjur)
även lekplatser=leikkipaikat > lekplatser (barn)?
