### ISSUE TITLE
ruokokuoriaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8220]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruokokuoriaiset 

#### Perustelut ehdotukselle   

https://laji.fi/taxon/MX.194793 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.kymijoenvesijaymparisto.fi/wp-content/uploads/2014/05/raportti_2014.pdf 

**Termiehdotus Fintossa:** [ruokokuoriaiset](http://finto.fi/yse/fi/page/Y508220)

**Comment by mariaforsen** [comment]
Sv. Donacia? /Laji.fi  ..Vai onko lat. Donaciinae, kuten esimerkkijulkaisussa yllä? Siinä kerrotaan mm. "Donaciinae eli ruokokuoriaiset ovat kovakuoriaisten Chrysomelidae–heimoon kuuluva alaheimo, joita on tavattu maapallolla n. 165 lajia."
