### ISSUE TITLE
tiirikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8221]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tiirikka 

#### Ehdotettu termi ruotsiksi   

en dyrk 

#### Vaihtoehtoiset termit ja ilmaisut   

tiirikointiväline 

#### Tarkoitusta täsmentävä selite   

Väline, jolla lukko avataan ilman lukkoon kuuluvaa avainta. 

#### Perustelut ehdotukselle   

Asiasanastossa ei ole tiirikointia tai tiirikointivälinettä kuvaavaa käsitettä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suomen kansallismuseon vankilakokoelman luetteloinnissa 

**Ehdottajan organisaatio:** Suomen kansallismuseo **Termiehdotus Fintossa:** [tiirikka](http://finto.fi/yse/fi/page/Y508221)

**Comment by mirmaid** [comment]
Ei Melindassa, mutta epäilemättä tarpeellinen termi jos kuvailtavana on tiirikka tai tiirikan kuva.

**Comment by mariaforsen** [comment]
Sv. dyrkar

**Comment by YSO-kokous** [comment]
Hyväksytään monikkomuodossa.
