### ISSUE TITLE
kuvitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8232]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuvitus](http://www.yso.fi/onto/ysa/Y96618) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kuvitustaide" 

#### Perustelut ehdotukselle   

Tunnetaan myös tällä nimityksella, joten olisi hyvä saada viittausmuodoksi sanastoon. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja vastaava YKL-luokkakin on [**75.12 Kuvitustaide**](http://urn.fi/URN:NBN:fi:au:ykl:75.12). Yleisemminkin asiasanastojen ja luokituksissa käytetyn terminologian olisi hyvä vastata toisiaan mahdollisimman hyvin.

**Comment by tpalonen** [comment]
Kuvitustaide olisi terminä hyvä ottaa sanastoon. Toisaalta mietin myös mahdollisuutta ottaa sanastoon erikseen kuvitukset ja kuvitus(taide). Tällaista on näköjään ehdotettukin: https://github.com/Finto-ehdotus/YSE/issues/3739 

Vrt. maalaukset, maalaus (kuvataide), maalaustaide; sarjakuvat, sarjakuvataide.

**Comment by YSO-kokous** [comment]
Käsitellään seuraavassa kokouksessa.

**Comment by mirmaid** [comment]
Yhdistelmää _kuvitus & kuvataide_ on käytetty Melindassa 343 kertaa. 

https://en.wikipedia.org/wiki/Illustration#Illustration_as_fine_art - onko _kuvitustaide_ oma taiteenlajinsa kuvataiteen alla, vai onko se ennemmin kuvataidetta (jollakin menetelmällä) tietyssä käyttöyhteydessä? Jos aineistossa käsitellään kuvitusta, on varmaan enemmän sääntö kuin poikkeus, että se nähdään jonkinlaisena luovan työn tuloksena, joten seuraisiko molempien ottamisesta sanastoon lähinnä (epäjohdonmukaista) päällekkäisyyttä?

**Comment by mariaforsen** [comment]
SAOssa illustrationskonst erikseen https://id.kb.se/term/sao/Illustrationskonst

**Comment by mirmaid** [comment]
_Kuvitustaide_ siis 11 kertaa Melindassa.

**Comment by mirmaid** [comment]
Tässä on siis kaksi mahdollisuutta:

1) lisätään _kuvitus_-käsitteelle ohjaustermit _kuvitustaide_ ja _kuvitukset_. Ei muutoksia tietokannoissa.

2) oteteen sanastoon _kuvitustaide_ ja muutetaan _kuvitus_ monikkoon. Lisätään **molemmat** kaikkiin n. 4200 tietueeseen, joissa Melindassa on _kuvitus_. Jatkossa käsitteitä voi käyttää haluamallaan tavalla, mutta varmaan yleensä kuvailuun tulisi (tai pitäisi tulla) molemmat.

**Comment by mariaforsen** [comment]
Kannatan vaihtoehtoa 2. Yksi termi joka olisi sekä kuvitus (toiminta), kuvitustaide (taiteen muoto) että kuvitukset (toiminnan tulokset) ei myöskään tuntuisi kovin "ontologiselta".

**Comment by jtuohini** [comment]
Mutta onko "kuvitus" toimintaa ('kuvittaminen') vai toiminnan tulos/tulokset ('kuvitus, kuvitukset')? "Kuvitustaide" sentään on selvästi yksi kuvataiteen alalajeista.

**Comment by mirmaid** [comment]
^^ Joka tapauksessa Melindan voisi "korjata" käytännössä vain lisäämällä kaikkiin viitteisiin molemmat, ja jatkossakin pitäisi yleensä laittaa aina molemmat, koska eihän aineisto käsittele oikeasti juuri koskaan jompaa kumpaa ilman toista. En ainakaan pysty kuvittelemaan kirjaa, jonka aiheena olisi kuvitustaide, mutta ei kuvitukset/kuvitus tai päin vastoin.

**Comment by jtuohini** [comment]
Tämä on hieman samantapainen termipari kuin ovat esim. _sävellykset_ ~ _musiikki_, _piirustukset (taide)_ ~ _piirustustaide_ ja _maalaukset_ ~ _maalaustaide_. Mitä virkaa on erillisillä asiasanoilla, jos kummatkin pitäisi aina laittaa? Juuri tämän takia LCSH:ssa ei vastaavaa juuri olekaan.

**Comment by YSO-kokous** [comment]
### Päätökset äänestyksen jälkeen
oteteen sanastoon kuvitustaide ja muutetaan kuvitus monikkoon kuvitukset
