### ISSUE TITLE
Kensingtonin palatsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8233]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kensingtonin palatsi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Kensingtonin palatsi](http://finto.fi/yse/fi/page/Y508233)

**Comment by mariaforsen** [comment]
Sv. Kensington Palace ET Kensingtonpalatset
