### ISSUE TITLE
suvannot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8236]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suvannot 

#### Ehdotettu termi englanniksi   

stream pool 

#### Perustelut ehdotukselle   

Suvanto on leveä ja syvä kohta virtavedessä, kuten esimerkiksi joessa tai purossa.  https://fi.wikipedia.org/wiki/Suvanto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://kymijoen.asiakkaat.sigmatic.fi/wp-content/uploads/2014/06/tutk125.pdf 

**Termiehdotus Fintossa:** [suvannot](http://finto.fi/yse/fi/page/Y508236)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. lugnvatten ET sel

**Comment by ilona-x** [comment]
Tieteen termipankki: 
**suvanto | jyrhämä | lompolo** http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:suvanto
**suvanto** http://tieteentermipankki.fi/wiki/Ilmatiede:suvanto

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

Keskusteltiin, onko riskiä väärinkäyttöön (suvantovaihe jossain toiminnassa tms). Ajaltiin kuitenkin, että riskiä ei ole eikä tarvita käsitteelle tarkennetta tms.
