### ISSUE TITLE
mikroverkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8237]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikroverkot 

#### Ehdotettu termi englanniksi   

micro-grids 

#### Ehdotettu termi ruotsiksi   

mikronät 

#### Vaihtoehtoiset termit ja ilmaisut   

mikrosähköverkot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sähköverkot](http://www.yso.fi/onto/yso/p7753) 

#### Vastaava käsite muussa sanastossa   

LCSH: Microgrids (Smart power grids) : <http://id.loc.gov/authorities/subjects/sh2016000604> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536) 

#### Tarkoitusta täsmentävä selite   

http://tieteentermipankki.fi/wiki/Clean_Energy_Research:micro-grid 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda x 5 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Renewable-energy-based single and community microgrids integrated with electricity markets 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mikroverkot](http://finto.fi/yse/fi/page/Y508237)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
