### ISSUE TITLE
Summanjoki (ja muita)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8238]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Summanjoki (ja muita) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Useita julkaisuja http://www.kymijoenvesijaymparisto.fi/julkaisut/ 

#### Perustelut ehdotukselle   

Summanjoki
https://fi.wikipedia.org/wiki/Summanjoki

Sorsajoki
https://beta.paikkatietoalusta.fi/tietokortit/nimisto/paikannimi/40830146

Vehkaojansuo
https://beta.paikkatietoalusta.fi/tietokortit/nimisto/paikannimi/40829843

Kiikunjoki
https://beta.paikkatietoalusta.fi/tietokortit/nimisto/paikannimi/40131772 

**Termiehdotus Fintossa:** [Summanjoki (ja muita)](http://finto.fi/yse/fi/page/Y508238)

**Comment by mirmaid** [comment]
Linjaus jokien tarkenteista? Sorsajoki on kokonaan Kouvolan kunnan alueella, mutta onko Paikannimirekisterin kunta tarkenne myös isommille joille?

**Comment by mirmaid** [comment]
Lisätty myös Summanjoen vesistö.

**Comment by YSO-kokous** [comment]
Sorsajoelle käytettäväksi termiksi Sorsajoki (Kouvola).
