### ISSUE TITLE
oppisisällöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8240]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oppisisällöt](http://www.yso.fi/onto/ysa/Y97859) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT opintosisällöt, opetussisällöt 

#### Perustelut ehdotukselle   

Löytyisi helpommin 

#### Ehdottajan organisaatio   

KK

**Comment by jtuohini** [comment]
Miksei kyseisellä asiasanalla ole suhdetta [**sisältö**](http://www.yso.fi/onto/yso/p2579)-asiasanaan? Vrt. [**työn sisältö**](http://www.yso.fi/onto/yso/p1833).

**Comment by tpalonen** [comment]
Lisätään käsitteelle RT sisältö. Käsitellään ohjaustermit YSO-kokouksessa.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermit.
