### ISSUE TITLE
huoltamot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8243]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huoltamot](http://www.yso.fi/onto/ysa/Y101698) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT bensiiniasemat 

#### Perustelut ehdotukselle   

on synonymi

**Comment by ilona-x** [comment]
^huom. tämä on ehtinyt muuttua ehdotuksen jälkeen: huoltamot KÄYTÄ **huoltoasemat**

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermeiksi bensiiniasemat ja bensa-asemat.
