### ISSUE TITLE
sarabande (tanssi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8245]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarabande (tanssi) 

#### Ehdotettu termi ruotsiksi   

sanraband (dans) 

#### Ehdotettu termi englanniksi   

sarabande (dance) 

#### Vaihtoehtoiset termit ja ilmaisut   

saraband (dance) 
zarabanda (tanssi) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Tarkoitusta täsmentävä selite   

Eteläamerikkaista alkuperää olevaa kolmijakoinen tanssi, joka oli suosituimmillaan Euroopassa 1500–1700-luvuilla. ("Dance in triple time with the accent on the second beat. Originally a somewhat erotic dance with a Spanish influence, it was danced in both S. America and Spain during the 16th century. It developed a more dignified form when it became popular in Europe during the 17th and 18th centuries." Lähteenä The Oxford Dictionary of Dance, 2nd edition.) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/016575774 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [sarabande (tanssi)](http://finto.fi/yse/fi/page/Y508245)

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. saraband (danser)
