### ISSUE TITLE
sähkösoittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8246]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sähkösoittimet](http://www.yso.fi/onto/ysa/Y99169) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-suhde asiasanaan "sähkölaitteet" 

#### Perustelut ehdotukselle   

Kaikki sähkösoittimet ovat yhdenlaisia sähkölaitteita, joten termien välillä tulisi vallita tätä seikkaa kuvaava suhde. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
