### ISSUE TITLE
psykoanalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8247]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[psykoanalyysi](http://www.yso.fi/onto/ysa/Y98252) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sanastosta löytyy myös psykoanalyyttiset teoriat ja psykoanalyyttinen kirjallisuudentutkimus. Onko käsitteitä käytetty johdonmukaisesti vai onko psykoanalyysiä käytetty myös teorioiden ja kirjallisuudentutkimuksen yhteydessä? Onko psykoanalyysi-käsitteen tarkoitus viitata vain hoitomenetelmään ja jos kyllä, onko tämä toteutunut kuvailussa? Asiaa olisi hyvä tutkia ja pohtia, vaatiiko tilanne muutoksia. Psykoanalyysiä voi toki teoriana soveltaa muussakin tutkimuksessa kuin kirjallisuudentutkimuksessa, esim. kuvataiteen tai elokuvien tutkimuksessa. 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

Psykoanalyysi ja kaunokirjallisuus esiintyvät yhdessä 111 Melinda-tietueessa.
Esim. The dark enlightenment : Jung, romanticism, and the repressed other / D.J. Moores.
Psykoanalyysi ja kuvataide esiintyvät yhdessä 67 Melinda-tietueessa.
Esim. Nykytaiteen alkukuvat : postjungilainen estetiikka nykykuvataiteen tulkintavälineenä / Johanna Wahlbeck.
Psykoanalyysi ja elokuvat esiintyvät yhdessä 95 Melinda-tietueessa.
Esim. The Disney fetish / Sean J. Harrington.

**Comment by tpalonen** [comment]
Lisähuomioita Melindasta: psykoanalyysi ja kirjallisuudentutkimus käytetty myös samoissa tietueissa.
Esim. The "Lord" in the Lord of the Rings : christian imagery and allegorical allusions in J.R.R. Tolkien’s epic saga / Satu Pietilä.
Psykoanalyysi ja kielitiede esiintyvät yhdessä 65 tietueessa.
Esim. To speak is never neutral / Luce Irigaray ; translated by Gail Schwab.
Psykoanalyysi ja teologia esiintyvät yhdessä 35 tietueessa.
Esim. Psychological insight into the Bible : texts and readings / edited by Wayne G. Rollins & D. Andrew Kille

**Comment by mirmaid** [comment]
psykoanalyyttinen kirjallisuudentutkimus KT psykoanalyysi (kirjallisuudentutkimus)?

**Comment by mirmaid** [comment]
Pitäisikö rajata psykoanalyysi (terapia)? On kyllä melkein 5000 kertaa käytetty Melindassa. Miten tätä halutaan rajata suhteessa psykoanalyyttisiin teorioihin?

**Comment by mirmaid** [comment]
Toisaalta jos osittainen ristiin käyttö ei ole suuri ongelma, voidaan vain lisätä ohjaustermejä myös muille kahdelle?

psykoanalyysi (terapia) KÄ psykoanalyysi
psykoanalyysi (teoriat) KÄ psykoanalyyttiset teoriat

**Comment by YSO-kokous** [comment]
#### Päätös
Lisätään ohjaustermit Mirjan ehdotuksen mukaisesti:
psykoanalyysi (terapia) KÄ psykoanalyysi
psykoanalyyttinen terapia KÄ psykoanalyysi
psykoanalyysi (teoriat) KÄ psykoanalyyttiset teoriat
psykoanalyysi (kirjallisuudentutkimus) KÄ psykoanalyyttinen kirjallisuudentutkimus
