### ISSUE TITLE
chatbot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8250]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

chatbot 

#### Ehdotettu termi englanniksi   

chatbot 

#### Ehdotettu termi ruotsiksi   

chatbot 

#### Tarkoitusta täsmentävä selite   

Chatbot on tietokoneohjelma, joka on suunniteltu käymään keskustelua ihmisen kanssa. 

#### Perustelut ehdotukselle   

Opinnäytetyön avainsanoissa saa käyttää vain YSA:sta löytyviä käsitteitä. Tämä sana on oleellinen avainsana opinnäytetyölleni. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Opinnäytetyö 

**Ehdottajan organisaatio:** Haaga-Helia **Termiehdotus Fintossa:** [chatbot](http://finto.fi/yse/fi/page/Y508250)

**Comment by mirmaid** [comment]
Melindassa suomenkielisessä kuvailussa kerran _chatbot_, kerran _chatbot-ohjelmat_.

**Comment by ilona-x** [comment]
**asiointibotti; palvelubotti; chattibotti**
en   chatbot; chatterbot; talkbot
määritelmä
ohjelma, joka on suunniteltu keskustelemaan ihmisen kanssa joko puheen tai kirjoitetun tekstin välityksellä
huomautus
Monet verkkoasiointia tarjoavat organisaatiot, kuten kaupat, lentoyhtiöt, hotellit, pankit ja viranomaiset, käyttävät asiointibotteja esimerkiksi edistämään myyntiä ja vastaamaan asiakkaiden yksinkertaisiin kysymyksiin.
Lähde: Tietotekniikan termitalkoot, 2018-12-19

**Comment by mariaforsen** [comment]
Sv. chatbottar ET chatbotar, chatrobotar, dialogrobotar
https://svenska.se/tre/?sok=bot&pz=1
https://it-ord.idg.se/ord/bot/
https://it-ord.idg.se/ord/dialogrobot/

**Comment by mirmaid** [comment]
Termitalkoiden muodoista käytetyin on _chattibotti_.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa chattibotit. Ohjaustermiksi chatbotit, palvelubotit, asiointibotit.
