### ISSUE TITLE
kalamajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8251]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kalamajat](http://www.yso.fi/onto/ysa/Y506649) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kalapirtit" 

#### Perustelut ehdotukselle   

Termiä on käytetty pitkään kirjallisuudessa (esim. Samuli Paulaharju ja http://www.rky.fi/read/asp/r_kohde_det.aspx?KOHDE_ID=1032), joten viittaussuhteelle on kirjallisuustakuu 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
