### ISSUE TITLE
karaiitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8252]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[karaiitit](http://www.yso.fi/onto/ysa/Y195067) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö selkeyttää? 

#### Perustelut ehdotukselle   

https://helda.helsinki.fi/handle/10138/239255
https://en.wikipedia.org/wiki/Crimean_Karaites

**Comment by tpalonen** [comment]
Tutkitaan vielä. Vrt. esim. karaiimin kieli.

**Comment by mariaforsen** [comment]
Ruotsin osalta tämä on selvä, https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/karaiter ("I Litauen och Ukraina finns ättlingar till karaiter som kallas karaimer")

**Comment by mirmaid** [comment]
Ainakin voisi lisätä karaiittijuutalaiset KÄ karaiitit, sekä RT-suhde käsitteille.

**Comment by mirmaid** [comment]
Tässä kuvailtavassa väitöskirjassa sanotaan: 
_On the basis of their linguistic differences, the Karaites may be divided into two groups: (1)the Arabic-speaking Karaites of the Middle East (Egypt, Iraq, Syria, Israel) and (2) the traditionally Turkic-speaking Karaites of Eastern Europe (the post-Soviet regions, Poland and Lithuania). At the moment, there are approximately 20–30,000 Karaites in the world. Most of them originated from Egypt, but emigrated to Israel or the United States after the 1950s._

Suomenkielisen wikipedian antamat väestömäärät vastaavat suunnilleen tätä kokonaismäärää, kun taas ruotsinkielinen sivu mainitsee vain Puolan ja Liettuan karaiimit, joitakin satoja. Englanninkielisen wikipedian mukaan Krimin karaiimeja (Crimean Karaites) on n. 2500. Karaitisk judendom -sivulla puolestaan puhutaan n. 30 000 uskontoa harjoittavasta. Vastaavilla suomen- ja englanninkielisillä sivuilla määrä on 50 000.

Eli ilmeisesti pitää olettaa, että ruotsinkielisen wikipedian näkökulma on suppea, suomenkielisen väestömäärä on täysin pielessä ja väitöskirjan termivalinta _I employ the traditional Latin term Karaites for simplicity’s sake_ ei ole tarkoituksessaan täysin onnistunut.

**Comment by mariaforsen** [comment]
Pitäisin vielä kiinni vakiintuneesta jaottelusta, eli en tekisi pelkästään tuon väitöskirjan perusteella muutoksia YSOon.

**Comment by YSO-kokous** [comment]
karaiittijuutalaiset KÄ karaiitit, sekä RT-suhde käsitteille
