### ISSUE TITLE
torviseitsikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8253]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[torviseitsikot](http://www.yso.fi/onto/ysa/Y214703) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

LIsätään LT-suhde asiasanaan "septetit" 

#### Perustelut ehdotukselle   

Torviseitsikko on sekä puhallinyhtye että septetti, ja termien välisten suhteiden pitäisi kuvastaa tätä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.
