### ISSUE TITLE
rukousmyllyt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8254]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rukousmyllyt 

#### Ehdotettu termi englanniksi   

prayer wheel 

#### Ehdotettu termi ruotsiksi   

bönekvarn 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://en.wikipedia.org/wiki/Prayer_wheel 

#### Perustelut ehdotukselle   

Yleinen ja tunnettu esine. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Museokokoelmat 

**Ehdottajan organisaatio:** Kansallismuseo **Termiehdotus Fintossa:** [rukousmyllyt](http://finto.fi/yse/fi/page/Y508254)

**Comment by mirmaid** [comment]
Kaksi viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.

**Comment by mariaforsen** [comment]
Sv. bönekvarnar
