### ISSUE TITLE
koptilainen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8256]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koptilainen kirkko](http://www.yso.fi/onto/ysa/Y96326) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCNAF/LCSH-sanaston termiin "Coptic Church" [http://id.loc.gov/authorities/names/n79107736] 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Tutkitetaan ja linkitetään tarvittaessa.

**Comment by tpalonen** [comment]
Koptilainen kirkko viittaa kahteen ainakin kahteen eri kirkkoon, ks. https://en.wikipedia.org/wiki/Coptic_church
