### ISSUE TITLE
Bilbao

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8258]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Bilbao 

#### Perustelut ehdotukselle   

Tarvitaan esim. ko. kaupungin matkaoppaan kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781789198812 

**Termiehdotus Fintossa:** [Bilbao](http://finto.fi/yse/fi/page/Y508258)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8262
