### ISSUE TITLE
kaupunginvaltuutetut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8260]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kaupunginvaltuutetut](http://www.yso.fi/onto/ysa/Y113405) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan termin hierarkia analogiseksi asiasanan "kunnanvaltuutetut" kanssa, t.s. lisätään LT-suhde asiasanaan "kunnallispoliitikot". 

#### Perustelut ehdotukselle   

Kaupunki on yksi kuntamuoto, joten kunnanvaltuutettu ja kaupunginvaltuutettu ovat kumpikin kunnallispoliitikkoja. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Tai oikeammin vielä parempi olisikin muuttaa **kaupunginvaltuutetut**-asiasanan LT-muodoksi **kunnanvaltuutetut**, jolloin analogia olisi sama kuin asiasanojen **kaupungit** ja **kunnat** välillä vallitseva LT/ST-suhde: kaikki kaupungit ovat kuntia, joten kaikki kaupunginvaltuutetut ovat yhdenlaisia kunnanvaltuutettuja. (Tällöin tietysti pitäisi poistaa muut, ylimääräiset LT-suhteet.)

**Comment by tpalonen** [comment]
Kaupunginvaltuutetut LT kunnanvaltuutetut.
