### ISSUE TITLE
työpiirustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8261]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

työpiirustukset 

#### Ehdotettu termi ruotsiksi   

arbetsritningar? 

#### Ehdotettu termi englanniksi   

structural designs? 

#### Vaihtoehtoiset termit ja ilmaisut   

rakennusmallit? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 
[28 Metsäteollisuus. Massa- ja paperiteollisuus. Paperiteollisuus. Puuteollisuus](http://www.yso.fi/onto/yso/p26585) 

#### Tarkoitusta täsmentävä selite   

Tarvittaisiin SLM-sanastoon huonekalujen, soittimien ym. työpiirustuksia varten. 

#### Perustelut ehdotukselle   

Kirjastossa on paljon pelkkiä malleja/kaavoja/työpiirustuksia ilman sanallisia rakennusohjeita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esimerkiksi Astiakaappi koristemaaluksin, 017373862/id 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [työpiirustukset](http://finto.fi/yse/fi/page/Y508261)

**Comment by mirmaid** [comment]
MAO-ontologiassa. Käytetty Melindassa runsaasti vapaana avainsanana, luultavasti tarpeen erityisesti SLM-terminä, mutta myös esim. https://melinda.kansalliskirjasto.fi/byid/003116265. 

Käytetty melko usein myös kudontatöistä, mihin kaikkeen tämän on tarkoitus soveltua?

**Comment by YSO-kokous** [comment]
Odotetaan SLM-kokousta ja edetään YSOn kannalta asiassa tämän jälkeen.

**Comment by AuHo22** [comment]
YSO tekniset piirustukset ryhmä 00
mitta-/pohjapiirustukset 
    37 Rakentaminen. Rakennusteollisuus Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus
    91 Arkkitehtuuri

Työpiirustukset voivat kai olla myös näitä kaikkia? Melko lähellä kuitenkin ryhmiä 28 ja 94

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
työ­piirustus
tav. mon. työn suoritusta varten tehty yksityiskohtainen piirustus.
Sillan työpiirustukset.

**Comment by ilona-x** [comment]
työpiirustukset | toteutuspiirustukset
	
Määritelmä rakentamisessa piirustukset, joiden perusteella kohde toteutetaan
Selite Työpiirustuksiin voi kuulua esimerkiksi porraspiirustuksia, ovi- ja ikkunakaavioita ja osaleikkauksia sekä erilaisia detaljipiirustuksia.

Lähde: http://tieteentermipankki.fi/wiki/Taidehistoria:ty%C3%B6piirustukset

**Comment by ilona-x** [comment]
MAOn hierarkia: 
piirustukset (tekniset) > suunnittelupiirustukset > työpiirustukset
http://www.yso.fi/onto/mao/p8366

**Comment by mirmaid** [comment]
Selvitetään lisää. Myös esim. käsityömallit, ompelukaavat vastaavia. Miten hyvin soveltuu tekniset piirustukset?

**Comment by annavii** [comment]
Termiä on perinteisesti käytetty (653-kentässä) veneiden/huonekalujen/soitinten/kangaspuiden piirustuksista, joissa ei ole mukana mitään suurempaa ohjeistusta (kyseessä siis "kaavat" joissa saattaa olla hiukan tekstiä tulkitsemisen avuksi). Tutkin meillä varastossa olevia tapauksia ja varmistin, että Tampereella kyse on vastaavanlaisesta aineistosta. Tampereella termiä on tosin käytetty myös (kangaspuilla kudottavien) kudontatöiden malleista. 

Muuten nuo tuntuisivat sopivan tuohon MAO-hierarkiaan (piirustukset (tekniset) > suunnittelupiirustukset > työpiirustukset), mutta kudontatöiden kaavoja on ehkä vaikea ajatella teknisinä piirustuksina?

**Comment by mirmaid** [comment]
Otetaan sanastoon tekniset piirustukset, KT työpiirustukset.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi työpiirustukset KÄYTÄ tekniset piirustukset.

**Comment by mirmaid** [comment]
Voiko SLM-sanastossa teknisten piirustusten yläkäsite olla _ohjeet_? Vaiko RT? Entä onko RT käsityöohjeet, rakennusohjeet?

**Comment by mirmaid** [comment]
Ei ehdotettuja suhteita.
