### ISSUE TITLE
kontrabasso

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8263]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kontrabasso](http://www.yso.fi/onto/ysa/Y101959) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään asiasanalle KT-muoto "pystybasso". 

#### Perustelut ehdotukselle   

Kyseistä termiä on käytetty Finnassa kontrabassoa kuvaamaan, joten viittausmuodolle olisi tilausta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja sama KT-muoto lisättäväksi toki myös Seko-sanastoon!

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
