### ISSUE TITLE
tapahtumalehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8264]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tapahtumalehdet 

#### Perustelut ehdotukselle   

Saisiko SLM-sanastoon, käytetty genreterminä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Koivu ja tähti -päivät

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
