### ISSUE TITLE
Törnävän kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8265]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Törnävän kirkko](http://www.yso.fi/onto/ysa/Y168113) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään nimen perään sulkutarkenne paikkakunnasta "(Seinäjoki)". 

#### Perustelut ehdotukselle   

Tyrnävän vanha nimi on Törnävä, joten pelkkä "Törnävän kirkko" voi viitata myös Tyrnävän kirkkoon (josta sivumennen sanottuna ei ole omaa YSO-asiasanaa). 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8267

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
