### ISSUE TITLE
kemiallinen kaasufaasipinnoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8266]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kemiallinen kaasufaasipinnoitus 

#### Ehdotettu termi englanniksi   

Chemical vapor deposition 

#### Vaihtoehtoiset termit ja ilmaisut   

CVD-pinnoitus 
CVD 

#### Ehdotettu yläkäsite YSOssa (LT)   

[menetelmät](http://www.yso.fi/onto/yso/p1913) 

#### Alakäsitteet (RT)   

[atomikerroskasvatus](http://www.yso.fi/onto/yso/p27468) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh94001275> 
Wikipedia : https://fi.wikipedia.org/wiki/Kemiallinen_kaasufaasipinnoitus 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Aerosol CVD synthesis and applications of single-walled carbon nanotube thin films using spark-discharged produced catalyst 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kemiallinen kaasufaasipinnoitus](http://finto.fi/yse/fi/page/Y508266)

**Comment by mirmaid** [comment]
Kerran Melindassa, 2 x kemiallinen kaasufaasikasvatus.

**Comment by mariaforsen** [comment]
Sv. kemisk gasfasdeponering ET CVD-beläggning, kemisk ångdeponering, kemisk ångavsättning

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
