### ISSUE TITLE
hilateoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8269]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hilateoria 

#### Ehdotettu termi englanniksi   

Lattice theory 

#### Vaihtoehtoiset termit ja ilmaisut   

Lattices (Mathematics) 
hilat (matematiikka) 

#### Vastaava käsite muussa sanastossa   

LCSH: : <http://id.loc.gov/authorities/subjects/sh85074991> 
Wikipedia : https://fi.wikipedia.org/wiki/Hila_(matematiikka) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

On decoding problems, lattices and generalized concatenated codes 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hilateoria](http://finto.fi/yse/fi/page/Y508269)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. gitterteori

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon, mutta YSOn ylläpito tutkii vielä kummassa muodossa otetaan: hilat (matematiikka) vai hilateoria?
