### ISSUE TITLE
Marskenttä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8270]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Marskenttä](http://www.yso.fi/onto/ysa/Y167479) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään yleis-YSOsta YSO-paikkoihin ja lisätään määrite, ettei sekoitu Pariisissa ja Pietarissa oleviin samannimisiin aukioihin/puistoihin. 

#### Perustelut ehdotukselle   

Kyseessä on paikannimi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Campus_Martius

**Comment by YSO-kokous** [comment]
Siirretään YSO-paikkoihin. Käsite viittaa Rooman Marskenttään. Tarkistetaan termimuoto ja tarve tarkenteelle.
