### ISSUE TITLE
kahluualtaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8271]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kahluualtaat 

#### Perustelut ehdotukselle   

Leikkipuistossa sijaitseva matala ulkoallas lasten kahlaamista ja vesileikkejä varten. https://www.hel.fi/helsinki/fi/kaupunki-ja-hallinto/hallinto/palvelut/palvelukuvaus?id=7417 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/ymk/julkaisut/moniste-06-03.pdf 

**Termiehdotus Fintossa:** [kahluualtaat](http://finto.fi/yse/fi/page/Y508271)

**Comment by mirmaid** [comment]
Kahluualtaiksi nimitetään myös puhallettavia yms. liikuteltavia altaita ja uimahallien matalia altaita, mutta ei liene ongelma.

Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. plaskbassänger ET plaskdammar, vadbassänger

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
