### ISSUE TITLE
vironkieliset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8272]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vironkieliset 

#### Ehdotettu termi englanniksi   

Estonian speakers 

#### Ehdotettu termi ruotsiksi   

estniskspråkiga 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kieleen liittyvä rooli](http://www.yso.fi/onto/yso/p2200) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 
[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

Melinda x 8 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Samaa vai eri maata? : tutkimus viiden kieliryhmän arvoista ja asenteista / 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vironkieliset](http://finto.fi/yse/fi/page/Y508272)

**Comment by mariaforsen** [comment]
Sv. estniskspråkiga ET estnisktalande
