### ISSUE TITLE
somalinkieliset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8273]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

somalinkieliset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kieleen liittyvä rooli](http://www.yso.fi/onto/yso/p2200) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Samaa vai eri maata? : tutkimus viiden kieliryhmän arvoista ja asenteista / 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 
[85 Kielitiede](http://www.yso.fi/onto/yso/p26557) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [somalinkieliset](http://finto.fi/yse/fi/page/Y508273)

**Comment by mariaforsen** [comment]
Sv. somalispråkiga ET somalitalande
