### ISSUE TITLE
Uutela

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8275]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Uutela 

#### Ehdotettu termi ruotsiksi   

Nybondas 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Uutela
Uutela on ulkoilupuisto Vuosaaressa Itä-Helsingissä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/2006/uutela_2006_7.pdf 

**Termiehdotus Fintossa:** [Uutela](http://finto.fi/yse/fi/page/Y508275)

**Comment by ilona-x** [comment]
Paikkatietoalustalla vain yksi Uutela Helsingissä, ja sen paikkatyyppinä on "Kylä tai kulmakunta" http://paikkatiedot.fi/so/1000772/10343157

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Uutela (Helsinki), yläkäsitteeksi Helsinki.
