### ISSUE TITLE
syreenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8276]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syreenit 

#### Ehdotettu termi englanniksi   

syringa 

#### Ehdotettu termi ruotsiksi   

syrensläktet 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Syreenit
Syreenit (Syringa) ovat öljypuukasveihin (Oleaceae) kuuluva puuvartinen kasvisuku. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/2006/pihasyreenit.pdf 

**Termiehdotus Fintossa:** [syreenit](http://finto.fi/yse/fi/page/Y508276)

**Comment by mariaforsen** [comment]
Sv. syrensläktet ET syrener, syrener (släkte) 
https://www.dyntaxa.se/Taxon/Info/1006345?changeRoot=True
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/syringa
https://sv.wikipedia.org/wiki/Syrensl%C3%A4ktet
