### ISSUE TITLE
pihasyreeni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8277]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pihasyreeni 

#### Ehdotettu termi ruotsiksi   

bondsyren, syren 

#### Ehdotettu termi englanniksi   

lilac, common lilac 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Pihasyreeni
Pihasyreeni (Syringa vulgaris) on oliivikasvien (Oleaceae) heimoon kuuluva lehtipensas, joka on suosittu koristekasvi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/2006/pihasyreenit.pdf 

**Termiehdotus Fintossa:** [pihasyreeni](http://finto.fi/yse/fi/page/Y508277)

**Comment by mariaforsen** [comment]
Sv. syren /NE ET bondsyren
https://www.dyntaxa.se/Taxon/Info/221841?changeRoot=True
