### ISSUE TITLE
Alppipuisto (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8278]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Alppipuisto (Helsinki) 

#### Ehdotettu termi ruotsiksi   

Alpparken 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Alppipuisto
Alppipuisto (ruots. Alpparken) on 16,5 hehtaarin kokoinen Helsingin Alppiharjun kaupunginosassa Alppilan osa-alueella sijaitseva puistoalue. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/alppilenin1_50.pdf 

**Termiehdotus Fintossa:** [Alppipuisto (Helsinki)](http://finto.fi/yse/fi/page/Y508278)

**Comment by mariaforsen** [comment]
Sv. Alpparken (Helsingfors)
