### ISSUE TITLE
Lenininpuisto (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8279]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Lenininpuisto (Helsinki) 

#### Ehdotettu termi ruotsiksi   

Leninparken 

#### Perustelut ehdotukselle   

Lenininpuisto (ruots. Leninparken) on Helsingin Alppilassa sijaitseva puutarha-arkkitehti Maj-Lis Rosenbröijerin suunnittelema 3,5 hehtaarin kokoinen puisto
https://fi.wikipedia.org/wiki/Lenininpuisto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/alppilenin1_50.pdf 

**Termiehdotus Fintossa:** [Lenininpuisto (Helsinki)](http://finto.fi/yse/fi/page/Y508279)

**Comment by mariaforsen** [comment]
Sv. Leninparken (Helsingfors)
