### ISSUE TITLE
plasmoniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8280]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

plasmoniikka 

#### Ehdotettu termi englanniksi   

plasmonics 

#### Ehdotettu termi ruotsiksi   

plasmonik 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2017005180> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Perustelut ehdotukselle   

Melinda x 10 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Loss circumvention and plasmonic lasing in arrays of magnetic nanodots 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [plasmoniikka](http://finto.fi/yse/fi/page/Y508280)

**Comment by mirmaid** [comment]
_Plasmoniikka eli metallisten nanorakenteiden optiikka._

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
