### ISSUE TITLE
luominen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8281]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luominen](http://www.yso.fi/onto/ysa/Y97004) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tämän on ilmeisesti tarkoitus viitata vain teologian merkitykseen, luokkana vain 53 ja englanniksi Creation (religion) 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

Käytetty Melindasas muussakin merkityksessä esim:
Managing and leading organizational learning and knowledge creation 
Becoming to know :essays on extended epistemology of knowledge creation 
Methods and models in linguistic and musical computational creativity

**Comment by ilona-x** [comment]
tiedon luominen https://github.com/Finto-ehdotus/YSE/issues/1830

**Comment by mirmaid** [comment]
Sanastossa on myös _luovuus, luova toiminta_ ja _taiteellinen työ_, jotka riittänevät yleensä muissa yhteyksissä.

**Comment by tpalonen** [comment]
Käytettäväksi termiksi _luominen (uskonto)_ ja sanastoon alla olevat ohjaustermit?
_luominen (luova toiminta) KÄ luova toiminta
luominen (luovuus) KÄ luovuus
luominen (taiteellinen työ) KÄ taiteellinen työ_

**Comment by YSO-kokous** [comment]
Käsitteen käytettäväksi termiksi luominen (uskonto).
