### ISSUE TITLE
Rastila (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8282]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Rastila (Helsinki) 

#### Ehdotettu termi ruotsiksi   

Rastböle 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Rastila
Rastila (ruots. Rastböle) on pientalovaltainen osa-alue Helsingin Vuosaaressa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/vas/KeskiVuosaari/Keski-Vuosaari_web_osaA.pdf 

**Termiehdotus Fintossa:** [Rastila (Helsinki)](http://finto.fi/yse/fi/page/Y508282)

**Comment by ilona-x** [comment]
Paikkatietoalusta: Rastila paikkatyyppi: "Kaupunkialueen tai taajaman osa" http://paikkatiedot.fi/so/1000772/10343149

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Rastila (Helsinki), yläkäsitteeksi Helsinki.
