### ISSUE TITLE
Maununneva (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8283]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Maununneva (Helsinki) 

#### Ehdotettu termi ruotsiksi   

Magnuskärr 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Maununneva
Maununneva (ruots. Magnuskärr) on Kaarelan kaupunginosan osa-alue Helsingissä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/2008/kaarela_2008_11_4.pdf 

**Termiehdotus Fintossa:** [Maununneva (Helsinki)](http://finto.fi/yse/fi/page/Y508283)

**Comment by ilona-x** [comment]
paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10012962

**Comment by YSO-kokous** [comment]
Käytettäväksi termiksi Maununneva (Helsinki), yläkäsitteeksi Helsinki.
