### ISSUE TITLE
suorituskyky

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8284]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suorituskyky](http://www.yso.fi/onto/ysa/Y99088) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkoittaako vain fyysistä suorituskykyä? Luokat: 78 Työelämä. Työsuojelu. Työterveys & 97 Liikunta. Urheilu
MUUNKIELISET TERMIT
performance (physical capacity) 

#### Perustelut ehdotukselle   

Käytetty Melindassa myös esim. yritysten suorituskyvystä

**Comment by tpalonen** [comment]
Sanastossa myös toimintakyky, fyysinen toimintakyky, psyykkinen toimintakyky, sosiaalinen toimintakyky, suoriutuminen, kompetenssi jne. Tutkitaan, onko käsite ylipäätään tarpeellinen ja jos on, pitäisikö käytettävää termiä tarkentaa.

**Comment by mariaforsen** [comment]
Toimintakyky on kuitenkin eri asia kuin Suorituskyky. Mutta suoriutuminen/"presterande" on kyllä aika lailla päällekkäinen ruotsin osalta (ja vaikea kääntää)

**Comment by mirmaid** [comment]
Käytetty Melindassa n. 2800 kertaa. Käyttö ei rajaudu fyysiseen suorituskykyyn, eikä liioin ihmisen suorituskykyyn, vaan on käytetty paitsi organisaatioista, myös laitteista.

**Comment by mirmaid** [comment]
_Suoriutuminen_-käsitettä käytetty Melindassa n. 1400 kertaa (ihmisistä ja yrityksistä).

Ruotsiksi ehkä suurin hankaluus tulee siitä, että sekä _suoritteet_, että _suoriutuminen_ olisi luontevinta kääntää _prestation/-er_?

**Comment by mirmaid** [comment]
Tässä issuessa ei ehkä nyt ole ihan selkeää mitä pitäisi lähteä edistämään, tuskin ainakaan _suorituskyky_-käsitteen poistoa, mutta pitäisikö jotakin rajata tarkemmin tms. jotta kielten vastaavuus olisi parempi, ja jos niin mitä näistä kolmesta?

**Comment by mariaforsen** [comment]
Hankalaa on varsinkin itse muoto suoriutuminen. Ja se että on epäselvää mitä käsitettä pitäisi käyttää "suoritukset"-merkityksestä? Ja se että suoritteet-termin merkitys on epäselvä.

**Comment by mirmaid** [comment]
Onko jotain esimerkkiä tuosta _suoritukset_-merkityksestä? Suomeksi sekin sopii niin monenlaisiin yhteyksiin.

**Comment by mirmaid** [comment]
Suoritteet on nyt määritelty: _Palvelu, työ tai vastaava laskennallisena yksikkönä_.

**Comment by YSO-kokous** [comment]
Suorituskyvyn eng. vastine korjattava. Maria päivittää suoritteet. Suoriutuminen: tutkitaan vastaavuus. Vrt. selviytyminen.

**Comment by mariaforsen** [comment]
Eli kyseessä nyt enää suoriutuminen. 

Tällä hetkellä suoriutuminen YK selviytyminen -väärin ruotsin osalta, ja jos merkitys todella on enemmänkin "selviytyminen" kuin suorittaminen niin vastinetta ei varmaan saada, varsinkin kun selviytyminen on jo erillisenä terminä (klara sig). 

Kielitoimiston sanakirja: suoriutua: "selviytyä, selvitä" - eli päällekkäinen selviytymisen kanssa. 

Ruotsiksi tarvittaisiin kyllä joku termi suorittamiselle/suorituksille, eli presterande/prestation, mutta se ei näköjään voi olla sama kuin "suoriutuminen"? Tosin Melindassa suoriutuminen=presterande on kyllä käytetty todella paljon suorittamisesta/suorituksista, mutta onko syy englanninkieliset ja ruotsinkieliset vastineet? (Näitä viitteitä ei voi ainakaan kuvailla muillaYSO-termeillä esim. suorituskyky tai suoritteet=prestationer (produkt))

Ks. myös https://vanha.karelia.fi/blogit/viittavaillevalmiinatyoelamaan/2019/04/05/suorittaminen-vai-suoriutuminen/ Eli merkityserot suoriutuminen selviytymisenä vs. suorittaminen "aktiivisenä tekemisenä"?

**Comment by mirmaid** [comment]
^ Kyllä suomeksikin siis suoriutua voi myös eri tasoisesti.

**Comment by mariaforsen** [comment]
Kyllä, ero kielten välillä on kuitenkin se että ruotsiksi presterande ei voi tarkoittaa että pelkästään "selviytyy/selviää" (prestera=ut­föra el. åstad­komma ngt positivt /svenska.se)

**Comment by jarmosaarikko** [comment]
- Wikidatassa on suomenkielisen terminä vain "tietokoneen suorituskyky" ja muut läheiset ovat Suorituskykymittaus, Tulosmatriisi (alias: suorituskykymatriisi), suorituskykypyramidi ja suorituskykyprisma. 
- [Toimintakyky](https://fi.wikipedia.org/wiki/Toimintakyky)
  -  _Toimintakyky voidaan määritellä myös "kyvyksi saada aikaan jokin toiminta" ja suorituskyky vastaavasti voisi tarkoittaa "kykyä saavuttaa jokin päämäärä". Jos toiminta jo on määritelty tavoitteellisena toimintana, näillä kahdella määritelmällä ei ole eroa. Suorituskykyyn liittyy vahvemmin kuin toimintakykyyn toiminnan taso ja tulos._

WIkipediassa on käsitelty mm. 
- _älyllinen suorituskyky_ (vr. älykkyysosamäärä),  KÄYTÄ **psyykkinen tomintakyky**
  - tai kompetenssi?
- _elimistön suorituskyky_, _fyysinen suorituskyky_ (vrt. kunto, ylikunto),  KÄYTÄ **fyysinen toimintakyky**
- erilaisten laitteiden suorituskyky,  KÄYTÄ  **laitteen suoritus-/toimintakyky**  (ei YSOssa), 
  - kuuluu ryhmään 00 Yleistermit, sillä sopii moneen eri ryhmään. 
  - entä _ohjelmiston suorituskyky_?
-  yrityksen, valtion tms. suorituskyky (vrt. bruttokansantuote)  KÄYTÄ **taloudellinen toiminta-/suorituskyky** (ei YSOssa)
   - kuuluu ryhmään 75

**Comment by ilona-x** [comment]
>  YSO-kokous commented on 3 Feb 
> 
> Suorituskyvyn eng. vastine korjattava. Maria päivittää suoritteet. Suoriutuminen: tutkitaan vastaavuus. Vrt. selviytyminen.

suorituskyky oli siis jo ratkaistu, eli nyt käsittelyssä **suoriutuminen**?

**Comment by mirmaid** [comment]
Äkkiseltään näyttää taas siltä, että pitäisi aloittaa siivoamalla pois _suoritteet_-merkitystä, koska sitä on nyt ainakin tulosjoukon alkupäässä paljon. _Suoriutuminen_ ja _menestyminen_ -käsitteissä on myös päällekkäisyyttä.

**Comment by YSO-kokous** [comment]
### Päätökset
siivotaan kuvailuista  
suoriutyminen --> suoritteet, silloin kun on siitä kyse
suoriutuminen  -->  menestyminen (framgång, success) -liittyvät aineistot
Tarkistetaan tilanne sen jälkeen

**Comment by ilona-x** [comment]
**YSO-kokous commented on 3 Feb 2021 • **Suorituskyvyn eng. vastine korjattava.**** 

suorituskyky edelleen performance (physical capacity) eli tätä ei ole vielä korjattu. Tämä tuli taas vastaan, kun käsittelyssä yrityksen suorituskykyä käsittelevä aineisto.

**Comment by mirmaid** [comment]
Suoriutuminen 1433/Melinda

**Comment by mariaforsen** [comment]
Oliko tarkoitus rajata suorituskyky johonkin tiettyyn? Alakäsitteinä on ainakin vielä fyysisiä suorituskykyjä ja myöskään ruotsin vastineessa ei ole mitenkään rajattu fyysistä puolta pois. 
https://fi.wiktionary.org/wiki/suorituskyky 

Suoriutuminen on ainakin ruotsin kannalta nyt se todellinen ongelma tässä. Se pitäisi saada joko poistetuksi tai tarkennetuksi (https://www.kielitoimistonsanakirja.fi/#/suoriutua?searchMode=all > selviytyminen on jo sanastossa)

**Comment by mirmaid** [comment]
^ Mielestäni ei, vaan nyt käsittelyssä vain _suoriutuminen_. Suorituskykyä päivitettävä vain eng. termimuodon osalta.

**Comment by mirmaid** [comment]
Jatketaan erillisessä issuessa, https://github.com/Finto-ehdotus/YSE/issues/10100.

**Comment by fantsby-m** [comment]
_Suorituskyky_ -termiä tarvittaisiin myös mm. kun puhutaan koneiden tai laitteiden suorituskyvystä (esim. väitös "Effect of Manufacturing Processes on Electrical Machine’s Performance"), termi ei voine olla sama kuin nykyinen, joka on ruotsiksi "prestationsförmåga".
