### ISSUE TITLE
Kaisaniemenlahti (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8285]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Kaisaniemenlahti (Helsinki) 

#### Perustelut ehdotukselle   

Kruunuvuorenselältä alkavan salmen osa https://fi.wikipedia.org/wiki/T%C3%B6%C3%B6l%C3%B6nlahti
https://fi.wikipedia.org/wiki/El%C3%A4intarhanlahti 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/2008/Kaisaniemenranta_yleissuunnitelma_web.pdf 

**Termiehdotus Fintossa:** [Kaisaniemenlahti (Helsinki)](http://finto.fi/yse/fi/page/Y508285)

**Comment by mirmaid** [comment]
Merenlahtien sulkutarkenteet?

**Comment by ilona-x** [comment]
Merenlahtia ilman sulkutarkennetta esim.
Mietoistenlahti  http://www.yso.fi/onto/yso/p109988
Mynälahti http://www.yso.fi/onto/yso/p109987

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10903612

**Comment by YSO-kokous** [comment]
Ei sulkutarkennetta. Vakaveden osille ei sulkutarkennetta ellei ole vaaraa sekoittaa johonkin toiseen paikkaan.
Poistetaan sulkutarkenne myös Töölönlahdelta. Korjataan muilta vastaavilta kohdattaessa.

**Comment by YSO-kokous** [comment]
SPARQL-kyselyn tuloksena lahdet, jotka ovat vakaveden osia ja joilla sulkutarkenne :

<http://www.yso.fi/onto/yso/p108299> "Hietalahti (Helsinki)"@fi
<http://www.yso.fi/onto/yso/p109632> "Töölönlahti (Helsinki)"@fi
<http://www.yso.fi/onto/yso/p110531> "Sätöslahti (Viinijärvi)"@fi
<http://www.yso.fi/onto/yso/p127424> "Taivallahti (Helsinki)"@fi
<http://www.yso.fi/onto/yso/p150274> "Säynätlahti (Kuhmoinen)"@fi
<http://www.yso.fi/onto/yso/p188866> "Kellolahti (Kaavi)"@fi
<http://www.yso.fi/onto/yso/p191281> "Sipoonlahti (Sipoo)"@fi

**Comment by mirmaid** [comment]
Annetaanko merialueen osille yläkäsitteeksi myös merialueen nimi?

**Comment by ilona-x** [comment]
Paikkatietoalustalla järven osissa ei näytä olevan mainintaa järvestä. Toki varmaan usemmiten helppo selvittää.
Esim. Kellolahti http://paikkatiedot.fi/so/1000772/10663574

Merialueen osissa näyttäisi olevan maininta siitä, minkä meren merialueen osasta on kyse.
Esim. Sipoonlahti http://paikkatiedot.fi/so/1000772/10014776

**Comment by mirmaid** [comment]
Listataan tähän yläkäsite-ehdokkaat ja pohditaan vielä tarkkuustaso.

**Comment by ilona-x** [comment]
Tässä vielä muutama merenlahti, joilta puuttuu/puuttui paikkalinkki, niin eivät ole tarttuneet sparql-hakuun:
Keikvedenlahti http://www.yso.fi/onto/yso/p147480
Himoistenlahti http://www.yso.fi/onto/yso/p110385

**Comment by mirmaid** [comment]
Gammelbyviken (Loviisa) http://www.yso.fi/onto/yso/p156088

**Comment by mirmaid** [comment]
Sätöslahti on sparql-tuloksista ainoa, joita on vain yksi. Poistetaanko sen tarkenne?

**Comment by mirmaid** [comment]
Onko tarkkuustaso Töölönlahdelle ym. Itämeri (Paikkatietoalusta: Itämeren pääosa-alueen osa) vai Suomenlahti? Tämänhetkinen hierarkia puoltaisi ehkä tarkempaa tasoa.

**Comment by mirmaid** [comment]
Kellolahti - Kaavinjärven osa, mutta ko. järvi ei ole YSO-paikoissa. Tämän tyyppisissä kannattaa ehkä lisätä.

**Comment by mirmaid** [comment]
Sovittiin, että yläkäsitteeksi lisätään tarkin mahdollinen, esim. ennemmin Perämeri kuin Itämeri.

**Comment by tpalonen** [comment]
PÄÄTÖS:
Poistetaan tarkenne Sätöslahti-käsitteeltä.
