### ISSUE TITLE
Töyrynummi (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8286]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Töyrynummi (Helsinki) 

#### Ehdotettu termi ruotsiksi   

Lidamalmen 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/T%C3%B6yrynummi
Töyrynummi (ruots. Lidamalmen) on Suutarilan peruspiiriin ja samannimisen kaupunginosaan kuuluva osa-alue Koillis-Helsingissä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/hkr/julkaisut/Suutarila_raportti_netti.pdf 

**Termiehdotus Fintossa:** [Töyrynummi (Helsinki)](http://finto.fi/yse/fi/page/Y508286)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10903404

**Comment by YSO-kokous** [comment]
Otetaan sanastoon.
