### ISSUE TITLE
magnetismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8288]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[magnetismi](http://www.yso.fi/onto/ysa/Y97232) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään KT magnetiikka? 

#### Perustelut ehdotukselle   

FinMeSH. magnetiikka KT magnetismi http://www.yso.fi/onto/mesh/D008280

LCSHssa molemmat ja näillä RT-suhde:
magnetics http://id.loc.gov/authorities/subjects/sh85079758
magnetism http://id.loc.gov/authorities/subjects/sh85079759 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Tutkitaan vielä lähteitä, esim. sanakirjoja. Käytetäänkö magnetiikka-muotoa tässä merkityksessä.

**Comment by FinMeSHienPaimentaja** [comment]
MeSH:inä (ja sitä myöten FinMeSH:inä, FinMeSH-synonyymit on nyt väärin eli päivitettävä ne) on vain tieteenala-merkityksessä:

Magnetics

Annotation
**the discipline (education, history, etc) only**; use MAGNETIC PHENOMENA for characteristics of magnetic substances; MAGNETIC FIELDS is also available

Scope Note
The study of MAGNETIC PHENOMENA.

See Also
Magnets

https://meshb.nlm.nih.gov/record/ui?name=Magnetics

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä.
