### ISSUE TITLE
reikämittaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8289]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

reikämittaus 

#### Ehdotettu termi englanniksi   

well-logging 

#### Perustelut ehdotukselle   

Löytyy GEOsta http://www.yso.fi/onto/gtk/GTK2015ID3192 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/kv/Geo/Julkaisut/julkaisu_95.pdf 

**Termiehdotus Fintossa:** [reikämittaus](http://finto.fi/yse/fi/page/Y508289)

**Comment by mirmaid** [comment]
18 viitettä Melindassa.

https://en.wikipedia.org/wiki/Well_logging

**Comment by mariaforsen** [comment]
Sv. borrhålsmätning

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
