### ISSUE TITLE
Ala-Arajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8290]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ala-Arajoki 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Maantieteelliset, paikallishistorialliset, ympäristövaikutusyhteenvedot. 

#### Tarkoitusta täsmentävä selite   

Kemijoen vesistöön kuuluva ja Kemijoesta lähtevä ja Värriöjärveen päättyvä joki Savukoskella. 

#### Perustelut ehdotukselle   

Joen nimi. 

**Ehdottajan organisaatio:** Rovaniemen kaupunginkirjasto, maakuntakokoelma. **Termiehdotus Fintossa:** [Ala-Arajoki](http://finto.fi/yse/fi/page/Y508290)

**Comment by mirmaid** [comment]
Sanastossa on Arajoki, Paikkatietoalustalla Yli-Arajoki, joka virtaa Arajärvestä Värriöjärveen ja Ala-Arajoki, joka virtaa Värriöjärvestä Kemijokeen. Wikidata tuntee kaikki kolme erikseen, mutta kyseessä lienee periaatteessa sama joki, joka Värriön kohdalla on muodostanut pienen järven.

Jaetaanko?

**Comment by YSO-kokous** [comment]
Jaetaan kahdeksi ja poistetaan Arajoki sanastosta.
