### ISSUE TITLE
bevasitsumabi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8299]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bevasitsumabi 

#### Ehdotettu termi englanniksi   

bevacizumab 

#### Perustelut ehdotukselle   

Bevasitsumabi on humanisoitu monoklonaalinen vasta-aine ja angiogeneesin estäjä, jota käytetään edenneiden syöpien hoidossa. https://fi.wikipedia.org/wiki/Bevasitsumabi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-5624-43-4 

**Termiehdotus Fintossa:** [bevasitsumabi](http://finto.fi/yse/fi/page/Y508299)

**Comment by HeidiRonkainen** [comment]
Tulikin eteen useita vastaavia, kuten nivolumabi, pembrolitsumabi, reslitsumabi. En tiedä onko sittenkään tarpeen ottaa näitä.

**Comment by mirmaid** [comment]
Bevasitsumabi käytetty 11 kertaa Melindassa, nivolumabi 9, pembrolitsumabi 7, reslitsumabi kerran.

http://www.yso.fi/onto/mesh/D000068258 lienee sama, muita ei FinMeSHissä.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8145

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon bevasitsumabi, nivolumabi, pembrolitsumabi ja reslitsumabi.

**Comment by mariaforsen** [comment]
Sv. 
-bevacizumab 
-nivolumab 
-pembrolizumab 
-reslizumab
