### ISSUE TITLE
heittoaseet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#83]
#### Ehdotettu termi suomeksi

heittoaseet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/ysa/ryhma_67)

**Luontipäivämäärä:** 30.06.1998

**Muokkauspäivämäärä:** 9.7.2001, 16.12.2008

**Voyager-id:** 113940

**Termiehdotus Fintossa:** [heittoaseet](http://finto.fi/yse/fi/page/Y313940)

**Comment by jarmosaarikko** [comment]
MAO/TAO: http://www.yso.fi/onto/mao/p4311 YK aseet
Wikidata: https://www.wikidata.org/wiki/Q1566976  heittoase | kastvapen |  throwing weapon

**Comment by mariaforsen** [comment]
Sv. kastvapen
