### ISSUE TITLE
Ramsinniemi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8300]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ramsinniemi 

#### Ehdotettu termi ruotsiksi   

Ramsöudden 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Ramsinniemi
Ramsinniemi (ruots. Ramsöudden) on metsäinen niemi ja vanha huvila-alue Helsingin Vuosaaren lounaiskulmassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/hel2/ksv/julkaisut/aos_2014-3.pdf 

**Termiehdotus Fintossa:** [Ramsinniemi](http://finto.fi/yse/fi/page/Y508300)

**Comment by YSO-kokous** [comment]
Auktorisoidaan ilman sulkutarkennetta. Yläkäsitteeksi Helsinki, RT:ksi Meri-Rastila ja Vuosaari.
