### ISSUE TITLE
kotiapulaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8301]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotiapulaiset](http://www.yso.fi/onto/ysa/Y96364) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan termin englanninkielinen muoto "household servants" --> "household assistants" 

#### Perustelut ehdotukselle   

Sanan "servant" on vanhahtava ja vahvasti hierarkkinen verrattunan "assistant"-sanaan. KT-muodoksi voisi lisätä myös muodot "household personal assistants", "personal household assistants" ja "private household assistants" 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Tutkitaan ehdotusta ja muutetaan tarvittaessa.
