### ISSUE TITLE
maailmanmestaruuskisat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8302]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maailmanmestaruuskisat](http://www.yso.fi/onto/ysa/Y103295) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

> maailmanmestaruuskilpailut 

#### Perustelut ehdotukselle   

Vastaavia Suomen mestaruuskisat ja Euroopan mestaruuskisat 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by LeKorsu** [comment]
Google-haun perusteella "maailmanmestaruuskilpailut" tosiaan yleisempi kuin "maailmanmestaruuskisat", vaikka oma mutu on, että -kisat on käytetympi. Jos vaihdetaan, varmaan ojaustermi -kisoista. Itse en välttämättä näe tarvetta muutokselle.

**Comment by ilona-x** [comment]
ehdotuksessa mainittujen lisäksi YSOssa arvokisat

**Comment by YSO-kokous** [comment]
Muutetaan maailmanmestaruuskisat käytettävä termi muotoon maailmanmestaruuskilpailut. Sama muutos käsitteille Suomen mestaruuskisat ja Euroopan mestaruuskisat.
