### ISSUE TITLE
rauhanyhdistykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8303]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rauhanyhdistykset 

#### Perustelut ehdotukselle   

Tarvitaan napakkaan ja lyhyeen sisällönkuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pirteissä ja kartanoilla / Raili Ala-Haavisto (9789529423576). 

**Ehdottajan organisaatio:** Oulun kaupunginkirjato **Termiehdotus Fintossa:** [rauhanyhdistykset](http://finto.fi/yse/fi/page/Y508303)

**Comment by jtuohini** [comment]
Tulisiko LT-suhteeksi [**uskonnolliset järjestöt**](http://www.yso.fi/onto/yso/p7545) vai [**uskonnolliset yhteisöt**](http://www.yso.fi/onto/yso/p5605) ja RT-suhteeksi [**lestadiolaisuus**](http://www.yso.fi/onto/yso/p5426) vai jotain muuta?

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Rauhanyhdistys

Käytetty Melindassa n. 50 kertaa.

**Comment by mariaforsen** [comment]
Sv. fridsföreningar

**Comment by YSO-kokous** [comment]
Otetaan käsite sanastoon.
