### ISSUE TITLE
e-äänikirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8307]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[e-äänikirjat](http://www.yso.fi/onto/ysa/Y505327) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Nykyäänikirjat alkavat olla pelkästään verkkoaineistoa. Riittäisikö sanastoon pelkkä äänikirjat-termi, jolla oikeasti löytyisi ao. aineisto? 

#### Perustelut ehdotukselle   

Katsoin Melindasta ja siellä genreä e-äänikirjat oli käytetty 962 kertaa ja äänikirjat 5877 kertaa ja sitten molempia genrejä oli käytetty 601 kertaa. 
Eli tuossa 962 tietueessa näyttäisi olevan yli kolmesataa sellaista e-äänikirjaa, joissa on vain tarkempi genre, joita ei löytyisi sitten tuolla laajemmalla genrellä. Toisaalta voi olla että löytyy myös paljon sellaisia e-äänikirjoja, joiden tietueissa sitten on vain äänikirjat-genre. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Kommentti sisällönkuvailulistalta: En usko että kenellekkään tulisi edes mieleen hakea e-äänikirjat-termillä. Täydellistä kirjastotätien hapatusta.

**Comment by FinMeSHienPaimentaja** [comment]
Samaa mieltä: pelkkä "äänikirjat" ihan ok.

**Comment by mirmaid** [comment]
Kommentti (Kirjastopalvelu): _mietin sitä, miten nämä e-äänikirjat ja (cd-, kasetti-) äänikirjat saa helposti tiedonhaussa eroteltua? Siksi e-äänikirjat ei minun korvissani ole ihan pölhö._

**Comment by mirmaid** [comment]
Kansalliskirjasto:
Siinäpä se, kun ei saa eroteltua erikseen verkkoaineistoa, koska välistä on käytetty molempia genrejä äänikirjat ja e-äänikirjat, välistä pelkkää e-äänikirjat tai pelkkää äänikirjat myös verkossa olevista äänikirjoista. 

Jos käytettäisiin vain äänikirjat-genreä, kaikki löytyisivät ja jos haluaa erotella niin voisi hakea verkkoaineisto-termillä erikseen. Monissa hakupalveluissa voi rajata eri tyyppiset aineiston muilla hakuominaisuuksilla, esim. aineistotyyppi CD tai verkossa saatavilla.

Tai pitäisi varmistaa, että varmasti käytetään molempia genrejä, sekä yleisempää että tarkempaa, kuten sisällönkuvailuopastuksissa on ollut tapana neuvoa. Nuo Melindan tulokset ei vaan rohkaisseet tähän uskomaan. 

Ja kuten sanottu kasetti- ja cd-aineisto on katoavaa tavaraa.

**Comment by mirmaid** [comment]
Kommenttina edelliseen:
- Mielestäni tähän voi vastata vain Mark Twainin sanomaksi väitetyllä lauseella "Uutiset kuolemastani ovat hiukan ennenaikaisia." 
Määrän vähentyminen ei ole sama asia kuin katoaminen. Suomessa julkaistaan koko ajan sekä vinyylilevyjä että C-kasetteja, CD-levyistä nyt puhumattakaan. Yhtä vakuuttavasti voisi väittää, että kirja on katoavaa tavaraa, kun kaikki näpräävät vain kännyköitään.

- Komppaan Heikin viestiä (meidänkin bändiltä on tulossa syksyllä uusi c-kasetti)…. Meidän alan yksi keskeisistä historiallisista totuuksista on, ettei mikään julkaisuformaatti kuole, muita tulee rinnalle ja muistiorganisaatioiden tulee huolehtia näistä kaikista.

**Comment by mirmaid** [comment]
Kansalliskirjasto: Tässä ketjussa oli kuitenkin kyse genrejen e-äänikirjat ja äänikirjat tarpeellisuudesta ja oikeasta käytöstä. Ja siitä että jos niitä ei ole käytetty oikein ja kattavasti, ei kattava hakukaan onnistu.

**Comment by mirmaid** [comment]
Kommentti: Tässä näyttää menevän myös genre ja formaattipuhe sekaisin. Nämä kannattaisi katsoa kuntoon noille uusille formaateille, että kaikki käyttävät samoja termejä.

**Comment by mirmaid** [comment]
Poistetaan e-äänikirjat. Jatketaan keskustelua siitä, voiko e-kirja olla myös äänikirja. Laaditaan tämän perusteella ohjeistus (käytetäänkö toisena terminä e-kirjat vai verkkojulkaisut, vai onko tarpeen käyttää mitään muuta termiä).

**Comment by mirmaid** [comment]
KAUNO-työryhmässä enemmistö oli sitä mieltä, että myös äänikirja voi olla e-kirja.

**Comment by YSO-kokous** [comment]
Poistetaan myös YSOsta e-äänikirjat. Ei perusteluja säilyttää käsitettä YSOssa, kun se on SLM:stä poistumassa. Lisätään ohjaustermi e-äänikirjat KÄYTÄ äänikirjat.

Jatkopohditaan tarvetta muille ohjaustermeille.

**Comment by mirmaid** [comment]
e-äänikirjat KÄ äänikirjat.
