### ISSUE TITLE
Pyhän Ristin kirkko (Kuusamo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8308]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyhän Ristin kirkko (Kuusamo) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Pyhän Ristin kirkko (Kuusamo)](http://finto.fi/yse/fi/page/Y508308)

**Comment by mariaforsen** [comment]
Sv. Kuusamo kyrka
