### ISSUE TITLE
piikkikalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8309]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[piikkikalat](http://www.yso.fi/onto/ysa/Y102116) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennettava: heimo (https://laji.fi/taxon/MX.53196) vai lahko (https://laji.fi/taxon/MX.53323) 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
Melindan viitteissä käsitellyt kalalajit kuuluvat piikkikalojen heimoon. Itseasiassa nykykäsityksen mukaan lahkoon kuuluu hyvin vähän muita kaloja piikkikalojen heimon lisäksi.

**Comment by YSO-kokous** [comment]
Otetaan käytettäväksi termiksi piikkikalat (heimo).
