### ISSUE TITLE
steppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8311]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[steppi](http://www.yso.fi/onto/ysa/Y104410) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ruotsinkielinen KT-muoto "steppdans" 

#### Perustelut ehdotukselle   

Ruotsinkielisen Wikipedian steppiä käsittelevä artikkeli on nimeltään Steppdans [https://sv.wikipedia.org/wiki/Steppdans], joten viittaus siitä muodosta ei kenties olisi haitaksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
