### ISSUE TITLE
genret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8312]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[genret](http://www.yso.fi/onto/ysa/Y102983) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään assosiatiiviseksi käsitteeksi perinteenlajit. 

#### Perustelut ehdotukselle   

Perinteenlajit ovat kansanperinteen genrejä. 

#### Ehdottajan organisaatio   

SKS:n kirjasto

**Comment by tpalonen** [comment]
Hyväksytään ehdotus.
