### ISSUE TITLE
teatteritaide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8313]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[teatteritaide](http://www.yso.fi/onto/ysa/Y99340) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "puheteatteri" 

#### Perustelut ehdotukselle   

Perinteinen käsite erottamaan puhuttua näyttämötaidetta varsinkin lauletusta. Jopa suomenkielinen Wikipedia käyttää tuota: "Perinteisen puheteatterin lisäksi teatterilla on useita muita muotoja." [https://fi.wikipedia.org/wiki/Teatteri] Ja kuten tunnettua, eivät viittausmuodot yleensä ole pahasta… 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
