### ISSUE TITLE
musiikkiteatteri (taiteet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8314]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkiteatteri (taiteet)](http://www.yso.fi/onto/ysa/Y103608) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "musikaaliteatteri" 

#### Perustelut ehdotukselle   

Harvemmin käytetty nimitys kuin musiikkiteatteri, mutta esiintyy esimerkiksi suomenkielisessä Wikipediassa: "Esimerkiksi musikaaliteatterissa esiintyjät myös laulavat." [https://fi.wikipedia.org/wiki/Teatteri] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
