### ISSUE TITLE
sindebelen kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8315]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sindebelen kieli 

#### Perustelut ehdotukselle   

Lisäksi isindebelen kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Linguistic diversity research among speakers of isindebele and sindebele in South Africa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sindebelen kieli](http://finto.fi/yse/fi/page/Y508315)

**Comment by mirmaid** [comment]
Eli käsittääkseni https://en.wikipedia.org/wiki/Sumayela_Ndebele_language & https://en.wikipedia.org/wiki/Southern_Ndebele_language (https://fi.wikipedia.org/wiki/Etel%C3%A4-ndebelen_kieli)

**Comment by mariaforsen** [comment]
Sv. 
-?
-sydndebele ET isiNdebele

**Comment by mirmaid** [comment]
^ Pohjois-ndebele on eri kieli, näitä tässä käsiteltyjä puhutaan molempia Etelä-Afrikassa, pohjois-ndebeleä Zimbabwessa. Sindebele on siis tämä Limpopon provinssissa puhuttava kieli: https://en.wikipedia.org/wiki/Sumayela_Ndebele_language.

**Comment by mirmaid** [comment]
Ei hyväksytty (termimuodon vakiintumattomuus, sekaantumisen riski).
