### ISSUE TITLE
Mustion kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8317]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Mustion kartano](http://www.yso.fi/onto/ysa/Y110681) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mustion linna 

#### Perustelut ehdotukselle   

Museovirasto käyttää

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Mustion_linna

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
