### ISSUE TITLE
Jabal Hārūn

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8319]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Jabal Hārūn 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Petra - the Mountain of Aaron 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Jabal Hārūn](http://finto.fi/yse/fi/page/Y508319)

**Comment by mirmaid** [comment]
Käytetty yli 10 kertaa. 
https://en.wikipedia.org/wiki/Tomb_of_Aaron
https://en.wikipedia.org/wiki/Mount_Hor

**Comment by mirmaid** [comment]
Jabal Haroun & ohjaustermit, myös Aaronin vuori.
