### ISSUE TITLE
elokuvateoriat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#832]
#### Ehdotettu termi suomeksi

elokuvateoriat
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/ysa/ryhma_96)

**Luontipäivämäärä:** 17.12.2002

**Muokkauspäivämäärä:** 17.12.2002, 16.12.2008, 27.04.2009

**Voyager-id:** 122228

**Termiehdotus Fintossa:** [elokuvateoriat](http://finto.fi/yse/fi/page/Y322228)

**Comment by 00501** [comment]
Saattaa olla muille marginaalinen, mutta KAVIn kirjastossa on muutama sata kirjaa aiheesta.

**Comment by mirmaid** [comment]
Melindassa 13 kertaa monikossa, neljä kertaa yksikössä.

https://fi.wikipedia.org/wiki/Elokuvateoria

**Comment by 00501** [comment]
Kyse on elokuvateoriaperheestä. Monikko please. Film theory is a set of scholarly approaches [1] within the academic discipline of cinema studies that questions the essentialism of cinema and provides conceptual frameworks for understanding film's relationship to reality, the other arts, individual viewers, and society at large. Film theory is not to be confused with general film criticism, or film history, though these three disciplines interrelate.

Although film theory originated from linguistics and literary theory [2] it also overlaps with the philosophy of film.[3]

**Comment by mariaforsen** [comment]
Sv. filmteori/er? SAOssa, Nationalencyklopedinissä jne. yksikössä. Monikossa antaa vähän tuloksia ja silloin myös toisenlaisessa merkityksessä.

**Comment by 00501** [comment]
Yksikkö tai monikko. Kunhan termi lisätään.

**Comment by vthuhtala** [comment]
Kaipaa ehdottomasti huomautusta käytöstä

**Comment by AuHo22** [comment]
ok, mikäli muista taidealoista on omat terminsä, muuten tekisin taideteoriat + ala

-tämä oli Outin näkemys, kun keskusteltiin, enkä ole eri mieltä - jos otetaan, niin sitten täytyy tulevaisuudessa hyväksyä yhtä lailla muiden taiteenalojen vastaavat termit, voiko tässä olla hankaluuksia?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/3203, _kirjallisuusteoria_ on KITOssa

**Comment by AuHo22** [comment]
Sekin kai sitten pitäisi olla monikossa?

**Comment by YSA-kokous** [comment]
Seuraava kokous

**Comment by mirmaid** [comment]
Mielestäni tätä käsitellään sekä suomeksi että muilla kielillä yleensä yksikössä, vaikka kyse ei olekaan vain yhdestä yhtenäisestä teoriasta. Jos otetaan, otetaan myös _kirjallisuusteoria_.

**Comment by AuHo22** [comment]
Tällöin pitää mielestäni joitain kirjallisuustermien suhteita YSAssa muokata, esim. poetiikka-termin ohjausterminä on nyt runousopin (ok) lisäksi kirjallisuudenteoria, mutta poetiikka on eri asia kuin kirjallisuusteoria, joka on paljon laajempi. 
Sitten yhtenä esimerkkinä vaikkapa narratologia, joka  on myös osa kirjallisuusteoriaa ja jota käytetään apuvälineenä useassakin kirjallisuuden tutkimussuuntauksessa.

**Comment by 00501** [comment]
Elokuvateoria rantautui suomalaisiin yliopistoihin vasta 1980-luvulla. Elokuvateoriaksi kutsuttu elokuvatutkimuksen alue on ollut rajoiltaan suhteellisen vakiintunut siitä lähtien kun Guido Aristarco ensimmäisenä kartoitti sen historiaa teoksessaan ’Storia delle teoriche de film’ vuonna 1951.
Ks.  Elokuvateorian historia : artikkelikokoelma / toim. Raimo Kinisjärvi, Matti Lukkarila, Tarmo Malmberg
Hki : Like, 1989.

**Comment by YSA-kokous** [comment]
elokuvateoria
