### ISSUE TITLE
enneagrammi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8320]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[enneagrammi](http://www.yso.fi/onto/ysa/Y112238) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Voisi olla hyvä muuttaa käsitteen käytettävää termiä tai tehdä muu merkitystä täsmentävä tarkennus. 

#### Perustelut ehdotukselle   

Termi enneagrammi tarkoittaa useaa eri asiaa, ks. https://en.wikipedia.org/wiki/Enneagram
YSOon käsite on otettu psykologian/persoonallisuuden kontekstissa. Wikipediassa tähän merkitykseen viittaavien artikkelien nimet ovat suomeksi Persoonallisuusenneagrammi, englanniksi Enneagram of Personality ja ruotsiksi Personlighetsenneagrammet. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Taitavat kyllä liittyä toisiinsa.

**Comment by tpalonen** [comment]
Lisätään ohjaustermiksi persoonallisuusenneagrammi. Tarkistetaan lisätäänkö myös englanniksi ja ruotsiksi. Ei muita muutoksia. Linkitetään käsite tähän kohteeseen: https://en.wikipedia.org/wiki/Enneagram_of_Personality
