### ISSUE TITLE
Vanhankaupunginkoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8322]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Vanhankaupunginkoski 

#### Ehdotettu termi ruotsiksi   

Gammelstadsforsen 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Vanhankaupunginkoski
Vanhankaupunginkoski on kulttuurihistoriallisesti merkittävä koski Vantaanjoen suussa Helsingin Vanhankaupunginlahden pohjukassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/liitteet/kaupunkiymparisto/julkaisut/julkaisut/julkaisu-15-18.pdf 

**Termiehdotus Fintossa:** [Vanhankaupunginkoski](http://finto.fi/yse/fi/page/Y508322)

**Comment by mirmaid** [comment]
_Suomalaisten vesistöjen osille annetaan yläkäsitteeksi sekä vesistö että kunta_ - koskille joen nimi? Eli Vantaanjoki, ei Vantaanjoen vesistö.

**Comment by YSO-kokous** [comment]
Tarkennetaan linjausta: "Suomalaisten vesistöjen osille annetaan yläkäsitteeksi sekä vesistö että kunta" täten "Joen osille annetaan yläkäsitteeksi kunnan lisäksi joen nimi. Järven osille annetaan yläkäsitteeksi kunnan lisäksi järven nimi."

Vanhankaupunginkoskelle yläkäsitteeksi Vantaanjoki (ja Helsinki).
