### ISSUE TITLE
tanssiurheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8323]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssiurheilu](http://www.yso.fi/onto/ysa/Y99310) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan RT-suhde asiasanaan "tanssi" LT-suhteeksi 

#### Perustelut ehdotukselle   

Kaikki tanssiurheilu on sekä tanssia että urheilua, joten asiasanojen keskinäisen suhteen pitäisi kuvastaa tätä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Ei muutoksia. Tanssi on YSOssa tulkittu taiteenlajiksi, joten toimintaa (esim. tanssiurheilu) ei voi laittaa sen alakäsitteeksi.
