### ISSUE TITLE
yinjooga

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8324]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yinjooga 

#### Ehdotettu termi ruotsiksi   

yinyoga 

#### Ehdotettu termi englanniksi   

yin yoga 

#### Vastaava käsite muussa sanastossa   

LCSH : yin yoga 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Hallikainen, Jouni: Total yin : terveyttä, tyyneyttä ja tyytyväisyyttä yinjoogalla (9789523730267) 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [yinjooga](http://finto.fi/yse/fi/page/Y508324)

**Comment by mirmaid** [comment]
Kerran Melindassa. Joogan lajeja on sanastossa useita.

https://en.wikipedia.org/wiki/Yin_Yoga

**Comment by mariaforsen** [comment]
Myös SAOssa

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
