### ISSUE TITLE
kuntoportaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8326]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuntoportaat 

#### Vaihtoehtoiset termit ja ilmaisut   

kuntoiluportaat 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/liitteet/kaupunkiymparisto/julkaisut/julkaisut/julkaisu-23-19.pdf 

#### Perustelut ehdotukselle   

https://yle.fi/uutiset/3-9900276
Eri puolille Suomea rakennetaan tai suunnitellaan parhaillaan lukuisia kuntoportaita. Porrastreenaus onkin nyt trendien trendi.
Ehkä porrastreenauksenkin voi jossain vaiheessa ottaa. 

**Termiehdotus Fintossa:** [kuntoportaat](http://finto.fi/yse/fi/page/Y508326)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. motionstrappor ET konditionstrappor, träningstrappor

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon kuntoportaat.
