### ISSUE TITLE
veikkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8328]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[veikkaus](http://www.yso.fi/onto/ysa/Y100124) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi urheiluvedonlyönti ja linkitys Wikidatan sports betting / urheiluvedonlyönti -kohteeseen. Muutetaan englanninkieliseksi vastineeksi sports betting.
https://www.wikidata.org/wiki/Q1506462
Muussa tapauksessa tarkennetaan käsitteen merkitystä muulla tavoin. 

#### Perustelut ehdotukselle   

Käsite viitannee erityisesti urheiluvedonlyöntiin. Sen nykyinen englanninkielinen vastine on football pools. Yläkäsitteenä on rahapelit ja RT:nä lotto. Sen sijaan RT-suhdetta ei ole käsitteisiin arpajaiset tai kolikkopelit.

Football pools lienee hivenen spesifi vastine veikkaukselle. Vrt. Veikkauksen sivuilla rahapelin kohteena voi jalkapallon lisäksi olla mm. jääkiekko, koripallo, pesäpallo, baseball ja tennis. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
YSOssa on myös **vedonlyönti** http://www.yso.fi/onto/yso/p5571 ST toto, eikö urheiluvedonlyönti pitäisi ohjata myös tähän?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**veikkaus**

1. veikkaaminen; arvaus.
Hänen veikkauksensa osui väärään.
2. rahapelejä joissa osanottajat yrittävät ennustaa tiettyjen jalkapallo-otteluiden t. ravikilpailujen tulokset.
Vakioveikkaus.
Raviveikkaus.
Saada veikkauksessa täysosuma, kolmetoista oikein.

**vedon­lyönti**

vedon lyöminen, us. veikkauksen tapaan järjestettynä rahapelinä; vrt. 2. veto.
Vedonlyönti hevoskilpailuissa.

**Comment by tpalonen** [comment]
Aloin miettimään, että tarvitaanko sanastossa erikseen veikkaus ja vedonlyönti. Ovat hyvin päällekkäisiä.

**Comment by mariaforsen** [comment]
Kyllä ne ruotsin kannalta ainakin voi olla molemmat, SAOssakin on molemmat.

**Comment by LeKorsu** [comment]
Ysossa on myös toto vedonlyönnin alakäsittenä (https://finto.fi/yso/fi/page/p6855). Kun veikkaus on rahapelien alakäsitteenä, jonkinlainen järjestely lienee paikallaan. En nyt ehdi miettiä järkevää ehdotusta.

**Comment by ilona-x** [comment]
Lainsäädännössä puhutaan veikkauspeleistä ja vedonlyöntipeleistä, määritelmiä ei kuitenkaan löydy: https://finlex.fi/fi/laki/ajantasa/2016/20161414

**Comment by ilona-x** [comment]
Tästä dokumentista löytyy Veikkaus Oy:n rahapelien sääntöjen lisäksi mainintoja eri rahapelien tyypeistä, tuon mukaan esim. "Lotto on **numeroveikkaus**" https://cms.veikkaus.fi/site/binaries/content/assets/dokumentit/viestinta/2017/veikkaus-oy_n-rahapelien-saannot-smdno_2017_1424.pdf

**Comment by mirmaid** [comment]
Ensimmäistä kertaa ikinä toivoisin joskus pelanneeni jotain rahapeliä :money_with_wings:

**Comment by fantsby-m** [comment]
Veikkaus on vedonlyöntipeli, mutta kaikki vedonlyönti ei ole veikkausta, siinä perinteisessä veikkauksen merkityksessä, jossa veikataan rivi jalkapallo-otteluista (nykyään muutakin urheilua). Vedonlyönnissä panos voi olla periaatteessa vaihteleva, veikkauksessa yhden rivin (esim perinteisesti jalkapallossa 13 ottelua rivillä) hinta on kiinteä, ja rivejä voi sitten tehdä kuinka paljon haluaa. Veikkauksessa siis veikataan pättyykö ottelu kotivoittoon, tasapeliin vai vierasvoittoon. Nykyään on sitten sotkemassa tietysti tulosveikkaus myös... Mutta kaikki ovat mielestäni vedonlyöntipelejä (mitä termiä ei YSOssa ole)

**Comment by YSO-kokous** [comment]
Maria selvittää tippning-käsitteen laajuutta. Voidaanko veikkaus suomeksi määritellä tarkemmin? Mihin kaikkeen halutaan ohjaustermiksi urheiluveikkaus. Tutkitaan vielä veikkaus-termin käyttö Melindassa.

**Comment by LeKorsu** [comment]
Tässä nyt yksi ehdotus (en ole miettinyt kielivastaavuutta ruotsin kanssa):
veikkauspelit (KT veikkaus)
ST urheiluveikkaus
           ST vakioveikkaus (jalkapallo) (KT veikkaus)
           ST raviveikkaus tai toto (toto nyt ysossa) ja toisesta ohjaustermi
ST lotto (KT numeroveikkaus)
veikkauspelien yläkäsitteeksi rahapelit ja siirretään sieltä lotto pois

Mikä tämän suhde on vedonlyöntiin / vedonlyöntipeleihin (tätä ei siis ysossa), ehdotukset tervetulleita
Ja ymmärretäänkö että urheiluveikkaus voisi käsittää myös laukkahevosten ja vinttikoirien tuloksista veikkaamisen / vedonlyönnin? Vai tarvitaanko niille omat ohjaustermit?

Entä tarvitaanko erikseen urheiluvedonlyönti vai voiko sen ohjata urheiluveikkaukseen tai vedonlyöntiin? Tai tarvitaanko sellaista ohjaustermiä laisinkaan?

EDIT: tämä ei nyt näytä sisennystä oikein, kun tämän tallentaa. Ehdotin, että vakioveikkaus ja raviveikkaus/toto olisivat urheiluveikkauksen alla, ei suoraan veikkauspelien alla.

**Comment by mariaforsen** [comment]
https://www.finlex.fi/fi/laki/ajantasa/2001/20011047

Kannatan ehdotusta veikkaus > veikkauspelit (näin myös Finlexissä) -sv. tippningsspel ("...penningspel där spelaren har möjlighet att genom gissning av händelser eller resultat vid idrottstävlingar eller andra tävlingar, inklusive hästtävlingar, eller genom lottning av nummer, märke eller andra igenkänningstecken delta i fördelningen av vinster")

ST ? Tarvitaanko todella "urheiluveikkaus" erikseen? Ei näytä olevan arpajaislaissa ainakaan. Ruotsinnos epävarma.
ST stryktips
ST toto
ST lotto
RT vedonlyönti/vedonlyöntipelit -Tälläkin termillä on oma määritelmänsä (ks. Finlex)

**Comment by mirmaid** [comment]
Näiden määritelmien eroa on kyllä asiaa tuntemattoman vähän vaikea hahmottaa:

2) vedonlyöntipeleillä rahapelejä, joissa pelaajalla on mahdollisuus osallistua urheilu- tai muun kilpailun, myös hevoskilpailun taikka rahapelin tapahtumia tai tuloksia koskevien arvausten perusteella pelaajan asettaman rahapanoksen ja lopputuloksen todennäköisyyttä osoittavan kertoimen tulon mukaisesti määräytyvien voittojen jakoon;

3) veikkauspeleillä muita kuin 2 kohdassa tarkoitettuja rahapelejä, joissa pelaajalla on mahdollisuus osallistua urheilu- tai muun kilpailun, myös hevoskilpailun tapahtumia tai tuloksia koskevien arvausten taikka numeroiden, merkkien tai muiden tunnusten arpomisen perusteella voittojen jakoon;

**Comment by YSO-kokous** [comment]
veikkaus  KÄ veikkauspelit
mietitään sopiva englanninkielinen vastine, jonka kattavuus on sama kuin suomen- ja ruotsinkielisen. ei muita muutoksia
