### ISSUE TITLE
studioäänitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8329]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

studioäänitteet 

#### Ehdotettu termi englanniksi   

studio recordings 

#### Ehdotettu termi ruotsiksi   

studioinspelningar 

#### Vaihtoehtoiset termit ja ilmaisut   

studioäänitykset 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2019026116> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uniarts.finna.fi/Record/uniarts.991361804206249 

#### Perustelut ehdotukselle   

Tarvitaan studioäänitteiden kuvailuun (erotuksena liveäänitteistä). 

#### Tarkoitusta täsmentävä selite   

SLM-sanastoon: studio-olosuhteissa ilman yleisöä tehdyt äänitteet. Yläkäsite SLM-sanastossa: äänitteet (käsite-ehdotuksena). 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [studioäänitteet](http://finto.fi/yse/fi/page/Y508329)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään myös YSOon.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
