### ISSUE TITLE
hengellinen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8330]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hengellinen musiikki](http://www.yso.fi/onto/ysa/Y95327) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Huomautus viittaa vain kristilliseen musiikkiin, pitäisikö termi muuttaa (vrt. hengelliset laulut (kristinusko)) vai huomautus..? 

#### Perustelut ehdotukselle   

Hengellinen=sellainen (tavallisesti aineeton), joka liittyy uskontoon tai henkimaailmaan
Ruotsiksi "andlig musik", joka voi olla myös muuta kuin kristillistä musiikkia.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa tarkenteen "kristinusko" lisäämistä.

**Comment by LeKorsu** [comment]
Eikös meillä ollut taannoin pitkään keskustelua hengellisistä lauluista ja tuleeko tarkenne kristinusko vai ei, ja päädyttiin sulkutarkenteeseen kristinusko ja ruotsiksi andliga sånger (kristendom). Siinä samassa hengessä (heh) pitäisi tähänkin sitten varmaan ottaa tuo kristinusko-tarkenne.

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.
