### ISSUE TITLE
hoivatyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8331]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hoivatyö](http://www.yso.fi/onto/ysa/Y107155) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan tai muutetaan huomautus: vars. lasten ja vanhusten hoitaminen (kotona) 

#### Perustelut ehdotukselle   

Näin ei hoivatyö yleensä ymmärretä, vaan termi on myös käytetty hoidosta joka tapahtuu muualla kuin kotona, ks. Melinda ja Google. Sama ruotsiksi. Tämä huomautus on varmaan lisätty onki-projektissa?

**Comment by tpalonen** [comment]
Poistetaan huomautus.
