### ISSUE TITLE
postilaatikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8333]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[postilaatikot](http://www.yso.fi/onto/ysa/Y116115) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Hei, huomasin, että kirjelaatikot-termi oli ohjattu termiin postilaatikot. Nämä ovat kuitenkin eri asioita: kirjelaatikko on Postin asentama laatikko, johon ihmiset voivat pudottaa kirjeitä ja kortteja kuljetettavaksi eteenpäin. Posti tyhjentää kirjelaatikot ja toimittaa lähetykset lajitteluun ja jatkokuljetukseen. Postilaatikot taas ovat kansalaisten itse pystyttämiä laatikoita, joihin kaikenlainen posti, kuten kirjeet, lehdet ja mainokset, voidaan jakaa vastaanottajalle. Ne rinnastuvat ovissa oleviin postiluukkuihin. Toivottavasti nämä käsitteet erotetaan jatkossa. 

#### Ehdotettu muutos   

Otetaan kirjelaatikot erillisenä käsitteenä

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**kirje­laatikko**
postilaitoksen laatikko vars. kirjeiden postittamista varten.
Kuv.
lehden tms. osasto, jossa on vars. toimituksen vastauksia lähetettyihin kysymyksiin. 

**posti­laatikko**
1. rakennuksen ulkopuolella, tien varressa tm. oleva laatikko, johon vastaanottajan posti jaetaan.
2. yleisk. kirjelaatikko.
3. = sähköpostilaatikko.

**Comment by YSO-kokous** [comment]
Kaivattiin selkeytystä käsitteen merkitykseen käyttäjälle. Tutkitaan tätä, tarvitaanko käsitteitä erikseen, löytyykö aineistoa, joka puoltaisi molempien ottamista. erikseen Pohdittiin myös mahdollisia selventäviä sulkutarkenteita, esim. kirjelaatikko (postin lähetys) ja postilaatikko (postin vastaanotto).

**Comment by mirmaid** [comment]
Melindassa 26 kertaa. Suurimmassa osassa viitteistä kyseessä ovat postin vastaanottamiseen tarkoitetut laatikot, muutamissa ei ihan varmaa kumpaa (vaiko molempia) on tarkoitettu.

**Comment by mirmaid** [comment]
https://www.clasohlson.com/fi/Kirjelaatikko/p/Pr363951000
https://habo.com/fi/valikoima/postilaatikot-kirjeluukut-ja-kyltit/postilaatikot-ja-kirjelaatikot
https://www.quriosa.fi/sailytys/kirjelaatikko-valkoinen.html

**Comment by YSO-kokous** [comment]
Ei muutosta.
