### ISSUE TITLE
kotimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8337]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotimusiikki](http://www.yso.fi/onto/ysa/Y214532) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö tarkenne tms.? 

#### Perustelut ehdotukselle   

Jos termi on todella tarkoitus käyttää vain hausmusiikista, pitäisikö lisätä tarkenne tai, ehkä vielä selvemmin, muuttaa termiä?
YSOn eng. on jo "hausmusik". 
Melindassa käytetty myös muusta kuin "hausmusiikista", esim. Children’s home musical experiences across the world / edited by Beatriz Ilari and Susan Young ja (?): Kotimusiikki : 2. ääni : 1. stämman = Hemmusik. 1 / [toim. Egil Cederlöf] ; [sov. Einar Englund ja Egil Cederlöf]

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa englanninkielisen termin muuttamista LCSH:n mukaiseen muotoon "music in the home".

**Comment by tpalonen** [comment]
Taustaa: Muusa oli sitä mieltä, että kotimusiikki viittaa laajempaan käsitteeseen kuin pelkkään hausmusikiin. Hausmusik-ohjaustermit voivat kuitenkin säilyä, koska ovat suppeampia termejä tälle laajemmalle käsitteelle.

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.
