### ISSUE TITLE
kuulemismenettely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8339]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuulemismenettely](http://www.yso.fi/onto/ysa/Y161724) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan/muutetaan huomautusta tai termiä 

#### Perustelut ehdotukselle   

Huomautus viittaa EU:hun, mutta Melindassa käytetty muussa merkityksessä ja vain 4 kertaa ylipäätään. Vrt esim. https://termipankki.fi/tepa/fi/haku/kuulemismenettely 
Sanastossa on myös kuuleminen (menettely)

**Comment by tpalonen** [comment]
Tarkennettava termimuotoja, jos molemmat pidetään erillään.

**Comment by ilona-x** [comment]
Olisiko mahdollista rajata kuulemismenettely vain Euroopan unioniin? Käytetty Melindassa vain 3 kertaa, joista 2 viitettä on v. 2008 ilmestynyt väitöskirja, jonka perusteella tämä termi on varmaankin vuonna 2008 otettu sanastoon. Lisäksi käytetty kerran virheellisesti. Toki voi pohtia termin tarpeellisuutta, kun käyttö on ollut niin vähäistä. Termi löytyy kuitenkin myös EKSistä.
EKS: Asiasana: | kuulemismenettely 
Korvaa termin: | Euroopan unionin kuulemismenettely

Kuuleminen (menettely) -termin tarkenne on hiukan hämmentävä. Esimerkiksi Tepan mukaan kyseessä on toimenpide.

fi        kuuleminen
sv       hörande

määritelmä
**toimenpide**, jolla asianosaiselle tai asiaan osalliselle annetaan tilaisuus esittää mielipiteensä tai selityksensä viranomaisen käsiteltävänä olevasta hallintoasiasta ja tarvittaessa sellaisista seikoista, jotka saattavat vaikuttaa asian ratkaisuun

huomautus
Asianosaisen kuulemisesta säädetään hallintolaissa (434/2003). Hallintolain mukaan hallintoasiassa asianosainen on se, jonka oikeutta, etua tai velvollisuutta asia koskee. Lastensuojelussa kuultavia voivat olla sekä asianosaiset että asiaan osalliset.

definition
åtgärd genom vilken en part eller delaktig i ärendet ges möjlighet att framföra sin åsikt eller förklaring i ett förvaltningsärende som en myndighet behandlar och vid behov i sådana ärenden som kan påverka hur ärendet löses

anmärkning
Förvaltningslagen (434/2003) innehåller bestämmelser om hörande. Enligt förvaltningslagen är part i ett förvaltningsärende den vars rätt, fördel eller skyldighet ärendet gäller. Inom barnskyddet kan ett hörande omfatta både parterna och personer som är delaktiga i ärendet.

Lähde:  Sosiaalialan tiedonhallinnan sanasto, versio 5.0 (THL, 2019) https://termipankki.fi/tepa/fi/haku/kuuleminen

**Comment by mariaforsen** [comment]
Huom. että termi on ruotsiksi eri riippuen onko EUsta (samrådsförfarande) vai yleisestä merkityksestä kyse. Kannatan rajaamista EUhun tämän termin kohdalla (näinhän on myös tehty EKSissä)

**Comment by mirmaid** [comment]
Kuuleminen (menettely) -käsitteen tarkenne pohjautuu siihen, että myös näistä erilaisista kuulemisista käytetään usein sanaa kuulemismenettely, esim.
https://www.finlex.fi/fi/viranomaiset/foka/2002/20021699
https://peda.net/laukaa/pops/luku7/7-4_erityinen-tuki/7hjok

**Comment by YSO-kokous** [comment]
Muutetaan kuulemismenettelyn käytettävä termi muotoon Euroopan unionin kuulemismenettely, ohjaustermiksi esim. kuuleminen (Euroopan unioni) tms.
