### ISSUE TITLE
sivistykselliset oikeudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8341]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sivistykselliset oikeudet](http://www.yso.fi/onto/ysa/Y110882) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

A) Yhdistetään käsitteeseen kulttuuriset oikeudet tai B) Tarkennetaan käsitteiden merkityseroa ja suhdetta. 

#### Perustelut ehdotukselle   

Sekä sivistyksellisten oikeuksien että kulttuuristen oikeuksien englannin vastine on cultural rights. Sivistykselliset oikeudet -käsitteen yläkäsite on TSS-oikeudet (eli taloudelliset, sosiaaliset ja sivistykselliset oikeudet). Ruotsiksi kyseinen termi on ESK-rättigheter eli ekonomiska, sociala och kulturella rättigheter. Englanniksi ESC rights eli economic, social and cultural rights.

Kulttuurisilla oikeuksilla on nyt RT sivistyksellisiin oikeuksiin. Olisiko parempi, että kulttuuriset oikeudet olisi sivistyksellisten oikeuksien alakäsite? Vrt. esim. Tieteen termipankin (=Pentti Arajärven) määritelmä sivistyksellisille oikeuksille: " yksilölle tai (vähemmistö)ryhmälle annettuja koulutuksellisia, kulttuurisia ja kielellisiä takeita tai näitä aiheita koskevia julkisen vallan velvollisuuksia" (https://tieteentermipankki.fi/wiki/Oikeustiede:sivistykselliset_oikeudet) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Tutkitaan vielä käyttöä ja mietitään onko esim. sivistykselliset oikeudet ja kulttuuriset oikeudet yhdistettävissä.

Vrt. Finlexissä suomen sivistykselliset oikeudet on ruotsiksi kulturella rättigheter.

**Comment by ilona-x** [comment]
**kulttuuriset oikeudet** http://www.yso.fi/onto/keko/p41
"Suppean määritelmän mukaan kulttuurisia oikeuksia ovat esimerkiksi oikeus omaan kieleen ja kulttuuriin, oikeus osallistua kulttuurielämään sekä vähemmistöjen oikeus nauttia omasta kulttuuristaan. Holistisen näkemyksen mukaan kulttuurisiin oikeuksiin kuuluu myös kansalais-, sosiaalisia ja taloudellisia oikeuksia."

**Comment by mariaforsen** [comment]
Ruotsiksi on siis oikeastaan vain "kulturella rättigheter", kuten yllä mainittu Finlexistä (kuten englanniksikin). Kannatan siis yhdistämistä. Ja eihän KEKOssakaan näytä olevan erikseen sivistyksellisiä oikeuksia, (käsitetyyppinä ei ole KEKO, vaan se on ymmärtääkseni YSOn käsite https://finto.fi/keko/fi/page/?clang=en&uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp13892 )

**Comment by mirmaid** [comment]
Yläkäsitteellä _TSS-oikeudet_ ei jostain syystä ole ohjausterminä muotoa _taloudelliset, sosiaaliset ja sivistykselliset oikeudet_. Sivistykselliset oikeudet viitannee ennen kaikkea oikeuteen saada opetusta. https://ihmisoikeudet.net/ihmisoikeudet/taloudelliset-sosiaaliset-ja-sivistykselliset-oikeudet/

**Comment by mirmaid** [comment]
Jos nämä on pakko yhdistää, pitäisikö suomeksi olla sitten _sivistykselliset ja kulttuuriset oikeudet_? Tai sitten kulttuuriset oikeudet KÄ _sivistykselliset oikeudet_? _Kielelliset oikeudet_ on myös sanastossa erikseen, sekin olisi varmaan tämän alakäsite?

**Comment by YSO-kokous** [comment]
sivistykselliset ja kulttuuriset oikeudet KT kulttuuriset oikeudet, sivistykselliset oikeudet
