### ISSUE TITLE
vuorovesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8342]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vuorovesi](http://www.yso.fi/onto/ysa/Y100317) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT laskuvesi, nousuvesi 

#### Perustelut ehdotukselle   

-

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
