### ISSUE TITLE
liiketoimintasuunnitelmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8343]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[liiketoimintasuunnitelmat](http://www.yso.fi/onto/ysa/Y134656) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan huomautus 

#### Perustelut ehdotukselle   

Vrt. miten liiketoimintasuunnitelma määritellään esim. TEPAssa ja Wikipediassa. Ei ole niinkään kyse vaihtoehtoisista suunnitelmista.

**Comment by tpalonen** [comment]
Poistetaan huomautus. Termi on itsessään yksiselitteinen.
