### ISSUE TITLE
luuttusoittimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8344]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luuttusoittimet](http://www.yso.fi/onto/ysa/Y110815) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan huomautus tai mahdollisesti poistetaan termi 

#### Perustelut ehdotukselle   

Sama huomautus kahdella eri käsitteellä: luuttu ja luuttusoittimet: Pyöreäpohjainen, kaksoiskielin varustettu näppäilysoitin. Ontologiassa ei saa olla sama asia tuplana.

**Comment by jtuohini** [comment]
Miten olisi termin muuttaminen muotoon _**kaulaluutut**_ tai _**maljakaulaluutut**_, jotka ovat Erich M. von Hornbostelin ja Curt Sachsin soitinluokituksessa käytettyjä nimityksiä (ryhmä 321.32 ja sen alaryhmä 321.321), niistä varsinkin jälkimmäiseen kun tämä asiasana kuitenkin on viittaavinaan. Nykyinen huomautus on joka tapauksessa virheellinen. Maljakaulaluuttuihin kuuluu sen alla olevan ST-suhteisen asiasanan **luuttu** lisäksi YSOsta myös löytyvät **balalaikka**, **banjo**, **buzuki**, **domra**, **kitara**, **mandoliini**, **sitar** ja **ukulele**.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin "luuttusoittimet" poistamista sanastosta. Tietueiden takautuvissa muutoksissa muutettaisiin muotoon "näppäilysoittimet".

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.
