### ISSUE TITLE
viherjätteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8346]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viherjätteet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.hel.fi/static/liitteet/kaupunkiymparisto/julkaisut/aineistot/aineistoja-03-20.pdf 

#### Perustelut ehdotukselle   

viherjätteitä: nurmijäte, puujäte, risut ja oksat, kitkentäjäte (sisältää myös rikkaruohojen siemeniä), lehtijäte ja vieraskasvilajit
Kasvijäte= yleisten alueiden ylläpidosta muodostuva lehti-, leikkuu-ja kitkentäjäte, puutarhajäte, risut, viherjäte, kannot ym. Puujäte= käsittelemätön puu, pintakäsitelty puu, puurakenteet, maalattu puu, pinnoitettu puu Vieraskasvijäte= esim. jättiputket, jättibalsami, hamppuvillakko. 

**Termiehdotus Fintossa:** [viherjätteet](http://finto.fi/yse/fi/page/Y508346)

**Comment by mirmaid** [comment]
Melindassa kerran yksikössä.

**Comment by ilona-x** [comment]
Esimerkkijulkaisun termit hieman hämmentävät.
Julkaisussa käytetään termiä _viherjätteet (Syntyviä viherjätteitä: nurmijäte, puujäte, risut ja oksat, kitkentäjäte (sisältää myös rikkaruohojen siemeniä), lehtijäte ja vieraskasvilajit.)_
Ja toisaalta mainitaan _"Jäteluokitus kaupungin toimittaman raporttipohjan mukaan: Kasvijäte= yleisten alueiden ylläpidosta muodostuva lehti-, leikkuu-ja kitkentäjäte, puutarhajäte, risut, **viherjäte**, kannot ym."_

Kasvijätteet myös AFOssa http://www.yso.fi/onto/afo/p76

**Comment by mirmaid** [comment]
_Kasvijätteet_ onkin näköjään melko runsaasti käytetty Melindassa.

**Comment by ilona-x** [comment]
^jos tämä otetaan, varmaan vaatii määritelmän, kun ainakin kasvijätteellä saattaa olla jonkinlainen vaara sekoittua biojätteeseen 🤔

**Comment by mariaforsen** [comment]
Sv. växtavfall, grönavfall

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa kasvijätteet. Ohjaustermiksi viherjätteet.
Lisätään ohjaustermi: hakkuujätteet KÄYTÄ hakkuutähteet.

Kasvijätteitä pidettiin merkitykseltään selkeämpänä terminä kuin viherjätteitä.

**Comment by mirmaid** [comment]
Sanastossa on näköjään myös maatalousjätteet: _Jäteluokka, johon kuuluu kasvien viljelystä ja eläinten kasvattamisesta peräisin oleva tuotantojäte._
