### ISSUE TITLE
mineraalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8349]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mineraalit](http://www.yso.fi/onto/ysa/Y97464) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan (liian pitkä ja virheellinen) huomautus. 

#### Perustelut ehdotukselle   

Huomautus vain YSOn puolella. Mineraali ei välttämättä aina ole yhdiste, vrt. https://termipankki.fi/tepa/fi/haku/mineraali
Olisiko esim. Tieteen termipankin määritelmä parempi: "luonnossa esiintyvä, epäorgaanisesti ja geologisten prosessien kautta syntynyt kiteinen aine, jolla on tietty (määrätty, mutta ei vakio) kemiallinen koostumus ja kiderakenne" tai mahdollisesti Wikipedian: "luonnossa kiinteässä muodossa esiintyvä alkuaine tai epäorgaaninen yhdiste, jolla on tietty koostumus ja tavallisesti säännöllinen kiderakenne"

**Comment by tpalonen** [comment]
Vaihdetaan tilalle Tieteen termipankin määritelmä.
