### ISSUE TITLE
uroteelikarsinooma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8350]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uroteelikarsinooma 

#### Ehdotettu termi ruotsiksi   

urotelial cancer 

#### Ehdotettu termi englanniksi   

urothelial carcinoma 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:NBN:fi-fe201801252292 

#### Perustelut ehdotukselle   

Virtsarakon syövistä yleisin on uroteelikarsinooma, joka käsittää 92–99 % tapauksista. 

**Termiehdotus Fintossa:** [uroteelikarsinooma](http://finto.fi/yse/fi/page/Y508350)

**Comment by mirmaid** [comment]
Lääketieteen termit: _uroteelikarsinooma, uroteliaalinen karsinooma | virtsateiden välimuotoisen epiteelin (uroteelin) karsinooma_

_Kasvaimista suuri osa on uroteelin karsinoomia (90 %) (Järvinen 2009). Uroteeli ulottuu aina munaisaltaaseen asti, joten syöpää voi tällöin esiintyä koko virtsateiden alueella (Martikainen 2007, 80). Loput ovat levyepiteeli-karsinoomia sekä adenokarsinoomia ja sarkoomia._ https://www.theseus.fi/bitstream/handle/10024/32926/varkia_rauni.pdf;jsessionid=8AC614D497DB693281979D51B22C3D7D?sequence=1

Ei FinMeSHissä, eikä Melindassa.

**Comment by ilona-x** [comment]
YSOssa on **virtsarakkosyöpä** http://www.yso.fi/onto/yso/p13039

Ehdotuksessa lukee, että "Virtsarakon syövistä yleisin on uroteelikarsinooma, joka käsittää 92–99 % tapauksista.", joten olisiko tämä riittävän tarkka termi. Entä olisiko ohjaustermi uroteelikarsinooma KÄ virtsarakkosyöpä mahdollinen/tarpeellinen?

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermi: uroteelikarsinooma KÄYTÄ virtsarakkosyöpä.

Käsite/termi hyvin paljon päällekkäinen virtsarakkosyövän kanssa.
