### ISSUE TITLE
apteeraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8351]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

apteeraus 

#### Perustelut ehdotukselle   

Yleensä puun katkontaohjeet tulevat kaatokoneen tietokoneelle metsäyhtiöltä, jolle puut on myyty. Katkontaohjeita kutsutaan apteeraus-ohjeiksi.[1]Apteeraus käsittää myös tietokonepohjaisen puun katkaisukohdan määrittämisen, jonka tarkoitus on saada puu mahdollisimman tarkoin hyötykäytettyä.
https://fi.wikipedia.org/wiki/Mets%C3%A4ty%C3%B6kone
https://puuproffa.fi/puutieto/puun-kaataminen/apteeraus/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.metsateho.fi/wp-content/uploads/2015/02/metsatehon_raportti_038.pdf 

**Termiehdotus Fintossa:** [apteeraus](http://finto.fi/yse/fi/page/Y508351)

**Comment by mirmaid** [comment]
AFOssa. Käytetty Melindassa n. 70 kertaa Agriforest-terminä ja 20 kertaa vapaana avainsanana.

_Rungon katkaisukohdan määrittäminen ottaen huomioon puutavaran mitta- ja laatuvaatimukset._

**Comment by mariaforsen** [comment]
Sv. aptering https://sv.wikipedia.org/wiki/Aptering

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
