### ISSUE TITLE
telit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8352]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

telit 

#### Ehdotettu termi englanniksi   

bogie, truck 

#### Ehdotettu termi ruotsiksi   

boggi 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Teli
Teli (engl. bogie tai am.engl. truck) tarkoittaa kahta tai useampaa akselia, jotka on rakennettu yhdeksi kokonaisuudeksi ja liitetty kulkuneuvoon tai siihen liitettävään perävaunuun joko kiinteästi, kääntyväksi tai jousituksella. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.metsateho.fi/wp-content/uploads/2015/02/metsatehon_raportti_023.pdf 

**Termiehdotus Fintossa:** [telit](http://finto.fi/yse/fi/page/Y508352)

**Comment by mirmaid** [comment]
Ei Melindassa. Vaatiiko tarkenteen?

Kielitoimiston sanakirja:
1. tekn.
a. veturin, rautatievaunun tms. runkoa kannattava ja sen suhteen kääntyvä alusvaunu.
b. raskaiden kuorma- t. linja-autojen akselisto, jossa kaksi t. useampi peräkkäinen akseli on kiinnitetty samoihin jousiin.
2. jäälautta t. levymäinen jääkappale.

**Comment by mariaforsen** [comment]
Sv. boggier https://svenska.se/tre/?sok=boggi&pz=1

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa telit (kulkuneuvot).
