### ISSUE TITLE
Tottijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8353]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Tottijärvi (kunta)](http://www.yso.fi/onto/yso/p110574) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Piitäisikö entisen kuntien yläkäsite vaihtaa? Nyt esim. Tottijärven YK Nokia (kaupunki), kun Tottijärvi on liitetty Nokiaan 1.1.1976. Olisiko mahdollista siirtää esim. maakuntien alakäsitteiksi, vai onko tämä mahdollisesti joissain tapauksissa ongelmallista? 

#### Perustelut ehdotukselle   

Nyt entisillä kunnilla on yläkäsitteenä se kunta, johon ko. kunta on liitetty. Nämä yläkäsitteet ovat ilmeisesti tulleet PNR-linkitysten yhteydessä, kun entisille kunnille on lisätty linkki nykyiseen paikkaan (esim. kylä), mutta nämä linkit on sittemmin päätetty poistaa. 

Lisäksi entiset kunnille on päätetty lisätä YSO-paikkoihin edeltäjä-seuraaja -suhde nykyiseen kylään, mutta edeltäjä-seuraaja -linkitys ei ole vielä teknisesti mahdollista 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/5622
YSO-kokous commented on 4 Sep •

PÄÄTÖS:
Kirjataan linjauksiin: Entisen kunnan yläkäsitteeksi laitetaan nykyinen maakunta (tai maakunnat), jonka alueella kyseinen kunta on sijannut.

**Comment by YSO-kokous** [comment]
Toteutetaan linjauksen mukaan.
