### ISSUE TITLE
biosimilaarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8354]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

biosimilaarit 

#### Ehdotettu termi englanniksi   

biosimilar 

#### Ehdotettu termi ruotsiksi   

biosimilar 

#### Perustelut ehdotukselle   

Biosimilaari on biologinen lääke, joka on kehitetty samankaltaiseksi ja vertailukelpoiseksi alkuperäislääkkeenä tunnetun biologisen viitevalmisteensa kanssa. https://www.fimea.fi/laaketurvallisuus_ja_tieto/biosimilaarit
https://fi.wikipedia.org/wiki/Biosimilaari 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-7299-03-6 ja http://urn.fi/URN:ISBN:978-952-7299-02-9 

**Termiehdotus Fintossa:** [biosimilaarit](http://finto.fi/yse/fi/page/Y508354)

**Comment by mirmaid** [comment]
Melindassa biosimilaarit ja biosimilaarilääkkeet muutamia kertoja.

FinMeSH: biosimilaarit lääkkeet

**Comment by FinMeSHienPaimentaja** [comment]
Fimea näyttää käyttävän sekä termejä "biosimilaarit" että "rinnakkaisvalmisteet" ja "rinnakkaislääkkeet".

https://www.fimea.fi/laaketurvallisuus_ja_tieto/biosimilaarit
https://www.fimea.fi/kansalaisen_laaketieto/rinnakkaislaakkeet-ja-laakevaihto

"Biosimilaarit" siis ovat nimenomaan biologisten lääkkeiden rinnakkaislääkkeitä/rinnakkaisvalmisteita.

YSO:sta löytyy nyt jo "rinnakkaisvalmisteet".

"Biosimilaarit" on mielestäni ok (jollei sitä pidetä liian epäsuomenkielisenä terminä, ja jollei käyttöä ole jatkossa liian vähänlaisesti).

**Comment by ilona-x** [comment]
YSO:
**rinnakkaisvalmisteet**  
KT    geneeriset lääkkeet
KT    geneeriset valmisteet
KT    kopiolääkkeet
KT    rinnakkaislääkkeet

FinMeSH:
rinnakkaisvalmisteet KÄ **geneeriset lääkkeet**
rinnakkaisvalmisteet KÄ **biosimilaarit lääkkeet**


YSOssa myös **biologiset lääkkeet**

**Comment by FinMeSHienPaimentaja** [comment]
Jep, FinMeSH-päivitystä tulossa seuraassa vuosittaisessa päivityksessä.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon. Yläkäsitteeksi lisättäneen biologiset lääkkeet ja rinnakkaisvalmisteet.

**Comment by mariaforsen** [comment]
Sv. biosimilarer  https://mesh.kib.ki.se/term/D059451/biosimilar-pharmaceuticals
