### ISSUE TITLE
Koitelaiskaira

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8355]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Koitelaiskaira](http://www.yso.fi/onto/ysa/Y108721) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

oliskohan tämän merkitys mahdollista selvittää, ja sen jälkeen täydentää tietoja 

#### Perustelut ehdotukselle   

Nyt linkattu wikidatassa kohoumaan https://sv.wikipedia.org/wiki/Koitelaiskaira
Paikkatietoalustasta ei löydy Koitelaiskaira -nimellä mitään. Sen sijaan löytyy Sodankylästä:
Koitelainen (tyyppitieto: kohouma) http://paikkatiedot.fi/so/1000772/10780838
Koitelaisenkaira (tyyppitieto: metsäalue) http://paikkatiedot.fi/so/1000772/10780864

https://www.ymparisto.fi/fi-FI/Luonto/Suojelualueet/Natura_2000_alueet/Koitelainen(6297) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Lisätutkitaan.

**Comment by ilona-x** [comment]
Melindan aineistot käsittelevät Koitelaisen/Koitelaiskairan aluetta suojelualueena. Aluetta on aikanaan ehdotettu luonnonpuistoksi/kansallispuistoksi.  

https://fi.wikipedia.org/wiki/Koitelaisenkaira

**Comment by mirmaid** [comment]
Linkitetään metsäalueeseen. KT Koitelaisenkaira
