### ISSUE TITLE
baritonitorvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8356]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

baritonitorvi 

#### Ehdotettu termi englanniksi   

baritone horn 

#### Ehdotettu termi ruotsiksi   

barytonhorn 

#### Vaihtoehtoiset termit ja ilmaisut   

barytontuba [swe] 
barytonitorvi [fin] 
baryton (bleckblåsinstrumenter) [swe – ettei sekoitus samanninimiseen jousisoittimeen tai lauluäänen äänialaan!] 
barytoni (vaskipuhaltimet) [fin – ettei sekoitus samannimiseen jousisoittimeen tai lauluäänen äänialaan!] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vaskipuhaltimet](http://www.yso.fi/onto/yso/p8070) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85011845> 
Wikidata : https://www.wikidata.org/wiki/Q790468 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

. . 

#### Perustelut ehdotukselle   

Finnassa on paljon museoiden kuva-aineistoa, joka esittää baritonitorvea. Monet kuvista kuvailtu väärin esimerkiksi asiasanalla "käyrätorvi" tai "tuuba". Vaikea korjata oikeaksi, jos ei ole täsmällistä vastinetta sanastossa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [baritonitorvi](http://finto.fi/yse/fi/page/Y508356)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta.

**Comment by mariaforsen** [comment]
SAO: barytonhorn

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
