### ISSUE TITLE
Rukolankulma (Urjala)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8357]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Rukolankulma (Urjala)](http://www.yso.fi/onto/yso/p131835) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Paikkatietoalustalta löytyy vain Rukolankulma (Punkalaidun) http://paikkatiedot.fi/so/1000772/10356351

Asutusnimihakemisto:
Rukolankulma 
Kyläkunta
Sijaintikunta: 	Punkalaidun, Urjala
Maakunta: 	Pirkanmaa 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdotettu muutos   

Sanastossa on nyt Rukolankulma (Urjala) http://www.yso.fi/onto/yso/p131835 & Rukolankulma (Punkalaidun) http://www.yso.fi/onto/yso/p131836. Molemmat on otettu sanastoon 30.6.2004. Kyseessä on ilmeisesti kuitenkin sama paikka, joka sijaitsee kahden kunnan rajalla.

**Comment by mirmaid** [comment]
Yhdistetty.
