### ISSUE TITLE
Enontekiö -- Pöyrisjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8358]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Enontekiö -- Pöyrisjärvi](http://www.yso.fi/onto/ysa/Y110025) 

#### Tila   

Käsittelyssä 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Ehdotettu muutos   

mihin tämän olisi tarkoitus viitata, järveen, kylään vai erämaa-alueeseen? 

#### Perustelut ehdotukselle   

Wikidata-linkitys on tehty järveen https://fi.wikipedia.org/wiki/P%C3%B6yrisj%C3%A4rvi
Melindan perusteella aineistoja on ainakin erämaa-alueesta
Termin muodon perusteella kyse ei ole alunperin ainakaan ollut järvestä vaan Enontekiö -- Pöyrisjärvi  -muoto viittaisi kylään

Paikkatietoalustala löytyy:
järvi: http://paikkatiedot.fi/so/1000772/10789388
erämaa-alue: http://paikkatiedot.fi/so/1000772/10897208

**Comment by YSO-kokous** [comment]
Lisätutkitaan. Järvi ja erämaa-alue ovat olemassa kuten myös saamelaisasutus. Ei kuitenkaan ole kylä Paikkatietoalustan mukaan.

**Comment by ilona-x** [comment]
Käytetty Melindassa 24 kertaa

Voisiko auktorisoida ainakin Pöyrisjärven erämaa-alueen, mikä löytyy paikkatietoalustalta http://paikkatiedot.fi/so/1000772/10897208 ja tästä erämaa-alueesta on myös aineistoja, esim. 
https://melinda.kansalliskirjasto.fi/byid/000927118
https://melinda.kansalliskirjasto.fi/byid/013801686

Lisäksi näyttäisi olevan aineistoja myös saamelaisasutuksesta/lapinkylästä, ainakin tämä:
https://melinda.kansalliskirjasto.fi/byid/013280973,

Kaikista viitteistä ei voi olla varma, mistä on kyse, mutta myös järvestä on mahdollisesti viitteitä, esim.
https://melinda.kansalliskirjasto.fi/byid/013287774

**Comment by mariaforsen** [comment]
Kannatan muodossa Pöyrisjärven erämaa-alue https://www.luontoon.fi/poyrisjarvi Sellaisia erämaa-alueita kun on muitakin https://finto.fi/yso-paikat/fi/search?clang=sv&anylang=on&q=*er%C3%A4maa-al* Ja tietty järvenä, kun se löytyy myös Maanmittauslaitoksen lähteissä.

**Comment by mirmaid** [comment]
Muutetaan > Pöyrisjärven erämaa-alue, korjataan siltä osin kuin soveltuu.
