### ISSUE TITLE
Botnia-alue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8360]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Botnia-alue](http://www.yso.fi/onto/ysa/Y198074) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko tämä poistettavissa, käytetty Melindassa 1 kerran, Suomeksi lötyyy googlella todella vähän viitteitä ja ruotsiksi löytyvistä viitteistä osa käsittelee selvästi eri aluetta, kun osumat ovat ruotsalaisilta sivuilta 

#### Perustelut ehdotukselle   

Termin huomautus: Käsittää Keski-Pohjanmaan maakunnan, Oulun Eteläisen seutukunnat ja Pietarsaaren seutukunnan 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta.

**Comment by ilona-x** [comment]
Miten käsitteen poistaminen tapahtuu? 🤔
