### ISSUE TITLE
Haapajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8361]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Haapajärvi](http://www.yso.fi/onto/ysa/Y105369) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

jaettava, kaupunki & järvi 

#### Perustelut ehdotukselle   

"Haapajärvi on kaupunki Keski-Pohjanmaalla ja järvi Evijärvellä. Tarkoitettaessa Haapajärvi-nimistä kylää Evijärvellä käytä muotoa Haapajärvi (Evijärvi)" 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Haapajärvi käytetty yli 3000 kertaa, toivottavasti lähinnä oikeasta kaupungista. https://fi.wikipedia.org/wiki/Haapaj%C3%A4rvi_(t%C3%A4smennyssivu)

**Comment by ilona-x** [comment]
Ehdotuksessa mainittua huomautusta ei näytä olevan YSO-paikoissa.

**Comment by mirmaid** [comment]
Haapajärvi (kaupunki)
