### ISSUE TITLE
Kalajoki (kaupunki) -- Rahja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8362]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kalajoki (kaupunki) -- Rahja](http://www.yso.fi/onto/ysa/Y108544) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Huomautus: Rahja on sekä kylä Kalajoella että saaristo Perämeren keskiosissa 

#### Perustelut ehdotukselle   

tarkennettava koskemaan vain kylää, kun saaristolle on oma käsitteensä http://www.yso.fi/onto/yso/p120567
Korjattava viitteet Melindassa, jos ja kun tätä käytetty saaristosta 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
toinen ehdotus samasta: https://github.com/Finto-ehdotus/YSE/issues/8643

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Rahja

Riittääkö Rahja (Kalajoki : kylä)? Ei tämä saaristostakaan käytettynä kovin kaukaa haettu ole.

**Comment by mirmaid** [comment]
Rahja (Kalajoki : kylä). Poistetaan huomautus ja ohjaustermi.

RT-suhde näiden välille.
