### ISSUE TITLE
samppanja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8364]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[samppanja](http://www.yso.fi/onto/ysa/Y112177) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde "viinit" --> "kuohuviini" 

#### Perustelut ehdotukselle   

"Samppanja on kuohuviini, jota tuotetaan Champagnen maakunnassa Ranskassa." [https://fi.wikipedia.org/wiki/Samppanja] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Tehdään ehdotetusti. Vrt. Alkon sivuilla esim. sanotaan. "Kaikki samppanjat ovat kuohuviiniä, mutta kaikki kuohuviinit eivät ole samppanjaa."
https://www.alko.fi/juoma-ruoka/makujen-maailma/viinien-maailma/samppanjasta-sanottua
