### ISSUE TITLE
mezzosopraanot (laulajat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8365]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mezzosopraanot (laulajat) 

#### Perustelut ehdotukselle   

Vastaava termi on jo muille äänialoille, esim: sopraanot (laulajat) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Helena Matheopoulos: Diiva ; suomennos: Päivi Heikinheimo. 

**Ehdottajan organisaatio:** Jyväskylän kaupunginkirjasto **Termiehdotus Fintossa:** [mezzosopraanot (laulajat)](http://finto.fi/yse/fi/page/Y508365)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. LT naislaulajat.

**Comment by YSO-kokous** [comment]
Hyväksytään Muusan ehdotus.

**Comment by mariaforsen** [comment]
Sv. mezzosopraner (sångare)
