### ISSUE TITLE
slime (askartelu)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8366]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

slime (askartelu) 

#### Perustelut ehdotukselle   

Leikkilimojen varsinainen buumi taitaa olla ohi, mutta yleisissä kirjastoissa asiakkaat edelleen kyselevät slime-reseptej säännöllisesti. Asiasana olisi tarpeen tiedonhaussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. 9789511320807 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [slime (askartelu)](http://finto.fi/yse/fi/page/Y508366)

**Comment by ilona-x** [comment]
Tästä keskusteltu aiemmin issuessa lima (nesteet) https://github.com/Finto-ehdotus/YSE/issues/4502

**Comment by EsaMPKK** [comment]
Slime selityksellä askartelulima.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa slime. Lisätään selventävä määritelmä.
Huom! Myös tämä on slime: https://fi.wikipedia.org/wiki/Slime

**Comment by mariaforsen** [comment]
Sv. slime ET slajm 
SAO Barn: Slime
