### ISSUE TITLE
suojautuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8368]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suojautuminen](http://www.yso.fi/onto/ysa/Y104435) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Sanastossa on termi suojautuminen sv. skyddsåtgärder ryhmissä eläintiede, sodankäynti ja palotoimi. Ruotsinkielinen termimuoto ei sovellu käytettäväksi eläimistä, eikä ihmisistäkään käytettynä ole yhtä laajasti käytettävä kuin suomenkielinen muoto.

Ks. myös https://github.com/Finto-ehdotus/YSE/issues/7692 

#### Ehdotettu muutos   

Tarkennetaan 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Eli suojautuminen oikeastaan "skydda sig", sellaiset muodot eivät kuitenkaan sovi ontologiaan, mutta on kyllä kompromissina tehty, ja niin pitää ehkä tehdä tässäkin tapauksessa (sanastossa on nimittäin paljon muitakin skydd-, suojat, suojaus, suojelu, suojaimet olisivat ruotsiksi kaikki skydd)

**Comment by mirmaid** [comment]
730 viitettä Melindassa. Muutetaanko ruotsiksi _skydda sig_, vai yritetäänkö jakaa tarkempiin käsitteisiin?

**Comment by YSO-kokous** [comment]
Skydda sig
