### ISSUE TITLE
Huhtala (Seinäjoki : kaupunginosa)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8370]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Huhtala (Seinäjoki : kaupunginosa) 

#### Tarkoitusta täsmentävä selite   

http://paikkatiedot.fi/so/1000772/10683063
https://www.wikidata.org/wiki/Q11863744
tyyppitieto: Kaupunkialueen tai taajaman osa

Onko ehdotettu tarkenne ok ja riittävä erottamaan toisesta Seinäjoen Huhtalasta?

Seinäjoella myös Huhtala-niminen kylä (Aiempi sijainti: Ylistaro) http://paikkatiedot.fi/so/1000772/10099162 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Seinäjoen Huhtala : yhdyskuntasuunnittelun ammattikurssi 1 2019 

#### Perustelut ehdotukselle   

tarve kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Huhtala (Seinäjoki : kaupunginosa)](http://finto.fi/yse/fi/page/Y508370)

**Comment by YSO-kokous** [comment]
Auktorisoidaan molemmat Huhtala (Seinäjoki : kylä) ja Huhtala (Seinäjoki : kaupunginosa). Kylälle ohjaustermiksi Huhtala (Ylistaro).
