### ISSUE TITLE
merkit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8371]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[merkit](http://www.yso.fi/onto/ysa/Y97363) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

onko jaettavissa, esim. konkreettisiin ja abstrakteihin tms? Ks. https://github.com/NatLibFi/Finto-data/issues/916
vai onko tässä tapauksessa parempi luoda erikoisratkaisu ruotsiksi, eli "märken och tecken" tms.? 

#### Perustelut ehdotukselle   

Termi on monimerkityksinen, ks. Kielitoimiston sanakirja.

**Comment by mariaforsen** [comment]
Ruotsiksi voidaan siis ratkaista niin että laitetaan "märken och tecken" jos suomeksi halutaan pitää sellaisenaan ilman tarkennusta mihin viitataan. Nykyinen tilanne ei kuitenkaan ruotsin osalta ole ok (sekä "tecken" että "tecken (teckenspråk)), joten toivotaan tietoa siitä miten tähän termiin suhtaudutaan ryhmässä.

**Comment by mirmaid** [comment]
Jos tätä halutaan jakaa pitäisi ainakin ensin varmaan hahmottaa missä ne käsitteiden rajat olisivat. Usein kyse on jonkinlaisista kuvioista, jotka on piirretty tai kirjoitettu tai muuten tuotettu jollekin pinnalle, josta ne voi lukea tai tulkita. Sitten on tämän tyyppisiä myös: [Vanhan rajan metsästäjät](https://melinda.kansalliskirjasto.fi/byid/016648289) - eli voivat olla myös esineitä. Varmaan tämä rajamerkki on kuitenkin ihan käsitteellisesti sama, kuin esim. [puupintaan piirretty merkki](https://melinda.kansalliskirjasto.fi/byid/017435956). 

Alakäsitteistä sellaiset, jotka ovat englanniksi tyyppiä "badges", eli erilaiset rintamerkit yms. pinssit ja lätkät, eivät ole kaikki samanlaisia myöskään ruotsiksi: rintamerkit = rockmärken, kunniamerkit = hederstecken, virkamerkit = tjänstetecken, KT tjänstemärken. Näkisin myös, että ne ovat samaa jatkumoa kuin vaikkapa omistajuutta ilmaisevat rajamerkit - karjan korvamerkit - ihmisen tiettyyn ryhmään kuulumista osoittavat merkit.

Sitten on toki nämä polkupyörämerkit, tavaramerkit jne., joita tulee harmillisesti vastaan artikkelikuvailussa (samoin postimerkit), kun parempaakin termistöä olisi pilvin pimein tarjolla. En sitten tiedä pitääkö tosiaan olla merkit (postimerkit) KÄ postimerkit, merkit (traktorit) KÄ traktorimerkit jne. :sweat:. Mutta nämä siis ovat ruotsiksi myös märken, eli jos jako on se, että merkit pitää rajata niihin pinsseihin, logoihin ym. jotka osoittavat johonkin kategoriaan kuulumista, eikä saa sisällyttää ko. merkin symboloimaa brändiä (eli vain mersun logot, ei mersuja), sama ongelma lienee molemmilla kielillä (eikä tavaramerkit voi olla enää tämän alakäsite).

Joitakin kertoja myös tunnusmerkit, ennusmerkit.

**Comment by mirmaid** [comment]
Muutamia aineistoja ns. "vauvaviittomista", joissa merkit ei sovi. Varmaan ruotsiksikin niihin tulisi kuitenkin tecken (teckenspråk)? Eri lähteissä on vähän erilaisia selityksiä - jossain puhutaan oikean viittomakielen viittomista, jossain tukiviittomista tai sanotaan että ne voi keksiä myös itse.

**Comment by mariaforsen** [comment]
Ruotsiksi käsite rajautuu osittain samalla, mutta osittain eri tavalla, vrt https://svenska.se/tre/?sok=tecken&pz=1 ja https://svenska.se/tre/?sok=m%C3%A4rke&pz=1 sekä https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9563af81f86b61adef2ea1e933b63768&list_id=1&keyword=merkki&word=merkki Eli jos on kyseessä fyysinen, konkreettinen merkki, esim. eläimelle laitettu korvamerkki tai pukuun kiinnitettävä merkki, niin termi on märke, jos taas vain signaali, symboli tms. esim. paperilla oleva kirjoitettu merkki tai käsillä tehty merkki niin se on tecken. 

Hankaluuden takia ajattelinkin että paras ratkaisu saattaa olla että laitetaan sv. märken och tecken -ne kattaa sitten kaikenlaiset merkit, sekä fyysiset, symboliset että kielelliset jne. Mutta sitä muutosta ei tehdä ennen kuin tiedetään ettei suomeksi haluta tehdä jakoa. Nykytilanne on kuitenkin virheellinen, eli toivotaan päätöstä.

**Comment by mirmaid** [comment]
Vaikea keksiä mitä tarkenteita voisi käyttää: merkit (symbolit) todennäköisesti tulkittaisiin täysin päällekkäiseksi symbolit-käsitteen kanssa. Myös (kuviot) olisi varmaan liian suppea. Ja toisaalta tecken voisi kai olla myös abstraktimpi, voiko olla joku "äänimerkki" tai "tunnusmerkki"/"enne" tms. myös tecken - eli vaatisiko myös ruotsiksi tarkenteen?

Toinen taas olisi vielä hankalampi, kun eihän kaikki "märken" ole "esineitä" (esim. tavaramerkit), ja suomeksi ehkä pinssin tai korvamerkin mieltäisi esineeksi, mutta joku paperi- tai kangaspala huonommin, toisaalta taas merimerkit on esineiksi jo vähän suuria. Suppeampia termejä tietysti on usein käytettävissä. Sitten on vielä merkinnät/märkningar -joka on hyvin lähellä tätä, ja mietin että onko se ruotsiksi vähän helpommin esinemäinen kuin suomeksi (esim. korvamerkit).

**Comment by YSO-kokous** [comment]
####Päätös
Ei jaeta käsitettä.
Lisätään tarvittaessa ohjaustermejä ohjaamaan tarkempiin käsitteisiin. 
Lisätään käyttöhuomautus: "Käytä mieluummin tarkempia termejä." tms.
