### ISSUE TITLE
mesipistiäiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8372]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mesipistiäiset](http://www.yso.fi/onto/ysa/Y127146) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritellään mihin viitataan ja lisätään latinankielinen nimi, sekä sen mukaan muunkieliset vastineet 

#### Perustelut ehdotukselle   

Epäselvää mihin viitataan, ks. myös https://github.com/NatLibFi/Finto-data/issues/740

**Comment by mirmaid** [comment]
Korjasin juuri satamäärin viitteitä Melindassa tämän https://github.com/Finto-ehdotus/YSE/issues/7270 ratkaisun jäljiltä, toivottavasti ei tule samat korjattaviksi uudestaan :sweat:. 

https://laji.fi/taxon/MX.289375 - onko tämä tulkinta ok? Wikipediassa viitataan sanalla myös Apoideaan, mutta se on Laji.fi:ssä _mesipistiäismäiset_.

**Comment by YSO-kokous** [comment]
laji.fi:n mukaan latinankielinen nimitys on Antophila. Mietitään ruotsin vastine tämän pohjalta. Wikipediassa ilmeisesti nimitykset yhdistetty väärin.

**Comment by mariaforsen** [comment]
Ruotsiksi ei varmaankaan laiteta Anthophila koska se on tämän mukaan https://www.dyntaxa.se/Taxon/Info/1003983?changeRoot=True joku perhonen.

**Comment by mariaforsen** [comment]
https://www.dyntaxa.se/Taxon/Info/1003983?changeRoot=True (Anthophila on Dynataxan mukaan perhosiin liittyvä joten ruotsin osalta nykyinen vastine jäänee)

**Comment by mirmaid** [comment]
Laji.fi: _Mesipistiäiset eli mehiläiset (Anthophila, aiemmin Apidae) ovat kooltaan vaihtelevia, useimmiten karvaisia ja melko tukevarakenteisia myrkkypistiäisiä (Aculeata)_. Eli onko niin, että dyntaxassa ja laji.fi:ssä käytetään samaa tieteellistä nimeä eri asioista? Jos näin on, ei varmaan voi laittaa myöskään ohjaustermiksi, mutta tilanne on kyllä vähän erikoinen.
