### ISSUE TITLE
moottoriajoneuvovero

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8373]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[moottoriajoneuvovero](http://www.yso.fi/onto/ysa/Y113580) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

käyttövoimavero tai uutena terminä 

#### Perustelut ehdotukselle   

Nykyään termi taitaa olla käyttövoimavero

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/K%C3%A4ytt%C3%B6voimavero

**Comment by ilona-x** [comment]
LIITO: käyttövoimavero http://www.yso.fi/onto/liito/p12941

**Comment by YSO-kokous** [comment]
Otetaan käyttövoimavero erillisenä käsitteenä sanastoon.

**Comment by mariaforsen** [comment]
Sv. drivkraftsskatt
