### ISSUE TITLE
Joki-Hautalampi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8376]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Joki-Hautalampi](http://www.yso.fi/onto/ysa/Y108048) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pitäisikö tätä tarkentaa? 

#### Perustelut ehdotukselle   

Jos kyse Natura2000-alueesta kuuluisi varmaankin YSOn puolelle. https://www.ymparisto.fi/fi-FI/Luonto/Suojelualueet/Natura_2000_alueet/JokiHautalampi(6805) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Ilona tutkii vielä.

**Comment by ilona-x** [comment]
Melindassa vain yksi aineisto (2 tietuetta)

Lintuvesiohjelma puntarissa - linnustoselvityksiä Pohjois-Karjalan lintujärvillä. |n Osa 1, 2, |p Outokummun Sysmäjärven linnusto. Kolme Karjalan kosteikkoa Sääperin, Joki-Hautalammen ja Jouhtenuslammen linnustoselvitykset 1991.
http://hdl.handle.net/10138/234023

**Comment by ilona-x** [comment]
Hautalampi (Rääkkylä): http://paikkatiedot.fi/so/1000772/10733549
Jokilampi (Rääkkylä) tyyppi: Järven osa http://paikkatiedot.fi/so/1000772/10733548

--

"Lintuvesialue muodostuu kapean kannaksen erottamista Jokilammen ja Hautalammen reunoiltaan umpeenkasvaneista altaista."
Lähde: https://www.ymparisto.fi/fi-FI/Luonto/Suojelualueet/Natura_2000_alueet/JokiHautalampi(6805)

"Joki-Hautalampi on suojeltu lintuvesi, se on Natura-aluetta ja Ramsar-kosteikko, ja se kuuluu Rääkkylän lintuvedet -nimiseen FINIBA-alueeseen."
Lähde: https://tiedostot.birdlife.fi/alueet/maali/pklty-maali-raportti.pdf

**Comment by ilona-x** [comment]
Lisätään huomautus, että tarkoittaa lintuvesialuetta/lunnonsuojelualuetta. Ei tehdä vielä muita muutoksia, vaan odotetaan päätöstä, mihin sanastoon suojelualueet jatkossa auktorisoidaan. 

Muutetaan mahdollisesti muotoon "Joki-Hautalammen luonnonsuojelualue"? https://finlex.fi/fi/laki/alkup/2021/20210141
