### ISSUE TITLE
lanttu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8377]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lanttu](http://www.yso.fi/onto/ysa/Y102000) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "räätikkä" ja "räätikäs" 

#### Perustelut ehdotukselle   

Lanttu tunnetaan myös näillä nimillä, joten olisi hyvä saada ne viittausmuodoiksi; ks. esim. https://fi.wikipedia.org/wiki/Lanttu 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
