### ISSUE TITLE
säästöpuu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8378]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

säästöpuu 

#### Vaihtoehtoiset termit ja ilmaisut   

jättöpuu 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/S%C3%A4%C3%A4st%C3%B6puu
Säästöpuu tai jättöpuu on sellainen puu, joka jätetään hakkuussa pystyyn turvaaman metsän biodiversiteettiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.metsateho.fi/wp-content/uploads/2015/02/metsatehon_raportti_053.pdf 

**Termiehdotus Fintossa:** [säästöpuu](http://finto.fi/yse/fi/page/Y508378)

**Comment by ilona-x** [comment]
AFO: **jättöpuut** KT säästöpuut http://www.yso.fi/onto/afo/p7832

**Comment by mirmaid** [comment]
Käytetty Melindassa sekä Agriforest-terminä, että vapaana asiasanana.

**Comment by mariaforsen** [comment]
Sv. sparträd ET överståndare? https://www.skogen.se/glossary/overstandare ET naturvårdsträd 

Olisiko ylispuu KT? https://termipankki.fi/tepa/fi/haku/ylispuu

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa säästöpuut, ohjaustermiksi jättopuut.

Tutkitaan, otetaanko ylispuut omana käsitteenään sanastoon.

**Comment by mariaforsen** [comment]
Kannatan ylispuut=överståndare omana terminä.

**Comment by AuHo22** [comment]
Ylispuu:
Edellisestä puusukupolvesta taimikon tai nuoren metsän päälle jääneet puut ovat ylispuita.
https://www.metsakeskus.fi/metsasanasto#Y-%C3%84

**Comment by mirmaid** [comment]
AFOssa on myös _ylispuut_ ja lisäksi _ylispuusto_. Käytetty 9/5 kertaa.

**Comment by jarmosaarikko** [comment]
> AFOssa on myös _ylispuut_ ja lisäksi _ylispuusto_. Käytetty 9/5 kertaa.
GFDC
KÄYTETTÄVÄ TERMI **ylispuuhakkuu**   
TYYPPI Sanaston käsite
ASSOSIATIIVISET KÄSITTEET GFDC [243 Latvuskerroksen avaaminen](http://dev.finto.fi/gfdc/fi/page/C243)
MUUNKIELISET TERMIT
**Increment fellings** englanti
**ljushuggning** ruotsi
**Lichtungshiebe** saksa
URI http://urn.fi/URN:NBN:fi:au:gfdc:G1721

**Comment by YSO-kokous** [comment]
Otetaan YSOon ylispuut. Ohjaustermi ylispuusto houkuttelisi, mutta onko KOKO-ongelma. Vrt. jalontaminen (https://github.com/Finto-ehdotus/YSE/issues/8410) ja ja kalliohakkaukset (https://github.com/Finto-ehdotus/YSE/issues/8450).
