### ISSUE TITLE
ergosteroli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8379]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ergosteroli 

#### Ehdotettu termi englanniksi   

ergosterol 

#### Ehdotettu termi ruotsiksi   

ergosterol 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.metsateho.fi/wp-content/uploads/2015/02/metsatehon_raportti_084.pdf 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Ergosteroli
Ergosteroli on sienien solukalvon steroli samalla tavalla kuin kolesteroli on eläimillä. 

**Termiehdotus Fintossa:** [ergosteroli](http://finto.fi/yse/fi/page/Y508379)

**Comment by mirmaid** [comment]
FinMeSHissä: http://www.yso.fi/onto/mesh/D004875

**Comment by mirmaid** [comment]
Lääketieteen termit: _steroleihin kuuluva kolesterolin pelkistymistuote; D2-vitamiinin esiaste, joka muuttuu ultraviolettisäteilyn vaikutuksesta ergokalsiferoliksi_
