### ISSUE TITLE
Ylikiiminki -- Reki-Vesala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8380]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Ylikiiminki -- Reki-Vesala](http://www.yso.fi/onto/ysa/Y108120) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Reki-Vesala on entisen Ylikiimingin kunnan länsiosassa Oulussa Pohjois-Pohjanmaalla sijaitseva alue, jonka muodostavat Kiiminkijoen varrella sijaitsevat Rekikylän ja Vesalan kylät. https://fi.wikipedia.org/wiki/Reki-Vesala 

#### Ehdotettu muutos   

Olisiko parempi poistaa tämä ja ottaa sanastoon Rekikylä (Oulu) ja Vesala (Oulu), joiille saisi PNR-linkit?
Käytetty Melindassa vain kerran https://melinda.kansalliskirjasto.fi/byid/004707395 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Reki-Vesala (Oulu) KT Reki-Vesala (Ylikiiminki)
Molemmat PNR-linkit.
