### ISSUE TITLE
Sonkajärvi -- Rutakko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8381]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Sonkajärvi -- Rutakko](http://www.yso.fi/onto/ysa/Y110401) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Rutakko (Sonkajärvi) tarkenteesta huolimatta tällä ei ole kuitenkaan yläkäsitteenä Sonkajärvi, tarvitseeko tarkenteen ja/tai yläkäsitteen? 

#### Perustelut ehdotukselle   

Huomautus:
Rutakko oli nykyisen Sonkajärven alueella vuosina 1872-1906 toiminut laiton kunta. Paikallisesti tätä yhteenliittymää kutsuttiin Rutakon ruhtinaskunnaksi 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Ilona tutkii.

**Comment by ilona-x** [comment]
Käytetty Melindassa 2 kertaa:

1.  Ole se muutos jota etsit / Heikki Rönkkö. https://melinda.kansalliskirjasto.fi/byid/005749685
2.  Raunioruntti ja kivenviha :kansanperinteen suurkerääjä Kaarle Krohn Rutakolla 1885 / Kaarina Ruotsalainen  https://melinda.kansalliskirjasto.fi/byid/000846222

--
viitteessä 1 Rutakko viittaa ilmeisesti Sonkajärven keskustaajamaan.

**Comment by mirmaid** [comment]
Poistetaan.
