### ISSUE TITLE
sisäpiiririkokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8382]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sisäpiiririkokset 

#### Ehdotettu termi englanniksi   

insider crimes 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rikokset](http://www.yso.fi/onto/yso/p125) 

#### Vastaava käsite muussa sanastossa   

SAO : Insiderbrott 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Tarkoitusta täsmentävä selite   

https://www.minilex.fi/a/sis%C3%A4piiritiedon-v%C3%A4%C3%A4rink%C3%A4ytt%C3%B6-on-rikos 

#### Perustelut ehdotukselle   

Sanastossa on aiemmin ollut sv. insiderbrott=organisaatiorikokset (korjataan). Tarvitaan myös tämä insiderbrott=sisäpiiririkokset sanastoon, on käytetty Melindassa esim: 
-En studie av insiderregleringen samt bevisproblem i samband med denna / Johan Hisinger.
-Insiders / av Annelie Östlund och Per Agerman.
-Insiderbrott i Finland : Vem, när, hur och varför? / Max Salomon Jansson. Svenska handelshögskolan, 2012.  
-Insiderhandel. Utmaningar inom insiderregleringen : en jämförande studie mellan Finland och Sverige / Karolina Teir. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sisäpiiririkokset erityisesti syyksiluettavuusarvioinnin näkökulmasta / Anni Laitasalo. 

**Termiehdotus Fintossa:** [sisäpiiririkokset](http://finto.fi/yse/fi/page/Y508382)

**Comment by mirmaid** [comment]
Onko tämä sama kuin sanastossa oleva _sisäpiirikaupat_? https://fi.wikipedia.org/wiki/Sis%C3%A4piirikauppa, ruotsinkielinen sivu on insiderbrott.

**Comment by mariaforsen** [comment]
Ei kai? Insiderbrott on: "Insiderbrott är en form av ekonomisk brottslighet, när någon använder för allmänheten okänd information för egen ekonomisk vinning, ofta i form av aktiehandel eller handel med värdepapper." Ja nationalencyklopedin vielä: "brott som begås när någon som fått insiderinformation för egen del eller för någon annans räkning, genom handel på värdepappersmarknaden, förvärvar eller avyttrar sådana finansiella instrument som informationen rör"

Sisäpiirikauppa on wikipedian mukaan: "julkisesti noteeratun osakkeen myynti- tai ostotapahtuma, jonka suorittaja kuuluu osakkeen arvoon liittyen sen sisäpiiriin"

Myös SAOssa on "insideraffärer" ja "insiderbrott" erillisinä termeinä.
Insiderbrott linkattuna LCSH-termiin Insider trading in securities

**Comment by mirmaid** [comment]
Jos lukee tuota wikipediasivua pitemmälle, todetaan: _Sisäpiirikaupat on kielletty pörssikaupan rahoitusmarkkinoiden uskottavuuden vuoksi. -- Osakkeiden sisäpiirikaupat ovat Ratan mukaan muuttuneet vuonna 2007 aiempaa enemmän järjestäytyneeksi rikollisuudeksi._

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/sis%C3%A4piiririkos
fi        sisäpiiririkkomus ; sisäpiiririkos ; sääntöjenvastainen sisäpiirin kaupankäynnin toimi 
sv       insiderbrott 
en      insider offence ; irregular operation of insider trading 

Lähde: IATE 26.02.2019, Euroopan unioni 
https://iate.europa.eu/entry/result/778546/all

**Comment by LeKorsu** [comment]
https://www.finanssivalvonta.fi/paaomamarkkinat/liikkeeseenlaskijat-ja-sijoittajat/sisapiiriasiat/sisapiirilaisen-kaupankaynti/

**Comment by YSO-kokous** [comment]
Tutkitaan, onko sama asia kuin sisäpiirikauppa. Tarvitaanko molempia käsitteitä erikseen?

**Comment by mirmaid** [comment]
https://www.investopedia.com/terms/i/insidertrading.asp laittomasta ja laillisesta sisäpiirikaupasta. En osaa sanoa puhutaanko suomeksi sisäpiirikaupasta silloin, kun kaupankäyntiin ei liity sisäpiiritiedon väärinkäyttöä.

**Comment by mirmaid** [comment]
Sain tähän kaksi vastausta Kauppakorkeakoulun rahoituksen laitokselta:

1. _Minulle ei tule mieleen sellaisia asiayhteyksiä, joissa sana “sisäpiirikauppa” olisi neutraali. Eli sisäpiiriläisten kaupankäynti sisältää sekä hyväksyttyjä että sisäpiirikauppoja._
_Sana “sisäpiiririkos” saattaisi tuoda lisäinformaatiota siinä mielessä, että jotkut sisäpiirikaupat voivat olla oikeudellisesti tuomittavampia kuin toiset (esim. torkeät, suunnitelmalliset sisäpiirikaupat vs. kaupat, jotka ovat tapahtuneet vahingossa tai lieventävien asianhaarojen vallitessa). Kaikkia sisäpiirikauppoja voisi olla harhaanjohtavaa kutsua rikoksiksi. Juristi osaisi vastata lakiin ja oikeuskäytäntöön pohjautuviin asetteluihin paljon paremmin._

2. _Kaikki sisäpiirikaupat eivät minustakaan ole rikollisia, sillä sisäpiirihän saa toki käydä myös laillisesti kauppaa, ei vaan saa käydä kauppaa tiettyinä aikoina ennen tulosjulkistusta normaaleissa listatuissa yrityksissä. Kyllä sisäpiirikaupoista puhutaan myös ei rikollisten kauppojen yhteydessä, ja seurataan kovalla mielenkiinnolla, sillä näiden katsotaan sisältävän informaatiota._

**Comment by mirmaid** [comment]
Helsingin yliopisto, rahoitusoikeus:
_Sisäpiirikauppa on legaalitermi ja esim. markkinoiden väärinkäyttöasetuksessa ja pörssin sisäpiiriohjeessa selväsanaisesti kielletään sisäpiirikaupat. En ole nähnyt termiä koskaan käytettävän neutraalissa merkityksessä myöskään yleisessä kielenkäytössä. Neutraalissa mielessä itse käyttäisin esim. termiä sisäpiiriläisen kaupankäynti tai sisäpiiriläisen kauppa osakkeella jne._

**Comment by YSO-kokous** [comment]
Hyväksytään ohjausterminä: sisäpiiririkokset KÄ sisäpiirikaupat
