### ISSUE TITLE
Äänekoski-Vaajakoski-vesiväylä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8383]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Äänekoski-Vaajakoski-vesiväylä](http://www.yso.fi/onto/ysa/Y107825) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Melindassa 2 viitettä:
- Äänekoski-Vaajakoski-reitin virtaus- ja vedenlaatumallisovellus : eri kuormittajien vaikutukset reitin fosforipitoisuuksiin 
- Kalataloudelliset velvoitetarkkailut Pohjois-Päijänteellä ja Äänekoski - Vaajakoski -vesireitillä 1980-2000, velvoittavien lakien kehitys / Jarkko Pönkä. 

#### Ehdotettu muutos   

Törmäsin tähän erikoiseen nimimuotoon. Kyseessä viitteiden perusteella vesireitti. Muita vastaavia auktorisoitu YSO-paikkoihin reitti-päätteellä. Vesiväylä-muotoisia termejä ei näytä olevan muita. Pitäisikö tämä muuttaa muotoon Äänekoski-Vaajakoski reitti? Lisäksi reitit linkattu vesistöön, mutta tällä kyseessä olevalla ei ole mitään suhteita. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Otetaan muodossa Äänekosken-Vaajakosken -reitti (tai Äänekosken-Vajaakosken reitti tai Äänekosken-Vajaakosken-reitti). Muut muodot ohjaustermeiksi.

**Comment by YSO-kokous** [comment]
Ks. https://www.kielikello.fi/-/amerikan-matka-ja-nobelin-palkinto-yhdysmerkki-erisnimen-yhteydessa

**Comment by ilona-x** [comment]
Kokouksen jälkeen päädytty julkaisuissa käytettyyn muotoon Äänekoski-Vaajakoski-reitti
