### ISSUE TITLE
MC:t

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8385]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[MC:t](http://www.yso.fi/onto/ysa/Y214559) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan käytettävä termi muotoon räppääjät ja tarkennetaan määritelmää. Ohjaustermiksi voisi myös lisätä rappaajat (musiikki). 

#### Perustelut ehdotukselle   

MC on vanhentunut nimitys. Nykyisin käytetään enemmän nimitystä räppääjä, englanniksi rapper. Saamamme palautteen perusteella MC ei myöskään ole tuttu termi kirjasto-/kuvailijakentällä. Sitä ei osata yhdistää rap-musiikkiin. Finton saama palaute ammattikuvailijalta: "Minulle koko MC:t -termi on täysin vieras ja varmaan niissä hakujärjestelmissä, missä rap+ ei ohjaa tuohon MC:t-termiin myös hankala."

Rap* ei siis tällä hetkellä ohjaa MC:t-termiin ja siitä syystä ajattelin, että tuo rappaajat voisi olla hyvä ohjaustermi. Määritelmässä mainitaan termi Rap-muusikko, mutta se on hieman harhaanjohtava, koska MC:t eivät yleensä soita soitinta vaan ovat laulusolisteja. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa termin muutosta Kielitoimiston sanakirjan suosittamaan muotoon "räppärit". MC:t ohjaustermiksi.

**Comment by tpalonen** [comment]
YSO-kokous voinee kommentoida, otetaanko ohjaustermiksi myös rapparit ja rappaajat -muotoja.

**Comment by mariaforsen** [comment]
Sv. rappare

**Comment by krinay** [comment]
> 
> 
> YSO-kokous voinee kommentoida, otetaanko ohjaustermiksi myös rapparit ja rappaajat -muotoja.

Ei kai ainakaan rappaajia? ;)

**Comment by YSO-kokous** [comment]
Hyväksytään käytettävän termin muutos: räppärit.
YSOn ylläpito päättää sisäisesti, otetaanko tälle myös ohjaustermit rapparit ja rappaajat. Rappaajat-muoto ei saanut YSO-kokouksessa kannatusta.
