### ISSUE TITLE
rocklyriikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8386]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rocklyriikka](http://www.yso.fi/onto/ysa/Y107436) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Erotetaan poplyriikasta, eli poistetaan ohjaustermi poplyriikka ja korjataan huomautus 

#### Perustelut ehdotukselle   

Poplyriikka ja rocklyriikka on eri asioita (sanastossa on myös popmusiikki ja rock erikseen)

**Comment by asormune** [comment]
Käytetäänkö poplyriikasta termiä "sanoitukset" vai "lyriikka"? (poplyriikka on vain ohjaustermi)

**Comment by tpalonen** [comment]
Kontrolloidun sanaston näkökulmasta näen ongelmallisena, että otettaisiin erikseen sanastoon käsitteitä kunkin populaarimusiikin genren lyriikkaa koskien (vrt. glam rock -lyriikka, ska-lyriikka jne). Luulisin, että kuvailussa ja tiedonhaussa olisi parempi käyttää kahta käsitettä: lyriikka + genre. Raplyriikka on näköjään jo livahtanut sanastoon kylläkin. Toisaalta rocklyriikka ja poplyriikka tuntuvat muutenkin hyvin vahvasti päällekkäisiltä ja varmaankin niiden erotus johtaisi siihen, että molempia käytettäisiin rinnakkain samantapaisissa aineistoissa.

Eri asia toki on, onko rocklyriikka paras mahdollinen käytettävä termi käsitteelle.

**Comment by MUUSA-kokous** [comment]
Muusa ei kannata muutoksia tässä vaiheessa.

**Comment by mariaforsen** [comment]
Jos termin pitää tässä sanastossa viitata näihin molempiin olisi varmaan syytä muuttaa käytettäväksi termiksi "pop- ja rocklyriikka" tms.

**Comment by YSO-kokous** [comment]
YSO-kokouksessa toivottiin, että Muusa pohtisi käsitettä vielä uudelleen. Termimuotoa pitäisi hioa: pop-musiikin näkökulmasta (Anna Abreu, Britney Spears jne) ei voida käyttää termiä, joka on muodossa "rocklyriikka", koska Anna Abreu ja Britney Spears eivät edusta rock-musiikkia vaan pop-musiikkia. Optimaalisesti nämä pitäisi saada joko erillisinä käsitteinä tai yhdistettyä jo termimuodossa (ks. Maria Forsenin ehdotus yllä).

**Comment by MUUSA-kokous** [comment]
Muusa päätyi pohdittuaan asiaa kannattamaan erillisiä termejä poplyriikka ja rocklyriikka. Vastaavat muutokset SLM:ään.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by YSO-kokous** [comment]
Erotetaan myös YSOssa rocklyriikka ja poplyriikka omiksi käsitteikseen.
