### ISSUE TITLE
roomalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8387]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[roomalaiset](http://www.yso.fi/onto/ysa/Y121000) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan tai määritellään tarkemmin. 

#### Perustelut ehdotukselle   

Huomautus nyt: Tarkoittaa joko Rooman kaupungin asukasta tai antiikin Rooman valtakunnan kansalaista. Ontologiassa ei saa olla monimerkityksisiä sanoja. Ruotsinkielinen vastine viittaa Rooman valtakunnan kansalaisiin.

**Comment by tpalonen** [comment]
Muutetaan päätermiksi roomalaiset (Rooman valtakunta) TAI antiikin roomalaiset.

**Comment by LeKorsu** [comment]
Peukku roomalaiset (Rooman valtakunta)

**Comment by YSO-kokous** [comment]
Otetaan päätermiksi roomalaiset (Rooman valtakunta). Ohjaustermiksi antiikin roomalaiset.

**Comment by mariaforsen** [comment]
Sv. romerska medborgare > romare (Romerska riket) ET romarinnor
