### ISSUE TITLE
sarjonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8388]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sarjonta 

#### Vaihtoehtoiset termit ja ilmaisut   

pienentäminen, suurentaminen 

#### Tarkoitusta täsmentävä selite   

Käsite tarkoittaa vaatteiden peruskaavojen tai kuositeltujen kaavojen muuttamista eri kokoihin 

#### Perustelut ehdotukselle   

Käsitteelle olisi käyttöä vaatteiden kaavoitusta ja sarjontaa käsittelevän aineiston kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://metropolia.finna.fi/Record/3amk.106615 https://metropolia.finna.fi/Record/3amk.285791 

**Ehdottajan organisaatio:** Metropolia AMK **Termiehdotus Fintossa:** [sarjonta](http://finto.fi/yse/fi/page/Y508388)

**Comment by mirmaid** [comment]
TAO-ontologiassa. KT gradeeraus (kaavat)?

**Comment by mariaforsen** [comment]
Sv. gradering (mönster)

**Comment by YSO-kokous** [comment]
Hyväksytään sarjonta YSOon, otetaan ohjaustermiksi gradeeraus (kaavat).
