### ISSUE TITLE
kanonisointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8390]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kanonisointi](http://www.yso.fi/onto/ysa/Y146213) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selkeytetään merkitysero kaanonit (valikoimat) -käsitteeseen ottamalla pois ryhmä 00 Yleistermit ja mahdollisesti muilla toimenpiteillä, joista enemmän alla. 

#### Perustelut ehdotukselle   

Kanonisointi-käsitteen merkitys on epäselvä. Sillä ei ole määritelmää, huomautusta tai sulkutarkennetta, joten merkitysero kaanonit (valikoimat) -käsitteeseen jää epäselväksi. Kaanon (valikoimat) -käsitteen määritelmä on "Kulttuurin ja/tai taiteen keskeisinä pidetyt teokset esim. jossakin maassa, tai uskonnon pyhien kirjojen kokoelma." 

Kanonisointia on nyt käytetty Melindassa lähinnä pyhimysten kanonisoinnin yhteydessä, mutta jokunen kerta myös ei-uskonnollisessa yhteydessä:
- Canon constitution and canon change in children’s literature / edited by Bettina Kümmerling-Meibauer and Anja Müller.
- Salla Jokela: Kuvitettuja matkoja isänmaahan: matkailu, kuva ja nationalismi Suomessa.
- Att sätta ansikte på samhällen : om kanon och personmuseer / Stefan Bohman.

Ja lisäksi Raamatun kaanonin (=kanonisoinnin) yhteydessä, vaikka kaanonit (valikoimat) lienee määritelmänsä ("uskonnon pyhien kirjojen kokoelma") puolesta se, mitä tällaisissa pitäisi käyttää:
- How the Bible became holy / Michael L. Satlow.
- Who chose the Gospels? : probing the great Gospel conspiracy / C. E. Hill.
- Mitä ovat apokryfikirjat? : apokryfit ja Raamatun kaanon / Tomas Bokedal

Kanonisointi-termi ei itsessään yksiselitteisesti rajaa käsitettä pyhimyksiin tai uskontoon sillä kanonisoida-verbiä käytetään myös taiteen yhteydessä samaan tapaan kuin kaanon-substantiiviakin. Käsitteiden eroa selkeyttäisi, jos kanonisointi-termi muutettaisiin muotoon "kanonisointi (pyhimykset/pyhät henkilöt)" tms ja "kaanon (valikoimat)" -käsitteelle lisättäisiin ohjaustermi "kanonisointi (teokset)" tms.

YSOn ylläpidon kesken keskusteltiin myös vaihtoehdoista, joissa käsitteiden merkitykset rajattaisiin muulla tavoin, esim. niin, että kanonisointi-käsitettä voisi käyttää myös pyhien kirjojen yhteydessä; tällöin se kuitenkin olisi merkitykseltään päällekkäinen kaanonit (valikoimat) -käsitteen kanssa. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Esimerkkejä kanonisoida-verbin käytöstä taiteen yhteydessä:

"Akateemisen taiteen käsitettä käytetään tavallisesti joko puhuttaessa kriittisesti mistä tahansa paikallaan polkevasta, kanonisoidusta tai teoreettisesta taiteesta..." (https://fi.wikipedia.org/wiki/Akateeminen_taide)
"[Taidepoliisit] myös valitsevat ja kanonisoivat todellisten taiteilijoiden kirjon ja luovat itselleen hyväksyttyjen listan." (https://www.veikkaus.fi/fi/yritys#!/article/inhimillisia-uutisia/julkaisut/2018/06/kuka-on-oikea-taiteilija)
"Kun on täydellinen vapaus itsensä ja taiteen suhteen, ei tarvitse ajatella, että tämä on kanonisoitua taidetta, että tätä pitää ymmärtää." (https://suomentaideyhdistys.fi/taiteessa-vaeltelija-kulkee-kohtaamisesta-toiseen-ja-kiikaroi-katseen-rajojen-yli/)
"Osaamistavoitteet: Opiskelijan ymmärtää länsimaisen taiteen kaanonin muotoutumista, tuntee kanonisoituja teoksia sekä taidehistorian keskeistä terminologiaa" (https://korppi.jyu.fi/kotka/course/student/generalCourseInfo.jsp?course=207444)

**Comment by tpalonen** [comment]
Asiaan liittyy myös kanonisointi-käsitteen Wikidata-linkitys. Tarjolla linkitettäväksi olisi pyhimysten kanonisointiin liittyvä Wikidata-kohde (https://www.wikidata.org/wiki/Q51621), mutta YSOn käsitteen tarkka merkitys olisi ensin hyvä selvittää.

**Comment by tpalonen** [comment]
Sisäisen YSO-kokouksen päätös: uskonnollisten ja muiden teosten kanonisointi (sekä näin muodostava kaanon) on eri asia kuin pyhimysten kanonisointi ja nämä pitäisi jatkossakin pitää erillään. Selkeyden vuoksi vaihdetaan kanonisoinnin päätermiksi pyhimykseksi julistaminen. Mietitään vielä ohjaustermejä tälle ja kaanonin (valikoimat) -käsitteelle.

**Comment by mirmaid** [comment]
Millaista onkaan äärikanonisointi: _2020-luvun silmin otsikossa rinnastuvat äärikanonisoitu taiteilija ja tuhoisana pidetty huumausaine._ https://www.hs.fi/nyt/art-2000006644409.html

**Comment by YSO-kokous** [comment]
Muutetaan kanonisointi muotoon pyhimykseksi julistaminen, ohjaustermiksi kanonisointi (pyhimykset). Lisätään myös ohjaustermiksi: kanonisointi (teokset) KÄYTÄ kaanonit (valikoimat).

**Comment by mariaforsen** [comment]
Sv. helgonförklaring
