### ISSUE TITLE
värilliset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8391]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[värilliset](http://www.yso.fi/onto/ysa/Y107262) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ei-valkoihoiset / people of color -merkityksen lisäksi värilliset-termi viittaa myös tiettyyn eteläafrikkalaiseen etniseen ryhmään. Onko sekaannuksen vaaraa? 

#### Perustelut ehdotukselle   

Ks. https://fi.wikipedia.org/wiki/V%C3%A4rilliset 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Linkitetään YSOn käsite Wiki-kohteeseen Person of Color. Ei muita toimenpiteitä.
