### ISSUE TITLE
kartastot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8392]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kartastot](http://www.yso.fi/onto/ysa/Y95911) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "karttakirjat" sekä YSOon että SLM:ään 

#### Perustelut ehdotukselle   

Kartastoista puhutaan usein karttakirjoina. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.

**Comment by mirmaid** [comment]
Lisätään YSOa vastaavat ohjaustermit, LCGFT atlases.
