### ISSUE TITLE
palveluliikenne

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8394]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[palveluliikenne](http://www.yso.fi/onto/ysa/Y113210) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Palveluliikenne määritellään Wikipediassa eri tavalla kuin YSOssa. Ongelma vaiko ei? 

#### Perustelut ehdotukselle   

Ks. https://fi.wikipedia.org/wiki/Palveluliikenne 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
"Palveluliikenne (servicetrafik; service transport). Joukkoliikennettä, joka on suunniteltu ja toteutettu erityisesti iäkkäiden ja vammaisten tai muiden erityisryhmien tarpeet huomioon ottaen. Palveluliikenne on kaikille avointa liikennettä. Linjan reitiltä voidaan tehdä poikkeamia asiakkaiden tarpeiden mukaan, tai liikennöinti voi perustua kokonaan ennakkotilausten pohjalta muodostettaviin reitteihin."

Lähde: Henkilöliikenteen palveluiden sanasto http://urn.fi/URN:978-952-317-556-3

**Comment by tpalonen** [comment]
Viitannevat samaan käsitteeseen, vaikka määritelmät ovatkin erilaiset. Linkitetään kuitenkin kyseiseen Wiki-kohteeseen.
