### ISSUE TITLE
selkokieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8395]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[selkokieli](http://www.yso.fi/onto/ysa/Y98774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Olisiko selkoteksti KT? 

#### Perustelut ehdotukselle   

Ruotsiksi selkokieli on ALLFOssa ollut =lättläst text. Jos suomeksi ei mielletä että selkoteksti voisi olla tämän KT niin täytyy varmaan muuttaa lättläst text > lättläst språk. 
Huomautus on nyt: Selkokieli on sisällöltään, sanastoltaan ja rakenteeltaan yleiskieltä luettavammaksi ja ymmärrettäväksi mukautettua kieltä niitä ihmisiä varten, joilla on vaikeuksia lukemisessa tai/ja ymmärtämisessä.

**Comment by YSO-kokous** [comment]
selkoteksti KÄYTÄ selkokieli
selkotekstit KÄYTÄ selkoaineistot
