### ISSUE TITLE
lastentarhanopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8396]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lastentarhanopettajat](http://www.yso.fi/onto/ysa/Y96777) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan tämä asiasanaksi "varhaiskasvatuksen opettajat". Laitetaan "lastentarhanopettajat" ohjaustermiksi, ja huomautus että uusi asiasana on otettu käyttöön 2020, sitä ennen käytetty "lastentarhanopettajat". 

#### Perustelut ehdotukselle   

Ammattinimeke muuttunut 2018 voimaan tulleen varhaiskasvatuslain myötä: https://www.sool.fi/opettajaksi/varhaiskasvatuksen-opettaja/ 

#### Ehdottajan organisaatio   

Jyväskylän yliopisto / Avoimen tiedon keskus, kirjasto

**Comment by mariaforsen** [comment]
Sv. lärare inom småbarnspedagogik

**Comment by YSO-kokous** [comment]
Päätermiksi varhaiskasvatuksen opettajat, ohjaustermiksi lastentarhanopettajat.
