### ISSUE TITLE
auraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8397]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[auraus](http://www.yso.fi/onto/ysa/Y94803) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan lumiauraus ja muu auraus. Tai rajataan tämä käsite lumiauraukseen ja lisätään kyntö-käsitteelle ohjaustermi auraus (kyntö). 

#### Perustelut ehdotukselle   

Nykyisin käsite on monimerkityksinen. Lumiauraus ja auran käyttö maanviljelyksessä ovat merkityksiltään aika kaukana toisistaan. Näistä ei käytetä englanniksi ja ruotsiksi samaa termiä. Tiedonhakija tuskin on kiinnostunut molemmista merkityksistä samalla kertaa. Auraus on tällä hetkellä LCSH-linkattu Ploughing-käsitteeseen, joka ei viittaa lumiauraukseen.

Ks. https://fi.wikipedia.org/wiki/Aura_(maanviljely)
https://fi.wikipedia.org/wiki/Auraus 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Viitteissä _auraus_ viittaa yleensä lumen auraukseen. Maanmuokkausta nimitetään auraukseksi toisinaan kun kyse on metsänhoidosta, maanviljelyn yhteydessä käytettävä termi on aina _kyntö_.

https://www.maaseuduntulevaisuus.fi/metsa/auraus-sopii-hyvin-paksun-kuntan-maille-1.163021

**Comment by LeKorsu** [comment]
Kannatan aurausta ilman etuliitettä lumenaurauksena ja auraus (maatalous [tai kyntö]) KÄ kyntö.  Mutta pitääkö metsänhoitokin huomioida, en osaa ottaa kantaa.
MOT:n mukaan lumenauraus snöröjning ja auraus & kyntö plöjning, joten ruotsin ja englanninkielisiä termejä pitänee tosiaan vaihtaa.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon lumenauraus, ohjaustermiksi lumiauraus, lumen auraus, auraus (lumenauraus). Mietitään käsitteen ryhmät ja suhteet tämän pohjalta. Poistetaan käytöstä auraus-käsite.

**Comment by mariaforsen** [comment]
Sv. snöplogning 
ALLFO: snöröjning=lumityöt
