### ISSUE TITLE
intuitionismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8399]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[intuitionismi](http://www.yso.fi/onto/ysa/Y106357) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Wikipediassa intuitionismi viittaa matematiikkaan. YSOn käsite ilmeisesti viittaa kuitenkin eettiseen intuitionismiin. Wikipediassa vastaava käsite on puolestaan nimeltään eettinen intuitionismi. Pitäisikö YSOn käytettävää termiä tarkentaa? Asia vaikuttaa mm. käsitteen linkitykseen ja kielivastineisiin. 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Intuitionism
https://en.wikipedia.org/wiki/Ethical_intuitionism

Obs! Tieteen termipankki käsittelee eri intuitionismeja yhteisesti: "eettinen, matemaattinen tai esteettinen näkemys, jonka mukaan jotkut perusasiat tai periaatteet ovat mentaalisina konstruktioina välittömästi varmoja ilman formaalista todistamista tai johtamista". http://tieteentermipankki.fi/wiki/Estetiikka:intuitionismi 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Lisätään käsitteelle matematiikan ryhmä. Mahdollisesti myös ryhmä 90 Taide yleensä. Muutetaan LCSH-linkki narrowmatchiksi. Ei linkkiä Wikidataan, koska siellä ei tarkkaa vastinetta.
