### ISSUE TITLE
halkaisija

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8400]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

halkaisija 

#### Ehdotettu termi englanniksi   

diameter 

#### Ehdotettu termi ruotsiksi   

diameter 

#### Vaihtoehtoiset termit ja ilmaisut   

läpimitta, poikkileikkaus 

#### Perustelut ehdotukselle   

Halkaisija tarkoittaa suomen yleiskielessä useita erilaisia asioita. Esineen, kuten esimerkiksi putken tai tukkipuun, halkaisijalla tarkoitetaan suurinta poikkileikkauskuvion mittaa. Halkaisija voi myös tarkoittaa yleensä suoraa katkaisukohtaa, joka jakaa esineen kahteen yhtäsuureen osaan, yhtä painavaan osaan, yhdenmuotoisiin osiin tai jonkin muun kriteerin perusteella yhtäläisiin osiin. Pituusmitan sijasta halkaisija voi tarkoittaa myös janaa, joka lävistää kuvion tietyllä tavalla.
Halkaisija tarkoittaa myös mitattua läpimittaa.
https://fi.wikipedia.org/wiki/Halkaisija

Kyseisessä julkaisussa läpimittana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.metsateho.fi/wp-content/uploads/2015/02/metsatehon_raportti_152.pdf 

**Termiehdotus Fintossa:** [halkaisija](http://finto.fi/yse/fi/page/Y508400)

**Comment by mirmaid** [comment]
Ei Melindassa. Sen sijaan _halkaisijat_ on käytetty joitakin kertoja puun halkaisuun käytettävästä laitteesta.

AFOssa on _läpimitta_, jota on käytetty runsaasti Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa läpimitta, ohjaustermiksi halkaisija.

**Comment by mariaforsen** [comment]
Sv. diameter ET genomskärning
