### ISSUE TITLE
varmenteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8401]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[varmenteet](http://www.yso.fi/onto/ysa/Y117697) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan loppuosa huomautuksesta 

#### Perustelut ehdotukselle   

Ks. englanninkielinen ja ruotsinkielinen vastine. Termillä saa olla vain yksi merkitys ontologiassa.

**Comment by tpalonen** [comment]
Tutkitaan, onko käyttö rajautunut vain digitaalisiin varmenteisiin. Pohditaan suomen, ruotsin ja englannin käytettävät termit sekä määritelmä vielä tältä pohjalta.

**Comment by ilona-x** [comment]
Käytetty Melindassa vain digitaaliset varmenteet -merkitykisessä.

Kielitoimiston sanakirja:
**varmenne**
tietoverkkojen käytössä esim. verkkopalvelujen yhteydessä käytettäviä tunnisteita, joilla todennetaan tiedonsiirrossa käytetyt palvelimet, palvelun tarjoajan identiteetti tms. 

Myös Tepassa kaikki määritelmät viittaavat digitaalisiin varmenteisiin.
https://termipankki.fi/tepa/fi/haku/varmenne

**Comment by ilona-x** [comment]
Laki viranomaisten sineteistä ja leimoista https://www.finlex.fi/fi/laki/ajantasa/2009/20090019
"Tässä laissa säädetään ylimpien valtioelinten, valtion viranomaisten ja Suomen Pankin asiakirjojen oikeellisuuden varmentamiseen käytettävistä sineteistä ja leimoista."

**Comment by mariaforsen** [comment]
Sanastossa on leimat ja sinetit erikseen, ne riittävät varmaan kattamaan sitä aluetta.

**Comment by YSO-kokous** [comment]
Säilytetään pääterminä varmenteet, ohjaustermiksi digitaaliset varmenteet. Termiä on käytetty käytännössä pelkästään merkityksessä digitaaliset varmenteet. Vaihdetaan määritelmäksi Kielitoimiston sanakirjan määritelmä.
