### ISSUE TITLE
varovaisuusperiaate

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8402]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[varovaisuusperiaate](http://www.yso.fi/onto/ysa/Y184957) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan tai muutetaan huomautus 

#### Perustelut ehdotukselle   

Käytetään myös muilla alueilla (esim. talous, terveys jne) kuin ympäristöoikeudessa. Eli poistetaan huomautus että voidaan käyttää sovellettuna millä tahansa alueella (sama perusmerkitys) tai mahdollisesti laajennetaan huomautusta. 
Ks. myös https://termipankki.fi/tepa/sv/s%C3%B6k/varovaisuusperiaate

**Comment by tpalonen** [comment]
Tutkitaan, löydetäänkö yleispätevää määritelmää.

**Comment by mariaforsen** [comment]
http://fi.opasnet.org/fi/Varovaisuusperiaate -Voisiko olla tämänkaltainen määritelmä?
https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=asy00609

**Comment by mirmaid** [comment]
_The precautionary principle (or precautionary approach) is a broad epistemological, philosophical and legal approach to innovations with potential for causing harm when extensive scientific knowledge on the matter is lacking. It emphasizes caution, pausing and review before leaping into new innovations that may prove disastrous._ https://en.wikipedia.org/wiki/Precautionary_principle

**Comment by mirmaid** [comment]
Yhdistellen jotain sellaista kuin:
_Periaate, jonka mukaan tieteellisten todisteiden puuttumista (uhan toteutumisesta) ei tule käyttää syynä uhan torjumiseen tai sen vaikutusten vähentämiseen tähtäävien toimien lykkäämiseen, kun seuraukset uhan toteutumisesta ovat vakavia tai palautumattomia._

**Comment by YSO-kokous** [comment]
Periaate, jonka mukaan tieteellisten todisteiden puuttumista uhan toteutumisesta ei tule käyttää perusteena lykätä toimia uhan torjumiseksi tai sen vaikutusten vähentämiseksi, kun seuraukset uhan toteutumisesta ovat vakavia tai palautumattomia.
