### ISSUE TITLE
vesiarvo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8403]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vesiarvo](http://www.yso.fi/onto/ysa/Y117701) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT lumen vesiarvo tai päätermin muutos 

#### Perustelut ehdotukselle   

Vesiarvo voi periaatteessa viitata myös muuhun. 
https://fi.wikipedia.org/wiki/Lumen_vesiarvo

**Comment by LeKorsu** [comment]
Yhteiskuntatieteilijä/humanistipeukkua päätermin muuttamiseksi lumen vesiarvoksi
https://tieteentermipankki.fi/wiki/Nimitys:lumen_vesiarvo

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi lumen vesiarvo.
