### ISSUE TITLE
americana

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8405]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

americana 

#### Ehdotettu termi ruotsiksi   

americana 

#### Ehdotettu termi englanniksi   

americana 

#### Vastaava käsite muussa sanastossa   

americana (Music) : https://lccn.loc.gov/sh2016002283 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarvitaan (ainakin SLM) tarkentamaan ja helpottamaan americana-musiikkia esittävien artistien musiikin (äänitteet/nuotit) kuvailua. Määritelmä Wikipediassa:Americana (also known as American roots music) is an amalgam of American music formed by the confluence of the shared and varied traditions that make up the musical ethos of the United States, specifically those sounds that are merged from folk, country, blues, rhythm and blues, rock and roll, gospel, and other external influences. Americana, as defined by the Americana Music Association (AMA), is "contemporary music that incorporates elements of various mostly acoustic American roots music styles, including country, roots rock, folk, gospel and bluegrass resulting in a distinctive roots-oriented sound that lives in a world apart from the pure forms of the genres upon which it may draw. While acoustic instruments are often present and vital, Americana also often uses a full electric band. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. Olli Haavisto: Collisions ; Ninni Poijärvi, Early James, Patty Griffin, Roseanne Cash, Tuomo & Markus... 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [americana](http://finto.fi/yse/fi/page/Y508405)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. Tuomas P. laatii määritelmän.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by mariaforsen** [comment]
Sv. americana (musik) https://sv.wikipedia.org/wiki/Americana

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by tpalonen** [comment]
Määritelmäehdotus:
"Pohjois-amerikkalaisen musiikkiperinteen lajeista kuten kantrista, bluesista, gospelista, bluegrassista ja rock and rollista ammentava perinnetietoinen musiikkityyli, jossa käytetään usein sähkösoittimien sijaan tai ohella akustisia soittimia."

**Comment by MUUSA-kokous** [comment]
Muusan muokkaama määritelmäehdotus: "Pohjois-amerikkalaisen musiikkiperinteen lajeista kuten kantrista, bluesista, gospelista, bluegrassista ja rock and rollista ammentava musiikkityyli, jossa käytetään usein sähkösoittimien sijaan tai ohella akustisia soittimia."

**Comment by tpalonen** [comment]
YSO-ylläpito suosittaisi vahvasti sulkutarkenteen lisäämistä suomen vastineeseen. Englannin ja ruotsin vastineisiin tämä joka tapauksessa lisätään. Eli ehdotettu muoto olisi siis _americana (musiikki)_. Perusteluna se, että americana-termi viittaa muuhunkin,  pohjoisamerikkalaiseen kulttuuriin ja esineistöön. LCSH:ssa americana sellaisenaan viittaa nimenomaan esineistöön:  https://id.loc.gov/authorities/subjects/sh85004426.html
Ks. myös: https://fi.wikipedia.org/wiki/Americana_(kulttuuri)

Kaipaamme Muusan kantaa tähän.

Ps. Hot tip: Kun yhdistät kinkkua, ananasta ja sinihomejuustoa, saat americana-pizzan!

**Comment by asormune** [comment]
Tulisiko sulkutarkenne myös SLM-termille?

**Comment by tpalonen** [comment]
Muusa voi kommentoida SLM:nkin kannalta. YSOn ylläpidossa kuitenkin uumoiltiin, että SLM:n puolella ei liene ihan samanlainen tarve sulkutarkenteelle, kun tuo muunlainen americana (esineet yms) tuskin olennaista SLM:n kannalta.

**Comment by MUUSA-kokous** [comment]
Kannatetaan sulkutarkennetta sekä YSOon että SLM:ään.
