### ISSUE TITLE
maine

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8408]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maine](http://www.yso.fi/onto/ysa/Y111141) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "jälkimaine" 

#### Perustelut ehdotukselle   

'Jälkimaine' on sangen tavallinen sana, joka olisi hyvä saada YSOon viittaamaan lähimpään sitä vastaavaan asiasanaan. Näistä "maine" lienee läheisin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. ET eftermäle

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
