### ISSUE TITLE
verkkovideot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8409]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verkkovideot](http://www.yso.fi/onto/ysa/Y169388) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT nettivideot tai päätermin muutos 

#### Perustelut ehdotukselle   

Otettiin KAUNOon muodossa nettivideot. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
voisi varmaan lisätä myös Internet-videot, joka tuottaa Googlella joitain osumia, mm. tämän https://fi.wikipedia.org/wiki/Luokka:Internet-videoiden_tekij%C3%A4t tai ainakin lisätä KT englanniksi https://en.wikipedia.org/wiki/Internet_video

**Comment by mirmaid** [comment]
Ei Melindassa. Verkossa _nettivideot_ on ylivoimainen.

**Comment by YSO-kokous** [comment]
Muutetaan käytettäväksi termiksi nettivideot. Ohjaustermeiksi verkkovideot ja internet-videot.
