### ISSUE TITLE
jalontaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8410]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jalontaminen 

#### Ehdotettu termi englanniksi   

grafting 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvullinen lisäys](http://www.yso.fi/onto/yso/p9299) 

#### Vastaava käsite muussa sanastossa   

AFO : <http://www.yso.fi/onto/afo/p2616> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jalontamisopas 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [jalontaminen](http://finto.fi/yse/fi/page/Y508410)

**Comment by mariaforsen** [comment]
Wikipediakäännöksen mukaan sama kuin tämä https://fi.wikipedia.org/wiki/Varttaminen ? =sv. ympning
https://www.suomela.fi/piha-puutarha/Puut-pensaat/Hedelmapuiden-lisaaminen-50061

**Comment by ilona-x** [comment]
AFOssa on 
jalontaminen 
ST silmutus
ST varttaminen

YSOssa varmaan riittäisi jalontaminen (KT varttaminen, KT silmutus KT varrentaminen KT ymppäys KT varrennus KT jalonnus)

Kielitoimiston sanakirja:

**jalontaa**
kehittää hedelmäpuu- ym. kasvilajiketta silmuttamalla t. varttamalla; vrt. jalostaa 1. 

**varrentaa**
1. = varttaa 2.
Perusrunkoon varrennettu oksa.
2. harv. silmuttaa. 

**varttaa**
1. kiinnittää varteen.
Varttaa kirves.
2. kasv. jalontaa kasvia siirtämällä sen versoon t. juureen toisen kasvin oksa(npalanen), varrentaa (1), oksastaa. 

**silmuttaa**
jalontaa hedelmäpuuta tm. liittämällä siihen silmullinen (oksan)kappale, silmikoida.

**Comment by mirmaid** [comment]
https://www.hankkija.fi/Piha_ja_puutarha/kasvit/hedelmapuut/omenapuu-perheomenapuu/ :open_mouth:

**Comment by ilona-x** [comment]
Ja käytännössä kaikissa omenapuissa on perusrunko eri lajiketta kuin ne hedelmiä tuottavat oksat. 🙃

**Comment by YSO-kokous** [comment]
Kysyttävä Finton KOKO-asiantuntijoilta: muodostuuko tämän ottaminen ongelmaksi KOKOon: YSOon jalontaminen-käsite ohjaustermeillä varustettuna versus AFOn tilanne. Vrt. myös säästöpuu (https://github.com/Finto-ehdotus/YSE/issues/8378) ja kalliohakkaukset (https://github.com/Finto-ehdotus/YSE/issues/8450).
