### ISSUE TITLE
Annala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8411]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Annala](http://www.yso.fi/onto/ysa/Y138596) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan, esim. Annalan puisto tms. 

#### Perustelut ehdotukselle   

Ks. huomautus. Myös muita Annala-nimisiä kartanoita yms.

**Comment by mirmaid** [comment]
_Annalan kartanokin_ tarvitsisi ehkä tarkenteen? 

Onko _Annalan puutarha_ liian rajaava, jos halutaan sisällyttää myös huvila? Entä _Annala (Helsinki)_?

https://hyotykasviyhdistys.fi/annala/

**Comment by satuniininen** [comment]
Kannatan muotoa _Annala (Helsinki)_. 
Annalasta tulee aina ensimmäisenä mieleen Tampereen Annala, jossa myös sijaitsee kartano, eri niminen tosin. 
Edit. kartano onkin näköjään Kaukajärven puolelle.

**Comment by ilona-x** [comment]
Annala on Helsingissä myös "Kaupunkialueen tai taajaman osa" http://paikkatiedot.fi/so/1000772/10342690

**Comment by mirmaid** [comment]
Ehkä tämän voisi tosiaan myös vain käsitellä paikkana?

**Comment by YSO-kokous** [comment]
Poistetaan YSOsta Annala. Otetaan YSO-paikkoihin Annala (Helsinki).
