### ISSUE TITLE
Espoonkartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8412]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Espoonkartano](http://www.yso.fi/onto/ysa/Y115450) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan ainakin huomautus 

#### Perustelut ehdotukselle   

Huomautus nyt "Kartano ja kylä Espoossa"

**Comment by ilona-x** [comment]
Espoonkartanoa ei näytä olevan YSO-paikoissa. http://paikkatiedot.fi/so/1000772/10071623

**Comment by mirmaid** [comment]
Kartanon omilla sivuilla ja wikipediassa kartanon nimi on nykyään kirjoitettu erikseen: http://espoonkartano.fi/, https://fi.wikipedia.org/wiki/Espoon_kartano.

**Comment by YSO-kokous** [comment]
Muutetaan muotoon Espoon kartano, ohjaustermiksi Espoonkartano (kartanot).
