### ISSUE TITLE
poliisikoulutus

### ISSUE THREAD

**Issue by AnnaLLe** [Finto-ehdotus/YSE#8413]
Tämä termi tarvitaan, se kuvaa lailla rajattuun ammattiin valmistumista.

Lisäksi pidän epämiellyttävänä että jooudun tekemään ehdotukseni nimimerkeille joista ei voi päätellä mitä tahoa ne edustavat. Täm luo yson kehittämisestä kyseenalaista kuvaa.

**Comment by ilona-x** [comment]
JUHO: poliisikoulutus  http://www.yso.fi/onto/juho/p12221
JUPO: poliisikoulutus http://www.yso.fi/onto/jupo/p665

**Comment by mirmaid** [comment]
Sanastossa on _opettajankoulutus, pappiskoulutus_ ja _sotilaskoulutus_, mutta mistä tahansa ammatista voisi muodostaa vastaavan. Melindassa _poliisit & koulutus_ 77 kertaa samoissa viitteissä.

**Comment by ilona-x** [comment]
Näyttää olevan paljon käytetty YLE:n uutisissa: https://yle.fi/aihe/t/18-28349

Melinda: poliisikoulutus x 5

**Comment by AnnaLLe** [comment]
Poliisikoulutus antaa kuitenkin ainoana koulutuksena luvan toimia poliisina. Poliisi voi saada uutakin koulutusta jolloin poliisit + koulutus on ok, esim yhdenvertaisuuskoulutus.
