### ISSUE TITLE
korjurit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8414]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

korjurit 

#### Ehdotettu termi ruotsiksi   

drivare 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Korjuri
Korjuri (harveri, yhdistelmäkone, combi, kombikone) on metsätyökone, jolla hoidetaan sekä puutavaran hakkuu että metsäkuljetus. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://www.metsateho.fi/wp-content/uploads/2015/02/metsatehon_raportti_200.pdf 

**Termiehdotus Fintossa:** [korjurit](http://finto.fi/yse/fi/page/Y508414)

**Comment by ilona-x** [comment]
korjurit Melindasssa 7 kertaa

**Comment by jarmosaarikko** [comment]
AFO:ssa http://www.yso.fi/onto/afo/p4289  sadonkorjuukoneet -- liitetään kaikki maanviljelyyn eikä metsänhoitoon. Metsätekniikassa on kyllä  http://www.yso.fi/onto/afo/p3114 korjuutekniikka, mutta korjuukoneet ovat olleet kaikki harvestereita http://www.yso.fi/onto/afo/p3114  tms. ei korjureita.   
Tämä ei ole päätynyt sanastoon, vaikka näkyy käytetyn jo yli 10 v sitten: 
tiedote:  http://www.metla.fi/tiedotteet/2007/2007-06-05-korjuri.htm 
julkaisu: http://www.metla.fi/julkaisut/workingpapers/2007/mwp048.htm jossa tämä myös asiasanana.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
