### ISSUE TITLE
verismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8415]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verismi](http://www.yso.fi/onto/ysa/Y110690) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö tarkenne? 

#### Perustelut ehdotukselle   

On käytetty määritelmän mukaan, mutta virheen mahdollisuus on: http://tieteentermipankki.fi/wiki/Filosofia:verismi 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
Tarkenne ei todellakaan olisi haitaksi! Vrt. https://fi.wikipedia.org/wiki/Verismi

**Comment by satuniininen** [comment]
_Verismi (tyylit)_ ?

**Comment by YSO-kokous** [comment]
Muutetaan YSOon muotoon verismi (tyylit). Tyylit nähtiin parempana sulkutarkenteena. Jos sulkutarkenne olisi taide, sen voisi nähdä rajaavan musiikin pois.

**Comment by asormune** [comment]
Tuleeko myös SLM sanastoon?
