### ISSUE TITLE
sovellukset (soveltaminen)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8416]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sovellukset (soveltaminen)](http://www.yso.fi/onto/ysa/Y233991) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "sovellutukset" 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/#/sovellutus 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
