### ISSUE TITLE
Varhaiskasvatuksen opettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8417]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Varhaiskasvatuksen opettajat 

#### Ehdotettu termi ruotsiksi   

Lärare inom småbarnspedagogik 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Varhaiskasvatuksen opettaja on uusi ammattinimike lastentarhanopettajalle. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kasvatusalan tutkielmat 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [Varhaiskasvatuksen opettajat](http://finto.fi/yse/fi/page/Y508417)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8396
