### ISSUE TITLE
itsesyttyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8418]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itsesyttyminen](http://www.yso.fi/onto/ysa/Y101904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT itsesytyntä 
Huomautuksen poisto/korjaaminen paremmaksi? 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Itsesytynt%C3%A4
Huomautus ei YSAssa.

**Comment by satuniininen** [comment]
Ei KT:ksi ainakaan. Itsesyttyminen Melindassa 7 kertaa, yhdessä aiheena paranormaalit ilmiöt.

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä, koska viittaa eri asiaan eli paranormaaliin ilmiöön.
