### ISSUE TITLE
kaupunkitalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8419]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kaupunkitalous](http://www.yso.fi/onto/ysa/Y131427) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selvitetään termien kaupunkitalous ja kaupunkitaloustiede merkityksiä ja suhdetta 

#### Perustelut ehdotukselle   

Huomautus nyt: Kaupunkitalous analysoi ja kuvaa kaupunkialueiden taloudellisia ilmiöitä
Tämä sama merkitys näyttää olevan myös termillä kaupunkitaloustiede, ks. esim. lahdenvuosi.fi/yleiskaavaselostus/lahti-vuonna-2025-tarina/kestavasti-kasvava-lahti/kaupunkitalous jossa sanotaan mm. "Kaupunkitaloustiede on taloustieteen osa-alue, joka analysoi kaupunkialueiden ilmiöitä taloustieteellisiä työvälineitä käyttäen." 
Ruotsiksi vastineet nyt urban ekonomi ja stadsekonomi, sekä englanniksi urban economics (regional economy) ja urban economics (eli monikielinen tilanne ongelmallinen myös).

**Comment by ilona-x** [comment]
kaupunkitalous otettu sanastoon v. 2004 varmaankin tämän v. 2004 ilmestyneen teoksen myötä: 
Seppo Laakso & Heikki A. Loikkanen: Kaupunkitalous https://www.gaudeamus.fi/kaupunkitalous/

Ja suuuri osa kaupunkitalous Google-hakutuloksista on myös tuohon teokseen liittyviä viitteitä

YSOssa aluetalous mutta ei aluetaloustiede. LCSH: regional economics & urban economics

Melindassa kaupunkitalous käytetty 149 kertaa, 
osassa viitteistä näyttäisi olevan kyse kunnallistaloudesta, esimerkiksi: 

- Kaupunkikuntien menot ja tulot vuosina 1928-1929
- Kaupungit panostivat psykiatriseen avohoitoon, hammashuoltoon ja vanhusten laitoshoitoon.
- Tulospalkkaus Jyväskylän kaupunkikonsernissa

**Comment by YSO-kokous** [comment]
Tutkitaan ainestoa vielä. Pohdittiin kaupunkitaloustiede-käsitteen poistoa (aika vähän käytetty kuvailussa) ja tämä ehkä ohjaustermiksi kaupunkitaloudelle. Lisäksi pohdittiin seuraavan ohjaustermin lisäämistä: kaupunkitalous (kunnallistalous KÄYTÄ kunnallistalous.

**Comment by mirmaid** [comment]
_Kaupunkitalous_ voisi kai olla englanniksi myös _urban economy_? https://www.ilo.org/sector/activities/topics/urban-economy/lang--en/index.htm. _Urban economics_ tuntuisi viittaavan nimenomaan _kaupunkitaloustieteeseen_, vrt. talous/taloustieteet. Esim. tässä https://melinda.kansalliskirjasto.fi/byid/016598848 kaupunkitalous ja uudistukset liittyvät selvästi yhteen ja kyse on Buttigiegin toiminnasta kaupungin talouden kohentamiseksi, jolloin urban economics ehkä sopii vähän huonosti (urban economics & reforms).

Usein vaikka kyse on taloudesta (economy), myös economics ja jopa taloustiede sopii kuvaamaan aineiston alaa, esim. https://melinda.kansalliskirjasto.fi/byid/010045682. 

Itse asiassa molemmat termit on otettu sanastoon v. 2004.

**Comment by mirmaid** [comment]
Jäin vielä miettimään, kun ruotsiksi nyt _kansantalous = samhällsekonomi_, _kansantaloustiede = nationalekonomi_. Rajautuvatko nuo nyt molemmilla kielillä samalla tavalla? Ettei tämä ole laajempi ongelma, joka on noussut nyt esiin vain tämän yhden käsiteparin kohdalla. Jos siis ruotsiksi ekonomi on sekä talous että taloustiede.

**Comment by mariaforsen** [comment]
kansantalous=samhällsekonomi, kansantaloustiede=nationalekonomi /Svenskt lagspråk i Finland Slaf – ruotsinkielinen lakikieli (VNK, 2017) 
Ks. myös MOT Schildts Finlandssvensk ordbok, jossa selkeä selitys. Yllä mainitulla "ongelmalla" on siis vakiintunut ratkaisu ja on aivan oikein YSOssa.

**Comment by mirmaid** [comment]
^ Ok, hyvä jos kyse ei ole laajemmasta ongelmasta. Tässäkin parissa taloustiede/talous -ero on periaatteessa ihan selkeä (tieteenala, tutkimusala vs. se mitä tieteenala tutkii "todellisessa maailmassa": _Shortest way home : one mayor’s challenge and a model for America’s future_ vs. _Oppihistoriallinen katsaus kaupunkitaloustieteeseen_). _Kaupunkitaloustiede_ on kuitenkin käytetty vain 38 kertaa Melindassa ja korvattavissa viitteissä _kaupunkitalous_-käsitteellä (sekä tarpeen mukaan _taloustieteet_), joten sen voi kyllä poistaa. Poistaisin myös huomautuksen _kaupunkitalous_-käsitteeltä.

**Comment by YSO-kokous** [comment]
otetaan kaupunkitalous, urban economy |   Poistetaan kaupunkitaloustiede.

**Comment by mirmaid** [comment]
^ Kaupunkitalous siis myös jo ennestään sanastossa.
