### ISSUE TITLE
kveenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8420]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kveenit](http://www.yso.fi/onto/ysa/Y105441) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutoksia huomautukseen? 

#### Perustelut ehdotukselle   

Eri huomautus YSAssa ja YSOssa, joissa annetaan hieman erilaisia merkityksiä termille (Pohjanlahti ja Ruija ovat aika kaukana toisistaan, keski-aika vs. 1800/2000-luku). Mikä näistä pätee? Tarvitseeko termi huomautusta ollenkaan? Tuskin sitä käytettäisiin väärin. 
Ks. myös https://www.uppslagsverket.fi/sv/sok/view-103684-Kvaener -onko termi oikeastaan kaksimerkityksinen?

**Comment by krinay** [comment]
Samaa mieltä siitä, että huomautus lienee tarpeeton. Sekaannuksen vaara on varmaan vähäinen  (mutta YSOn huomautus-teksti hiukan hämmentävä). 

Selitystä Lassi Saresalon väitöskirjassa _Kveenit_ (1996) sivuilla 15–19 (http://urn.fi/urn:nbn:fi:sks-dor-000999). Katkelma:
"Kveeneiksi kutsutaan kielellisesti ja etnisesti omaksi ryhmäkseen erotettavaa pohjoisnorjalaista historiallista vähemmistöä, jonka kulttuuri perustuu suomalaiseen kulttuuriin ja kieli suomen kieleen.  Tämä suomalaisperäinen väestö asuu Ruijassa, Pohjois-Norjassa Finmarkun ja Tromssan läänien alueella rinnan valtaväestönä olevan norjalaisen ja alkuperäisväestöksi laskettavan saamelaisväestön kanssa. --- Kveeniväestö on asettunut nykyisille asuinsijoilleen 1600-luvulta alkaneen ja 1800-luvun lopulle ulottuneen muuttoliikkeen aikana.”

Ks. myös 
https://www.kotus.fi/kielitieto/kielipolitiikka/ajankohtaista_kielipolitiikasta/kielipolitiikasta_mediassa_2017-2018/kveenin_kielen_puhujia_on_enaa_parituhatta.26359.news.

**Comment by mirmaid** [comment]
YSAssa on ollutkin hyvin erilainen huomautus: http://www.yso.fi/onto/ysa/Y105441. Olen parhaillaan käymässä huomautuksia läpi, mutta se etenee etanan vauhdilla muun ohessa...edellisen kerran aihetta käsiteltiin vielä YSA-aikana, silloin ei huomattu tätä huomautus-eroa. https://github.com/Finto-ehdotus/YSE/issues/5440

**Comment by YSO-kokous** [comment]
Poistetaan käsitteeltä huomautus. Merkitys selkeä eikä sekoittumisen riskiä.
