### ISSUE TITLE
levytys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8421]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[levytys](http://www.yso.fi/onto/ysa/Y96851) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan huomautuksessa oleva viittaus äänityssessioihin ("Levytyksen tuloksena syntyvistä tuotteista (levytyksistä) katso äänityssessiot") 

#### Perustelut ehdotukselle   

Tässä olisi varmaan tarkoitus viitata levyihin tai äänitteisiin?

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa viittaamista äänityssessioiden sijasta äänityksiin.

**Comment by mirmaid** [comment]
Linkki korjattu.
