### ISSUE TITLE
ansiopäiväraha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8422]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ansiopäiväraha 

#### Ehdotettu termi ruotsiksi   

inkomstrelaterad dagpenning 

#### Ehdotettu termi englanniksi   

earnings-related unemployment allowance 

#### Vaihtoehtoiset termit ja ilmaisut   

ansiosidonnainen päiväraha 
ansiosidonnainen työttömyyspäiväraha 

#### Ehdotettu yläkäsite YSOssa (LT)   

[työttömyyspäivärahat](http://www.yso.fi/onto/yso/p10381) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Tarkoitusta täsmentävä selite   

Kelan terminologinen sanasto, 5. laitos: työttömyyspäiväraha, jonka määrä riippuu työttömyyttä edeltäneistä ansiotuloista ja joka voidaan myöntää silloin, kun työtön on ollut riittävän pitkään työttömyyskassan jäsen 

#### Perustelut ehdotukselle   

Kuuluu työttömyysturvan persukäsitteisiin 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.kela.fi/tilastot-aiheittain/suomen-tyottomyysturva , 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [ansiopäiväraha](http://finto.fi/yse/fi/page/Y508422)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by ilona-x** [comment]
JUPOssa monikossa ansiopäivärahat http://www.yso.fi/onto/jupo/p105

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by mariaforsen** [comment]
Sv. inkomstrelaterad dagpenning ET förtjänstrelaterad dagpenning, dagpenning avvägd enligt förtjänsten
