### ISSUE TITLE
peruspäiväraha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8423]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

peruspäiväraha 

#### Ehdotettu termi ruotsiksi   

grunddagpenning 

#### Ehdotettu termi englanniksi   

basic unemployment allowance 

#### Perustelut ehdotukselle   

Kuuluu työttömyysturvan peruskäsitteisiin 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.kela.fi/tilastot-aiheittain/suomen-tyottomyysturva , 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549) 

#### Tarkoitusta täsmentävä selite   

Kelan terminologinen sanasto, 5. laitos:  	
työttömyyspäiväraha, jonka määrä ei riipu työttömyyttä edeltäneistä ansiotuloista ja joka voidaan myöntää, vaikkei työtön ole työttömyyskassan jäsen tai ei ole ollut jäsen riittävän pitkään 

**Ehdottajan organisaatio:** Kela **Termiehdotus Fintossa:** [peruspäiväraha](http://finto.fi/yse/fi/page/Y508423)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
