### ISSUE TITLE
veljentyttäret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8425]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

veljentyttäret 

#### Ehdotettu termi ruotsiksi   

brodsdöttrar 

#### Ehdotettu termi englanniksi   

niece 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jälkeläiset](http://www.yso.fi/onto/yso/p3900) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh86002904> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 

#### Perustelut ehdotukselle   

Tarve sisällönkuvailussa tarkemmalle termille 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

"The forgotten kin : aunts and uncles" 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [veljentyttäret](http://finto.fi/yse/fi/page/Y508425)

**Comment by mariaforsen** [comment]
Sv. brorsdöttrar ET niecer (brorsdöttrar)

**Comment by jarmosaarikko** [comment]
Käsite: **sisaruksen lapset**   
> ohjaustermit/alakäsitteet:  
> fi: veljenpojat, veljentyttäret, sisarenpojat, sisarentyttäret   (sv: brorssöner, brorsdöttrar, systerssöner, systersdöttrar)
> en: nieces, nephews
> owl:inverseOf  [tädit](http://www.yso.fi/onto/yso/p25689), [sedät](http://www.yso.fi/onto/yso/p25230), [enot](http://www.yso.fi/onto/yso/p25229)  (fastrar, mostrar, farbröder, morbröder)
Tarvitaanko nämä kaikki omina käsitteinään?

katso myös #8426

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon veljentyttäret.
