### ISSUE TITLE
veljenpojat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8426]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

veljenpojat 

#### Ehdotettu termi ruotsiksi   

brorsöner 

#### Ehdotettu termi englanniksi   

nephews 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jälkeläiset](http://www.yso.fi/onto/yso/p3900) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh97008228> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 

#### Perustelut ehdotukselle   

Tarve sisällönkuvailussa tarkemmalle termille 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The forgotten kin : aunts and uncles 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [veljenpojat](http://finto.fi/yse/fi/page/Y508426)

**Comment by jarmosaarikko** [comment]
Sopisiko yläkäsitteeksi paremmin [sukulaiset ](http://www.yso.fi/onto/yso/p405)

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by mariaforsen** [comment]
Sv. brorsöner ET nevöer (brorsöner)
