### ISSUE TITLE
sisarenpojat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8428]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sisarenpojat 

#### Ehdotettu termi ruotsiksi   

systersöner 

#### Ehdotettu termi englanniksi   

nephews 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jälkeläiset](http://www.yso.fi/onto/yso/p3900) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh97008228> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[61 Väestötiede. Demografia](http://www.yso.fi/onto/yso/p26570) 

#### Perustelut ehdotukselle   

Tarve sisällönkuvailussa tarkemmalle termille 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

"The forgotten kin : aunts and uncles" 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjasto **Termiehdotus Fintossa:** [sisarenpojat](http://finto.fi/yse/fi/page/Y508428)

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by mariaforsen** [comment]
Sv. systersöner ET nevöer (systersöner)
