### ISSUE TITLE
olematon

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8429]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

olematon 

#### Ehdotettu termi ruotsiksi   

obefintlig 

#### Ehdotettu termi englanniksi   

nothing 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ontologia (filosofia)](http://www.yso.fi/onto/yso/p1055) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85092796> 

#### Tarkoitusta täsmentävä selite   

tai muodossa olemattomuus, obefintlighet, nothingness
LCSH.ssa nothing (philosophy) asiasanan ohjausterminä nothingness (philosophy)
Kielitoimiston sanakirja: olematon "1. jota ei ole olemassa, epätodellinen, vain kuviteltu, puuttuva" "2. 2. mitätön, kovin pieni, vähäinen, vähäpätöinen, niukka." 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

tarve sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

"The social life of nothing: silence, invisibility and emptiness in tales of lost experience" 

**Ehdottajan organisaatio:** Itä-Suomen yliopiston kirjaso **Termiehdotus Fintossa:** [olematon](http://finto.fi/yse/fi/page/Y508429)

**Comment by jtuohini** [comment]
Mieluummin nimisanana (substantiivina) kuin laatusanana (adjektiivina). Vrt. esim. "YSOn käsitteiden termit ovat tesaurusstandardien mukaisesti useimmiten monikkomuotoisia substantiiveja. Yksikössä esitetään esim. ainesanat sekä abstrakteja käsitteitä ja toimintaa kuvaavat termit. Joillain termeillä on yksikkö- ja monikkomuodossa eri merkitys, esim. termi baletti viittaa taidemuotoon ja baletit yksittäisiin taideteoksiin." [https://www.kiwi.fi/display/Asiasanastotjaontologiat/YSO]

**Comment by mariaforsen** [comment]
Sv. intet SAO: https://id.kb.se/term/sao/Intet ET intighet, obefintlighet, icke-existens

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa olemattomuus, ohjaustermiksi olematon.
