### ISSUE TITLE
glam rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8430]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[glam rock](http://www.yso.fi/onto/ysa/Y206903) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM sanastoon 

#### Perustelut ehdotukselle   

Lisätäänkö? 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto

**Comment by jtuohini** [comment]
LCGFT-vastine: [**Glam rock (Music)**](http://id.loc.gov/authorities/genreForms/gf2018026029)

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa ehdotusta. Määritelmä tulee myöhemmin.

**Comment by jaskaj** [comment]
Ehdotus määritelmäksi:

1970-luvun alussa kehittynyt rock-musiikin laji joka yhdisteli pop-musiikkia ja hard rockia teatraaliseen esiintymiseen. Esittäjät hämärsivät sukupuolten rajoja pukeutumisella ja meikkaamisella.

**Comment by asormune** [comment]
... pop-musiikkia > popmusiikkia ... ?

**Comment by jaskaj** [comment]
1970-luvun alussa kehittynyt rockmusiikin laji joka yhdistelee popmusiikkia ja hard rockia teatraaliseen esiintymiseen, johon kuuluu usein sukupuolten rajoja hämärtävä pukeutuminen ja meikkaaminen.

**Comment by MUUSA-kokous** [comment]
Muusa kannattaa määritelmäehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
