### ISSUE TITLE
inkeroismurteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8432]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[inkeroismurteet](http://www.yso.fi/onto/ysa/Y101850) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Inkeroisen kieli https://finto.fi/lexvo/fi/page/izh
https://fi.wikipedia.org/wiki/Inkeroisen_kieli
LCSH:  Ingrian language 

#### Ehdotettu muutos   

Vaihdetaan päätermiksi inkeroisen kieli?
Lisätään tarkenne ohjaustermille inkeroinen (vrt. Inkeroinen (Kouvola)) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Ks. esim. https://www.kotus.fi/kielitieto/kielet
"Suomea ja sen lähimpiä sukukieliä kutsutaan itämerensuomalaisiksi kieliksi. Näistä puhutuimpia ovat suomen ohella viro ja karjala. Muita ovat inkeroinen, lyydi (jota on toisen näkemyksen mukaan pidetty karjalan murteena), vepsä, vatja ja liivi."

**Comment by mariaforsen** [comment]
Sv. ingriska

**Comment by YSO-kokous** [comment]
Vaihdetaan päätermiksi inkeroisen kieli.
