### ISSUE TITLE
edge computing (suomeksi?)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8433]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

edge computing (suomeksi?) 

#### Ehdotettu termi englanniksi   

edge computing 

#### Perustelut ehdotukselle   

mm. Lightweight virtualization in edge computing for internet of things /Roberto Morabito.
väitöskirjoissa useamminkin 

#### Tarkoitusta täsmentävä selite   

Liittyy esineiden internetiin ja pilvipalveluihin.
Google kääntää termin 'reunalaskennaksi'. 
 Edge Computing eli prosessoinnin siirtäminen mahdollisimman lähelle päätelaitetta ja käyttötilannetta. (lähde: Edge Computing haastaa, mutta ei riko | Tivi ) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lightweight virtualization in edge computing for internet of things /Roberto Morabito. 

**Ehdottajan organisaatio:** KB **Termiehdotus Fintossa:** [edge computing (suomeksi?)](http://finto.fi/yse/fi/page/Y508433)

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/reunalaskenta

**Comment by mirmaid** [comment]
Melindassa kerran reunalaskenta, 5 kertaa edge computing.

**Comment by mirmaid** [comment]
Kyllä kai tämä on otettava jos kerran [vuosi 2020 on reunalaskennan vuosi](https://www.mikrobitti.fi/uutiset/vuosi-2020-on-reunalaskennan-vuosi/81d41fe8-0392-4321-bd77-ff3d6370172e) :nerd_face:.

**Comment by mariaforsen** [comment]
Sv. edge computing ET kantberäkning, kantdatorsystem
https://it-ord.idg.se/ord/kantdatorsystem/

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa reunalaskenta.
