### ISSUE TITLE
vika- ja vaikutusanalyysi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8434]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

failure mode and effect analysis 

#### Ehdotettu termi suomeksi   

vika- ja vaikutusanalyysi 

#### Vaihtoehtoiset termit ja ilmaisut   

VVA 
FMEA 

#### Perustelut ehdotukselle   

Saimme palautetta Finto-postiin Karelia AMK:sta: "Tälle ei ole oikein mitään sopivaa vastinetta sanastossa." 

#### Tarkoitusta täsmentävä selite   

http://www.fistb.fi/sites/fistb/files/liitteet/istqb_sanasto_2015-04-30%202.3%20ENG-FI%20Koekelpoinen%20versio_0.pdf 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vika- ja vaikutusanalyysi](http://finto.fi/yse/fi/page/Y508434)

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Failure_mode_and_effects_analysis
LCSH: Failure mode and effects analysis http://id.loc.gov/authorities/subjects/sh2012001105
https://termipankki.fi/tepa/fi/haku/vika-%20ja%20vaikutusanalyysi

**Comment by mirmaid** [comment]
5 viitettä Melindassa. YK riskianalyysi.

**Comment by mariaforsen** [comment]
Sv. feleffektsanalys ET FMEA-analys
https://mesh.kib.ki.se/term/D000067495/healthcare-failure-mode-and-effect-analysis

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
