### ISSUE TITLE
kuraattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8435]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuraattorit](http://www.yso.fi/onto/ysa/Y151132) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Täsmennetään tai jaetaan 

#### Perustelut ehdotukselle   

Monimerkityksinen termi, myös ruotsiksi. 
Ks. Kielitoimiston sanakirjaa

**Comment by ilona-x** [comment]
Kielitoimiston sanakirjasta:
kuraattori
1. koulukuraattori.
2. taide- tm. näyttelyn kokoamisesta ja järjestämisestä vastaava henkilö.
3. yliopiston osakunnan toimintaa johtava henkilö; myös eräistä muista akateemisten järjestöjen luottamushenkilöistä.
4. vanh. valvoja, huoltaja. 

YSOssa erikseen koulukuraattorit http://www.yso.fi/onto/yso/p11769

**Comment by mirmaid** [comment]
Ainakin voisi lisätä kuraattorit (koulut) KÄ koulukuraattorit. 

Suurin osa viitteistä liittyy tavalla tai toisella taiteeseen (ml. teatteritaide jne.), mutta joitakin kertoja sosiaalityöstä myös koulun ulkopuolella.

**Comment by YSO-kokous** [comment]
Muutetaan käytettävä termi muotoon kuraattorit (kulttuuri), korjataan kuvailua ja katsotaan, onko tarvetta muille muutoksille. 
Lisätään ohjaustermi kuraattorit (koulut) KÄYTÄ koulukuraattorit.

Keskustelua: Puolustusvoimissa on käytössä ammatti sosiaalikuraattori.

**Comment by mirmaid** [comment]
- Muutamia viitteitä, joissa kyseessä [osakunnan kuraattori](https://fi.wikipedia.org/wiki/Kuraattori#Osakuntien_ja_opiskelijaj%C3%A4rjest%C3%B6jen_kuraattorit).
- Joitakin kertoja kysymys korkeakoulusta, jolloin _koulukuraattorit_ ei ehkä sovellu, vrt. Koulukuraattorit ry: _Yhdistyksen tehtävänä on esi- ja peruskouluissa, ammatillisissa oppilaitoksissa ja lukioissa toimivien vastaavien kuraattorien ja kuraattorien ammatillinen edunvalvonta, ammatillinen koulutus ja verkostoituminen._
- _Sosiaalikuraattori_-nimitystä käyttävät puolustusvoimat ja Merimieskirkko. Sosiaaliturvan sanasto tuntee sosiaalikuraattorin https://termipankki.fi/tepa/fi/haku/sosiaalikuraattori, mutta viitteitä ei juuri tule kuin em. organisaatioihin. Ruotsissa _terveyden- ja sairaanhoiton kuraattori_: https://sv.wikipedia.org/wiki/Kurator_(socialt_arbete), https://www.soch.lu.se/utbildning/halso-och-sjukvardskurator, mutta suomeksi kuraattori-nimitystä käytetään melko yksinomaan oppilashuollon kontekstissa, lisäksi löytyy _adoptiokuraattori_, näistä myös jonkin verran aineistoa. 
- Kerran eläintarhan kuraattori.

**Comment by YSO-kokous** [comment]
Ei oteta osakunnan kuraattorit, voi käyttää 653 tai join muu termi.
jatketaan valmistelua

**Comment by mirmaid** [comment]
21 viitettä Melindassa

- kuraattorit (sote/Ruotsi): 6 kertaa
- osakunnan kuraattorit: 4 kertaa
- merimieskirkko/laivakuraattori: 4 kertaa
- adoptiokuraattori: 3 kertaa
- puolustusvoimien sosiaalikuraattori: 2 kertaa
- eläintarhan kuraattori: kerran
- ammattikorkeakoulun kuraattori: kerran

**Comment by mirmaid** [comment]
Kaikkia käytetty niin vähän, että riittäisikö 653-kenttä ja mahd. lisäksi _sosiaalityöntekijät_?

**Comment by mariaforsen** [comment]
Kannatan poistoa. Olisiko kuitenkin tarvetta termille sosiaalikuraattorit? https://termipankki.fi/tepa/fi/haku/sosiaalikuraattori Käytetty Melindassa 18 kertaa asiasanana.

**Comment by mirmaid** [comment]
^ Näyttää lähes kaikki liittyvän puolustusvoimien sosiaalikuraattoreihin. Tämä on kieltämättä vähän hankala, kun en tiedä voiko sitä käyttää noista adoptiokuraattoreista ja merimieskirkon kuraattoreista, kun eivät itse käytä ko. ammattinimikettä.

**Comment by YSO-kokous** [comment]
### Päätös
otetaan sanastoon sosiaalikuraattorit
