### ISSUE TITLE
motiivit (aihelmat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8436]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[motiivit (aihelmat)](http://www.yso.fi/onto/ysa/Y97511) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ryhmä 50. 

#### Perustelut ehdotukselle   

Motiivit on keskeisen tärkeä termi folkloristiikassa.
(Jos mahdollista, olisi hienoa saada lisäksi RT motiiviluettelot, mutta jos se tuntuu hankalalta, ilmankin pärjätään.) 

#### Ehdottajan organisaatio   

SKS:n kirjasto

**Comment by mirmaid** [comment]
Lisätty.
