### ISSUE TITLE
kahvipannut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8437]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kahvipannut 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kahv, Ville...käy kahville 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kahvipannut](http://finto.fi/yse/fi/page/Y508437)

**Comment by mirmaid** [comment]
MAOssa/TAOssa: http://www.yso.fi/onto/mao/p3999

**Comment by mirmaid** [comment]
18 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. kaffepannor
