### ISSUE TITLE
viitat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8442]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[viitat](http://www.yso.fi/onto/ysa/Y189555) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi keepit. RT:ksi ponchot. 

#### Perustelut ehdotukselle   

Keeppi lienee suomen vastine englannin ja ruotsin sanoille cape. YSOssa viitat on ruotsiksi caper ja englanniksi cloaks, ohjausterminä capes. Englannin cloak- ja cape-sanojen erosta: Wikipedia: "In fashion, the word “cape” usually refers to a shorter garment and “cloak” to a full-length version of the different types of garment, though the two terms are sometimes used synonymously for full-length coverings."

YSOn viitat on nyt linkitetty Wikidatassa sekä cape- että cloak-kohteisiin, koska YSOn viitat-käsitteessä esiintyy molempien kohteiden termejä.
https://www.wikidata.org/wiki/Q1034198
https://www.wikidata.org/wiki/Q516992

Pikagooglauksella ponchot näyttivät esiintyvän usein samassa yhteydessä kuin viitat ja keepit, joten RT voisi olla sopiva näille? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Keeppi

Näyttäisi suomeksi viittaavan nimenomaan tähän lyhyen ponchon näköiseen asusteeseen, joka usein on myös edestä yhtenäinen.

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä. YSO-ylläpito miettinee RT ponchot. Huom! keepit MAOssa erillisenä käsitteenä eli ohjaustermi olisi KOKO-ongelma.
