### ISSUE TITLE
kreolisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8443]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kreolisaatio 

#### Ehdotettu termi englanniksi   

creolization 

#### Ehdotettu termi ruotsiksi   

kreolisering 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-93-0490-5 

#### Perustelut ehdotukselle   

Creolization is the process through which creole languages and cultures emerge.[1] Creolization was first used by linguists to explain how contact languages become creole languages, but now scholars in other social sciences use the term to describe new cultural expressions brought about by contact between societies and relocated peoples.[2] Creolization is traditionally used to refer to the Caribbean, although it is not exclusive to the Caribbean and some scholars use the term to represent other diasporas.[3] Furthermore, creolization occurs when participants select cultural elements that may become part of or inherited culture.
https://en.wikipedia.org/wiki/Creolization 

**Termiehdotus Fintossa:** [kreolisaatio](http://finto.fi/yse/fi/page/Y508443)

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:kreolisaatio

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon. Käsitteelle ainakin ryhmät 50 ja 85.
