### ISSUE TITLE
soveltava taide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8444]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[soveltava taide](http://www.yso.fi/onto/ysa/Y179976) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "käyttötaide" 

#### Perustelut ehdotukselle   

"Soveltava taide eli käyttötaide on käytännön tarkoituksia palvelevaa taidetta, esimerkiksi taideteollisuuden tuotteita ja mainosgrafiikkaa." [https://fi.wikipedia.org/wiki/K%C3%A4ytt%C3%B6taide] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. brukskonst, nyttokonst https://sv.wikipedia.org/wiki/Brukskonst

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
