### ISSUE TITLE
asetukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8446]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asetukset](http://www.yso.fi/onto/ysa/Y94729) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

vaatiiko tarkenteen tai jaetaanko? 

#### Perustelut ehdotukselle   

käytetty Melindassa joitakin kertoja tietokoneiden, älypuhelinten ym. laitteiden asetuksista, esim.:
https://melinda.kansalliskirjasto.fi/byid/013589319
https://melinda.kansalliskirjasto.fi/byid/013591284

Kielitoimiston sanakirja:
**1. oikeussäännöksiä t. hallintomääräyksiä sisältävä lakia alempi säädös, jonka presidentti, valtioneuvosto t. ministeriö antaa ilman eduskunnan myötävaikutusta.**
Tulliasetus.
Antaa asetus.
Asetus maataloushallinnosta.
Vastoin lakia ja asetuksia.

2. asettaminen, sovittaminen.

**3. tietotekn. ohjelman t. järjestelmän toimintaa ohjaava määrittely t. valinta.**
Asetusten päivitys. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi tähän asti ollut förordningar eli oikeusmerkityksessä. Asetukset säätönä on sv. inställningar, myös sv. inställning=säätö YSOssa.

**Comment by mirmaid** [comment]
_Asetukset (säädökset)_ kyllä ok, mutta ensimmäisten sadan joukossa ei tullut virheellisiä vastaan (1600 kertaa Melindassa). (Mikrobitti + asetukset löytyi 11 kertaa :nerd_face:)

**Comment by ilona-x** [comment]
Ja MikroPC + asiasana asetukset 28 kertaa. 

Ehkä tämä toinen merkitys ei ole sanastossa välttämätön. Joissain viitteissä on asetusten lisäksi mm. seuraavia termejä: säätö, kalibrointi, optimointi

**Comment by YSO-kokous** [comment]
Muutetaan asetukset muotoon asetukset (säädökset). Korjataan viitteitä tarpeen mukaan.
