### ISSUE TITLE
yhteiskuntaluokat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8448]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhteiskuntaluokat](http://www.yso.fi/onto/ysa/Y100387) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermi sosiaaliluokat? 

#### Perustelut ehdotukselle   

https://tieteentermipankki.fi/wiki/Epidemiologia:yhteiskuntaluokka
FinMeSH: yhteiskuntaluokka KÄYTÄ sosiaaliluokka http://www.yso.fi/onto/mesh/D012923 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. KT sociala klasser

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
