### ISSUE TITLE
ukonvaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8449]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ukonvaajat 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Puukenkien kopinaa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ukonvaajat](http://finto.fi/yse/fi/page/Y508449)

**Comment by krinay** [comment]
On MAOssa: http://www.yso.fi/onto/mao/p2981.

**Comment by mirmaid** [comment]
3 viitettä Melindassa. 

https://fi.wikipedia.org/wiki/Ukonvaaja. Suomenkielinen toinen merkitys ei varmaan ole ongelma?

_Suomenkielessä fulguriitista on käytetty vanhaa termiä salamaniskemä. Ukonvaaja-termi on alun perin tarkoittanut pellosta löytyneitä kivikautisia kivikirveitä, joita on aikoinaan pidetty salamoinnin aiheuttamina. Matti Nuortevan (1996) mielestä myös osa ukonvaaja-nimellä tunnetuista löydöistä voi todellisuudessa olla fulguriitteja. Tämän kirjoittajan mielestä salamaniskun synnyttämistä laseista olisi kuitenkin suositeltavaa käyttää niiden kansainvälisen fulgurite-termin jo vakiintunutta suomennosta muodossa fulguriitti. Mahdollinen toinen uusi termi voisi olla salamasula, mutta se hyväksyminen ja yleistyminen vaatisi vuosia._ https://docplayer.fi/18261340-Hiekkafulguriitti-orimattilasta-ja-suomen-fulguriittiloydoista.html

Toivon, että _salamasula_ yleistyy! Ehkä kaunein ikinä kuulemani sana :sparkling_heart:

**Comment by mariaforsen** [comment]
Sv. 
-åskviggar ET torsviggar 
-fulguriter ET blixtrör

**Comment by YSO-kokous** [comment]
Otetaan YSOon kaksi käsitettä:

ukonvaajat
fulguriitit

Ukonvaajalle löytynee Wikipediasta myös ohjaustermejä.
