### ISSUE TITLE
luottoriskit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8451]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

luottoriskit 

#### Ehdotettu termi englanniksi   

credit risk 

#### Ehdotettu termi ruotsiksi   

kreditrisk 

#### Vaihtoehtoiset termit ja ilmaisut   

luottoriski 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luotot](http://www.yso.fi/onto/yso/p6702) 

#### Perustelut ehdotukselle   

Luottoriski on yleinen ja käytetty termi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Rahoitusmarkkinoihin, -laitoksiin, pankkitoimintaan liittyvät aineistot 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

**Termiehdotus Fintossa:** [luottoriskit](http://finto.fi/yse/fi/page/Y508451)

**Comment by ilona-x** [comment]
JUPO: **luottoriskit** http://www.yso.fi/onto/jupo/p1136
LIITO: **luottoriski** http://www.yso.fi/onto/liito/p11604

**Comment by mirmaid** [comment]
6 viitettä Melindassa. Sanastossa toistaiseksi vain _terveysriskit_ ja _ympäristöriskit_.

**Comment by mariaforsen** [comment]
Sv. kreditrisker 
https://sv.wikipedia.org/wiki/Kreditrisk

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by ilona-x** [comment]
fi        luottoriski; luottotappioriski
sv       kreditrisk
en      credit risk; credit loss risk
anmärkning
Med kreditrisk avses risken att motparten inte kan fullgöra sina åtaganden gentemot kreditinstitutet.
Till kreditrisker hör till exempel risk förknippad med företagskunder (på finska: yritysten luottoriski, på engelska: risk related to corporate customers ) och kreditrisk avseende privatkunder (på finska: henkilöasiakkaiden luottoriski, på finska: credit risk relating to private customers).
Lähde:   Pankki- ja rahoitussanasto / Bank- och finansterminologi (TSK), 2002-09-13
https://termipankki.fi/tepa/fi/haku/luottoriski
