### ISSUE TITLE
glamour

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8455]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

glamour 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Glamouria Suomessa 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [glamour](http://finto.fi/yse/fi/page/Y508455)

**Comment by mariaforsen** [comment]
Sv. glamour

**Comment by mirmaid** [comment]
Kerran Melindassa. 

LCSH: http://id.loc.gov/authorities/subjects/sh2008009813

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
