### ISSUE TITLE
sitar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8456]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sitar](http://www.yso.fi/onto/ysa/Y214659) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö huomautus korjata? 

#### Perustelut ehdotukselle   

Huomautus nyt: Intialainen pitkäkaulainen luuttusoitin, klassisen musiikin keskeinen soolosoitin. Tarkoitetaanko "intialaisen klassisen musiikin..." tms.?

**Comment by MUUSA-kokous** [comment]
Muusan ehdotus määritelmäksi: "Intialainen pitkäkaulainen luuttusoitin, intialaisen taidemusiikin keskeinen soolosoitin".

**Comment by YSO-kokous** [comment]
Muusan ehdottama määritelmä hyväksytään. Korjataan myös SEKOssa oleva määritelmä.
