### ISSUE TITLE
elinpiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8457]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elinpiirit](http://www.yso.fi/onto/ysa/Y104177) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Selvitettävä merkitys ja vrt. reviirit 

#### Perustelut ehdotukselle   

Ruotsiksi vastineena on ollut utbredningsområden (todennäköisesti muutettava)
https://termipankki.fi/tepa/fi/haku/elinpiiri
https://www.kielitoimistonsanakirja.fi/#/elinpiiri
https://www.stat.fi/meta/kas/tavomelinpiiri.html

**Comment by mariaforsen** [comment]
Jos tällä viitataan vain eläinten elinpiiriin voidaan korjata > hemområden (djur) tms. 

Onko siis rajanveto tämä: "Reviiri tai territorio on eläimen elinpiirin osa, jota eläin puolustaa saman lajin yksilöiltä. " Näin määritellään myös hemområde vs. revir Nationalencyklopedinissa, eli ratkaisu olisi oikein toimiva.

**Comment by mirmaid** [comment]
On käytetty eläinten lisäksi ihmisistä, usein nimenomaan vanhustenhuollon yhteydessä (esim. ikääntyneiden elinpiirin laajuus ja yksinäisyys). Haittaako jos ei rajaudu eläimiin? Eri asia kuitenkin kuin utbredningsområde = levinneisyysalue.

Jos halutaan rajata tarkemmin, pitää suomeksi lisätä tarkenne (esim. _elinpiirit (biologia)_) ja korvata vanhuksiin liittyvissä aineistoissa muilla termeillä (liikkuvuus, aktiivisuus, sosiaaliset suhteet tms.).

**Comment by mariaforsen** [comment]
Vaikeaa nähdä miten voidaan kääntää ellei rajata biologiaan, ja tuskin hakija haluaa ainaiestoa molemmista näistä asioista. Kannatan siis ehdottomasti rajaamista.

**Comment by YSO-kokous** [comment]
elinpiirit (biologia)
