### ISSUE TITLE
geohydrologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8458]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[geohydrologia](http://www.yso.fi/onto/ysa/Y107256) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään geohydrologia ja hydrogeologia. 

#### Perustelut ehdotukselle   

UDK:ssa nämä on yhdistetty. Samoin LCSH:ssa. Suomen- ja englanninkielisessä Wikipediassa nämä esitetään synonyymeina.
https://finto.fi/udcs/fi/page/034390
http://id.loc.gov/authorities/subjects/sh85063439
https://en.wikipedia.org/wiki/Hydrogeology

Tieteen termipankissa nämä ovat erikseen, mutta määritelmät ovat varsin samankaltaiset. Erona on lähinnä se, että hydrogeologia ajatellaan kuuluvaksi geologian alaan ja geohydrologia hydrologian alaan. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Tieteen termipankki: http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:geohydrologia http://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:hydrogeologia

**Comment by ilona-x** [comment]
**Geohydrologia, pohjavesihydrologia** 
Tutkimushaara, joka käsittelee maanpinnan alaisia vesiä lähinnä hydrologisiin ympäristötekijöihin painottuen ja veden kiertokulkua selvittäen.

**Hydrogeologia**
Luonnontiede, joka tutkii pohjaveden ja sen geologisen ympäristön vuorovaikutussuhteita ja pohjavesi-ilmiöitä, erityisesti geologisten tekijöiden vaikutusta pohjaveden fysikaaliseen käyttäytymiseen ja kemialliseen koostumukseen.

Lähde: Kinnunen, T. (toim.). 2005 Pohjavesitutkimusopas: käytännön ohjeita. Suomen vesiyhdistys, Helsinki.http://www.vesiyhdistys.fi/pdf/Pohjavesiopas.pdf

**Comment by mariaforsen** [comment]
SAOssa molemmat. Nationalencyklopedin: "...Ibland används termen synonymt med hydrogeologi, som dock lägger större tonvikt vid geologiska förhållanden."
https://termipankki.fi/tepa/fi/haku/geohydrologi
En kannata yhdistämistä.

**Comment by ilona-x** [comment]
Ehdotuksessa lukee, että "UDK:ssa nämä on yhdistetty." 
Menevät näköjään samaan udk-luokkaan "**556.3 Pohjavesi. Geohydrologia. Hydrogeologia**", mutta nähdäkseni niitä ei muuten ole "yhdistetty". 🤔

**Comment by mirmaid** [comment]
Tämä kokonaisuus käytiin edellisen kerran läpi melko vähän aikaa sitten. https://github.com/Finto-ehdotus/YSE/issues/6919

**Comment by YSO-kokous** [comment]
Ei nähty tarvetta muutokselle. Asia jo kertaalleen käsitelty.
