### ISSUE TITLE
alumiiniveneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8459]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alumiiniveneet 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suomen ensimmäiset alumiiniveneet 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [alumiiniveneet](http://finto.fi/yse/fi/page/Y508459)

**Comment by ilona-x** [comment]
MAO: alumiiniveneet http://www.yso.fi/onto/mao/p9440

Jos tämä otetaan, voisiko samalla ottaa myös MAOsta löytyvät:
lasikuituveneet http://www.yso.fi/onto/tao/p1946
kumiveneet http://www.yso.fi/onto/mao/p3957

--

Melinda:
alumiiniveneet x 5
kumiveneet x 31
lasikuituveneet x 6

--

lasikuituveneitä ehdotettu aiemmin: https://github.com/Finto-ehdotus/YSE/issues/1191

**Comment by mirmaid** [comment]
YSOssa on _puuveneet_ ja _muoviveneet_.

**Comment by mariaforsen** [comment]
Sv. 
-aluminiumbåtar
-gummibåtar
-glasfiberbåtar
