### ISSUE TITLE
sonaattimuoto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8461]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sonaattimuoto](http://www.yso.fi/onto/ysa/Y104366) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan/muutetaan yksi huomautuksista. 

#### Perustelut ehdotukselle   

Termillä on nyt 2 eri huomautusta, epäselvää mikä niistä pätee. 
-Sävellysmuoto, joka vakiintui 1700-luvun jälkipuoliskolla. Sonaattimuodossa on kolme vaihetta: johdantojakso, kehittelyjakso ja kertausjakso, jotka sisältävät pää- ja sivuteemojen variaatioita eri sävellajeissa.
-Varsinkin sonaattien, sinfonioiden ym. sarjasävellysten (ääri)osissa esiintyvä rakenne, johon kuuluu kolme tai neljä määrämuotoista jaksoa.

**Comment by MUUSA-kokous** [comment]
Huomautus ja lähdetieto voidaan poistaa.

**Comment by YSO-kokous** [comment]
Tehdään Muusan ehdottamalla tavalla.
