### ISSUE TITLE
allokointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8462]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[allokointi](http://www.yso.fi/onto/ysa/Y100694) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

allokointi nyt vain taloustieteen ryhmässä ja englanniksi allocation (economics)
Pitäisikö allokoinnilla olla suomeksikin tarkenne?

(lisäksi YSOssa kohdentaminen eng. allocation (active) & kohdentuminen eng. allocation (passive) & resursointi eng. resource allocation) 

#### Perustelut ehdotukselle   

allokointia käytetty Melindassa myös tietoliikennetekniikan aineistoissa esim. https://melinda.kansalliskirjasto.fi/byid/011419933

https://fi.wikipedia.org/wiki/Allokaatio

Tieteen termipankissa biologian terminä: http://tieteentermipankki.fi/wiki/Biologia:allokointi
ja myös tätä biologian allokointia taitaa löytyä muutama tapaus Melindasta: https://melinda.kansalliskirjasto.fi/byid/002405265 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi allokering on ensisijaisesti taloudellinen termi.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: allokoiminen, kohdentaminen.

Wikisanakirja: erit. taloudessa kohdentaa, suunnata ja jakaa rajalliset voimavarat vaihtoehtoisiin käyttötarkoituksiin

_Kohdentaminen_ on sanastossa erikseen ja sillä huomautus: Talouden yhteydessä käytä allokointi.

**Comment by mirmaid** [comment]
Allokointi ei varmaankaan ole kuitenkaan korvattavissa kohdentamisella kaikkien muiden kuin talousalan aineistojen osalta...

**Comment by mirmaid** [comment]
Allokoinnin merkitys taitaa olla melkolailla sama kuitenkin aina, jopa biologiassa. Eli ongelma on osittainen päällekkäisyys kohdentamisen kanssa? Jos rajataan tarkenteella vain talouteen, sen sisälläkin on monia erilaisia konteksteja sijoittajan riskinhallinnasta tietyn valtion kehitysapupolitiikkaan ja kunnallistalouteen. 

Ks. myös https://en.wikipedia.org/wiki/Resource_allocation

**Comment by mirmaid** [comment]
Jos _allokoinnin_ ja _kohdentamisen_ ero hahmottuu suunnilleen samoin suomeksi ja ruotsiksi, tyytyisin ehkä poistamaan huomautuksen ja lisäämään ryhmiä allokoinnille. 

Eli allokoinnissa (rajallisia) resursseja jaetaan useille kohteille tai useisiin tarkoituksiin. Kohdentamisessa jotakin kohdistetaan/suunnataan johonkin tai joihinkin tiettyihin kohteisiin. Ja molemmat käsitteet voivat kyllä esiintyä myös samoissa viitteissä, koska toki resursseja voidaan sekä allokoida että kohdentaa.

**Comment by mariaforsen** [comment]
Allokera on sanakirjan https://svenska.se/tre/?sok=allokera&pz=1 mukaan ruotsiksi:
1 rationellt fördela varor el. resurser; särsk. i fråga om pol. åtgärder för att utjämna skillnader mellan olika områden
2 reservera (utrymme i datorminne) för datamängd 
ks. myös https://sv.wikipedia.org/wiki/Minnesallokering Tämä on ainakin joidenkin sanakirjojen mukaan suomeksi muistinvaraus?

**Comment by mirmaid** [comment]
^ Näyttää siltä (hyvin pikaisesti katsottuna), että suomeksikin voitaisiin puhua myös muistinvarauksen yhteydessä allokoinnista.

**Comment by ilona-x** [comment]
YSOssa myös:

resursointi http://www.yso.fi/onto/yso/p24562
en resource allocation
sv resursallokering

00 Yleistermit
75 Taloustieteet. Kansantalous. Liiketalous. Kauppa

**Comment by mirmaid** [comment]
Kuulostaa, että käännösvastineet ovat vähän suppeita?

**Comment by ilona-x** [comment]
tässä yksi tietoliikennetekniikan väitös, jossa tarve allokoinnille: http://urn.fi/URN:ISBN:978-952-64-0615-2

**Comment by ilona-x** [comment]
LCSHssa Resource allocation, joka linkattu YSOn resursointi-käsitteeseen
Resource allocationin alakäsitteenä esim. [Radio frequency allocation](http://id.loc.gov/authorities/subjects/sh85110473) & [Radio resource management (Wireless communications)](http://id.loc.gov/authorities/subjects/sh2008004985)

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Allokaatio
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4041212f0756faa7efc9a7a4dddbdf6e&list_id=1&keyword=allokointi&word=allokointi

**Comment by mirmaid** [comment]
^^ Eli englanniksi ainakin korjattava.

**Comment by mirmaid** [comment]
Oma ehdotukseni siis kootusti:

- resursointi: tarkistetaan kielivastineet ja linkitys. Jos tarpeen, jatketaan erillisessä issuessa.
- kohdentaminen: korjataan englanninkielinen termi. Poistetaan huomautus.
- allokointi: lisätään ryhmiä

**Comment by mariaforsen** [comment]
Mietitään ruotsiksi olisiko myös resursfördelning KÄYTÄ resursallokering? Tai myös mahdollisesti muutos resursallokering KÄYTÄ resursering tai resursfördelning? Kohdentaminen saattaa muuttua myös ruotsiksi, mutta se katsotaan sen jälkeen kun tai jos kohdentuminen poistuu. Mitä ryhmiä voi suomen kannalta lisätä allokoinnille? Ruotsiksi ainakin tilastotiede. 

Onko mahdollista välttää allokoinnin ja resursoinnin päällekkäistä käyttöä, esim. ohjaamalla allokointi (varat tai resurssit)? Sitä ajatellen että ruotsiksi resursointi on nyt resursallokering, joten käyttö ei nyt välttämättä täysin täsmää, eli ruotsiksi käytetään resursallokering fi. resursointi kun kyseessä on varojen allokointi, mutta suomeksi käytetään vastaavassa tapauksessa allokointi?

**Comment by mirmaid** [comment]
^ Mä kyllä ymmärrän allokoinnin niin, että siinä aina on kyse jonkinlaisesta resurssista, jota jaetaan tietyille kohteille. Resurssointi taas on mitä vaan resurssien hankintaa - allokoinnissa on valmiina jokin potti, josta jaetaan, kun taas resurssointi voi lähteä siitä, että ei ole mitään valmiina vaan suoritetaan varainhankintaa. Toki resurssointi voi tapahtua myös "ylhäältäpäin" olemassaolevista varoista tms., mutta siinä ei ole olennaista se, että jostain isommasta kokonaisuudesta lohkaistaan jotain juuri tähän tarkoitukseen, kuten allokoinnissa.

**Comment by mirmaid** [comment]
Resurssointi / allokointi Melindassa?

**Comment by mariaforsen** [comment]
Jos tämä merkitysero on suomeksi selvä, niin tilanne voidaan varmaan ratkaista muuttamalla sv. resursallokering KÄYTÄ resursering/resursfördelning. (Kohdentamisen sv. on jo muutettu > riktande)
Vai olisiko siis ok ohjaustermi **"resurssien allkointi" KÄYTÄ allokointi**?

**Comment by mirmaid** [comment]
Varmaan _resurssien allokointi_ olisi mahdollinen ohjaustermi _allokoinnille_.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ohjaustermi _resurssien allokointi_.
