### ISSUE TITLE
neoplastismi tai uusplastismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8464]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

neoplastismi tai uusplastismi 

#### Vaihtoehtoiset termit ja ilmaisut   

uusplastismi 

#### Tarkoitusta täsmentävä selite   

Neoplastismi on taiteellinen virta, jonka Piet Mondrian kehitti vuonna 1917 Alankomaissa yhteistyössä Theo van Doesburgin kanssa. ...  Geometristen muotojen, koneiden ja viivojen ainutlaatuinen käyttö. Yleensä teoksissa vallitsevat geometriset muodot ovat neliöitä ja suorakulmioita.

- Käyrät ja muotojen ja viivojen järjestäminen ei ole kohtisuorassa siten, että työssä muodostuu vain oikeat kulmat.

- Ensisijaisten värien käyttö (keltainen, sininen ja punainen) sekä neutraalit värit (valkoinen, musta ja harmaa). Valot tai varjot eivät muuta värejä, ja taustat ovat yleensä selkeitä. 

#### Perustelut ehdotukselle   

Abstraktin taiteen suuntaus. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirja: Pääsky: The evening is over, the beauty remains 

**Ehdottajan organisaatio:** KB **Termiehdotus Fintossa:** [neoplastismi tai uusplastismi](http://finto.fi/yse/fi/page/Y508464)

**Comment by ilona-x** [comment]
MAOssa: **neoplastismi** http://www.yso.fi/onto/mao/p6947

**Comment by mariaforsen** [comment]
Sv. neoplasticism

**Comment by mirmaid** [comment]
Neoplastismi Melindassa 9 kertaa.

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa neoplastismi.
