### ISSUE TITLE
jumalat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8467]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jumalat](http://www.yso.fi/onto/ysa/Y95668) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan kielletty muoto 'jumala' 

#### Perustelut ehdotukselle   

Nyt kiellettynä muotona 'jumala', mutta on olemassa myös termi 'Jumala' http://www.yso.fi/onto/yso/p13849
Termien erona on vain iso ja pieni alkukirjain.
==> Kirjastojärjestelmät eivät tee eroa ison ja pienen kirjaimen välillä; automaattinen auktoriteettivalvonta antaa virheilmoituksen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Vaihtoehtoinen ratkaisuehdotus: otetaan kattavasti – siis muissakin kuin vain Alma-ohjelmaa hyödyntävissä kirjastoissa – käyttöön henkilö- ja yhteisönimien osalta sanastotunnus ("finaf"), jolloin auktoriteettitietueiden muodot (tässä tapauksessa "040f yso/fin + 150a jumalat + 450a jumala" vastaan "040f finaf + 100a Jumala") eivät olisi ristiriidassa.

Jumalasta henkilönä kenties pitäisi olla auktoriteetti ennemmin Asterissa kuin YSOssa – vai käsitelläänkö erisnimistä Jumalaa henkilönä laisinkaan esimerkiksi antiikin jumalien tapaan? Vrt. RDA, lähinnä luvut 9.6.1.6–9.6.1.9.

**Comment by mariaforsen** [comment]
Molemmat tarvitaan YSOssakin. Ja huom. vain YSO on myös ruotsinkielinen.

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/6434. Voiko tällaisessa tapauksessa edes tehdä toimija-auktoriteettia?

**Comment by YSO-kokous** [comment]
Lisätään _Jumala_-käsitteelle ohjautermiksi _Jumala (monoteistiset uskonnot)_. YSOn Jumala-käsite viittaa nimenomaan monoteististen uskontojen Jumalaan.
