### ISSUE TITLE
vahvuudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8468]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vahvuudet 

#### Vaihtoehtoiset termit ja ilmaisut   

luonteenvahvuus 
erityistaidot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[itsetunto](http://www.yso.fi/onto/yso/p266) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Suuri kirja vahvuuksista  9789523414365 

#### Perustelut ehdotukselle   

Itsetunnon vahvistamiseen. Tarinoit erilaisista luonteenvahvuuksista 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [vahvuudet](http://finto.fi/yse/fi/page/Y508468)

**Comment by mariaforsen** [comment]
Vahvuudet=styrkor, mutta YSOssa on jo styrka=voima.

**Comment by mirmaid** [comment]
N. 20 viitettä Melindassa. Kerran käytetty muodossa _vahvuudet (psykologia)_, mutta viitteistä noin puolet käsitteli erilaisten organisaatioiden tms. vahvuuksia.

**Comment by YSO-kokous** [comment]
Ei hyväksytä YSOon.

**Comment by mirmaid** [comment]
Palaute: En pysty ehdottamaan asiasanaa vahvuudet, koska siitä on ollut ehdotus aiemmin eikä sitä ole hyväksytty silloin. Kuitenkin sekä minä että kollegani olemme kaivanneet asiasanaa vahvuudet useampaan kertaan. Esimerkiksi kirja joka käsittelee erityisherkkyyttä ja erityisherkän vahvuuksia työelämässä. Vastapariksi löytyisi kyllä jo haasteet (ongelmat), toki voisi olla heikkoudetkin, jos halutaan suorempi pari vahvuuksille. Ehdotamme siis että vahvuudet otetaan uudelleen käsittelyyn tai ainakin perustellaan miksi ei oteta tai mikä käsite ajaisi asian.

**Comment by mariaforsen** [comment]
Entä psykologinen vahvuus, olisiko se mahdollinen muoto?

**Comment by LeKorsu** [comment]
> Entä psykologinen vahvuus, olisiko se mahdollinen muoto?

Ei ollenkaan huono vaihtoehto.

**Comment by tpalonen** [comment]
Tai _vahvuudet (psykologia)_? Psykologinen vahvuus viittaa terminä yksilön vahvuuteen kokonaisuudessaan, eli vastaa kysymykseen miten vahva yksilö on psyykkisesti, mutta vahvuudet monikossa ovat yksilön yksittäisiä piirteitä, yksittäisiä taitoja, yksittäisiä luonteenpiirteitä yms ja luulen, että tässä haettiin enemmän tällaista.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _vahvuudet (psykologia)_.

**Comment by mariaforsen** [comment]
Sv. styrkor (psykologi) HT psykologiska styrkor
