### ISSUE TITLE
teorianoppaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8469]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

teorianoppaat 

#### Vaihtoehtoiset termit ja ilmaisut   

"musiikinteoria (oppaat)" ; "teorianoppaat (musiikki)" 

#### Perustelut ehdotukselle   

"teorianopas" on käytössä manifestaation laajuuden (yksikön) terminä. Laajuuden yksiköillä "soitonopas" ja "laulunopas" on jo vastaava termi SLM:ssä (soitonoppaat, laulunoppaat). 

#### Tarkoitusta täsmentävä selite   

SLM sanastoon. Tarvitseeko tarkenteen? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Musiikinteorian oppaat (nuotit, kirjat) 

**Ehdottajan organisaatio:** Jyväskylän kaupunginkirjasto **Termiehdotus Fintossa:** [teorianoppaat](http://finto.fi/yse/fi/page/Y508469)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta muodossa _teorianoppaat (musiikki)_. KT teoriaoppaat

**Comment by tpalonen** [comment]
EDIT: KT _teoriaoppaat (musiikki)_

**Comment by mariaforsen** [comment]
Sv. teoriböcker (musik) ET teoriguider (musik) 
https://finto.fi/mts/fi/page/m2031

**Comment by mirmaid** [comment]
Hyväksytty SLM:ään. _Laulunoppaat_ ja _soitonoppaat_ ovat myös YSOssa, entä tämä?

**Comment by YSO-kokous** [comment]
Hyväksytty sulkutarkenteella (musiikki).
