### ISSUE TITLE
indeksointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8471]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[indeksointi](http://www.yso.fi/onto/ysa/Y95546) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Sisällönkuvailun osalta yhdistetään KÄ asiasanoitus. Lisäksi mahdollisesti tietokannan indeksointi (?). 

#### Perustelut ehdotukselle   

Nyt päällekkäisyyttä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Varmaan paras aloittaa siivoamalla joukosta ne, joissa kyse on selkeästi asiasanoituksesta.

**Comment by YSO-kokous** [comment]
Edetään mirmaidin ehdottamalla tavalla.

**Comment by mirmaid** [comment]
Varmaan voisi myös lisätä indeksointi (asiasanoitus) KÄ asiasanoitus?

**Comment by mirmaid** [comment]
Tämän tyyppistä aineistoa myös jonkin verran: https://en.wikipedia.org/wiki/Indexing_and_abstracting_service. Laitetaanko näihinkin asiasanoitus? Kyse voi periaatteessa olla myös muunlaisesta hakemistosta.

**Comment by mirmaid** [comment]
Otetaan _tietokannan indeksointi_ tai _indeksointi (tietotekniikka)_? Jälkimmäistä kannatettu Finton teknisessä tiimissä.

**Comment by mariaforsen** [comment]
Onko tämä sama kuin "automaattinen indeksointi"? 
SAO: https://id.kb.se/term/sao/Automatisk%20indexering
Eli LCSH:ssa automatic indexing

**Comment by mirmaid** [comment]
^ Eikö tuo olisi automaattinen sisällönkuvailu?

**Comment by mariaforsen** [comment]
"Automatic indexing is the computerized process of scanning large volumes of documents against a controlled vocabulary, taxonomy, thesaurus or ontology and using those controlled terms to quickly and effectively index large electronic document depositories."

**Comment by mariaforsen** [comment]
Eikö ole aika suuri riski että "indeksointi (tietotekniikka)" sekoitetaan myös muuhun kuin tietokannan indeksointi?

**Comment by ilona-x** [comment]
Melidna-korjausta tehdessä olisi hyvä, jos tietokannan indeksointia varten olisi oma termi jo käytettävissä, niin voisi samalla korjata indeksointi (asiasanoitus) KÄ asiasanoitus ja indeksointi (tietokannan) KÄYTÄ indeksoint (tietotekniikka) tai mikä termimuoto nyt sitten olisikaan.

**Comment by mirmaid** [comment]
Kaikki korjattu, _indeksointi_ voidaan poistaa.
