### ISSUE TITLE
Mummon kammari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8474]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Mummon kammari](http://www.yso.fi/onto/ysa/Y108568) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään tämä yhteisöauktoriteetti asiasanastosta Asteriin ja muutetaan samalla sen käyttö Marc 21 -fomaatin mukaisesti aiheena) 650-kentästä 610-kenttään. 

#### Perustelut ehdotukselle   

Nykyinen ratkaisu ei perustu formaattiin 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
KANTO: Mummon kammari http://urn.fi/URN:NBN:fi:au:finaf:000021316

**Comment by mariaforsen** [comment]
Kannatan, tätä ei jäädä kaipaamaan.

**Comment by mirmaid** [comment]
Alkujaan tämä on varmaan otettu YSAan rakennuksena, _organisaatiot_-yläkäsite on valittu YSOssa.

**Comment by ilona-x** [comment]
Kyse ilmeisesti Tampereen Mummon kammarista, joka on sijainnut tavallisen kerrostalon liiketilassa. Ja näyttää muuttaneen vanhasta sijainnistaan (Otavalankadulta) uuteen paikaan (Hämeenkadulle) v. 2019. Eli Tampereella ei ainakaan ole Mummon kammarina tunnettua rakennusta. 👵

**Comment by mirmaid** [comment]
^ Ei, mutta alun perin varmaan tulkittu niin, koska yhteisöjä ei kuitenkaan ole otettu YSAan laajemmin. Joitakin vastaavanlaisia tapauksia on (kyseessä ei varsinaisesti mikään merkittävä rakennus, mutta luultavasti ajateltu kuuluvan samaan ryhmään kuin sanastossa olevat museot tms. eli tulkittu viittaavan johonkin muuhun kuin selkeästi organisaatioksi miellettyyn). Mun puolestani voi siis poistaa, tämä vaan historiallisena selityksenä sille, miksi ko. käsite ylipäätään on sanastossa. Vastaavia on varmasti muitakin, mutta varsinaiseen etsimiseen ei kyllä tällä hetkellä ole aikaa.

**Comment by ilona-x** [comment]
Ok. Tämän poistaminen YSOsta olisi varmaan helpoimmasta päästä. Melindassakin suurin osa Mummon kammareista näytti olevan jo valmiiksi 610-kentässä. YSO-terminä käytetty vain 8 kertaa. Eikä ruotsinkielistä nimimuotoakaan ole olemassa.

**Comment by YSO-kokous** [comment]
Poistetaan Mummon kammari YSOsta.
