### ISSUE TITLE
uudelleensanoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8476]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uudelleensanoitukset 

#### Perustelut ehdotukselle   

Jos YSo niin myös SLM 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Prinsessa Pikkiriikin astetta paremmat loilotukset (nuotti) (SLM terminä) 

**Ehdottajan organisaatio:** Jyväskylän kaupunginkirjasto **Termiehdotus Fintossa:** [uudelleensanoitukset](http://finto.fi/yse/fi/page/Y508476)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ainakin SLM:ään muodossa _uudelleensanoitetut teokset_.
LT musiikki

**Comment by mariaforsen** [comment]
Mikä olisi vastaava termi englanniksi?

**Comment by krinay** [comment]
Teoksista en tiedä, mutta uudestisanoitetuista lauluista on käytetty englanninkielistä termiä _rewritten songs_ (tai _rewritten song lyrics_).

**Comment by YSO-kokous** [comment]
Palautetaan Muusalle kielivastineiden selvittämiseksi. Käsitteen kattavuus ja käyttö sekä määritelmä. Kattaako käännökset? Kattaako myös  uudelleensanoitetut oopperat?

**Comment by MUUSA-kokous** [comment]
Kyllä kattaa useat eri kielelle kirjoitetut sanoitukset mutta ei varsinaisia käännöksiä. Samoin uudelleensanoitetut oopperat.
ST käännösiskelmät

**Comment by YSO-kokous** [comment]
YSO-kokous ehdottaa Muusalle, että hyväksyttäisiin muodossa "uudelleensanoitetut laulut", jolloin saataisiin paremmin ruotsinkielinen ja englanninkielinen vastine.

**Comment by MUUSA-kokous** [comment]
"Uudelleensanoitetut laulut" ei kattaisi intuitiivisesti esim. kokonaisia oopperoita, joten ei kannateta tätä muotoa.

**Comment by jtuohini** [comment]
Vrt. LCGFT:n [**Musical parodies**](https://lccn.loc.gov/gf2014026955) -termin huomautus ja käyttöohje, varsinkin viimeiset kaksi virkettä: "Compositions that distort or exaggerate features of another composition or a composer’s works in general for humorous or satirical ends. For vocal works from the Middle Ages or Renaissance in which a new text has been substituted for the original without a significant change to the music see _Contrafacta_. For post-Renaissance songs in which a new text has been substituted for the original without a significant change to the music see _Song parodies_."

**Comment by ilona-x** [comment]
SLM/Hyväksytään uudelleensanoitetut laulut (sånger med ny text)

**Comment by mirmaid** [comment]
SLM:ssä ei ole termiä _käännösiskelmät_ (YSOssa on).

**Comment by YSO-kokous** [comment]
Otetaan YSOon KÄ uudelleensanoitetut laulut YK laulut.

**Comment by mirmaid** [comment]
Muusan näkemys tähän: https://github.com/Finto-ehdotus/YSE/issues/8476#issuecomment-902466072

**Comment by MUUSA-kokous** [comment]
> SLM:ssä ei ole termiä _käännösiskelmät_ (YSOssa on).

Ei tarvita termiä _käännösiskelmät_ SLM:ään. Musiikinkuvailussa ei ole tarvetta ottaa kantaa tekstin käännöksellisyyteen.
