### ISSUE TITLE
Pyreneiden niemimaan sota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8477]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pyreneiden niemimaan sota 

#### Ehdotettu termi ruotsiksi   

spanska självständighetskriget 

#### Ehdotettu termi englanniksi   

Peninsular War 

#### Vaihtoehtoiset termit ja ilmaisut   

Espanjan itsenäisyyssota [fin] 
Spanska befrielsekriget [swe] 
Spanska frihetskriget [swe] 
Spanska folkkriget [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sodat](http://www.yso.fi/onto/yso/p1271) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85099422> 
Wikidata : https://www.wikidata.org/wiki/Q152499 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Tarvetta kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/017433256 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Pyreneiden niemimaan sota](http://finto.fi/yse/fi/page/Y508477)

**Comment by mariaforsen** [comment]
Sv. spanska frihetskriget ET spanska frihetskriget 1807-1814 /sao, spanska självständighetskriget /wp
