### ISSUE TITLE
uppspelningshastighet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8478]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

uppspelningshastighet 

#### Ehdotettu termi suomeksi   

toistonopeus 

#### Ehdotettu termi englanniksi   

playback speed 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vid katalogisering av inspelningar. 

#### Perustelut ehdotukselle   

Behövs i termbanken för att man (t.ex. vid katalogisering) ska kunna ange vilken typ av tekniskt data man avser. 

#### Tarkoitusta täsmentävä selite   

https://termipankki.fi/tepa/sv/sök/uppspelningshastighet 

**Ehdottajan organisaatio:** Sibeliusmuseums arkiv/Stiftelsen för Åbo Akademi **Termiehdotus Fintossa:** [uppspelningshastighet](http://finto.fi/yse/fi/page/Y508478)

**Comment by mirmaid** [comment]
Onkohan ehdotus oikeastaan Metatietosanastoon?

**Comment by YSO-kokous** [comment]
Ei nähty tarvetta käsitteelle YSOssa, ei tarvetta aiheiden kuvailuun. Mikäli termiä tarvitaan Metatietosanastossa, sitä voi ehdottaa sinne osoitteessa: met-sanasto@helsinki.fi
