### ISSUE TITLE
inspelningshastighet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8479]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

inspelningshastighet 

#### Ehdotettu termi englanniksi   

recording speed 

#### Ehdotettu termi suomeksi   

tallennusnopeus  

#### Perustelut ehdotukselle   

Behövs vid katalogisering av inspelningar. 

#### Tarkoitusta täsmentävä selite   

https://termipankki.fi/tepa/sv/sök/inspelningshastighet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Termen behövs för att kunna ange vilken typ av teknisk data som avses. 

**Ehdottajan organisaatio:** Sibeliusmuseums arkiv/Stiftelsen för Åbo Akademi **Termiehdotus Fintossa:** [inspelningshastighet](http://finto.fi/yse/fi/page/Y508479)

**Comment by mirmaid** [comment]
Onkohan ehdotus oikeastaan Metatietosanastoon?

**Comment by YSO-kokous** [comment]
Ei nähty tarvetta käsitteelle YSOssa, ei tarvetta aiheiden kuvailuun. Mikäli termiä tarvitaan Metatietosanastossa, sitä voi ehdottaa sinne osoitteessa: met-sanasto@helsinki.fi
