### ISSUE TITLE
tiedevastaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8480]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tiedevastaisuus 

#### Perustelut ehdotukselle   

Termiä olisin kaivannut monen viimeisten vuosien aikana julkaistun kirjan kuvailussa. Kirjat ovat käsitelleet informaatiosodankäyntiä, valeuutisia, faktatietoa yms. En ole yso:sta keksinyt mitään vastaavaa termiä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Usean eri informaatiosodankäyntiä, valeuutisia ja faktatietoja käsittevien kirjan kuvailussa. 

**Termiehdotus Fintossa:** [tiedevastaisuus](http://finto.fi/yse/fi/page/Y508480)

**Comment by mariaforsen** [comment]
Sv. antivetenskap, vetenskapsskepticism..?

**Comment by LeKorsu** [comment]
Minä olen miettinyt rokotevastaisuus-termiehdotuksen lähettämistä, mutta himmaillut, kun olen miettinyt, että seuraako siitä tulva vastaisuus-loppuisia termiehdotuksia. (Käsittelyssä ollut kirja: Jonathan Berman: Anti-vaxxers, MIT Press 2020). En siis vastusta tätä tiedevastaisuutta, mutta onko tämä -vastaisuus samanlainen keissi kuin "x:n opetus"?

**Comment by mirmaid** [comment]
Kerran Melindassa. Käytetty yhdistelmiä tiede + ennakkoluulot, asenteet, vastutus, kritiikki, uskomukset.

**Comment by mariaforsen** [comment]
Sv. 
-antivetenskap ET vetenskapsmotstånd, vetenskapsskepticism 
-vaccinmotstånd ET vaccinationsmotstånd, antivaccin, vaccinskepticism 
 https://sv.wikipedia.org/wiki/Vaccinationsmotst%C3%A5nd
