### ISSUE TITLE
Länsisatama (Helsinki : kaupunginosa)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8483]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Länsisatama (Helsinki : kaupunginosa) 

#### Ehdotettu termi ruotsiksi   

Västra hamnen 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/L%C3%A4nsisatama_(Helsinki) 

#### Perustelut ehdotukselle   

Helsingin 20. kaupunginosa
https://www.hel.fi/helsinki/fi/kaupunki-ja-hallinto/hallinto/kaupunginosat/lansisatama
Huom. ei löydy paikkatietoalustalta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

x 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Länsisatama (Helsinki : kaupunginosa)](http://finto.fi/yse/fi/page/Y508483)

**Comment by mirmaid** [comment]
Jäävätkö satamat YSO-paikkoihin? Jos ei, ei tarvita tarkennetta "kaupunginosa".

**Comment by ilona-x** [comment]
Eikös satamat päätetty auktorisoida YSO-paikkoihin 🤔 Vai onko tämä noussut uudelleen keskusteluun. Löysin muistion v. 2019, jossa oli päätetty auktorisoida satamat paikkoina.

**Comment by mirmaid** [comment]
Varmistetaan toimijakuvailusta.

**Comment by ilona-x** [comment]
Kun tämä kaupunginosa auktorisoidaan, pitäisi sen alakäsitteiksi lisätä seuraavat osa-alueet:
Ruoholahti 
Salmisaari 
Lapinlahti 
Jätkäsaari 
Hernesaari 
https://fi.wikipedia.org/wiki/L%C3%A4nsisatama_(Helsinki)

**Comment by mirmaid** [comment]
Länsisatama (Helsinki : kaupunginosa)

**Comment by ilona-x** [comment]
Länsisatama (Helsinki : kaupunginosa)
Länsisatama (Helsinki : satama)
