### ISSUE TITLE
ihmisjäännökset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8484]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ihmisjäännökset 

#### Ehdotettu termi englanniksi   

Human remains (Archaeology) 

#### Ehdotettu termi ruotsiksi   

mänskliga kvarlevor 

#### Vaihtoehtoiset termit ja ilmaisut   

ihmisjäänteet 
vainajat 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[arkeologia](http://www.yso.fi/onto/yso/p1265) 

#### Alakäsitteet (RT)   

[muumiot](http://www.yso.fi/onto/yso/p2193) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh92003545.html 
SAO : https://id.kb.se/term/sao/M%C3%A4nskliga%20kvarlevor 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Tarkoitusta täsmentävä selite   

Jäännös  on  arkeologiassa  perinteisesti  käytetty termi,  jolla  tarkoitetaan  säilynyttä  osaa  muutoin  kadonneesta  kokonaisuudesta. Ihmisjäännös ihmisruumiin  osia kuten luita, muumioituneita ruumiinosia tai kokonaan muumioituneita vainajia. Ks. Ihmisjäännökset suomalaisissa museoissa kyselytutkimus säilyttämiseen ja esittelyyn liittyvistä käytännöistä / Sofia Paasikivi 2014 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1h3k2rg/alma9932142133506253 

#### Perustelut ehdotukselle   

Aiemmin käytössä ollut vainajat-käsite on muuttunut ohjaustermiksi, eikä uusi KT kuolleet sovi arkeologiseen kontekstiin. Esim. Helka-tietokannassa Human remains haku kirjaston kokoelmiin tuottaa yli 500 osumaa. 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [ihmisjäännökset](http://finto.fi/yse/fi/page/Y508484)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by FinMeSHienPaimentaja** [comment]
Btw MeSH:inä on "Body Remains", FinMeSH prio "ruumis"

https://meshb.nlm.nih.gov/record/ui?ui=D000071298

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
