### ISSUE TITLE
päivätyöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8485]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[päivätyöt](http://www.yso.fi/onto/ysa/Y111033) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pitäisikö ohjaustermille taksvärkki lisätä jokin tarkenne? Törmäsin tietueeseen, jossa oli asiasana päivätyöt ja teos käsitteli taksvärkkikeräystä, ei päivätyötä.

Lisäksi jäin miettimään, onko päivätyöt -termin merkis ylipäänsä selkeä. Päivätyöt-termiä käytetty Melindassa 29 kertaa ja suurin osa näyttäisi olevan taksvärkkikeräystä. 

#### Perustelut ehdotukselle   

Kielitoimiston sanakirja:

taksvärkki
1. hist. = päivätyö 4.
2. = taksvärkkikeräys. 

päivä­työ
1. päivällä suoritettava työ.
Iltatöiden lisäksi hänellä on normaali päivätyö.
2. päivittäinen työ, päivän työ; se työmäärä, joka päivässä voidaan t. on tapana tehdä, työpäivä.
Päästä levolle raskaan päivätyön jälkeen.
3. kuv. elämäntyö.
Tehdä jllak alalla arvokas, pitkä päivätyö.
Pitkän päivätyön tehnyt vanha hevonen.
4. hist., tav. mon. yhden henkilön yhtenä päivänä suorittama työ veron, vuokran tms. vastikkeena, taksvärkki.
Hevos-, jalkapäivätyö.
Oli, kävi kartanossa päivätöissä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Dagsverke: "mängd arbete som normalt kan ut­föras av en person på en dag" eli pivätyön merkitys nro 2 ja käy myös historialliseen merkitykseen eli nro 4.

**Comment by mirmaid** [comment]
Varmaankin kannattaisi ottaa sanastoon _taksvärkkikeräys_ ja miettiä uusi ratkaisu jäljelle jääville viitteille?

**Comment by YSO-kokous** [comment]
Otetaan taksvärkkikeräys uutena käsitteenä YSOon, korjataan päivätyöt-käsitteen kuvailu ja katsotaan, tarvitaanko tämän jälkeen vielä muutoksia.

**Comment by mariaforsen** [comment]
Sv. dagsverkesinsamling ET dagsverksinsamling, operation dagsverke 
https://sv.wikipedia.org/wiki/Operation_Dagsverke 
https://unicef.se/fragor/vad-ar-operation-dagsverke

**Comment by mirmaid** [comment]
Korjattu, jäljelle jäi 12 viitettä.

**Comment by mariaforsen** [comment]
Kannatan termin säilyttämistä historiallisessa merkityksessa (lisätään tarkenne (historia) tms?) 
Tämä historiallinen käsite on myös SAOssa: https://id.kb.se/term/sao/Dagsverken
https://fi.wikipedia.org/wiki/Taksv%C3%A4rkki
