### ISSUE TITLE
terveyshaitat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8486]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[terveyshaitat](http://www.yso.fi/onto/ysa/Y182396) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "terveydelliset haittavaikutukset" 

#### Perustelut ehdotukselle   

Yleisesti käytetty ilmaus, josta olisi hyvä viitata asianmukaiseen asiasanaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
