### ISSUE TITLE
työvoimapalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8487]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työvoimapalvelut](http://www.yso.fi/onto/ysa/Y99837) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

voisiko lisätä KT työllisyyspalvelut & mahdollisesti myös KT TE-palvelut? 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

https://www.google.com/search?q=ty%C3%B6llisyyspalvelut
https://www.te-palvelut.fi/

**Comment by YSO-kokous** [comment]
Hyväksytään molemmat ohjaustermit.
