### ISSUE TITLE
esitystekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8488]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[esitystekniikka](http://www.yso.fi/onto/ysa/Y179743) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
olisiko tähän mitään tarkempia tietoja/perusteluja?

**Comment by mirmaid** [comment]
Eli käytetty sekä teknisestä välineistöstä, että esiintymistaitoon liittyen (esim. https://melinda.kansalliskirjasto.fi/byid/006809826). Ehdotuksessa olisi kyllä voinut olla kysymysmerkki mukana, eli onko tämä ongelma. Voi myös yrittää lisätä ohjaustermejä.

**Comment by tpalonen** [comment]
Ajattelitko @mirmaid että tämä esiintymistaitotekniikka kattaisi myös soittotekniikan? Soittotekniikalle voisi olla tarvetta sellaisenaankin.

**Comment by mirmaid** [comment]
^ Ehkä huomasin tämän siinä yhteydessä, kun mietin tuota soittotekniikkaa.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermejä, esim. esitystekniikka (esitystaito) KÄYTÄ esiintymistaito tms.
