### ISSUE TITLE
sellomusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8489]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sellomusiikki 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/299824 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sellomusiikki](http://finto.fi/yse/fi/page/Y508489)

**Comment by MUUSA-kokous** [comment]
Kannatetaan.
Määritelmäehdotus: "Musiikki, joka on sävelletty tai sovitettu yhdelle tai useammalle sellolle tai muulle kokoonpanolle, jossa sello on keskeisessä osassa."

**Comment by mariaforsen** [comment]
Sv. cellomusik

**Comment by YSO-kokous** [comment]
Otetaan sellomusiikki sanastoon. Hyväksytään Muusan ehdottama määritelmä.
