### ISSUE TITLE
marginalisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#849]
#### Ehdotettu termi suomeksi

marginalisaatio
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 17.12.2002

**Muokkauspäivämäärä:** 9.12.2004, 17.12.2002, 8.7.2004, 25.2.2008, 16.12.2008, 11.6.2009, 30.05.2012

**Voyager-id:** 122268

**Termiehdotus Fintossa:** [marginalisaatio](http://finto.fi/yse/fi/page/Y322268)

**Comment by tarjaturunen** [comment]
Kannnatan marginalisaatio -asiasanan ottamista käyttöön. On käytetty vapaana asiasanana Melindassa 7ssä viitteessä. Olisi tarvittu asiasanana seuraavassa väitöskirjasssa https://melinda.kansalliskirjasto.fi/byid/017861121

**Comment by jarmosaarikko** [comment]
Onko tarpeen? RIittääisikö ohjausterminä, kun  _marginalisering_ on jo ohjausterminä käsitteessä **[syrjäytyminen](http://www.yso.fi/onto/yso/p8917), utslagning, social exclusion**
* https://fi.wikipedia.org/wiki/Syrj%C3%A4ytyminen
* https://en.wikipedia.org/wiki/Social_exclusion : "Social exclusion or social **marginalisation** is the social disadvantage and relegation to the fringe of society. "

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/sv/s%C3%B6k/marginalisering

**Comment by YSO-kokous** [comment]
marginalisaatio (syrjäytyminen) KÄ syrjäytyminen

**Comment by ilona-x** [comment]
marginalisoituminen #1985
