### ISSUE TITLE
olkaluu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8490]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

olkaluu 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/291871 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [olkaluu](http://finto.fi/yse/fi/page/Y508490)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D006811

**Comment by mariaforsen** [comment]
Sv. överarmsben
