### ISSUE TITLE
Kulttuuritalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8491]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kulttuuritalo](http://www.yso.fi/onto/ysa/Y111099) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kulttuuritalo (Helsinki) 

#### Perustelut ehdotukselle   

Nyt sama termi sekä kiellettynä että sallittuna:
150 $$a Kulttuuritalo $$0 http://www.yso.fi/onto/yso/p9632

150 $$a kulttuuritalot $$0 http://www.yso.fi/onto/yso/p9633
450 $$a kulttuuritalo

Estää automaattisen auktoriteettivalvonnan Almassa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan tarkenteen lisäämistä suomeksikin, muissakin kaupungeissa ja kunnissa kuin Helsingissä puhutaan "Kulttuuritalosta". Käytetty Melindassa esim. Kaarinan kulttuuritalosta

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
