### ISSUE TITLE
Hoppula

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8492]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Hoppula 

#### Tarkoitusta täsmentävä selite   

"Kadonnut" kylä Kemijärvellä Kemijoen varressa. Näkyy kartassa paikannimenä ja taloryhmänä yhä. Sijaitsi Juujärven pohjoispuolella, Juukosken luona. Katosi Seitakorva voimalaitoksen rakentamisen myötä 1960-luvun alussa. 

#### Perustelut ehdotukselle   

Paikannimi, entinen kylän nimi. Näkyy kartalla yhä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

paikallishistoriallinen aineisto 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Hoppula](http://finto.fi/yse/fi/page/Y508492)

**Comment by ilona-x** [comment]
Paikkatietoalusta: Kylä tai kulmakunta http://paikkatiedot.fi/so/1000772/10495891

**Comment by mirmaid** [comment]
Auktorisoidaan.
