### ISSUE TITLE
Juukoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8493]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Juukoski 

#### Tarkoitusta täsmentävä selite   

"Entinen" koski Kemijoessa, Juujärven pohjoispuolella. Katosi Seitakorvan rakentamisen myötä 1960-luvun alussa. Koskessa virtaa toisinaan yhä vettä säännöstelytilanteesta riippuen. 

#### Perustelut ehdotukselle   

Maantieteellinen paikka 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

paikallishistoriallinen aineisto 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Juukoski](http://finto.fi/yse/fi/page/Y508493)

**Comment by ilona-x** [comment]
Paikkatietoalustalla Juukoski "Muu maastopaikka" http://paikkatiedot.fi/so/1000772/10495786

**Comment by mirmaid** [comment]
RT Kemijoki

**Comment by mirmaid** [comment]
Korjattava vielä Juujärvet...
