### ISSUE TITLE
kirkkaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8498]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kirkkaus](http://www.yso.fi/onto/ysa/Y102528) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT luminositeetti 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Tai ehkä erikseen: https://en.wikipedia.org/wiki/Luminosity

 _The luminosity of a star is its intrinsic brightness, that is, the amount of energy that the star radiates per second in all directions. Also referred to as absolute brightness or absolute magnitude._

_The apparent brightness of a star is how bright it actually appears to an observer. Technically, it is the amount of energy per second from a star that strikes a square centimeter of a detector (retina of the eye, photographic plate, charge-coupled device CCD) per second. Also referred to as apparent magnitude._

**Comment by mariaforsen** [comment]
Kirkkaus=luminositet /YSO

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/luminosity
valoisuus; valoteho; värin kirkkaus

**Comment by ilona-x** [comment]
MOT Englannin tekniikka ja kauppa; en-su
luminosity
1 valoteho, valovoima
2 värin kirkkaus
3 valaist valoisuus

YSOssa myös valovoima (eng luminous intensity sv ljusstyrka) http://www.yso.fi/onto/yso/p18225

**Comment by YSO-kokous** [comment]
Tutkitaan vielä ja palataan asiaan myöhemmin.

**Comment by mirmaid** [comment]
Tämä taisikin avata hiukan isomman ongelman, koska kirkkaus on käytetty myös esim. vesistä (vrt. MOT ruotsi = klarhet). Käytetty vain 41 kertaa Melindassa, joten korjattavaa on onneksi vähän.

**Comment by fantsby-m** [comment]
eri käsitteitä tukee tämäkin:
https://fi.wikipedia.org/wiki/Luminositeetti
myös sv:
https://sv.wikipedia.org/wiki/Luminositet

**Comment by mirmaid** [comment]
Riittäisikö veden osalta _sameus_, https://fi.wikipedia.org/wiki/Sameus. Melindan 42 viitteestä 11:ssa on aiheena veden kirkkaus/sameus.

**Comment by mirmaid** [comment]
Muutamissa yksittäisissä viitteissä kirkkautta käsitellään runouden tai uskonnon kontekstissa, niissä riittänevät muut termit.

**Comment by mirmaid** [comment]
Tähtitieteen osalta usein oikeampi olisi suomeksikin _luminositeetti_ (KT kirkkaus (luminositeetti), säteilyteho). Muutaman kerran kyseessä kuitenkin tämä: https://en.wikipedia.org/wiki/Apparent_magnitude.

**Comment by mirmaid** [comment]
Joitakin artikkeleita näytön kirkkaudesta, lisäksi kourallinen viitteitä kirkkauden havaitsemisesta.

**Comment by LeKorsu** [comment]
Kannatan tähtitieteellisen kirkkauden eli luminositeetin ottaminen omaksi käsitteekseen.

**Comment by mariaforsen** [comment]
Ruotsiksi käytetään näytön kirkkaudesta termiä ljusstyrka (suomeksi valonvoimakkuus?), joka on YSOssa valovoima, myös ongelmallinen tapaus?
Kannatan ainakin luminositeetti=luminositet erillisenä. Ruotsiksi tosiaan eri termi näille eri merkityksille.

**Comment by YSO-kokous** [comment]
### Päätös
Otetaan uusi käsite: luminositeetti  KT kirkkaus (luminositeetti)
Poistetaan käsite kirkkaus
veden kirkkaus, kirkkaus (vesi) KÄYTÄ sameus
