### ISSUE TITLE
kertymäkiekot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8499]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kertymäkiekot 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Kertym%C3%A4kiekko 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Super-critical accretion onto black holes and neutron stars 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kertymäkiekot](http://finto.fi/yse/fi/page/Y508499)

**Comment by mariaforsen** [comment]
Sv. ackretionsskivor ET insamlingsskivor

**Comment by mirmaid** [comment]
Melindassa kerran yksikössä.

LCSH: Accretion (Astrophysics) ja Protoplanetary discs

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
