### ISSUE TITLE
madonna (Jeesuksen äiti)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8500]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

madonna (Jeesuksen äiti) 

#### Ehdotettu termi ruotsiksi   

madonna 

#### Ehdotettu termi englanniksi   

madonna 

#### Vaihtoehtoiset termit ja ilmaisut   

neitsyt Maria 
Jumalan äiti 
Maria (Jeesuksen äiti) 

#### Perustelut ehdotukselle   

Esiintyy mm. taiteessa, painokuvissa, kirjoissa ja postikorteissa, joita museossa luetteloidaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

taide, postikortit, painokuvat, kirjat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [madonna (Jeesuksen äiti)](http://finto.fi/yse/fi/page/Y508500)

**Comment by vthuhtal** [comment]
On jo Asterissa: Maria, Jeesuksen äiti (FIN11)000105935

**Comment by mirmaid** [comment]
KANTO: http://urn.fi/URN:NBN:fi:au:finaf:000105935
