### ISSUE TITLE
buurisota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8505]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[buurisota](http://www.yso.fi/onto/ysa/Y106333) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan käsite kahtia. 

#### Perustelut ehdotukselle   

Sotia on ollut kaksi ja käsitettä on käytetty Melinda-kuvailussa molempien yhteydessä.
https://en.wikipedia.org/wiki/First_Boer_War
https://en.wikipedia.org/wiki/Second_Boer_War

Melinda-esimerkit:
Ensimmäinen buurisota: The Transvaal Rebellion : the first Boer War, 1880-1881 / John Laband.
Toinen buurisota:The boer war 1899-1902 / Gregory Fremont-Barnes. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Sv. första boerkriget, andra boerkriget

**Comment by LeKorsu** [comment]
Vai vuosilukutarkenteet perään niin kuin Afganistanin sodissa  ja Kiinan-Japanin sodissa on? Voisi olla helpommin hahmotettavissa vuosilukujen avulla.

**Comment by mirmaid** [comment]
Tässä on vähän hajontaa, sanastossa myös _ensimmäinen Saksan-Tanskan sota, toinen Saksan-Tanskan sota_.

**Comment by YSO-kokous** [comment]
Tehdään seuraava jako:
- käytettäväksi termiksi ensimmäinen buurisota, ohjaustermiksi buurisota (1880-1881)
- käytettäväksi termiksi toinen buurisota, ohjaustermiksi buurisota (1899-1902)
