### ISSUE TITLE
PASS-teorin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8508]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[PASS-teorin](http://www.yso.fi/onto/allars/Y44296) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermi 'PASS' poisto, sillä on olemassa
pass  http://www.yso.fi/onto/yso/p16594 

#### Perustelut ehdotukselle   

Termi ei voi olla yhtä aikaa sallittu ja kielletty! 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi ohjausterminä on "PASS (rehabiliteringsteori)", ja se on aivan sallittua.
