### ISSUE TITLE
kroniskt obstruktiv lungsjukdom

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8509]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kroniskt obstruktiv lungsjukdom](http://www.yso.fi/onto/allars/Y42173) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermin 'KOL' poisto, sillä on olemassa
kol  http://www.yso.fi/onto/yso/p138 

#### Perustelut ehdotukselle   

Termi ei voi olla yhtä aikaa sallittu ja kielletty! 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätään tarkenne ohjaustermille.
