### ISSUE TITLE
säärystimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8510]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

säärystimet 

#### Ehdotettu yläkäsite YSOssa (LT)   

[asusteet](http://www.yso.fi/onto/yso/p10459) 

#### Assosiatiiviset (RT)   

[sukat](http://www.yso.fi/onto/yso/p15415) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Tarvitaan käsityöohjeiden kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Ieva Ozolina: Kirjovarsia ja pitsiunelmia : 50 latvialaista villasukka- ja säärystinmallia 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [säärystimet](http://finto.fi/yse/fi/page/Y508510)

**Comment by ilona-x** [comment]
MAOssa: säärystimet http://www.yso.fi/onto/mao/p428

**Comment by mirmaid** [comment]
90 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. benvärmare

**Comment by YSO-kokous** [comment]
Ei oteta damaskit-termiä ohjausterminä tai erillisenä käsitteenä.
