### ISSUE TITLE
navitoklaksi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8511]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

navitoklaksi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301606 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [navitoklaksi](http://finto.fi/yse/fi/page/Y508511)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Navitoclax

**Comment by mariaforsen** [comment]
Sv. navitoclax

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
