### ISSUE TITLE
translokaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8512]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

translokaatio 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301606 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [translokaatio](http://finto.fi/yse/fi/page/Y508512)

**Comment by mirmaid** [comment]
Mahdollisesti myös fuusiogeenit.

**Comment by mirmaid** [comment]
FinMeSH: translokaatio http://www.yso.fi/onto/mesh/D014178

**Comment by mariaforsen** [comment]
Sv. translokation /ne, mesh ET genetisk translokation

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
