### ISSUE TITLE
siemenpuut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8513]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

siemenpuut 

#### Ehdotettu termi ruotsiksi   

fröträd 

#### Ehdotettu termi englanniksi   

seed trees 

#### Ehdotettu yläkäsite YSOssa (LT)   

[puut (kasvit)](http://www.yso.fi/onto/yso/p8147) 

#### Assosiatiiviset (RT)   

[säästöpuut](http://www.yso.fi/onto/yso/p39008) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Seed_tree 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Männyn luontainen uudistaminen siemenpuumenetelmällä Lapissa / Mikko Hyppönen. 

#### Perustelut ehdotukselle   

Yleinen käsite 

**Termiehdotus Fintossa:** [siemenpuut](http://finto.fi/yse/fi/page/Y508513)

**Comment by AuHo22** [comment]
Siemenpuumetsikkö:
Metsä, jossa on käynnissä männyn luontainen uudistaminen. Alueelle on jätetty 50 – 150 siemenpuuta hehtaaria kohden, joiden tarkoituksena on siementää alueelle uusi taimikko
https://www.metsakeskus.fi/metsasanasto#R-S

**Comment by mirmaid** [comment]
AFOssa.

Melindassa 21 kertaa Agriforest-terminä, 6 kertaa vapaana avainsanana.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
