### ISSUE TITLE
punch needle -tekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8514]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

punch needle -tekniikka 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The punch needle handbook 

#### Perustelut ehdotukselle   

https://www.martat.fi/marttakoulu/kasityoohjeet/marttaraitavinkit/punch-needle-tekniikka/ 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [punch needle -tekniikka](http://finto.fi/yse/fi/page/Y508514)

**Comment by mariaforsen** [comment]
Sv. tuftning ET punch needle

**Comment by mirmaid** [comment]
Suomeksikin näköjään myös _tuftaus_.

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa tuftaus, ohjaustermiksi punch needle -tekniikka.
