### ISSUE TITLE
kiinteistöjohtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8515]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kiinteistöjohtaminen](http://www.yso.fi/onto/ysa/Y121982) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisäys eng. KT-muodoksi facility management 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Facility_management
https://id.loc.gov/authorities/subjects/sh85046812.html 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Lisätty
