### ISSUE TITLE
Kuuban vallankumous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8516]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kuuban vallankumous 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/306229 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Kuuban vallankumous](http://finto.fi/yse/fi/page/Y508516)

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85034586

**Comment by mirmaid** [comment]
10 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. kubanska revolutionen ET kubanska revolutionen 1959 /sao
