### ISSUE TITLE
kielentunnistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8517]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kielentunnistus 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301459?show=full 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kielentunnistus](http://finto.fi/yse/fi/page/Y508517)

**Comment by mariaforsen** [comment]
Sv. språkigenkänning ET automatisk språkigenkänning

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

https://fi.wikipedia.org/wiki/Kielentunnistus

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
