### ISSUE TITLE
Ansku

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8520]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ansku 

#### Ehdotettu termi ruotsiksi   

Antskog 

#### Ehdotettu termi englanniksi   

Antskog 

#### Vaihtoehtoiset termit ja ilmaisut   

Anskuu 

#### Perustelut ehdotukselle   

Suomen vanhimpia ruukkialueita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lisätietoja: https://fi.wikipedia.org/wiki/Ansku 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Ansku](http://finto.fi/yse/fi/page/Y508520)

**Comment by kouralex** [comment]
Tämä oli minun käsialaani. Testasin uudelta palvelimelta ehdotuslomaketta - näyttää toimivan.
