### ISSUE TITLE
Raasepori -- Fiskars

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8521]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Raasepori -- Fiskars](http://www.yso.fi/onto/ysa/Y179675) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Raasepori -- Fiskari 

#### Perustelut ehdotukselle   

Paikan suomenkielinen nimi on Fiskari, vaikkain Fiskars lienee tunnetumpi paikkakunnalta kotoisin olevan yhtiön ansiosta. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by kouralex** [comment]
Tämä on minun ehdotukseni. Testasin vielä toisen kerran uudelta palvelimelta ehdotuksien käyttöä.

**Comment by mirmaid** [comment]
Raaseporin kaupungin sivut?

**Comment by mirmaid** [comment]
Muutetaan > Fiskari
