### ISSUE TITLE
löytöeläimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8522]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[löytöeläimet](http://www.yso.fi/onto/ysa/Y111137) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT kodittomat eläimet 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Sama ohjaustermi myös heitteille jätetyt eläimet -käsitteelle?

**Comment by FinMeSHienPaimentaja** [comment]
Tähän liittyen: oma nyt jo edesmennyt koirani eksyi, joku ystävällinen ihminen sen sitten löysi ja otti huomaansa eli se oli siinä vaiheessa löytöeläin, mutta ei kuitenkaan koditon eläin (siinä mielessä kuin kulkukissat, kulkukoirat).

**Comment by YSO-kokous** [comment]
Lisätään seuraavat ohjaustermit:
kodittomat eläimet KÄYTÄ löytöeläimet
kodittomat eläimet KÄYTÄ heitteille jätetyt eläimet
