### ISSUE TITLE
varikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8523]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[varikot](http://www.yso.fi/onto/ysa/Y107123) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "arsenaalit" 

#### Perustelut ehdotukselle   

Ks. https://fi.wikipedia.org/wiki/Arsenaali 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Varikko - merkitys on laajempi kuin arsenaalin (sikäli kuin sillä viitataan asevarastoon).

**Comment by mariaforsen** [comment]
Arsenaler voidaan lisätä KT:ksi ainakin ruotsiksi, koska se voi viitata myös laajemmin kuin aseisiin ("tillgängligt förråd av hjälpmedel el. färdigheter")

**Comment by YSO-kokous** [comment]
Ei lisätä suomeksi ohjaustermiä.
