### ISSUE TITLE
Raamatun henkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8524]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Raamatun henkilöt](http://www.yso.fi/onto/ysa/Y94368) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "raamatulliset henkilöt" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
