### ISSUE TITLE
keskitysleirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8525]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keskitysleirit](http://www.yso.fi/onto/ysa/Y96104) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "tuhoamisleirit" tai tehdään sille oma asiasanansa 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja: 
tuhoamis­leiri
vars. natsi-Saksan niistä keskitysleireistä, joissa murhattiin suunnitelmallisesti hyvin suuria vankimääriä.

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by YSO-kokous** [comment]
Lisätään keskitysleirien ohjaustermiksi tuhoamisleirit.
