### ISSUE TITLE
kilpailut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8526]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kilpailut](http://www.yso.fi/onto/ysa/Y96166) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kilvat" 

#### Perustelut ehdotukselle   

Ks. https://www.kielitoimistonsanakirja.fi/#/kilpa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
