### ISSUE TITLE
parantolat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8527]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[parantolat](http://www.yso.fi/onto/ysa/Y103239) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "sanatoriumit", "sanatooriot" ja "sanatoriot" 

#### Perustelut ehdotukselle   

Ks. esim. https://www.wikidata.org/wiki/Q46124 ja https://fi.wikipedia.org/wiki/Hyvink%C3%A4%C3%A4n_parantola 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotetut ohjaustermit.
