### ISSUE TITLE
vaivaistalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8528]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vaivaistalot](http://www.yso.fi/onto/ysa/Y111991) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "köyhäintalot" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
