### ISSUE TITLE
yleisöakvaariot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8529]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yleisöakvaariot 

#### Ehdotettu termi englanniksi   

public aquariums 

#### Ehdotettu termi ruotsiksi   

öffentliga akvarier 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ihmisen määrittämät paikat](http://www.yso.fi/onto/yso/p347) 

#### Assosiatiiviset (RT)   

[akvaariot](http://www.yso.fi/onto/yso/p6076) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85006227> 
Wikidata : https://www.wikidata.org/wiki/Q2281788 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 
[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

Nykyinen YSO-asiasana vaikuttaa viittaavan (koti)akvaarioihin esineinä, ei eläintarhan kaltaisena vierailupaikkana. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [yleisöakvaariot](http://finto.fi/yse/fi/page/Y508529)

**Comment by jtuohini** [comment]
Ks. myös https://fi.wikipedia.org/wiki/Yleis%C3%B6akvaario

**Comment by mariaforsen** [comment]
Sv. offentliga akvarier ET allmänna akvarier, publika akvarier

**Comment by mirmaid** [comment]
Ei Melindassa, mutta _akvaariot_-käsitettä on käytetty myös näistä. Toki myös yleisöakvaariot koostuvat akvaarioista (=kala-altaista).

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Meriakvaario
Melindassa meriakvaariot x 45
Marine aquariums http://id.loc.gov/authorities/subjects/sh85081123

**Comment by YSO-kokous** [comment]
Otetaan sanastoon yleisöakvaariot. YSO-ylläpito miettii ohjaustermit, esim. akvaariot yleisölle KÄYTÄ yleisöakvaariot.

**Comment by jarmosaarikko** [comment]
Ehdotan yläkäsitteeksi [eläintarhat](http://www.yso.fi/onto/yso/p12663) samaan tapaan kuin wikidatassa: https://www.wikidata.org/wiki/Q2281788
