### ISSUE TITLE
luostarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8530]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luostarit](http://www.yso.fi/onto/ysa/Y97039) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "konventit" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjan mukaan konventti on kokous, Googlella lähinnä Jehovan todistajiin liittyviä viitteitä.

**Comment by mariaforsen** [comment]
Pitää varmaan ottaa muodossa "konventit (luostarit)" KÄYTÄ luostarit
Esim. https://researchportal.helsinki.fi/en/publications/suomen-keskiaikaiset-konventit-ja-luostarit ja Wikipedia: "Katoliset luostarit
    Helsingin birgittalaiskonventti
    Jumalanäidin karmeliittaluostari Espoossa
    Turun birgittalaisluostari
    keskiaikaiset luostarit
        Kökarin fransiskaanikonventti
        Naantalin birgittalaisluostari
        Rauman fransiskaanikonventti
        Turun dominikaanikonventti
        Viipurin dominikaanikonventti
        Viipurin fransiskaanikonventti"

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermi muodossa _konventit (luostarit)_.
