### ISSUE TITLE
hybridit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8531]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hybridit](http://www.yso.fi/onto/ysa/Y107029) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarvitsisiko tarkenteen tai mahdollisesti päätermiksi nykyinen KT-muoto lajiristeymät? 

#### Perustelut ehdotukselle   

Melindassa käytetty mm. näissä viitteissä:

Moottorilla varustettu polkupyörä : Bultaco Brinco RE ja R - laillinen ja laiton!.
Energiaremontti kiuaslämmöllä ja aurinkokeräimillä.
Hybridi- ja sähköautojen korjaamoprosessi 
Mielenkiintoinen omakotitalon hybridilämmitysjärjestelmä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja: 

hybridi

biol. ristey(ty)mä.
Rusakon ja metsäjäniksen hybridi.

Laajemmin
Hybridi hybridiauto.
Teos on kahden lajityypin välinen hybridi.

**Comment by mariaforsen** [comment]
Sv. hybrider (arter)?

**Comment by FinMeSHienPaimentaja** [comment]
> #### Ehdotettu muutos
> tarvitsisiko tarkenteen tai mahdollisesti päätermiksi nykyinen KT-muoto lajiristeymät?

Ok muuten, mutta "lajiristeymien" sijaan laittaisin laajemmin käyttökelpoisen "risteymät".

**Comment by mirmaid** [comment]
^ Ei kai se ole liiankin laajasti käytettävissä, Kielitoimiston sanakirja: Laajemmin: _Kahden kulttuurin risteymä_. 

Melindassa risteymät 20 kertaa (lajien ja lajikkeiden risteymistä). Enimmäkseen Googlellakin tätä. Mahdollinen myös tarkenne: _hybridit (biologia)_ (tai risteymät (biologia)).

**Comment by YSO-kokous** [comment]
Muutetaan käytettäväksi termiksi risteymät (biologia), ohjaustermiksi esim. hybridit (biologia).
