### ISSUE TITLE
huvimajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8533]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[huvimajat](http://www.yso.fi/onto/ysa/Y101720) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "paviljongit" ja "puistomajat" 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/#/paviljonki 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Taidehistoria:paviljonki

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermit muodossa puistomajat ja paviljongit (huvimajat). Paviljonki tarkoittaa myös näyttelyrakennusta ja siksi sulkutarkenne tarpeellinen.
