### ISSUE TITLE
puunhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8534]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puunhoito 

#### Ehdotettu termi ruotsiksi   

trädvård 

#### Ehdotettu termi englanniksi   

arboriculture 

#### Perustelut ehdotukselle   

https://sv.wikipedia.org/wiki/Tr%C3%A4dv%C3%A5rd
Trädvård eller trädvårdsarbete kallas det arbete som omfattar plantering, kontroll och underhåll av träd, för att de ska hålla sig friska och vara säkra för omgivningen. Det inkluderar även studier om hur träd växer och reaktioner på till exempel miljö och odlingsmetoder. Det läggs mest energi på träd i trädgårdar, parker eller i urbana områden, där träd planteras för behaglighet.

https://en.wikipedia.org/wiki/Arboriculture
Arboriculture (/ˈɑːrbərɪkʌltʃər/) is the cultivation, management, and study of individual trees, shrubs, vines, and other perennial woody plants. The science of arboriculture studies how these plants grow and respond to cultural practices and to their environment. The practice of arboriculture includes cultural techniques such as selection, planting, training, fertilization, pest and pathogen control, pruning, shaping, and removal. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Puista ja puiden seuralaisista =about trees and their companions : 23. Puunhoidon seminaari, Tampere 29.11.2019 

**Termiehdotus Fintossa:** [puunhoito](http://finto.fi/yse/fi/page/Y508534)

**Comment by ilona-x** [comment]
AFO: puunhoito http://www.yso.fi/onto/afo/p5844

**Comment by mirmaid** [comment]
Käytetty 70 kertaa Agriforest-terminä ja 20 kertaa vapaana avainsanana.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
