### ISSUE TITLE
lahjoitusmaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8535]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lahjoitusmaat](http://www.yso.fi/onto/ysa/Y102957) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään englanninkielinen KT-muoto "land grants" ja LCSH-siltaus vastaavaan asiasanaan Land grants [http://id.loc.gov/authorities/subjects/sh85074296] 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Lisätty
