### ISSUE TITLE
Software as service

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8536]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Software as service 

#### Vaihtoehtoiset termit ja ilmaisut   

Saas-malli 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/303511 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Software as service](http://finto.fi/yse/fi/page/Y508536)

**Comment by mariaforsen** [comment]
Sv. Software as service, SaaS-tjänster, SaaS-modellen

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Software_as_a_Service

**Comment by ilona-x** [comment]
**fi        verkkosovelluspalvelu; etäsovelluspalvelu**
en      software as a service; SaaS
määritelmä
palvelu, jossa tarjotaan verkkosovelluksia käytettäväksi internetin kautta
huomautus
Verkkosovelluspalveluja käytetään usein selaimella.
Jos yritys käyttää verkkosovelluspalveluja, sen ei tarvitse ostaa sovelluksia itselleen, vaan se voi hankkia palveluja verkkosovelluspalvelujen tarjoajilta tarpeen mukaan. Myös yksityiset ihmiset voivat käyttää verkkosovelluspalveluja. Tällaisia palveluja ovat esimerkiksi selaimen kautta käytettävät selainsähköposti ja sähköinen kalenteri.
Yrityksille tarjottavat verkkosovelluspalvelut ovat yleensä maksullisia, mutta yksityisille ihmisille löytyy myös ilmaisia verkkosovelluspalveluja.
Lähde: Tietotekniikan termitalkoot, 2012-01-10 https://termipankki.fi/tepa/fi/haku/%20software%20as%20a%20service

**Comment by LeKorsu** [comment]
Peukuttaisin mieluusti verkkosovelluspalvelua ja noita kahtai muuta ohjaustermiksi, mutta tuolla Tepassa näyttäisivät nuo ohjaustermeiksi ehdottamani olla nimenomaan suosituksia.

**Comment by osma** [comment]
Eikö sen pitäisi olla "Software as *a* service" myös suomeksi (as if) ja ruotsiksi...
Tai siis mikä ikinä onkaan ensisijainen termi, niin ei minusta ole syytä pudottaa a-artikkelia pois silloin kun käytetään tuota englanninkielistä termiä.

**Comment by MikkoAleksanteri** [comment]
pitäisikö samalla ottaa myös PaaS? https://en.wikipedia.org/wiki/Platform_as_a_service

**Comment by osma** [comment]
"verkkosovelluspalvelu" antaa viitisensataa osumaa Googlella, joukossa ihan oikeita tuotteita eikä pelkästään terminologiajuttuja. Toisaalta esim. [Wikipedia-artikkelissa](https://fi.wikipedia.org/wiki/Software_as_a_Service) ei edes mainita verkkosovelluspalvelu-termiä, puhutaan vain SaaSista.

Vähän olen kiikun kaakun tämän suhteen. Sinänsä kannatan suomenkielisen terminologian kehittämistä ja käyttöä, joten ehkä varovainen peukku verkkosovelluspalvelulle.

**Comment by miguelvaara** [comment]
SaaS-palveuihin liittyvää markkinointi- ja viestintätyötä tekevältä ammattilaiselta pyydetty mielipide: "verkkosovelluspalvelu" ei ole lainkaan sovelias termi

**Comment by joelit** [comment]
Tähän samaan perheeseen kuuluu:
- Content as a service
- Data as a service (relevantti)
- Desktop as a service
- Function as a service
- Infrastructure as a service (relevantti)
- Integration platform as a service
- Mobile backend as a service
- Network as a service
- Platform as a service (relevantti)
- Security as a service
- Software as a service (tyypillisin)

"Saas-malli" ja "Software as a service" on niitä mihin itse olen suomenkielisessä keskustelussa törmännyt. Näiden kaikkien yhteenkokoava yläkäsite on palvelukeskeinen arkkitehtuuri, https://en.wikipedia.org/wiki/Service-oriented_architecture

**Comment by MikkoAleksanteri** [comment]
> 
> 
> Tähän samaan perheeseen kuuluu:
> 
>     * Content as a service
> 
>     * Data as a service (relevantti)
> 
>     * Desktop as a service
> 
>     * Function as a service
> 
>     * Infrastructure as a service (relevantti)
> 
>     * Integration platform as a service
> 
>     * Mobile backend as a service
> 
>     * Network as a service
> 
>     * Platform as a service (relevantti)
> 
>     * Security as a service
> 
>     * Software as a service (tyypillisin)
> 
> 
> "Saas-malli" ja "Software as a service" on niitä mihin itse olen suomenkielisessä keskustelussa törmännyt. Näiden kaikkien yhteenkokoava yläkäsite on palvelukeskeinen arkkitehtuuri, https://en.wikipedia.org/wiki/Service-oriented_architecture

Vielä kattavampi lista "aaS:eja" täällä: https://en.wikipedia.org/wiki/As_a_service
Yleisimmät lienevät SaaS, PaaS ja MaaS?

**Comment by mirmaid** [comment]
Kommentti: Ilonan laittamat suomenkieliset versiot ok (ja miksei olisi, sentään Tieteen termipankista). Tottakai a-artikkeli. Markkinoijien puheet kannattaa heti alkuun unohtaa silloin, kun puhutaan oikeasti asiasta. Eli: Software as a service ohjaustermiksi, myös SaaS(-malli). Loppukaneettina: asiat muuttuvat luonnollisiksi ja käytettäviksi sillä, että niitä käytetään.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa SaaS-palvelut. Ohjaustermiksi software as a service ja muut soveltuvat. Asiasta äänestettiin ja lievä enemmistö kannatti Saas-palvelut-muotoa.

**Comment by mariaforsen** [comment]
Sv. SaaS-tjänster ET SaaS-modellen, software as a service, program som nättjänst
https://it-ord.idg.se/ord/software-as-a-service/
