### ISSUE TITLE
maa-alkalimetallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8537]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

maa-alkalimetallit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/304331 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [maa-alkalimetallit](http://finto.fi/yse/fi/page/Y508537)

**Comment by mirmaid** [comment]
AFOssa, GEOssa ja FinMeSHissä. 
LCSH: http://id.loc.gov/authorities/subjects/sh85003595

**Comment by mariaforsen** [comment]
Sv. alkaliska jordartsmetaller /ne ET alkaliska jordmetaller, jordalkalimetaller
