### ISSUE TITLE
puretus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8539]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

puretus 

#### Ehdotettu termi englanniksi   

mordant 

#### Tarkoitusta täsmentävä selite   

Puretus lisää kuidun väripintaa, materiaali ”tahmeutuu” ja värihiukkaset kiinnittyvät paremmin kuituun, jolloin
värjäystulos on voimakkaampi ja kestävämpi puretetussa materiaalissa.
Tavallisimmat puretusaineet ovat: aluna, viinikivi, kupari- ja rautavihtrilli.

Katso myös:
https://fi.wikipedia.org/wiki/V%C3%A4rj%C3%A4ys 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Perustelut ehdotukselle   

Termin avulla voisi monipuolistaa värjäystä käsittelevän aineiston kuvailua 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Rudkin: Natural dyes 978-1-78994-027-5 

**Ehdottajan organisaatio:** Metropolia AMK **Termiehdotus Fintossa:** [puretus](http://finto.fi/yse/fi/page/Y508539)

**Comment by ilona-x** [comment]
TAOssa: puretus (värjäys) http://www.yso.fi/onto/tao/p2436

**Comment by mirmaid** [comment]
Melindassa kerran muodossa _purettaminen_.

_Mordant_ olisi oikeastaan _purete_ tai _puretusaine_, mutta _puretus_ kuulostaa terminä käyttökelpoisemmalta.

**Comment by mariaforsen** [comment]
Sv. betning (färgning)?

**Comment by YSO-kokous** [comment]
Tutkitaan vielä suhde peittaukseen. Mahdollista päällekkäisyyttä tämän kanssa. Määritelmä selkeyttäisi.

**Comment by mirmaid** [comment]
Peittaus käytetty yleensä tästä: https://fi.wikipedia.org/wiki/Peittaus_(siemenvilja). Wikipediassa linkitykset ovatkin aika mielenkiintoisia - ruotsin betning kattaa samassa artikkelissa useita pintakäsittelyn kohteita, siihen linkittyvä saksankielinen keskittyy metalliteollisuuteen, ja se puolestaan on linkitetty eng. https://en.wikipedia.org/wiki/Pickling_(metal), kun taas ruotsinkielinen on linkitetty https://en.wikipedia.org/wiki/Mordant ja suomenkielinen https://en.wikipedia.org/wiki/Seed_treatment. 

Suomeksi on myös https://fi.wikipedia.org/wiki/Peittaus (käytetty joitakin kertoja Melindassa), joka on linkitetty eng. https://en.wikipedia.org/wiki/Pickling_(metal), mutta saksaksi https://de.wikipedia.org/wiki/Beizen_(Pflanzenschutz) :facepalm:

Ehdottaisin peittaukselle sulkutarkenteita, esim. (vilja) ja (metallit) tms.

**Comment by mirmaid** [comment]
_Puretus_-termiä ei suomeksi käytetä laajemmin, en tiedä miksi TAOssa on päädytty tarkenteeseen.

**Comment by YSO-kokous** [comment]
Hyväksytään. Muilla kielillä voidaan tarvita tarkenteita.  
Jaetaan peittaus -> peittaus (vilja) ja peittaus (metallit)
