### ISSUE TITLE
Devicin tauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8540]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Devicin tauti 

#### Vaihtoehtoiset termit ja ilmaisut   

NMO 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305017 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Devicin tauti](http://finto.fi/yse/fi/page/Y508540)

**Comment by ilona-x** [comment]
FinMeSH:
Devicin oireyhtymä http://www.yso.fi/onto/mesh/D009471
KT Devicin tauti

**Comment by mariaforsen** [comment]
Sv. neuromyelitis optica /mesh ET Devics sjukdom

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mirmaid** [comment]
Ilmeisesti nykyään käytetään nimeä _neuromyelitis optica_. 

https://en.wikipedia.org/wiki/Neuromyelitis_optica

**Comment by FinMeSHienPaimentaja** [comment]
> Ilmeisesti nykyään käytetään nimeä _neuromyelitis optica_.
> 
> https://en.wikipedia.org/wiki/Neuromyelitis_optica

Kyllä, em. on nykyään käytetty:

https://www.terveysportti.fi/sovellukset/sanakirjat/#/q//lte15354

https://www.terveysportti.fi/apps/icd/?query=neuromyelitis%20optica

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa neuromyelitis optica, ohjaustermiksi Devicin tauti.
