### ISSUE TITLE
toiminimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8541]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toiminimet](http://www.yso.fi/onto/ysa/Y104626) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "aputoiminimet" 

#### Perustelut ehdotukselle   

Osa toiminimistä on aputoiminimiä; ks. esim. https://www.prh.fi/fi/kaupparekisteri/yritystennimet/aputoiminimi.html 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. hjälpfirmanamn, bifirmanamn

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä. LIITOssa aputoiminimi on erillisenä käsitteenä ja tämä muodostaisi ongelman KOKO-ontologian kannalta.
