### ISSUE TITLE
jättisoluarteriitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8542]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

jättisoluarteriitti 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305377 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [jättisoluarteriitti](http://finto.fi/yse/fi/page/Y508542)

**Comment by ilona-x** [comment]
FinMeSH: ohimovaltimotulehdus http://www.yso.fi/onto/mesh/D013700

**Comment by mirmaid** [comment]
Melindassa 3 kertaa ohimovaltimotulehdus, kerran jättisoluarteriitti. Googlella jättisoluarteriitti on yleisin muoto, ja myös temporaaliarteriitti antaa enemmän viitteitä kuin ohimovaltimotulehdus.

Lääketieteen termit: 
jättisoluarteriitti | _valtimotulehdus jolle ovat ominaisia tulehduspesäkkeiden monitumaiset jättisolut_; ks. myös ohimovaltimotulehdus, Takayasun tauti 

ohimovaltimotulehdus: temporaaliarteriitti, Hortonin arteriitti | _etenkin iäkkäiden naisten kaulavaltimoiden haaroissa (ja muissakin valtimoissa) esiintyvä jättisoluarteriitti, josta aiheutuvia oireita ovat mm. lihassäryt, päänsärky, pureskeluvaikeudet, jopa sokeuteen asti kehittyvät näköhäiriöt, kuumeilu, laihtuminen ja huono yleisvointi_

Vaikuttaa siltä, että jättisoluarteriitti on vähän laajempi, mutta ko. julkaisussa kyseessä ohimovaltimotulehdus, joka on tavallisin jättisoluarteriitti: https://harvinaiset.fi/diagnoosi/jattisoluarteriitti/

**Comment by mariaforsen** [comment]
Sv. jättecellsarterit /mesh ET Hortons arterit, storcellsarterit, temporalarterit

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa jättisoluarteriitti, ohjaustermiksi ohimovaltimotulehdus.
