### ISSUE TITLE
sappiteiden atresia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8543]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sappiteiden atresia 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301452 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sappiteiden atresia](http://finto.fi/yse/fi/page/Y508543)

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/306371

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D001656

**Comment by mariaforsen** [comment]
Sv. gallgångsatresi ET biliär atresi
