### ISSUE TITLE
sokeriaineenvaihdunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8545]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sokeriaineenvaihdunta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/299825 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sokeriaineenvaihdunta](http://finto.fi/yse/fi/page/Y508545)

**Comment by mariaforsen** [comment]
Sv. sockeromsättning

**Comment by mirmaid** [comment]
2 kertaa Melindassa, 3 kertaa _glukoosiaineenvaihdunta_. FinMeSHissä on _glukoosiaineenvaihdunnan häiriöt_ (4 viitettä).

YSOssa on _rasva-aineenvaihdunta_ (on myös FinMeSHissä).

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen puolella lähes poikkeuksetta on kysymys "glukoosiaineenvaihdunnasta", ei muiden sokereiden aineenvaihdunnasta - suomenkieliselle termille "glukoosiaineenvaihdunta" on ollut ja on suuri tarve. 

Myös tässä https://helda.helsinki.fi/handle/10138/299825 on kyse "glukoosiaineenvaihdunnasta".

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa glukoosiaineenvaihdunta, ohjaustermiksi sokeriaineenvaihdunta.

**Comment by mariaforsen** [comment]
Sv. glukosomsättning ET glukosämnesomsättning, sockeromsättning
