### ISSUE TITLE
JAK-STAT-signalointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8546]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

JAK-STAT-signalointi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305397 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [JAK-STAT-signalointi](http://finto.fi/yse/fi/page/Y508546)

**Comment by mariaforsen** [comment]
Sv. JAK-STAT-signalering

**Comment by mirmaid** [comment]
LCSH: JACK-STAT pathway http://id.loc.gov/authorities/subjects/sh2015001689

Melindassa kerran jak-stat-signalointireitti, jak-stat-reitti

https://en.wikipedia.org/wiki/JAK-STAT_signaling_pathway

**Comment by YSO-kokous** [comment]
Ei oteta toistaiseksi YSOon.

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/329512

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
