### ISSUE TITLE
lääkeresistenssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8547]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lääkeresistenssi](http://www.yso.fi/onto/ysa/Y182290) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmän laajennus 

#### Perustelut ehdotukselle   

Ei liity välttämättä mikrobeihin, vaan myös esim. syöpä voi kehittyä resistentiksi lääkehoidolle. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Poistetaan huomautus lääkeresistenssi-käsitteeltä.
