### ISSUE TITLE
musikaalielokuvax

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8548]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

musikaalielokuvax 

#### Ehdotettu termi ruotsiksi   

musikalfilmex 

#### Ehdotettu termi englanniksi   

musical films 

#### Vaihtoehtoiset termit ja ilmaisut   

elokuvamusikaali? 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Tarkoitusta täsmentävä selite   

Saisiko tämän termin myös SLM-sanastoon? Se on nyt YSOssa, mutta puuttuu SLMstä. (Anteeksi väärinkirjoitukset tuolla alussa, en saanut muuten lähetettyä tätä, koska termi on jo YSOssa...) 

#### Perustelut ehdotukselle   

Sanastossa on kyllä 'musiikkielokuvat', mutta joissakin tapauksissa 'musikaalielokuvat' on täsmällisempi määritelmä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sound of music, Rocky horror picture show, ym. 

**Ehdottajan organisaatio:** Tampereen kaupunginkirjasto **Termiehdotus Fintossa:** [musikaalielokuvax](http://finto.fi/yse/fi/page/Y508548)

**Comment by asormune** [comment]
Tehtiinköhän YSOssa jo olevan termin SLM ehdotus "muutosehdotuksena" YSO-termiin ja lisätään kommentti, että tarvitaan myös SLM.

**Comment by AuHo22** [comment]
KP:n av:lta kysyttyä ja vastaus: "Tämä on ihan hyvä kysymys, onko musikaalit liian teatteriin liittyvä ja tarvitaan erikseen musikaalielokuvat? Toisaalta tässä on mielestäni riski, että se sekoitetaan musiikkielokuviin ja siksi suosittelisin käyttämään musikaalit termiä myös sen tyyppisistä elokuvista. Sopii ihan hyvin myös noihin esimerkkitapauksiin." Esim. La la land Melinda-id: 011440025

**Comment by jtuohini** [comment]
LCGFT-siltaus: [**Musical films**](http://id.loc.gov/authorities/genreForms/gf2011026414)

**Comment by mirmaid** [comment]
Hyväksytty/SLM. Jaakko laatii määritelmät musikaalielokuvat ja musiikkielokuvat -termeille. Muusa kommentoi määritelmiä. Lisäksi käyttöhuomautus musikaalit-termille.

**Comment by jtuohini** [comment]
KT "elokuvamusikaalit", LT "musiikkielokuvat", LT/RT "musikaalit". Elokuva, jossa hahmojen laulamat laulut ja musiikki kuljettavat tarinaa eteenpäin ja joka voi perustua teatterimusikaaliin tai josta on tehty teatteriversioita. Videoidusta teatterimusikaalista käytetään SLM-termejä "musikaalit" ja "videoidut esitykset".

**Comment by MUUSA-kokous** [comment]
Kannatetaan määritelmäehdotusta.

**Comment by mirmaid** [comment]
Musiikkielokuvat-termin määritelmä puuttuu vielä?

**Comment by jtuohini** [comment]
Määritelmäehdotus löytyy täältä: https://github.com/Finto-ehdotus/YSE/issues/8647 ("Elokuva, jonka keskeisenä aiheena on musiikkielämä tai muusikon henkilöhistoria ja jossa musiikkia käytetään diegeettisesti (äänilähde näkyvillä elokuvassa).")

**Comment by jtuohini** [comment]
Pohdittavia esimerkkejä määritelmän päivittämisen kannalta: selkeinä _Amadeus_ (1984) ja _Tous les matins du monde_ (1991), entä _Pink Floyd – The Wall_ (1982)?
