### ISSUE TITLE
nivelpsoriaasi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8549]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nivelpsoriaasi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301319 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [nivelpsoriaasi](http://finto.fi/yse/fi/page/Y508549)

**Comment by ilona-x** [comment]
FinMeSH:
**psoriaasiin liittyvä niveltulehdus** http://www.yso.fi/onto/mesh/D015535
KT nivelpsoriaasi

**Comment by mariaforsen** [comment]
Sv. psoriasisartrit /mesh, ne ET ledpsoriasis

**Comment by mirmaid** [comment]
14 viitettä Melindassa, FinMeSHin muoto 5 kertaa.

**Comment by FinMeSHienPaimentaja** [comment]
"Nivelpsoriaasi" on mielestäni myös FinMeSH:eissä paras ensisijainen termi (-> seuraavaan sanastopäivitykseen), "nivelpsoriaasia" näyttää käytettävän yleisesti.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa nivelpsoriaasi.
