### ISSUE TITLE
glukuronidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8550]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

glukuronidit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Human efflux transporters in drug disposition 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [glukuronidit](http://finto.fi/yse/fi/page/Y508550)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D020719

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. glukuronider /mesh
