### ISSUE TITLE
mikroreaktorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8551]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mikroreaktorit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/306828 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mikroreaktorit](http://finto.fi/yse/fi/page/Y508551)

**Comment by ilona-x** [comment]
LCSH: Microreactors http://id.loc.gov/authorities/subjects/sh00004949

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

Tarvitsisi ehkä tarkenteen (kemia) tms. Termiä käytetään myös pienistä ydinvoimaloista puhuttaessa, https://fi.wikipedia.org/wiki/Pieni_modulaarinen_ydinreaktori.

**Comment by mariaforsen** [comment]
Sv. mikroreaktorer (kemi)

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa _mikroreaktorit (kemia)_.
