### ISSUE TITLE
eksomisekvensointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8552]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

eksomisekvensointi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/278894 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [eksomisekvensointi](http://finto.fi/yse/fi/page/Y508552)

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/301111

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/305550

**Comment by mariaforsen** [comment]
Sv. exomsekvensering

**Comment by mirmaid** [comment]
10 viitettä Melindassa. Toistuu tällä hetkellä taajaan väitöskirjoissa.

**Comment by FinMeSHienPaimentaja** [comment]
"...sekvensointi" vai "...sekvenointi"? Ilmeisesti molempia käytetään, lieneekö kumpikaan "oikeakielisempi"...?

**Comment by mirmaid** [comment]
-sekvensointi on ainakin tavallisempi muoto.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
