### ISSUE TITLE
keuhkoödeema

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8553]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

keuhkoödeema 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305243 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [keuhkoödeema](http://finto.fi/yse/fi/page/Y508553)

**Comment by ilona-x** [comment]
FinMeSH:
**keuhkopöhö** http://www.yso.fi/onto/mesh/D011654
KT keuhkoödeema

**Comment by mariaforsen** [comment]
Sv. lungödem

**Comment by mirmaid** [comment]
Melindassa 9 kertaa _keuhkoödeema_, 12 kertaa _keuhkopöhö_.

Lääketieteen termit: keuhkopöhö

Googlella keuhkoödeema on käytetympi.

**Comment by FinMeSHienPaimentaja** [comment]
Miten olisi "keuhkoturvotus"?

https://www.terveysportti.fi/apps/icd/?query=keuhkop%C3%B6h%C3%B6

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa keuhkoödeema, ohjaustermeiksi keuhkopöhö ja keuhkoturvotus.
