### ISSUE TITLE
mini-invasiiviset leikkaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8554]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mini-invasiiviset leikkaukset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305243 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mini-invasiiviset leikkaukset](http://finto.fi/yse/fi/page/Y508554)

**Comment by ilona-x** [comment]
FinMeSH: mini-invasiiviset leikkaukset http://www.yso.fi/onto/mesh/D019060

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Minimally_invasive_procedure

**Comment by mariaforsen** [comment]
Sv. minimalinvasiv kirurgi  /mesh ET minimalinvasiva ingrepp, minimalinvasiva operationer

**Comment by FinMeSHienPaimentaja** [comment]
Termi sinänsä on tarpeellinen - kunpa siihen vielä löytyisi "suomenkielisempi" lue: vähemmän vierasperäinen sana.
