### ISSUE TITLE
lahjasoluhoidot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8555]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lahjasoluhoidot 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301864 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lahjasoluhoidot](http://finto.fi/yse/fi/page/Y508555)

**Comment by mirmaid** [comment]
https://helminauha.info/lahjasoluhoidot/
https://www.simpukka.info/lahjasoluhoitojen-linjaukset-julkisella-sektorilla/

**Comment by mariaforsen** [comment]
Vain vähän googlessa, onko muita muotoja? 
Sv. ? "behandling med donerade celler"

**Comment by ilona-x** [comment]
FinMeSH: hedelmöitys luovuttajan sukusoluilla http://www.yso.fi/onto/mesh/D000072234

**Comment by mirmaid** [comment]
Onkohan sitten sv. [fertilitetsbehandlingar med donerade könsceller](https://www.sttinfo.fi/tiedote/hus-inleder-fertilitetsbehandlingar-med-donerade-konsceller?publisherId=23980819&releaseId=69867717)?

**Comment by mirmaid** [comment]
Ei ole kovin paljon käytetty (olisin odottanut, että enemmän, koska asia on kuitenkin ollut akuutti jo hyvin pitkään), mutta vaikea ilmaista muuten kuin tarkalla termillä (toki mahdollista ottaa myös "lahjoitetut/luovutetut sukusolut", mutta onko se yhtään toimivampi).

**Comment by mirmaid** [comment]
Varsin ajankohtainen aihe myös ihan tällä hetkellä: https://areena.yle.fi/1-50703738
https://yle.fi/uutiset/3-11031523

**Comment by FinMeSHienPaimentaja** [comment]
Ainakin veren kantasolujen luovutuksia tehdään -> luovutetuilla soluilla tehdyt hoidot on myös käsitettävissä lahjasoluhoidoiksi. Toistaiseksi "lahjasoluhoidoista" puhuminen / sanan käyttö ei ole kovinkaan yleistä.

**Comment by mirmaid** [comment]
Itselleni ihan tuttu nimenomaan tässä muodossa jo niiltä ajoilta, kun nyt teini-ikäiset lapset olivat pieniä, ja perheaiheisia nettifoorumeita tuli seurattua - siksi olinkin vähän ihmeissäni ettei nyt löydy isoa massaa viitteitä Googlella.

Tays ja HUS siis aloittivat lahjasoluhoidot viime vuonna uudelleen tauon jälkeen, yksityisellä puolella niitä on tehty koko ajan. Ko. väitöstutkimuksen kohteena olivat nimenomaan lahjasoluhoidoilla lapsen saaneet vanhemmat. Voin laittaa 653-kenttään, mutta ei tämä tutkimus kyllä viimeiseksi jää tästä aiheesta :slightly_smiling_face:.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa lahjasoluhoidot, ohjaustermiksi hedelmöitys luovuttajan sukusoluilla.

**Comment by jarmosaarikko** [comment]
Kunhan ei mene sekaisin esim. kantasoluluovutusten kanssa 
https://www.veripalvelu.fi/kantasolurekisteri/jasenpalvelut/usein-kysyttya - ei varmaan, sillä  kantasoluhoito KÄ kantasolujen siirto

**Comment by mariaforsen** [comment]
Sv. assisterad befruktning med donerade könsceller ET befruktning med hjälp av donation, befruktning med donation, behandling med donerade celler, fertilitetsbehandlingar med donerade könsceller
