### ISSUE TITLE
elämäkertaelokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8556]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elämäkertaelokuvat](http://www.yso.fi/onto/ysa/Y111953) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "henkilöhistorialliset elokuvat" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Myös elämäkerralliset elokuvat.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotettu ohjaustermi ja myös mirmaidin ehdottama ohjaustermi.
