### ISSUE TITLE
solulimakalvosto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8557]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

solulimakalvosto 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/303927 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Solulimakalvosto 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [solulimakalvosto](http://finto.fi/yse/fi/page/Y508557)

**Comment by ilona-x** [comment]
FinMeSH: solulimakalvosto http://www.yso.fi/onto/mesh/D004721

**Comment by mirmaid** [comment]
4 kertaa Melindassa vapaana avainsanana.
