### ISSUE TITLE
Von Willebrandin tauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8558]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Von Willebrandin tauti 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305277 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Von Willebrandin tauti](http://finto.fi/yse/fi/page/Y508558)

**Comment by ilona-x** [comment]
FinMeSH:
von Willebrandin tauti http://www.yso.fi/onto/mesh/D014842

**Comment by mirmaid** [comment]
N. 10 viitettä Melindassa.

https://fi.wikipedia.org/wiki/Von_Willebrandin_tauti

**Comment by mariaforsen** [comment]
Sv. von Willebrands sjukdom /ne, wp ET von Willebrands sjukdomar /mesh, Willebrands sjukdom
