### ISSUE TITLE
hemofilia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8559]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hemofilia](http://www.yso.fi/onto/ysa/Y95326) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT verenvuototauti 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
FinMeSH: 
**hyytymisproteiinihäiriöt** http://www.yso.fi/onto/mesh/D020147
KT hemofilia

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
