### ISSUE TITLE
hermopinteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8560]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hermopinteet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/306228 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hermopinteet](http://finto.fi/yse/fi/page/Y508560)

**Comment by ilona-x** [comment]
FinMeSH:
**hermopinneoireyhtymät**  http://www.yso.fi/onto/mesh/D009408
KT hermopinteet

**Comment by mariaforsen** [comment]
Sv. nervinklämningar, nervkompressionssyndrom /mesh

**Comment by mirmaid** [comment]
Melindassa 17 kertaa _hermopinteet_, 2 kertaa _hermopinneoireyhtymät_.

**Comment by mirmaid** [comment]
Lääketieteen termit: pinne: _pehmytkudoksen, erityisesti hermon tai verisuonen, puristustila; ks. myös kyynärkanavaoireyhtymä, rannekanavaoireyhtymä, kyynärpääpinne, thoracic outlet ‑oireyhtymä, ahdas olka_

**Comment by FinMeSHienPaimentaja** [comment]
Lääkärin käsikirjassa puhutaan "hermojen pinne- ja kompressiotiloista".
https://www.terveysportti.fi/apps/ltk/article/ykt00923/search/hermopinne

"Pinne" ja "kompressio" vaikuttavat kuitenkin synonyymeiltä tässä.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa hermopinteet.

**Comment by mariaforsen** [comment]
Sv. nervinklämningar ET nervkompressionssyndrom, inklämda nerver
