### ISSUE TITLE
suunielusyöpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8561]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suunielusyöpä 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305612 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suunielusyöpä](http://finto.fi/yse/fi/page/Y508561)

**Comment by ilona-x** [comment]
FinMeSH:
**suunielun kasvaimet** http://www.yso.fi/onto/mesh/D009959
KT suunielun syöpä
KT suunielun tuumorit

**Comment by mariaforsen** [comment]
Sv. orofarynxtumörer ET orofarynxcancer

**Comment by mirmaid** [comment]
Melindassa 3 kertaa _suunielun kasvaimet_, 8 kertaa _nielusyöpä_ (joka voi olla suunielun, alanielun tai nenänielun syöpä, FinMeSH _nielun kasvaimet_). FinMeSHin ratkaisu on sikäli ehkä vähän erikoinen, että kasvaimet voivat olla myös hyvälaatuisia...

**Comment by FinMeSHienPaimentaja** [comment]
On totta, että monesti suomennuksissa on hankalaa ilmaista hyvä- ja pahalaatuisus, tai yleensäkin on monesti haasteellista tietää, että kummasta on kysymys (ja voi olla kummastakin). ICD-10 (Terveysportin kautta) 

https://www.terveysportti.fi/apps/icd/?query=suunielu

antaa kuitenkin sen käsityksen, että olisivat pahalaatuisia (ks. hierarkia), ja  "syöpää" on käytetty (mikä sekään ei mielestäni ole mikään tyhjentävä ratkaisu tähän asiaan), joskin hyvälaatuiset eivät ole poissuljettu. 

FinMeSH-termit ovat MeSH-termien suomennuksia ja sen takia paljon riippuvaisia MeSH-merkityksistä. 

MeSH sanoo termistä "Oropharyngeal Neoplasms" 
_Scope Note Tumors or cancer of the OROPHARYNX._

 https://meshb.nlm.nih.gov/record/ui?name=Oropharyngeal%20Neoplasms

Termin "Neoplasms" MeSH määrittää:

_Scope Note
New abnormal growth of tissue. Malignant neoplasms show a greater degree of anaplasia and have the properties of invasion and metastasis, compared to benign neoplasms.
Entry Version
NEOPL
Entry Term(s)
Benign Neoplasms
Cancer
Malignancy
Malignant Neoplasms
Neoplasia
Neoplasm
Neoplasms, Benign
Tumors_

https://meshb.nlm.nih.gov/record/ui?ui=D009369

**Comment by ilona-x** [comment]
kasvain vs. syöpä: YSOssa myös aivokasvaimet ja FinMeSHissä aivosyöpä KÄYTÄ aivokasvaimet
Jos halutaan korostaa pahanlaatuisuutta, voi kuvailuun lisätä syöpätaudit

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa _suunielun kasvaimet_, ohjausterminä suunielun syöpä / suunielusyöpä.
