### ISSUE TITLE
itkut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8562]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itkut](http://www.yso.fi/onto/ysa/Y95589) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon itkuvirret. 

#### Perustelut ehdotukselle   

Finto sai asiantuntijapalautetta: nähtiin, että termi itkut voi mennä sekaisin itku-käsitteen kanssa. Olisi parempi, että käytettävänä terminä olisi itkuvirret, joka on terminä selkeämpi ja käytetään tutkimuksessa yhtä paljon kuin itkut-termiäkin. 

#### Ehdottajan organisaatio   

Kansallikirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by YSO-kokous** [comment]
Muutetaan käytettävä termi muotoon itkuvirret.
