### ISSUE TITLE
runonlaulu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8563]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[runonlaulu](http://www.yso.fi/onto/ysa/Y106226) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytettävästä termistä herännyt keskustelua. 

#### Perustelut ehdotukselle   

Saimme asiantuntijapalautetta:
runolaulu/runonlaulu. Tästä väännetään paljon myös tutkimuksen/muusikoiden piirissä. Folkloristiikassa ollaan enemmän runolaulun kannalla, mutta toisenlaista näkemystä on vahvasti tullut esiin mm. muusikoiden puolelta. Tähän liittyvää mm. Kati Kallion blogikirjoituksessa: http://neba.finlit.fi/blogi/miten-kutsua-vanhaa-runoa/ 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by MUUSA-kokous** [comment]
Ei kannateta muutosta.

**Comment by krinay** [comment]
(Nyky)kansanmusiikin tutkijoiden ja esittäjien parista lähtenyt termimuoto _runolaulu_ on viime aikoina aika lailla vakiintunut myös folkloristisessa tutkimuksessa, jossa _runo**n**laulu_-termillä on tietenkin pitkät perinteet. Termivalinnasta keskustellaan paljon, mutta hyvin suuri osa aihealueen tutkijoista käyttää nykyisin termiä _runolaulu_. Jos termiä ei muuteta nyt, muutosehdotuksia tulee varmasti jatkossa epätasaisen tasaisin välein.

**Comment by YSO-kokous** [comment]
Ei muutoksia tähän käsitteeseen muuta kuin lisätään RT runonlaulajat. 
Lisätään myös seuraava ohjaustermi:
runolaulajat KÄYTÄ runonlaulajat
