### ISSUE TITLE
GIST-kasvaimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8564]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

GIST-kasvaimet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301450 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [GIST-kasvaimet](http://finto.fi/yse/fi/page/Y508564)

**Comment by mirmaid** [comment]
FinMeSH: GIST http://www.yso.fi/onto/mesh/D046152

**Comment by mirmaid** [comment]
https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=orp01478
https://fi.wikipedia.org/wiki/Gastrointestinaalinen_stroomakasvain

**Comment by mariaforsen** [comment]
Sv. gastrointestinala stromatumörer  ET gastrointestinala stromacellstumörer, GIST, GIST-tumörer

**Comment by mirmaid** [comment]
Melindassa 7 kertaa _GIST_, kerran _gastrointestinaaliset syöpätaudit_ ja kerran _gastrointestinaaliset stromaaliset tuumorit_.

**Comment by FinMeSHienPaimentaja** [comment]
GIST on lyhenne: Gastrointestinal Stromal Tumors. Jos olisi "GIST-kasvaimet", se olisi siis "Gastrointestinal Stromal Tumors -kasvaimet" eli kahteen kertaan olisi tumors/kasvaimet -merkitys, mikä olisi mielestäni vähän hassua.

**Comment by mirmaid** [comment]
^ Totta. Muotoa kuitenkin käytetään väitöskirjan tiivistelmässä - ehkä siksi, että se kertoo mistä on kyse paremmin kuin pelkkä GIST, mutta on kuitenkin lyhyempi kuin gastrointestinaaliset stroomakasvaimet tms. (Googlella saman verran viitteitä.)

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa _gastrointestinaaliset stroomakasvaimet_. Ohjaustermiksi _GIST-kasvaimet_ ja muut täällä esitetyt termimuodot soveltuvin osin.
