### ISSUE TITLE
endogeenisen kasvun teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8565]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

endogeenisen kasvun teoria 

#### Ehdotettu termi englanniksi   

endogenous growth theory 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Endogeenisen_kasvun_teoria
Endogeenisen kasvun teoria kehitettiin makrotaloustieteessä 1980-luvulla vastauksena eksogeenisen kasvun mallien saamaan kritiikkiin. Eksogeenisen kasvun malleista poiketen endogeenisen kasvun teoria pyrkii kuvaamaan kasvuprosessin siten, että keskeiset kasvuun vaikuttavat taloudelliset tekijät määräytyvät mallin sisällä eikä niitä oteta annettuna mallin ulkopuolelta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

On classical foundations of endogenous growth : Allyn Young and the early development theory 

**Termiehdotus Fintossa:** [endogeenisen kasvun teoria](http://finto.fi/yse/fi/page/Y508565)

**Comment by mariaforsen** [comment]
Sv. endogen tillväxtteori

**Comment by mirmaid** [comment]
Kerran Melindassa, _endogeeninen kasvu_ 4 kertaa, _endogeeninen kasvuteoria_ 4 kertaa, _endogeeninen kasvumalli_ 3 kertaa. Tavallisesti tähän ilmeisesti viitataan teoriana.

LCSH: Endogenous growth (Economics) http://id.loc.gov/authorities/subjects/sh98003329

**Comment by LeKorsu** [comment]
Peukku endogeeniselle kasvuteorialle.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon muodossa _endogeeninen kasvuteoria_.
