### ISSUE TITLE
kaasuhitsaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8566]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaasuhitsaus 

#### Ehdotettu termi ruotsiksi   

gassvetsning 

#### Ehdotettu termi englanniksi   

gas welding, oxyacetylene welding 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hitsaus](http://www.yso.fi/onto/yso/p16009) 

#### Assosiatiiviset (RT)   

[polttoleikkaus](http://www.yso.fi/onto/yso/p12665) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : Gassvetsning 
SAO : https://id.kb.se/term/sao/Gassvetsning 
TEPA : https://termipankki.fi/tepa/fi/haku/kaasuhitsaus 
LCSH : https://id.loc.gov/authorities/subjects/sh85096323.html 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Hitsaussanasto = Welding terminology ; Tulityöt. 3, Kaasuhitsaus- ja polttoleikkauslaitteet ja niiden turvallinen käyttö 

#### Perustelut ehdotukselle   

On aineistoa Melindassa. Tarkennetaan myös millainen suhde on termiin polttoleikkaus (olisiko jopa ohjaustermi), joka on nyt englanniksi oxyacetylene cutting  + ohjaustermejä jotka viittaavaat kaasuhitsaukseen. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[34 Metalliteollisuus. Metallurgia. Konepajateollisuus. Hienomekaaninen teollisuus](http://www.yso.fi/onto/yso/p26576) 

**Termiehdotus Fintossa:** [kaasuhitsaus](http://finto.fi/yse/fi/page/Y508566)

**Comment by mirmaid** [comment]
16 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksyttäneen YSOon, mutta tutkitaan vielä suhde polttoleikkaukseen ja näiden keskinäiset ohjaustermit ja linkitys (LCSH, Wikidata).

**Comment by mirmaid** [comment]
Tehdään samoilla laitteilla, mutta nimensä mukaisesti hitsauksessa liitetään ja leikkauksessa irrotetaan. Jos nämä haluttaisiin käsitellä yhdellä termillä, muodon pitäisi olla kuten LCSH:ssa. 
https://fi.wikipedia.org/wiki/Hitsaus#Kaasuhitsaus
https://fi.wikipedia.org/wiki/Polttoleikkaus
https://en.wikipedia.org/wiki/Oxy-fuel_welding_and_cutting#Welding_torch
