### ISSUE TITLE
Haagin vuoden 1954 yleissopimus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8567]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Haagin vuoden 1954 yleissopimus](http://www.yso.fi/onto/ysa/Y118626) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT Yleissopimus kulttuuriomaisuuden suojelemiseksi aseellisen selkkauksen sattuessa 

#### Perustelut ehdotukselle   

Käytetään, esim https://fi.wikipedia.org/wiki/Yleissopimus_kulttuuriomaisuuden_suojelemiseksi_aseellisen_selkkauksen_sattuessa

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
