### ISSUE TITLE
amorilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8568]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

amorilaiset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Between nomadism and sedentism: Amorites from the perspective of contextual archaeology 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [amorilaiset](http://finto.fi/yse/fi/page/Y508568)

**Comment by jtuohini** [comment]
LCSH-vastine [**Amorites**](http://id.loc.gov/authorities/subjects/sh85004575).

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Amorilaiset

**Comment by mirmaid** [comment]
4 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. amoriter ET amoréer, amoreer
