### ISSUE TITLE
Porvoon julistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8569]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Porvoon julistus 

#### Ehdotettu termi ruotsiksi   

Borgådeklarationen

#### Ehdotettu termi englanniksi   

The Porvoo Declaration 

#### Assosiatiiviset (RT)   

[Porvoon yhteinen julkilausuma](http://www.yso.fi/onto/yso/p18014) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

https://evl.fi/sanasto/-/glossary/word/Porvoon_julistus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Porvoon julistus kirkko-oikeudellisena ongelmana : ekumenian uudet haasteet / Riikka Junttila-Rantanen. 

**Termiehdotus Fintossa:** [Porvoon julistus](http://finto.fi/yse/fi/page/Y508569)

**Comment by mirmaid** [comment]
11 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
