### ISSUE TITLE
flamenco (perinnemusiikki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8570]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[flamenco (perinnemusiikki)](http://www.yso.fi/onto/ysa/Y101371) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

flamenco (musiikki) tai flamenco (kansanmusiikki) 

#### Perustelut ehdotukselle   

perinnemusiikki -termi on poistettu YSOsta 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto

**Comment by tpalonen** [comment]
Suosittelen sulkutarkennetta (musiikki), koska on neutraalimpi. Flamenco on maailmanlaajuisesti suosittu, levytetty ja sähköistynyt genre, mm. Gipsy Kings. Joku kuvailija saattaisi vieroksua esim. Gipsy Kingsin äänitettä kuvaillessaan termiä "flamenco (perinnemusiikki)".

**Comment by MUUSA-kokous** [comment]
Kannatetaan muotoa _flamenco (musiikki)_.

**Comment by YSO-kokous** [comment]
hyväksytty
