### ISSUE TITLE
yleissitovuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8571]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

yleissitovuus 

#### Vaihtoehtoiset termit ja ilmaisut   

työehtosopimuksen yleissitovuus (eks) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.sttk.fi/wp-content/uploads/sites/2/2019/10/Yleissitovuus_sopimusj%C3%A4rjestelm%C3%A4-_ty%C3%B6paikkatason-sopiminen_2019_verkko.pdf 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Ty%C3%B6ehtosopimus
Työehtosopimuksen yleissitovuus tarkoittaa sitä, että myös järjestäytymättömän työnantajan on noudatettava niitä määräyksiä, joista on sovittu valtakunnallisessa, asianomaisella alalla edustavassa työehtosopimuksessa. 

**Termiehdotus Fintossa:** [yleissitovuus](http://finto.fi/yse/fi/page/Y508571)

**Comment by mariaforsen** [comment]
Sv. kollektivavtals allmänt bindande verkan

**Comment by mirmaid** [comment]
EKS-termiä käytetty Melindassa 42 kertaa. Pelkkä yleissitovuus 2 kertaa.

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa työehtosopimuksen yleissitovuus.
