### ISSUE TITLE
kioskit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8572]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kioskit](http://www.yso.fi/onto/ysa/Y102486) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "kojut" ja "myyntikojut" 

#### Perustelut ehdotukselle   

Ks. esim. https://www.kielitoimistonsanakirja.fi/#/koju ja https://www.kielitoimistonsanakirja.fi/#/myyntikoju 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
_Kojut_ on käytetty Melindassa kolme kertaa eläinten tarkkailuun tarkoitetuista kopeista. En ole varma onko hyvä yhdistää _myyntikojut_ ja _kioskit_, omaan korvaani kioski on pysyvämpi kuin torin tai markkinoiden myyntikoju. Tosin osa myyntikojuista on vähän rajatapauksia.

**Comment by mariaforsen** [comment]
En yhdistäisi, on tosiaan eri asioita. Erikseen voisi toki ottaa myyntikojut = försäljningsstånd (mahdollisesti marknadsstånd)

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermejä. Ei nähty synonyymeina.
