### ISSUE TITLE
kanavasulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8573]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kanavasulut](http://www.yso.fi/onto/ysa/Y191786) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "sulut (kanavasulut)" tms. sulkutarkenteen osalta 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
