### ISSUE TITLE
konsernit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8574]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[konsernit](http://www.yso.fi/onto/ysa/Y96316) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "konglomeraatit" 

#### Perustelut ehdotukselle   

Ks. https://fi.wikipedia.org/wiki/Konglomeraatti_(liiketalous) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Olisiko parempi ohjaus konglomeraatit KÄ _monialayritykset_, ruotsiksi on jo vastaava?
https://www.osakeliitto.fi/uutiset/monialayhtiot-uhkaavat-jaada-historiaan/

**Comment by mariaforsen** [comment]
Laittaisin tarkenteella, koska konglomeraatti on myös (ensisijaisesti) kivilaji. Lisätty ehdotus https://github.com/Finto-ehdotus/YSE/issues/8665

Ainakin motissa sanotaan "(monialayhtiö)" ja Wikipediassa "Monialayrityksestä kertoo artikkeli Konglomeraatti (liiketalous)."

**Comment by jtuohini** [comment]
Ja tuossa jo viitatussa Wikipedia-artikkelissa: "Konglomeraatti on monialayhtymä, konserniyritys, jossa on monenlaisia eri toimialan yrityksiä [- -]" eli viittaus voisi konglomeraateista viedä kumpaankin.

**Comment by YSO-kokous** [comment]
Lisätään seuraava ohjaustermi:
konglomeraatit (monialayritykset) KÄYTÄ monialayritykset
