### ISSUE TITLE
Leighin tauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8575]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Leighin tauti 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305550 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Leighin tauti](http://finto.fi/yse/fi/page/Y508575)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D007888
https://fi.wikipedia.org/wiki/Leighin_oireyhtym%C3%A4
https://www.norio-keskus.fi/tietoa/diagnoosikohtaista-tietoa/leighin-oireyhtyma.html
https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=orp01571

**Comment by mariaforsen** [comment]
Sv. Leighs sjukdom ET Leighs syndrom

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

Googlella muodot tauti/oireyhtymä ovat suunnilleen yhtä käytettyjä.

**Comment by FinMeSHienPaimentaja** [comment]
Leighin **tauti**: https://www.terveysportti.fi/sovellukset/sanakirjat/#/q//lte12380

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa Leighin tauti, ohjaustermiksi Leighin oireyhtymä.
