### ISSUE TITLE
klubitalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8576]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[klubitalot](http://www.yso.fi/onto/ysa/Y128421) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Asiasanan englanninnos pitäisi varmaan olla vain "clubhouses"  ilman 'rehabilitation'-sulkutarkennetta ja LCSH-siltaus asiasanaan "Clubhouses" [http://id.loc.gov/authorities/subjects/sh85027224] -- vai viitataanko asiasanalla ihan muuhun kuin klubihuoneistoihin ja erillisiin klubitaloihin? Vrt. https://en.wikipedia.org/wiki/Clubhouse_model_of_psychosocial_rehabilitation 

#### Perustelut ehdotukselle   

Nykyinen asiasana on vähintään harhaanjohtava, jos sillä halutaan viitata psykososiaaliseen kuntoutukseen eikä ranennuksiin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by tpalonen** [comment]
Off-topic: musiikkiklubit-käsitteelle pitäisi lisätä klubit-alkuinen ohjaustermi. Esim. "klubit (musiikki)". Lisäsin jo tällaisen englanniksi "clubs (music)". Tiedonhakija ei välttämättä tajua lähestyä aihetta musiikki-alkuisesti. Saman voisi tehdä myös ruotsiksi? Muussa tapauksessa riski, että se sekoittuu tähän käsitteeseen _kerhot / clubs (recreational)_: http://www.yso.fi/onto/yso/p7642

Samaan aiheeseen liittyen: klubit-käsitteelle (http://www.yso.fi/onto/yso/p11265) pitäisi minusta lisätä käytettävään termiin sulkutarkenne, koska sekin voi mennä sekaisin musiikkiklubit-käsitteen kanssa.

**Comment by ilona-x** [comment]
klubitalot käytetty Melindassa 36 kertaa, näistä 33 viitettä käsittelee kuntoutusta ja vain 3 viitettä rakennuksia:

- 2004 : Klubbhuset 150 = Klubitalo 150 
- Mäntän Klubin albumi 
- Avoimet ovet ja löydetyt tarinat

**Comment by ilona-x** [comment]
LCSHssa rakennusten lisäksi myös:
Clubhouse Model of Psychiatric Rehabilitation http://id.loc.gov/authorities/subjects/sh2010000564

**Comment by YSO-kokous** [comment]
Muutetaan käytettäväksi termiksi klubitalomalli, ohjaustermiksi klubitalot (kuntoutus).
Lisätään ohjaustermi klubit (musiikki) KÄYTÄ musiikkiklubit.
