### ISSUE TITLE
hallintoalueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8577]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hallintoalueet](http://www.yso.fi/onto/ysa/Y107774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "hallinnolliset alueet" 

#### Perustelut ehdotukselle   

Paljon käytetty ilmaus, josta ei ole YSO:ssa viittaus mihinkään. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
