### ISSUE TITLE
nanotoksikologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8578]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nanotoksikologia 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/303465 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [nanotoksikologia](http://finto.fi/yse/fi/page/Y508578)

**Comment by mirmaid** [comment]
TEROssa ja TSR-ontologiassa.

https://en.wikipedia.org/wiki/Nanotoxicology

**Comment by mariaforsen** [comment]
Sv. nanotoxikologi

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.
