### ISSUE TITLE
metyylielohopea

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8579]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metyylielohopea 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/306728 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [metyylielohopea](http://finto.fi/yse/fi/page/Y508579)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Metyylielohopea
GEO: http://www.yso.fi/onto/gtk/GTK2015ID2421
FinMeSH ja TERO: metyylielohopeayhdisteet, http://www.yso.fi/onto/mesh/D008767

**Comment by mariaforsen** [comment]
Sv. metylkvicksilver ET metylkvicksilverföreningar

**Comment by mirmaid** [comment]
17 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by mirmaid** [comment]
Myös Behnam Tajik.
