### ISSUE TITLE
RNA-virukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8580]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

RNA-virukset 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/304738 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [RNA-virukset](http://finto.fi/yse/fi/page/Y508580)

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/303106

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D012328
LCSH: http://id.loc.gov/authorities/subjects/sh85143842

**Comment by mirmaid** [comment]
8 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. RNA-virus
