### ISSUE TITLE
mantelitumake

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8581]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mantelitumake 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/302781 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mantelitumake](http://finto.fi/yse/fi/page/Y508581)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D000679
LCSH: http://id.loc.gov/authorities/subjects/sh85004720

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. amygdala /ne https://www.medicinskordbok.se/term/amygdala ET amygdalakärna, mandelkärna /mesh
