### ISSUE TITLE
kainaattireseptorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8582]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kainaattireseptorit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/302781 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kainaattireseptorit](http://finto.fi/yse/fi/page/Y508582)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kainaattireseptori

**Comment by mariaforsen** [comment]
Sama kuin tämä (ainakin wikipediakäännösten mukaan)? https://finto.fi/mesh/fi/page/D018092?anylang=on&clang=en

**Comment by mirmaid** [comment]
^ Siltä vaikuttaa.

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään YSOon.

**Comment by mariaforsen** [comment]
Sv.  kainatreceptorer ET kainsyrareceptorer
