### ISSUE TITLE
tilapalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8583]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tilapalvelut](http://www.yso.fi/onto/ysa/Y142617) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT toimitila- ja käyttäjäpalvelut 

#### Perustelut ehdotukselle   

https://termipankki.fi/tepa/fi/haku/toimitila-%20ja%20k%C3%A4ytt%C3%A4j%C3%A4palvelut

**Comment by YSO-kokous** [comment]
Ei oteta ohjaustermiä, koska käyttäjäpalvelut-termin merkitys on paljon tätä laajempi.
