### ISSUE TITLE
sävellykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8584]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sävellykset](http://www.yso.fi/onto/ysa/Y108687) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde asiasanasta "musiikilliset objektit" --> "taiteelliset teokset" 

#### Perustelut ehdotukselle   

Kaikki sävellykset teoksia, tarkemmin ilmaistuna taiteellisia teoksia, joten niitä kuvaava asiasana olisi osuvampi kuin nykyinen. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by asormune** [comment]
Miksi (Finto-ehdotus YSE) termin linkki vie "YSA - Yleinen suomalainen asiasanasto sivuille"?

**Comment by tpalonen** [comment]
Finton tekniset resurssit on tällä hetkellä suunnattu uuden ehdotusjärjestelmän kehittämiseen. YSA-ongelma on tiedostettu, mutta vanhan järjestelmän korjaamiseen ei valitettavasti ole tällä hetkellä resursseja. Vanha ehdotusjärjestelmä on rakennettu alunperin YSA-ehdotuksia varten.

**Comment by MUUSA-kokous** [comment]
Kannatetaan, jos muutos tehdään muillekin taiteellisille teoksille. Muuten LT _teokset_.

**Comment by mirmaid** [comment]
_Taiteelliset teokset_ -käsitteellä ei ole tällä hetkellä alakäsitteitä. Sävellysten osalta molemmat ehdotukset voisi ja kannattaisikin toteuttaa monihierarkiana, eli säilyttää myös aikaisempi yläkäsite.

**Comment by jtuohini** [comment]
Myös muista tehty ehdotuksia: https://github.com/Finto-ehdotus/YSE/issues/8586 ja https://github.com/Finto-ehdotus/YSE/issues/8587

**Comment by mirmaid** [comment]
Lisätty toinen yläkäsite.
