### ISSUE TITLE
rakenteistumisteoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8585]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakenteistumisteoria](http://www.yso.fi/onto/ysa/Y108313) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan (jos viittaa samaan kuin strukturaatioteoria) 

#### Perustelut ehdotukselle   

Näyttää olevan synonymi, sanastossa on myös strukturaatioteoria, joka määritellään Giddensin merkityksen mukaan. Tällä termillä ei ole huomautusta mutta googlehaku paljastaa että on myös kysymys Giddensistä. Eng. vastine molemmille on structuration theory, ruotsiksi myös synonymejä.

**Comment by YSO-kokous** [comment]
Yhdistetään käsitteet rakenteistumisteoria ja strukturaatioteoria. Käytettäväksi termiksi otettaneen strukturaatioteoria.

**Comment by mirmaid** [comment]
YSOn ylläpitoryhmä valitsi käytettäväksi termiksi _rakenteistumisteoria_ (YSOssa vanhempi ja esim. Helsingin yliopistossa enemmän käytetty muoto).
