### ISSUE TITLE
taideteokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8586]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taideteokset](http://www.yso.fi/onto/ysa/Y104506) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde asiasanaan "teokset" --> "taiteelliset teokset" 

#### Perustelut ehdotukselle   

Taideteokset kuuluisivat hierarkkisesti paremmin taiteellisten teosten alle kuin suoraan teosten alle. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Muutettu.
