### ISSUE TITLE
tanssiteokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8587]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssiteokset](http://www.yso.fi/onto/ysa/Y128464) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde asiasanaan "teokset" --> "taiteelliset teokset" 

#### Perustelut ehdotukselle   

Tanssiteokset kuuluisivat hierarkkisesti paremmin taiteellisten teosten alle kuin suoraan teosten alle. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Muutettu.
