### ISSUE TITLE
keskusteluryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8589]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keskusteluryhmät](http://www.yso.fi/onto/ysa/Y111986) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Asiasanan voisi ehkä muuttaa muotoon, joka tekisi selväksi, että kyse on nimenomaan verkkojutteluryhmästä, ei muunlaisesta keskusteluryhmästä. 

#### Perustelut ehdotukselle   

Nykyisellään asiasana voi lipsahtaa aineistoihin, jotka eivät käsittele verkkojutteluryhmiä (uutisryhmiä, "nyyssejä"), kun alkaa ilmiönä olla jo hieman lähihistoriallinen. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
KT-muodoksi voisi lisätä myös keskustelupalstat & keskustelufoorumit, jotka ovat ehkä uutisryhmiä uudempi ilmiö 🤓 : https://termipankki.fi/tepa/fi/haku/keskusteluryhm%C3%A4

Verkkojuttelu taitaa sitten olla asia erikseen eli reaaliaikainen verkkokeskustelu (chat, irc) http://www.yso.fi/onto/yso/p17816

**Comment by ilona-x** [comment]
Ja vielä tähän Kielitoimiston sanakirjan mukaan tosiaan kaksi merkitystä:
keskustelu­ryhmä
1. keskustelijoiden muodostama ryhmä.
Yhdistyksen järjestämät avoimet keskusteluryhmät.
2. eril. sähköisistä palveluista ja sivustoista.
a. tavallisemmin: keskustelupalsta.
b. aik. internetissä toimineita palveluja, joiden käyttäjät saattoivat lukea ja kirjoittaa aiheittain jaoteltuja artikkeleita, ilmoituksia t. mielipiteitä. 

Eli olisiko selkeintä muuttaa käytettäväksi termiksi **keskustelupalstat**?

**Comment by mariaforsen** [comment]
Sanastossa on jo keskustelupalstat erikseen (joka viittaa nimenomaan netissä oleviin). En näe mitään siitä miksei tämä voisi olla "keskusteluryhmä" riippumatta formaatista, mistä oikeastaan tulee käsitys että tämä koskisi vain netissä olevia ryhmiä? Ryhminä sekä 45 että 60. Myös ruotsinkielinenkin termi on neutraali sen suhteen. Melindassakin näyttää olevan käytetty muustakin kuin netissä olevista ryhmistä.

**Comment by YSO-kokous** [comment]
Ei nähty tarvetta muutoksille paitsi vaihdetaan keskusteluryhmät-käsitteen LCSH-linkitys narrowmatchiksi. Termi keskusteluryhmä viittaa ryhmään, joka keskustelee, eikä ota kantaa siihen, missä keskustelu käydään.
