### ISSUE TITLE
parlamenttitalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#859]
#### Ehdotettu termi suomeksi

parlamenttitalot
#### Ehdotetut ohjaustermit

valtiopäivätalot
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)
[91 Arkkitehtuuri](http://www.yso.fi/onto/ysa/ryhma_91)
#### Lähde

Julkaisu: Westerbom, T. Folkets suveränitet förstenad

**Luontipäivämäärä:** 17.12.2002

**Muokkauspäivämäärä:** 8.2.2005, 8.2.2005, 17.12.2002, 16.12.2008

**Voyager-id:** 122307

**Termiehdotus Fintossa:** [parlamenttitalot](http://finto.fi/yse/fi/page/Y322307)

**Comment by jtuohini** [comment]
Tarvetta on edelleen tälle!
 
LCSH-vastine: [**Capitols**](http://id.loc.gov/authorities/subjects/sh85019978)
Wikidata-siltaus: https://www.wikidata.org/wiki/Q224158

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. parlamentsbyggnader ET parlamentshus 
JOS pohjoismaissa: riksdagsbyggnader 
https://id.kb.se/term/sao/Riksdagsbyggnader = lcsh capitols

**Comment by ilona-x** [comment]
MAOssa parlamenttitalot http://www.yso.fi/onto/mao/p7159

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon muodossa _parlamenttitalot_.

**Comment by jtuohini** [comment]
Ja tälle pitäisi olla KT-muotona _kongressitalot_, josta nyt on vahingossa tehty uusi, oma itsenäinen asiasanansa kokouskeskuksien sijaan. Ks. https://github.com/Finto-ehdotus/YSE/issues/8719.

**Comment by mariaforsen** [comment]
TEPA: kongressitalo=kulttuurirakennus, jossa järjestetään kongresseja https://termipankki.fi/tepa/sv/s%C3%B6k/kongresshus

**Comment by YSO-kokous** [comment]
parlamenttitalot KT kongressitalot (parlamenttitalot)
nykyinen kongressitalot muutetaan muotoon 
kongressikeskukset KT kongressitalot (kongressikeskukset)
