### ISSUE TITLE
väliyhteisöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8590]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[väliyhteisöt](http://www.yso.fi/onto/ysa/Y113705) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko YSOn eng. oikeasti controlled corporations? 

#### Perustelut ehdotukselle   

https://termipankki.fi/tepa/fi/haku/offshore-yhti%C3%B6

**Comment by mariaforsen** [comment]
https://en.wikipedia.org/wiki/Offshore_company = https://fi.wikipedia.org/wiki/Offshore-yritys

**Comment by tpalonen** [comment]
Termistöä lisätty englanniksi. Päätermiksi muutettu controlled foreign corporations. 
Ks. esim. https://www.wikidata.org/wiki/Q441835
https://www.finlex.fi/en/laki/kaannokset/1994/en19941217_19981091.pdf
