### ISSUE TITLE
kotiteatterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8591]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kotiteatterit](http://www.yso.fi/onto/ysa/Y117569) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi eng. KT home cinema ja home entertainment systems? 

#### Perustelut ehdotukselle   

LCSH home entertainment systems
https://en.wikipedia.org/wiki/Home_cinema

**Comment by ilona-x** [comment]
pitäiskö tämä olla suomeksi mieluummin kotiteatterijärjestelmät tmv. kun yläkäsitteenä on audiovisuaalinen laitteisto?
Nyt linkattu LCSH 
Home Theatres
KT Home motion picture theaters
KT Theater rooms
LT  Rooms

Kielitoimiston sanakirja:
koti­teatteri
yhdistelmä viihde-elektroniikan laitteita, joilla saadaan aikaan elokuvateatterimainen kuvan- ja äänentoisto; kodin t. laitoksen teatterinomaiseksi järjestetty huone, jossa em. laitteita käytetään.

**Comment by YSO-kokous** [comment]
Muutetaan käytettävä termi muotoon kotiteatterijärjestelmät. Muut kielet tämän mukaisesti.
