### ISSUE TITLE
oopperaryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8593]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oopperaryhmät 

#### Ehdotettu termi ruotsiksi   

operagrupper 

#### Ehdotettu termi englanniksi   

opera companies 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ryhmät](http://www.yso.fi/onto/yso/p1127) 

#### Vastaava käsite muussa sanastossa   

LCSH : Opera companies 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://uniarts.finna.fi/Record/uniarts.994180124206249 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

YSOsta puuttuu käsitteet oopperataloille organisaatioina ja oopperaryhmille. Vrt. teatterit (organisaatiot), teatteriryhmät. 

**Ehdottajan organisaatio:** Taideyliopiston kirjasto **Termiehdotus Fintossa:** [oopperaryhmät](http://finto.fi/yse/fi/page/Y508593)

**Comment by MUUSA-kokous** [comment]
Kannatetaan. Määritelmäehdotus seuraa myöhemmin.

**Comment by jarmosaarikko** [comment]
YSOssa on jo [teatteriryhmät](http://www.yso.fi/onto/yso/p8966) ja [tanssiryhmät](http://www.yso.fi/onto/yso/p6485) KT "balettiseurueet"

- **oopperaryhmät** (opera companies)- wikidata: https://www.wikidata.org/wiki/Q20819922   LT "ryhmät" tai "organisaatiot"    LCSH http://id.loc.gov/authorities/subjects/sh85094909 "Opera companies"
- vastaavasti voisi olla omana käsitteenään: **balettiryhmät** (ballet companies)  LT "ryhmät" tai "organisaatiot" KT "balettiseurueet"  https://www.wikidata.org/wiki/Q805233 LCSH http://id.loc.gov/authorities/subjects/sh85011281

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by YSO-kokous** [comment]
hyväksytty

**Comment by mariaforsen** [comment]
Sv. operasällskap ET operagrupper, operakompanier

**Comment by mirmaid** [comment]
_Määritelmäehdotus seuraa myöhemmin_. (?)

**Comment by MUUSA-kokous** [comment]
Määritelmäehdotus: "Oopperoita esittävä yhteisö".
KT oopperaseurueet
