### ISSUE TITLE
tarkkuuslääketiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8594]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tarkkuuslääketiede 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305495 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tarkkuuslääketiede](http://finto.fi/yse/fi/page/Y508594)

**Comment by ilona-x** [comment]
FinMeSH:
täsmälääketiede http://www.yso.fi/onto/mesh/D057285

**Comment by mariaforsen** [comment]
Sv. precisionsmedicin ET individualiserad medicin, individuellt anpassad medicin, personaliserad medicin

**Comment by mirmaid** [comment]
_Täsmälääketiede_ kerran Melindassa.

**Comment by YSO-kokous** [comment]
Otetaan YSOon muodossa täsmälääketiede ja ohjaustermiksi tarkkuuslääketiede.

**Comment by mariaforsen** [comment]
Varmaan myös meshin ohjaustermit sekä tämä https://stm.fi/yksilollistetty-laaketiede
