### ISSUE TITLE
Valkoinen talo (Värtsilä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8595]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Valkoinen talo (Värtsilä) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Valkoisen talon historia 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Valkoinen talo (Värtsilä)](http://finto.fi/yse/fi/page/Y508595)

**Comment by mirmaid** [comment]
https://vartsi.net/2011/04/07/valkoinen-talo/

**Comment by mariaforsen** [comment]
Sv. Valkoinen  talo (Värtsilä)
