### ISSUE TITLE
eskimokielet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8597]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[eskimokielet](http://www.yso.fi/onto/ysa/Y101318) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YKL-ryhmälle tullut palaute: "Olen aiemminkin (tälle luokalle on nimittäin ollut tässä käyttöäkin) hieman miettinyt tuota 89.98:n "eskimokielet", koska eskimo- nimitystä on ymmärtääkseni jossain määrin alettu pitää halventavana. Myös tuo saman luokan "intiaani" on toki herättänyt viime aikoina keskustelua. Voisiko näiden alkuperäiskansojen kielten nimityksiä tarkistaa? 

#### Perustelut ehdotukselle   

x

**Comment by ilona-x** [comment]
^Sopivasti tämän päivän uutisista poimittua 🍦 : https://www.mtvuutiset.fi/makuja/artikkeli/nyt-se-on-varmaa-legendaarisen-eskimo-jaatelon-nimi-muuttuu-tassa-uusi-pakkaus-ja-nimi/7988106#gs.laxbsk

**Comment by marjutpu** [comment]
YKL-ryhmän käymää keskustelua:

Ehdottomasti tarkistettava! Mielestäni ne pitäisi olla kielitoimiston suositusten mukaiset. Siis molemmat: intiaanikielet, eskimokielet. Samalla pitäisi myös hakutermit intiaanit, eskimot miettiä kokonaan uudestaan. Näiden muuttaminen kyllä sisältä pienoisen ongelman, sillä nämä ovat varmaan ne termit, millä ihmiset niitä vielä hakevat. Mutta voisiko ainakin kaavaan vaihtaa ajantasaiset korrektit termit.

Kielten nimien suhteen muutos voi olla vaikea, koska nämä ovat kai edelleen kielitieteen käyttämiä termejä (+ mm. YSOssa). Kielitieteellistä ongelmaa valaisee mm. tämä Kielikellon artikkeli: https://www.kielikello.fi/-/eskimo-vai-inuitti-

Jaakko Anhavan Maailman kielet ja kielikunnat on vuodelta 1998, vielä vanhempi. S.188: 'Amerikan mannerten alkuperäisasukkaista eskimoiden kielet muodostavat luonnollisen kielikunnan, sen sijaan nimitys "intiaanikielet" tarkoittaa kaikkien muiden Pohjois- ja Etelä-Amerikan alkuasukkaiden puhumia kieliä sukulaisuuteen katsomatta.'
Pelkästään Pohjois-Amerikan puhuttujen intiaanikielten määrä on n. 150.

"Eskimo-aleuttilaiset kielet" näyttää olevan edelleen vankasti käytössä. Sen käyttöä perustellaan kielitieteellisillä syillä esim. englannin ja saksan kielisissä Wikipedia-artikkeleissa. Ranskaksi Wikipediassa kerrotaan myös vaihtoehtoiset nimet (dites aussi eskaléoutes ou inuites-aléoutes). Myös 2013 ilmestynyt "Johdatus kielitieteeseen" käyttää eskimo-aleuttilainen termiä. En tällä perusteella uskaltaisi ruveta tuota muuttamaan. Intiaanikielet on tosiaan erilainen tapaus, koska siinä ei ole kyse kielikunnasta. Tieteen termipankissa määritelmä on Anhavalta: "termillä "intiaanikielet" viitataan kaikkiin Amerikan alkuasukkaiden kieliin sukulaisuudesta riippumatta". Vaikka YSO käyttää edelleen intiaanikieliä, tämän voisi varmaankin luokan 89.98 otsikossa muuttaa muotoon "Amerikan alkuperäiskielet". Esim. "Johdatus kielitieteeseen" (Ojutkangas, 2013) ei näytä käyttävän lainkaan intiaanikielet -termiä.

https://www.kielikello.fi/-/intiaanisanastoa-tyylikkaasti-suomeksi

Kielitieteessä käytetty termi eskimokielet jaetaan jupikkieliin ja inuitikieliin. Molemmissa käytetään termiä eskimo, paitsi kanadalaiset eskimot haluavat käyttää itsestään nimitystä inuiti. Täten termi eskimo on ainakin vielä ihan neutraali.

Euroopassa sana intiaani on neutraali, Jenkeissä ei kai niinkään... Mielestäni intiaanikielet-sana kannattaa jättää ainakin termiksi, koska ihmiset eivät osaa hakea sanoilla Amerikan alkuperäiskielet, vaikka se olisikin korrektimpi muoto. Siis tarkoitan, että Amerikan alkuperäiskielet voi hyvin olla käytettävä termi, mutta intiaanikielet esim. ohjaustermiksi muiden ohella. Fintosta löytyi kohta Supistettu UDK, jossa termit näin https://finto.fi/udcs/fi/page/000880 (tässä virheitä) ja https://finto.fi/udcs/fi/page/001166

**Comment by mirmaid** [comment]
Ks. Marjutin yllä linkittämä Kielikellon artikkeli. Vaihtoehtoista, kaikkien mielestä korrektia, mutta samaa tarkoittavaa termiä ei ole olemassa.

**Comment by YSO-kokous** [comment]
Ei toistaiseksi muutoksia. Eskimokielet näyttää edelleen olevan se termi, jota tässä yhteydessä käytetään.

**Comment by mirmaid** [comment]
Tässä artikkelissa hyvin seikkaperäisesti ongelmasta paitsi kielten, myös etnisten ryhmien nimien osalta: https://www.kielikello.fi/-/eskimo-vai-inuitti-
