### ISSUE TITLE
siirtoistutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8599]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[siirtoistutus](http://www.yso.fi/onto/ysa/Y122090) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan huomautuksella tms. toimenpide 

#### Perustelut ehdotukselle   

Ongelmallinen ainakin ruotsin kannalta. Eng. on nyt transplantation (vaikka onkin Tieteen termipankissa mainittu näin, niin ei tunnu juuri löytyvän aineistoissa, vaan enemmän näyttää olevan translocation, reintroduction jne.)

Sanastossa on myös istutus (eläimet) = inplantering (djur). Siirtoistutus=utplantering on korjattava ruotsiksi (synonymi termille inplantering). Mahdollinen ratkaisu on tarkenteen lisääminen tms., esim. "in/utplantering i nya områden" tms. -jos termin pitää viitata tähän: eliön istuttaminen sellaiselle alueelle, jolta se on aikaisemmin puuttunut? Mutta siinä tapauksessa on myös lisättävä huomautus tästä. Melindassa siirtoistutus on käytetty myös muussa merkityksessä, esim. puun siirrosta.

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Biologia:siirtoistutus
https://fi.wikipedia.org/wiki/Siirtoistutus

**Comment by mirmaid** [comment]
Auttaisikohan jokin sen tyyppinen kuin siirtoistutus (puutarhakasvit) KÄ _istutus (kasvit)_ + määritelmä siirtoistutukselle Tieteen termipankin mukaan? Virheellistä käyttöä on joitakin kertoja lähinnä artikkeliaineistossa.

**Comment by YSO-kokous** [comment]
Hyväksytään mirmaid-ehdotus edellä.
