### ISSUE TITLE
trip hop

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8601]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

trip hop 

#### Ehdotettu termi ruotsiksi   

triphop 

#### Ehdotettu termi englanniksi   

trip hop 

#### Ehdotettu yläkäsite YSOssa (LT)   

[elektroninen tanssimusiikki](http://www.yso.fi/onto/yso/p29932) 
[popmusiikki](http://www.yso.fi/onto/yso/p2969) 

#### Assosiatiiviset (RT)   

[hip hop](http://www.yso.fi/onto/yso/p14336) 

#### Vastaava käsite muussa sanastossa   

Trip-hop (Music) (LCGF) : https://lccn.loc.gov/gf2014027146 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Tarvitaan ainakin SLM-sanastoon trip hop -artistien musiikin kuvailuun. Artisteja esim. Massive Attack, Faithless, Tricky, Portishead, Gorillaz... 

#### Tarkoitusta täsmentävä selite   

Trip hop on 1990-luvulla Bristolin kaupungissa Britanniassa syntynyt elektronisen musiikin muoto, joka perustuu jumittaviin ja synkkiin rytmeihin. Laulu on usein melodista, mutta välillä myös hyvin rap-henkistä. Trip hopissa on otettu vaikutteita downtemposta, hip hopista, dancesta, housesta, dubista, reggaesta, jazzista, soulista ja rockista. (Wikipedia) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tricky: Fall into pieces ; Faithless: All blessed ; Gorillaz: Song machine 

**Ehdottajan organisaatio:** Kirjastopalvelu

**Comment by mariaforsen** [comment]
Sv. triphop ET trip-hop 

https://sv.wikipedia.org/wiki/Triphop

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by tpalonen** [comment]
Suositan vahvasti suomenkieliselle käytettävälle termille yhteenkirjoitettua muotoa. Helsingin Sanomissa yhteenkirjoitettu muoto triphop on selvästi enemmän käytössä kuin erikseen kirjoitettu muoto trip hop. (51 vs 24 esiintymää). Samoin Rumbassa (96 vs 43). Samoin Soundissa (30 vs 24).

Vrt. kotimaisten keskeisten musiikkimedioiden ammattitoimittajilla teettämäni kysely (ks. Github-linkki alla), jossa suurin osa toimittajista suositti musiikkigenrejen yhteenkirjoitettuja muotoja erikseen kirjoitettujen sijaan (poikkeuksena metallimusiikin genret). Käytettyjä termejä ei lähdetty YSOssa muuttamaan, vaikka perustelut muutokselle olivat varsin hyvät. Toivottavasti kuitenkin jatkossa uusien käsitteiden kohdalla noudatetaan yhteenkirjoitusta, ellei ole selviä perusteita tehdä toisin.
https://github.com/Finto-ehdotus/YSE/issues/8126

**Comment by MUUSA-kokous** [comment]
Kannatetaan termin yhteenkirjoitettua muotoa.

**Comment by LeKorsu** [comment]
Ylen musiikkiäänitekannassa on kirjoitettu erikseen "trip hop" (122 biisissä) .... Mutta en vastusta yhteenkirjoitettua muotoa.

**Comment by tpalonen** [comment]
Joo, tämän huomasinkin. Kuitenkin Ylenkin uutisteksteissä yhteenkirjoitettu muoto näyttäisi olevan käytössä:
esim. https://yle.fi/uutiset/3-6120873

**Comment by YSO-kokous** [comment]
Hyväksytään yhteenkirjoitetussa muodossa.
