### ISSUE TITLE
vankeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8602]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vankeus](http://www.yso.fi/onto/ysa/Y100071) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään huomautus merkityksestä tms. tarkennus? 

#### Perustelut ehdotukselle   

Ruotsiksi on ollut fångenskap, mutta jos tämä viittaa vain vankeusrangaistukseen niin tämä pitäisi muuttaa > fängelse (straff) tms. Termiä fångenskap ei käytetä vankeudesta vankilassa. Ryhmä ja suhteet viittaavat nyt siihen että olisi vankeusrangaistuksesta kyse, mutta toisaalta Melindassa on käytetty myös muusta vankeudesta.

**Comment by mariaforsen** [comment]
Jos tätä ei voida rajoittaa vain vankeusrangaistukseen, niin toinen mahdollinen ratkaisu voisi olla:
-vankeus (vankina olo tms.) = fångenskap
-vankeusrangaistus KT vankeus ( rangaistus) = fängelsestraff

**Comment by mirmaid** [comment]
Tuo _vankeus (vankina olo)_ ei suomeksi rajaa pois vankeutta vankilassa. 

Käytetty suurimmaksi osaksi vankeudesta vankilassa, lisäksi sotavankeudesta, vankileireistä ja terroristijärjestön vankina olosta. Joitakin kertoja myös ihmisryöstöstä tai perheenjäsenen vankina olosta. (ensimmäiset 100 viitettä)

Sitten esim. tällainen: https://melinda.kansalliskirjasto.fi/byid/011455171

**Comment by YSO-kokous** [comment]
vankeus (vangittuna olo)
vankeus (rikokset), vapausrangaistukset KÄ vankeusrangaistus
