### ISSUE TITLE
toisinnot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8603]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toisinnot](http://www.yso.fi/onto/ysa/Y206819) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään huomautus/määritelmä 

#### Perustelut ehdotukselle   

Ruotsiksi versioner, mutta vaatii tarkenteen lisäämistä tms. Mihin kaikkeen tätä voi käyttää suomeksi? Onko aina kyse jonkinlaisesta kerronnasta?

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/toisinto
KS: muunnos, rinnakkaisasu, -muoto, variantti. 
https://evl.fi/sanasto/-/glossary/word/Toisinto
https://tieteentermipankki.fi/wiki/Nimitys:toisinto

Ohjaustermi on variantit. Sanastossa on myös mukaelmat ja sovitukset.

**Comment by jtuohini** [comment]
Myös kansansävelmien yhteydessä puhutaan toisinnoista. Siinä yhteydessä tarkoittaa samaa kuin variantti tai versio (ei siis sama asia kuin mukaelma tai sovitus).

**Comment by tpalonen** [comment]
Sen verran kimurantti asia, että käsiteltäisiinkö pikemminkin ongelmakokouksessa?

**Comment by mirmaid** [comment]
Tähän olisi kiva saada Kristiinan kommentti? Kyseessä voi kai olla ainakin kansanperinne/kertomusperinne, mutta jos myös sävellys voi olla toisinto, _kerronta_ ei sovi tarkenteeksi. _Teokset_ ei varmaan ole tarpeeksi poissulkeva? Ehkä tähän pystyisi kuitenkin muodostamaan jonkun x och x -tyyppisen tarkenteen? Jos pitää taas ottaa erikseen toisinnot (sävellykset) ja toisinnot (kerronta), ollaan todennäköisesti taas samassa liemessä kuin balladien ym. musiikki vs. ei-musiikki ketjutustarkenteiden kanssa, eli osassa aineistosta ero ei mene näiden kahden välillä, vaan sekä sävellys, että sanat ovat osa toisintoa.

**Comment by krinay** [comment]
Kamalan vaikea on tosiaan keksiä järkevää tarkennetta  tai riittävän yksiselitteistä määritelmää. Termiä käytetään suullisen perinteen yhteydessä, on kansansadun (esimerkiksi Tuhkimo-sadun), kansanrunon, kansanlaulun, arvoituksen jne. toisintoja eli esiintymiä, (arkisto)muistiinpanoja tms. Kyse ei ole tietyn "alkuteoksen" mukaelmista, vaan eri tilanteissa (eri kerroilla, eri paikoissa jne.) esitetystä versiosta, varianteista. -- Yritän miettiä vielä jotakin täsmällisempää keskiviikoksi.

**Comment by krinay** [comment]
Tuli muuten mieleen, että auttaisiko asiaa yhtään, jos ruotsinkielinen termi olisi _varianter_ eikä _versioner_? Ainakin folkloristit käyttävät ruotsinkielistä termiä _varianter_.

**Comment by mariaforsen** [comment]
Variant ei kerro sen enempää kuin versionkaan, https://svenska.se/tre/?sok=variant&pz=1 Voi esim. olla kasvi, virus tai mikä tahansa muu, eli tarkenne on miten vain tarpeen. Muutan siis mielelläni termi varianter:iksi, mutta sekin tarvitsee tarkenteen.

**Comment by mirmaid** [comment]
Olisiko muodolle _varianter_ yhtään helpompaa keksiä tarkennetta kuin versioner-termille? Vaikka siis kumpikaan ei toki ilman tarkennetta rajaudu tähän merkitykseen.

**Comment by mariaforsen** [comment]
Ei ole helpompaa, olennaista on edelleen se että mihin kaikkeen toisinnot käytetään, sen mukaan voidaan valita minkälainen tarkenne laitetaan.

**Comment by krinay** [comment]
_Varianter_ vastaisi parhaiten toisinnot-termin folkloristista merkitystä, vaikka ei rajaakaan merkitystä yleisessä kielenkäytössä. 

Kyseessä on aivan keskeinen folkloristinen käsite, mutta YSOssa merkitystä ei tietenkään tarvitse rajata siihen. Tarkalleen ottaen versio ja toisinto eivät ole folkloristiikassa aivan sama asia, mutta niin hienovaraiseen ja täsmälliseen merkitykseen ei voi eikä ole tarpeenkaan pyrkiä yleisessä sanastossa (ks. hyvä blogikirjoitus, jonka seassa ärsyttävän paljon mainoksia: https://www.patheos.com/blogs/foxyfolklorist/folklorethursday-version-vs-variant/). 

Kuinka paljon sotkua eli epärelevanttia käyttöä olisi luvassa - ja toisaalta, mitä tarpeellista jäisi uupumaan, jos olisi ilman tarkenteita ja määritelmiä: 
_toisinnot_ - _variants_ - _varianter_ ja ryhmät 50 (ml.  kansansävelmät?) ja 87?

**Comment by mariaforsen** [comment]
Ruotsiksi on tuskin mahdollista pitää ilman tarkennetta, koska se voi tosiaan viitata ihan mihin vain (toisin kuin suomeksi).
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/variant

**Comment by krinay** [comment]
Toistaiseksi tilanne näyttäisi olevan Melindassa hyvin hallinnassa. Asiasanaa on käytetty 112 kertaa ja lähes yksinomaan suullisen perinteen ja kirjallisuuden yhteydessä. Pari kertaa rahan keräilijöiden oppaan ja pari (vai oliko kolme) kertaa postimerkkien (keräilyn) yhteydessä. En tunne numismatiikkaa enkä filateliaa, joten en tiedä, miten siellä toisinnot määritellään. Ei ehkä ole kovin kaukana kirjallisuudentutkimuksen (tieteellisten editioiden laadinnassa käytetystä) käsitteestä.

**Comment by mirmaid** [comment]
Mietin, että jos _version_ menee sekaisin _mukaelmien_ ja _sovitusten_ kanssa (?), niin meneekö myös _variant_ sekaisin niiden kanssa, vai vain kasvien, virusten jne.? Eli jos esim. (verk) tai (konst och tradition) ei erottele versioner-termiä oikein, voisiko sen tyyppinen erotella variant-muotoa niistä, joihin se sekoittuu? Mutta jos myös variant sekoittuu samoihin kuin version, niin sitten ei auta tietenkään.

**Comment by YSO-kokous** [comment]
Kristiina kysyy vielä kommenttia liittyen tekstuaalitieteisiin. Lisätään ruotsiksi tarkenne (tradition) tms.

**Comment by krinay** [comment]
Asiantuntija, jolta asiaa kysyin, on sitä mieltä, että _toisinnot_ on tekstuaalitieteiden ja kirjallisuudentutkimuksen näkökulmasta vanhentunut termi. Käytettyjä termejä ovat _variantit_ ja _versiot_, mutta ne eivät ole niin olennaisia tai tiedonhaun kannalta tärkeitä, että niitä tarvittaisiin YSOon. _Toisinnot_ voisi siis jäädä käyttöön folkloristisessa merkityksessä, ruotsinkielisenä vastineena _varianter_ sopivalla tarkenteella (tradition/folktradition/folklore tms.).

**Comment by mariaforsen** [comment]
Sulkutarkenne "tradition" ei kovin selkeästi erottele (kuuluuhan traditioniin esim. musiikki ja kaikenlaista muutakin), eikä myöskään verk, koska se voi olla mikä tahansa teos. Mutta jos kerronta tms. rajoittaa liikaa, saattaa olla ettei ole vaihtoehtoja.

**Comment by mirmaid** [comment]
Varianter (tradition)
