### ISSUE TITLE
renium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8604]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

renium 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www3.uef.fi/ajassa/vaitostiedotteet/-/asset_publisher/g2ss1EfgtZyc/content/id/2312143 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [renium](http://finto.fi/yse/fi/page/Y508604)

**Comment by mariaforsen** [comment]
Sv. rhenium
