### ISSUE TITLE
korkein oikeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8605]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

korkein oikeus 

#### Ehdotettu termi ruotsiksi   

högsta domstolen 

#### Ehdotettu termi englanniksi   

Supreme Court 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tuomioistuimet](http://www.yso.fi/onto/yso/p3961) 

#### Perustelut ehdotukselle   

Käsitteen kuuluisi olla myös YSO:ssa, Tuomioistuimet-osuus on nyt puutteellinen,ks. myös https://oikeus.fi/tuomioistuimet/fi/index.html vrt. http://www.yso.fi/onto/koko/p56329 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Valtiopäiväasiat ja -asiakirjat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

**Ehdottajan organisaatio:** Eduskunnan keskuskanslia **Termiehdotus Fintossa:** [korkein oikeus](http://finto.fi/yse/fi/page/Y508605)

**Comment by vthuhtal** [comment]
Asterin yhteisöauktoriteetti: Suomi. Korkein oikeus

**Comment by mirmaid** [comment]
Löytyy tosiaan KANTOsta: http://urn.fi/URN:NBN:fi:au:finaf:000034981. Toisaalta hierarkiasta nyt puuttuu ylin oikeusaste yleisesti, https://fi.wikipedia.org/wiki/Ylin_oikeusaste.

**Comment by ilona-x** [comment]
Voisiko ottaa YSOon monikossa korkeimmat oikeudet, kun on myös Korkein hallinto-oikeus?  Ja toki muuallakin maailmassa: https://fi.wikipedia.org/wiki/Luokka:Korkeimmat_oikeudet

**Comment by mariaforsen** [comment]
Sv. högsta domstolar ET högsta domstolen, högsta rättsinstans

**Comment by mirmaid** [comment]
Melindassa 2 kertaa _korkeimmat oikeudet_ (merkitty eks-termiksi, mutta ei löydy eks:stä). 3 kertaa _ylin oikeusaste_.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa _korkeimmat oikeudet_, ohjaustermiksi _ylin oikeusaste_ [yksikössä].
