### ISSUE TITLE
kulkeutuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8606]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kulkeutuminen](http://www.yso.fi/onto/ysa/Y112063) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Voidaanko määritellä/lisätä huomautus? 

#### Perustelut ehdotukselle   

Ruotsiksi migrering, mutta se ei ole ok sellaisenaan (joko lisätään tarkenne, muutetaan termi esim. "spridning med" tms.) ja termin valinta riippuu merkityksestä. Onko esim. tämän mukainen: https://fi.wikipedia.org/wiki/Kulkeutuminen vai jokin näistä: https://termipankki.fi/tepa/fi/haku/kulkeutuminen

**Comment by jarmosaarikko** [comment]
Käsittääkseni yleisempi lienee tuon wikipedian määritelmän mukainen käsite kulkeutuminen (aineen liike, mass transfer tms.) kuin termipankin siirto, kuljetus, migrering

**Comment by mariaforsen** [comment]
Hankala termi ruotsin osalta, mutta nykyinen vastine ei ainakaan ole ok, joten se pitäisi korjata mahdollisimman pian.

**Comment by mirmaid** [comment]
_Kulkeutuminen_ on ainakin aina passiivista, jonkin mukana paikasta toiseen joutumista, ei itsenäistä vaeltamista eikä toisen suorittamaa siirtämistä. Wikipedia-sivu on juuri tätä, mutta mielestäni myös moni noista TEPAn viitteistä, vaikka niissä onkin osin outoja termimuotoja.

**Comment by mirmaid** [comment]
_Kaukokulkeutuminen_ näyttää olevan _fjärrtransport_, mutta tarvitseeko se tarkenteen? Kun tulee googlella kuljetusalan tuloksia?

**Comment by mariaforsen** [comment]
Jos tarkoitus on viitata esim. ilmansaasteiden kaukokulkeutumiseen niin voi olla että pitää vaihtaa koko termi ruotsiksi. 

Mutta mitä tulee kulkeutumiseen niin sitä ei saa käännettyä järkevästi, ellei määritellä ensin mihin se viittaa. Ja se pitää olla näkyvissä (tarkenne tai ainakin huomautus) myös käyttäjille, jotta se sitten käytetään samalla tavalla molemmilla kielillä.

Onko nykyinen eng. vastine https://en.wikipedia.org/wiki/Advection ok? Jos todella on niin mahdollisesti yksi vaihtoehto ruotsiksi voisi olla vastaava "advektion" + tarkenne? Ei se kuitenkaan varmaan ole, kun sitten termi olisi varmaan suomeksikin advektio, ks. https://termipankki.fi/tepa/fi/haku/advektio  

Olisiko advektio parempi terminä? Ks. Tieteen termipankki: "Kulkeutuminen eli advektio on rajoitetusta lähteestä lähtevän ilmansaasteen kulkeutuminen ilmakehässä. Päästölähteenä voi olla esimerkiksi teollisuuslaitos, moottoriliikenne, ydinvoimala tai tulivuoren purkaus. Milloin kulkeutuminen tapahtuu kauas, satojen kilometrien päähän, puhutaan kaukokulkeutumisesta.." Tämä on ainakin selkeä käsite ja käännettävissä. 

Monessa tapauksessa (Melindassa) käytettäisiin ruotsiksi varmaan termiä spridning, tämä on jo usean termin vastineena YSOssa, lähinnä olisi nyt kyseessä varmaan tuo spridning (process), joka on leviäminen.

**Comment by YSO-kokous** [comment]
### Päätös
Etsitään soveltuvaa tarkennetta. 
Esim. transport (advektion)

**Comment by mariaforsen** [comment]
Siis miten tämä määritellään suomeksi? Suomeksi ei ole lisätty advektio ohjaustermiksi? Ei ruotsiksi voida sekoittaa tähän advektiota, jos suomeksikaan ei ole edes ohjausterminä. 
Wikipediassa:
"Kulkeutuminen on [aineen](https://fi.wikipedia.org/wiki/Aine) [liikettä](https://fi.wikipedia.org/wiki/Liike_(fysiikka)) toisen aineen mukana. [Ympäristötieteissä](https://fi.wikipedia.org/wiki/Ymp%C3%A4rist%C3%B6tiede) tutkitaan etenkin [saasteiden](https://fi.wikipedia.org/wiki/Saaste) kulkeutumista [veden](https://fi.wikipedia.org/wiki/Vesi) ja ilman mukana. Kulkeutumisessa vaikuttaa aineen oman [kemiallisen muuttumisen](https://fi.wikipedia.org/wiki/Kemiallinen_reaktio) lisäksi neljä [fysikaalista](https://fi.wikipedia.org/wiki/Fysiikka) [prosessia](https://fi.wikipedia.org/wiki/Prosessi): [[1]](https://fi.wikipedia.org/wiki/Kulkeutuminen#cite_note-1)
advektio eli [tuulen](https://fi.wikipedia.org/wiki/Tuuli) tai virtaavan veden mukana ajelehtiminen
diffuusio eli [pitoisuuserojen](https://fi.wikipedia.org/wiki/Konsentraatio) tasaantuminen
dispersio eli [sekoittuminen](https://fi.wikipedia.org/wiki/Dispersio_(kemia)) muun muassa [turbulenssin](https://fi.wikipedia.org/wiki/Turbulenssi) takia
poistuminen: ilmansaasteiden osalta märkälaskeuma [sateen](https://fi.wikipedia.org/wiki/Sade) mukana ja kuivalaskeuma, maassa virtaavan veden osalta adsorptio eli siirtyminen [maaperään](https://fi.wikipedia.org/wiki/Maaper%C3%A4)"

"spridning med ämne"? Mutta ruotsiksi kyllä käytettäisiin "spridning" fi. leviäminen...
https://termipankki.fi/tepa/fi/haku/advektion
https://sv.wikipedia.org/wiki/Advektion Mutta Nationalencyklopedin: "horisontell energitransport (jämför [konvektion](https://www-ne-se.ezproxy.vasa.abo.fi/uppslagsverk/encyklopedi/l%C3%A5ng/konvektion))."

**Comment by mirmaid** [comment]
^ Laitoinkin jo tuolla aiemmin, että suomeksi nimenomaan passiivista jonkin mukana siirtymistä. Kulkeutuminen ei mielestäni aina ole leviämistä (laajalle alueelle), vaikka voi olla sitä.

**Comment by mariaforsen** [comment]
Eli olisiko suomen kannalta ok jos laitetaan "spridning med ämne" vai onko se liian suppea > "spridning med något"? Nämä ovat kyllä ruotsinkielisten kuvailjoiden keskuudessa aika kryptisiä. Jos molemmilla kielillä olisi huomautus, joka rajaisi siihen "kulkeutumiseen jonkin mukana"  (vrt https://www.kielitoimistonsanakirja.fi/#/kulkeutua?searchMode=all )  sekin varmaan auttaisi ja parantaisi kuvailun yhteneväisyyttä.

**Comment by mirmaid** [comment]
Mietin vaan, että eikö spridning nimenomaan tarkoita leviämistä, kun taas jokin voi kulkeutua ihan tiettyyn pisteeseenkin, esim. lääkeaine kulkeutuu kasvaimeen. Olennaista on, että jokin siirtyy paikasta toiseen passiivisesti.

**Comment by mariaforsen** [comment]
Spridning ei ruotsiksi välttämättä tarkoita laajalle leviämistä, mutta siihen saa myös ruotsinkielinen sanastoryhmä ottaa kanttaa että mikä termimuoto on paras. Tärkeintä olisi nyt saada se merkityskenttä täsmäämään, ja se vaatii jonkinlaista tarkennusta (esim. jonkin mukana) ainakin ruotsiksi. Onko nyt kuitenkin niin ettei olekaan kyseessä "jonkin mukana leviämistä tai siirtymistä"? Mielestäni se näytti aika lupaavalta Melindassa (ei toki niin että tämä termi olisi ruotsiksi järkevä, mutta niin ettei ainakaan tule aivan virheellisiä tietueita). Olisiko toinen vaihtoehto sitten migrering + tarkenne, mutta Melindassa ei näytä täsmäävän. https://termipankki.fi/tepa/sv/s%C3%B6k/migrering Nykyinen tilanne on kuitenkin monikielisyyden kannalta virheellinen. 

Wikipedia: "Kulkeutuminen on aineen liikettä toisen aineen mukana. Ympäristötieteissä tutkitaan etenkin saasteiden kulkeutumista veden ja ilman mukana. Kulkeutumisessa vaikuttaa aineen oman kemiallisen muuttumisen lisäksi neljä fysikaalista prosessia: [1]
advektio eli tuulen tai virtaavan veden mukana ajelehtiminen
diffuusio eli pitoisuuserojen tasaantuminen
dispersio eli sekoittuminen muun muassa turbulenssin takia
poistuminen: ilmansaasteiden osalta märkälaskeuma sateen mukana ja kuivalaskeuma, maassa virtaavan veden osalta adsorptio eli siirtyminen maaperään"
..olisiko mahdollista että YSOssa määriteltäisiin vastaavalla tavalla?  Sv. olisi sitten spridning med ämne/något

**Comment by mirmaid** [comment]
Jos tämä olisi _spridning med något_, se tuskin kovin loogisesti erottuisi kuvailussa käsitteesta _spridning (process)_. Suomeksi _leviäminen_-käsitteessä keskeinen piirre on se, että tutkittava asia päätyy entistä laajemmalle alueelle, ei vain pisteestä A pisteeseen B. Aina välillä leviäminen on kyllä mahdollinen vaihtoehto, ja lääkkeiden tapauksessa voidaan käyttää (laajamerkityksisempää) farmakokinetiikka-asiasanaa. Toisaalta englanniksi aineistoissa on yleensä terminä transport, ei spreading. Transport on YSOssa vastine kuljetukselle, joka ei tietenkään suomeksi ole mahdollinen.

Tämä on aika tyypillinen esimerkki siitä, mitä kulkeutuminen voisi olla, ja missä leviäminen ei oikein sovi: https://melinda.kansalliskirjasto.fi/byid/013868338. Mikä olisi tässä ruotsinkielinen termi sille, mitä jätteille tapahtuu?

Entä olisiko tämäkin spridning https://melinda.kansalliskirjasto.fi/byid/006001376? Vai transport?

**Comment by mariaforsen** [comment]
Transport (tässä merkityksessä) on yleensä ruotsiksi "förflyttning i större skala (av gods eller passagerare) vanligen med hjälp av for­don, far­tyg, flyg­plan el. löpande band" mutta toki joku saattaisi käyttää sitä myös tämäntyyppisessä lauseessa missä puhutaan jätelautan liikkumisesta, yhtä hyvin varmaan kuin "spridas" (avfall sprids med havsströmmar jne.) tai ehkä "förflytta sig". Toisessa lienee ensisijaisesti spridning kyseessä (kukaan ei tahallaan varmaan kuljeta mihinkään ja kyseessä on "pieniä aineita"). 

https://stuk.fi/sv/transport-av-radioaktiva-amnen (kuljetus siis..)

**Comment by mirmaid** [comment]
Olisiko ihan mahdoton ajatus, että tämän päätermi olisi ruotsiksi _förflytta sig_, HT transport (passiv)? Mikä tahansa spridning-ratkaisu tuntuu todella ongelmalliselta, koska siinä häviää ero leviämiseen. Leviäminenhän voi yhtä lailla tapahtua jonkin (aineenkin) mukana. Ja se ero mikä tässä suomeksi on, on juuri siinä, että leviäminen = laajemmalle alueelle, kulkeutuminen = toiseen paikkaan. Jos tämä näyttää mahdottomalta Melindan kulkeutuminen-viitteiden valossa, niin sitten täytyy vaan valmistella seuraavaksi jokin poistoehdotus, en usko että jakokaan toimii, kun ei se muuta tilannetta sen suhteen, että jotkut asiat voisivat vain kulkeutua ja toiset levitä. 

_Kaukokulkeutuminen_ on myös rajattava ruotsiksi ja englanniksi niin, että se sulkee pois pitkän matkan kuljetukset.

**Comment by mariaforsen** [comment]
Ruotsiksi "förflytta sig" vie ajatukset kyllä heti ihmisten liikkumiseen, siitä näyttää hyvin harvoin, jos koskaan, olevan kyse Melindassa. 

Eli tuo kaukokulkeutuminen rajautuu saasteiden leviämiseen?  Siinä tapauksessa pitää ainakin lisätä tarkenne ruotsiksi.
https://termipankki.fi/tepa/fi/haku/kaukokulkeutuminen

**Comment by mirmaid** [comment]
^ Ei ihan välttämättä, vaan voidaan tutkia myös ainakin siitepölyn kaukokulkeutumista. Mutta kävisiköhän joku "hiukkaset" ja ohjaustermiksi saasteet?

**Comment by YSO-kokous** [comment]
**Päätös**

Käsitteen _kaukokulkeutuminen_ englanninkielistä käännöstä työstetään YSOn ylläpitoryhmässä. 

Viedään vastineen _aineiden kulkeutuminen_ käsittely AASI-kokoukseen, ja palataan tämän jälkeen ongelmakokouksessa käsitteeseen uudelleen.

**Comment by mariaforsen** [comment]
AASI kannattaa sv. ämnestransport (+huomautus) HT ämnens transport, ämnens förflyttning
"Avser hur ämnen rör sig från plats till plats, t.ex. i kroppen, i vattendrag, med luftströmmar etc." https://www.diva-portal.org/smash/get/diva2:1636112/FULLTEXT01.pdf  
https://mesh.kib.ki.se/term/D001692/biological-transport
https://www.havochvatten.se/vagledning-foreskrifter-och-lagar/vagledningar/ovriga-vagledningar/overvakningsmanualer-for-miljoovervakning/overvakningsmanualer/berakning-av-amnestransport.html

fjärrtransport (fi. kaukokulkeutuminen) > fjärrtransport (partiklar) HT långväga transport (partiklar) 


https://termipankki.fi/tepa/fi/haku/kaukokulkeutuminen
https://www.sanakirja.fi/custom/all/kaukokulkeutuminen
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a73bb36dee9eecb3a917b0681be49050&list_id=1&keyword=kaukokulkeutuminen&word=kaukokulkeutuminen
https://libris.kb.se/bib/7650516
https://libris.kb.se/hitlist?d=libris&q=%22l%c3%a5ngv%c3%a4ga+transport%22&f=simp&spell=true&hist=true&mf=&p=1
https://sv.ilmatieteenlaitos.fi/atmosfar-abc?term=Transport

**Comment by mirmaid** [comment]
^ Onhan nyt niin, että ämnestransport ei voi tarkoittaa aineiden kuljetusta, esim. https://www.finlex.fi/sv/laki/alkup/2023/20230541?

Jos ruotsiksi onnistuu näin rajaus passiiviseen, tehdäänkö suomenkieliselle päätermille jotain?

**Comment by mariaforsen** [comment]
AASI kannatti huomautusta. 
Jos termi olisi suomeksi edelleen vain kulkeutuminen, käy varmaan niin että sitä käytetään sellaisesta mihin ämnestransport **ei** sovi, esim. Melindassa: 
Vieraslajit viherrakentamisessa
Pihatot uusiksi : ruokinta ja kuivitus helpottuvat ?
Kasvikulkurit ihmisen jalanjäljissä
Venäjältä tuotavan havupuun mukana kulkeutuvat kovakuoriaiset 
Satamien ympäristö on kovilla jatkuvasti kasvavan meriliikenteen takia ?
Siperianmäntykehrääjä voi kulkeutua länteen
Paarlastikasvit hukkumaisillaan 
Invasive insects in Europe : the role of climate change and global trade
Tulokkaita joka lähtöön
Merenkiviä ja muita rantojen aarteita
Toivottuja tulokaslajeja : purjelaivakauden historia kukkii Reposaaressa
Kansoittavatko muukalaiset Itämeren?
Paarlastikasvit hukkumaisillaan

**Comment by YSO-kokous** [comment]
PÄÄTÖS:
Lisätään sulkutarkenne: kulkeutuminen (aineet)
