### ISSUE TITLE
kieltäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8607]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kieltäytyminen](http://www.yso.fi/onto/ysa/Y116090) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Voidaanko määritellä? 

#### Perustelut ehdotukselle   

Ruotsinkielinen termi riippuu merkityksestä. Vägran on vahvasti kieltäytyminen johonkin käskyyn tms. Ei sovi esim. merkityksestä "luopua, pidättyä (nautinnosta tms.), hylätä jk." /Kielitoimiston sanakirja. Ei kyllä myöskään yleiseen "ei-sanomiseen".

**Comment by mirmaid** [comment]
Käytetty Melindassa 91 kertaa. Usein ei tunnu kovin tarpeelliselta tai osuvalta - esim. paljon käytetty _koulunkäynti & kieltäytyminen_ ei ole hakijaa ajatellen kovin intuitiivinen yhdistelmä, ennemmin _koulupudokkaat, poissaolot, opintojen keskeyttäminen_. Sellaisissa tilanteissa, joissa käsitellään ihmisen oikeutta (tai oikeaa tapaa) kieltäytyä jostakin toiminnasta, vastuusta tai esim. hoidosta termi kuitenkin puoltaisi paikkaansa, mutta tarkenteen keksiminen on kyllä hankalaa. 

Esim.
https://melinda.kansalliskirjasto.fi/byid/013656298
https://melinda.kansalliskirjasto.fi/byid/013921567
https://melinda.kansalliskirjasto.fi/byid/006454944
https://melinda.kansalliskirjasto.fi/byid/011437337
https://melinda.kansalliskirjasto.fi/byid/009374340
https://melinda.kansalliskirjasto.fi/byid/013493507
https://melinda.kansalliskirjasto.fi/byid/013469710

**Comment by fantsby-m** [comment]
"Hoidosta kieltäytyminen" voisi hyvinkin tulla omana terminään joskus tarpeelliseksi, esim. Google-haussa 11500 tulosta. (On MeSHissä)

**Comment by YSO-kokous** [comment]
Tehdään ruotsiksi yhdistelmätermi.
