### ISSUE TITLE
ennenaikainen siemensyöksy

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8608]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ennenaikainen siemensyöksy 

#### Ehdotettu termi englanniksi   

Premature Ejaculation 

#### Ehdotettu termi ruotsiksi   

tidig sädesuttömning 

#### Ehdotettu yläkäsite YSOssa (LT)   

[seksuaaliset häiriöt](http://www.yso.fi/onto/yso/p8254) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D061686> 
LCSH : <http://id.loc.gov/authorities/subjects/sh88007626> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Diagnosis, etiology, and psychobehavioral treatment of premature ejaculation 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ennenaikainen siemensyöksy](http://finto.fi/yse/fi/page/Y508608)

**Comment by mariaforsen** [comment]
Sv. tidig sädesuttömning /mesh ET för tidig utlösning /wp, tidig utlösning /rfsu, prematur ejakulation
