### ISSUE TITLE
yhdysvaltalaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8609]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhdysvaltalaiset](http://www.yso.fi/onto/ysa/Y196894) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määrittely/tarkennus suhteessa termiin amerikkalaiset 

#### Perustelut ehdotukselle   

Vrt. ruotsi ja englanti -viittaako todella yhdysvaltain kansalaisiin? Ks. myös Kielitoimiston s.k. (on ainakin osittain päällekkäinen amerikkalaisten kanssa.

**Comment by jtuohini** [comment]
LT–ST-suhde!

**Comment by mariaforsen** [comment]
Kielitoimiston sanakirja: amerikkalainen: "Amerikasta, us. vars. Yhdysvalloista peräisin oleva"

**Comment by tpalonen** [comment]
Suoraan sanoen vähän vaikea nähdä mihin niin laajamerkityksistä (=epämääräistä) käsitettä kuin amerikkalaiset (eli pohjos-amerikkalaiset ja etelä-amerikkalaiset) voi sanastossa tarvita. Yleiskielessä viittaa yleensä yhdysvaltalaisiin ja myös Melinda-kuvailussa käytetty paljon merkityksessä yhdysvaltalaiset.

**Comment by ilona-x** [comment]
YSOssa näyttää olevan myös amerikkalaisuus http://www.yso.fi/onto/yso/p10617

**Comment by mirmaid** [comment]
Jos tässä ehdotetaan oikeasti _amerikkalaiset/amerikkalaisuus_ -käsitteiden poistoa, se vaatisi perusteellista Melindan penkomista. Voisin kuvitella, että tarvetta on joskus myös yleisemmille termeille, vaikka ei kerralla viitattaisikaan maanosien kaikkiin valtioihin. Sanastossa on myös _eurooppalaiset, eurooppalaisuus, afrikkalaiset, afrikkalaisuus, aasialaiset_. Sille, että amerikkalainen meillä arkipuheessa tyypillisesti viittaa yhdysvaltalaisiin ei oikein voi mitään. Toki _pohjois-amerikkalaiset_ jne. on mahdollinen pohdittava ratkaisu.

**Comment by YSO-kokous** [comment]
Tehdään seuraavat muutokset:
amerikkalaiset (yhdysvaltalaiset) KÄYTÄ yhdysvaltalaiset
yhdysvaltalaiset LT pohjoisamerikkalaiset

Keskustelu: Yhdysvaltalaisten nähtiin viittaavan Yhdysvalloissa asuviin henkilöihin.

**Comment by jarmosaarikko** [comment]
pohjoisamerikkalaiset RT amerikanruotsalaiset, 
voisiko samalla lisätä RT amerikansuomalaiset ?

**Comment by mirmaid** [comment]
Hierarkia kaipaa tarkistusta laajemmin:
amerikanruotsalaiset, amerikansuomalaiset, kanadansuomalaiset, argentiinansuomalaiset, brasiliansuomalaiset käsiteltävä johdonmukaisesti. Vrt. myös amerikankuubalaiset, amerikanaasialaiset

**Comment by mirmaid** [comment]
Nyt siis 

- kanadansuomalaiset, argentiinansuomalaiset, brasiliansuomalaiset YK ulkosuomalaiset
- amerikankuubalaiset, amerikanaasialaiset YK amerikkalaiset
- amerikansuomalaiset YK ulkosuomalaiset, amerikkalaiset
- amerikanruotsalaiset YK väestöryhmään liittyvä rooli

**Comment by mirmaid** [comment]
Pitäisikö tehdä:

- kanadansuomalaiset YK ulkosuomalaiset ja kanadalaiset? (vastaavat samoin)

**Comment by mirmaid** [comment]
_Amerikan_-alkuiset: katsotaanko Amerikan viittaavan tässä a) Yhdysvaltoihin, b) Pohjois-Amerikkaan, c) molempiin maanosiin? Eli ovatko kanadansuomalaiset ja/tai argentiinansuomalaiset amerikansuomalaisia?

**Comment by mariaforsen** [comment]
Ruotsiksi tämänkaltaiset -suomalaiset yms. on yleensä tehty  muodossa "finländare i x-land", amerikansuomalaisten kohdalla on kuitenkin tehty muotoon "amerikafinländare", mutta ruotsiksi "amerikansk" tässä yhteydessä viittaa ensisijaisesti yhdysvaltalaiseen. Ks. esim. https://sv.wikipedia.org/wiki/Svenskamerikan ja https://en.wikipedia.org/wiki/Americans 
**"Americans are the citizens and nationals of the United States of America."** Vrt. myös https://id.loc.gov/authorities/subjects/sh85004432.html

Hierarkian osalta kannatan siis periaatetta amerikansuomalaiset YK ulkosuomalaiset ja YK yhdysvaltalaiset. 
Ja huom. yhdysvaltalaiset=invånare i Förenta staterna, aikaisemman keskustelun mukaisesti (eli riippumatta henkilön taustasta, "invånare" ei siihen ota kantaa).

**Comment by jarmosaarikko** [comment]
Melindassa:
- 1320 | amerikkalaiset (yso/fin) - [Asteri-termitietue]
- 59 | yhdysvaltalaiset (yso/fin) - [Asteri-termitietue]

Suurin osa amerikkalaiset -kuvailusta viitannee yhdysvaltalaisiin, sillä he ovat käyttäneet yli 200 vuotta itsestään termiä "Americans", kun heille "United States" ja "America" ovat käytännössä synonyymejä.

Wikidatassa   yhdysvaltalaiset KT amerikkalaiset   https://www.wikidata.org/wiki/Q846570
- **Ehdotan**, että YSOssa tehdään samoin.
- Eri maista peräisin oleva yhdysvaltalaiset voinee jättää muuttamatta eli amerikansuomalaiset eikä yhdysvaltainsuomalaiset.
- WIkipedia: [American](https://en.wikipedia.org/wiki/American_(word)#Other_languages) - artikkeli esittelee läpikotaisin amerikkalaiset-termin käyttöä eri kielissä.

LCSH:n määritelmä on mielenkiintoinen:  [Americans](http://id.loc.gov/authorities/subjects/sh85004432)
- ovat ulkoamerikkalaisia / ulkoyhdysvaltalaisia ja termiä käytetään vain ketjuissa.
- _Here are entered works on citizens of the United States not currently residing within the borders of the United States. The heading is **only used with local subdivision** or with local subdivision in combination with subdivisions used under names of ethnic groups._ 
- _Works on topics relating to Americans living within the borders of the United States are entered under the appropriate specific heading, e.g. [Anthropometry--United States; United States--Social conditions; National characteristics, American.]_

LCSH  [Latin Americans](http://id.loc.gov/authorities/subjects/sh85074933)
- _Here are entered works on citizens of Latin American countries. Works on citizens of Latin American countries in the United States are entered under [Latin Americans--United States.] Works on United States citizens of Latin American descent are entered under [**Hispanic Americans**.]_

LCSH [South Americans](http://id.loc.gov/authorities/subjects/sh2004003253)
- vaikea nähdä eroa edelliseen

LCSH [South American Americans](http://id.loc.gov/authorities/subjects/sh2004003254)
- nämä ovat Etelä-Amerikasta tulleita yhdysvaltalaisia

Molempiin Amerikoihin ([the Americas](https://en.wikipedia.org/wiki/Americas)) viittaa termi "Pan-American", mutta sitä ei ole sanastossa

**Comment by AuHo22** [comment]
Latinalaisen Amerikan ja Etelä-Amerikan ero on kulttuuris-maantieteellinen, edelliseen kuuluu esimerkiksi Meksiko (maantieteellisesti Pohjois-Amerikkaa), jälkimmäinen on maanosa, joka ei myöskään sisällä Keski-Amerikkaa.

https://fi.wikipedia.org/wiki/Latinalainen_Amerikka
https://fi.wikipedia.org/wiki/Etel%C3%A4-Amerikka

**Comment by mirmaid** [comment]
Melindassa on 277 viitettä, joissa termit _amerikansuomalaiset_ ja _Kanada_, n. 60 näistä on uudempia kuin termi _kanadansuomalaiset_ sanastossa.

**Comment by mirmaid** [comment]
Tulkitsenko nyt keskustelua oikein, että hierarkian nähtäisiin kuitenkin olevan lähimpänä totuutta, jos tulkitaan "amerikan-" olevan tässä = "yhdysvaltain-"? Vaikka varsinkin kanadansuomalaisten nähdäänkin aika usein sisältyvän amerikansuomalaisiin?

**Comment by mirmaid** [comment]
Voisi varmaan lisätä amerikansuomalaiset (Kanada) KÄ kanadansuomalaiset?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8609#issuecomment-742494056 - tästä päätöksestä on nyt vajaa vuosi, joten en avaisi tätä keskustelua tässä vaiheessa uudestaan.

**Comment by YSO-kokous** [comment]
### Päätökset
Lisätään ohjaustermi amerikansuomalaiset (Kanada) KÄYTÄ kanadansuomalaiset
Korjataan hierarkiaa niin, että amerikan- alkuiset termit viittaavat Yhdysvaltoihin
