### ISSUE TITLE
skitsoaffektiivinen häiriö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8610]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

skitsoaffektiivinen häiriö 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/306425 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [skitsoaffektiivinen häiriö](http://finto.fi/yse/fi/page/Y508610)

**Comment by mirmaid** [comment]
https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00487
https://fi.wikipedia.org/wiki/Skitsoaffektiivinen_h%C3%A4iri%C3%B6

**Comment by mariaforsen** [comment]
Sv. schizoaffektivt syndrom ET schizoaffektiv störning

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

FinMeSH-käsite [psykoottiset mielialahäiriöt](http://www.yso.fi/onto/mesh/D000341) tarkoittanee samaa sairautta.

**Comment by FinMeSHienPaimentaja** [comment]
> https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00487
> https://fi.wikipedia.org/wiki/Skitsoaffektiivinen_h%C3%A4iri%C3%B6

Näyttää siis olevan ICD-10:ssä ja DSM V:ssä.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
