### ISSUE TITLE
kansalaisyhteiskunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8611]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansalaisyhteiskunta](http://www.yso.fi/onto/ysa/Y107547) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pitäisikö tämän olla englanniksi civil society? 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Civil_society
https://en.wikipedia.org/wiki/Civic_society 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by tpalonen** [comment]
Muutettu
