### ISSUE TITLE
rajatieto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8612]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rajatieto 

#### Ehdotettu termi ruotsiksi   

Gränskunskap. Paranormala fenomen 

#### Ehdotettu termi englanniksi   

Fringe Knowledge. Paranormal phenomena 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Rajatieto 

#### Tarkoitusta täsmentävä selite   

Tähän ja alaluokkiin teokset, jotka koskevat tieteelle selittämättömiä paranormaaleja ilmiöitä sekä tapahtumia, länsimaista esoteriaa ja esoteerisia oppeja, okkultismia, ufoja ja parapsykologiaa sekä rajatietoon kohdistuva skeptismi. Tässä alaluokassa ei ole merkittäviä esoteerisia liikkeitä kuten teosofiaa ja ruusuristiläisyyttä. 

#### Perustelut ehdotukselle   

Jostain syystä muutosehdotuslomakkeeni ei ilmeisesti saapunut perille, joten yritän muotoilla ehdotukseni tätä kautta:

Luokka 15 on suomeksi rajatieto. Tämä kuvaa kattavasti siihen luokitettua kirjallisuutta. Luokka 15 on kuitenkin ruotsiksi paranormala fenomen ja englanniksi paranormal phenomena. Yläkäsitteenä on siten "philosophy. psychology. paranormal phenomena" sekä sama ruotsiksi. Tässä käytetty termi sivuuttaa esimerkiksi luokkaan kuuluvan laajemman esoterian ja uushenkisyyden. Myös luokkaan kuuluva ufokirjallisuus käsittelee monesti ufoja (tunnistamattomia lentäviä esineitä) muuna kuin paranormaalina ilmiönä. Luokan englannin- ja ruotsinkielinen kuvaus vaatisikin tästä syystä täydennystä.

Vuonna 2018 Tommy Ramstedt rajatietoskeneä koskevassa väitöskirjassaan lanseerasi ruotsinkielisen rinnakkaistermin "Gränskunskap" sekä englanninkielisen rinnakkaistermin "Fringe Knowledge". Gränskunskap-termiä on alkanut epävirallisesti käyttämään myös Rajatiedon Yhteistyö ry, jota perustettaessa termi "rajatieto" alkuaan lanseerattiin suomenkieleen. Gränskunskap-termi on vastaanotettu myönteisesti tiedotusvälineissä ja muun muassa Yle Svenska on käyttänyt tätä tuotannossaan. "Fringe Knowledge" termi on puolestaan käytössä Rajatiedon Yhteistyö ry:n ylläpitämän erikoiskirjaston englanninkielisessä nimessä "Library for Fringe Knowledge". Rajatieto-termin ruotsin- ja englanninkieliset rinnakkaistermit "Gränskunskap" ja "Fringe knowledge" ovat toki vielä suhteellisen tuntemattomia, mutta niin oli "rajatietokin" kun se tuli kirjastoluokituksen osaksi.

Näin ollen luokan 15 kuvauksen täydentäminen on paitsi perusteltua, myös mahdollista, koska tällainen rinnakkaistermi on nyt olemassa ja yleisön käytössä.

Tästä syystä ehdotan luokan 15 ruotsinkieliseksi kuvaukseksi "Gränskunskap. Paranormala fenomen". Sekä yläkäsitteeksi "Filosofi. Psykologi, Gränskunskap". Vastaavasti ehdotan luokan 15 englanninkieliseksi kuvaukseksi "Fringe knowledge. Paranormal phenomena". Sekä yläkäsitteeksi "Philosophy. Psychology. Fringe knowledge"

Jani Lassila
Rajatiedon erikoiskirjasto
044-9792544
jani.lassila@rajatieto.fi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://finto.fi/ykl/fi/page/?clang=sv&uri=15 

**Ehdottajan organisaatio:** Rajatiedon erikoiskirjasto, Rajatiedon Yhteistyö ry **Termiehdotus Fintossa:** [rajatieto](http://finto.fi/yse/fi/page/Y508612)

**Comment by mirmaid** [comment]
Ehdotus koskee YKL-luokitusta.

**Comment by ilona-x** [comment]
välitetty YKL-ryhmän käsittelyyn
