### ISSUE TITLE
litografia (mikrovalmistus)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8613]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

litografia (mikrovalmistus) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/308673 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [litografia (mikrovalmistus)](http://finto.fi/yse/fi/page/Y508613)

**Comment by tpalonen** [comment]
Tämä näyttää aika laajalta tekniikan kentältä ja useita termejä esiintyy. Englanninkielisessä Wikipediassa mainitaan microlithography ja nanolithography. Suomenkielistä nanolitografia-termiä on käytetty parissa yhteydessä Googlen mukaan. Mikrolitografia-termillä en löytänyt suomenkielistä käyttöä. Tämän kaupallisesti kehittyneimmäksi muodoksi mainitaan photolithography, ja muita metodeja ovat electron beam lithography, maskless lithography, nanoimprint lithography, interference lithography, X-ray lithography, extreme ultraviolet lithography, magnetolithography ja scanning probe lithography. Photolithographysta käytetään myös termejä optical lithography ja UV lithography. Suomeksi photolithography-termin vastine Wikipediassa on optinen litografia, mutta Googlen mukaan myös muotoa fotolitografia on käytetty jokunen kerta.
https://en.wikipedia.org/wiki/Lithography#Microlithography_and_nanolithography
https://en.wikipedia.org/wiki/Photolithography
https://fi.wikipedia.org/wiki/Optinen_litografia

**Comment by tpalonen** [comment]
Jos tällainen otetaan sanastoon niin nykyinen litografia-käsite tarvinnee sulkutarkenteen?

**Comment by ilona-x** [comment]
optinen litografia (mikrotekniikka) otettiin sanastoon aiemmin tänä vuonna. 

Tässä ehdotuksessa esimerkkiaineistona olevan väitöskirjan kuvailuun riittäisi varmastikin **mikrovalmistus**, josta ehdotus: https://github.com/Finto-ehdotus/YSE/issues/7884

Lainauksia väitöskirjan tiivistelmästä:
"Tässä työssä kehitettiin uusia mikrovalmistusmenetelmiä" 
"Työn ensimmäisessä osassa kehitettiin uusi yksivaiheinen litografinen menetelmä"

**Comment by mirmaid** [comment]
^ Sikäli kuin se hyväksytään. Litografiaa on jo käytetty myös mikrovalmistuksesta, joten se tarvitsee joka tapauksessa tarkenteen, jos merkitystä halutaan rajata. Sama koskee myös etsausta. Toki on mahdollista myös ajatella nämä saman(kaltaisen) tekniikan käyttösovelluksina, mutta jos tämä tuntuu ongelmalliselta, jako olisi hyvä tehdä mahdollisimman varhaisessa vaiheessa.

**Comment by YSO-kokous** [comment]
Jaetaan käsitteet ja etsitään soveltuvat tarkenteet

**Comment by mirmaid** [comment]
Tarkenteet etsaukselle ja litografialla taiteen ja painomenetelmän osalta vielä päättämättä, korjataan ensin pois mikrovalmistus. Pohdittu mm. etsaus (grafiikka), mutta erit. litografian osalta haastavaa, jotta mikrovalmistus varmasti rajautuu pois ja toisaalta katetaan muut käyttökohteet.

**Comment by mirmaid** [comment]
Korjattu pois mikrovalmistus.

https://melinda.kansalliskirjasto.fi/byid/005890087 (?)

**Comment by mirmaid** [comment]
Nyt siis ratkaistava _litografia_-käsitteen tarkenne, jonka pitää kattaa Melindan nykyiset käyttötapaukset, mutta sulkea pois mikrovalmistus.

**Comment by mirmaid** [comment]
Esim.
Turun kivipainatuksia ja kivipainajia 1850-luvulla
Käyttögrafiikan tekniikasta taiteen välineeksi
Topografikarttojen painaminen kivipaino- eli litografiamenetelmällä

Jne. Ks. Melinda

**Comment by mirmaid** [comment]
En kyllä keksi parempaa kuin litografia (painomenetelmät) KT litografia (grafiikka), litografia (taide) ja ehkä etsaus (grafiikka). Olen aika varma, että ryhmässä moni tuntee tätä paremmin kuin minä. En ole ihan varma poissulkeeko litografia (painomenetelmät) mikrovalmistuksen, vai voisiko joku nähdä senkin painomenetelmänä, mutta nyt ei mitenkään päin irtoa muuta ehdotusta.

**Comment by mariaforsen** [comment]
Kannatan muotoja: litografia (grafiikka) ja etsaus (grafiikka), vastaava olisi mielestäni selkein vaihtoehto ruotsiksi. Litografia "taiteellisena menetelmänä" ei välttämättä nähdä suoranaisesti "painomenetelmänä". Ja olihan tämä aikaisemmin silloin kun käsite oli jaettuna: litografia (taidelajit) ja litografia (painomenetelmät) https://onki.fi/fi/browser/search?q=litografia&lang=fi&os=yso Eli grafiikka olisi ymmärtääkseni sopivan neutraali.

**Comment by mirmaid** [comment]
^ Mutta käykö sitten noihin mainitsemiini esimerkkeihin: 
_Turun kivipainatuksia ja kivipainajia 1850-luvulla
Käyttögrafiikan tekniikasta taiteen välineeksi
Topografikarttojen painaminen kivipaino- eli litografiamenetelmällä_

**Comment by mariaforsen** [comment]
Kun grafiikka on "vars. kuvataiteelliset menetelmät, joissa kaivertamalla, syövyttämällä tms. tehty kuva monistetaan painamalla; siten tehdyt kuvat t. vedokset; graafinen taide, taidegrafiikka, piirrostaide" (Kielitoimiston sk.) niin ymmärtääkseni sopii?

**Comment by YSO-kokous** [comment]
**PÄÄTÖS**
Lisätään sulkutarkenteet:
litografia (grafiikka)
etsaus (grafiikka).
