### ISSUE TITLE
ligaasit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8614]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ligaasit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305328 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ligaasit](http://finto.fi/yse/fi/page/Y508614)

**Comment by mirmaid** [comment]
FinMeSH: http://www.yso.fi/onto/mesh/D008025

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ligaasit

Kerran Melindassa yksikössä, 2 kertaa FinMeSH-terminä.

**Comment by mariaforsen** [comment]
Sv. ligaser
