### ISSUE TITLE
kondriitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8616]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kondriitit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/300084 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kondriitit](http://finto.fi/yse/fi/page/Y508616)

**Comment by mariaforsen** [comment]
Sv. kondriter (meteoriter)

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

LCSH: Chondrites (Meteorites) http://id.loc.gov/authorities/subjects/sh85024675

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
