### ISSUE TITLE
korona (tähdet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8617]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

korona (tähdet) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305145 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [korona (tähdet)](http://finto.fi/yse/fi/page/Y508617)

**Comment by mariaforsen** [comment]
Sv. korona (stjärnor)

**Comment by mirmaid** [comment]
5 viitettä Melindassa.

LCSH: Stars--Corona http://id.loc.gov/authorities/subjects/sh85127425

**Comment by tpalonen** [comment]
Kannatan monikkomuotoa _koronat (tähdet/tähtitiede)_. Kaikilla tähdillä on tällainen.

Huom! Varsinkin englannin osalta hyvä huomioida, että erään tähtikuvion nimi on Corona borealis, suomeksi Pohjan kruunu, ja siihen kuuluvat tähdet ovat muotoa Alpha Coronae Borealis, Beta Coronae Borealis jne. https://en.wikipedia.org/wiki/Corona_Borealis

**Comment by ilona-x** [comment]
LCSHssa myös: Sun--Corona http://id.loc.gov/authorities/subjects/sh85130465

**Comment by ilona-x** [comment]
GEOssa koronat http://www.yso.fi/onto/gtk/GTK2015ID1752

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon, mutta tutkitaan vielä yksikkö-monikkomuodon johdonmukaisuus tämän tyyppisissä käsitteissä (vrt. heliosfääri otettiin yksikössä).

**Comment by jarmosaarikko** [comment]
MAOssa on "[korona](http://www.yso.fi/onto/mao/p4778)", jonka yläkäsite on [pelit](http://www.yso.fi/onto/yso/p6062).   
KOKO-sotkujen välttämiseksi pitäisikö YSOssa olla myös "**korona (pelit)**"?
