### ISSUE TITLE
fiktiiviset henkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8618]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fiktiiviset henkilöt](http://www.yso.fi/onto/ysa/Y107395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan asiasana muotoon "fiktiiviset hahmot" ja vaihdetaan nykyinen KT-muodoksi 

#### Perustelut ehdotukselle   

RDA:ssa käytetään sanamuotoa "fiktiivinen hahmo", ja sana "hahmo" kattaa helpommin myös muut fiktiiviset yksilöt kuin puhtaasti ihmishahmot. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ksornova** [comment]
kannatan!

**Comment by mariaforsen** [comment]
Sv. fiktiva gestalter ET fiktiva figurer

**Comment by mirmaid** [comment]
6 viitettä Melindassa. Näistä angry birds -hahmoihin _fiktiiviset henkilöt_ ei sovi.

Fiktiiviset henkilöt käytetty 2251 kertaa.

**Comment by mirmaid** [comment]
Tämä keskustelu voisi kiinnostaa myös KAUNO-ryhmää ja fiktioaineistoryhmää?

**Comment by YSO-kokous** [comment]
YSO-kokous puoltaa muutosehdotusta, mutta tähän kaivataan vielä KAUNO-ryhmän kantaa.

**Comment by ghost** [comment]
KAUNO-ryhmä kannattaa muutosehdotusta.

**Comment by YSO-kokous** [comment]
Muutetaan päätermiksi fiktiiviset hahmot KT fiktiiviset henkilöt
