### ISSUE TITLE
vaikuttajamarkkinointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8619]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaikuttajamarkkinointi 

#### Ehdotettu termi englanniksi   

Influencer marketing 

#### Ehdotettu termi ruotsiksi   

influens marknadsföring 

#### Ehdotettu yläkäsite YSOssa (LT)   

[markkinointi](http://www.yso.fi/onto/yso/p5878) 

#### Assosiatiiviset (RT)   

[viraalimarkkinointi](http://www.yso.fi/onto/yso/p24254) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Vaikuttajamarkkinointi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The Gray Zone in Marketing – Consumer Responses to Influencer Marketing http://urn.fi/URN:ISBN:978-952-12-3831-4 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vaikuttajamarkkinointi](http://finto.fi/yse/fi/page/Y508619)

**Comment by mariaforsen** [comment]
Sv. influencermarknadsföring ET influensermarknadsföring, influensmarknadsföring, influerarmarknadsföring

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon.
