### ISSUE TITLE
tulenjohto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8620]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tulenjohto 

#### Vaihtoehtoiset termit ja ilmaisut   

tulenjohto (toiminta) / tulenjohto (organisaatiot) SOTO 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Tulenjohtolennot : tykistölennot Rukajärven suunnalla 1942-1944 / Hannu Siivonen 

#### Tarkoitusta täsmentävä selite   

Wikipedia: Tulenjohto on tykistön ammunnan organisoimiseksi tapahtuvaa käskytystoimintaa, jolla määrätään tykkiyksiköiden ammunnan kohteet ja se kuinka paljon tulivoimaa kukin tykki käyttää. 

#### Perustelut ehdotukselle   

Teoksesta: Kirjassa on katsaus Ilmavoimien lentoyksiköiden ja tykistön yhteistoimintaan sekä lentotiedustelun että lentotähysteisen tulenjohdon kehittymiseen Suomessa. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [tulenjohto](http://finto.fi/yse/fi/page/Y508620)

**Comment by mariaforsen** [comment]
Sv. eldledning https://sv.wikipedia.org/wiki/Eldledning

**Comment by mirmaid** [comment]
126 viitettä Melindassa.

**Comment by tpalonen** [comment]
Ohjaustermiksi tulenjohtaminen?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon tulenjohto ja ohjaustermiksi tulenjohtaminen.
