### ISSUE TITLE
Viekijärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8622]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Viekijärvi](http://www.yso.fi/onto/ysa/Y106018) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan huomautus 

#### Perustelut ehdotukselle   

Huomautus: Järvi ja Kuopion hiippakuntaan kuuluva seurakunta Lieksassa (aikaisemmin Pielisjärvellä)
On päätettävä mihin tämä viittaa, ei voi olla sekä järvi että seurakunta.

**Comment by mirmaid** [comment]
Huomautus poistettu, YSO-paikoissa ei ole seurakuntia.

**Comment by mirmaid** [comment]
Viitteistä 4/5 käsittelee Viekijärveä kuitenkin muussa merkityksessä kuin järvenä. Ks. Alastarolla...

**Comment by ilona-x** [comment]
Viekijärven kirkko näyttää sijaitsevan Viekin kylässä 🤔 Vieki löytyy YSO-paikoista http://www.yso.fi/onto/yso/p124852

https://fi.wikipedia.org/wiki/Viekij%C3%A4rven_kirkko.
https://fi.wikipedia.org/wiki/Vieki

**Comment by mirmaid** [comment]
^^ Postitoimipaikka

**Comment by ilona-x** [comment]
https://kylat.fi/p/157/vieki
**Vieki**

Kylän yhdistykset
Viekijärven Riistamiehet ry,
Viekin Erä ry
Viekin reserviläiset ry
Viekin Vapaaehtoinen Palokunta ry
Koivurinteen Erä ry
Keskusta Viekin paikallisyhdistys ry
Viekin Nuorisoseura ry

**Comment by mirmaid** [comment]
Viekijärvi (järvi), poistetaan RT-suhde Pielisjärveen. Viitteisiin Vieki tai Lieksa.
