### ISSUE TITLE
intiaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8623]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[intiaanit](http://www.yso.fi/onto/ysa/Y95568) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään suhde asiasanaan "alkuperäiskansat" 

#### Perustelut ehdotukselle   

Intiaanit (Kanadassa nimityksenä "first nations") ovat monelta osin alkuperäisväestöä, joten seikan tulisi näkyä asiasanaston sanasuhteissa. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätään RT-suhde: intiaanit, adivasit, aboriginaalit, saamelaiset & eng. wikipedian listaussivujen mukaiset.

**Comment by mirmaid** [comment]
Mitähän listaussivuja tarkoitettiin? Näitä on wikipediassa alasivuineen lukemattomia.

**Comment by mirmaid** [comment]
Alkuperäiskansojen johdonmukainen kartoittaminen todettiin mahdottomaksi nykyisessä resurssitilanteessa. Ei lisätä yksittäisiä sattumanvaraisia RT-suhteita.
