### ISSUE TITLE
Leppävesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8625]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Leppävesi](http://www.yso.fi/onto/ysa/Y110675) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne ja muutetaan huomautus 

#### Perustelut ehdotukselle   

Sanastossa myös Leppävesi (Laukaa) -vaatinee myös tarkennusta

**Comment by mirmaid** [comment]
Leppävesi (Laukaa) -käsitteelle riittäisi periaatteessa tarkenne (Laukaa), koska ainakin Paikannimirekisteri sijoittaa järven Jyväskylään. Toisaalta kun järvi kuitenkin yltää myös Laukaan alueelle, sekaantumisen riski on, mutta mikä tulisi paikkatyypiksi tarkenteeseen, Paikannimirekisteri: Kaupunkialue tai taajama.

**Comment by mirmaid** [comment]
Taajama? https://fi.wikipedia.org/wiki/Lepp%C3%A4vesi - ei käytetty suomalaisista paikoista.

**Comment by mirmaid** [comment]
Leppävesi (Laukaa : kylä)
