### ISSUE TITLE
Äkäslompolo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8626]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Äkäslompolo](http://www.yso.fi/onto/ysa/Y200570) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Äkäslompolo (Kolari). Sekä järvi että kylä sijaitsevat Kolarissa, joten tarkennusta tarvitaan.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8625

**Comment by mirmaid** [comment]
Äkäslompolo (järvi)
Äkäslompolo (Kolari : kylä)
