### ISSUE TITLE
Iisvesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8628]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Iisvesi](http://www.yso.fi/onto/ysa/Y118601) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa on myös Iisvesi (Suonenjoki)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8625

Vain yksi IIsvesi (järvi), jonka Paikkatietoalusta sijoittaa Tervoon. Iisvesi (Suonenjoki) on taajama.

**Comment by mariaforsen** [comment]
Ruotsiksi lisätty toisellekin tarkenne, eli Iisvesi (sjö).

**Comment by mirmaid** [comment]
Iisvesi (järvi)
Iisvesi (Suonenjoki : kaupunginosa)
