### ISSUE TITLE
Topjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8633]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Topjoki](http://www.yso.fi/onto/ysa/Y118920) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa on myös Topjoki (Salo)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Toppjoki

**Comment by mirmaid** [comment]
Paikkatietoalustalla vain joki ja talo. Asutusnimihakemistossa kylä, "Topjoki". Google Mapsissa joki on Topjoki, tien nimi on Toppjoenkyläntie ja Toppjoki-Krinttiläntie.

**Comment by ilona-x** [comment]
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=Topjoki

**Comment by mirmaid** [comment]
Topjoki (Salo : kylä) KT Toppjoki (Salo : kylä)
Topjoki (joki)
