### ISSUE TITLE
Virolahti -- Ravijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8634]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Virolahti -- Ravijoki](http://www.yso.fi/onto/ysa/Y108232) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan 

#### Perustelut ehdotukselle   

YSO-paikat: Ravijoki (Virolahti) 
Virolahdella on sekä vesistö että kylä, jolla on sama nimi.

**Comment by mirmaid** [comment]
Tarkennetta muutettu, käytetty vain kylästä.
