### ISSUE TITLE
Kuusamo -- Liikasenvaara

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8635]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuusamo -- Liikasenvaara](http://www.yso.fi/onto/ysa/Y193035) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan huomautus (ja mahdollisesti jaetaan?) 

#### Perustelut ehdotukselle   

YSO-paikat: Liikasenvaara (Kuusamo)

**Comment by mirmaid** [comment]
Kuusamossa on kaksi Liikasenvaara-nimistä kohoumaa. Aineisto käsittelee lähinnä kai kylää (joistakin vähän vaikea sanoa).

**Comment by ilona-x** [comment]
Riittäisikö tässä pelkkä kylä. Toinen kohouma näyttää sijaitsevan lähes samoissa koordinaateissa kuin kylä, ja toinen kohouma on ihan eri suunnalla Kuusamoa (etäisyys näiden kahden Liikasenvaaran välillä n. 80 km).

**Comment by mirmaid** [comment]
Liikasenvaara (Kuusamo : kylä)
