### ISSUE TITLE
Viitasaari -- Huopanankoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8636]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Viitasaari -- Huopanankoski](http://www.yso.fi/onto/ysa/Y108254) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

YSO-paikat: Huopanankoski (Viitasaari)
https://fi.wikipedia.org/wiki/Huopanankoski 

#### Ehdotettu muutos   

Tarkennetaan

**Comment by mirmaid** [comment]
Käytetty nimenomaan koskesta, jota Paikkatietoalusta ei tunne.

**Comment by mirmaid** [comment]
Huom. sanastossa myös Huopana.

https://fi.wikipedia.org/wiki/Huopanankoski

**Comment by mirmaid** [comment]
Huopanankoski (koski) KT Huopana (koski)
Huopanankoski (Viitasaari : kylä)
Huopana (Viitasaari : Kylä)

**Comment by mirmaid** [comment]
Onkohan Huopana ja Huopanankoski varmasti eri kyliä? Vrt. wikipedia.

https://fi.wikipedia.org/wiki/Huopanankoski

**Comment by mirmaid** [comment]
Annetaan olla erillään.
