### ISSUE TITLE
Tammerkoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8637]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Tammerkoski](http://www.yso.fi/onto/ysa/Y217601) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa on myös Tammerkoski (Tampere)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Tammerkoski_(t%C3%A4smennyssivu)

**Comment by nikopartanen** [comment]
[Tampere -- Tammerkoskessa](https://finto.fi/ysa/fi/page/Y179464) on huomautus:

> Tammerkoski on kaupunginosa Tampereella. Tarkoitettaessa koskea Tampereella käytä muotoa Tammerkoski

**Comment by mirmaid** [comment]
Tammerkoski (koski)
Tammerkoski (Tampere : kaupunginosa)
