### ISSUE TITLE
Porvoo -- Pellinki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8638]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Porvoo -- Pellinki](http://www.yso.fi/onto/ysa/Y176119) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

YSO-paikat: Pellinki (Porvoo)
Ei voi varmaan viitata sekä "saaristoon" että kylään. 

#### Ehdotettu muutos   

Korjataan huomautus?

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Pellinki

**Comment by mirmaid** [comment]
Tässä voi olla kyllä hyvin vaikea erotella, ja olisiko hakijan kannalta kovin tarkoituksenmukaista?

**Comment by mirmaid** [comment]
Päätermi nykyiselleen, muokataan huomautusta: Pellinki on kylä ja ryhmä saaria Porvoossa.
