### ISSUE TITLE
Kuopio -- Pulkonkoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8639]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuopio -- Pulkonkoski](http://www.yso.fi/onto/ysa/Y125912) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

YSO-paikat: Pulkonkoski (Kuopio)
Huomautus nyt  "Pulkonkoski on sekä kylä että koski Kuopiossa" 

#### Ehdotettu muutos   

Tarkennetaan

**Comment by mirmaid** [comment]
Vastaava kuin https://github.com/Finto-ehdotus/YSE/issues/8642

**Comment by mirmaid** [comment]
Aineisto?

**Comment by mirmaid** [comment]
Poistetaan huomautus, jätetään tarkenne entiselleen.
