### ISSUE TITLE
ratamaksut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#864]
#### Ehdotettu termi suomeksi

ratamaksut
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/ysa/ryhma_39)
#### Lähde

Lähde:  Ratamaksuperiaatteiden uudistaminen: Laki valtion rataverkosta, radanpidosta ja rataverkon käytöstä
#### Käsitteen määritelmä

Sanalla on ainakin kaksi merkitystä. 1) Vuodesta 1990 lähtien rautatieyrityksiltä on peritty ratamaksua rataverkon käyttämisestä. 2) Tarkoittaa maksua, jonka harrastajat maksavat esim. ampumaradan, moottoriradan yms. käytöstä

**Luontipäivämäärä:** 17.12.2002

**Muokkauspäivämäärä:** 17.12.2002, 16.12.2008

**Voyager-id:** 122318

**Termiehdotus Fintossa:** [ratamaksut](http://finto.fi/yse/fi/page/Y322318)

**Comment by HeidiRonkainen** [comment]
Tarvitsisin merkityksessä 1. http://www.doria.fi/bitstream/handle/10024/121074/lts_2015-31_978-952-317-105-3.pdf?sequence=1&isAllowed=y

**Comment by YSA-kokous** [comment]
ratamaksut (rautatieliikenne)
