### ISSUE TITLE
Hämeenkyrö -- Kyröskoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8642]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hämeenkyrö -- Kyröskoski](http://www.yso.fi/onto/ysa/Y124440) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan 

#### Perustelut ehdotukselle   

YSO-paikat: Kyröskoski (Hämeenkyrö)
Ei voi varmaan olla sekä koski että kylä

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Kyr%C3%B6skoski

Tarvitaanko koski erikseen? Ei ole Paikkatietoalustalla.

**Comment by ilona-x** [comment]
Näissä saattaisi olla tarpeen Kyröskoski (koski):

https://melinda.kansalliskirjasto.fi/byid/007079216
Kyröskosken syntymä-asiasta / esittänyt Yrjö Koskinen.

https://melinda.kansalliskirjasto.fi/byid/013415696
Ja Kyröskoski vaikenee : kertomus siitä, kuinka yksi koski saa erilaiset arvomaailmat törmäämään rajusti toisiinsa; yhden kosken pitäisi riittää kansallismaisemaksi, rahasammoksi, asuinympäristöksi, työpaikaksi ja paljoksi muuksi.

https://melinda.kansalliskirjasto.fi/byid/013977257
Kyröskosken voimalaitokselle uusi ilme paikka hyödyntäen.

https://melinda.kansalliskirjasto.fi/byid/012331128
Kyröskosken voima voimalan laajennushankkeesta

**Comment by mirmaid** [comment]
Kyröskoski (Hämeenkyrö : taajama)
Kyröskoski (koski)
