### ISSUE TITLE
musikaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8646]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musikaalit](http://www.yso.fi/onto/ysa/Y103606) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT "teatterimusikaalit" ja RT/ST "musikaalielokuvat" sekä huomautus: Näytelmä, jossa populaarimusiikkia edustavat laulut ja tanssinumerot kuljettavat tarinaa eteenpäin. Elokuvaksi sovitetuista musikaaleista käytetään SLM-termiä "musikaalielokuvat". 

#### Perustelut ehdotukselle   

Ks. https://github.com/Finto-ehdotus/YSE/issues/8548 ja https://www.wikidata.org/wiki/Q2743 sekä Oxford Music Online ("The principal form of Western popular musical theatre in the 20th century, in which sung and danced musical numbers in popular and pop music styles are combined within a dramatic structure.") 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Lisätään teatterimusikaalit ohjaustermiksi.

**Comment by MUUSA-kokous** [comment]
KT "teatterimusikaalit" ja RT "musikaalielokuvat"
Määritelmää vielä viilattava.

**Comment by jarmosaarikko** [comment]
odottaa määritelmää Muusalta

**Comment by YSO-kokous** [comment]
Odotetaan määritelmää Muusalta.

**Comment by mirmaid** [comment]
Määritelmäehdotus puuttuu edelleen.

**Comment by MUUSA-kokous** [comment]
Määritelmäehdotus:
Näyttämömusiikkiteos, jossa viihteellisillä lauluilla ja usein myös tanssinumeroilla on merkittävä rooli tarinan kuljettamisessa.

**Comment by mirmaid** [comment]
Entäpä SLM? (Määritelmä, suhteet?)

**Comment by MUUSA-kokous** [comment]
Määritelmä SLM:ssä sama kuin YSOssa. ST musikaalielokuvat siirretään RT:ksi.

**Comment by ilona-x** [comment]
SLM/Määritelmä sama kuin YSOssa.

LT näyttämömusiikki, samoin operetit ja oopperat
