### ISSUE TITLE
musiikkielokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8647]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[musiikkielokuvat](http://www.yso.fi/onto/ysa/Y101180) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään ST "musikaalielokuvat" sekä määritelmä ja käyttöhuomautus: "Elokuva, jonka keskeisenä aiheena on musiikkielämä tai muusikon henkilöhistoria ja jossa musiikkia käytetään diegeettisesti (äänilähde näkyvillä elokuvassa)." 

#### Perustelut ehdotukselle   

Ks. https://github.com/Finto-ehdotus/YSE/issues/8548 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Ei kannateta ehdotusta. Musikaalielokuva ei ole musiikkielokuvan alalaji. Määritelmäehdotus on liian rajaava.

**Comment by YSO-kokous** [comment]
Jää termiehdotukseksi

**Comment by mirmaid** [comment]
Määritelmä ja mahdollinen käyttöhuomautus puuttuvat edelleen.

**Comment by jarmosaarikko** [comment]
Musikaalit on nyt Muusassa määritelty "näyttämömusiikkiteoksiksi" #8646. Mitä sitten on musiikkiteoksesta tehty elokuva?

**Comment by MUUSA-kokous** [comment]
Musiikkiteoksesta tehty elokuva on liikkuvan kuvan teos, jolla on suhde musiikkiteokseen.

**Comment by ilona-x** [comment]
SLM-kokous: Lisätään huomautus, että käytetään vain fiktioelokuvista. Palataan määritelmään myöhemmin. Yläkäsitteeksi fiktioelokuvat

**Comment by mirmaid** [comment]
Siirrän tämän kommentin musikaalielokuvat-issuesta, koska kuuluu tähän termiin: _Pohdittavia esimerkkejä määritelmän päivittämisen kannalta: selkeinä Amadeus (1984) ja Tous les matins du monde (1991), entä Pink Floyd – The Wall (1982)?_

**Comment by mirmaid** [comment]
Elokuvat issuessa kommentti: 

musiikkielokuvat (+ST)
- Tarvitseeko tarkenteen, jos rajautuu fiktioon

**Comment by MUUSA-kokous** [comment]
Ehdotetaan sulkutarkennetta _fiktioelokuvat_
Määritelmäehdotus: Fiktioelokuva, jossa musiikilla on keskeinen asema.

**Comment by mirmaid** [comment]
musiikkielokuvat (dokumentit) KÄ musiikkidokumentit

Hyväksytään muodossa musiikkielokuvat. Lisätään määritelmä.

**Comment by mirmaid** [comment]
YSO vrt. SLM, lisätäänkö määritelmä ja puuttuvat suhteet?
