### ISSUE TITLE
kognitiivinen ergonomia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8648]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kognitiivinen ergonomia 

#### Ehdotettu termi ruotsiksi   

kognitiv ergonomi 

#### Ehdotettu termi englanniksi   

cognitive ergonomics 

#### Vaihtoehtoiset termit ja ilmaisut   

informaatioergonomia, informationsergonomi, information ergonomics 

#### Vastaava käsite muussa sanastossa   

Työsuojelusanasto (TSK 35, 2006/2008) : https://termipankki.fi/tepa/fi/haku/kognitiivinen%20ergonomia 

#### Tarkoitusta täsmentävä selite   

"ergonomia, joka keskittyy järjestelmiin ja niiden käyttöliittymiin sekä ihmisen tiedonkäsittelyyn" (Työsuojelusanasto (TSK 35, 2006/2008), https://termipankki.fi/tepa/fi/haku/kognitiivinen%20ergonomia) 

#### Perustelut ehdotukselle   

Kognitiivista ergonomiaa käsitteleviä opinnäytteitä (ja muuta aineistoa) on nykyään aika kattavasti, joten termin sisällyttäminen YSOon helpottaisi kuvailua ja näin ollen myös tiedonhakua. AMK-opinnäytteiden tallennusprosessi vaatii myös opiskelijaa antamaan työlleen sopivat YSO-sanat ja kognitiivisen ergonomian puuttuminen on aiheuttanut haasteita. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. http://urn.fi/URN:NBN:fi:amk-2020051611767 tai http://urn.fi/URN:NBN:fi:tuni-202004173331 

**Ehdottajan organisaatio:** SAMK (Satakunnan Ammattikorkeakoulu) **Termiehdotus Fintossa:** [kognitiivinen ergonomia](http://finto.fi/yse/fi/page/Y508648)

**Comment by mirmaid** [comment]
LIITOssa, TEROssa ja TSR-ontologiassa. 5 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään ehdotus.
