### ISSUE TITLE
jatkuvat julkaisut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8650]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jatkuvat julkaisut](http://www.yso.fi/onto/ysa/Y161665) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-hierarkian tarkistus 

#### Perustelut ehdotukselle   

Kausijulkaisut-termin alatermejä halutaan käyttää tarvittaessa myös päivittyvien julkaisujen kuvailussa. Onko tarpeen muuttaa hierarkiaa? 

#### Ehdottajan organisaatio   

SLM-kokous

**Comment by mirmaid** [comment]
- Maria tutkii, miten Ruotsin genresanastossa käsitelty jatkuvien julkaisujen termejä.

- LCGFT: serial publications -termit. Tutustutaan ennen seuraavaa kokousta ja verrataan omaan jatkuvien julkaisujen termistöön.

**Comment by mariaforsen** [comment]
SAO genre: 
Seriella publikationer (eng. serial publications) https://id.kb.se/term/saogf/Seriella%20publikationer
 ST årsböcker, nyhetsbrev, dagstidningar, periodika, almanackor

Periodika (eng. periodicals) https://id.kb.se/term/saogf/Periodika
 ST fanziner

Fortlöpande publikationer (fi. jatkuvat julkaisut) löytyy siis ainoastaan MARC-terminä, ei sanastoissa. Ei myöskään löydy "continuous publications" (=YSO eng.) LCSH:sta.

https://publications.europa.eu/code/fi/fi-240300.htm : 
4.3.2 Jatkuvat julkaisut
Standardin ISO 3297:2017 (ISSN) mukaan jatkuvat julkaisut ovat julkaisuja, jotka ovat julkisesti saatavilla ja ilmestyvät missä tahansa julkaisumuodossa. Ne ilmestyvät peräkkäisinä tai täydentyvinä osina, jotka on yleensä merkitty numeerisesti tai kronologisesti, eikä niiden päättymisajankohtaa ole etukäteen määritetty. Jatkuvia julkaisuja ovat
1) kausijulkaisut, jotka ilmestyvät peräkkäisinä tai erillisinä, yleensä numeroituina osina ilman ilmestymisen päättymisajankohtaa (sanoma- ja aikakauslehdet, painetut ja sähköiset kausijulkaisut, vuosijulkaisut (esimerkiksi vuosikertomukset, vuosiluettelot ja -kirjat sekä hakemistot), tutkielmat ja monografiasarjat)
2) jatkuvasti päivitettävät julkaisut eli ilman päättymisajankohtaa ilmestyvät jatkuvat julkaisut, joita täydennetään kokonaisuuteen yhdistyvillä päivityksillä (tietokannat, jatkuvasti päivitettävät irtolehtijulkaisut ja jatkuvasti päivitettävät verkkosivustot, kuten tämän julkaisukäsikirjan verkkoversio).

**Comment by mirmaid** [comment]
Onko tälle tarpeen tehdä jotain? Kausijulkaisut-käsitteen alla lähinnä lehdet-loppuisia. Halutaanko esim. lisätä kausijulkaisut-käsitteelle määritelmä, joka pitää sisällään myös päivittyvät julkaisut? Tai jättää ristiriita nykyiselleen, jos se ei kuitenkaan aiheuta palautetta? Tai tehdä jotain muuta?

Avointa issueta on mielestäni turha pitää mukana käsittelyjonossa, jos ei ole ehdotusta toivotusta muutoksesta.

**Comment by mirmaid** [comment]
Palataan asiaan, jos herättää jatkossa kysymyksiä/keskustelua.
