### ISSUE TITLE
spekulatiivinen fiktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8651]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[spekulatiivinen fiktio](http://www.yso.fi/onto/ysa/Y200892) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-hierarkian tarkistus 

#### Perustelut ehdotukselle   

Miten käsitellään useille aineistotyypeille yhteiset genretermit, esim. kyberpunk? Ylätasolle vai kaikkien soveltuvien yläkäsitteiden alle? 

#### Ehdottajan organisaatio   

SLM-kokous

**Comment by mirmaid** [comment]
Huomioitava hierarkian toimivuus "alas asti", nyt esim. spekulatiivinen fiktio -termi sopisi useamman aineistotyypin genreksi, mutta sillä on puolestaan kirjallisuus-loppuisia alatermejä.

**Comment by AuHo22** [comment]
Meillä on spekulatiivinen fiktio -termiä käytetty ainoastaan kirjallisuusaineiston yhteydessä. Pelien tai elokuvien yhteydessä  käytettäneen sitten ehkä spesifimmin fantasia- tai scifipelit -termejä ja elokuvassa samoin.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8826

**Comment by mirmaid** [comment]
YK kaunokirjallisuus
