### ISSUE TITLE
elokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8652]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elokuvat](http://www.yso.fi/onto/ysa/Y95002) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-hierarkia tarkistettava 

#### Perustelut ehdotukselle   

Kirjastopalvelun ehdottamat vaihtoehdot:

1. ELOKUVA (kannatettu vaihtoehto)
> elokuvat + dokumenttielokuvat + loput johdettuna elokuva-päähierarkiasta

2.	 ELOKUVAT
> fiktioelokuvat + dokumenttielokuvat + loput johdettuna elokuvat-päähierarkiasta muiden kuin sisältöominaisuuden mukaan 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mirmaid** [comment]
**elokuvat / (fiktioelokuvat)**
- sisällön mukaan, so. genret

**dokumenttielokuvat**
- sisällön mukaan, esim. draamadokumentit, luontodokumentit, opetuselokuvat

**elokuva(t)-hierarkian pudotustasolla (voi sisältää sekä fiktiivisiä että dokumenttielokuvia):**
- kohderyhmän mukaan, so. lastenelokuvat, nuortenelokuvat, perhe-elokuvat
- tekniikan mukaan, esim. animaatioelokuvat, dogmaelokuvat (?), 3D-elokuvat, mykkäelokuvat, mustavalkoiset elokuvat, värielokuvat, tehoste-elokuvat jne.
- tuotantotavan mukaan, kuten independent-elokuvat, amatöörielokuvat (+ kotivideot?), yhteistuotantoelokuvat, uusintatuotantoelokuvat
- ominaan esim. kokeelliset elokuvat (kokeellisuus voi koskea muotoa tai sisältöä), videoidut esitykset?
 - välineen mukaan, so. mediatyyppi? televisioelokuvat, videoelokuvat

**Comment by mirmaid** [comment]
Huom. kuvailukäytön kannalta on ongelma, jos sanastossa on sekä _elokuva_- että _elokuvat_-termi. Keskusteltiin _fiktioelokuvat_-termistä ja todettiin, että fiktiivisistä elokuvista puhutaan yleisesti pelkkinä elokuvina, joten se olisi sekä kuvailijoille, että käyttäjille luonteva kuvailu/hakutermi, vaikka sanastossa olisikin lisäksi fiktioelokuvat. Tämä voisi johtaa epäjohdonmukaiseen kuvailukäyttöön, jossa osa fiktiivisistä elokuvista saisi genren fiktioelokuvat, osa pelkän elokuvat-termin. 
Hierarkian kannalta _fiktioelokuvat_ olisi käytännöllinen.

Keskusteltiin myös vaihtoehdosta, jossa _elokuvat_-termi on yläkäsite, jonka alla on _dokumenttielokuvat_, mutta ei erillistä yläkäsitettä fiktiivisille elokuville. Tämä vastaisi termien yleistä käyttöä, eikä ole ongelma hierarkian kannalta, mutta ei mahdollista kaikkien fiktioelokuvien kokoamista yhden kattotermin alle esim. hakuliittymissä.

Todettiin, että dokumenttielokuvat ei kata kaikkia ei-fiktiivisiä elokuvia.

**Comment by mirmaid** [comment]
Seuraava kokous: tutkitaan, miten _elokuvat_-termiä on käytetty Melindassa. Miten laajasti termiä on käytetty ei-fiktiivisistä elokuvista?

**Comment by AuHo22** [comment]
Elonetissa/Kansallisfilmografiassa ensinnä Lajityyppi-jaottelu Fiktio/Dokumentti ja genreinä sitten lähemmin kuvailevia termejä. Myös teoksia tuli vastaan, joissa ei Lajityyppiä ole eriteltynä. 
"_Keskusteltiin myös vaihtoehdosta, jossa elokuvat-termi on yläkäsite, jonka alla on dokumenttielokuvat, mutta ei erillistä yläkäsitettä fiktiivisille elokuville. Tämä vastaisi termien yleistä käyttöä, eikä ole ongelma hierarkian kannalta, mutta ei mahdollista kaikkien fiktioelokuvien kokoamista yhden kattotermin alle esim. hakuliittymissä_." -> Keskusteltiinko jossain vaiheessa senkaltaisesta hierarkiavaihtoehdosta, jossa tietoaineisto, toisaalta fiktiivinen/taiteellinen aineisto jo ylemmän hierarkian tasolla eroteltaisiin, ja tällöin elokuvat asettuisi molempien alle terminään, vrt. kuten kyberpunk asettuu eri taiteitten lajien alle? Ja ratkaisisiko se mitään?

**Comment by AuHo22** [comment]
AV:n kommentointia: Yo. kursiivilla oleva vaihtoehto tuntuu parhaimmalta. Muitakin keinoja erottaa fiktiivisiä elokuvia dokumenttielokuvista on kuin hierarkia: -> Luokitus elokuvissa menee ihan täysin sisällön mukaan kuten kirjoissakin. Eli fiktiivinen aineisto 84 luokkiin ja sitten tietoaineisto aiheen mukaiseen luokkaan. Tietoaineistossa käytetään dokumenttielokuvat muototermiä oli aihe sitten ihan mikä tahansa ei fiktiivinen.

**Comment by AuHo22** [comment]
https://www.loc.gov/aba/publications/FreeSHM/H1913.pdf

**Comment by jtuohini** [comment]
Johdatus Kongressin kirjaston lajityyppi- ja muotosanastoon: https://www.loc.gov/aba/publications/FreeLCGFT/2020%20LCGFT%20intro.pdf

**Comment by jtuohini** [comment]
LCGFT kokonaisuutena: https://www.loc.gov/aba/publications/FreeLCGFT/GENRE.pdf

**Comment by mirmaid** [comment]
Ryhmä ehdottaa fiktioelokuvat-termin ottamista sanastoon, mutta pyytää vielä kommentteja KUMEAn peli- ja videotyöryhmältä ja KAUNO-ryhmältä. 

Käyttöhuomautus: _Fiktioelokuvien kuvailussa lajityyppiterminä käytetään elokuvat-termiä ja sitä tarkentavia genretermejä, esim. elokuvat & gangsterielokuvat. Fiktioelokuvat-termin sijasta pyritään käyttämään tarkempia termejä aina kun se on mahdollista. Fiktioelokuvat-termiä käytetään elokuvat-termin lisäksi silloin, kun tarkempaa elokuvan fiktiivisyyden ilmaisevaa termiä ei ole._

**Comment by mirmaid** [comment]
Kopioidaan tähän Kirjastopalvelun ehdotus fiktioelokuvien hierarkiasta.
https://docs.google.com/document/d/1OkndbtgGMY2fa3-R72cU_bJjCk0t9MIrVZzCbWcPJxc/edit
https://docs.google.com/document/d/1UXR2wtNzenFxxkMVcx2Ph1Qtvn3Xibhr7bUZMfvPkOk/edit

**Comment by ghost** [comment]
KAUNO-ryhmä ei pidä termiä kuvailun kannalta tarpeellisena, mutta ei vastusta termin ottamista sanastoon. Käyttöhuomautus tärkeä olla.

**Comment by annavii** [comment]
Termin lisääminen sanastoon sopii myös KUMEAn peli- ja videotyöryhmälle.

**Comment by AuHo22** [comment]
Kyseenalaistamatta fiktioelokuvia?  (SLM-listaus elokuvista):

Bollywood-elokuvat
buddy-elokuvat
chick flick  
dogmaelokuvat
                        
draamaelokuvat
**eläinelokuvat**
-> POISTETAANKO MÄÄRITELMÄ -> RAJATAAN PELKÄSTÄÄN FIKTIOON / käytetty molemmissa
> lisätään tarkenne (fiktioelokuvat) ja poistetaan määritelmä

elämäkertaelokuvat
> tutkitaan, onko käytetty vain fiktiosta ja tarvitseeko tarkenteen

episodielokuvat
epookkielokuvat
eroottiset elokuvat
fantasiaelokuvat
film noir
gansterielokuvat
historialliset elokuvat
jengielokuvat
jännityselokuvat
katastrofielokuvat
kauhuelokuvat (+sen ST)
lännenelokuvat (+ ST)
maaseutuelokuvat

**matkailuelokuvat**
-liitän tämän termin dokumenttiin, mikäli fiktiivinen niin käytetään road moviet, ei siis tarvi matkailudokumentteja -Samaa mieltä -Sopii minulle, jos päätetään näin niin road movie määritelmää pitää varmaan tarkentaa -> Käytetään (fiktiivisistä) elokuvista, joissa keskeisen kerronnan rakenteen muodostaa matkustaminen usein symbolisesti esitettynä pakenemisena yhteiskunnallisista sidonnaisuuksista vapaaseen elämään.
-> RAJATAANKO SIIS DOKUMENTTIELOKUVIIN
> tästä on vanha issue, selvitetään termin lopullinen muoto ja rajaus

mieselokuvat? naiselokuvat? fikt. aiheina, voiko olla dokumenttia, ei kohderyhmänä, vrt.
> KAUNO-ryhmä keskustelee

opiskelijaelokuvat
perhe-elokuvat
musikaalielokuvat

musiikkielokuvat (+ST)
> tarvitseeko tarkenteen, jos rajautuu fiktioon

oikeussalielokuvat
poliisielokuvat
poliittiset elokuvat, yhteiskunnalliset elokuvat
> tutkitaan, tarvitseeko tarkenteen

pseudodokumentit
psykologiset elokuvat
queer-elokuvat
rakkauselokuvat (+ST)
rikoselokuvat
> onko käytetty dokumenteista? Otetaanko true crime/rikosdokumentit?

rillumareielokuvat
road moviet
romanttiset draamat
salapoliisielokuvat
satuelokuvat
seikkailuelokuvat (+ST)
seksielokuvat
siirtolaiselokuvat (fikt. aiheena)
> poistetaan termi

sotaelokuvat
splatter
supersankarielokuvat

**taiteilijaelokuvat**, voidaanko käyttää myös dokumenteista, esim. Virpi Suutari: Aalto?
-Kyllä käyttäisin myös dokumenteissa vaikka tuossa Aalto tapauksessa, vaikka dokumentteihin harvoin laitetaan muita genrejä kuin dokumenttielokuvat
> määritelmä

**tanssielokuvat** todellisuuspohjaisia elokuvia, mutta fiktiota samoin kuin musiikkielokuvat? 
-outo genre itselleni, jos on musiikkielokuva niin se tai sitten musikaalit, en tiedä mikä voisi olla tanssielokuva?
> miten käytetty, määritelmä?

tieteiselokuvat (+ST)
todellisuuspohjaiset elokuvat
toimintaelokuvat (+ST)
tuhkimotarinat
tukkilaiselokuvat

**urheiluelokuvat** 
-Tätä genreä olen vähän kaivannut myös tietokäyttöön, koska on paljon urheiluelokuvia, jotka ovat dokumentteja. En kuitenkaan ole laittanut, pitäisikö? urheiludokumentit KT urheiluelokuvat (dokumenttielokuvat)

uskonnolliset elokuvat
vakoiluelokuvat
vankilaelokuvat
veijarielokuvat
yhteiskunnalliset elokuvat

**Comment by mirmaid** [comment]
YK elokuvat:
3D-elokuvat
amatöörielokuvat
animaatioelokuvat
independent-elokuvat
kokeelliset elokuvat
lastenelokuvat
lyhytelokuvat
mainoselokuvat
mustavalkoiset elokuvat
mykkäelokuvat
nuortenelokuvat
opetuselokuvat
piilokameraelokuvat 
> vaatisi ehkä termin muokkausta?

sarjaelokuvat
televisioelokuvat (Jaakko laatii määritelmän)
uusintatuotantoelokuvat (vai onko aina fiktiota)?
värielokuvat
yhteistuotantoelokuvat

**Comment by mirmaid** [comment]
dokumenttielokuvat YK elokuvat
alakäsitteiksi luontodokumentit ja urheiludokumentit (?)
draamadokumentit (?)

**Comment by mirmaid** [comment]
Poistetaan tehoste-elokuvat

**Comment by mirmaid** [comment]
Vielä kesken:

**uusintatuotantoelokuvat**: YK elokuvat vai fiktioelokuvat?

**tanssielokuvat** todellisuuspohjaisia elokuvia, mutta fiktiota samoin kuin musiikkielokuvat?
- outo genre itselleni, jos on musiikkielokuva niin se tai sitten musikaalit, en tiedä mikä voisi olla tanssielokuva?
_- Miten käytetty, määritelmä?_

**taiteilijaelokuvat**, voidaanko käyttää myös dokumenteista, esim. Virpi Suutari: Aalto?
- Kyllä käyttäisin myös dokumenteissa vaikka tuossa Aalto tapauksessa, vaikka dokumentteihin harvoin laitetaan muita genrejä kuin dokumenttielokuvat
_- Määritelmä_

**urheiluelokuvat**
- Tätä genreä olen vähän kaivannut myös tietokäyttöön, koska on paljon urheiluelokuvia, jotka ovat dokumentteja. En kuitenkaan ole laittanut, pitäisikö? urheiludokumentit KT urheiluelokuvat (dokumenttielokuvat)

**rikoselokuvat**
_- Onko käytetty dokumenteista? Otetaanko true crime/rikosdokumentit?_

**poliittiset elokuvat, yhteiskunnalliset elokuvat**
_- Tutkitaan, tarvitseeko tarkenteen_

**musiikkielokuvat (+ST)**
_- Tarvitseeko tarkenteen, jos rajautuu fiktioon_

**mieselokuvat, naiselokuvat**: poistetaanko?

**Comment by AuHo22** [comment]
Hei,
meidän av-osaajamme kommentoi olemassaolevaa keskeneräiset-listaa näitä osin:

Rikoselokuvat käytetään fiktiivisistä elokuvista, ihan kuten vaikka rikoskirjallisuus.

Värielokuva on oletus, joten se tulisi käytännössä jokaiseen elokuvaan. En tiedä miten tuota muokkaisi? Siksi on mustavalkoelokuvat, jos haluaa korostaa mustavalkoisuutta aina en ole sitä käyttänyt edes mustavalkoelokuvissa. Yhteistuotanto on vähän sama, että se tulisi melkein kaikkiin elokuviin. Uusintatuotantoelokuvat on fiktioo.

-> Oma kommenttini: Onko värielokuvat nykyisin vähän sama kuin tehoste-elokuvat, eli tarvitaanko enää edes sanastossa - perusoletuksena siis jokaisessa olemassa?

**Comment by jtuohini** [comment]
Ehkä "värielokuvakaudella" tuotetut mustavalkoelokuvat ovat sellaisia poikkeuksia, joissa **mustavalkoelokuvat**-termi puoltaisi paikkaansa?

**Comment by AuHo22** [comment]
Tietenkin elokuvan alkuaikoina tuotettujen värielokuvien kohdalla (kun elokuvissa mainitaan aina tuotantovuodetkin), slm-termi värielokuvat lienee tarpeellinen.

**Comment by AuHo22** [comment]
Meiltä tullut korjausehdotus:
SLM-käsite tuhkimotarinat on nyt fiktioelokuvien ST. Käytetään myös kirjallisuuteen. 

Vrt. veijaritarinat RT veijarielokuvat RT veijariromaanit
Hierarkialinjaukset - monihierarkia?

**Comment by mirmaid** [comment]
Poistetaan mieselokuvat ja naiselokuvat.

uusintatuotantoelokuvat: YK fiktioelokuvat
tanssielokuvat: YK fiktioelokuvat, RT myös musikaalielokuvat
taiteilijaelokuvat: YK fiktioelokuvat
urheiluelokuvat: YK fiktioelokuvat
rikoselokuvat: YK fiktioelokuvat
poliittiset elokuvat, yhteiskunnalliset elokuvat - ei tarkennetta

yhteistuotantoelokuvat - pois RT uusintatuotantoelokuvat

Keskusteltavaksi onko yhteistuotantoelokuvat, mustavalkoelokuvat ja värielokuvat aihetta poistaa kokonaan. 

Musiikkielokuvat - oma issue. 

tuhkimotarinat YK tarinat

**Comment by AuHo22** [comment]
_Keskusteltavaksi onko yhteistuotantoelokuvat, mustavalkoelokuvat ja värielokuvat aihetta poistaa kokonaan._ Av:n kommentti:-> Yhteistuotantoelokuvat, mustavalkoelokuvat ja värielokuvat voi mielestäni poistaa kokonaan. en usko, että kukaan hakee värielokuvia. En näe millään näillä termillä lisäarvoa kuvailuun. -- Siitä värillisyydestä tai mv tulee maininta kyllä elokuvissa 300 kenttään ja myös kiinteissä on sille oma koodinsa. Eli ei tuo tieto löytyy sieltä joka tapauksessa, mutta en ole noita termejä asiasanoina kyllä käyttänyt juurikaan. Ei niissä silti mitään väärää ole, ihan asiallisia ja päteviä termejä. Aika vain on muuttanut vähän merkitystä ja aiempi harvinaisuus värielokuva on nykyään oletus. Mikäli termit säilytetään sanastossa niin olisi hyvä käydä keskustelua missä yhteydessä niitä on tarkoitus käyttää? Esim värielokuva tulisi nykyään melkein jokaiseen elokuvatietueeseen. Jos on nykyaikainen mv elokuva niin voisin laittaakin genreksi mustavalkoelokuvat, mutta kyllä niitä genreen liittyviä termejä miettii enemmän kuin ihan tällaisia muotoon liittyviä.

Myös seuraava kommentti:  -mielestäni tuo "harvinaisuus"  mustavalkoelokuvat olis hyvä säilyttää. Itse hakisin sillä (paremman puutteessa) -> Kirjastojen asiakasnäkökulmasta tietenkin ajatellen yleensä halutaan erilaisten koodien aukikirjoittamista, koskapa asiakas ei yleensä kykene koodikieltä lukemaan eikä sen myötä osaa hakea aineistoa sen avulla.

Myös: "Mustavalkoelokuvat on perusteltu pitää SLM-sanastossa. YSO-terminä olisi hyvä olla myös värielokuvat, koska ne muuttivat ilmaisua yhtä paljon kuin äänen tulo elokuviin. Elokuvatutkimuksessa näitä aina välillä tutkitaan."

**Comment by mirmaid** [comment]
**_Tutkittava, onko mustavalkoisuus/värillisyys haettavissa Finnasta (Ilkka)._**

Poistetaan yhteistuotantoelokuvat.
