### ISSUE TITLE
asterikasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8654]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[asterikasvit](http://www.yso.fi/onto/ysa/Y107909) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT mykerökukkaiset 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
kts. myös https://tieteentermipankki.fi/wiki/Nimitys:myker%C3%B6kukkaiset
on Kassussa ja Wikipediassa muodossa "mykerökukkaiskasvit", jonka voinee myös lisätä.  Näitä ei ole listattu lajitietokeskuksen kannassa yleiskielisenä varianttinimenä tälle taksonille:   http://tun.fi/MX.39723

**Comment by YSO-kokous** [comment]
Hyväksytty
