### ISSUE TITLE
urbaani fantasia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8655]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

urbaani fantasia 

#### Ehdotettu termi englanniksi   

urban fantasy 

#### Ehdotettu termi ruotsiksi   

urban fantasy 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fantasia](http://www.yso.fi/onto/yso/p8512) 

#### Tarkoitusta täsmentävä selite   

https://www.kirjasampo.fi/fi/sivupiiri-kirjallisuusgenre-urbaani-fantasia 

#### Perustelut ehdotukselle   

Urbaani fantasia on kirjallisuuskeskustelussa paljon käytetty genretermi, jonka tarve ilmenee etenkin nuorten ja nuorten aikuisten kirjallisuudessa. 
"Urbaani fantasia on eräänlainen kattotermi tarinoille, jotka sijoittuvat (pääasiassa) tavalliseen todellisuuteen, mutta tässä tavallisessa todellisuudessa piilottelee lukuisia olentoja, jotka eivät kuulu meidän todeksi tietämäämme maailmaan. Tällaisia olentoja ovat esimerkiksi vampyyrit, haltiat, ihmissudet, keijut, velhot, lohikäärmeet, harpyijat ja niin edelleen." 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Elina Rouhiainen: Unienpunoja ; Stephenie Meyer: Keskiyön aurinko 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [urbaani fantasia](http://finto.fi/yse/fi/page/Y508655)

**Comment by jarmosaarikko** [comment]
"urbaani fantasia"@fi, "urban fantasy"@sv   tai "storstadfantasy"@sv,   "urban fantasy"@en 
https://www.wikidata.org/wiki/Q1188977 - https://en.wikipedia.org/wiki/Urban_fantasy
LCSH vain skos:broaderMatch  http://id.loc.gov/authorities/subjects/sh85047114 "fantasy fiction"

**Comment by ghost** [comment]
KAUNO-ryhmä kannattaa ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. urban fantasy ET stadsfantasy
https://id.kb.se/term/saogf/Urban%20fantasy
