### ISSUE TITLE
metylaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8656]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metylaatio 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/300754 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [metylaatio](http://finto.fi/yse/fi/page/Y508656)

**Comment by jarmosaarikko** [comment]
Löytyy TSR-ontologiasta.     - lieneelaajempi käsite kuin YSO:n  DNA-metylaatio http://www.yso.fi/onto/yso/p38350
FinMeshissä  "[metylaatio](http://www.yso.fi/onto/mesh/D008745)"@fi ("metylering"@sv)  on [DNA-metylaatio](http://www.yso.fi/onto/mesh/D019175)n yläkäsite.   
https://www.wikidata.org/wiki/Q518328
LCSH http://id.loc.gov/authorities/subjects/sh00007546  "methylation"@en

**Comment by mirmaid** [comment]
9 viitettä Melindassa, osassa tosin kyse DNA-metylaatiosta. 
_Metylaatio tarkoittaa metyyliryhmien (-CH3) liittymistä tai substituutiota yhdisteeseen_. https://fi.wikipedia.org/wiki/Metylaatio

**Comment by mariaforsen** [comment]
Sv. metylering

**Comment by mirmaid** [comment]
https://www.uef.fi/fi/artikkeli/luonnon-omasta-polymeerista-fossiilisten-kemikaalien-korvaajaksi
