### ISSUE TITLE
pyhäinjäännöslippaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8657]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pyhäinjäännöslippaat 

#### Ehdotettu termi englanniksi   

Reliquaries 

#### Ehdotettu termi ruotsiksi   

relikvarier 

#### Vaihtoehtoiset termit ja ilmaisut   

relikvaariot 

#### Vastaava käsite muussa sanastossa   

SAO : https://id.kb.se/term/sao/Relikvarier 
LCSH : <http://id.loc.gov/authorities/subjects/sh88005676> 
Wikipedia : https://fi.wikipedia.org/wiki/Pyh%C3%A4inj%C3%A4%C3%A4nn%C3%B6slipas 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Silver arms and silk heads :medieval reliquaries in the Nordic countries / 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [pyhäinjäännöslippaat](http://finto.fi/yse/fi/page/Y508657)

**Comment by jtuohini** [comment]
Lisäksi sopisi paremmin kuin hyvin sanaryhmään 94 (Taideteollisuus. Sisustustaide).

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

**Comment by jarmosaarikko** [comment]
Wikidata: https://www.wikidata.org/wiki/Q722604
Finna: pyhäinjäännöslipas: 25 kpl, relikvaario, 9 kpl
