### ISSUE TITLE
barium

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8658]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

barium 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/302636 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [barium](http://finto.fi/yse/fi/page/Y508658)

**Comment by jarmosaarikko** [comment]
On AFO:ssa - yläkäsitteet  aine > alkuaineet > metallt > maa-alkalimetallit > barium
YSOssa ei ole maa-alkalimetallit -ryhmää kuten AFO:ssa. Näitä ovat AFO:ssa  barium, beryllium, kalsium, magnesium, radium, strontium, jotka ovat YSOssa suoraan metallit-käsitteen alla. 
Ehdotus: 
- Lisätään  **barium** suoraan metallit-käsitteen alle TAI
- lisätään YSO:on  AFO: tapaan metallit alakäsitteeksi **maa-alkalimetallit**, jonka alle liitetään **barium** sekä siirretään metallien alta tähän nuo muutkin, jotka nyt ovat suoraan metallit-käsitteen alla.

**Comment by mirmaid** [comment]
^ Maa-alkalimetallit hyväksyttiin viime kokouksessa.

**Comment by mariaforsen** [comment]
Sv. barium
