### ISSUE TITLE
Fallot'n tetralogia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8659]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Fallot'n tetralogia 

#### Vastaava käsite muussa sanastossa   

FinMeSH : Fallot'n tetralogia 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/301458 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Fallot'n tetralogia](http://finto.fi/yse/fi/page/Y508659)

**Comment by jarmosaarikko** [comment]
"Fallot’n tetralogia"@fi, . "Fallots tetrad"@sv "tetralogy of Fallot"@en
 KT "TOF"@fi 
 LCSH: http://id.loc.gov/authorities/subjects/sh85134202
 Wikidata: https://www.wikidata.org/wiki/Q1126831
 Wikipedia: https://fi.wikipedia.org/wiki/Fallot%E2%80%99n_tetralogia
 Määritelmä:  https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=ltt00807  synnynnäisten sydänvikojen yhdistelmä...

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/321148

**Comment by mariaforsen** [comment]
Sv. Fallots tetrad
