### ISSUE TITLE
syövän esiasteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8660]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syövän esiasteet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/305769 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [syövän esiasteet](http://finto.fi/yse/fi/page/Y508660)

**Comment by mariaforsen** [comment]
Sv. cancerförstadier, förstadier till cancer
https://finto.fi/mesh/fi/page/D011230
