### ISSUE TITLE
hengellinen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8661]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hengellinen musiikki](http://www.yso.fi/onto/ysa/Y95327) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSO termillä on tarkenne: (kristinusko). Tuleeko myös SLM-termille tarkenne? 

#### Perustelut ehdotukselle   

vrt. hengelliset laulut (kristinusko), sulkutarkenne on YSO + SLM 

#### Ehdottajan organisaatio   

Jyväskylän kaupunginkirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
