### ISSUE TITLE
boogie woogie (tanssit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8662]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

boogie woogie (tanssit) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

boogie woogie löytyy YSOsta vain musiikkikäsitteenä, ei tanssikäsitteenä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim Modernit seuratanssit. Osa 5, Lindy hop, boogie woogie. ja Tanssikurssi. 1. 

**Ehdottajan organisaatio:** Jyväskylän kaupunginkirjasto **Termiehdotus Fintossa:** [boogie woogie (tanssit)](http://finto.fi/yse/fi/page/Y508662)

**Comment by fantsby-m** [comment]
https://fi.wikipedia.org/wiki/Boogie_woogie_(tanssi)

**Comment by mariaforsen** [comment]
Sv. boogie woogie (danser)

**Comment by mirmaid** [comment]
http://www.yso.fi/onto/yso/p29816 tarvitsee nyt tarkenteen, _boogie woogie (musiikki)_?
