### ISSUE TITLE
merengue (tanssi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8663]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

merengue (tanssi) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[latinalaistanssit](http://www.yso.fi/onto/yso/p210) 
[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

merengue on YSO ssa vain musiikkiin viittaavana käsitteenä, ei tanssilajina 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. tanssinopetusvideot Tanssikurssi. 2., Modernit seuratanssit. Osa 4, Salsa, merenque, bachata., Latinos : let's dance!. Osa 2, Salsa, merenque. 

**Ehdottajan organisaatio:** Jyväskylän kaupunginkirjasto **Termiehdotus Fintossa:** [merengue (tanssi)](http://finto.fi/yse/fi/page/Y508663)

**Comment by fantsby-m** [comment]
https://fi.wikipedia.org/wiki/Merengue_(tanssi)

**Comment by mariaforsen** [comment]
Sv. merengue (danser)
Sulkutarkenne monikossa.
