### ISSUE TITLE
fusku (tanssi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8664]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fusku (tanssi) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[latinalaistanssit](http://www.yso.fi/onto/yso/p210) 
[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

fusku on yleinen ja suosittu tanssilaji lavatansseissa ja kilpatansseissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

tanssinopetusvideoissa esim.: Tule tanssimaan. 1, Häävalssi (valssi), tango, foxi (hitaat), lavajive (fusku) ; Hannun ja Helenin kanssa parketilla. ; Modernit seuratanssit. Osa 1, Fusku, jive, bugg. ; Modernit seuratanssit. Osa 7, Fusku (jatkokurssi), jive (jatkokurssi), rockabilly. ; Tanssikurssi kotona. 2 

**Termiehdotus Fintossa:** [fusku (tanssi)](http://finto.fi/yse/fi/page/Y508664)

**Comment by mirmaid** [comment]
Onko tarkenne tarpeen?

**Comment by fantsby-m** [comment]
https://fi.wikipedia.org/wiki/Fusku
Engl. ei ole tuohon^ linkitetty, mutta on ilmeisesti sama:
https://en.wikipedia.org/wiki/Single_Swing

**Comment by mariaforsen** [comment]
Sv. fusku (danser)
