### ISSUE TITLE
konglomeraatti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8665]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

konglomeraatti 

#### Ehdotettu termi ruotsiksi   

konglomerat (geologi) 

#### Ehdotettu termi englanniksi   

conglomerate (geology) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kivilajit](http://www.yso.fi/onto/yso/p12593) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Yleinen käsite geologiassa. Käytetty Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Meso- and Neoproterozoic cover rocks of the Svecofennian Domain. 

**Termiehdotus Fintossa:** [konglomeraatti](http://finto.fi/yse/fi/page/Y508665)

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/konglomeraatti

**Comment by jtuohini** [comment]
Pitää varoa, ettei monikkomuoto – jos sellaisesta tehdään viittaus – sekoitus konglomeraatteihin eli konserneihin eli monialayhtymiin, ks. https://fi.wikipedia.org/wiki/Konglomeraatti_(liiketalous)

**Comment by jarmosaarikko** [comment]
ehdotus muutettu 29.1.2021
Sama käytettävä termi näkyy olevan kahdella eri käsitteellä wikidatassa. Sekaannusten välttämiseksi voisi käsitteelle [monialayritykset ](http://www.yso.fi/onto/yso/p4218)   lisätä ohjaustermiksi **konglomeraatit (yritykset)**{@fi} tai **konglomeraatit (liiketalous)**{@fi}, sekä "conglomerates (corporations)"
- kts. https://fi.wikipedia.org/wiki/Konglomeraatti_(liiketalous), sekä conglomerate ([Q778575](https://www.wikidata.org/wiki/Q778575))  two or more corporations that fall under one corporate group 

Ehdotettu uusi käsite: "**konglomeraatti (geologia)**"@fi  "konglomerat (geologi)"@sv  "conglomerate (geology)"@en   
tai "**konglomeraatti (kivilaji)**", konglomerat (bergart)", "conglomerate (rock)"
- https://fi.wikipedia.org/wiki/Konglomeraatti
- https://sv.wikipedia.org/wiki/Konglomerat_(bergart)  
- https://en.wikipedia.org/wiki/Conglomerate_(geology)
- conglomerate ([Q191704](https://www.wikidata.org/wiki/Q191704)) a rock that is composed of smaller rounded rocks cemented together

**Comment by mirmaid** [comment]
Tarvitsee tarkenteen, esim. _(sedimenttikivilajit)_ tai _(geologia)_.

**Comment by YSO-kokous** [comment]
Hyväksytään konglomeraatti (geologia)
