### ISSUE TITLE
poliisilaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8666]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[poliisilaitokset](http://www.yso.fi/onto/ysa/Y103976) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "poliisiasemat" 

#### Perustelut ehdotukselle   

Paljon käytetty ilmaisu, josta olisi hyvä tehdä viittaus. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Ruotsiksi on jo ohjausteminä "polisstationer".
Mielestäni tämä termi viittaa **rakennukseen** eikä organisaation (kuten poliisilaitokset), jolloin tämä pitäisi kuvata eri käsitteenä (vrt. palokunnat - paloasemat). Poliisilaitoksessa voi olla käytössä useita poliisasemarakennuksia.

**Comment by mirmaid** [comment]
HYK ehdottanut termiä myös erikseen, https://github.com/Finto-ehdotus/YSE/issues/8837.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: poliisilaitos: 
1. Poliisihallituksen alaisuudessa toimivia hallinnollisia yksiköitä.
2. koko maan poliisitoimesta. 

Alun perin tuskin on ollut tarkoitus ottaa vain organisaatio-merkityksessä, koska myös poliisilaitos-sanaa kyllä käytetään viittaamaan toimipisteeseen: _Passia säilytetään noutopaikassa 14 vuorokautta. Noutamaton lähetys palautuu noin viikossa poliisilaitokselle, mistä voit noutaa sen_.

**Comment by fantsby-m** [comment]
Kielitoimiston sanakirjassa myös '[poliisiasema](https://www.kielitoimistonsanakirja.fi/#/poliisiasema)':

paikallispoliisin toimipaikka.

**Comment by YSO-kokous** [comment]
Lisätään poliisiasema omana käsitteen  #8837
