### ISSUE TITLE
Kuu (Maan)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8667]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuu (Maan)](http://www.yso.fi/onto/ysa/Y109627) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään termi YSO-paikkoihin 

#### Perustelut ehdotukselle   

Kyse on paikasta, sijainnista avaruudessa. Ks. myös LCSH (https://lccn.loc.gov/sh85087107), jossa sama on 151-kentässä eli maantieteellisenä asiasanana. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Jos toimitaan ehdotuksen mukaan, niin pitäisi samalla kaikki [planeetat](http://www.yso.fi/onto/yso/p6224)-alakäsitteinä olevat **yksilökäsitteet** siirtää yso-paikkoihin, esim. Merkurius, Venus (planeetat), Mars (planeetat) jne.  Ne ovat LCSH:ssa maantieteellisiä käsitteitä.

**Comment by AuHo22** [comment]
Aika paljon muutakin näköjään LCSH:ssa laitettu maantieteellisiin asiasanoihin, esimerkiksi Solar system (tarkoittaako aurinkokuntaamme vs. muut aurinkokunnat, joka jälkimmäinen ei enää ole yksilökäsite? linkitetty jälkimmäiseen) tai Outer space (avaruus), myös Milky Way geografisissa asiasanoissa. Libriksessä kuitenkin näyttäisi olevan vähän erilaisiakin ratkaisuja, jos oikein katsoin.

**Comment by mirmaid** [comment]
Samoin toki myös sitten _maapallo_. LCSHssa linkityspolitiikka on vähän väljempi kuin meillä ja esim. Water (150) on alakäsite Earth-käsitteelle (151).

**Comment by fantsby-m** [comment]
> 
> 
> Jos toimitaan ehdotuksen mukaan, niin pitäisi samalla kaikki [planeetat](http://www.yso.fi/onto/yso/p6224)-alakäsitteinä olevat **yksilökäsitteet** siirtää yso-paikkoihin, esim. Merkurius, Venus (planeetat), Mars (planeetat) jne. Ne ovat LCSH:ssa maantieteellisiä käsitteitä.

Samoin esim. Halleyn komeetta...

**Comment by mariaforsen** [comment]
Näissä käsitteissä on kyllä muitakin "ulottuvuuksia" kuin pelkästään maantieteellisiä.

**Comment by mirmaid** [comment]
Kieltämättä - maantiede: tiede joka tutkii maapallon pintaa, siihen vaikuttavia tekijöitä ja sen alueellisia piirteitä, geografia. :earth_africa: Englanninkielisen wikipedian mukaan tosin geography = _field of science devoted to the study of the lands, features, inhabitants, and phenomena of the Earth and planets_. Mutta että _universumikin_ http://id.loc.gov/authorities/subjects/sh2010007248 ...siihen amerikkalaisetkin sitten vetävät rajan, _multiversumi_ on tavallinen käsite http://id.loc.gov/authorities/subjects/sh2017004652

**Comment by YSO-kokous** [comment]
Ei muutosta
