### ISSUE TITLE
karjatilat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8668]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[karjatilat](http://www.yso.fi/onto/ysa/Y112541) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "karja-asemat" ja "ranchit" 

#### Perustelut ehdotukselle   

Karjatiloja nimitetään Australiassa usein karja-asemiksi (engl. cattle station) ja Yhdysvalloissa rancheiksi (engl. ranch), ja kun nämä kumpikin esiintyvät myös suomenkielisissä teksteissä, niistä olisi hyvä saada viitausmuoto. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
LCHS:ssa  "ranch" on "farm" käsitteen alakäsitteenä ja sillä on ohjausterminä "cattle ranch".  Wikidatassa erillisinä käsitteinä:   [ranch](https://www.wikidata.org/wiki/Q509028) ja [cattle station](https://www.wikidata.org/wiki/Q3663773) mutta käytännössä ne lienevät sama käsite.   Jättäisin "karja-asemat" pois, mutta  englanninkieliseksi ohjaustermiksi voi lisätä "cattle station".

**Comment by YSO-kokous** [comment]
Hyväksytty "ranchit", ei "karja-asemat".
