### ISSUE TITLE
Pitkäkoski -- Vantaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8669]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pitkäkoski -- Vantaa](http://www.yso.fi/onto/ysa/Y160063) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaaan käsitteen ohjaustermiä seuraavasti:
Helsinki (Pitkäkoski) -> Pitkäkoski (Helsinki) 

#### Perustelut ehdotukselle   

Käsitteellä on nähdäkseni ohjaustermissä virhe, varsinainen nimike ja tarkenne ovat väärin päin (Helsinki ei ole osa Pitkäkoskea, vaan Pitkäkoski on osa Helsinkiä (tai Vantaata)). 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Korjattu.
