### ISSUE TITLE
röntgensäteily

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8670]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[röntgensäteily](http://www.yso.fi/onto/ysa/Y98675) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan englanninkielistä käytettävää termiä:
X-radiation -> X-ray radiation
LIsätään ohjaustermi:
X-rays 

#### Perustelut ehdotukselle   

Fysiikan alalla "X-radiation" on erittäin vähän käytetty termi, yleensä käytetään "X-rays"-termiä. Ehkä YSO:ssa käsitteeksi sopii myös "X-ray radiation", kuten Tieteen termipankissa Tähtitieteen luokittelussa on: https://tieteentermipankki.fi/wiki/T%C3%A4htitiede:r%C3%B6ntgens%C3%A4teily

Joka tapauksessa "X-rays" tulisi olla myös ohjausterminä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
wikidatassa X-ray on labelina ja X-radiation aliaksena.

**Comment by jarmosaarikko** [comment]
Käsite päivitetty 5.6.2021
