### ISSUE TITLE
gravitaatioaallot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8671]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[gravitaatioaallot](http://www.yso.fi/onto/ysa/Y207728) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään käsite yhtä tasoa ylemmäs hierarkiassa, "Sähkömagneettinen säteily" -käsitteen alta "Säteily"-käsitteen alle. 

#### Perustelut ehdotukselle   

Gravitaatioaallot eivät ole sähkömagneettista säteilyä. Säteilynä tätä ilmiötä voi pitää, mutta ilmiö ei liity sähkömagneettiseen kenttään, jonka voi ajatella välittävän sähkömagneettista säteilyä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
YSOn ryhmittelevät käsitteet "säteily syntytavan mukaan" ja "säteily aallonpituuden mukaan" ovat nyt sähkömagneettisen säteilyn alakäsitteitä, jolloin myös kaikki näihin ryhmiin kuuluvat ovat hierarkiassa sähkömagneettisen säteilyn alla. Korjataan hierarkia.

- poistetaan ryhmittelevät käsitteet, tai
- siirretään ryhmittelevät käsitteet ylöspäin hierarkiassa ja tehdään niihin kuuluville käsitteille tarvittaessa tuplahierarkia

**Comment by mirmaid** [comment]
Ryhmien muut käsitteet ovat sähkömagneettista säteilyä, mutta _lämpösäteily_ ja _optinen säteily_ eivät oikeastaan ole "säteilyä aallonpituuden mukaan" samassa mielessä kuin muut ryhmän käsitteet. Ne voisi siirtää ja muuttaa ryhmän nimeä > sähkömagneettinen säteily aallopituuden mukaan? Toinen ryhmä tuntuu ehkä tarpeettomalta, käsitteet voisivat olla suoraan säteilyn tai sähkömagneettisen säteilyn alla?

**Comment by mirmaid** [comment]
^ Toteutetaan ehdotetut muutokset.
