### ISSUE TITLE
toiminnallinen magneettikuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8672]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toiminnallinen magneettikuvaus](http://www.yso.fi/onto/ysa/Y175685) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään englannin kieliseen käsiteversioon ohjaustermi "fMRI". 

#### Perustelut ehdotukselle   

Sekä suomaiaisessa että ruotsalaisessa käsiteversiossa on jo ohjausterminä "fMRI". 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
käsite päivitetty 4.5.2021
