### ISSUE TITLE
sähköposti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8673]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sähköposti](http://www.yso.fi/onto/ysa/Y104097) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään englannin kieliseen käsiteversioon ohjaustermi "email", tai asetetaan tämä käytettäväksi termiksi ja muutetaan "e-mail" ohjaustermiksi. 

#### Perustelut ehdotukselle   

"e-mail" -muodon lisäksi teksteissä käytetään paljon, ehkä jopa enemmän, muotoa "email". Internetin hakukone antaa viivattomalle versiolle yli kaksi kertaa enemmän osumia kuin viivalliselle. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
päivitetty YSOon 13.3.2021
