### ISSUE TITLE
Jeesuksen uhri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8674]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Jeesuksen uhri 

#### Ehdotettu termi englanniksi   

sacrifice of Jesus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

”Jeesuksen uhri” on miltei keskeisin asiasana kristinuskossa, mutta sitä ei löydy YSO-sanastosta. Jeesus-hakusannalla löytyy vain ”Jeesuksen pikkusisarukset”, ”Jeesuksen rukous” ja ”Jeesus-liike”, jotka ovat toisarvoisia asiasanoja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

FINNA-hakupaleve 

**Termiehdotus Fintossa:** [Jeesuksen uhri](http://finto.fi/yse/fi/page/Y508674)

**Comment by Uusisana** [comment]
Aineisto jonka kuvailussa käsitettä tarvitaan: FINNA-hakupalvelu

**Comment by jarmosaarikko** [comment]
Ehdotan mieluummin termiä "Jeesuksen sovitusuhri" tai pelkkä "sovitusuhri" ja lisättäväksi ohjausterminä  käsitteelle [sovitus (uskonto)](http://www.yso.fi/onto/yso/p5254)  vastaavasti kuten on tehty LCSH:ssa   [Atonement](http://id.loc.gov/authorities/subjects/sh85009335)  Variant:  "Jesus Christ-Atonement"

**Comment by Uusisana** [comment]
Hei,

kiitos vastauksesta.

”Sovitusuhri” sopii hyvin, mutta Jeesus-sana pitäisi olla mukana.
”Jeesuksen sovitusuhri” erottuu vanhan testamentin ”sovitusuhreista”,
joissa uhri oli eläin ja joita uhrattiin toistuvasti. Jeesus uhraten
itsensä kerran oli kertakaikkinen sovitus.

Ystävällisin terveisin,

Gernot Ludwig

pe 8. tammik. 2021 klo 21.19 Jarmo Saarikko (notifications@github.com)
kirjoitti:

**Comment by mariaforsen** [comment]
Ohjausterminä ok. Edes Teologian asiasanastossa ei ole sen muotoista termiä.
https://evl.fi/sanasto/-/glossary/word/Sovitus
https://evl.fi/sanasto/-/glossary/word/Lunastus
https://evl.fi/sanasto/-/glossary/word/Uhri

**Comment by YSO-kokous** [comment]
hyväksytään ohjausterminä:  sovitusuhri KÄ sovitus (uskonto)
