### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8676]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bugg 

#### Ehdotettu termi ruotsiksi   

bugg 

#### Tarkoitusta täsmentävä selite   

https://tanssit.fi/tanssin-abc/tanssilajit/bugg/ 

#### Perustelut ehdotukselle   

Tarvittaisiin aihetta käsittelevän kirjan kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Bugg för alla : en introduktion till Sveriges populäraste pardans 978-91-80200-13-4 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [bugg](http://finto.fi/yse/fi/page/Y508676)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Bugg

**Comment by fantsby-m** [comment]
https://www.tanssit.fi/tanssin-abc/tanssilajit/bugg/

**Comment by mariaforsen** [comment]
SAOssa https://id.kb.se/term/sao/Jitterbugg

**Comment by mariaforsen** [comment]
Sv. bugg (danser)
