### ISSUE TITLE
ilmakehän rajakerros

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8677]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmakehän rajakerros 

#### Ehdotettu termi englanniksi   

atmospheric boundary layer 

#### Vastaava käsite muussa sanastossa   

LCSH : Boundary layer (Meteorology) <http://id.loc.gov/authorities/subjects/sh85016096> 

#### Perustelut ehdotukselle   

Melinda: 
ilmakehän rajakerros x 25 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Developing methods for Doppler lidar to investigate atmospheric boundary layer 

#### Tarkoitusta täsmentävä selite   

https://tieteentermipankki.fi/wiki/Clean_Energy_Research:atmospheric_boundary_layer 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ilmakehän rajakerros](http://finto.fi/yse/fi/page/Y508677)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Ilmakeh%C3%A4n_rajakerros

**Comment by mariaforsen** [comment]
Sv. atmosfäriskt gränsskikt https://termipankki.fi/tepa/fi/haku/rajakerros
