### ISSUE TITLE
lidar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8678]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lidar 

#### Ehdotettu termi ruotsiksi   

lidar 

#### Ehdotettu termi englanniksi   

lidar 

#### Vaihtoehtoiset termit ja ilmaisut   

Optical radar 
Laser radar 
optiset tutkat 
valotutkat 

#### Vastaava käsite muussa sanastossa   

LCSH : Optical radar <http://id.loc.gov/authorities/subjects/sh85095164> 
GEO : lidar-menetelmät <http://www.yso.fi/onto/gtk/GTK2015ID2017> 
Wikipedia : https://fi.wikipedia.org/wiki/Lidar 

#### Perustelut ehdotukselle   

Melinda x 42

Huom. YSOssa nyt LiDAR (sv) ohjausterminä laserkeilaukselle http://www.yso.fi/onto/yso/p21546 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Developing methods for Doppler lidar to investigate atmospheric boundary layer 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lidar](http://finto.fi/yse/fi/page/Y508678)

**Comment by jarmosaarikko** [comment]
siis tässä halutaan erottaa laite ja menetelmä käsitteinä toisistaan? Ohjaustermien perusteella tämä ehdotettu käsite olisi laite valotutkat <https://www.wikidata.org/wiki/Q504027>  ja laserkeilaus <https://www.wikidata.org/wiki/Q1361664> on menetelmä, jossa laitetta käytetään.

**Comment by ilona-x** [comment]
tässä väitöksessä puhutaan lidar-tekniikasta: Environment Awareness with Hyperspectral LiDAR Technologies https://aaltodoc.aalto.fi/handle/123456789/47576 

--

Ja englanninkielisessä wikipedia-artikkelissa puhutaan menetelmästä: "Lidar is a method for measuring distances (ranging) by illuminating the target with laser light and measuring the time the reflection of the light takes to return to the sensor." 
https://en.wikipedia.org/wiki/Lidar

**Comment by fantsby-m** [comment]
Oikeinkirjoitus? LiDAR, Lidar, lidar, LIDAR - kaikkia löytyy.

**Comment by mariaforsen** [comment]
Sv. lidar 
https://svenska.se/tre/?sok=lidar&pz=1

**Comment by mirmaid** [comment]
Englanninkielinen wikipedia esittää laser scanningin laajemmin, mutta suomeksi ja (ruotsiksi?) laserkeilaus näyttää käytettävän nimenomaan mittausmenetelmästä, jolloin on - sikäli kuin saan selvää - aika päällekkäinen lidarin kanssa. 

Jos halutaan nimenomaan laitteena, niin sitten on erotettavissa.

**Comment by FinMeSHienPaimentaja** [comment]
Erään maanmittausinsinöörin mukaan ei ole ainakaan "valotutka". 

Maanmittauksessa tarkoitetaan yleensä laserkeilausta. Se voi tarkoittaa menetelmää laserkeilaus tai laitetta laserkeilain asiayhteydestä riippuen.

**Comment by mirmaid** [comment]
https://erepo.uef.fi/handle/123456789/23033

**Comment by FinMeSHienPaimentaja** [comment]
Kuten jo todettiinkin, Wikipedian mukaan näyttäisi olevan etenkin menetelmä-merkityksessä. 

"Lidar" lyhenne: 

_Lidar is an acronym of "light detection and ranging or "laser imaging, detection, and ranging"._

https://en.wikipedia.org/wiki/Lidar

https://oceanservice.noaa.gov/facts/lidar.html

**Comment by mirmaid** [comment]
Yleensä käytetään synonyymeinä, tässä erotettu, mutta ei kovin selkeä määritelmä: s. 11 https://helda.helsinki.fi/bitstream/handle/10138/42935/Laserkirja_painettu.pdf?sequence=2
