### ISSUE TITLE
suvaitsevaisuuskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8679]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suvaitsevaisuuskasvatus 

#### Perustelut ehdotukselle   

x 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9780593110416 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [suvaitsevaisuuskasvatus](http://finto.fi/yse/fi/page/Y508679)

**Comment by jarmosaarikko** [comment]
käytetty myös mm: http://www.theseus.fi/handle/10024/66120  "Suvaitsevaisuuskasvatus varhaiskasvatuksessa"

**Comment by mirmaid** [comment]
Kaksi viitettä Melindassa.

Sanastossa tälle läheisiä _arvokasvatus, asennekasvatus, eettinen kasvatus, kansainvälisyyskasvatus, tasa-arvokasvatus_.

**Comment by fantsby-m** [comment]
> Kaksi viitettä Melindassa.
> 
> Sanastossa tälle läheisiä _arvokasvatus, asennekasvatus, eettinen kasvatus, kansainvälisyyskasvatus, tasa-arvokasvatus_.

Noilla +_suvaitsevaisuus_ pääsee jo aika pitkälle

Toisaalta termiä on verkossa käytetty aika paljon, ja esim. Theseuksessa on [lähes 70 julkaisua](https://www.theseus.fi/discover?query=suvaitsevaisuuskasvatus) joissa sana esiintyy.

**Comment by mariaforsen** [comment]
Sv. toleransfostran ET toleranspedagogik
