### ISSUE TITLE
toteaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8681]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[toteaminen](http://www.yso.fi/onto/ysa/Y131567) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan käsite. 

#### Perustelut ehdotukselle   

Käytetty hyvin vähän. On merkitykseltään niin monimerkityksinn/epämääräinen, että onko kuvailussa kovinkaan ilmaisuvoimainen? YSO-ylläpidon muistiinpano vuodelta 2018: "Käytetty Melindassa 10 kertaa: 2 x kuoleman toteaminen, 2 x lukihäiriön toteaminen, kerran osteoporoosin toteaminen, 2 x mikrobien toteaminen (vain toinen lääketiedettä), kerran syyllisyyden (?) toteaminen, kerran laadun (?) toteaminen. Kerran asiasanana on "vakaumuksen toteaminen"." 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Ks. https://github.com/NatLibFi/Finto-data/issues/956

**Comment by YSO-kokous** [comment]
Poistetaan käsite
