### ISSUE TITLE
raviradat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8682]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[raviradat](http://www.yso.fi/onto/ysa/Y112589) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan LT-suhde asiasananaan "radat" --> "kilparadat" 

#### Perustelut ehdotukselle   

Raviradat ovat nimenomaan kilparatoja, eivät ratoja yleensä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kilparadat-käsitteellä ei ole muita alakäsitteitä, ei muutosta.
