### ISSUE TITLE
Euroopan unionin turvallisuus- ja puolustuspolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8684]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Euroopan unionin turvallisuus- ja puolustuspolitiikka 

#### Ehdotettu termi englanniksi   

Common Security and Defence Policy 

#### Ehdotettu termi ruotsiksi   

gemensamma säkerhets- och försvarspolitiken 

#### Vaihtoehtoiset termit ja ilmaisut   

CSDP 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Euroopan_unionin_turvallisuus-_ja_puolustuspolitiikka 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.cmcfinland.fi/wp-content/uploads/2019/10/CMC-Finland-Organized-Crime-Handbook.pdf 

**Termiehdotus Fintossa:** [Euroopan unionin turvallisuus- ja puolustuspolitiikka](http://finto.fi/yse/fi/page/Y508684)

**Comment by jtuohini** [comment]
Eikö tälle riittäisi yleistermit **[puolustuspolitiikka](http://www.yso.fi/onto/yso/p9565)** ja **[turvallisuuspolitiikka](http://www.yso.fi/onto/yso/p9566)** yhdistettynä yhteisön nimeen **[Euroopan unioni](http://urn.fi/URN:NBN:fi:au:finaf:000035482)**? Eihän sanastoon muutenkaan kai oteta vastaavasti esim. "Suomen elintarvikepolitiikka"-, "Suomen puolustuspolitiikka"-, "Suomen turvallisuuspolitiikka"-, "Suomen ulkopolitiikka"- yms. tyyppisiä asiasanoja kaikkien mahdollisten maiden ja valtioliittojen ja liittolaisryhmien osalta, vaikka kyseisiä aiheita käsittelevää aineistoa löytyy runsain mitoin.

**Comment by jarmosaarikko** [comment]
Sanastossa on kyllä ohjausterminä: "**Euroopan unionin yhteinen ulko- ja turvallisuuspolitiikka**" → [yhteinen ulko- ja turvallisuuspolitiikka](http://www.yso.fi/onto/yso/p25320) - onko tässä kyseessä (lähes) sama käsite?

**Comment by mirmaid** [comment]
Yhteinen turvallisuus- ja puolustuspolitiikka (YTPP) on osa unionin yhteistä ulko- ja turvallisuuspolitiikkaa. https://eu2019.fi/prioriteetit/kokonaisturvallisuus/turvallisuus-ja-puolustusyhteistyo

**Comment by fantsby-m** [comment]
https://op.europa.eu/en/web/eu-vocabularies/concept/-/resource?uri=http://eurovoc.europa.eu/6709&lang=fi

**Comment by fantsby-m** [comment]
Ks. myös
https://iate.europa.eu/search/standard/result/1615467677076/1
jossa ehdotettu termi on merkitty "obsolete"

**Comment by fantsby-m** [comment]
> 
> 
> Sanastossa on kyllä ohjausterminä: "**Euroopan unionin yhteinen ulko- ja turvallisuuspolitiikka**" → [yhteinen ulko- ja turvallisuuspolitiikka](http://www.yso.fi/onto/yso/p25320) - onko tässä kyseessä (lähes) sama käsite?

Lähes sama, mutta EU:ssakin omana käsitteenään:
https://op.europa.eu/en/web/eu-vocabularies/concept/-/resource?uri=http://eurovoc.europa.eu/5788&lang=fi

**Comment by fantsby-m** [comment]
Ehdotuksessa on engl. termi nykyinen EU:n termi, suom. ja ruots. vanhoja muotoja, nähtävästi

**Comment by mariaforsen** [comment]
Sv. gemensam säkerhets- och försvarspolitik, gemensamma säkerhets- och försvarspolitiken, europeisk säkerhets- och försvarspolitik, europeiska säkerhets- och försvarspolitiken

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/euroopan%20unionin%20turvallisuus-%20ja%20puolustuspolitiikka

**Comment by ilona-x** [comment]
https://www.europarl.europa.eu/factsheets/fi/sheet/159/yhteinen-turvallisuus-ja-puolustuspolitiikka
"Yhteinen turvallisuus- ja puolustuspolitiikka (YTPP) on erottamaton osa unionin yhteistä ulko- ja turvallisuuspolitiikkaa (YUTP)[1]. "

**Comment by YSO-kokous** [comment]
otetaan ohjaustermiksi  -  KÄ yhteinen ulko- ja turvallisuuspolitiikka
