### ISSUE TITLE
Puistolumikello (tai lumikello?)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8685]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Puistolumikello (tai lumikello?) 

#### Ehdotettu termi ruotsiksi   

Snödroppe 

#### Perustelut ehdotukselle   

Tarvitaan aineiston kuvailuun. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Snödroppar : en galantofil kärlekshistoria 978-91-88953-99-5 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Puistolumikello (tai lumikello?)](http://finto.fi/yse/fi/page/Y508685)

**Comment by jarmosaarikko** [comment]
Suosittelen lajitietokeskuksen käyttämää nimistöä: https://laji.fi/taxon/MX.41097  
Tieteellinen nimi: Galanthus nivalis, Yleiskieliset nimet: **puistolumikello** (suomi), snödroppe (ruotsi) , snowdrop (English, United States) . Lumikello voi olla ohjausterminä.
wikidata: https://www.wikidata.org/wiki/Q109995
