### ISSUE TITLE
hämäläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8686]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hämäläiset](http://www.yso.fi/onto/ysa/Y101761) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan asiasanan englanninkielinen muoto "residents of Häme" --> "Tavastians" 

#### Perustelut ehdotukselle   

Hämäläisyys viittaa syvemmälle kuin asuinpaikkaan, englanninkielinen muoto tarkoittaa ihan eri asiaa. Ks. myös https://en.wikipedia.org/wiki/Tavastians 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Kannatan. Termi on käytössä myös EB:ssä   https://www.britannica.com/topic/Tavastian
