### ISSUE TITLE
Pitkäkoski -- Vantaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8687]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Pitkäkoski -- Vantaa](http://www.yso.fi/onto/ysa/Y160063) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "Pitkäkoski (Helsinki ja Vantaa)" ja tarkistetaan viittausmuodot. 

#### Perustelut ehdotukselle   

Koska Pitkäkoski on Helsingin ja Vantaan rajalla, ei sitä voi sijoittaa vain toisen osaksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Paikkatietoalustalla sijainti Vantaa: http://paikkatiedot.fi/so/1000772/10012925

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8669

**Comment by mirmaid** [comment]
Suomalaisten paikkojen osalta hierarkiasuhteet noudattavat Maanmittauslaitoksen Paikannimirekisterin rakennetta. https://www.kiwi.fi/display/Finto/YSO-paikat
