### ISSUE TITLE
vastaanottokeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8688]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vastaanottokeskukset](http://www.yso.fi/onto/ysa/Y111494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "siirtolaiskeskukset" 

#### Perustelut ehdotukselle   

Tätä muotoa käytetään mediassa (ks. esim. https://www.hs.fi/ulkomaat/art-2000004633759.html, https://www.is.fi/ulkomaat/art-2000006636846.html, https://www.kansalainen.fi/lesbokselle-nousee-uusi-siirtolaiskeskus-paikalliset-vastustavat-siirtolaiset-mellakoivat/ ja https://www.skp.fi/keywords/siirtolaiskeskus), joten siitä olisi hyvä saada jonkinlainen viittausmuoto. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
