### ISSUE TITLE
Haapakangas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8689]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Haapakangas](http://www.yso.fi/onto/ysa/Y176825) 

#### Tila   

Käsittelyssä 

#### Perustelut ehdotukselle   

Käsitteellä nyt huomautus:
Historiallinen ja nykyinen seurakunta Pohjois-Inkerissä sekä myös taajama Pietarista Viipuriin vievän valtatien varrella

---

Suurin osa Melindan viitteistä näyttäisi käsittelevän Oulun (ent. Haukiputaan) Haapakangasta 

#### Ehdotettu muutos   

jaettava? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Oulun Haapakangas on "kaupunkialueen tai taajaman osa", kaupunginosa on Haukipudas (joka on vielä YSO-paikoissa itsenäisenä).
