### ISSUE TITLE
Naamijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8690]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Naamijoki](http://www.yso.fi/onto/ysa/Y110931) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

jaettava? 

#### Perustelut ehdotukselle   

Huomautus:
On sekä kylä että joki Pellossa 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Käytetty joesta, lisätty tarkenne.
