### ISSUE TITLE
Pohjolan kartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8691]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Pohjolan kartano 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Perustelut ehdotukselle   

Kartano Hartolassa
Yso-paikoissa nyt Pohjola (Hartola), jolla huomautus "Pohjola on sekä kylä että kartano Hartolassa" http://www.yso.fi/onto/yso/p109457

Pohjolan kartano käytetty Melindassa 2 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melinda 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Pohjolan kartano](http://finto.fi/yse/fi/page/Y508691)

**Comment by jtuohini** [comment]
Ei kuulu YSO:on, vaan Asteriin. Ks. Marc 21 -formaatti (https://www.loc.gov/marc/bibliographic/ambiguous-headings.html > Manors) sekä päivitetty _Establishing Certain Entities in the Name or Subject Authority File_ -ohjeistus (https://www.loc.gov/aba/publications/FreeSHM/H0405.pdf > Group Two > Manors), jonka kummankin mukaan kartanot tulee auktorisoida 110-muodossa, ei 150.

**Comment by mariaforsen** [comment]
Sv. Malmgård (Gustav Adolfs)
