### ISSUE TITLE
Kuopion lentoasema

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8692]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kuopion lentoasema 

#### Ehdotettu termi ruotsiksi   

Kuopio flygplats 

#### Ehdotettu termi englanniksi   

Kuopio Airport 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lentoasemat](http://www.yso.fi/onto/yso/p664) 

#### Vastaava käsite muussa sanastossa   

wikipedia : https://fi.wikipedia.org/wiki/Kuopion_lentoasema 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

Rissala (Siilinjärvi) -käsitteellä on nyt YSO-paikoissa huomautus:
On sekä kylä Siilinjärvellä että Kuopion lentokenttä

Lentoasema pitäisi auktorisoida erikseen YSOon tai mahdollisesti YSO-paikkoihin, jos lentoasemat päätetään siirtää sinne

Kuopion lentoasema käytetty Melindassa 4 kertaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melinda 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Kuopion lentoasema](http://finto.fi/yse/fi/page/Y508692)

**Comment by jtuohini** [comment]
Ei kuulu YSO:on eikä YSO-paikkoihin, vaan Asteriin. Ks. Marc 21 -formaatti (https://www.loc.gov/marc/bibliographic/ambiguous-headings.html > Airports) sekä päivitetty _Establishing Certain Entities in the Name or Subject Authority File_ -ohjeistus (https://www.loc.gov/aba/publications/FreeSHM/H0405.pdf > Group One > Airports), jonka kummankin mukaan lentoasemat tulee auktorisoida 110-muodossa, ei 150 eikä 151.

**Comment by jarmosaarikko** [comment]
kts. YSO lentoasemat http://www.yso.fi/onto/yso/p664

**Comment by mirmaid** [comment]
Ilmeisesti ongelma koskee kuitenkin vain Rissala-paikkakäsitettä.

**Comment by mirmaid** [comment]
Poistetaan huomautus.

**Comment by jtuohini** [comment]
Kuopion lentoasema on Kannossa, Asteri-ID 000222185.
