### ISSUE TITLE
kartanot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8694]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kartanot](http://www.yso.fi/onto/ysa/Y95910) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "moisiot (kartanot)" 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/moisio 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja muita KT-muotoja lisättäväksi: "herraskartanot", "hovit (kartanot)", "kartanorakennukset" ja "maakartanot".

**Comment by YSO-kokous** [comment]
Hyväksytty kaikki KT muodot

**Comment by jarmosaarikko** [comment]
haluaisin vielä palata tähän tapaukseen. Tässä on mielestäni kaksi käsitettä sekaisin. Jos nämä kartanot ovat (pää)rakennuksia niin mikä on sitten kartano-maatilan yläkäsite? 

Yleensähän kartanot ne ovat aika isoja ja alueellisesti merkittäviä toimijoita (ei vain rakennus).    Wikidatassa nämä ovat erikseen:
 https://www.wikidata.org/wiki/Q879050 "kartanon päärakennus",  "manor house"  joka on osa kohdetta  
 https://www.wikidata.org/wiki/Q2116450  "kartano", "manor" alias "manor estate" 
Jos nämä ovat YSOssa yhdessä käsitteessä, niin  YK pitäisi olla myös "maatilat".  

Ehdotan, että kirjataan eri käsitteiksi: 
"**kartanorakennukset**" YK **asuinrakennukset** ja  en: **manor houses**
**kartanot**  YK **maatilat**  ja en: **manors**  KT **manor estates**

Olisiko tämä ongelma kuvailun  kannalta? Käsitelläänkö näitä aina yhdessä vai myös erikseen?  Katsomissani viittauksissa ja kuvauksissa useamminoli käsittelyssä koko tila, ei vain (pää)rakennus, jotka ovat myös paljon lyhytkestoisempia.  Päärakennus voi olla purettu  tai korvattu uudella mutta tila edelleen olemassa, esim. Tammiston kartano Vantaalla.

**Comment by mirmaid** [comment]
Kuvailun kannalta tämä ei ole ongelma, ei tehdä muutoksia.
