### ISSUE TITLE
harmonikansoittajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8697]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[harmonikansoittajat](http://www.yso.fi/onto/ysa/Y105626) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "haitaristit" ja "harmonikkataiteilijat" 

#### Perustelut ehdotukselle   

Kumpaakin on käytetty ahkerasti kirjallisuudessa, tuoreeltaan esim. https://yle.fi/uutiset/3-11711089 ja esim. https://yle.fi/uutiset/3-10979607. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by YSO-kokous** [comment]
hyväksytty
