### ISSUE TITLE
Kovelanjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8699]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kovelanjärvi 

#### Vaihtoehtoiset termit ja ilmaisut   

Myllyjärvi 

#### Perustelut ehdotukselle   

https://www.jarviwiki.fi/wiki/Kovelanj%C3%A4rvi_eli_Myllyj%C3%A4rvi_(23.071.1.002) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.luvy.fi/wp-content/uploads/Julkaisu-19_2020_Lohjan-Kovelanjarven-eli-Myllyjarven-kunnostustarkastelu.pdf 

**Termiehdotus Fintossa:** [Kovelanjärvi](http://finto.fi/yse/fi/page/Y508699)

**Comment by mirmaid** [comment]
Luonnonmaantieteellisten paikkojen tarkenteet: tässä altLabelin tarkenne - Lohjalla on toinenkin Myllyjärvi. Eli laitetaanko Myllyjärvi (Lohja, Kovela)?

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10670547

**Comment by mirmaid** [comment]
KT Myllyjärvi (Kovelanjärvi)
