### ISSUE TITLE
rakennusosat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8700]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rakennusosat](http://www.yso.fi/onto/ysa/Y101677) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "rakennuksen yksityiskohdat" ja "rakennusten yksityiskohdat" 

#### Perustelut ehdotukselle   

Kirjallisuudessa käytetty näitä paljon, joten viittaussuhde ei olisi haitaksi. Terminä "rakennusosat" on hieman harhaanjohtava myös, kun puhutaan valmiin rakennuksen yksityiskohdista eikä niinkään legopalikkatyylisistä elementeistä tms, joista rakennus on kasattu. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja lisäksi voisi lisätä puuttuvan LCSH-siltauksen: [**Architecture--Details**](http://id.loc.gov/authorities/subjects/sh85006626).

**Comment by jarmosaarikko** [comment]
Rakennetun ympäristön pääsanasto    [rakennusosa ](http://uri.suomi.fi/terminology/rakymp/c66)
Määritelmä: rakennettavan tai rakennetun kohteen käsitteellisesti itsenäinen, aineellinen osa
_Talonrakennuksessa rakennusosat koostuvat [rakennustuotteista](http://uri.suomi.fi/terminology/rakymp/c65)._
Huomautus:  _Talonrakennuksessa tyypillisiä rakennusosia ovat esimerkiksi välipohjat, ulkoseinät ja vesikatot. Infrarakentamisessa tyypillisiä rakennusosia ovat esimerkiksi penkereet, teiden eri rakennekerrokset ja kallioavoleikkaukset._

Huom! YSO:ssa on vain noita talonrakennuksen käsitteitä alakäsitteinä.  Infrarakentamisen rakennusosat ovat suoraan elottomien objektien alla.  

Jos on sekaannusten vaara, niin niiden välttämiseksi voisiko lisätä sulkutarkenteen: "rakennusosat (talonrakentaminen)"   ja siirtää "rakennusosat" ohjaustermiksi?

**Comment by jtuohini** [comment]
_**Rakennustuotteet**_-asiasanalle kai olisi myös tarvetta sitten? Ehdotettu sulkutarkenne ainakin muuttaisi merkityksen juuri toiseksi kuin kattamaan rakennuksen (arkkitehtonisia) yksityiskohtia. – Merkitsevä ero on mielestäni rakennustekniikan/talonrakentamisen ja arkkitehtuurin välillä.

**Comment by fantsby-m** [comment]
> 
> 
> Rakennetun ympäristön pääsanasto [rakennusosa ](http://uri.suomi.fi/terminology/rakymp/c66)
> Määritelmä: rakennettavan tai rakennetun kohteen käsitteellisesti itsenäinen, aineellinen osa
> _Talonrakennuksessa rakennusosat koostuvat [rakennustuotteista](http://uri.suomi.fi/terminology/rakymp/c65)._
> Huomautus: _Talonrakennuksessa tyypillisiä rakennusosia ovat esimerkiksi välipohjat, ulkoseinät ja vesikatot. Infrarakentamisessa tyypillisiä rakennusosia ovat esimerkiksi penkereet, teiden eri rakennekerrokset ja kallioavoleikkaukset._
> 
> Huom! YSO:ssa on vain noita talonrakennuksen käsitteitä alakäsitteinä. Infrarakentamisen rakennusosat ovat suoraan elottomien objektien alla.
> 
> Jos on sekaannusten vaara, niin niiden välttämiseksi voisiko lisätä sulkutarkenteen: "rakennusosat (talonrakentaminen)" ja siirtää "rakennusosat" ohjaustermiksi?

Ja lisäksi 'rakennustuote' termissä on huomautus:  _Rakennustuotteita ovat esimerkiksi betonielementit, ikkunat, ovet ja sahatavara._

Eli tarvitaanko kolme termiä: rakennustuotteet, rakennusosat (jotka koostuvat rakennustuotteista) ja rakennusosat (arkkitehtuurin yksityiskohdat) - tms.? Vai kattaako _rakennusosat_ molemmat jälkimmäiset?

**Comment by mirmaid** [comment]
Sanastossa on myös _rakennusaineet_ (KT rakennusmateriaalit), _rakennuselementit_ ja _rakenteet (rakentaminen)_. Varmaan mikään YSOn käsite ei suoraan sovi vastineeksi arkkitehtuurin yksityiskohdille, mutta jos sitä halutaan omana käsitteenään, kaipaisin jotain esimerkkiaineistoa vähän helpottamaan pohdintaa.

**Comment by ilona-x** [comment]
ICONCLASS-luokitus: 
arkkitehtoniset yksityiskohdat https://finto.fi/ic/fi/page/48C16
ALAKÄSITTEET
    48C164 constructive (architectural) parts ~ human beings
    48C162 kaari, arkkivoltti ~ arkkitehtuuri
    48C165 mouldings ~ architecture
    48C168 other architectural details
    48C167 pavement, floor ~ architecture
    48C163 pylväsjärjestelmät ~ arkkitehtuuri
    48C161 pylväs, pilari ~ arkkitehtuuri
    48C166 surface decorations ~ architecture

**Comment by YSO-kokous** [comment]
Otetaan sanastoon "arkkitehtoniset yksityiskohdat", Ehkä KT  yksityiskohdat (arkkitehtuuri)

**Comment by mariaforsen** [comment]
Sv. arkitektoniska detaljer
