### ISSUE TITLE
venesatamat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8701]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[venesatamat](http://www.yso.fi/onto/ysa/Y104281) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "marinat" 

#### Perustelut ehdotukselle   

Venesatamaa nimitetään myös marinaksi (ks. esim. https://fi.wikipedia.org/wiki/Marina_(t%C3%A4smennyssivu)), ja viittausmuoto olisi jälleen paikallaan, jotta kuvailussa käytettävä löytyisi helposti. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
on jo KT "marinor"@sv ja "marinas"@en, niin miksei sitten "marinat"@fi
Mutta: vrt. myös marina - jupina, napina, nurina

**Comment by fantsby-m** [comment]
lisätään KT marinat (venesatamat), niin vältetään jupinat?
