### ISSUE TITLE
toimitalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8702]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

toimitalot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[toimitilat](http://www.yso.fi/onto/yso/p6919) 
[liikerakennukset](http://www.yso.fi/onto/yso/p15074) 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/toimitalo 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/015729367 ym. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [toimitalot](http://finto.fi/yse/fi/page/Y508702)

**Comment by jarmosaarikko** [comment]
on laajalti käytössä  [Wikisanakirjan ](https://fi.wiktionary.org/wiki/toimitalo) määritelmä: "yrityksen tai laitoksen työntekijöiden työskentelypaikkana toimiva rakennus"  en: "office building" -- toisaalta Wiktionaryn "[office building](https://en.wiktionary.org/wiki/office_building)"  termille on pantu suomenkieliset vastineet "toimistotalo", "toimistorakennus"

Wikidatassa "**toimitalo**" on terminä käsitteelle: [Q47012103](https://www.wikidata.org/wiki/Q47012103)  "**mixed-use building**"

Toisaalta Wikidatassa on myös: [Q1021645](https://www.wikidata.org/wiki/Q1021645) "toimistorakennus" KT "virastorakennus", "konttori", "toimistotalo" EN  "office building".
Samoin TEPA:ssa terminä  [toimistotalo](https://termipankki.fi/tepa/fi/haku/toimistotalo),  sv "kontorsbyggnad", en "office building"
Jos ja kun nämä ovat synonyymejä, niin ehdotan "toimitalot" ohjaustermiksi käsitteelle "[toimistorakennukset](http://www.yso.fi/onto/yso/p472)"

**Comment by mirmaid** [comment]
Kerran Melindassa. Entä ohjaustermiksi _toimitilat_-käsitteelle?

**Comment by mariaforsen** [comment]
Yllä mainitut ohjaukset ok (mutta ei erillisenä terminä)

**Comment by YSO-kokous** [comment]
Hyväksytään  toimitalot KÄ toimitilat
