### ISSUE TITLE
julkiset käymälät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8703]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

julkiset käymälät 

#### Ehdotettu termi englanniksi   

public toilets 

#### Ehdotettu termi ruotsiksi   

offentliga toaletter 

#### Vaihtoehtoiset termit ja ilmaisut   

julkiset vessat 
julkiset WC:t 
yleiset käymälät 
yleiset vessat 
yleiset WC:t 
yleisövessat 
yleisö-WC:t 

#### Ehdotettu yläkäsite YSOssa (LT)   

[julkiset tilat](http://www.yso.fi/onto/yso/p494) 
[käymälät](http://www.yso.fi/onto/yso/p3060) 
[yleisötilat](http://www.yso.fi/onto/yso/p15531) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85108627> 
Wikidata : https://www.wikidata.org/wiki/Q813966 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/004884980, https://melinda.kansalliskirjasto.fi/byid/006780305, https://melinda.kansalliskirjasto.fi/byid/007033742 ym. 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [julkiset käymälät](http://finto.fi/yse/fi/page/Y508703)

**Comment by LeKorsu** [comment]
Käymälä vaan kuulostaa nykyaikana kovin vanhanaikaiselta. Tietävätkö millenniaalit mitä se tarkoittaa? (tiedän että käymälät on käytössä oleva termi sanastossa)

**Comment by jarmosaarikko** [comment]
> Käymälä vaan kuulostaa nykyaikana kovin vanhanaikaiselta. Tietävätkö millenniaalit mitä se tarkoittaa? (tiedän että käymälät on käytössä oleva termi sanastossa)
käymälä, vessa vai wc?   
google-tilastoa: käymälä 0,9 milj. vessa 1,5 milj., julkinen käymälä 34 t., julkinen vessa  53 t. julkinen wc 154 t.
mielestäni ei tarvitse vaihtaa

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa "yleiset käymälät"

**Comment by mariaforsen** [comment]
Sv. allmänna toaletter ET offentliga toaletter, allmänna wc/wc:n, offentliga wc/wc:n
