### ISSUE TITLE
urheilukilpailut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8704]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[urheilukilpailut](http://www.yso.fi/onto/ysa/Y99904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "kisat" ja "urheilukisat" 

#### Perustelut ehdotukselle   

Ovat synonyymejä (https://www.kielitoimistonsanakirja.fi/kisa ja https://www.kielitoimistonsanakirja.fi/urheilukisat). 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Pitäisikö kisat olla ennemmin _kilpailut_-käsitteen ohjaustermi?

**Comment by YSO-kokous** [comment]
Hyväksytään urheilukilpailiut KT urheilukisat sekä  kilpailut KT kisat
