### ISSUE TITLE
pinnan karkeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8706]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pinnan karkeus 

#### Ehdotettu termi englanniksi   

Surface roughness 

#### Vaihtoehtoiset termit ja ilmaisut   

pinnankarheus 
pinnankarkeus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fysikaaliset ominaisuudet](http://www.yso.fi/onto/yso/p1174) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85130724> 
Wikipedia : https://en.wikipedia.org/wiki/Surface_roughness 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Seasonal snow surface roughness and albedo  	http://hdl.handle.net/10138/301140 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [pinnan karkeus](http://finto.fi/yse/fi/page/Y508706)

**Comment by mirmaid** [comment]
Käytetty hyvin monenlaisista pinnoista, ei liene ongelma?

**Comment by mariaforsen** [comment]
Minkälainen suhde tähän Surface finish https://en.wikipedia.org/wiki/Surface_finish
"Ytfinhet är ett mått eller karaktären på en ytas släthet eller grovhet. Ytfinhet består i sin tur av tre olika delar: våghet, ytjämnhet och bearbetningens upplägg."

**Comment by jarmosaarikko** [comment]
Q3439090 | - | surface finish | small, local deviations of a surface from a perfectly flat ideal | Alias: surface textures, surface topography 
Q1282856 | - | Surface finish | Surface finish, also known as surface texture or surface topography, is the nature of a surface as defined by the three characteristics of **lay**, **surface roughness**, **and waviness**. | Alias: Surface topography

Q114817 | pinnan karheus | surface roughness | component of surface texture | alias: roughness -- **tämä on suure**
Tuon perusteella tämä olisi ruotsiksi "**ytjämnhet**" ja on siis osa "surface finish" käsitettä. Tarvitaanko molemmat?

**Comment by YSO-kokous** [comment]
Hyväksytään pinnan karkeus, surface roughness

**Comment by mariaforsen** [comment]
Sv. ytjämnhet https://termipankki.fi/tepa/fi/haku/surface%20roughness
