### ISSUE TITLE
kalmistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8707]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kalmistot](http://www.yso.fi/onto/ysa/Y95793) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "arkeologiat hauta-alueet" 

#### Perustelut ehdotukselle   

Kyseistä ilmausta käytetty jonkin verran, joten siitä olisi hyvä saada viittaus sanastossa jo olevaan muotoon. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
KT-muodoksi tietysti siis "arkeologiset hauta-alueet"!

**Comment by mirmaid** [comment]
Kerran Googlella. MAOsta löytyy laajempi _hauta-alueet_.

**Comment by fantsby-m** [comment]
> 
> 
> Kerran Googlella. MAOsta löytyy laajempi _hauta-alueet_.

Yksikössä ("arkeologinen hauta-alue") 88 tulosta Googlella - tosin niistä surin osa näyttää vievän samaan paikkaan.

**Comment by YSO-kokous** [comment]
Ei lisätä.
