### ISSUE TITLE
satamalaiturit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8708]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

satamalaiturit 

#### Ehdotettu termi englanniksi   

wharfs 

#### Ehdotettu termi ruotsiksi   

kajer (jokin sopiva lisämääre) 

#### Vaihtoehtoiset termit ja ilmaisut   

quays [eng] 

#### Assosiatiiviset (RT)   

[satamat](http://www.yso.fi/onto/yso/p11027) 
[laiturit](http://www.yso.fi/onto/yso/p13299) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q828909 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

Tarkkaa asiasanaa ei ole ennestään sanastossa ("laiturit" selvästi eri asia), mutta aineistoa on jonkin verran (kirjallisuutta ja puutteellisesti kuvailtuja kuvia vielä enemmän). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000969470, https://melinda.kansalliskirjasto.fi/byid/006778719, https://melinda.kansalliskirjasto.fi/byid/013176924 ym. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [satamalaiturit](http://finto.fi/yse/fi/page/Y508708)

**Comment by mariaforsen** [comment]
Pir=pistolaituri sanakirjoissa..

**Comment by fantsby-m** [comment]
Englanniksi ottaisin mieluummin termiksi _quay_ ja _wharf_ sitten vaihtoehtoiseksi (edit. tai sitten kuten ehdotuksessa, jotta menee samalla tavalla kuin LCSH:ssa). _Pier_ taas voi olla erillinen laituri tai osa satamalaituria, en tiedä onko se ongelma. 

Erityisesti Britanniassa tyypillinen _pier_ (https://en.wikipedia.org/wiki/List_of_piers_in_the_United_Kingdom) taas ei olisi suomeksi satamalaituri vaan varmaankin vain laituri - tai _kävelylaituri_ (kuten MOT-sanakirjassa)?

**Comment by mirmaid** [comment]
![image](https://user-images.githubusercontent.com/10060845/110917611-c1e3f180-8322-11eb-82a4-1c944bfdbee9.png)

**Comment by fantsby-m** [comment]
LCSH:ssa on [_wharves_ ](https://id.loc.gov/authorities/subjects/sh85146364.html), siinä variantteina quays ja wharfs. [_Piers_ ](https://id.loc.gov/authorities/subjects/sh85102058.html)on omana terminään, ja niinhän se YSOssakin on, _laiturin_ engl. versiona. Kuvailussa voinee tarvittaessa sitten käyttää jompaa kumpaa tai molempia?

**Comment by jarmosaarikko** [comment]
Tuo Mirjan postaama nelitaulu on hieno, mutta termejä käytetään tosi laajasti ristiin. 
Jos määriteltäisiin 2-3 käsitettä, niin ehdotan:
a) **satamalaiturit**  (rannansuuntaiset laiturit)
käytettävä termi: wharves | kaj | satamalaiturit
ohjaustermit: quays | bryggor  |

b) **pistolaiturit** (rannasta ulkonevat laiturit)
käytettävä termi:  piers | pirer | laivalaiturit
ohjaustermit: jetties |  utskutjande bryggor | pistolaiturit, aallonmurtajat

**Comment by mirmaid** [comment]
^ Muuten ihan hyvä ehdotus, mutta myös _satamalaiturit_ saatetaan käyttää esim. venesataman laitureista, jotka eivät ole rannan myötäisiä, onko ongelma? Ja toisaalta, onko tässä ehdotuksessa tarkoitus poistaa kokonaan pelkät _laiturit_, vai muuttaa se pistolaitureiksi?

**Comment by mariaforsen** [comment]
Sv. hamnkajer 
https://svenska.se/tre/?sok=hamnkaj&pz=1 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_5ce1922b5b7878e5cba0226e75e43991&list_id=1&keyword=satamalaituri&word=satamalaituri
