### ISSUE TITLE
suun ja kasvojen granulomatoosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8709]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suun ja kasvojen granulomatoosi 

#### Ehdotettu termi englanniksi   

Orofacial Granulomatosis 

#### Vaihtoehtoiset termit ja ilmaisut   

orofasiaalinen granulomatoosi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[suun sairaudet](http://www.yso.fi/onto/yso/p28933) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D051261> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Oral manifestations in Crohn´s disease and orofacial granulomatosis 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suun ja kasvojen granulomatoosi](http://finto.fi/yse/fi/page/Y508709)

**Comment by mariaforsen** [comment]
Sv. orofacial granulomatos

**Comment by jarmosaarikko** [comment]
Ei ole LCSH eikä wikidatassa
