### ISSUE TITLE
monitoimihallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8712]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[monitoimihallit](http://www.yso.fi/onto/ysa/Y118882) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "areenat (monitoimihallit)" ja "monitoimiareenat" 

#### Perustelut ehdotukselle   

Nimityksiä areena ja monitoimiareena käytetään yleisesti. Edellinen useiden monitoimihallien nimissä (Barona Areena, Elysée Areena, Espoo Metro Areena, Hartwall Areena, Hartwall Arena), joten viittausmuodolle on tilausta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja viittausmuoto areenat-sanasta kaivannee sulkutarkenteen, ettei käsitteenä sekoitu areena-sanan nimissään sisältäviin tapahtumiin (Suomi-areena ym.)

**Comment by YSO-kokous** [comment]
Hyväksytty
