### ISSUE TITLE
kylpylät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8715]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kylpylät](http://www.yso.fi/onto/ysa/Y102884) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "viihdekylpylät" 

#### Perustelut ehdotukselle   

Ks. huomautus: https://melinda.kansalliskirjasto.fi/byid/013903225. Viittausmuoto voisi toisaalta olla myös asiasanaan "kylpylähotellit", jotka ovat vielä selvemmin viihdekylpylöitä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään
