### ISSUE TITLE
roomalaiset kylpylät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8716]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

roomalaiset kylpylät 

#### Ehdotettu termi englanniksi   

Roman baths 

#### Ehdotettu termi ruotsiksi   

termer (badanläggningar) 

#### Vaihtoehtoiset termit ja ilmaisut   

termit (kylpylät) [fin] 
Roman public baths [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kylpylät](http://www.yso.fi/onto/yso/p8541) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh99013339> 
Wikidata : https://www.wikidata.org/wiki/Q6581615 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 
[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [roomalaiset kylpylät](http://finto.fi/yse/fi/page/Y508716)

**Comment by mariaforsen** [comment]
Sv. romerska bad, myös SAOssa https://id.kb.se/term/sao/Romerska%20bad
