### ISSUE TITLE
pakkahuoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8717]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pakkahuoneet 

#### Ehdotettu termi ruotsiksi   

packhus 

#### Vaihtoehtoiset termit ja ilmaisut   

tulli- ja pakkahuoneet [fin] 
tull- och packhus [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset käyttötarkoituksen mukaan](http://www.yso.fi/onto/yso/p493) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q11886456 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Finnassa yli tuhat osumaa sanalla pakkahuone (https://finna.fi/Search/Results?lookfor=pakkahuone&type=AllFields), eikä sopivaa asiasanaa ole sanastossa! 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Tarkoitusta täsmentävä selite   

Ks. esim. https://fi.wikipedia.org/wiki/Pakkahuone 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [pakkahuoneet](http://finto.fi/yse/fi/page/Y508717)

**Comment by ilona-x** [comment]
MAO: 
tullirakennukset  http://www.yso.fi/onto/mao/p7595
ST    pakkahuoneet
ST    tullihuoneet
ST    tullimakasiinit

**Comment by YSO-kokous** [comment]
hyväksytty ohjausterminä KÄ tullirakennukset

**Comment by mariaforsen** [comment]
Sv. tullbyggnader ET tullhus, tullmagasin, packhus
