### ISSUE TITLE
tullikamarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8718]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tullikamarit 

#### Ehdotettu termi englanniksi   

customhouses 

#### Ehdotettu termi ruotsiksi   

tullhus 

#### Vaihtoehtoiset termit ja ilmaisut   

tulli- ja pakkahuoneet [fin] 
tull- och packhus [swe] 
tullitalot [fin] 
tullhus [swe] 
tullihuoneet [fin] 
custom houses [eng] 
customs houses [eng] 
customshouses [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset käyttötarkoituksen mukaan](http://www.yso.fi/onto/yso/p493) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh88004487> 
Wikidata : https://www.wikidata.org/wiki/Q218653 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Finnassa tuhansia osumia tullikamari-sanalla haettaessa, mutta sanastosta ei löydy täsmällistä asiasanaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [tullikamarit](http://finto.fi/yse/fi/page/Y508718)

**Comment by ilona-x** [comment]
MAO: 
tullirakennukset  http://www.yso.fi/onto/mao/p7595
ST    pakkahuoneet
ST    tullihuoneet
ST    tullimakasiinit

**Comment by mirmaid** [comment]
Kerran monikossa, 4 kertaa yksikössä (tietystä rakennuksesta).

**Comment by jarmosaarikko** [comment]
KÄ **tullirakennukset**  KT  tullikamarit, pakkahuoneet, tullihuoneet, tullimakasiinit
LCSH: **Customhouses** http://id.loc.gov/authorities/subjects/sh88004487
Wikidata: **customs house** https://www.wikidata.org/wiki/Q218653 | tullikamari alias: tullitalo, tullihuone
sv: tullhus  KT packhus, tullkammare, tullmagasin

**Comment by YSO-kokous** [comment]
Hyväksytään **tullirakennukset** KT tullikamarit, pakkahuoneet, tullihuoneet, tullimakasiinit

**Comment by mariaforsen** [comment]
Sv. tullbyggnader ET tullkammare, packhus, tullhus, tullmagasin
