### ISSUE TITLE
kokouskeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8719]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kokouskeskukset 

#### Ehdotettu termi englanniksi   

convention centers 

#### Ehdotettu termi ruotsiksi   

mötescentrum / mötescentra ? 

#### Vaihtoehtoiset termit ja ilmaisut   

konferenssikeskukset [fin] 
kongressikeskukset [fin] 
conference centers [eng] 
conference centres [eng] 
congress centers [eng] 
congress centres [eng] 
kongresshaller [swe] 
konferenshaller [swe] 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset käyttötarkoituksen mukaan](http://www.yso.fi/onto/yso/p493) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85031685> 
Wikidata : https://www.wikidata.org/wiki/Q1378975 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Perustelut ehdotukselle   

Yli tuhat osumaa Finnassa yksistään kongressikeskus-sanalla haettaessa, mutta sopiva asiasana puuttuu 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kokouskeskukset](http://finto.fi/yse/fi/page/Y508719)

**Comment by mirmaid** [comment]
Melindassa kerran _kongressikeskukset_, kerran _konferenssirakennukset_.

Sanastossa on _kongressitalot_ ja _kokoustilat_, eli voisi myös lisätä ohjaustermejä.

**Comment by YSO-kokous** [comment]
Otetaan ohjausterminä konferenssikeskukset KÄ kongressitalot, kongressikeskukset KÄ kongressitalot

**Comment by mariaforsen** [comment]
Sv. konferenscentrum/center, kongresscentrum ANV kongresshus

**Comment by jtuohini** [comment]
Meniköhän tämä nyt ihan oikein YSO:on? Nimittäin siellä on nyt varsinaisena asiasanana [**kongressitalot**](http://www.yso.fi/onto/yso/p4950), vaikka kyseinen nimitys viittaa ennemmin eduskuntaa vastaavan kongressin kokousrakennukseen kuin (kaupalliseen) kokouskeskukseen eli konferenssikeskukseen eli kongressikeskukseen. Vrt. esim. https://fi.wikipedia.org/wiki/Yhdysvaltain_kongressitalo ja googlailu "kongressitalo"- ja muilla mainituilla sanoilla. – Ja YSO:ssa on kuitenkin erikseen myös [**parlamenttitalot**](http://www.yso.fi/onto/yso/p39094)…

**Comment by ilona-x** [comment]
fi        kongressitalo
sv       kongresshus n
en      congress building
määritelmä
kulttuurirakennus, jossa järjestetään kongresseja
huomautus
Rakennusluokitus 2018: luokka 0710
Lähde:  Rakennetun ympäristön sanasto (2020)
https://termipankki.fi/tepa/fi/haku/kongressitalo

**Comment by jtuohini** [comment]
Koska "kongressitalo"-sanaa kuitenkin käytetään viittaamaan sekä kokouskeskuksiin että parlamenttitaloihin, olisi selkeämpää valita asiasanaksi sellainen, joka jo heti kättelyssä kertoisi, kummasta on kyse. Ainakin itselleni Googlen kuvahaku "kongressitalo"-sanalla tuottaa aika dominoivasti jälkimmäistä merkitystä vastaavia kuvia (Washington ykkösenä, kärkipäässään myös Brasília ja muutama Yhdysvaltain osavaltiopääkaupunki). Eli olen edelleen sitä mieltä, että ratkaisua pitäisi ehkä miettiä uudelleen kaikenlaisen sekaannuksen välttämiseksi.

**Comment by jarmosaarikko** [comment]
Ongelma ei ole siis kongressikeskuksissa, vaan kongressitaloissa, joka voi viitata joidenkin maiden parlamentin (kongressin) rakennukseen.

Emme voi mitään sille, että **congress** -- viittaa sekä parlamentteihin että muihin kokouksiin : [Merriam-Webster](https://www.merriam-webster.com/dictionary/congress)  ja vastaavasti ko. rakennukset.  
Aivan vastaavasti Kielitoimiston sanakirja antaa molemmat merkitykset termille [kongressi](https://www.kielitoimistonsanakirja.fi/#/kongressi?searchMode=all). SIellä on myös termi "kongressihotelli".

Mielestäni suomen kielessä konferenssi ja kongressi käsitteitä käytetään täysin ristiin eli ovat yhdeltä merkitykseltään ekvivalentteja.

En näe muutosta tapreellisena.  
Enintään voisiko "kongressitalot" ollla ohjausterminä käsitteelle "parlamenttitalot", vaikka se on myös eri käsitteen suositeltava termi?

**Comment by jtuohini** [comment]
Ihannetilanne olisi kaksi asiasanaa: 1) **parlamenttitalot**, KT _kongressitalot (parlamenttitalot)_, ja 2) **kokouskeskukset**, KT _konferenssikeskukset_, _kongressikeskukset_, _kongressitalot (kokouskeskukset)_. Kuuluisiko _kongressihotellit_ jälkimmäisen KT-muodoksi, on tietysti hyvä kysymys.

**Comment by mirmaid** [comment]
^ Vaikka "suomenkielinen" päätermi olisikin mukava, _kongressikeskukset_ on selvästi käytetympi kuin _kokouskeskukset_. Tässä muodossa sekaantumisen vaaraa tuskin on?

**Comment by YSO-kokous** [comment]
hyväksytään ohjaustermiksi. Päätermin muutos kongressikeskukset KT kokouskeskukset
