### ISSUE TITLE
Kuhmoinen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8720]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuhmoinen](http://www.yso.fi/onto/ysa/Y94230) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kuhmoinen kuuluu v. 2021 alusta Pirkanmaahan 

#### Perustelut ehdotukselle   

https://www.ely-keskus.fi/-/tervetuloa-pirkanmaalle-kuhmoinen-pirkanmaa-

Huom. Jämsän seutukunnan tilanne
"Kuhmoinen Jämsän seutukunnasta Tampereen seutukuntaan. Jämsän seutukunta saatetaan lakkauttaa, sillä Jämsä jäisi muuten sen ainoaksi kunnaksi." Lähde: https://fi.wikipedia.org/wiki/Suomen_seutukunnat#Muutokset_1.1.2021 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
Lisäksi: 

- "Etelä-Savosta siirtyy **Joroinen** Pohjois-Savoon ja **Heinävesi** Pohjois-Karjalaan"  https://yle.fi/uutiset/3-11675073
- "2021 alusta alkaen **Isokyrö** liittyy Etelä-Pohjanmaan maakuntaan."  https://yle.fi/uutiset/3-11646223
- "**Iitti** siirtyy Kymenlaakson maakunnasta Päijät-Hämeeseen 1.1.2021" https://www.iitti.fi/iitti-siirtyy-kymenlaakson-maakunnasta-paijat-hameeseen-112021

**Comment by ilona-x** [comment]
Millainen huomautus näihin tehdään, ja jätetäänkö entinen maakunta RT-suhteeksi tmv.?

**Comment by mirmaid** [comment]
Kuhmoinen kuului vuoteen 2020 asti Keski-Suomen maakuntaan. RT Keski-Suomi.
