### ISSUE TITLE
sukupuolierottelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8722]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sukupuolierottelu 

#### Ehdotettu termi ruotsiksi   

könssegregation 

#### Ehdotettu termi englanniksi   

sex segregation/separation 

#### Vastaava käsite muussa sanastossa   

SAO : https://id.kb.se/term/sao/K%C3%B6nssegregation 
Wikipedia: https://fi.wikipedia.org/wiki/Sukupuolierottelu

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

Vai liittyykö jo YSOssa oleviin termeihin sukupuolittuminen, sukupuolisyrjintä jne.? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sex segregation in sports : why separate is not equal / Adrienne N. Milner and Jomills Henry Braddock II. 

**Termiehdotus Fintossa:** [sukupuolierottelu](http://finto.fi/yse/fi/page/Y508722)

**Comment by jtuohini** [comment]
Vrt. YSO:ssa _rotuerottelu_ KÄ **apartheid** ja **rotusyrjintä**. Mainittu esimerkkikirja on Kongressin kirjastossa kuvailtu mm. asiasanalla **Sex discrimination in sports** ja laitettu hyllyluokkaan GV706.32 eli "Recreation. Leisure—Sports—Philosophy. Relation to other topics—Relation to race and discrimination". – Jotenkin tuntuu äkkiseltään siltä, että voisi ehkä YSO:ssa lisätä _sukupuolierottelun_ KT-muodoksi ainakin mainitulle **sukupuolisyrjintä**-asiasanalle.

**Comment by mirmaid** [comment]
Ei Melindassa. Mielestäni ohjaus syrjintään ei tässä kuitenkaan ole ihan toimiva, koska peruste erottelulle on vain osittain verrattavissa apartheidiin - vaikka ei nykynäkökulmasta olekaan välttämättä perusteltu tai ongelmaton.

**Comment by mirmaid** [comment]
Ei Melindassa, mutta voisi kyllä puoltaa paikkaansa myös erikseen. Vaikka nykynäkökulmasta sukupuolierottelu esim. koululiikunnassa nähdään enenevästi turhana/haitallisena, sen tarkoitus ei varmasti ole ollut syrjiä tyttöjä (ei myöskään erillisten vessojen ym.). Jotkut erottelun muodot toki ovat alun perinkin selkeämmin syrjiviä.

**Comment by mariaforsen** [comment]
Joo ei tähän oikein käy -syrjintä, siitä ei nyt ole kysymys. Kannatan erillisenä.

**Comment by AuHo22** [comment]
Tasa-arvosanastossa **Sukupuolen mukainen segregaatio** : 
https://thl.fi/fi/web/sukupuolten-tasa-arvo/sukupuoli/tasa-arvosanasto 

_Segregaatio tarkoittaa eriytymistä, eriyttämistä tai eristämistä. Sukupuolen mukainen segregaatio liittyy useimmiten työelämään tai koulutukseen ja tarkoittaa töiden, tehtävien ja koulutusalojen eriytymistä naisten ja miesten aloiksi ja töiksi. Työmarkkinoiden ja koulutuksen segregaatio on Suomessa erittäin jyrkkää. Horisontaalinen (aloihin liittyvä) ja vertikaalinen (asemiin liittyvä) segregaatio erotellaan usein toisistaan._

Itse vierastan -erottelu-sanaa (vaikka sitä käytetäänkin) ja toivoisi että löytyisi jokin muu, koskapa kuten aiemmin mainittu, konnotaatiota syrjintään on.

**Comment by jarmosaarikko** [comment]
YSOssa on "segregaatio".  Voisi olla sen alakäsitteenä "sukupuolisegregaatio".  
Mutta onko tällä merkityseroa käsitteeseen "sukupuolierottelu"?

**Comment by mirmaid** [comment]
Pikavilkaisulla _sukupuolen mukainen segregaatio_ on käytetty viittaamaan hiukan eri asiaan: https://thl.fi/fi/web/sukupuolten-tasa-arvo/tasa-arvon-tila/koulutus-ja-kasvatus/koulutuksen-sukupuolen-mukainen-segregaatio (=sukupuolittuminen).

**Comment by ilona-x** [comment]
liikunnan opetuksen yhteydessä näytetään käytettävän termiä erillisopetus, jota myös ehdotettu YSOon: erillisopetus #1754

**Comment by AuHo22** [comment]
Sukupuolittuminen-termin ohjaustermeissä on huolettomasti tämä aktiivinen / passiivinen -ero jätetty pois, tehdäänkö segregaatiota tietoisesti vai onko se tiedostamattomampi rakenteellinen kysymys.
