### ISSUE TITLE
piirustukset (taide)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8723]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[piirustukset (taide)](http://www.yso.fi/onto/ysa/Y234005) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Aineiston muotona

**Comment by jtuohini** [comment]
Viitattaisiinko tällä piirustuksiin manifestaatioina eli konkreettisina uniikkeina piirustuksina sellaisenaan? Eikä termiä käytettäisi siis esimerkiksi piirustuksia esittelevien kirjojen kuvailuun? Teos–manifestaatio-jaotteluun liittyvistä ratkaisuista SLM:ssä vrt. esim. **[julisteet](http://urn.fi/URN:NBN:fi:au:slm:s1329)** ja **[postikortit](https://finto.fi/slm/fi/page/s1207)**.

**Comment by jtuohini** [comment]
LCGFT-siltaus: [**Drawings**](http://id.loc.gov/authorities/genreForms/gf2017027231).

**Comment by jtuohini** [comment]
Lisätään **_kuvateokset_**-termille KT-muoto _valokuvakirjat_.

**Comment by mirmaid** [comment]
Tehdäänkö Jaakon ehdottama linkitys, joka olisi tässä tapauksessa broader match? - Ok

**Comment by mirmaid** [comment]
^^ Lisätäänkö KT-muoto YSOon?

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2806
