### ISSUE TITLE
Laki julkisen hallinnon tiedonhallinnasta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8724]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Laki julkisen hallinnon tiedonhallinnasta 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-14-3963-6 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Laki julkisen hallinnon tiedonhallinnasta](http://finto.fi/yse/fi/page/Y508724)

**Comment by jtuohini** [comment]
Jatkossa olisi varmaan hyvä tehdä säädöksistä ym. teosauktoriteettitietueet asiasana-auktoriteettitietueiden sijaan ja auktorisoitujen hakumuotojensa osalta noudattaa RDA:n luvun 6.29.1 ohjeistusta. Tämäkään ei RDA:n puitteissa kuuluisi 650-kenttään, vaan 610-kenttään, kaiketikin muodossa "610 14 |a Suomi. |t Laki julkisen hallinnon tiedonhallinnasta."

**Comment by mariaforsen** [comment]
Sv. lag om informationshantering inom den offentliga förvaltningen
