### ISSUE TITLE
mahajana

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8725]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mahajana 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Mahajana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Finding the Heart Sutra : guided by a magician, an art collector and Buddhist sages from Tibet to Japan 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [mahajana](http://finto.fi/yse/fi/page/Y508725)

**Comment by jtuohini** [comment]
LCSH-vastine **[Mahayana Buddhism](http://id.loc.gov/authorities/subjects/sh85079842)**. KT-muodoksi ainakin _suuri vaunu (buddhalaisuus)_. – Samalla varmaan **zenbuddhalaisuus**-asiasanan LT-suhde muutettaneen **buddhalaisuus** --> **_mahajana_**.

**Comment by mirmaid** [comment]
2 viitettä Melindassa, kerran _mahajana buddhalaisuus._

**Comment by jarmosaarikko** [comment]
Nuo buddhalaisuuden pääsuunnat ja niiden alaryhmät (lamalaisuus ja zenbuddhalaisuus) voivat olla suoraan buddhalaisuuden alla. Tai pitäisikö olla buddhalaisuuden alla kaikki kolme buddhalaisuuden päähaaraa (Theravāda, Mahāyāna sekä Vajrayāna), ja sitten niiden alla nuo alahaarat (vajrayana -> lamalaisuus, mahayana -> zenbuddhalaisuus)?   LCSH:ssa [buddhism](http://id.loc.gov/authorities/subjects/sh85017454) alla on pitkä joukko erilaisia käsitteitä. Nämä päähaarat ovat myös käsitteen "buddhist sects" alla.  [Hinayana Buddhism](http://id.loc.gov/authorities/subjects/sh85060865), [Mahayana Buddhism](http://id.loc.gov/authorities/subjects/sh85079842), [Theravāda Buddhism](http://id.loc.gov/authorities/subjects/sh85134734)

Finna.fi  mahayana: 296 kpl, hinayana 40, theravada 193 - puoltaisi kaikkien kolmen päähaaran lisäämistä omina käsitteinään.

**Comment by YSO-kokous** [comment]
Hyväksytty.  Lisätä buddhalaisuuden kaikki kolme päähaaraa, mutta tarkistetaan suomenkieliset kirjoitusasut.

**Comment by mariaforsen** [comment]
Sv. 
-mahayana https://id.kb.se/term/sao/Mahayana
-hinayana https://id.kb.se/term/sao/Hinayana
-theravada https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/theravada

SAOssa myös https://id.kb.se/term/sao/Vajrayana = Tantric Buddhism (LCSH)
https://fi.wikipedia.org/wiki/Vajrayana
