### ISSUE TITLE
rollaattorit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8726]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rollaattorit](http://www.yso.fi/onto/ysa/Y336483) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodoksi "pyörälliset kävelytelineet" 

#### Perustelut ehdotukselle   

Välineen kyseinen, virallinen nimitys olisi hyvä saada viittausmuodoksi. Ks. esim. https://www.pieksamaki.fi/wp-content/uploads/Apuvälineiden_saatavuusperusteet-apuvälineryhmittäin-1.pdf > kohta 1206. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään
