### ISSUE TITLE
virtsarakkosyöpä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8729]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[virtsarakkosyöpä](http://www.yso.fi/onto/ysa/Y113561) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi ohjaustermi: virtsarakon kasvaimet? 

#### Perustelut ehdotukselle   

Mesh: virtsarakon kasvaimet

**Comment by mirmaid** [comment]
Virtsarakon kasvain ei välttämättä ole pahanlaatuinen.

**Comment by fantsby-m** [comment]
> 
> 
> Virtsarakon kasvain ei välttämättä ole pahanlaatuinen.

Eli virtsarakon kasvaimet omaksi termikseen [kasvainten](https://finto.fi/yso/fi/page/p2299) alle?

**Comment by ilona-x** [comment]
FinMeSH: virtsarakon kasvaimet KT virtsarakkosyöpä http://www.yso.fi/onto/mesh/D001749

Tästä kasvain/syöpä ja hyvälaatuinen/pahalaatuinen -asiasta keskusteltiin viimeksi tässä issuessa: https://github.com/Finto-ehdotus/YSE/issues/8561

**Comment by mirmaid** [comment]
^ Lähinnä mietin, että ohjaus virtsarakon kasvaimista olisi tässä tapauksessa laajemmasta suppeampaan, eli vähän ongelmallinen.

**Comment by YSO-kokous** [comment]
Ei lisätä ohjaustermiä
