### ISSUE TITLE
kuormat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8730]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuormat](http://www.yso.fi/onto/ysa/Y96564) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne: kuormat (kuljetus)? 

#### Perustelut ehdotukselle   

Näin saataisiin merkitys selkeäksi, ja ruotsiksi on näin ollut jo tähän asti: laster (transporter). Termi on monimerkityksinen, ks. Kielitoimiston sk. Sanastossa on kuitenkin erikseen kuormitus=belastning. Ks. myös Melinda (suurimmaksi osaksi kuljetusta).

**Comment by ilona-x** [comment]
kuormat -termillä myös huomautus "Jossakin kuljetusneuvossa yhdellä kertaa kuljetettava tavara- tai ainemäärä.", joten tarkenne olisi tarpeen.

**Comment by mirmaid** [comment]
Aika usein näyttää kyseessä olevan raskaan liikenteen aiheuttama kuormitus teiden/siltojen ym. rakenteille, mahtaisiko _kuormat (kuljetus)_ tuntua hyvinkin sopivan näihin?

**Comment by mariaforsen** [comment]
Toivottavasti ei, kun sehän ei sitten sovi ruotsiksi, siihen merkitykseen olisi YSOssa oleva belastning=kuormitus. Eli kuormituksesta rakenteille yms. Pitäisikö siis sen lisäksi tehdä jonkinlainen ohjaus, esim. kuormat (kuormitus) KÄ kuormitus?

**Comment by ilona-x** [comment]
> 
> 
> Aika usein näyttää kyseessä olevan raskaan liikenteen aiheuttama kuormitus teiden/siltojen ym. rakenteille, mahtaisiko _kuormat (kuljetus)_ tuntua hyvinkin sopivan näihin?

Jotenkin tuntuisi aika epätodennäköiseltä, että kuvailija kokisi tuohon tilanteeseen sopivaksi termiksi kuormat (kuljetus). Mutta voisiko tämän ratkaista tekemällä ohjaustermin kuormat (kuormitus) KÄYTÄ kuormitus?

**Comment by ilona-x** [comment]
Voisiko kuormat (kuljetus) termille lisätä ohjaustermiksi lastit?
https://www.kielitoimistonsanakirja.fi/#/lasti

**Comment by mirmaid** [comment]
Suurin osa Melindan viitteistä näyttäisi itse asiassa mielestäni olevan kuormitusta, aina ei kuitenkaan helppo päätellä, kuten esim. tämä auto- ja kuljetustekniikan opinnäyte: https://melinda.kansalliskirjasto.fi/byid/006506496.

**Comment by YSO-kokous** [comment]
### Päätös
kuormat (kuormitus) KÄYTÄ kuormitus
kuormat (kuljetus) KT lastit
