### ISSUE TITLE
Karunan kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8731]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Karunan kirkko 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Seurasaaren Karunan kartanokirkon taulumaalaukset vuonna 1704 

#### Perustelut ehdotukselle   

Vastaavista kirkkorakennuksista löytyy yso-käsite esim. Lakeuden Risti, Pyhän Laurin kirkko ym. 

**Termiehdotus Fintossa:** [Karunan kirkko](http://finto.fi/yse/fi/page/Y508731)

**Comment by mariaforsen** [comment]
Kaksi eri kirkkoa: 
- https://fi.wikipedia.org/wiki/Karunan_vanha_kirkko eli https://www.myhelsinki.fi/fi/n%C3%A4e-ja-koe/n%C3%A4ht%C3%A4vyydet/karunan-kirkko
- https://fi.wikipedia.org/wiki/Karunan_kirkko eli https://www.paimionseurakunta.fi/kirkot-ja-tilat/karunan-kirkko
Eli lisätäänkö molemmat sulkutarkenteineen?

**Comment by mirmaid** [comment]
^ Näin varmaan syytä tehdä.

**Comment by mariaforsen** [comment]
Sv. 
-Karuna gamla kyrka (Fölisön) ET Karuna kyrka (Fölisön)
-Karuna kyrka (Sagu)
