### ISSUE TITLE
sijaissota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8732]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sijaissota 

#### Ehdotettu termi englanniksi   

proxy war 

#### Ehdotettu termi ruotsiksi   

ombudskrig 

#### Vaihtoehtoiset termit ja ilmaisut   

KT proxy-sota 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sodankäynti](http://www.yso.fi/onto/yso/p4130) 

#### Vastaava käsite muussa sanastossa   

LCSH : proxy war 
Wikipedia : sijaissota 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

Sijaissota eli proxy-sota tarkoittaa sisällissotaa tai paikallista sotaa, johon ulkopuoliset valtiot ovat sekaantuneet tukien sodan vastakkaisia osapuolia. 

#### Perustelut ehdotukselle   

On vakiintunut täsmätermi, jolle on tarvetta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Teos Kristiina Koivunen: Kirkuk - Iranin sijaissodan näyttämö 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [sijaissota](http://finto.fi/yse/fi/page/Y508732)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Sijaissota

Ei Melindassa, eikä SOTOssa.

**Comment by mariaforsen** [comment]
Sv. ombudskrig ET krig genom ombud, proxykrig /NE

**Comment by LeKorsu** [comment]
Ikinä ennen kuullutkaan tällaista käsitettä.
