### ISSUE TITLE
suoritteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8733]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suoritteet](http://www.yso.fi/onto/ysa/Y104443) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritellään, selkeytetään suhteessa suoriutumiseen ja suorituksiin 

#### Perustelut ehdotukselle   

Vastine on ruotsiksi ollut prestationer (joka voi yhtä hyvin olla suomeksi suoritukset). 
Tarvitaanko mahdollisesti suoritukset erillisenä terminä suomen osalta, vai voisiko se olla ohjaustermi suoriutumiselle tai mahdollisesti tälle? Melindassa suoritteet=prestationer on nyt käytetty myös "suoritus-merkityksessä", esim. 
-Höga betyg, en lyckad karriär, sociala relationer och en vältränad kropp : en studie om sambandet mellan stress och upplevda prestationskrav / Emma Söderman.
-Älä pelkää puuttumista : suomalaiset esimiehet arastelevat puuttumista huonoon suoritukseen : siitä ei seuraa hyvää.
-Svagt presterande ungdomar i yrkesutbildning / Nina Lundqvist.
-Total stabilitetsträning för prestationsutveckling och skadeprevention / Joanne Elphinston ; [illustrationer: Amanda Williams ; fotografier: Joanne Elphinston ... ; översättning: Salamandra HB ; fackgranskning: Lena Sundén]
-Att ständigt bli bedömd : elevers berättelser om betyg och nationella prov / Héctor Pérez Prieto och Håkan Löfgren (red.).
-Att lyckas med kunskapsbedömning : internationella och jämförande perspektiv på bedömning / Therese N. Hopfenbeck ; översättning : Elisabet Fredholm.

Ellei suomeksi haluta termilisäyksi, voitaisiin ruotsiksi mahdollisesti tehdä ohjaus prestationer (presterande) KÄYTÄ presterande, ja lisätä jonkinlainen tarkenne tälle -jos suomeksi suoritteet määritellään taloudelliseksi/hallinnolliseksi (tosin termi on nyt myös ryhmässä 00) ?

**Comment by mirmaid** [comment]
Eli määritelty nyt: _Palvelu, työ tai vastaava laskennallisena yksikkönä_. 00-ryhmä on varmaan tässä siksi, ettei rajaudu esim. tietylle alalle, voisi kyllä varmaan olla myös ainakin ryhmä 75, enkä tiedä onko tuo 00 kovin tarpeellinen. Aikaisemmin sitä käytettiin hövelimmin. Melindassa yleensä yrityksen suoritteista, ja suomeksi tosiaan ei puhuttaisi yksilön suoritteesta, jos tarkoitettaisiin "saavutusta", ehkä yksilölläkin jossain laskennallisessa mielessä voi olla (työ)suorite.

**Comment by jarmosaarikko** [comment]
Yksilön "suoritteita" lasketaan esim. valtion laitoksissa ja yliopistoissa. Näitä ovat esim. tutkimustietojärjestelmään kirjattavat asiat (julkaisut, esitelmät, matkat, jäsenyydet, osallistuminen toimintaan, jne.). Nämä ovat siis lukumäärällisesti laskettavissa olevia entiteettejä.  TÄmä ei sisällä laatua tai muuta arviointia (suoritus) mutta niiden lukumäärää voidaan arvioida osana suoriutumista.

**Comment by mirmaid** [comment]
^ Tuossakin merkityksessä kuulostaisi vähän hurjalta jos näistä tosiaan puhuttaisiin suoritteina, ilman lainausmerkkejä.

**Comment by YSO-kokous** [comment]
suoritteet käsitteen ryhmä vaihdetaan 00:sta 75:een
