### ISSUE TITLE
Vattihuusi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8734]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Vattihuusi](http://www.yso.fi/onto/ysa/Y115443) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne tai huomautus? 

#### Perustelut ehdotukselle   

Voi viitata muuhunkin kuin Oulussa sijaitsevaan rakennukseen

**Comment by mirmaid** [comment]
Ei varmaan suomeksi käytettäisi muista rakennuksista.

**Comment by ilona-x** [comment]
YSAssa on ollut huomautus: "Vattihuusi on C. L. Engelin v. 1829 suunnittelema puutalo Oulussa. Talo on alunperin toiminut vaivaistalona, myöhemmin kouluna" http://www.yso.fi/onto/ysa/Y115443

**Comment by mariaforsen** [comment]
Entä rakennuksen nykyinen nimi? Ks. https://fi.wikipedia.org/wiki/Kajaanintullin_koulu
