### ISSUE TITLE
presidenttiehdokkaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8735]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

presidenttiehdokkaat 

#### Ehdotettu termi ruotsiksi   

presidentkandidater 

#### Ehdotettu termi englanniksi   

presidential candidates 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh85106456.html 

#### Perustelut ehdotukselle   

Tarvitaan sisällönkuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Osnos: Joe Biden :  the life, the run and what matters now (isbn 978-1-9821-74026) 

**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [presidenttiehdokkaat](http://finto.fi/yse/fi/page/Y508735)

**Comment by AuHo22** [comment]
On tullut vastaan ja taidettu kiertää presidentinvaalit ja ehdokkaat

**Comment by mirmaid** [comment]
N. 10 kertaa Melindassa lähinnä artikkeleissa. _Presidentinvaalit_ & _ehdokkaat_ esiintyy samoissa viitteissä 1200 kertaa.

**Comment by LeKorsu** [comment]
Minun ehdotukseni. Kyseinen kirja ei käsitellyt pääosin vaaleja, vaan on henkilökuva. Siksi tuo kierto presidentinvaalit ja ehdokkaat ei tuntunut hyvältä tässä, vaan ajattelin presidenttiehdokasta enemmän "tittelinä", kuten senaattori.
