### ISSUE TITLE
vakavaraisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8736]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vakavaraisuus](http://www.yso.fi/onto/ysa/Y110615) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi ohjaustermi: soliditeetti 

#### Perustelut ehdotukselle   

On synonymi, ks. esim Wikipedia, https://www.visma.fi/epasseli/kirjanpidon-sanakirja/s/soliditeetti-mita-tarkoittaa-soliditeetti/  https://fi.wiktionary.org/wiki/soliditeetti

**Comment by YSO-kokous** [comment]
Hyväksytty
