### ISSUE TITLE
raportit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8737]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[raportit](http://www.yso.fi/onto/ysa/Y104137) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon 

#### Perustelut ehdotukselle   

Feedback from vocab: SLM
termi "raportit" löytyy YSO'sta, ehdotan myös SLM termiksi, kuten sen liepehelliset termit "katsaukset", "selvitykset" mahdollisin tarkennuksin. 

#### Ehdottajan organisaatio   

-

**Comment by mirmaid** [comment]
Raportit (tutkimusraportit) KÄ tutkimusraportit.

**Comment by mirmaid** [comment]
Seuraava kokous.

**Comment by mirmaid** [comment]
Aineistoesimerkkejä? Milloin tätä ei saa käyttää?

**Comment by jtuohini** [comment]
Myös huomioitava "selonteko"-sana. Joka tapauksessa tarvitaan maininta journalistisista raporteista KÄ [**reportaasit**](http://urn.fi/URN:NBN:fi:au:slm:s114).

**Comment by AuHo22** [comment]
Esimerkkejä raporteista mm.
https://peace.ax/rapportserie/
ja historiallisia:
978-952-5705-81-2

**Comment by jtuohini** [comment]
Ainakin pitäisi tulla selvyys seuraavien kesken: _ilmoitukset_, _kannanotot_, _katsaukset_, _kertomukset_, _kirjalliset selvitykset_, _lausunnot_, _selonteot_, _selostukset_, _selvitykset_, _tiedotukset_, _tiedotteet_, _tilannekatsaukset_, samoin kuin _osavuosikatsaukset_, _vuosikertomukset_ ja _vuosiraportit_. Ja onko muitakin?

**Comment by jtuohini** [comment]
Onko pääasiallisena tarkoituksena tämänhetkisen tilanteen selvittäminen? 
Vai muutosehdotusten selvittäminen – tähdätään toimintaan?
Alla joitakin ajatuksiani pikaisesti:

-selkeämmin tämänhetkisen tilanteen raportoimista, mahdollinen muutos on jo tehty  – mennyt aika
•	ilmoitukset
•	katsaukset
•	kertomukset
•	selostukset  ?
•	tiedotukset
•	tiedotteet
•	tilannekatsaukset 

-näistä samaa tarkoittavat:
•	ilmoitukset
•	tiedotukset
•	tiedotteet
-ja
•	katsaukset
•	tilannekatsaukset


-toistuvat aikaan sidotut raportit, eivät liity muutokseen – mennyt aika
•	(kertomukset)
•	osavuosikatsaukset
•	vuosikertomukset
•	vuosiraportit

-näistä samaa tarkoittavat :
•	vuosikertomukset
•	vuosiraportit


-tavoitteena enemmän muutostarpeen selvitys? – tulevaisuus
•	kannanotot
•	lausunnot
•	kirjalliset selvitykset = selonteot = selvitykset
•	raportit

- näistä samaa tarkoittavat :
•	kannanotot
•	lausunnot


@ Arja Niskala, HYK 9.6.2022

**Comment by jtuohini** [comment]
Tässä vasta muistiinpanoja, jotka lähinnä hajanaisia kirjauksia, joiden pariin yritän aina palata – termejä joiden suhde pohdinnassa:

Ainakin pitäisi tulla selvyys seuraavien kesken: ilmoitukset, kannanotot, katsaukset, kertomukset, kirjalliset selvitykset, lausunnot, selonteot, selostukset, selvitykset, tiedotukset, tiedotteet, tilannekatsaukset, samoin kuin osavuosikatsaukset, vuosikertomukset ja vuosiraportit. Ja onko muitakin?


matkaraportit – kertomukset
ero reportaasit/ ohjaustermi: reportaasikirjallisuus (reportage)
kokousjulkaisut
tilinpäätös – vuosikatsaus - toimintakertomukset
vertailevat … selvitykset, katsaukset, raportit
tutkimusraportit tutkimukset tutkielmat (kokonaisrakenteen perusmalli: IMRD - johdanto, menetelmät, tulokset, pohdinta)
tutkimustyö (talletettuna raportin muotoon – oma työ, oma raportti)
/tutkimuskatsaus (raportoidaan muiden toimintaa) voi olla osa tutkimusraporttia, edeltää raportointia.
vuosikatsaukset
kirjalliset teokset
toimintakertomukset, vuosikirjat
systemaattiset kirjallisuuskatsaukset
uutiskatsaukset → uutiset
vuosikatsaukset
kirjalliset teokset
toimintakertomukset, vuosikirjat
x
tiivistelmä (tutkielma pienoiskoossa)
tutkimustyön osa on kirjoittaminen s.o. raportointi – raportin tekeminen/kirjoittaminen. Pelkkä raportti puolestaan on jonkin muun työn, toiminnan, tapahtuman raportointia, kirjaamista raportin mallin mukaan. Raportoinnin kohde (toiminta, työ, tapahtumat) edeltävät raportin kirjoittamista.
ero selvitykseen, missä oma esitysmallinsa!? 
turvallisuusselvitykset



selvitys  
Tyyppi  Yleiskäsite
Yläkäsite kohdistuva toiminta
Alakäsitteet
palontutkinta, pesänselvitys, turvallisuusselvitykset
Assosiatiiviset käsitteet
selonteot

@ Matti Lamminen, HYK 9.7.2022

**Comment by AuHo22** [comment]
Kokosin jotain yltä:
näistä samaa tarkoittavat:
• ilmoitukset
• tiedotukset
• tiedotteet (on jo SLM-termi, muut ohjaustermeiksi?)

(kertomukset) -> 
• osavuosikatsaukset
• vuosikertomukset
• vuosiraportit

-näistä samaa tarkoittavat :
• vuosikertomukset
• vuosiraportit

SLM jo toimintakertomukset, Kotus: _"tav. määräajalta laadittu kirjallinen selostus liikeyrityksen, järjestön tms. toiminnasta._" - voivatko yo. olla ohjaustermejä, voi olla osavuosikatsaus tai vuosikatsaus?

YSOssa sekä kannanotot että RT lausunnot ST lääkärinlausunnot / päätöslauselmat / suositukset


Kotus: raportti  -> _tiedotus, tiedote, tiedonanto, selonteko, tilannekatsaus_. 

YSO raportit ST hyvinvointikertomukset, sotaraportit, tutkimusraportit 
Miten erotetaan raportti selvityksistä (YSO turvallisuusselvitykset on), katsauksista (YSO kirjallisuuskatsaukset, vuosikatsaukset on) ja selonteosta? Vai pitäisikö tyytyä vain tarkempiin termeihin ja katsaukset/selvitykset ohjaisivat raportteihin, joka olisi uusi SLM-termi?

**Comment by AuHo22** [comment]
Kotus: lausunto -> _asiantuntemukseen nojautuva (pyydetty), tav. kirjallinen mielipiteen ilmaisu, kannanotto, selvitys tms.
Komitean, valiokunnan lausunto._
Kotus: kannanotto -> _kannan ottaminen; kanta._
_Poliittinen kannanotto._
Kotus: selonteko -> _suullinen t. kirjallinen selvitys (2), selostus, kertomus_.
_Hallituksen selonteko verolain uudistuksesta._

**Comment by mariaforsen** [comment]
Eli mitkä kaikkia nyt käsitellään tässä? Minusta on selvää että raportit tarvitaan (itsekin tarvinnut monesti kun kyseessä EI ole tutkimusraportteja/forskningsrapporter vaan jonkin hankkeen, kaupallisen tms.), eli kannatan sitä.

**Comment by AuHo22** [comment]
Ehdotus SLM-termiksi: selonteot, selvitykset, katsaukset KÄ raportit

**Comment by mirmaid** [comment]
Entä tämä kommentti https://github.com/Finto-ehdotus/YSE/issues/8737#issuecomment-862171380? Jonkinlainen ohjaus varmasti tarvitaan, jotta näitä journalistisia raportteja ei vahingossa kuvailtaisi _raportit_-genrellä (itse voisin ainakin moisen virheen hyvin tehdä).

**Comment by mirmaid** [comment]
Raportit (reportaasit) KÄ reportaasit

Tiedonannot KÄ tiedotteet

Hyväksytään _raportit_ KT kirjalliset selonteot, selvitykset

Vuosikertomukset, osavuosikatsaukset KÄ toimintakertomukset

**Comment by mariaforsen** [comment]
Sv. rapporter HT skriftliga redogörelser, utredningar

**Comment by mariaforsen** [comment]
Lisätäänkö samat ohjaustermit myös YSOon?

**Comment by mirmaid** [comment]
Eli 
raportit KT kirjalliset selonteot, selvitykset

YSOssa on erikseen vuosikatsaukset, toisin kuin SLM:ssä. Lisätäänkö osavuosikatsaukset kuitenkin ohjaustermiksi toimintakertomuksille, kuten SLM:ssä?

**Comment by jarmosaarikko** [comment]
Tämäkö oli jo päätetty?
**tiedonannot** on käsitteenä ollut aivan eri asia kuin "tiedotteet" (yleensä lyhyitä viestinnällisiä tekstejä). Mielestäni näitä ei saa sotkea keskenään. kts.
- "Metsäntutkimuslaitoksen tiedonantoja" (ja muitakin vastaavia oli)  http://urn.fi/URN:ISSN:0358-4283
 - tämä oli tieteellinen vertaisarvioimaton julkaisusarja, jossa julkaistiin monenlaisia raportteja, kokousjulkaisuja, tutkimustulosksia yms.  kymmeniä tai satoja sivuja, joskus useita artikkeleita sisältäviä. NÄitä julkaistiin vuosien varrella lähes tuhat. 
- https://www.jyu.fi/science/fi/bioenv/tutkimus/julkaisut/tiedonantoja
- https://www.julkari.fi/handle/10024/141694 Tiedonantoja (Eläketurvakeskus)
- https://www.eduskunta.fi/FI/valtiopaivaasiat/Sivut/Valtioneuvoston-tiedonannot.aspx  (tässä julkaistaan 'selvityksiä')
- https://www.doria.fi/handle/10024/96390 Tilastollisia tiedonantoja (sarjassa on ilmestynyt laajahkoja tilastollisia erityisselvityksiä ja tutkimuksia,...)
- jne. 
**Nämä eivät olleet "tiedotteita".**
Sen sijaan esim. seuraava on tiedote
- Tiedonantoja merenkulkijoille - https://www.traficom.fi/fi/liikenne/merenkulku/tiedonantoja-merenkulkijoille-koosteet

**Comment by mariaforsen** [comment]
https://www.kielitoimistonsanakirja.fi/#/tiedote?searchMode=all 
https://www.kielitoimistonsanakirja.fi/#/tiedonanto?searchMode=all 
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_39c15c1210c2950472a0608e63a5c1bc&list_id=1&keyword=tiedonanto&word=tiedonanto
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4f977c82fc99d7c330930792516b4a56&list_id=1&keyword=tiedote&word=tiedote

Siispä jos todella haluttaisiin tiedotteet ja tiedonannot erillisinä terminä, se vaatisi jonkinlaisia tarkennuksia niiden merkitykseen, viimeistään siinä vaiheessa kun ne käännetään.

**Comment by YSO-kokous** [comment]
**Päätös**

Muutokset _selvitykset (selonteot)_ käytä _selonteot_ sekä  _selvitykset (raportit)_ käytä _raportit_. Myös _osavuosikatsaukset_ käytä _toimintakertomukset_.
