### ISSUE TITLE
itseohjautuvat robotit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8738]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

itseohjautuvat robotit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Engineering autonomous vehicles and robotics 

#### Perustelut ehdotukselle   

- 

**Termiehdotus Fintossa:** [itseohjautuvat robotit](http://finto.fi/yse/fi/page/Y508738)

**Comment by mirmaid** [comment]
Engineering autonomous vehicles and robots
https://melinda.kansalliskirjasto.fi/byid/017465331

**Comment by mariaforsen** [comment]
Sv. autonoma robotar ET självstyrande robotar

**Comment by fantsby-m** [comment]
https://en.wikipedia.org/wiki/Autonomous_robot
