### ISSUE TITLE
robottiautot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8739]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[robottiautot](http://www.yso.fi/onto/ysa/Y504783) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT itseohjautuvat ajoneuvot 

#### Perustelut ehdotukselle   

-

**Comment by mirmaid** [comment]
Myös itseohjautuvat autot

**Comment by YSO-kokous** [comment]
Hyväksytty
