### ISSUE TITLE
melaniini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8740]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

melaniini 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Use of melanin binding as drug delivery strategy to the posterior eye segment 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [melaniini](http://finto.fi/yse/fi/page/Y508740)

**Comment by mirmaid** [comment]
Tai monikossa FinMeSHin tapaan http://www.yso.fi/onto/mesh/D008543

Myös LCSH: Melanins http://id.loc.gov/authorities/subjects/sh85083376

_There are five basic types of melanin: eumelanin, pheomelanin, neuromelanin, allomelanin and pyomelanin._ https://en.wikipedia.org/wiki/Melanin

**Comment by mariaforsen** [comment]
Sv. melaniner
