### ISSUE TITLE
oppimispelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8741]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[oppimispelit](http://www.yso.fi/onto/ysa/Y152657) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan myös SLM-sanastoon. 

#### Perustelut ehdotukselle   

Tarvitaan oppimispelien kuvailussa 

#### Ehdottajan organisaatio   

kk

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
