### ISSUE TITLE
spekulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8742]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

spekulaatio 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/309787 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [spekulaatio](http://finto.fi/yse/fi/page/Y508742)

**Comment by mirmaid** [comment]
8 kertaa monikossa/yksikössä, mutta muutama viitteistä liittyy keinotteluun.

Kielitoimiston sanakirja: spekulaatio: 1. teoreettinen, olettamuksiin perustuva ajattelu, järkeily, mietiskely; laskelmointi. _Antautua metafyysisiin spekulaatioihin. Spekulaatiot talouspoliittisen linjan jatkuvuudesta._ 

https://tieteentermipankki.fi/wiki/Filosofia:spekulaatio

**Comment by mariaforsen** [comment]
Sv. spekulation (filosofi) 
Sanastossa on jo "spekulation (ekonomi)"

**Comment by fantsby-m** [comment]
Sanaston _spekulation (ekonomi)_ on suom. _keinottelu_ - sopisiko siihen siihen ohjaustermiksi _spekulaatio (talouselämä)_?

**Comment by YSO-kokous** [comment]
Hyväksytään spekulaatio (filosofia)    lisäksi keinottelu KT spekulaatio (talous)
