### ISSUE TITLE
ioniset nesteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8743]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ioniset nesteet 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/308782 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ioniset nesteet](http://finto.fi/yse/fi/page/Y508743)

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/310354

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ioninen_neste
LCSH: Ionic solutions (?) http://id.loc.gov/authorities/subjects/sh85067821

5 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. jonvätskor, joniska vätskor

**Comment by fantsby-m** [comment]
> https://fi.wikipedia.org/wiki/Ioninen_neste
> LCSH: Ionic solutions (?) http://id.loc.gov/authorities/subjects/sh85067821

Onkohan tuo _ionic solutions_ eri asia vai sama? Täällä: https://en.wikipedia.org/wiki/Ionic_liquid lukee mm. näin: 

> Low-temperature ionic liquids can be compared to ionic solutions, liquids that contain both ions and neutral molecules, and [--]

Eli tuo solution on kaiketi liuos.
