### ISSUE TITLE
säeromaani

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8744]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

säeromaani 

#### Perustelut ehdotukselle   

Nykyään ilmestyy säeromaaneita kasvavassa tahdissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://outi.finna.fi/Record/outi.2129362 

**Ehdottajan organisaatio:** Oulun kaupunginkirjasto **Termiehdotus Fintossa:** [säeromaani](http://finto.fi/yse/fi/page/Y508744)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/7476

**Comment by mirmaid** [comment]
Tälle ei ole vastinetta ruotsiksi (tai muilla kielillä). Voidaan kuvailla yhdistelmällä _runoromaanit_ ja _nuortenkirjallisuus_.
