### ISSUE TITLE
Laki lapsen huollosta ja tapaamisoikeudesta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8745]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Laki lapsen huollosta ja tapaamisoikeudesta 

#### Vaihtoehtoiset termit ja ilmaisut   

Lapsenhuoltolaki 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lait](http://www.yso.fi/onto/yso/p1464) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Kirjassa käsitellään uudistunutta ko. lakia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Uudistunut lapsenhuoltolaki 9789521440168 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Laki lapsen huollosta ja tapaamisoikeudesta](http://finto.fi/yse/fi/page/Y508745)

**Comment by jtuohini** [comment]
Jatkossa olisi varmaan hyvä tehdä säädöksistä ym. teosauktoriteettitietueet asiasana-auktoriteettitietueiden sijaan ja auktorisoitujen hakumuotojensa osalta noudattaa RDA:n luvun 6.29.1 ohjeistusta. Tämäkään ei RDA:n puitteissa kuulu aiheena käsiteltynä 650-kenttään, vaan 610-kenttään, kaiketikin muodossa "610 14 |a Suomi. |t Laki lapsen huollosta ja tapaamisoikeudesta."

**Comment by mariaforsen** [comment]
On jo YSOssa http://www.yso.fi/onto/yso/p39049
