### ISSUE TITLE
ventraalityrä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8746]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ventraalityrä 

#### Ehdotettu termi ruotsiksi   

ventralbråck 

#### Ehdotettu termi englanniksi   

ventral hernia 

#### Vaihtoehtoiset termit ja ilmaisut   

arpityrä 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tyrät](http://www.yso.fi/onto/yso/p21990) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D006555> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85142751> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Surgical treatment of incisional ventral hernia : with a special reference to laparoscopic techniques 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ventraalityrä](http://finto.fi/yse/fi/page/Y508746)

**Comment by FinMeSHienPaimentaja** [comment]
Terveysportista lääketieteen termit löytyy suomenkielisempi "vatsatyrä":

https://www.terveysportti.fi/sovellukset/sanakirjat/#/q/113/lte23944

vatsatyrä hernia abdominalis (ventralis), hernia ventralis, laparocele la, ventral hernia, laparocele e, bukbråck ‑et, laparocele ‑t r ventraalihernia, laparoseele | vatsaontelosta vatsanpeitteisiin tai niiden läpi tunkeutuva tyrä; vrt. eventraatio

**Comment by ilona-x** [comment]
esimerkkiaineistossa (http://jultika.oulu.fi/Record/isbn978-952-62-2532-6) käsiteltiin leikkauskomplikaationa syntyvää arpityrää, joka on FinMeSHissä KT-muotona ventraalityrälle http://www.yso.fi/onto/mesh/D006555

FinMeSHissä näin:
vatsatyrä  http://www.yso.fi/onto/mesh/D046449
ALAKÄSITTEET
    nivustyrä
    reisityrä
    vatsahalkio
    ventraalityrä

YSOssa on jo nivustyrä, joka FinMeSHIssä on vatsatyrän alakäsite samoin kuin nyt ehdotettu ventraalityrä.

HUOM. FinMeSHissä näköjään tuon vatsatyrä-käsitteen lisäksi ventraalityrä KT vatsatyrä. 🤔
