### ISSUE TITLE
lööpit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8747]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lööpit](http://www.yso.fi/onto/ysa/Y175455) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjataan englanninkielinen prefLabel "lööpit" joksikin englanninkieliseksi, vaikka "headline" tai joku muu. 

#### Perustelut ehdotukselle   

"Lööpit" on suomea, ei englantia. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Viittaako lööpit julisteisiin vai otsikoihin?

**Comment by mirmaid** [comment]
_Puhekielessä lööpillä tarkoitetaan usein myös lehden etusivua tai raflaavia otsikoita ylipäätään._ (Wikipedia)

Käytetty Melindassa 21 kertaa, molempia käyttötapauksia.

**Comment by mirmaid** [comment]
Myös lööppijulisteet sisältävät lööppiotsikoita, joten jälkimmäinen on monikäyttöisempi. Tuntuisi ehkä vähän turhalta ottaa näitä erikseen, tutkimuskohteena varmaan kuitenkin molempien osalta huomiohakuinen otsikoiden muotoilu.

Mielestäni voisi olla esim.
lööpit KT lööppijulisteet, lööppiotsikot

**Comment by mariaforsen** [comment]
Ruotsiksi täytyy varmaan pitää nykyinen muoto, paitsi jos on tarkoitus viitata uutisotsikoihin? Siinä tapauksessa voidaan muuttaa/lisätä > nyhetsrubriker.

**Comment by mirmaid** [comment]
^ Ruotsiksi ei ole siis termiä näille raflaaville, huomiohakuisille otsikoille erikseen? _Uutisotsikot_-termiä mietin itsekin ja se on toki mahdollinen korvaaja, jos muuten ei voida kuvailla näitä lööppiotsikoita. Se on kuitenkin neutraali, ei ota kantaa otsikon tyyliin. Pelkkä _otsikotkin_ kenties riittää. 

Jos ruotsiksi rajautuu vain lööppijulisteisiin, on päätermi vaihdettava suomeksikin.

**Comment by mariaforsen** [comment]
Ei, nyhetsrubriker käytetään kyllä riippumatta siitä kuinka "raflaavia" ne ovat :)
