### ISSUE TITLE
ruukinpatruunat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8749]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruukinpatruunat 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Högforsin patruunat 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ruukinpatruunat](http://finto.fi/yse/fi/page/Y508749)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: patruuna 2. _aik. tehtaan- t. kartanonomistajasta_.

https://fi.wikipedia.org/wiki/Teollisuuspatruuna

**Comment by mariaforsen** [comment]
Sv. brukspatroner
Myös SAOssa https://id.kb.se/term/sao/Brukspatroner

**Comment by YSO-kokous** [comment]
Hyväksytään ruukinpatruunat KT patruunat (ruukinpatruunat)
