### ISSUE TITLE
ura

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8750]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ura 

#### Vaihtoehtoiset termit ja ilmaisut   

läheisesti liittyy työura (karriär, career) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Väitöskirjatutkimuksessa 

#### Perustelut ehdotukselle   

Muuttuneissa työelämäkäsitteissä puhutaan yleisesti urasta. Uusien opetussuunnitelmien ja työelämäpalveluiden osalta puhutaan urasuunnittelusta, uraohjauksesta jne. Ura on muodostunut käsitteeksi laajemmasta näkemyksestä yksilön elämänkulusta, joka pitää sisällään mahdolliset poikkeamat työelämän ulkopuolelle ja erilaiset vaiheet ihmisen elämässä. 

**Termiehdotus Fintossa:** [ura](http://finto.fi/yse/fi/page/Y508750)

**Comment by mirmaid** [comment]
Sanastossa on _työura_ ja _urheilu-ura_. Jos otettaisiin lisäksi yleinen ura (= työelämä ja muut jaksot, opiskelu jne.), menisi käyttö todennäköisesti melko päällekkäin.

**Comment by mariaforsen** [comment]
Sanastossa on jo karriär=työura, päällekkäisyyden takia en kannata.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi  ura (työura) KÄ työura
