### ISSUE TITLE
akuuttihoitopalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8751]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[akuuttihoitopalvelut](http://www.yso.fi/onto/ysa/Y206749) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään KT ensihoitopalvelut 

#### Perustelut ehdotukselle   

vrt. FinMeSH: 
ensihoitopalvelut KT akuuttihoitopalvelut http://www.yso.fi/onto/mesh/D004632 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Mihinköhän tämän päätermin on tarkoitus viitata, kun joukossa on sekaisin akuuttihoitoa ja fysioterapiaa, ja ohjausterminä on suoravastaanotto?

**Comment by YSO-kokous** [comment]
Palataan tähän, kun selvitetään fysioterapia suoravastaanottotoiminnassa asema.

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit (Terveysportti):

_**akuuttihoito**
acute medicine, emergency care e, akutvård ‑en r hätätilojen diagnostiikka ja hoito (erityisesti päivystävissä yksiköissä) mukaan lukien välitöntä hoitoa vaativien sairauksien tunnistaminen ja hoitaminen sekä kiireellisen jatkohoidon järjestäminen; ks. myös ensihoito, ensiapu_

_**ensihoito**
initial treatment e, inledande behandling r terveydenhuollon ammattihenkilöiden antama ensiapu (esim. nesteensiirron aloittaminen); vrt. ensiapu, ensivaste (1), hätäensiapu, akuuttihoito_

Näyttäisi olevan merkitykset aika samoja...FinMeSH:eissä esiintyy (epäjohdonmukaisesti) sekä akuuttihoitoa että ensihoitoa, toisaalta jotkut termeistä ovat vakiintuneita. 

![image](https://user-images.githubusercontent.com/33662610/117322994-280a7200-ae97-11eb-9151-875016892f1c.png)

**Comment by mirmaid** [comment]
_Fysioterapeutin suoravastaanotto tarkoittaa, että tuki- ja liikuntaelinoireinen potilas ohjataan ajanvarauksesta tai hän varaa itse ajan ensikäynnille fysioterapeutin vastaanotolle ilman lähetettä._

Tarvitaanko tälle omaa käsitettä vai riittääkö _fysioterapia & vastaanottotoiminta_?
