### ISSUE TITLE
laskimotukos

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8753]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laskimotukos 

#### Ehdotettu termi englanniksi   

Venous Thrombosis 

#### Ehdotettu termi ruotsiksi   

ventrombos 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tromboosi](http://www.yso.fi/onto/yso/p1659) 

#### Alakäsitteet (RT)   

[syvä laskimotromboosi](http://www.yso.fi/onto/yso/p5525) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D020246> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Melinda:
laskimotromboosi x 30
laskimotukos x 83
laskimotukokset x 3 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Thromboprophylaxis with low-molecular-weight heparin in critically ill patients 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [laskimotukos](http://finto.fi/yse/fi/page/Y508753)

**Comment by LeKorsu** [comment]
Sanastossa on jo laskimotukos kansankielellä eli veritulppa http://finto.fi/yso/fi/page/p1658. 
Se pitäisi varmaan muuttaa ohjaustermiksi. Tai ainakin laskimoveritulppa, jos englanninkelen perusteella thromobis ja embolism eivät ole täsmällisiä synonyymejä.

https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00039

**Comment by mirmaid** [comment]
^ Hyvä huomio!

Lääketieteen termit: veritulppa: _1. verenkierron mukana kulkeva → embolus; 2. embolusten aiheuttama verisuon(i)en tulppautuminen; ks. embolia; 3. verisuonen(sisäinen) hyytymätulppa; ks. tromboosi_

**Comment by mirmaid** [comment]
Leenan linkistä myös: _Laskimotukos syntyy syvällä kudosten sisällä oleviin laskimoihin. Ihon alla sijaitsevissa pinnallisissa laskimoissa esiintyy laskimotulehduksia, mutta ei merkittäviä tukoksia_. Vaatinee lisäselvittelyä.

**Comment by FinMeSHienPaimentaja** [comment]
Thrombin ja emboluksen eroista: 

https://meshb.nlm.nih.gov/record/ui?ui=D016769

https://meshb.nlm.nih.gov/record/ui?ui=D004617

https://meshb.nlm.nih.gov/record/ui?ui=D013927

ja jotta pähkäilyt ei loppuisi:

https://meshb.nlm.nih.gov/record/ui?ui=D013923

***

https://www.terveysportti.fi/sovellukset/sanakirjat/#/q/113/lte23630

https://www.terveysportti.fi/sovellukset/sanakirjat/#/q/113/lte04542

***

Summa summarum, thrombi näyttäisi olevan nimenomaan verihyytymä -> tukkeuma,  embolus voi olla muutakin, joka tukkii.

**Comment by ilona-x** [comment]
YSOssa nyt:
veritulppa http://www.yso.fi/onto/yso/p1658
tromboosi http://www.yso.fi/onto/yso/p1659
sinustromboosi http://www.yso.fi/onto/yso/p38462
syvä laskimotromboosi http://www.yso.fi/onto/yso/p5525

**Comment by mirmaid** [comment]
Ilmeisesti puuttuu vielä tämä: https://www.terveyskirjasto.fi/dlk00688

**Comment by YSO-kokous** [comment]
jatketaan selvittämistä

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

**laskimotromboosi**
[sori, toistoa...]

thrombosis venae mon. thrombosis venarum la, venous thrombosis e, ventrombos ‑en, venös trombos r flebotromboosi | laskimo(ide)n hyytymätulppa, laskimotukos; vrt. tromboflebiitti; ks. myös tromboosi, pyletromboosi

**pinnallinen laskimotromboosi** thrombosis (venae/venarum) superficialis la, superficial venous thrombosis e, ytlig ventrombos r pinnallinen laskimotukos | →iholaskimon tromboosi

**syvä laskimotromboosi** thrombosis (venae/venarum) profunda la, deep vein thrombosis, deep venous thrombosis e, djup ventrombos r (lyh. SLT, DVT) syvä laskimotukos | tavallisesti pohkeen laskimoon syntyvä tromboosi, joka voi ulottua →reisilaskimoon (vena femoralis) ja edelleen ulompaan →lonkkalaskimoon (vena iliaca externa)

**Comment by FinMeSHienPaimentaja** [comment]
Embolism:

https://en.wikipedia.org/wiki/Embolism

**Comment by mirmaid** [comment]
Sanastossa on siis _syvä laskimotromboosi,_ puuttuu _pinnallinen laskimotulehdus_. _Veritulppa_ voi olla esim. syvä laskimotromboosi, tai tästä seurannut _keuhkoveritulppa_ (keuhkovaltimon tukos). Se voi viitata myös itse veren mukana kulkevaan tulppaan, embolukseen. Sanastossa on myös _tromboosi_ (= verisuonitukos, _verihyytymän muodostuminen verisuonen sisälle; verihyytymän esiintyminen verisuonen sisällä (Lääketieteen termit)_). 

Ehdotan, että otetaan siis sanastoon _pinnallinen laskimotulehdus_. Olemassaolevista termeistä _veritulppa_ ja _tromboosi_ ovat melko päällekkäisiä, ja Melindassa veritulppa on usein käytetty aineistoissa, joissa kyseessä on nimenomaan syvä laskimotukos. MeSH: veritulppa KÄ _embolia ja tromboosi_ (näiden erottaminen on tavikselle aika haastavaa, embolia: _yhden tai useamman verenkierron mukana kulkevan emboluksen (tavallisesti verihyytymän) aiheuttama verisuon(t)en tulppautuminen_). 

Poistetaanko _veritulppa_? Ainakin kannattanee tehdä ohjaus veritulppa (syvä laskimotukos) KÄ syvä laskimotromboosi.

**Comment by ilona-x** [comment]
> Poistetaanko _veritulppa_? Ainakin kannattanee tehdä ohjaus veritulppa (syvä laskimotukos) KÄ syvä laskimotromboosi.

Kannatan veritulppa-termin poistoa ja ohjaamista muihin tarkempiin termeihin.

**Comment by YSO-kokous** [comment]
Otetaan muodossa "pinnallinen laskimotulehdus",  poistetaan veritulppa-käsite.
Veritulppa jää ohjaustermiksi.

**Comment by mariaforsen** [comment]
Onko se sama kuin tämä: https://finto.fi/mesh/fi/page/D010689 ? netissä ei löydy paljoa termillä "pinnallinen laskimotulehdus"

**Comment by mirmaid** [comment]
^ https://www.terveyskirjasto.fi/dlk00688

**Comment by ilona-x** [comment]
Mitä tässä muuten kävi tuolle alkuperäiselle ehdotukselle **laskimotukos**, joka ei siis ole sama asia kuin hyväksytyksi tullut **pinnallinen laskimotulehdus**? 

laskimotukos siis meshissä: http://www.yso.fi/onto/mesh/D020246

**Comment by mirmaid** [comment]
Se laskimotukos on (sen perusteella mitä em. lähteissä sanotaan) joko pinnallinen laskimotulehdus tai syvä laskimotromboosi. 

Tai suunnilleen noin: _Various other forms of venous thrombosis also exist; some of these can also lead to pulmonary embolism. Venous thromboembolism and superficial vein thrombosis account for about 90% of venous thrombosis. Other rarer forms include retinal vein thrombosis, splanchnic vein thrombosis, cerebral venous sinus thrombosis, renal vein thrombosis, and ovarian vein thrombosis._ https://en.wikipedia.org/wiki/Venous_thrombosis

**Comment by mariaforsen** [comment]
Eli onko ok jos laitetaan tämä ruotsiksi: https://finto.fi/mesh/fi/page/D010689?clang=sv
