### ISSUE TITLE
kuvastot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8754]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kuvastot](http://www.yso.fi/onto/ysa/Y102876) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä "kuvia sisältävä esite, kaupallinen luettelo tms." tms. ainakin SLM:n puolelle. 

#### Perustelut ehdotukselle   

Yleiskielessä kuvasto on epätarkka käsite ja voi sekoittua kuvateoksiin SLM:n käytön kannalta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kuvallinen tuoteluettelo. (YK tuoteluettelot)

Muista runsaasti kuvia sisältävistä julkaisuista käytetään termiä kuvateokset.
