### ISSUE TITLE
kulkueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8755]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kulkueet](http://www.yso.fi/onto/ysa/Y110777) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "juhlakulkueet" 

#### Perustelut ehdotukselle   

Paljon käytetty nimitys, josta soisi viitattavan käytettävään asiasanaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
