### ISSUE TITLE
riemukaaret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8757]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[riemukaaret](http://www.yso.fi/onto/ysa/Y104179) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "triumfikaaret" 

#### Perustelut ehdotukselle   

Ks. esim. https://melinda.kansalliskirjasto.fi/byid/001408881 ja https://fi.wikipedia.org/wiki/Riemukaari: "Triumfikaari (”riemukaari”) on suuri monumentaaliportti, jolla on juhlistettu muun muassa sotavoittoa." Googlen sanahakukin tuottaa ainakin 777 osumaa, joten viittausmuodon kirjallisuustakuu täyttyy kevyesti. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
