### ISSUE TITLE
klubit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8758]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[klubit](http://www.yso.fi/onto/ysa/Y121099) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

klubit-käsitteelle (http://www.yso.fi/onto/yso/p11265) pitäisi minusta lisätä käytettävään termiin sulkutarkenne, koska sekin voi mennä sekaisin musiikkiklubit-käsitteen kanssa 

#### Perustelut ehdotukselle   

https://github.com/Finto-ehdotus/YSE/issues/8576 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Lisätty klubit (musiikki) KÄ musiikkiklubit, onko silti ongelma?

**Comment by mirmaid** [comment]
Jos tarvitaan, niin tuleeko tarkenteeksi esim. _klubit (kerhot)_? Viitteet korjattava joka tapauksessa.

**Comment by fantsby-m** [comment]
Minkätyyppisiä klubeja tuolla kommersiell verksamhet/ commercial lopulta tarkoitetaan, jos vapaa-ajan kerhot ovat erikseen?

**Comment by ilona-x** [comment]
Melindassa näyttää olevan jonkin verran viitteitä, jotka käsittelevät yksityisklubeja

https://fi.wikipedia.org/wiki/Luokka:Yksityisklubit
LCSH: Private clubs http://id.loc.gov/authorities/subjects/sh2009003342

**Comment by ilona-x** [comment]
Yksi mahdollinen ohjaus voisi olla **klubit (yökerhot) KÄYTÄ yökerhot**

englanninkielisessa wikipediassa: "A nightclub, music club, or simply **club**, is an entertainment venue and bar that usually operates late into the night." https://en.wikipedia.org/wiki/Nightclub

**Comment by ilona-x** [comment]
myös ohjaus **klubit (kerhot) KÄYTÄ kerhot** voisi ohjata käyttöä oikeaan suuntaan

**Comment by ilona-x** [comment]
siivottu Melindasta musiikkiklubeja käsittelevät viitteet

**Comment by mariaforsen** [comment]
Sv. privata klubbar ET privatklubbar
