### ISSUE TITLE
riskiviestintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8761]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

riskiviestintä 

#### Ehdotettu termi englanniksi   

risk communication 

#### Ehdotettu termi ruotsiksi   

riskkommunikation 

#### Ehdotettu yläkäsite YSOssa (LT)   

[viestintä](http://www.yso.fi/onto/yso/p36) 

#### Vastaava käsite muussa sanastossa   

TSR : <http://www.yso.fi/onto/tsr/p13225> 
LCSH : <http://id.loc.gov/authorities/subjects/sh87005717> 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 11 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kohti vuorovaikutteista riskiviestintää : tapausesimerkkinä langattoman viestintätekniikan säteily 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [riskiviestintä](http://finto.fi/yse/fi/page/Y508761)

**Comment by ilona-x** [comment]
fi        riskiviestintä; riskin viestintä
sv       riskinformation
en      communication concerning a specific risk

määritelmä
riskiin liittyvien tietojen ja mielipiteiden aktiivinen, hallittu ja vastavuoroinen välittäminen niille, joita riski koskee

definition
aktiv, kontrollerad och ömsesidig spridning av information och åsikter kring en risk som förmedlas till alla som berörs av risken

Lähde: Työsuojelusanasto (TSK 35, 2006/2008)

**Comment by mariaforsen** [comment]
Sv. riskkommunikation ET kommunikation av riskinformation https://id.kb.se/term/sao/Riskkommunikation
