### ISSUE TITLE
tontit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8762]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tontit](http://www.yso.fi/onto/ysa/Y99586) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "rekisteritontit" 

#### Perustelut ehdotukselle   

Helsingin kaupungin kaupunkisuunniteluviraston terminologiatyöryhmän laatima Kaupunkisuunnittelun terminologiaa, s. 18: "Tontti (rekisteritontti) on asemakaava-alueella sijaitseva rakennuskortteliin kuuluva alue [- -]" 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Sama lähde, s. 19: "Tomt (registertomt) (tontti) är ett område [- -]" eli myös ruotsinkielinen viittaus _registertomter_ KÄ **tomter** olisi hyvä saada.

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Oikeustiede:tontti

**Comment by YSO-kokous** [comment]
Hyväksytty. Lisätään myös KT kaavatontit
