### ISSUE TITLE
strippisarjakuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8763]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[strippisarjakuvat](http://www.yso.fi/onto/ysa/Y149757) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "sanomalehtisarjakuvat" 

#### Perustelut ehdotukselle   

Ilmausta käytetty nimenomaan strippisarjakuvaa tarkoittamassa mm. useissa Wikipedia-artikkeleissa 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
