### ISSUE TITLE
suurteholaskenta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8764]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suurteholaskenta 

#### Ehdotettu termi ruotsiksi   

högpresterande datorsystem 

#### Ehdotettu termi englanniksi   

high-performance computing 

#### Vaihtoehtoiset termit ja ilmaisut   

HPC 

#### Ehdotettu yläkäsite YSOssa (LT)   

[laskentamenetelmät](http://www.yso.fi/onto/yso/p22180) 

#### Vastaava käsite muussa sanastossa   

TEPA termipankki : https://termipankki.fi/tepa/fi/haku/suurteholaskenta 
wikidata : https://www.wikidata.org/wiki/Q1190465 
LCSH : <http://id.loc.gov/authorities/subjects/sh95008935> 
IATE : https://iate.europa.eu/entry/result/1757975/all 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Perustelut ehdotukselle   

Esimerkiksi Annif kehittämisessä käytetään suurteholaskentaa, joten Annif palvelun kvailussa tarvitaan tätä käsitetttä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Annif 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suurteholaskenta](http://finto.fi/yse/fi/page/Y508764)

**Comment by MikkoAleksanteri** [comment]
Melindassa suomenkielisinä ainakin teokset:

- Implementation techniques for the lattice Boltzmann method / Keijo Mattila.  Mattila, Keijo. Jyväskylä : University of Jyväskylä, 2010 (Jyväskylä : Jyväskylä University Printing House)    Väitöskirja 

- Laskentateho on kortilla : ohjelmointitaitoisen näyttöpaikka.  Haataja, Juha.    Artikkeli 

- Suurteholaskenta tutkimuksessa : Suomen kattava metatietokone? / Kimmo Kaski.  Kaski, Kimmo.    Artikkeli 

- Suurteholaskenta USAssa :  Nieminen, Risto.    Artikkeli 

- Suomen tieteellinen suurteholaskenta nousussa.

**Comment by mariaforsen** [comment]
https://id.kb.se/term/sao/H%C3%B6gpresterande%20ber%C3%A4kningar 
Sv. högpresterande beräkning ET högpresterande databehandling, högpresterande datorsystem
