### ISSUE TITLE
hyötyliikunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8765]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hyötyliikunta](http://www.yso.fi/onto/ysa/Y112962) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään ohjaustermi arkiliikunta 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Hy%C3%B6tyliikunta
ruotsiksi YSOssa vardagsmotion 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
