### ISSUE TITLE
viljasiilot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8766]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viljasiilot 

#### Ehdotettu termi englanniksi   

grain elevators 

#### Vaihtoehtoiset termit ja ilmaisut   

jyväsiilot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[siilot](http://www.yso.fi/onto/yso/p11070) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85056231> 
Wikidata : https://www.wikidata.org/wiki/Q1520009 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 
[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Finnassa sanahaulla "viljasiilo" yli 300 osumaa, joukossaan paljon tätä asiasanaa tarkkaa kuvailuun kaipaavia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [viljasiilot](http://finto.fi/yse/fi/page/Y508766)

**Comment by ilona-x** [comment]
AFO: **viljasiilot** http://www.yso.fi/onto/afo/p1802 YK siilot RT viljavarastot
MAO/TAO: **viljasiilot** http://www.yso.fi/onto/mao/p9431 YK viljavarastot

viljavarastot löytyy myös YSOsta http://www.yso.fi/onto/yso/p12696
