### ISSUE TITLE
vastaanottokeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8767]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vastaanottokeskukset](http://www.yso.fi/onto/ysa/Y111494) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "maahanmuuttokeskukset" 

#### Perustelut ehdotukselle   

Ilmausta käytetty kyseisten instituutioiden nimissä, esim. Vöyrin maahanmuuttokeskus. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. migrationscenter

**Comment by YSO-kokous** [comment]
Hyväksytty
