### ISSUE TITLE
Meltaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8770]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Meltaus 

#### Tarkoitusta täsmentävä selite   

Maantieteellinen paikannimi. 

#### Perustelut ehdotukselle   

Ounasjoen varrella Rovaniemen kaupungin alueella sijaitseva kylä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallishistoriallinen, luonnontieteellinen, maantieteellinen. 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Meltaus](http://finto.fi/yse/fi/page/Y508770)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10219049
