### ISSUE TITLE
Meltausjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8771]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Meltausjoki 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Joen nimi. Lähtee Unarijärvestä ja laskee Meltauksen kylän kohdalla idästä Ounasjokeen. 

#### Perustelut ehdotukselle   

Maantieteellinen joen nimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallishistoriallinen, luonnontieteellinen, maantieteellinen. 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Meltausjoki](http://finto.fi/yse/fi/page/Y508771)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10499303
