### ISSUE TITLE
Vallitunsaari (Kemi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8772]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Vallitunsaari (Kemi) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vallitunsaaren lapset 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Vallitunsaari (Kemi)](http://finto.fi/yse/fi/page/Y508772)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10747020
