### ISSUE TITLE
Ylikartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8773]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Ylikartano](http://www.yso.fi/onto/ysa/Y105775) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Käytetty myös muista kuin Mäntsälässä olevista kartanoista. Samanniminen kartano myös muualla (Taivalkoski, Hämeenlinna, Toholampi, Tyrnävä)

**Comment by mirmaid** [comment]
Melindassa Ylikartano (Mäntsälä) ja Ylikartano (Hattula/Retulansaari)
