### ISSUE TITLE
vuokaaviot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8774]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vuokaaviot](http://www.yso.fi/onto/ysa/Y101451) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "prosessikaaviot" 

#### Perustelut ehdotukselle   

Vuokaavioita nimitetään myös prosessikaavioiksi, joten viittaus vastaavaan asiasanaan olisi hyväksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. processcheman

**Comment by YSO-kokous** [comment]
Hyväksytty
