### ISSUE TITLE
kalanviljelylaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8775]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kalanviljelylaitokset](http://www.yso.fi/onto/ysa/Y106183) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "kalankasvattamot" (fin) ja "fish hatcheries" (eng) sekä LCSH-siltaus asiasanaan "Fish hatcheries" [http://id.loc.gov/authorities/subjects/sh85048633] 

#### Perustelut ehdotukselle   

Finnasta löytyy 35 osumaa sanahaulla "kalankasvattamo", joten viittausmuoto voisi olla omiaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
