### ISSUE TITLE
raamattupiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8776]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

raamattupiirit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Eletty uskonto: arjen uskonnollisuudesta ja sen tutkimuksesta 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [raamattupiirit](http://finto.fi/yse/fi/page/Y508776)

**Comment by jtuohini** [comment]
LT-suhteiksi ehkä [**kirjallisuuspiirit**](http://www.yso.fi/onto/yso/p17413) (KT _lukupiirit_) ja [opintokerhot](http://www.yso.fi/onto/yso/p17706) (KT _opintopiirit_)? KT-muodoksi varmaan _raamattuluokat_, joka on vanhoillislestadiolaisten käyttämä nimitys kyseiselle harrastukselle ainakin Wikipedian [https://fi.wikipedia.org/wiki/Raamattuluokka] mukaan. Ja muutama englanninkielinen vastine: **_Bible study groups_** sekä **_base communities_**, **_basic ecclesial communities_**, **_class meetings_** [https://en.wikipedia.org/wiki/Cell_group], [https://en.wikipedia.org/wiki/Basic_ecclesial_community].

LCSH-siltaus haasteellinen tehtävä: [**Bible--Study and teaching**](http://id.loc.gov/authorities/subjects/sh85013718) ei mene yksiin eikä [**Bible--Societies, etc.**](http://id.loc.gov/authorities/subjects/sh85013716) (KT _Bible--Study and teaching--Societies_) laisinkaan (jälkimmäinen "[- -] societies organized for professional and scholarly study of the Bible [- -]". Ja viitattuun Wikipedia-artikkeliin liittyen LCSH:n vastaavalta vaikuttava asiasana [**Cell churches**](http://id.loc.gov/authorities/subjects/sh2004007845) (KT _Cell groups (Christianity)_) viittaa sekin jossian määrin itsellisiin pikkukirkkoihin eikä pelkkiin raamattupiireihin, vaikka se ytimenä pohjalla olisikin (ja tietysti aivan eri asia kuin [**House churches**](http://id.loc.gov/authorities/subjects/sh85062540)).

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. bibelkretsar ET bibelcirklar, bibelstudiecirklar
