### ISSUE TITLE
sedat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8777]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sedat 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Eletty uskonto: arjen uskonnollisuudesta ja sen tutkimuksesta 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [sedat](http://finto.fi/yse/fi/page/Y508777)

**Comment by jtuohini** [comment]
Mihin tämä ehdotettu asiasana viittaa? Googlaamalla ei löydy mitään järkevän tuntuista. Onko vain kirjoitusvirhe (p.o. "seidat" - joka tosin on jo YSO:ssa)?

**Comment by mirmaid** [comment]
Ehdotuksen mukaan ortodoksinen vähemmistöryhmittymä Virossa. Viittaisikohan kuitenkin setukaisiin?

**Comment by ilona-x** [comment]
Ehdotuksessa mainitussa kirjassa näyttää olevan artikkeli: "Eletty uskonto arkistossa : pyhät kuvat arkiston teksteissä ja setojen elämässä"

**Comment by YSO-kokous** [comment]
hyväksytään ohjausterminä: setot KÄ setukaiset
