### ISSUE TITLE
dekriminalisointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8781]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dekriminalisointi 

#### Ehdotettu termi englanniksi   

decriminalization 

#### Ehdotettu termi ruotsiksi   

avkriminalisering 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kohdistuva toiminta](http://www.yso.fi/onto/yso/p38217) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85036356> 
WIkipedia : https://fi.wikipedia.org/wiki/Dekriminalisointi 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Drug decriminalization policy : literature review : models, implementation and outcomes 

#### Perustelut ehdotukselle   

tarve kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [dekriminalisointi](http://finto.fi/yse/fi/page/Y508781)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. avkriminalisering ET dekriminalisering 
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/avkriminalisering
Tärkeä termi.
