### ISSUE TITLE
erikoistuomioistuimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8782]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[erikoistuomioistuimet](http://www.yso.fi/onto/ysa/Y101283) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

erikoistuomioistuimet muutetaan muotoon erityistuomioistuin 

#### Perustelut ehdotukselle   

olemme tekemässä yhteisötyyppilistausta toimijakuvailuverkoston kanssa. meille olisi tulossa erityistuomioistuin, koska tätä termiä käytetään yleisesti (katso esim. nämä: https://tieteentermipankki.fi/wiki/Oikeustiede:erityistuomioistuin "Vanhemmassa oikeuskielessä erityistuomioistuimia (specialdomstolar) kutsuttiin erikoistuomioistuimiksi." ja 
https://eur-lex.europa.eu/summary/glossary/specialised_court.html?locale=fi ja https://oikeus.fi/tuomioistuimet/fi/index.html). Onko kyse samasta asiasta? Olisi ainakin hyvä kuulla jonkinlaista perustelua, miksi on päädytty tekemään näin eikä toisin. 

#### Ehdottajan organisaatio   

Kansalliskirjasto, Toimijakuvailuverkosto

**Comment by mirmaid** [comment]
Termi on otettu sanastoon v.1986, liekö vanhempi oikeuskieli ollut vielä käytössä 🙂. On samassa muodossa myös EKS-sanastossa.

**Comment by YSO-kokous** [comment]
Kysytään vielä Eduskunnan kirjaston kantaa.

**Comment by ilona-x** [comment]
Tuomioistuinsanasto
Tietueen lähde Tuomioistuinsanasto (2001), luku: Tuomioistuimet (käsite 18)

**fi:   	erityistuomioistuin    suositettava termi**
fi:	erikoistuomioistuin
	  
Määritelmä:	  	laissa erikseen määrättyjä asiaryhmiä käsittelevä tuomioistuin	  

sv:  	specialdomstol
	  
Määritelmä:	  	domstol som behandlar i lag särskilt bestämda kategorier av mål eller ärenden	  

Tuomioistuinsanasto (c) valtioneuvoston kanslia 2001
