### ISSUE TITLE
kinkerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8784]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kinkerit](http://www.yso.fi/onto/ysa/Y102485) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "lukuset" 

#### Perustelut ehdotukselle   

"Kinkerit, lukukinkerit tai lukuset olivat rippikoulua edeltäneitä opetus- ja kuulustelutilaisuuksia Suomen maaseutualueilla." [https://fi.wikipedia.org/wiki/Kinkerit] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
