### ISSUE TITLE
taigametsähanhi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8785]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taigametsähanhi 

#### Ehdotettu termi englanniksi   

Taiga bean goose 

#### Vaihtoehtoiset termit ja ilmaisut   

Anser fabalis fabalis 

#### Ehdotettu yläkäsite YSOssa (LT)   

[metsähanhi](http://www.yso.fi/onto/yso/p38983) 

#### Vastaava käsite muussa sanastossa   

Laji.fi : https://laji.fi/taxon/MX.292022/taxonomy 

#### Tarkoitusta täsmentävä selite   

Huom. metsähanhen eng. termimuoto nyt taiga been goose  
Lisäksi LCSH: bean goose ei linkattu YSOon http://id.loc.gov/authorities/subjects/sh85012643 

#### Perustelut ehdotukselle   

tarve aineiston kuvailussa
Melinda:
taigametsähanhi x 7
tundrametsähanhi x 9 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Evolutionary and conservation genetics of European domestic and wild geese 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [taigametsähanhi](http://finto.fi/yse/fi/page/Y508785)

**Comment by ilona-x** [comment]
Jos tämä metsähanhen alalaji otetaan, voisi samalla ottaa myös toisen alalajin eli tundrametsähanhen (Anser fabalis rossicus)
 http://tun.fi/MX.292023

**Comment by mariaforsen** [comment]
Sv. 
-tajgasädgås
-tundrasädgås
