### ISSUE TITLE
koukkuaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8786]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koukkuaminen](http://www.yso.fi/onto/ysa/Y102731) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

koukkuaminen (virkkaus) 

#### Perustelut ehdotukselle   

YSOn koukkuaminen viittaa virkkaustekniikkaan, eng. tunisian crochet
https://fi.wikipedia.org/wiki/Koukkuaminen

Koukkumisella voidaan tarkoittaa myös taustakankaalle tehtävää kirjontaa, eng. rug hooking.
https://tekstijatikki.fi/2020/09/22/kaksi-tekniikkaa-yhden-hinnalla/
https://en.wikipedia.org/wiki/Rug_hooking 

#### Ehdottajan organisaatio   

kk

**Comment by mariaforsen** [comment]
Sv. krokning (virkning) ET tunisisk virkning, stickvirkning, afghanvirkning
