### ISSUE TITLE
laki asuinhuoneiston vuokrauksesta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8787]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

laki asuinhuoneiston vuokrauksesta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Laki asuinhuoneiston vuokrauksesta : kommentaari  978-951-685-512-0 

#### Perustelut ehdotukselle   

kattava kirja ko. laista 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [laki asuinhuoneiston vuokrauksesta](http://finto.fi/yse/fi/page/Y508787)

**Comment by jtuohini** [comment]
Ja tämäkin on RDA:n näkökulmasta teos eli hakutieto pitäisi muodostaa [luvun 6.19.1.2](http://original.rdatoolkit.org/rdachp6-fi_rda6-8414.html) mukaan. Marc 21 -muotoon puettuna auktoriteettitietue olisi siis "110 1_ |a Suomi. |t Laki asuinhuoneiston vuokrauksesta", ei suinkaan 150, kuten asiasanat.

**Comment by mariaforsen** [comment]
Sv. lag om hyra av bostadslägenhet
