### ISSUE TITLE
vaellusratsastus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8788]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vaellusratsastus 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781570769603 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [vaellusratsastus](http://finto.fi/yse/fi/page/Y508788)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

https://www.ratsastus.fi/lajit/muut-lajit/vaellusratsastus/

KT ratsastusvaellukset

**Comment by mariaforsen** [comment]
YSOssa on jo maastoratsastus eng. trail riding
Yksikielinen wikipedia-sivu https://fi.wikipedia.org/wiki/Ratsastusvaellus Olisiko tälle eng. termi? Epäselvää miten saisi ruotsiksi käännetty.
Sanakirjoista ei löydy, mutta kylläkin retkiratsastus=turridning

**Comment by YSO-kokous** [comment]
vaellusratsastus KT retkiratsastus

**Comment by mariaforsen** [comment]
Sv. terräng- och turridning
ET utflyktsridning

**Comment by mirmaid** [comment]
Soveltuvien kielivastineiden löytäminen osoittautui mahdottomaksi, joten päädyin ehdottamaan, että muutetaan käsitettä maastoratsastus > maasto- ja vaellusratsastus. Lisäksi maastoratsastus (kenttäratsastus) KÄ kenttäratsastus, koska nyt on Melindassa käytetty maastoratsastus-käsitettä, kun kyse on kenttäratsastuksesta, jossa yhtenä osana on maasto**este**ratsastus (mikä taas on hyvin eri asia kuin tavallinen maasto/vaellusratsastus).
