### ISSUE TITLE
perunan tummarengasmätä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8789]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

perunan tummarengasmätä 

#### Ehdotettu termi englanniksi   

Bacterial wilt of potato 

#### Ehdotettu termi ruotsiksi   

mörk ringröta på potatis 

#### Vaihtoehtoiset termit ja ilmaisut   

Pseudomonas solanacearum 
perunantummarengasmätä 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvitaudit](http://www.yso.fi/onto/yso/p8076) 

#### Vastaava käsite muussa sanastossa   

perunantummarengasmätä : <http://www.yso.fi/onto/afo/p1493> 
Bacterial wilt of potato : <http://id.loc.gov/authorities/subjects/sh85010859> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Valmiussuunnitelma perunan tummarengasmädän varalle :(Ralstonia solanacearum -bakteeri) /tekijät: Milja Keskinen, Mirkka Soukainen, Leila Keinänen. 

**Ehdottajan organisaatio:** kk **Termiehdotus Fintossa:** [perunan tummarengasmätä](http://finto.fi/yse/fi/page/Y508789)

**Comment by mirmaid** [comment]
Näköjään usein pelkkä tummarengasmätä.

**Comment by mariaforsen** [comment]
Sv. mörk ringröta https://www.dyntaxa.se/Taxon/Info/6035117?changeRoot=True

**Comment by YSO-kokous** [comment]
Hyväksytään tummarengasmätä KT perunan tummarengasmätä
