### ISSUE TITLE
sukeltajasorsat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8790]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sukeltajasorsat](http://www.yso.fi/onto/ysa/Y109320) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitaan selvennystä/latinankielisten nimien vahvistamista tälle termille ja puolisukeltajasorsat-termille 

#### Perustelut ehdotukselle   

Näitä nimityksiä ei löydy laji.fi:stä.
Tarkistetaan myös ruotsinnokset tämän jälkeen.

**Comment by jarmosaarikko** [comment]
YSO:n hierarkia on nyt pielessä, kun sorsat (suku) (Anas) on lipsahtanut väärälle tasolle ja sille on merkitty alakäsitteksi muita sukuja. Seuraava olisi laji.fi hierarkian mukainen ryhmittely, §-merkillä merkityt ovat tai tulisi olla YSOssa.
**Sorsat** -termin osalta ongelma on heimon ja suvun erottaminen toisistaan. Jos heimo jätetään pois hierarkiasta, ongelmaa ei ole.  Mikäli jossakin suvussa on enemmän kuin yksi laji, se voidaan ottaa väliportaaksi. Jos suku jätetään pois hierarkiasta, niin näiden sukujen lajit näkyvät hierarkiassa samalla tasolla kuin suvut, joissa on useampia lajeja.
```
§ sorsalinnut  (Anseriformes, lahko)
    - sorsat  (Anatidae, heimo)
        § joutsenet (Cygnus, suku)
                § kyhmyjoutsen
                § laulujoutsen
        § harmaahanhet (Anser, suku)
                § kiljuhanhi 
                § merihanhi
                § metsähanhi
        § kirjohanhet (Branta, suku)
                § kanadanhanhi 
                § valkoposkihanhi 
      -  (Clangula, suku)
      § alli 
      -  haahkat (Somateria, suku)
      § haahka 
      -  mustalinnut (Melanitta, suku)
      § pilkkasiipi 
      - telkät (Bucephala, suku)
      § telkkä 
      - koskelot (Mergus, suku)
      § isokoskelo 
     - ristisorsat (Tadorna, suku)
     § ristisorsa 
     § sotkat (Aythya, suku)
              § punasotka 
              § tukkasotka 
    - haapanat (Mareca, suku) 
    § haapana 
    § sorsat (Anas, suku)
             § tavi 
             § sinisorsa
                   § ankka (rotu)
    - lapasorsat (Spatula, suku)
    §  heinätavi 
```
Edellä siis taksonomian mukainen ryhmittely.  Nuo muut kuuluisivat hierarkiassa hierarkisoivan käsitteen alle: "sorsalinnut tyypin mukaan" (YK sorsalinnut)  ja tyypit ovat: 
- hanhet ( 5 lajia), 
- sukeltajasorsat (alli, telkkä, haahka, pilkkasiipi, isokoskelo, punasotka, tukkasotka) sekä  
- puolisukeltajasorsat (tavi, sinisorsa, heinätavi, ristisorsa, haapana)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Puolisukeltajat
https://fi.wikipedia.org/wiki/Kokosukeltajasorsat

**Comment by mirmaid** [comment]
^ Tarvitaanko vielä lisäselvitystä?

**Comment by mariaforsen** [comment]
Onko siis puolisukeltajat/puolisukeltajasorsat=Anatinae, kuten Wikipediassa väitetään? Jos on niin ehdotan lisättäväksi ohjausterminä, ja muutetaan sen mukaiseksi myös ruotsiksi. Tai sitten tehdään laji.fi:n mukaisesti (ei puolisukeltajat-termiä).

Vastaava kysymys sukeltajasorsat-termin kohdalla, eli mihin lat.kieliseen nimitykseen se viittaa, jos pidetään (vaikkei ole laji:fi:ssä)? 

Eli selvitetään mihin tarkalleen viitataan näillä nimityksillä, jotta saadaan myös yksiselitteiset vastineet.

**Comment by mirmaid** [comment]
Kokosukeltajat näyttää ainakin wikipediassa olevan sv. dykänder, joka vastaa tuota suomenkielistä muotoakin.
