### ISSUE TITLE
pulssioksimetria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8791]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pulssioksimetria 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Deep learning for next generation sleep diagnostics - Sophisticated computational methods for more efficient and accurate assessment of sleep and obstructive sleep apnea 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [pulssioksimetria](http://finto.fi/yse/fi/page/Y508791)

**Comment by ilona-x** [comment]
pulssioksimetria ei löydy FinMeSHistä
FinMeSH: **oksimetria** http://www.yso.fi/onto/mesh/D010092

--

LCSH: **oximetry** http://id.loc.gov/authorities/subjects/sh85096318

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Pulssioksimetria

Lääketieteen termit:
- oksimetria: verenpunan happikyllästeisyyden mittaus
- pulssioksimetria: verenpunan happikyllästeisyyden mittaus esim. sormeen tai korvalehteen kiinnitetyn anturin avulla

**Comment by mariaforsen** [comment]
Sv. pulsoximetri

**Comment by YSO-kokous** [comment]
Hyväksytään  muodossa oksimetria

**Comment by mariaforsen** [comment]
Sv.  oximetri ET syrgasmätning
