### ISSUE TITLE
aivokalvo(t)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8792]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aivokalvo(t) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.uef.fi/fi/artikkeli/miksi-migreenikipu-tykyttaa-ja-pitkittyy 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aivokalvo(t)](http://finto.fi/yse/fi/page/Y508792)

**Comment by mirmaid** [comment]
Myös Kseniia Koroleva

**Comment by ilona-x** [comment]
FinMeSH: aivo- ja selkäydinkalvot http://www.yso.fi/onto/mesh/D008578
https://fi.wikipedia.org/wiki/Aivo-_ja_selk%C3%A4ydinkalvot

**Comment by mariaforsen** [comment]
Sv. hjärnhinnor ET  hjärn- och ryggmärgshinnor, meninger
