### ISSUE TITLE
Levanto (Mäntsälä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8793]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Levanto (Mäntsälä) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Levantoo, kylä joka nousi tuhkasta 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Levanto (Mäntsälä)](http://finto.fi/yse/fi/page/Y508793)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10697419
