### ISSUE TITLE
Ala-Luosta (Rautavaara)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8794]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ala-Luosta (Rautavaara) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ala-Luosta: elämää ja muistoja järven ympäriltä 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Ala-Luosta (Rautavaara)](http://finto.fi/yse/fi/page/Y508794)

**Comment by ilona-x** [comment]
ei Paikkatietoalustalla (löytyy vain järvi)

**Comment by mirmaid** [comment]
Alastarolla: Kylä, järvi Rautavaaralla.

**Comment by mirmaid** [comment]
https://www.rautavaara.fi/asukkaille/asuminen-ja-ymparisto/kylat/ala-luosta/
