### ISSUE TITLE
varjoaineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8795]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

varjoaineet 

#### Ehdotettu termi englanniksi   

Contrast media 

#### Ehdotettu termi ruotsiksi   

kontrastmedel 

#### Vaihtoehtoiset termit ja ilmaisut   

Contrast Agents 

#### Vastaava käsite muussa sanastossa   

LCSH : Contrast media (Diagnostic imaging) 
FinMeSH : <http://www.yso.fi/onto/mesh/D003287> 
Wikipedia : https://fi.wikipedia.org/wiki/Varjoaine 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Nanoparticles as magnetic resonance imaging contrast agents : feasibility studies on cell labelling, acute myocardial infarct imaging and articular cartilage imaging 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [varjoaineet](http://finto.fi/yse/fi/page/Y508795)

**Comment by mirmaid** [comment]
Sanastossa on _varjoainetutkimus_.

4 kertaa Melindassa.
