### ISSUE TITLE
taalerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8796]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taalerit](http://www.yso.fi/onto/ysa/Y197331) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde "raha" --> "metallirahat" ja lisätään KT-muoto "plootut" 

#### Perustelut ehdotukselle   

Taalerit ovat nimenomaan lyötyä rahaa eli metallirahaa. Plootuista taaleriarvoisina rahoina ks. esim. https://sv.wikipedia.org/wiki/Plåtmynt 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ei sittenkään plootuja KT-suhteeksi, vaan se omaksi asiasanakseen, ks. https://github.com/Finto-ehdotus/YSE/issues/8797!
