### ISSUE TITLE
plootut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8797]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

plootut 

#### Ehdotettu termi ruotsiksi   

plåtmynt 

#### Ehdotettu termi englanniksi   

plate money 

#### Vaihtoehtoiset termit ja ilmaisut   

plåt [swe] 
plooturahat [fin] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taalerit](http://www.yso.fi/onto/yso/p27270) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85103236> 
Wikidata : https://www.wikidata.org/wiki/Q1410856 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Finnassa huomattavan monta osumaa niin artikkeleita kuin kuva-aineistoa plootuista, joten tarkalle asiasanalle on tilausta ("metallirahat" aivan liian epätarkka plootuihin niiden omaleimaisuuteen nähden) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [plootut](http://finto.fi/yse/fi/page/Y508797)

**Comment by mirmaid** [comment]
MAOssa. Melindassa 3 kertaa plootut, 4 kertaa plooturahat (masa).
