### ISSUE TITLE
uskomushoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8800]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uskomushoito 

#### Perustelut ehdotukselle   

Tällä termillä kuvattaisiin osuvasti niitä vaihtoehtoisa hoitomuotoja, joiden perustana on luja usko parantumiseen. Tällä voisi myös erottaa ne hoitomuodot, joita ei ole (lääke-)tieteellisesti todistettu vaikuttaviksi. Muistaakseni luin jokin aika sittenTiina Raevuoren kolumnin Suomen Kuvalehdestä, jossa hän käytti po. käsitettä. (Viimeinen lause ei ole perustelu, mutta halusin tuoda esille, etten ole itse käsitettä luonut.) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Viimeisin on teos Eroon oireista / Maria Nordin. 

**Termiehdotus Fintossa:** [uskomushoito](http://finto.fi/yse/fi/page/Y508800)

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjasta löytyy myös samainen: https://www.kielitoimistonsanakirja.fi/uskomushoito! Vrt. myös https://www.kielitoimistonsanakirja.fi/uskomuslääkintä
 
Pitäisikö muuten olla asiasanana monikossa (**_uskomushoidot_**)?

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjassa siis uskomushoito > uskomuslääkintä: _tieteelliseen tutkimukseen perustuvan lääkinnän ulkopuolelle jäävät hoitomenetelmät, vaihtoehtolääkintä_. 

Ehdotettu myös: https://github.com/Finto-ehdotus/YSE/issues/8877

**Comment by mariaforsen** [comment]
https://researchportal.helsinki.fi/sv/publications/uskomushoito-tarkoittaa-eri-asiaa-kuin-cam
cam=complementary and alternative medicine=komplementär- och alternativmedicin=vaihtoehtolääkintä..?
https://fi.wikipedia.org/wiki/T%C3%A4ydent%C3%A4v%C3%A4t_ja_vaihtoehtoiset_hoidot = https://en.wikipedia.org/wiki/Alternative_medicine
Ruotsiksi päätermi on miten vain alternativmedicin tms., "uskoon liittyvää" termiä ei ole. 

Uskomushoito ei ole mitenkään kiistaton termi, ks. esim. http://www.laakaripaivat.fi/2013/media/tiedotteet/ennakkoinfon-tiedotteet/onko-olemassa-nayttoon-perustuvia-vaihtoehtohoitoja/index.html "Eräät suomalaiset lääkärit kutsuvat vaihtoehtohoitoja uskomushoidoiksi. ”Uskomushoito” on sanana epäonnistunut. Kaikki vaihtoehtohoidot eivät ole uskomuksia ja eräät koululääketieteen hoidot ovat uskomuksia. Näyttöön perustuva lääketiede syntyi kritiikkinä koululääketieteen sisäisiä uskomuksia kohtaan eikä vaihtoehtohoitoja kohtaan. ”Uskomushoito” on lisäksi halventava sana."

**Comment by krinay** [comment]
"Termi uskomuslääkintä on uudissana, joka voitti Duodecimin sanakilpailun vuonna 1995. Sana uskomushoito on erityisesti vaihtoehtohoitoihin kielteisesti suhtautuvien käytössä." https://fi.wikipedia.org/wiki/Uskomusl%C3%A4%C3%A4kint%C3%A4

**Comment by LeKorsu** [comment]
En tiedä miten pitkälle lainsäädäntötyö on edennyt ministeriössä, mutta tässä käytetään vaihtoehtohoitoja
https://www.valvira.fi/terveydenhuolto/hyva-ammatinharjoittaminen/vaihtoehtohoidot

**Comment by FinMeSHienPaimentaja** [comment]
Ruotsinnokseksi on ehdotettu termiä "poikkeava hoito":

_Uskomushoito-sanalle ei löydy suoraa ruotsinnosta. Poikkeava hoito olisi ruotsiksi avvikande sjukvård tai avvikande medicin._

Wahlberg, Peter
Entä jos puhuisimme poikkeavasta hoidosta?
Suomen lääkärilehti - Finlands läkartidning  2018  vol. 73  no. 11  s. 695    
Kirje. Kommentti
http://www.laakarilehti.fi/ajassa/keskustelua/enta-jos-puhuisimme-poikkeavasta-hoidosta/
http://www.laakarilehti.fi/pdf/2018/SLL112018-694.pdf

**Comment by mariaforsen** [comment]
Ruotsiksi pitää edelleen käyttää se mikä oikeasti on käytössä eli alternativ/komplementär medicin tms. EI siis voida tässä sanastossa keksiä omia ja luoda sellaista termiä kuin "avvikande..." tms. (joka ei myöskään merkitykseltään mitenkään vastaa "uskomushoito"-termiä). Eikä myöskään voida yhden lehtiartikkelin (mielipidekirjoituksen) perusteella tehdä sellaista "luovaa työtä".

**Comment by krinay** [comment]
LCSH: Alternative medicine http://id.loc.gov/authorities/subjects/sh85134721

**Comment by YSO-kokous** [comment]
Hyväksytään ohjausterminä:  uskomushoito KÄ vaihtoehtolääkintä
