### ISSUE TITLE
sebelipaasi alfa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8801]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sebelipaasi alfa 

#### Ehdotettu termi englanniksi   

sebelipase alfa 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Sebelipase_alfa
Sebelipase alfa, sold under the brand name Kanuma, is a recombinant form of the enzyme lysosomal acid lipase (LAL) that is used as a medication for the treatment of lysosomal acid lipase deficiency (LAL-D). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-5624-84-7 

**Termiehdotus Fintossa:** [sebelipaasi alfa](http://finto.fi/yse/fi/page/Y508801)

**Comment by mirmaid** [comment]
Voidaan ottaa (YK lääkeaineet), aineistoa ei välttämättä tule kovin paljon. Tarvittaisiinko jokin laajempi termi vastaaville, MeSHissä on _harvinaislääkkeen tuotanto_, http://www.yso.fi/onto/mesh/D009965. Lääketieteen termit: harvinaislääke: _harvinaistautiin käytettävä lääkeaine, jonka tutkimiseen ja valmistamiseen on kaupallisissa lääkeyhtiöissä menekin vähäisyyden takia usein vain vähän kiinnostusta_.

Melindassa 9 kertaa harvinaislääkkeet. (KT orpolääkkeet)

**Comment by mariaforsen** [comment]
Kannatan harvinaislääkkeet=särläkemedel 
https://www.fimea.fi/myyntiluvat/myyntilupahakemus/harvinaislaakkeet

**Comment by YSO-kokous** [comment]
Hyväksytty "harvinaislääkkeet" sekä sebelipaasi alfa

**Comment by mariaforsen** [comment]
Sv. 
-särläkemedel https://termipankki.fi/tepa/en/search/harvinaisl%C3%A4%C3%A4ke
-sebelipas alfa https://www.fass.se/LIF/substance?userType=0&substanceId=ID6350708058371329
