### ISSUE TITLE
Wolmanin tauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8802]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Wolmanin tauti 

#### Ehdotettu termi englanniksi   

lysosomal acid lipase deficiency 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-952-5624-84-7 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Wolmanin_tauti
lysosomaalinen kertymäsairaus 

**Termiehdotus Fintossa:** [Wolmanin tauti](http://finto.fi/yse/fi/page/Y508802)

**Comment by mariaforsen** [comment]
Sv. Wolmans sjukdom https://finto.fi/mesh/fi/page/D015223
