### ISSUE TITLE
savuttomuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8803]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

savuttomuus 

#### Ehdotettu termi englanniksi   

smoke-free policy 

#### Ehdotettu termi ruotsiksi   

rökfri policy 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.oph.fi/sites/default/files/documents/savupilvi_portin_ylla.pdf 

#### Perustelut ehdotukselle   

Löytyy FinMeSHistä, tupakoimattomuus ei aja asiaa. 

**Termiehdotus Fintossa:** [savuttomuus](http://finto.fi/yse/fi/page/Y508803)

**Comment by jtuohini** [comment]
LCSH-siltaus: [**Nonsmoking areas**](http://id.loc.gov/authorities/subjects/sh87003516) ja "policy"-käsitteen suuntaan painottaen **Nonsmoking areas--Government policy**? Joskin kuvailtavaksi tarkoitetun aineiston kannalta kyse ehkä ennemmin: [**Smoking cessation**](http://id.loc.gov/authorities/subjects/sh88006409), jonka KT-muotona on mm. _Smoking cessation programs_. Vrt. esim. https://lccn.loc.gov/90620604.

**Comment by mirmaid** [comment]
Savuttomuus ei terminä kovin selkeästi eroa tupakoimattomuudesta. Tupakointikiellot ehkä?

**Comment by mariaforsen** [comment]
YSOssa tupakoimattomuus=rökfrihet(=myös savuttomuus). En näe olennaista eroa. 
Termille tupakointikiellot olisi vastine, rökförbud.

**Comment by YSO-kokous** [comment]
hyväksytään muodossa "savuttomat tilat" KT savuttomuus  (tilat)

**Comment by mariaforsen** [comment]
Sv. rökfria miljöer ET rökfria områden/utrymmen/lokaler
