### ISSUE TITLE
tanssioppilaitokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8804]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssioppilaitokset](http://www.yso.fi/onto/ysa/Y104982) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "tanssikoulut" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja KT:ksi myös _tanssiopistot_.

**Comment by YSO-kokous** [comment]
Hyväksytty
