### ISSUE TITLE
reaalikorko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8805]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

reaalikorko 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/309298 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [reaalikorko](http://finto.fi/yse/fi/page/Y508805)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Reaalikorko

Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. realränta
