### ISSUE TITLE
millimetriaallot (erikseen)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8807]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

millimetriaallot (erikseen) 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://aaltodoc.aalto.fi/handle/123456789/46312 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [millimetriaallot (erikseen)](http://finto.fi/yse/fi/page/Y508807)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Extremely_high_frequency
LCSH: http://id.loc.gov/authorities/subjects/sh85085407

11 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. millimetervågor

**Comment by YSO-kokous** [comment]
Hyväksytty  uutena käsitteenä millimetriaallot
