### ISSUE TITLE
aihemallinnus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8808]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aihemallinnus 

#### Ehdotettu termi englanniksi   

topic modelling 

#### Perustelut ehdotukselle   

Aihemallinnus on ihmistieteissä, esim. yhteiskuntatieteissä käytetty koneoppimisen menetelmä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/310459 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aihemallinnus](http://finto.fi/yse/fi/page/Y508808)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Topic_model

**Comment by osma** [comment]
+1 minun puolestani. Ihan vakiintunut menetelmä, josta tosin usein puhutaan vain englanninkielisellä nimellä.

Yläkäsitteeksi voisi sopia esim. [tekstinlouhinta](http://www.yso.fi/onto/yso/p27112)

**Comment by mariaforsen** [comment]
Sv. ämnesmodellering 
https://digiteket.se/inspirationsartikel/artificiell-intelligens-moter-kbs-stora-samlingar/

**Comment by YSO-kokous** [comment]
Hyväksytty
