### ISSUE TITLE
tietokirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8809]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietokirjallisuus](http://www.yso.fi/onto/ysa/Y99514) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "tiedekirjallisuus" ja "tutkimuskirjallisuus" tai tarpeen tullen mukaan tehdään näistä omat asiasanansa. 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Melindassa tiedekirjallisuus 2 kertaa, tutkimuskirjallisuus 5 kertaa.

**Comment by krinay** [comment]
Joissakin yhteyksissä tietokirjojen ja tiedekirjojen välillä nähdään selvä ero, 
http://neba.finlit.fi/blogi/mita-eroa-on-tiedekirjoilla-ja-tietokirjoilla/. Mutta ero ei tietenkään aina ole selvä (https://journal.fi/tt/article/view/56597). Voi olla, että kaksi eri varsinaista asiasanaa hankaloittaisi sisällönkuvailua ja tiedonhakua.

**Comment by mariaforsen** [comment]
Sv. vetenskaplig litteratur, forskningslitteratur. Varsinkin tutkimuskirjallisuus on kyllä oma lajinsa, voisi olla erillisenä terminä.

**Comment by mirmaid** [comment]
_Tutkimusraportit_ löytyy.

**Comment by YSO-kokous** [comment]
Siirretään SLM kokoukselle.

**Comment by ilona-x** [comment]
"Tutkimuskirjallisuus = tutkimuksesi teoreettinen kehys, tieteellisiä julkaisuja, kuten artikkeleita ja kirjoja aiheestasi. "
Lähde: https://koppa.jyu.fi/avoimet/kirjasto/kirjastotuutori/aihehaku-tutkimusprosessissa/menetelmatietoa-ja-palveluja

Jos tutkimuskirjallisuus määritellään yllä olevalla tavalla, ei tutkimuskirjallisuus ole hyödyllinen termi, sillä mikä tahansa kirjallisuuus voisi olla tutkimuskirjallisuutta.

**Comment by ilona-x** [comment]
https://www.suomentietokirjailijat.fi/kirjailijalle/jaseneksi-liittyminen/tietokirjallisuuden-lajit.html

**Comment by jtuohini** [comment]
http://neba.finlit.fi/blogi/mita-eroa-on-tiedekirjoilla-ja-tietokirjoilla/

**Comment by mirmaid** [comment]
SLM:ssä kaivattiin enemmän hierarkkista yläkäsitettä tietoaineistoille. Tutkimuskirjallisuus ja tiedekirjallisuus -termit ovat ongelmallisia, eikä käyttötarve ole selkeä. 

Takaisin YSO-kokoukseen.

**Comment by YSO-kokous** [comment]
Ei oteta kumpaakaan ohjaustermiksi.

**Comment by jtuohini** [comment]
SLM:n hierarkkinen yläkäsite, ks. https://github.com/Finto-ehdotus/YSE/issues/9470
