### ISSUE TITLE
heteroseksismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8811]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

heteroseksismi 

#### Ehdotettu termi englanniksi   

heterosexism 

#### Ehdotettu termi ruotsiksi   

heterosexism 

#### Perustelut ehdotukselle   

Termiä ei löydy YSOn sanastosta ja se on erittäin ajankohtainen käsite seksuaali- ja sukupuolentutkimuksessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Overcoming heterosexism and homophobia : strategies that work 

**Termiehdotus Fintossa:** [heteroseksismi](http://finto.fi/yse/fi/page/Y508811)

**Comment by jtuohini** [comment]
LCSH-siltaus: [**Heterosexism**](http://id.loc.gov/authorities/subjects/sh93002513).

Mistä mieleen juontuen: mikä on ehdotetun suhde nykyiseen [**heteronormatiivisuus**](http://www.yso.fi/onto/yso/p20827)-asiasanaan? Vrt. mainitun LCSH-asiasanan viittaussuhde _Heteronormativity_ KÄ **Heterosexism**.

**Comment by mirmaid** [comment]
^ Ovathan ne hyvin likeisiä, wikipediassakin kuitenkin omat sivunsa kummallekin: 
_Heteronormativity is the belief that heterosexuality is the default, preferred, or normal mode of sexual orientation.
Heterosexism is a system of attitudes, bias, and discrimination in favor of opposite-sex sexuality and relationships._

**Comment by mirmaid** [comment]
4 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Myös SAOssa molemmat, on eri merkitys. 
https://id.kb.se/term/sao/Heterosexism
https://id.kb.se/term/sao/Heteronormativitet

**Comment by YSO-kokous** [comment]
Hyväksytty,   RT heteronormatiivisuus
