### ISSUE TITLE
hematologiset kasvaimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8812]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hematologiset kasvaimet 

#### Ehdotettu termi englanniksi   

Hematologic Neoplasms 

#### Ehdotettu termi ruotsiksi   

blodtumörer 

#### Vaihtoehtoiset termit ja ilmaisut   

hematologiset syövät 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvaimet](http://www.yso.fi/onto/yso/p2299) 
[veritaudit](http://www.yso.fi/onto/yso/p5886) 

#### Assosiatiiviset (RT)   

[leukemia](http://www.yso.fi/onto/yso/p18980) 
[lymfoomat](http://www.yso.fi/onto/yso/p20932) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D019337> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Identifying targetable genes across hematological malignancies 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hematologiset kasvaimet](http://finto.fi/yse/fi/page/Y508812)

**Comment by mariaforsen** [comment]
Sv. blodtumörer ET hematologiska tumörer
