### ISSUE TITLE
hermetismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8815]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hermetismi 

#### Ehdotettu termi ruotsiksi   

hermetism 

#### Ehdotettu termi englanniksi   

hermetism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[okkultismi](http://www.yso.fi/onto/yso/p530) 

#### Assosiatiiviset (RT)   

[esoterismi](http://www.yso.fi/onto/yso/p6603) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh85060409.html 
SAO : https://id.kb.se/term/sao/Hermetism 
Wikipedia : https://en.wikipedia.org/wiki/Hermeticism 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Corpus Hermeticum ; Smaragditaulu ja muita hermeettisiä kirjoituksia / Hermes Trismegistos ; suomeksi kääntäneet ja toimittaneet Sampsa Kiianmaa, H.M. Lampikoski ja Pentti Tuominen. 

**Termiehdotus Fintossa:** [hermetismi](http://finto.fi/yse/fi/page/Y508815)

**Comment by mirmaid** [comment]
17 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytty

**Comment by mirmaid** [comment]
Tarvitseeko tarkenteen: https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:hermetismi? Tarvitaanko erikseen kirjallisuudentutkimuksen yhteydessä?

**Comment by YSO-kokous** [comment]
Lisätään tarkenteet:  hermetismi (okkultismi),  hermetismi (runous) TAI hermetismi (lyriikka)
