### ISSUE TITLE
Riemannin monistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8817]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Riemannian manifolds 

#### Ehdotettu termi ruotsiksi   

Riemann mångfalder 

#### Ehdotettu termi suomeksi   

Riemannin monistot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[monistot](http://www.yso.fi/onto/yso/p28181) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85114045> 
Wikipedia : https://fi.wikipedia.org/wiki/Riemannin_monisto 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[04 Matematiikka. Tilastotiede](http://www.yso.fi/onto/yso/p26574) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Navier-Stokes equations on Riemannian manifolds 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda:
Riemannin monisto x 2
Riemannin monistot x 2
Riemannian manifolds x 60 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Riemannin monistot](http://finto.fi/yse/fi/page/Y508817)

**Comment by ilona-x** [comment]
toinen väitös, jossa olisi ollut tarpeen: Geodesic tomography problems on Riemannian manifolds  http://urn.fi/URN:ISBN:978-951-39-7958-4

**Comment by mariaforsen** [comment]
Sv. Riemannska mångfalder ET Riemannmångfalder
