### ISSUE TITLE
Reutuaapa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8820]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Reutuaapa 

#### Tarkoitusta täsmentävä selite   

Kylän nimi Tervolassa, Kemijoen itäpuolella. 

#### Perustelut ehdotukselle   

Maantieteellinen paikannimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallishistoriallinen, luonnontieteellinen, maantieteellinen. 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Reutuaapa](http://finto.fi/yse/fi/page/Y508820)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10483325
