### ISSUE TITLE
bahnarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8821]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bahnarit 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/Bahnarit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9786047703197 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [bahnarit](http://finto.fi/yse/fi/page/Y508821)

**Comment by mariaforsen** [comment]
Sv. bahnarer
