### ISSUE TITLE
tulipolte

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8823]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tulipolte 

#### Ehdotettu termi englanniksi   

fire blight 

#### Ehdotettu termi ruotsiksi   

päronpest 

#### Vaihtoehtoiset termit ja ilmaisut   

päronpest 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvitaudit](http://www.yso.fi/onto/yso/p8076) 

#### Vastaava käsite muussa sanastossa   

AFO : https://finto.fi/afo/fi/page/p3143 
LCSH : https://id.loc.gov/authorities/subjects/sh85048458.html 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 
[22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa: https://docplayer.fi/3912588-Eviran-julkaisuja-16-2006-varosuunnitelma-tulipolte-elintarviketurvallisuusvirasto-evira-kasvinsuojeluyksikko.html 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Varosuunnitelma tulipolte 

**Ehdottajan organisaatio:** kk **Termiehdotus Fintossa:** [tulipolte](http://finto.fi/yse/fi/page/Y508823)

**Comment by mirmaid** [comment]
Nimeä käytetään myös tautia aiheuttavasta bakteerista, auktorisoidaanko kasvitautina vai bakteerina (https://laji.fi/taxon/MX.63268)? Molemmat ratkaisut ok ja varmasti kuvailussa mahdotonta erottaa.

**Comment by satuniininen** [comment]
Sopii kumpi vaan.

**Comment by YSO-kokous** [comment]
Hyväksytty
