### ISSUE TITLE
Partakko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8824]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Partakko 

#### Tarkoitusta täsmentävä selite   

Kylän nimi Inarin kunnassa, Inarijärven pohjoispuolella. 

#### Perustelut ehdotukselle   

Maantieteellinen paikannimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallishistoriallinen, luonnontieteellinen, maantieteellinen. 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Partakko](http://finto.fi/yse/fi/page/Y508824)

**Comment by ilona-x** [comment]
Paikkatietoalusta: http://paikkatiedot.fi/so/1000772/10820733
