### ISSUE TITLE
SLM: manifestaatioon liittyvät termit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8826]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM: manifestaatioon liittyvät termit 

#### Perustelut ehdotukselle   

Päätettiin ohjeistaa termikohtaisesti tapauksissa, joissa termiä on tarkoitus käyttää kuvailuun vain silloin, kun se liittyy kuvailtavaan manifestaatioon (ei manifestaation sisältämään teokseen/teoksiin). Tietueeseen lisätään käyttöhuomautus, esim. Termillä kuvaillaan ainoastaan konkreettisia postikortteja. Postikortteja esittelevistä kuvateoksista käytetään SLM-termiä kuvateokset, kuvastot tms. ja sopivaa YSO-asiasanaa (esim. pääsiäiskortit). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

-

**Comment by mirmaid** [comment]
Työstettävät kokonaisuudet:
Ilona: kausijulkaisut
Mirja ja Liisa: päätason alla olevat termit
Marjut, Auli, Anna: monografiat

**Comment by AuHo22** [comment]
Hei,
lisään tähän ne termit, joita Marjutin ja Annan kanssa pidettiin alustavasti ongelmallisina:

blogit, puheet, esitelmät, haastattelut jne. – selviääkö muoto hierarkiasta vai tarvitaanko määritelmää?

taiteilijakirjat - määritelmä

aineskokoelmat - määritelmä

spekulatiivinen fiktio – määritelmä, suhde elokuviin ja peleihin (hierarkia)

henkilökuvat – voiko ruotsinkielistä termiä porträtt (skriftliga alster) käyttää elokuvista?

**Comment by mariaforsen** [comment]
Sv. porträtt (skriftliga alster) vain kirjallisista teoksista eli vaatii mahdollisesti muutoksia (personporträtt..?)
Toisaalta, SLM:ssä ei ole muotokuvat-termiä, eikä henkilökuvat-termiä rajata myöskään suomeksi pelkästään muuhun kuin maalaustaiteeseen. Kielitoimiston sanakirja: henkilökuva=kuva henkilöstä, muotokuva; henkilöhahmo.

**Comment by mirmaid** [comment]
Päätason alla: 

- mainokset
- tiedotteet, esitteet, lomakkeet - voiko näitä olla kuvateoksissa? Ei varmaan sentään kuolinilmoituksia...

**Comment by mirmaid** [comment]
kartastot YK kartat, tähtikartat lisätään
blogit > blogikirjoitukset
taiteilijakirjat: YSOn huomautus
aineskokoelmat: Jaakko laatii määritelmän (kysytään Kristiinan kommentti)
henkilökuvat > lisätään tarkenne henkilökuvat (henkilöhistoria)

**Comment by mirmaid** [comment]
Näille lisätään postikortti-tyyppinen huomautus:

- mainokset

**Comment by mirmaid** [comment]
Blogeilla on kaksi alakäsitettä?

aineskokoelmat: Jaakko laatii määritelmän (kysytään Kristiinan kommentti)

**Comment by mirmaid** [comment]
Muutetaan blogit, poistetaan alakäsitteet.

**Comment by mirmaid** [comment]
Lisätään määritelmä, jos sellainen saadaan. Tehdään siinä tapauksessa erillinen issue.
