### ISSUE TITLE
Topjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8830]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Topjoki](http://www.yso.fi/onto/ysa/Y118920) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös toinen Topjoki

**Comment by ilona-x** [comment]
toinen issue samasta: https://github.com/Finto-ehdotus/YSE/issues/8633
