### ISSUE TITLE
Armenian kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8831]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Armenian kirkko](http://www.yso.fi/onto/ysa/Y111883) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään asisanastosta Kantoon ja lisätään LCNAF/LCSH-siltaus 

#### Perustelut ehdotukselle   

Kyseessä on yhteisö, joten auktoriteettitietueen pitäisi olla Kannossa. LCNAF/LCSH-siltaus: http://id.loc.gov/authorities/names/n50002600 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
On varmaan nähty omana uskontonaan?

**Comment by mariaforsen** [comment]
Tämän sijaan voidaan hyväksyä esim. tämä https://github.com/Finto-ehdotus/YSE/issues/2199 :
 https://fi.wikipedia.org/wiki/Orientaaliortodoksiset_kirkot 
https://www.ortodoksi.net/index.php/Orientaaliortodoksit
https://peda.net/joensuu/yp/hein%C3%A4vaaran-koulu/luokat-7-9/oppiaineet/oul/8lk-uo/km/ortodoksinen-kirkko/o 

Sanastossa myös idän katoliset kirkot

**Comment by AuHo22** [comment]
Armenian apostolinen kirkko näyttäisi oleva melko vallitseva -> ehdotus yhteisöauktoriteetteihin

**Comment by YSO-kokous** [comment]
Kun ei ole oma uskontonsa, niin voidaan siirtää Kantoon toimijakuvailuksi.
Tilalle uusi käsite idän ortodoksisest kirkot. Tarkistetaan tarkempi sanamuoto.

**Comment by mariaforsen** [comment]
Sv. orientaliska kyrkor /ne orientaliskt ortodoxa kyrkor /wp ET österländskt ortodoxa kyrkor, icke-kalcedoniska kyrkor, förkalcedonska kyrkor
