### ISSUE TITLE
Parainen -- Jurmo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8833]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Parainen -- Jurmo](http://www.yso.fi/onto/ysa/Y109975) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan yläkäsite Brändö ja/tai jaetaan 

#### Perustelut ehdotukselle   

Yläkäsitteenä nyt sekä Parainen että Brändö, vaikka huomautuksen mukaan viittaa Paraisiin kuuluvaan saareen. Ehdotan sanastoon myös Brändön kuntaan kuuluva Jurmo-niminen saari (osa Ahvenanmaata). Aineistoa on Melindassa, esim. M/s Doppingen liikennöi Åvasta Jurmoon : rehellinen peli kannattaa. -Huom tässä nyt virhe, ei ole Paraisen Jurmosta kyse.

**Comment by mariaforsen** [comment]
Ks. https://kartta.paikkatietoikkuna.fi

**Comment by ilona-x** [comment]
Brändö:
Jurmo (kylä) http://paikkatiedot.fi/so/1000772/10296378
Jurmo (saari) http://paikkatiedot.fi/so/1000772/10296232
https://fi.wikipedia.org/wiki/Jurmo_(Br%C3%A4nd%C3%B6)

Parainen:
Jurmo (saari) http://paikkatiedot.fi/so/1000772/10310933
https://fi.wikipedia.org/wiki/Jurmo
huom. Paraisilla myös toinen Jurmo-niminen hyvin pieni saari: http://paikkatiedot.fi/so/1000772/10309498

**Comment by mirmaid** [comment]
Tämä toinen Paraisten Jurmo on n. 100 m pitkä saari, josta on aika vaikea kuvitella tulevan aineistoa. Jos halutaan kuitenkin erotella, tarkenne olisi kai Parainen, Jurmo fjärden? Muuten riittänee Parainen.

**Comment by mirmaid** [comment]
Auktorisoidaanko Brändön Jurmo niin, että linkataan saareen? Ei ole ainakaan kirjattu ylös linjausta voiko tehdä kaksi PNR-linkkiä samalle...

**Comment by mirmaid** [comment]
^ Molempiin, mutta vain isompi paikkatyyppi (?). Viikkopalaveriin. 

Jurmo (Parainen). Huomautus: Saari Paraisilla Jurmofjärdenillä (tai Jurmonselällä, jos käytetty).
