### ISSUE TITLE
koulupiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8835]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koulupiirit](http://www.yso.fi/onto/ysa/Y121990) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "oppilaaksiottoalueet" ja "oppilasalueet" 

#### Perustelut ehdotukselle   

Aiemmin koulupiireiksi nimityistä alueista puhutaan nyt uusilla nimityksillä, joista on syytä lisätä KT-muodot tai toisinpäin ja viitata vanhasta nimityksestä uuteen. Asia sinällään on pysynyt samana. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. elevområden, elevupptagningsområden

**Comment by YSO-kokous** [comment]
ei lisätä ohjaustermejä.
