### ISSUE TITLE
seurantalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8836]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seurantalot](http://www.yso.fi/onto/ysa/Y104308) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "haalit" 

#### Perustelut ehdotukselle   

"Haali on sali tai seurojentalo, joissa amerikansuomalaiset järjestävät yhteisiä tapaamisia, kokouksia ja juhlia." [https://fi.wikipedia.org/wiki/Haali] 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytty
