### ISSUE TITLE
poliisiasemat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8837]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

poliisiasemat 

#### Ehdotettu termi ruotsiksi   

polisstationer * 

#### Ehdotettu termi englanniksi   

police stations 

#### Assosiatiiviset (RT)   

[poliisilaitokset](http://www.yso.fi/onto/yso/p13271) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85104253> 
Wikidata : https://www.wikidata.org/wiki/Q861951 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Perustelut ehdotukselle   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/yso/p26524) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [poliisiasemat](http://finto.fi/yse/fi/page/Y508837)

**Comment by jtuohini** [comment]
https://finto.fi/allars/en/page/Y24396

**Comment by jtuohini** [comment]
Lisäksi KT-muodot _poliisin palvelupisteet_ ja _poliisitalot_.

**Comment by mirmaid** [comment]
JUPOssa ja MAOssa. JUPOssa ei ole _poliisilaitokset_-käsitettä, MAOssa on molemmat. Käytetty Melindassa vain Kaunokki-käsitteenä Sydämen asialla -sarjan kuvailussa, termiä ei kuitenkaan ole Kaunokissa/KAUNOssa.

**Comment by YSO-kokous** [comment]
Hyväksytty
