### ISSUE TITLE
kerrostalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8838]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kerrostalot](http://www.yso.fi/onto/ysa/Y96090) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "lamellitalot" ja "pistetalot" 

#### Perustelut ehdotukselle   

Lamellitalo ja pistetalo ovat kerrostalon kaksi päätyyppiä, joista olisi hyvä saada viittausmuoto (jollei kyseisiä tarvittaisi itsenäisinä asiasanoinaan – kenties ei tarvita). 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Sitten on toki myös lamellihirsitalo, joita joskus myös nimitetään lamellitaloiksi.

**Comment by ilona-x** [comment]
MAOssa omina termeinään: 
lamellitalot http://www.yso.fi/onto/mao/p7223
pistetalot http://www.yso.fi/onto/mao/p7425

**Comment by YSO-kokous** [comment]
Hyväksytty
