### ISSUE TITLE
miljoonakala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8843]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

miljoonakala 

#### Ehdotettu termi englanniksi   

Guppy 

#### Ehdotettu termi ruotsiksi   

guppy 

#### Vaihtoehtoiset termit ja ilmaisut   

Poecilia reticulata 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hammaskarpit](http://www.yso.fi/onto/yso/p23813) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Miljoonakala 
LCSH : <Guppies http://id.loc.gov/authorities/subjects/sh85057955> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Dispersal, habitat use, and the invasion dynamics of introduced populations :a case study on the guppy (Poecilia reticulata) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [miljoonakala](http://finto.fi/yse/fi/page/Y508843)

**Comment by mariaforsen** [comment]
Sv. guppy ET miljonfisk
