### ISSUE TITLE
koulutusteknologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8847]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koulutusteknologia](http://www.yso.fi/onto/ysa/Y112460) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

yhdistetään koulutusteknologia & opetusteknologia?
eli koulutusteknologia KÄ opetusteknologia 

#### Perustelut ehdotukselle   

onko näillä termeillä selkeää eroa?

--

Wikipedia: Educational technology = opetusteknologia https://en.wikipedia.org/wiki/Educational_technology
YSO: educational technology = koulutusteknologia http://www.yso.fi/onto/yso/p12937

--
fi        opetusteknologia
sv       undervisningsteknologi; utbildningsteknologi
Lähde  Finsk-svensk utbildningsordlista (Forskningscentralen för de inhemska språken, 2005)
	  
YSO: 
opetusteknologia = undervisningsteknologi
koulutusteknologia = utbildningsteknologi

--

Melinda:
opetusteknologia x 2607
koulutusteknologia x 216 
opetusteknologia & koulutusteknologia x 120

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Yhdistetään. Päätermiksi opetusteknologia
