### ISSUE TITLE
avaruusteleskoopit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8849]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[avaruusteleskoopit](http://www.yso.fi/onto/ysa/Y504861) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "avaruusobservatoriot" ja "avaruustutkimusasemat" 

#### Perustelut ehdotukselle   

Ks. https://fi.wikipedia.org/wiki/Avaruustutkimusasema 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Käytössä on jonkin verran vaihtelua (viittaako avaruusteleskooppi vain avaruudessa sijaitsevaan teleskooppiin, mihin kaikkeen avaruustutkimusasema voi viitata). Ohjaustermit kuitenkaan tuskin lisäävät sekavuutta.

**Comment by mariaforsen** [comment]
Sanastossa on myös avaruusasemat, mikä sen suhde on termeihin "avaruusobservatoriot" ja "avaruustutkimusasemat"?

**Comment by YSO-kokous** [comment]
EI hyväksytä, tutkitaan vielä lisää, palataan seuraavalla kerralla

**Comment by jarmosaarikko** [comment]
En kannata lisäämistä. Observatorio ja tutkimusasema viittaavat mielestäni "miehitettyyn" paikkaan, kun taas teleskooppi ei ole sitä.

**Comment by mirmaid** [comment]
Wikipediassa: _A space telescope or space observatory is a telescope located in outer space to observe distant planets, galaxies and other astronomical objects_. Jos käyttö halutaan suomeksi täysin rajata näin, tarvitaan tarkenne, mutta mitään kovin eleganttia ei taida löytyä. Avaruusteleskoopit (avaruudessa) tms. LCSH:ssa lisäksi Large astronomical telescopes, http://id.loc.gov/authorities/subjects/sh00005582 ja Very large array telescopes http://id.loc.gov/authorities/subjects/sh85142926.

**Comment by mirmaid** [comment]
Laitoin URSAan sähköpostia.

**Comment by mirmaid** [comment]
URSAn kommentit:

Tämä onkin monimutkainen kysymys, koska käytettävään sanaan vaikuttaa se, millä aallonpituuksilla havaintoja tehdään. "Teleskooppi" toimii aina, mutta "kaukoputki" ei aina. "Kaukoputki" on turvallinen vaihtoehto pelkälle "teleskoopille", kun puhutaan näkyvän valon aallonpituuksien havaitsemisesta. Tää on yksinkertaisin nyrkkisääntö, minkä voin sanoa.

1) avaruudessa sijaitseva teleskooppi, kuten Hubble
Tämä olisi nyt se avaruusteleskooppi.

2) maanpinnalla sijaitseva avaruustutkimusteleskooppi, esim. VLT
Tämä olisi ihan vain teleskooppi. Niillä kaikilla tutkitaan avaruuden kohteita, joten sanaa "avaruus" ei tarvitse käyttää. Jos puhutaan yleisemmin kaukoputkista, joilla voidaan katsoa myös asioita Maan pinnalla, voidaan tarkentaa että nyt puhutaan tähtitieteellisistä teleskoopeista, tai teleskoopeista, joilla tehdään tähtitieteellistä tutkimusta. Harrastuskäytössä olevista teleskoopeista voidaan puhua tähtikaukoputkina. En puhuisi tähtikaukoputkista, jos kyse on isoista ammattikäyttöön tarkoitetuista välineistä.
Tähtitieteilijät, siis tutkijat, puhuvat yleisesti teleskoopeista kaukoputkien sijaan. Tähän voi vaikuttaa sekin, että isoimmat optiset teleskoopit eivät ole perinteisiä putkia enää ollenkaan.

3) maanpinnalla sijaitseva "teleskooppisarja", esim. Very Large Array
Nämä ovat tyypillisesti radioteleskooppeja (kuten VLA). Niissä kaikki teleskoopit (tai osa niistä) toimivat oleellisesti yhtenä suurena teleskooppina, ja radiosignaalien yhdistämistä kutsutaan apertuurisynteesiksi. Tällaista radioteleskooppiryhmää voidaankin nimittää synteesiteleskoopiksi.
Teleskooppiryhmää, jonka jäsenten keräämä signaali yhdistetään, voidaan nimittää myös interferometriksi, jolla siis tehdään interferometriaa. Interferometriaa voidaan tehdä muillakin aallonpituusalueilla kuin radioaalloilla. Esim. VLT-teleskoopilla, johon kuuluu useita yksittäisiä optisen alueen teleskooppeja, voidaan tehdä näkyvän valon aallonpituuksien interferometriaa. Mutta jotta asia olisi mahdollisimman monimutkainen, interferometriaa voidaan tehdä myös teleskoopeilla, jotka eivät ole selvästi osa samaa fyysistä ryhmää, vaan ne voivat olla ripoteltuna ympäri maapalloa.
Eli hieman riippuen, miten muu konteksti on rakennettu, voidaan puhua ihan vain teleskoopista, synteesiteleskoopista, tai interferometrista.

Summa summarum, kaikkein yksinkertaisimmin:
1) avaruusteleskooppi, esim. Hubble-avaruusteleskooppi, tai Chandra-avaruusteleskooppi
2) teleskooppi, esim. VLT-teleskooppi
3) teleskooppi, esim. VLA-teleskooppi

**Comment by mirmaid** [comment]
Tiivistetysti, avaruusteleskooppi-termi rajautuisi ammattilais- (ja harrastaja-) käytössä avaruudessa sijaitseviin teleskooppeihin. Maan pinnalla sijaitseva olisi teleskooppi, ei kaukoputki. Asiaan vihkiytymätön kuvailija tarvitsisi käyttöä selkeyttävät tarkenteet.

**Comment by mariaforsen** [comment]
Kaukoputket + teleskoopit = teleskop ruotsiksi (riippumatta siitä ovatko avaruudessa vai maan päällä)
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/teleskop

**Comment by mirmaid** [comment]
Tyydytäänkö siihen, että otetaan avaruusteleskoopeilta pois ohjaustermit ja lisätään sille määritelmä? Jos halutaan myös tarkenne, en keksi muuta kuin (avaruudessa). 

Kaukoputket - jätetään sellaisekseen, tai muutetaan > kaukoputket ja teleskoopit

Entä ehdotetut ohjaustermit? Jos päätermi on muotoa "teleskoopit", ei liene sekaantumisen vaaraa avaruusasemiin, mutta kylläkin maanpäällisiin observatorioihin, joten ohjausmuodot saattavat lisätä tätä sekaantumisen riskiä.

**Comment by LeKorsu** [comment]
En haluaisi yhdistelmää "kaukoputket ja teleskoopit", jättäisin mielelläni entiselleen kaukoputkiksi.

**Comment by nikopartanen** [comment]
Jos tuota URSAn vastausta tulkitsee, niin radioteleskoopit esimerkiksi eivät ole varsinaisesti kaukoputkia. Toisaalta "teleskoopit" olisi hankala muutos, kun jonain päivänä eteemme tulevat varmasti vielä lintukaukoputket yms. "Kaukoputket ja teleskoopit" olisi siten ok-ratkaisu, niin meillä on kaikenlaiset tämän tyylin havainnointivälineet samassa paikassa.

Ehdotetuista ohjaustermeistä "avaruusobservatoriot" ja "avaruustutkimusasemat" olen samaa mieltä @jarmosaarikko:n kanssa, että ne viittaavat aika erilaisiin miehitettyihin asioihin kuin "avaruusteleskoopit". Toisaalta ne ovat keskenään samantapaisia siinä mielessä, että ne ovat Maasta raketilla lähetettyjä avaruudessa kiertäviä ihmisen rakentamia ja käyttämiä asioita. Tällainen on myös jo ohjausterminä oleva "avaruusasemat".

**Comment by mariaforsen** [comment]
Kun kyseessä on lintubongaukseen yms. käytetty kaukoputki termi on ruotsiksi **tubkikare**. Ks. esim. Birdlife Sverige https://www.naturbutiken.se/sv/articles/4/kikare-tillbehor https://svenska.se/tre/?sok=tubkikare&pz=1 
https://www.stjarnhusetonline.se/essentials/Nyb%C3%B6rjarteleskop/stj%C3%A4rnkikare/teleskop.html

**Comment by mirmaid** [comment]
^ Älä vaan sano, että se on tietynlainen kiikari :scream:

**Comment by YSO-kokous** [comment]
**Päätös**

Muutetaan muotoon _avaruusteleskoopit (avaruudessa)_. 

Muutetaan _kaukoputket_ muotoon _kaukoputket ja teleskoopit_.

**Comment by mariaforsen** [comment]
Sv. teleskop > tubkikare och teleskop? HT tuber och teleskop
https://svenska.se/tre/?sok=tub&pz=1
https://www.google.com/search?q=tubkikare&rlz=1C1GCEU_enFI883FI883&sxsrf=ALiCzsY_zcwSfVLY8_VwcZTzmVTbczg95g:1664372746955&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi-mezSz7f6AhWBCBAIHdavBqMQ_AUoAXoECAEQAw&biw=938&bih=477&dpr=1.88
https://www.google.com/search?q=kaukoputki&tbm=isch&ved=2ahUKEwjei7rVz7f6AhVjxosKHfC3B2cQ2-cCegQIABAA&oq=kaukoputki&gs_lcp=CgNpbWcQAzIECCMQJzIECCMQJzIFCAAQgAQyBAgAEB4yBAgAEB4yBAgAEB4yBAgAEB4yBAgAEB4yBAgAEB4yBAgAEB46BAgAEEM6CAgAELEDEIMBUK0bWMIlYIkoaAFwAHgAgAFciAGtBpIBAjExmAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=EFA0Y97DGeOMrwTw7564Bg&bih=477&biw=938&rlz=1C1GCEU_enFI883FI883

Rymdteleskop avser på svenska teleskop i rymden, så parentes behövs ej.

**Comment by mariaforsen** [comment]
AASI-ryhmän kommentti: Kaukoputkilla on kuitenkin merkittävä ero siinä ovatko tarkoitettu eläinten ja lintujen tarkkailuun vai tähtien ja muiden avaruudessa olevien kohteiden tarkkailuun. Joten olisiko kuitenkin parempi että olisi kaksi erillistä selkeää termiä? Esim. 

-teleskoopit (avaruudessa olevat kohteet) OT tähtikaukoputket = sv. teleskop HT stjärnkikare
-kaukoputket (maassa tai ilmassa olevat kohteet) OT maakaukoputket = sv. tubkikare

 "**Tähtikaukoputki ei sovellu lintujen tarkkailuun – lintukaukoputkia kutsutaankin maakaukoputkiksi.**" / https://www.birdlife.fi/lintuharrastus/lintuharrastuksen-perusteet/valineet/kiikarit-ja-kaukoputket/

**Comment by mirmaid** [comment]
Huh. En tiedä mikä voisi olla oikeasti suomeksi tätä jakoa vastaava
**tähtikaukoputket ja avaruusteleskoopit (maassa)** (joka kattaisi kaikki pienistä kädessä pidettävistä suurimpiin teleskooppeihin ja -sarjoihin)
**maakaukoputket (?) KT lintukaukoputket** (joka kattaisi ne pienet kaukoputket, joilla ei katsota suoraan ylöspäin yöllä)

**Comment by mirmaid** [comment]
Noinkohan AASi-ryhmäkään on sitä mieltä, että [tällä](https://www.verkkokauppa.com/fi/product/267037/Celestron-ASTROMASTER-130EQ-MD-tahtikaukoputki) ja [tällä](https://en.wikipedia.org/wiki/Very_Large_Telescope#/media/File:Paranal_and_the_Pacific_at_sunset_(dsc4088,_retouched,_cropped).jpg) on enemmän yhteistä kuin ensimmäisellä ja [tällä](https://www.gigantti.fi/product/urheilu-ja-vapaa-aika/kiikarit/focus-optics-hawk-15-45-x-60-kaukoputki/454488).

**Comment by mariaforsen** [comment]
Ensimmäinen on teleskop/stjärnkikare, viimeinen on tubkikare (maakaukoputki). Keskimmäinen näyttää joltakin laitokselta, jossa kai on teleskooppeja? 
https://fi.wikipedia.org/wiki/T%C3%A4htikaukoputki

**Comment by mirmaid** [comment]
Keskimmäinen on siis Very Large Telescope, _one of the world's most advanced optical telescopes, consisting of four Unit Telescopes with main mirrors of 8.2m diameter and four movable 1.8m diameter Auxiliary Telescopes_. Osateleskooppeja voidaan käyttää yhtenä laitteena tai erikseen.

**Comment by mariaforsen** [comment]
AASI-ryhmän näkmyksen mukaan on edelleen olennaisempaa mihin tarkoitukseen teleskooppi/kaukoputki on tehty, ei niinkään sen koko. Kuten ylläkin on todettu, niin tähtikaukoputket/teleskoopit eroavat maa/lintukaukoputkista niin paljon etteivät ne sovellu lintujen yms. maassa olevien kohteiden tarkkailuun.

**Comment by mirmaid** [comment]
No, jos tämä päätetään jakaa, niin korjaus on kerrankin suoraviivainen. Mutta mitkä olisivat termit? URSAn mukaan siis kyse ei aina ole kaukoputkista, mutta _tähtikaukoputket ja -teleskoopit_ vaihtoehdon kanssa saattaa lisääntyä se virhe, että kuitenkin käytettäisiin myös avaruudessa sijaitsevista laitteista. _Maassa_-tarkenne olisi kyllä kestämättömän kömpelö, joten ehkä pitää sitten vain luottaa ohjaustermin voimaan. 

Olisiko toinen lintukaukoputket KÄ _maakaukoputket_? Siltä varalta, että joskus tulee aineisto, jossa kaukoputki on vaikka purjehduskäyttöön tms.

**Comment by YSO-kokous** [comment]
**Päätös**

Uusi käsite _maakaukoputket_, ohjaustermiksi _lintukaukoputket_. Muutoksena _tähtikaukoputket ja teleskoopit_.
