### ISSUE TITLE
Valkoinen talo (Washington, D.C.)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8852]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Valkoinen talo (Washington, D.C.) 

#### Ehdotettu termi ruotsiksi   

Vita huset (Washington, D.C.) 

#### Ehdotettu termi englanniksi   

White House (Washigton, D.C.) 

#### Vaihtoehtoiset termit ja ilmaisut   

Valkoinen talo 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset](http://www.yso.fi/onto/yso/p1786) 
[virka-asunnot](http://www.yso.fi/onto/yso/p255) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85146483> 
Wikipedia : https://www.wikidata.org/wiki/Q35525 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

Yhdysvaltain presidentin virka-asunto 

#### Perustelut ehdotukselle   

YSO:ssa on vain Valkoinen talo (Värtsilä). Melindassa tämä presidentin virka-asunto on viitattuna yli 40 kertaa useilla erilaisilla asiasanoilla. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/001991110 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Valkoinen talo (Washington, D.C.)](http://finto.fi/yse/fi/page/Y508852)

**Comment by mirmaid** [comment]
Mahdollisia tarkenteita varmaan ehdotettu muoto, tai pelkkä (Washington) tai (Yhdysvallat).

**Comment by LeKorsu** [comment]
Pelkkä Washington ei riitä, koska se tarkoittaa virallisesti osavaltiota länsirannikolla.

**Comment by YSO-kokous** [comment]
Hyväksytty ehdotetussa muodossa
