### ISSUE TITLE
kansalaisjournalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8853]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansalaisjournalismi](http://www.yso.fi/onto/ysa/Y112733) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan käsitteen merkitystä. Ei ole valmista muutosesitystä, muuta kuin että se muutettaisiin tarkoittamaan todellakin kansalaisten, ei-ammattijournalismien harjoittamaa viestintää / (tutkivaa) journalismia jne. 

#### Perustelut ehdotukselle   

Olen tätä aikaisemminkin miettinyt - ja ehkäpä tätä on joskus käsiteltykin - en tiedä, mutta tuntuu että jo pidemmän aikaa kansalaisjournalismin selitehuomautus on kovin vanhentunut eikä tätä käsitettä voi käyttää siinä mielessä, mitä  sillä nykyään ajattelee. Nyt kun käsissä on Eliot Higginsin Me olemme Bellingcat, tuli taas mieleen, että olisipa kelpo asiasana, jos huomautuksena ei lukisi sitä, mitä siinä nyt lukee. 

#### Ehdottajan organisaatio   

Yle Arkisto

**Comment by mirmaid** [comment]
Wikipediassa erotettu suomeksi ja englanniksi, mutta termitasolla eron ilmentäminen on hankalaa:
https://fi.wikipedia.org/wiki/Kansalaisjournalismi
https://fi.wikipedia.org/wiki/Kansalaisjournalismi_(julkaiseminen)
https://en.wikipedia.org/wiki/Citizen_journalism
https://en.wikipedia.org/wiki/Civic_journalism

**Comment by mirmaid** [comment]
LCSH:ssa on [Citizen journalism](http://id.loc.gov/authorities/subjects/sh2009003468), mutta ei käsitettä Civic journalism.

**Comment by mirmaid** [comment]
Ks. myös http://kans.jyu.fi/sanasto/sanat-kansio/kansalaisjournalismi. YSOssa on _kansalaismedia_.

**Comment by AuHo22** [comment]
https://jyx.jyu.fi/bitstream/handle/123456789/43612/978-951-39-5723-0_vaitos14062014.pdf?sequence=1&isAllowed=y

Vuonna 2014 tehdyssä media-alan tutkimuksessa ei pidetä termin merkitystä vanhentuneena, mutta kiinnitetään huomio termin kaksinaiskäyttöön.

**Comment by mirmaid** [comment]
^ Yllä mainitusta: _Nykyisin ensimmäisen aallon kansalaisjournalismi-into on hiipunut, tai ainakin kansalaisjournalismin  painopiste  on  muuttunut:  nyt  puhutaan  perinteistä  kan-salaisjournalismia   enemmän   citizen   journalismista,   kansalaisreporttereista,   bloggaajista,  sattumaraportoijista,  sosiaalisesta  mediasta,  käyttäjien  tuottamista  mediasisällöistä, median ja kansalaisten vuorovaikutuksesta sekä joukkoistami-sesta.  Tai  kuten  Deuze  (2011)  on  todennut,  media-ammattilaisten  rinnalle  on  tullut  eräänlaiset  ”pro  ams”  tai  ”amafessionals”  ryhmät  eli  taitavat  amatööri-journalistit (Deuze 2011, 11)._

**Comment by AuHo22** [comment]
Vrt. kansalaistiede - sama kaksijakoisuus: Kansalaistiede (engl. citizen science) on tieteellistä tutkimusta, jonka tavalliset ihmiset osittain tai kokonaan toteuttavat, esim. 
https://vastuullinentiede.fi/fi/tutkimustyo/vastuullinen-kansalaistiede

**Comment by mirmaid** [comment]
Vaihtoehtoja:

1) ei muutosta
2) poistetaan määritelmä, saa käyttää molemmista
3) lisätään tarkemme, esim. kansalaisjournalismi (osallistava ammattijournalismi tms.)
4) lisätään ohjaus kansalaisjournalismi (amatöörijournalismi tms.) KÄ kansalaismedia - en tosin tiedä, onko kansalaismedia-termiä kovin usein käytetty tässä merkityksessä (tai missä merkityksessä ylipäätään...https://en.wikipedia.org/wiki/Community_media)

**Comment by mariaforsen** [comment]
Sv. medborgarjournalistik= samlingsbenämning på journalistik som väljs ut, bearbetas, produceras och sprids av personer ur allmänheten. /Nationalencyklopedin. Eli ruotsiksi nykyinen termi on rajattu "kansalaisten tekemään journalismiin". 

Kielitoimiston sanakirja: kansalaisjournalismi: vars. journalismista ja julkisesta keskustelusta, jota kansalaiset harjoittavat internetissä.

**Comment by mirmaid** [comment]
_Kansalaisjournalismi on sellaista ammattijournalismia, joka tietoisesti tähtää julkisen keskustelun synnyttämiseen ja kansalaisten osallistumisen kannustamiseen sekä vuorovaikutukseen. -- Nykyään kansalaisjournalismi-termiä käytetään usein kuvaamaan myös – useimmiten verkossa tapahtuvaa – kansalaisten oma-aloitteista julkaisemista, itsenäistä tiedonhankintaa, blogi-kirjoittelua ja itse otettujen valokuvien julkaisemista. -- Kuitenkin esimerkiksi bloggaamista tai Nopola Newsin (www.nopolanews.fi) kaltaista yhteisöllistä julkaisemista voisi pikemminkin kutsua kansalaisten vertaisviestinnäksi tai kansalaismediaksi kuin kansalaisjournalismiksi._ 

_Vaikka kansalaisjournalismi on uudistusliikkeenä jo hiipunut, on se edelleen voimissaan työkäytäntöinä. -- Viime aikoina onkin alettu puhua kansalaisjournalismin lisäksi myös osallistavasta journalismista (participatory journalism). -- Tieteellisessä keskustelussa ja journalismin tutkimuksessa käytetään edelleen käsitettä kansalaisjournalismi._
http://kans.jyu.fi/sanasto/sanat-kansio/kansalaisjournalismi

Ks. myös http://kans.jyu.fi/ajankohtaista/uutiset/keskustelua-suomalaisesta-kansalaismediasta

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Vertaismedia
_Suomenkielisessä tutkimuksessa puhutaan muun muassa vertaisviestinnästä, kansalaisjournalismista, kansanjournalismista ja kansalaismediasta. Termit eroavat toisistaan lähinnä sillä, mitä osallistumismuotoja ne sisältävät. Toiset tutkijat käsittävät termillä vain journalistisesti merkittävät tekstit, toisille vertaismedia tarkoittaa kaikkea sosiaalisessa mediassa tapahtuvaa sisällöntuotantoa._

**Comment by mirmaid** [comment]
kansalaisjournalismi (ammattijournalismi/ammattimedia) KT osallistava journalismi
kansalaisjournalismi (harrastajajournalismi/amatöörijournalismi) KÄ kansalaismedia (KT vertaismedia)

TAI (?)
kansalaisjournalismi (kansalaismedia?)
kansalaisjournalismi (ammattimedia) KÄ osallistava journalismi
Jos näin, pitäisi varmaan poistaa _kansalaismedia_ erillisenä. _Osallistava journalismi_ on kyllä hyvin vähän käytetty toistaiseksi.

**Comment by LeKorsu** [comment]
Alkuperäisen ehdotuksen tekijänä (pahoittelut etten pääse 3.11. kokoukseen) kommentti: En ole ollenkaan huomannut, että Ysossa on kansalaismedia. Tosin jos mietin käsitettä esim. mainitsemani Bellingat-kirjan osalta, siihen se osuu vain osittain, kun on kyse julkaisemisesta, mutta heillä on kyse myös (tutkivan journalismin) menetelmistä  
Olen taipuvaisempi kannattamaan Mirjan yllä olevasta postauksesta alempaa vaihtoehtoa, mutta miten tuo kansalaismedian poisto erillisenä, onko hankalaa. Näkyy tulevan 69 osumaa Melindasta.

**Comment by AuHo22** [comment]
Myös muotoa osallistuva journalismi näkee, mutta osallistava journalismi kuitenkin tuntuu selkeämmältä. Kansalaismedia on mielestäni selkeästi tarkoituksen ilmaiseva - kyse on toisaalta kuitenkin siitä, että kansalaisjournalismi-sanan käyttö on hyvinkin yleistä.

**Comment by YSO-kokous** [comment]
### Päätökset
Jaetaan kansalaisjournalismi:
kansalaisjournalismi (kansalaismedia)
osallistava journalismi KT kansalaisjournalismi (ammattimedia)  civic journalism

Tutkitaan onko Melinda kansalaismedia -kuvailituihin spiva termi kansalaisjournalismi. Jos sopii, niin voidaan poistaa kansalaismedia omana käsitteenää

**Comment by mirmaid** [comment]
Tutkitaan onko termi _kansalaismedia_ korvattavissa Melindassa termillä _kansalaisjournalismi (kansalaismedia)_. Jos on, voidaan poistaa kansalaismedia omana käsitteenään.

**Comment by mariaforsen** [comment]
Sv.
-medborgarjournalistik (fi. osallistava journalismi) >> deltagarjournalistik? (jos eng. participatory journalism)
-medborgarjournalistik? (fi. kansalaisjournalismi (kansalaismedia)) 

Lopulliset ruotsinnokset saadaan kun alla olevat asiat on käsitelty.

**Comment by mariaforsen** [comment]
Onko osallistavan journalismin eng. todella civic journalism? Monen ammattilaisen mielestä ei näköjään, vaan participatory journalism, ks. esim. http://kansalaisjournalismintutkimusta.blogspot.com/2011/04/mita-on-kansalaisjournalismi.html : "Termien sekaannusta lisäsi edelleen uusi osallistumisen muoto, osallistava journalismi (engl. participatory journalism), joka niin ikään sisällytettiin kansalaisjournalismiin. **Osallistavalla journalismilla tarkoitetaan lukijoille annettua mahdollisuutta tuottaa sisältöä verkko- tai paperijulkaisuihin.** Osallistava journalismi on kuitenkin oma-aloitteista julkaisua lähempänä kansalaisjournalismin alkuperäistä merkitystä, sillä siinä kansalaisen tuottama sisältö sisällytetään verkkojulkaisuun.

Myös Jyväskylän yliopisto: "Viime aikoina onkin alettu puhua kansalaisjournalismin lisäksi myös **osallistavasta journalismista (participatory journalism).** Tässäkin tapauksessa termein käyttö on melko sekalaista, mutta yleensä termillä participatory journalism viitataan siihen, että lukijoille annetaan mahdollisuus osallistua journalismin tekemiseen jossakin verkkojulkaisussa. Useimmiten ihmiset tällöin joko itse tuottavat aineistoja, kuten kuvia tai tekstejä, tai kommentoivat toimittajien artikkeleita." / http://kans.jyu.fi/sanasto/sanat-kansio/kansalaisjournalismi

Eli nyt ei näytä osallistavan journalismin (vanha ysa-)huomautus myöskään täsmäävän.

**Comment by mirmaid** [comment]
260/Melinda

**Comment by mirmaid** [comment]
https://id.loc.gov/authorities/subjects/sh2009003468.html

LCSH:ssa nimenomaan citizen journalism -käsitteen ohjaustermi on "participatory journalism". Eli palataanko siihen, että toinen käsite on _kansalaisjournalismi (ammattimedia)_? Tuohan varmaan liittyy siihen, että participatory voi tarkoittaa sekä osallistavaa, että "osallistuvaa".

**Comment by LeKorsu** [comment]
Minusta tuo 3.11. tehty päätös osallistava journalismi KT kansalaisjournalismi (ammattimedia) civic journalism on selkeämpi hahmottaa kuin että kansalaisjournalismi (ammattimedia) olisi päätermi, mutta huomautus tosiaan vanhentunut tässäkin yhteydessä, kun pitäisi ottaa huomioon myös tämä  "Osallistavalla journalismilla tarkoitetaan lukijoille annettua mahdollisuutta tuottaa sisältöä verkko- tai paperijulkaisuihin."
Tuohon englanninkielisen vastineen setvimiseen klo 16:n jälkeen, ei aivot valitettavasti enää kykene.

**Comment by YSO-kokous** [comment]
#### Päätös 
Äänestyksen jälkeen päätettiin pitää vain yksi käsite. Peruutetaan tehty jako.
Poistetaan osallistava journalismi sekä poistetaan tarkenne käsitteestä kansalaisjournalismi.
