### ISSUE TITLE
mobiilimaksaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8854]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mobiilimaksaminen 

#### Ehdotettu termi ruotsiksi   

mobilbetalning 

#### Ehdotettu termi englanniksi   

mobile payment 

#### Vaihtoehtoiset termit ja ilmaisut   

mobiilimaksut 

#### Assosiatiiviset (RT)   

[maksutavat](http://www.yso.fi/onto/yso/p21843) 

#### Vastaava käsite muussa sanastossa   

Liito : <http://www.yso.fi/onto/liito/p13402> 

#### Tarkoitusta täsmentävä selite   

https://termipankki.fi/tepa/fi/haku/mobiilimaksaminen

--

Huom. LCSH: Mobile commerce KT Mobile payments http://id.loc.gov/authorities/subjects/sh2002005081
Here are entered works on the exchange of goods and services and the transfer of funds through mobile communication devices. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda:
mobiilimaksaminen x 5
mobiilimaksut x 4 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

On the foundations of white-box cryptography 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mobiilimaksaminen](http://finto.fi/yse/fi/page/Y508854)

**Comment by YSO-kokous** [comment]
Hyväksytty

**Comment by mariaforsen** [comment]
Sv. mobilbetalning ET mobil betalning 
https://termipankki.fi/tepa/fi/haku/mobil%20betalning
