### ISSUE TITLE
teknostressi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8855]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

teknostressi 

#### Ehdotettu termi englanniksi   

techno stress 

#### Ehdotettu yläkäsite YSOssa (LT)   

[stressi](http://www.yso.fi/onto/yso/p133) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Tarkoitusta täsmentävä selite   

Lisääntyvän teknologian käytön aiheuttama stressi. 

#### Perustelut ehdotukselle   

Aiheesta tehdään paljon tutkimusta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Opinnäytteet 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [teknostressi](http://finto.fi/yse/fi/page/Y508855)

**Comment by mirmaid** [comment]
Sanastossa on ainakin jossain määrin tähän liittyvä _nettiriippuvuus_. Joitakin vuosia sitten puhuttiin tietotulvasta, mutta sitä ei löydy edes ehdotuksena.

**Comment by mariaforsen** [comment]
Sv. teknostress. 
https://svenska.se/tre/?sok=teknostress&pz=1 
https://www.ne.se/uppslagsverk/ordbok/svensk/teknostress 
Ei ole sama asia kuin nettiriippuvuus. Kannatan

**Comment by LeKorsu** [comment]
Nationalencyklopedin mukaan mainittu 1. kerran jo vuonna 1985. Intressant!

**Comment by YSO-kokous** [comment]
Hyväksytty
