### ISSUE TITLE
Vaikuttajamarkkinointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8856]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Vaikuttajamarkkinointi 

#### Ehdotettu termi englanniksi   

Influencer marketing 

#### Vastaava käsite muussa sanastossa   

https://en.wikipedia.org/wiki/Influencer_marketing :  

#### Tarkoitusta täsmentävä selite   

Vaikuttajamarkkinointi tarkoittaa sitä, että yritys hyödyntää esimerkiksi sosiaalisen median vaikuttajaa osana markkinointia. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 

#### Perustelut ehdotukselle   

Vaikuttajamarkkinointi lisääntyy koko ajan ja yritykset panostavat siihen yhä enemmän 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Opinnäytteet 

**Ehdottajan organisaatio:** Jyväskylän yliopisto **Termiehdotus Fintossa:** [Vaikuttajamarkkinointi](http://finto.fi/yse/fi/page/Y508856)

**Comment by mirmaid** [comment]
Hyväksyttiin viime kerralla: https://github.com/Finto-ehdotus/YSE/issues/8619.
