### ISSUE TITLE
Rapuoja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8859]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Rapuoja](http://www.yso.fi/onto/ysa/Y170636) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö tarkenne? 

#### Perustelut ehdotukselle   

Myös Orimattilassa.

**Comment by mirmaid** [comment]
Ilmeisesti aineistossa tarkoitetaan juuri tätä Orimattilan Rapuojaa. Erikoista kyllä, että Rapuoja näyttäisi kulkevan vain lyhyen matkan Orimattilan puolella, mutta Paikkatietoalustalla se on yläkäsite.

**Comment by mirmaid** [comment]
Rapuoja (Orimattila)
