### ISSUE TITLE
pegmatiitti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8864]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pegmatiitti 

#### Ehdotettu termi ruotsiksi   

pegmatit 

#### Ehdotettu termi englanniksi   

pegmatite 

#### Ehdotettu yläkäsite YSOssa (LT)   

[magmakivilajit](http://www.yso.fi/onto/yso/p12887) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Kivilaji. Tarvitaan Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pegmatites / by Davis London. 

**Termiehdotus Fintossa:** [pegmatiitti](http://finto.fi/yse/fi/page/Y508864)

**Comment by mirmaid** [comment]
Pitäisiköhän ottaa monikossa, vrt. esim. fulguriitit, vulkaniitit?

**Comment by mariaforsen** [comment]
https://id.loc.gov/authorities/subjects/sh85099236.html

**Comment by YSO-kokous** [comment]
Hyväksytty monikossa

**Comment by mariaforsen** [comment]
Sv. pegmatiter
