### ISSUE TITLE
asevarikot *

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8865]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

asevarikot * 

#### Ehdotettu termi englanniksi   

arsenals 

#### Vaihtoehtoiset termit ja ilmaisut   

arsenaalit 
asevarastot 

#### Ehdotettu yläkäsite YSOssa (LT)   

[varikot](http://www.yso.fi/onto/yso/p11239) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85007447> 
Wikidata : https://www.wikidata.org/wiki/Q81669 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Tarkoitusta täsmentävä selite   

Ks. myös https://www.kielitoimistonsanakirja.fi/#/arsenaali?searchMode=all ja https://www.kielitoimistonsanakirja.fi/#/asevarikko?searchMode=all 

#### Perustelut ehdotukselle   

Pelkkä "varikot" viittaa sekä liikenne- että asevarikoihin. Kyseessä kuitenkin kaksi eri asiaa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [asevarikot *](http://finto.fi/yse/fi/page/Y508865)

**Comment by mirmaid** [comment]
21 viitettä Melindassa. MAOssa omana käsitteenään, SOTOssa ohjausterminä _varikot_-käsitteelle.

**Comment by mariaforsen** [comment]
Sv. vapendepåer ET vapenarsenaler, arsenaler (vapen), tyghus (vapen)
https://svenska.se/tre/?sok=vapenarsenal&pz=1
NE: "tyghus, byggnad för vapen och materiel som tillhör artilleriet, se arsenal" 

YSO nyt varikot=depåer https://svenska.se/tre/?sok=dep%C3%A5&pz=1 -voi siis olla yhtä lailla aseista kuin liikenteesta tai muustakin kyse. Tarvitaan siis kyllä tarkempiakin termejä.

**Comment by YSO-kokous** [comment]
Hyväksytty  asevarikot KT  varikot (asevarikot), poistetaan varikot KT asevarikot
