### ISSUE TITLE
verenohennus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8866]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[verenohennus](http://www.yso.fi/onto/ysa/Y184960) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSO-termi "verenohennus" on mielestäni hämärryttävä, kyseessä on veren hyytymistä ehkäisevä (lääke)hoito eli antikoagulaatiohoito. Ohjaustermeissä näyttää nyt olevan parempia ehdokkaita ensisijaiseksi termiksi. 

#### Perustelut ehdotukselle   

päätermi on epäselvä 

#### Ehdottajan organisaatio   

Kansalliskirjasto / YSO-asiakaspalaute KK-02491006

**Comment by mirmaid** [comment]
Onko ehdotus päätermiksi siis _antikoagulaatiohoito_?

**Comment by mariaforsen** [comment]
Sv. antikoagulationsbehandling?

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

**antikoagulaatio**
anticoagulatio la, anticoagulation e, antikoagulation ‑en r (< anti kr vastaan + coagulare la juoksuttaa maito) 1. hyytymisenesto; 2. ks. hyytymisenestohoito

**hyytymisenestohoito**
anticoagulatio la, anticoagulation e, antikoagulation(sbehandling) ‑en, antikoagulansbehandling ‑en r antikoagulaatio | hoito jossa veren hyytymistaipumusta vähennetään antikoagulanttien avulla



Miten olisi "hyytymisenestohoito"?
