### ISSUE TITLE
käsikauppalääkkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8867]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[käsikauppalääkkeet](http://www.yso.fi/onto/ysa/Y182271) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotus päätermin vaihtamiseksi:
YSO-termille "käsikauppalääkkeet" olisi ymmärrettävämpi käytettävä termi "itsehoitolääkkeet" tai "itsehoitovalmisteet". 

#### Perustelut ehdotukselle   

Fimea käyttää termiä "itsehoitovalmisteet" https://www.fimea.fi/laakehaut_ja_luettelot/itsehoitovalmisteet ja 
Kelan sanastossa on "itsehoitolääke" https://www.kela.fi/documents/10180/17802081/Kelan_terminologinen_sanasto_5laitos.pdf/6accac09-bb77-4f5d-bf95-a0727bf15f32 

#### Ehdottajan organisaatio   

Kansalliskirjasto / YSO-asiakaspalaute KK-02491021

**Comment by mirmaid** [comment]
Eli muutosehdotus käsikauppalääkkeet KÄ itsehoitolääkkeet

**Comment by YSO-kokous** [comment]
Vaihdetaan päätermi:  käsikauppalääkkeet KÄ itsehoitolääkkeet

**Comment by mariaforsen** [comment]
Sv. receptfria läkemedel > egenvårdsläkemedel
https://termipankki.fi/tepa/fi/haku/itsehoitol%C3%A4%C3%A4ke
https://www.finlex.fi/sv/laki/ajantasa/2013/20130713
https://www.fimea.fi/web/sv/soktjanster_och_forteckningar/egenvardsmedel
