### ISSUE TITLE
Odottaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8868]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Odottaminen 

#### Ehdotettu termi englanniksi   

Waiting 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kohdistuva toiminta](http://www.yso.fi/onto/yso/p38217) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh90000108> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Teos: Timescapes of waiting : spaces of stasis, delay and deferral / ed. Christopher Singer, Robert Wirth and Olaf Berwald 

#### Perustelut ehdotukselle   

Odottaminen toimintana puuttuu sanastosta, mutta ilmiötä käsitellään kirjallisuudessa monipuolisesti. 

**Ehdottajan organisaatio:** Itä-Suomen yliopisto **Termiehdotus Fintossa:** [Odottaminen](http://finto.fi/yse/fi/page/Y508868)

**Comment by mariaforsen** [comment]
Sv. väntande

**Comment by LeKorsu** [comment]
Odottaminen vai odotus? Jos jälkimmäinen, sekoittuuko jo sanastossa olevaan monikkoon odotukset?

**Comment by ilona-x** [comment]
KAUNOssa: **odotus** sv, väntan http://www.yso.fi/onto/kauno/p1443

**Comment by YSO-kokous** [comment]
Hyväksytty odottaminen KT odotus

**Comment by mariaforsen** [comment]
Sv. väntande ET väntan
