### ISSUE TITLE
näyttelyrakennukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8871]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

näyttelyrakennukset 

#### Ehdotettu termi englanniksi   

exhibition buildings 

#### Vaihtoehtoiset termit ja ilmaisut   

näyttelypaviljongit 
paviljongit (näyttelyrakennukset) 
exhibition pavilions 

#### Ehdotettu yläkäsite YSOssa (LT)   

[näyttelytilat](http://www.yso.fi/onto/yso/p4240) 
[rakennukset käyttötarkoituksen mukaan](http://www.yso.fi/onto/yso/p493) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85046347> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Suomen paviljongit Pariisin maailmannäyttelyssä, Venetsian biennaalissa jne. aiheuttavat sekaannuksen YSO:n nykyiseen viittassuhteeseen huvimajoihin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [näyttelyrakennukset](http://finto.fi/yse/fi/page/Y508871)

**Comment by jtuohini** [comment]
"Näyttelyrakennus"-nimitystä käytetty Finnassa yli 70 kertaa.

**Comment by mirmaid** [comment]
13 kertaa Melindassa, mutta voisi olla myös ohjaustermi _näyttelytilat_-käsitteelle?

**Comment by jtuohini** [comment]
"Näyttelytilat" voi viitata mihin tahansa näyttelytilaan osana muuta rakennusta, mutta silloin kun kyse on varsinaisesta näyttelytoimintaa varten suunnitellusta rakennuksesta, niin osuvampi asiasana olisi ehkä paikallaan.

**Comment by mariaforsen** [comment]
Kannatan näyttelytilat KT näyttelyrakennukset. Ruotsin vastine "utställningslokaler" ei ota kantaa siihen onko se rakennuksen sisällä vai itse rakennus jne.

**Comment by LeKorsu** [comment]
Kannatan näyttelytilat KT näyttelyrakennukset. Ja näyttelypaviljongit varmaan ohjaustermiksi myös.

**Comment by YSO-kokous** [comment]
Hyväksytty ohjausterminä: näyttelyrakennukset KÄ näyttelytilat
