### ISSUE TITLE
Lapua -- Tiistenjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8872]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Lapua -- Tiistenjoki](http://www.yso.fi/onto/ysa/Y109774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Korjattava 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
YSO-paikoissa väärinpäin:  Lapua (Tiistenjoki) http://www.yso.fi/onto/yso/p109774
myös jaettava: On sekä kylä että joki Lapualla

**Comment by mirmaid** [comment]
Lisätty tarkenne Tiistenjoki (Lapua : kylä), aineistot käsittelevät kylää.
