### ISSUE TITLE
FEM

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8875]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[FEM](http://www.yso.fi/onto/ysa/Y112280) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

poistetaan tai tarkennetaan? Nyt käytetty Melindassa päällekäin elementtimenetelmän http://www.yso.fi/onto/yso/p24565 kanssa (elementtimenetelmästä käytetään paljon lyhennettä FEM (Finite element method))
https://en.wikipedia.org/wiki/Finite_element_method 

#### Perustelut ehdotukselle   

Alunperin käyttötarve ollut ilmeisesti jollekin ohjelmistolle:
Henkilökohtaisille tietokoneille soveltuvat FEM-ohjelmistot https://melinda.kansalliskirjasto.fi/byid/000640843
https://cris.vtt.fi/en/publications/henkil%C3%B6kohtaisille-tietokoneille-soveltuvat-fem-ohjelmistot
Eli tuo ohjelmistokin näyttäisi liittyvän samaan elementtimenetelmään, tarvitaanko sille erillinen termi? 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
ehdotuksia termin tarkentamiseksi:
FEM-ohjelmistot
FEM-laskentaohjelmat
FEM-laskentaohjelmistot

**Comment by mirmaid** [comment]
Käytetty 26 kertaa Melindassa. Tarvitaanko tämä siis erikseen, jos viitteet liittyvät mainittuun menetelmään?

**Comment by ilona-x** [comment]
siis ongelma oli, että tätä FEM-termiä on käytetty silloin kun olisi pitänyt käyttää elementtimenetelmä -termiä

--
IATE3
fi        FEM ★★☆☆; elementtimenetelmä ★★☆☆
en      FEM ★☆☆☆; finite element method ★★★☆
de      Methode fuer finiten Elemente ★★★☆
fr        méthode des éléments finis ★★★☆
da      finite element metode ★★★☆
	  
Lähde: 	
IATE 30.09.2020, Euroopan unioni (1074816)

**Comment by ilona-x** [comment]
mutta alunperin tämä FEM on siis otettu viittaaman FEM-ohjelmistoihin ilmeisesti tämän teoksen 
kuvailuuun 

Tekijä | Vähä-Pietilä, Kirsi.
Nimeke | Henkilökohtaisille tietokoneille soveltuvat FEM-ohjelmistot / Kirsi Vähä-Pietilä.

**Comment by ilona-x** [comment]
eli varmaan helpoin muutos olisi tarkentaa tämä FEM muotoon FEM-ohjelmistot, kun noista ohjelmistoista näyttää kuitenkin olevan joitain viitteitä

**Comment by ilona-x** [comment]
ja vielä lisähuomiona, että tuolla tietokoneohjelmat -termin alakäsitteinä on paljon tällaisia kirjainlyhenteitä, joissa saattaa olla vastaavia ongelmia http://www.yso.fi/onto/yso/p26592

**Comment by mariaforsen** [comment]
Lisätty ruotsiksi myös ohjaus "FEM (finita elementmetoden)" ANV elementmetoden. Pitäisikö vastaava ohjaus tehdä myös suomeksi, ks. esim. https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi748D216XvAhWj_CoKHQvNBFsQFjAAegQIAhAD&url=https%3A%2F%2Fhelda.helsinki.fi%2Fbitstream%2Fhandle%2F10138%2F273474%2FLOPULLINENGRADU.pdf%3Fsequence%3D2%26isAllowed%3Dy&usg=AOvVaw1JjGdpEpg_VqPnjJMGFhZS 
Eli "FEM (elementtimenetelmä)" KÄYTÄ elementtimenetelmä? 
Toisaalta, tarvitaanko todella "FEM-ohjelmat" tms. erikseen, eikö se ole sitten aika lähellä itse menetelmääkin?

**Comment by mirmaid** [comment]
^ Samaa ajattelin, että voisiko ne ohjelmatkin vain kuvailla menetelmän nimellä. Toki tuo on helppo muuttaa > FEM-ohjelmat, kun käsite jo sanastossa on.

**Comment by YSO-kokous** [comment]
FEM muutetaan muotoon FEM-ohjelmistot
