### ISSUE TITLE
spiritualiteetti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8876]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[spiritualiteetti](http://www.yso.fi/onto/ysa/Y107822) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

yhdistetään YSO-käsite  "spiritualiteetti"   käsitteeseen "hengellisyys" 

#### Perustelut ehdotukselle   

http://www.yso.fi/onto/yso/p176 : spiritualiteetti, spirituality (religion), spiritualitet / andligt liv
http://www.yso.fi/onto/yso/p17710 hengellisyys, religious spirituality, andlighet (religiositet), / andlighet

evl.fi sanasto: "Spiritualiteetti tarkoittaa hengellisyyttä ja hengellistä elämää. Termi tulee latinan kielen sanasta spiritualis (= hengellinen)."   
kts. myös https://svenska.se/tre/?sok=spiritualitet&pz=2
LCSH: http://id.loc.gov/authorities/subjects/sh85126779 Spirituality
Here are entered works about the personal search for sacredness or meaning that may be independent from organized religion.

HUOM: Eri käsite kuin 
http://www.yso.fi/onto/yso/p15308  henkisyys, spirituality (mental qualities), andlighet (mentalitet) / spirituaalisuus,, andlighet, andlighet (mentala egenskaper)

Wikipediassa nämä "spirituality" -käsitteet sekoittuvat eri kielisissä versioissa eri tavoilla. 

#### Ehdottajan organisaatio   

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Onkohan niin, että hengellisyys koetaan usein (kristillisen) uskonnollisuuden synonyyminä ja spiritualiteetti laajempana?

**Comment by mariaforsen** [comment]
Alkuperäinen ehdotus hyvä.
Hengellisyys käytetään myös esim. new age-piireissä, spiritualiteetti aika paljon kristinuskossa. Ja näiden termien kohdalla ei varmaan muutenkaan kannata rajata tiettyyn uskontoon.

**Comment by krinay** [comment]
Kannatan ehdotusta, mutta kummasta termistä tulisi varsinainen asiasana? Mikä on tämän ja toisaalta termin _henkisyys_ englanninkielinen vastine?

Onko merkitysero termien/käsitteiden _henkisyys_ ja _hengellisyys/spiritualiteetti_ välillä selvä? Vrt. ehdottajan maininta siitä, että Wikipediassa käsitteet sekoittuvat erikielisissä versioissa. 

Esimerkiksi Tieteen termipankissa (folkloristiikka) sanotaan mm. näin: "Nykykulttuurin ilmiöiden kuten New Age -pohjaisten käytäntöjen nimittäminen nykykansanuskoksi liittää ne tutkimustraditioon mutta luontevampia termejä olisivat henkisyys tai uushenkisyys." https://tieteentermipankki.fi/wiki/Folkloristiikka:kansanusko 

Kielitoimiston sanakirja: 
hengellisyys -- uskonnollisuus, hurskaus
henkisyys vrt. henkinen -> henkinen -- 1. älyllinen, sielullinen, psyykkinen; hengen-, sielunelämään kuuluva t. sitä koskeva 2. aineeton, abstrakti 3. yhdyssanojen jälkiosana [lämminhenkinen, kolmihenkinen]

YSOssa on myös uskonnollisuus (LCSH Religiousness).

**Comment by AuHo22** [comment]
Hengellisyys-termistä en halua luopua, mutta spiritualiteetista kyllä: https://evl.fi/sanasto/-/glossary/word/Spiritualiteetti

**Comment by mirmaid** [comment]
_Spiritualiteetti_ käytetty 1861 kertaa, sekä kristinuskoon, että muihin uskontoihin liittyvissä aineistoissa, lisäksi esim. elämäntaito-oppaissa. 

_Henkisyys_ käytetty 883 kertaa, "henkimaailmaan" liittyvissä kirjoissa, elämäntaito-oppaissa, myös uskontoon liittyen (ehkä enemmän muusta kuin kristillisestä).

_Hengellisyys_ käytetty 1654 kertaa, samoin edellä mainituista, mutta hieman enemmän painottuen (kristilliseen) uskonnollisuuteen, ei niinkään "henkimaailmasta" (keijut ym.).

_Uskonnollisuus_ käytetty 3999 kertaa, uskontoon liittyvä aineisto uskontokunnasta riippumatta. 

Huom. katsottu kustakin vain 50 uusinta viitettä.

**Comment by mirmaid** [comment]
Spiritualiteetti siis halutaan poistaa? Miten haluttaisiin rajautuvan suhteessa toisiinsa:
1) uskonnollisuus ja hengellisyys
2) hengellisyys ja henkisyys

**Comment by mariaforsen** [comment]
Hengellisyys vs. henkisyys-ongelma on ruotsiksi ratkaistu: andlighet (religiositet), andlighet (mentalitet), ei kovin hyvä ratkaisu, vaan kompromissi jotta saadaan molemmille suomenkielisille termeille vastine. En kannata liian tarkkoja/keinotekoisia rajauksia yllä olevien kohdalla, vaan että ne saa käyttää kuten yleensäkin todella käytetään. Uskonnollisuus viittaa enemmän "ulkoiseen uskonelämään", ja hengellisyys sisäiseen ja henkilökohtaiseen. Henkisyys taas enemmän sielulliseen, kuin tiettyyn/perinteiseen uskontoon.

**Comment by mirmaid** [comment]
^ Toivottavasti rajaukset eivät olisi keinotekoisia, mutta kuitenkin selkeyttäviä. 

Sanastossa tosiaan vielä lisäksi _kristillisyys_. Jako ulkoiseen uskonnollisuuteen ja sisäiseen hengellisyyteen ei kuulosta omaan korvaani tutulta, oikeastaan on vaikea sanoa, mitä hengellisyys varsinaisesti on. Sana assosioituu kristinuskoon (vrt. hengellinen musiikki), Kielitoimiston sanakirjan mukaan = uskonnollisuus, hurskaus. Jos halutaan, että merkitys on "ihmisen sisäinen, spirituaalinen elämä" (kuten vaikka noissa elämäntaito-oppaissa tai uushenkisyyttä käsittelevässä kirjallisuudessa), omaan korvaan melkein paras näistä kolmesta on _spiritualiteetti_, joka ei erityisesti assosioidu kristinuskoon, ja soveltuu mielestäni sekä uskonnolliseen, että ei-uskonnolliseen kontekstiin. Mutta tämä vain siis oma mielikuvani näistä.

**Comment by ilona-x** [comment]
Tätä samaa henkinen/hengellinen keskustelua taidettiin käydä aiemmin hengellinen kirjallisuus issuessa https://github.com/Finto-ehdotus/YSE/issues/7895

**Comment by AuHo22** [comment]
Kuinka termit uskonelämä ja spiritualiteetti oikeastaan eroavat toisistaan? Molempien ohjaustermi on hengellinen elämä?

https://evl.fi/kirkontutkimuskeskus/tutkimushankkeet/meneillaan-olevat-tutkimushankkeet/suomalainen-spiritualiteetti

spiritualiteetti KÄ uskonelämä (?)

**Comment by mariaforsen** [comment]
Jos jotain pitää poistaa/yhdistää kannatan spiritualiteetti > KÄ uskonelämä ja KÄ hengellisyys/henkisyys -näin olisi oikein ainakin ruotsin kannalta.

**Comment by mirmaid** [comment]
Tämän poiston jälkeen jäisi siis _uskonnollisuus, hengellisyys, kristillisyys_ (kaikki omassa kielenkäytössäni uskontoon liittyviä) ja _henkisyys_ (ei-uskonnollinen ominaisuus). Toivottavasti tästä poistosta ollaan aivan varmoja, koska näitä termejä yleensä halutaan enemmän lisätä kuin vähentää (vrt. eletty uskonto), ja Melindassa pari tuhatta korjattavaa, joissa katsottava onko uskonnollista vai ei.

Itselleni on aika selkeästi niin, että _hengellisyys_ liittyy kristinuskoon ja _henkisyys_ ei-uskonnolliseen, mutta Melindassa käyttö ei kyllä ole kovin selvärajaista, siksi laitoin tämän kommentin https://github.com/Finto-ehdotus/YSE/issues/8876#issuecomment-918899883. Herran haltuun?

**Comment by fantsby-m** [comment]
Jos poistetaan niin olisiko ohjaukset mahdollisesti näin:

spiritualiteetti (uskonelämä) KÄ uskonelämä
spiritualiteetti (hengellisyys) KÄ hengellisyys
spiritualiteetti (henkisyys) KÄ henkisyys

**Comment by YSO-kokous** [comment]
PÄÄTÖS
spiritualiteetti (uskonelämä) KÄ uskonelämä
spiritualiteetti (hengellisyys) KÄ hengellisyys
spiritualiteetti (henkisyys) KÄ henkisyys

Tarkistetaan vielä HULibista

**Comment by jtuohini** [comment]
Päätös ok! (Varmistettu HYK:n teologian kokoelmien hoitajalta.)
