### ISSUE TITLE
vaihtoehtolääkintä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8877]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vaihtoehtolääkintä](http://www.yso.fi/onto/ysa/Y104772) 

#### Tila   

Käsittelyssä 

#### Ehdottajan organisaatio   

Kansalliskirjasto / YSO-asiakaspalaute KK-02490992 Mon, 15 Feb 2021 16:57:41 +0200 

#### Perustelut ehdotukselle   

Feedback from vocab: YSO
YSO-termi "vaihtoehtolääkintä" pitäisi olla käytettävä termi "uskomushoidot", "uskomuslääkintä" tms. 

"Vaihtoehtolääkintä" on harhaanjohtava - oikeastihan kyseessä ei ole lääketieteellisessä mielessä mikään vaihtoehto esim. lääkkelle, jolle potilas on vaikkapa allerginen tms. syystä tarvii vaihtoehtoisen lääkkeen tai hoitotavan esim. leikkauksista puhuttaessa. Mm. oheisessa Suomen lääkäriliiton ohjeistuksessa käytetään termiä "uskomushoidot" https://www.laakariliitto.fi/laakarin-tietopankki/kuinka-toimin-laakarina/suositus-laakarin-suhtautumisesta-uskomushoitoihin/

Tallettajan huomautus. Termiä käsitelty 2020  issuessa https://github.com/Finto-ehdotus/YSE/issues/7519 "luontaishoito" 

#### Ehdotettu muutos   

päätermin muutos muotoon "uskomushoidot"

**Comment by mariaforsen** [comment]
https://mesh.kib.ki.se/term/D000529/complementary-therapies 

Uskomuslääkintä ongelmallinen termi ks. esim http://www.laakaripaivat.fi/2013/media/tiedotteet/ennakkoinfon-tiedotteet/onko-olemassa-nayttoon-perustuvia-vaihtoehtohoitoja/index.html 

Ruotsiksi vastaavaa termiä ei ole, eikä taida olla englanniksikaan? Näyttää olevan "suomalainen erikoisuus", ks. https://www.bioetiikka.fi/?p=1438 

"..Suomessa käytetään ainutlaatuisena maailmassa termiä ’uskomushoidot". Suomi onkin jäänyt jälkeen kansainvälisen tutkimuksen kehityksestä..." / https://www.tiedetoimittajat.fi/tiedetoimittaja/huuhaata-vai-vaikuttavaa-hoitoa/

**Comment by ilona-x** [comment]
FinMeSHissä uskomushoidot (en Complementary Therapies ; sv Alternativ- och komplementärmedicin) http://www.yso.fi/onto/mesh/D000529
