### ISSUE TITLE
harvesterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8880]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[harvesterit](http://www.yso.fi/onto/ysa/Y171401) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko sama kuin hakkuukoneet? 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Ainakin näiden mukaan ovat sama asia: 
https://www.kielitoimistonsanakirja.fi/#/harvesteri?searchMode=all 
https://fi.wikipedia.org/wiki/Hakkuukone
https://smy.fi/sanasto/harvesteri-harvester/
https://forest.fi/glossary/harvester-harvesteri-hakkuukone-monitoimikone-moto/
http://puuhuolto.fi/koneellinen-puunkorjuu/glossary/hakkuukone/

**Comment by jarmosaarikko** [comment]
Ilmeisesti sitten meillä katsotaan samaksi hakkuukoneet (felling machines) ja harvesterit  (harvesters)  KT monitoimikoneet  (moto)  - https://en.wikipedia.org/wiki/Harvester_(forestry)
Jos yhdistetään, niin olisiko:
KÄ harvesterit KT hakkuukoneet, monitoimikoneet, motot  YK metsäkoneet

Muistettava, ettei saa mennä sekaisin leikkuupuimurin (combine harvester) kanssa.
Samoin LCSH:n "[Harvesting machinery](http://id.loc.gov/authorities/subjects/sh85059216)" ovat viljankorjuun maatalouskoneita.

**Comment by YSO-kokous** [comment]
hakkuukoneet KÄ harvesterit
