### ISSUE TITLE
Seipäjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8883]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Seipäjärvi 

#### Tarkoitusta täsmentävä selite   

Järvi ja kylä Sodankylän kunnan lounaisosassa. 

#### Perustelut ehdotukselle   

Maantieteellinen paikannimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Maantieteelliset, paikallishistorialliset, ympäristövaikutusyhteenvedot. 

**Ehdottajan organisaatio:** Rovaniemen kaupunginkirjasto, maakuntakokoelma. **Termiehdotus Fintossa:** [Seipäjärvi](http://finto.fi/yse/fi/page/Y508883)

**Comment by mirmaid** [comment]
Jos ei ole muita samannimisiä järviä, onko tarkenne kuitenkin muotoa (Sodankylä : järvi) vai vain (järvi)?

**Comment by mirmaid** [comment]
Seipäjärvi (järvi)
