### ISSUE TITLE
psykoosit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8887]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[psykoosit](http://www.yso.fi/onto/ysa/Y98262) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään kaksisuuntainen mielialahäiriö ja skitsofrenia mielenterveyshäiriöiden alle, RT psykoosit. Vrt. MeSH yläkäsite skitsofreniakirjon ja muut psykoottispiirteiset häiriöt, jonka alla erikseen skitsofrenia, psykoottiset mielialahäiriöt ja psykoottiset häiriöt. 

#### Perustelut ehdotukselle   

https://www.terveyskirjasto.fi/terveyskirjasto/tk.koti?p_artikkeli=dlk00411
https://www.mielenterveystalo.fi/aikuiset/itsehoito-ja-oppaat/oppaat/mielenterveys_puheeksi/Pages/psykoosi.aspx 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
hyväksytään hierarkiamuutos ehdotuksen mukaan
