### ISSUE TITLE
Skutskär

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8888]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Skutskär 

#### Ehdotettu termi ruotsiksi   

Skutskär 

#### Perustelut ehdotukselle   

Teoksen Ei verta rakkaampaa / Milka Hakkarainen tapahtumat sijoittuvat tähän tehdaskaupunkiin. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä 

**Ehdottajan organisaatio:** Oulun kaupunginkirjasto **Termiehdotus Fintossa:** [Skutskär](http://finto.fi/yse/fi/page/Y508888)

**Comment by mirmaid** [comment]
Kahden kunnan alueella sijaitseva taajama Ruotsissa, paikkatarkenne (Älvkarleby)? https://fi.wikipedia.org/wiki/Skutsk%C3%A4r KT Skutskär (Gävle)?

**Comment by mirmaid** [comment]
Skutskär (Älvkarleby)
