### ISSUE TITLE
esittelijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8889]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[esittelijät](http://www.yso.fi/onto/ysa/Y95112) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne tms. tarkennus 

#### Perustelut ehdotukselle   

On ryhmässä 71  ja ruotsiksi "föredragande" (person som före­drar ett ärende). Ks. https://termipankki.fi/tepa/fi/haku/esittelij%C3%A4 Mutta Melindassa käytetty myös esim. tuote-esittelijästä. Vrt. esittely.

**Comment by ilona-x** [comment]
esittely: https://github.com/Finto-ehdotus/YSE/issues/7334

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Oikeustiede:esittely
https://toissa.fi/valmistuneiden-kertomukset/show/740

Kuuluvatko em. molemmat tähän? Mikä voisi olla mahdollinen tarkenne?

**Comment by mariaforsen** [comment]
Voisiko olla "päätöksenteko" tai "hallinto"?

**Comment by LeKorsu** [comment]
Peukku: "päätöksenteko" Pitääkö tuote-esittelijöistä tehdä ohjaustermi konsulentteihin?

**Comment by mirmaid** [comment]
Esittelijät (päätöksenteko/päätöksentekomenettely/hallinto)?

Tuote-esittelijät KÄ konsulentit

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa: esittelijät (päätöksentekomenettely)  sekä tuote-esittelijät KÄ konsulentit
