### ISSUE TITLE
Kirkniemi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8890]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kirkniemi](http://www.yso.fi/onto/ysa/Y110189) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Kirkniemen kartano 

#### Perustelut ehdotukselle   

Monimerkityksinen

**Comment by mirmaid** [comment]
Jo korjattu, https://github.com/Finto-ehdotus/YSE/issues/8930.
