### ISSUE TITLE
Sanginjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8893]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Sanginjoki](http://www.yso.fi/onto/ysa/Y136724) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaanko? 

#### Perustelut ehdotukselle   

Myös kylä, alue jne. Ks. Paikkatietoikkuna. Käytetty Melindassa myös muusta kuin joesta.

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Sanginjoki_(Muhos)
https://www.luontoon.fi/sanginjoki

Lisätty tarkenne (joki). Jos otetaan vielä YSOon Sanginjoen luonnonsuojelualue, ja kun viitteet on korjattu, katsotaan mitä jää. Käytetty nyt aika monenlaisesta, vaikea sanoa onko viitattu kylään.
