### ISSUE TITLE
ekotrillerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8896]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ekotrillerit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esim. Risto Isomäki: Sarasvatin hiekkaa 

**Ehdottajan organisaatio:** KAUNO-ryhmä **Termiehdotus Fintossa:** [ekotrillerit](http://finto.fi/yse/fi/page/Y508896)

**Comment by mirmaid** [comment]
Ryhmä toivoi lisää esimerkkiteoksia ja määritelmää.

**Comment by AuHo22** [comment]
https://joelburcat.com/2020/04/23/environmental-fiction-list-of-thrillers-eco-thrillers-legal-thrillers-and-cli-fi-april-22-2020/

**Comment by jtuohini** [comment]
Onko kyseessä todellakin oma kirjallisuudenlajinsa vai viittaako ehdotettu termi ennemmin sisältöön? Englanninkielisessä Wikipediassa on tähän ryhmään listattu mm.  Peter Benchleyn _Jaws_ ja Michael Crichtonin _Jurassic Park_, ks. https://en.wikipedia.org/wiki/Category:Eco-thriller_novels. Selventäviä esimerkkejä kaivattaisiin?

**Comment by mariaforsen** [comment]
Sv. ekothrillers HT ekothriller, ekothrillrar

**Comment by mirmaid** [comment]
Hyväksytty/SLM. Kauno-ryhmä laatii määritelmän.

**Comment by mirmaid** [comment]
KAUNO-ryhmä: Jännityksen alalaji, jossa luonto on uhattuna ihmisen toiminnan seurauksena.

**Comment by mirmaid** [comment]
Hyväksytään määritelmä. Pidetään hierarkia toistaiseksi entisellään.
