### ISSUE TITLE
työtoverit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8897]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[työtoverit](http://www.yso.fi/onto/ysa/Y184948) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon työkaverit. 

#### Perustelut ehdotukselle   

Työkaverit on nykyaikaisempi ja käytetympi termi. 

#### Ehdottajan organisaatio   

KAUNO-ryhmä

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjassa _työtoveri_ on edelleen ilmaisuna "ajankohtaisempi" kuin _työkaveri_, koska jälkimmäinen on erikseen määritelty työtoveriksi (https://www.kielitoimistonsanakirja.fi/työkaveri).

**Comment by mariaforsen** [comment]
Olisiko uusi KT myös "kollegat"? https://www.kielitoimistonsanakirja.fi/#/kollega?source=suggestion&searchMode=all Päätermi ruotsiksi on "kolleger".

**Comment by jtuohini** [comment]
Marian viittaamaan _Kielitoimiston sanakirjan_ mukaan "kollega" voi olla sekä työtoveri että virkaveli – ja virkavelihän voi toimia aivan toisessa organisaatiossa ja jopa eri maassa (kaikki lääkärit ovat toistensa virkeveljiä, vaikka eivät olisi työtevereita) eli kollega kyllä kelpaa rajatusti KT:ksi.

**Comment by YSO-kokous** [comment]
Ei muutosta. Selvitetään vielä kielivastinetta

**Comment by mariaforsen** [comment]
Ruotsinkielisen sanastoryhmän kommentti: Ei voida ruotsiksi poistaa "kolleger" kokonaan, mutta jos näiden merkityskenttä on eri, niin toivotaan että myös kollegat/virka-/ammattitoverit=kolleger lisätään erikseen sanastoon, ja siinä tapauksessa on ok muuttaa työtoverit=>arbetskamrater.

Mot Kielitoimiston sanakirja: kollega: virkaveli, virka-, ammattitoveri.

**Comment by jarmosaarikko** [comment]
kollega/ammattitoveri on siis eri käsite kuin työtoveri, joka on samassa organisaatiossa/työpaikassa mikä puoltaisi kyllä erillistä käsitettä? Tämä käsite on jo metatietosanastossa: http://urn.fi/URN:NBN:fi:au:mts:m1801, tarvitaanko YSO:ssa?

**Comment by mirmaid** [comment]
Ei suomeksi Melindassa.

**Comment by YSO-kokous** [comment]
lisätään uusi käsite kollegat KT ammattitoverit
