### ISSUE TITLE
sydänkeskiaika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8900]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sydänkeskiaika 

#### Ehdotettu termi ruotsiksi   

högmedeltiden 

#### Ehdotettu termi englanniksi   

High Middle Ages 

#### Ehdotettu yläkäsite YSOssa (LT)   

[keskiaika](http://www.yso.fi/onto/yso/p2559) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Perustelut ehdotukselle   

YSOsta löytyy ennestään jo varhaiskeskiaika ja myöhäiskeskiaika. Sydänkeskiaikaa on käytetty Melindassakin 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Otavan suuri maailmanhistoria. 8, Sydänkeskiaika [ja monta muuta teosta] 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [sydänkeskiaika](http://finto.fi/yse/fi/page/Y508900)

**Comment by mirmaid** [comment]
Kerran Melindassa.
https://fi.wikipedia.org/wiki/Syd%C3%A4nkeskiaika

**Comment by mariaforsen** [comment]
Myös SAOssa.

**Comment by YSO-kokous** [comment]
Hyväksytty
