### ISSUE TITLE
vanha musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8904]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vanha musiikki](http://www.yso.fi/onto/ysa/Y144396) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tarvitaan myös SLM-sanastossa 

#### Perustelut ehdotukselle   

Tarvitaan erityisesti kokoelmalevyissä/-nuoteissa, joiden tarkempi kuvailu on vaikeaa.

YSO:n määritelmä: Yleensä barokkimusiikista ja sitä vanhemmasta länsimaisesta taidemusiikista (keskiaika, renessanssi) käytetty nimitys.

Musassa ollut käyttöhuomautus:
Termiä käytetään, kun tarkempi ilmaus esimerkiksi julkaisun kokoelmaluonteen takia ei kuvaa sisältöä yksiselitteisesti. Jos julkaisu sisältää vain yhden vanhaan musiikkiin kuuluvan tyylikauden musiikkia, on ensisijaisesti käytettävä tätä tarkkaa ilmaisua, esimerkiksi vanha musiikki : soitinmusiikki : Eurooppa mutta messut : renessanssi : Espanja. 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by jtuohini** [comment]
Tämä on jätetty tarkoituksella pois SLM:stä, koska on tarkoituksenmukaisempaa kuvailla aikakausi omana fasettinaan. Ajan voi ilmaista 388-kentässä joko YSO:n aika- (esim. **keskiaika**) tai tyylikautta kuvaavalla asiasanalla (esim. **renessanssi**, **barokki**) tai vuosisatoina (esim. **1100-luku**, **1500-luku**), ja 655-kenttään on hyvä laittaa edes jokin karkea musiikinlajia kuvastava SLM-termi (esim. **taidemusiikki**, **kirkkomusiikki**, **tanssimusiikki**). Yhteensä nämä kuvastavat huomattavasti paremmin sisältöä kuin kovin epätarkka "vanha musiikki", joka käytännössä vastaisi samaa kuin 388-kentässä aikamääre "ennen 1760-lukua" yhdistettynä 655-kentän **musiikki**-termiin.

**Comment by asormune** [comment]
Marc21 ohjeissa ei ole esimerkkejä asiasanan käytöstä 388-kentissä.. (jos siis on sallittua)

**Comment by jtuohini** [comment]
Hei

Sisällönkuvailuoppaassa on: https://www.kiwi.fi/display/ohjaus/11.+Luomisaika, tapaus Broken Laughter.

Terveisin,


Jaakko

Jaakko Tuohiniemi
tietoasiantuntija (taiteiden tutkimus)
Helsingin yliopiston kirjasto
Saatavuuspalvelut
PL 53 (Fabianinkatu 30)
00014 HELSINGIN YLIOPISTO

puh. +358-29-412 4702

Tilaa kirjaston uutiskirje: https://www.helsinki.fi/fi/helsingin-yliopiston-kirjasto/seuraa-uutisia/tilaa-uutiskirje

**Comment by jtuohini** [comment]
Sisällönkuvailuoppaassa on ohje tästä: https://www.kiwi.fi/display/ohjaus/11.+Luomisaika, tapaus _Broken Laughter_.

**Comment by asormune** [comment]
Eli esimerkiksi: 388 1_  $a antiikki  $2 yso/fin

**Comment by jtuohini** [comment]
Nimenomaan. Eli jos on vaikkapa silppusisältöinen _Music of the Middle Ages_ -antologia, niin kuvailu epätarkimmillaan "388 1_ |a keskiaika |2 yso/fin |0 [URI]" + "655 _7 |a musiikki |2 slm/fin |0 [URI]". Mutta mieluummin vuosisadat + hieman tarkempia 655-kenttiä musiikista itsestään.

**Comment by MUUSA-kokous** [comment]
Ei kannateta ehdotusta.

**Comment by ilona-x** [comment]
Ei SLM-sanastoon.
