### ISSUE TITLE
suonikalvo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8907]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suonikalvo 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Small choroidal melanomas 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suonikalvo](http://finto.fi/yse/fi/page/Y508907)

**Comment by mirmaid** [comment]
Hmm, http://www.yso.fi/onto/mesh/D002823

**Comment by mirmaid** [comment]
Eli voisi olla _korioidea_ tai _silmän suonikalvo_? http://www.yso.fi/onto/mesh/D002829

**Comment by mirmaid** [comment]
https://helda.helsinki.fi/handle/10138/321396

**Comment by ilona-x** [comment]
voisiko harkita otettavaksi tämän sijaan laajemman termin **suonikalvosto**? "https://www.solunetti.fi/fi/histologia/suonikalvosto/  
FinMeSH: 
**suonikalvosto**
ST   korioidea
ST   sädekehä
ST   veri-vesieste
ST   värikalvo
http://www.yso.fi/onto/mesh/D014602 

Mirjan linkkaama toinen aineisto näyttää käsittelevän **suonikalvoston** melanoomaa.

**Comment by YSO-kokous** [comment]
Hyväksytty  muodossa suonikalvosto

**Comment by mariaforsen** [comment]
Sv. uvea /mesh
