### ISSUE TITLE
Valkila

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8908]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Valkila](http://www.yso.fi/onto/ysa/Y131998) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan 

#### Perustelut ehdotukselle   

Suomessa myös muita samannimisiä kartanoita, ks. https://kartta.paikkatietoikkuna.fi/?lang=fi

**Comment by ilona-x** [comment]
YSOssa huomautus: Kartano Pirkkalassa.
Käytetty Melindassa 3 kertaa, ja kaikki käsittelevät Pirkkalassa sijaitsevaa kartanoa

Paikkatietoikkunasta löytyy Valkila-nimisiä taloja, mutta ilmeisesti ei ole toista Valkilan kartanoa?
