### ISSUE TITLE
Suur-Merijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8911]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Suur-Merijoki](http://www.yso.fi/onto/ysa/Y111325) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Suur-Merijoen kartano (tai ohjausterminä) 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Suur-Merijoen_kartano 
Myös samanniminen lentokenttä (johon käytetty myös Melindassa)

**Comment by ilona-x** [comment]
kannatan päätermin vaihtoa muotoon Suur-Merijoen kartano
