### ISSUE TITLE
Virtaan Uusikartano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8913]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Virtaan Uusikartano](http://www.yso.fi/onto/ysa/Y110259) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT Virtaan kartano (Uusikartano) tms. 

#### Perustelut ehdotukselle   

Myös lisäyksiä/muutoksia Virtaan Vanhakartano:lle (esim. Vanhakartano)

**Comment by mirmaid** [comment]
https://www.sysma.fi/sysma-kartanopitajana
