### ISSUE TITLE
Etelä-Italia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8916]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Etelä-Italia 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Napolista etelään / Eero Hämeenniemi 

**Termiehdotus Fintossa:** [Etelä-Italia](http://finto.fi/yse/fi/page/Y508916)

**Comment by mirmaid** [comment]
Mezzogiorno KT Etelä-Italia

**Comment by ilona-x** [comment]
Wikipediasta löytyi myös tällainen:
https://en.wikipedia.org/wiki/South_Italy
"South Italy (Italian: Italia meridionale or just Sud Italia) is one of the five official statistical regions of Italy "

vrt. https://en.wikipedia.org/wiki/Southern_Italy

**Comment by ilona-x** [comment]
LCSH:
Italy, Southern
Variants
    Meridione (Italy)
    Mezzogiorno (Italy)
    Southern Italy
http://id.loc.gov/authorities/subjects/sh85069035
