### ISSUE TITLE
noppapelit (SLM)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8917]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

noppapelit (SLM) 

#### Perustelut ehdotukselle   

Voisiko termin "noppapelit" lisätä Suomalaiseen lajityyppi- ja muotosanastoon? Se olisi minusta yhtä oleellinen kuin "korttipelit" -termi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [noppapelit (SLM)](http://finto.fi/yse/fi/page/Y508917)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Noppapeli

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. tärningsspel
