### ISSUE TITLE
Playstation (pelikonsoli)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8918]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Playstation (pelikonsoli) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Playstation-kansa : kuinka Pleikkari valloitti Suomen (9789526952802) 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [Playstation (pelikonsoli)](http://finto.fi/yse/fi/page/Y508918)

**Comment by mariaforsen** [comment]
Sv. PlayStation (spelkonsoler)

**Comment by YSO-kokous** [comment]
Hyväksytty PlayStation (pelikonsolit) - huomaa kirjoitusmuoto
