### ISSUE TITLE
sikermät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8920]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sikermät](http://www.yso.fi/onto/ysa/Y214655) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSO-termin ohjaustermien lisääminen myös SLM-käsitteelle: https://finto.fi/slm/fi/page/s146

medleyt
potpourrit
potpurit
sikermäsävellykset 

#### Perustelut ehdotukselle   

Näistä ainakin potpurit-termi on yleiskielessä paljon käytetty ja tarvitaan ohjaustermiksi. 

#### Ehdottajan organisaatio   

Helsingin Konservatorio

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta. Lisätään vielä "kimarat".

**Comment by ilona-x** [comment]
Hyväksytty/SLM
