### ISSUE TITLE
logiikkaohjelmointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8921]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

logiikkaohjelmointi 

#### Ehdotettu termi englanniksi   

logic programming 

#### Ehdotettu termi ruotsiksi   

logikprogrammering 

#### Vaihtoehtoiset termit ja ilmaisut   

logiikkapohjainen ohjelmointi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[ohjelmointi](http://www.yso.fi/onto/yso/p4887) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh86003454> 
Wikipedia : https://en.wikipedia.org/wiki/Logic_programming 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 6 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Normalization and Rewriting for Answer Set Programming and Optimization 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [logiikkaohjelmointi](http://finto.fi/yse/fi/page/Y508921)

**Comment by mirmaid** [comment]
RT ohjelmoitavat logiikat?

**Comment by YSO-kokous** [comment]
Hyväksytty
