### ISSUE TITLE
keskusteluryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8922]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[keskusteluryhmät](http://www.yso.fi/onto/ysa/Y111986) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan "keskustelupalstat"-asiasanan KT-muodoksi 

#### Perustelut ehdotukselle   

Käytännössä sama asia. Ks. esim. https://www.hyvakysymys.fi/keskusteluryhmat/ ("Keskusteluryhmät ovat järjestöjen ylläpitämiä keskustelupalstoja eri aihealueista"), https://www.kielitoimistonsanakirja.fi/keskustelupalsta ja varsinkin https://www.kielitoimistonsanakirja.fi/keskusteluryhmä, kohta 2a. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8589

**Comment by YSO-kokous** [comment]
Jätetään erillisiksi käsitteiksi
