### ISSUE TITLE
dokumenttiohjelmat (SLM)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8923]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dokumenttiohjelmat (SLM) 

#### Perustelut ehdotukselle   

Tarvitaanko myös SLM-terminä? https://github.com/Finto-ehdotus/YSE/issues/5420 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [dokumenttiohjelmat (SLM)](http://finto.fi/yse/fi/page/Y508923)

**Comment by mirmaid** [comment]
luontodokumentit, urheiludokumentit, draamadokumentit: jos dokumenttiohjelmat hyväksytään, onko se näiden YK dokumenttielokuvien lisäksi? Entä dokumenttisarjat? https://github.com/Finto-ehdotus/YSE/issues/8652#issuecomment-817556668

**Comment by mirmaid** [comment]
Hyväksytty/SLM. ^ Hyväksytty monihierarkia.

**Comment by mirmaid** [comment]
Draamadokumentit onkin nyt fiktioelokuvien alla, tuleeko sille toiseksi yläkäsitteeksi dokumenttiohjelmat? Luontodokumentit oli dokumenttielokuvien alla, urheiludokumenteilla RT-suhde...kumpi malli valitaan? Entä tuleeko dokumenttiohjelmien yläkäsitteeksi televisio-ohjelmat ja radio-ohjelmat? Dokumenttisarjoilla pitäisi kai olla toisena yläkäsitteenä sarjaohjelmat (vai televisiosarjat)?

**Comment by mirmaid** [comment]
Draamadokumentit RT elokuvat, dokumenttiohjelmat. Luontodokumentit ja urheiludokumentit myös RT-suhteet. Palataan hierarkiakysymykseen seuraavassa kokouksessa. 

Ilkka pohjustaa LCGFT:n ratkaisua.

**Comment by ilona-x** [comment]
SLM-kokous: toistaiseksi monihierarkia
