### ISSUE TITLE
radio-ohjelmat (SLM)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8924]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

radio-ohjelmat (SLM) 

#### Perustelut ehdotukselle   

Tarvitaanko myös SLM-terminä? https://github.com/Finto-ehdotus/YSE/issues/5420 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [radio-ohjelmat (SLM)](http://finto.fi/yse/fi/page/Y508924)

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
Alakäsitteiksi: lastenohjelmat, luonto-ohjelmat, musiikkiohjelmat, radiosarjat ja kuunnelmat. - Ok

**Comment by mirmaid** [comment]
Radiofonia LT kuunnelmat ja elektroakustinen musiikki
