### ISSUE TITLE
Kuorasjärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8926]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kuorasjärvi](http://www.yso.fi/onto/ysa/Y138252) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Kuorasjärvi (Alavus)

**Comment by mirmaid** [comment]
Kyläkunta, järvi Alavudella.
