### ISSUE TITLE
Hagalund

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8931]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hagalund](http://www.yso.fi/onto/ysa/Y152619) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Hagalundin kartano, tarkennus 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Hagalundin_kartano

**Comment by jarmosaarikko** [comment]
Ruotsiksi tämä on jo Hagalund gård ja pelkkä Hagalund on Tapiolan ensisijainen termi ruotsiksi yso-paikoissa. 
Tarkennemuoto lienee "Hagalundin kartano (Espoo)"

**Comment by mirmaid** [comment]
Tarvitseeko tarkennetta? En löydä tietoa samannimisistä.
