### ISSUE TITLE
Itätalo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8932]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Itätalo](http://www.yso.fi/onto/ysa/Y208941) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Monimerkityksinen. https://kartta.paikkatietoikkuna.fi

**Comment by mirmaid** [comment]
Ohjausterminä nyt Itätalo (Kaurissalo).

**Comment by mariaforsen** [comment]
Itätalon-nimisiä rakennuksia näyttää olevan monessa paikassa Suomessa.

**Comment by jarmosaarikko** [comment]
Ehdotus:  Itätalon kartano (Kustavi)

**Comment by mirmaid** [comment]
Kaurissalo valittiin kai ohjaustermin tarkenteeksi, koska Kustavissakin on toinenkin Itätalo 🙂

**Comment by jarmosaarikko** [comment]
https://kotiseutuliitto.fi/toiminta/kirjamakasiini/esittelyt-ja-arvostelut-2015/kustavin-kaunissalossa-itatalo/
