### ISSUE TITLE
Jutikkala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8933]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Jutikkala](http://www.yso.fi/onto/ysa/Y124121) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jutikkalan kartano 

#### Perustelut ehdotukselle   

Monimerkityksinen

**Comment by mirmaid** [comment]
Eli halutaan erottaa paikannimestä?

**Comment by jarmosaarikko** [comment]
wikidata: https://www.wikidata.org/wiki/Q18659578
