### ISSUE TITLE
Juthbacka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8934]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Juthbacka](http://www.yso.fi/onto/ysa/Y155153) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Juthbackan kartano 

#### Perustelut ehdotukselle   

Monimerkityksinen. https://fi.wikipedia.org/wiki/Juthbackan_kartano

**Comment by mirmaid** [comment]
Tässäkin ilmeisesti erotukseksi paikannimestä?
