### ISSUE TITLE
Halola

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8935]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Halola](http://www.yso.fi/onto/ysa/Y110878) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Halolan kartano 

#### Perustelut ehdotukselle   

Monimerkityksinen. https://kartta.paikkatietoikkuna.fi/?lang=fi

**Comment by jarmosaarikko** [comment]
Haulla "Halolan kartano" ei löydy mitään Finnasta eikä Melindasta, mutta kyseessä lienee Maaningalla sijaitseva Halola. Paikkatietoikkunassa on Halola nimisiä taloja kymmenittäin, joten  lienee parempi vaihtaa.  TIetueeseen olisi hyvä lisätä ainakin RT-viittaus yso-paikat sanastossa olevaan sijaintipaikkakuntaan.

**Comment by ilona-x** [comment]
Melindasta löytyy kyllä viitteitä tuolla nykyisellä asiasanalla "Halola". Näyttäisivät käsittelevän Maaningan Halolaa.

**Comment by jarmosaarikko** [comment]
Esitän muodoksi "**Halolan tila (Kuopio)**".  MTT:n ja sittemmin Luken toimipaikka on Halolan tilalla Maaningalla, joka on nykyisin osa Kuopiota.  Oheisessa Senaatin julkaisussa on kattavat taustatiedot ja historiaa 1500-luvulta.  https://www.senaatti.fi/app/uploads/2020/08/978-952-368-027-2_2020_Arkkitehtitoimisto-Arto-Mattila-Oy_Maaninka_LUKE_Rakennushistoriaselvitys-1.pdf, 
Melindassa: https://melinda.kansalliskirjasto.fi/byid/016801362
sekä https://portal.mtt.fi/portal/page/portal/mtt/mtt/esittely/toimipaikat/maaninka/historiaa

**Comment by mirmaid** [comment]
^ Halolan tila olisi varmaankin yhteisö tai paikka? Kartano voidaan käsitellä rakennuksena, kuten tähänkin asti.

Suomessa ei ole muita samannimisiä kartanoita.
