### ISSUE TITLE
kvanttilaskenta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8937]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

quantum computing 

#### Ehdotettu termi suomeksi   

kvanttilaskenta 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tietojenkäsittely](http://www.yso.fi/onto/yso/p2407) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2014002839> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 4 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Enhanced elementary operations for quantum computing http://urn.fi/URN:ISBN:978-952-64-0124-9 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kvanttilaskenta](http://finto.fi/yse/fi/page/Y508937)

**Comment by mariaforsen** [comment]
Sv. kvantberäkning

**Comment by YSO-kokous** [comment]
Hyväksytty
