### ISSUE TITLE
vapaapalokunnat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8939]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vapaapalokunnat](http://www.yso.fi/onto/ysa/Y220496) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

sopimuspalokunnat 

#### Perustelut ehdotukselle   

Pelastusalalla oikea termi on sopimuspalokunta tai vapaaehtoinen palokunta.
https://pelastustoimi.fi/pelastustoimi/sopimuspalokunnat
Vapaapalokunta on vanhentunut termi.

**Comment by mirmaid** [comment]
Otettiin sanastoon vasta 2018 omana käsitteenään. _Vapaaehtoiset palokunnat_ on nyt ohjausterminä. Varmaan tätä wikipedia-sivua silloin käytettiin lähteenä: https://fi.wikipedia.org/wiki/Vapaaehtoinen_palokunta.

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/vapaapalokunta

fi        vapaaehtoinen palokunta; VPK
ei: vapaapalokunta
sv       frivillig brandkår; FBK

määritelmä
palokuntatoimintaa varten perustettu yhdistys

Lähde:Varautumisen ja väestönsuojelun sanasto (TSK 39, 2009)

**Comment by mariaforsen** [comment]
Ks. myös Palo- ja pelastussanasto (TSK 33, 2006) (sopimuspalokunta TEPAssa). 
Nämä pitäisi siis varmaan molemmat olla erillisinä päätermeinä. Ks. https://finlex.fi/fi/laki/ajantasa/2011/20110379

**Comment by YSO-kokous** [comment]
otetaan sanastoon sopimuspalokunnat RT vapaapalokunnat
Lisätään ohjaustermi  vapaapalokunnat KT vapaaehtoispalokunnat

**Comment by mariaforsen** [comment]
Sv. avtalsbrandkårer
https://termipankki.fi/tepa/fi/haku/avtalsbrandk%C3%A5r
