### ISSUE TITLE
mittapiirustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8940]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mittapiirustukset](http://www.yso.fi/onto/ysa/Y504774) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaustermiksi: mittauspiirustukset 

#### Perustelut ehdotukselle   

Ks. esim.
https://www.aalto.fi/fi/arkisto/arkkitehtuurin-mittauspiirustukset 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
hyväksytty
