### ISSUE TITLE
katsekontakti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8941]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

katsekontakti 

#### Ehdotettu termi englanniksi   

eye contact 

#### Ehdotettu termi ruotsiksi   

ögonkontakt 

#### Assosiatiiviset (RT)   

[sosiaalinen vuorovaikutus](http://www.yso.fi/onto/yso/p10590) 
[ruumiinkieli](http://www.yso.fi/onto/yso/p6836) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh86001125> 
Wikipedia : https://fi.wikipedia.org/wiki/Katsekontakti 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 
[60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 6 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

All eyes on eye contact : studies on cognitive, affective and behavioral effects of eye contact / 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [katsekontakti](http://finto.fi/yse/fi/page/Y508941)

**Comment by mirmaid** [comment]
Sanastossa on _katse_, myös osa sillä kuvailluista viitteistä käsittelee katsekontaktia.

**Comment by YSO-kokous** [comment]
Hyväksytty
