### ISSUE TITLE
biennaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8942]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[biennaalit](http://www.yso.fi/onto/ysa/Y164053) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "biennaalit (näyttelyt)" 

#### Perustelut ehdotukselle   

On myös musiikkitapahtumia, joiden nimessä esiintyy biennaali, esim. "Helsinki Biennale" (nykyiseltä nimeltään "Musica nova Helsinki") ja "Tampere Biennale". YSO:n hierarkia viittaa siihen, että biennaalit ovat vain näyttelyitä, joten sulkutarkenne on tarpeen, ettei asiasanalla kuvailtaisi mainittuja ja kaltaisiansa biennaaleja, jotka eivät ole näyttelyitä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _joka toinen vuosi järjestettävä kansainvälinen näyttely_.
Wikipediassa määritelty laajemmin: https://fi.wikipedia.org/wiki/Biennaali

**Comment by satuniininen** [comment]
Melindassa käytetty myös musiikki- ja teatteribiennaaleista ja varmasti muistakin. Pitäisikö mieluummiin muuttaa hierarkia (esim. LT yhteiskunnalliset tapahtumat)?

**Comment by YSO-kokous** [comment]
Kannatetaan laajempaa merkitystä 2-vuosittaiset tapahtumat. Korjataan hierarkiaa, ei muita muutoksia
