### ISSUE TITLE
blues rock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8943]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

blues rock 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rock](http://www.yso.fi/onto/yso/p1882) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

Sekä YSO että SLM-sanastoihin olisi hyvä lisätä rockin alalaji blues rock, onhan niissä ennestään vastaavina tapauksina mm. folk rock ja country rock. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://en.wikipedia.org/wiki/Blues_rock 

**Termiehdotus Fintossa:** [blues rock](http://finto.fi/yse/fi/page/Y508943)

**Comment by mariaforsen** [comment]
Sv. bluesrock
https://svenska.se/tre/?sok=bluesrock&pz=1

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LCSH: https://id.loc.gov/authorities/subjects/sh2003002221.html
LCGFT: https://id.loc.gov/authorities/genreForms/gf2014026666.html

**Comment by ilona-x** [comment]
Hyväksytty/SLM

**Comment by mirmaid** [comment]
Suomenkielisessä wikipediassa yhteenkirjoitettuna. Halutaanko tälle määritelmää tai muita suhteita kuin RT blues?

**Comment by YSO-kokous** [comment]
YSOssa [rock](http://www.yso.fi/onto/yso/p1882) alakäsitteissä esiintyy sekä erikseen- että yhteenkirjoitettuna ja myös yhdysmerkillä.  Ruotsin kielessä kirjoitetaan yleensä yhteen, ellei ole erityistä syytä kirjoittaa erikseen.  Ryhmä puoltaa hieman yhteenkirjoitettua muotoa, jota myös YLE käyttää. 
Päätös: Muusalle edelleen pohdittavaksi.

**Comment by MUUSA-kokous** [comment]
Kannatetaan yhteenkirjoitettua muotoa.
Ei tarvita määritelmää eikä muita suhteita.
