### ISSUE TITLE
Tuntsajoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8944]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Tuntsajoki 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Venäjälle laskeva joki Sallan kunnan pohjoisosassa. 

#### Perustelut ehdotukselle   

Maantieteellinen paikannimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallishistoriallinen, luonnontieteellinen, maantieteellinen. 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Tuntsajoki](http://finto.fi/yse/fi/page/Y508944)

**Comment by mirmaid** [comment]
Linjaus puuttuu: joki, joka on Suomen ja toisen maan alueella.

**Comment by ilona-x** [comment]
Vilajoella YK Lappeenranta & Venäjä
käsitelty tässä issuessa: https://github.com/Finto-ehdotus/YSE/issues/8214

**Comment by mirmaid** [comment]
Kirjataan alakohdaksi linjaussivulle.
