### ISSUE TITLE
Baadus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8945]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Baadus 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Paikannimi Utsjoella Tenojoen varrella. 

#### Perustelut ehdotukselle   

Maantieteellinen paikannimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

paikallishistoriallinen aineisto 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Baadus](http://finto.fi/yse/fi/page/Y508945)

**Comment by mirmaid** [comment]
Paikkatietoalustalla talo.

**Comment by ilona-x** [comment]
Asutusnimihakemistosta löytyi tällainen:
Paatus : Paatuksessa
pohjoissaameksi Báđoš
Kyläkunta
Sijaintikunta: 	Utsjoki
Maakunta: 	Lappi
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=paatus

**Comment by mirmaid** [comment]
Myös Alastarolla Ylistarossa samoin ^.

**Comment by mirmaid** [comment]
Paatus KT Baadus, ei linkkiä taloon.
