### ISSUE TITLE
Sonkajärvi (Rovaniemi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8948]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Sonkajärvi (Rovaniemi) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Tarkoitusta täsmentävä selite   

Rovaniemen kaupungissa sijaitseva järvi, kaupungin länsiosassa. Sen ympärillä on myös Sonka-niminen kylä. 

#### Perustelut ehdotukselle   

Maantieteellinen paikannimi. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Paikallishistoriallinen, luonnontieteellinen, maantieteellinen. 

**Ehdottajan organisaatio:** Rovaniemen kaupunki, maakuntakokoelma. **Termiehdotus Fintossa:** [Sonkajärvi (Rovaniemi)](http://finto.fi/yse/fi/page/Y508948)

**Comment by mirmaid** [comment]
Sanastossa on ennestään Sonkajärvi (järvi), joka sijaitsee Sonkajärven kunnassa. Mitenkäs tarkenteet? Sonkajärvi (Rovaniemi) ja Sonkajärvi (Sonkajärvi : järvi)?

**Comment by mirmaid** [comment]
Sonkajärvi (Sonkajärvi : järvi)
Sonkajärvi (Rovaniemi)
