### ISSUE TITLE
suomenruotsalaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8950]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[suomenruotsalaisuus](http://www.yso.fi/onto/ysa/Y108697) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

eng. myös "Finland-Swedishness" (ohjausterminä?) 

#### Perustelut ehdotukselle   

Käytetty esim. väitöskirjoissa.

**Comment by jarmosaarikko** [comment]
lisätty YSOon 1.6.2021
