### ISSUE TITLE
moniammatillinen yhteistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8952]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

moniammatillinen yhteistyö 

#### Perustelut ehdotukselle   

Moniammatillinen yhteistyö -käsite on tärkeässä roolissa esimerkiksi kasvatukseen, opetukseen ja terapeuttiseen asiayhteyteen liittyvissä asioissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

tehtävä 

**Ehdottajan organisaatio:** UEF **Termiehdotus Fintossa:** [moniammatillinen yhteistyö](http://finto.fi/yse/fi/page/Y508952)

**Comment by mirmaid** [comment]
57 kertaa Melindassa, on TSR-ontologiassa. Sanastossa on kuitenkin _moniammatillisuus_, ja luultavasti se yleensä viittaa nimenomaan moniammatilliseen yhteistyöhön / toimintaan.

**Comment by mariaforsen** [comment]
Sv. multiprofessionellt samarbete

**Comment by AuHo22** [comment]
Mielestäni voitaisiin korvata, on selkeämpi -> moniammatillinen yhteistyö KT moniammatillisuus

**Comment by jarmosaarikko** [comment]
**multiprofessional cooperation**
https://termipankki.fi/tepa/fi/haku/moniammatillinen%20yhteisty%C3%B6
Löytyy esim. JAMK opetusohjelmasta: https://opetussuunnitelmat.peppi.jamk.fi/en/SKO2019SMM/course_unit/SWKO1506
MOT: moniammatillinen on muodossa multi-professional

**Comment by YSO-kokous** [comment]
moniammatillinen yhteistyö KÄ moniammatillisuus
