### ISSUE TITLE
Hamnskär

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8953]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hamnskär](http://www.yso.fi/onto/ysa/Y130671) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Monimerkityksinen. Ks. esim. Paikkatietoikkuna

**Comment by mirmaid** [comment]
Lisätty.
