### ISSUE TITLE
Hepojoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8955]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hepojoki](http://www.yso.fi/onto/ysa/Y118925) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Hepojärvi (Kaarina)

**Comment by mirmaid** [comment]
Hepojoki (Kaarina : joki) & Hepojoki (Kaarina : kylä)
