### ISSUE TITLE
Sorsajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8959]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Sorsajärvi](http://www.yso.fi/onto/ysa/Y110395) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Monessa paikassa samannimisiä, ks. Paikkatietoikkuna

**Comment by mirmaid** [comment]
Lisätty.
