### ISSUE TITLE
karsinoidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8960]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

karsinoidit 

#### Vaihtoehtoiset termit ja ilmaisut   

karsinoidi, karsinoidikasvaimet, karsinoidikasvain 

#### Vastaava käsite muussa sanastossa   

MeSH : <http://www.yso.fi/onto/mesh/D002276> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85020159> 
Wikipedia : https://en.wikipedia.org/wiki/Carcinoid 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://urn.fi/URN:ISBN:978-951-51-5788-1 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [karsinoidit](http://finto.fi/yse/fi/page/Y508960)

**Comment by mariaforsen** [comment]
Sv. karcinoidtumörer /mesh ET karcinoider /ne https://sv.wikipedia.org/wiki/Karcinoid karcinoida tumörer, carcinoider, carcinoidtumörer
