### ISSUE TITLE
nostoväki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8961]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[nostoväki](http://www.yso.fi/onto/ysa/Y103690) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "varareservi" ja tehdään nykyisestä viittausmuoto. 

#### Perustelut ehdotukselle   

"Nostoväki"-nimitys on vanhentunut. Ks. esim. https://www.kielitoimistonsanakirja.fi/nostoväki ja https://fi.wikipedia.org/wiki/Varareservi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Vähän mietin kuulostaako anakronistiselta historiallisissa yhteyksissä. Käytetty vain 23 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. ersättande reserv https://finlex.fi/sv/laki/ajantasa/2007/20071438
