### ISSUE TITLE
Gammelbyviken

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8962]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Gammelbyviken](http://www.yso.fi/onto/ysa/Y156088) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Monimerkityksinen, ks. esim. Paikkatietoikkuna

**Comment by mirmaid** [comment]
Lisätty tarkenne.
