### ISSUE TITLE
somevaikuttajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8965]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

somevaikuttajat 

#### Ehdotettu termi ruotsiksi   

influerare 

#### Ehdotettu yläkäsite YSOssa (LT)   

[julkisuuden henkilöt](http://www.yso.fi/onto/yso/p9596) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. Termi löytyy jo KAUNO-ontologiasta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Itse tehty : opas omannäköiseen työelämään / Sara Parikka (9789510462966) 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [somevaikuttajat](http://finto.fi/yse/fi/page/Y508965)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by ilona-x** [comment]
juuri eilen huomasin uutisia selatessa, että YLE:llä on käytössä aihe **sosiaalisen median julkkikset** https://yle.fi/aihe/t/18-108770

**Comment by mariaforsen** [comment]
Sv. influerare (sociala medier) /ne ET influencers (sociala medier)
https://svenska.yle.fi/artikel/2018/11/13/sprakkolumnen-en-influencer-ger-ocksa-sprakliga-influenser
https://svenska.se/tre/?sok=influerare&pz=1

ne: "influerare, person som aktivt försöker påverka sin omgivning, främst via sociala medier och huvudsakligen i syfte att styra konsumtionsattityder och köpbeteenden."

isof.se: "influerare, person vars inflytande används i marknadsföringssammanhang
”En influerare är någon som människor litar på, lyssnar på och bryr sig om. Vi som
finns i den digitala sfären, vilket i dag är i stort sett alla, påverkar vår omgivning på
olika nivåer. Våra röster kan i dag vara lika starka i vissa nätverk som en ’kändis’”
(Resumé 8 augusti 2016). "

**Comment by satuniininen** [comment]
Näytti olevan Ylellä myös käytössä myös **vaikuttaja**: https://yle.fi/uutiset/18-217645

**Comment by YSO-kokous** [comment]
somevaikuttajat KT influensserit
