### ISSUE TITLE
oikeustila

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8966]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oikeustila 

#### Ehdotettu termi ruotsiksi   

rättsläg 

#### Ehdotettu termi englanniksi   

legal state/position? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oikeudelliset ominaisuudet](http://www.yso.fi/onto/yso/p28823) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://sv.wikipedia.org/wiki/R%C3%A4ttsl%C3%A4ge 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Nyt oikeusasema=rättsläge. Olisiko tämä suomeksikin oma käsitteensä? Pitää varmaan miten vain muuttaa oikeusasema > rättslig/rättsställning tms. Melindassa esim. "Tavaramerkkioikeuksien vaikutus kauttakuljetuksessa : Euroopan unionissa vallitseva oikeustila / Anu Monto." 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Taseyhtiökauppojen verokohtelu : vallitseva oikeustila ja sen kehittyminen / Terhi Holmström. 

**Termiehdotus Fintossa:** [oikeustila](http://finto.fi/yse/fi/page/Y508966)

**Comment by mirmaid** [comment]
En löydä _oikeustilalle_ suomenkielistä määritelmää, työpaikalla EIF:ssa voisi olla. Kuulostaa ainakin eri asialta kuin _oikeusasema_, toisaalta Melindassa ei kertaakaan aiheena.

**Comment by jarmosaarikko** [comment]
MOT antaa käännökseksi termille **oikeustila** 
sv: rättsläge, rättstillstånd  en: legal state (legal condition, legal position, legal situation, legal status)
ja  termille **oikeusasema** 
sv: rättslig ställning  en: 1) legal position (asia) 2) legal status (henkilö)
YSOssa **oikeusasema**  sv: rättsläge  en: legal status

[Nykysuomen sanakirjan ](https://kaino.kotus.fi/ns/Nykysuomen_sanakirja_4_O-R.pdf) määritelmät:
- **oikeusasema** s. objektiivisen oikeuden määräyksistä sekä subjektiivisista oikeuksista aiheutuvien henkilön kaikkien oikeuksien, velvollisuuksien ja oikeussuhteiden määräämä asema jonakin ajankohtana; suppeammassa merkityksessä henkilöoikeudellinen asema; oikeudellinen asema; vrt. oikeustila.
- **oikeustila** s. vrt seur. 
    1.) tila, jossa vallitsee laillisuus ja oikeudellisuus. |  Sodan häiritsemä oikeustila. Valtion tehtävänä on oikeustilan ylläpitäminen. Ihanteelliset pyrkimykset kansainvälisen oikeustilan luomiseksi. 
    2.) oikeudenhoidon, oikeusolojen tila. | Maamme oikeustila ennen Turun hovioikeuden perustamista. 
    3.) (pysyvästä) oikeussuhteiden, oikeutusten tilasta; vrt. oikeusasema. | Oikeustilan tai edun menetys. Odotusoikeus
on pelkkää odotustilaa jonkin verran voimakkaampi oikeustila. 
- **oikeustilanne** s. vrt. ed. | Konkurssin johdosta syntyy sellainen oikeustila, että velallinen menettää oikeutensa määrätä omaisuudestaan ja tämä oikeus siirtyy hänen velkojilleen.

**Comment by mirmaid** [comment]
EIFin hakemistosta ei löydy mitään tällä sanalla. ^ Merkitys 2 tuntuu melko selkeältä, mutta merkitys 3 epäselvempi suhteessa oikeusasemaan, ks. myös esim. https://www.invalidiliitto.fi/sites/default/files/2021-03/Invalidiliiton_lausunto_eduskunnan_tarkastusvaliokunnalle_lakiesitysten_vaikutusarvioinneistaFINAL.pdf.

**Comment by fantsby-m** [comment]
Ei ole EKS:ssa, eikä EU-sanastoissa.

**Comment by YSO-kokous** [comment]
Hyväksytään oikeustila   2-kohdan määritelmän mukaisena, jossa viitataan yhteiskunnan tilaan. "oikeudenhoidon, oikeusolojen tila".
