### ISSUE TITLE
klamydiat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8967]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[klamydiat](http://www.yso.fi/onto/ysa/Y105625) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

vaihdetaan käytettäväksi termiksi klamydiainfektiot niin olisi sama termi kuin FinMeSHissä https://finto.fi/mesh/fi/page/D002690 (YSOssa en. Chlamydia infection ; sv. klamydiainfektioner) 

#### Perustelut ehdotukselle   

ja lisäksi voisi selventää, mihin klamydia -termillä olisi tarkoitus viitata? http://www.yso.fi/onto/yso/p26079
Nyt molempien yläkäsite on sukupuolitaudit. Olisiko tämän tarkoitus viitata klamydiabakteeriin, joka löytyy myös FinMeSHistä https://finto.fi/mesh/fi/page/D002689 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
YSAssa klamydiat-termin yläkäsite on ollut bakteerit ja klamydian sukupuolitaudit. Siltä pohjalta toinen voisi siis olla myös _klamydiabakteerit_. https://en.wikipedia.org/wiki/Chlamydia_(genus)

**Comment by YSO-kokous** [comment]
vaihdetaan monikkomuodon päätermiksi klamydiabakteerit
yksikkömuoto jää sukupuolitauteihin
