### ISSUE TITLE
kulkueet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8968]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kulkueet](http://www.yso.fi/onto/ysa/Y110777) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kavalkadit" 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/kavalkadi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään
