### ISSUE TITLE
Annalan huvila (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8969]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Annalan huvila (Helsinki) 

#### Ehdotettu termi ruotsiksi   

Villa Anneber 

#### Ehdotettu termi englanniksi   

Villa Anneberg 

#### Vaihtoehtoiset termit ja ilmaisut   

Villa Anneberg 
Annalan kartano (Helsinki) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kartanot](http://www.yso.fi/onto/yso/p832) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Käytetty Melindassa (termillä Annala). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Villa Anneberg : porvarisidyllistä kaupunkilaisten keitaaksi = Annalan huvila / [kirjoittajat: Julia Donner ... ja muita] ; [käännös englanniksi: Nicholas Mayon i.e. Mayow] ; Annalan huvilan historia / Julia Donner. 

**Termiehdotus Fintossa:** [Annalan huvila (Helsinki)](http://finto.fi/yse/fi/page/Y508969)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8411 - tätä korjattiin juuri vähän aikaa sitten, ja ajatus oli, että paikkakäsite riittää kuvailussa. Tarvitaanko rakennus välttämättä erikseen?
