### ISSUE TITLE
tornipöllöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8973]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tornipöllöt](http://www.yso.fi/onto/ysa/Y109017) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

tornipöllöt (heimo) (alakäsite: tornipöllö (laji)) 

#### Perustelut ehdotukselle   

YSOssa on myös "tornipöllö". Tornipöllön pitäisi olla tornipöllöjen alakäsite.

**Comment by mirmaid** [comment]
Kerran Melindassa monikossa ja silloinkin kyse on lajista. Mutta ok tarkenteilla (olisi vielä tornipöllöjen sukukin).
