### ISSUE TITLE
mhallamit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8974]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mhallamit 

#### Vastaava käsite muussa sanastossa   

https://en.wikipedia.org/wiki/Mhallami :  

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9786059082297 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [mhallamit](http://finto.fi/yse/fi/page/Y508974)

**Comment by mirmaid** [comment]
http://id.loc.gov/authorities/subjects/sh2018003034

Suomenkieliselle nimelle ei löydy oikein lähdettä.

**Comment by mariaforsen** [comment]
Sv. mhallami https://sv.wikipedia.org/wiki/Mhallami
