### ISSUE TITLE
hautausmaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8975]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[hautausmaat](http://www.yso.fi/onto/ysa/Y95306) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "nekropolit" 

#### Perustelut ehdotukselle   

"Nekropoli (kreikan sanasta nekropolis ’kuolleiden kaupunki’) tarkoittaa isoa hautausmaata tai hautapaikkaa, missä haudoille on rakennettu omat rakennelmat." (https://fi.wikipedia.org/wiki/Nekropoli)

Itsenäisenä asiasanana ei välttämättä tarvetta, mutta viittausmuoto ei olisi haitaksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Voisi ehkä olla erikseenkin, mutta vain 2 kertaa Melindassa. LCSH:ssa myös vain ohjausterminä.

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2763

**Comment by mariaforsen** [comment]
Sv. nekropoler
