### ISSUE TITLE
oppivelvollisuuslaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8977]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

oppivelvollisuuslaki 

#### Perustelut ehdotukselle   

Lisäksi: Laki opetus- ja kulttuuritoimen rahoituksesta  
Laki tutkintokoulutukseen valmentavasta koulutuksesta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-5735-67-3 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [oppivelvollisuuslaki](http://finto.fi/yse/fi/page/Y508977)

**Comment by jtuohini** [comment]
Kyseessä jälleen juridinen teos, joten auktorisoitu hakutieto pitäisi muodostaa RDA:n luvun 6.29.1.2 perusteella tekijä-nimekeauktoriteettina "**110 1_ |a Suomi. |t Oppivelvollisuuslaki**".

**Comment by mariaforsen** [comment]
Sv. läropliktslag https://finlex.fi/sv/laki/alkup/2020/20201214
