### ISSUE TITLE
gurungit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8978]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gurungit 

#### Ehdotettu termi englanniksi   

Gurungs 

#### Vaihtoehtoiset termit ja ilmaisut   

Gurung people [eng] 
Tamu [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[nepalilaiset](http://www.yso.fi/onto/yso/p23080) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85057978> 
Wikidata : https://www.wikidata.org/wiki/Q1341218 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000061816 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [gurungit](http://finto.fi/yse/fi/page/Y508978)

**Comment by mirmaid** [comment]
_Nykyisin gurungit haluavat käyttää itsestään omakielistä nimitystä tamu_. https://synkooppilehti.wordpress.com/2017/01/02/haastattelussa-professori-pirkko-moisala/

**Comment by YSO-kokous** [comment]
gurungit KT tamut

**Comment by mariaforsen** [comment]
Sv. gurunger ET gurung (folk)
