### ISSUE TITLE
neuropalaute

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8979]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

neuropalaute 

#### Ehdotettu termi englanniksi   

neurofeedback 

#### Ehdotettu termi ruotsiksi   

neurobeedback 

#### Vaihtoehtoiset termit ja ilmaisut   

neuroterapia 
EEG-biopalautehoito 
neurofeedback 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hoitomenetelmät](http://www.yso.fi/onto/yso/p392) 

#### Assosiatiiviset (RT)   

[biopalaute](http://www.yso.fi/onto/yso/p25269) 

#### Vastaava käsite muussa sanastossa   

neurofeedback : https://id.loc.gov/authorities/subjects/sh2017003467.html 
neuropalaute : https://finto.fi/mesh/fi/page/D058765 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://nemoy.fi/wp-content/uploads/2019/01/Helsingin-Diakonissalaitos-julkaisu-neurofeedback.pdf 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Tarkoitusta täsmentävä selite   

Neurofeedback (NFB), also called neurotherapy or neurobiofeedback, is a type of biofeedback that uses real-time displays of brain activity—most commonly electroencephalography (EEG)—in an attempt to teach self-regulation of brain function. 
https://en.wikipedia.org/wiki/Neurofeedback

Melindassa 5 kertaa aiheena. 

**Ehdottajan organisaatio:** KK/SN **Termiehdotus Fintossa:** [neuropalaute](http://finto.fi/yse/fi/page/Y508979)

**Comment by mirmaid** [comment]
http://www.yso.fi/onto/mesh/D058765

Kerran Melindassa / neurofeedback 5 kertaa.

**Comment by mariaforsen** [comment]
Sv. neurofeedback /mesh
