### ISSUE TITLE
pistekirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8982]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pistekirjat](http://www.yso.fi/onto/ysa/Y203926) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan, että siirrettäisiin SLM-sanastoon, vrt. 'äänikirjat', 'selkokirjat'. 

#### Perustelut ehdotukselle   

Ilmentäisi teoksen muodon, ks. ylläoleva. 

#### Ehdottajan organisaatio   

Oulun kaupungin kirjasto

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
