### ISSUE TITLE
annoonakasvit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8983]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

annoonakasvit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/311761 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [annoonakasvit](http://finto.fi/yse/fi/page/Y508983)

**Comment by mariaforsen** [comment]
Sv. kirimojaväxter /dyntaxa
