### ISSUE TITLE
kuntouttava työote

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8984]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuntouttava työote 

#### Perustelut ehdotukselle   

käsitettä käytetään paljon sosiaali- ja terveydenhuollossa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

opinnnäytetyö 

**Termiehdotus Fintossa:** [kuntouttava työote](http://finto.fi/yse/fi/page/Y508984)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

https://fysiogeriatria.fi/organisaatioille/kuntouttava-tyoote-koulutus/
https://www.kaksineuvoinen.fi/wp-content/uploads/2017/09/Eth%C3%A4n-tee-karhunpalvelusta_luettava-versio-nettiin.pdf

Tarkoittaa suunnilleen potilaan toimintakyvyn tukemista hoivatyössä.

**Comment by mariaforsen** [comment]
Sv. rehabiliterande arbetssätt ET rehabiliterande förhållningssätt, rehabiliterande grepp
