### ISSUE TITLE
Välivesi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8986]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Välivesi](http://www.yso.fi/onto/ysa/Y112258) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Monimerkityksinen, ks. Paikkatietoikkuna

**Comment by mirmaid** [comment]
Todella :droplet:
