### ISSUE TITLE
typen kierto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8991]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

typen kierto 

#### Ehdotettu termi englanniksi   

nitrogen cycle 

#### Ehdotettu termi ruotsiksi   

kvävets kretslopp 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aineiden kierto](http://www.yso.fi/onto/yso/p12488) 

#### Alakäsitteet (RT)   

[nitrifikaatio](http://www.yso.fi/onto/yso/p12486) 
[denitrifikaatio](http://www.yso.fi/onto/yso/p12487) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85092071> 
Wikipedia : https://fi.wikipedia.org/wiki/Typen_kierto_luonnossa 
AFO : <http://www.yso.fi/onto/afo/p1374> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 
[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Nitrogen cycling from the perspective of boreal Scots pine trees 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [typen kierto](http://finto.fi/yse/fi/page/Y508991)

**Comment by mirmaid** [comment]
FinMeSH: typpikierto. Käytetty Melindassa kuitenkin muodossa _typen kierto_.

**Comment by mariaforsen** [comment]
Sv. kvävets kretslopp ET kvävecykel https://finto.fi/mesh/fi/page/D058458?clang=sv kvävekretslopp

**Comment by FinMeSHienPaimentaja** [comment]
"Typen kierto" kuulostaa paremmalta kuin "typpikierto" -> FinMeSH-prion muutos seuraavassa päivityksessä.
