### ISSUE TITLE
monosyytit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8992]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

monosyytit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/321476 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [monosyytit](http://finto.fi/yse/fi/page/Y508992)

**Comment by mirmaid** [comment]
MeSHissä ja TEROssa. Melindassa 5 kertaa MeSH-terminä, 3 kertaa vapaana avainsanana yksikössä ja 3 kertaa monikossa. 

http://id.loc.gov/authorities/subjects/sh85086902
https://fi.wikipedia.org/wiki/Monosyytti
https://www.solunetti.fi/fi/histologia/monosyytti_uusi/
https://www.terveyskirjasto.fi/ltt02165

**Comment by mariaforsen** [comment]
Sv. monocyter
