### ISSUE TITLE
leukemia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8993]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leukemia](http://www.yso.fi/onto/ysa/Y96849) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

uusi KT verisyöpä 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/#/verisy%C3%B6p%C3%A4?searchMode=all

**Comment by YSO-kokous** [comment]
hyväksytään
