### ISSUE TITLE
aivoperäinen dopamiinihermokasvutekijä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8994]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

aivoperäinen dopamiinihermokasvutekijä 

#### Vaihtoehtoiset termit ja ilmaisut   

CDNF 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/320465 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [aivoperäinen dopamiinihermokasvutekijä](http://finto.fi/yse/fi/page/Y508994)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Cerebral_dopamine_neurotrophic_factor

**Comment by mariaforsen** [comment]
suhde tähän: https://mesh.kib.ki.se/term/D019208/brain-derived-neurotrophic-factor ?

**Comment by mirmaid** [comment]
^ Molemmat ovat hermokasvutekijöitä, mutta eivät sama.

**Comment by mariaforsen** [comment]
Sv. cerebral dopaminnervtillväxtfaktor ET CDNF
https://helda.helsinki.fi/bitstream/handle/10138/16161/pro_gradu_Nordstrom_2010.pdf?sequence=1&isAllowed=y
