### ISSUE TITLE
vieritestit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8995]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vieritestit](http://www.yso.fi/onto/ysa/Y169391) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT vierianalyysi, vierianalytiikka 

#### Perustelut ehdotukselle   

https://helda.helsinki.fi/handle/10138/313460 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Myös vieritutkimukset?

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/vieritesti
https://vardgivarguiden.se/administration/verksamhetsadministration/remittering/medicinsk-service/patientnara-analyser/

**Comment by YSO-kokous** [comment]
hyväksytään vieritestit KT vierianalyysi, vierianalytiikka, vieritutkimukset
