### ISSUE TITLE
vastasyntyneen hengitysvaikeusoireyhtymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8996]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vastasyntyneen hengitysvaikeusoireyhtymä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/bitstream/handle/10138/315034/HORMONAL.pdf?sequence=1&isAllowed=y 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vastasyntyneen hengitysvaikeusoireyhtymä](http://finto.fi/yse/fi/page/Y508996)

**Comment by mirmaid** [comment]
http://www.yso.fi/onto/mesh/D012127

Muutamia kertoja Melindassa (hengitysvaikeus/hengitysvaikeusoireyhtymä).

**Comment by mariaforsen** [comment]
Sv. andnödssyndrom hos nyfödda /mesh
