### ISSUE TITLE
ruumishuoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8997]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruumishuoneet 

#### Ehdotettu termi englanniksi   

morgues 

#### Ehdotettu termi ruotsiksi   

bårhus 

#### Vaihtoehtoiset termit ja ilmaisut   

mortuaries [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[rakennukset käyttötarkoituksen mukaan](http://www.yso.fi/onto/yso/p493) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85087265> 
Wikidata : https://www.wikidata.org/wiki/Q6451172 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Finnassa "ruumishuone"-haku tuottaa yli 800 osumaa, myös tekstiaineistoja, mikä viittaa asiasanan tarpeellisuuteen. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [ruumishuoneet](http://finto.fi/yse/fi/page/Y508997)

**Comment by mirmaid** [comment]
Melindassa 5 kertaa Kaunokki-terminä. On MAOssa.
