### ISSUE TITLE
veisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8998]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[veisto](http://www.yso.fi/onto/ysa/Y100125) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan 

#### Perustelut ehdotukselle   

Ruotsiksi vastine on ollut slöjd (veisto/puutyö kouluaineena). Onko sanastossa termi joka viittaisi tähän kouluaineeseen? Ks. Kielitoimiston sanakirja. Melindassa tämä on käytetty melko paljon kouluaineesta (ruotsin vastineen takia?) Mutta myös muusta kuin "puunveistosta", eli esim. kiven veistosta, lumen veistosta jne. Voidaanko rajata pelkästään puunveistoon? Yläkäsite onkin kyllä jo puutyöt. Tämän käsittelyn jälkeen muutetaan ruotsin vastine (träslöjd, täljning..?)

**Comment by jtuohini** [comment]
Kouluaineen osalta on: [**tekninen työ**](https://finto.fi/yso/fi/page/p5558).

**Comment by mirmaid** [comment]
Yllättävän paljon on jäänveistosta aineistoa, mutta sanastossa on jo _jääveistokset_, joka varmaan niissä riittää. Jonkin verran on kiven ym. materiaalien veistoa, johon sitten ehkä riittäisi _kivityöt, luutyöt_ yms.?

Usein näihin veisto-viitteisiin sopii myös _kuvanveisto_, mutta ei toki läheskään aina.

**Comment by mariaforsen** [comment]
Ruotsin osalta tekniskt arbete ei ole ensisijaisesti kouluaine, ks. esim. https://www.framtid.se/yrken/tekniskt-arbete

**Comment by mirmaid** [comment]
^ Pitää ehkä tarkentaa, koska suomeksi on - virheellistä käyttöä kuitenkin vähän myös suomeksi, joten voisi katsoa lisätäänkö tarkenne suomeksikin.

**Comment by mirmaid** [comment]
tutkitaan myös tekstiilityö - voiko käyttää / onko käytetty laajemmin kuin oppiaineesta

**Comment by mirmaid** [comment]
Myös _tekstiilityö_ käytetty laajemmin Melindassa.

**Comment by mariaforsen** [comment]
Ruotsiksi textilslöjd käy myös laajemmin kuin pelkästään oppiaineesta.

**Comment by mirmaid** [comment]
Lisätäänkö tarkenne (oppiaineet) myös tekstiilityölle?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**tekstiilityö**
tekstiilialan työ; neule, kudonnainen tms.
Tekstiilitöiden näyttely.
Erik.
osana peruskoulun käsityön oppiainetta.

**Comment by YSO-kokous** [comment]
### Päätös
muutetaan termi tekstiilityö (oppiaineet)
lisätään käsite tekstiilityöt  YK käsityöt

**Comment by jtuohini** [comment]
Asiasana **tekninen työ (oppiaineet)** on vielä vailla KT-muotoa _veisto (oppiaineet)_, joten kai sekin lisätään? Siitähän tämä koko sanavyyhti on lähtenyt purkautumaan.
