### ISSUE TITLE
Les six

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#8999]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Les six 

#### Ehdotettu termi englanniksi   

Les six 

#### Ehdotettu termi ruotsiksi   

Les six 

#### Vaihtoehtoiset termit ja ilmaisut   

Les 6 
Kuuden ryhmä 

#### Ehdotettu yläkäsite YSOssa (LT)   

[säveltäjät](http://www.yso.fi/onto/yso/p2353) 
[taiteilijaryhmät](http://www.yso.fi/onto/yso/p2393) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh94007895> 
Wikidata : https://www.wikidata.org/wiki/Q841212 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006824092, https://melinda.kansalliskirjasto.fi/byid/002475639, https://melinda.kansalliskirjasto.fi/byid/007225290 jne. 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Les six](http://finto.fi/yse/fi/page/Y508999)

**Comment by jtuohini** [comment]
Ja KT:ksi ainakin myös Groupe des six [eng] ja De sex [swe].

Myös voisi harkita, pitääkö asiasanan olla mieluummin muodossa **_Les six (säveltäjäryhmä)_** samaan tapaan kuin on **Helsinki School (taiteilijaryhmä)**. LT–ST-suhteen osalta ks. myös https://github.com/Finto-ehdotus/YSE/issues/9004.

**Comment by mirmaid** [comment]
Eikö tämän pitäisi olla yhteisö? Jos ei, niin miksi ei? Vaikea perustella, miksi esim. festivaaleja pitäisi siirtää pois YSOsta, jos sitten tämän tyyppisiä kuitenkin halutaan lisätä. Toki siis _Groupe des six_  on LCSH:ssa auktorisoitu 150-kentässä, mutta ei kai se voi olla linjauksen peruste?

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta sulkutarkenteella "säveltäjäryhmä". Kyse ei ole yksiselitteisesti yhteisöstä vaan löyhähköstä säveltäjien ryhmittymästä.
Kyseessä on yksilökäsite.
LT (jos hyväksytään): säveltäjäryhmät

**Comment by YSO-kokous** [comment]
LCSH määritellyt  aiheena "Groupe des six (Group of composers)" http://id.loc.gov/authorities/subjects/sh94007895
ja Ranskan kansalliskirjasto taasen toimijana. https://catalogue.bnf.fr/ark:/12148/cb13195155c
Ehdotetaan lisättäväksi toimijakuvailuun.

**Comment by mirmaid** [comment]
Ehdotettu Kantoon.

**Comment by YSO-kokous** [comment]
Hyväksytty Kantoon: http://urn.fi/URN:NBN:fi:au:finaf:000216906
