### ISSUE TITLE
viiden ryhmä (säveltäjäryhmä)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9000]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

viiden ryhmä (säveltäjäryhmä) 

#### Ehdotettu termi englanniksi   

The Five (group of composers) 

#### Vaihtoehtoiset termit ja ilmaisut   

nuorvenäläinen koulukunta (säveltäjäryhmä) 
venäläinen viisikko (säveltäjäryhmä) 
Mighty Handful (group of composers) 
Mighty Five (group of composers) 
New Russian School 
Russian Five (group of composers) 
The 5 (group of composers) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[säveltäjät](http://www.yso.fi/onto/yso/p2353) 
[taiteilijaryhmät](http://www.yso.fi/onto/yso/p2393) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh00000601> 
Wikidata : https://www.wikidata.org/wiki/Q190390 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/001493578, https://melinda.kansalliskirjasto.fi/byid/011720197 jne. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [viiden ryhmä (säveltäjäryhmä)](http://finto.fi/yse/fi/page/Y509000)

**Comment by mariaforsen** [comment]
Sv. De fem (tonsättargrupp) ET nyryska skolan, ungryska skolan, novatorerna, Mogutjaja kutjka 
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/nyryska-skolan
http://www.musiksok.se/MUSTERM/u_nyryska_skolan.html
https://sv.wikipedia.org/wiki/De_fem

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Kyseessä on yksilökäsite.
LT (jos hyväksytään): säveltäjäryhmät
Lisäksi RT: _mogutšaja kutška_

**Comment by fantsby-m** [comment]
Isolla kai nyt kuitenkin: Viiden ryhmä (ja Mogutšaja kutška)

**Comment by YSO-kokous** [comment]
Pohdittiin milloin ryhmä on niin löyhä, ettei se ole yhteisö. Todettiin, että tämä on selkeästi ryhmä, jonka henkilötkin tunnetaan, jolloin se kuuluisi auktorisoida toimijana eikä YSOssa.  Ehdotuksen näkökulma on enemmänkin "koulukunta". Ryhmä ei ole itse nimennyt itseään.

Päätettiin kuitenkin ottaa tämä ryhmä YSOon.  KÄ "Viiden ryhmä". KT "Mogutšaja kutška"
