### ISSUE TITLE
säveltäjäryhmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9004]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

säveltäjäryhmät 

#### Ehdotettu termi englanniksi   

groups of composers 

#### Ehdotettu termi ruotsiksi   

tonsättargrupper 

#### Vaihtoehtoiset termit ja ilmaisut   

composers' groups 
säveltäjäryhmittymät 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[taiteilijaryhmät](http://www.yso.fi/onto/yso/p2393) 

#### Tarkoitusta täsmentävä selite   

Ks. esim. https://sv.wikipedia.org/wiki/Kategori:Tons%C3%A4ttargrupper 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Perustelut ehdotukselle   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [säveltäjäryhmät](http://finto.fi/yse/fi/page/Y509004)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. tonsättargrupper ET kompositörsgrupper

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
