### ISSUE TITLE
tasapaino

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9005]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tasapaino](http://www.yso.fi/onto/ysa/Y104549) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätäänkö ryhmiä vai tarkenne? 

#### Perustelut ehdotukselle   

YSOssa nyt vain ryhmissä 07 ja 48, mutta Melindassa käytetty myös paljon laajemmin. Mielestäni pitää joko lisätä tarkenne (ja korjata aika paljon Melindassa) tai laajentaa lisäämällä ryhmiä (00?) Ruotsin osalta on aivan ok lisätä ryhmiä.

**Comment by mirmaid** [comment]
00?
