### ISSUE TITLE
basaarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9006]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

basaarit 

#### Ehdotettu termi englanniksi   

bazaars 

#### Ehdotettu termi ruotsiksi   

basarer * 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85012584> 
Wikidata : https://www.wikidata.org/wiki/Q219760 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Melindassa jonkin verran aineistoa, joka käsittelee nimenomaan basaareja. Finnassa lisäksi kuva-aineistoa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ks. yllä 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [basaarit](http://finto.fi/yse/fi/page/Y509006)

**Comment by jtuohini** [comment]
LT-suhteeksi olisi tarve **_kauppapaikat_**-asiasanalle, joka näyttää jääneen pelkäksi YSE-ehdotukseksi (https://github.com/Finto-ehdotus/YSE/issues/950).

**Comment by mirmaid** [comment]
4 viitettä Melindassa. _Kauppapaikat_ 19 kertaa Masa-sanana ja 13 kertaa vapaana avainsanana. Molemmat termit ovat MAOssa.

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Basarer
