### ISSUE TITLE
kauppakeskukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9007]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kauppakeskukset](http://www.yso.fi/onto/ysa/Y118837) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "kauppagalleriat" 

#### Perustelut ehdotukselle   

Ks. https://www.kielitoimistonsanakirja.fi/kauppagalleria 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
hyväksytään  kauppakeskukset KT kauppagalleriat
