### ISSUE TITLE
Lapua -- Länsikylä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9010]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Lapua -- Länsikylä](http://www.yso.fi/onto/ysa/Y123534) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT Prepula 

#### Perustelut ehdotukselle   

Kylän vanha nimi, ks. MOT

**Comment by mirmaid** [comment]
Lisätty.
