### ISSUE TITLE
Raasepori

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9011]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Raasepori](http://www.yso.fi/onto/ysa/Y163327) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan? 

#### Perustelut ehdotukselle   

Sanastossa on myös Raasepori (Tammisaari)

**Comment by ilona-x** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9061
