### ISSUE TITLE
avoleikkaukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9012]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

avoleikkaukset 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/315031 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [avoleikkaukset](http://finto.fi/yse/fi/page/Y509012)

**Comment by mirmaid** [comment]
Ei Melindassa...tätä on vähän vaikea ilmaista, jos verrataan esim. tähystysleikkausta ja avoleikkausta. 

Lääketieteen termit: _leikkaus joka tehdään (vain) leikkausviillon →avauksen kautta; vrt. tähystysleikkaus_

**Comment by mariaforsen** [comment]
Näköjään myös tietermi: https://termipankki.fi/tepa/sv/s%C3%B6k/avoleikkaus

**Comment by FinMeSHienPaimentaja** [comment]
Maallikkona on (väärä?, oikea?) käsitys, että leikkaushoito yleensä olisi avoleikkausten tekoa -> ei tarvisi erikseen puhua avoleikkauksista. Toki "avoleikkaukset" saattaa olla tarpeen, jos vertaillaan esim. leikkausmenetelmiä.

**Comment by mirmaid** [comment]
^^ No kuinkas muuten :confounded:

^ Nykyään on ilmeisesti tähystysleikkaukset yleistyneet niin paljon joissakin leikkausaiheissa, että sitten tulee jo vertailevia tutkimuksia joissa avoleikkaukset on se epätyypillinen tilanne.

**Comment by YSO-kokous** [comment]
hyväksytään muodossa  avoleikkaukset (leikkaushoito)

**Comment by mariaforsen** [comment]
Sv. öppen kirurgi ET öppna operationer
jfr https://finto.fi/mesh/fi/page/D061887?clang=sv
