### ISSUE TITLE
Karl Gustav (Länsipohja)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9014]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Karl Gustav (Länsipohja)](http://www.yso.fi/onto/ysa/Y226828) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkenne voisi myös olla Norrbotten 

#### Perustelut ehdotukselle   

Viitataanko vain Karl Gustaviin ennen v. 1809? Silloin oli Länsipohjan alueella. Mutta onhan sen jälkeenkin ollut Karl Gustav ja nykyään se on Norrbottenin alueella, ei Länsipohjan. 
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/karl-gustav-(2)

**Comment by mariaforsen** [comment]
Ks. myös https://fi.wikipedia.org/wiki/V%C3%A4sterbotten Nykyään Karl Gustav ei siis ole ollenkaan Länsipohjan alueella, vaan Norrbottenin.

**Comment by mirmaid** [comment]
Muutettu. En osaa sanoa enää miksi tein alun perin noin, kun ehdotus taisi tulla joltain excel-listalta.
