### ISSUE TITLE
Raman-spektroskopia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9017]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Raman-spektroskopia 

#### Ehdotettu termi englanniksi   

Raman spectroscopy 

#### Ehdotettu termi ruotsiksi   

Raman-spectroskopi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[spektroskopia](http://www.yso.fi/onto/yso/p10176) 
[spektrianalyysi](http://www.yso.fi/onto/yso/p23978) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Raman_spectroscopy 
LCSH : <http://id.loc.gov/authorities/subjects/sh85111278> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 
[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 15 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Application of Raman spectroscopy for the characterisation of synthetic non-metallic inclusions found in Al-killed calcium treated steels 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Raman-spektroskopia](http://finto.fi/yse/fi/page/Y509017)

**Comment by mirmaid** [comment]
http://www.yso.fi/onto/mesh/D013059. Ehdotettu muoto on kuitenkin paljon käytetympi.

**Comment by mariaforsen** [comment]
Sv. Ramanspektroskopi /ne, mesh
