### ISSUE TITLE
hyperspektrikuvantaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9019]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Hyperspectral imaging 

#### Ehdotettu termi suomeksi   

hyperspektrikuvantaminen 

#### Ehdotettu termi ruotsiksi   

hyperspektral avbildning 

#### Vaihtoehtoiset termit ja ilmaisut   

hyperspektrikuvaus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[spektrikuvaus](http://www.yso.fi/onto/yso/p26364) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2017003567> 
Wikipedia : https://en.wikipedia.org/wiki/Hyperspectral_imaging 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

New options for non-invasive imaging and non-invasive treatment of skin cancers / 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hyperspektrikuvantaminen](http://finto.fi/yse/fi/page/Y509019)

**Comment by mirmaid** [comment]
Melindassa kerran hyperspektrikuvantaminen, 2 kertaa hyperspektrikuvaus. Googlella "kuvantaminen" paljon käytetympi.

**Comment by mariaforsen** [comment]
Sv. https://mesh.kib.ki.se/term/D000081862/hyperspectral-imaging
