### ISSUE TITLE
fotodynaaminen hoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9020]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fotodynaaminen hoito](http://www.yso.fi/onto/ysa/Y125092) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

lisätään KT-muodot valoaktivaatiohoito & PDT-hoito 

#### Perustelut ehdotukselle   

Fotodynaamisessa hoidossa (valoaktivaatiohoito, PDT-hoito) Lähde: https://www.terveyskirjasto.fi/dlk00913 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään
