### ISSUE TITLE
poliisikorkeakoulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9027]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[poliisikorkeakoulut](http://www.yso.fi/onto/ysa/Y109520) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

voisiko lisätä KT poliisiammattikorkeakoulut?
Huom. yläkäsite nyt yliopistot 

#### Perustelut ehdotukselle   

Suomessa poliisien korkea-asteen koulutusta tarjoaa Poliisiammattikorkeakoulu (joka löytyy toki yhteisönimistä) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Korkeakoulujen hierarkia on kyllä vähän erikoinen nyt. Ehkäpä yliopistojen alla voisi olla vain yliopistoiksi nimitetyt?

**Comment by YSO-kokous** [comment]
hyväksytään poliisikorkeakoulut KT poliisiammattikorkeakoulut
Selkeytetään hierarkia.
