### ISSUE TITLE
polydekstroosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9028]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

polydekstroosi 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.uef.fi/fi/artikkeli/ruokavaliota-taydentamalla-voidaan-saadella-rasvakudoksen-tulehdusta-ja-nalan-tunnetta 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [polydekstroosi](http://finto.fi/yse/fi/page/Y509028)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Polydekstroosi

**Comment by mariaforsen** [comment]
Sv. polydextros

**Comment by ilona-x** [comment]
Melindassa käytetty vain ehdotuksessa mainitussa väitöskirjassa

**Comment by mirmaid** [comment]
^ Voi sen jättää myös 653:een.

**Comment by mariaforsen** [comment]
Tämä on hyvin selkeä termi, hakusanalla polydextrose löytyy enemmän. Kannatan hyväksymistä.
