### ISSUE TITLE
ellipsometria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9030]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ellipsometria 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.uef.fi/fi/artikkeli/uudenlaisia-optisia-mittausmenetelmia-ja-uutta-tietoa-valon-interferenssista 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ellipsometria](http://finto.fi/yse/fi/page/Y509030)

**Comment by mirmaid** [comment]
3 viitettä Melindassa.

http://id.loc.gov/authorities/subjects/sh85042606
https://en.wikipedia.org/wiki/Ellipsometry

**Comment by mariaforsen** [comment]
Sv. ellipsometri https://portal.research.lu.se/portal/sv/organisations-units/physical-chemistry(934914e2-b090-4249-bed4-6a3f2187938a).html
