### ISSUE TITLE
alkeenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9031]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

alkeenit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://erepo.uef.fi/handle/123456789/23894 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [alkeenit](http://finto.fi/yse/fi/page/Y509031)

**Comment by mirmaid** [comment]
8 viitettä melindassa. 

http://id.loc.gov/authorities/subjects/sh85094589
https://fi.wikipedia.org/wiki/Alkeenit

**Comment by mariaforsen** [comment]
Sv. alkener ET olefiner /ne
