### ISSUE TITLE
impedanssipneumografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9032]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

impedanssipneumografia 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://trepo.tuni.fi/handle/10024/124003 

**Termiehdotus Fintossa:** [impedanssipneumografia](http://finto.fi/yse/fi/page/Y509032)

**Comment by fantsby-m** [comment]
Ks. myös 
https://www.tuni.fi/fi/ajankohtaista/javier-gracia-tabuenca-pienten-lasten-astman-yonaikainen-kotiseuranta-onnistuu

**Comment by mariaforsen** [comment]
Sv. impedanspneumografi
