### ISSUE TITLE
Korttajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9033]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Korttajärvi](http://www.yso.fi/onto/ysa/Y144435) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Korttajärvi (Jyväskylä)

**Comment by mirmaid** [comment]
Onkohan tässä virhe, Paikkatietoalusta tuntee vain järven. Kylä mahd. Puuppolan toinen nimi, https://fi.wikipedia.org/wiki/Puuppola.

**Comment by ilona-x** [comment]
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=Korttaj%C3%A4rvi

**Comment by mirmaid** [comment]
Yhdistetään Korttajärvi (kylä) KÄ Puuppola. Korttajärvi > Korttajärvi (järvi).
