### ISSUE TITLE
Kurejoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9034]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kurejoki](http://www.yso.fi/onto/ysa/Y115292) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Kurejoki (Alajärvi)

**Comment by mirmaid** [comment]
Mikä olisi toisen tarkenne, wikipedian mukaan "kylä" (osa Alajärven keskustaajamaa), Paikkatietoalustan mukaan "kaupunkialueen tai taajaman osa". 
https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/tietokortit/nimisto/paikka/10320676
https://fi.wikipedia.org/wiki/Kurejoki

**Comment by ilona-x** [comment]
Asutusnimihakemistossa kylä https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=kurejoki

**Comment by mirmaid** [comment]
Tarkenteeseen "kylä".
