### ISSUE TITLE
matot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9036]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[matot](http://www.yso.fi/onto/ysa/Y97322) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "lattiamatot" 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/lattiamatto 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään matot KT lattiamatot
