### ISSUE TITLE
itämaiset matot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9037]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[itämaiset matot](http://www.yso.fi/onto/ysa/Y95600) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "aidot matot" sekä ainakin "anatolialaiset matot", "kaukasialaiset matot", "klassisset anatolialaiset matot", "mamelukkimatot", "osmanimatot", "persialaiset hovimatot" ja "persialaiset matot". 

#### Perustelut ehdotukselle   

Melko hassun kuuloista "aito matto" -ilmausta käytetään yleisesti käsinsolmituista itämaisista matoista (googlaamalla lähes 5 000 osumaa), joten viittaussuhde voisi olla hyväksi. Lisäksi eri mattotyyppien 'ylätasot' olisi hyvä saada viitatuiksi, kun niille tuskin tarvitaan omia asiasanojaan ja alkuperäalue voidaan ilmaista yhdistämällä "itämaiset matot" ja asianmukainen maantieteellinen asiasana. Erilaisia tarkkoja mattotyyppejä ("Holbein-matot", "kelimit", "lohikäärmematot", "Lotto-matot", "qomit" eli "Kum-matot", "Qum-matot" jne, "Uşak-matot" eli uşakit yms) riittäisi loputtomiin, mutta tarve niille marginaalinen. – Päätyypeistä ks. esim. Geknüpfte Kunst: Teppiche des Museums für Islamische Kunst, hrsg. von Anna Beselin (Edition Minerva, 2011). 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Näistä _persialaiset matot_ tuo runsaasti viitteitä Googlella, _aidot matot_ myös jonkin verran. _Anatolialaiset matot, kaukasialaiset matot_ ja _persialaiset hovimatot_ tuovat kukin muutaman viitteet, muut eivät mitään.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi  itämaiset matot KT persialaiset matot, aidot matot
