### ISSUE TITLE
kelimit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9038]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kelimit 

#### Ehdotettu termi englanniksi   

kilims 

#### Ehdotettu termi ruotsiksi   

kelimer 

#### Vaihtoehtoiset termit ja ilmaisut   

kelims [eng] 
gilims [eng] 
kelim-matot [fin] 
sumakit [fin] 
soumaks [eng] 
kelilmmattor [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[itämaiset matot](http://www.yso.fi/onto/yso/p1597) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85072317> 
Wikidata : https://www.wikidata.org/wiki/Q585358 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[26 Tekstiiliteollisuus. Vaatetusteollisuus. Jalkineteollisuus. Nahkateollisuus. Turkisteollisuus](http://www.yso.fi/onto/yso/p26578) 
[94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/013503633, https://melinda.kansalliskirjasto.fi/byid/007046113, https://melinda.kansalliskirjasto.fi/byid/005732814 jne. 

#### Perustelut ehdotukselle   

Kelimeistä näyttääkin löytyvän sen verran aineistoa, että tarkka asiasana sille sittenkin tarpeen ("itämaiset matot" turhan epätarkka). 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kelimit](http://finto.fi/yse/fi/page/Y509038)

**Comment by mirmaid** [comment]
13 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. https://svenska.se/tre/?sok=kelim&pz=1
