### ISSUE TITLE
Silkkitie

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9039]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Silkkitie](http://www.yso.fi/onto/ysa/Y98845) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCSH:n maantieteelliseen asiasanaan "Silk Road" (http://id.loc.gov/authorities/subjects/sh85122554) 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätään, jos YSO-paikat jossain vaiheessa linkitetään LCSH-sanastoon.
