### ISSUE TITLE
airfryerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9040]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

airfryerit 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The skinnytaste air fryer cookbook : the best healthy recipes for your air fryer 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [airfryerit](http://finto.fi/yse/fi/page/Y509040)

**Comment by mirmaid** [comment]
https://www.testivoittaja.net/kodinkoneet/airfryer-kokemuksia/
airfryer / ilmakeitin / kiertoilmakypsennin / ilmafriteerauskeitin / ilmakypsennin

**Comment by mirmaid** [comment]
Mietittiin lasten kanssa kotona, että mikä tämän suomenkielinen nimi olisi, ihan omasta päästä päädyttiin muotoon ilmakeitin :slightly_smiling_face:.

**Comment by mirmaid** [comment]
Melindassa kerran _airfryerit_. Googlella käytetyin yksikössä _airfryer_, monikossa _kiertoilmakypsentimet_.

**Comment by mariaforsen** [comment]
Sv. airfryer, varmluftsfritöser..?

**Comment by LeKorsu** [comment]
Kannatan mitä tahansa suomenkielistä airfryerin sijaan!

**Comment by Jaakkina** [comment]
Suomenkielinen termi ei ole tuntunut vakiintuneen kahdessa vuodessa. Kirjallisuudessa ja sosiaalisen median kanavilla käytetään yleisesti airfryer-termiä, sama termi on käytössä myös suomenkielisessä kirjassa Spåra / Airfryer : maukkaampaa & terveellisempää. Laitevalmistaja Philips ja elintarvikeala käyttävät suomenkielisissä internet-sivuillaan termiä "airfryer". Olisi mukava saada sellainen termi käyttöön, jolla kaikenkieliset kirjat löytyisivät yhdellä kertaa. Kirjoitusasuissa on eroa, esim. "airfryer" vs. englanninkielinen termi "air fryer" tai "air-fryer",

**Comment by mirmaid** [comment]
Tämä https://github.com/Finto-ehdotus/YSE/issues/9040#issuecomment-831708443 pitää edelleen paikkansa, paitsi Melindassa nyt 5 kertaa. 

Yksiköss _airfryer_ on ylivoimaisesti käytetyin muoto, mutta _kiertoilmakypsennin_ myös paljon käytetty.

**Comment by mariaforsen** [comment]
Sv. varmluftsfritöser HT airfryers
https://spraktidningen.se/qa/lat-svenskan-ga-fore-engelskan/

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _kiertoilmakypsentimet_, ohjausterminä _airfryerit_.
