### ISSUE TITLE
Danzig

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9042]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Danzig](http://www.yso.fi/onto/ysa/Y169018) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään/selkeytetään 

#### Perustelut ehdotukselle   

Sanastossa on myös Gdansk, onko todella molempien tarkoitus olla päätermeinä? Molemmissa (luonnollisesti) sama wikipedia-artikkeli,

**Comment by mirmaid** [comment]
Yhdistetään, YK Puola?

**Comment by ilona-x** [comment]
SAO: 
Polen--Gdansk KT Danzig  https://id.kb.se/term/sao/Polen--Gdansk

**Comment by ilona-x** [comment]
Myös tämän parin voisi varmaan yhdistää:

**Stettin & [Szczecin](http://www.yso.fi/onto/yso/p192081)** 
Stettinin nimi muuttui Szczeciniksi pian toisen maailmansodan jälkeen, jolloin kaupunki luovutettiin Puolalle

SAO: Szczecin KT Stettin

**Comment by mirmaid** [comment]
Gdansk KT Danzig
Szczecin KT Stettin
