### ISSUE TITLE
mansikan punamätä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9043]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mansikan punamätä 

#### Ehdotettu termi englanniksi   

Phytophthora fragariae 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kasvitaudit](http://www.yso.fi/onto/yso/p8076) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[16 Kasvitiede](http://www.yso.fi/onto/yso/p26533) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda: mansikan punamätä x 6 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Application of recombinase polymerase amplification to diagnosis of phytophthora diseases of strawberry 

#### Tarkoitusta täsmentävä selite   

https://www.ruokavirasto.fi/viljelijat/kasvintuotanto/kasvinterveys/kasvintuhoojat/laatutuhoojat/punamata/

--
HUOM. AFOsssa perunanpunamätä http://www.yso.fi/onto/afo/p2196 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mansikan punamätä](http://finto.fi/yse/fi/page/Y509043)

**Comment by mariaforsen** [comment]
Sv. jordgubbsrödröta https://www.dyntaxa.se/Taxon/Info/6034698?changeRoot=True  ET rödröta på jordgubbar https://www.ruokavirasto.fi/sv/odlare/vaxtproduktion/vaxthalsa/vaxtskadegorare/kvalitetsskadegorare/rodrota-pa-jordgubbar/
