### ISSUE TITLE
lamalaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9049]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lamalaisuus](http://www.yso.fi/onto/ysa/Y102989) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotetaan käytettävän termin vaihtamista muotoon  ”tiibetinbuddhalaisuus” ja  ”lamalaisuus” poistamista tai siirtämistä ohjaustermiksi. 

#### Perustelut ehdotukselle   

Finto feedback Ehdotus 1:
Termi ’lamalaisuus’ on vanhanaikainen ja epätarkka, ja mieluummin käytetään termiä ’tiibetinbuddhalaisuus’.Voisiko YSOn puolella häivyttää tuon ”lamalaisuuden”? ”Lama” tietenkin pitää edelleen siellä olla, sillä se tarkoittaa ”tiibetinbuddhalaista korkea-arvoista opettajaa”. -- Asiakaspalaute [[KK-02562559]] 

Ehdotus 2:
Lamalaisuus on ainakin joidenkin mielestä jo vanhahtava termi ja käyttäisimme luetteloinnissa mieluiten neutraaleja ja myös kansainvälisesti relevantteja termiä. Suomenkielisessä Wikipediassa käytetään tosin yläotsikkona lamalaisuutta, mutta englantilaisessa Tibetan buddhism. Nyt finto kääntää lamalaisuuden lamaismiksi. Jos tiibetinbuddhalaisuus on modernimpi ja kansainvälisesti käytetympi termi, niin asia olisi hyvä korjata myös fintoon.   -- Asiakaspalaute [[KK-02561806]] 

#### Ehdottajan organisaatio   

Kansalliiskirjasto / asiakaspalaute

**Comment by YSO-kokous** [comment]
hyväksytään tiibetinbuddhalaisuus KT lamalaisuus
