### ISSUE TITLE
ojibwat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9050]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ojibwat 

#### Ehdotettu termi englanniksi   

Ojibwa Indians 

#### Vaihtoehtoiset termit ja ilmaisut   

ojibwa-intiaanit 
ojibwayt 

#### Ehdotettu yläkäsite YSOssa (LT)   

[intiaanit](http://www.yso.fi/onto/yso/p646) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85024423> 
Wikipedia : https://fi.wikipedia.org/wiki/Ojibwayt 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Studying native North American literature : nature/land relationships and native (Ojibwe) ecologue in Louise Erdrich's Birchbark House series 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [ojibwat](http://finto.fi/yse/fi/page/Y509050)

**Comment by mirmaid** [comment]
13 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. ojibwa (folk) ET ojibwaindianer, chippewa (folk), salteaux (folk)
https://id.kb.se/term/sao/Ojibwa%20%28folk%29
