### ISSUE TITLE
asiakasturvallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9051]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

asiakasturvallisuus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[turvallisuus](http://www.yso.fi/onto/yso/p7349) 

#### Perustelut ehdotukselle   

Termi löytyy KOKOsta, muttei YSOsta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Sosiaalisesti kestävää Kymenlaaksoa tekemässä 

**Ehdottajan organisaatio:** UEF kirjasto **Termiehdotus Fintossa:** [asiakasturvallisuus](http://finto.fi/yse/fi/page/Y509051)

**Comment by mirmaid** [comment]
TSR-ontologiassa. Ei Melindassa.

**Comment by mirmaid** [comment]
Potilas- ja asiakasturvallisuus tarkoittaa sosiaali- ja terveydenhuollossa toimivien henkilöiden ja organisaatioiden periaatteita ja toimintoja, joilla varmistetaan hoidon, hoivan ja palvelujen turvallisuus ja suojataan asiakkaita tai potilaita vahingoittumasta. https://www.hel.fi/sote/fi/esittely/potilas--ja-asiakasturvallisuus/

_Potilasturvallisuus_ on sanastossa.

**Comment by mariaforsen** [comment]
Sv. klientsäkerhet (socialvård)
(klientsäkerhet jos sosiaalihuoltoon liittyvä, muuten voi olla myös kundsäkerhet)
