### ISSUE TITLE
lääkkeenkantajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9052]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

lääkkeenkantajat 

#### Ehdotettu termi englanniksi   

drug carriers (Pharmacy) 

#### Ehdotettu termi ruotsiksi   

läkemedelsbärare 

#### Vaihtoehtoiset termit ja ilmaisut   

lääkkeenkuljettajat 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85039758> 
Wikipedia : https://en.wikipedia.org/wiki/Drug_carrier 
FinMeSH : <http://www.yso.fi/onto/mesh/D004337> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Preparation and characterization of extracellular vesicles for cancer therapy 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [lääkkeenkantajat](http://finto.fi/yse/fi/page/Y509052)

**Comment by mirmaid** [comment]
6 kertaa Melindassa MeSH-terminä.

**Comment by mirmaid** [comment]
KT lääkekuljettimet, lääkkeenkuljettimet

https://helda.helsinki.fi/handle/10138/321150

**Comment by mariaforsen** [comment]
Sv. ET läkemedelstransportörer
