### ISSUE TITLE
kehonulkoinen happeuttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9053]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kehonulkoinen happeuttaminen 

#### Ehdotettu termi englanniksi   

Extracorporeal Membrane Oxygenation 

#### Ehdotettu termi ruotsiksi   

extrakorporeal membransyresättning 

#### Vaihtoehtoiset termit ja ilmaisut   

ECMO 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hoitomenetelmät](http://www.yso.fi/onto/yso/p392) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh92005395> 
FinMeSH : <http://www.yso.fi/onto/mesh/D015199> 
Wikipedia : https://fi.wikipedia.org/wiki/ECMO 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Venoarterial membrane oxygenation and heart transplantation in management of severe heart failure 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kehonulkoinen happeuttaminen](http://finto.fi/yse/fi/page/Y509053)

**Comment by FinMeSHienPaimentaja** [comment]
Mm. koronan hoitoon liittyen tarpeellinen termi. "Happeuttaminen" kuulostaa kielikorvaani oudolta, mutta se löytyy myös:

Lääketieteen termit

_ECMO
extracorporeal membrane oxygenation, extracorporeal life support e extrakorporeal membranoxygenering r veren kehonulkoinen happeuttaminen (sydän-keuhkokoneella)_

**Comment by mariaforsen** [comment]
Sv.  extrakorporeal membranoxygenering https://sv.wikipedia.org/wiki/Extrakorporeal_membranoxygenering ET ECMO /ne, extrakorporeal membransyresättning https://finto.fi/mesh/sv/page/D015199
