### ISSUE TITLE
paraatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9054]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[paraatit](http://www.yso.fi/onto/ysa/Y112075) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "sotilasparaatit" 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/sotilasparaati 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
… ja vastaavasti myös _militärparader_ (ruotsiksi) ja _military parades_ (englanniksi). Vrt. SAO:n ja LCSH:n itsenäiset asiasanat [**Militärparader**](https://id.kb.se/term/sao/Milit%C3%A4rparader) ja [**Military parades**](http://id.loc.gov/authorities/subjects/sh2018002201), joista edellisellä on KT-muotona lisäksi _Vaktparader_. Suomeksi voisi harkita lisäksi KT-muotoja _vahtiparaatit_ ja _vartioparaatit_. Ks. esim. https://www.kielitoimistonsanakirja.fi/#/vahtiparaati ja jopa _Tonttujen vahtiparaati_ -laulu…

**Comment by mirmaid** [comment]
Termeillä _vahtiparaatit, vartioparaatit_ ei löydy aihehaulla Melindasta tai Finnasta mitään (myöskään yksikössä). _Vahdinvaihto_ tuo 4 viitettä Finnassa, mutta ne ovat lasten aineistoa, jossa vahdinvaihto on Kielitoimiston sanakirjan merkityksessä ark. vuoron vaihto. Mielestäni ei tarpeen tässä vaiheessa lisätä ohjaustermejä tai ottaa vahdinvaihtoa erikseen.

**Comment by YSO-kokous** [comment]
Ei hyväksytä vahdinvaihdot eikä vahtiparaatit
