### ISSUE TITLE
danit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9055]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[danit](http://www.yso.fi/onto/ysa/Y133139) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

1) LCHS linkin korjaus. 
2) Yläkäsitteeksi afrikkalaiset  http://www.yso.fi/onto/yso/p1680
3) Tarkenteen lisäys danit (Länsi-Afrikka) 

#### Perustelut ehdotukselle   

Kyseessä on kansa Länsi-Afrikassa  https://fi.wikipedia.org/wiki/Danit  https://www.wikidata.org/wiki/Q1804699 , joten LCSH linkki pitäisi olla https://id.loc.gov/authorities/sh85054292  

Erotukseksi danit (Länsi-Uusi-Guinea)  [uusi käsite] on https://en.wikipedia.org/wiki/Dani_people, https://www.wikidata.org/wiki/Q1159714, http://id.loc.gov/authorities/subjects/sh85035716 

#### Ehdottajan organisaatio   

Kansalliskirjasto/Finto

**Comment by jarmosaarikko** [comment]
jos on käytetty molemmista, jaetaan käsite

**Comment by YSO-kokous** [comment]
jos on käytetty molemmista, jaetaan käsite

**Comment by ilona-x** [comment]
Melinda x 6, kaikki näyttäisivät käsittelevän Uuden-Guinean daneja

**Comment by mariaforsen** [comment]
Sv.
dani (folk) ET ndani (folk) https://id.kb.se/term/sao/Dani%20%28folk%29
dan (folk) ET dan (afrikanskt folk) https://id.kb.se/term/sao/Dan%20%20%28folk%29
