### ISSUE TITLE
piispantalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9056]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

piispantalot 

#### Ehdotettu termi ruotsiksi   

biskopshus 

#### Ehdotettu termi englanniksi   

bishop's houses 

#### Vaihtoehtoiset termit ja ilmaisut   

piispankartanot 
bishop's palaces 

#### Ehdotettu yläkäsite YSOssa (LT)   

[virkatalot](http://www.yso.fi/onto/yso/p426) 

#### Assosiatiiviset (RT)   

[pappilat](http://www.yso.fi/onto/yso/p20041) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Tarkoitusta täsmentävä selite   

https://fho.sls.fi/uppslagsord/14414/biskopshus/  Sedan reformationen benämning på biskopsboställe eller biskopens familj. Under 1700-talet också sammanfattningen av biskopsämbetena gentemot något annat ämbete, eller biskopsämbetsinnehavarnas familjer gentemot någon annan ämbetsinnehavares familj.
The residence of a bishop. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kotiseutuliitto.fi/toiminta/kirjamakasiini/esittelyt-ja-arvostelut-2015/kustavin-kaunissalossa-itatalo/ 

#### Perustelut ehdotukselle   

YSO:ssa on jo pappilat. 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [piispantalot](http://finto.fi/yse/fi/page/Y509056)

**Comment by jtuohini** [comment]
LCSH-siltaus: [**Bishops--Dwellings**](http://id.loc.gov/authorities/subjects/sh2009008467) ja [**Bishops--Homes and haunts**](http://id.loc.gov/authorities/subjects/sh85014421).

**Comment by mirmaid** [comment]
Ei Melindassa, on MAOssa. _Itätalo_ on sanastossa.
