### ISSUE TITLE
hyönteishotellit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9057]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hyönteishotellit 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Orlow: Hyönteishotelli 978-952-375-376-1 

#### Perustelut ehdotukselle   

kirjassa 30 rakennusohjetta erilaisista hyönteishotelleista 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [hyönteishotellit](http://finto.fi/yse/fi/page/Y509057)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. insektshotell ET insekthotell, bihotell
https://sv.wikipedia.org/wiki/Insektshotell
