### ISSUE TITLE
todistusharkinta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9062]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

todistusharkinta 

#### Perustelut ehdotukselle   

https://tieteentermipankki.fi/wiki/Oikeustiede:todistusharkinta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/322119 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [todistusharkinta](http://finto.fi/yse/fi/page/Y509062)

**Comment by mirmaid** [comment]
2 viitettä Melindassa. Ei EKS:ssa.

**Comment by mariaforsen** [comment]
Sv. bevisprövning

**Comment by ilona-x** [comment]
OIKO: **todistusharkinta** http://www.yso.fi/onto/oiko/p1496
