### ISSUE TITLE
Kiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9063]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kiikka](http://www.yso.fi/onto/ysa/Y105151) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan sanastoon paikan ruotsinkielinenkin nimi "Kikois". 

#### Perustelut ehdotukselle   

Nyt ruotsinkielisenä nimenä on jostain syystä suomenkielinen nimi, ilman että ruotsinkielinen olisi edes viittausmuotona. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ei kun perutaankin tämä. Kikois on tietysti Kiikoisten, ei Kiikan, ruotsinkielinen nimi!
