### ISSUE TITLE
televisioelokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9068]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[televisioelokuvat](http://www.yso.fi/onto/ysa/Y144391) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä "Elokuva, joka on tuotettu lähtökohtaisesti televisiolevitystä varten." 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
televisiossa esitettäväksi tehty elokuva

Hyväksytään tässä muodossa.
