### ISSUE TITLE
Brittiläinen Guayana

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9075]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Brittiläinen Guayana](http://www.yso.fi/onto/ysa/Y148033) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ohjaus- tai pääterminä myös Brittiläinen Guyana, Brittiläinen Guiana 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Brittil%C3%A4inen_Guiana

**Comment by mirmaid** [comment]
Muutetaanko?

**Comment by ilona-x** [comment]
Lisäisin nämä ohjaustermeiksi, Wikipedia-sivulla on vain englanninkielisiä lähdelinkkejä, joten jää epäselväksi, millä perusteella suomenkielinen nimimuoto on sivulle valittu.

**Comment by mirmaid** [comment]
^ Ok.
