### ISSUE TITLE
hammaskiille

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9077]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hammaskiille 

#### Ehdotettu termi englanniksi   

dental enamel 

#### Ehdotettu termi ruotsiksi   

tandemalj 

#### Assosiatiiviset (RT)   

[hampaat](http://www.yso.fi/onto/yso/p2205) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85042959> 
FinMeSH : <http://www.yso.fi/onto/mesh/D003743> 
Wikipedia : https://fi.wikipedia.org/wiki/Hammaskiille 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 14 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Molar-incisor hypomineralization : observations from groups of Finnish children and a treatment practice survey among 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hammaskiille](http://finto.fi/yse/fi/page/Y509077)

**Comment by mariaforsen** [comment]
Sv. ET emalj (tänder)
