### ISSUE TITLE
Valkjärvi -- Satakunta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9078]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Valkjärvi -- Satakunta](http://www.yso.fi/onto/ysa/Y112240) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon Valkjärvi (Satakunta) 

#### Perustelut ehdotukselle   

Nyt virheellinen muoto YSO-paikoissa: Satakunta (Valkjärvi)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Valkj%C3%A4rvi_(Pomarkku-Siikainen)
http://paikkatiedot.fi/so/1000772/10230236

Paikkatietoalustan mukaan "järvi- tai lampiryhmä", mutta kartalla näyttää kyllä ihan tavalliselta järveltä. Vähän etelään on Vähäselkä-niminen järvi, jonka rannalla on Pikkuvalkjärven uimaranta. Sekin löytyy erikseen, samalla paikkatyypillä: http://paikkatiedot.fi/so/1000772/10230044.

**Comment by mirmaid** [comment]
Tarkenteeksi (Pomarkku)
