### ISSUE TITLE
Hospitz

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9081]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Hospitz 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Vieraanvaraisuutta vuodesta 1933 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Hospitz](http://finto.fi/yse/fi/page/Y509081)

**Comment by mariaforsen** [comment]
Viittaa rakennukseen (iso alkukirjain)? 
https://fi.wikipedia.org/wiki/Hotelli_Hospitz

Sv. Hospitz (Nyslott)
