### ISSUE TITLE
katter

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9083]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kissat

**Ehdotettu termi ruotsiksi**

katter

**Ehdotettu termi englanniksi**

cats

**Tarkoitusta täsmentävä selite**

Mikas test från National Biblioteket

**Perustelut ehdotukselle**

Mikas test från National Biblioteket

**Ehdotettu yläkäsite YSOssa (LT)**

 [Högsar](http://www.yso.fi/onto/yso/p24543)

**Ehdotetut temaattiset ryhmät**

 [00 Allmänna termer](http://www.yso.fi/onto/yso/p26556), [02 Filosofi](http://www.yso.fi/onto/yso/p26545)

**Vaihtoehtoiset termit**

 Alt 1 Mikas test från National Biblioteket, Alt 2Mikas test från National Biblioteket

**Alakäsitteet (RT)**

 [hunnit](http://www.yso.fi/onto/yso/p19557)

**Assosiatiiviset (RT)**

 [assamin kieli](http://www.yso.fi/onto/yso/p25431), [assembly-kieli](http://www.yso.fi/onto/yso/p7766)

**Vastaava käsite muussa sanastossa**

 [www.testi.fi](http://www.testi.fi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mikas test från National Biblioteket

**Ehdottajan organisaatio**

Mikas test från National Biblioteket

**Comment by jarmosaarikko** [comment]
suljin testi-issuen, ettei päädy  FIntoon
