### ISSUE TITLE
kolminpelit [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9085]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kolminpelit [SLM] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit](http://www.yso.fi/onto/yso/p6062) 

#### Perustelut ehdotukselle   

Sisällönkuvailun asiantuntijaryhmän Fiktionaineistoryhmän pelien kuvailua käsittelevässä kokouksessa todettu tarpeelliseksi lisäykseksi SLM-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kolminpelit [SLM]](http://finto.fi/yse/fi/page/Y509085)

**Comment by mariaforsen** [comment]
Sv. "spel för tre spelare"
