### ISSUE TITLE
kuusinpelit [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9088]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kuusinpelit [SLM] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[pelit](http://www.yso.fi/onto/yso/p6062) 

#### Perustelut ehdotukselle   

Sisällönkuvailun asiantuntijaryhmän Fiktionaineistoryhmän pelien kuvailua käsittelevässä kokouksessa todettu tarpeelliseksi lisäykseksi SLM-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kuusinpelit [SLM]](http://finto.fi/yse/fi/page/Y509088)

**Comment by mariaforsen** [comment]
Sv. "spel för sex personer"? Miten merkitys rajautuu, onko kyseessä peli jossa voi olla enintään kuusi pelaajaa, vai esim. 1-6 pelaajaa?

**Comment by mirmaid** [comment]
Vai aina nimenomaan kuusi pelaajaa? Vai mahdollisesti mikä tahansa peli, jota voi pelata kuusi pelaajaa, riippumatta siitä, voiko sitä pelata myös pienemmällä tai suuremmalla joukolla? Pitääkö kuvailussa listata kaikki mahdolliset määrät pelaajia?

Vrt. myös moninpelit.
