### ISSUE TITLE
ensipelit [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9089]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ensipelit [SLM] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lastenpelit](http://www.yso.fi/onto/yso/p26478) 

#### Perustelut ehdotukselle   

Sisällönkuvailun asiantuntijaryhmän Fiktionaineistoryhmän pelien kuvailua käsittelevässä kokouksessa todettu tarpeelliseksi lisäykseksi SLM-sanastoon. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [ensipelit [SLM]](http://finto.fi/yse/fi/page/Y509089)

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. förstaspel ET barns första spel, småbarnsspel

**Comment by mirmaid** [comment]
Sanastoissa ensikirjat KÄ katselukirjat. Tämä lienee silti ok.
