### ISSUE TITLE
solukierto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9091]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

solukierto 

#### Ehdotettu termi englanniksi   

cell cycle 

#### Ehdotettu termi ruotsiksi   

cellcykel 

#### Vaihtoehtoiset termit ja ilmaisut   

solusykli 

#### Alakäsitteet (RT)   

[solunjakautuminen](http://www.yso.fi/onto/yso/p24933) 
[meioosi](http://www.yso.fi/onto/yso/p24934)
[mitoosi](http://www.yso.fi/onto/yso/p24935)

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D002453> 
Wikipedia : https://fi.wikipedia.org/wiki/Solusykli 
LCSH : <http://id.loc.gov/authorities/subjects/sh85021643> 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda: 
solukierto x 7 
solusykli x 14

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Cell cycle regulation via growth factor- and stress-induced pathways  http://urn.fi/URN:ISBN:978-951-51-5909-0 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

https://tieteentermipankki.fi/wiki/Biologia:solukierto 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [solukierto](http://finto.fi/yse/fi/page/Y509091)

**Comment by YSO-kokous** [comment]
Hyväksytään  solukierto KT solusykli
