### ISSUE TITLE
diffraktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9092]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

diffraktio 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/312770 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [diffraktio](http://finto.fi/yse/fi/page/Y509092)

**Comment by mirmaid** [comment]
21 viitettä Melindassa. 

https://fi.wikipedia.org/wiki/Diffraktio
http://id.loc.gov/authorities/subjects/sh85037928

**Comment by mariaforsen** [comment]
Sv. diffraktion
