### ISSUE TITLE
sylkikaskas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9093]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sylkikaskas 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/313939 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [sylkikaskas](http://finto.fi/yse/fi/page/Y509093)

**Comment by mariaforsen** [comment]
Sv. allmän spottstrit /dyntaxa https://sv.wikipedia.org/wiki/Allm%C3%A4n_spottstrit
