### ISSUE TITLE
steiner education

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9094]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

steiner education 

#### Ehdotettu termi englanniksi   

steiner education 

#### Perustelut ehdotukselle   

YSO:n Waldorf education ei ole samassa linjassa ruotsinkielisen vastineen kanssa: Steinerpedagogik. Steiner education -termiä on käytetty esimerkiksi seuraavassa teoksessa: Stehlik, T. (2019) Waldorf schools and the history of Steiner education : an international view of 100 years . Cham, Switzerland: Palgrave Macmillan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [steiner education](http://finto.fi/yse/fi/page/Y509094)

**Comment by jtuohini** [comment]
Mitä tällä ehdotuksella varsinaisesti tarkoitetaan?
 
YSO-asiasana [**steinerpedagogiikka**](http://www.yso.fi/onto/yso/p1897) on linkitetty täysin oikein LCSH-asiasanaan [**Waldorf method of education**](http://id.loc.gov/authorities/subjects/sh85144872), jonka KT-muodot ovat _Steiner education_, _Steiner-Waldorf education_ ja _Waldorf education_. Svenska ämnesordissa vastaava siltaus on asiasanasta [**Waldorfpedagogik**](https://id.kb.se/term/sao/Waldorfpedagogik), jonka KT-muoto on _Steinerpedagogik_.
 
Halutaanko siis kyseisen YSO-asiasanan ruotsinkielinen muoto nykyisestä samaksi kuin SAO:n asiasana?

**Comment by mirmaid** [comment]
Ehdotus varmaankin koskee englanninkielistä muotoa, joka on nyt _Waldorf education_ LCSH:n mukaisesti.

**Comment by mirmaid** [comment]
Lisätty ohjaustermi Steiner education, päätermi jätetty ennalleen (LCSH, Wikipedia, Google-tulosten määrä).
