### ISSUE TITLE
Jänisjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9097]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Jänisjoki](http://www.yso.fi/onto/ysa/Y109416) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Muita samannimisiä Suomessa

**Comment by mirmaid** [comment]
Tarkenteeksi siis Paikkatietoalustan mukaan Tohmajärvi, toiseksi yläkäsitteeksi Venäjä. Entä KT Jänisjoki (Joensuu)? Ei ole varsinaisesti linjattu laitetaanko näitä vesistöjen muita kuntia, mutta olen nyt jonkun verran laittanut (esim. Laakajärvi).

**Comment by mirmaid** [comment]
Lisätään tarkenne ja ohjaustermi + tarkenne.
