### ISSUE TITLE
veteraaniurheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9099]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[veteraaniurheilu](http://www.yso.fi/onto/ysa/Y109858) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ohjaustermiksi aikuisurheilu (tai uusi termi ja ohjaus toisinpäin). 

#### Perustelut ehdotukselle   

Veteraaniurheilun sijaan puhutaan usein nykyisin aikuisurheilusta ja Veteraaniurheiluliittokin on muuttanut nimekseen Suomen Aikuisurheiluliitto. 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
https://www.saul.fi/

**Comment by mariaforsen** [comment]
Sv. veteranidrott > vuxenidrott?
