### ISSUE TITLE
yhdenvertaisuuslaki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9100]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[yhdenvertaisuuslaki](http://www.yso.fi/onto/ysa/Y146873) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaettava 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Yhdenvertaisuuslaki
https://www.finlex.fi/fi/laki/alkup/2014/20141325 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Eli olisiko:
Yhdenvertaisuuslaki (1912)
Yhdenvertaisuuslaki (2014)

**Comment by YSO-kokous** [comment]
Hyväksytty  jako Yhdenvertaisuuslaki (1912), Yhdenvertaisuuslaki (2014)

**Comment by mariaforsen** [comment]
Sv.
-likställighetslag (1912) https://fho.sls.fi/uppslagsord/12590/likstallighetslag/
-diskrimineringslag (2014)
