### ISSUE TITLE
miniatyyrit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9101]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[miniatyyrit](http://www.yso.fi/onto/ysa/Y102502) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

muutetaan käytettäväksi termiksi minaityyrimaalaukset 

#### Perustelut ehdotukselle   

tämän käsitteen yläkäsite on maalaukset. miniatyyrit voi viitata muihinkin pienikokoisiin esineisiin - https://fi.wikipedia.org/wiki/Miniatyyri. 
miniatyyrit voisi olla tämän ja miniatyyrikirjat käsitteiden ohjausterminä
https://www.wikidata.org/wiki/Q282129 miniatyyrimaalaus
https://fi.wikipedia.org/wiki/Miniatyyrimaalaus 

#### Ehdottajan organisaatio   

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
käsitelty aiemmin: https://github.com/Finto-ehdotus/YSE/issues/7701
 

> YSO-kokous commented on 26 Aug 2020
> 
> Jätetään miniatyyrit nykyiseen muotoonsa. Muutetaan sen hierarkiaa niin että kattaa muutakin kuin maalaukset.
