### ISSUE TITLE
Ala-Jalve (Utsjoki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9103]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Ala-Jalve (Utsjoki) 

#### Ehdotettu termi ruotsiksi   

Ala-Jalve (Utsjoki) 

#### Ehdotettu termi englanniksi   

Ala-Jalve (Utsjoki) 

#### Vaihtoehtoiset termit ja ilmaisut   

Vuollejalvi (Utsjoki) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh89006407> 
MML : <http://paikkatiedot.fi/so/1000772/10824076> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Tarkoitusta täsmentävä selite   

Maanmittauslaitoksen paikannimirekisteri; tyyppitieto: Talo.
Esihistoriallinen asuinpaikka. 

#### Perustelut ehdotukselle   

Käsite löytyy LCSH-sanastosta, ainoana paikkana Utsjoelta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kokemuksia yhteysdokumentoinnista Utsjoen Ala-Jalvessa. Tuija Rankama,.Muinaistutkija 2/2000, sivut 39-45. https://finna.fi/Record/jykdok.71814, https://www.kyppi.fi/to.aspx?id=112.890010001, https://www.kyppi.fi/to.aspx?id=108.999000274 

**Ehdottajan organisaatio:** Kansalliskirjasto/Finto **Termiehdotus Fintossa:** [Ala-Jalve (Utsjoki)](http://finto.fi/yse/fi/page/Y509103)

**Comment by mirmaid** [comment]
Ei Alastarolla Ylistarossa -kirjassa.

**Comment by mirmaid** [comment]
Tehdään kuten Levänluhta, ei linkkiä taloon.
