### ISSUE TITLE
taidemusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9104]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taidemusiikki](http://www.yso.fi/onto/ysa/Y99237) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-sanasto. Muutos hierarkiassa, alla olevien termien yläkäsitteeksi "musiikin" sijasta "taidemusiikki":

aariat
adagiot
airit
aleatorinen musiikki
alkusoitot
allemandet
anthemit
antifonit
arabeskit (musiikki)
ariosot
bagatellit
barkarolit
berceuset
capricciot
chaconnet
elektroakustinen musiikki
etydit
fantasiat
fuugat
humoreskit
imromptut
intermezzot (soitinmusiikki)
inventiot
kaanonit
kadenssit
kamarimusiikki
kantaatit
konsertot
koraalialkusoitot
lamentot
laulusarjat
magnificatit
melodraamat (musiikki)
mikrotonaalinen musiikki
motetit
muunnelmat (musiikki)
nocturnet
ohjelmamusiikki
oodit (musiikki)
oratoriot
orkesterilaulut
orkesterimusiikki
passacagliat
passiot
pastoraalimusiikki
Peking-ooppera
postludit
preludit
rāgat
rapsodiat
resitatiivit
ricercaret
rondot
sarjallinen musiikki
sarjat
scherzot
sinfonia concertantet
sinfoniat
sinfoniettat 
sinfoniset runot
sonaatit
sonatiinit
spektrimusiikki
tertsetot
toccatat
tomebeaut 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto 

#### Perustelut ehdotukselle   

SLM-sanaston hierarkian kehittäminen.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Muusa voisi tarpeen mukaan päivittää määritelmää: _Taidemusiikki käsitteenä viittaa erityisesti 1800-luvulla syntyneeseen jaotteluun vakavan taidemusiikin ja kansanomaisen kansan- ja populaarimusiikin välillä, mutta taidemusiikiksi voidaan sanoa myös vanhaa kirkko- ja hovimusiikkia, jotka taidemusiikista eroavista funktioistaan huolimatta nähdään saman perinteen jatkumona. Taidemusiikkia yhdistävät yleensä institutionaalinen olemus, perinteisiin nojautuvat käytännöt sekä tietyt esteettiset piirteet._

**Comment by mirmaid** [comment]
Hyväksytään Muusan hierarkiaehdotus.

**Comment by mirmaid** [comment]
Kaanonit? Muunnelmat rajatuu näin? - Ok

**Comment by mirmaid** [comment]
Kamarimusiikki, ohjelmamusiikki, orkesterimusiikki nyt YK soitinmusiikki, tuplahierarkia? Laulusarjat nyt YK laulut. - Ok

**Comment by mirmaid** [comment]
Lamentot, spektrimusiikki ei ole SLM:ssä.

**Comment by MUUSA-kokous** [comment]
Määritelmäehdotus: Klassinen musiikki ja hovimusiikki kulttuureissa, joissa tehdään ero taidemusiikin ja kansanmusiikin välillä.

**Comment by YSO-kokous** [comment]
Määritelmä ollut olemassa vanhastaan. Kattaa muutkin kuin länsimaiset kulttuurit. Populaarimusiikki on vielä näistä erillinen ryhmä, joka ei ole kumpaakaan määritelmässä mainituista. Ehdotetaan Muusalle, että määritelmän loppuosa muokattaisiin muotoon "... taidemusiikin ja muun musiikin välillä."

**Comment by MUUSA-kokous** [comment]
Kannatetaan määritelmän loppusosan muokkaamista.
