### ISSUE TITLE
syväoppiminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9105]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

syväoppiminen 

#### Ehdotettu termi englanniksi   

deep learning 

#### Ehdotettu termi ruotsiksi   

djupinlärning 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Syv%C3%A4oppiminen 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://aaltodoc.aalto.fi/handle/123456789/101686 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa, paljon käytetty koneoppimista käsittelevän aineiston yhteydessä 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [syväoppiminen](http://finto.fi/yse/fi/page/Y509105)

**Comment by mirmaid** [comment]
19 kertaa Melindassa.

http://www.yso.fi/onto/mesh/D000077321

**Comment by mariaforsen** [comment]
Sv. djupinlärning /avh. ET deep learning /mesh, djuplärning
https://sv.wikipedia.org/wiki/Djupinl%C3%A4rning
