### ISSUE TITLE
beetasalpaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9106]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

beetasalpaajat 

#### Ehdotettu termi ruotsiksi   

adrenerga betablockerare 

#### Ehdotettu termi englanniksi   

adrenergic beta-antagonists 

#### Vaihtoehtoiset termit ja ilmaisut   

betasalpaajat 
adrenergic beta blockers 
betablockerare 

#### Ehdotettu yläkäsite YSOssa (LT)   

[lääkkeet](http://www.yso.fi/onto/yso/p1077) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D000319> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85001009> 
Wikipedia : https://fi.wikipedia.org/wiki/Beetasalpaajat 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 46 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Therapeutic factors contributing to the long-term survival of acute coronary syndrome patients 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [beetasalpaajat](http://finto.fi/yse/fi/page/Y509106)

**Comment by mariaforsen** [comment]
Sv. betablockerare https://sv.wikipedia.org/wiki/Betablockerare https://svenska.se/tre/?sok=betablockerare&pz=1 ET betareceptorblockerare /ne, adrenerga betablockerare /mesh, β-blockerare
