### ISSUE TITLE
suonikalvoston tulehdus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9107]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suonikalvoston tulehdus 

#### Ehdotettu termi englanniksi   

uveitis 

#### Ehdotettu termi ruotsiksi   

druvhinneinflammation 

#### Vaihtoehtoiset termit ja ilmaisut   

uveiitti 

#### Ehdotettu yläkäsite YSOssa (LT)   

[silmätaudit](http://www.yso.fi/onto/yso/p12047) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85141648> 
FinMeSH : <http://www.yso.fi/onto/mesh/D014605> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Treatment and complications of juvenile idiopathic arthritis-related uveitis 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suonikalvoston tulehdus](http://finto.fi/yse/fi/page/Y509107)

**Comment by mariaforsen** [comment]
Sv. druvhinneinflammation ET uveit
