### ISSUE TITLE
piilotyöpaikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9108]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

piilotyöpaikat 

#### Ehdotettu termi englanniksi   

hidden jobs 

#### Ehdotettu yläkäsite YSOssa (LT)   

[työpaikat](http://www.yso.fi/onto/yso/p13463) 

#### Alakäsitteet (RT)   

[työnhaku](http://www.yso.fi/onto/yso/p9860) 

#### Vastaava käsite muussa sanastossa   

https://uraohjauksen-sanakirja.purot.net/piilotyopaikka 

#### Perustelut ehdotukselle   

Yleinen käsite työnhakua ohjattaessa ja koulutuksissa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

opinnäyte 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525) 

**Termiehdotus Fintossa:** [piilotyöpaikat](http://finto.fi/yse/fi/page/Y509108)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. dolda jobb ET dolda arbetsplatser

**Comment by LeKorsu** [comment]
Onko vielä vähän epämääräinen asia, jättäisin toistaiseksi termiehdotukseksi.
