### ISSUE TITLE
tanssimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9109]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssimusiikki](http://www.yso.fi/onto/ysa/Y99308) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-sanasto. 
Muutos hierarkiassa, alla olevien termien yläkäsitteeksi "musiikin" sijasta "tanssimusiikki":
allemandet
beguinet
bolerot
cancanit
cha-cha-chat
fandangot
foxtrotit
gavotit
hambot
humpat
häävalssit
kontratanssit
lambadat
mambot
masurkat
menuetit
pasodoblet
passepied't
pavanat
polkat
poloneesit
polkat
rumbat
sambat
tangot
tarantellat 
twistit
valssit
wieninvalssit

"Tanssimusiikki" yläkäsitteeksi assosiatiivisen sijasta termeille:
giguet
sarabandet 

#### Perustelut ehdotukselle   

SLM-hierarkian kehittäminen. 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytään ehdotettu muutos, paitsi wieninvalssit YK valssit.

**Comment by mirmaid** [comment]
Myös häävalssit YK valssit, kuten YSOssa? Listalla polkat kaksi kertaa, toinen lienee polskat?

Onko allemandet YK sekä tanssimusiikki että taidemusiikki?

**Comment by mirmaid** [comment]
^ Ok. Häävalssit myös LT häämusiikki.
