### ISSUE TITLE
endoskooppinen retrogradinen kolangiopankreatografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9110]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

endoskooppinen retrogradinen kolangiopankreatografia 

#### Ehdotettu termi englanniksi   

endoscopic retrograde cholangiopancreatography 

#### Vaihtoehtoiset termit ja ilmaisut   

ERCP 

#### Ehdotettu yläkäsite YSOssa (LT)   

[endoskopia](http://www.yso.fi/onto/yso/p1036) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D002760> 
LCSH : <http://id.loc.gov/authorities/subjects/sh89001955> 
Wikipedia : https://fi.wikipedia.org/wiki/Endoskooppinen_retrogradinen_kolangiopankreatikografia 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Risk factors associated to endoscopic retrograde cholangiopancreatography related complications 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [endoskooppinen retrogradinen kolangiopankreatografia](http://finto.fi/yse/fi/page/Y509110)

**Comment by mariaforsen** [comment]
Sv. endoskopisk retrograd kolangiopankreatografi ET ERCP
https://finto.fi/mesh/sv/page/D002760
