### ISSUE TITLE
uskonnollinen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9111]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uskonnollinen musiikki](http://www.yso.fi/onto/ysa/Y199056) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM-sanasto. Lisätään termi myös SLM-sanastoon. 

#### Ehdottajan organisaatio   

Taideyliopiston kirjasto 

#### Perustelut ehdotukselle   

Tarvitaan myös SLM-sanastossa.

**Comment by jtuohini** [comment]
LCGFT-siltaus: [**Sacred music**](http://id.loc.gov/authorities/genreForms/gf2014027062).

**Comment by mirmaid** [comment]
Hyväksytään/SLM.

**Comment by mirmaid** [comment]
Miten SLM:ssä hierarkia uskonnolliset laulut, hengelliset laulut / uskonnollinen/hengellinen musiikki?

**Comment by mirmaid** [comment]
Uskonnolliset laulut LT uskonnollinen musiikki & laulut.
Hengelliset laulut LT uskonnolliset laulut & hengellinen musiikki.
