### ISSUE TITLE
konekääntäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9113]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

konekääntäminen 

#### Ehdotettu termi englanniksi   

machine translation 

#### Ehdotettu termi ruotsiksi   

maskinöversättning 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://aaltodoc.aalto.fi/handle/123456789/97333 

#### Perustelut ehdotukselle   

Vakiintunut käsite ja ala jota tutkitaan paljon. Sanastossa oleva termi "tietokoneavusteinen kääntäminen" ei sovellu 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [konekääntäminen](http://finto.fi/yse/fi/page/Y509113)

**Comment by mirmaid** [comment]
11 viitettä Melindassa.

**Comment by ilona-x** [comment]
LCSH: Machine translating  http://id.loc.gov/authorities/subjects/sh85079361

**Comment by ilona-x** [comment]
Ehdotuksessa mainitun tietokoneavusteisen kääntämisen ohjaustermi "automaattinen kielenkääntäminen" pitäisi varmaan ohjata konekääntämiseen, jos tämä  ehdotus hyväksytään.

YSO:
**tietokoneavusteinen kääntäminen** http://www.yso.fi/onto/yso/p6070
KT    automaattinen kielenkääntäminen
KT    käännösteknologia

_

tietokoneavusteinen kääntäminen käytetty Melindassa 432 kertaa

**Comment by YSO-kokous** [comment]
Hyväksytään konekääntäminen KT automaattinen kielenkääntäminen

**Comment by mariaforsen** [comment]
Sv. maskinöversättning https://id.kb.se/term/sao/Maskin%C3%B6vers%C3%A4ttning ET maskinell översättning, datoröversättning, automatisk översättning
