### ISSUE TITLE
tuohi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9115]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tuohi](http://www.yso.fi/onto/ysa/Y156865) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään "tuohi"-käsite "puunkuori"-käsitteen (http://www.yso.fi/onto/yso/p24500) alakäsitteeksi. Poistetaan (tai siirretään jonnekin) samalla "tuohi"-käsitteen nykyinen yläkäsite "kuori". 

#### Perustelut ehdotukselle   

Tuohi on ensisijaisesti yksi puunkuoren tyyppi (kuten kaarna, jonka voisi samalla lisätä "puunkuori"-käsitteen alakäsiteeksi, sen sijaan että on ohjausterminä puunkuorelle).

"Fyysiset objektit"-käsitteen alakäsitteenä on nyt "aine", "elottomat objektit", "kuori" ja "orgaaniset objektit" käsitteiden kanssa, ja "kuori" ei tunnu olevan verrannollinen muihin tason käsitteisiin, joten se olisi hyvä poistaa (tai siirtää). 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Ryhmä ei kannattanut _kuori_-käsitteen poistoa: https://github.com/Finto-ehdotus/YSE/issues/6685. _Tuohi_ on varmaan hyvä siirtää, mutta _kuori_-käsitteelle paremman paikan löytäminen on vaikeampaa, koska kuori voi olla eloton tai orgaaninen.
