### ISSUE TITLE
koulukalusteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9117]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koulukalusteet 

#### Ehdotettu termi ruotsiksi   

skolmöbler 

#### Ehdotettu termi englanniksi   

school furniture 

#### Vaihtoehtoiset termit ja ilmaisut   

koulukaluste 
skolmöbel 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kalusteet](http://www.yso.fi/onto/yso/p13261) 

#### Vastaava käsite muussa sanastossa   

lcsh : <http://id.loc.gov/authorities/subjects/sh85118459> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568) 
[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Feedback from vocab: KOKO
Ehdotan, että KOKOon tulisi sana Koulukalusteet, jolla voisi hakea pulpetteja, kaappeja, opettajanpöytiä, karttatelineitä jne museokokoelmasta. Käyttötarkoitus olisi esineluettelointi /haku Finnasta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esineluettelointi 

**Ehdottajan organisaatio:** museo /Finto-asiakaspalaute [KK-02602056] **Termiehdotus Fintossa:** [koulukalusteet](http://finto.fi/yse/fi/page/Y509117)

**Comment by mirmaid** [comment]
Kerran Melindassa. _Koulut & kalusteet_ 41 kertaa. Sanastossa on _myymäläkalusteet_ ja _toimistokalusteet_.
