### ISSUE TITLE
SLM goottilaiset kauhuromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9118]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM goottilaiset kauhuromaanit 

#### Perustelut ehdotukselle   

Tämä oli joskus omana genrenään sanastossa, minusta pitäisi saada takaisin kauhukirjallisuuden alagenreksi, koska tämä ei liity pelkästään historiaan vaan tiettyyn kauhukirjallisuuden tyyliin ja edelleen käyttökelpoinen termi niin aikuisten kuin nuortenkin aineistossa. Wikipedian määritelmä: Goottilainen romaani[1] (engl. Gothic fiction) eli kauhuromantiikka[2] on kauhukirjallisuuden lajityyppi, jonka toistuvia piirteitä ovat väkivalta, salaisuudet, keskiaikaiset rauniot sekä yliluonnolliset elementit. Tyypillinen goottilainen romaani sijoittuu pelottavaan linnaan, jossa rappeutuneen suvun viimeinen vesa joutuu tekemään tiliä esi-isiensä syntien kanssa. Usein menneisyyden taakka konkretisoituu kohtalonomaisena kostona, joka toteutuu kummitusten, demonien ja muiden yliluonnollisten voimien myötävaikutuksella.

Goottilainen romaani kehittyi Englannissa 1700-luvun jälkipuoliskolla ja oli suosituimmillaan 1700–1800-lukujen vaihteen molemmin puolin. Genren perusteokseksi muodostui Horace Walpolen Otranton linna (1765). Lajityypin suosio laski 1800-luvun mittaan, ja sen kummallisia juonenkäänteitä myös parodioitiin usein. Vaikutteita gotiikasta esiintyi kuitenkin laajalti vuosisadan kirjallisuudessa, tunnetuimpina esimerkkeinä Mary Shelleyn Frankenstein (1818) ja Bram Stokerin Dracula (1897). Myös modernissa kauhukirjallisuudessa goottilaisen romaanin perintö elää vahvana, vaikka lajityypin puhdasveriset edustajat ovatkin nykyään suhteellisen harvinaisia.

Vaikka goottilainen romaani oli ennen muuta englanninkielisen kirjallisuuden suuntaus, kehittyi vastaavia yliluonnollisen kauhun traditioita myös Manner-Euroopassa. Saksassa puhuttiin ”puistatusromaaneista” ja Ranskassa ”mustista romaaneista”. Yhdysvalloissa kehittyi ”etelägotiikaksi” kutsuttu suuntaus, jonka aiheita olivat syvän etelän rappeutuneet plantaasit ja orjuuden synnyttämät etniset konfliktit.

Goottilainen romaani uudisti 1700-luvun kirjallisuutta kolmella tapaa. Ensinnäkin se vastusti valistusajan edistysuskoa ja nostalgisoi mennyttä. Toisekseen se oli antiteesi esteettisille ja moraalisille ihanteille: kauneuden sijaan gotiikka pyrki rumuuteen ja pelottavuuteen. Kolmanneksi gotiikka kuvasi aiempaa rohkeammin vaiettuja ilmiöitä, kuten väkivaltaa, hulluutta ja seksuaalisuutta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Jukka Laajarinne Hurmeen maku esim. 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [SLM goottilaiset kauhuromaanit](http://finto.fi/yse/fi/page/Y509118)

**Comment by mirmaid** [comment]
YSOssa on _goottilaiset romaanit_.

**Comment by mirmaid** [comment]
Goottilaiset romaanit KT goottilaiset kauhuromaanit

**Comment by mirmaid** [comment]
LCGFT-linkitys, broader Match.

**Comment by mirmaid** [comment]
Tehdään broad match http://id.loc.gov/authorities/genreForms/gf2014026360
