### ISSUE TITLE
mitokondriotaudit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9119]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mitokondriotaudit](http://www.yso.fi/onto/ysa/Y152639) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

ST GRACILE-oireyhtymä http://www.yso.fi/onto/yso/p38763 

#### Perustelut ehdotukselle   

https://neuroliitto.fi/tieto-tuki/tietoa-sairauksista/harvinaiset-neurologiset-sairaudet/diagnoosit/mitokondrio/
https://www.duodecimlehti.fi/duo15991
https://www.duodecimlehti.fi/duo10420 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
tämä ehdotus koskee siis oikeastaan tuota GRACILE-oireyhtymää, mutta siihen kohdistuvan muutosehdotuksen tekeminen ei onnistunut
