### ISSUE TITLE
HLA

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9120]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

HLA 

#### Ehdotettu termi ruotsiksi   

HLA 

#### Ehdotettu termi englanniksi   

HLA 

#### Vaihtoehtoiset termit ja ilmaisut   

Human leukocyte antigen 
HL-antigeenit 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q911125 
FinMeSH : https://finto.fi/mesh/fi/page/D006680 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/314110 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [HLA](http://finto.fi/yse/fi/page/Y509120)

**Comment by mirmaid** [comment]
Lääketieteen termit: HL-antigeeni: (lyh. HLA) HLA-proteiini | solujen pinnassa olevia proteiineja, joiden perusteella T-solut tunnistavat elimistön omia rakenteita

**Comment by mirmaid** [comment]
18 kertaa Melindassa tässä muodossa, 4 kertaa HL-antigeenit.

**Comment by mariaforsen** [comment]
Sv. HLA-antigener https://finto.fi/mesh/fi/page/D006680?clang=sv ET HLA

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteessä (immunologiassa) ihan relevantti termi.

**Comment by YSO-kokous** [comment]
hyväksytään HLA-antigeenit KT HLA
