### ISSUE TITLE
kimalaiskolibri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9121]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kimalaiskolibri 

#### Ehdotettu termi englanniksi   

bee hummingbird 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kolibrit](http://www.yso.fi/onto/yso/p17487) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Perustelut ehdotukselle   

lintulaji, tarvitaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

artikkeli 

**Termiehdotus Fintossa:** [kimalaiskolibri](http://finto.fi/yse/fi/page/Y509121)

**Comment by jarmosaarikko** [comment]
kimalaiskolibri –  bikolibri{@sv}   - KT "Mellisuga helenae"
http://tun.fi/MX.29758,  https://www.wikidata.org/wiki/Q213036 
YK kolibrit http://www.yso.fi/onto/yso/p17487

**Comment by mariaforsen** [comment]
Sv. bikolibri ET helenakolibri
