### ISSUE TITLE
Haapakangas

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9124]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Haapakangas](http://www.yso.fi/onto/ysa/Y176825) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan 

#### Perustelut ehdotukselle   

Samannimisiä myös Suomessa

**Comment by mirmaid** [comment]
Haapakangas (Inkeri)?

**Comment by ilona-x** [comment]
Huomautus nyt: "Historiallinen ja nykyinen seurakunta Pohjois-Inkerissä sekä myös taajama Pietarista Viipuriin vievän valtatien varrella"
Pitäisikö näistä valita yksi merkitys seurakunta vai taajama? Ja jos kyseessä seurakunta, niin pitäisikö olla samoin kuin Inkere (seurakunta) eli Haapakangas (seurakunta)?

**Comment by mirmaid** [comment]
Haapakangas (Inkeri), tutkitaan vielä Inkere. Hietamäen huomautus?
