### ISSUE TITLE
kvanttiväridynamiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9126]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

quantum chromodynamics 

#### Ehdotettu termi suomeksi   

kvanttiväridynamiikka 

#### Ehdotettu termi ruotsiksi   

kvantkromodynamik 

#### Vaihtoehtoiset termit ja ilmaisut   

kvanttikromodynamiikka 
QCD 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85109458> 
Wikipedia : https://fi.wikipedia.org/wiki/Kvanttiv%C3%A4ridynamiikka 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 12 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

From QCD to neutron stars and back : probing the fundamental properties of dense matter / 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kvanttiväridynamiikka](http://finto.fi/yse/fi/page/Y509126)

**Comment by mariaforsen** [comment]
Sv. kvantkromodynamik ET QCD https://id.kb.se/term/sao/Kvantkromodynamik
