### ISSUE TITLE
Kahva

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9128]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kahva 

#### Perustelut ehdotukselle   

Usein museoalalla tarvittava sana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esineluettelointi 

**Termiehdotus Fintossa:** [Kahva](http://finto.fi/yse/fi/page/Y509128)

**Comment by mirmaid** [comment]
18 kertaa Melindassa, on MAOssa.

**Comment by mariaforsen** [comment]
Sv. handtag ET skaft (handtag)
