### ISSUE TITLE
galaktoglukomannaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9129]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

galactoglucomannans 

#### Ehdotettu termi suomeksi   

galaktoglukomannaanit 

#### Vaihtoehtoiset termit ja ilmaisut   

GGM 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mannaanit](http://www.yso.fi/onto/yso/p23996) 

#### Assosiatiiviset (RT)   

[hemiselluloosa](http://www.yso.fi/onto/yso/p28368) 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Galactoglucomannan 
LCSH : <http://id.loc.gov/authorities/subjects/sh2009001145> 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 7 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Associative behavior of spruce galactoglucomannans in aqueous solutions and emulsions 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [galaktoglukomannaanit](http://finto.fi/yse/fi/page/Y509129)

**Comment by mariaforsen** [comment]
Sv. galaktoglukomannaner  ET GGM /abo.fi
