### ISSUE TITLE
levinneisyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9130]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[levinneisyys](http://www.yso.fi/onto/ysa/Y103112) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi ohjaustermi: levinneisyysalue 

#### Perustelut ehdotukselle   

Tarkoittaa yleensä sama asia, levinneisyys = kuinka laajalla alueella laji esiintyy

**Comment by YSO-kokous** [comment]
hyväksytään
