### ISSUE TITLE
Kylpykirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9132]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kylpykirjat 

#### Ehdotettu termi englanniksi   

bath books 

#### Vastaava käsite muussa sanastossa   

Bath books : https://id.loc.gov/authorities/genreForms/gf2019026144.html 

#### Tarkoitusta täsmentävä selite   

SLM-ehdotus 

#### Perustelut ehdotukselle   

Kumea on uudistamassa tietueiden sidosasumerkintöjä ja tarve nousi asiaa valmistelevalta työryhmältä. Nykyisin kylpykirjat merkitään huomautuksena 500-kenttään, mutta mieluummin käytettäisiin auktorisoitua sanastoa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://kansalliskirjasto.finna.fi/Record/fikka.4303002 

**Ehdottajan organisaatio:** KK/SN **Termiehdotus Fintossa:** [Kylpykirjat](http://finto.fi/yse/fi/page/Y509132)

**Comment by mirmaid** [comment]
Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. badböcker
