### ISSUE TITLE
Elsass

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9133]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Elsass](http://www.yso.fi/onto/ysa/Y169021) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

yhdistetään käsitteeseen Alsace 

#### Perustelut ehdotukselle   

käytännössä sama alue, mutta vain eri aikoina.  Wikipediassa ja Wikidatassa sama käsite https://www.wikidata.org/wiki/Q1142 https://fi.wikipedia.org/wiki/Alsace
Eri käsite kuin https://fi.wikipedia.org/wiki/Elsass-Lothringen (Alsace-Moselle/Alsace-Lorraine) 

#### Ehdottajan organisaatio   

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Yhdistetään?

**Comment by ilona-x** [comment]
SAO: Frankrike--Alsace KT Elsass  https://id.kb.se/term/sao/Frankrike--Alsace

**Comment by mirmaid** [comment]
Alsace KT Elsass
