### ISSUE TITLE
katsomuskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9134]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

katsomuskasvatus 

#### Ehdotettu termi ruotsiksi   

åskådningsfostran 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Lapsenkokoinen katsomuskasvatus (9789523543782) 

**Ehdottajan organisaatio:** Suomen kirjastopalvelu Oy **Termiehdotus Fintossa:** [katsomuskasvatus](http://finto.fi/yse/fi/page/Y509134)

**Comment by mirmaid** [comment]
Kaksi viitettä Melindassa (esiopetuksen oppikirja). Sanastossa on _katsomusaineet, elämänkatsomus, elämänkatsomustieto, uskontokasvatus_.

**Comment by ilona-x** [comment]
https://evl.fi/sanasto/-/glossary/word/Varhaiskasvatuksen+katsomuskasvatus

**Comment by YSO-kokous** [comment]
katsomuskasvatus RT katsomusaineet, elämänkatsomus, elämänkatsomustieto,
