### ISSUE TITLE
harpit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9135]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

harpit 

#### Tarkoitusta täsmentävä selite   

mittausväline 

#### Perustelut ehdotukselle   

Museotyössä tarvittava termi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esineluettelointi 

**Termiehdotus Fintossa:** [harpit](http://finto.fi/yse/fi/page/Y509135)

**Comment by mariaforsen** [comment]
Sv. passare (verktyg) ET cirkelpassare
https://svenska.se/tre/?sok=passare&pz=1
