### ISSUE TITLE
ruiskut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9137]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ruiskut 

#### Perustelut ehdotukselle   

Museotyössä tarvittava sana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esineluettelointi 

**Termiehdotus Fintossa:** [ruiskut](http://finto.fi/yse/fi/page/Y509137)

**Comment by mirmaid** [comment]
29 kertaa Melindassa. AFOssa, TEROssa ja MeSHissä, Melindan viitteet maalausta ja kasvinsuojelua.

**Comment by mariaforsen** [comment]
Sv. sprutor

**Comment by LeKorsu** [comment]
Tarkoittaisiko tämä nimenomaan injektioruiskua (eng syringe)? Paloruiskulle kävisi varmaan ohjaustermiksi KÄ letkut. Mutta entä maaliruiskut?
