### ISSUE TITLE
pihdit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9140]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pihdit 

#### Perustelut ehdotukselle   

Esineluetteloinnissa tarpeellinen ja yleinen sana 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Esineluettelointi 

**Termiehdotus Fintossa:** [pihdit](http://finto.fi/yse/fi/page/Y509140)

**Comment by mirmaid** [comment]
14 viitettä Melindassa. On MAOssa (ja HEROssa), LIIKOssa puolestaan on _pihdit (kuormauslaitteet)_. https://www.cascorp.com/eme/fi/forkclamps

**Comment by mariaforsen** [comment]
Sv. tänger https://id.kb.se/term/sao/T%C3%A4nger
