### ISSUE TITLE
ennakkotiedot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9141]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ennakkotiedot](http://www.yso.fi/onto/ysa/Y172861) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennetaan/jaetaan/poistetaan 

#### Perustelut ehdotukselle   

Monimerkityksinen termi, käytetty Melindassa 15 kertaa ja vaihtelevissa merkityksissä. 
Sv. tähän asti förhandsuppgifter (yleismerkitys). Muita mahdollisia käännöksiä esim. förhandskunskaper, förhandsinformation, förhandsbesked (verotus)

EKS: ennakkotieto	
Korvaa termin:	ennakkotieto verotuksessa, Keskusverolautakunnan ennakkoratkaisu
Asiasana ruotsiksi:	förhandsbesked
Asiasana englanniksi:	advance ruling

https://termipankki.fi/tepa/fi/haku/ennakkotiedot 

VALTER:
fi ennakkotieto
Ks. myös: ennakkopäätös, ennakkoratkaisu
sv förhandsbesked
Lisätieto: När det är fråga om ett (bindande) besked från t.ex. enmyndighet om ett kommande beslut i ett enskilt fall, förhandsinformation iallmännare sammanhang.

Ks. myös Verosanasto

**Comment by mariaforsen** [comment]
VALTER:

fi ennakkotieto
Ks. myös: ennakkopäätös, ennakkoratkaisu 
sv förhandsbesked
Lisätieto: När det är fråga om ett (bindande) besked från t.ex. enmyndighet om ett kommande beslut i ett enskilt fall, förhandsinformation iallmännare sammanhang.

**Comment by jarmosaarikko** [comment]
Huom. **ennakkotiedot** käsite on lainsäädännössä myös muualla kuin verotuspäätösten yhteydessä.  esimerkiksi kaupassa ja luottosopimuksia tehtäessä: kts. 
- **kuluttajansuojalaki** https://finlex.fi/fi/laki/ajantasa/1978/19780038 
esim. 7. luku 28 § Kuluttajalle annettavat ennakkotiedot, 10. luku 4 § Ennakkotiedot, jne. eli se on yleisempi käsite. 

Käännösesimerkkejä säädöksistä: 
- arvonlisäverolaki 150/1993  237 § ennakkotieto - "advance ruling", mutta 190 § ja Luku 20: ennakkoratkaisu - "advance ruling" eli sama käännös molemmille (sic!)
- kuluttajansuojalaki 6a. luku 5§   ennakkotiedot - "prior information"
- ydinenergialaki 990/1987 3. luku 8 §  sitova ennakkotieto - "binding advance ruling"
- ydinenergialaki 990/1987 82 § ennakkotieto - "preliminary information"
- ydinenergia-asetus 161/1988 19. luku 142 § ennakkotieto - "advance ruling"

Säädöksien käännöksissä on käytetty termejä sekavasti ristiin ja eri tavalla kuin Valterissa. 
### Ehdotukseni:
fi: **ennakkoratkaisut** 
sv: förhandsavgöranden
en: advance rulings  KT preliminary rulings

fi: **ennakkotiedot (verotus)** 
sv: förhandsbesked (beskattning)
en: preliminary decisions  (taxation)

fi: **ennakkotiedot**
sv: förhandsbesked
en: preliminary information KT prior information, advance information

### YSOssa on jo ennestään
fi: **ennakkopäätökset (prejudikaatit)**
sv: prejudikat
en: advance rulings  KT precedents (law)

- ehdotan, että tämän käännösvastine muutetaan KÄ precedents (law), ja käytettävä termi "advance rulings"  siirretään "ennakkoratkaisut" käsitteelle.

fi: **ennakkoratkaisut (EU-oikeus)**
sv: förhandsavgöranden (EU-rätt)
en: preliminary rulings (EU law)

- Ehdotan, että lisätään tarkenne käänösvastineeseen. Tulisiko se muuttaa muotoon "advance rulings (EU law) KT preliminary rulings (EU law)" jotta olisi yhteneväinen toisen ennakkoratkaisut -käsitteen kanssa?

**Comment by mirmaid** [comment]
^ Ei siis voi olla niin, että sanastossa olisi sama termi sulkutarkenteella ja ilman.

**Comment by ilona-x** [comment]
JUPO:

**ennakkotiedot (kuluttajansuoja)**  http://www.yso.fi/onto/jupo/p5538

MÄÄRITELMÄ
tieto, jonka elinkeinonharjoittaja antaa kuluttajalle ennen sopimuksen tekemistä

HUOMAUTUS
Kuluttajansuojalaissa on lueteltu ennakkotiedot, jotka etämyynnissä ja kotimyynnissä on annettava kuluttajalle tai asetettava kuluttajan saataville.



**ennakkotieto (verotus)**  http://www.yso.fi/onto/jupo/p4818

HUOMAUTUS
veroviraston ennalta antama kannanotto siihen, miten se tulee verotusta toimittaessaan ratkaisemaan verovelvollisen hakemuksessaan tarkoittaman tulo- tai varallisuusverotusta koskevan asian

**Comment by mariaforsen** [comment]
Tässä laissa olevalle merkitykselle https://finlex.fi/sv/laki/ajantasa/1978/19780038 sv. termi on förhandsinformation.

**Comment by mirmaid** [comment]
Melindan viitteistä suurin osa käsittelee siis henkilön aikaisempia tietoja jostakin asiasta (ja sen vaikutusta asiaan x). Kerran on käytetty termiä etukäteistieto. Esim.

_Ennakkotietoa elämyksestä : syventääkö käsiohjelma konserttielämystä?
Assessing university students’ prior knowledge : implications for theory and practice
Nature based horse riding tourism : the role of preminary information in product development_ 

Mitä näiden suhteen tehdään? Osaan sopisi pohjatiedot tai aikaisemmat tiedot, mutta jos kyse on edeltä käsin annettavasta tiedosta niin sekään ei käy, eikä ehkä muutaman viitteen korjaamisen takia kannata ottaa erikseen. Eli laitetaan vain tapauskohtaisesti jotain 653-kenttään?

**Comment by mirmaid** [comment]
Verotus: 
Sanastossa on nyt _ennakkoratkaisut (verotus)_: sitova ratkaisu, jonka toimivaltainen viranomainen antaa hakemuksesta ennen veron määräämistä tai suorittamista hakijan tai lain tulkinnan kannalta tärkeästä asiasta. Eri verolajeissa toimivaltaisia viranomaisia ovat keskusverolautakunta, verovirasto, Tullihallitus ja Ajoneuvohallintokeskus. Ennakkoratkaisuun voi hakea muutosta (vrt. ennakkotieto).

Sanastosta puuttuu _ennakkotiedot (verotus)_: veroviraston ennalta antama kannanotto siihen, miten se tulee verotusta toimittaessaan ratkaisemaan verovelvollisen hakemuksessaan tarkoittaman tulo- tai varallisuusverotusta koskevan asian. Ennakkotieto sitoo verovirastoa, jos verovelvollinen niin vaatii. Ennakkotietoon ei voi hakea muutosta (vrt. ennakkoratkaisu).

**Comment by mirmaid** [comment]
Melindan viitteissä siis kerran käytetty _ennakkotiedot_ verotukseen liittyvässä aineistossa väärin, kun kyse olisi ollut siirtohinnoittelun ennakkosopimuksesta. Tämän tyyppisiä virheitä ei ehkä voi estää, määritelmän voi lisätä.

**Comment by YSO-kokous** [comment]
### Päätökset
lisätään tarkenne ennakkotiedot (verotus) sekä määrtelmä

**Comment by mirmaid** [comment]
Ennakkotiedot ilmeisesti vanhentunut termi (2021 syksyllä), ei oteta sanastoon.
