### ISSUE TITLE
caprit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9142]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

caprit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[housut](http://www.yso.fi/onto/yso/p17896) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Tarkoitusta täsmentävä selite   

puolisääreen ulottuvat housut 

#### Perustelut ehdotukselle   

käsityöohjeiden kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käsityökaavojen 

**Ehdottajan organisaatio:** Lapuan kaupunginkirjasto **Termiehdotus Fintossa:** [caprit](http://finto.fi/yse/fi/page/Y509142)

**Comment by mirmaid** [comment]
Ei Melindassa. Usein myös muodossa _caprihousut_.

**Comment by mariaforsen** [comment]
Sv. capribyxor ET caprin

**Comment by YSO-kokous** [comment]
hyväksytään muodossa caprihousut KT caprit
