### ISSUE TITLE
shortsit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9143]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

shortsit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[housut](http://www.yso.fi/onto/yso/p17896) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Tarkoitusta täsmentävä selite   

lyhyet housut 

#### Perustelut ehdotukselle   

käsityöohjeiden kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käsityökaavojen 

**Ehdottajan organisaatio:** Lapuan kaupunginkirjasto **Termiehdotus Fintossa:** [shortsit](http://finto.fi/yse/fi/page/Y509143)

**Comment by mirmaid** [comment]
162 kertaa Melindassa. MAOssa muodossa _sortsit_ (kerran Melindassa). Kielitoimiston sanakirja: shortsit = sortsit.

**Comment by mariaforsen** [comment]
Sv. shorts ET kortbyxor https://sv.wikipedia.org/wiki/Kortbyxor

**Comment by YSO-kokous** [comment]
Hyväksytään shortsit KT sortsit
