### ISSUE TITLE
kylpytakit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9144]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kylpytakit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[takit](http://www.yso.fi/onto/yso/p11547) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

käsityöohjeiden kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käsityökaavojen 

**Ehdottajan organisaatio:** Lapuan kaupunginkirjasto **Termiehdotus Fintossa:** [kylpytakit](http://finto.fi/yse/fi/page/Y509144)

**Comment by mirmaid** [comment]
29 kertaa Melindassa, on MAOssa. KT saunatakit.

**Comment by mariaforsen** [comment]
Sv. badrockar ET badkappor, basturockar

**Comment by YSO-kokous** [comment]
hyväksytään.
