### ISSUE TITLE
kynsikkäät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9145]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kynsikkäät 

#### Vaihtoehtoiset termit ja ilmaisut   

käsineet 
hansikkaat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[käsineet](http://www.yso.fi/onto/yso/p12471) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527) 

#### Perustelut ehdotukselle   

käsityöohjeiden kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käsityökaavojen 

**Ehdottajan organisaatio:** Lapuan kaupunginkirjasto **Termiehdotus Fintossa:** [kynsikkäät](http://finto.fi/yse/fi/page/Y509145)

**Comment by mirmaid** [comment]
8 kertaa Melindassa. Kielitoimiston sanakirja: _puolisormikkaat_ (ei Melindassa). _Kynsikkäät_ on myös sienisuku, https://laji.fi/taxon/MX.69776. Myös muotoa _avosormikkaat_, kynsikkäät on selvästi käytetyin.

**Comment by mariaforsen** [comment]
Sv. halvvantar https://svenska.se/tre/?sok=halvvantar&pz=1

**Comment by jarmosaarikko** [comment]
ehdotus: kynsikkäät (käsineet)  YK käsineet
tai nykyisen mukaan  käsineet KT kynsikkäät (käsineet) sekä KT rukkaset. 
Muuten pitäisi kai olla myös sormelliset "sormikkaat" omana käsitteenään.
