### ISSUE TITLE
pipot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9146]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pipot 

#### Vaihtoehtoiset termit ja ilmaisut   

päähineet, lakit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[päähineet](http://www.yso.fi/onto/yso/p10458) 

#### Tarkoitusta täsmentävä selite   

yleensä joustavasta materiaalista usein kutomalla tai virkkaamalla valmistettu päänmyötäinen päähine 

#### Perustelut ehdotukselle   

käsityöohjeiden kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

käsityöohjeiden 

**Ehdottajan organisaatio:** Lapuan kaupunginkirjasto **Termiehdotus Fintossa:** [pipot](http://finto.fi/yse/fi/page/Y509146)

**Comment by mirmaid** [comment]
539 kertaa Melindassa. On MAOssa. On myös samanniminen kasvisuku https://laji.fi/taxon/MX.42239, joten vaatiiko tarkenteen? Kasvisuku on Kassussa ja MeSHissä, mutta Laji.fi mukaan ei havaintoja Suomesta.

**Comment by mariaforsen** [comment]
Ruotsiksi osittain päällekkäinen: myssyt = mössor

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**pipo** neulottu korville vedettävä (tupsullinen) päähine. 
**myssy** syvä ja päänmyötäinen lieritön ja lipaton päähine. 

Voisiko olla pipot KÄYTÄ myssyt tai yhdistelmä myssyt ja pipot?

--
suomenkielisessä Wikipediassa molemmat, mutta näistä vain pipo-artikkelilla on vastineita muilla kielillä:
https://fi.wikipedia.org/wiki/Pipo
https://fi.wikipedia.org/wiki/Myssy

--

MAOssa molemmat

--

fi        lakki; myssy; pipo
sv       mössa
en      cap
de      Mütze f
Lähde:  Vaatetussanaluettelo (TSK 8, 1985)  https://termipankki.fi/tepa/fi/haku/pipo

**Comment by mariaforsen** [comment]
Kyllä, myssyt, pipot, lakit = mössor

**Comment by YSO-kokous** [comment]
kts. #9178
