### ISSUE TITLE
rauhoitus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9149]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rauhoitus](http://www.yso.fi/onto/ysa/Y107007) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitsee tarkenteen 

#### Perustelut ehdotukselle   

Menee sekaisin lääketieteellisen merkityksen kanssa.

**Comment by mirmaid** [comment]
Vai riittääkö rauhoitus (sedaatio) KÄ sedaatio?

**Comment by mirmaid** [comment]
On kyllä myös käytetty hassusti väärin joitakin kertoja, olojen rauhoittaminen tai psyykkinen "rauhoittelu". Jos halutaan lisätä tarkenne, se voisi olla (suojelu). Joskus myös lisätty tarkenne ohjaustermiin.

**Comment by jarmosaarikko** [comment]
Hyvä jos **sedaatio** käsitettä voi käyttää!   Vaihtoehtona voisi olla lisätä uusi käsite: **rauhoittelu** / lugnande / appeasement, reassurance.  Näitä termejä ei löydy Finton sanastoista, paitsi ALLFO ohjaustermi "lugnande mediciner" -> sedatiivit.

 **Rauhoitus** -termi liittyy lähes aina **suojeluun** minkä vuoksi en katso tarkennetta tarpeelliseksi.
Esim. eläimet, kasvit, luonnonmuistomerkit, luonnonsuojelualueet, kalastusalueet , metsät - [Yksityismetsälaki 4§](https://www.finlex.fi/fi/laki/alkup/1967/19670412?search%5Btype%5D=pika&search%5Bpika%5D=rauhoitus#Pidp446498528)
