### ISSUE TITLE
kryoelektronimikroskopia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9150]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kryoelektronimikroskopia 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/314720 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kryoelektronimikroskopia](http://finto.fi/yse/fi/page/Y509150)

**Comment by mirmaid** [comment]
MeSH: http://www.yso.fi/onto/mesh/D020285

Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. kryoelektronmikroskopi /mesh

**Comment by jarmosaarikko** [comment]
en:  KÄ cryogenic electron microscopy KT cryoelectron microscopy, cryo-EM  YK elektronimikroskopia
https://www.wikidata.org/wiki/Q5190506
