### ISSUE TITLE
Kaurissalo (Kustavi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9158]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kaurissalo (Kustavi)

**Ehdotettu termi ruotsiksi**

Kaurissalo (Gustavs)

**Ehdotettu termi englanniksi**

Kaurissalo (Kustavi)

**Tarkoitusta täsmentävä selite**

Saari Kustavissa

**Perustelut ehdotukselle**

YSO-käsitteen Itätalo (Kaurissalo) http://www.yso.fi/onto/yso/p29190  sijainti on Kaurissalossa.  Tarkempi tarkenne voi olla tarpeen, sillä Kaurissalo on myös saarella sijaisevan kylän nimi (http://paikkatiedot.fi/so/1000772/10297132).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Kaurissalo (Kustavi : saari), Kaurissalo (Gustavs : ö)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q24328538), [MML](http://paikkatiedot.fi/so/1000772/10296959)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. https://www.finna.fi/Record/uef.9910982233705966#details

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [Kaurissalo (Kustavi)](http://finto.fi/yse/fi/page/Y509158)

**Comment by mirmaid** [comment]
Mitä tehdään kylän wikidata- ja paikkatietoalusta -linkkien suhteen? Varmaankin saaren tarkkuus on aineistoissa riittävä, mutta linkitetäänkö myös kylä samaan?

**Comment by mirmaid** [comment]
Linkit vain saareen.
