### ISSUE TITLE
eskimot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9159]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eskimot](http://www.yso.fi/onto/yso/p24293)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Inuiitti tai/ja jupikki

**Perustelut ehdotukselle**

Eskimo on loukkaava sana, eikä sitä ole kohteliasta käyttää. Jupikki- ja inuiitti-sanat tarkoittavat ”ihmisiä”, jotka ovat paljon neutraalimpeja sanoja.

**Ehdottajan organisaatio**

Wisam Elfadl

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/8597

**Comment by jarmosaarikko** [comment]
Kun "eskimot" ryhmä koostuu selvästi kahdesta alakäsitteenä olevasta ryhmästä, niin neutraali termi olisi
* **inuitit ja jupikit** (KT eskimot) / inuiter och yupiker (KT eskimåer) / Inuits and Yupiks  (KT Eskimos)
* Wikipedian [Eskimot](https://fi.wikipedia.org/wiki/Eskimot) -sivulla on selvitystä aiheesta

**Comment by mirmaid** [comment]
Tässä artikkelissa hyvin seikkaperäisesti ongelmasta paitsi kielten, myös etnisten ryhmien nimien osalta: https://www.kielikello.fi/-/eskimo-vai-inuitti-

**Comment by fantsby-m** [comment]
> 
> 
> Tässä artikkelissa hyvin seikkaperäisesti ongelmasta paitsi kielten, myös etnisten ryhmien nimien osalta: https://www.kielikello.fi/-/eskimo-vai-inuitti-

Artikkelissa mainittu Kööpenhaminan yliopisto on vaihtanut oppiaineen nimen eskimolologiasta muotoon "Grønlandske og arktiske studier". Tässä jutussa käytetään myös termiä "inuit":
https://sermitsiaq.ag/node/211175

**Comment by fantsby-m** [comment]
> 
> 
> Kun "eskimot" ryhmä koostuu selvästi kahdesta alakäsitteenä olevasta ryhmästä, niin neutraali termi olisi
> 
>     * **inuitit ja jupikit** (KT eskimot) / inuiter och yupiker (KT eskimåer) / Inuits and Yupiks  (KT Eskimos)
> 
>     * Wikipedian [Eskimot](https://fi.wikipedia.org/wiki/Eskimot) -sivulla on selvitystä aiheesta

Myös tämä tukisi muotoa **inuitit ja jupikit** (KT eskimot):
https://www.uaf.edu/anlc/resources/inuit_or_eskimo.php
(University of Alaska Fairbanks/Alaska Native Language Center)

**Comment by mariaforsen** [comment]
SAOssa https://id.kb.se/term/sao/Yupik ja https://id.kb.se/term/sao/Inuiter Ks. myös LCSH

**Comment by krinay** [comment]
LCSH:
Eskimos https://id.loc.gov/authorities/subjects/sh85044824.html
Inuit https://id.loc.gov/authorities/subjects/sh93001720.html
Yupik Eskimos https://id.loc.gov/authorities/subjects/sh89005230.html

**Comment by mirmaid** [comment]
YSOssa on omina käsitteinään _inuitit_ ja _jupikit_.

**Comment by AuHo22** [comment]
Kongressin kirjaston sanastoa katsoessa ei juurikaan voi pitää eskimo-termiä epäkorrektina - päinvastoin termejä on paljonkin asuinalueen mukaan rajattuna. Pitäisikö YSOssa olla määritelmät nykyisin olemassaoleville käsitteille?

**Comment by YSO-kokous** [comment]
Päätös
poistetaan **eskimot** 
jätetään erikseen **inuitit** sekä **jupikit**
Melindassa n. 400 tietuetta - -- voidaan korvata joko pelkällä inuitit tai jupikit -termillä tai sekä inuitit että jupikit
yhdistelmää "inuitit ja jupikit voidaan käyttää kuvailussa 653 kentässä

**Comment by jtuohini** [comment]
Aika huono ratkaisu poistaa nykyinen asiasana, kun sen olisi voinut jättää ja pistää sen kaksi alaryhmää ST-suhteisiksi. Missään nimessä ei voi Melindan 400:aan tietueseen heittää hatusta kumpaakin suppeampaa termiä tutkimatta, käsitteleekö kuvailtu aineisto vain jompaakumpaa vai kumpaakin. Edelleen vaikea ymmärtää, että YSO:on ei kelpaa termi, joka löytyy sekä LCSH:stä että Wikipediasta.

**Comment by mirmaid** [comment]
Yllä linkitetystä artikkelista: _Although the name "Eskimo" was commonly used in Alaska to refer to Inuit and Yupik people of the world, this usage is now considered unacceptable by many or even most Alaska Natives, largely since it is a colonial name imposed by non-Indigenous people_. https://www.uaf.edu/anlc/resources/inuit_or_eskimo.php

Kirjoittajasta: https://www.uaf.edu/anlc/emeritus.php

**Comment by mirmaid** [comment]
_Inuitit ja jupikit_ -muoto oli myös käsittelyssä, kuten edeltä kommenteista käy ilmi. Käytännössä se olisi kuitenkin täysin päällekkäinen kahden alakäsitteensä kanssa, joita voi molempia käyttää silloin, kun aineisto käsittelee kumpaakin, tai määrittelemätöntä ryhmää. Jos sanastossa olisi sekä erilliset käsitteet, että niiden yhdistelmä, se voisi johtaa epäjohdonmukaiseen käyttöön, jolloin osa kuvailjoista käyttää laajempaa, osa suppeampien yhdistelmää. Tässä tapauksessa toki haitta olisi pieni, jos yhdistelmän termimuoto on sama. En kuitenkaan ihan tavoita, mitä hyötyä yhdistelmätermillä saavutettaisiin.

**Comment by mirmaid** [comment]
Ks. myös https://sermitsiaq.ag/node/211175

**Comment by jtuohini** [comment]
Hieman toista mieltä olen Mirjan "[k]äytännössä se olisi kuitenkin täysin päällekkäinen kahden alakäsitteensä kanssa, joita voi molempia käyttää silloin, kun aineisto käsittelee kumpaakin, tai määrittelemätöntä ryhmää" kanssa: jos kuvailija ei ole vanhastaan määritellyt, onko aiheena inuitit ja/vai jupikit, ei tietueeseen oikein pitäisi mekaanisesti ajaa näitä molempia. Yhdistelmätermin olemassaolo mahdollistaisi sen, että nykyisellä asiasanalla kuvailtuja aineistoja ei tarvitsisi erikseen kaivaa esiin ja tutkailla, kumpaa ryhmää niissä käsitellään, ja jatkossa voitaisiin sillä kuvailla aineisto, joka käsittelee sekä inuiteja että jupikkeja. Asiasanoja on muutenkin usein tietueissa turhan monta, joten erilaiset niputtavat sellaiset ovat käytännöllisiä.

Vaan suorastaan fantastista on lukea yllä lähteenä käytetyn _Kielikellon_ artikkelin sisältämä lainaus "Useimmat eskimot kutsuivat itseään vain ihmisiksi tai oikeiksi ihmisiksi. Näillä nimityksillä he erottivat itsensä ”täinmunista” (intiaaneista) ja muista maanpäällisistä otuksista, jotka eskimoiden mielestä muistuttivat ulkonäöltään ihmisiä, mutta olivat itse asiassa alempiarvoisia eläinkunnan edustajia." Eli nimitys _inuit_ on ryhmänimenä yhtä rasistinen ja ryhmää itseään muihin nähden ylentävä kuin vaikka kansallissosialistien käyttämä "arjalainen"? Ja toisaalta venäjäksi 'saksalainen' on _немец_, joka viittaa puhumattomuuteen/mykkyyteen, olleen varmasti ainakin jonkun mielestä halventava (https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BC%D0%B5%D1%86_(%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F)). Pitäisiköhän tuonkin sanan käyttö kieltää kyseisessä kielessä? – Kaksoisstandardit ovat todellinen lahja varsinkin kielellisen käänteen jälkeiselle maailmalle.

**Comment by jarmosaarikko** [comment]
Tässä aiheessa ei ehkä pidä enää nojata yli 10 vuoden ikäisiin lähteisiin. Eri ihmisryhmistä käytettyjen nimityksien käytännöt ovat muuttuneet radikaalisti viimeisen 5-10 vuoden aikana ympäri maailmaa. Esimerkiksi Kööpenhaminan yliopiston tekemä eskimologian laitoksen nimen ja painotuksen muutos (2019) sekä suomalaisen jäätelöpuikon ja suklaasuukkojen nimenmuutokset.  Eskimologiasta ei enää puhuta. Osittain sen on voinut korvata "inuitologia".  Eskimot on kuitenkin säilytetty YSOssa ohjaustermeinä, jotta takautuva aineisto löytyy. Terminmuutoksen myötä sitä ei siis suositella uusissa kuvailuissa.

Eng-wIkipedian [Inuit](https://en.wikipedia.org/wiki/Inuit)-sivulla on aiemmin jo viitattujen lisäksi useita muita viitteitä aiheesta.  mm. [Why you probably shouldn't say eskimo?](https://www.npr.org/sections/goatsandsoda/2016/04/24/475129558/why-you-probably-shouldnt-say-eskimo?t=1645431370286) (National Public Radio, vuodelta 2016). Termin historiaa avataan hieman kirja-arvostelussa vuodelta 2018: [Early inuit studies](https://histanthro.org/reviews/early-inuit-studies/).
