### ISSUE TITLE
ristikkäiskauppa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#916]
#### Ehdotettu termi suomeksi

ristikkäiskauppa
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)
#### Lähde

Lähde: Taloussanasto
#### Käsitteen määritelmä

Tarkoittaa samanlaisten tuotteiden vientiä ja tuontia. Suurin osa teollisuusmaiden kaupasta on ristikkäiskauppaa

**Luontipäivämäärä:** 11.03.2003

**Muokkauspäivämäärä:** 11.3.2003, 11.3.2003, 16.12.2008

**Voyager-id:** 123839

**Termiehdotus Fintossa:** [ristikkäiskauppa](http://finto.fi/yse/fi/page/Y323839)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/344
