### ISSUE TITLE
elämäkertaelokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9161]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elämäkertaelokuvat](http://www.yso.fi/onto/ysa/Y111953) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tutkitaan, onko käytetty vain fiktiosta vai tarvitseeko tarkenteen. 

#### Perustelut ehdotukselle   

https://github.com/Finto-ehdotus/YSE/issues/8652

**Comment by AuHo22** [comment]
Bellfons-tietokannassa 2000-luvulla käytetty 6 kertaa dokumenttielokuvien yhteydessä, eli hyvin pienessa osassa verrattuna fiktiokuviin: Maria by Callas, Den unge Zlatan, Jaco, He named me Malala, Control, Satumaa

**Comment by mirmaid** [comment]
Ei muutoksia, ei lisätä tarkennetta.
