### ISSUE TITLE
piilokameraelokuvat (SLM)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9162]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

piilokameraelokuvat (SLM) 

#### Perustelut ehdotukselle   

On jo SLM-sanastossa, termi vaatisi ehkä muokkausta? https://github.com/Finto-ehdotus/YSE/issues/8652 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

-

**Comment by mirmaid** [comment]
Ei muutosta, suoraan elokuvien alle.
