### ISSUE TITLE
sähköturvallisuusmääräystutkinto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9163]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähköturvallisuusmääräystutkinto](http://www.yso.fi/onto/yso/p24318)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Termi muutetaan muotoon sähköturvallisuustutkinto.

**Perustelut ehdotukselle**

1980-luvulla oli sähköturvallisuusmääräystutkinto (StM-tutkinto), 1990-luvulla jossain vaiheessa se muuttui sähköturvallisuustutkinnoksi, joka löytyy kaikesta ammattikirjallisuudesta ja myös 2016 uudistetusta sähköturvallisuuslaista.

**Ehdottajan organisaatio**

Sähköalan standardointijärjestö SESKO / Vesa Linja-aho

**Comment by linjaaho** [comment]
Uusi termi on ollut pitkään käytössä kaikkialla. Vanhaan termiin törmäsin itse asiassa vain CSC:n Justus -järjestelmässä julkaisuja ilmoittaessa, kun se tyrkytti kuvailusanaksi sähköturvallisuusmääräystutkinto ja lähdin selvittämään, mistä tämä itselleni aiemmin tuntematon termi tulee järjestelmään ja täältähän se. Se on ollut käytössä ainakin 1980-luvulla:
https://finna.fi/Record/fikka.3279879#toc

mutta nykyään (ja siitä asti kun aloitin opinnot 2000-luvun alulla) on aina puhuttu sähköturvallisuustutkinnosta (löytyy niin Tukesin sivuilta kuin sähköturvallisuuslaistakin). Päivittyykö termi tätä kautta myös KOKO-ontologiaan? Ruotsinkielinen termi on oikein (elsäkerhetsexamen).

Englanninkielinen termi on electrical safety examination (ks. https://www.finlex.fi/en/laki/kaannokset/2016/en20161135.pdf ja https://tukes.fi/en/online-services/tukes-s-exams/electrical-safety-certification ).
