### ISSUE TITLE
tekstintunnistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9164]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tekstintunnistus](http://www.yso.fi/onto/ysa/Y109546) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

englanninkielinen termimuoto nyt text recognition. Pitäisikö muuttaa muotoon optical character recognition tai ainakin lisätä KT-muodoksi? 

#### Perustelut ehdotukselle   

https://termipankki.fi/tepa/fi/haku/tekstintunnistus
https://fi.wikipedia.org/wiki/Tekstintunnistus 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
ja LCSH-linkin voisi myös lisätä: Optical character recognition http://id.loc.gov/authorities/subjects/sh2010007127

**Comment by tpalonen** [comment]
Muutettu
