### ISSUE TITLE
opioidit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9165]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[opioidit](http://www.yso.fi/onto/ysa/Y112247) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Määritelmä ja suhde opiaatteihin kaipaa selkeytystä. 

#### Perustelut ehdotukselle   

Lääketieteen termien määritelmä erilainen. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Lääketieteen termit: opioidi: _1. luonnon opioidit | morfiini ja sitä muistuttavat luonnonaineet (etenkin oopiumin aineosat); 2. puolisynteettiset opioidit | opioidit jotka on valmistettu muuttamalla luonnon opioidien molekyylirakennetta; 3. synteettiset opioidit | synteettisiä lääkeaineita, jotka muistuttavat vaikutuksiltaan morfiinia, mutta poikkeavat siitä molekyylirakenteeltaan; 4. opioidipeptidit | elimistössä esiintyviä peptidejä, jotka vaikuttavat keskushermoston opioidireseptoreihin (endogeeniset opioidit, esim. enkefaliinit); 5. toisinaan opioideiksi luetaan myös →opioidiantagonistit_

opiaatti: _oopiumialkaloidi; oopiumialkaloideja sisältävä lääke; oopiumialkaloidien johdoksia sisältävä lääke_

**Comment by mirmaid** [comment]
YSO: Opioideja ovat synteettisesti valmistetut opiaattien tavoin vaikuttavat lääkeaineet

**Comment by mirmaid** [comment]
MeSH: opioidit KÄ opioidikipulääkkeet, opiaatit KÄ opiaattialkaloidit

**Comment by mirmaid** [comment]
https://paihdelinkki.fi/fi/tietopankki/tietoiskut/huumeet-ja-muut-paihdyttavat-aineet/opiaatit-morfiini-ja-heroiini

https://fi.wikipedia.org/wiki/Opioidit

**Comment by mirmaid** [comment]
Wikipedian määritelmä opiaateille on melko selkeä: _Termi opiaatti viittaa vain luonnollisiin oopiumiunikosta saataviin oopiumialkaloideihin ja niiden puolisynteettisiin johdannaisiin_. Opioidi vaikuttaisi kuitenkin olevan yläkäsite, johon myös opiaatit sisältyvät.

Pitäisikö poistaa huomautus opioideilta, lisätä opiaateille määritelmä ja näille kahdelle käsitteelle LT-ST-suhde?

**Comment by FinMeSHienPaimentaja** [comment]
MeSH- ja FinMeSH-termien suhteen tätä merkitysten vastaavuus -asiaa on pohdittu jo aiemminkin:

"opioidit", "opiaatit" ja "morfiinijohdannaiset" eivät ole merkityksiltään täsmälleen samoja.

MeSH-sanastosta kuitenkin näyttää puuttuvan täsmälliset vastineet "opioidit"- ja "opiaatit" -termeille. 

"opioidit" "Opioids" on kylläkin nykyisin voimassa olevan termin "Analgesics, Opioid"
https://meshb.nlm.nih.gov/record/ui?ui=D000701
entry-terminä. 

"Opioideihin" liittyviä termejä löytyy MeSH-sanastosta:

https://meshb.nlm.nih.gov/search?searchInField=allTerms&sort=&size=20&searchType=anyWord&searchMethod=SubString&page=1&from=0&q=opioid

Mitä "opiaatteihin" tulee, MeSH-sanastosta löytyy voimassa oleva "Opiate Alkaloids", jonka entry-terminä on "Opiates". 
https://meshb.nlm.nih.gov/record/ui?ui=D053610

Vaikka nyt em. (väliaikaiseen?) ratkaisuun MeSH-FinMeSH-kuviossa  onkin päädytty, siltikin haasteena on edelleen se, että mikä MeSH-termi olisi tarkoituksenmukaisin suomenkielisen termin "opioidit", "opioidi" vastineeksi. Sisällönkuvailtavassa aineistossa "opioideja" käytetään sekä merkityksessä kipulääkkeet (jolle siis on olemassa MeSH- ja FinMeSH-vastineet) että merkityksessä huumausaineet.

**Comment by mirmaid** [comment]
^ Onko tätä opioidien sekakäyttöä tarpeen yrittää ratkaista jotenkin?

**Comment by mirmaid** [comment]
Myös LCSH: Opioids http://id.loc.gov/authorities/subjects/sh85095085

**Comment by FinMeSHienPaimentaja** [comment]
Jos joku osaa ratkaista em. sekakäyttöongelmaa MeSH-FinMeSH-kuviossa, olisin tosi kiitollinen. :-)

**Comment by mariaforsen** [comment]
SAOssa vain https://id.kb.se/term/sao/Opioider 
opiat = "opiumhaltigt preparat särsk. om läke­medel" 
opioid = "substans som lindrar smärta och verkar lugnande och som in­går i många narkotika­klassade mediciner"
/SAOL, SO, NE

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _opioidien_ huomautus, mutta lisätään uusi määritelmä _opiaateille_, joka siirretään _opioidien_ alakäsitteeksi.
