### ISSUE TITLE
sähköherkkyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9166]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sähköherkkyys](http://www.yso.fi/onto/yso/p26838)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Englanninkielinen termi on electromagnetic hypersensitivity, ei electrosensitivity.

**Perustelut ehdotukselle**

https://www.sciencedirect.com/search?qs=electromagnetic%20hypersensitivity https://www.who.int/teams/environment-climate-change-and-health/radiation-and-health/non-ionizing/el-hsensitivity https://en.wikipedia.org/wiki/Electromagnetic_hypersensitivity

**Ehdottajan organisaatio**

**Comment by tpalonen** [comment]
Muutettu
