### ISSUE TITLE
paljakka / tunturipaljakka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9168]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

paljakka / tunturipaljakka 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/313993 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [paljakka / tunturipaljakka](http://finto.fi/yse/fi/page/Y509168)

**Comment by jarmosaarikko** [comment]
on myös paikannimi, esim. http://www.yso.fi/onto/yso/p201216 Paljakka (Kouvola), 
MML [Paljakka](https://paikkatietojentuottajat-koekaytto.maanmittauslaitos.fi/tietokortit/nimisto/paikka/10452037) ja kymmeniä muita

**Comment by mirmaid** [comment]
^ Tässä kuitenkin kasvillisuuteen liittyvänä yleisterminä.

**Comment by mirmaid** [comment]
Tunturipaljakka KT paljakka?

**Comment by mariaforsen** [comment]
Sv. kalfjäll

**Comment by YSO-kokous** [comment]
hyväksytään tunturipaljakka KT paljakka
