### ISSUE TITLE
proteiinikorona

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9170]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

proteiinikorona 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/321150 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [proteiinikorona](http://finto.fi/yse/fi/page/Y509170)

**Comment by ilona-x** [comment]
FinMeSH: proteiinikorona http://www.yso.fi/onto/mesh/D000066970

**Comment by mariaforsen** [comment]
Sv. proteinkorona ET protein corona /mesh
