### ISSUE TITLE
kaukalot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9171]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaukalot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarpeellinen esineluetteloinnissa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museoesineet

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kaukalot](http://finto.fi/yse/fi/page/Y509171)

**Comment by ilona-x** [comment]
MAOssa: kaukalot http://www.yso.fi/onto/mao/p706 (YLÄKÄSITE karjanhoitovälineet)

--

Kielitoimiston sanakirja https://www.kielitoimistonsanakirja.fi/#/kaukalo?searchMode=all :

**kaukalo**

1. pitkänomainen matalahko astia t. säiliö, allas, purtilo.
Puinen sian kaukalo.
Leik., halv.
veneestä t. laivasta.
Ei tuollaisella kaukalolla myrskyyn lähdetä.

2. Purjeveneen kaukalo kattamaton oleskelutila.

3. vars. jääkiekkokenttä laitarakennelmineen.
Jääkiekkokaukalo.

**Comment by mirmaid** [comment]
Ei Melindassa. Vähän hankala rajata...

**Comment by mariaforsen** [comment]
Sv. tråg, hoar, myös muita vaihtoehtoja riippuen merkityksestä.

**Comment by fantsby-m** [comment]
Tarvittaisiinko sitten lisäksi _urheilukaukalot_: kaukalot (urheilu) -> urheilukaukalot (tms.). Jotta termiä _kaukalot_ ei käytettäisi esim. jääkiekon, kaukalopallon ja kaukalojalkapallon yhteydessä? Aineistoa tosin ei varmaankaan ihan heti ole (https://melinda.kansalliskirjasto.fi/F/A4RD2SFC58EUXPLLE9YDKGHUQ269DXU6EI1GG4MRTACBXRSV6S-02118?func=find-b&request=j%C3%A4%C3%A4kiekkokauk*&find_code=WRD&x=0&y=0)

**Comment by mariaforsen** [comment]
Kyllä, tarvitaan ehdottomasti erillisenä terminä, jos halutaan myös urheilumerkityksessä (sv. rinkar)

**Comment by mirmaid** [comment]
Kun ehdotus on tullut museopuolen esineluetteloinnista, niin tarve on siis varmaankin [tämän tyyppinen](https://finna.fi/Search/Results?limit=0&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=kaukalot&type0%5B%5D=Subject&filter%5B%5D=%7Eformat_ext_str_mv%3A%220%2FImage%2F%22). 

Jos tarkenne olisi (astiat), sopisiko se myös eläinten syöttökaukaloihin tai [tähän](https://finna.fi/Record/museovirasto.0E9A8D8B4CC3E4726A2E42F0EA06C21C)?

**Comment by YSO-kokous** [comment]
otetaan muodossa kaukalot (astiat) 
Erikseen käsite  ruokintakaukalot KT kaukalot (eläinruokinta)

**Comment by mariaforsen** [comment]
Sv.
-tråg (kärl) 
-hoar (utfodring) ET utfodringshoar, foderhoar, mathoar
