### ISSUE TITLE
Britannia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9172]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Britannia](http://www.yso.fi/onto/ysa/Y131239) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarkennettava, jos käyttö halutaan rajata historialliseen. 

#### Perustelut ehdotukselle   

Ks. Melinda 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Samalla voisi päivittää _Britannia, Iso-Britannia_ ja _Englanti_-käsitteiden huomautukset.

**Comment by jtuohini** [comment]
Jos kaikkien paikkakuntien yhteydessä käytettäisiin valtionnimiä tarkenteina, kuten RDA olettaa, iso osa hämäristä käsitteistä tulisi kovin kirkkaiksi ilman erillisiä selityksiä ja käyttöohjeita…

**Comment by mirmaid** [comment]
^ Mutta ei ehkä auttaisi Britannian tapauksessa?

**Comment by jtuohini** [comment]
Kongressin kirjaston käytännöstä Rooman provinssien osalta, ks. LCSH-asiasanan [**Roman provinces**](http://id.loc.gov/authorities/subjects/sh85115186) ohjeistus.

Mitä tulee nimenomaan Britannian tapaukseen, LC näyttää käyttää asiasanaa [**Great Britain--History--Roman period, 55 B.C.-449 A.D.**](http://id.loc.gov/authorities/subjects/sh85056728) eikä erillistä hakutietoa samalle alueelle eri aikakauden mukaan.

Koska YSO käyttää erilaisia periaatteita, eikö yksinkertaisin ratkaisu Rooman provinssin erittelemiseksi olisi käyttää muotoa **_Britannia (Rooman valtakunta)_**?

**Comment by mirmaid** [comment]
Korjataan ensin pois ne, joissa pitäisi olla Iso-Britannia.

**Comment by ilona-x** [comment]
Voisiko Iso-Britannialle lisätä ohjaustermin Britannia (Iso-Britannia)?

**Comment by ilona-x** [comment]
Korjattu ne, joissa selvästi kyseessä Iso-Britannia. Jäljelle jäi 169 viitettä.

**Comment by mirmaid** [comment]
Muutetaan muotoon _Britannia (Rooman valtakunta)_. Tutkitaan, tarvitaanko vielä muuta.

**Comment by mirmaid** [comment]
Selvät tapaukset siivottu, jäljellä runsaasti historia-aineistoja, jotka eivät sijoitu selvästi nimen omaan roomalaisaikaan.

**Comment by tpalonen** [comment]
PÄÄTÖS:

Lisätään Iso-Britannia-käsitteelle ohjaustermiksi valtion uudempia nimimuotoja (esim. Ison-Britannian ja Pohjois-Irlannin yhdistynyt kuningaskunta). Täydennetään huomautusta viimeisen parinsadan vuoden ajan muutoksilla ja nimityksillä. 
Korjataan Britannia-viitteitä. Sen tilalle Englanti, Britteinsaaret tai muu soveltuva.
