### ISSUE TITLE
nuijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9173]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nuijat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa käytetty termi

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museon esineluettelointi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [nuijat](http://finto.fi/yse/fi/page/Y509173)

**Comment by jarmosaarikko** [comment]
on jo MAO käsite http://www.yso.fi/onto/mao/p5843,  http://www.yso.fi/onto/koko/p38180
https://www.wikidata.org/wiki/Q3202271 nuija, mallet
http://id.loc.gov/authorities/subjects/sh97005679 Mallets
https://fi.wikipedia.org/wiki/Nuija_(ty%C3%B6kalu)
https://en.wikipedia.org/wiki/Mallet

**Comment by mirmaid** [comment]
2 viitettä Melindassa.

**Comment by mariaforsen** [comment]
YSOssa klubbor = mailat, eli ruotsiksi tarvitaan tarkennetta.

**Comment by mirmaid** [comment]
^ Onko muuten klubbor-sanan kattavuus urheiluun liittyen sama kuin suomeksi (tennis/pesis/golf/jne.)? Ja pitäisikö lisätä tarkenne, vaikka ei otettaisikaan _nuijat_-käsitettä erikseen?

Kielitoimiston sanakirja: nuija: paksu- ja raskaspäinen varrellinen iskemiseen käytettävä työkalu. _Luolamiehen nuija. Puunuija. Peruna-, lihanuija. Hakata, pehmittää jtak nuijalla._

**Comment by mariaforsen** [comment]
Klubbor urheilumerkityksessä: "utvidgat redskap med böjd eller vinklad ända för manövrering av boll eller puck e.d." Mutta esim. tennismaila=tennisracket, pesismaila=slag/bollträ.. Näiden nimitys voi siis vaihdella riippuen lajista.

**Comment by mirmaid** [comment]
Mailat 26 kertaa Melindassa: jääkiekko, golf, tennis, pesis, sähly, baseball ainakin.

**Comment by mirmaid** [comment]
[Nuijat](https://finna.fi/Search/Results?limit=0&join=AND&bool0%5B%5D=AND&lookfor0%5B%5D=nuijat&type0%5B%5D=Subject&filter%5B%5D=%7Eformat_ext_str_mv%3A%220%2FImage%2F%22)

**Comment by YSO-kokous** [comment]
Tutkitaan vielä lisää nuijat ja mailat käsitteitä, jotta saadaan kielivastineet ja tarkenteet oikein.

**Comment by mirmaid** [comment]
Jos olisi _nuijat (työvälineet)_, löytyisikö ruotsiksi vastine?

Pystyykö urheilumailoille muodostamaan ruotsiksi yhdistelmäkäsitettä? Muussa tapauksessa en oikein keksi muuta kuin että kaikkien lajien mailat pitäisi auktorisoida erikseen, kun ei oikein ole sellaista jakoa suomeksi kuin "mailat, joissa on verkko (tai muu pyöreä lapa)" tai "mailat, joilla lyödään maan pinnassa" tai "suorat mailat"...

**Comment by mariaforsen** [comment]
Nuijat (työvälineet) voisi olla klubbor (arbetsredskap). Mailat voisi mahdollisesti olla "klubbor, racketar och slagträn"? Saattaa olla vielä joku muukin, mutta nämä ainakin mainitaan sanakirjoissa. Tämä ei kyllä ole suositeltava ratkaisu ruotsin kannalta, mutta jos todella halutaan välttyä ottamasta eri lajien mailat erikseen niin muuta ratkaisua ei taida olla.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon nuijat (työvälineet) 
Tämä ei kata esim. puheenjohtajan nuijia, joista paljon kuva-aineistoa. Niitä mietittävä.

fi: mailat  sv: "klubbor, racketar och slagträn"

**Comment by mariaforsen** [comment]
Sv. klubbor (arbetsredskap)

**Comment by mariaforsen** [comment]
Tehdään varmaan vastaavalla tavalla mailapelien kohdalla, eli sv. "spel med klubba, racket eller slagträ"?

**Comment by jarmosaarikko** [comment]
Englanniksi haastavaa. Wikidatassa iso joukko käsitteitä termille mailat, jotka nyt linkitetty [mailapeli](https://www.wikidata.org/wiki/Q31085894)-käsitteeseen:
 
- https://www.wikidata.org/entity/Q23669139 - bats, rackets, sticks and clubs
- https://www.wikidata.org/entity/Q240502  - racket
- https://www.wikidata.org/entity/Q12047696 - bat 
- https://www.wikidata.org/entity/Q40044101 - sports stick
- https://www.wikidata.org/entity/Q1442455 - polo stick
- https://www.wikidata.org/entity/Q3246534 - hurley
- https://www.wikidata.org/entity/Q3246534 - golf club
- https://www.wikidata.org/entity/Q3246534 - cue stick
