### ISSUE TITLE
kairat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9174]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kairat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museon esineluettelointi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kairat](http://finto.fi/yse/fi/page/Y509174)

**Comment by jarmosaarikko** [comment]
Miksei museoissa voisi käyttää MAO-käsitettä http://www.yso.fi/onto/mao/p578 , http://www.yso.fi/onto/koko/p38054
kts. myös https://termipankki.fi/tepa/fi/haku/kaira

Ei käy YSOssa ilman tarkennetta sillä [kaira ](https://www.kielitoimistonsanakirja.fi/#/kaira?searchMode=all) on myös "jokien välinen laaja erämaa Pohjois-Suomessa, selkonen, kiveliö.  Vaeltaa kairalla t. kairassa."   (Kotus)

Ehdotus:  **kairat (porat)** YK porat -- tai --- **kairat KÄ porat**
