### ISSUE TITLE
tietokonelingvistiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9175]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tietokonelingvistiikka](http://www.yso.fi/onto/ysa/Y99522) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

pitäisikö muuttaa englanninkielinen termi muotoon computational linguistics tai lisätä ainakin KT-muodoksi 

#### Perustelut ehdotukselle   

https://termipankki.fi/tepa/fi/haku/tietokonelingvistiikka
https://en.wikipedia.org/wiki/Computational_linguistics 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
voisi myös linkata tähän: LCSH: Computational linguistics http://id.loc.gov/authorities/subjects/sh85077224

**Comment by tpalonen** [comment]
Muutettu
