### ISSUE TITLE
Hiedanranta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9176]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Hiedanranta 

#### Ehdotettu termi ruotsiksi   

Sama? 

#### Ehdotettu termi englanniksi   

Sama 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[11 Maantiede. Kartografia. Kartoitus. Geodesia. Geologia. Paleontologia](http://www.yso.fi/onto/yso/p26535) 

#### Perustelut ehdotukselle   

Hiedanranta on Tampereelle rakennettava 25000 asukkaan kaupunginosa https://hiedanranta.fi/hiedanranta/ 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melinda tietue: Elävät kaupunkilaboratoriot kulttuuritoimijat Tampereen Hiedanrannan uudistajina 

**Ehdottajan organisaatio:** HY:n pääkirjasto **Termiehdotus Fintossa:** [Hiedanranta](http://finto.fi/yse/fi/page/Y509176)

**Comment by mirmaid** [comment]
Ei vielä Paikkatietoalustalla.

**Comment by mirmaid** [comment]
Millä periaatteella suunnitteilla olevat paikat sanastoon? Viikkokokous.

**Comment by ilona-x** [comment]
Google Mapsista löytyy jo: https://www.google.com/maps/place/Hiedanranta,+33400+Tampere/

**Comment by jarmosaarikko** [comment]
Kaikki suunnitelmat tai kaava-alueet eivät toteudu joko eivät heti tai eivät ollenkaan.  Silti niihin voi liittyä julkaisuja, kaavoja tms., joten niihin on tarve viitata. Sen vuoksi eikö olisi hyvä, että näitäkin (kuvitteellisia) paikkoja voi olla YSO-paikoissa siinä missä historiallisiakin paikkoja on.

**Comment by ilona-x** [comment]
Hiedanrannasta paljon osumia YLEn sivuilta: https://yle.fi/aihe/t/18-153184
