### ISSUE TITLE
lakki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9178]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lakki

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Olennainen pukeutumiseen liittyvä käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museokokoelmat

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [lakki](http://finto.fi/yse/fi/page/Y509178)

**Comment by jtuohini** [comment]
Ja KT-muodoiksi varmaan ainakin _baretit_, _baseball-lakit_, _baskerit_, _fetsit_, _kalotit (päähineet)_, _karvalakit_, _kenttälakit_, _kipat_, _kipparilakit_, _koppalakit_, _lippalakit_, _patalakit_, _pileolukset_, _suikat_, _ylioppilaslakit_ ja _zucchettot_, ellei osaa haluta itsenäisiksi asiasanoiksi? Vai halutaanko ehdotettu _**lakit**_ rajata tarkoittamaan yksinomaan lipallisia lakkeja, jolloin vain osa mainituista KT-muodoista olisi sopivia? Silloin olisi parempi otta varsinaiseksi asiasanaksi _**lippalakit**_.

**Comment by ilona-x** [comment]
MAO: 
lakit http://www.yso.fi/onto/mao/p335

--

Kielitoimiston sanakirja: 
lakki
us. lipallinen (miesten) päähine.
Lippa-, koppa-, karvalakki.

--

fi lakki; myssy; pipo
sv mössa
en cap
de Mütze f
Lähde: Vaatetussanaluettelo (TSK 8, 1985) https://termipankki.fi/tepa/fi/haku/lakki

**Comment by LeKorsu** [comment]
Kun päähineiden alakäsitteinä näyttää nykyisin olevan vain hatut, myssyt ja tykkimyssyt(!), kannatan lämpimästi lakkien ottamista ysoon. Museoala varmaan pitäisi tarkempienkin lakkien ottamista sanastoon, mutta kannattaako kuitenkin jäädä odottamaan ehdotuksia niistä?

Länsimurteiden alueelta tulevana ero on minulle selvä =)
https://www.kielikello.fi/-/hatut-lakit-ja-hattulakit

Mutta pitäisikö tykkimyssyt siirtää myssyjen alakäsitteeksi?

EDIT, lisäys: Mutta onko niin että ruotsiksi mössa on sekä lakki, myssy että pipo?

**Comment by mariaforsen** [comment]
Sv. mössa, jo sanastossa, fi. myssyt. Olisiko ratkaisu: "lakit, myssyt, pipot" tms., tai sitten pitää määritellä tarkemmin, esim. "lippalakit" (sv. skärmmössor) jne.

**Comment by jarmosaarikko** [comment]
YSO:ssa on [päähineet](http://www.yso.fi/onto/yso/p10458)  
ST hatut, hattar, hats 
ST myssyt, mössor, beanies (headgear)
ST tykkimyssyt, styckemössor, tykkimyssyt

Jos tähän halutaan selkeyttä voidaan lisätä 3 uutta alakäsitettä ja kaksi RT-suhdetta:
ST **lakit**,  skärmmössor, caps (headgear) KT keps | http://id.loc.gov/authorities/subjects/sh96011660 |  https://www.wikidata.org/wiki/Q6147804
ST **pipot**, toppluvor, knit caps  | https://www.wikidata.org/wiki/Q795738 -- kts #9146
ST **baretit**, baretter, berets | http://id.loc.gov/authorities/subjects/sh85013305
RT [kypärät](http://www.yso.fi/onto/yso/p9570),  
RT [kruunut](http://www.yso.fi/onto/yso/p19933)

**Comment by jtuohini** [comment]
Asiasanojen **tykkimyssyt** ja **myssyt** keskinäinen suhde ei käyne LT–ST-muotoiseksi, koska edellisen kuvaamat ovat kovitettuja päähineitä, siis eräänlaisia hattuja, jälkimmäisen taas pehmeitä, esimerkiksi neulomalla tehtyjä päähineitä, oikeastaan pipoja. Kielitoimiston sanakirjan mukaan hattu on "tav. jäykästä aineesta tehty kuvullinen [- -] päähine" (https://www.kielitoimistonsanakirja.fi/hattu).

Ja aivan sivuhuomioksi: mitä "NT" tarkoittaa? Aiemmin sanastoissa oli selkeästi KT = korvattu termi, LT = laajempi termi, RT = rinnakkainen termi, ST = suppeampi termi.

**Comment by YSO-kokous** [comment]
muutos: myssyt  uusi päätermi  "myssyt ja pipot"  KT myssyt, pipot
otetaan käsitteeksi "lippalakit" KT "lippikset", "lakit (lippalakit)", "baseball-lakit"

**Comment by mariaforsen** [comment]
Sv.
(-mössor)
-skärmmössor  ET baseballkepsar, kepsar, lippisar /finlandssvensk ordbok
