### ISSUE TITLE
Arbetshus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9179]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

**Ehdotettu termi ruotsiksi**

Arbetshus

**Ehdotettu termi englanniksi**

workhouse

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Behövs vid indexering.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://sv.wikipedia.org/wiki/Arbetshus)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/F/PBEXDNJ7DIGBGQM2QX9G57J4EVDKRFKGR7B9PPPBTU4MDTLGNC-02568?func=full-set-set&set_number=028945&set_entry=000001&format=999

**Ehdottajan organisaatio**

Åbo Akademi
**Termiehdotus Fintossa:** [Arbetshus](http://finto.fi/yse/fi/page/Y509179)

**Comment by mirmaid** [comment]
Löytyy _työlaitos_ https://fi.wikipedia.org/wiki/Ty%C3%B6laitos, mutta en uskaltaisi sanoa että kyse on riittävän samasta asiasta. Onkohan aivan välttämätön? Voisiko kuvailla yleisemmillä termeillä (köyhäinhoito jne.)?

**Comment by mariaforsen** [comment]
Myös SAOssa: https://id.kb.se/term/sao/Arbetshus LCSH workhouses 
YSOssa on jo: "workhouses" ja "workhouses (correctional institutions)" 
Termi "arbetshus" voisi mahdollisesti olla ohjaustermi arbetsinrättningar=fi. työlaitokset-termille (tosin tämä olisi yksinkertaistus)? Riippuen työlaitokset-termin rajauksesta, Wikipedian "työlaitos-artikkeli" taitaa olla puutteellinen, olivat nämä laitokset kai muillekin kuin elatusavun laiminlyöneille..

Ks. https://fho.sls.fi/uppslagsord/2574/arbetshus/  "Samlande benämning på diverse (mindre) förbättringsanstalter för personer som på grund av mindre förseelser, lösdriveri eller arbetslöshet hade förordnats eller dömts till allmänt arbete för kronans räkning. Arbetshusen ersattes under autonoma tiden huvudsakligen med arbets- och korrektionsinrättningar." Ja suomeksi: "rangaistustyölaitos, työsiirtola, ”työhuone”: Yleisnimitys erilaisille parannuslaitoksille, joita perustettiin pienempien rikkeiden, irtolaisuuden tai työttömyyden perusteella yleiseen työhön määrättyjä ihmisiä varten. Ne korvattiin autonomian aikana työ- ja ojennuslaitoksilla."

https://sv.wikipedia.org/wiki/Arbetshus
https://termipankki.fi/tepa/fi/haku/ty%C3%B6laitos

**Comment by mirmaid** [comment]
_Pakkotyölaitokset_ käytetty vain 13 kertaa Melindassa, enimmäkseen vangeista mutta myös tässä merkityksessä.

**Comment by YSO-kokous** [comment]
Tarkennetaan ohjaustermi arbetshus KÄ arbetsinrättningar
