### ISSUE TITLE
kartat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9180]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kartat](http://www.yso.fi/onto/ysa/Y95912) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään huomautus tämän SLM-termin käytöstä. 

#### Perustelut ehdotukselle   

Osa SLM-ryhmästä oli sitä mieltä että tätä ei käsitellä samalla tavalla kuin esim. postikortit, joten tarvitaan varmaan huomautus siitä miten/mihin tätä saa käyttää.

**Comment by AuHo22** [comment]
Mielestäni kartat kuuluvat omaan hierarkiaansa
Vrt. LC -> Maps yläkäsitteinä sekä **Cartographic materials** sekä Informational works ja Visual works.
Kartat SLM-termiä luonnollisesti käytetään vain silloin, kun kyseessä on todellinen kartta, ei karttakuvitusta, samalla tavalla kuin on kuvateos vs. vähäisempää kuvitusta. Itse en kaipaa määritelmää, vaan hierarkinen jaottelu riittäisi, kartta-aineisto on oma aineistotyyppinsä myös bib-kuvailun näkökulmasta koodeineen ja kenttineen.
Klassinen tapaus esim. kartan ja kirjan välisestä rajanvedosta Kumeassa, ks. muistion kohta 5 -> https://www.kiwi.fi/display/kumea/2019-03-20#id-20190320-5)Kysymys:Karttavaikirja?

**Comment by AuHo22** [comment]
Meillä on siis käytetty tuota kartat ikäänkuin yläkäsitteenä erimuotoisille kartta-aineistoille eli jokin termi kartta-aineisto/kartografinen aineisto ei tuo lisäarvoa? SLM-sanaston sivupaneelia katsoessa kartat on tällä hetkellä monografioiden alla, vrt. esim. elokuvat tai pelit eivät näy monografioiden alla?

**Comment by mirmaid** [comment]
Ei muutosta.
