### ISSUE TITLE
henkilökuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9181]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[henkilökuvat](http://www.yso.fi/onto/ysa/Y112823) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne (henkilöhistoria) tms. kuten SLM:ssä 
+ lisätäänkö tarkenne muotokuvat (kuvat/kuvataide) tms. 

#### Perustelut ehdotukselle   

Ruotsin vastine ei nyt täsmää, ja tarvitaan tarkennusta että voidaan erottaa termistä muotokuvat. Onko tarkenne tarpeen myös muotokuville (ruotsiksi tämä on tarkennettu kuviin) ?

Kielitoimiston sanakirja: Muotokuva:
1. näköisyyttä ja muuta luonteenomaisuutta tavoitteleva taideteos t. valokuva jksta henkilöstä. 
2. myös kirjallisesta tms. henkilökuvauksesta, henkilökuva. Kirjallinen muotokuva. Yritysjohtajan muotokuva.

Henkilökuva: kuva henkilöstä, muotokuva; henkilöhahmo

**Comment by mirmaid** [comment]
Tässä onkin mukava setti korjattavaa :unamused:.

**Comment by mirmaid** [comment]
_Muotokuvat_ näyttäisi käytetyn pääsääntöisesti oikein.

**Comment by mariaforsen** [comment]
Eli päätettiin lisätä henkilökuvat (henkilöhistoria).
