### ISSUE TITLE
kriittiset editiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9187]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kriittiset editiot](http://www.yso.fi/onto/yso/p27876)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritelmä: Kriittiset editiot ovat teosten alkuperäislähteisiin pohjautuvia julkaisuja, jotka koostuvat tekstikriittisin perustein valikoidusta ja toimitetusta tekstistä tai nuottiaineistosta sekä sitä täydentävästä kommentaariosiosta.

**Perustelut ehdotukselle**

SLM-sanasto: määritelmä tarvitaan selventämään termin käyttöä erityisesti SLM-sanastossa, mutta sopii myös YSOon.

**Ehdottajan organisaatio**

Taideyliopiston kirjasto

**Comment by mirmaid** [comment]
Lisätään määritelmä:
Teoksen alkuperäislähteisiin pohjautuva julkaisu, joka koostuu tekstikriittisin perustein valikoidusta ja toimitetusta alkuteoksen tekstistä tai nuottiaineistosta sekä sitä täydentävistä kommentaareista.

**Comment by AuHo22** [comment]
Ehdottajan määritelmä kattaa mielestäni paremmin ja laajemmin sen, mitä kriittinen editio voi olla, koska jälkimmäinen määritelmä rajaa käännösten kriittisiä editioita ulkopuolelle: Vrt:

**Kriittiset editiot ovat teosten alkuperäislähteisiin pohjautuvia julkaisuja, jotka koostuvat tekstikriittisin perustein valikoidusta ja toimitetusta tekstistä tai nuottiaineistosta sekä sitä täydentävästä kommentaariosiosta.**

mutta:  Jälkimmäisessä määritelmässä: -- _**koostuu -- alkuteoksen tekstistä**

Alkuteosten tekstiä ei välttämättä ole edes olemassa - esimerkkinä Septuaginta, joka on kreikankielinen käännös VT:stä, ja alkuperäistä tekstiä ei välttämättä ole edes olemassa. Septuagintasta on kuitenkin kirjoitettu lukemattomia kriittisiä editioita.


 https://ethesis.helsinki.fi/repository/handle/123456789/349
https://gaz.wiki/wiki/fi/Critical_edition
https://fi.wikipedia.org/wiki/Historia_Norvegi%C3%A6
http://www.vsnrweb-publications.org.uk/Text%20Series/Historia%26Passio.pdf

Itse näkisin tässäkin olennaisempana kysymyksenä oikeastaan sen, kuinka tieteellistä otetta kriittiseltä editiolta odotetaan - voiko esimerkiksi klassikon uudelleenkääntäminen yllä mainittuine piirteineen olla tekstikriittinen editio (ei tiedeyhteisössä tehty, mutta ammattitaitoisen kääntäjän tekemänä?) 

Muunkielisissä määritelmissä en myöskään löytänyt tuota alkuteoksen tekstin välttämättömyyttä - Esim, Uppslagsverk:

**Med edition av ett litterärt verk avses vanligen en s.k. vetenskaplig (eller kritisk) utgåva, där verkets tillkomsthistoria redovisas och olika versioner av texten meddelas, oftast i form av varianter, och där verket förses med ord- och realkommentar. -- 

En kritisk utgåva utgörs av huvudtext, va­ri­ant­apparat, som återger avvikelser från huvudtexten i tidigare och i vissa fall också senare versioner av texten, real- och språkkommentar samt ibland även konkordans till texten_

A text that has been published with an editor's extensive annotations, commenting on variations between different versions of the text (manuscripts, drafts, editions), and that provides an understanding of the text based on other sources.**
https://dictionary.archivists.org/entry/critical-edition.html

**Comment by MUUSA-kokous** [comment]
Määritelmä OK.

**Comment by AuHo22** [comment]
Nykyinen määritelmä SLM:ssä vaatisi mielestäni korjausta: 

    Teoksen alkuperäislähteisiin pohjautuva julkaisu, joka koostuu tekstikriittisin perustein valikoidusta ja toimitetusta **alkuteoksen tekstistä** tai nuottiaineistosta sekä sitä täydentävistä kommentaareista.

**Comment by mirmaid** [comment]
Käsitellään Aulin ehdotus ensin SLM-kokouksessa.

**Comment by mirmaid** [comment]
Teoksen alkuperäislähteisiin pohjautuva julkaisu, joka koostuu tekstikriittisin perustein valikoidusta ja toimitetusta **alkuteoksen tekstistä** tai nuottiaineistosta sekä sitä täydentävistä kommentaareista.

**Comment by mirmaid** [comment]
Tieteellisesti toimitettu julkaisu, joka pohjautuu teoksen alkuperäislähteisiin ja koostuu tekstikriittisin perustein valikoidusta ja toimitetusta alkuperäistekstistä tai nuottiaineistosta sekä sitä täydentävistä kommentaareista.

**Comment by mirmaid** [comment]
YSO?

**Comment by mirmaid** [comment]
Ratkaisuehdotus: sama määritelmä YSOon.
