### ISSUE TITLE
esiintymiskeikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9188]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[esiintymiskeikat](http://www.yso.fi/onto/ysa/Y177651) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Uusi KT soittokeikat, musiikkikeikat? 

#### Perustelut ehdotukselle   

Ja vielä tärkeämpi kysymys: rajautuuko myös suomeksi vain muusikoiden keikkoihin? Vrt. ruotsin ja englannin vastineet.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta. Termi ei rajaudu nykyisellään musiikkikeikkoihin.

**Comment by mirmaid** [comment]
Myös _gigs_ mahdollinen laajemminkin.

**Comment by mariaforsen** [comment]
Ruotsinkielinen vastine "spelningar" kyllä rajautuu lähinnä musiikkikeikkoihin. Ks. https://svenska.se/tre/?sok=spelning&pz=1 Esiintymiskeikka taitaa muuten olla aika harvinainen termi, ei löydy sanakirjoista eikä paljoa googlessakaan.

**Comment by mirmaid** [comment]
^ Onhan se. Aikoinaan kuitenkin haluttiin jokin termi _konsertit_-termin lisäksi, jolla voisi kuvailla näitä muita tilaisuuksia, ja tuo valittiin päätermiksi mieluummin kuin keikat (esiintyminen).

**Comment by mirmaid** [comment]
On käytetty valtaosin musiikista, lisäksi esim. lavarunoudesta ja stand upista. En tiedä miten välttämätön on noissa jälkimmäisissä.

**Comment by YSO-kokous** [comment]
Sanastosta löytyy jo framträdande - esiintyminen sekä uppträdande - esiintyjät. Kts myös aikaisempi ehdotus #1336 
Muutetaan päätermi muotoon KÄ **musiikkikeikat**, vanha muoto jää pois.
Muihin esiintymisiin on käytettävissä tarkemmat termit, kuten lavarunous ja stand-up -komiikka
