### ISSUE TITLE
Vanhakartano (Köyliö)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9190]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vanhakartano (Köyliö)](http://www.yso.fi/onto/yso/p17593)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tämän käytettävän termin muuttaa muotoon "Köyliönkartano" ja ohjaustermiksi "Vanhakartano" tai "Vanhakartano (Köyliö)"?

**Perustelut ehdotukselle**

"Köyliön vanhakartano" on paikannimirekisterissä kylä tai kulmakunta http://paikkatiedot.fi/so/1000772/10045727

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Yritysrekisterissä Maatal- ja Metsäyht. Köyliön Vanhakartano. MML:n paikkatyyppi on ehkä hiukan yllättävä, koska saaressa ei näyttäisi olevan kylää. Mutta varmaan molemmat muodot ok.

**Comment by mirmaid** [comment]
Kaikki kolme nimimuotoa (Köyliönkartano/Vanhakartano/Köyliön Vanhakartano) ovat käytössä kartanosta. Paikannimirekisterissä siis "Köyliön vanhakartano".

**Comment by mirmaid** [comment]
> Köyliön Vanhakartano
