### ISSUE TITLE
räpylät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9191]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

räpylät

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Eläintieteessä ja liikuntatieteessä tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esineluettelointi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [räpylät](http://finto.fi/yse/fi/page/Y509191)

**Comment by mirmaid** [comment]
2 viitettä Melindassa. En ehkä yhdistäisi näitä merkityksiä samaan, Melindan viitteet ihmisten uimaräpylöistä.

**Comment by mariaforsen** [comment]
Ruotsiksi eri termit riippuen merkityksestä. Yhdistäminen ei ole mahdollista.

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa "uimaräpylät (liikuntavälineet)"

**Comment by mariaforsen** [comment]
Sv. simfenor ET simfötter (utrustning)
