### ISSUE TITLE
kasakat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9193]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kasakat](http://www.yso.fi/onto/yso/p20599)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

muutetaan yläkäsite "muinaiskansat" -> "väestöryhmään liittyvä rooli". 

**Perustelut ehdotukselle**

Kasakat eivät ole muinaiskansa. https://en.wikipedia.org/wiki/Cossacks According to the 2002 Russian Census, 140,028 people self-identified as ethnic Cossacks. Between 3.5 and 5 million people associate themselves with the Cossack identity in post-Soviet Russia and around the world. 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Korjattu.
