### ISSUE TITLE
y-sukupolvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9197]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[y-sukupolvi](http://www.yso.fi/onto/yso/p27507)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermi ei ole milleniaali vaan millenniaali

**Perustelut ehdotukselle**

Etymologia sanalle on etymologia sanalle mille ”tuhat” ja annus ”vuosi” eli millenniaali.  https://www.kielikello.fi/-/numeron-lyhenne-ja-elaman-merkitys 

**Ehdottajan organisaatio**

YAMK-opiskelija Metropolia AMK, Hanne Mustiala

**Comment by mirmaid** [comment]
Lisätään, mutta myös muotoa milleniaalit käytetään.

**Comment by fantsby-m** [comment]
Molempia muotoja käytetään, joten voisi olla molemmat?
