### ISSUE TITLE
högkänslighet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9198]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

högkänslighet

**Ehdotettu termi ruotsiksi**

högkänslighet

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Används flitigt av studerande i social och vårdutbildningar

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

social och vård

**Ehdottajan organisaatio**

ÅA
**Termiehdotus Fintossa:** [högkänslighet](http://finto.fi/yse/fi/page/Y509198)

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/4280
https://github.com/Finto-ehdotus/YSE/issues/5755

**Comment by fantsby-m** [comment]
https://www.erityisherkat.fi/erityisherkkyys/
https://fi.wikipedia.org/wiki/Erityisherkkyys

**Comment by mariaforsen** [comment]
Kannatan, högkänslighet=erityisherkkyys. On jo myös Kielitoimiston sanakirjassa.

**Comment by mirmaid** [comment]
Sanastossa on siis jo: _herkkyys (psykologia), sähköherkkyys, ympäristöherkkyys, monikemikaaliyliherkkyys_ ja _aistiyliherkkyys_.

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: erityisherkkä: erilaisiin ärsykkeisiin erityisen voimakkaasti reagoivasta ihmisestä. _Erityisherkän lapsen tukeminen._ 

7 viitettä Melindassa, mutta aika paljon tätä on kuvailtu termillä _herkkyys (psykologia)_. Eikö näitä ole aika vaikea erottaa, milloin on kyseessä vain herkkyys ja milloin erityisherkkyys?

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi:  erityisherkkyys KÄ herkkyys (psykologia), aistiyliherkkyys
