### ISSUE TITLE
kroaatin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9200]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kroaatin kieli](http://www.yso.fi/onto/ysa/Y107285) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö päätermiksi vaihtaa kroatian kieli? 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/#/kroatia?searchMode=all
https://kaino.kotus.fi/eksonyymit/?a=kayttoohje&s=kielilistaus

**Comment by mirmaid** [comment]
Myös http://www.yso.fi/onto/yso/p28818

**Comment by mirmaid** [comment]
Lexvo: http://lexvo.org/id/iso639-3/hrv
