### ISSUE TITLE
vierasaineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9201]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[vierasaineet](http://www.yso.fi/onto/ysa/Y109712) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko jaettava tai tarkennettava? 

#### Perustelut ehdotukselle   

Huomautus rajaa elintarvikkeisiin, käytetty myös esim. vesistöistä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by ilona-x** [comment]
**ksenobiootti; luonnolle vieras aine**
määritelmä
Syntetisoituja yhdisteitä, joiden rakenteita ei esiinny luonnossa (BTS).
Lähde: 	Tieteen termipankki 08.12.2020, Ympäristötieteet:ksenobiootti https://termipankki.fi/tepa/fi/haku/ksenobiootti
	  
**vierasaine**
määritelmä
elintarvikkeeseen, rehuun tai eläimeen tuotantoprosessin yhteydessä joutunut tai lisätty aine, joka ei ole valmistus- tai lisäaine ja jolle on säädetty enimmäismäärä 
Lähde:  Maataloustukien täydentävien ehtojen sanasto (2006) https://termipankki.fi/tepa/fi/haku/vierasaine

**vieras aine**
määritelmä
tahattomasti elintarvikkeeseen tuotannon, valmistuksen, varastoinnin tai jonkin muun käsittelyn yhteydessä joutunut aine
huomautus
Vieraiksi aineiksi katsotaan esim. ympäristösaasteet (lyijy, kadmium, PCB) sekä torjunta- tai lääkeainejäämät. Vieraille aineille on asetettu sallitut enimmäismäärät.
Lähde: Lisäainesanasto (Terminfo 1995:6) https://termipankki.fi/tepa/fi/haku/vierasaine

**kontaminantti; vierasaine; vierasmikrobi**
määritelmä
epätoivottu eliö tai aine
selite
Esim. puhdasviljelmään, normaalimikrobistoon tai elintarvikkeeseen luontaisesti kuulumaton mikrobi.
Luokitus: mikrobiologia
Lähde: Tieteen termipankki 08.12.2020, Mikrobiologia:kontaminantti https://tieteentermipankki.fi/wiki/Mikrobiologia:kontaminantti

--

LCSH: Xenobiotics http://id.loc.gov/authorities/subjects/sh85148783

--

Wikipedia: https://en.wikipedia.org/wiki/Xenobiotic

--

FinMeSH: ksenobiotit KÄYTÄ vierasaineet http://www.yso.fi/onto/mesh/D015262

**Comment by fantsby-m** [comment]
Jako?: 
vierasaineet (elintarvikkeet)
vierasaineet (luonto) KT ksenobiootit

**Comment by mariaforsen** [comment]
Ruotsiksi xenobiotika määritellään: "är beteckningen på alla kroppsfrämmande ämnen, vanligtvis i betydelsen läkemedel, miljögifter och droger" eli liittyy vahvasti ihmiskehoon myös. 

Ruotsiksi toinen päätermi pitäisi varmaan olla "xenobiotika", koska termi on ihan vakiintunut https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/xenobiotika

**Comment by FinMeSHienPaimentaja** [comment]
MeSH-termin Xenobiotics määritelmä:
https://meshb.nlm.nih.gov/record/ui?ui=D015262

**Comment by FinMeSHienPaimentaja** [comment]
> Jako?: vierasaineet (elintarvikkeet) vierasaineet (luonto) KT ksenobiootit

Vierastan em. jakoa: voi tulla sen tapaisia tilanteita vastaan, että jos esimerkiksi sienissä on jotain  muutenkin luonnossa olevaa ympäristömyrkkyä, voi olla hankala valita onko kyseessä vierasaine (elintarvikkeet) vai vierasaineet (luonto). Toki konteksti ehkä kertoo, onko kyse sienistä elintarvikkeina, mutta siltikin...

**Comment by mirmaid** [comment]
https://www.jyu.fi/fi/ajankohtaista/arkisto/2022/05/10-6-2022-m-sc-andreas-eriksson-matemaattis-luonnontieteellinen-tiedekunta-bio-ja-ymparistotieteiden-laitos

**Comment by mirmaid** [comment]
https://melinda.kansalliskirjasto.fi/byid/013991283
https://melinda.kansalliskirjasto.fi/byid/013326215
https://melinda.kansalliskirjasto.fi/byid/013907045

Rajanveto mietityttää tässäkin: jos ihmisen ravintonaan käyttämiin eläimiin tai kasveihin päätyy ksenobiootteja luonnonvesistä tms., niin missä kohtaa nämä muuttuvat elintarvikkeiksi ja vierasaineiksi? Ihmisten ruuassa on vierasaineita, mutta eläinten ravinnossa ksenobiootteja? Onko vesijohtovesi elintarvike, vai onko siinä ksenobiootteja? Puhdistaako istukka sikiön ravinnosta vierasaineita kun kyse on siitä mitä äiti on syönyt, mutta ksenobiootteja, kun aineet ovat tulleet hengityksen kautta?

**Comment by mirmaid** [comment]
Ehdotus: poistetaan huomautus, lisätään ksenobiootit ohjaustermiksi.

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan ehdotuksen mukaisesti.
