### ISSUE TITLE
Hämeen lääni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9203]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Hämeen lääni](http://www.yso.fi/onto/ysa/Y105117) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "Hämeenlinnan lääni" 

#### Perustelut ehdotukselle   

Kyseisestä läänistä on käytetty myös nimeä "Hämeenlinnan lääni", ks. esim. http://digi.narc.fi/digi/view.ka?kuid=74435228 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Myös http://www.yso.fi/onto/yso/p138838

**Comment by jtuohini** [comment]
Mirjan viittaamassa pitäisi englanninkielisen muodon muuten olla ehkä enemmin "Province" kuin "County": _province_ of laajempi kuin _county_ ja Suomen osalta näiden vastineet olisivat lääni ja kihlakunta. Ruotsin osalta jostain syystä kuitenkin puhutaan läänienkin osalta noissa "suppeammalla" nimityksellä, mutta Uudenmaan ja Hämeen lääni oli olemassa myös Suomen suuriruhtinaskunnassa osana Venäjän keisarikuntaa.
