### ISSUE TITLE
haalarikamerat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9212]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

haalarikamerat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Poliisin käyttöönottama haalarikamera/vartalokamera/mikrokamera.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kamerat](http://www.yso.fi/onto/yso/p6350)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://poliisi.fi/documents/25235045/42553324/selvitys_haalarikameroiden_kayttoonotosta_poliisissa.pdf/726a205e-6f93-bfaf-716f-3c248ab2f4c8/selvitys_haalarikameroiden_kayttoonotosta_poliisissa.pdf?t=1605192756209

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [haalarikamerat](http://finto.fi/yse/fi/page/Y509212)

**Comment by mirmaid** [comment]
https://fi.wiktionary.org/wiki/haalarikamera

**Comment by mirmaid** [comment]
Sitten on kaikenlaisia action-kameroita/urheilukameroita, laitteina hyvin saman näköisiä...

**Comment by mariaforsen** [comment]
Kannatan yleisemmässä muodossa eli vartalokamera, henkilökamera tms. käytössä oleva termi. Ruotsiksi termi on kroppskameror (eng. bodycam). Nämä yleistyvät ja muutkin kuin poliisit käyttävät, jolloin se harvemmin on "haalari"kamera.

**Comment by fantsby-m** [comment]
Ylessä on jonkin verran käytetty termiä _vartalokamera_:
https://yle.fi/uutiset/18-117336

Termi näyttää olevan myös kaupallisesti käytössä, rinnalla on käytetty termejä _henkilökamera_ ja _haalarikamera_

**Comment by mirmaid** [comment]
https://www.e-ville.com/fi/1039-action-kamerat
https://www.is.fi/kotimaa/art-2000005184524.html

Olisi hyvä saada termi, joka kattaa myös ns. kypäräkamerat.

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/toimintakamera

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa **toimintakamerat** ja muut ohjaustermiksi

**Comment by mariaforsen** [comment]
Sv. actionkameror ET kroppskameror

**Comment by ilona-x** [comment]
**ohjaustermiksi** voisi lisätä myös jonkin verran käytetyn **kehokamerat**
