### ISSUE TITLE
bumerangit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9213]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

bumerangit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museokokoelmat

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [bumerangit](http://finto.fi/yse/fi/page/Y509213)

**Comment by mirmaid** [comment]
6 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. bumeranger
