### ISSUE TITLE
varamiehet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9214]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[varamiehet](http://www.yso.fi/onto/ysa/Y111074) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT varahenkilöt tai varahenkilöt päätermiksi? (vrt. esimiehet https://github.com/Finto-ehdotus/YSE/issues/9084) 

#### Perustelut ehdotukselle   

https://www.kielitoimistonsanakirja.fi/#/varahenkil%C3%B6?searchMode=all 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään KÄ varahenkilöt KT varamiehet.
