### ISSUE TITLE
Id al-Fitr

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9215]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Id al-Fitr 

#### Ehdotettu termi ruotsiksi   

Eid al-fitr 

#### Ehdotettu termi englanniksi   

Eid al-Fitr 

#### Vaihtoehtoiset termit ja ilmaisut   

Ramadanin päätösjuhla 

#### Vastaava käsite muussa sanastossa   

Id al-Fitr : https://fi.wikipedia.org/wiki/Id_al-Fitr 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Tarpeellinen termi esimerkiksi kirjassa 978-1-4197-5403-6 Once upon an Eid, jossa on juhlaa käsitteleviä kaunokirjallisia novelleja. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-1-4197-5403-6 Once upon an Eid 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Id al-Fitr](http://finto.fi/yse/fi/page/Y509215)

**Comment by mirmaid** [comment]
LCSH: http://id.loc.gov/authorities/subjects/sh85064106

**Comment by mariaforsen** [comment]
Sv. Id al-Fitr ET Eid al-fitr
 https://id.kb.se/term/sao/Id%20al-Fitr
