### ISSUE TITLE
digihyvinvointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9217]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

digihyvinvointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esiintyy usein tutkkimuskirjallisuudessa

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

-

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [digihyvinvointi](http://finto.fi/yse/fi/page/Y509217)

**Comment by jtuohini** [comment]
Mihin tällä asiasanalla mahdetaan viitata? Ettei vain olisi muutaman tutkijan lanseeraama hetkellinen muotikäsite, joka ei lopulta vakiinnu kieleen ja jonka kattama ilmiö voidaan kuvailla jo olemassaolevilla asiasanoilla.

**Comment by mirmaid** [comment]
Ei Melindassa. Aiheen ympärillä on jo melko runsaasti termistöä.

**Comment by ilona-x** [comment]
Itse olen törmännyt muotoon "digitaalinen hyvinvointi" Android-puhelimessa, kun se aina välillä ilmoittaa päivittävänsä sovellusta nimeltä "Digitaalinen hyvinvointi". https://play.google.com/store/apps/details?id=com.google.android.apps.wellbeing&hl=fi&gl=US

Mutta näyttää tästä digitaalisesta hyvinvoinnista löytyvän muutakin esim. Digitaalinen hyvinvointi perheissä -hanke:
https://demoshelsinki.fi/fi/julkaisut/digihyvinvoinnin-tiekartta/
http://urn.fi/URN:ISBN:978-952-287-913-4

**Comment by mariaforsen** [comment]
Sv. digitalt välbefinnande https://valtioneuvosto.fi/sv/-/10623/allas-delaktighet-och-valfard-ar-viktiga-i-det-digitala-samhallet digitalt välmående https://www.vaestoliitto.fi/sv/forskning/familjers-valmaende/digitalt-valmaende-i-familjer/

**Comment by ilona-x** [comment]
Tuli kuvailussa vastaan julkaisu: Digihyvinvointi kuuluu kaikille https://urn.fi/URN:ISBN:978-952-344-334-1
Tämä vain tänne muistiin eli ehdotusta ei tarvitse ottaa vielä uudelleen käsittelyyn tämän takia.
