### ISSUE TITLE
fornnordisk religion

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9218]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi ruotsiksi   

fornnordisk religion 

#### Ehdotettu termi suomeksi   

skandinaavinen muinaisusko? 

#### Ehdotettu termi englanniksi   

old norse religion 

#### Vaihtoehtoiset termit ja ilmaisut   

norse paganism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[forntida religioner](http://www.yso.fi/onto/yso/p27264) 

#### Vastaava käsite muussa sanastossa   

Svenska ämnesord : https://id.kb.se/term/sao/Fornnordisk%20religion 
Wikipedia : https://sv.wikipedia.org/wiki/Fornnordisk_religion 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/fornnordisk-religion 

#### Perustelut ehdotukselle   

Behövs vid indexering. Viktig svenskspråkig term inom religionsvetenskap. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Se Melinda: "fornnordisk religion" 

**Termiehdotus Fintossa:** [fornnordisk religion](http://finto.fi/yse/fi/page/Y509218)

**Comment by mirmaid** [comment]
Käytetty _muinaisusko, skandinaavinen mytologia, Skandinavia/Pohjoismaat_. 

https://fi.wikipedia.org/wiki/Skandinaavinen_muinaisusko, linkattu sivuun https://sv.wikipedia.org/wiki/Asatro.

**Comment by mariaforsen** [comment]
YSOssa muinaisusko = forntida religioner, eli eri asia > Kielitoimiston: =muinaisaikojen kansanusko. 

Fornnordisk religion tarvitaan siis erikseen (asatro on yksi muoto tästä tai nimitys ja yllä oleva linkki suositellaan vaihdettavaksi niin että se ohjaa fornnordisk religion-artikkeliin)

**Comment by YSO-kokous** [comment]
pohdittiin "skandinaavinen mytologia" ja "skandinaavinen muinaisusko" käsitteiden eroa. Suomessa käytetty ensin mainittua jo paljon. Kuvailussa melko päällekkäisiä käsitteitä.
Hyväksytään "skandinaavinen muinaisusko".
