### ISSUE TITLE
purpurit (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9219]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[purpurit (sävellykset)](http://www.yso.fi/onto/ysa/Y104056) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan ainakin SLM:n puolella LT-suhde "musiikki" --> "pelimannimusiikki" ja "tanssimusiikki" 

#### Perustelut ehdotukselle   

Purpurit ovat purpuritanssin säestyksenä soitettavia tanssisävelmien kokonaisuus, tyyliltään kansanmusiikkia, tarkemmin pelimannimusiikkia. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
