### ISSUE TITLE
koulunkäyntikyky

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9220]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koulunkäyntikyky 

#### Perustelut ehdotukselle   

Käsite sopii esim. seuraavaa teosta kuvailemaan: Haanpää, S. & Lahtinen, N. (2021) 140 kysymystä perusopetuksesta . 1. painos. Helsingissä: Kustannusosakeyhtiö Otava. Teoksen alaotsikossa on käytetty koulunkäyntikyky -termiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

140 kysymystä perusopetuksesta 

**Termiehdotus Fintossa:** [koulunkäyntikyky](http://finto.fi/yse/fi/page/Y509220)

**Comment by mirmaid** [comment]
Sanastossa on jo _opiskelukyky_ ja _oppimiskyky_. Melindassa vain tässä mainittu teos.

**Comment by mariaforsen** [comment]
Sv. skolgångsförmåga

**Comment by fantsby-m** [comment]
Ministeriö käyttää:
https://minedu.fi/-/tyoryhma-vaativaa-erityista-tukea-tarvitsevien-oppilaiden-oikeutta-saada-opetusta-jokaisena-esiopetus-ja-koulupaivanaan-vahvistettava

Tässä julkaisussa: https://julkaisut.valtioneuvosto.fi/handle/10024/80629
todetaan näin: 

> [Ministeriön asettama] [k]ehittämisryhmä ehdottaa, että koulukuntoisuus-käsitteen sijasta käytetään käsitettä koulunkäyntikyky.
> Koulunkäyntikykyä ei ole mielekästä arvioida pelkästään sairauden, diagnoosin
> tai käyttäytymisen perusteella, vaan on otettava huomioon myös toimintaympäristö.
> Koulunkäyntikykyyn vaikuttavat välillisesti myös koulun toimintakulttuuri ja siihen liittyvät
> asenteet sekä opetushenkilöstön pedagoginen osaaminen ja oppilaan tilanteeseen
> sopivien toimintamallien hallinta. Kehittämisryhmä korostaa koulun toimintakulttuurin ja
> -ympäristön vahvistamista ja oppilaan poislähettämisen kulttuurin toimintatapojen hylkäämistä.
> Koulunkäyntikyvyn määrittelyssä tarvitaan tiivistä yhteistyötä oppilaan ja huoltajan
> kanssa. Opetustoimen lisäksi tarvitaan moniammatillista yhteistyötä ainakin sosiaali- ja
> terveydenhuollon toimijoiden kanssa.

**Comment by fantsby-m** [comment]
...ja edelleen:

> Koulunkäyntikyvyn arviointiprosessi käynnistetään moniammatillisesti viipymättä kun
> signaaleja arvioinnin tarpeesta ilmenee, esimerkiksi heti, kun oppilaalle alkaa kertyä epäselviä
> poissaoloja tai akuutissa väkivalta- tai muussa kriisitilanteessa tai niiden uhatessa.
> Moniammatillisella arviointiprosessilla tarkoitetaan taulukon 1 mukaista kolmitahoista
> arviointia, jossa arvioidaan 1) oppilaan vointi, 2) koulun ja ryhmän tilanne sekä 3) muiden
> tahojen järjestämä tuki. Koulun ja ryhmän tilanteen arvioinnissa suositaan ryhmän ulkopuolisen
> toimijan suorittamaa havainnointia. Arvioinnin tulosten perusteella suunnitellaan
> ja vastuutetaan tarvittavat jatkotoimenpiteet.

_Opiskelukyky_ ja _oppimiskyky_ eivät siis tarkoita ihan samaa asiaa

**Comment by ilona-x** [comment]
"Koulunkäyntikyvyn osa-alueita ovat opiskelu- ja toimintakyky."

Lähde: "Mutta onko tämä lapsi koulukuntoinen?" Koulunkäyntikyvyn arviointi ja tukeminen. Puustjärvi, Anita; Luoma, Ilona. Lääkärilehti. 2019. https://www.potilaanlaakarilehti.fi/site/assets/files/0/53/18/755/sll32019-114.pdf
