### ISSUE TITLE
teemat (kielitiede)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9221]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

teemat (kielitiede) 

#### Perustelut ehdotukselle   

Tarvitaanko erikseen kielitieteen merkityksessä/merkityksissä? Ei saisi sekoittua kerrontaan. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [teemat (kielitiede)](http://finto.fi/yse/fi/page/Y509221)

**Comment by mirmaid** [comment]
https://termipankki.fi/tepa/fi/haku/teema

Pitäisikö oikeastaan olla yksikössä?

**Comment by mariaforsen** [comment]
Kannatan kielellisenä erikseen ja yksikössä.

**Comment by YSO-kokous** [comment]
Selvitetään vielä tarvitaanko tarkempi tarkenne kuin (kielitiede). 
kts. #5832 ja #8216

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Kielitiede:teema
https://tieteentermipankki.fi/wiki/Kielitiede:patientti

Itselläni ei järki riitä ymmärtämään merkitysten 1 ja 2 (tai patientti) eroa. Osaako joku sanoa, pitääkö nämä todella erottaa?

KTO:ssa on teema-reema -rakenne KÄ _tematiikka_, joka ehkä myös olisi mahdollinen ratkaisu, tematiikka (kielitiede)? KTO:ssa tosin on sekä tematiikka että _informaatiorakenne_, Tieteen termipankissa ne ovat samassa: 
https://tieteentermipankki.fi/wiki/Kielitiede:informaatiorakenne

https://www.kotus.fi/ohjeet/saadoskielen_ohjeita/informaatiorakenne

**Comment by YSO-kokous** [comment]
Otetaan sanastoon muodossa "teema-reema -rakenne"

Kts. esim. https://www.wikidata.org/wiki/Q933845   https://en.wikipedia.org/wiki/Topic_and_comment

**Comment by mariaforsen** [comment]
Sv. tema-rema
https://sv.wikipedia.org/wiki/Tema-rema
