### ISSUE TITLE
pienoisromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9223]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pienoisromaanit](http://www.yso.fi/onto/ysa/Y107466) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään YSO:on ja SLM:ään ruotsinkieliset KT-muodot "miniatyrromaner", "novellor" ja "romanetter" 

#### Perustelut ehdotukselle   

Ensimmäistä on käytetty Bella-sanastossa, ja jälkimmäiset esiintyvät mm. Wikipediassa (https://sv.wikipedia.org/wiki/Kortroman) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Lisätty.
