### ISSUE TITLE
Henkilökortti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9224]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Henkilökortti

**Ehdotettu termi ruotsiksi**

Identitetskort

**Ehdotettu termi englanniksi**

Identity card

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Suomalaisista virallisista henkilöllisyystodistuksista passi on YSO:ssa, henkilökorttia ei, vaikka se on ollut vakiintuneessa käytössä jo pitkään. Sisältöjen ja uutisten asiasanoittaminen poliisin verkkosivuilla on haasteellista, koska käytämme pääsääntöisesti YSO:a ja asiasanana voidaan käyttää vain henkilöllisyystodistusta. SEOlla tätä voidaan paikata mutta olisi hienoa, jos henkilökortti saataisiin myös asiasanana YSO:on.

**Ehdotettu yläkäsite YSOssa (LT)**

 [henkilötodistukset](http://www.yso.fi/onto/yso/p18290)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [henkilöllisyys](http://www.yso.fi/onto/yso/p22334)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Poliisin verkkosivut https://poliisi.fi/henkilokortti ja kaikki tämän asiakohdan alasivut

**Ehdottajan organisaatio**

Poliisihallitus, Timo Torvinen, timo.torvinen@poliisi.fi
**Termiehdotus Fintossa:** [Henkilökortti](http://finto.fi/yse/fi/page/Y509224)

**Comment by jarmosaarikko** [comment]
- https://www.wikidata.org/wiki/Q47988
- https://fi.wikipedia.org/wiki/Henkil%C3%B6kortti
- https://sv.wikipedia.org/wiki/Legitimationshandling
- https://en.wikipedia.org/wiki/Identity_document
- http://id.loc.gov/authorities/subjects/sh85064144 Identification cards

**Comment by mariaforsen** [comment]
YSOssa nyt identitetskort=henkilötodistukset, mutta se voisi tarkemmin olla myös identitetshandlingar/legitimationshandlingar. SAO: https://id.kb.se/term/sao/Identitetskort

**Comment by mirmaid** [comment]
Sanastossa on siis edelleen _sähköiset henkilökortit_. Pitäisikö tämä nyt kuitenkin muuttaa > henkilökortit?

**Comment by YSO-kokous** [comment]
Poistetaan sähköiset henkilökortit - otetaan tilalle henkilökortit
Poistetaan henkilökortit KÄ henkilöllisyystodistukset

**Comment by mariaforsen** [comment]
Sv. identitetskort > identitetshandlingar /https://termipankki.fi/tepa/fi/haku/henkil%C3%B6todistus ET identitetsbevis legitimationshandlingar, personbevis 
elektroniska id-kort > identitetskort /finlex ET id-kort, legitimationer
