### ISSUE TITLE
pussit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9225]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pussit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esineluettelointi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pussit](http://finto.fi/yse/fi/page/Y509225)

**Comment by mirmaid** [comment]
MAOssa ja LIIKOssa, paljon käytetty Melindassa.

**Comment by mariaforsen** [comment]
Sv. påsar
