### ISSUE TITLE
lööpit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9226]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lööpit](http://www.yso.fi/onto/yso/p24294)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi YK julisteet 

**Perustelut ehdotukselle**

Kielitoimiston sanakirja: lööppi=myyntijuliste joka sisältää (päivä)lehden tärkeimmät otsikot, otsikkojuliste. Huom. myös sv. ja eng. (eivät sovi "otsikoiden" alle)

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ruotsiksi tämä on löpsedlar ja ne eivät ole otsikoita vaan: "affisch som gör reklam för ett tidningsnummer" /saol Eli sama kuin Kielitoimiston sanakirjan määritelmä: myyntijuliste joka sisältää (päivä)lehden tärkeimmät otsikot, otsikkojuliste.

Ks. https://github.com/Finto-ehdotus/YSE/issues/8747
Eli olisiko uutisotsikot=nyhetsrubriker parempi termi/hyvä lisäys otsikko-merkitykselle? Tämä kattaisi sekä asiallisten että "vähemmän asiallisten" lehtien otsikoita...

Vrt. myös https://fi.wikipedia.org/wiki/L%C3%B6%C3%B6ppi  
"Lööppi on kansankielinen nimitys julisteelle, jolla mainostetaan sanoma- tai aikakauslehden, tavallisimmin keltaisen lehdistön julkaiseman iltapäivälehden viimeisintä numeroa."

**Comment by mirmaid** [comment]
21 viitettä Melindassa. Niistä, joista pelkän tietueen pohjalta pystyi päättelemään, suurempi osa käsitteli uutisotsikoita, muutama myös nimenomaan julisteita. Sanastossa on jo _otsikot_, ja sitä on luonnollisesti käytetty runsaasti uutisotsikoista, joten ei ehkä tarkoituksenmukaista ottaa _uutisotsikot_-käsitettä erikseen. 

Muutetaanko _lööpit_ muotoon _lööppijulisteet_?

**Comment by YSO-kokous** [comment]
päätös:
lööppijulisteet  KT lööpit
otsikot KT lööpit (otsikot)
