### ISSUE TITLE
mikrotietokoneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9228]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mikrotietokoneet](http://www.yso.fi/onto/yso/p6786)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mikrotietokoneet-käsitteen alakäsitteet voisi ryhmitellä uudelleen 

**Perustelut ehdotukselle**

Voisiko käsitteen "mikrotietokoneet" alaluokat järjestellä uudelleen? Voisiko uudelleenjärjestely auttaa sisällönkuvailijaa ilmaisemaan kuvattavan asian täsmällisemmin ja vähenisikö muutoksen myötä myös virheiden mahdollisuus, jos kohdealue ei ole tuttu?

Hämmennystä aiheuttavat seuraavat alakäsitteet:  
- Amiga 
- Commodore 64 
- Kannettavat tietokoneet 
- Raspberry Pi  

Amiga, Commodore, Raspberry ... eivät voi olla hierarkiassa samalla tasolla ja eivät samalla tasolla kannettavien tietokoneiden kanssa. Kaikista neljästä voidaan toki periaatteessa sanoa, että "x on mikrotietokone", mutta hierarkian jättäminen tämän varaan, mahdollistaa asiaa vähemmän tuntevalle kuvailijalle mahdollisuuden jopa virheelliseen kuvailuun.   

Seuraavaksi sisällönkuvailijaa tukeva ja myös arki- tai lukijanäkökulma, koska loppuun asti tarkka käsitteellinen määrittely tai erottelu olisi "liian" akateeminen ja sisältäisi myös vaikeasti kuvattavaa päällekkäisyyttä:  

Amigan ja Commodoren voisi niputtaa mikrotietokoneiden alakäsitteen alakäsitteiksi (esimerkiksi: varhaiset kotitietokoneet, varhaiset henkilökohtaiset tietokoneet tms. alakäsitteiksi). "Varhaiset kotitietokoneet" määrittyvät ensimmäisiksi yleisemmin käytetyiksi kotitietokoneiksi, jotka eivät vielä silti edustanet nykymuotoisia koti- tai yrityskäyttöön tarkoitettuja PC-tietokoneita (https://fi.wikipedia.org/wiki/Henkil%C3%B6kohtainen_tietokone), mutta eivät ole myöskään suurtietokoneita (https://fi.wikipedia.org/wiki/Suurtietokone) tai minitietokoneita (https://fi.wikipedia.org/wiki/Minitietokone). 

Raspberry Pi taas voisi saada yläkäsitteekseen korttitietokoneet (markkinointitermi) tai yhden piirilevyn tietokoneet tms. "Korttitietokoneet" olisivat mikrotietokoneiden alakäsite.  Amiga ja Commodore eivät ole niin paljon omia 'tyyppejään', että voisivat olla mikrotietokoneiden alakäsitteitä, koska paljon muitakin vastaavia oli aikanaan olemassa, kuten Amstrad CPC, Spectravideo yms., jotka myöskään eivät voi olla samalla tasolla kannettavien tietokoneiden kanssa, kuten Amiga ja Commodorekin nyt ovat. 

Ehdotetaan seuraavaa hierarkiaa (kuvailun tarpeet huomioiva, ei akateeminen näkemys):  

1 Mikrotietokoneet: 
1.1 kannettavat tietokoneet 
1.1.1 taskutietokoneet 
1.2 varhaiset kotitietokoneet 
1.2.1 Amiga 
1.2.2 Commodore 
1.2.3 Amstrad CPC 
1.2.4 Spectravideo 
1.3 korttitietokoneet 
1.3.1 RaspBerry Pi 
1.3.2 Arduino Uno 
1.4 Ohjelmoitavat logiikat (laite) 
(eng: Programmable logic controllers, ohjaus: PLC) 
1.4.1 Siemens SIMATIC 
1.4.2 QnU 
1.4.3 ABB PLC 
1.4.4. Omron 
jne..

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Edellyttäisi uusien käsitteiden lisäämistä, mutta näin tehdään normaalisti vain kuvailutarpeen perusteella. Nykyinen hierarkia vastaa esim. LCSH:n hierarkiaa. Ei muutoksia / YSO-palaveri 16.12.2021.
