### ISSUE TITLE
pulpetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9229]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

pulpetit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museoesineet

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [pulpetit](http://finto.fi/yse/fi/page/Y509229)

**Comment by mirmaid** [comment]
MAOssa, kerran Melindassa. Pitääkö tätä rajata jotenkin? Suomeksi kyllä yleensä rajautuu koulukalusteisiin.

**Comment by mariaforsen** [comment]
Olisi hyvä rajata, jos koulukaluste= pulpeter/skolbänkar, jos muu niin pulpeter + tarkenne 
https://svenska.se/tre/?sok=pulpet&pz=1 Ja kyllähän myös Kielitoimiston sanakirja antaa tälle sanalle kolme eri merkitystä.

**Comment by fantsby-m** [comment]
Tarkenne voisi olla tarpeen, ettei käytetä esim. ohjauspulpeteista.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa pulpetit (koulukalusteet)

**Comment by mariaforsen** [comment]
Sv. pulpeter (skolbänkar) ET skolbänkar
