### ISSUE TITLE
valintakoemenetelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9230]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

valintakoemenetelmä 

#### Ehdotettu termi englanniksi   

choice experiment 

#### Perustelut ehdotukselle   

Valintakoemenetelmällä tehtävät tutkimukset ovat yleistyneet esimerkiksi taloustieteen ja lääketieteen saralla, sanastosta löytyvä "valintakoe" tarkoittaa pääsykoetta, joka ei ole lainkaan verrattavissa englannin kielessä käytettyihin choice experimentseihin. Käsitettä valintakoemenetelmä käytetään jo suomeksi laajasti kuvaamaan kyseisellä metodilla toteutettuja tutkimuksia. 

#### Tarkoitusta täsmentävä selite   

Esimerkiksi taloustieteessä hyödynnettävä tutkimusmenetelmä, jossa selvitetään kyselyn avulla vastaajan preferenssejä vastaajan tekemien valintojen perusteella. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.ptt.fi/julkaisut-ja-hankkeet/kaikki-julkaisut/yksityismetsien-puuntarjonta-puunmyyntipaatokseen-vaikuttavat-tekijat.html 

**Ehdottajan organisaatio:** Vaasan yliopisto **Termiehdotus Fintossa:** [valintakoemenetelmä](http://finto.fi/yse/fi/page/Y509230)

**Comment by mirmaid** [comment]
6 viitettä Melindassa. Itse kyllä oletin, että kyse on opiskelijavalinnasta (valintakoe/todistuspisteet) - ja on näköjään myös käytetty siinä yhteydessä (Google). 

Eli varmaan joko _valintakoemenetelmä (tutkimusmenetelmät)_ tai päätermiksi _CE-menetelmä_. Jälkimmäinen kyllä aika vähän käytetty...

**Comment by mariaforsen** [comment]
Sv. choice experiment metoden ET (CE-metoden, valexperiment)

**Comment by YSO-kokous** [comment]
valintakoemenetelmä (tutkimusmenetelmät) KT CE-menetelmä
