### ISSUE TITLE
metsävakuutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9231]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

metsävakuutus 

#### Ehdotettu termi englanniksi   

forest insurance 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vakuutus](http://www.yso.fi/onto/yso/p2956) 

#### Tarkoitusta täsmentävä selite   

Tontti- tai talousmetsälle otettava vakuutus 

#### Perustelut ehdotukselle   

Metsävakuutukset muodostavat merkittävän sektorin suomalaisista vakuutusmarkkinoista ja käsite on vakiintunut vakuutusalalla 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Brunette, M., Couture, S., & Pannequin, F. (2017). Is forest insurance a relevant vector to induce adaptation efforts to climate change? Annals of Forest Science, 74(2), 41. https://doi.org/10.1007/s13595-017-0639-9 

**Termiehdotus Fintossa:** [metsävakuutus](http://finto.fi/yse/fi/page/Y509231)

**Comment by mirmaid** [comment]
AFOssa, käytetty reilut 30 kertaa Melindassa. Vastaavia on sanastossa.

**Comment by mariaforsen** [comment]
Sv. skogsförsäkring
