### ISSUE TITLE
suorakulmat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9232]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suorakulmat 

#### Ehdotettu termi englanniksi   

square 

#### Ehdotettu termi ruotsiksi   

vinkelhake 

#### Perustelut ehdotukselle   

Yleinen työkalu, puuttuu, vaikka löytyy kyllä vanhasta ysasta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

museoesineet 

**Ehdottajan organisaatio:** Kansallismuseo **Termiehdotus Fintossa:** [suorakulmat](http://finto.fi/yse/fi/page/Y509232)

**Comment by jtuohini** [comment]
Ja vähintään KT-muodoksi kielellisesti ainakin itselleni tutumpi "suoratkulmat" ([Kielitoimiston sanakirjassa](https://www.kielitoimistonsanakirja.fi/#/suorakulma?searchMode=all) kumpikin taivutusmuoto listattuna).

**Comment by mirmaid** [comment]
Eli nimenomaan tämä työkalu https://fi.wikipedia.org/wiki/Suorakulma, ei mikä tahansa kulmaviivain? MAO http://www.yso.fi/onto/mao/p4511.

**Comment by jtuohini** [comment]
Ja kaikille vielä helpoksi linkiksi Mirjan mainitsemat kulmaviivaimet ja astelevyt: https://fi.wikipedia.org/wiki/Viivain

**Comment by mariaforsen** [comment]
Sv. anslagsvinklar (verktyg) ET vinkelhakar

**Comment by fantsby-m** [comment]
Tarkenteella: _suorakulmat (työkalut)_? Muuten saatetaan käyttää virheellisesti jos termin _suora kulma_ oikeinkirjoitus ei ole hallussa (toki on epätodennäköistä että tällaista aineistoa tulisi).  

Ohjaustermiksi _suorakulmain_?

**Comment by YSO-kokous** [comment]
Hyväksytään suorakulmat (työkalut) KT suorakulmaimet, suoratkulmat
