### ISSUE TITLE
ilmastokriisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9233]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ilmastokriisi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Asiasana "ilmastonmuutokset" on täysin harhaanjohtava ja riittämätön käsite kuvaamaan valtavaa kriisiä, jossa olemme. Ilmastokriisiä käsittelevää aineistoa ilmestyy paljon ja koko ajan enemmän. Kyseessä on ihmiskunnan historian suurin kriisi ja meillä ei ole vuonna 2021 edes asiasanaa ilmastonmuutokselle, saati ilmastokriisille/ilmastokatastrofille tai luonnon monimuotoisuuden kriisille / ekokriisille. Ehdotan samalla myös ekokriisin ottamista sanastoon. 

Covid-19-pandemiallekin on jo näin nopeasti oma asiasanansa, vaikka kyseessä on vain pieni osa koko valtavaa ekokriisiä, jossa olemme. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

No tätä nykyä vaikka kuinka monen. Tämä tuli nyt mieleen artikkelia Sanaton yhteys (Kirjailija 1/2021) asiasanoittaessa.

**Ehdottajan organisaatio**

Suomalaisen kirjallisuuden seura
**Termiehdotus Fintossa:** [ilmastokriisi](http://finto.fi/yse/fi/page/Y509233)

**Comment by jarmosaarikko** [comment]
- https://www.wikidata.org/wiki/Q60933643 - sv: klimatkris
- https://en.wikipedia.org/wiki/Climate_crisis
Viiteitä:
- https://www.sitra.fi/blogit/mita-ipccn-raportin-ensimmainen-osa-kertoo-ilmastokriisin-etenemisesta/
- https://www.un.org/en/un75/climate-crisis-race-we-can-win
- Käytetty Melindassa kerran asiasanana, esiintyy 28 tietueessa, 
- Google 218.000 osumaa. "climate crisis" 18 miljoonaa osumaa.

**Comment by mirmaid** [comment]
Kerran Melindassa. YSOssa on: _ilmastonmuutokset, kasvihuoneilmiö, ilmastovaikutukset, ilmastonsuojelu, ilmastopolitiikka, ilmastostrategiat, ekokatastrofit_ jne. 

https://github.com/Finto-ehdotus/YSE/issues/6896

**Comment by mirmaid** [comment]
Ekokriisit KÄ ekokatastrofit?

**Comment by YSO-kokous** [comment]
Hyväksytään ilmastokriisi
Lisätään ekokriisit KÄ ekokatastrofit

**Comment by mariaforsen** [comment]
Sv. klimatkrisen
