### ISSUE TITLE
sirpit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9237]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sirpit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museoesineet

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [sirpit](http://finto.fi/yse/fi/page/Y509237)

**Comment by jarmosaarikko** [comment]
- https://fi.wikipedia.org/wiki/Sirppi - https://sv.wikipedia.org/wiki/Sk%C3%A4ra skära -  https://en.wikipedia.org/wiki/Sickle
- https://www.wikidata.org/wiki/Q42233
- http://id.loc.gov/authorities/subjects/sh85122299

**Comment by mirmaid** [comment]
MAOssa, 13 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. skäror
