### ISSUE TITLE
suolanpoisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9242]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

suolanpoisto 

#### Ehdotettu termi ruotsiksi   

avsaltning 

#### Ehdotettu termi englanniksi   

saline water conversion 

#### Vaihtoehtoiset termit ja ilmaisut   

suolanpoisto vedestä 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[vedenpuhdistus](http://www.yso.fi/onto/yso/p15306) 

#### Vastaava käsite muussa sanastossa   

LCSH : Saline water conversion 

#### Tarkoitusta täsmentävä selite   

https://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:suolanpoisto 

#### Perustelut ehdotukselle   

tarve kuvailussa
Melinda x 7 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The role of renewable energy based seawater reverse osmosis (SWRO) in meeting the global water challenges in the decates to come 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [suolanpoisto](http://finto.fi/yse/fi/page/Y509242)

**Comment by mirmaid** [comment]
8 kertaa Melindassa.

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Desalination

**Comment by YSO-kokous** [comment]
Hyväksytään. Tarkistetaan yläkäsite ja tarvitaanko tarkennetta.
