### ISSUE TITLE
lähihistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9244]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lähihistoria](http://www.yso.fi/onto/ysa/Y127143) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotan huomautusta poistettavaksi, termi kuvaa myös aikakautta, eikä vain historiantutkimuksen aluetta. Tämänkaltainen käyttökelpoinen termi tarvitaan myös laajemmassa merkityksessä. Termi nykyaika on vielä problemaattisempi eli sitä en ehdota, esim.
https://tieteentermipankki.fi/wiki/Nimitys:nykyaika 

#### Perustelut ehdotukselle   

https://tieteentermipankki.fi/wiki/Nimitys:l%C3%A4hihistoria

Här / nu : 10+1 essäer : om samtiden  / red. Ralf Andtbacka och Ulrika Nielsen 

#### Ehdottajan organisaatio   

Kirjastopalvelu

**Comment by mariaforsen** [comment]
MOT Schildts Finlandssvensk ordbok: närhistoria vanl. samtidshistoria fi. lähihistoria. 
Nationalencyklopedin: "historia om den egna tiden i mots. till gångna tider" / "samtidshistoria, nutidshistoria, nyaste tidens historia, vid 1800-talets slut uppkommen benämning på den allra senaste historien."
