### ISSUE TITLE
alkusammutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9246]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

alkusammutus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Alkusammutus on pienen palon alun ripeää sammutusta alkusammutusvälineillä ja poikkeaa varsinaisesta sammutustyöstä. Alkusammutuksen voi tehdä kuka tahansa varsinaisen sammutustyön ollessa pelastusalan ammattilaisten toimintaa. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [sammutus](http://www.yso.fi/onto/yso/p1873)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://issuu.com/spek_ry/docs/spek_opastaa_5_alkusammuttimet

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [alkusammutus](http://finto.fi/yse/fi/page/Y509246)

**Comment by jarmosaarikko** [comment]
- "incipient fire extinguishing" tai "incipient stage fire extinguishing"  Lähde: https://en.wikipedia.org/wiki/Active_fire_protection
- primärsläckning  -- lähde: https://pelastustoimi.fi/sv/hem-och-vardag/nodsituation/primarslackningsutrustning

Onko tarpeen kuvailla toimintaa (alkusammutus)  vai välineitä  (alkusammutusvälineet) vai molempia? 
- Alkusammutusvälineet ovat kohteessa olevia ja yhden henkilön käyttöön soveltuvia kuten käsisammuttimet ja sammutuspeitteet.  [https://fi.wikipedia.org/wiki/Alkusammutin](https://fi.wikipedia.org/wiki/Alkusammutin)  
- YK [sammuttimet](http://www.yso.fi/onto/yso/p18186)

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. primärsläckning, förstahandssläckning, första släckning ET första släckningsinsats
https://termipankki.fi/tepa/fi/haku/alkusammutus
