### ISSUE TITLE
käpyrauhanen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9247]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

käpyrauhanen 

#### Ehdotettu termi englanniksi   

pineal gland 

#### Ehdotettu termi ruotsiksi   

tallkottkörtel 

#### Vaihtoehtoiset termit ja ilmaisut   

käpylisäke 

#### Ehdotettu yläkäsite YSOssa (LT)   

[umpirauhaset](http://www.yso.fi/onto/yso/p5176) 

#### Assosiatiiviset (RT)   

[aivot](http://www.yso.fi/onto/yso/p7040) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D010870> 
LCSH : <http://id.loc.gov/authorities/subjects/sh85102232> 
Wikipedia : https://fi.wikipedia.org/wiki/K%C3%A4pyrauhanen 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

Melinda:
käpyrauhanen x 5
käpylisäke x 4 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Microneurosurgery of pineal region cysts and tumors 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [käpyrauhanen](http://finto.fi/yse/fi/page/Y509247)

**Comment by mariaforsen** [comment]
Sv. tallkottkörtel ET epifysen, övre hjärnbihanget, tallkottskörtel
