### ISSUE TITLE
lamentot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9248]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lamentot](http://www.yso.fi/onto/ysa/Y505560) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan myös SLM-sanastoon, LT "laulumusiikki" ja "taidemusiikki" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Hyväksytty/SLM
