### ISSUE TITLE
spektrimusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9249]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[spektrimusiikki](http://www.yso.fi/onto/ysa/Y214678) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan SLM-sanastoon, LT "taidemusiikki" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
Hyväksytty/SLM
