### ISSUE TITLE
SLM monikieliset teokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9251]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM monikieliset teokset

**Ehdotettu termi ruotsiksi**

flerspråkiga verk

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tämä tarvitaan SLM termiksi juuri sellaisiin aineistoihin, joissa on kyse yhdestä teoksesta, jossa erikielisiä ekspressioita. Tätä asiaa ei voi ilmaista oikein muulla tavalla ja genreterminä olisi mahdollista saada paremmin esiin tämän tyyppistä aineistoa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

978-952-7347-97-3 / Kuinka krokotiili kadotti kielensä ja 978-951-1-37739-9 / Tervetuloa! = ‡b Soo dhawoow! = Benvenuti! = Xoš âmadid! = Bi xêr bi!

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [SLM monikieliset teokset](http://finto.fi/yse/fi/page/Y509251)

**Comment by ilona-x** [comment]
Seuraava SLM-kokous. 
Selvitetään mahdollisuutta rajata käyttöä sellaisiin teoksiin, joissa on koko sisältö kahdella/useammalla kielellä.

**Comment by jtuohini** [comment]
Pohdittavaksi kaksi- tai useampikielisten julkaisujen (manifestaatioiden, ei teosten) osalta myös muodot **_rinnakkaistekstit_**, **_rinnakkaistekstiset julkaisut_** tms, jos ehdotuksen ydin on, että kuvailtava aineisto sisältää yhden ja saman teoksen useana erikielisenä ekspressiona.

**Comment by AuHo22** [comment]
https://www.kirjastot.fi/kysy/onko-helmetissa-italiankielisia-kirjoja-joissa?language_content_entity=fi

**Comment by AuHo22** [comment]
978-952-94-5069-5 
Tässä meillä eteen tullut monikielinen kirja (aikuisten)

Yo. Helmetin vastauksessa seuraava: "Haut on kohdistettu tässä kaunokirjallisuuteen, koska tietokirjallisuuden sisällyttäminen hakuun toisi mukaan oppikirjat ja sanakirjat."
->
Itse taipunen kannattamaan muotoa monikieliset kirjat, mutta mielestäni tarvitsisi huomautuksen, jossa nimenomaan suljetaan pois ei-relevanttia aineistoa, esim. Ei käytetä oppikirjojen, sanakirjojen tai näyttelyjulkaisujen yhteydessä tms. -> Näyttelyjulkaisujen yhteydessä yleensä kuvallinen esittäminen on tärkeämpi kuin kielellinen.

**Comment by mirmaid** [comment]
Ko. kirja ^ https://www.suomenpen.fi/suomen-penin-kustantama-kirja-sulava-monikielinen-kirjallisuus-suomessa-on-julkaistu-ja-saatavilla-kaupoista/

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/2515
