### ISSUE TITLE
tanssinopettajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9252]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssinopettajat](http://www.yso.fi/onto/ysa/Y105934) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "balettimestarit" ja "tanssimestarit" 

#### Perustelut ehdotukselle   

Ks. esim. https://oopperabaletti.fi/kulisseissa/vastaava-balettimestari-ingrid-nemeckova/, https://fho.sls.fi/uppslagsord/12995/dansmastare/, https://www.britannica.com/art/dancing-master, https://en.wikipedia.org/wiki/Dancing_master 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
https://tieteentermipankki.fi/wiki/Esitt%C3%A4v%C3%A4t_taiteet:balettimestari

Tanssimestari suomeksi tuo mieleen enemmän jonkun kilpakentillä menestyneen.

**Comment by YSO-kokous** [comment]
hyväksytään KT tanssimestarit (tanssinopettajat)
Tarkistetaan vielä "balettimestarit".

**Comment by mariaforsen** [comment]
Sv. gemensam jordbrukspolitik ET gemensamma jordbrukspolitiken

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: balettimestari = baletin ohjaaja.

Tieteen termipankki: balettiryhmän johtaja. _Kyseessä on vanha nimike, joka on ollut käytössä 1700-luvulta 1900-luvulle. Balettimestari oli käytännössä balettiryhmän johtaja, jonka laajaan työnkuvaan kuului tanssijoiden koulutus ja hän harjoitti heille ohjelmistossa olevat teokset. Balettimestari toimi baletin koreografina ja hän vastasi usein myös oopperoiden koreografioista, jos ryhmä toimi oopperatalossa. Sittemmin työtehtävät ovat eriytyneet ja nykyään balettiryhmässä on usein erikseen taiteellinen johtaja, harjoittaja sekä vierailevia koreografeja._

Tämän perusteella en lisäisi ohjaustermiä, balettimestari on toisaalta suppeampi termi (yhden tanssilajin "mestari"), toisaalta laajempi, eli muutakin kuin vain opettaja.

**Comment by YSO-kokous** [comment]
EI hyväksytä KT balettimestarit, sillä on muutakin kuin opettaja.
