### ISSUE TITLE
koreografit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9253]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koreografit](http://www.yso.fi/onto/ysa/Y96329) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "tanssimestarit" 

#### Perustelut ehdotukselle   

Vrt. https://github.com/Finto-ehdotus/YSE/issues/9252 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
ei hyväksytty
