### ISSUE TITLE
rastahiukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9254]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rastahiukset 

#### Vaihtoehtoiset termit ja ilmaisut   

rastatukka 
takkutukka 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Takkunuttu 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [rastahiukset](http://finto.fi/yse/fi/page/Y509254)

**Comment by jarmosaarikko** [comment]
- LCSH **Dreadlocks** [http://id.loc.gov/authorities/subjects/sh94003063](http://id.loc.gov/authorities/subjects/sh94003063)
- https://www.wikidata.org/wiki/Q898801  **rastatukka**

**Comment by mariaforsen** [comment]
Sv. rastafrisyr, dreadlocks https://svenska.se/so/?id=165206&ref=lnr803174 ET rastahår
