### ISSUE TITLE
maaseudun kehittäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9255]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maaseudun kehittäminen

**Ehdotettu termi ruotsiksi**

landsbygdsutveckling

**Ehdotettu termi englanniksi**

rural development

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Käytössä MMM:ssä ja muuallakin hallinnonaloilla. Yksi MMM:n osastoista.
RYHMÄ: 22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous

**Ehdotettu yläkäsite YSOssa (LT)**

 [kehittäminen](http://www.yso.fi/onto/yso/p4230)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 rural utveckling, utveckling av landsbygden

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [maaseudun suunnittelu](http://www.yso.fi/onto/yso/p10880), [yhteiskuntakehitys](http://www.yso.fi/onto/yso/p9763)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85115899), [JUHO](http://www.yso.fi/onto/juho/p1814), [Wikidata](https://www.wikidata.org/wiki/Q3773637), [Wikipedia](https://en.wikipedia.org/wiki/Rural_development), [Agrovoc](http://aims.fao.org/aos/agrovoc/c_6701)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

VNK julkaisut

**Ehdottajan organisaatio**

Kansalliskirjasto / MMM
**Termiehdotus Fintossa:** [maaseudun kehittäminen](http://finto.fi/yse/fi/page/Y509255)

**Comment by mirmaid** [comment]
AFOssa, JUHOssa ja JUPOssa, käytetty runsaasti.
https://github.com/Finto-ehdotus/YSE/issues/9256

**Comment by mariaforsen** [comment]
Sv. landsbygdsutveckling ET glesbygdsutveckling, rural utveckling
