### ISSUE TITLE
yhteinen maatalouspolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9256]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yhteinen maatalouspolitiikka

**Ehdotettu termi ruotsiksi**

gemensamma jordbrukspolitiken

**Ehdotettu termi englanniksi**

common agricultural policy

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

CAP kattaa puolet EU:n budjetista, joten siihen liittyviä aineistoja on paljon. Määritelmä/kuvaus:  https://ec.europa.eu/info/food-farming-fisheries/key-policies/common-agricultural-policy/cap-glance_fi

**Ehdotettu yläkäsite YSOssa (LT)**

 [EU-politiikka](http://www.yso.fi/onto/yso/p8435)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

 Euroopan unionin yhteinen maatalouspolitiikka, YMP, GJP, CAP, Politique Agricole Commune

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [maatalouspolitiikka](http://www.yso.fi/onto/yso/p10881), [maataloustuet](http://www.yso.fi/onto/yso/p38573)

**Vastaava käsite muussa sanastossa**

 [Wikidata](https://www.wikidata.org/wiki/Q220687), [Wikipedia](https://fi.wikipedia.org/wiki/Euroopan_unionin_yhteinen_maatalouspolitiikka)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Erityisesti valtionhallinnon/VNK dokumenteissa ja julkaisuissa sekä EU-tutkimuksessa.

**Ehdottajan organisaatio**

Kansalliskirjasto/asiakasehdotus (MMM)
**Termiehdotus Fintossa:** [yhteinen maatalouspolitiikka](http://finto.fi/yse/fi/page/Y509256)

**Comment by jarmosaarikko** [comment]
"maaseudun kehittäminen" liittyy maaseutupolitiikkaan, kun taas "maaseudun suunnittelu" liittyy aluesuunnitteluun eli nämä ovat eri käsitteitä.

**Comment by mirmaid** [comment]
2 viitettä Melindassa. Sanastossa on _yhteinen ulko- ja turvallisuuspolitiikka_.

**Comment by mariaforsen** [comment]
Sv. gemensam jordbrukspolitik ET gemensamma jordbrukspolitiken
