### ISSUE TITLE
Lappajärven musiikkipäivät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9257]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Lappajärven musiikkipäivät 

#### Ehdotettu termi ruotsiksi   

Lappajärvi musikdagar 

#### Ehdotettu termi englanniksi   

Lappajärvi Music Festival 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tapahtumat](http://www.yso.fi/onto/yso/p2108) 
[juhlat](http://www.yso.fi/onto/yso/p1574) 
[musiikkijuhlat](http://www.yso.fi/onto/yso/p1482) 

#### Alakäsitteet (RT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 
[vapaa-aika](http://www.yso.fi/onto/yso/p3276) 
[musiikkijuhlat](http://www.yso.fi/onto/yso/p1482) 
[taidemusiikki](http://www.yso.fi/onto/yso/p18434) 

#### Perustelut ehdotukselle   

Merkittävä musiikkifestivaali jota järjestettiin Lappajärvellä vuosina 1985-1998. Esiintymässä olivat sen ajan kotimaisia tähtiä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Finna 

**Termiehdotus Fintossa:** [Lappajärven musiikkipäivät](http://finto.fi/yse/fi/page/Y509257)

**Comment by jtuohini** [comment]
Kyseessä tapahtuma ja kuuluu Kannon puolelle! (Marcissa 111-muotoinen hakutieto.)

**Comment by MUUSA-kokous** [comment]
Kannatetan lisäämistä Kantoon.

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q107280610

**Comment by mariaforsen** [comment]
Lappajärvi musikdagar kerran googlessa.

**Comment by mirmaid** [comment]
Ehdotus koskee toimijan nimeä, viesti on välitetty Kansalliskirjaston toimijakuvailupalveluun ([katso yhteystiedot](https://www.kiwi.fi/x/m4GQB)).
