### ISSUE TITLE
jenkka (tanssit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9258]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jenkka (tanssit)](http://www.yso.fi/onto/ysa/Y216383) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "sotiisi (tanssit)", "tyyskä (tanssit)" ja "tyyskäpolkka (tanssit)" 

#### Perustelut ehdotukselle   

Kyseinen tanssi tunnetana myös näillä nimillä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
**Päätös:** Lisätään KT-muodot "sottiisi (tanssit)", "tyyskä (tanssit)" ja "tyyskäpolkka (tanssit)"
