### ISSUE TITLE
jenkat (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9259]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[jenkat (sävellykset)](http://www.yso.fi/onto/ysa/Y101934) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "sotiisit (sävellykset)", "tyyskät (sävellykset)" ja "tyyskäpolkat (sävellykset)". – SLM:n puolelle tarvitaan samat lisäykset + ne, jotka ovat jääneet taannoin YSO:sta siirtämättä, toki ilman tarpeettomia sulkutarkenteita. 

#### Perustelut ehdotukselle   

Jenkkasävelmiä tunnetaan myös näillä nimillä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by YSO-kokous** [comment]
**Päätös:**  Lisätään KT-muodot "sottiisit (sävellykset)", "tyyskät (sävellykset)" ja "tyyskäpolkat (sävellykset)"
