### ISSUE TITLE
dispersiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9260]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dispersiot](http://www.yso.fi/onto/ysa/Y106632) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tätä ehkä tarkennettava, vrt. optinen dispersio 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
yksikkömuoto olisi oma käsitteensä. 
- https://fi.wikipedia.org/wiki/Dispersio  --> materiaalidispersio ja geometrinen dispersio.
- https://termipankki.fi/tepa/fi/haku/dispersio --> muita merkityksiä, mm. biologiassa levintä/hajonta/dispersio 
- YSO: [hajonta ](http://www.yso.fi/onto/yso/p1879)- dispersion (mathematics and statistics)

Yksikkö-monikko tapauksia:  https://github.com/NatLibFi/Finto-data/issues/536

**Comment by mirmaid** [comment]
Muutamia kertoja käytetty fysiikan/elektroniikan yhteydessä todennäköisesti väärin - vaikea ilman aineistoa olla ihan varma tästä. Periaatteessa monikon pitäisi kertoa, että kyse ei ole fysiikan ilmiöstä vaan kemian seoksista. En ole ihan varma auttaako edes tarkenne tässä, jos kuvailija ei ole tarkkana tai muuten tunne aihetta. 

Voidaan siis lisätä dispersiot (kemia) tai jättää ilman tarkennetta. Fysiikan yhteydessä useita, en osaa sanoa kannattaako ottaa dispersio (fysiikka)...https://en.wikipedia.org/wiki/Dispersion. Melindassa näyttäisi olevan jokunen optiikkaan kuuluva ja yksi jossa aiheena on dielektrinen dispersio.

**Comment by ilona-x** [comment]
Voisiko tarkenne olla yläkäsite eli dispersiot (seokset)? Luulisi, että seokset-tarkenne herättäisi hätäisemmässäkin kuvailijassa epäilyksen, että termi ei ole oikea fysiikan ilmiön yhteydessä.

**Comment by mariaforsen** [comment]
Jos tarkoitus on että käytetään vain seos-merkityksessä niin kannatan tarkennetta (seokset). Tarvitaan ainakin ruotsiksi.. https://svenska.se/tre/?sok=dispersion&pz=8

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään tarkenne dispersiot (seokset).
