### ISSUE TITLE
valjakkourheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9261]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[valjakkourheilu](http://www.yso.fi/onto/ysa/Y107773) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Käytetty myös valjakkoajosta. Lisätään tarkenne tälle, ja/tai ohjaustermi valjakkoajolle. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Ruotsiksi ja englanniksi voisi lisätä ohjaustermejä valjakkoajolle, vrt. wikipedia.

**Comment by mariaforsen** [comment]
Kannatan tarkennusta.
Valjakkoajon ruotsin vastine muutetaan? > sportkörning (ridsport), körning (ridsport), körsport (ridsport) https://www.ridsport.se/Grenar/sportkorning Riippuen mihin tarkalleen suomenkielinen termi viittaa.

**Comment by mirmaid** [comment]
^ Juuri tuohon viittaa, Melindassa tosin taas luovaa artikkelikuvailua...

**Comment by mirmaid** [comment]
Pitäisikö lisätä tarkenne myös valjakkoajolle (hevosurheilu). Ei porot, eikä varsinaisesti myöskään kaupungeissa turisteja ajeluttavat hevosvaljakot.

**Comment by mariaforsen** [comment]
Valjakkoajolle nimenomaan myös tarkenne, jotta saadaan selkeä merkitysero koirat vs. hevoset ja sen mukaiset vastineet ruotsiksikin.

**Comment by YSO-kokous** [comment]
LIsätään tarkenteet: valjakkoajo (hevosurheilu) ja valjakkourheilu (koiraurheilu)

**Comment by mariaforsen** [comment]
Sv. spannkörning > körning (hästsport) ET sportkörning, körsport 
Avser en viss gren med tre moment: dressyr, maraton, precision
https://www.ridsport.se/globalassets/svenska-ridsportforbundet-gotlands-ridsportforbund/bilder/korning/vad-ar-korning.pdf
https://hastsverige.se/hast-manniska/anvandningsomraden/ridsport/korning/
http://www.topdriving.org/sv/valjakkoajo
https://termipankki.fi/tepa/fi/haku/valjakkoajo
https://www.ridsport.se/Grenar/sportkorning
https://sv.wikipedia.org/wiki/K%C3%B6rning_(ridsport)
