### ISSUE TITLE
ulkomaalaisvalvonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9262]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ulkomaalaisvalvonta

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://poliisi.fi/ulkomaalaisvalvonta

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Laittoman maahantulon torjunnan arviointiraportti : vuosi 2014.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ulkomaalaisvalvonta](http://finto.fi/yse/fi/page/Y509262)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. utlänningsövervakning
