### ISSUE TITLE
Uhta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9264]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Uhta 

#### Ehdotettu termi englanniksi   

Ukhta 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://sv.wikipedia.org/wiki/Uchta 

#### Perustelut ehdotukselle   

On kaupunki Komin tasavallassa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Melindassa 

**Termiehdotus Fintossa:** [Uhta](http://finto.fi/yse/fi/page/Y509264)

**Comment by mirmaid** [comment]
YK Venäjä vai Komi? Muutetaanko hierarkiaa kuten Yhdysvalloille?

**Comment by mirmaid** [comment]
Voidaan tehdä tarkempi hierarkia helpoissa tapauksissa.
