### ISSUE TITLE
Vanjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9265]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Vanjoki](http://www.yso.fi/onto/ysa/Y108045) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Vanjoki (Vihti)

**Comment by mirmaid** [comment]
Vanjoki on joki Vihdissä. Myös Karjaanjoen Vihdin alueella olevaa alajuoksua nimitetään Vanjoeksi. Tarkoitettaessa Vanjoki-nimistä kylää Vihdissä käytä muotoa Vanjoki (Vihti).

Eli toinen muutettava Vanjoki (Vihti : kylä)

Joki: http://paikkatiedot.fi/so/1000772/10064661, http://paikkatiedot.fi/so/1000772/10078201
Vähän sekavaa, jos meillä Vanjoki viittaa vain pohjoisen latvahaaran alajuoksuun ja muuten koko kokonaisuus on Karjaanjoki (myös siis osuus Karkkilan Pyhäjärvestä Hiidenveteen) ja Paikkatietoalustalla on erotettu latvahaara (Karjaanjoki/Vanjoki) ja Lohjanjärven alapuolinen Mustionjoki/Karjaanjoki. En tiedä mikä mahtaa olla tuo "joki Vihdissä".

**Comment by mirmaid** [comment]
Vanjoki KT Karjaanjoki (Vihti), Mustionjoki (Vihti), Karjaanjoki (Karkkila)
Karjaanjoki > Mustionjoki KT Karjaanjoki (Raasepori)

Korjataan linkit.
