### ISSUE TITLE
Koli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9267]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Koli](http://www.yso.fi/onto/ysa/Y105748) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Koli (Lieksa)

**Comment by jarmosaarikko** [comment]
Voikohan Kolin vaaran vaihtaa johonkin sen huipuista esim. Ukko-Koli?  Muita ovat Akka-Koli, Paha-Koli tai Pieni-Koli.  Vai pitäisikö näiden olla ohjaustermeinä käsitteelle **Koli (Lieksa : kohouma)** ja tuo toinen Koli olisi **Koli (Lieksa : kylä)**?

**Comment by mirmaid** [comment]
Koli (Lieksa : vaara)
Koli (Lieksa : kylä)
