### ISSUE TITLE
Kråkskär

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9268]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Kråkskär](http://www.yso.fi/onto/ysa/Y173436) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Muitakin samannimisiä

**Comment by mirmaid** [comment]
Melindan viite 2 on tämä: http://paikkatiedot.fi/so/1000772/10277508. Kaiketi virheellisesti tietueessa myös Saaristomeren kansallispuisto. 1 ja 3 ovat melko varmasti tämä http://paikkatiedot.fi/so/1000772/10308475, se sijaitsee Kihdillä ja on Paraisten Kråkskäreistä suurin. Myös krouvi on ollut siellä. Mikä tarkenne?

**Comment by mirmaid** [comment]
Toisen tarkenne Österskärs fjärden.
