### ISSUE TITLE
absorptio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9269]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[absorptio](http://www.yso.fi/onto/ysa/Y100540) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitääkö jakaa tai muuttaa huomautusta? 

#### Perustelut ehdotukselle   

Huomautuksessa puhutaan aineesta, soveltuuko optiikkaa tai hiukkasfysiikkaan? https://termipankki.fi/tepa/fi/haku/absorptio 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Jos kyseessä on aina jonkinlaista imeytymistä (kuten lukee TEPAssa ja esim. https://fi.wikipedia.org/wiki/Absorptio) niin huomautuksen laajentaminen riittänee?

**Comment by mirmaid** [comment]
Huomautettu myös, että _absoprtiolla_ ja _imeytymisellä_ on sama vastine englanniksi.

**Comment by mariaforsen** [comment]
Tilanne vastaava ruotsiksi, eli on ongelma että sanastossa on sekä absorption että uppsugning.

SAOssa on: absorption, absorption (värmelära), absorption (optik). 

MESH: https://mesh.kib.ki.se/term/D000042/absorption Jos kyseessä on ravintoaineiden imeytyminen niin ruotsiksi käytettäisiin näringsupptagning (fi. ravinnonotto YSOssa)

Ruotsin kannalta päätermi olisi absorption ja ohjausterminä uppsugning. 

Kielitoimiston sanakirja: "absorptio =imeytyminen, imeytys, pidätys" .. eli olisiko myös suomen kannalta korrektia yhdistää ja/tai mahdollisesti jakaa?

**Comment by jarmosaarikko** [comment]
Tieteen termipankki
- [Biologia:absorptio](https://tieteentermipankki.fi/wiki/Biologia:absorptio)
  1. aineen imeytyminen johonkin materiaaliin
  2. ravintoaineiden imeytyminen eläimen elimistöön tai ravinteiden imeytyminen kasvien soluihin tai soluelimiin 
- [Geofysiikka:absorptio](https://tieteentermipankki.fi/wiki/Geofysiikka:absorptio)
  1. säteilyenergian imeytymistä aineeseen
- [Ympäristötieteet:absorptio](https://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:absorptio)
  1. Nesteen tai kaasun imeytyminen kiinteään aineeseen tai nesteeseen. 
- [Tähtitiede:absorptio](https://tieteentermipankki.fi/wiki/T%C3%A4htitiede:absorptio)
  1.  Absorptiossa atomiin osuu fotoni, joka tuhoutuu ja luovuttaa energiansa atomille. Atomi virittyy korkeampaan energiatilaan. Absorption vastakohta on emissio.

Alla oleva käsite ei tainnut tulla esiin aiemmin: --- Voisiko myös lisätä sanastoon samalla kerralla:
- **absorptio (psykologia)** - Absorption (psychology) - https://en.wikipedia.org/wiki/Absorption_(psychology)  
  - a disposition or personality trait in which a person becomes absorbed in their mental imagery, particularly fantasy.[1] 
- **kognitiivinen absorptio** - cognitive absoption  KT CA, deep involvement ---  Todennäköisesti sama käsite?
  - kts. [Cognitive absorption in work-related information system usage](http://epub.lib.aalto.fi/en/ethesis/pdf/13027/hse_ethesis_13027.pdf)  (pro gradu)

**Comment by mirmaid** [comment]
_Absorptio_ käytetty Melindassa 155 kertaa, lähinnä fysiikan ja kemian alan julkaisuissa. _Imeytyminen_ käytetty 289 kertaa: lääkkeen imeytyminen, ravitsemus, veden imeytyminen maaperään.

**Comment by mirmaid** [comment]
Voisikohan yksi olla _imeytyminen (aineenvaihdunta)_ KT imeytyminen (lääkkeet), imeytyminen (ravitsemus) jne. Tulee kyllä aika lähelle kemiaa. Absorptio kuulostaa aika vieraalta silloin kun kyse on tulva-/hule- jne. vesien hallinnasta, mahdollinen voisi olla _imeytyminen (hydrologia)_?

**Comment by mirmaid** [comment]
Vähän epäilen, ettei kemian ja fysiikan absorptiossa oikeasti ole aina kyse samasta ilmiöstä, wikipedia: 
https://en.wikipedia.org/wiki/Absorption_(chemistry)
https://en.wikipedia.org/wiki/Absorption_(electromagnetic_radiation)

**Comment by ilona-x** [comment]
FinMeSH: 
imeytyminen KT absorptio http://www.yso.fi/onto/mesh/D000042
ST   fysikaalis-kemiallinen imeytyminen
ST   fysiologinen imeytyminen

**Comment by YSO-kokous** [comment]
### Päätökset

Tutkitaan edelleen YSOn infiltraatio = infiltration käyttöä veden imeytymisessä  vrt. imeytyminen (hydrologia)

**Comment by FinMeSHienPaimentaja** [comment]
Vertailun vuoksi MeSH-termeissä absorptiota/imeytymistä esiintyy mm. seuraavasti, kun haettu termejä, joissa "*absorp":

+  Absorptiometry, Photon  fotoniabsorptiotekniikka
+  Absorption  imeytyminen
+  Absorption, Physicochemical  fysikaalis-kemiallinen imeytyminen
+  Absorption, Physiological  fysiologinen imeytyminen
+  Absorption, Radiation  säteilyn imeytyminen
+  Fluorescent Treponemal Antibody-Absorption Test  FTA-ABS-testi
+  Gastric Absorption  imeytyminen mahalaukusta
+  Gastrointestinal Absorption  gastrointestinaalinen imeytyminen
+  Intestinal Absorption  suolistoimeytyminen
+  Intestinal Reabsorption  intestinaalinen reabsorptio
+  Intramuscular Absorption  intramuskulaarinen imeytyminen
+  Lactose Intolerance  laktoosi-intoleranssi
+  Malabsorption Syndromes  imeytymishäiriöt
+  Nasal Absorption  nasaalinen imeytyminen
+  Ocular Absorption  imeytyminen silmästä
+  Oral Mucosal Absorption  imeytyminen suun limakalvolta
+  Peritoneal Absorption  peritoneaalinen imeytyminen
+  Rectal Absorption  rektaalinen imeytyminen
+  Renal Reabsorption  renaalinen reabsorptio
+  Respiratory Tract Absorption  imeytyminen hengityselimistä
+  Skin Absorption  iholta imeytyminen
+  Spectrophotometry, Atomic  atomiabsorptiospektrofotometria
+  Subcutaneous Absorption  ihonalainen imeytyminen
+  Vaginal Absorption  vaginaalinen imeytyminen
+  X-Ray Absorption Spectroscopy  röntgensädeabsorptiospektroskopia

**Comment by mirmaid** [comment]
_Infiltraatio_ on 00-termi, mutta käytetty Melindassa vain 5 kertaa, vaikka se on ollut sanastossa vuodesta 2010. Kuulostaa varmaan liian tekniseltä, jotta uskallettaisiin käyttää. Viidestä kerrasta kolmessa kyse on veden imeytymisestä. Toisaalta tässä on myös usein aspektina veden suodattuminen (saadaan pohjavettä > juomavettä), eikä pelkästään vesimäärien "hallinta".

**Comment by mariaforsen** [comment]
Sv. infiltration on svenska.se:n mukaan "omärkligt eller gradvis in­trängande av främmande element, spec. i organism". NE:ssa useita eri merkityksiä, mm. "inom hydrologin vattnets nedträngande i marken".

https://termipankki.fi/tepa/fi/haku/infiltraatio
https://fi.wikipedia.org/wiki/Infiltraatio

Ruotsiksi pitäisi ehkä olla ohjauksena infiltration (innästling) ANV innästling (fi. soluttautuminen)
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_ad1859f8e0c834d8b95482431c12d947&list_id=1&keyword=soluttautuminen&word=soluttautuminen

**Comment by mirmaid** [comment]
Ehdotan, että ei käsitellä tässä nyt infiltraatiota, en usko että se varsinaisesti vie asiaa eteenpäin. Tuntuu, että mahdollisesti ainoa tapa on ketjutyylinen jako, eli toteutetaanko sellainen nyt vaikka puoliväkisin aloittamalla tuosta _imeytyminen (aineenvaihdunta)_ (tai (fysiologia) MeSHin tapaan)?

Vai halutaanko lähteä yhdistämään kaikki (olisiko silloin sitten absorptio huolimatta siitä, että joissain yhteyksissa kuulostaa erikoiselta)?

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen puolella siis kyse on elimistöön tavalla tai toisella imeytymisestä. Vierastan kuitenkin tuota _imeytyminen (aineenvaihdunta)_ eikä _imeytyminen (fysiologia)_ sekään minusta käy tähän yhteyteen. Voisiko olla yksinkertaisesti _imeytyminen (elimistö)_...?

**Comment by YSO-kokous** [comment]
**Päätös**

Käsitteet yhdistetään. Päätermi _imeytyminen_, ohjaustermi _absorptio_.

**Comment by mariaforsen** [comment]
Sv. absorption HT uppsugning
