### ISSUE TITLE
avoin tiede

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9270]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

avoin tiede

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

open science

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Avoin_tiede

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [avoin tieto](http://www.yso.fi/onto/yso/p26655)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://doi.org/10.23847/978-952-599516-9

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [avoin tiede](http://finto.fi/yse/fi/page/Y509270)

**Comment by jarmosaarikko** [comment]
- https://www.wikidata.org/wiki/Q309823
- **öppen vetenskap** [https://avointiede.fi/sv](https://avointiede.fi/sv)

**Comment by mirmaid** [comment]
12 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. öppen vetenskap
