### ISSUE TITLE
Komion luonnonsuojelualue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9271]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Komion luonnonsuojelualue 

#### Ehdotettu termi ruotsiksi   

Komio naturskyddsområde 

#### Ehdotettu termi englanniksi   

Komio Nature Reserve 

#### Ehdotettu yläkäsite YSOssa (LT)   

[luonnonsuojelualueet](http://www.yso.fi/onto/yso/p1371) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560) 
[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526) 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Maakylän-Räyskälän alueen kansallispuiston hoito- ja käyttösuunnitelma 

**Ehdottajan organisaatio:** SN/KK **Termiehdotus Fintossa:** [Komion luonnonsuojelualue](http://finto.fi/yse/fi/page/Y509271)

**Comment by jarmosaarikko** [comment]
- http://paikkatiedot.fi/so/1000772/10895483
- Kunta Loppi
