### ISSUE TITLE
spektroskopia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9273]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[spektroskopia](http://www.yso.fi/onto/ysa/Y99021) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö tämän olla spektrianalyysin alakäsite? 

#### Perustelut ehdotukselle   

Esim. LCSH:ssa on vain yksi käsite. Vastaavaa myös suppeammissa -skopia/-metria -käsitteissä. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
SAOssa molemmat ja RT-suhde näiden välillä.
svenska.se:
-spektroskopi: (läran om) under­sökning av spektrum och dess ut­nyttjande för studiet av materiens struktur 
-spektralanalys: analys och fast­ställande av ett ämnes kemiska bestånds­delar, med hjälp av dess spektrum
Ks. myös Nationalencyklopedin. 
https://sv.wikipedia.org/wiki/Spektroskopi
https://sv.wikipedia.org/wiki/Spektralanalys

**Comment by mirmaid** [comment]
Ei näitä ehkä uskalla yhdistää, vaikka ei oikein ymmärrys riitä, mitä kaikkia merkityksiä tässä on, https://en.wikipedia.org/wiki/Spectral_analysis.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
