### ISSUE TITLE
turvapalvelut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9274]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[turvapalvelut](http://www.yso.fi/onto/ysa/Y99697) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vrt. turvallisuuspalvelut. Jos halutaan rajata käyttöä, tarvitaan tarkenne. 

#### Perustelut ehdotukselle   

Ks. myös huomautus (Lähde: Sosiaaliturvan sanasto) 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
KELAn [Toimeentulotuen ohjeissa](https://www.kela.fi/documents/10192/3464829/Toimeentulotuki.pdf) on maininta mitä sen mukaan turvapalvelut ovat:
- **Turvapalvelut** (turvapuhelin, turvaranneke ja hälytyskäynnit), kun käytölle on todettu
terveysperuste ja maksu peritään kunnan asiakasmaksun yhteydessä tai kunnan
ostopalveluntuottajan laskuttamana.
- [Termipankki: turvapalvelu](https://termipankki.fi/tepa/en/search/turvapalvelu)

eng käännös: **safety services**

Olisiko tarpeen tarkenteella erottaa turvapalvelut (sosiaalipalvelut) vartiointiyritysten tarjoamasta turvapalvelusta "security service" liittyen rikosten estämiseen sekä valtion turvapalveluista "state security service"/"national security service" ?

**Comment by mariaforsen** [comment]
Kannatan selkeää erottelua eli tarkenteiden lisäämistä.

**Comment by mirmaid** [comment]
Olisiko siis
turvapalvelut (sosiaalipalvelut/kotihoito)

_Turvallisuuspalvelut_ käytetty melko laajasti, siihen ei ehkä tarkennetta saa/tarvitse. (KT turvapalvelut (rikosten torjunta)?)

**Comment by LeKorsu** [comment]
Minä miettisin tarkenteet kaikille, mutta onko Melindassa iso työ eritellä? Ja mikä olisi hyvä noille vartiointipalveluille ja hälytyslaitteille?
turvallisuuspalvelut (sosiaalipalvelut) KÄ turvapalvelut (sosiaalipalvelut)
turvallisuuspalvelut (valtiot) KÄ tiedustelupalvelut (tai turvallisuuspoliisi)
turvallisuuspalvelut (vartiointi / laitteet??)  KÄ turva-alan palvelut ????
Tuo viimeinen vain siksi että ysossa turvallisuusala KÄ turva-ala

**Comment by YSO-kokous** [comment]
**Päätökset**
Lisätään tarkenne: **turvapalvelut (kotihoito)**
turvallisuuspalvelut (kotihoito) KÄ turvapalvelut (kotihoito)
Säilytetään ilman tarkennetta: turvallisuuspalvelut
