### ISSUE TITLE
Koillis-Suomi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9275]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Koillis-Suomi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Nälkämailta : kuvia ja havaintoja Koillis-Suomesta nälkävuodelta 1902 / kirjoittanut Kalle Kajander 

#### Perustelut ehdotukselle   

60 kertaa Melindassa 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Koillis-Suomi](http://finto.fi/yse/fi/page/Y509275)

**Comment by mirmaid** [comment]
Mitenkäs tämän ja vastaavien suhteet?

**Comment by ilona-x** [comment]
Melindassa muussa kuin artikkeliaineistossa vain 14 kertaa.

YSO-paikat linjauksissa: "Sanastoon ei auktorisoida maiden osia, jotka on muodostettu ilmansuunnasta ja maan nimestä (esim. Itä-Viro, Pohjois-Ranska), elleivät nämä ole osa kyseisen maan virallista hallinnollista jakoa. Poikkeuksia voidaan tehdä, jos tällainen alueen nimi on selkeästi vakiintunut käyttöön ja usein kuvailussa tarvittu." https://www.kiwi.fi/display/Finto/YSO-paikat

Sanastossa on nyt väli-ilmansuunta-Suomi-termejä: Lounais-Suomi & Kaakkois-Suomi, mutta nämä vaikuttavat olevan vakiintuneempia: esim. Kaakkois-Suomen ELY-keskus & Lounais-Suomen aluehallintovirasto, mutta Koilllis-Suomen osalta ei näytä löytyvän mitään vastaavia. 

Ja vielä Melinda-luvut näille YSO-termeille: Lounais-Suomi x 885 ja Kaakkois-Suomi x 899

**Comment by mirmaid** [comment]
YK kaikille Suomi. Kaakkois-Suomelle RT-suhteet.
