### ISSUE TITLE
letkajenkka (tanssit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9277]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

letkajenkka (tanssit) 

#### Ehdotettu termi englanniksi   

bunny hop 

#### Ehdotettu termi ruotsiksi   

letkajenkka (danser) / letkis (danser) / ? 

#### Vaihtoehtoiset termit ja ilmaisut   

letkis (tanssit) 
 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssilajit](http://www.yso.fi/onto/yso/p3046) 

#### Assosiatiiviset (RT)   

[conga (tanssit)](http://www.yso.fi/onto/yso/p29829) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q4997884 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Tarkoitusta täsmentävä selite   

San Franciscossa vuonna 1952 congasta kehitelty tanssi, joka Suomessa nousi suureen suosioon Rauno Lehtisen säveltämän Letkis-tanssi-iskelmän (1963) siivittämänä ja joka sen myötä tunnetaan nimillä letkajenkka ja letkis. 

#### Perustelut ehdotukselle   

Letkajenkasta on Finnassa paljon aineistoa, niin tekstiä kuin kuvia, eikä kyseistä tanssia voi missään nimessä kuvailla asiasanalla "jenkka (tanssit)", kun kyseessä ei ole jenkka. – Ruotsinkielisen muodon osalta vrt. esim. https://digi.kansalliskirjasto.fi/sanomalehti/binding/1782829?term=letkajenkka&term=letkis&page=16 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/013725985 jne. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [letkajenkka (tanssit)](http://finto.fi/yse/fi/page/Y509277)

**Comment by jarmosaarikko** [comment]
Wikidata: https://www.wikidata.org/wiki/Q1859644 - eri kuin "bunny hop" https://www.wikidata.org/wiki/Q4997884

**Comment by mirmaid** [comment]
6 viitettä Melindassa eri muodoissa. ^ Kuulostaa kyllä ihan samalta kuin bunny hop?

**Comment by mariaforsen** [comment]
Wikipediasta:
"The steps of Letkajenkka are like the steps of Bunny Hop, a novelty dance from the 1950s. It has been proposed that exchange students returning from the United States to Finland would have imported the steps of the Bunny Hop to Finland, as they had seen them on the TV show Bandstand. Whereas the Bunny Hop starts with a right foot lead, the Letkajenkka / letkajenkka transformed into a dance based on the same step, but starting with a left leg lead. "

"Letkajenkka eli Letkis kuuluu tanssina festivaalimarssien tai conga line -jonotanssien joukkoon. Samaan joukkoon kuuluu myös Letkajenkka-tanssin esikuva Bunny Hop."

Sv. letkajenkka, letkajenka

**Comment by mirmaid** [comment]
^ Mutta bunny hopin esittelyssä sanottiin taas, että aloitetaan vasemmalla jalalla :slightly_smiling_face:.

**Comment by mariaforsen** [comment]
Sv. letkajenkka ET letkajenka, letkis (danser), slängschottis
