### ISSUE TITLE
Tulivuorirock

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9278]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tulivuorirock 

#### Vaihtoehtoiset termit ja ilmaisut   

Tulivuorijuhlat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[musiikkijuhlat](http://www.yso.fi/onto/yso/p1482) 

#### Alakäsitteet (RT)   

[musiikki](http://www.yso.fi/onto/yso/p1808) 
[musiikkijuhlat](http://www.yso.fi/onto/yso/p1482) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Finna 

#### Perustelut ehdotukselle   

Lappajärven Halkosaaressa 1970-luvulta vuoteen 1988 järjestetty rockfestivaali ja uudeleen vuosina 2007-2016. Oli aikanaan merkittävimpiä rockfestareita Suomessa 1980-luvun puoleen väliin saakka. 

**Termiehdotus Fintossa:** [Tulivuorirock](http://finto.fi/yse/fi/page/Y509278)

**Comment by jtuohini** [comment]
Ja erisnimisenä tapahtumana tämäkin kuuluu Kantoon, ei Ysoon.

**Comment by fantsby-m** [comment]
Ruisrock, Ankkarock, Ilosaarirock ja lukuisat muut rockfestivaalit löytyvät useista ontologioista Fintossa, mutta eivät vielä Kantosta, joten: ?

**Comment by MUUSA-kokous** [comment]
Kannatetaan lisäämistä Kantoon, jos tälle on tarvetta aineiston kuvailussa.

**Comment by fantsby-m** [comment]
Täältä alakäsitteet sitten myös Kantoon ja pois YSOsta?
https://finto.fi/yso/fi/page/p5106

**Comment by ilona-x** [comment]
Aiemmin on käsitelty Tuska-festivaalia ja käsittely on yhä kesken: [Tuska (festivaali)](https://github.com/Finto-ehdotus/YSE/issues/6498#)

**Comment by mirmaid** [comment]
Ehdotus koskee toimijan nimeä, viesti on välitetty Kansalliskirjaston toimijakuvailupalveluun ([katso yhteystiedot](https://www.kiwi.fi/x/m4GQB)).
