### ISSUE TITLE
kairat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9282]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kairat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Museotyössä tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esineluettelointi

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kairat](http://finto.fi/yse/fi/page/Y509282)

**Comment by mirmaid** [comment]
MAOssa, 27 viitettä Melindassa. Vaatiiko tarkenteen? Toisaalta jos kaira voi olla myös = pora, riittäisikö _jääkairat_? Melindan viitteissä yhtä lukuunottamatta kyse on niistä.

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9174

**Comment by mariaforsen** [comment]
Pelkkä kaira olisi =borr, mutta se on jo sanastossa =porat. Tarkennusta tarvitaan.

**Comment by YSO-kokous** [comment]
Hyväksytään muodossa **jääkairat**

**Comment by mariaforsen** [comment]
Sv. isborrar
