### ISSUE TITLE
Gruyère (Sveitsi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9283]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Gruyère (Sveitsi) 

#### Ehdotettu termi ruotsiksi   

Gruyère (Schweiz) 

#### Ehdotettu termi englanniksi   

Gruyère (Switzerland) 

#### Vastaava käsite muussa sanastossa   

LCNAF/LCSH : <http://id.loc.gov/authorities/names/n84057848> 
Wikidata : https://www.wikidata.org/wiki/Q388306 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/001771303 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Gruyère (Sveitsi)](http://finto.fi/yse/fi/page/Y509283)

**Comment by mirmaid** [comment]
Onko kyseessä siis nimenomaan _Gruyèren alue_, eikä kaupunki _Gruyères_: https://fi.wikipedia.org/wiki/Gruy%C3%A8res_(Sveitsi)? Mietin vaan, kannattaako kantoneiden hallintoalueita ottaa erikseen sanastoon. 
https://en.wikipedia.org/wiki/Districts_of_Switzerland

**Comment by mirmaid** [comment]
https://de.wikipedia.org/wiki/Greyerz_FR

**Comment by jtuohini** [comment]
Alueesta ehdotuksessa on kyse, ei kaupungista.
 
Mainitun aineiston kuvailussa riittäisi kyllä kantonitasokin, mutta YSO:ssapa on sekatietue, joka edustaa yhtä aikaa sekä kaupunkia että kantonia – eli aidosti siis ei kumpaakaan, ks. [**Fribourg**](http://www.yso.fi/onto/yso/p112668).

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9416

**Comment by mirmaid** [comment]
Korjataan Fribourg.
