### ISSUE TITLE
seksuaalinen käyttäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9285]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[seksuaalinen käyttäytyminen](http://www.yso.fi/onto/ysa/Y98766) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Onko teillä tarkoituksella 'seksikäyttäytyminen' ohjausterminä kahdelle termille (seksuaalinen käyttäytyminen ja sukupuolielämä)?
En tiedä, millainen periaate ohjaustermien suhteen YSOssa on käytössä, voihan olla, että ohjaustermi voi viitata kahteen eri päätermiin. Sinänsä asiallinen kummassakin. 

#### Perustelut ehdotukselle   

Päällekkäisyys vai ei?

**Comment by mirmaid** [comment]
Ok molemmissa? Sama ohjaustermi voi tosiaan olla useammalla kuin yhdellä käsitteellä.
