### ISSUE TITLE
Laakajärvi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9286]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Laakajärvi](http://www.yso.fi/onto/ysa/Y205604) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Sanastossa myös Laakajärvi (Sotkamo)

**Comment by mirmaid** [comment]
Muokattu myös > Laakajärvi (Sotkamo : kylä), koska osa järvestä kuuluu Sotkamoon.
