### ISSUE TITLE
Lankoori (Luvia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9287]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lankoori (Luvia)](http://www.yso.fi/onto/yso/p110721)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lankoori (Eurajoki)

**Perustelut ehdotukselle**

Kunta on nykyään Eurajoki

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Muutettu.
