### ISSUE TITLE
Lemlahti (Luvia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9288]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lemlahti (Luvia)](http://www.yso.fi/onto/yso/p113443)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lemlahti (Eurajoki)

**Perustelut ehdotukselle**

Kunta nykyään Eurajoki

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Muutettu.
