### ISSUE TITLE
gruyère (juusto)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9290]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

gruyère (juusto) 

#### Ehdotettu termi ruotsiksi   

gruyère (ost) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[juusto](http://www.yso.fi/onto/yso/p12240) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q2376488 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/012880655, https://melinda.kansalliskirjasto.fi/byid/013979408 jne. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [gruyère (juusto)](http://finto.fi/yse/fi/page/Y509290)

**Comment by mirmaid** [comment]
4 viitettä Melindassa, halutaanko tätä Pandoran lipasta avata?

**Comment by ilona-x** [comment]
nyt juuston (http://www.yso.fi/onto/yso/p12240) alakäsitteinä:
    feta
    leipäjuusto
    raejuusto
    sinihomejuusto
    sulatejuusto

**Comment by mirmaid** [comment]
gruyèrejuusto ja joitakin muita eniten käytettyjä?

**Comment by YSO-kokous** [comment]
Hyväksytään gruyèrejuusto KT gruyerejuusto  ja joitakin muita eniten käytettyjä Melindasta.

**Comment by mariaforsen** [comment]
Sv. gruyèreost ET gruyère
