### ISSUE TITLE
taltat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9292]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taltat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa keskeinen käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [37 Rakentaminen. Rakennusteollisuus. Talonrakennus. Maarakennus. Vesirakennus. Tienrakennus](http://www.yso.fi/onto/yso/p26568)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esineluettelointi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
MAOssa, 8 viitettä Melindassa.

**Comment by mariaforsen** [comment]
Sv. mejslar...? voi olla muutakin (mejsel, huggjärn, huggmejsel, håljärn, stämjärn, stämmejsel, lockbetel, stamp, stämverktyg, skrotmejsel)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: _terään päättyvä pitkänomainen työkalu, jota käytetään us. lyömällä sitä vasaralla tms._

**Comment by mirmaid** [comment]
Mejslar = meisselit

**Comment by ilona-x** [comment]
Ruuvimeisseli eli ruuvitaltta https://fi.wikipedia.org/wiki/Ruuvimeisseli (ruuvitaltat on YSOssa)

Mutta olisikohan tässä ehdotuksessa ennemmin kyseessä veistotaltat/puutaltat/puuntyöstötaltat/puusepän taltat ?
esim. https://www.plektratrading.fi/kasityokalut/puusepantaltat/c/21/

**Comment by ilona-x** [comment]
Stämjärn https://sv.wikipedia.org/wiki/St%C3%A4mj%C3%A4rn suomeksi sama: https://fi.wikipedia.org/wiki/Taltta

Wikipediassa mainittu puunveiston lisäksi kivenveisto: "Taltta on kivenveiston ja puunveiston tärkein työkalu."

**Comment by YSO-kokous** [comment]
Hyväksytään taltat  KT veistotaltat

**Comment by mariaforsen** [comment]
Sv. stämjärn
