### ISSUE TITLE
Länsiranta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9293]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Länsiranta](http://www.yso.fi/onto/yso/p193032)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa myös muita Länsirantoja

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Mikä tarkenne? Näyttää kyllä käytössä ongelmattomalta...

**Comment by mirmaid** [comment]
Länsiranta (Palestiina)
