### ISSUE TITLE
Mustijoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9294]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mustijoki](http://www.yso.fi/onto/yso/p116650)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa myös Mustijoki (Porvoo)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tarkenne vrt. Paikkatietoalusta (kaupunkialueen tai taajaman osa) vs. wikipedia (kylä).

**Comment by ilona-x** [comment]
Asutusnimihakemistossa kylä:
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=mustijoki

Samoin Porvoon kaupungin sivuilla:
https://www.porvoo.fi/asuminen-ymparisto/kaavoitus/yleiskaavat/kylarakenneohjelma/ 
-> https://www.porvoo.fi/app/uploads/2021/10/kylarakenneohjelma_ehdotus_liite1_fi_sv.pdf

**Comment by mirmaid** [comment]
Tarkenteeksi (Porvoo : kylä)
