### ISSUE TITLE
Nuottasaari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9296]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Nuottasaari](http://www.yso.fi/onto/yso/p162829)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

On monta muitakin samannimisiä Suomessa.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Myös Helsingissä kaksi.

**Comment by mirmaid** [comment]
Tarkenne (Helsinki, Santahamina)
