### ISSUE TITLE
Oulanka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9300]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Oulanka](http://www.yso.fi/onto/yso/p176085)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisi jakaa tai tarkentaa

**Perustelut ehdotukselle**

Oulanka on myös alue Suomessa, sekä kylä ja näin on käytetty virheellisesti Melindassa. Huomautus viittaa nyt Venäjään. 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
http://paikkatiedot.fi/so/1000772/10573566 - Oulangan kansallispuisto on erikseen YSOssa. Jos otetaan lisäksi Oulanka (Kuusamo), sitä varmaan helposti käytetään kansallispuistosta, eikä pelkästä pienestä kylästä (?). En osaa sanoa, onko kylästä aineistoa, pitäisi käydä kaikki viitteet läpi.

Venäjän puolen Oulanka ei ole kuulunut Suomeen, tarkenteeksi (Venäjä)? Tai (Karjalan tasavalta), jota on käytetty tarkenteena enemmän. Tässä nyt vähän hajontaa.

**Comment by mirmaid** [comment]
Korjataan kansallispuistoa koskevat viitteet ja katsotaan mitä jää jäljelle.

**Comment by mirmaid** [comment]
Tarkenteeksi Oulanka (Karjalan tasavalta); Jänisjärvi (Venäjä) > Jänisjärvi (Sortavalan piiri).
