### ISSUE TITLE
Rakkolanjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9303]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Rakkolanjoki](http://www.yso.fi/onto/yso/p168991)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa myös Rakkolanjoki (Vahviala)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Rakkolanjoki (joki) ja Rakkolanjoki (Vahviala : kylä)? Kyseessä luovutetun Karjalan kylä.

**Comment by mirmaid** [comment]
Rakkolanjoki (joki) ja Rakkolanjoki (Vahviala : kylä)
