### ISSUE TITLE
Vuolenkoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9309]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vuolenkoski](http://www.yso.fi/onto/yso/p185106)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne

**Perustelut ehdotukselle**

Sanastossa myös Vuolenkoski (Iitti)

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
paikkatiedot linkki on nyt vesistöön eikä kylään. 
Kylän linkki on :  [http://paikkatiedot.fi/so/1000772/10537492](http://paikkatiedot.fi/so/1000772/10537492)
