### ISSUE TITLE
tarinat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9312]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tarinat](http://www.yso.fi/onto/yso/p4990)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan suhteessa termiin kertomukset, lisätään määritelmiä ja/tai mahdollisesti yhdistetään

**Perustelut ehdotukselle**

Sanastossa (myös SLM:ssä) on sekä tarinat että kertomukset ja nämä ovat osittain synonymisia, ks. Kielitoimiston sanakirja. Tarinoiden vastine on kuitenkin sv. sägner ja tämä termi käytetäään nyt osittain virheellisesti Melindassa (käyttö sekava). Ks. myös TEPA. Nationalencyklopedin: sägen=kort folklig berättelse som vanl. innehåller övernaturliga inslag men ändå betraktas som i viss mån trovärdig  

**Ehdottajan organisaatio**

ALLFO

**Comment by jarmosaarikko** [comment]
MOT
**kertomus** : 
-  EN: (tarina) **story**, tale, erik kirjall narrative  |   (selonteko) account, (erik virallinen) report (jstak on)
-  SV: **berättelse**, _historia_, utsaga, historiett, story  |  skildring, relation | redovisning, redogörelse, rapport |  oik beskrivning

Alakäsite:  **tarina**:  
- EN: story, **tale** (jstak about/of), (eläintarina) fable, (myytti) myth   (faabelit ovat YSOssa satujen alakäsitteenä)
- SV: berättelse, historia, **sägen** ?

Kun nämä yhdistetään, niin kummitustarinat ja lännentarinat siirtyvät suoraan kertomusten alle mikä ei liene ongelma? Ohjausterminä voisi olla myös "tarut".  esim. "taru sormusten herrasta".

**Comment by mariaforsen** [comment]
Kyllä, kummitustarinat ja lännentarinat nimenomaan sopisivat kertomusten alle.

**Comment by mirmaid** [comment]
Jotenkin tuli sellainen aavistus, että tästä saattaa syntyä pitkä ja leveä keskustelu, mutta ehkä olen väärässä :slightly_smiling_face:.

**Comment by mirmaid** [comment]
^ Ei ainakaan vielä :sweat_smile:.

_Tarinat_ yso-käsitteenä 3041 kertaa, _kertomukset_ 6284.

**Comment by krinay** [comment]
Kansankertomukset, kansantarinat, kansansadut, myytit ja legendat alakäsitteineen on joka tapauksessa hyvä pitää ennallaan, niillä on omat merkityksensä ja käyttötarkoituksensa.

**Comment by ghost** [comment]
"Narratologiassa juoni on erotettu tarinasta sillä perusteella, että jos tarina on tapahtumasarja, josta kerrotaan, vasta juoni eli kerronta järjestää tapahtumasarjan kausaaliseksi ja teleologiseksi kokonaisuudeksi. Teemu Ikosen (2001) mukaan tarina on kertomuksen sisällön taso siinä missä kerronta on sen ilmaisun taso." https://tieteentermipankki.fi/wiki/Kirjallisuudentutkimus:tarina

https://www.fsd.tuni.fi/fi/palvelut/menetelmaopetus/kvali/teoreettis-metodologiset-viitekehykset/kertomuksen-tutkimus/

**Comment by mariaforsen** [comment]
Tämä virhetilanne näkyy jatkuvasti Melindan tietueissa, joten tarvitaan ratkaisua mahdollisimman pian.
Melindassa valitettavasti jo1642 kertaa sägner ja suurimmalle osalle näistä viitteistä sopisi siis kertomukset. Sägner ei siis sovi muihin kuin niihin tapauksiin, missä on kyse vanhoista kansantarinatyyppisistä tarinoista (EI esim. muumit, tai kenen vaan nykyhenkilön keksimät kertomukset, kuten nyt on laitettu Melindassa).

**Comment by mirmaid** [comment]
SLM-ryhmä kannatti varovaisesti yhdistämistä. Kertomukset enemmän käytetty, eli se päätermiksi (?).

**Comment by YSO-kokous** [comment]
**Päätös**

Kertomukset KT tarinat, tarinat poistuu.

Tarinoiden alakäsitteet siirtyvät kertomusten alakäsitteiksi.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
