### ISSUE TITLE
transvestismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9314]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[transvestismi](http://www.yso.fi/onto/yso/p3439)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi KT ristiinpukeutuminen 

**Perustelut ehdotukselle**

https://thl.fi/fi/web/sukupuolten-tasa-arvo/sukupuoli/tasa-arvosanasto https://fi.wikipedia.org/wiki/Transvestisuus 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Sanastossa on myös _ristiinpukeutuminen (esittävät taiteet)_. Eli tälle ehkä ristiinpukeutuminen (transvestismi).

**Comment by YSO-kokous** [comment]
Hyväksytään transvestismi KT ristiinpukeutuminen (transvestismi)
