### ISSUE TITLE
vankeinhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9315]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vankeinhoito](http://www.yso.fi/onto/yso/p12898)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sosiaalipalvelut-yläkäsitteen poisto vankeinhoito-käsitteeltä.

**Perustelut ehdotukselle**

Vankeinhoito ei ole koodistopalvelimella julkaistun Sosiaalihuolto -  Sosiaalipalvelut -luokituksen  https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=703&versionKey=2683 mukaan sosiaalipalvelu. Luokitusta päivitetään ja se pidetään ajantasaisena, joten luottaisin siihen. 

**Ehdottajan organisaatio**

THL

**Comment by jtuohini** [comment]
Koskeeko mainittu luokitus vain Suomea vai onko kyseessä yleinen (yleismaailmallinen)? Toisin sanoen: katsotaanko vankeinhoito muissa maissa tai ylipäänsä osaksi sosiaalipalveluja?

**Comment by mariaforsen** [comment]
Ks. myös https://termipankki.fi/tepa/fi/haku/vankeinhoito 

"vankeinhoito: "vankien ja vankilasta vapautuneiden tarpeita palveleva sosiaalihuollon alue"
Lähde: |   | Sosiaaliturvan sanasto"

**Comment by mirmaid** [comment]
Eri määritelmiä. Onko nykyään sama kuin kriminaalihuolto? Onko vankeinhoito oikeastaan historiallinen käsite?

**Comment by ilona-x** [comment]
mulla hyllyssä oleva tietosanakirja vuodelta 1993 kertoo vankeinhoidosta näin:

**vankeinhoito** oikeusministeriön vankeinhoito-osaston johtama hallinnonhaara. Keskusvankiloita seitsemän, lääninvankiloita kahdeksan, varavankiloita viisi, nuorisovankila Keravalla. Muita mm. työsirtolat, pakkolaitokset (keskusvankiloiden osastoja), vankien kurssikeskus (Sulkava) ja vankimielisairaala (Turku).
Lähde: Rantala, Risto. Tietosanakirja. 2. uud. laitos. Otava, 1993.

**Comment by ilona-x** [comment]
"Vuonna 2001 rangaistusten täytäntöönpanon organisaatio uudistettiin osana oikeusministeriön kriminaalipoliittisten tehtävien uudelleen järjestelyä. Tällöin lakkautettiin oikeusministeriön vankeinhoito-osasto ja perustettiin uusi keskusvirasto, Rikosseuraamusvirasto. "
Lähde: https://www.rikosseuraamus.fi/fi/index/rikosseuraamuslaitos/historiaa.html

**Comment by ilona-x** [comment]
Ja vielä Kielitoimiston sanakirjasta:
**vankeinhoito**
valtiovallan toiminta vankeusrangaistusten täytäntöönpanon järjestämiseksi. 
https://www.kielitoimistonsanakirja.fi/#/vankeinhoito?searchMode=all

**Comment by ilona-x** [comment]
YSAssa näköjään vankeinhoidon yläkäsitteenä on ollut oikeushallinto http://www.yso.fi/onto/ysa/Y100070

**Comment by mirmaid** [comment]
Myös _kriminaalihuolto_ on nyt sosiaalipalveluiden alla, ja siellä on paljon samanlaista termistöä. Toisaalta "huolto"-loppuiset voisivat varmaan olla myös _sosiaalihuollon_ alakäsitteitä ja vankeinhoito _hoidon_ alakäsite, jos halutaan siirtää. Tai takaisin oikeushallinnon alle? https://tieteentermipankki.fi/wiki/Oikeustiede:oikeushallinto

**Comment by LeKorsu** [comment]
Kriminaalihuolto kuulostaa minusta vanhentuneemmalta kuin vankeinhoito. Ja Rikosseuraamusvirastokin on nykyään Rikosseuraamuslaitos.  (Ysossa muuten rikosseuraamukset KÄ seuraamukset)
Mutta kannatan kyllä vankeinhoidon siirtämistä oikeushallinnon alle, jos nyt aluksi mennään sillä ennen kuin ruvetaan miettimään mahdollista tuoreempaa käsitettä asialle.

**Comment by mariaforsen** [comment]
SAOssa on kriminalvård HT fångvård https://id.kb.se/term/sao/Kriminalv%C3%A5rd

**Comment by mirmaid** [comment]
Toisaalta oikeushallinto on hallinnonalojen alla, ja siellä ei ole muita kuin hallinto-päätteisiä alakäsitteitä. Voisin kallistua siihen, että siirretään sekä vankeinhoito, että huolto-loppuiset sosiaalipalvelujen alakäsitteet sosiaalihuollon alle. Siellä on muuten nyt jo laitoshoito ja sen ST sairaalahoito.

**Comment by YSO-kokous** [comment]
**Päätös**

Tarkistetaan hierarkiaa yllä esitetyn mukaisesti.
