### ISSUE TITLE
fantasiasarjakuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9317]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fantasiasarjakuvat 

#### Ehdotettu termi englanniksi   

fantasy comics 

#### Ehdotettu termi ruotsiksi   

fantasyserier (tecknade serier) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sarjakuvat](http://www.yso.fi/onto/yso/p1148) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[80 Viestintä. Tiedonvälitys. Joukkoviestintä. Mainonta](http://www.yso.fi/onto/yso/p26547) 
[87 Kirjallisuus](http://www.yso.fi/onto/yso/p26564) 
[92 Kuvataide. Maalaustaide. Grafiikka. Kuvanveisto](http://www.yso.fi/onto/yso/p26569) 

#### Perustelut ehdotukselle   

Alla mainitussa teoksessa tutkimuksen kohteena mm. fantasiasarjakuvat. Käsite puuttuu YSO:sta, on SML:ssa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Fantasia : lajit, ilmiö ja yhteiskunta / Jyrki Korpua, Irma Hirsjärvi, Urpo Kovala & Tanja Välisalo (toim.) 

**Ehdottajan organisaatio:** Oulun kaupungin kirjasto **Termiehdotus Fintossa:** [fantasiasarjakuvat](http://finto.fi/yse/fi/page/Y509317)

**Comment by mirmaid** [comment]
Samoin monet muut KAUNOsta SLM:ään tulleet sarjakuvagenret. Liittyy myös tähän avoimeen issueen https://github.com/Finto-ehdotus/YSE/issues/7333.
