### ISSUE TITLE
vuoroviljely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9318]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vuoroviljely](http://www.yso.fi/onto/yso/p19441)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yhdistetään käsitteeseen viljelykierto.

**Perustelut ehdotukselle**

Kielitoimiston sanakirja: https://www.kielitoimistonsanakirja.fi/#/viljelykierto  maat. viljelykasvien vuorottelu jllak viljelyalalla,  KT vuoroviljely.

**Ehdottajan organisaatio**

Finto-palvelu

**Comment by jarmosaarikko** [comment]
Elleivät nämä ole sama käsite, niin mikä on ero?  
**vuoroviljely** | rotational cropping  | växelbruk  vs. **viljelykierto** crop rotation | växtföljd   --

- Tieteen termipankissa ne ovat samassa käsitteessä - https://tieteentermipankki.fi/wiki/Ymp%C3%A4rist%C3%B6tieteet:vuoroviljely lähde EnDic2004

- AFO:ssa  vuoroviljely | rotational cropping  http://www.yso.fi/onto/afo/p783   vs  viljelykierto http://www.yso.fi/onto/afo/p782

- Agrovocissa termit samassa käsitteessä  crop rotation KT rotational cropping  http://aims.fao.org/aos/agrovoc/c_6662  -- System of cultivation where different crops are planted in consecutive growing seasons to maintain soil fertility.

- wikidata https://www.wikidata.org/wiki/Q191258

- LCSH Crop rotation KT Rotation of crops   http://id.loc.gov/authorities/subjects/sh85034244

- MOT  "rotation" - 4 **maat** vuoroviljely, viljelykierto (myös crop rotation, rotation of crops, rotation of cultivation)

- Wikipediassa: https://fi.wikipedia.org/wiki/Viljelykierto  alkaa lauseella: **Viljelykierto eli vuoroviljely**[1] on maanviljelyä, jossa samalla pellolla viljeltävä kasvi vaihtuu peräkkäisinä vuosina (viittaus Kielitoimiston sanakirjaan)

**Comment by mirmaid** [comment]
Hyvin hämärä mielikuva, että tätä olisi joskus käsitelty. Näyttää kyllä, että olisivat päällekkäiset. _Vuoroviljely_ on vanha käsite, _viljelykierto_ lisätty 2006.

**Comment by mirmaid** [comment]
KT myös kasvinvuorottelu/-vuorotus

**Comment by mariaforsen** [comment]
SAOssa molemmat erikseen ja merkitykset tällä tavalla eri:
-växtföljd= ordningsföljd i vilken grödor odlas på en åker
-växelbruk= växtföljd där grödor av olika slag regelbundet växlar med varandra från år till år 
https://id.kb.se/term/sao/V%C3%A4xtf%C3%B6ljd
https://id.kb.se/term/sao/V%C3%A4xelbruk

**Comment by ilona-x** [comment]
Tuolle ruotsinkieliselle termille "växtföljd" löytyy Tepasta käännökset:

**fi        kasvien järjestys viljelykierrossa;**
kasvijärjestys
sv       växtföljd
en      crop succession

**fi        kasvinvuorotus**
sv       växtföljd


ja vielä tällainenkin:
fi        kasvuaika
sv       växtföljd 
en      crop cycle
crop growth cycle 

https://termipankki.fi/tepa/fi/haku/v%C3%A4xtf%C3%B6ljd

**Comment by YSO-kokous** [comment]
muutetaan  viljelykierto päätermiksi  kasvijärjestys (vuoroviljely)
vuoroviljely KT kasvinvuorotus,  kasvien vuorottely
