### ISSUE TITLE
Sirottimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9319]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Sirottimet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esineluetteloinnissa tarvittava käsite

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Museoesineet

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Sirottimet](http://finto.fi/yse/fi/page/Y509319)

**Comment by jarmosaarikko** [comment]
sv: ströaren KT spridaren, (saltströaren, bordsaltströaren, pepparströaren)
en: condiment dispensers KT  shakers, caster, (alakäsitteistä: salt shakers, pepper shakers, salt cellars, salt casters, pepper casters)

- LCSH : http://id.loc.gov/authorities/subjects/sh2006004345 "Casters (Containers)"
- https://www.wikidata.org/wiki/Q96955718  caster

**Comment by mirmaid** [comment]
MAOssa, kerran Melindassa.

**Comment by mariaforsen** [comment]
Sv. ströare (ruok.) tai mahdollisesti spridare (tekn.) Mitä kaikkea tämän on tarkoitus kattaa?
https://svenska.se/so/?id=179983&pz=3

**Comment by mirmaid** [comment]
^ Varmaan museoaineistossa noita suola- ym. sirottimia. Itsekin miellän sen nimenomaan mausteisiin liittyväksi, mutta näköjään myös https://www.bauhaus.fi/sirotin-gardena.html ja jopa https://www.nettikone.com/salo/sirotin/1992354.

**Comment by YSO-kokous** [comment]
Oteaan YSOon muodossa sirottimet (astiat) YK astiat

**Comment by mariaforsen** [comment]
Sv. ströare
