### ISSUE TITLE
yhdyskuntajätteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9320]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yhdyskuntajätteet](http://www.yso.fi/onto/yso/p4748)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

tämän käsitteen ohjaustermit siirretään käsitteeseen "talousjätteet"

**Perustelut ehdotukselle**

asumisjätteet ja bostadsavfall  ovat molemmat talousjätettä

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Ohjaustermi on nyt suomeksi asumajätteet. Sekä sillä muodolla, että asumisjätteet, löytyy hyvin vähän mitään.

**Comment by YSO-kokous** [comment]
hyvksytään siirto. muutetaan termi muotoon  asumisjätteet KÄ talousjätteet

**Comment by mariaforsen** [comment]
Huomautuksessa puhutaan kaatopaikasta, nykyään parempi olisi varmaan puhua jätehuollosta. Ks. TEPA.
