### ISSUE TITLE
luokanvalvojat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9321]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[luokanvalvojat](http://www.yso.fi/onto/yso/p3512)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään KT-muodoksi luokanohjaajat

**Perustelut ehdotukselle**

https://termipankki.fi/tepa/fi/haku/luokanohjaaja

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Muutetaan samalla en: KÄ "class teacher" KT "homeroom teacher", "form master".   
Em. termipankin tietueen mukaan "tutor" termiä ei pitäisi käyttää tässä merkityksessä.

**Comment by mirmaid** [comment]
Tyttären lukiossa nimitys on "ryhmänohjaaja". Englanniksi tilanne ei ole yksinkertainen, koska class teacher tarkoittaa myös luokanopettajaa. Tutor on ehkä kuitenkin paras kompromissi, muuten tarvitaan mutkikkaita tarkenteita kuvaamaan mistä on kysymys suomalaisessa koulujärjestelmässä.

**Comment by YSO-kokous** [comment]
Hyväksytään KT luokanohjaajat, ryhmänohjaajat (luokanvalvojat)
