### ISSUE TITLE
surumarssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9322]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[surumarssit](http://www.yso.fi/onto/ysa/Y103429) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan SLM:ssä LT-suhde "musiikki" --> "marssit" ja "surumusiikki" 

#### Perustelut ehdotukselle   

Surumarssit ovat sekä marsseja että surumusiikkia, minkä pitäisi kuvastua termien välisestä suhteesta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytään muutokset.
