### ISSUE TITLE
häämarssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9323]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[häämarssit](http://www.yso.fi/onto/ysa/Y214501) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan SLM:ssä LT-suhde "musiikki" --> "häämusiikki" ja "marssit" 

#### Perustelut ehdotukselle   

Häämarssit ovat sekä häämusiikkia että marsseja, minkä pitäisi kuvastua termien välisestä suhteesta. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Hyväksytään muutokset.
