### ISSUE TITLE
purpurit (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9324]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[purpurit (sävellykset)](http://www.yso.fi/onto/ysa/Y104056) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään termille YSO:ssa olevat KT-muodot ja muutetaan LT-suhde "musiikki" --> "pelimannimusiikki" ja "tanssimusiikki" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja SLM:ssä termihän on ilman sulkutarkennetta (http://urn.fi/URN:NBN:fi:au:slm:s33).

**Comment by jtuohini** [comment]
Lisäksi RT [**sikermät**](http://urn.fi/URN:NBN:fi:au:slm:s146), ellei peräti LT-suhteeksi, joita purpurit musiikillisessa mielessä ovat peräkkäisten tanssisävelmien muodostamina sikerminä. Vrt. myös esim. https://melinda.kansalliskirjasto.fi/byid/017994010.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta ja RT-suhdetta sikermät.

**Comment by jtuohini** [comment]
Samasta esityksestä vanhempi versio: https://github.com/Finto-ehdotus/YSE/issues/9219

**Comment by mirmaid** [comment]
Hyväksytään muutokset. Lisäksi KT purppurit (myös YSO).

**Comment by mirmaid** [comment]
Pelimannimusiikki-käsitteellä ei ole muita alakäsitteitä, lisätäänkö muitakin kuin purpurit?

**Comment by jtuohini** [comment]
Muita ei taida olla lisättäväksi, kun tanssimusiikin osalta ilmaistu teoksen muoto (esim. **menuetit** ei ota kantaa, onko kyseessä taide- vai kansanmusiikin puolelle kuuluva teos). Ja pelimannimusiikki on pitkälti tanssimusiikkia.

**Comment by mirmaid** [comment]
LT-suhde ok.
