### ISSUE TITLE
laki yhteishallinnosta vuokrataloissa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9325]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

laki yhteishallinnosta vuokrataloissa

**Ehdotettu termi ruotsiksi**

lag om samförvaltning i hyreshus

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.finlex.fi/fi/laki/alkup/1990/19900649
Ehdotuksissa on myös yhteishallinto https://github.com/Finto-ehdotus/YSE/issues/282  ja yhteishallinta https://github.com/Finto-ehdotus/YSE/issues/1496, voisiko myös yhteishallinnon ottaa?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 yhteishallintolaki

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-11-4731-9

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Ja tämäkin ehdotettu "asiasana" viittaisi yksittäiseen teokseen ja tulisi RDA:n mukaan käsitellä tekijä-nimekekirjauksena…

**Comment by jarmosaarikko** [comment]
en: Act on Joint Management of Rental Buildings  - [https://www.finlex.fi/en/laki/kaannokset/1990/en19900649](https://www.finlex.fi/en/laki/kaannokset/1990/en19900649)

**Comment by mirmaid** [comment]
^^ Tämä on toki tiedossa. Nykytilanteessa ei varmaan ole järkevää muuttaa käytäntöä, kun ei oikein ole vaihtoehtoa auktorisoida muulla tavoin ja lait ovat kuitenkin selkeä kokonaisuus, joka on muutettavissa tarvittaessa myöhemmin. Laki siis ok.

**Comment by mirmaid** [comment]
Yhteishallinta/-hallinto, missä merkityksessä tarvittu, nimenomaan tähän samaan liittyen? Yhteishallintoa käytetään myös esim. kuolinpesistä, ja ilman tarkennetta varmaan helposti monessa muussakin yhteydessä. (Yhteishallinta usein luonnonvaroista ja maa-alueista.)

**Comment by ilona-x** [comment]
https://termipankki.fi/tepa/fi/haku/yhteishallinto

**Comment by YSO-kokous** [comment]
Hyväksytään lakikäsite.

Tutkitaan edelleen käsitettä asukasdemokratia KT yhteishallinto jää ehdotukseksi.  
poistuu  asukasdemokratia KÄ lähidemokratia

**Comment by mirmaid** [comment]
Myöskään _asukasdemokratia_ ei yksiselitteisesti rajaudu tähän yhteishallintoon vuokra-asumisessa, eikä termiä käytetä laissa. Asukasdemokratia voisi kyllä jäädä ohjaustermiksi lähidemokratialle tarkenteella varustettuna. Yhteishallintoa ei ole käytetty tässä merkityksessä Melindassa, Finnasta löytyy 2 viitettä. Mahdollinen ehkä yhteishallinto (asuminen/asukasdemokratia/asukkaat).

**Comment by YSO-kokous** [comment]
**Päätökset:** 
Ohjaustermi: asukasdemokratia (lähidemokratia) KÄ lähidemokratia
Hyväksytään käsite: yhteishallinto (asuminen) TAI  yhteishallinto (asukasdemokratia)  TAI  yhteishallinto (asukkaat).

**Comment by mariaforsen** [comment]
Sv. samförvaltning (boende)
