### ISSUE TITLE
reelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9327]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

reelit 

#### Ehdotettu termi englanniksi   

reels 

#### Ehdotettu termi ruotsiksi   

reeler / reels / ? 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kansanmusiikki](http://www.yso.fi/onto/yso/p2841) 
[tanssimusiikki](http://www.yso.fi/onto/yso/p181) 

#### Assosiatiiviset (RT)   

[kontratanssit (sävellykset)](http://www.yso.fi/onto/yso/p29808) 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014027043> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/017995039 ja muita 

#### Perustelut ehdotukselle   

Yleinen skottilainen tanssisävelmätyyppi, jolle ei vanhastaan löydy täsmällistä SLM-termiä. Vrt. ruotsinkielinen Wikipedia: "Som musik är reel numera den kanske vanligaste formen av brittisk "spelmansmusik", så kallade "fiddle tunes" (fiollåtar), vilken förekommer på Irland, i Skottland, England, Kanada och USA. Flera gamla reels har även letat sig in i bluegrassmusiken. Irländarna spelar musiken i snabbt tempo med mycket ornamentering, medan skottar och amerikaner ofta spelar lite långsammare och enklare." (https://sv.wikipedia.org/wiki/Reel) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 
[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Tämä siis SLM-ehdotus!

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Sv. reelar HT reel, reeler
https://id.kb.se/term/saogf/Reel

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mirmaid** [comment]
Entä YSO?

**Comment by jtuohini** [comment]
Voisi kelvata YSO:nkin puolelle, joskin käyttötarve kohtuullisen vähäinen. Äkkiseltään en löytänyt muita esimerkkitietueita Melindasta kuin https://melinda.kansalliskirjasto.fi/byid/002955145 (nuotteja ml. soitonoppaita ja äänitteitä kyllä löytyi, ja niihin siis tulee SLM-termi).

**Comment by YSO-kokous** [comment]
**Päätös:** Otetaan myös YSOon  **reelit**
