### ISSUE TITLE
nahkaveneet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9328]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

nahkaveneet 

#### Ehdotettu termi englanniksi   

skin boats 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

The bark canoes and skin boats of northern Eurasia 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu

**Comment by jtuohini** [comment]
LCSH-vastine: [**Skin boats**](http://id.loc.gov/authorities/subjects/sh86002985)

**Comment by jarmosaarikko** [comment]
aineistoesim. [https://melinda.kansalliskirjasto.fi/byid/000342682](https://melinda.kansalliskirjasto.fi/byid/000342682)  
wikidata: https://www.wikidata.org/wiki/Q63771697

**Comment by mariaforsen** [comment]
Sv. skinnbåtar
