### ISSUE TITLE
Surrey

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9329]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Surrey 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Surrey](http://finto.fi/yse/fi/page/Y509329)

**Comment by mirmaid** [comment]
Yläkäsite Englanti vai Iso-Britannia? Vrt. Yhdysvallat. Tuleeko tarkenteeksi Englanti?

**Comment by mirmaid** [comment]
Surrey (Englanti) ja järjestetään Iso-Britannia hierarkiaan.
