### ISSUE TITLE
bitcoin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9330]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

bitcoin 

#### Perustelut ehdotukselle   

Lisäksi Monero. Otetaanko yksittäisiä virtuaalivaluuttoja? Oikeita valuuttoja on muutamia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Bitcoin ja Monero : kryptovaluuttojen kuninkaat

**Comment by jtuohini** [comment]
LCSH-vastine: [**Bitcoin**](http://id.loc.gov/authorities/subjects/sh2015000075). Muita yksittäisiä kryptovaluuttoja ei ainakaan vielä ole auktorisoitu kyseiseen sanastoon.

**Comment by jarmosaarikko** [comment]
wikidata: https://www.wikidata.org/wiki/Q131723

**Comment by mirmaid** [comment]
Bitcoin on melko paljon käytetty Melindassa, Monero ei kertaakaan, Ethereum 4 viitettä, tosin virallisesti se ei viittaa itse valuuttaan (mutta käytetään myös siitä).

**Comment by mariaforsen** [comment]
Sv. bitcoin https://id.kb.se/term/sao/Bitcoin
