### ISSUE TITLE
Iranin vallankumous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9331]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Iranin vallankumous 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

esim. 9789198266917 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [Iranin vallankumous](http://finto.fi/yse/fi/page/Y509331)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Iran--History--Revolution, 1979**](http://id.loc.gov/authorities/subjects/sh86002666)

**Comment by jarmosaarikko** [comment]
https://www.wikidata.org/wiki/Q126065 
- fi: KT Iranin islamilainen vallankumous  
- sv: Iranska revolutionen  KT Islamiska revolutionen i Iran
- en:  Iranian revolution
- vaatiiko huomautuksen tai tarkenteen v. 1979?

**Comment by mariaforsen** [comment]
Sv. iranska revolutionen (1979) ET islamiska revolutionen 1979, islamska revolutionen 1979
https://id.kb.se/term/sao/Islamiska%20revolutionen%201979
