### ISSUE TITLE
kaivospiirit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9333]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaivospiirit 

#### Ehdotettu yläkäsite YSOssa (LT)   

[erityisalueet](http://www.yso.fi/onto/yso/p13700) 

#### Assosiatiiviset (RT)   

[kaivosalueet](http://www.yso.fi/onto/yso/p26256) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85085710> 

#### Tarkoitusta täsmentävä selite   

Ks. esim. https://tukes.fi/paatokset-ja-kuulutukset/kaivospiirit-ja-kaivosluvat, https://fi.wiktionary.org/wiki/kaivospiiri ja https://tieteentermipankki.fi/wiki/Oikeustiede:kaivospiiri 

#### Perustelut ehdotukselle   

Ennestään ei tälle asiasanaa; Melindassa 11 osumaa sanalla "kaivospiiri". Toinen vaihtoehto olisi lisätä tämä KT-muodoksi "kaivosalueet"-asiasanalle. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[32 Kaivosteollisuus. Kaivannaisteollisuus](http://www.yso.fi/onto/yso/p26567) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kaivospiirit](http://finto.fi/yse/fi/page/Y509333)

**Comment by jarmosaarikko** [comment]
sv: utmål  en: mining concession

**Comment by mirmaid** [comment]
Ainakin Tieteen termipankin perusteella KT-muoto olisi ok?

**Comment by mariaforsen** [comment]
Utmål on vanhentuneen lainsäädännön termi. https://sv.wikipedia.org/wiki/Utm%C3%A5l

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi  kaivospiirit KÄ kaivosalueet
