### ISSUE TITLE
vatsanpeitteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9334]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vatsanpeitteet 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.utupub.fi/handle/10024/150207 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vatsanpeitteet](http://finto.fi/yse/fi/page/Y509334)

**Comment by mariaforsen** [comment]
Sv. bukvägg https://finto.fi/mesh/fi/page/D034861?clang=sv
