### ISSUE TITLE
vatsahalkio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9335]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vatsahalkio 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.utupub.fi/handle/10024/150207 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vatsahalkio](http://finto.fi/yse/fi/page/Y509335)

**Comment by jarmosaarikko** [comment]
MESH http://www.yso.fi/onto/mesh/D020139  vatsahalkio YK vatsatyrä YK tyrä | vatsahalkio YK tuki- ja liikuntaelinten epämuodostumat 
- en: gastroschisis KT congenital fissure of the abdominal cavity
- sv: gastroschis
- YK http://www.yso.fi/onto/yso/p21990 tyrät  TAI  http://www.yso.fi/onto/yso/p39204 ventraalityrä
- WIkidata: https://www.wikidata.org/wiki/Q1495674  - https://fi.wikipedia.org/wiki/Gastroskiisi
- Terveyskirjasto: [Gastroskiisi](https://www.terveyskirjasto.fi/orp01482)
- [CDC definition](https://www.cdc.gov/ncbddd/birthdefects/gastroschisis.html#:~:text=Gastroschisis%20is%20a%20birth%20defect,outside%20of%20the%20baby's%20body.)

**Comment by mariaforsen** [comment]
Sv. gastroschis ET gastroschisis
