### ISSUE TITLE
napanuoratyrä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9336]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

napanuoratyrä 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.utupub.fi/handle/10024/150207 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [napanuoratyrä](http://finto.fi/yse/fi/page/Y509336)

**Comment by mirmaid** [comment]
Lääketieteen termit: omfaloseele: _napanuoratyrä | synnynnäinen epämuodostuma, jossa vain kalvopussin ympäröimiä suolenmutkia on työntynyt navan kohdalla vatsaontelon ulkopuolelle_

https://www.terveyskirjasto.fi/orp01483

**Comment by mariaforsen** [comment]
Sv. navelsträngsbråck ET omfalocele

**Comment by YSO-kokous** [comment]
Hyväksytään napanuoratyrä KT omfaloseele
