### ISSUE TITLE
hammasluu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9337]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hammasluu 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.utupub.fi/handle/10024/149412 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [hammasluu](http://finto.fi/yse/fi/page/Y509337)

**Comment by mariaforsen** [comment]
Sv. tandben ET dentin
