### ISSUE TITLE
mesenkymaaliset kantasolut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9338]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mesenkymaaliset kantasolut 

#### Ehdotettu termi ruotsiksi   

mesenkymala stamceller 

#### Ehdotettu termi englanniksi   

Mesenchymal Stem Cells 

#### Vaihtoehtoiset termit ja ilmaisut   

mesenkymaaliset stroomasolut 
MSC-solut 

#### Ehdotettu yläkäsite YSOssa (LT)   

[stroomasolut](http://www.yso.fi/onto/yso/p30223) 
[kantasolut](http://www.yso.fi/onto/yso/p13517) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D059630> 
LCSH : <http://id.loc.gov/authorities/subjects/sh2010012753> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579) 

#### Tarkoitusta täsmentävä selite   

huom. http://id.loc.gov/authorities/subjects/sh2010012753 linkattu nyt stroomasolut 

#### Perustelut ehdotukselle   

Melinda:
mesenkymaaliset kantasolut x 11
mesenkymaaliset stroomasolut x 7 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/320762 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [mesenkymaaliset kantasolut](http://finto.fi/yse/fi/page/Y509338)

**Comment by mariaforsen** [comment]
Sv. mesenkymala stamceller ET mesenkymala stromaceller
