### ISSUE TITLE
rahka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9339]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rahka](http://www.yso.fi/onto/ysa/Y185417) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT maitorahka 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jtuohini** [comment]
Ja samoin tein KT-muodoksi myös _kvarkki (rahka)_. Lähteenä esim. https://www.kielitoimistonsanakirja.fi/kvarkki, merkitys 2.
