### ISSUE TITLE
maidontuotanto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9340]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maidontuotanto](http://www.yso.fi/onto/ysa/Y112976) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvitseeko tarkenteen? 

#### Perustelut ehdotukselle   

Käytetty myös maidontuotannosta merkityksessä maidoneritys/-muodostus. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Maidontuotanto (maitotalous)? Tai (maatalous/karjatalous)?

**Comment by YSO-kokous** [comment]
lisätään tarkenne maitotalous

**Comment by mirmaid** [comment]
Tarkenteeksi kuitenkin linjauksen mukainen (kotieläintalous).
