### ISSUE TITLE
ekologiset käytävät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9341]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ekologiset käytävät](http://www.yso.fi/onto/ysa/Y133605) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT ekologiset yhteydet 

#### Perustelut ehdotukselle   

Helpottaisi oikean käsitteen löytämistä.
Täällä käsitteet määritetty synosyymeiksi: https://www.vantaa.fi/instancedata/prime_product_julkaisu/vantaa/embeds/vantaawwwstructure/147989_ekologiset_yhteydet_web.pdf

**Comment by mariaforsen** [comment]
Sv. ekologiska förbindelser
