### ISSUE TITLE
HOKS

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9344]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

HOKS

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Henkilökohtaisen osaamisen kehittämissuunnitelma

**Perustelut ehdotukselle**

HOPSit on taidettu monessa paikassa korvata HOKSeilla jo muutamia vuosia sitten, mutta sanastosta löytyy edelleen vain ensinmainittu.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Luetteloin juuri yksilöllisiä opintopolkuja käsittelevän opinnäytetyön, jossa puhutaan nimenomaan HOKSeista.

**Ehdottajan organisaatio**

Metropolia Ammattikorkeakoulu
**Termiehdotus Fintossa:** [HOKS](http://finto.fi/yse/fi/page/Y509344)

**Comment by jtuohini** [comment]
Olisiko nykyiset [**HOJKS**](http://www.yso.fi/onto/yso/p22091) ja [**HOPS**](http://www.yso.fi/onto/yso/p20979) ynnä ehdotettu **_HOKS_** – samalla mahdolliset tulevat vastaavat "keisarin uudet vaatteet" ennakoiden – syytä koostaa yhdeksi asiasanaksi, _**henkilökohtaiset opetussuunnitelmat**_ tms?

**Comment by mirmaid** [comment]
HOKS näyttää olevan (tällä hetkellä) käytössä nimenomaan ammatillisessa koulutuksessa. Niissäkin tosin myös vielä osittain käytössä muoto HOPS.

https://termipankki.fi/tepa/fi/haku/hoks
https://termipankki.fi/tepa/fi/haku/hojks
https://termipankki.fi/tepa/fi/haku/hops

**Comment by YSO-kokous** [comment]
Hyväksytään HOKS  KT "henkilökohtaisen osaamisen kehittämissuunnitelma"

**Comment by mariaforsen** [comment]
Sv. personlig utvecklingsplan för kunnandet ET PUK (utbildning)
