### ISSUE TITLE
lapsipornografia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9346]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lapsipornografia](http://www.yso.fi/onto/ysa/Y131445) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Palaute: Törmäsin Fintossa nykyään vanhentuneeseen käsitteeseen lapsiporno. YK:n ihmisoikeusvaltuutetun toimisto sekä Suomessa Pelastakaa Lapset ry suosittavat termin käytöstä luopumista ja sen korvaamista esimerkiksi termillä lapsen hyväksikäyttömateriaali. Lapsiporno-termi häivyttää näkyvistä lapseen kohdistuvan hyväksikäytön ja väkivallan, ja tämä materiaali tarkoittaa pornoa vain niille, jotka ovat seksuaalisesti kiinnostuneita lapsista. Hyväksikäyttömateriaali sen sijaan korostaa uhrin asemaa ja sitä, että kyse on rikoksesta. Lisätietoa linjauksesta löytyy esimerkiksi täältä: https://www.pelastakaalapset.fi/uutiset/sanoilla-merkitysta-lapsen-hyvaksikaytosta-keskustellaan/ sekä täältä (s. 34) https://www.ohchr.org/Documents/Issues/Children/SR/TerminologyGuidelines_en.pdf. Huomasin, että Fintossa ei ole myöskään rasistisia termejä, joten näkisin että tämänkin termin osalta päivitys olisi paikallaan. 

#### Perustelut ehdotukselle   

-

**Comment by jtuohini** [comment]
Kielitoimiston sanakirjan mukaan ei ole vanhentunut (https://www.kielitoimistonsanakirja.fi/lapsipornografia).

Ehdotettu korvaava asiasana "lapsen hyväksikäyttömateriaali" olisi lisäksi harhaanjohtaja: kaikki hyväksikäyttöhän ei ole seksuaalista, vaan voi olla myös taloudellisesta, terveydellistä jne, eikä ehdotettu kieli siitä, että kysymyksessä olisi pornografia ylipäätään. Kielitoimiston sanakirjan mukaan hyväksikäyttö on moraalisesti tuomittavaa hyötymistä tms. toimintaa (https://www.kielitoimistonsanakirja.fi/hyväksikäyttö), eikä vastaavaa moraalista tuomittavuutta ole muidenkaan asianojen muodostuksessa juurikaan huomioitu.

**Comment by YSO-kokous** [comment]
hyväksytään ohjaustermiksi: lapsipornografia KT lapsen hyväksikäyttömateriaali
