### ISSUE TITLE
raakapuu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9347]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[raakapuu](http://www.yso.fi/onto/yso/p18447)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö ollan englanniksi roundwood?

**Perustelut ehdotukselle**

AFOssa on näin http://www.yso.fi/onto/afo/p97 ja usein julkaisuissakin on käsitteenä roundwood, esim. http://urn.fi/URN:ISBN:978-951-40-2223-4

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Tarvinnee tarkenteen. ettei sekoitu raakapuuhun osana takilointia, ks. esim. https://fi.wikipedia.org/wiki/Raakapuu

**Comment by jarmosaarikko** [comment]
Kyllä roundwood lienee kelvollinen termi, sillä https://fi.wikipedia.org/wiki/Puutavara - _raakapuu on metsästä saatavaa pyöreää puutavara_   - Suomeksi voisi olla "raakapuu (puutavara)", muttei liene tarpeellista, kun tuo takilan osa ei ole sanastossa.  

- FI: **KÄ raakapuu KT pyöreä puutavara, jalostamaton puutavara, teollisuuspuu** 
- SV: råvirke KT industrivirke
- EN: roundwood  KT raw wood, industrial roundwood

Lähde: [Luke](https://www.luke.fi/en/news/roundwood-removals-remained-high-although-down-by-five-million-cubic-metres/) , [Tilastokeskus](https://www.stat.fi/til/mahakk/index_en.html)

https://www.greenfacts.org/glossary/pqrs/roundwood.htm  - Roundwood Definition: _Wood in its natural state as felled, with or without bark. It may be round, split, roughly squared or in other forms._

- Takilan osalle on myös parempi termi tuolla wikipedia-sivulla eli "raakapuomi".  
- Sille on myös käsitesivu: https://www.wikidata.org/wiki/Q663616

**Comment by mirmaid** [comment]
Raakapuut takilointiin liittyen olisi monikossa, ja on aika epätodennäköinen ainakin tekstiaineistojen kuvailussa.

**Comment by jtuohini** [comment]
Finnan "raakapuu"-sanahaun ensimmäinen osuma sattuu olemaan https://finna.fi/Record/musketti_tmk.M20:TMM19907 …

**Comment by jarmosaarikko** [comment]
termillä on kaksi merkitystä, sille ei voi mitään. Voi vain suositella museoita käyttämään esineestä termiä **raakapuomi** - tosin silloin se pitäisi lisätä sanastoon myös...  Kun näitä kuvia katsoo, niin ei tule juuri maston osan kuvia: https://wikidocumentaries-demo.wmflabs.org/Q16296645?language=fi  ja raakapuomin kuvia tästä:  https://wikidocumentaries-demo.wmflabs.org/Q5429522?language=fi

**Comment by mirmaid** [comment]
raakapuomit KT raakapuut (takilointi/purjehdus), raa'at (?)

**Comment by YSO-kokous** [comment]
raakapuomit KT raakapuut (purjehdus), raa'at

**Comment by mariaforsen** [comment]
Sv. rår (segling)
