### ISSUE TITLE
Västerfjärden

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9350]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Västerfjärden 

#### Ehdotettu termi ruotsiksi   

Västerfjärden 

#### Tarkoitusta täsmentävä selite   

Västerfjärden är en sötvattensbassäng i Närpes, Österbotten. Västerfjärden var ursprungligen en havsvik men uppdämdes på 1970-talet för att trygga råvattenbehovet åt industri. Idag anses Västerfjärden vara en sjö. 

#### Perustelut ehdotukselle   

Tarvitaan kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://www.doria.fi/handle/10024/161882 

**Ehdottajan organisaatio:** SN/KK **Termiehdotus Fintossa:** [Västerfjärden](http://finto.fi/yse/fi/page/Y509350)

**Comment by ilona-x** [comment]
https://sv.wikipedia.org/wiki/V%C3%A4sterfj%C3%A4rden_(sj%C3%B6_i_N%C3%A4rpes,_%C3%96sterbotten)

**Comment by jarmosaarikko** [comment]
Näyttäisi olevan sama kuin **Knåpfjärden** - http://paikkatiedot.fi/so/1000772/10233412
edellä viitatun sv wikipedian sivun [koordinaatit](https://geohack.toolforge.org/geohack.php?language=sv&pagename=V%C3%A4sterfj%C3%A4rden_(sj%C3%B6_i_N%C3%A4rpes,_%C3%96sterbotten)&params=62.3973_N_21.2883_E_type:waterbody_region:FI) vievät samaan paikkaan

**Comment by mirmaid** [comment]
Näin tosiaan. Eli Knåpfjärden KT Västerfjärden (Närpiö)?

**Comment by mirmaid** [comment]
Samalla voidaan miettiä, onko yläkäsite (meren osana) Pohjanlahti vai Selkämeri?

**Comment by mirmaid** [comment]
Västerfjärden (Närpiö) KT Knåpfjärden, Västerfjärdenin allas. PNR paikkatyyppi, ei kuitenkaan yläkäsitteeksi laajempaa merialuetta.
