### ISSUE TITLE
basaarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9351]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[basaarit](http://www.yso.fi/onto/yso/p39308)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritelmä? 

**Perustelut ehdotukselle**

Kielitoimiston sanakirja: 1. itämainen kauppakuja t. -halli. 2. myyjäiset. Sanastossa on myös myyjäiset, voidaanko ne määritellä kuten Kielitoimiston sanakirjassa: tav. hyväntekeväisyystarkoituksessa järjestettävä tavaranmyyntitilaisuus. Ruotsiksi nämä ovat molemmat basarer, mutta myyjäiset voisi mahdollisesti olla myös välgörenhetsförsäljningar tms., riippuen miten rajataan suomeksi. 

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
2021-07-12/JS:  basarer (sv) on nyt kahteen kertaan käsitteissä basaarit ja myyjäiset.  "jumble sales" on ruotsiksi käännetty  "loppmarknader", joka taas on kirpputorit, joka on "flea markets" eli  kehäpäätelmä....   

Ehdotan, että myyjäiset olisi ruotsiksi "tillfälliga försäljningar" KT "basarer".  
https://www.synonymer.se/sv-syn/basar

Collins dictionary: 
- "A jumble sale is a sale of cheap second-hand goods, usually held to raise money for charity."   Am. "rummage sale"
- "A flea market is an outdoor market which sells cheap used goods and sometimes also very old furniture." -- 
Kirpputori tämä siis on pysyvämpi paikka (market) kun edellinen on "kertaluonteinen" (tillfällig)?

**Comment by mariaforsen** [comment]
Ruotsinnos korjataan kun termien merkitys on suomeksi tarkennettu.

**Comment by mirmaid** [comment]
Jännä tuo Kielitoimiston sanakirja, itselleni ainakin basaari-sana on ihan vieras myyjäiset-merkityksessä. 

myyjäiset: _tav. hyväntekeväisyystarkoituksessa järjestettävä tavaranmyyntitilaisuus._ 
En sitten tiedä, miten tuo hyväntekeväisyys rajautuu, koska varmaan myös esim. yhdistys voi järjestää myyjäiset rahoittaakseen toimintaansa. 
Melko vähän käytetty Melindassa, osaan sopisi (ja osassa onkin lisäksi) _markkinat (tapahtumat)_. Hyväntekeväisyys-aspekti ei kuitenkaan ehkä suoraan käy ilmi viitteissä.

**Comment by ilona-x** [comment]
Voisiko tuon hyväntekeväisyyden ajatella tässä tapauksessa olevan merkitykseltään laajempi, kun myyjäisten avulla kai yleensä kerätään rahaa johonkin tiettyyn tarkoitukseen / jonkin asian hyväksi, esim. koululuokan retkeen tai yhdistyksen/urheiluseuran toimintaan

**Comment by YSO-kokous** [comment]
basaarit - itämainen kauppakuja tai -halli
ruotsiksi voisi olla försäljningar (evenemang)
