### ISSUE TITLE
pullonokkadelfiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9352]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pullonokkadelfiini 

#### Ehdotettu termi ruotsiksi   

öresvin 

#### Ehdotettu termi englanniksi   

common bottlenose dolphin 

#### Vaihtoehtoiset termit ja ilmaisut   

pullokuonodelfiini 
bottlenose dolphin 
Tursiops truncatus 

#### Ehdotettu yläkäsite YSOssa (LT)   

[delfiinit](http://www.yso.fi/onto/yso/p11230) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[17 Eläintiede](http://www.yso.fi/onto/yso/p26529) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/318184 

#### Perustelut ehdotukselle   

sisällönkuvailu 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [pullonokkadelfiini](http://finto.fi/yse/fi/page/Y509352)

**Comment by jarmosaarikko** [comment]
Suosittelen käyttämään prefLabelinä lajitietokeskuksen nimeä: **pullokuonodelfiini** 
- Tursiops truncatus 
- http://tun.fi/MX.47013
- https://www.wikidata.org/wiki/Q174199
- http://id.loc.gov/authorities/subjects/sh85009170

**Comment by mariaforsen** [comment]
Sv. öresvin ET flasknosdelfin
