### ISSUE TITLE
Israelin itsenäisyyssota

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9353]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Israelin itsenäisyyssota 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://fi.wikipedia.org/wiki/Israelin_itsen%C3%A4isyyssota 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789651328138 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [Israelin itsenäisyyssota](http://finto.fi/yse/fi/page/Y509353)

**Comment by jarmosaarikko** [comment]
- https://www.wikidata.org/wiki/Q49097
- Israelin itsenäisyyssota
- "1947–1949 Palestine war" - https://en.wikipedia.org/wiki/1947%E2%80%931949_Palestine_war
- "1948 års arabisk-israeliska krig"

onko eri kuin tämä, joka samalla nimellä wikidatassa (tai tämä on osa ylempää):
- https://www.wikidata.org/wiki/Q49092
- 1948 Arab–Israeli War - https://en.wikipedia.org/wiki/1948_Arab%E2%80%93Israeli_War

tai tämä:
- https://www.wikidata.org/wiki/Q2379101
- 1947–1948 civil war in Mandatory Palestine
- Palestiinan mandaattialueen sisällissota https://fi.wikipedia.org/wiki/Palestiinan_mandaattialueen_sis%C3%A4llissota

**Comment by mariaforsen** [comment]
Sv. Palestinakriget (1948-1949) ET Palestinakriget 1948-1949 /SAO 1948 års arabisk-israeliska krig /WP, första Israelkriget, Israels självständighetskrig (1948)

https://sv.wikipedia.org/wiki/1948_%C3%A5rs_arabisk-israeliska_krig

**Comment by mirmaid** [comment]
LCSH: Israel-Arab War, 1948-1949 http://id.loc.gov/authorities/subjects/sh85068706

**Comment by mirmaid** [comment]
Ehdotettua muotoa käytetty Ylellä. Eli olisiko Israelin itsenäisyyssota (1948-1949), KT Palestiinan sota (1948-1949) - sikäli kuin nuo tarkenteet halutaan mukaan. Tässä ei oikeastaan ole kyse siitä, että erotettaisiin muista samannimisistä, mutta tarvitaanko silti?

**Comment by YSO-kokous** [comment]
Hyväksytään  Israelin itsenäisyyssota (1948-1949) KT Palestiinan sota (1948-1949)
