### ISSUE TITLE
Aurejärvi (Ylöjärvi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9354]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Aurejärvi (Ylöjärvi)](http://www.yso.fi/onto/yso/p125921)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä on ollut alunperin muodossa Aurejärvi (Kuru), ja muutettu v. 2009 kuntaliitoksen jälkeen muoton Aurejärvi (Ylöjärvi). PItäiskö kuitenkin palauttaa vanha muoto? Huom. nykyään Aurejärvi-niminen kylä sijaitsee Parkanossa (tämä kylä syntynyt, kun osa Kurun Aurejärven kylästä liittyi Parkanoon)

**Perustelut ehdotukselle**

Aurejärven kylä on hajonnut v. 1926 alussa https://fi.wikipedia.org/wiki/Aurej%C3%A4rvi Käytetty Melindasssa vain kerran kuvailtaessa kylän hajoamista käsittelevää julkaisua: https://trepo.tuni.fi/handle/10024/88798

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Aurejärvi (Kuru) ja huomautus historiasta, lisäksi otetaan Aurejärvi (Parkano). Aurejärvelle tarkenne (järvi).
