### ISSUE TITLE
Pihlajasaari (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9355]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pihlajasaari (Helsinki)](http://www.yso.fi/onto/yso/p120449)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaanko muotoon Pihlajasaaret? Nyt ei linkkejä Paikkatietoalustalle, siellä Itäinen Pihlajasaari & Läntinen Pihlajasaari. http://paikkatiedot.fi/so/1000772/10342454 & http://paikkatiedot.fi/so/1000772/10342324

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Pihlajasaaret 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Tästä taidetaan puhua yleensä yksikössä (myös wikipedian tekstissä ja kaupungin sivuilla), mutta mun puolestani molemmat ok. Ohjaustermejä ainakin voisi lisätä.

**Comment by mirmaid** [comment]
KT Pihlajasaaret, Itäinen Pihlajasaari & Läntinen Pihlajasaari, linkitys molempiin, päätermi yksikössä.
