### ISSUE TITLE
Polytechnics Act

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9356]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Polytechnics Act](http://www.yso.fi/onto/yso/p13036)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng termiksi "Universities of Applied Sciences Act"

**Perustelut ehdotukselle**

virallinen finlex-käännös:  https://www.finlex.fi/en/laki/kaannokset/2014/en20140932. Vanha muoto voitaneen jättää ohjaustermiksi.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto/js

**Comment by jarmosaarikko** [comment]
voisi myös lisätä RT-suhteen käsitteeseen ammattikorkeakoulut http://www.yso.fi/onto/yso/p10564.

**Comment by tpalonen** [comment]
Muutettu
