### ISSUE TITLE
ammattikorkeakoulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9357]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ammattikorkeakoulut](http://www.yso.fi/onto/yso/p10564)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng termi muotoon "universities of applied sciences"

**Perustelut ehdotukselle**

ammattikorkeakoululaki virallinen käännös Finlexissä on "Universities of Applied Sciences Act".  OKM ja korkeakoulut käyttävät nykyään tätä muotoa.  Vanha suositeltava termi voidaan säilyttää ohjausterminä.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto/js

**Comment by tpalonen** [comment]
Muutettu
