### ISSUE TITLE
Pikku-Pyötinen (Karhula)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9358]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pikku-Pyötinen (Karhula)](http://www.yso.fi/onto/yso/p179669)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämä pitäisi yhdistää: Pikku-Pyötinen (Kotka)

**Perustelut ehdotukselle**

Karhula liitetty 1.1.1977 Kotkaan

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by ilona-x** [comment]
myös vanha ehdotus samasta https://github.com/Finto-ehdotus/YSE/issues/8846
