### ISSUE TITLE
taudinaiheuttajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9359]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[taudinaiheuttajat](http://www.yso.fi/onto/yso/p8822)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö lisätä myös kasvitieteen luokka.

**Perustelut ehdotukselle**

Taudinaiheuttajia myös kasveilla, esim. http://urn.fi/URN:ISBN:978-951-40-2295-1

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ehkä myös 15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia?

**Comment by YSO-kokous** [comment]
Lisätään molemmat luokat
