### ISSUE TITLE
Harju (Tampere)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9361]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Harju (Tampere)](http://www.yso.fi/onto/yso/p122562)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

kuuluuko YSO-paikkoihin vai pitäisikö poistaa?
Harju-nimistä paikkaa ei ole Tampereella, vaan kyseessä on seurakunta. Tämä on otettu sanastoon ilmeisesti kuorohistoriikin kuvailuun: https://melinda.kansalliskirjasto.fi/byid/000934245, ko. kuoro on perustettu aikanaan Harjun seurakunnassa

**Perustelut ehdotukselle**

"Harjun seurakunta on Tampereen toiseksi suurin seurakunta, käsittäen koko läntisen Tampereen Pispalaa myöten, joka on seurakunnan itäinen raja."  Lähde: https://fi.wikipedia.org/wiki/Harjun_seurakunta https://harjunkamarikuoro.net/wp/kuoro/harjun-kamarikuoron-historiaa/

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Jos näin on, kannatan poistoa.

**Comment by mirmaid** [comment]
Poistetaan.

**Comment by jtuohini** [comment]
Harju itse asiassa on paikka Tampereella. Kyseessä on jakokunta, joka siirtyi Pirkkalan jaossa vuonna 1921 osaksi Pohjois-Pirkkalaa (eli myöhempää Nokiaa) ja edelleen vuonna 1937 osaksi Tamperetta. – Suomen evankelis-luterilaisen kirkon Harjun seurakunta vastannee alueellisesti kyseistä jakokuntaa.

Mutta mainitun kuorohistoriikin kuvailuun ei kyseinen jakokunta kylläkään mielekkäästi luonnu.
