### ISSUE TITLE
Holmön (Uumaja)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9362]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Holmön (Uumaja)](http://www.yso.fi/onto/yso/p115591)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Mihin tämä mahtaa viitata? Wikidata-linkitys tähän: https://sv.wikipedia.org/wiki/Holm%C3%B6ns_distrikt
Mutta voisiko kyseessä olla mahdollisesti tämän saariryhmän pääsaari: https://sv.wikipedia.org/wiki/Holm%C3%B6arna?

Huom. jostain syystä yläkäsite puuttuu, Ruotsi vai Uumaja vai joku muu?

**Perustelut ehdotukselle**

Melinda

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by ilona-x** [comment]
Myös Salmis (Haaparanta) puuttuu yläkäsite, Ruotsi vai Haaparanta? http://www.yso.fi/onto/yso/p147452

**Comment by mirmaid** [comment]
Kannattaisiko muuttaa > Holmöarna?

**Comment by mirmaid** [comment]
Holmöarna. Toistaiseksi YK Ruotsi.
