### ISSUE TITLE
Himoistenlahti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9363]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Himoistenlahti](http://www.yso.fi/onto/yso/p110385)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Löytyisikö tälle yläkäsite ja mahdollisesti PNR-linkki
Paikkatietoalustalta löytyy Isosalmi & Himoistenperä, mutta ei Himoistenlahtea

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Vehmassalmi

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Kyllä Himoistenlahti näyttää olevan sama kuin PNR:n **Himoistenperä**, http://paikkatiedot.fi/so/1000772/10299345, joka on kartalle tuon Isosalmen perukassa eli on osa "Vehmassalmea" http://www.yso.fi/onto/yso/p110386. jonka YK on Taivassalo

**Comment by mirmaid** [comment]
Tämän https://fi.wikipedia.org/wiki/Vehmassalmi mukaan Himoistenlahti = Isosalmi, http://paikkatiedot.fi/so/1000772/10299276. Vain perukka olisi Himoistenperä?

Käytetty kerran Melindassa, ehkä voisi muuttaa > Isosalmi?

**Comment by mirmaid** [comment]
Muutetaan > Isosalmi KT Himoistenlahti
