### ISSUE TITLE
Vilajoki (Säkkijärvi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9364]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Vilajoki (Säkkijärvi) 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/S%C3%A4kkij%C3%A4rvi, käytetty Melindassa myös kylästä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Kun kyseessä virtavesi eikä ole muualla Suomessa niin ei kai tarvitse tarkennetta?
https://fi.wikipedia.org/wiki/Vilajoki - https://www.wikidata.org/wiki/Q4106215

**Comment by mirmaid** [comment]
Eli tässä kyse siis kylästä Säkkijärvellä. Vilajoki jokena on jo auktorisoitu. Tarvitaanko:

Vilajoki (Säkkijärvi : kylä)
Vilajoki (joki)

_Vilajoki laskee Venäjän puolella Viipurinlahden Vilalahteen entisen Säkkijärven kunnan Vilajoen kylän luona._

**Comment by mirmaid** [comment]
^ Kuten yllä.

**Comment by jarmosaarikko** [comment]
Wikidatan Vilajoki on väärässä paikassa. Se on Tapiolan kohdalla, mutta tämän 1920 luvun kartan mukaan Vilajoen kylä on tuossa joen suulla siinä missä joki laskee Viipurinlahteen ja valtatie ylittää joen.

![image](https://user-images.githubusercontent.com/32375550/236290729-2084ce19-dcc9-4340-a71f-b73652f04c4e.png)

Yandex-kartan haku termillä "Vilajoki" antaa oikeammat koordinaatit ja vastaavan kylän paikan: посёлок Балтиец (Baltietsin kylä) https://yandex.ru/maps/geo/posyolok_baltiyets/53152012/?ll=28.286402%2C60.623071&z=13.48

Eli oikea Wikidatassa linkattava kohde Vilajoen kylälle on tämä https://www.wikidata.org/wiki/Q4076894

**Comment by mariaforsen** [comment]
Sv. Vilajoki, _jos_ viitataan siihen aikaan kun kylä kuului Suomeen, jos nykyään niin https://www.geonames.org/579372/baltiyets.html

**Comment by mirmaid** [comment]
Lisätään Jarmon ehdottama linkki.
