### ISSUE TITLE
Lappsundinjoki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9366]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lappsundinjoki](http://www.yso.fi/onto/yso/p110904)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tätä voisi yrittää selvittää, mistä joesta on kyse, niin saisi ehkä pnr-linkin tai yläkäsitteen. Melindassa vain 1 viite: "Kevätkutuisten kalalajien lisääntyminen Lappsundinjoella 1990-1996"

Voisiko kyseessä olla esim. tämä http://paikkatiedot.fi/so/1000772/10039524

**Perustelut ehdotukselle**

x

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Eiköhän se ole juuri tuo joki eli YK Mustasaari. Kulkee tosi mielenkiintoisesti aivan Kyröjoen vierestä, muttei liity siihen vaan laskee mereen Petsmossa.

**Comment by mirmaid** [comment]
Lisätty linkki ja yläkäsite.
