### ISSUE TITLE
sävellykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9367]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sävellykset](http://www.yso.fi/onto/ysa/Y108687) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:n puolella muutetaan KT:ksi "musiikki"-termille, sama termien "musiikkiteokset" ja "sävelteokset" osalta 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mirmaid** [comment]
Poistetaan sävellykset ja lisätään ehdotetut ohjaustermit.
