### ISSUE TITLE
Kypros

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9369]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Kypros](http://www.yso.fi/onto/yso/p106039)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisättävä tarkenne (joko saari tai valtio)

**Perustelut ehdotukselle**

Viittaussuhde on tällä hetkellä epäselvä, kun alakäsitteinä on sekä kaupunkeja että hallinnollinen itsenäiseksi julistautunut alue.  Saari ja valtio pitäisi käsitellä eri paikkoina..

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jarmosaarikko** [comment]
käsitteestä puuttuu tyyppi onko tämä
- Kypros (saari)   https://www.wikidata.org/wiki/Q644636   vai    
- Kypros (valtio)  https://www.wikidata.org/wiki/Q229  

Kun alakäsitteenä on eristäytynyt hallintoalue Pohjois-Kypros, niin se viittaisi siihen, että kyseessä on saari. Mutta eikö silloin pitäisi olla myös alakäsite Kypros -niminen valtio, jota nyt ei taida olla lainkaan yso-paikoissa?   Kts.
- https://fi.wikipedia.org/wiki/Kyproksen_tasavalta
- https://fi.wikipedia.org/wiki/Kypros

**Comment by mirmaid** [comment]
Jaottelu ei ehkä palvelisi käyttäjää/kuvailijaa parhaalla mahdollisella tavalla.
