### ISSUE TITLE
Ersmark

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9371]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ersmark](http://www.yso.fi/onto/yso/p140937)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään huomatus tai sulkutarkenne, että tämä sijaitsee Skellefteåssa eikä Uumajassa.

**Perustelut ehdotukselle**

kaksi samannimistä paikkaa Ruotsissa. Melindan aineisto viittaa Skellefteåån.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jarmosaarikko** [comment]
Uumajassa https://www.wikidata.org/wiki/Q2439435 
Skellefteåssa  https://www.wikidata.org/wiki/Q2742608

**Comment by ilona-x** [comment]
Melinda-viite: https://melinda.kansalliskirjasto.fi/byid/000446615

**Comment by mirmaid** [comment]
Lisätty tarkenne.
