### ISSUE TITLE
Repola (Viipurin maalaiskunta)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9372]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Repola (Viipurin maalaiskunta)](http://www.yso.fi/onto/yso/p112468)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

sulkutarkenteeseen (Viipuri)

**Perustelut ehdotukselle**

WIkipedian mukaan tämä olisi Viipurin kaupunginosa (ei maalaiskunnan) https://fi.wikipedia.org/wiki/Repola_(Viipuri) -- Wikipedian mukaan Viipurin maalaiskunnassa on Repola-Tervajoki: https://fi.wikipedia.org/wiki/Repola%E2%80%93Tervajoki

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Sanastossa myös Repola ilman tarkennetta. https://fi.wikipedia.org/wiki/Repola - tälle lisättävä tarkenne (Karjalan tasavalta?).

Kolmessa Repola (Viipurin maalaiskunta) -viitteessä kyseessä ilmeisesti maalaiskunnan Repola-Tervajoki (voisi varmistaa).

**Comment by mirmaid** [comment]
^ Muutetaan > Repola-Tervajoki.

Repola (Karjalan tasavalta)

**Comment by mariaforsen** [comment]
Ristiriitaista ruotsiksi: toisaalta käännetään sen vanhan (Suomen aikaisen) nimen mukaisesti, mutta tarkenteena lisätään silti "Karelska republiken", eli nykytilanteen mukaisesti.
