### ISSUE TITLE
Maustesaaret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9380]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Maustesaaret](http://www.yso.fi/onto/yso/p169608)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT suhde Molukut pitäisi olla  seuraaja-suhde  TAI yhdistetään nämä käsitteet

**Perustelut ehdotukselle**

saman paikan entinen ja nykyinen nimi eri käsitteinä - hallnnollisesti sama alue. Maustesaaret on historiallinen nimityös löytöretkien aikaan, joten voisi olla ohjausterminä kuten Wikidatassa.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Poistettu.
