### ISSUE TITLE
puhallinorkesterit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9388]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[puhallinorkesterit](http://www.yso.fi/onto/ysa/Y103809) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Täsmennetään huomautusta korostamaan puhallinorkesterin taidemusiikillisuutta verrattuna soittokuntiin (jotka kattavassa asiasanassa asia on tehty selväksi) sekä siirretään nykyinen KT-muoto "brass bandit" soittokuntien KT-muodoksi, samoin tietysti ruotsinkielinen "brass band". 

#### Perustelut ehdotukselle   

Finnassa tällä hetkellä aivan tolkuton määrä soittokuntia esittäviä valokuvia on kuvailtu asiasanalla "puhallinorkesterit". Muutamista olen raportoinut, ja niitä on korjattukin. Ja osassa tietueista on sekä "puhallinorkesterit" että "soittokunnat", vaikka ovat jokseenkin toisensa poissulkevia. Jotta jatkossa tulisi vähemmän sotkua, pitäisi selkeyttä sanaston puolella lisätä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
- http://www.yso.fi/onto/yso/p29989  soittokunnat / musikkårer / **brass bands**
-- MÄÄRITELMÄ: Pääosin vaskipuhaltimista koostuva orkesteri.
-- HUOMAUTUS: Jos orkesteri koostuu pääosin puupuhaltimista, käytetään ensisijaisesti käsitettä kamariorkesterit.

- http://www.yso.fi/onto/yso/p16416 puhallinorkesterit **(KT brass bandit ❌ )**   / blåsorkestrar **(KT brass band ❌ )** / concert bands (KT wind ensembles, etc.) 
-- MÄÄRITELMÄ: Pääasiassa puhaltimia ja lyömäsoittimia käsittävä sotilas-, ammattikunta- (esim. poliisi, palokunta, rautatie), työväenyhdistyksen jne. orkesteri.
-- HUOMAUTUS: Jos puhallinsoittimista koostuva kokoonpano sisältää modernin puhallinorkesterin soittimet, siitä käytetään ilmaisua puhallinorkesterit. Jos tällainen kokoonpano on nimetysti osa sotilaallista organisaatiota, käytetään käsitettä sotilassoittokunnat.

**Comment by jarmosaarikko** [comment]
Asiaa hämmentää jonkin verran esityskokoonpanosanasto SEKO:
* SEKO ei sisällä termiä "soittokunta" lainkaan ja yhdistää nämä termit eri tavalla ja ristiin...   
* SEKO http://urn.fi/urn:nbn:fi:au:seko:00800 puhallinorkesteri (KT blåsorkestrar, **brass band**, puhallinorkesterit)
    * MÄÄRITELMÄ: Orkesteri, joka koostuu pääosin vaskipuhaltimista. Kokoonpanoon kuuluu yleensä myös puupuhaltimia sekä lyömäsoittimia.
    * skos:exactMatch LCMPTM [band](http://id.loc.gov/authorities/performanceMediums/mp2013015048),  YK instrumental ensemble (eli soitinyhtye) 
    
* SEKO http://urn.fi/urn:nbn:fi:au:seko:00803 puhallinyhtye 
    * MÄÄRITELMÄ: Pääasiassa puhallinsoittimista koostuva yhtye.
    * skos:exactMatch LCMPTM  **[brass band](http://id.loc.gov/authorities/performanceMediums/mp2013015100)** YK band.
* YSO:ssa on "[soitinyhtyeet](http://www.yso.fi/onto/yso/p27211)", mutta sen AK puhallinyhtyeistä vain "[torviseitsikot](http://www.yso.fi/onto/yso/p29875)".

Onko SEKOssa ensimmäinen exactMatch oikeassa käsitteessä?
* [band](http://id.loc.gov/authorities/performanceMediums/mp2013015048) - A large ensemble consisting primarily of woodwinds, brass, and percussion. For an ensemble consisting of two or more mixed woodwind or brass instruments, see [[wind ensemble](http://id.loc.gov/authorities/performanceMediums/mp2013015802).] For an ensemble consisting of brass or woodwinds only, see [[brass ensemble](http://id.loc.gov/authorities/performanceMediums/mp2013015101)] or [[woodwind ensemble](http://id.loc.gov/authorities/performanceMediums/mp2013015806).]

**Comment by jtuohini** [comment]
Ylemmässä kommentissa (@jarmosaarikko) määritelmä ja huomautus menneet ristiin asiasanojen kesken! Sekoa koskevat korjaukset olisi varmaan hyvä "heittää" Muusalle pohdittavaksi.
 
Mitä tulee LCMPT:n "ensemble"-sanaan, niin pitää muistaa, että se ei ola sama kuin meidän "yhtye", vaan paremminkin "kokoonpano" ja kattaa myös orkesterit.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ohjaustermin _brass bandit_ siirtämistä _puhallinorkestereista_ _soittokuntiin_.

Ei kuitenkaan kannateta _puhallinorkestereiden_ määritelmän muutosta. Sen sijaan ehdotetaan, että _soittokunnat_ siirretään _puhallinorkestereiden_ alakäsitteeksi.

SEKOssa muutetaan puhallinyhtyeen LCMPT-vastineeksi [wind ensemble](https://id.loc.gov/authorities/performanceMediums/mp2013015802.html).

**Comment by mariaforsen** [comment]
Termien määritelmät eivät oikein täsmää ruotsin osalta, kysytään ruotsinkieliseltä musiikkiasiantuntijalta mitä toimenpiteitä tämä vaatii ruotsin osalta.

**Comment by YSO-kokous** [comment]
Hyväksytään
soittokunnat KT brassbandit   YK puhalinorkesterit
poistetaan brassbandit puhallinorkestereista

**Comment by mariaforsen** [comment]
Musiikkiasiantuntijamme ei kannattanut brassband-ohjaustermin siirtoa, eikä kannattanut nykyistä puhallinorkestereiden huomautusta, jossa kehoitetaan käyttämään kamariorkesterit kun kyseessä on puupuhallinorkesteri. Ruotsiksi nämä ohjaukset eivät ole sopivia. 
https://svenska.se/tre/?sok=brassband&pz=1
https://svenska.se/tre/?sok=bl%C3%A5sorkester&pz=1

**Comment by mirmaid** [comment]
https://www.kielitoimistonsanakirja.fi/#/puhallinorkesteri?searchMode=all

**Comment by mirmaid** [comment]
Soittokuntien ja puhallinorkesterien määritelmiä olisi hyvä johdonmukaistaa: "moderni puhallinorkesteri", "pääosin vaskipuhaltimista" jne. ovat turhan epäselviä tekemään erotteluja varsinkaan, jos kuvailija ei ole itse hyvin perillä siitä, mihin näillä sanamuodoilla viitataan. Soittokuntien huomautuksessa käsketään nyt käyttämään termiä puhallinorkesterit jos "kokoonpano sisältää modernin puhallinorkesterin soittimet", mutta puhallinorkesterien määritelmä ei mainitse "modernia puhallinorkesteria".

**Comment by MUUSA-kokous** [comment]
Ehdotetaan huomautuksen ensimmäisen virkkeen poistamista _soittokunnista_.

Puhallinorkesterien määritelmä edelleen OK.

**Comment by mirmaid** [comment]
^ Ehdotetun muutoksen jälkeen määritelmät:
**puhallinorkesterit:** Pääosin vaskipuhaltimista koostuva orkesteri.
Huomautus: Jos orkesteri koostuu pääosin puupuhaltimista, käytetään ensisijaisesti käsitettä kamariorkesterit.

**soittokunnat:** Pääasiassa puhaltimia ja lyömäsoittimia käsittävä sotilas-, ammattikunta- (esim. poliisi, palokunta, rautatie), työväenyhdistyksen jne. orkesteri.
Huomautus: Jos tällainen kokoonpano on nimetysti osa sotilaallista organisaatiota, käytetään käsitettä sotilassoittokunnat.

**Comment by mirmaid** [comment]
Tässä ei nyt ollut Muusan kantaa Marian kommentteihin edellä koskien puhallinorkesterien huomautusta ja ohjaustermiä brass bandit.

**Comment by YSO-kokous** [comment]
### Päätös

**soittokunnat:** Pääasiassa puhaltimia ja lyömäsoittimia käsittävä sotilas-, ammattikunta- (esim. poliisi, palokunta, rautatie), työväenyhdistyksen jne. orkesteri.
_Huomautus:_ Jos tällainen kokoonpano on nimetysti osa sotilaallista organisaatiota, käytetään käsitettä sotilassoittokunnat.

Pyydetään Muusa tarkistamaan **puhalinorkesterien** määritelmä vastaamaan SEKOn määritelmää, jotta ruotsinkielinen käsite saadaan vastaamaan käsitettä.

**Comment by MUUSA-kokous** [comment]
Määritelmämuutosehdotus YSOon: Pääosin puhaltimista koostuva orkesteri.
Huomautus voidaan poistaa.

**Comment by YSO-kokous** [comment]
### Päätös
Toteutetaan Muusan ehdotuksen (30.3.) mukaisesti.
**puhalllinorkesterit** Pääosin puhaltimista koostuva orkesteri.  
Huomautus poistetaan.
