### ISSUE TITLE
Pirilänkoski

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9390]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pirilänkoski](http://www.yso.fi/onto/yso/p188858)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Wikidata-linkki nyt Harjavallan vesivoimalaitokseen: https://www.wikidata.org/wiki/Q11861542. Pitäisikö poistaa?

Yläkäsitteeksi lisätty Kokemäenjoki, mutta mikä lisätään sijaintikunnaksi, kun koski sijaitsee Harjavallan ja Nakkilan rajalla, eikä tätä koskea löyty paikkatietoalustalta?

**Perustelut ehdotukselle**

x

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Wikidata-linkki korjattu käsitteeseen:  https://www.wikidata.org/wiki/Q108152056

Liittyykö kuvailutarve Pirilänkosken luonnonsuojelualueeseen? 
- https://www.ymparisto.fi/fi-FI/KokemaenjokiLIFE_2006__2012/Hankealueet/Pirilankoski
- sekä https://urn.fi/URN:ISBN:978-952-257-445-9 (Doriassa)
- https://www.wikidata.org/wiki/Q108150035

Pirilä (Harjavalta) - http://paikkatiedot.fi/so/1000772/10050183 -

**Comment by mirmaid** [comment]
Molemmat kunnat. Poistetaan linkki voimalaitokseen.
