### ISSUE TITLE
autoradat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9391]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

autoradat 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Toimintahistoriikki / Suomen Scalextric harrastajat 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [autoradat](http://finto.fi/yse/fi/page/Y509391)

**Comment by jarmosaarikko** [comment]
Wikipediassa tämä on muodossa ura-autoilu ja sen perusteella käytettävä termi voisi olla **ura-autoradat**
- https://fi.wikipedia.org/wiki/Ura-autoilu
- https://sv.wikipedia.org/wiki/Sp%C3%A5rstyrd_racing
- https://en.wikipedia.org/wiki/Slot_car_racing

Olisiko kuitenkin parempi kuvata YSO:ssa harrastus "**ura-autoilu**" kuin pelkkä osa harrastusta eli tuo rata?
Harrastuksen kohteena ovat ura-autot ja ura-autoradat, jne
- https://www.hobbylinna.fi/fi/muut-tuotteet/ura-autot-ja-radat/c/108/
- https://rc.kokua.fi/2020/08/23/ura-autorata-sisaradalla/

Ehdotus käsitteiksi: 
ura-autoilu (KT RC autoilu) | spårstyrd racing (KT slotracing) | slot-car racing
- YK harrastukset

autoradat (KT ura-autoradat) | bilbanor | slot car tracks
- YK leikkikalut

ura-autot | spårstyrda modellbilar | slot cars (KT slot racers)   
-- YK leikkiautot 
-- LCSH http://id.loc.gov/authorities/subjects/sh97008888

**Comment by mirmaid** [comment]
6 kertaa Melindassa, kerran käytetty eri merkityksessä (lastenhuoneen sisustus). 

Myös _pienoisautoilu_, https://github.com/Finto-ehdotus/YSE/issues/3252 - käytetty 13 kertaa Melindassa, mutta niissä kyse radio-ohjattavista.

**Comment by LeKorsu** [comment]
Minusta ura-autoradat on kyllä ei-ammattikäyttäjän mielestä vaikea löytää harraste/leikkiautoratoja, mutta en nyt yksiselitteiseti vastustakaan. Entä pitäisikö tuoda selvemmin esiin ero moottoriratoihin, ettei autourheiluratoja haeta autoradoilla (käsite-eron ura-autoradat kyllä selvemmin tuo esiin, myönnetään).

**Comment by mirmaid** [comment]
Riittäisiköhän kuitenkin tuo aiemmin ehdotettu _pienoisautoilu_ (ohjaustermein), https://www.autourheilu.fi/lajit/pienoisautoilu/.

**Comment by YSO-kokous** [comment]
otetaan muodossa pienoisautoilu KT ura-autoilu, RC-autoilu

**Comment by mariaforsen** [comment]
Sv. modellbilracing ET radiostyrd racing, spårstyrd racing, slotracing https://sv.wikipedia.org/wiki/Radiostyrd_bilsport https://sv.wikipedia.org/wiki/Sp%C3%A5rstyrd_racing
