### ISSUE TITLE
Mommila (Lammi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9392]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mommila (Lammi)](http://www.yso.fi/onto/yso/p124922)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaanko muotoon Hietoinen (Hausjärvi) tai Mommila-Hietonen (Hausjärvi)?
Kylä siirtynyt kuntaliitosten myötä Lammilta Hämeenlinnan kautta Hausjärvelle. Hausjärvellä myös toinen Mommila-nimellä tunnettu kylä.

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Hietoinen & https://fi.wikipedia.org/wiki/Mommila

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
**Hietoinen (Hausjärvi)** 
- MML ja kunnan karttapalvelu käyttävät tätä nimimuotoa.  Ongelmaksi tässä ratkaisusa voi nousta se, että Mommila ei näkyisi enää kuvailuissa paikkaterminä. Yhdistelmämuotoakin näkee, joten sitäkin voisi harkita.
- KT Mommila-Hietoinen, Hietoinen (Lammi), Mommila (Lammi), Hietoinen, Mommila  
- YK Hausjärvi  
- http://paikkatiedot.fi/so/1000772/10114751
- https://www.wikidata.org/wiki/Q11862546

Eri kuin **Mommila (Hausjärvi)** 
**- tämä luotava uuten käsitteenä**
- KT Mommila  YK Hausjärvi
- http://paikkatiedot.fi/so/1000772/10114488  
- Paikanlaji: Kylä tai kulmakunta
- https://www.wikidata.org/wiki/Q11883141
