### ISSUE TITLE
Muotkatunturi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9397]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Muotkatunturi](http://www.yso.fi/onto/yso/p182188)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

muutetaan muotoon Muotkatunturin erämaa-alue?

**Perustelut ehdotukselle**

huomautuksen mukaan tarkoittaa erämaa-aluetta, paikkatietoalustalla erikseen Muotkatunturit (tunturiryhmä)

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Kannatan muutosta muotoon "**Muotkatunturin erämaa-alue**"
- YK Inari, Utsjoki
- https://www.wikidata.org/wiki/Q6305899 
- http://paikkatiedot.fi/so/1000772/10896708 
- Paikanlaji: Erämaa-alue

Erikseen tunturiryhmä nimellä "**Muotkatunturit**"  
- YK Inari, Utsjoki (kunnaraja menee alueen keskeltä)
- https://www.wikidata.org/wiki/Q24322365 
- https://fi.wikipedia.org/wiki/Muotkatunturit 
- http://paikkatiedot.fi/so/1000772/10792073
- Paikanlaji: Kohoumaryhmä

**Comment by ilona-x** [comment]
Ehdin jo aiemmin lisätä tuolle Muotkatunturille pnr-linkin ja yläkäsitteeksi pnr:n mukaisesti Inarin. Wikidata-linkki jo olikin.

Melinda-viitteet näyttäisivät käsittelevän erämaa-aluetta.

**Comment by mirmaid** [comment]
Muutetaan > Muotkatunturin erämaa-alue
