### ISSUE TITLE
aasialaisamerikkalainen kirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9398]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aasialaisamerikkalainen kirjallisuus](http://www.yso.fi/onto/yso/p21825)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

poistetaan SLM-sanastosta, myös afroamerikkalainen kirjallisuus ja amerikansuomalainen kirjallisuus...

**Perustelut ehdotukselle**

ei kai tällaisia ole tarkoitus käyttää, jos on niin pitäisi lisätä paljon muitakin vastaavia sanastoon

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
Tämäntyyppisiä on vain nämä kolme slm:ssä.  Melindassa:
- afroamerikkalainen kirjallisuus (slm/fin)  64 kpl  
- aasialaisamerikkalainen kirjallisuus (slm/fin) 4 kpl 
- amerikansuomalainen kirjallisuus 0 kpl

**Comment by jtuohini** [comment]
Tieto olisikin paremmin ilmaistavissa kentässä 386, ks. [Sisällönkuvailuopas, luku 13 (Tekijän ominaisuudet)](https://www.kiwi.fi/pages/viewpage.action?pageId=130548122).

**Comment by AuHo22** [comment]
Afroamerikkalaisen kirjallisuuden lisäksi on jonkin verran käytetty esimerkiksi termiä ruotsinsuomalainen kirjallisuus ; suomenruotsalainen kirjallisuus oli puolestaan yleisten kirjastojen pitkäaikainen toive saada kaunokirjallisuuden kuvailuun. Voidaanko näitä poistaakaan ainakaan tässä vaiheessa kun 386-kentän käyttöä ei juurikaan ole, vrt. myös lastenkirjallisuus kiteytyneenä ilmaisuna ja siitä käyty keskustelu 385-kenttään siirrosta? local?

**Comment by mirmaid** [comment]
Ei muutosta. Mahdollisesti jatkossa riittäisi vastaavien tekijää kuvaavien termien käyttö 386-kentässä (tekijän ominaisuudet).
