### ISSUE TITLE
Savolankylä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9415]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Savolankylä

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

http://paikkatiedot.fi/so/1000772/10464856

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Savolankylä : poimintoja historiasta

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [Savolankylä](http://finto.fi/yse/fi/page/Y509415)

**Comment by jarmosaarikko** [comment]
Tyyppi: kylä tai kulmakunta. YK Ähtäri. 
On niin pieni kylä/paikka, ettei ole edes Ähtärin wikipedia-sivulla sivukylien listassa. on kuitenkin omat fb-sivut https://facebook.com/savolankylansivut/
