### ISSUE TITLE
Fribourg

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9416]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Fribourg](http://www.yso.fi/onto/ysa/Y112668) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Jaetaan kahtia sekä lisätään tarpeelliset KT-muodot, kuten "Freiburg (Sveitsi : kantoni)" ja "Freiburg (Sveitsi)" tms. 

#### Perustelut ehdotukselle   

Kattaa nyt sekä kaupungin että kantonin, joten on merkitykseltään epämääräinen. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Fribourg (kantoni) ja Fribourg (kaupunki)

**Comment by mirmaid** [comment]
Genevellä sama huomautus.
