### ISSUE TITLE
Björkön

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9418]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Björkön](http://www.yso.fi/onto/yso/p110851)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennetään

**Perustelut ehdotukselle**

Onko todella (tässä muodossa) saari Mustasaaressa, kuten huomautuksessa sanotaan? Ks. Paikkatietoikkuna ja esim. Wikipedia https://fi.wikipedia.org/wiki/Bj%C3%B6rk%C3%B6_(Mustasaari)

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
toinen ehdotus samasta: https://github.com/Finto-ehdotus/YSE/issues/9455
