### ISSUE TITLE
Euraasia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9419]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Euraasia](http://www.yso.fi/onto/yso/p125927)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

pitäisikö Euraasian  olla Euroopan ja Aasian yläkäsite -- tai ainakin RT-suhde näihin?

**Perustelut ehdotukselle**

hierarkian korjaus/täydennys

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Lisätty RT-suhde. Jos lisätään hierarkkisia suhteita, sen voisi tehdä vähän laajemmin.
