### ISSUE TITLE
huijarisyndrooma

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9421]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

huijarisyndrooma 

#### Ehdotettu termi ruotsiksi   

bluffsyndromet 

#### Ehdotettu termi englanniksi   

impostor syndrome 

#### Vaihtoehtoiset termit ja ilmaisut   

huijari-ilmiö (ei niin selkeä) 

#### Vastaava käsite muussa sanastossa   

LCSH : Impostor phenomenon 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[55 Psykologia](http://www.yso.fi/onto/yso/p26543) 

#### Tarkoitusta täsmentävä selite   

Here are entered works on feeling like a fake or fraud although one is successful. Works on impostors in the legal sense are entered under [Impostors and imposture.] LCSH 

#### Perustelut ehdotukselle   

Olemassaoleva ilmiö ja aineistoa tietokannoissa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Huijareiden vallankumous : huijarisyndrooman yhteiskunnallisilla juurilla / Sanni Lehtinen 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [huijarisyndrooma](http://finto.fi/yse/fi/page/Y509421)

**Comment by jarmosaarikko** [comment]
https://www.wikidata.org/wiki/Q1073568  - https://fi.wikipedia.org/wiki/Huijarisyndrooma - https://sv.wikipedia.org/wiki/Bluffsyndromet - https://en.wikipedia.org/wiki/Impostor_syndrome

**Comment by mirmaid** [comment]
Lääketieteen termit: huijarioireyhtymä: _huijarisyndrooma | psykologinen ilmiö, jossa ihminen kokee saavuttaneensa asemansa osaamisen sijasta hyvällä onnella tai harhauttamalla muut luulemaan itseään todellista kyvykkäämmäksi_

**Comment by YSO-kokous** [comment]
hyväksytään muodossa huijarisyndrooma
