### ISSUE TITLE
autonasentajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9422]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[autonasentajat](http://www.yso.fi/onto/yso/p3700)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

autonasentajat ja automekaanikot  pitäisi olla eri prefLabel englanniksi.  

**Perustelut ehdotukselle**

molemmissa nyt sama eng. preflabel ja "car mechanics" LCSH linkki  [Automobile mechanics](http://id.loc.gov/authorities/subjects/sh85010164)
Autonasentaja on "virallinen" ammattiermi suomalaisessa koulutusohjelmassa.  Lähde: [https://ec.europa.eu/esco/portal/occupation](https://ec.europa.eu/esco/portal/occupation) ajoneuvoasentaja ESCO Code 7231.10 
- KT automekaanikko, autonasentaja.    
- EN: vehicle technician, KT automotive mechanic,  automotive technician, auto mechanic   

Jos ovat eri käsite, niin muutetaanko autonasenaja prefLabel muotoon "automotive technician"?    Voisi lisätä KT **ajoneuvoasentaja** joka on nykyään ammattitutkinnon termi. Tämän eng termi olisi "**vehicle technician**".    

Vaihtoehtoisesti:  Ellei eroa ole käsitteiden välillä, niin voiko ne yhdistää?  

Melindassa: autonasentajat  35 kpl, automekaanikot 29 kpl.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mariaforsen** [comment]
Sv. wikipediassa on myös annettu tällainen merkitys montör/asentaja-termille: https://sv.wikipedia.org/wiki/Bilmont%C3%B6r

**Comment by mirmaid** [comment]
https://kokeile.tyomarkkinatori.fi/ammatit/Ajoneuvoasentaja

**Comment by mirmaid** [comment]
Näyttäisivät minusta olevan sama asia ja käytetty ristiin. Kumpikaan ei tarkoita erityisesti autoteollisuudessa autoja rakentavaa työntekijää. 

_Ajoneuvoasentaja_ on nykyinen koulutusnimike, voi olla joko päätermi tai ohjaustermi?

**Comment by YSO-kokous** [comment]
yhdistetään autonasentajat ja automekaanikot ja ajoneuvoasentajat
ajoneuvonasentaja KT autonasentajat, automekaanikot

**Comment by mariaforsen** [comment]
Sv. fordonsmekaniker
