### ISSUE TITLE
geologiset kartat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9424]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[geologiset kartat](http://www.yso.fi/onto/yso/p10835)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään SLM-sanastoon

**Perustelut ehdotukselle**

Tarvitaan aineistotyyppinä

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
Geologiset kartat ovat tärkeitä esimerkiksi kaivostoiminnassa, rakentamisessa sekä aluesuunnittelussa. https://fi.wikipedia.org/wiki/Geologinen_kartta

Ovatko nykyisin yleensä sähköisiä muodoltaan? 
https://www.suomi.fi/palvelut/gtk-n-karttapalvelut-geologian-tutkimuskeskus-gtk/eddf3845-d86a-401d-828e-1da7236a2b57

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. geologiska kartor
