### ISSUE TITLE
Päämaja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9425]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Päämaja](http://www.yso.fi/onto/ysa/Y105059) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Siirretään Kantoon tai muutetaan monikkoon 

#### Perustelut ehdotukselle   

Jos tällä viitataan vain ja ainoastaan Suomen ylipäällikön esikuntaa, on viittauksen kohde yhteisö. Ja yhteisöt pitäisi olla Kanto-tietokannassa, ei YSO-asiasanastossa.

Ja tällä taas viitataan päämajaan yleensä, pitäisi sanan olla pienellä ja monikossa.

"Päämaja tarkoittaa paikkaa ja tilaa, jossa ylin sodanjohto pääasiallisesti sijaitsee. Tilapäinen alijohtopaikka, jossa johto ei sijaitse vakinaisesti, on komentopaikka, joita voi olla useita." (https://fi.wikipedia.org/wiki/P%C3%A4%C3%A4maja) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by fantsby-m** [comment]
Käytetty Melindassa asiasanana johdonmukaisesti Suomen armeijan päämajasta toisen maailmansodan aikana.
Muutaman kerran myös kentässä 653, samassa merkityksessä (+ kerran "Suomen Armeijan päämaja"). 
Kerran 1918 sotaan liittyen ("Päämaja Seinäjoella 1918").

Tällä tuskin on haluttu viitata "päämajaan yleensä", kun engl. asiasanaksikin on valittu _Päämaja_. 

Kantossa on jo _Suomi. Päämaja_ (https://finto.fi/finaf/fi/page/000035800). 
Kanton tietueessa on YHTEISÖN TOIMINTAAN LIITTYVÄ AJANJAKSO 1918/1944 - joten em. 1918 sotaan liittyvä julkaisu menisi tähän myös?

**Comment by mariaforsen** [comment]
Ruotsin vastine ei (luonnollisesti) rajaudu Suomeen. Ks. esim. https://www.forsvarsmakten.se/sv/organisation/hogkvarteret/

**Comment by mirmaid** [comment]
Kannatan kyllä tämän siirtämistä Kantoon, vaikea kuvitella aineistoa jossa käsiteltäisiin yleisesti päämajoja.

**Comment by YSO-kokous** [comment]
Päätös: Poistetaan YSOsta. Riittää, että on Kantossa.
