### ISSUE TITLE
maaseudun kehittäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9426]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maaseudun kehittäminen

**Ehdotettu termi ruotsiksi**

landsbygdsutveckling

**Ehdotettu termi englanniksi**

rural development

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Maaseudun kehittäminen on EU:n yhteisen maatalouspolitiikan (CAP) toinen pilari.  https://ec.europa.eu/info/food-farming-fisheries/key-policies/common-agricultural-policy/rural-development_fi

**Ehdotettu yläkäsite YSOssa (LT)**

 [maatalouspolitiikka](http://www.yso.fi/onto/yso/p10881)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikidata](https://www.wikidata.org/wiki/Q3773637), [wikipedia](https://en.wikipedia.org/wiki/Rural_development), [LCSH](http://id.loc.gov/authorities/subjects/sh85115899), [AFO](http://www.yso.fi/onto/afo/p3213), [JUPO](http://www.yso.fi/onto/jupo/p3421), [KOKO](http://www.yso.fi/onto/koko/p71105)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

maa- ja metsätalousministeriön ja  EU dokumentit

**Ehdottajan organisaatio**

Finto/asiakaspalaute #KK-02771820#

**Comment by jarmosaarikko** [comment]
jahas, muistikatkos - tämä olikin jo ehdotettu.... #9255
