### ISSUE TITLE
yhteinen maatalouspolitiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9427]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

yhteinen maatalouspolitiikka

**Ehdotettu termi ruotsiksi**

den gemensamma jordbrukspolitiken

**Ehdotettu termi englanniksi**

common agricultural policy

**Tarkoitusta täsmentävä selite**

"Yhteistä maatalouspolitiikkaa toteutetaan elintarviketuotannon, ympäristön ja maaseudun hyväksi. "@fi |"EU:s jordbrukspolitik handlar om maten, miljön och landsbygden. "@sv | 
"The common agricultural policy is about our food, the environment and the countryside. "@en

**Perustelut ehdotukselle**

EU:n maatalouspolitiikka on erittäin tärkeä  suomalaiselle maataloudelle

**Ehdotettu yläkäsite YSOssa (LT)**

 [EU-politiikka](http://www.yso.fi/onto/yso/p8435)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

 EU:n yhteinen maatalouspolitiikka, EU:s gemensamma jordbrukspolitik, CAP

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

tarvitaan Maa- ja metsätalousministeriön ja EU-asoiden aineistojen kuvailussa

**Ehdottajan organisaatio**

Finto/asiakaspalaute #KK-02771820#

**Comment by jarmosaarikko** [comment]
Tämä olikin jo ehdotettu aiemmin.... #9256
