### ISSUE TITLE
Tähtien sota -elokuvat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9429]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Tähtien sota -elokuvat 

#### Ehdotettu termi englanniksi   

Star wars films 

#### Ehdotettu termi ruotsiksi   

Stjärnornas krig-filmer 

#### Vaihtoehtoiset termit ja ilmaisut   

Star wars -elokuvat 
Star wars -filmer 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85127382> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534) 

#### Perustelut ehdotukselle   

On paljon aineistoa, joka käsittelee Tähtien sota -elokuvia joukkona, eikä aina ole mielekästä aina muodostaa kohdeviittausta yksittäisestä elokuvasta; vastaavantyyppinen kuin olisi taannoin ehdottamani "James Bond -elokuvat" -asiasana. Huom. TÄMÄ ON ASIASANAEHDOTUS, EI EHDOTUS TEOKSEN AUKTORISOIDUKSI HAKUTIEDOKSI! 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Tähtien sota -elokuvat](http://finto.fi/yse/fi/page/Y509429)

**Comment by jarmosaarikko** [comment]
"Star Wars"  https://www.wikidata.org/wiki/Q22092344 -   Termi voisi olla myös  "Star Wars (elokuvasarja)"
LCSH: "Star Wars films".  Kts myös: 
- "James Bond film series"  https://www.wikidata.org/wiki/Q2484680   tai  "James Bond (elokuvasarja)"
- "James Bond films"  http://id.loc.gov/authorities/subjects/sh85069330

Tämän YK on "elokuvasarjat"   https://www.wikidata.org/wiki/Q24856 - ei ole YSOssa, voisiko lisätä samalla?
YSOssa on vain sarjafilmit KÄ [televisiosarjat](http://www.yso.fi/onto/yso/p25701)

Lisäksi voisi myös olla käsite "Tähtien sota" / "Star Wars" brandinä  kuten: https://www.wikidata.org/wiki/Q462  jos on tarvetta kuvailla esineitä. julisteita, pienpainatteita, yms.

**Comment by mirmaid** [comment]
Pelien puolella auktorisoitu jonkin verran vastaavia, mielestäni ovat kuitenkin enemmän teoksia/teossarjoja. Sisku-ryhmä voisi keskustella aiheesta?

**Comment by YSO-kokous** [comment]
Odotetaan Sisku-ryhmän päätöstä.

**Comment by mirmaid** [comment]
Vastaavia (?)

Uuni Turhapuro -elokuvat
Avengers-elokuvat
Batman-elokuvat
Matrix-elokuvat

Tiina-kirjat
Neiti Etsivä -kirjat
Iijoki-sarja
Muumi-kirjat

**Comment by mirmaid** [comment]
LCSH: 
100 | 1_ \|a Keene, Carolyn. \|t Nancy Drew mystery stories
https://en.wikipedia.org/wiki/Nancy_Drew_Mystery_Stories: The Nancy Drew Mystery Stories is the long-running "main" Nancy Drew series, which was published under the pseudonym Carolyn Keene. There are 175 novels — plus 34 revised stories — that were published between 1930 and 2003 under the banner; Grosset & Dunlap published the first 56, and 34 revised stories, while Simon & Schuster published the series beginning with volume 57.

**Comment by jtuohini** [comment]
_Nancy Drew Mystery Stories_ on julkaisusarja, ei joukko samanaiheisia kirjoja. Tärkeää tässä pystyä erottamaan aidot sarjat (jotka on julkaistu yhteinellä nimekkeellä) joukosta erillisiä teoksia, jotka tunnetaan jollakin yhteisellä nimellä, kuten "James Bond -elokuvat".

**Comment by mirmaid** [comment]
LCGFT-sanastossa _Star Wars films_ ja _James Bond films_ ovat ohjaustermejä _Science fiction films_ ja _Spy films_ & _Action and adventure films_ -käsitteille. LCSH:ssa ne ovat omina käsitteinään. Ilmeisesti siis Kongressin kirjaston mielestäkään ne eivät ole oikeita genrejä, vaan teoksen ja sen johdannaisteosten muodostamia teosryhmiä. Oma logiikan tajuni mieltää nämä ennemmin teossarjojen kaltaisiksi, kuin genrejä muistuttavaksi asioiksi, mutta jos näkemys on, että missään tapauksessa näitä ei tulla ottamaan teossanastoon, koska LC:kään ei tee niin, niin sitten varmaan ainoa mahdollisuus on YSO tai ei mitään. Jos otetaan YSOon, niin toivottavasti niitä ei sitten ala näkyä genren tavoin käytettynä Star Wars -elokuvien tietueissa, kun termi pitäisi LC:n logiikalla rajautua ainoastaan kuvaamaan aineiston aihetta.

**Comment by AuHo22** [comment]
LCSH **Star Wars films**: Here are entered works on Star Wars films discussed collectively. Works on individual Star Wars films are entered under the specific title. 
Eli käytettäisiin sitten seuraavaan tapaan, 630_00-kentässä on siis yksittäinen elokuva, ja asiasanakentässä koko sarja elokuvia?
https://catalog.loc.gov/vwebv/staffView?searchId=7161&recPointer=8&recCount=25&bibId=22770594

630	00	 |a Star wars (Motion picture) |v Miscellanea.
650	_0	 |a Star Wars films |v Miscellanea.

Tietenkin kun katsoo jo suomenkielisestä wikipediasta elokuvasarjojen tai samanaiheisten elokuvien joukkoa, niin niitä todellakin riittää samoin kuin kirjasarjoja: 
https://fi.wikipedia.org/wiki/Luokka:Elokuvasarjat
https://fi.wikipedia.org/wiki/Luokka:Kirjasarjat

LC:ssä sitten kuitenkin esim.  130 James Bond (Comic strip) -> eli jotenkin tuntuisi loogisemmalta, että voisi olla yhtä hyvin vaikkapa 630 James Bond (elokuvasarja), tai  630 James Bond -elokuvat jne.

**Comment by jtuohini** [comment]
Tapaus "130 James Bond (Comic strip)" viittaa yksittäiseen _James Bond_ -nimiseen usean tekijän luomaan strippisarjakuvaan, ei joukkoon eri sarjakuvia, jotka kertovat James Bondista. X30 on varattu yksittäiselle teokselle tai moniosaiselle teokselle, ei joukolle samankaltaisia teoksia. Ja mainittu strippisarjakuva on X30-muotoa eikä X00+t on H405-listan peruja, ks. https://www.loc.gov/aba/publications/FreeSHM/H0405.pdf > Comic strips ja sen loppuviite.

**Comment by mirmaid** [comment]
Mikä tahansa elokuvayhtiö ei voisi kuitenkaan tehdä Star Wars, Marvel tai James Bond -elokuvaa. Elokuville on suositeltuja katsomisjärjestyksiä (esim. https://editorial.rottentomatoes.com/guide/marvel-movies-in-order/ ja lukuisia muita). Näen aika lailla mielipidekysymyksenä, milloin jokin elokuvasarja katsotaan teossarjaksi, mutta ilman muuta edellä mainitut ovat enemmän kuin vain joukko samankaltaisia elokuvia - kaikki supersankarielokuvat ovat ainakin ei-harrastajan mielestä samankaltaisia, kaikki scifi-elokuvat tai historialliset draamaelokuvat vastaavasti. Mutta tosiaan koska lienee selvää, että näitä ei tulla ottamaan teosauktoriteettisanastoon (jos sellainen joskus saadaan), niin päätös on sen välillä, otetaanko sitten YSOon vai ei mihinkään. 

Varmaan käyttöhuomautus ainakin hyvä lisätä, ettei käytettäisi genrenä (ehkä auttaa ehkä ei).

**Comment by AuHo22** [comment]
Heräsi oikeastaan myös kysymys sitten musiikin yhtenäistettyjen nimekkeiden käytöstä teosauktoriteeteissa, onko niin että ne jatkossakin linkittyvät tekijän mukaan, eivät teosjoukon mukaan, kuten esim. Sisällönkuvailuoppaan esimerkit:

600 14  |a  Bruckner, Anton,  |d  1824-1896.  |t  Sinfoniat -> Bruckner-linkki
Wagner, Richard,  |d  1813-1883.  |t  Ring des Nibelungen,  |n  WWV86.  |0  (FI-ASTERI-N)000063207

Tähtien sota -elokuvat on joka tapauksessa hyödyllinen ihan jo kirjallisuuskuvailun takia (lastenkirjallisuutta jossa elokuvan hahmoja jne.) - miettii sitten tulevaisuutta ja sitä, kuinka paljon mm. kirjallisia oheistuotteita tulee olemaan tietynlaisista suosikkisarjoista. Jos asiasanakentässä tulevaisuudessa, niin voi tietenkin käyttää myös 653-kenttää, ja YSO-kokous voi hyväksyä useampien esiintymien myötä? Myös kirjallisuus- ja elokuvatutkimuksessa voisin ajatella tämäntyyppisiä tulevan vastaan.

**Comment by jtuohini** [comment]
Musiikin ja kirjallisuuden osalta _yhden tekijän_ teosten koosteiden kokoavat yhtenäistetyt nimekkeet perustuvat RDA:n lukuihin 6.2.2.10.2–6.2.2.10.3 sekä 6.14.2.8.2–6.13.2.8.4, mutta koska elokuvat ovat _yhteistyössä tehtyjä_ teoksia, eivät nuo sääntökohdat sovellu niihin (ks. RDA, luku 6.27.1.3 > Poikkeukset > Liikkuva kuva: "Elokuvien, videoiden, videopelien tms. auktorisoitu hakutieto muodostetaan teoksen ensisijaisesta nimekkeestä").

**Comment by AuHo22** [comment]
Yllä:  "tunnetaan jollakin yhteisellä nimellä, kuten "James Bond -elokuvat"
Sepitetyn nimekkeen mahdollisuudet?

**Comment by jtuohini** [comment]
"Sepitetyt nimekkeet. Tämä ohje pätee teoksiin, joille ei löydy nimekkeitä teoksen sisältävistä manifestaatioista tai tietolähteistä." (RDA, 6.2.2.6.2) Eli esimerkiksi artikkeli, joka on julkaistu ilman otsikkoa, tai jotkin antiikin tekstifragmentit. Bond-elokuvilla on jokaisella oma nimensä, joten siltäkään osin ei kyseinen sääntökohta päde. Ja edelleen: joukko erillisiä teoksia ei ole teoskokonaisuus, vaikka ne miellettäisiin jonkinlaiseksi sarjaksi tms. _à la_ Tohtori Mabuse -elokuvat" tai Shakespearen kuningasnäytelmät.

**Comment by tpalonen** [comment]
Voisiko KAUNO-ontologia olla sopiva osoite tällaisille? James Bond, Sherlock Holmes ym voisivat olla satuolentojen alla kuten nyt ovat esim. Joulupukki ja smurffit. Star Wars voisi niin ikään olla käsite KAUNOssa esim. kulttuuriset ilmiöt alla. En tiedä ratkaiseeko tämä sitä, miten toteutettaisiin kuvailussa, mutta minusta tuntuu, että KAUNO olisi joka tapauksessa tämän tyyppisille käsitteille parempi sijoituspaikka kuin YSO.

**Comment by AuHo22** [comment]
Loppujen lopuksi, esim. James Bond -elokuvahistoriaa on voitu kuvailla kuten seuraavassa: 
978-1-7354616-2-5
60014 | \|a Bond, James \|c (fiktiivinen hahmo)
650 7 | \|a elokuvat \|2 yso/fin \|0 http://www.yso.fi/onto/yso/p1235
jne. elokuvahistoria/elokuvatutkimus tms.

Tämä ei kuitenkaan ratkaise kaikkea, ja seuraavissa on sitten jo erilaista Star Wars -elokuviin liittyvää kuvailua, jossa Star Wars on jo melkein jonkinlainen brändi, nämä kuitenkin sijoittuvat kuvailussa tietokirjallisuuteen: 978-0-7440-3005-1 tai 978-1-80336-350-9

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään muodossa Star wars -elokuvat.

**Comment by mirmaid** [comment]
^ Kirjoitetaan varmaan isolla Star Wars -elokuvat.

**Comment by mariaforsen** [comment]
Sv. Star Wars-filmer HT Stjärnornas krig-filmer 
https://sv.wikipedia.org/wiki/Star_Wars
jfr https://sv.wikipedia.org/wiki/Stj%C3%A4rnornas_krig_(film)

**Comment by jtuohini** [comment]
Miksi englanniksi, kun kokonaisuus tunnetaan suomenkieliselläkin nimellä (ks. esim. https://fi.wikipedia.org/wiki/T%C3%A4htien_sota)?

**Comment by mirmaid** [comment]
^ Ratkaisu liittyi siihen, että uudemmat elokuvat on julkaistu meilläkin Star Wars -nimellä. Ryhmä kyllä yleensä suosii suomenkielisiä muotoja, jos ei ole hyvää perustelua toisenlaiselle päätökselle.
