### ISSUE TITLE
temperointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9430]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[temperointi](http://www.yso.fi/onto/yso/p26884)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan, lisätään myös musiikkimerkityksessä?

**Perustelut ehdotukselle**

Myös musiikkimerkityksessä, esim. How to deal with the syntonic comma in music education? : recognition, preferences of usage, and utility / Markku Viitasaari.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. temperering (musik)

**Comment by YSO-kokous** [comment]
Odotetaan Muusan kantaa

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
Musiikkitermin muodoksi _temperointi (musiikki)_ ja seuraavat suhteet:
LT kohdistuva toiminta
RT viritys (soittimet)

**Comment by YSO-kokous** [comment]
### Päätös
temperointi (musiikki)  LT kohdistuva toiminta RT viritys (soittimet)
temperointi (lämpötila)   esim. termperointi ruoanvalmistuksessa tai teräksen valmistuksessa

**Comment by mariaforsen** [comment]
Sv. 
-temperering (musik)
-temperering (temperatur)

**Comment by MUUSA-kokous** [comment]
Määritelmäehdotus: Soittimen virittäminen jonkin temperoidun viritysjärjestelmän mukaisesti.

**Comment by jtuohini** [comment]
Jotenkin pitäisi ehkä ilmaista, että kyse on siis kiinteävireisten soittimien virittämisestä (erona virittämiseen yleensä)?
