### ISSUE TITLE
julkinen omistus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#944]
#### Ehdotettu termi suomeksi

julkinen omistus
#### Ehdotetut ohjaustermit

julkisen ektorin omistus, valtion omistus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/ysa/ryhma_71)
[75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/ysa/ryhma_75)
#### Lähde

Lähde: ELSST

**Luontipäivämäärä:** 17.10.2003

**Muokkauspäivämäärä:** 17.10.2003, 16.12.2008

**Voyager-id:** 127595

**Termiehdotus Fintossa:** [julkinen omistus](http://finto.fi/yse/fi/page/Y327595)

**Comment by mirmaid** [comment]
Hyväksytty YSA-kokouksessa 1/2016.
