### ISSUE TITLE
pikkuleivät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9444]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pikkuleivät](http://www.yso.fi/onto/ysa/Y112920) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vrt. keksit. Pitääkö yhdistää (keksit ja pikkuleivät tms.), jotta saadaan kielet täsmäämään. Tai voiko olla eng. esim. pastry biscuits? 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: pieni makea leivonnainen. _Kakkua ja kaikenlaisia pikkuleipiä. Suklaapikkuleipä._

**Comment by mirmaid** [comment]
https://www.meillakotona.fi/artikkelit/isoaidin-pikkuleivat

Itse en sanoisi lusikkaleipiä tai herrasväen pikkuleipiä kekseiksi, muita varmaan kyllä. Mitä mieltä muut?

**Comment by fantsby-m** [comment]
_keksit ja pikkuleivät
kex och småbröd
cookies, crackers, and biscuits_
?

Mutta onko yhdistäminen oikeasti tarpeellista?

**Comment by ilona-x** [comment]
Eli onko ongelma kielten vastaavuudessa vain englannin kielen osalta? Jos ongelma on vain englannin kielen osalta, niin en ehkä lähtisi näitä yhdistämään.

**Comment by mariaforsen** [comment]
Mielestäni nykyinen tilanne on aivan ok ruotsiksi. Kun keksi on "pieni, kuiva ja kevyt leivonnainen" (Kielitoimiston sk.) ja kex on "liten torr, spröd kaka". Pikkuleivät=småbröd/småkakor. Toki saattaa olla että nämä käytetään päällekkäisinäkin, mutta tällä kertaa ei ole varsinaista ruotsin ongelmaa.

**Comment by YSO-kokous** [comment]
Äänestyspäätös:  yhdistetään pikkuleivät ja keksit.
