### ISSUE TITLE
pennut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9445]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pennut](http://www.yso.fi/onto/yso/p3899)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan tai yhdistetään 

**Perustelut ehdotukselle**

Eri kielillä on eri nimityksiä, esim. ruotsinkielinen "valp" on koiran pentu, muttei esim. kissan tai muun eläimen. Ks. Kielitoimiston sanakirja ja esim. https://fi.wikipedia.org/wiki/Pentu  

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
koiranpennut (puppies) + kissanpennut (kittens) ominaan? -> ehkä tarpeellisia, voidaanko muita kuvata poikaset-termin (animal young) avulla, esim. cub -> The young of certain other animals, including the bear, wolf, lion and tiger.

**Comment by ilona-x** [comment]
LCSH:
**puppies** http://id.loc.gov/authorities/subjects/sh85109152
**kittens** http://id.loc.gov/authorities/subjects/sh85072589

SAO:
**hundvalpar** https://id.kb.se/term/sao/Hundvalpar

**Comment by mariaforsen** [comment]
Myös SAO: kattungar https://id.kb.se/term/barn/Kattungar ja yleistermi: https://id.kb.se/term/sao/Djurungar

Unge= "avkomma till (högre stående) djur" eli ruotsin osalta olisi ok että kaikenlaisten eläinten poikaset kuvattaisiin poikaset-termillä. Ja pennut pitäisi siis tarkentaa tai poistaa, jotta saadaan käännökset täsmäämään.

**Comment by mirmaid** [comment]
Kuinkahan kattava on _djurungar_ vs. _poikaset_? Sanastossa on _vasat, varsat_ jne. Toisaalta suomeksi esim. petoeläimillä yleensä _pennut_, jotain ohjaustermejä ehkä pitäisi lisätä ("suden poikaset" vähän erikoinen, "hirven poikanen" ei kyllä mahdollinen).

**Comment by AuHo22** [comment]
susi + poikaset jne. sv. ungar sanastossa tällä hetkellä? Mielestäni ei ohjaustermejä tarvita - tai sitten ehkä kaupunkilaisille, mutta agraaritaustaa meillä kaikilla vielä? Sekä poikasia että pentuja (ja penikoita, YSOssa penikointi) näkee teksteissä, esim. http://www.suurpedot.fi/lajit/susi/elintavat-ja-lisaantyminen.html

**Comment by mirmaid** [comment]
https://svenska.yle.fi/artikel/2016/04/22/hogholmens-forsta-djurunge-varen-har-fotts

Tätä mietin, että jos djurunge voi olla myös vasa, niin sitten on tietueessa hirvelläkin poikaset. Vaikka eipä kai se sen oudompaa sitten ole kuin koirien ja kissojen _koiraat_...

**Comment by AuHo22** [comment]
Sanastossa jo siis vasat, sv. kalvar (hjortdjur) LT hirvieläimet

**Comment by mariaforsen** [comment]
Kun sanastossa on vasat jne. erikseen niin en näe uhkana että käytettäisiin termiä djurungar/ungar niistä (ainakaan sen enempää kuin suomeksikaan). Yllä mainitussa uutisessa on haluttu painottaa että ensimmäinen "eläimen pienokainen" on syntynyt, jos artikkelissa lukisi "första kalven har fötts.." niin sehän kertoisi vain sen että ensimmäinen "sorkkaeläimen pienokainen" on syntynyt, ja siinä ei nyt vain olisi mitään järkeä.

Vasat + vasikat = kalvar ruotsiksi, sen takia on yllä mainitulla tarkenne.

**Comment by mirmaid** [comment]
^ Ymmärrän tämän, mutta suomeksi otsikko "Korkeasaaressa syntyi kevään ensimmäinen poikanen" olisi ainakin omaan korvaani aika erikoinen, jos siellä olisi syntynyt hirvenvasa. Ei kuitenkaan lähimainkaan yhtä kummallinen, kuin jos todettaisiin _koirashirvien_ osallistuneen hellästi poikasen hoitoon.

**Comment by mirmaid** [comment]
Eli ilmeisesti pennut KÄ poikaset? Tämä voi tuon ruotsinkielisen muodon mukana tulla joskus myös tapauksiin, joissa suomeksi ei puhuttaisi poikasista tai pennuista, mutta sen osalta toki tilanne ei muutu nykyisestä.

**Comment by mirmaid** [comment]
Ehdotus: pennut KÄ poikaset
