### ISSUE TITLE
mikrosirut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9446]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mikrosirut](http://www.yso.fi/onto/ysa/Y151343) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

LCSH KÄ integrated circuits. Mihin tällä viitataan tarkalleen, entä eläinten tunnistesirut? 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Kielitoimiston sk. mikrosiru > siru: mikropiirejä sisältävä (tav. piistä tehty) pieni komponentti, mikrosiru.
https://sv.wikipedia.org/wiki/Mikrochip  

Sanastossa on erikseen "tunnistusmerkintä (lemmikkieläimet)" eli siltä osin ok. Mutta sanastossa on myös mikropiirit (ET integroidut piirit) onko se siis ongelmallista?
Ks. https://termipankki.fi/tepa/fi/haku/mikrosiru

SAO: https://id.kb.se/term/sao/Integrerade%20kretsar

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: mikropiiri: sähk. hyvin pienikokoisia elektronisten laitteiden rakenneosayhdistelmiä, integroitu piiri.

**Comment by mirmaid** [comment]
Mikrosirujen käyttöä on laajemminkin, kuin vain tunnistusmerkintänä. Esim. https://suomenkuvalehti.fi/jutut/ulkomaat/laakkeita-annosteleva-mikrosiru-korvaa-paivittaisen-injektiokynan/ - tämän tyyppisissä mikropiirit ei olisi oikein toimiva.

**Comment by mirmaid** [comment]
Ehdotus: ei muutosta.
