### ISSUE TITLE
islamilaiset maat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9447]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[islamilaiset maat](http://www.yso.fi/onto/ysa/Y136086) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "muslimimaat" 

#### Perustelut ehdotukselle   

Runsaasti käytetty nimitys, josta olisi hyvä saada viittausmuoto. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Esim. Wikipedia (lähteeksi mainittu mm. Hämeen-Anttilan Islamin käsikirja): Nykypäivän "islamilaisiin valtioihin" kuuluvat Pakistan, Mauritania, Iran[5] ja Afganistan,[6] jotka ovat "islamilaisia tasavaltoja". Muita ovat ainakin Saudi-Arabia, Oman, Jemen, Yhdistyneet Arabiemiraatit ja Bahrain. "Muslimivaltioita" ovat maat, joissa enemmistö asukkaista on muslimeja, mutta joissa šaria ei ole tärkeässä asemassa lainsäädännössä. 
https://fi.wikipedia.org/wiki/Islamilainen_valtio

Toisaalla: Maantieteellisesti ja poliittisesti islamilainen maailma yleensä tarkoittaa yleensä muslimienemmistöisiä maita. https://fi.wikipedia.org/wiki/Islamilainen_maailma
Ja: https://fi.wikipedia.org/wiki/Luettelo_muslimienemmist%C3%B6isist%C3%A4_valtioista

Onko yksiselitteistä että islamilaisilla mailla tarkoitetaan muslimienemmistöisiä maita eikä islamilaisia valtioita?

**Comment by mirmaid** [comment]
Ohjausterminä on _islamilaiset valtiot_, joten varmasti sillä voidaan tarkoittaa ainakin niitä. Rajaaminen pelkästään niihin on toisaalta myös hankalaa. Ruotsiksi on jo ohjausterminä muslimska länder.

LCSH: Islamic countries: _Here are entered works on the group of countries in which the majority of the people are Muslims or in which Islam is the established religion_.

**Comment by YSO-kokous** [comment]
Hyväksytään KT muslimimaat
