### ISSUE TITLE
runebergintorttu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9448]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

runebergintorttu 

#### Ehdotettu termi ruotsiksi   

Runebergstårta 

#### Ehdotettu termi englanniksi   

Runeberg's torte 

#### Vaihtoehtoiset termit ja ilmaisut   

Runebergin torttu 

#### Ehdotettu yläkäsite YSOssa (LT)   

[leivokset](http://www.yso.fi/onto/yso/p2453) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q1817903 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555) 

#### Tarkoitusta täsmentävä selite   

Lieriön muotoinen mantelilla maustettu (ja us. punssilla kostutettu) leivonnainen, jonka koristeena on sokerikuorrutusta ja hilloa. (https://www.kielitoimistonsanakirja.fi/runebergintorttu) 

#### Perustelut ehdotukselle   

Siinä määrin keskeinen konditoriatuote suomalaisessa kulttuuriperinnössä kuvailtavaa aineistoa myöten, että omalle asiasanalle olisi tilausta (jottei Melindan 653-kenttään ilmestyisi mitä moninaisimpia muotoja). 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [runebergintorttu](http://finto.fi/yse/fi/page/Y509448)

**Comment by mirmaid** [comment]
11 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään monikkomuodossa.  
Muutetaan myös pulla ja marenki monikkomuotoon.
