### ISSUE TITLE
raivotauti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9449]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[raivotauti](http://www.yso.fi/onto/ysa/Y161017) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen vesikauhu? 

#### Perustelut ehdotukselle   

Ei kai näitä ole tarpeen olla erikseen? Kyllä mielestäni myös eläinten yhteydessä voidaan puhua vesikauhusta. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
Jos käsitteet halutaan yhdistää, niin käytettävä termi voisi olla  KÄ Rabies KT vesikauhu, raivotauti  YK virustaudit.
Silloin lienee LCSH suhteet muutetava skos:narrowMatch suhteeksi:  
- "Rabies in animals" http://id.loc.gov/authorities/subjects/sh88003398 - raivotauti https://www.wikidata.org/wiki/Q7278725
- "Rabies" http://id.loc.gov/authorities/subjects/sh85110217 - vesikauhu https://www.wikidata.org/wiki/Q39222

**Comment by fantsby-m** [comment]
Täällä yhdistetty myös kuten yllä ehdotetaan:
https://finto.fi/mesh/fi/page/D011818

**Comment by YSO-kokous** [comment]
Päätös: yhdistetään.  Päätermiksi rabies
