### ISSUE TITLE
dissosiaatio (psykologia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9452]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

dissosiaatio (psykologia)

**Ehdotettu termi ruotsiksi**

dissosiation (psykologi)

**Ehdotettu termi englanniksi**

dissociation (psychology)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Dissosiaatio käsitteenä puuttuu.  Luokittelua ja aineistohakuja varten varten se olisi
hyödyllistä lisätä muunakin kuin häiriöin (dissosiaatiohäiriön) merkityksessä, koska se ymmärretään myös normatiivisena ihmislajille ja asettuu jatkumolle inhimillisessä
kokemusmailmassa.

**Ehdotettu yläkäsite YSOssa (LT)**

 [psykologia](http://www.yso.fi/onto/yso/p1632)

**Ehdotetut temaattiset ryhmät**

 [55 Psykologia](http://www.yso.fi/onto/yso/p26543)

**Vaihtoehtoiset termit**

 dissosiaatio

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [dissosiaatiohäiriöt](http://www.yso.fi/onto/yso/p17224)

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh85038501), [wikidata](https://www.wikidata.org/wiki/Q18663), [wikipedia](https://fi.wikipedia.org/wiki/Dissosiaatio_(psykologia))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tarvitaan teologian gradun asiasanoitukseen

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto-asiakaspalaute
**Termiehdotus Fintossa:** [dissosiaatio (psykologia)](http://finto.fi/yse/fi/page/Y509452)

**Comment by jarmosaarikko** [comment]
Oikeampi YSOn yläkäsite on  **puolustusmekanismit (psykologia)** [http://www.yso.fi/onto/yso/p5642](http://www.yso.fi/onto/yso/p5642) 
försvarsmekanismer (psykologi), defence mechanisms (mental phenomena)

**Comment by mariaforsen** [comment]
Kannatan. Myös SAOssa https://id.kb.se/term/sao/Dissociation%20%28psykologi%29

Sv. dissociation (psykologi)
