### ISSUE TITLE
herkkutatti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9453]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

herkkutatti

**Ehdotettu termi ruotsiksi**

karljohanssvamp

**Ehdotettu termi englanniksi**

Boletus edulis 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Herkkutatti
Herkkutatti (Boletus edulis, aiemmin myös kivitatti ja hepotatti[2]) on arvostettu ruokasieni, jota tavataan lähes kaikkialla pohjoisen pallonpuoliskon havu- ja sekametsissä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [tatit](http://www.yso.fi/onto/yso/p13864)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-951-40-2419-1

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [herkkutatti](http://finto.fi/yse/fi/page/Y509453)

**Comment by mariaforsen** [comment]
Sv. stensopp ET karljohan, karljohanssvamp,
