### ISSUE TITLE
AdWords

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9454]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[AdWords](http://www.yso.fi/onto/yso/p21140)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

vaihdetaan päätermiksi "Google Ads" ja "AdWords" ohjaustermiksi

**Perustelut ehdotukselle**

tuotteen nimi on vaihtunut kts. esim. https://en.wikipedia.org/wiki/Google_Ads

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto-asiakaspalaute

**Comment by YSO-kokous** [comment]
Päätös:  vaihdetaan päätermi
