### ISSUE TITLE
Mantšuria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9456]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Mantšuria](http://www.yso.fi/onto/yso/p110034)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Käytettävä termi muotoon "Koillis-Kiina".

**Perustelut ehdotukselle**

Kotuksen Eksonyymioppaan mukaan oikea muoto on nykyisin Koillis-Kiina: https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1577&ex=Koillis-Kiina 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Wikipedia/wikidata edelleen Mantšuria.

**Comment by nikopartanen** [comment]
Puhuttaessa juuri Kiinan kolmen koillisen provinssin muodostamasta alueesta Koillis-Kiina on varmastikin parempi kuin Mantšuria. YSO-paikat näyttäisi listaavan tällaisia Kiinan alueita, joten ehkä muutos on perusteltu. Historiallisesta Mantšuriasta puhuttaessa tuo on kuitenkin suppein Mantšurian monista määritelmistä, ja varmasti ainakin länsimaisessa historiaa käsittelevässä kirjallisuudessa tarkoitetaan usein jotain laajempaa tulkintaa. 

Mantšuria kai on Kiinan sisällä myös nykyisen Sisä-Mongolian alueella, sitten osittain Venäjällä, ja myös Amur-joen alku yltää Mongolian puolelle (Janhunen 1996, 12–13).

En sitten tiedä mikä on tällaisten historiallisten / hankalasti rajattavien alueiden suhde YSO-paikkoihin? Onko yksi vaihtoehto lisätä useampaan maahan "Mantšuria (historiallinen alue)", esimerkiksi noihin Kiinaan, Mongoliaan ja Venäjään? **Edit:** Tuo Mongolian sisällyttäminen vaikuttaa aika harvinaiselta ratkaisulta. 

Juha Janhunen 1996. _Manchuria – An ethnic history_. Suomalais-Ugrilaisen Seuran Toimituksia 222. Suomalais-Ugrilainen Seura.

**Comment by mirmaid** [comment]
Ei muutosta.
