### ISSUE TITLE
risteytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9457]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[risteytyminen](http://www.yso.fi/onto/yso/p26497)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko mahdollista poistaa?

**Perustelut ehdotukselle**

Sanastossa on myös risteytys ja risteymät (biologia). Ruotsiksi samoja termejä.. Risteytyminen on käytetty vain 44 kertaa Melindassa ja näissä tapauksessa riittäisi muut sanastossa olevat käsitteet?

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Onko muuten risteytys tarpeeksi selkeä? Ruotsiksi pitää varmaan tarkentaa selkeämmin (voisi nyt periaatteessa olla myös tulos, eikä vain toiminta)

Kielitoimiston sk. risteytys:
1. risteyttäminen, ristisiitos. Risteytyksen tuloksena saatu koirarotu.
2. paremmin: ristey(ty)mä.

**Comment by mirmaid** [comment]
^ Kyllä suomeksikin _risteytys_-sanaa voi käyttää myös "tuloksesta": "Meidän Musti on tällainen monirotuinen risteytys." En näe tässä ongelmaa, koska kyse on kuitenkin ihan samasta aihepiiristä (termi olisi kyllä monikossa jos tarkoitus olisi viitata niihin lopputuloksiin, mutta myös monikko viittaisi kuitenkin ensisijaisesti risteytystapahtumiin). 

Luonnossa tapahtuviin _risteytymisiin_ risteytys ei suomeksi viittaa (edes "lopputuloksiin"), koska se sisältää tarkoituksellisen toiminnan merkityksen. _Risteytyminen_ voisi kyllä olla korvattavissa _risteymät (biologia)_ -käsitteellä, vaikka ensimmäinen viittaa tapahtumaan ja jälkimmäinen tuloksiin. - Välillä tosin aineistoissa kyse on nimenomaan prosessista, ei niinkään niistä syntyvistä yksilöistä: _Nykyihminen ja neandertalinihminen risteytyivät ilmeisesti jo paljon aiemmin kuin on luultu, Coexistence of northern hares : consequences of crossbreeding and changing climate_.

**Comment by mirmaid** [comment]
Rajautuuko ruotsiksi nyt samoin vai pitäisikö ihmisen tekemään risteytykseen lisätä tarkenne (avel tms.)?

**Comment by mariaforsen** [comment]
Sanastossa on nyt siis:
risteytys = korsning (biologi)
risteytyminen = korsande
risteymät (biologia) = korsningar (organismer) 

Eli risteytys on aina ihmisen tekemä? Sellainen tarkenne voidaan varmaan luoda, mutta ei avel, koska se rajautuu eläimiin. Eli viittaa tähän käsitteeseen: https://fi.wikipedia.org/wiki/Risteytt%C3%A4minen ? Yksiselitteisempi termi olisi varmaan risteyttäminen, mutta voisi lisätä ainakin ohjausterminä?

Todellinen ongelma ruotsin kannalta on kuitenkin tuo keskimmäinen termi risteytyminen, koska vastaavaa passiivista termiä ei ole ruotsiksi. Nykyinen "korsande" ei toimi. Kun se on myös vain vähän käytetty, eikä kai tuo paljoa lisäarvoa asiasanana (esim. yllä mainitussa esimerkissä), niin olisiko poistettavissa? Sama ongelma taitaa olla englanniksi, eihän nykyinen vastine 
hybridisation myöskään toimi kuten pitäisi, ks. esim. https://en.wikipedia.org/wiki/Hybridisation

**Comment by YSO-kokous** [comment]
### Päätös
Poistetaan käsite risteytyminen.
Lisätään ohjaustermiksi: risteytyminen KÄYTÄ risteymät (biologia)
