### ISSUE TITLE
Brittiläinen Kolumbia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9458]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Brittiläinen Kolumbia](http://www.yso.fi/onto/yso/p116954)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Brittiläinen Columbia

**Perustelut ehdotukselle**

https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1360&ex=Brittil%C3%A4inen+Columbia

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Wikipedia/wikidata edelleen "Kolumbia".

**Comment by mirmaid** [comment]
Vaihdetaan.
