### ISSUE TITLE
Reininmaa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9460]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Reininmaa](http://www.yso.fi/onto/yso/p234828)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Rheinland-Pfalz

**Perustelut ehdotukselle**

https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1669&ex=Rheinland-Pfalz. 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jtuohini** [comment]
Reininmaa ei ole sama asia kuin Rheinland-Pfalzin osavaltio, joten ei voi muuttaa heittämällä! "Vaikkei Reininmaa ole ollut hallinnollinen yksikkö vuoden 1945 jälkeen, on se säilynyt Saksan osavaltioiden Rheinland-Pfalz ja Nordrhein-Westfalen nimissä. Suurin osa molemmista osavaltioista sekä myös Saarland kuuluivat aiemmin Reininmaahan." (https://fi.wikipedia.org/wiki/Reininmaa)

**Comment by ilona-x** [comment]
Ehdotuksen perustelussa mainitusta Kotuksen Eksonyymit -hausta löytyy erikseen myös Reininmaa https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1668&ex=Reininmaa

**Comment by mirmaid** [comment]
Ei muutosta.
