### ISSUE TITLE
pienhiukkaset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9461]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pienhiukkaset](http://www.yso.fi/onto/yso/p7435)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng. microparticles

**Perustelut ehdotukselle**

onko synonymi? https://en.wikipedia.org/wiki/Microparticle

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ei taida olla?

**Comment by tpalonen** [comment]
Ei muutosta
