### ISSUE TITLE
pienhiukkaset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9462]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pienhiukkaset](http://www.yso.fi/onto/yso/p7435)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: mikrohiukkaset

**Perustelut ehdotukselle**

relevantti termi

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9461

**Comment by mirmaid** [comment]
Taitaa tarkoittaa usein eri asiaa.

**Comment by YSO-kokous** [comment]
Tutkitaan lisätäänkö mikrohiukkaset eri käsitteeksi.
