### ISSUE TITLE
päällekkäisviljely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9463]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[päällekkäisviljely](http://www.yso.fi/onto/yso/p18935)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: vuorosekaviljely

**Perustelut ehdotukselle**

Vrt. eng. relay intercropping. Ks. esim. https://issuu.com/luomulehti/docs/luomulehti_3_2020_issuu/s/10640404 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
AFO: Päällekkäisviljely (kaksoiskylvö) on sekaviljelytapa, jossa syysvilja kylvetään jo keväällä kasvamaan yhdessä yksivuotisen kevätkylvöisen kasvin (päällyskasvin) kanssa

Vuorosekaviljely: Kahden tai useamman kasvilajin yhtäaikainen viljely niin, että lajit kasvavat osan kasvuajastaan yhdessä. Sadonkorjuu tapahtuu yleensä eriaikaisesti. Yleisimpiä muotoja nurmen kylvö suojaviljaan, aluskasvien käyttö.

Ehkä riittävän sama? Löysin ainakin kertaalleen _päällekkäisviljely_-termiä käytetyn kuminan viljelystä.

**Comment by mariaforsen** [comment]
Tarkempi YK olisi "sekaviljely", ks. esim. http://www.mtt.fi/asarja/pdf/asarja86.pdf
