### ISSUE TITLE
nykytaide

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9464]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[nykytaide](http://www.yso.fi/onto/yso/p9593)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: aikalaistaide

**Perustelut ehdotukselle**

Käytetään samassa merkityksessä, vrt. myös eng. contemporary art. https://fi.wikipedia.org/wiki/Nykytaide

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
KT-muoto mieluiten muodossa _aikalaistaide (nykytaide)_, koska "aikalaistaide"-sanalla on ainakin Tieteen termipankin mukaan kaksi merkitystä, nykytaide ja aikalaistaide kirjaimellisesti tulkittuna (https://tieteentermipankki.fi/wiki/Nimitys:aikalaistaide).

**Comment by YSO-kokous** [comment]
Ei hyväksytty.
