### ISSUE TITLE
kertomuksen teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9465]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kertomuksen teoria](http://www.yso.fi/onto/yso/p25857)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan tai poistetaan nykyinen määritelmä?

**Perustelut ehdotukselle**

On laajempi kuin pelkästään Ricoeurin teoria. Vrt. eng. narrative theory. Ks. myös esim. https://opinto-opas.jyu.fi/2020/fi/opintojakso/kira260/ ja https://weboodi.uef.fi/weboodi/opintjakstied.jsp?MD5avain=&Kieli=1&OpinKohd=58776913&OnkoIlmKelp=0&ooo_SortJarj=2&vl_tila=4&takaisin=vl_kehys.jsp&Opas=4330&Org=20784032&haettuOpas=4330&haeOpintJaks=haeopintojaksot ja https://teemary.org/?tag=yhteishaku  

**Ehdottajan organisaatio**

**Comment by AuHo22** [comment]
Voi viitata hyvinkin moneen asiaan, myös esim. https://www.fsd.tuni.fi/fi/palvelut/menetelmaopetus/kvali/teoreettis-metodologiset-viitekehykset/kertomuksen-tutkimus/

**Comment by YSO-kokous** [comment]
Päätös:  Poistetaan määritelmä
