### ISSUE TITLE
ositus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9468]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ositus](http://www.yso.fi/onto/yso/p6015)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään määritelmä ja/tai tarkenne

**Perustelut ehdotukselle**

Voidaan sekoittaa muihinkin merkityksiin kuin pelkästään avioliitonjälkeiseen ositukseen, ks. Melinda (esim. Käsikirja yksityisteiden tienpidon osittelusta ; Recycling potential of municipal solid waste in Finland / Olli Sahimaa). Vrt. myös eng. ja sv. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Välttämätön toimenpide käännösten kannalta.

**Comment by mirmaid** [comment]
Ositus (avio-oikeus)?

**Comment by mariaforsen** [comment]
Wikipediassa näköjään virheellinen linkitys: https://sv.wikipedia.org/wiki/Avvittring  ja https://fi.wikipedia.org/wiki/Pes%C3%A4nositus 

Ruotsiksi tähän liittyy myös termi bodelning (fi. pesänjako YSOssa). Nationalencyklopedin: "avvittring, äldre benämning på bodelning i samband med arvskifte" Voidaan ehkä ratkaista huomautuksella ja ohjaustermillä "bodelning (äktenskapsrätt)" KÄ avvittring (äktenskapsrätt) ruotsiksi?

Ks. https://fho.sls.fi/uppslagsord/16123/avvittring/ (fi. "pesänositus, pesäselvitys, omaisuuden ositus")

**Comment by mirmaid** [comment]
^ Vaatisiko _bodelning_ tarkenteen sitten ruotsiksi myös tuossa pesänjako-merkityksessä?

**Comment by YSO-kokous** [comment]
Lisätään tarkenne  ositus (avio-oikeus)    ruotsiksi   avvitring (äktenskapsrätt)

Tutktaan vielä pesänjako
-- pesänjako liittyen perintöihin ja pesänselvitys liittyen konkursseihin

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: 
pesänselvitys: oik. kuolinpesän varojen ja velkojen selville ottaminen ja velkojen maksaminen ennen pesänjakoa. 
pesänjako: oik. omaisuuden jakaminen pesän osakkaiden kesken. 

https://perukirjanetissa.fi/pesanjaon-ja-pesanselvityksen-ero/

**Comment by mirmaid** [comment]
_Pesänselvitys_ voi koskea myös konkurssipesää, ja kuolinpesäkin voi joskus muuttua konkurssipesäksi. Kuolinpesän ja konkurssipesän selvitys ovat toki normaalisti vähän erilaisia toimenpiteitä, mutta voisiko kuitenkin olla sama termi?

**Comment by mariaforsen** [comment]
Sv. bodelning (fi. pesänjako) =upp­delning av gemensam egendom på en­skilda parter som formell juridisk handling; vid döds­fall el. äktenskaps­skillnad
boutredning (fi. pesänselvitys) =åt­gärder som vid­tas med en av­liden persons till­gångar och skulder innan de av­vecklas genom arv­skifte

**Comment by mirmaid** [comment]
^ Noin, mutta _pesänselvitys_ voidaan siis tehdä paitsi kuolinpesälle, myös konkurssipesälle.

**Comment by mariaforsen** [comment]
Missä lukee enemmän sellaisesta pesänselvityksestä joka ei liity kuolinpesään? En tiedä mitä se voisi olla ruotsiksi. Jos kyseessä todella on jokin muu kuin esim. tässä mainittu asia: https://www.finlex.fi/sv/laki/ajantasa/1991/19910758 
Myös konkurssilaissa mainittu vain kuolinpesän yhteydessä https://www.finlex.fi/fi/laki/ajantasa/2004/20040120
https://termipankki.fi/tepa/fi/haku/pes%C3%A4nselvitys
https://www.kielitoimistonsanakirja.fi/#/pes%C3%A4nselvitys
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_1532596b8017542a7096bc1ab94729ac&list_id=1&keyword=pes%C3%A4nselvitys&word=pes%C3%A4nselvitys

**Comment by mirmaid** [comment]
Esim. täällä: https://www.minilex.fi/a/konkurssipes%C3%A4n-julkisselvitys: _Konkurssipesän julkisselvityksellä tarkoitetaan viranomaisten toimittamaa, tarkemmin sanottuna konkurssiasiamiehen toimittamaa konkurssipesän selvitystä valtion varoilla. Normaalin konkurssimenettelyn mukainen pesänselvitys toteutetaan pesänhoitajan ja velkojien johdolla yksityisesti._

Usein myös muodossa _konkurssipesän selvitys_ (https://www.minilex.fi/a/pes%C3%A4nhoitajan-selvitys, https://www.finlex.fi/fi/laki/ajantasa/2004/20040120#L4), mutta Melindassa _pesänselvitys_-termiä on käytetty näissä, ja jos ei voi olla sama termi, niin sitten vaatinee suomeksi tarkenteen.

**Comment by ilona-x** [comment]
Konkurssilaissa esim. näin:

9 luku
**Konkurssipesän selvitys** ja velallisen kirjanpito

9 kap
**Utredning av konkursboet** samt gäldenärens bokföring

https://www.finlex.fi/fi/laki/ajantasa/2004/20040120

**Comment by ilona-x** [comment]
Ja MOTin suomi-ruotsi -sanakirjasta löytyi vielä tällainen:

konkursbouppteckning
talous
[konkurssipesän selvitys](https://www.sanakirja.fi/custom/en-sv-de-fi-la-fr-ru-es-it-pt-nl-da-zh-is-se/konkurssipes%C3%A4n%20selvitys)

**Comment by mariaforsen** [comment]
Eli voisiko se konkurssipesän selvitys ottaa erillisenä terminä? Sillä tavalla saadaan sopivia vastineita myös ruotsiksi. 

Konkursbouppteckning ei tosin välttämättä täsmää täysin, voi olla myös konkurssipesän pesäluettelo? (Vid en konkurs utser tingsrätten en konkursförvaltare vars uppgift bland annat är att upprätta en konkursbouppteckning där bolagets tillgångar, enligt konkurslagen, skall upptas till noggrant uppskattade värden.") Ks. myös https://termipankki.fi/tepa/fi/haku/bouppteckning Tarkempi sv. voisi mahdollisesti olla "utredning av konkursbo".

**Comment by mirmaid** [comment]
_Konkurssipesän selvitys_ olisi varmaan ok. 

Nyt alan kyllä näiden viitteiden kanssa ihmetellä, miten _ositus (avio-oikeus)_ ja _kuolinpesän selvitys/jako_ suhteutuvat silloin, kun on kyse lesken tilanteesta...jäämistöositus-termiä näkyy myös 😓. Ehkäpä niihin sitten tulisi lisäksi _ositus (avio-oikeus)_. https://www.minilex.fi/a/j%C3%A4%C3%A4mist%C3%B6n-ositus

**Comment by mirmaid** [comment]
Olisiko _pesänjako_ sellaisenaan ok, mutta _pesänselvitys_ vaatisi vielä tarkenteen (kuolinpesät)?

**Comment by mirmaid** [comment]
Eli:
pesänselvitys: lisätään tarkenne (kuolinpesät) ja otetaan erikseen _konkurssipesän selvitys_
pesänjako: ei muutoksia

**Comment by mariaforsen** [comment]
Onko siis pesänjako suomeksi ok käyttää myös avioeron jälkeen? Muuten pitää lisätä tarkenne ruotsiksi tai ehkä vaihtaa päätermiä (bodelning/boskifte)

**Comment by mirmaid** [comment]
^ Ei mun käsittääkseni, vaan silloin on se ositus.

**Comment by mariaforsen** [comment]
Eli mihin kaikkeen käy pesänjako suomeksi? Riittääkö tarkenteena kuolinpesät tms. vai voidaanko pesänjakoa käyttää myös muissa tapauksissa? Ruotsiksi bodelning käy yhtä hyvin av(i)oeron jälkeen.  https://www.domstol.se/amnen/familj/skilsmassa-och-bodelning/bodelning/

**Comment by ilona-x** [comment]
Suomeksi ei käytetä pesänjakoa ainakaan tuosta avioeron ja ositukseen jälkeen tapahtuvasta omaisuuden jaosta. YLE:llä näyttää löytyvän aiheena **Omaisuudenjako (Avioero)** https://yle.fi/aihe/t/18-44381 Mielestäni pesänjako liittyy vain kuolinpesiin.

**Comment by FinMeSHienPaimentaja** [comment]
Kun avioliitto päättyy, on tehtävä ositus. Avioliitto voi päättyä siihen, että toinen puolisoista kuolee tai tulee avioero. Ennen jakoa on tehtävä ositus. Jos avioliitto on päättynyt toisen kuolemaan, kyseessä on  jäämistöositus. Vasta osituksen tekemisen jälkeen voidaan tehdä jako. **Jako / omaisuuden jakaminen on eri käsite kuin ositus**, vaikka niistä monesti puhutaankin "kimpassa" ja ositus ja jako käytännössä monesti tehdään samaan syssyyn. Pesänjako liittyy siihen, kun toinen osapuoli on kuolleen puolison kuolinpesä (tai voihan molemmatkin olla kuolleet, jolloin on kaksi kuolinpesää).

Ennen ositukseen ja jakoon menemistä on tehtävä selvitys / kuolinpesän / kuolinpesien selvitykset.  (Avio-oikeusasioihin liittymättä, ainakin konkurssipesiä selvitetään / kuuluu käsittääkseni selvittää, eli kyseessä on silloinkin selvitys, mutta ei kuolinpesän selvitys, vaan konkurssipesän selvitys).

terveisin nimim. "avio-oikeus" ;D

PS. Korjatkaa, jos olen oppinut huonosti em. läksyt elämänkoulussa. ;D

**Comment by FinMeSHienPaimentaja** [comment]
Tuli vaan mieleen, että olisiko käsite "pesä" kyseessä nimenomaan silloin, kun kyseessä oleva omaisuus/varallisuusmassa on peräisin siitä, että omistajansa on menehtynyt, olipa omistansa sitten ollut ihminen tai firma...(?)

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan yllä esitetyn ehdotuksen mukaisesti. Ruotsiksi tarkistetaan valittuja termejä.

**Comment by mariaforsen** [comment]
Pesänjako on näköjään kuitenkin käytetty Melindassa myös muusta kuin kuolinpesistä, esim.
Yrityksen konkurssi / velallisen oikeudet ja velvollisuudet / Annabella Holm.
Näin vältät osituksen sudenkuopat.
Omaisuuden erottelu avoerossa : nykytila ja lakiesitys / Maiju Ojala.
Avioero ja asumiskysymys / Riikka Salo.
KKO 2008:22 : Pesänjakajan määrääminen toimitetuksi väitetyn osituksen jälkeen.
Avioero-ositus : hahmotelma uudeksi pesänjakojärjestelmäksi / Achilles Westling.

Sen lisäksi melko paljon ruotsinkielistä aineistoa, mutta niihin tietueisiin pesänjako on varmaan päätynyt ruotsin kautta. Onko siis varmasti niin ettei pesänjakoa käytetä jatkossa muusta kuin kuolinpesistä? Vai olisiko ainakin huomautus tarpeen, varsinkin kuvailijoille jotka eivät tunne lakia?

Jos nyt lisätään kuolinpesät tarkenteena ruotsiksi, se on tällaisissa tietueissa aivan väärä.

**Comment by FinMeSHienPaimentaja** [comment]
Näköjään pikaisesti nettiä selailemalla pesänjakoa / pesänjakajaa on kyllä käytetty ihan avioeronkin yhteydessä, ilman kuolleita osallisia/puolisoita.

Myös täällä pesänjakaja avioeron yhteydessä: https://oikeus.fi/tuomioistuimet/fi/index/asiat/perheasiat/avioero.html

**Comment by FinMeSHienPaimentaja** [comment]
Perhe- ja jäämistöoikeuden perusteet; Kangas, Urpo:

_"Osituksen tai erottelun yhteydessä saattaa tulla toimitettavaksi myös yhteisen omaisuuden jako."_

https://verkkokirjahylly.almatalent.fi/teos/FADBIXDTEB#/kohta:VIII((20)Avioliitto(:10((20)OMAISUUDEN((20)OSITUS/piste:t1Us

Netissä esim. joillain asianajotoimistojen sivuilla ositusta ja jakoa näyttää käytettävän siten, että saa vaikutelman, että kyseessä  olisi yksi käsite (mikä ei olekaan mikään ihme, koska avioerotilanne eroaa tilanteesta, jossa kuolema erottaa -> ositus -> jako (kenties montakin kuolleen puolison kuolinpesän osakasta, joiden kesken kuolleen puolison kuolinpesä jaetaan)).

Joka tapauksessa osituksen ideana / pointtina on, että määritetään avio-osat (avio-osien suuruus ja mitä nimenomaisia "haarukoita ja lusikoita lue: rahasto-osuuksia ja osakkeita" yms. maallista mammonaa osituksen osapuolille kummallekin tulee avio-oikeuden alaisesta omaisuudesta (konkreettisessa) jaossa).

**Comment by ilona-x** [comment]
Törmäsin tällaiseen ihan pätevältä vaikuttavaan Wikipedia-artikkeliin, jonka mukaan 

> "Pesänositus eli pesänjako oli ennen vuotta 1930 solmituissa [avioliitoissa](https://fi.wikipedia.org/wiki/Avioliitto) käytössä ollut menettely, jolla aviopuolisoiden yhteinen omaisuus jaettiin [avioeron](https://fi.wikipedia.org/wiki/Avioero) tai toisen puolison kuoleman johdosta. Vuoden 1930 alussa voimaan tullut [avioliittolaki](https://fi.wikipedia.org/wiki/Avioliittolaki) (234/1929) toi sen aikana solmittuihin avioliittoihin pesän[osituksen](https://fi.wikipedia.org/wiki/Ositus_(oikeustiede)) tilalle osituksen."

Lähde: https://fi.wikipedia.org/wiki/Pes%C3%A4nositus

---
Varmaan tuota vanhaa perua on tuo vähän hämmentävä pesänjakaja, joka voidaan riitaisassa erossa ottaa hoitamaan ositus. Mutta mielestäni tuo pesänjako avioeron yhteydessä on suomeksi vanhentunut termi ja voisi tehdä ohjaukset:

pesänjako (avio-oikeus) KÄYTÄ ositus (avio-oikeus)
pesänositus (avio-oikeus) KÄYTÄ ositus (avio-oikeus)

**Comment by ilona-x** [comment]
Pesänjako-termi konkurssin yhteydessä näyttää löytyvän vain kahdesta Melinda-viitteessä, joista toinen käsitelee ylivelkaista kuolinpesää eikä mitään varsinaista konkurssipesää. Ja tuohon yrityksen konkurssia käsittelevään kävisi varmasti myös nyt sanastoon otettava termi **konkurssipesän selvitys**

Tässä vielä Melinda-viitteet haulla pesänjako AND konkurssi?:

Yrityksen konkurssi / velallisen oikeudet ja velvollisuudet  https://melinda.kansalliskirjasto.fi/byid/009885111
Ylivelkaisuustilanteet ja vastuut kuolinpesässä https://melinda.kansalliskirjasto.fi/byid/006307000

**Comment by mariaforsen** [comment]
konkurssipesän selvitys = sv. konkursbouppteckning, utredning av konkursbo /finlex 
https://www.sanakirja.fi/custom/fi-en-sv/konkurssipes%C3%A4n
https://www.rikstermbanken.se/search?q=konkursbouppteckning&s=termer
https://www.finlex.fi/sv/laki/ajantasa/2004/20040120
https://bolagslexikon.se/konkursbouppteckning/
https://www.betydelse-definition.com/Konkursbouppteckning
https://www.isof.se/download/18.3f96527c178d05b35bf2ea66/1619263625244/konkurs_utmatning.pdf
https://www.sanakirja.fi/custom/fi-en-sv/konkursbouppteckning

konkursutredning (fi. konkurssiselvitys)?
