### ISSUE TITLE
päämäärät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9469]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[päämäärät](http://www.yso.fi/onto/yso/p5397)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voidaanko määritellä suhteessa termiin "tavoitteet" (tai mahdollisesti yhdistää)?

**Perustelut ehdotukselle**

Ruotsin termi pitää muuttaa, "mål" on monimerkityksinen termi, mutta ainakin ruotsiksi nämä termit ovat hyvin lähellä toisiaan. 

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Yhdistäminen kuulostaa hyvältä idealta, ainakin jos Kielitoimiston sanakirjaan (https://www.kielitoimistonsanakirja.fi/päämäärä) on luottaminen.

**Comment by ilona-x** [comment]
Melinda:
päämäärät x 287
tavoitteet x  4487
päämäärät & tavoitteet x 160

**Comment by fantsby-m** [comment]
Kävin Melindassa läpi satakunta tietuetta joissa oli YSO-termi _päämäärät_ (mutta ei termiä _tavoitteet_) yksikään niistä ei ollut sellainen etteikö tilalla olisi voinut käyttää termiä _tavoitteet_.

**Comment by YSO-kokous** [comment]
Päätös:  päämäärtä KÄYTÄ tavoiteet
