### ISSUE TITLE
tietoaineistot [SLM]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9470]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tietoaineistot [SLM] 

#### Ehdotettu termi englanniksi   

Informational works 

#### Vastaava käsite muussa sanastossa   

LCGFT : <http://id.loc.gov/authorities/genreForms/gf2014026113> 

#### Perustelut ehdotukselle   

Yksi SLM:n vielä puuttuvista ylätasoista. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
https://id.kb.se/term/saogf/Informativa%20verk

**Comment by ilona-x** [comment]
Informational works http://id.loc.gov/authorities/genreForms/gf2014026113

**Comment by mirmaid** [comment]
Seuraava kokous.

Etsitään aikaisempi selvitys aiheesta ja kopioidaan tähän (Mirja). 
Listataan tähän kaikki, mikä tulisi tähän ryhmään.

**Comment by mirmaid** [comment]
Toivottiin ensisijaisesti käsitettä, jota voi käyttää myös kuvailussa (ei "termihirviö"). Tyypillisesti käytettäisiin kuitenkin tarkempia termejä.

**Comment by mariaforsen** [comment]
Täytyy huomioida että tällä termillä voi olla kaksi merkitystä: "tietoa sisältävä aineisto; tiettyä tarkoitusta varten kerättyjen dokumenttien muodostama kokonaisuus" /Kielitoimiston sk. Ja käännös riippuu merkityksestä (ihan eri termi ruotsiksi)

Ks. myös https://termipankki.fi/tepa/fi/haku/tietoaineisto Eli jos halutaan suomeksi termi joka vastaa LCSH:n informational works, niin onko tietoaineistot todella paras vaihtoehto?

**Comment by mirmaid** [comment]
Hyväksytään muodossa _ei-fiktiiviset aineistot_.

Määritelmä: Works whose main purpose is to record and convey factual information. / Teokset, joiden päätarkoitus on tallentaa ja välittää tietoa.

**Comment by jtuohini** [comment]
Muita **ei-fiktiiviset aineistot** -termin alle siirrettäviä:

- almanakat
- direktiivit
- esitelmät
- hakemistot
- historiikit
- mielipidekirjallisuus
- mielipidekirjoitukset
- määräykset
- näyttelyjulkaisut
- oppaat (teokset)
- oppikirjat
- paikallishistoriat
- sanastot
- seurakuntahistoriat
- suositukset
- synodaaliväitöskirjat
- testit
- tiedotteet

Nämä hyväksytty /SLM.

**Comment by mariaforsen** [comment]
Sv. icke-fiktiva material HT icke-fiktivt material, informativa verk

**Comment by jtuohini** [comment]
Muita **ei-fiktiiviset aineistot** -termin alle siirrettäviä:
- asiasanastot
- barometrit
- kasviot
- luettelot
- matkakertomukset
- muistelmat
- pääkirjoitukset
- seurakuntahistoriat
- sukukirjat
- suunnitelmat
- unikirjat

**Comment by mirmaid** [comment]
^ Hyväksytty.

**Comment by jtuohini** [comment]
SLM:ssä lisää **ei-fiktiiviset aineistot** -termin alle siirrettäviä:

- arvostelut
- haastattelut
- hakuteokset
- hautakirjoitukset
- henkilökuvat (henkilöhistoria)
- keittokirjat
- kielioppikirjat
- kiertokirjeet
- kurssijulkaisut [?, termi vaatinee joka tapauksessa selityksen sanastoon]
- luennot
- nekrologit
- ohjeet
- ohjekirjat
- pamfletit
- reportaasit
- standardit
- toimintaohjelmat

Lisäksi **kausijulkaisut**-termin alta pitää valikoida sellaiset, jotka eivät ole kaunokirjallisia tms.

**Comment by jtuohini** [comment]
Ja lisätään **tietosarjakuvat**-termin toiseksi LT-suhteeksi **ei-fiktiiviset aineistot**.

**Comment by mirmaid** [comment]
Hyväksytään ehdotetut muutokset.

**Comment by mirmaid** [comment]
"Lisäksi kausijulkaisut-termin alta pitää valikoida sellaiset, jotka eivät ole kaunokirjallisia tms."

Miten tämän osalta tehdään?

**Comment by jtuohini** [comment]
Pikavilkaisulla kausijulkaisuista ainakin seuraavat menisivät luullakseni ongelmitta:
- aluelehdet (ST maakuntalehdet, paikallislehdet)
- puoluelehdet
- sanomalehdet (ST iltapäivälehdet)
- sensaatiolehdet
- työväenlehdet

Aikakauslehdistä taas valittavaa riittää, äkkivilkaisulla ainakin:
- asumislehdet
- autolehdet
- elokuvalehdet
- eläinlehdet
- erälehdet
- häälehdet
- käsityölehdet
- liikuntalehdet
- luontolehdet
- maanpuolustuslehdet
- maatalouslehdet
- markkinointilehdet
- matkailulehdet
- metsälehdet
- mielipidelehdet
- miestenlehdet
- moottoripyörälehdet
- muotilehdet
- naistenlehdet
- pelilehdet
- puutarhalehdet
- rakennuslehdet
- rikoslehdet
- ruokalahdet
- seksilehdet [?]
- sisustuslehdet
- talouslehdet
- tapahtumalehdet
- teatterilehdet
- tekniikkalehdet
- terveyslehdet
- tiedelehdet
- tiedotuslehdet
- tietotekniikkalehdet
- urheilulehdet
- valokuvauslehdet
- vauvalehdet
- venelehdet
- yleisaikakauslehdet

**Comment by mirmaid** [comment]
Miestenlehdet (seksilehdet) KÄ seksilehdet. Hierarkiatäydennykset ok.

**Comment by mirmaid** [comment]
Eikö musiikkilehdet ole aina ei-fiktiivisiä (entä taide-, tanssil.)? Naistenlehdissä voisi ehkä olla fiktiivistäkin matskua (joku jatkokertomus), vaikuttaako asiaan? Seksilehdissä kysymysmerkki, voisi ehkä jättää pois ei-fiktiivisistä?

**Comment by mirmaid** [comment]
^ Nämä ok.
