### ISSUE TITLE
kertomakirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9471]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kertomakirjallisuus](http://www.yso.fi/onto/ysa/Y96093) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSO:n puolella ei muutosta! SLM:n puolella lisätään LT-suhde "kaunokirjallisuus" ja muutetaan nykyiset RT-suhteet ST-suhteiksi. 

#### Perustelut ehdotukselle   

Kaikki kertomakirjallisuus on kaunokirjallisuutta, joten hierarkin pitäisi kuvastaa tätä. Kertomakirjallisuuden lajit pitäisi myös olla ST-suhteessa, ei RT-suhteessa. Ks. esim. https://fi.wikipedia.org/wiki/Kaunokirjallisuus 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
"muutetaan nykyiset (kertomakirjallisuuden) RT-suhteet ST-suhteiksi" -> **kertomarunot** LT runot  ; **pakinat** voivat yhtä hyvin sijoittua tietokirjallisuuteen -> RT-suhde kuvaavampi? ; **tarinat** voivat olla yhtä hyvin suullista perinnettä, ts. kansanperinnettä eivätkä välttämättä kaunokirjallisuutta -> RT-suhde edelleen?

**Comment by mariaforsen** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9813
https://github.com/Finto-ehdotus/YSE/issues/9312

**Comment by mirmaid** [comment]
LT ok, ST eepokset, novellit, romaanit.
