### ISSUE TITLE
luettelot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9473]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[luettelot](http://www.yso.fi/onto/ysa/Y96982) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään LT-suhde "hakuteokset" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Onko kuitenkin kyse RT-suhteesta, vrt. YSO. Fennican sisällönkuvailuohjeeseen aiemmin selvitettyä:
**Hakuteos** on tavallisesti hakusanoittain järjestetty, tiiviitä artikkeleita tietyltä aihealueelta tai -alueilta sisältävä teos. Villit vihreät kaupungit: Suomen kaupunkikasvio. Jalkapallon ennätyskirja.
**Luettelo** on listaus määräyhteyteen kuuluvista henkilöistä, esineistä tms. Näitä ovat esimerkiksi hintaoppaat, keräilykohteiden luettelot ja luettelot taidekokoelmista. Luettelo entisessä Viipurin läänin maakunta-arkistossa säilytettävistä suomalaisaineistoista. Silver coins of the Indian sub-continent from 449 until 1947.

Myös alephin kiinteiden kenttien sisältövaihtoehdoissa nämä katsotaan erillisiksi: c = luettelot, kuvastot ja e = tietosanakirjat, hakuteokset

**Comment by mariaforsen** [comment]
Ruotsin osalta ST ei sovi, RT ok.

**Comment by mirmaid** [comment]
Lisätään RT-suhde.
