### ISSUE TITLE
taideteokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9474]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taideteokset](http://www.yso.fi/onto/ysa/Y104506) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Otetaan myös SLM-sanastoon, ST-suhteenan sanastossa jo oleva "piirustukset (taide)" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja SLM:ssä toiseksi ST-suhteiseksi [**taiteilijakirjat**](http://urn.fi/URN:NBN:fi:au:slm:s122).

**Comment by AuHo22** [comment]
Olisiko tässä kyseessä kuvateos taideteoksista vai kuvattaisiinko tällä yksittäistä artefaktia, ja millainen käyttötarve silloin termillä olisi? vrt. exlibrikset #7016 -> 
"Termillä kuvaillaan ainoastaan konkreettisia exlibriksiä. Exlibriksiä esittelevistä kuvateoksista käytetään SLM-termiä kuvateokset, kuvastot tms. ja YSO-asiasanaa exlibrikset."

**Comment by jtuohini** [comment]
Nimenomaan taideteokset itsessään, ei niitä esittävät kuvateokset. Eli tulisi samankaltainen huomautus.

**Comment by mirmaid** [comment]
Visuaaliset teokset? (LCGFT Visual works) Palataan hierarkian käsittelyn yhteydessä.

**Comment by jtuohini** [comment]
ST-suhteiseksi myös [**videotaideteokset**](http://urn.fi/URN:NBN:fi:au:slm:s1356).

**Comment by jtuohini** [comment]
"Visuaalinen teos" = "kuvataideteos"?

**Comment by mirmaid** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9474#issuecomment-1022979980 tämä lienee jossain kokouksessa kirjattu kommentti, en muista enää mitä aiheesta on mahdollisesti keskusteltu. Voidaanko ratkaista, otetaanko ehdotettu genretermi taideteokset, vai jätetäänkö se tässä vaiheessa (aineistoesimerkkien puutteessa) termiehdotukseksi?

**Comment by mariaforsen** [comment]
Eli oliko tässä oikeastaan tarkoitus ottaa jonkinlaista yläkäsitettä erityyppisille "taideteoksille", vastaavalla tavalla kuin LC:ssä on tehty: https://id.loc.gov/authorities/genreForms/gf2017027266.html Ei välttämättä mene ihan yksi yhteen SLM-termivalikoiman ja -hierarkian kanssa..

**Comment by mirmaid** [comment]
Kuvataideteokset /SLM

**Comment by mariaforsen** [comment]
Sv. bildkonstverk HT konstverk (bildkonst)
https://kuvasto.fi/sv/bildrattigheternas-abc/
https://svenska.se/tre/?sok=bildkonstverk&pz=8
