### ISSUE TITLE
ohjelmistosuunnittelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9475]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ohjelmistosuunnittelu](http://www.yso.fi/onto/ysa/Y191904) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään sulkutarkenne sekä otetaan sanastoon uusi termi:
ohjelmistosuunnittelu (tietojenkäsittely)
ohjelmistosuunnittelu (media) 

#### Perustelut ehdotukselle   

Termi nyt vain ryhmässä 43 (atk jne.). On paljon käytetty termi myös media-alalla. 

#### Ehdottajan organisaatio   

Yle Arkisto

**Comment by ilona-x** [comment]
Jos ohjelmistosuunnitelu -termiä lähdetään jakamaan, niin samassa yhteydessä voisi pohtia, olisiko ohjelmistosuunnittelu & ohjelmistokehitys mahdollisesti yhdistettävissä? Vrt. YSOssa ohjelmistosuunnittelijat KÄYTÄ ohjelmistokehittäjät.

**Comment by fantsby-m** [comment]
Mitä tässä mahdetaan tarkoittaa media-alalla? Melindassa asiasanaa _ohjelmistosuunnittelu_ on käytetty noin 200 kertaa, liittyen tietojenkäsittelyyn - lukuun ottamatta kahta, jotka liittyivät taide-/kulttuurialaan.

**Comment by mariaforsen** [comment]
Ohjelmistosuunnittelu on ruotsiksi programvarudesign YSOssa, joten sitä ei voi ainakaan käyttää mediamerkitykseen.

**Comment by ilona-x** [comment]
YLEllä käytetty ohjelmistosuunnittelua esim. tämän kuvailussa:
https://yle.fi/aihe/artikkeli/2015/06/26/yle-vastaa-ohjelmisto-syntyy-yleison-toiveista
"Ylen koko tarjonnan ohjelmistosuunnittelu on palapeliä, johon vaikuttaa moni asia ja ammattilainen."

https://yle.fi/aihe/t/18-92807

**Comment by YSO-kokous** [comment]
Tutkitaan voidaanko yhdistää ohjelmistosuunnittelu KÄ ohjelmistokehitys

**Comment by mirmaid** [comment]
Kysytty KK:n koodareilta: _Ei se kyllä minusta sama asia ole. Ohjelmistosuunnittelu on, no, suunnittelua - vähän niin kuin arkkitehdin pitää ensin tehdä piirustukset ennen kuin taloa voidaan alkaa rakentaa. Tosin ohjelmistokehityksessä, varsinkin nykyisenä ketteränä aikana, nämä kyllä limittyvät vahvasti toisiinsa. Voisi ajatella, että ohjelmistosuunnittelu on osa ohjelmistokehitystä, mutta ohjelmistokehitykseen kuuluu paljon muutakin, erityisesti sitä käytännön toteutusta_. (tässä 4 peukkua)

_Tämä jako ohjelmiston suunnitteluun ja ohjelmointiin tulee osin sellaisista taloista, missä on eriytetty nämä kaksi. On sellaisia paikkoja missä ohjelmoijalle tulee niin yksityiskohtainen kuvaus ohjelman rakenteesta, että on luokka luokalta ja metodi metodilta selitetty toiminta melkein yhtä monella rivillä kuin lopullinen ohjelmakoodikin tulee olemaan. Tällöin se ohjelmistosuunnittelu ja koodaus ovat tosiaan eri tehtävät.Mutta erityisesti ketterissä ja pienissä organisaatioissa ohjelmistosuunnittelijat käytännössä tekevät myös kaiken koodauksen.
Oma sektorinsa on sitten ohjelmistoarkkitehdin työ, ohjelmistoarkkitehdin ja -suunnittelijan ero käsittääkseni on siinä, että kun katsotaan koko ohjelmiston tasolla rakenteita, jakoa osiin, protokollia, kytkentöjä rinnakkaisiin järjestelmiin jne, se on arkkitehdin hommaa.
Ohjelmistosuunnittelu taas on matalamman tason juttuja, siinä kohtaa jako moduuleihin ja protokollat on jo pääosin kiinnitetty._

**Comment by mariaforsen** [comment]
Mikä olisi ohjelmistosuunniittelu mediamerkityksessä ruotsiksi? Programplanering ei oikein toimi, koska se voi viitata myös tietyn ohjelman suunnitteluun.

**Comment by mirmaid** [comment]
Olisiko jotain tyyliin programutbud + planering = ohjelmatarjonnan suunnittelu? Jos tämä päätetään ottaa.

**Comment by mariaforsen** [comment]
Programutbud on myös monimerkityksinen sana ks. esim. https://www.mustionlinna.fi/sv/att-gora/programutbud https://www.kasnas.com/sv/konferens-och-fest/programutbud https://www.turku.fi/sv/nyhet/2021-05-28_ett-maritimt-sommartorg-erbjuder-sommarfirare-ett-brett-programutbud
Planering av programutbud i tv, radio...? Planering av programutbud (medier)? 

**Olisiko mitenkään mahdollista että käytettäisiin tästä jo olemassa olevat termit ohjelmatarjonta + suunnittelu?**

**Comment by mirmaid** [comment]
Tarvitaanko sanastoon jäävälle ohjelmistosuunnittelulle tarkenne (tietojenkäsittely/tietotekniikka)?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään tarkenne _ohjelmistosuunnittelu (tietotekniikka)_.
