### ISSUE TITLE
elämäkerrat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9476]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[elämäkerrat](http://www.yso.fi/onto/ysa/Y95034) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

YSO:ssa ei muutosta! SLM:ssä lisätään LT-suhteeksi "tietoaineistot" (https://github.com/Finto-ehdotus/YSE/issues/9470) 

#### Perustelut ehdotukselle   

Tämä ja pari aiempaa ehdotusta tehty SLM:n hierarkian parantamiseksi 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytään LT ei-fiktiiviset aineistot.
