### ISSUE TITLE
sukukirjat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9480]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sukukirjat](http://www.yso.fi/onto/ysa/Y197444) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään RT "matrikkelit" tms ja jokin sopiva LT-suhde. 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Ehdottaja on varmaankin tässä ajatellut ns. sukutauluja, joissa voidaan henkilötietoja esittää kaavamaisesti järjestyksessä. Sukukirja on kuitenkin laajempi kokonaisuus, ja sisältää useimmiten suorasanaista esitystä suvun historiasta kaikkinensa. Tällä hetkellä matrikkelilt LT hakemistot / luettelot RT jäsenluettelot. Ei mielestäni sovi tähän joukkoon.

**Comment by mirmaid** [comment]
Ei lisätä suhdetta.
