### ISSUE TITLE
Lanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9481]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Lanit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Lan party

**Tarkoitusta täsmentävä selite**

Tietokonepelaamiseen tarkoitettu tapahtuma käyttäen lähiverkkoyhteyttä.

**Perustelut ehdotukselle**

Lani -tapahtumat alkavat olla jo miljoona-luokan bisnestä, eli ei mikään pieni asia. Käsite on myös ollut vakiintunut Suomen kielessä jo 2000 luvulta alkaen, eli pitäisi olla jo ihan vakiintunut ja yleinen termi.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [43 Atk. Tietotekniikka. Tietojenkäsittely](http://www.yso.fi/onto/yso/p26553)

**Vaihtoehtoiset termit**

 Lähiverkkotapahtuma, Verkkopelitapahtuma, Local Area Network Party, Lani tapahtuma

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](https://fi.wikipedia.org/wiki/Lähiverkkotapahtuma)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

E-sport lanitapahtumien kuvailussa

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Lanit](http://finto.fi/yse/fi/page/Y509481)

**Comment by jtuohini** [comment]
Wikidata-siltaus: https://www.wikidata.org/wiki/Q185220

"Lähiverkkotapahtuma (arkikielessä myös lanit), joskus myös verkkopelitapahtuma, tarkoittaa tapahtumaa, jossa yhteen tilaan kokoontuu ihmisiä harrastamaan omien tietokoneidensa kanssa." (https://fi.wikipedia.org/wiki/L%C3%A4hiverkkotapahtuma)
 
Asiasanaston varmaan mieluiten kirjakielinen muoto **_lähiverkkotapahtumat_** ja puhekielinen _lanit_ siis vain KT-muodoksi.

**Comment by jarmosaarikko** [comment]
Jatkona edelliseen: 
KÄ "local area network events" 
KT "local area network parties", "LAN parties", "demoparties"
RT elektroninen urheilu

Jos sanastoon valitaankin käsite "verkkopelitapahtumat" niin käännös olisi: KÄ "online game events" KT "video game events",

Aivan eri käsite on sitten: "virtuaalipelitapahtumat / "virtual gaming events", jossa henkilöt eivät kokoonnu samaan paikaan, vaan ovat hajallaan verkossa ja pelaavat etänä.
https://tabletop.events/conventions/virtual-gaming-con

**Comment by ilona-x** [comment]
Lanit on lisätty Kielitoimiston sanakirjaan uusimmassa päivityksessä.  https://www.kotus.fi/sanakirjat/kielitoimiston_sanakirja/ajankohtaista_kielitoimiston_sanakirjassa/kielitoimiston_sanakirjaan_uusia_sanoja_ja_merkityksia_loppusyksylla.36872.news

**lanit**
slg. lähiverkossa toteutettava videopelitapahtuma; kasvokkainen kokoontuminen, jossa osallistujat pelaavat samaa videopeliä omilla laitteillaan. 
Lähde: https://www.kielitoimistonsanakirja.fi/#/lanit?searchMode=all

**Comment by jtuohini** [comment]
Mutta huomioksi, että on merkitty sanakirjaan slangi-ilmaisuksi, ja luullakseni sellaisia ei sanastoon oteta, jos kirjakielinen/yleiskielinen vaihtoehto on tarjolla.

**Comment by AuHo22** [comment]
Kuntien nuorisotoimen samoin kuin seurakuntien sivuilla voidaan puhua laneista - itseäni kyllä miellyttää lyhyt muoto, ja sen voisi epäillä yleiskielistyvänkin, vrt. blogit jne. ?

**Comment by fantsby-m** [comment]
_Lanit_-sana on tuttu jo yli kymmenen vuoden takaa, _lähiverkkotapahtuma_-termi ei ole ennestään tuttu. Pidempää ei ole esim. Kielitoimiston sanakirjassa lainkaan.

Ylellä tosin on termi _lähiverkkotapahtuma_ käytössä: https://yle.fi/uutiset/18-131576

**Comment by mirmaid** [comment]
Melindassa ei ole toistaiseksi käytetty mitään ehdotetuista muodoista. Googlella myös muotoa _LAN-tapahtumat_.

**Comment by satuniininen** [comment]
Käyttö laajentunut kattamaan myös muita kuin verkkopelitapahtumia, esim ompelulanit. Näihin ei aukikirjoitettu muoto oikein sovi.
https://www.ommel.fi/2019/01/11/ommellaan-yhdessa-ommel-laneissa/
https://yle.fi/uutiset/3-10246712

**Comment by mariaforsen** [comment]
Sv. LAN-party https://svenska.se/tre/?sok=lan-party&pz=1 Mutta ruotsiksi tämä rajautuu tietokonemerkitykseen, eli ei käy käsityöstä tms. Sellaista termiä ei taida ruotsiksi löytyä, vaan se on sitten tapaamiset, tapahtumat tms. + ompelu.

**Comment by fantsby-m** [comment]
Tuo laajennus ompeluun ym. kuulostaa vähän hassulta kun koko sana perustuu _local area network_-termiin.

**Comment by jtuohini** [comment]
Samaa tasoa kuin väärin opitut ilmaisut _à la_ "rahvas mies"!

**Comment by YSO-kokous** [comment]
Otetaan sanastoon lähiverkkotapahtumat KT lanit

**Comment by mariaforsen** [comment]
Sv. LAN-partyn HT LAN-evenemang
https://svenska.se/tre/?sok=lan-party&pz=1
