### ISSUE TITLE
itsensä johtaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9482]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[itsensä johtaminen](http://www.yso.fi/onto/yso/p27940)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

englanninkieliseksi termiksi self-leadership

**Perustelut ehdotukselle**

Ehdotan, että itsensä johtamisen englanninkieliseksi termiksi lisätään self-leadership, koska se tuo kansainvälisissä tutkimuksissa ja artikkeleissa suomenkielistä termiä "itsensä johtaminen" vastaavaa aineistoa. Nyt YSO tarjoaa englanniksi termiä self-management, joka tuottaa kansainvälisissä hauissa enemmänkin itsehoito-ohjeita.

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
Ehdottaja on jokseenkin oikeassa ja kannatan vaihtamista.  **itsensä johtaminen**  vaihtoehdot:
-  **self-leadership** Melindassa 31 kertaa, asiasanana 2 kertaa.
Eräs määritelmä: "_Self-leadership is the practice of intentionally influencing your thinking, feeling and actions towards your objective/s_" (Bryant and Kazan 2012)
- **self-management** Melindassa  268 kertaa, asiasanana 55 kertaa, 
- - Mutta osa näistä ei olekaan itsensä johtamista, vaan itsehallintaa (self-control), itseapua (self-help (psychology)), itsehoitoa (self-care) tai itseohjautuvuutta (self-direction)
- - Eräs määritelmä:  "_Self-management is our ability to manage our behaviors, thoughts, and emotions in a conscious and productive way_"

Self-leadership -termi rajautuu paremmin vastaamaan suomenkielistä käsitettä.
Katso myös:  [The Four Pillars of Self-Leadership](https://thriveglobal.com/stories/the-4-pillars-of-self-leadership-time-to-focus-on-you/):  Self-Discovery, Self-Acceptance, **Self-Management**, Self-Growth
