### ISSUE TITLE
tutkimusraportit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9483]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tutkimusraportit](http://www.yso.fi/onto/ysa/Y99719) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-suhde ehdotettuun termiin "tietoaineistot" 

#### Perustelut ehdotukselle   

SLM:n hierarkin parantaminen. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja ehdotettu LT-termiehdostus on siis https://github.com/Finto-ehdotus/YSE/issues/9470

**Comment by mirmaid** [comment]
Hyväksytään LT ei-fiktiiviset aineistot.
