### ISSUE TITLE
Omaopettaja

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9485]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Omaopettaja 

#### Vaihtoehtoiset termit ja ilmaisut   

Ryhmäohjaaja 

#### Vastaava käsite muussa sanastossa   

https://www.jyu.fi/edupsy/fi/laitokset/psykologia/opiskelu/ohjeita-opiskeluun/omaopettaja-toiminta 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 

#### Perustelut ehdotukselle   

Ammatillisessa koulutuksessa ryhmäohjaaja-termi on korvautunut osittain omaopettaja-termillä 

#### Tarkoitusta täsmentävä selite   

https://termipankki.fi/tepa/fi/haku/omaopettaja 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Opetuskäytössä 

**Termiehdotus Fintossa:** [Omaopettaja](http://finto.fi/yse/fi/page/Y509485)

**Comment by jtuohini** [comment]
Ovatko kaikki ryhmänohjaajat omaopettajia? T.s. olisiko KT-muodon parempi olla _ryhmänohjaajat (omaopettajat)_?

**Comment by AuHo22** [comment]
Ryhmäohjausta toteutetaan Jyväskylän yliopistossa monin eri nimikkein: opettajatutorointi, kotiryhmätoiminta, omaopettaja-toiminta yms. https://www.jyu.fi/fi/opiskelijalle/opintojen-suunnittelu/opintojen-ohjaus#autotoc-item-autotoc-6
->
Eroaako omaopettaja ryhmäohjaajasta siinä, että on myös yksilöohjaaja? Muuten voidaan puhua tutoreista/tutoroinnista (YSO-termejä)?

**Comment by mariaforsen** [comment]
Yllä oleva ehdottajan TEPA-linkki siis johtaa termiin HOKS-ohjaaja, sv. PUK-handledare
Sv. egenlärare? Kaikki ryhmänohjaajat eivät ole omaopettajia. Kielitoimiston sk. : ryhmänohjaaja: harrastus-, leiri-, terapia- tms. ryhmän ohjaaja; erik. lukion opetusryhmän ohjaaja ja valvoja.

https://www.kielitohtori.fi/suomen-kielenhuollon-kysymys/ryhm%C3%A4nohjaus-vai-ryhm%C3%A4ohjaus-ent%C3%A4-ryhm%C3%A4nohjaaja-vai-ryhm%C3%A4ohjaaja

**Comment by fantsby-m** [comment]
Ehdotuksessa viitataan ammatilliseen koulutukseen, mutta hakutuloksissa Googlella enemmän esillä yliopistoja. 
Melindassa haku **[omaopettaj?](https://melinda.kansalliskirjasto.fi/F/G3G2JB67MAY8JPRYARABX2PL2N153RYEX1AAKRGR1SEMNGDRQD-04325?func=find-b&request=omaopettaj%3F&find_code=WRD&x=0&y=0)** tuottaa yhdeksän hakutulosta, liittyvät yliopistoihin/korkeakouluihin.

**Comment by mirmaid** [comment]
_Omaopettaja_-termiä käytetään sekä korkeakoulujen että ammattioppilaitosten ja jopa autokoulujen verkkosivuilla. Voidaanko ajatella, että kyse on riittävän samasta asiasta? On varmasti osin päällekkäinen _tutorit_ ja _luokanvalvojat_ -termien kanssa - kasvatusalan termistössä jatkuva vaihtuvuus on kyllä sanastotyölle melkoinen haaste.

**Comment by YSO-kokous** [comment]
Hyväksyttiin äänestyksen jälkeen.

**Comment by jtuohini** [comment]
Kai sentään monikossa? Koska jos olisi yksikössä, pitäisi olla "omaopettajatoiminta" tms.

**Comment by mariaforsen** [comment]
Sv. egenlärare
https://www.abo.fi/studera-hos-oss/du-som-redan-studerar/studieinformation/egenlarare-och-tutorer/
