### ISSUE TITLE
lausunnot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9486]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lausunnot](http://www.yso.fi/onto/ysa/Y96796) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään LT-suhde "tietoaineistot" (https://github.com/Finto-ehdotus/YSE/issues/9470) 

#### Perustelut ehdotukselle   

SLM:n hierarkin täydentäminen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytään LT ei-fiktiiviset aineistot.
