### ISSUE TITLE
muistiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9489]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muistiot](http://www.yso.fi/onto/ysa/Y103521) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään LT-suhde "tietoaineistot" (https://github.com/Finto-ehdotus/YSE/issues/9470) 

#### Perustelut ehdotukselle   

SLM:n hierarkian parantaminen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytään LT ei-fiktiiviset aineistot.
