### ISSUE TITLE
mietinnöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9490]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[mietinnöt](http://www.yso.fi/onto/ysa/Y102634) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään LT-suhde "tietoaineistot" (https://github.com/Finto-ehdotus/YSE/issues/9470) 

#### Perustelut ehdotukselle   

SLM:n hierarkin parantaminen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytään LT ei-fiktiiviset aineistot.
