### ISSUE TITLE
autofiktio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9496]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[autofiktio](http://www.yso.fi/onto/ysa/Y184605) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä lisätään LT-suhde "kaunokirjallisuus" 

#### Perustelut ehdotukselle   

Jos autofiktio on määritelty fiktion lajiksi, lukeutuu se silloin kaunokirjallisuuteen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Hyväksytään muutos.
