### ISSUE TITLE
tekniset piirustukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9499]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tekniset piirustukset](http://www.yso.fi/onto/ysa/Y103941) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-suhde "tietoaineistot" (https://github.com/Finto-ehdotus/YSE/issues/9470) 

#### Perustelut ehdotukselle   

SLM:n hierarkin parantaminen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
LC:ssä Drawings -termin yläterminä Visual works, ei Informational works, sis. myös esim. arkkitehtien tekniset piirustukset, [Architectural drawings] ja [Geological cross-sections]
Myös Maps-termillä 3 ylätermiä: Cartographic materials, Informational works, 
Visual works

**Comment by mirmaid** [comment]
Hyväksytään LT ei-fiktiiviset aineistot.
