### ISSUE TITLE
Kantola (Kauhava)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9500]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Kantola (Kauhava)

**Ehdotettu termi ruotsiksi**

Kantola (Kauhava)

**Ehdotettu termi englanniksi**

Kantola

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Puuhakas kylä nimeltä Kantola

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Kauhavalla on kaksi Kantola-nimistä kylää:
http://paikkatiedot.fi/so/1000772/10095465
http://paikkatiedot.fi/so/1000772/10319482

Tarkenne: https://fi.wikipedia.org/wiki/Kauhava

Kummasta ko. julkaisussa mahtoi olla kyse?

**Comment by ilona-x** [comment]
Asutusnimihakemiston perusteella toinen Kauhavan Kantola-nimisistä kylistä on sijainnut aiemmin Alahärmässä
https://kaino.kotus.fi/asutusnimihakemisto/index.php?a=listaus&hakunimi=Kantola
Joten olisikohan tuossa kirjassa ollut sitten kyseessä se kylä, joka on sijainnut alunperinkin Kauhavalla. 🤔 Eli siis tämä http://paikkatiedot.fi/so/1000772/10319482

Tarkenne onkin sitten tälle "alkuperäiselle" Kauhavan Kantolalle onkin sitten hankalampi homma. Nuo wikipedian Alahärmän alue ja Kauhavan alue kuulostavat ehkä erikoisilta, kun nyt molemmat sijaitsevat kuitenkin Kauhavalla.

**Comment by mirmaid** [comment]
Kantola (Kauhava, Kauhavan alue)
kantola (Kauhava, Alahärmän alue)
