### ISSUE TITLE
tacot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9501]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tacot

**Ehdotettu termi ruotsiksi**

tacos

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvittaisiin keittokirjojen kuvailuun.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Fredagskockens hamburgare & tacos 9789155269401

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [tacot](http://finto.fi/yse/fi/page/Y509501)

**Comment by mirmaid** [comment]
10 viitettä Melindassa.

http://id.loc.gov/authorities/subjects/sh00000014
