### ISSUE TITLE
keltavuokko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9503]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

keltavuokko

**Ehdotettu termi ruotsiksi**

gulsippa

**Ehdotettu termi englanniksi**

yellow anemone

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Laji. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [vuokot](http://www.yso.fi/onto/yso/p21925)

**Ehdotetut temaattiset ryhmät**

 [16 Kasvitiede](http://www.yso.fi/onto/yso/p26533)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://en.wikipedia.org/wiki/Anemonoides_ranunculoides)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Melinda

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [keltavuokko](http://finto.fi/yse/fi/page/Y509503)

**Comment by jarmosaarikko** [comment]
lajisto: http://tun.fi/MX.37883 
wikidata https://www.wikidata.org/wiki/Q161045  
wikipedia https://en.wikipedia.org/wiki/Anemonoides_ranunculoides
