### ISSUE TITLE
SLM pulmapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9507]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

SLM pulmapelit 

#### Ehdotettu termi englanniksi   

puzzle game 

#### Perustelut ehdotukselle   

on jo strategiapelit ja älykkyyspelit, mutta niissä on hieman eri näkökulma, pulmapelissä lähtökohta on hauskuus ja ongelmanratkaisu ei niinkään strategia tai älykkyys. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

5056208810977 

**Termiehdotus Fintossa:** [SLM pulmapelit](http://finto.fi/yse/fi/page/Y509507)

**Comment by mariaforsen** [comment]
Tämäkö: https://fi.wikipedia.org/wiki/Pulmapeli ? Määritelmät eivät tosin näytä oikein täsmäävän?
Sv. pusselspel?

**Comment by mirmaid** [comment]
Seuraava kokous: Marjut, Auli ja Anna selvittävät.

**Comment by AuHo22** [comment]
Kommentti kysytty: pulmapelit on ehkä monipuolisempi termi kuin älykkyyspelit, joten tuo olisi ihan hyvä, että älykkyyspelit ohjaisi käyttämään pulmapelit. 
Älykkyyspelit menee mielestäni myös lähelle strategiapelejä, joten siinäkin mielessä tuo olisi hyvä ja selkeä muutos. Näin peleihin kommenttina.

**Comment by annavii** [comment]
Meilläkin peliasiantuntijat kannattivat älykkyyspelien vaihtamista pulmapeleiksi.

**Comment by mariaforsen** [comment]
Eli mihin tällä termillä halutaan viitata? Onko se sama kuin wikipedian määritelmässä: "Pulmapeli on videopelilajityyppi, jossa painopiste on ongelman tai pulmatehtävän ratkaisemisessa."? Kuvahaussa (google) tulee aivan erityyppiset pelit (ei tietokonepelejä). Olisiko eng. todella puzzle games (vrt. https://en.wikipedia.org/wiki/Puzzle_video_game )? Googlesta löytyy myös "ongelmanratkaisupeli", olisiko se mahdollisesti KT?

**Comment by marjutpu** [comment]
Kommentteja Helsingistä:
- Onhan noita jokunen konsolipeli, jotka voisi laittaa pulmapelin alle.
- Lautapeleissä pulmapelejä kyllä on, hieman rinnakkaisia pakopelien kanssa.
- Älykkyyspelit on omasta mielestäni vähän loukkaava termi.
- Sopii konsolipeleihin: pelaaminen painottuu yleensä "pulmien" ympärille. Älykkyyspeleissä on ehkä enemmän perinteisen ÄO-testin tyyppisiä tehtäviä ja strategiapeleissä ollaan yleensä jotain vastustajaa tai pelin omaa mekaniikkaa vastaan, joka yritetään päihittää. Pulmapelit voivat olla myös (ja useimmiten mun mielestäni) yksinkin pelattavia. Sittenhän on vielä tällaiset "point and click" -pelit, joissa ratkotaan esim. rikoksia etsimällä (kilkkaamalla) vihjeitä ympäristöstä.

**Comment by ilona-x** [comment]
https://www.lautapelit.fi/category/131/alypelit

**Comment by mirmaid** [comment]
Joudutaan mahdollisesti ottamaan erikseen digitaaliset pulmapelit ja fyysiset pulmapelit, vrt. esim. https://fi.wikipedia.org/wiki/Mekaaninen_pulma, https://www.suomalainen.com/search?q=pulmapeli+lautapeli, https://www.lautapelit.fi/category/131/alypelit. 

Mitkä termit sopisivat erottelemaan eri merkitykset? (Marjut selvittää vielä.) Voisiko jokin olla esim. ongelmanratkaisupelit?

**Comment by mariaforsen** [comment]
Sv. problemlösningsspel? Pusselspel=datorspelgenre som bygger på ett eller flera moment där objekt som liknar eller kompletterar varandra beträffande form eller färg på något sätt ska pusslas ihop. /WP Tosin termi käytetään myös palapeleista yms.

**Comment by marjutpu** [comment]
HKK: ongelmanratkaisupelit on pitkä sana mutta ihan hyvä, eikä siinä ole mitään eroa pulmapeliin.

**Comment by mirmaid** [comment]
Ongelmanratkaisupelit KT pulmapelit, älykkyyspelit (poistuu erillisenä).

**Comment by mirmaid** [comment]
Entä YSO?

**Comment by YSO-kokous** [comment]
### Päätös
muutetaan päätermi  SLM mukaisesti ongelmanratkaisupelit KT pulmapelit
