### ISSUE TITLE
sisälähetys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9508]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sisälähetys](http://www.yso.fi/onto/ysa/Y98878) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään määritelmä 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
NE: Inremission: benämning på den evangelisation inom det egna landet som väckelserörelser bedrivit under 1800- och 1900-talen (motsats: yttre s.k. fjärrmission). Termi ei taida rajautua aivan samalla tavalla suomeksi?

**Comment by mirmaid** [comment]
Liittyy YKL-luokkiin 25.5 ja 26.
26: Tähän ja alaluokkiin kirkkokunnasta tai kristillisestä yhteisöstä riippumatta kristillinen lähetystyö ja Raamatun levitystyö ei-kristillisillä alueilla tai ei-kristittyjen väestöryhmien keskuudessa.

Wikipedia: Kotimaassa tehtävää työtä kutsutaan sisälähetykseksi.

Nykysuomen sanakirja (1980): vapaa kristillinen toiminta, jonka tarkoituksena on johtaa kirkosta ja kristinuskosta luopuneita ja vieraantuneita takaisin kirkon yhteyteen sekä tukea ja auttaa sisäisessä ja ulkonaisessa ahdingossa olevia, vrt. ulkolähetys. | Kirkon sananjulistusta täydentävänä s. on mm. merimies-, siirtolais- ja kaupunkilähetystä. (Ulkolähetys: kristillinen lähetystyö pakanain keskuudessa, pakanalähetys.)

Kielitoimiston sanakirja: vapaa kristillinen toiminta, jonka tavoitteena on johtaa kristinuskosta vieraantuneita takaisin kristillisen elämän yhteyteen sekä tukea hengellisessä t. aineellisessa hädässä olevia. / ulkolähetys: ei-kristillisiin maihin suunnattu lähetystyö.

**Comment by AuHo22** [comment]
Heräsi kysymys siitä, mitä tarkoitetaan määritelmien **vapaalla** kristillisellä toiminnalla? Tarkoittaako se sisälähetyksen monialaisuutta - evankelioiminen, diakonia jne. - vai jotain muuta? Tietääkseni sisälähetystä harrastetaan kirkon/seurakunnan puitteissa eli siinä mielessä en ajattele sitä "vapaana".

**Comment by mirmaid** [comment]
^ Ei varmaan tarvitse ottaa sitä mukaan YSOn määritelmään. Kaipaisin itse kuitenkin selkeytystä siihen, milloin ulkomaille suuntautuvasta lähetystyöstä käytetään _sisälähetys_-sanaa. Jos rajaus menee sen mukaan, onko kyse ei-kristitystä maasta, taitaa hyvin suuri osa lähetystyöstä olla kyllä sisälähetystä, tai ainakin lähellä sitä (maassa on jo vakiintunut kristillinen yhteisö).

**Comment by mariaforsen** [comment]
Ruotsiksi inremission on kotimaassa tehtävää lähetystä (kuten esim. Nationalencyklopedin määritelmässä).

**Comment by FinMeSHienPaimentaja** [comment]
Seuraavassa uskonnon ammatti-ihmisen näkemys asiasta: 

"Perinteisesti  'sisälähetys(työ)' on ollut kotimaassa tapahtuvaa työtä lähetystyön mahdollistamiseksi. 

'Sisälähetys(työ)' on 1900-luvun termi - kirkkomme ei käyttänyt Suomessa tehtävästä työstä termiä lähetystyö, vaan  Suomessa tehtiin sisälähetystyötä, jolla tuettiin ulkomailla tehtävää  lähetystyötä. Kristilliset järjestöt tekivät siis lähetystyötä ulkomailla ja kotimaassa tehtävä työ oli sisälähetystyötä, eli tilaisuuksien järjestäminen yhdessä seurakuntien kanssa tai järjestöjen omat tilaisuudet.   Silloin ei Suomessa paljon evankelioitu koska yli 90% kuului kirkkoon, kutsuttiin kyllä osallistumaan tapahtumiin uskon vahvistamiseksi. Toki vähän jopa evankelioitiin mutta kovin vähän, myytiin kirjoja ja tuettiin lähetystyötä järjestämällä tilaisuuksia, se oli sisälähetystyötä. 

2000-luvulla tilanne on muuttunut. Kirkkoon kuuluu yhä vähemmän väkeä ja kirkossammekin on todettu, että lähetystyö alkaa kotiovelta. Nyt siis Suomessakin saa tehdä lähetystyötä ja siksi tuo termi alkaa jäädä pois käytöstä. Kaikki työ evankeliumin saattamiseksi ihmisten vastaanotettavaksi on lähetystyötä."

**Comment by ilona-x** [comment]
Lisätään nyt vielä yksi tietosanakirjamääritelmä:

**sisälähetys**, toiminta, joka pyrkii johtamaan kirkosta luopuneita ja kristinuskosta vieraantuneita takaisin kristilliseen elämään ja tukee hengellisessä ja aineellisessa ahdingossa olevia.

Lähde: Rantala, R. (1993). Tietosanakirja (2. uud. laitos.). Otava.

**Comment by mirmaid** [comment]
Jako ulkomailla vs. kotimaassa tapahtuvaan toimintaan olisi selkeämpi, kuin jaottelu sen mukaan tehdäänkö lähetystyötä (valtaväestöltään?) kristillisessa/ei-kristillisessä maassa, mutta ainakin merimieslähetys on kai ulkomailla tehtävää sisälähetystä. Asia on noussut esiin alun perin Inkerinmaalla tai Karjalassa tehtävää lähetystyötä käsittelevissä aineistoissa, kun ei ole löytynyt oikein selkeää ohjeistusta kumpaa asiasanaa tai YKL-luokkaa pitäisi käyttää.

**Comment by AuHo22** [comment]
Törmäsin useampaankiin kirjoitukseen, jossa sisä- ja ulkolähetykseen tehtävää jakoa ei pidetä enää tarkoituksenmukaisena tai se koetaan vanhentuneena, yksi perustelu oli mm. Suomessa maahanmuuttajien keskuudessa tehtävä lähetystyö. Ja usein tähän sitten liittyi diakoniatyötä, eli Ilonan yllä oleva määritelmä olisi sopiva siitäkin näkökulmasta.
Tässä myös meiltä saatu kommentti lähetystyöntekijätuttavien työstä: "Sisälähetystä on JO kristityille tehtävä lähetystyö maasta ja paikasta riippumatta. Varsinainen lähetystyö (ulkolähetys) tarkoittaa ei-kristittyjen keskuudessa tehtävää työtä (usein nämä voivat mennä päällekkäin; esim. ystäväperheeni oli tekemässä Japanissa lähetystyötä. Se, mitä tehtiin suomalaisten kanssa oli sisälähetystä, se, mitä ei-kristillisten kanssa oli (ulko)lähetystyötä. Lähetysseura oli heidän palkanmaksajana)."
Myös diasporatyöstä keskusteltiin asiasanana (on YKL:ssä), mikä olisi tainnut sopia tuohon ko. Inkerinmaata koskevaan tietueeseen.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta.
