### ISSUE TITLE
vedenalainen kulttuuriperintö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9509]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vedenalainen kulttuuriperintö 

#### Ehdotettu termi englanniksi   

underwater cultural heritage 

#### Ehdotettu termi ruotsiksi   

kulturarv under vatten 

#### Vaihtoehtoiset termit ja ilmaisut   

undervattenskulturarv 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuuriperintö](http://www.yso.fi/onto/yso/p8475) 

#### Vastaava käsite muussa sanastossa   

vedenalainen kulttuuriperintö : <http://www.yso.fi/onto/mao/p9291> 
Underwater Cultural Heritage : <http://www.unesco.org/new/en/culture/themes/underwater-cultural-heritage/> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

Ihmisen toiminnasta syntyneitä veden alla sijaitsevia jäännöksiä nimitetään vedenalaiseksi kulttuuriperinnöksi.
https://www.museovirasto.fi/fi/kulttuuriymparisto/arkeologinen-kulttuuriperinto/vedenalainen-kulttuuriperinto 
https://itameri.fi/fi-FI/Luonto_ja_sen_muutos/Asiantuntijan_kynasta/Itameri__vedenalaisen_kulttuuriperinnon_(52467) 

#### Perustelut ehdotukselle   

Asiasanaa vedenalainen kulttuuriperintö käytetty Melindassa 34ssä tietueessa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1h3k2rg/alma9933772104806253 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [vedenalainen kulttuuriperintö](http://finto.fi/yse/fi/page/Y509509)

**Comment by mirmaid** [comment]
On MAOssa.

**Comment by AuHo22** [comment]
Vedenalainen arkeologia YKL:ssä -> Vedenalainen arkeologia (90.4) eli Ryhmä 51 Arkeologia

**Comment by krinay** [comment]
Vedenalainen arkeologia on myös YSOssa (Ryhmä 51). 

Määritelmät MAOssa (jossa siis molemmat käsitteet):

vedenalainen arkeologia
vedenalaisten kohteiden tutkimus arkeologisin menetelmin

vedenalainen kulttuuriperintö
kulttuuriperintö, joka on veden pinnan alapuolella
