### ISSUE TITLE
Kommunikaatiohäiriöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9512]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Kommunikaatiohäiriöt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Communication Disorders

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kommunikaatihäiröt käsite auttaa mm. logopedian aineiston kuvailua. Käsite on TERO:ssa (https://finto.fi/tero/fi/page/T00196). Kommunikaatiohäiriöt -käsite eroaa jo YSO:sta löytyvästä kielelliset häiriöt (http://www.yso.fi/onto/yso/p2234) -termistä. merkitys on laajempi. Kommunikaatio -sana pitää sisällöön esimerkiksi non-verbaalisen kommunikaation (esim. katsekontakti).

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [MeSH]( http://www.yso.fi/onto/mesh/D003147)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://primo.uef.fi/permalink/358FIN_UOEF/1aabkvo/alma997795353705966s

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Kommunikaatiohäiriöt](http://finto.fi/yse/fi/page/Y509512)

**Comment by mariaforsen** [comment]
Sv. kommunikationsstörningar

**Comment by AuHo22** [comment]
LCSH Communicative disorders

**Comment by mirmaid** [comment]
Ei Lääketieteen termit -sanastossa. 

On kyllä hyvin lähellä kielelliset häiriöt -käsitellä: _A communication disorder is any disorder that affects an individual's ability to comprehend, detect, or apply language and speech to engage in discourse effectively with others_. https://en.wikipedia.org/wiki/Communication_disorder Ongelmallista, että vaikka tämä onkin vähän laajempi, käyttö olisi suurelta osin päällekkäistä (?).

**Comment by YSO-kokous** [comment]
Todettiin, että menee helposti päällekkäin kielellisten häiriöiden kanssa. 
Lisätään ohjaustermiksi: kommunikaatiohäiriöt (kielelliset häiriöt) KÄ kielelliset häiriöt
