### ISSUE TITLE
foxtrotit (sävellykset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9514]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[foxtrotit (sävellykset)](http://www.yso.fi/onto/ysa/Y161295) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "foksit", "fokstrotit" ja "foxit" YSO:on ja SLM:ään 

#### Perustelut ehdotukselle   

https://www.wikidata.org/wiki/Q245418 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi
