### ISSUE TITLE
sulfaattimenetelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9515]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sulfaattimenetelmä 

#### Ehdotettu termi ruotsiksi   

sulfatprocessen 

#### Ehdotettu termi englanniksi   

kraft process 

#### Ehdotettu yläkäsite YSOssa (LT)   

[massanvalmistus](http://www.yso.fi/onto/yso/p12560) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh85130334.html 
Wikipedia : https://fi.wikipedia.org/wiki/Sulfaattimenetelm%C3%A4 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[28 Metsäteollisuus. Massa- ja paperiteollisuus. Paperiteollisuus. Puuteollisuus](http://www.yso.fi/onto/yso/p26585) 

#### Perustelut ehdotukselle   

Kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://lutpub.lut.fi/handle/10024/162289 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [sulfaattimenetelmä](http://finto.fi/yse/fi/page/Y509515)

**Comment by mirmaid** [comment]
GEO-ontologiassa. Käytetty 14 kertaa Agrifors-terminä, ei ole auktorisoituna AFOssa.

**Comment by ilona-x** [comment]
ohjaustermiksi sulfaattiprosessi?

IATE3
fi        sulfaattimenetelmä;
sulfaattiprosessi
sv       sulfatprocess
en      sulphate pulping process;
sulfate pulping process

Lähde: IATE 10.08.2021, Euroopan unioni (1107911)
https://termipankki.fi/tepa/fi/haku/sulfaattimenetelm%C3%A4

**Comment by mariaforsen** [comment]
Sv. sulfatprocessen HT sulfatmetod, sulfatmetoden, sulfatprocess 

https://svenska.se/tre/?sok=sulfatmetod&pz=1
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_ce02a6a22ce571b02bbfe89e60501631&list_id=1&keyword=sulfaattimenetelm%C3%A4&word=sulfaattimenetelm%C3%A4
https://sv.wikipedia.org/wiki/Sulfatprocessen
https://id.kb.se/find?q=Sulfate%20pulping%20process
