### ISSUE TITLE
spin casting

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9516]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[spin casting](http://www.yso.fi/onto/yso/p17186)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

en-päätermin vaihto muotoon "spin fishing"

**Perustelut ehdotukselle**

Wikipediasta löytyy kolme eri merkitystä termille "spin casting".  https://en.wikipedia.org/wiki/Spin_casting_(mirrors)  ja https://en.wikipedia.org/wiki/Spin_casting  https://en.wikipedia.org/wiki/Centrifugal_casting_(industrial)

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jarmosaarikko** [comment]
https://en.wikipedia.org/wiki/Spin_fishing  https://www.wikidata.org/wiki/Q10998454
