### ISSUE TITLE
vanhojentanssit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9517]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vanhojentanssit 

#### Vaihtoehtoiset termit ja ilmaisut   

vanhojen tanssit 
wanhojen tanssit 
wanhojentanssit 
vanhojenpäivän tanssiaiset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[tanssiaiset](http://www.yso.fi/onto/yso/p27351) 
[koulujuhlat](http://www.yso.fi/onto/yso/p8256) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554) 
[95 Teatteri. Tanssi](http://www.yso.fi/onto/yso/p26582) 

#### Perustelut ehdotukselle   

Huomattava määrä aineistoa Finnassa tästä aiheesta, niin kuvia kuin artikkeleita – vai riittääkö kuvailuun asiasana "tanssiaiset" 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [vanhojentanssit](http://finto.fi/yse/fi/page/Y509517)

**Comment by jtuohini** [comment]
Lisäksi RT [**vanhojenpäivä**](http://www.yso.fi/onto/yso/p25642). Suhde toki "part of" -tyyppiä, joten LT olisi vaistonvaraisesti parempi, mutta jo vain "is a" -suhde edelleen kelpaa sellaiseksi…

**Comment by satuniininen** [comment]
Vai riittäisikö pelkkä vanhojenpäivä + tanssiaiset?

**Comment by mirmaid** [comment]
Kerran Melindassa.

**Comment by jtuohini** [comment]
Mutta kuvia Finnassa peräti 44 kpl

**Comment by YSO-kokous** [comment]
Ohjaustermiksi: vanhojentanssit KÄ vanhojenpäivä
