### ISSUE TITLE
popcorn

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9518]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[popcorn](http://www.yso.fi/onto/yso/p8702)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään KT-muoto "paukkumaissi"

**Perustelut ehdotukselle**

Vanhahtava, mutta edelleen käytetty nimitys samalle asialle. Ks. esim. https://fi.wikipedia.org/wiki/Popcorn ja https://www.kielitoimistonsanakirja.fi/paukkumaissi

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään KT paukkumaissi
