### ISSUE TITLE
julkisuusperiaate

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9520]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

julkisuusperiaate

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Julkisuusperiaate tarkoittaa julkisen hallinnon avoimuutta.
https://fi.wikipedia.org/wiki/Julkisuusperiaate

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [julkisuus](http://www.yso.fi/onto/yso/p882), [laki viranomaisten toiminnan julkisuudesta](http://www.yso.fi/onto/yso/p9064)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-11-4813-2

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [julkisuusperiaate](http://finto.fi/yse/fi/page/Y509520)

**Comment by jtuohini** [comment]
Ja RT-suhteeksi varmaan myös [**avoimuus**](http://www.yso.fi/onto/yso/p10569), myös RT-suhteiseksi ehdotetulle **julkisuus**-asiasanalle, koska liittyvät vahvasti toisiinsa?

**Comment by mariaforsen** [comment]
Sv. offentlighetsprincipen. Ks. https://en.wikipedia.org/wiki/Principle_of_public_access_to_official_records

**Comment by fantsby-m** [comment]
Termi on myös julkisuuslaissa heti 1 §:ssä: https://www.finlex.fi/fi/laki/ajantasa/1999/19990621
