### ISSUE TITLE
EU-asetukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9521]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

EU-asetukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Asetukset ovat sitovia säädöksiä, joita on sovellettava kaikilta osiltaan kaikkialla EU:ssa.
https://europa.eu/european-union/law/legal-acts_fi

**Perustelut ehdotukselle**

Astukset eivät ole direktiivejä, eivätkä myöskaan suomalaisia asetuksia, jotka pohjautuvat kotimaiseen lainsäädäntöön.

**Ehdotettu yläkäsite YSOssa (LT)**

 [säädökset](http://www.yso.fi/onto/yso/p4200)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

 Euroopan Unionin asetukset, asetukset (Euroopan Unioni)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kurkistuksia kollokaatioon : EU-suomen toimenpiteen rantautumisesta Suomen säädöskieleen

**Ehdottajan organisaatio**

Helsingin yliopisto
**Termiehdotus Fintossa:** [EU-asetukset](http://finto.fi/yse/fi/page/Y509521)

**Comment by jtuohini** [comment]
Eikö parempi LT olisi [**asetukset (säädökset)**](http://www.yso.fi/onto/yso/p15823)? Jos kaikki EU-asetukset ovat nimensa mukaisesti asetuksia, niin silloin ainakin pitäisi olla.

**Comment by ilona-x** [comment]
OIKO: EU-asetus http://www.yso.fi/onto/oiko/p605 
JUPO: EU-asetukset http://www.yso.fi/onto/jupo/p5588
EKS: EU-asetus

**Comment by mariaforsen** [comment]
Sv. EU-förordningar

**Comment by AuHo22** [comment]
Kotimaisessa lainsäädännössä asetukset on rajattu tietyntyyppisesti eli ei käy EU-asetusten LT:ksi, esim. EKS: 

asetukset | 
Korvaa termin: | presidentin asetus, ministeriön asetus, valtioneuvoston asetus
Asiasana ruotsiksi: | förordningar
Asiasana englanniksi: | decrees

Ja wikipedia samoin: https://fi.wikipedia.org/wiki/Asetus

asetukset (säädökset) -termi mielestäni tarkoittaa juuri tätä kotimaisen lainsäädännön tyyppiä, tai sitten jouduttaisiin muokkaamaan sanastoa näiltä osin

**Comment by YSO-kokous** [comment]
Päätös: EU-asetukset YK säädökset
