### ISSUE TITLE
EU-direktiivit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9522]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[EU-direktiivit](http://www.yso.fi/onto/yso/p10768)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään selitys:
Direktiiveissä määritellään tavoitteet, joihin kaikkien EU-maiden on yllettävä. Maat saavat kuitenkin itse päättää laeista, joilla tämä toteutetaan.
https://europa.eu/european-union/law/legal-acts_fi

**Perustelut ehdotukselle**

EU-direktiivit, toisin kuin asetukset, vaativat kansallista lainsäädäntöä

**Ehdottajan organisaatio**

Helsingin yliopisto

**Comment by YSO-kokous** [comment]
Määritelmän lisääminen ei saanut kannatusta. SIsällössä ei ole epäselvyyttä.
