### ISSUE TITLE
juonitiivistelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9524]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

juonitiivistelmät

**Ehdotettu termi ruotsiksi**

plot sammanfattningar

**Ehdotettu termi englanniksi**

plot summaries

**Tarkoitusta täsmentävä selite**

Tiivis esitys romaanin, näytelmän, oopperan tms. tarinallisen teoksen juonellisesta sisällöstä.

**Perustelut ehdotukselle**

SLM-sanastoon.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCGFT]( http://id.loc.gov/authorities/genreForms/gf2014026149)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

The complete operas of Richard Strauss https://melinda.kansalliskirjasto.fi/byid/001065748

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [juonitiivistelmät](http://finto.fi/yse/fi/page/Y509524)

**Comment by mirmaid** [comment]
Hyväksytty/SLM. Ei YSOon.

**Comment by mariaforsen** [comment]
Sv. intrigsammandrag HT intrigsammanfattningar, plottsammanfattningar, resuméer (intrig), intrigbeskrivningar

https://termipankki.fi/tepa/fi/haku/intrig
https://svenska.se/tre/?sok=plott&pz=1
jfr https://sv.wikipedia.org/wiki/Intrig_(narratologi)
