### ISSUE TITLE
latgallin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9525]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

latgallin kieli 

#### Vastaava käsite muussa sanastossa   

https://fi.wikipedia.org/wiki/Latgallin_kieli 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9789934875359 

#### Tarkoitusta täsmentävä selite   

Tarvitaan myös termi ’latgallinkielinen kirjallisuus’. 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [latgallin kieli](http://finto.fi/yse/fi/page/Y509525)

**Comment by mariaforsen** [comment]
Sv. lettgalliska
