### ISSUE TITLE
flätning

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9527]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[flätning](http://www.yso.fi/onto/yso/p27296)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voidaanko rajata kampauksiin?

**Perustelut ehdotukselle**

Käytetty Melindassa 32 kertaa, melkein vain kampauksista. Sanastossa on myös punonta, molemmat ovat ruotsiksi oikeastaan flätning, mutta vastineena on epämääräisyyden takia ollut tvinning (ei sovi Melinda-tietueisiin). Jos käsite rajataan saadaan ongelma ruotsiksi ratkaistu: flätning (frisyrer), flätning (handarbete)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
Suomeksi palmikointi, YK punonta.

**Comment by mariaforsen** [comment]
YK voisi olla kampausmerkitykselle kohdistuva toiminta ja käsityölle käsityö (toiminta)?

**Comment by mirmaid** [comment]
Sanastossa myös _letit_ (YK kampaukset). Palmikointi käytetty 33 kertaa ja 24 viitteessä myös letit.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi palmikointi (kampaukset) KÄ letit
Tutkitaan onko palmikointi käsityötekniikkana rajattavissa. Muuten poistetaan.

**Comment by mirmaid** [comment]
Ehdotettu, että poistettaisiin kokonaan. Tarvitaanko ohjausterminä palmikointi (käsityöt) KÄ punonta?

**Comment by mirmaid** [comment]
Ehdotus: palmikointi (käsityöt) KÄ punonta. Poistetaan palmikointi.
