### ISSUE TITLE
yhtymät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9528]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yhtymät](http://www.yso.fi/onto/yso/p3772)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voidaanko tarkentaa, esim. yhtymät (verotus) tai verotusyhtymät?

**Perustelut ehdotukselle**

On jo pitkään ollut ongelmalistalla, ks. https://github.com/NatLibFi/Finto-data/issues/886 Ruotsin vastine pitää vaihtaa/lisätä tarkenne. 

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
Muutetaan muotoon  verotusyhtymät KT yhtymät (verotus) 

Tarkistetaan hierarkia alakäsitteiden osalta, esim. elinkeinoyhtymät, seurakuntayhtymät, jne.
