### ISSUE TITLE
Bern

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9529]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Bern](http://www.yso.fi/onto/ysa/Y234582) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään sulkutarkenne 

#### Perustelut ehdotukselle   

Bern on sekä kaupunki että kantoni; Wikidata-linkki vie kaupunkia käsittelevään artikkeliin, mutta muutoin ei voi olla varma, kumpaan viitataan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Myös Genevellä sama huomautus.

**Comment by ilona-x** [comment]
Fribourg jaettiin: Fribourg (kantoni) ja Fribourg (kaupunki) https://github.com/Finto-ehdotus/YSE/issues/9416

**Comment by mirmaid** [comment]
Jaetaan Bern ja Geneve.
