### ISSUE TITLE
steampunk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9530]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[steampunk](http://www.yso.fi/onto/ysa/Y226759) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään sulkutarkenne "(kaunokirjallisuus)" tms. 

#### Perustelut ehdotukselle   

Steampunk vaikuttaa olevan laajempi asia kuin vain yksi kaunokirjallisuuden tyylilajeista, ks. esim. https://yle.fi/uutiset/3-12106196. Sekaantumisen välttämiseksi olisi hyvä lisätä sulkutarkenne, ettei joku kuvaile vaikkapa steampunk-pukuja käsittelevää aineistoa YSO:n yksinomaan kirjallisuuteen varatulla asiasanalla. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Ks. myös https://github.com/Finto-ehdotus/YSE/issues/7333#issuecomment-957134348

**Comment by YSO-kokous** [comment]
Ei muutosta. Voidaan käyttää yleisesti kaikesta. 
Tarkistetaan hIerarkia.
