### ISSUE TITLE
iltapala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9532]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

iltapala

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Suomalaiselle kulttuurille ominainen ateria. Keittokirjoissa (suomenkieliset) usein reseptit ryhmitelty ateriatyypeittäin. Iltapala ei ole sama kuin illallinen, päivällinen tai välipala.  

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [24 Ravitsemus. Ravitsemisala. Elintarvikeala. Majoitusala. Kotitalous](http://www.yso.fi/onto/yso/p26555)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://oula.finna.fi/Record/oy.9916110463906252

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [iltapala](http://finto.fi/yse/fi/page/Y509532)

**Comment by ilona-x** [comment]
Ehdotuksessa mainitun teoksen "Helppo olla vege : Härkis-reseptejä aamiaisesta iltapalaan" kuvailuun ei ole laitettu YSOssa olevia ateriatyyppejä, joten juuri tuon teoksen kuvailuun termi ei liene välttämätön.

Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. kvällsmål tms.

**Comment by mirmaid** [comment]
Ei Melindassa. Ateriana kuitenkin aika saman tyyppinen kuin välipala, ehkä siksi ei ole ollut tarvetta termille tähän asti.

**Comment by AuHo22** [comment]
Mielestäni välipala on jotain aterioiden välillä nautittavaa ja iltapalan myötä voidaan pikku hiljaa mennä nukkumaan - voisi kuvitella että vanhustenhuollossa myös olisi tarvetta tämänkaltaiselle termille? Aamiaiset on myös olemassa, monikossa tietysti iltapalat

**Comment by mirmaid** [comment]
^ Juu, en sinänsä vastusta. Mutta siis varmaan yleensä iltapalaksi syödään aika lailla samoja juttuja kuin välipalaksi, siksi ehkä esim. keittokirjoissa ei ole tätä tarvittu erikseen.

**Comment by YSO-kokous** [comment]
Hyväksytään monikossa: iltapalat

**Comment by mariaforsen** [comment]
Sv. kvällsmål HT kvällsbitar, vickningar, lätta kvällsmåltider, kvällsmat
