### ISSUE TITLE
karnaattinen musiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9533]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

karnaattinen musiikki

**Ehdotettu termi ruotsiksi**

karnatiska musiken

**Ehdotettu termi englanniksi**

carnatic music

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

YSO- ja SLM-termiksi.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 Etelä-Intian taidemusiikki

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://lccn.loc.gov/sh85088861), [LCGFT](https://lccn.loc.gov/gf2014026693)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 https://melinda.kansalliskirjasto.fi/byid/016336489

**Ehdottajan organisaatio**

Taideyliopiston kirjasto
**Termiehdotus Fintossa:** [karnaattinen musiikki](http://finto.fi/yse/fi/page/Y509533)

**Comment by mariaforsen** [comment]
Sv. karnatisk musik

**Comment by YSO-kokous** [comment]
Odotetaan Muusan kantaa

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
LT taidemusiikki
Määritelmä: Eteläisen Intian taidemusiikin traditio.

**Comment by mirmaid** [comment]
Eteläisen Intian taidemusiikin traditioon kuuluvat teokset.

**Comment by mirmaid** [comment]
Hyväksytty/SLM.
