### ISSUE TITLE
leijukerrospoltto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9536]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[leijukerrospoltto](http://www.yso.fi/onto/ysa/Y96817) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

EN ohjaustermiksi
fluidized bed combustion 

#### Perustelut ehdotukselle   

Ks. esim. 
https://id.loc.gov/authorities/subjects/sh85049392.html
https://lutpub.lut.fi/handle/10024/161930 

#### Ehdottajan organisaatio   

KK

**Comment by ilona-x** [comment]
LCSHssa muodossa Fluidized-bed combustion
