### ISSUE TITLE
kielelliset vaikutukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9537]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kielelliset vaikutukset](http://www.yso.fi/onto/ysa/Y186369) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Mikä on tämän suhde käsitteeseen kielellinen vuorovaikutus, entä näiden muut käsitesuhteet? Onko selkeytettävää? 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Ruotsiksi ensimmäinen on "språkliga konsekvenser" YSOssa, eli suuntaan "kielelliset seuraukset", toinen taas on språklig interaktion, joten ruotsin osalta nämä ovat hyvin selkeästi eri asioita.

**Comment by mirmaid** [comment]
Käytännössä siis _kielellinen vuorovaikutus_ -käsitettä on käytetty runsaasti ja enimmäkseen ihmisten välisen vuorovaikutuksesta (lähinnä keskustelun) tutkimuksesta, mutta joskus myös muusta, esim. https://melinda.kansalliskirjasto.fi/byid/011639644. _Kielelliset vaikutukset_ taas on käytetty vain 35 kertaa, siitä miten kieli vaikuttaa kulttuuriin tai toiseen kieleen.

**Comment by mirmaid** [comment]
Näyttäisi käytetyn myös digitaalisista peleistä 🤔.

**Comment by mirmaid** [comment]
Onko RT anglismit, finlandismit ja svetisismit ok _kielellinen vuorovaikutus_ -käsitteessä? Eikö niissä kyse ole kielellisistä vaikutuksista?

**Comment by mariaforsen** [comment]
Ruotsiksi oikeampi RT-suhde on kyllä varmaan kielellinen vuorovaikutus.

**Comment by mariaforsen** [comment]
Mielestäni ok.

**Comment by mariaforsen** [comment]
Riippu tulkinnasta, ruotsiksi ei ainakaan varmaan mielletä että finlandismi olisi eräänlainen "språklig konsekvens".

**Comment by mirmaid** [comment]
Mielestäni ne tuntuvat aika kaukaa haetuilta tuossa _kielellinen vuorovaikutus_ -käsitteessä (eli kun puhutaan ihmisten välisestä kielellisestä vuorovaikutuksesta). Enemmän niissä mielestäni on kyse yhden kielen vaikutuksesta toiseen kieleen.

**Comment by YSO-kokous** [comment]
**Alustava työstö**

Mahdollisesti jaetaan _kielelliset vaikutukset_, toinen merkitys rajautuisi ihmisryhmiin kodistuviin kielellisiin vaikutuksiin, ja toinen käsittäisi kielen vaikutuksen toiseen kieleen.

Ehdotettu yhtenä mahdollisuutena _kielellisten vaikutusten arviointi_ (RT _kielelliset oikeudet_).

**Comment by krinay** [comment]
YSOssa on myös _kielikontaktit_ (KT lainautuminen; RT anglismit, finlandismit, svetisismit yms.).

Kielitieteen ontologiassa ei ole termiä _kielikontaktit_. Anglismit yms. ovat RT-suhteessa käsitteeseen _kielellinen vuorovaikutus_. Termiä _kielelliset vaikutukset_ KTOssa ei ole. (On _kielellinen vaikuttaminen_, englanniksi linguistic influence, RT koodinvaihto yms.)

**Comment by fantsby-m** [comment]
> Riippu tulkinnasta, ruotsiksi ei ainakaan varmaan mielletä että finlandismi olisi eräänlainen "språklig konsekvens".

Mutta olisiko se "språklig influens"? Vastaavatko YSOn suomen- ja ruotsinkieliset termimuodot nyt toisiaan? Eikö _konsekvenser_ olisi pikemminkin _seuraukset_?

**Comment by mariaforsen** [comment]
"Kielelliset vaikutukset" käännetään ruotsiksi eri termeillä riippuen mistä on kyse, ks. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_4cfa9cbb63898e43140ba94e3fd56606&list_id=1&keyword=vaikutus&word=vaikutus 

Jos kyseessä on ihmisiin vaikuttavat asiat, termi ei ole influens, vaan konsekvenser on ollut oikea kun on kyseessä esim. yllä mainitut kielellisten vaikutusten arviointi-asiayhteydet. Influens voi olla varteenotettava vaihtoehto jos kyseessä on esim. kieleen vaikuttava asia. Esim. tässä https://www.sprakbruk.fi/-/om-svenskans-inverkan-pa-finskan on oikea termi "språkliga influenser".

**Comment by fantsby-m** [comment]
Ymmärrän, ehkä ongelmana onkin pikemminkin se että suomessa samalla termillä voidaan tarkoittaa sekä toisen kielen/kulttuurin vaikutusta kieleen että esim. lainsäädännön vaikutusta kielellisiin oikeuksiin. Koko termi ei siinä mielessä ole kovin hyvä.

**Comment by mirmaid** [comment]
Ollaanko kuitenkin yhtä mieltä siitä, että anglismit, finlandismit ja svetisismit eivät liity _kielelliseen vuorovaikutukseen_ (språklig interaktion), vaan RT-suhde pitäisi poistaa?

Jos sen merkityskenttä on selkeä (vaikka ilmeisesti jokunen satunnainen virhe löytyy), voidaan jatkaa _kielelliset vaikutukset_ -käsitteen työstämistä tästä erillään.

**Comment by krinay** [comment]
Tieteen termipankissa (kielitiede) on myös termi _kieltenvälinen vaikutus_ (en crosslinguistic influence), joka tuntuisi ehkä jotenkin yksiselitteisemmältä kuin _kielelliset vaikutukset_. Määritelmää termipankissa ei kylläkään ole. https://tieteentermipankki.fi/wiki/Kielitiede:kieltenv%C3%A4linen_vaikutus 

Kieltenvälisen vaikutuksen alakäsitteenä on _kielikontakti_, joka on YSOssakin. Määritelmä: "Vaikutusta kahden tai useamman erillisen kielen välillä." -- "Kielikontaktien tuloksia kielissä ovat esimerkiksi lainasanat ja muutokset kielten äännerakenteessa." 
https://tieteentermipankki.fi/wiki/Kielitiede:kielikontakti

**Comment by mirmaid** [comment]
^ Kieltenvälinen vaikutus kuulostaa kyllä paljon selkeämmältä kuin kielelliset vaikutukset. Jotenkin tuo kielikontaktit tuntuisi olevan jotain, mistä vasta seuraa niitä vaikutuksia...siis se, että ollaan kontaktissa toiseen kieleen.

**Comment by mirmaid** [comment]
Ehkä voisi taas tehdä muut muutokset ja korjaukset ensin, ja vasta sitten aineistojen valossa pohtia, mitä tarvitaan liittyen vähemmistökielten asemaan jne.

**Comment by mirmaid** [comment]
Ehdotettu siis
- poistetaan _kielellinen vuorovaikutus_ -käsitteen RT-suhde käsitteisiin anglismit, finlandismit ja svetisismit
- muutetaan _kielelliset vaikutukset_ muotoon kieltenvälinen vaikutus (tai kieltenväliset vaikutukset)

**Comment by tpalonen** [comment]
kieltenvälinen vaikutus RT kielikontaktit?

**Comment by fantsby-m** [comment]
Jos muutetaan kielelliset vaikutukset muotoon kieltenvälinen vaikutus (tai kieltenväliset vaikutukset), kuten yllä ehdotettiin, niin uusi termimuoto ei sopine enää esim näihin julkaisuihin:
https://melinda.kansalliskirjasto.fi/byid/009789165
https://melinda.kansalliskirjasto.fi/byid/006135101
https://melinda.kansalliskirjasto.fi/byid/006429386

**Comment by mariaforsen** [comment]
Se onkin nimenomaan ongelma tässä ruotsin kannalta että melko tärkeä termi ja merkitys häviää sanastosta.

**Comment by fantsby-m** [comment]
Häviää se silloin suomen kannaltakin.

**Comment by mariaforsen** [comment]
Näköjään alle 50 kertaa Melindassa, joten ehkä haitta ei ole suuri (ellei Ylellä enemmän käytetty..)

**Comment by mirmaid** [comment]
Ja siis oikeastaan se mikä häviää, on aikaisemman termin virheellinen käyttö. Mutta ehdotin tuolla ylempänä, että korjausten jälkeen voidaan (vaikkapa erillisessä issuessa) pohtia, tarvitaanko jotain muita toimia vielä https://github.com/Finto-ehdotus/YSE/issues/9537#issuecomment-1539776788.

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan Mirjan yllä esitetyn [ehdotuksen](https://github.com/Finto-ehdotus/YSE/issues/9537#issuecomment-1705037280) mukaisesti. Valitaan muoto _kieltenväliset vaikutukset_.

**Comment by mariaforsen** [comment]
Sv. tvärspråkliga influenser HT tvärspråkligt inflytande 
https://jyx.jyu.fi/bitstream/handle/123456789/80807/1/URN%3ANBN%3Afi%3Ajyu-202204292472.pdf
https://termipankki.fi/tepa/fi/haku/kieltenv%C3%A4linen%20vaikutus
https://sprakbruk.fi/artiklar/om-svenskans-inverkan-pa-finskan/
https://en.wikipedia.org/wiki/Crosslinguistic_influence 
https://libris.kb.se/bib/1bjc0sq5zhh0c339?vw=full
https://libris.kb.se/bib/10641583

**Comment by mariaforsen** [comment]
https://tieteentermipankki.fi/wiki/Kielitiede:kieltenv%C3%A4linen_vaikutus
https://tieteentermipankki.fi/wiki/Kielitiede:kielikontakti
kielikontakti : Määritelmä: Vaikutusta kahden tai useamman erillisen kielen välillä.
https://finto.fi/yso/fi/page/p3805
