### ISSUE TITLE
näytelmäkirjallisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9541]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[näytelmäkirjallisuus](http://www.yso.fi/onto/yso/p17229)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan itsenäisenä asiasanana ja muutetaan KT-muodoksi asiasanalle "näytelmät".

**Perustelut ehdotukselle**

Samalle käsitteelle ei tarvita kahta eri termiä ja "näytelmät" on valittu SLM-termiksi.

**Ehdottajan organisaatio**

Taideyliopiston kirjasto

**Comment by mariaforsen** [comment]
Nykyinen ruotsink. vastine näytelmille on skådespel, joten ruotsiksi se ei rajaudu pelkästään kirjallisuuteen, vaan voi olla se itse näytelmä mikä esitetään näyttämöllä. Jos suomeksi rajautuu vain tekstiin/kirjallisuuteen niin pitää varmaan korjata?
https://svenska.se/tre/?sok=sk%C3%A5despel&pz=1
https://svenska.se/so/?id=114509&ref=kcnr461178
https://svenska.se/so/?id=161586&ref=xnr280288

https://fi.wikipedia.org/wiki/N%C3%A4ytelm%C3%A4
"Sanaa näytelmä käytetään sekä tekstistä että sen esittämisestä teatterissa, mutta jos näiden eroa täytyy erityisesti korostaa, jälkimmäistä sanotaan teatteriesitykseksi." Olisiko siis huomautus tarpeen jos todella rajataan tekstiin?

**Comment by AuHo22** [comment]
Ehdotusta teatteriesityksistä ei hyväksytty YSOon, siksikin sitten tarvitaan ehkä kuitenkin näytelmät #4181

**Comment by YSO-kokous** [comment]
SIirretään ongelmakokoukseen. 
Ruotsiksi huomattava ero  dramatik vs. skådespel.
Ontologisesti näytelmäkirjallisuus ja näytelmät ovat pitkälti sama käsite.

**Comment by mariaforsen** [comment]
Näytelmäkirjallisuus on yksi kaunokirjallisuuden kolmesta päälajista (draama) ja käsitellään kirjallisuudentutkimuksessa nimenomaan sellaisena. Ks. esim. https://fi.wikipedia.org/wiki/Kaunokirjallisuus Se pitää YSOn puolella edelleen olla mahdollista käyttää sellaisiin aineistoihin missä käsitellään näytelmäkirjallisuutta tällaisena kirjallisuuden lajina. SLM:n puolella asia on luonnollisesti toisin, siellä ei tarvita tätä termiä, vaan näytelmät riittää.

**Comment by mirmaid** [comment]
Sanastossa on myös _lyriikka_ ja _runot_, SLM:ssä on lyriikka KÄ runot.

**Comment by LeKorsu** [comment]
Kannatan sekä näytelmäkirjallisuuden että näytelmien säilyttämistä ysossa, komppaan Marian perustelua yllä.

**Comment by YSO-kokous** [comment]
### Päätös
Pidetään käsitteet erillään, näytelmäkirjallisuus, näytelmät, teatteritaide
Etsitään sopivat  määritelmät, jotka selventävät käsitteiden eroa.  Tarkistetaan LCSH linkitykset.
