### ISSUE TITLE
viileä vyöhyke

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9545]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[viileä vyöhyke](http://www.yso.fi/onto/yso/p14795)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

olisiko poistettavissa tai muutettavissa?

**Perustelut ehdotukselle**

Ei näytä olevan selkeä käsite (ei juuri tietoa googlessa tms.) ja käännökset ovat samalla tavalla epämääräisiä. Melindassa käytetty 12 kertaa eikä näytä olevan sopivin asiasana niille aineistoille. Virallisia kasvillisuusvyöhykkeitä löytyy kyllä runsaasti, olisiko tämä sama kuin jokin niistä, ks. esim. https://fi.wikipedia.org/wiki/Kasvillisuusvy%C3%B6hyke

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. kyliga zonen ja tämä olisi siis hyvä poistaa.

**Comment by YSO-kokous** [comment]
Poistetaan sanastosta epäselvyyden vuoksi.  Tarkistetaan voidaanko lisätä ohjaustermiksi boreaaliselle vyöhykkeelle.
