### ISSUE TITLE
päivälliset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9547]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[päivälliset](http://www.yso.fi/onto/ysa/Y117388) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "päivällinen" 

#### Perustelut ehdotukselle   

Monikossa tarkoittaa tapahtumaa (päivälliskutsuja), ei yhdentyyppistä ateriaa. Ks. https://www.kielitoimistonsanakirja.fi/päivällinen
 
Jos tarkoitus viitata päivälliskutsuihin, pitäisi asiasanojen keskinäinen suhdekin muuttaa eli ainakin lisätä LT "kutsut (juhlat)" 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Myös aamiaiset, lounaat jne. monikossa.

**Comment by mariaforsen** [comment]
Nämä ruotsiksi yksikössä.

**Comment by AuHo22** [comment]
Voisiko olla tarkenteen kanssa eli tarkenne monikossa (ateriat)? 

Kielitoimiston esimerkit mm.: 
2. tämän- t. senpäiväinen.
Päivällinen sade.
Päivälliset vieraat.

**Comment by YSO-kokous** [comment]
Mietitään tarkemmin onko kyseessä ateriatyyppi vai järjestetty tilaisuus.  Vrt. illalliset, illallinen

**Comment by mirmaid** [comment]
Heti 10 ensimmäistä _päivälliset_-viitettä kertoo, että erottaminen ei ole mitenkään suoraviivaista - päivällinen on ateria, mutta se voi olla myös juhla-ateria alku- ja jälkiruokineen. En ehkä näe erottelua tässä kovin tarpeellisenakaan, kun pääasia kuitenkin on se ateria. 

_Illalliset_-termin käytössä on enemmän juhlakulttuuriin liittyvää aineistoa, mutta myös ruokaohjeita. Ateriana se voi tarkoittaa samaa kuin päivällinen, ja kulttuurierot vielä vaikuttavat asiaan. Yksi mahdollisuus olisi tässä kyllä yhdistäminen: illalliset (ateriat) KÄ päivälliset. Jos ruokakutsuille halutaan oma terminsä niin sekin on varmaan mahdollinen, esim. illalliskutsut/illallisjuhlat (KT päivälliskutsut?). Ja jos haluaa olla ihan varma, ettei käytetä väärin, niin toki voi myös lisätä tarkenteen päivälliset (ateriat).

**Comment by mariaforsen** [comment]
Ruotsiksi pitää varmaan tarkentaa: middag > middagar (måltider)? https://svenska.se/tre/?sok=middag&pz=1

ALLFOssa illalliset=supé ja se taas on: https://svenska.se/tre/?sok=sup%C3%A9&pz=1 Eli muutos ehkä tarpeen > kvällsmåltider? (Joka tosin tulee tosi lähelle kvällsmål=iltapalat YSOssa)

**Comment by mirmaid** [comment]
Jos tarkennetaan > päivälliset (ateriat), niin se ei siis (varmistuksena) ota mitään kantaa siihen, onko kyseessä pidoissa tarjottava kymmenen ruokalajin kattaus vai yksinkertainen arkiateria kotona. Se ei myöskään kovin tarkkaan määrittele aterian tarjoamisen ajankohtaa. Illallisen ja päivällisen erottelu aterioina ei ole suomeksi mielekästä. Iltapala on puolestaan yksinkertaisempi ateria, kuten välipala (voi olla pelkkä hedelmä, voileipä tms.).

**Comment by mirmaid** [comment]
Ja siis kyllä illallinen on = supé, mutta käytetään myös ristiin päivällisen kanssa.

**Comment by mariaforsen** [comment]
Middag ruotsiksi: "dagens huvudmåltid med det främsta (el. enda) lagade målet; numera sällan mitt på dagen", eli ajankohta tässäkään ei kovin ratkaiseva. Olisiko nämä sitten mahdollisesti yhdistettävissä? Entä aiemmin ehdotettu: illalliskutsut KT päivälliskutsut, mahdollisesti sv. middagsbjudningar?
Wikipedia: **"Vanlig middagstid i Europa varierar mellan klockan 16.00 och 22.30. I Sverige främst sen eftermiddag eller tidig kväll. Middag kan även avse en festmåltid (middagsbjudning) senare på kvällen._"**

**Comment by mirmaid** [comment]
Otetaanko siis
päivälliset (ateriat) KT illalliset (ateriat)
illalliset (juhlat) KT päivälliset (juhlat)

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan yllä esitetyn ehdotuksen mukaisesti.

**Comment by mariaforsen** [comment]
Sv. 
-middag > middagar (måltider)
-middagar (fester) HT supéer (fester), middagsbjudningar
https://svenska.se/tre/?sok=sup%C3%A9&pz=1 "mindre måltid"? stämmer ej med illalliset..
jfr https://www.kielitoimistonsanakirja.fi/#/illallinen?searchMode=all
https://sverigesradio.se/artikel/3226095
https://frageladan.isof.se/visasvar.py?svar=45083
https://sv.wiktionary.org/wiki/middag
