### ISSUE TITLE
heittokalastus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9548]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[heittokalastus](http://www.yso.fi/onto/yso/p17186)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermi virvelöinti

**Perustelut ehdotukselle**

yleiskielen termi heittokalastukselle.  https://www.vapaa-ajankalastaja.fi/kalastustapa/heittokalastus/ 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Hyväksytään KT virvelöinti
