### ISSUE TITLE
jalkapalloseurat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9549]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jalkapalloseurat

**Ehdotettu termi ruotsiksi**

fotbollsklubbar

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tai mahdollisesti ohjausterminä

**Ehdotettu yläkäsite YSOssa (LT)**

 [urheilu- ja liikuntaseurat](http://www.yso.fi/onto/yso/p2041)

**Ehdotetut temaattiset ryhmät**

 [97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [jalkapallo](http://www.yso.fi/onto/yso/p6409)

**Vastaava käsite muussa sanastossa**

 [Svenska ämnesord](https://id.kb.se/term/sao/Fotbollsklubbar)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

melinda-aineisto

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [jalkapalloseurat](http://finto.fi/yse/fi/page/Y509549)

**Comment by jtuohini** [comment]
LCSH-siltaus: [**Soccer teams**](http://id.loc.gov/authorities/subjects/sh85123848), KT _Soccer clubs_.

**Comment by ilona-x** [comment]
Melinda:
jalkapalloseurat x 6
jalkapallojoukkueet x 6
jalkapallo & urheilu- ja liikuntaseurat x 742

**Comment by LeKorsu** [comment]
Tämä on taas yksi pandoran lipas -ehdotus niin mielellään kuin itsekin käyttäisi yhtä termiä eikä yhdistelmää laji + urheilu- ja liikuntaseurat. Mutta sitten meillä on jonossa jääkiekkoseurat, salibandyseurat, koripalloseurat, lentopalloseurat, suunnistusseurat, jne jne. Olemmeko valmiit tähän?

**Comment by YSO-kokous** [comment]
Otetaan sanastoon jalkapalloseurat ja jääkiekkoseurat.

**Comment by mariaforsen** [comment]
Sv. fotbollsklubbar, ishockeyklubbar HT fotbollsföreningar, ishockeyföreningar
