### ISSUE TITLE
Ilmajoen kisailijat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9551]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Ilmajoen kisailijat 

#### Perustelut ehdotukselle   

Kirjatietue 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kirja: 9789529451388, Sofia Yli-Hannuksela : Ilmajoen kisailijat Melinda id 017989274 

#### Tarkoitusta täsmentävä selite   

Urheiluseura Ilmajoella. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546) 

**Ehdottajan organisaatio:** Seinäjoen kaupunginkirjasto **Termiehdotus Fintossa:** [Ilmajoen kisailijat](http://finto.fi/yse/fi/page/Y509551)

**Comment by jtuohini** [comment]
Yhteisö, joten kuuluu Kantoon, YSO:on!

**Comment by jtuohini** [comment]
Ja siis on jo Kannossa: [**Voimistelu- ja urheiluseura Ilmajoen Kisailijat**](http://urn.fi/URN:NBN:fi:au:finaf:000039055)!
