### ISSUE TITLE
korvatorven pallolaajennus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9552]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

korvatorven pallolaajennus 

#### Ehdotettu termi englanniksi   

balloon eustachian tuboplasty 

#### Vaihtoehtoiset termit ja ilmaisut   

BET 

#### Ehdotettu yläkäsite YSOssa (LT)   

[leikkaushoito](http://www.yso.fi/onto/yso/p842) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550) 

#### Perustelut ehdotukselle   

kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helda.helsinki.fi/handle/10138/314877 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [korvatorven pallolaajennus](http://finto.fi/yse/fi/page/Y509552)

**Comment by mariaforsen** [comment]
https://hoito-ohjeet.fi/OhjepankkiVSHPRuotsi/Ballongdilatering%20av%20%C3%B6rontrumpeten.pdf

**Comment by YSO-kokous** [comment]
Tarkistetaan vielä käyttötarve. Voidaan lisätä tarvittaessa  tarkenne.
