### ISSUE TITLE
Lapinjärvi (järvi)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9553]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lapinjärvi (järvi)](http://www.yso.fi/onto/yso/p212061)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tieto kunnasta

**Perustelut ehdotukselle**

Samannimisiä järviä on monella muullakin paikkakunnalla.

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Eli Lapinjärvi (Lapinjärvi : järvi)?

**Comment by mirmaid** [comment]
^ ok.
