### ISSUE TITLE
baskin kieli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9569]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[baskin kieli](http://www.yso.fi/onto/yso/p15830)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

euskera > euskara

**Perustelut ehdotukselle**

Omakielinen yleis(baski)kielen nimi on euskara. Euskera on tosin eniten puhuttu seitsemästä olemassa olevasta baskikielistä. Kts esim. https://www.ehu.eus/eu/web/nazioarteko-harremanak/-/international-week-20-1; standardikielen luonnista on vastannut Euskaltzaindia https://www.euskaltzaindia.eus/ - Kansalliskirjastonkin kokoelmasta löytyy teos Linguae vasconum primitiae, jossa kuvataan standardikielen synty ja periaatteet.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Päätös:  lisätään  KT euskara
