### ISSUE TITLE
intianenglanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9573]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

intianenglanti

**Ehdotettu termi ruotsiksi**

indisk engelska

**Ehdotettu termi englanniksi**

Indian English

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [englannin kieli](http://www.yso.fi/onto/yso/p2573)

**Ehdotetut temaattiset ryhmät**

 [85 Kielitiede](http://www.yso.fi/onto/yso/p26557)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Intianenglanti), [LCSH](http://id.loc.gov/authorities/subjects/sh2008119611)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Crossing the borders : the influence of Indian English in the Southeast Asian region

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [intianenglanti](http://finto.fi/yse/fi/page/Y509573)

**Comment by mariaforsen** [comment]
Sv. indisk engelska
