### ISSUE TITLE
sosiaalidemokraatit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9586]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sosiaalidemokraatit 

#### Ehdotettu termi ruotsiksi   

socialdemokrater 

#### Ehdotettu termi englanniksi   

social democrats 

#### Ehdotettu yläkäsite YSOssa (LT)   

[aatteelliseen ryhmään liittyvä rooli](http://www.yso.fi/onto/yso/p2741) 

#### Assosiatiiviset (RT)   

[sosiaalidemokratia](http://www.yso.fi/onto/yso/p15797) 
[työväenliike](http://www.yso.fi/onto/yso/p7821) 
[työväenliike](http://www.yso.fi/onto/yso/p7821) 

#### Perustelut ehdotukselle   

Paljon esiintyvä käsite kotimaisen poliittisen historian tutkimuksessa. Käsite kommunistit löytyy jo YSO:sta - olisi mielekästä, että käsite sosiaalidemokraatitkin löytyisi. Lisäksi termistä tapaa kahta kirjoitusmuotoa (sosialidemokraatit ja sosiaalidemokraatit), joista Kielitoimiston sanakirjan mukaan on käytettävä muotoa sosiaalidemokraatit. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/discovery/search?query=any,contains,Aatteesta%20ammatiksi%20-%20puoluety%C3%B6t%C3%A4%20ja%20punap%C3%A4%C3%A4omaa%20:%20Julius%20Nurmisen%20ja%20Anna%20Haverisen%20(ent.%20Nurminen)%20el%C3%A4m%C3%A4%20ja%20toiminta%20ty%C3%B6v%C3%A4enliikkeen%20j%C3%A4rjest%C3%B6aktiiveina%201900-luvun%20alkukymmenin%C3%A4%20~2F%20Pertti%20Nurminen.&tab=Everything&search_scope=MyInst_and_CI&vid=358UOH_INST:VU1&offset=0 

**Ehdottajan organisaatio:** Työväenliikkeen kirjasto **Termiehdotus Fintossa:** [sosiaalidemokraatit](http://finto.fi/yse/fi/page/Y509586)

**Comment by fantsby-m** [comment]
LT sosialistit

**Comment by AuHo22** [comment]
Aiemmin kuvattu mm. kansanedustajat + sosiaalidemokraattiset puolueet jne.

**Comment by ilona-x** [comment]
SAO: socialdemokrater https://id.kb.se/term/sao/Socialdemokrater

**Comment by AuHo22** [comment]
Kuinka kuvataan porvarillisten puolueiden edustajat?

**Comment by LeKorsu** [comment]
Hyvä kysymys @AuHo22
