### ISSUE TITLE
työolot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9587]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[työolot](http://www.yso.fi/onto/yso/p10899)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: työolosuhteet

**Perustelut ehdotukselle**

synonymi

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
Päätös: hyväksytään KT työolosuhteet
