### ISSUE TITLE
hallinto-oikeudet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9588]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hallinto-oikeudet](http://www.yso.fi/onto/yso/p10925)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tämä ja hallintotuomioistuimet yhdistettävissä?

**Perustelut ehdotukselle**

Miten eroavat toisistaan (muuten kuin nimitystasolla)? Ruotsiksi sama termi. Jos molemmat pitää olla erikseen, tarvitaan selkeämmät tarkenteet ruotsiksi. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://oikeus.fi/tuomioistuimet/fi/index/tuomioistuinlaitos/tuomioistuimet/hallintotuomioistuimet.html Voisiko siis yksi päätermi (hallintotuomioistuimet) riittää? Ks. myös Kielitoimiston sanakirja.

**Comment by ilona-x** [comment]
https://valter.sanakirja.fi/tuomioistuinsanasto/all/hallinto-oikeus
https://valter.sanakirja.fi/tuomioistuinsanasto/all/hallintotuomioistuin

**Comment by ilona-x** [comment]
EKS:

**Comment by ilona-x** [comment]
EKSissä molemmat erikseen, mutta lisäksi hallinto-oikeudet on KT-muuoto hallintotuomioistuimille. 🤔 

**Asiasana:	hallintotuomioistuimet**
Korvaa termin:	hallinto-oikeudet, lääninoikeudet

**Asiasana:	hallinto-oikeudet**

https://www.eduskunta.fi/kirjasto/EKS/

**Comment by mirmaid** [comment]
Eli ilmeisesti hallinto-oikeus on vain ensimmäisen  asteen (alueellinen) hallintotuomioistuin, mutta jälkimmäinen kattaa myös korkeimman hallinto-oikeuden, https://oikeus.fi/tuomioistuimet/fi/index/tuomioistuinlaitos/tuomioistuimet/hallintotuomioistuimet.html.

**Comment by YSO-kokous** [comment]
Poistetaan hallinto-oikeudet
Lisätään ohjaustermiksi hallinto-oikeudet KÄYTÄ hallintotuomioistuimet

**Comment by mirmaid** [comment]
On nyt seuraaja käsitteelle lääninoikeudet...
