### ISSUE TITLE
kolonisaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9589]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kolonisaatio

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

colonization 

**Tarkoitusta täsmentävä selite**

https://tieteentermipankki.fi/wiki/Alkuper%C3%A4iskansatutkimus:kolonisaatio

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [toiminta](http://www.yso.fi/onto/yso/p8090)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

 colonisation

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [kolonialismi](http://www.yso.fi/onto/yso/p3837)

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh85028571.html), [SAO](https://id.kb.se/term/sao/Kolonisation), [WIkipedia](https://fi.wikipedia.org/wiki/Kolonisaatio)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Written culture in a colonial context : Africa and the Americas 1500-1900

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kolonisaatio](http://finto.fi/yse/fi/page/Y509589)

**Comment by fantsby-m** [comment]
Tarkenne:
_kolonisaatio (kolonialismi)_

Jotta ei sekoiteta lääketiet. kolonisaatioon: https://www.terveyskirjasto.fi/ltt01696/kolonisaatio

**Comment by ilona-x** [comment]
https://tieteentermipankki.fi/wiki/Alkuper%C3%A4iskansatutkimus:kolonisaatio

muita merkityksiä:
https://termipankki.fi/tepa/fi/haku/kolonisaatio

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermiksi kolonisaatio KÄ kolonialismi
