### ISSUE TITLE
poni

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9590]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[poni](http://www.yso.fi/onto/ysa/Y105615) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Monikkoon, ei ole eläinlaji eikä rotu. 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by YSO-kokous** [comment]
Päätös: muutetaan monikkoon: ponit
