### ISSUE TITLE
nikkelimetallihydridiakut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9600]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

Nickel-metal hydride batteries 

#### Ehdotettu termi suomeksi   

nikkelimetallihydridiakut 

#### Ehdotettu termi ruotsiksi   

nickel-metallhydridbatterier 

#### Vaihtoehtoiset termit ja ilmaisut   

NiMH-akut 

#### Ehdotettu yläkäsite YSOssa (LT)   

[akut](http://www.yso.fi/onto/yso/p2306) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh93003489> 
Wikipedia : https://fi.wikipedia.org/wiki/Nikkelimetallihydridiakku 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[41 Sähkötekniikka. Elektroniikka](http://www.yso.fi/onto/yso/p26536) 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Complexities of hydrometallurgical recycling of spent NiMH and Li-ion batteries 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [nikkelimetallihydridiakut](http://finto.fi/yse/fi/page/Y509600)

**Comment by mariaforsen** [comment]
Sv. nickelmetallhydridbatterier HT NiMH-batterier, nickel-metallhydridbatterier, nickel-metallhydridackumulatorer, nickelmetallhydridackumulatorer
https://termipankki.fi/tepa/fi/haku/nimh-batteri
