### ISSUE TITLE
tuohikirjoitukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9602]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tuohikirjoitukset 

#### Ehdotettu termi ruotsiksi   

näverdokument 

#### Ehdotettu termi englanniksi   

Bark inscriptions 

#### Vaihtoehtoiset termit ja ilmaisut   

tuohikirjeet, näverbrev, Birch bark inscriptions 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaisjäännökset](http://www.yso.fi/onto/yso/p5340) 

#### Assosiatiiviset (RT)   

[käsikirjoitukset](http://www.yso.fi/onto/yso/p11009) 

#### Vastaava käsite muussa sanastossa   

LCSH : <https://id.loc.gov/search/?q=bark%20inscriptions&q=cs:http://id.loc.gov/authorities/subjects> 
SAO : https://id.kb.se/term/sao/N%C3%A4verbrev 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Perustelut ehdotukselle   

Melindassa 25 tietuetta, jossa käytetty tuohikirjoitukset-asiasanaa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1h3k2rg/alma9915417623506253 

#### Tarkoitusta täsmentävä selite   

https://en.wikipedia.org/wiki/Birch_bark_manuscript 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [tuohikirjoitukset](http://finto.fi/yse/fi/page/Y509602)

**Comment by mariaforsen** [comment]
Sv. näverbrev HT näverinskrifter, näverdokument
