### ISSUE TITLE
SLM/kaupunkiromaanit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9603]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

SLM/kaupunkiromaanit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

city novel

**Tarkoitusta täsmentävä selite**

Esim. tms. Kaupunkielämä ja sen kuvaus yleensä tietyn kaupungin paikalliskuvauksen kautta on vallitsevaa.

**Perustelut ehdotukselle**

Kaupunki voi olla kaunokirjallisuudessa yhtä vahvassa pääosassa kuin varsinaiset päähenkilöt.

**Ehdotettu yläkäsite YSOssa (LT)**

 [romaanit](http://www.yso.fi/onto/yso/p1896)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [maaseuturomaanit](http://www.yso.fi/onto/yso/p29701)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Rooman fuuga / Andreo Larsen 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [SLM/kaupunkiromaanit](http://finto.fi/yse/fi/page/Y509603)

**Comment by AuHo22** [comment]
https://www.themodernnovel.org/my-lists/city/

These are not simply novels set in a city (though, of course, they are set in a city) but novels where a city plays a key role and, indeed, is often a, if not the main, character in the novel.

**Comment by mirmaid** [comment]
Maaseuturomaanit: muutetaan huomautus: Käytetään teoksista, jotka kuvaavat maaseutua ja maanviljelijöiden elämää. > kuvaavat maaseutua ja maalaiselämää.

**Comment by mirmaid** [comment]
KAUNO-ryhmä laatii määritelmän.

**Comment by mirmaid** [comment]
KAUNO-ryhmä: Käytetään teoksista, joissa todellisella tai fiktiivisellä kaupungilla on tarinan kannalta merkittävä rooli.

**Comment by mirmaid** [comment]
Käytetään romaaneista, joissa todellisella tai fiktiivisellä kaupungilla on merkittävä rooli.

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Sv. stadsromaner HT stadsskildringar (romaner)
