### ISSUE TITLE
hautakummut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9604]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

hautakummut 

#### Ehdotettu termi ruotsiksi   

gravhögar 

#### Ehdotettu termi englanniksi   

mounds 

#### Vaihtoehtoiset termit ja ilmaisut   

tumulus, tumuli, burial mounds, barrows, kumpuhaudat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaishaudat](http://www.yso.fi/onto/yso/p5714) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh85087721.html 
SAO : https://id.kb.se/term/sao/Gravh%C3%B6gar 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Tarkoitusta täsmentävä selite   

arkeologisen kulttuuriperinnön opas
http://akp.nba.fi/wiki;hautakumpu?s[]=hautakummut 

#### Perustelut ehdotukselle   

Aihehaku mounds tuottaaa Melindassa 51 tulosta 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1h3k2rg/alma9933667318206253 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [hautakummut](http://finto.fi/yse/fi/page/Y509604)

**Comment by fantsby-m** [comment]
On MAO/TAOssa

**Comment by mariaforsen** [comment]
Sv. gravhögar HT gravkullar
