### ISSUE TITLE
Samis

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9605]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Samis](http://www.yso.fi/onto/yso/p11537)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö englanninkielisten termien ohjaustermiksi lisätä myös pidempi muoto 'saami'. Koskisi kaikkia termejä Samis, Sami Identitty, Sami culture jne.

**Perustelut ehdotukselle**

https://en.wikipedia.org/wiki/S%C3%A1mi_people ja http://www.sarks.fi/masf/masf_9/masf_9.html

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
Näkyy pitkässä muodossa siellä täällä. Esim. https://en.wikipedia.org/wiki/Saami_Council  esim. "...and to helping the **Saamis** safeguard their traditions, "  sekä  http://www.suri.ee/eup/samis.html
