### ISSUE TITLE
ehkäisymenetelmät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9627]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[ehkäisymenetelmät](http://www.yso.fi/onto/ysa/Y94946) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan LT-suhde joksikin toiseksi tai jaetaan asiasana kahtia (erikseen "ehkäisymenetelmät" ja "ehkäisyvälineet") 

#### Perustelut ehdotukselle   

Tällä hetkellä "ehkäisymenetelmät"-asiasanan suppeampina termeinä on yksinomaan ehkäisyvälineitä, jotka eivät hierarkkisesti kuulu asiasanan "menetelmät" vaan "välineet" alle. Varmat päivät ja keskeytetty yhdyntä toki eivät ole välineitä, mutta niitä ei YSO:ssa ole. (https://www.ehkaisynetti.fi/ehkaisymenetelmat) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Jos jako tarvitaan, niin vaihdetaan päätermiksi ehkäisyvälineet ja siirretään ehkäisymenetelmät raskauden ehkäisyn ohjaustermiksi. Meshissä nämä ovat molemmat raskauden ehkäisyn ohjaustermejä.  Samoin wikidatassa hierarkia on hankala.
Vastaavat LCSH käsitteet olisivat:
- [Contraception](http://id.loc.gov/authorities/subjects/sh85031589) --- YSO: [raskauden ehkäisy](http://www.yso.fi/onto/yso/p2237) KT ehkäisymenetelmät  
- [Contraceptives](http://id.loc.gov/authorities/subjects/sh85031597) --- ehkäisyvälineet  YK välneet RT raskauden ehkäisy

**Comment by satuniininen** [comment]
Kannatan mieluummin hierarkian korjausta kuin käsitteen jakamista. YSOssa on jo _sterilointi (lääketieteellinen toimenpide)_ RT _ehkäisymenetelmät_, joten muutkin ehkäisymenetelmien alakäsitteet voisi muuttaa assosiatiivisiksi käsitteiksi, En haluaisi päätyä tilanteeseen, jossa kuvailuun joutuu säännönmukaisesti lisämään sekä _ehkäisymenetelmät_ että _ehkäisyvälineet_.

**Comment by YSO-kokous** [comment]
Päätös: Tehdään Sadun ehdotuksen mukaan.
