### ISSUE TITLE
kuvateokset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9630]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuvateokset](http://www.yso.fi/onto/yso/p2599)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

SLM: Lisätään huomautus myös SLM:n puolella? Ja/tai muu tarkennus suhteessa kuvakirjoihin 

**Perustelut ehdotukselle**

Epäselvää milloin pitäisi käyttää kuvakirjat ja milloin kuvateokset (genretermeinä). Vrt. huomautukset YSOssa ja SLM:ssä. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Onko mahdollista rajata kuvakirjat > lasten kuvakirjat? Sv. bilderböcker on ensisijaisesti lastenkirjoja. Ja näin myös Tieteen termipankissa: https://termipankki.fi/tepa/fi/haku/kuvakirja YSOssa termi rajautuu myös englannin osalta lastenkirjallisuuteen. Tällä tavalla saataisiin käytäntö selkeäksi ja johdonmukaiseksi. Voitaisiin myös siirtää kuvakirjojen huomautus "Käytetään kirjoista, jotka perustuvat yhtä paljon tai enemmän kuvaan kuin tekstiin." kuvateokset-termille, kuten YSOssa on.

**Comment by jtuohini** [comment]
SLM:n puolella ongelman pitäisi ratketa muuttamalla nykyinen RT lastenkirjallisuus --> LT lastenkirjallisuus. Silloin olisi selvää, että kyse on lastenaineistosta.

**Comment by AuHo22** [comment]
Keskustelun jälkeen huomattiin ettei rajaus pelkkään lastenaineistoon toimi, esim. 978-952-68765-2-8 https://holvi.com/shop/illustratoremmi/product/6ae495e3713e2acd32b8b76f43451b98/
tai 978-952-94-2902-8 
https://www.katinarhi.com/shop/ei-mikn
ja 978-1-78689-948-4 
Määritelmät kuvakirjat/runokuvakirjat/kuvateokset sanastoissa (myös Kauno) -> yhtenä erottavana piirteenä kaunokirjallinen teos vs.  tietoaineisto

**Comment by mirmaid** [comment]
Lisätään käyttöhuomautus: Käytetään lastenkirjoista ja tyyliltään lastenkirjaa muistuttavista kirjoista.

**Comment by mirmaid** [comment]
Koska tässä oli jo huomautus, muokkasin sitä seuraavasti: _Käytetään lastenkirjoista ja tyyliltään lastenkirjaa muistuttavista kirjoista, jotka perustuvat yhtä paljon tai enemmän kuvaan kuin tekstiin_.

**Comment by mirmaid** [comment]
Ehdotettu, että myös kuvateoksille lisättäisiin määritelmä. (SLM-kokous)

**Comment by AuHo22** [comment]
Kielitoimiston sanakirja: kuvateos = runsaasti t. pääasiassa kuvia sisältävä kirja.
Kuvateos avaruuden valloituksesta.

**Comment by jtuohini** [comment]
Olisiko sitten aiemmassa keskustelussa tietoaineistoisuus huomioiden **kuvateokset**-termin selityksenä "Runsaasti tai pääasiassa kuvia sisältävä tietokirja"? Mainittua termiähän ei kaiketikaan ole käytetty kuvareportaasien yhteydessä, vaan nimenomaan kirjoista.

**Comment by mariaforsen** [comment]
Ei tämä termi ainakaan ruotsiksi rajaudu tietoaineistoon, eikä taida olla niin Melindassakaan (yli 7000 kertaa). Toivon että olennaista määritelmässä olisi kuvien tyyppi (valokuva?) ja määrä, mieluummin kuin että onko kirja kauno- vai tietoaineisto (nykyään ei myöskään aina ole mahdollista sanoa tarkkaan että olisi vain joko tai..)

SAO: "Denna term används som genre/formterm för verk som helt eller huvudsakligen består av stillbilder. Används också för verk där stillbildernas syfte är att förklara, förstärka eller utsmycka text eller annat innehåll. (LCGFT)"

**Comment by AuHo22** [comment]
Viimeksi taisi olla puhetta - runokuvakirjamääritelmän yhteydessä - "Käytetään kuvakirjoista, joissa runot muodostavat yhtenäisen tarinan tai runo ja kuva ei toimi ilman vuorovaikutussuhdetta." 
So. kuvateokset ja runot -> on käytetty esim. valokuvateoksissa (tai myös maalauksia, akvarelleja), joissa on sitten myös runoja (yleensä yksittäisiä), usein uskontoaiheisia tai sitten voi olla luontoaiheisia.
Näissä on sitten myös luokitus osoittamassa sen, että teoksessa on ikäänkuin 2 näkökulmaa, esim. 978-951-52-5842-7

**Comment by mirmaid** [comment]
Lisätään kuvakirjoille ja kuvateoksille RT-suhde molemmissa sanastoissa, sekä muotoillaan käyttöhuomautus toisesta vaihtoehdoista (kuvakirjat-puolelle tyyliä "muista...").

**Comment by mirmaid** [comment]
Pitäisikö runokuvakirjan YK olla kuvateokset, eikä kuvakirjat, jos kuvakirja on aina lastenkirja tai lastenkirjaa muistuttava?

**Comment by AuHo22** [comment]
Ei määritelmän mukaan: -> 
Käytetään kuvakirjoista, joissa runot muodostavat yhtenäisen tarinan tai runo ja kuva eivät toimi ilman vuorovaikutussuhdetta.

**Comment by mirmaid** [comment]
^ Tarkoitin siis, että kun tuossa ei sanota, että runokuvakirja olisi välttämättä lastenkirja tai sellaista muistuttava, niin silloin tuntuu epäloogiselta että yläkäsite voisi olla kuvakirjat.

**Comment by AuHo22** [comment]
Nykyiset YK:t ovat mielestäni ok, kuvateokset ja runot ovat sitten jo vähän eri asia, eli kyse ei ole kuvan ja runon vuorovaikutuksesta samalla tavalla.

**Comment by mirmaid** [comment]
Tämä issue on siis muilta osin valmis, mutta itse näen, että **runokuvakirjat**-käsitteen yläkäsite pitäisi olla _kuvateokset_, eikä _kuvakirjat_, koska jälkimmäinen on määritelty lastenkirjoiksi tai tyyliltään lastenkirjaa muistuttaviksi. Runokuvakirjat taas voivat kai olla tyyliltään täysin aikuisten kirjoja, joten tuntuisi ristiriitaiselta, että niiden yläkäsitteenä olisi lastenkirjaksi rajattu käsite.

Jos tämä ratkaisu tuntuu huonolta, voisi ratkaista myös niin, että kumpikaan mainituista ei ole yläkäsite, vaan näillä on vain RT-suhde toisiinsa.

**Comment by AuHo22** [comment]
_runokuvakirjat-käsitteen yläkäsite pitäisi olla kuvateokset_ <- tämä ei joka tapauksessa toimi
**runokuvakirja**: -> Käytetään kuvakirjoista, joissa runot muodostavat yhtenäisen tarinan tai runo ja kuva eivät toimi ilman vuorovaikutussuhdetta.
vrt. **kuvateokset ja runot** -> on käytetty esim. valokuvateoksissa (tai myös maalauksia, akvarelleja yksittäisinä kuvina), joissa on sitten myös runoja (myös  yksittäisiä eikä yhtenäistä tarinaa ole), usein uskontoaiheisia tai sitten voi olla luontoaiheisia -> ja näissä tapauksissa kuvat ja runot voidaan irrottaa toisistaan omiksi kokonaisuuksikseen
**kuvakirjat** myös yleensä sisältävät tarinan, joissa teksti ja kuva ovat vuorovaikutuksessa eivätkä enää toimi erikseen toisistaan

**Comment by mariaforsen** [comment]
Kannatan RT-suhdetta siinä tapauksessa.

**Comment by mirmaid** [comment]
Kuvateokset-termin käyttöhuomautus (myös yso): Käytä termiä kuvakirjat lastenkirjoista ja tyyliltään lastenkirjaa muistuttavista kirjoista, jotka perustuvat yhtä paljon tai enemmän kuvaan kuin tekstiin.

Runokuvakirjat: jää nykyiseen paikkaansa.
