### ISSUE TITLE
avopuolisot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9631]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[avopuolisot](http://www.yso.fi/onto/yso/p14031)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko avoparit ja avopuolisot yhdistettävissä?

**Perustelut ehdotukselle**

Päällekkäisiä. Sen lisäksi sanastossa on myös puolisot.

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
YSOssa on erikseen [avioparit ](http://www.yso.fi/onto/yso/p25211)- [aviopuolisot](http://www.yso.fi/onto/yso/p10868),  sekä  [avoparit ](http://www.yso.fi/onto/yso/p25384)- [avopuolisot](http://www.yso.fi/onto/yso/p14031).  Liittyvät parisuhteeseen.  Ovat eri käsitteitä tonen käsittelee molempia yhdessä, toinen parisuhteen osapuolta erikseen. Ei liene tarpeen yhdistää.

[puolisot](http://www.yso.fi/onto/yso/p24273) -käsite liittyy sukulaisuussuhteisiin

**Comment by mariaforsen** [comment]
Ruotsin kannalta nämä ovat päällekkäisiä. Ja näin taitaa olla myös eng.:  cohabiting couples ja cohabiting partners

**Comment by mirmaid** [comment]
Kuten Jarmo kirjoittaakin, suomeksi siis "parit" = molemmat osapuolet, "puolisot" = jompi kumpi. Aineisto voisi käsitellä esim. avopuolison asemaa eron jälkeen omaisuudenjakotilanteessa, tai avoparin asemaa asuntolainan hakijana. Eri asia toki, miten tarkkaan erottelu on hyödyllistä käytännössä, mutta sama koskee sitten aviopareja/-puolisoita.

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään ongelmakokoukseen. Tutkitaan _avioparit_, _avoparit_, _aviopuolisot_, _avopuolisot_ ja _puolisot_ -käsitteiden käyttöä.

**Comment by mariaforsen** [comment]
Sv. nyt:

sambor (personer) fi. avopuolisot  -Melindassa 84
sambopar fi. avoparit  -Melindassa 8

gifta par fi. avioparit -Melindassa 322
makar fi. aviopuolisot -Melindassa 2451

partner (stadigvarande parförhållande) fi. puolisot -Melindassa 558

**Comment by AuHo22** [comment]
Itse en lakiasioitten näkökulmasta erojen kohdalla välttämättä oikein löytänyt tarvetta sekä avio/avoparit sekä avio/avopuolisot -termipareille, mutta huomasin että pariskunnat (vain Kauno-termi nykyisin) vilahti siellä sun täällä mm. pankkiasioitten yhteydessä:

https://yle.fi/a/74-20013139
https://www.op-media.fi/asunnon-osto/asunnon-ostaminen-avoparina--miten-toimia/

Voisiko siis olla avoparit / avioparit KÄYTÄ pariskunnat?

Sen lisäksi meillä on avoliitto/avioliitto -termit tietyntyyppisinä yhteiselämän muotoina olemassa (ja tietenkin nuo aviopuolisot/avopuolisot -termit.

Kotimaisten kielten sanakirja:
_pariskunta -> parisuhteessa keskenään olevat henkilöt
Lapseton pariskunta.
Oliko pöydässämme istunut pariskunta aviopari?_

**Comment by mirmaid** [comment]
Heti tässä ensimmäisessä avoparit-viitteessä avopuolisot tuntuisi oudolta: https://melinda.kansalliskirjasto.fi/byid/018708416. Mutta olisi toki korvattavissa > avoliitto, avioliitto. Tai entä tämä: https://melinda.kansalliskirjasto.fi/byid/017415587?

**Comment by AuHo22** [comment]
Edellisessä toimisi varmaankin lapsiperheet/uusperheet + avoliitto/avioliitto

Sitten taidettiin juuri ottaa se työparit-termi sanastoon, jota jälkimmäisessä voisi käyttää, tässä taidetaan kuvata ainakin kustantajan mukaan yhtä hyvin rakkaus/parisuhdetta, jota voisi käyttää myös (tai pariskunnat-termiä). 
https://johanerlandsson.com/boken-om-beck/

Sitä mietin, että onko nykyihmisen kannalta olennaista tehdä erottelua avopari/aviopari-statuksen suhteen, itselläni se ainakin herättää vain lisäkysymyksiä. Sen lisäksi olen joskus miettinyt, kun on teoksia presidenttien puolisoista, niin ovatko he puolisoita vai aviopuolisoita, en ole päässyt täyteen ymmärrykseen, mutta näköjään käytetympi muoto on aviopuolisot-termi sitten, eli sitä olen käyttänyt.

**Comment by LeKorsu** [comment]
> Itse en lakiasioitten näkökulmasta erojen kohdalla välttämättä oikein löytänyt tarvetta sekä avio/avoparit sekä avio/avopuolisot -termipareille, mutta huomasin että pariskunnat (vain Kauno-termi nykyisin) vilahti siellä sun täällä mm. pankkiasioitten yhteydessä:
> 
> https://yle.fi/a/74-20013139 https://www.op-media.fi/asunnon-osto/asunnon-ostaminen-avoparina--miten-toimia/
> 
> Voisiko siis olla avoparit / avioparit KÄYTÄ pariskunnat?
> 
Minä nostaisin ainakin vienohkosti peukkua tälle Aulin ehdotukselle avo/avioparien korvaamista pariskunnalla.

**Comment by mirmaid** [comment]
^^ Halutaanko edelleen säilyttää sekä puolisot, että suppeammat, vai tehdä avio-/avopuolisoista ohjaustermejä? Sanastossa on muuten vielä _aviomiehet_ ja _aviovaimot_.

**Comment by LeKorsu** [comment]
Niin kauan kuin esim. lainsäädännössä on merkitystä sillä, oletko avopuoliso vai aviopuoliso, säilyttäisin molemmat. Aviomiehet ja aviovaimot olisin valmis yhdistämään aviopuolisoihin.

**Comment by ilona-x** [comment]
Tässä muiden sanastojen termitarjontaa. (Voi olla, että jotain termejä jäi huomaamatta💦) 

LCSH:
Unmarried couples
Spouses
Husbands
Wives
Married people
Married women
Married men

SAO:
Makar
Hustrur 
Gifta kvinnor 
Äkta män

**Comment by mariaforsen** [comment]
Koska juridisesti sillä on suurikin merkitys onko avo- vai aviopuoliso niin ei tietenkään voi poistaa sitä eroa sanastosta. Kyse on kai lähinnä siitä että voisiko poistaa jotain päällekkäisyyksiä, esim. **puolisot** on hämärämerkityksinen termi ja päällekkäinen useamman muun termin kanssa, ja se että on sekä **avopuolisot** että **avoparit**, ja **aviopuolisot** että **avioparit** on mielestäni kummallista (näin ainakin ruotsin kannalta).

**Comment by ilona-x** [comment]
Puolisot on ollut välillä ihan hyödyllinen termi, jos aineistosta ei selvästi mainita, onko kyseessä avo- vai aviopuoliso. Esimerkiksi puolison sairastumista käsittelevissä muistelmissa ei välttämättä tule ilmi, onko kyse avo- vai aviopuolisosta, mutta kuvailu jäisi vajaaksi, jos ei voisi näissä tilanteissa käyttää puolisot-termiä. 🤔

**Comment by mirmaid** [comment]
Jonkin verran puoltoa aviomiehet ja aviovaimot -termien poistolle, mutta en lähtisi tähän tutkimatta ensin viitteitä, varsinkin kun se ei taida ratkaista alkuperäistä ongelmaa mitenkään. 

Aviopuolisot ja avioparit -käsitteillä on kai ihan selkeät ruotsinkieliset vastineet, ja tarve yhdistämiselle lähtee lähinnä siitä, että sambor voi viitata sekä henkilöihin yksilöinä että yhdessä pariskuntana. Joissakin (lähinnä lakiasioihin liittyvissä) Google-hiteissä näkyi termiä _sambopartner_, mutta en tiedä onko siitä nyt mitään iloa (onko esim. person parempi tarkenne kuin partner?)...

Pariskunnat-käsitteen lisäämistä avio- ja avoparien tilalle on ehdotettu. Mikähän se olisi ruotsiksi? Toisaalta on vastustettu avio- ja avopuolisoiden poistoa (neutraali puolisot on jo), joten eikö tähän muutokseen päde sama?

Sitä mietin myös, onko tuo makar varmasti juuri **avio**puoliso? Sanakirja jättää tässä vähän tulkinnanvaraa. Puoliso-termin ruotsivastineen tarkenne epäilemättä aiheuttaa harmia.

**Comment by krinay** [comment]
Pitäisikö myös termien välisiä suhteita tarkistaa, jotta kaikki tarjolla olevat termit tulisivat helpommin esille. Nyt:

sukulaiset ST omaiset (ja muita)
omaiset ST perheenjäsenet, puolisot (ja muita) 
perheenjäsenet ST avopuolisot, aviopuolisot (ja muita)
(hierarkiasta johtuen käsitteellä _puolisot_ ei siis ole assosiatiivista tai muuta suoraa suhdetta avo- ja aviopuolisoihin)

avoparit- ja avioparit-termeillä ei ole muita termisuhteita kuin assosiatiivinen suhde toisiinsa ja molemmilla hierarkisoiva yläkäsite _sukulaisuuteen liittyvä rooli_  (kuten myös käsitteellä sukulaiset)

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutosta. Erilaisia vaihtoehtoja käsiteltiin perusteellisesti.
