### ISSUE TITLE
St Michel

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9634]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

St Michel 

#### Perustelut ehdotukselle   

Kantoon vai YSOon? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

St Michel : vauhtijuhlan vuodet 1981-2020 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [St Michel](http://finto.fi/yse/fi/page/Y509634)

**Comment by jarmosaarikko** [comment]
Kyseessä on vuosittainen kansainvälinen ravikilpailu. "_Kansainvälinen St Michel -ajo järjestetään vuosittain heinäkuun puolivälissä._ "
Kantossa ei liene ravikisoja? YSOssa on kolme hevosurheilun urheilukilpailua, joista yksi on raviurheilua.
Ehdotettu termi on jo varattu Mikkelin kaupugille. (S:t Michel)
verkkosivut: https://www.stmichel.fi/
- Jos päätetään ottaa sanastoon, ehdotan termiksi "St MIchel -ajot" tai "St Michel (raviurheilu)"
- Ruotsiksi "St Michel-loppet"  https://sv.wikipedia.org/wiki/St._Michel-loppet
- Englanniksi "St Michel Harness Race"  Lähde https://www.visitmikkeli.fi/en/palvelut/mikkeli-trotting-track
YK urheilukilpailut  RT raviurheilu

**Comment by jtuohini** [comment]
Kyseessä nimetty hevosurheiluTAPAHTUMA, joten oikea paikka on Kanto. Yksittäinen tapahtuman hakutieto kuitenkin sisältää myös vuoden ja paikan, joten YSO-auktoriteetin kiinnittäminen sellaiseen ei onnistu.

**Comment by fantsby-m** [comment]
Tai "St Michel -ravit".

**Comment by mirmaid** [comment]
KANTOssa.
