### ISSUE TITLE
napatyrä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9635]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

napatyrä

**Ehdotettu termi ruotsiksi**

navelbråck

**Ehdotettu termi englanniksi**

Umbilical hernia

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Melko yleinen sairaus

**Ehdotettu yläkäsite YSOssa (LT)**

 [tyrät](http://www.yso.fi/onto/yso/p21990)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Napatyr%C3%A4), [Wikipedia](https://en.wikipedia.org/wiki/Umbilical_hernia)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.terveyskirjasto.fi/dlk00089

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [napatyrä](http://finto.fi/yse/fi/page/Y509635)

**Comment by jarmosaarikko** [comment]
Onko sama vai eri kuin #9336 napanuoratyrä   
- https://www.terveyskirjasto.fi/orp01483/omfaloseele-l-napanuoratyra-orphanet?q=omfaloseele

- LCSH http://id.loc.gov/authorities/subjects/sh85139526 Navel--Hernia, Exomphalos, Omphalocele
- Mesh http://www.yso.fi/onto/mesh/D006554  Umbilical Hernia,   Hernia umbilicalis

**Comment by mirmaid** [comment]
https://www.terveyskirjasto.fi/dlk00532/tyrat-lapsella?q=napatyr%C3%A4
https://www.terveyskirjasto.fi/orp01483

Napanuoratyrä on isompi epämuodostuma, napatyrä yleensä itsestään korjautuva.
