### ISSUE TITLE
taidemusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9636]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[taidemusiikki](http://www.yso.fi/onto/ysa/Y99237) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä siirretään seuraavat "musiikki"-termin alla olevat "taidemusiikin" alle:
- "canzonat"
- "duetot"
- "duot"
- "elegiat (musiikki)"
- "intermediot"
- "kvartetot"
- "kvintetot"
- "monikuoroinen musiikki" (?)
- "nonetot"
- "oktetot"
- "parafraasit (musiikki)" (?)
- "pastissit" (?)
- "sekstetot"
- "septetot"
- "soolosävellykset" (?)
- "tonadillat"
- "triot"
- "versetit"
- "välisoitot" 

#### Perustelut ehdotukselle   

Nämä jääneet edellisessä isossa siirrossa väliin. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by JohPa** [comment]
Toivottavasti jatkossakin voidaan käyttää esim. duot ja triot ym. -termejä ilmaisemaan esittäjien kokonaismäärä nuottien kuvailussa genrevapaasti, vaikka termit siirrettäisiinkin taidemusiikin alle? Tarvetta kokoonpanon ilmaisemiseen on myös mm. jazzissa ja populaarimusiikissa. Muusa on hyväksynyt termien käytön esityskokoonpanoa kuvaamaan niin kauan kuin 382-kentän laskurien varaan ei voida laskea tiedonhaussa. Ei kai käyttöä olla rajaamassa nyt pelkkään taidemusiikkiin?

**Comment by MUUSA-kokous** [comment]
Kannatetaan muiden termien paitsi seuraavien osalta:
duetot
duot
kvartetot
kvintetot
nonetot
oktetot
pastissit
sekstetot
septetot
soolosävellykset
triot
