### ISSUE TITLE
Röysö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9637]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Röysö 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Röysöarkipelagen 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [Röysö](http://finto.fi/yse/fi/page/Y509637)

**Comment by jarmosaarikko** [comment]
Onko kyseessä tämä? http://paikkatiedot.fi/so/1000772/10343239 - saari tai luoto  Sipoossa
https://www.wikidata.org/wiki/Q24315572
