### ISSUE TITLE
Pyhän Kolminaisuuden luostari

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9638]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Pyhän Kolminaisuuden luostari](http://www.yso.fi/onto/yso/p17427)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kaipaisin tarkennusta sille, mitä luostaria tällä tarkoitetaan, suluissa maantieteellinen paikka? 

**Perustelut ehdotukselle**

https://fi.wikipedia.org/wiki/Pyh%C3%A4n_Kolminaisuuden_luostari / YSOssa myös Aleksanteri Syväriläisen luostari, onko sama asia? Itse kaipasin seuraavaa, esim. artikkelissa: --hän päätti pyrkiä Moskovan alueella sijaitsevaan Pyhän Kolminaisuuden luostariin (Troitse-Sergieva Lavra), jonne hänet hyväksyttiin noviisiksi vuonna 1992-- mutta en uskaltanut käyttää mitään https://aamunkoitto.fi/maailmalta/laatokan-valamon-kavijoille-tuttu-arkkimandriitta-mefodi-menehtyi-koronaan-lue-isa / teos 9789525495713

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by jarmosaarikko** [comment]
Tuo Moskovan alueen luostari lienee Wikipediassa tämä:
- https://fi.wikipedia.org/wiki/Troitse-Sergijevin_luostari myös nimellä "Pyhän Kolminaisuuden ja Pyhän Sergein lavra"
- https://en.wikipedia.org/wiki/Trinity_Lavra_of_St._Sergius 
- https://www.wikidata.org/wiki/Q211962 "Troitse-Sergijevin luostari" 

Kongressin kirjastossa tämä on määritelty toimijaksi (LCNAF):
- http://id.loc.gov/authorities/names/n82165215 - "**Troit︠s︡e-Sergieva lavra**"

**Comment by mariaforsen** [comment]
Myös luostari esim. Ruotsissa.

**Comment by mirmaid** [comment]
https://www.primatours.fi/aleksanteri-syvarilaisen-luostari-2

Vaihdetaan tämän luostarin nimi ja lisätään Aleksanteri Syväriläisen luostarille ohjaustermi paikkatarkenteella.

**Comment by YSO-kokous** [comment]
Vaihdetaan ohjaustermi päätermiksi.
Pyhän Kolminaisuuden luostari (Leningradin alue)  KÄ Aleksanteri Syväriläisen luostari
