### ISSUE TITLE
maakuntavaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#964]
#### Ehdotettu termi suomeksi

maakuntavaalit
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/ysa/ryhma_62)
[71 Hallinto. Organisaatiotutkimus. Julkinen hallinto](http://www.yso.fi/onto/ysa/ryhma_71)

**Luontipäivämäärä:** 17.10.2003

**Muokkauspäivämäärä:** 17.10.2003, 21.10.2003, 16.12.2008

**Voyager-id:** 127636

**Termiehdotus Fintossa:** [maakuntavaalit](http://finto.fi/yse/fi/page/Y327636)

**Comment by ilona-x** [comment]
Tätä olisi voinut käyttää teoksen Kansalaismielipide ja kunnat : ilmapuntari 2016 kuvailussa.
https://fi.wikipedia.org/wiki/Maakuntavaalit

**Comment by vthuhtala** [comment]
Pitäisikö kuitenkin odottaa lainsäädännön läpimenoa?

**Comment by mariaforsen** [comment]
Sv. landskapsval
