### ISSUE TITLE
dialektinen teologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9640]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

dialektinen teologia 

#### Ehdotettu termi englanniksi   

dialectical theology 

#### Ehdotettu yläkäsite YSOssa (LT)   

[teologia](http://www.yso.fi/onto/yso/p3830) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Ei löydy sopivaa YSO-vastinetta vanhastaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/002543496 ja noin sata muuta 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [dialektinen teologia](http://finto.fi/yse/fi/page/Y509640)

**Comment by mariaforsen** [comment]
Sv. dialektisk teologi. Myös SAOssa https://id.kb.se/term/sao/Dialektisk%20teologi ja LCSH https://id.loc.gov/authorities/subjects/sh85037525.html

**Comment by mirmaid** [comment]
Näissä käytetty myös _dialektiikka_-käsitettä (?).

https://en.wikipedia.org/wiki/Neo-orthodoxy

**Comment by ilona-x** [comment]
Teologian sanakirjassa: http://sanakirja.teol.helsinki.fi/#/sanat/dialektinen%20teologia
