### ISSUE TITLE
Q-teoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9641]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Q-teoria 

#### Ehdotettu termi englanniksi   

Q hypothesis 

#### Vaihtoehtoiset termit ja ilmaisut   

Logia-lähde 
Q-lähde 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85109386 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/011455505 ja yli 150 muuta 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Q-teoria](http://finto.fi/yse/fi/page/Y509641)

**Comment by mariaforsen** [comment]
Sv. Q-källan. Myös SAOssa https://id.kb.se/term/sao/Q-k%C3%A4llan
https://sv.wikipedia.org/wiki/Q-k%C3%A4llan
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/q-k%C3%A4llan

https://fi.wikipedia.org/wiki/Q-l%C3%A4hde
https://en.wikipedia.org/wiki/Q_source

**Comment by AuHo22** [comment]
Q hypothesis (Synoptics criticism)
https://id.loc.gov/authorities/subjects/sh85109386.html

**Comment by mirmaid** [comment]
_Q-teoria_ vaatii tarkenteen (esim. "eksegetiikka"), muodossa _Q-lähde_ varmaan sellaisenaan yksiselitteinen, mutta olisiko se oikeastaan teos?

**Comment by mariaforsen** [comment]
Q-lähde on teoria, ei teos.

**Comment by mirmaid** [comment]
^ Mielestäni wikipediassa käytettiin viittaamaan kirjalliseen dokumenttiin, jota Matteuksen ja Luukkaan evankeliumien kirjoittajat ovat käyttäneet, eli kadonnut teos. Siksi tuo teoria-muoto tuntuisi paremmalta ja sille olisi myös hyvä paikka ontologiassa.

**Comment by YSO-kokous** [comment]
Hyväksytään. Mietitään vielä parhaiten soveltuva päätermi.
Logia-lähde (päätermi ttka:ssa), Q-tutkimus, Q-teoria, Q-lähde.

**Comment by mariaforsen** [comment]
Sv. Q-källan HT Logiakällan, talkällan
