### ISSUE TITLE
venehautaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9643]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

venehautaus 

#### Ehdotettu termi ruotsiksi   

Båtgravar 

#### Ehdotettu termi englanniksi   

Ship burials 

#### Vaihtoehtoiset termit ja ilmaisut   

venehaudat 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hautaustavat](http://www.yso.fi/onto/yso/p26069) 

#### Assosiatiiviset (RT)   

[hauta-antimet](http://www.yso.fi/onto/yso/p29572) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh85121528.html 
SAO : https://id.kb.se/term/sao/B%C3%A5tgravar 
wikipedia : https://fi.wikipedia.org/wiki/Venehautaus#Suomi_ja_Viro 
wikipedia : https://en.wikipedia.org/wiki/Ship_burial 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1h3k2rg/alma9931715403506253 

#### Tarkoitusta täsmentävä selite   

A ship burial or boat grave is a burial in which a ship or boat is used either as the tomb for the dead and the grave goods, or as a part of the grave goods itself. If the ship is very small, it is called a boat grave. (wikipedia) 

#### Perustelut ehdotukselle   

Melindassa venehaudat 8 kpl, ship burials 12 kpl, venepolttohautaus 3 kpl (mao-ontologian kapeampi käsite) 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [venehautaus](http://finto.fi/yse/fi/page/Y509643)

**Comment by mariaforsen** [comment]
Tai mahdollisesti båtbegravning (hautaus vs. haudat)?

**Comment by mirmaid** [comment]
_Venehaudat_ sopisi _muinaishautojen_ alakäsitteeksi.

**Comment by AuHo22** [comment]
Itselläni sekoittui - varsinkin venehaudat - ensin laivalatomuksiin (kuten Gotlannissa) - onko sekaantumisen vaaraa?
https://fi.wikipedia.org/wiki/Laivalatomus

**Comment by mirmaid** [comment]
^ _Laivalatomukset_ voisi olla myös sanastossa? On MAOssa.

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Skeppss%C3%A4ttning

**Comment by YSO-kokous** [comment]
Otetaan sanastoon sekä vehehaudat että laivalatomukset

**Comment by mariaforsen** [comment]
Sv. 
-båtgravar
-skeppssättningar HT stenskepp
