### ISSUE TITLE
redaktiokritiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9645]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

redaktiokritiikki 

#### Ehdotettu termi englanniksi   

Biblical redaction criticism 

#### Ehdotettu termi ruotsiksi   

redaktionskritik 

#### Ehdotettu yläkäsite YSOssa (LT)   

[eksegetiikka](http://www.yso.fi/onto/yso/p9983) 
[tutkimusmenetelmät](http://www.yso.fi/onto/yso/p415) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85013630> 
Wikidata : https://www.wikidata.org/wiki/Q496434 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/007318181 ja vajaa 50 muuta 

#### Perustelut ehdotukselle   

. . 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [redaktiokritiikki](http://finto.fi/yse/fi/page/Y509645)

**Comment by mirmaid** [comment]
N. 40 viitettä Melindassa.
https://fi.wikipedia.org/wiki/Redaktiokritiikki

https://tieteentermipankki.fi/wiki/Nimitys:redaktiokritiikki - onko laajemminkin käytettävissä? Tässä rajoittuu kyllä Raamattuun: https://en.wikipedia.org/wiki/Redaction_criticism.

**Comment by YSO-kokous** [comment]
Hyväksytään: redaktiokritiikki (ekseketiikka)

**Comment by mariaforsen** [comment]
Sv. redaktionskritik (exegetik)
