### ISSUE TITLE
rukoushetket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9646]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

rukoushetket 

#### Ehdotettu termi ruotsiksi   

bönestunder 

#### Ehdotettu termi englanniksi   

prayer meetings 

#### Ehdotettu yläkäsite YSOssa (LT)   

[hartaustilaisuudet](http://www.yso.fi/onto/yso/p19140) 

#### Assosiatiiviset (RT)   

[jumalanpalvelus](http://www.yso.fi/onto/yso/p15215) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85106137> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

. . 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/014351629 ja kymmeniä muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [rukoushetket](http://finto.fi/yse/fi/page/Y509646)

**Comment by mirmaid** [comment]
Melko runsaasti käytetty Melindassa. Voiko tarkoittaa mitä tahansa minkä tahansa uskonnon rukoushetkeä? 
https://evl.fi/sanasto/-/glossary/word/Rukoushetki

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Hetkipalvelus
https://fi.wikipedia.org/wiki/Tefilla
https://fi.wikipedia.org/wiki/Salat

**Comment by YSO-kokous** [comment]
Tarkistetaan englanninkielinen termi. LCSH- prayer meetings ei sovi tähän, kun on laajempi käsite.
