### ISSUE TITLE
koggit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9647]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

koggit 

#### Ehdotettu termi englanniksi   

Cogs (Sailing ships) 

#### Ehdotettu termi ruotsiksi   

Koggar 

#### Vaihtoehtoiset termit ja ilmaisut   

hansalaivat 

#### Vastaava käsite muussa sanastossa   

LCSH : https://id.loc.gov/authorities/subjects/sh85027757.html 
SAO : https://id.kb.se/term/sao/Koggar 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

Koggi eli yleisesti myös hansalaiva oli 1200-luvulla Hansan käyttöön ottama purjealustyyppi, joka oli suunniteltu Itämeren rahtiliikenteeseen (wikipedia) 

#### Perustelut ehdotukselle   

YSOsta puuttuu tämä purjealustyyppi. Fregatit, klipperit, kuunarit ja parkkilaivat on. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.helsinki.fi/permalink/358UOH_INST/1h3k2rg/alma9934126313206253 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [koggit](http://finto.fi/yse/fi/page/Y509647)

**Comment by mariaforsen** [comment]
Sv. koggar
