### ISSUE TITLE
eräoppaat (teokset)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9648]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[eräoppaat (teokset)](http://www.yso.fi/onto/yso/p1932)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitaan myös SLM:ään

**Perustelut ehdotukselle**

käytetty Melindassa genreterminä

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Hyväksytty SLM:ään.

Ehdotettu joko KT tai päätermin muutos > retkeilyoppaat (vain teokset, ei ammattina).

**Comment by mirmaid** [comment]
YSO-kokoukseen.

**Comment by mirmaid** [comment]
Jos päätermi muuttuu YSOssa, varmaankin sama myös SLM:ään.

**Comment by mariaforsen** [comment]
Sv. utflyktsguider, friluftsguider..? Retkeilyopas ei sanakirjoissa tms. sanastoissa.

**Comment by mirmaid** [comment]
Eli ehdotettu siis, että kun kyse on teoksesta, päätermiksi tulisi retkeilyoppaat. Ruotsiksi ei ole tarpeen tehdä muutosta, jos se ei sovellu. Vähintään kuitenkin ohjaustermiksi. 

Google-haulla eräopas tuo ammattiviitteitä ja retkeilyopas näitä kirjoja. Sen pohjalta kannattaisin muutosta suomeksi.

**Comment by mariaforsen** [comment]
Suomeksi ei sitten ole minkäänlaista merkityseroa erä- ja retkeilyoppailla? Eräopas olisi siis yhtä sopiva esim. tälle: https://www.suomalainen.com/products/uusi-paakaupunkiseudun-retkeilyopas?variant=21150543347801&currency=EUR&gclid=Cj0KCQiA1ZGcBhCoARIsAGQ0kkq7hyU2ELIxU5mo2EM48hG6HnCcpuelRZPOvshNBUuj8wC_vmNOYvQaAoV0EALw_wcB 

Vrt. https://www.kielitoimistonsanakirja.fi/#/er%C3%A4retki?searchMode=all 

Muuten olen kyllä samaa mieltä että retkeilyopas on suomeksi parempi ja nykyaikainen termi. Pyrkimyksenä siis vain varmistaa että todella on ok säilyttää ruotsiksi vildmarksguider (vildmark mielletään yleensä aika kauas Helsingistä..)

**Comment by mirmaid** [comment]
^ Eli onko kysymys, että olisiko tuota Helsingin seudun retkeilyopasta kuvailtu eräoppaat (teokset) -termillä? Veikkaan että varmaankin, kun ei muuta ole ollut, mutta retkeilyoppaat toki sopii paremmin. Retkeilyoppaat ainakin mielestäni sopii monenlaisiin ympäristöihin, oli sitten vildmark tai enempi sivistyksen laitamilla 🙂.

**Comment by mariaforsen** [comment]
Ongelma onkin se että retkeilyoppaat sopii riippumatta onko vildmark vai sivistyksen laitamilla, mutta vildmarksguider ei sovi. Ruotsin kannalta voisi olla kaksi termiä, vildmarksguider ja utflykts/frilufts/vandringsguider, mutta ymmärrän toki ettei suomeksi haluta kahta. Jos tämä muutos nyt kuitenkin tehdään suomeksi, niin taitaa olla tarpeen tehdä jonkinlainen muutos myös ruotsiksi (yllä kuvaillusta syystä).

**Comment by ilona-x** [comment]
Vähän ohi aiheen, mutta törmäsin tässä joku aika sitten YKL-hakemistosanoissa näihin oppaisiin, jotka olisivat tarpeen varmaan vielä eräoppaitakin vaativammissa ympäristöissä 😁 
[79.4Retkeily. Ulkoilu ](https://finto.fi/ykl/fi/page/79.4) 
Henkiinjäämisoppaat, erätaidot (79.4)
Selviytymisoppaat, erätaidot (79.4)

**Comment by mirmaid** [comment]
^ 😁

Ehkä ruotsiksi toimiva olisi sitten yhdistelmätermi, ellei joku noista utflykts/frilufts/vandringsguider jo pelkästään kata retkeilyä riippumatta paikasta.

**Comment by AuHo22** [comment]
Ohjaustermi voisi olla myös vaellusoppaat.

**Comment by YSO-kokous** [comment]
**Päätös**

Tehdään ehdotettu muutos. Lisätään _vaellusoppaat_ ohjaustermiksi.

**Comment by mirmaid** [comment]
Ilmeisesti aiemmin päätetyn mukaisesti siis SLM:ään _retkeilyoppaat_.

**Comment by mirmaid** [comment]
^ Hyväksytty/SLM.

**Comment by mariaforsen** [comment]
Sv. vildmarksguider (verk) > utflyktsguider (verk) HT friluftsguider, utfärdsguider, vandringsguider 
Libris titlar: https://libris.kb.se/hitlist?d=libris&q=utflyktsguide&f=ext&spell=true&hist=true&mf=&p=1
https://svenska.se/tre/?sok=utflykt&pz=1
https://svenska.se/tre/?sok=friluft&pz=1
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_d8e9e51cd34226d186f4163bf867b5a5&list_id=1&keyword=retkeily&word=retkeily
