### ISSUE TITLE
matala-asteinen tulehdus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9649]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

matala-asteinen tulehdus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Termi esiintyy jo paljon mediassa.  https://www.puhti.fi/tietopaketit/matala-asteinen-tulehdus/, https://www.uef.fi/fi/artikkeli/runsas-liikunta-auttaa-hillitsemaan-matala-asteista-tulehdusta-lapsilla

**Ehdotettu yläkäsite YSOssa (LT)**

 [suoliston taudit](http://www.yso.fi/onto/yso/p4707)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [tulehdukselliset suolistosairaudet](http://www.yso.fi/onto/yso/p38636)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/015289634   , https://melinda.kansalliskirjasto.fi/byid/016601403

**Ehdottajan organisaatio**

Finto / Asiakaspalalute [KK-03044712]
**Termiehdotus Fintossa:** [matala-asteinen tulehdus](http://finto.fi/yse/fi/page/Y509649)

**Comment by mariaforsen** [comment]
Sv. låggradig inflammation HT låg inflammation, lågintensiv inflammation

**Comment by mirmaid** [comment]
Ei Lääketieteen termit -sanastossa. Tätä on kuitenkin ollut myös väitöskirjoissa, eng. _subclinical inflammation, low-grade inflammation_.

**Comment by fantsby-m** [comment]
Ei ICD-10:ssä

**Comment by AuHo22** [comment]
Vähän ihmetyttää, että tätä ei sanastoista löydy, koskapa tutkimuksia löytyy paljonkin varsinkin englanniksi?

**Comment by FinMeSHienPaimentaja** [comment]
Joo, tätä "matala-asteinen tulehdus" tulee varsin paljon lääketieteen puolella vastaan. Ehkä siksi ei löydy sanastoista, koska ei ole varsinainen tauti? (Toisaalta on esim. Insulin Resistance MeSH-terminä, mutta ehkä "matala-asteinen tulehdus" ei vaan vielä ole niin vakiintunut ja lyönyt itseään terminä läpi.)
