### ISSUE TITLE
vähemmistöstressi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9650]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vähemmistöstressi

**Ehdotettu termi ruotsiksi**

minoritetsstress

**Ehdotettu termi englanniksi**

minority stress

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vähemmistöstressistä puhutaan entistä enemmän, joten olisi hyvä saada se legitiimiksi myös sanastotasolla. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [mielenterveys](http://www.yso.fi/onto/yso/p1949), [hyvinvointi](http://www.yso.fi/onto/yso/p1947)

**Ehdotetut temaattiset ryhmät**

 [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549), [55 Psykologia](http://www.yso.fi/onto/yso/p26543), [60 Sosiologia. Sosiaalipsykologia](http://www.yso.fi/onto/yso/p26562)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [seksuaalivähemmistöt](http://www.yso.fi/onto/yso/p1828), [sukupuolivähemmistöt](http://www.yso.fi/onto/yso/p15698), [vähemmistöt](http://www.yso.fi/onto/yso/p5740)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/V%C3%A4hemmist%C3%B6stressi)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/182067

**Ehdottajan organisaatio**

Åbo Akademi 
**Termiehdotus Fintossa:** [vähemmistöstressi](http://finto.fi/yse/fi/page/Y509650)

**Comment by mirmaid** [comment]
Ei Melindassa. 
https://fi.wikipedia.org/wiki/V%C3%A4hemmist%C3%B6stressi

Stressin alla toistaiseksi vain _teknostressi_.

**Comment by LeKorsu** [comment]
Google n. 11800 osumaa, minulle tulee ensimmäiseksi Duodecimin artikkeli https://www.duodecimlehti.fi/duo16384. Yläpeukku.
