### ISSUE TITLE
kinestetiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9651]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kinestetiikka 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

http://jultika.oulu.fi/Record/isbn978-952-62-2701-6 

#### Perustelut ehdotukselle   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [kinestetiikka](http://finto.fi/yse/fi/page/Y509651)

**Comment by ilona-x** [comment]
TSR : kinestetiikka http://www.yso.fi/onto/tsr/p11765

**Comment by mirmaid** [comment]
4 viitettä Melindassa.
https://fi.wikipedia.org/wiki/Kinestetiikka

**Comment by mariaforsen** [comment]
Sv. kinestetik
https://www.vaasankeskussairaala.fi/sv/for_patienter/aktuellt/nyheter/2017/i-kinestetik-tillgodogors-de-egna-resurserna/
