### ISSUE TITLE
päälliköt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9652]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[päälliköt](http://www.yso.fi/onto/yso/p26193)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa tai mahdollisesti yhdistettävissä/poistettavissa (johtajat, esimiehet)

**Perustelut ehdotukselle**

Ruotsiksi termi on ollut chef, mutta tämä termi käytetään ruotsiksi myös esimiehistä ja johtajista. Ks. Melinda: tietueisiin tulee nyt automaattisesti "päälliköt", vaikka suomeksi todennäköisesti käytettäisiin "esimiehet" ja/tai "johtajat". Kielitoimiston sanakirja: päällikkö=henkilö jonka käskyvallan alaisena on toisia henkilöitä t. jk organisaatio, laitos tms.; johtaja, esimies, päämies.  

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ei ole aina korvattavissa näillä:
Purjeveneen päälliköksi : opas saaristo- ja rannikkopäällikkökurssille
Pääesikunnan päälliköt vuosina 1982-2019 (?)

Samoin esim. heimopäälliköt, mutta ehkä johtajat mahdollinen niissä (?). Varmaan joka tapauksessa yhdistettävä.

**Comment by YSO-kokous** [comment]
Poistetaan päälliköt
Lisätään ojaustermiksi: päälliköt KÄ johtajat, esihenkilöt
