### ISSUE TITLE
terveyslukutaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9653]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

terveyslukutaito 

#### Ehdotettu termi englanniksi   

health literacy 

#### Ehdotettu yläkäsite YSOssa (LT)   

[informaatiolukutaito](http://www.yso.fi/onto/yso/p15108) 

#### Assosiatiiviset (RT)   

[terveysosaaminen](http://www.yso.fi/onto/yso/p26366) 

#### Vastaava käsite muussa sanastossa   

FinMeSH : <http://www.yso.fi/onto/mesh/D057220> 
LCSH : <http://id.loc.gov/authorities/subjects/sh2013000623> 

#### Perustelut ehdotukselle   

tarve kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Developing an instrument for measuring health literacy among school-aged children / 

**Termiehdotus Fintossa:** [terveyslukutaito](http://finto.fi/yse/fi/page/Y509653)

**Comment by mirmaid** [comment]
6 viitettä Melindassa. 

Sanastossa on _terveysosaaminen_, ovat kyllä mielestäni melko päällekkäisiä: _Puutteet terveydenlukutaidossa huolestuttavat tutkijoita, koska koettu terveysosaaminen vaikutti terveyteen ja terveyskäyttäytymiseen enemmän kuin sukupuoli tai perheen varallisuus_. https://www.laakarilehti.fi/ajassa/ajankohtaista/monella-nuorella-on-puutteita-terveyden-lukutaidossa/

Varmaan mahdollista määritellä, että "lukutaito" liittyy nimenomaan kykyyn hankkia, ymmärtää ja arvioida terveyteen liittyvää tietoa, mutta en ole ihan vakuuttunut tarpeesta muodostaa loputtomasti lukutaito-päätteisiä yhdyssanoja sen sijaan, että käytettäisiin _medialukutaito_-käsitettä ym. yhdessä soveltuvien muiden käsitteiden kanssa.

**Comment by ilona-x** [comment]
Joo, päällekkäisyyden havaitsin jo ehdotusta tehdessä, mutta päätin kuitenkin laittaa tämän ehdolle, kun oli FinMeSHIssä ja LCSHssa toisin kuin terveysosaaminen.  Olisikohan mahdollista lisätä ohjaustermiksi terveyslukutaito KÄYTÄ terveysosaaminen? 

IATE4
fi        terveystiedon tulkintataito ★★★☆;
terveysosaaminen ★★★☆;
terveyden lukutaito ★★★☆
sv       hälsokompetens ★★☆☆
en      health literacy ★★★☆
Lähde:  IATE 10.08.2021, Euroopan unioni (926210)
https://termipankki.fi/tepa/fi/haku/terveysosaaminen

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi: terveyslukutaito KÄ terveysosaaminen
