### ISSUE TITLE
yhdyskuntatalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9654]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[yhdyskuntatalous](http://www.yso.fi/onto/yso/p23473)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko poistettavissa? Käytetty Melindassa vain 15 kertaa. 

**Perustelut ehdotukselle**

Ruotsiksi urbanekonomi ja englanniksi urban economics, nämä ovat jo sanastossa muodossa kaupunkitalous. Tämä ei ole helposti ratkaistavissa millään muulla tavalla.  

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Vain vähän käytetty myös Googlessa, ja Melindan 15 tietutta vanhoja aineistoja. Ei löydy sanakirjoista (Mot, TEPA tms.)

**Comment by jtuohini** [comment]
Entä muuttaminen KT-muodoksi **kaupunkitalous**-asiasanalle? Yleisperiaatteena kai mieluummin viittausmuoto täyden poiston sijaan?

**Comment by mariaforsen** [comment]
Kyllä, pitäisi olla ohjaustermi.

**Comment by mirmaid** [comment]
Pitäisi varmaankin ohjata myös muihin - kunnallistalous, paikallistalous, aluetalous?

**Comment by YSO-kokous** [comment]
Poistetaan yhdyskuntatalous
Lisätään ohjaustermiksi  yhdyskuntatalous KÄ  kunnallistalous, paikallistalous, aluetalous
