### ISSUE TITLE
lyhytproosa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9655]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[lyhytproosa](http://www.yso.fi/onto/ysa/Y117601) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

SLM:ssä muuteteen nykyiset RT-suhteiset ST-suhteisiksi, ainakin "kertomukset", "novellit", "pienoisnovellit", "pienoisromaanit" ja "tarinat" 

#### Perustelut ehdotukselle   

Hierarkian korjaaminen 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
KAUNO-ryhmä työstää selkeämmän määritelmän.

**Comment by mirmaid** [comment]
KAUNO-ryhmä ehdottaa määritelmän poistoa. Ryhmän puolesta hierarkiamuutos muuten ok, mutta _pienoisromaanit_ ennemmin romaanien alle. Ryhmä käsittelee pienoisromaanit ja pienoisnovellit -termejä vielä tulevassa kokouksessa.

**Comment by mirmaid** [comment]
Säilytetään RT-suhteet. Kielitoimiston sanakirjan määritelmä sai kannatusta vähän muokattuna: _Lyhyt katkelmallinen proosateksti, joka ei ole novelli._

**Comment by mirmaid** [comment]
KAUNO-ryhmä: Ehdotetaan termin ’pienoisnovellit’ poistamista sanastosta.

**Comment by AuHo22** [comment]
Meiltä tullut kommentti:  pienoisnovelli on tosiaan oma kirjallinen muotonsa (kerrontakeinona on todella voimakas tiivistys ja  pituus on korkeintaan sivu).

Stories of fewer than 1,000 words are sometimes referred to as "short short stories", or "flash fiction"
(https://en.wikipedia.org/wiki/Short_story)
https://en.wikipedia.org/wiki/Flash_fiction

**Comment by mirmaid** [comment]
^ Tämä tullut siis KAUNO-kokouksen jälkeen, koska silloin päädyttiin ehdottamaan pienoisnovellit-genren poistoa muistaakseni nimenomaan siksi, että ei katsottu olevan mitään selkeää kriteeriä erotella pienoisnovellit novelleista. "Korkeintaan sivun pituus" on yleensä varmaan selvästi vähemmän kuin 1000 sanaa? Sinänsä tuollainen määritelmä olisi suhteellisen selkeä, mutta löytyykö sitä mistään lähteestä?

**Comment by AuHo22** [comment]
Tässä ei tietääkseni etsitty määritelmää.

**Comment by mirmaid** [comment]
^ Se on ehkä vähän rivien välissä, mutta KAUNO-ryhmä siis käsitteli termejä pienoisromaanit ja pienoisnovellit, kuten ylempänä on kirjattu https://github.com/Finto-ehdotus/YSE/issues/9655#issuecomment-1049648852. Ryhmä hyväksyi määritelmän pienoisromaaneille, mutta pienoisnovellit-termi oli ryhmälle ongelmallisempi. Ehdotus sen poistamisesta on siis KAUNO-ryhmän (ei minun, vaikka olen sen kirjannut tänne ryhmän puolesta). Ajattelin, että jos jokin määritelmäehdotus on, niin ehkä KAUNO-ryhmä voi päätyä toisenlaiseen ratkaisuun. 

Olisi varmaan hyvä vähän selkeyttää myös eri ryhmien vastuuta, eli jos SLM-ryhmän näkemys eroaa Muusan tai KAUNO-ryhmän näkemyksestä, kuka viime kädessä tekee päätöksen musiikin/fiktion ehdotuksista? Onko se kuitenkin sitten SLM-ylläpitoryhmä?

**Comment by mariaforsen** [comment]
SLM-ryhmän pitää varmaan tehdä lopulliset päätökset SLM:n sisällöstä, mutta jos musiikin ja kaunokirjallisuuden asioissa haluttaisiin jostain syystä toisenlaista ratkaisua kuin Muusa- tai Kaunoryhmät kannattavat, niin siihen pitää olla painavat syyt ja argumentit. 

Pienoisnovellit on kyllä Melindassa käytetty yli 100 kertaa SLM-terminä, joten en kevyein perustein poistaisi, mutta ymmärrän että voi olla ongelmallista tietää milloin sitä pitäisi käyttää, ja milloin vain novellit riittää. Ja onko sitä käytetty johdonmukaisesti Melindassa?

**Comment by AuHo22** [comment]
Romaanin ja pienoisromaanin välinen rajanveto taitaa olla ihan samalla tavalla sumea kuin novellin ja pienoisnovellin. Itse olen kuvaillut julkaisuja, joissa on ollut tarkoituksenmukaista käyttää sekä lyhytproosa että pienoisnovellit -termejä, mutta novellit-termi olisi jo voinut olla liioiteltua.

**Comment by mirmaid** [comment]
SLM-ryhmässä ehdotettiin kuitenkin pienoisnovellit-termin säilyttämistä. Kirjastopalvelu lähettää vielä kommentit KAUNO-ryhmälle.

**Comment by AuHo22** [comment]
https://id.loc.gov/authorities/genreForms/gf2014026543.html

**Comment by ghost** [comment]
Kauno-ryhmä käsitteli uudelleen termiä pienoisnovellit ja on edelleen termin poistamisen kannalla. SLM-ryhmä päättää.

**Comment by mirmaid** [comment]
Poistetaan /SLM.
