### ISSUE TITLE
musiikkiesitykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9657]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[musiikkiesitykset](http://www.yso.fi/onto/yso/p29963)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT musiikkikeikat

**Perustelut ehdotukselle**

Nämä liittyvät usein toisiinsa

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Suhde on jo sanastossa.
