### ISSUE TITLE
konsertit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9658]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[konsertit](http://www.yso.fi/onto/yso/p11185)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

RT musiikkikeikat

**Perustelut ehdotukselle**

Nämä liittyvät usein toisiinsa

**Ehdottajan organisaatio**

**Comment by jtuohini** [comment]
Vai ovatko peräti sama asia?

**Comment by mirmaid** [comment]
Suhde on jo sanastossa.

**Comment by jtuohini** [comment]
Kuka tuota suhdetta olikaan ehdottanut lisättäväksi, niin vastavuoroisesti teen ehdotuksen, että **musiikkikeikat** muutetaan **konsertit**-asiasanan KT-muodoksi. Kysehän on populaarimusiikin konserteista, joita puhekielessä "keikoiksi" satutaan nimittämään? Myös taidemusiikin puolella puhutaan "keikoista" samassa merkityksessä.

**Comment by MUUSA-kokous** [comment]
Kannatetaan musiikkikeikkojen muuttamista konserttien KT:ksi.
