### ISSUE TITLE
esteettömyys

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9659]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[esteettömyys](http://www.yso.fi/onto/yso/p16241)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko jaettavissa tai mahdollisesti tarkennettavissa?

**Perustelut ehdotukselle**

Ruotsiksi hinderslöshet, mutta vastine riippuu merkityksestä (hinderslöshet=det att en verksamhet inte möter laga hinder enl. prövning av en myndighet; i fråga om t.ex. hinders­prövning). Tilanne näyttää olevan sama englanniksi (non-impediment), eli termi ei sovi siihen merkitykseen missä nykyään usein käytetään, eli: https://termipankki.fi/tepa/fi/haku/esteett%C3%B6myys Ks. myös https://fi.wikipedia.org/wiki/Esteett%C3%B6myys 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Jos käsite jaetaan/rajataan vammaisuuteen liittyvään merkitykseen ruotsinnos voisi olla "fysisk tillgänglighet" tms. Termi on ruotsin kannalta haastava, koska saatavuus, saavutettavuus ja esteettömyys ovat kaikki oikeastaan "tillgänglighet". Nykyinen tilanne on kuitenkin korjattava, Melindassa on nyt "hinderslöshet" väärissä tietueissa.

**Comment by mirmaid** [comment]
Nämä eivät suomeksi mene sekaisin saatavuuden kanssa (esteettömyys ja saavutettavuus ovat osittain päällekkäisiä, https://www.invalidiliitto.fi/esteettomyys/saavutettavuus). Olisiko tuo hinderslöshet vastakohta _esteellisyydelle_ (sv. jäv)? Muutamia kertoja samoissa viitteissä esteellisyys ja esteettömyys, auttaisiko esteettömyys (ei-esteellisyys) KÄ esteellisyys?

**Comment by mariaforsen** [comment]
Ongelma on nimenomaan esteettömyyden ja saavutettavuuden osittainen päällekkäisyys. Yllä ehdotettu ohjaustermi ei auta ruotsiksi. 

Mutta **jos** esteettömyys on rajattu fyysiseen ympäristöön, kuten sanastossa "Sosiaali- ja terveyspalvelujen yhdenvertaisuuden käsitteet (THL, 2019)" niin sitten voidaan mahdollisesti laittaa ruotsiksi "framkomlighet" ("finlandismina") :

fi        esteettömyys
määritelmä
tila, jossa rakennettu ympäristö, tuotteet ja palvelut ovat mahdollisimman toimivia, helppokäyttöisiä ja helposti saavutettavia
huomautus
Esteettömyys toteutuu, kun ympäristöstä poistetaan mahdollisimman monet liikkumisen, toimimisen, näkemisen, kuulemisen, ymmärtämisen ja kommunikaation esteet. Perinteisesti esteettömyys on liitetty rakennettuun ympäristöön, mutta viime aikoina käsite on laajentunut kattamaan myös palvelujen, viestinnän ja ihmisten välisen vuorovaikutuksen esteettömyyden.
Sosiaali- ja terveyspalveluja toteutettaessa on edistettävä esteettömyyttä.
Esteettömyys- ja saavutettavuus-käsitteitä käytetään usein päällekkäin. **Esteettömyys liitetään usein fyysiseen ympäristöön, saavutettavuus taas digitaaliseen ympäristöön ja asenteisiin.**

https://www.kommunforbundet.fi/informationsprodukter-och-informationstjanster/webbhandbocker/tillganglighet/2-vad-ar-tillganglighet

**Comment by mirmaid** [comment]
Eli se mitä halutaan onkin esteettömyyden ja saavutettavuuden yhdistäminen? Sain sen käsityksen, että ongelmana oli sekoittuminen esteettömyyteen merkityksessä "ei-esteellinen" ("ei-jäävi") esim. päätöksenteossa.

**Comment by mirmaid** [comment]
Voidaanko yhdistää esteettömyys KÄ saavutettavuus?

**Comment by fantsby-m** [comment]
Englanninkielinen termi _non-impediment_ kuulostaa lähinnä esteettömyydeltä esim. avioliittoon ("esteettömyystodistus"). Esteettömyydestä ja saavutettavuudesta käytetään kaiketi englanniksi molemmista termiä _accessibility_.

**Comment by mariaforsen** [comment]
Kyllä, yhdistäminen auttaisi. Tilanne on siis ollut se että ruotsiksi ja englanniksi termi on tarkoittanut esteettömyys merkityksessä jäävittömyys. Kun nyt pitää korjata se, niin pitää olla selvä tarkalleen mihin termi viitta ja miten se eroaa saavutettavuudesta, koska molemmat termit esteettömyys (liittyen vammaisuuteen tms.) ja saavutettavuus käännetään ruotsiksi **tillgänglighet**.

**Comment by mirmaid** [comment]
^ Mutta varmaan ruotsiksikin rajataan sitten, ettei sekoitu saatavuuteen, tyyliin "perunan saatavuus on ollut huono satovahinkojen takia".

**Comment by YSO-kokous** [comment]
### Päätös
yhdistetään käsitteet:  esteettömyys ja saavutettavuus KT esteettömyys, saavutettavuus
