### ISSUE TITLE
Eläintenhoito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9661]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Eläintenhoito

**Ehdotettu termi ruotsiksi**

Djursskötsel

**Ehdotettu termi englanniksi**

Animal care

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Mm. lastenkirjoissa usein tarpeellinen yleistermi eläinten hoitamiselle, esim. koirien ulkoiluttaminen, lemmikkieläimien hoitaminen tms.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kohdistuva toiminta](http://www.yso.fi/onto/yso/p38217)

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

London's No. 1 Dog-Walking Agency

**Ehdottajan organisaatio**

Suomen kirjastopalvelu OY
**Termiehdotus Fintossa:** [Eläintenhoito](http://finto.fi/yse/fi/page/Y509661)

**Comment by mirmaid** [comment]
Sanastossa on _kotieläinhoito_. KAUNO-kokouksessa tästä todettiin, että voidaan hoitaa muitakin kuin kotieläimiä (varmaankin tietoaineistoissa esim. eläintarhassa?), toistaiseksi varmaan tyypillisesti kuvailtu _koira + hoito_ jne.

**Comment by mirmaid** [comment]
3 viitettä Melindassa, mutta niihin sopisi kyllä _kotieläinhoito_.

**Comment by LeKorsu** [comment]
Paljon amerikkalaisia eläintarhoista kertovia tv-ohjelmia seuranneena peukku eläintenhoidolle, joka voi sisältää niin lemmikit kuin eläintarhojen eläimet.

**Comment by AuHo22** [comment]
Eläintenhoitajat on, eläintenhoito on kuitenkin laajempi kuin kotieläinhoito (maatalous lähinnä?),
esim. https://www.studentum.fi/koulutushaku/elainten-hoito-koulutus
Voisi myös käyttää yleisesti kuten edellä mainittu ja ehdotuksessa.

**Comment by mirmaid** [comment]
Sitten on kyllä aika todennäköistä, että myös kotieläimistä aletaan käyttää termiä eläintenhoito.

**Comment by YSO-kokous** [comment]
hoito (eläimet) KÄ eläintenhoito
hoito (tuotantoeläimet) KÄ kotieläinhoito
lemmikkieläinten hoito KÄ eläintenhoito
eläintenhoito (tuotanntoeläimet) KÄ kotieläinhoito

**Comment by mariaforsen** [comment]
Sv. djurskötsel HT djurvård
https://svenska.se/tre/?sok=djursk%C3%B6tsel&pz=1
https://termipankki.fi/tepa/fi/haku/el%C3%A4intenhoitajan%20ammattitutkinto
