### ISSUE TITLE
zirkoniumfosfaatti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9662]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

zirkoniumfosfaatti 

#### Ehdotettu termi englanniksi   

zirconium phosphate 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fosfaatit](http://www.yso.fi/onto/yso/p8696) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85149913> 
Wikipedia : https://en.wikipedia.org/wiki/Zirconium_phosphate 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[09 Kemia](http://www.yso.fi/onto/yso/p26531) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Ion exchange in nuclear fuel reprocessing : zirconium phosphate materials for the separation of trivalent actinides and lanthanides / 

#### Perustelut ehdotukselle   

tarve kuvailussa 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [zirkoniumfosfaatti](http://finto.fi/yse/fi/page/Y509662)

**Comment by mariaforsen** [comment]
Sv. zirkoniumfosfat
