### ISSUE TITLE
kaljuutit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9666]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaljuutit 

#### Ehdotettu termi englanniksi   

galiots 

#### Ehdotettu termi ruotsiksi   

gallioter 

#### Vaihtoehtoiset termit ja ilmaisut   

kitsit 
kolmimastokaljuutit 
galliots [eng] 
galiotes [eng] 
galjoter [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[purjelaivat](http://www.yso.fi/onto/yso/p20211) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q1046122 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Perustelut ehdotukselle   

Kohtuullisen paljon aineistoa tästä laivatyypistä, koska yksi Suomen tunnetuimmista hylyistä, Sankt Mikael (1747), oli kaljuutti. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

. . 

#### Tarkoitusta täsmentävä selite   

Pienehkö tasapohjainen ja pyöreäperäinen rannikkopurjehtija, joka oli varustettu alaslaskettavilla sivuköleillä eli miekoilla. (https://www.mas.fi/fi/tutkimus-ja-artikkelit/artikkelit/laivatyyppien-nimitysperusteita) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kaljuutit](http://finto.fi/yse/fi/page/Y509666)

**Comment by mariaforsen** [comment]
https://www.saob.se/artikel/?unik=G_0001-0117.60QB
