### ISSUE TITLE
Implementointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9667]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Implementointi 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Näyttöön perustuvan tiedon jalkauttaminen 

#### Perustelut ehdotukselle   

Näyttöön perustuvan hoitotyön kehittäminen 

**Termiehdotus Fintossa:** [Implementointi](http://finto.fi/yse/fi/page/Y509667)

**Comment by mirmaid** [comment]
Edellisessä kokouksessa lisätty implementointi ohjaustermiksi _toteutukselle_. https://github.com/Finto-ehdotus/YSE/issues/9423

Pitäisikö oikeastaan lisätä myös KÄ _käyttöönotto_?

**Comment by AuHo22** [comment]
Implementointi-termiä käytetään myös direktiivien saattamisessa osaksi kansallista lainsäädäntöä. EKS: EU-oikeuden kansallinen voimaansaattaminen 
Korvaa termin: | EU-oikeuden implementointi

https://tieteentermipankki.fi/wiki/Oikeustiede:direktiivi_EU-oikeudessa
--direktiivin implementointi, kansallinen täytäntöönpano--

Myös lisäys implementointi KÄ täytäntöönpano?

**Comment by YSO-kokous** [comment]
Hyväksytään ohjaustermiksi implementointi KÄ täytäntöönpano  KÄ käyttöönotto
