### ISSUE TITLE
musta teologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9670]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

musta teologia 

#### Ehdotettu termi englanniksi   

Black theology 

#### Ehdotettu yläkäsite YSOssa (LT)   

[teologia](http://www.yso.fi/onto/yso/p3830) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85014636> 
Wikidata : https://www.wikidata.org/wiki/Q3943023 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Sopivaa käsitettä ei vanhastaan YSO:ssa, mutta on Teologisen tiedekunnan asiasanastossa, josta tarkoitus konvertoida Helkassa ja Melindassa. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/002273422 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [musta teologia](http://finto.fi/yse/fi/page/Y509670)

**Comment by mariaforsen** [comment]
Sv. svart teologi https://id.kb.se/term/sao/Svart%20teologi

**Comment by mirmaid** [comment]
20 viitettä Melindassa.
https://fi.wikipedia.org/wiki/Musta_teologia

**Comment by jtuohini** [comment]
LT-muodoksi ei **teologia**, vaan **vapautuksen teologia**! Lisäksi englanninkieliseksi KT-muodoksi _Black liberation theology_.
