### ISSUE TITLE
skotismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9671]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

skotismi 

#### Ehdotettu termi ruotsiksi   

skotism 

#### Ehdotettu termi englanniksi   

Scotism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[skolastiikka](http://www.yso.fi/onto/yso/p2886) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q1861708 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[02 Filosofia](http://www.yso.fi/onto/yso/p26545) 

#### Perustelut ehdotukselle   

Täsmällistä YSO-asiasanaa ei vanhastaan; löytyy Teologisen tiedekunnan asiasanastosta, jota ollaan konvertoimassa pois Helkasta ja Melindasta. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/001490632 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [skotismi](http://finto.fi/yse/fi/page/Y509671)

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Skotismi
