### ISSUE TITLE
uusprotestantismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9672]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uusprotestantismi 

#### Ehdotettu termi englanniksi   

New Protestantism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[protestantismi](http://www.yso.fi/onto/yso/p5043) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

Albrecht Ritschlin kehittelemä oppisuuntaus 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa tälle; löytyy Teologisen tiedekunnan kirjaston asiasanastosta, jota ollaan konvertoimassa Helkassa ja Melindassa pois. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/012613979 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [uusprotestantismi](http://finto.fi/yse/fi/page/Y509672)

**Comment by mariaforsen** [comment]
Sv. nyprotestantism

**Comment by mirmaid** [comment]
Näissä viitteissä näyttää esiintyvän myös sama Karl Barth, johon liittyy myös _dialektinen teologia_ -ehdotus. Googlella hyvin vähän mitään suomeksi. Onko tässä nyt varmasti kyse olemassaolevista oppisuunnista, vai enemmän yksittäisten teologien ajattelusta?

**Comment by ilona-x** [comment]
Teologian sanakirjassa näkyy olevan kulttuuriprotestantismi (http://sanakirja.teol.helsinki.fi/#/sanat/kulttuuriprotestantismi) , joka on mainittu esim. tämän uusprotestantismi-termillä kuvaillun teoksen nimekkeessä: https://melinda.kansalliskirjasto.fi/byid/001313112

**Comment by mirmaid** [comment]
^ Aika vähän viitteitä sekin tuo Googlella.

**Comment by AuHo22** [comment]
Saksan kansalliskirjastossa LT Protestantismus ST Neuprotestantismus 23 osumaa ST Kulturprotestantismus 58 osumaa

**Comment by mariaforsen** [comment]
Nationalencyklopedin: "Den dialektiska teologin såg nyprotestantismen som uttryck för en teologisk förfallsperiod. Till de omstridda elementen hör nyprotestantismens absolutifiering av vetenskapen och av evolutionstanken." https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/nyprotestantism
