### ISSUE TITLE
panenteismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9673]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

panenteismi 

#### Ehdotettu termi englanniksi   

panentheism 

#### Ehdotettu termi ruotsiksi   

panenteism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[jumalakäsitykset](http://www.yso.fi/onto/yso/p10555) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh91006238> 
Wikidata : https://www.wikidata.org/wiki/Q221390 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa tälle; löytyy Teologisen tiedekunnan kirjaston asiasanastosta, jota ollaan Helkassa ja Melindassa konvertoimassa pois. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/005976204 ja muita 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [panenteismi](http://finto.fi/yse/fi/page/Y509673)

**Comment by mariaforsen** [comment]
Myös SAOssa: https://id.kb.se/term/sao/Panenteism 
Hyvä RT olisi panteismi.

**Comment by mirmaid** [comment]
12 kertaa Melindassa.
