### ISSUE TITLE
Qumranin liike

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9674]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Qumranin liike 

#### Ehdotettu termi englanniksi   

Qumran community 

#### Vaihtoehtoiset termit ja ilmaisut   

Kuolleenmeren kääröjen yhteisö 
Qumranin veljeskunta 
Qumranin yhteisö 

#### Ehdotettu yläkäsite YSOssa (LT)   

[juutalaiset](http://www.yso.fi/onto/yso/p8494) 

#### Assosiatiiviset (RT)   

[essealaiset](http://www.yso.fi/onto/yso/p13135) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85110122> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/013003100 ja muita 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan täsmällistä asiasanaa; löytyy Teologisen tiedekunnan asiasanastosta, joka ollaan Helkassa ja Melindassa konvertoimassa pois. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [Qumranin liike](http://finto.fi/yse/fi/page/Y509674)

**Comment by mariaforsen** [comment]
Sv. Qumranförsamlingen HT Qumran-församlingen https://www.sprakbruk.fi/-/bindestreck-en-liten-repetition
https://id.kb.se/term/sao/Qumran-f%C3%B6rsamlingen

**Comment by mirmaid** [comment]
Melindassa käytetty (ttka) muotoa _Qumranin veljeskunta_ ja joitakin kertoja _Qumranin yhteisö_. Googlella eniten muotoa Qumranin yhteisö.

https://blogs.helsinki.fi/qumranjatekstiloydot/qumranin-liike/

**Comment by YSO-kokous** [comment]
Hyväksytään Qumranin yhteisö KT Qumranin liike, Qumranin veljeskunta
