### ISSUE TITLE
poltinrauta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9675]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

poltinrauta

**Ehdotettu termi ruotsiksi**

brännjärn

**Ehdotettu termi englanniksi**

branding iron

**Tarkoitusta täsmentävä selite**

Esineiden merkitsemiseen käytetty työväline

**Perustelut ehdotukselle**

Yleinen sana, puuttuu.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

 polttoleimasin

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

museokokoelmat

**Ehdottajan organisaatio**

Suomen kansallismuseo
**Termiehdotus Fintossa:** [poltinrauta](http://finto.fi/yse/fi/page/Y509675)

**Comment by jtuohini** [comment]
LCSH-vastine: [**Branding irons**](http://id.loc.gov/authorities/subjects/sh2012004264).

Ja sanaryhmäksi varmaan myös _22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous_? Poltinrauta kai myös hevosten ja nautakarjan merkitsemisessä käytettä väline? Myös orjia on polttomerkitty, joskin seikan huomioiminen sanaryhmän tasolla suomalaisessa kontekstissa lienee liioittelua.

**Comment by fantsby-m** [comment]
Myös _polttomerkkirauta_: https://www.finna.fi/Search/Results?lookfor=poltinrauta&type=AllFields

**Comment by YSO-kokous** [comment]
Hyväksytään poltinraudat KT polttomerkkiraudat

**Comment by mariaforsen** [comment]
Sv. brännjärn HT brännstämplar
