### ISSUE TITLE
kirkon lapsityö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9676]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kirkon lapsityö 

#### Ehdotettu termi ruotsiksi   

kyrkligt barnarbete 

#### Ehdotettu termi englanniksi   

church work with children 

#### Vaihtoehtoiset termit ja ilmaisut   

kyrkans barnarbete 
kirkollinen lapsityö 
seurakuntien lapsityö 
seurakunnallinen lapsityö 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkon kasvatustoiminta](http://www.yso.fi/onto/yso/p1926) 

#### Assosiatiiviset (RT)   

[pyhäkoulu](http://www.yso.fi/onto/yso/p11298) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85025784> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa tälle; löytyy Teologisen tiedekunnan kirjaston asiasanastosta, jota ollaan Helkassa ja Melindassa konvertoimassa pois. Vastaava jo olemassa oleva YSO-asiasana: "kirkon nuorisotyö". 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/002311560 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kirkon lapsityö](http://finto.fi/yse/fi/page/Y509676)

**Comment by mariaforsen** [comment]
Sv. kyrkans barnverksamhet HT kyrkans barnarbete, kyrkans arbete med barn
ALLFO barnverksamhet=lapsityö
OBS! inte barnarbete på svenska, se NE, SAOL etc.

**Comment by mirmaid** [comment]
Eikö ehdotettu yläkäsite ja pelkkä _lapsityö_ riittäisi? Jälkimmäistä käytetty kuvailussa myös kirkon toiminnasta.

**Comment by fantsby-m** [comment]
Melindassa 29 kertaa, 653 tai ttka.

**Comment by LeKorsu** [comment]
Sanastossa on jo "kirkon nuorisotyö" joten sikäli muoto "kirkon lapsityö" puolustaisi paikkansa kirkon kasvatustoiminnan alakäsitteenä.  Olisiko pyhäkoulu sitten tämän mahdolisen uuden termin alakäsite vai RT?
