### ISSUE TITLE
kanaanilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9677]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kanaanilaiset 

#### Ehdotettu termi englanniksi   

Canaanites 

#### Ehdotettu termi ruotsiksi   

kananéer 

#### Vaihtoehtoiset termit ja ilmaisut   

kaanaanilaiset [fin] 
kanaaninmaalaiset [fin] 
kanaanéer [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaiskansat](http://www.yso.fi/onto/yso/p14665) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85019279> 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000199867 ja muita 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa tälle; löytyy Teolologisen tiedekunnan kirjaston asiasnastosta, jota Helkassa ja Melindassa ollaan konvertoimassa pois. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 
[52 Historia](http://www.yso.fi/onto/yso/p26540) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kanaanilaiset](http://finto.fi/yse/fi/page/Y509677)

**Comment by mariaforsen** [comment]
Sv. kanaanéer ET kananéer
https://id.kb.se/term/sao/Kanaan%C3%A9er

**Comment by mirmaid** [comment]
_The word "Canaanites" serves as an ethnic catch-all term covering various indigenous populations—both settled and nomadic-pastoral groups—throughout the regions of the southern Levant or Canaan. It is by far the most frequently used ethnic term in the Bible._ 
_The name "Canaanites" is attested, many centuries later, as the endonym of the people later known to the Ancient Greeks from c. 500 BC as Phoenicians, and after the emigration of some Canaanite-speakers to Carthage (founded in the 9th century BC), was also used as a self-designation by the Punics (as "Chanani") of North Africa during Late Antiquity._ 
https://en.wikipedia.org/wiki/Canaan

_Thus while "Phoenician" and "Canaanite" refer to the same culture, archaeologists and historians commonly refer to the Bronze Age, pre-1200 BC Levantines as Canaanites; and their Iron Age descendants, particularly those living on the coast, as Phoenicians. More recently, the term Canaanite has been used for the secondary Iron Age states of the interior (including the Philistines and the states of Israel and Judah) that were not ruled by Arameans—a separate and closely related ethnic group._ https://en.wikipedia.org/wiki/Ancient_Canaanite_religion#The_Canaanites

**Comment by mirmaid** [comment]
Muinaiskansojen alla on _foinikialaiset_. Jos tämä on käytännössä foinikialaisten nimitys Raamatussa, onko ongelma että molemmat ovat sanastossa muinaiskansojen alla?

**Comment by YSO-kokous** [comment]
Tutkitaan edelleen onko tarpeen ottaa foinikialaiset -kästteen rinnalle
Voi tarkoittaa samaa kansaa, mutta vain eri aikakaudella.  Hisotriantutkimus: fonikialaiset,  raamatuntutkimus: kanaanilaiset.

LIsätietoa:  https://www.thecollector.com/phoenicians-canaanites-history-of-lebanon/

**Comment by mariaforsen** [comment]
En näe syytä tehdä eri ratkaisu YSOssa kuin SAOssa ja LCSH:ssa (sekä yleisesti eri hakuteoksissa yms.) tällaisessa tapauksessa. Kannatan erillisenä.

**Comment by mirmaid** [comment]
^ Ei varmaan sitten mitään määritelmiä, vaan vain RT-suhteella? Ainakin wikipedian määrittelyt aika vaikeita, jos kanaanilaiset viittaa pronssikauteen, mutta tiettyjen maantieteellisten alueiden osalta myös rautakauteen...

**Comment by mariaforsen** [comment]
RT ok, en kannata määritelmää. Aineistossa näkyy mistä on kysymys.
