### ISSUE TITLE
Hytermä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9678]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Hytermä](http://www.yso.fi/onto/yso/p115779)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tämän yläkäsite olisi varmaankin Savonlinna. Lisätäänkö PNR-linkit Suuri-Hytermä ja Pieni-Hytermä, ja nämä myös KT-muodoiksi?

**Perustelut ehdotukselle**

Paikkatietoalustalta löytyy Suuri-Hytermä http://paikkatiedot.fi/so/1000772/10718928 & Pieni-Hytermä http://paikkatiedot.fi/so/1000772/10718936

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Lisätään linkit, YK + tarkenne Savonlinna, ohjaustermeiksi Suuri-Hytermä ja Pieni-Hytermä
