### ISSUE TITLE
vauvanuket

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9679]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

vauvanuket

**Ehdotettu termi ruotsiksi**

babydockor

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Englanninkielisen termin reborn dolls voi kai suomentaa vauvanukeiiksi. Näiden nukkien valmistajat ja käyttäjät eivät kaikki ole välttämättä lapsia.

**Ehdotettu yläkäsite YSOssa (LT)**

 [nuket](http://www.yso.fi/onto/yso/p4588)

**Ehdotetut temaattiset ryhmät**

 [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Kirja, jossa opastettiin vauvanuken kasvojen ja kasvonpiirteiden valmistusta.

**Ehdottajan organisaatio**

Kokkolan kaupunginkirjasto
**Termiehdotus Fintossa:** [vauvanuket](http://finto.fi/yse/fi/page/Y509679)

**Comment by mariaforsen** [comment]
Rebornnukke taitaa olla tarkemmin rajattu ilmiö kuin pelkkä "vauvanukke". Näin myös ruotsiksi. 
https://fi.wikipedia.org/wiki/Reborn-nukke

**Comment by mirmaid** [comment]
Ei Melindassa, mutta sanastossa on muitakin nukketyyppejä. MAOssa on vauvanuket.

**Comment by fantsby-m** [comment]
_Vauvanuket_-asiasanalla on kuvailtu ihan tavallisia nukkeja Finnassa:
https://www.finna.fi/Search/Results?lookfor=vauvanuket&type=Subject

Ehkä tämä olisi kuitenkin suomeksikin _reborn_-nukke?

**Comment by mirmaid** [comment]
^ Juu, mutta ehkä vauvanuket kattaisi kaikki, myös nämä aidon näköiset.

**Comment by YSO-kokous** [comment]
Hyväksytään vauvanuket. Ei oteta ohjaustermiä.
