### ISSUE TITLE
uskonnolliset vähemmistöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9682]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uskonnolliset vähemmistöt](http://www.yso.fi/onto/ysa/Y104747) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "eriuskoiset" 

#### Perustelut ehdotukselle   

Historiallinen nimitys, mutta KT-muodot eivät koskaan haitaksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by ilona-x** [comment]
tässä ehdotettu KT-muotoa **eriuskoiset**, jota ei löydy Melindasta, mutta sen sijaan Melindassa näyttää käytetyn ttka- ja eks-terminä **eriuskolaiset**. Jäin miettimään, olisiko tässä kuitenkin tarkoitettu tuota eriuskolaiset-termiä?

**Comment by AuHo22** [comment]
Eriuskolaislaki on ollut, eli olisi ehkä oikeampi ilmaisu?

**Comment by YSO-kokous** [comment]
**Päätös:**  Ei hyväksytty.
