### ISSUE TITLE
apostolinen suksessio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9683]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

apostolinen suksessio 

#### Ehdotettu termi englanniksi   

apostolic succession 

#### Ehdotettu termi ruotsiksi   

apostolisk succession 

#### Vaihtoehtoiset termit ja ilmaisut   

apostolinen sukkessio 
apostolinen seuraanto 

#### Assosiatiiviset (RT)   

[pappisvihkimys](http://www.yso.fi/onto/yso/p2373) 
[piispanvihkimys](http://www.yso.fi/onto/yso/p27605) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85006060> 
Wikidata : https://www.wikidata.org/wiki/Q49482 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lopettamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/005974714 ja muita 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [apostolinen suksessio](http://finto.fi/yse/fi/page/Y509683)

**Comment by mirmaid** [comment]
Tietynlainen sukkessio http://www.yso.fi/onto/yso/p5677 :slightly_smiling_face:.

**Comment by mirmaid** [comment]
2 viitettä Melindassa.
https://fi.wikipedia.org/wiki/Apostolinen_suksessio

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Apostolisk%20succession

**Comment by jtuohini** [comment]
Ynnä 4 viitettä Melindassa muodossa "suksessio" (ttka).
