### ISSUE TITLE
makkabilaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9684]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

makkabilaiset 

#### Ehdotettu termi englanniksi   

Maccabees 

#### Ehdotettu termi ruotsiksi   

mackabéer 

#### Vaihtoehtoiset termit ja ilmaisut   

Machabees [eng] 
makkabealaiset [fin] 
makkabit [fin] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[juutalaiset](http://www.yso.fi/onto/yso/p8494) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85079260> 
Wikidata : https://www.wikidata.org/wiki/Q400019 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/017634360 ja muita 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [makkabilaiset](http://finto.fi/yse/fi/page/Y509684)

**Comment by mirmaid** [comment]
_Makkabealaiset oli juutalainen pappis- ja hallitsijasuku, jonka jäsenet hallitsivat Juudeaa noin vuosina 165–37 eaa. Suku kapinoi seleukideja vastaan niin sanotun makkabilaiskapinan aikana._ https://fi.wikipedia.org/wiki/Makkabealaiset

_The Maccabees were a group of Jewish rebel warriors who took control of Judea, which at the time was part of the Seleucid Empire. They founded the Hasmonean dynasty, which ruled from 167 BCE to 37 BCE, being a fully independent kingdom from about 110 to 63 BCE._
_The name Maccabee is often used as a synonym for the entire Hasmonean dynasty, but the Maccabees proper were Judas Maccabeus and his four brothers. The name Maccabee was a personal epithet of Judah, and the later generations were not his direct descendants._ https://en.wikipedia.org/wiki/Maccabees

**Comment by mirmaid** [comment]
9 viitettä Melindassa (makkabilaiset).

Katsotaanko makkabilaisten tarkoittavan kapinan aloittajia (ja heidän seuraajiaan?), vai mahdollisesti myöhempää hallitsijasukua alamaisineen tai kenties ylipäätään aikakauden traditionalistisen juutalaisuuden kannattajia? Ainakin paikka hierarkiassa riippuu tulkinnasta.

**Comment by LeKorsu** [comment]
Tarvitaanko ohjaustermiä makkabealaisista? KÄ makkabilaiset?

**Comment by YSO-kokous** [comment]
Hyväksytään: makkabilaiset KT makkabealaiset, makkabit
