### ISSUE TITLE
montanolaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9685]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

montanolaisuus 

#### Ehdotettu termi ruotsiksi   

montanism 

#### Ehdotettu termi englanniksi   

Montanism 

#### Vaihtoehtoiset termit ja ilmaisut   

montanismi 

#### Ehdotettu yläkäsite YSOssa (LT)   

[uskonnolliset yhteisöt](http://www.yso.fi/onto/yso/p5605) 
[varhaiskristillisyys](http://www.yso.fi/onto/yso/p16480) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85087022> 
Wikidata : https://www.wikidata.org/wiki/Q138681 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa vastinetta; tarvitaan Teologisen tiedekunnan kirjaston asianaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006399727 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [montanolaisuus](http://finto.fi/yse/fi/page/Y509685)

**Comment by mariaforsen** [comment]
Myös SAOssa https://id.kb.se/term/sao/Montanism

**Comment by mirmaid** [comment]
N. 10 kertaa Melindassa.
