### ISSUE TITLE
radikaalipietismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9686]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

radikaalipietismi 

#### Ehdotettu termi englanniksi   

Radical Pietism 

#### Ehdotettu termi ruotsiksi   

radikalpietism 

#### Vaihtoehtoiset termit ja ilmaisut   

radikaali pietismi 
yltiöpietismi 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q2125785 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa tälle; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/005755723 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [radikaalipietismi](http://finto.fi/yse/fi/page/Y509686)

**Comment by mariaforsen** [comment]
Kannatan. https://sv.wikipedia.org/wiki/Radikalpietism

**Comment by mirmaid** [comment]
10 viitettä Melindassa.
