### ISSUE TITLE
filistealaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9687]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

filistealaiset 

#### Ehdotettu termi englanniksi   

Philistines 

#### Ehdotettu termi ruotsiksi   

filistéer 

#### Ehdotettu yläkäsite YSOssa (LT)   

[muinaiskansat](http://www.yso.fi/onto/yso/p14665) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85100807> 
Wikidata : https://www.wikidata.org/wiki/Q193776 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa tälle; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006410798 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [filistealaiset](http://finto.fi/yse/fi/page/Y509687)

**Comment by mirmaid** [comment]
N. 10 kertaa Melindassa.

**Comment by jarmosaarikko** [comment]
WD http://www.wikidata.org/entity/Q193776
LCSH http://id.loc.gov/authorities/subjects/sh85100807 Philistines BT Ethnology--Palestine
