### ISSUE TITLE
leeviläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9688]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

leeviläiset 

#### Ehdotettu termi englanniksi   

Levites 

#### Ehdotettu termi ruotsiksi   

leviter 

#### Vaihtoehtoiset termit ja ilmaisut   

tribe of Levi [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[heimot](http://www.yso.fi/onto/yso/p6060) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85076334> 
Wikidata : https://www.wikidata.org/wiki/Q16707860 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/007016349 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [leeviläiset](http://finto.fi/yse/fi/page/Y509688)

**Comment by mirmaid** [comment]
N. 10 kertaa Melindassa. 

_Heimot_-käsitteellä ei ole muita alakäsitteitä YSOssa. Jos otetaan, voiko yläkäsite olla _Raamatun henkilöt_? Vai ajatellaanko että leeviläisyys on jatkunut edelleen (eli olisivat tavallaan "suku")? Ilman tarkennetta tämä voi sekoittua lestadiolaisuuteen, https://fi.wikipedia.org/wiki/Leevil%C3%A4isyys.

**Comment by jarmosaarikko** [comment]
menneekö käsitteen "juutalaiset" alle kuten ehdotettu issuessa #9731   fariseukset (tai farisealaiset)

**Comment by YSO-kokous** [comment]
Hyväksytään leeviläiset (juutalaisuus)
