### ISSUE TITLE
muotohistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9689]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

muotohistoria 

#### Ehdotettu termi ruotsiksi   

formhistoria 

#### Ehdotettu termi englanniksi   

form criticism 

#### Vaihtoehtoiset termit ja ilmaisut   

formkritik [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[eksegetiikka](http://www.yso.fi/onto/yso/p9983) 
[tutkimusmenetelmät](http://www.yso.fi/onto/yso/p415) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85013616> 
Wikidata : https://www.wikidata.org/wiki/Q496428 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/005770516 ja muita 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Tarkoitusta täsmentävä selite   

"Historiallis-kriittisen raamatuntutkimuksen menetelmä, jossa tavoitteena on selvittää tekstissä esiintyvien kirjallisten muotojen, lajien ja traditioiden luonne ja alkuperä." (https://tieteentermipankki.fi/wiki/Nimitys:muotohistoria) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[56 Tiede. Tutkimus](http://www.yso.fi/onto/yso/p26544) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [muotohistoria](http://finto.fi/yse/fi/page/Y509689)

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Formhistoria

**Comment by mirmaid** [comment]
9 viitettä Melindassa. Jos otetaan, tarvitsee varmaan tarkenteen (eksegetiikka)?

**Comment by jtuohini** [comment]
Lisäksi RT-suhde asiasanaan **tekstikritiikki**.

**Comment by jarmosaarikko** [comment]
WD: http://www.wikidata.org/entity/Q496428 - form criticism
LCSH 
- http://id.loc.gov/authorities/subjects/sh85013616 - Bible--Criticism, Form; Form criticism (Bible) 
- http://id.loc.gov/authorities/subjects/sh99005441 - Criticism, Form; Form criticism 
  Use as a topical subdivision under uniform titles of sacred works.
  BT Criticism, interpretation, etc.

**Comment by YSO-kokous** [comment]
Hyväksytään käsite:  muotohistoria (eksegetiikka)

**Comment by mariaforsen** [comment]
Sv. formhistoria (exegetik) HT formhistorisk undersökning (exegetik), formhistorisk metod (exegetik)
