### ISSUE TITLE
ylipapit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9690]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ylipapit 

#### Ehdotettu termi englanniksi   

high priests 

#### Ehdotettu termi ruotsiksi   

överstepräster 

#### Ehdotettu yläkäsite YSOssa (LT)   

[papit](http://www.yso.fi/onto/yso/p5468) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2004001948 (ST-vastine!)> 
Wikidata : https://www.wikidata.org/wiki/Q3114821 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa; tarvitaan Teologisen tiedekunnan asiasanaston lakkauttamisen myötä. 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006226463 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [ylipapit](http://finto.fi/yse/fi/page/Y509690)

**Comment by mirmaid** [comment]
Kielitoimiston sanakirja: korkea-arvoinen t. ylin (vars. ei-kristillisen kirkon) pappi. _Juutalaisten ylipapit. Auringonjumalan temppelin ylipappi._ 

6 viitettä Melindassa.

**Comment by YSO-kokous** [comment]
Hyväksytään sanastoon  kaksi käsitettä:  ylipapit ja toisena ylipapittaret

**Comment by mariaforsen** [comment]
Sv. överstepräster, översteprästinnor
