### ISSUE TITLE
miafysitismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9691]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

miafysitismi 

#### Ehdotettu termi ruotsiksi   

monofysitism 

#### Ehdotettu termi englanniksi   

Monophysitism 

#### Vaihtoehtoiset termit ja ilmaisut   

monofysitismi 
yksiluonto-oppi 
monophysism [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kristologia](http://www.yso.fi/onto/yso/p6748) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85086960> 
Wikidata : https://www.wikidata.org/wiki/Q183091 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/014299514 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [miafysitismi](http://finto.fi/yse/fi/page/Y509691)

**Comment by mirmaid** [comment]
Käytetty Melindassa muodossa monofysitismi.

**Comment by ilona-x** [comment]
Teologian sanakirja: http://sanakirja.teol.helsinki.fi/#/sanat/monofysitismi

**Comment by mirmaid** [comment]
Myös Googlella enemmän _monofysitismi_, wikipediassa muilla kielillä mono- (?).

**Comment by jtuohini** [comment]
https://fi.wikipedia.org/wiki/Miafysitismi

**Comment by YSO-kokous** [comment]
Hyväksytään  muodossa  monofysitismi 
Tutkitaan voiko miafytismi ja yksiluonto-oppi olla ohjausterminä.
