### ISSUE TITLE
ebionilaiset / ebionilaisuus / ebioniitit / ebionit / ebionitismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9692]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ebionilaiset / ebionilaisuus / ebioniitit / ebionit / ebionitismi 

#### Ehdotettu termi englanniksi   

Ebionism / Ebionites 

#### Ehdotettu termi ruotsiksi   

ebionism / ebioniter 

#### Ehdotettu yläkäsite YSOssa (LT)   

[juutalaiskristillisyys](http://www.yso.fi/onto/yso/p27471) 
[juutalaiskristityt](http://www.yso.fi/onto/yso/p11196) 
[uskonnolliset liikkeet](http://www.yso.fi/onto/yso/p4851) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85040649> 
Wikidata : https://www.wikidata.org/wiki/Q208171 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan tarkkaa asiasanaa; tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000205124 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [ebionilaiset / ebionilaisuus / ebioniitit / ebionit / ebionitismi](http://finto.fi/yse/fi/page/Y509692)

**Comment by mariaforsen** [comment]
Sv. evjoniter HT ebioniter, ebjoniter
https://id.kb.se/term/sao/Evjoniter
https://sv.wikipedia.org/wiki/Ebioniter

**Comment by mirmaid** [comment]
https://fi.wikipedia.org/wiki/Ebioniitit

Melindassa 4 kertaa ebionit, kerran ebioniitit. Googlella eniten muotoa _ebionit_.

**Comment by LeKorsu** [comment]
Onko tuo Melindan ebionit se, joka siellä Teologisen tdk:n kirjaston omassa asiasanastossa on ollut?

**Comment by jarmosaarikko** [comment]
> Onko tuo Melindan ebionit se, joka siellä Teologisen tdk:n kirjaston omassa asiasanastossa on ollut?

Tuohan on 653 kentässä eli ei ole sanastoa merkitty. Teologisen tiedekunnan sanastolla on kyllä oma koodinsa "[ttka](https://www.loc.gov/standards/sourcelist/subject.html)", joten jos se on sanastossa olisi voinut olla 650 kentässä tuolla sanastokoodilla. Vaikea sanoa näkemättä sanastoa...  
- **[ebionit](https://blogs.helsinki.fi/teolasiasanasto/e/)** löytyy tästä blogimuodossa julkaistusta sanastosta vuodelta 2013: https://blogs.helsinki.fi/teolasiasanasto/  - lieneekö sama kuin **ttka**?
- Ilonalla olikin tuoreempi teologian sanastolinkki  [ebioniitit](http://sanakirja.teol.helsinki.fi/#/sanat/ebioniitit), jossa myös määritelmä. Mutta tuo onkin Teinosen sanakirjan verkkoversio, eikä ttka.  Olisi tietysti mainiota, jos sanakirjassakin olisi tulevaisuudessa käsitteille pysyvät tunnisteet.

**Comment by ilona-x** [comment]
Ilmeisesti ttka-termit on jo muutettu yso-termeiksi, kun Melindasta tulee 5 osumaa muodolla ebionilaiset ja näissä sanastokoodina yso ja linkki tähän ehdotukseen `|2 yso/fin |0 https://github.com/Finto-ehdotus/YSE/issues/9692 `
esim. https://melinda.kansalliskirjasto.fi/byid/014373677

**Comment by YSO-kokous** [comment]
Hyväksytään ebionit KT ebioniitit, ebionilaiset
