### ISSUE TITLE
taksamittarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9693]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

taksamittarit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Esim. takseissa käytössä: https://yle.fi/uutiset/3-11396310

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 taksat

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-952-62-2550-0

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [taksamittarit](http://finto.fi/yse/fi/page/Y509693)

**Comment by jtuohini** [comment]
"Taksa" ei oikein voi käydä KT-muodoksi, kun ei viittaa samaan: mittari (tässä taksamittari) _versus_ mitattava asia (tässä taksa, s.o. hinta).

**Comment by jarmosaarikko** [comment]
YK mittauslaitteet 
- LCSH Taximeters http://id.loc.gov/authorities/subjects/sh85132891
- Wikidata  https://www.wikidata.org/wiki/Q1135572
- Wikipedia https://fi.wikipedia.org/wiki/Taksamittari

**Comment by mariaforsen** [comment]
Sv. taxametrar HT taximätare
https://svenska.se/tre/?sok=taxameter&pz=1

**Comment by AuHo22** [comment]
Myös taksimittarit, esim.
https://www.eduskunta.fi/FI/vaski/JulkaisuMetatieto/Documents/EDK-2016-AK-88051.pdf
https://www.taksiasennus.fi/

Vesimittauksen taksoista https://www.sipoo.fi/asuminen/sipoon-vesi/sipoon-vesi-taksat/
Voiko taksamittari tarkoittaa muutakin kuin taksimittaria ja kumpaa halutaan?

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**taksamittari**
takseissa ajomaksun osoittava mittari. 

--

Vedenkulutuksen mittaus tapahtuu vesimittareila, josta saatavan kulutuslukeman perusteella vedestä sitten laskutetaan vesilaitoksen hinnaston (hinnan/taksan) mukaan.

**Comment by YSO-kokous** [comment]
Hyväksytään taksamittarit KT taksimittarut
