### ISSUE TITLE
vapaaehtoistyö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9694]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vapaaehtoistyö](http://www.yso.fi/onto/yso/p3050)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ohjaustermi vaihdetaan päätermiksi:   KÄ vapaaehtoistoiminta KT vapaaehtoistyö

**Perustelut ehdotukselle**

Kukaan vapaaehtoistoiminnan toimijoista ei puhu enää työstä asian yhteydessä. 

**Ehdottajan organisaatio**

Finto/asiakaspalaute  (vantaa.fi)   tiketti KK-03056317

**Comment by jarmosaarikko** [comment]
Vapaaehtoistoiminnan  sv ja en vastineet  **frivilligverksamhet**  ja **voluntary activity**.  
- Wikidatassa vapaaehtoistyön en-vastine on **volunteering**.

Vastaava käsite JUPO:ssa https://finto.fi/jupo/fi/page/p3373

**Comment by mariaforsen** [comment]
Vapaaehtoistyö taitaa kyllä olla aivan yleisessä käytössä vielä, ks. esim. https://www.suomi.fi/kansalaiselle/oikeudet-ja-velvollisuudet/perusoikeudet-ja-vaikuttaminen/opas/vapaaehtoistyo https://fi.wikipedia.org/wiki/Vapaaehtoisty%C3%B6  
Googlehaku: "vapaaehtoistoiminta" n. 212 000 ja "vapaaehtoistyö" n. 501 000

**Comment by fantsby-m** [comment]
Ehdotuksen perustelun mukaan "[k]ukaan vapaaehtoistoiminnan toimijoista ei puhu enää työstä asian yhteydessä". Googlehaku kuitenkin osoittaa toisin (ks. yllä), samoin vaikkapa tämä:
https://vapaaehtoistyo.fi/fi/ ja monet kansalaisjärjestöjen sivut (esim. SPR, WWF, Pelastusarmeija...)

**Comment by YSO-kokous** [comment]
**Päätös:** Ei muutosta.
