### ISSUE TITLE
Konginkankaan kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9696]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Konginkankaan kirkko 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkorakennukset](http://www.yso.fi/onto/yso/p25) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[91 Arkkitehtuuri](http://www.yso.fi/onto/yso/p26552) 

#### Perustelut ehdotukselle   

Kuvailu 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Kongintaival: Konginkankaan kirkko 150 v 

**Ehdottajan organisaatio:** KK **Termiehdotus Fintossa:** [Konginkankaan kirkko](http://finto.fi/yse/fi/page/Y509696)

**Comment by mariaforsen** [comment]
Sv. Konginkangas kyrka

**Comment by jarmosaarikko** [comment]
WD: http://www.wikidata.org/entity/Q17315740
