### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9697]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[DOI](http://www.yso.fi/onto/ysa/Y195412) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT digitaalinen objektien tunnistejärjestelmä 

#### Ehdottajan organisaatio   

Kansalliskirjasto 

#### Perustelut ehdotukselle   

-

**Comment by YSO-kokous** [comment]
**Päätös:** KT digitaalinen objektien tunnistejärjestelmä
