### ISSUE TITLE
tonaalisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9699]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tonaalisuus](http://www.yso.fi/onto/ysa/Y100912) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään toiseksi KT-muodoksi "sävellajisidonnaisuus" 

#### Perustelut ehdotukselle   

Tässä juuri Marcus Castrenin tonaalisuutta käsittelevää esitelmää kuunnellessa ja siinä "sävellajisidonnaisuus"-käsitteeseen törmänneenä… 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
Odotetaan Muusan kantaa

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.
