### ISSUE TITLE
tanssilaulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9705]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[tanssilaulut](http://www.yso.fi/onto/ysa/Y206818) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-muoto "tanssimusiikki" 

#### Perustelut ehdotukselle   

Tanssilaulut ovat nimenomaan tanssin säestykseen tarkoitettuja lauluja, joten sanasuhteen pitäisi heijastaa tätä. Koskee sekä SLM- että YSO-sanastoja. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
YSOssa kaikki _laulut_ ovat sävellysten alakäsitteenä ja musiikinlajit taiteenlajien hierarkiassa. Riittäkö RT-suhde?

**Comment by YSO-kokous** [comment]
RT suhde riittää

**Comment by MUUSA-kokous** [comment]
Kannatetaan RT-suhdetta.

**Comment by mirmaid** [comment]
SLM?

**Comment by mirmaid** [comment]
SLM:ssä lisätään yläkäsite.
