### ISSUE TITLE
monoteismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9707]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[monoteismi](http://www.yso.fi/onto/ysa/Y101983) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "yksijumalaisuus" 

#### Perustelut ehdotukselle   

. . 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jtuohini** [comment]
Ja unohtui ihan lähde ehdotetulle KT-muodolle: https://www.kielitoimistonsanakirja.fi/yksijumalaisuus

**Comment by YSO-kokous** [comment]
**Päätös:** KT "yksijumalaisuus"
