### ISSUE TITLE
polyteismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9708]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[polyteismi](http://www.yso.fi/onto/ysa/Y101984) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "monijumalaisuus" 

#### Perustelut ehdotukselle   

KT-muodon lähteenä esim. https://www.kielitoimistonsanakirja.fi/monijumalaisuus 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by YSO-kokous** [comment]
**Päätös:**  KT"monijumalaisuus"
