### ISSUE TITLE
aravajärjestelmä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9709]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aravajärjestelmä](http://www.yso.fi/onto/yso/p20358)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö lisätä ohjaustermiksi ARA-asunnot (tai tehdä siitä oma termi)? 

**Perustelut ehdotukselle**

Pelkkä aravajärjestelmä assosioituu lainaan, mutta järjestelmä sisältää myös vuokra-asuntoja: https://fi.wikipedia.org/wiki/Arava ja termiä on käytetty ARA-talojen yms. kuvailussa

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://termipankki.fi/tepa/fi/haku/arava-asunto

**Comment by YSO-kokous** [comment]
lisätään ohjausterminä ARA-asunnot KÄ aravajärjestelmä
