### ISSUE TITLE
ongelmakäyttäytyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#971]
#### Ehdotettu termi suomeksi

ongelmakäyttäytyminen
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[55 Psykologia](http://www.yso.fi/onto/ysa/ryhma_55)

**Luontipäivämäärä:** 22.10.2003

**Muokkauspäivämäärä:** 1.2.2013, 22.10.2003, 01.02.2013

**Voyager-id:** 127727

**Termiehdotus Fintossa:** [ongelmakäyttäytyminen](http://finto.fi/yse/fi/page/Y327727)

**Comment by mariaforsen** [comment]
Sv. problembeteende
