### ISSUE TITLE
manipulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9710]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[manipulaatio](http://www.yso.fi/onto/yso/p5616)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi ainakin? tähän termiin aivopesu ellei jopa omaksi asiasanaksi?
hjärntvätt
brainwashing

**Perustelut ehdotukselle**

käytetty vapaana terminä Melidassa, olisi tarvittu sisällönkuvailussa tässä teoksessa:  https://melinda.kansalliskirjasto.fi/byid/018064793

**Ehdottajan organisaatio**

Itä-Suomen yliopiston kirjasto

**Comment by mariaforsen** [comment]
Kannatan erillisenä terminä. https://id.kb.se/term/sao/Hj%C3%A4rntv%C3%A4tt
https://id.kb.se/term/sao/Manipulation%20%28psykologi%29

**Comment by mirmaid** [comment]
10 viitettä Melindassa. _Manipulaatio_-käsitettä on käytetty laajemminkin, esim. _Är resultatmanipulation ett tecken på inkommande konkurs? : en kvantitativ studie av finländska bolag_. Mutta jos puhutaan ihmisen manipuloinnista/aivopesusta, ovatko nämä mitenkään erotettavissa? Pitääkö manipulaatio-käsitettä jakaa jotenkin?

**Comment by ilona-x** [comment]
LCSH:

**Brainwashing** http://id.loc.gov/authorities/subjects/sh85016371
KT    Brain control
KT    Brain-washing
KT    Forced indoctrination
KT    Indoctrination, Forced
KT    Menticide
KT    Mind control
KT    Thought control

**Comment by jarmosaarikko** [comment]
eikö vanhastaan tuttu "aivopesu" sitten ohjaustermiksi?

**Comment by YSO-kokous** [comment]
Tutkitaan jaetaanko manipulaatio

**Comment by mariaforsen** [comment]
SAOssa https://id.kb.se/term/sao/Manipulation%20%28psykologi%29 ja lcsh-linkitys 
Manipulative behavior. Sen lisäksi https://id.kb.se/term/sao/Manuell%20medicin ja lcsh Manipulation (Therapeutics)

https://svenska.se/tre/?sok=manipulation&pz=1
Nationalencyklopedin: [manipulation](https://www-ne-se.ezproxy.vasa.abo.fi/uppslagsverk/encyklopedi/l%C3%A5ng/manipulation-(korrigering-av-felst%C3%A4llningar))
manipulation, justering, inom medicinen metod att med hjälp av speciella handgrepp korrigera förmodade felställningar i rörelseorganen för att därigenom lindra smärtor, speciellt i ryggen.
https://finto.fi/mesh/fi/search?clang=sv&q=manipul

YSOssa on jo myös manipulaatiohoito

Aika paljon tosiaan resultatmanipulering-viitteitä Melindassa, olisiko sille oma termi? Suomeksi se ei kuitenkaan näytä olevan "tulosmanipulaatio" tms. kun kyseessä on talous..

**Comment by mirmaid** [comment]
Toisaalta manipulaatio taloudessa tulee joskus aika lähelle psykologian manipulaatiota: https://www.mtvuutiset.fi/artikkeli/finanssivalvonta-huolissaan-osakekurssien-manipuloinnista-sosiaalisessa-mediassa-kehottaisin-varovaisuuteen-jotta-ei-joudu-tutkinnan-kohteeksi/8091902

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään määrite _manipulaatio (psykologia)_, ohjaustermiksi _aivopesu_.

Tutkitaan, mikä on soveltuvin termi talousaineistoille.

_Manipulaatio (hoitomenetelmät)_ KÄ _manipulaatiohoito_.

_Manipulointi (psykologia)_ KÄ _manipulaatio (psykologia)_.

**Comment by fantsby-m** [comment]
[Täällä ](https://trepo.tuni.fi/handle/10024/92135)on hyvin määritelty tulosmanipulaatio ja jaettu se lailliseen ja laittomaan:

> Tulosmanipulaatio jakautuu kahteen osaan: tuloksenjärjestelyyn ja petolliseen taloudelliseen raportointiin. Tuloksenjärjestelyllä tarkoitetaan toimintaa, joka on laillista ja perustuu voimassa olevien säännösten antamiin mahdollisuuksiin. Petollisella taloudellisella raportoinnilla tarkoitetaan toimintaa, joka on laitonta ja rikkoo voimassa olevia säännöksiä.

**Comment by mirmaid** [comment]
^ Olisiko tämä _tulosmanipulaatio (talous)_? Tulosmanipulaatio ei tosiaan ole kovin käytetty, toinen vaihtoehto on ottaa _tuloksenjärjestely_ ja lähteä siitä, että yleensä kyse olisi laillisesta toiminnasta.

**Comment by mariaforsen** [comment]
Kannatan, myös ruotsiksi voi olla sekä laillinen että laiton.

Sv. resultatmanipulering (ekonomi) HT resultatmanipulation (ekonomi) 
https://finto.fi/yso/fi/page/p38248?clang=sv

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _tulosmanipulaatio (talous)_. Ohjaustermiksi _tuloksenjärjestely_.
