### ISSUE TITLE
papittaret

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9712]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

papittaret

**Ehdotettu termi ruotsiksi**

prästinnor

**Ehdotettu termi englanniksi**

priestesses

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tärkeä käsite aineistossa joka käsittelee antiikin ja muita ei-kristillisiä uskontoja 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551), [50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [papit](http://www.yso.fi/onto/yso/p5468)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Sacrae virgines : Studien zum religiösen und gesellschaftlichen Status der Vestalinnen / Alexander Bätz.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [papittaret](http://finto.fi/yse/fi/page/Y509712)

**Comment by mirmaid** [comment]
On KAUNOssa, tietoaineistossa Melindassa kerran.

**Comment by jarmosaarikko** [comment]
WD http://www.wikidata.org/entity/Q6116659
LCSH http://id.loc.gov/authorities/subjects/sh85147687 Women priests KT priestesses, ets. - kattaa myös muita uskontoja
