### ISSUE TITLE
autonomian aika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9713]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[autonomian aika](http://www.yso.fi/onto/ysa/Y94819) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCSH-asiasanastoon: "Finland--History--1809-1917"(http://id.loc.gov/authorities/subjects/sh85048379) 

#### Perustelut ehdotukselle   

Siltaus puuttuu vanhastaan, vaikka asiasana on aivan keskeinen Suomen historiaa käsittelevässä aineistossa. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
LCSH siltaus lisätty
