### ISSUE TITLE
joustavuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9714]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[joustavuus](http://www.yso.fi/onto/yso/p17703)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa ja yhteensovitettavissa niin että termi käytetään samalla tavalla sekä suomeksi että ruotsiksi (ks. myös eng.)

**Perustelut ehdotukselle**

YSO-kokouksessa käsitelty joustot ja huomauttu että myös joustavuus voi vaatia tarkennuksia. Sanastossa on tosin myös kimmoisuus (Kielitoimiston sanakirja: kappaleen kyky muuttaa muotoaan ulkoisten voimien vaikutuksesta sekä palautua jälleen alkuperäiseen tilaansa, joustavuus, elastisuus). 

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
Haastavaa löytää "oikea" englanninkielinen vastine käsitteelle
**joustavuus**, flexibilitet, resiliency (flexibility) KT elastisuus, joustot (joustavuus), elasticitet, elasticity
- flexibility on nyt käsitteessä "[notkeus](http://www.yso.fi/onto/yso/p25081)", vighet
- elasticity (physical properties) on käsitteessä "[kimmoisuus](http://www.yso.fi/onto/yso/p15864)", spänst
- resilience on käsitteessä "[resilienssi](http://www.yso.fi/onto/yso/p25253)", resiliens
- plasticity on käsitteessä "[plastisuus](http://www.yso.fi/onto/yso/p16566)" (eli muovautuvuus), plasticitet
- pliability on vapaana, mutta se on lähinnä "taipuisuus" (ei ysossa)
- stretchiness samoin, mutta tarkoittanee "venyvyys" (ei ysossa)

Wikidatassa 
- "**joustavuus**" https://www.wikidata.org/wiki/Q4161341  - ei ole fyysinen ominaisuus vaan "yrityksen ominaisuus, joka kertoo siitä, miten yritys pystyy sopeutumaan kysynnässä tapahtuviin määrällisiin ja laadullisiin muutoksiin"
-  **elasticity** alias plasticity https://www.wikidata.org/wiki/Q51992182   - "ability to stretch, deform, expand or contract one's body into any form imaginable"  - tämä viittaa henkilöihin/supersankareihin!

Collins dictionary: [elasticity](https://www.collinsdictionary.com/dictionary/english/elasticity)
- The **elasticity** of a material or substance is its ability to return to its original shape, size, and condition after it has been stretched.
- Synonyms: flexibility, suppleness, plasticity, give [informal] 

MOT/Oxford Thesaurus - synonyms for **elasticity**:
- stretchiness, flexibility, pliancy, suppleness, rubberiness, plasticity, resilience, springiness

MOT Kielitoimiston sanakirja
- "**joustavuus**" kts. "joustava" -- perään, myöten antava, taipuisa, kimmoisa, elastinen, notkea, sulava.
- "**kimmoisuus**" -- kappaleen kyky muuttaa muotoaan ulkoisten voimien vaikutuksesta sekä palautua jälleen alkuperäiseen tilaansa, joustavuus, elastisuus.
- "**elastisuus**" -- kimmoisuus, joustavuus, jousto.
- MOT sanakirjoissa joustavuus ja kimmoisuus saavat samat englanninkieliset termit eli ovat käytännössä synonyymejä.  

Ratkaisuehdotus:  YHDISTÄMINEN TAI 
1) Vaihdetaan kimmoituus vastineeksi "elastic resilience", spänst  (eng-lähde [MOT](https://www.sanakirja.fi/english-finnish/elastic%20resilience)) 
2) merktiään  joustavuuden vastineeksi "elasticity", elasticitet

**Comment by mariaforsen** [comment]
Riippuu tosiaan mistä on tarkoitus käyttää.. Elasticitet ei nyt toimi vastineena joustavuudelle kun se on käytetty paljon muustakin Melindassa kuin "jonkin objektin fyysisestä joustavuudesta", ks. https://svenska.se/tre/?sok=elasticitet&pz=1 ja https://sv.wikipedia.org/wiki/Elasticitet 

Osa Melinda-viitteistä näyttää siltä että ruotsiksi oikea olisi resiliens (nyt fi. resilienssi YSOssa) https://www.psykologiguiden.se/psykologilexikon/?Lookup=resiliens 

Joustavuus käytetty siis n. 1200 kertaa Melindassa, ja suurempi osa näistä eivät ole elasticitet:iä. Sen sijaan nykyinen vastine flexibilitet sopii, ainakin jotenkin, merkittävään osaan Melinda-viitteistä. Flexibilitet "kyky sopeutua", ks. https://svenska.se/tre/?sok=flexibilitet&pz=1 ja vrt myös https://sv.wikipedia.org/wiki/Flexibilitet

**Comment by mirmaid** [comment]
Törmäsin kimmoisuutta tutkiessa muutamiien erikoisiin tapauksiin: https://melinda.kansalliskirjasto.fi/byid/013831599, https://melinda.kansalliskirjasto.fi/byid/004010406. 

Jos puhutaan materiaaleista tai anatomiasta, on kyllä aika haastavaa sanoa milloin tarkalleen ottaen pitäisi puhua kimmoisuudesta ja milloin joustavuudesta, ja pitäisikö elastisuuden ohjata näihin molempiin - aineistot ovat monesti englanniksi ja niissä käytetty elasticity. Pääsisikö tässä liikkeelle sitä kautta, missä aineistoissa _flexibilitet_ ei sovellu? Jos tilanne jää nykyiselleen, tässä tapauksessa voisi tarkenteista olla hyötyä elastisuus-ohjaustermissä.

**Comment by mariaforsen** [comment]
Tuossa matematiikan aineistossa taitaa olla kyseessä ainakin ruotsin kannalta elasticitet:istä, eli YSOssa https://finto.fi/yso/sv/page/p3204 ?

Nyt kun katsoo Melindan viitteitä niin tulee mieleen ettemme välttämättä pääse lähempään vastaavuuteen ainakaan ruotsin osalta. Mutta onko eng. termi paras mahdollinen [resiliency (flexibility)](https://finto.fi/yso/fi/page/p17703?clang=en) ?

**Comment by mirmaid** [comment]
^Tuon siirtolaisuus-aineiston on pakko olla jonkun muun kielen tuoma virhe, koska suomeksi on vaikea käsittää miten siirtolaiset voisivat olla kimmoisia. Ymmärrän nyt sen matematiikan (ehkä tullut ennen tarkenteita), mutta onko spänst vain fysikaalinen?

**Comment by mirmaid** [comment]
Eli tämä _joustavuus_ ratkeaisi siis englannin termimuodon korjauksella?

**Comment by mariaforsen** [comment]
En siis ainakaan näe miten voisi ratkea millään muulla tavalla, jos ei lisätä tarkenteita? Kimmoisuus on muuten sv. spänst (kyllä, on fysikaalinen), eli se on yhtä virheellinen tuossa pakolaisuusviitteessä kuin suomeksikin. https://svenska.se/tre/?sok=sp%C3%A4nst&pz=1

**Comment by ilona-x** [comment]
> Törmäsin kimmoisuutta tutkiessa muutamiien erikoisiin tapauksiin: https://melinda.kansalliskirjasto.fi/byid/013831599

Löysin tuon artikkelin (Why they are not refugees : Climate change, environmental degradation and population displacement) kokotekstin, ja siinä näyttäisi olevan kyse resilienssistä https://siirtolaisuus-migration.journal.fi/article/download/89696/48979/143516

Korjasin tuon Melinda-viitteen.

**Comment by mirmaid** [comment]
Eng. yksi harkittava vaihtoehto myös flexibility (adaptability)

**Comment by YSO-kokous** [comment]
**Päätös**

Tarkistetaan englannin termimuoto, ei muita muutoksia.
