### ISSUE TITLE
kohdentaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9715]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kohdentaminen](http://www.yso.fi/onto/yso/p1032)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa? Sanastossa on myös kohdentuminen  (ja allokointi)

**Perustelut ehdotukselle**

Merkityskenttä erilainen ruotsiksi (fokusointi)? Kielitoimiston sanakirja: kohdentaa=suunnata oikein; kohdistaa (eri kohteisiin), allokoida

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Onko kohdentuminen mahdollisesti poistettavissa (käytetty 90 kertaa)? On hyvin vaikea kääntää järkevästi.

**Comment by mirmaid** [comment]
Vain kolme kertaa samoissa viitteissä. Tämä on kyllä varsin hankala, koska suomeksi nämä eivät usein ole korvattavissa toisillaan: esim. https://helda.helsinki.fi/handle/10138/135821 äitiysvapaat nimenomaan _kohdentuvat_ tiettyihin yrityksiin (joissa työskentelee tietyn ikäisiä naisia), eikä niitä aktiivisesti _kohdenneta_ niihin. Jos samaa eroa ei ole tehtävissä ruotsiksi, tulee suomeksikin sitten vääriä termejä tietueisiin. _Kohdentuminen ja kohdentaminen_ -tyyppinen termi olisi kyllä jo vähän absurdi.

**Comment by mariaforsen** [comment]
Nykyinen vastine voi tarkoittaa hyvin monenlaisia asioita, mutta ei sitä mitä tässä varmaan lähinnä haetaan, koska sellaista vastaavaa "passiivista" käsitettä ei ole ruotsiksi, esim. yllä mainittu äitysvapaiden kohdentumista. Antaako tuo "kohdentuminen" hirveästi lisäarvoa asiasanana noissa tietueissa, vai onko se käytetty lähinnä koska otsikossa on sana kohdentuminen? Näyttää siltä että myös aika eri merkityksissä käytetty, esim. "Hiihtokeskusten kohdekuvat vertailussa : tapaus: Saariselkä, Levi, Ylläs, Ruka ja Pyhä-Luosto / Virpi Kuismin."

**Comment by mirmaid** [comment]
Jos tarkastellaan aktiivista _kohdentamista_, niin soveltuuko _fokusering_ nykyisiin Melindan viitteisiin (n. 200)? Ja onko niin, että fokusering ei sovellu missään passiivisessa merkityksessä, vaan on aina jonkun aktiivisesti tekemää? (Koska siis kohdentaminen sisältää sen aktiivisen merkityksen, eli ei saisi tulla mihinkään missä tapahtuu jotain "itsestään".)

**Comment by mirmaid** [comment]
Hauskaa kyllä näyttää siltä, että kohdentuminen olisi toisinaan korvattavissa käsitteellä _jakautuminen_ :smile:.

**Comment by mariaforsen** [comment]
Kyllä, näyttää siltä ett fokusering toimii noissa viitteissä yhtä hyvin kuin suomeksikin. Toki monesti aika mitäänsanomaton asiasanana, mutta ei ainakaan virheellinen. (Osa viitteistä kuvailtaisiin ehkä  ruotsiksi termillä "riktande" tms. jos aivan ruotsiksi kuvailisi katsomatta suomenkielistä vastinetta jne.) Onko esimerkkejä jostain passiivisesta merkityksestä..? Vähän vaikeaa ruotsin kannalta miettiä kun ei tehdä tuollaista samanlaista eroa kuin suomeksi.

**Comment by mirmaid** [comment]
^ Eli ainakaan noissa _kohdentuminen_-aineistoissa ei toivottavasti sovi _fokusering_? Joissakin tapauksissa niistä suomeksikin myös aktiivinen tulkinta on mahdollinen, mutta enimmäkseen ei.

**Comment by mariaforsen** [comment]
Aika suuri osa viitteistä näyttää olevan otsikoita missä lukee kohdentuminen, en näkisi kuvailijana syytä (eikä tulisi mieleen) laittaa termiä fokusering noihin.

**Comment by mirmaid** [comment]
Eli tässä ilmeisesti toivottu (ja ainoa mahdollinen?) ratkaisu olisi _kohdentuminen_-termin poisto ja korvaaminen tietueissa (92 x Melindassa) yksitellen jollain muulla termillä (saatavuus, jakautuminen, valikoituminen, kohderyhmät tms., usein ei mitään). Tämän jälkeen ilmeisesti kohdentaminen olisi ok?

**Comment by YSO-kokous** [comment]
**Päätös**

Tehdään Mirjan yllä olevan ehdotuksen mukaisesti.
