### ISSUE TITLE
ravinnonotto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9716]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ravinnonotto](http://www.yso.fi/onto/yso/p16138)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaanko?

**Perustelut ehdotukselle**

Ks. myös issue absorptiosta, jos imeytyminen (ravitsemus) lisätään sanastoon ohjausterminä, niin se on osittain päällekkäinen tämän termin kanssa? Ruotsiksi tämä on näringsupptag, eikä rajaudu esim. vain kasveihin (termi on ryhmässä 15)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Käytetty Melindassa 40 kertaa, eniten kasveista ja kaloista, jonkin verran myös muista eläimistä ja joitakin kertoja ihmisestä (tuntuu yleensä näissä virheelliseltä).

**Comment by mariaforsen** [comment]
Eli mikä termi YSOssa on tarkoitus käyttää kun kyseessä on ihmisten "ravinnonotto"? Kun ruotsiksi se on nyt nimenomaan tämä (näringsupptag), ja se käy yhtä hyvin muiden eläinten ja kasvien kohdalla.

**Comment by mirmaid** [comment]
Mun on helpointa ymmärtää ravinnonotto juuri kasveilla ja hyvin alkeellisilla eläimillä, eli miten ne ottavat ravintoa aika passiivisesti ympäristöstä. Sitten kun puhutaan vaikka kaloista, niin kai viitataan siihen, miten kala "syö", mutta esim. nisäkkäiden osalta ei tunnuta käyttävän tätä termiä kuvaamaan mitä tai millä tavalla eläimet syövät. Ihmisistä puhuttaessa tosiaan ravinnonotto viittaamassa siihen, minkä verran tai mitä syö tuntuu suomeksi ihan vieraalta, koska siitä tulee sellainen mielikuva, että ottaisi ravintoa ikäänkuin puolivahingossa ympäristöstään.

**Comment by mirmaid** [comment]
Englanniksi käännetty nutrient uptake (ei food/feed intake), ja vaikuttaa rajautuvan kasveihin.

**Comment by ilona-x** [comment]
suomeksi ravinteidenotto /ravinteiden otto tuottaa  Googlella enemmän tuloksia 

---

IATE4
fi        ravinteiden otto
sv       absorption av näringsämnen;
näringsämnesupptag
en      absorption of nutrients

Luokitus: natural and applied sciences
AGRICULTURE, FORESTRY AND FISHERIES
Luotettavuus: ★★★☆
 
Lähde:IATE 10.08.2021, Euroopan unioni (1246462) https://termipankki.fi/tepa/fi/haku/ravinteidenotto

**Comment by ilona-x** [comment]
Ja ihmisten osalta tätä ehkä kuvailisi jotenkin tähän tapaan: syöminen & ruoka & ravintoaineet & imeytyminen

**Comment by ilona-x** [comment]
Tämä MOTista löytynyt auttaa ehkä hahmottamaan tuota ruotsinkielisen termin kattamaa settiä:

MOT Ruotsin tekniikka ja kauppa; ru-su
näringsupptagning
ravinnon otto, lannoitteenottokyky, **kehon kyky käyttää hyväkseen ravintoa**

**Comment by jarmosaarikko** [comment]
Olisiko  ehkä ihmisellä/eläimillä [ravinnonsaanti](http://www.yso.fi/onto/yso/p10827) ja kasveilla [ravinnonotto ](http://www.yso.fi/onto/yso/p16138)?

**Comment by LeKorsu** [comment]
> Olisiko ehkä ihmisellä/eläimillä [ravinnonsaanti](http://www.yso.fi/onto/yso/p10827) ja kasveilla [ravinnonotto ](http://www.yso.fi/onto/yso/p16138)?

Elli tulisiko näihin kahteen tarkenteet selkeyden vuoksi: ravinnonsaanti (ihmiset ja eläimet) ; ravinnonotto (kasvit)?

Absorptioon ja sen päällekkäisyyteen en tässä yhteydessä ota kantaa.

**Comment by YSO-kokous** [comment]
**PÄÄTÖS**
ravinnonotto (kasvit)  KT ravinteiden otto
