### ISSUE TITLE
hevonen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9717]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hevonen](http://www.yso.fi/onto/yso/p501)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: villihevonen, kesyhevonen, vai uusina termeinä?

**Perustelut ehdotukselle**

Hevosen alalajeja

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
En tiedä oikein villihevosesta - ainakin jos kyse on przewalskinhevosesta tai tarpaanista niin olisi varmaan parempi käyttää tarkkaa termiä, ei pelkkää _hevonen_ (?).

**Comment by YSO-kokous** [comment]
Hyväksytään kesyhevonen KÄ hevonen
