### ISSUE TITLE
markkerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9719]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[markkerit](http://www.yso.fi/onto/ysa/Y140799) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö biomarkkerit olla erikseen tai päätermi? 

#### Perustelut ehdotukselle   

IVD-applicable biomarkers : best practices and pitfalls in commercializing 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mariaforsen** [comment]
Kannatan erillisenä terminä.
https://termipankki.fi/tepa/fi/haku/markkeri
https://termipankki.fi/tepa/fi/haku/biomarkkeri

**Comment by mirmaid** [comment]
Sanastossa on lisäksi _merkkiaineet_, http://www.yso.fi/onto/yso/p17476.

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Biomarker

Käytännössä _markkerit_-termillä kuvailluissa varmaan lähes aina on kyse biomarkkereista, ja pelkkä markkerit on vähän epäselvä suhteessa merkkiaineisiin ja yleensäkin mistä kaikesta voi käyttää. 

Kielitoimiston sanakirja: markkeri: tekn., lääk., ark. merkkiaine.

**Comment by YSO-kokous** [comment]
Vaihdetaan päätermi markkerit KÄ biomarkkerit
