### ISSUE TITLE
Azazelin rukous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9721]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[Azazelin rukous](http://www.yso.fi/onto/ysa/Y189545) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Ehdotettu poistoa 

#### Perustelut ehdotukselle   

Viittaa teokseen, käytetty vain kerran.

**Comment by YSO-kokous** [comment]
Hyväksytään poistettavaksi
