### ISSUE TITLE
ekologinen kriisi / ekokriisi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9722]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ekologinen kriisi / ekokriisi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Sanastossa on ilmastokriisi, mutta ei laajempaa käsitettä ekokriisi tai ekologinen kriisi, joka kattaa sekä ilmastokriisin, kuudennen massasukupuuton että muun käsillä olevan ympäristötuhon. Ekologista kriisiä käsitellään todella monissa aineistoissa tätä nykyä. YSO:n käsite ekokatastrofit ei sovi kuvaamaan tätä laajaa kokonaisuutta, vaan viittaa yksittäisiin katastrofeihin. Tällä hetkellä joutuu käyttämään montaa eri käsitettä kuvatakseen tätä ilmiötä, kun sen voisi kuvata yhdellä täsmällisellä käsitteellä.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kriisit](http://www.yso.fi/onto/yso/p6173)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ilmastokriisi](http://www.yso.fi/onto/yso/p39413)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Todella monen erin. Esim. Zen and the art of saving the planet. 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [ekologinen kriisi / ekokriisi](http://finto.fi/yse/fi/page/Y509722)

**Comment by jarmosaarikko** [comment]
Wikidata: https://www.wikidata.org/wiki/Q2382319 ecological crisis

**Comment by mirmaid** [comment]
Viime kokouksessa tosiaan tämä lisättiin ohjaustermiksi: ekokriisit KÄ ekokatastrofit https://github.com/Finto-ehdotus/YSE/issues/9233. Kuvailussa ei oikein voi pitää periaatteena, että laaja ilmiö pitäisi pystyä kuvaamaan yhdellä käsitteellä, kun hakijat voivat kuitenkin etsiä aineistoa myös muilla termeillä. Jos hakijalla on valittavana sekä _ekokatastrofit_ että _ekokriisi_, epäilen vähän, ettei ero tunnu selkeältä, eikä ehkä kaikille kuvailijoillekaan.

**Comment by mariaforsen** [comment]
Sv. ekologiska kriser

**Comment by jarmosaarikko** [comment]
eikö kriisi tule ennen katastrofia eli ei ole sama käsite? Kun ollaan katastrofissa, kriisivaihe on jo ylitetty?
Kielitoimiston sanakirja:
- **kriisi** - kärjistynyt, vaarallinen tilanne, käänne(kohta), murros.
- **katastrofi** - tuhoisa tapahtuma, (suur)onnettomuus, romahdus, tuho.

**Comment by FinMeSHienPaimentaja** [comment]
> eikö kriisi tule ennen katastrofia eli ei ole sama käsite? Kun ollaan katastrofissa, kriisivaihe on jo ylitetty? Kielitoimiston sanakirja:
> 
> * **kriisi** - kärjistynyt, vaarallinen tilanne, käänne(kohta), murros.
> * **katastrofi** - tuhoisa tapahtuma, (suur)onnettomuus, romahdus, tuho.

Suomeksi varmaankin juuri niin. Molemmat ovat kreikkalaisperäisiä sanoja. "Katastrofi" - alaspäin kääntyminen/meno, vrt. voimakas vesiputous, jota ei voi pysäyttää. "Kriisi" (-> "kriittinen") valinnan/harkinnan paikka/kohta/hetki, suomeksi "käännekohta" käynee monesti myös hyvin.

**Comment by YSO-kokous** [comment]
Päätös: Ei muutosta. Edelleen vain yksi käsite:  ekokriisit KÄ ekokatastrofit
