### ISSUE TITLE
massasukupuutot (tai kuudes massasukupuutto)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9723]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

massasukupuutot (tai kuudes massasukupuutto)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

mass extinctions

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Nykyinen termi sukupuuttoon kuoleminen kuvastaa paremmin yksittäisten lajien sukupuuttoon kuolemista kuin meneillään olevaa massasukupuuttoa (= kuudes sukupuutto), joka kaipaisi spesifiä termiä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh2009010754)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Monenkin, mutta esim. nyt Zen and the art of saving the planet. 

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [massasukupuutot (tai kuudes massasukupuutto)](http://finto.fi/yse/fi/page/Y509723)

**Comment by mirmaid** [comment]
Melindassa kerran _sukupuuttoaalto_.
https://fi.wikipedia.org/wiki/Joukkosukupuutto

**Comment by ilona-x** [comment]
Tieteen termipankki: **sukupuuttoaalto** (en: mass extinction) https://tieteentermipankki.fi/wiki/Biologia:sukupuuttoaalto

**Comment by fantsby-m** [comment]
GEOssa on _massasukupuutot_: http://www.yso.fi/onto/gtk/GTK2015ID2307

**Comment by mariaforsen** [comment]
Sv. massutdöenden

**Comment by YSO-kokous** [comment]
Hyväksytään **massasukupuutot** , muut ohjaustermeiksi.
