### ISSUE TITLE
aktiivisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9724]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[aktiivisuus](http://www.yso.fi/onto/yso/p15704)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitääkö jakaa? Myös fysiikan/kemian alueella. 

**Perustelut ehdotukselle**

Myös määritelty: "ydinmuutosten lukumäärä tiettynä aikavälinä jaettuna tällä aikavälillä" ja "termodynaaminen suure, joka ilmaisee aineen, esimerkiksi katalyytin vaikuttavan konsentraation tai intensiteetin tietyssä kemiallisessa systeemissä" Sopiiko sama termi ihmistieteiden alueella?

**Ehdottajan organisaatio**

**Comment by fantsby-m** [comment]
Esimerkkejä hauista, miten termiä on käytetty:
_Aktiivisuus_ + _termodynamiikka_ ei Melindassa.
_Aktiivisuus_ + _lämpöoppi_ ei Melindassa.
_Aktiivisuus_ + _aurinko_ 57 kertaa Melindassa.
Jonkin verran myös esim. liittyen kemiaan tai lääkesuunnitteluun.

**Comment by mirmaid** [comment]
Kaiken kaikkiaan n. 1400 kertaa Melindassa.

**Comment by mirmaid** [comment]
Tässä ei kai ainakaan suomen ja ruotsin välillä ole eroa merkityskentässä. Käytetty ihmisten fyysisestä ja psyykkisestä aktiivisuudesta, yksilön tai ryhmän aktiivisuudesta jonkin elämänalueen tms. aihealueen suhteen (äänestysaktiivisuus, aktiivimallin edellyttämä työttömän aktiivisuus, innovaatiotoiminnan aktiivisuus Euroopassa, metsänomistajien aktiivisuus). 

Ihmisten lisäksi aktiivisuus sopii tietysti muihin eläimiin, tähtiin, proteiineihin, katalyytteihin jne. Toisaalta onko ihmisen aivojen fysiologinen aktiivisuus lähempänä metsänomistajien aktiivisuutta metsiensä hyödyntämisessä, kuin proteiinien aktiivisuutta? Alkuperäisen ehdotuksen määritelmät ovat täältä: https://termipankki.fi/tepa/fi/haku/aktiivisuus. Jos tätä lähdetään jakamaan, tuskin myöskään kaikki muuhun kuin ihmisen toimintaan liittyvä aktiivisuus on kuitattavissa yhdellä tai kahdella uudella käsitteellä, mutta onko se siis tarpeen vai voiko aktiivisuus jäädä 00-ryhmän yleistermiksi?

**Comment by mariaforsen** [comment]
Ainoa ongelma ruotsiksi taitaa olla se että aktivitet voi olla periaattessa myös "aktiviteetti", eli mahdollisesti pitäisi lisätä tarkenne > aktivitet (egenskaper=ominaisuudet) tms. ? Jos tämä suomeksikin rajautuu ominaisuuteen, kuten yläkäsite antaa ymmärtää?

**Comment by mirmaid** [comment]
Mietinkin tuota englannin osalta, siinä sama aktiviteetti-merkitys olemassa. Suomeksi tätä ei ole, vaan kyse on aina jonkin ominaisuudesta.

**Comment by LeKorsu** [comment]
Minä kannatan yleiskäsitteeksi 00 jättämistä.  Ja jos ruotsiksi on ok laittaa tarkenne perään, en näe tarvetta jakaa.

**Comment by YSO-kokous** [comment]
### Päätös
Ei jaeta. lisätään tarkenteet ruotsiksi ja englanniksi. Jätetään yleiskäsitteeksi.

**Comment by mariaforsen** [comment]
Tarkenne ei näytä olevan käytännössä (ks. Melinda) tarpeellinen ruotsiksikaan.
