### ISSUE TITLE
esiintymistaito

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9725]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[esiintymistaito](http://www.yso.fi/onto/yso/p565)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi: esiintymiskyky

**Perustelut ehdotukselle**

synonymi

**Ehdottajan organisaatio**

**Comment by YSO-kokous** [comment]
Päätös: KT esiintymiskyky
