### ISSUE TITLE
aluevaalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9727]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

aluevaalit

**Ehdotettu termi ruotsiksi**

välfärdsområdesval

**Ehdotettu termi englanniksi**

county elections

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarvitaan sisällönkuvailussa esim. oikeusministeriössä

**Ehdotettu yläkäsite YSOssa (LT)**

 [vaalit](http://www.yso.fi/onto/yso/p3225)

**Ehdotetut temaattiset ryhmät**

 [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

ministeriöiden viestintä

**Ehdottajan organisaatio**

oikeusministeriö
**Termiehdotus Fintossa:** [aluevaalit](http://finto.fi/yse/fi/page/Y509727)

**Comment by fantsby-m** [comment]
Tästä tulee varmasti aineistoa kun ensimmäiset aluevaalit on pidetty.

**Comment by fantsby-m** [comment]
Nyt sanastossa on _maakuntavaalit_ - joita ei sitten koskaan järjestettykään, asiasanaa on kuitenkin jonkin verran käytetty Melindassa.

**Comment by ilona-x** [comment]
YSOon otettiin maakuntavaalit v. 2018 https://github.com/Finto-ehdotus/YSE/issues/964 
tarvitaanko molemmat erikseen vai pitäisikö muuttaa maakuntavaalit KÄYTÄ aluevaalit? 🤔 

https://fi.wikipedia.org/wiki/Suomen_aluevaalit

**Comment by mariaforsen** [comment]
Ruotsinnoksen kannalta on tärkeää että merkityskenttä on selvä - eli onko kyseessä mitkä tahansa aluevaalit, vai nimenomaan hyvinvointialuevaalit. Varmasti meillä pitääkin olla sanastossa nämä ensi vuonna tulevat vaalit. 
Ks. myös https://fi.wikipedia.org/wiki/Suomen_aluevaalit

**Comment by ilona-x** [comment]
Oikeusministeriön ylläpitämällä Vaalit.fi -sivustolla:  suomeksi **aluevaalit**, ruotsiksi **välfärdsområdesval** ja englanniksi **county elections**
https://vaalit.fi/aluevaalit

**Comment by YSO-kokous** [comment]
Päätös: muutetaan maakuntavaalit käsitteen päätermi:   
aluevaalit KT  maakuntavaalit, hyvinvointialuevaalit

Lisättävä huomautus, että rajautuu hyvinvointialueiden vaaleihin.
Englanninkielisen termin tarrkenteena voisi olla (Finland)
Tarkistetaan termi Ahvenanmaan osalta.

**Comment by mariaforsen** [comment]
Sv. välfärdsområdesval HT områdesval, landskapsval
https://www.finlex.fi/sv/esitykset/he/2020/20200241.pdf
https://vaalit.fi/sv/valfardsomradesval
