### ISSUE TITLE
fintech

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9728]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fintech

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

fintech, FinTech

**Tarkoitusta täsmentävä selite**

Fintech-ala koskee sähköisiä finanssi-/pankkipalveluita.

**Perustelut ehdotukselle**

Fintech/FinTech(Financial technology) on ajankohtainen finanssimaailman termi, jota käsitellään paljon finassialan julkaisuissa. Fintech-alalle on syntynyt huomattava määrä yrityksiä, jotka tarjoavat asiakkaille uusia mahdollisuuksia talletuksiiin, maksupalveluihin ja luottoasioihin.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

 rahoitusteknologia, finanssiteknologia

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

FinTech strategy : linking entrepreneurship, finance, and technology; China's fintech explosion : disruption, innovation, and survival; Understanding cybersecurity management in FinTech : challenges, strategies, and trends; Banking 5.0 : how fintech will change traditional banks in the 'new normal' post pandemic  

**Ehdottajan organisaatio**

Turun yliopiston kirjasto
**Termiehdotus Fintossa:** [fintech](http://finto.fi/yse/fi/page/Y509728)

**Comment by fantsby-m** [comment]
Finanssivalvonnan sivuilla näin:
https://www.finanssivalvonta.fi/fintech--finanssialan-innovaatiot/

Sanastoon _finanssiteknologia_ ja ohjaustermiksi _FinTech_ (ja _financial technology_)?

**Comment by mirmaid** [comment]
_Finanssiteknologia_ 2 kertaa Melindassa. Googlella myös _rahoitusteknologia_. Luulin ensin että tämä on jotain suomalaista teknologiaa :facepalm:.

**Comment by ilona-x** [comment]
IATE2
fi        FinTech ★★★☆;
finanssiteknologia ★★☆☆;
rahoitusteknologia ★★★☆;
fintech ★★★☆
sv       fintech ★★★☆;
finansteknik ★★★☆
en      financial technology ★★★☆;
FinTech ★★★☆
  
Lähde: IATE 10.08.2021, Euroopan unioni (3566568)
https://termipankki.fi/tepa/fi/haku/fintech

**Comment by mariaforsen** [comment]
Sv. finansiell teknologi HT finansteknik, fintech
https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/finansiell-teknologi
https://sv.wikipedia.org/wiki/Fintech

**Comment by YSO-kokous** [comment]
Hyväksytään rahoitusteknologia  KT finanssiteknologia, FinTech
