### ISSUE TITLE
augustinolaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9729]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

augustinolaiset 

#### Ehdotettu termi englanniksi   

Augustinians 

#### Ehdotettu termi ruotsiksi   

augustiner 

#### Assosiatiiviset (RT)   

[sääntökunnat](http://www.yso.fi/onto/yso/p1003) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006394715 ja muita 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa tarkkaa asiasanaa; tarvitaan Teologisen tiedekunnan asiasanaston lakkauttamisen myötä. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [augustinolaiset](http://finto.fi/yse/fi/page/Y509729)

**Comment by mirmaid** [comment]
Melindassa muutamia kertoja sekä _augustinolaiset_ että _augustinolaisuus_. Eikö _sääntökunnat_ voi olla YK? Olisiko _dominikaanit_ tämän ST?

**Comment by LeKorsu** [comment]
Mitään asiasta tietämättä (tai googlaamatta), ovatko dominkaanit (ja fransiskaanit ym) enemmän RT kuin ST? Sääntökunnat varmaankin tosiaan YK.

**Comment by jarmosaarikko** [comment]
https://en.wikipedia.org/wiki/Augustinians - tämä on ihan ryhmänsä.  
- Katso esim. tämä pitkä lista: https://en.wikipedia.org/wiki/List_of_religious_institutes, jossa Augustinian on yksi ryhmistä sarakkeessa "Family".

**Comment by mariaforsen** [comment]
Sv. augustiner HT augustinorden, augustinerorden
