### ISSUE TITLE
taivaaseenastuminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9730]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

taivaaseenastuminen 

#### Ehdotettu termi englanniksi   

ascension 

#### Ehdotettu termi ruotsiksi   

himmelfart 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa. Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/002538353 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [taivaaseenastuminen](http://finto.fi/yse/fi/page/Y509730)

**Comment by mariaforsen** [comment]
Sv. himmelsfärd..? https://sv.wikipedia.org/wiki/Himmelsf%C3%A4rd Termi riippuu myös siitä rajataanko Jeesuksen taivaaseenastumiseen ks. https://fi.wikipedia.org/wiki/Jeesuksen_taivaaseenastuminen Kannatan laajempana.

**Comment by mirmaid** [comment]
Kerran Melindassa, Neitsyt Marian taivaaseenastumisesta.

**Comment by jarmosaarikko** [comment]
Taivaaseenastuminen - myös Enok ja Elia.  Wikipedian mukaan sama käsite myös muissa uskonnoissa.

**Comment by mariaforsen** [comment]
Sv. himmelsfärd
