### ISSUE TITLE
fariseukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9731]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[fariseukset](http://www.yso.fi/onto/ysa/Y185591) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde "toimintaan liittyvä rooli" --> "juutalaiset" sekä tarkistetaan RT-suhteiden tarve ja koko termin muoto ("farisealaiset" vai "fariseukset" ~ "farisealaisuus" yms). 

#### Perustelut ehdotukselle   

Fariseukset eivät ole jokin rooli, vaan juutalaisuuden yhden koulukunnista (farisealaisuus) jäseniä. Vrt. "The Pharisees [- -] were a social movement and a school of thought in the Levant during the time of Second Temple Judaism. After the destruction of the Second Temple in 70 CE, Pharisaic beliefs became the foundational, liturgical, and ritualistic basis for Rabbinic Judaism." 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Vrt. myös https://github.com/Finto-ehdotus/YSE/issues/9684, katsotaanko nämä historialliset ryhmät juutalaisten alakäsitteeksi? Muoto voisi ehkä olla paremmin _farisealaiset_, kuten wikipediassa, tosin _fariseukset_ selkeästi käytetyin.

**Comment by YSO-kokous** [comment]
Lisätään ohjaustermeiksi farisealaisuus, farisealaiset KÄ fariseukset
