### ISSUE TITLE
vanhakatoliset kirkot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9732]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vanhakatoliset kirkot 

#### Ehdotettu termi englanniksi   

Old Catholic Church 

#### Ehdotettu termi ruotsiksi   

gammalkatolska kyrkor 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kirkkokunnat](http://www.yso.fi/onto/yso/p938) 

#### Assosiatiiviset (RT)   

[roomalaiskatolinen kirkko](http://www.yso.fi/onto/yso/p15408) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85094530> 
Wikidata : https://www.wikidata.org/wiki/Q5169816 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

YSO:ssa ei vanhastaan sopivaa asiasanaa. Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000463958 ja muita 

#### Tarkoitusta täsmentävä selite   

Joukko kirkkokuntia, jotka ovat erkaantuneet roomalaiskatolisesta kirkosta ja joista osa kuuluu Utrechtin unioniin (= "Vanhakatolinen kirkko" yhteisönä, yksikössä, tämä asiasanaehdotus kuitenkin monikossa, kun viittaa sekä tämän unionin jäsenkirkkoihin että sen ulkopuolella oleviin). 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [vanhakatoliset kirkot](http://finto.fi/yse/fi/page/Y509732)

**Comment by mirmaid** [comment]
Kerran Melindassa tässä muodossa, joitakin kertoja myös _vanhakatolisuus_.
https://fi.wikipedia.org/wiki/Vanhakatolinen_kirkko

**Comment by YSO-kokous** [comment]
Hyväksytään vanhakatoliset kirkot KT vanhakatolisuus

**Comment by mariaforsen** [comment]
Sv. gammalkatolska kyrkor HT gammalkatolicism
