### ISSUE TITLE
airsoft

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9733]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[airsoft](http://www.yso.fi/onto/ysa/Y164040) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

KT softaus 

#### Perustelut ehdotukselle   

- 

#### Ehdottajan organisaatio   

Kauno-kokous

**Comment by YSO-kokous** [comment]
Päätös: KT softaus
