### ISSUE TITLE
koira

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9734]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[koira](http://www.yso.fi/onto/ysa/Y96272) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Pitäisikö lemmikkieläimille (tai muuten tavallista hakijaa kiinnostaville eläimille) lisätä monikkomuotoisia ohjaustermejä. 

#### Perustelut ehdotukselle   

KAUNO-ontologiassa eläinlajien nimiä ollaan muuttamassa monikkoon, koska fiktioaineistossa osin yksikölliset ja osin monikolliset muodot eläimistä aiheuttavat hämmennystä. Mietittiin kuitenkin, onko hakijalle hankalaa se, että tietoaineistoa pitää osata hakea eri logiikalla.

**Comment by mariaforsen** [comment]
Myös SAOssa monikossa (koira ei ole laji, vaan suden "muoto")

**Comment by jarmosaarikko** [comment]
Yksikkö-monikko muutos tiettyjen käsitteiden osalta ei ole yksinkertainen:
Samakantaisissa eliöiden nimisssä laji on yleensä yksikössä ja lajiryhmät monikossa. 
Esim. varis - varikset, yksikössä se viittaa meillä havaittavaan lintulajiin jälkimmäinen viittaa yleensä varis-suvun lajeihin tai yksilöihin. YSOssa onkin tämän vuoksi lisätty tarkenteita varis (laji) - varikset (suku).

Koiran kohdalla monikko onkin ohjausterminä, lajiryhmä on "**koiraeläimet**". 
Yksikössä termi vittaa alalajiin _Canis lupus familiaris_  Linnaeus, 1758. Tunniste: http://tun.fi/MX.291296.  Erikseen on monenlaisia assosiatiivisia termejä  esimerkiksi käyttötarkoituksen mukaan.   Ei silti liene tarpeen erottaa biologista eläinlajia omaksi käsitteekseen?

On varmaan tarpeen, että YSO-pohjaisissa ontologioissa käsitteiden nimeämisessä linjaukset olisivat yhtenäisiä.

**Comment by YSO-kokous** [comment]
Kouno-ryhmälle pohdittavaksi vielä hyödyttääkö hakijaa Yleisten kirjastojen aineistoissa, että monikkomuodot ovat mukana tai onko haittaa, jos eri sanastoista samasta käsitteestä toisessa yksikkö ja toisesta monikko.

**Comment by mirmaid** [comment]
YSOon nyt lisätty joitakin tavallisia lemmikkieläimien monikkomuotoja.
