### ISSUE TITLE
ympäristönhoitajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9736]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

ympäristönhoitajat

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ammatti johon kouluttaudutaan
https://eperusteet.opintopolku.fi/#/fi/esitys/1742262/naytto/sisalto/1744047
https://www.vyl.fi/tietopankki/koulutus/perustutkinto/ymparistonhoitaja/
https://smy.fi/ammattinimikkeet/11121/
https://www.oph.fi/fi/koulutus-ja-tutkinnot/ammatilliset-perustutkinnot

**Ehdotettu yläkäsite YSOssa (LT)**

 [ammatit](http://www.yso.fi/onto/yso/p1179)

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ympäristönhoito](http://www.yso.fi/onto/yso/p3162)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. Opetushallituksen laatima "Luonto- ja ympäristöalan perustutkinto : ympäristöalan koulutusohjelma..."

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [ympäristönhoitajat](http://finto.fi/yse/fi/page/Y509736)

**Comment by mirmaid** [comment]
5 viitettä Melindassa (yksi näistä yksikössä).

**Comment by mariaforsen** [comment]
Sv. miljövårdare HT naturvårdare (yrken)
https://www.finlex.fi/sv/laki/alkup/2011/20110003
https://www.framtid.se/yrke/naturvardare
https://termipankki.fi/tepa/fi/haku/ymp%C3%A4rist%C3%B6nhoitaja
https://svenska.se/tre/?sok=naturv%C3%A5rdare&pz=1
https://svenska.se/tre/?sok=milj%C3%B6v%C3%A5rdare&pz=1

**Comment by jarmosaarikko** [comment]
ehdotus: environmental managers KT environment managers, environment carers
