### ISSUE TITLE
luontokato

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9737]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

luontokato

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

biodiversity loss

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Merkittävä aikanamme kaikkeen liittyvä ilmiö, jonka kuvailemiselle ei ole mitään käsitettä. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [biodiversiteetti](http://www.yso.fi/onto/yso/p5496)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. Saario, Jakosuo ja Koutaniemi: Rakkauskirjeitä luonnolle

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [luontokato](http://finto.fi/yse/fi/page/Y509737)

**Comment by mirmaid** [comment]
2 viitettä Melindassa.
https://en.wikipedia.org/wiki/Biodiversity_loss

Myös _lajikato, biodiversiteettikato_.

**Comment by ilona-x** [comment]
IATE3
fi        biologisen monimuotoisuuden köyhtyminen;
biodiversiteetin väheneminen;
biologisen monimuotoisuuden väheneminen;
luontokato;
luonnon monimuotoisuuden väheneminen;
luonnon monimuotoisuuden köyhtyminen;
biodiversiteetin köyhtyminen

sv       minskning av biologisk mångfald;
förlust av biologisk mångfald

en      biodiversity erosion;
loss of biodiversity;
erosion of biodiversity;
biodiversity loss;
loss of biological diversity

Lähde:  IATE 10.08.2021, Euroopan unioni (1174843)
https://termipankki.fi/tepa/fi/haku/luontokato

**Comment by mariaforsen** [comment]
Sv. förlust av biologisk mångfald, biodiversitetsförlust, naturförlust..? Tärkeä käsite, mutta tutkittava/mietittävä millä termillä parhaiten kuvataan ilmiötä.

**Comment by mirmaid** [comment]
Tämä tuli vastaan eilen töistä lähtiessäkin, https://www2.helsinki.fi/fi/tiedekulma.

**Comment by YSO-kokous** [comment]
Hyväksytään luontokato KT biodiversiteettikato, lajikato

**Comment by mariaforsen** [comment]
Sv. förlust av biologisk mångfald HT förlust av biodiversitet, biodiversitetsförlust, naturförlust, minskning av biologisk mångfald, artförlust, minskad biodiversitet
