### ISSUE TITLE
urheiluyläkoulut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9739]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

urheiluyläkoulut

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vastaa urheilulukioiden toimintaa.
https://www.olympiakomitea.fi/huippu-urheilu/urheiluakatemiaohjelma/ylakoulutoiminta/urheiluylakoulu/
Urheiluyläkoulutoiminnan tavoitteena on oppilaitosten, seurojen ja urheiluakatemian suunnitelmallisella yhteistyöllä mahdollistaa noin 20 tunnin viikoittainen liikkumisen, harjoittelun ja urheilun kokonaismäärä. Urheiluyläkoulut mahdollistavat tästä kokonaismäärästä noin 10 tuntia liikuntaa ja harjoittelua kouluviikon yhteydessä urheiluseurojen ja urheiluakatemian kanssa tiiviissä yhteistyössä. Urheiluyläkoulujen toimintaa ohjaavat urheilijaksi kasvamisen sisältösuositukset.

**Ehdotettu yläkäsite YSOssa (LT)**

 [yläkoulu](http://www.yso.fi/onto/yso/p21292)

**Ehdotetut temaattiset ryhmät**

 [57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554), [97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [urheilulukiot](http://www.yso.fi/onto/yso/p7426)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://kihuenergia.kihu.fi/tuotostiedostot/julkinen/2020_rou_sujuukoark_sel98_36065.pdf

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [urheiluyläkoulut](http://finto.fi/yse/fi/page/Y509739)

**Comment by mirmaid** [comment]
Melindassa kerran yksikössä.

**Comment by mariaforsen** [comment]
Sv. idrottshögstadier
