### ISSUE TITLE
otteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#974]
#### Ehdotettu termi suomeksi

otteet
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[00 Yleistermit](http://www.yso.fi/onto/ysa/ryhma_00)

**Luontipäivämäärä:** 22.10.2003

**Muokkauspäivämäärä:** 22.10.2003, 16.12.2008

**Voyager-id:** 127732

**Termiehdotus Fintossa:** [otteet](http://finto.fi/yse/fi/page/Y327732)

**Comment by mirmaid** [comment]
Ehdotettu muototerminä 16.1.2018

**Comment by mirmaid** [comment]
Lajityyppi- ja muotosanastoon otettiin _katkelmat_ KT otteet.
