### ISSUE TITLE
uudistava maatalous

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9741]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

uudistava maatalous 

#### Vastaava käsite muussa sanastossa   

Wikipedia : https://en.wikipedia.org/wiki/Regenerative_agriculture 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

9781603587631 

**Ehdottajan organisaatio:** Helsingin kaupunginkirjasto **Termiehdotus Fintossa:** [uudistava maatalous](http://finto.fi/yse/fi/page/Y509741)

**Comment by fantsby-m** [comment]
https://carbonaction.org/fi/ensiesittelyssa-uusi-termi-regeneratiivinen-maatalous/

https://luomuinstituutti.fi/mita-uutta-regeneratiivisen-eli-uudistavan-maatalouden-keinovalikoima-tarjoaisi-luonnonmukaiselle-maataloudelle/

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by fantsby-m** [comment]
Myös _regeneratiivinen viljely_ tai _hiiliviljely_:
https://www.proagriaoulu.fi/fi/regeneratiivinen-viljely-vaatii-uudenlaista-ajattelua/

https://fi.wikipedia.org/wiki/Hiiliviljely
_Hiiliviljely_ ei ehkä kata kokonaan samaa asiaa.

**Comment by mirmaid** [comment]
_Kestävä maatalous_ on sanastossa, _hiiliviljely_ ei.

**Comment by fantsby-m** [comment]
_Kestävä maatalous_ varmaankin sopisi aineistoon, mutta se ei kerro täsmällisemmin että kyse on maaperän kunnon palauttamisesta tai parantamisesta (tms.).

**Comment by fantsby-m** [comment]
Tuolla vielä lisää:
https://carbonaction.org/wp-content/uploads/2021/02/BSAG_CA_Regeneratiivinen-maatalous_FI_202101.pdf

**Comment by mariaforsen** [comment]
Sv. regenerativt jordbruk/lantbruk?

**Comment by LeKorsu** [comment]
Entä jos/kun uudistavasta maataloudesta tulee jossain vaiheessa yleisesti harjoitettavaa maataloutta? Vähän epämääräinen, jättäisin toistaiseksi termiehdotukseksi.

**Comment by mirmaid** [comment]
_Eri  tahojen  laatimissa  uudistava  maatalous  -termin  määritelmissä  on  jonkin  verran  vaihtelua. Laajimmissa  näkemyksissä  se  pitää  sisällään  paitsi  maatalouden  ekosysteemit,  myös  sosiaalisen  kestävyyden  ja  eläinten  hyvinvoinnista  huolehtimisen  sekä  uusien  viljelijäsukupolvien  kasvattamisen.  Laajasti  tulkituissa  määritelmissä  uudistava  maatalous  voidaan  miltei  nähdä  rinnakkaisena  terminä  agroekologiselle  lähestymistavalle.  Toisessa  päässä  määritelmät  ovat  tiukasti rajaavia._ 

_Tarkasteltaessa  uudistavan  maatalousjärjestelmän  keskeistä  osa-aluetta,  maaperän  hoitoa,  voidaan  puhua  regeneratiivisesta  eli  uudistavasta  maanviljelystä.    Se  on  maaperän  kasvukuntoa  parantavaa,  ravinteita  kierrättävää,  maaperän  hiilivarastoa  kasvattavaa  ja  luonnon  monimuotoisuutta  edistävää  maanviljelyä.    Termiä  hiiliviljely  käytetään,  kun  halutaan  korostaa  uudistavien  viljelymenetelmien  maaperän  kuntoa  parantavia  ja  hiilivarastoa  kasvattavia  ominaisuuksia._

**Comment by mirmaid** [comment]
Tähän liittyviä käsitteitä sanastossa myös _agroekologia, maaperänsuojelu_. Googlella eniten _hiiliviljely_, sen jälkeen _uudistava maatalous_.

**Comment by mirmaid** [comment]
Ehdotuksen aineisto: https://www.adlibris.com/fi/kirja/dirt-to-soil-9781603587631

**Comment by ilona-x** [comment]
IATE4

fi        uudistava viljely;
regeneratiivinen viljely;
uudistava maatalous;
regeneratiivinen maatalous

en      regenerative agriculture;
regenerative farming
	  
Lähde: IATE 10.08.2021, Euroopan unioni (3591477)
https://termipankki.fi/tepa/fi/haku/uudistava%20maatalous;	

---

https://www.sitra.fi/hankkeet/uudistavan-viljelyn-e-opisto/
https://www.uudistavaviljely.fi/

**Comment by YSO-kokous** [comment]
Ei hyväksytä tässä vaiheessa. Odotetaan käsitteen vakiintumista

**Comment by AuHo22** [comment]
Myös termi uudistava viljely, raja kestävään maatalouteen on sen sijaan vaikeampi hahmottaa:

https://valtioneuvosto.fi/documents/1410837/178555033/Kest%C3%A4v%C3%A4+maatalous,+maaper%C3%A4n+hiilensidonta,+Liisa+Pietola.pdf/6e10dc2c-827b-163e-5f1e-12bb6e9292bb/Kest%C3%A4v%C3%A4+maatalous,+maaper%C3%A4n+hiilensidonta,+Liisa+Pietola.pdf?t=1695383479132
