### ISSUE TITLE
Edith Wapple

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9742]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Edith Wapple](http://www.yso.fi/onto/yso/p10588)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan käsitettä poistettavaksi sanastosta

**Perustelut ehdotukselle**

Tästä  ei löydy googlella muuta tietoa kuin YSOsta ja Onkista ja pari sillä asiasanoitettua kirjaa Finnasta (WAP)  MIkä tämä oikein on? Turhan eksoottinen YSOon.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jarmosaarikko** [comment]
Sanastossa on useita tällaisia käytöstä poistuneita ohjelmistoja, joista ei löydy tietoa netistä eikä löydy viittauksia Melindasta eli kuka enää tietää edes mitä ne ovat? Pitäisikö tieto tällaisista ohjelmista löytyä  asiasanojen avulla kirjastosta, vähintään Fennicasta tai Varastokirjastosta? Ellei löydy, niin nämä pitäisi poistaa tarpeettomina. 
- Kuka ehtisi käydä nämä läpi: http://www.yso.fi/onto/yso/p26592 - listalla on 300 arvoa.
- ellei käsitettä poisteta, niin voisiko ainakin harvinaisimpiin lisätä jonkinlaisen huomautuksen esimerkiksi valmistajasta tai käyttöjärjestemästä ja ehkä julkaisuvuoden?

**Comment by YSO-kokous** [comment]
Poistetaan Edith Wapple sanastosta.
