### ISSUE TITLE
roolipelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9744]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[roolipelit](http://www.yso.fi/onto/yso/p4295)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Roolipelit ->
liveroolipelit
pöytäroolipelit

**Perustelut ehdotukselle**

Roolipelit (Role-playing games, RPG) on hyvä yleiskäsite. Tämä jakaantuu alaluokkiin niiden toimintatapojen tai käytetyn median mukaan.  Liveroolipelit (Live action role-playing games, LARP) ovat toimintapainotteisia. Käsite ei kuitenkaan pidä sisällään pöytäroolipelejä. Pöytäroolipelit (Tabletop role-playing games, TRPG) ovat lähtökohtaisesti staattisempia, esimerkiksi pöytäroolipeli Dungeons & Dragons.

**Ehdottajan organisaatio**

Lapin yliopisto, Taiteiden tiedekunta Taidekasvatus

**Comment by jtuohini** [comment]
Eikö olisi helpompi ottaa sanastoon uusina käsitteinä **_liveroolipelit_** ja **_pöytäroolipelit_**, kumpikin nykyisen **roolipelit**-asiasanan ST-suhteisina? Näin ei tarvitsisi lähteä yksitellen tutkimaan nykyisiä tietueita ja tarkistamaan, kummasta missäkin tapauksessa on kyse.

**Comment by mariaforsen** [comment]
Sanastossa on jo liveroolipelit, ja hyvä niin, koska kyllähän nämä ovat aika eri asioita.

**Comment by fantsby-m** [comment]
Melindassa asiasanana _roolipelit_ 2356 kertaa, _roolipelit_ + _liveroolipelit_ 100 kertaa, pelkkä _liveroolipelit_ 31 kertaa. Olisiko mahdollista edes selvittää onko noissa yli 2000:ssa julkaisussa kyse pöytäroolipeleistä, liveroolipeleistä vai esimerkiksi molemmista?

**Comment by mirmaid** [comment]
Näyttäisi käytetyn myös digitaalisista peleistä 🤔.

**Comment by YSO-kokous** [comment]
Odotetaan SLM:n käsittelyä

**Comment by mirmaid** [comment]
Myös SLM:ssä on molemmat. Mitä kaikkea halutaan kuvailla termillä _roolipelit_? Jos sanastossa olisi erikseen myös _pöytäroolipelit_, miten _roolipelit_-termiä käytettäisiin? Onko tarvetta käyttää digitaalisten pelien yhteydessä?

**Comment by mirmaid** [comment]
Kysytään tähän peliasiantuntijoiden näkemystä.

**Comment by frosterus** [comment]
Roolipelit yläkäsitteenä, jonka alla liveroolipelit ja pöytäroolipelit kuulostaa minusta järkevältä. Yleisesti ottaen väittäisin, että jos kirja ei selkeästi määrittele itseään liveroolipeliksi niin lähes poikkeuksetta kyseessä on silloin pöytäroolipeli, eli kuvailijan kannalta tilanteen ei pitäisi olla hirveän hankala vaikka ei olisi aiheeseen perehtynytkään. Myös sellainen tilanne, jossa sama kirja kuvaa sekä liveroolipelin että pöytäroolipelin on äärimmäisen harvinainen (ei tule suorilta käsin yhtään mieleen ja aika hyvin tunnen alaa). Eli tältä kantilta tuo roolipelit jäisi ehkäpä vähälle käytölle jatkossa, mutta seuraavassa kappaleessa vielä tähän liittyvää pohdintaa.

Digitaaliset roolipelit onkin sitten aika eri olento, eli videopelirintamalla roolipeleiksi nimitetään nykyään jotakuinkin kaikkia pelejä, joissa pelihahmo kehittyy pelin edetessä jollain sellaisella tavalla, jossa pelaajalla on jotain päätäntävaltaa. Usein myös edellytetään, että pelihahmo voi tehdä valintoja käymänsä dialogin suhteen, mutta ei aina. Aiemmin roolipelit viittasivat aika rajattuun genreen, mutta nykyään tosiaan esimerkiksi uudempia Tomb Raider -pelejä tituleerataan roolipeleiksi. Jos halutaan, niin olisi mahdollista tehdä videopelien alle toimintapelien kaltaisesti tietokoneroolipelit (tjsp - CRPG on se tyypillinen lyhenne näistä eli computer role playing games), mutta ehkäpä tuo yläkäsite roolipelit kelpaisi tähän tarkoitukseen.

Roolipelit käsitteellä muuten näyttäisi olevan ruotsiksi altLabel LARP jonka pitäisi ehkä olla vain liveroolipeleissä?

**Comment by mariaforsen** [comment]
Ks. https://finto.fi/slm/fi/search?clang=fi&q=larppaus
Ruotsinkielinen ohjaustermi on todennäköisesti laitettu koska suomeksikin on ohjausterminä larppaus KÄYTÄ roolipelit? Eli jos suomeksikin poistetaan niin tehdään samalla tavalla ruotsiksi.

**Comment by mirmaid** [comment]
Renni Honkasen vastaus:
Käytännössä kirjastoaineistossa varmaankin 98% on pöytäroolipelejä. Oikeastaan tuo on vähän hassu tarkennus siinä suhteessa eikä anna hakijalle oikeastaan lisäinformaatiota. Yleensä pöytäroolipelit sisältävät ohjekirjoja, jotka ovat juuri niitä luetteloitavia ”kirjoja”.

Liveroolipelit tapahtuvat ”ulkona”, siis ihmisten kesken järjestetyissä tapahtumissa. Nämä ovat usein kertaluonteisia, suunniteltuja, tapahtumia joissa osallistujilla on omat roolinsa. Nämä sisältävät vielä enemmän eläytymistä hahmoon kuin pöytäpeleissä, vähän kuin näyteltäisiin vapaamuotoista näytelmää.

Luetteloitavaksi tulisi ohjeita miten tällaisia tapahtumia järjestetään jne, tai kertomuksia jo tapahtuneista sessioista. En itse ole juuri näihin törmännyt, varmasti näitä kuitenkin on.

”Pöytäroolipelit” asiasanan lisääminen ”roolipelit” asiasanan alle ei siis sinänsä anna juurikaan lisäarvoa, sen sijaan ”liveroolipelit” antaisi.

Roolipelejä voidaan pelata myös verkon yli, mutta käytännössä peli on edelleen yleensä pöytäroolipeli, se vaan käydään verkon yli yhden pelaajista ohjaamana.

Digitaalisissa peleissä löytyy myös elementtejä roolipeleistä, mutta näkemykseni mukaan ne eivät näitä ”roolissa pelaamisen” tunnusmerkkejä täytä. Roolipelaaminen on pitkälle sosiaalista pelaamista (juu kyllä pelikulttuurissa sitä muutenkin on tietty nykypäivänä paljon, tarkoitan tällaista fyysisempää läsnäoloa).

Jos luetteloitava teos on liveroolipelaamisesta, niin se kyllä mainittaisiin takakannessa. Jos tästä ei ole mainintaa, niin pöytäroolipeli se on.

**Comment by mirmaid** [comment]
SLM: korjataan larppaus > KÄ liveroolipelit. Palataan seuraavassa kokouksessa ehdotukseen.

**Comment by ilona-x** [comment]
SLM-sanastossa liveroolipelit ei ole tarpeellinen, poistetaan. / SLM-kokous 19.4.2022

Käytetty paljon tietokone-/konsolipeleistä, tarvittaisiinko oma termi näille esim. Wikipediassa https://fi.wikipedia.org/wiki/Tietokoneroolipeli 

SLM-sanastoon mahdollisesti:
**tietokoneroolipelit** ohjaustermi roolipelit (tietokonepelit?), roolipelit (konsolipelit?) yläkäsite digitaaliset pelit?
**pöytäroolipelit** ohjaustermi roolipelit (pöytäroolipelit?) yläkäsite pelit

Roolipelit -termi koettiiin ongelmalliseksi SLM-sanastossa, jos sinne lisätään suppeammat pöytäroolipelit ja tietokoneroolipelit.

YSOssa voisi olla liveroolipelit, pöytäroolipelit ja roolipelit + mahdollisesti lisättävä tietokoneroolipelit.

**Comment by mirmaid** [comment]
Kysytään vielä Renniltä, olisiko mahdollista poistaa roolipelit, ja ottaa genrekäyttöön pöytäroolipelit ja tietokoneroolipelit (jos jäisi pelkkä roolipelit, sitä helposti käytettäisiin edelleen molemmista, vaikka otettaisiin tietokoneroolipelit erikseen).

**Comment by mariaforsen** [comment]
SAOgenressä kaksi termiä, tietokoneella pelattavat ja https://id.kb.se/term/saogf/Rollspel
"Hit resurser som utgör rollspel i alla former förutom elektroniska spel (använd Rollspel (datorspel)). I rollspel ställs läsaren/spelaren inför olika val som kan leda berättelsen åt olika håll. Termen används för såväl solo- som gruppspel."

**Comment by mirmaid** [comment]
Jaetaan:
roolipelit (pöytäroolipelit) KT pöytäroolipelit
roolipelit (digitaaliset pelit) KT tietokoneroolipelit, digitaaliset roolipelit

**Comment by mariaforsen** [comment]
Sv. 
-rollspel (bordsrollspel) HT bordsrollspel, penna- och papper-rollspel
-rollspel (digitala spel) HT datorrollspel, digitala rollspel
https://id.kb.se/term/saogf/Rollspel%20%28datorspel%29
https://id.kb.se/term/saogf/Rollspel
https://sv.wikipedia.org/wiki/Datorrollspel
https://sv.wikipedia.org/wiki/Rollspel

**Comment by mirmaid** [comment]
YSO?

**Comment by YSO-kokous** [comment]
Jaetaan Mirjan ehdotuksen mukaisesti.
