### ISSUE TITLE
Academy Awards

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9746]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Academy Awards

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Academy Awards

**Tarkoitusta täsmentävä selite**

Oscar-palkintoja ja -palkittuja käsittelevä kirjallisuus, ym. aineisto. Myös Oscar-palkittujen elokuvien (videotallenteiden) huomioiminen asiasanalla. 

**Perustelut ehdotukselle**

Palkinnoista on YSO:ssa nyt lähinnä vain suomalaisia palkintoja, sekä Nobel-palkinnot. Oscarit ovat Nobeleiden lisäksi kansainvälisistä palkinnoista varmaankin ne, joita eniten seurataan ja jotka eniten kiinnostavat.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

 Oscar-palkinnot

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://Academy Awards (Motion pictures)), [fi.wikipedia.org](https://fi.wikipedia.org/wiki/Oscar-palkinto)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esimerkiksi Kinn, Gail: The Academy Awards : the complete unofficial history, 978-1-57912-986-6 (007221636/id)

**Ehdottajan organisaatio**

Tampereen kaupunginkirjasto
**Termiehdotus Fintossa:** [Academy Awards](http://finto.fi/yse/fi/page/Y509746)

**Comment by mirmaid** [comment]
Sanastossa on _elokuvapalkinnot_. Eikö tämä suomeksi olisi kuitenkin _Oscar-palkinto/-palkinnot_? (_Jussi-palkinto_ on yksikössä, samoin suurin osa muista palkinnoista, _Nobelin palkinnot_ monikossa.) Käytetty muutamia kertoja Melindassa sekä yksikössä että monikossa.

**Comment by mariaforsen** [comment]
Nationalencyklopedin: Oscar HT Academy Award

**Comment by jarmosaarikko** [comment]
WD: https://www.wikidata.org/wiki/Q19020 "Oscar-palkinnot", "Academy Awards" 
näitähän myönnetään kymmenittäin erilaisia joka vuosi.

LCSH http://id.loc.gov/authorities/subjects/sh85000301  "Academy Awards (Motion pictures)"
Akatemiapalkintoja on monta muutakin, siksi varmaan tarkenne

**Comment by YSO-kokous** [comment]
Hyväksytään Oscar-palkinnot  
Muutetaan muut vastaavaat palkinnot monikkomuotoon

**Comment by mariaforsen** [comment]
Sv. Oscar-priser HT Academy Awards, Oscars-priser
