### ISSUE TITLE
Braunschweig

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9753]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Braunschweig

**Ehdotettu termi ruotsiksi**

Braunschweig

**Ehdotettu termi englanniksi**

Brunswick

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kirjan ilmestymispaikka

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [wikidata](https://www.wikidata.org/wiki/Q2773)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://kansalliskirjasto.finna.fi/Record/fikka.3972235

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [Braunschweig](http://finto.fi/yse/fi/page/Y509753)

**Comment by mirmaid** [comment]
Testi

**Comment by fantsby-m** [comment]
Myös eng Braunschweig ohjaustermiksi

**Comment by jtuohini** [comment]
Vaatii tarkenteen, ettei sekoitu Braunschweigin herttuakuntaan (1915–1918), seuraajaansa Braunschweigin vapaavaltioon (1918–1946) tai muihin samannimisiin alueisiin, ks. https://de.wikipedia.org/wiki/Braunschweig_(Begriffskl%C3%A4rung).

**Comment by mirmaid** [comment]
Braunschweig (kaupunki)
