### ISSUE TITLE
pappiskoulutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9754]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[pappiskoulutus](http://www.yso.fi/onto/ysa/Y105922) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "pappeinkoulutus" tai otetaan jopa varsinaiseksi päätermiksi. KT-muodoksi voisi myös ottaa "koulutus papin työhön" 

#### Perustelut ehdotukselle   

Kyseistä ilmaista käytetään myös – ja on itse asiassa yksiselitteisempi (onko kyseessä pappien antama koulutus vai koulutus papin ammattiin?). 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by fantsby-m** [comment]
_Pappeinkoulutus_ Google-haku: 3 osumaa.
_Pappiskoulutus_: yli sata osumaa.
Eri taivutusmuodoissa vielä isompi ero.

**Comment by YSO-kokous** [comment]
Ei hyväksytty
