### ISSUE TITLE
basistit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9755]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[basistit](http://www.yso.fi/onto/ysa/Y113316) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään siltaus LCSH-asiasanaan "Bass guitarists" (http://id.loc.gov/authorities/subjects/sh90006160) sekä RT-suhde asiasanaan "kontrabasistit" 

#### Perustelut ehdotukselle   

Siltaus puuttuu; RT-suhde auttaa selkeyttämään "basistit"-sanan viittaamista nimenomaan bassokitaransoittajiin, ei kontrabasisteihin, joita puhekielessä myös nimitetään basisteiksi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Onko tämä selvä ilman tarkennetta? Ruotsiksi todennäköisesti ei, ks. https://svenska.se/tre/?sok=basist&pz=1
Kielitoimiston: "basisti: mus. (orkesterin) kontrabasson t. bassokitaran soittaja"
Wikipedia: "Basisti on henkilö, joka soittaa kontrabassoa, bassokitaraa, bassotorvea tai kosketinsoitinbassoa."

**Comment by fantsby-m** [comment]
Ei ole selvä suomeksikaan ilman tarkennetta.

**Comment by fantsby-m** [comment]
_Basisti_ tarkoittaa sekä sähköbasisteja että kontrabasisteja, olisi outoa rajata sana tarkoittamaan vain sähköbasson soittajia. Näin myös englannissa, ks. esim. https://en.wikipedia.org/wiki/Bassist.

**Comment by jarmosaarikko** [comment]
LCSH:ssa nämä ovat erikseen, molemmissa ohjaustermi **bassists** 
- Double bassists  http://id.loc.gov/authorities/subjects/sh85039173  -> kontrabasistit, tms. KT basistit
- Bass guitarists http://id.loc.gov/authorities/subjects/sh90006160 -> bassokitaristit KT basistit

Kun aihe selvästi aiheuttaa hämminkiä, niin pitäisikö meilläkin olla nämä molemmat?

**Comment by YSO-kokous** [comment]
Odotetaan Muusan kommenttia

**Comment by MUUSA-kokous** [comment]
Kannatetaan siltausehdotusta ja lisäksi termin muuttamista muotoon bassokitaristit. RT-suhde ei ole tämän jälkeen tarpeen.
Lisäksi seuraavat ohjaustermit:
bassokitaristit KT basistit (bassokitara)
kontrabasistit KT basistit (kontrabasso)

**Comment by YSO-kokous** [comment]
### Päätös
bassokitaristit KT basistit (bassokitara)
kontrabasistit KT basistit (kontrabasso)
Pelkkä "basistit" poistuu.

**Comment by mariaforsen** [comment]
Sv.
-basgitarrister HT elbasister, basister (basgitarr)
-kontrabasister HT basister (kontrabas)

Jfr https://id.kb.se/find?q=basister
