### ISSUE TITLE
tangot/metallitangot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9756]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

tangot/metallitangot 

#### Perustelut ehdotukselle   

- 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

SFS-käsikirja, Teräs. Tuotestandardit. Osa 1: Lanka- ja tankotuotteet sekä profiilit 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [tangot/metallitangot](http://finto.fi/yse/fi/page/Y509756)

**Comment by mariaforsen** [comment]
Sv. stänger/metallstänger? SAOL: smal cylindrisk an­ordning ofta med bärande funktion

**Comment by ilona-x** [comment]
Riittäisikö esimerkkiteoksen kuvailuun kuitenkin metallituotteet.

metallitangot ei Melindassa, & terästangot x 1 

LCSH: 
Bars (Engineering) http://id.loc.gov/authorities/subjects/sh85011971
alakäsitteitä mm. steel bars & plastic bars

--

Kielitoimiston sanakirja https://www.kielitoimistonsanakirja.fi/#/tanko?searchMode=all:

**tanko**
1. pitkänomainen, jäykkä, ohuehko, tav. määrätarkoitukseen tehty esine; vrt. sauva, seiväs, kanki, keppi, puikko.

- Terästanko.
- Lippu-, verhotanko.
- Ohjaus-, vaihdetanko.
- Laskea lippu puolitankoon ks. puolitangossa.
- Polkupyörän tanko miesten polkupyörän rungon vaakasuora osa.
- Istua [polkupyörän] tangolla.

2. harkkomaisista esineistä.

- Saippua-, suklaatanko.

**Comment by mirmaid** [comment]
^ Esimerkkiteoksessa oli erilaisia metallituotteita, joista muille oli tarkemmat termit sanastossa.

**Comment by YSO-kokous** [comment]
Hyväksytään metallitangot

**Comment by mariaforsen** [comment]
Sv. metallstänger
