### ISSUE TITLE
neuropsykiatrisia erityispiirteitä omaavat henkilöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9759]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

neuropsykiatrisia erityispiirteitä omaavat henkilöt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

Nepsyiksi lukeutuvat esimerkiksi henkilöt, joilla on diagnosoitu ADHD, ADD, autismikirjon häiriöt, kehityksellinen kielihäiriö tai Touretten oireyhtymä, myös aistiyliherkkyys liittynee tähän.

**Perustelut ehdotukselle**

Laajan nepsy-termin käyttö on yleistynyt vauhdilla myös kirjallisuudessa. YSOsta en löydä ihan vastaavaa termiä. Ehdottamaani asiasanaa näkee käytettävän nepsyn selityksenä, mutta ilmiön selvittämiseen tarvittaneen alan asiantuntijaa: mitkä nykyiset YSO-termit ovat suppeampia termejä, mitkä assosiatiivisiä jne. Esim. Artossa on kuvailtu termeillä neuropsykiatria ja erityisryhmät. Nepsy-lapsista puhutaan, miten löytyy kattavasti tietoa kirjastoista?

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 neuropsykiatriset erityispiirteet (?)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://finna.fi/Record/arto.013602074 

**Ehdottajan organisaatio**

Diakonia amk:n kirjasto, Hanna Saario
**Termiehdotus Fintossa:** [neuropsykiatrisia erityispiirteitä omaavat henkilöt](http://finto.fi/yse/fi/page/Y509759)

**Comment by jarmosaarikko** [comment]
YSOssa ei ole jaettu ihmisiä sairauksien mukaan ryhmiin, joten tämä on hieman hankala käsite. On esimerkiksi "autismi", muttei ole "autistit".   Tällä tavalla muodostettuna uutena käsitteenä voisi olla "**neuropsykiatriset erityispiirteet**" tai "neuropsykiatriset oireet".  Englanniksi esim. "neuropsychiatric features" tai "-characteristics" KT  "nepsy"

Onko nepsy jo niin laajasti käytössä, että voisi käyttää pääterminä? 
esim. https://naenepsy.fi/tietoa/ Näe nepsy.

Huom! sanastossa on jo käsite [neuropsykiatrinen valmennus](http://www.yso.fi/onto/yso/p26670) sekä [neuropsykologinen kuntoutus](http://www.yso.fi/onto/yso/p38574)
Wikipediassa [nepsy](https://en.wikipedia.org/wiki/NEPSY) on "neuropsykologinen testimenetelmä."

**Comment by mariaforsen** [comment]
Ehdotetussa muodossa hyvin vähän käytetty. En kannata leimaavia "ryhmänimityksiä" YSOon. Ruotsissa on nykyään aika tarkkaa että viitataan mieluummin "henkilöihin joilla on jokin sairaus/vamma tms.", kuin että leimataan tekemällä ryhmänimityksiä itse sairaudesta/vammasta, vrt. esim kehitysvammaiset=personer med utvecklingsstörning ALLFOssa.

**Comment by mirmaid** [comment]
_Neuropsykiatriset häiriöt_ olisi mahdollinen. _Nepsy_-muotoa käytetään viittaamaan sekä häiriöön/oireeseen, että henkilöihin. Se on mielestäni terminä aika neutraali, mutta epätarkkuudenkin vuoksi ehkä parempi ohjausterminä. Ehdotettu muoto ei ole sellaisenaan käytössä.

**Comment by mariaforsen** [comment]
Kannatan neuropsykiatriset häiriöt uutena terminä. SAOssa https://id.kb.se/term/sao/Neuropsykiatriska%20diagnoser

**Comment by YSO-kokous** [comment]
### Päätökset
Otetaan muodossa neuropsykiatriset häiriöt

**Comment by mariaforsen** [comment]
Sv. neuropsykiatriska störningar HT neuropsykiatriska diagnoser, neuropsykiatriska funktionsnedsättningar, neuropsykiatriska funktionsvariationer
https://id.kb.se/term/sao/Neuropsykiatriska%20diagnoser

**Comment by mirmaid** [comment]
Kirja: arki toimimaan
