### ISSUE TITLE
kaksiluonto-oppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9761]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kaksiluonto-oppi 

#### Ehdotettu termi ruotsiksi   

dyofysitism 

#### Ehdotettu termi englanniksi   

dyophysitism 

#### Vaihtoehtoiset termit ja ilmaisut   

dyofysitismi [fin] 
tvånatursläran [swe] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kristologia](http://www.yso.fi/onto/yso/p6748) 

#### Vastaava käsite muussa sanastossa   

Wikidata : https://www.wikidata.org/wiki/Q1991529 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/005718753 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [kaksiluonto-oppi](http://finto.fi/yse/fi/page/Y509761)

**Comment by mirmaid** [comment]
Yksiluonto-opin osalta päätermi on _monofysitismi_.
