### ISSUE TITLE
antisemitismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9762]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[antisemitismi](http://www.yso.fi/onto/ysa/Y94667) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "antijudaismi" 

#### Perustelut ehdotukselle   

https://fi.wikipedia.org/wiki/Antijudaismi ym. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT antijudaism

**Comment by jarmosaarikko** [comment]
https://en.wikipedia.org/wiki/Anti-Judaism
https://fi.wikipedia.org/wiki/Antijudaismi
https://fi.wikipedia.org/wiki/Antisemitismi

Wikipedia-artikkelin mukaan nämä olisivat hieman eri käsitteitä:
> _**Antijudaismi** on juutalaisen uskonnon ja sen harjoittajien vastustusta.  Antijudaismi on uskonnollisesti suuntautunutta, usein kristillistä, ja siten eroaa poliittisiin, rodullisiin ja kulttuurisiin ennakkoluuloihin perustuvasta antisemitismistä. Antijudaistisen ja antisemitistisen suhtautumistavan erottaminen käytännössä on kuitenkin hankalaa._
> _**Antisemitismi** eli juutalaisvastaisuus tarkoittaa vihamielistä suhtautumista juutalaisiin joko heidän juutalaisen uskonsa tai kansallisuutensa vuoksi._

**Comment by mirmaid** [comment]
Wikipediassa kuitenkinkin myös: _Antijudaistisen ja antisemitistisen suhtautumistavan erottaminen käytännössä on kuitenkin hankalaa._

**Comment by YSO-kokous** [comment]
### Päätös
Lisätään ehdotuksen mukaan ohjaustermiksi antijudaismi KÄYTÄ antisemitismi
