### ISSUE TITLE
maalipallo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9763]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

maalipallo

**Ehdotettu termi ruotsiksi**

goalball

**Ehdotettu termi englanniksi**

goalball

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Maalipallo on näkövammaisille suunniteltu joukkuepeli
https://fi.wikipedia.org/wiki/Maalipallo

**Ehdotettu yläkäsite YSOssa (LT)**

 [palloilu](http://www.yso.fi/onto/yso/p1930)

**Ehdotetut temaattiset ryhmät**

 [97 Liikunta. Urheilu](http://www.yso.fi/onto/yso/p26546)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://kihuenergia.kihu.fi/tuotostiedostot/julkinen/2019_hyr_miestenmaa_sel88_51104.pdf

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [maalipallo](http://finto.fi/yse/fi/page/Y509763)

**Comment by mariaforsen** [comment]
Sv. goalball HT målboll, blindboll, plingboll, goalboll

**Comment by jarmosaarikko** [comment]
LCSH
http://id.loc.gov/authorities/subjects/sh2014001920 Goalball
Wikidata
http://www.wikidata.org/entity/Q647559
