### ISSUE TITLE
fundamentaaliteologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9764]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

fundamentaaliteologia 

#### Ehdotettu termi ruotsiksi   

fundamentalteologi 

#### Ehdotettu termi englanniksi   

fundamental theology 

#### Ehdotettu yläkäsite YSOssa (LT)   

[dogmatiikka](http://www.yso.fi/onto/yso/p12684) 
[uskonnonfilosofia](http://www.yso.fi/onto/yso/p6225) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/009339837 ja muita 

#### Tarkoitusta täsmentävä selite   

"[D]en del av teologin som behandlar trossatsernas grundläggande sanningsproblem" (https://www.ne.se/uppslagsverk/encyklopedi/l%C3%A5ng/fundamentalteologi) 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [fundamentaaliteologia](http://finto.fi/yse/fi/page/Y509764)

**Comment by mirmaid** [comment]
Wikipedia: _Fundamentaaliteologia eli uskonnollisen ajattelun fundamentteja, perusteita ja edellytyksiä pohtiva ala. Siihen kuuluu muun muassa uskonnollisen kielen sekä uskonnollisen tiedon luonnetta ja mahdollisuutta koskeva pohdinta. Fundamentaaliteologia on hyvin lähellä uskonnonfilosofiaa ja on lähinnä teologian käyttämä erillinen nimitys uskonnonfilosofisista kysymyksistä, joilla on erityisen suuri merkitys dogmatiikalle. Fundamentaaliteologiasta käytetään joskus myös nimitystä prinsiippioppi._

**Comment by jarmosaarikko** [comment]
Wikidata: http://www.wikidata.org/entity/Q1004343 fundamental theology
Wikipedia: https://en.wikipedia.org/wiki/Fundamental_theology   YK katolinen teologia

LCSH menee jotenkin eri tavalla?
http://id.loc.gov/authorities/subjects/sh85134686 - Theology, Doctrinal KT Fundamental theology, Systematic theology
