### ISSUE TITLE
narratiivinen kritiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9765]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

narratiivinen kritiikki 

#### Ehdotettu termi englanniksi   

narrative criticism 

#### Ehdotettu termi ruotsiksi   

narrativ kritik 

#### Ehdotettu yläkäsite YSOssa (LT)   

[eksegetiikka](http://www.yso.fi/onto/yso/p9983) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh90003784> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

"A development in biblical studies, especially in USA, since about 1970. The main thesis is that readers (e.g. of the gospels) should read the narratives and respond to them as the authors hoped." (http://www.oxfordbiblicalstudies.com/article/opr/t94/e1308) 

#### Perustelut ehdotukselle   

Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/007318181 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [narratiivinen kritiikki](http://finto.fi/yse/fi/page/Y509765)

**Comment by krinay** [comment]
Rajautuuko käsite siis raamatuntutkimukseen? Onko se selvää ilman tarkennetta tms. eli rajaavatko hierarkia ja temaattinen ryhmä merkitystä riittävän selvästi? (LCSH https://id.loc.gov/authorities/subjects/sh99005442.html  ja https://id.loc.gov/authorities/subjects/sh90003784.html)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Narrative_criticism

Suomeksi tällä ei löydy kyllä oikein mitään, paitsi Melindasta.

**Comment by YSO-kokous** [comment]
#### Päätös
Selvitetään lisää.  Ehdotettu muotoa  narraatiokritiikki

**Comment by AuHo22** [comment]
Tarvitsisi mielestäni tarkenteen - raamatuntutkimus/eksegetiikka?

https://apowiki.fi/wiki/Narraatiokritiikki_(raamatuntutkimus) 
https://erepo.uef.fi/bitstream/handle/123456789/13157/urn_nbn_fi_uef-20140211.pdf?sequence=-1&isAllowed=y

**Comment by mirmaid** [comment]
Otettiin jo _muotohistoria (eksegetiikka)_ ja _redaktiokritiikki (eksegetiikka)_. Myös muoto _narraatiokritiikki_ tuo vain muutamia viitteitä Googlella.

**Comment by mariaforsen** [comment]
Suhde tähän? https://termipankki.fi/tepa/fi/haku/narratiivinen%20tutkimus

**Comment by YSO-kokous** [comment]
### Päätös
Selvitetään vielä sopiiko ohjausteminä.
narratiivinen kritiikki KÄYTÄ narratiivinen tutkimus

**Comment by mariaforsen** [comment]
Voisiko kysyä esim. tältä opettajalta: https://studies.helsinki.fi/opintotarjonta/cu/hy-CU-133961756-2021-08-01

**Comment by krinay** [comment]
Ei taida olla ihan selvä aihekokonaisuus tämä, ks. https://tieteentermipankki.fi/wiki/Monitieteisen_humanistisen_termity%C3%B6hankkeen_kokousmuistio_19032019 

Täällä pohditaan termejä _narratiivinen kritiikki_ ja _narratiivinen teologia_, joka (jälkimmäinen) muuten on jo YSOssa:
https://legendmakers.wordpress.com/2008/10/14/narratiivisen-teologian-maaritelmasta/ (teksti on kai kirjoitettu jo 15 vuotta sitten, joten en tiedä onko ajan tasalla)

YSOssa on monenlaista:
narratologia https://finto.fi/yso/fi/page/p10906
narratiivinen tutkimus https://finto.fi/yso/fi/page/p22220
narratiivinen psykologia https://finto.fi/yso/fi/page/p27796
narratiivinen teologia https://finto.fi/yso/fi/page/p25660
narratiivinen terapia https://finto.fi/yso/fi/page/p15932
(narratiivisuus https://finto.fi/yso/fi/page/p10164, kerronta https://finto.fi/yso/fi/page/p6895, kokemuskerronta https://finto.fi/yso/fi/page/p28953 yms.)

Mutta _narratiivinen kritiikki (eksegetiikka)_ olisi varmaan ihan selvä.

**Comment by mirmaid** [comment]
^ Vähän ehkä ketjumainen, mutta voidaan varmaan palata asiaan, jos tätä tarvitaan jossain muussa yhteydessä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään uusi käsite _narratiivinen kritiikki (eksegetiikka)_.

**Comment by mariaforsen** [comment]
Sv. narrativ kritik (exegetik) 
http://www.diva-portal.se/smash/get/diva2:817871/FULLTEXT01.pdf
https://www.diva-portal.org/smash/get/diva2:1634369/FULLTEXT01.pdf
