### ISSUE TITLE
ilmoitus (teologia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9766]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ilmoitus (teologia) 

#### Assosiatiiviset (RT)   

[ilmestykset](http://www.yso.fi/onto/yso/p29400) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

"Kristillisessä kielenkäytössä ilmoituksella tarkoitetaan yleensä sekä toimintaa, jossa Jumala paljastaa itsensä ihmiskunnalle, että sitä Jumalaa koskevaa tietoa, joka tästä Jumalan toiminnasta välittyy ihmisille." (https://sti.fi/luennot/files/NR020205.pdf) 

#### Perustelut ehdotukselle   

Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/013372529 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [ilmoitus (teologia)](http://finto.fi/yse/fi/page/Y509766)

**Comment by mariaforsen** [comment]
Onko ehdottomasti tarpeen yleissanastossa? Sv. uppenbarelse, mutta mikä tarkenne olisi tarpeeksi selkeä, jotta rajautuu samalla, hyvin suppealla tavalla? Sama ongelma todennäköisesti englanniksi? 
Ks. esim. Nationalencyklopedin uppenbarelse: "inom religionerna en gudomlig självmeddelelse från gudar, andar eller makter i en annan värld än vår"... "I kristet språkbruk betecknar uppenbarelsen Guds självmeddelelse till människorna, särskilt i Kristus, och det sakliga innehållet i denna." Eli suomeksi on kaksi eri termiä ilmoitus ja ilmestys, mutta ruotsiksi vain uppenbarelse.

**Comment by jarmosaarikko** [comment]
Kristinuskossa keskeisiä ovat "yleinen ilmoitus" (general revelation) ja "erityinen ilmoitus" (special revelation) 
- https://www.gotquestions.org/Suomi/yleinen-erityinen-ilmoitus.html  
- https://en.wikipedia.org/wiki/Special_revelation
- https://en.wikipedia.org/wiki/General_revelation (Natural revelation)

Kielitoimiston sanakirja: **ilmoitus c.** usk. se millä jumaluus ilmaisee itsensä ihmisille. **Jumalan pelastusilmoitus**.

Jos otetaan sanastoon, niin ehdotan muotoa "**Jumalan ilmoitus**". Ei ehkä rajaudu kristinuskoon - onko tämä sama käsite Islamissa? Kts. [Kalam](https://fi.wikipedia.org/wiki/Kalam) "_Kalamin lähtökohtana on Jumalan ilmoitus,_ "
Tällöin YK olisi varmaankin "uskontoon liittyvät abstraktit objektit"?

englanniksi  pelkkä "revelation" liitetään Jumalan ilmestyksiin, esim. Johanneksen ilmestys.

Lähikäsite http://www.wikidata.org/entity/Q3458440 "continuous revelation"
tai "divine revelation" (kts. [Economy of Salvation](https://en.wikipedia.org/wiki/Economy_of_Salvation)) - toisaalta tämä voidaan kääntää myös muodossa "jumalallinen ilmestys".

**Comment by YSO-kokous** [comment]
### Päätös
otetaan sanastoon muodossa Jumalan ilmoitus  OT ilmoitus (teologia)

**Comment by mariaforsen** [comment]
Sv. Guds uppenbarelse HT uppenbarelse (Guds)
