### ISSUE TITLE
liitto (teologia)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9768]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

liitto (teologia) 

#### Ehdotettu termi englanniksi   

Biblical covenents 

#### Vaihtoehtoiset termit ja ilmaisut   

Jumalan liitto 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2008101834> 
Wikidata : https://www.wikidata.org/wiki/Q1005024 

#### Perustelut ehdotukselle   

Tarvitaan Teologisen tiedekunnan kirjaston asiasanaston lakkauttamisen myötä. 

#### Tarkoitusta täsmentävä selite   

"The Hebrew Bible makes reference to a number of covenants (Hebrew: בְּרִיתוֹת‎) with God (YHWH). These include the Noahic Covenant (in Genesis), which is between God and all living creatures, as well as a number of more specific covenants with Abraham, the whole Israelite people, the Israelite priesthood, and the Davidic lineage of kings. In form and terminology, these covenants echo the kinds of treaty agreements in the surrounding ancient world." (https://en.wikipedia.org/wiki/Covenant_(biblical)). Ks. myös esim. https://rll.fi/2016/09/liitto/ 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/007017288 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [liitto (teologia)](http://finto.fi/yse/fi/page/Y509768)

**Comment by mariaforsen** [comment]
Sv. förbund (teologi) HT Guds förbund

**Comment by YSO-kokous** [comment]
### Päätös
Liitto (teologia) OT Jumalan liitto
hyväksytään, mutta tarvitsee määritelmän.
