### ISSUE TITLE
poliittinen ajattelu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#977]
#### Ehdotettu termi suomeksi

poliittinen ajattelu
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/ysa/ryhma_65)

**Luontipäivämäärä:** 22.10.2003

**Muokkauspäivämäärä:** 3.6.2005, 13.1.2004, 22.10.2003, 16.12.2008, 30.11.2009

**Voyager-id:** 127737

**Termiehdotus Fintossa:** [poliittinen ajattelu](http://finto.fi/yse/fi/page/Y327737)

**Comment by AuHo22** [comment]
YSOssa aiemmin hyväksyttyjä mm.

    kriittinen ajattelu
    matemaattinen ajattelu
    pedagoginen ajattelu
    tieteellinen ajattelu

Sopisi hyvin tähän termiperheeseen ja termille olisi myös tilauksensa, esim. teos: Havel, Václav, Euroopan toivo : esseitä ja puheita 1978-2002 

Eli poliitikkojen ja muiden politiikkaan tavalla tai toisella osallistuneiden yhteiskunnallisten vaikuttajien teoksissa hyödyllinen termi.

**Comment by AuHo22** [comment]
Teos Alpo Juntunen, Paasikivi : geopoliitikko ja Suomen kohtalon vuodet (2021) 
Kustantaja: "J. K. Paasikiven toiminta ja geopoliittinen ajattelu olivat ratkaisevia niin sodassa kuin rauhassa. Paasikivi rakensi nuoruudestaan lähtien omintakeista ajattelumallia tavoitteenaan Suomen aseman turvaaminen. Kirja kuvaa Paasikiven pohdintoja ja itsensä peliin laittamista niin rauhanneuvotteluissa, luotaessa itsenäiselle Suomelle ulkopolitiikkaa kuin ohjattaessa Suomea turvallisille vesille toisen maailmansodan jälkeen. Kirja osoittaa, että paasikiveläiselle realismille on yhä tarvetta."

**Comment by jarmosaarikko** [comment]
eng: political thought KT political thinking, political philosophy
- kuvailun kohde esim. https://finna.fi/Record/oy.99414133906252 The foundations of modern political thought
Mappaukset
- wd: poliittinen ajattelu https://www.wikidata.org/wiki/Q11499141
- wd: poliittinen filosofia https://www.wikidata.org/wiki/Q179805  --  ehkä sama kuin edellinen?
 - LCSH political science KT political thought, poltical theory, politics  http://id.loc.gov/authorities/subjects/sh85104440 
 - kts. myös Political science--Philosophy KT Political philosophy  http://id.loc.gov/authorities/subjects/sh88004669

**Comment by mirmaid** [comment]
10 viitettä Melindassa. Sanastossa on _poliittiset asenteet_.

**Comment by AuHo22** [comment]
Poliittiset asenteet -termiä käytetään yleensä tutkittaessa kansalaisten poliittista käyttäytymistä.

**Comment by mariaforsen** [comment]
Sv. politiskt tänkande

**Comment by AuHo22** [comment]
Saksan kansalliskirjastossa erilliset käsitteet mm. -> Albert Schweitzer als "homo politicus" : eine biographische Studie zum politischen Denken und Handeln des Friedensnobelpreisträgers / Thomas Suermann 
Asiasanoitus: -> Schweitzer, Albert ; Politisches Denken ; Nationalsozialismus ; Ost-West-Konflikt ; Atomkriegsgefahr ; Kolonialismus

Toisaalta esim. -> Le pervertissement totalitaire : la banalité du mal selon Hannah Arendt / Martine Leibovici et Anne-Marie Roviello
Asiasanoitus: Arendt, Hannah ; Politische Philosophie ; Totalitarismus ; Das Böse

**Comment by mariaforsen** [comment]
Sv. politiskt tänkande
