### ISSUE TITLE
k-pop (vai K-pop)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9770]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

k-pop (vai K-pop) 

#### Ehdotettu termi ruotsiksi   

k-pop 

#### Ehdotettu termi englanniksi   

K-pop (music) 

#### Ehdotettu yläkäsite YSOssa (LT)   

[popmusiikki](http://www.yso.fi/onto/yso/p2969) 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[89 Musiikki](http://www.yso.fi/onto/yso/p26571) 

#### Tarkoitusta täsmentävä selite   

LC:ssä on sekä K-pop (music) että K-pop (subculture). Pitäisikö saman tien ottaa ysoonkin molemmat? Ja myös slm:ään musiikkina. 

#### Perustelut ehdotukselle   

Kirjallisuutta alkaa ilmestyä, musiikkia on julkaistu jo pitkään. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Minja Mäkilä: K-pop : unelma huomisesta 

**Ehdottajan organisaatio:** Yle Arkisto **Termiehdotus Fintossa:** [k-pop (vai K-pop)](http://finto.fi/yse/fi/page/Y509770)

**Comment by asormune** [comment]
Onko K-pop genre? Vai onko se popmusiikkia/rockia tms? Ei taida vielä olla termejä esim. Suomirock, Brittirock. Luomispaikka ja kielikoodi genren lisänä on käytössä.

**Comment by MUUSA-kokous** [comment]
Kannatetaan lisäämistä YSOon isolla alkukirjaimella mutta ei toistaiseksi SLM:ään.

**Comment by mariaforsen** [comment]
Sv. K-pop HT koreansk pop

**Comment by mirmaid** [comment]
Alkuperäisessä ehdotuksessa erillisinä, mutta Muusa kannattanee vain yhtä käsitettä (musiikin hierarkiassa)?

**Comment by jarmosaarikko** [comment]
Wikidata: http://www.wikidata.org/entity/Q213665  K-pop
Wikipedia https://fi.wikipedia.org/wiki/K-pop
>"_Toisinaan K-popia suositellaan tarkasteltavaksi musiikkigenren sijaan kokonaan omana alanaan, sillä siihen liittyy tietynlaisen musiikkityylin lisäksi lukuisia ulkomusiikillisia piirteitä._ "

LCSH 
http://id.loc.gov/authorities/subjects/sh2019103591 "Popular music--Korea (South)"  KT "K-pop (Music)" (ComplexSubject)
http://id.loc.gov/authorities/subjects/sh2020006575 K-pop (Subculture)

**Comment by LeKorsu** [comment]
Ehdotuksen tekijänä minulle kelpaa hyvin yksi käsite musiikin hierarkiassa.

**Comment by YSO-kokous** [comment]
### Päätös
otetaan vain yksi käsite termillä K-pop

**Comment by MUUSA-kokous** [comment]
Määritelmäehdotus: Eteläkorealaisen popmusiikin ympärille kehittynyt osakulttuuri.
