### ISSUE TITLE
Antiikin Epeiros

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9771]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Antiikin Epeiros 

#### Ehdotettu termi ruotsiksi   

Epirus 

#### Ehdotettu termi englanniksi   

Epirus (Greece and Albania) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh85044434 
wikipedia : https://fi.wikipedia.org/wiki/Antiikin_Epeiros 

#### Tarkoitusta täsmentävä selite   

Antiikin Epeiros käsittää nykytermein ilmaistuna Kreikan luoteisen kulman ja eteläisen osan Albaniaa. (https://helda.helsinki.fi/handle/10138/335876) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1b30nf2/alma9934154637206253 

#### Perustelut ehdotukselle   

Tarvitaan kirjastoaineiston kuvailussa 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [Antiikin Epeiros](http://finto.fi/yse/fi/page/Y509771)

**Comment by ilona-x** [comment]
Eikö tämä tulisi yso-paikkoihin?

**Comment by mariaforsen** [comment]
Miksi antiikin? On edelleen olemassa.

**Comment by ilona-x** [comment]
LCSH:
[Epirus (Greece and Albania)](https://id.loc.gov/authorities/subjects/sh85044434)
[Ēpeiros (Greece)](https://id.loc.gov/authorities/names/n2012043475)

**Comment by ilona-x** [comment]
https://www.wikidata.org/wiki/Q565751

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Epirus

**Comment by mirmaid** [comment]
Epeiros, YK Kreikka, RT Albania
