### ISSUE TITLE
dogmihistoria

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9772]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[dogmihistoria](http://www.yso.fi/onto/ysa/Y184631) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "dogminkehitys" 

#### Perustelut ehdotukselle   

Teologian asiasanastossa käytetty muoto, joka on hyvä saada "talteen" sanaston poistuessa käytöstä. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT dogmutveckling

**Comment by mirmaid** [comment]
Dogmihistoria varmaankin tutkii dogminkehitystä? Dogminkehitys tuo vain 4 tulosta Googlella ja niistäkin yksi on Teologian sanasto.

**Comment by YSO-kokous** [comment]
### Päätös
lisätään dogminkehitys KÄYTÄ dogmihistoria
