### ISSUE TITLE
Metsäpeuran maa

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9773]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Metsäpeuran maa](http://www.yso.fi/onto/yso/p3450)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan tai  muutetaan päätermiksi "Peuran polku", jonka YK: retkeilyreitit. 
Jos päätermi muutetaan, niin lisätään toiseksi ohjaustermiksi "Metsäpeuranmaa"

**Perustelut ehdotukselle**

Tällä nimellä ei löydy oikeastaan mitään netistä muualta kuin YSOsta.   Melindassa 3 viitettä, jiossa käytetään nimeä "Metsäpeuranmaa".  Mietsähallituksella tämä kulkee nyt nimellä "Peuran polku"  https://www.luontoon.fi/peuranpolku  reitillä myös  Salamajärven kansallispuisto", joka olisi RT:nä.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
Metsäpeuranmaa käyttetty esim. tässä 10.11.2020 julkaistussa uutisessa : https://keski-pohjanmaa.fi/news,metsapeuranmaan-kehitystyo-eteenpain.html

---

Metsäpeuranmaan neuvottelukunta 
"Neuvottelukunnan tarkoituksena on edistää luontomatkailun kehittymistä Metsäpeuranmaan luontomatkailualueen ja Salamajärven kansallispuiston alueella ja toimia alueella yhteistyöelimenä."
Lähde: https://kasesoft.fi/lestijarvenkunta/julkaistut_liitteet/l1382Metsapeuranmaan_neuvottelukunta_saannot_(ID_10798).pdf

---
"Peuran Polku muodostaa alueelle Metsäpeuranmaan, jonka yrittäjät tarjoavat retkeilijöille ja muille matkailijoille erilaista majoitusta, ateriapalveluita ja elämyksiä luonnossa. "
Lähde: http://www.peuranpolku.fi/peuranpolku.php

**Comment by mirmaid** [comment]
Ainakaan toistaiseksi tämän nimistä retkeilyaluetta ei ole olemassa, toisaalta eivät mielestäni ole ihan sama asia vaan _Peuran polku_ on yksittäinen retkeilyreitti.

**Comment by ilona-x** [comment]
Ehdotettu päätermin muutos Peuran poluksi ei ole toimiva vaihtoehto Melindan aineistojen perusteella:

- Metsäpeuranmaa on luontomatkailun ja metsätalouden esittelykohde.
- Metsäpeuranmaan kehittäminen 
- Tarinat ja kohteet Metsäpeuranmaan luontoreitistöllä
- Keskellä kuikkien marinaa : salomaisuus huokuu mökittömällä Lehtosenjärvellä.
- Metsäpeuranmaan erämaa-alue kutsuu luontomatkaajaa

**Comment by mirmaid** [comment]
Ehdotettu muutos ei tosiaan varmaankaan toimi, jätetäänkö entiselleen vai poistetaanko kokonaan?

**Comment by fantsby-m** [comment]
Voisi muuttaa muotoon Metsäpeuranmaa, erikseen kirjoitettu muoto on selvästi virheellinen

**Comment by mirmaid** [comment]
Ehdotus > Metsäpeuranmaa ja YK retkeilyalueet
