### ISSUE TITLE
pappeus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9774]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[pappeus](http://www.yso.fi/onto/yso/p1498)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvitettävä miten käännökset täsmäävät. Myös paavius. 

**Perustelut ehdotukselle**

Ongelmallisia sanamuotoja

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sv. prästadöme fi. pappeus, https://svenska.se/tre/?sok=pr%C3%A4stad%C3%B6me&pz=1 lienee nyt ok ruotsin kannalta, vrt https://sv.wikipedia.org/wiki/Allm%C3%A4nna_pr%C3%A4stad%C3%B6met
Sv. påvedöme fi. paavius hankalampi.. https://svenska.se/tre/?sok=p%C3%A5ved%C3%B6me&pz=1 jos tarkoitus on viitata paavina olemiseen, sen sijaan paavinvalta ok, ks. https://www.kielitoimistonsanakirja.fi/#/paavius?searchMode=all Ja mielestäni Melinda-käyttö ei näytä kovin ongelmalliselta.

**Comment by mirmaid** [comment]
Paavius voi tarkoittaa sitä, millaista on olla paavi (vrt. opettajuus, mieheys) tai sitä, että on olemassa paavin funktiossa toimivia henkilöitä ("paavius keskiajan Euroopassa") - en tiedä onko tuo jälkimmäinen sama kuin "paavinvalta" - vähän epämääräinen itselleni. Omasta puolestani tämä ei tarvitse muutoksia, jos ruotsiksi prästadöme ja påvedöme sopivat tietueisiin nykyisellään.

**Comment by mariaforsen** [comment]
Jos haluttaisiin viitata siihen millaista on olla paavi, niin "termi" pitäisi ruotsiksi olla "att vara påve" tms. Mutta hyvä jos toimii näinkin.

**Comment by mirmaid** [comment]
Opettajuus on ruotsiksi lärarskap, läraridentitet, lärarrollen. Ja opettajuus suomeksi sisältää (ainakin omaan korvaani) ihan vastaavan merkityskentän kuin paavius. Eli jos påvedöme on jotakuinkin vastaava paaviuden osalta kuin lärarskap opettajuuden, ollaan varmaan ok tilanteessa.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei tarvita muutosta.
