### ISSUE TITLE
Kulttuuriperinnön palauttaminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9775]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Kulttuuriperinnön palauttaminen 

#### Ehdotettu termi ruotsiksi   

Återlämning av kulturföremål 

#### Ehdotettu termi englanniksi   

Cultural property--Repatriation 

#### Vaihtoehtoiset termit ja ilmaisut   

repatriaatio (kulttuuriperintö), restituutio 

#### Ehdotettu yläkäsite YSOssa (LT)   

[kulttuuriperintö](http://www.yso.fi/onto/yso/p8475) 

#### Vastaava käsite muussa sanastossa   

LCSH : https://lccn.loc.gov/sh97000184 
SAO : https://id.kb.se/term/sao/%C3%85terl%C3%A4mning%20av%20kulturf%C3%B6rem%C3%A5l 
Tieteen termipankki : https://tieteentermipankki.fi/wiki/Nimitys:repatriaatio 
wikipedia : https://fi.wikipedia.org/wiki/Kulttuuriperinn%C3%B6n_palauttaminen 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[50 Kansanperinne. Perinnetieteet. Kulttuuriantropologia. Okkultismi](http://www.yso.fi/onto/yso/p26532) 

#### Tarkoitusta täsmentävä selite   

kulttuuriperinnöksi luokiteltavien konkreettisten, alkuperäisten kulttuurin tuotteiden palauttaminen lähtöpaikkaansa, alkuperäisille omistajilleen tai heitä edustavan toimijan haltuun, Repatriaatio on kulttuureja ja kulttuuriperintöä tutkivien oppialojen kuten arkeologian, kansatieteen ja taidehistorian piirissä 2000-luvun kuluessa käyttöön otettu käsite. Se koskee sekä museoita, arkistoja että niiden kokoelmia käyttäviä ja kartuttavia tutkijoita. Käsite on syntynyt keskusteltaessa alkuperäiskansojen ja erilaisten etnisten vähemmistöjen oikeudesta hallita omaa kulttuuriperintöään ja päättää sen käytöstä. (Tieteen termipankki) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1h3k2rg/alma9934126416506253 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa. 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [Kulttuuriperinnön palauttaminen](http://finto.fi/yse/fi/page/Y509775)

**Comment by AuHo22** [comment]
Tarvetta myös teoksessa Bååstede : the return of Sámi cultural heritage

**Comment by mirmaid** [comment]
_Repatriaatio_ 8 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. återlämning av kulturföremål HT repatriering av kulturföremål, återförande av kulturföremål, återföring av kulturföremål, återlämnande av kulturföremål

**Comment by jarmosaarikko** [comment]
**LCSH**:  korjattu URI: http://id.loc.gov/authorities/subjects/sh97000184 "Cultural property--Repatriation"
**Wikidata** http://www.wikidata.org/entity/Q873642  art repatriation, kulttuuriperinnön palauttaminen alias restituutio, kulttuuriomaisuuden palauttaminen
https://en.wikipedia.org/wiki/Repatriation_(cultural_property)

**Comment by YSO-kokous** [comment]
kulttuuriperinnön palauttaminen OT kulttuuriomaisuuden palauttaminen

**Comment by mirmaid** [comment]
https://aaltodoc.aalto.fi/handle/123456789/40272
