### ISSUE TITLE
eveenit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9776]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

eveenit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

Evens (Asian people)

**Tarkoitusta täsmentävä selite**

Ohjaustermi: tunguusit

**Perustelut ehdotukselle**

YSO:ssa on jo käytössä "evenin kieli", mutta tarvitaan käsite myös kielen puhujille. Käsitettä tarvitaan etnografisen ja historiallisen (esim. arkeologia) kirjallisuuden kuvailuun. Eveenejä ei tule sekottaa evenkeihin, joiden nimi YSOsta jo löytyykin.  

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [00 Yleistermit](http://www.yso.fi/onto/yso/p26556)

**Vaihtoehtoiset termit**

 "Evenit" ;  aiemmin eveenejä kutsuttiin "lamuuteiksi"

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Eveenit](https://fi.wikipedia.org/wiki/Eveenit), [Even (Asian people)](https://id.loc.gov/authorities/subjects/sh97005034.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esimerkiksi teos ISBN: 5-02-028337-1.

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [eveenit](http://finto.fi/yse/fi/page/Y509776)

**Comment by mariaforsen** [comment]
Sv. evener HT lamuter
