### ISSUE TITLE
verkkosisällöt

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9778]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

verkkosisällöt

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

verkossa julkaistava t. julkaistu sisältö

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.cupore.fi/fi/julkaisut/cuporen-julkaisut/suomalaisten-naekemykset-tekijaenoikeusjaerjestelmaestae

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [verkkosisällöt](http://finto.fi/yse/fi/page/Y509778)

**Comment by ilona-x** [comment]
Melinda x 1

**Comment by ilona-x** [comment]
YSOssa on jo **verkkoaineisto**
ja lisäksi paljon muita termejä:
verkkosivustot
www-sivut
verkkolehdet
verkkojulkaisut
blogit
verkko-oppimateriaali
jne.

**Comment by mariaforsen** [comment]
Mahdollisesti ohjausterminä?

**Comment by YSO-kokous** [comment]
#### Päätös
verkkosisällöt KÄYTÄ verkkoaineistot
