### ISSUE TITLE
maalit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9782]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[maalit](http://www.yso.fi/onto/ysa/Y97159) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Tarvinnee tarkenteen / jaettava, käytetty jonkin verran myös urheilun maaleihin liittyen. 

#### Perustelut ehdotukselle   

Esim. Melinda-haut:
maalit AND urheilu
maalit AND jalkapallo
maalit AND jääkiekko 

#### Ehdottajan organisaatio   

KK

**Comment by mirmaid** [comment]
Käytetty sekä taidemaalaukseen että pintakäsittelyyn liittyen, mikä tarkenne valitaan? Maalit (maalaus)?

**Comment by annamarj** [comment]
Maalit (maalaus) vaikuttaisi selkeältä ja kattavalta.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: maalit (maalaus).
