### ISSUE TITLE
villiinnyttäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9783]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

villiinnyttäminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

rewilding

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Villiinnyttäminen on käsite joka on noussut voimakkaasti esiin 90-luvulta eteenpäin ja nyt siitä ilmestyy kokonaisia kirjoja.  "Villiinnytys (engl. Rewilding) tai villiinnyttäminen on luonnonsuojeluperiaate, jonka tavoitteena on kunnostaa ekologisesti ihmisen toiminnan vaikutuksesta yksipuolistuneita luontoalueita." (Wikipedia.)  Villiinnyttäminen on eri asia kuin YSOssa oleva ennallistaminen. Wikipediassa: "Villiinnytyksellä ei aina pyritä luonnon ennallistamiseen, sillä luonnolliset prosessit eivät ole täysin ennustettavissa." Eli ennallistamisessa pyritään palauttamaan luonto johonkin aiemmin vallinneeseen tilaan kun taas villiinnyttämisessä käynnistetään ekosysteemissä prosessi, jonka lopputulosta ei tiedetä, mutta pyrkimyksenä on monimuotoinen, hyvinvoiva luonto. Villiinnyttämistä voidaan tehdä esimerkiksi suuria eläimiä luontoon palauttamalla, mikä johtaa ekosysteemin monimuotoistumiseen. Ennallistaminen ei mitenkään kata tätä, joten korrektia termiä tarvitaan.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 villiinnytys

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ennallistaminen](http://www.yso.fi/onto/yso/p14328)

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh90005976.html)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Paul Jepson: Rewilding. Tai The most important comic book on earth: stories to save the world.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [villiinnyttäminen](http://finto.fi/yse/fi/page/Y509783)

**Comment by jarmosaarikko** [comment]
### LCSH
Viitattu käsite [Wildlife reintroductions](https://id.loc.gov/authorities/subjects/sh90005976.html), jossa **rewilding** on ohjausterminä, on jo linkattu YSO käsitteeseen [luontoonpalautus](http://www.yso.fi/onto/yso/p29460).  Minusta se tuntuu kattavan tässä ehdotuksessa esitetyt tapaukset yksittäisten lajien osalta. 

Villiinnyttäminen koskee sen sijaan koko ekosysteemiä eli on eri käsite, vaikka LCSH:ssa ne ovat yhdessä. kts. Wikidata.

### Wikidata 
- villiinnytys | återförvildande | rewilding | http://www.wikidata.org/entity/Q13878863 
- https://en.wikipedia.org/wiki/Rewilding_(conservation_biology)
- https://fi.wikipedia.org/wiki/Villiinnytys

**Comment by mariaforsen** [comment]
Sv. återförvildande HT rewilding, återförvildning
https://rewilding-sweden.com/darfor-rewilding/
http://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1442566&dswid=-3864
https://www.isof.se/lar-dig-mer/bloggar/sprakradsbloggen/inlagg/2021-09-01-nyordet-aterforvildande

**Comment by YSO-kokous** [comment]
### Päätökset
villiinnyttäminen OT villiinnitys
