### ISSUE TITLE
mithralaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9784]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mithralaisuus 

#### Vaihtoehtoiset termit ja ilmaisut   

mihtralaisuus 
mitralaisuus 
Mithraism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[mysteeriuskonnot](http://www.yso.fi/onto/yso/p12285) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85086278> 
Wikidata : https://www.wikidata.org/wiki/Q219903 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Tarvitaan Teologian asiasanaston lakkauttamisen myötä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/002514288 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [mithralaisuus](http://finto.fi/yse/fi/page/Y509784)

**Comment by jtuohini** [comment]
Ja ehdotuksessa **_Mithraism_** siis asiasanan englanninkielinen muoto, ei vaihtoehto, ja ruotsinkielinen sama (kaiketikin pienellä alkukirjaimella?).

**Comment by mariaforsen** [comment]
Sv. mithraism HT Mithrakulten, Mithrasmysterierna, Mitrasmysterierna, mitraism
https://id.kb.se/find?q=mithraism
https://sv.wikipedia.org/wiki/Mithraism
