### ISSUE TITLE
profetismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9785]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[profetismi](http://www.yso.fi/onto/ysa/Y208757) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Vaihdetaan LT-suhde "itsenäinen toiminta" --> "armolahjat" (ja poistetaan nykyinen RT-suhde jälkimmäiseen) 

#### Perustelut ehdotukselle   

Profetismi on yksi armolahjoista, eikä "itsenäinen toiminta" ylähierarkiana auta tiedonhakijaa tippaakaan. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
profetismia (profetoiminen?) ei voi kytkeä alakäsitteenä armolahjoihn, sillä se liittyy myös muihin uskontoihin, kuten juutalaisuuteen tai islamiin, shamanismiiin jne.   - "_Profetoiminen on yleisuskonnollinen ilmiö_"  - lähde: [Profetoiminen](https://rovasti.fi/node/270) (rov. O.Peltola)

Armolahjat on vain kristinuskoon liittyvä käsite.
https://fi.wikipedia.org/wiki/Armolahja
https://fi.wikipedia.org/wiki/Profeetta
https://fi.wikipedia.org/wiki/Profetia
https://fi.wikipedia.org/wiki/Divinaatio

- LCSH:ssa **Profecy** -käsitteen yläkäsite on **Forecasting** http://id.loc.gov/authorities/subjects/sh85050485  
- YSOssa vastaava yläkäsite olisi **ennusteet** http://www.yso.fi/onto/yso/p3297, jossa on ohjausterminä **ennustaminen (arviointi)**
- kts. myös https://termipankki.fi/tepa/en/search/ennustaminen
- RT  **profetiat**  http://www.yso.fi/onto/yso/p3912
