### ISSUE TITLE
ristin teologia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9786]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

ristin teologia 

#### Ehdotettu termi englanniksi   

theology of the cross 

#### Ehdotettu termi ruotsiksi   

korsteologi 

#### Vaihtoehtoiset termit ja ilmaisut   

staurology [eng] 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh2006002883> 
Wikidata : https://www.wikidata.org/wiki/Q1133898 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Tarkoitusta täsmentävä selite   

https://evl.fi/sanasto/-/glossary/word/Ristin+teologia 

#### Perustelut ehdotukselle   

Tarvitaan Teologian asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006731935 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [ristin teologia](http://finto.fi/yse/fi/page/Y509786)

**Comment by mariaforsen** [comment]
Sv. korsets teologi HT korsteologi
