### ISSUE TITLE
liiketoimintaekosysteemi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9787]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

liiketoimintaekosysteemi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

business ecosystem

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

On käytetty HY:n väitöskirjassa ja selitys löytyy mm. täältä: https://www.sitra.fi/artikkelit/mita-nama-kasitteet-tarkoittavat/

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://helda.helsinki.fi/handle/10138/330120

**Ehdottajan organisaatio**

HY:n kirjasto
**Termiehdotus Fintossa:** [liiketoimintaekosysteemi](http://finto.fi/yse/fi/page/Y509787)

**Comment by ilona-x** [comment]
Aiempi ehdotus: liiketoimintaekosysteemi https://github.com/Finto-ehdotus/YSE/issues/6866

**Comment by mariaforsen** [comment]
Sv. affärsverksamhetsekosystem /finlex HT affärsekosystem

**Comment by jarmosaarikko** [comment]
https://www.sitra.fi/tulevaisuussanasto/liiketoimintaekosysteemi/
https://www.sitra.fi/sv/ordbok/affarsverksamhetsekosystem/
https://www.sitra.fi/en/dictionary/business-ecosystem/
Finnassa [110 osumaa](https://finna.fi/Search/Results?lookfor=liiketoimintaekosysteemi&type=Subject), joista aiheena 31 kertaa.  Business ecosystem 51 kertaa.
Melindassa 10 kertaa vapaana asiasanana. Perushaussa 15 osumaa suomeksi ja 49 englanniksi, affärsekosystem   3 kertaa.

**Comment by mirmaid** [comment]
Myös https://github.com/Finto-ehdotus/YSE/issues/8919

**Comment by YSO-kokous** [comment]
### Päätös
otetaan sanastoon muodossa liiketoimintaekosysteemit
