### ISSUE TITLE
halal

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9788]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[halal](http://www.yso.fi/onto/ysa/Y169098) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Muutetaan muotoon "halal-ruoka" 

#### Perustelut ehdotukselle   

Pelkkä "ḥalāl" tarkoittaa kaikkea islamilaisen lain mukaan puhdasta tai sallittua, ei vain ruokaa. (https://en.wikipedia.org/wiki/Halal) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Mielestäni käsite on selkeä, vaikkei selkeästi rajata vain ruokaan. Ks. esim. WP: "Halal ([arab.](https://fi.wikipedia.org/wiki/Arabian_kieli) حلال‎, ḥalāl ”puhdas, sallittu”) tarkoittaa [islamissa](https://fi.wikipedia.org/wiki/Islam) kaikkea sitä, mikä keskiajalla vakiintuneen Jumalan lain, [šarian](https://fi.wikipedia.org/wiki/%C5%A0aria), mukaan on sallittua ja luvallista. Sen vastakohta on [haram](https://fi.wikipedia.org/wiki/Haram_(islam)), joka tarkoittaa kiellettyä.[[1]](https://fi.wikipedia.org/wiki/Halal#cite_note-islamopas-halal-1)[[2]](https://fi.wikipedia.org/wiki/Halal#cite_note-sardar-2) Šarialaissa käsite halal liittyy tyypillisesti ruoka-aineisiin."

**Comment by mirmaid** [comment]
^ Jos jätetään rajaamatta, pitäisikö hierarkiaa muuttaa? Sama koskee muuten _kosheria_.

**Comment by jarmosaarikko** [comment]
Käsite on linkitetty LCSH:ssa http://id.loc.gov/authorities/subjects/sh2006008707  Halal food
Tämä puoltaisi rajausta ja käytettävän termin muutosta muotoon Halal-ruoka. 

Jos YSO:n kosher rajautuu ruokaan (kosher-ruoka?), niin vastaava LCSH käsite on 
http://id.loc.gov/authorities/subjects/sh85073169 Kosher food

Kuvailun kannalta voisi olla helpompaa, ettei rajata ruokaan, mutta silloin **kosher**, **halal** ja **haram**  yläkäsite olisi "uskontoon liittyvät abstraktit objektit" http://www.yso.fi/onto/yso/p38222

**haram** - http://www.wikidata.org/entity/Q223862   -- tämä olisi uusi YSOlle käsite

**Comment by mariaforsen** [comment]
Hierarkiamuutos riittäisi ja YK voisi olla esim. https://finto.fi/yso/fi/page/p26368 tai [uskontoon liittyvät abstraktit objektit](https://finto.fi/yso/fi/page/p38222)

**Comment by mirmaid** [comment]
Ehdotus: tarkennetaan hierarkiaa Marian esittämällä tavalla.
