### ISSUE TITLE
sharia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9789]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sharia](http://www.yso.fi/onto/ysa/Y151388) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään LT-suhde asiasanaan "oikeus (oikeudenala)" 

#### Perustelut ehdotukselle   

Sharia on yhdistelmä uskontoa ja oikeudenkäyttöä, joten asiasanan pitäisi myös sanasuhteiltaan heijastella tätä. Sana aiheryhmissäkin seikka on jo ilmaistu. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by jarmosaarikko** [comment]
Kannatan yläkäsitteen muutosta.
Tämä on eräs uskonnollinen laki, religiös lag, religious law  -- kts. aikaisempi ehdotus #2993
https://en.wikipedia.org/wiki/Religious_law
https://sv.wikipedia.org/wiki/Religi%C3%B6s_lag
käsite puuttuu YSO:sta, mutta olisiko tarpeen lisätä, sillä näitä on muitakin kts.  #9790

**Comment by mirmaid** [comment]
Käsiteltiin YSO-toimituksen kesken ehdotusta siirtää tämä (ja halakha) oikeus (oikeudenala) -käsitteen alle. Ryhmä piti kuitenkin RT-suhdetta parempana ottaen huomioon nykyisen alakäsitejoukon, vaikka molemmat on mahdollista ymmärtää sekä lakikokoelmina, että laajemmin tietynlaisena oikeudenalana.
