### ISSUE TITLE
halakha

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9790]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

halakha 

#### Ehdotettu termi englanniksi   

Jewish law 

#### Ehdotettu termi ruotsiksi   

halacha 

#### Vaihtoehtoiset termit ja ilmaisut   

juutalainen laki 
halaha 
halaa 
Mosaic law 
Torah law 
Hebrew law 

#### Ehdotettu yläkäsite YSOssa (LT)   

[oikeus (oikeudenala)](http://www.yso.fi/onto/yso/p1532) 
[juutalaisuus](http://www.yso.fi/onto/yso/p727) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85070287> 
Wikidata : https://www.wikidata.org/wiki/Q107427 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 
[69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559) 

#### Perustelut ehdotukselle   

Tarvitaan Teologian asiasanaston lakkauttamisen myötä 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/007010589 ja parikymmentä muuta 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [halakha](http://finto.fi/yse/fi/page/Y509790)

**Comment by jtuohini** [comment]
Ja yhtenä KT-muodoista _halaka_, ei "halaa".

**Comment by mariaforsen** [comment]
Sv. halakha HT halaka, halacha 
https://id.kb.se/find?q=halak%2a

**Comment by jarmosaarikko** [comment]
kts myös #2993
