### ISSUE TITLE
borrelioosi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9791]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[borrelioosi](http://www.yso.fi/onto/yso/p13976)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

voisiko päätermiksi muuttaa FinMeSHin mukaan borreliainfektiot, kun sitä tämä termi ilmeisesti tarkoittaa
FisMeSH: http://www.yso.fi/onto/mesh/D001899

**Perustelut ehdotukselle**

Ysossa on nyt siis sekä Lymen borrelioosi että borrelioosi, mikä saattaa aiheuttaa hämmennystä

FinMeSHissä borrelioosi on ohjaustermi sekä borreliainfektioille että Lymen borrelioosille

**Ehdottajan organisaatio**

kk/il

**Comment by FinMeSHienPaimentaja** [comment]
Pitäisin **borrelioosin** eli puheena olevan tautia kuvaavan termin sinällään. Infektiot eli tartunnat voi aiheuttaa taudin tai olla aiheuttamatta - tartunnat / tartunnan saaminen ei ole sama asia kuin tauti. 

**Lymen borrelioosi** on tietyn Borrelia-bakteerin aiheuttama tauti. Lääketieteen termien mukaan: 

**borrelioosi**

**borreliosis** la e, borrelios ‑en r **jonkin Borrelia-lajin aiheuttama infektio**; ks. myös toisintokuume
**Lymen borrelioosi** borreliosis Lyme, morbus Lyme la, Lyme borreliosis, Lyme disease e, Lyme-borrelios ‑en, Lyme-sjuka ‑n r (nimetty Yhdysvalloissa sijaitsevan löytöpiirikunnan mukaan) **Lymen tauti | puutiaisten levittämä, Borrelia burgdorferi ‑spirokeetan aiheuttama borrelioosi**, jonka ilmenemismuotoja ovat alkuvaiheessa puremakohdan ihossa vähitellen laajeneva punoitus (erythema migrans; →eryteema), sitten ihon →lymfosytooma, levinneessä vaiheessa neurologiset oireet, sydän-, silmä-, nivel- ja lihasoireet sekä myöhäisvaiheessa ihomuutokset ja keskushermosto-oireet; ks. myös acrodermatitis chronica atrophicans (→akrodermatiitti), Bannwarthin oireyhtymä, borrelioosiaivokalvotulehdus (→aivokalvotulehdus).

FinMeSH:it ovat MeSH:ien suomennuksia ja ne ovat riippuvaisia siitä, miten on MeSH-termit, vaikka sitten olisivatkin "epäsynkronisaatiossa"  YSO-termien kanssa. FinMeSH-termeissä **borrelioosi** synonyyminä **Borrelia-infektioille** korjataan/päivitetään seuraavassa päivityksessä.   MeSHeissä on **borrelioosiin** liittyen:

+  Borrelia  Borrelia  
+  Borrelia burgdorferi  Borrelia burgdorferi  
+  Borrelia burgdorferi Group  Borrelia burgdorferi -ryhmä  
+  Borrelia Infections  borreliainfektiot  
+  Erythema Chronicum Migrans  vaeltava punoitus  
+  Lyme Disease  Lymen borrelioosi  
+  Lyme Disease Vaccines  Lymen tauti -rokotteet  
+  Lyme Neuroborreliosis  Lymen neuroborrelioosi  
+  Post-Lyme Disease Syndrome  Lymen borrelioosin jälkeinen oireyhtymä

**Comment by mirmaid** [comment]
Taitaa kyllä nykyisellään mennä sekaisin. Jos borrelioosi voi viitata muihinkin tauteihin, sen pitäisi kai olla monikossa, mutta näyttää, että yleensä borrelioosilla viitataan juuri Lymen borrelioosiin ja toisesta taudista käytetään nimeä toisintokuume (relapsing fever).

**Comment by mirmaid** [comment]
Borrelioosi Melindassa 228 kertaa, Lymen borrelioosi 135 kertaa.

**Comment by ilona-x** [comment]
YSOssa siis 
Lymen borrelioosi YLÄKÄSITE **bakteeritaudit**
borrelioosi YLÄKÄSITE **infektiot**

**Comment by mirmaid** [comment]
Ehdotan yhdistämistä, mutta tarvitaanko borreliainfektiot lisäksi?

**Comment by mirmaid** [comment]
Sanastossa on _flavivirusinfektiot_ ja _zikavirusinfektio_. Zikavirus on myös erikseen, flavivirukset ei. MeSHissä borreliainfektiot on Lymen borrelioosin ja toisintokuumeen yläkäsite. Meillä se olisi kuitenkin varmaan hyvin päällekkäinen borrelioosin kanssa, toinen taudeista on täällä hyvin harvinainen (ja jos aineisto käsittelisi sitä, varmaan syytä olla erikseen).

Sanastossa on myös _Borrelia-bakteerit_.

**Comment by mirmaid** [comment]
Eli ehdotus: Lymen borrelioosi KÄ borrelioosi tai toisin päin.

**Comment by mariaforsen** [comment]
Ruotsiksi pääterminä varmaan borrelios. Nationalencyklopedin: "borrelios..Borrelios beskrevs först i USA som Lyme disease, ”Lymesjukdomen” efter ett större utbrott i Old Lyme, Connecticut."

**Comment by mirmaid** [comment]
borrelioosi KT Lymen borrelioosi
