### ISSUE TITLE
grundtvikilaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9792]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

grundtvikilaisuus 

#### Ehdotettu termi ruotsiksi   

grundtvigianism 

#### Ehdotettu termi englanniksi   

Grundtvigianism 

#### Ehdotettu yläkäsite YSOssa (LT)   

[uskonnolliset liikkeet](http://www.yso.fi/onto/yso/p4851) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85057544> 
Wikidata : https://www.wikidata.org/wiki/Q2576120 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[53 Uskonto. Teologia. Uskontotiede](http://www.yso.fi/onto/yso/p26551) 

#### Perustelut ehdotukselle   

Tarvitaan Teologian asiasanaston lakkauttamisen myötä. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/000349787 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [grundtvikilaisuus](http://finto.fi/yse/fi/page/Y509792)

**Comment by mirmaid** [comment]
oik. grundtvigilaisuus
