### ISSUE TITLE
uskonnonfilosofia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9793]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[uskonnonfilosofia](http://www.yso.fi/onto/ysa/Y106075) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "fideismi" 

#### Perustelut ehdotukselle   

Lakkauttamisen alaisessa Teologian asiasanastossa ST-suhtesena asiasanana, mutta on käytetty Melindassa vain 7 kertaa, joten viittausmuoto riittäisi. 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
En kannata ohjausterminä (aivan eri merkitys kuin uskonnonfilosofia-termillä). 
https://tieteentermipankki.fi/wiki/Filosofia:fideismi : "näkemys, jonka mukaan uskonnollisia näkemyksiä ei voi eikä ole tarkoituskaan arvioida rationaalisesti" 

Kannatan siis erillisenä terminä sanastossa.

**Comment by mirmaid** [comment]
Päätermiä selvästi suppeampien ohjaustermien ongelmista on saatu sen verran palautetta, että en myöskään kannata. Ennemmin erillisenä, jos tarvitaan.

**Comment by YSO-kokous** [comment]
### Päätös
Ei lisätä ehdotettua ohjaustermiä
Lisätään uutena käsitteenä **fideismi**

**Comment by mariaforsen** [comment]
Sv. fideism
