### ISSUE TITLE
julkinen valta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9794]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[julkinen valta](http://www.yso.fi/onto/ysa/Y118826) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muoto "esivalta" 

#### Perustelut ehdotukselle   

On itsenäisenä asiasanana lakkautettavassa Teologian asiasanastossa. Ks. myös https://www.kielitoimistonsanakirja.fi/esivalta 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by mariaforsen** [comment]
Sv. HT överhet

**Comment by mirmaid** [comment]
Kielitoimiston sanakirjan mukaan ilmaus on ylätyylinen. Omaan korvaani esivalta viittaa erityisesti vallankäyttäjiin (toimijoihin), julkinen valta enemmän valtuuteen/vallankäyttöön. Termi näyttää olevan käytössä lähinnä teologian puolella.

**Comment by jarmosaarikko** [comment]
Esivalta on englanniksi  "authorities"   (MOT sanakirja).
YSOssa on jo käsite [auktoriteetti](http://www.yso.fi/onto/yso/p12600), auktoritet, authority. 
MOT sanakirjan esimerkissä: maallinen esivalta = temporal powers 

http://www.wikidata.org/entity/Q174834 - [auktoriteetti](https://fi.wikipedia.org/wiki/Auktoriteetti)
https://fi.wikipedia.org/wiki/Esivalta
https://fi.wikipedia.org/wiki/Julkinen_valta - linkattu tähän: https://en.wikipedia.org/wiki/Public_policy

Tätä vanhahtavaa termiä ei tarvita sanastossa. Uusimmassa raamtunkäännöksessä sama Roomalaiskirjeen kohta on käännetty termillä "**vallanpitäjät**", joka kyllä sopisi ohjaustermiksi käsitteelle "julkinen valta". Samalla voisi lisätä tuon "authorities".

>UT2020
 _Rm 13:1 Kaikkien on alistuttava vallanpitäjien ja viranomaisten määräyksiin. Eihän valtaan pääse muuten kuin Jumalan tahdosta, joten vallanpitäjät ovat Jumalan asettamia._
>KR92
_Rm 13:1 Jokainen olkoon alamainen sille esivallalle, jonka vallan alla hän on. Sillä ei ole esivaltaa muutoin kuin Jumalalta; ne, jotka ovat, ovat Jumalan asettamat._

**Comment by YSO-kokous** [comment]
### Päätös
Ei lisätä ohjaustermejä
