### ISSUE TITLE
mamelukit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9795]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

mamelukit 

#### Ehdotettu termi englanniksi   

mamlukes 

#### Ehdotettu termi ruotsiksi   

mamluker 

#### Vaihtoehtoiset termit ja ilmaisut   

mamelukes [eng] 
mamluqs [eng] 
mameluks [eng] 
mamalukes [eng] 
marmelukes [eng] 

#### Ehdotettu yläkäsite YSOssa (LT)   

[sotilaat](http://www.yso.fi/onto/yso/p2504) 
[orjat](http://www.yso.fi/onto/yso/p13194) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85080253> 
Wikidata : https://www.wikidata.org/wiki/Q947784 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[52 Historia](http://www.yso.fi/onto/yso/p26540) 
[67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575) 

#### Perustelut ehdotukselle   

Sopiva asiasana puuttuu vanhastaan; tarvitaan sanastoon – kenties kera tarkenteen? –, ettei sekoitu Mao/Tao-sanaston vastaavaan vaatekappaletta kuvastavaan asiasanaan 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://melinda.kansalliskirjasto.fi/byid/006844954 ja muita 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [mamelukit](http://finto.fi/yse/fi/page/Y509795)

**Comment by mirmaid** [comment]
Voiko kuitenkaan sanoa, että mamelukit olisivat olleet aina orjia tai edes sotilaita? https://en.wikipedia.org/wiki/Mamluk_Sultanate
Mikähän voisi olla tarkenne, jos sellainen tarvitaan?

**Comment by YSO-kokous** [comment]
### Päätös
Otetaan sanastoon muodossa mamelukit (väestöryhmät)
