### ISSUE TITLE
Black lives matter

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9796]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

Black lives matter 

#### Perustelut ehdotukselle   

Ehdotus tullut alun perin Toikuun. Selvittelyn jälkeen näyttäisi, että tämä olisi kuitenkin enemmin YSO-termi.

Saksan kansalliskirjasto on tehnyt siitä yhteisöauktoriteettitietueen, mutta ilmeisesti poistanut sen käytöstä.
http://viaf.org/processed/DNB%7C1153800764

Termi löytyy asiasana sekä Saksan kansalliskirjastosta että Kongressin kirjastosta:
https://d-nb.info/gnd/1190845202
http://id.loc.gov/authorities/subjects/sh2016001442

Lisäksi YSO-terminä näyttää olevan jonkin verran liikkeitä esim. Jeesus-liike ja Zeitgeist-liike. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Termiehdotus Fintossa:** [Black lives matter](http://finto.fi/yse/fi/page/Y509796)

**Comment by annamarj** [comment]
-> Black lives matter -liike, Black lives matter ohjaustermiksi?

**Comment by mariaforsen** [comment]
Sv. Black Lives Matter-rörelsen HT Black Lives Matter, BLM-rörelsen

**Comment by LeKorsu** [comment]
Pitääkö olla avattuna, vai kävisikö BLM-liike? Toisaalta, argumentoin itseäni heti perään, että kuinka pian lyhenteen merkitys avattuna unohtuu. Joka tapauksessa kannatan liike-sanan liittämistä käsitteen perään.

**Comment by mirmaid** [comment]
_Black lives matter -liike_ olisi varmaan paras päätermiksi.

**Comment by YSO-kokous** [comment]
### Päätös
Black lives matter -liike OT BLM-liike
