### ISSUE TITLE
muovikassit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9797]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[muovikassit](http://www.yso.fi/onto/ysa/Y164161) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Yhdistetään käsitteeseen muovipussit. 

#### Perustelut ehdotukselle   

(Lähes) sama asia. 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Muovikassit 26 kertaa Melindassa, muovipussit 24...hedelmä- ja koirankakkapussit eivät ehkä olisi muovikasseja. Toisaalta kestokassi ei ole pussi. Kumpi valitaan?

**Comment by mirmaid** [comment]
Tästä äänestämme 🙂

**Comment by YSO-kokous** [comment]
**Päätös**

Valitaan muovipussit, ohjaustermiksi muovikassit.
