### ISSUE TITLE
Euroopan-puoleinen Venäjä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9798]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Euroopan-puoleinen Venäjä

**Ehdotettu termi ruotsiksi**

Europeiska Ryssland

**Ehdotettu termi englanniksi**

European Russia

**Tarkoitusta täsmentävä selite**

Tarkoittaa Uralin länsipuoleista osaa Venäjästä, joka on osa Itä-Eurooppaa.

**Perustelut ehdotukselle**

YSO-paikoissa on jo Etelä-Venäjä, Pohjois-Venäjä, Luoteis-Venäjä, mutta ei ole käsitettä "Euroopan-puoleinen Venäjä" tai Länsi-Venäjä, johon usein viitataan.
Käytössä esim. YLE:ssä. https://haku.yle.fi/?page=1&query=%22l%C3%A4nsi-ven%C3%A4j%C3%A4%22
Melindassa 15 kertaa. Finnassa 65 osumaa.

LCSH: "Here are entered works on the western areas of imperial Russia, or the Russian Federation. Works on the western areas of the Soviet Union are entered under the heading [Soviet Union, Western.]"

**Ehdotettu yläkäsite YSOssa (LT)**

 [Itä-Eurooppa](http://www.yso.fi/onto/yso/p105223), [Venäjä](http://www.yso.fi/onto/yso/p94479)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 Länsi-Venäjä, Venäjän länsiosa, West Russia

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia: European Russia](https://en.wikipedia.org/wiki/European_Russia), [Wikipedia: Europeiska Ryssland](https://sv.wikipedia.org/wiki/Europeiska_Ryssland), [LCSH: Western Russia](http://id.loc.gov/authorities/subjects/sh94003455), [Kotus Eksonyymit: Euroopan-puoleinen Venäjä](https://kaino.kotus.fi/eksonyymit/?a=tietue&id=1398&ex=Euroopan-puoleinen+Ven%C3%A4j%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

YLE:n uutiset, Seko, kartat Finnassa

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Länsi-Venäjä KT Euroopan-puoleinen Venäjä

**Comment by mariaforsen** [comment]
Sv. Västra Ryssland HT Europeiska Ryssland, Västryssland
