### ISSUE TITLE
fyysinen ergonomia

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9799]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

fyysinen ergonomia

**Ehdotettu termi ruotsiksi**

fysiskt ergonomi

**Ehdotettu termi englanniksi**

physical ergonomics 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Ergonomia on monitieteinen tutkimusalue, jonka tavoitteena on kehittää työtä ja työoloja vastaamaan työntekijän fyysisiä, psyykkisiä ja sosiaalisia ominaisuuksia.

Ergonomiayhdistyksen sivuilla lukee: "Fyysinen ergonomia keskittyy fyysisen toiminnan sopeuttamiseen ihmisen anatomisten ja fysiologisten ominaisuuksien mukaisiksi. Fyysinen ergonomia ilmenee fyysisen työympäristön, työpisteiden, työvälineiden ja työmenetelmien suunnittelussa.

Kognitiivinen ergonomia keskittyy järjestelmien ja niiden käyttöliittymien sopeuttamiseen vastaamaan ihmisen tiedonkäsittelyn ominaispiirteitä. Kognitiivinen ergonomia ilmenee järjestelmien ja niiden käyttöliittymien (näytöt ja ohjaimet) ja tiedon esittämistapojen suunnittelussa.

Organisatorinen ergonomia keskittyy teknisen järjestelmän ja sosiaalisen järjestelmän yhteensovittamiseen. Organisatorinen ergonomia ilmenee mm. henkilöstön, työprosessien, työkokonaisuuksien ja työaikajärjestelyjen suunnittelussa, ja se liittyy myös tuotannon ja palveluiden kehittämiseen sekä henkilöstön yhteistyön kehittämiseen".
lähde: https://www.ergonomiayhdistys.fi/ergonomia/mita-ergonomia-on/

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [78 Työelämä. Työsuojelu. Työterveys](http://www.yso.fi/onto/yso/p26525)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [työ työn luonteen mukaan](http://www.yso.fi/onto/yso/p5863)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Tutkin etätyön fyysisen ja kognitiivisen ergonomian tasoa sekä koetun fyysisen ja kognitiivisen ergonomian yhteyttä koettuun työkykyyn COVID-19 pandemian aikana Etätyöpisteiden olosuhteet-tutkimuksen alkutilanteessa.  Tutkimus on osa Etätyöpisteiden olosuhteet (ETERGO) -tutkimushanketta, jonka tarkoituksena on tuottaa tietoa etätyöolosuhteista kokonaisvaltaisesti. Tutkimuksen kohderyhmänä on tietotyötä tekevät henkilöt, jotka tekevät säännöllistä etätyötä vähintään kaksi kertaa viikossa (n =70). 

**Ehdottajan organisaatio**

Itä-Suomen yliopisto (UEF)
**Termiehdotus Fintossa:** [fyysinen ergonomia](http://finto.fi/yse/fi/page/Y509799)

**Comment by ilona-x** [comment]
TSR: **fyysinen ergonomia** http://www.yso.fi/onto/tsr/p13061

**Comment by mariaforsen** [comment]
Sv. fysisk ergonomi
https://www.arbetsgivarverket.se/ledare-i-staten/arbetsgivarguiden/arbetsmiljo/ergonomi/

**Comment by mirmaid** [comment]
Varmaan valtaosa _ergonomia_-käsitteellä kuvaillusta aineistosta on nimenomaan fyysiseen ergonomiaan liittyvää, jos molemmat ovat käytettävissä, miten ajatellaan käytön rajautuvan?

**Comment by ilona-x** [comment]
Olisiko tämä haluttu nyt sanastoon, kun viime vuonna otettiin kognitiivinen ergonomia ergonomian alakäsitteeksi 🤔

**Comment by YSO-kokous** [comment]
### Päätös
fyysinen ergonomia  KÄYTÄ ergonomia
