### ISSUE TITLE
liikuntatapahtumat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9800]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[liikuntatapahtumat](http://www.yso.fi/onto/yso/p1963)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö kuitenkin olla erikseen urheilutapahtumat tai vaihtaa päittäin. 

**Perustelut ehdotukselle**

Kaikkiin julkaisuihin liikuntatapahtumat ei tunnu oikealta, jos on kyse urheilukilpailuista (tai esim. e-urheilutapahtumat..)

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Pitäisikö olla _urheilu- ja liikuntatapahtumat_, samaan tapaan kuin _urheilu- ja liikuntaseurat_?

**Comment by MarkoLatvanen** [comment]
Onko yhdistetyssä _urheilu- ja liikuntatapahtumat_ -käsitteessä se riski, että siinä menee samaan koriin kaupalliset urheilutapahtumat (maksava yleisö vs kilpailevat urheilijat) ja kaikille avoimet liikuntatapahtumat, joissa ei pääasiassa kilpailla?

**Comment by mariaforsen** [comment]
Kannatan joko erillisenä tai yhdistettynä (Mirjan ehdotus), nykyinen ratkaisu huonoin vaihtoehto.

**Comment by ilona-x** [comment]
> Kaikkiin julkaisuihin liikuntatapahtumat ei tunnu oikealta, jos on kyse urheilukilpailuista (tai esim. e-urheilutapahtumat..)

YSOssa on **urheilukilpailut**, jolla alakäsitteinä iso joukko urheilutapahtumia http://www.yso.fi/onto/yso/p1934

**Comment by mirmaid** [comment]
^ Riittäisikö siis kuitenkin urheilutapahtumat KÄ urheilukilpailut, liikuntatapahtumat?

**Comment by mariaforsen** [comment]
Muutoksia ehkä tarvitaan silti ruotsiksi, jos halutaan että esim. urheilutapahtumat voidaan käyttää myös e-urheilu-merkityksestä? 

Urheilukilpailut on nimittäin nyt sv. idrottstävlingar, ja toki liikuntatapahtumatkin on sv. idrottsevenemang (sv. motionsevenemang saattaisi olla parempi vastine), mutta ei ole miten vain ok e-urheilusta. Onko e-urheilu suomeksi hyväksytty liikkuntana/urheiluna?

Ruotsiksi erimielisyyttä siitä, ks. esim. 
https://www.sesf.se/vad-ar-e-sport 
https://svenska.yle.fi/a/7-1438369 ; https://kit.se/arkiv/2016/08/29/58456/darfor-ar-e-sport-en-sport-men-inte-en-idrott/ 
https://www.komplett.se/article/88248/darfor-ska-e-sport-klassas-som-idrott?utm_source=facebook&utm_medium=post&utm_campaign=artikel_esportidrott&utm_term=090619 
https://www.svt.se/nyheter/inrikes/e-sporten-far-nobben-som-idrott-trots-riksdagsmajoritet

**Comment by YSO-kokous** [comment]
**Päätös**

Yllä olevan ehdotuksen mukaisesti _urheilutapahtumat_ KÄ _urheilukilpailut_, _liikuntatapahtumat_.

**Comment by mariaforsen** [comment]
AASI: idrottstävlingar > sport- och idrottstävlingar
Obs. Se underordnade begrepp https://finto.fi/yso/fi/page/p1934?clang=sv
Se NE
https://svenska.se/tre/?sok=idrott&pz=1
https://svenska.se/tre/?sok=sport&pz=1
https://svenska.yle.fi/a/7-1438369
https://sv.wikipedia.org/wiki/Idrott
https://sv.wikipedia.org/wiki/Sport 
https://id.kb.se/find?q=idrott
https://id.kb.se/term/sao/Sport
