### ISSUE TITLE
Laki sosiaali- ja terveydenhuollon asiakasmaksuista

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9804]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Laki sosiaali- ja terveydenhuollon asiakasmaksuista

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tätä lakia en vielä löytänyt YSOsta. Se olisi tarkka termi, jota tarvittaisiin esim. Uudistunut asiakasmaksulaki -teoksen kuvailussa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [73 Sosiaalipolitiikka. Yhteiskuntapolitiikka. Sosiaaliturva. Terveydenhuolto. Asuminen](http://www.yso.fi/onto/yso/p26549)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Uudistunut asiakasmaksulaki (2021)

**Ehdottajan organisaatio**

Hämeen ammattikorkeakoulu
**Termiehdotus Fintossa:** [Laki sosiaali- ja terveydenhuollon asiakasmaksuista](http://finto.fi/yse/fi/page/Y509804)

**Comment by mariaforsen** [comment]
Sv. lag om klientavgifter inom social- och hälsovården
