### ISSUE TITLE
Suvilahti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9805]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Suvilahti](http://www.yso.fi/onto/yso/p27158)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tähän lisätä tarkenteen (Helsinki), ja mahdollisesti siirtää YSO-paikkoihin?
https://fi.wikipedia.org/wiki/Suvilahti_(Helsinki)
Huom. Suvilahti (Helsinki) ei löydy MML:n Paikkatietoalustalta.

**Perustelut ehdotukselle**

Käytetty Melindassa 74 kertaa, ja näistä 44 viitteessä on myös asiasana Vaasa, mikä viittaisi siihen, että tätä YSO:n Suvilahtea on käytetty Vaasan Suvilahti-kaupunginosaa käsittelevissä aineistoissa. https://fi.wikipedia.org/wiki/Suvilahti_(Vaasa)

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
YSAssa on wikipedian tähän artikkeliin https://fi.wikipedia.org/wiki/Suvilahti_(kulttuurikeskus) liittyvä määritelmä. Nykytulkinnan mukaan kulttuurikeskus olisi kai yhteisö.

**Comment by mariaforsen** [comment]
Myös Suvilahti (Vaasa) pitäisi lisätä YSO-paikkoihin.

**Comment by mirmaid** [comment]
Poistetaanko YSOsta?

**Comment by mirmaid** [comment]
Siirtyisikö tämä sitten Kantoon?

**Comment by ilona-x** [comment]
YSAssa on ollut huomautus:
"Helsingin Sörnäisissä sijaitseva entinen energiantuotantoalue, jonka rakennukset ja toiminta siirtyivät vuonna 2010 Helsingin kaupungin omistaman Kiinteistö Oy Kaapelitalon omistukseen; toimintakonseptiltaan Suvilahti on Kaapelitehdasta vastaava kulttuurikeskus"

Eli pitäisi varmaan tutkia Melinda-viitteitä ja katsoa, mitä kaikkea tarvitaan. 🤔 Olisikohan tuo Suvilahden alue mahdollista jotenkin auktorisoida YSO-paikkoihin, vaikka sitä ei MML:n karttapalveluista löydykään.

Suvilahden voimalaitosalue 
http://www.rky.fi/read/asp/r_kohde_det.aspx?KOHDE_ID=1579
https://kartta.museoverkko.fi/?action=showRegistryItem&id=1579&registry=rky2000&mapLayers=20

**Comment by mirmaid** [comment]
Ehdotus: poistetaan YSOsta ja lisätään tarvittaessa Kantoon, tutkitaan tarvetta paikkakäsitteenä yso-paikkojen ylläpidossa.

**Comment by mirmaid** [comment]
Ei auktorisoida Helsingin alueena, korjataan viitteisiin laajempi kaupunginosa. Otetaan Suvilahti (Vaasa).

**Comment by ilona-x** [comment]
Helsingin Suvilahti löytyy nyt myös paikkatietoalustalta:
http://paikkatiedot.fi/so/1000772/12021955

**Comment by ilona-x** [comment]
Lisätty YSO-paikkoihin myös Suvilahti (Suojärvi), kun Melinda-korjauksia tehdessä tuli vastaan 6 Suojärven Suvilahtea käsittelevää viitettä
