### ISSUE TITLE
lemmikkieläimet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9806]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[lemmikkieläimet](http://www.yso.fi/onto/yso/p675)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi seuraeläimet?

**Perustelut ehdotukselle**

https://www.kielitoimistonsanakirja.fi/#/seurael%C3%A4in?searchMode=all

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Sv. sällskapsdjur pääterminä.
