### ISSUE TITLE
laki kuvaohjelmien tarkastamisesta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9807]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[laki kuvaohjelmien tarkastamisesta](http://www.yso.fi/onto/yso/p10371)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisi olla Kuvaohjelmalaki

**Perustelut ehdotukselle**

"Tämä laki on kumottu L:lla 17.6.2011/710, joka on voimassa 1.1.2012 alkaen" https://finlex.fi/fi/laki/ajantasa/kumotut/2000/20000775 ja https://finlex.fi/fi/laki/ajantasa/2011/20110710

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Eli uudempi laki pitäisi oikeastaan ottaa lisäksi.

**Comment by mariaforsen** [comment]
Sv. lag om bildprogram
