### ISSUE TITLE
perinnelaivat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9808]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

perinnelaivat 

#### Ehdotettu termi ruotsiksi   

traditionsfartyg 

#### Ehdotettu termi englanniksi   

heritage ships 

#### Vaihtoehtoiset termit ja ilmaisut   

perinnealukset 

#### Ehdotettu yläkäsite YSOssa (LT)   

[laivat](http://www.yso.fi/onto/yso/p4911) 

#### Vastaava käsite muussa sanastossa   

MAO/TAO : <http://www.yso.fi/onto/mao/p5838> 
LIIKO : <http://www.yso.fi/onto/mero/m9391> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[39 Liikenne. Kuljetus. Posti. Pakkausteollisuus](http://www.yso.fi/onto/yso/p26577) 

#### Tarkoitusta täsmentävä selite   

Merenkulun tai huviveneilyn historian kannalta merkittäviksi arvioitu edelleen käytössä oleva alus. Aluksen tulee olla vähintään 50 vuotta vanha. https://www.museovirasto.fi/fi/palvelut-ja-ohjeet/tietojarjestelmat/perinnealusrekisteri 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helka.helsinki.fi/permalink/358UOH_INST/1h3k2rg/alma9932697613506253 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [perinnelaivat](http://finto.fi/yse/fi/page/Y509808)

**Comment by mariaforsen** [comment]
https://www.transportstyrelsen.se/sv/sjofart/Fartyg/Fartygstyper/traditionsfartyg/

HT traditionsbåtar, fi. perinneveneet?

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q2447856
