### ISSUE TITLE
pikavalokuvaus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9810]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

pikavalokuvaus 

#### Vaihtoehtoiset termit ja ilmaisut   

polaroid-kuvaus 
pikakamerat 
polaroid-kuvat 

#### Perustelut ehdotukselle   

minulla on teos: 978-952-7226-98-8

Tämä Parvs-kustantamon julkaisu. Teoksessa on polaroid-kameralla otettuja TAIDEkuvia. 
Ongelmana on, etten saa asiaa ilmaistua ja se on kuvien (estetiikan) kannalta oleellinen asia. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

978-952-7226-98-8 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [pikavalokuvaus](http://finto.fi/yse/fi/page/Y509810)

**Comment by fantsby-m** [comment]
Vastaavassa tapauksessa olen joskus tainnut laittaa 653-kentään sanan _Polaroid_.

**Comment by ilona-x** [comment]
VALO-ontologiassa mm.:
polaroid-kuvat
polaroidkamerat
https://finto.fi/valo/fi/search?clang=fi&q=polaroid*

**Comment by mirmaid** [comment]
Pikakameroita on useilla kameramerkeillä, joten yleisempi termi olisi varmaan parempi. VALOssa on myös _pikakuvat_, http://www.yso.fi/onto/valo/p1464, mutta tämä ehkä liian epämääräinen termimuoto.

**Comment by jarmosaarikko** [comment]
Wikidatassa on http://www.wikidata.org/entity/Q313695 pikakamera, instant camera KT **instant photography**, Polaroid
Wikipedia
https://en.wikipedia.org/wiki/Instant_camera
https://fi.wikipedia.org/wiki/Pikakamera
https://sv.wikipedia.org/wiki/Direktbildskamera
https://en.wikipedia.org/wiki/Category:Instant_photography
http://www.wikidata.org/entity/Q95920463 polaroid-kuva (hieman orpo käsite)

Kumpi on tarpeellisempi: toimintana "pikavalokuvaus" vai  oliona "pikavalokuvat"? 
Tarvittaessa erikseen "pikakamerat".

**Comment by mirmaid** [comment]
^ Ottaisin varmaan "pikavalokuvaus".

**Comment by ilona-x** [comment]
YLEllä pikakuvat tuottaa uutisia selfieistä ja instagram-kuvista https://yle.fi/uutiset/18-87128

**Comment by YSO-kokous** [comment]
### Päätös
Otetaan sanastoon muodossa pikavalokuvat OT Polaroid-kuvat
Lisätään määritelmä

**Comment by mariaforsen** [comment]
Sv. polaroidfotografier
