### ISSUE TITLE
täytäntöönpano

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9815]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[täytäntöönpano](http://www.yso.fi/onto/yso/p4246)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritellään, varsinkin suhteessa termiin toimeenpano, tai yhdistetään?

**Perustelut ehdotukselle**

Kielitoimiston sanakirja: täytääntöönpano=toimeenpano. Ruotsiksi vastineet verkställande, verkställighet, eli on selvennettävä. Vrt. myös eng. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ks. myös https://termipankki.fi/tepa/fi/haku/toimeenpano ja
https://termipankki.fi/tepa/fi/haku/t%C3%A4yt%C3%A4nt%C3%B6%C3%B6npano

Molemmat käytetty noin 4oo kertaa Melindassa, täytäntöönpano selkeästi enemmän oikeus- ja rangaistusasioissa, mutta sanastossa on myös rangaistuksen täytäntöönpano.

**Comment by mirmaid** [comment]
Tätä olisi varmaan helpompi ratkoa, jos kaikki sellaiset olisi siivottu pois, joissa kyseessä on _rangaistuksen täytäntöönpano_.

**Comment by mariaforsen** [comment]
Pitäisikö ohjata verkställighet (straff) fi. täytäntöönpano (rangaistukset) KÄYTÄ straffverkställighet fi. rangaistuksen täytäntöönpano?

**Comment by mirmaid** [comment]
^ Varmaan hyvä ohjata noin.

**Comment by mirmaid** [comment]
On aika paljon sellaista aineistoa, jossa kyse ei ole suoranaisesta rangaistuksesta, vaikka täytäntöönpanon perustana on oikeuden päätös tai oikeudellinen velvoite (esim. ulosoton tai lapsen huoltopäätöksen täytäntöönpano). 

Sitten taas voidaan puhua esim. direktiivin täytäntöönpanosta, mutta myös toimeenpanosta.

**Comment by mariaforsen** [comment]
Näin on, onko mahdollista käyttää näistä muista kuin rangaistuksista "toimeenpano" ja ohjausterminä "täytäntöönpano (toimeenpano)"? Näin olisi ruotsiksi, mutta jos ei ole suomeksi ok, niin ruotsiksi pitää keksiä jonkinlaisia tarkenteita?
https://termipankki.fi/tepa/fi/haku/toimeenpano
https://www.kielitoimistonsanakirja.fi/#/t%C3%A4yt%C3%A4nt%C3%B6%C3%B6npano?searchMode=all
https://valter.sanakirja.fi/all/all/toimeenpano
https://valter.sanakirja.fi/all/all/t%C3%A4yt%C3%A4nt%C3%B6%C3%B6npano

**Comment by mirmaid** [comment]
Jos _rangaistuksen täytäntöönpanon_ sijasta sanastossa olisi _tuomion täytäntöönpano_, se olisi käyttökelpoinen vähän nykyistä laajemmin. Toisaalta se ei ratkaisisi tilannetta kuitenkaan kovin pitkälle, koska kysymys voi riita-asioissa (tai esim. Euroopan ihmisoikeustuomioistuimen tapauksessa) olla tuomion sijasta ratkaisusta tai päätöksestä. Joissakin tilanteissa suomeksi puhutaan yksinomaan täytäntöönpanosta, esim. lapsen tapaamisoikeuden täytäntöönpano, ei toimeenpano. Myös kun kyse on tuomiosta, toimeenpano-sana saa "fyysisen" sävyn, mikä onneksi on vähemmän pulmallista nyt kun ei ketjuteta. Tämä tilanne siis esim. kun on kyse riita-asian tai talousoikeuden tuomiosta, joka ei ole rangaistuksen luonteinen, esim. https://melinda.kansalliskirjasto.fi/byid/007328275. 

Toisaalta mahdollinen tarkenne (esim. "oikeus") johtaisi kuitenkin siihen tilanteeseen, että ruotsiksi tarvittaisiin toisellekin termille tarkenne, ja lisäksi ehkä entistä suurempaan päällekkäisyyteen _rangaistuksen täytäntöönpano_ -termin kanssa. Mitä mieltä muut olette, voidaanko yhdistää täytäntöönpano KÄ _toimeenpano_, vaikka kaikissa yhteyksissä se ei suomeksi ihan luonteva olekaan?

**Comment by mariaforsen** [comment]
Ruotsiksi joo pitää molemmille lisätä tarkenne. Toinen voisi periaatteessa olla verkställande/verkställighet (juridik). Mutta mitä toinen sitten olisi?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _toimeenpano_, ohjaustermiksi _täytäntöönpano_.
