### ISSUE TITLE
urheilu

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9816]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[urheilu](http://www.yso.fi/onto/yso/p965)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Määritelmä/rajaaminen tai ruotsiksi "idrott och sport"? Rajautuuko käsite suomeksi laajemmin, eli sisältyykö esim. autourheilu, e-urheilu yms. sellaisia lajeja, joissa ruumillinen harjoitus ei ole keskiössä?

**Perustelut ehdotukselle**

Ruotsiksi on kaksi termivaihtoehtoa: idrott ja sport (nämä erikseen myös SAOssa). Ensimmäinen, joka on nyt pääterminä, rajautuu lähinnä ruumilliseen urheiluun (>>hierarkiaongelma). Ks. https://termipankki.fi/tepa/fi/haku/urheilu 

**Ehdottajan organisaatio**

ALLFO

**Comment by jtuohini** [comment]
YSO:n **liikunta**- ja **urheilu**-asiasanojen tarkka merkitys on jo pitkään askarruttanut myös suomeksi: puhekielessä on paljon yhdyssanoja, joissa "liikunta" ja "urheilu" ovat synonyymejä: liikuntatunti ~ urheilutunti, kuntoliikunta ~ kuntourheilu jne. Olisikin hyvä saada kummallekin asiasanalle selitys ja tarpeen tullen käyttöohje, jotta kuvailijat ja tiedonhakijat tietäisivät, mikä kyseisten asiasanojen ero on ja kumpaa käyttää.

**Comment by mirmaid** [comment]
Mielestäni tämä vastaa aika lailla yleistä käsitystä siitä, mitä urheilu on: https://fi.wikipedia.org/wiki/Urheilu#M%C3%A4%C3%A4rittely

Mielestäni siis urheilu = sport, https://sv.wikipedia.org/wiki/Sport#Sport_och_idrott ilmeisesti ruotsiksikin merkitys pitkälti sama nykyään?

**Comment by mariaforsen** [comment]
TEPA: "Idrott och sport är i det närmaste synonyma men kan ändå inte användas helt på samma sätt. Idrott har mer att göra med ansträngande kroppsövningar avsedda att öka kroppens prestationsförmåga med eller (ofta) utan redskap, oftast med tävlingsinslag, medan sport ofta har med lek och fritidsaktiviteter att göra. Sport är det ord som kommer i fråga när man använder mer avancerade redskap och när människans roll snarare är att styra än att röra på sig för egen kraft, t.ex. klassas formel 1 och hästsport som sport medan löpning och skidåkning är idrottsgrenar. Man talar också om motionsidrott och inte om motionssport." / https://termipankki.fi/tepa/sv/s%C3%B6k/sport

Kuten wikipediassakin mainitaan: **Ibland används begreppet "sport" inom dagens nordiska språk synonymt med idrott, även om det ofta kvarstår valörskillnader. Termen sport är ofta redskapsbaserad och omfattar även vissa aktiviteter som inte är fysiska och enligt en ännu vidare definition även spel** som frågesport och schack.[2] **Begreppet idrott kan också innefatta vissa aktiviteter som inte så ofta kallas sport, då de inte är redskapsdominerade, inklusive motionsidrotter** som joggning, stavgång, aerobics och aikido.

Eli toisin sanoen, pitää ehkä muuttaa > idrott och sport? Jos suomeksi urheilu kattaa näitä molempia, eli sekä oikeasti fyysisiä lajeja, joissa harjoitetaan ihan itsekseen, että myös hyvin vähän fyysisiä, kuten esim. e-urheilua ja jopa pelejä.

**Comment by mirmaid** [comment]
^ Joo, kyllähän suomeksikin osa kyseenalaistaa sen, pitäisikö e-urheilua tai shakkia ajatella urheiluna, ja varmasti aina välillä jossain keskustellaan siitä onko moottoriurheilu tai ampumaurheilu oikeaa urheilua. Mutta mitään muuta sanaa "fyysiselle urheilulle" ei ole olemassa, koska liikunta tarkoittaa ei-kilpailullista, lähinnä kuntoliikuntaa.

**Comment by YSO-kokous** [comment]
**Päätös**

Ei muutoksia suomeksi.

**Comment by mariaforsen** [comment]
AASI:n päätettäväksi vielä muutetaanko idrott > sport och idrott
