### ISSUE TITLE
sukupuolielämä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9817]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sukupuolielämä](http://www.yso.fi/onto/yso/p5897)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

seksuaaliset suhteet

**Perustelut ehdotukselle**

'Sukupuolielämä' on harhaanjohtava ja siksi syystäkin vanhentunut termi. Sekaannus ja termin alkuperä johtunee ruotsin ja engalnnin kielen sanojen 'sex' kaksoimerkityksestä: suomen sana sukupuoli ei kuitenkaan nykykielessä viittaa seksuaalisuuteen. Kun ihmiset etsivät tietoa seksuaalisuudesta, he kirjoittavat hakukenttään 'sukupuoli*' -sanan sijasta todennäköisemmin seksi*, seksuaalisuus, seksisuhteet, tai vastaavaa. Seksielämä olisi suorempi käännös ruotsin kielen vastaavasta avainsanasta, mutta suomen kielessä seksielämällä ei ole yhtä laajaa ja yhteiskunnallista konnotaatiota kuin seksuaalisuudella ja seksuaalisilla suhteilla. Nämä sopivat siis paremmin avainsanoiksi yhteiskunnallisten ilmiöiden alle ja tuottaisivat johdonmukaisia hakutuloksia..

**Ehdottajan organisaatio**

Helsingin yliopisto

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:
**sukupuolielämä**
sukupuolisuuden toteuttaminen elämässä, rakkaus-, seksuaali-, seksielämä. 
https://www.kielitoimistonsanakirja.fi/#/sukupuoliel%C3%A4m%C3%A4?searchMode=all

**Comment by mirmaid** [comment]
Onko näillä kuitenkin vähän erilainen kattavuus ja näkökulma: sukupuolielämä 1700-luvun Englannissa vs. seksuaaliset suhteet 1700-luvun Englannissa?

**Comment by mariaforsen** [comment]
Sv. https://id.kb.se/find?q=sexualliv

**Comment by krinay** [comment]
Seksuaalielämä? https://www.kielitoimistonsanakirja.fi/#/seksuaaliel%C3%A4m%C3%A4?searchMode=all
Jotenkin tosiaan tuntuu, että _seksuaaliset suhteet_ on vähän eri asia kuin _sukupuolielämä_. Mutta kumpi aspekti on tarpeellisempi, jos eroa on?

YSOssa on myös _seksuaalinen käyttäytyminen_ ja _sukupuolielämän_ ohjausterminä seksikäyttäytyminen.

**Comment by fantsby-m** [comment]
Kielitoimiston sanakirjan mukaan _seksuaalielämä, seksielämä_ ja _sukupuolielämä_ ovat synonyymejä.

**Comment by mirmaid** [comment]
Onko tämä niin ongelmallinen, että jotain pitäisi tehdä? Aihepiirin sanastoa on runsaasti, eikä sukupuolielämä kuulosta erityisen vanhentuneelta sellaisessa tutkimusaineistossa, jossa aiheena olisi seksi avioliitossa ja sen ulkopuolella, prostituutio, seksiin liittyvät normit ja käsitykset jossakin yhteiskunnassa tai jollain aikakaudella tms. Silloinkin varmasti käyttäisi sen lisäksi monia muita sanaston käsitteitä, mutta mielestäni se on ihan käyttökelpoinen juuri laajan kattavuutensa takia. Seksuaaliset suhteet tuntuisi viittaavan ensisijaisesti muihin suhteisiin kuin pysyvään parisuhteeseen tai satunnaiseen/maksulliseen seksiin.

**Comment by YSO-kokous** [comment]
### Päätös
lisätään ohjaustermit seksuaalielämä, seksuaaliset suhteet, seksielämä
Tarkistetaan seksi-käsitteen ohjaustermit
