### ISSUE TITLE
vihkiminen tehtävään

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9818]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vihkiminen tehtävään 

#### Perustelut ehdotukselle   

Vihkiminen-korjausta tehdessä tämä toistui usein, diakoniksi, munkiksi tms. vihkiminen. Pitäisikö ottaa erikseen? 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vihkiminen tehtävään](http://finto.fi/yse/fi/page/Y509818)

**Comment by jtuohini** [comment]
KT-muotona on syytä huomioida myös _vihkimys_ (https://www.kielitoimistonsanakirja.fi/vihkimys), joka esiintyy käytössä ainakin osana yhdyssanoja diakoninvihkimys, pappisvihkimys ja piispanvihkimys, joista ensimmäinen tosin harvinaisena.

**Comment by mariaforsen** [comment]
Sv. ordination/vigning till ämbete, ämbetsvigning Rajataan kai kirkollisiin tehtäviin?
 https://svenska.se/tre/?sok=ordination&pz=1

**Comment by YSO-kokous** [comment]
Siirretään ongelmakokoukseen

**Comment by AuHo22** [comment]
https://kirkkokasikirja.fi/toim/vihkimiset.html

**Comment by YSO-kokous** [comment]
**Päätös**

Siirretään myöhemmäksi.

**Comment by mariaforsen** [comment]
Onko tämä hieman epämääräinen termi tarpeen/hyödyllinen? Sanastossa on jo jotain tarkempia termejä (esim. pappisvihkimys, piispanvihkimys), voisiko niiden lisäksi ottaa muita tarkempia termejä, jos tarvitaan? 
https://kyrkohandboken.fi/forr/handledning_kyrkliga_forrattningar.pdf

**Comment by mirmaid** [comment]
Melindaa korjatessa siis diakonien vihkiminen toistui useita kertoja:

https://melinda.kansalliskirjasto.fi/byid/005948200
https://melinda.kansalliskirjasto.fi/byid/004784604
https://melinda.kansalliskirjasto.fi/byid/013460863
https://melinda.kansalliskirjasto.fi/byid/005192180
https://melinda.kansalliskirjasto.fi/byid/013903488 - tämän mukaan siis kuuluisi muutakin kuin varsinaiset diakonit. Eli jos halutaan tarkempi termi, niin mikä se on? Diakonian virkaan vihkiminen?

Lisäksi munkiksi vihkiminen:
https://melinda.kansalliskirjasto.fi/byid/013029688
https://melinda.kansalliskirjasto.fi/byid/014110270

**Comment by mariaforsen** [comment]
Kannatan: 
-diakonvigning = diakoniksi vihkiminen?
-munkvigning = munkiksi vihkiminen

**Comment by mirmaid** [comment]
Tuossa viimeisessä linkkaamassani viitteessä lukee kuvauksessa: _Virkarakennekomitea ehdottaa kirkolle hengellistä virkaa, diakonaattia, johon kuuluisi kyllä vihkimys, mutta josta puuttuisivat kirkon virkaan liittyvät oikeudet. Diakonaattiin kuuluisivat esim. diakonit, kanttorit, nuorisotyönohjaajat_. 

Siksi mietin siis termimuotoa _diakonian virkaan vihkiminen_, jos virkanimike ei välttämättä ole diakoni (vaan esim. kanttori). Ko. muoto on tuolla Aulin aiemmin linkkaamalla sivulla.

**Comment by ilona-x** [comment]
"diakonian virkaan vihkimys" -muotoa näyttää käytetyn useamman hiippakunnan (Espoo, Helsinki, Lapua, Tampere) verkkosivuilla, esim. https://www.espoonhiippakunta.fi/kirkkoon-toihin/diakonian-virkaan-vihkimys/
Ja lisäksi Turun arkkihiippakunnan sivuilta löyty muoto "diakonian vihkimys". https://www.arkkihiippakunta.fi/kirkkoon-toihin/diakonian-vihkimys/

Nyt YSOssa pappis**vihkimys** & piispan**vihkimys**, eli voisivatko uudet termit olla muodosssa diakonian (virkaan) **vihkimys** & munkki**vihkimys**?

**Comment by jtuohini** [comment]
Varmaan _**munkinvihkimys**_, KT _munkkisvihkimys_ ja _munkkivihkimys_. Entä _luostarivihkimys_ vai onko liian rajaava (ehkä sulkiessaan pois konventtiveljet)?

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään _diakonian virkaan vihkimys_ tai _diakonian vihkimys_.

**Comment by mariaforsen** [comment]
Sv. diakonivigning HT diakonvigning, diakonissvigning https://www.borgastift.fi/verksamhet/diakoni/
