### ISSUE TITLE
vihkiminen käyttöön

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9819]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

vihkiminen käyttöön 

#### Perustelut ehdotukselle   

Vihkiminen-korjausta tehdessä tämä toistui todella usein, eikä kyse aina ollut avajaisista tai käyttöönotto-käsite ei soveltunut. Esim. kirkkojen vihkimisestä oli aineistoa, jossa saatettiin käsitellä tapahtumaa keskiajalla. Käyttöön saatettiin myös vihkiä urut tai ikonostaasi. Toisaalta oli aineistoa tehtaiden, yritysten tms. vihkimisestä - halutaanko näitä mukaan samaan... 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

- 

**Ehdottajan organisaatio:** Kansalliskirjasto **Termiehdotus Fintossa:** [vihkiminen käyttöön](http://finto.fi/yse/fi/page/Y509819)

**Comment by mariaforsen** [comment]
Sv. invigning (ibruktagande)
Nu avajaiset = invigningar > öppningsceremonier
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_6acd0068315a0d4bb1e485a5f5f46ff7&list_id=1&keyword=vihki%C3%A4&word=vihki%C3%A4
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_13242dab061369c0bb29bf792a7f932f&list_id=1&keyword=avajaiset&word=avajaiset
https://svenska.se/tre/?sok=invigning&pz=1

**Comment by YSO-kokous** [comment]
siirretään ongelmakokoukseen

**Comment by jarmosaarikko** [comment]
MOT mukaan rakennuksen vihkiminen olisi "inauguration"  mutta wikipediassa liitetään _henkilön_ virkaan vihkimiseen.
Wikidatassa [inauguration ](https://en.wikipedia.org/wiki/Inauguration)-- vihkimistilaisuus

MOTissa kirkon vihkimien on "consecration"
Wikidatassa consecration http://www.wikidata.org/entity/Q125375 
Wikipediassa [consecration](https://en.wikipedia.org/wiki/Consecration) kuvaus viittaa sekä henkilöiden että objektien vihkimiseen (pyhittämiseen tms.)

Ehdotukseni käännösvastineeksi: **consecration**:  LCSH: http://id.loc.gov/authorities/subjects/sh85031237
Jos halutaan jakaa, niin voisi olla 
- vihkiminen tehtävään - consecration to office
- vihkiminen käytöön - consecration to purpose

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan muodossa _käyttöön vihkiminen_, ohjaustermiksi _vihkiminen käyttöön_. Tarkistetaan kirjoitetaanko yhteen vai ei.
