### ISSUE TITLE
Livonsaari (Askainen)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9820]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Livonsaari (Askainen)](http://www.yso.fi/onto/yso/p154137)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sulkeisiin Askaisten tilalle Naantali

**Perustelut ehdotukselle**

Livonsaari on liitetty vuonna 2011 Naantaliin. Lisäksi Askainen on tätä nykyä osa Maskua.

**Ehdottajan organisaatio**

Naantalin kaupunginkirjasto

**Comment by mirmaid** [comment]
KT Livonsaari (Askainen), Livonsaari (Masku), Livonsaari (Velkua)?
https://fi.wikipedia.org/wiki/Livonsaari

**Comment by mirmaid** [comment]
^ ok näin.
