### ISSUE TITLE
e-lehdet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9823]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

e-lehdet

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

e-kirjoille on oma terminsä, e-lehtiäkin kuvaillaan tai e-lehtitietokantoja.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Mikä tahansa yksittäin hankittu e-lehtinimeke

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [e-lehdet](http://finto.fi/yse/fi/page/Y509823)

**Comment by jtuohini** [comment]
Eli SLM-ehdotuksesta on kyse? Vanhastaan löytyy jo [**verkkolehdet**](http://urn.fi/URN:NBN:fi:au:slm:s50), jonka ruotsinkielisissä KT-muodoissa on listattuna _e-tidningar_ ja _e-tidskrifter_. Riittäisikö suomenkielisten KT-muotojen lisääminen vai pitäisikö itse päätermi vaihtaa?

**Comment by vthuhtal** [comment]
"Verkkolehdet" on vakiintunut käyttöön. SLM:ään voisi lisätä "e-lehdet" ohjaustermiksi

SLM
verkkolehdet http://urn.fi/URN:NBN:fi:au:slm:s50

YSO
verkkolehdet http://www.yso.fi/onto/yso/p13383
OHJAUSTERMIT e-lehdet

**Comment by mirmaid** [comment]
YSOssa onkin jo ko. ohjaus.
