### ISSUE TITLE
kansalaisopistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9825]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[kansalaisopistot](http://www.yso.fi/onto/ysa/Y95835) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Poistetaan eng. ohjaustermi community colleges - aiheuttaa sekaannusta 

#### Perustelut ehdotukselle   

https://en.wikipedia.org/wiki/Community_college 

#### Ehdottajan organisaatio   

Kansalliskirjasto

**Comment by mirmaid** [comment]
Tai vaihtoehtoisesti lisätään tarkenne ohjaustermille.
