### ISSUE TITLE
rumpurakenteet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9828]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[rumpurakenteet](http://www.yso.fi/onto/ysa/Y504487) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään tarkenne 

#### Perustelut ehdotukselle   

Jos käyttö halutaan rajata maarakennukseen, https://melinda.kansalliskirjasto.fi/byid/017405829

**Comment by mirmaid** [comment]
Ja jos rajaus ei tarpeen, niin ehkä ryhmien lisäys?

**Comment by mirmaid** [comment]
Eli saako käyttää rumpumaisista rakenteista missä tahansa kontekstissa? Jos ok, lisätään ryhmiä.

**Comment by ilona-x** [comment]
Mitenköhän tämä toimii eri kielillä? Nyt esim. englanniksi tämän vastine on culverts. Yritin katsoa tuota ehdotuksessa mainittua esimerkkiaineistoa, mutta en keksinyt, mitä termiä siinä on käytetty englanninkielisessä tiivistelmässä tuosta rummusta. 🤔 

Ehkä tämän termin rajaaminen maarakennukseen voisi olla helpompaa kuin laajentaa tämän käyttyöä kaikenlaisiin rumpuihin.

**Comment by mirmaid** [comment]
Eli tarkenne (maarakennus)?
