### ISSUE TITLE
sinfoniset runot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9829]
#### Ehdotuksen tyyppi   

Muutos olemassa olevaan käsitteeseen 

#### preflabel   

[sinfoniset runot](http://www.yso.fi/onto/ysa/Y104333) 

#### Tila   

Käsittelyssä 

#### Ehdotettu muutos   

Lisätään KT-muodot "sinfoniset runoelmat" ja "sävelrunot" SLM:n ja YSO:n puolella (siltä osin kuin ei jo ennestään ole) 

#### Perustelut ehdotukselle   

Tunnetaan myös näillä nimityksillä (ks. esim. https://fi.wikipedia.org/wiki/Sinfoninen_runo) 

#### Ehdottajan organisaatio   

Helsingin yliopiston kirjasto

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by mariaforsen** [comment]
Sv. HT tondikter
