### ISSUE TITLE
sydän (kuva)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9830]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

sydän (kuva) 

#### Tarkoitusta täsmentävä selite   

Kielitoimiston käsikirja käyttään ehdottamastasi käsitteestä muotoa "sydämenkuva".
https://www.kielitoimistonsanakirja.fi/#/syd%C3%A4menkuva
https://en.wiktionary.org/wiki/syd%C3%A4menkuva
Tätä voi käyttää nyt  653-kentässä.

Vaihtoehtoisia termejä esim. 
sydän (kuvio), sydän (motiivi), sydän (symboli), sydän (kulttuuri)
heart motif, heart shape, heart pattern 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

museoesineiden 

#### Perustelut ehdotukselle   

sydätä kuva-aiheena ei löydy KOKOsta 

**Ehdottajan organisaatio:** Espoon kaupunginmuseo **Termiehdotus Fintossa:** [sydän (kuva)](http://finto.fi/yse/fi/page/Y509830)

**Comment by mariaforsen** [comment]
Sv. hjärtsymbol HT hjärta (symbol) https://sv.wikipedia.org/wiki/Hj%C3%A4rta_(symbol)

**Comment by jarmosaarikko** [comment]
Wikidata
http://www.wikidata.org/entity/Q826930
LCSH
[Heart (shape)](http://id.loc.gov/authorities/subjects/sh00000374)

Kuvat ei käy yläkäsitteeksi, kun nämä sydänkuvat usein eivät ole teoksia.
ehdotan termiä **sydän (symbolit)** KT sydämenkuva  YK [symbolit](http://www.yso.fi/onto/yso/p2015) 
englanniksi "heart symbol" KT "heart shape", "heart motif" tai heart (shapes), heart (motifs)

Symbolit käsitteen alakäsitteissä on tällä hetkellä yksi yksikkömuotoinen käsite: hakaristi.

**Comment by mirmaid** [comment]
Ei ainakaan ensimmäisten sadan viitteen joukossa Melindassa (kaikkiaan 1300). Jos otetaan, toinen sydän tarvitsee tarkenteen (elimet?).

**Comment by ilona-x** [comment]
Melindassa sydän + symbolit tuottaa 7 osumaa:

- Symbolina sydän.
- The book of hearts / by Francesca Gavin.
- Alliierte im Himmel : populare Religiosität und Kriegserfahrung / Gottfried Korff (Hg.)
- Miksi ja milloin sydämen merkki liitettiin sydämeen?.
- Hjertets kulturhistorie : frå antikken til vår tid / Ole M. Høystad.
- Sydän taiteen ja populaarikulttuurin symbolina / Liisa Juhantalo.
- Masken i människohjärtat : om en symbol i Runebergs diktning / Tore Wretö.

**Comment by ilona-x** [comment]
https://tieku.fi/kulttuuri/mista-sydansymboli-on-lahtoisin

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään muodossa sydänsymboli OT sydän (symbolit), sydämenkuva
