### ISSUE TITLE
kvartersbutiker

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9832]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kvartersbutiker](http://www.yso.fi/onto/yso/p27334)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Asiasanalla ei ole tässä englanninkielistä versiota. 

**Perustelut ehdotukselle**

Tässä on vain suomenkielinen asiasana kaksi kertaa. 

**Ehdottajan organisaatio**

Åbo Akademis bibliotek

**Comment by fantsby-m** [comment]
Brick-and-mortar shops?

**Comment by jarmosaarikko** [comment]
kyllä  Wikipedia: [brick and mortar](https://en.wikipedia.org/wiki/Brick_and_mortar)
http://www.wikidata.org/entity/Q726870
https://www.sanakirja.fi/finnish-english/kivijalkakauppa

**Comment by mariaforsen** [comment]
Sv. on ollut kvartersbutiker (täydellistä vastaavuutta ei ole), ja se käännetään MOTissa: 
1.neighbourhood shop [corner shop](https://www.sanakirja.fi/custom/en-sv-fi/corner%20shop) 
2.SPEC. AMER. [convenience store](https://www.sanakirja.fi/custom/en-sv-fi/convenience%20store)

Stora finsk-svenska ordboken: 
kvartersbutik -en -er närbutik -en -er
erikoisliike specialaffär -en -er
pikkukauppa liten butik (mon) småbutiker

https://www.mediesprak.fi/det-heter-narkop

https://it-ord.idg.se/ord/bricks-and-mortar/

Wikipedia: "Keskustelussa termiä kivijalkakauppa käytetään usein **vertailukohtana [kauppakeskuksille](https://fi.wikipedia.org/wiki/Kauppakeskus), [automarketeille](https://fi.wikipedia.org/wiki/Automarketti) ja [tavarataloille](https://fi.wikipedia.org/wiki/Tavaratalo). Monesti kivijalkakaupalla tarkoitetaan lähellä olevaa pienikokoisempaa kauppapistettä, esimerkiksi [lähikauppaa](https://fi.wikipedia.org/wiki/L%C3%A4hikauppa), kun taas kauppakeskus, automarket ja tavaratalo kuvaavat kauempana sijaitsevia suuria kaupan keskittymiä.**
Käytännössä sanat kivijalkakauppa ja kivijalkaliike ovat siirtymässä tarkoittamaan [verkkokaupan](https://fi.wikipedia.org/wiki/Verkkokauppa) eli nettikaupan vastakohtaa, fyysistä liiketoimintaa tai liiketilaa, jossa asiakas kohdataan kasvokkain ja jossa tämä pääsee näkemään ja koskettamaan myytäviä tavaroita."

Ruotsin kannalta hyvin ongelmallinen termi ollut alusta asti. Tuo ehdotettu eng. taitaa sopia vain jos laajennetaan käsitteen merkitystä niin että se viittaa mihin tahansa fyysiseen kauppaan (vs. nettikauppaan), silloin vaihdetaan myös ruotsin termi, mutta se olisi sitten todennäköisesti "fysiska butiker" tms.
