### ISSUE TITLE
kodinsisustusliikkeet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9833]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kodinsisustusliikkeet

**Ehdotettu termi ruotsiksi**

heminredningsaffärer

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Nykyään IKEA:n yms. aikana on erikoista, ettei tämä ala ole saanut omaa asiasanaa. Pelkkä "huonekaluliike" ei mielestäni täysin kuvaa kodinsisutusalan nykytilaa. 

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [75 Taloustieteet. Kansantalous. Liiketalous. Kauppa](http://www.yso.fi/onto/yso/p26538), [94 Taideteollisuus. Sisustustaide](http://www.yso.fi/onto/yso/p26586), [98 Vapaa-aika. Harrastukset. Matkailu. Käsityöt](http://www.yso.fi/onto/yso/p26527)

**Vaihtoehtoiset termit**

 sisustusliikkeet

**Alakäsitteet (RT)**

 [sisustus](http://www.yso.fi/onto/yso/p9426), [koti](http://www.yso.fi/onto/yso/p5473), [huonekalut](http://www.yso.fi/onto/yso/p3684), [kodintekstiilit](http://www.yso.fi/onto/yso/p1115)

**Assosiatiiviset (RT)**

 [huonekaluliikkeet](http://www.yso.fi/onto/yso/p13502)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.doria.fi/handle/10024/182786

**Ehdottajan organisaatio**

Åbo Akademis bibliotek
**Termiehdotus Fintossa:** [kodinsisustusliikkeet](http://finto.fi/yse/fi/page/Y509833)

**Comment by ilona-x** [comment]
sisustusliikkeet Melinda x 3
kodinsisustusliikkeet ei Melindassa 


Kielitoimiston sanakirja https://www.kielitoimistonsanakirja.fi/#/sisustusliike?searchMode=all
sisustusliike 
sisustustekstiilejä yms. myyvä liike.

**Comment by mirmaid** [comment]
Olisiko sisustusliikkeet huonekaluliikkeiden yläkäsite?

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään muodossa sisustusliikkeet

**Comment by mariaforsen** [comment]
Sv. inredningsaffärer HT  inredningsbutiker, heminredningsaffärer, heminredningsbutiker
https://svenska.se/tre/?sok=aff%C3%A4r&pz=1
https://svenska.se/tre/?sok=butik&pz=1
