### ISSUE TITLE
matemaattinen fysiikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9836]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

matemaattinen fysiikka 

#### Ehdotettu termi englanniksi   

mathematical physics 

#### Vaihtoehtoiset termit ja ilmaisut   

Physical mathematics 

#### Ehdotettu yläkäsite YSOssa (LT)   

[fysiikka](http://www.yso.fi/onto/yso/p900) 

#### Vastaava käsite muussa sanastossa   

LCSH : <http://id.loc.gov/authorities/subjects/sh85082129> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Statistical physics 

#### Perustelut ehdotukselle   

Ysossa ei vanhastaan sopivaa asiasanaa. Käytetty Melindassa 37 kertaa. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [matemaattinen fysiikka](http://finto.fi/yse/fi/page/Y509836)

**Comment by mariaforsen** [comment]
Sv. matematisk fysik https://id.kb.se/find?q=Mathematical%20physics
