### ISSUE TITLE
sähköheikko faasimuunnos / sähköheikko faasitransitio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9837]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi englanniksi   

electroweak phase transition 

#### Ehdotettu termi suomeksi   

sähköheikko faasimuunnos / sähköheikko faasitransitio 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[07 Fysiikka](http://www.yso.fi/onto/yso/p26565) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Singlet-assisted electroweak phase transition at two loops 

#### Perustelut ehdotukselle   

Hyvin usein käytetty termi esim. fysiikan alan väitöskirjoissa, ei löydy YSOsta sopivaa. 

**Ehdottajan organisaatio:** Helsingin yliopiston kirjasto **Termiehdotus Fintossa:** [sähköheikko faasimuunnos / sähköheikko faasitransitio](http://finto.fi/yse/fi/page/Y509837)

**Comment by jtuohini** [comment]
Tommi Tenkasen kirjassa _Matka mustaan aukkoon_ käytetään muotoa _sähköheikko olomuodonmuutos_, joka varmaan myös KT:ksi.

**Comment by jarmosaarikko** [comment]
kuvattu jollakin tavalla täällä: https://en.wikipedia.org/wiki/Electroweak_epoch
Tätä käsitteleviä julkaisuja löytyy paljon, joten kannatan lisäämistä.

**Comment by mirmaid** [comment]
Kari Enqvistiltä löytyy esitys, jossa muoto sähköheikko faasimuutos, ja joitakin kertoja löytyy muodossa sähköheikko faasitransitio. Heldassa kerran sähköheikko faasitransitio.

**Comment by mirmaid** [comment]
Tämä kaipaisi ohjaustermejä: http://www.yso.fi/onto/yso/p2916.

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään muodossa **sähköheikko faasimuutos**  OT sähköheikko faasimuunnos, sähköheikko faasitransitio
Lisätään ohjaustermi faasimuutos KÄYTÄ aineen olomuodon muutos

**Comment by mariaforsen** [comment]
Sv. elektrosvag fasövergång
 https://sv.wikipedia.org/wiki/Elektrosvag_v%C3%A4xelverkan
https://sv.wikipedia.org/wiki/Fas%C3%B6verg%C3%A5ng
