### ISSUE TITLE
informaatikot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9839]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[informaatikot](http://www.yso.fi/onto/yso/p3249)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermi tietoasiantuntijat - TAI - vaihdetaan se päätermiksi
Vaihdetaan ohjaustermi "information specialists" päätermiksi ja
"information manager" ohjaustermiksi Tai kokonaan pois, sillä on lähempänä "data manager" -käsitettä. Jos se halutaan pitää, niin sitten voisi lisätä data mangerin ohjaustermiksi.  (vrt. data management KÄYTÄ information management)

**Perustelut ehdotukselle**

kirjastoissa on monessa paikassa siirrytty suomenkieliseen nimikkeistöön ja informaatikon koulutuksen saaneet toimivat yleensä tietoasiantuntijoina.  Specialist on vakiintuneempi asiantuntijan nimikkeenä. Manager on harvinaisempi eikä luultavasti vastaa suomalaisen tietoasiantuntijan toimenkuvaa.

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by ilona-x** [comment]
Metatietosanastossa molemmat: informaatikko http://urn.fi/URN:NBN:fi:au:mts:m2723 & tietoasiantuntija http://urn.fi/URN:NBN:fi:au:mts:m3979

**Comment by fantsby-m** [comment]
Molempia on edelleen kirjastoissa eivätkä tehtävät välttämättä ole suoraan toisiaan vastaavia.

**Comment by fantsby-m** [comment]
Monissa tapauksissa tietoasiantuntijan aiempi nimike ei olisi ollut informaatikko vaan kirjastonhoitaja. 
_Tietoasiantuntija_ tarvittaisiin ehkä omana terminään - tosin tämä olisi englannin kannalta hankalaa.

**Comment by mirmaid** [comment]
Samaa problematiikkaa kuin koulunkäynninohjaajien ja sairaalahuoltajien kohdalla...kyse ei ole ihan selkeästi erotettavista ammattinimikkeistä, mutta ei toisaalta myöskään täysin samasta asiasta.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään _tietoasiantuntijat_ uudeksi käsitteeksi, ei yhdistetä _informaatikoihin_.

**Comment by mariaforsen** [comment]
Sv. informationsspecialister HT informationsexperter
https://finto.fi/tt/sv/page/?clang=en&uri=t103
https://finto.fi/mts/sv/page/m3979
https://tieteentekijat.fi/sv/forbundet-nara-dig/medlemsforeningar/
