### ISSUE TITLE
sydämenhieronta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9840]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sydämenhieronta](http://www.yso.fi/onto/yso/p10109)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi paineluelvytys tai vaihdetaan päätermiksi paineluelvytys kuten FinMeSHissä?

**Perustelut ehdotukselle**

FinMeSH: paineluelvytys KT sydänhieronta, sydämenhieronta http://www.yso.fi/onto/mesh/D006336

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Ratkaisuehdotus: KÄ paineluelvytys.
