### ISSUE TITLE
kaupunkisaarekeilmiö

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9841]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kaupunkisaarekeilmiö

**Ehdotettu termi ruotsiksi**

urban värmeö

**Ehdotettu termi englanniksi**

urban heat island, UHI

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Kaupunkisaarekeilmiö on kaupunkialueiden ominaisuus, jonka seurauksena kaupunkialueen lämpötila nousee ympäristöään korkeammaksi.
https://fi.wikipedia.org/wiki/Kaupunkisaarekeilmi%C3%B6

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://urn.fi/URN:ISBN:978-951-827-354-0

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kaupunkisaarekeilmiö](http://finto.fi/yse/fi/page/Y509841)

**Comment by ilona-x** [comment]
LCSH:  **Urban heat island** http://id.loc.gov/authorities/subjects/sh85141317

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by fantsby-m** [comment]
Ilmatieteen laitos:
https://www.ilmatieteenlaitos.fi/ilmakeha-abc?term=Kaupunkisaarekeilmi%C3%B6

**Comment by mariaforsen** [comment]
Sv. urban värmeöeffekt HT urban värmeö-fenomen, urban värmeö, urban värmeö-effekt
