### ISSUE TITLE
koe-eläinmallit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9843]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koe-eläinmallit](http://www.yso.fi/onto/yso/p28104)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

voisiko tälle lisätä ohjaustermiksi eläinmallit, kun ruotsiksikin on ohjausterminä djurmodeller?

**Perustelut ehdotukselle**

FinMeSHIssä on eläinmalit http://www.yso.fi/onto/mesh/D023421

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Myös mesh https://finto.fi/mesh/fi/page/D023421
