### ISSUE TITLE
kivikirveet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9845]
#### Käsitteen tyyppi   

CONCEPT 

#### Ehdotettu termi suomeksi   

kivikirveet 

#### Ehdotettu termi ruotsiksi   

stenyxor 

#### Ehdotettu termi englanniksi   

stone axes 

#### Vastaava käsite muussa sanastossa   

SAO : https://id.kb.se/term/sao/Stenyxor 
MAO/TAO : <http://www.yso.fi/onto/mao/p4761> 

#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)   

[51 Arkeologia](http://www.yso.fi/onto/yso/p26593) 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

https://helsinki.primo.exlibrisgroup.com/permalink/358UOH_INST/1b30nf2/alma9924213023506253 

#### Perustelut ehdotukselle   

Käsitettä tarvitaan kirjastoaineiston kuvailussa. 

**Ehdottajan organisaatio:** Museoviraston kirjasto **Termiehdotus Fintossa:** [kivikirveet](http://finto.fi/yse/fi/page/Y509845)

**Comment by jarmosaarikko** [comment]
http://www.wikidata.org/entity/Q1540412 kivikirves|stone axe  vai  http://www.wikidata.org/entity/Q479448 käsikirves|hand axe
https://sv.wikipedia.org/wiki/Stenyxa#Handkil
https://en.wikipedia.org/wiki/Hand_axe
https://fi.wikipedia.org/wiki/K%C3%A4sikirves

MOT sanakirja: kivikirves - stone hatchet
