### ISSUE TITLE
kiertäjähermon stimulaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9846]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kiertäjähermon stimulaatio

**Ehdotettu termi ruotsiksi**

vagusnervstimulering

**Ehdotettu termi englanniksi**

vagus nerve stimulation

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sähköärsytyshoito](http://www.yso.fi/onto/yso/p38913)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

 vagusstimulaatio, vagushermon stimulaatio, VNS-hoito

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH: kiertäjähermon stimulaatio](http://www.yso.fi/onto/mesh/D055536), [wikipedia](https://en.wikipedia.org/wiki/Vagus_nerve_stimulation)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

VNS therapy for refractory epilepsy https://trepo.tuni.fi/handle/10024/123151

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [kiertäjähermon stimulaatio](http://finto.fi/yse/fi/page/Y509846)

**Comment by mirmaid** [comment]
Onpas kiertäjähermo on pinnalla...

**Comment by ilona-x** [comment]
Melinda:
vagushermostimulaatio x 4
vagushermostimulaattori x 1
vagushermostimulaattorihoito x 1
vagussimulaattorihoito x 1
vagusstimulaattorihoito x 1

**Comment by mariaforsen** [comment]
OT kiertäjähermon stimulointi?
HT vagusstimulering
