### ISSUE TITLE
nanosatelliitit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9847]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nanosatelliitit

**Ehdotettu termi ruotsiksi**

nanosatelliter

**Ehdotettu termi englanniksi**

nanosatellites

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [satelliitit](http://www.yso.fi/onto/yso/p5078)

**Ehdotetut temaattiset ryhmät**

 [06 Tähtitiede. Astronomia. Avaruustutkimus](http://www.yso.fi/onto/yso/p26588)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH ](http://id.loc.gov/authorities/subjects/sh2001000772), [wikipedia](https://fi.wikipedia.org/wiki/Nanosatelliitti)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Asteroid tomography by utilizing nanosatellites 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [nanosatelliitit](http://finto.fi/yse/fi/page/Y509847)

**Comment by mirmaid** [comment]
Yllättävää, että _mikrosatelliitit_ on käytetty vain yhdessä merkityksessä, vaikka sekin voi viitata pieniin satelliitteihin.
