### ISSUE TITLE
rehabilitointi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9848]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rehabilitointi

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

rehabilitation

**Tarkoitusta täsmentävä selite**

Palauttaa arvoonsa, julistaa syyttömäksi, todistaa syyttömyys

**Perustelut ehdotukselle**

Syyttömät, väärin perustein tuomitut voidaan rehabilitoida, maine, arvo ja kunnia palauttaa. Rehabilitointi-käsitettä on käytetty ainakin poliittisten vainojen kohteeksi joutuneiden ja kuolemaantuomittujen maineen puhdistamiseen ja samalla syyttömäksi julistamiseen postuumisti. Stalinin poliittisissa vainoissa menehtyneitä on rehabilitoitu vuosikymmenien jälkeen, jälkeen jääneiden omaisten ja sukulaisten lohduksi. Kyseisiä Neuvostoliitossa vaikuttaneiden ja vankileireillä kuolleiden poliittisten vainojen uhrien / suomalaisemigranttien rehabilitointi-asiakirjoja sisältökuvaillessani tämä käsite olisi hyödyllinen.

**Ehdotettu yläkäsite YSOssa (LT)**

 [kohdistuva toiminta](http://www.yso.fi/onto/yso/p38217), [maine](http://www.yso.fi/onto/yso/p3615)

**Ehdotetut temaattiset ryhmät**

 [52 Historia](http://www.yso.fi/onto/yso/p26540), [65 Valtio-oppi. Politiikka. Kansainvälinen politiikka](http://www.yso.fi/onto/yso/p26541), [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

 kunnianpalautus, maineenpalautus, syyttömyys, syyttömäksi julistaminen

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Esim. tämän arkistonmuodostajan alla olevaan aineistoon: https://www.finna.fi/Collection/ta_yksa.163705470356900 JA mm. tämä yksittäinen asiakirja: https://www.finna.fi/Record/ta_yksa.163705470356900_163853900912200/HierarchyTree?recordID=ta_yksa.163705470356900_163853900912200

**Ehdottajan organisaatio**

Työväen Arkisto
**Termiehdotus Fintossa:** [rehabilitointi](http://finto.fi/yse/fi/page/Y509848)

**Comment by ilona-x** [comment]
LCSH: Political rehabilitation http://id.loc.gov/authorities/subjects/sh86003246

**Comment by mirmaid** [comment]
Olisiko _maineenpalautus_ mahdollinen, ettei sekoittuisi mihinkään kuntoutus-merkitykseen? Tai tarkenne? Rehabilitointi käytetty 5 kertaa Melindassa.

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään muodossa rehabilitointi (maineenpalautus) OT rehabilitointi (politiikka), kunnianpalautus, ym.

**Comment by mariaforsen** [comment]
Sv. ja eng vastineet eivät ehkä voi olla LCSHn ja SAOn "poliittinen rehabilitointi", koska se on suppeampi merkitykseltään (ei kata esim. minkä tahansa ei-poliittisesti tuomitun rehabilitointia)?

Sv. rehabilitering (återupprättelse)
