### ISSUE TITLE
projektio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9851]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[projektio](http://www.yso.fi/onto/yso/p8992)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan/lisätään tarkenne?

**Perustelut ehdotukselle**

Monimerkityksinen termi ja Melindassa käytetty myös esim. psykologiasta. Kielitoimiston sanakirja: "1. geom. kuvion kuvaaminen suoralle t. pinnalle sädekimpulla, projisointi; siinä käytetty menetelmä; siten syntynyt kuvio. Pisteen projektiot x- ja y-akselilla. Janan projektio jllak suoralla. Karttaprojektio. 2. kuvanheittimellä tms. projisoitu kuva. 3. psyk. omien piirteiden tahaton sijoittaminen toisiin; yksilön psyykkisten voimien, viettien yms. ilmeneminen hänen suhtautumisessaan ulkoisiin seikkoihin."

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
https://fi.wikipedia.org/wiki/Projektio
https://svenska.se/tre/?sok=projektion&pz=1

**Comment by mirmaid** [comment]
Vain 49 kertaa Melindassa, mutta käyttö kyllä hajoaa ja matematiikan osalta on varsin vaikeaa...

Voisiko olla _projektio (piirustus)_, joka kattaisi tämän https://fi.wikipedia.org/wiki/Karttaprojektio ja tämän https://en.wikipedia.org/wiki/3D_projection?

_Projektio (psykologia)_ olisi myös helppo poimia erilleen.

**Comment by mariaforsen** [comment]
Olisin ruotsiksi voinut kuvitella projektion (avbildning) ja projektion (psykologi)

**Comment by mirmaid** [comment]
^ Mietin että sopiiko (mallinnus) tai (kuvaus) liiankin laajasti. https://en.wikipedia.org/wiki/Projection

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan käyttöön _projektio (psykologia)_ ja _projektio (mallinnus)_. Ohjaustermeiksi ensimmäiselle _psykologinen projektio_, _projisointi (psykologia)_. Tutkitaan psykologian osalta onko päätermi _projektio_ vai _projisointi_.

**Comment by mariaforsen** [comment]
Sv. -projektion (avbildning) https://svenska.se/saol/?hv=lnr71480
-projektion (psykologi) HT projicering (psykologi), psykologisk projektion
https://id.kb.se/term/sao/Projektion%20%28psykologi%29
https://sv.wikipedia.org/wiki/Projektion_(psykologi)
https://www.psykologiguiden.se/psykologilexikon/?Lookup=projektion
