### ISSUE TITLE
toteutus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9852]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[toteutus](http://www.yso.fi/onto/yso/p23615)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa?

**Perustelut ehdotukselle**

Todettu YSO-toimituskokouksessa että varsinkin kielivastineiden osalta tarvitaan mahdollisesti tarkennuksia/muutoksia.  Sanastossa on myös toteutuminen (lienee selvä suomeksi, mutta tällaista muotoa ei muilla kielillä ole ja sen takia englanniksi "realisation (passive)" ja ruotsiksi "bli förverkligad") Tämä termimuoto (toteutus) aiheuttaa myös lisähämmennystä koska se voi viitata kahteen asiaan: "1 toteuttaminen 2 toteuttamisen tulos." /Gummeruksen suomen kielen sanakirja. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Onko suomeksi mahdoton ajatus että pääterminä olisi vain toteutus ja muut muodot ohjaustermejä? 

Toteutuminen käytetty Melindassa 125 kertaa, sopisiko toteutus ainakin osaan viitteistä (mikään ei kuitenkaan toteudu aivan itsestään)..? 

Onko termi toteutuminen välttämätön tai antaako lisäarvoa sellaisissa tietueissa kuin esim: 
-Implementing inclusive education : a Commonwealth guide to implementing Article 24 of the UN Convention on the Rights of Persons with Disabilities  / Richard Rieser 
-Kuntauudistus prosessina : institutionaalinen johtajuus kuntamuutoksessa / Jenni Airaksinen... 
-Ohjaako yhteinen näky? : strategisen työskentelyn tilanne ja Meidän kirkko -strategian toteutumisen edistyminen seurakunnissa syksyllä 2010 / Terhi Jormakka
-SDP puoluekokouspäätökset 1999 : raportti toteutumisesta 27.5.2002 / SDP suunnittelusihteeristö.
-The Nordic implementation of UNSCR 1325 : a comparative evaluation / Pirjo Jukarainen, Eeva Puumala

Eikö näiden kohdalla ole kuitenkaan kyse melko aktiivisesta toteuttamisesta/toteutuksesta?

**Comment by AuHo22** [comment]
Kotimaisten kielten sanakirja: toteutus=toteuttaminen; sen tulos. 

https://www.kielikello.fi/-/heretkaa-toteuttamasta

**Comment by mirmaid** [comment]
^^ Oliko siis nyt niin, että ongelma on termissä _toteutuminen_, eikä _toteutus_?

**Comment by mirmaid** [comment]
Profetia tai ennuste ainakin taitaa toteutua ihan itsestään 🙂. Mutta yleensä näissä on kyse siitä, että aineistossa tarkastellaan, ovatko asetetut tavoitteet toteutuneet (onko esim. opetussuunnitelma toteutunut koulussa). Koulu voi pyrkiä toteuttamaan opetussuunnitelmaa, ja arvioitaessa tilannetta lukuvuoden lopussa todeta, että hyvästä yrityksestä huolimatta se ei kuitenkaan toteutunut resurssien riittämättömyyden takia.

Esim. 
https://melinda.kansalliskirjasto.fi/byid/015289575
https://melinda.kansalliskirjasto.fi/byid/015903317
https://melinda.kansalliskirjasto.fi/byid/013645976
https://melinda.kansalliskirjasto.fi/byid/009800149

_Toteutus_ keskittyisi siihen tapaan, millä johonkin tulokseen pyritään, _toteutuminen_ taas siihen, onko asetettuun tavoitteeseen ylipäätään päästy (tai missä määrin on päästy).

**Comment by mariaforsen** [comment]
Toteutuminen on näistä tietty suurin ongelma ruotsin kannalta, mutta lisähankaluuttaa tuo se että toteutus on monimerkityksinen.

**Comment by mirmaid** [comment]
Miten tuo toteutuminen kääntyisi noissa neljässä esimerkissäni edellä? (Eli tavoitteen/ennusteen/tasa-arvon/lain toteutuminen.)

**Comment by mariaforsen** [comment]
Ruotsinkielinen kuvailija tietty kuvailisi näitä kaikkia termillä förverkligande, eli fi. toteutus, ruotsiksi kun ei tehdä sitä passiivi-eroa samalla tavalla. Ennuste saattaisi olla erikoistapaus.

**Comment by mirmaid** [comment]
^ Ymmärrän, mutta ilmeisesti sitten förverkligande ei edellytä ihan niin selkeää "suorittamista" kuin toteutus, jos voidaan sanoa, että tasa-arvo "toteutettiin" - man förverkligade jämställdheten?

**Comment by mariaforsen** [comment]
Niin varmaan voisi sanoa että jämställdheten förverkligades tai man förverkligade.. mutta förverkligande ei ylipäätään normaalissa ruotsissa käytetä yhtä innokkaasti kuin suomeksi, ks. yllä mainittu: 

https://www.kielikello.fi/-/heretkaa-toteuttamasta 

https://www.sprakinstitutet.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/1986/forverkliga_ideer_och_missa_taget

**Comment by mirmaid** [comment]
Mietin siis, että suomeksi ei ole juuri merkitystä sillä, viittaako toteutus prosessin suorittamiseen (työllistämishanke toteutettiin rivakasti) vai "lopputulokseen" (työllistämishankkeen toteutus ontui). Sen sijaan aktiivisella ja passiivisella muodolla on merkitysero, joka voi johtaa virheisiin kuvailussa: aineistossa seksuaalivähemmistöjen tasa-arvon toteutumisesta kuvailu tasa-arvo + toteutus kuulostaisi melkoisen kummalliselta. Puhumattakaan tulevaisuutta koskevan ennusteen "toteutuksesta", mutta ilmeisesti siinä sentään ei ruotsiksikaan sopisi förverkligande. Ja ehkä siis förverkligande ei kauhean helposti tulisi ruotsiksi mieleen käyttää silloin jos kyse on passiivisesta toteutumisesta, vaikka se olisikin periaatteessa mahdollinen, mikä tietysti pienentää ongelmaa.

Mutta toteutuminen KÄ toteutus ei siis mun mielestäni ole ratkaisu mihinkään, koska vaikka noista 126:sta viitteestä osaan on mahdollista vaihtaa toteutus ilman että tapahtuu mitään kummallista (esim. vihreä siirtymä voi toteutua mutta se voidaan myös toteuttaa), niin osa asioista suomeksi toteutuu vain passiivisesti ja ne pitäisi ratkaista jollain muulla tavalla. Joissakin yhteyksissä taas toteutus-sana tuo vähän hassun "suorittavan" sävyn kuvailuun: Ariana Grande voi toteuttaa unelmansa poptähteydestä, mutta unelmat + toteutus kuulostaa siltä kuin homma hoituisi yhtä suoraviivaisesti kuin työpöydän siivous.

**Comment by mirmaid** [comment]
Tyypillisiä esimerkkejä toteutuvista asioista viitteissä ovat tavoitteet, ennusteet, oikeudet ja palvelujen/etuuksien saatavuus.

**Comment by vthuhtal** [comment]
"toteutus" ei tarkoita mitään. Minkä toteutus?

**Comment by mirmaid** [comment]
Olisikohan kuitenkin ongelmattomampaa jos jäisi toteutuminen...

**Comment by FinMeSHienPaimentaja** [comment]
Itse kaipaisin lääketieteen puolelle jotain aika ympäripyörää termiä, joka kävisi esim. erilaisten terveys- ja/tai sosiaalipalvelujen ja hankkeiden sekä toteutumisiin ja toteutumattomiksi jäämisiin, että toteuttamisiin ja toteuttamisyrityksiin ja vain yrityksiksi jääneisiin toteuttamisiin.

**Comment by mirmaid** [comment]
Kun katson näitä viitteitä (kovin perusteelliseen läpikäyntiin ei aika harmi kyllä riitä), tuntuu että _toteutus_ olisi usein vaihdettavissa > itsensä toteuttaminen tai > toimeenpano. Ruotsiksi osuvammalta tuntuu (sikäli kuin oma korvani nyt tätä oikein kuulee) ainakin toisinaan genomförande, sekin taitaa olla aika lähellä tuota toimeenpanoa. Mutta tämä nyt vain alustavaa pohdintaa, lähinnä jos kokouksessa jää noiden pitemmälle työstettyjen käsittelyn jälkeen vielä aikaa.

**Comment by AuHo22** [comment]
Selkeämpi merkitysten kannalta voisi siis olla tuo toteutuminen, jonka siis voisi kombinoida esim. haasteet (ongelmat)-termin kanssa silloin, kun jotain jää toteutumatta? Joissain tietueissa mielestäni termin toteutus voisi yksinkertaisesti jättää pois eikä haittaisikaan - tai sen voisi sitten korvata termeillä käyttöönotto tai toimeenpano, esimerkiksi erilaiset yritysstrategiat tai hallinnolliset suunnitelmat?

**Comment by YSO-kokous** [comment]
**Päätös**

Palataan seuraavassa YSO-kokouksessa. Siihen mennessä tutkitaan aiheutuuko yllä esitetystä muutoksesta mahdollisesti ongelmia.

**Comment by mariaforsen** [comment]
Eli päätermi olisi suomeksi toteutuminen ja ruotsiksi förverkligande, joka ei toki sulje pois "aktiivista toteuttamista" ? Jos tehtäisiin ruotsiksi vielä ohjauksena förverkligande (verkställande) ANV verkställande (fi. toimeenpano) niin se saattaisi auttaa vähän. 

On kyllä vaikeaa saada vastine juuri **toteutumiselle**, ks. esim. https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9a469d23dfe68c9202a9a8b5c73f6cec&list_id=1&keyword=toteutua&word=toteutua
https://www.sanakirja.fi/custom/all/toteutua

Olisiko englanniksi jatkossakin mystinen "realisation (passive)"?

**Comment by ilona-x** [comment]
Eli tässä nyt ilmeisesti kysymys siitä, että poistetaanko joko toteutus tai toteutuminen sanastosta? 

**toteutus** 
sanastoon v. 2007
Melinda x 599 (artikkelit pois lukien 457)

**toteutuminen** 
sanastoon v. 2012
Melinda x 132 (artikkelit pois lukien 76)

Melindassa toteutuminen on siis paljon vähemmän käytetty, mutta toteutus on ollut 5 vuotta pidempään sanastossa.

Viitteitä selatessa kumpikaan ei tunnu kaikissa tilanteissa välttämättömältä termiltä vaan suuri osa kuvailuista ei kärsisi, vaikka termin niistä poistaisi.

Toteutus-termiä on käytetty paljon suunnittelun parina ja tässä lisäksi joitain yleisiä yhdistelmiä:
suunnittelu & toteutus 210
suunnitelmat & toteutus 27
opetussuunnitelmat & toteutus 14
unelmet & toteutus 37
tavoitteet & toteutus 32
strategiat & toteutus 40
projektit & toteutus 53
innovaatiot & toteutus 13
uudistukset & toteutus 10
organisaatiomuutokset & toteutus 8

Joissain tilanteissa voisi termin poiston myötä jäädä kuvailusta pois jotain oleellista esim. Ratatöiden toteutustapojen valintaprosessi, osapuolten roolit ja yhteistyö.

Joissain tilanteissa toteutus voisi olla korvattavissa termeillä käyttöönotto, toimeenpano ja toteutuminen, mutta kovin yleisesti näitä ei ole käytetty samoissa tietueissa:
käyttöönotto & toteutus 13
toimeenpano & toteutus 14
toteutuminen & toteutus 2

Toteutuminen termillä on osin kuvailtu samankaltaisia aineistoja kuin toteutus-termilläkin (esim. tavoitteet, unelmat, suunnitelmat, uudistukset, strategiat).

Näistä termeistä ei kumpikaan välttämättä ole sellainen, jolla tiedonhakija tekisi hakuja, 🤔 Ja vaikka näkee tietueessa nimekkeen ja listan asiasanoista, ei silti aina pysty päättelemään, minkä asian toteutuksesta/toteutumisesta kulloinkin on kyse. 

Vähän vastaava tapaus [kohdentuminen/kohdentaminen ](https://github.com/Finto-ehdotus/YSE/issues/9715) ratkaistiin poistamalla kohdentuminen sanastosta.

Eli Melindan käyttömäärien perusteella poistaisin mieluummin tässäkin tapauksessa passivisen toteutumisen ja jättäisin toteutuksen sanastoon. Ja ilmeisesti toteutus (KT toteuttaminen)-termi olisi ruotsin kannaltakin parempi kuin toteutuminen?

**Comment by mariaforsen** [comment]
Kannatan yllä olevaa kommenttia ja kyllä, on myös helpompaa monikielisyyden kannalta jos termi on toteutus.

**Comment by mirmaid** [comment]
Jos niin kuin edellä on todettu ruotsiksi ei ole suurta intoa käyttää förverkligande-termiä ylipäätään, ei varmaan seuraa suurta ongelmaa siitä, että suomeksi toteutus sopii vain aktiiviseen tekemiseen. Kaikkea Melindan toteutumista ei voi korjata toteutus-termillä, mutta niistä sitten pitää vain jättää pois tämä tai siirtää 653:een.

**Comment by mariaforsen** [comment]
Kyllä, se että totetutus sopii vain aktiiviseen sopii erinomaisesti myös ruotsiksi.

**Comment by YSO-kokous** [comment]
PÄÄTÖS

Poistetaan toteutuminen sanastosta.
Lisätään RT-suhde: toteutus RT toimeenpano

**Comment by mariaforsen** [comment]
Sv. förverkligande
(bli förverkligad > -) 
https://www.kielitoimistonsanakirja.fi/#/toteutus?searchMode=all (på finska både "verksamheten och resultatet")
https://www.sanakirja.fi/custom/en-sv-fi/toteutus
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_46b334eff8c51a3f52e3e0b7e88bb1da&list_id=1&keyword=toteutus&word=toteutus
https://www.sprakinstitutet.fi/sv/publikationer/sprakspalter/reuters_rutor_1986_2013/1986/forverkliga_ideer_och_missa_taget
