### ISSUE TITLE
hapenpuute

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9864]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[hapenpuute](http://www.yso.fi/onto/yso/p19161)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Sanastossa myös happikato, anoksia, hypoksia. Onko osa näistä yhdistettävissä? Jäljelle jäävien käsitteiden merkityseroa pitäisi selkeyttää. 

**Perustelut ehdotukselle**

Todettu YSO-toimituskokouksessa: https://github.com/NatLibFi/Finto-data/issues/501

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Kannatan tarkenteiden lisäämistä jos pidetään useita termejä.

https://termipankki.fi/tepa/fi/haku/hapenpuute
https://termipankki.fi/tepa/fi/haku/happikato
https://termipankki.fi/tepa/fi/haku/anoksia
https://termipankki.fi/tepa/fi/haku/hypoksia

Kielitoimiston sanakirja:
hapenpuute: ei määritelmää
happikato:vähähappinen tila vars. luonnonvesissä
anoksia: ei löydy
hypoksia: ei löydy

MESH:
hapenpuute=eng. Hypoxia=syrebrist
happikato: ei löydy
anoksia: ei löydy
hypoksia → asfyksia= eng. Asphyxia=kvävning

Nationalencyklopedin:
Anoxi=syrebrist i vävnader eller organ
Asfyxi= brist på syre i inandningsluften eller i blodet
Hypoxi=syrebrist

Ruotsin kannalta ainakin syresvinn fi. happikato on ylimääräinen.

**Comment by FinMeSHienPaimentaja** [comment]
Äkkiseltään ajateltuna "anoksia" on (lähes) täydellinen hapenpuute, "hypoksia" on vähähappisuus, joskin elävässä elämässä varmaan niitä käytettäneen ei niin kovin täsmällisesti/tarkasti. Huom. näköjään tämän teeman  FinMeSH:it kaipaavat myös päivitystä eli eivät ole mielestäni tarpeeksi täsmällisiä/selkeitä.

**Comment by ilona-x** [comment]
> Ruotsin kannalta ainakin syresvinn fi. happikato on ylimääräinen.

Mutta jos happikato poistetaan, mitä termiä käytettäisiin vesistöjen happikadosta? 🤔 

YSOssa [happikadolla ](https://finto.fi/yso/fi/page/p11510)määritelmä:
"Hapen merkittävä väheneminen tai loppuminen vesistä. -- Ympäristösanasto TSK 27"

YSO:n hierarkia: [tapahtumat ja toiminta](https://finto.fi/yso/fi/page/p15238) > [tapahtumat](https://finto.fi/yso/fi/page/p2108) > [fysikaaliset tapahtumat](https://finto.fi/yso/fi/page/p27715) > happikato

Happikato myös AFOssa http://www.yso.fi/onto/afo/p382

-----------------------------------------------

SAO:ssa:
**Hypoxi (vatten)** https://id.kb.se/term/sao/Hypoxi%20%28vatten%29%20
alternative label
Hypoxia
Syrebristzoner (vatten)
Syrefattiga havsbottnar

**Anoxi (vatten)** https://id.kb.se/term/sao/Anoxi%20%28vatten%29%20
alternative label
Anoxicitet
Döda havsbottnar
Syrebristzoner (vatten)
Syrefria havsbottnar 

--------------------------------

LCSH:

**Hypoxia (Water)** http://id.loc.gov/authorities/subjects/sh2001005452

**Anoxic zones** http://id.loc.gov/authorities/subjects/sh2006006277

**Comment by FinMeSHienPaimentaja** [comment]
Lääketieteen termit:

**anoksia**
anoxia la, anoxia e, anoxi -n r (< an- kr ei + oxys kr hapan) (kudosten) **hapettomuus;** vrt. asfyksia, hyperoksia, hypoksia, iskemia

**asfyksia**
asphyxia la, asphyxia e, asfyxi -n r (< a- kr ei + sphyxis kr pulssi) **1. hengitysvajaus | happivajaus ja samanaikainen hiilidioksidin kertyminen elimistöön;** 2. vanh. (sikiöstä tai vastasyntyneestä:) sykkeettömyys

**hypoksia**
hypoxia la, hypoxia e, hypoxi -n r (< hypo kr alla + oxys kr hapan) (kudosten) **hapen niukkuus;** vrt. anoksia, hyperoksia

**Comment by ilona-x** [comment]
anoksia ja hypoksia ovat YSO:ssa hapenpuutteen alakäsitteitä

[tapahtumat ja toiminta](https://finto.fi/yso/fi/page/p15238) > [ilmiöt](https://finto.fi/yso/fi/page/p3974) > [olosuhteet](https://finto.fi/yso/fi/page/p25374) > [hapenpuute](http://www.yso.fi/onto/yso/p19161)

**Comment by mariaforsen** [comment]
_Mutta jos happikato poistetaan, mitä termiä käytettäisiin vesistöjen happikadosta?_

Vastaus: Ruotsin osalta se olisi syrebrist (hapenpuute, onkin myös ryhmässä 18) ja/tai anoxi, hypoxi.  
https://www.rikstermbanken.se/search?q=syrebrist&s=termer
https://termipankki.fi/tepa/fi/haku/happikato
https://termipankki.fi/tepa/fi/haku/hapenpuute
Mutta termivalinta taitaa vaihdella eri kielillä ja erikoisaloilla, senkin takia olisi tärkeä saada nämä termit tarkennettua.. Ruotsin osalta syresvinn on ylimääräinen, mutta tarvitaanko suomeksi sekä hapenpuute että happikato, ja niiden lisäksi vielä anoksia ja hypoxia?

**Comment by tpalonen** [comment]
EHDOTUS
Näkisin tässä yhdistämismahdollisuuden lääketiedekäsitteille eli ehdottaisin, että yhdistetään hypoksia ja hapenpuute. Kannatan tätä yksinkertaisesti siitä syystä, että näin on tehty MESHissäkin (englanniksi: oxygen deficiency -> Hypoxia). Yhdistää voisi myös hypoksian ja anoksian. Tätä puoltaisi esim. anoksian ja hypoksian merkitysten läheisyys, MESHin Anoxia, Cell -> Cell Hypoxia -ohjaustermi, sekä anoksian vähäinen käyttö Melinda-kuvailussa, mutta ensisijaisesti asetun kannattamaan tuota hypoksian ja hapenpuutteen yhdistämistä.

PERUSTELUJA
Tarkennuksena tuohon keskustelussa edellä mainittuun MESHin tilanteeseen, että siellä näköjään suomenkieliset termit vähän sekoittavat pakkaa.
- Asphyksia (en) -käsitteellä on englannin ohjaustermeinä suffocation ja suffocations. Suomenkielen pääterminä on asfyksia ja ohjaustermeinä asphyxia, hapenpuute, hapenpuutetila, hypoksia, hypoxia. https://finto.fi/mesh/fi/page/D001237?clang=en
- Kuitenkin MESHistä löytyy erikseen käsite Hypoxia (en), jossa enkun ohjaustermeinä oxygen deficiencies ja oxygen deficiency. Suomen pääterminä hapenpuute ja ohjaustermeinä, hapen niukkuus, hapen puute, vähähappisuus. https://finto.fi/mesh/fi/page/D000860?clang=en
Eli katsoisin tässä enemmänkin MESHin englannin termejä. Selvennyksenä suomen osalta siis MESHIssä hapenpuute on sekä Asphyksia-käsitteen ohjaustermi että Hypoxia-käsitteen päätermi ja toisaalta suomen termi hypoxia/hypoksia kuitenkin ohjaa Asphyksia-käsitteeseen, ei Hypoxia-käsitteeseen kuten varmaankin pitäisi.
- Anoxia-käsitettä MESHissä ei sellaisenaan ole, vaan löytyy ainoastaan ohjausterminä Anoxia, Cell / Anoxia, Cellular käsitteelle Cell Hypoxia (suomen pääterminä tässä soluhypoksia, ohjaustermeinä solujen hypoksia ja solun hypoksia). https://finto.fi/mesh/fi/page/D015687?clang=en

Tuntuu, että eri sanastoissa termejä on yhdistelty ja eritelty vähän eri tavalla. LCSH:ssa ja Wikipediassa on omat koukeronsa. En tiedä auttaako tai hankaloittaako niiden siteeraaminen tässä (älkää siis lukeko seuraavia lauseita!). LCSH:ssa on Cerebral anoxia ja sen lisäksi Anoxemia, en-Wikipediassa taas Hypoxia ja lisäksi Hypoxemia. Anoxemia ja hypoxemia liittyvät hapenpuutteeseen veressä, anoxia ja hypoxia hapenpuutetilaan kudoksessa tai kudoksen heikkoon hapensaantiin, missä merkityksessä tulevat taas sitten varsin lähellä anoxiaa ja hypoxiaa.

Anoksia ja hypoksian näyttävät olevan samaa jatkumoa, hypoksiassa happea on kudoksissa vain vähän, anoksiassa ei ollenkaan. Wikipedia: "Hypoxia in which there is complete absence of oxygen supply is referred to as anoxia." https://en.wikipedia.org/wiki/Hypoxia_(medical)

Melindassa YSOn käsitteitä on käytetty seuraavasti: hapenpuute 167 kertaa, hypoksia 123, anoksia 22.

PS. YSOssa hapenpuutteen englannin pää/ohjaustermiksi oxygen deficiency?

**Comment by tpalonen** [comment]
UUSI EHDOTUS
hapenpuute (lääketieteellinen)
hapenpuute / happikato (ei-lääketieteellinen)
(+ ehkä voisi säilyttää anoksian erillisenä käsitteenä, mutta toisaalta en tiedä tarvitaanko YSOssa näin spesifiä käsitettä lääketiede-hapenpuutteen rinnalle)

PERUSTELU
No niin, just kun olin edellä kirjoittanut pitkän sepustuksen niin huomasin, että hapenpuute siis YSOssa on ilmeisesti monimerkityksinen käsite eli tarkoittaa sekä eläimen että vaikkapa vesistön hapenpuutetta (vrt YSO-ryhmät)? No, jos näin on niin ehkä voisi olla yksi lääketieteellinen hapenpuute-käsite ja yksi ei-lääketieteellinen hapenpuutekäsite. Ja tämän lääketieteellisen hapenpuute-käsitteen lisäksi minusta sanastossa ei tarvita erikseen hypoksia-käsitettä, ja myös anoksia-käsite voitaisiin tähän samaan yhdistää (anoksia kun on tuollainen hapenpuutteen erikoistapaus ja en tiedä tarvitaanko YSOssa hienojakoa juuri tässä kohtaa).

**Comment by mirmaid** [comment]
^ Meillä ei kyllä ole mitään (ei-x)-tarkenteita, ja melkein sanoisin ettei tulekaan 😉.

Ruotsin kannalta ilmeisesti ongelmana on ennen kaikkea _happikato_, ja se on siis käsite, joka liittyy nimenomaan vesistöihin. Suomeksi happikato on tapahtuma, kuten @ilona-x jo tuolla aiemmin kommentoikin, siis _hapen väheneminen vesistössä_. Samaa sarjaa, kuin vaikka vesistön _rehevöityminen_ tai _saastuminen_.

**Comment by ilona-x** [comment]
https://en.wikipedia.org/wiki/Hypoxia_(environmental)
https://sv.wikipedia.org/wiki/Syrgasbrist
https://fi.wikipedia.org/wiki/Happikato

**Comment by YSO-kokous** [comment]
**Päätös**

Ehdotettu happikato-termin korvaamista käsitteellä _hapenpuute (ympäristö)_. Toiselle lisätään tarkenne _hapenpuute (lääketiede)_. Jatketaan seuraavassa kokouksessa.

**Comment by AuHo22** [comment]
https://fi.wikipedia.org/wiki/Happipitoisuus_(limnologia)

**Comment by mariaforsen** [comment]
Kannatan viime YSO-kokouksen ehdotusta, näin saadaan myös monikielisyys toimimaan näiden käsitteiden kohdalla. 
Sv. 
-syrebrist (medicin) HT anoxi, hypoxi
-syrebrist (miljö)
https://mesh.kib.ki.se/term/D000860/hypoxia
https://www.rikstermbanken.se/search?q=syrebrist&s=termer
https://termipankki.fi/tepa/fi/haku/hapenpuute

**Comment by mirmaid** [comment]
Oliko toive, että joka tapauksessa erotettaisiin hapenpuute (lääketiede) ja anoksia (lääketiede) ja hypoksia (lääketiede) tulisivat sen ohjaustermeiksi?
Toisinaan voi olla vähän liian rajaava, esim. https://melinda.kansalliskirjasto.fi/byid/013817887, https://melinda.kansalliskirjasto.fi/byid/013905640, https://melinda.kansalliskirjasto.fi/byid/013630862

Entä _hapenpuute (fysiologia)_? (tai ohjaustermiksi hapenpuute (fysiologia), hapenpuute (urheilu))
Toki on myös kasvifysiologiaa, mutta en sitten osaa sanoa, mihin niiden aineistojen oikeastaan pitäisi mennä meidän jaottelussamme. (esim. https://helda.helsinki.fi/items/422fff79-ed33-4928-90f4-66db118b97cc)

Tämän tyyppiset aineistot eivät ehkä helpolla sovi mihinkään, jos tarkennetaan jollain "ympäristö"-tyyppisellä:  https://melinda.kansalliskirjasto.fi/byid/014013646, https://melinda.kansalliskirjasto.fi/byid/006092540 ...tai https://melinda.kansalliskirjasto.fi/byid/013267911 (ympäristö vähän eri tavalla ajateltuna). Toisaalta happikato-termiä on käytetty niin johdonmukaisesti vesistöistä, että tuntuisi paremmalta rajata kuitenkin vesistöihin kuin ympäristöön yleisesti. En tiedä voisiko noissa muissa tapauksissa kiertää jollain muulla happi + x -kuvailulla, tai 653...

**Comment by tpalonen** [comment]
Mirjan kysymyseen hapenpuutteesta ja anoksiasta: siteeraan itseäni: _"tämän lääketieteellisen hapenpuute-käsitteen lisäksi minusta sanastossa ei tarvita erikseen hypoksia-käsitettä, ja myös anoksia-käsite voitaisiin tähän samaan yhdistää (anoksia kun on tuollainen hapenpuutteen erikoistapaus ja en tiedä tarvitaanko YSOssa hienojakoa juuri tässä kohtaa)."_

**Comment by FinMeSHienPaimentaja** [comment]
Samoilla linjoilla tpalosen kanssa: kreikaksi tuo on ihan selvää, mutta suomeksi ja nykylääketieteeksi ei niin selvää maallikoille, joten turhaa hiustenhalkomista tässä yhteydessä välttäisin eli ali siitä mistä aita matalin tässä kohden.

**Comment by mirmaid** [comment]
Mun puolestani voidaan näin tehdä, mutta tarkenne (lääketiede) on siis mielestäni vähän pulmallinen urheilua käsittelevissä aineistoissa.

**Comment by FinMeSHienPaimentaja** [comment]
Onnistuisiko hapenpuute (elimistö) tms.? Niin erottaisi hapenpuute (ympäristö) tms.? PS. Olen mieltynyt "happikatoon", olkoonkin, että sitä oli jo aiemmin käsitelty.

**Comment by YSO-kokous** [comment]
**Päätös**

Toimitaan yllä viimeisimpänä ehdotetun mukaisesti: _hapenpuute (elimistö)_, ohjaustermeiksi _anoksia (elimistö)_ ja _hypoksia (elimistö)_ toinen _happikato (vesistöt)_.

**Comment by mariaforsen** [comment]
Sv.
-syrebrist (kroppen) HT anoxi (medicin), hypoxi (medicin)
Ska avse människor och djur, ej växter.
-syrebrist (vatten) HT syresvinn (vatten), hypoxi (vatten), anoxi (vatten)
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_af67988b8ba0468862c9d98035953467&list_id=1&keyword=happikato&word=happikato
https://termipankki.fi/tepa/fi/haku/happikato
https://www.rikstermbanken.se/search?q=syrebrist&s=termer
https://www.vesi.fi/sv/sanasto/syrebrist/
https://id.kb.se/term/sao/Hypoxi%20%28vatten%29%20
https://id.kb.se/term/sao/Anoxi%20%28vatten%29%20
