### ISSUE TITLE
Morbacka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9865]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Morbacka](http://www.yso.fi/onto/yso/p13979)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Siirretään Kantoon? 

**Perustelut ehdotukselle**

On asuinyhteisö. Ks. myös https://fi.wikipedia.org/wiki/Morbackan_hiljaisuuden_yhteis%C3%B6

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tämä on nyt auktorisoitu Kantoon ja voidaan näin ollen poistaa YSOsta.
