### ISSUE TITLE
montaasi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9866]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[montaasi](http://www.yso.fi/onto/yso/p8230)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitääkö tarkentaa? Mihin kaikkeen saa käyttää suomeksi?

**Perustelut ehdotukselle**

Gummerus suomen kielen sanakirja:  "1 mm. elokuvan leikkaus, koostaminen 2 valokuvista tehty kuvakooste 3 yleensä kokoonpano, kokoaminen, asentaminen". Ainakin ruotsiksi tämä käytetään sen lisäksi myös kirjallisuudessa. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Ryhmänä on nyt siis vain 96 Valokuvaus. Elokuva, pitäisikö lisätä muitakin, esim. Kirjallisuus?

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Montage

**Comment by mirmaid** [comment]
Riittääkö ryhmien lisäys?

**Comment by mariaforsen** [comment]
Ruotsiksi montage on: "(konstnärlig) helhet som ut­gör en sammanfogning av skilda element" eli siinä mielessä riittäisi ryhmien lisäys, mutta se voi periaatteessa myös viitata "asentamiseen". Melindassa ei tosin näytä olevan käytetty siitä. Ainakin ruotsiksi olisi ehkä kuitenkin parasta lisätä yllä mainittu huomautus.

**Comment by AuHo22** [comment]
Kollaasit -termin yhteydessä käytetty 90 Taide yleensä -ryhmää
Esim. https://trio.journal.fi/article/view/113281/66899 sekä kirjallisesta että musiikillisesta montaasista

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään ryhmät 87, 89 ja 90 nykyisen 96 lisäksi.
