### ISSUE TITLE
diilerit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9867]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[diilerit](http://www.yso.fi/onto/yso/p7601)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään tarkenne tai jaetaan?

**Perustelut ehdotukselle**

Ruotsiksi langare = "person som bedriver olaglig handel med sprit, narkotika e.d." Kaunossa käytetty myös samassa merkityksessä. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Jos kyseessä on "pankeissa ulkomaanpankkien kanssa valuuttakauppaa käyvä virkailija" (Kielitoimisto) niin ruotsiksi dealer + tarkenne tai valutahandlare/dealer? Voiko kuitenkin olla muutakin kuin valuutta kysessä?

**Comment by mirmaid** [comment]
Käytetty Melindassa vain 2 kertaa, toinen valuuttakauppaan liittyen, toisesta ei oikein pysty tulkitsemaan merkitystä. Onkohan koko termi tarpeen?

**Comment by mirmaid** [comment]
Ratkaisuehdotus: poistetaan.
