### ISSUE TITLE
Akko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9868]
#### Käsitteen tyyppi   

GEO 

#### Ehdotettu termi suomeksi   

Akko 

#### Vaihtoehtoiset termit ja ilmaisut   

Akka 
Acre 

#### Perustelut ehdotukselle   

Kaupunki jota ei ole YSO-paikoissa. Nykyään Israelin alueella. 

#### Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)   

Pillars of light 

**Ehdottajan organisaatio:** Kirjastopalvelu **Termiehdotus Fintossa:** [Akko](http://finto.fi/yse/fi/page/Y509868)

**Comment by jarmosaarikko** [comment]
Kaupunki on vaihtanut nimeä ja omistajaa lukuisia kertoja 4000 vuoden aikana.
KT Acco, Accho, Akka
- http://www.wikidata.org/entity/Q126084 
- https://fi.wikipedia.org/wiki/Akko   
- https://sv.wikipedia.org/wiki/Akko
- https://en.wikipedia.org/wiki/Acre,_Israel
- http://id.loc.gov/authorities/names/n80001043
- http://id.loc.gov/rwo/agents/n80001043

Wikidataan talletettu edeltäjiä eri käsitteinä:
Edeltäjä
- http://www.wikidata.org/entity/Q28197137  - Sainct-Jehan-d'Acre, Saint John of Acre
Edeltäjä
- http://www.wikidata.org/entity/Q92277123  - Ptolemais in Phoenicia
Edeltäjä
- http://www.wikidata.org/entity/Q93227102 - Antiokia Ptolemais  
Edeltäjä
- http://www.wikidata.org/entity/Q90908609 - Ake
