### ISSUE TITLE
onnellisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9870]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[onnellisuus](http://www.yso.fi/onto/yso/p2416)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään ohjaustermiksi "onni (onnellisuus)" sekä "joy"

**Perustelut ehdotukselle**

Käsitteet onni ja onnellisuus ovat menneet kuvailussa helposti sekaisin.  "joy" ei ole sanastossa.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by krinay** [comment]
YSOssa termin _ilo_ englanninkielinen vastine on _joy_.

**Comment by mirmaid** [comment]
Toisaalta onni ja onnellisuus ovat niin läheisiä käsitteitä, että niiden esiintyminen samoissa tai samankaltaisissa viitteissä ei välttämättä kerro sekoittumisesta.

**Comment by YSO-kokous** [comment]
### Päätös
Ei tehdä ehdotettuja muutoksia.
