### ISSUE TITLE
ruokaohjelmat (televisio-ohjelmat)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9872]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ruokaohjelmat (televisio-ohjelmat)](http://www.yso.fi/onto/yso/p27861)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ruoka-ohjelmat (media) tms..?

**Perustelut ehdotukselle**

Ruokaohjelmia tulee myös radiossa ja nykyään netissäkin, eli televisio-ohjelmat on liian rajaava sulkutarkenteena. Ks. esim. https://areena.yle.fi/audio/1-3014306 ; https://areena.yle.fi/audio/1-3014306 ;  https://areena.yle.fi/audio/1-4482948 ja myös esim. Youtube. 

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Sama koskee myös vaaliohjelmia.

**Comment by mirmaid** [comment]
Eli varmaankin ehdotettu tarkenne (media), jota jonkin verran jo käytetty. Pieni virheen riski tuossa on, jos joku tulkitsee ketjutyyppisesti (miten ruokaohjelmia - joka on muutenkin monimerkityksinen - tms. käsitellään mediassa). Sama pätee kuitenkin muihinkin vastaaviin ja teoriassa myös nykyiseen tarkenteeseen, vaikka sen suhteen tuskin kukaan erehtyisi.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: ruokaohjelmat (media).
