### ISSUE TITLE
majat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9879]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[majat](http://www.yso.fi/onto/yso/p2254)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan.

**Perustelut ehdotukselle**

Ruotsiksi kojor. Muunkieliset vastineet riippuvat siitä mihin tällä viitataan.  Ruotsin kannalta majat AK ulkoilumajat on virhe.

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
Tarkastellaan muutkin alakäsitteet: 
Onko "huts" sama kuin "cabins"? vrt. [cabins (buildings)](http://www.yso.fi/onto/yso/p1618)  = stugor = tuvat (rakennukset)
- [fäbodar](https://finto.fi/yso/fi/page/p12231?clang=sv) | [cowherd's cottages](https://finto.fi/yso/fi/page/p12231?clang=en) | karjamajat
- [fiskarstugor](https://finto.fi/yso/fi/page/p38228?clang=sv) | [fishing huts](https://finto.fi/yso/fi/page/p38228?clang=en) |kalamajat
- [jaktstugor](https://finto.fi/yso/fi/page/p757?clang=sv) | [hunting lodges](https://finto.fi/yso/fi/page/p757?clang=en) | metsästysmajat
- [raststugor](https://finto.fi/yso/fi/page/p2770?clang=sv) | [recreational lodges](https://finto.fi/yso/fi/page/p2770?clang=en) | ulkoilumajat
- [sportstugor](https://finto.fi/yso/fi/page/p2773?clang=sv) | [sport cabins](https://finto.fi/yso/fi/page/p2773?clang=en) | urheilumajat
- [trädkojor](https://finto.fi/yso/fi/page/p30193?clang=sv) | [tree houses](https://finto.fi/yso/fi/page/p30193?clang=en) | puumajat

Voisiko olla 
ulkoilumajat
**YK**  rakennukset

Katso myös
- retkeily**majat** | vandrarhem | youth hostels https://finto.fi/yso/fi/page/p2772 **YK** majoitusliikkeet
- autiotuvat | ödemarksstugor | wilderness **huts** https://finto.fi/yso/fi/page/p14992 **YK** tuvat (rakennukset)
- kammit | gammer (torvkåtor) | earth **lodges**  http://www.yso.fi/onto/yso/p28216   **YK** asumukset
- kodat | kåtor | goahti, (Saami **huts**) http://www.yso.fi/onto/yso/p5381 **YK** asumukset
- kämpät |  timmer**kojor** (skogskojor) |  bunkhouses (forestry **huts**)  http://www.yso.fi/onto/yso/p11036 **YK** rakennukset

**Comment by mariaforsen** [comment]
Kannatan kaikkien majat-alakäsitteiden siirtoa ylöspäin hierarkiassa, jotta hierarkiavirhe korjaantuu. Trädkojor on ainoa joka ruotsiksi sopii majojen alla.

**Comment by mirmaid** [comment]
Suomeksi maja ei välttämättä tarkoita vaan äärimmäisen yksinkertaista rakennelmaa, vrt. esim. http://www.lapinmaja.fi/, https://santaclausvillage.info/fi/rooseveltin-maja/, Finnan kuvat...

Jos siis pitäisi rajata ihan yksinkertaisiin, niin varmaan helpointa olisi poistaa koko käsite. Mikään tarkenne ei oikein ilmaise, että rakennus on riipaistu parista laudasta ja vanhasta viltistä :grinning:

**Comment by mariaforsen** [comment]
Monikielisyyden kannalta varmaan pitäisikin tehdä jotain majat-termille, Melindassa ei nyt täsmää.

**Comment by YSO-kokous** [comment]
**Päätös**

Korjataan ne viitteet, joihin löytyy sopiva tarkempi termi. Sen jälkeen mietitään tarvitaanko muita muutoksia, jotta _majat_-käsite voidaan poistaa.

**Comment by mirmaid** [comment]
Ainakin _vierasmajat_ toistuu usein, samoin lasten "leikkimaja" esim. https://melinda.kansalliskirjasto.fi/byid/013864115 (sanastossa on nyt puumajat ja leikkimökit) ja pajumajat.

**Comment by mariaforsen** [comment]
Kannatan uutena sitten ainakin vierasmajat = gäststugor 
Pajumaja mahdollisesti videkojor https://svenska.yle.fi/a/7-564075

**Comment by mirmaid** [comment]
Pajumajoissa voisi ehkä 653 riittää, _vierasmajat_ tarvitaan ainakin. Varmaan aika usein noihin tulisi vain _vapaa-ajan asunnot_ tai jopa vain _rakennukset_.

Entä nuo lasten majat? Esim. näistä https://www.arkki.net/leirit/majanrakennusleirit/ on aika paljon viitteitä.

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _majat_. Lisätään _vierasmajat_ ja _leikkimajat_.

KT vierasmökit, majat (lasten)

**Comment by mariaforsen** [comment]
Sv. 
-gäststugor
-kojor (lek) HT lekkojor
