### ISSUE TITLE
kiertäjähermo

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9880]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kiertäjähermo

**Ehdotettu termi ruotsiksi**

vagusnerven

**Ehdotettu termi englanniksi**

vagus nerve

**Tarkoitusta täsmentävä selite**

Kiertäjähermo eli vagushermo (lat. nervus vagus) on kaulassa lähelle pintaa tuleva kymmenes aivohermo. (Wikipedia)

**Perustelut ehdotukselle**

Olisi kätevää olla täsmällinen termi vagushermon toimintaa käsitteleville kirjoille. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [autonominen hermosto](http://www.yso.fi/onto/yso/p15872)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 vagushermo, nervus vagus, kymmenes aivohermo, vagus, X aivohermo

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [ MeSH / FinMeSH](http://www.yso.fi/onto/mesh/D014630)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Stanley Rosenberg: Opas vagushermon parantavaan voimaan

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [kiertäjähermo](http://finto.fi/yse/fi/page/Y509880)

**Comment by mariaforsen** [comment]
Sv. vagusnerv /mesh
