### ISSUE TITLE
sidonta

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9886]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sidonta](http://www.yso.fi/onto/yso/p12174)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko tarkennettavissa tai mahdollisesti poistettavissa?

**Perustelut ehdotukselle**

Useita mahdollisia vastineita ruotsiksi ja tarkenne pitäisi lisätä (sanastoon hyväksyttiin nyt myös sitoutuminen (kemia)=bindning (kemi))  Melindassa sidonta käytetty 219 kertaa, mutta osalle näyttää olevan sopivampia termejä (sanastossa on myös kirjansidonta, kukkien sidonta, perhonsidonta jne.)

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ruotsiksi voisimme laittaa "bindning (aktivitet)", jolloin rajautuisi ihmisen tekemään aktiiviseen sitomiseen, mutta kaikkiin Melindatietueisiin se ei sovi (esim. lääketieteelliseen toimintaan, maatalouteen liittyviin prosesesseihin jne.)

**Comment by mirmaid** [comment]
Jäljellä nyt 95, seuraavat vielä vähän isompia ryhmiä:
- pölynsidonta
- haavat, murtumat, urheiluvammat, avanteet (joitakin kertoja myös psykiatrisessa pakkohoidossa potilaan sitominen) (sanastossa on haavanhoito, joka näistä puuttuu, mutta se ei kata ihan kaikkea)

Muuten hajoaa kyllä todella paljon.

**Comment by YSO-kokous** [comment]
**Päätös**

Otetaan _pölynsidonta_ omana käsitteenään

Otetaan _sidonta (sairaanhoito)_, mutta mietitään tarkennetta

_sidonta (perhot)_ KÄ _perhonsidonta_

**Comment by mariaforsen** [comment]
Sv. -dammbindning
-bandagering HT förbandsläggning, bandageläggning
https://svenska.se/tre/?sok=banDAGERA&pz=1
https://svenska.se/so/?id=104559

**Comment by mirmaid** [comment]
Palataan vielä ratkaisuun _sidonta (sairaanhoito)_.

**Comment by jarmosaarikko** [comment]
MOT sanakirjassa:   haavansidonta -> dressing tai bandage; puristusside - pressure bandage,
MESHissä "wound closure" ("haavan sulkeminen");  bandages - sidemateriaalit KT dressing
Wikidatassa 
- wound care http://www.wikidata.org/entity/Q56313174 (haavansidonta?)
- dressing http://www.wikidata.org/entity/Q523536  (sidos?) -- ei toimintaa
- bandage http://www.wikidata.org/entity/Q376724 (kääre) -- ei toimintaa

**Comment by mirmaid** [comment]
Sovittu YSOn ylläpitokokouksessa, että korjataan jäljelläolevat n. 30 viitettä muilla soveltuvilla termeillä ja tarvittaessa 653-kenttää käyttäen. Ei oteta erillistä termiä haavojen sidonnalle tai muulle sairaanhoidon sidonnalle. Tarkenteeton sidonta voidaan siis poistaa. 

kompressiosidonta KÄ kompressiohoito?
