### ISSUE TITLE
runko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9888]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[runko](http://www.yso.fi/onto/yso/p12210)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Jaetaan tai lisätään sulkutarkenne

**Perustelut ehdotukselle**

Ruotsiksi on ollut "stam (växtdelar)" ja eng. tree trunks. Virheellisesti käytetty Melindassa! Esim. "stam (växtdelar)" nyt aivan väärissä tietueissa (esim. pyörien tai perävaunujen rungoista)

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
On kyllä käytetty hyvin laajasti. Tarkenne varmasti ok, mutta voi olla että korjaus vaatii jonkun uuden terminkin.

**Comment by mariaforsen** [comment]
Stora finsk-svenska ordboken:
1
stam -men -mar
2
(rakenteissa) stomm|e -en -ar (myös kuv);
(auton, polkupyörän) ram -en -ar;
(auton alusta) chassi -[e]t -er;
(laivan) skrov -et =;
(runko-osa, yhd) -kropp -en -ar; (kuv) stomm|e -en -ar

**Comment by mirmaid** [comment]
Ratkaisuehdotus: lisätään tarkenne (kasvinosat).
