### ISSUE TITLE
Uusi-Englanti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9889]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Uusi-Englanti](http://www.yso.fi/onto/yso/p199608)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään siltaus LCNAF/LCSH-asiasanaan "New England" (http://id.loc.gov/authorities/subjects/sh85091260)

**Perustelut ehdotukselle**

Kyseessä sama tarkoite

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by mirmaid** [comment]
Näi varmasti tehdään, jos LCSH-linkitys toteutetaan tälle sanastolle.
