### ISSUE TITLE
nosework

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9890]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

nosework

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

nosework

**Tarkoitusta täsmentävä selite**

nosework on koiralle opetettavaa hajutyöskentelyä

**Perustelut ehdotukselle**

noseworkin suosio on kasvamassa Suomessa

**Ehdotettu yläkäsite YSOssa (LT)**

 [eläinten koulutus](http://www.yso.fi/onto/yso/p28336)

**Ehdotetut temaattiset ryhmät**

 [22 Maatalous. Maanviljely. Puutarhanhoito. Kotieläintalous](http://www.yso.fi/onto/yso/p26528)

**Vaihtoehtoiset termit**

 hajutyöskentely

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

nyt on ilmestynyt ensimmäinen suomenkielinen kirja noseworkistä  ISBN 978-952-94-5778-6 Elli Kinnunen: Löytö! : Nosework-harrastajan opas 

**Ehdottajan organisaatio**

Jyväskylän kaupunginkirjasto
**Termiehdotus Fintossa:** [nosework](http://finto.fi/yse/fi/page/Y509890)

**Comment by jtuohini** [comment]
Sama uutena ehdotuksena: https://github.com/Finto-ehdotus/YSE/issues/9965
