### ISSUE TITLE
proantosyanidiinit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9891]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

proantosyanidiinit

**Ehdotettu termi ruotsiksi**

proantocyanidiner

**Ehdotettu termi englanniksi**

proanthocyanidins 

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 8

**Ehdotettu yläkäsite YSOssa (LT)**

 [tanniinit](http://www.yso.fi/onto/yso/p8755), [flavonoidit](http://www.yso.fi/onto/yso/p6771)

**Ehdotetut temaattiset ryhmät**

 [09 Kemia](http://www.yso.fi/onto/yso/p26531)

**Vaihtoehtoiset termit**

 kondensoituneet tanniinit, antosyanidiinipolymeerit

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D044945), [wikipedia](https://fi.wikipedia.org/wiki/Proantosyanidiinit)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Structure elucidation and ruminant-related bioactivities of purified proanthocyanidins 

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [proantosyanidiinit](http://finto.fi/yse/fi/page/Y509891)

**Comment by mariaforsen** [comment]
Sv. proantocyanidiner HT procyanidiner
