### ISSUE TITLE
tuettu työllistyminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9892]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tuettu työllistyminen](http://www.yso.fi/onto/yso/p3541)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tätä laajentaa käsittämään myös muuta tuettua työllistymistä, kuin vain vammaisille suunnattua. 

**Perustelut ehdotukselle**

Tässä käsitellään pitkäaikaistyöttömien tuettua työllistymistä: https://kuntoutussaatio.fi/assets/files/2019/04/KUTU-ty%C3%B6seloste-58.pdf ja täällä viitataan ja myös THL viittaa muihinkin ryhmiin: "Tuetun työllistymisen menetelmät on Työkykyohjelman toimenpidekokonaisuus. Kokonaisuuden painopisteenä on kehittää työllistymistä tukevia palveluita niin, että ne tukevat vammaisia, osatyökyisiä, mielenterveys- ja päihdepalvelujen asiakkaita sekä kuntouttavan työtoiminnan asiakkaita työllistymään paremmin ja pysymään töissä." https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/tyokykyohjelma/tuetun-tyollistymisen-menetelmat

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tätä on käytetty laajemmin, mutta meneekö sekaisin sitten kaiken työllistämistoiminnan kanssa?

**Comment by MarkoLatvanen** [comment]
JUPO sisältää "tukityöllistetyt", mikä voisi viitata siihen, että kyseessä on erityinen ryhmä ja siten yleisemmästä työllistämistoiminnasta eriytyvä asia. Vaikea ottaa suoraa kantaa - TEM:n ja STM:n asiantuntijoita olisi ehkä kuultava?

**Comment by AuHo22** [comment]
Tukityö-termin kohdalla tällä hetkellä seuraava käyttöhuomautus: Tarkoittaa pitkäaikaistyöttömille järjestettyä tilapäistyötä.

**Comment by mariaforsen** [comment]
Taitaa tosiaa olla muillekin kuin pelkästään vammaisille, ks. esim. https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/tyokykyohjelma/tuetun-tyollistymisen-menetelmat  ja https://www.vates.fi/vates/kehittamistoiminta/tuettu-tyollistyminen.html
"Tuetun työllistymisen työhönvalmennus on tukimenetelmä henkilöille, joilla on haasteellista saavuttaa yhdenvertainen asema työelämässä vamman, sairauden tai osittaisen työ- ja toimintakyvyn vuoksi. "

**Comment by mirmaid** [comment]
Toki tämä on tällä hetkellä vain huomautus, joka tuskin vaikuttaa termin käyttöön kuvailussa kovinkaan paljon. Aihepiirin sanasto on kyllä melko limittäistä ja usein itse termi ei rajaudu kovin selkeästi, jolloin virheellisen käytön riski on iso ja jälkikäteen tapahtuva korjaaminen todella hankalaa.

**Comment by mirmaid** [comment]
(Muokattu sivulta https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/tyokykyohjelma/tuetun-tyollistymisen-menetelmat):
_Tuettu työllistyminen tarkoittaa työnhakijan työllistymistä normaaliin palkkatyöhön avoimille työmarkkinoille henkilökohtaisen tuen eli työhönvalmentajan avulla. Tuki on tarkoitettu vammaisille, osatyökykyisille ja mielenterveys- ja päihdepalvelujen, sekä kuntouttavan työtoiminnan asiakkaille_. (THL)

**Comment by AuHo22** [comment]
Katsoin yo. sivustoa ja kyse on tavoitteista (kuinka realistisia palvelut ovat esim. henkilökohtaisen työhönvalmentajan kohdalla?). Näköjään voidaan puhua myös moniammatillisista tukitiimeistä/monialaisista palveluista: Esim.  TE-toimiston sivuilla otsikon Tuetun työllistymisen palvelut alla: 
https://toimistot.te-palvelut.fi/kaakkois-suomi/typ

**Comment by mirmaid** [comment]
^ Yritin muokata niin, että vastaisi termimuotoa - kun meillä se on "tuettu työllistyminen" (ei oikein voi sanoa, että tuettu työllistyminen on tavoite).

**Comment by mirmaid** [comment]
Ehdotan siis määritelmän [muutosta](https://github.com/Finto-ehdotus/YSE/issues/9892#issuecomment-1534118705).

**Comment by AuHo22** [comment]
"--henkilökohtaisen tuen **tai** työhönvalmentajan avulla? 
Tarkoitin tavoitteista puhuessani THL:n tutkimushankkeen tavoitteita asian kehittämiseksi, otsikkona on: Tuetun työllistymisen menetelmät  -kokonaisuuden **tavoitteet**. Itse Stakesilla töissä olleena tiedän siellä tehdyn tutkimuksen määrän ja lobbaustyön poliittisten päättäjien suuntaan.
Eli heräsi siis se kysymys, kuinka tavoitetasolla tässä ohjelmassa oikein liikutaan, toimeenpano on siis sitten eri asia. Yleisesti Työkykyohjelmasta (jonka alla tuettu työllistyminen) THL:n sivustolla: "Työkykyohjelma oli osa pääministeri Sanna Marinin hallitusohjelman työllisyystoimien kokonaisuutta." - Jossain epäiltiin myös palvelujen jatkumista ohjelman päätyttyä. 
Ks. julkaisulinkit sivuston alaosassa: 
https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/tyokykyohjelma?redirect=%2Ffi%2Ftutkimus-ja-kehittaminen%2Ftutkimukset-ja-hankkeet%2Ftutkimukset-ja-hankkeet-aiheittain%2Ftoimintakyky-tutkimukset-ja-hankkeet

Eli pakosti heräsi kysymys hallituskauden vaihtuessa ja 6 mrd. säästöjen paineessa siitä, että riittääkö todellakin jokaiselle tuetun työllistymisen ohjelmaan osallistuvalle henkilökohtaista valmentajaa?

**Comment by mirmaid** [comment]
^ Toisaalta jos siihen ei ole varaa, onko sitten kyse tuetusta työllistymisestä? Jos se on parempi, voidaan kyllä jättää pois se henkilökohtainen valmentaja ja puhua vain henkilökohtaisesta tuesta?

**Comment by AuHo22** [comment]
Toisaalta näkee termiä yksilövalmentaja tai työ(hön)valmentaja, joita haetaan työpaikkailmoituksilla (usein sosionomitaustaisia), eli miksei sen voi säilyttää määritelmässä, ja esim. https://luovi.fi/koulutukset/tyovalmentaja/ 
Itse ehdotin tuota tai-konjunktiota eli- sijasta. TAI:
henkilökohtaisen tuen kuten työhönvalmentajan avulla / työhönvalmentajan tai muun henkilökohtaisen tuen avulla (?)

**Comment by mirmaid** [comment]
En ehkä uskaltaisi muuttaa lähdetekstiä niin, että esittäisin nämä vaihtoehtoina, mutta sen "eli työhönvalmentajan" voi hyvin tuossa mielestäni jättää pois.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään määritelmä.
