### ISSUE TITLE
myyntivoitot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9893]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[myyntivoitot](http://www.yso.fi/onto/yso/p16978)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Myyntivoitto kaipaa määritelmän, jolla sen erottaa luovutusvoitosta.  Vaihtoehtoisesti yhdistetään nämä käsitteet.

**Perustelut ehdotukselle**

Monessa paikassa nämä nähdään synonyymeinä. Esim.  verottaja, veronmaksajien keskusliitto ja Wikipedia.  Wikipedian teksti alkaa:   "Verotuksessa luovutusvoitoksi (toiselta nimeltään myyntivoitto[1]) kutsutaan voittoa, joka..."    Veronmaksat:  https://www.veronmaksajat.fi/Sijoittaminen/Myyntivoitto-eli-luovutusvoitto/.    Verottaja: https://www.vero.fi/henkiloasiakkaat/omaisuus/luovutusvoitto/   "Luovutusvoittoa eli myyntivoittoa syntyy, kun myyt tai vaihdat omaisuuttasi ja myyntihinta on suurempi kuin se, mitä itse maksoit alun perin."

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mariaforsen** [comment]
Valterissa vain luovutusvoitto ja määritelmänä: "tulo, joka muodostuu omaisuuden myynnistä tai vaihtamisesta saadusta voitosta"  / https://valter.sanakirja.fi/all/all/luovutusvoitto

**Comment by jarmosaarikko** [comment]
### Tieteen termipankki
- mainitaan vain luovutusvoitto  https://tieteentermipankki.fi/wiki/Oikeustiede:luovutusvoitto

### Termipankki
- https://termipankki.fi/tepa/fi/haku/myyntivoitto
- https://termipankki.fi/tepa/fi/haku/luovutusvoitto
 luovutusvoitto (sv: överlåtelsevinst)  
 määritelmä:  pääomatulo, joka muodostuu omaisuuden myynnistä tai vaihtamisesta saadusta voitosta, 
MUTTA   
- Tepassa on myös:   IATE4;  myyntivoitto,  luovutusvoitto  sv: realisationsvinst en: capital gains   (eli merkitty samaksi!)

### Wikidata
Mistä nämä linkitettäisiin....  Onko myyntivoitto  
- **gross income**  https://www.wikidata.org/wiki/Q3683077   vai 
- **net profit**  https://www.wikidata.org/wiki/Q2105346
luovutusvoitto - https://www.wikidata.org/wiki/Q11879887 - - ei ole linkattu minnekään wikidatassa, joten tästä linkkauksesta ei tule lisäarvoa
### Valtion termipankki
- Ei ole myyntivoitto käsitettä, vain https://valter.sanakirja.fi/all/all/luovutusvoitto. 
### [Eduskunnan sanasto](https://www.eduskunta.fi/kirjasto/EKS/) 
ilman määritelmiä: 
- luovutusvoitot - överlåtelsevinster - windfall profits
- myyntivoitot - försäljningsvinster - sales profits 
### [Melindassa](http://melinda.kansalliskirjasto.fi/F/?func=scan-list&CON_LNG=fin&local_base=fin01_opac)
- myyntivoitot yso/fin  103 kertaa
- luovutusvoitot yso/fin 245 kertaa.
### LCSH
- katso myös **profit** alakäsitteet  http://id.loc.gov/authorities/subjects/sh85107281

**Comment by mirmaid** [comment]
Nämä on otettu sanastoon samana päivänä, joten silloin on ainakin haettu eri merkityksiä.

**Comment by mirmaid** [comment]
Taloussanasto:

**luovutusvoitto**
överlåtelsevinst
_profit from assignment_
Omaisuuden luovutuksesta syntynyt voitto. Lasketaan siten, että luovutushinnasta vähennetään hankintamenon poistamatta oleva osa ja voiton hankkimisesta aiheutuneet menot. Luovutusvoitosta säädetään verolaissa.

**myyntivoitto**
försäljningsvinst
_sales profit, capital gain_
Kirjanpidossa esim. käyttöomaisuuden myynti- ja hankintahinnan positiivinen erotus.

**Comment by mirmaid** [comment]
En osaa sitten sanoa, miten loogisesti näitä kuvailussa käytetään. Lisätäänkö määritelmät? Tarvitaanko muita toimenpiteitä?

**Comment by mirmaid** [comment]
Jos ei tule muita ehdotuksia, lisätään määritelmät, ei muita muutoksia.
