### ISSUE TITLE
puitesopimukset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9894]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

puitesopimukset

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

MOT: sopimus joka koskee kaupan tms. yleisiä periaatteita
"Tarkoittaa tyypillisesti sopimusta, jolla osapuolet määrittävät säännöt tai periaatteet myöhemmille keskinäisille sopimuksilleen." https://docue.com/fi-fi/lakitieto/puitesopimus-tarkoittaa

**Ehdotettu yläkäsite YSOssa (LT)**

 [sopimukset](http://www.yso.fi/onto/yso/p3356)

**Ehdotetut temaattiset ryhmät**

 [69 Oikeus. Lainsäädäntö](http://www.yso.fi/onto/yso/p26559)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.vtv.fi/app/uploads/2020/08/VTV-Tarkastus-10-2020-Yhteishankintojen-toteuttaminen.pdf

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [puitesopimukset](http://finto.fi/yse/fi/page/Y509894)

**Comment by ilona-x** [comment]
JUHO: **puitesopimukset** http://www.yso.fi/onto/juho/p2359

**Comment by mirmaid** [comment]
Melindassa kerran yksikössä.

**Comment by mirmaid** [comment]
Myös https://www.superliitto.fi/tyoelamassa/tyosuhde/tyosopimus/runkosopimus/

**Comment by mariaforsen** [comment]
Sv. ramavtal
