### ISSUE TITLE
autoklinikat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9895]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[autoklinikat](http://www.yso.fi/onto/yso/p20956)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

käsitteen päätermi vaihdetaan muotoon "mobiiliklinikat".  Nykyinen päätermi poistetaan tai siirretään käsitteelle "korjaamot".

**Perustelut ehdotukselle**

"Autoklinikka"-termillä viitataan usein autokorjaamoihiin eikä  liikkuviin eli mobiileihin klinikoihin/sairaaloihin. Kts. Autoklinikka franchising-verkosto.  sivulla https://fi.wikipedia.org/wiki/Autoklinikka sekä  https://www.autoklinikka.fi/.    Korvaava termi voisi olla  "mobiiliklinikat" ,  kuten sv: ja en: vastineissa. 

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Vähän sama ongelma tuossa mobiiliklinikat-termissä: https://www.telia.fi/yrityksille/artikkelit/artikkeli/telia-toi-mobiilivarmenteen-tyopaikkaklinikan-sanomataloon-newsroom, https://blogi.eoppimispalvelut.fi/elavalappi/2018/04/11/oppia-muualta-mobiiliklinikalla-pureuduttiin-yritysten-mobiilinakyvyyteen/

_Autoklinikat_ on käytetty kerran, eikö tässä riittäisi vain _liikkuvat palvelut_? Vähän kyllä nyt mietin, miten _mobiilipalvelut_-käsite jatkossa alkaa rajautua...

**Comment by ilona-x** [comment]
FinMeSHissä **liikkuvat terveydenhuoltoyksiköt** http://www.yso.fi/onto/mesh/D008952. FinMeSHin termimuoto olisi ainakin yksiselitteinen.

**Comment by FinMeSHienPaimentaja** [comment]
Liikkuvat terveyspalvelut?

**Comment by ilona-x** [comment]
Tätä tosiaan käytetty Melindassa vain yhden kerran tämän julkaisun kuvailussa:
**Autoklinikka** https://urn.fi/URN:NBN:fi-fe2014120246765

> Autoklinikan tarkoituksena oli joukkotutkimusmenetelmin etsiä
> väestöstä eräitä yleisiä tauteja jo niiden oireettomassa alkuvaiheessa,
> silloin kun asianomainen henkilö ei niistä vielä
> tiennyt. Toiminnalla haluttiin estää työkyvyttömyyden syntyä,
> lyhentää työkyvyttömyysaikoja ja lievittää sairauksien seuraamuksia.
> Tarkoituksena oli myös saada tutkimustietoa sairauksien
> esiintymisestä eri osissa maata ja eri väestöryhmissä
> sekä kokeilla ja kehittää uusia joukkotutkimusmenetelmiä.
Lähde:  Autoklinikka / työryhmä: Arpo Aromaa ... [ja muita].

Täällä vielä lisää tietoa autoklinikkatutkimuksista:
https://thl.fi/fi/tutkimus-ja-kehittaminen/tutkimukset-ja-hankkeet/autoklinikka-tutkimukset

**Comment by ilona-x** [comment]
Olisikohan mahdollista poistaa autoklinikat-termi, kun nuo Kelan tutkimustoimintaa palvelleet autoklinikat ovat ehkä hiukan erityyppisiä kuin nykyiset liikkuvat terveydenhuoltoyksiköt. 🤔

**Comment by mirmaid** [comment]
^ Kannatan, asiaan voidaan palata kun tarvetta taas ilmenee. Ja tässä riittää varmasti _liikkuvat palvelut_.
