### ISSUE TITLE
kuona-aineet

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9897]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kuona-aineet](http://www.yso.fi/onto/yso/p14409)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään ryhmät 32 Kaivosteollisuus. Kaivannaisteollisuus  ja  34 Metalliteollisuus. Metallurgia.

**Perustelut ehdotukselle**

kuonaa ja kuona-aineita syntyy esim. metalli- ja kaivosteollisuudessa. Mikäli rajoitetaan vain eliön kuona-aineisiin, tarvitaan tarkenne.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
Mielestäni tälle ei tarvitse lisätä ryhmiä, sillä YSOssa on myös **kuona** http://www.yso.fi/onto/yso/p21211, jolla on tässä ehdotetut ryhmät 32 & 34. Ja mielestäni myös näiden merkitysero on selvä.

Tässä vielä merkitykset Kielitoimiston sanakirjasta:

**kuona-aine**
elimistössä syntynyt t. siihen ulkopuolelta tullut haitallinen t. tarpeeton aine.

**kuona**
jäteaine jota syntyy hehkutettavan t. sulatettavan metallin hapettuessa sekä kivihiilen t. koksin palaessa.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: ei muutosta.
