### ISSUE TITLE
vasteaika

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9898]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[vasteaika](http://www.yso.fi/onto/yso/p6969)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko laajentaa yleiseen käyttöön, käytetään myös esim. poliisin vasteaikana. Toisaalta myös valmiusajan voisi ottaa? "Työryhmän asettaminen ja työ pohjautuu pääministeri Marinin hallitusohjelman 2019 kirjaukseen, jonka mukaan poliisille määritellään enimmäisvasteajat koko Suomeen. Työryhmän raportissa vasteajasta puhutaan toimintavalmiusaikana, joka on poliisihallinnossa yleisesti käytetty termi."

**Perustelut ehdotukselle**

https://poliisi.fi/documents/25235045/42553324/poliisintoimintavalmiusaika.pdf/2335631c-6157-37fc-bc06-0346f0251507/poliisintoimintavalmiusaika.pdf?t=1603791360435

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Ongelmakokouksessa hyväksyttiin sanastoon _toimintavalmius_. _Vasteaika_ on nyt ryhmässä 43 tietotekniikka, mutta käytetty hyvin monenlaisissa yhteyksissä (kaikkiaan vain 21 kertaa).

**Comment by mariaforsen** [comment]
https://sv.wikipedia.org/wiki/Responstid
https://it-ord.idg.se/ord/svarstid/
https://svenska.se/saol/?sok=svarstid&pz=1

Wikipedia: "Responstid är tiden det tar mellan att en begäran lagts, till dess att begäran utförts. Ofta pratar man om responstid inom [datateknik](https://sv.wikipedia.org/wiki/Datateknik), men responstid kan även vara exempelvis tiden det tar för ett [företag](https://sv.wikipedia.org/wiki/F%C3%B6retag) att åtgärda ett fel efter att det upptäckts."

Eli vaihteleva käyttö myös ruotsiksi.

**Comment by mirmaid** [comment]
Minkälaisia toimenpiteitä tämä tarvitsisi?

**Comment by ilona-x** [comment]
Melindassa käytetty vasteaika-termiä 22 kertaa, ja näistä vain kolmessa viitteessä oli käytetty tietotekniikan yhteydessä. Paljon poliisin ja pelastuslaitosten toimintaa käsitteleviä viitteitä. Ja lisäksi yllättävän paljon oli aivoihin liittyvää tutkimusta, esim. 

- Aivojen jännitevasteiden rekisteröinti useaan äänen piirteeseen yhdellä mittauskerralla terveillä musiikkileikkikoulua käyvillä kaksivuotiailla 
- Sensorisen kuulomuistin kesto MMN-tutkimuksella tarkasteltuna 
- Tehtäväsuoriutumisen häiriintyminen ja aivojen tapahtumasidonnaiset jännitevasteet 10 - 15-vuotiailla: Kahden koeasetelman vertailua 

Hiukan epäilyttää, onko tämä YSO:n vasteaika sopiva termi myös noissa aivoja käsittelevissä aineistoissa. 🤔

**Comment by mirmaid** [comment]
Näyttää kyllä esiintyvän ihan fysiologiaan liittyen muutenkin kuin Melindassa.

**Comment by YSO-kokous** [comment]
**Päätös**

Lisätään sopivia ryhmiä.
