### ISSUE TITLE
neulakinnastekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9899]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[neulakinnastekniikka](http://www.yso.fi/onto/yso/p483)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KÄ kinnasompelu

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Tässä taisi olla ajatuksena, että uusi termimuoto sopisi paremmin käsityö-hierarkiaan, mutta neulakinnastekniikka on kyllä käytetyin muoto.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: ei muutosta.
