### ISSUE TITLE
salavuoteus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#990]
#### Ehdotettu termi suomeksi

salavuoteus
#### Ehdotetut temaattiset ryhmät (YSA-ryhmät)

[52 Historia](http://www.yso.fi/onto/ysa/ryhma_52)
#### Lähde

951-41-0910-4

**Luontipäivämäärä:** 23.10.2003

**Muokkauspäivämäärä:** 11.1.2006, 23.10.2003, 16.12.2008, 31.05.2010

**Voyager-id:** 127758

**Termiehdotus Fintossa:** [salavuoteus](http://finto.fi/yse/fi/page/Y327758)

**Comment by mirmaid** [comment]
Fintoon tullut palaute, että tätä tarvitaan kuvailussa, ei kuitenkaan aineistoesimerkkiä.

**Comment by mariaforsen** [comment]
Jonkin verran Melindassa, esim. [Salavuoteus- ja huoruusrikosten sääntely ja oikeuskäytäntö erityisesti 1800-luvun lopun Suomessa / Janne Kaisanlahti.]
https://www.kielikello.fi/documents/35556/369858/Yhdess%C3%A4makaamista+ja+ajatonta+vuoteenseuraa_Heikkil%C3%A4.pdf/ecf2bca0-bf4b-6c1f-0534-05bcf3c142ab


Sv. lönskaläge HT lägersmål 
https://www.sanakirja.fi/custom/en-sv-fi/salavuoteus
https://svenska.se/tre/?sok=l%C3%B6nskal%C3%A4ge&pz=1
https://svenska.se/tre/?sok=l%C3%A4gersm%C3%A5l&pz=1
https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_b57e42efdeb5a6575a957ba7ce8bb94b&list_id=1&keyword=salavuoteus&word=salavuoteus
https://riksarkivet.se/forbjudna-forbindelser
