### ISSUE TITLE
tutkimustekniikka

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9900]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tutkimustekniikka](http://www.yso.fi/onto/yso/p17848)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tutkitaan, miten tätä on käytetty ja mihin käsitteellä on tarkoitus viitata, sekä onko nykyinen termimuoto paras.

**Perustelut ehdotukselle**

Epäselvä käsite. Kuuluuko tekniikoiden vai teknologian alle+

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Suurin osa Melindaviitteistä tutkimusmenetelmä-tyyppisiä? Esim. [Doing qualitative research / David Silverman.](https://melinda.kansalliskirjasto.fi/F/X4MR1DQG3K72YBJQN1BUPPK9JBQAGTCJ7131HFCVVCXTIXJQHN-00388?func=full-set-set&set_number=012511&set_entry=000043&format=999) ; [Case studies in interdisciplinary research / [edited by] Allen F. Repko, William H. Newell, Rick Szostak.](https://melinda.kansalliskirjasto.fi/F/X4MR1DQG3K72YBJQN1BUPPK9JBQAGTCJ7131HFCVVCXTIXJQHN-05296?func=full-set-set&set_number=012511&set_entry=000052&format=999) ; [Research methods for business students / Mark Saunders, Philip Lewis, Adrian Thornhill.](https://melinda.kansalliskirjasto.fi/F/X4MR1DQG3K72YBJQN1BUPPK9JBQAGTCJ7131HFCVVCXTIXJQHN-05298?func=full-set-set&set_number=012511&set_entry=000053&format=999) ; Tulevan maisterin graduopas / Juha T. Hakala. ; Kirjallisuuskatsaus hoitotieteessä / Minna Stolt, Anna Axelin, Riitta Suhonen (toim.) 

Vähemmän teknisemmässä mielessä, esim. artikkeli 50 vuotta rikostutkintaa : hämyisistä kellareista moderniin tekniikkaan. Ongelmana myös että tämä pienempi osa viitteistä koskee tutkimustekniikka toisessa merkityksessä ks. https://www.kielitoimistonsanakirja.fi/#/tutkimus?searchMode=all ja vrt https://svenska.se/tre/?sok=forskning&pz=1 Tutkimus hoitotyössä, esim. [Pediatric ultrasound : how, why and when / edited by Rose De Bruyn.](javascript:open_window("/F/X4MR1DQG3K72YBJQN1BUPPK9JBQAGTCJ7131HFCVVCXTIXJQHN-07506?func=service&doc_number=006209026&line_number=0009&service_type=TAG%22);) -tässä forskningsteknik on väärä, kyseessä on undersökning.

**Comment by mirmaid** [comment]
^ Suomeksi ei ole tätä forskning/undersökning -jakoa, eli on vähän vaikea hahmottaa eroa sitä kautta.

**Comment by mirmaid** [comment]
Melindassa 270 kertaa, suurimmassa osassa viitteistä myös _tutkimusmenetelmät_-termi. Näissä on varmasti päällekkäisyyttäkin, toisaalta tutkimusmenetelmät viittaa vaihtoehtoisiin eri menetelmiin, tutkimustekniikkaa käytetty _opiskelutekniikka_-termin tavoin yleisemmällä tasolla esim. graduoppaissa ym. "näin teet tutkimusta".

**Comment by mariaforsen** [comment]
Jos tästä huolimatta halutaan säilyttää erillisenä terminä niin monikielisyyden kannalta olisi tärkeä erottaa tieteelliseen tutkimustoimintaan liittyvät asiat muista esim. lääkärintutkimus-, rikostutkimus- yms. arkipäiväisistä "selvittämisasioista". 

Sv. on siis forskningsteknik, ja se sopii vain tieteellisen tutkimuksen yhteydessä.

**Comment by ilona-x** [comment]
Melinda: 
**tutkimustekniikka NOT tutkimusmenetelmät** = 91 viitettä, joista ainakin 33 viitettä on erilaisia tutkielman laadinnan oppaita.

Käytetty esimerkiksi Tutki ja kirjoita -teoksen kuvailussa, jossa sisällysluettelon perusteella käsitellään viittaustekniikkaa ja kielitekniikkaa https://melinda.kansalliskirjasto.fi/byid/001006119 . Mielestäni tämänkaltaisten oppaiden kuvailut näyttävät kattavilta, vaikka tämä tutkimustekniikka -termi niistä poistuisikin (tietenkin voisi lisätä tutkimusmenetelmät -termin niihin joista se puuttuu).

Viitteiden tarkastelun jälkeen olisin valmis poistamaan tämän tai mahdollisesti ohjaamaan tutkimusmenetelmiin. Toisaalta joissain tapauksissa voisi ehkä käyttää myös tutkimus/tutkimustyö & tekniikat tai sitten jos kyse on teknologiasta niin tutkimus & teknologia -yhdistelmiä.

**Comment by mirmaid** [comment]
^ Vakuuttavan paljon kannatusta saanut ehdotus. Oliko tällaisesta tavattu palkita nakkimukilla 😄

**Comment by YSO-kokous** [comment]
**Päätös**

Poistetaan _tutkimustekniikka_.
