### ISSUE TITLE
tasaikäiskasvatus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9904]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tasaikäiskasvatus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Tarvitaan jatkuvan kasvatuksen rinnalle

**Ehdotettu yläkäsite YSOssa (LT)**

 [metsänkasvatus](http://www.yso.fi/onto/yso/p24915)

**Ehdotetut temaattiset ryhmät**

 [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [jatkuva kasvatus](http://www.yso.fi/onto/yso/p24914)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.ptt.fi/julkaisut-ja-hankkeet/kaikki-julkaisut/metsien-hoidon-ja-kasvatusmenetelmien-hyvaksyttavyys-metsanomistaja-2020.html

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tasaikäiskasvatus](http://finto.fi/yse/fi/page/Y509904)

**Comment by mirmaid** [comment]
Ei Melindassa, aika vähän Googlella...luulin ensin että kyse on jostain päiväkotiryhmistä :smile:.

**Comment by mariaforsen** [comment]
Muita muotoja ja eng.?

**Comment by mirmaid** [comment]
Taitaa olla sama kuin myös ehdotettu jaksollinen kasvatus: https://github.com/Finto-ehdotus/YSE/issues/10148?

**Comment by YSO-kokous** [comment]
### Päätös
tasaikäiskasvatus KÄYTÄ jaksollinen kasvatus
