### ISSUE TITLE
rajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9905]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[rajat](http://www.yso.fi/onto/yso/p2856)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Pitäisikö käsite jakaa kahtia, esim. rajat (maantiede) ja rajat (psykologia)? Tai tarvitseeko tuo eka tuota tarkennetta ollenkaan? Nyt on ryhminä sekä yleistermi että maantiede.

**Perustelut ehdotukselle**

LCSH:ssa on boundaries (psychology). Tuli mieleen tuoretta väitöskirjaa asiasanoittaessa https://jyx.jyu.fi/handle/123456789/78582

**Ehdottajan organisaatio**

Yle Arkisto

**Comment by mirmaid** [comment]
Tätä on käsitelty jokin aika sitten, päätös vuodelta 2020: https://github.com/Finto-ehdotus/YSE/issues/5409.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: ei muutosta.
