### ISSUE TITLE
kvartetit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9906]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kvartetit](http://www.yso.fi/onto/yso/p30113)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

LCSH-linkitysten tarkistus yhtyeet-käsitteen alakäsitteille.

**Perustelut ehdotukselle**

Linkityssuhteet eivät vaikuta ihan jondonmukaisilta - osalla ei mitään ja osalla broader matchina Chamber music groups. Miten nämä rajautuvat käytännössä?

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by MUUSA-kokous** [comment]
Ehdotetaan Chamber music groups -linkityksen poistamista ao. käsitteistä.
