### ISSUE TITLE
kehitysoppi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9907]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kehitysoppi](http://www.yso.fi/onto/yso/p4474)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisiko tämän yhdistää > evoluutioteoria, vai onko aiemman nimityksen säilyttämiselle perusteita?

**Perustelut ehdotukselle**

Tarkoittaa samaa

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by mirmaid** [comment]
Ratkaisuehdotus: yhdistetään.
