### ISSUE TITLE
toksinen maskuliinisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9908]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

toksinen maskuliinisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vakiintunut käsite. Kirja käsittelee nimenomaan toksista maskuliinisuutta, mutta sille ei ole asiasanaa.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ford: Boys will be boys : power, patriarchy and toxic masculinity

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [toksinen maskuliinisuus](http://finto.fi/yse/fi/page/Y509908)

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/9780
