### ISSUE TITLE
toiminta-alueittainen opetus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9910]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

toiminta-alueittainen opetus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Perusopetuksen toiminta-alueittain järjestettävä opetus on opetusjärjestely, joka muusta oppiainejakoisesta opetuksesta poiketen perustuu toiminta-alueisiin. Toiminta-alueittaisessa opetuksessa oppilas ei opiskele erillisiä oppiaineita vaan hänen oppimistavoitteensa on määritelty toiminta-alueittain. Toiminta-alueittaisen opetuksen tavoitteena on antaa oppilaalle tietoja ja taitoja, joiden avulla hän suoriutuu mahdollisimman itsenäisesti elämässään. Toiminta-alueet ovat motoriset taidot, kieli ja kommunikaatio, sosiaaliset taidot, päivittäisten toimintojen taidot ja kognitiiviset taidot.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

 [57 Kasvatus. Opetus. Koulutus](http://www.yso.fi/onto/yso/p26554)

**Vaihtoehtoiset termit**

 toiminta-alueittain järjestettävä opetus

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.oph.fi/fi/tilastot-ja-julkaisut/julkaisut/oppimisen-edistymisen-seuraaminen-ja-arviointi-toiminta-alueittain

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [toiminta-alueittainen opetus](http://finto.fi/yse/fi/page/Y509910)

**Comment by mirmaid** [comment]
Ei Melindassa.

**Comment by mariaforsen** [comment]
Sv. undervisning enligt verksamhetsområde https://eperusteet.opintopolku.fi/#/sv/perusopetus/419550/tekstikappale/432698
https://www.oph.fi/sv/nyheter/2021/ny-utredning-om-undervisning-som-ordnas-enligt-verksamhetsomrade-varierande
