### ISSUE TITLE
tulorekisteri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9911]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tulorekisteri

**Ehdotettu termi ruotsiksi**

inkomstregistret

**Ehdotettu termi englanniksi**

incomes register

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

https://www.vero.fi/tulorekisteri/

Tulorekisteri on sähköinen tietokanta, jonne työnantajat ja muut suorituksen maksajat ilmoittavat tiedot maksetuista palkoista, eläkkeistä ja etuuksista. Tiedot ilmoitetaan viiden päivän kuluessa maksusta. Myös kotitaloustyönantajat ilmoittavat maksamansa palkat tulorekisteriin.

**Ehdotettu yläkäsite YSOssa (LT)**

 [rekisterit](http://www.yso.fi/onto/yso/p82)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://www.vtv.fi/app/uploads/2021/04/VTV-Tarkastus-3-2021-Tulorekisterin-kayttoonotto-ja-vaikutukset.pdf

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tulorekisteri](http://finto.fi/yse/fi/page/Y509911)

**Comment by ilona-x** [comment]
JUPO: **tulorekisteri** http://www.yso.fi/onto/jupo/p3049

**Comment by mirmaid** [comment]
4 kertaa Melindassa yksikössä.

**Comment by mariaforsen** [comment]
Sv. inkomstregister

**Comment by YSO-kokous** [comment]
### Päätös
Hyväksytään muodossa tulorekisterit
