### ISSUE TITLE
soidin

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9912]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[soidin](http://www.yso.fi/onto/yso/p15300)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

vaihdetaan en: päätermiksi  "lek" ja ohjaustermiksi "lekking"

**Perustelut ehdotukselle**

courtship rites sopii paremmin uudeksi käsitteeksi nimellä "kosintamenot" eli "courtship display", jota tosin ei ole YSOssa  kts. http://www.wikidata.org/entity/Q10968643.  Soidin olisi tämän käsitteen alakäsite.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mariaforsen** [comment]
Ongelmatermi! Eri termejä eri kielillä, jotka rajautuvat eri tavalla. 
Soidin: 
(el): (lintujen) spel -et =;
(kurkien) dans -en -er;
(kalojen) lek -en -ar;
(nisäkkäiden) parningslek

Ks. https://termipankki.fi/tepa/fi/haku/soidin

Sanastossa myös kutu= lek (fortplantningsbeteende) -ehkä myös tarkennettava ruotsiksi. Ks. NE "lek, term inom zoologin med två olika betydelser..."

**Comment by jarmosaarikko** [comment]
Jukka Salon ja Martti Soikkelin kirjassa "Eläiinten käyttäytyminen" (Otava, 1983) mainitaan soidin sivulla 65: _"Kaikkien monisoluisten eläinten soitimessa voidaan erottaa kaavamaisia, kerta toisensa jälkeen samanlaisina toistuvia lyhyehköjä toimintoja."_ 
- soidin käsitteenä kattaa siis kaikki eläimet sekä yksittäin esitettynä että ryhmässä tapahtuvana. 
- Tässä merkityksessä lähin englanninkielinen vastine olisi  alussa kuvatut termit tai myös "courtship behaviour", joka voidaan kääntää "kosintakäyttäytyminen".   
- Marian mainitsemat termit eri lajien soitimesta voisivat olla ohjaustermeinä.
- Soidin voi tietysti tarkoittaa myös paikkaa, jossa soidin tapahtuu, mutta silloin voisi terminä olla "soidinpaikka".
- courtship (animals) voisi olla ohjausterminä.
- https://www.collinsdictionary.com/dictionary/english/lek
- https://www.merriam-webster.com/dictionary/lek
- https://www.audubon.org/news/what-heck-lek-quirkiest-mating-party-earth
- https://en.wikipedia.org/wiki/Lek_mating#Lekking_behaviour -- listaa laajan joukon eläinlajeja, joilla on soidin

**Comment by mariaforsen** [comment]
Ruotsiksi silti ongelma, ks. esim. Nationalencyklopedin: "Lek, term inom zoologin med två olika betydelser.Dels åsyftas fortplantning hos fiskar och groddjur: gäddan leker under dess på våren inträffande lektid; spiggen anlägger en speciell lekdräkt (hanens buk blir röd). Dels åsyftas en typ av parningsbeteende (i vissa fall kallat spel), som kännetecknas av att ett antal individer (i regel hanar) samlas på viss, ofta år från år identisk plats, lekplats, arena, där de utför beteenden som attraherar individer av det motsatta könet, som väljer någon av de lekande (eller spelande) individerna för parning. Lekbeteenden har studerats hos insekter, fiskar, groddjur, fåglar och däggdjur."

**Comment by mirmaid** [comment]
138 kertaa Melindassa, lähes kaikki viitteet linnuista. Kerran sammakoista, muutaman kerran yleisesti eläimistä. Jos auttaa, voitaneen rajata _soidin (linnut)_ ja muissa tapauksissa vain _lisääntymiskäyttäytyminen_?

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään Mirjan ehdotus yllä.

**Comment by mariaforsen** [comment]
Sv. spel (fåglar) HT parningsspel (fåglar)
