### ISSUE TITLE
Länsisatama (Helsinki)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9913]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Länsisatama (Helsinki)](http://www.yso.fi/onto/yso/p123970)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Selvennetään kuvailutiedoissa viittaako käsite satamaan vai kaupungiosaan.

**Perustelut ehdotukselle**

Länsisatama ei ole vain liikennealue, kuten tietue antaa ymmärtää, vaan myös Helsingin 20. kaupunginosa.  MML tiedot siten hieman vajanaiset tai harhaanjohtavat. Lähde WIkipedia  https://fi.wikipedia.org/wiki/L%C3%A4nsisatama_(Helsinki).  Wikidatassa on erikseeen Länsisatama – satama-alue Jätkäsaaren osa-alueella Länsisataman kaupunginosassa.  https://fi.wikipedia.org/wiki/L%C3%A4nsisatama.   Kumpaa WIkidatan käsitettä YSO-paikkojen käsitteen on tarkoitus kuvata: satama vai kaupunginosa?

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
tästä on vanha issue, jonka käsittely on kesken. Länsisatama (Helsinki : kaupunginosa) #8483
