### ISSUE TITLE
kassamyyjät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9914]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kassamyyjät](http://www.yso.fi/onto/yso/p995)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Kassamyyjät vs. kassanhoitajat, vaikea hahmottaa mitä eroa näillä on. Yhdistettävä tai selkeytettävä?

https://finto.fi/yso/fi/page/p995
https://finto.fi/yso/fi/page/p17056

**Perustelut ehdotukselle**

Käsitteet epäselviä

**Ehdottajan organisaatio**

KK

**Comment by ilona-x** [comment]
Kielitoimiston sanakirja:

**kassamyyjä**
myymälän kassalla työskentelevä myyjä. 

**kassanhoitaja**
Ravintolan, pankin, myymälän kassanhoitaja.

--

"**Myymälän kassanhoitaja** 
Kassanhoitaja tai kassamyyjä ottaa asiakkaalta maksun tuotteesta kassalla. Päätoimisia kassanhoitajia on lähinnä marketeissa, valintamyymälöissä ja tavarataloissa. "
Lähde: https://kokeile.tyomarkkinatori.fi/ammatit/Myym%C3%A4l%C3%A4n-kassanhoitaja

"**Kassanhoitaja, toimisto** 
Kassanhoitaja huolehtii yrityksen, laitoksen, viraston, järjestön tai yhdistyksen rahaliikenteestä. "
Lähde: https://kokeile.tyomarkkinatori.fi/ammatit/Kassanhoitaja,-toimisto

**Comment by mirmaid** [comment]
_Kassanhoitajat_ käytetty vain 6 kertaa Melindassa, eikä näissäkään kaikissa oikein tai tarpeellinen kuvailussa.

**Comment by mariaforsen** [comment]
Ruotsiksi eri asioita: https://svenska.se/tre/?sok=kass%C3%B6r&pz=1 Eli kassör = person som sköter kassa och ofta an­svarar för t.ex. en klubbs ekonomi

**Comment by mirmaid** [comment]
Ehdottaisin kassanhoitajat-käsitteen poistoa ja tarvittaessa kassanhoitajat (myyjät) KÄ kassamyyjät.

**Comment by mariaforsen** [comment]
Toinen merkitys putoaa sitten kokonaan pois sanastosta?

**Comment by mirmaid** [comment]
^ Jos katsoo Melindan viitteitä niin ei vaikuta kovin tarpeelliselta.

**Comment by YSO-kokous** [comment]
#### Päätös
Poistetaan käsite kassanhoitajat
lisätään ohjaustermi kassanhoitajat (myyjät) KÄYTÄ kassamyyjät

**Comment by mirmaid** [comment]
Huomattiin, että Yle on käyttänyt runsaasti _kassanhoitajat_-käsitettä. Uutena ehdotuksena yhdistetään nämä käsitteet niin, että päätermiksi tulisi _kassatyöntekijät_ (KT kassamyyjät, kassanhoitajat). Lisäksi ohjaustermi kassanhoitajat (yhdistykset) KÄ taloudenhoitajat (rahatalous).

**Comment by mariaforsen** [comment]
Sv. 
-kassapersonal (fi. kassahenkilöstö) HT kassaarbetare, kassaanställda, kassörer (arbetare), kassaexpediter, kassaförsäljare, kassabiträden 
-skattmästare (fi. "taloudenhoitajat (rahatalous)") > kassörer (ekonomiansvar) HT kassaförvaltare
(obs. ekonomichefer skilt begrepp i allfo)

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_a1aec528f8a8af19fe261384d95c5573&list_id=1&keyword=taloudenhoitaja&word=taloudenhoitaja

https://svenska.se/tre/?sok=kass%C3%B6r&pz=1

https://fho.sls.fi/uppslagsord/6569/skattmastare/

https://kaino.kotus.fi/finsk-svensk/?p=qs-article&suru_id=SURU_9f00ddf833c1bf1ccf26d72f3c180023&list_id=1&keyword=rahastonhoitaja&word=rahastonhoitaja

https://fho.sls.fi/uppslagsord/12483/kassaforvaltare/
