### ISSUE TITLE
katutyöntekijät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9915]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[katutyöntekijät](http://www.yso.fi/onto/yso/p7411)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkenne (kadunrakennus)

**Perustelut ehdotukselle**

Käytetty myös etsivän sosiaalityön yhteydessä. Ks. https://melinda.kansalliskirjasto.fi/byid/013356612

**Ehdottajan organisaatio**

KK

**Comment by jtuohini** [comment]
Eikö selkeämpi suomenkielinen muoto olisi **_kadunrakentajat_** ja KT-muodoksi ainakin _tientekijät_? "Katutyöntekijästä" tulevat mieleen feissarit ja jopa katutytöt!

Vastaavia rakentajat-loppuisia asiasanoja löytyy YSO:sta useita, ainakin **kirkonrakentajat**, **laivanrakentajat**, **urkujenrakentajat** ja **viulunrakentajat**. "Radanrakentajat" ei jostain syystä löydy, mutta **radanrakennus** kyllä, samoin **kadunrakennus** ja **tienrakennus**.

**Comment by mirmaid** [comment]
Duunitorilta ei löydy töitä kadunrakentajalle, mutta kylläkin tienrakentajalle.

Toisaalta tätä on käytetty Melindassa vain kolme kertaa, joista kaksi oikeassa merkityksessä, eikä työntekijään viittaava termi ole kummassakaan erityisen tarpeellinen lisä.

**Comment by ilona-x** [comment]
Samaiselta duunitorilta löytyi v. 2020 hakuilmoitus, jossa haettiin katutyöntekijää Kangasalan kaupungille tällaisella tehtävänkuvauksella:

"Katutyöntekijän tehtävänä on mm. liikennemerkkien sekä katuviittojen uusiminen, hulevesiin liittyviä töitä, kuten katurumpujen ja sadevesikaivojen aukaisua, ilkivallan ja vahinkojen korjaustöitä, erilaisten tapahtumien liikennejärjestelyjä."
https://duunitori.fi/tyopaikat/tyo/katutyontekija-sksun-11990280

**Comment by mirmaid** [comment]
Ratkaisuehdotus: poistetaan.
