### ISSUE TITLE
Vittanki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9916]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Vittanki](http://www.yso.fi/onto/yso/p111698)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yläkäsitteeksi Kiiruna (kunta).  Pitäisikö sen olla Kiiruna (Ruotsi)?

**Perustelut ehdotukselle**

Kumpaan  käsitteeseen tämä viittaa: taajamaan vai piiriin? Wikidatassa käsitteet ovat erikseen.  taajama: https://www.wikidata.org/wiki/Q960861  ja piiri: https://www.wikidata.org/wiki/Q21721318

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Poistetaan tarkenne Kiirunalta.
