### ISSUE TITLE
kirjastonjohtajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9917]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kirjastonjohtajat](http://www.yso.fi/onto/yso/p16382)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT ylikirjastonhoitajat

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Ainakin ruotsiksi oikea termi olisi KÄYTÄ kirjastonjohtajat, tämä ohjaus on jo ALLFOssa.
Ks. https://www.sttinfo.fi/tiedote/kimmo-tuominen-kansalliskirjaston-ylikirjastonhoitajaksi?publisherId=3747&releaseId=69931240

**Comment by mariaforsen** [comment]
Vastaava ohjaus jo olemassa ALLFOssa
