### ISSUE TITLE
koulunkäynninohjaajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9918]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[koulunkäynninohjaajat](http://www.yso.fi/onto/yso/p27273)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistettävä/selkeytettävä - tämä ja koulunkäyntiavustajat (https://finto.fi/yso/fi/page/p16602)

**Perustelut ehdotukselle**

Ks. tässä oleva määritelmä. Engl. termi sama molemmissa, myös.

**Ehdottajan organisaatio**

KK

**Comment by ilona-x** [comment]
koulunkäynninohjaajat termin huomatuksessa mm. "Tehtävän nimikkeestä on ollut kiistaa, vanhempi nimike on koulunkäyntiavustajat". Jokohan tilanne olisi 10 vuodessa rauhoittunut niin, että nämä uskaltaisi yhdistää. 🤔 

--

"Kun uusi ammattiryhmä on ilmestynyt kouluihin, edes tehtävän nimikkeestä ei ole yksimielisyyttä. He itse ja JHL puhuvat koulunkäynninohjaajista. OAJ kutsuu heitä koulunkäyntiavustajiksi."
Lähde: https://suomenkuvalehti.fi/jutut/kotimaa/uusi-ammattiryhma-koulussa-tehtavan-nimikkeesta-riita/

**Comment by mirmaid** [comment]
Oman lapsen koulun henkilökuntaan näyttää kuuluvan 3 koulunkäyntiavustajaa, yksi koulunkäynninohjaaja ja yksi erityiskoulunkäynninohjaaja.

**Comment by mirmaid** [comment]
Melindassa koulunkäyntiavustajat 216 kertaa, koulunkäynninohjaajat 17 kertaa. Googlella jälkimmäinen vähän suositumpi, mutta määrät hyvin lähellä 41000/45000.

**Comment by mirmaid** [comment]
Kysyin tätä vielä tuttavapiiristä. Nykyään koulutuksesta valmistuu _koulunkäynninohjaajia_, jotka toivovat itsestään käytettävän tätä ammattinimeä. Lisäksi kouluissa työskentelee avustajia, joilla ei välttämättä ole mitään koulutusta ko. ammattiin (saattavat olla esim. opettajan ammattia harkitsevia lukion päättäneitä tms.). Koulutetut koulunkäynninohjaajat eivät tietenkään toivo, että kouluttamattomasta henkilöstöstä käytettäisiin samaa nimitystä. Ehkä tähän merkitykseen riittäisi pelkkä _avustajat_-käsite, jos on tarpeen kuvailla erikseen.

**Comment by mariaforsen** [comment]
OKSAssa, Tieteen termipankissa, yms. sanastoissa on termi koulunkäyntiavustaja https://termipankki.fi/tepa/fi/haku/%20%20koulunk%C3%A4yntiavustaja
https://termipankki.fi/tepa/fi/haku/skolg%C3%A5ngsbitr%C3%A4de 

Koulunkäynninohjaaja-termiä ei löydy mistään näistä tai TEPAsta ylipäätään. Aika outoa, koska OKSAkin on viime vuodelta. Onko tässä asiassa siis vielä jotain polemiikkiä, eli että osa haluaisi nimityksen olevan nimenomaan -ohjaaja, muttei ole ihan vakiintunut siihen kuitenkaan?

**Comment by mirmaid** [comment]
https://www.osao.fi/opinnot/koulunkaynnin-ja-aamu-ja-iltapaivatoiminnan-ohjaaja/
https://www.tredu.fi/hae-opiskelemaan/koulunkaynnin-ja-aamu-ja-iltapaivatoiminnan-ohjaaja.html

**Comment by mirmaid** [comment]
Ratkaisuehdotus: yhdistetään, päätermiksi koulunkäynninohjaajat.

**Comment by mariaforsen** [comment]
Sv. skolgångshandledare HT skolgångsbiträden

**Comment by mirmaid** [comment]
YSO-toimituskokous päätyi ehdottamaan, että näitä ei kuitenkaan yhdistettäisi, vrt. apuhoitajat/perushoitajat/lähihoitajat.

**Comment by mirmaid** [comment]
Ehdotus: ks. edellinen kommentti, ei muutosta.
