### ISSUE TITLE
Ceylon

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9919]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Ceylon](http://www.yso.fi/onto/yso/p105197)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Eng-päätermin vaihto muotoon "Dominion of Ceylon". Poistetaan Brittiläinen Ceylon,

**Perustelut ehdotukselle**

Nämä ovat kaksi eri käsitettä. Brittiläinen Ceylon http://www.wikidata.org/entity/Q918153  oli  Ceylonin dominion edeltäjä ja Britannian kruununsiirtomaa vuosien 1802 ja 1948 välillä.  Ceylonin dominio oli Britannian siirtomaa vuosina 1948-1972.  http://www.wikidata.org/entity/Q2670092

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
Toinen Ceylonia koskeva ehdotus https://github.com/Finto-ehdotus/YSE/issues/9368

**Comment by mirmaid** [comment]
Englanninkielinen nimimuoto tulee wikidatasta. Jatketaan käsittelyä muilta osin toisessa issuessa.
