### ISSUE TITLE
käsityöläiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9921]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[käsityöläiset](http://www.yso.fi/onto/yso/p1541)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Engl. termiksi craftspeople (ALT craftspersons), yksikössä cratsperson. 
Craftsmen ja craftswomen ohjaustermeiksi.

**Perustelut ehdotukselle**

Sukupuolineutraali ja selkeä termi.

**Ehdottajan organisaatio**

KK

**Comment by fantsby-m** [comment]
Ehdotuksessa typo: yksikössä **craftsperson**

**Comment by mariaforsen** [comment]
Ks. myös https://www.sanakirja.fi/custom/en-sv-fi/hantverkare
