### ISSUE TITLE
Myanmar

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9925]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Myanmar](http://www.yso.fi/onto/yso/p109012)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään käsitteeseen Burma.   http://www.yso.fi/onto/yso/p105715

**Perustelut ehdotukselle**

Käytännössä sama maa, vain hallintomuoto ja nimi vaihtunut vuonna 1990.  Vain yksi käsite WIkdatassa http://www.wikidata.org/entity/Q836  ja LCSH:ssa http://id.loc.gov/authorities/names/n80021691.  Aikaisempi Paganin kunigaskunta olisi eri käsite https://fi.wikipedia.org/wiki/Paganin_kuningaskunta.

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
SAO:
Burma KT Myanmar
https://id.kb.se/term/sao/Burma

**Comment by mirmaid** [comment]
Myanmar KT Burma (säilytetään kuitenkin vanhempi auktoriteetti)
