### ISSUE TITLE
Svetogorsk

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9926]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Svetogorsk](http://www.yso.fi/onto/yso/p113093)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

englanninkielien käytettävä termi vaihdettava muotoon Enso (Jääski), 

**Perustelut ehdotukselle**

Svetogorsk on toisen käsitteen englanninkielinen päätermi http://www.yso.fi/onto/yso/p106569

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
