### ISSUE TITLE
Lesogorsky

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9927]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Lesogorsky](http://www.yso.fi/onto/yso/p105366)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muuttaisin englanninkielinen päätermin muotoon Jääski mikäli käsite viittaa Suomen entiseen kuntaan ennen vuotta 1944. Lesogorsky voinee jäädä ohjaustermiksi.

**Perustelut ehdotukselle**

Lesogorsky viittaa enemmän alueen nykyiseen kuntaan/nimeen Venäjän alueella. Mikäli sitä käytettiin myös Suomen vallana aikana, niin voi jättäää ohjaustermiksi. Muussa tapauksessa siitä olisi tehtävä oma käsitteensä.  Wikidatassa ja -pediassa nämä tosin on esitetty samassa käsitteessä  https://www.wikidata.org/wiki/Q4892     https://en.wikipedia.org/wiki/Lesogorsky    https://fi.wikipedia.org/wiki/J%C3%A4%C3%A4ski 

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Paikkojen englanninkieliset nimimuodot näkyvät sellaisina, kuin ne ovat [Wikidata.org-tietokannassa](https://www.wikidata.org/wiki/Wikidata:Main_Page). YSO-paikoilla ei toistaiseksi ole omaa englanninkielistä ylläpitoa.
