### ISSUE TITLE
tietullit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9929]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tietullit](http://www.yso.fi/onto/yso/p7477)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yhdistetään tietullit käsitteeseen tiemaksut http://www.yso.fi/onto/yso/p7476 ja lisätään käsitteen termit sinne ohjaustermeiksi.

**Perustelut ehdotukselle**

Nykyään tietulli ei ole yläkäsitteen mukaan tullimaksu vaan oikeammin tienkäyttömaksu. Ehkä historiallisena käsitteen kaupungin rajalla piti maksaa (tavarasta) tullimaksu eli "kaupunkitulli". vrt Töölön tulli https://fi.wikipedia.org/wiki/T%C3%B6%C3%B6l%C3%B6n_tulli   Samoin  https://en.wikipedia.org/wiki/Toll_(fee)  alkaa "A toll is a fee charged for the use of a road or waterway."  sekä https://en.wikipedia.org/wiki/Road_toll_(historical)

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by ilona-x** [comment]
yhdistäminen ei varmaan onnistu? Ks. tiemaksut #9930

**Comment by mirmaid** [comment]
Käsitellään ehdotus issuen https://github.com/Finto-ehdotus/YSE/issues/9930 yhteydessä.
