### ISSUE TITLE
tiemaksut

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9930]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[tiemaksut](http://www.yso.fi/onto/yso/p7476)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään ohjaustermiksi tienkäyttömaksu

**Perustelut ehdotukselle**

tarkentaa käsitteen sisältöä. Kts. myös https://fi.wikipedia.org/wiki/Tienk%C3%A4ytt%C3%B6maksu  ja https://fi.wikipedia.org/wiki/Maksullinen_tie  

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jtuohini** [comment]
Onko tämä itse asiassa sama kuin tienhoitomaksu, siis tiekunnan jäseniltä kerätty maksu, joka ei ole käyttöperustainen? Jos on, niin ei oikein voi yhdistää **tietullit**-asiasanaan.

**Comment by ilona-x** [comment]
Kielitoimisotn sanakirja:

**tiemaksu** https://www.kielitoimistonsanakirja.fi/#/tiemaksu?searchMode=all
1. = tienkäyttömaksu. https://www.kielitoimistonsanakirja.fi/#/tienk%C3%A4ytt%C3%B6maksu
2.  tiekunnan osakkaan maksuosuus tiestä. 

**tietulli** https://www.kielitoimistonsanakirja.fi/#/tietulli
vars. autoilijoilta jllak tiellä, tieosuudella t. alueella ajamisesta perittävä maksu. 

**ruuhkamaksu** 
suurkaupunkeihin johtavien teiden käytöstä ruuhka-aikoina perittävä tienkäyttömaksu. 

--

tienkäyttömaksut sopisi ohjaustermiksi **tietullit** -käsitteelle http://www.yso.fi/onto/yso/p7477 ja myös YSOssa olevalle **ruuhkamaksut**-käsitteelle http://www.yso.fi/onto/yso/p21274

Kielitoimiston sanakirjan tiemaksut 2. merkitys ei taida olla pelkästään tien**käyttö**maksu? 
"Tiemaksu
Tieyksiköiden perusteella määräytyvä maksu. kts. yksityistien yksiköinti. Tämän lisäksi voidaan periä perusmaksua ja käyttömaksuja."
Lähde: https://www.tiekunta.fi/sanasto/

"Tiemaksu
Tieyksiköiden perusteella määrätään tiemaksut, jotka peritään tieosakkailta tienpitoon liittyvien kustannusten kattamiseksi."
Lähde: https://finlex.fi/fi/laki/ajantasa/2018/20180560

"Tiemaksut
Tiemaksut perustuvat tiestä saatavaan hyötyyn. Tiemaksuja on kolmenlaisia: yksikkömaksu, käyttömaksu ja perusmaksu. Yleisin hyödyn mitta on tien käyttö. Tiekuntaa perustettaessa toimituksessa sille vahvistetaan ensimmäiset tieyksiköt."
Lähde: https://fi.wikipedia.org/wiki/Tiekunta

**Comment by mariaforsen** [comment]
Yhdistäminen ei onnistu. https://www.kielitoimistonsanakirja.fi/#/tiemaksu?searchMode=all

**Comment by mirmaid** [comment]
Vaatiiko tarkenteen, ettei sekoitu käyttömaksuihin? (esim. yksityistiet/tiekunnat/tienpito/?)

**Comment by jtuohini** [comment]
Olisiko muodossa _**tienhoitomaksut**_ yksiselitteinen? Ei pienintäkään riskiä sekaantumisesta tietulleihin tms. En tiedä, kuinka virallinen kyseinen muoto on, mutta sitä olen kuullut käytettävän (mm. mökkitien osalta tiekunnan kokouksissa), ja googlaamallakin tulee ainakin jotain osumia.

**Comment by YSO-kokous** [comment]
### Päätös
lisätään ohjaustermi  tienkäyttömaksut KÄYTÄ tietullit, ruuhkamaksut
Lisätään päätermiin tarkenne ja uusi ojaustermi  tiemaksut (yksityistiet)  KT tiemaksut (tiekunnat)
