### ISSUE TITLE
keskoset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9931]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[keskoset](http://www.yso.fi/onto/yso/p15938)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

ohjaustermiksi ennenaikaisesti syntyneet lapset

**Perustelut ehdotukselle**

FinMeSH: http://www.yso.fi/onto/mesh/D007234

**Ehdottajan organisaatio**

kk/il

**Comment by mariaforsen** [comment]
Lisätään vastaavat myös ruotsiksi https://finto.fi/mesh/fi/page/D007234?clang=sv
