### ISSUE TITLE
Crouzonin oireyhtymä

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9932]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Crouzonin oireyhtymä

**Ehdotettu termi ruotsiksi**

Crouzons syndrom

**Ehdotettu termi englanniksi**

Crouzon syndrome

**Tarkoitusta täsmentävä selite**

Kallon- ja kasvonluiden geneettinen kasvuhäiriö

**Perustelut ehdotukselle**

Kyseinen oireyhtymä olisi hyvä lisätä oireyhtymien listaan.

**Ehdotettu yläkäsite YSOssa (LT)**

 [oireyhtymät](http://www.yso.fi/onto/yso/p21363), [kasvuhäiriöt](http://www.yso.fi/onto/yso/p10099)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

  Crouzonin kraniofasiaalinen dysostoosi

**Alakäsitteet (RT)**

 [epämuodostumat](http://www.yso.fi/onto/yso/p6004)

**Assosiatiiviset (RT)**

 [luuston sairaudet](http://www.yso.fi/onto/yso/p10782)

**Vastaava käsite muussa sanastossa**

 [Wikipedia](http://Crouzonin oireyhtymä), [NORD - National organization for rare disorders](https://rarediseases.org/rare-diseases/crouzon-syndrome/)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Henley, Ariel: A face for Picasso : coming of age with Crouzon syndrome

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [Crouzonin oireyhtymä](http://finto.fi/yse/fi/page/Y509932)

**Comment by mariaforsen** [comment]
Meshin muoto kraniofasiaalinen dysostoosi  https://finto.fi/mesh/fi/page/D003394

**Comment by fantsby-m** [comment]
YSOssa on termi [kraniosynostoosit](http://www.yso.fi/onto/yso/p28456). Kraniosynostoosi on nähtävästi Crouzonin oireyhtymän keskeisin oire: https://www.tukiliitto.fi/diagnoosit/crouzonin-oireyhtyma/

**Comment by mirmaid** [comment]
Ottaisin muodossa Crouzonin oireyhtymä KT Crouzonin tauti (RT kraniosynostoosit).

**Comment by mariaforsen** [comment]
Sv. Crouzons syndrom HT Crouzons sjukdom 
https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/sallsynta-halsotillstand/crouzons-syndrom/
