### ISSUE TITLE
sepät (ammatit)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9933]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sepät (ammatit)](http://www.yso.fi/onto/yso/p2515)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Alakäsite puusepät on ruotsiksi virheellinen. 

**Perustelut ehdotukselle**

Jos tällä termillä viitataan tähän: "metallia vars. käsityönä (tarve-esineiksi) muokkaava ammattimies" (/Kielitoimiston sk.) niin hierakiamuutos olisi varmaan myös suomeksi hyvä. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Myös kelloseppä = urmakare on ainakin ruotsiksi virheellinen tässä hierarkiassa.
