### ISSUE TITLE
Viipurin kuvernementti

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9934]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Viipurin kuvernementti](http://www.yso.fi/onto/yso/p197138)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Muutetaan eng käytettävä termi muotoon "Vyborg Governorate".

**Perustelut ehdotukselle**

"Old Finland" on käytössä pääterminä käsitteelle Vanha Suomi. http://www.yso.fi/onto/yso/p94473

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jarmosaarikko** [comment]
korjattu linkitykset Wikidatassa http://www.wikidata.org/entity/Q440068 - samalla labelit menevät nyt oikein.
