### ISSUE TITLE
Neste Oil Ralli

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9935]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Neste Oil Ralli](http://www.yso.fi/onto/yso/p27107)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Voisi yhdistää käsitteen Jyväskylän suurajot kanssa.  http://www.yso.fi/onto/yso/p12856

**Perustelut ehdotukselle**

Eikö tämä ole käytännössä sama ralli, joka ajettu eri vuosina eri nimillä. Viimeisin Secto Rally Finland.   https://www.wikidata.org/wiki/Q849851   Käytettävä termi voisi olla "Suomen ralli". 

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by jtuohini** [comment]
Kantoon kuuluva asia! Ja jos tapahtuma on vaihtanut nimeään, niin sitten mennään RDA:n ohjeistuksella siitä, milloin kyseessä on oma entiteettinsä tms.
