### ISSUE TITLE
Gangsta rap

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9936]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Gangsta rap

**Ehdotettu termi ruotsiksi**

Gangstarap eller gangsterrap

**Ehdotettu termi englanniksi**

Gangsta rap

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Selkeä rap-musiikin alagenre

**Ehdotettu yläkäsite YSOssa (LT)**

 [rap](http://www.yso.fi/onto/yso/p10871), [hip hop](http://www.yso.fi/onto/yso/p14336)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

 Gangsta rap or gangster rap, initially called reality rap (https://en.wikipedia.org/wiki/Gangsta_rap)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [](http:// Gangsta rap (Music))

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

 From staircase to stage  

**Ehdottajan organisaatio**

Kirjastopalvelu /OH
**Termiehdotus Fintossa:** [Gangsta rap](http://finto.fi/yse/fi/page/Y509936)

**Comment by jtuohini** [comment]
Tarvittaneen sekä YSO:ssa että SLM:ssä.

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

LCSH: http://id.loc.gov/authorities/subjects/sh2006007673
LCGFT: http://id.loc.gov/authorities/genreForms/gf2014026830

**Comment by mirmaid** [comment]
Hyväksytty/SLM.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.

**Comment by mariaforsen** [comment]
Sv. gangsterrap
