### ISSUE TITLE
foxtrot (dance music)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9937]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[foxtrot (dance music)](http://www.yso.fi/onto/yso/p23372)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

eng. sävellyksiin viittaavissa käsitteissä vaihtelee tarkenne, (compositions) vs. (dance music) - olisi hyvä yhtenäistää

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by MUUSA-kokous** [comment]
Foxtrot (dance music) on pätevä ohjaustermi.

**Comment by mirmaid** [comment]
Eli olisiko päätermin tarkenne compositions-käsitteen alakäsitteillä aina (compositions)? Nyt vahtelee melko paljon.

**Comment by YSO-kokous** [comment]
###Päätös
Odotetaan Muusan käsittelyä  tarkenteen muodosta

**Comment by MUUSA-kokous** [comment]
Tarkenne compositions silloin, kun suomenkielinen vastine on sävellykset.
