### ISSUE TITLE
esineellistäminen

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9939]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

esineellistäminen

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

objectification

**Tarkoitusta täsmentävä selite**

Se, ettei suhtaudu ihmiseen ihmisyksilönä, vaan tavarana, jota voi liikutella, omistaa, kosketella ja katsella. (Wikisanakirja)

**Perustelut ehdotukselle**

Esineellistäminen-käsitettä on käytetty jo 1970-luvulta asti ja on edelleen olennainen käsite keskustelussa naisen asemasta ja naisruumiin seksualisoimisesta yhteiskunnassa. Tuotteistus-termi on vähän harhaanjohtava tässä yhteydessä eikä kata kaikkea esineellistämistä, koska esineellistää voi tuotteistamattakin vaikka mielessään, puheissaan tai teoissaan. 

Esineellistäminen-käsitettä voidaan käyttää myös esimerkiksi eläimistä.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

 seksuaalinen objektivointi

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](https://id.loc.gov/authorities/subjects/sh2017004494.html), [Wikipedia](https://en.wikipedia.org/wiki/Objectification)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Ratajkowski: My body.

**Ehdottajan organisaatio**

Kirjastopalvelu
**Termiehdotus Fintossa:** [esineellistäminen](http://finto.fi/yse/fi/page/Y509939)

**Comment by mirmaid** [comment]
5 kertaa Melindassa.

**Comment by mariaforsen** [comment]
Sv. objektifiering https://sv.wikipedia.org/wiki/Objektifiering
