### ISSUE TITLE
oireyhtymät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9940]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[oireyhtymät](http://www.yso.fi/onto/yso/p21363)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisäys oireyhtymälistaukseen: Crouzonin oireyhtymä / Crouzon syndrome

**Perustelut ehdotukselle**

Täsmätermi sairaudelle

**Ehdottajan organisaatio**

Kirjastopalvelu/ OH

**Comment by mirmaid** [comment]
Tästä olikin oma termiehdotuksensa: https://github.com/Finto-ehdotus/YSE/issues/9932.
