### ISSUE TITLE
Peräseinäjoen kirkko

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9941]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[Peräseinäjoen kirkko](http://www.yso.fi/onto/yso/p23377)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

yhdistetään käsitteeseen Pyhän Paavalin kirkko (Peräseinäjoki) http://www.yso.fi/onto/yso/p18757

**Perustelut ehdotukselle**

kyseessä on sama kirkko  kts. https://www.seinajoenseurakunta.fi/peraseinajoen-kirkko ; http://www.wikidata.org/entity/Q19708556 ;  https://fi.wikipedia.org/wiki/Per%C3%A4sein%C3%A4joen_kirkko

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto

**Comment by mirmaid** [comment]
Yhdistetään.
