### ISSUE TITLE
junapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9943]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

junapelit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-termi, oma kategoriansa lautapelien alagenrenä

**Perustelut ehdotukselle**

Kymmeniä vuosia omana alagenrenään ollut käsite, junapeleillä on oma harrastajakuntansa. Lisäksi on myös junapelejä, joita pelataan laajemminkin (Menolippu / Ticket to ride)

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lautapelit

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [junapelit](http://finto.fi/yse/fi/page/Y509943)

**Comment by ilona-x** [comment]
Hyväksytään SLM-sanastoon junapelit /SLM-kokous 19.4.2022
Yläkäsite pelit
https://www.lautapeliopas.fi/teemat/junapelit/

**Comment by mariaforsen** [comment]
Sv. tågspel
