### ISSUE TITLE
sivilisaatiopelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9944]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

sivilisaatiopelit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-termi

**Perustelut ehdotukselle**

Oma kategoriansa, näitä on sekä digitaalisten että fyysisten pelien puolella. Yleensä peli käsittää pitkän jakson historiaa, sekä sisältää tarinan kaaren ja oman yhteiskuntansa kehityksen

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lautapelit

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [sivilisaatiopelit](http://finto.fi/yse/fi/page/Y509944)

**Comment by ilona-x** [comment]
Hyväksytään SLM-sanastoon /SLM-kokous 19.4.2022
yläkäsite pelit?
https://www.lautapeliopas.fi/teemat/sivilisaatiopelit/

**Comment by mariaforsen** [comment]
Sv. civilisationsspel
