### ISSUE TITLE
kampanjapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9945]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kampanjapelit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-termi

**Perustelut ehdotukselle**

Pelaaminen koostuu useasta eri pelisessiosta, peli yleensä muuttuu (säännöiltään tai komponenteiltaan) pelin edetessä. Näitä julkaistaan paljon, osa ei ole kirjastomateriaalia mutta elementtinä tämä on nykyään jo monessa pelissä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lautapelit

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [kampanjapelit](http://finto.fi/yse/fi/page/Y509945)

**Comment by ilona-x** [comment]
https://www.lautapeliopas.fi/pelimekaniikat/kampanjapelit/

**Comment by ilona-x** [comment]
Hyväksytään SLM-sanastoon: kampanjapelit (lautapelit)
Tälle kaivattiin määritelmää: Lautapelioppaassa: "Yksittäiset pelikerrat muodostavat yhtenäisen kampanjan"

**Comment by mariaforsen** [comment]
Sv. kampanjspel (brädspel)?
