### ISSUE TITLE
näppäryyspelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9947]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

näppäryyspelit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-termi

**Perustelut ehdotukselle**

Peli jossa on fyysinen elementti, esimerkiksi neppailua tai palikoiden pinoamista. Hyvin yleinen mekaniikka

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lautapelit

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [näppäryyspelit](http://finto.fi/yse/fi/page/Y509947)

**Comment by ilona-x** [comment]
https://www.lautapeliopas.fi/luokat/napparyyspelit/

englanniksi dexterity games

**Comment by ilona-x** [comment]
Hyväksytään SLM-sanastoon / SLM-kokous 19.4.2022
Yläkäsite lautapelit?

**Comment by mariaforsen** [comment]
Sv. fingerfärdighetsspel
