### ISSUE TITLE
tikkipelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9948]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tikkipelit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-termi

**Perustelut ehdotukselle**

Perinteinen tapa pelata korteilla, puhutaan myös kiipeämispeleistä, mutta Tikkipelit on yleisempi ja laajempi käsite. Näitä siis julkaistaan myös itsenäisinä peleinä, muokatuilla korteilla

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lautapelit

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [tikkipelit](http://finto.fi/yse/fi/page/Y509948)

**Comment by ilona-x** [comment]
https://fi.wikipedia.org/wiki/Tikkipeli

**Comment by ilona-x** [comment]
Hyväksytään SLM-sanastoon **tikkipelit (lautapelit)** yläkäsite lautapelit. / SLM-kokous 19.4.2022

**Comment by mariaforsen** [comment]
Sv. stickspel (brädspel) HT sticktagningsspel (brädspel)
