### ISSUE TITLE
Filleripelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9949]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Filleripelit

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

SLM-termi

**Perustelut ehdotukselle**

Lyhytkestoinen peli, joka pelataan esim kahden isomman pelin välissä tai peli-illan alussa.  Vakiintunut termi : "otetaanko joku filleri alkuun"

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Lautapelit

**Ehdottajan organisaatio**

Helsingin kaupunginkirjasto
**Termiehdotus Fintossa:** [Filleripelit](http://finto.fi/yse/fi/page/Y509949)

**Comment by ilona-x** [comment]
Lyhytkestoisia lautapelejä.
Tälle toivottiin määritelmää, esimerkiksi: https://www.lautapeliopas.fi/luokat/fillerit/
Yläkäsitteeksi lautapelit?
Hyväksytään SLM-sanastoon / SLM-kokous 19.4.2022

**Comment by mariaforsen** [comment]
Sv. fillerspel HT utfyllnadsspel

**Comment by mirmaid** [comment]
KT fillerit (pelit)?

Määritelmä: Lyhytkestoinen lautapeli. / Lyhytkestoinen, helposti opittava lautapeli.

**Comment by mirmaid** [comment]
KT fillerit (pelit)
Määritelmä: Lyhytkestoinen, helposti opittava lautapeli.
