### ISSUE TITLE
myostatiini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9950]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

myostatiini

**Ehdotettu termi ruotsiksi**

myostatin

**Ehdotettu termi englanniksi**

myostatin

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
myostatiini x 4
myostatiinit x 2

**Ehdotettu yläkäsite YSOssa (LT)**

 [proteiinit](http://www.yso.fi/onto/yso/p4332)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [FinMeSH](http://www.yso.fi/onto/mesh/D055435), [Wikipedia](https://fi.wikipedia.org/wiki/Myostatiini)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Molecular and physiological effects of muscle wasting and its treatment by blocking myostatin and activins

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [myostatiini](http://finto.fi/yse/fi/page/Y509950)

**Comment by mariaforsen** [comment]
Sv. myostatin HT GDF-8
