### ISSUE TITLE
diaspora

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9951]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[diaspora](http://www.yso.fi/onto/yso/p8486)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Ehdotan ainakin ryhmän 61 (ja 65?) lisäämistä ontologiaan.

**Perustelut ehdotukselle**

Diaspora ei ole vain uskonnollinen käsite. Esim. https://fi.wikipedia.org/wiki/Diaspora

**Ehdottajan organisaatio**

Kirjastopalvelu

**Comment by annamarj** [comment]
Kannatan. Tosiaan aika paljon käytetty myös yhteiskuntatieteissä/kulttuurintutkimuksessa.

**Comment by mirmaid** [comment]
Ryhmien lisäämistä kannatettu.
