### ISSUE TITLE
Masennuslääke

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9952]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Masennuslääke

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Masennuslääkkeet ovat yleinen lääkaineryhmä, ja asiasana toimisi yläkäsitteenä esim. SSRI-lääkkeille.

**Ehdotettu yläkäsite YSOssa (LT)**

 [lääkkeet](http://www.yso.fi/onto/yso/p1077)

**Ehdotetut temaattiset ryhmät**

 [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [SSRI-lääkkeet](http://www.yso.fi/onto/yso/p26767), [psyykenlääkkeet](http://www.yso.fi/onto/yso/p7977)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Irti masennuslääkkeistä / Rostain Jenny

**Ehdottajan organisaatio**

Turun yliopiston kirjasto
**Termiehdotus Fintossa:** [Masennuslääke](http://finto.fi/yse/fi/page/Y509952)

**Comment by ilona-x** [comment]
FinMeSH: masennuslääkkeet http://www.yso.fi/onto/mesh/D000928
TERO: masennuslääkkeet http://www.yso.fi/onto/tero/D000928
LCSH: Antidepressants http://id.loc.gov/authorities/subjects/sh85005661

**Comment by mariaforsen** [comment]
Sv. antidepressiva läkemedel HT antidepressiva medel, depressionsmediciner/läkemedel
https://id.kb.se/find?q=Antidepressiva%20medel

**Comment by fantsby-m** [comment]
FinMeSHistä löytyy myös kattava lista ohjaustermejä.
