### ISSUE TITLE
Sanginjoen luonnonsuojelualue

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9954]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Sanginjoen luonnonsuojelualue

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

https://www.luontoon.fi/sanginjoki
Sanginjoki on yhtenäinen metsäalue ja sijaitsee noin 16 kilometrin päässä Oulun keskustasta. Alueella on luonnonmetsän piirteitä, vanhoja kuusikoita myös korpia ja kuivaa harjuluontoa. Sanginjoella on tavattu uhanalaisia kääpiä ja harvinaisia lintulajeja.

Sanginjoen luonnonsuojelualue siirtyi Metsähallituksen hallintaan keväällä 2021.

**Perustelut ehdotukselle**

Tarvitaan kuvailussa

**Ehdotettu yläkäsite YSOssa (LT)**

 [luonnonsuojelualueet](http://www.yso.fi/onto/yso/p1371)

**Ehdotetut temaattiset ryhmät**

 [18 Luonnonsuojelu. Ympäristönsuojelu. Ympäristö. Jätteet](http://www.yso.fi/onto/yso/p26560), [62 Yhteiskuntasuunnittelu. Yhdyskuntasuunnittelu. Aluesuunnittelu](http://www.yso.fi/onto/yso/p26526)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://julkaisut.metsa.fi/julkaisut/show/2632

**Ehdottajan organisaatio**

kk
**Termiehdotus Fintossa:** [Sanginjoen luonnonsuojelualue](http://finto.fi/yse/fi/page/Y509954)

**Comment by mariaforsen** [comment]
Sv. Sanginjoki naturskyddsområde
