### ISSUE TITLE
Sandö (Nauvo)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9956]
**Käsitteen tyyppi**

GEO

**Ehdotettu termi suomeksi**

Sandö (Nauvo)

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Album VI

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [Sandö (Nauvo)](http://finto.fi/yse/fi/page/Y509956)

**Comment by mirmaid** [comment]
Sandö (Nauvo) vai Sandö (Parainen, Nauvo)?

**Comment by ilona-x** [comment]
Tämän pnr-linkki? Sandö-nimisiä saaria näyttää olevan Paraisilla 3 kpl.

**Comment by mirmaid** [comment]
Sandö (Parainen, Nauvo)
