### ISSUE TITLE
mailapelit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9958]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[mailapelit](http://www.yso.fi/onto/yso/p1929)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan tai mahdollisesti poistetaan? Tai muutetaan ruotsiksi > "spel med klubba, racket eller slagträ" ja englanniksi vastaavalla tavalla (mailat=bats, rackets, sticks and clubs)

**Perustelut ehdotukselle**

Ei täsmää ruotsiksi, eikä englanniksi. Ks. myös aiempi päätös termistä "mailat". 

**Ehdottajan organisaatio**

ALLFO

**Comment by jarmosaarikko** [comment]
#9173

**Comment by jarmosaarikko** [comment]
"racket sport" on Wikidatassa käännetty suomeksi nimellä "Mailaurheilu".  
- https://en.wikipedia.org/wiki/List_of_racket_sports  - lista näistä peleistä englanniksi.

Tuosta listasta kuitenkin puuttuvat "loput" mailapelit, jotka pelataan muunlaisilla mailoilla... eli miköhän tuossa nyt olisi "oikea" suomenkielinen käännös? Varmaan edelleen mailapelit mutta ehkä jollakin tarkenteella?

Saksaksi näyttää  [Schläger (Sport)](https://de.wikipedia.org/wiki/Schl%C3%A4ger_(Sport))  olevan lähellä suomen **mailat**-käsitettä.

https://en.wikipedia.org/wiki/Team_sport
Tämän joukkueurheilusivun jaottelussa mailapelit näkyvät alaosan taulussa nimillä:
- **Bat-and-ball games**
- **Stick and ball sports**  (Hockey sports, Polo sports)
- **Net sports** (tässä on tenniksen ja sulkapallon lisäksi muitakin kuin mailapelejä)
muita kuin joukkuepelejä on sitten esim.
- [cue sports](https://www.wikidata.org/wiki/Q3341285) - biljardipelit

**Comment by mirmaid** [comment]
Käytetty 165 kertaa. Tarvitaanko tätä? Onhan näillä peleillä yhteinen nimittäjä olemassa, mutta aika vähän yhteistä on biljardilla ja jääkiekolla tai pesäpallolla ja golfilla.

**Comment by mariaforsen** [comment]
Tosiaan on hyvin vähän yhteistä, kannatan poistoa. Wikidatassa pitäisi korjata, racket sport EI ole sama asia kuin mailaurheilu, vaan paljon suppeampi merkitykseltään. 

Biljardi ei muuten sisälly tuohon aikaisempaan ruotsinnokseen (ei ole klubba, racket tai slagträ, vaan biljardissa välineen nimitys on biljardkäpp tai kö)

**Comment by YSO-kokous** [comment]
### Päätös
Poistetaan **mailapelit** sanastosta
