### ISSUE TITLE
tuomarinympyrät

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9959]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

tuomarinympyrät

**Ehdotettu termi ruotsiksi**

domarringar

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

pohjoismainen tyyppi

**Ehdotettu yläkäsite YSOssa (LT)**

 [muinaisjäännökset](http://www.yso.fi/onto/yso/p5340)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Tuomarinympyr%C3%A4)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

http://akp.nba.fi/wiki;k%C3%A4r%C3%A4j%C3%A4ympyr%C3%A4

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [tuomarinympyrät](http://finto.fi/yse/fi/page/Y509959)

**Comment by jarmosaarikko** [comment]
MAO/TAO: käräjäympyrät - http://www.yso.fi/onto/mao/p4604  YK käräjäpaikat http://www.yso.fi/onto/mao/p8122
Wikidata http://www.wikidata.org/entity/Q1236830  en: stone ring alias domarring, judge circle; sv:domarring

**Comment by mirmaid** [comment]
Kumpaakaan muotoa ei Melindassa, muutamia viitteitä muodossa _käräjäkivet_. Tämä on myös eniten käytetty muoto Googlella, mutta käytetty myös muissa yhteyksissä kuin varsinaisista muinaisjäännöksistä.

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään muodossa käräjäympyrät OT tuomarinympyrät
