### ISSUE TITLE
metsäauraus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9961]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

metsäauraus

**Ehdotettu termi ruotsiksi**

skogplogning

**Ehdotettu termi englanniksi**

forest ploughing

**Tarkoitusta täsmentävä selite**

Metsämaan käsittely ennen siemennystä tai istutusta. 
Soil preparation before seeding or planting

**Perustelut ehdotukselle**

tälle löytyy kymmeniä viittauksia Melindassa, jotka jäivät ilman käsitettä, kun auraus
#8397   muutettiin käsittämään vain lumenauraus.

**Ehdotettu yläkäsite YSOssa (LT)**

 [maanmuokkaus](http://www.yso.fi/onto/yso/p8786)

**Ehdotetut temaattiset ryhmät**

 [21 Metsätalous. Metsänhoito](http://www.yso.fi/onto/yso/p26537)

**Vaihtoehtoiset termit**

metsänauraus, ploughing of forest soil, forest plowing

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [metsänkäsittely](http://www.yso.fi/onto/yso/p27050)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. * Aluminium chemistry in ploughed podzolic forest soils / c Niina Tanskanen. * Arktisten metsien kasvun ihme / c Olavi Huikari. * Aurausjäljen muuttuminen ja kasvillisuuden kehittyminen metsänuudistusaloilla Lapissa 10 vuoden aikana = |b Development of ploughed tracks and vegetation on reforestation areas in Finnish Lapland during a period of 10 years / |c Ari Ferm ja Pentti Sepponen. Lapissa (ja muualla) runneltiin metsämaata auraamalla näitä 1980 ja 90-luvuilla. Nyt  nämä tietueet ovat vailla "tätä aihetta kuvaavaa" termiä

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto asiakaspalaute (HULib)
**Termiehdotus Fintossa:** [metsäauraus](http://finto.fi/yse/fi/page/Y509961)

**Comment by jarmosaarikko** [comment]
Edelleen ajankohtainen käsite.  Kts esim 
- https://www.finna.fi/Search/Results?lookfor=mets%C3%A4auraus&type=AllFields - 893 osumaa
- https://www.metsalehti.fi/artikkelit/kustannukset-puoltavat-auraa/#40123c87 - Metsälehti 23.2.2021 
- https://www.luke.fi/blogi/maanmuokkaus-lisaa-metsan-kasvua-ja-sen-myota-hiilivarastoa/ 
- https://www.mhy.fi/siikalakeus/metsanhoito/metsan-uudistamispaketti/metsaauraus
- https://www.metsalehti.fi/artikkelit/10-uskomusta-metsanhoidosta/#40123c87 (kohta 3)

Koneellinen metsämaan muokkaus tosin on nykyään usein muuta kuin aurausta. Esim. laikutusta, mätästystä jne.

**Comment by jtuohini** [comment]
Kielellisesti oikeampi muoto lienee metsä**n**auraus, vrt. lume**n**auraus (ei 'lumiauraus') ja vaikkapa metsä**n**muokkaus (ei 'metsämuokkaus').

"[K]un verbi saisi vaihtelevasijaisen kohdetta tarkoittavan objektin (esim. soittaa viulua, heittää kiven), on yhdyssanan alkumuotona genetiivi (viulunsoitto, kivenheitto) tavallisempi kuin nominatiivi. Silti nominatiivikin on usein mahdollinen (jalkahoito)." (http://www.kielitoimistonohjepankki.fi/haku/yhdyssana/ohje/393)

**Comment by mirmaid** [comment]
^ Molempia käytetty, enemmän kuitenkin _metsäauraus_. Yllättävän vähän lopulta Googlella (ja hyvä tietysti niin).

**Comment by mariaforsen** [comment]
Sv. skogplogning ei ole käytössä oleva termi. Jonkin verran käytetty "skogsplöjning", mutta enemmän hyggesplöjning (onkohan aivan sama asia?) https://www.skogskunskap.se/ordlista/h/hyggesplojning/ 
Nykyään kielletty menetelmä ainakin Ruotsissa.

**Comment by fantsby-m** [comment]
Metsien yhteydessä käytetään ehkä yleisimmin vain sanaa _auraus_ eikä yhdyssanaa _metsänauraus_ tai _metsäauraus_. Termihän voisi olla myös _auraus (metsätalous)_ tms. - ja nuo muut sitten ohjaustermeiksi?

**Comment by YSO-kokous** [comment]
### Päätös
hyväksytään metsäauraus OT metsänauraus, auraus (metsänkäsittely), auraus (metsät)

**Comment by mariaforsen** [comment]
Sv. skogsplöjning HT hyggesplöjning 
https://www.landskogsbruk.se/skog/forbjuden-plog-lockar-forskare/
