### ISSUE TITLE
äärivasemmistolaisuus

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9963]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

äärivasemmistolaisuus

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

far left

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Vasemmiston radikaalisiipi oman terminsä alle. 

**Ehdotettu yläkäsite YSOssa (LT)**

 [vasemmistolaisuus](http://www.yso.fi/onto/yso/p448)

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

 [ääriliikkeet](http://www.yso.fi/onto/yso/p19), [antirasismi](http://www.yso.fi/onto/yso/p8643), [antifasismi](http://www.yso.fi/onto/yso/p27239)

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Finna

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [äärivasemmistolaisuus](http://finto.fi/yse/fi/page/Y509963)

**Comment by jarmosaarikko** [comment]
Wikidata: http://www.wikidata.org/entity/Q1129409 
aliaksia ultravasemmisto. ultravasemmistolaisuus.  far-left alias far left, extreme left;  vänsterextremism alias extremvänster
https://en.wikipedia.org/wiki/Far-left_politics
https://fi.wikipedia.org/wiki/%C3%84%C3%A4rivasemmisto
https://sv.wikipedia.org/wiki/V%C3%A4nsterextremism

LCSH [Left-wing extremists](http://id.loc.gov/authorities/subjects/sh95005689) on linkattu Wikidatassa käsitteeseen [leftism](https://www.wikidata.org/wiki/Q2660346)  mikä lienee virhe tai sama käsite kuin Q1129409?

**Comment by mariaforsen** [comment]
Sv. vänsterextremism https://id.kb.se/find?q=Left-wing%20extremists HT extremvänster, revolutionär vänster, ultravänster, radikal vänster

**Comment by annamarj** [comment]
Ehdotuksessa ei oikein esitetä perusteluja. Siinä esitetyt assosiatiiviset käsitteet ovat myös outoja (miksi antirasisti ei voisi olla poliittisesti oikealla tai keskellä, mikä yhdistää koko nimityksen ääriliikkeeseen?) YSOssa kuitenkin on äärioikeisto ->KT äärioikeistolaisuus. Sen assosiatiiviset käsitteet liittyvät tarkkarajaisemmin juuri noilla nimillä poliittisessa historiassa tunnettuihin aatteisiin ja liikkeisiin ja ovat yleisessä käytössä (myös tutkimuksessa, jonkin verran myös näiden aatteiden edustajien omassa käytössä. Äärivasemmisto on nähdäkseni  epätarkempi ja Suomessa lähinnä pejoratiivisessa käytössä.)  Tähän voisi haluttaessa hakea vielä näkökulmaa yleistajuisista tutkimuskäsitteistä? Tuolla ehdotuksessa #10105 on kuitenkin myös perusteluja (sisäministeriön julkaisujen kuvailutarve). Assosiatiivisten käsitteiden perusteet voisi ainakin miettiä, jos tämä otetaan. Ja mahdollisesti ohjaustermeiksi sekä oikeistoradikalismi -> äärioikeistolaisuus että vasemmistoradikalismi -> äärivasemmistolaisuus.
