### ISSUE TITLE
hajutyöskentely

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9965]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

hajutyöskentely

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

koirankoulutuksessa tehdään hajutyöskentelyä, noseworkiä

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

ensimmäinen suomenkielinen kirja noseworkistä ilmestyi 2021: Elli Kinnunen: Löytö! : Nosework-harrastajan opas  

**Ehdottajan organisaatio**

Jyväskylän kaupunginkirjasto
**Termiehdotus Fintossa:** [hajutyöskentely](http://finto.fi/yse/fi/page/Y509965)

**Comment by jarmosaarikko** [comment]
Wikipedia https://en.wikipedia.org/wiki/Nosework   nosework, nose work, scent work, scent detection
Wikidata http://www.wikidata.org/entity/Q21002376
Wikipedia-artikkelin perusteella yläkäsite on [koiraurheilu](http://www.yso.fi/onto/yso/p27444)
Katso myös: https://www.kennelliitto.fi/koiraharrastukset/kokeet-ja-kilpailut/nosework

Kennelliitto ja [lajiyhdistys ](https://www.nwf.fi/yhdistys/) käyttävät kansainvälistä termiä **nosework**
> _Nosework -kokeessa koira etsii sille merkitykselliseksi koulutettuja hajuja erilaisissa ympäristöissä_

Kannatan termiä **hajutyöskentely** KT nosework

**Comment by mirmaid** [comment]
_Nosework_ taitaa olla käytetympi myös meillä.

**Comment by mariaforsen** [comment]
Sv. nosarbete HT nosework 
https://www.skk.se/sv/prov-tavling/olika-prov-och-tavlingar/nosework/
https://www.adlibris.com/fi/sv/bok/nosework-allt-du-behover-veta-9789198161380

**Comment by YSO-kokous** [comment]
### Päätös
otetaan muodossa hajutyöskentely  OT nosework
