### ISSUE TITLE
substanssi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9966]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[substanssi](http://www.yso.fi/onto/yso/p1058)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitseeko tarkenteen (filosofia)?

**Perustelut ehdotukselle**

Käytön johdonmukaisuus

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Nyt käyttö jonkin verran hajoaa:
_Kielen ja substanssin integroivan opetuksen kehittäminen 
Geotekninen tutkimus ja koestus. Osa 1, Maan ja kallion luokitukset : Geotechnical investigation and testing. Part 1, Classification of soil and rock
Pk-yrityksen arvonmääritys yrityskauppatilanteissa
Kulttuuriyrittäjyys Savonlinnassa : paikallisuuden vaihtelut identiteetissä, substanssissa, verkostoissa ja markkinoissa_ 

Suurin osa käytöstä filosofiaa.

**Comment by mariaforsen** [comment]
Tarpeen myös ruotsiksi: https://svenska.se/tre/?sok=substans&pz=8  Vrt. https://www.kielitoimistonsanakirja.fi/#/substanssi?searchMode=all
SAOssakin tarkenteella https://id.kb.se/find?q=substans

**Comment by mirmaid** [comment]
Ratkaisuehdotus: lisätään tarkenne (filosofia)
