### ISSUE TITLE
sofismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9967]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sofismi](http://www.yso.fi/onto/yso/p19567)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Poistetaan sanastosta? KÄ sofistit

**Perustelut ehdotukselle**

Päällekkäisiä, käsite hiukan epäselvä.

**Ehdottajan organisaatio**

**Comment by jarmosaarikko** [comment]
Ovat Wikidatassa eri käsitteinä
**sofisti** - http://www.wikidata.org/entity/Q3750514  (YSO-ID [26223](https://www.yso.fi/onto/yso/p26223)) - https://en.wikipedia.org/wiki/Sophist
**sofismi** - http://www.wikidata.org/entity/Q166955 - (sisältää YSO-ID [19567](https://www.yso.fi/onto/yso/p19567), joka on merkittävä vanhentuneeksi jos käsite poistuu) 

Mutta En-wikipediassa yhdessä, sillä "Sophistic movement" onkin edelleenohjaus käsitteeseen "Sophist" -- eli toimii samaan tapaan kuten tässä issuessa ehdotetaan YSOon.  Fi-wikipediassa on vain [Sofismi](https://fi.wikipedia.org/wiki/Sofismi).
eli ristiin rastiin mennään. 
LCSH:ssa [Sophists (Greek philosophy)](http://id.loc.gov/authorities/subjects/sh85125278)

**Comment by mirmaid** [comment]
Taustana taisi olla se, että sofismilla on myös merkitys "tahallinen virhepäätelmä tai näennäistodistus", eli tarvitsisi tarkenteen. Koska ei kuitenkaan ole tiedossa, että sofistien ajattelu olisi muodostanut varsinaisesti yhtenäisen aatteen, koulukunnan tms., tarkenteen keksiminen ei ole ihan helppoa. Kun termi lisäksi on käytössä täysin päällekkäinen _sofistit_-termin kanssa, ajateltiin että jälkimmäinen riittää.

**Comment by mariaforsen** [comment]
https://svenska.se/tre/?sok=sofism&pz=1 Eli sofism on ruotsiksi: "yttrande som skenbart är egendomligt eller orimligt men i verkligheten kan bevisas genom någon typ av logiskt resonemang" Jonkinlainen virhepäätelmä siis. Jos olisi viitattu sofistien liikeeseen termi olisi ruotsiksi "sofistik" -ks. Nationalencyklopedin

SAOssakin on vain yksi termi: sofisterna (ohjausterminä sofistik) https://id.kb.se/find?q=sofistik

**Comment by mirmaid** [comment]
Ratkaisuehdotus: poistetaan, KÄ sofistit.
