### ISSUE TITLE
dandiedinmontinterrieri

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9970]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

dandiedinmontinterrieri

**Ehdotettu termi ruotsiksi**

Dandie dinmont terrier

**Ehdotettu termi englanniksi**

Dandie Dinmont Terrier

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailussa
Melinda x 3

**Ehdotettu yläkäsite YSOssa (LT)**

 [terrierit](http://www.yso.fi/onto/yso/p14668)

**Ehdotetut temaattiset ryhmät**

 [17 Eläintiede](http://www.yso.fi/onto/yso/p26529)

**Vaihtoehtoiset termit**

 dandie, Dandie (Dog)

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia](https://fi.wikipedia.org/wiki/Dandiedinmontinterrieri), [LCSH](http://id.loc.gov/authorities/subjects/sh85035697), [SAO]( https://id.kb.se/term/sao/Dandie%20dinmont%20terrier )

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Dandie ISSN 2737-3770

**Ehdottajan organisaatio**

Kansalliskirjasto
**Termiehdotus Fintossa:** [dandiedinmontinterrieri](http://finto.fi/yse/fi/page/Y509970)

**Comment by jarmosaarikko** [comment]
Melindassa 2 kertaa (alan lehti ja yhdistys) Finnassa 3 (sama lehti kolmella nimellä).  
Wikidata: http://www.wikidata.org/entity/Q38336
