### ISSUE TITLE
transsendentalismi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9971]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[transsendentalismi](http://www.yso.fi/onto/yso/p2716)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

mikä on tämän ja transsendentaalifilosofia -käsitteen ero? Tieteentermipankissa synonyymeja.

Melinda:
transsendentaalifilosofia x 37 (otettu sanastoon v. 2010)
transsendentalismi  x 157 (otettu sanastoon v. 1993)

**Perustelut ehdotukselle**

https://tieteentermipankki.fi/wiki/Filosofia:transsendentaalifilosofia

**Ehdottajan organisaatio**

kk/il

**Comment by mirmaid** [comment]
Ainakin osassa näyttää olevan kyse tästä: https://fi.wikipedia.org/wiki/Transsendentaalinen_idealismi, https://tieteentermipankki.fi/wiki/Nimitys:transsendentaalinen_idealismi.

**Comment by mariaforsen** [comment]
Ovat eri asioita, ks. esim. NE:  
-"transcendentalfilosofi: den filosofi som i Kants efterföljd strävar att klarlägga de nödvändiga eller oundgängliga grundvalar på vilka all vår kunskap vilar."
-"transcendentalism: "amerikansk litterär och filosofisk rörelse ca 1836–60 med centrum i Bostonområdet, speciellt i den lilla staden Concord."

https://fi.wikipedia.org/wiki/Henry_David_Thoreau : "Emersonin houkuttelemana Concordiin muutti muitakin runoilijoita, ja he perustivat transsendentalismin suuntauksen, jossa romantiikka yhdistyy uudistukseen ja joka korostaa yksilöä, tunnetta ja luontoa. Transsendentalismi oli ulkonaisesti vähäpätöinen liike, mutta 1800-luvun lopulla sen keskeiset nimet Emerson ja Thoreau nousivat englanninkielisen kirjallisuuden merkkihenkilöiksi."

Vaikuttaa siis siltä ettei Tieteen termipankissa vielä ole tehty artikkelia jälkimmäisestä transsendentalismista?

Ks. https://www.britannica.com/search?query=Transcendentalism :
1) Transcendentalism (American movement)
"Transcendentalism, 19th-century movement of writers and philosophers in New England who were loosely bound together by adherence to an idealistic system of thought based on a belief in the essential unity of all creation, the innate goodness of humanity, and the supremacy of insight over logic and..."
2) transcendental idealism, also called formalistic idealism
"term applied to the epistemology of the 18th-century German philosopher Immanuel Kant,  who held that the human self, or [transcendental ego, constructs knowledge out of sense impressions and from universal concepts called categories that it imposes upon them..."

**Comment by ilona-x** [comment]
Melindassa haku transsendentalismi & Kant tuottaa 47 viitettä ja haku Kant & transsendentaalifilosofia tuottaa 29 viitettä. Jonkun Kantin filosofiaa käsittelevän aineiston yhteydessä tähän törmäsin ja hämmennyin, kun näytti, että samantyyppisten aineistojen kuvailuissa oli käytetty välillä transsendentalismi -termiä ja välillä transsendentaalifilosofia -termiä.

YSOn **transsendentalismi** on linkattu LCSH-termiin **Transcendentalism**, jolla alakäsitteinä Neo-Kantianism & Transcendental logic
http://id.loc.gov/authorities/subjects/sh85136885

**Comment by mirmaid** [comment]
^ Jotenkin pitäisi kyllä saada nämä pysymään erillään, mutta eipä ole helppo tarkennepähkinä...

**Comment by ilona-x** [comment]
LCSHssa näköjään:
Transcendentalism (New England) http://id.loc.gov/authorities/subjects/sh85136886
Transcendentalism http://id.loc.gov/authorities/subjects/sh85136885 (YSOn transsendentalismi linkattu tähän)

**Comment by ilona-x** [comment]
Ranskassa ovat ratkaisseet näin:

Topic :	**Philosophie transcendantale** https://data.bnf.fr/en/11979829/philosophie_transcendantale/
Variant subject headings :	
Idéalisme transcendantal
Transcendantale, Philosophie
Transcendantalisme (philosophie européenne)

Topic : **Transcendantalisme (philosophie américaine)** https://data.bnf.fr/en/11946172/transcendantalisme__philosophie_americaine_/
Variant subject headings :	
Mouvement transcendantaliste
Transcendantalisme (mouvement littéraire)
Trascendentalismo (italien)

**Comment by AuHo22** [comment]
Saksan kansalliskirjastossa käsittein: 

Transzendentalphilosophie
ja
Transzendentalismus (jota asiasanatietueessa on tarkennettu maantieteellisen käsitteen avulla: Neuengland)

Voisin ehdottaa jakoa:  transsendentaalifilosofia ja toisaalta: transsendentalismi (Uusi-Englanti) tai amerikkalainen transsendentalismi

Näitähän on varmaankin käytetty sekaisin, mutta viimeistään nyt olisi hyvä erottaa ja tarkentaa.

**Comment by mirmaid** [comment]
Kun molemmat ovat (ainakin jossain määrin) filosofiaa, olisiko turvallisempaa nimittää _transsendentaaliseksi idealismiksi_ sitä, mikä nyt on transsendentaalifilosofia ja toinen olisi Aulin ehdotuksen mukaan _amerikkalainen transsendentalismi_? Lisäksi määritelmät ja ohjaustermejä.

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään Mirjan ehdotus yllä.

**Comment by mariaforsen** [comment]
Sv.
-transcendentalfilosofi > transcendental idealism 
-transcendentalism > transcendentalism (amerikansk) HT amerikansk transcendentalism
