### ISSUE TITLE
ohjelmistot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9973]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[ohjelmistot](http://www.yso.fi/onto/yso/p11291)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

lisätään tarkenne? Nyt termillä on määritelmä "Kaikki mitä taiteilija, taidelaitos tmns. ohjelmanaan esittää", ja kielivastineet tämän merkityksen mukaiset, mutta termiä on käytetty Melindassa myös tietokoneohjelmistoista

**Perustelut ehdotukselle**

Melinda: esim. haku ohjelmistot & ohjelmistokehitys tuottaa  yli 500 viitettä

**Ehdottajan organisaatio**

kk/il

**Comment by MUUSA-kokous** [comment]
Ehdotetaan tarkennetta "taiteet".

**Comment by mirmaid** [comment]
Toivottavasti ei mene tällaisissa sekaisin: https://melinda.kansalliskirjasto.fi/byid/016297745. Ensimmäiset 100 viitettä sisältää vain taiteita tai tietotekniikkaa, mutta viitteitä kaikkiaan yli 4000. Haku ohjelmistot ja televisio tuo esim. https://melinda.kansalliskirjasto.fi/byid/014409250, https://melinda.kansalliskirjasto.fi/byid/013627500, https://melinda.kansalliskirjasto.fi/byid/000578644. Pitäisikö olla _(taiteet ja media)_ tai _(kulttuuri)_ vai kattaako _(taiteet)_ myös nuo tv-aineistot?

**Comment by YSO-kokous** [comment]
### Päätös
ohjelmistot (taiteet)
ohjelmistot (media) KÄYTÄ ohjelmatarjonta
