### ISSUE TITLE
rumpumusiikki

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9974]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

rumpumusiikki

**Ehdotettu termi ruotsiksi**

trummmusik

**Ehdotettu termi englanniksi**

drum music

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

 [soitinmusiikki](http://www.yso.fi/onto/yso/p1514)

**Ehdotetut temaattiset ryhmät**

 [89 Musiikki](http://www.yso.fi/onto/yso/p26571)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCSH](http://id.loc.gov/authorities/subjects/sh96008214)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://melinda.kansalliskirjasto.fi/byid/001491599

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [rumpumusiikki](http://finto.fi/yse/fi/page/Y509974)

**Comment by MUUSA-kokous** [comment]
Kannatetaan ehdotusta.

**Comment by jarmosaarikko** [comment]
LCSH 
http://id.loc.gov/authorities/subjects/sh96008214 Drum music vai  
http://id.loc.gov/authorities/subjects/sh96008254 Drum set music
