### ISSUE TITLE
meromorfiset funktiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9975]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

meromorfiset funktiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/24505

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [meromorfiset funktiot](http://finto.fi/yse/fi/page/Y509975)

**Comment by jarmosaarikko** [comment]
en: meromorphic function sv: meromorf funktion
Wikidata: http://www.wikidata.org/entity/Q217616
WIkipedia: https://fi.wikipedia.org/wiki/Meromorfinen_funktio

**Comment by ilona-x** [comment]
LCSH: **Functions, Meromorphic** http://id.loc.gov/authorities/subjects/sh85052343

**Comment by mariaforsen** [comment]
Sv. meromorfa funktioner HT meromorfiska funktioner
