### ISSUE TITLE
kokonaiset funktiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9976]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

kokonaiset funktiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/24505

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [kokonaiset funktiot](http://finto.fi/yse/fi/page/Y509976)

**Comment by jarmosaarikko** [comment]
en: entire functions sv: hela funktioner
LCSH http://id.loc.gov/authorities/subjects/sh85052337 Functions, entire
WIkidata: http://www.wikidata.org/entity/Q847600 
Wikipedia: https://fi.wikipedia.org/wiki/Kokonainen_funktio

**Comment by mariaforsen** [comment]
Sv. hela funktioner
