### ISSUE TITLE
jaksolliset funktiot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9977]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

jaksolliset funktiot

**Ehdotettu termi ruotsiksi**

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

-

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

https://erepo.uef.fi/handle/123456789/24505

**Ehdottajan organisaatio**

**Termiehdotus Fintossa:** [jaksolliset funktiot](http://finto.fi/yse/fi/page/Y509977)

**Comment by jarmosaarikko** [comment]
sv: periodisk funktion; en: periodic function  
Wikidata: http://www.wikidata.org/entity/Q184743 YK funktiot
Wikipedia: https://fi.wikipedia.org/wiki/Jaksollinen_funktio

**Comment by ilona-x** [comment]
LCSH: **Periodic functions** http://id.loc.gov/authorities/subjects/sh85099883

**Comment by mariaforsen** [comment]
Sv. periodiska funktioner
