### ISSUE TITLE
Näthat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9978]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

Verkkoviha

**Ehdotettu termi ruotsiksi**

Näthat

**Ehdotettu termi englanniksi**

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

Används i en doktorsavhandling vid Åbo Akademi.

**Ehdotettu yläkäsite YSOssa (LT)**

**Ehdotetut temaattiset ryhmät**

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Karin Sandell: Parasiter och "bättre folk" : affekt i näthat mot det svenska i Finland.

**Ehdottajan organisaatio**

Åbo Akademis bibliotek.
**Termiehdotus Fintossa:** [Näthat](http://finto.fi/yse/fi/page/Y509978)

**Comment by mariaforsen** [comment]
Svenska ämnesord: https://id.kb.se/find?q=n%C3%A4that

Käytetään runsaasti, esim. myös Ylen uutisissa: https://svenska.yle.fi/t/18-153628

Aineistoa Melindassa esim. nämä kirjat:
-Det demokratiska samtalet i en digital tid : så stärker vi motståndskraften mot desinformation, propaganda och näthat : betänkande / av kommittén Nationell satsning på medie- och informationskunnighet och det demokratiska samtalet.
-Den ensamme terroristen? : om lone wolves, näthat och brinnande flyktingförläggningar / Mattias Gardell, Heléne Lööw, Michael Dahlberg-Grundberg.
-Tackla hatet : om näthat och hot : och hur du skyddar dig / Rebecka Bohlin.
-Nätmobbning, näthat och nätkärlek : kunskap och strategier för en bättre vardag på nätet / Elza Dunkels.
-Näthat : rättigheter och möjligheter / Alexandra Sackemark & Mårten Schultz ; med: Mikaela Alderhorn, Sebastian Caicedo Gordh och Johan Rosell.
-Bokmärken : en handbok i att bekämpa näthat genom människorättsfostran.

**Comment by jarmosaarikko** [comment]
Englanniksi  "cyber hate"  KT "cyberhate", "online hate", "cyberbullying" 
- Lähteitä:  https://projects.tuni.fi/cyberhate/, https://nathatshjalpen.se/en/a/what-cyber-hate/, https://nathatshjalpen.se/k/nathat/

RT [vihapuhe](http://www.yso.fi/onto/yso/p24781)

- LCSH:ssa vain "verkkovihapuhe" [Online hate speech](http://id.loc.gov/authorities/subjects/sh2009002821)
- Wikidatassa ei tekona vaan tekijänä: [näthat ~ hater](http://www.wikidata.org/entity/Q5681313)  - suomeksi kaiketi "verkkovihaaja" tms.?

**Comment by mirmaid** [comment]
_Verkkoviha_ tuo kyllä jonkun verran viitteitä Googlella, mutta yleensä käytetty termi on _vihapuhe_. Ainakin nämä olisivat erittäin päällekkäiset, vaikka vihapuhe ei rajaudukaan nettiin (mutta se on kuitenkin se keskeisin foorumi).

Kerran Melindassa.

**Comment by mirmaid** [comment]
Kas, meillä on sanastossa _viharyhmät_ http://www.yso.fi/onto/yso/p22553 :frowning:.

**Comment by YSO-kokous** [comment]
### Päätös
lisätään ohjaustermiksi verkkoviha KÄYTÄ vihapuhe
