### ISSUE TITLE
lingot (aseet)

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9980]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

lingot (aseet)

**Ehdotettu termi ruotsiksi**

slungor

**Ehdotettu termi englanniksi**

slings (weapons)

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tämä heittoase on sekoittunut kuvailussa muihin linkoihin (sentrifugit, lumilingot, pesulingot) joten se tulisi esittää omana käsitteenään.
Eri käsite kuin ritsa (slingshot)

**Ehdotettu yläkäsite YSOssa (LT)**

 [aseet](http://www.yso.fi/onto/yso/p3463)

**Ehdotetut temaattiset ryhmät**

 [67 Sodankäynti. Sotatekniikka. Maanpuolustus. Aseet](http://www.yso.fi/onto/yso/p26575)

**Vaihtoehtoiset termit**

 paimenen linko, shepherd's sling

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Linko (wikipedia)](https://fi.wikipedia.org/wiki/Linko), [Linko (wikidata)](http://www.wikidata.org/entity/Q199771)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

esim. https://melinda.kansalliskirjasto.fi/byid/007154088, https://melinda.kansalliskirjasto.fi/byid/003738401

**Ehdottajan organisaatio**

Kansalliskirjasto/Finto
**Termiehdotus Fintossa:** [lingot (aseet)](http://finto.fi/yse/fi/page/Y509980)

**Comment by mariaforsen** [comment]
Sv. slungor (vapen)

**Comment by mirmaid** [comment]
Olisiko toisen tarkenne (laitteet)?

**Comment by YSO-kokous** [comment]
### Päätös
Otetaan sanastoon lingot (aseet)
Lisätään tarkenne lingot (laitteet)
