### ISSUE TITLE
musiikkiala

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9981]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[musiikkiala](http://www.yso.fi/onto/yso/p11568)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yhdistetään "musiikkiteollisuus"-asiasanaan tai lisätään selitys, mitä näillä asiasanoilla oikeastaan tarkoitetaan.

**Perustelut ehdotukselle**

Asiasanojen tarkka merkitys ja sen myötä käyttötapa on epäselvä, ja esimerkiksi Wikidatassa musiikkiteollisuus ja musiikkiala viittaavat (ainakin ruotsiksi) yhteen ja samaan tarkoitteeseen (https://www.wikidata.org/wiki/Q746359).

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by asormune** [comment]
Termiä musiikkiala on käytetty myös elokuvan kuvailussa: "Olen suomalainen (elokuva : 2019). Tässä musiikkiteollisuus tuntuisi liian suppealta, mielestäni.

**Comment by asormune** [comment]
Keskin kannassa termien käyttö, kaikki aineistolajit:
musiikkiala 97 kpl
musiikkiteollisuus 99 kpl
molemmat 23 kpl

**Comment by mirmaid** [comment]
Nämä määritelmät olisivat varmaan Muusan alaa.

**Comment by mariaforsen** [comment]
https://id.kb.se/find?q=musikindustrin

**Comment by MUUSA-kokous** [comment]
Toimialojen alakäsitteillä ei ole määritelmiä muutenkaan, joten ei koeta tarvetta sellaiselle musiikkialankaan kohdalla. Musiikkiteollisuuden määritelmä on OK.

**Comment by jarmosaarikko** [comment]
LCSH ja WIkidata käsittelevät näitä yhtenä käsitteenä.  YSOssa -ala ja -teollisuus  -tyyppiset käsitteet ovat usein käsitteinä.
Toimialaluokituksessa on useita musiikkiin liittyviä aloja eli ne eivät ole siellä yhtenä "musiikkiala" luokkana (musiikin kustantaminen, vähittäisikauppa, opetus, jne.). 

Musiikkiala voidaan nähdä musiikkitieollisuutta hieman laajempana, mutta päällekkäisenä käsitteenä. Sillä perusteella ne voisi myös yhdistää samaan käsitteeseen. Jälkimmäisessä tapauksessa pitäisi sitten vain päättää kumpi on käytettävä termi ja kumpi ohjaustermi mikä on hankalaa, kun niitä on käytetty suunnilleen yhtä usein.  

Esiintymät Melindassa:  
721  - musiikkiala (yso/fin)
1421 - musiikkiteollisuus (yso/fin) 

Kts muita vastaavia jakoja YSOssa:
elokuva-ala (film sector) vs.  elokuvateollisuus (motion picture industry)
kulttuuriala (culture sector) vs. kulttuuriteollisuus (culture industry)
audiovisuaalinen ala (audiovisual sector)   _[ei aivan sama ero]_ ääniteteollisuus (sound recording industry)
kustannusala (publishing sector)  _[ei aivan sama ero]_  kustannustoiminta (publishing)

**Comment by YSO-kokous** [comment]
### Päätös
Ei yhdistetä. Molemmat käsitteet ovat tarpeellisia. Muusan ehdotuksen mukaan ei lisätä määritelmää musiikkialalle.  Vastaavia jakoja on muillakin aloilla.

**Comment by jtuohini** [comment]
https://github.com/Finto-ehdotus/YSE/issues/11101

**Comment by jtuohini** [comment]
Mutta mihin _musiikkiala_-asiasana sitten täsmälleen ottaen viittaa? Jos se on laajempi kuin _musiikkiteollisuus_, niin jotenkin asia pitäisi tehdä kirkkaaksi niin kuvailijalle kuin tiedonhakijalle. Joten huomautus tarvitaan myös edelliseen asiasanaan!

**Comment by tpalonen** [comment]
Näen näissä osittaisen päällekkäisyyden mutta samalla huomattavan sävyeron, mikä vaikuttaa varmaan siihen kumpaa termiä kirjoittaja aineistossa käyttää, mikä taas vaikuttaa siihen, kumpaa termiä kuvailija käyttää. Musiikkiteollisuus assosioituu enemmän suuriin yrityksiin ja ylipäätään bisnekseen. Pienempien toimijoiden ja ruohonjuuritason yhteydessä tai muusikoiden, levykauppiaiden, äänityöläisten arkea kuvatessa musiikkiteollisuus tuntuisi vieraalta. Vähemmän vieraalta minusta tuntuisi jos bisnesaiheisessa aineistossa musiikkiteollisuuden sijaan käytettäisiin musiikkiala-termiä.

**Comment by mirmaid** [comment]
Tästä on nyt kuitenkin Muusa-ryhmän kannanotto ja siihen perustuva päätös. Keskustelu mahdollisesta yhdistämisestä pitäisi palauttaa Muusalle, mutta onko tullut sellaisia uusia perusteluja, että tähän olisi nyt syytä?

**Comment by jtuohini** [comment]
Jos Muusa voisi sitten kertoa, mikä näiden kahden asiasanan merkitysero on? Ryhmän kommentti "(t)oimialojen alakäsitteillä ei ole määritelmiä muutenkaan, joten ei koeta tarvetta sellaiselle musiikkialankaan kohdalla" on mielestäni ongelman sivuuttamista, koska Muusa on käsittääkseni koko ajan kannattanut termien määrittelemistä tarpeen mukaan, ja tässä jos missä olisi määrittelylle tarvetta. Siis: mikä _musiikkiala_-asiasanan tarkoite?

**Comment by mirmaid** [comment]
Voisiko ajatella, että jos musiikkiteollisuus on "kaikkien teollisesti toimivien elinkeinoelämän haarojen kokonaisuus, jotka osallistuvat musiikin tuottamiseen", niin musiikkiala olisi musiikkitoimiala, ml. musiikkiteollisuuden, mutta myös pienemmät, ei-teollisen mittakaavan toimijat  (vaikka pienemmät musiikkitapahtumat, konsertit, musiikin julkaiseminen muuten kuin levy-yhtiön kautta...kunhan pohdin). Varmasti olennaisin ero näissä yleensä on se, mistä näkökulmasta asiaa katsotaan (esim. musiikkialan palkkakehitys tai työolot keikkailevan muusikon näkökulmasta eivät välttämättä ole musiikkiteollisuuden aluetta (?)).

Mutta toki ilahdun, jos määritelmä saadaan Muusalta.

**Comment by jtuohini** [comment]
Lukeutuvatko musiikkialaan mm. musiikin opettaminen (työ konservatorioissa yms.), tutkiminen (ammattilaiset esim. yliopistoissa kuukausipalkkalaisina tai apurahatutkijoina), ja arvostelu (sanomalehtien kulttuuritoimitus)? Nämä ja vastaavat ovat kaiketikin toimialaan kuuluvia ilmiöitä, mutta eivät missään nimessä teollisuutta?

**Comment by YSO-kokous** [comment]
**Päätös**

Kokoukseen osallistujien enemmistön päätöksellä päätettiin, ettei lisätä määritelmiä. Vastaavanlaisia pareja on jo useita, joten määritelmät eivät ole tässäkään tarpeellisia.

**Comment by jtuohini** [comment]
Määritelmät olisivat tarpeen muissakin, joten perustelu jättää epäselvä asiasana määrittelemättä on hieman ontuva.

**Comment by tpalonen** [comment]
YSO-ylläpidolla ei ole resursseja laatia käsitteille määritelmiä tapauksissa, joissa YSO-kokouksen enemmistö on päättänyt, että määritelmää ei tarvita.
