### ISSUE TITLE
visailukysymykset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9982]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[visailukysymykset](http://www.yso.fi/onto/yso/p14022)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarvitaan myös SLM-sanastoon

**Perustelut ehdotukselle**

Aineiston kuvailu, esim. Tosi hukassa? : viikkovisa / Jari Kurittu. Nyt laitettu kenttään 650, mutta oikea kenttä olisi 655. 

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
Hyväksytään SLM-sanastoon / SLM-kokous 19.4.2022 
Ohjaustermiksi tietokilpailukysymykset
Sijainti hierarkiassa?

**Comment by mirmaid** [comment]
Voiko olla LT pelit? Jos ei, niin sitten varmaan RT pelit ja hierarkiassa ylätasolle, kuten postikortit ym.

**Comment by mariaforsen** [comment]
Mieluummin RT pelit, koska jos kyseessä on kirja, sitä on vaikeaa mieltää peliksi.

**Comment by mirmaid** [comment]
YK ei-fiktiivinen aineisto, RT pelit
