### ISSUE TITLE
varsi

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9983]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[varsi](http://www.yso.fi/onto/yso/p12029)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaan?

**Perustelut ehdotukselle**

Ruotsiksi ja englanniksi rajattu kasvitieteeseen, mutta esim. Finna-kuvat aivan muita asioita. 

**Ehdottajan organisaatio**

ALLFO

**Comment by jarmosaarikko** [comment]
**Melindassa** 11 kertaa, joista vain yksi ei ole kasvin varsi (lapion varsi).

Sopisiko tarkenteeksi **varsi (kasvinosat)** tai **varsi (kasvitiede)**?
LCSH vastine on [Stems (Botany)](http://id.loc.gov/authorities/subjects/sh85127927)

YSOssa nyt: [kyynärvarret](https://finto.fi/yso/fi/page/p25425), [käsivarret](https://finto.fi/yso/fi/page/p38345), [olkavarret](https://finto.fi/yso/fi/page/p11539), [tienvarret](https://finto.fi/yso/fi/page/p9785), [äänivarret](https://finto.fi/yso/fi/page/p27929), [maavarsi](https://finto.fi/yso/fi/page/p25546)

Jos varsi-käsitteellä on kuvttu muutakin, niille tarvitaan sitten varmaan eri käsite.
- robottikäsivarsi, käsivarsirobotti, - tämä käsite esiintyy jo useissa julkaisuissa ja näitä on käytössä esim. Oodi-kirjastossa!

### varsia Finnan kuvissa  
- **työkalun varsia** "lapion varsi", "kirveen varsi", "viikatteen varsi", "moukarin varsi", "keksin varsi", "harjan varsi", "petkeleen varsi", "haravan varsi", "rintaporan varsi", "vasaran varsi", "viilan varsi", "meisselin varsi", 
- **aseita** "keihään varsi", "jalkajousen varsi", "hilparin varsi"
- **koneita** ""nosturin varsi", "paalutuskoneen varsi", "juntan varsi", "pumpun varsi"
- **muiden esineiden osia** "lusikan varsi", "kauhan varsi", "survimen varsi", "vispilan varsi"; "kaapimen varsi", "mustekynän varsi", "jalkineen varsi", "piipun varsi", "lampun varsi",  "valtikan varsi",  "peilin varsi", "banderollin varsi"
- **paikkoja** "puron varsi", "ojan varsi", "kadun varsi", "radan varsi", "aidan varsi"

**Comment by mirmaid** [comment]
Kasvinosat on jo tarkenteena kolmella alakäsitteellään.

**Comment by mirmaid** [comment]
Ratkaisuehdotus: lisätään tarkenne (kasvinosat)
