### ISSUE TITLE
sublimaatio

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9984]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[sublimaatio](http://www.yso.fi/onto/yso/p21835)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Tarkennetaanko?

**Perustelut ehdotukselle**

Ruotsiksi ja englanniksi rajattu psykologiaan, mutta Melindassa käytetty muistakin asioista. 

**Ehdottajan organisaatio**

ALLFO

**Comment by mirmaid** [comment]
No on kyllä mielenkiintoinen setti :sweat_smile:. _Härmistyminen_ ei taida oikein toimia tulostuksen yhteydessä, vaikka siitä todella on kysymys...

**Comment by mirmaid** [comment]
Ratkaisuehdotus: _sublimaatio (psykologia)_ ja lisäksi _sublimaatiotulostus_?

**Comment by mariaforsen** [comment]
Sv. sublimering (utskrift)
