### ISSUE TITLE
latvusto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9985]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[latvusto](http://www.yso.fi/onto/yso/p9480)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko nyt virheellisesti YK kasvinosat ja ruotsiksikin termi sen mukaan?

**Perustelut ehdotukselle**

Onko tämä kuitenkin "Puiden latvojen, oksien ja lehtien muodostama kokonaisuus." / https://termipankki.fi/tepa/fi/haku/latvusto Ruotsiksi muutetaan siinä tapauksessa > krontak? 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
Huom. sanastossa myös latvus.
https://www.kielitoimistonsanakirja.fi/#/latvusto?searchMode=all

**Comment by jarmosaarikko** [comment]
On  tuo korjattava:
- latvus on yhden puun osa eli kasvinosa  en: tree crown tai crown (botany) - **trädkrona**
- latvusto on monien puiden (metsikön) latvusten mudostama  metsän ylin kasvustokerros. en: forest canopy
 ruotsiksi   [krontak](https://tieteentermipankki.fi/wiki/Nimitys:kronverk) (Tieteen termipankki) tai  [kronverk](https://mot.kielikone.fi/mot/endic/netmot.exe) (EnDic)

**Comment by mariaforsen** [comment]
Latvus on ollut trädtopp. Entä suomeksi latva/puunlatva ("kasvin, tav. puun ylin osa") ? Onko se mahdollisesti erillinen termi vai ohjaustermi? Vrt. latvus="puun tm. (latva)oksisto" https://www.kielitoimistonsanakirja.fi/#/latvus?searchMode=all

**Comment by mirmaid** [comment]
^ Edes AFOssa ei ole latvaa erikseen, joten ei varmaan ole tarpeen?

**Comment by mirmaid** [comment]
Ratkaisuehdotus: korjataan hierarkia ja ruotsinkielinen termimuoto.
