### ISSUE TITLE
assyrialaiset

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9988]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[assyrialaiset](http://www.yso.fi/onto/yso/p19470)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Yläkäsitteen muutos: muinaiskansat -> väestöryhmään liittyvä rooli. Tai nykyiselle assyrialaiselle pitää tehdä oma käsite. 

**Perustelut ehdotukselle**

Maailmassa on nykyään yhteensä 3,3 miljoonaa assyrialaista. Slaavilaisessa kirjastossa on kirjoja, jotka käsittelevät assyrialaisia Venäjällä 1800-1900-luvulla. YSO:n käsite assyrialaiset kuuluu muinaiskansat ryhmään, eikä sovi kuvailemaan nykyajan assyrialaisia. 

**Ehdottajan organisaatio**

Kansalliskirjasto

**Comment by jarmosaarikko** [comment]
LCSH  - **[Assyrians](http://id.loc.gov/authorities/subjects/sh85008832)** - General Notes: Here are entered works on speakers of the Modern Syriac language.
- tämä on linkattu Wikidatassa käsitteeseen 	[Assyrialaiskristityt - Assyrian people](http://www.wikidata.org/entity/Q377085)  - Christian ethnic group indigenous to Mesopotamia
- Wikidatassa erikseen [Assyrians](http://www.wikidata.org/entity/Q745718) - ancient people in Mesopotamia

Tällä perusteella jälkimmäinen vaihtoehto eli kaksi eri käsitettä. 
- https://fi.wikipedia.org/wiki/Assyrialaiset_(kansa)
- https://en.wikipedia.org/wiki/Assyrian_people
- https://en.wikipedia.org/wiki/History_of_the_Assyrians  (muinaiskansa)

**Comment by mirmaid** [comment]
https://en.wikipedia.org/wiki/Assyrian_people - tämän mukaan kyse ei ehkä kuitenkaan olisi selkeästi kahdesta eri käsitteestä, vaan historiallisesta jatkumosta (?).

**Comment by mariaforsen** [comment]
SAOssa vain yksi käsite: https://id.kb.se/find?q=assyrier Mutta sanakirjoissa kaksi merkitystä: https://svenska.se/tre/?sok=assyrier&pz=1 Eli muinaiskansa vs. kristitty vähemmistö Syyriasta tms. maista.

**Comment by mirmaid** [comment]
Modern Assyrians are [Syriac Christians](https://en.wikipedia.org/wiki/Syriac_Christianity) who [claim descent from Assyria](https://en.wikipedia.org/wiki/Assyrian_continuity), one of the oldest civilizations in the world, dating back to 2500 BC in ancient [Mesopotamia](https://en.wikipedia.org/wiki/Mesopotamia).

https://en.wikipedia.org/wiki/Assyrian_people#History - onko jossakin lähteessä mainittu, että olisi jokin selkeä katkos (muinaiskansa häviää tms.)? Tämän wikipedian laajan historiaosuuden perusteella vaikuttaa koko ajan olevan kyse samasta kansasta. Vielä laajempaa erillistä sivua en ole ehtinyt lukea, mutta kyllä historia siinäkin näyttäisi jatkuvan nykypäivään saakka: https://en.wikipedia.org/wiki/History_of_the_Assyrians.

**Comment by YSO-kokous** [comment]
### Päätös
Todettiin, että nykyiset assyrialaiset ovat jatkumoa aikaisemmilla.
Korjataan hierarkia.
