### ISSUE TITLE
opetusaineisto

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9989]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[opetusaineisto](http://www.yso.fi/onto/yso/p12049)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Onko mahdollista selkeyttää? Olisiko ohjaustermi opetusmateriaali?

**Perustelut ehdotukselle**

OKSA: "opetusmateriaali sv undervisningsmaterial; ~ lärarens material en teaching material; instructional material määritelmä aineisto, jota opettaja käyttää opetuksen (1) yhteydessä tai jonka avulla opettaminen tapahtuu huomautus Opettajan käyttämä opetusmateriaali voi poiketa oppijan käyttämästä oppimateriaalista esim. siten, että edellinen sisältää tehtävien ratkaisut." YSOssa on nyt useita (osittain päällekkäisiä?) termejä: opetusvälineet = undervisningsmaterial, opetusaineisto = läromaterial, oppimateriaali = läromedel. Nämä termit eivät nyt ole johdonmukaisia, ainakaan ruotsiksi. Onko mahdollista selkeyttää esim. kuten OKSA-sanastossa? 

**Ehdottajan organisaatio**

ALLFO

**Comment by mariaforsen** [comment]
OKSA: https://julkaisut.valtioneuvosto.fi/bitstream/handle/10024/162845/OKM_2021_10.pdf
OKSAssa: oppimateriaali sv studiematerial; ~ elevens material
en learning material; study material
määritelmä: aineisto, jota oppija käyttää opetuksen (1) yhteydessä tai jonka avulla oppiminen tapahtuu

Jos YSOssa olisi nämä kaksi käsitettä määriteltynä samalla tavalla kuin OKSAssa ja sen lisäksi opetusvälineet määriteltynä: "esine tai laite, jolla oppimateriaalia esitetään" /https://tieteentermipankki.fi/wiki/Nimitys:opetusv%C3%A4line niin olisi mahdollista saada johdonmukaiset vastineet ruotsiksikin.

**Comment by mirmaid** [comment]
_Opetusväline_ on mielestäni suomeksi ihan selkeä: jokin konkreettinen opetuksessa käytettävä "työkalu" (älytaulu, mutta voisi olla myös esim. kirja). 

_Oppimateriaali_ on runsaasti käytetty, _opetusaineisto_ vähemmän. Molemmat viittaavat sisältöihin, määritelmät on varmaan mahdollista lisätä, mutta kyllä nämä mielestäni myös ovat osittain päällekkäisiä. Opetusaineisto on suunnattu opettajalle, mutta sen voi mieltää myös olevan osa oppimateriaalia. https://shop.edita.fi/tuote/nyckel-8-digitaalinen-opetusaineisto-ops-2016

Kielitoimiston sanakirja: oppimateriaali: opetuksessa käytettävät oppi- ja työkirjat, videoelokuvat, äänitteet yms., opetusmateriaali.

**Comment by mirmaid** [comment]
Kuulostaisi ehkä, että _undervisningsmaterial_ sopisi paremmin vastineeksi _opetusaineistolle_?

**Comment by ilona-x** [comment]
YSOssa nyt opetusmateriaali KÄYTÄ oppimateriaali. Pitäisikö opetusmateriaalin kuitenkin olla ohjaustermi tähän opetusaineisto-termiin? Tai ehkä jopa mieluummin opetusmateriaali KT opetusaineisto?

fi        opetusmateriaali
sv       undervisningsmaterial; ~ lärarens material
en      teaching material; instructional material

määritelmä
aineisto, jota opettaja käyttää opetuksen (1) yhteydessä tai jonka avulla opettaminen tapahtuu

huomautus
Opettajan käyttämä opetusmateriaali voi poiketa oppijan käyttämästä oppimateriaalista esim. siten, että edellinen sisältää tehtävien ratkaisut.

Käsitteen tunnus: c1073
Lähde: Opetus- ja koulutussanasto, 2. laitos (OKM, 2021:10) 
https://termipankki.fi/tepa/fi/haku/opetusmateriaali


fi        oppimateriaali
sv       studiematerial; ~ elevens material
en      learning material; study material

määritelmä
aineisto, jota oppija käyttää opetuksen (1) yhteydessä tai jonka avulla oppiminen tapahtuu

huomautus
Oppimateriaaleja voivat olla kirjat ja muut painotuotteet, audiovisuaaliset aineistot kuten televisio-ohjelmat sekä mm. erilaiset sähköiset aineistot.
Kullakin opintojaksolla käytettävä oppimateriaali voidaan mainita opetustarjontatietojen yhteydessä (kohdassa ”kurssin kirjallisuus”).

Käsitteen tunnus: c761
Luokitus:  yleinen/yhteinen
	  
Lähde: Opetus- ja koulutussanasto, 2. laitos (OKM, 2021:10)
https://termipankki.fi/tepa/fi/haku/oppimateriaali

**Comment by mariaforsen** [comment]
Mirjan kysymykseen, kyllä, undervisningsmaterial olisi parempi, mutta vain jos siihen ohjataan myös opetusmateriaali, ks. OKSA. Nyt on kuitenkin opetusmateriaali KÄYTÄ oppimateriaali, mikä on mielestäni hyvin ongelmallista, eikä esim. OKSAn mukaista. 

Kannatan yllä ehdotettua ratkaisua eli opetusaineisto KÄYTÄ opetusmateriaali, kuten OKSAssakin. Ja myös vastaavia määritelmiä, sen jälkeen ongelma olisi ratkaistavissa myös ruotsiksi.

**Comment by mirmaid** [comment]
Eli muutosehdotus olisi opetusmateriaali KÄ/KT opetusaineisto? Ei muita muutoksia?

**Comment by YSO-kokous** [comment]
#### Päätös
vaihdetaan päätermi

**Comment by mariaforsen** [comment]
Voisiko vielä lisätä määritelmiä, mm. jotta saadaan kieliversiot selkeästi täsmäämään myös käytössä? Esim. Oksan mukaiset: 

opetusmateriaali: aineisto, jota opettaja käyttää opetuksen yhteydessä tai jonka avulla opettaminen tapahtuu

oppimateriaali: aineisto, jota oppija käyttää opetuksen yhteydessä tai jonka avulla oppiminen tapahtuu

opetusvälineet: esine tai laite, jota käytetään opetukusessa? tms.

Ainakin ruotsiksi tarvitaan termimuutosten lisäksi selkeät määritelmät, koska nämä termit menevät helposti sekaisin, ja tarkoitushan on että ne käytettäisiin johdonmukaisesti ja eri merkityksissä.

**Comment by mariaforsen** [comment]
Opetusmateriaali tarvitaan myös SLM-sanastoon (+määritelmät).
