### ISSUE TITLE
kesäasukkaat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9990]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kesäasukkaat](http://www.yso.fi/onto/yso/p11250)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

KT mökkiläiset

**Perustelut ehdotukselle**

-

**Ehdottajan organisaatio**

**Comment by ilona-x** [comment]
pitäisiköhän samalla lisätä mökkiläiset ohjaustermiksi myös termille vapaa-ajan asukkaat (http://www.yso.fi/onto/yso/p27411)?
