### ISSUE TITLE
gelsoliini

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9992]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

gelsoliini

**Ehdotettu termi ruotsiksi**

gelsolin

**Ehdotettu termi englanniksi**

gelsolin

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

tarve kuvailusssa
Melinda x 3

**Ehdotettu yläkäsite YSOssa (LT)**

 [proteiinit](http://www.yso.fi/onto/yso/p4332)

**Ehdotetut temaattiset ryhmät**

 [15 Biologia. Mikrobiologia. Perinnöllisyystiede. Genetiikka. Antropologia](http://www.yso.fi/onto/yso/p26579), [48 Lääketiede. Anatomia. Fysiologia. Patologia. Tautioppi. Psykiatria. Hammaslääketiede. Eläinlääketiede. Farmasia. Kauneudenhoito. Hoitomenetelmät](http://www.yso.fi/onto/yso/p26550)

**Vaihtoehtoiset termit**

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [Wikipedia ](https://en.wikipedia.org/wiki/Gelsolin_(cellular)), [FinMeSH](http://www.yso.fi/onto/mesh/D018260)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

Amyloid angiopathy in hereditary gelsolin amyloidosis

**Ehdottajan organisaatio**

kk/il
**Termiehdotus Fintossa:** [gelsoliini](http://finto.fi/yse/fi/page/Y509992)

**Comment by jarmosaarikko** [comment]
Wikidata: http://www.wikidata.org/entity/Q3098700
