### ISSUE TITLE
alaistaidot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9994]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[alaistaidot](http://www.yso.fi/onto/yso/p23892)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Nykyään käytetään mieluummin "työyhteisötaidot". 

**Perustelut ehdotukselle**

Vanhentunut käsite. Ei ole muissakaan sanakirjoissa. 

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
_Työyhteisötaidot_ on myös YSOssa, samoin _esimiestaidot_.

_Alaistaidot_ on otettu sanastoon 2010 ja käytetty Melindassa 86 kertaa. _Työyhteisötaidot_ on otettu 2011 ja käytetty 392 kertaa. Näillä varmaan pitäisi olla jokin suhde, jos molemmat jätetään.

**Comment by mariaforsen** [comment]
Kannatan poistoa/yhdistämistä. Termiä on yritetty kääntää sv. organisatoriskt engagemang, eng. organisational citizenship behaviour, mutta tämä ei ole ollenkaan sama asia. 

Alaistaidot voisi mahdollisesti olla medarbetarkompetens, mutta se on vastineea työyhteisötaidoille. Ks. https://www.sprakbruk.fi/-/medarbetarkompetens 

Ruotsiksi ei nähdä järkevänä korostaa "alaisuutta" eikä sellainen kuuluu samalla tavalla ruotsalaiseen työkulttuuriin, se lienee syy miksei vastaavaa termiä ole. Ks. myös https://yle.fi/uutiset/3-9193835

**Comment by fantsby-m** [comment]
Yhdistäminen olisi varmasti hyvä ratkaisu, alaistaidot pois.

**Comment by mirmaid** [comment]
Yhdistäminen saanut kannatusta.
