### ISSUE TITLE
kustantajat

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9995]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[kustantajat](http://www.yso.fi/onto/yso/p7239)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Uusi ohjaustermi kirjankustantajat

**Perustelut ehdotukselle**

Synonymi, sanastossa myös erikseen lehtikustantajat jne.

**Ehdottajan organisaatio**

**Comment by mariaforsen** [comment]
Vastaava on jo ruotsiksi, bokförläggare ANV förlag

**Comment by YSO-kokous** [comment]
### Päätös
lisätään ohjaustermi ruotsinkielisen mukaan
kirjankustantajat KÄYTÄ kustantajat
kustantajat (lehdet) KÄYTÄ lehtikustantajat
