### ISSUE TITLE
stop motion -elokuvat [SLM + YSO]

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9996]
**Käsitteen tyyppi**

CONCEPT

**Ehdotettu termi suomeksi**

stop motion -elokuvat [SLM + YSO]

**Ehdotettu termi ruotsiksi**

stop motion-filmer

**Ehdotettu termi englanniksi**

stop-motion animation films

**Tarkoitusta täsmentävä selite**

**Perustelut ehdotukselle**

. .

**Ehdotettu yläkäsite YSOssa (LT)**

 [animaatioelokuvat](http://www.yso.fi/onto/yso/p13637)

**Ehdotetut temaattiset ryhmät**

 [96 Valokuvaus. Elokuva](http://www.yso.fi/onto/yso/p26534)

**Vaihtoehtoiset termit**

 frame-by-frame animation films, object animation films, stop-action animation films, stop-motion animated films

**Alakäsitteet (RT)**

**Assosiatiiviset (RT)**

**Vastaava käsite muussa sanastossa**

 [LCGFT](     http://id.loc.gov/authorities/genreForms/gf2011026615)

**Aineisto jonka kuvailussa käsitettä tarvitaan (esim. nimeke tai URL)**

. .

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto
**Termiehdotus Fintossa:** [stop motion -elokuvat [SLM + YSO]](http://finto.fi/yse/fi/page/Y509996)

**Comment by jtuohini** [comment]
Ja tälle ST-suhteiseksi [**_vaha-animaatiot_**](https://github.com/Finto-ehdotus/YSE/issues/3675) tai [**_vaha-animaatioelokuvat_**](https://github.com/Finto-ehdotus/YSE/issues/1931).

LCSH-siltaus YSO-termille: [**Stop-motion animation films**](http://id.loc.gov/authorities/subjects/sh2010000786).

**Comment by mirmaid** [comment]
Hyväksytään muodossa stop motion -animaatiot.

**Comment by mirmaid** [comment]
YSO?

**Comment by mariaforsen** [comment]
Sv. stop motion-animationer

**Comment by YSO-kokous** [comment]
**Päätös**

Hyväksytään.
