### ISSUE TITLE
teosluettelot

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9997]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[teosluettelot](http://www.yso.fi/onto/yso/p22719)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Lisätään määritelmä ja käyttöohje, varsinkin SLM:n puolelle.

**Perustelut ehdotukselle**

Termin käyttä tällä hetkellä horjuvaa.

**Ehdottajan organisaatio**

Helsingin yliopiston kirjasto

**Comment by AuHo22** [comment]
Fennican sisällönkuvailuohje tällä hetkellä: teosluettelot ->
Termiä teosluettelot käytetään, kun kyseessä on taiteilijan tärkeimmän tuotannon kattavasti käsittävä luettelo. Jos on kysymys esim. taidemaalarin, graafikon tms. teosluettelosta, asiasanaksi laitetaan myös kuvataitelijat. Genretermiä teosluettelot ei käytetä elokuva- tai teatteriohjaajien ohjaustöiden luetteloista.

**Comment by mirmaid** [comment]
Ohjausterminä catalogue raisonnét. Sanastossa on lisäksi (tämän alakäsitteenä) _säveltäjien teosluettelot_ ja _temaattiset luettelot_. Jos tämä halutaan rajata kuvataiteilijoihin, hierarkia pitää muuttaa. 

Käytetty myös: arkkitehdit, muotoilijat, ohjaajat, lisäksi luetteloista, joissa ei ole kyse vain yhden henkilön teoksista (näissä myös musiikkia, kirjallisuutta).

Entäpä tällainen: https://melinda.kansalliskirjasto.fi/byid/000302121

**Comment by mirmaid** [comment]
Henkilöbibliografiat YK teosluettelot

Hyväksytään catalogue raisonnét, Jaakko & Ilkka laativat määritelmän

**Comment by jtuohini** [comment]
LCGFT-vastine: [**Catalogues raisonnés**](http://id.loc.gov/authorities/genreForms/gf2014026058).
