### ISSUE TITLE
verkkoseminaarit

### ISSUE THREAD

**Issue by Finto-ehdotus** [Finto-ehdotus/YSE#9999]
**Käsitteen tyyppi**

Muutos olemassa olevaan käsitteeseen

**prefabel**

[verkkoseminaarit](http://www.yso.fi/onto/yso/p28463)

**Tila**

Käsittelyssä

**Ehdotettu muutos**

Verkkoseminaarit- webinaarit ovat yhä enemmän verkko-opiskelussa toteutettavaa yhteisöllistä reaaliaikaista verkko-opetusta. Tässä terminologiassa on näkyvillä vain perinteinen kokousajattelu tai seminaareihin kytkeytyvä luento-ajattelu. 

**Perustelut ehdotukselle**

ks. yllä

**Ehdottajan organisaatio**

**Comment by mirmaid** [comment]
Millaista muutosta termistöön toivottaisiin? Ei varsinaista ehdotusta...

**Comment by YSO-kokous** [comment]
### Päätös
Ei muutosta
